### ISSUE TITLE
Migrate fails 

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#10008]
## Current Behavior
When running `yarn dlx nx migrate latest` the process fails with the following message

```ts
 ERROR  The migrate command failed.
Command failed: yarn add -W @nrwl/workspace@latest
```

## Expected Behavior

It should work.

### Failure Logs

```ts
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest

 ERROR  The migrate command failed.

Command failed: yarn add -W @nrwl/workspace@latest
```

### Environment

   Node : 16.14.0
   OS   : linux x64
   yarn : 3.0.2
   
   nx : 13.9.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.9.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.9.5
   @nrwl/eslint-plugin-nx : 13.9.5
   @nrwl/express : Not Found
   @nrwl/jest : 13.9.5
   @nrwl/js : 13.9.5
   @nrwl/linter : 13.9.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.9.5
   @nrwl/react-native : Not Found
   @nrwl/schematics : 8.12.11
   @nrwl/storybook : 13.9.5
   @nrwl/web : 13.9.5
   @nrwl/workspace : 13.9.5
   typescript : 4.3.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

**Comment by LuckeeDev** [comment]
I'm getting a similar error:
```
 ERROR  The migrate command failed.

Command failed: yarn add -W @nrwl/workspace@14.0.3
warning package.json: No license field
warning No license field
error An unexpected error occurred: "EPERM: operation not permitted, unlink 'C:\\Users\\USERNAME\\AppData\\Local\\Yarn\\Cache\\v6\\npm-caniuse-lite-1.0.30001332-39476d3aa8d83ea76359c70302eafdd4a1d727dd-integrity\\node_modules\\caniuse-lite\\.yarn-tarball.tgz'".
```

**Comment by l1qu1d** [comment]
Duplicate of @BigForNothing comment on issue: [#2386](https://github.com/nrwl/nx/issues/2386#issuecomment-1079961901). A workaround that has been working for me is to rerun the command again to get it to progress.

The command I run is: ```yarn nx migrate latest```.

I use Yarn v3 with ```nodeLinker: node-modules``` in ```.yarnrc.yml``` A.k.a. not using Plug'n'Play.

**Comment by nemonemi** [comment]
2 weeks ago I've managed to run `nx migrate`, and now I cannot due to this error. Re-running it yielded no progress in my case.

**Comment by MrChrisRodriguez** [comment]
Two things:
- You may want to try upgrading one step at a time instead of all the way to latest `yarn nx migrate next`
- Is there a reason for running the migration in a temporary environment (`dlx`)? If not, drop the `dlx`.

**Comment by madipta** [comment]
I am having similar problem,,


**Command:**
  `npx nx migrate latest` / `yarn nx migrate latest` (I tried both)
  I also tried delete node_modules folder and yarn cache clean --all


**Error Messages:**
Command failed: yarn add -W @nrwl/cypress@14.1.4
warning package.json: No license field
warning No license field
error https://registry.yarnpkg.com/@nrwl/cypress/-/cypress-14.1.4.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "EEXIST: file already exists, mkdir 'C:\\Users\\pipiz\\AppData\\Local\\Yarn\\Cache\\v6\\npm-@nrwl-cypress-14.1.4-7ac38ead60afee62e1d253f958bba7f575e2b698-integrity\\node_modules\\@nrwl\\cypress\\src\\migrations\\update-9-4-0'"


**Environment:**
  Node : 16.13.1
  OS   : win32 x64
  yarn : 1.22.18
  nx : 13.2.2
  @nrwl/angular : undefined
  @nrwl/cli : 13.2.2
  @nrwl/cypress : 13.2.2
  @nrwl/devkit : 13.2.2
  @nrwl/eslint-plugin-nx : 13.2.2
  @nrwl/express : undefined
  @nrwl/jest : 13.2.2
  @nrwl/linter : 13.2.2
  @nrwl/nest : 13.2.2
  @nrwl/next : undefined
  @nrwl/node : 13.2.2
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.2.2
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.2
  @nrwl/web : 13.2.2
  @nrwl/workspace : 13.2.2
  @nrwl/storybook : 13.2.2
  @nrwl/gatsby : undefined
  typescript : 4.3.5
  rxjs : 7.4.0

**Comment by nemonemi** [comment]
> Two things:
> 
> * You may want to try upgrading one step at a time instead of all the way to latest `yarn nx migrate next`
> * Is there a reason for running the migration in a temporary environment (`dlx`)? If not, drop the `dlx`.

No reason, I've tried also with just `yarn nx migrate 13.10.3` and I get the same result.
What is `-W`?

**Comment by madipta** [comment]
unfortunately still error with latest version 14.1.5

**Comment by atsjo** [comment]
The same started happening to me on every update since v14. Was hoping it would go away, but still the same on 14.1.7. I also noticed that nx seems to fetch the @nrwl packages twice during nx migrate.... Tried many workarounds, cleaning yarn cache removing node modules etc, but usually ends up upgrading all packages using yarn first, so the updated @nrwl packages are present in the cache, and then reverting packages.json and running yarn again. THEN it usually works for me to run nx migrate....

Typical output on error below:
Fetching meta data about packages.
It may take a few minutes.
Fetching nx@14.1.7
Fetching nx@latest
Fetching @nrwl/js@14.1.7
Fetching @nrwl/cypress@14.1.7
Fetching @nrwl/linter@14.1.7
Fetching @nrwl/workspace@14.1.7
Fetching @nrwl/angular@14.1.7
Fetching @nrwl/jest@14.1.7
Fetching @nrwl/js@14.1.7
Fetching @nrwl/cypress@14.1.7
Fetching @nrwl/angular@14.1.7
Fetching @nrwl/workspace@14.1.7
Fetching @nrwl/jest@14.1.7
Fetching @nrwl/linter@14.1.7

 ERROR  The migrate command failed.

Command failed: yarn add -W @nrwl/jest@14.1.7
warning package.json: No license field
warning No license field
error https://registry.yarnpkg.com/@nrwl/devkit/-/devkit-14.1.7.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, stat 'C:\\Users\\atles\\AppData\\Local\\Yarn\\Cache\\v6\\npm-@nrwl-devkit-14.1.7-7a253f41b936d611a11633438d77a138445c8245-integrity\\node_modules\\@nrwl\\devkit\\LICENSE'"

**Comment by madipta** [comment]
still error on 14.2.4

**Comment by DmitryEfimenko** [comment]
still error on 14.3.6

After running it 3 times the error went away. However, the diff of `package.json` showed the line containing `"dependencies": {` removed. So the JSON would be invalid. Not a big deal - I manually re-added it, but I almost missed it and I'm sure people will

---

Also, the line 
> `"@angular/compiler-cli": "~13.3.0",`

got replaced with:

>"@anu4a0/2ompiler-cli": "14.0.2",

---
In addition, I had some elf cli and commitizen configurations in the package.json. They were left intact. However, at the very end this got added:
```json
eat/elf-cli-ng"
     ]
    }
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  }
}
     ]
    }
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  }
}
```
which I also manually removed.

**Comment by l1qu1d** [comment]
Is anyone still having this issue? If not this should be closed. I noticed this hasn't happened to me since ```NX 14.5.X``` and using ```Yarn 3.2.2```.

**Comment by madipta** [comment]
> Is anyone still having this issue? If not this should be closed. I noticed this hasn't happened to me since `NX 14.5.X` and using `Yarn 3.2.2`.

hi, I have successful migrate to 14.5.6 without error warning (Thanks to Nx Team)

but there is an issue on react-router that i have to fix manually 

> { path: string; exact: true; render: () => Element; }' is not assignable to type 'IntrinsicAttributes & (PathRouteProps | LayoutRouteProps | IndexRouteProps)'.
  Property 'exact' does not exist on type 'IntrinsicAttributes & (PathRouteProps | LayoutRouteProps | IndexRouteProps)

Node : 14.20.0
OS : win32 x64
yarn : 1.22.9

**Comment by nemonemi** [comment]
I am still having this same issue, and I'm unable to get off from the version `"@nrwl/cli": "13.9.5"`.
Whatever I try, I get the `Command failed: yarn add -W @nrwl/workspace@next`.

Node : 16.14.0
OS : Ubuntu
yarn : 3.2.3

**Comment by kenatwex** [comment]
My Nx footprint has gone south...

cannot even create any kind of library

the builds fail right out of the box

this is not good

Nx is coming apart before us in the field

**Comment by nemonemi** [comment]
I have managed to get back on the latest version updating train.
The way I went about it was that I updated all the NX versions in my package.json manually, and then the migrator had no longer issues keeping up with the newer versions.

**Comment by dennisluitwieler** [comment]
Unfortunately still issues here.

We're running 14.5.10 and want to upgrade to the latest in 14.x (currently 14.8.6). We see that the latest 14.x has been labelled as 'previous' so I would have expected this to work:

nx migrate previous

But this doesn't do anything, the CLI says there are no migrations and also package.json has not been updated.

nx migrate@nrwl/workspace@previous 

Seems to start doing something, but after a couple of minutes comes back with an error 'No matching version found for @nrwl/workspace@0.0.0'

**Comment by nemonemi** [comment]
@dennisluitwieler, I would say this is another issue, which does not directly match to this one. Please create a separate issue to get better support.
