### ISSUE TITLE
WIth version 14.0.3, Using Nx Core Without Plugins tutorial fails on step 'Creating Second NPM Package and Enabling Yarn Workspaces'

### ISSUE THREAD

**Issue by jlister** [nrwl/nx#10013]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[Enter the URL or documentation section here.](https://nx.dev/getting-started/nx-core)

### Additional context or description

After running the command
`nx g npm-package complex`

the tutorial says running `nx test complex` you should give an error `@myorg/simple cannot be resolved`.  With nx version 14.0.3 I see the error `NX   Cannot find project 'complex'`

**Comment by jlister** [comment]
Downgrading to 
```
"nx": "14.0.2",
"@nrwl/cli": "14.0.2",
```
fixes the issue.

**Comment by AgentEnder** [comment]
This is fixed by #10031, and should be released later today or tomorrow. I'm going to close this out since the fix is merged.
