### ISSUE TITLE
With version 14.0.3, react module federation raises error in remoteEntry.js Uncaught SyntaxError: Cannot use 'import.meta' outside a module

### ISSUE THREAD

**Issue by Elvis116** [nrwl/nx#10017]
## Current Behavior
With version 14.0.3, react module federation raises error in remoteEntry.js Uncaught SyntaxError: Cannot use 'import.meta' outside a module. 
if (typeof import.meta.url === "string") scriptUrl = import.meta.url
This blocks me loading remote modules.
It works fine in 13.10.

## Expected Behavior
This should work as in 13.10

**Comment by Elvis116** [comment]
It's urgent. Any updates on this?

**Comment by Elvis116** [comment]
By the way, it only happens on dynamic script load, working following the document to create host/remote apps.

**Comment by jaysoo** [comment]
@Elvis116 Can you include the output from `nx report`?

Also, if you have a public repo we can check that would help a lot.

**Comment by corneflex** [comment]
Hello I've got the same issue when trying to import dynamically mfe module. I've created a simple project that reproduces the issue. 
**Note**: I use the useFederatedComponent from webpack 5  module federation example for loading component dynamically. (https://github.com/module-federation/module-federation-examples/tree/master/advanced-api/dynamic-remotes)

**This is the repo that reproduce the issue**:
https://github.com/corneflex/react-mfe-dynamic

**Comment by Elvis116** [comment]
Hi @corneflex ,

I fixed this by using loadModule.
function loadModule(url) {
  try {
    return import(/* webpackIgnore:true */ url);
  } catch (error) {
    console.log(error);
  }
}

function loadComponent(remoteUrl, module) {
  return async () => {
    // eslint-disable-next-line no-undef
    await __webpack_init_sharing__('default');
    const container = await loadModule(remoteUrl);
    // eslint-disable-next-line no-undef
    await container.init(__webpack_share_scopes__.default);
    const factory = await container.get(module);
    const Module = factory();
    return Module;
  };
}

**Comment by Anjanas-dh** [comment]
Hi all,
I have the same error with my Angular Nx workspace: `Uncaught SyntaxError: Cannot use 'import.meta' outside a module (at styles.js:3322:29)`.

I've created a new nx workspace from cratch following the steps in the documentation for setting up Micro Frontends with Module Federation: https://nx.dev/module-federation/faster-builds, and even then the error occurs.

Adding this to the host app `module-federation.config.js` does not solve the error:
```
 experiments: {
    outputModule: true,
  },
  ```

**Comment by corneflex** [comment]
@Elvis116 you rock, the loadModule works like a charm, thank you again :)

**Comment by aloksharma1** [comment]
same error in angular for me, latest version just created Cannot use 'import.meta' outside a module with 14.5.10

**Comment by rajdiran** [comment]
Any update on this error? Am also getting the same error

`Uncaught SyntaxError: Cannot use 'import.meta' outside a module (at styles.js:7592:29)`

`"@angular-architects/module-federation": "^14.3.12",`

**Comment by miguelchicoespin** [comment]
Same error here, just with a new nx project created following the guide in https://nx.dev/recipes/module-federation/faster-builds.

**Comment by JeremieLapert** [comment]
do you have any clue for this problem?

**Comment by JuNe98** [comment]
I have the same issue with `"@angular-architects/module-federation": "^15.0.2"`. Are there any updates how to fix?

**Comment by aloksharma1** [comment]
will this ever get a fix, 3 versions have gone up already?

**Comment by gestj** [comment]
I now got this too ....

In an older project I did the `nx migrate latest` from `14.5.10` to `15.3.3`.
Now in my node app (an express API) I get this error

```
***/dist/apps/myapp/main.js:33069
/******/ 		if (typeof import.meta.url === "string") scriptUrl = import.meta.url
         		                  ^^^^

SyntaxError: Cannot use 'import.meta' outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.Module._load (***/packages/js/src/executors/node/node-with-require-overrides.ts:16:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (***/packages/js/src/executors/node/node-with-require-overrides.ts:20:1)
```

I created with `npx nx generate @nrwl/node:app myapp` a complete new empty node app. That ones runs. Then I copied over the code from my not working app (only the `src` folder => not NX related!) and *boom the same error...

The migration didn't lead to any code change inside that `src` folder, only `nx.json`, `package.json`, `workspace.json`.

I have now NX in place since 12.9.0 over a year ago. Never a problem with any update. The node app always worked. And now it is broken.

When I google this error `SyntaxError: Cannot use 'import.meta' outside a module` there is really not much help out there. I also don't understand the posts regarding that.
It seems it has to do with this webpack module federation but I don't have custom webpack config that I could adapt as propose in some answers here.

**Comment by nezdemkovski** [comment]
I have completely the same error and tried the same flow that @gestj mentioned. Migrated nx from `v14.8.3`

**Comment by rahulraghavankklm** [comment]
I have this issue after migrating from `14.5.2`

**Comment by wobo-cveera** [comment]
We are running into same issue 😢

**Comment by ZackTherrien** [comment]
+1 with 15.6

**Comment by wobo-cveera** [comment]
We were able to resolve this issue by adding `scriptType` prop in webpack config (for `output`).

```
output: {
      ...newConfig.output,
      scriptType: 'text/javascript'
},
```

**Comment by aloksharma1** [comment]
> We were able to resolve this issue by adding `scriptType` prop in webpack config (for `output`).
> 
> ```
> output: {
>       ...newConfig.output,
>       scriptType: 'text/javascript'
> },
> ```

hello @wobo-cveera did you applied this in your host app or remote apps? also are you using angular?

**Comment by Galileon-venta** [comment]
Hello,

I have the same problem with styles.js. The suggestions here in the thread did not work for me.

Manfred Steyer over at https://github.com/angular-architects/module-federation-plugin/issues/96 stated that the error only occurs in development and does not cause any actual problems

**Comment by nitsan** [comment]
I'm using `@nrwl/angular` version 14.8.6 and changed my `webpack.config.js` from:
```
const { withModuleFederation } = require('@nrwl/angular/module-federation');
const config = require('./module-federation.config');
module.exports = withModuleFederation(config);
```
to:
```
const { withModuleFederation } = require('@nrwl/angular/module-federation');
const config = require('./module-federation.config');

module.exports = withModuleFederation(config).then((webpackConfigFunc) =>
  webpackConfigFunc({
    output: {
      scriptType: 'text/javascript',
    },
  }),
);
```
And now I'm not getting this `caught SyntaxError: Cannot use 'import.meta' outside a module` error

**Comment by turnerguo** [comment]
either set webpack output to `scriptType: 'text/javascript'` or dynamic load script with `type="module"` will solve `import.meta` error.
```js
...
    const element = document.createElement('script');
    element.src = scriptUrl;
   // here must be the same type with your webpack output config
    element.type = 'module'; // 'text/javascript';
...
```
But the `@nrwl/react:host` apps still not work with its remotes, the only solution maybe drop it and use webpack original MF configs. 😢

**Comment by ahernd2** [comment]
@nitsan This works for me when I am running just the single mfe on its own. However when I import that mfe into a shell application it fails to load the mfe. Curious how did you get around this?

Also this is now a big problem for us after upgrading to angular 16 as this overlay keeps appearing and we have to keep dismissing it

![image](https://github.com/nrwl/nx/assets/133104909/bc4c23a7-5264-45ac-b924-8a022766a638)

**Comment by hackmajoris** [comment]
> either set webpack output to `scriptType: 'text/javascript'` or dynamic load script with `type="module"` will solve `import.meta` error.
> 
> ```js
> ...
>     const element = document.createElement('script');
>     element.src = scriptUrl;
>    // here must be the same type with your webpack output config
>     element.type = 'module'; // 'text/javascript';
> ...
> ```
> 
> But the `@nrwl/react:host` apps still not work with its remotes, the only solution maybe drop it and use webpack original MF configs. 😢

I have exactly the same issue

**Comment by Sygnious** [comment]
I also got the problem, when generating Remote modules with NX, and try to run it in host-apps set up with Webpack, or with CRA + Craco.

This issue (bug?) has been open for almost a year and a half. Any updates on any fixes?

**Comment by jh185367** [comment]
I have added the `scriptType: 'text/javascript` to my config:
```typescript
import { composePlugins, withNx } from '@nx/webpack';
import { withReact } from '@nx/react';
import { withModuleFederation } from '@nx/react/module-federation';

import baseConfig from './module-federation.config';

const config = {
  ...baseConfig,
};

// Nx plugins for webpack to build config object from Nx options and context.
export default composePlugins(
  withNx(),
  withReact(),
  withModuleFederation(config),
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  (config) => {
    config.output = {
      ...config.output,
      scriptType: 'text/javascript'
    };
  
    return config
  }
);
```
I am now getting an error: `Uncaught SyntaxError: Unexpected token 'export' (at remoteEntry.js:12269:10)`. The outputted remoteEntry.js file contains an export statement at the bottom that the compiler doesn't like: `/******/ export { __webpack_exports__get as get, __webpack_exports__init as init };`

**Comment by jaysoo** [comment]
There's been many fixes and enhancements to module federation support, including better dynamic remote support. 

Please use the latest Nx version (18), and if anyone is still running into issues with `import.meta`, please open a new issue with a repro.
