### ISSUE TITLE
Webpack DevServer Proxy config doesn't allow full range of configuration

### ISSUE THREAD

**Issue by gregveres** [nrwl/nx#10019]
## Current Behavior
I am trying to configure the DevServer proxy to proxy everything except the namespace of my application. To do that I believe I have to use the array form of the proxy configuration with the "context" setting as described [here](https://stackoverflow.com/questions/46798131/using-webpack-dev-server-how-to-proxy-everything-except-app-but-including) and [here](https://webpack.js.org/configuration/dev-server/#devserverproxy) talking about the context property.

I have setup my project.json file to look like this:

```
 "serve": {
      "executor": "@nx-plus/vue:dev-server",
      "parallel": true,
      "options": {
        "port": 8080,
        "browserTarget": "ui:build",
        "devServer": {
          "https": false,
          "open": true,
          "proxy": [
            {
              "context": [
                "**",
                "!ui/**"
              ],
              "target": "http://localhost:50447/"
            }
          ]
        }
      },
    },
``` 
but I get an error when I try to run ```nx serve ui```

```
> nx run ui:serve 
 INFO  Starting development server...
When specified, "proxy" in package.json must be a string or an object.
Instead, the type of "proxy" was "object".
Either remove "proxy" from package.json, or make it an object.
```

## Expected Behavior
I expected that NX would pass this configuration to the webpack devServer. 
Alternatively, I could have used a bypass function (this is what I was using before migrating to NX, but I don't know how to specify a javascript function in a json file, it just gets interpretted as a string. 

I doubt this is a regression but I just started using NX so I don't know.

## Steps to Reproduce
Create an NX workspace and app that uses webpack. 
add the above devServer config to the app's project.json file. 

### Failure Logs
```
> nx run ui:serve 
 INFO  Starting development server...
When specified, "proxy" in package.json must be a string or an object.
Instead, the type of "proxy" was "object".
Either remove "proxy" from package.json, or make it an object.
```

### Environment
```
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : win32 x64
   yarn : 1.22.17
   
   nx : 13.10.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.10.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.3
   @nrwl/eslint-plugin-nx : 13.10.3
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.3
   @nrwl/js : Not Found
   @nrwl/linter : 13.10.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 13.0.0
   typescript : 4.3.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         @nx-plus/vue: 13.0.0
```

**Comment by AgentEnder** [comment]
Hey @gregveres! It looks like you are using an executor from @nx-plus/vue. Since that is coming in from a community plugin, you'd need to open an issue on it's repo so the maintainers can take a look. This one is out of Nx's control.

I'm going to close this out, you should file the issue here: https://github.com/ZachJW34/nx-plus

**Comment by gregveres** [comment]
@AgentEnder sorry about that. I thought this was something common they were inheriting. I will open the issue with them.
