### ISSUE TITLE
tasksRunnerOptions required as of 13.10 ?

### ISSUE THREAD

**Issue by mlahp7** [nrwl/nx#10010]
## Current Behavior

We are attempting to upgrade from version 12 to the 13. In doing so we are getting an exception thrown when running migrations. 
`Cannot read property 'default' of undefined`
Adding `tasksRunnerOptions` to our nx.json would fix the issue but we aren't using this currently. 

Is this something that is required as of version 13.10? 

## Expected Behavior

It should allow us to migrate without taskRunnerOptions, as it did before.

It looks like this was an issue with a past migration https://github.com/nrwl/nx/pull/8762
## Steps to Reproduce

Remove the property tasksRunnerOptions if you have one already in your nx.json, then run:
`nx migrate 13.10.3`
`npm i`
`nx migrate --run-migrations --verbose` 
### Failure Logs

![image](https://user-images.githubusercontent.com/72365595/165358311-3436ffec-b39e-4afb-a383-b8cf7d5e025d.png)

### Environment

   Node : 14.17.3
   OS   : linux x64
   npm  : 7.20.3
   
   nx : 13.10.3
   @nrwl/angular : 13.10.3
   @nrwl/cypress : 13.10.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.3
   @nrwl/eslint-plugin-nx : 13.10.3
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.3
   @nrwl/js : Not Found
   @nrwl/linter : 13.10.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.3
   @nrwl/web : Not Found
   @nrwl/workspace : 13.10.3
   typescript : 4.6.3
   rxjs : 6.6.7

**Comment by Ontic-Entity** [comment]
Having the same problem, migrated to latest (14) and not certain if I have lost/missed something along the migration trail.

**Comment by skanygin** [comment]
Same with migrating to 14.4 from 13.7

```Running migration 14-0-6-remove-root
Successfully finished 14-0-6-remove-root
---------------------------------------------------------
Running migration 14-2-0-add-json-schema
Successfully finished 14-2-0-add-json-schema
---------------------------------------------------------
Running migration 14-2-0-remove-default-collection
Successfully finished 14-2-0-remove-default-collection
---------------------------------------------------------
Running migration 14-2-0-replace-relative-outputs-with-absolute
Successfully finished 14-2-0-replace-relative-outputs-with-absolute
---------------------------------------------------------
Running migration 14.3.4-create-target-defaults
Successfully finished 14.3.4-create-target-defaults
---------------------------------------------------------
Running migration 13-9-0-replace-tao-with-nx
Please run npm install to ensure the correct version of Nx is installed.
Successfully finished 13-9-0-replace-tao-with-nx
---------------------------------------------------------
Running migration 13-10-0-update-decorate-cli
Successfully finished 13-10-0-update-decorate-cli
---------------------------------------------------------
Running migration 13-10-0-update-tasks-runner

 >  NX   Cannot read properties of undefined (reading 'default')
```

Trying to clear everything:
```
nx clear-cache
rm -rf node_modules package-lock.json
npm i --legacy-peer-deps
nx migrate --run-migrations 
```

But still not working.
