### ISSUE TITLE
Unable to mock any component exported from lib in apps

### ISSUE THREAD

**Issue by tar-aldev** [nrwl/nx#10029]
## Current Behavior

Given that I have a lib called `frontend-shared` and that lib has index.ts file, which exports everything from that it. 
Given I have a hook in my lib which is exported as
export * from './lib/components/RightUpperMenu/useUsersList';

Then in my test file which is in apps/frontend
I am trying to import that hook and lib
```
import { useUsersList } from '@workspace/frontend-shared';
```

And then I need to mock that particular hook (no need to mock entire lib.
So I tried to
```
jest.mock('@workspace/frontend-shared', () => {
  return {
    ...jest.requireActual('@workspace/frontend-shared'),
    useUsersList: jest.fn()
  };
});
```

Although in the test file `useUsersList` is a mocked function now, in the component where the hook is used, it is still a real hook, not a mocked function.

I understand that `@workspace/frontend-shared` is just a kind of symlink and is not an npm package from node_modules, so probably because of this, it doesn't work
## Expected Behavior

I would like to easily mock part of the lib (e.g. mock hook or helper function)

No
## Steps to Reproduce

1. Create a lib and put any hook there (e.g. useUsersList).
2. in libs/lib-name/src/lib/ folder there will be an index.ts file
3. add export * from './lib/useUsersList' to that file
4. in apps/app-name/src/components create a component which uses the hook
5. create a test and try to mock the hook
Result: the hook is not mocked.
It is also impossible to use relative path to mock it as it will give the error

> Projects cannot be imported by a relative or absolute path, and must begin with a npm 
> scopeeslint[@nrwl/nx/enforce-module-boundaries]

### Environment

   nx : 13.9.6
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.9.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.9.6
   @nrwl/eslint-plugin-nx : 13.9.6
   @nrwl/express : 13.9.6
   @nrwl/jest : 13.9.6
   @nrwl/js : 13.9.6
   @nrwl/linter : 13.9.6
   @nrwl/nest : Not Found
   @nrwl/next : 13.9.6
   @nrwl/node : 13.9.6
   @nrwl/nx-cloud : 13.2.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.9.6
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.9.6
   @nrwl/web : 13.9.6
   @nrwl/workspace : 13.9.6
   typescript : 4.5.4
   rxjs : 6.6.7

**Comment by bobbypiper** [comment]
Did you ever figure this out? I'm hitting the exact same problem trying to mock utils from my utilities library into feature library.

**Comment by barbados-clemens** [comment]
@bobbypiper or @tar-aldev I've not been able to reproduce this so maybe something else is at play.

do either of you have a repo I can clone down and look at?

**Comment by bobbypiper** [comment]
@barbados-clemens @tar-aldev I actually resolved this problem some time ago; although the implementation is somewhat inelegant. I've pushed a repo showing my implementation here https://github.com/bobbypiper/nx-vitest-mocking

Basically, whilst using VItest, the automocking solution with vitest/jest doesn't play well with the NX packaging solution - there are plenty of times where I only want to mock one or two modules whilst leaving the remaining modules intact. Vitest (and I think jest) attempts to figure out and mock all modules even those that don't have a manually created mock within __mocks__ directory.

My solution was to do the following:
- Store all my mocks in the usual location within the __mocks__ directory of a library - https://github.com/bobbypiper/nx-vitest-mocking/tree/master/libs/library-one/src/lib/__mocks__
- then within the library root directory (inline with src) I would create another __mocks__ directory and create an index.ts file; this would import all the manual mocks created, it would then export all from the root index file (getting all modules within the library) then finally export the previously imported mocks - see here for example https://github.com/bobbypiper/nx-vitest-mocking/blob/master/libs/library-one/src/__mocks__/index.ts
- Finally, I would create a mocks.ts alongside the library index.ts (and add to the tsconfig base paths) this would allow me to access the relevant mocks within tests to alter the mocking capability as required - see here https://github.com/bobbypiper/nx-vitest-mocking/blob/master/libs/library-one/src/mocks.ts

Example of using the mocks can be found here - https://github.com/bobbypiper/nx-vitest-mocking/blob/master/libs/library-two/src/lib/library-two.mocked.test.ts

**Comment by barbados-clemens** [comment]
Okay interesting. I'll take a look, we don't use the __mocks__ folder conventions and just mock the modules and specific exports we want within the Nx codebase so never come across this behavior. 

i.e. like the [createProjectGraphAsync() from devkit](https://github.com/nrwl/nx/blob/3195fe06e4f2eb4fdaf5fb14b899dd2f6ce2ef15/packages/jest/src/migrations/update-15-8-0/update-configs-jest-29.spec.ts#L11-L17)

**Comment by bobbypiper** [comment]
@barbados-clemens Interesting! thanks for the link to the implementation you use with devkit.

IIRC, the use of `requireActual` was a problem for us; the module in question that required mocking had `process.env` values which are intentionally excluded within test suite - this means that any attempt to `requireActual` the whole package and then overload the relevant module would bork due to the `process.env` presence (or lack of!)

**Comment by barbados-clemens** [comment]
@tar-aldev I just tried on latest and I'm able to mock functions from other projects. 

example. 
```ts
import { render } from '@testing-library/react';

import App from './app';
jest.mock('@jest-mocking-sample/lib-one', () => ({
  ...jest.requireActual('@jest-mocking-sample/lib-one'),
  // this hook by default renders 0 and increments by 1
  useMyHook: () => ({ count: 2, increment: jest.fn() }),
}));

describe('App', () => {
  it('should mock hook', async () => {
    const { findByRole, findByTestId } = render(<App />);
    (await findByRole('button')).click();
    const p = await findByTestId('count');
    expect(p).toMatchInlineSnapshot(`
      <p
        data-testid="count"
      >
         Count: 
        2
         
      </p>
    `);
  });
});

```

which you can see here. 
https://github.com/barbados-clemens/jest-mock-hook-example

retry with latest and provide a clone-able reproducible so I can take look into it.

**Comment by always-maap** [comment]
We have the same issue after migrating to nx from 13 to 15

```ts
jest.mock('@zoomit/editor', () => ({
  ...jest.requireActual('@zoomit/editor'),
  useEditor: jest.fn(),
}));

mocked(useEditor).mockImplementation(createEditorState([createBlockDefaultValue('action-box')]));
```

this code is not working anymore. 
error:

```
TypeError: Cannot read properties of undefined (reading 'default')
```

**Comment by barbados-clemens** [comment]
@always-maap I need a cloneable repo to look into it.
