### ISSUE TITLE
NestJs need to have es6 in tsconfig target

### ISSUE THREAD

**Issue by Need-To-Learn** [nrwl/nx#1002]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

I merged my api repository using nest to my nrwl repository with the 7.3 version.
The ng serve nestjs-project is suppose to correctly run the API

## Current Behavior

Nest wasn't able to handle request when using Nest middleware (infinite loading).
I found out the issue : https://github.com/nestjs/nest/issues/266.
Nestjs need to have tsconfig target set to es6, but by default the tsconfig generated by nrwl inherit from the global tsconfig (es5).

## Other

I think it would be nice to override nrwl default tsconfig with the default nestjs tsconfig options when generating a new nestjs project

**Comment by mehrad-rafigh** [comment]
Hey guys.  I opened a PR #1770 
Is it, what you party people are looking for? If so, cool! If not, what needs to be changed?

I created a brand new nest app with the nest cli and compared the tsconfig
After my patch, there won't be much difference.

**Comment by Need-To-Learn** [comment]
@mehrad-rafigh Hi, that's exactly what I was looking for :)
I didn't test it yet but reading the code, it looks good !

Plus I agree to the fact that we should stick to nestjs' es version.

**Comment by vsavkin** [comment]
Folks. Is it still an issue?
