### ISSUE TITLE
View the Project Graph does not show dependency from blog to ascii

### ISSUE THREAD

**Issue by yuchien302** [nrwl/nx#10036]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/core-tutorial/03-share-assets

### Additional context or description

I followed the tutorial strictly, and expect there's a dependency arrow from blog to ascii. But there isn't
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/1877281/165652508-cd47be31-2d7d-4b96-9b74-f405221805ba.png">

**Comment by hho** [comment]
Same here. This subsequently also breaks the "build affected projects" step.

**Comment by ldgarcia** [comment]
@yuchien302, @hho  It happened to me as well. 

[The tutorial ](https://nx.dev/core-tutorial/03-share-assets#tell-nx-about-the-dependencies) uses:

```json
{
  "dependency": {
    "ascii": "*"
  },
}
```

And the graph is shown as:

![Screenshot from 2022-05-22 17-07-09](https://user-images.githubusercontent.com/1865386/169720116-43655646-0b8c-476b-83a5-07a3b6195b3e.png)

However, following [the docs](https://nx.dev/configuration/packagejson) for using `package.json`, I used:

```json
{
  "nx": {
    "implicitDependencies": [
      "ascii"
    ]
  }
}
```

And the graph is shown as:

![Screenshot from 2022-05-22 17-09-06](https://user-images.githubusercontent.com/1865386/169720148-15eedfdc-d9f3-461b-9360-38dc67121729.png)

**Comment by nightmarelie** [comment]
@hho @yuchien302 
Try adding the following lines to your `packages/blog/package.json`

```
  "nx": {
    "implicitDependencies": [
      "ascii"
    ]
  }
 ```

**Comment by hho** [comment]
Thank you, but isn't that missing the point? The tutorial tries to explain that Nx detects depencies inside JS code automatically (just not in Markdown or Go code):

> ![Screenshot_20220829_114139](https://user-images.githubusercontent.com/478228/187172954-90a27364-ccba-45f2-a29d-4fcd813fc9da.png)

… and that doesn't work, apparently.
Yes, your workaround would do it, but it's exactly opposite to what the tutorial tries to teach here.

**Comment by isaacplmann** [comment]
This tutorial is no longer referenced from the getting started page.
