### ISSUE TITLE
Cannot find target storybook for project

### ISSUE THREAD

**Issue by dangviettuan** [nrwl/nx#10039]
Library config is not updated in cache
## Current Behavior

Error "Cannot find target storybook for project xxx" when run library storybook

## Expected Behavior

Run storybook command working correctly

## Steps to Reproduce

1. Generate a react library
2. Generate react library storybook config
3. Run storybook of the library
4. An error occurs "Cannot find target storybook for project xxx"
5. Remove node_modules folder to remove .cache folder then re-install 
6. Re-run storybook command of the library. The command working 

### Environment

  Node : 14.17.6
  OS   : linux x64
  yarn : 1.22.17
  
  nx : 13.0.0
  @nrwl/angular : Not Found
  @nrwl/cli : 13.0.0
  @nrwl/cypress : 13.0.0
  @nrwl/devkit : 13.0.0
  @nrwl/eslint-plugin-nx : 13.0.0
  @nrwl/express : Not Found
  @nrwl/jest : 13.0.0
  @nrwl/linter : 13.0.0
  @nrwl/nest : Not Found
  @nrwl/next : 13.0.0
  @nrwl/node : 13.0.0
  @nrwl/nx-cloud : 12.5.0
  @nrwl/react : 13.0.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.0.0
  @nrwl/web : 13.0.0
  @nrwl/workspace : 13.0.0
  @nrwl/storybook : 13.0.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by AgentEnder** [comment]
We've fixed some small issues recently with this, can you try updating to 14.0.3 and see if it has been fixed?

**Comment by dangviettuan** [comment]
> We've fixed some small issues recently with this, can you try updating to 14.0.3 and see if it has been fixed?

I have updated it to 14.0.5 but the issue still happened after several libs were created. In my case is 1 error over 10 created libs.

Node : 14.17.6
   OS   : linux x64
   yarn : 1.22.11
   
   nx : 14.0.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.0.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.0.5
   @nrwl/eslint-plugin-nx : 14.0.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.5
   @nrwl/js : 14.0.5
   @nrwl/linter : 14.0.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.0.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.0.5
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.0.5
   @nrwl/web : 14.0.5
   @nrwl/workspace : 14.0.5
   typescript : 4.6.3
   rxjs : 6.6.7

**Comment by flexbox** [comment]
I encounter the same issue with my stack
```
apps/
  mobile/   # react-native
  web/       # react 
```

My root `package.json`
```json
    "@storybook/addon-essentials": "~6.4.12",
    "@storybook/builder-webpack5": "~6.4.12",
    "@storybook/core-server": "~6.4.12",
    "@storybook/manager-webpack5": "~6.4.12",
    "@storybook/react": "~6.4.12",
    "nx": "14.1.7",
```

```console
❯ nx run web:storybook

 >  NX   Cannot find target 'storybook' for project 'web'
```

Steps to reproduce:

1.  `yarn add --dev @nrwl/storybook`
2. `nx g @nrwl/react:storybook-configuration web`

**Comment by flexbox** [comment]
@dangviettuan 
Have you tried to run `nx reset`?

If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨

**Comment by dangviettuan** [comment]
> @dangviettuan Have you tried to run `nx reset`?
> 
> If your problem is solved can you please close the issue? It sparks joy for maintainers sparkles

Many thanks @flexbox
