### ISSUE TITLE
Custom swcrc path

### ISSUE THREAD

**Issue by djgrant** [nrwl/nx#10058]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Pass a custom swcrc path to the @nrwl/js:swc executor.

## Motivation
I am attempting to keep my tooling config in a config folder. I find it a bit annoying that for each package folder I open, I see exactly the same files. I think it would be great if nx could enable some config housekeeping. 

I was able to configure some tools with custom config paths, but cannot provide a config path for SWC. 

<img width="236" alt="Screenshot 2022-04-29 at 11 18 40" src="https://user-images.githubusercontent.com/1670902/165926829-9a750089-5314-4f01-aa46-fd3d39a9fe36.png">

## Suggested Implementation
Add an optional `swcrcPath` option. Pass it here, defaulting to current behaviour if not present. 

https://github.com/nrwl/nx/blob/71bd3e13ada518412477eb78b3a7e8f206ea747a/packages/js/src/executors/swc/swc.impl.ts#L53

## Alternate Implementations
Not familiar with the codebase, but this looks like the only entrypoint to change that option. 

If nx wanted to get on board with the config files in a folder movement, it'd be good to enforce some consistency for executors to provide this option, as well an option in generators.

**Comment by AgentEnder** [comment]
This makes sense to add. Since you've identified the correct area for the change, would you like to contribute it?

You'd need to:
- Add option in the swc schema.json
  - This is where you can specify the default value
- Add property to options model in schema.d.ts
- Make the change to line 53
```typescript
 swcrcPath: join(contextRoot, projectRoot, options.swcrcPath), 
```

**Comment by nartc** [comment]
@djgrant I can assign this task to you if you'd like to take up on it.

**Comment by djgrant** [comment]
Yep, going to work on it this afternoon.
