### ISSUE TITLE
Nx v14 can't auto shared some module in mfe project

### ISSUE THREAD

**Issue by a616101** [nrwl/nx#10054]
## Current Behavior

In Nx v.14 + :

I followed the documentation:
<img width="721" alt="image" src="https://user-images.githubusercontent.com/4496234/165874493-780c7939-d038-4b1e-97eb-596bc4d29a64.png">

The conclusion is：
Unable to share @angular/animations automatically when I use micro frontend project.

In Nx v.13 + :
Manual webpack.config.js  configuration is no problem
shared: share({
        '@angular/animations': {
          singleton: true,
          eager: true,
          requiredVersion: 'auto'
        },
        ......
})

## Expected Behavior

@angular/animations needs to be shareable or provide manual configuration method

## Steps to Reproduce

1. app.module with import  BrowserModule and  BrowserAnimationsModule in my shell app.
2. create some service and  inject AnimationBuilder in remote app
3. start up shell app and remote app

### Failure Logs
<img width="1670" alt="image" src="https://user-images.githubusercontent.com/4496234/165873474-34326ee5-4d2a-4e07-8524-c244dda2d7ae.png">

### Environment

 Node : 16.14.0
   OS   : darwin x64
   npm  : 8.3.1
   
   nx : 14.0.5
   @nrwl/angular : 14.0.5
   @nrwl/cypress : 14.0.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.0.5
   @nrwl/eslint-plugin-nx : 14.0.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.5
   @nrwl/js : Not Found
   @nrwl/linter : 14.0.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.0.5
   @nrwl/web : Not Found
   @nrwl/workspace : 14.0.5
   typescript : 4.6.4
   rxjs : 7.5.5

**Comment by Vevl** [comment]
Hello @leosvelperez, first many thanks for your work, it's great.

I run into a similar issue. In my case, it was 3rd party component which is using AnimationBuilder.
Before posting I tried different solutions but none of them seems to help. 

## Steps to Reproduce
- I create [repo](https://github.com/Vevl/kendo-test) where you can test it on your own,
- Just start it and try to open the dropdown panel

## Issue
When both host and remote are using AnimationBuilder then it throws an error even `additionalShared: ['@angular/animations']` is added to mf config file.
![image](https://user-images.githubusercontent.com/35180926/180414941-91e7febd-f54f-44d0-be53-c2ca413edd59.png)
BrowserModule, BrowserAnimationsModule are imported by host app.module.ts only.
