### ISSUE TITLE
Integrate Environmental Variables into Angular builders

### ISSUE THREAD

**Issue by neilsoult** [nrwl/nx#10051]
## Description
From the discussion on [this issue](https://github.com/nrwl/nx/issues/6941#issuecomment-1112394862)

> The problem right now is that @angular-devkit/build-angular-browser doesn't provide the same environment variable support that our executors provide.

## Motivation
While Angular does prefer using environment.ts file transforms, this does not apply to index.html compilation, as there are cases where we need specific values depending on the build/serve environment. For instance, using Google Tag Manager or other analytics platforms require injecting their bootstrap script in the index file, and would have separate GTM ids for development environments vs production environments.

## Suggested Implementation
I would assume exactly like the documentation for the react executors describes.

## Alternate Implementations
¯\\_(ツ)_/¯

**Comment by Coly010** [comment]
The angular team themselves are working on an implementation of a solution that should support this. Therefore I'll close this issue as it is something that should be applied natively by angular soon.

**Comment by neilsoult** [comment]
@Coly010 can you point me to an issue or info I can keep track of for this implementation that angular is working on? I couldn't find it from a google search, and all I could find was a much older issue that was closed as not on the roadmap:
https://github.com/angular/angular-cli/issues/8759

**Comment by Coly010** [comment]
https://github.com/angular/angular-cli/issues/3855

**Comment by neilsoult** [comment]
@Coly010 thanks for the link, but best I can tell from reading the comments, the team seems against implementing this feature.

from [dgp1130](https://github.com/dgp1130):
> The CLI as it stands today, just isn't the right tool to solve this particular problem.
