### ISSUE TITLE
Migration to v14 fails

### ISSUE THREAD

**Issue by LuckeeDev** [nrwl/nx#10086]
## Current Behavior
Migrating to `v14.0.5` fails with the error pasted below.

## Expected Behavior
Migrating from previous versions worked.

## Steps to Reproduce
The issue happens when migrating from `13.10.2` to any other version, including the latest one `14.0.5` but also `13.10.3`.

### Failure Logs
```
error https://registry.yarnpkg.com/acorn/-/acorn-8.7.1.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, stat 'C:\\src\\yarn\\v6\\npm-acorn-8.7.1-0197122c843d1bf6d0a5e83220a788f278f63c30-integrity\\node_modules\\acorn\\dist\\acorn.mjs'"
```

### Environment
```
Node : 16.13.1
OS   : win32 x64
yarn : 1.22.18

nx : 13.10.2
@nrwl/angular : Not Found
@nrwl/cypress : 13.10.2
@nrwl/detox : Not Found
@nrwl/devkit : 13.10.2
@nrwl/eslint-plugin-nx : 13.10.2
@nrwl/express : Not Found
@nrwl/jest : 13.10.2
@nrwl/js : 13.10.2
@nrwl/linter : 13.10.2
@nrwl/nest : Not Found
@nrwl/next : 13.10.2
@nrwl/node : 13.10.2
@nrwl/nx-cloud : Not Found
@nrwl/nx-plugin : Not Found
@nrwl/react : 13.10.2
@nrwl/react-native : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : 13.10.2
@nrwl/web : 13.10.2
@nrwl/workspace : 13.10.2
typescript : 4.6.4
rxjs : 6.6.6
---------------------------------------
Community plugins:
     @jscutlery/semver: 2.23.3
```

**Comment by demisx** [comment]
Not sure if this is related or should be filed as a separate but, but after upgrading from `v13.9.5 -> v14.0.5` with:

```sh
npx nx migrate latest
npm install
```

I get the following error running `npx nx migrate --run-migrations`: "sh: nx: command not found". 

Had to roll back to `v13.9.5`.

**Comment by dveluchamy** [comment]
I am trying to migrate nx from version `13.8.5` to latest `14.0.5`
```sh
$ yarn nx migrate latest
yarn run v1.22.18
$ nx migrate latest
√ We noticed you are migrating to a new major version, but are not taking advantage of Nx Cloud. Nx Cloud can make your CI up to 10 times faster. Learn more about it here: nx.app. Would you like to add it? · No
Fetching meta data about packages.
It may take a few minutes.
Fetching nx@14.0.5
Fetching nx@latest
Fetching @nrwl/workspace@14.0.5
Fetching @nrwl/cypress@14.0.5
Fetching @nrwl/linter@14.0.5
Fetching @nrwl/js@14.0.5
Fetching @nrwl/jest@14.0.5
Fetching @nrwl/node@14.0.5
Fetching @nrwl/web@14.0.5
Fetching @nrwl/react@14.0.5
Fetching @nrwl/storybook@14.0.5
Fetching @nrwl/workspace@14.0.5
Fetching @nrwl/jest@14.0.5
Fetching @nrwl/js@14.0.5
Fetching @nrwl/linter@14.0.5
Fetching @nrwl/node@14.0.5
Fetching @nrwl/cypress@14.0.5
Fetching @nrwl/web@14.0.5
Fetching @nrwl/react@14.0.5
Fetching @nrwl/storybook@14.0.5

 ERROR  The migrate command failed.

Command failed: yarn add -W @nrwl/jest@14.0.5
warning package.json: No license field
warning No license field
error https://registry.yarnpkg.com/electron-to-chromium/-/electron-to-chromium-1.4.132.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, stat 'C:\\Users\\username\\AppData\\Local\\Yarn\\Cache\\v6\\npm-electron-to-chromium-1.4.132-b64599eb018221e52e2e4129de103b03a413c55d-integrity\\node_modules\\electron-to-chromium\\versions.js'"

Done in 426.53s.
```
I have cleared my node_modules folder and yarn cache, still no luck. 

**The file that errors is different for each run**, for example when I run the same command the next time, the error as below

```sh
 ERROR  The migrate command failed.

Command failed: yarn add -W @nrwl/react@14.0.5
warning package.json: No license field
warning No license field
warning @nrwl/react > @nrwl/web > stylus > css > source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
error An unexpected error occurred: "EPERM: operation not permitted, unlink 'C:\\Users\\username\\AppData\\Local\\Yarn\\Cache\\v6\\npm-rollup-plugin-typescript2-0.31.2-463aa713a7e2bf85b92860094b9f7fb274c5a4d8-integrity\\node_modules\\rollup-plugin-typescript2\\.yarn-tarball.tgz'"
```

**Comment by Waterstraal** [comment]
I'm getting the following error when I try to run `nx migrate --run-migrations`. `nx migrate latest` ran just fine, so it seems that the latest version of nx broke the cli package?
```
nx : The term 'nx' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that t 
he path is correct and try again.
```
Installing nx globally does not help. 

Repro:
1. `nx migrate latest`
2. `npm i`
3. `nx migrate --run-migrations`

**Comment by dveluchamy** [comment]
```shell
yarn nx migrate latest
```
>  ERROR  The migrate command failed.
> 
> Command failed: yarn add -W @nrwl/react@14.0.5
> warning package.json: No license field
> warning No license field
> warning @nrwl/react > @nrwl/web > stylus > css > source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
> error An unexpected error occurred: "EPERM: operation not permitted, unlink 'C:\\Users\\username\\AppData\\Local\\Yarn\\Cache\\v6\\npm-rollup-plugin-typescript2-0.31.2-463aa713a7e2bf85b92860094b9f7fb274c5a4d8-integrity\\node_modules\\rollup-plugin-typescript2\\.yarn-tarball.tgz'"

**UPDATE:** I am able to migrate to latest version, when I execute the above in "Command Prompt"  with Administrative rights. 
Now, experiencing errors in react testing library, it could be because of the latest migration updated the react version to v18.

**Comment by LuckeeDev** [comment]
@dveluchamy I tried to execute the command inside the Command Prompt with admin rights, too, but without success.

**Comment by bhuber2010** [comment]
This worked for me finally, and I had upgraded to pnpm v7 also...

- added a `npm migrate` script = `nx migrate --run-migrations`
- deleted node_modules
- `pnpm i`
- `pnpm add nx`
- `pnpm run migrate`

Now I feel not all that is actually necessary and likely can be condensed down, but it's exactly what I stumbled so figured I'd share. Now that I'm good for now, unfortunately don't have the time to test what's the important bit. I'd guess something around the new un-namespaced `nx` package.

**Comment by Marr11317** [comment]
@bhuber2010 Thank you installing nx solved it, though tsc is still not working (see #10162 )

**Comment by LuckeeDev** [comment]
@bhuber2010 unfortunately adding nx didn't solve the problem for me :(

**Comment by kacase** [comment]
It seemed to be an isssue with my local version of nx.
Running `npx nx migrate latest` worked like a charm.
