### ISSUE TITLE
Missing install deps instruction in Storybook Webpack Migration

### ISSUE THREAD

**Issue by leandrocrs** [nrwl/nx#10097]
### Documentation issue

- [ ] Reporting a typo
- [X] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?
Storybook Webpack Migration

Enter the URL or documentation section here.
[storybook/migrate-webpack-final-angular#storybook-webpack-migration](https://nx.dev/storybook/migrate-webpack-final-angular#storybook-webpack-migration)

### Additional context or description
The guide asks to change webpack config to `{ core: 'webpack5' }`, but do not ask to install `@storybook/builder-webpack5`. If you follow migration instructions as is, you will be caught in the following error when try running any storybook tasks:
```
Error: Cannot find module '@storybook/builder-webpack5'...
```

And after install @storybook/builder-webpack5:
```
Error: Cannot find module '@storybook/manager-webpack5'
```

Provide any additional details here as needed.
What fix is to add the following install instruction:
```sh
yarn add -D @storybook/builder-webpack5 @storybook/manager-webpack5
```

**Comment by mandarini** [comment]
Hi there @leandrocrs ! Good catch! 
Would you like to help us with this, by updating the documentation? You can go on [this page](https://nx.dev/storybook/migrate-webpack-final-angular#storybook-webpack-migration) and click the "Edit this page" button at the bottom! :)  Let me know if you need any help!
