### ISSUE TITLE
Error: tree.branch is not a function tree.branch is not a function with angular 1.5.0 and @nrwl/schematics 0.1.1

### ISSUE THREAD

**Issue by dreamerNcoder** [nrwl/nx#101]
Hi All, 
I have install angular cli latest and nrwl/schematics, but whenever I am trying to run create new project i am getting new error.
```
PS C:\> ng new myprojectname --collection=@nrwl/schematics
Error: tree.branch is not a function
tree.branch is not a function
```
But I am able to create a new project with angular cli using below code: 

`PS C:\> ng new myprojectname `

As the angular cli is working so thought it is a bug with this. 

**Environment**: 
Windows 10
node js : v6.11.5
npm : 3.10.10
Angular cli: 1.5.0

**Comment by dreamerNcoder** [comment]
I have already deleted node_module globally and reinstalled the node modules. 
Please suggest any workaround to solve this issue.

**Comment by dreamerNcoder** [comment]
Reinstalled node and also updated node version to v8.x and v9.x same issue. :(

**Comment by jschwarty** [comment]
Did you use yarn for the global install? To be able to create a new project with the schematics for Nx you need to either use yarn or use the install script.

**Comment by dreamerNcoder** [comment]
I used npm, will give a try with yarn :)

**Comment by kevincam3** [comment]
I get the same problem Windows 10

**Comment by dreamerNcoder** [comment]
It working for me, but as mentioned above please use **"YARN"** in stead of npm, and make sure to clean up global npm packages.
