### ISSUE TITLE
[Support]: Adding a non-angular project to nx workspace

### ISSUE THREAD

**Issue by michelcve** [nrwl/nx#1011]
[Support]: Adding a non-angular project to nx workspace

Basically we want to develop a very small web application using only typescript and html (but no angular!), and add that to our nx workspace.

What would be the best approach to add a non-angular typescript web application to a NX workspace?

**Comment by vsavkin** [comment]
You can generate a non-angular ts application by running: `ng g app myapp --framework=web-components`.
