### ISSUE TITLE
React application with buildLibsFromSource: false does not automatically build libs during serve

### ISSUE THREAD

**Issue by ajwootto** [nrwl/nx#10124]
## Current Behavior

If I have a React application which depends on a buildable lib, and the "buildLibsFromSource" setting is set to false, then running `nx serve your-app` will not work because the dependent lib has not been built. Running `nx build your-app` will work properly. Changes to that lib will not cause the application to hot-reload.

## Expected Behavior

I expected that the library would have been automatically built, with the dev server auto-reloading when files have changed with this setting set.

This seemed to work fine on Nx 13.10

## Steps to Reproduce

Reproduced in this repo at this particular commit.
https://github.com/DevCycleHQ/js-sdks/tree/673772254c979d636389f98a75e9781fe4deba53
Try running `nx serve example-react-with-async-provider`

### Environment

```
 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : darwin x64
   yarn : 3.2.0

   nx : 14.0.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.0.5
   @nrwl/detox : 14.0.5
   @nrwl/devkit : 14.0.5
   @nrwl/eslint-plugin-nx : 14.0.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.5
   @nrwl/js : 14.0.5
   @nrwl/linter : 14.0.5
   @nrwl/nest : Not Found
   @nrwl/next : 14.0.5
   @nrwl/node : 14.0.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.0.5
   @nrwl/react-native : 14.0.5
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.0.5
   @nrwl/web : 14.0.5
   @nrwl/workspace : 14.0.5
   typescript : 4.6.3
   rxjs : 6.6.7
```

**Comment by tudorgergely** [comment]
Any news on this one? Also the documentation is very angular focused for incremental builds
