### ISSUE TITLE
add simpleModuleName flag to nestjs library schematic

### ISSUE THREAD

**Issue by mehrad-rafigh** [nrwl/nx#10125]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Similar to angular libs --simpleModuleName, there should be the same flag for creating nestjs libraries.

## Motivation
Remove redundancy in the name

**Comment by AgentEnder** [comment]
Hey @mehrad-rafigh, this sounds good to me. If you want to port the flag over I can assign the issue to you.

**Comment by mehrad-rafigh** [comment]
Hey @AgentEnder this would be great. Thank you very much :)

**Comment by mehrad-rafigh** [comment]
@AgentEnder sry this took a bit longer than I anticipated. Hope PR is ok, so it can be merged :)

**Comment by mehrad-rafigh** [comment]
@AgentEnder any chance you can review the PR?

**Comment by mehrad-rafigh** [comment]
@AgentEnder it would be great if we could get this merged. Can you please check the PR please? Our team really needs it :) Thanks
