### ISSUE TITLE
Build configuration cannot be set in targetDependencies

### ISSUE THREAD

**Issue by Indronil** [nrwl/nx#10136]
## Current Behavior
Current Behavior: One target can be made dependent on other targets by defining the targetDependencies. example:
```
"targetDependencies": {
    "deploy": [
      {
        "target": "build-nx-prod",
        "projects": "self"
      }
    ]
  }
```
But there is no way to define the build target's configuration in the dependency. eg:
If I run
`npx nx affected --target=deploy -c=production --parallel --max-parallel=3 --stage=pr --skip-nx-cache` in my CI/CD pipeline using github actions.
The build target with default configuration is run and not the defined -c=production configuration.

## Expected Behavior
Expected Behavior:
When we run the above command from ci.yml file the ci should pick the build configuration and not the default one.
We need a way where we can define the configuration in nx so it is picked correctly.

No
## Steps to Reproduce

1. Create two targets in project.json of an app.
2. Call them build and deploy
3. add build configuation like 
```
"build": {
      "executor": "@angular-devkit/build-angular:browser",
      "options": {
        "outputPath": "dist/administration",
        "aot": true,
        "index": "apps/administration/src/index.html",
        "main": "apps/administration/src/main.ts",
        "tsConfig": "apps/administration/tsconfig.app.json",
        "polyfills": "apps/administration/src/polyfills.ts",
        "assets": [
          "apps/administration/src/assets",
          "apps/administration/src/favicon.ico",
          {
            "glob": "**/*",
            "input": "libs/web/angular/shared/data-access/application-api/src/lib/assets",
            "output": "/assets"
          },
          {
            "glob": "**/*",
            "input": "qa-data",
            "output": "/assets"
          },
          {
            "input": "libs/configuration/src/lib",
            "glob": "frameRedirect.html",
            "output": "/"
          },
          {
            "input": "node_modules/msal/dist",
            "glob": "msal.min.js",
            "output": "/"
          },
          {
            "input": "config",
            "glob": "config.json",
            "output": "/"
          },
          {
            "glob": "configuration.js",
            "input": "libs/logging/src/lib/new-relic",
            "output": "/newrelic"
          }
        ],
        "styles": [
          "node_modules/normalize.css/normalize.css",
          "node_modules/bootstrap/dist/css/bootstrap.css",
          "apps/administration/src/styles.scss"
        ],
        "scripts": ["node_modules/msal/dist/msal.js"]
      },
      "configurations": {
        "development": {
          "baseHref": "/",
          "outputPath": "/"
        },
        "production": {
          "baseHref": "/administration/",
          "outputHashing": "all",
          "sourceMap": true,
          "optimization": true,
          "outputPath": "dist/administration",
          "budgets": [
            {
              "type": "anyComponentStyle",
              "maximumWarning": "6kb"
            }
          ],
          "fileReplacements": [
            {
              "replace": "apps/administration/src/environments/environment.ts",
              "with": "apps/administration/src/environments/environment.prod.ts"
            },
            {
              "replace": "environments/environment.ts",
              "with": "environments/environment.prod.ts"
            }
          ],
          "namedChunks": false,
          "extractLicenses": true
        },
}}
```
4. Add the targetDependencies in nx.json
```
"targetDependencies": {
    "deploy": [
      {
        "target": "build",
        "projects": "self"
      }
    ]
  },
```
5. Run the Ci command
npx nx affected --target=deploy -c=production --parallel --max-parallel=3 --stage=pr --skip-nx-cache

You will notice the -c=production is not run instead it runs only the default options in the build target.

**Comment by elgurinn** [comment]
Any news on this?

**Comment by elgurinn** [comment]
@Indronil did you manage to fix this? Unable to update NX from 13 to 14 because of this.

**Comment by Indronil** [comment]
@elgurinn No not now. This seems to be an issue with NX. All I did as a workaround is created the target with options that I need to run from my CI.

**Comment by haven2world** [comment]
Experiencing a similar issue, I think when we define the targetDependencies, we need another field to specify the configuration. like
```
"targetDependencies": {
    "deploy": [
      {
        "target": "build",
        "configuration": "production/test/e2e",
        "projects": "self"
      }
    ]
  },
```

**Comment by Indronil** [comment]
@haven2world I do not think we have anything like the one you mentioned above. We do not have configurations property that is defined in the targetDependencies or targetDefaults(NX 14.4 & above).

**Comment by haven2world** [comment]
@Indronil I don't really remember the context. I think what we want is when we specify the dependency of a target, we can specify the configuration at the same time. For example, in a E2E project, we'll want its `test` target to depend on the original project's `build` target with e2e configuration

**Comment by Indronil** [comment]
@haven2world have you tried it with the configuration param as you have mentioned earlier? If it works can you specific which version of NX it works?

**Comment by AgentEnder** [comment]
Hey @Indronil  and @haven2world!

I think you are each describing a slightly different issue. 
- `-c production` is not hitting the production configuration for target dependencies, as described by @elgurinn. I think this works if you pass `--configuration`, but it should work with each. Regardless, this is tracked here: #16147
- The ability to depend on a specific configuration of a dependency target, which may be different than the target currently running. This is being tracked here: #15064

Its not lost on me that those issues are each newer than this one, but since they are a bit more specific and have a bit more activity, I'm going to close this issue in favor of tracking the changes there.
