### ISSUE TITLE
Setting up an angular app prevents commands from working

### ISSUE THREAD

**Issue by YonatanKra** [nrwl/nx#10143]
## Current Behavior
I've setup a new workspace with the `web` preset. 
`npm start` spins up the app.
I then installed the angular package (`npm i -D @nrwl/angular`).
`npm start` spins up the app.
I then created a new angular app(`npm run nx g @nrwl/angular:app test-app`).
`npm start` fails with the following error:
```
    at createProjectFileMap (/Users/ykra/projects/vonage-projects/ai-widget/node_modules/nx/src/project-graph/file-map-utils.js:27:33)
    at /Users/ykra/projects/vonage-projects/ai-widget/node_modules/nx/src/project-graph/build-project-graph.js:26:97
    at Generator.next (<anonymous>)
    at /Users/ykra/projects/vonage-projects/ai-widget/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/ykra/projects/vonage-projects/ai-widget/node_modules/tslib/tslib.js:114:16)
    at buildProjectGraph (/Users/ykra/projects/vonage-projects/ai-widget/node_modules/nx/src/project-graph/build-project-graph.js:24:20)
    at /Users/ykra/projects/vonage-projects/ai-widget/node_modules/nx/src/project-graph/project-graph.js:51:66
    at Generator.next (<anonymous>)
```

## Expected Behavior
`npm start` should run without issues.

## Steps to Reproduce
1. `npx create-nx-workspace` and select the web components preset
2. run `npm start` to see the app loads
3. `npm i -D @nrwl/angular`
4. run `npm start` to see the app loads
5. `npm run nx g @nrwl/angular:app` to generate an angular app
6. run `npm start` to see the error
7. Revert all the angular app's changes and everything is back to normal

### Failure Logs
{
  stack: "TypeError: Cannot read properties of undefined (reading 'endsWith')\n" +
    '    at createProjectRootMappings (/Users/ykra/projects/vonage-projects/vonage-ai-widget/node_modules/nx/src/project-graph/file-map-utils.js:12:38)\n' +
    '    at createProjectFileMap (/Users/ykra/projects/vonage-projects/vonage-ai-widget/node_modules/nx/src/project-graph/file-map-utils.js:27:33)\n' +
    '    at /Users/ykra/projects/vonage-projects/vonage-ai-widget/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:92:85\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at fulfilled (/Users/ykra/projects/vonage-projects/vonage-ai-widget/node_modules/tslib/tslib.js:115:62)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)',
  message: "Cannot read properties of undefined (reading 'endsWith')\n" +
    '\n' +
    'Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.\n' +
    'If the error persists, please run "nx reset".'
}

### Environment
     Node : 16.13.0
   OS   : darwin x64
   npm  : 8.1.0
   
   nx : 14.0.5
   @nrwl/angular : 14.1.1
   @nrwl/cypress : 14.0.5
   @nrwl/detox : 13.4.1
   @nrwl/devkit : 14.0.5
   @nrwl/eslint-plugin-nx : 14.0.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.5
   @nrwl/js : 14.0.5
   @nrwl/linter : 14.0.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.0.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.4.1
   @nrwl/react-native : 13.4.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.1
   @nrwl/web : 14.0.5
   @nrwl/workspace : 14.0.5
   typescript : 4.6.4
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:

**Comment by AgentEnder** [comment]
Hey @YonatanKra , it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

**Comment by YonatanKra** [comment]
Migrating does work!   Thanks!
It is surprising that creating an nx workspace and installing stuff from scratch creates this issue.
This enters into my magic arsenal right after `rm -rf node_modules && npm i` ;)
Thanks for the quick solution!

**Comment by AgentEnder** [comment]
FWIW, creating a new workspace and installing packages that match that workspace's version should work, its just that in your repo the packages were misaligned. Its likely that you ran `npx create-nx-workspace` instead of `npx create-nx-workspace@latest`, and then `npm I @nrwl/angular` installed the latest version of the plugin.
