### ISSUE TITLE
Error creating express application

### ISSUE THREAD

**Issue by wmedia** [nrwl/nx#10140]
## Current Behavior
Error creating a express (v14.1.1) application, sends this:
Cannot find module 'nx/src/generators/utils/json'

## Expected Behavior
Create a express application

## Steps to Reproduce
 yarn add @nrwl/express -W
 yarn nx g @nrwl/express:application api

### Failure Logs
Cannot find module 'nx/src/generators/utils/json'
Require stack:
- /home/wmediape/angular/example/node_modules/@nrwl/express/node_modules/@nrwl/devkit/src/generators/format-files.js
- /home/wmediape/angular/example/node_modules/@nrwl/express/node_modules/@nrwl/devkit/index.js
- /home/wmediape/angular/example/node_modules/@nrwl/express/src/generators/application/application.js
- /home/wmediape/angular/example/node_modules/nx/src/config/workspaces.js
- /home/wmediape/angular/example/node_modules/nx/src/command-line/generate.js
- /home/wmediape/angular/example/node_modules/nx/src/command-line/nx-commands.js
- /home/wmediape/angular/example/node_modules/nx/bin/init-local.js
- /home/wmediape/angular/exmple/node_modules/nx/bin/nx.js
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by mwarger** [comment]
This is also occurring when generating a node application and NX 13.10.3.

Reproduce:
```
npm i @nrwl/node
npx nx generate @nrwl/node:application myapp --no-interactive
```

Cannot find module 'nx/src/generators/utils/json'

**Comment by AgentEnder** [comment]
Can each of you run `nx report` and paste the output here?

**Comment by mwarger** [comment]
```
  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : darwin arm64
   npm  : 8.5.0
   
   nx : 13.10.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.3
   @nrwl/eslint-plugin-nx : 14.1.1
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.1
   @nrwl/js : 14.1.1
   @nrwl/linter : 14.1.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.1.1
   @nrwl/nx-cloud : 14.0.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.1.1
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.1
   @nrwl/web : 14.1.1
   @nrwl/workspace : 13.10.3
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         nx-electron: 13.0.0
```

**Comment by wmedia** [comment]
>  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : linux x64
   npm  : 8.5.5
   
   nx : 14.0.5
   @nrwl/angular : 13.10.3
   @nrwl/cypress : 13.10.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.3
   @nrwl/eslint-plugin-nx : 13.10.3
   @nrwl/express : 13.10.3
   @nrwl/jest : 13.10.3
   @nrwl/js : 13.10.3
   @nrwl/linter : 13.10.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 13.10.3
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.3
   @nrwl/web : Not Found
   @nrwl/workspace : 13.10.3
   typescript : 4.6.4
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:
         @datorama/akita: 7.1.1

**Comment by wmedia** [comment]
I have deleted the yarn.lock and make yarn install to recreate the lock. after that  the command yarn nx g @nrwl/express:application api worked, and does not show errors and created the application, but now 
yarn nx serve api throws a new error:

TypeError: Cannot read properties of undefined (reading 'endsWith')
    at createProjectRootMappings (/home/wmediape/angular/example/node_modules/nx/src/project-graph/file-map-utils.js:12:38)
    at createProjectFileMap (/home/wmediape/angular/example/node_modules/nx/src/project-graph/file-map-utils.js:27:33)
    at /home/wmediape/angular/example/node_modules/nx/src/project-graph/build-project-graph.js:26:97
    at Generator.next (<anonymous>)
    at /home/wmediape/angular/example/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/wmediape/angular/example/node_modules/tslib/tslib.js:114:16)
    at buildProjectGraph (/home/wmediape/angular/example/node_modules/nx/src/project-graph/build-project-graph.js:24:20)
    at /home/wmediape/angular/example/node_modules/nx/src/project-graph/project-graph.js:51:66
    at Generator.next (<anonymous>)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by koshpendi** [comment]
@wmedia the same error

**Comment by danghung-dev** [comment]
I have the same error when run storybook
```
❯ nx run share-ui:storybook --verbose

> nx run share-ui:storybook --verbose

Cannot find module 'nx/src/generators/utils/json'
Require stack:
- /Users/hung/Documents/work/projects/smartlog/stx/smartlog-app/node_modules.nosync/@nrwl/storybook/node_modules/@nrwl/devkit/src/generators/format-files.js
- /Users/hung/Documents/work/projects/smartlog/stx/smartlog-app/node_modules.nosync/@nrwl/storybook/node_modules/@nrwl/devkit/index.js
- /Users/hung/Documents/work/projects/smartlog/stx/smartlog-app/node_modules.nosync/@nrwl/storybook/src/executors/storybook/storybook.impl.js
- /Users/hung/Documents/work/projects/smartlog/stx/smartlog-app/node_modules.nosync/nx/src/config/workspaces.js
- /Users/hung/Documents/work/projects/smartlog/stx/smartlog-app/node_modules.nosync/nx/src/command-line/run.js
- /Users/hung/Documents/work/projects/smartlog/stx/smartlog-app/node_modules.nosync/nx/bin/run-executor.js
Error: Cannot find module 'nx/src/generators/utils/json'
Require stack:
- /Users/hung/Documents/work/projects/smartlog/stx/smartlog-app/node_modules.nosync/@nrwl/storybook/node_modules/@nrwl/devkit/src/generators/format-files.js
- /Users/hung/Documents/work/projects/smartlog/stx/smartlog-app/node_modules.nosync/@nrwl/storybook/node_modules/@nrwl/devkit/index.js
- /Users/hung/Documents/work/projects/smartlog/stx/smartlog-app/node_modules.nosync/@nrwl/storybook/src/executors/storybook/storybook.impl.js
- /Users/hung/Documents/work/projects/smartlog/stx/smartlog-app/node_modules.nosync/nx/src/config/workspaces.js
- /Users/hung/Documents/work/projects/smartlog/stx/smartlog-app/node_modules.nosync/nx/src/command-line/run.js
- /Users/hung/Documents/work/projects/smartlog/stx/smartlog-app/node_modules.nosync/nx/bin/run-executor.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/hung/Documents/work/projects/smartlog/stx/smartlog-app/node_modules.nosync/@nrwl/storybook/node_modules/@nrwl/devkit/src/generators/format-files.js:6:16)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "share-ui:storybook" failed
```

Here is my report
```
 nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : darwin x64
   yarn : 1.22.10
   
   nx : 14.0.2
   @nrwl/angular : 14.0.2
   @nrwl/cypress : 14.0.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.0.2
   @nrwl/eslint-plugin-nx : 14.0.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.2
   @nrwl/js : Not Found
   @nrwl/linter : 14.0.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 13.3.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.4
   @nrwl/web : Not Found
   @nrwl/workspace : 14.0.2
   typescript : 4.6.3
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
         @ngrx/component-store: 13.1.0
         @nx-tools/nx-docker: 2.3.0
         ng-zorro-antd: 13.1.1
         @nx-dotnet/core: 1.9.11
         @storybook/angular: 6.4.22
```

**Comment by zach-herridge** [comment]
I get the same error


```
yarn nx g @nrwl/react:application 
yarn run v1.22.18
$ /home/zach/workspace/air/node_modules/.bin/nx g @nrwl/react:application
✔ What name would you like to use for the application? · original-app
✔ Which stylesheet format would you like to use? · css
✔ Would you like to add React Router to this application? (y/N) · false
Cannot find module 'nx/src/generators/utils/json'
Require stack:
- /home/zach/workspace/air/node_modules/@nrwl/react/node_modules/@nrwl/devkit/src/generators/format-files.js
- /home/zach/workspace/air/node_modules/@nrwl/react/node_modules/@nrwl/devkit/index.js
- /home/zach/workspace/air/node_modules/@nrwl/react/src/utils/lint.js
- /home/zach/workspace/air/node_modules/@nrwl/react/src/generators/application/application.js
- /home/zach/workspace/air/node_modules/nx/src/config/workspaces.js
- /home/zach/workspace/air/node_modules/nx/src/command-line/generate.js
- /home/zach/workspace/air/node_modules/nx/src/command-line/nx-commands.js
- /home/zach/workspace/air/node_modules/nx/bin/init-local.js
- /home/zach/workspace/air/node_modules/nx/bin/nx.js
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```
Node : 16.14.2
   OS   : linux x64
   yarn : 1.22.18
   
   nx : 13.10.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.10.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.1
   @nrwl/eslint-plugin-nx : 13.10.1
   @nrwl/express : 13.10.4
   @nrwl/jest : 13.10.1
   @nrwl/js : 13.10.1
   @nrwl/linter : 13.10.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 13.10.1
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 13.10.4
   @nrwl/react : 14.1.4
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.4
   @nrwl/web : 14.1.4
   @nrwl/workspace : 13.10.1
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         @nxext/svelte: 13.3.1
````

**Comment by jiayisheji** [comment]
I error from e2e testing:

```ts
await runNxCommandAsync(`generate @nx-club/cz:init`); 
```

Report complete - copy this into the issue template

```text
   Node : 14.15.0
   OS   : win32 x64
   npm  : 6.14.8
   
   nx : 14.0.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.0.3
   @nrwl/eslint-plugin-nx : 14.0.3
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.3
   @nrwl/js : 14.0.3
   @nrwl/linter : 14.0.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 14.0.3
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.0.3
   typescript : 4.6.3
   rxjs : 6.6.7
```

**Comment by mwarger** [comment]
I tried another new app.  By using the `create-nx-workspace --preset empty`, it landed me on nx 13.X.  I tried creating multiple apps and got this same error.  However, I then did an `nx upgrade latest` without having created any apps.  This put me on the latest version of nx (14.1.4) and I was able to create apps without any issues (this includes the express app that failed for me as noted above).

**Comment by AsimNet** [comment]
I just had this issue after upgrading to: `14.0.1`
and it was solved after running these commands (upgrade Nx):
```
$: nx migrate latest
$: nx migrate --run-migrations
```

Reference: https://nx.dev/using-nx/updating-nx

**Comment by 0xZoomEye** [comment]
i got this error too 

Cannot find module 'nx/src/generators/utils/json'

nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.0
   OS   : linux x64
   npm  : 8.4.0
   
   nx : 13.10.4
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.4
   @nrwl/eslint-plugin-nx : 14.1.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.4
   @nrwl/js : 14.1.4
   @nrwl/linter : 14.1.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.1.4
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 13.10.4
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
