### ISSUE TITLE
On nx 14.0.3 -- nx migrate latest fails

### ISSUE THREAD

**Issue by fbartho** [nrwl/nx#10144]
## Current Behavior

```shell
$ yarn nx migrate latest
yarn run v1.22.17
[shortened]/node_modules/.bin/nx migrate latest

 ERROR  The migrate command failed.

Cannot read properties of undefined (reading 'split')
```

## Expected Behavior
I expect `nx migrate latest` to always succeed -- either it does nothing, or it updates package.json

## Steps to Reproduce

1. Create a package.json with the following packages
```json
{
  "devDependencies": {
     		"@nrwl/cli": "14.0.0",
		"@nrwl/eslint-plugin-nx": "14.0.1",
		"@nrwl/express": "14.0.1",
		"@nrwl/jest": "14.0.2",
		"@nrwl/linter": "14.0.0",
		"@nrwl/node": "14.0.2",
		"@nrwl/nx-cloud": "13.3.1",
		"@nrwl/workspace": "14.0.1",
		"nx": "14.0.3",
  }
}
```
2. create a working nx.json / workspace.json 
3. run `yarn nx migrate latest`

### Environment

```shell
$ yarn nx report
yarn run v1.22.17
[shortened]/node_modules/.bin/nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 14.0.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.0.1
   @nrwl/eslint-plugin-nx : 14.0.1
   @nrwl/express : 14.0.1
   @nrwl/jest : 14.0.2
   @nrwl/js : 14.0.2
   @nrwl/linter : 14.0.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.0.2
   @nrwl/nx-cloud : 13.3.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.0.1
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

✨  Done in 0.51s.
```

Related ticket: #10086

**Comment by AgentEnder** [comment]
Hey @fbartho! Do you care to try this again? There have been some fixes published that may have touched this area.

**Comment by fbartho** [comment]
@AgentEnder it still fails exactly as described above! let me know if you want me to try to migrate with any particular magic logging CLI arguments or Environment Variables.

**Comment by fbartho** [comment]
@AgentEnder this was introduced by #9849, embedding the context here:

>Specifically, it assumes that `devDependencies` exists and has versions for either package. Then it passes `undefined` to `isMigratingToNewMajor` which then passes undefined to `normalizeVersion` which expects a non-null string, so then that throws an error.
>
>Further context on why: We use `@manykg/cli` to manage our monorepo dependencies, which has an additional [rule that the top level package.json in a monorepo doesn't have a distinction between shipping deps and devDeps, so it recommends and enforces that you should just have one `dependencies` hash](https://github.com/Thinkmill/manypkg#root-has-devdependencies).
>
>The `Migrator` code below takes this into account, but this marketing code does not. Using stricter null-type checking on your tsconfig or linter settings would have flagged this section as potentially problematic.

Specific comments found here:
- https://github.com/nrwl/nx/commit/a162bfb420c2421319bdb7abdcefe7ecdc32fecb#r73241995
- https://github.com/nrwl/nx/commit/a162bfb420c2421319bdb7abdcefe7ecdc32fecb#r73241356

Please let me know if you need anything further, if necessary I can potentially submit a PR for this issue as it's still causing problems in our repository..

**Comment by fbartho** [comment]
Further info: this sometimes, but not always* replicates with a global install of `nx`, but it always replicates in our project when using the package.json-based install of `nx`.

*:  different developer machines see different behavior
