### ISSUE TITLE
Local cache miss when not forwarding arguments

### ISSUE THREAD

**Issue by arabull** [nrwl/nx#10145]
## Current Behavior
If a target runs using the `@nrwl/workspace:run-commands` executor and does not forward arguments, it results in cache misses if arguments are passed, even though the arguments are ignored.

## Expected Behavior
It should be a cache hit.

## Steps to Reproduce
1. Have one project with a target that runs a command using the `@nrwl/workspace:run-commands` executor. _The command should not forward arguments._
2. Have another project with a target that depends on the first target.
3. Run the first project's target with no arguments.
4. Run the second project's target _with arguments_. Because it is a dependency, the first target runs. Because the first target's arguments are not forwarded, the results should come from cache. They do not.

A repo that illustrates the problem is at https://github.com/arabull/nx-cache-miss.

### Environment
```
   Node : 18.0.0
   OS   : darwin x64
   npm  : 8.8.0
   
   nx : 14.0.5
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.0.5
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.5
   @nrwl/js : Not Found
   @nrwl/linter : 14.0.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.0.5
   typescript : 4.1.6
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by arabull** [comment]
@AgentEnder I don't want to be "that guy," but this issue is hurting us, so I'm going to... is there anything I can do to bump up the visibility on this guy? It's really hurting us on our builds. Ironically, it's hurting you guys too. We are paying Nx Cloud customers, and every cache miss costs you guys money. And this issue is causing _a lot_ of cache misses.

Outside of the reproduction repo I provided, please let me know if there's any other information I can provide. Thank you!

**Comment by AgentEnder** [comment]
Hey @arabull, I can't give a timeline on this but spent some time investigating it. In short, the default hasher for a task includes hashing any arguments passed to it. The **_default_** hasher, can't know how an executor is going to use them, and thus can't make any decisions based on certain args.

It is better for us to err on having extra cache misses compared to any extra cache hits, but I agree that perhaps a custom hasher for run-commands could be beneficial. I'm going to categorize this as a feature request, since the current implementation is performing as expected.

**Comment by arabull** [comment]
Would still like to see this addressed. It's costing us a ton of extra build time, and it's costing you guys money because we're not getting cloud cache hits.

**Comment by arabull** [comment]
This is really hurting us by artificially extending our build times. Any updates?

**Comment by arabull** [comment]
Would love to see this addressed.
