### ISSUE TITLE
Angular 13 ng cache support

### ISSUE THREAD

**Issue by swatghc** [nrwl/nx#10150]
## Current Behavior
As part of the Angular 13 upgrade, Angular CLI supports persistent disk cache by [default](https://angular.io/cli/cache), as [requested by the community](https://github.com/angular/angular-cli/issues/21545). 
 In `angular.json` file it allows us to turn the cache off by this:

```
{
    "$schema": "...",
    "cli": {
        "cache": {
            "enabled": false
        }
    }
    ...
}
```
We can also use the command `ng config cli.cache.enabled false` or `ng cache disable` introduced in this [PR](https://github.com/angular/angular-cli/pull/22851).

However, my project is in nx workspace, I don't see the options to turn the cache off in either `angular.json` or `nx.json`. And running the `nx cache` is not working either. 

## Expected Behavior
nx workspace should have the ability to turn off the angular cache.

## Steps to Reproduce
run `nx cache` in the root directory

### Failure Logs
```
$ nx cache
Unable to read workspace file 'C:\Workspace\zincore2\angular.json': Invalid format version detected - Expected:[ 1 ] Found: [ 2 ]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
### Environment
```
 >  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : win32 x64
   yarn : 1.22.10

   nx : 13.8.0
   @nrwl/angular : 13.8.0
   @nrwl/cli : 13.8.0
   @nrwl/cypress : 13.8.0
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.0
   @nrwl/eslint-plugin-nx : 13.8.0
   @nrwl/express : undefined
   @nrwl/jest : 13.8.0
   @nrwl/js : undefined
   @nrwl/linter : 13.8.0
   @nrwl/nest : 13.8.0
   @nrwl/next : undefined
   @nrwl/node : 13.8.0
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.0
   @nrwl/tao : 13.8.0
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.7
   typescript : 4.5.5
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
         @angular/animations: 13.3.2
         @angular/compiler: 13.3.2
         @angular/core: 13.3.2
         @angular/elements: 13.3.2
         @angular/forms: 13.3.2
         @angular/platform-browser: 13.3.2
         @angular/platform-browser-dynamic: 13.3.2
         @angular/router: 13.3.2
         @nestjs/azure-func-http: 0.6.0
         @ngrx/component-store: 13.0.2
         @ngrx/effects: 13.0.2
         @ngrx/entity: 13.0.2
         @ngrx/store: 13.0.2
         @ngrx/store-devtools: 13.0.2
         @angular-builders/custom-webpack: 13.1.0
         @angular-devkit/architect: 0.1302.2
         @angular-devkit/build-angular: 13.3.2
         @angular/cdk: 13.3.2
         @angular/cli: 13.3.2
         @angular/compiler-cli: 13.3.2
         @angular/language-service: 13.3.2
         @angular/material: 13.3.2
         @storybook/angular: 6.4.18
```

**Comment by AgentEnder** [comment]
@swatghc You should be able to set this in `nx.json` under the cli property, similar to how it would work in angular.json. Do you care to check?

**Comment by rfprod** [comment]
@swatghc

```json
...
"cli": {
    "cache": {
      "enabled": true, <--
      "environment": "all",
      "path": ".angular/cache"
    },
    "defaultCollection": "@nrwl/angular",
    "warnings": {
      "versionMismatch": false
    }
  },
...
```
https://github.com/rfprod/nx-ng-starter/blob/main/nx.json#L5-L15

Your failure log is weird, is something wrong with your `angular.json`?

Whan I execute `nx cache` it logs
```plaintext
>  NX   Cannot find target 'cache' for project 'client'
```
which seems correct.

**Comment by swatghc** [comment]
> @swatghc You should be able to set this in `nx.json` under the cli property, similar to how it would work in angular.json. Do you care to check?

Thanks @AgentEnder and @rfprod , it works as you suggested. Appreciate your help
