### ISSUE TITLE
Support additionalEntryPoints for `@nrwl/web:webpack`

### ISSUE THREAD

**Issue by ZouYouShun** [nrwl/nx#10178]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Hi Nx team, when I use `@nrwl/web:webpack`, I want to use that with my chrome-extension app,

and I found that additionalEntryPoints only work in `@nrwl/node:webpack`, 

although I can implement that inside my custom webpack, but I think that will be good when that implement inside `web:webpack`

could we add that `additionalEntryPoints` into nx?😎

**Comment by FrozenPandaz** [comment]
Hey, I'm curious what kind of additional entry point you are adding? Is it lazy loading a file or is it something else?

**Comment by ZouYouShun** [comment]
> 

Hi @FrozenPandaz , I use that in chrome development, 

there have many entry points for that, like `background`, `content_scripts`, that is not lazy load file

https://github.com/lxieyang/chrome-extension-boilerplate-react/blob/master/src/manifest.json
