### ISSUE TITLE
Docs: add a link executor docs header for related "Discussions" and/or "Issues" (link can contain a label querystring filter)

### ISSUE THREAD

**Issue by hcharley** [nrwl/nx#10173]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.

https://nx.dev/packages/node/executors/webpack

### Additional context or description

Provide any additional details here as needed.

#### Docs feature idea

Links could be placed on doc pages for executors to take users to related Github "Discussions" and/or Github "Issues". "Related" Discussions & Issues could be based on Github "Labels." 

Another idea could be to add a link to a "Start discussion" or "Ask question" to start a new Discussion with related Labels automatically added. 

#### Example link with label(s):

https://github.com/nrwl/nx/discussions?discussions_q=label%3Astale

https://github.com/nrwl/nx/discussions?discussions_q=label%3Astale+label%3A%22scope%3A+node%22

#### Additional labels

Additional labels would probably need to be added, one for each executor, so it might not make since for this repo's maintainers to actually do.

**Comment by FrozenPandaz** [comment]
Can you be more specific about the workflow where you think this link would be useful?

Is it for someone who has an issue and is reading the docs?
Is it for someone who has never used the executor and wants to see discussion?
