### ISSUE TITLE
lazy loaded path not added to parent module router paths

### ISSUE THREAD

**Issue by markgoho** [nrwl/nx#1017]
## Expected Behavior

When running `ng g lib` with flags `--lazy --routing --parent-module` the parent module that gets passed in (under very specific circumstances) gets updated with a new path referencing that lazy loaded module. 

## Current Behavior
What is the current behavior?

That "very specific circumstance" is when that module has in its list of imports a RouterModule.forChild (or forRoot) and an array of routes inside it. That is the only time the schematic property updates that array and adds the path to the lazy loaded module.

## Failure Information (for bugs)

One interesting thing to note is that in every case, the module that gets passed in shows up on the list of updated files, e.g.

``` bash
UPDATE angular.json (17042 bytes)
UPDATE nx.json (934 bytes)
UPDATE tsconfig.json (1344 bytes)
UPDATE libs/privacy/src/lib/privacy.module.ts (498 bytes)
```
however upon inspecting the module, nothing has actually changed

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create a module in your project
2. move the router paths out of the imports array and put it somewhere else (some folks like to put the entire thing into a separate `module.routing.ts` file or something like that)
3. generate a new lazy loaded module using the nx schematic (`ng g lib --lazy --routing --parent-module`) and pass in that first module to the parent module flag
4. see that nothing in that module was changed

### Context

Using Nx 7.4.1

### Other helpful information

The critical code is here: https://github.com/nrwl/nx/blob/master/packages/schematics/src/utils/ast-utils.ts#L438

My AST comprehension is somewhat low, but from what I can tell, this function right off the bat looks for the imports array in the `@NgModule` decorator and starts from there. So that's probably something that could be a little more flexible at least for scenarios where folks put the array of routes in the same file, but as a separate constant.

I'm thinking Nx has to be a little conservative with the number of patterns that it supports so the schematics files aren't looking in 17 different places.

So perhaps the proposal would be:
Add the new route to whatever `route` const that exists in the module that gets passed into the `--parent-module` flag. If the end user passes in a `my-module.routing.ts` file there, the schematic will expect the routes to be defined in that way.

**Comment by brandonroberts** [comment]
@markgoho will you verify this is still an issue with the latest version of Nx?

**Comment by FrozenPandaz** [comment]
Closing this issue as it is very old and not actionable. Please open a new issue if you have more ideas for how this can be enhanced.
