### ISSUE TITLE
Support Next.js with Expo for Web

### ISSUE THREAD

**Issue by timothymiller** [nrwl/nx#10177]
- [x ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Today, `@nrwl/next` & `@nrwl/expo` support Next.js and Expo apps respectively, but not in the same application.

[This link ](https://docs.expo.dev/guides/using-nextjs/)shows the use case

It would be wonderful if there was first party support to implement the Expo SDK for a Next.js app in a NX monorepo.

## Motivation

At Porsche Digital, we are happy users of the NX monorepo. We would like to increase code re-use across our Next.js and React Native projects.  One way to do this would be to use the Expo SDK with Next.js to gain access to Expo's wonderful universal components.

**Comment by jaysoo** [comment]
Hi @timothymiller it's definitely something we can look into. It looks like `@expo/next-adapter` is experimental so I'm not sure if we will integrate it at this point.

You can definitely integrate it after first generating an app using `nx g @nrwl/expo:app`. If I have some time I'll see if I can create an example for this.

Happy you chat further about this!

**Comment by KaneLabs** [comment]
This would be huge. Check out Solito who is focused on bridging Next and React Native Web. They're 6 months old and have 1K stars.

**Comment by kenchoong** [comment]
This will be HUGE!

**Comment by amosbastian** [comment]
I've made an example with Nx using Expo, Next.js and Solito [here](https://github.com/amosbastian/nx-expo-nextjs), hopefully it's useful to someone 😄

**Comment by RileySeaburg** [comment]
> * [x ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))
> 
> ## Description
> Today, `@nrwl/next` & `@nrwl/expo` support Next.js and Expo apps respectively, but not in the same application.
> 
> [This link ](https://docs.expo.dev/guides/using-nextjs/)shows the use case
> 
> It would be wonderful if there was first party support to implement the Expo SDK for a Next.js app in a NX monorepo.
> 
> ## Motivation
> At Porsche Digital, we are happy users of the NX monorepo. We would like to increase code re-use across our Next.js and React Native projects. One way to do this would be to use the Expo SDK with Next.js to gain access to Expo's wonderful universal components.
> 
> ## Suggested Implementation
> ## Alternate Implementations

I'm just curious if @timothymiller is willing to implement this feature, why not ask to submit a PR with the feature rather than writing it off as experimental?
