### ISSUE TITLE
Using ngx-bootstrap breaks mfe setup due to bad package.json name

### ISSUE THREAD

**Issue by yharaskrik** [nrwl/nx#10187]
## Current Behavior

When trying to use `ngrx-bootstrap/carousel` in our application that is using MFE we get 

![image](https://user-images.githubusercontent.com/9469090/167157766-04dfe4d9-ac13-411e-957c-066d81f25c7c.png)

I have tracked that down to the package.json for ngx-bootstap/schematis using the name `schematics` not `ngx-bootstrap/schematics` for the `name` property. Don't think schematics is used anywhere (we are only using carousel) but this errors the build.

## Expected Behavior

Should be able to import ngx-bootstrap into mfes

## Steps to Reproduce

generate angular workspace
add host app
add remote app
import ngx-boostrap/carousel into host app (or remote or both)

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

Same as a fresh workspace (any version support mfes)

**Comment by leosvelperez** [comment]
hey @yharaskrik!

Could you please retry with the latest version? We recently released a [fix](https://github.com/nrwl/nx/pull/10129) that should have addressed this issue. Another [fix](https://github.com/nrwl/nx/pull/10216) is in progress to address a separate issue that can happen when collecting those secondary entry points for MF builds.
