### ISSUE TITLE
deploy multiple apps to different vercel projects

### ISSUE THREAD

**Issue by vincent-thomas** [nrwl/nx#10186]
### Discussed in https://github.com/nrwl/nx/discussions/6275

<div type='discussions-op-text'>

<sup>Originally posted by **salzhrani** July  6, 2021</sup>
The documentation explains how deploy a single app. Also, it recommends agains changing the root folder. how can we configure nx/vercel to   to deploy multiple apps to different projects properly and without triggering builds for other projects.  anyone who have done this please chime in. </div>

It doesn't say anything about it in the docs and it would be really nice if someone could clarify!

**Comment by vincent-thomas** [comment]
Commenting to keep this issue up

**Comment by MatthewPosgate** [comment]
same question for me too

**Comment by matthewherbstritt** [comment]
I'm unsure about this, too. Anyone have any ideas?

**Comment by matthewherbstritt** [comment]
Seems https://nx.dev/guides/deploy-nextjs-to-vercel covers it after all. 

The key point I was missing was to add the `npx nx-ignore <app-name>` command under Project Settings > Git on Vercel.

**Comment by mrlubos** [comment]
@matthewherbstritt man, your comment is less than 3 weeks old and the link is already broken. Reported in https://github.com/nrwl/nx/issues/11839

**Comment by mandarini** [comment]
Hi there! The new docs page can be found here: https://nx.dev/recipe/deploy-nextjs-to-vercel

Apologies for any inconvenience caused by the restructuring, I respect your frustration. You can use the quicksearch feature to find the pages that have been moved!

Let me know if this helps!

**Comment by mandarini** [comment]
Hi there! The new docs page can be found here: https://nx.dev/recipe/deploy-nextjs-to-vercel

Apologies for any inconvenience caused by the restructuring, I respect your frustration. You can use the quicksearch feature to find the pages that have been moved!

Let me know if this helps!
