### ISSUE TITLE
After adding any of generators the global nx starting crashing

### ISSUE THREAD

**Issue by HackPoint** [nrwl/nx#10197]
Nx Report:
```
 Node : 16.14.2
   OS   : darwin x64
   npm  : 8.5.0
   
   nx : 14.0.3
   @nrwl/angular : 10.4.7
   @nrwl/cypress : 10.4.7
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.0.3
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 10.4.7
   @nrwl/js : Not Found
   @nrwl/linter : 10.4.7
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 10.4.7
   @nrwl/web : Not Found
   @nrwl/workspace : 10.4.7
   typescript : 4.0.8
   rxjs : 6.5.5
   ---------------------------------------
   Community plugins:

Error:

{
  stack: "TypeError: Cannot read properties of undefined (reading 'endsWith')\n" +
    '    at createProjectRootMappings (/Users/user/dev/work-projects/dex-workspace/gcc-ui/node_modules/nx/src/project-graph/file-map-utils.js:12:38)\n' +
    '    at createProjectFileMap (/Users/myuser/dev/work-projects/dex-workspace/gcc-ui/node_modules/nx/src/project-graph/file-map-utils.js:27:33)\n' +
    '    at /Users/myuser/dev/work-projects/dex-workspace/gcc-ui/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:92:85\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at fulfilled (/Users/myuser/dev/work-projects/dex-workspace/gcc-ui/node_modules/tslib/tslib.js:115:62)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)',
  message: "Cannot read properties of undefined (reading 'endsWith')\n" +
    '\n' +
    'Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.\n' +
    'If the error persists, please run "nx reset".'
}

**Comment by HackPoint** [comment]
@vsavkin @jeffbcross

**Comment by marwan38** [comment]
I had this issue as well, I found it to be caused by mismatching nx versions between packages, and I had forgotten to run `npm i` after upgrading the packages.

**Comment by AgentEnder** [comment]
Hey @HackPoint, it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

**Comment by HackPoint** [comment]
@AgentEnder hi sure I will try to verify that versions are lined up. But I’m unable to update. I need to support lower versions of angular. Because of the legacy components that I’m working on. Otherwise sure. The first thing o would do, is update.

**Comment by HackPoint** [comment]
@vsavkin Can you help? Spent so many hours and every time the nx breaks. Is it possible to use old angular9-10 and use the latest nx? 
@AgentEnder

**Comment by AgentEnder** [comment]
The versions have to be in line, or it will not work. Specifically, the compatibility layer for angular lives in the core of Nx. That compatibility layer is itself tied pretty heavily to very specific versions of angular, as they have changed the internals of the library over time.

If you cannot update, your options are downgrading the packages which are at higher versions to match the versions in your existing workspace (10.4.7).

**Comment by HackPoint** [comment]
> The versions have to be in line, or it will not work. Specifically, the compatibility layer for angular lives in the core of Nx. That compatibility layer is itself tied pretty heavily to very specific versions of angular, as they have changed the internals of the library over time.
> 
> If you cannot update, your options are downgrading the packages which are at higher versions to match the versions in your existing workspace (10.4.7).

Which means? Sorry for my bad english. I haven't understood you.
