### ISSUE TITLE
Name of remote module required to be remoteEntry.mjs

### ISSUE THREAD

**Issue by oschlegel** [nrwl/nx#10206]
Hi, i'm integrating your module federation features for a projct and found out that you required the name of remote modules for be `remoteEntry.mjs` [here](https://github.com/nrwl/nx/blob/master/packages/angular/mfe/mfe.ts#L61). This is a issue since i have to integrate remote modules which are named differently. Wouldn't it be a better approach to check if `remoteUrl` already includes the filename and only add `remoteEntry.mjs` as fallback?

```
   Node : 16.14.0
   OS   : darwin x64
   npm  : 8.3.1
   
   nx : 14.1.4
   @nrwl/angular : 14.1.4
   @nrwl/cypress : 14.1.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.4
   @nrwl/eslint-plugin-nx : 14.1.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.4
   @nrwl/js : Not Found
   @nrwl/linter : 14.1.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.4
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.4
   typescript : 4.6.3
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
         @ngneat/spectator: 10.0.0
         angular-playground: 9.0.1
         ng-mocks: 13.1.0
```

**Comment by Coly010** [comment]
Hey 😄 

Are you also using our `withModuleFederation` helper to expose the remote entry? If so, it is also set to `remoteEntry.mjs`. Where do you have a difference?

**Comment by oschlegel** [comment]
Hi, i have a mixed setup. Part of my remote modules are located within my nx workspace and are using `withModuleFederation`, but other remote modules are maintained in other repostories which are not using nx tooling.

**Comment by ubergeoff** [comment]
Can we also have this fixed for the manifest files..?

**Comment by Kavebo** [comment]
> 

How did you manage to configure Nx monorepo to use module which is now build with _withModuleFederation_? I'm trying to do it 2 days without success. All examples are just using apps from monorepo itself or it's configured with ModuleFederationPlugin without nx tooling.

I'm always getting error like:
`fn is not a function. (In 'fn(arg1, arg2)', 'fn' is undefined)
while loading "./Module" from 2636
`

remoteEntry.js from "external" repo app is loaded but this is everything.
