### ISSUE TITLE
JS library generator always includes "build" target even when not buildable

### ISSUE THREAD

**Issue by ajwootto** [nrwl/nx#10224]
## Current Behavior

If you generate a js lib with `nx g @nrwl/js:lib my-lib`, that lib will include a "build" target even though the `--buildable` option was not specified.

It also seems to generate a package.json file which doesn't include a "name" field.

## Expected Behavior

I would expect the build target to not be added for a non-buildable JS lib.

I'd also expect there to be no package.json file in the generated output.
## Steps to Reproduce

`nx g @nrwl/js:lib my-lib`

### Environment

```
 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : darwin x64
   yarn : 3.1.0

   nx : 14.1.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.4
   @nrwl/eslint-plugin-nx : 14.1.4
   @nrwl/express : 14.1.4
   @nrwl/jest : 14.1.4
   @nrwl/js : 14.1.4
   @nrwl/linter : 14.1.4
   @nrwl/nest : 14.1.4
   @nrwl/next : Not Found
   @nrwl/node : 14.1.4
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 14.1.4
   @nrwl/workspace : 14.1.4
   typescript : 4.6.4
   rxjs : 7.2.0
```

**Comment by ajwootto** [comment]
not stale

**Comment by mandarini** [comment]
This issue has been addressed in the latest version of Nx.

Running:

```
npx nx generate @nrwl/js:library my-lib --buildable=false
```

will generate a non-buildable library, no `build` target, no `package.json`.

If you look at the documentation, the [`buildable` option](https://nx.dev/packages/js/generators/library#buildable) is set to `true` by default, so you need to specifically pass `--buildable=false`.
