### ISSUE TITLE
github npm registry does not allow custom fields on `npm view`, breaking migrations

### ISSUE THREAD

**Issue by gioragutt** [nrwl/nx#10223]
## Current Behavior

[Discussion on slack](https://nrwlcommunity.slack.com/archives/CMFKWPU6Q/p1650630724184429).

`nx migrate` relies on `npm view` to get information about migrations to run from updated packages, specifically by getting the `ng-update` or `nx-migration` fields.

However, in the case of packages that reside in the github package registry, its implementation of `npm view` does not return custom fields.

In that case, [getting the package with npm view](https://github.com/nrwl/nx/blob/master/packages/nx/src/command-line/migrate.ts#L522) will not fail since `npm view` does not throw, so it does not fall back to [getting the package with package-manager install](https://github.com/nrwl/nx/blob/master/packages/nx/src/command-line/migrate.ts#L527).

This results in migrations not being picked up.

## Expected Behavior

All packages, including those under the github package registry, should allow migrations.

I've been in contact with the github support team, and it's been communicated that exposing arbitrary package.json fields is not prioritized and will not be implemented any time soon.

Given that, my suggestion is to special-case the npm github package registry to opt out of the `npm view` behavior.

### Failure Logs

There are no failures, as `npm view`, in this case, acts as if the package has no migrations.

### Environment

This is not an NX issue, so it will happen on all versions with the `npm view` behavior.

**Comment by tremppu** [comment]
Any updates? Just started using GitHub Packages for our organization and this bug makes life difficult atm...

**Comment by EkatZaytseva** [comment]
Hey; any update on this? This is definitely not stale as issue is still there.

**Comment by AgentEnder** [comment]
This was fixed by #16423
