### ISSUE TITLE
.ignore file to exclude modules

### ISSUE THREAD

**Issue by mklueh** [nrwl/nx#10258]
I'm in the following situation:

Migrating an old NX project with Vue 2 / Nuxt 2 modules to Vue 2 / Nuxt 3. Something bites when I execute yarn install, as some packages are missing required to run the Nuxt 3 application. My guess is that there are conflicts somewhere between old and new packages.

Is there a way to exclude modules of my workspace entirely, so that yarn install won't pick up their package.json files?

**Comment by AgentEnder** [comment]
If you're using yarn workspaces, you'd need to update the workspaces key in the root package.json I believe.
