### ISSUE TITLE
Deploying a small sized Next.js project with SSR

### ISSUE THREAD

**Issue by ShadiBlitz** [nrwl/nx#10255]
Hello team! I need urgent help.
I am using NX monorepo for my current project where I have a next.js dashboard app located in /apps/dashboard , this app is widely implementing the SSR feature using getServerSideProps.
I am trying to deploy this next.js app (dashboard) to production. I have used yarn build and yarn serve and everything went smoothly, however, I want to deploy it without having all the node_modules and the whole monorepo. I tried making a [standalone](https://nextjs.org/docs/advanced-features/output-file-tracing) build but that didn't work, i got the same issues in [here](https://github.com/nrwl/nx/issues/9017).
Currently I want to deploy to Azure using a docker container, and I am really looking for a small size docker image.
I need your help. Thanks !

## Current Behavior
Can't build a standalone next.js app.
Unavoidable bloated node_modules folder.

## Steps to Reproduce

Build the app using nx build
`yarn nx run dashboard:build --configuration=production`

the build output will be in `dist/apps/dashboard` , however, this can't be run by it self, it needs the whole nx monorepo packages.
my run command `yarn nx run dashboard:serve --configuration=production`

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by ndcunningham** [comment]
Hey! Thanks for opening this. 
When it comes to deploying next apps, using Nx, Vercel is first class.
Artifacts inside `dist/apps/<app>` are self-containted so usually you should be able to deploy that folder and run `npx next start` from it.
We will look into other deployment targets, as currently there maybe a few issues left to be ironed out.

**Comment by jaysoo** [comment]
One more note, the compiled `dist/apps/<app>` folder can be copied/deployed elsewhere, and you just need to `npm install` or yarn install` and run `npx next start` as Nicholas said above.

**Comment by ShadiBlitz** [comment]
I think you are guys are not following here.
I want to run the nextjs application with SSR support and not having to install all the dependencies of the monorepo.
I want to avoid installing unnecessary packages!!

**Comment by dwfee** [comment]
I'm having the same problem trying to deploy multiple nextjs ISR apps, using libs for comonents etc. Nx does not even do the package.json correctly. Server.js is not ported etc. So I'm thinking of doing whole nx monorepo in docker. I'm using wsl, with the same distro as my server. Hopefully this works.

**Comment by kaceycleveland** [comment]
For building a docker image with NX and NextJS and to maintain a small image size, I would recommend using this in your `next.config.js`:

```  
experimental: {
    // See: https://github.com/nrwl/nx/issues/9017
    outputStandalone: true,
    outputFileTracingRoot: path.join(__dirname, '../../'),
  },
  
```

This should dramatically decrease your image size and in addition, you do not need to do a `npm install` in the built standalone build. The package.json is incorrect however the image size is small and the application should work without `npm install` so the package.json should not matter really. For the Docker file, you can basically copy the standalone files over and that should be it.


```
FROM node:16-alpine
WORKDIR /app

ENV NODE_ENV=production

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

COPY --chown=nextjs:nodejs dist/apps/public-app/.next/standalone .
COPY --chown=nextjs:nodejs apps/public-app/public ./apps/public-app/public

USER nextjs

EXPOSE 3100

ENV PORT 3100

CMD ["node", "apps/public-app/server.js"]
```

**Comment by moatorres** [comment]
@kaceycleveland, thank you for your example. I was actually wondering if Next's standalone build actually meant "standalone". Not having to reinstall/rebuild the app inside Docker currently saves me 13 minutes. 👍 

One thing that I haven't got my head around yet is the Dockerfile paths. I'm apparently unable to copy from `dist/apps/...`:

```sh
...
 => CANCELED [4/6] RUN adduser -S nextjs -u 1001                                                                                                                                 0.8s
 => ERROR [5/6] COPY --chown=nextjs:nodejs dist/apps/public-app/.next/standalone .                                                                                                     0.0s
 => ERROR [6/6] COPY --chown=nextjs:nodejs apps/public-app/public ./apps/public-app/public 
```

That is, when running from the workspace root:

1. Run `nx build public app`
2. Run `docker buildx build -t ghcr.io/me/public-app ./apps/docs`

Any thoughts would be very appreciated. ☺️

**Comment by raymondKelly** [comment]
> here

@kaceycleveland as mentioned in the description link https://github.com/nrwl/nx/issues/9017 that is currently not supported in NX
