### ISSUE TITLE
Web dev-server executor should support generateIndexHtml

### ISSUE THREAD

**Issue by cloudratha** [nrwl/nx#10263]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
The Web webpack executor supports "generateIndexHtml" option which allows the developer to implement their own index.html generation, ie using something like HtmlWebpackPlugin.

This however isn't honored in the dev-server executor, resulting in duplication of emitted files for index.html.
I would like to see the optional flag introduced for the dev-server that omits the addition of the default html plugin: https://github.com/nrwl/nx/blob/5251bd73acb5ac52d37b0795e26346b02dba24f7/packages/web/src/utils/devserver.config.ts#L49

## Motivation
It seems weird we allow it for production builds but expect the developer to manipulate the dev-server webpack plugins to support a custom index.html generator.

## Suggested Implementation
I would hope simply wrapping the above in a configuration flag would do the trick.

## Alternate Implementations
:(

**Comment by bheftel** [comment]
@cloudratha - I hit this issue too, but there is a hacky workaround to just remove the `IndexHtmlWebpackPlugin` until there can be a config flag to conditionally include it. This is working for me in a custom webpack config.

```
module.exports = function override(config, context) {
  if (context.configuration === 'development') {
    const filteredPlugins = config.plugins.filter(
      (plugin) => plugin.constructor.name !== 'IndexHtmlWebpackPlugin'
    );
    config.plugins = filteredPlugins;
  }

  return merge(config, {
    plugins: [
      new HtmlWebpackPlugin({
        templateParameters: { customParams },
        template: 'src/index.html',
      }),
    ],
  });
};

```
