### ISSUE TITLE
Running affected:xx command from npm 

### ISSUE THREAD

**Issue by daBishMan** [nrwl/nx#1026]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

I have the the following scripts in my package.json
`
 "affected:check": "npm run affected:check:lint && npm run affected:check:test && npm run affected:check:build",
        "affected:check:lint": "npx nx affected:lint --base=HEAD --parallel --maxParallel 4",
        "affected:check:test": "npx nx affected:test --base=HEAD --parallel --maxParallel 4",
        "affected:check:build": "npx nx affected:build --base=HEAD --prod --parallel --maxParallel 4"
`
If I run "npm run affected:check" I expect the 3 scripts to run in sequentially

## Current Behavior
the first command runs but it stops at 
`
Running lint for affected projects succeeded.
`
Not at a prompt just that last line in the console. 

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  create a new nx-workspace
2.  create a branch and then run the script above
3.  it stops after the first script is ran.
4.  But if you remove the parrallel flag out it works.

### Context

Please provide any relevant information about your setup:

> Angular CLI: 7.2.3
Node: 10.13.0
OS: win32 x64
Angular: 7.2.2
... animations, cdk, common, compiler, compiler-cli, core
... elements, forms, http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.12.3
@angular-devkit/build-angular      0.12.3
@angular-devkit/build-ng-packagr   0.12.3
@angular-devkit/build-optimizer    0.12.3
@angular-devkit/build-webpack      0.12.3
@angular-devkit/core               7.2.3
@angular-devkit/schematics         7.2.3
@angular/cli                       7.2.3
@ngtools/webpack                   7.2.3
@schematics/angular                7.2.3
@schematics/update                 0.12.3
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.28.4

**A minimal reproduce scenario using allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

Please include any relevant log snippets or files here.

## Other

Any other relevant information that will help us help you.

**Comment by vsavkin** [comment]
Unfortunately, I cannot reproduce it.

Could you point to a repository with a min reproduction?

**Comment by TomDobbelaere** [comment]
I have this issue too on our Azure Pipelines :\

**Comment by vsavkin** [comment]
Fixed it here: https://github.com/nrwl/nx/pull/1697
