### ISSUE TITLE
nx g scam doesn't want to work sometimes

### ISSUE THREAD

**Issue by e-oz** [nrwl/nx#10260]
## Current Behavior

```
nx g scam test
```
gives error:

```
TypeError: this.tree.readText is not a function
    at TreeWorkspaceHost.readFile (/path/node_modules/@schematics/angular/utility/workspace.js:23:26)
    at readJsonWorkspace (/path/node_modules/@angular-devkit/core/src/workspace/json/reader.js:17:28)
    at Object.readWorkspace (/path/node_modules/@angular-devkit/core/src/workspace/core.js:91:62)
    at async getWorkspace (/path/node_modules/@schematics/angular/utility/workspace.js:73:27)
    at async /path/node_modules/@schematics/angular/component/index.js:96:27
this.tree.readText is not a function
```

## Expected Behavior

component generated

## Steps to Reproduce

It's reproducible in one project (TS 4.6), and not reproducible in another (TS 4.7).

### Environment

```
 Node : 18.1.0
   OS   : darwin x64
   npm  : 8.9.0
   
   nx : 14.1.5
   @nrwl/angular : 14.1.5
   @nrwl/cypress : 14.1.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.5
   @nrwl/eslint-plugin-nx : 14.1.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.5
   @nrwl/js : Not Found
   @nrwl/linter : 14.1.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.0.4-beta.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.5
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.5
   typescript : 4.6.4
   rxjs : 7.5.5
```

Looking at the error mesage, please give me a hint what should I try to fix/check.

**Comment by e-oz** [comment]
`nx g c test` gives the same error:
TypeError: this.tree.readText is not a function

**Comment by e-oz** [comment]
uh oh, I'll have to create them manually!

**Comment by e-oz** [comment]
I see, it's Angular bug. Ok, sorry for disturbing you :)

**Comment by nhhockeyplayer** [comment]
would be nice if they errored out and printed a log message to install missing packages... or smart enough to see if those packages were installed and do same.

any chance of documenting whats appropriate to have for packages for this to function?

i got bit by this on the 14 upgrade

I put these in my package.json and it now works
```
      "@angular-devkit/core": "^14.0.0",
      "@angular-devkit/schematics": "^14.0.0",
      "@schematics/angular": "^14.0.0",
      "@angular-devkit/build-webpack": "^0.1400.0",
      "@angular-devkit/architect":"^0.1400.0",
```

but I dont know what the specs are as of yet or how or what to do with these now as they sit in my package.json

**Comment by DesertFoxNV** [comment]
@e-oz I am seeing this as well. Did you find your solution in an angular issue? Or just come up with it on your own?
