### ISSUE TITLE
NX update migrations don't rename mfe.config in webpack configuration files

### ISSUE THREAD

**Issue by caeb92** [nrwl/nx#10271]
Hello!! Im currently using angular with module federation using the flag **federationType=dynamic**, I made a update to fix [issue 9861](https://github.com/nrwl/nx/issues/9861) in windows machines and work fine, but migrations are missing rename some file content.

## Current Behavior

After update my project **module-federation.config.js** and **webpack.config.js** keep old references to **mfe.config** , serve project crash becouse can't find **mfe.config** file in Angular MFE host and remote projects.

Same issue in MacOS 12.3.1 and Windows 11 machines

## Expected Behavior

NX may replace the reference for old name **mfe.config** to **module-federation.config.js** in **webpack.config.js** and **webpack.prod.config.js** configuration files in Angular MFE host and remote projects.

## Steps to Reproduce

- Upgrade NX workspace from version 13.10.2 to 14.1.5
- Follow **next steps** after upgrade
- Serve MFE Host with NX console

### Failure Logs

```bash
nx run host-app:serve:development

Generating browser application bundles (phase: setup)...Cannot find module './mfe.config'
Require stack:
- root/proyect-name/apps/host-app/webpack.config.js
- root/proyect-name/node_modules/@nrwl/angular/src/builders/utilities/webpack.js
- root/proyect-name/node_modules/@nrwl/angular/src/builders/webpack-server/webpack-server.impl.js
- root/proyect-name/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- root/proyect-name/node_modules/@angular-devkit/architect/node/index.js
- root/proyect-name/node_modules/nx/src/adapter/ngcli-adapter.js
- root/proyect-name/node_modules/nx/src/command-line/run.js
- root/proyect-name/node_modules/nx/bin/run-executor.js
```

### Environment

```
   Node : 14.15.5
   OS   : darwin x64
   npm  : 8.1.4
   
   nx : 14.1.5
   @nrwl/angular : 14.1.5
   @nrwl/cypress : 14.1.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.5
   @nrwl/eslint-plugin-nx : 14.1.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.5
   @nrwl/js : 14.1.5
   @nrwl/linter : 14.1.5
   @nrwl/nest : 14.1.5
   @nrwl/next : Not Found
   @nrwl/node : 14.1.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.5
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.5
   typescript : 4.6.3
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:
```

**Comment by caeb92** [comment]
After upgrade and install dependencies works fine but I restart VSCode and run my host app,  my web browser now is throwing 404 error can't find **/assets/module-federation.manifest.json**

The file **main.ts** of my host project is calling the file as **module-federation.manifest.json** not **module-federation.config.json**

```javascript
import { setRemoteDefinitions } from '@nrwl/angular/mfe';

fetch('/assets/module-federation.manifest.json')
  .then((res) => res.json())
  .then((definitions) => setRemoteDefinitions(definitions))
  .then(() => import('./bootstrap').catch((err) => console.error(err)));
```

I rename the reference in **main.ts** as **module-federation.config.json**, works fine

**Comment by Coly010** [comment]
I'm sorry you encountered this issue! As you have seen, it was straightforward to fix. I'm going to close this issue as there isn't anything we can do from an Nx side to address this. 

Thanks for raising this !
