### ISSUE TITLE
Storybook generator creates stories for stories

### ISSUE THREAD

**Issue by Brian-McBride** [nrwl/nx#10286]
## Current Behavior
Storybook `npx nx generate @nrwl/react:stories` is creating stories for files that have `.stories` in the name. 

## Expected Behavior
Stories should only be created for actual component files.

## Steps to Reproduce
`npx nx generate @nrwl/react:stories --project=<your compont project>

### Environment
```
Node : 16.13.1
   OS   : darwin x64
   npm  : 8.10.0
   
   nx : 14.1.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.5
   @nrwl/eslint-plugin-nx : 14.1.5
   @nrwl/express : 14.1.5
   @nrwl/jest : 14.1.5
   @nrwl/js : 14.1.5
   @nrwl/linter : 14.1.5
   @nrwl/nest : Not Found
   @nrwl/next : 14.1.5
   @nrwl/node : 14.1.5
   @nrwl/nx-cloud : 14.0.3
   @nrwl/nx-plugin : 14.1.5
   @nrwl/react : 14.1.5
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.5
   @nrwl/web : 14.1.5
   @nrwl/workspace : 14.1.5
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         @nx-extend/gcp-cloud-run: 3.4.0
         @nx-extend/gcp-functions: 6.2.0
```

**Comment by Brian-McBride** [comment]
I don't have time to open a PR, on a tight deadline. But I did trace down the problem. 

## Affected code: `packages/react/src/generators/stories.ts`

### Existing code link
https://github.com/nrwl/nx/blob/38809f177d5b62ff152137c4baaf7978beb1aa68/packages/react/src/generators/stories/stories.ts#L79-L92

### Suggestion for updated code
```typescript
  const existingStories = new Set();
  visitNotIgnoredFiles(tree, projectPath, (path) => {
    if (
      (path.endsWith('.tsx') && !path.endsWith('.spec.tsx')) ||
      (path.endsWith('.js') && !path.endsWith('.spec.js')) ||
      (path.endsWith('.jsx') && !path.endsWith('.spec.jsx'))
    ) {
      const ext = path.slice(path.lastIndexOf('.'));
      const storyPath = `${path.split(ext)[0]}.stories${ext}`;
      const isStory = path.slice(-ext.length - 7, -ext.length) === 'stories'
      if (isStory) {
         existingStories.add(path);
      }
      // Updating this line with set check
      if (!existingStories.has(path) && !tree.exists(storyPath)) {
        componentPaths.push(path);
      }
    }
  });
  existingStories.clear()
```

**Comment by Brian-McBride** [comment]
@Coly010  It looks like you fixed this before. I didn't have this issue an update or two ago (can't remember when).

**Comment by Balance8** [comment]
Bump, I can confirm this is occurring on my repo as well.  It is generating stories for story files as well as double-generating cypress specs.

**Comment by mandarini** [comment]
Oops that sounds frustrating. Looking into it now, thanks @Brian-McBride @Balance8 !
