### ISSUE TITLE
undefined type is ignored in BE apps

### ISSUE THREAD

**Issue by SunStupic** [nrwl/nx#10280]
## Current Behavior

If I write any variable with undefined type in any nx BE app, the undefined type will be ignored:

I found it because `Array.find` returns no undefined, which caused a serious bug in our code because the engineer had a faith in the variable is not undefined.

```ts
// should be number || undefined, but got number
const a = [1].find(x => x !== 1);
// should be undefined, but got any
const b = undefined;
// should be string | undefined, but got string
const c = '1' as string | undefined;
```
<img width="678" alt="image" src="https://user-images.githubusercontent.com/90165041/168273456-90bb243d-cf4e-44c7-85d7-417e5e473a8d.png">
<img width="699" alt="image" src="https://user-images.githubusercontent.com/90165041/168273478-295f3fce-7677-487f-8c56-c8ff7cb4c499.png">
<img width="534" alt="image" src="https://user-images.githubusercontent.com/90165041/168273496-b52d4ee2-98b5-41a8-be60-52ccb211f7cf.png">

## Expected Behavior

It should be like this in FE apps, same code but with right types:

<img width="593" alt="image" src="https://user-images.githubusercontent.com/90165041/168274103-12e98273-fede-49d2-8f6b-90c0041eb506.png">
<img width="521" alt="image" src="https://user-images.githubusercontent.com/90165041/168274110-84da5b04-9bd8-4406-a301-a334418f0c14.png">
<img width="430" alt="image" src="https://user-images.githubusercontent.com/90165041/168274129-865117e6-1bb2-46d7-a691-1f23d663e33e.png">

## Steps to Reproduce

1. Clone the [example repo](https://github.com/SunStupic/undefined-ignore-in-nx-be-apps): `git clone https://github.com/SunStupic/undefined-ignore-in-nx-be-apps.git`
2. Run `npm install`
3. Open BE example with vscode `code apps/test/src/main.ts`,
4. Hover on the variables, you will see the bug

> As contrast, you can open the FE example `code apps/test-fe/src/main.tsx`

### Environment
```

 >  NX   Report complete - copy this into the issue template

   Node : 14.19.0
   OS   : darwin arm64
   npm  : 6.14.16

   nx : 14.1.5
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.5
   @nrwl/eslint-plugin-nx : 14.1.5
   @nrwl/express : 14.1.5
   @nrwl/jest : 14.1.5
   @nrwl/js : 14.1.5
   @nrwl/linter : 14.1.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.1.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.5
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by AgentEnder** [comment]
Hey @SunStupic! This behavior points to a difference in the tsconfig for your apps. In particular, the front end tsconfig contains `strict: true`, which enables strict null checks. See here: https://github.com/SunStupic/undefined-ignore-in-nx-be-apps/blob/main/apps/test-fe/tsconfig.json#L9

To enable the same behavior across your workspace, you can set the strict flag in tsconfig.base.json, or in individual apps. We don't do this automatically since it adds a bit of friction to the adoption process when unexpected.

**Comment by SunStupic** [comment]
@AgentEnder Thanks!
