### ISSUE TITLE
Warning: ReactDOM.hydrate is no longer supported in React 18

### ISSUE THREAD

**Issue by hubertkuoch** [nrwl/nx#10294]
## Current Behavior

When running a Next.js app with `nx start` , I get the following warning:

<img width="1338" alt="Screenshot 2022-05-14 at 08 54 55" src="https://user-images.githubusercontent.com/50402245/168414624-08b17785-a2b7-4f60-9332-fd01d4188423.png">

This only happens with next v12.1.6 and not v12.1.5.
Prior to this, I also checked that using v12.1.6 with `create-next-app` does not log this warning, so it should not either with nx.

## Expected Behavior

It should compile without any warning

## Steps to Reproduce

```
pnpx create-nx-workspace@latest --preset=next
// then create a new Next.js app
pnpm start
```

### Environment

<img width="564" alt="Screenshot 2022-05-14 at 08 57 05" src="https://user-images.githubusercontent.com/50402245/168414703-bf6d703b-dd81-47e7-b45e-8c2239f91c5f.png">
<img width="370" alt="Screenshot 2022-05-14 at 08 58 17" src="https://user-images.githubusercontent.com/50402245/168414745-38a60e9c-afd9-4139-b63c-6510454bc187.png">

**Comment by LeonardoGobbiLopez** [comment]
Hey @hubertkuoch I'm experiencing this issue after migrating nx versions using nextjs, did you manage to solve this?
