### ISSUE TITLE
Incorrect `workspaceRoot` in e2e plugin tests

### ISSUE THREAD

**Issue by blaugold** [nrwl/nx#10298]
## Current Behavior
A plugin under test sees the repo in which it is developed as the `workspaceRoot`, instead of the temporary workspace.

## Expected Behavior

The plugin under test should see the temporary workspace as the `workspaceRoot`.

## Steps to Reproduce
Here is a [repo](https://github.com/blaugold/nx-plugin-test-issue/commit/544d6fc52389872369de5196a28ddfba3f32bad5) to reproduce the issue.

### Environment
```
 >  NX   Report complete - copy this into the issue template

   Node : 16.13.1
   OS   : darwin arm64
   npm  : 8.1.2
   
   nx : 14.1.4
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.4
   @nrwl/eslint-plugin-nx : 14.1.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.4
   @nrwl/js : 14.1.4
   @nrwl/linter : 14.1.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 14.1.4
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.4
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by simondotm** [comment]
Possibly related to https://github.com/nrwl/nx/issues/5065

**Comment by blaugold** [comment]
@simondotm Thanks for linking the issue. This is basically the same issue. The locally built and linked version of the plugin resolves `nx` in the `node_modules` in  the workspace in which it is developed, not the temporary workspace. `nx` resolves the `workspaceRoot` (which is the same as the `appRoot`) based on where it lives, and then everything that uses `workspaceRoot` has the wrong results in the plugin.

**Comment by simondotm** [comment]
Yes, you will see on the other thread I added a workaround. Hoping it'll get fixed one day

**Comment by khalilou88** [comment]
I believe it's correct now at least in version 14.6.3

**Comment by simondotm** [comment]
No longer seeing this issue with this in 15.2.1
