### ISSUE TITLE
Custom Gradle Tasks on android build

### ISSUE THREAD

**Issue by true-hamid** [nrwl/nx#10299]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
For android build the nx command to build the app has two param options:

1. apk, either app bundle or an apk based on what is passed 
2. debug, either release or debug based on what is passed 

but there is a case where there are several build flavors which requires custom gradle task to run, example:
Using https://github.com/luggit/react-native-config#android-1 to create different build flavors requires you to use custom build variants, such as assembleDevRelease or assembleProdRelease.

Hence i believe we should have a new option to pass custom gradle task which overrides the default tasks.
## Motivation
For building multi flavor react native apps using nx
## Suggested Implementation
https://github.com/nrwl/nx/pull/10276

**Comment by AgentEnder** [comment]
@true-hamid I see you've marked the checkbox that you'd be willing to implement, this makes sense to me if you want to go for it. If you decide to, let me know and I can add you as an assignee. If not, I'll send this on to @xiongemi to evaluate.

**Comment by true-hamid** [comment]
I've raised a pull request https://github.com/nrwl/nx/pull/10276 for the suggested changes @xiongemi. I'm waiting for you feedback
