### ISSUE TITLE
Jest 24 and jest-preset-angular 7 changes

### ISSUE THREAD

**Issue by vitalyiegorov** [nrwl/nx#1029]
After updating to latest Jest(24.0.0) and jest-angular-preset(7.0.0-alpha.2) which has some breaking changes:
https://github.com/thymikee/jest-preset-angular/blob/release/7/CHANGELOG.md

This is only showing warnings for now but  the main problem is that it does not find `tsconfig.spec.json` anymore.

Debugging `jest-builder` showed that change in https://github.com/nrwl/nx/blob/7.1.x/packages/builders/src/jest/jest.builder.ts#L47:
```
tsConfig: path.join('<rootDir>', path.relative(builderConfig.root, options.tsConfig))
```
fixes tests.

Also its weird that I cannot override `globals` Jest settings in my `jest.config.js` which I think would be expected.

# Prerequisites
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior
Running jest unit tests  normally as was before an update to latest Jest and jest-preset-angular

## Current Behavior
```
File not found: tsconfig.spec.json (resolved as: .../tsconfig.spec.json)
```

It resolves always to monorepo root folder, not to lib folder.

**Comment by FrozenPandaz** [comment]
I'm excited for the changes in Jest 24 :) I think we'll wait for `ts-jest` and `angular-preset-angular` to stabilize before we decide what to do. More than likely, it will have limited impact on the current usage of jest since most things are handled within the builder.

**Comment by YonatanKra** [comment]
So what can be done in the meantime? My tests don't run now. I have the same issue as #1054.

**Comment by nongrata081** [comment]
@YonatanKra If you downgrade jest to v23.6.0 it should work

**Comment by YonatanKra** [comment]
For some reason it doesn't happen locally - only on circle-ci. I've set the version to just `23.6.0` in package.json (without ~ nor ^) but to no avail.

**Comment by TekSiDoT** [comment]
This issue is now relevant to https://www.npmjs.com/advisories/786 , not upgrading to Jest >= 24 will report security issues with a dependency ([braces](https://github.com/micromatch/braces)) during installations and npm audits.

**Comment by FrozenPandaz** [comment]
https://github.com/thymikee/jest-preset-angular/pull/224 was merged and I tested it with Nx with the changes that @vitalyiegorov mentioned and it's looking good. I'll write the migrations tonight :)

**Comment by ViceIce** [comment]
[jest-preset-angular](https://www.npmjs.com/package/jest-preset-angular) v7 was released. So no more a blocker.

**Comment by tencho12** [comment]
> @YonatanKra If you downgrade jest to v23.6.0 it should work

downgrading is not working. is there any other alternative?

**Comment by dgroh** [comment]
I still get with version 7.1.1:

> File not found: <rootDir>/src/tsconfig.spec.json

**Comment by dgroh** [comment]
For those who are still facing this issue, this solution has helped me.*

https://github.com/thymikee/jest-preset-angular/issues/286
