### ISSUE TITLE
Document migrating from Angular CLI with multiple projects 

### ISSUE THREAD

**Issue by MaxKless** [nrwl/nx#10301]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/migration/migration-angular 

### Additional context or description

With #9885, it is now possible to migrate Angular CLI workspaces with multiple projects. The documentation linked above doesn't reflect that change. 

I'd be happy to contribute this when I get around to it - preferably not on my phone :)

**Comment by leosvelperez** [comment]
Thanks for reporting this! This is already being worked on, will update this issue once it gets merged.
