### ISSUE TITLE
`nx serve --prod` not working with cache hit

### ISSUE THREAD

**Issue by hubertkuoch** [nrwl/nx#10312]
## Current Behavior

When the build is retrieved from cache, `nx serve --prod` does not work

## Expected Behavior

`nx serve --prod` should always work, even when the cache is hit for retrieving the build

## Steps to Reproduce

```
npx create-nx-workspace@latest repo --preset=next
cd repo
nx generate @nrwl/next:application webapp

// Commands sequence

nx serve
nx serve --prod
// Error (expected): "Could not start production server. Try building your app with `nx build webapp`."
nx build
nx serve --prod

// Now, let's re-do the exact same flow

nx serve
nx build
// Build is instant as expected because it is retrieved from cache
nx serve --prod
// Error (unexpected): "Could not start production server. Try building your app with `nx build webapp`."

```

### Environment

Node : 16.15.0
OS   : darwin arm64
pnpm : 7.1.0
   
nx : 14.1.5
@nrwl/angular : Not Found
@nrwl/cypress : 14.1.5
@nrwl/detox : Not Found
@nrwl/devkit : 14.1.5
@nrwl/eslint-plugin-nx : 14.1.5
@nrwl/express : Not Found
@nrwl/jest : 14.1.5
@nrwl/js : 14.1.5
@nrwl/linter : 14.1.5
@nrwl/nest : Not Found
@nrwl/next : 14.1.5
@nrwl/node : Not Found
@nrwl/nx-cloud : Not Found
@nrwl/nx-plugin : Not Found
@nrwl/react : 14.1.5
@nrwl/react-native : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : 14.1.5
@nrwl/web : 14.1.5
@nrwl/workspace : 14.1.5
typescript : 4.6.4
rxjs : 6.6.7

**Comment by bitfrost** [comment]
related to this discussion I suspect https://github.com/nrwl/nx/discussions/10162

**Comment by hubertkuoch** [comment]
Thanks for the idea. I just tried downgrading to pnpm v^6 but it does not work either.

When looking at the `dist` folder, it feels like when running in sequence:
step 1 - `nx build`
step 2 - `nx serve`
step 3 - `nx build`
step 4 - `nx serve --prod` or `nx serve -- --prod` with pnpm v^6
The CLI does not actually update the dist artifact after step 3 with the one cached at after step 1.

**Comment by bitfrost** [comment]
yeah, sorry.  saw the pnpm 7 ref above and just assumed, but the pnpm 7 issue I linked too has to do with the default script runner getting extra --'s entirely.  I jumped the gun.

**Comment by hubertkuoch** [comment]
The only workaround I found is to set a different outputPath for the build in development mode e.g. tmp/apps/webapp so that the build commands in dev and prod mode do not override each other.

**Comment by Phault** [comment]
Pretty big issue I'd say, as this can lead to shipping broken production builds. In our case the CI built production builds, then ran e2e tests which mistakenly was testing with serve:development, if tests succeeded it would deploy. That's obviously not great, but the deploy step was dependent on build:production, so it should've been all good. Nx said there was a cache hit but the development build would end up deployed.

Nothing is _actually_ in production yet, so no real harm done.

**Comment by jaysoo** [comment]
This will be fixed in the next release. For the time being, set `outputPath` to something else as the workaround.

```json5
{
  // ...
  "targets": {
    "build": {
      "executor": "@nrwl/next:build",
      "outputs": [
        "{options.outputPath}"
      ],
      "defaultConfiguration": "production",
      "options": {
        "root": "apps/demo",
        "outputPath": "dist/apps/demo"
      },
      "configurations": {
        "development": {
          // NOTE: Point to a different path so there aren't any collisions.
          "outputPath": "tmp/apps/demo"
        },
        "production": {}
      }
    },
    // ...
}
```
