### ISSUE TITLE
React Native application generator ignores the value of "appsDir" in nx.json

### ISSUE THREAD

**Issue by ajwootto** [nrwl/nx#10327]
## Current Behavior

Nx react native application generator ignores the value of "appsDir" in the nx.json configuration. It incorrectly generates the app in "apps" no matter what the value of `appsDir` is. The corresponding `e2e` app is generated in the correct directory.
## Expected Behavior

React native applications should be generated inside the "appsDir" folder, not a hard-coded "apps" folder.

## Steps to Reproduce

Set `appsDir` to something other than apps
`nx g @nrwl/react-native:app my-app`

### Environment

```
 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : darwin x64
   yarn : 3.2.0

   nx : 14.0.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.0.5
   @nrwl/detox : 14.0.5
   @nrwl/devkit : 14.0.5
   @nrwl/eslint-plugin-nx : 14.0.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.5
   @nrwl/js : 14.0.5
   @nrwl/linter : 14.0.5
   @nrwl/nest : Not Found
   @nrwl/next : 14.0.5
   @nrwl/node : 14.0.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.0.5
   @nrwl/react-native : 14.0.5
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.0.5
   @nrwl/web : 14.0.5
   @nrwl/workspace : 14.0.5
   typescript : 4.6.3
   rxjs : 6.6.7
```

**Comment by xiongemi** [comment]
submit a pr https://github.com/nrwl/nx/pull/10606 to fix this
