### ISSUE TITLE
React native application generator uses wrong key name for resolver "blockList" 

### ISSUE THREAD

**Issue by ajwootto** [nrwl/nx#10328]
## Current Behavior

When generating a new react native application, the app will not work if there is anything in the repo's dist/ directory due to a "Duplicate package name" error, as mentioned here:
https://github.com/nrwl/nx/issues/8669

The metro.config.js includes a setting called `resolver.blacklistRE` which is supposed to fix this problem. That setting was renamed in some version of metro to now be `blockList`

## Expected Behavior

A newly generated react native app should start up correctly if there are built packages in the dist/ directory

## Steps to Reproduce

1. have a repo with buildable packages
2. build a package so it exists in dist/
3. generate a new react native application
4. run the application with `nx serve`

There will be an error about "duplicate packages" because the metro config does not properly ignore the dist/ directory

### Environment

```
 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : darwin x64
   yarn : 3.2.0

   nx : 14.0.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.0.5
   @nrwl/detox : 14.0.5
   @nrwl/devkit : 14.0.5
   @nrwl/eslint-plugin-nx : 14.0.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.5
   @nrwl/js : 14.0.5
   @nrwl/linter : 14.0.5
   @nrwl/nest : Not Found
   @nrwl/next : 14.0.5
   @nrwl/node : 14.0.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.0.5
   @nrwl/react-native : 14.0.5
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.0.5
   @nrwl/web : 14.0.5
   @nrwl/workspace : 14.0.5
   typescript : 4.6.3
   rxjs : 6.6.7
```

**Comment by ajwootto** [comment]
As a followup to this, I've also found that the ignore pattern being used for `dist/` doesn't correctly ignore the directory if the react native application is inside of a subdirectory. eg. my app is in `apps/some-directory/my-app` and because the dist/ directory is up a few folders it seemingly isn't being ignored. I fixed it by changing the pattern to the following:
```
 resolver: {
               ...,
                blockList: exclusionList([/\/dist\/.*/]),
            },
```

Basically removing the leading `\.` character from the pattern. However, I'm not sure if that will have unintended side effects (like is it now ignoring all dist/ directories and not just the root one?)

**Comment by xiongemi** [comment]
submit a pr https://github.com/nrwl/nx/pull/10607 to fix this

**Comment by ajwootto** [comment]
@xiongemi thanks for the fix. Did you see my followup note above about the pattern not correctly ignoring the dist/ folder for nested application folders?

**Comment by ajwootto** [comment]
@jaysoo since this is now closed should I open a new issue for the second problem I mentioned above?

**Comment by xiongemi** [comment]
> @jaysoo since this is now closed should I open a new issue for the second problem I mentioned above?

what if there is a library in node_modules with the dist folder that we could not block?

**Comment by ajwootto** [comment]
yeah that was part of my concern with the pattern I used above, I don't think it's the "correct" fix. But I couldn't come up with a working pattern to specifically exclude just the root-level dist directory but not the dist/ folders in node_modules

**Comment by ajwootto** [comment]
opened a new issue here:
https://github.com/nrwl/nx/issues/10644
