### ISSUE TITLE
nx g @nrwl/next:component "--export" flag doesn't work

### ISSUE THREAD

**Issue by smitroshin** [nrwl/nx#10322]
## Current Behavior

`nx g @nrwl/next:component header --project=ui-shared --export`
Creating "next.js" component with "--export" flag doesn't updates index.ts file.

![Screenshot 2022-05-13 172459](https://user-images.githubusercontent.com/20210690/168611923-0eaadc1e-8c58-4d6e-b98a-fc67483ce9f4.png)

## Expected Behavior

The component should be exported from the index.ts file.

## Steps to Reproduce

Just create "next.js" component via CLI with "--export" flag.

### Environment

```
   Node : 16.15.0
   OS   : linux x64
   npm  : 8.9.0
   
   nx : 14.1.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.5
   @nrwl/eslint-plugin-nx : 14.1.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.5
   @nrwl/js : 14.1.5
   @nrwl/linter : 14.1.5
   @nrwl/nest : Not Found
   @nrwl/next : 14.1.5
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.1.5
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.5
   @nrwl/web : 14.1.5
   @nrwl/workspace : 14.1.5
   typescript : 4.6.4
   rxjs : 6.6.7
```

**Comment by ndcunningham** [comment]
Hey! Thanks for reporting this if this is still an issue please feel free to open a new ticket.
