### ISSUE TITLE
Jest in Angular workspace can not find paths to libraries

### ISSUE THREAD

**Issue by e-oz** [nrwl/nx#10337]
After 14.1.6, Jest can not translate "@orgPrefix/libName" into a path.
Reproducible with 14.1.6 and 14.1.7-beta.2.

## Current Behavior

Application test error:
```
 FAIL   appName  apps/appName/src/app/[..]/task-images/task-images.component.spec.ts
       
  ● Test suite failed to run appName/src/app/[..]/upload-page.component.spec.ts
       
           Cannot find module '@scs/api' from 'src/app/[..]/task-images/task-images.component.ts'
       
           Require stack:
             src/app/[..]/task-images/task-images.component.ts
             src/app/[..]/task-images/task-images.component.spec.ts
       
             1 | import { Component, ChangeDetectionStrategy, NgModule, Input, Output, EventEmitter } from '@angular/core';
           > 2 | import { PermissionService } from '@scs/api';
               | ^

```
Library test error:
```
 FAIL   inputs  libs/inputs/src/lib/standard-input/standard-input.component.spec.ts
  ● Test suite failed to run
       
           Cannot find module '@scs/api' from 'src/lib/enums.ts'
       
           Require stack:
             src/lib/enums.ts
             src/lib/inputs.service.ts
             src/lib/base-input.component.ts
             src/lib/standard-input/standard-input.component.ts
             src/lib/standard-input/standard-input.component.spec.ts
       
           > 1 | export { ApiDataTypes as DataTypes } from '@scs/api';
               | ^
             2 |
```
## Expected Behavior

Jest was working great with 14.1.6-beta.1

### Environment

```
   Node : 18.1.0
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 14.1.7-beta.2
   @nrwl/angular : 14.1.7-beta.2
   @nrwl/cypress : 14.1.7-beta.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.7-beta.2
   @nrwl/eslint-plugin-nx : 14.1.7-beta.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.7-beta.2
   @nrwl/js : Not Found
   @nrwl/linter : 14.1.7-beta.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.0.4-beta.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.7-beta.2
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.7-beta.2
   typescript : 4.6.4
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:
         @ngrx/component-store: 13.2.0
         @ngrx/data: 13.2.0
         @ngrx/effects: 13.2.0
         @ngrx/entity: 13.2.0
         @ngrx/store: 13.2.0
         @ngrx/store-devtools: 13.2.0
         ng-mocks: 13.5.2

Also:
    "jest": "^28.1.0",
    "jest-environment-jsdom": "^28.1.0",
    "jest-preset-angular": "~12.1.0-next.0",
    "ts-jest": "^28.0.2",
    "ts-node": "^10.7.0",

```

**Comment by samuelfernandez** [comment]
Same issue here! In my case it also throws an error in jest angular preset. I saw it first in v14.1.5

`Cannot find module '@angular/core/testing' from '../../node_modules/jest-preset-angular/build/config/setup-jest.js'`

**Comment by e-oz** [comment]
Still reproducible with 14.1.7, unfortunatelly.

**Comment by seanlawrenz** [comment]
Same issue:
```
Cannot find module '@angular/core/testing' from '../../node_modules/jest-preset-angular/build/config/setup-jest.js'
```

nx 14.1.7

**Comment by Coly010** [comment]
Hey, thanks for reporting this issue!

I've taken a look at this and here are some of my findings:

- Creating a new v14.1.5 workspace - testing works fine
- Creating a new v14.1.4 workspace -> migrate to v14.1.5 using `nx migrate 14.1.5` and `nx migrate --run-migrations` -> testing works fine
- Creating a new v14.1.4 workspace -> use `npm install --save-dev @nrwl/jest@14.1.5` for each nrwl package -> This reproduces the error

We do not recommend upgrading Nrwl Packages manually. You should always use the `migrate` command followed by the `--run-migrations` flag.

More docs here: https://nx.dev/cli/migrate#migrate

 Can everyone facing this issue confirm if they encountered this after running `nx migrate 14.1.5` followed by `nx migrate --run-migrations`?
 
 
 @samuelfernandez I noticed your PR only updated the versions in `package.json`. There should have been a migration that was run.
 
---

 For everyone visiting this, the problem comes from a change to how the `jest.config.ts` (in every app and library) is interpreted.  It currently uses `module.exports = { ... }`, however, it now needs to match the following syntax: `export default {...}`
 
A typical `jest.config.ts` now looks like this: 

```ts
export default {
  displayName: 'app0',
  preset: '../../jest.preset.js',
  setupFilesAfterEnv: ['<rootDir>/src/test-setup.ts'],
  globals: {
    'ts-jest': {
      tsconfig: '<rootDir>/tsconfig.spec.json',
      stringifyContentPathRegex: '\\.(html|svg)$',
    },
  },
  coverageDirectory: '../../coverage/apps/app0',
  transform: {
    '^.+\\.(ts|mjs|js|html)$': 'jest-preset-angular',
  },
  transformIgnorePatterns: ['node_modules/(?!.*\\.mjs$)'],
  snapshotSerializers: [
    'jest-preset-angular/build/serializers/no-ng-attributes',
    'jest-preset-angular/build/serializers/ng-snapshot',
    'jest-preset-angular/build/serializers/html-comment',
  ],
};

```

**Comment by Coly010** [comment]
@e-oz 
It's two-step process :) 

1. Run `nx migrate latest` or if you're targeting a certain version `nx migrate 14.1.5`
2. Run `nx migrate --run-migrations`


The first step installs the dependencies for that version, but it also creates a `migrations.json` file which contains definitions for automated code fixes for any potential breaking changes that occur between versions. Basically, we use this to make sure you're less likely to hit breaking changes!

`nx migrate --run-migrations` then analyses the `migrations.json` file and runs each of the automated code migrations :)

It's a similar concept to `ng update` except, we'd argue it's slightly better as you have more control over when to run migrations themselves. 

There's a good video on this here: https://egghead.io/lessons/javascript-update-your-nx-workspace-with-nx-migrations

A more in-depth written guide here: https://nx.dev/using-nx/updating-nx

Hope this helps!

**Comment by e-oz** [comment]
Thanks a lot, will use it next time. Please consider adding an argument for "nx migrate" to set the "from"/"source" version, like `nx migrate --from=14.1.5 --to=latest` or `nx migrate --source=14.1.5 --target=latest`

For others:
Root jest.config.ts should be:
```
import { getJestProjects } from '@nrwl/jest';

export default {
  projects: getJestProjects(),
};
```

Root jest.preset.ts:
```
const nxPreset = require('@nrwl/jest/preset').default;

module.exports = { ...nxPreset };
```

In every app/lib jest.config.ts replace `module.exports = {` by `export default {`, as Colum mentioned.

Thanks a lot for help, our tests are running again!!!

**Comment by Coly010** [comment]
Nx migrate does support a `from` option :)

https://nx.dev/cli/migrate#from

**Comment by Coly010** [comment]
`nx migrate @nrwl/workspace@9.0.0 --from="@nrwl/workspace@8.0.0,@nrwl/node@8.0.0"`

**Comment by seanlawrenz** [comment]
Immediate fail 

```
 Unexpected token 'export'
```

**Comment by seanlawrenz** [comment]
Okay. The migration for `update-jest-config-extensions` failed with a cryptic error on `tsconfig.json` stating there was a `ValueExpected at position 248` on one of my libraries. 

I removed that library, got what it was trying to do (`"exclude": ["jest.config.ts"]`), added back in the library and now I'm in a semi good state.
