### ISSUE TITLE
custom webpack config does not feed original config as seed

### ISSUE THREAD

**Issue by engina** [nrwl/nx#10342]
## Current Behavior
When extending webpack config for a react app within the workspace, the original config is not fed to the modifier function.

i.e. project.json has `"webpackConfig": "@nrwl/react/plugins/webpack"` by default.

When I replace it with `"webpackConfig": "apps/my-app/custom-webpack.config.js"` and have a 
```
const { merge } = require('webpack-merge');

module.exports = (config, context) => config; // no-op, just return the config as it is.
```

## Expected Behavior
If I don't modify the config I'd expect the build to be the same as before but it turns out it's missing svg loader.

This can be worked around by forcing the default modification function on the config, i.e.
```
const { merge } = require('webpack-merge');
const FaviconsWebpackPlugin = require('favicons-webpack-plugin');

const nrwlReactWebpack = require('@nrwl/react/plugins/webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = (config, context) => {
  const original = nrwlReactWebpack(config); // force default config modifier here.
  const result = merge(original, {
    // overwrite values here
    plugins: [
      new HtmlWebpackPlugin({
        src: './src/index.html',
        filename: 'index.html',
      }),
      new FaviconsWebpackPlugin({ logo: 'src/assets/enda.png', inject: true }),
    ],
  });
  console.log('original', original.plugins);
  console.log('result', result.plugins);
  return result;
};

```

## Steps to Reproduce
1. Create workspace
2. Add a react app
3. import a svg
4. build (expected to be succesful)
5. add a custom webpack config and do not modify the config
6. it should build as well, as it must be the same config as in step 4.
7. it fails to build complaining about missing svg loader.

**Comment by jpaas** [comment]
You can get it like this...
```
const getNxWebpackConfig = require("@nrwl/react/plugins/webpack")
const configFactory = (webpackConfig, _commandConfig) => {
  const originalConfig = getNxWebpackConfig(webpackConfig)
  ...
}
```
