### ISSUE TITLE
Unable to specify configuration for run-many and affected

### ISSUE THREAD

**Issue by elgurinn** [nrwl/nx#10348]
## Current Behavior
Using version **14.1.6**

When running affected and run-many commands the **configuration** passed in is not used.

e.g. `npm run-many --target build --projects enr -c=devops`

The **devops** configuration is not used.

## Expected Behavior

Before updating from 13.9.5 to 14.1.6 the commands picked up the configuration and the applications were built with that particular config.

## Steps to Reproduce
1. npx create-nx-workspace issue
2. run `nx run-many --target build --projects issue -c=production`

Result:
![image](https://user-images.githubusercontent.com/20297705/168842910-19dbc04e-d122-4782-a883-3d39963677d6.png)

---

### UPDATE adding --configuration works at least for 14.1.9

if I add  `--configuration` it is not used at all

![image](https://user-images.githubusercontent.com/20297705/168869755-d5386ade-926b-4731-ae56-6d8e39ccc489.png)

**Comment by danielkresta** [comment]
`nx affected:build -c=production`
does not seem to work, but
`nx affected:build --configuration=production`
does.
@nrwl/cli: 14.1.9

**Comment by elgurinn** [comment]
@danielkresta thanks can confirm it works.
