### ISSUE TITLE
generateFIles looks for .template instead of __tmpl__ 

### ISSUE THREAD

**Issue by AdamGonda** [nrwl/nx#10344]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?
In `generate-files.js` I found this doc for `generateFiles` which seems outdated

It says that it will look for `__tmpl__`
![1](https://user-images.githubusercontent.com/40203031/168814618-a7fcf2b4-cd73-4870-b63d-0e79005e5724.png)

but it looks for `.template` instead
![2](https://user-images.githubusercontent.com/40203031/168814623-c402e3f5-5fa4-46f6-b92b-16cf06bd92e6.png)

**Comment by AgentEnder** [comment]
The reference to `__tmpl__` is based on the call in the example typescript. See the example call here:
```typescript
generateFiles(tree, path.join(__dirname, 'files'), './tools/scripts', { tmpl: '', name: 'myscript' })
```

The last arg, is the substitutions. `tmpl` is stripped out since it's substituted with an empty string.
