### ISSUE TITLE
ability to assign filename in withModuleFederation interface

### ISSUE THREAD

**Issue by KiranMantha** [nrwl/nx#10364]
## Description
I just created a monorepo with 2 micro frontends using nx and it's awesome. one thing i noticed when debugging is, when i check the network tab i can see multiple remoteEntry.mjs files. at first i thought it is due to some mis-config from my side. but when i went through them each indicates one mfe. right now there is no way to assign a filename for a remote in existing MFE interface.

<img width="519" alt="image" src="https://user-images.githubusercontent.com/13364465/169024103-51da22a6-574a-4b03-a296-1b6a02c4f695.png">

## Motivation
I think it would be better if nx allows devs to assign custom filename instead of generic name like remoteEntry.mjs. this will helps immensly which mfe got loaded.

## Suggested Implementation
need something like
```javascript
// in module-federation.config.js

module.exports = {
  name: 'orders',
  filename: 'ordersRemoteEntry.js', // right now this defaults to remoteEntry.mjs
  exposes: {
    './Module': 'apps/orders/src/app/remote-entry/entry.module.ts'
  }
};
```

## Alternate Implementations
i created a [sample angular workspace](https://github.com/KiranMantha/angular-mfe) without using nx. here i used module federation to load multiple MFEs. in this example, i was able to assign custom filename in module federation section of webpack.config.js.

Hope this makes sense..

**Comment by Coly010** [comment]
Hi @KiranMantha!

While this could be possible, I think overall the experience would be poorer, as we can make less assumptions on our side. This means the code that we have to automatically find remotes for the host would fail as we could never know the actual filename being used by the remote.

That said, in the network tab, if you click the remoteEntry.mjs file, you can see the origin of where the file came from. Therefore, you can match that to the config in your workspace. 

As this is something we're not looking to support at the moment, I'm going to close this issue.

**Comment by KiranMantha** [comment]
> That said, in the network tab, if you click the remoteEntry.mjs file, you can see the origin of where the file came from. Therefore, you can match that to the config in your workspace.

atleast this will help alot for debugging purposes. thanks @Coly010
