### ISSUE TITLE
Being able to configure to use swc compiler for Cypress tests within @nrwl/cypress

### ISSUE THREAD

**Issue by jase88** [nrwl/nx#10363]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

As swc is already available for plugins like @nrwl/js it would be great to be able to use it in other places as well.

For cypress tests it would be great to setup swc as compiler within nx.

Similiar direction like https://github.com/nrwl/nx/issues/8900

## Motivation
E2E tests are costly. To speed this up we have accepted a compile process that does not do a type check. The type check can then be parallelized within the CI.

We are currently solving this by pulling in esbuild with the following setup:

example of project-e2e/src/plugins/index.ts
```
import createBundler from '@bahmutov/cypress-esbuild-preprocessor';

export default (on: Cypress.PluginEvents) => {

  on('file:preprocessor', createBundler());
```
already improved our CI times drastically, but would be great if configuration for compilers would be baked into nx.

## Suggested Implementation

- make it configurable if webpack or swc should be used for @nrwl/cypress compilation
- default is of course webpack

**Comment by barbados-clemens** [comment]
interesting idea, fits into the idea of wanting to build cypress tests and executor later from #1206

**Comment by barbados-clemens** [comment]
We now have a [vite preprocessor](https://nx.dev/packages/cypress/generators/cypress-project#using-cypress-with-vite.js) which should help accomplish the goal of this issue. 

but we aren't looking to add a swc preprocessor at this time.
