### ISSUE TITLE
How to use react lib in angular app or angular lib in react app?

### ISSUE THREAD

**Issue by dengc367** [nrwl/nx#10368]
### Discussed in https://github.com/nrwl/nx/discussions/10367

<div type='discussions-op-text'>

<sup>Originally posted by **dengc367** May 18, 2022</sup>
Hello.

I have a monorepo have two apps (`angular-app`, `react-app`), and two libs (`angular-lib`, `react-lib`), that now `angular-app` is used `angular-lib`, and `react-app` use `react-lib`
but now I have need to use some `angular-lib` component in `react-app`, and `react-lib` component in `angular-app`, how to connect the two react component with angular component in `nx`. 

and where can get the example? which is the best way to use the `nx`.</div>

**Comment by AgentEnder** [comment]
I'm going to close this issue in favor of the discussion, answers should go there.
