### ISSUE TITLE
Formatting affected files throws if only files are deleted

### ISSUE THREAD

**Issue by FrozenPandaz** [nrwl/nx#1036]
## Current Behavior

`nx format:write --uncommited` throws an error when _only_ files are deleted in the diff

```
Jasons-MacBook-Pro:nesttest jason$ yarn format:write --uncommitted
yarn run v1.13.0
$ ./node_modules/.bin/nx format:write --uncommitted
[error] No matching files. Patterns tried: apps/app2/src/app/app.module.ts !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
/Users/jason/projects/temp/temp/nesttest/node_modules/@nrwl/schematics/node_modules/yargs/yargs.js:1133
      else throw err
```

## Expected Behavior

`nx format:write --uncommited` should not throw an error because it is fine in our case to not format anything.

## Related Code

https://github.com/nrwl/nx/blob/master/packages/schematics/src/command-line/format.ts#L44

**Comment by ZachJW34** [comment]
I'll make a PR for this issue this weekend.
