### ISSUE TITLE
lint error when @nrwl/* packages are in devDependencies

### ISSUE THREAD

**Issue by muradm** [nrwl/nx#1038]
## Expected Behavior

`npm run lint` should work when `@nrwl/*` packages defined in `package.json` `devDependencies` section.

## Current Behavior

```
> nx lint && ng lint

The package.json is inconsistent:
The versions of the @nrwl/nx and @nrwl/schematics packages must be the same.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create new workspace with angular application (or add angular application later).
2. move all (`dependencies` section should be empty) packages from `dependencies` to `devDependencies` section.
3. issue `npm run lint`

### Context

All versions are latest as of today.

Our frontend application projects outputs the final application in `dist` folder, which is then populated to `docker` container. Only binary dependencies remain in `dependencies` section because they have to be recompiled for every image. All other dependencies go to `devDependencies` section, to avoid garbage `node_modules` in docker container and reduce its size. So that for build container we do `npm install` and for production image we do `npm install --only=production` to install binary dependencies, and then copy compiled `dist` from build image to production image.

Similar issues was reported, but they were related to version parsing or else.

### Workaround

Moving `@nrwl/nx` package from `devDependencies` to `dependencies` section solves the issue.

**Comment by muradm** [comment]
Basically, `NxModule` is not used at this point. But every time we run schematics commands, it keeps adding it :) so we gave up, and left it in `packages.json`.

Another thing, is that all our dependencies of angular application including angular it self are in `devDependencies`. Let's look it from this way, if you have a project, which has no dependents, like final front-end application, and resulting artifact is what is generated in `dist` final javascript / html / etc. outputs, all your dependencies are effectively `devDependencies` because you don't need them to run the application. As the result, for instance `@angular/core` is also dev dependency. So why `@nrwl/nx` can not be in `devDependencies` if `@angular/core` is?

**Comment by vsavkin** [comment]
@FrozenPandaz we should fix it as part of our repackaging

**Comment by jaysoo** [comment]
This issue has been fixed as packages can now be in `devDependencies`.
