### ISSUE TITLE
Add run-macos, run-windows executors to @nrwl/react-native plugin for building and running desktop apps

### ISSUE THREAD

**Issue by maierson** [nrwl/nx#10391]
We are building a desktop app based on react-native as per the docs here:
https://microsoft.github.io/react-native-windows/docs/getting-started

We would like to reuse many of the existing repo libs inside this desktop app.

## Description

It would be great to have desktop targets (run and build) for the project:
```
npx nx run-macos [my-desktop-app]
// or
npx nx run-windows [my-desktop-app]
```

## Motivation

Share code between the web app and desktop app

## Suggested Implementation

It looks like we would need this configuration to work in project.json
```
    "run-macos": {
      "executor": "@nrwl/react-native:run-macos",
      "options": {}
    },
    "bundle-ios": {
      "executor": "@nrwl/react-native:bundle",
      "outputs": ["apps/[my-desktop-app]/build"],
      "options": {
        "entryFile": "src/main.tsx",
        "platform": "ios", // or "macos" not sure
        "bundleOutput": "dist/apps/[my-desktop-app]/macos/main.jsbundle"
      }
    },
```

**Comment by xiongemi** [comment]
currently, we don't support the desktop app. we will get to this feature when we got the bandwidth.
