### ISSUE TITLE
Make nx run more flexible when using script runner workflow

### ISSUE THREAD

**Issue by jordanpowell88** [nrwl/nx#10398]
## Current Behavior
After adding Nx to a Lerna repo using `add-nx-to-monorepo` I'm unable to run any scripts that have a colon in them. 

Example:

```json
{
  "name": "packages/my-lib",
  "scripts": {
    "cypress:open": "cypress open ",
    ...
  }
}
```

```bash
nx run packages/my-lib:cypress:open
```

## Expected Behavior
I would expect that I could run the `cypress:open` script using `nx run`

## Steps to Reproduce
- Run `add-nx-to-monorepo` to an existing Lerna workspace
- Add a script with a colon in a package's `package.json`
- Call that script with a colon using `nx run`

### Failure Logs
When you run the command you get the following error:

`NX Cannot find target 'cypress' for project `packages/my-lib`

### Environment
 NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : darwin x64
   npm  : 8.1.2

   nx : 14.1.7
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : Not Found
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : Not Found
   typescript : 4.4.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

**Comment by AgentEnder** [comment]
Hey @jordanpowell88! We added some accommodations  for this somewhat recently. If you target name itself includes a colon, you can wrap it in quotation marks or use the infix  target format. Either of the below should work:

```bash
nx run my-project:"my:target":configuration
nx my:target my-project -c configuration
```

Does this suit the use case you are looking at?

**Comment by jordanpowell88** [comment]
@AgentEnder The infix target format works but the quotation marks example does not.

**Comment by AgentEnder** [comment]
So the reason the quote mark example doesn't work, is that evidently the shell is consuming the quotes before they can get to Nx... I'm not super sure what we can do about this on our side to be honest. 

Its ugly, but in the meantime this is working as expected:
```
nx run my-project:\"my:target\":configuration
```

**Comment by jordanpowell88** [comment]
Ok, I mean I can just use the infix version as well. I hadn't tried that approach yet before creating this bug. There is probably some documentation gaps around how do these for people running Nx in my scenario (Lerna) if it won't work the other way. Mostly because the terminal outputs the `run` commands so I don't think people new to Nx coming from Lerna would know the different ways to execute the command

**Comment by AgentEnder** [comment]
I'm going to close this out now for the following reasons:
- The documented reasons for failure above (e.g. shell consuming quotes)
- The infix notation works
- Transitioning from lerna "just works" with the `useNx` flag introduced in lerna v5. Folks can continue running their commands with `lerna`.
