### ISSUE TITLE
optimisticUpdate causes errors.

### ISSUE THREAD

**Issue by phsims** [nrwl/nx#104]
O am trying to run an optimisticUpdate for a simple function that passes a user id and state to the server.

```
  @Effect() updateFont = this.d.optimisticUpdate<UpdateFont>('UPDATE_FONT', {
    run: (a: UpdateFont, state: UserState) => {
      return this.backend.sendFont( a.payload.id, a.payload.font)
    },
    
    undoAction: (a: UpdateFont, e: any) => {
      return ({
        type: 'UNDO_UPDATE_FONT',
        payload: a
      });
    }
  })
```

```
  sendFont(id: number, font: boolean): Observable<any> {
    return this.http.put(`${this.url}/${id}`, {id, font: font})
  }
```

The effect sends the payload and posts to the server without issue but I get the following errors after

Effect "UserEffects.updateFont" dispatched an invalid action
effects.es5.js:247 Source: UserEffects {actions: Actions, d: DataPersistence, backend: BackendService, updateTheme: Actions, updateFont: Actions}
effects.es5.js:247 Effect: Actions {_isScalar: false, source: Actions, operator: MergeMapOperator}
Dispatched: Response {_body: "{↵  "id": 0,↵  "font": false↵}", status: 200, ok: true, statusText: "OK", headers: Headers, …}
effects.es5.js:247 Notification: Notification {kind: "N", value: Response, error: undefined, hasValue: true}

**Comment by vsavkin** [comment]
You need to set the dispatch property to false.

```
  @Effect({dispatch: false})
  loadData = this.d.pessimisticUpdate('LOAD_DATA', {
    run: (a: LoadData, state: ModelState) => {
      return <any>of('some data');
      // return {
      //   type: 'DATA_LOADED',
      //   payload: {}
      // };
    },
```


I updated the api docs to cover this: https://github.com/nrwl/nx/commit/846d5e41865fc81d7173453ae21a516353c701d1
