### ISSUE TITLE
Host fails to render entirely if any of the remotes fails to load

### ISSUE THREAD

**Issue by anogr** [nrwl/nx#10404]
## Current Behavior
If I generate a host and a remote with Nx React plugin and start the host without starting the remote, the host fails to render entirely. It doesn't matter if the lazy-loaded remote is within an ErrorBoundary. The screen is just white anyway.

I have built a similar application without involving Nx but still using Webpack Module Federation, and the host renders fine even if a remote doesn't respond, except for the part where the remote were supposed to be of course. The major difference is that Nx configures Webpack experiments.outputModule = true and ModuleFederationPlugin library.type = 'module'.

## Expected Behavior
I expect the host and all working remotes to render normally even if one of the remotes fails to load. I expect to be able to use an ErrorBoundary to render an error component where the failing remote would be.

## Steps to Reproduce
Run
```
npx create-nx-workspace --preset=react
npx nx generate @nrwl/react:host host --remotes=remote
npx nx build host
```

And open up the built HTML (with all other files) in a local web server, such as Visual Studio Code Live Server extension. Depending on how you do that you might want to configure baseHref in project.json in the host app.

In this case, there is no ErrorBoundary in the host app yet, but even if you create one around the laxy-loaded remote, it will still not render. I'm don't know much about Webpack bundles, but if I look at the bundled JavaScript when the library.type = 'module', I can see standard imports, but if the library.type = 'var' I can see some error-handling around the bundled code that is loading the remote.

### Failure Logs
If you start up a web server for the remote on the right port, the browser will log a standard 404 (since we haven't built the remote), but nothing more.

### Environment
   Node : 16.14.2
   OS   : win32 x64
   npm  : 8.5.0

   nx : 14.1.7
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.7
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.7
   @nrwl/eslint-plugin-nx : 14.1.7
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.7
   @nrwl/js : 14.1.7
   @nrwl/linter : 14.1.7
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.1.7
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.7
   @nrwl/web : 14.1.7
   @nrwl/workspace : 14.1.7
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

**Comment by simonbergstrom** [comment]
Experiencing the same issue. Following this thread.

**Comment by simonbergstrom** [comment]
Currently a blocker for us to proceed with this to production

**Comment by michaellatman** [comment]
Experiencing the same issue. We would like to be able to catch this exception to display an error page if a specific module does not load.

**Comment by imaitland** [comment]
Bump - Also experiencing this issue.

**Comment by chrisdibble** [comment]
Experiencing this as well - seems like a goal of micro frontends would be to limit the blast radius in situations where one app is unavailable - this feels like a big issue.

**Comment by Cpt-Falcon** [comment]
BUMP

**Comment by roelmang** [comment]
Bump. Solving this issue would also help my project out a lot.

**Comment by xiongemi** [comment]
currently for react, the remotes for react are rendered static out of box. 
as mentioned in https://github.com/nrwl/nx/issues/19491#issuecomment-1773058683, the error message was related to webpack error. https://github.com/webpack/webpack/issues/11944

you can try dynamic module federation with react as mentioned in https://github.com/webpack/webpack/issues/11944.
or if you still want to do try catch, you have to do it in the remote app.
