### ISSUE TITLE
No way to bundle dependency with `@nrwl/web:rollup`

### ISSUE THREAD

**Issue by vkurchatkin** [nrwl/nx#10405]
I'm building a publishable library and want to bundle some dependencies, but not the others. It seems that this piece of code is to blame 

https://github.com/nrwl/nx/blob/70f1a6b781b61efc885602ee7a638290d0c6c1b4/packages/web/src/executors/rollup/rollup.impl.ts#L267-L271

`externalPackages` by default includes all npm dependencies and there is no way to exclude one. It's somewhat hard to see what is even the point of `external` since pretty much everything you could include is already there by default.

## Current Behavior
Dependency is not listed in `external`, but is still treated as external and not bundled.

## Expected Behavior

Dependency should not be bundled.

## Steps to Reproduce
Sample config:

```json
 {
      "executor": "@nrwl/web:rollup",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/libs/ui",
        "tsConfig": "libs/ui/tsconfig.lib.json",
        "project": "libs/ui/package.json",
        "entryFile": "libs/ui/src/index.ts",
        "external": ["react/jsx-runtime", "react"],
        "rollupConfig": "libs/ui/rollup-config",
        "compiler": "babel",
        "assets": [
          {
            "glob": "libs/ui/README.md",
            "input": ".",
            "output": "."
          }
        ]
      }
    }
```

`ui` lib uses `zod` npm package, which is not listed as external, but is still not bundled.

### Failure Logs
None

### Environment
 Node : 16.13.2
   OS   : darwin arm64
   npm  : 8.1.2

   nx : 14.1.6
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.6
   @nrwl/eslint-plugin-nx : 14.1.6
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.6
   @nrwl/js : 14.1.6
   @nrwl/linter : 14.1.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.1.6
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.6
   @nrwl/web : 14.1.6
   @nrwl/workspace : 14.1.6
   typescript : 4.6.4
   rxjs : 6.6.7

### Workaround

Obviously, can be work around by using custom rollup config:

```js
function getRollupOptions(options) {
  const extraGlobals = {
    react: 'React',
    'react-dom': 'ReactDOM',
    'styled-components': 'styled',
    '@emotion/react': 'emotionReact',
    '@emotion/styled': 'emotionStyled',
  };
  if (Array.isArray(options.output)) {
    options.output.forEach((o) => {
      o.globals = { ...o.globals, ...extraGlobals };
    });
  } else {
    options.output = {
      ...options.output,
      globals: {
        ...options.output.globals,
        ...extraGlobals,
      },
    };
  }

  const bundled = [
    'zod'
  ]

  return {
    ...options,
    external: name => {
      if (bundled.includes(name)) {
        return false;
      }

      return options.external(name)
    }
  }
}
```

**Comment by ryanbas21** [comment]
I also reported this in #10395, seems the same. This is a big blocker to using Rollup.

**Comment by NejcZdovc** [comment]
+1 on this one

**Comment by seerviashish** [comment]
Same issue I am also facing and not able to import with alias any hack?

**Comment by bernardocorbella** [comment]
bump. This is a huge blocker for using rollup.
