### ISSUE TITLE
Static assets (image files) from React library not showing in Next.js app 

### ISSUE THREAD

**Issue by jls527** [nrwl/nx#10407]
## Current Behavior

Image files are **not** showing in Next.js app when imported from shared React library.

<img width="300" alt="Screenshot 2022-05-20 at 15 28 32" src="https://user-images.githubusercontent.com/103194434/169538146-089d2d93-6e91-4e12-991f-46757b4871ef.png">

## Expected Behavior

I expect static assets like image files are "automatically" working when serving/building the Next.js app with React components imported from a shared library.

It works fine for Storybook ✅ 

It doesn't work when serving or building the Next.js app 🆘 

## Steps to Reproduce

1. Create Nx workspace with **Next.js** app
2. Generate **React library** (shared) and add an image file (PNG in this example)
3. Create a React component that renders an img tag with your image file:
```tsx
import myImage from './assets/my-image.png'

export const Footer = () => <img src={myImage} />
```

5. Import the React component on a page in your Next.js app:
<img width="615" alt="Screenshot 2022-05-20 at 15 35 57" src="https://user-images.githubusercontent.com/103194434/169539580-4d6a44aa-5f4c-45ff-b9c3-6d560b5c42f1.png">

6. Serve the Next.js app. The image src is broken:
<img width="300" alt="Screenshot 2022-05-20 at 15 28 32" src="https://user-images.githubusercontent.com/103194434/169538146-089d2d93-6e91-4e12-991f-46757b4871ef.png">

## Screenshot of library files:

<img width="274" alt="Screenshot 2022-05-20 at 15 30 27" src="https://user-images.githubusercontent.com/103194434/169538525-bd50e093-eeaf-49f2-9f3e-6c8d4b5017d3.png">

### Environment

```
   Node : 16.13.1
   OS   : darwin x64
   npm  : 8.3.0

   nx : 13.10.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.10.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.4
   @nrwl/eslint-plugin-nx : 13.10.4
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.4
   @nrwl/js : 13.10.4
   @nrwl/linter : 13.10.4
   @nrwl/nest : Not Found
   @nrwl/next : 13.10.4
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.10.4
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.4
   @nrwl/web : 13.10.4
   @nrwl/workspace : 13.10.4
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by vkurchatkin** [comment]
This seems to be expected in Next.js. In Next.js importing an image results in an object, not a string. The simples thing you can do support both Next.js and Storybook (and other "normal" Webpack-based configurations) is to do something like this:

```js
import myImage from './assets/my-image.png'

export const Footer = () => <img src={typeof myImage === 'string' ? myImage : myImage.src} />
```

**Comment by ndcunningham** [comment]
This is expected. To load an image the with your syntax you need to use the Image element from nextjs 
`import Image from 'next/image'`
