### ISSUE TITLE
Project Graph Start and End should work without specifying both

### ISSUE THREAD

**Issue by gregveres** [nrwl/nx#10403]
- [maybe ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
The graph gets pretty cluttered pretty quickly. I like the introduction of Start and End projects, but I didn't understand how you expected to use them at first. I had thought that selecting Start on a project would give me the tree of all of the projects that the selected project used and that selecting End would give me all the projects that used the selected project.  I didn't realize that the feature required you to select a start **and** an end project to work.

I can see the value of selecting a start and an end project, but I think the feature would be much more valuable if you could select a start project without having to select an end project and vis versa. The behaviour I would expect in this situation would be all the projects the selected project depends on (start) and all the projects that depend on the selected project (end).

## Motivation
Because graphs for any reasonable size workspace becomes far too sprawling to be useful, you need some strategies for limiting the projects you are looking for. 

For seeing all the projects that the selected project uses, it would give you a sense of how many things you will be pulling into  your app if you have to rely on the selected project.

For seeing all the projects that use the selected project, you get to see which other projects are potentially going to be affected by the changes you are about to make in the selected project. 

## Suggested Implementation
When I select a project in the graph, I could click on the Start button. This would fill in the start project just like it does now. The change would be that the graph would instantly be limited to all of the projects that the selected project uses, without having to select an end project. 
If I then select one of the on screen projects and click end, then it would behave just as it does today when you select a start and an end project.

Similarily with clicking on the end button first, it would show all the projects that use this project directly and indirectly. If I then choose one of those projects and click start, it would act as it does today when selecting both start and end.

I would also expect that I could remove the start or end (when I have both selected) and the graph would update to show either the projects up stream or down stream as if I had just selected the one project.

**Comment by philipjfulcher** [comment]
@gregveres - I still think this is an interesting feature, but I don't have time to implement it right now. If you (or anyone else watching this thread) is willing to implement, I can help get you started.
