### ISSUE TITLE
Enable independent typecheck executor / execution step

### ISSUE THREAD

**Issue by cdaringe** [nrwl/nx#10413]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

From any project, `nx typecheck <project-name>`

## Motivation

Skipping typechecking in targets can greatly speed up some targets, such as tests. However, we want to catch up to type errors, or schedule them out to some beefier worker perhaps in CI.

It is useful to be able to go fast **in some cases** (dev, ci), while staying true to safety and allowing for typechecking independently. Those cases are surely hotly contested, and I would suggest out-of-scope discussion for this particular issue.

## Suggested Implementation

- nx plugin that autoregisters the `typecheck` target for all projects with a `tsconfig.json`

**However, if i `cd libs/foo` && `node ../../node_modules/.bin/tsc`, currently typechecking doesn't quite work independently with tsc using default nx patterns** 🤔 

nx sets `files: [], include: []`, then uses `references` in tsconfig.json. it's not clear how to actually _do_ typechecking in a way that is compatible with NX's current tsconfig setup.

```js
// some-typecheck-plugin.js
const path = require("path");
const executor = `${path.resolve(__dirname, "..")}:typecheck`;
const target = { executor, options: {} };
const targets = { typecheck: target };

module.exports = {
  name: "workspace-typecheck-plugin",
  projectFilePatterns: ["tsconfig.json"],
  registerProjectTargets: () => targets,
};
```

## Alternate Implementations

- don't offer it
- offer it as an optional plugin

**Comment by AgentEnder** [comment]
Thanks for chiming in, I was going between the two and I think you could be correct. The **_only_** real benefit I can think of would be the ability to specify the `emit` flag in a configuration, but I don't think it'd be a real value.

If / when we move forward, we should use the new executor approach.

@cdaringe let me know if you have concerns, or do want to start work on this so the issue can be assigned to you.

**Comment by cdaringe** [comment]
huh, i was unaware that such an executor _already_ existed. will need to study to better understand _why_ `tsc -p libs/foo/bar/tsconfig.json` emits no type errors, but the nrwl/nx executor _does_. I'm assuming the run-typecheck executor does emit errors when errors are present--I haven't actually validated that yet :)

If that's the case, it seems that allowing arbitrary additional flags to flow into `compilerOptions` may be the best course of action, that way the executor doesn't need to indefinitely mirror 🪞  the full typescript API. Specifying one-off or arbitrary flags in the executor schema is not a good growth strategy for the `schema.json`. Alternatively, some pattern, maybe `--compilerOptions.foo=bar --compilerOptions.baz=zap` would make that extensibility story work better, where there's some convention for arbitrary flag forwarding.  adding incremental exposure to nx executor entrypoints seems to be a common theme when working w/ nx source.  would be nice to have an improved mechanism for proxying config thru the nx cli into their eventual tooling target.

**Comment by nartc** [comment]
@cdaringe just want to clarify that `runTypeCheck` is not an _executor_ but a utility function inside of `nrwl/js`. And it is actually exposed as `nrwl/js` public API so you can technically import and run it. 
```ts
import { runTypeCheck } from '@nrwl/js';
```

**Comment by cdaringe** [comment]
oh, thx! sorry, i only gave a very rapid scan and made some bad assumptions :)
