### ISSUE TITLE
Jest testing fails on both an existing project or a freshly generated nx react app in my monorepo

### ISSUE THREAD

**Issue by sicarius97** [nrwl/nx#10428]
## Current Behavior
When running nx test, I am currently experiencing the error 'cannot use import statement outside a module' like below:
![image](https://user-images.githubusercontent.com/73046273/169725153-3bad9f64-4bd7-4990-a7a6-45f1aa905051.png)
 

## Expected Behavior
I expected tests to pass as normal, I only started experiencing this after switching over to nx for monorepo tooling

## Steps to Reproduce
I am actually not sure on this, we formerly didn't have tooling for our monorepo and we transitioned over to nx. Since testing wasn't working with the existing app after the transition, I tried generating a new app in that same monorepo, but nx test still would not work. After that, I created an entirely new nx workspace with the react app option selected, and then ran nx test, and it did work. I'm not sure what could be going on here as my configs were pretty much the same as the default ones that came with the newly scaffolded workspace. Here are my current configs:

nx.json:
```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "npmScope": "sl-vnext",
  "affected": {
    "defaultBase": "main"
  },
  "cli": {
    "defaultCollection": "@nrwl/react"
  },
  "implicitDependencies": {
    "package.json": {
      "dependencies": "*",
      "devDependencies": "*"
    },
    ".eslintrc.json": "*"
  },
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build", "lint", "test", "e2e"]
      }
    }
  },
  "targetDependencies": {
    "build": [
      {
        "target": "build",
        "projects": "dependencies"
      }
    ]
  },
  "generators": {
    "@nrwl/react": {
      "application": {
        "style": "styled-components",
        "linter": "eslint",
        "babel": true
      },
      "component": {
        "style": "styled-components"
      },
      "library": {
        "style": "styled-components",
        "linter": "eslint"
      }
    },
    "@nrwl/web:application": {
      "style": "css",
      "linter": "eslint",
      "unitTestRunner": "jest",
      "e2eTestRunner": "cypress"
    },
    "@nrwl/web:library": {
      "style": "css",
      "linter": "eslint",
      "unitTestRunner": "jest"
    }
  },
  "defaultProject": "vnext-web"
}
```
workspace.json:
```json
{
  "$schema": "./node_modules/nx/schemas/workspace-schema.json",
  "version": 2,
  "projects": {
    "nest-blockchain": "packages/nest/blockchain",
    "nest-common": "packages/nest/common",
    "nest-db": "packages/nest/db",
    "services-ec-api": "packages/services/ec-api",
    "services-matchmaker": "packages/services/matchmaker",
    "services-socket-server": "packages/services/socket-server",
    "services-steemmonsters": "packages/services/steemmonsters",
    "vnext-api": "packages/vnext/api",
    "vnext-core": "packages/vnext/core",
    "vnext-web": "packages/vnext/web",
    "vnext-web-e2e": "packages/vnext/web-e2e"
  }
}
```
### Environment
```
Node : 16.14.2
   OS   : win32 x64
   npm  : 8.5.0
   
   nx : 14.1.7
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.7
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.7
   @nrwl/eslint-plugin-nx : 14.1.7
   @nrwl/express : 14.1.7
   @nrwl/jest : 14.1.7
   @nrwl/js : 14.1.7
   @nrwl/linter : 14.1.7
   @nrwl/nest : 14.1.7
   @nrwl/next : Not Found
   @nrwl/node : 14.1.7
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.1.7
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.7
   @nrwl/web : 14.1.7
   @nrwl/workspace : 14.1.7
   typescript : 4.6.4
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:
```

**Comment by barbados-clemens** [comment]
can you share your projects jest.config.ts?

**Comment by aautem** [comment]
@barbados-clemens Same issue here. Here are my config files which were auto-generated when initializing my workspace with the react preset. I didn't make any changes.

```js
// ./apps/my-app/jest.config.ts
export default {
  displayName: 'my-app',
  preset: '../../jest.preset.js',
  transform: {
    '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': '@nrwl/react/plugins/jest',
    '^.+\\.[tj]sx?$': 'babel-jest',
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  coverageDirectory: '../../coverage/apps/my-app',
};


// ./jest.preset.js
const nxPreset = require('@nrwl/jest/preset').default;

module.exports = { ...nxPreset };


// ./jest.config.ts
import { getJestProjects } from '@nrwl/jest';

export default {
  projects: getJestProjects(),
};
```

**Comment by barbados-clemens** [comment]
@aautem this is very interesting because I just run `npx create-nx-workspace@latest` and use react and it _just works_ 

can you try updating your `babel-jest` transformer like so `<regex>: ['babel-jest', { presets: ['@nrwl/react/babel'] }],` 

I've started a [repo to run more in-depth validation](https://github.com/barbados-clemens/testing-validation-bench) for jest + nx as there are a lot of customizations that can happen that I'm just not aware of and noticed sometimes babel-jest needs to be told what preset to use but still trying to figure out why. 

You can also try cloning the repo and running `npm run validate` and see if that fails on your system to see if it's an environmental thing vs nx thing. it's really just a default workspace with a couple of extra options added for using other libs.

**Comment by aautem** [comment]
@barbados-clemens Thanks for the quick response!

Double checked my changes since initializing the workspace and tracked the issue down to a `NODE_ENV` override in a `.env.local` file. I had set `NODE_ENV=development` without realizing it was always being used. Jest seems to require `NODE_ENV=test`.

**Comment by barbados-clemens** [comment]
Ah, interesting. it looks like we set it `test` if it's not currently set. wonder if we should make that a warning or something when not set correctly 🤔 

[`process.env.NODE_ENV ??= 'test';`](https://github.com/nrwl/nx/blob/master/packages/jest/src/executors/jest/jest.impl.ts#L13)
