### ISSUE TITLE
Nx restores incorrect cache

### ISSUE THREAD

**Issue by Matwog** [nrwl/nx#10431]
First of all, thanks a ton to the authors for the great work with Nx. ❤️ 🚀 
We, in our codebase, recently migrated away from `yarn` and `lerna` to using `pnpm` and would like to integrate `Nx` and observed few blockers.

## Current Behavior

Nx in a monorepo using PNPM workspaces does not restore the correct cache.

## Expected Behavior

Nx restores the correct cache.

## Steps to Reproduce

- Please use this repo [minimal repo](https://github.com/Matwog/investigating-pnpm-nx) to reproduce this issue.
- Run `pnpm install` at root level
- Run `pnpm build-all`. 
- The files are put into the the `build` folder. Observe the files in the `build` folder.
- Now modify the console log statement in `index.js` file in `package-one`.
- Run `pnpm build-all`. Nx triggers a fresh build for `package-one` but uses the cached version for `package-two`. 🚀 
- Now revert back the console log in the `index.js` file in `package-one` and run `pnpm build-all`.
- Nx says that it uses the local cache as shown in the below screenshot.
- Observe the `index.js` file inside the `build` folder. It does not reflect the latest state of the source file. 

![Screenshot 2022-05-23 at 13 38 47](https://user-images.githubusercontent.com/52502941/169811382-eddec2cf-e668-4511-b4c4-b610ab837ed0.png)

**Additional Info:** **Nx was added to the repo by running `npx add-nx-to-monorepo`.**

- This is a very minimalistic example of the actual issue that we face with trying to integrate Nx into our repo using `pnpm`. This would be a potential blocker. 

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

The above screenshot may be useful.

### Environment

```
 Node : 16.13.2
   OS   : darwin x64
   pnpm : 7.0.1
   
   nx : 14.1.7
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : Not Found
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : Not Found
   typescript : Not Found
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by AgentEnder** [comment]
Hey @Matwog! I think I see what is going on. Here are the two elements at play:
- Nx relies on an `outputs` property to know where your artifacts are for each script ran. For test (w/o coverage) this is normally none, but for build you are outputting an artifact to disk.
- Your build script outputs the artifact to a "non-standard" spot. 

Here is the docs on how to specify non-standard outputs: https://nx.dev/configuration/packagejson#project-configuration

Nx supports build artifacts in the following locations by default:
- `dist/path/to/package/root`
- `path/to/package/root/dist`
- `path/to/package/root/build`
- `path/to/package/root/public`

**Comment by Matwog** [comment]
@AgentEnder Thanks for quick response.

Yes specifying non-standard outputs makes sense. I tried it now in the [minimal repo](https://github.com/Matwog/investigating-pnpm-nx) and I can see that Nx works and is able to correctly restore the cache. 👍 
Will try to integrate the same way for our product.
