### ISSUE TITLE
Can't use `libraryGenerator` from `@nrwl/workspace` without `@angular-devkit/schematics`

### ISSUE THREAD

**Issue by kitsune7** [nrwl/nx#10437]
## Current Behavior

I'm trying to create a custom generator that extends `libraryGenerator` from `@nrwl/workspace`, but I get an error when I try to run it without adding `@angular-devkit/schematics` first.

## Expected Behavior

I expect to be able to use the Nx's library generator without adding `@angular-devkit/schematics` as a dependency. It's not mentioned anywhere in the [documentation](https://nx.dev/generators/composing-generators#using-nx-devkit-generators) on composing generators (the documentation is even using this specific generator).

### Failure Logs

```shell
Cannot find module '@angular-devkit/schematics'
Require stack:
- /Users/my-user/frontend/node_modules/.pnpm/@nrwl+workspace@14.1.5_y6u32vedbwjta2g3ygg56bhflu/node_modules/@nrwl/workspace/src/utils/ast-utils.js
- /Users/my-user/frontend/node_modules/.pnpm/@nrwl+workspace@14.1.5_y6u32vedbwjta2g3ygg56bhflu/node_modules/@nrwl/workspace/src/utils/project-type.js
- /Users/my-user/frontend/node_modules/.pnpm/@nrwl+workspace@14.1.5_y6u32vedbwjta2g3ygg56bhflu/node_modules/@nrwl/workspace/index.js
- /Users/my-user/frontend/dist/tools/generators/make-lib/index.js
- /Users/my-user/frontend/node_modules/.pnpm/nx@14.1.5_typescript@4.6.4/node_modules/nx/src/config/workspaces.js
- /Users/my-user/frontend/node_modules/.pnpm/nx@14.1.5_typescript@4.6.4/node_modules/nx/src/command-line/generate.js
- /Users/my-user/frontend/node_modules/.pnpm/nx@14.1.5_typescript@4.6.4/node_modules/nx/src/command-line/workspace-generators.js
- /Users/my-user/frontend/node_modules/.pnpm/nx@14.1.5_typescript@4.6.4/node_modules/nx/src/command-line/nx-commands.js
- /Users/my-user/frontend/node_modules/.pnpm/nx@14.1.5_typescript@4.6.4/node_modules/nx/bin/init-local.js
- /Users/my-user/frontend/node_modules/.pnpm/nx@14.1.5_typescript@4.6.4/node_modules/nx/bin/nx.js
 ELIFECYCLE  Command failed with exit code 1.
```

### Environment

   Node : 16.13.0
   OS   : darwin x64
   pnpm : 7.1.2
   
   nx : 14.1.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.5
   @nrwl/eslint-plugin-nx : 14.1.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.5
   @nrwl/js : Not Found
   @nrwl/linter : 14.1.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.0.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.5
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         @nxext/vite: 14.0.0

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This is due to the `@nrwl/workspace` entry point having some backward-compatible exports that do require `@angular/devkit`. Could you please change the import to the library generator to `import { libraryGenerator } from '@nrwl/workspace/generators';` instead?

I'll amend the docs to make sure they recommend the right import.
