### ISSUE TITLE
Enable `"hot": "only"` scenario

### ISSUE THREAD

**Issue by ziacik** [nrwl/nx#10430]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
webpack-dev-server has this schema for `hot`:
```json
    {
      "anyOf": [
        {
          "type": "boolean",
          "cli": {
            "negatedDescription": "Disables Hot Module Replacement."
          }
        },
        {
          "enum": ["only"]
        }
      ],
      "description": "Enables Hot Module Replacement.",
      "link": "https://webpack.js.org/configuration/dev-server/#devserverhot"
    }
```

But `hmr` in web/dev-server only allows a boolean, and setting `liveReload: false` does not prevent the page from full reloading if hot reload is not possible.

## Motivation
Sometimes we want to only allow hot reload but prevent reload as a fallback.

## Suggested Implementation
When `hmr` is set to `true` and `liveReload` is set to `false`, translate it to `hot: "only"` in webpack config.

## Alternate Implementations
Enable `hmr: "only"` in schema.

**Comment by gamegee** [comment]
@ziacik same issue here

**Comment by ziacik** [comment]
Not stale (I guess)
