### ISSUE TITLE
Usage of `convertNxExecutor` should not incur installing `@swc`

### ISSUE THREAD

**Issue by damienwebdev** [nrwl/nx#10441]
## Current Behavior

I'm using https://github.com/angular-eslint/angular-eslint in an Angular 13 project. I do not use Nx in this project, yet surprisingly, I found a tree in my `node_modules` that uses `nx` not once, but twice!

## Expected Behavior
I do not need `nx` in my dep graph for a linter.

## Steps to Reproduce
1. Install `angular-eslint` in a fresh ng13 Angular CLI project.
2. npm ls `@swc/core-linux-x64-gnu@1.2.186 `

```txt
frontend@0.0.0 /frontend
└─┬ @angular-eslint/builder@13.2.1
  └─┬ @nrwl/devkit@13.1.3
    └─┬ @nrwl/tao@13.1.3
      └─┬ nx@13.1.3
        └─┬ @nrwl/cli@14.1.7
          └─┬ nx@14.1.7
            └─┬ @swc/core@1.2.186
              └── @swc/core-linux-x64-gnu@1.2.186 
```

3. `du -h node_modules -d 1 | sort -h

```txt
47M     node_modules/@daffodil
57M     node_modules/dgeni-packages
59M     node_modules/@nrwl
61M     node_modules/typescript
109M    node_modules/@angular-devkit
114M    node_modules/@angular
166M    node_modules/canvas
821M    node_modules/@swc
2.1G    node_modules/
```

4. Be concerned.

See https://github.com/angular-eslint/angular-eslint/issues/982 for additional information.

### Environment
```
frontend$ npx ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.2.6
Node: 16.14.2
Package Manager: npm 8.5.0
OS: linux x64

Angular: 13.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.6
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.3.6
@angular-devkit/schematics      13.3.6
@angular/cdk                    13.3.7
@angular/cli                    13.2.6
@angular/elements               13.3.9
@angular/localize               13.3.9
@nguniversal/common             13.0.2
@schematics/angular             13.3.6
ng-packagr                      13.3.1
rxjs                            7.5.5
typescript                      4.4.4
webpack                         5.72.1
```

**Comment by AgentEnder** [comment]
Hey @damienwebdev! 

We are working on eliminating some of the strict dep's from the main Nx package that should make it less of an issue in cases like this. Currently, we are working to eliminate the dependency on:
- rxjs (done, removed from `nx`)
- typescript (tbd)
- swc (should be optional, I'm working on this one now.)

Unfortunately, using convertNxExecutor will always bring in Nx since its a runtime util and not a build time util. Hopefully lessening our bundle size will make this less of a burden in the plain-angular situations.

**Comment by AgentEnder** [comment]
I'm going to close this out `@swc/core` is an optional dep now.
