### ISSUE TITLE
Hash computation does not take .gitignore in nested directory into account

### ISSUE THREAD

**Issue by blaugold** [nrwl/nx#10442]
## Current Behavior
A file that is ignored by a .gitignore file other than the one at the workspace root, will prevent cache hits if it changes.

## Expected Behavior
Regardless of through which .gitignore file a file is ignored, it should not be used to calculate cache hashes.

## Steps to Reproduce
1. Clone `https://github.com/blaugold/nx-gitignore-caching`
2. `npm i`
3. `npx nx test foo`
4. Create `packages/foo/src/ingored.ts`, which is ignored by `packages/foo/.gitignore`
5. `npx nx test foo`: Should be a cache hit, but is executed again.

### Environment
```
 >  NX   Report complete - copy this into the issue template

   Node : 16.13.1
   OS   : darwin arm64
   npm  : 8.1.2
   
   nx : 14.1.7
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.7
   @nrwl/eslint-plugin-nx : 14.1.7
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.7
   @nrwl/js : 14.1.7
   @nrwl/linter : 14.1.7
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.7
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by wittjosiah** [comment]
I'm still seeing this issue in 15.2.1, can this be re-opened? It seems as though the PR which resolved this issue was reverted and as far as I can tell was never fixed again.
