### ISSUE TITLE
Creating a new library: ENOENT: no such file or directory, scandir

### ISSUE THREAD

**Issue by duxard** [nrwl/nx#10449]
Hi Team,

I have a NX monorepo (D\myorg) created by nx CLI. It has the following basic structure:

myorg/
├── apps/
│   ├── todos/
│   ├── todos-e2e/
│   └── api/
├── libs/
│   └──  shared/
│          └──  some_other_library/
├── tools/
├── .eslintrc.json
├── nx.json
├── package.json
└── tsconfig.base.json

I'm trying to generate an angular library ("ui") and I'm using this command:
https://nx.dev/angular-tutorial/08-create-libs

D\myorg:> `npx nx g @nrwl/angular:lib ui`

However, I'm getting this error:

`ENOENT: no such file or directory, scandir 'D\myorg\libs\ui'`

I tried to remove node_modules and do "npm install" but it didn't help...

Could you please advice on this?

**Comment by duxard** [comment]
@driley-abbvie thanks, I will take a look. Actually I'm still now able to overcome this issue. Still looking for a way to resolve it.

**Comment by Coly010** [comment]
@duxard Can you run `nx report` and paste the result here? It'll help us track down where the issue is :)

Thank you!!

**Comment by duxard** [comment]
@Coly010 Here you go:
 ```


>  NX  Report complete - copy this into the issue template

 

  Node : 16.13.1

  OS   : win32 x64

  npm  : 8.3.0

 

  nx : undefined

  @nrwl/angular : 13.3.12

  @nrwl/cli : 13.3.12

  @nrwl/cypress : 13.3.12

  @nrwl/devkit : 13.3.12

  @nrwl/eslint-plugin-nx : undefined

  @nrwl/express : 13.3.12

  @nrwl/jest : 13.3.12

  @nrwl/linter : 13.3.12

  @nrwl/nest : undefined

  @nrwl/next : undefined

  @nrwl/node : 13.3.12

  @nrwl/nx-cloud : undefined

  @nrwl/react : 13.3.12

  @nrwl/react-native : undefined

  @nrwl/schematics : undefined

  @nrwl/tao : 13.3.12

  @nrwl/web : 13.3.12

  @nrwl/workspace : 13.3.12

  @nrwl/storybook : 13.3.12

  @nrwl/gatsby : undefined

  typescript : 4.4.4

  rxjs : 7.4.0

  ---------------------------------------

  Community plugins:

         @angular/animations: 13.1.3

         @angular/common: 13.1.3

         @angular/compiler: 13.1.3

         @angular/core: 13.1.3

         @angular/forms: 13.1.3

         @angular/platform-browser: 13.1.3

         @angular/platform-browser-dynamic: 13.1.3

         @angular/router: 13.1.3

         ng-zorro-antd: 11.4.2

         @angular-devkit/build-angular: 13.1.4

         @angular/cli: 13.1.4

         @angular/compiler-cli: 13.1.3

         @angular/language-service: 13.1.3

 
```

Thanks,

Aleksandr

**Comment by Coly010** [comment]
@duxard I see you're on an older version of Nx. Could you try migrate to latest and see if your problem still exists?

`nx migrate latest && nx migrate --run-migrations`
