### ISSUE TITLE
nx migrate latest from 14.1.7 -> 14.1.8 fails

### ISSUE THREAD

**Issue by atsjo** [nrwl/nx#10459]
## Current Behavior
yarn nx migrate latest fails... I've had problems migrating all since v14, and every time I have ended up doing it via yarn up first, then rolling back and then doing via nx migrate (to get the migrations) . Nx has double fetched all nrwl packages since 14.x, and now it seems to try to fetch some packages for a third time with invalid paths:
....
Fetching @nrwl/angular@file:../angular
Fetching @nrwl/js@file:../js
Fetching @nrwl/cypress@file:../cypress

## Expected Behavior
It works...

### Failure Logs
C:\Users\atles\source\repos\teve-no\task4s>yarn nx migrate latest
yarn run v1.22.18
$ C:\Users\atles\source\repos\teve-no\task4s\node_modules\.bin\nx migrate latest
Fetching meta data about packages.
It may take a few minutes.
Fetching nx@14.1.8
Fetching nx@latest
Fetching @nrwl/js@14.1.8
Fetching @nrwl/jest@14.1.8
Fetching @nrwl/workspace@14.1.8
Fetching @nrwl/angular@14.1.8
Fetching @nrwl/linter@14.1.8
Fetching @nrwl/cypress@14.1.8
Fetching @nrwl/workspace@14.1.8
Fetching @nrwl/js@14.1.8
Fetching @nrwl/jest@14.1.8
Fetching @nrwl/linter@14.1.8
Fetching @nrwl/cypress@14.1.8
Fetching @nrwl/angular@14.1.8
Fetching @nrwl/angular@file:../angular
Fetching @nrwl/js@file:../js
Fetching @nrwl/cypress@file:../cypress

 ERROR  The migrate command failed.

Command failed: yarn add -W @nrwl/angular@file:../angular
warning package.json: No license field
warning No license field
error Package "" refers to a non-existing file '"C:\\Users\\atles\\AppData\\Local\\Temp\\angular"'.

Done in 79.09s.
### Environment
 >  NX   Report complete - copy this into the issue template

   Node : 16.15.0
   OS   : win32 x64
   yarn : 1.22.18

   nx : 14.1.7
   @nrwl/angular : 14.1.7
   @nrwl/cypress : 14.1.7
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.7
   @nrwl/eslint-plugin-nx : 14.1.7
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.7
   @nrwl/js : 14.1.7
   @nrwl/linter : 14.1.7
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.7
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.7
   typescript : 4.6.4
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:

**Comment by driley-abbvie** [comment]
Also not working for me 

Error when trying to generate new node app, what got me here
```
> Executing task: yarn nx generate @nrwl/node:application sqs-cli --no-interactive --dry-run <

yarn run v1.22.18
$ /Users/rileydd/dev/provider-directory/node_modules/.bin/nx generate @nrwl/node:application sqs-cli --no-interactive --dry-run
Cannot find module 'nx/src/generators/utils/json'
Require stack:
- /Users/rileydd/dev/provider-directory/node_modules/@nrwl/node/node_modules/@nrwl/devkit/src/generators/format-files.js
- /Users/rileydd/dev/provider-directory/node_modules/@nrwl/node/node_modules/@nrwl/devkit/index.js
- /Users/rileydd/dev/provider-directory/node_modules/@nrwl/node/src/generators/application/application.js
- /Users/rileydd/dev/provider-directory/node_modules/nx/src/config/workspaces.js
- /Users/rileydd/dev/provider-directory/node_modules/nx/src/command-line/generate.js
- /Users/rileydd/dev/provider-directory/node_modules/nx/src/command-line/nx-commands.js
- /Users/rileydd/dev/provider-directory/node_modules/nx/bin/init-local.js
- /Users/rileydd/dev/provider-directory/node_modules/nx/bin/nx.js
error Command failed with exit code 1.
```

Error when trying to migrate
```
❯ nx migrate latest
✔ We noticed you are migrating to a new major version, but are not taking advantage of Nx Cloud. Nx Cloud can make your CI up to 10 times faster. Learn more about it here: nx.app. Would you like to add it? · No

Fetching meta data about packages.
It may take a few minutes.
Fetching nx@14.1.8
Fetching @nrwl/nest@14.1.8
Fetching @nrwl/workspace@14.1.8
Fetching @nrwl/linter@14.1.8
Fetching @nrwl/node@14.1.8
Fetching @nrwl/jest@14.1.8
Fetching @nrwl/linter@file:../linter
Fetching @nrwl/nest@file:../nest
Fetching @nrwl/jest@file:../jest

 ERROR  The migrate command failed.

Command failed: yarn add -W @nrwl/nest@file:../nest
warning package.json: No license field
warning No license field
error Package "" refers to a non-existing file '"/private/var/folders/6x/j0m2hjv93ys9481_vmqf1zz8vp42h_/T/nest"'.

```

Report
```
 >  NX   Report complete - copy this into the issue template

   Node : 18.2.0
   OS   : darwin arm64
   yarn : 1.22.18
   
   nx : 13.10.5
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.0.5
   @nrwl/eslint-plugin-nx : 14.0.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.5
   @nrwl/js : 14.0.5
   @nrwl/linter : 14.0.5
   @nrwl/nest : 14.0.5
   @nrwl/next : Not Found
   @nrwl/node : 14.0.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.0.5
   typescript : 4.6.4
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:

```

**Comment by driley-abbvie** [comment]
I dont know why this worked but I bumped down my nvm to 16 tried, it didnt work, bumped back up to 18 and ran `nx migrate latest --verbose` and it worked

**Comment by AndrewBGM** [comment]
I was able to solve this by using setting the versions in the migration command via `--to="@nrwl/js@14.1.8,..."

**Comment by timtos** [comment]
I have the same or at least a similar issue. How small my migrate step should be I always get a message like

`Command failed: yarn add -W @nrwl/linter@14.1.9`

The actual package name differs. After executing that command manually, it is possible to run the migration without problem.

**Comment by atsjo** [comment]
worked for me with 14.1.9... maybe this https://github.com/nrwl/nx/pull/10411 is a fix for it... hoping I won't have to mess around with workarounds for upgrading in the future, it all worked flawlessly until v14 for me...

**Comment by timtos** [comment]
@AgentEnder It was indeed a transient error. After doing a nx reset, the migration step succeeded. Thank you.

But one thing I don't understand: Why does nx update the @storybook/addon-notes package to verison 6.4.12 when the latest package version available is still 5.3.21. Perhaps I should create a ticket for that?

**Comment by AgentEnder** [comment]
Huh, yeah that looks wrong. open one up

**Comment by timtos** [comment]
@AgentEnder Ok, created [a ticket](https://github.com/nrwl/nx/issues/10484). Thank you for your support.
