### ISSUE TITLE
Storybook 6.5 isn't compatible with nx

### ISSUE THREAD

**Issue by prewk** [nrwl/nx#10469]
## Current Behavior

Storybook 6.5 isn't compatible with nx.

## Expected Behavior

That Storybook 6.5 is supported.

## Steps to Reproduce & Failure Logs

Update Storybook from 6.4 like so: `npx storybook@latest upgrade` This bumps all of the Storybook packages to 6.5.

Then run a Storybook instance that previously worked. This crash happens:

```
Cannot find module '@storybook/core/server'
Require stack:
- /<redacted>/node_modules/@nrwl/storybook/src/executors/storybook/storybook.impl.js
- /<redacted>/node_modules/@nrwl/tao/src/shared/workspace.js
- /<redacted>/node_modules/@nrwl/tao/src/commands/run.js
- /<redacted>/node_modules/@nrwl/tao/index.js
- /<redacted>/node_modules/@nrwl/cli/lib/run-cli.js
```

It seems `@storybook/core/server` has been replaced with `@storybook/core-server` or something?

### Environment

```
  Node : 14.18.1
  OS   : darwin x64
  yarn : 1.22.17

  nx : 12.9.0
  @nrwl/angular : 12.9.0
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 999.9.9             # <-WTF?
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

Since `nx report` gave strange results above I ran `yarn why @nrwl/storybook`: `Found "@nrwl/storybook@14.1.9"`

**Comment by CodeCakePie** [comment]
It is also not working on my project (even though i ran the latest migrations)
