### ISSUE TITLE
Angular MFE No version specified and unable to determine one

### ISSUE THREAD

**Issue by yharaskrik** [nrwl/nx#10460]
## Current Behavior

When building a host in our application after running `nx g @nrwl/angular:setup-mfe` we are getting the following warnings in the console.

```
shared module firebase/app -> /Users/jaybell/WebstormProjects/trellis-mono4/node_modules/firebase/app/dist/index.esm.js - Warning: No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file, or manually specify version in shared config.

shared module firebase/auth -> /Users/jaybell/WebstormProjects/trellis-mono4/node_modules/firebase/auth/dist/index.esm.js - Warning: No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file, or manually specify version in shared config.

shared module firebase/app-check -> /Users/jaybell/WebstormProjects/trellis-mono4/node_modules/firebase/app-check/dist/index.esm.js - Warning: No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file, or manually specify version in shared config.

shared module firebase/remote-config -> /Users/jaybell/WebstormProjects/trellis-mono4/node_modules/firebase/remote-config/dist/index.esm.js - Warning: No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file, or manually specify version in shared config.

shared module firebase/messaging -> /Users/jaybell/WebstormProjects/trellis-mono4/node_modules/firebase/messaging/dist/index.esm.js - Warning: No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file, or manually specify version in shared config.

shared module firebase/analytics -> /Users/jaybell/WebstormProjects/trellis-mono4/node_modules/firebase/analytics/dist/index.esm.js - Warning: No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file, or manually specify version in shared config.

shared module @apollo/client/utilities -> /Users/jaybell/WebstormProjects/trellis-mono4/node_modules/@apollo/client/utilities/index.js - Warning: No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file, or manually specify version in shared config.

shared module @apollo/client/core -> /Users/jaybell/WebstormProjects/trellis-mono4/node_modules/@apollo/client/core/index.js - Warning: No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file, or manually specify version in shared config.

shared module @apollo/client/link/batch -> /Users/jaybell/WebstormProjects/trellis-mono4/node_modules/@apollo/client/link/batch/index.js - Warning: No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file, or manually specify version in shared config.

shared module @apollo/client/link/subscriptions -> /Users/jaybell/WebstormProjects/trellis-mono4/node_modules/@apollo/client/link/subscriptions/index.js - Warning: No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file, or manually specify version in shared config.
```

Each of the secondary entry points have a `package.json` that does not have a `version` in it, even though the root packages `package.json` does.

For example `node_modules/@apollo/client/core/package.json` does not have a version but `node_modules/@apollo/package.json` does.

![image](https://user-images.githubusercontent.com/9469090/170111334-73cba7ea-26c2-46aa-919e-6d2b2d9147af.png)

![image](https://user-images.githubusercontent.com/9469090/170111355-d0671469-514f-47d8-bd98-61004b7fd797.png)

This does not seem to be a warning from Nx but rather from webpack instead has Nx is correctly collecting the secondary entry points and their version as can be seen from the calculated shared libs here:

```
"@apollo/client": {
    "singleton": true,
    "strictVersion": true,
    "requiredVersion": "^3.6.0"
  },
  "@apollo/client/cache": {
    "singleton": true,
    "strictVersion": true,
    "requiredVersion": "^3.6.0"
  },
  "@apollo/client/core": {
    "singleton": true,
    "strictVersion": true,
    "requiredVersion": "^3.6.0"
  },
  "@apollo/client/errors": {
    "singleton": true,
    "strictVersion": true,
    "requiredVersion": "^3.6.0"
  },
  "@apollo/client/link/batch": {
    "singleton": true,
    "strictVersion": true,
    "requiredVersion": "^3.6.0"
  },
  "@apollo/client/link/batch-http": {
    "singleton": true,
    "strictVersion": true,
    "requiredVersion": "^3.6.0"
  },
/// etc
```

Note this is only true for `@apollo/client/*` from my error logs, `firebase` does not seem to be shared at all for some reason. I print the entire sharedLibraries out and firebase does not exist in the shared libs. We do not use `firebase` directly, instead we are using AngularFire which would then use firebase internally. do I need to configure firebase as an additonal shared dep or should Nx see that AngularFire depends on firebase and then share it automatically?

## Expected Behavior

MFE tooling should correctly share the packages

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

See above

### Environment

```
 NX   Report complete - copy this into the issue template

   Node : 14.19.0
   OS   : darwin x64
   yarn : 1.22.18
   
   nx : 14.1.7
   @nrwl/angular : 14.1.7
   @nrwl/cypress : 14.1.7
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.7
   @nrwl/eslint-plugin-nx : 14.1.7
   @nrwl/express : 14.1.7
   @nrwl/jest : 14.1.7
   @nrwl/js : 14.1.7
   @nrwl/linter : 14.1.7
   @nrwl/nest : 14.1.7
   @nrwl/next : Not Found
   @nrwl/node : 14.1.7
   @nrwl/nx-cloud : 14.0.3
   @nrwl/nx-plugin : 14.1.7
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.7
   @nrwl/web : 14.1.7
   @nrwl/workspace : 14.1.7
   typescript : 4.6.3
   rxjs : 7.4.0
```

**Comment by yharaskrik** [comment]
Oddly, on a subsequent run the firebase warnings are now gone but the `@apollo/client/*` warnings are still there.

**Comment by yharaskrik** [comment]
Adding this also does not solve the issue so I believe it is an outside of Nx issue, not sure what we can do about it since it seems webpack just isn't happy that the package.jsons don't have a version

![image](https://user-images.githubusercontent.com/9469090/170114363-55e0038f-d449-4b62-bc68-9a2bebcd7b6a.png)

**Comment by Coly010** [comment]
Yeah, this is an interesting problem. I'll need to look at the internals of webpack's `ModuleFederationPlugin` to see how it's interpreting versions. 

You said this happens at build time?

**Comment by yharaskrik** [comment]
> Yeah, this is an interesting problem. I'll need to look at the internals of webpack's `ModuleFederationPlugin` to see how it's interpreting versions.
> 
> You said this happens at build time?

Yup, it's a warning when running the dev-server. 

Line 131 `ProvideShaedPlugin.js` in the webpack repo is where it is thrown. I think it has to do with some packages not publishing versions in their secondary entyr points package.json

this does work but obviously is not desirable

![image](https://user-images.githubusercontent.com/9469090/170555283-b83decd6-1143-4882-a3f2-1166fdce5223.png)

**Comment by Coly010** [comment]
@yharaskrik Can you try again with the latest version of Nx to see if this still exists?

**Comment by Fredo182** [comment]
I'm am still running into this issue with the apollo libraries running the lastest 14.5.2 nx version. Was this issue resolved?

**Comment by keaston67** [comment]
Just updated to nx version 14.7.11 and hit this issue.

**Comment by Coly010** [comment]
@keaston67 tracking this here now : https://github.com/nrwl/nx/issues/11765

**Comment by kenatwex** [comment]
Im getting this now

**Comment by nhhockeyplayer** [comment]
Okay looks like the caret '^' matters

```
    additionalShared: [
        '@angular/animations',
        '@angular/cdk',
        '@angular/common',
        '@angular/compiler',
        '@angular/core',
        '@angular/forms',
        '@angular/router',
        '@apollo/client',
        '@ngneat/transloco',
        '@ngrx/effects',
        '@ngrx/store',
        'ngrx-store-logger',
        'ngrx-store-freeze',
        'apollo-angular',
        'graphql',
        {
            libraryName: 'luxon',
            sharedConfig: {
                singleton: true,
                requiredVersion: '2.4.0',
                strictVersion: true
            }
        },
    ]
```

its working for me now across all host/remotes

I re-created all host.remotes without any intervention

works great as-is

cept' that caret

**Comment by nhhockeyplayer** [comment]
and I got root NgRX on deck too... yeah

**Comment by cougdoble** [comment]
@nhhockeyplayer did you have to make any changes to the config of your remotes or only in the host to get luxon working? I'm having a very similar looking issue with luxon, but your suggestion doesn't appear to be working for me.

**Comment by k7daniel** [comment]
I was able to fix this by importing @apollo/client and not @apollo/client/core
