### ISSUE TITLE
Allow API to be named when creating workspace with UI and API (e.g. react-express)

### ISSUE THREAD

**Issue by devklick** [nrwl/nx#10464]
- [x] I'd be willing to implement this feature (but I've honestly never even looked at the nx codebase) ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I would like to have the option of giving a name to my API when creating a `react-express` workspace (or other workspace that creates a UI and API). I have the option to name my react app, but my express API is always automatically called `api`. 

## Motivation

In a monorepo where it's possible to have multiple API's, I find name far too ambiguous.

## Suggested Implementation

After executing the `create-nx-workspace` command we are given the option specify an `Application name`. Since _two_ apps are created, I would like to be prompted to give my second app (the API) a name. 

## Alternate Implementations

Alternatively the name of the API could be determined based on the name of the application that the user specified. For example, if I specify my application name as `my-awesome-app`, the API could be called `my-awesome-app-api` rather than just `api`.

Another alternative is that we, the user, just create an empty workspace and add both the react app and API separately, allowing us to name each of them when we are created. Or create _either_ an express or react workspace, then add the other app after the initial creation, again allowing us to name each of them.

**Comment by devklick** [comment]
Another alternative which I've just realised is to execute the `move` command to essentialy rename the API after creating the `react-express` workspace. 

```
npx nx generate @nrwl/workspace:move my-awesome-app-api --projectName=api
```

**Comment by AgentEnder** [comment]
Hey @devklick, we've visited this idea before. You can find the relative discussion here: https://github.com/nrwl/nx/issues/7960

In short, there are ways to accomplish what you want that are more appropriate than trying to add all of the necessary settings to both presets.
