### ISSUE TITLE
Configuration '${configuration}' is not set in the workspace.

### ISSUE THREAD

**Issue by timtos** [nrwl/nx#10468]
## Current Behavior
* Clone [the angular mfe example](https://github.com/nrwl/ng-module-federation)
* Duplicate the 'development' configuration and rename it to something, in my case 'hmr'. (for build and serve)
* Try to serve the new configuration
* Result: `Configuration '${configuration}' is not set in the workspace`.

## Expected Behavior
The new configuration should be served.

### Failure Logs
yarn run v1.22.5
$ C:\Code\Playground\nx\ng-module-federation\node_modules\.bin\nx serve host --configuration=hmr

> nx run host:serve:hmr

C:\Code\Playground\nx\ng-module-federation\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:76
                        throw new Error(`Configuration '${configuration}' is not set in the workspace.`);
                              ^

Error: Configuration 'hmr' is not set in the workspace.
    at Object.getOptions (C:\Code\Playground\nx\ng-module-federation\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:76:31)
    at WorkspaceNodeModulesArchitectHost.getOptionsForTarget (C:\Code\Playground\nx\ng-module-federation\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:162:50)
    at async Promise.all (index 1)

 >  NX   Running target "host:serve" failed

   Failed tasks:

   - host:serve:hmr

### Environment
   Node : 16.13.2
   OS   : win32 x64
   yarn : 1.22.5

### Sample Project.json 
```
{
  "projectType": "application",
  "sourceRoot": "apps/host/src",
  "prefix": "ng-module-federation",
  "targets": {
    "build": {
      "executor": "@nrwl/angular:webpack-browser",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/apps/host",
        "index": "apps/host/src/index.html",
        "main": "apps/host/src/main.ts",
        "polyfills": "apps/host/src/polyfills.ts",
        "tsConfig": "apps/host/tsconfig.app.json",
        "assets": ["apps/host/src/favicon.ico", "apps/host/src/assets"],
        "styles": ["apps/host/src/styles.css"],
        "scripts": [],
        "customWebpackConfig": {
          "path": "apps/host/webpack.config.js"
        }
      },
      "configurations": {
        "production": {
          "budgets": [
            {
              "type": "initial",
              "maximumWarning": "500kb",
              "maximumError": "1mb"
            },
            {
              "type": "anyComponentStyle",
              "maximumWarning": "2kb",
              "maximumError": "4kb"
            }
          ],
          "fileReplacements": [
            {
              "replace": "apps/host/src/environments/environment.ts",
              "with": "apps/host/src/environments/environment.prod.ts"
            }
          ],
          "outputHashing": "all",
          "customWebpackConfig": {
            "path": "apps/host/webpack.prod.config.js"
          }
        },
        "development": {
          "buildOptimizer": false,
          "optimization": false,
          "vendorChunk": true,
          "extractLicenses": false,
          "sourceMap": true,
          "namedChunks": true
        },
        "hmr": {
          "buildOptimizer": false,
          "optimization": false,
          "vendorChunk": true,
          "extractLicenses": false,
          "sourceMap": true,
          "namedChunks": true
        }
      },
      "defaultConfiguration": "production"
    },
    "serve": {
      "executor": "@nrwl/angular:module-federation-dev-server",
      "configurations": {
        "production": {
          "browserTarget": "host:build:production"
        },
        "development": {
          "browserTarget": "host:build:development"
        },
        "hmr": {
          "browserTarget": "host:build:hmr"
        }
      },
      "defaultConfiguration": "development",
      "options": {
        "port": 4200,
        "publicHost": "http://localhost:4200"
      }
    },
    "extract-i18n": {
      "executor": "@angular-devkit/build-angular:extract-i18n",
      "options": {
        "browserTarget": "host:build"
      }
    },
    "lint": {
      "executor": "@nrwl/linter:eslint",
      "options": {
        "lintFilePatterns": ["apps/host/**/*.ts", "apps/host/**/*.html"]
      }
    },
    "test": {
      "executor": "@nrwl/jest:jest",
      "outputs": ["coverage/apps/host"],
      "options": {
        "jestConfig": "apps/host/jest.config.ts",
        "passWithNoTests": true
      }
    }
  },
  "tags": [],
  "implicitDependencies": ["cart", "shop", "about"]
}

```

**Comment by Coly010** [comment]
Hey, thanks for reporting this!

Do each of your remotes have a `hmr` configuration?

If not, they will.

The reason behind this is:
- When you build your host + remotes, you want to ensure you're not mix and matching the configuration that each are being built with. i.e. you do not want to load a development remote app into a production host app.

So when you run `nx serve host --configuration=hmr` we then attempt to run `nx serve remote --configuration=hmr` to ensure maximum consistency across the stack.

**Comment by timtos** [comment]
@Coly010 Thank you very much for you detailed explanation! I added the hmr configuration everywhere and now it is working like a charm. :)

**Comment by johngrimsey** [comment]
Would recommend adding project name to the error message if you can, this would potentially save time trying to hunt down the source of the problem to those that haven't encountered it yet and aren't sure which part of their config is responsible for the error 👍
