### ISSUE TITLE
@nrwl/jest coveragePathIgnorePatterns property on global jest.config.ts doesn't work

### ISSUE THREAD

**Issue by davidediak** [nrwl/nx#10477]
## Current Behavior
if you specify a file within the coveragePathIgnorePatterns property in global config file, that file will still be "covered" by the coverage.
If I specify the file within the jest.config file at "lib" level the property actually works and file get ignored from the coverage.
## Expected Behavior
coveragePathIgnorePatterns from the global config file should be considered.
I
## Steps to Reproduce

- in the global config add   coveragePathIgnorePatterns: [file.ts] // it doesn't matter if it's nested in a lib folder
- run test with coverage, file will still be included in the coverage
- in the config at lib level add coveragePathIgnorePatterns: [file.ts]
- run test with coverage, file will be excluded in the coverage

### Environment
```
  Node : 16.15.0
  OS   : linux x64
  npm  : 8.5.5
  
  nx : 13.4.4
  @nrwl/angular : 13.4.4
  @nrwl/cli : 13.4.4
  @nrwl/cypress : 13.4.4
  @nrwl/devkit : 13.4.4
  @nrwl/eslint-plugin-nx : 13.4.4
  @nrwl/express : undefined
  @nrwl/jest : 13.4.4
  @nrwl/linter : 13.4.4
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.4
  @nrwl/web : undefined
  @nrwl/workspace : 13.4.4
  @nrwl/storybook : 13.4.4
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
  	 @angular/animations: 13.1.1
  	 @angular/cdk: 13.1.1
  	 @angular/common: 13.1.1
  	 @angular/compiler: 13.1.1
  	 @angular/core: 13.1.1
  	 @angular/forms: 13.1.1
  	 @angular/platform-browser: 13.1.1
  	 @angular/platform-browser-dynamic: 13.1.1
  	 @angular/router: 13.1.1
  	 @angular/service-worker: 13.1.1
  	 @angular-devkit/build-angular: 13.1.2
  	 @angular/cli: 13.1.2
  	 @angular/compiler-cli: 13.1.1
  	 @angular/language-service: 13.1.1
  	 @storybook/angular: 6.5.0-alpha.12

```

**Comment by zfowles** [comment]
Has this been looked into at all? Having same issue.

**Comment by barbados-clemens** [comment]
Not yet, but it could be related to pathing as the root directory will be set as the project root (where the jest config is located). 

also, try adding it to the root level jest preset as a shot in the dark?

**Comment by barbados-clemens** [comment]
try attempted using the jest.preset.js and it works.
See this [commit for changes working](https://github.com/barbados-clemens/testing-validation-bench/commit/352f4663cebdbb1d0448463ea786283da51c7b94)

[instructions in the README](https://github.com/barbados-clemens/testing-validation-bench#globally-use-coveragepathignorepatterns)
