### ISSUE TITLE
Better errors than `Unexpected token } in JSON at position 84`

### ISSUE THREAD

**Issue by kirjs** [nrwl/nx#1047]
## Current Behavior
When I run `ng g lib ...`,  I get an error:`Unexpected token } in JSON at position 84`
It's unclear which `.json` file is broken, and I have to look at every json file in the project to find a fix.

## Expected Behavior
I'd like the error message to look more like
`error parsing tsconfig.json: Unexpected token } in JSON at position 84`

### Steps to Reproduce
Break `tsconfig.json` and try to generate something .

**Comment by codestitch** [comment]
I know @FrozenPandaz  closed this. but I tried to get the latest update v7.7.2 but I'm still getting this error.
