### ISSUE TITLE
React Storybook Configuration is incredibly slow for HMR

### ISSUE THREAD

**Issue by WonderPanda** [nrwl/nx#10473]
Apologies if this is the wrong place to post this. I'm not sure if its a webpack issues, a storybook issue, an NX issue or some combination of the above. We're massive fans of NX and as much as possible are trying to stick to the official @nrwl generator best practices but the current Storybook experience has been a bit of a barrier for adoption with people doing primarily React component development

## Current Behavior
When setting up a Storybook configuration for a react library using the `@nrwl/react` generators, the Developer XP for HMR is slow and bordering on unusable in some contexts

## Expected Behavior
Storybook HMR should be able to reflect changes to components quickly. When setting up Storybook manually outside of an NX monorepo HMR can reflect changes almost instantaneously. Its not clear if there's an 

## Steps to Reproduce
I've created a [minimal reproduction repo here](https://github.com/WonderPanda/nx-slow-storybook). The readme contains information about what we're seeing but I'll include it here as well for completeness

This repo demonstrates that the developer experience of using a Storybook configuration for a react library all generated through official @nrwl generators
`@nrwl/react:library` and `@nrwl/react:storybook-configuration` is extremely slow.

Even with an incredibly simple monorepo set up with a single react component library that has a storybook configuration it takes 1-2 full seconds for HMR to kick in and the UI to update.

In our actual project at work where there are a few more libs and apps (2 apps and ~6 libs) the hot reload can take 10-15 seconds which makes it completely unusable. In our example at work however we've scaffolded a brand new React component library similar to the one in the repro that I've linked which only has one component so that part is somewhat comparable

### Steps

1. Install the dependencies by running `yarn`
2. Run the storybook for the component library `yarn nx storybook components` and wait for it to become available
3. Make a change inside `components.tsx` and observe that it takes a very long time for changes to be reflected in the UI

### Notes

It feels like there is something going wrong with the setup here because I've seen in many other projects/setups that Storybook hot reloading should feel nearly instantaneous

Example output:

```
webpack built preview 629e33ca826bf35dc419 in 1504ms
webpack building...
webpack built preview e9f2d5d63a668308e3e0 in 1196ms
webpack building...
webpack built preview c4c4f47821c914339dbc in 1149ms
```

### Environment
We're seeing the same behavior on both Linux and Mac currently

NX report from the minimal repro:
```
Node : 16.15.0
   OS   : linux x64
   yarn : 1.19.0
   
   nx : 14.1.9
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.9
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.9
   @nrwl/eslint-plugin-nx : 14.1.9
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.9
   @nrwl/js : 14.1.9
   @nrwl/linter : 14.1.9
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.1.9
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.9
   @nrwl/web : 14.1.9
   @nrwl/workspace : 14.1.9
   typescript : 4.6.4
```

NX report from our actual project where HMR takes 10-15 seconds to reload for a react library with a single component that doesn't reference any other libs:

```
Node : 16.15.0
   OS   : linux x64
   yarn : 1.19.0
   
   nx : 14.1.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.8
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.5
   @nrwl/js : 14.1.7
   @nrwl/linter : 14.1.5
   @nrwl/nest : 14.1.7
   @nrwl/next : Not Found
   @nrwl/node : 14.1.7
   @nrwl/nx-cloud : 14.0.3
   @nrwl/nx-plugin : 14.1.8
   @nrwl/react : 14.1.5
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.5
   @nrwl/web : 14.1.5
   @nrwl/workspace : 14.1.5
   typescript : 4.3.5
   rxjs : 7.4.0
```

**Comment by bdebon** [comment]
Exactly the same sensation here. On NX 14, storybook for react project is super super slow. Components take 5 to 7s to reflects changes which remove a lot of Storybook convenience... I have no clue where it could come from.
We have this warning message but not sure it comes from here:
```
react-dom.development.js:86 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
```
