### ISSUE TITLE
Nx thinks project not builded when using custom build executor

### ISSUE THREAD

**Issue by ssslambda** [nrwl/nx#10487]
I have Angular libs and i have custom executors on target build for them

## Current Behavior

When i run `nx build my-custom-build-lib1` it builds (and also runs `build-angular` which is default `@nrwl/angular:package` builder that i just renamed), but then when i building lib, `my-lib2` for e.g. that depends on `my-custom-build-lib1` it asks me to run `build-angular` on it, nx not even trying to build `my-lib2`, it just asking me to do what i already did in my custom build executor

## Expected Behavior

I expect Nx to understand that `my-custom-build-lib1` what builded already and he should start building `my-lib2` without asking me to build it again with just another command

## Steps to Reproduce
1. Create two libs
2. Make one of them with custom executor to be dependency of another
3. Try to build another with `--with-deps` flag

As you can see below, all difference between `build` and `build-angular` is copying folder from one lib into another, so it builds perfectly as expected

My executor code:
```ts
export default async function runMyLibBuildExecutor(
    options: BuildExecutorSchema,
    context: ExecutorContext,
) {
    const buildResult = await runExecutor(
        {project, target: 'build-angular'},
        options,
        context,
    );

    for await (const res of buildResult) {
        if (!res.success) return res;
    }

    // rootDir is root of nx monorepo
    // distDir is path to the dist/libs/<lib-name>
    // fs === npm/fs-extra
    fs.copySync(
        path.resolve(rootDir, 'libs', 'common', 'src', 'lib', 'static'),
        path.resolve(distDir, 'static'),
    );

    return {
        success: true,
    };
}
```

Angular.json:
```json
                "build": {
                    "builder": "./libs/<lib-name>/src/executors/build:build",
                    "options": {
                        "tsConfig": "libs/<lib-name>/tsconfig.lib.json",
                        "project": "libs/<lib-name>/ng-package.json"
                    },
                    "configurations": {
                        "production": {
                            "tsConfig": "libs/<lib-name>/tsconfig.lib.prod.json"
                        }
                    }
                },
                "build-angular": {
                    "builder": "@nrwl/angular:package",
                    "options": {
                        "tsConfig": "libs/<lib-name>/tsconfig.lib.json",
                        "project": "libs/<lib-name>/ng-package.json"
                    },
                    "configurations": {
                        "production": {
                            "tsConfig": "libs/<lib-name>/tsconfig.lib.prod.json"
                        }
                    }
                },
```

### Failure Logs

> Some of the project my-lib2 dependencies have not been built yet. Please build these libraries before:
> - my-custom-build-lib1
> 
> Try: nx run my-custom-build-lib1:build-angular --with-deps

### Environment
  Node : 16.13.0
  OS   : darwin x64
  npm  : 8.5.5
  
  nx : Not Found
  @nrwl/angular : 11.6.3
  @nrwl/cli : 11.6.3
  @nrwl/cypress : 11.6.3
  @nrwl/devkit : 11.6.3
  @nrwl/eslint-plugin-nx : 11.6.3
  @nrwl/express : Not Found
  @nrwl/jest : 11.6.3
  @nrwl/linter : 11.6.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.6.3
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.6.3
  @nrwl/web : Not Found
  @nrwl/workspace : 11.6.3
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.6

**Comment by AgentEnder** [comment]
Hey @ssslambda! A lot of this has changed from 11.6 to now, as we have a new way of handling dependency builds. Is there anyway that you can check if this still occurs in latest?
