### ISSUE TITLE
Migrating leads to wrong @storybook/addon-notes version

### ISSUE THREAD

**Issue by timtos** [nrwl/nx#10484]
## Current Behavior
Migrating to nx version 14.1.9 bumps @storybook/addon-notes version to 6.4.12 which does not exist. The latest package version available is still 5.3.21.

## Expected Behavior
The migration process should stick to version 5.3.21.

## Steps to Reproduce
Migrate to the latest version and check the package.json.
Running yarn will let you choose a version as the "migrated version" does not exist.

### Environment
Node : 16.13.2
OS : win32 x64
yarn : 1.22.5

**Comment by mandarini** [comment]
Ooops!!! Fix on it's way!! Thanks for reporting @timtos !

**Comment by mandarini** [comment]
Quick question. Which version did you migrate FROM? @timtos

**Comment by timtos** [comment]
@mandarini Probably too late, but I still want to answer: The version was 13.8.8. Thank you for the fix! 👍
