### ISSUE TITLE
Webpack build does not remove dead code with SWC as compiler in default webpack config

### ISSUE THREAD

**Issue by espenja** [nrwl/nx#10507]
## Current Behavior
Importing a `react-icon` causes the entire module to be included in the resulting webpack bundle, not just the one icon.
```ts
// packages/bundle-test/src/app/app.tsx
import { MdPerson } from "react-icons/md"

export function App() {
  return (
    <MdPerson size={128} />
  );
}
export default App;
```

Running webpack analyze shows the file size of bundled output is excessive
![image](https://user-images.githubusercontent.com/1131968/170880333-9755b21c-6e7a-452a-8f34-532a3d00c3fe.png)

Inspecting `dist/main.hash.esm.js` we can see the entire module has been imported.

## Expected Behavior

Importing a react-icon should not include the entire module from `react-icons/md`, only the imported icon.
Inspecting `dist/main.hash.esm.js` should show that only the one icon has been imported.
In the reproducible repo below, I have been able to produce a fix that outputs this analysis, significantly reducing the size footprint:

![image](https://user-images.githubusercontent.com/1131968/170881590-e5630e8f-ca29-454f-b16b-5ba84ae19ebf.png)

## Steps to Reproduce

A minimal repo has been made by @rudfoss and a branch attempting to fix this has been made by me @espenja over at https://github.com/rudfoss/nx-bundling-issue/tree/minimizer-fix

Editing the code in `./webpack.custom.ts` to the below code, or just using the default `"@nrwl/react/plugins/webpack"` as `webpackConfig`, reproduces the issue reported in this ticket:
```ts
//./webpack.custom.ts
/* eslint-disable @typescript-eslint/no-var-requires */
import { Configuration, ids } from "webpack"
const getWebpackConfig = require("@nrwl/react/plugins/webpack.js")

module.exports = (config: Configuration) => {
    getWebpackConfig(config)

    // if (config.optimization) {
    //     delete config.optimization.minimizer
    // }

    // if (config.plugins) {
    //     config.plugins.push(new ids.HashedModuleIdsPlugin({
    //         hashFunction: 'sha256',
    //         hashDigest: 'hex',
    //         hashDigestLength: 4,
    //     }))
    // }
    return config
};
```

By default from `nx`, `config.optimization.minimizer` contains an instance of `new webpack.ids.HashedModuleIdsPlugin()`
By removing the default `config.optimization.minimizer` setting, the bundle produces expected results.
Therefore I am left wondering if the `HashedModuleIdsPlugin` is inserted at the wrong place by `nx`?
Should it not instead have been inserted in `config.plugins` as per webpacks own test files found here https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/test/configCases/hash-length/hashed-module-ids/webpack.config.js ?

Enabling my fix again to the below code should produce a significantly lower size footprint in the webpack output.
```ts
//./webpack.custom.ts
/* eslint-disable @typescript-eslint/no-var-requires */
import { Configuration, ids } from "webpack"
const getWebpackConfig = require("@nrwl/react/plugins/webpack.js")

module.exports = (config: Configuration) => {
    getWebpackConfig(config)

    if (config.optimization) {
        delete config.optimization.minimizer
    }

    if (config.plugins) {
        config.plugins.push(new ids.HashedModuleIdsPlugin({
            hashFunction: 'sha256',
            hashDigest: 'hex',
            hashDigestLength: 4,
        }))
    }
    return config
};

```

We are using `swc` as compiler.

### Failure Logs

N/A

### Environment

Node : 16.14.2
   OS   : win32 x64
   npm  : 8.5.0

   nx : 14.1.9-beta.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.9-beta.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.9-beta.1
   @nrwl/eslint-plugin-nx : 14.1.9-beta.1
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.9-beta.1
   @nrwl/js : 14.1.9-beta.1
   @nrwl/linter : 14.1.9-beta.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.1.9-beta.1
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.9-beta.1
   @nrwl/web : 14.1.9-beta.1
   @nrwl/workspace : 14.1.9-beta.1
   typescript : 4.6.4
   ---------------------------------------
   Community plugins:

**Comment by rudfoss** [comment]
Hi, this does not seem to have been fixed. I have the same problem in version `14.6.5`. And the workaround provided (deleting `optimization.minimizer` solves the issue)

```
"@nrwl/cli": "14.6.5",
"@nrwl/eslint-plugin-nx": "14.6.5",
"@nrwl/jest": "14.6.5",
"@nrwl/js": "14.6.5",
"@nrwl/linter": "14.6.5",
"@nrwl/react": "^14.6.5",
"@nrwl/web": "14.6.5",
"@nrwl/workspace": "14.6.5",
"@swc/cli": "~0.1.55",
"@swc/core": "^1.2.173",
"@swc/jest": "0.2.20",
```

**Comment by espenja** [comment]
As @rudfoss says, upgrading to the latest version does not solve this problem. I'm not even sure why this issue was immediately closed in the first place without a discussion. The effects are still visible in the latest version with the provided reproduce repository and configuration.

I have migrated our nx workspace to the latest version and updated the repository and branch: [https://github.com/rudfoss/nx-bundling-issue/tree/minimizer-fix](https://github.com/rudfoss/nx-bundling-issue/tree/minimizer-fix)

_Something that I should have highlighted **more** in the original post is that we are using **SWC** as our compiler._

With this `project.json`, the build that is produced is bloated and contains the entire contents of `react-icons`'s MD package, despite only including one single icon in the code.

```json
{
  "$schema": "..\\..\\node_modules\\nx\\schemas\\project-schema.json",
  "sourceRoot": "packages/bundle-test/src",
  "projectType": "application",
  "targets": {
    "build": {
      "executor": "@nrwl/webpack:webpack",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "compiler": "swc",
        "outputPath": "dist/packages/bundle-test",
        "index": "packages/bundle-test/src/index.html",
        "baseHref": "/",
        "main": "packages/bundle-test/src/main.tsx",
        "polyfills": "packages/bundle-test/src/polyfills.ts",
        "tsConfig": "packages/bundle-test/tsconfig.app.json",
        "assets": [
          "packages/bundle-test/src/favicon.ico",
          "packages/bundle-test/src/assets"
        ],
        "styles": [],
        "scripts": [],
        "progress": true,
        "statsJson": true,
        "verbose": true,
        "skip-nx-cache": true
      },
      "configurations": {
        "development": {
          "extractLicenses": false,
          "optimization": false,
          "sourceMap": true,
          "vendorChunk": true
        },
        "production": {
          "fileReplacements": [
            {
              "replace": "packages/bundle-test/src/environments/environment.ts",
              "with": "packages/bundle-test/src/environments/environment.prod.ts"
            }
          ],
          "optimization": true,
          "outputHashing": "all",
          "sourceMap": true,
          "namedChunks": false,
          "extractLicenses": true,
          "vendorChunk": false
        }
      }
    },
    "serve": {
      "executor": "@nrwl/webpack:dev-server",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "bundle-test:build",
        "hmr": true
      },
      "configurations": {
        "development": {
          "buildTarget": "bundle-test:build:development"
        },
        "production": {
          "buildTarget": "bundle-test:build:production",
          "hmr": false
        }
      }
    },
    "lint": {
      "executor": "@nrwl/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["packages/bundle-test/**/*.{ts,tsx,js,jsx}"]
      }
    },
    "test": {
      "executor": "@nrwl/jest:jest",
      "outputs": ["coverage/packages/bundle-test"],
      "options": {
        "jestConfig": "packages/bundle-test/jest.config.ts",
        "passWithNoTests": true
      }
    }
  },
  "tags": []
}
```

Output of `npx source-map-explorer .\dist\packages\bundle-test\main.*.js --no-border-checks` after running `nx build`:

![image](https://user-images.githubusercontent.com/1131968/191124462-6eba81a2-7d28-49ef-8f7f-d71ca801a7d0.png)

From inspecting the produced webpack config, it seems no minifier at all is applied with this configuration. These are the only values contained in `webpackConfig.optimization.minimizer` during the `webpack.custom.ts` merge function logged with `console.dir`:

```javascript
[
  HashedModuleIdsPlugin {
    options: {
      context: null,
      hashFunction: 'md4',
      hashDigest: 'base64',
      hashDigestLength: 4
    }
  },
  CssMinimizerPlugin {
    options: {
      test: /\.(?:css|scss|sass|less|styl)$/,
      warningsFilter: [Function: warningsFilter],
      parallel: true,
      include: undefined,
      exclude: undefined,
      minimizer: [Object]
    }
  }
]
```

On a tangent, I don't even know what `HashedModuleIdsPlugin` is doing in the minimizer object, as it's not a minimizer, but a plugin, and should be placed in the `webpackConfig.plugins` object according to the documentation [https://webpack.js.org/plugins/hashed-module-ids-plugin/](https://webpack.js.org/plugins/hashed-module-ids-plugin/). I don't have in-depth knowledge about this, so I could of course be wrong.

## Fixing the issue with a custom config

Applying either of these custom webpack configs fixes the minification issues with **SWC** as compiler:

```javascript
// webpack.custom.1.ts
import { Configuration } from 'webpack';
import TerserPlugin from 'terser-webpack-plugin';
const getWebpackConfig = require('@nrwl/react/plugins/webpack.js');

module.exports = (config: Configuration) => {
  getWebpackConfig(config);
  config.optimization?.minimizer?.push(
    new TerserPlugin({
      minify: TerserPlugin.swcMinify,
      terserOptions: {},
    })
  );
  return config;
};
```

```javascript
// webpack.custom.2.ts
import { Configuration } from 'webpack';
import TerserPlugin from 'terser-webpack-plugin';
const getWebpackConfig = require('@nrwl/react/plugins/webpack.js');

module.exports = (config: Configuration) => {
  getWebpackConfig(config);
  delete config.optimization?.minimizer;
  return config;
};
```

After applying either of these, the output of `npx source-map-explorer .\dist\packages\bundle-test\main.*.js --no-border-checks` looks like this:

![image](https://user-images.githubusercontent.com/1131968/191124601-9b8e1a41-6e9e-4263-b8cc-ff48d8bb81be.png)

## Looking around the nx code base

The only place in the distributed code I can find any mention of `TerserPlugin` is within `node_modules\@nrwl\webpack\src\utils\config.js`, but it's guarded inside this if-clause that specifically says to use `TerserPlugin` when **SWC** is **NOT** the compiler:

```javascript
// node_modules\@nrwl\webpack\src\utils\config.js @L118
if (options.compiler !== 'swc' && internalOptions.isScriptOptimizeOn) {
```

Again, I don't have in-depth knownledge of the nx codebase, but it seems odd that the `webpackConfig.optimization.minimizer` object doesn't contain an actual js/ts minimizer, and/or that the `TerserPlugin` is disabled when having **SWC** as the compiler.

Inverting that logic, _without any other changes or custom webpack config_, produces a correctly minified bundle. Running `npx source-map-explorer .\dist\packages\bundle-test\main.*.js --no-border-checks` after this "fix":

```javascript
if (options.compiler === 'swc' && internalOptions.isScriptOptimizeOn) {
```

![image](https://user-images.githubusercontent.com/1131968/191126428-3c7e254f-dab2-44c7-a503-c3c6069b6f0f.png)

**Comment by espenja** [comment]
@AgentEnder Would it be possible to re-open this issue and take another look? I have provided more information and an updated reproduction repository after migrating to the newest version of `nx` and verifying that it still does not work. This is specifically for `swc` as compiler.

**Comment by montella1507** [comment]
Have same issue.

**Comment by KraKeN-47** [comment]
![image](https://user-images.githubusercontent.com/51761760/195675395-42f7fbc8-1912-4534-9fe1-3f7e3ab02421.png)
![image](https://user-images.githubusercontent.com/51761760/195675482-1e016d30-6c8c-46f8-a198-8849a2d907ff.png)

**Comment by KraKeN-47** [comment]
As of `nx v14.8.4` , newly built app bundle size differs very much, both examples ran with default `serve:production` scripts and analyzed with `webpack-bundle-analyzer`:

### Babel: 
![image](https://user-images.githubusercontent.com/51761760/195675990-3ba90818-64e1-4f5b-91e2-7dabfb3ecfb8.png)

### Swc:
![image](https://user-images.githubusercontent.com/51761760/195676116-ad2e6e87-1681-4963-95af-1a1ae6e99575.png)
