### ISSUE TITLE
@nrwl/node:webpack does not use tsConfig option

### ISSUE THREAD

**Issue by koyedele** [nrwl/nx#10535]
## Current Behavior

The `node:webpack` executor always [resolves the root tsConfig file](https://github.com/nrwl/nx/blob/b35e3836c2f3d45decbeb071efd26f54923e802b/packages/node/src/executors/webpack/webpack.impl.ts#L48-L50) and not the value specified in the options (like [`web:webpack` does](https://github.com/nrwl/nx/blob/b35e3836c2f3d45decbeb071efd26f54923e802b/packages/web/src/executors/webpack/webpack.impl.ts#L93-L96)). My app tsConfig file has compiler option `module: "commonjs"` while the root has `module: "esnext"`. 

If I provide a custom webpack config with the `webpackConfig` option set to a `.ts` file, the build fails with error `Cannot use import statement outside a module`. The error comes from trying to parse the custom `webpackConfig` file.

## Expected Behavior

The executor should respect the provided tsConfig option and default to the root tsConfig otherwise.

## Steps to Reproduce

Github repo: https://github.com/koyedele/nx-node-webpack-issue

Run `nx run test-app:build`

### Failure Logs

```plain
> nx run test-app:build

Cannot use import statement outside a module

 ————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for project test-app (1s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
 
error Command failed with exit code 1.
```

### Environment

```plain

   Node : 17.8.0
   OS   : darwin arm64
   yarn : 1.22.18
   
   nx : 14.0.5
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.0.5
   @nrwl/eslint-plugin-nx : 14.0.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.5
   @nrwl/js : 14.0.5
   @nrwl/linter : 14.0.5
   @nrwl/nest : 14.0.5
   @nrwl/next : Not Found
   @nrwl/node : 14.0.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.0.5
   typescript : 4.6.4
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:

```

**Comment by farazsa88** [comment]
I solved it by adding `"ts-node": { "compilerOptions": { "module": "CommonJS" } }` to root `tsconfig.json`.
Since webpack itself is executed by `ts-node`, this way we can override options for the executor only
