### ISSUE TITLE
Error: ENOENT: no such file or directory, open '~/tools/tsconfig.tools.json'

### ISSUE THREAD

**Issue by artalar** [nrwl/nx#10555]
Custom generator fails with following error:

## Current Behavior

```
> npx nx workspace-generator new-package some
nx workspace-generator [name]

Runs a workspace generator from the tools/generators directory

Positionals:
  name  The name of your generator                                                                                [string] [required]

Options:
  --help             Show help                                                                                              [boolean]
  --version          Show version number                                                                                    [boolean]
  --list-generators  List the available workspace-generators                                                                [boolean]

Find more information and examples at https://nx.dev/cli/workspace-generator

Error: ENOENT: no such file or directory, open '/workspace/reatom/tools/tsconfig.tools.json'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at readJsonFile (/workspace/reatom/node_modules/nx/src/utils/fileutils.js:21:43)
    at toolsTsConfig (/workspace/reatom/node_modules/nx/src/command-line/workspace-generators.js:93:41)
    at getToolsOutDir (/workspace/reatom/node_modules/nx/src/command-line/workspace-generators.js:49:20)
    at compileTools (/workspace/reatom/node_modules/nx/src/command-line/workspace-generators.js:40:25)
    at Object.<anonymous> (/workspace/reatom/node_modules/nx/src/command-line/workspace-generators.js:26:24)
    at Generator.next (<anonymous>)
    at /workspace/reatom/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/workspace/reatom/tools/tsconfig.tools.json'
}
```

## Expected Behavior

A new folder and files generated.

## Steps to Reproduce

1. Go to the repo: https://github.com/artalar/reatom/tree/233ac496bb20bd0973479547142109a0453bda3d
2. Clone it or open by gitpod.io
3. `npm i`
4. `npx nx workspace-generator new-package some`

### Environment

Personal MacBook Air:

```
Node : 16.13.1
OS   : darwin arm64
npm  : 8.1.2

nx : 14.1.9
@nrwl/angular : Not Found
@nrwl/cypress : Not Found
@nrwl/detox : Not Found
@nrwl/devkit : 14.1.9
@nrwl/eslint-plugin-nx : Not Found
@nrwl/express : Not Found
@nrwl/jest : 14.1.9
@nrwl/js : Not Found
@nrwl/linter : 14.1.9
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/nx-cloud : Not Found
@nrwl/nx-plugin : Not Found
@nrwl/react : Not Found
@nrwl/react-native : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : Not Found
@nrwl/web : Not Found
@nrwl/workspace : 14.1.9
typescript : 4.6.4
---------------------------------------
Community plugins:
  @ngrx/store: 13.2.0
```

Gitpod instance:
```
   Node : 16.15.0
   OS   : linux x64
   npm  : 8.5.5
   
   nx : 14.1.9
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.9
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.9
   @nrwl/js : Not Found
   @nrwl/linter : 14.1.9
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.9
   typescript : 4.6.4
   ---------------------------------------
   Community plugins:
         @ngrx/store: 13.2.0
```

**Comment by artalar** [comment]
cc #4221

**Comment by Kmarutsi** [comment]
having the same issue :

nx workspace-generator [name]

Runs a workspace generator from the tools/generators directory

Positionals:
  name  The name of your generator                                                                                                              [string] [required]

Options:
  --help             Show help                                                                                                                            [boolean]
  --version          Show version number                                                                                                                  [boolean]
  --list-generators  List the available workspace-generators                                                                                              [boolean]

Find more information and examples at https://nx.dev/cli/workspace-generator

Error: ENOENT: no such file or directory, open '/Users/kudzaimarutsi/econet-projects/ai-di-project/tools/tsconfig.tools.json'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at readJsonFile (/Users/kudzaimarutsi/econet-projects/ai-di-project/node_modules/nx/src/utils/fileutils.js:18:43)
    at toolsTsConfig (/Users/kudzaimarutsi/econet-projects/ai-di-project/node_modules/nx/src/command-line/workspace-generators.js:93:41)
    at getToolsOutDir (/Users/kudzaimarutsi/econet-projects/ai-di-project/node_modules/nx/src/command-line/workspace-generators.js:49:20)
    at compileTools (/Users/kudzaimarutsi/econet-projects/ai-di-project/node_modules/nx/src/command-line/workspace-generators.js:40:25)
    at Object.<anonymous> (/Users/kudzaimarutsi/econet-projects/ai-di-project/node_modules/nx/src/command-line/workspace-generators.js:26:24)
    at Generator.next (<anonymous>)
    at /Users/kudzaimarutsi/econet-projects/ai-di-project/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/kudzaimarutsi/econet-projects/ai-di-project/tools/tsconfig.tools.json'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The terminal process "/bin/zsh '-c', 'yarn nx workspace-generator feature test --no-interactive --dry-run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

**Comment by artalar** [comment]
I'm trying to fix it, what does that even mean???

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/27290320/178162159-496612f9-9013-4986-9b09-65d1a11766d3.png">

**Comment by dan-cooke** [comment]
Not sure why the default generator template, does not include a tsconfig.json - but you can find an example `tsconfig.tools.json` on their  examples repo.


https://github.com/nrwl/nx-examples/blob/master/tools/tsconfig.tools.json

```
{
  "extends": "../tsconfig.base.json",
  "compilerOptions": {
    "outDir": "../dist/out-tsc/tools",
    "rootDir": ".",
    "module": "commonjs",
    "target": "es5",
    "esModuleInterop": true,
    "types": ["node"]
  },
  "include": ["**/*.ts"]
}

```

**Comment by pmrotule** [comment]
> I'm trying to fix it, what does that even mean???
> 
> <img alt="image" width="1060" src="https://user-images.githubusercontent.com/27290320/178162159-496612f9-9013-4986-9b09-65d1a11766d3.png">

I'm also running into the same strange type errors after adding a `tsconfig.tools.json` inside the `tools` directory. Anyone is able to help here?

**Comment by dan-cooke** [comment]
@pmrotule see my reply.

**Comment by pmrotule** [comment]
@dan-cooke Oh now I understand where I got confused, sorry. I'm creating a generator to create a new package and somehow I thought this `tsconfig` was the one copied to the new package (which doesn't make sense now that I think about it). So now that I used the exact same config used in the example repo, it worked! Thanks for helping out 🙏 

I removed the `extends` property so I ended up with the following config:

**tools/tsconfig.tools.json**
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "outDir": "../dist/out-tsc/tools",
    "rootDir": ".",
    "noUnusedLocals": true,
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "types": ["node"],
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2017", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": "."
  },
  "exclude": ["node_modules", "tmp"],
  "include": ["**/*.ts"]
}
```

This `tsconfig.tools.json` should definitely be added when running `nx generate @nrwl/workspace:workspace-generator my-generator` to avoid confusion.

**Comment by mwjaco** [comment]
> I removed the extends property so I ended up with the following config:
> 
> tools/tsconfig.tools.json
> 
> {
>   "compileOnSave": false,
>   "compilerOptions": {
>     "module": "commonjs",
>     "target": "es5",
>     "outDir": "../dist/out-tsc/tools",
>     "rootDir": ".",
>     "noUnusedLocals": true,
>     "sourceMap": true,
>     "declaration": false,
>     "moduleResolution": "node",
>     "emitDecoratorMetadata": true,
>     "experimentalDecorators": true,
>     "importHelpers": true,
>     "types": ["node"],
>     "typeRoots": ["node_modules/@types"],
>     "lib": ["es2017", "dom"],
>     "skipLibCheck": true,
>     "skipDefaultLibCheck": true,
>     "baseUrl": "."
>   },
>   "exclude": ["node_modules", "tmp"],
>   "include": ["**/*.ts"]
> }
Thanks @pmrotule. Your snippet unblocked me.

**Comment by artalar** [comment]
=\
