### ISSUE TITLE
When adding storybook to a NX project it says: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by JosepSalvat** [nrwl/nx#10566]
## Steps to Reproduce
1. First `yarn add --dev @nrwl/storybook`
2. nx g @nrwl/react:storybook-configuration myProjectName
3. The error appears and can't continue

### Failure Logs
✔ Configure a cypress e2e app to run against the storybook instance? (Y/n) · true

✔ Automatically generate *.stories.ts files for components declared in this project? (Y/n) · true

✔ Automatically generate *.spec.ts files in the cypress e2e app generated by the cypress-configure generator? (Y/n) · true

adding .storybook folder to the root directory - 
     based on the Storybook version installed (v6), we'll bootstrap a scaffold for that particular version.
adding .storybook folder to app - using Storybook version 6
**Cannot convert undefined or null to object**
### Environment
Working on local atm. ReactJS v17

   nx : 13.4.6
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.3
  @nrwl/cypress : 13.4.3
  @nrwl/devkit : 13.4.3
  @nrwl/eslint-plugin-nx : 13.4.3
  @nrwl/express : undefined
  @nrwl/jest : 13.4.3
  @nrwl/linter : 13.4.3
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : 13.0.2
  @nrwl/react : 13.4.3
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.3
  @nrwl/web : 13.4.3
  @nrwl/workspace : 13.4.3
  @nrwl/storybook : 14.1.9
  @nrwl/gatsby : undefined
  typescript : 4.6.3
  rxjs : 6.5.5
  
  ---------------------------------------
  Community plugins:
  	 @nrwl/js: 13.4.3

**Comment by mandarini** [comment]
Hi there! Thanks for filing an issue! I see that your versions of `@nrwl/storybook` and the rest of the `@nrwl/*` packages are not aligned. Can you please make sure all your `@nrwl/*` packages are on the same version?

**Comment by mandarini** [comment]
Please either migrate to the latest version of Nx, or just install the version of `@nrwl/storybook` that all other `@nrwl/*` packages are on: `yarn add --dev @nrwl/storybook@13.4.3`

**Comment by mandarini** [comment]
I will be closing this, feel free to reopen if it persists after you follow the steps I suggested! Thanks again!!
