### ISSUE TITLE
print-affected not working when project.json or index.html file changed

### ISSUE THREAD

**Issue by Genesys-AlexW** [nrwl/nx#10563]
## Current Behavior
When running `npx nx print-affected --type=app --base={your base} --head=HEAD --select=projects`, I am not seeing the affected projects. The affected project is an angular application (Project A). Current change in Project A is an index.html change and a project.json change.

## Expected Behavior
Expected to see Project A in the `print-affected` print out.

### Environment

Node : 16.14.0
 OS   : darwin x64
 npm  : 7.10.0

 nx : 13.10.2
 @nrwl/angular : 13.10.2
 @nrwl/cypress : 13.10.2
 @nrwl/detox : Not Found
 @nrwl/devkit : 13.10.2
 @nrwl/eslint-plugin-nx : 13.10.2
 @nrwl/express : Not Found
 @nrwl/jest : 13.10.2
 @nrwl/js : 13.10.2
 @nrwl/linter : 13.10.2
 @nrwl/nest : Not Found
 @nrwl/next : Not Found
 @nrwl/node : Not Found
 @nrwl/nx-cloud : Not Found
 @nrwl/nx-plugin : Not Found
 @nrwl/react : 13.10.2
 @nrwl/react-native : Not Found
 @nrwl/schematics : Not Found
 @nrwl/storybook : 13.10.2
 @nrwl/web : 13.10.2
 @nrwl/workspace : 13.10.2
 typescript : 4.6.3
 rxjs : 6.6.7
 ---------------------------------------
 Community plugins:
   @ngrx/component-store: 13.0.1
   @ngrx/effects: 13.0.1
   @ngrx/entity: 13.0.1
   @ngrx/router-store: 13.0.1
   @ngrx/store: 13.0.1
   @compodoc/compodoc: 1.1.19
   @ngrx/schematics: 13.0.1
   @ngrx/store-devtools: 13.0.1

**Comment by Genesys-AlexW** [comment]
Any updates on this?

**Comment by FrozenPandaz** [comment]
I tried to reproduce this on my clone of `nx-examples` by only making a change to `apps/cart/src/index.html`:

https://github.com/FrozenPandaz/nx-examples/tree/10563

Running the command:
```sh
npx nx print-affected --type=app --base=ff6a4856d3d5337205362d264b681fe849dbf7a0 --head=HEAD --select=projects
```

It correctly prints  `cart`

Can you please provide a repo that exhibits the issue? Please provide the base commit.
