### ISSUE TITLE
Storybook react: import type Unexpected token, expected "from"

### ISSUE THREAD

**Issue by Jordan-Hall** [nrwl/nx#10584]
## Current Behavior
`import type { CSSVars, Theme } from './utils';`

## Expected Behavior
Storybook to compile and run fine

## Steps to Reproduce
Simple react component inside storybook. Make another library that uses import type and export type. 

Import library and it fails

```
libs\theme\src\index.ts: Unexpected token, expected "from" (6:12)

  4 |   themeA11yProps,
  5 | } from "./utils";
> 6 | import type { CSSVars, Theme } from './utils';
    |             ^
  7 |
  8 | export * from './preset';
  9 |
    at instantiate (C:\dev\clients\Portal.Web\node_modules\@babel\parser\lib\index.js:72:32)
    at constructor (C:\dev\clients\Portal.Web\node_modules\@babel\parser\lib\index.js:358:12)
    at Parser.raise (C:\dev\clients\Portal.Web\node_modules\@babel\parser\lib\index.js:3341:19)

```

**Comment by Lusito** [comment]
Hi @Coly010 

I have the same issue. Looks like the same issue as #9372, but I can't fix it with a .babelrc file in the library folder.

Here is the smallest reproduction I could make:
https://github.com/Lusito/nx-import-type-repro

I first thought, it was a Problem with `import type`, but it generally doesn't understand typescript in the library.

What I found out, is that using `"executor": "@nrwl/web:webpack"` fails, but using `"executor": "@nrwl/node:webpack"` works perfectly fine.

**Comment by Coly010** [comment]
Thanks @Lusito  when I’m back in the office on Monday I’ll see if I can fit this on my priority list

**Comment by Jordan-Hall** [comment]
Cheers, sorry i was going to sort a repo out today, so thank you @Lusito  and your a @Coly010  as I promise a client there will have storybook 🤣 and I've been to busy sorting out other things to take a look at how I can resolve this myself sorry

**Comment by Lusito** [comment]
Looking at the node:webpack implementation, it registers ts-node: https://github.com/nrwl/nx/blob/e507d7b4cf9b44fdcfb4657650d1cd34f68458cc/packages/node/src/executors/webpack/webpack.impl.ts#L115

The web:webpack implementation does not register ts-node. I've tried hacking in the registerTsNode into the compiled webpack.impl.js, but it doesn't seem to change anything, so I'm not sure this is the issue.

I guess I'll better wait for monday. Thanks!

**Comment by Jordan-Hall** [comment]
Whats strange is I've been using the storybook vite builder and it still does this.

**Comment by Coly010** [comment]
@Lusito You do not have storybook in your reproduction at all? 

@Jordan-Hall  Can you provide a reproduction of this using Storybook? 

I can then check if the problem is indeed Storybook related or if it's related to something else.

**Comment by Jordan-Hall** [comment]
@Coly010  No repo step anymore. Closing this down looks like its now all working so not sure what the issue is. If i can repo it in a basic setup i'll reopen. Im so sorry

**Comment by Lusito** [comment]
I don't use storybook. It looked like the same issue to me.

@Coly010 did you change anything? Otherwise I don't think my issue is fixed. Should I create a new issue?

**Comment by Lusito** [comment]
ok, done
