### ISSUE TITLE
Use project scoped ESLint cache as default

### ISSUE THREAD

**Issue by minijus** [nrwl/nx#10589]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Today ESLint executor accepts `cacheLocation` and uses it to store ESLint cache. The problem occurs when using `affected` or `run-many` with parallel option. Parallel runs of linter does not support atomic read/write to cache file and overrides cache file that in the end results in non-full cache.

Instead of attempting to store all ESlint cache in single file (for example `./cache/eslint`), it could be stored in multiple files scoped per project (`./cache/eslint/project1`, `./cache/eslint/project2`, ...).

## Motivation
Having possibility to store ESLint cache per project will ensure that ESLint does not override it when ran in parallel.

## Suggested Implementation
Suffix `cacheLocation` with `projectName`:
```ts
options.cacheLocation ? `${options.cacheLocation}/${projectName}`: undefined;
```

**Comment by minijus** [comment]
It would be great to have possibility to set defaults for executors in workspace as presented in #8544 discussion. It would allow to set caching options for all lint executions on workspace.

**Comment by meeroslav** [comment]
Thank you @minijus for reporting this issue and proposing the fix in the PR.

> It would be great to have possibility to set defaults for executors in workspace as presented in https://github.com/nrwl/nx/discussions/8544 discussion. It would allow to set caching options for all lint executions on workspace.

This is a good idea. We had this in discussion already, but I'm not sure why it hasn't been implemented yet. I will add this to my list.
