### ISSUE TITLE
How to use Angular 14 with @nrwl/cli v14.1.9

### ISSUE THREAD

**Issue by its-ratikant** [nrwl/nx#10581]
How to use Angular 14 with @nrwl/cli v14.1.9?
Angular 13.3.0 version it is using instead?

**Comment by Jordan-Hall** [comment]
You can upgrade the packages yourself. It works without any issues.

**Comment by PieterjanDeClippel** [comment]
This is the ´package.json´ for a new angular app created by ´ng new´

```
{
  "name": "eslinttest",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^14.0.0",
    "@angular/common": "^14.0.0",
    "@angular/compiler": "^14.0.0",
    "@angular/core": "^14.0.0",
    "@angular/forms": "^14.0.0",
    "@angular/platform-browser": "^14.0.0",
    "@angular/platform-browser-dynamic": "^14.0.0",
    "@angular/router": "^14.0.0",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.0.0",
    "@angular/cli": "~14.0.0",
    "@angular/compiler-cli": "^14.0.0",
    "@types/jasmine": "~4.0.0",
    "jasmine-core": "~4.1.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.7.2"
  }
}
```

Following packages aren't used anymore by angular 14 apps:

    "@angular-eslint/eslint-plugin": "~13.1.0",
    "@angular-eslint/eslint-plugin-template": "~13.1.0",
    "@angular-eslint/template-parser": "~13.1.0",

So you can simply remove these from the package.json since there's no 14 version

**Comment by daniel-zero** [comment]
> Following packages aren't used anymore by angular 14 apps:
> 
> ```
> "@angular-eslint/eslint-plugin": "~13.1.0",
> "@angular-eslint/eslint-plugin-template": "~13.1.0",
> "@angular-eslint/template-parser": "~13.1.0",
> ```
> 
> So you can simply remove these from the package.json since there's no 14 version

This is not fully correct. Since Angular V12 ESLint is not added by default anymore and you have to add the project by yourself. Take a look at the official docs: https://github.com/angular-eslint/angular-eslint

**Comment by FrozenPandaz** [comment]
Hi all, Nx `14.2.1` has been released and has support for Angular 14. Please use `nx migrate latest` to update your repos. :tada:

If you run into any issues, please open a new comment. :pray:
