### ISSUE TITLE
Add support for Storybook custom builder 

### ISSUE THREAD

**Issue by Jordan-Hall** [nrwl/nx#10585]
Currently storybook requires either webpack or webpack5 set in the `{ core: { builder: '...' } }`

I've been wanting to use more custom builder for plugins without having to fork the whole storybook integration. For example:

```
const rootMain = require('../../../.storybook/main');

module.exports = {
  ...rootMain,

  core: { ...rootMain.core, builder: '@storybook/builder-vite' },

  stories: [
    ...rootMain.stories,
    '../src/lib/**/*.stories.mdx',
    '../src/lib/**/*.stories.@(js|jsx|ts|tsx)',
  ],
  addons: [...rootMain.addons, '@nrwl/react/plugins/storybook'],

  async webpackFinal(config, { configType }) {
    // apply any global webpack configs that might have been specified in .storybook/main.js
    if (rootMain.webpackFinal) {
      config = await rootMain.webpackFinal(config, { configType });
    }

    // add your own webpack tweaks if needed

    return config;
  }
};


```

**Comment by mandarini** [comment]
Hi there @Jordan-Hall ! What happens when you make that change to your `main.js`?

**Comment by Jordan-Hall** [comment]
@mandarini  it says its reverts to webpack 4

**Comment by mandarini** [comment]
Ohhhhhhhhhhhhhhh I know the issue! Ok, will look into this soon. I'm on PTO after PTO these days, but next week it will be my priority! :)

**Comment by mandarini** [comment]
I know the message says so, but does it actually use webpack4, or maybe it does use your `builder-vite` but just says it uses webpack 4?

**Comment by mandarini** [comment]
Perfect!!!! Thanks these answers were super helpful!!! :D :D Just bad messaging, easy to fix!! Thanks @Jordan-Hall !

**Comment by mandarini** [comment]
Note to self: fix messaging and core builder check for Storybook

**Comment by mandarini** [comment]
Hi @Jordan-Hall ! I'm testing this out, right now!

Sooooo, great news!!!

I just tested this! I installed `vite` and `@storybook/builder-vite`. Then, in my React projects's `.storybook/main.js` I changed the builder to this: `builder: '@storybook/builder-vite'`, and I had to install `"@storybook/client-api"` for some reason as well.

Then I just did `nx storybook my-project` and it works like a charm.

![Screenshot 2022-06-09 at 12 40 40 PM](https://user-images.githubusercontent.com/6603745/172817405-ca0c1709-83c5-4ad3-a6ad-c4860668a3f6.png)

I'll push my repo later. But I had to do nothing more, it just works! I just need to remove that webpack4 message, which is disorienting!

Please please let me know if it works for you!
