### ISSUE TITLE
Cannot find module './typescript/compilation' error when running custom schematics

### ISSUE THREAD

**Issue by joewIST** [nrwl/nx#10594]
## Current Behavior
When I run a custom schematic, nx throws the following error:

Cannot find module './typescript/compilation'
Require stack:
- C:\....\node_modules\@nrwl\workspace\src\utilities\typescript.js
.....

## Expected Behavior
The schematic should run as expected and generated the required files.

### Environment
   Node : 14.17.3
   OS   : win32 x64
   yarn : 1.22.10

   nx : 14.1.9
   @nrwl/angular : 14.1.9
   @nrwl/cypress : 14.1.9
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.9
   @nrwl/eslint-plugin-nx : 14.1.9
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.9
   @nrwl/js : 14.1.9
   @nrwl/linter : 14.1.9
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.0.5
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : 8.12.11
   @nrwl/storybook : 13.9.6
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.9
   typescript : 4.6.4
   ---------------------------------------
   Community plugins:
         @ngneat/spectator: 8.3.1
         @ngrx/component-store: 12.5.1
         @ngrx/effects: 12.5.1
         @ngrx/entity: 12.5.1
         @ngrx/router-store: 12.5.1
         @ngrx/store: 12.5.1
         apollo-angular: 2.6.0
         @compodoc/compodoc: 1.1.18
         @ngneat/spectator: 8.3.1
         @ngrx/schematics: 12.5.1
         @ngrx/store-devtools: 12.5.1
         @storybook/angular: 6.5.0
         nx-stylelint: 12.2.0

**Comment by FrozenPandaz** [comment]
You should not have @nrwl/schematics : 8.12.11 anymore. Could you remove that?

If that does not solve the issue, pleas provide a repo that shows the issue to help us debug.

**Comment by joewIST** [comment]
I can't provide a repo right now, but this is the error that is generated:

**Cannot find module './typescript/compilation'
Require stack:
- C:\...\@nrwl\workspace\src\utilities\typescript.js
- C:\...\@nrwl\angular\src\generators\utils\storybook.js
- C:\...\@nrwl\angular\src\generators\component-story\component-story.js
- C:\...\@nrwl\angular\src\generators\component-story\compat.js
- C:\...\@angular-devkit\schematics\tools\export-ref.js
- C:\...\@angular-devkit\schematics\tools\index.js
- C:\...\nx\src\adapter\ngcli-adapter.js
- C:\...\nx\src\command-line\generate.js
- C:\...\nx\src\command-line\workspace-generators.js
- C:\...\nx\src\command-line\nx-commands.js
- C:\...\nx\bin\init-local.js
- C:\...\nx\bin\nx.js
- C:\...\@nrwl\cli\bin\nx.js
**
