### ISSUE TITLE
Cannot find configuration for ... in undefined. Latest version NX, trying to add storybook

### ISSUE THREAD

**Issue by JosepSalvat** [nrwl/nx#10610]
## Current Behavior
npx nx g @nrwl/react:storybook-configuration /libs/ui/components

and it throws this error:

Cannot find configuration for '/libs/ui/components' in undefined.

This command is supposed to create a configuration file isn't it? So why is trying to find a configuration file?

## Expected Behavior
Should work

### Failure Logs
Cannot find configuration for '/libs/ui/components' in undefined.

I've tried ./libs, /libs/ui ... etc

my project is something like

nx.json
package.json
apps
 - app1
 - app2
libs
 - ui
   - components
.
.
.

### Environment

nx : 14.1.9
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.9
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.9
   @nrwl/eslint-plugin-nx : 14.1.9
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.9
   @nrwl/js : 14.1.9
   @nrwl/linter : 14.1.9
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.0.5
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.1.9
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.9
   @nrwl/web : 14.1.9
   @nrwl/workspace : 14.1.9
   typescript : 4.6.3
   ---------------------------------------
   Community plugins:
   	 rxjs: 6.5.5

**Comment by FrozenPandaz** [comment]
The command you are looking for is: `npx nx g @nrwl/react:storybook-configuration ui-components`. You should pass the name of the project rather than the path.

Nonetheless, this is a strange error indeed. We should improve it.

**Comment by rubiagatra** [comment]
I'll take a look

**Comment by rubiagatra** [comment]
I think you can close this @FrozenPandaz, I try to replicate it in the latest version it went fine.

```
pnpm nx g @nrwl/react:storybook-configuration /libs/ui/components

>  NX  Generating @nrwl/react:storybook-configuration

✔ Configure a cypress e2e app to run against the storybook instance? (Y/n) · false
✔ Automatically generate *.stories.ts files for components declared in this project? (Y/n) · true
✔ Automatically generate *.spec.ts files in the Cypress E2E app generated by the cypress-configure generator? (Y/n) · false

 >  NX   Cannot find configuration for '/libs/ui/components' in /workspace.json.

   Pass --verbose to see the stacktrace.
```

**Comment by yongjoo-choi** [comment]
@JosepSalvat Is this issue still unresolved?

**Comment by jardelgoncalves** [comment]
I was able to install the storybook with the following commands.

I installed storybook as the docs recommends:
```
yarn add --dev @nrwl/storybook
```

then I ran the command passing the name of my lib using the `--name` option:
```
yarn nx g @nrwl/react:storybook-configuration --name=ui
```

**Comment by abhisheksharma1123** [comment]
I'm still getting the same error "Cannot find configuration for name in /workspace.json."even with above solution

**Comment by GeuntaBuwono** [comment]
you should connect app first with configuration. 

`nx g @nrwl/storybook:configuration`

[storybook generator docs](https://nx.dev/packages/storybook/generators/configuration)

**Comment by mandarini** [comment]
@GeuntaBuwono you don't need to run the `nx g @nrwl/storybook:configuration` generator first. The steps that @jardelgoncalves followed are correct. If you are using React, React-Native or Angular it's preferable to use directly the `:storybook-configuration` generator of one of these packages, as mentioned in the docs:

![Screenshot 2023-02-14 at 3 29 02 PM](https://user-images.githubusercontent.com/6603745/218752606-59ea71e4-41bb-41da-b8e7-6eb7c2129568.png)

So, correctly, in the React case, here are the docs: https://nx.dev/packages/react/generators/storybook-configuration.

I will close this issue, since it has been fixed! :D

**Comment by dlarroder** [comment]
Hey @mandarini, looks like I'm having the same issue here, I have a [public](https://github.com/dlarroder/nx-nextjs-storybook7) repo you can check out if you don't mind, I followed @jardelgoncalves steps and it still gives the same error.

![Screen Shot 2023-02-15 at 12 52 39 PM](https://user-images.githubusercontent.com/52998821/218934734-5c28829b-512f-41a9-9831-3cbae99c7956.png)
