### ISSUE TITLE
Cannot build publishable libraries

### ISSUE THREAD

**Issue by mdilshan** [nrwl/nx#10627]
## Current Behavior

I have tried to create a library with `@nrwl/react-native` with `--publishable` flag. When I try to run `yarn build lib-name` it throws an error. ( Note: I'm testing the NX for the first time to integrate to a production system )

```
rpt2: options error TS6059: File '/Users/madukadilshan/Desktop/research/stores/libs/sm-ui/jest.config.ts' is not under 'rootDir' '/Users/madukadilshan/Desktop/research/stores/libs/sm-ui/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Root file specified for compilation
  index.js 95 Bytes
Error during bundle: Error: The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../../../../libs/sm-ui/jest.config.d.ts".
Bundle failed: sm-ui
```

## Expected Behavior

It should out put a publishable package to dist folder like it said in [here](https://blog.nrwl.io/publishing-react-libraries-made-easy-d5b3d013deba)

## Steps to Reproduce

1. Create a workspace with a sample `react` project. ` npx create-nx-workspace@latest stores --preset=react `
2. `cd` into the workspace
3. Add the rn plugin. `yarn add @nrwl/react-native`
4. Add the library. `npx nx g @nrwl/react-native:lib sm-ui --publishable --importPath=@smartlife/ui2`
5. Export some dummy component from `/lib/sm-ui/src/index.ts`
6. Run `yarn build sm-ui`

At this point it will throw an error. Then I tried to add a library with a core plugin `@nrwl/react`

7. Run `npx nx g @nrwl/react:lib sm-ui-web --publishable --importPath=@smartlife/ui3`
8. Run `yarn build sm-ui-web`

This time i get another error,
```
Cannot find project 'sm-ui-web'
```
The project with the issue can be found [here](https://github.com/mdilshan/nrwl-nx-issue)

### Failure Logs

1. Error with react-native library
![Screenshot 2022-06-08 at 07 47 25](https://user-images.githubusercontent.com/47513639/172517037-8adf79b0-509c-4ef8-957c-c809314244e9.png)

2. Error with react library which created after react-native library
![Screenshot 2022-06-08 at 08 08 35](https://user-images.githubusercontent.com/47513639/172519337-9254ad67-3942-40f5-92c2-85d939caf28c.png)

### Environment
```
Node : 14.17.6
   OS   : darwin x64
   yarn : 1.22.11
   
   nx : 14.2.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.2.1
   @nrwl/detox : 14.2.1
   @nrwl/devkit : 14.2.1
   @nrwl/eslint-plugin-nx : 14.2.1
   @nrwl/express : Not Found
   @nrwl/jest : 14.2.1
   @nrwl/js : 14.2.1
   @nrwl/linter : 14.2.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.2.1
   @nrwl/react-native : 14.2.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.2.1
   @nrwl/web : 14.2.1
   @nrwl/workspace : 14.2.1
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
```

**Comment by RaitoBezarius** [comment]
I hit this problem too.

**Comment by mdilshan** [comment]
> I hit this problem too, downgrading to 14.1.9 did not change anything, same for the eslint parser.

**Comment by mdilshan** [comment]
Tried building a react library. It successfully build it but still the react native libraries aren't able to build throwing the same issue.

**Comment by xiongemi** [comment]
i think it should be fixed a while back. there is an e2e test to build publishable library.
