### ISSUE TITLE
upgrade angular 14 (storybook fails to start) 

### ISSUE THREAD

**Issue by dean-g** [nrwl/nx#10623]
I am trying to upgrade angular 14 with the nrwl migration command, 

My storybook is failing to run 

```
> nx run stories:storybook

Schema validation failed with the following errors:
  Data path undefined should NOT have additional properties(assets).

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target storybook for project stories (4s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

please see the above error and advise if anything i am missing

**Comment by FrozenPandaz** [comment]
Are you using Nx `14.2.1`? Could you provide a repo that we can use to debug?

**Comment by dean-g** [comment]
I am using the following version:

`"@nrwl/workspace": "14.2.1",`

It's the private repo that I can't share. Please suggest what's going wrong here!.

**Comment by mandarini** [comment]
Hi there @dean-g ! Thanks for filing an issue!

Take a look at [this comment](https://github.com/nrwl/nx/issues/8496#issuecomment-1139607645) here. That person had a similar issue as you. Check out my [response](https://github.com/nrwl/nx/issues/8496#issuecomment-1139660833).

[Starting Nx 14.1.8](https://nx.dev/storybook/extra-topics-for-angular-projects) we're using the native Angular executor for Storybook as you may have already noticed. That native executor does not support assets. You have to add assets the "[Storybook way](https://storybook.js.org/docs/angular/configure/images-and-assets)"!

**Comment by mandarini** [comment]
I will be closing this issue, and let me know if you need any more help if I got it wrong, I can reopen! :)

Thank you so much!

**Comment by dean-g** [comment]
@mandarini Can you please check https://github.com/nrwl/nx/issues/11044 and advise?
