### ISSUE TITLE
Breaking changes in `nx print-affected` when moving from 14.1.9 to 14.2.2

### ISSUE THREAD

**Issue by fbartho** [nrwl/nx#10645]
## Current Behavior

We use `nx print-affected` and pipe it to a JSON file. We then use that to implement linting around our local package dependencies.

In 14.2.2 a the affected json file might look like:

```json
{
  "tasks": [],
  "projects": [],
  "projectGraph": {
    "nodes": [
      "myApp",
      "myLib",
    ],
    "dependencies": {
      "myApp": [
        {
          "source": "myApp",
          "target": "npm:axios",
          "type": "static"
        },
      ]
   // …
}       
```

## Expected Behavior

```json
{
  "tasks": [],
  "projects": [],
  "projectGraph": {
    "nodes": [
      "myApp",
      "myLib",
    ],
    "dependencies": {
      "myApp": [
        {
          "source": "myApp",
          "target": "myLib", // THIS IS MISSING IN 14.2.2
          "type": "static"
        },
        {
          "source": "myApp",
          "target": "npm:axios",
          "type": "static"
        },
      ]
   // …
}       
```

Notice the key difference -- that a local dependency on myLib is no longer exposed in the print-affected project graph.

## Steps to Reproduce

1. make a project using nx <= 14.1.9
1. make the project have at least 1 application target that depends on at least 1 local library target
1. examine the output of `nx print-affected`
1. notice that the dependency on the local library targets are documented via a `"target"` line that does not include `npm:`
1. upgrade to nx 14.2.2 & compare the output of `nx print-affected`
1. Notice that the local dependencies are no longer described in the `projectGraph::dependencies` node

### Failure Logs
_No failure logs present -- just undocumented breaking changes_

### Environment

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.12.0
   OS   : darwin x64
   yarn : 1.22.17
   
   nx : 14.2.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.2.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.2.2
   @nrwl/eslint-plugin-nx : 14.2.2
   @nrwl/express : 14.2.2
   @nrwl/jest : 14.2.2
   @nrwl/js : 14.2.2
   @nrwl/linter : 14.2.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.2.2
   @nrwl/nx-cloud : 14.0.8
   @nrwl/nx-plugin : 14.2.2
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 14.2.2
   @nrwl/workspace : 14.2.2
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:

✨  Done in 0.72s.
```

**Comment by fbartho** [comment]
EDIT: Filled in more of the template, accidentally submitted early.

**Comment by AgentEnder** [comment]
@fbartho Can you check on the dep-graph and make sure that the dependency is still actually being detected? This reads as if Nx doesn't think the dependency exists anymore.

**Comment by AgentEnder** [comment]
Is this repo public? Can you show your nx.json file?

**Comment by fbartho** [comment]
@AgentEnder no the repo is not public, here's my nx.json with some secrets stripped.

```json
{
	"extends": "nx/presets/npm.json",
	"implicitDependencies": {
		".eslintrc.json": "*",
		".github/workflows/pull_request.main.yml": "*"
	},
	"npmScope": "backend",
	"workspaceLayout": {
		"appsDir": "apps",
		"libsDir": "libs"
	},
	"tasksRunnerOptions": {
		"default": {
			"runner": "@nrwl/nx-cloud",
			"options": {
				"runtimeCacheInputs": ["sh -c 'echo ${RECORD:-false}-${UPDATE_FIXTURES:-false}'"],
				"cacheableOperations": [
					"build",
					"test",
					"lint",
					"package",
					"prepare",
					"emulator-start",
					"db-start-if-not-started"
				],
				"accessToken": "SECRET_REMOVED",
				"parallel": 1
			}
		}
	},
	"targetDependencies": {
		"build": [
			{
				"target": "build",
				"projects": "dependencies"
			}
		],
		"prepare": [
			{
				"target": "prepare",
				"projects": "dependencies"
			}
		],
		"package": [
			{
				"target": "package",
				"projects": "dependencies"
			}
		]
	},
	"affected": {
		"defaultBase": "origin/develop"
	},
	"cli": {
		"defaultCollection": "@nrwl/workspace"
	},
	"defaultProject": "gateway",
	"$schema": "./node_modules/nx/schemas/nx-schema.json"
}
```

Our workspace.json is much richer, but it's a huge file, so let me know if you need me to pore over that to check for secrets.

**Comment by AgentEnder** [comment]
@fbartho Can you add this to the bottom of your nx.json? The npm preset was updated to turn this off by default to more closely mimic standard npm workspaces, though I believe that there should have been a migration for that in the @nrwl/workspace package.

```json
  "pluginsConfig": {
    "@nrwl/js": {
      "analyzeSourceFiles": true
    }
  }
```

**Comment by fbartho** [comment]
Inspired by nx dep-graph I set our repo up to generate an SVG of the local packages and how they interrelate.

![mass of packages and their interdependencies](https://user-images.githubusercontent.com/209712/172952100-073b10b3-61b8-42d2-9473-23a6da749a8e.png)

This diagram is generated for every PR, and updated in our README when PRs merge. Triangles are NX applications, and Circles are NX Libraries.

**Comment by AgentEnder** [comment]
Looking further at your `nx.json` file, `defaultCollection` is also still present. Did you remember to run `nx migrate --run-migrations` after `nx migrate latest`?

**Comment by fbartho** [comment]
Adding the `pluginConfig` had partial effect? A very small number of the projects now have a graph of local dependencies, but by no means all of them. I tried `--skip-nx-cache` just in case, but no dice.

**Comment by fbartho** [comment]
Running `nx migrate latest` *again* to update from 14.2.2 to 14.2.4 appears to have resolved the immediate issues (it however did **not** produce a migrations.json however)

@AgentEnder Does your previous comment suggest we need to recover an old migration, or is there a patch we need to add to our nx.json?

**Comment by AgentEnder** [comment]
`nx migrate latest --from 14.1.9` would recreate a migrations json with those

**Comment by fbartho** [comment]
Thanks for the help @AgentEnder! Closing the ticket. 

Idea: documentation on the recommended way to integrate `nx migrate` with dependabot would have helped us avoid this mistake (unclear how it happened still, if it was a manual error or a bug somewhere).
