### ISSUE TITLE
Build fails after upgrade to v14.2.1

### ISSUE THREAD

**Issue by hamzou247** [nrwl/nx#10640]
## Current Behavior
Library build fails after migration from v13 to v14. 

ts-node is a dependancy of "@nrwl/angular". I don't know if it is is related to the error log.

## Expected Behavior
Build passes 

## Steps to Reproduce
1) Migrate to v14
2) build library

### Failure Logs
$ nx build shared-chat

   ×    1/1 dependent project tasks failed (see below)

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

> nx run shared-environments:build:development

Building Angular Package

------------------------------------------------------------------------------
Building entry point '@safesante/chat'
------------------------------------------------------------------------------
✖ Compiling with Angular sources in Ivy full compilation mode.
Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for project shared-chat and 4 task(s) it depends on (11s)

    ×    1/4 failed
    √    3/4 succeeded [0 read from cache]

### Environment
- Windows 11
- VSCode
- Angular
- NX

 >  NX   Report complete - copy this into the issue template

   Node : 14.17.3
   OS   : win32 x64
   npm  : 6.14.13

   nx : 14.2.1
   @nrwl/angular : 14.2.1
   @nrwl/cypress : 14.2.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.2.1
   @nrwl/eslint-plugin-nx : 14.2.1
   @nrwl/express : Not Found
   @nrwl/jest : 14.2.1
   @nrwl/js : 14.2.1
   @nrwl/linter : 14.2.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.0.5
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.2.1
   @nrwl/web : Not Found
   @nrwl/workspace : 14.2.1
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
         @ng-bootstrap/ng-bootstrap: 11.0.1
         @nguniversal/builders: 13.1.0
         @nguniversal/express-engine: 13.1.0
         ng2-charts: 3.0.9
         ngx-store: 3.1.1
         @compodoc/compodoc: 1.1.19
         @storybook/angular: 6.5.5
         @trumbitta/nx-plugin-unused-deps: 1.10.0

**Comment by hamzou247** [comment]
Solved. It was a configuration issue but the error was not explicit.

In the project.json, targets -> build -> options -> project was pointing to an other lib.

The error was misleading

**Comment by Coly010** [comment]
Hey @hamzou247 , can you share the project.json build target json? I'm curious if it's something we need to take into consideration for a migration.

Thanks!

**Comment by hamzou247** [comment]
Sure:

{
  "$schema": "..\\..\\..\\node_modules\\nx\\schemas\\project-schema.json",
  "projectType": "library",
  "sourceRoot": "libs/shared/environments/src",
  "prefix": "safesante",
  "targets": {
    "build": {
      "executor": "@nrwl/angular:ng-packagr-lite",
      "outputs": [
        "dist/libs/shared/environments"
      ],
      "options": {
        "project": "libs/shared/environments/ng-package.json"
      },
      "configurations": {
        "development": {
          "tsConfig": "libs/shared/environments/tsconfig.lib.json"
        }
      },
      "defaultConfiguration": "development"
    },
    "test": {
      "executor": "@nrwl/jest:jest",
      "outputs": [
        "coverage/libs/shared/environments"
      ],
      "options": {
        "jestConfig": "libs/shared/environments/jest.config.ts",
        "passWithNoTests": true
      }
    },
    "lint": {
      "executor": "@nrwl/linter:eslint",
      "options": {
        "lintFilePatterns": [
          "libs/shared/environments/src/**/*.ts",
          "libs/shared/environments/src/**/*.html"
        ]
      }
    }
  },
  "tags": [
    "scope:shared",
    "type:environments"
  ]
}


Error source was:

        "project": "libs/shared/chat/ng-package.json"

**Comment by Coly010** [comment]
No problem, so it was an invalid config value. 

I'll close this issue as there isn't much we can do for this, but hopefully, the information in this ticket helps others solve it just as you have! :)

**Comment by capJavert** [comment]
I had the same error on `nx@14.4.3`, it was due to `"tsPlugins": ["@nestjs/swagger/plugin"]` line in my `project.json`. Based on this https://stackoverflow.com/questions/72488958/false-expression-non-string-value-passed-to-ts-resolvetypereferencedirective I downgraded `typescript` to `4.6.4` (latest `4.6.x`) release and the error was gone. FYI @Coly010
