### ISSUE TITLE
React native resolver blockList does not work for apps in subdirectories

### ISSUE THREAD

**Issue by ajwootto** [nrwl/nx#10644]
## Current Behavior

If a react native app is located in a subdirectory of `apps/` eg.
`apps/my-category/my-app`
Then the blockList rule that is meant to exclude the repo's root-level `dist/` directory does not work correctly. You then get errors about the build trying to include the contents of the `dist/` directory

## Expected Behavior

The configuration of react native apps should ignore the root-level dist/ directory regardless of whether it's located in `apps/` or in a subdirectory.

## Steps to Reproduce

1. `nx g @nrwl/react-native app my-category/my-app`
2. ensure `dist/` directory has some contents
3. nx serve my-category-my-app

### Environment

```
 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : darwin x64
   yarn : 3.2.0

   nx : 14.0.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.0.5
   @nrwl/detox : 14.0.5
   @nrwl/devkit : 14.0.5
   @nrwl/eslint-plugin-nx : 14.0.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.5
   @nrwl/js : 14.0.5
   @nrwl/linter : 14.0.5
   @nrwl/nest : Not Found
   @nrwl/next : 14.0.5
   @nrwl/node : 14.0.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.0.5
   @nrwl/react-native : 14.0.5
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.0.5
   @nrwl/web : 14.0.5
   @nrwl/workspace : 14.0.5
   typescript : 4.6.3
   rxjs : 6.6.7
   ```

**Comment by xiongemi** [comment]
how about regex like `/^(?!.*node_modules).*\/dist\/.*/`. this should block all the dist folder that is NOT under node_modules.

**Comment by xiongemi** [comment]
close this issue.
