### ISSUE TITLE
Configurable normalized project name maximum length for `--output-style=stream`

### ISSUE THREAD

**Issue by mehmetcozdemir** [nrwl/nx#10656]
## Description
Newly implemented `--output-style=stream` is great but it normalizes project names to at most 15 chars. Our project names are mostly around 30-40 chars so it looks really weird with current configuration. 

Code is here: https://github.com/nrwl/nx/blob/67a27774ac9e0aa906797fa3a02cccec40d71fcb/packages/nx/src/utils/add-command-prefix.ts#L59-L63

## Motivation
15 is a pretty arbitrary number for max length of normalized project names. It should be configurable.

## Suggested Implementation
There should be an option to set max length of normalized project names.

## Alternate Implementations
An option to disable project name normalization completely might be sufficient. Maybe both options should be available.

**Comment by josephtesla** [comment]
Currently having the same issue
