### ISSUE TITLE
Where is the stable version.

### ISSUE THREAD

**Issue by backnotprop** [nrwl/nx#10675]
Im not sure I really need to explain this, however – and I am certain there exists a vast amount of nx users frustrated with the `nx migration` experiences. Specifically, lacking (or hard to find?) documentation on any version support. Instead, there are plenty if github issues, google results + all the spam generated results, stackoverflow links, etc... to various rabbit holes of further nuance. 

Minimally, where is the node, angular/any-package, `compatibility` matrix, and `lts` timeline? This library is an integration fabric, "always be updating" won't work for even the most adaptive enterprise software shops.

**Comment by backnotprop** [comment]
fwiw here is an approach that worked for me, migrating from 12 to 13, (tried 14 first, failed a bunch, after failing a bunch with 13). 

Using `OSX`. Still concerned bc I have devs that need to figure this out on windows.

1. **Wipe node/npm:**
    - Remove all`Node`versions where `nx` was globally installed
   -  if anything, ensure you **delete all global `nx`** 
   -  the reason you nuke it all is because there seems to be a bunch of issues or conflicts with things like symlinks and/or peer dependencies. `nvm` envs likely make this worse
   - **never** npm install -g nx again**
      ```diff
       ⛔️ - npm install -g nx ⛔️
      ```
2. Stabilize/reinstall your local Node back to whatever your last stable was
3. Wipe your projects `node_modules`, `cd <wksprj-dir> && rm -rf ./node_modules`
4. If `@nrwl/cli` isn't in your `package.json`, add it there.
5. `npm install` (in your workspace/project dir)
6. `node_modules/.bin/nx migrate @nrwl/workspace@13.10.5`
    - you an set `"nx": "node_modules/.bin/nx"` in package.json scripts
7. 🤞

If all goes well, `npm install` take the next steps, 🤞

**Comment by jaytavares** [comment]
It would be VERY helpful if the documentation website displayed version support information. It's pretty untenable to require that everyone always be using the absolute latest version of Nx. Version selection within API documentation is ubiquitous and IMO absolutely necessary.

**Comment by jaytavares** [comment]
Not closed
