### ISSUE TITLE
Nx run serve could not find project

### ISSUE THREAD

**Issue by akirawinz** [nrwl/nx#10674]
## Current Behavior
I'm working on multiple nx project and all of them uses some sharelib together so I decide to separate 1 nx for sharelib with using git submodule after I tried to use npm workspaces for link 2 nx project but after i try nx can't find project path

## Expected Behavior
I want to run nx serve in root project path

## Steps to Reproduce
I already add READ.me for start project
https://github.com/akirawinz/multi-nx-project-with-sharedlib

### Failure Logs
NX   Running target "workspaces-apps-ms-test:serve" failed

### Environment

Here is nx report

  Node : 16.15.0
   OS   : darwin arm64
   npm  : 8.5.5

   nx : 14.2.1
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.2.1
   @nrwl/eslint-plugin-nx : 14.2.1
   @nrwl/express : Not Found
   @nrwl/jest : 14.2.1
   @nrwl/js : 14.2.2
   @nrwl/linter : 14.2.1
   @nrwl/nest : 14.2.4
   @nrwl/next : Not Found
   @nrwl/node : 14.2.4
   @nrwl/nx-cloud : 14.0.8
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.2.1
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:

**Comment by harjotsingh26** [comment]
>  NX   Cannot find target 'serve' for project 'backend-ms-identities'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
