### ISSUE TITLE
Error: Can't resolve 

### ISSUE THREAD

**Issue by eugenotop** [nrwl/nx#1068]
angular.json
```
      "architect": {
        "build": {
          "builder": "@nrwl/builders:node-build",
          "options": {
            "outputPath": "dist/server",
            "main": "apps/server/src/main.ts",
            "tsConfig": "apps/server/tsconfig.json",
            "assets": ["apps/server/src/assets"],
            "progress": true
          },
```

```
"@angular/animations": "7.2.4",
"@angular/cdk": "7.3.1",
"@angular/common": "7.2.4",
"@angular/compiler": "7.2.4",
"@angular/core": "7.2.4",
"@angular/forms": "7.2.4",
"@angular/http": "7.2.4",
"@angular/material": "7.3.1",
"@angular/platform-browser": "7.2.4",
"@angular/platform-browser-dynamic": "7.2.4",
"@angular/platform-server": "7.2.4",
"@angular/router": "7.2.4",
"@nestjs/common": "^5.7.0",
"@nestjs/core": "^5.7.0",
"@nestjs/microservices": "^5.7.0",
"@nestjs/ng-universal": "^0.2.0",
"@nestjs/websockets": "^5.7.0",
"@ngrx/effects": "^7.2.0",
"@ngrx/router-store": "^7.2.0",
"@ngrx/store": "^7.2.0",
"@nguniversal/common": "7.1.0",
"@nguniversal/express-engine": "7.1.0",
"@nguniversal/module-map-ngfactory-loader": "^7.1.0",
"@nrwl/nx": "7.5.1",

"@angular-devkit/build-angular": "~0.13.0",
"@angular/cli": "~7.3.0",
"@angular/compiler-cli": "^7.2.4",
"@angular/language-service": "^7.2.4",
"@nestjs/testing": "^5.7.0",
"@nrwl/builders": "^7.5.1",
"@nrwl/schematics": "7.5.1",
```

### Failure Logs

WARNING in ./node_modules/@nestjs/common/utils/load-package.util.js

Module not found: Error: Can't resolve '/src' in '/node_modules/@nestjs/common/utils'

@ ./node_modules/@nestjs/common/utils/load-package.util.js

@ ./node_modules/@nestjs/core/adapters/fastify-adapter.js

@ ./node_modules/@nestjs/core/adapters/index.js

@ ./node_modules/@nestjs/core/index.js

@ ./apps/server/src/main.ts

WARNING in ./node_modules/moment/moment.js

Module not found: Error: Can't resolve 'src' in '/node_modules/moment'

@ ./node_modules/moment/moment.js

@ ./dist/server-mobile/main.js

@ ./apps/server/src/main.ts

WARNING in ./node_modules/optional/optional.js

Module not found: Error: Can't resolve '/src' in '/node_modules/optional'

@ ./node_modules/optional/optional.js

@ ./node_modules/@nestjs/core/nest-application.js

@ ./node_modules/@nestjs/core/index.js

@ ./apps/server/src/main.ts

ERROR in ./node_modules/@angular/core/fesm5/core.js

Module not found: Error: Can't resolve '/src' in '/node_modules/@angular/core/fesm5'

@ ./node_modules/@angular/core/fesm5/core.js 18260:15-36 18272:15-102

@ ./apps/server/src/main.ts

ERROR in ./node_modules/@nestjs/core/node_modules/express/lib/view.js

Module not found: Error: Can't resolve '/src' in '/node_modules/@nestjs/core/node_modules/express/lib'

@ ./node_modules/@nestjs/core/node_modules/express/lib/view.js 81:13-25

@ ./node_modules/@nestjs/core/node_modules/express/lib/application.js

@ ./node_modules/@nestjs/core/node_modules/express/lib/express.js

@ ./node_modules/@nestjs/core/node_modules/express/index.js

@ ./node_modules/@nestjs/core/adapters/express-adapter.js

@ ./node_modules/@nestjs/core/nest-application.js

@ ./node_modules/@nestjs/core/index.js

@ ./apps/server/src/main.ts

ERROR in ./node_modules/express/lib/view.js

Module not found: Error: Can't resolve '/src' in '/node_modules/express/lib'

@ ./node_modules/express/lib/view.js 81:13-25

@ ./node_modules/express/lib/application.js

@ ./node_modules/express/lib/express.js

@ ./node_modules/express/index.js

@ ./apps/server/src/main.ts

**Comment by FrozenPandaz** [comment]
Please provide a repro of the issue so I can take a look.

**Comment by vsavkin** [comment]
Closing this. If the issue persists, could you reopen it with a repro? Thanks!
