### ISSUE TITLE
Auto-install nestjs/cli

### ISSUE THREAD

**Issue by ThomasBurleson** [nrwl/nx#1069]
When creating a NestJS node application with nrwl/schematics, the NestJS/CLI should be auto-installed.

```console
npm i -g @nestjs/cli
```

**Comment by FrozenPandaz** [comment]
What is the motivation for having NestCLI installed?

Running schematics is a bit easier with the NestCLI but it requires a separate configuration from `angular.json` so I would recommend using Angular CLI to run schematics.

See related issue on better support for NestJS Schematics: https://github.com/nrwl/nx/issues/972

**Comment by vsavkin** [comment]
+1 to @FrozenPandaz said. I think having two CLIs can confuse developers. Our goal is to unify the toolstack as much as we can, so devs can build full stacks apps using same commands (ng and Angular Console).

We should make sure nothing we do prevents folks from using the nest cli, but I  don't think we should go beyond that.
