### ISSUE TITLE
changelog?

### ISSUE THREAD

**Issue by EreckGordon** [nrwl/nx#107]
cannot find one

**Comment by ciesielskico** [comment]
https://github.com/nrwl/nx/commits/master

**Comment by EreckGordon** [comment]
so, no then?

**Comment by jschwarty** [comment]
We will work on getting one added. 😎

**Comment by vsavkin** [comment]
here you go: https://github.com/nrwl/nx/blob/master/CHANGELOG.md

**Comment by zpydee** [comment]
it would be useful for nx to create a changelog for my workspace on releases, like lerna does with the --conventional-commits flag.
