### ISSUE TITLE
execute package independent without app (such cli package)

### ISSUE THREAD

**Issue by jon9090** [nrwl/nx#10705]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Currently, nrwl js lib or node lib support build command to build the package.
It would be nice if I can run the package independent, such as cli (with build and watch)

## Motivation

For example I need to create a repo with cli. when I write the code I want to run it so I can test my cli.

**Comment by luxaritas** [comment]
Maybe you're looking for the [`@nrwl/node:node` executor](https://nx.dev/packages/node/executors/node)?

**Comment by jon9090** [comment]
Yes, it can be my solution. thanks!
