### ISSUE TITLE
Cannot migrate to latest from 14.1.7

### ISSUE THREAD

**Issue by chriscurnow** [nrwl/nx#10717]
Sorry some of the error messages have scrolled off my terminal transcript so I have to rely on memory for the exact messasges.

## Current Behavior
Run npx nx migrate latest
Error: `can't find '/migrations/`

Created `migrations` directory and moved current `migrations.json` to this directory
There was another error at this point.

I ended up migrating to `14.2.2` first and then to latest. That worked

## Expected Behavior
Should be able to migrate directly from `14.1.7` to latest

## Steps to Reproduce
Starting with installed version `14.1.7` run

`npm nx migrate latest`

### Environment

Here is nx report. (It is probably not particularly helpful now as I have already migrated to `14.2.2`)

 Node : 16.15.1
   OS   : darwin arm64
   npm  : 8.12.1
   
   nx : 14.2.4
   @nrwl/angular : 14.2.4
   @nrwl/cypress : 14.2.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.2.4
   @nrwl/eslint-plugin-nx : 14.2.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.2.4
   @nrwl/js : Not Found
   @nrwl/linter : 14.2.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.2.4
   @nrwl/web : Not Found
   @nrwl/workspace : 14.2.4
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
         @ngrx/component-store: 13.2.0
         @ngrx/effects: 13.2.0
         @ngrx/entity: 13.2.0
         @ngrx/router-store: 13.2.0
         @ngrx/store: 13.2.0
         rxjs: 6.6.7
         @ngrx/schematics: 13.2.0
         @ngrx/store-devtools: 13.2.0

**Comment by chriscurnow** [comment]
This is obviously not a high-priority issue.
I just wanted to let you know about it for future migration scripts:)

**Comment by FrozenPandaz** [comment]
Sorry, I can no longer reproduce this issue. It's possible it has been fixed if you were able to migrate past `14.2.2`.

I rolled `nx-examples` back to `14.1.7` and ran `nx migrate latest` successfully.

If you come across the same issue, please open a new issue. :pray:
