### ISSUE TITLE
Docs: mfe tutorial does not work with version 14.2.4

### ISSUE THREAD

**Issue by gkamperis** [nrwl/nx#10711]
Hello

Following the steps of the below 

https://nx.dev/module-federation/dynamic-module-federation-with-angular

after login the navigation fails and the component is not shown

`nx serve dashboard --devRemotes=login`

with error

![image](https://user-images.githubusercontent.com/18055519/173205700-1d59b725-b42d-4516-b4cb-a8a9c95fceda.png)

Thanks

EDIT: 14.1.9 + ng v13 has the same result

### Environment
>  NX   Report complete - copy this into the issue template

   Node : 18.0.0
   OS   : win32 x64
   npm  : 8.4.1

   nx : 14.2.4
   @nrwl/angular : 14.2.4
   @nrwl/cypress : 14.2.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.2.4
   @nrwl/eslint-plugin-nx : 14.2.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.2.4
   @nrwl/js : Not Found
   @nrwl/linter : 14.2.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.2.4
   @nrwl/web : Not Found
   @nrwl/workspace : 14.2.4
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:

**Comment by Coly010** [comment]
The error in the console is known and a non-issue. You can read more about that explanation here: https://github.com/nrwl/nx/issues/8137#issuecomment-996576398

I'll update the docs to include that.

**Comment by gkamperis** [comment]
Thanks for the quick response.

However the navigation does not work once I log in. I can see the message saying I can see the content but nothing is shown. The nx-welcome component is not displayed.

**Comment by gkamperis** [comment]
@Coly010 you closed the issue but the erroneous end result still remains. 

If the attached reported error is not causing the issue then something else is. 

The example still does not work even after your commit. 
Can you pls reopen and check the issue out or should I raise another issue?

**Comment by gkamperis** [comment]
@Coly010 many thanks... after your last response I checked and indeed it is not supposed to be shown!

To clarify after scaffolding and adding the routes per post I have the below setup in the dashboard app.

```
RouterModule.forRoot(
      [
        {
          path: '',
          component: NxWelcomeComponent,
        },
        {
          path: 'login',
          loadChildren: () =>
            import('login/Module').then((m) => m.RemoteEntryModule),
        },
      ],
      { initialNavigation: 'enabledBlocking' }
    ),
```

so I assumed this 
```
ngOnInit() {
    this.isLoggedIn$
      .pipe(distinctUntilChanged())
      .subscribe(async (loggedIn) => {
        if (!loggedIn) {
          this.router.navigateByUrl('login');
        } else {
          this.router.navigateByUrl('');
        }
      });
  }
```
would show it but it seems the post's template only has an outlet when **not** logged in.
```
template: `
    <div class="dashboard-nav">Admin Dashboard</div>
    <div *ngIf="isLoggedIn$ | async; else signIn">
      You are authenticated so you can see this content.
    </div>
    <ng-template #signIn><router-outlet></router-outlet></ng-template>
  `,
```

So for it to show I need to add an outlet or rework the template
```
     ...
      You are authenticated so you can see this content.
      <router-outlet></router-outlet>
     ...
```
Thanks again for your help!
