### ISSUE TITLE
[Feature request] server side webpack with source-map-support

### ISSUE THREAD

**Issue by ueqt** [nrwl/nx#1072]
## Expected Behavior

When node-app throw error, I need ts stack trace, not js stack trace.

## Current Behavior

I got js stack trace.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. generate node-app in nx project
```bash
create-nx-workspace test
cd test
ng g node-app server
```
2. add error in /apps/server/src/main.ts just after `import` 
```typescript
throw new Error('test');
```
3. run it
```bash
ng serve server
```
4. it will show stack trace as follow
```
test/dist/apps/server/main.js:222
throw new Error('test');
```
but I wanna it show like `main.ts:9`

### Reference

https://decembersoft.com/posts/how-to-fix-your-server-side-typescript-call-stack-with-webpack-bannerplugin/

**Comment by FrozenPandaz** [comment]
It seems we need https://webpack.js.org/plugins/banner-plugin/.

The related code is here: https://github.com/nrwl/nx/blob/master/packages/builders/src/node/build/webpack/config.ts#L80
