### ISSUE TITLE
Browser application bundles will not generate after update

### ISSUE THREAD

**Issue by nwatrailhub** [nrwl/nx#10721]
## Current Behavior

After upgrading from @nrwl/angular 13.x.x to @nrwl/angular 14.2.4 using nx migrate latest

`nx serve <project> --devRemotes=<remote-project>` generates the following output and hangs `⠋ Generating browser application bundles (phase: setup)...⠋ Generating browser application bundles (phase: setup)...`

Adding the --verbose flag generates no additional output

## Expected Behavior
The project should build and serve as normal like it did before the upgrade.

## Steps to Reproduce
It's an internal project so I can't provide a repo and it's a cli issue. After running nx migrate lastest my project hangs on generating browser application bundles

### Environment
 NX   Report complete - copy this into the issue template

   Node : 18.0.0
   OS   : darwin arm64
   npm  : 8.12.1
   
   nx : 14.2.4
   @nrwl/angular : 14.2.4
   @nrwl/cypress : 14.2.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.2.4
   @nrwl/eslint-plugin-nx : 14.2.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.2.4
   @nrwl/js : Not Found
   @nrwl/linter : 14.2.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.2.4
   @nrwl/web : Not Found
   @nrwl/workspace : 14.2.4
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
         @reactivex/rxjs: 6.6.7
         ngx-build-plus: 14.0.0

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Unfortunately, I'm unable to reproduce the issue with the information provided. Without a reproduction would be hard for us to troubleshoot this. You mentioned you can't provide the project because it's internal, but you could try creating a reproduction.

**Comment by leosvelperez** [comment]
@nwatrailhub could you try to serve it without passing the `--devRemotes` flag? It could narrow down where to look. If you identify is one of the remotes you're passing to it, you could try serving the remote on its own with `--verbose` to try to get more info.

**Comment by Coly010** [comment]
It has been 20 days since this issue has had any updates. I'm going to close this issue.

If there are any future updates, feel free to reply and tag me in the reply and we can take a look at this again!
