### ISSUE TITLE
No cached ProjectGraph is available

### ISSUE THREAD

**Issue by B1Z1** [nrwl/nx#10730]
Hi, we started to use nx in our application. Currently, we have moved 280 modules to buildable libraries.

## Current Behavior
Sometimes build fails because of an error. Mainly it happens when some of our developers switch between branches, but also when we trying to build an application after yarn nx clear-cache command. It also fails on random libraries, sometimes on one library, sometimes on several libraries.

## Expected Behavior
Normal not failing build. In our company, we have ~100 developers and 3/4 of them face this problem several times a week.

## Steps to Reproduce

I tried to make a repository and add some libraries, but I cannot reproduce it. Maybe it's something with background graph updating. Once you wrote in your documentation, that graph updates in the background once in while. Maybe because of build took too long, graph updates and interrupt the build process? 

If you need more information, we can try go deeper with it

### Failure Logs

```
[readCachedProjectGraph] ERROR: No cached ProjectGraph is available.

If you are leveraging \`readCachedProjectGraph()\` directly then you will need to refactor your usage to first ensure that
the ProjectGraph is created by calling \`await createProjectGraphAsync()\` somewhere before attempting to read the data.

If you encounter this error as part of running standard \`nx\` commands then please open an issue on https://github.com/nrwl/nx

Make sure invoke 'node ./decorate-angular-cli.js' in your postinstall script.
The decorated CLI will compute the project graph.
'ng --help' should say 'Smart, Fast and Extensible Build System'.
```

### Environment

Every developer have same environment

   Node : 12.22.7
   OS   : darwin x64
   yarn : 1.22.4

   nx : 14.0.5
   @nrwl/angular : 14.0.5
   @nrwl/cypress : 14.0.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.0.5
   @nrwl/eslint-plugin-nx : 13.8.5
   @nrwl/express : Not Found
   @nrwl/jest : 13.8.5
   @nrwl/js : 14.0.5
   @nrwl/linter : 14.0.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.0.5
   @nrwl/nx-cloud : 14.0.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.0.5
   @nrwl/web : 14.0.5
   @nrwl/workspace : 14.0.5
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
   	 @ngneat/transloco: 2.20.1
   	 @ngrx/effects: 12.5.0
   	 @ngrx/entity: 12.4.0
   	 @ngrx/store: 12.5.0
   	 @ngrx/store-devtools: 12.5.0
   	 @storybook/angular: 6.4.19

**Comment by AgentEnder** [comment]
Hey @B1Z1, it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

**Comment by B1Z1** [comment]
Hi @AgentEnder, I think it doesn't matter, because:
1) It's only jest and eslint, I think they cannot interrupt into the process
2) Before we had 13.8.5 version of every package and we still got it
3) I have a commit which updates nx to version 14.1.9 and it's still doesn't work :D

**Comment by AgentEnder** [comment]
For clarity, the actual packages that are out of sync don't matter necessarily. Different versions of packages interact differently, so its definitely recommended to keep them in line and use `nx migrate` to update them, which should keep them in sync. 

If you've already checked with everything lined up on 13.8.5 and 14.1.9, then that is what matters in this context.

Can you try to create a reproduction for this issue and link it? This isn't something we have seen in standard setups, so there may be some other info that we need from a repro to troubleshoot this.

**Comment by B1Z1** [comment]
@AgentEnder meanwhile here is full log of error, maybe it might help you:

Error reading '/Users/illia.mishkin/ppm/ui/node_modules/.cache/nx/nxdeps.json'. Continue the process without the cache.
Error: ValueExpected in /Users/illia.mishkin/ppm/ui/node_modules/.cache/nx/nxdeps.json at position 0
    at parseJson (/Users/illia.mishkin/ppm/ui/node_modules/nx/src/utils/json.js:30:15)
    at readJsonFile (/Users/illia.mishkin/ppm/ui/node_modules/nx/src/utils/fileutils.js:26:37)
    at readCache (/Users/illia.mishkin/ppm/ui/node_modules/nx/src/project-graph/nx-deps-cache.js:41:49)
    at readCachedProjectGraph (/Users/illia.mishkin/ppm/ui/node_modules/nx/src/project-graph/project-graph.js:19:61)
    at /Users/illia.mishkin/ppm/ui/node_modules/@nrwl/angular/src/executors/package/package.impl.js:41:161
    at Generator.next (<anonymous>)
    at resume (/Users/illia.mishkin/ppm/ui/node_modules/tslib/tslib.js:225:48)
    at /Users/illia.mishkin/ppm/ui/node_modules/tslib/tslib.js:224:125
    at new Promise (<anonymous>)
    at Object.i.<computed> [as next] (/Users/illia.mishkin/ppm/ui/node_modules/tslib/tslib.js:224:67)
    at /Users/illia.mishkin/ppm/ui/node_modules/nx/src/command-line/run.js:50:35
    at Generator.next (<anonymous>)
    at /Users/illia.mishkin/ppm/ui/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/illia.mishkin/ppm/ui/node_modules/tslib/tslib.js:113:16)
    at iteratorToProcessStatusCode (/Users/illia.mishkin/ppm/ui/node_modules/nx/src/command-line/run.js:36:20)
[readCachedProjectGraph] ERROR: No cached ProjectGraph is available.

If you are leveraging \`readCachedProjectGraph()\` directly then you will need to refactor your usage to first ensure that
the ProjectGraph is created by calling \`await createProjectGraphAsync()\` somewhere before attempting to read the data.

If you encounter this error as part of running standard \`nx\` commands then please open an issue on https://github.com/nrwl/nx

Make sure invoke 'node ./decorate-angular-cli.js' in your postinstall script.
The decorated CLI will compute the project graph.
'ng --help' should say 'Smart, Fast and Extensible Build System'.

**Comment by leosvelperez** [comment]
hey @B1Z1!

Looking at this part of the log, have you run those commands below? Do they run successfully?

```bash
Make sure invoke 'node ./decorate-angular-cli.js' in your postinstall script.
The decorated CLI will compute the project graph.
'ng --help' should say 'Smart, Fast and Extensible Build System'.
```

When the issue happens, are you running `nx ...` or `ng ...`?

**Comment by B1Z1** [comment]
Interesting facts:

1. We implemented nx cloud and after it worked well. Now we don't use nx cloud, because we are waiting for financing 
2. On our CI we always start building applications without cache (cold start) and we had no problems with it

**Comment by leosvelperez** [comment]
Thanks for the provided info. Unfortunately, it's not enough for us to be able to troubleshoot this issue. We need a reproduction.

**Comment by B1Z1** [comment]
If you can show your project and add repro steps, it might help to reproduce it

**Comment by BenLune** [comment]
Thanks @B1Z1 for your quick reply. Unfortunatly it's a private project and I can't share it.
Which nx version are you using ?
It worked well with `14.3.6` nx version, since I updated to `14.4.3`, I have this problem.
I'm triggering a CI job with another project using `14.3.6` to see if it works or not. If it works on the same CI environment with `14.3.6`, it may mean that there is a problem in the `14.4.3` version.

**Comment by B1Z1** [comment]
At this moment I have version 14.1.9, but I tried to upgrade our project, to the newest one and this doesn't change anything. We are waiting, for Angular 14.1 and will upgrade it and merge it, but I think it doesn't help

**Comment by BenLune** [comment]
The other project I have in the same CI environment was successfully built, with nx `14.3.6` version.
Hi @leosvelperez, could please let us know what you think about this?

**Comment by BenLune** [comment]
I have new functionalities to deliver, I'll have to build the app locally and deploy it manually. I won't `nx migrate` my other projects...
@leosvelperez, I think this issue should be re-open.

**Comment by BenLune** [comment]
I reverted my package.json file to the `14.3.6` version and it's ok now.
I still don't understand what happened but there might be something strange in the `14.4.3` version.
I think I'll create a dedicated branch when I migrate Nx to be sure it will run on CI. And waiting for successful build before going on working on new functionalities.
@leosvelperez @AgentEnder please let us know what you think about this :-)
