### ISSUE TITLE
Storybook live reloading does not catch compilation errors

### ISSUE THREAD

**Issue by 051181** [nrwl/nx#10737]
## Current Behavior
When introducing a typescript error storybook live server does not catch the error and webpack compilation is fine

## Expected Behavior
I espect that webpack will fail if an error is thrown

## Steps to Reproduce
create an empty angular workspace, add a library and a component, add storybook to that library, start storybook, type whatever inside your component and then save

### Environment
  Node : 14.17.4
   OS   : linux x64
   npm  : 8.5.4
   
   nx : 14.3.1
   @nrwl/angular : 14.3.1
   @nrwl/cypress : 14.3.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.1
   @nrwl/eslint-plugin-nx : 14.3.1
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.1
   @nrwl/js : Not Found
   @nrwl/linter : 14.3.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.3.1
   @nrwl/web : Not Found
   @nrwl/workspace : 14.3.1
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
         @storybook/angular: 6.5.9

**Comment by mandarini** [comment]
Hi there @051181 ! Thanks for filing an issue! I think that this is not an issue with Nx, but rather an issue with Storybook. The reason I believe that, is that [Nx is now using the native Storybook executors](https://nx.dev/storybook/extra-topics-for-angular-projects), so there's basically no "middleperson" between your code and Storybook any more.

In any case, you can verify this by trying out Storybook in a pure Angular app, and just let me know if the experience you have is different.

Here's how you can try out Storybook in a pure Angular app (steps copied from [this guide](https://storybook.js.org/docs/angular/get-started/install)):

1. `ng new my-app`
2. `cd my-app`
3. `npx storybook init`
4. Update your angular.json file to include Storybook's custom builder:
```
{
  "storybook": {
    "builder": "@storybook/angular:start-storybook",
    "options": {
      "browserTarget": "my-app:build",
      "port": 6006
    }
  },
  "build-storybook": {
    "builder": "@storybook/angular:build-storybook",
    "options": {
      "browserTarget": "my-app:build"
    }
  }
}
```
5. `ng run my-app:storybook`

**Comment by 051181** [comment]
hi @mandarini, you are absolutely right! i will close this issue and i will open another inside the storybook project.
Thanks

**Comment by mandarini** [comment]
Ohhh cool!!! I mean, not cool that there's a bug, but cool that now the experience we offer is native! :) Thanks @051181 !
