### ISSUE TITLE
Rollup package issues after (#10349)

### ISSUE THREAD

**Issue by radulle** [nrwl/nx#10741]
Introduced after feat(web): add support for Node ESM when used to package SSR-ready library (#10349)

## Current Behavior
New feature causes issues in tolling that does not support `type: module` and `exports`. CSS can't be imported via @import in other CSS files and import in JS/TS and missing react/jsx-runtime error is getting thrown. If I remove `type: module` and `exports` it does work. CSS import from lib does work if CSS is added to `exports` but only in JS, not in CSS.

## Expected Behavior
1. It would be good to have a flag that would omit these two properties from package.json.
2. Exports should contain generated CSS assets.
3. CSS should be importable via `@import` in CSS files

## Steps to Reproduce

Here is reproduction Gasket (NextJS with React 17) repo https://github.com/radulle/gasket-issue. It's interesting that pure nextjs app does not have react/jsx-runtime issue https://github.com/radulle/nextjs-issue. This is NX repo where lib is generated https://github.com/radulle/nx-issue. I added FIXME comments with some conclusions in both repos that use the lib.

### Environment
NextJS apps provided in 2 repos, one with React 18 and one React 17.

**Comment by jaysoo** [comment]
In the next release, Nx will not generated `exports` field by default, and users need to opt-in via `generateExportsField`. This patch should fix issues where entry points are broken with `exports`.

**Comment by evanjmg** [comment]
How do we remove the exports field on the current version? My build is breaking
