### ISSUE TITLE
Parallel and MaxParallel nx.json tasksRunnnerOptions are Ignored in Nx 12.8.0 to 12.10.1

### ISSUE THREAD

**Issue by DG-SHeather** [nrwl/nx#10756]
## Current Behavior

In Nx version `12.8.0` to `12.10.1`, adding `options.parallel` or `options.maxParallel` to `tasksRunnerOptions.default` in `nx.json` is ignored when running `nx affected` or `nx run-many` and the settings default to `false` and `3` respectively.

## Expected Behavior

Adding these options should set these properties as default. This works correctly in versions `12.7.2` and below.

## Cause

This is caused by a change in PR https://github.com/nrwl/nx/pull/6669 setting defaults on the CLI in `packages/workspace/src/command-line/nx-commands.ts` for the `parallel` and `maxParallel` parameters, meaning that settings within `nx.json` are never considered.

### Resolution

Remove the CLI defaults for [parallel](https://github.com/nrwl/nx/blob/513f1036584267bb2b8f894d464f60e5e81cce1d/packages/workspace/src/command-line/nx-commands.ts#L532) and [maxParallel](https://github.com/nrwl/nx/blob/513f1036584267bb2b8f894d464f60e5e81cce1d/packages/workspace/src/command-line/nx-commands.ts#L538)

### Environment

```
Node : 14.17.2
  OS   : win32 x64
  npm  : 6.14.13

  nx : 12.10.0
  @nrwl/angular : 12.10.0
  @nrwl/cli : 12.10.0
  @nrwl/cypress : 12.10.0
  @nrwl/devkit : 12.10.0
  @nrwl/eslint-plugin-nx : 12.10.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.10.0
  @nrwl/linter : 12.10.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.10.0
  @nrwl/storybook : 12.10.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by AgentEnder** [comment]
Hey @DG-SHeather! Nx 12 is not something we actively support, as it is a few major versions back at this point. I understand that their may be a requirement to stay on Angular 12 that is keeping you there, but could you try migrating Nx to 13.1.x?  This should leave angular on v12 since support for 13 was added in 13.2.0.

**Comment by DG-SHeather** [comment]
HI @AgentEnder, thanks for the response. is the supported Nx versions and the support lifecycle documented anywhere?
