### ISSUE TITLE
Storybook build fails with the nrwl/angular 14 upgrade

### ISSUE THREAD

**Issue by dean-g** [nrwl/nx#10752]
```
nx run stories:build-storybook --source-map=false
> nx run stories:build-storybook --source-map=false
'source-map' is not found in schema
 
 >  NX   Running target "stories:build-storybook" failed
   Failed tasks:
   
   - stories:build-storybook
   
   Hint: run the command with --verbose for more details.
error Command failed with exit code 1.
```
package versions: 

```
"@nrwl/storybook": "14.3.1",
    "@storybook/addon-actions": "^6.5.9",
    "@storybook/addon-controls": "^6.5.9",
    "@storybook/addon-docs": "^6.5.9",
    "@storybook/addon-essentials": "6.5.9",
    "@storybook/addon-links": "^6.5.9",
    "@storybook/addon-options": "^6.0.0-alpha.29",
    "@storybook/addon-storysource": "^6.5.9",
    "@storybook/addons": "^6.5.9",
    "@storybook/angular": "6.5.9",
    "@storybook/builder-webpack5": "6.5.9",
    "@storybook/core-server": "6.5.9",
    "@storybook/manager-webpack5": "6.5.9",
    "@storybook/theming": "^6.5.9",
```

Can someone please advise on this?

**Comment by mandarini** [comment]
Hi there @dean-g ! Thanks for filing an issue! I think that this is not an issue with Nx, but rather an issue with Storybook. The reason I believe that, is that [Nx is now using the native Storybook executors](https://nx.dev/storybook/extra-topics-for-angular-projects), so there's basically no "middleperson" between your code and Storybook any more.

If you look at the [documentation](https://storybook.js.org/docs/angular/get-started/install#troubleshooting) (expand the Troubleshooting section), you will see that indeed there's no `source-map` flag available!

In any case, you can verify this by trying out Storybook in a pure Angular app, and just let me know if the experience you have is different.

Here's how you can try out Storybook in a pure Angular app (steps copied from [this guide](https://storybook.js.org/docs/angular/get-started/install)):

1. `ng new my-app`
2. `cd my-app`
3. `npx storybook init`
4. Update your `angular.json` file to include Storybook's custom builder:
```
{
  "storybook": {
    "builder": "@storybook/angular:start-storybook",
    "options": {
      "browserTarget": "my-app:build",
      "port": 6006
    }
  },
  "build-storybook": {
    "builder": "@storybook/angular:build-storybook",
    "options": {
      "browserTarget": "my-app:build"
    }
  }
}
```
5. `ng run my-app:storybook`
