### ISSUE TITLE
how to distribute the cache manually using my own storage mechanisms

### ISSUE THREAD

**Issue by G233** [nrwl/nx#10769]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/using-nx/caching#distributed-computation-caching

### Additional context or description

how to distribute the cache manually using my own storage mechanisms?

**Comment by StalkAltan** [comment]
Hi @G233 

If you'd like to use your own storage mechanism, we have the API for Nx Cloud published at https://nx.dev/nx-cloud/reference/server-api.

Using this, you can implement a custom task runner that follows the API contracts listed on that page.

We don't really recommend this, as small issues in your task runner can cause major problems with Nx's usability, though it is technically possible.

Best of luck if you choose to go down this route!
