### ISSUE TITLE
defaultProject is missing in nx.json

### ISSUE THREAD

**Issue by iKrishnaSahu** [nrwl/nx#10766]
## Current Behavior

defaultProject field is missing in nx.json

This was working in 13.10.5

## Expected Behavior

defaultProject field should get added in nx.json

## Steps to Reproduce

1. Create new 14.3.1 workspace - `npx create-nx-workspace@14.3.1--cli=angular`
2. Install @nrwl/angular - `npm i @nrwl/angular@latest -D`
3. Generate app using `ng g @nrwl/angular:app` 

### Failure Logs

defaultProject field is missing in nx.json

### Environment

Node : 14.19.2
   OS   : win32 x64
   npm  : 6.14.17

   nx : 14.3.2
   @nrwl/angular : 14.3.5
   @nrwl/cypress : 14.3.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.2
   @nrwl/eslint-plugin-nx : 14.3.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.5
   @nrwl/js : Not Found
   @nrwl/linter : 14.3.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.3.5
   @nrwl/web : Not Found
   @nrwl/workspace : 14.3.2
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:

**Comment by AgentEnder** [comment]
It looks like I may have had some timelines mixed up. We **_are_** planning to deprecate the property, but have not done so yet. The angular generator was fixed in #10789.
