### ISSUE TITLE
Cannot find module 'nx/src/config/configuration'

### ISSUE THREAD

**Issue by Rofer11607** [nrwl/nx#10764]
## Current Behavior

I am trying to build a typescript library in my mono repo called 'crm-sdk', it fails to build with the below error

when I try an build nx build <project name> it shows the following error:

Cannot find module 'nx/src/config/configuration'
Require stack:
- /Users/goose/Documents/programming/monster/node_modules/@nrwl/js/node_modules/@nrwl/devkit/index.js
- /Users/goose/Documents/programming/monster/node_modules/@nrwl/js/src/utils/check-dependencies.js
- /Users/goose/Documents/programming/monster/node_modules/@nrwl/js/src/executors/tsc/tsc.impl.js
- /Users/goose/Documents/programming/monster/node_modules/nx/src/config/workspaces.js
- /Users/goose/Documents/programming/monster/node_modules/nx/src/command-line/run.js
- /Users/goose/Documents/programming/monster/node_modules/nx/bin/run-executor.js

## Steps to Reproduce

run nx build

### Environment

 >  NX   Report complete - copy this into the issue template

   Node : 17.7.1
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 14.1.7
   @nrwl/angular : 14.1.7
   @nrwl/cypress : 14.1.7
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.7
   @nrwl/eslint-plugin-nx : 14.1.7
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.7
   @nrwl/js : 14.2.4
   @nrwl/linter : 14.1.7
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.3.5
   @nrwl/nx-cloud : 14.0.5
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.7
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.7
   typescript : 4.6.4
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
         ngx-spinner: 13.1.1

**Comment by Rofer11607** [comment]
as a work around, If I run `npm i @nrwl/js --save-dev` it works for a while before reverting

**Comment by joewIST** [comment]
Having the same issue in @nrwl/devkit

node_modules/@nrwl/devkit/index.d.ts:18:43 - error TS2724: '"nx/src/config/workspace-json-project-json"' has no exported member named 'ProjectsConfigurations'. Did you mean 'ProjectConfiguration'?

18 export type { WorkspaceJsonConfiguration, ProjectsConfigurations, TargetDependencyConfig, TargetConfiguration, ProjectConfiguration, ProjectType, Workspace, } from 'nx/src/config/workspace-json-project-json';
                                             ~~~~~~~~~~~~~~~~~~~~~~

node_modules/@nrwl/devkit/index.d.ts:27:77 - error TS2307: Cannot find module 'nx/src/config/configuration' or its corresponding type declarations.

27 export { readNxJson, readAllWorkspaceConfiguration, workspaceLayout, } from 'nx/src/config/configuration';
                                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@nrwl/devkit/index.d.ts:176:44 - error TS2307: Cannot find module 'nx/src/utils/workspace-root' or its corresponding type declarations.

176 export { workspaceRoot, appRootPath } from 'nx/src/utils/workspace-root';
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 3 errors in the same file, starting at: node_modules/@nrwl/devkit/index.d.ts:18
