### ISSUE TITLE
getJestProjects is not taking into account targets based on project inference

### ISSUE THREAD

**Issue by maartencardinaels** [nrwl/nx#10772]
## Current Behavior
We are using the new [project inference feature ](https://nx.dev/extending-nx/project-inference-plugins)of Nx to dynamically generate targets. We use it amongst others to generalize our `test` targets in our libraries.

Furthermore, we are using [getJestProjects()](https://github.com/nrwl/nx/blob/428106f6be/packages/jest/src/utils/config/get-jest-projects.ts) in our global jest config. However, we noticed that getJestProjects() is not taking into account the projects that have a `test` target based on project inference (and that use the @nrwl/jest:jest executor and have a jest config), resulting in failures when running the tests (from within WebStorm), because these projects are not known as jest projects: 

```
No files found in <library-path>.
Make sure Jest's configuration does not exclude this directory.
To set up Jest, make sure a package.json file exists.
```

## Expected Behavior

Projects that have a `test` target based on project inference and that use the @nrwl/jest:jest executor and have a jest config should be taken into account in getJestProjects()

## Steps to Reproduce

- have a project for which the test target is generalized by using project inference
- try to run tests for this project (from within WebStorm)

### Failure Logs

```
No files found in <library-path>.
Make sure Jest's configuration does not exclude this directory.
To set up Jest, make sure a package.json file exists.
```
### Environment

 Node : 16.15.0
   OS   : win32 x64
   yarn : 1.22.15

   nx : 14.3.5
   @nrwl/angular : 14.3.5
   @nrwl/cypress : 14.3.5
   @nrwl/devkit : 14.3.5
   @nrwl/eslint-plugin-nx : 14.3.5
   @nrwl/jest : 14.3.5
   @nrwl/js : 14.3.5
   @nrwl/linter : 14.3.5
   @nrwl/node : 14.3.5
   @nrwl/nx-plugin : 14.3.5
   @nrwl/react : Not Found
   @nrwl/storybook : 14.3.5
   @nrwl/web : 14.3.5
   @nrwl/workspace : 14.3.5
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
         @auth0/auth0-angular: 1.9.0
         @cumul.io/ngx-cumulio-dashboard: 2.1.1
         @ngneat/edit-in-place: 1.6.1
         @ngneat/transloco: 4.1.0
         @ngrx/component: 13.2.0
         @ngrx/component-store: 13.2.0
         ng2-charts: 3.0.11
         single-spa-angular: 6.3.1
         @compodoc/compodoc: 1.1.19
         @ngneat/spectator: 10.0.1
         @storybook/angular: 6.5.9
         @twittwer/compodoc: 1.8.0

**Comment by jogelin** [comment]
I fixed this by [patching the function](https://www.npmjs.com/package/patch-package) `getJestConfigProjectPath`:

```patch
diff --git a/node_modules/@nrwl/jest/src/utils/config/get-jest-projects.js b/node_modules/@nrwl/jest/src/utils/config/get-jest-projects.js
index 44d2911..ff8c558 100644
--- a/node_modules/@nrwl/jest/src/utils/config/get-jest-projects.js
+++ b/node_modules/@nrwl/jest/src/utils/config/get-jest-projects.js
@@ -2,6 +2,7 @@
 Object.defineProperty(exports, "__esModule", { value: true });
 exports.getJestProjects = void 0;
 const path_1 = require("path");
+const fs = require("fs");
 const file_utils_1 = require("nx/src/project-graph/file-utils");
 const JEST_RUNNER_TOKEN = '@nrwl/jest:jest';
 function getJestConfigProjectPath(projectJestConfigPath) {
@@ -12,25 +13,12 @@ function getJestProjects() {
     const ws = (0, file_utils_1.readWorkspaceConfig)({
         format: 'nx',
     });
+
     const jestConfigurationSet = new Set();
     for (const projectConfig of Object.values(ws.projects)) {
-        if (!projectConfig.targets) {
-            continue;
-        }
-        for (const targetConfiguration of Object.values(projectConfig.targets)) {
-            if (targetConfiguration.executor !== JEST_RUNNER_TOKEN) {
-                continue;
-            }
-            if ((_a = targetConfiguration.options) === null || _a === void 0 ? void 0 : _a.jestConfig) {
-                jestConfigurationSet.add(getJestConfigProjectPath(targetConfiguration.options.jestConfig));
-            }
-            if (targetConfiguration.configurations) {
-                for (const configurationObject of Object.values(targetConfiguration.configurations)) {
-                    if (configurationObject.jestConfig) {
-                        jestConfigurationSet.add(getJestConfigProjectPath(configurationObject.jestConfig));
-                    }
-                }
-            }
+        const jestConfigPathFromRoot = `${projectConfig.root}/jest.config.ts`;
+        if (fs.existsSync(jestConfigPathFromRoot)) {
+            jestConfigurationSet.add(getJestConfigProjectPath(jestConfigPathFromRoot));
         }
     }
     return Array.from(jestConfigurationSet);
```

I am just testing that the project is containing a `jest.config.ts` file instead of testing the targets. 

This does not cover having multiple `jest.config` per project. The best solution should be to load the plugin and merge the targets but less performant IMO

@barbados-clemens

**Comment by barbados-clemens** [comment]
that is basically doing the same thing (or should be). I'll take a look here soon now that I'm back in the office. 

@AgentEnder would project inferences just stop the workspace from seeing the project targets options like this? since it's still iterating the projects so those are coming back correctly (at least via this git diff from above).
