### ISSUE TITLE
Args for the command executor no longer work after upgrade to 14.3.6 from 14.1.9 of NX

### ISSUE THREAD

**Issue by yurisim** [nrwl/nx#10787]
## Current Behavior

```
    "prisma-migrate": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "commands": [
          "env-cmd -f apps/XYZ-api/.env.local npx prisma db push --accept-data-loss --force-reset",
          "env-cmd -f apps/XYZ-api/.env.local yarn ts-node ./apps/XYZ-api/prisma-seed.ts"
        ],
        "schema": "apps/XYZ-api/schema.prisma",
        "parallel": false
      },
```

The command above gives the error

```
Error: Could not find a schema.prisma file that is required for this command.
You can either provide it with --schema, set it as `prisma.schema` in your package.json or put it into the default location ./prisma/schema.prisma https://pris.ly/d/prisma-schema-location
ERROR: Something went wrong in run-commands - Command failed: env-cmd -f apps/XYZ-api/.env.local npx prisma db push --accept-data-loss --force-reset
```

## Expected Behavior

I could fix the above "error" by adding the schema attribute to each of the commands like
```
env-cmd -f apps/XYZ-api/.env.local npx prisma db push --accept-data-loss --force-reset --schema=apps/XYZ-api/schema.prisma
```

but the previous version of NX i was using (14.1.9) was running the first code block just fine. I don't think it has anything to do with Prisma, the options command no longer seems to work like it did. 

I can't even find a [reference for how I thought it previously worked](https://nx.dev/packages/nx/executors/run-commands).

## Steps to Reproduce
I'm not sure this is as much of a bug as much as it is a "There's a breaking API change whose documentation I can't find."

### Failure Logs
```
Error: Could not find a schema.prisma file that is required for this command.
You can either provide it with --schema, set it as `prisma.schema` in your package.json or put it into the default location ./prisma/schema.prisma https://pris.ly/d/prisma-schema-location
ERROR: Something went wrong in run-commands - Command failed: env-cmd -f apps/XYZ-api/.env.local npx prisma db push --accept-data-loss --force-reset
```

### Environment
```
Node : 16.14.0
   OS   : win32 x64
   yarn : 1.22.18
   
   nx : 14.3.6
   @nrwl/angular : 14.3.6
   @nrwl/cypress : 14.3.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : 14.3.6
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.6
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.3.6
   @nrwl/nest : 14.3.6
   @nrwl/next : Not Found
   @nrwl/node : 14.3.6
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.3.6
   @nrwl/web : 14.3.6
   @nrwl/workspace : 14.3.6
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
         apollo-angular: 3.0.1
```

**Comment by AgentEnder** [comment]
Is seems like the "schema" option in your target block was getting passed previously, that was an undefined behaviour that may have been impacted by some changes recently.

I'd recommend adding the --schema param manually to the commands, since this was an undefined behavior we will probably not attempt to restore it.

**Comment by Brian-McBride** [comment]
Seems like a fix is coming? 

```
/bin/sh: line 0: pwd: --: invalid option
pwd: usage: pwd [-LP]
[graphql-codegen-zod] ❌ Error: ERROR: Something went wrong in run-commands - Command failed: pwd --color=true --parallel=false
```

In my case, I have more complexity which worked before my last Nx update. I'm using a community plugin `@jscutlery/semver:version` to handle versioning. But, things were working before. 

For instance, a follow-up project target is: 
```
      "github": {
        "executor": "@jscutlery/semver:github",
        "options": {
          "tag": "${tag}",
          "notes": "${notes}"
      }
    },
```

**Comment by Phault** [comment]
> Seems like a fix is coming?
> 
> ```
> /bin/sh: line 0: pwd: --: invalid option
> pwd: usage: pwd [-LP]
> [graphql-codegen-zod] ❌ Error: ERROR: Something went wrong in run-commands - Command failed: pwd --color=true --parallel=false
> ```
> 
> In my case, I have more complexity which worked before my last Nx update. I'm using a community plugin `@jscutlery/semver:version` to handle versioning. But, things were working before.
> 
> For instance, a follow-up project target is:
> 
> ```
>       "github": {
>         "executor": "@jscutlery/semver:github",
>         "options": {
>           "tag": "${tag}",
>           "notes": "${notes}"
>       }
>     },
> ```

@Brian-McBride You're experiencing a different issue, see https://github.com/nrwl/nx/issues/11382 for details. You can disable `forwardAllArgs` to work around it.
