### ISSUE TITLE
Run commands executor showing Missing property "__unparsed__" error in IDE

### ISSUE THREAD

**Issue by utsavkapoor** [nrwl/nx#10780]
## Current Behavior
Run commands executor in IDE (VSCode) shows Missing property "__unparsed__" error

## Expected Behavior
Since this is an internal property, the error should not show up

## Steps to Reproduce
Upgrade to 14.3.5,
Open project.json file with run-command executors in VSCode
Attaching IDE Screenshot
![Screen Shot 2022-06-16 at 11 19 37 AM](https://user-images.githubusercontent.com/26679878/174140318-1a84d79a-5a0e-49b1-a956-aa4e72b5dc52.png)

**Comment by dolphinigle** [comment]
Supposed to be closed with this issue: https://github.com/nrwl/nx/issues/10750 but:

![Screenshot (16)](https://user-images.githubusercontent.com/7020472/174435382-625879a9-4763-4975-8b12-00edbbfece3c.png)

**Comment by rodrigomata** [comment]
I also have this problem because `__unparsed__` is a required field that shouldn't be a required one. I think this is also breaking additional flags not to be set on some scripts
