### ISSUE TITLE
I can't see gitlab ci docs

### ISSUE THREAD

**Issue by gustawdaniel** [nrwl/nx#10790]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ x ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/using-nx/ci-overview

### Additional context or description

I would like to read about GitLab ci integration.

**Comment by rubiagatra** [comment]
this should be closed https://nx.dev/using-nx/ci-overview @AgentEnder
