### ISSUE TITLE
nx migrate latest removes defaultCollection from nx.json

### ISSUE THREAD

**Issue by sandeeppatidar30** [nrwl/nx#10792]
`nx migrate latest` command removes defaultCollection from nx.json. which creates breaking change for us.

## Current Behavior

`nx migrate latest` command removes defaultCollection from nx.json.

## Expected Behavior

It should not remove defaultCollection from nx.json.

## Steps to Reproduce

1. Run nx migrate latest
2. Check nx.json 

### Environment
Windows 10
Node 14.22

**Comment by AgentEnder** [comment]
This is expected behavior, as we changed the way we handle default collections recently. Can you explain how it is a breaking change for your use case?

Currently, you can just add it back but the property is deprecated and support may be removed in v15.
