### ISSUE TITLE
DataPersistence navigation doesn't fire 'run' callback

### ISSUE THREAD

**Issue by WJChai** [nrwl/nx#108]
Hi, I couldn't make DataPersistence.navigation() working.

repro:
1. curl -fsSL https://raw.githubusercontent.com/nrwl/nx/master/packages/install/install.sh | bash -s myprojectname
2. ng generate app myapp
3. ng generate ngrx app --module=apps/myapp/src/app/app.module.ts  --root
4. add following to app.effects.ts
@Effect()
  loadData = this.d.navigation(AppComponent, {
    run: (a, state) => {
      console.log('ran')
      return {
        type: 'DATA_LOADED',
        payload: {}
      };
    },

    onError: (a, error) => {
      console.error('Error', error);
    }
  });

Is there any additional setup needed? I couldn't find more detailed docs on web. Thanks!

**Comment by jschwarty** [comment]
The `AppComponent` isn't something that gets routed to, so an action doesn't come through for that. If you use `navigation` with a component that is used in a route config it will receive the action in the effect.

**Comment by WJChai** [comment]
Hi, thank you for reply.
However, I just used AppComponent for simplicity sake.
Even if I setup as following:
1. curl -fsSL https://raw.githubusercontent.com/nrwl/nx/master/packages/install/install.sh | bash -s myprojectname
2. ng generate app myapp
3. ng generate ngrx app --module=apps/myapp/src/app/app.module.ts --root
4. ng g component data-navigation --app=myapp
5. add <router-outlet></router-outlet> to app.component.html
6.  add RouterModule.forRoot([
      {path: 'nav', component: DataNavigationComponent}
    ]) to app.module.ts
7. add @Effect()
  loadData = this.d.navigation(DataNavigationComponent, {
    run: (a, state) => {
      console.log('ran');
      return {
        type: 'DATA_LOADED',
        payload: {}
      };
    },

    onError: (a, error) => {
      console.error('Error', error);
    }
  }); to app.effects.ts
8. navigate to 'localhost:4200/nav'

It still won't log 'ran' in console and no action dispatched seen in Redux DevTools chrome extensions.

Sorry for not making my question clear.

Besides that, as you mentioned AppComponent won't trigger DataPersistence.navigation callback, how can I setup if I wish to call a function whenever the app is initialized/bootstrap-ed(using DataPersistence.navigation?

**Comment by jschwarty** [comment]
Ah, I bet you need the `StoreRouterConnectingModule` to be added to your imports for the NgModule. I don't think that gets added with the Nx schematics. Check if that is what is missing for your code to work and let me know. If so, we will take a look at how we might be able to work that into the schematics workflow (we might need to add that to the ngrx schematic with the --root flag).

**Comment by WJChai** [comment]
Yea StoreRouterConnectingModule is needed to make it works.
I tried to submit a pull request but not sure whether I've done it right, first time doing this haha.

Thanks for your help! =)
