### ISSUE TITLE
Nx 14.2 migration fails w/ "Cannot find module './util/canReportError'"

### ISSUE THREAD

**Issue by LMFinney** [nrwl/nx#10801]
## Current Behavior

I ran `nx migrate --run-migrations --create-commits` on my Angular 13 app. Several of the migrations worked successfully, but then it failed when it hit Angular's migration-entry-components:
![image](https://user-images.githubusercontent.com/6683747/174405817-0d464cde-53fc-4579-8326-2b44b5c4b68b.png)

I manually made the relevant changes and tried again, but then I got the identical error with the "migration-v14-typed-forms" migration. I stopped at that point.

## Expected Behavior

I expected the migration to work like the other migrations do. I have never tried this migration before.

## Steps to Reproduce

Unfortunately, I don't know what is special about my repo that is causing the failure that apparently hasn't been true of other repos that haven't had this problem.

### Environment

 >  NX   Report complete - copy this into the issue template

   Node : 14.18.1
   OS   : win32 x64
   yarn : 1.22.5

   nx : 14.3.6
   @nrwl/angular : 14.3.6
   @nrwl/cypress : 14.3.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : 14.3.6
   ---------------------------------------
   Community plugins:
         @ngrx/effects: 13.2.0
         @ngrx/entity: 13.2.0
         @ngrx/router-store: 13.2.0
         @ngrx/schematics: 13.2.0
         @ngrx/store: 13.2.0
         @ngrx/store-devtools: 13.2.0
         single-spa-angular: 6.3.0
         @compodoc/compodoc: 1.1.19
         @storybook/angular: 6.5.9

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Could you run the migrations with the `--verbose` flag and share the output here? Maybe we get a little bit more info with that.

**Comment by LMFinney** [comment]
When I returned to that branch and added the `--verbose` flag, the migration completed without incident. I don't know what's different compared to before besides the tag.

Since I can't reproduce my own report, I'm closing this.

Thanks
