### ISSUE TITLE
Duplicate npm install on nx migrate

### ISSUE THREAD

**Issue by wiesnery** [nrwl/nx#10813]
## Current Behavior
run `nx migrate latest`

Nx output:

> - Make sure package.json changes make sense and then run 'npm install'
> - Run 'npx nx migrate --run-migrations'
> - To learn more go to https://nx.dev/using-nx/updating-nx

I run `npm install` --- wait 5 minutes until completed ---
I run `npx nx migrate --run-migrations` it runs `npm install` again

## Expected Behavior
No duplicate `npm install` runs as these are expensive for large projects.

- Either remove the hint to run npm install
- Or remove the npm install in the migration step

## Steps to Reproduce
Initiate a repo with nx with a non-latest version.

### Environment

 >  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : darwin x64
   npm  : 8.10.0
   
   nx : 14.3.6
   @nrwl/angular : 14.3.6
   @nrwl/cypress : 14.3.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : 14.3.6
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.6
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.3.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.1.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.3.6
   @nrwl/web : 14.3.6
   @nrwl/workspace : 14.3.6
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:

**Comment by FrozenPandaz** [comment]
This was added in order to prevent users from running migrations before they had installed the new version.

If you'd like to skip this, you can pass `NX_MIGRATE_SKIP_INSTALL=true` as an environment variable.
