### ISSUE TITLE
TypeScript library not being transpiled when imported from app project

### ISSUE THREAD

**Issue by Lusito** [nrwl/nx#10819]
Originally posted in #10584, as I thought it was the same issue:

## Current Behavior
When importing a typescript library (in the same monorepo) from an app project using "executor": "@nrwl/web:webpack", an error is thrown:

```
ERROR in ../repro-lib/src/index.ts
Module build failed (from ../../node_modules/@nrwl/web/src/utils/web-babel-loader.js):
SyntaxError: /home/lusito/Code/typescript/repro/packages/repro-lib/src/index.ts: Support for the experimental syntax 'flow' isn't currently enabled (3:8):

  1 | export class Repro {}
  2 |
> 3 | export type Second = {
    |        ^
  4 |     repro: Repro;
  5 | };
  6 |
```

Using "executor": "@nrwl/node:webpack" works perfectly fine, but I need it to work with web:webpack..

## Expected Behavior
TypeScript is transpiled correctly and no error is thrown.

## Steps to Reproduce

Here is the smallest reproduction I could make:
https://github.com/Lusito/nx-import-type-repro

### Environment

```
>  NX   Report complete - copy this into the issue template

   Node : 18.1.0
   OS   : linux x64
   npm  : 8.8.0
   
   nx : 14.3.6
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.3.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.6
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.3.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.3.6
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 14.3.6
   @nrwl/workspace : 14.3.6
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
```

**Comment by AgentEnder** [comment]
There's not a generic scope for web, and the people that maintain the roll-up executor look at the react scope.

**Comment by Lusito** [comment]
Ah, okay. Thanks for the clarification.

**Comment by janewang** [comment]
+1 for us

**Comment by marcputs** [comment]
I hit the same issue as well. The issue below put me on the right track, as I think it's the same issue:
https://github.com/nrwl/nx/issues/8943

When I copy the .babelrc file from the app to the lib, the app will build succesfully.

I believe it has to do with Project-wide vs File-relative babel config files, as documented in Babel's official docs. There's a special mention of caveats in Monorepos:
https://babeljs.io/docs/en/config-files#project-wide-configuration

**Comment by marcputs** [comment]
I found the solution in #3184.

I added `"presets": ["@nrwl/web/babel"]` to the `babel.config.json` file in the monorepo root, and the issue has been solved.

**Comment by Lusito** [comment]
@marcputs Your second comment with the babel.config.json seems to work for me. The first one, with the .babelrc file does nothing at all.

I'm not sure though if this has any side-effects on the other projects in my repository.

Aside from that, this seems like a workaround and still should be working without these changes, right?

**Comment by srn271** [comment]
> When I copy the .babelrc file from the app to the lib, the app will build succesfully.
> I added "presets": ["@nrwl/web/babel"] to the babel.config.json file in the monorepo root, and the issue has been solved.

Nothing worked for me.

Here is my smallest reproduction i could make:
https://github.com/srn271/nx-test-workspace

I am encountering this error in a react-native project.

**Comment by marcputs** [comment]
> Aside from that, this seems like a workaround and still should be working without these changes, right?

@Lusito I'm not sure if it's a workaround or the actual fix. It's possible that this exact change should be added to the generator from `@nrwl/web`. But as I only have a few days of hands-on experience with nx and no prior monorepo knowledge, I can't say for sure.

**Comment by diginikkari** [comment]
I had the same issue when using lib build with `@nrwl/js:swc` and building storybook. For me adding `.babelrc` file with `{"presets": ["@nrwl/web/babel"]}` content to root of the `@nrwl/js:swc` builded lib fixed the issue.

**Comment by VictorJozwicki** [comment]
> I found the solution in #3184.
> 
> I added `"presets": ["@nrwl/web/babel"]` to the `babel.config.json` file in the monorepo root, and the issue has been solved.

Fixed it for me. I had a React app that used a TS Lib and it couldn't understand the TS `Unexpected token, expected "," `

**Comment by B-R-Bender** [comment]
did you guys using any of jetbrains IDE?
I could assume there is a language level set to flow instead of ts for you repo

**Comment by exsesx** [comment]
+1, same issue. I have a shared constants TypeScript library, used by the frontend React app and Node.js backend, stuck on building the frontend, getting the error:

```
Module parse failed: Unexpected token (1:7)
You may need an appropriate loader to handle this file type...
```

**Comment by ossamaweb** [comment]
hey @exsesx did you solve your issue?

**Comment by ossamaweb** [comment]
Thanks, @exsesx
That's what I ended up doing. But I was hoping to upgrade NX to the latest, maybe when I have a clearer mind ;)

**Comment by kuzaxak** [comment]
Keep in mind that by default buildable libraries are compiled from source.

https://github.com/nrwl/nx/commit/fa67518

**Comment by win-ly** [comment]
> `@nrwl/js:swc`在使用 lib build和构建 Storybook时，我遇到了同样的问题。对我来说，将`.babelrc`包含内容的文件添加`{"presets": ["@nrwl/web/babel"]}`到构建的库的根目录`@nrwl/js:swc`解决了这个问题。

May I ask if you solved it? I'm trying to upgrade storybook from 6.x.x to 7.x.x and I'm experiencing the same problem.

**Comment by mandarini** [comment]
This issue is quite old, and the `@nrwl/web:webpack` executor does not exist any more. If this issue still exists in some way or another, please can you create a new issue with a reproduction repository? It will be very helpful for us to see what's happening there. But please, first, retry with latest, since, as I said, these executors do not really exist any more, or exist in a different way.
