### ISSUE TITLE
Nx and Typescript Tutorial Cannot Be Completed

### ISSUE THREAD

**Issue by mikecann** [nrwl/nx#10810]
### Documentation issue

- [ ] Reporting a typo
- [ x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/getting-started/nx-and-typescript#create-a-typescript-based-application

### Additional context or description

This is the very first thing that a new user will experience with Nx and it doesnt work. When you get to the section "Create a TypeScript based application" it asks you to:

```
nx generate @nrwl/node:app demoapp
```

This errors:

```
 # nx generate @nrwl/node:app demoapp
Unable to resolve @nrwl/node:app.
Cannot find module '@nrwl/node'
Require stack:
- C:\dev\gangbusters\battletabs-nx\node_modules\nx\src\utils\package-json.js
- C:\dev\gangbusters\battletabs-nx\node_modules\nx\src\utils\package-manager.js
- C:\dev\gangbusters\battletabs-nx\node_modules\nx\bin\init-local.js
- C:\dev\gangbusters\battletabs-nx\node_modules\nx\bin\nx.js
- C:\Users\mikec\AppData\Local\Yarn\Data\global\node_modules\nx\bin\nx.js
```

Same goes for the other example:

```
 # nx generate @nrwl/web:app demoapp
Unable to resolve @nrwl/web:app.
Cannot find module '@nrwl/web'
Require stack:
- C:\dev\gangbusters\battletabs-nx\node_modules\nx\src\utils\package-json.js
- C:\dev\gangbusters\battletabs-nx\node_modules\nx\src\utils\package-manager.js
- C:\dev\gangbusters\battletabs-nx\node_modules\nx\bin\init-local.js
- C:\dev\gangbusters\battletabs-nx\node_modules\nx\bin\nx.js
- C:\Users\mikec\AppData\Local\Yarn\Data\global\node_modules\nx\bin\nx.js
```

**Comment by mikecann** [comment]
Ahh okay! Thats quite the gotcha. Yes something should be added for that, ill see what I can do

**Comment by isaacplmann** [comment]
The PR fixing this was merged
