### ISSUE TITLE
Update typescript-eslint peer dependency to 5.28

### ISSUE THREAD

**Issue by nzacca** [nrwl/nx#10821]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
We would like to see the `typescript-eslint` peer dependency updated to at least `5.28` which allows support for Typescript 4.7.

References:
* Current peer dependency: https://github.com/nrwl/nx/blob/master/packages/eslint-plugin-nx/package.json#L26
* Typescript-eslint support: https://github.com/typescript-eslint/typescript-eslint/tree/v5.28.0#supported-typescript-version

## Motivation
Angular 14 (now supported by Nx 14) uses Typescript 4.7. This causes an issue with `typescript-eslint` 5.24 which is a peer dependency of the `eslint-plugin-nx` package. We are now receiving the following warnings when linting:

```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.7.0

YOUR TYPESCRIPT VERSION: 4.7.4

Please only submit bug reports when using the officially supported version.

=============
```

## Suggested Implementation
Update the peer dependency of `eslint-plugin-nx` to at least 5.28.

**Comment by AgentEnder** [comment]
This was fixed by #10668
