### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'constructor')

### ISSUE THREAD

**Issue by makhataibar** [nrwl/nx#10824]
## Current Behavior
<img width="1103" alt="Screen Shot 2022-06-21 at 08 39 47" src="https://user-images.githubusercontent.com/27006656/174704841-3fdc7418-543a-430c-8ab6-3986edc10537.png">

50/50 in ci/cd pipeline (gitlab) build with @nrwl/expo break but nx think build is succesfull

## Expected Behavior
1. Successful build
2. If can't build throw error

## Steps to Reproduce
@nrwl/expo build-web

**Comment by AgentEnder** [comment]
What's `nx report` say?

**Comment by makhataibar** [comment]
>  NX   Report complete - copy this into the issue template

   Node : 16.14.1
   OS   : darwin arm64
   yarn : 1.22.18
   
   nx : 14.1.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.0.5
   @nrwl/detox : 14.0.5
   @nrwl/devkit : 14.0.5
   @nrwl/eslint-plugin-nx : 14.0.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.5
   @nrwl/js : 14.0.1
   @nrwl/linter : 14.0.5
   @nrwl/nest : Not Found
   @nrwl/next : 14.0.5
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.0.5
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.0.5
   @nrwl/web : 14.0.5
   @nrwl/workspace : 14.0.5
   typescript : 4.3.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         @nrwl/expo: 14.1.1

**Comment by AgentEnder** [comment]
Hey @makhataibar, it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

**Comment by xiongemi** [comment]
i tried with my expo with `nx build-web` with my expo repo, it seems fine. maybe try to upgrade nx package.

**Comment by xiongemi** [comment]
@makhataibar i think you might have a version mismatch. nx should be the same version as the rest of @nrwl/* libraries. close this issue for now.
