### ISSUE TITLE
Can't find libraries when running Jest tests

### ISSUE THREAD

**Issue by jberrydev** [nrwl/nx#10825]
## Current Behavior
After updating to the latest via migrate I am unable to run Jest unit tests as it doesn't seem to be able to resolve my nx libraries.  Similar to this issue: https://stackoverflow.com/questions/72606965/testing-with-nx-jest-and-angular-cant-find-library-when-running-tests

## Expected Behavior
Should be able to run Jest tests when using nx libraries.

### Failure Logs
 Cannot find module '@org/shared:ui' from 'src/header/header.tsx'

### Environment
```
    "next": "^12.1.5",
    "@nrwl/cypress": "14.3.1",
    "@nrwl/eslint-plugin-nx": "14.3.1",
    "@nrwl/jest": "14.3.1",
    "@nrwl/js": "14.3.1",
    "@nrwl/linter": "14.3.1",
    "@nrwl/next": "14.3.1",
    "@nrwl/node": "14.3.1",
    "@nrwl/react": "14.3.1",
    "@nrwl/storybook": "14.3.1",
    "@nrwl/tao": "14.3.1",
    "@nrwl/web": "14.3.1",
    "@nrwl/workspace": "14.3.1",
    "jest": "^28.1.1",
    "jest-environment-jsdom": "^28.1.1",
```

**Comment by jberrydev** [comment]
@AgentEnder So my setup is create a Util library, Feature Library, and an App.  Have the Feature library use a function from the  Util library.  Write a jest unit test in the Feature library for the item that uses the Util library.  You should get Cannot find module error.  I am sure this may  be just some configuration or something I am missing, but have tried everything I know and can't write unit tests for libraries that use other libs

**Comment by marckassay** [comment]
@jberrydev This seems to be the same issue as mentioned in 'nxext/nx-extensions' issue #[688](https://github.com/nxext/nx-extensions/issues/688).

It seems to be a Jest issue.

**Comment by jberrydev** [comment]
@marckassay ok, I will try this and post back.

**Comment by marckassay** [comment]
@jberrydev The repo link by the author in the 'nxext/nx-extensions' issue I mentioned above, I'm now able to achieve his objective. By the way, that repo has multi branches, so I'm not sure where he left off. In addition to Jest's `moduleNameMapper` being set, set a `paths` entry to the Nx library's index.ts file in tsconfig.base.json, and have 2 sets of TS config files in the Nx project being tested; tsconfig.lib.json and tsconfig.spec.json. For the 'tsconfig.lib.json' file, I added a glob pattern entry in the `includes` array that is a relative path to the library's src folder (eg: "../hello-tsc/src/**/*").

Anyways, yeah post back. ;)

**Comment by jberrydev** [comment]
@marckassay so which config should I be updating.  I am not using stencil and only using NX to generate my libraries and apps.  I assume adding the moduleNameMapper to the lib that is using the local library? NX generates at jest.config.js.  I have tried using this, but it can't seem to find modules outside of or the <rootDir>

**Comment by wangzishi** [comment]
I had almost the same problem, jest reported an error when running the test that `Cannot find module '@myorg/mylib' from 'src/lib/foo.ts`

**Comment by jberrydev** [comment]
@wangzishi I think the jest.config.js at root basically grabs the jest projects, but not sure it is working.  Basically anybody having this issue you must basically add all of your library dependencies to the moduleNameMapper to their folder locations and you must use <rootDir>.  If you have images and such you may have to also add the file mock and image modules.  Again this was all after a migrate to latest.

**Comment by marckassay** [comment]
@wangzishi It's for Nx projects, if needed, to "extend" from that use Jest. Similar to tsconfig.base.json files in relation to sub-projects that use TypeScript. However, I never used it or confirmed that `getJestProjects()` is working as expected. See [here](https://stackoverflow.com/a/42236602/648789) for short discussion.

**Comment by marckassay** [comment]
@jberrydev To answer your question:

> ... is the above expected of the developer for every library and app to configure jest when adding libs and modules?

You can utilize what @wangzishi questioned. In short, move `moduleNameMapper` to the workspace jest.config.ts file. And `import` and spread the root Jest config object in the Nx project's Jest file:

```typescript
// ./libs/nx-project/jest.config.ts
import jestConfig  from '../../jest.config';

export default {
  ...jestConfig,
  // other project specific properties if any listed below
}
```

Perhaps that will reduce maintenance. As for if this is a new issue or Nx development team should resolve this, I don't know enough about historical development in this context of Node JS ecosystem to answer that.

**Comment by jberrydev** [comment]
@marckassay Understood.  I just feel I shouldn't have to be doing this.  The issue for me though is that my lib directories are 3 levels deep and my apps are only 2, so I can't put the paths at the top level.  At least I am getting errors when doing it at the top level assuming that is the issue.  Thanks for the help everyone.  Hopefully this helps others.

**Comment by marckassay** [comment]
@jberrydev I just came across closed issue #10660, take note of [this](https://github.com/nrwl/nx/issues/10660#issuecomment-1152366240) comment. Not sure if that fix got deployed in the build you're using or is even the same issue.

**Comment by wangzishi** [comment]
I found that the issue I was having was related to esm.

When it was declared as esm
```jsonc
// root/package.json
{
  "type": "module"
}
```

I must set `moduleNameMapper` in `jest.preset.js` to solve the problem.
```js
// root/jest.preset.js
import nxPreset from '@nrwl/jest/preset/index.js';

export default {
  ...nxPreset,
  moduleNameMapper: { '^@sheencity/(.*)$': '<rootDir>/../$1/src/index.ts' },
};
```

When js files treated as commonjs
```js
// root/jest.preset.js
const nxPreset = require('@nrwl/jest/preset');

module.exports = {
  ...nxPreset,
}
```
Everything works again. Looks like nxPreset only works in commonjs.

**Comment by KamalAman** [comment]
Experiencing the same issue after updating. 

I resolved it be padding a moduleNameMapper fixed at the `cwd`

`jest.preset.js`

```js
const nxPreset = require('@nrwl/jest/preset');
const { pathsToModuleNameMapper } = require('ts-jest/utils');
const { compilerOptions } = require('./tsconfig.base.json');

module.exports = {
  ...nxPreset,
  testEnvironment: 'jsdom',
  transform: {
    '\\.(gql|graphql)$': 'jest-transform-graphql',
    '.*': 'babel-jest',
  },
  moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, {
    prefix: process.cwd()
  })
};
```

It seems like moduleNameMapper should be a part of the `@nrwl/jest/preset` in the first place.
When troubleshooting it seems like imports are being done relative to each lib

**Comment by marckassay** [comment]
@KamalAman that solution seems to be best! Thanks for sharing.

**Comment by ivan114** [comment]
I modified the preset from @KamalAman a little bit as the config crashing when there is JSON file in the project, and this config works for my nodejs test

```js
const nxPreset = require('@nrwl/jest/preset');
const { pathsToModuleNameMapper } = require('ts-jest');
const { compilerOptions } = require('./tsconfig.base.json');

module.exports = {
  ...nxPreset,
  testEnvironment: 'node',
  transform: {
    '^.+\\.(ts|tsx)$': 'ts-jest',
  },
  moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, {
    prefix: process.cwd(),
  }),
};
```

**Comment by saitodisse** [comment]
The @KamalAman solution works.
- Why this happened after upgrading nx.dev / jest?
- Should nx.dev includes this code on all generated tests?

**Comment by barbados-clemens** [comment]
looks like y'all might have overridden the resolver which removed the nrwl/jest resolver which finds your other local packages in your workspace through tspaths. 

you shouldn't need a moduleNamedMapper unless you're wanting to point to a different file for a given name such as d3 pointing to the min.js version.

**Comment by KamalAman** [comment]
@barbados-clemens please clarify how we all can see how the `resolver`  for speficying the `nrwl/jest resolver`  can be overwritten? 

I dont have anything special in my configuration. I am not overriding anyhting.

```
const nxPreset = require('@nrwl/jest/preset');
const { pathsToModuleNameMapper } = require('ts-jest');
const { compilerOptions } = require('./tsconfig.base.json');

module.exports = {
  ...nxPreset,
  testEnvironment: 'node',
  transform: {
    '^.+\\.(ts|tsx)$': 'ts-jest',
  },
  moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, {
    prefix: process.cwd(),
  }),
};
```

With `moduleNameMapper` it works, without it, it does not work.

**Comment by barbados-clemens** [comment]
if you're using nx v14+ then you'll need to update your preset import to 
```diff
- const nxPreset = require('@nrwl/jest/preset');
+ const nxPreset = require('@nrwl/jest/preset').default;
```
the nx preset contains a path to the nx resolver. 

on a side note, I ran into this with babel-jest for jest 28, where the fix is to include in the babel-jest transform options. 

```diff
- '^.+\\.[tj]sx?$': 'babel-jest',
+ '^.+\\.[tj]sx?$': ['babel-jest', { presets: ['@nrwl/next/babel'] }],
```

but that's not relevant here, just a note for anyone else coming to this issue and wanting other stuff to try.

**Comment by jarodsim** [comment]
> se você estiver usando o nx v14+, precisará atualizar sua importação predefinida para
> 
> ```diff
> - const nxPreset = require('@nrwl/jest/preset');
> + const nxPreset = require('@nrwl/jest/preset').default;
> ```
> 
> a predefinição nx contém um caminho para o resolvedor nx.
> 
> em uma nota lateral, encontrei isso com babel-jest para jest 28, onde a correção é incluir nas opções de transformação babel-jest.
> 
> ```diff
> - '^.+\\.[tj]sx?$': 'babel-jest',
> + '^.+\\.[tj]sx?$': ['babel-jest', { presets: ['@nrwl/next/babel'] }],
> ```
> 
> mas isso não é relevante aqui, apenas uma nota para qualquer pessoa que venha a este problema e queira tentar outras coisas.

Hello, with the const nxPreset = require('@nrwl/jest/preset').default; I can't run the coverage test. Can you help me? It ignores the settings it puts in to collect test coverage


`export default {
  displayName: 'myapp',
  preset: '../../jest.preset.js',
  transform: {
    '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': '@nrwl/react/plugins/jest',
    '^.+\\.[tj]sx?$': ['babel-jest', { presets: ['@nrwl/next/babel'] }],
  },
  globals: {
    window: {},
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  coverageDirectory: '../../coverage/apps/myapp',
  collectCoverage: true,
  testPathIgnorePatterns: ['/node_modules/'],
  collectCoverageFrom: [
    '**/*.{ts, tsx}',
    '!**/node_modules/**',
    '!**/vendor/**',
    '!**/*.d.ts',
    '!**/*.config.ts',
  ],
  testMatch: ['**/*.spec.ts'],
};`

**Comment by KamalAman** [comment]
It seems like `+ '^.+\\.[tj]sx?$': ['babel-jest', { presets: ['@nrwl/next/babel'] }],` did the trick

**Comment by JacobPotter** [comment]
I have tried the changes to` jest.preset.js` with no luck, on "@nrwl/jest": "14.5.4",
