### ISSUE TITLE
Entity interface should be named 'what it is' for any given store

### ISSUE THREAD

**Issue by nhhockeyplayer** [nrwl/nx#10845]
SUBJECT: add option to name the Entity interface

## Description

an option ( or better yet automate it silently) to name the Entity interface specific to the name of the store

## Motivation

its preventing fluid coding after adding multiple NgRX state/stores...developer has to backpedal and rename interfaces to keep them unique from colliding

all are generated with name Entity 
when if you create an spinner ngrx store, it should be called SpinnerEntity (if I am wrong please advise)

Example... this is what gets generated after

`nx g @nrwl/angular:ngrx spinner --module=libs/shared/root/data-access/src/lib/shared-root-data-access.module.ts --directory +state/spinner --facade  --syntax=classes --no-interactive`

```
/**
 * Interface for the 'Spinner' data used in
 *  - SpinnerState, and the reducer function
 *
 *  Note: replace if already defined in another module
 */
export interface Entity {
    id: string;
    name: string;
}
```

The fact that there is a note in the generated code means someone knows about this
But it should be automated not left to user to instrument and mangle... everything else is generated why not this?

Now if I add stores for APP, AUTH, USER and so on within same module they all collide because each store has Entity for its interface

Be nice to see this automated without having an option would be best way

this should have been automated from get go

Thanks for an awesome elite product

```
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : darwin x64
   yarn : 1.22.18
   
   nx : 14.3.6
   @nrwl/angular : 14.3.6
   @nrwl/cypress : 14.3.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : 14.3.6
   @nrwl/express : 14.3.6
   @nrwl/jest : 14.3.6
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.3.6
   @nrwl/nest : 14.3.6
   @nrwl/next : Not Found
   @nrwl/node : 14.3.6
   @nrwl/nx-cloud : 14.1.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : 8.12.11
   @nrwl/storybook : 14.3.6
   @nrwl/web : 14.3.6
   @nrwl/workspace : 14.3.6
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
   	 @fortawesome/angular-fontawesome: 0.11.1
   	 @ionic/angular: 6.1.10
   	 @ngrx/component-store: 14.0.0
   	 @ngrx/effects: 14.0.0
   	 @ngrx/entity: 14.0.0
   	 @ngrx/router-store: 14.0.0
   	 @ngrx/store: 14.0.0
   	 @nxtend/capacitor: 13.0.0
   	 @nxtend/ionic-angular: 13.1.0
   	 @storybook/angular: 6.5.9
   	 angular-builder-custom-terser-options: 1.0.1
   	 @ngrx/schematics: 14.0.0
   	 @ngrx/store-devtools: 14.0.0
   	 @nxpm/stack: 4.21.0
   	 @nxtend/capacitor: 13.0.0
   	 @storybook/angular: 6.5.9
```

**Comment by Coly010** [comment]
Entity suffix is fine, it matches the creator syntax and it matches the pattern of NgRx Entity already.

I’ve a PR that adds the name of the Entity to the start of the interface name. This should suffice. Unfortunately we can’t control what other interfaces and models are named within user codebases so there’s only so much we can do. 

Typescript and JavaScript offer solutions to circumvent name clashes in imports, so there are additional workarounds that can be used if needed.

**Comment by nhhockeyplayer** [comment]
well these are obvious enough for minimal baseline harmless intent and will fly easy

here is another...
say we have an Auth ngrx store

what Im seeing is that the `AuthPartialState` is the generated code for consumers to inject into constructors.
```
export interface AuthPartialState {
    readonly [AUTH_FEATURE_KEY]: AuthState;
}
```

what would make tons of sense to the developer consuming this code is that is be named AuthStore

and I use it in my code as follows

```
    constructor(private authStore: Store<AuthPartialState>) {
        this.authStore.dispatch(new usersActions.Find())),
    }
```

Store is already specified as generic but I feel it could be better as AuthStore instead ofAuthPartialState (confusing... what is it?)
```
    constructor(private authStore: Store<AuthStore>) {
        this.authStore.dispatch(new usersActions.Find())),
    }
```

just call it what it is...

Im glad Nx team does not go as far as naming their stuff like the yarn folks... berry, canary... 
Team has done a phenomenal job though I preferred the simpler initial version of NgRX

Thanks !

**Comment by nhhockeyplayer** [comment]
https://github.com/nrwl/nx/issues/10879

**Comment by nhhockeyplayer** [comment]
well the naming collisions continue to grow
and this can be nipped in the code generation from the schematic

I added a bunch of stores... into a shared root library
all my ngrx stores have an initialState variable

and that needs to have the NAME OF THE STORE pre-pended to it to avoid multiple naming collisions after code is generated. Otherwise we need to double back and refactor and its not fun.

If this can be finally resolved it would be highly appropriate

`TS2308: Module './lib/+state/user/user.actions' has already exported a member named 'Update'. Consider explicitly re-exporting to resolve the ambiguity.`

In fact all of whats exported is colliding inside my barrel file

```
TS2308: Module './lib/+state/users/users.reducer' has already exported a member named 'initialState'. Consider explicitly re-exporting to resolve the ambiguity.
TS2308: Module './lib/+state/users/users.reducer' has already exported a member named 'reducer'. Consider explicitly re-exporting to resolve the ambiguity.
```

thanks for helping get this right

**Comment by nhhockeyplayer** [comment]
```

export * from './lib/+state/user/user.actions';
export * from './lib/+state/root.selectors';
export * from './lib/+state/root.actions';
export * from './lib/+state/app/app.actions';
export * from './lib/+state/setting/setting.selectors';
export * from './lib/+state/router-store/router.state';
export * from './lib/+state/users/users.reducer';
export * from './lib/+state/user/user.facade';
export * from './lib/+state/spinner/spinner.facade';
export * from './lib/+state/auth/auth.effects';
export * from './lib/+state/root.facade';
export * from './lib/+state/users/users.facade';
export * from './lib/+state/auth/auth.actions';
export * from './lib/+state/root.effects';
export * from './lib/+state/user/user.reducer';
export * from './lib/+state/app/app.effects';
export * from './lib/+state/auth/auth.selectors';
export * from './lib/+state/app/app.facade';
export * from './lib/+state/auth/auth.reducer';
export * from './lib/+state/auth/auth.facade';
export * from './lib/+state/user/user.selectors';
export * from './lib/+state/setting/setting.reducer';
export * from './lib/+state/users/users.selectors';
export * from './lib/+state/user/user.effects';
export * from './lib/+state/app/app.selectors';
export * from './lib/+state/spinner/spinner.effects';
export * from './lib/+state/setting/setting.effects';
export * from './lib/+state/setting/setting.facade';
export * from './lib/+state/spinner/spinner.selectors';
export * from './lib/+state/router-store/custom-serializer';
export * from './lib/+state/users/users.actions';
export * from './lib/shared-root-data-access.module';
export * from './lib/+state/root.reducer';
export * from './lib/+state/spinner/spinner.reducer';
export * from './lib/+state/app/app.reducer';
export * from './lib/+state/setting/setting.actions';
export * from './lib/+state/spinner/spinner.actions';
export * from './lib/+state/users/users.effects';
```
