### ISSUE TITLE
`deleteOutputPath` option should delete the contents and not the directory itself

### ISSUE THREAD

**Issue by sarveshraj** [nrwl/nx#10856]
## Current Behavior
`@nrwl/node:webpack` executor deletes the output folder before execution. This is due to `deleteOutputPath` option being set to `true` by default.

Any target using `@nrwl/workspace:run-commands` executor with the `cwd` option set to the output path and one of the commands set to the target using `@nrwl/node:webpack` executor fails. The failure is because `@nrwl/workspace:run-commands` tries to run commands in a deleted folder.

## Expected Behavior
I am proposing that the `deleteOutputPath` option delete the contents of the output folder and not the folder itself.

## Steps to Reproduce
Reproduced in https://github.com/nrwl/nx-examples/pull/207
Steps mentioned in the PR itself

### Environment
```
 >  NX   Report complete - copy this into the issue template

   Node : 14.18.1
   OS   : darwin x64
   yarn : 1.22.19
   
   nx : 14.3.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.3.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.1
   @nrwl/eslint-plugin-nx : 14.3.1
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.1
   @nrwl/js : 14.3.1
   @nrwl/linter : 14.3.1
   @nrwl/nest : Not Found
   @nrwl/next : 14.3.1
   @nrwl/node : 14.3.1
   @nrwl/nx-cloud : 14.1.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.3.1
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.3.1
   @nrwl/web : 14.3.1
   @nrwl/workspace : 14.3.1
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
         @nxext/svelte: 13.0.2
```

**Comment by hevans90** [comment]
I just tried setting `deleteOutputPath` to false (as I wanted this behaviour on one of my builds), and it doesn't seem to even work?

https://nx.dev/packages/node/executors/webpack#deleteoutputpath

<img width="613" alt="image" src="https://user-images.githubusercontent.com/12142999/175341762-078cf613-bcc2-44c6-b302-68a653a81db7.png">

**Comment by JGitHub01** [comment]
I can confirm that setting `deleteOutputPath` to false does not work. The folder is still deleted. I even tried to overwrite webpack `output: clean` to false:
```
const {merge} = require('webpack-merge');

module.exports = (config, _) => {
  return merge(config, {
    // overwrite values heres
    output: {
      clean: false,
    },
  });
}
```
The output folder still gets deleted.

This behavior also causes a problem with docker volume mount on Linux machine. When the folder is deleted, the mounted volume is lost even if the same folder is recreated. It's not an issue on Mac OS.

**Comment by kf6kjg** [comment]
Or you get fun failures like ` >  NX   EBUSY: resource busy or locked, rmdir '/path/to/outputfolder'` - in my case I've got the output folder mounted `tmpfs` in my Docker dev container.
