### ISSUE TITLE
Minor: please add "component" to @nrwl/angular/generators barrel export

### ISSUE THREAD

**Issue by savvyshell** [nrwl/nx#10861]
- [*] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Adding the component generator to the barrel export in `@nrwl/angular/generators`.

## Motivation

I had trouble finding the component generator to use for my custom plugin generator. It took a bit of digging around to realize the barrel export file (generators.d.ts) just missed it as it was in the `src/generators` folder.

## Suggested Implementation

Editing `generators.d.ts` and adding an export.

## Alternate Implementations

The previous is the best & simplest implementation of that.

**Comment by leosvelperez** [comment]
hey @savvyshell!

Would you like to create a PR with this? If you're up for it, you can go ahead and add the export in the `packages/angular/generators.ts` file.

**Comment by savvyshell** [comment]
@leosvelperez Oh my bad, wasn't expecting a reply so soon. Appreciate the quick response.
