### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by bogdan2510** [nrwl/nx#10866]
## Current Behavior

Running `nx test` in an `@nrwl/expo:library` fails with `SyntaxError: Cannot use import statement outside a module`

## Expected Behavior

To be able to run test

## Steps to Reproduce

1. Run `npx create-nx-workspace@latest --packageManager yarn` and pick the `app` option
2. Add `@nrwl@react` and `@nrwl/expo`
3. Generate a `expo` app and `expo` lib
4. Generate `expo:component` in the `expo:lib`. generated above
5. Try to run `nx test` against the `expo:lib`

Repo showing the bug: https://github.com/nrwl/nx-examples/pull/208

### Failure Logs
`> nx run expo-ui:test

 FAIL   expo-ui  libs/expo-ui/src/lib/expo-btn/expo-btn.spec.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/bogdan/Documents/proiecte/nx-examples/node_modules/react-native/index.js:14
    import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      2 | import React from 'react';
      3 |
    > 4 | import { View, Text } from 'react-native';
        | ^
      5 |
      6 | /* eslint-disable-next-line */
      7 | export interface ExpoBtnProps {

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/lib/expo-btn/expo-btn.tsx:4:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.328 s`
### Environment

`~/D/p/monorepo ❯❯❯ nx report                                                                                                                                                                                                 dev ✭ ✚

 >  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 14.3.6
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.2.4
   @nrwl/detox : 14.3.6
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : 14.3.6
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.6
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.3.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.3.6
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.3.6
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.3.6
   @nrwl/web : 14.3.6
   @nrwl/workspace : 14.3.6
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
         @nrwl/expo: 14.3.1`

**Comment by barbados-clemens** [comment]
hi @bogdan2510 looking at the changes you made. 

it looks like you have both a jest.config.ts and jest.config.js in your app. 
While the jest.config.js file contains the correct react-native configurations. the project.json is pointing towards the jest.config.ts file (that lacks the configs for react-native)

I'd suggest you move the config items from jest.config.js to jest.config.ts and delete the jest.config.js. 

Try that out and let me know if that works.

Also, is this the default generated project you got? Could be I missed updating react-native to use jest.config.ts vs jest.config.js causing both to get generated.

**Comment by xiongemi** [comment]
@bogdan2510 for the lib you generated, you might have to change jest.config.ts for your expo-ui library.

**Comment by bogdan2510** [comment]
@xiongemi What i need to change?

**Comment by xiongemi** [comment]
@bogdan2510 yes, exactly. could you try it run test again?

**Comment by bogdan2510** [comment]
@xiongemi I moved stuff to `jest.config.ts` and run the test.

**This is the result**

` FAIL   expo-ui  libs/expo-ui/src/lib/expo-btn/expo-btn.spec.tsx
  ● Test suite failed to run

    Cannot find module '@babel/plugin-transform-flow-strip-types'
    Require stack:
    - /Users/bogdan/Documents/proiecte/nx-examples/node_modules/react-native/jest/preprocessor.js
    - /Users/bogdan/Documents/proiecte/nx-examples/node_modules/jest-util/build/requireOrImportModule.js
    - /Users/bogdan/Documents/proiecte/nx-examples/node_modules/jest-util/build/index.js
    - /Users/bogdan/Documents/proiecte/nx-examples/node_modules/jest-config/build/getCacheDirectory.js
    - /Users/bogdan/Documents/proiecte/nx-examples/node_modules/jest-config/build/Defaults.js
    - /Users/bogdan/Documents/proiecte/nx-examples/node_modules/jest-config/build/normalize.js
    - /Users/bogdan/Documents/proiecte/nx-examples/node_modules/jest-config/build/index.js
    - /Users/bogdan/Documents/proiecte/nx-examples/node_modules/@nrwl/jest/src/executors/jest/jest.impl.js
    - /Users/bogdan/Documents/proiecte/nx-examples/node_modules/nx/src/config/workspaces.js
    - /Users/bogdan/Documents/proiecte/nx-examples/node_modules/nx/src/command-line/run.js
    - /Users/bogdan/Documents/proiecte/nx-examples/node_modules/nx/bin/run-executor.js

      at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (../../node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
      at Object.process (../../node_modules/react-native/jest/preprocessor.js:66:10)
      at ScriptTransformer.transformSource (../../node_modules/@jest/transform/build/ScriptTransformer.js:619:31)
      at ScriptTransformer._transformAndBuildScript (../../node_modules/@jest/transform/build/ScriptTransformer.js:765:40)
      at ScriptTransformer.transform (../../node_modules/@jest/transform/build/ScriptTransformer.js:822:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.294 s
Ran all test suites.`

**Comment by bogdan2510** [comment]
@xiongemi After adding some modules(because i got erros saying that they are missing) test  run was a success.

modules added:

1. `yarn add @babel/plugin-transform-flow-strip-types -D`
2. `yarn add @babel/plugin-transform-react-jsx-source -D`

Is this the expected behaviour?

**Comment by xiongemi** [comment]
I never installed @babel/plugin-transform-flow-strip-types and it works for me out of the box. it should be installed as a dependency for metro-babel-register. however, good to hear it works.
