### ISSUE TITLE
Is there a way to split up package.json "scripts"?

### ISSUE THREAD

**Issue by dolanmiu** [nrwl/nx#1089]
Is there a way to split up package.json "scripts"?

In our mono-repo, we have 20+ projects and the `package.json` "scripts" section is getting very unmaintable. Can we split the `package.json` scripts into sub `package.json`s, so that each `app` has it's own `package.json` with it's own `scripts`?

**Comment by xmlking** [comment]
This also helps organizing `node-app` dependencies separate from  `web-app` dependencies

**Comment by xmlking** [comment]
I am thinking of adopting Lerna and Yarn workspace on top of nx monorepo

**Comment by lonix1** [comment]
@xmlking Do you know the difference between nx and lerna? I can't find info on that... Are they the same or complementary, etc.? They seem to do the same thing, but I'm not sure.

**Comment by xmlking** [comment]
I think one overlap  feature  in nx and Lerna is , thy both help  detect `affected` modules and help test/build only modified modules.
I am thinking to use nx for affected, Lerna for publishing `publishable` lib modules, and switch to `yarn`

**Comment by lonix1** [comment]
You are gonna use nx AND lerna... interesting...

Yarn: I don't see the point, these days npm does everything yarn does. You might want to look into pnpm which has unique features.

**Comment by lonix1** [comment]
@xmlking You are gonna use nx AND lerna... interesting... (I didn't realise they were that different)

Yarn: I don't see the point, these days npm does everything yarn does. You might want to look into pnpm which has unique features (doesn't download npm packages over and over again for different projects, and its VERY fast!)

If you have success with nx+lerna let us know when you get the chance, I'll do the same :smiley:

**Comment by xmlking** [comment]
My main goal is split package.json , one in root and one each in apps/web-app apps/node-app with their own scripts in it. Considering yarn because  of its support for workspaces

**Comment by lonix1** [comment]
Hey @xmlking you might want to look at [rush](https://www.npmjs.com/package/@microsoft/rush) as well. It's similar to lerna and made by Microsoft, so it has better support. I don't know if it works with nx nicely. I plan to try both and see which plays better with nx.

**Comment by vsavkin** [comment]
- You could run your script using the angular cli instead of npm. We provide the run-commands builder for that. So you could do: `ng run myproject:myscript`. I personally think this is the best option.
- You could also use yarn workspaces. 
- You could use a tool like `nps` to organize your scripts.

**Comment by gangadharjannu** [comment]
@vsavkin Can you give me an example or documentation on how to use run-commands? I have googled but couldn't find enough info

**Comment by onderceylan** [comment]
Here's an example:

`
"json-server": {
          "builder": "@nrwl/builders:run-commands",
          "options": {
            "outputPath": "apps/xx",
            "commands": [
              {
                "command": "json-server apps/xx/src/mock-backend/db.json --routes apps/xx/src/mock-backend/routes.json --port 8080"
              }
            ],
            "parallel": false
          }
        }
`

You can set parallel to true and add more commands to be executed in parallel if you like.
