### ISSUE TITLE
@nrwl/angular:move generates backslashes on Windows in file paths 

### ISSUE THREAD

**Issue by montella1507** [nrwl/nx#10892]
## Current Behavior
1) `nx generate @nrwl/angular:move --destination=assist/shared/translations --projectName=assist-translations --importPath=@assist/shared/translations --dry-run --no-interactive`

Generates paths like "\\..\\..\\.." rather than expected "../../../"

in files:
.eslintc.json
ng-package.json
project.json

Example: (screenshot from git - manual fix of wrongly modified files)
![image](https://user-images.githubusercontent.com/10418323/175661353-86e3b213-a44f-4e3b-a960-0dace125dfc7.png)

They are not compatible with other OS than windows.

## Expected Behavior
@nrwl/angular:move should generate multiplatform-compatible paths

### Environment
NX:                   14.1.7
Nrwl/angular:   14.1.7
Windows:  11 x86

**Comment by montella1507** [comment]
@leosvelperez  TYVM!

**Comment by montella1507** [comment]
@leosvelperez  btw is this fixed in other files as well? Because it is not generating wrong paths only in ng-package, but in project.json and .eslintc.json as well?  I see only patched ng-package generator in the pull request..

**Comment by leosvelperez** [comment]
@montella1507 you're absolutely right, somehow I completely missed the other files. I guess I only focused on the screenshot 🤦🏻
