### ISSUE TITLE
dep-graph does not recognize dependencies for apps or libs inside of git submodule

### ISSUE THREAD

**Issue by ramyhhh** [nrwl/nx#10903]
## Current Behavior

If an app or a lib is a part of git submodule the `dep-graph` does not recognize their dependencies. After some debugging I found out the the map variable `allWorkspaceFiles` does not really contain all the workspace files, instead it only contains only the files that are tracked by git directly. Also this limitation will affect all project dependency related operations such as the flag `generatePackageJson` as dep-graph does not show any dependencies for the project.

## Expected Behavior

It's expected that git submodules are fully supported and that includes the ability to see apps and libs dependencies even inside git submodules.

## Steps to Reproduce

* create an nx workspace
* mkdir inside apps dir and init a git submodule
* generate a project inside that dir
* generate a lib and make the project depend on it (via import)
* run `nx graph` and it should show the app with no dependencies

### Environment

Node : 18.3.0
   OS   : darwin x64
   npm  : 8.11.0
   
   nx : 14.1.9
   @nrwl/angular : 14.1.9
   @nrwl/cypress : 14.1.9
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.9
   @nrwl/eslint-plugin-nx : 14.1.9
   @nrwl/express : 14.1.9
   @nrwl/jest : 14.1.9
   @nrwl/js : 14.1.9
   @nrwl/linter : 14.1.9
   @nrwl/nest : 14.1.9
   @nrwl/next : Not Found
   @nrwl/node : 14.1.9
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : 0.9.1
   @nrwl/storybook : 14.1.9
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.9
   typescript : 4.6.3

**Comment by ramyhhh** [comment]
I've solved this for myself by setting the flag `--recurse-submodules` for `git ls-files` in git-hasher
I can create PR if my edits are fine.

**Comment by ramyhhh** [comment]
I've been working on my modified `nx` as shown in the PR and it has been working just fine.

**Comment by FrozenPandaz** [comment]
Thank you so much! This was fixed with https://github.com/nrwl/nx/pull/11334
