### ISSUE TITLE
@nrwl/node:library does not properly validate --importPath

### ISSUE THREAD

**Issue by AustinHaigh-Hach** [nrwl/nx#10914]
## Current Behavior

Invalid node package names are accepted by the generator. Eg:

`nx generate @nrwl/node:library --buildable --publishable --importPath=@myorg/invalid/pkg/name`

or

`nx generate @nrwl/node:library --buildable --publishable --directory=mylibs --name=pkg`
(the second example generates an import path of `@myorg/mylibs/pkg`)

## Expected Behavior

Although the `--buildable` and `--publishable` flags were given, the generated library cannot be installed with npm because the package name is invalid. Package names can only contain one backslash.

## Steps to Reproduce
1. Generate a node library: `nx generate @nrwl/node:library --buildable --importPath=@myorg/invalid/pkg/name --name=pkg`
2. Install the library with npm. Eg: `npm install ./libs/pkg`

### Failure Logs

```
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "@myorg/invalid/pkg/name": name can only contain URL-friendly characters

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2022-06-27T13_19_55_202Z-debug.log
```

### Environment

```
 >  NX   Report complete - copy this into the issue template

   Node : 14.17.2
   OS   : darwin x64
   npm  : 7.21.1
   
   nx : 14.2.1
   @nrwl/angular : 14.2.1
   @nrwl/cypress : 14.2.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.2.1
   @nrwl/eslint-plugin-nx : 14.2.1
   @nrwl/express : Not Found
   @nrwl/jest : 14.2.1
   @nrwl/js : 14.2.4
   @nrwl/linter : 14.2.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.2.4
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.2.1
   @nrwl/web : 14.2.1
   @nrwl/workspace : 14.2.1
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:

```

**Comment by AustinHaigh-Hach** [comment]
Instead of changing the importPath (which is valid for typescript), would it be better to create a new `package.json` file? For eg:

```
nx generate @nrwl/node:library --buildable --publishable --directory=mylibs --name=pkg
vim ./libs/mylibs/package.json  # create a valid package.json file here
npm install ./libs/mylibs
```

Now a `require("@myorg/mylibs/pkg")` call would work, because the package name is `@myorg/mylibs` instead of `@myorg/mylibs/pkg`.

**Comment by nartc** [comment]
Hi @AustinHaigh-Hach, thank you for reporting. When it comes to package name (that is subject to npm), this seems to be a documentation issue rather as each consumer can have different way to adjust their `package.json` as well as specifying the libs' `importPath`.

A valid use-case (as-is) is a publishable library with buildable secondary entry point.

```ts
npx nx g @nrwl/node:lib core --publishable --import-path=@myorg/core
npx nx g @nrwl/node:lib secondary --buildable --directory=core --import-path=@myorg/core/secondary
npx nx g @nrwl/node:lib third --buildable --directory=core --import-path=@myorg/core/experimental/third
```

```
// consumer side runs npm install @myorg/core

import { coreStuff } from "@myorg/core";
import { secondaryStuff } from "@myorg/core/secondary";
import { experimentalThirdStuff } from "@myorg/core/experimental/third";
```

That said, I think we can clarify this point in the documentation. What do you think?
