### ISSUE TITLE
what does "which module should import the library" do ?

### ISSUE THREAD

**Issue by kkoo95** [nrwl/nx#1092]
When generating a lib we get this question asked. But after several tries I couldn't figure out what it does.
So, what does it do ? :)

**Comment by FrozenPandaz** [comment]
This sets the `parentModule` option:

https://nx.dev/api-schematics/library#options

In general, it adds the import to the parent module.

The parent module is a path from the root of the workspace

If you think it can be more clear, PRs are welcome :)
