### ISSUE TITLE
tsconfig.base.json formatted twice with format:write

### ISSUE THREAD

**Issue by lewsmith** [nrwl/nx#10937]
## Current Behavior

`tsconfig.base.json` seems to be being formatted twice with every run of `nx format:write` when there are no changes to the file.
No changes are reported by `format:check` so I'm unsure why this is happening. When running `format:write` you can see the file being formatted to to one style before being formatted again back to the previous format.

There was an issue similar to this ([#6118](https://github.com/nrwl/nx/issues/6118)), but this was an issue for multiple json files in the root dir. It's only `tsconfig.base.json` that I'm seeing this happen with.

Obviously it's not a huge issue, I'm more interested in the internal workings of Nx's formatting so keen to see if we could get a fix

## Expected Behavior

I expect not to see `tsconfig.base.json` being formatted when no formatting is required.

## Steps to Reproduce

```
# Create a new nx workspace:
npx create-nx-workspace --preset=ts --packageManager=yarn --name=test-project --nxCloud=false

cd test-project

# Run format
yarn nx format:write --all

# Run format again to see tsconfig being reported as fomatted
yarn nx format:write --all
```

If you open `tsconfig.base.json` in vscode and run `format:write --all`, you'll see the double formatting happening.

### Environment

```
   Node : 14.19.3
   OS   : linux x64
   yarn : 1.22.10
   
   nx : 14.3.6
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.6
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.3.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.3.6
   typescript : 4.7.4
```

**Comment by AgentEnder** [comment]
This happens due to us sorting some props in the json file during format, so it's updated which breaks the prettier styling and then prettier goes in and fixes it up.

The alternative we may consider would be to manually invoke prettier silently on the file, but that would be inconsistent in cases the format is needed.

I'm going to close this out, hopefully that gives a good context into the reasoning. It's the same reason workspace.json changes are typically reported.
