### ISSUE TITLE
How to lazy load react components from path alias?

### ISSUE THREAD

**Issue by roddc** [nrwl/nx#10945]
I have migrated my  Create-React-App project to nx workspace, and I want to move some components to a library, but I got an error ` Can't resolve @ws/my-lib` when I tried to load the components with [@loadable/component](https://github.com/gregberge/loadable-components). I think the problem is that webpack didn't create the chunk of the library because I didn't import the components statically. 
How do I tell webpack to create the chunk? I have added the lib to `implicitDependencies` in the app's project.json, but still no luck.
Is there any docs I can follow? I tried [this](https://webpack.js.org/guides/code-splitting/#prefetchingpreloading-modules), it is not working either. I have to use relative path i.e. `../../../../libs/my-lib/${componentPath}` to load the component.
How do I use path alias to load the components? for example:
```
loadable(() => import(`@ws/my-lib/${componentPath}`))
```
In tsconfig.base.json:
```
"paths": {
      "@ws/my-lib/*": ["libs/my-lib/src/*"]
    }
```
The `componentPath` is received from backend.

**Comment by marckassay** [comment]
@roddc Without seeing a demo repo, are you aware of [TsconfigPathsPlugin](https://github.com/dividab/tsconfig-paths-webpack-plugin)? If not, it seems from what I gather, it's worth looking into.

**Comment by zaunermax** [comment]
@roddc sorry for pinging you and re-activating a stale issue, but have you been able to figure something out? 🙌
