### ISSUE TITLE
Nx Cloud doesn't read cache for read only token

### ISSUE THREAD

**Issue by B1Z1** [nrwl/nx#10954]
Hi! I found a little problem with NxCloud distributed cache.

## Current Behavior
We are using Nx Cloud and when we try to build an application with the read-write token, it's ok. Cache successfully saved on NxCloud and successfully downloads on cold start. But when we try to build an application with the read-only token, log displays it:

 NX   Nx Cloud: Cache miss 0444323ed11c93cf987385d8a253d53fbaba0071b10071153b49a5ffefd8cf6a.

for every hash  

## Expected Behavior
NxCloud Cache works with read-only token

## Steps to Reproduce
Before you need to have NxCloud

1. Execute NX_CLOUD_AUTH_TOKEN=your-token yarn build
2. yarn nx clear-cache
3. yarn build

### Environment
   Node : 12.22.7
   OS   : darwin x64
   yarn : 1.22.4
   
   nx : 14.1.9
   @nrwl/angular : 14.1.9
   @nrwl/cypress : 14.1.9
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.9
   @nrwl/eslint-plugin-nx : 14.1.9
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.9
   @nrwl/js : 14.1.9
   @nrwl/linter : 14.1.9
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.1.9
   @nrwl/nx-cloud : 14.1.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.9
   @nrwl/web : 14.1.9
   @nrwl/workspace : 14.1.9
   typescript : 4.6.4
   ---------------------------------------
   Community plugins:
         @ngneat/transloco: 2.20.1
         @ngrx/effects: 12.5.0
         @ngrx/entity: 12.4.0
         @ngrx/store: 12.5.0
         @ngrx/store-devtools: 12.5.0
         rxjs: 6.6.7
         @storybook/angular: 6.4.19

**Comment by B1Z1** [comment]
Hi guys, bumping this bug, because we cannot use NxCloud with all features

**Comment by dapengzhangMecca** [comment]
Hi @B1Z1, has this issue been resolved? I recently saw the same issue. Could you please share if you have any findings? Thanks

**Comment by B1Z1** [comment]
Hi, @dapengzhangMecca! I tried to contact nx cloud support and they solved for us this problem. I just tried to build an application with read-only token and it works properly

**Comment by dapengzhangMecca** [comment]
Thanks @B1Z1, do you know what was the cause? Was it a configuration problem or NX's problem?

**Comment by B1Z1** [comment]
No, the problem was inside the NX Cloud mechanism. They fixed it on their servers

**Comment by dapengzhangMecca** [comment]
@B1Z1 Thank you! I will contact their support.
