### ISSUE TITLE
shared-features will not compile ... feature GROUP rootDir incoherent 

### ISSUE THREAD

**Issue by nhhockeyplayer** [nrwl/nx#10952]
SUBJECT: shared-features will not compile ...rootDir incoherent (I have spent a fair amount of time shaking this out without remedy)

here is the repo for nrwl committer just ask to be collaborator
https://github.com/nhhockeyplayer/meanstacknh

My `.eslintrc.json` follows the book `Enterprise Angular Monorepo Patterns` Victor published has obsoleted tech leads overnight and ahead of its time since 2018. Produces a nice dep-graph. The scaffolds Im seeing being built in the field are spaghetti. This book is the `new standard for scaffolding`. So my focus on this is as close to spec as possible in hopes for the schematic to be generating elite fail-safe scaffolded code. Thanks Victor (and nx team) for bringing clarity to shared modules/libraries in the field...  Nx is a masterpiece.

## Current Behavior
My quest to obtain a valid visual dep-graph via grouping has been successful. If you run nx dep-graph everything looks great with downward trajectory for groups consuming libs. No spaghetti. Nx is `the way` to develop commercial software and scaffolding is now the primary focus to obtaining real-world extensibility and re-usability.
I have adhered to the current docs for developing Nx libraries using the following schematics and the code generated. Everything is buildable and publishable.

- @nrwl/angular:library
- @nrwl/angular:ngrx

I scaffolded 2 apps and set of shared library folders aggregating libraries as follows:
```
- apps
    - admin (frontend)
    - api-typegoose  (backend)
- libs
    - admin
        - root
            - feature-shell
    - shared
        - feature
                - auth
                - chat
                - notification
                - setting
                - user
        - api-service
        - material
        - custom-material
        - root
            - assets
            - data-access
            - environments
            - service
            - ui-animation
            - ui-spinner
            - ui-styles
            - util
        - ui
            - widget
        - util
            - dto
            - entity
            - generics

```
**everything scaffolded after the feature folder builds**

As soon as I start to **attempt to build individual features **within the feature folder** I am receiving rootDir errors**

`error TS6059: File '/Users/meanstack02/meanstacknh/libs/shared/root/data-access/src/lib/+state/root.actions.ngtypecheck.ts' is not under 'rootDir' '/Users/meanstack02/meanstacknh/libs/shared/feature/chat/src'. 'rootDir' is expected to contain all source files.
`

I have attempted to augment the project config, tsconfig.base.json for rootDir property (adding/omitting)

I cannot build past this rootDir issue. Developers hoping to focus on pure business logic hope to bypass (at least I do) the wildcard tsconfig biz of changing/adding wild cards to remedy what a schematic could or should be doing (but all looks to be in order) that should be boiler plate less special cases.

The rootDir issue is frequent on web research but this codebase is on the medium size regardless I do not think rootDir should be an issue if this is the inspired way as the docs suggest to scaffold and build out a very shared monorepo.

## Expected Behavior
It would be nice if my feature libraries build

I can build most of the lower level consumable ones 

but as I start building libraries that consume the lower level consumable libraries the compiler gives out and loses coherency of the rootDir as it pertains to and across libraries project.json files.

This repo does have real compiler errors in the feature branch I have not qualified all the ngrx logic as of yet but the **_rootDir_** continuity across projects at the feature group folder level are preventing me from closure on left over compiler errors.

I expect compiler errors but not the rootDir error

## Steps to Reproduce

Please note 
Sometimes ng-packagr library developers bypass the npm registry and temporarily customize package.json for test purposes to bypass npm registry. I have done this since I am not officially publishing anything.
So I had to jerry rigged my npm packages for each library to simulate npm registry installation for DEV purposes without having credentials to an npm registry and mainly in part due to following ticket
https://github.com/nrwl/nx/issues/10800

so in my package.json my libs are setup as look as follows to progress compilation continuity in dev mode

```
    "@meanstacknh/shared-api-service": "file:libs/shared/api-service/src/lib",
    "@meanstacknh/shared-custom-material": "file:libs/shared/custom-material/src/lib",
    "@meanstacknh/shared-feature-auth": "file:libs/shared/feature/auth/src/lib",
    "@meanstacknh/shared-feature-chat": "file:libs/shared/feature/chat/src/lib",
    "@meanstacknh/shared-feature-notification": "file:libs/shared/feature/notification/src/lib",
    "@meanstacknh/shared-feature-setting": "file:libs/shared/feature/setting/src/lib",
    "@meanstacknh/shared-feature-user": "file:libs/shared/feature/user/src/lib",
    "@meanstacknh/shared-material": "file:libs/shared/material/src/lib",
    "@meanstacknh/shared-root-assets": "file:libs/shared/root/assets/src/lib",
    "@meanstacknh/shared-root-data-access": "file:libs/shared/root/data-access/src/lib",
    "@meanstacknh/shared-root-environments": "file:libs/shared/root/environments/src/lib",
    "@meanstacknh/shared-root-service": "file:libs/shared/root/service/src/lib",
    "@meanstacknh/shared-root-ui-animation": "file:libs/shared/root/ui-animation/src/lib",
    "@meanstacknh/shared-root-ui-spinner": "file:libs/shared/root/ui-spinner/src/lib",
    "@meanstacknh/shared-root-ui-styles": "file:libs/shared/root/ui-styles/src/lib",
    "@meanstacknh/shared-root-util": "file:libs/shared/root/util/src/lib",
    "@meanstacknh/shared-ui-widget": "file:libs/shared/ui/widget/src/lib",
    "@meanstacknh/shared-util-dto": "file:libs/shared/util/dto/src/lib",
    "@meanstacknh/shared-util-entity": "file:libs/shared/util/entity/src/lib",
    "@meanstacknh/shared-util-generics": "file:libs/shared/util/generics/src/lib",
```

I use the following commands to reproduce

1. build everything that builds clean
```
        -- good
        nx build shared-material
        nx build shared-custom-material
        nx build shared-feature-notification
        nx build shared-api-service
        nx build shared-root-assets
        nx build shared-root-data-access
        nx build shared-root-environments
        nx build shared-root-service
        nx build shared-root-ui-animation
        nx build shared-root-ui-spinner
        nx build shared-root-ui-styles
        nx build shared-root-util
        nx build shared-ui-widget
        nx build shared-util-dto
        nx build shared-util-entity
        nx build shared-util-generics
```

2. TO REPRODUCE attempt to build at the feature group level (this is where it gives out)
```
        nx build shared-feature-chat
             or
        nx build shared-feature-auth
        nx build shared-feature-user

```

eventually ideally hoping for 100% clean build with `nx run-many --all --target build`
### Failure Logs
```
meanstack02@admin meanstacknh % nx build shared-feature-chat    


   ✔    8/8 dependent project tasks succeeded [6 read from cache]

   Hint: you can run the command with --verbose to see the full dependent project outputs

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


> nx run shared-feature-chat:build:production

Building Angular Package

------------------------------------------------------------------------------
Building entry point '@meanstacknh/shared-feature-chat'
------------------------------------------------------------------------------
✖ Compiling with Angular sources in Ivy partial compilation mode.
libs/shared/root/data-access/src/lib/+state/root.actions.ts:1:1 - error TS6059: File '/Users/meanstack02/meanstacknh/libs/shared/root/data-access/src/lib/+state/root.actions.ngtypecheck.ts' is not under 'rootDir' '/Users/meanstack02/meanstacknh/libs/shared/feature/chat/src'. 'rootDir' is expected to contain all source files.

1 import { Action } from '@ngrx/store';
  
libs/shared/root/data-access/src/lib/+state/router-store/router.state.ts:1:1 - error TS6059: File '/Users/meanstack02/meanstacknh/libs/shared/root/data-access/src/lib/+state/router-store/router.state.ngtypecheck.ts' is not under 'rootDir' '/Users/meanstack02/meanstacknh/libs/shared/feature/chat/src'. 'rootDir' is expected to contain all source files.

1 import { Params } from '@angular/router'
  
libs/shared/root/data-access/src/lib/+state/auth/auth.actions.ts:1:1 - error TS6059: File '/Users/meanstack02/meanstacknh/libs/shared/root/data-access/src/lib/+state/auth/auth.actions.ngtypecheck.ts' is not under 'rootDir' '/Users/meanstack02/meanstacknh/libs/shared/feature/chat/src'. 'rootDir' is expected to contain all source files.

1 import {Action} from '@ngrx/store'
  
libs/shared/root/data-access/src/lib/+state/auth/auth.reducer.ts:1:1 - error TS6059: File '/Users/meanstack02/meanstacknh/libs/shared/root/data-access/src/lib/+state/auth/auth.reducer.ngtypecheck.ts' is not under 'rootDir' '/Users/meanstack02/meanstacknh/libs/shared/feature/chat/src'. 'rootDir' is expected to contain all source files.

1 import {AuthAction, EAuthActions} from './auth.actions'
  
libs/shared/root/data-access/src/lib/+state/auth/auth.reducer.ts:1:40 - error TS6059: File '/Users/meanstack02/meanstacknh/libs/shared/root/data-access/src/lib/+state/auth/auth.actions.ts' is not under 'rootDir' '/Users/meanstack02/meanstacknh/libs/shared/feature/chat/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Imported via './auth.actions' from file '/Users/meanstack02/meanstacknh/libs/shared/root/data-access/src/lib/+state/auth/auth.reducer.ts'

```

### Environment
```
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : darwin x64
   yarn : 1.22.18
   
   nx : 14.3.6
   @nrwl/angular : 14.3.6
   @nrwl/cypress : 14.3.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : 14.3.6
   @nrwl/express : 14.3.6
   @nrwl/jest : 14.3.6
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.3.6
   @nrwl/nest : 14.3.6
   @nrwl/next : Not Found
   @nrwl/node : 14.3.6
   @nrwl/nx-cloud : 14.1.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : 8.12.11
   @nrwl/storybook : 14.3.6
   @nrwl/web : 14.3.6
   @nrwl/workspace : 14.3.6
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
   	 @fortawesome/angular-fontawesome: 0.11.1
   	 @ionic/angular: 6.1.12
   	 @ngrx/component-store: 14.0.0
   	 @ngrx/effects: 14.0.0
   	 @ngrx/entity: 14.0.0
   	 @ngrx/router-store: 14.0.0
   	 @ngrx/store: 14.0.0
   	 @nxtend/capacitor: 13.0.0
   	 @nxtend/ionic-angular: 13.1.0
   	 @storybook/angular: 6.5.9
   	 angular-builder-custom-terser-options: 1.0.1
   	 @ngrx/schematics: 14.0.0
   	 @ngrx/store-devtools: 14.0.0
   	 @nxpm/stack: 4.21.0
   	 @nxtend/capacitor: 13.0.0
   	 @storybook/angular: 6.5.9
```

**Comment by Hikachhu** [comment]
I have the same kind of error on my side since a few weeks. I think you must have put your repo in private I can't access it and I can't find it on your profile

**Comment by nhhockeyplayer** [comment]
thanks friend repo is for @nrwl/nx committers sorry im developing some proprietary patterns from nd

I am revisiting my library grouping

this link speaks to everything being downward trajectory which no doubt will fix for the compiler
https://bobbyhadz.com/blog/typescript-file-is-not-under-rootdir

but the @nrwl/nx docs offer grouping logic here https://nx.dev/structure/grouping-libraries#grouping-libraries
which I had hoped would be able to navigate upward trajectories

Im going to try and remodel/move my groups with the move schematic and see what shakes

Im sure the team knows what the limitations are

**Comment by nhhockeyplayer** [comment]
a good question is the policy definition on grouping needs clarification

parent to child cross library references seem valid 

the one outstanding is sibling to sibling cross library references seems undefined
my feature lib wants to operate shared root data stores and I would hate to have to relocate it dependently under features since its root scope

**Comment by Hikachhu** [comment]
Thanks for the messages, I had the same analysis of the problem on my side, I'm happy to see that I'm not the only one, indeed the transversal dependencies between the libraries seem to have a problem, but I don't have the level in ts compilation to understand where the conflict comes from

**Comment by nhhockeyplayer** [comment]
This one might be a while, since ng-packagr appears to be going thru some gyrations on the angular team. Hoping they can step up its really late for this to be omitted.

which leads me to assert the issue may lie in the angular lib compiler. If the @nrwl/nx team can confirm unless they are fit to augment this... I would love to see @nrwl/nx team invent their own compiler for angular libs ng-packagr has not been fun in the field and committing to it has been like this stalled.

need a silver bullet

**Comment by nhhockeyplayer** [comment]
this link appears to be step in right direction
still working it
https://tyapk.ru/blog/post/nx-publish-library-deps

**Comment by Hikachhu** [comment]
From what I could see in my tests, the error appears only when the lib at the origin of the dependencies is not itself in another lib. If we have a->b in the graph then a must be under libs/, b can be anywhere

**Comment by nhhockeyplayer** [comment]
well yes thats downward trajectory

**Comment by nhhockeyplayer** [comment]
> this link appears to be step in right direction still working it https://tyapk.ru/blog/post/nx-publish-library-deps
> 
> spassiiba oohn ruusky

this one fixed it.. have to augment paths for libraries... ng-packagr trait

```
            "@meanstacknh/shared-feature-chat": [
                "dist/libs/shared/feature/chat",
                "libs/shared/feature/chat/src/index.ts"
            ],
```

**Comment by nhhockeyplayer** [comment]
> this link appears to be step in right direction still working it https://tyapk.ru/blog/post/nx-publish-library-deps
> 
> spassiiba oohn ruusky

this one fixed it.. have to augment paths for libraries... ng-packagr trait

```
            "@meanstacknh/shared-feature-chat": [
                "dist/libs/shared/feature/chat",
                "libs/shared/feature/chat/src/index.ts"
            ],
```
