### ISSUE TITLE
Multiple Host MF app fail to start with devRemotes

### ISSUE THREAD

**Issue by lifeisegg123** [nrwl/nx#10963]
## Current Behavior

I've followed the guide from official docs, and run command below
`nx g @nrwl/react:host shell --remotes=shop,cart`
And then I added some configuration to run as multiple hosts app.
My configurations is like this
```js
// shell
module.exports = {
  name: 'shell',
  remotes: ['shop', 'cart'],
  exposes: {
    './queryClient': './src/queryClient',
    './atoms': './src/atoms',
  },
};
```
```js
// cart
module.exports = {
  name: 'cart',
  remotes: ['shell'],
  exposes: {
    './Module': './src/remote-entry',
  },
};
```

`nx serve shell` and `nx serve cart` runs fine but it fails with `nx serve shell --devRemotes cart,shop`.
I think it try to run shell multiple times, so that makes the error.

## Expected Behavior

`nx serve shell --devRemotes cart,shop` runs fine with multiple host set-up.
## Steps to Reproduce

set configuration above and run `nx serve shell --devRemotes cart,shop`
[my repo](https://github.com/lifeisegg123/nx-test)

### Failure Logs

```
Error: listen EADDRINUSE: address already in use 127.0.0.1:4200
    at Server.setupListenHandle [as _listen2] (node:net:1330:16)
    at listenInCluster (node:net:1378:12)
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:1516:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:73:8) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 4200
}

Running target "shell:serve" failed

   Failed tasks:
   
   - shell:serve:development
   
   Hint: run the command with --verbose for more details.

node:internal/process/promises:279                                                                                                                          
            triggerUncaughtException(err, true /* fromPromise */);
            ^

RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 44978.
    at /Users/ijeongjae/Desktop/workspace/nx-test/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: undefined,
  signal: undefined
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 44979.
    at /Users/ijeongjae/Desktop/workspace/nx-test/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: undefined,
  signal: undefined
}
```

### Environment

```
   Node : 16.14.1
   OS   : darwin arm64
   yarn : 1.22.18
   
   nx : 14.3.6
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.3.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : 14.3.6
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.6
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.3.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.3.6
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.3.6
   @nrwl/web : 14.3.6
   @nrwl/workspace : 14.3.6
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
 ```

**Comment by franktroia** [comment]
I have the same issue, but with Angular MFE.

The port is unused. I have confirmed with netstat. Also note that everything starts fine using the configured ports when the --devRemotes flag is not set. So something specific to devRemotes seems broken.

**Comment by franktroia** [comment]
Aha. I think the issue is with my module-federation.config.js. The remotes array needs to be empty since I'm doing dynamic module federation. Once I made the remotes array empty, it worked.

**Comment by Stusaw** [comment]
> Aha. I think the issue is with my module-federation.config.js. The remotes array needs to be empty since I'm doing dynamic module federation. Once I made the remotes array empty, it worked.

Yes this was also the case with in my app. It does get very confusing which config settings are actually required when trying to keep up with the latest changes.

**Comment by LongLiveCHIEF** [comment]
I'm getting the same error, but i have a mfe with more than one exposed component instead.

I'm not using dynamic module federation either, so it would seem the problem is more around having more than one exposed component in a remote than anything to do with the host.  My problem happens whenever i just run the `nx serve parent` _without_ the `devRemotes` option.

**Comment by Aleksidius** [comment]
Hey until this is fixed, I believe this works:

nx serve shell --open --devRemotes=feature-c --devRemotes=feature-b --devRemotes=remote

**Comment by paul-paliychuk** [comment]
any update on this?
