### ISSUE TITLE
nx wipes `{options.outputPath}`  after update from `14.2.1` to `14.3.6` in a `@nrwl/node:webpack` build

### ISSUE THREAD

**Issue by gestj** [nrwl/nx#10964]
## Current Behavior
My `mono.repo/apps/<node-app>/dist` folder that contains `Dockerfile` and some other files added to Git gets wiped completely by nx build.

I build with npm scripts. In this case the build command is the following:

```
nx build <node-app> --optimization
```

In `workspace.json` the app is configured properly:

```
...
    "<node-app>": {
      "$schema": "../../node_modules/nx/schemas/project-schema.json",
      "root": "apps/<node-app>",
      "sourceRoot": "apps/<node-app>/src",
      "projectType": "application",
      "architect": {
        "build": {
          "builder": "@nrwl/node:webpack",
          "outputs": [
            "{options.outputPath}"
          ],
          "options": {
            "outputPath": "apps/<node-app>/dist",
            "main": "apps/<node-app>i/src/main.ts",
            "tsConfig": "apps/<node-app>/tsconfig.app.json"
          },
          "configurations": {
            "production": {
              ...
            }
          }
        },
        "serve": {
          "builder": "@nrwl/node:node",
           ...
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          ...
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          ...
        }
      },
      "tags": [],
      "implicitDependencies": [
        ...
      ]
    },
```

Serving locally, testing & linting works as expected.

Building also runs without error *BUT* after the build the `apps/<node-app>/dist` folder only contains the compiled javascript.

## Expected Behavior
Existing files in `apps/<node-app>/dist` that aren't part of the compilation shouldn't be removed by the build.

## Steps to Reproduce
https://github.com/nrwl/nx-examples/pull/211

### Failure Logs
No logs involved.

### Environment
Locally on Mac, latest iOS Monterey as well as in CI on docker with `ubuntu-latest` image.

**Comment by gestj** [comment]
I guess it's a bad way to use store sources in the `dist` folder in the first place.

This whole behaviour can be worked around with keeping `dist` empty & add sources needed for image build somewhere else.

*BUT* nx definitely changed its behaviour here - it worked for me until update to `14.3.6`.

I for myself already moved the files and fixed my build...

**Comment by ridyio** [comment]
I think this is a breaking change yet it was implemented in a minor version release with a notice. In my case i build the database migrations in a prepare build step and depend the actual build step on prepare being completed but when building, the webpack builder deletes the prepared migration files.
Given that postbuild step is not possible in nx (as far as i have searched) i have to rollback to older versions of nx.
