### ISSUE TITLE
package.json scripts don't work when using `yarn bin _`

### ISSUE THREAD

**Issue by mrjackdavis** [nrwl/nx#10973]
## Current Behavior

Given `workspaces/mypkg/package.json` contains

```
{
  scripts:{
    test: "node $(yarn bin jest)"
  }
}
```

Running `yarn nx test mypkg` yields `MODULE_NOT_FOUND`

<img width="636" alt="Screen Shot 2022-07-01 at 12 48 12 pm" src="https://user-images.githubusercontent.com/1670700/176813845-78c6ad57-8a6c-4a28-ae57-b66cca8b4573.png">

## Expected Behavior

Given `workspaces/mypkg/package.json` contains

```
{
  scripts:{
    test: "node $(which jest)"
  }
}
```

Running the script produces the correct behaviour (i.e. it doesn't fail). This bug is only evident when running scripts via NX

## Steps to Reproduce

1. Take any nx repo which uses yarn 1 (not sure if this affects other yarn versions)
2. Replace a `package.json` script with the `yarn bin` version of the command. e.g. `"test":"jest"` becomes `"test":"node $(yarn bin jest)"`
3. Run the command `yarn nx test mypkg`

### Failure Logs

```
REDACTED/node_modules/.bin/jest'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

### Environment

```
 >  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : darwin x64
   yarn : 1.22.10

   nx : 14.3.6
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.6
   @nrwl/js : Not Found
   @nrwl/linter : 14.3.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.3.6
   typescript : 4.4.4
   ---------------------------------------
   Community plugins:
   	 @nx-aws-plugin/nx-aws-cache: 1.1.0
```

**Comment by FrozenPandaz** [comment]
I can't reproduce this issue. For me, this works properly:

![image](https://user-images.githubusercontent.com/8104246/181839611-ec8fb2fd-80a0-43c0-a2dd-b64b471005b9.png)

Could you please provide a repo that exhibits the issue? Please make sure you have `jest` installed locally in the workspace.

If you have `jest` installed globally but not in the repo, `which jest` will succeed whereas `yarn bin jest` will fail:

```sh
jason@pop-os ~/p/t/yarn-bin-test (main)> which jest
/usr/local/bin/jest
jason@pop-os ~/p/t/yarn-bin-test (main)> yarn bin jest
error Couldn't find a binary named "jest"
```
