### ISSUE TITLE
Storybook: consumer.computeColumnSpans is not a function

### ISSUE THREAD

**Issue by timtos** [nrwl/nx#10979]
## Current Behavior
I created a new nx workspace and added a component to the app -> Everything is working fine.
Then I added storybook and wanted to start it: Now I get an error message

## Expected Behavior
Storybook should work out of the box

## Steps to Reproduce
Create a workspace from scratch and add storybook.

**A sample repository can be found** [here](https://github.com/timtos/acme).
If you try to build or run storybook, you'll get the error message below:

### Failure Logs
ERR! => Failed to build the preview
ERR! Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
ERR! TypeError: C:\Code\Nx\acme\libs\awesome\.storybook\preview.js-generated-config-entry.js: consumer.computeColumnSpans is not a function
ERR!     at buildMappingData (C:\Code\Nx\acme\node_modules\@angular-devkit\build-angular\node_modules\@babel\core\lib\transformation\file\merge-map.js:144:12)
ERR!     at mergeSourceMap (C:\Code\Nx\acme\node_modules\@angular-devkit\build-angular\node_modules\@babel\core\lib\transformation\file\merge-map.js:19:17)
ERR!     at generateCode (C:\Code\Nx\acme\node_modules\@angular-devkit\build-angular\node_modules\@babel\core\lib\transformation\file\generate.js:72:39)
ERR!     at run (C:\Code\Nx\acme\node_modules\@angular-devkit\build-angular\node_modules\@babel\core\lib\transformation\index.js:53:33)
ERR!     at run.next (<anonymous>)
ERR!     at Function.transform (C:\Code\Nx\acme\node_modules\@angular-devkit\build-angular\node_modules\@babel\core\lib\transform.js:25:41)
ERR!     at transform.next (<anonymous>)
ERR!     at step (C:\Code\Nx\acme\node_modules\gensync\index.js:261:32)
ERR!     at C:\Code\Nx\acme\node_modules\gensync\index.js:273:13
ERR!     at async.call.result.err.err (C:\Code\Nx\acme\node_modules\gensync\index.js:223:11)
ERR! Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
ERR! TypeError: C:\Code\Nx\acme\storybook-init-framework-entry.js: consumer.computeColumnSpans is not a function
ERR!     at buildMappingData (C:\Code\Nx\acme\node_modules\@angular-devkit\build-angular\node_modules\@babel\core\lib\transformation\file\merge-map.js:144:12)
ERR!     at mergeSourceMap (C:\Code\Nx\acme\node_modules\@angular-devkit\build-angular\node_modules\@babel\core\lib\transformation\file\merge-map.js:19:17)
ERR!     at generateCode (C:\Code\Nx\acme\node_modules\@angular-devkit\build-angular\node_modules\@babel\core\lib\transformation\file\generate.js:72:39)
ERR!     at run (C:\Code\Nx\acme\node_modules\@angular-devkit\build-angular\node_modules\@babel\core\lib\transformation\index.js:53:33)
ERR!     at run.next (<anonymous>)
ERR!     at Function.transform (C:\Code\Nx\acme\node_modules\@angular-devkit\build-angular\node_modules\@babel\core\lib\transform.js:25:41)
ERR!     at transform.next (<anonymous>)
ERR!     at step (C:\Code\Nx\acme\node_modules\gensync\index.js:261:32)
ERR!     at C:\Code\Nx\acme\node_modules\gensync\index.js:273:13
ERR!     at async.call.result.err.err (C:\Code\Nx\acme\node_modules\gensync\index.js:223:11)
ERR! Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
ERR! TypeError: C:\Code\Nx\acme\node_modules\slash\index.js: consumer.computeColumnSpans is not a function
ERR!     at buildMappingData (C:\Code\Nx\acme\node_modules\@angular-devkit\build-angular\node_modules\@babel\core\lib\transformation\file\merge-map.js:144:12)
ERR!     at mergeSourceMap (C:\Code\Nx\acme\node_modules\@angular-devkit\build-angular\node_modules\@babel\core\lib\transformation\file\merge-map.js:19:17)
ERR!     at generateCode (C:\Code\Nx\acme\node_modules\@angular-devkit\build-angular\node_modules\@babel\core\lib\transformation\file\generate.js:72:39)
ERR!     at run (C:\Code\Nx\acme\node_modules\@angular-devkit\build-angular\node_modules\@babel\core\lib\transformation\index.js:53:33)
ERR!     at run.next (<anonymous>)
ERR!     at Function.transform (C:\Code\Nx\acme\node_modules\@angular-devkit\build-angular\node_modules\@babel\core\lib\transform.js:25:41)
ERR!     at transform.next (<anonymous>)
ERR!     at step (C:\Code\Nx\acme\node_modules\gensync\index.js:261:32)
ERR!     at C:\Code\Nx\acme\node_modules\gensync\index.js:273:13
ERR!     at async.call.result.err.err (C:\Code\Nx\acme\node_modules\gensync\index.js:223:11)
ERR! C:/Code/Nx/acme/libs/awesome/src/index.ts is part of the TypeScript compilation but it's unused.
ERR! Add only entry points to the 'files' or 'include' properties in your tsconfig.
ERR! C:/Code/Nx/acme/libs/awesome/src/lib/awesome.module.ts is part of the TypeScript compilation but it's unused.
ERR! Add only entry points to the 'files' or 'include' properties in your tsconfig.
ERR! C:/Code/Nx/acme/libs/awesome/src/test-setup.ts is part of the TypeScript compilation but it's unused.
ERR! Add only entry points to the 'files' or 'include' properties in your tsconfig.
ERR! Error: => Webpack failed, learn more with --debug-webpack
ERR!     at C:\Code\Nx\acme\node_modules\@storybook\builder-webpack5\dist\cjs\index.js:234:62
ERR!     at C:\Code\Nx\acme\node_modules\webpack\lib\HookWebpackError.js:68:3
ERR!     at Hook.eval [as callAsync] (eval at create (C:\Code\Nx\acme\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Code\Nx\acme\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
ERR!     at Cache.shutdown (C:\Code\Nx\acme\node_modules\webpack\lib\Cache.js:150:23)
ERR!     at C:\Code\Nx\acme\node_modules\webpack\lib\Compiler.js:1225:15
ERR!     at Hook.eval [as callAsync] (eval at create (C:\Code\Nx\acme\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Code\Nx\acme\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
ERR!     at Compiler.close (C:\Code\Nx\acme\node_modules\webpack\lib\Compiler.js:1218:23)
ERR!     at C:\Code\Nx\acme\node_modules\@storybook\builder-webpack5\dist\cjs\index.js:233:20
ERR!  Error: => Webpack failed, learn more with --debug-webpack
ERR!     at C:\Code\Nx\acme\node_modules\@storybook\builder-webpack5\dist\cjs\index.js:234:62
ERR!     at C:\Code\Nx\acme\node_modules\webpack\lib\HookWebpackError.js:68:3
ERR!     at Hook.eval [as callAsync] (eval at create (C:\Code\Nx\acme\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Code\Nx\acme\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
ERR!     at Cache.shutdown (C:\Code\Nx\acme\node_modules\webpack\lib\Cache.js:150:23)
ERR!     at C:\Code\Nx\acme\node_modules\webpack\lib\Compiler.js:1225:15
ERR!     at Hook.eval [as callAsync] (eval at create (C:\Code\Nx\acme\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Code\Nx\acme\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
ERR!     at Compiler.close (C:\Code\Nx\acme\node_modules\webpack\lib\Compiler.js:1218:23)
ERR!     at C:\Code\Nx\acme\node_modules\@storybook\builder-webpack5\dist\cjs\index.js:233:20

Broken build, fix the error above.
You may need to refresh the browser.

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build-storybook for project awesome (56s)

    ×    1/1 failed
    √    0/1 succeeded [0 read from cache]

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command yarn nx run awesome:build-storybook" terminated with exit code: 1.

### Environment
Node : 16.13.2
   OS   : win32 x64
   yarn : 1.22.5

   nx : 14.1.9
   @nrwl/angular : 14.1.9
   @nrwl/cypress : 14.1.9
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.9
   @nrwl/eslint-plugin-nx : 14.1.9
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.9
   @nrwl/js : Not Found
   @nrwl/linter : 14.1.9
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.9
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.9
   typescript : 4.6.4

**Comment by mandarini** [comment]
Hi there @timtos ! Thanks for filing an issue and for including a sample repository, too!

Unfortunately, I could not reproduce your issue, using your repository. I could not reproduce your issue, neither, when using a new Nx workspace.

[Here is the output](https://app.warp.dev/block/gF73cv0v6RYOrF7FSmpJbX) of running `nx storybook awesome`. 

And here is my `nx report`:

```
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.0
   OS   : darwin x64
   yarn : 1.22.17

   nx : 14.4.0
   @nrwl/angular : 14.4.0
   @nrwl/cypress : 14.4.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.0
   @nrwl/eslint-plugin-nx : 14.4.0
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.0
   @nrwl/js : 14.4.0
   @nrwl/linter : 14.4.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 999.9.1
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.0
   @nrwl/web : 14.4.0
   @nrwl/workspace : 14.4.0
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
   	 @storybook/angular: 6.5.9
```

**Comment by timtos** [comment]
Hey @mandarini, thank you for your support. It is working on another machine for me, too, so I guess, I am having some cache issues. I'll close this for now, as it doesn't seem to be code related. Thanks again!
