### ISSUE TITLE
Cannot import a @nrwl/js:lib into @nrwl/react:app 

### ISSUE THREAD

**Issue by afgallo** [nrwl/nx#10990]
## Current Behavior
I've generated a workspace that contains the following structure, all generated from their default nrwl generators. I don't use typescript so all generators were run using `--js` flag.:

```
├─ apps
├── app **-> React App**
│   ├── jest.config.ts
│   ├── postcss.config.js
│   ├── project.json
│   ├── src
│   ├── tailwind.config.js
│   ├── tsconfig.app.json
│   ├── tsconfig.json
│   └── tsconfig.spec.json
├── app-e2e
│   ├── cypress.json
│   ├── project.json
│   ├── src
│   └── tsconfig.json
├─ libs
├── api **-> JS library**
│   ├── README.md
│   ├── jest.config.js
│   ├── package.json
│   ├── project.json
│   ├── src
│   ├── tsconfig.json
│   ├── tsconfig.lib.json
│   └── tsconfig.spec.json
├── data **-> React library**
│   ├── README.md
│   ├── jest.config.js
│   ├── project.json
│   ├── src
│   ├── tsconfig.json
│   ├── tsconfig.lib.json
│   └── tsconfig.spec.json
└── ui **-> React library**
    ├── README.md
    ├── jest.config.js
    ├── project.json
    ├── src
    ├── tsconfig.json
    ├── tsconfig.lib.json
    └── tsconfig.spec.json
```

When trying to import modules from `api` into `data`, I get the following error:

```
ERROR in ../../libs/api/src/index.js 3:0
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (3:0)
File was processed with these loaders:
 * ../../node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
 * ../../node_modules/@nrwl/web/src/utils/web-babel-loader.js
You may need an additional loader to handle the result of these loaders.
| __webpack_require__.$Refresh$.runtime = require('/xxx/xxx/Code/xxx/xxx-platform/node_modules/react-refresh/runtime.js');
|
> export * from './posts/read';
|
| const $ReactRefreshModuleId$ = __webpack_require__.$Refresh$.moduleId;
```

## Expected Behavior
I expect to be able to import files from `api` in `data` with no errors.

## Steps to Reproduce
1. Generate a workspace by running `npx create-nx-workspace --preset=react`
2. Add api library by running `nx g @nrwl/js:library api --js`
3. Add data library by running `nx g @nrwl/react:library data --js`
4. Import modules from api into data
5. Import modules from data into app
6. Run `nx serve app:serve:development`

### Environment
   Node : 16.15.0
   OS   : darwin arm64
   npm  : 8.12.1

   nx : 14.4.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.4.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.0
   @nrwl/eslint-plugin-nx : 14.4.0
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.0
   @nrwl/js : 14.4.0
   @nrwl/linter : 14.4.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.4.0
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.0
   @nrwl/web : 14.4.0
   @nrwl/workspace : 14.4.0
   typescript : 4.7.3

Thank for your help!

**Comment by afgallo** [comment]
I've been experimenting a bit and have realised that if I run `nx g @nrwl/js:library api --js --buildable=false` it all seem to work. Is this the intended behaviour?

**Comment by michelepatrassi** [comment]
same here. A fix seems to convert all the JS files to TS, else I cannot have a publishable library which I can also consume in a monorepo app

**Comment by gxxcastillo** [comment]
If anyone else stumbles on this, I added the following from @jaysoo's fix to my old webpack config file and it did the trick 🥳 

```
    {
      test: /\.js$/,
      type: 'javascript/auto',
    },
```
