### ISSUE TITLE
Better @nrwl/nx-plugin testing utils

### ISSUE THREAD

**Issue by ZachJW34** [nrwl/nx#10992]
## Description

Hey nrwl team! I'm the author of the [nx-plus](https://github.com/ZachJW34/nx-plus) plugins

The utils provided from `@nrwl/nx-plugin` for testing purposes work pretty well but I've noticed a few things:

- There is no option for providing what package manager to use when [invoking cli commands](https://github.com/nrwl/nx/blob/3b1ea739f911b4655e33fdced5708140ebadc59c/packages/nx-plugin/src/utils/testing-utils/nx-project.ts#L81). I use `yarn` in my repo but CIinvokes `npm` when scaffolding tmp projects.
- I have to strip ansii colors from command output

It seems like all of these problems have been solved by the internal tooling located in [e2e/utils](https://github.com/nrwl/nx/blob/master/e2e/utils/index.ts). It would be great if either the `nx-plugin` package was updated or these utils were published instead. The code in both locations looks the same, so a good chance to remove some duplication.

## Motivation
Make it easier for plugin authors to e2e test their plugins

## Suggested Implementation
Update `@nrwl/nx-plugin/testing` to have the same API as `e2e/utils`. It would be nice as a plugin author to use the same API used internally to test plugins.

## Alternate Implementations
Either reuse the same code in both locations or do a good ol copy and paste if the team wants to keep their e2e utils internal.

**Comment by jkavalec** [comment]
This is rather unpleasant, everything is there, but you cant use it for testing your plugins 😞

**Comment by khalilou88** [comment]
Hope this issue will be resolved, i need many functions from `nx e2e testing` like `runNxCommandUntil`.

**Comment by FrozenPandaz** [comment]
Our e2e testing strategy for plugins has changed quite a bit since we released the verdaccio support.

If you want any e2e testing utils, please create a new issue for the specific util you would like.
