### ISSUE TITLE
Mfe angular application to share external npm packages Nx workspace

### ISSUE THREAD

**Issue by anandjaisy** [nrwl/nx#10997]
Trying to share external npm library among MFE applications using `"@nrwl/angular": "^14.4.0",`

created a base `module-federation.config.js` and added the library

```
const coreLibraries = new Set([
  '@ckeditor/ckeditor5-build-classic',
  '@ckeditor/ckeditor5-angular',
]);
module.exports = {
  shared: (libraryName, defaultConfig) => {
    if (coreLibraries.has(libraryName)) {
      console.log(libraryName); // The library never occurs here
      return defaultConfig;
    }
    return false;
  },
};
```

In the `coreLibraries.has(libraryName)` condition the library is not present and hence facing the exception as

```
ERROR Error: Uncaught (in promise): CKEditorError: ckeditor-duplicated-modules
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules
CKEditorError: ckeditor-duplicated-modules
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules
    at ckeditor.js:6:316950
    at ckeditor.js:6:315303
    at ckeditor.js:6:217
    at ckeditor.js:6:80
    at 9949 (ckeditor.js:6:1)
    at __webpack_require__ (bootstrap:19:1)
    at 8210 (core.mjs:1831:1)
    at __webpack_require__ (bootstrap:19:1)
    at 373 (entry.component.html:7:63)
    at __webpack_require__ (bootstrap:19:1)
    at resolvePromise (zone.js:1211:31)
    at resolvePromise (zone.js:1165:17)
    at zone.js:1278:17
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26510:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:585:35) 
```

The issue occurred because in other mfe the module is included again (multiple times)

In the` package.json` I have the below dependencies

```
"dependencies": {
    "@ckeditor/ckeditor5-angular": "^4.0.0",
    "@ckeditor/ckeditor5-build-classic": "^34.2.0"
}
```
During the build, there are no logs on the console, because `@ckeditor/ckeditor5-angular` is not present.

How do we share npm libraries in all MFE, it is supposed to be done by module-federation.config.js

**Comment by Coly010** [comment]
Perhaps our docs need improved a little.

The Module federated app will only share the npm dependencies it uses. If two different apps need them, but it's not used by one of them, then there's an option that you can provide to the configuration within `module-federation.config.js` that will allow you to share them.

This property is `additionalShared`

and it can be used as such:

```js
module.exports = {
  ...,
  additionalShared: ['@ckeditor/ckeditor5-angular']
}
```

**Comment by anandjaisy** [comment]
Including the additionalShared to the host application

```
module.exports = {
  name: 'host',
  remotes: ['product', 'order', 'discount'],
  additionalShared: ['@ckeditor/ckeditor5-angular'],
};
```

Getting an exception on serve `nx serve host --open --devRemotes=product,discount,order`

```
> nx run host:serve:development --open=true --devRemotes=product,discount,order

⠋ Generating browser application bundles (phase: setup)...⠋ Generating browser application bundles (phase: setup)...⠋ Generating browser application bundles (phase: setup)...⠋ Generating browser application bundles (phase: setup)...
 >  NX   The specified dependency "@ckeditor/ckeditor5-angular" in the additionalShared configuration does not exist in the project graph. Please check your additionalShared configuration and make sure you are including valid workspace projects or npm packages.

   Pass --verbose to see the stacktrace.
```

**Comment by Coly010** [comment]
Awesome, this was fixed in: https://github.com/nrwl/nx/pull/11018 and will be released soon!

I'll close this issue as it has been addressed :) keep an eye on the releases for when this lands :)

**Comment by timothylombrana** [comment]
@Coly010 will `additionalShared` option still work if we're using this [Advanced Angular Micro Frontends with Dynamic Module Federation](https://nx.dev/recipes/module-federation/dynamic-module-federation-with-angular)

**Comment by timothylombrana** [comment]
> @Coly010 Including the additionalShared to the host application
> 
> ```
> module.exports = {
>   name: 'host',
>   remotes: ['product', 'order', 'discount'],
>   additionalShared: ['@ckeditor/ckeditor5-angular'],
> };
> ```
> 
> Getting an exception on serve `nx serve host --open --devRemotes=product,discount,order`
> 
> ```
> > nx run host:serve:development --open=true --devRemotes=product,discount,order
> 
> ⠋ Generating browser application bundles (phase: setup)...⠋ Generating browser application bundles (phase: setup)...⠋ Generating browser application bundles (phase: setup)...⠋ Generating browser application bundles (phase: setup)...
>  >  NX   The specified dependency "@ckeditor/ckeditor5-angular" in the additionalShared configuration does not exist in the project graph. Please check your additionalShared configuration and make sure you are including valid workspace projects or npm packages.
> 
>    Pass --verbose to see the stacktrace.
> ```
> 
> **Package.json**
> 
> ```
> "@ckeditor/ckeditor5-angular": "^4.0.0",
>     "@ckeditor/ckeditor5-build-classic": "^34.2.0",
> ```

@anandjaisy did you figure this out?
