### ISSUE TITLE
"ng generate lib mymodule" not working as described in docs

### ISSUE THREAD

**Issue by jaufgang** [nrwl/nx#110]
according to the documentation 
```
ng generate lib mymodule
```
should generate the following files
```
libs/mymodule/src/mymodule.module.spec.ts
libs/mymodule/src/mymodule.module.ts
libs/mymodule/index.ts
```
however when I execute that command i get 
```
$ ng generate lib mymodule
  create libs/mymodule/src/mymodule.spec.ts (149 bytes)
  create libs/mymodule/src/mymodule.ts (26 bytes)
  create libs/mymodule/index.ts (41 bytes)
  update .angular-cli.json (2112 bytes)
```

Note that this is the expected output of running the command with the ` --nomodule` option, but  I have not used that option.

**Comment by vsavkin** [comment]
Could you provide a repro? Also, make sure you are using nx >= 0.2.0?

**Comment by jaufgang** [comment]
Not sure what you mean by "provide a repro".   I just installed nx today following the instructions at https://nrwl.io/nx/guide-getting-started, ran a few commands and these are the results I see.  In my original post, I pasted the output of the `ng generate lib mymodule` command straight from the terminal.  

Just checked package versions, and i've got `@nrwl/nx@0.1.0`,`@nrwl/schematics@0.1.0`

but those are the versions i got by running
```
$ yarn global add @nrwl/schematics
$ ng new myprojectname --collection=@nrwl/schematics
```

**Comment by vsavkin** [comment]
It's possible that you are running the ng command installed by npm. So `yarn global add @nrwl/schematics` installs the package that the ng command doesn't see.

You can check if the package is installed properly as follows:
 * Run  `yarn global dir`,
* `cd` into that folder, and run the following:`cat node_modules/@nrwl/schematics/package.json`

If you see 0.2.0, it means that the package is installed properly and you are running ng installed via npm.

You can also use this helper script instead:

```
curl -fsSL https://raw.githubusercontent.com/nrwl/nx/master/packages/install/install.sh | bash -s myprojectname
```

**Comment by vsavkin** [comment]
Closing this issue

**Comment by jaufgang** [comment]
That did it, thanks!
