### ISSUE TITLE
Jest can't compile AMD dependencies

### ISSUE THREAD

**Issue by flexwie** [nrwl/nx#11017]
## Current Behavior
When running unit test with jest libraries and react apps that depend on a module with is compiled with AMD set as the module target in its tsconfig. When building the app, the dependency gets compiled correctly.

## Expected Behavior
Jest/Babel compile AMD modules to CommonJS or UMD.

## Steps to Reproduce
Create a react library that imports "azure-devops-extension-sdk" (in our case) and run the test target.

### Failure Logs
● Test suite failed to run

    ReferenceError: define is not defined

    > 1 | import * as SDK from "azure-devops-extension-sdk";
        | ^
      2 | import {
      3 |   IExtensionDataManager,
      4 |   IExtensionDataService,

      at Object.<anonymous> (../../node_modules/azure-devops-extension-sdk/SDK.js:44:1)

### Environment
````
  Node : 16.14.2
  OS   : darwin arm64
  npm  : 8.5.0
  
  nx : 13.7.3
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.6
  @nrwl/cypress : 13.4.6
  @nrwl/devkit : 13.4.6
  @nrwl/eslint-plugin-nx : 13.4.6
  @nrwl/express : undefined
  @nrwl/jest : 13.4.6
  @nrwl/linter : 13.4.6
  @nrwl/nest : 13.4.6
  @nrwl/next : 13.7.3
  @nrwl/node : 13.4.6
  @nrwl/nx-cloud : 13.1.2
  @nrwl/react : 13.4.6
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.6
  @nrwl/web : 13.4.6
  @nrwl/workspace : 13.4.6
  @nrwl/storybook : 13.4.6
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.5.2
  ---------------------------------------
  Community plugins:
         @nestjs/azure-func-http: 0.8.0
````

**Comment by AgentEnder** [comment]
Hey @flexwie, it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

**Comment by flexwie** [comment]
Hey @AgentEnder, thanks for your reply. I updated nx as per your instructions to the latest version (see report output below), but the issue still remains. AMD dependencies (`azure-devops-extension-sdk` in our case) are not compiled.
I assume that that compiling in the build is done by webpack. Is there a way to add that to the preprocessing for jest as well (not a webpack expert here)?

`
   Node : 16.14.2
   OS   : darwin arm64
   npm  : 8.5.0
   
   nx : 14.4.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.2
   @nrwl/eslint-plugin-nx : 14.4.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.2
   @nrwl/js : 14.4.2
   @nrwl/linter : 14.4.2
   @nrwl/nest : 14.4.2
   @nrwl/next : 14.4.2
   @nrwl/node : 14.4.2
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.4.2
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.2
   @nrwl/web : 14.4.2
   @nrwl/workspace : 14.4.2
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
         @nestjs/azure-func-http: 0.8.0
`

P.S.: The migrations don't like trailing commas in arrays in the tsconfig files. Not hard to debug, but the error message is not really helpful.

**Comment by barbados-clemens** [comment]
can you share your project level jest config? You should be able to just add/update the transformIgnorePatterns to have that package be transformed for jest to understand it.
