### ISSUE TITLE
(regression) Command line arguments not passed to dependent tasks

### ISSUE THREAD

**Issue by Bielik20** [nrwl/nx#11014]
Exactly that: https://github.com/nrwl/nx/issues/7136

I was also trying to tackle it here: https://github.com/nrwl/nx/issues/9034#issuecomment-1164228805

### Environment

```
   Node : 16.15.1
   OS   : darwin arm64
   npm  : 8.11.0

   nx : 14.4.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.4.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.1
   @nrwl/eslint-plugin-nx : 14.4.1
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.1
   @nrwl/js : 14.4.1
   @nrwl/linter : 14.4.1
   @nrwl/nest : Not Found
   @nrwl/next : 14.4.1
   @nrwl/node : 14.4.1
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.4.1
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.1
   @nrwl/web : 14.4.1
   @nrwl/workspace : 14.4.1
   typescript : 4.7.4
```

**Comment by tanepiper** [comment]
Also https://github.com/nrwl/nx/issues/10844

**Comment by Bielik20** [comment]
@leosvelperez Can we reopen this, since the issue has not been fixed?

**Comment by chrizza87** [comment]
Please reopen. the issue has not been fixed. tested it yesterday

**Comment by martinsik** [comment]
I think I'm experiencing the same issue with Nx@13.

**Comment by bruno333** [comment]
I also have the issue, which prevents me from upgrading all my apps. Can we reopen or should we create a new issue?
