### ISSUE TITLE
`--framework=none` fail with error:   service.ts does not exist

### ISSUE THREAD

**Issue by xmlking** [nrwl/nx#1102]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

`ng g lib data --framework=none  -d` should generate typescript module

## Failure Information (for bugs)

`Error .service.ts does not exist.`

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.
```
$ ng g lib data --framework=none  -d
? In which directory should the library be generated? 
? Which module should import the library? 
? Which stylesheet format would you like to use? CSS
? Would you like to add a routing configuration to the library? No
? Will this library be lazy loaded? No
? Which tags would you like to add to the library? (used for linting) 
Path "/libs/data/src/lib/data.service.ts" does not exist.
```

### Context

Please provide any relevant information about your setup:

project: https://github.com/xmlking/ngx-starter-kit

```
Angular CLI: 8.0.0-beta.2
Node: 11.10.0
OS: darwin x64
Angular: 8.0.0-beta.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.3
@angular-devkit/build-angular      0.13.3
@angular-devkit/build-ng-packagr   0.13.3
@angular-devkit/build-optimizer    0.13.3
@angular-devkit/build-webpack      0.13.3
@angular-devkit/core               7.3.3
@angular-devkit/schematics         7.3.3
@angular/cdk                       7.3.3
@angular/cli                       8.0.0-beta.2
@angular/flex-layout               7.0.0-beta.23
@angular/material                  7.3.3
@angular/pwa                       0.13.3
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.3
@schematics/angular                7.3.3
@schematics/update                 0.14.0-beta.2
ng-packagr                         4.7.1
rxjs                               6.4.0
typescript                         3.1.6
webpack                            4.29.0
```

**A minimal reproduce scenario using allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

Please include any relevant log snippets or files here.

## Other

Any other relevant information that will help us help you.

**Comment by FrozenPandaz** [comment]
This is related to the breaking change described in https://github.com/nrwl/nx/issues/1096.

Angular CLI 7.3.3 contains some breaking changes for Nx so please make sure you're using `7.3.1`.
