### ISSUE TITLE
Reassembly doesn't work

### ISSUE THREAD

**Issue by WCN-llc** [nrwl/nx#11031]
Hi,
1. Create a new project (the current version of NX is - Angular&Nest );
2. Building an Angular project: npx nx build project;
3. Uploading the assembly to the production server;
4. Making changes to the project;
5. Building the project after making changes: npx nx build project;
6. Uploading the assembly to the production server;
And nothing has changed after the update on the server. Only the first assembly remains.

**Comment by WCN-llc** [comment]
Understood.
My mistake.
nx build name-project --skip-nx-cache

**Comment by AgentEnder** [comment]
Hey @WCN-llc, is this still occurring for you or can the issue be closed out? You shouldn't need to skip the cache but without some more info regarding your setup it would be hard to troubleshoot further.
