### ISSUE TITLE
Package.json as a project - optin 

### ISSUE THREAD

**Issue by shairez** [nrwl/nx#11033]
## Description

A configurtaion option for `nx.json` that says if I'm interested in making ALL package.json files as "project files" or just the ones who contain a special property. 

It's like the opposite of `ignore": true`

## Motivation
Recently I've added nx to an existing project with lots of legacy projects.
When I wanted to build I realized it is failing because nx finds all of those legacy `package.json` and try to reason about their node_modules etc...

I'd like to just mark a handful of projects under the control of nx, not ALL of the package.json files in the entire repo.

## Suggested Implementation

In `nx.json` :
---------
```
"explicitPackageJsonAsProject": true`
```

And in `package.json` :
---------------------
```
"nx": {
    "project": true
  }
```

**Comment by shairez** [comment]
so... WDYT? :)

**Comment by AgentEnder** [comment]
Talked a bit with @shairez elsewhere. This was resolved when we started only using package.json fields that were indicated by npm/pnpm/yarn workspaces.
