### ISSUE TITLE
@nrwl/js:lib with secondary entry points not respecting tsconfig paths

### ISSUE THREAD

**Issue by MRDNZ** [nrwl/nx#11037]
## Current Behavior

Building a (framework agnostic) js/ts library with secondary entry points is failing and throwing errors because the compiler is not able to resolve the modules specified in the compilerOptions.paths from the tsconfig.

This is the errors that are being throwed look like this: `Cannot find module '@example/npm-scope/secondary-entrypoint' or its corresponding type declarations.`.

After debugging and trying different approaches like splitting up build steps myself I got it to work. BUT this is not reliable at all and it makes me deviate from the nx workflow, I'd rather see a proper solution. 

What I noticed eventually after diving in the source code of the `@nrwl/js:tsc` executor the following things are happening.

1. The `tscExecutor` function is checking if there is a `tmpTsConfig` available and if so it will overwrite the `options.tsConfig` with this.
![image](https://user-images.githubusercontent.com/21969501/177547936-deb7dbf4-0340-4947-8879-90111add210b.png)

2. The `checkDependencies` function that can return a `tmpTsConfig` shows that there is no possible way to configure this and it only checks if there are dependencies. If so, it will generate a config file for you.
![image](https://user-images.githubusercontent.com/21969501/177548936-934f9f1d-0941-44ef-a7e0-4331c49b8782.png)

3. The `createTmpTsConfig` function takes the original tsconfig file and will create a new temp tsconfig file for you containing the remapped paths, but these paths are not configurable. Which is strange because we specificy our own paths in our own tsconfig.
![image](https://user-images.githubusercontent.com/21969501/177550811-01817779-95e1-4ea2-b398-2bd66a7a30f7.png)
In the `updatePaths` function you can see that there is a mapping using from `dep.outputs` this can be found in the configuration from the `project.json`:

```json
{
  "$schema": "..\\..\\..\\node_modules\\nx\\schemas\\project-schema.json",
  "sourceRoot": "libs/npm-scope/secondary-entrypoint/src",
  "projectType": "library",
  "targets": {
    "build": {
      "executor": "@nrwl/js:tsc",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/libs/npm-scope/secondary-entrypoint",
        "main": "libs/npm-scope/secondary-entrypoint/src/index.ts",
        "tsConfig": "libs/npm-scope/secondary-entrypoint/tsconfig.lib.json",
        "assets": ["libs/npm-scope/secondary-entrypoint/*.md"]
      }
    }
  }
}
```

If you comment out the following line from the `createTmpTsConfig` function `process.on('exit', () => cleanupTmpTsConfigFile(tmpTsConfigPath));` you can see the generated result that is being used. Even with my `tsconfig.base.json` specifying the paths that need to be used, this generated file does not respect the paths and overwrites them causing the build to fail.

So looking at this I thought it probably would be possible to define an additional output from the project.json, referencing the path(s) I want to use (that I also use in the tsconfig.base). But it seems to be causing another error so that wont work either:
`File 'C:/Users/yes/Projects/no/example/libs/npm-scope/secondary-entrypoint-one/src/index.ts' is not under 'rootDir' 'libs/npm-scope/secondary-entrypoint-two'. 'rootDir' is expected to contain all source files.`

Side note: running an application that is consuming this library with entry-points is no problem at all, which is also quite strange indicating inconsistent rules/behaviour for development environment vs build/production environments. This just works using the tsconfig.base paths and no errors are being throw.

This is also one of the pro's using paths, so you can reference build libraries from your dist or directly from source (libs), so you can test specific environment scenarios.

## Expected Behavior

It is expected behavior that (same as creating angular libraries with secondary-entrypoints) you can compose libraries and entrypoints to your needs. If I for example want to create a structure as following it should be able to see which libs/entry-points are being used, they should be build in the correct order and also respect the paths from where it should resolve the modules from.

```
libs/
  /entities
    /interfaces
    /models
    /....
    /....
    /src
```
    
In this particular case it should be able to do the following.

1. Define interfaces in the `@example/entities/interfaces` scope of the package.
2. Define models in the `@example/entities/models` scope of the package and utilize `@example/entities/interfaces`
3. Expose all entrypoints from the root package `@example/entities` for the users that need all availabe entry-points

## Steps to Reproduce

Generate a new workspace with a js lib containing 2 entrypoints. Expected behaviour can be used as an example.

### Workaround
1. If I comment out the following part from the `tscExecutor` function everything works as expected (with the use of my own defined paths in the original tsconfig):

```js
        // if (tmpTsConfig) {
        //     options.tsConfig = tmpTsConfig;
        // }
```

### Failure Logs

-

### Environment

 ```
   Node : 18.3.0
   OS   : win32 x64
   yarn : 1.22.15

   nx : 14.2.1
   @nrwl/angular : 14.3.6
   @nrwl/cypress : 14.2.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : 14.2.1
   @nrwl/express : Not Found
   @nrwl/jest : 14.2.1
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.2.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.3.6
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.3.6
   @nrwl/web : 14.2.2
   @nrwl/workspace : 14.2.1
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:

 ```

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by gund** [comment]
I also need secondary entry points support with this TS executor!

Would be nice to see a similar support that was implemented in `ng-packagr` where you just drop a config file in the subfolder and it is magically recognized and compiled as a secondary entry point.

**Comment by yharaskrik** [comment]
This is not stale. A secondary entry point generator for js/ts libs would be great

**Comment by itea-dev** [comment]
We also need secondary entry points in typescript libraries.
