### ISSUE TITLE
Support Storybook test-runner

### ISSUE THREAD

**Issue by Djiit** [nrwl/nx#11047]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
I'd like to see support for [Storybook Test Runner](https://storybook.js.org/docs/react/writing-tests/test-runner).

## Motivation
it's becoming the de-facto way of testing components (compared to creating a separated cypress config).

## Suggested Implementation
Not sure how to help/where to start. I guess a `test-storybook` executor ?

## Alternate Implementations
One could forge a workaround using the `run-commands` executors, but it won't scale well :).

Thanks for the awesome work team!

**Comment by mandarini** [comment]
Hi there @Djiit ! Actually, here is what I would do:

1. Try to set up Storybook Test Runner in an existing Nx workspace with Storybook - with Angular and with React.
2. See what changes need to be made
3. If for example, you only needed to create a new target inside `project.json` that references/calls the test-runner script, all I would is I would write a generator that generates/adds this target on `project.json` and installs the necessary dependencies.
4. If it was a very small change that I needed to make in my workspace to get tets-runner to work, I would maybe even just write a docs page on how to set up test-runner on Nx
5. Maybe I would not create a new executor (too much trouble) if I could just set test-runner in an existing workspace as a new target for example


So, let me know what you think!

**Comment by Djiit** [comment]
Sounds clear to me, thank you. i'll give it a shot ASAP :)

**Comment by Djiit** [comment]
Just gave a first stab at it. Added a test. How can I easly test it locally within a project ?

**Comment by mandarini** [comment]
@Djiit 
The best way to do it is to follow the steps described [here](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#building-the-project). Build `nx` and then publish it with verdaccio to a local registry.

The other way to do it (more sloppy I guess), is to create a Nx workspace normally, and then go in node_modules and make the changes you made to the code.

**Comment by DzmVasileusky** [comment]
@Djiit is storybook test-runner working for you in nx workspace?
For me it can't find any tests. I have tried to call it as mentioned in storybook docs, as you did in your PR and setting up through generator.
But still I am getting `No tests found, exiting with code 1`
https://github.com/storybookjs/test-runner/issues/229
