### ISSUE TITLE
Zombie process after shutting down all relevant nx commands 

### ISSUE THREAD

**Issue by mcmxcdev** [nrwl/nx#11058]
## Current Behavior
I noticed in the system monitor that the script located at `node_modules/nx/src/daemon/server/start.js` keeps running with 0% CPU but 60-200MB memory after shutting down all processes.

## Expected Behavior
Process is killed when all e.g. `nx dev` commands are terminated.

## Steps to Reproduce

- run e.g. `nx dev <project>`
- check system monitor of OS of choice
- see remaining node process with a path to `node_modules/nx/src/daemon/server/start.js`

### Environment
Node : 16.15.0
   OS   : linux x64
   pnpm : 7.5.0
   
   nx : 14.4.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.2
   @nrwl/eslint-plugin-nx : 14.4.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.2
   @nrwl/js : 14.4.2
   @nrwl/linter : 14.4.2
   @nrwl/nest : 14.4.2
   @nrwl/next : 14.4.2
   @nrwl/node : 14.4.2
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.4.2
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.2
   @nrwl/web : 14.4.2
   @nrwl/workspace : 14.4.2
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:

**Comment by NordlingDev** [comment]
@AgentEnder Please see my comment in another thread: https://github.com/nrwl/nx/issues/10822#issuecomment-1172713930

It seems to be related and makes it impossible to rebuild targets without killing this daemon process.
