### ISSUE TITLE
Wrong unitTestRunner and e2eTestRunner after update to 7.6

### ISSUE THREAD

**Issue by mehrad-rafigh** [nrwl/nx#1105]
## Expected Behavior

After updating to version 7.6.2. nrwl sets the `unitTestRunner` to the used Unit Test Runner and the `e2eTestRunner` to the used E2E Test Runner in my `angular.json`. 

## Current Behavior
After updating to version 7.6.2. nrwl sets the `unitTestRunner` to karma and the `e2eTestRunner` to protractor in my `angular.json`. 

### Steps to Reproduce

1. Update to v7.6.2 with ng update
2. check angular.json

### Context
```
Angular CLI: 7.3.3
Node: 10.15.0
OS: darwin x64
Angular: 7.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.3
@angular-devkit/build-angular     0.13.3
@angular-devkit/build-optimizer   0.13.3
@angular-devkit/build-webpack     0.13.3
@angular-devkit/core              7.3.3
@angular-devkit/schematics        7.3.3
@angular/cdk                      7.3.3
@angular/cli                      7.3.3
@angular/flex-layout              7.0.0-beta.23
@angular/material                 7.3.3
@ngtools/webpack                  7.3.3
@schematics/angular               7.3.3
@schematics/update                0.13.3
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.28.4
```

**Comment by FrozenPandaz** [comment]
In `7.6.0`, `jest` and `cypress` are now default.

To keep existing workspaces working as they did, we set the default in `angular.json` to `karma` and `protractor` **_if there was none defined._**

**Comment by mehrad-rafigh** [comment]
I did not see any side-effects, because I changed the values immediately. I will close this issue.
