### ISSUE TITLE
Nx wrongly caches tasks that depends on other self targets that have different inputs

### ISSUE THREAD

**Issue by edusperoni** [nrwl/nx#11055]
## Current Behavior
When running a task that has `inputs`, the nx hasher saves the file inputs as `somelib:$filesets`. When this task depends on another cacheable operation within the same project that has different inputs, `somelib:$filesets` will contain the hash to the dependency (because it builds first) and then it'll reuse that hash for every task:

https://github.com/nrwl/nx/blob/3b1ea739f911b4655e33fdced5708140ebadc59c/packages/nx/src/hasher/hasher.ts#L384

So let's say you have target: build and tool. build has inputs `["{projectRoot}/**/*","!{projectRoot}/sometool/**/*"]` and tool has inputs `"inputs": ["{projectRoot}/sometool/**/*"],`. build depends on tool.

When you run the first time, it'll build `tool` and `build`. Now if you change `src/index.ts`, `build` will not run again because the hasher is **only** caching `${task.target.project}:$filesets`. Both builds will run if you change `sometool/script.sh`

## Expected Behavior
The inputs hashes must be self contained so they don't pollute other targets.

Possible solutions:

Simply change the mapKey (not sure about the implications):
```
    const mapKey = `${task.target.project}:${task.target.target}:$filesets`;
```
Change the mapkey itself to a hash of matched files/inputs array.

## Steps to Reproduce

https://github.com/edusperoni/nx-fileset-cache-issue

1. nx run somelib:build
2. change index.ts
3. nx run somelib:build
4. it'll read it from the cache instead of building

I can open a PR to https://github.com/nrwl/nx-examples later if that's needed

### Failure Logs
`nx run somelib:build  [existing outputs match the cache, left as is]`

### Environment
```
 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : darwin arm64
   npm  : 8.4.1
   
   nx : 14.4.2
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.2
   @nrwl/eslint-plugin-nx : 14.4.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.2
   @nrwl/js : 14.4.2
   @nrwl/linter : 14.4.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.4.2
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
```

**Comment by abrenneke** [comment]
possibly a regression in https://github.com/nrwl/nx/pull/10874?

**Comment by kgdev** [comment]
I've met the same issue.

**Comment by kgdev** [comment]
When can this be fixed?

**Comment by edusperoni** [comment]
An update on this:

it seems this issue is no longer 100% accurate.

Nx now will not break in the same way as before by reusing the wrong cache, but it'll now trigger unnecessary builds.

Let's say we have build1, build2 and build3 on the same project. build1 depends on build2 and build3 and the following inputs:

```
build1dir/**/*
build2dir/**/*
build3dir/**/*
```

let's say you build everything individually and everything is now cached

if you change things in `build1dir` and then run:

`nx run project:build2` will read build2 from cache
`nx run project:build3` will read build3 from cache
`nx run project:build1` will **build** build2, build3, build1
