### ISSUE TITLE
Error: Cannot find project 'blog' on Core Nx Tutorial - Step 1

### ISSUE THREAD

**Issue by mbriantoc** [nrwl/nx#11053]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?
https://nx.dev/core-tutorial/01-create-blog

### Additional context or description

After following all the steps in the page, the `build` and `serve` commands both fail with `Cannot find project 'blog'` is there any step missing? 

I tried adding ```{ "blog": "packages/blog"}``` to the `projects` property of `workspace.json` but then I got different errors about missing files. So  if that's the way, there's more missing configuration.

**Comment by joncarlson** [comment]
Encountered the same issue. If you delete `workspace.json` it works as expected.

[The docs ](https://nx.dev/configuration/projectjson#workspace-json) state that: `The workspace.json file in the root directory is optional. It's used if you want to list the projects in your workspace explicitly instead of Nx scanning the file tree for all project.json and package.json files.`. 

It seems that either the tutorial should be updated to mention adding 'blog' to workspace.json or generating shouldn't create that file by default.

**Comment by AgentEnder** [comment]
The npm preset shouldn't create a workspace.json file, hence the assumption that project inference would be active. Can you confirm `npx create-nx-workspace@latest --preset npm` is creating a workspace.json file?

**Comment by joncarlson** [comment]
Yes, I just copy/pasted that command and there is a workspace.json in the created project.

**Comment by jshinevar** [comment]
I can also verify I am having the same result.

**Comment by rascode** [comment]
Same issue here.

**Comment by pikooli** [comment]
> The npm preset shouldn't create a workspace.json file, hence the assumption that project inference would be active. Can you confirm `npx create-nx-workspace@latest --preset npm` is creating a workspace.json file?

yeap this command create the workpkace.json.
Should tell in the tutorial to remove it or not create it in the first place.

Thanks

**Comment by johnstew** [comment]
Same issue in trying the tutorial.

**Comment by npalmer-zs** [comment]
Also encountered the same issue.

**Comment by rafacteixeira** [comment]
I had the same issue.
After deleting the workspace.json file, the commands started working

**Comment by medmin** [comment]
https://nx.dev/getting-started/package-based-repo-tutorial#getting-started-with-package-based-repos

 this guide does not work 

I have error "NX : Cannot find project 'is-even'"

**Comment by AgentEnder** [comment]
@medmin see: https://github.com/nrwl/nx/issues/12689
