### ISSUE TITLE
The updateBuildableProjectDepsInPackageJson option uses dist instead of libs

### ISSUE THREAD

**Issue by jasongerbes** [nrwl/nx#11063]
## Current Behavior

The `updateBuildableProjectDepsInPackageJson` option provided by multiple build executors (e.g. `@nrwl/js:tsc`) currently pulls the `version` of internal projects from the `dist` folder (e.g. `dist/libs/lib-1/package.json`).

We've run into an issue where the `dist` output of a project is modified via a custom `publish` script, which can lead to inconsistent `build` output of a depending library.

## Expected Behavior

When populating internal dependencies via the `updateBuildableProjectDepsInPackageJson` option, the `version` of each project should be read from the `libs` folder (e.g. `libs/lib-1/package.json`) to ensure consistent build output.

## Steps to Reproduce

1. Create a workspace with two buildable libs: `lib-1` and `lib-2`.
2. Import `lib-1` within `lib-2` (`lib-2` should depend on `lib-1`).
3. Build `lib-1`
4. Modify the `version` of `lib-1` in `dist/libs/lib-1/package.json`.
5. Build `lib-2`.
6. Check `dist/libs/lib-2/package.json` - the version of `lib-1` has been pulled from `dist/libs/lib-1/package.json`.

### Environment

```
Node : 16.14.2
OS   : darwin x64
yarn : 1.22.18

nx : 14.2.0-rc.1
@nrwl/angular : 14.2.0-rc.1
@nrwl/cypress : 14.2.0-rc.1
@nrwl/detox : Not Found
@nrwl/devkit : 14.2.0-rc.1
@nrwl/eslint-plugin-nx : 14.2.0-rc.1
@nrwl/express : Not Found
@nrwl/jest : 14.2.0-rc.1
@nrwl/js : 14.2.0-rc.1
@nrwl/linter : 14.2.0-rc.1
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/nx-cloud : 14.0.5
@nrwl/nx-plugin : Not Found
@nrwl/react : 14.2.0-rc.1
@nrwl/react-native : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : 14.2.0-rc.1
@nrwl/web : 14.2.0-rc.1
@nrwl/workspace : 14.2.0-rc.1
typescript : 4.7.2
---------------------------------------
Community plugins:
    @ngrx/component-store: 13.2.0
    @ngrx/effects: 13.2.0
    @ngrx/entity: 13.2.0
    @ngrx/router-store: 13.2.0
    @ngrx/store: 13.2.0
    rxjs: 6.5.5
    @ngrx/store-devtools: 13.2.0
```

**Comment by jasongerbes** [comment]
Bump

**Comment by sergeylukin** [comment]
As a user, I find current behavior convenient. I suggest to ask yourself why a script would need to modify dist folder after package is built.
