### ISSUE TITLE
Nx generate @nrwl/angular:component  results in an error

### ISSUE THREAD

**Issue by HaasStefan** [nrwl/nx#11070]
I have an Nx workspace containing a few Angular applications and libraries. I recently removed all node_modules and afterwards ran `npm i --also dev` and ` ng add @nrwl/angular --preserve-angular-cli-layout` and then I tried creating a component using `nx generate @nrwl/angular:component abcde` which results in the following error:

> InvalidInputOptions [Error]: Schematic input does not validate against the Schema: {"style":"scss","project":"luis","name":"abc","displayBlock":false,"inlineStyle":false,"inlineTemplate":false,"standalone":false,"changeDetection":"Default","skipTests":false,"flat":false,"skipImport":false,"skipSelector":false,"type":"component","export":false,"path":"apps/luis/src/app"}
> Errors:
> 
>   Data path "" must NOT have additional properties(standalone).
>     at MapSubscriber.project (C:\Users\stefan.haas\source\luis\node_modules\@nrwl\angular\node_modules\@angular-devkit\schematics\tools\schema-option-transform.js:30:27)
>     at MapSubscriber._next (C:\Users\stefan.haas\source\luis\node_modules\@nrwl\angular\node_modules\rxjs\internal\operators\map.js:49:35)
>     at MapSubscriber.Subscriber.next (C:\Users\stefan.haas\source\luis\node_modules\@nrwl\angular\node_modules\rxjs\internal\Subscriber.js:66:18)
>     at ThrowIfEmptySubscriber._next (C:\Users\stefan.haas\source\luis\node_modules\@nrwl\angular\node_modules\rxjs\internal\operators\throwIfEmpty.js:44:26) 
>     at ThrowIfEmptySubscriber.Subscriber.next (C:\Users\stefan.haas\source\luis\node_modules\@nrwl\angular\node_modules\rxjs\internal\Subscriber.js:66:18)   
>     at TakeSubscriber._next (C:\Users\stefan.haas\source\luis\node_modules\@nrwl\angular\node_modules\rxjs\internal\operators\take.js:54:30)
>     at TakeSubscriber.Subscriber.next (C:\Users\stefan.haas\source\luis\node_modules\@nrwl\angular\node_modules\rxjs\internal\Subscriber.js:66:18)
>     at MergeMapSubscriber.notifyNext (C:\Users\stefan.haas\source\luis\node_modules\@nrwl\angular\node_modules\rxjs\internal\operators\mergeMap.js:93:26)    
>     at SimpleInnerSubscriber._next (C:\Users\stefan.haas\source\luis\node_modules\@nrwl\angular\node_modules\rxjs\internal\innerSubscribe.js:27:21)
>     at SimpleInnerSubscriber.Subscriber.next (C:\Users\stefan.haas\source\luis\node_modules\@nrwl\angular\node_modules\rxjs\internal\Subscriber.js:66:18) {  
>   errors: [
>     {
>       instancePath: '',
>       schemaPath: '#/additionalProperties',
>       keyword: 'additionalProperties',
>       params: [Object],
>       message: 'must NOT have additional properties'
>     }
>   ]
> }
> Schematic input does not validate against the Schema: {"style":"scss","project":"luis","name":"abc","displayBlock":false,"inlineStyle":false,"inlineTemplate":false,"standalone":false,"changeDetection":"Default","skipTests":false,"flat":false,"skipImport":false,"skipSelector":false,"type":"component","export":false,"path":"apps/luis/src/app"}
> Errors:
> 
>   Data path "" must NOT have additional properties(standalone).

package.json:
```
{
  "name": "luis",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "nx",
    "postinstall": "node ./decorate-angular-cli.js && ngcc --properties es2015 browser module main",
    "start": "nx serve",
    "start:assisteur-portal": "nx serve assisteur-portal",
    "start:all": "nx run-many --target=serve --all",
    "analyze": "webpack-bundle-analyzer dist/apps/luis/stats.json",
    "build:stats": "ng build --stats-json",
    "build": "nx build",
    "test": "nx test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.3.0",
    "@angular/cdk": "^13.3.7",
    "@angular/common": "~13.3.0",
    "@angular/compiler": "~13.3.0",
    "@angular/core": "~13.3.0",
    "@angular/forms": "~13.3.0",
    "@angular/material": "^13.3.7",
    "@angular/platform-browser": "~13.3.0",
    "@angular/platform-browser-dynamic": "~13.3.0",
    "@angular/router": "~13.3.0",
    "@ngx-translate/core": "^14.0.0",
    "@ngx-translate/http-loader": "^7.0.0",
    "@nrwl/angular": "^14.4.2",
    "@types/jquery": "^3.5.14",
    "flag-icon-css": "^4.1.7",
    "guid-typescript": "^1.0.9",
    "keycloak-angular": "^10.0.1",
    "keycloak-js": "^18.0.1",
    "ngx-filesize": "^2.0.16",
    "primeflex": "^3.2.0",
    "primeicons": "^5.0.0",
    "primeng": "^13.4.0",
    "rxjs": "~7.4.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.3.0",
    "@angular-eslint/eslint-plugin": "~13.1.0",
    "@angular-eslint/eslint-plugin-template": "~13.1.0",
    "@angular-eslint/template-parser": "~13.1.0",
    "@angular/cli": "~13.3.0",
    "@angular/compiler-cli": "~13.3.0",
    "@angular/language-service": "~13.3.0",
    "@nrwl/cli": "14.1.5",
    "@nrwl/cypress": "14.1.5",
    "@nrwl/eslint-plugin-nx": "14.1.5",
    "@nrwl/jest": "14.1.5",
    "@nrwl/linter": "14.1.5",
    "@nrwl/workspace": "^14.1.5",
    "@types/jest": "27.4.1",
    "@types/node": "16.11.7",
    "@typescript-eslint/eslint-plugin": "~5.18.0",
    "@typescript-eslint/parser": "~5.18.0",
    "cypress": "^9.1.0",
    "eslint": "~8.12.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "jest": "27.5.1",
    "jest-preset-angular": "11.1.1",
    "ngx-build-plus": "^13.0.1",
    "nx": "14.1.5",
    "prettier": "^2.5.1",
    "ts-jest": "27.1.4",
    "ts-node": "9.1.1",
    "typescript": "~4.6.2",
    "webpack-bundle-analyzer": "^4.5.0"
  }
}
```

nx.json:
```
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "npmScope": "luis",
  "affected": {
    "defaultBase": "master"
  },
  "cli": {
    "packageManager": "npm"
  },
  "implicitDependencies": {
    "package.json": {
      "dependencies": "*",
      "devDependencies": "*"
    },
    ".eslintrc.json": "*"
  },
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build", "lint", "test", "e2e"]
      }
    }
  },
  "generators": {
    "@nrwl/angular:application": {
      "style": "scss",
      "linter": "eslint",
      "unitTestRunner": "jest",
      "e2eTestRunner": "cypress"
    },
    "@nrwl/angular:library": {
      "linter": "eslint",
      "unitTestRunner": "jest"
    },
    "@nrwl/angular:component": {
      "style": "scss"
    }
  },
  "defaultProject": "luis",
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build"]
    }
  }
}
```

**Comment by AgentEnder** [comment]
Hey @HaasStefan , it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

**Comment by HaasStefan** [comment]
Indeed, it was related with version mismatches. I manually decreased @nrwl/angular version to ~13.3.0 to match the version of my angular cli

**Comment by phihochzwei** [comment]
In case others stumple over this problem: Also check the version of your **"@schematics/angular"**
