### ISSUE TITLE
Incorrect schema support for `coverageReporters`

### ISSUE THREAD

**Issue by marlomgirardi** [nrwl/nx#11090]
## Current Behavior
NX reports a schema type error and does not run the jest tests.

## Expected Behavior

Jest tests should run as expected with coverage report options.

## Steps to Reproduce

https://github.com/nrwl/nx-examples/pull/213

Assuming all dependencies are already installed, run `yarn nx test cart` and the error should appear.

### Failure Logs

```
 >  NX   Property 'coverageReporters' does not match the schema.

   {
     "type": "string"
   }'
```

### Environment

runner on `nx-examples` repo:
```
 >  NX   Report complete - copy this into the issue template

   Node : 18.5.0
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 14.2.0-rc.1
   @nrwl/angular : 14.2.0-rc.1
   @nrwl/cypress : 14.2.0-rc.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.2.0-rc.1
   @nrwl/eslint-plugin-nx : 14.2.0-rc.1
   @nrwl/express : Not Found
   @nrwl/jest : 14.2.0-rc.1
   @nrwl/js : 14.2.0-rc.1
   @nrwl/linter : 14.2.0-rc.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.0.5
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.2.0-rc.1
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.2.0-rc.1
   @nrwl/web : 14.2.0-rc.1
   @nrwl/workspace : 14.2.0-rc.1
   typescript : 4.7.2
   ---------------------------------------
   Community plugins:
         @ngrx/component-store: 13.2.0
         @ngrx/effects: 13.2.0
         @ngrx/entity: 13.2.0
         @ngrx/router-store: 13.2.0
         @ngrx/store: 13.2.0
         rxjs: 6.5.5
         @ngrx/store-devtools: 13.2.0

✨  Done in 0.90s.
```

**Comment by AgentEnder** [comment]
https://nx.dev/packages/jest/executors/jest#coveragereporters

It looks like the option for coverage reporters only accepts an array of strings, is this something that worked in the past?

**Comment by marlomgirardi** [comment]
Hey, yeah that works, It is how I'm using it, but thought it was a bit weird this divergence of behavior for the same attribute.

**Comment by barbados-clemens** [comment]
yeah, it's a little confusing since you're adding config options via the project config vs the CLI, even though the jest executor follows the jest CLI args (since that's what we call under the hood) so we don't have a way to pass it to jest even if we supported it. 

I'm working on adding a "Troubleshooting" guide for jest on the nx docs with common gotchas, questions, and tips we commonly come across. I'll add this to the list of things to add to that guide so thank you for bringing it up. 😃
