### ISSUE TITLE
Ambiguous documentation of app --routing schematics

### ISSUE THREAD

**Issue by bridzius** [nrwl/nx#1109]
## Expected Behavior

As per https://github.com/nrwl/nx/blob/master/docs/api-schematics/application.md - `--routing` option on `ng g app <name> --routing` should generate a routing module.

## Current Behavior

Based on https://github.com/nrwl/nx/blob/master/packages/schematics/src/collection/application/index.ts#L343 - --routing ignores the default angular schematic definition completely and just inlines the paths in the module file.

## Question

Is the documentation incorrect (generates a routing config in the existing module instead of a new routing module) and Nx proposes to keep the routing configuration along with the app module declaration? Or is the documentation correct and this is behaviour that should change in ther future?

Are there any performance/logic merits for keeping the route config in the module file?

**Comment by SebasG22** [comment]
I tried to use only the routing configuration without the NgModule when generating a lib to check if create a new routing module but it doesn't work.

![Nx-Routing-Configuration](https://user-images.githubusercontent.com/17608169/55670930-b3941d80-584f-11e9-8958-c9a3598ff74b.gif)
 
The previous command generate this under the libs folder:
![image](https://user-images.githubusercontent.com/17608169/55670951-e76f4300-584f-11e9-902a-97d1339c398b.png)

As you can see, If you say "No" to the NgModule will not generate the routing Module.

I wondering if this is intended behavior

**Comment by brandonroberts** [comment]
@bridzius a routing module is more for convention, so inlining the routing configuration is valid also. There wouldn't be any significant performance merits, other than its one less NgModule to compile. If anything is still an issue, please verify with the latest version of Nx and open a new issue.
