### ISSUE TITLE
Duplicate cloned workspaces ...cannot reset workspace instance using "nx g @nrwl/nx-cloud:init "

### ISSUE THREAD

**Issue by nhhockeyplayer** [nrwl/nx#11093]
SUBJECT: cannot reset workspace instance using `nx g @nrwl/nx-cloud:init `

## Current Behavior
I had a @nrwl/nx account with zero workspaces. Went thru the processes of creating workspace but somehow duplicate workspaces are being instantiated at NxCloud.

Currently I have a local workspace which build fails to connect to NxCloud
But my github actions successfully connects and reports runs fine.

But there are two workspaces with same name at NxCloud.

`@nrwl/nx-cloud` is installed in my monorepo

I use this schematic
`nx g @nrwl/nx-cloud:init`

it initializes and yields a URL to paste in browser to add my workspace to my user account at @nrwl

```
>  NX   Nx Cloud has been enabled

   Your workspace is currently unclaimed. Run details from unclaimed workspaces can be viewed on nx.app by anyone
   with the link. Claim your workspace at the following link to restrict access.
   
   https://nx.app/orgs/workspace-setup?accessToken=ZWM4MzY3NmMtMTZhMy00NmNkLWI1NzYtN2I5YjUzNjc5ZjhhfHJlYWQtd3JpdGU=
```

so I take the url generated and plug it into browser

I click CONNECT WORKSPACE and my workspace is connected successfully
I copy to clipboard th enext step in commands at NxCloud and execute it on my machine
`NX_BRANCH=testing npx nx run admin:build`

BUT... subsequent build attempts fail to connect with this token that was supposedly generated. Thhs happens everytime.

```
 >  NX   Successfully ran target build for project admin and 12 task(s) it depends on (153ms)
 
   Nx read the output from the cache instead of running the command for 13 out of 13 tasks.
 

 >  NX   Nx Cloud Problems

   - Invalid Nx Cloud workspace.
```

no other error or log anywhere

NOTE: my PR's on github actions appear to run fine and get picked up by NxCloud I can see the runs at NxCloud clicking the link on my PR page at github
But something has gone ary locally in my monorepo preventing lightning speed runs to be pushed to the NxCloud for local builds

## Expected Behavior
My local nx builds should be able to find NxCloud and they cant, I continue to receive this error after trying to recover from this half dozen attempts and I think its referring to a cloned duplicate that somehow got cloned at NxCloud... or spread I wold guess.

## Steps to Reproduce
I listed them
I launch a local build on my machine and listed that failure below
I create a PR and that integrates fine NxCloud sees those runs

But I end up with two workspaces at NxCloud with the same name `@nhhockeyplayer/meanstacknh`
when I assume there is only suppose to be one with that name?

thanks for any asisst

I have a repo please ask to collaborate
https://github.com/nhhockeyplayer/meanstacknh

### Failure Logs
```
```
 >  NX   Nx Cloud Problems

   - Invalid Nx Cloud workspace.
   

### Environment
```
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : darwin x64
   yarn : 1.22.18
   
   nx : 14.4.2
   @nrwl/angular : 14.4.2
   @nrwl/cypress : 14.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.2
   @nrwl/eslint-plugin-nx : 14.4.2
   @nrwl/express : 14.4.2
   @nrwl/jest : 14.4.2
   @nrwl/js : 14.4.2
   @nrwl/linter : 14.4.2
   @nrwl/nest : 14.4.2
   @nrwl/next : Not Found
   @nrwl/node : 14.4.2
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : 8.12.11
   @nrwl/storybook : 14.4.2
   @nrwl/web : 14.4.2
   @nrwl/workspace : 14.4.2
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
   	 @fortawesome/angular-fontawesome: 0.11.1
   	 @ionic/angular: 6.1.13
   	 @ngrx/component: 14.0.1
   	 @ngrx/component-store: 14.0.1
   	 @ngrx/effects: 14.0.1
   	 @ngrx/entity: 14.0.1
   	 @ngrx/router-store: 14.0.1
   	 @ngrx/store: 14.0.1
   	 @nxtend/capacitor: 13.0.0
   	 @nxtend/ionic-angular: 13.1.0
   	 @storybook/angular: 6.5.9
   	 angular-builder-custom-terser-options: 1.0.1
   	 @compodoc/compodoc: 1.1.19
   	 @ngrx/schematics: 14.0.1
   	 @ngrx/store-devtools: 14.0.1
   	 @nxtend/capacitor: 13.0.0
   	 @storybook/angular: 6.5.9
```

**Comment by nhhockeyplayer** [comment]
but error continues

one of my issues is I am unable to do an npm login from terminal to my github account and Im unsure which token to use for that... going to try the NxCloud token and see

**Comment by StalkAltan** [comment]
Hi @nhhockeyplayer

It looks like two separate workspaces were created 3 minutes apart from one another. The link you posted is for the second workspace.

I am interested in the contents of your nx.json. Can you confirm that a property that looks similar to this exists, and that the `accessToken` value matches the one from your link above?

```
  "tasksRunnerOptions": {
    "default": {
      "runner": "@nrwl/nx-cloud",
      "options": {
        "accessToken": "SOME ACCESS TOKEN",
        "cacheableOperations": [
          "build",
          "test",
          "lint"
        ],
        "parallel": 3
      }
    }
  },
```

**Comment by nhhockeyplayer** [comment]
```
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "npmScope": "meanstacknh",
  "affected": {
    "defaultBase": "main"
  },
  "cli": {
    "packageManager": "yarn",
    "defaultCollection": "@nrwl/angular"
  },
  "implicitDependencies": {
    "tsconfig.base.json": "*",
    "nx.json": "*",
    "workspace.json": "*",
    "package.json": {
      "dependencies": "*",
      "devDependencies": "*"
    },
    ".eslintrc.json": "*"
  },
  "tasksRunnerOptions": {
    "default": {
      "runner": "@nrwl/nx-cloud",
      "options": {
        "canTrackAnalytics": false,
        "showUsageWarnings": true,
        "scan": true,
        "cacheableOperations": [
          "build",
          "lint",
          "test",
          "e2e"
        ],
        "parallel": 1,
        "accessToken": "ZWM4MzY3NmMtMTZhMy00NmNkLWI1NzYtN2I5YjUzNjc5ZjhhfHJlYWQtd3JpdGU="
      }
    }
  },
  "targetDependencies": {
    "build": [
      {
        "target": "build",
        "projects": "dependencies"
      }
    ]
  },
  "generators": {
    "@nrwl/angular:library": {
      "linter": "eslint",
      "unitTestRunner": "jest",
      "simpleModuleName": true,
      "standaloneConfig": true
    },
    "@nrwl/angular:scam": {
      "style": "scss",
      "changeDetection": "OnPush",
      "flat": true,
      "inlineStyle": true,
      "inlineTemplate": true,
      "skipTests": true,
      "inlineScam": false
    },
    "@nrwl/angular:application": {
      "style": "scss",
      "linter": "eslint",
      "unitTestRunner": "jest",
      "e2eTestRunner": "cypress"
    },
    "@nrwl/angular:component": {
      "style": "scss"
    }
  },
  "defaultProject": "admin"
}

```

**Comment by nhhockeyplayer** [comment]
strange I do npm login and authenticate fine to github actions and registry

but cannot do yarn install thereafter

I was able to do an `npm publish` and published my library fine

something is up with using `npm login` and github using scope maybe

the registry is being detached I will look into this but still havent pin pointed the nxcloud workspace issue


```
meanstack02@admin meanstacknh % npm login
npm notice Log in on https://npm.pkg.github.com/
Username: nhhockeyplayer
Password: 
Email: (this IS public) meanstack@hotmail.com
Logged in as nhhockeyplayer on https://npm.pkg.github.com/.
meanstack02@admin meanstacknh % yarn install
yarn install v1.22.18
warning package.json: "dependencies" has dependency "@nxtend/capacitor" with range "~13.0.0" that collides with a dependency in "devDependencies" of the same name with version "^13.0.0"
warning package.json: "dependencies" has dependency "@storybook/angular" with range "^6.5.9" that collides with a dependency in "devDependencies" of the same name with version "6.5.9"
warning package.json: "dependencies" has dependency "@storybook/core-server" with range "^6.5.9" that collides with a dependency in "devDependencies" of the same name with version "6.5.9"
warning package.json: "dependencies" has dependency "@types/passport-local" with range "^1.0.34" that collides with a dependency in "devDependencies" of the same name with version "^1.0.33"
info No lockfile found.
warning @nhhockeyplayer/meanstacknh@0.0.0: "dependencies" has dependency "@nxtend/capacitor" with range "~13.0.0" that collides with a dependency in "devDependencies" of the same name with version "^13.0.0"
warning @nhhockeyplayer/meanstacknh@0.0.0: "dependencies" has dependency "@storybook/angular" with range "^6.5.9" that collides with a dependency in "devDependencies" of the same name with version "6.5.9"
warning @nhhockeyplayer/meanstacknh@0.0.0: "dependencies" has dependency "@storybook/core-server" with range "^6.5.9" that collides with a dependency in "devDependencies" of the same name with version "6.5.9"
warning @nhhockeyplayer/meanstacknh@0.0.0: "dependencies" has dependency "@types/passport-local" with range "^1.0.34" that collides with a dependency in "devDependencies" of the same name with version "^1.0.33"
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://npm.pkg.github.com/@angular%2fanimations: npm package \"animations\" does not exist under owner \"angular\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/meanstack02/meanstacknh/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by nhhockeyplayer** [comment]
I cited some auth issues with npmjs.org and just got my libraries publishing just today meaning I has just resolved all my github actions auth stuff too

This could be an auth issue regarding the availability of registries...specifically the ones NxCloud is dependent on?

just a thought

**Comment by nhhockeyplayer** [comment]
anyway I added you as collaborator
feel free to check it out

**Comment by nhhockeyplayer** [comment]
be nice of someone could fix this one its really shutting by CI pipeline down

https://github.com/nrwl/nx/issues/11088

**Comment by StalkAltan** [comment]
@nhhockeyplayer 

I cloned your repo and can use Nx Cloud after installing with `yarn`. 
Run link: `https://nx.app/runs/EhPS9BauD5F`

Something is wrong with the way the access token is being set on your machine. Please check your terminal session, as well as any `.env` files to make sure you do not have something setting the value for the `NX_CLOUD_AUTH_TOKEN` or `NX_CLOUD_ACCESS_TOKEN` environment variables.

**Comment by nhhockeyplayer** [comment]
Thank you Altan

Yes I set those env var in shell... docs are unclear when or where to set those

I will remove them and try this now

Appreciate the assist ! Thank you!

**Comment by nhhockeyplayer** [comment]
So Im in clear now for this ticket...

any thoughts on this guy? 
https://github.com/nrwl/nx/issues/11088

it seems someone in the yml team for NxCloud has coded VOLTA in their boiler plate actions
and its biting now
seems they forgot to install VOLTA for their case logic in the event its encountered?
I dont know to what extent NxCloud is using VOLTA

**Comment by nhhockeyplayer** [comment]
Thanks for all your responsiveness patience and turnaround.
Very much appreciated.

Im running with the ball into the field and clients are very anxiously waiting for these new designs and constructs to hit their cloud Im poised to bring them the very best from the NxCloud team.
