### ISSUE TITLE
RFC: Allow user defined nx-module-boundaries additional lint error text on violation report

### ISSUE THREAD

**Issue by cdaringe** [nrwl/nx#11107]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I would like to allow for user values to be suffixed to the ESLint error reporting messages rendered by `enforce-module-boundaries` plugin.

I am implementing **multi-dimension** tag constraints, using dimensions such as `app:*` and `market:*` style tags, to prevent x-app and x-market import violations using `enforce-module-boundaries`. Multi-dim constraints are awesome, and super helpful when communicating violations. However, the ESLint provided message--though very helpful--is quite minimal, and has left a few users confused.

## Motivation

Currently, on violation, users get [the following text](https://github.com/nrwl/nx/blob/438ea6cdfed60dc0f7f358e967650f004f2e7c42/packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts#L121)

> A project tagged with "app:foo" can only depend on libs tagged with `[app:foo]`

For my users, it would be awesome to suffix this richer information

> A project tagged with "app:foo" can only depend on libs tagged with `[app:foo]`
>
> Does lib "bar" need to add an `app:` tag in /path/to/bar/project.json?
> You can read about app: tags at [our tag docs](https://whatever)

## Suggested Implementation

The existing plugin is well structured and could support this functionality quite easily.

You can see that the ESLint plugin uses template strings, and passes in values [here](https://github.com/nrwl/nx/blob/438ea6cdfed60dc0f7f358e967650f004f2e7c42/packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts#L505-L511)

A flexible solution would be to allow an extension [to the schema](https://github.com/nrwl/nx/blob/438ea6cdfed60dc0f7f358e967650f004f2e7c42/packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts#L95-L100) to allow for users to pass in a formatter.

For example:

```json5
// eslintrc.json
"@nrwl/nx/enforce-module-boundaries": [
  "error",
   {
        "formatDepConstraintsMessageModule": "{{workspaceRoot}}/scripts/eslint/nx/format-msg.js" 

// or
// inside of depConstraints[]
"sourceTag": "foo",
"onlyDependOnLibsWithTags": ["foo"],
"formatMessageModule": "{{workspaceRoot}}/scripts/eslint/nx/format-msg.js" 
```

On lint module load, a dynamic require would load the formatter module, and pass in the preformatted message, as well as other metadata about the report/violation. `f(msg-string, metadata) => msg-string`

## Alternate Implementations

More implementations could be easily thought up. Another such implementation would be to offer a first class, [optional](url) formatting DSL.

```json5
// eslintrc.json
"@nrwl/nx/enforce-module-boundaries": [
  "error",
  {
    "formattersByTag": {
      "market:*": "Does '{{importedProjectName}}' need to add a `market:` tag in {{consumedProject.dirname}}/project.json?",
      "app:*": "Does '{{importedProjectName}}' need to add a `app:` tag in {{consumedProject.dirname}}/project.json?"
    },
    "depConstraints": [
      {
        "sourceTag": "market:us",
        "onlyDependOnLibsWithTags": ["market:us", "market:generic"]
      },
```

The formatter could then find a matching `formatter` from `formattersByTag` when a violation is found by the `sourceTag`, and suffix the user contextualizing information.

Surely other fancy ideas could be had. The amount of code to achieve this goal i perceive could be quite low, but it would warrant a docs update as well. Further, it is somewhat of a niche feature, for those of us in massive projects. If it's not too offensive to do the dynamic require, it is the simplest in implementation, and gives max dexterity to users. 

Something like the `"formatDepConstraintsMessageModule": "{{workspaceRoot}}/scripts/eslint/nx/format-msg.js"` could maximize support for all use cases, and cost minimal LOC and maintenance by nrwl/nx for the plugin

**Comment by meeroslav** [comment]
Hey @cdaringe,

Feel free to create a PR with this feature. Let me know if you need any help.

**Comment by meeroslav** [comment]
Closing this as a stale feature request
