### ISSUE TITLE
Bad indentation on line 20, column 11

### ISSUE THREAD

**Issue by ruskovweb** [nrwl/nx#11119]
### Documentation issue

- [x] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[Enter the URL or documentation section here.](https://nx.dev/ci/monorepo-ci-bitbucket-pipelines)

### Additional context or description

The `name` property should be indented one more tab.

**Comment by rubiagatra** [comment]
Fix in #11225 @AgentEnder
