### ISSUE TITLE
Cannot find module 'jasmine-marbles' from 'nrwl-nx-testing.umd.js'

### ISSUE THREAD

**Issue by TahiraM** [nrwl/nx#1112]
## Issue 

Jest tests for created Library failing with the error `Cannot find module 'jasmine-marbles' from 'nrwl-nx-testing.umd.js'`, when looking in the dev dependencies there is no mention of Jasmine 

`"devDependencies": { 
     "@angular/cli": "7.3.1",
     "@angular/compiler-cli": "^7.0.0",
     "@angular/language-service": "^7.0.0",
     "@angular-devkit/build-angular": "0.13.1",
     "@ngrx/store-devtools": "7.2.0",
     "ngrx-store-freeze": "0.2.4",
     "@nrwl/schematics": "7.6.2",
     "@types/node": "~8.9.4",
     "codelyzer": "~4.5.0",
     "dotenv": "6.2.0",
     "ts-node": "~7.0.0",
     "tslint": "~5.11.0",
     "typescript": "3.2.2",
     "prettier": "1.15.2",
     "cypress": "3.1.0",
     "@types/jquery": "3.3.6",
     "@nrwl/builders": "7.6.2",
     "jest": "23.0.0",
     "@types/jest": "23.0.0",
     "jest-preset-angular": "6.0.1"
  }`

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create a new project `npx -p @nrwl/schematics create-nx-workspace projectName`
2. start project `ng g application ` 
3. set dependencies for jest and cypress 
4. create a library `ng g library` 
5. run tests 

### Context

Please provide any relevant information about your setup:
`"@ngrx/store-devtools": "7.2.0",
    "ngrx-store-freeze": "0.2.4",
    "@nrwl/schematics": "7.6.2",
"@angular-devkit/build-angular": "0.13.1",
    "@angular/cli": "7.3.1",
    "@angular/compiler-cli": "^7.0.0",`

I had to install Jasmine-marbles manually for this error to go.

**Comment by pasinsjr** [comment]
Same here. I had to install Jasmine-marbles manually too

**Comment by brandonroberts** [comment]
`jasmine-marbles` is a dependency in Nx 8.x
