### ISSUE TITLE
npx nx affected --target build:staging not working

### ISSUE THREAD

**Issue by HaasStefan** [nrwl/nx#11135]
I would like to build the affected apps in my Nx workspace with different stages (staging, production) so I created a npm script for the staging build called `build:staging`:
```
  "scripts": {
    "ng": "nx",
    "postinstall": "node ./decorate-angular-cli.js && ngcc --properties es2015 browser module main",
    "start": "nx serve",
    "start:assisteur-portal": "nx serve assisteur-portal",
    "start:all": "nx run-many --target=serve --all",
    "analyze": "webpack-bundle-analyzer dist/apps/luis/stats.json",
    "build:stats": "ng build --stats-json",
    "build": "nx build",
    "build:staging": "nx build --configuration=staging",
    "test": "nx test"
  },
```

Badly when I run `npx run affected --target build:staging` nothing is actually build, although I have made changes. 
![image](https://user-images.githubusercontent.com/29503005/178955681-92eaa921-f3bf-4040-9c08-e43e2f3f77fb.png)

when I run `npx run affected --target build` it works and builds the affected apps, but not with the right stage.

**Comment by AgentEnder** [comment]
Scripts from the root package.json do not translate to targets on individual projects. You'd want to run something like `nx affected --target build --configuration staging`
