### ISSUE TITLE
How are dependencies gathered?

### ISSUE THREAD

**Issue by Itrulia** [nrwl/nx#1115]
I am using ng-packagr quite heavily and thus have tons of packages in the angular CLI.

`@itrulia/error-reporting` for example is using `@itrulia/common` which will not be shown via `nx dep-graph`. It will only be shown when I add `"implicitDependencies": ["@itrulia/common"]` in nx.json.

When checking out nx-examples it catches it automatically. So how are the dependencies resolved?

**Comment by Itrulia** [comment]
if this is indeed abnormal, I can provide a repository to reproduce.

**Comment by FrozenPandaz** [comment]
Dependencies are gathered by looking at Typescript `import` statements. If the import matches the pattern, `@npmScope/libraryName`, the project containing that Typescript import will depend on `libraryName` project.

**Comment by Itrulia** [comment]
I guess this explains, the library name inside angular.json is `@itrulia/error-reporting`, the npmscope is set to itrulia. So it tries to do `@itrulia/@itrulia/error-reporting` I guess?

Thanks!
