### ISSUE TITLE
Outputs relative to project directory

### ISSUE THREAD

**Issue by SoftMemes** [nrwl/nx#11156]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I'm not sure if this is a feature request or bug report, but cannot find documentation that covers it. I'm using NX core with config in package.json and am trying to adopt NX on top of an existing monorepo setup.

My repo consists of a number of projects (workspaces, in yarn terminology), each of which produces their own "lib". With yarn 3 workspaces, the dependencies across modules just work, and I can import from A/lib using the files produced by A.

It appears however that NX expects the output to be relative to the root of the monorepo, rather than the project. It took me many attempts to configure outputs before I realised this.

I have a workaround now by having _each_ module explicitly describe their output directories, so "A" located in "libraries/A" specify outputs: "libraries/A/lib" in the nx section of packager.json, but this leads to a lot of duplication. What I'd really want is a project local output path in the root nx.json, but simply using outputs: [{projectRoot}/lib], does not appear to work.

## Motivation
Many existing monorepo builds work in this way, where each project produces artifacts in its own directory, used by other parts of the monorepo. Having a shorthand to support this would make things significantly less verbose and brittle to configure.

## Suggested Implementation

Support using `{projectRoot}` in outputs specified in nx.json. 

## Alternate Implementations
N/A

**Comment by FrozenPandaz** [comment]
We added this capability recently in `14.4.3`. And we also fixed an issue recently here: https://github.com/nrwl/nx/pull/11157.

Please retry with the latest version and let us know if there are any problems.

Also, here's a working example: https://github.com/FrozenPandaz/nx-bugs/tree/project-root-output
