### ISSUE TITLE
long CLI flags are truncated on --help

### ISSUE THREAD

**Issue by cdaringe** [nrwl/nx#11152]
## Current Behavior
`--help` emits truncated text. You can see that long flags get chopped, and I cannot discern what the flag is because the help test squashes it

![image](https://user-images.githubusercontent.com/1003261/179100882-8a6ef799-d468-4f14-86f2-60e58a1f46da.png)

## Expected Behavior
`--help` to emit non-truncated text. maybe add help text _below_ the options, vs inlined in the same row

## Steps to Reproduce

- create an executor/builder
- add a long property name
- run `nx executorname project-name --help`

nx-examples currently has no executors baked in. perhaps it's candidate for inclusion over there? repros could be added mo-fasta!

### Failure Logs

n/a

### Environment

```

> walmart-web@0.0.1 nx /Users/c0d01a5/src/walmart-3
> NODE_OPTIONS="--max-old-space-size=8192" nx "report"


 >  NX   Report complete - copy this into the issue template

   Node : 16.10.0
   OS   : darwin arm64
   pnpm : 6.33.0
   
   nx : 13.8.0
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.0
   @nrwl/cypress : 12.8.0
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.0
   @nrwl/eslint-plugin-nx : 13.8.0
   @nrwl/express : undefined
   @nrwl/jest : 13.8.0
   @nrwl/js : 13.8.0
   @nrwl/linter : 13.8.0
   @nrwl/nest : undefined
   @nrwl/next : 12.8.0
   @nrwl/node : 13.8.0
   @nrwl/nx-cloud : 13.1.4
   @nrwl/react : 13.8.0
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.0
   @nrwl/tao : 13.8.0
   @nrwl/web : 13.8.0
   @nrwl/workspace : 13.8.0
   typescript : 4.3.2
   rxjs : 6.6.3
   ---------------------------------------
   Community plugins:
   	 @angular-devkit/architect: 0.1100.7
   	 @nrwl/gatsby: 12.8.0
   	 @testcafe-community/nx-builder: 1.1.0


```

**Comment by FrozenPandaz** [comment]
Hi, this issue has been fixed here: https://github.com/nrwl/nx/commit/85721e42f03a1aac63344b9dc47d00693c4fa94e which is available on Nx `13.10.0` and above. You should see the full property name after updating. :smile:
