### ISSUE TITLE
Angular migration doesn't support non-root tsconfig files

### ISSUE THREAD

**Issue by jesse-humi** [nrwl/nx#11165]
## Current Behavior
When running `ng add @nrwl/angular` interestingly I was seeing the following warning in the console
```
The tsConfig file "src/tsconfig.json" specified in the "build" target could not be found. Skipping updating the tsConfig file.
```
However, the files very much do exist. Moving the files out of the `src` folder and into the root of the project and then updating the paths in `angular.json` does resolve this issue, but it seems quite restrictive that I can't have tsconfig files in subdirectories in my project.

### Cause
From debugging the code I can see that it initially finds the `src/tsconfig.json` when calling `moveProjectFiles()` however inside of [moveProjectRootFile](https://github.com/nrwl/nx/blob/master/packages/angular/src/generators/ng-add/utilities/project.migrator.ts#L285) it is not keeping the subfolder so it is moving it directly into `/apps/[project-name]/tsconfig.json` instead of `/apps/[project-name]/src/tsconfig.json`. This is why the warning is generated in [updateBuildTargetConfiguration](https://github.com/nrwl/nx/blob/master/packages/angular/src/generators/ng-add/utilities/app.migrator.ts#L348) later on, because it is looking for the file in `/apps/[project-name]/src/tsconfig.json`.

The warning can be ignored, but the file paths inside of the migrated `tsconfig` file continue to be incorrect since it references files inside of the `src` folder not realizing it's been moved an a directory level up

## Expected Behavior
The migration should be able to move tsconfig files that are in subdirectories and maintain the same subdirectory structure within the new project folder so that manual intervention isn't required and confusing warnings are not shown.

ie.
```
[root_folder]/example_folder/tsconfig.json
// Should migrate to
[root_folder]/apps/[project_folder]/example_folder/tsconfig.json
```
Or if this is not possible, then the migration should at least be smart enough to look for the file in the new location without the subdirectory, and should be able to update the `files` array with new relative paths to account for the change in directory heirarchy

## Steps to Reproduce
1. Create an Angular project
2. Move the `tsconfig.json` into any subfolder
3. Update the `tsconfig` property in the `build` configuration in `angular.json` to point to the `tsconfig.json` within the subfolder
4. Run `ng add **@nrwl/angular`

### Environment
```
 Node : 16.15.0
   OS   : darwin arm64
   npm  : 8.12.2
   
   nx : 14.4.2
   @nrwl/angular : 14.4.2
   @nrwl/cypress : 14.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/eslint-plugin-nx : 14.4.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.2
   @nrwl/js : 14.4.2
   @nrwl/linter : 14.4.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.2
   @nrwl/web : 14.4.2
   @nrwl/workspace : 14.4.2
   typescript : 4.6.4
   ---------------------------------------
   Community plugins:
         angular-calendar: 0.29.0
         @compodoc/compodoc: 1.1.19
         @cypress/schematic: 2.0.0
         @storybook/angular: 6.5.9
         rxjs: 6.6.7
```

**Comment by leosvelperez** [comment]
We are not planning to add support for this for the time being. The recommend way to migrate to an Nx workspace is to use `nx init` and that doesn't have this issue.
