### ISSUE TITLE
Nextjs migration script to NX

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [nrwl/nx#11164]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

If there was a migration script similar to `npx cra-to-nx` for Next.js this would be really useful. I am currently trying to migrate a next.js project to nx

**Comment by zhaoguangyue** [comment]
need

**Comment by jdiponziano** [comment]
definitely need this
