### ISSUE TITLE
Unclear how to use the "sourceMap" or "declarationMap" option in TSConfig in the context of an NX monorepo

### ISSUE THREAD

**Issue by Zamiell** [nrwl/nx#11179]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

It seems like a pretty common use-case for NX is to publish a package to NPM from inside of an NX monorepo. However, it is unclear how to do so while simultaneously having the "sourceMap" or "declarationMap" option in the "tsconfig.json" file turned on.

Please either document how to do this, or document that it is impossible as a limitation of the product.

<br>

### A More Detailed Explanation

When publishing libraries to NPM, it's a nice quality-of-life improvement to use the "sourceMap" compiler option in the "tsconfig.json" file for the project. Doing this allows end-users who are consuming the library to be able to press F12 in VSCode (i.e. "jump to definition"), and instead of warping to the definitions stub (like normal), they are instead warped directly to the real source code.

Under the hood, this works by publishing all of the source files to NPM alongside the compiled JavaScript files. And then VSCode uses the `.map` file to work its way backwards from the `.js` file to the appropriate `.ts` file.

As an example, running `npx tsc` in my library directory of:

```
/Users/Zamiell/foo
```

Would create the following files:

```
/Users/Zamiell/foo/dist/index.d.ts.map
/Users/Zamiell/foo/dist/index.js
```

The contents of `index.d.ts.map` are:

```
{"version":3,"file":"index.d.ts","sourceRoot":"","sources":["../src/index.ts"]}
```

And then, I publish both my "src" and "dist" directories to NPM, and everything works great. (i.e. by using the "files" key in the "package.json" file to specify what gets uploaded)

<br>

### Introducing NX

However, when we try to do this in an NX monorepo, things break down. When we turn on the "sourceMap" compiler option, the maps point upwards into directories that don't exist. For example, say that I run `npx tsc` in the following folder:

```
/Users/Zamiell/nx-monorepo/packages/foo
```

It creates the following files, but this time they go to the monorepo root:

```
/Users/Zamiell/nx-monorepo/dist/packages/foo/index.d.ts.map
/Users/Zamiell/nx-monorepo/dist/packages/foo/index.js
```

And in this case, the contents of `index.d.ts.map` are:

```
{"version":3,"file":"index.d.ts","sourceRoot":"","sources":["../../../packages/foo/src/index.ts"]}
```

Here, the root directory of the uploaded files to npm are `/Users/Zamiell/monorepo/dist/packages/foo`, so the "sources" property looks backwards into directories that don't exist on the computers of the end-users.

It's unclear how to solve this problem:

- If we manually add the `.ts` files after the compilation step, that doesn't help anything, because the `.d.ts.map` files are already created with the erroneous paths.
- If we manually add the `.ts` files before the compilation, that doesn't help anything, because then all of the import statements break, as the paths to all of the libraries and what-not have changed.

Is this problem solvable?

Note that this isn't a problem with other monorepo tools, because it doesn't consolidate the `dist` directory like NX does.

**Comment by aymanmoukhtar** [comment]
Having the same problem, Is there any fix to this?

**Comment by Zamiell** [comment]
Until NX fixes this problem, I have to do a disgusting hack like this:

#### rewriteDeclarationMapPaths.ts
```ts
import * as fs from "fs";
import glob from "glob";
import { file } from "isaacscript-cli";
import * as JSONC from "jsonc-parser";
import path from "path";

const PACKAGE_ROOT = path.join(__dirname, "..");
const REPO_NAME = path.basename(PACKAGE_ROOT);
const TSCONFIG_PATH = path.join(PACKAGE_ROOT, "tsconfig.json");

main();

function main() {
  const outDir = getOutDir();
  const distDir = path.resolve(PACKAGE_ROOT, outDir);
  const globPath = "/**/*.d.ts.map";
  const filePaths = glob.sync(globPath, {
    root: distDir,
  });
  if (filePaths.length === 0) {
    error(`Failed to find any files in the following glob: ${globPath}`);
  }

  for (const filePath of filePaths) {
    const fileContents = file.read(filePath, false);
    const newFileContents = fileContents.replaceAll(
      `../../../../packages/${REPO_NAME}`,
      "..",
    );
    file.write(filePath, newFileContents, false);
  }
}

function getOutDir(): string {
  let fileContents: string;
  try {
    fileContents = fs.readFileSync(TSCONFIG_PATH, "utf8");
  } catch (err) {
    error(`Failed to read the "${TSCONFIG_PATH}" file:`, err);
  }

  let config: Record<string, unknown>;
  try {
    config = JSONC.parse(fileContents) as Record<string, unknown>;
  } catch (err) {
    error(`Failed to parse the "${TSCONFIG_PATH}" file:`, err);
  }

  if (typeof config !== "object") {
    error(`Failed to read the config file: ${TSCONFIG_PATH}`);
  }

  const { compilerOptions } = config;
  if (typeof compilerOptions !== "object") {
    error(`Failed to read the "compilerOptions" field in: ${TSCONFIG_PATH}`);
  }

  const { outDir } = compilerOptions as Record<string, unknown>;
  if (typeof outDir !== "string") {
    error(`Failed to read the "outDir" field in: ${TSCONFIG_PATH}`);
  }

  return outDir;
}

function error(...args: unknown[]): never {
  console.error(...args);
  return process.exit(1);
}
```

**Comment by aymanmoukhtar** [comment]
I resolved to adding `"inlineSources": true` in `tsconfig.base.json`, and if you do this, you don't have to publish the source files, they will be included in the map file under `sourceContent`.
