### ISSUE TITLE
Imports of lazy loaded libraries forbidden not triggered

### ISSUE THREAD

**Issue by romainZiba** [nrwl/nx#11178]
Hello everyone, I may have missed something regarding this Eslint rule. Though, I think this use-case is quite disturbing.

## Current Behavior
Lint job for the app is successful

## Expected Behavior
Lint job should fail with error : "Imports of lazy loaded libraries forbidden"

## Steps to Reproduce
1. Clone the repo https://github.com/romainZiba/nx_issue_lazy
2. Run nx run repro:lint

### Environment
nx v14.4.3
npm v8.11.0
node v16.15.1

**Comment by FrozenPandaz** [comment]
Thank you for the repro. This certainly is an issue, we will take a look.
