### ISSUE TITLE
Running build with the --watch flag makes the cli hang

### ISSUE THREAD

**Issue by Rofer11607** [nrwl/nx#11186]
## Current Behavior

I currently have an app that was building just fine, I tried to use a library from the 'libs' folder; now the app will build if I manually say 'nx build server' however if I run 'nx build server -- watch' it gets to the typescript output 'Found 0 errors. Watching for file changes' however if I make changes to the file nothing happens, nothing changes in dist/apps/server output. If I purposefully try to add an error, typescript doesn't output the error in the terminal like it normally does

## Expected Behavior

I noticed this behavior when I first tried to use the library in my mono repo, it now says that it depends on the project when building and in the graph; I have since removed the import statement however the mono repo still seems to think that the app depends on the library.

## Steps to Reproduce

Not sure how to provide this; I will try to get my employer to allow some code to be posted here. In the meantime is there a workaround to remove the dependency manually could it be my version of node? (16.16.0)

### Environment

  Node : 16.16.0
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 14.1.7
   @nrwl/angular : 14.1.7
   @nrwl/cypress : 14.1.7
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.7
   @nrwl/eslint-plugin-nx : 14.1.7
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.7
   @nrwl/js : 14.1.7
   @nrwl/linter : 14.1.7
   @nrwl/nest : 14.1.7
   @nrwl/next : Not Found
   @nrwl/node : 14.1.7
   @nrwl/nx-cloud : 14.0.5
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.7
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.7
   typescript : 4.6.4
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
         ngx-spinner: 13.1.1

**Comment by Rofer11607** [comment]
** Update
I commented out the line in the workspace.json that defines the path for the library in question and it started working. The question now is why is the --watch flag not working when linking this project internally to the lib?

**Comment by Rofer11607** [comment]
** Update
I tried to transpile it again and now it is saying that the library is not int the root dir 'apps/server', its def not, its in 'libs/crm-sdk/' I tried to change the root dir in the ts-config itself however it doesn't seem to make a difference

**Comment by FrozenPandaz** [comment]
If I understand correctly, you have an application that depends on a buildable library?

This is all normal but won't work well with `nx build app1 --watch` :thinking: Rather, it would be better to use `nx serve app1` instead which should handle watching the sources of dependencies as well.

Check out our guide on [Incremental Builds](https://nx.dev/ci/setup-incremental-builds-angular#setup-incremental-builds-for-angular-applications) to learn more.
