### ISSUE TITLE
feat: extract package manager utilities in separate package

### ISSUE THREAD

**Issue by MichaelDeBoey** [nrwl/nx#11197]
## Description
Have a separate package that _only_ exports the package manager utilities

## Motivation
I recently created a PR to @remix-run's `indie-stack` (https://github.com/remix-run/indie-stack/pull/126) where I copied over quit some code from this repo (with some minor changes).

Since these 2 functions could be very handy in `@remix-run/dev` too, it would be lovely to have it in a separate package instead of us needing to have `nx` as a dependency _or_ copy/paste it into `@remix-run/dev` & all 3 stacks' `remix.init` folder & maintain it ourselves, while you guys are already maintaining it.

https://github.com/nrwl/nx/blob/38a2d95d9d654c89f58ed6700ec7b6cc01ddf74b/packages/nx/src/utils/package-manager.ts#L38-L114

## Suggested Implementation
Create a separate package that exports the package manager utilities.

## Alternate Implementations
- Importing `nx` as dependency of `@remix-run/dev` & all 3 stacks' `remix.init` folder
- Copy/paste the needed utilities into `@remix-run/dev` & all 3 stacks

**Comment by MichaelDeBoey** [comment]
I still think this is a valuable feature

**Comment by AgentEnder** [comment]
I don't disagree that there is value here, but I'm not sure that we want to bring larger attraction to them as that will increase the maintenance burden.

e.g. We don't support Bun for installation yet, but if this was a wider ecosystem library there would be more of a compulsion to do so.

I'm going to close this out as such, the utils are largely internal and we don't want to lose the ability to modify them as needed.

**Comment by MichaelDeBoey** [comment]
@AgentEnder Would you be OK with me creating such a third-party library & using it in NX instead?

**Comment by AgentEnder** [comment]
You can create the lib, but we likely would not change our internal implementation. Like I said,
>  we don't want to lose the ability to modify them as needed.
