### ISSUE TITLE
Library Generator Directory issue

### ISSUE THREAD

**Issue by njohnson-ml** [nrwl/nx#11193]
## Current Behavior

I am using `libraryGenerator` from `@nrwl/workspace/generators` as part of a custom workspace generator.
When I specify a directory on the Schema, an error is thrown:

```
% npx nx workspace-generator node-lib test-dir-specific --directory test-lib-dir
>  NX  Generating /dist/out-tsc/tools/generators/workspace-generators.json:node-lib

Cannot find configuration for 'test-dir-specific' in /workspace.json.
``` 

If I do not set the directory, the library generates as expected in the root of the `libs` directory.

## Expected Behavior

I would expect to be able to specify the directory in `libs` that the library gets generated in.
i.e. `libs/<directory-name>`

## Steps to Reproduce

- Create a new workspace generator
- Set a directory on the schema for the generator
- Run the workspace generator 

### Environment

```
Node : 16.14.0
   OS   : darwin x64
   npm  : 8.3.1
   
   nx : 14.3.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.3
   @nrwl/eslint-plugin-nx : 14.3.3
   @nrwl/express : 14.3.3
   @nrwl/jest : 14.3.3
   @nrwl/js : 14.3.3
   @nrwl/linter : 14.3.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.3.3
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.3.3
   typescript : 4.3.5
```

**Comment by FrozenPandaz** [comment]
Can you share the source of your workspace-generator?

I can't tell exactly what you're trying to do but are you perhaps reading the configuration after the library is generated?

Example:
```ts
await libraryGenerator(tree, { name: 'my-lib', directory: 'my-dir' });
...
const proj = readProjectConfiguration(tree, 'my-lib');
```

This will fail because the project that was created using the `libraryGenerator` is actually `my-dir-my-lib` so you'd want to do the following instead:


```ts
await libraryGenerator(tree, { name: 'my-lib', directory: 'my-dir' });
...
const proj = readProjectConfiguration(tree, 'my-dir-my-lib');
```

**Comment by njohnson-ml** [comment]
Ah, that was exactly my problem. Thanks!
