### ISSUE TITLE
Project named with dash in front cannot be managed

### ISSUE THREAD

**Issue by ALMaclaine** [nrwl/nx#11199]
I accidentally created a lib with a dash (I'm not sure how, I can't find command):

```
  "projects": {
    "-client-hooks-use-abort-manager": "libs/client/hooks/use-abort-manager",
```

nx fails to manage this project:

```
pnpm nx g @nrwl/workspace:remove "-client-hooks-use-abort-manager"              

>  NX  Generating @nrwl/workspace:remove


 >  NX   Required property 'projectName' is missing
```

```
pnpm nx g @nrwl/workspace:remove --projectName "-client-hooks-use-abort-manager"

>  NX  Generating @nrwl/workspace:remove


 >  NX   Property 'projectName' does not match the schema. 'true' should be a 'string'.
```

```
pnpm nx g @nrwl/workspace:move "client/hooks/use-abort-manager" --projectName "-client-hooks-use-abort-manager"

>  NX  Generating @nrwl/workspace:move


 >  NX   Property 'projectName' does not match the schema. 'true' should be a 'string'.
```

**Comment by AgentEnder** [comment]
This isn't really a bug, when parsing command line args a `-` represents a flag and in this case `--projectName` is translated as `--projectName=true` and `-client-hooks-use-abort-manager` as a separate flag...

This is something that we can't really change as it comes from `yargs` parsing. The recommendation would be to update the project name.

**Comment by ALMaclaine** [comment]
@AgentEnder So I can just rename the project directly in workspace.json?

**Comment by AgentEnder** [comment]
Yeah
