### ISSUE TITLE
Changing styles in react with storybook leads to `Ignored an update to unaccepted module ./apps/ata/src/styles.css`

### ISSUE THREAD

**Issue by herrKlein** [nrwl/nx#11209]
## Current Behavior
due to this error : ```Ignored an update to unaccepted module```
storybook does not show the changes made to tailwind classes in my component.
Changes will show after manual refresh

## Expected Behavior
Update or refresh storybook to reflect css changes.
I think HMR in storybook can't update changes to tailwind

## Steps to Reproduce
Create a workspace, choose react and css
`npx create-nx-workspace@latest`
Install tailwind according to the steps in the NX documentation
`npm install -D tailwindcss@latest postcss@latest autoprefixer@latest`
Configure tailwind according to the NX documentation
`npx tailwindcss init -p`
Add storybook
`nx g @nrwl/react:storybook-configuration ata`

add `import '../src/styles.css'` to the preview.js so that storybook also imports the generated tailwind classes

start both storybook and the app
`nx serve`
`nx run <project-name>:storybook`

add `<div className='bg-red-200'>test</div>` to the App component.
change `bg-red-200` to `bg-blue-500`
- Changes will reflect in the app which is served
- Changes will not reflect due to an error ( see below ), but will after manual refreshing storybook.

### Failure Logs
`Ignored an update to unaccepted module ./apps/ata/src/styles.css -> ./apps/ata/.storybook/preview.js -> ./apps/ata/.storybook/preview.js-generated-config-entry.js`

### Environment
```
Node : 16.13.2
   OS   : darwin x64
   npm  : 8.1.2
   
   nx : 14.4.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.4.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.3
   @nrwl/eslint-plugin-nx : 14.4.3
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.3
   @nrwl/js : 14.4.3
   @nrwl/linter : 14.4.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.4.3
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.3
   @nrwl/web : 14.4.3
   @nrwl/workspace : 14.4.3
   typescript : 4.7.4
   ---------------------------------------
```

**Comment by andrewszucs** [comment]
I ran into the same issue. I found a solution [here](https://github.com/tailwindlabs/tailwindcss/discussions/6570#discussioncomment-2017456), which worked for me, but I'm hoping to understand the issue more and find alternative solutions if exist.
