### ISSUE TITLE
React-native new architecture & Hermes

### ISSUE THREAD

**Issue by HekTheLastSavior** [nrwl/nx#11203]
When creating  a new react-native app or maybe upgrading ask if we need to enable Hermes and the new architecture.
They both require minor changes in the android and ios directories.

**Comment by xiongemi** [comment]
Hello, @HekTheLastSavior Currently @nrwl/react-native uses 0.69.1 which should have new architecture as default. what additional changes did you make?

**Comment by HekTheLastSavior** [comment]
I'm wondering if when we create a new react-native app by to be asked by the NX cli if we want to enable hermes and the new architecture.
it's a feature request.

**Comment by xiongemi** [comment]
@HekTheLastSavior I think currently @nrwl/react-native just copies the native code from the react-native library as it is. I do not want to derail from that, just in case it react-native team decides to turn it on by default. you could still manually turn it on.
