### ISSUE TITLE
`ExecutorContext.workspace.npmScope` is not not being sent as part of the executor context for custom executors

### ISSUE THREAD

**Issue by DibyodyutiMondal** [nrwl/nx#11205]
## Current Behavior
Let us say that we have a custom executor that adds a symlink between the output and node_modules (#9304).
It just symlinks the paths, before passing it on to the actual `@nrwl/js:tsc` executor
This used to work in previous versions, but after migrating to v14, `context.workspace.npmScope` returns `undefined`, even though it has been set in nx.json.

```typescript
import { ExecutorContext } from '@nrwl/devkit';
import { tscExecutor as nrwl_tsc_exec } from '@nrwl/js/src/executors/tsc/tsc.impl';
import { ExecutorOptions } from '@nrwl/js/src/utils/schema';
import * as fs from 'fs/promises';
import * as path from 'path';

export async function* tscExecutor(
    options: ExecutorOptions,
    context: ExecutorContext
) {
    const dist_path = path.resolve(context.cwd, options.outputPath);

    // symlink the libraries so that nodemon can work
    if (context.workspace.projects[context.projectName!].projectType === 'library') {
        const node_path = path.resolve(context.cwd, `node_modules/@${context.workspace.npmScope}/${context.projectName}`);
        await fs.rm(node_path, { recursive: true, force: true });
        await fs.mkdir(path.resolve(node_path, '..'), { recursive: true });
        await fs.symlink(dist_path, node_path, 'dir');
    }

    return yield* nrwl_tsc_exec(options, context);
}

export default tscExecutor;
```

## Expected Behavior
`context.workspace.npmScope` will return the npmScope as specified in nx.json
Is this a regression? Yes

## Steps to Reproduce
1. make the custom executor and add it as a target executor for any plain typescript project
2. ensure that `"projectType": "library"` is specified in `project.json`
3. run the executor (`--skip-nx-cache` is useful for debugging)
4. We should see the output in the `dist` folder, and a symlink to this output folder via `node_modules/@undefined`.
5. I tried to debug and pause and try to find `npmScope` somewhere in the arguments passed to the executor, but I could not find it.

### Failure Logs
No failure logs: Task failed successfully...

### Environment

```
 >  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : linux x64
   npm  : 8.13.2

   nx : 14.4.3
   @nrwl/angular : 14.4.3
   @nrwl/cypress : 14.4.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.3
   @nrwl/eslint-plugin-nx : 14.4.3
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.3
   @nrwl/js : 14.4.3
   @nrwl/linter : 14.4.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.3
   @nrwl/web : 14.4.3
   @nrwl/workspace : 14.4.3
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
```

**Comment by Phault** [comment]
It appears that ExecutorContext.workspace no longer includes NxJsonConfiguration, despite its type still saying it does. Guessing this was introduced by #10860 as it worked fine in v14.3.6.

**Comment by AgentEnder** [comment]
I believe this should be fixed now, I'm going to close this out as such. If anyone can confirm this still happens, feel free to let me know and I'll reopen it.

**Comment by fernandobracaroto** [comment]
> I believe this should be fixed now, I'm going to close this out as such. If anyone can confirm this still happens, feel free to let me know and I'll reopen it.

Not working, context.workspace.npmScope is undefined.  "nx": "15.2.1"
