### ISSUE TITLE
React Native incorrect version and incorrect setup

### ISSUE THREAD

**Issue by HekTheLastSavior** [nrwl/nx#11201]
NX 14.4.3

## Current Behavior
New fresh installation of Nx and react-native, I can't install any npm package because of the conflict between react-native and react.
React is set at version 18.02 and react-native at version 0.68.2.

Based on the documentation from react-native version 0.68.2 can only be suitable with version of react 17.x.

## Expected Behavior
To have the latest version of react-native currently 0.69.1 and have the correct android and ios files .
It seems that some kind migrations was happening but it's not complete.

## Steps to Reproduce
```
npx create-nx-workspace XXX
npm install XXX
```

### Environment
Linux zsh

**Comment by xiongemi** [comment]
@HekTheLastSavior yes. there is a version conflict. However, just use `npm install xxx --force` flag. If you upgrade your @nrwl/react-native package, which now also supports react-native 0.69 and react 18 as well.

**Comment by HekTheLastSavior** [comment]
@xiongemi okay, I'll give it a try
