### ISSUE TITLE
Nx react-native upgrade-native for vsCOde

### ISSUE THREAD

**Issue by HekTheLastSavior** [nrwl/nx#11202]
## Current Behavior
the moment you enter a package name in the "project name" field it wipes out the android and ios directories.
and when run it crashes.

```
>  NX  Generating @nrwl/react-native:upgrade-native


 >  NX   Could not upgrade React Native code for end-user

   Pass --verbose to see the stacktrace.

The terminal process "/usr/bin/zsh '-c', 'npx nx generate @nrwl/react-native:upgrade-native end-user --no-interactive'" terminated with exit code: 1.
```

## Expected Behavior
Not to wipe out the directories without warning or actually taking action.
I think the dry run is running and it's not really dry lol.

## Steps to Reproduce
Just enter the name of a react-native app in the project name field.

### Environment
linux vscode

**Comment by xiongemi** [comment]
this should be fixed for pr https://github.com/nrwl/nx/pull/11369.
