### ISSUE TITLE
Add report-unused-disable-directives options for eslint plugin

### ISSUE THREAD

**Issue by peterreisz** [nrwl/nx#11212]
Add option to control the given settings via plugin option:
https://eslint.org/docs/latest/user-guide/command-line-interface#--report-unused-disable-directives

- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Increase code quality by removing unused disable directives

## Motivation

Increase code quality

## Suggested Implementation

Update the option mapping here:
https://github.com/nrwl/nx/blob/master/packages/linter/src/executors/eslint/utility/eslint-utils.ts#L44
```ts
reportUnusedDisableDirectives: options.reportUnusedDisableDirectives
```

Also update the option interface

**Comment by meeroslav** [comment]
Thank you for this suggestion @peterreisz.

Please go ahead and create a PR with this improvement!
