### ISSUE TITLE
How to consume @nrwl/remote in application that is not using Nx?

### ISSUE THREAD

**Issue by sumansaurav91** [nrwl/nx#11218]
### Discussed in https://github.com/nrwl/nx/discussions/11217

<div type='discussions-op-text'>

<sup>Originally posted by **sumansaurav91** July 19, 2022</sup>
I have created 2 remote component in Nx and configure webpack, remote entry and module federation. I want to inject this in application that not using Nx. How can I do this?</div>

**Comment by AgentEnder** [comment]
Closing as a duplicate of #11217, discussion can take place there.
