### ISSUE TITLE
WARNING in DefinePlugin Conflicting values for 'process.env.NODE_ENV'

### ISSUE THREAD

**Issue by avol-io** [nrwl/nx#11222]
To reopen  #7924

**Comment by mandarini** [comment]
Ohhh it's the `process.env.NODE_ENV warning`, right? It works, but it gives a warning, that's all, right?

**Comment by mandarini** [comment]
So, @avol-io this is an issue that appears in the Storybook side. You can check out [this reproduction](https://github.com/mandarini/pure-angular-storybook),  which is just a pure Angular app (no Nx) with Storybook. The same warning appears. Check out the log [here](https://app.warp.dev/block/bGg587ZUdts461JdtuRVaa). On Nx, we are using the [Storybook builders](https://nx.dev/storybook/extra-topics-for-angular-projects) directly (`@storybook/angular:start-storybook`). There's no "middle-person" between your app and Storybook in that case. So all logs are on the Storybook side. You can open an issue on the Storybook repo about that warning!

Thank you so much!! :D
