### ISSUE TITLE
Nx 14 migration error:  The "path" argument must be of type string or an instance of Buffer or URL. Received null

### ISSUE THREAD

**Issue by kwu-work** [nrwl/nx#11243]
## Current Behavior

Trying to migrate from Nx 13.3.9 to latest (14.4.3)
1. rm -rf node_modules
2. npm i --legacy-peer-deps
3. npx nx migrate latest
4. npm i --legacy-peer-deps
5. npx nx migrate --run-migrations --verbose
6. got error: 
```
>  NX  Running migrations from 'migrations.json'

Running migration 14-0-6-remove-root

 >  NX   The "path" argument must be of type string or an instance of Buffer or URL. Received null


TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received null
    at Object.openSync (node:fs:577:10)
    at readFileSync (node:fs:453:35)
    at readJsonFile (/private/var/folders/pf/5xs2my6n7jg58lyy1_5s95thsrqq4_/T/tmp-76749-TNRzzaM5dBAc/node_modules/nx/src/utils/fileutils.js:18:43)
    at /private/var/folders/pf/5xs2my6n7jg58lyy1_5s95thsrqq4_/T/tmp-76749-TNRzzaM5dBAc/node_modules/nx/src/command-line/migrate.js:704:57
    at Generator.next (<anonymous>)
    at /private/var/folders/pf/5xs2my6n7jg58lyy1_5s95thsrqq4_/T/tmp-76749-TNRzzaM5dBAc/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/private/var/folders/pf/5xs2my6n7jg58lyy1_5s95thsrqq4_/T/tmp-76749-TNRzzaM5dBAc/node_modules/tslib/tslib.js:114:16)
    at runNxMigration (/private/var/folders/pf/5xs2my6n7jg58lyy1_5s95thsrqq4_/T/tmp-76749-TNRzzaM5dBAc/node_modules/nx/src/command-line/migrate.js:702:20)
    at /private/var/folders/pf/5xs2my6n7jg58lyy1_5s95thsrqq4_/T/tmp-76749-TNRzzaM5dBAc/node_modules/nx/src/command-line/migrate.js:617:23
Command failed: /var/folders/pf/5xs2my6n7jg58lyy1_5s95thsrqq4_/T/tmp-76749-TNRzzaM5dBAc/node_modules/.bin/nx _migrate --run-migrations --verbose
```
any help would be greatly appreciated.

### Environment

 Node : 16.14.2
OS   : darwin x64
npm  : 8.5.0

nx : 13.10.0
@nrwl/angular : 14.4.3
@nrwl/cypress : 14.4.3
@nrwl/detox : Not Found
@nrwl/devkit : 13.10.0
@nrwl/eslint-plugin-nx : 14.4.3
@nrwl/express : Not Found
@nrwl/jest : 14.4.3
@nrwl/js : 14.4.3
@nrwl/linter : 14.4.3
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/nx-cloud : Not Found
@nrwl/nx-plugin : Not Found
@nrwl/react : Not Found
@nrwl/react-native : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : 14.4.3
@nrwl/web : 14.4.3
@nrwl/workspace : 14.4.3
typescript : 4.7.4
rxjs : 7.3.0
---------------------------------------
Community plugins:
  @ngrx/store: 14.0.2
  @compodoc/compodoc: 1.1.19
  @jscutlery/semver: 2.17.5
  @storybook/angular: 6.4.22

**Comment by llnathanll** [comment]
I'm not able to replicate your error, but it's odd that in your `npx nx report` you are still showing `nx: 13.10.0`.  It looks as though nx was upgraded from your original 13.3, but only to the next major version and not all the way to 14.4.3.  The [docs](https://nx.dev/using-nx/updating-nx) say to upgrade one major version at a time, so maybe you first need to migrate from 13.3 to 13.10, and then from 13.10 to latest.

**Comment by FrozenPandaz** [comment]
I also was not able to reproduce this. Could you please provide a repo that demonstrates the issue?
