### ISSUE TITLE
Angular AoT runtime error with Module Federation in NX13 and NX14 (Cannot read properties of undefined (reading 'ɵcmp'))

### ISSUE THREAD

**Issue by TimHermens** [nrwl/nx#11259]
## Current Behavior
I'm trying to implement the Module Federation architecture in my app, but I'm running into a runtime error whenever I try to run  my app with the AoT (Ahead of Time) option enabled:

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'ɵcmp')
TypeError: Cannot read properties of undefined (reading 'ɵcmp')
    at getComponentDef (node_modules_angular_core_fesm2015_core_mjs.js:1778:14)
    at extractDirectiveDef (node_modules_angular_core_fesm2015_core_mjs.js:1580:15)
    at Array.map (<anonymous>)
    at def.directiveDefs (node_modules_angular_core_fesm2015_core_mjs.js:1555:123)
    at createTView (node_modules_angular_core_fesm2015_core_mjs.js:12100:59)
    at getOrCreateTComponentView (node_modules_angular_core_fesm2015_core_mjs.js:12011:24)
    at createRootComponentView (node_modules_angular_core_fesm2015_core_mjs.js:14990:47)
    at ComponentFactory.create (node_modules_angular_core_fesm2015_core_mjs.js:25603:29)
    at ViewContainerRef.createComponent (node_modules_angular_core_fesm2015_core_mjs.js:27055:43)
    at IonRouterOutlet.activateWith (default-node_modules_ionic_angular_fesm2015_ionic-angular_js.js:4941:49)
    at resolvePromise (polyfills.js:6889:19)
    at resolvePromise (polyfills.js:6836:9)
    at polyfills.js:6963:9
    at _ZoneDelegate.invokeTask (polyfills.js:5910:171)
    at Object.onInvokeTask (node_modules_angular_core_fesm2015_core_mjs.js:30190:25)
    at _ZoneDelegate.invokeTask (polyfills.js:5910:54)
    at Zone.runTask (polyfills.js:5669:39)
    at drainMicroTaskQueue (polyfills.js:6119:23)
```
As you can see from the error stack trace, the error is thrown by the `getComponentDef` Angular core function:

```javascript
function getComponentDef(type) {
    return type[NG_COMP_DEF] || null;
}
```

This error is specifically thrown whenever Angular tries to retrieve the component definition of a custom `<core-page-header>` HTML element in my page:

```html
<ion-content role="main">
  <core-page-header title="{{ 'TITLE' | translate }}"></core-page-header>

  <div content>
    <button routerLink="/mortgages-fm/fm-page2">FM page 2</button>
  </div>
</ion-content>
```
Angular core cannot find the typing of this element and is passing a `undefined` type into the `getComponentDef` Angular core function which is causing the error: `TypeError: Cannot read properties of undefined (reading 'ɵcmp')`.

This issue only happens when I enable AoT. The app runs fine if I either:

1. disable AoT, or
2. leave AoT enabled and either:
   1. take out the lib `ui-components` from `angular.json` that exports this `<core-page-header>` component, or
   2. take out the lib `ui-components` from the `resolve.alias` webpack config setting

But this is of course a very bad workaround, not a solution.

The issue happens in both NX13 and NX14.

## Expected Behavior
I can run my app with Module Federation and AoT mode enabled without any runtime errors.

## Steps to Reproduce
Please checkout my Github repo: https://github.com/TimHermens/angular-nx-aot-issue. This repo contains a very small app in which I reproduced the issue. I have included some extra information about reproducing the issue in the readme.

### Another issue with Angular 14
I have also noticed a difference in runtime errors between Angular 13 and Angular 14 when you use `@angular-architects/module-federation/` helper functions in your webpack config instead of NRWL. I have noticed that a lot of bundles are suddenly missing when the app is built with Angular 14 in this manner (all the `@angular/*` and `@ionic/*` bundles are missing). These bundles are essential to run the app. I have documented this issue in the readme as well. I'm unsure what is causing this (it is not `aot` in this case), so I would appreciate if anyone could help me find the root problem here as well.

### Failure Logs
The runtime error I get when running the app with AoT mode enabled:

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'ɵcmp')
TypeError: Cannot read properties of undefined (reading 'ɵcmp')
    at getComponentDef (node_modules_angular_core_fesm2015_core_mjs.js:1778:14)
    at extractDirectiveDef (node_modules_angular_core_fesm2015_core_mjs.js:1580:15)
    at Array.map (<anonymous>)
    at def.directiveDefs (node_modules_angular_core_fesm2015_core_mjs.js:1555:123)
    at createTView (node_modules_angular_core_fesm2015_core_mjs.js:12100:59)
    at getOrCreateTComponentView (node_modules_angular_core_fesm2015_core_mjs.js:12011:24)
    at createRootComponentView (node_modules_angular_core_fesm2015_core_mjs.js:14990:47)
    at ComponentFactory.create (node_modules_angular_core_fesm2015_core_mjs.js:25603:29)
    at ViewContainerRef.createComponent (node_modules_angular_core_fesm2015_core_mjs.js:27055:43)
    at IonRouterOutlet.activateWith (default-node_modules_ionic_angular_fesm2015_ionic-angular_js.js:4941:49)
    at resolvePromise (polyfills.js:6889:19)
    at resolvePromise (polyfills.js:6836:9)
    at polyfills.js:6963:9
    at _ZoneDelegate.invokeTask (polyfills.js:5910:171)
    at Object.onInvokeTask (node_modules_angular_core_fesm2015_core_mjs.js:30190:25)
    at _ZoneDelegate.invokeTask (polyfills.js:5910:54)
    at Zone.runTask (polyfills.js:5669:39)
    at drainMicroTaskQueue (polyfills.js:6119:23)
```

The runtime error I get when running the app with AoT mode enabled on Angular 14 with the webpack config configured with `@angular-architects/module-federation/` helper functions instead of NRWL:

```
Error: Cannot find module '@angular/platform-browser'
    at webpackMissingModule (main.js:436:179)
    at main.js:436:279
    at __webpack_require__.m.<computed> (main.js:472:33)
    at __webpack_require__ (main.js:33:41)
    at 776 (apps_mortgages-fm_src_bootstrap_ts.js:153:83)
    at Function.__webpack_require__ (main.js:33:41)
    at _ZoneDelegate.invoke (polyfills.js:5877:158)
    at Zone.run (polyfills.js:5616:37)
    at polyfills.js:6962:28
    at _ZoneDelegate.invokeTask (polyfills.js:5910:171)
```

#### Angular 13 environment
```
Node : 16.14.0
   OS   : darwin x64
   yarn : 1.22.17
   
   nx : 13.10.4
   @nrwl/angular : 13.10.4
   @nrwl/cypress : 13.10.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.4
   @nrwl/eslint-plugin-nx : 13.10.4
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.4
   @nrwl/js : 13.10.4
   @nrwl/linter : 13.10.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 13.10.4
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.10.4
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.4
   @nrwl/web : 13.10.4
   @nrwl/workspace : 13.10.4
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         @ionic/angular: 5.6.5
         @ionic/angular-toolkit: 2.3.3
         @ngneat/spectator: 10.0.0
         ng-mocks: 13.0.4
```

#### Angular 14 environment
```
Node : 16.14.0
   OS   : darwin x64
   yarn : 1.22.17
   
   nx : 14.4.3
   @nrwl/angular : 14.4.3
   @nrwl/cypress : 14.4.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.3
   @nrwl/eslint-plugin-nx : 14.4.3
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.3
   @nrwl/js : 14.4.3
   @nrwl/linter : 14.4.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.4.3
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.4.3
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.3
   @nrwl/web : 14.4.3
   @nrwl/workspace : 14.4.3
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
         @ionic/angular: 6.1.15
         rxjs: 6.6.7
         @ionic/angular-toolkit: 7.0.0
         @ngneat/spectator: 10.0.0
         ng-mocks: 14.1.0
```

**Comment by TimHermens** [comment]
Ok, I actually figured out what was causing the error:

```
Cannot read properties of undefined (reading 'ɵcmp')
```

I somehow missed that you had to also export all the individual components in your barrel file of your lib and not just the module. The app runs fine in AoT mode if I add the missing component exports to my shared lib:

```javascript
export * from './lib/ui-components.module';
export * from './lib/page-header/page-header.component'; // added this
```

This resolved both my NX 13 and NX 14 issues. I'm closing this issue. I hope that this information would be useful for someone else too.

**Comment by Arthur-Fedotiev** [comment]
> Ok, I actually figured out what was causing the error:
> 
> ```
> Cannot read properties of undefined (reading 'ɵcmp')
> ```
> 
> I somehow missed that you had to also export all the individual components in your barrel file of your lib and not just the module. The app runs fine in AoT mode if I add the missing component exports to my shared lib:
> 
> ```js
> export * from './lib/ui-components.module';
> export * from './lib/page-header/page-header.component'; // added this
> ```
> 
> This resolved both my NX 13 and NX 14 issues. I'm closing this issue. I hope that this information will be useful for someone else too.

Thank you very much Sir! You literally saved my day :)

**Comment by fvoska** [comment]
Although the solution works and I am fine with exporting not just the modules but individual components as well, I feel like it is not ok to close this issue, as I would still like to be able to export just modules. At the very minimum Nx documentation should mention that this is an important step when defining lib exports.

**Comment by ringodotnl** [comment]
Seems issue here, we had to export, besides the module, a component in the index.ts which without MF wasn't needed, bug?

**Comment by TimHermens** [comment]
Yes I suppose the NX documentation is lacking information regarding this potential issue. I would strongly recommend you to configure your custom libs' build architect with NRWL's ng-packagr executors (or anything similar) in your `angular.json` or `project.json` file. This executor will validate if you have exported everything that is referenced in your Angular modules.

```json
    "build": {
      "executor": "@nrwl/angular:ng-packagr-lite",
      "outputs": ["dist/libs/flight/ui"],
      "options": {
        "project": "libs/flight/ui/ng-package.json"
      },
      "configurations": {
        "production": {
          "tsConfig": "libs/flight/ui/tsconfig.lib.prod.json"
        },
        "development": {
          "tsConfig": "libs/flight/ui/tsconfig.lib.json"
        }
      },
      "defaultConfiguration": "production"
    },
```

The `libs/flight/ui/ng-package.json` file simply packages everything from the lib's barrel file:

```ts
{
  "$schema": "../../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../../dist/libs/flight/ui",
  "lib": {
    "entryFile": "src/index.ts"
  }
}
```

So, if you would try to build your project when you have just exported the module in your barrel file, the ng-packagr builder would throw an error because it also expects to find export definitions of the Angular components/directives/etc. that are part of that module.

So if I would try to just export a module like this:

```ts
export * from './lib/flight-card/flight-card.module';
// export * from './lib/flight-card/flight-card.component';
```
The `nx build` command would produce the following error:

`Unsupported private class FlightCardComponent. This class is visible to consumers via FlightCardModule -> FlightCardComponent, but is not exported from the top-level library entrypoint.`

**Comment by deefactorial** [comment]
Since I have a lot of components in my libraries, I developed this command to help automate adding to the barrel export index.ts file all the component files.

```bash
find "lib" -type f -name "*.component.ts" | sed -e 's/\.ts//' | while read filepath; do echo "export * from './$filepath'"; done >> index.ts
```

run this in your library `src` directory.
hope it helps someone.
