### ISSUE TITLE
jest.config.js not created if jest already installed

### ISSUE THREAD

**Issue by ph55** [nrwl/nx#1125]
## Expected Behavior

`jest.config.js` should be added when first jest app created even if `jest` already installed.

## Current Behavior

If `jest` already exists in `package.json` as dependency, `jest.config.js` won't be created.
Also following dependencies won't be added:

```json
    "@types/jest": "23.0.0",
    "jest-preset-angular": "6.0.1"
```

Which then leads to more errors, when trying to test lib.

```
ng g lib lib-one --unit-test-runner="jest"
ng test lib-one
```

```
● Validation Error:

  Preset ../../jest.config.js not found.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

● Validation Error:

  Preset ../../jest.config.js not found.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html
```

### Steps to Reproduce

1. `npx -p @nrwl/schematics create-nx-workspace apps-nx`
2. `npm install jest@23.0.0 --save-dev --save-exact`
3. `ng g app app-one --unit-test-runner="jest"`

### Use case

You will not get this error when following "Getting started guide".

This use case more for people that already have angular/nx project and have their preset of common packages they work with.

`packaje.json` could be merged with nx default one before creating first app.

**Comment by FrozenPandaz** [comment]
Yes, existence of the `jest` dependency is the criteria for generating the `jest.config.ts`.

I don't think it's high priority since it's easy to add jest by skipping step 2. Someone can help adjust the criteria for generating `jest.config.js` though :)

**Comment by mehrad-rafigh** [comment]
@FrozenPandaz what do you have in mind?

**Comment by vsavkin** [comment]
@mehrad-rafigh I think we should change the check to see if we have `@nrwl/jest` installed instead of `jest`.

**Comment by mehrad-rafigh** [comment]
@vsavkin thank you for pointing me to the right direction. I will take a look at this.

**Comment by vsavkin** [comment]
Looked into it more. I misunderstood the issue. Fixed it by always running the jest init logic, same way we do it with all other packages.
