### ISSUE TITLE
`ng add @nrwl/schematics` Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Doginal** [nrwl/nx#1126]
Trying to convert angular universal app to an nx workspace

## Expected Behavior

`ng add @nrwl/schematics` should migrate angular app to nx workspace.

## Current Behavior

``` 
$ ng add @nrwl/schematics
Skipping installation: Package already installed
? What is the npm scope you would like to use for your Nx Workspace? test
Cannot read property 'split' of undefined
```

is this an error in my project? no stack trace, not sure how to debug this. I can create a new workspace in a different folder, and also migrate a brand new angular app. What could be causing this?

**Comment by FrozenPandaz** [comment]
It's hard to guess without your code but Is `angularCompilerOptions.entryModule` defined in `tsconfig.server.json`? That's one place where we call `.split` on something

**Comment by Doginal** [comment]
`angularCompilerOptions.entryModule` is defined in `ts.config.server.json`, what code do you need to see?

**Comment by jmcdo29** [comment]
@Doginal did you ever find a solution to this? I just ran into it tonight while trying to convert my project to an nx workspace.

**Comment by Doginal** [comment]
@jmcdo29 I did turn out I was missing tsconfig for my tests in angular.json and had some comments in tsconfig files. 

To debug I built a new version of the schematics from master branch and replaced the @nrwl/schematics folder in my node_modules. 
I added some console logs into `/packages/schematics/src/collection/ng-add/index.ts` above each `moveOutOfSrc()` this allowed me to figure out which lines/files were missing/not splitting correctly. Hope this helps!

**Comment by bcabanes** [comment]
We have re-architectured the different Nx packages since then, you can try with the new version and open a new issue if you have any problem. Closing this issue.

**Comment by fishgills** [comment]
I got this today with latest NX:

```➜  neo2.0 git:(u/cdavis/nx) ✗ yarn ng add @nrwl/workspace          
yarn run v1.21.1
$ node_modules/.bin/ng add @nrwl/workspace
Skipping installation: Package already installed
Cannot read property 'split' of undefined
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  neo2.0 git:(u/cdavis/nx) ✗ ```

Not really sure where to look to fix this... trying to read source code right now for NX but that's hard. ;)
