### ISSUE TITLE
Configuring storybook on React library replaces webpack v5 to v4 during npm install

### ISSUE THREAD

**Issue by Pandalovespink** [nrwl/nx#11267]
## Current Behavior
I have 3 React applications and 1 React library, two of the applications use the module federation plugin. Webpack in node_module is v5. Then I run `nx g @nrwl/react:storybook-configuration <lib-project-name>` command to add the storybook to my React library. Up to this point, it's still fine. However, if I run `npm install`, it replaces the webpack from v5 to v4 and I have the following error:

> nx run demo-module-y-app:serve:development

Cannot destructure property 'ModuleFederationPlugin' of 'require(...).container' as it is undefined.

 >  NX   Running target "demo-module-y-app:serve" failed

   Failed tasks:

   - demo-module-y-app:serve:development

   Hint: run the command with --verbose for more details.

## Expected Behavior
npm install after adding storybook should not replace webpack v5 to v4

## Steps to Reproduce
- Have an React application that is referencing the ModuleFederationPlugin example: `const { ModuleFederationPlugin } = require('webpack').container`
- Add storybook configuration: `nx g @nrwl/react:storybook-configuration <lib-project-name>`
- Confirm everything is working by running the application
- run `npm install`
- Confirm again

## Project.json dependencies
"devDependencies": {
    "@babel/core": "7.12.13",
    "@babel/preset-typescript": "7.12.13",
    "@nrwl/cli": "14.2.4",
    "@nrwl/cypress": "14.2.4",
    "@nrwl/eslint-plugin-nx": "14.2.4",
    "@nrwl/jest": "14.2.4",
    "@nrwl/js": "14.4.2",
    "@nrwl/linter": "14.2.4",
    "@nrwl/node": "^14.4.2",
    "@nrwl/react": "^14.2.4",
    "@nrwl/storybook": "14.2.4",
    "@nrwl/web": "14.2.4",
    "@nrwl/workspace": "14.2.4",
    "@storybook/addon-essentials": "~6.5.4",
    "@storybook/builder-webpack5": "~6.5.4",
    "@storybook/core-server": "~6.5.4",
    "@storybook/manager-webpack5": "~6.5.4",
    "@storybook/react": "~6.5.4",
    "@svgr/webpack": "^5.4.0",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "13.3.0",
    "@types/jest": "27.4.1",
    "@types/node": "16.11.7",
    "@types/react": "18.0.12",
    "@types/react-dom": "18.0.5",
    "@types/react-router-dom": "5.3.3",
    "@typescript-eslint/eslint-plugin": "~5.24.0",
    "@typescript-eslint/parser": "~5.24.0",
    "babel-jest": "27.5.1",
    "babel-loader": "8.1.0",
    "cucumber-html-reporter": "^5.5.0",
    "cypress": "^9.1.0",
    "cypress-cucumber-preprocessor": "^4.3.1",
    "eslint": "~8.15.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-jsx-a11y": "6.5.1",
    "eslint-plugin-react": "7.30.0",
    "eslint-plugin-react-hooks": "4.5.0",
    "jest": "27.5.1",
    "nx": "14.2.4",
    "prettier": "^2.6.2",
    "react-test-renderer": "18.1.0",
    "ts-jest": "27.1.4",
    "ts-node": "~10.8.0",
    "typescript": "~4.7.2",
    "url-loader": "^3.0.0"
  },
  "dependencies": {
    "autoprefixer": "^10.4.7",
    "core-js": "^3.6.5",
    "cypress-real-events": "^1.7.1",
    "postcss": "^8.4.14",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-router-dom": "6.3.0",
    "regenerator-runtime": "0.13.7",
    "tailwindcss": "^3.1.0",
    "tslib": "^2.3.0"
  }

### Environment
Node : 16.16.0
   OS   : win32 x64
   npm  : 8.11.0

   nx : 14.2.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.2.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.2.4
   @nrwl/eslint-plugin-nx : 14.2.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.2.4
   @nrwl/js : 14.4.2
   @nrwl/linter : 14.2.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.4.2
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.2.4
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.2.4
   @nrwl/web : 14.2.4
   @nrwl/workspace : 14.2.4
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:

**Comment by mandarini** [comment]
Hi there @Pandalovespink ! Unfortunately I cannot reproduce your issue. [Here](https://github.com/mandarini/module-federation-storybook) is my repository. Can you please create a reproduction repository and share it with me?

Thank you so much for filing an issue, and I'll do what I can to help you!

**Comment by mandarini** [comment]
Hi there @Pandalovespink ! Did you get any chance of creating a reproduction repository, or checking out mine?
