### ISSUE TITLE
error while importing component from lib that using emotion/styled

### ISSUE THREAD

**Issue by netanelvaknin** [nrwl/nx#11270]
## Current Behavior

After creating new nx env. & nx app & nx lib I create a component that using a emotion styled component for example:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/36129935/180581944-f3d2f224-345c-4d12-8c89-0f0afb672bbd.png">

The problem is when I import this component from my app like:
`import {Test} from '@my-app/my-lib'` 
is showing this error:
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/36129935/180581497-41548cbd-24ba-41f7-acb3-4b2e264fb20a.png">

## Expected Behavior
Render the component without any errors on the screen

## Steps to Reproduce

1. migrate existing CRA (create-react-app) to nx with 'npx cra-to-nx' script
2. generate new lib
3. install `@emotion/styled` and `@emotion/core` and `@emotion/react`
4. create new component that using `styled` from `@emotion/styled`
5. import the component from the app use generated

### Environment
`
    "@emotion/core": "^10.3.1",
    "@emotion/react": "^11.7.1",
    "@emotion/styled": "^11.6.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "nx": "14.4.3"
`

`
Node : 16.10.0
OS   : darwin arm64
npm  : 7.24.0
`

**Comment by brianmarco** [comment]
I just tried the steps to reproduce. Unfortunately I was unable to reproduce the issue. That is, I was able to successfully use my lib component. Maybe there's something in the host application that could be part of the problem? Or maybe I didn't recreate the situation correctly? :shrug: 

FWIW here's a sample repo that I created that has my attempt to reproduce the issue - https://github.com/brianmarco/fake-app-11270.

I'm happy to help more if this issue continues for you.
