### ISSUE TITLE
Peer dependencie issue after using nx migrate latest 

### ISSUE THREAD

**Issue by MirkoDaumann** [nrwl/nx#11278]
## Current Behavior
After using nx migrate latest im getting a peer dependencie issue.

## Expected Behavior
I expect my nx workspace to run with Angular 14.

## Steps to Reproduce
```
nx migrate @nrwl/workspace@latest
npm i 
```

### Failure Logs

```
npm ERR! While resolving: xxx@0.0.0
npm ERR! Found: @angular-devkit/build-angular@13.3.8
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"14.0.0" from the root project
npm ERR!   peer @angular-devkit/build-angular@">=0.1102.19 <15.0.0" from jest-preset-angular@12.2.0
npm ERR!   node_modules/jest-preset-angular
npm ERR!     dev jest-preset-angular@"11.1.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"14.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/compiler-cli@14.0.7
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   peer @angular/compiler-cli@"^14.0.0 || ^14.0.0-rc" from @angular-devkit/build-angular@14.0.0
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"14.0.0" from the root project
```

### Environment

```
   nx : 14.1.9
   @nrwl/angular : 14.1.9
   @nrwl/cypress : 14.1.9
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.9
   @nrwl/eslint-plugin-nx : 14.1.9
   @nrwl/express : 14.4.2
   @nrwl/jest : 14.1.9
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.1.9
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.3.6
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.9
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.9
   typescript : 4.6.4
   ---------------------------------------
   Community plugins:
         @ngrx/component-store: 13.0.2
         @ngrx/effects: 13.0.2
         @ngrx/entity: 13.0.2
         @ngrx/router-store: 13.0.2
         @ngrx/store: 13.0.2
         @ngrx/schematics: 13.0.2
         @ngrx/store-devtools: 13.0.2
```

**Comment by AgentEnder** [comment]
Hey @MirkoDaumann , it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

**Comment by MirkoDaumann** [comment]
Hey, thanks for the reply.

I have manually reduced all the package version to match 14.1.9 (which is also my local version).
After that i tryed to use nx migrate latest. It does not change anything. I still get the same error from above.

**Comment by leosvelperez** [comment]
hey @MirkoDaumann! You're correct, the issue here is the version of `jest-preset-angular`. Unfortunately, we can't just bump it to the version that supports Angular v14 because it also needs support for Jest 28 which is currently in progress. Once https://github.com/nrwl/nx/pull/10857 lands, this issue should be resolved.

In the meantime, you could run `npm i --legacy-peer-deps`.

**Comment by MirkoDaumann** [comment]
Hey, 

so i found the issue i think. 
I had to delete the package.lock.json and delete all my node_modules and change the jest-preset-angular version to 12.2.0
