### ISSUE TITLE
Cannot generate a new workspace within an existing workspace

### ISSUE THREAD

**Issue by Araknos** [nrwl/nx#11275]
Hello,

I'm currently working on some Angular apps that have a lot in common, that's why I want to migrate our apps to Rx (and keep the git history). In the main app I tried the guide https://nx.dev/migration/migration-angular#transitioning-manually which always gives me the following error:

```
✔ Installing dependencies with npm
✖ Creating your workspace

 >  NX   Nx failed to create a workspace.

   Exit code: 1
```

And the error.log:

```
>  NX  Generating @nrwl/workspace/generators.json:new


 >  NX   Cannot generate a new workspace within an existing workspace

   Pass --verbose to see the stacktrace.
```

I tried with the manual migration with resolves... the same error!
This was with Angular 13 so I migrate to Angular 14 just to try again and guess what... same result!

It creates a decorate-angular.cli.js, jest.config.ts, jest.preset.js and nx.json but the architecture is still the same, I don't see the apps folder, the libs folder etc...

At this point I'm lost, what can I do? Is there a way to make it work?

**Comment by AgentEnder** [comment]
You need to create the workspace outside of the current repository and follow the guide from there. That guide doesn't directly go over keeping git history, you'll want to check this one too: https://nx.dev/migration/preserving-git-histories
