### ISSUE TITLE
admin password seems not work right when setup private nx cloud image

### ISSUE THREAD

**Issue by niudai** [nrwl/nx#11271]
## Current Behavior

I setup and run nx cloud image by following https://nx.dev/nx-cloud/private-cloud/get-started, but I found that even though I create the docker image by 

```shell
docker create --name cloud -p 80:8081 -e NX_CLOUD_APP_URL="http://localhost" -e ADMIN_PASSWORD=admin  -e NX_CLOUD_MONGO_SERVER_ENDPOINT="mongodb://mymongo/:27017/nrwl-api"  -v ~/private-cloud:/data nxprivatecloud/nxcloud:latest 
```

which declares the admin password is "admin", but when I visite the nx cloud url, I found that I cannot login by `admin/admin` accout：

![image](https://user-images.githubusercontent.com/44165182/180599322-dd4044a0-287a-480b-b277-3f2b3fde57d9.png)

**Comment by bcabanes** [comment]
Hi @niudai
We just pushed a new image containing the fix, it should be available now on the `latest` and `next` channels 👍

**Comment by niudai** [comment]
Thanks very much! btw I switched to github auth and everything goes well~
