### ISSUE TITLE
Nx Commands Just Stop Working

### ISSUE THREAD

**Issue by StephenMP** [nrwl/nx#11292]
## Current Behavior
Sometimes after installing/uninstalling dependencies using yarn, when running nx commands locally in the project (e.g. via a yarn nx script), they do nothing. For example, a `yarn nx build my-project` results in 
```
▶ yarn nx build my-project
yarn run v1.22.19
$ nx build my-project
✨  Done in 0.45s.
```

However, running nx through a globally installed nx works just fine.

## Expected Behavior
Project scoped nx commands should execute properly.

## Steps to Reproduce
I cannot guarantee that this will reproduce the issue, but this happens randomly when I install new dependencies into my project. I can sometimes reproduce it if I nuke the node_modules and yarn.lock and do a fresh `yarn install`. Again, doesn't always reproduce the issue, but sometimes does.

### Failure Logs
There are no failure logs

### Environment
```
▶ yarn nx report
yarn run v1.22.19
$ nx report
✨  Done in 0.50s.
```

For context, here are the versions we are using:
```json
    "@nrwl/devkit": "12.10.1",
    "@nrwl/eslint-plugin-nx": "^12.10.0",
    "@nrwl/jest": "^12.10.0",
    "@nrwl/linter": "12.10.1",
    "@nrwl/nest": "^12.10.0",
    "@nrwl/node": "^12.10.0",
    "@nrwl/nx": "^7.8.7",
    "@nrwl/workspace": "^12.10.0",
```

**Comment by AgentEnder** [comment]
Hey @StephenMP , it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

**Comment by StephenMP** [comment]
@AgentEnder 

Thanks for the reply. I ran `nx migrate 12.10.0` (using the globally installed nx) and it didn't change my package.json, kept all the versions the same and get the following log

```
>  NX  The migrate command has run successfully.

- package.json has been updated
- there are no migrations to run, so migrations.json has not been created.
```

I ran `nx migrate latest` to upgrade to 14.4.3 to test it out and it updated everything except @nrwl/nx (kept that at ^7.8.7, but that appears to be the latest of that package). Then ran `nx format` to attempt to fix config changes introduced in v13, but that fails. So it's not an easy migration to v14.

I'm not sure what you mean by our versions not matching though? The only ones are patch version difference. So I ran `nx migrate ^12.10.1`, but again, that does nothing and produces the log

```
>  NX  The migrate command has run successfully.

- package.json has been updated
- there are no migrations to run, so migrations.json has not been created.
``

**Comment by AgentEnder** [comment]
The @nrwl/nx package is old, it should be removed.

Patch version differences can certainly cause things to break, the versions of packages inside the nx monorepo are only tested against the same matching version. I'd recommend removing any kind of ~ or ^ from their specifiers, clearing your lock file and reinstalling with matching versions.

**Comment by kommander** [comment]
I just used `npx add-nx-to-monorepo` and have the same issue. Clearing all node_modules and reinstalling, same issue. No nx command works. Neither with global nx, nor with `yarn nx`. Global nx does not even output anyhting.

The only dependency it adds is in the mono root package.json:
```
  "devDependencies": {
    "nx": "14.5.4"
  }
```

It creates an `nx.json` config:
```
{
  "extends": "nx/presets/npm.json",
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": [
          "build"
        ]
      }
    }
  },
  "targetDefaults": {
    "build": {
      "dependsOn": [
        "^build"
      ]
    }
  },
  "affected": {
    "defaultBase": "main"
  }
}
```

What's wrong?

**Comment by vtereshyn** [comment]
I am experiencing the same issue. Why this is closed?

I am using the latest `nx` version. The only thing that helps is `nx reset`.

**Comment by StephenMP** [comment]
@vtereshyn
Not sure if we missed the stale threshold and it auto-closed...

@AgentEnder 
This is still an issue, so the issue should be reopened
