### ISSUE TITLE
Module parse failed: Unexpected token (14:7)

### ISSUE THREAD

**Issue by airowe** [nrwl/nx#11307]
## Current Behavior

Attempting to import react-native-config in a lib shared by a react-native app and a react-js app in a monorepo disallows the web app from being served

## Expected Behavior

Able to share react-native-config library between react-native app and react-js app

Not sure

## Steps to Reproduce

In a library file shared between the two apps in a monorepo, add this file:

`import Config from 'react-native-config';

export function getEnv(key: string) {
  return process.env[key] || Config?.[key];
}`

Attempt to run the web app. See the below error.

I have tried to follow the steps here < [Sharing Native Libraries with Web](https://blog.nrwl.io/introducing-react-native-support-for-nx-48d335e90c89) > to no avail.

### Failure Logs

> ERROR in ../../node_modules/react-native/index.js 14:7
Module parse failed: Unexpected token (14:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| // Components
> import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
| import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
| import typeof Button from './Libraries/Components/Button';

### Environment

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : darwin arm64
   npm  : 8.14.0

   nx : 13.8.3
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.3
   @nrwl/cypress : 13.8.3
   @nrwl/detox : 13.8.3
   @nrwl/devkit : 13.8.3
   @nrwl/eslint-plugin-nx : 13.8.3
   @nrwl/express : undefined
   @nrwl/jest : 13.8.3
   @nrwl/js : 13.8.3
   @nrwl/linter : 13.8.3
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : 13.8.3
   @nrwl/react-native : 13.8.3
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.3
   @nrwl/tao : 13.8.3
   @nrwl/web : 13.8.3
   @nrwl/workspace : 13.8.3
   typescript : 4.4.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

**Comment by airowe** [comment]
Or if anyone knows another way to read environment variables in a shared lib between react-native and react-js in an nx monorepo, I can shift gears to doing it that way instead.

**Comment by xiongemi** [comment]
in your web app, in the file `.babelrc`, you might need to add this line:
```
"plugins": [
    [
      "module-resolver",
      {
        "alias": {
          "^react-native$": "react-native-web"
        }
      }
    ]
  ]
```
so your .babelrc would probably look like:
```
{
  "presets": [
    [
      "@nrwl/react/babel",
      {
        "runtime": "automatic"
      }
    ]
  ],
  "plugins": [
    [
      "module-resolver",
      {
        "alias": {
          "^react-native$": "react-native-web"
        }
      }
    ]
  ]
}

```

**Comment by airowe** [comment]
@xiongemi Thanks for offering to help! Unfortunately, that didn't do the trick. I'm still seeing the same error.

**Comment by IMalaniak** [comment]
I'm also having this problem trying to setup NativeWind for my project, I'm using this guide: https://www.nativewind.dev/guides/postcss
