### ISSUE TITLE
Allow targetDefaults dependsOn to specify a package

### ISSUE THREAD

**Issue by luxaritas** [nrwl/nx#11323]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
I would like running a target to implicitly rely on a different target of a specific package

## Motivation
Example use case: I have an eslint plugin which I consume from the workspace. Running `lint` on any other package should require the plugin to be built

## Suggested Implementation
Allow the targetDefaults dependsOn "package" property to be a package name instead of `self` or `dependencies`

## Alternate Implementations
* (No change to Nx) Setting up an implicit dependency for every other package (though this wouldn't limit it to just the lint target)
* (No change to Nx) Abusing inputs to also include inputs from the other package
* Somehow using the global implicit dependencies to specify the same thing instead of targetDefaults

**Comment by Hakhenaton** [comment]
That would be very useful.

A good use case for this one is when you only need to build some custom executor implementation that is used within the project.

Another alternative would be to allow the user to create dependency "groups".

For example:

```json
{
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/project-1",
  "projectType": "application",
  "targets": {
    "my-target": {
      "executor": "my-executor",
      "options": {},
      "dependsOn": [
        {
          "projects": [
            "project-2", 
            "project-3"
          ],
          "target": "build"
        }
      ]
    }
  }
}
```

**Comment by gund** [comment]
Also a shorthand syntax would be nice:

```json
{
  "dependsOn": ["project-2:build", "project-3:build"]
}
```

**Comment by luxaritas** [comment]
@AgentEnder Should this be linked to #16100? (That PR was linked to itself)

**Comment by AgentEnder** [comment]
Ah, yeah it should have been. Thanks.
