### ISSUE TITLE
yarn 3 (node_modules) - is it supported?

### ISSUE THREAD

**Issue by rbirkgit** [nrwl/nx#11328]
I am wondering if nx supports yarn v3 (with node_modules). I have searched around and cannot find any info from nx team. What does nx support? Only npm or yarn as well? Is there a page somewhere with what is supported?

**Comment by ambeur** [comment]
@rbirkgit I use latest nx with yarn 3 + node_modules, it works pretty fine. Unfortunately, there is no [yarn pnp support](https://github.com/nrwl/nx/issues/2386).

**Comment by AgentEnder** [comment]
I'm going to close this out. Yarn PnP support is tracked in #2386. The node_modules version **_should_** work
