### ISSUE TITLE
Module Federation - AnimationBuilder is not provided globally

### ISSUE THREAD

**Issue by Vevl** [nrwl/nx#11330]
## Current Behavior

I run into a similar issue as was discussed here - [Issue #10054](https://github.com/nrwl/nx/issues/10054) (I tried to comment in order to reopen that issue but it seems that its better to open a new one or?).

In my case, it was 3rd party component which is using AnimationBuilder. 
Before posting I tried different solutions but none seems to help - loading different modules eagerly.

## Expected Behavior
AnimationBuilder should be available across remote applications when it's provided in the host.

## Steps to Reproduce

I created [repo](https://github.com/Vevl/kendo-test) where you can test it on your own,
Just start it and try to open the dropdown panel

### Failure Logs
When both host and remote are using AnimationBuilder, it throws an error even additionalShared: ['@angular/animations'] is added to mf config file.
![image](https://user-images.githubusercontent.com/35180926/181470650-94b4fdd4-ad4f-4bd1-8ec0-0f70c2c21d60.png)
BrowserModule, BrowserAnimationsModule are imported by host app.module.ts only.

### Environment

Node : 16.14.2
   OS   : win32 x64
   npm  : 8.5.0
   
   nx : 14.4.2
   @nrwl/angular : 14.4.2
   @nrwl/cypress : 14.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.2
   @nrwl/eslint-plugin-nx : 14.4.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.2
   @nrwl/js : 14.4.2
   @nrwl/linter : 14.4.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.2
   @nrwl/web : 14.4.2
   @nrwl/workspace : 14.4.2
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
         @progress/kendo-angular-buttons: 8.0.0
         @progress/kendo-angular-common: 3.1.0
         @progress/kendo-angular-dropdowns: 7.0.0
         @progress/kendo-angular-inputs: 9.0.0
         @progress/kendo-angular-intl: 4.0.0
         @progress/kendo-angular-l10n: 4.0.0
         @progress/kendo-angular-popup: 5.0.0
         @progress/kendo-angular-treeview: 7.0.0

**Comment by Vevl** [comment]
OK, so maybe I didn't understand the concept of "additionalShared" libraries here.

If somebody encounters the same issue with sharing not directly provided package, you need to *share* it also from remote that is involved. I also upgraded repo - [Add animation package to remote](https://github.com/Vevl/kendo-test/commit/18f78a3224635d1b75e7b45109ea725d41202595).

Remote module federation config

```
module.exports = {
  name: 'test',
  exposes: {
    './Module': 'apps/test/src/app/remote-entry/entry.module.ts',
  },
  additionalShared: [
    '@angular/animations'
  ]
};
```


Host module federation config
```
module.exports = {
  name: 'host',
  remotes: ['test'],
  additionalShared: [
    '@angular/animations'
  ]
};
```

@AgentEnder do you think this needs to be documented somewhere? Please feel free to close this if you don't think so.

**Comment by Coly010** [comment]
We should make it clearer in the docs. Thanks for raising it!

**Comment by Rav185** [comment]
Did you solve the issue?
