### ISSUE TITLE
git-hasher `parseGitStatus` fails to detect changed files if git config has status colors enabled

### ISSUE THREAD

**Issue by wmhilton** [nrwl/nx#11339]
## Current Behavior

The git-hasher does not parse git output correctly if the user's global `~/.gitconfig` has `[color] status = always`.

## Expected Behavior

`nx` should override that behavior to make sure the `git status` spawned by the git-hasher does not return text with ASCII color codes in it that are not interpreted correctly.

## Steps to Reproduce

Run the following:
```
git config --global color.status always
```

Modify some files in your nx monorepo project
Run an nx build. NX uses cached results because it detected no files were changed! The symptoms are similar to https://github.com/nrwl/nx/issues/5104 but for a different underlying reason. (`parseGitStatus` expects to see an 'M' for modified, but receives a ASCII color coded `\e[32mM\e[0m` garbage.)

## Suggested Fix

I suggest overriding any `color.status` settings when spawning the command on [this line](https://github.com/bekos/nx/blob/master/packages/workspace/src/core/hasher/git-hasher.ts#L26) like:

```js
const output = spawnProcess('git', ['-c', 'color.status=off', 'status', '-s', '-u', '-z', '.'], path);
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
```

or investigate using the [`GIT_CONFIG_NOSYSTEM`](https://git-scm.com/docs/git#Documentation/git.txt-codeGITCONFIGNOSYSTEMcode) environment variable to try to make git cli output more predictable.

### Environment

```
   Node : 16.13.2
   OS   : darwin x64
   yarn : 1.22.5

   nx : 13.10.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.10.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.0
   @nrwl/eslint-plugin-nx : 13.10.0
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.0
   @nrwl/js : 13.10.0
   @nrwl/linter : 13.10.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 13.10.0
   @nrwl/nx-cloud : 13.2.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.10.0
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.0
   @nrwl/web : 13.10.0
   @nrwl/workspace : 13.10.0
   typescript : 4.6.3
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by wmhilton** [comment]
meanwhile i'm just removing that line from my `~/.gitconfig` as a workaround

**Comment by FrozenPandaz** [comment]
Thank you for investigating a fix! Passing `-c, color.status=off,` sounds good to me! Would you like to send a PR? :pray:
