### ISSUE TITLE
Moving `ts` files with `nx workspace-generator` causes transpiled `js` files to be copied as well

### ISSUE THREAD

**Issue by dan-cooke** [nrwl/nx#11332]
## Current Behavior

Following on from the previous issue i raised around generators #11331  - using the example `tsconfig.json` and attempting to move `ts` files into an app- results in `.js` files also being moved.

## Expected Behavior

Only the files defined in my `files` directory should be copied

## Steps to Reproduce

1. Follow steps from #11331 
2. Now add the following `tsconfig.tools.json
```json
{
  "extends": "../tsconfig.base.json",
  "compilerOptions": {
    "outDir": "../dist/out-tsc/tools",
    "rootDir": ".",
    "module": "commonjs",
    "target": "es5",
    "sourceMap": false,
    "esModuleInterop": true,
    "types": ["node"]
  },
  "include": ["**/*.ts"],
}
```
3. Change the `index.ts` in `generators/my-lib` to:
```.ts
import {
  Tree,
  formatFiles,
  installPackagesTask,
  generateFiles,
} from '@nrwl/devkit';
import { moveGenerator } from '@nrwl/workspace/generators';
import path from 'path';

export default async function (tree: Tree, schema: any) {
  const apiTestSuitesDir = './libs/mylib/tests/suites';
  generateFiles(
    tree,
    path.join(__dirname, './files'),
    apiTestSuitesDir,
    schema
  );
  await formatFiles(tree);
  return () => {
    installPackagesTask(tree);
  };
}

```
5. Add the following `files` directory
```
files/
    - __name__
         - index.ts
```

6. Put anything in the `index.ts`
7. Run the generator `nx workspace-generator mylib test`

**Look at the .js files copied to mylib/tests/suites**

### Environment
```
 >  NX   Report complete - copy this into the issue template

   Node : 16.13.0
   OS   : darwin x64
   npm  : 8.1.0

   nx : 14.4.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.4.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.3
   @nrwl/eslint-plugin-nx : 14.4.3
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.3
   @nrwl/js : 14.4.3
   @nrwl/linter : 14.4.3
   @nrwl/nest : 14.4.3
   @nrwl/next : Not Found
   @nrwl/node : 14.4.3
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.4.3
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.3
   @nrwl/web : 14.4.3
   @nrwl/workspace : 14.4.3
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
         @nrwl/remix: 14.4.2
```

**Comment by AgentEnder** [comment]
This is a common issue for generators in general. The recommendation is to use files such as `index.ts__tmpl__`, and pass `"tmpl": ""` in the call to generate files.

Its not really a bug, by the time the generator is running `tsc` has been executed and the .js files exist. I'm going to close this out, let me know if you have more questions.

**Comment by dan-cooke** [comment]
@AgentEnder oh. Well perhaps the docs should be updated then as the examples do not mention this recommendation. And in fact show example output which does not include js files
