### ISSUE TITLE
Running `serve` for one Angular application runs `build` for all the other applications

### ISSUE THREAD

**Issue by theorlovsky** [nrwl/nx#11349]
## Current Behavior

Serving any application causes `Running target build for N project(s)`

## Expected Behavior

Non-dependent projects should not be built on serve command

## Steps to Reproduce

1. `npx create-nx-workspace --name=serve-bug --appName=serve-bug --preset=angular --nxCloud=false --style=scss`
2. `cd serve-bug`
3. `npx nx g @nrwl/angular:app another-app --routing=false`
4. for both projects, in `project.json` change the build executor to `@nrwl/angular:webpack-browser`, serve executor to `@nrwl/angular:webpack-server`, and add `"buildLibsFromSource": false` to `targets.build.options`
5. `npx nx serve serve-bug` or `npx nx serve another-app`

### Environment

```
 >  NX   Report complete - copy this into the issue template

   Node : 16.15.0
   OS   : darwin x64
   npm  : 8.5.5
   
   nx : 14.5.1
   @nrwl/angular : 14.5.1
   @nrwl/cypress : 14.5.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.1
   @nrwl/eslint-plugin-nx : 14.5.1
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.1
   @nrwl/js : 14.5.1
   @nrwl/linter : 14.5.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.1
   @nrwl/web : 14.5.1
   @nrwl/workspace : 14.5.1
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
```

**Comment by cskiwi** [comment]
I also have this issue and in my setup the nx server <client> runs first `nx run <client>:build:development` and in that build it does  `nx run <client>:build:production` so it runs both production and development builds.

**Comment by Coly010** [comment]
I can reproduce this on latest Nx. I'll take a look. 

Thank you for reporting this and for the great reproduction steps! 🙌
