### ISSUE TITLE
@nrwl/next - Suspense not working

### ISSUE THREAD

**Issue by tremppu** [nrwl/nx#11345]
## Current Behavior
With the latest version of nextjs, `dynamic(() => import('../src/text'), {suspense: true,})` suspension is not working correctly when using nx (@nrwl/next). Suspense works when serving the app but building fails. 

## Expected Behavior
With a "vanilla" setup everything is working when building the app so it should work fine with the latest @nrwl/next package as it uses the same versions of next & react.

## Steps to Reproduce
Here is a demo: https://github.com/tremppu/suspense-next-issue-demo

### Failure Logs
Invalid suspense option usage in next/dynamic. Read more: https://nextjs.org/docs/messages/invalid-dynamic-suspense

### Environment
@nrwl/nest : Not Found
@nrwl/next : 14.5.1
@nrwl/node : Not Found
@nrwl/nx-cloud : Not Found
@nrwl/nx-plugin : Not Found
@nrwl/react : 14.5.1
@nrwl/react-native : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : 14.5.1
@nrwl/web : 14.5.1
@nrwl/workspace : 14.5.1
typescript : 4.7.4

### Other info

Issue seem to be that related to [this line](https://github.com/vercel/next.js/blob/0dda1b9f6c0d3fa0894cb790f96980b52aba3002/packages/next/shared/lib/dynamic.tsx#L109) as `!process.env.__NEXT_REACT_ROOT` returns true when using @nrwl/next. I can fix the issue by manually overriding the `__NEXT_REACT_ROOT` to `__NEXT_REACT_ROOT=true` in my .env file.

**Comment by kuus** [comment]
this is still an issue with latest nx and latest next.js

**Comment by colmugx** [comment]
same problem
still with `"@nrwl/next": "15.0.10"` and `"nx": "15.0.3"`
