### ISSUE TITLE
v14.5.0 release notes on Nest v9

### ISSUE THREAD

**Issue by samratarmas** [nrwl/nx#11344]
Hello team,

The [https://github.com/nrwl/nx/releases/tag/14.5.0](url) release note states:

Nest: upgrade nest to v9

With these references: #11120 -> [https://github.com/nrwl/nx/commit/421b4d940e4e342b1ad9be462ce2692de0f3a622](url)

However, 
On this commit: [https://github.com/nrwl/nx/commit/15880d9bd1395f85d69645db9546959eeb753903](url) reverted those upgrades.

As of  nx version 14.5.1 creating a new workspace and generating a nest application brings in dependencies from v8.
This means that either the release notes were not supposed to mention the v9 upgrade, or those reverted commits were not supposed to happen. Hence, it would be very helpful to know whether nx team have plans to bring in nest v9 in current nx version 14 or are waiting for the next major nx update cycle.

Looking forward to hearing from you,
Cheers!

_Originally posted in https://github.com/nrwl/nx/issues/11120#issuecomment-1198874907_

**Comment by AgentEnder** [comment]
I accidentally hit the revert button after merging, but never opened the PR to revert it. It shows in the logs that the commit was added, but it was added to another branch (not master) and never merged. If you check the changes from that PR, then you'll see that they are present. It looks like the versions.ts file in @nrwl/nest wasn't updated by the PR though, so new projects still use v8.

Projects that are already on v8 were likely bumped to v9 during migration, but another PR will be needed for new nest projects to be on v9.
