### ISSUE TITLE
Can't import GLTFExporter.js from Three.JS

### ISSUE THREAD

**Issue by russ0133** [nrwl/nx#11354]
## Current Behavior
Importing "examples/jsm/exporters/GLTFExporter.js" module from Three.JS version 143 results in an error.

## Expected Behavior
It's a simple .js file so I reckon it would have to import normally?

## Steps to Reproduce
Install three.js version 137+ in a NX environment.
Try importing GLTFExporter through:
"import { GLTFExporter } from 'three/examples/jsm/exporters/GLTFExporter.js';"

Then it will give an error.

### Failure Logs
[0] ERROR in /home/gabriel/work/reactapp/node_modules/three/examples/jsm/exporters/GLTFExporter.js 694:35
[0] Module parse failed: Unexpected token (694:35)
[0] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
[0] | 	buildORMTexture( material ) {
[0] | 
[0] > 		const occlusion = material.aoMap?.image;
[0] | 		const roughness = material.roughnessMap?.image;
[0] | 		const metalness = material.metalnessMap?.image;

### Environment
Node : 16.15.1
  OS   : linux x64
  npm  : 8.4.1
  
  nx : 12.10.1
  @nrwl/angular : Not Found
  @nrwl/cli : 12.10.1
  @nrwl/cypress : 12.10.1
  @nrwl/devkit : 12.10.1
  @nrwl/eslint-plugin-nx : 12.10.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.10.1
  @nrwl/linter : 12.10.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.10.1
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.10.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.1
  @nrwl/web : 12.10.1
  @nrwl/workspace : 12.10.1
  @nrwl/storybook : 12.10.1
  @nrwl/gatsby : Not Found
  typescript : 4.5.5

**Comment by AgentEnder** [comment]
@russ0133 Can you try w/o the file extension in the import?

**Comment by russ0133** [comment]
Same behaviour with or without file extension.

I managed to talk with Three.JS guys and their answer was that NX bundler has a problem handing ?. syntax, maybe that's something you guys should look into? @AgentEnder 

Changing Three.JS code from:
`const roughness = material.roughnessMap**?**.image;`

to

`const roughness = material.roughnessMap.image;`

Seems to not give warnings anymore.

**Comment by YingjuHan** [comment]
GLTFExporter.js has a serious problem，It cannot be imported normally.
`Module parse failed: Unexpected token (759:33)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/co
ncepts#loaders
|               console.warn( 'THREE.GLTFExporter: Merged metalnessMap and roughnessMap textures.' );
|
>               const metalness = metalnessMap?.image;
|               const roughness = roughnessMap?.image;`

**Comment by YingjuHan** [comment]
I can use it after processing it with babel-loader, and configure it in webpack.
