### ISSUE TITLE
Nx run-many command does not give intended result for storybook composition

### ISSUE THREAD

**Issue by burakkgunduzz** [nrwl/nx#11353]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

[URL
](https://nx.dev/storybook/storybook-composition-setup)

### Additional context or description

Storybook composition looks for refs in build time. That's because the nx run-many executes commands in parallel, this results with main storybook host cannot reach to other storybooks. If start the ref storybooks manually before and lastly the main host, composition works properly. Documentation should offer another way to do storybook composition properly with nx commands.

**Comment by mandarini** [comment]
:( sorry about that @burakkgunduzz ! I'll look into it!

**Comment by mandarini** [comment]
Hi there @burakkgunduzz !

I just tested this and it seems to work as expected for React + Storybook apps. You can check out [this repo](https://github.com/mandarini/july-nx-workshop/tree/chore/test-compo), the `chore/test-compo`, and run:

```
nx run-many --target=storybook --projects=reapp-one,reapp-two,reapp-three --parallel=3
```

In that case, `reapp-one` is the host and `reapp-two,reapp-three` are the "hosted".

The case where it breaks is the Angular case:

```
nx run-many --target=storybook --projects=store-ui-shared,ui-one,ui-two --parallel=3
```

We are looking into it.

Can you please verify that for you it breaks for Angular apps? And please check out my repo as well, and see if it works for you.

**Comment by burakkgunduzz** [comment]
Hey @mandarini, first of all thank you for your interest. I can confirm that the angular case also breaks for me. 
When I try react composition in chore/test-compo it worked. I'm using the same config and commands as in chore/test-compo but my composition does not work as intended. My host and hosted storybooks opens successfully but my hosted section in host storybook stuck in loading state. When I examine the network tab from dev tools, I see call to http://localhost:4401/stories.json is red (response code is 200 but there is no repsonse data). console says 

> Access to fetch at 'http://localhost:4401/stories.json' from origin 'http://localhost:4400' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
I added 
```config.devServer = {
      headers: [
        {
          key: 'Access-Control-Allow-Origin',
          value: 'http://localhost:4400'
        }
      ]
```
to hosted project(port:4401) but no luck. Interestingly everything works fine if I run manually first the hosted and then host. Any ideas?

Ps: I have also noticed that If I try to run only host storybook first it just hangs in terminal without success or error. Also, it is the case for angular case in chore/test-compo (store-ui-shared).

**Comment by mandarini** [comment]
Hi there @burakkgunduzz ! I removed my original comment, because I verified that you need to have your "composed" instances running first, before starting the host. I updated the docs, you can look at the PR attached to this issue. Thanks for reporting it!!!

**Comment by mandarini** [comment]
Take a look at this [extra section](https://nx.dev/storybook/storybook-composition-setup#optional:-use-and-create-a-target) I just added!

**Comment by burakkgunduzz** [comment]
thank you so much, it works! @mandarini
