### ISSUE TITLE
Provide versioned documentation 

### ISSUE THREAD

**Issue by Richard-Lynch** [nrwl/nx#11352]
It would be great if you could provided versioned documentation, at least for each major version!

### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

n/a

#### Examples of other projects providing versioned docs:

[click](https://click.palletsprojects.com/en/8.1.x/shell-completion/)
[flask](https://flask.palletsprojects.com/en/2.1.x/)

**Comment by isaacplmann** [comment]
We did this at one point, but it was very difficult to maintain.  We have some more time these days though, so I'll bring this up in planning meetings.

**Comment by isaacplmann** [comment]
I still think we should do this, but it isn't on the immediate priority list right now.  Closing this issue since we won't take any action on this for the next two months at least.
