### ISSUE TITLE
"Overwriting" tsconfig when generating a new lib

### ISSUE THREAD

**Issue by danieldanielecki** [nrwl/nx#1136]
## Expected Behavior

Excluding one line of code to **paths** keeping my global **tsconfig.json** untouched after generating a new lib.

## Current Behavior

Whenever I'm creating a new lib, then all my comments & grouping in **tsconfig.json** in are "overwriten", or more precisely all spaces/comments removed e.g. from

```
"compilerOptions": {
    /* Basic options. */
    "declaration": true, // Generates corresponding '.d.ts' file.
    "diagnostics": true, // Show diagnostic information.

    /* Strict type-checking options. */
    "strict": true, // Enable all strict type checking options. Enabling --strict enables: '--alwaysStrict', '--noImplicitAny', '--noImplicitThis', '--strictBindCallApply', '--strictFunctionTypes', '--strictNullChecks', and '--strictPropertyInitialization'.

    /* Additional checks. */
    "noFallthroughCasesInSwitch": true, // Report errors for fallthrough cases in switch statement.
    "noImplicitReturns": true, // Report error when not all code paths in function return a value.
    "noUnusedLocals": true, // Report errors on unused locals.
    "noUnusedParameters": true, // Report errors on unused parameters.

    /* Source map options. */
    "inlineSources": true, // Emit the source alongside the sourcemaps within a single file; requires --inlineSourceMap or --sourceMap to be set.
    "inlineSourceMap":  true, // Emit a single file with source maps instead of having a separate file.

    /* Experimental options. */
    "experimentalDecorators": true, // Enables experimental support for ES decorators.
    "emitDecoratorMetadata": true // Emit design-type metadata for decorated declarations in source.
}
```

After generating a new lib `ng generate lib mylib` it would generate (plus adding the one line of code in paths ofc)

```
"compilerOptions": {
    "declaration": true,
    "diagnostics": true,
    "strict": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "inlineSources": true,
    "inlineSourceMap":  true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
}
```

## Question

The only thing, which is actually changed during in the global **tsconfig.json** is adding to paths 1 new value, but is it really required to merge all my grouped properties, remove all whitespaces, and comments?
Recently putted a bit effort to go through all TypeScript compiler settings, and have quite many notes, which would like to keep with myself what is what in the **tsconfig.json**.

**Comment by FrozenPandaz** [comment]
Yes, this is annoying. As we write a `stringify`'d JSON object for the file. Fixing it isn't trivial though but can be done with some sort of JSON AST parser like what is currently done for typescript.
