### ISSUE TITLE
React native entry file breaking iOS archive command on Xcode 

### ISSUE THREAD

**Issue by davisantos-tag** [nrwl/nx#11376]
Trying to **archive**(`Product->Archive`) a version locally on **Xcode**, the command is **breaking** returning an _entry file_ issue. 

## Current Behavior
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/106993146/181966506-4b50ee7d-7ce7-43b5-b306-62ea59700962.png">

## Expected Behavior
Get the app properly archived from Xcode. 

## Steps to Reproduce

1. Create a fresh react native app using the nrwl boilerplate(`npx create-nx-workspace freshRnNxAppiOS --preset=react-native --appName=mobileiOS`).   
2. Runs the `npx nx run mobilei-os:run-ios` command
3. Open Xcode and select the proper target to archive: 
<img width="422" alt="image" src="https://user-images.githubusercontent.com/106993146/181972958-7604c030-ea1a-4710-9dce-8d37f1a81ddf.png">
4. On Product->Archive execute the command and wait for the reported error. 

### Failure Logs

```
/Users/davi.santos/Documents/fresh-rn-nx-appi-os/apps/mobilei-os/ios/Pods/../.xcode.env: line 12: PROJECT_DIR: command not found
../node_modules/react-native/scripts/xcode/with-environment.sh: line 35: .xcode.env: command not found
../node_modules/react-native/scripts/xcode/with-environment.sh: line 35: node: command not found
[Warning] You need to configure your node path in the  environment.  You can set it up quickly by running:  echo 'export NODE_BINARY=' > .xcode.env  in the ios folder. This is needed by React Native to work correctly.  We fallback to the DEPRECATED behavior of finding . This will be REMOVED in a future version.  You can read more about this here: https://reactnative.dev/docs/environment-setup#optional-configuring-your-environment
Now using node v18.7.0 (npm v8.15.0)
+ DEST=/Users/davi.santos/Library/Developer/Xcode/DerivedData/MobileiOs-amarjsyrkayffpgjcigiiwampfzi/Build/Intermediates.noindex/ArchiveIntermediates/MobileiOs/BuildProductsPath/Release-iphoneos/MobileiOs.app
+ [[ Release = *Debug* ]]
+ [[ -n '' ]]
+ case "$CONFIGURATION" in
+ DEV=false
+++ dirname ../node_modules/react-native/scripts/react-native-xcode.sh
++ cd ../node_modules/react-native/scripts/..
++ pwd
+ REACT_NATIVE_DIR=/Users/davi.santos/Documents/fresh-rn-nx-appi-os/apps/mobilei-os/node_modules/react-native
+ PROJECT_ROOT=/Users/davi.santos/Documents/fresh-rn-nx-appi-os/apps/mobilei-os/node_modules/react-native/../..
+ cd /Users/davi.santos/Documents/fresh-rn-nx-appi-os/apps/mobilei-os/node_modules/react-native/../..
+ [[ -n /../src/main.tsx ]]
+ :
+ [[ false != true ]]
+ [[ ! -f /../src/main.tsx ]]
+ echo 'error: Entry file /../src/main.tsx does not exist. If you use another file as your entry point, pass ENTRY_FILE=myindex.js'
error: Entry file /../src/main.tsx does not exist. If you use another file as your entry point, pass ENTRY_FILE=myindex.js
+ exit 2
```

### Environment
<img width="459" alt="image" src="https://user-images.githubusercontent.com/106993146/181986239-4723250c-58b6-4022-a6b8-bc48f57c41cd.png">

**Comment by carlos-kelly** [comment]
Hi :wave: We were able to archive an iOS Release build by adding

```sh
export ENTRY_FILE="${PROJECT_DIR}/../src/main.tsx"
```

where `main.tsx` was our entry file, we're using TypeScript, after the `set -e` command in the Bundle React Native code and images build phase in Xcode.

**Comment by davisantos-tag** [comment]
Hi @carlos-kelly :) 

You mean, like this? 
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/106993146/182391812-960dab75-ba04-476c-adef-f39475dff017.png">

Thank you!

**Comment by mucahit-tekin** [comment]
@davisantos-tag  No you can just replace 

`export ENTRY_FILE=$(PROJECT_DIR)/../src/main.tsx` with `export ENTRY_FILE="${PROJECT_DIR}/../src/main.tsx"` in ios/.xcode.env file.

**Comment by GirugaCode** [comment]
> @davisantos-tag No you can just replace
> 
> `export ENTRY_FILE=$(PROJECT_DIR)/../src/main.tsx` with `export ENTRY_FILE="${PROJECT_DIR}/../src/main.tsx"` in ios/.xcode.env file.

Thank you! This helped me resolve the same issue.

**Comment by richardwalters** [comment]
Hi @xiongemi. The fix for this was incorrect and we still see the error `Entry file /../src/main.tsx does not exist`. You updated
`export ENTRY_FILE=$(PROJECT_DIR)/../src/main.tsx`
to
`export ENTRY_FILE="$(PROJECT_DIR)/../src/main.tsx"`
but should it have been
`export ENTRY_FILE="${PROJECT_DIR}/../src/main.tsx"`
i.e. curly brackets instead of round brackets?
