### ISSUE TITLE
Guidance/support for using `baseUrl` and `paths`

### ISSUE THREAD

**Issue by dan-cooke** [nrwl/nx#11374]
This is a long one so bare with me
## Current Behavior

Lots of users set `baseUrl` or `paths` for their applications. Unfortuately this does not play with how `nx` detects your dependency graph.

### Reproduction
I have come here after encountering the following issue https://github.com/nrwl/nx/issues/6840 - but it turns out this issue is part of a underlying problem.

1. `npx create-nx-workspace --preset=nest`
2. ` nx g @nrwl/nest:lib env`
3. `npm i dotenv`
4. Add the following to `libs/env/src/index.ts`
```.ts
import { config } from 'dotenv';

export const test = () => config();

```

5. Add the following line to the nest application
```.ts
import { test } from '@nx-bug-generate-package/env'

test();
```

6. Add `generatePackageJson` to the webpack options
7.  Go to `node_modules/@nrwl/workspaces/src/utilities/createPackageJson.js` and add a `console.log`

```.js
function createPackageJson(projectName, graph, options) {
    const npmDeps = findAllNpmDeps(projectName, graph);
  // Add this line here for demo purposes
    console.log(devkit_1.readCachedProjectGraph().dependencies)
```

9. Run `nx build api`

You should see the following output:
<img width="876" alt="image" src="https://user-images.githubusercontent.com/22816887/181919251-0e460036-3c08-44ea-a6bf-6a9b8c3397e0.png">

Great - you can see `nx` has detected that `env `is a dependency of `api` with the followig line
` { source: 'api', target: 'env', type: 'static' } `

## Now lets break it
1. Go into the `nest` app and add a `baseUrl` to the tsconfig.json
```
"baseUrl": ".",
```
2. Run `nx build api`

## First issue
This is more of a Typescript issue, but its fundamental to how `nx` links packages together. The import you previously had :

```.ts
import { test } from '@nx-bug-generate-package/env'
```

Will not be resolved by Typescript.

### Why?
Well because `baseUrl` and `paths` are meant to be used together really, so when building the API we have changed the baseUrl to `apps/api/tsconfig.json` - but the `tsconfig.base.json` defines the lib path as follows:

```.json
 "paths": {
      "@nx-bug-generate-package/env": ["libs/env/src/index.ts"]
    }
```
So the path `libs/env/src/index.ts` does not make sense with a base url of `apps/api/` it only makes sense with a `baseUrl` set to the root of the monorepo.

## Second issue
Okay now lets hack this - to get Typescript to resolve our packages properly.

1. Change the `tsconfig.base.json` path to the follwing
```.json
 "@nx-bug-generate-package/env": ["../../libs/env/src/index.ts"]
```

This allows typescript to resolve our package , but it will break the `nx` depdency resolution (of course)

2. `nx build api`

And this time you will not see ` { source: 'api', target: 'env', type: 'static' } ` in the dependency graph.

# Workaround
So you can actually modify all your `tsconfig.base.json` paths to include both the `"../../lib` and "lib/"` path to keep both Typescript and NX happy - but I just feel very hacky doig this.

Is there any advice on how we should be using `baseUrl` and `paths` - if we should be at all?

###  Environment
```
  OS   : darwin x64
   npm  : 8.1.0

   nx : 14.4.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.4.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.3
   @nrwl/eslint-plugin-nx : 14.4.3
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.3
   @nrwl/js : 14.4.3
   @nrwl/linter : 14.4.3
   @nrwl/nest : 14.4.3
   @nrwl/next : Not Found
   @nrwl/node : 14.4.3
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.4.3
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.3
   @nrwl/web : 14.4.3
   @nrwl/workspace : 14.4.3
   typescript : 4.7.4
   ---------------------------------------

```

**Comment by AgentEnder** [comment]
`baseUrl` should not generally be set at the project level. Similar story with `paths`. If you set either of these, you'll need to set the paths in the project-level tsconfig for any libraries you want to use.

**Comment by dan-cooke** [comment]
Just for clarification. Is project level the root of the Nx monorepo ? Or the root of the individual apps/library?

**Comment by AgentEnder** [comment]
project level would be the root of the individual projects, we generally refer to the root of the monorepo as the workspace root

**Comment by dan-cooke** [comment]
Right yeah, in this example I have set the baseUrl in the project level.

but the issue with this is that you then need to duplicate all the paths from the workspace root.
