### ISSUE TITLE
nx:run-commands forwards executor options when assigned via overrides

### ISSUE THREAD

**Issue by Phault** [nrwl/nx#11382]
## Current Behavior

If you have an `nx:run-commands` executor configured to use `forwardAllArgs` and you invoke it either from CLI or with `runExecutor()` with an override for one of the executor's own options e.g. `cwd`, `color` or `outputPath`, it will forward the option to the command as well. 

For example with this executor:
```jsonc
// apps/my-app/project.json
{
  "targets": {
    "my-command": {
      "executor": "nx:run-commands",
      "options": {
        "command": "echo hello world",
        "cwd": "apps/my-app"
      }
    }
  }
}
```  

Running `nx run my-app:my-command --cwd apps/my-other-app` will execute `echo hello world --cwd apps/my-other-app` in `apps/my-other-app`, and hence output:
```
hello world --cwd apps/my-other-app
```

This happens because `nx:run-commands` just appends whatever its `options.__unparsed__` contains, regardless of whether it contains a parameter that it owns itself such as "color", "command", etc.

## Expected Behavior

The known executor options should be consumed by the executor and not forwarded. 

After https://github.com/nrwl/nx/commit/da1faaf483668227b9a7e8706426c93846c5ef4a `runExecutor()` now has the same issue, which has caused some trouble: https://github.com/jscutlery/semver/issues/554 https://github.com/nrwl/nx/issues/10787#issuecomment-1194765051

### Environment

```
    Node : 16.16.0
   OS   : darwin x64
   pnpm : 7.1.0

   nx : 14.3.6
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.3.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : 14.3.6
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.6
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.3.6
   @nrwl/nest : Not Found
   @nrwl/next : 14.3.6
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : 14.3.6
   @nrwl/react : 14.3.6
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.3.6
   @nrwl/web : 14.3.6
   @nrwl/workspace : 14.3.6
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
   	 @jscutlery/semver: 2.25.2
   	 ngx-deploy-npm: 4.1.2
```

**Comment by AgentEnder** [comment]
Hey @Phault, it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

**Comment by Phault** [comment]
Hi @AgentEnder,
Ahh you're right, nx-plugins was too new. I've downgraded it to 14.3.6, as I cannot update due to a different bug. I unfortunately still experience the same issue.

**Comment by ndrsg** [comment]
Hello! 

I can confirm this issue still exists in 14.5.10, so I suggested a bugfix in my PR #11734 .

Another workaround is to rewrite the run-commands options, with "forwardAllArgs: false" or appending " # " to the commands (when using sh/bash)

Env:
```
   nx : 14.5.10
   @nrwl/angular : 14.5.10
   @nrwl/cypress : 14.5.10
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.10
   @nrwl/eslint-plugin-nx : 14.5.10
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.10
   @nrwl/js : 14.5.10
   @nrwl/linter : 14.5.10
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.5.10
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.10
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.10
   @nrwl/web : 14.5.10
   @nrwl/workspace : 14.5.10
   typescript : 4.7.2
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @jscutlery/semver: 2.26.0
```

**Comment by Phault** [comment]
@FrozenPandaz please reopen this if possible, since the fix was reverted.
