### ISSUE TITLE
Building an application within the CI pipeline of Railway fails every other time due to the Nx daemon

### ISSUE THREAD

**Issue by ChristianIvicevic** [nrwl/nx#11395]
## Current Behavior

I was attempting to deploy a fresh Nest.js application from within my monorepo to Railway but exactly every other build results in a SIGTERM (Docker error 143) failing the entire process.

After a lot of trial an error I was consistently able to build the application successful while having the `NIXPACKS_NO_CACHE` environment variable enabled, indicating the cache (within `node_modules`?) from an earlier run of the pipeline is either corrupt or causing the next run to fail due to inexcplicable reasons.

Eventually I dropped said environment variable and set `NX_DAEMON=false` and have been successfully deploying ever since, indicating that the daemon is seemingly running in an CI environment and crashing or going OOM when running within a directory that has a restored cache from a previous run.

## Expected Behavior

I expect the build to work correctly.

## Steps to Reproduce

Repro Repo is here: https://github.com/ChristianIvicevic/nx-daemon-sigterm-repro
It's a fresh nx workspace with a single Nest.js application.
Try to deploy on Railway using the following variables:
```dotenv
NIXPACKS_BUILD_CMD=npx nx build api --prod
NIXPACKS_START_CMD=node dist/apps/api/main.js
NODE_OPTIONS=--max-old-space-size=4096
```
The first deployment should normally succeed. After that has been confirmed, punch the cache by editing any file. Most suitable is the hardcoded string in `apps/api/src/app/app.service.ts` then try to deploy again and you will have the aforementioned error that occurs unless `NX_DAEMON=false`.

### Failure Logs

Unfortunately there are no verbose logs during the build and there is no information to be found.
```
#11 [stage-0 7/8] RUN --mount=type=cache,id=s/17a25dbf-8ad1-4ae6-9c5c-c6d7a8b06129-node_modules/cache,target=node_modules/.cache npx nx build api --prod
#11 sha256:facf798fe73bcb4ff1cc5fab5b85d4f0f7ed04c0fe73792d6c598234cf6e3990
 
#11 1.466 Terminated
 
#11 ERROR: executor failed running [/bin/bash -ol pipefail -c npx nx build api --prod]: exit code: 143
```

### Environment

```
#11 2.574    Node : 16.15.0
#11 2.574    OS   : linux x64
#11 2.574    npm  : 8.5.5
#11 2.574
#11 2.574    nx : 14.5.1
#11 2.574    @nrwl/angular : Not Found
#11 2.574    @nrwl/cypress : Not Found
#11 2.574    @nrwl/detox : Not Found
#11 2.574    @nrwl/devkit : 14.5.1
#11 2.574    @nrwl/eslint-plugin-nx : 14.5.1
#11 2.574    @nrwl/express : Not Found
#11 2.574    @nrwl/jest : 14.5.1
#11 2.574    @nrwl/js : 14.5.1
#11 2.574    @nrwl/linter : 14.5.1
#11 2.574    @nrwl/nest : 14.5.1
#11 2.574    @nrwl/next : Not Found
#11 2.574    @nrwl/node : 14.5.1
#11 2.574    @nrwl/nx-cloud : Not Found
#11 2.575    @nrwl/nx-plugin : Not Found
#11 2.575    @nrwl/react : Not Found
#11 2.575    @nrwl/react-native : Not Found
#11 2.575    @nrwl/schematics : Not Found
#11 2.575    @nrwl/storybook : Not Found
#11 2.575    @nrwl/web : Not Found
#11 2.575    @nrwl/workspace : 14.5.1
#11 2.575    typescript : 4.7.4
```

**Comment by AgentEnder** [comment]
The daemon should generally be disabled on CI. We do this for many providers, but some may be missing. If this does flag up for you, setting the daemon to false should work but I'd recommend setting `CI=true` instead so that other pieces of Nx recognize it as a CI environment.
