### ISSUE TITLE
File doesn't exist

### ISSUE THREAD

**Issue by MadeStoel** [nrwl/nx#11392]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?
https://nx.dev/angular-tutorial/02-add-e2e-test

### Additional context or description

The documentation specifies the editing of app.spec.ts:

'Next, update apps/todos-e2e/src/integration/app.spec.ts.'

This file, however, does not exist. There is an todos-e2e/src/e2e/app.cy.ts file available though. Nx version used for generating the Angular app: 14.5.1

**Comment by barbados-clemens** [comment]
Thanks for bringing this up @MadeStoel, we released support for cypress 10 a couple of days ago which changed the name of files, but yes app.cy.ts is the correct file to work with in that case.

**Comment by MadeStoel** [comment]
@barbados-clemens Thank you for the fast reply and action!
