### ISSUE TITLE
issue with last detox edit - expo app setup

### ISSUE THREAD

**Issue by LeandreArnaud** [nrwl/nx#11390]
## Current Behavior
Hi guys, I just tried to set up an nx project with an expo app and I had some issues with the recent modification of:
`packages/detox/src/generators/application/files/app/.detoxrc.json.template`
(PR: #11104)

## Expected Behavior
It seems to be fixed for me by manually removing the modifications made by this last PR on this file above (only the lines with <% ... %> ).

## Steps to Reproduce
follow this tutorial:
https://blog.nrwl.io/introducing-expo-support-for-nx-3fffb1849a6f

### Failure Logs
`
Error in node_modules/@nrwl/detox/src/generators/application/files/app/.detoxrc.json.template
line 15...
framework is not defined
Pass --verbose to see the stacktrace.
`

**Comment by xiongemi** [comment]
this should be fixed https://github.com/nrwl/nx-labs/pull/93 for @nrwl/expo version 14.5.0.
