### ISSUE TITLE
NX Migrate latest to 14.5.x (0, 1, 2) from 14.4.3 fails on npm install

### ISSUE THREAD

**Issue by Chowarmaan** [nrwl/nx#11404]
I have tried running the migration step from my current repository which is running nx 14.4.3.  Trying to migrate to the latest (14.5.2), or 14.5.1 or 14.5.0 changes the package.json file.  However, trying to run the `npm install` gives a dependency error. Deleting the contents of the node_modules does not help either.

## Current Behavior

	$ npm install
	npm ERR! code ERESOLVE
	npm ERR! ERESOLVE could not resolve
	npm ERR!
	npm ERR! While resolving: workspace@0.3.0
	npm ERR! Found: @angular-devkit/build-angular@14.0.7
	npm ERR! node_modules/@angular-devkit/build-angular
	npm ERR!   dev @angular-devkit/build-angular@"14.1.0" from the root project
	npm ERR!   peer @angular-devkit/build-angular@">=0.1002.4" from jest-preset-angular@11.1.2
	npm ERR!   node_modules/jest-preset-angular
	npm ERR!     dev jest-preset-angular@"~11.1.2" from the root project
	npm ERR!
	npm ERR! Could not resolve dependency:
	npm ERR! dev @angular-devkit/build-angular@"14.1.0" from the root project
	npm ERR!
	npm ERR! Conflicting peer dependency: @angular/compiler@14.1.0
	npm ERR! node_modules/@angular/compiler
	npm ERR!   peer @angular/compiler@"14.1.0" from @angular/compiler-cli@14.1.0
	npm ERR!   node_modules/@angular/compiler-cli
	npm ERR!     dev @angular/compiler-cli@"14.1.0" from the root project
	npm ERR!     peer @angular/compiler-cli@"^14.0.0" from @angular-devkit/build-angular@14.1.0
	npm ERR!     node_modules/@angular-devkit/build-angular
	npm ERR!       dev @angular-devkit/build-angular@"14.1.0" from the root project
	npm ERR!     2 more (@angular/localize, ng-packagr)
	npm ERR!
	npm ERR! Fix the upstream dependency conflict, or retry
	npm ERR! this command with --force, or --legacy-peer-deps
	npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

## Expected Behavior

I would have expected npm install to complete the install of the packages so that the next step of running the `nx migrate --run-migrations` would then work.

## Steps to Reproduce

Install the packages for 14.4.3, and then try the migration.  I have attached the package.json file diff between my version and the 14.5.0 version.

### Environment

 NX   Report complete - copy this into the issue template
   Node : 18.5.0
   OS   : win32 x64
   npm  : 8.12.1

   nx : 14.4.3
   @nrwl/angular : 14.4.3
   @nrwl/cypress : 14.4.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.3
   @nrwl/eslint-plugin-nx : 14.4.3
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.3
   @nrwl/js : 14.4.3
   @nrwl/linter : 14.4.3
   @nrwl/nest : 14.4.3
   @nrwl/next : Not Found
   @nrwl/node : 14.4.3
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.3
   @nrwl/web : 14.4.3
   @nrwl/workspace : 14.4.3
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
         @jscutlery/semver: 2.25.2

**Comment by Chowarmaan** [comment]
Diff of Package.json 14.4.3 and 14.5.0.
[package.json.txt](https://github.com/nrwl/nx/files/9243480/package.json.txt)

npm debug log
[2022-08-02T14_46_17_479Z-debug-0.log](https://github.com/nrwl/nx/files/9243487/2022-08-02T14_46_17_479Z-debug-0.log)

[eresolve-report.txt](https://github.com/nrwl/nx/files/9243488/eresolve-report.txt)

**Comment by Chowarmaan** [comment]
Running a `npm install --force` will install packages as indicated.  Attempting to re-run the `npm install` still fails with the errors.  However, running ` nx migrate --run-migrations --create-commits` after, does complete without error.

NX  Successfully finished running migrations from 'migrations.json'. This workspace is up to date!
$ nx --version
14.5.2

**Comment by AgentEnder** [comment]
This may be fixed in latest, I'm going to close this out pending future reports as we've updated the packages in question recently
