### ISSUE TITLE
Migration command does not work

### ISSUE THREAD

**Issue by SantyTaco** [nrwl/nx#11406]
## Current Behavior

I run the command yarn nx migrate latest to update my current version of nx 12.5.8 to the latest one because I need the last feature of typescript. After to run the command I did not get any update in my package.json 

## Expected Behavior

I was expected to update the package.json and the nx version

## Steps to Reproduce
1. Run  nx migrate latest
2. I received this log:
√ We noticed you are migrating to a new major version, but are not taking advantage of Nx Cloud. Nx Cloud can make your CI up to 10 times faster. Learn more about it here: nx.app. Would you like to add it? · No

Fetching meta data about packages.
It may take a few minutes.
Fetching nx@14.5.2
Fetching nx@latest

>  NX  The migrate command has run successfully.

- package.json has been updated
- there are no migrations to run, so migrations.json has not been created.

>  NX  Next steps:

- Make sure package.json changes make sense and then run 'npm install'  
- To learn more go to https://nx.dev/using-nx/updating-nx
- You may run 'npm run nx -- connect-to-nx-cloud' to get faster builds, GitHub integration, and more. Check out https://nx.app

3. I reviewed the current version of nx and  it was not updated.
npx nx --version  
12.5.8

**Comment by Lonli-Lokli** [comment]
Same for me with 13 -> 14 migrate

```
   Node : 14.18.1
   OS   : win32 x64
   npm  : 6.14.15

   nx : undefined
   @nrwl/angular : undefined
   @nrwl/cli : 13.7.3
   @nrwl/cypress : 13.7.3
   @nrwl/detox : undefined
   @nrwl/devkit : 13.7.3
   @nrwl/eslint-plugin-nx : 13.7.3
   @nrwl/express : 13.7.3
   @nrwl/jest : 13.7.3
   @nrwl/js : 13.7.3
   @nrwl/linter : 13.7.3
   @nrwl/nest : 13.8.0
   @nrwl/next : undefined
   @nrwl/node : 13.7.3
   @nrwl/nx-cloud : undefined
   @nrwl/react : 13.7.3
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.7.3
   @nrwl/tao : 13.7.3
   @nrwl/web : 13.7.3
   @nrwl/workspace : 13.7.3
   typescript : 4.5.2
   rxjs : 7.5.6
   ---------------------------------------
   Community plugins:
```

**Comment by Lonli-Lokli** [comment]
For those who interested, you should
`npm uninstall -D @nrwl/cli` then `npm install -D nx@13` then` npm run update`. That should let you update packages
https://github.com/nrwl/nx/issues/10218#issuecomment-1123597909
