### ISSUE TITLE
@nrwl/web 14.5.1 error

### ISSUE THREAD

**Issue by liosixer** [nrwl/nx#11400]
when ci create-nx-workspace --preset=react, it happens
## Current Behavior

--- error.log

```
The latest release of @nrwl/web is "14.5.0".

Other releases are:
  * next: 14.5.0-rc.0
  * previous: 13.10.6

If you need the full list of all 797 published versions run "$ pnpm view @nrwl/web versions".

 >  NX   Command failed: pnpm install --no-frozen-lockfile

   Pass --verbose to see the stacktrace.
```

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by AgentEnder** [comment]
You can see the release is present on npm here: https://www.npmjs.com/package/@nrwl/web

This is either a transient issue or something with a custom registry setup, try again and if its still not working I'd recommend checking your package registry settings.
