### ISSUE TITLE
Errors when try to serve Angular MFE apps

### ISSUE THREAD

**Issue by dkhrunov** [nrwl/nx#11414]
After updating my monorepo from v13 to Nx v14.5.1 and Angular v14.1.0, I had these errors in the console when trying to run the serve command for an MFE app. But after some waiting, my app started successfully.
What the problem is?
<img width="855" alt="image" src="https://user-images.githubusercontent.com/25565058/182479258-0c7fd1bf-0e31-412b-a71f-a2c670e84ee7.png">

And I had errors at the beginning of the serve command (as in this [issue](https://github.com/nrwl/nx/issues/11138)):
```
Project extension with invalid name ($schema) found.
Project extension with invalid name (tags) found.
Project extension with invalid name (configFilePath) found.
```

**Comment by dkhrunov** [comment]
08.05.2022 UPD: 
I noticed that when I run nx serve for a single MFE application, it starts production builds for all applications in my monorepo
<img width="525" alt="image" src="https://user-images.githubusercontent.com/25565058/183036893-86a98950-ea2e-400e-8340-cf5b1e60fd6c.png">

**Comment by Coly010** [comment]
The second issue has a fix merged and released in Nx 14.5.3.

If you migrate to latest using `nx migrate latest` you should get it.

As for the first issue, could you share a repo? Or some kind of reproduction?

If you used `nx migrate` to upgrade your workspace, it could be that a migration went awry.

**Comment by dkhrunov** [comment]
> The second issue has a fix merged and released in Nx 14.5.3.
> 
> If you migrate to latest using `nx migrate latest` you should get it.
> 
> As for the first issue, could you share a repo? Or some kind of reproduction?
> 
> If you used `nx migrate` to upgrade your workspace, it could be that a migration went awry.

Yes, [here](https://github.com/dkhrunov/fullstack-angular-mfe/tree/update-to-angular-v14) you can find my project after migration

**Comment by dkhrunov** [comment]
@Coly010 One clarification, during the migration I encountered a problem, my `tsconfig.base.ts` file did not allow me to migrate, then I used the workaround described [here](https://github.com/nrwl/nx/issues/11138#issuecomment-1198934086).

**Comment by dkhrunov** [comment]
After updating to nx v14.5.4 I get this errors when try to start any MFE app.
![image](https://user-images.githubusercontent.com/25565058/183223643-f320c4ef-08c3-4291-9b03-ea6b773e9d27.png)

But when I removed the folders: /dist, /node_modules and /tmp;
Run yarn / npm install;
Try running the MFE application and everything will start as expected.

What was the problem I did not understand.

Thanks!

**Comment by Coly010** [comment]
I believe it may have been down to an incorrect package resolution. As there is a workaround and you've got past your issue, I'll close this.

Thanks for reporting!
