### ISSUE TITLE
Server Error - CustomDocument.getInitialProps() - Preset Next + styled-components 

### ISSUE THREAD

**Issue by rdsmartins** [nrwl/nx#11411]
## Current Behavior
Right after workspace creation, accessing the default url , an error is being shown by accessing the initial page: 
"Server Error
Error: "CustomDocument.getInitialProps()" should resolve to an object with a "html" prop set with a valid html string..."

## Expected Behavior
Just to show the initial page.

## Steps to Reproduce
npx create-nx-workspace@latest --preset=next
and select styled-components as Default stylesheet format.

### Failure Logs
<img width="996" alt="image" src="https://user-images.githubusercontent.com/8462801/182464111-c87447a2-f14b-4c68-801d-ba8661c9d1f7.png">

### Environment
>  NX   Report complete - copy this into the issue template

   Node : 12.22.9
   OS   : darwin x64
   npm  : 8.13.2

   nx : 14.5.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.2
   @nrwl/eslint-plugin-nx : 14.5.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.2
   @nrwl/js : 14.5.2
   @nrwl/linter : 14.5.2
   @nrwl/nest : Not Found
   @nrwl/next : 14.5.2
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.2
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.2
   @nrwl/web : 14.5.2
   @nrwl/workspace : 14.5.2
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:

**Comment by jaysoo** [comment]
Fixed here https://github.com/nrwl/nx/pull/11362

**Comment by ndcunningham** [comment]
This should be fixed with: https://github.com/nrwl/nx/pull/11362
