### ISSUE TITLE
Smarter tsconfig.lib.json for Angular/TypeScript compiler options

### ISSUE THREAD

**Issue by danieldanielecki** [nrwl/nx#1142]
## Expected Behavior

In **tsconfig.json** files, which inherits from global **tsconfig.json** file, avoid to repeat the same **compilerOptions**/**angularCompilerOptions** rules. Many of them are already defined in a global **tsconfig.json** for TypeScript, whilst for Angular it could be defined there as well.

## Current Behavior

For every lib generation I'm getting a local **tsconfig.lib.json** file with exactly the same compilers settings for TypeScript (**compilerOptions**) - some of them repeats from global, and for Angular (**angularCompilerOptions**) - it could be defined once, in a global **tsconfig.json**.

## Question

Is it due to the reason that for apps **tsconfig.app.json** file is different than that one for libs? Especially in case of **angularCompilerOptions** for which **tsconfig.app.json** doesn't contain anything.

**Comment by FrozenPandaz** [comment]
Yes, it is because `tsconfig.app.json` does not need these options. In your own repo, you can do the following:

1. Create a `tsconfig.lib.json` which extends `tsconfig.json` at the root
2. Extend the root `tsconfig.lib.json` in each project.

In my opinion, given that it is generated for you.. maybe just leave it though as that is less work.

**Comment by danieldanielecki** [comment]
@FrozenPandaz did that way and it worked out really good. Well, if you want for example more stricted rules for Angular's compiler then using the default's Nx I had to write the rules line in every single lib. Now, I got everything from 1 file, it helps to follow the [DRY ](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle. Would be great to see it at some point in Nx.
