### ISSUE TITLE
Upgrading to 14.5.1 breaks all tests that reference a lib

### ISSUE THREAD

**Issue by 72gm** [nrwl/nx#11420]
## Current Behavior
When I run my app tests any tests that reference a library fail as the 'module cannot be found'

## Expected Behavior
I expect my tests to be able to find the referenced libs
This worked in 14.0.5

## Steps to Reproduce
Using 14.5.1 run nx run mpApp:test where myApp has tests that reference a library

When I revert back to 14.0.5 all tests pass again

No, the 2 apps in the examples repo don't reference any Libs in the tests

### Environment
* I've reverted back to previous version but you can replace 14.0.5 with 14.5.1
* 
Node : 14.18.1
   OS   : win32 x64
   yarn : 1.22.17

   nx : 14.0.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.0.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.0.5
   @nrwl/eslint-plugin-nx : 14.0.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.5
   @nrwl/js : 14.0.5
   @nrwl/linter : 14.0.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.0.5
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.0.5
   @nrwl/web : 14.0.5
   @nrwl/workspace : 14.0.5
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

**Comment by barbados-clemens** [comment]
@72gm can you share you root jest.preset.js?

it sounds like the nx preset isn't been applied correctly. 
the jest preset should look something like this. 
```js
const nxPreset = require('@nrwl/jest/preset').default;
module.exports = {
  ...nxPreset,
};
```
