### ISSUE TITLE
dynamic-module-federation-with-angular host app doesn't working with nx serve, throw error "Invalid dynamic remote configured in ..."

### ISSUE THREAD

**Issue by CP-Ram** [nrwl/nx#11448]
## Current Behavior
dynamic-module-federation-with-angular host app doesn't working with nx serve

## Expected Behavior
dynamic-module-federation-with-angular host app should work with nx serve

## Steps to Reproduce
1.Creates an dynamic-module-federation-with-angular host application
2.Creates an dynamic-module-federation-with-angular remote application
3.Add remote app entry module required detail in host ```module-federation.manifest.json```
   
  ```
 {
    "dremotemfe1": "http://localhost:4201"
     }
```
     
     
4.serve remote app.
5.serve host app with ```npx nx serve```
 it will throw error ``` NX   Invalid dynamic remote configured in```
  
### Failure Logs
```
Error: Invalid dynamic remote configured in "C:\Users\dev\source\repos\nx\separate-repo\dynamic-mf\host\hostdmf\apps\dhostux\src\assets\module-federation.manifest.json": dremotemfe1.
    at getDynamicRemotes (C:\Users\dev\source\repos\nx\separate-repo\dynamic-mf\host\hostdmf\node_modules\@nrwl\angular\src\builders\module-federation-dev-server\module-federation-dev-server.impl.js:35:15)
    at executeModuleFederationDevServerBuilder (C:\Users\dev\source\repos\nx\separate-repo\dynamic-mf\host\hostdmf\node_modules\@nrwl\angular\src\builders\module-federation-dev-server\module-federation-dev-server.impl.js:77:28) 
    at onInput 
```

### Environment
module-federation-dev-server

**Comment by ngacho** [comment]
Are you naming your remotes consistently within the repo? I've had this issue and it's been a naming issue throughout.

**Comment by CP-Ram** [comment]
quite not understood your question. could you please provide more context?
i have two repo app. one for host app and another one for remote app.
if you are asking about remote name in host application ..tried like given below but still getting same issue.
module-federation.manifest.json
```
{
    "dremotemfe1": "http://localhost:4201"
}
```
as well module-federation.config.js
```
module.exports = {
  name: 'dhostux',
  remotes: ['dremotemfe1'],
};
```

**Comment by CP-Ram** [comment]
Host and Remote need to be in the same workspace to use nx module-federation-dev-server builder.
current workaround solution @angular-architects/module-federation plugin
so closing the issue.
