### ISSUE TITLE
Migrating leads to wrong @storybook/addon-postcss

### ISSUE THREAD

**Issue by stasnegreev** [nrwl/nx#11465]
## Current Behavior
Migrating to nx latest version bumps @storybook/addon-postcss to ~6.5.9 which does not exist. The latest package version available is still 2.0.0.

## Expected Behavior
Migrate to the latest version and check the package.json.

## Steps to Reproduce
Migrate to the latest from the 13.10.6 version and check the package.json.
steps:
run nx migrate 
run npm i
run nx migrate --run-migrations

### Environment
Node : v16.16.0
OS : win32 x64
npm: 8.11.0

**Comment by mandarini** [comment]
Thank you for filing this bug @stasnegreev !
