### ISSUE TITLE
Allow Windows users to contribute to the project without WSL

### ISSUE THREAD

**Issue by markgoho** [nrwl/nx#1146]
`To build Nx on Windows, you need to use WSL`

I'm not sure why this is, but it's extremely frustrating to be a Windows user in the development world (in general) but contributing to most projects doesn't require anything special. Fork, branch, commit, PR. Pretty simple.

But for this project, we need to install an entirely new operating system, get about 8 separate installations working (which I've yet to do) and also understand Linux in order to contribute.

I think you're scaring a lot of potential contributors away with this requirement and it should change.

I'm at the point where a Linux partition on my Windows machine is much more accessible than trying to use WSL. I hope you'll reconsider this requirement and make the necessary changes to make contributing to this project more inclusive of developers using Windows.

**Comment by FrozenPandaz** [comment]
I agree, I also use Windows frequently but switch to a unix OS to develop. This is not something all developers have available to them.

The reason why the repo currently requires some sort of unix terminal to develop is that we execute things like `rm`, `mv`, etc. directly.

 It would be great to enable development through **cmd** and/or **powershell**. It would be greatly appreciated if someone from the community could take this effort on.

**Comment by Hotell** [comment]
btw: WSL 2 will be GA in stable windows (no preview builds) soonish
