### ISSUE TITLE
yarn berry not supported

### ISSUE THREAD

**Issue by xenoterracide** [nrwl/nx#11472]
## Current Behavior

```
❯ yarn create nx-workspace
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 1s 434ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0068: │ jest-extended ➤ peerDependencies ➤ @types/jest: No matching package in the dependency tree; you may not need this rule anymore.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ defaults@npm:1.0.3 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ is-interactive@npm:1.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ ora@npm:5.3.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ wcwidth@npm:1.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs-parser@npm:21.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 0s 351ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 1s 871ms

✔ Workspace name (e.g., org name)     · @cof/e1-types
✔ What to create in the new workspace · ts
✔ Set up distributed caching using Nx Cloud (It's free and doesn't require registration.) · No

 >  NX   Nx is creating your v14.5.2 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "yarn install" several times. Please wait.

✖ Installing dependencies with yarn

 >  NX   Nx failed to install dependencies

   Exit code: 1
   Log file: /var/folders/xk/s3n8ww014pzbx2sn30ctz7000000gq/T/tmp-23910-3r9cGTIUsvTM/error.log

❯ git status
On branch ccushing/typed-client
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .eslintrc.yml

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	packages/devexchange-client/src/typed-dev-exchange.ts

no changes added to commit (use "git add" and/or "git commit -a")


## Expected Behavior

documentation in readme should work

## Steps to Reproduce

follow instructions to setup yarn berry, then `yarn create nx-workspace`

### Failure Logs

```
❯ cat    Log file: /var/folders/xk/s3n8ww014pzbx2sn30ctz7000000gq/T/tmp-23910-3r9cGTIUsvTM/error.log

[bat error]: 'Log': No such file or directory (os error 2)
[bat error]: 'file:': No such file or directory (os error 2)
Unknown Syntax Error: Command not found; did you mean one of:

  0. yarn cache clean [--mirror] [--all]
  1. yarn cache clean [--mirror] [--all]
  2. yarn config get [--json] [--no-redacted] <name>
  3. yarn config set [--json] [-H,--home] <name> <value>
  4. yarn config unset [-H,--home] <name>
  5. yarn set resolution [-s,--save] <descriptor> <resolution>
  6. yarn set version from sources [--path #0] [--repository #0] [--branch #0] [--plugin #0] [--no-minify] [-f,--force] [--skip-plugins]
  7. yarn set version [--only-if-needed] <version>
  8. yarn workspaces list [--since] [-R,--recursive] [-v,--verbose] [--json]
  9. yarn --clipanion=definitions
 10. yarn help
 11. yarn help
 12. yarn help
 13. yarn <leadingArgument> ...
 14. yarn -v
 15. yarn -v
 16. yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
 17. yarn bin [-v,--verbose] [--json] [name]
 18. yarn config [-v,--verbose] [--why] [--json]
 19. yarn dedupe [-s,--strategy #0] [-c,--check] [--json] [--mode #0] ...
 20. yarn exec <commandName> ...
 21. yarn explain peer-requirements [hash]
 22. yarn explain [--json] [code]
 23. yarn info [-A,--all] [-R,--recursive] [-X,--extra #0] [--cache] [--dependents] [--manifest] [--name-only] [--virtuals] [--json] ...
 24. yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
 25. yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
 26. yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
 27. yarn link [-A,--all] [-p,--private] [-r,--relative] <destination>
 28. yarn unlink [-A,--all] ...
 29. yarn node ...
 30. yarn plugin import from sources [--path #0] [--repository #0] [--branch #0] [--no-minify] [-f,--force] <name>
 31. yarn plugin import <name>
 32. yarn plugin remove <name>
 33. yarn plugin list [--json]
 34. yarn plugin runtime [--json]
 35. yarn rebuild ...
 36. yarn remove [-A,--all] [--mode #0] ...
 37. yarn run
 38. yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
 39. yarn up [-i,--interactive] [-E,--exact] [-T,--tilde] [-C,--caret] [-R,--recursive] [--mode #0] ...
 40. yarn why [-R,--recursive] [--json] [--peers] <package>
 41. yarn workspace <workspaceName> <commandName> ...
 42. yarn create [-p,--package #0] [-q,--quiet] <command> ...
 43. yarn dlx [-p,--package #0] [-q,--quiet] <command> ...
 44. yarn init [-p,--private] [-w,--workspace] [-i,--install]
 45. yarn npm audit [-A,--all] [-R,--recursive] [--environment #0] [--json] [--severity #0]
 46. yarn npm info [-f,--fields #0] [--json] ...
 47. yarn npm login [-s,--scope #0] [--publish]
 48. yarn npm logout [-s,--scope #0] [--publish] [-A,--all]
 49. yarn npm publish [--access #0] [--tag #0] [--tolerate-republish] [--otp #0]
 50. yarn npm tag add <package> <tag>
 51. yarn npm tag list [--json] [package]
 52. yarn npm tag remove <package> <tag>
 53. yarn npm whoami [-s,--scope #0] [--publish]
 54. yarn pack [--install-if-needed] [-n,--dry-run] [--json] [-o,--out #0]
 55. yarn patch-commit [-s,--save] <patchFolder>
 56. yarn patch [--json] <package>
 57. yarn unplug [-A,--all] [-R,--recursive] [--json] ...

While running --silent --ignore-scripts
```
### Environment

(can't run nx report  The current directory isn't part of an Nx workspace.)

## System:
 - OS: macOS 11.6.8
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
## Binaries:
 - Node: 16.14.2 - /private/var/folders/xk/s3n8ww014pzbx2sn30ctz7000000gq/T/xfs-117d792a/node
 - Yarn: 3.2.2 - /private/var/folders/xk/s3n8ww014pzbx2sn30ctz7000000gq/T/xfs-117d792a/yarn
 - npm: 8.5.0 - ~/.asdf/plugins/nodejs/shims/npm
## npmPackages:
 - jest: ^28.1.3 => 28.1.3

**Comment by AgentEnder** [comment]
Yarn 2+ support is tracked in #2386
