### ISSUE TITLE
TS error when attempting to run a workspace generator — TS5042: Option 'project' cannot be mixed with source files on a command line

### ISSUE THREAD

**Issue by Kris-Pelteshki** [nrwl/nx#11487]
## Current Behavior
Invoking a workspace generator results in a TS error. The same behavior is also true when using the `--dry-run` flag
```
nx workspace-generator test mylib
error TS5042: Option 'project' cannot be mixed with source files on a command line.
```

## Expected Behavior
I haven't used generators before, but I'm following the CLI from the [documentation](https://nx.dev/generators/workspace-generators). 

I assume that creating a Nx workspace, then create a workspace generator, then invoke that generator would not result in a TS error.

## Steps to Reproduce

1. `npx create-nx-workspace@latest` 
(does not seem to matter which present, from what I can tell)

2. `nx generate @nrwl/workspace:workspace-generator test`
![image](https://user-images.githubusercontent.com/40208044/183268030-ab21a70d-d0af-4808-b866-b1178721bae7.png)

3. `nx workspace-generator test mylib`

### Failure Logs

```
nx workspace-generator test mylib
error TS5042: Option 'project' cannot be mixed with source files on a command line.
```

### Environment
Node : 16.14.2
   OS   : win32 x64
   npm  : 8.5.0

   nx : 14.5.4
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.4
   @nrwl/eslint-plugin-nx : 14.5.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.4
   @nrwl/js : 14.5.4
   @nrwl/linter : 14.5.4
   @nrwl/nest : 14.5.4
   @nrwl/next : Not Found
   @nrwl/node : 14.5.4
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.5.4
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:

**Comment by Kris-Pelteshki** [comment]
I've gone ahead with the "local" nx plugin option. 
Everything seems to work fine! 

 — Thank you for the amazing tooling :)

**Comment by virus231** [comment]
Can you please explain ? how did you resolve "error TS5042: Option 'project' cannot be mixed" issue?
