### ISSUE TITLE
Build a Basic Blog cut off toward the end

### ISSUE THREAD

**Issue by npearson72** [nrwl/nx#11488]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/core-tutorial/01-create-blog

### Additional context or description

This is the only thing that's visible at the end of the document:

<img width="865" alt="Screen Shot 2022-08-06 at 3 40 29 PM" src="https://user-images.githubusercontent.com/1323414/183268098-45729392-6fd3-4609-857a-2d94a1014f8a.png">

It should display a lot more as is the case here: https://github.com/nrwl/nx/blob/master/docs/shared/core-tutorial/01-create-blog.md#build-a-basic-blog

**Comment by bcabanes** [comment]
Fixed by https://github.com/nrwl/nx/pull/12206.
