### ISSUE TITLE
Outdated Configurations Run Command

### ISSUE THREAD

**Issue by ewandos** [nrwl/nx#11495]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/configuration/projectjson#targets
Section: Configurations

### Additional context or description

For me it's not possible to run a selected configuration with `nx run mylib:build:configuration=production`.
It only works with `nx run mylib:build:production`.

**Comment by AgentEnder** [comment]
That definitely seems incorrect, would you like to open a PR correcting it?

**Comment by AgentEnder** [comment]
It appears this has been fixed as docs have been updated over time.
