### ISSUE TITLE
[Bug][CLI] Cli should warn no apps to run

### ISSUE THREAD

**Issue by luchillo17** [nrwl/nx#115]
# Bug outline
I created a new project with the command `curl -fsSL https://raw.githubusercontent.com/nrwl/nx/master/packages/install/install.sh | bash -s myprojectname` which should use the stable version, right?

## Current behavior
I got into the project, kick on a `yarn && yarn start` and it installed ok, but when running i get this error:
![image](https://user-images.githubusercontent.com/9698639/33145913-27e11b7e-cf90-11e7-8d21-74288d3a7c61.png)

## Expected behavior
To just install and run without issues, is this an issue with my PC? am i the only one?

## Additional info
Output of `ng --version`:
```sh
Angular CLI: 1.5.0
Node: 8.9.1
OS: linux x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.36
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.5
typescript: 2.4.2
webpack: 3.8.1
```

**Comment by luchillo17** [comment]
**Update:** Tested the `@next` version and same issue.

**Comment by luchillo17** [comment]
**Update 3:** Definitely its a `@nwrl/schematics` issue when generating the project, tried with latest `@angular/cli@1.5.3` when generating through global install, set up to use yarn instead of npm, and it still breaks when serving, am i the only one suffering this issue?

**Comment by vsavkin** [comment]
Could you provide a repro?

Also, take a look at this: https://github.com/nrwl/nx/wiki/FAQ

**Comment by luchillo17** [comment]
@vsavkin thanks for the response, first, "Where have you been sweet FAQ?", now i understand why the custom fork.

As stated above, i just generated a new project with the shell script provided in the main page, tried both the stable version and the `@next` one, and both fail the same.

On other news, i noticed the `root` field in the `angular-cli.json` had double backslashes `\\` which seems to complain with Windows paths, which might be the reason of bug on Ubuntu, i'll try later in my Linux PC at home to make sure this isn't the cause of above error.

So far the repro should be:
* Be on a Unix based system.
* Use stable version of Nwrl shell script to generate a project  (doesn't matter NPM nor Yarn).
* Run `ng serve`.

Those should trigger the issue, though i only have Ubuntu 17.10 to test.

**Comment by luchillo17** [comment]
@vsavkin I'm dumb, i forgot to create an app, that's why this error shows up, though it would be nice for the cli to warn the user instead of the cryptic message.

**Comment by eppsilon** [comment]
I ran into this issue too. Would it be possible to add a note to the docs about this @vsavkin ?

**Comment by luchillo17** [comment]
@eppsilon did yours also because you lacked the app creation step? i think it shouldn't just throw up such an issue but instead tell you if there's no app to show.

**Comment by eppsilon** [comment]
Yep, I tried running `ng serve` without creating an app first. I'd agree with re-opening this issue as a suggested documentation change.

**Comment by vsavkin** [comment]
@jschwarty could you incorporate it into your docs update?
