### ISSUE TITLE
Import library from monorepo inside other repo in development mode

### ISSUE THREAD

**Issue by jebesampaio** [nrwl/nx#11518]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [x] Documentation feedback

### Additional context or description
We are trying to migrate to a monorepo solution and we've made most of the work, however a problem was raised with the local development workflow.

We have separated our repos into a private and public on github. 
The public Nx monorepo which has some libs that will be published and will be consumed by other github private repo (a simple react app, in this case).
To use the libs locally on the private repo, in development mode, what is the recommended approach, since I don't have some the libs published to npm? 
Previously we used the `npm i relative-path/to-library`, but since the node modules are now on the root folder, the packages are not found.
Is there something we're missing here?

Thank you

**Comment by jebesampaio** [comment]
This should be a very straightforward process. 
Anyone has a clue on this?

**Comment by JonathanWilbur** [comment]
I came here to post a question exactly like this. I would love to see official support for some kind of "remote extensions" to a monorepo, or a "public-private hybrid monorepo." The only ways I see that can give us this behavior are:

1. `npm link` (For JavaScript / TypeScript projects only)
2. Making the monorepo public, but putting the private subtree of it in a Git submodule that you clone separately if you can.
  - I think this option would only require Nx to tolerate projects that appear in `workspace.json`, but don't actually exist.

**Comment by Nick-Lucas** [comment]
I wonder if this has become much easier with 15.7.0 with the complete removal of workspace.json? Could a submodule be detected naturally now and just the base tsconfig be updated by hand?

**Comment by isaacplmann** [comment]
There are several ways to run your own npm repository.  You could use Artifactory or Verdaccio.  Or you could run `npm pack` and then copy the `*.tgz` file into the other repo and use `file:path/to/tgz-file` in your package.json.
