### ISSUE TITLE
Example not working: Advanced Angular Micro Frontends with Dynamic Module Federation

### ISSUE THREAD

**Issue by Sebastian-Herbst** [nrwl/nx#11516]
### Documentation issue

- [x] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?
https://nx.dev/module-federation/dynamic-module-federation-with-angular

### Additional context or description
- The documentation isn't consistent on @ng-mf/@ng-mf
- If you follow the example on the page it works until 'nx run login:serve'. The login isn't passed to the dashboard doesn't show up.

**Comment by Coly010** [comment]
thanks for raising this. It seems there was a change to how `initialNavigation' : 'enableBlocking'` operates in Angular 14
