### ISSUE TITLE
Eleventy install command(npm) is strange

### ISSUE THREAD

**Issue by MechanicKim** [nrwl/nx#11510]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/core-tutorial/01-create-blog#adding-eleventy

### Additional context or description

In Eleventy install

yarn command is correct.

<img width="340" alt="스크린샷 2022-08-09 오후 5 31 10" src="https://user-images.githubusercontent.com/12149783/183604017-b71bdcd7-fae0-4c68-a1bb-f81eb4a1e9fd.png">

But npm command is strange.

<img width="323" alt="스크린샷 2022-08-09 오후 5 31 16" src="https://user-images.githubusercontent.com/12149783/183604103-2d3862f2-3bdd-485b-9cd4-cbfdf2d1b6d4.png">

I think this command should be changed to 'npm i -D @11ty/eleventy'.

nx generate @nrwl/react:library => npm i -D @11ty/eleventy

Please confirm it.
Thanks.

**Comment by AgentEnder** [comment]
Yeah, that looks wrong. Do you want to submit a PR to fix it?
