### ISSUE TITLE
Nextjs application created with nx g @nrwl/next:app doesn't immediately render

### ISSUE THREAD

**Issue by snigdha920** [nrwl/nx#11514]
## Current Behavior

1. I created an nx app by running `nx g @nrwl/next:app my-app-name`
2. I ran `nx serve my-app-name`
3. Navigated to `localhost:4200`, the app wouldn't render with the following error:

```
Error: "CustomDocument.getInitialProps()" should resolve to an object with a "html" prop set with a valid html string
```

## Expected Behavior

The app should just render without any errors.

## Steps to Reproduce

1. Create an nextjs nx app using `nx g @nrwl/next:app your-app-name`
2. Run `nx serve your-app-name`
3. Navigate to `localhost:4200` 
4. You will see the following error:

```
Error: "CustomDocument.getInitialProps()" should resolve to an object with a "html" prop set with a valid html string
```

### Failure Logs

```
> nx run my-app:serve:development

info  - automatically enabled Fast Refresh for 1 custom loader
event - compiled client and server successfully in 294 ms (174 modules)
[ ready ] on http://localhost:4200
wait  - compiling / (client and server)...
event - compiled client and server successfully in 215 ms (190 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 57 ms (191 modules)
error - Error: "CustomDocument.getInitialProps()" should resolve to an object with a "html" prop set with a valid html string
    at loadDocumentInitialProps (/Users/snigdhasingh/bpaas/node_modules/next/dist/server/render.js:774:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async renderDocument (/Users/snigdhasingh/bpaas/node_modules/next/dist/server/render.js:856:43)
    at async Object.renderToHTML (/Users/snigdhasingh/bpaas/node_modules/next/dist/server/render.js:893:28)
    at async doRender (/Users/snigdhasingh/bpaas/node_modules/next/dist/server/base-server.js:915:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/Users/snigdhasingh/bpaas/node_modules/next/dist/server/base-server.js:1020:28)
    at async /Users/snigdhasingh/bpaas/node_modules/next/dist/server/response-cache.js:69:36 {
  page: '/'
}
```

### Environment

```
 >  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : darwin arm64
   yarn : 3.2.2

   nx : 14.5.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.4
   @nrwl/eslint-plugin-nx : 14.5.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.4
   @nrwl/js : 14.5.4
   @nrwl/linter : 14.5.4
   @nrwl/nest : 14.5.4
   @nrwl/next : 14.5.4
   @nrwl/node : 14.5.4
   @nrwl/nx-cloud : 14.3.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.4
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.4
   @nrwl/web : 14.5.4
   @nrwl/workspace : 14.5.4
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
   	 @nx-go/nx-go: 2.6.0
   	 @nx-tools/nx-docker: 3.0.2
   	 nest-commander-schematics: 3.0.0
```

**Comment by snigdha920** [comment]
I fixed it by following the steps given in the NextJS docs for customising the Document in the latest version [here](https://nextjs.org/docs/advanced-features/custom-document#customizing-renderpage).

This is my `_document.tsx` file that works:

```
/* eslint-disable react/display-name */
import Document, { DocumentContext, Head, Html, Main, NextScript } from 'next/document';

export default class CustomDocument extends Document {
  static async getInitialProps(ctx: DocumentContext) {
    const originalRenderPage = ctx.renderPage;

    // Run the React rendering logic synchronously
    ctx.renderPage = () =>
      originalRenderPage({
        // Useful for wrapping the whole react tree
        enhanceApp: (App) => App,
        // Useful for wrapping in a per-page basis
        enhanceComponent: (Component) => Component,
      });

    // Run the parent `getInitialProps`, it now includes the custom `renderPage`
    const initialProps = await Document.getInitialProps(ctx);

    return initialProps;
  }

  render() {
    return (
      <Html>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

```

I'd be happy to open a PR to update the `_document.tsx` file being rendered if someone can point me to where the changes need to be made :)

**Comment by Kris-Pelteshki** [comment]
> I fixed it by following the steps given in the NextJS docs for customising the Document in the latest version [here](https://nextjs.org/docs/advanced-features/custom-document#customizing-renderpage).
> 
> This is my `_document.tsx` file that works:
> 
> ```
> /* eslint-disable react/display-name */
> import Document, { DocumentContext, Head, Html, Main, NextScript } from 'next/document';
> 
> export default class CustomDocument extends Document {
>   static async getInitialProps(ctx: DocumentContext) {
>     const originalRenderPage = ctx.renderPage;
> 
>     // Run the React rendering logic synchronously
>     ctx.renderPage = () =>
>       originalRenderPage({
>         // Useful for wrapping the whole react tree
>         enhanceApp: (App) => App,
>         // Useful for wrapping in a per-page basis
>         enhanceComponent: (Component) => Component,
>       });
> 
>     // Run the parent `getInitialProps`, it now includes the custom `renderPage`
>     const initialProps = await Document.getInitialProps(ctx);
> 
>     return initialProps;
>   }
> 
>   render() {
>     return (
>       <Html>
>         <Head />
>         <body>
>           <Main />
>           <NextScript />
>         </body>
>       </Html>
>     );
>   }
> }
> ```
> 
> I'd be happy to open a PR to update the `_document.tsx` file being rendered if someone can point me to where the changes need to be made :)

I'm also new around here 👋 and thanks for offering to contribute!

Here is the document template that's used when a next application is generated: 
https://github.com/nrwl/nx/blob/master/packages/next/src/generators/application/files/pages/_document.tsx__tmpl__

path in the repo: `packages/next/src/generators/application/files/pages/_document.tsx__tmpl__`

and here's the link to the guidelines for contributing:
https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md

**Comment by snigdha920** [comment]
Hello 👋 I'll try to open a PR after work to fix this, thank you!

**Comment by snigdha920** [comment]
It's been fixed thanks to https://github.com/nrwl/nx/commit/50afd2b6648ce967ed76437598315df016278a35, closing the issue.
