### ISSUE TITLE
@nrwl/next static assets 404 with @nrwl/next:server executor

### ISSUE THREAD

**Issue by pmualaba** [nrwl/nx#11524]
## Current Behavior

When using the **@nrwl/next:server executor** (nx serve), static assets are served only from **apps/app/public** source folder. Even when we configure project.json like this:

` "options": {
        "root": "apps/app",
        "outputPath": "dist/apps/app",
        "assets": [
          {
            "input": "libs/ui/static",
            "glob": "**/*",
            "output": ""
          },
          {
            "input": "libs/ui/icons/assets",
            "glob": "**/*",
            "output": "assets/icons"
          }
        ]
      },`

This results in 404 resource not found for all static assets that are moved out of the next public folder into the nx library when launching the local dev server with **nx serve app**

## Expected Behavior

nx serve app SHOULD serve static assets according to the configuration in project.json and NOT serve the static assets only from next public folder

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

<img width="583" alt="image" src="https://user-images.githubusercontent.com/1754718/183755365-c73ccac3-d5bf-4eae-9f29-8bc64f41dd7d.png">

### Environment

"next": "12.2.3",

 >  NX   Report complete - copy this into the issue template

   Node : 16.15.0
   OS   : linux x64
   yarn : 3.2.2
   
   nx : 14.5.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.4
   @nrwl/eslint-plugin-nx : 14.5.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.4
   @nrwl/js : 14.5.4
   @nrwl/linter : 14.5.4
   @nrwl/nest : 14.5.4
   @nrwl/next : 14.5.4
   @nrwl/node : 14.5.4
   @nrwl/nx-cloud : 14.3.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.4
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.4
   @nrwl/web : 14.5.4
   @nrwl/workspace : 14.5.4
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
         @nx-go/nx-go: 2.6.0
         @nx-tools/nx-docker: 3.0.2
         nest-commander-schematics: 3.0.0

**Comment by pmualaba** [comment]
This commit is the one that is responsible for breaking local dev resulting in 404 on static assets when you execute **nx run app:serve:development**  in a local dev environment:

https://github.com/nrwl/nx/commit/8075cb9a9fc43f12eb0a1a58853167a27b3452d9

**Comment by jaysoo** [comment]
This should be working in latest version. See demo here https://github.com/jaysoo/nx-demo-issue-11524

Note that since the dev server uses `public/` folder in source, it will need to be gitignored. We'll look at potential solutions for not needing this gitignore (if we can provide multiple "public" paths to the dev server somehow.

For now you can just gitignore the assets. :)

**Comment by alexfreska** [comment]
Hi @jaysoo just upgraded NX and hit the same issue as @Puertas and @JeanBarriere (  https://github.com/nrwl/nx/pull/11257#issuecomment-1231944630). As the others have described, I have a directory of public assets that are copied from a design system lib into the public directory of multiple next apps, so the above change means all shared assets from the design system are missing in dev mode.

**Comment by asotog** [comment]
same here, we had shared assets on root level of repo, reused by apps, and now are coming 404, issue seems around these source files
old
https://github.com/nrwl/nx/blob/1f534317d03251deaf231e2f5f3de0905b4627e7/packages/next/src/builders/server/lib/default-server.ts
vrs
latest
https://github.com/nrwl/nx/blob/master/packages/next/src/executors/server/lib/default-server.ts

[default-server.ts](https://github.com/nrwl/nx/blob/1f534317d03251deaf231e2f5f3de0905b4627e7/packages/next/src/builders/server/lib/default-server.ts)
<https://github.com/[nrwl/nx](https://github.com/nrwl/nx)|nrwl/nx>nrwl/nx | Added by [GitHub](https://snaptechnology.slack.com/services/B02EYULS5K7)

[default-server.ts](https://github.com/nrwl/nx/blob/master/packages/next/src/executors/server/lib/default-server.ts)
<https://github.com/[nrwl/nx](https://github.com/nrwl/nx)|nrwl/nx>nrwl/nx | Added by [GitHub](https://snaptechnology.slack.com/services/B02EYULS5K7)

**Comment by EmilioAiolfi** [comment]
@jaysoo help us

**Comment by anthodb** [comment]
Any News on this issue?

**Comment by ndcunningham** [comment]
Please try this with the latest version

**Comment by anthodb** [comment]
@ndcunningham still having this issue with "@nrwl/next": "15.8.9". What version did resolve this?
When serving our assets in dev mode, the files are correcly copied into the dist/public folder, but our assets are not served.
