### ISSUE TITLE
vscode intellisense does't work after fresh install

### ISSUE THREAD

**Issue by mathpaquette** [nrwl/nx#1152]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Intellisense should work out of the box like on any generated Angular-cli project,

## Current Behavior

Even if trying to add HttpClientModule in imports on app.module.ts from a freshly generated app, vscode Intellisense doesn't work. I have to manually reference the module.

![image](https://user-images.githubusercontent.com/4358455/54065052-1494eb00-41e9-11e9-8bd9-e4bfd5ded8dc.png)

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. ...

### Context

Please provide any relevant information about your setup:

- version of Nx used
@nrwl/schematics@7.6.2
- version of Angular CLI used
@angular/cli@7.3.5
- `angular.json` configuration
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "",
  "projects": {
    "myapp": {
      "root": "apps/myapp/",
      "sourceRoot": "apps/myapp/src",
      "projectType": "application",
      "prefix": "nx-mono",
      "schematics": {
        "@nrwl/schematics:component": {
          "style": "scss"
        }
      },
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/apps/myapp",
            "index": "apps/myapp/src/index.html",
            "main": "apps/myapp/src/main.ts",
            "polyfills": "apps/myapp/src/polyfills.ts",
            "tsConfig": "apps/myapp/tsconfig.app.json",
            "assets": ["apps/myapp/src/favicon.ico", "apps/myapp/src/assets"],
            "styles": ["apps/myapp/src/styles.scss"],
            "scripts": [],
            "es5BrowserSupport": true
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "apps/myapp/src/environments/environment.ts",
                  "with": "apps/myapp/src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "myapp:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "myapp:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "myapp:build"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "apps/myapp/tsconfig.app.json",
              "apps/myapp/tsconfig.spec.json"
            ],
            "exclude": ["**/node_modules/**"]
          }
        },
        "test": {
          "builder": "@nrwl/builders:jest",
          "options": {
            "jestConfig": "apps/myapp/jest.config.js",
            "tsConfig": "apps/myapp/tsconfig.spec.json",
            "setupFile": "apps/myapp/src/test-setup.ts"
          }
        }
      }
    },
    "myapp-e2e": {
      "root": "apps/myapp-e2e",
      "projectType": "application",
      "prefix": "",
      "architect": {
        "e2e": {
          "builder": "@nrwl/builders:cypress",
          "options": {
            "cypressConfig": "apps/myapp-e2e/cypress.json",
            "tsConfig": "apps/myapp-e2e/tsconfig.e2e.json",
            "devServerTarget": "myapp:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "myapp:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "apps/myapp-e2e/tsconfig.e2e.json",
            "exclude": ["**/node_modules/**"]
          }
        }
      }
    }
  },
  "cli": {
    "warnings": {
      "typescriptMismatch": false,
      "versionMismatch": false
    },
    "defaultCollection": "@nrwl/schematics"
  },
  "schematics": {
    "@nrwl/schematics:application": {
      "style": "scss"
    },
    "@nrwl/schematics:library": {
      "style": "scss"
    }
  },
  "defaultProject": "myapp"
}

- version of Angular DevKit used
"@angular-devkit/build-angular": "0.13.1",
- 3rd-party libraries and their versions
vanilla install
- and most importantly - a use-case that fails

**A minimal reproduce scenario using allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

Please include any relevant log snippets or files here.

## Other

Any other relevant information that will help us help you.

**Comment by skydever** [comment]
hi!

just wondering - I am facing performance issues with vscode lately, sometimes it takes very long to get the intellisense as it should be, and my machine is a I would say good one ... how did you solve your issue? by just waiting a bit longer until you get the suggestions?

I googled a bit about performance issues using vscode and came to the issue about the [Angluar Language Service](https://github.com/angular/vscode-ng-language-service/issues/44#issuecomment-457631584) but did not dive deeper into the problem, I just live with the performance issues at the moment ... but when there is time I will dive deeper hopefully, I don't want to deactivate the angular language service ...

I was thinking about the latets `tsconfig.json` changes that were added to get the right intellisense concerning the jest and cypress typings - now vscode can pick the config and use it to get the right typings, but what is happening under the hood? does vscode start a new typescript server process for whenever you open a file with another `tsconfig.json` and starts to recompile/check all the sources? they are all linked to the `tsconfig.json` in the root of the workspace... is a `exclude` in a sub project overriding the `"exclude": ["node_modules", "tmp"]` from the root `tsconfig.json` was another thing I was thinking of, somehow `node_modules` will be picked from the typescript server doing things there, I don't know yet ...

Do you open the complete workspace in vscode, or just apps or libs you are working on? I am opening the whole workspace, even more - the nx workspace is part of a monorepo on top of it, that includes java backends etc. but even when I deactivate the java extensions I have problems ...

Any comment on that topic would be helpful to me, thx in advance!

**Comment by egarkavy** [comment]
I migrated existing angular project to NX and had the problem when I was creating new ts files they are weren't visible for others by intellisense and new ts file itself didn't see paths aliases except default node_modules
It appeared that I needed to add tsconfig.editor.json to the level where tsconfig.app.json lays
The content of tsconfig.editor.json
`{
  "extends": "./tsconfig.json",
  "include": ["**/*.ts"],
  "compilerOptions": {
    "types": ["jest", "node"]
  }
}
`

tsconfig.json: 
`{
    "extends": "../../tsconfig.base.json",
    "compilerOptions": {
        "types": ["node", "jest"]
    },
    "files": [],
    "include": [],
    "references": [
        {
            "path": "./tsconfig.app.json"
        },
        {
            "path": "./tsconfig.spec.json"
        },
        {
            "path": "./tsconfig.editor.json"
        }
    ]
}
`
