### ISSUE TITLE
`nx connect-to-nx-cloud` does (sometimes) not work with pnpm

### ISSUE THREAD

**Issue by mariohamann** [nrwl/nx#11548]
## Current Behavior
I'm executing `nx connect-to-nx-cloud` in a `pnpm` workspace. I get the following error `Error: Command failed: pnpm add -D @nrwl/nx-cloud@latest`, preventing me to proceed.

## Expected Behavior
Instead of `pnpm add -D @nrwl/nx-cloud@latest` I believe `pnpm add -D @nrwl/nx-cloud@latest -w` should be executed, otherwise `pnpm` logs the following error:

` ERR_PNPM_ADDING_TO_ROOT  Running this command will add the dependency to the workspace root, which might not be what you want - if you really meant it, make it explicit by running this command again with the -w flag (or --workspace-root). If you don't want to see this warning anymore, you may set the ignore-workspace-root-check setting to true.`

After setting `ignore-workspace-root-check=true` in `.nprmc` it worked.

## Steps to Reproduce
Couldn't reproduce in another repo...

### Environment
```
nx : 14.1.4
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.1
   @nrwl/js : Not Found
   @nrwl/linter : 14.5.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.3.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.5.1
   typescript : 4.7.4
   rxjs : Not Found
```
(I updated `nx` later, too, but hadn't any luck.)

**Comment by AgentEnder** [comment]
Hey @mariohamann, it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.
