### ISSUE TITLE
 NX   Schema does not support positional arguments.

### ISSUE THREAD

**Issue by berc** [nrwl/nx#11559]
In the version of `nx@~12.10.1` the following command was working just fine:

`nx run my-app:serve -- --proxy-config=./apps/my-app/proxy.conf.json`

Now with version `nx@14.5.4` I receive this error:
`NX   Schema does not support positional arguments. Argument '--proxy-config=./apps/my-app/proxy.conf.json' found`

Questions:
1. Is it an issue of NX or more like not support anymore from Angular of positional arguments ?
2. If it is not an issue of NX, is there some workaround to dynamically define proxy config from command line ?

**Comment by AgentEnder** [comment]
Can you try to run the command without `--`? That's not generally needed for Nx commands.

**Comment by berc** [comment]
Yes, it worked without ` -- `. Thank you for advice.
