### ISSUE TITLE
 npx nx generate storybook-configuration results in error:   NX   Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by peter-coastpay-com** [nrwl/nx#11566]
## Current Behavior

running the command:

 npx nx generate storybook-configuration

and then entering the project name and responding to the prompts results in the following error: 

 >  NX   Cannot convert undefined or null to object

```

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at findStorybookAndBuildTargetsAndCompiler (/Users/petervijeh/workspace/payments-management/webapps/all-apps/node_modules/@nrwl/storybook/src/utils/utilities.js:167:12)
    at /Users/petervijeh/workspace/payments-management/webapps/all-apps/node_modules/@nrwl/storybook/src/generators/configuration/configuration.js:18:103
    at Generator.next (<anonymous>)
    at /Users/petervijeh/workspace/payments-management/webapps/all-apps/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/petervijeh/workspace/payments-management/webapps/all-apps/node_modules/tslib/tslib.js:114:16)
    at configurationGenerator (/Users/petervijeh/workspace/payments-management/webapps/all-apps/node_modules/@nrwl/storybook/src/generators/configuration/configuration.js:14:20)
    at /Users/petervijeh/workspace/payments-management/webapps/all-apps/node_modules/@nrwl/react/src/generators/storybook-configuration/configuration.js:24:74
    at Generator.next (<anonymous>)
```

## Expected Behavior

it should run

## Steps to Reproduce

described above

### Environment

"react": "^17.0.2",
"nx": "14.5.4",

**Comment by Kris-Pelteshki** [comment]
Can you share your `project.json` file for the project that you're trying to add a storybook configuration to? 
It might be missing a `"targets"` definition for the project

**Comment by peter-coastpay-com** [comment]
here is the projects json for an app within the project: 

`{
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/qualifications-portal/src",
  "projectType": "application",
  "targets": {
    "storybook": {
      "executor": "@nrwl/storybook:storybook",
      "options": {
        "uiFramework": "@storybook/react",
        "port": 4400,
        "config": {
          "configFolder": "apps/qualifications-portal/.storybook"
        }
      },
      "configurations": {
        "ci": {
          "quiet": true
        }
      }
    },
    "build-storybook": {
      "executor": "@nrwl/storybook:build",
      "outputs": ["{options.outputPath}"],
      "options": {
        "uiFramework": "@storybook/react",
        "outputPath": "dist/storybook/qualifications-portal",
        "config": {
          "configFolder": "apps/qualifications-portal/.storybook"
        }
      },
      "configurations": {
        "ci": {
          "quiet": true
        }
      }
    }
  },
  "tags": []
}
`

**Comment by mandarini** [comment]
Hi there @peter-coastpay-com ! Which project are you trying to generate `storybook-configuration` for? The `project.json` for `webapps/all-apps/storybook-static` looks weird, it does not match the schema that Nx expects. So Nx will not be able to generate Storybook configuration for it. What type of project is that project?

**Comment by mandarini** [comment]
Hi there @peter-coastpay-com ! Did you get a chance to look into this?

**Comment by peter-coastpay-com** [comment]
@mandarini this project was original a Create React Apps app that i converted (after much struggle) to use NX

**Comment by mandarini** [comment]
Hi @peter-coastpay-com ! If you cannot share more about your project in this public channel, you can join the [Nx community slack](https://join.slack.com/t/nrwlcommunity/shared_invite/zt-1fmyh7hib-MsIDqDDxoutA1gqeFHCnyA) and we can continue the debugging there. Your `project.json` looks different than the expected format and this is what's causing the issue.

**Comment by mandarini** [comment]
I'll be closing this since I've had no reply from @peter-coastpay-com ! If it persists, feel free to ping me again and I'll reopen! :)
