### ISSUE TITLE
'enforce-module-boundaries' rule doesn't work with Windows CLI (I already found a fix)

### ISSUE THREAD

**Issue by aronmandrella** [nrwl/nx#11577]
## Current Behavior

When using ESLint VSCode plugin, everything works as expected. However, when you run `nx lint` with rule `enforce-module-boundaries` at one point eslint plugin calls a `getSourceFilePath` function:
https://github.com/nrwl/nx/blob/d9ebe0870de2bd309af1d790d57a2f66583c5839/packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts#L195

on Windows first argument can look like this:
`"C:\\Users\\abc\\repo\\apps\\example-next-app-1\\pages\\index.tsx"`
and second one can look like this:
`"/Users/abc/repo"`

Given these arguments function returns:
`o/apps/example-next-app-1/pages/index.tsx`

## Expected Behavior

Function should return:
`apps/example-next-app-1/pages/index.tsx`

## Steps to fix

Normalzie path first by changing:
https://github.com/nrwl/nx/blob/d9ebe0870de2bd309af1d790d57a2f66583c5839/packages/workspace/src/utils/runtime-lint-utils.ts#L205

to

```ts
export function getSourceFilePath(sourceFileName: string, projectPath: string) {
  const relativePath = normalizePath(sourceFileName).slice(projectPath.length + 1);
  return normalizePath(relativePath);
}
```

**Comment by AgentEnder** [comment]
Hey, this looks like a valid fix. Do you want to open a PR?

**Comment by aronmandrella** [comment]
> Hey, this looks like a valid fix. Do you want to open a PR?

Hey, unfortunately I won't have an access to any pc during this week.

**Comment by meeroslav** [comment]
Thank you @aronmandrella for reporting the issue and proposing the fix.
