### ISSUE TITLE
Cache bugs in CI, how to debug?

### ISSUE THREAD

**Issue by joshribakoff-sm** [nrwl/nx#11572]
I am caching `./node_modules/.cache/nx` in circle CI and restoring it at the start of CI jobs.

## Current Behavior
- I can surface the `./node_modules/.cache/nx` as artifacts in my CI job, and pull them locally and Nx uses the cache locally, the cache being created is not corrupt ✅ 
- In CI, Nx does not use the cache. Cache directory always increases in size after running the command(s), when compared to the original size of the cache restored from the previous CI job which run the command(s). *something* is changing the cache's hash and causing a cache miss ❌ 
- When running in CI, it doesn't output the same information as when I run it locally like ` 9/9 succeeded [0 read from cache]` ❌ 

## Expected Behavior
- Use the cache 🤷 nothing has changed!
- Output diagnostics about why the cache was not used?
- Output anything at all about whether the cache was used, when running in CI.

## Steps to Reproduce
Try caching `node_modules/.cache` on CircleCI?

### Environment
```
 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : darwin x64
   npm  : 8.1.2
   
   nx : 13.7.1
   @nrwl/angular : undefined
   @nrwl/cli : 13.7.1
   @nrwl/cypress : 13.7.1
   @nrwl/detox : undefined
   @nrwl/devkit : 13.7.1
   @nrwl/eslint-plugin-nx : 13.7.1
   @nrwl/express : 13.8.3
   @nrwl/jest : 13.7.1
   @nrwl/js : 13.7.1
   @nrwl/linter : 13.7.1
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : 13.7.1
   @nrwl/nx-cloud : undefined
   @nrwl/react : 13.7.1
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.3
   @nrwl/tao : 13.7.1
   @nrwl/web : 13.7.1
   @nrwl/workspace : 13.7.1
   typescript : 4.4.4
   rxjs : 7.5.4
   ---------------------------------------
   Community plugins:
         @nx-tools/nx-docker: 2.3.0
```

**Comment by dereekb** [comment]
Since you're using CircleCI you might want to check out the CircleCI orb for Nx if you aren't already and see if it will help resolve your issue.

https://circleci.com/developer/orbs/orb/nrwl/nx
https://github.com/nrwl/nx-orb
https://nx.dev/ci/monorepo-ci-circle-ci

I don't think I'm doing anything special in particular on my project with those orbs enabled and CircleCI is using the local and remote cache properly.

Run:

https://app.circleci.com/pipelines/github/dereekb/dbx-components/1581/workflows/6807e0dc-11fe-4599-95c9-91c9076a3469/jobs/4352/parallel-runs/0/steps/0-109

That project's [config.yml](https://github.com/dereekb/dbx-components/blob/develop/.circleci/config.yml)

**Comment by joshribakoff-sm** [comment]
>  you might want to check out the CircleCI orb for Nx
Already using it, but it doesn't do anything with storing the local cache to CircleCI. I had to add that part myself. You can confirm this by observing the word `cache` doesn't appear anywhere in the Orb's source code: https://github.com/nrwl/nx-orb/search?q=cache

>  CircleCI is using the local and remote cache properly.
Your build output states it used a remote cache, I don't think we can conclude this means local cache was used.

 I don't see anywhere that you're persisting `./node_modules/.cache` folder and restoring it in your `config.yml`, so it seems pretty obvious to me you're exclusively using "remote cache". The only CircleCI `restore_cache` you have in related to firebase.

**Comment by joshribakoff-sm** [comment]
Right after `restore_cache`, I can observe these files in the remote `./node_modules/.cache` inside my CircleCI container (which result in a cache hit if I pull them locally to my machine and run the command locally):

```
608K	node_modules/.cache/nx

total 296K
drwxr-xr-x 17 circleci circleci 4.0K Aug 13 01:00 .
drwxr-xr-x  3 circleci circleci   16 Aug 13 00:38 ..
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 16d611d54bc53bd653f7dc1f44c10553a3b7c2e6989f74794d87ddb92a76547e
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 16d611d54bc53bd653f7dc1f44c10553a3b7c2e6989f74794d87ddb92a76547e.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 2d403a76f633eab21d731e66f7de7c265311ff0f0f09e4e71580175a7d76dbc2
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 2d403a76f633eab21d731e66f7de7c265311ff0f0f09e4e71580175a7d76dbc2.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 2fb59954f8b7d580ed5021cd633648ded5fe4b7c4819cc64b22bdf83a48a0d6b
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 2fb59954f8b7d580ed5021cd633648ded5fe4b7c4819cc64b22bdf83a48a0d6b.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 5b56fe4a13686e710e3a9317600ed9749234f057932e615e45d6afac4b51724a
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 5b56fe4a13686e710e3a9317600ed9749234f057932e615e45d6afac4b51724a.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 852aefc797729a1985e8f2df36f66c25991f64bcbf64f20214f8c2da52c3ba61
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 852aefc797729a1985e8f2df36f66c25991f64bcbf64f20214f8c2da52c3ba61.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 88ccc953ee86e3b37d663dc583f616de78682841d47c7d5b17a9a58e365da9ab
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 88ccc953ee86e3b37d663dc583f616de78682841d47c7d5b17a9a58e365da9ab.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 b1efc96c192f334d65c682fdce7ec41d48b067f938cc36688636e3ad8d94b9ac
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 b1efc96c192f334d65c682fdce7ec41d48b067f938cc36688636e3ad8d94b9ac.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 b253f2970385e32201f9957cea65cfb25a8973fe8bc7f58d9ab48b1c952f0224
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 b253f2970385e32201f9957cea65cfb25a8973fe8bc7f58d9ab48b1c952f0224.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 bdf4aedff878c22ed037876e6674366fa130116a31efb8333ef0810f0a22de49
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 bdf4aedff878c22ed037876e6674366fa130116a31efb8333ef0810f0a22de49.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 c7fc24d23fc3de31c6d21adfab20a14e2890adcb731d7af9b3c587c42d407001
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 c7fc24d23fc3de31c6d21adfab20a14e2890adcb731d7af9b3c587c42d407001.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 cc29aeb6d665b914c6123ba73981479312897a88e6fe2def22ca57c7ad175651
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 cc29aeb6d665b914c6123ba73981479312897a88e6fe2def22ca57c7ad175651.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 fd26018d45991214b7f518c94e0131cff6df98183b90c4e555b12a16599736cb
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 fd26018d45991214b7f518c94e0131cff6df98183b90c4e555b12a16599736cb.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 ff7e8ece45f0b56dfd028635a9de11ae4e41275cc0db290e627f08547aa818b9
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 ff7e8ece45f0b56dfd028635a9de11ae4e41275cc0db290e627f08547aa818b9.commit
drwxr-xr-x  2 circleci circleci   28 Aug 13 01:00 latestOutputsHashes
-rw-r--r--  1 circleci circleci 233K Aug 13 00:41 nxdeps.json
drwxr-xr-x  2 circleci circleci 4.0K Aug 13 01:00 terminalOutputs
```


After running the Nx command remotely on the CircleCI container with the above files present, I experience the previously mentioned cache miss, I can then see the below files (notice they grew in size)
```
928K	node_modules/.cache/nx

total 356K
drwxr-xr-x 30 circleci circleci 8.0K Aug 13 01:00 .
drwxr-xr-x  3 circleci circleci   16 Aug 13 00:38 ..
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 16d611d54bc53bd653f7dc1f44c10553a3b7c2e6989f74794d87ddb92a76547e
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 16d611d54bc53bd653f7dc1f44c10553a3b7c2e6989f74794d87ddb92a76547e.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 2413f16ce3bcdcb21cb1b24a94edbaf6f34b47edde232d348e9cc33ba08a3561
-rw-r--r--  1 circleci circleci    4 Aug 13 01:00 2413f16ce3bcdcb21cb1b24a94edbaf6f34b47edde232d348e9cc33ba08a3561.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 2d403a76f633eab21d731e66f7de7c265311ff0f0f09e4e71580175a7d76dbc2
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 2d403a76f633eab21d731e66f7de7c265311ff0f0f09e4e71580175a7d76dbc2.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 2fb59954f8b7d580ed5021cd633648ded5fe4b7c4819cc64b22bdf83a48a0d6b
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 2fb59954f8b7d580ed5021cd633648ded5fe4b7c4819cc64b22bdf83a48a0d6b.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 36dc61b099ce52e81f698bdf4ee0062b86dc937eddcae4bdc3d73b1cbf290563
-rw-r--r--  1 circleci circleci    4 Aug 13 01:00 36dc61b099ce52e81f698bdf4ee0062b86dc937eddcae4bdc3d73b1cbf290563.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 5b56fe4a13686e710e3a9317600ed9749234f057932e615e45d6afac4b51724a
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 5b56fe4a13686e710e3a9317600ed9749234f057932e615e45d6afac4b51724a.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 65b945618d14f7c6ef481d1a636d82122bf86971ac24be33c027cb6ba34392d7
-rw-r--r--  1 circleci circleci    4 Aug 13 01:00 65b945618d14f7c6ef481d1a636d82122bf86971ac24be33c027cb6ba34392d7.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 7200706cea0d9b7584407b92b4f24aa0a39acdbe4b9c5b2f206b1eb483682527
-rw-r--r--  1 circleci circleci    4 Aug 13 01:00 7200706cea0d9b7584407b92b4f24aa0a39acdbe4b9c5b2f206b1eb483682527.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 7d3fbdf5348d3be2dae3cdf32495409dc5840e5b837e624fd7cbd18272e72d5e
-rw-r--r--  1 circleci circleci    4 Aug 13 01:00 7d3fbdf5348d3be2dae3cdf32495409dc5840e5b837e624fd7cbd18272e72d5e.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 852aefc797729a1985e8f2df36f66c25991f64bcbf64f20214f8c2da52c3ba61
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 852aefc797729a1985e8f2df36f66c25991f64bcbf64f20214f8c2da52c3ba61.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 88ccc953ee86e3b37d663dc583f616de78682841d47c7d5b17a9a58e365da9ab
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 88ccc953ee86e3b37d663dc583f616de78682841d47c7d5b17a9a58e365da9ab.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 a57cba6b016c2fcbf083e2202c75720f70a50434ccc521dfcaef98d0a407413c
-rw-r--r--  1 circleci circleci    4 Aug 13 01:00 a57cba6b016c2fcbf083e2202c75720f70a50434ccc521dfcaef98d0a407413c.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 b1efc96c192f334d65c682fdce7ec41d48b067f938cc36688636e3ad8d94b9ac
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 b1efc96c192f334d65c682fdce7ec41d48b067f938cc36688636e3ad8d94b9ac.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 b253f2970385e32201f9957cea65cfb25a8973fe8bc7f58d9ab48b1c952f0224
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 b253f2970385e32201f9957cea65cfb25a8973fe8bc7f58d9ab48b1c952f0224.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 b53c0e76490bd114c2d91c7983aaba3ba33dc470e9dee224178f37efedd31aca
-rw-r--r--  1 circleci circleci    4 Aug 13 01:00 b53c0e76490bd114c2d91c7983aaba3ba33dc470e9dee224178f37efedd31aca.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 bdf4aedff878c22ed037876e6674366fa130116a31efb8333ef0810f0a22de49
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 bdf4aedff878c22ed037876e6674366fa130116a31efb8333ef0810f0a22de49.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 c7fc24d23fc3de31c6d21adfab20a14e2890adcb731d7af9b3c587c42d407001
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 c7fc24d23fc3de31c6d21adfab20a14e2890adcb731d7af9b3c587c42d407001.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 cc29aeb6d665b914c6123ba73981479312897a88e6fe2def22ca57c7ad175651
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 cc29aeb6d665b914c6123ba73981479312897a88e6fe2def22ca57c7ad175651.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 cf46fe28ce0033f769331ac6774ea11d3e4ceb14c8e995096f610c252d7d369d
-rw-r--r--  1 circleci circleci    4 Aug 13 01:00 cf46fe28ce0033f769331ac6774ea11d3e4ceb14c8e995096f610c252d7d369d.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 e3e1886f5769348ef232536cc0f7fec7c9ad8400b115d76c9161cb56fdcdc33a
-rw-r--r--  1 circleci circleci    4 Aug 13 01:00 e3e1886f5769348ef232536cc0f7fec7c9ad8400b115d76c9161cb56fdcdc33a.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 eb8869dc8d404c7964bae1c0a12bb37efb3f819aec6003470c6709bfdc222aed
-rw-r--r--  1 circleci circleci    4 Aug 13 01:00 eb8869dc8d404c7964bae1c0a12bb37efb3f819aec6003470c6709bfdc222aed.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 ee5b103ed47e22f900255f8fed5a430cd7845b00787d68df48f58cdbdd0ce069
-rw-r--r--  1 circleci circleci    4 Aug 13 01:00 ee5b103ed47e22f900255f8fed5a430cd7845b00787d68df48f58cdbdd0ce069.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 f242547f527c0fc0aac4d70155c15732809d3f543fe14692486be7ec41e9a668
-rw-r--r--  1 circleci circleci    4 Aug 13 01:00 f242547f527c0fc0aac4d70155c15732809d3f543fe14692486be7ec41e9a668.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 fd26018d45991214b7f518c94e0131cff6df98183b90c4e555b12a16599736cb
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 fd26018d45991214b7f518c94e0131cff6df98183b90c4e555b12a16599736cb.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 fe13c068c481239cc51694349cf4b54181054e93ef6cfde3d77aede7cf578f3b
-rw-r--r--  1 circleci circleci    4 Aug 13 01:00 fe13c068c481239cc51694349cf4b54181054e93ef6cfde3d77aede7cf578f3b.commit
drwxr-xr-x  3 circleci circleci   55 Aug 13 01:00 ff7e8ece45f0b56dfd028635a9de11ae4e41275cc0db290e627f08547aa818b9
-rw-r--r--  1 circleci circleci    4 Aug 13 00:41 ff7e8ece45f0b56dfd028635a9de11ae4e41275cc0db290e627f08547aa818b9.commit
drwxr-xr-x  2 circleci circleci   28 Aug 13 01:00 latestOutputsHashes
-rw-r--r--  1 circleci circleci 233K Aug 13 01:00 nxdeps.json
drwxr-xr-x  2 circleci circleci 4.0K Aug 13 01:00 terminalOutputs
```

The biggest problem here is that I have no way of debugging, looking at these hashes I cannot determine which underlying hashed piece of information is changing, so I cannot really figure out what needs to change in my CircleCI setup to prevent invalidating the cache. I do run a code generator on every build, but locally running my code generator does not invalidate the caches.

**Comment by StalkAltan** [comment]
Hi @joshribakoff-sm 

Unfortunately there's not a good way to surface this stuff through the default task runner. There would definitely be some value in adding that, as I understand debugging these issues are frustrating.

Hazarding a guess here, are you running your node_modules install with something that doesn't respect existing lockfiles? (ex. not using `npm ci`, `yarn --frozen-lockfile`, etc).

If you have and non-pinned versions in your package.json OR dependencies of your dependencies have non-pinned versions (very likely), this will cause your lockfile to be regenerated and possibly invalidate your cache. Additionally, if your pipeline is running a slightly different version of your package manager, this can also cause your lockfile to be invalidated and re-created.

For a more in-depth look at what is going on, I would recommend connecting your workspace to Nx Cloud and using our run comparison tool. There's no billing setup required, and we remove historic data after 30/90 days, so you could use it to figure out this issue and never touch it again. (though I think it's a lot nicer of an experience than trying to manually cache the node_modules/.cache folder)

Let me know if you've already investigated the lockfiles suggestions and we can see if there are other places to check out.

**Comment by dereekb** [comment]
Yea, I see what you're saying and asking for. I think you're running down the wrong path though, since the cache implementation seems like it is designed as black box that "just works" based on the lack of documentation. There are random things that could cause it to not be used.

The local cache is being hit on my builds. They're all persisted when I persist the entire workspace. You can see on the example below the cached build being used when test is called.

https://app.circleci.com/pipelines/github/dereekb/dbx-components/1591/workflows/4af70708-8b56-4dea-a904-27f4e9f3efad/jobs/4387/parallel-runs/0/steps/0-103

> `https://nx.app/runs/wWqaakUUJkE`

<img width="1038" alt="Screen Shot 2022-08-15 at 3 14 10 PM" src="https://user-images.githubusercontent.com/3586580/184710588-66269aa9-c784-4c32-9114-05569770f298.png">

It would be helpful to see your CircleCI config.

**Comment by joshribakoff-sm** [comment]
We're running the same versions locally and remotely, and yes we're using `npm ci`. Also when I pulled the remote cache, it was a cache hit locally, which I would not expect if either of these were the cause.

As far as the Nx Cloud, ideally we shouldn't need a 3rd party service in our toolchain to debug this, but I'll see if I have time to create a standalone repro.

> I think you're running down the wrong path though, since the cache implementation seems like it is designed as black box that "just works" based on the lack of documentation. 

🤣 thanks for the feedback, but yeah it just works until it doesn't work...

> There are random things that could cause it to not be used.

Right, so when it is not used, it could be useful to have the ability to log out debug logs as to why it was not used. Seems like a pretty reasonable request 🙏 from there, I could turn on these logs and update my issue as to whether there is a caching related bug, or perhaps help fill out any missing documentation based on what we learn.

The logs would be purely opt in, and it's entirely likely other users could experience similar issues and benefit from the logs.

**Comment by GrumpyMeow** [comment]
Interesting. I'm also having the same issue. We are also doing the "wrong" thing by persisting our .nxcache.
I thought that it might had something to do with that the outputs statement was missing in our project.json files ("output: ["dist/cypress/"]"). So i've added this to our project.json files. But still got the issue.

My next suspicion is that we've also implemented a "retry" (retryCountOnTaskFailure: 1) to reduce the impact of flaky e2e-tests. Which might keep the result files when the first e2e-attempt failed and wrote junit report files, but the second attempt did succeed. So something about not cleaning the report files generated by Cypress:
`` 
        set -e
        rm -r -f dist/cypress     < just added this to ensure that all junit report files get removed before retrying
        mkdir -p dist/cypress
        cp ci/e2escreenshots.artifactignore dist/cypress/.artifactignore
        npx start-server-and-test 'ng serve webapimock-app' 'http://localhost:4000/dev-interface/#/' 'nx affected:e2e $(affectedflags) $(e2eflags) --browser=${{ parameters.browser }}'
```

**Comment by joshribakoff-sm** [comment]
Keep active

**Comment by ZeekoZhu** [comment]
> The biggest problem here is that I have no way of debugging, looking at these hashes I cannot determine which underlying hashed piece of information is changing, so I cannot really figure out what needs to change in my CircleCI setup to prevent invalidating the cache.

Thanks to the clean architecture of nx, I managed to create a task runner ([nx-debug-hasher-runner](https://www.npmjs.com/package/@zeeko/nx-debug-hasher-runner?activeTab=readme)) that is able to open the 'black box' of the nx hasher.

```json5
// 1. update your nx.json to use the debug runner
{
  tasksRunnerOptions: {
    default: {
      // change the default runner to `@zeeko/nx-debug-hasher-runner`
      runner: '@zeeko/nx-debug-hasher-runner',
      options: {
        // see the following table for the available options
        debugOptions: {
          runner: 'your-custom-runner', // remove this line if you are not using a custom runner
          enable: true,
          debugInputPattern: true,
        },
        // all other options are passed to the actual runner (see debugOptions.runner)
        cacheableOperations: ['build'],
      },
    },
  },
}
```

2. Run your tasks with `NX_DAEMON=false`

```shell
NX_DAEMON=false nx build my-project
```

3. Now you will see the debug output from the runner, for example:

```text
DEBUG TASK: nx-debug-hasher-runner:build
{
  "id": "nx-debug-hasher-runner:build",
  "target": {
    "project": "nx-debug-hasher-runner",
    "target": "build"
  },
  "projectRoot": "packages/nx-debug-hasher-runner",
  "overrides": {
    "__overrides_unparsed__": []
  },
  "hash": "8244009900898338034",
  "hashDetails": {
    "command": "1710125247983764296",
    "nodes": {
      "nx-debug-hasher-runner:{projectRoot}/**/*": "12720395929004522337",
      "ProjectConfiguration": "17990397324634414488",
      "TsConfig": "11181298256226281826",
      // many other dependencies' hashes are omitted
    },
    "implicitDeps": {},
    "runtime": {}
  },
  "startTime": 1691655852529
}
DEBUG TASK: nx-debug-hasher-runner:build input
{projectRoot}/**/*
[
  {
    "file": "packages/nx-debug-hasher-runner/.eslintrc.json",
    "hash": "16896711999632553762"
  },
  // many other file hashes are omitted
]
```

The debug runner will output the following info:

- task object created by nx, `task.hashDetails` contains all the hashed pieces of the task.
- project input files, this array contains all the files resolved by the fileset input of the task.

P.S. The debug runner is currently in its early stages of development. If you encounter any issues, please feel free to open them [here](https://github.com/ZeekoZhu/js-prelude/issues).
