### ISSUE TITLE
To avoid opening a new issue when I'm not going to put the time into finding a repro path, I will just tack this report onto this similar issue.

### ISSUE THREAD

**Issue by AgentEnder** [nrwl/nx#11575]
To avoid opening a new issue when I'm not going to put the time into finding a repro path, I will just tack this report onto this similar issue.

## NX 14.5.5: Cannot read properties of undefined (reading 'hashTask')

Migrated to 14.5.5, 14.5.5 is installed globally, ran migrations to turn jest-config.js into .ts, everything looks good, I've done many many NX migrations successfully. Angular 14 project, all deps are latest stable version.

However, I got this with 14.5.5:

```red
% nx serve --verbose

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target serve for project MYPROJ


 >  NX   Cannot read properties of undefined (reading 'hashTask')


TypeError: Cannot read properties of undefined (reading 'hashTask')
    at /MYDIR/node_modules/@nrwl/workspace/node_modules/nx/src/hasher/hash-task.js:24:22
    at Generator.next (<anonymous>)
    at /MYDIR/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/MYDIR/node_modules/tslib/tslib.js:114:16)
    at hashTask (/MYDIR/node_modules/@nrwl/workspace/node_modules/nx/src/hasher/hash-task.js:15:20)
    at TasksSchedule.<anonymous> (/MYDIR/node_modules/@nrwl/workspace/node_modules/nx/src/tasks-runner/tasks-schedule.js:62:48)
    at Generator.next (<anonymous>)
    at /MYDIR/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
```

I'm guessing this is a general Nx broken build, but it could be specific to my project. Rolling everything back to 14.5.4 works fine. If it is specific to my project, accept my apologies for reporting.

`nx report` output _after rolling back_ (I only filed the bug once I knew rolling back worked again):

```red
% nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : darwin x64
   yarn : 1.22.19
   
   nx : 14.4.3
   @nrwl/angular : 14.5.4
   @nrwl/cypress : 14.5.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.4
   @nrwl/eslint-plugin-nx : 14.5.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.4
   @nrwl/js : 14.5.4
   @nrwl/linter : 14.5.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.4
   @nrwl/web : 14.5.4
   @nrwl/workspace : 14.5.4
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
   	 @ionic/angular: 6.2.2
   	 @ionic/angular-toolkit: 7.0.0
   	 @nxtend/capacitor: 13.0.0
   	 @nxtend/ionic-angular: 13.1.0
   	 ngx-build-plus: 14.0.0
```

Yes I know I can update nxtend to nxext and I even tried that in 14.5.5 but it didn't help so I rolled everything back to the 14.5.4 configuration that I pasted above.

Oh and I did run `nx clear-cache` and tossed `node_modules` and my dist folder and everything while trying to get 14.5.5 working.

Thanks for all your work on Nx.

_Originally posted by @spicemix in https://github.com/nrwl/nx/issues/11543#issuecomment-1213913465_

**Comment by AgentEnder** [comment]
@spicemix your version of Nx is older than the other @nrwl packages, can you try bumping it up to be equal?

**Comment by spicemix** [comment]
LOL at the issue title!
 
I somehow, despite following instructions iirc, never had `nx` as a direct dependency in my package.json, but it had somehow got into my yarn.lock, and never got updated while I did update everything else including the global `nx` and ran `nx migrate latest`. The thing also never complained, at least that I noticed, until 14.5.5 finally broke it.

So you could just dismiss this as a broken package.json, or you could fix your peer deps if there is a problem there that would have forced nx to update alongside whatever else is depending on it that broke.

Thanks for all your work on Nx!

**Comment by AgentEnder** [comment]
Sure, sounds like this has been resolved. New workspaces will certainly have `nx` installed, its possible that you had a pre-13.9 workspace that didn't contain Nx as a dep and the migration that added it was missed.
