### ISSUE TITLE
Projects Tests Hang, do not run or resolve

### ISSUE THREAD

**Issue by peter-coastpay-com** [nrwl/nx#11589]
## Current Behavior
I am trying to run all of my projects test, ignoring the cache, like so:

with the following command:
`❯ yarn nx run-many --all --target=test --skip-nx-cache --verbose`

here is the output:
```
yarn run v1.22.19
$ /Users/path/.bin/nx run-many --all --target=test --skip-nx-cache --verbose

 >  NX   Running target test for 1 projects

         With additional flags:
           --verbose=true

    →    Executing 1/1 remaining tasks...

    ⠙    nx run [project name]:test

```

environment: 
```
    "@nrwl/cli": "14.5.4",
    "@nrwl/cypress": "14.5.4",
    "@nrwl/eslint-plugin-nx": "14.5.4",
    "@nrwl/jest": "14.5.4",
    "@nrwl/linter": "14.5.4",
    "@nrwl/nx-cloud": "latest",
```

## Expected Behavior
I expect the tests to run, but they don't it just hangs like this forever with no output or resolution

**Comment by barbados-clemens** [comment]
can you try with setting the `--output-style=stream` and clearing your jest cache?

`yarn jest --clear-cache && yarn nx run-many --all --target=test --skip-nx-cache --verbose --output-style=stream`

also any reproduce-able repo you have would be helpful to know what's happening.

did this just start happening after an update? if so from what version where you on?
what kind of project is this? 
what is in your `jest.config.ts` for the project and the root `jest.preset.js` and `jest.config.ts`?

**Comment by peter-coastpay-com** [comment]
this has been happening since the beginning. 

the root has a jest.config.ts that looks like this: 

`
import { getJestProjects } from '@nrwl/jest';

export default {
  projects: getJestProjects(),
};
`

root jest.presets.js looks like this; 

`
const nxPreset = require('@nrwl/jest/preset').default;

module.exports = { ...nxPreset };
`

there are no application specific jest config files, if that matters. 


also, i noticed when running this command, there are about 1/3 of the project tests that are ignored / no not run. 

`yarn jest --clear-cache && yarn nx run-many --all --target=test --skip-nx-cache --verbose --output-style=stream`

**Comment by barbados-clemens** [comment]
you should have a project level `jest.config.ts` for each nx project generated if you're using the defaults.

if you pick one of your projects that are having issues, what does the `jestConfig` option say for the `test` target in your project configuration (usually `project.json`)

also can you run nx report and post the information back here.

**Comment by peter-coastpay-com** [comment]
NX report looks like this: 

` >  NX   Report complete - copy this into the issue template

   Node : 18.7.0
   OS   : darwin arm64
   yarn : 1.22.19

   nx : 14.5.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.4
   @nrwl/eslint-plugin-nx : 14.5.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.4
   @nrwl/js : 14.5.4
   @nrwl/linter : 14.5.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.5.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.4
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.10
   @nrwl/web : 14.5.4
   @nrwl/workspace : 14.5.4
   typescript : 4.5.5
   ---------------------------------------
   Community plugins:

✨  Done in 0.60s.`


the project.json looks like this: 

`
{
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/<project>/src",
  "projectType": "application",
  "tags": []
}

`


I am not sure what the jestConfig option for test is,  how do I produce that? 


Also, it would be incredibly useful to see a working project / example of a create react apps (CRA) project that was converted to use NX.  It would also provide me peace of mind to know that this setup does actually work as intended,  is there such an example repo?

**Comment by barbados-clemens** [comment]
1. you'll want to make sure all the @nrwl/* packages match the `nx` version (minus nx-cloud). you can run `nx migrate 14.5.10` to fix that. looks like just storybook is out of sync.
2. I didn't realize you were migrating from create-react-app. I'm not too familiar what that migration looks like for tests. I'll have to investigate what might be happening there since nx will be running the test script from your package.json in that case since there is not a _test_ target in your `project.json`

You can try running our jest project generator to add a jest configuration to your create-react-app to see if it fixes it, I'm not 100% sure if it will, but might be worth a shot just to see if it get's you unstuck.

https://nx.dev/packages/jest/generators/jest-project#@nrwl/jest:jest-project

the options you'll probably want for that generator (it's default options our react app generator uses)

`--project=<project-name> --support-tsx=true --compiler='babel' --skip-serializers `

You'll then see a new target in your `project.json` that looks similar to
```json
  "test": {
      "executor": "@nrwl/jest:jest",
      "outputs": [
        "coverage/apps/<your project name>"
      ],
      "options": {
        "jestConfig": "apps/<your project name>/jest.config.ts",
        "passWithNoTests": true
      }
    }
```

where the project level `jest.config.ts` will look something like this.
```ts
/* eslint-disable */
export default {
  displayName: '<your project name>',
  preset: '../../jest.preset.js',
  transform: {
    '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': '@nrwl/react/plugins/jest',
    '^.+\\.[tj]sx?$': ['babel-jest', {presets: ['@nrwl/react/babel']}],
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  coverageDirectory: '../../coverage/apps/<your project name>',
};
```
