### ISSUE TITLE
Add `registerProjectTags` prop to `NxPlugin`

### ISSUE THREAD

**Issue by aronmandrella** [nrwl/nx#11584]
## Description

Currently NxPlugin supports `registerProjectTargets` and `projectFilePatterns` props, and they are really handy for reducing redundand config code. For example, it can be used to automatically convert a regular barell export file, into a non-buildable lib with `lint` and `test` targets. No `project.json` file, looks like a regular directory but plays well with `nx affected`, very elegant. 

https://github.com/nrwl/nx/blob/db97728793190e8f4bb1b2d6ce19c69f7fd4f244/packages/nx/src/utils/nx-plugin.ts#L33

I think adding adding a new `registerProjectTags`prop would really fit well with that use case. If it would accept a path as an argument, it could for examle automatically inject `ui` tag if parent directory is `lib/ui`, or could inject `feature` if parent dir starts with `feature-`.

## Motivation

- Would greatly reduce amount of required manual configuration 
- Tags logic would be defined in one place and could be easly updated
- Contributes to "Negative configuration" goal outlined in NX 15 roadmap

**Comment by AgentEnder** [comment]
The plugin API v2 has landed, with docs incoming, so I'm going to go ahead and close it out.
