### ISSUE TITLE
--verbose flag does not work on with test commands

### ISSUE THREAD

**Issue by peter-coastpay-com** [nrwl/nx#11590]
Version info:

`    "@nrwl/cli": "14.5.4",
    "@nrwl/cypress": "14.5.4",
    "@nrwl/eslint-plugin-nx": "14.5.4",
    "@nrwl/jest": "14.5.4",
    "@nrwl/linter": "14.5.4",
    "@nrwl/nx-cloud": "latest",
    "@nrwl/react": "14.5.4",
    "@nrwl/storybook": "^14.5.4",
    "@nrwl/web": "14.5.4",
    "@nrwl/workspace": "14.5.4",`

Behavior:

When trying to run tests with the --verbose flag,  no logging appears:

`yarn nx run-many --all --target=test --skip-nx-cache --verbose`

expected:

Id expect to see some kind of log messages

**Comment by AgentEnder** [comment]
`--verbose` is used to print stack traces when something internal to Nx throws an error, what logging are you expecting to see?

**Comment by barbados-clemens** [comment]
Are you wanting to see the output of the tests while using `run-many`? by default you'll only see the output when an error happens. 
if you want to see the output always then you can use the [`--output-style` arg to customize the output](https://nx.dev/nx/run-many#output-style) of the output of nx. 
i.e. 
`yarn nx run-many --all --target=test --skip-nx-cache --output-style=stream`
