### ISSUE TITLE
feat: Add ability to ignore the ignore files for copying assets

### ISSUE THREAD

**Issue by joeflateau** [nrwl/nx#11598]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I would like to be able to copy assets that are ignored by .gitignore

## Motivation

I would like to copy the built javascript code of a dependency into the built code of a project. (ie: copying ./dist/lambda/origin-response into ./dist/packages/cdk-cloudfront-lambda-edge/assets)

## Suggested Implementation

Add an option to assets object to decide whether or not to apply ignore:

```
        "assets": [
          {
            "input": "./dist/packages/lambdas",
            "glob": "**/*",
            "output": "./assets",
            "bypassIgnoreFiles": true
          }
        ],

```

**Comment by giorgosera** [comment]
I just stumbled upon this issue myself! 

I'm using Prisma and I want to generate the client in a custom output path. I do not want to version control the prisma client but I want to copy it in the dist dir.
