### ISSUE TITLE
[Question] Versioning and Build strategy

### ISSUE THREAD

**Issue by dereklin** [nrwl/nx#116]
Hi,

I have app1, app2, and app3.  I have libA that's used in app1 and app2.  I have libB that's used by app3 only for now.

When I modify libB, should it trigger the building of the whole mono repo? What are some of the ways to trigger the build only for libB and app3 automatically?

For releasing, the apps can be released in different times and thus have different versions.  What are the common ways to handle this?

Also, if a team works on app1 and libA and modifies libA, they need to regression test app2.  Let's say app2 is developed and maintained by a different team.  When app2 breaks in this case, it might be unclear which team should fix app2.  In general, is mono repo better suited for very close teams where they are happy to fix each other's problems?

**Comment by vsavkin** [comment]
I think a good default is to have the team changing Lib2 having to fix app2. This is how it works at Google, Facebook, etc. But it's really up to your organization to figure it out. 

For instance, you could say the team changing Lib2 will make sure all unit tests pass, but won't guarantee that all e2e tests pass. So if app2 has poor unit test coverage, the team building the app will be responsible for fixing a lot of issues.

It all boils down to making sure the master is always green. With the current version of Nx, you will have to rerun all the tests on every commit to make sure this is the case.

Constructing a dependency graph of what app depends on what lib isn't difficult, so we are thinking about giving you a way to test a subset of apps on every change. 

Finally, once we release a bazel version of Nx, we could use it to rerun the minimum set of tests needed.
