### ISSUE TITLE
@nrwl/js:swc – path mapping not relative to baseUrl

### ISSUE THREAD

**Issue by djgrant** [nrwl/nx#11635]
## Current Behavior
When using the swc executor, `jsc.paths` produces paths that are not relative to `jsc.baseUrl`. 

## Expected Behavior
Given a path mapping:

```json
{
  "jsc": {
    "baseUrl": "./",
    "paths": {
      "src/*": ["src/*"]
    }
  }
}
```

Compiled relative paths will point two levels deeper than they should.

## Steps to Reproduce

- Generate a SWC project
- Add the above path mappings
- Add `import { x } from "src/x";`
- Observe compiled path is incorrect

## Cause

- When running the `@nrwl/js:swc` executor, `cwd`  is set to the parent directory of the project
- SWC resolves `baseUrl` relative to `cwd`, resulting in incorrect compiled paths

## Attempted Solution

I have tried changing the behaviour of the swc executor so `cwd` is the project itself, and the input directory is `$PWD`. This results in SWC producing a very different output – `/src` modules are compile into the dist root directory (see https://github.com/swc-project/swc/issues/2092#issuecomment-1053853279 for example).

I cannot find a way to make SWC produce an output where the original directory structure is preserved.

## Workaround

Set `jsc.baseUrl` relative to parent directory:

```diff
{
  "jsc": {
-    "baseUrl": "./",
+    "baseUrl": "./{projectName}",
    "paths": {
      "src/*": ["src/*"]
    }
  }
}
```

**Comment by nartc** [comment]
not stale
