### ISSUE TITLE
nx print-affected with --target does not filter

### ISSUE THREAD

**Issue by mbeckenbach** [nrwl/nx#11645]
## Current Behavior

In my case only 2 of 5 apps have a target "deploy". 

`nx print-affected --type=app --select=projects --target=deploy`

The output lists all 5 apps. 

## Expected Behavior

Only the 2 apps with target deploy should be shown.

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.15.0
   OS   : darwin arm64
   npm  : 8.5.5

   nx : 14.5.7
   @nrwl/angular : 14.5.7
   @nrwl/cypress : 14.5.7
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.7
   @nrwl/eslint-plugin-nx : 14.5.7
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.7
   @nrwl/js : 14.5.7
   @nrwl/linter : 14.5.7
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.4.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.7
   @nrwl/web : 14.5.7
   @nrwl/workspace : 14.5.7
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @ngrx/effects: 14.1.0
   	 @ngrx/entity: 14.1.0
   	 @ngrx/router-store: 14.1.0
   	 @ngrx/store: 14.1.0
   	 @ngrx/store-devtools: 14.1.0
   	 @compodoc/compodoc: 1.1.19
   	 @ngrx/schematics: 14.0.2
   	 @nx-extend/strapi: 2.2.1
   	 @nx-tools/nx-docker: 2.3.0
   	 @twittwer/compodoc: 1.8.0

**Comment by jefflage** [comment]
This is causing me some pain in my CI pipeline, so I plan to work on a PR for this now
