### ISSUE TITLE
What is the environments folder for?

### ISSUE THREAD

**Issue by neilm813** [nrwl/nx#11648]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[environment-variables](https://nx.dev/nx-cloud/reference/env-vars#environment-variables)

### Additional context or description

I expected to find a little information on the `apps/my-app/environments` folder in here. I don't know when to place an env var in there instead of in a local env file.

**Comment by AgentEnder** [comment]
This is a pattern that is common in angular apps, the environment variables on the page you link are unrelated and are system specific variables that should be set in process.env, not one of these files. 

Here is Angular's docs on the environments folder, that should give you a good idea of how to use them: https://angular.io/guide/build#configuring-application-environments
