### ISSUE TITLE
Briefly mention what to put in the apps/my-app/app folder.

### ISSUE THREAD

**Issue by neilm813** [nrwl/nx#11647]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[nx-setup#folder-structure](https://nx.dev/getting-started/nx-setup#folder-structure)

### Additional context or description

I've been confused about what to put inside `apps/my-app` vs what to put inside `apps/my-app/app` because I've seen in a video a CLI command place a generated api controller inside of `apps/my-app` so I'm left wondering what actually to use the `app` folder for.

**Comment by AgentEnder** [comment]
I'm not sure what path you are referring to, as that page doesn't contain the string `apps/my-app/app`. Did a generator create that folder in your workspace?

**Comment by neilm813** [comment]
> I'm not sure what path you are referring to, as that page doesn't contain the string `apps/my-app/app`. Did a generator create that folder in your workspace?

The page doesn't go that deep in the folder structure, I'm describing the generated folder structure for an app inside of `apps`.

I forgot one level in the path, it should be: `apps/name-of-app/src/app`. Is there anywhere in the docs that gives any guidance on when to put files inside `apps/name-of-app/src` vs `apps/name-of-app/src/app`?
