### ISSUE TITLE
TypeError when calling toObservable in convert-nx-executor.ts

### ISSUE THREAD

**Issue by snocorp** [nrwl/nx#11653]
## Current Behavior
Running `ng lint` causes an error in the devkit package of `nx`.

## Expected Behavior
No error to be thrown

The issue is at https://github.com/nrwl/nx/blob/master/packages/devkit/src/utils/convert-nx-executor.ts#L52

`if ((!value as any).next) {` should be `if (!(value as any).next) {` (note the placement of the exclamation mark).

## Steps to Reproduce
I'm not sure this requires steps to reproduce. The code cannot work since any value, whether it had a `next` attribute or not, would fail to satisfy the condition and any value that should have passed the condition would cause the error on line [60](https://github.com/nrwl/nx/blob/master/packages/devkit/src/utils/convert-nx-executor.ts#L60)

I think it would be ideal to have a unit test for this toObservable to avoid this type of issue.

### Failure Logs
```
.../node_modules/@nrwl/devkit/src/utils/convert-nx-executor.js:55
                        .next()
                         ^

TypeError: iterator.next is not a function
    at recurse (/Users/dave/dev/kahi/web-client-app/node_modules/@nrwl/devkit/src/utils/convert-nx-executor.js:55:26)
    at /Users/dave/dev/kahi/web-client-app/node_modules/@nrwl/devkit/src/utils/convert-nx-executor.js:72:17
```

### Environment

 >  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : darwin arm64
   npm  : 6.14.15
   
   nx : 14.5.8
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.8
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : Not Found
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : Not Found
   typescript : 4.6.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 rxjs: 6.5.5
   	 @cypress/schematic: 2.0.2

**Comment by NathanWalker** [comment]
I'm also seeing this (nx 14.5.8) with rxjs 7.5.6 (don't believe rxjs version is a factor here). Just running a standard executor task such as (`yarn nx run appname:clean`)

**Comment by hassanasad** [comment]
Following

**Comment by mlc-mlapis** [comment]
I have the same problem when running `npm run lint <project>`. It ends with the line `All files pass linting.` and then the error is shown.

```
(node:29348) UnhandledPromiseRejectionWarning: TypeError: iterator.next is not a function
    at recurse (C:\Data\WAMP\github\m-eso\node_modules\@nrwl\devkit\src\utils\convert-nx-executor.js:54:26)
    at C:\Data\WAMP\github\m-eso\node_modules\@nrwl\devkit\src\utils\convert-nx-executor.js:71:17
```

Nx : 14.5.8
RxJS: 7.5.6
Angular: 14.1.3
Angular CLI: 14.1.3
NodeJS: 14.17.0
Platform: Windows 10

**Comment by MikaStark** [comment]
The issue is : `(!value).next`
Should be : `!value.next`

**Comment by coyoteecd** [comment]
For anyone else ending up here via Google, the error does not appear with Angular 14.1.2 packages.
So a temporary workaround is to go back to that version until a new `@nrwl/devkit` is released.

**Comment by russcarver** [comment]
I haven't changed my Angular version in a month. It's at 14.1.0 and we suddenly started seeing this error on Friday 8/19/22. Our eslint package is at 8.20.0.

Is it known which 3rd party packages will need updated once this fix is "live"?

**Comment by bolemeus** [comment]
@russcarver I've set the version of @nrwl/cli and @nrwl/devkit to `14.5.4` which seems to have fixed it in my project.

**Comment by AgentEnder** [comment]
The only affected package version with this should be 14.5.8, since 14.5.9 has been released `nx migrate 14.5.9` is the recommended remediation for the bug.

**Comment by mlc-mlapis** [comment]
I can confirm that the bug was effectively eliminated by the fix https://github.com/nrwl/nx/issues/11653

**Comment by Max-LAB** [comment]
Had the same issue, fixed it by updating those devDependencies to a version 14.0.3 in my package.json file

```  json
"devDependencies": {
    "@angular-eslint/builder": "14.0.3",
    "@angular-eslint/eslint-plugin": "14.0.3",
    "@angular-eslint/eslint-plugin-template": "14.0.3",
    "@angular-eslint/schematics": "14.0.3",
    "@angular-eslint/template-parser": "14.0.3",
```
