### ISSUE TITLE
NextJs Custom Server Fails with "Buildable libraries can only depend on other buildable libraries. You must define the build-custom-server target for the following libraries:"

### ISSUE THREAD

**Issue by nsmith7989** [nrwl/nx#11675]
## Current Behavior
When adding a custom server to nextjs application, then adding a library to the nextjs application error is output

> Buildable libraries can only depend on other buildable libraries. You must define the build-custom-server target for the following libraries: <libName>

## Expected Behavior
Should build/serve without error

## Steps to Reproduce
1. Create a new workspace `npx create-nx-workspace --preset=ts`
2. Add `@nrwl/next` plugin `yarn add @nrwl/next --dev`
3. Add nextjs application `yarn nx g @nrwl/next:application app`
4. Add custom server to nextjs app `yarn nx g @nrwl/next:custom-server app`
5. Add a library `yarn nx g @nrwl/react:lib ui --buildable` (for fun make it buildable)
6. Open packages/app/pages/index.tsx and import the ui library created previously
7. Try to serve `app` `yarn nx serve app`
> Error: Buildable libraries can only depend on other buildable libraries. You must define the build-custom-server target for the following libraries: "ui"

Minimal reproduction repo done with above steps: https://github.com/nsmith7989/nx-nextjs-custom-server-repo

### Environment

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.1
   OS   : darwin x64
   yarn : 1.22.18
   
   nx : 14.5.8
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.8
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.8
   @nrwl/eslint-plugin-nx : 14.5.8
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.8
   @nrwl/js : 14.5.8
   @nrwl/linter : 14.5.8
   @nrwl/nest : Not Found
   @nrwl/next : 14.5.8
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.8
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.8
   @nrwl/web : 14.5.8
   @nrwl/workspace : 14.5.8
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

**Comment by jaysoo** [comment]
we'll fix this in the next patch
