### ISSUE TITLE
nestjs compilation - include other files than just main.js

### ISSUE THREAD

**Issue by creadicted** [nrwl/nx#1167]
Hello, 
i use nx and used a nestjs backend in there before you supported it. So thank you for the integration.
What I also love is the second way of compiling  the code with the ``"builder": "@nrwl/builders:node-build"` instead of nodemon. 

## Expected Behavior 
Files that are not importable in to the main.js file are placed in the correct folder structure in the dist files. 

## Current Behavior
The problem I run in to is that the builder creates a single main.js file. So when I use for example typeorm and require migration files to be loaded,  those can not be found because they do not exist in this one file environment anymore. Also with other files. Like XML or json files that I have in my structure. So is there a way how to include those files in the dev compilation step? 

```
dist/app/
      main.js
      migrations/
           234234523456345.migration.js
           928232398232112.migration.js
      otherpath/
           data.js 
           data2.xml
```

**Comment by xmlking** [comment]
may be we could use    ` "assets": ["apps/api/src/assets", "apps/api/src/migrations", "apps/api/src/otherpath"],` in `angular.json`

**Comment by creadicted** [comment]
Thank you @xmlking for taking the time. 
With the assets path I have two problems: 

1. yes the files are included but they are then typescript files and are then not readable by the main.js
2. The files I reference have to be in the project source root. Since I use backend libraries and share them between backends, i have files that I reference to, outside of the main app folder.

**Comment by FrozenPandaz** [comment]
I was playing around with `worker_threads` and ran into similar issues. 

I haven't given this as much thought as I need to but my preliminary solution would be to provide an option for `additionalEntries`. I think inputs to that property would be added to the array of `entries` passed to `webpack`. I think it would solve this use case in a generic way?

**Comment by creadicted** [comment]
@FrozenPandaz : 

> Caveat: I still want main to be a single entry so we know which script to execute during serve
I totally agree

**Comment by maku** [comment]
@creadicted how do you solve your problem?. I would also like to execute some maintenance functionality "ad hoc" but I don't have a good idea how to. (besides providing a REST API and call it)

**Comment by creadicted** [comment]
@maku I used a custom webpack config that extends the default behaviour (if you need help with that let me know and I look the issue up where someone gave me an example) and I used the assets folder.

**Comment by maku** [comment]
@creadicted thank you for responding. I think I will create a new "app" which is only for maintenance func. This should be enough...

**Comment by NailRode** [comment]
I'm having the same issue. Trying to find migrations & seeds from my knexfile and can't find the files, since the builder is building to a single main.js. 
@creadicted could you provide your solution here?

**Comment by maksym-plotnikov** [comment]
+1 with migrations & seeds. Please @creadicted share Your solution :)

**Comment by creadicted** [comment]
in the angular.json you need to add the webpack config:

``` "schematics": {},
      "architect": {
        "build": {
            "webpackConfig": "tools/build/webpack.config.js",
```
In the config file you can define files that should bed added:

```javascript

module.exports = function(config, context) {
  // clean base directory for dist
  const baseDirectory = path.resolve(config.output.path);
  const ormConfigDev = loadConfiguration(config);

  // generate additionalEntries
  const additionalEntries = {
    ...getMigrations(ormConfigDev.migrations)
  };

  // merge entries
  config.entry = {
    ...config.entry,
    ...additionalEntries
  };
 
 //output
  config.output = {
    path: baseDirectory,
    filename: '[name].js',
    libraryTarget: 'commonjs'
  };

  // config.module.rules = newRules;
  return config;
};
```
And a method to generate the file list of migrations based on an ormconfig file. 

```json
{
  "migrations": ["_migrations/dev/*.js", "_seeds/*.js"],
}
```
Here you just can define a method that grabs your files and returns the paths of them. 
Something you have to adjust based on your parameters. 

```javascript
function getMigrations(migrations) {

  // Convert js file names to ts
  migrations = migrations.map(migration => {
    return migration.substr(0, migration.lastIndexOf('.')) + '.ts';
  });

  const additionalEntries = {};

  for (let index = 0; index < migrations.length; index++) {
    const relativePaths = glob.sync(migrations[index], {
      absolute: false
    });

    for (let index = 0; index < relativePaths.length; index++) {
      const relativePath = relativePaths[index];
      const absolutePath = glob.sync(relativePath, {
        absolute: true
      });
      const key = relativePath
        .split('.')
        .slice(0, -1)
        .join('.');
      additionalEntries[key] = absolutePath;
    }
  }
  console.groupEnd();
  return additionalEntries;
}
```

**Comment by nestorvanz** [comment]
I solved this creating a custom command to run TypeScript compiler, you can check the documentation right here: https://nx.dev/angular/workspace/builders/run-commands-builder

Basically I compile the application with `typescript` and then run the `.js` file with node. Here is my make command:

```json
"make": {
  "builder": "@nrwl/workspace:run-commands",
  "options": {
    "commands": [
      {
        "command": "tsc --project apps/my-app/tsconfig.app.json"
      }
    ]
  }
}
```

**Comment by memee** [comment]
> in the angular.json you need to add the webpack config:
> 
> ```
>       "architect": {
>         "build": {
>             "webpackConfig": "tools/build/webpack.config.js",
> ```

For me it was under `architect.build.options.webpackConfig`

**Comment by mopcweb** [comment]
up

**Comment by herbola** [comment]
> @maku I used a custom webpack config that extends the default behaviour (if you need help with that let me know and I look the issue up where someone gave me an example) and I used the assets folder.

yes please

**Comment by itseramin** [comment]
Any workaround for this?

**Comment by Zenyk-Coder** [comment]
> Any workaround for this?

FILE: `custom-webpack.config`
`// Helper for combining webpack config objects
const { merge } = require('webpack-merge')
const path = require('path')

module.exports = (config, context) => {
  const baseDirectory = path.resolve(config.output.path)

  return merge(config, {
    // overwrite values here
    entry: {
      seed: './apps/backend/src/database/seeds/seed.ts',
    },
    output: {
      path: baseDirectory,
      filename: '[name].js',
      libraryTarget: 'commonjs',
    },
  })
}
`
FILE: project.json
`"webpackConfig": "./apps/backend/custom-webpack.config.js"`
