### ISSUE TITLE
ENOENT: no such file or directory, unlink

### ISSUE THREAD

**Issue by B1Z1** [nrwl/nx#11679]
Hi! I updated the application to the 14.5.8 version to fix this issue: https://github.com/nrwl/nx/pull/11595 and it works. But now I'm getting new error every 2-3 builds on hot rebuild

## Current Behavior
ENOENT: no such file or directory, unlink '/Users/illia.mishkin/ppm/ui/node_modules/.cache/nx/latestOutputsHashes/dist-libs-ppm-box-box-application.hash'

## Expected Behavior
No errors on build

## Steps to Reproduce
I'm not sure how it works on the clear repo. But after a cold angular application build, every second hot build (from cache) I'm getting this error. Between builds, I don't change anything

### Failure Logs
 >  NX   Ran target build for project app and 277 task(s) it depends on (3s)

    ✖    0/218 failed
    ✔    218/218 succeeded [218 read from cache]

 >  NX   ENOENT: no such file or directory, unlink '/Users/illia.mishkin/ppm/ui/node_modules/.cache/nx/latestOutputsHashes/dist-libs-ppm-box-box-application.hash'

   Pass --verbose to see the stacktrace.

### Environment

   Node : 16.16.0
   OS   : darwin x64
   yarn : 1.22.4

   nx : 14.5.8
   @nrwl/angular : 14.5.8
   @nrwl/cypress : 14.5.8
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.8
   @nrwl/eslint-plugin-nx : 14.5.8
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.8
   @nrwl/js : 14.5.8
   @nrwl/linter : 14.5.8
   @nrwl/nest : 14.5.8
   @nrwl/next : Not Found
   @nrwl/node : 14.5.8
   @nrwl/nx-cloud : 14.4.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.8
   @nrwl/web : 14.5.8
   @nrwl/workspace : 14.5.8
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @ngneat/transloco: 2.20.1
   	 @ngrx/effects: 12.5.0
   	 @ngrx/entity: 12.4.0
   	 @ngrx/store: 12.5.0
   	 @ngrx/store-devtools: 12.5.0
   	 @rx-angular/cdk: 1.0.0-beta.2
   	 @rx-angular/state: 1.6.0
   	 @rx-angular/template: 1.0.0-beta.32
   	 @storybook/angular: 6.5.10
   	 @testing-library/angular: 11.0.4

**Comment by B1Z1** [comment]
#11595

**Comment by g-cheishvili** [comment]
I had that too, then restarted daemon, cleared cache and everything continued to work.
`nx clear-cache` ?

**Comment by B1Z1** [comment]
@g-cheishvili hi, it doesn't help. After the warm build, I'm getting same error
