### ISSUE TITLE
Can't see dependency line drawn from blog to ascii

### ISSUE THREAD

**Issue by MechanicKim** [nrwl/nx#11672]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/core-tutorial/03-share-assets#tell-nx-about-the-dependencies

### Additional context or description

For the blog project, l added ascii as a dependency in the package.json file.
When I ran 'nx graph, I couldn't see a dependency line drawn from blog to ascii.

<img width="640" alt="184998694-3413d086-e2ae-48f6-b68d-e18fcedd2677" src="https://user-images.githubusercontent.com/12149783/186031213-b95c7882-473e-432b-a346-3e6a2078feae.png">

'ascii' is an asset library just for holding the ASCII asset files. 'blog' references that shared asset file by relative path. So, I think that we should add ascii as an implicit dependency like this.

```
  "nx": {
    "implicitDependencies": ["ascii"]
  }
```

Thanks.

**Comment by isaacplmann** [comment]
This tutorial is no longer linked from the getting started page
