### ISSUE TITLE
Inherit styles duplicated on development environment. NX + craco

### ISSUE THREAD

**Issue by JosepSalvat** [nrwl/nx#11677]
## Current Behavior
For some reason, shared lib styles scss, duplicates every time we call a variable. So in our case it's impossible to work due to the load of css every time that we inspect elements

## Expected Behavior
NX-React should only call once the file of css, not 1000

## Steps to Reproduce

right button, inspect element, see the inheritance classes

We've a repo with 2 apps. Both apps can call variables that are shared on a lib/theme/styles.scss
In styles.scss we've imported typography.scss + variables.scss. They're files containing variables: ex. --grey-3: #e2e2ea;
and then we import them to our own modules.scss with var(--grey-3)

### Failure Logs

![image](https://user-images.githubusercontent.com/88655444/186097476-7aa1c350-d9eb-436d-b21f-ecacd652f640.png)
![image](https://user-images.githubusercontent.com/88655444/186097586-f682d205-0ae5-413e-8e79-997757770f78.png)

### Environment
 nx : 13.4.6
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.3
  @nrwl/cypress : 13.4.3
  @nrwl/devkit : 13.4.3
  @nrwl/eslint-plugin-nx : 13.4.3
  @nrwl/express : undefined
  @nrwl/jest : 13.4.3
  @nrwl/linter : 13.4.3
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : 13.0.2
  @nrwl/react : 13.4.3
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.3
  @nrwl/web : 13.4.3
  @nrwl/workspace : 13.4.3
  @nrwl/storybook : 14.4.3
  @nrwl/gatsby : undefined
  typescript : 4.6.3
  rxjs : 6.5.5
  ---------------------------------------
  Community plugins:
  	 @nrwl/js: 13.4.3
  	 
 
 More things. This only happens on developement mode. On build it works fine, just as expected.
 This is a huge app migrated from React to NX months ago. We didn't notice that until now due to a slow behaviour.
 
 We're using craco and they way that we load the scss into both apps and libs is this way (inside craco.config.js, inside both apps)
 `plugins: [
      {
        plugin: sassResourcesLoader,
        options: {
          resources: [
            '../../libs/theme/src/lib/sass/styles.scss',
          ],
        },
      },
    ],`
    
    
  I really don't know if the problem is craco, nx, or this plugin. Anyone had this issue before?

**Comment by AgentEnder** [comment]
Your install of Nx is a bit outdated, can you try migrating to latest and see if it has been resolved? The command would be `nx migrate latest` followed by `nx migrate --run-migrations`
