### ISSUE TITLE
Allow adding single targets in dependsOn

### ISSUE THREAD

**Issue by DaSchTour** [nrwl/nx#11687]
## Description
Allow adding references to targets as dependsOn for example in the syntax "projectFoo:build".
## Motivation

1. As a possibility to work around https://github.com/nrwl/nx/issues/8065
2. To have a possibility to add implicitDependencies more specific as dependencies in one target to another target

## Suggested Implementation
Should work similar to how dependsOn works now just that instead of the options self and dependencies you can specify dependencies explicitly like with implicitDependencies.

**Comment by AgentEnder** [comment]
This is fixed 🎉, see: #16675, #16674
