### ISSUE TITLE
Integration of NX with Lerna - backward compatibility - inconsistent behavior of 'lerna run --scope'

### ISSUE THREAD

**Issue by ifatregev** [nrwl/nx#11681]
## Current Behavior
After integrating NX to Lerna, using the 'useNx' flag, you can not run lerna using the 'scope' flag without running project dependencies as well. 

## Expected Behavior

Running lerna with 'scope' flag will run only the specified project, without project dependencies. 
Support Lerna existing behaviour.

## Steps to Reproduce

- lerna init
- add two packages (A and B), both with the same "build" command
- make package A depend on B
- run: lerna run --stream --scope A build

```
// nx.json
{
  "extends": "nx/presets/npm.json",
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build"]
      }
    }
  }
}
```
```
// lerna.json
{
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent",
  "useNx": true
}
```

### Failure Logs

" Lerna (powered by Nx)   Running target build for project A and 1 task(s) it depends on"

### Environment

   Node : 16.13.1
   OS   : darwin x64
   yarn : 1.22.10

   nx : 14.5.8
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : Not Found
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : Not Found
   typescript : 4.2.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

**Comment by AlonMiz** [comment]
+1 this refers to this issue by other users
https://github.com/lerna/lerna/issues/3289

**Comment by AgentEnder** [comment]
This issue is covered by the issue on the lerna repo that was linked by @AlonMiz, and is being tracked by it. As such, I'm going to close this out. Feel free to follow up on the linked issue, but it is known by the team already so is not necessary.
