### ISSUE TITLE
Shared libraries (e.g. SharedComponents) are problematic for dep graph analysis

### ISSUE THREAD

**Issue by Merott** [nrwl/nx#1169]
One of the primary benefits of using nx is its ability to statically scan project dependencies and detect affected apps.

What I'm struggling with is how to make that work effectively when dealing with shared libraries that are used in multiple, if not all, apps.

Let's say our monorepo has 10 apps, and we have a `SharedComponentsModule` that is imported by all 10 of them. Let's also say that `SharedComponentsModule` has 100 components inside.

What happens when we need to update a single component in the shared components module? The dependency analysis will conclude that every app has been affected by the change, even if the particular component is only used in one or two apps.

The only way I can think of to avoid that issue is to wrap each component into its own library. That way, each component is isolated enough for the dep graph analysis to detect which apps have been affected by a single change.

Where that solution doesn't work, is when we need to add new components. If we introduce a new library every time that we add a new component, our implicit dependencies (`angular.json`, `nx.json`, and `tsconfig.json`) will be updated every time, and therefore all apps are considered affected.

It's good practice to componentize our applications and break things up into small, reusable components. 

However, having to re-build every app in a monorepo whenever we introduce a new component feels counterintuitive/counterproductive.

What am I missing here?

**Comment by FrozenPandaz** [comment]
Hey, your assessment is correct.

Splitting the components into separate libraries is the way to go. Having everything affected when a project is added is unfortunate.

For `tsconfig.json`, `nx.json` and `angular.json` there are some optimizations we may be able to make in the future? `nx.json` and `angular.json` are relatively implicit but `tsconfig.json` is explicitly extended upon by most projects.

**Comment by Merott** [comment]
Thanks for the quick reply.

The auto-generated changes to `tsconfig.json`, `nx.json` and `angular.json` are predictable, and shouldn't be too difficult to check.

If the only difference is the addition of one or few modules, I don't see how that in itself would affect any of the existing apps/libraries. Or would it?

**Comment by SebasG22** [comment]
Seems like this is the expected behavior because you the file that changes are not related to app-specific-library.
As you said the if there is a change on e.g shared-data-access lib that is a responsible for generic way to handle the data using ngrx. The affected graph will mark the entire workspace like affected. Why ? You must be aware that the change doesn't broke something else.

As you can see here:
![image](https://user-images.githubusercontent.com/17608169/55675629-15be4400-588b-11e9-8444-6105c19b6e18.png)

**Comment by Merott** [comment]
@SebasG22 - Sure, a change in a `shared-data-access` lib would affect any app that uses that lib.

However, introducing a new library doesn't actually affect every app, but only those that import the new library. Currently, nx isn't able to detect that due to implicit dependencies.

I've actually been working on a hack to get around that limitations. It really is a _hack_ but I'll see over time how well it works. If it works well enough, I might as well share it :)

**Comment by atifsyedali** [comment]
@Merott Can you share your hack please? :)

If not, I think I am going to go ahead and implement my suggestion in #1972 as a plugin, where I am going to generate `workspace.json` and `nx.json` from the app- or lib-specific `workspace.json` and `nx.json` files (i.e. generate `/workspace.json` and `/nx.json` from `/apps/app1/nx.json`, `/apps/app2/nx.json`, `/libs/lib1/nx.json`, etc.)

**Comment by atifsyedali** [comment]
I have to mention that on new projects adopting Nx (most) there is bound to be a lot of code churn across all apps and libs, and thus affected becomes less useful.

**Comment by Merott** [comment]
@atifsyedali happy to share it, but with the caveat and disclaimer that it is what it is: **_A HACK_**.

It's a node script, which accepts a `base` argument, and checks if there have been any changes to _existing_ project configurations defined in `tsconfig.json`, `nx.json` or `angular.json`. If all that has changed is _new_ projects added, it will ignore them. Otherwise, it writes the current date to a file called `.nx-hack`.

I've updated the `implicitDependencies` config to only include the `.nx-hack` file:

```json
{
  "implicitDependencies": { ".nx-hack": "*" }
}
```

And here's the script, which I run before using any of the `affected:*` scripts:

```ts
// nx-hack.ts

import { execSync } from 'child_process';
import * as deepDiff from 'deep-diff';
import * as Diff from 'diff';
import * as fs from 'fs';
import * as stripJsonComments from 'strip-json-comments';
import * as yargs from 'yargs';

const argv = yargs.usage('Usage: nx-hack --base [base]').option('base', {
  describe: 'The base to use for affected:* comparisons',
}).argv;

const base = (argv.base as string) || 'latest';

const diff = execSync(`git diff HEAD ${base}`).toString();
const changedFiles = Diff.parsePatch(diff);

const implicitDeps: { [filename: string]: string[] | null } = {
  'angular.json': ['projects'], // only if projects change
  'nx.json': ['projects'], // only if projects change
  'package.json': null, // if anything changes
  'tsconfig.json': ['compilerOptions', 'paths'], // only if compilerOptions or paths change
  'tslint.json': null, // if anything changes
};

const affectedImplicits = changedFiles
  .filter(isModifiedFile)
  .filter(isImplicitDependency)
  .filter(isMoreThanJustNewProject);

if (affectedImplicits.length > 0) {
  console.log('Some key dependencies have changed. Updating .nx-hack!');

  fs.writeFileSync('.nx-hack', Date.now());
}

function isModifiedFile(file: Diff.ParsedDiff) {
  return (
    file.oldFileName &&
    file.oldFileName.startsWith('a/') &&
    file.newFileName &&
    file.newFileName.startsWith('b/') &&
    file.oldFileName.substr(2) === file.newFileName.substr(2)
  );
}

function isImplicitDependency(file: Diff.ParsedDiff) {
  return Object.keys(implicitDeps).includes(file.oldFileName!.substr(2));
}

function isMoreThanJustNewProject(file: Diff.ParsedDiff) {
  const fileName = file.newFileName!.substr(2);
  const fileDiff = execSync(`git diff HEAD ${base} -- ${fileName}`).toString();

  const newFileContent = fs.readFileSync(fileName).toString();
  const oldFileContent = Diff.applyPatch(newFileContent, fileDiff);

  if (!newFileContent || !oldFileContent) return true;

  const newValue = JSON.parse(stripJsonComments(newFileContent));
  const oldValue = JSON.parse(stripJsonComments(oldFileContent));
  const valueDiff = deepDiff.diff(oldValue, newValue);

  if (!valueDiff) return true;

  const keyPath = implicitDeps[fileName];

  return keyPath
    ? valueDiff.some(keyDiff => !isJustNewKeyInPath(keyDiff, keyPath))
    : valueDiff.length > 0;
}

function isJustNewKeyInPath<T>(
  keyDiff: deepDiff.Diff<T, T>,
  pathToKey: string[],
) {
  return (
    keyDiff.kind === 'N' &&
    !!keyDiff.path &&
    keyDiff.path.length === pathToKey.length + 1 &&
    pathToKey.every((key, index) => keyDiff.path![index] === key)
  );
}

```

**Comment by rarmatei** [comment]
Related issue #3033 

This specific issue has been inactive for a while - can you please check out the above related issue, update to the newest version Nx, and if this is still a problem, create a new issue, please? 

Closing for now.
