### ISSUE TITLE
Plans for providing an minimal example app with every lib for e2e testing

### ISSUE THREAD

**Issue by nvdnkpr** [nrwl/nx#117]
Are there any plans to provide a minimal example setup (`index.html`, `app.ts`, `main.ts`) that loads a component when you run `ng serve` in a lib ?
Currently when you run `ng serve` in a lib (it's allowed from an ng-cli's perspective since libs are apps)
it stops with an error since index.html is missing.

**Comment by sean-perkins** [comment]
This doesn't seem like a use-case that many would need. Why not just create a "demo" app that pulls in your libs for testing? I know in my NX set-up, a lot of the libs are either themes (sass), ngrx logic for my app, or some abstract code I want to split away from my primary code-base (and possibly share to another app later).

**Comment by vsavkin** [comment]
@nvdnkpr in many cases, that's just impossible to do. Many libraries require some env to run inside of. If your library uses NgRx, you must have `StoreModule.forRoot` configured somewhere. If you use the router, you must have `RouterModule.forRoot` configured somewhere. 

But I'm thinking about adding a schematic generating some sort of playground app to make building independent components easier.

Closing this issue
