### ISSUE TITLE
Support for Angular Single File Components when Generating Angular Libraries with Standalone Components Support

### ISSUE THREAD

**Issue by mainawycliffe** [nrwl/nx#11702]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md)) - Would need some guidance.

## Description

When generating an angular lib that uses a standalone component (`--standalone`), it would be great if the components generated could be single file components (`--inlineStyle` and `--inlineTemplate`).

## Motivation

At the moment, if I want to use Single File Components, I have to generate an angular lib with `--standalone` flag, then manually configure the component generated as Single File Component. This would save me and others who might want to do this the pain.

## Suggested Implementation

During the generation of the angular lib, we could read the configurations from `@nrwl/angular:component` nx schema (or CLI flags) and use those to decide the kind of component to generate with the library.

**Comment by e-oz** [comment]
You can do it already.
In nx.json, to "generators", add:

```json

    "@nrwl/angular:component": {
      "style": "scss",
      "changeDetection": "OnPush",
      "displayBlock": true,
      "standalone": true,
      "inlineTemplate": true,
      "inlineStyle": true
    }
```

and then `nx g c my-component` will generate exactly what you want.

**Comment by mainawycliffe** [comment]
This works when you are generating a normal component; a library with the standalone flag i.e., `npx nx g @nrwl/angular:library home --standalone` support generates multiple files per component. So, in this case, I have to convert to inline style and template manually.

**Comment by e-oz** [comment]
`@nrwl/angular:library home` should not generate components at all, it should generate the library itself only. Sorry, looks like I don't understand you.

**Comment by mainawycliffe** [comment]
When you are generating a lib with NgModules, that's the case; it doesn't contain any component. For standalone component-based libs, the lib has a component, which is exported by default. Below is a screenshot of what is generated by the following command: `npx nx g @nrwl/angular:library test --standalone `
![image](https://user-images.githubusercontent.com/12270550/186506708-6f861c84-02f0-471d-8414-d7ef533c4002.png)
