### ISSUE TITLE
Running affected --target causes cacheable operation to not work

### ISSUE THREAD

**Issue by ureciocais** [nrwl/nx#11703]
I'm running a task (tsCheck) on github, using DTE. I'm not getting the output from the agents into the main job when it fails.
If I go and check the run on nx, I see this: 
![Screenshot 2022-08-24 at 12 35 26](https://user-images.githubusercontent.com/104901556/186397861-0ce31f98-bbc3-43cb-9e84-02921c5b2f84.png)
I believe it might be because of using --target=, but not sure.
We run the command like this `yarn nx affected --target=tsCheck --base=remotes/origin/main --head=HEAD`

## Current Behavior

NX not sending the output back to the main job of the workflow + run fails

## Expected Behavior

NX sends output back, command is successful and tsCheck is a cacheable operation when using --target=

I think so

## Steps to Reproduce

Run a task using --target, with DTE enabled on github

**Comment by AgentEnder** [comment]
Can you paste `nx report`'s output here?

**Comment by ureciocais** [comment]
@AgentEnder sure, here it is:
```
Node : 16.15.0
   OS   : linux x64
   yarn : 1.22.19
   
   nx : [14](https://github.com/cais-group/monorepo/runs/8092007303?check_suite_focus=true#step:5:15).5.8
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.8
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.8
   @nrwl/eslint-plugin-nx : 14.5.8
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.8
   @nrwl/js : 14.5.8
   @nrwl/linter : 14.5.8
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.5.8
   @nrwl/nx-cloud : 14.4.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.8
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.8
   @nrwl/web : 14.5.8
   @nrwl/workspace : 14.5.8
   typescript : 4.4.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by StalkAltan** [comment]
Hi @ureciocais !

Can you send an email to `cloud-support@nrwl.io` with a link to one of your runs, as well as the content of your nx.json, and the target configuration for one (or a few) of your projects with the `tsCheck` target? We can take a look

**Comment by ureciocais** [comment]
Sure @StalkAltan. Thank you

**Comment by ureciocais** [comment]
Hi @StalkAltan, did you see my email? Best

**Comment by StalkAltan** [comment]
Hi @ureciocais, apologies. We have replied now!

**Comment by StalkAltan** [comment]
Closing this issue as it was resolved via support channels.

If you are using a custom executor and Nx is not picking up output from a spawned child process, make sure that you have a property called `outputCapture` defined in your executor's schema.json. 

schema.json
```
{
  ...other props,
  "outputCapture": "pipe"
}
```

We are working on improving the defaults as well as our documentation around this behavior.
