### ISSUE TITLE
@nrwl/next >= 14.5.5 breaks compatibility with react@17

### ISSUE THREAD

**Issue by harvestnide** [nrwl/nx#11717]
Enabling `__NEXT_REACT_ROOT` by default breaks compatibility with react@17 - when called through `@nrwl/next:build` next tries to load `react-dom/client`, which is available only in `react-dom@^18`

Next just [checks](https://github.com/vercel/next.js/blob/8958867d91a1bea621ad3a00a8c556529aa3c3a9/packages/next/client/index.tsx#L38-L40) if env var is present, and new build executor sets it to `true` if it's not present - hence it cannot be fixed by local env config override.

Supporting something like `__NEXT_REACT_ROOT=false` by `@nrwl/next:build` would solve this issue, but would be confusing

Introduced in #11362

**Comment by Miikis** [comment]
@harvestnide i think this is the same issue as #11609, which _should_ have been resolved w/ #11656 — but it's not:

@AgentEnder @puku0x @jaysoo the `__NEXT_REACT_ROOT` env var needs to be unset for `react@^17`. Instead, [here](https://github.com/nrwl/nx/pull/11656/files#diff-fcd96d0c9996c7987e1c72da9391cb2d845b36ab056886d02511dea284371c5dR34), it is set to the string `'undefined'`.

That line should either be an `if` statement or the `__NEXT_REACT_ROOT` property should be `delete`d from `process.env`.

**Comment by puku0x** [comment]
@Miikis I see. Thank you for your advice. https://github.com/nrwl/nx/pull/11749

**Comment by harvestnide** [comment]
Awesome, thanks for your time

I wasn't aware that validating dependency version inside executors is a thing 🤔
