### ISSUE TITLE
Tutorial is missing a step concerning the 'workspace.json'-file

### ISSUE THREAD

**Issue by deannabosschert** [nrwl/nx#11718]
### Documentation issue
- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

In the documentation, it states to start the tutorial by running:

```bash
npx create-nx-workspace@latest
```

However, this also creates the `workspace.json`-file containing this:
```json
{
  "$schema": "./node_modules/nx/schemas/workspace-schema.json",
  "version": 2,
  "projects": {}
}
```

This file doesn't include the _blog_ project yet, causing the next step to fail when trying to run 
```bash
nx serve blog
```

, causing this error:

```bash
 >  NX   Cannot find project 'blog'
```

When the workspace.json-file is removed, the serve command executes fine though.

### Is there a specific documentation page you are reporting?
[https://nx.dev/core-tutorial/01-create-blog](https://nx.dev/core-tutorial/01-create-blog)

### Additional context or description
Another step could be added to the docs; either removing the workspace.json file for now, or adding the blog project to it as well.

**Comment by isaacplmann** [comment]
create-nx-workspace no longer creates a workspace.json file.  And this tutorial has been updated
