### ISSUE TITLE
Migration script split-create-tree for migrate from nx@13.8.1 to nx@14.5.10

### ISSUE THREAD

**Issue by gerardcastell** [nrwl/nx#11716]
## Current Behavior

When migrating from from nx@13.8.1 to nx@14.5.10 there is a script in the migrations.json which I am attaching below that fails:
`    {
      "version": "14.2.0-beta.0",
      "description": "Adjusts calls to createTreeWithEmptyWorkspace to reflect new API",
      "factory": "./src/migrations/update-14-2-0/split-create-empty-tree",
      "package": "@nrwl/devkit",
      "name": "split-create-tree"
    },`

The error in verbose mode is the following:
![Screenshot 2022-08-25 at 09 33 40](https://user-images.githubusercontent.com/25346175/186603604-c9db0918-8d03-41f4-86e4-97901cc359ec.png)

## Expected Behavior

If I remove this statement from the migrations.json the command `nx migrate --run-migrations --verbose` the migrations succeed.

I do not know if you can provide something of information about what pursuits that script and if it is totally mandatory for the migration because I do not know if I can skip this step and migrate properly to the latest version. Thanks in advance!

### Environment

 Node : 14.18.1
   OS   : darwin x64
   npm  : 6.14.15

   nx : 14.5.10
   @nrwl/angular : 14.5.10
   @nrwl/cypress : 14.5.10
   @nrwl/detox : 14.5.10
   @nrwl/devkit : 14.5.10
   @nrwl/eslint-plugin-nx : 14.5.10
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.10
   @nrwl/js : 14.5.10
   @nrwl/linter : 14.5.10
   @nrwl/nest : 14.5.10
   @nrwl/next : Not Found
   @nrwl/node : 14.5.10
   @nrwl/nx-cloud : 14.5.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.10
   @nrwl/react-native : 14.5.10
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.10
   @nrwl/web : 14.5.10
   @nrwl/workspace : 14.5.10
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @ng-bootstrap/ng-bootstrap: 10.0.0
   	 @ngrx/component-store: 14.0.2
   	 @ngrx/effects: 14.0.2
   	 @ngrx/entity: 14.0.2
   	 @ngrx/router-store: 14.0.2
   	 @ngrx/store: 14.0.2
   	 ngx-bootstrap: 8.0.0
   	 ngx-spinner: 12.0.0
   	 @fortawesome/angular-fontawesome: 0.10.1
   	 @ngrx/schematics: 14.0.2
   	 @ngrx/store-devtools: 14.0.2
   	 @nguniversal/builders: 13.1.1

**Comment by AgentEnder** [comment]
Fixed in #11736

**Comment by gerardcastell** [comment]
Hi @AgentEnder ! When is this ticket supposed to be released? Thanks !
