### ISSUE TITLE
Failing Storybook build

### ISSUE THREAD

**Issue by davidslaby** [nrwl/nx#11711]
## Current Behavior
Getting error during build phase - `ERR! => Failed to build the preview`
`NX   Module not found: Error: Can't resolve '../_isolated-hnrs/dist/emotion-react-_isolated-hnrs.browser.esm.js'`

## Expected Behavior
Build without errors

## Steps to Reproduce
Try to build Storybook on Windows (MacOS without any troubles) after upgrade of `@emotion/react` package to version `11.10.0` build is failing (working after downgrade to `11.9.3`)

I assume it's caused by absence of dependencies

```
yarn.lock
@emotion/react@11.9.3":
  version "11.9.3"
  dependencies:
    "@babel/runtime" "^7.13.10"
    "@emotion/babel-plugin" "^11.7.1"
    "@emotion/cache" "^11.9.3"
    "@emotion/serialize" "^1.0.4"
    "@emotion/utils" "^1.1.0"
    "@emotion/weak-memoize" "^0.2.5"
    hoist-non-react-statics "^3.3.1"
```
Especially babel-plugin

### Failure Logs
See above

### Environment
```
Node : 14.18.0
   OS   : darwin x64
   yarn : 1.22.10
   
   nx : 14.5.10
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.10
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.10
   @nrwl/eslint-plugin-nx : 14.5.10
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.10
   @nrwl/js : 14.5.10
   @nrwl/linter : 14.5.10
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.10
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.10
   @nrwl/web : 14.5.10
   @nrwl/workspace : 14.5.10
   typescript : 4.7.4
   --------------------------
```

**Comment by peter-coastpay-com** [comment]
im having the same issue

**Comment by mandarini** [comment]
Hi @davidslaby , thanks for filing an issue. If you keep the version to `11.10.0`, and you add `babel-plugin`, does it work? I have not worked much with `@emotion/react`, would it be easy for you to create a reproduction repository for me, so that I can reproduce this locally?

**Comment by twfarland** [comment]
I had the same issue on a fresh nx workspace on windows 10. To reproduce, set up a fresh workspace with emotion, react, and storybook.

**Comment by mandarini** [comment]
I see @twfarland ! Since I am not super experienced with `@emotion/react`, could you please create that reproduction repository for me if it's not too much trouble and share it with me? I'll do my best to help you out! :)

**Comment by igor-co** [comment]
Same issue. 
Fresh nx workspace with react library, emotion and storybook

**Comment by igor-co** [comment]
> I see @twfarland ! Since I am not super experienced with `@emotion/react`, could you please create that reproduction repository for me if it's not too much trouble and share it with me? I'll do my best to help you out! :)

You do not need any experience with emotion.  Just make a fresh repo. I have described that issue on stackoverflow
https://stackoverflow.com/questions/73833642/nx-monorepo-react-library-storybook-does-not-start

**Comment by mandarini** [comment]
Ahhhhhh sorry I just realized we're talking about Windows. Silly me. I'll get back to you again on that, sorry!

**Comment by mandarini** [comment]
Ahhh I see. So the issue is on `@emotion/react`, and not on Nx?

**Comment by davidslaby** [comment]
@mandarini exactly 🙂 Thank you for support!

**Comment by igor-co** [comment]
> Downgrade of `@emotion/react` from version `11.10.4` to `11.9.3` should solve this issue. There is some issue with imports and `/` on Windows.

Thanks a lot! Downgrading worked just fine
