### ISSUE TITLE
Angular tests are much slower since upgrade NX from 13 to 14

### ISSUE THREAD

**Issue by rique-dev** [nrwl/nx#11715]
## Current Behavior

We recently migrated our NX workspace from v13.0.2 to v14.5.10, but we noticed that our angular unit tests are extremely slow, both local and Github Actions (our CI/CD). Some tests here 3x up the execution time.

This same behavior happens in a clean NX workspace v14, see below

| nx 14  | nx 13 |
| ------ | ----- |
|  ![Image](https://user-images.githubusercontent.com/11713190/186512075-4e9f9b02-4b46-4e82-af70-54ae1445b176.png)  |  ![Image](https://user-images.githubusercontent.com/11713190/186511969-3283bd59-0d89-4cb3-862c-0ee1d9919e36.png)  |
| ![image](https://user-images.githubusercontent.com/11713190/186570171-0d8eb394-1f3b-440a-ac03-95a6d42c4a17.png) | ![image](https://user-images.githubusercontent.com/11713190/186570227-0535ce7c-b540-45bd-b068-175fc79af671.png) |

## Expected Behavior

We expected same execution time or more faster

## Steps to Reproduce

1. create nx 14 workspace with Angular app
2. create 3 buildable lib
3. `npx nx run-many --target=test`

I've made sample repo to demonstrate the problem

- [13.0.2](https://github.com/rique-dev/nx-13.0.2-angular-with-slow-test)
- [14.5.10](https://github.com/rique-dev/nx-14.5.10-angular-with-slow-test)

The results CI is same of prints above.

- [Github Actions with NX 13.0.2](https://github.com/rique-dev/nx-13.0.2-angular-with-slow-test/runs/8002931685?check_suite_focus=true)
- [Github Actions with NX 14.5.10](https://github.com/rique-dev/nx-14.5.10-angular-with-slow-test/runs/8002705708?check_suite_focus=true) 

### Environment

```
   Node : 16.17.0
   OS   : darwin x64 (ubuntu-20.04)
   npm : 8.15.0
   
   nx : 14.5.10
   @nrwl/angular : 14.5.10
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.10
   @nrwl/eslint-plugin-nx : 14.5.10
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.10
   @nrwl/js : Not Found
   @nrwl/linter : 14.5.10
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.5.10
   typescript : 4.7.2
   --------------------------
```

### Others (Our workaround)

We did many tests to circumvent this situation, but still tests are very slow. We are adding [`esbuild`](https://esbuild.github.io/) and changing our configs jest (`jest.config.ts`) adding this config:

```ts
globals: {
        'ts-jest': {
            isolatedModules: true,
```

**Comment by barbados-clemens** [comment]
Okay his is mainly because in angular only ships ESM code as of ng v13 onward. So all the @angular/* deps have to be transpiled by jest preset angular since jest ESM support is lacking. 

I am working on changes to hopefully improve performance mainly through jests caching mechanisms but nothing concrete as of yet.
