### ISSUE TITLE
NX does not run all the tests in a project

### ISSUE THREAD

**Issue by peter-coastpay-com** [nrwl/nx#11714]
Using the latest version of NX

## Current Behavior
after migrating from CRA to NX,  I am trying to run all the tests in my project from the NX project root:

`yarn nx run-many --all --target=test --skip-nx-cache --verbose`

I see that 590 tests have run and passed.

but in the original CRA project, there are 882 tests. 

I can see in the test output that many tests have not run at all. 

## Expected Behavior

I expect all the tests to run,  not just a subset.

**Comment by barbados-clemens** [comment]
closing as you already have an open issue for testing with CRA -> nx migration #11589
