### ISSUE TITLE
storybook stories fail if component is imported from shared library

### ISSUE THREAD

**Issue by peter-coastpay-com** [nrwl/nx#11728]
I am trying to import a component from a shared library into storybook,  but this is failing. 

i see this error message about not being able to resolve the path to the module: 

` src/general/inputs/formik-phone-field/FormikPhoneField.tsx
ERR!   Line 1:25:  Unable to resolve path to module '@coast-workspace/general'  import/no-unresolved`

`❯ npx nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.7.0
   OS   : darwin arm64
   yarn : 1.22.19

   nx : 14.5.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.4
   @nrwl/eslint-plugin-nx : 14.5.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.4
   @nrwl/js : 14.5.4
   @nrwl/linter : 14.5.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.5.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.4
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.10
   @nrwl/web : 14.5.4
   @nrwl/workspace : 14.5.4
   typescript : 4.5.5
   ---------------------------------------
   Community plugins:`

**Comment by mandarini** [comment]
Hi there @peter-coastpay-com ! Thank you very much for filing an issue! Unfortunately, I do not have enough information to help you out. Can you please try to create a minimum reproduction repository and share it with me?

**Comment by mandarini** [comment]
Hi there @peter-coastpay-com ! Did you get a chance to look into this more and give me some more information? I'd love to help you out!

**Comment by peter-coastpay-com** [comment]
The issues seems like storybook was not configured to be able to import components from outside of it's project directory. This is probably because I migrated to NX from a CRA project. 

I was able to get this working by adding this to .storybook/main.js 

`  webpackFinal: async (config, { configType }) => {
    // apply any global webpack configs that might have been specified in .storybook/main.js
    if (rootMain.webpackFinal) {
      config = await rootMain.webpackFinal(config, { configType });
    }

    // Remove guard against importing modules outside of `src`.
    // Needed for workspace projects.
    config.resolve.plugins = config.resolve.plugins.filter(
      (plugin) => !(plugin instanceof ModuleScopePlugin)
    );

    // Add support for importing workspace projects.
    config.resolve.plugins.push(
      new TsConfigPathsPlugin({
        configFile: path.resolve(__dirname, 'tsconfig.json'),
        extensions: ['.ts', '.tsx', '.js', '.jsx'],
        mainFields: ['module', 'main'],
      })
    );

    // Replace include option for babel loader with exclude
    // so babel will handle workspace projects as well.
    config.module.rules[5].oneOf.forEach((r) => {
      if (r.loader && r.loader.indexOf('babel') !== -1) {
        r.exclude = /node_modules/;
        delete r.include;
      }
    });

    return config;
  },`

**Comment by mandarini** [comment]
Ohhh I see. I'm so glad you managed to solve this issue! :)
