### ISSUE TITLE
Core Tutorial - Automatic Dependency Detection isn't working

### ISSUE THREAD

**Issue by justingish** [nrwl/nx#11726]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/core-tutorial/05-auto-detect-dependencies

### Additional context or description

The dependency auto-detection isn't working. I followed the tutorial and I got the cow app to work, but when I run nx graph, there is no line between the `cow` and `messages` projects.  A similar problem happened on Step 3 of the tutorial about sharing assets, but someone else had already reported that issue and shared a workaround using implicitDependencies.

**Comment by Mikoz93** [comment]
Try explicitly setting this in the `nx.json`:
```
 "pluginsConfig": {
    "@nrwl/js": {
      "analyzeSourceFiles": true
    }
  }
```

**Comment by AgentEnder** [comment]
Closing this, as its explicitly stated in the tutorial now.
