### ISSUE TITLE
Fresh workspace has Jasmine Types in tsconfig.tools.json file

### ISSUE THREAD

**Issue by ZackDeRose** [nrwl/nx#1173]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Should not expect Jasmine as test-runner for tools.

## Current Behavior

Adds jasmine as a compilerOptions.types in tools/tsconfig.tools.json.

### Steps to Reproduce

1. create an nx workspace `create-nx-workspace for-jasmine-bug`

### Context

Please provide any relevant information about your setup:

- version of Nx used - 7.7.0
- version of Angular CLI used - ~7.2.2
- version of Angular DevKit used - ^0.13.2

**Comment by mehrad-rafigh** [comment]
@FrozenPandaz @vsavkin This issue can be closed. This is no longer the case. It tried it with Nx@8.4.13
