### ISSUE TITLE
List and Document all `NX_*` environment variables part of the public API

### ISSUE THREAD

**Issue by tinesoft** [nrwl/nx#11731]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

Nx uses a lot of environment  variables internally, that change its behaviour based on whether or not  they are set.

For example:
* `NX_VERBOSE`
* `NX_CACHE_DIRECTORY`
* `NX_STREAM_OUTPUT`
* etc

Some of them, are pretty self-explanatory (like NX_VERBOSE, that allows more detailed logging when executing a Nx command). Others are harder to guess what they do...

A new page can be added in the docs, to list all of those variables (at least those that can be considered "public API"), and document them.

### Additional context or description
FYI, there is this existing page: https://github.com/nrwl/nx/blob/master/docs/shared/guides/environment-variables.md
But it is more about how to use/define __user environment variables__ in a Nx application, not about Nx own env variables.

**Comment by isaacplmann** [comment]
There is this page: https://nx.dev/reference/environment-variables

But it doesn't include NX_STREAM_OUTPUT.  I'll leave this open until we add that.

**Comment by isaacplmann** [comment]
NX_STREAM_OUTPUT is an internal variable that was intentionally undocumented.
