### ISSUE TITLE
Caching docs confusing

### ISSUE THREAD

**Issue by joeldbirch** [nrwl/nx#11730]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

[Caching / what is cached](https://nx.dev/using-nx/caching#what-is-cached)

### Additional context or description

I'm trying to figure out why outputs are not being cached and this section is confusing. The code-block doesn't seem to have enough context.

- Where does that code live?
- What is the `architect` property?
- How many of those other properties are required in addition to the `outputs` property? 
- "Nx also caches the files generated by a command. The list of folders is listed in the outputs property." <-- is this done by NX, or is it a something we need to set up?

Thank you.

**Comment by isaacplmann** [comment]
This section has been updated since this issue was raised.  Closing this issue.  Please reopen, if the docs are still confusing.
