### ISSUE TITLE
nestjs prod build fail due to externalDependencies

### ISSUE THREAD

**Issue by xmlking** [nrwl/nx#1174]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior
sample project : https://github.com/xmlking/ngx-starter-kit

`ng build api --prod` should work without warnings and errors

## Current Behavior

`ng build api ` works but   `ng build api --prod` throw following error

> PS: if I remove `"externalDependencies": "none"` from `angular.json` `api` project, it works
 
```
WARNING in ./node_modules/ws/lib/validation.js
Module not found: Error: Can't resolve 'utf-8-validate' in '/Developer/Work/SPA/ngx-starter-kit/node_modules/ws/lib'
 @ ./node_modules/ws/lib/validation.js
 @ ./node_modules/ws/lib/sender.js
 @ ./node_modules/ws/index.js
 @ ./node_modules/engine.io/lib/server.js
 @ ./node_modules/engine.io/lib/engine.io.js
 @ ./node_modules/socket.io/lib/index.js
 @ ./apps/api/src/app/shared/eventbus.gateway.ts
 @ ./apps/api/src/app/shared/index.ts
 @ ./apps/api/src/app/user/user.module.ts
 @ ./apps/api/src/app/user/index.ts
 @ ./apps/api/src/app/app.module.ts
 @ ./apps/api/src/main.ts
 @ multi ./apps/api/src/main.ts

ERROR in ./node_modules/got/index.js
Module not found: Error: Can't resolve 'electron' in '/Developer/Work/SPA/ngx-starter-kit/node_modules/got'
 @ ./node_modules/got/index.js 75:29-48
 @ ./node_modules/openid-client/lib/helpers/http.js
 @ ./node_modules/openid-client/lib/issuer.js
 @ ./node_modules/openid-client/lib/index.js
 @ ./node_modules/kubernetes-client/lib/auth-providers/openid.js
 @ ./node_modules/kubernetes-client/lib/auth-providers sync ^\.\/.*\.js$
 @ ./node_modules/kubernetes-client/lib/backends/request.js
 @ ./node_modules/kubernetes-client/lib/swagger-client.js
 @ ./node_modules/kubernetes-client/lib/index.js
 @ ./apps/api/src/app/project/kubernetes/kubernetes.service.ts
 @ ./apps/api/src/app/project/project.module.ts
 @ ./apps/api/src/app/project/index.ts
 @ ./apps/api/src/app/app.module.ts
 @ ./apps/api/src/main.ts
 @ multi ./apps/api/src/main.ts

ERROR in ./node_modules/pg/lib/native/client.js
Module not found: Error: Can't resolve 'pg-native' in '/Developer/Work/SPA/ngx-starter-kit/node_modules/pg/lib/native'
 @ ./node_modules/pg/lib/native/client.js 9:13-33
 @ ./node_modules/pg/lib/native/index.js
 @ ./node_modules/pg/lib/index.js
 @ ./node_modules/typeorm/platform/PlatformTools.js
 @ ./node_modules/typeorm/entity-manager/MongoEntityManager.js
 @ ./node_modules/typeorm/index.js
 @ ./apps/api/src/app/auth/auth.service.ts
 @ ./apps/api/src/app/auth/index.ts
 @ ./apps/api/src/app/app.module.ts
 @ ./apps/api/src/main.ts
 @ multi ./apps/api/src/main.ts

ERROR in ./node_modules/engine.io/lib/server.js
Module not found: Error: Can't resolve 'uws' in '/Developer/Work/SPA/ngx-starter-kit/node_modules/engine.io/lib'
 @ ./node_modules/engine.io/lib/server.js 90:23-37
 @ ./node_modules/engine.io/lib/engine.io.js
 @ ./node_modules/socket.io/lib/index.js
 @ ./apps/api/src/app/shared/eventbus.gateway.ts
 @ ./apps/api/src/app/shared/index.ts
 @ ./apps/api/src/app/user/user.module.ts
 @ ./apps/api/src/app/user/index.ts
 @ ./apps/api/src/app/app.module.ts
 @ ./apps/api/src/main.ts
 @ multi ./apps/api/src/main.ts

ERROR in ./node_modules/sharp/build/Release/sharp.node 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/sharp/lib/utility.js 3:14-52
 @ ./node_modules/sharp/lib/index.js
 @ ./apps/api/src/app/user/profile/profile.service.ts
 @ ./apps/api/src/app/user/user.module.ts
 @ ./apps/api/src/app/user/index.ts
 @ ./apps/api/src/app/app.module.ts
 @ ./apps/api/src/main.ts
 @ multi ./apps/api/src/main.ts
```
 

 

### Context

sample project : https://github.com/xmlking/ngx-starter-kit

Please provide any relevant information about your setup:

- version of Nx used
- version of Angular CLI used
- `angular.json` configuration
- version of Angular DevKit used
- 3rd-party libraries and their versions
- and most importantly - a use-case that fails

**A minimal reproduce scenario using allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

Please include any relevant log snippets or files here.

## Other

Any other relevant information that will help us help you.

**Comment by xmlking** [comment]
this could be reproduces with 
```
npx create-nx-workspace myorg --preset="full-stack"
ng build api --prod
```

**Comment by ZenSoftware** [comment]
I am encountering this problem as well.  After running `ng update @nrwl/schematics` going from **7.6.2** to **7.7.1**.  A bare-bones NestJS app with the `--prod` flag does not compile.

### Does Not Compile

- NestJS app with `--prod`

### Compiles

- NestJS app without `--prod`
- Angular app with `--prod`
- Angular app without `--prod`

### System

- Node.js **10.15.3**
- @nrwl/nx@**7.7.1**
- @nestjs/core@**5.7.4**
- @angular/core@**7.2.9**
- @angular/cli@**7.3.6**
- @angular-devkit/build-angular@**0.13.6**
```
$ ng build --project=api --prod

Starting type checking service...
Using 6 workers with 2048MB memory limit

<--- Last few GCs --->

[20231:0x3829ab0]   155794 ms: Mark-sweep 1378.5 (1423.6) -> 1378.2 (1425.1) MB, 535.0 / 0.0 ms  (average mu = 0.110, current mu = 0.005) allocation failure scavenge might not succeed
[20231:0x3829ab0]   156337 ms: Mark-sweep 1378.3 (1425.1) -> 1378.3 (1424.6) MB, 542.6 / 0.0 ms  (average mu = 0.058, current mu = 0.001) allocation failure GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x3ed97135be1d]
Security context: 0x2d1967d9e6e9 <JSObject>
    1: _replaceInStringNode [0x2a62b97678f9] [/home/z/Work/tuspeak/node_modules/webpack-sources/lib/ReplaceSource.js:~197] [pc=0x3ed973588985](this=0x2a3bdeac74d1 <Source map = 0x505a152e309>,output=0x2a0ae6f1fd51 <JSArray[869461]>,replace=0x2a0ae6f1fd71 <ReplacementEnumerator map = 0x81e59cfc331>,getOriginalSource=0x1ec4918540b1 <JSFunction getOriginalSourc...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8dc510 node::Abort() [ng build --project=api --prod]
 2: 0x8dc55c  [ng build --project=api --prod]
 3: 0xad9b5e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [ng build --project=api --prod]
 4: 0xad9d94 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [ng build --project=api --prod]
 5: 0xec7bf2  [ng build --project=api --prod]
 6: 0xec7cf8 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [ng build --project=api --prod]
 7: 0xed3dd2 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [ng build --project=api --prod]
 8: 0xed4704 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [ng build --project=api --prod]
 9: 0xed7371 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [ng build --project=api --prod]
10: 0xea0466 v8::internal::Factory::AllocateRawArray(int, v8::internal::PretenureFlag) [ng build --project=api --prod]
11: 0xea0cea v8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Heap::RootListIndex, int, v8::internal::Object*, v8::internal::PretenureFlag) [ng build --project=api --prod]
12: 0xea12a7 v8::internal::Factory::NewUninitializedFixedArray(int, v8::internal::PretenureFlag) [ng build --project=api --prod]
13: 0xe5462f  [ng build --project=api --prod]
14: 0x10fa57d v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [ng build --project=api --prod]
15: 0x3ed97135be1d 
fish: “ng build --project=api --prod” terminated by signal SIGABRT (Abort)
```

**Comment by ZenSoftware** [comment]
There seems to be issues with a bare-bones nx project using nestjs@6.0.0 as well.  I submitted an issue in the nest repo here: https://github.com/nestjs/nest/issues/1706

Minimum reproduction can be found here: [Nx & nestjs@6.0.0 bug reproduction](https://github.com/ZenSoftware/nx-nest)

**Comment by xmlking** [comment]
may be `nx` provide  noWebPack option (`ng build api --noWebPack --prod`)  for node projects.
WebPack bundles   has no really benefit for server-side apps and some times, not compatible well with some frameworks (e.g, typeorm migrations etc)

**Comment by ZenSoftware** [comment]
It would be nice if there was a no webpack option.  I'm not sure if there is.  The `--prod` flag is usually only used to indicate that we want to use the `environments.prod.ts` file during the compilation of server side Node apps.

**Comment by ZenSoftware** [comment]
@xmlking 
From: https://github.com/nestjs/nest/issues/1706
> After spending a few hours on this, I have found the root of the problem!<br>
> `ng build --prod` is equivalent to `ng build --configuration=production`.  @angular/cli looks for the configuration named `production` in the `angular.json` file under `architect.configurations`.  Here is the scaffolded Nest configuration produced by Nx:
> 
> ```
> "architect": {
>   "configurations": {
>     "production": {
>       "optimization": true,
>       "extractLicenses": true,
>       "inspect": false,
>       "fileReplacements": [
>       {
>         "replace": "apps/api/src/environments/environment.ts",
>         "with": "apps/api/src/environments/environment.prod.ts"
>       }
>       ],
>       "externalDependencies": "none"
>     }
>   }
> }
> ```
> 
> I believe removing the line `"externalDependencies": "none"` skips the webpack tree shaking processing.  It compiles fine if you remove that line from the configuration.  
> 
> @FrozenPandaz Fortunately server side build sizes are not important for most scenarios.  Would it be possible to make a change to Nx so that `"externalDependencies": "none"` is not included in the scaffolding of Nest projects?  It should unblock people from upgrading to Nest v6.

**Comment by xmlking** [comment]
looks like nx already support excluding some or all  node modules from bundling `externalDependencies: 'all' | 'none' | string[];` [here](https://github.com/nrwl/nx/blob/master/packages/builders/src/node/build/node-build.builder.ts#L26)

for my case `"externalDependencies": "all"` worked.

**Comment by FrozenPandaz** [comment]
Using `externalDependencies: 'all'` should work. We would like bundling to be the default in production for deploying a lighter docker image. Let's keep discussing in https://github.com/nestjs/nest/issues/1706 because there is more information there.

We could provide a `ts-node` builder but it would lack some features like being unable to do `fileReplacements` and such.
