### ISSUE TITLE
Angular storybook references not installed React modules

### ISSUE THREAD

**Issue by montella1507** [nrwl/nx#11746]
HI i have used this tutorial:

https://nx.dev/storybook/overview-angular

tsconfig.json was generated with linked React files: 
<img width="683" alt="image" src="https://user-images.githubusercontent.com/10418323/187001413-5980400c-01bd-4661-937a-a669402b9289.png">

```
Error:
angular-compilerError: ENOENT: no such file or directory, open node_modules/@nrwl/react/typings/styled-jsx.d.ts'
    at Object.openSync (node:fs:585:3)
    at Module.readFileSync (node:fs:453:35)

```

Version:
   "@nrwl/storybook": "^14.5.10",

**Comment by mandarini** [comment]
Oh no!!! Looking into it, thanks for reporting @montella1507 !!
