### ISSUE TITLE
generate execute node package

### ISSUE THREAD

**Issue by jon9090** [nrwl/nx#11759]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I wish that nx can generate nodejs lib with executable. for example a cli lib. 

## Motivation

Take a look for example cli lib. 
Sometimes I need to create cli lib that do something. this is not app. can be import as lib but can also execute by command promprt.

## Suggested Implementation

when creating node lib add a flag to make it executable

**Comment by AgentEnder** [comment]
This is what a node app is, just choose no framework and write the code as you otherwise would.
