### ISSUE TITLE
How to configure & debug NestJS using vscode?

### ISSUE THREAD

**Issue by olakara** [nrwl/nx#1175]
I am struggling to debug (use breakpoints and inspect the application flow) using vscode. Can someone share me how to configure the debug. I have tried multiple solutions available after googling. But all of them are not in Nx Workspace or with Angular.

Can someone share the launch.json / nodemon-debug.json or other related files for debugging? I would like to know how you are debugging the NestJS application in nrwl workspace

Many Thanks!!

**Comment by appsolutegeek** [comment]
hi @olakara , I am having the same issue. If I placed a debugger statement then it stops.

If I place a breakpoint, it states that Breakpoint unverified and is greyed out (not red).

I can share what I have right now but its not working :-(

Did you get any further ?

```
    {
      "type": "node",
      "request": "attach",
      "protocol": "inspector",
      "name": "API",
      "port": 5880,
      "sourceMaps": true,
      "trace": true
    }
```

I just can't seem to figure it out :-(

Anybody have any suggestions ?

**Comment by olakara** [comment]
hi @appsolutegeek , good to know someone else is having this issue.. I have tried multiple things and failed. I am not an expert so not sure whats the mistake. I haven't found a solution yet :-(. I did ask the same question on other repos as well (some example repos) and nor reply. 

If people are not using vscode, can someone explain how they are debugging the nestjs app in nrwl?

**Comment by appsolutegeek** [comment]
I have tested a standard nestjs app used via the nest cli....  i used the same debug port and i was able to attach the debugger using the same config

So vscode is working it appears.

**Comment by olakara** [comment]
yes, I agree.  I am able to debug a nestjs application that is not in nrwl workspace. My issue is debugging in a nrwl workspace. I not able to figure that out

**Comment by appsolutegeek** [comment]
Ok I fixed it :-)

Here is what I did....  

So I have a container for called projects and under that i placed an NX workspace under the directory called vscode-debug-problem. 

I run ng serve from the vscode-debug-problem directory

but I launch code from the projects directory - so inside code I can see

projects
     vscode-debug-problem
     other-dir
     other-dir2

This emulates what I am doing in real life.

My launch.json was 

```
    {
      "type": "node",
      "request": "attach",
      "protocol": "inspector",
      "name": "API",
      "port": 5880,
      "sourceMaps": true,
      "trace": true
   }
```

but sure enough, attaching a debugger says the breakpoints are unverified and they never stop.

Now add the following to the launch.json above

```
      "cwd": "${workspaceFolder}/vscode-debug-problem"
```

Now attach and add a breakpoint, you will notice straight away that the breakpoint is now RED and not grey stating its unverified.


Hit an endpoint where the breakpoint is and thats it, it stops!

So check if you are doing something similar.

The way I figured this out, is that i created a standard NX project and attached a debugger and it worked - and I thought that is strange as mine doesn't. Then I noticed my directory structure is different.

Hope that helps @olakara and anybody else that finds a similar issue.

So the issue is really a vscode one and its not really an issue, its just knowing what to do - i suppose :-)

**Comment by appsolutegeek** [comment]
On a side note, you can also remove "protocol" and "trace", these are no longer needed. I added them for testing etc.

**Comment by olakara** [comment]
@appsolutegeek Thanks my friend, I am able to debug now. Here is my launch.json:
`  {
      "type": "node",
      "request": "attach",
      "name": "Debug API",
      "sourceMaps": true,
      "port": 7777
    }`

**Comment by omidkrad** [comment]
Really, we should be able to debug out of the box after generating a new nest app. Not to have to spend the next half an hour to find a launch.json setting that works!

**Comment by Tomerl101** [comment]
this lunch.json configuration works pretty fine for me

    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceFolder}/src/main.ts",
      "preLaunchTask": "tsc: watch - tsconfig.build.json",
      "outFiles": ["${workspaceFolder}/dist/**/*.js"],
      "skipFiles": [
        "${workspaceFolder}/node_modules/**/*.js",
        "<node_internals>/**/*.js"
      ]
    }

**Comment by xamantra** [comment]
this works for me too, thank you @Tomerl101 

> this lunch.json configuration works pretty fine for me
> 
> ```
> {
>   "type": "node",
>   "request": "launch",
>   "name": "Launch Program",
>   "program": "${workspaceFolder}/src/main.ts",
>   "preLaunchTask": "tsc: watch - tsconfig.build.json",
>   "outFiles": ["${workspaceFolder}/dist/**/*.js"],
>   "skipFiles": [
>     "${workspaceFolder}/node_modules/**/*.js",
>     "<node_internals>/**/*.js"
>   ]
> }
> ```

**Comment by webhacking** [comment]
@Tomerl101 Thx !

**Comment by coloradocolby** [comment]
> this lunch.json configuration works pretty fine for me
> 
> ```
> {
>   "type": "node",
>   "request": "launch",
>   "name": "Launch Program",
>   "program": "${workspaceFolder}/src/main.ts",
>   "preLaunchTask": "tsc: watch - tsconfig.build.json",
>   "outFiles": ["${workspaceFolder}/dist/**/*.js"],
>   "skipFiles": [
>     "${workspaceFolder}/node_modules/**/*.js",
>     "<node_internals>/**/*.js"
>   ]
> }
> ```

That's it. I'm submitting a ticket Microsoft to support `lunch.json`

**Comment by bcldvd** [comment]
Since I struggled a lot with something so trivial as this, I thought I would add to the solutions above (of which none was ok for me).

Simply add the following options to the "serve" of your NestJs [config](https://github.com/hmagrini/nx/blob/b99f274d9e1d97b0812b4516382407aa75fdae16/docs/api-builders/node-execute.md) in angular.json :

```
"inspect": true,
"port": 9229
```


In context :
```
"serve": {
  "builder": "@nrwl/node:execute",
  "options": {
    "buildTarget": "server:build",
    "inspect": true,
    "port": 9229
  }
}
```

**Comment by Ponjimon** [comment]
> Since I struggled a lot with something so trivial as this, I thought I would add to the solutions above (of which none was ok for me).
> 
> Simply add the following options to the "serve" of your NestJs [config](https://github.com/hmagrini/nx/blob/b99f274d9e1d97b0812b4516382407aa75fdae16/docs/api-builders/node-execute.md) in angular.json :
> 
> ```
> "inspect": true,
> "port": 9229
> ```
> 
> In context :
> 
> ```
> "serve": {
>   "builder": "@nrwl/node:execute",
>   "options": {
>     "buildTarget": "server:build",
>     "inspect": true,
>     "port": 9229
>   }
> }
> ```

And then? For me, now it starts the debugger for a second but immediately closes again and in the console I now see `Waiting for the debugger to disconnect...`

**Comment by bcldvd** [comment]
Do you have "auto attach" to "on" ?

**Comment by Ponjimon** [comment]
Yes

**Comment by ISimplifyComplexity** [comment]
> this lunch.json configuration works pretty fine for me
> 
> ```
> {
>   "type": "node",
>   "request": "launch",
>   "name": "Launch Program",
>   "program": "${workspaceFolder}/src/main.ts",
>   "preLaunchTask": "tsc: watch - tsconfig.build.json",
>   "outFiles": ["${workspaceFolder}/dist/**/*.js"],
>   "skipFiles": [
>     "${workspaceFolder}/node_modules/**/*.js",
>     "<node_internals>/**/*.js"
>   ]
> }
> ```

@Tomerl101  you're awesome, thank you.

**Comment by Oddisey** [comment]
For anyone that is like me and was having issues going from a solution like @olakara 's
> ```
> {
>      "type": "node",
>       "request": "attach",
>       "name": "Debug API",
>       "sourceMaps": true,
>       "port": 7777
>     }
> ```

To a solution like @Tomerl101 's

> this lunch.json configuration works pretty fine for me
> 
> ```
> {
>   "type": "node",
>   "request": "launch",
>   "name": "Launch Program",
>   "program": "${workspaceFolder}/src/main.ts",
>   "preLaunchTask": "tsc: watch - tsconfig.build.json",
>   "outFiles": ["${workspaceFolder}/dist/**/*.js"],
>   "skipFiles": [
>     "${workspaceFolder}/node_modules/**/*.js",
>     "<node_internals>/**/*.js"
>   ]
> }
> ```

The difference between these solutions is that when using the first one, you need to start your NestJS back end on your own, and then run the debugger to watch that running application. With the second one, the dubugger actually starts your NestJS application as well. I think this second method is quite nifty, so kudos to @Tomerl101 for the info. There are a couple of things I had to do when transitioning to this new solution.

1) I am using a mono-repo in Nx Workspace. This means I have many apps sitting in an `apps` directory. My NestJS back-end is sitting in `/apps/nest` (front-end is in `/apps/angular`) so I had to modify the `program`, `outFiles` and `preLaunchTask` to the following:
    - `"program": "${workspaceFolder}/apps/nest/src/main.ts",`
    - `"outFiles": ["${workspaceFolder}/dist/apps/nest/**/*.js"],`
    - `"preLaunchTask": "tsc: watch - apps/nest/tsconfig.json",`
(note I have a `tsconfig.json` instead of a `tsconfig.build.json`)

2) I didn't have a Pre Launch Task set up yet. If you don't either, don't worry VS Code will help set it up for you. With your path to your tsconfig.json set in the `preLaunchTask`, run the debugger. VS Code should show an alert, it will complain and say "Could not find the task 'tsc: watch - apps/nest/tsconfig.json'.". Click the "Configure Task" button. It will generate a task.json file for you. Just save that file, and re-run your debugger.

That is it! Your NestJS back-end should be running in "debug mode" (ie. with a debugger attached)

If you're getting the error `Error: listen EADDRINUSE: address already in use :::3000`, this means your NestJS application is still running. Make sure you kill it before running the debugger, because the debugger is what starts your NestJS app.

    
             
3)

**Comment by chawk** [comment]
For some reason I do get debugging capabilities using the lunch.json file but It's throwing 500 errors when debugging and not when manually firing via package.json script.  I'm trying to track down the issue at the moment.

**Comment by chawk** [comment]
** update.   I figured out my issue had to do with the fact that the debugger is reading files from the dist folder and not from src.  I had to copy static assets as well as handlebars templates manually to the dist folder.   I tried to do this via the nest-cli but it didn't seem to work.   I'm going to look into having webpack move these files during the build process.

**Comment by jakehova** [comment]
@Oddisey solution almost worked for me (thank you for the explanation).  

The three changes I made were: 
1) changing the app name from "nest" to my app name (nestbackend)
2) change the prelaunchtask to point to tsconfig.app.json instead of tsconfig.json.
3) Went to the root angular.json file and changed the serve -> options property for the nestjs app to set inspect to true: 

```
 "serve": {
          "builder": "@nrwl/node:execute",
          "options": {
            "buildTarget": "nestbackend:build",
            "inspect": true
          }
        },
```
I didn't need to create a task.json.

**Comment by Olgagr** [comment]
Just a reminder for people who use .env files in their project. Don't forget to set up path to the .env file too in the launch.json 😄 

```
"envFile": "${workspaceFolder}/apps/your_nest_app/.env",
```

**Comment by LucCADORET** [comment]
I had some problems with the above `launch.json`, which is why I'd like to share my own `launch.json` config that I find way more efficient, using the latest debugger `pwa-node` and `ts-node`

`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Backend",
            "type": "pwa-node",
            "request": "launch",
            "args": [
              "apps/backend/src/main.ts"
            ],
            "runtimeArgs": [
              "--require",
              "ts-node/register",
              "--require",
              "tsconfig-paths/register",
            ],
            "cwd": "${workspaceRoot}",
            "internalConsoleOptions": "openOnSessionStart",
            "env": {
              "NODE_ENV": "local",
              "NODE_PORT": "8000",
              "TS_NODE_PROJECT": "apps/backend/tsconfig.app.json", // Specify the tsconfig to use
            },
            "sourceMaps": true,
            "console": "internalConsole",
            "outputCapture": "std",
            "resolveSourceMapLocations": [
              "${workspaceFolder}/**",
              "!**/node_modules/**" // Disable the "could not read source map" error for node_modules
            ]
          }
    ]
}`

Some quick notes:
- You need to adapt the paths to your `main.ts` and `tsconfig.app.json`
- The TS_NODE_PROJECT is an env var recognized by ts-node to find out which `tsconfig` to look at
- the console and outCapture option are just personal options, otherwise my NestJS debugging log doesn't show up in VSCode terminal

See https://github.com/TypeStrong/ts-node for complementary info

**Comment by RyanElfman** [comment]
> I had some problems with the above `launch.json`, which is why I'd like to share my own `launch.json` config that I find way more efficient (no "out files", no "pre launch tasks"), using the latest debugger `pwa-node` and `ts-node`
> 
> ```
> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "Debug Backend",
>             "type": "pwa-node",
>             "request": "launch",
>             "args": [
>               "apps/backend/src/main.ts"
>             ],
>             "runtimeArgs": [
>               "--require",
>               "ts-node/register",
>               "--require",
>               "tsconfig-paths/register",
>             ],
>             "cwd": "${workspaceRoot}",
>             "internalConsoleOptions": "openOnSessionStart",
>             "env": {
>               "NODE_ENV": "local",
>               "NODE_PORT": "8000",
>               "TS_NODE_PROJECT": "apps/backend/tsconfig.app.json", // Specify the tsconfig to use
>             },
>             "sourceMaps": true,
>             "console": "internalConsole",
>             "outputCapture": "std",
>             "resolveSourceMapLocations": [
>               "${workspaceFolder}/**",
>               "!**/node_modules/**" // Disable the "could not read source map" error for node_modules
>             ]
>           }
>     ]
> }
> ```
> 
> Some quick notes:
> 
> * You need to adapt the paths to your `main.ts` and `tsconfig.app.json`
> * The TS_NODE_PROJECT is an env var recognized by ts-node to find out which `tsconfig` to look at
> * the console and outCapture option are just personal options, otherwise my NestJS debugging log doesn't show up in VSCode terminal
> 
> See https://github.com/TypeStrong/ts-node for complementary info

This worked for me!! I spent half a day trying to debug my application. Thank you!

**Comment by Jedliu** [comment]
> I had some problems with the above `launch.json`, which is why I'd like to share my own `launch.json` config that I find way more efficient (no "out files", no "pre launch tasks"), using the latest debugger `pwa-node` and `ts-node`
> 
> ```
> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "Debug Backend",
>             "type": "pwa-node",
>             "request": "launch",
>             "args": [
>               "apps/backend/src/main.ts"
>             ],
>             "runtimeArgs": [
>               "--require",
>               "ts-node/register",
>               "--require",
>               "tsconfig-paths/register",
>             ],
>             "cwd": "${workspaceRoot}",
>             "internalConsoleOptions": "openOnSessionStart",
>             "env": {
>               "NODE_ENV": "local",
>               "NODE_PORT": "8000",
>               "TS_NODE_PROJECT": "apps/backend/tsconfig.app.json", // Specify the tsconfig to use
>             },
>             "sourceMaps": true,
>             "console": "internalConsole",
>             "outputCapture": "std",
>             "resolveSourceMapLocations": [
>               "${workspaceFolder}/**",
>               "!**/node_modules/**" // Disable the "could not read source map" error for node_modules
>             ]
>           }
>     ]
> }
> ```
> 
> Some quick notes:
> 
> * You need to adapt the paths to your `main.ts` and `tsconfig.app.json`
> * The TS_NODE_PROJECT is an env var recognized by ts-node to find out which `tsconfig` to look at
> * the console and outCapture option are just personal options, otherwise my NestJS debugging log doesn't show up in VSCode terminal
> 
> See https://github.com/TypeStrong/ts-node for complementary info

This doesn't work in the watch mode. So I have to restart again to load the changes.

**Comment by Jedliu** [comment]
After some research, I have below working ones in watch mode for Nestjs and Jest unit test and Jest e2e test. Hope this could help.

### Debug Nestjs in Watch Mode.
First, you need to have `nodemon` installed by `npm i --save-dev nodemon`.
Add `"start:debug:nodemon": "nodemon --config nodemon-debug.json",` in the `scripts` section of `package.json` file.
Create a new file `nodemon-debug.json` with below content. This is the config for nodemon.
```
{
  "watch": ["src"],
  "ext": "ts",
  "ignore": ["src/**/*.spec.ts"],
  "exec": "node --inspect --nolazy -r tsconfig-paths/register -r ts-node/register src/main.ts"
}
```
Second, you need to add below to the `configurations` section of `launch.json`. This is to attach the Debugger.
```
{
    //should run command "npm run start:debug -nodemon" first then attach to the debug process
    "type": "node",
    "request": "attach",
    "name": "Attach NestJS Debugger",
    "port": 9229,
    "restart": true,
    "stopOnEntry": false,
    "protocol": "inspector"
},
```
**How to run?**
Run the script in the terminal `npm run start:debug:nodemon`
Then run the Debugger from the VSCode.
![image](https://user-images.githubusercontent.com/771703/129430504-c733664d-d39c-42b5-ba84-f77543374c38.png)

### Debug Jest Unit Test in watch mode.
Add below to the `configurations` section of `launch.json`.
```
{
    // https://jestjs.io/docs/troubleshooting
    "name": "Debug Jest Tests --watch",
    "type": "node",
    "request": "launch",
    "runtimeArgs": [
        "--inspect-brk",
        "${workspaceRoot}/node_modules/.bin/jest",
        "--runInBand",
        "--watch",
        // you can add fitler here to run specific test
    ],
    "console": "integratedTerminal",
    "internalConsoleOptions": "neverOpen",
    "port": 9229
},
```
Then run the Debugger from the VSCode.

### Debug Jest E2E Test in watch mode.
Add below to the `configurations` section of `launch.json`.
```
{
    "name": "Debug Jest E2E Tests --watch",
    "type": "node",
    "request": "launch",
    "runtimeArgs": [
        "--inspect-brk",
        "${workspaceFolder}/node_modules/.bin/jest",
        "--runInBand",
        "--config",
        "${workspaceRoot}/test/jest-e2e.json",
        "--watch"
    ],
    "console": "integratedTerminal",
    "internalConsoleOptions": "neverOpen",
    "port": 9229,
}
```
Then run the Debugger from the VSCode.

**Comment by xelaos** [comment]
> I had some problems with the above `launch.json`, which is why I'd like to share my own `launch.json` config that I find way more efficient (no "out files", no "pre launch tasks"), using the latest debugger `pwa-node` and `ts-node`
> 
> ```
> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "Debug Backend",
>             "type": "pwa-node",
>             "request": "launch",
>             "args": [
>               "apps/backend/src/main.ts"
>             ],
>             "runtimeArgs": [
>               "--require",
>               "ts-node/register",
>               "--require",
>               "tsconfig-paths/register",
>             ],
>             "cwd": "${workspaceRoot}",
>             "internalConsoleOptions": "openOnSessionStart",
>             "env": {
>               "NODE_ENV": "local",
>               "NODE_PORT": "8000",
>               "TS_NODE_PROJECT": "apps/backend/tsconfig.app.json", // Specify the tsconfig to use
>             },
>             "sourceMaps": true,
>             "console": "internalConsole",
>             "outputCapture": "std",
>             "resolveSourceMapLocations": [
>               "${workspaceFolder}/**",
>               "!**/node_modules/**" // Disable the "could not read source map" error for node_modules
>             ]
>           }
>     ]
> }
> ```
> 
> Some quick notes:
> 
> * You need to adapt the paths to your `main.ts` and `tsconfig.app.json`
> * The TS_NODE_PROJECT is an env var recognized by ts-node to find out which `tsconfig` to look at
> * the console and outCapture option are just personal options, otherwise my NestJS debugging log doesn't show up in VSCode terminal
> 
> See https://github.com/TypeStrong/ts-node for complementary info
This works, thank you, but i have to restart it manually  or should this have an watch mode?

**Comment by tobertigor** [comment]
is there a final version of the config?

**Comment by vsinghipcium** [comment]
Try this: Works in watch mode. Debugger auto attach when server restarts. Configuration "Debug:Server" runs server before attaching.
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to Server",
      "port": 9229,
      "restart": true,
      "request": "attach",
      "type": "pwa-node"
    },
    {
      "name": "Launch Server",
      "command": "yarn run server",
      "request": "launch",
      "type": "node-terminal",
      "envFile": "${workspaceFolder}/.env"
    }
  ],
  "compounds": [
    {
      "name": "Debug:Server",
      "configurations": ["Launch Server", "Attach to Server"]
    }
  ]
}
```

**Comment by kamal-brill** [comment]
@singhsoldier13 I'm getting "Property command is not allowed" as per your launch.json

![image](https://user-images.githubusercontent.com/46436784/178161074-19b16001-0508-40a7-87a4-d9f4aa766a47.png)

@gitn00b1337

**Comment by morbargig** [comment]
My solution was 
```json
    {
      "name": "Api (NestJS BFF)",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "npx",
      "runtimeArgs": ["nx", "run", "api:serve", "--inspect"],
      "preLaunchTask": "tsc: watch - apps/api/tsconfig.json",
      "cwd": "${workspaceRoot}",
      "internalConsoleOptions": "neverOpen",
      "env": {
        "NODE_ENV": "local",
        "NODE_PORT": "8080",
        "IS_DEBUG_MODE": "true",
        "TS_NODE_PROJECT": "apps/api/tsconfig.app.json" // Specify the tsconfig to use,
      },
      "sourceMaps": true,
      "console": "internalConsole",
      "outputCapture": "std",
      "resolveSourceMapLocations": [
        "${workspaceFolder}/**",
        "!**/node_modules/**" // Disable the "could not read source map" error for node_modules
      ]
    }
```
I used few solutions here, but the best way was to just use the NPX
to run any command that I want and still be able to run with testing in the lunch and watch on files saves 
and debugger jumps on “debugger” and with line selections

**Comment by nniirraavv** [comment]
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/src/main.ts",
            "preLaunchTask": "tsc: watch - tsconfig.build.json",
            "outFiles": [
                "${workspaceFolder}/dist/**/*.js"
            ],
            "skipFiles": [
                "${workspaceFolder}/node_modules/**/*.js",
                "<node_internals>/**/*.js"
            ]
        }
    ]
}
