### ISSUE TITLE
With Latest version, with minimal setup when we try to serve the nest application we get "TypeError: Cannot read property ‘nodes’ of undefined" 

### ISSUE THREAD

**Issue by subramanya4shenoy** [nrwl/nx#11751]
## Current Behavior

on serve or build getting the error "TypeError: Cannot read property ‘nodes’ of undefined"

## Expected Behavior

To serve and run the server

Nope. I tried with version 14.1.7  all worked fine.

## Steps to Reproduce

Simple nx workspace with nrwl/nest package installed and trying to run. 

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by NathanAdhitya** [comment]
Can confirm. Is happening with @nrwl/express too.

**Comment by AgentEnder** [comment]
Can you run `nx report` in the repo? Is there a reproduction that you can link?

**Comment by AgentEnder** [comment]
All packages under the @nrwl scope except nx-cloud **_must_** be at the same version, or you will likely run into errors. This would likely show up in `nx report`, hence why I asked for its outputs.

**Comment by subramanya4shenoy** [comment]
I understand now. 

this is my nx report 

```
   Node : 15.9.0
   OS   : darwin x64
   npm  : 7.5.3
   
   nx : 14.1.9
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.9
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.9
   @nrwl/eslint-plugin-nx : 14.1.9
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.9
   @nrwl/js : 14.1.7
   @nrwl/linter : 14.1.9
   @nrwl/nest : 14.1.7
   @nrwl/next : Not Found
   @nrwl/node : 14.1.7
   @nrwl/nx-cloud : 14.5.4
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.1.9
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.9
   @nrwl/web : 14.1.9
   @nrwl/workspace : 14.1.9
   typescript : 4.6.4
   ---------------------------------------
   Community plugins:
```
