### ISSUE TITLE
Serving an app fails in nx 14.1.10

### ISSUE THREAD

**Issue by 31piy** [nrwl/nx#11766]
I have a workspace which I just migrated to nx 14.1.10. When I try to start my server, an error is thrown on the console:

```
Cannot find module '@angular-devkit/core'
Require stack:
- app/node_modules/nx/src/adapter/ngcli-adapter.js
- app/node_modules/nx/src/command-line/run.js
- app/node_modules/nx/bin/run-executor.js
```

## Expected Behavior
I am using `@angular-builders/custom-webpack` version `13.1.0` to serve this application. But any other application which uses `@angular-devkit/build-angular` also doesn't work. Ideally, I shouldn't get the angular devkit error.

## Steps to Reproduce
I had the workspace using nx 13.1.4 and I tried to upgrade it to nx 14.1.10 using the standard `nx migrate 14.1.10` command. The migrations ran smoothly but serving the application result in the error above.

I'm trying to reproduce it on the example repo.

### Environment

```
> nx report                                                                                                                                                                          

 >  NX   Report complete - copy this into the issue template

   Node : 16.17.0
   OS   : darwin x64
   npm  : 8.15.0

   nx : 14.1.10
   @nrwl/angular : 14.1.10
   @nrwl/cypress : 14.1.10
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.10
   @nrwl/eslint-plugin-nx : 14.1.10
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.10
   @nrwl/js : Not Found
   @nrwl/linter : 14.1.10
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.6.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.10
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.10
   typescript : 4.6.3
   ---------------------------------------
   Community plugins:
   	 rxjs: 6.6.7
   	 single-spa-angular: 5.0.2
   	 @ngneat/spectator: 8.3.1
   	 @storybook/angular: 6.4.21
   	 ngx-build-plus: 11.0.0
   	 nx-stylelint: 12.2.0

(node:64188) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at app/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by e-oz** [comment]
Try to build it, maybe there is some error (nx serve will not show it, only nx build - see [this issue](https://github.com/nrwl/nx/issues/11770)).

**Comment by 31piy** [comment]
@e-oz The build target also fails. Here is the output from the verbose logs:

```

   ✔    4/4 dependent project tasks succeeded [1 read from cache]

   Hint: you can run the command with --verbose to see the full dependent project outputs

 —————————————————————————————————————————————————————————————————————————————————————————————————————


> nx run app:build:production --verbose

Cannot find module '@angular-devkit/core'
Require stack:
- app/node_modules/nx/src/adapter/ngcli-adapter.js
- app/node_modules/nx/src/command-line/run.js
- app/node_modules/nx/bin/run-executor.js
Error: Cannot find module '@angular-devkit/core'
Require stack:
- app/node_modules/nx/src/adapter/ngcli-adapter.js
- app/node_modules/nx/src/command-line/run.js
- app/node_modules/nx/bin/run-executor.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at Module.require (app/node_modules/nx/src/adapter/compat.js:14:40)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (app/node_modules/nx/src/adapter/ngcli-adapter.js:6:16)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)

 —————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for project app and 4 task(s) it depends on (14s)

         With additional flags:
           --verbose=true

    ✖    1/5 failed
    ✔    4/5 succeeded [1 read from cache]
```

**Comment by 31piy** [comment]
Interestingly, the nx CLI depends on `@angular-devkit/core` (https://github.com/nrwl/nx/blob/14.1.10/packages/nx/src/adapter/ngcli-adapter.ts#L2) and this import appears in the dist bundles too, but this package is missing from the `node_modules/nx`.

**Comment by e-oz** [comment]
There is Angular 14.2 and a related devkit version - try to use them.

**Comment by 31piy** [comment]
Apparently, in my package.json, I previously had `@angular-builders/jest` which internally installed `@angular-devkit/core`. I removed it in between the migration because I didn't need it, I use `@nrwl/jest` executor throughout my project. Turns out that I still need to include it since it install the package.

**Comment by FrozenPandaz** [comment]
Which `builder` are you using for `serve`/`build`?

That package is supposed to bring in its own version of `@angular-devkit/core` :eyes: 

Can you provide a repro please? I can't reproduce this with the default setup. `@angular-devkit/build-angular` does bring in its own version of `@angular-devkit/core`.

**Comment by 31piy** [comment]
@FrozenPandaz As I mentioned in the issue description, I am using `@angular-builders/custom-webpack` to serve this app. I have updated it to `13.1.0` which should be compatible with Angular v13.

**Comment by 31piy** [comment]
I am not able to repro this anymore. I upgraded nx to 13.10 and then 14.1, which worked fine without any problems. Thank you for your support.
