### ISSUE TITLE
allow --port flag to be passed in for e2e cypress tests

### ISSUE THREAD

**Issue by markgoho** [nrwl/nx#1177]
If you've got your app running and then run your e2e tests, it'll fail because that port is already in use. It doesn't look like it'll just use the running application, so it tries to start the e2e version of the app on the same port because there's no way to specify a different port per build target.

So, we need the option to pass in a different port when running e2e tests.

**Comment by markgoho** [comment]
It would be nice to see the port passed in as a flag, but it's been pointed out that if you start you e2e tests in watch mode, you can also continue developing using the served application on its default port.

**Comment by adamm-monek** [comment]
It would still be useful to cope with this, or at least document it. My reasoning is that when you try and run it (by mistake perhaps), the feedback from the generated `ng run XXXXX:e2e --watch=true` command then suggests `Port 4200 is already in use. Use '--port' to specify a different port'. The fact you then can't pass that from the `nx` level command causes confusion.

**Comment by Blackhex** [comment]
Also, if you are running e2e tests on CI in multiple runs (e.g. for different branches) the port needs to be selected at random to prevent clashes between pipelines.

**Comment by crates** [comment]
@Blackhex - This issue is marked closed already. If you'd like to see that feature (I know I would), please consider opening a new issue.
