### ISSUE TITLE
cypress-component-configuration: mount issues with SVGs served with SVGR

### ISSUE THREAD

**Issue by liambutler** [nrwl/nx#11785]
## Current Behavior

I've got an NX monorepo which serves SVGs via svgr. `nx serve` works as expected, and all assets are rendered.

However, when I attempt to mount the app for Cypress component testing (configuration generated via `nx generate cypress-component-configuration`), I'm seeing the following error:

> Module parse failed: Unexpected token (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. 

I suspect that some of the settings in `next.config.js` are not being used when generating the configuration for Cypress component testing

## Expected Behavior
Components can be mounted in the Cypress spec, just as they are rendered via `nx serve`

## Steps to Reproduce
Minimal GitHub repro: https://github.com/liambutler/cypress-ct-nx-issue/

Instructions are in the readme

### Failure Logs
```
webpack 5.74.0 compiled with 1 error in 29 ms
7 assets
55 modules

ERROR in ../../libs/ui/src/icon/assets/Achievements/one.svg 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <svg width="64" height="64" viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg">
| <circle cx="32" cy="32" r="32" fill="#DFE2E4"/>
| <path fill-rule="evenodd" clip-rule="evenodd" d="M35 21H31V42H35V31.5L40.0092 42.0018L44 42L39.0335 31.5L44 21H40.0092L35 31.5V21Z" fill="#394754"/>

webpack 5.74.0 compiled with 1 error in 31 ms
```

### Environment
```
   Node : 16.16.0
   OS   : darwin arm64
   yarn : 1.22.19

   nx : 14.5.10
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.10
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.10
   @nrwl/eslint-plugin-nx : 14.5.10
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.10
   @nrwl/js : 14.5.10
   @nrwl/linter : 14.5.10
   @nrwl/nest : Not Found
   @nrwl/next : 14.5.10
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.10
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.10
   @nrwl/web : 14.5.10
   @nrwl/workspace : 14.5.10
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by barbados-clemens** [comment]
[Next.js support for cypress component testing is still considered alpha by cypress](https://docs.cypress.io/guides/component-testing/component-framework-configuration#Next-js)

So at this time we aren't explicitly handling anything special for Next

Better support for react projects was just merged (#11725) which should handle this usage as long as it's not requiring any special applications from the next config to be applied. 

But you can always extend the component testing generated webpack config if needed via 
```ts
import { defineConfig } from 'cypress';
import { nxComponentTestingPreset } from '@nrwl/react/plugins/component-testing';

function addExtraToWebpack(config) {
  const webpack = config.devServer.webpackConfig;

  // do whatever you want with the webpack config

  return {
   ...config,
    devSever: {
     ...config,
     webpackConfig: webpack
  }
}

export default defineConfig({
  component: addExtrasToWebpack(nxComponentTestingPreset(__filename)),
});

**Comment by liambutler** [comment]
Makes sense, seeing as it's in alpha. I'll give your suggestion a try. Thanks!

**Comment by barbados-clemens** [comment]
Just add anything extra to that example repo and I'll make sure to test against so it'll work out of the box for you. 👍
