### ISSUE TITLE
Use all Cypress flags in nx console

### ISSUE THREAD

**Issue by tamtakoe** [nrwl/nx#11780]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

I want to use in my package.json (or something similar)
```
"test:e2e": "nx e2e web-e2e --disable-gpu"
```
But it doesn't work and I can't find documentation how to use any flags for Cypress or other modules

**Comment by barbados-clemens** [comment]
I'm not familiar with the --disable-gpu option for cypress and I don't see it in the [cli docs.](https://docs.cypress.io/guides/guides/command-line#cypress-cache-command) 

Can you point me to where in the cypress docs they talk about this flag?

**Comment by tamtakoe** [comment]
Looks like there is more suitable place https://docs.cypress.io/api/plugins/browser-launch-api#Syntax to setup `--disable-gpu` and some other flags... But it also works incorrect https://github.com/cypress-io/cypress/issues/23626. Maybe it is Cypress bug, maybe - my bad, I don't know.

Anyway will be good to add into NX/Cypress docs info about setupNodeEvents and how to add browser flags etc.
