### ISSUE TITLE
Missing the "structure" part documentation

### ISSUE THREAD

**Issue by reenan** [nrwl/nx#11794]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

`https://nx.dev/structure/*`

### Additional context or description

For a couple of days, I see that this part of the documentation isn't available anymore. It used to be very helpful. I can find parts of what I was looking for inside `structure` at the "courses" or spread in other places, but honestly, it doesn't feel as conventional. 

Sorry if I missed any announcements regarding it, also wanted to check the Slack channel but it seems to not be open anymore. 

Are there any plans towards making this documentation available through some legacy link or similar?

**Comment by mandarini** [comment]
Hi there @reenan ! Can you try using the quicksearch feature and see if you can find the pages you are looking for, as a temporary solution?

![Screenshot 2022-08-31 at 12 09 13 PM](https://user-images.githubusercontent.com/6603745/187642564-d2d097c9-cdce-4bcc-95e6-09d8068977a4.png)
