### ISSUE TITLE
Pages are not found

### ISSUE THREAD

**Issue by Lornot** [nrwl/nx#11795]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/structure/buildable-and-publishable-libraries
https://nx.dev/ci/incremental-builds
https://nx.dev/structure/monorepo-tags

**Comment by ezhikov** [comment]
All links from main page also lead to 404, unless they are opened in new tab/window

**Comment by mandarini** [comment]
https://nx.dev/more-concepts/buildable-and-publishable-libraries

https://nx.dev/more-concepts/incremental-builds

https://nx.dev/core-features/enforce-project-boundaries#tags

Hi there! Do these pages help?
