### ISSUE TITLE
Guides => Using Tailwind CSS in React => 404

### ISSUE THREAD

**Issue by warrendugan** [nrwl/nx#11807]
### Documentation issue
- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[Using Tailwind CSS in React](https://nx.dev/guides/using-tailwind-css-in-react)

**Comment by mrlubos** [comment]
+1, also noticed guides missing https://github.com/nrwl/nx/issues/11839

**Comment by mandarini** [comment]
Hi there! I understand the frustration. You can use the quicksearch to find the page you are looking for, if a URL is broken. For example, the above page can be found here: https://nx.dev/recipe/using-tailwind-css-in-react
