### ISSUE TITLE
Broken links on website Home page

### ISSUE THREAD

**Issue by slashwhatever** [nrwl/nx#11815]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/migration/lerna-and-nx
https://nx.dev/migration/adding-to-monorepo

### Additional context or description
Both of these key links on the home page are broken, leading to a 404 error page.

Edit: So are most of the links further down the page in the "Best-in-Class Support for Monorepos" section. Too many to list.

**Comment by mrlubos** [comment]
Yeah, seems their documentation went offline big time https://github.com/nrwl/nx/issues/11839

**Comment by mandarini** [comment]
Hi there! Thanks for filing an issue! Our documentation, actually, did not go offline. We just made a big restructure to make things easier. This restructure has cause some frustration, as I understand. All documentation is there as it was, it has just moved under different URLs. You can use the quicksearch feature to find/navigate to any page that has moved! :) Please let me know if this helps, and we are working to make the experience smoother for everyone.

You can find the pages you are looking for here:

https://nx.dev/recipe/lerna-and-nx

and 

https://nx.dev/recipe/adding-to-monorepo

**Comment by bcabanes** [comment]
The home page links have been fixed, thank you for the report.
