### ISSUE TITLE
Cannot create Angular application in new workspace

### ISSUE THREAD

**Issue by namdien177** [nrwl/nx#11823]
## Current Behavior
Cannot create a new Angular application in a new `nx@14.6.1` workspace. The error of `Collection "@schematics/angular" cannot be resolved.` was returned.

## Expected Behavior
Should create new Angular application normally.

## Steps to Reproduce
Sample repository: [here](https://github.com/namdien177/sample-nx-error)

- `pnpm dlx create-nx-workspace sample-nx-error`
- cd to directory
- `pnpm install --save-dev @nrwl/angular`
- `nx generate @nrwl/angular:app cliscord`

### Failure Logs
![image](https://user-images.githubusercontent.com/29449869/187889269-275cdf97-15a3-4437-a383-d206b2433caf.png)

### Environment

> PS D:\work\projects\sample-error> nx report
> 
> >  NX   WARNING  Running global Nx CLI with PNPM may have issues.
> 
>   Prefer to use "pnpm" (https://pnpm.io/cli/exec) to execute commands in this workspace.
>    TIP  create a shortcut such as: doskey pnx=pnpm nx -- $*
> 
> 
> 
>  >  NX   Report complete - copy this into the issue template
> 
>    Node : 16.14.2
>    OS   : win32 x64
>    pnpm : 7.3.0
> 
>    nx : 14.6.1
>    @nrwl/angular : 14.6.1
>    @nrwl/cypress : Not Found
>    @nrwl/detox : Not Found
>    @nrwl/devkit : Not Found
>    @nrwl/eslint-plugin-nx : 14.6.1
>    @nrwl/express : Not Found
>    @nrwl/jest : 14.6.1
>    @nrwl/js : Not Found
>    @nrwl/linter : 14.6.1
>    @nrwl/nest : 14.6.1
>    @nrwl/next : Not Found
>    @nrwl/node : 14.6.1
>    @nrwl/nx-cloud : 14.6.0
>    @nrwl/nx-plugin : Not Found
>    @nrwl/react : Not Found
>    @nrwl/react-native : Not Found
>    @nrwl/schematics : Not Found
>    @nrwl/storybook : Not Found
>    @nrwl/web : Not Found
>    @nrwl/workspace : 14.6.1
>    typescript : 4.7.4
>    ---------------------------------------
>    Local workspace plugins:
>    ---------------------------------------
>    Community plugins:

**Comment by FrozenPandaz** [comment]
Hi, I cloned your repository and it is working for me

Could you try running the command via `pnpm` as the note recommends?

```bash
pnpm nx generate @nrwl/angular:app cliscord
```

**Comment by namdien177** [comment]
> Hi, I cloned your repository and it is working for me
> 
> Could you try running the command via `pnpm` as the note recommends?
> 
> ```shell
> pnpm nx generate @nrwl/angular:app cliscord
> ```

Yea it seems that using `pnpm nx ...` work. Close the issue.
