### ISSUE TITLE
Microfrontend architecure page not found

### ISSUE THREAD

**Issue by vadjs** [nrwl/nx#11824]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.

https://nx.dev/module-federation/micro-frontend-architecture

### Additional context or description

Provide any additional details here as needed.

**Comment by mrlubos** [comment]
Possibly related to https://github.com/nrwl/nx/issues/11839

**Comment by mandarini** [comment]
Hi there! Thanks for filing an issue! We just made a big restructure to our documentation make things clearer. This restructure has cause some frustration, as I understand. All documentation is there as it was, it has just moved under different URLs. You can use the quicksearch feature to find/navigate to any page that has moved! :) Please let me know if this helps, and we are working to make the experience smoother for everyone.

You can find the page you are looking for here:

https://nx.dev/more-concepts/micro-frontend-architecture
