### ISSUE TITLE
bug: `dependsOn` has no effect in Nx 14.6.x

### ISSUE THREAD

**Issue by edbzn** [nrwl/nx#11826]
## Current Behavior

With Nx 14.5.4, when I run `nx run semver:version` it runs the `build` target before the `version` target since I configured the target defaults in nx.json:

```
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build"]
    },
    "version": {
      "dependsOn": ["^build"]
    }
  }
```

## Expected Behavior

After migrating to Nx 14.6.1, `dependsOn` has no effect, the `build` target is never run so the command is failing as it is expecting a build output. I also tried to put the `dependsOn` config at the project level but it's still doing nothing.

## Steps to Reproduce

You can clone the [semver repository](https://github.com/jscutlery/semver) to reproduce, the main branch is using Nx 14.6.1 so you can verify the issue by running `nx run semver:version`, it should build semver before versioning.

**Comment by edbzn** [comment]
@FrozenPandaz I tried again with Nx 16.6.4 and I'm still getting an error, the build target is not run before, here is the log:

```
Error: Unable to resolve ./dist/packages/semver:version.
Cannot find module './dist/packages/semver/package.json'
Require stack:
- jscutlery/semver/node_modules/nx/src/utils/package-json.js
- jscutlery/semver/node_modules/nx/src/utils/package-manager.js
- jscutlery/semver/node_modules/nx/bin/init-local.js
- jscutlery/semver/node_modules/nx/bin/nx.js
- /usr/local/lib/node_modules/nx/bin/nx.js
    at Workspaces.readExecutor (jscutlery/semver/node_modules/nx/src/config/workspaces.js:117:19)
    at getExecutorForTask (jscutlery/semver/node_modules/nx/src/tasks-runner/utils.js:133:22)
    at getCustomHasher (jscutlery/semver/node_modules/nx/src/tasks-runner/utils.js:137:21)
    at jscutlery/semver/node_modules/nx/src/hasher/hash-task.js:21:58
    at Generator.next (<anonymous>)
    at jscutlery/semver/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (jscutlery/semver/node_modules/tslib/tslib.js:114:16)
    at hashTask (jscutlery/semver/node_modules/nx/src/hasher/hash-task.js:20:20)
    at TasksSchedule.<anonymous> (jscutlery/semver/node_modules/nx/src/tasks-runner/tasks-schedule.js:62:48)
```

**Comment by FrozenPandaz** [comment]
Sorry, I forgot to tell you, @edbzn.

Part of the issue for you is that `semver:version` uses an executor which is produced by `semver:build`.

However, `version` targets only depend on `^build` which are the build targets of its dependencies, not the project itself. So you should add `build` to the `dependsOn` for `version` in `targetDefaults`.

That should resolve the issue for you.

I see this commit is where the change happened? https://github.com/jscutlery/semver/commit/f2b5a5ecf79f2e754eb2b9f35402a6d25d64f0e1
