### ISSUE TITLE
[@nrwl/web:webpack] Bundle is not minified when compiler is set as "swc" on production configuration

### ISSUE THREAD

**Issue by GraxMonzo** [nrwl/nx#11821]
## Current Behavior

Bundle is not minified when `compiler` is `"swc"` and `optimization` is `true`.

## Expected Behavior

Bundle is minified when `compiler` is `"swc"` and `optimization` is `true`.

## Steps to Reproduce

1. Create a React workspace
```bash
npx create-nx-workspace --preset=react
```
2. Set compiler option in `project.json` of main app as `"swc"`
3. Build
### Failure Logs

None.
### Environment
```
   Node : 16.15.1
   OS   : win32 x64
   npm  : 8.11.0

   nx : 14.5.10
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.10
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.10
   @nrwl/eslint-plugin-nx : 14.5.10
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.10
   @nrwl/js : 14.5.10
   @nrwl/linter : 14.5.10
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.10
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.10
   @nrwl/web : 14.5.10
   @nrwl/workspace : 14.5.10
   typescript : 4.8.2
```

**Comment by FrozenPandaz** [comment]
I couldn't reproduce this issue:

It was bundled for me: https://github.com/FrozenPandaz/nx-bugs/tree/repro-11821

```bash
jason@pop-os ~/p/t/swc-test (main)> nx build app1

> nx run app1:build:production

Entrypoint main 201 KiB = runtime.f0b83be3db90bb2c.esm.js 6.23 KiB main.8265108115b05bf8.esm.js 195 KiB
Entrypoint polyfills [big] 575 KiB = runtime.f0b83be3db90bb2c.esm.js 6.23 KiB polyfills.efd53650a9f21d51.esm.js 569 KiB
Entrypoint styles 6.23 KiB = runtime.f0b83be3db90bb2c.esm.js 6.23 KiB styles.ef46db3751d8e999.css 0 bytes
chunk (runtime: runtime) main.8265108115b05bf8.esm.js (main) 193 KiB [initial] [rendered]
chunk (runtime: runtime) polyfills.efd53650a9f21d51.esm.js (polyfills) 545 KiB [initial] [rendered]
chunk (runtime: runtime) styles.ef46db3751d8e999.css (styles) 50 bytes (javascript) 80 bytes (css/mini-extract) [initial] [rendered]
chunk (runtime: runtime) runtime.f0b83be3db90bb2c.esm.js (runtime) 3.23 KiB [entry] [rendered]
webpack compiled successfully (9373934b9c6c1943)

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target build for project app1 (3s)
 ```

**Comment by GraxMonzo** [comment]
> I couldn't reproduce this issue:
> 
> It was bundled for me: https://github.com/FrozenPandaz/nx-bugs/tree/repro-11821
> 
> ```shell
> jason@pop-os ~/p/t/swc-test (main)> nx build app1
> 
> > nx run app1:build:production
> 
> Entrypoint main 201 KiB = runtime.f0b83be3db90bb2c.esm.js 6.23 KiB main.8265108115b05bf8.esm.js 195 KiB
> Entrypoint polyfills [big] 575 KiB = runtime.f0b83be3db90bb2c.esm.js 6.23 KiB polyfills.efd53650a9f21d51.esm.js 569 KiB
> Entrypoint styles 6.23 KiB = runtime.f0b83be3db90bb2c.esm.js 6.23 KiB styles.ef46db3751d8e999.css 0 bytes
> chunk (runtime: runtime) main.8265108115b05bf8.esm.js (main) 193 KiB [initial] [rendered]
> chunk (runtime: runtime) polyfills.efd53650a9f21d51.esm.js (polyfills) 545 KiB [initial] [rendered]
> chunk (runtime: runtime) styles.ef46db3751d8e999.css (styles) 50 bytes (javascript) 80 bytes (css/mini-extract) [initial] [rendered]
> chunk (runtime: runtime) runtime.f0b83be3db90bb2c.esm.js (runtime) 3.23 KiB [entry] [rendered]
> webpack compiled successfully (9373934b9c6c1943)
> 
>  ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
> 
>  >  NX   Successfully ran target build for project app1 (3s)
> ```
> 
> Could you provide the repo where you were running into this issue please?

Hey @FrozenPandaz, thanks for checking it out.
I cloned `nx-bugs` at `repro-11821` and these are results of the build with no changes and no formatting (swc):
![image](https://user-images.githubusercontent.com/11737104/188256667-515a67c3-9b56-4962-9fbf-eab82646ced8.png)
And babel build of same project with same branch:
![image](https://user-images.githubusercontent.com/11737104/188256717-b450c28d-f05d-48ec-bf46-62d7a404f414.png)

As you can see babel successfully minifies the bundle while "swc" leaves white spaces and new lines.

**Comment by GraxMonzo** [comment]
swc:
```
Entrypoint main 201 KiB = runtime.f0b83be3db90bb2c.esm.js 6.23 KiB main.435cd701ccd77263.esm.js 195 KiB
Entrypoint polyfills [big] 575 KiB = runtime.f0b83be3db90bb2c.esm.js 6.23 KiB polyfills.ceee0f49f2a9ea1a.esm.js 569 KiB
Entrypoint styles 6.23 KiB = runtime.f0b83be3db90bb2c.esm.js 6.23 KiB styles.ef46db3751d8e999.css 0 bytes
chunk (runtime: runtime) main.435cd701ccd77263.esm.js (main) 193 KiB [initial] [rendered]
chunk (runtime: runtime) polyfills.ceee0f49f2a9ea1a.esm.js (polyfills) 545 KiB [initial] [rendered]
chunk (runtime: runtime) styles.ef46db3751d8e999.css (styles) 50 bytes (javascript) 81 bytes (css/mini-extract) [initial] [rendered]
chunk (runtime: runtime) runtime.f0b83be3db90bb2c.esm.js (runtime) 3.23 KiB [entry] [rendered]
webpack compiled successfully (34c590470eb2d1d6)
```
babel:
```
Entrypoint main 161 KiB = runtime.54e36ebee261465d.esm.js 1.19 KiB main.edbb481395ce144a.esm.js 160 KiB
Entrypoint polyfills 93.1 KiB = runtime.54e36ebee261465d.esm.js 1.19 KiB polyfills.1222c95ab5422a7a.esm.js 91.9 KiB
Entrypoint styles 1.19 KiB = runtime.54e36ebee261465d.esm.js 1.19 KiB styles.ef46db3751d8e999.css 0 bytes
chunk (runtime: runtime) main.edbb481395ce144a.esm.js (main) 174 KiB [initial] [rendered]
chunk (runtime: runtime) polyfills.1222c95ab5422a7a.esm.js (polyfills) 300 KiB [initial] [rendered]
chunk (runtime: runtime) styles.ef46db3751d8e999.css (styles) 50 bytes (javascript) 81 bytes (css/mini-extract) [initial] [rendered]
chunk (runtime: runtime) runtime.54e36ebee261465d.esm.js (runtime) 3.23 KiB [entry] [rendered]
webpack compiled successfully (95ef406388649385)
```

**Comment by GraxMonzo** [comment]
Temporary solution by providing custom webpack config for production:
`project.json`:
```json
{
   ...
  "production": {
    ...
    "webpackConfig": "apps/shell/webpack.config.prod.js"
  }
}

```
`webpack.config.prod.js`;
```js

/**
 * @param {import('webpack').Configuration} config
 * @param {any} context
 * @return {Promise<import('webpack').Configuration>}
 * */
module.exports = async (config, context) => {
  if (!config.optimization) {
    config.optimization = {};
  }
  config.optimization.minimize = true;

  return config;
};
```

**Comment by GraxMonzo** [comment]
Unfortunately passing `minify: true` to swc-loader options doesn't help.
https://github.com/nrwl/nx/blob/c3bd976d40bc147e7418ee1e3171f79c696b22cc/packages/web/src/utils/config.ts#L104-L123

**Comment by NiklasPor** [comment]
I just came across it and this is still happening. Maybe connected to other SWC issues with dead code removal.
