### ISSUE TITLE
Renaming app breaks implicitDependencies

### ISSUE THREAD

**Issue by dherges** [nrwl/nx#1182]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

1. `ng g app foo`
2. `mv apps/foo apps/foo-app`
3. edit `angular.json` and rename project `foo` to `foo-app`, edit all occurences of `apps/foo` to`apps/foo-app`

## Expected Behavior

`yarn dep-graph` runs through

## Current Behavior

throws cannot read property "type" of undefined

What is the current behavior?

implicit dependency from e2e project to app is set up with:

`key.replace(/-e2e/, '')`

thus implicit depndency from `foo-e2e` to `foo`, but `foo` was renamed to `foo-app`

https://github.com/nrwl/nx/blob/master/packages/schematics/src/command-line/shared.ts#L276

Workaround is:

rename in `angular.json`, project `foo` to `foo-app` and `foo-e2e` to `foo-app-e2e` (the project key in json is considered for implicit dependency)

### Steps to Reproduce

see above, prioject keys for `app` and `app-e2e` are out of sync, thus the above error message.

**Comment by FrozenPandaz** [comment]
We added the feature to define your own `implicitDependencies` so you can do it that way. We intend to write a migration which would add the current e2e implicit dependencies to the declared ones and deprecate the e2e implicit dependencies.
