### ISSUE TITLE
What happened to guides?

### ISSUE THREAD

**Issue by mrlubos** [nrwl/nx#11839]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/guides

### Additional context or description

The guides completely disappeared. There are no redirects, no info as to what might've happened, just poof. Gone.

**Comment by mandarini** [comment]
Can you try [this page](https://nx.dev/concepts/more-concept-guides)? I respect the expectation for a redirect or a similar approach, but as a workaround at the moment you can use the quicksearch feature to find the pages that are moved to new locations! Thank you for reporting the issue! :)

**Comment by mrlubos** [comment]
Hi @mandarini! Thank you for the quick response, that workaround helps. I found out about this issue by following a broken link, so I didn't think to search for the page.
