### ISSUE TITLE
hitting alot of docs links NOT FOUND and unable to sift thru docs from google

### ISSUE THREAD

**Issue by kenatwex** [nrwl/nx#11844]
### Documentation issue
hitting alot of docs links NOT FOUND and unable to sift thru docs from google

### Is there a specific documentation page you are reporting?

[Enter the URL or documentation section here.](https://nx.dev/structure/applications-and-libraries)

**Comment by kenatwex** [comment]
this particular one came from this google link

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiQ6byi2vX5AhUKjYkEHa9uAgQQFnoECBAQAQ&url=https%3A%2F%2Fnx.dev%2Fstructure%2Fapplications-and-libraries&usg=AOvVaw2dDGFiWRgTLmBFwcyYagcX

**Comment by mandarini** [comment]
Hi there, thanks for filing an issue! I understand the frustration! In the meantime, if the links do not work, you can try using the quicksearch box to find the page you are looking for! :) Let me know if this helps! For example, the above page can be found here: https://nx.dev/more-concepts/applications-and-libraries

**Comment by pct-cclausen** [comment]
It seems pretty much all google hits on nx.dev yield a 404?
