### ISSUE TITLE
https://nx.dev/module-federation/micro-frontend-architecture

### ISSUE THREAD

**Issue by hawaijar** [nrwl/nx#11841]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.

https://nx.dev/module-federation/micro-frontend-architecture

### Additional context or description

The url is no longer available.

Provide any additional details here as needed.

**Comment by mandarini** [comment]
Can you try [this page](https://nx.dev/more-concepts/micro-frontend-architecture)? I respect the expectation for a redirect or a similar approach, but as a workaround at the moment you can use the quicksearch feature to find the pages that are moved to new locations! Thank you for reporting the issue! :)

**Comment by hawaijar** [comment]
Thanks, that works!

**Comment by bcabanes** [comment]
Closing issue with https://github.com/nrwl/nx/pull/11850.
