### ISSUE TITLE
eleventy don't render txt file in tutorial 

### ISSUE THREAD

**Issue by pikooli** [nrwl/nx#11843]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/core-tutorial/03-share-assets

### Additional context or description

In this page you ask to change the file packages/blog/src/posts/ascii.md with this code :

   ```&#123;% renderFile "../ascii/assets/cow.txt" %&#125; ```

But it do not work 

I change it with this and it work : 

   ```{% renderFile "../ascii/assets/cow.txt" %}```

**Comment by FrozenPandaz** [comment]
Good catch, would you or anyone else like to send a PR to fix the documentation? The file is here: https://github.com/nrwl/nx/blob/master/docs/shared/core-tutorial/03-share-assets.md

**Comment by hayawata3626** [comment]
I am thinking of trying it, is it ok?

**Comment by outsideris** [comment]
It seems fixed by #11768 .

**Comment by bcabanes** [comment]
Fixed by #12206.
