### ISSUE TITLE
NX   Cannot read properties of undefined (reading 'externalNodes') when running nx run-ios mobile

### ISSUE THREAD

**Issue by Celleb** [nrwl/nx#11865]
I am running `nx run-ios mobile` for react-native project and I am getting an error

## Current Behavior

The execution fails with the following error:

```sh
 >  NX   Cannot read properties of undefined (reading 'externalNodes')
```

## Expected Behavior

The execution completes successfully

## Steps to Reproduce

1. `npx nx g @nrwl/react-native:app mobile` 
2. `nx run-ios mobile

### Failure Logs

```sh
TypeError: Cannot read properties of undefined (reading 'externalNodes')
    at findAllNpmDependencies (/Users/nx/dev/mobile/node_modules/@nrwl/react-native/src/utils/find-all-npm-dependencies.js:11:24)
    at /Users/nx/dev/mobile/node_modules/@nrwl/react-native/src/executors/sync-deps/sync-deps.impl.js:23:78
    at Generator.next (<anonymous>)
    at /Users/nx/dev/mobile/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/nx/dev/mobile/node_modules/tslib/tslib.js:114:16)
    at syncDeps (/Users/nx/dev/mobile/node_modules/@nrwl/react-native/src/executors/sync-deps/sync-deps.impl.js:22:20)
    at runIosExecutor_1 (/Users/nx/dev/mobile/node_modules/@nrwl/react-native/src/executors/run-ios/run-ios.impl.js:20:137)
    at runIosExecutor_1.next (<anonymous>)
    at resume (/Users/nx/dev/mobile/node_modules/tslib/tslib.js:230:48)
```

### Environment

```sh
 >  NX   Report complete - copy this into the issue template

   Node : 17.1.0
   OS   : darwin x64
   yarn : 1.22.15
   
   nx : 14.5.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.4
   @nrwl/detox : 14.5.4
   @nrwl/devkit : 14.5.4
   @nrwl/eslint-plugin-nx : 14.5.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.4
   @nrwl/js : 14.5.8
   @nrwl/linter : 14.5.4
   @nrwl/nest : 14.5.8
   @nrwl/next : Not Found
   @nrwl/node : 14.5.4
   @nrwl/nx-cloud : 14.4.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.8
   @nrwl/react-native : 14.5.8
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.8
   @nrwl/web : 14.5.4
   @nrwl/workspace : 14.5.4
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
```

**Comment by AgentEnder** [comment]
Hey @Celleb, it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

**Comment by dennisschneider** [comment]
had the same issue ... running `nx migrate latest` fixed it for me

**Comment by xiongemi** [comment]
could you provide an example repo? maybe try run `nx migrate latest` as mentioned above?

**Comment by bsplosion** [comment]
> had the same issue ... running `nx migrate latest` fixed it for me

Migrating to latest brought up v15 which was undesirable for us due to a few other dependencies requiring big changes, but you can also migrate to any version from what I can tell, so we were on 14.5.2 and ran `nx migrate 14.8.6` which worked beautifully.  I still couldn't tell exactly what changed to fix the issue itself in the migration, however.

**Comment by Celleb** [comment]
Migrating works
