### ISSUE TITLE
Watching for Changes (Headed Mode) bad example

### ISSUE THREAD

**Issue by tamtakoe** [nrwl/nx#11878]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/packages/cypress#watching-for-changes-(headed-mode)

```
nx e2e frontend-e2e --prod
```

Should be
```
nx e2e frontend-e2e --watch
```

**Comment by tamtakoe** [comment]
And there is unclear how to use `--prod` flag. I see some difference of e2e logs (error if --prod mode https://nx.dev/packages/cypress#testing-applications), but I don't understand why.

**Comment by barbados-clemens** [comment]
docs just look to be outdated. for --prod, just use configurations (if they are set up in your cypress executor) --configuration=production
