### ISSUE TITLE
Cannot find @nrwl/node document

### ISSUE THREAD

**Issue by alt1o** [nrwl/nx#11871]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.

### Additional context or description

Provide any additional details here as needed.

**Comment by alt1o** [comment]
https://user-images.githubusercontent.com/21084335/188427767-6d37faa7-c44b-49c5-8c76-9da3c60b39d1.mov

**Comment by AgentEnder** [comment]
Duplicate of #11863
