### ISSUE TITLE
[Question] How does this compare to alternatives?

### ISSUE THREAD

**Issue by lonix1** [nrwl/nx#1187]
The docs are good, but something is missing. How does this compare to similar tools, e.g. [lerna](https://github.com/lerna/lerna)?

Can someone please advise the factors to consider when choosing the one or the other (or other alternatives)? Presumably there is overlap, but also I would assume one is better suited for some scenarios and the other is suitable for others.

Any advice would be appreciated!

**Comment by xmlking** [comment]
I wish #nx sopport lerna style release management , essentially useful for publishing lib modules

**Comment by FrozenPandaz** [comment]
I'll leave a brief answer here but I think it would be helpful to have some formal FAQs section for our docs.

Lerna is good at easily running _everything_. It is probably better for doing things like publishing a set of libraries. 

Nx is intelligent about how to run tasks on the workspace. Nx workspaces can have many internal projects which do not need to be published. It can decide which projects need to be re-tested, rebuilt, etc. for a subset of changes. This makes the amount of "work" which needs to be done significantly more manageable when a workspace has 100+ projects.

**Comment by lonix1** [comment]
Thanks for explaining it to us! Makes more sense now... Maybe even a good idea to use both as @xmlking suggested for publishing workflows.

FAQ section would be very helpful. :+1: 

I don't know if you want me to close, or leave open for the FAQ idea.

**Comment by xmlking** [comment]
Would be nice if nx support `ng publish my-public-module`,  `ng affected:publish --base=origin/master --head=HEAD`,  then we don’t need Lerna. Yes we also need version management support

**Comment by lonix1** [comment]
@xmlking Probably a good idea to have that in a separate issue so we don't forget about it. If enough people like the idea maybe we can have that feature one day. I'll upvote you.
