### ISSUE TITLE
NX cloud documentation improvement request

### ISSUE THREAD

**Issue by g-cheishvili** [nrwl/nx#11880]
### Documentation issue
- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?
Pages where examples of usage of nx/ci workflows are given

### Additional context or description
Please mention somewhere that if you are using a mix of your custom workflows and workflows from [nrwl/ci](https://github.com/nrwl/ci) you need to make sure that the same tokens are used for agents and main runners. The issue is that if you want to do something advanced, which is not covered by [nx-cloud-main](https://github.com/nrwl/ci/blob/main/.github/workflows/nx-cloud-main.yml) and want to write your own version of the main runner, you need to pass [secrets](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow) properly to agent runners if you do not plan to have custom agents too. Otherwise, you will end up with different tokens used in starting workflow and starting agent, which will lead to unexpected results.

Also, it would be better if doc mentioned that even if you do not do anything crazy, setting `NX_CLOUD_AUTH_TOKEN` or `NX_CLOUD_ACCESS_TOKEN` in caller env workflow will not do much if you have a read-only token set in nx.json and in CI you have a read-write token. main and agents workflows will still use the read-only tokens from the nx.json, because they do not have access to the secrets, and secrets and inputs are the only way to pass down those values to nx/ci's workflows

P.S
Thank you so much for providing such amazing tools

**Comment by StalkAltan** [comment]
@g-cheishvili Good find! We recently discovered this but have not gotten a chance to fix it.

To clarify a bit, you shouldn't need to use the exact same token on your main and agent jobs, but you *will* need to use tokens of the same type (i.e read with read, read-write with read-write). 

We are working on making the job fail if we detect a token mismatch, as well as clarifying the docs. I will keep this open so it can be publicly tracked, but the fix should be released fairly soon.

Thanks again for the report!
