### ISSUE TITLE
Migration to latest version

### ISSUE THREAD

**Issue by Kmarutsi** [nrwl/nx#11895]
## Current Behavior

after successfully migrating to the latest version, i try to run the project and it gives me the error below

 >  NX   Cannot read property 'endsWith' of undefined

   
   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".

## Expected Behavior

After migrating with nx migrate latest i expected a migrations.json file to appear but it did not 

## Steps to Reproduce
kudzaimarutsi@Kudzais-MacBook-Pro-3 econet-suite % npx nx migrate latest
✔ We noticed you are migrating to a new major version, but are not taking advantage of Nx Cloud. Nx Cloud can make your CI up to 10 times faster. Learn more about it here: nx.app. Would you like to add it? · No

Fetching meta data about packages.
It may take a few minutes.
Fetching nx@14.6.4

 >  NX   The migrate command has run successfully.

   - Package.json has been updated.
   - There are no migrations to run, so migrations.json has not been created.

 >  NX   Next steps:

   - Make sure package.json changes make sense and then run 'yarn',
   - To learn more go to https://nx.dev/using-nx/updating-nx
   - You may run 'yarn nx connect-to-nx-cloud' to get faster builds, GitHub integration, and more. Check out https://nx.app

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by AgentEnder** [comment]
What does nx report say?
