### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'testEnvironmentOptions')

### ISSUE THREAD

**Issue by airowe** [nrwl/nx#11891]
## Current Behavior

Unable to use Jest to test React Native project inside an Nx Monorepo

## Expected Behavior

@nrwl/jest:jest should run all tests in the React Native project, or running one test manually should succeed (or fail) based on the test predicate.

No, this has never worked on the repo I'm working with

## Steps to Reproduce

No, but couldn't find a Typescript or React Native app in that repo.

The web app in this monorepo is able to be tested, but the React Native app fails no matter how I kick off the tests with the following error:

### Failure Logs

` Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'testEnvironmentOptions')

      at new NodeEnvironment (../../node_modules/jest-environment-node/build/index.js:96:49)
      at async TestScheduler.scheduleTests (../../node_modules/@jest/core/build/TestScheduler.js:333:13)
      at async runJest (../../node_modules/@jest/core/build/runJest.js:404:19)
      at async _run10000 (../../node_modules/@jest/core/build/cli/index.js:320:7)
      at async runCLI (../../node_modules/@jest/core/build/cli/index.js:173:3)`

### Environment

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : darwin arm64
   npm  : 8.19.1

   nx : 13.8.3
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.3
   @nrwl/cypress : 13.8.3
   @nrwl/detox : 13.8.3
   @nrwl/devkit : 13.8.3
   @nrwl/eslint-plugin-nx : 13.8.3
   @nrwl/express : undefined
   @nrwl/jest : 13.8.3
   @nrwl/js : 13.8.3
   @nrwl/linter : 13.8.3
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : 13.8.3
   @nrwl/react-native : 13.8.3
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.3
   @nrwl/tao : 13.8.3
   @nrwl/web : 13.8.3
   @nrwl/workspace : 13.8.3
   typescript : 4.4.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

**Comment by rmarku** [comment]
same problem here with a nextjs app and lib

### Enviroment

   Node : 16.17.0
   OS   : linux x64
   pnpm : 7.2.0
   
   nx : 14.5.10
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.10
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.10
   @nrwl/eslint-plugin-nx : 14.5.10
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.10
   @nrwl/js : 14.5.10
   @nrwl/linter : 14.5.10
   @nrwl/nest : 14.5.10
   @nrwl/next : 14.5.10
   @nrwl/node : 14.5.10
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.10
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.10
   @nrwl/web : 14.5.10
   @nrwl/workspace : 14.5.10
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nx-go/nx-go: 2.6.0
         @nx-tools/nx-docker: 3.0.3

**Comment by rexkenley** [comment]
I am experiencing the same issue. My current workaround is to delete the testEnvironment property in jest.config.

I also tried jest-environment-jsdom and jest-environment-node, they didn't work.
listed in the [documentation](https://jestjs.io/docs/configuration#testenvironmentoptions-object) 

![image](https://user-images.githubusercontent.com/10548251/189439812-0f9903eb-05ba-41f6-ab27-37e6a7cdf1d8.png)

**Comment by barbados-clemens** [comment]
@rexkenley @rmarku @airowe do any of y'all have a reproducible I can clone down to take a look at? all the default tests generated seems to be working in our e2e tests.

**Comment by coderroggie** [comment]
Same issue here. Removing the testEnvironment: "node" in the jest.config file did not fix it for me, just caused other problems.

**Comment by coderroggie** [comment]
I have fixed my issue by adding and pinning the versions of jest-environment-node and jest-config to the same version as jest.

```
    "jest": "27.5.1",
    "jest-environment-node": "27.5.1",
    "jest-config": "27.5.1",
```

**Comment by nzcodarnoc** [comment]
I'm experiencing this issue.

**Comment by nzcodarnoc** [comment]
I ran `nx run dummy-e2e:test-ios:production` again, but with debugging to catch any unhandled errors and found this curiosity. My Prima facie reading is that instead of loading `./environment.js` it is doing some kind of unholey string substitution here. 

```sh
Exception has occurred: Error: Cannot find module 'jest-environment-./environment' from '/Users/conrad/dev/the-project/apps/the-app-e2e'
```

For reference `nx generate @nrwl/react-native:application dummy` creates the an `environment.js` file, and I believe it is this setting in `jest.config.js` (also generated) that is implicated.

```js
{
  "preset": "../../jest.preset",
  "verbose": true,
  "testEnvironment": "./environment", // <---- This here
  "testRunner": "jest-circus/runner",
  "globalSetup": "<rootDir>/global-test-setup.js",
  "testTimeout": 120000,
  "reporters": ["detox/runners/jest/streamlineReporter"],
  "testResultsProcessor": "../../node_modules/jest-junit-reporter",
  "setupFilesAfterEnv": ["<rootDir>/test-setup.ts"],
  "setupFiles": ["./jest-cucumber-config"],
  "transform": {
    "^(?!.*\\.(js|jsx|ts|tsx|css|json)$)": "@nrwl/react/plugins/jest",
    "^.+\\.[tj]sx?$": "babel-jest"
  }
}
```

**Comment by nzcodarnoc** [comment]
I have created a repo which reproduces this error:

https://github.com/nzcodarnoc/testEnvironmentOptionsDiagnostic

cc @barbados-clemens

**Comment by nzcodarnoc** [comment]
On reflection, commenting in a closed issue perhaps isn't the smartest thing I've done this week, so, I've opened a new issue for this at: https://github.com/nrwl/nx/issues/13518
