### ISSUE TITLE
Provide better understanding for `@angular/cli` as a dependency

### ISSUE THREAD

**Issue by emilio-martinez** [nrwl/nx#119]
The nrwl/nx workspace uses https://github.com/nrwl/fix-cli-build as a replacement for `@angular/cli`. Would you mind providing some documentation around:

- The scope of the changes between the original and the modified versions?
- The frequency at which changes are synced? For example, at the time of this writing `@angular/cli@1.5.4` is the stable version whereas `nrwl/fix-cli-build` is `1.5.0`.
- Plans to just use `@angular/cli` instead of `nrwl/fix-cli-build`?

**Comment by jwuliger** [comment]
I came here to find out the same thing for myself! Thanks @emilio-martinez 

I want to use the Angular CLI 1.6 RC for better NGSW integration. Thanks!

**Comment by vsavkin** [comment]
Answered the question in the wiki: https://github.com/nrwl/nx/wiki/FAQ
