### ISSUE TITLE
In @nrwl/nx/enforce-module-boundaries, add possibility to specify "allow" inside "depConstraints"

### ISSUE THREAD

**Issue by Grochni** [nrwl/nx#11909]
## Description
In the configuration for the @nrwl/nx/enforce-module-boundaries eslint rule, I would like to have the option to add a list of allowed imports for a specific source tag. This is currently possible only ouside of the `depConstraints`, so it applies to all `sourceTag`s.

The configuration I would like to use would look like this:
````
"@nrwl/nx/enforce-module-boundaries": [
  "error",
  {
    "depConstraints": [
      {
        "sourceTag": "scope:a",
        "allow": ["@foo/z/entry-point-1/**", "@foo/z/entry-point-3/**"],
        "onlyDependOnLibsWithTags": ["scope:x", "scope:y"]
      }
    ]
  }
]
````

## Motivation
My use case is, that I have a library `@foo/z` with a bunch of secondary entry points. In my other libraries, I would like to restrict the imports to only some of these entry points. As I cannot assign tags to secondary entry points, my only option is to completely restrict imports from `@foo/z` (by not adding its tags to `onlyDependOnLibsWithTags`) and use the `allow` option to specify the allowed exceptions.

The problem is, I cannot specify the `allow` option per `sourceTag`, but only globally. If I do so in my root .eslintrc.json file, it would apply to all my libraries, which makes it useless.

So what I do at the moment to achive this, is to add a seperate .eslintrc.json file to each library to specify the `allow` option in there. However, this overrides the whole rule configuration, so I need to copy all the other configuration into the library's .eslintrc.json file. This wouldn't be an issue if every library had a unique tag, but I have many libraries sharing the same tags, so whenever something in the rule's configuration changes, I need to copy that changed configuration to a number of libraries. This is very hard to maintain.

## Suggested Implementation
I briefly looked into the rule's code and I think adding an `allow` option inside the `depConstraints` would work fine. I don't know if I missed relevant implementation details thoug.

## Alternate Implementations
Another approach that would fix my specific use case is to allow tags for secondary entry points. I don't see how this would be achievable though and it's probably a lot more work than my suggestion.

**Comment by meeroslav** [comment]
Hi @Grochni,

This sounds like a reasonable feature. Would you like to try to implement it?

**Comment by meeroslav** [comment]
Closing this as a stale feature request
