### ISSUE TITLE
html encoding of liquid delimiters

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [nrwl/nx#11928]
### Documentation issue

- [X] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[Enter the URL or documentation section here.](https://nx.dev/core-tutorial/03-share-assets)

### Additional context or description
There has been some html encoding

`- &#123;% renderFile "../ascii/assets/cow.txt" %&#125;`
`+ {% renderFile "../ascii/assets/cow.txt" %}`

**Comment by bcabanes** [comment]
Fixed by https://github.com/nrwl/nx/pull/12206.
