### ISSUE TITLE
Default CircleCI Config Example Invalid

### ISSUE THREAD

**Issue by irazorx1** [nrwl/nx#11920]
### Documentation issue

- [x] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[Enter the URL or documentation section here.](https://nx.dev/recipe/monorepo-ci-circle-ci)

### Additional context or description
With no modifications made using both manual copy/paste and with using the copy button on the docs: 
```
#!/bin/sh -eo pipefail
# Unable to parse YAML
# mapping values are not allowed here
#  in 'string', line 33, column 15:
#               when: always
#                   ^
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
```

**Comment by isaacplmann** [comment]
Can we have some more information?  I'm going to close this issue.  If this is still a problem, please reopen it.
