### ISSUE TITLE
Changing a file referenced by a namedInput using {workspaceRoot} affects all packages

### ISSUE THREAD

**Issue by richard-ling** [nrwl/nx#11922]
## Current Behavior
When a project.json contains a namedInput using a glob that begins with `{workspaceRoot}`, and a file matching the glob is changed, every package is affected.

It does not matter whether any target uses the namedInput.

## Expected Behavior
Only the project that defines the namedInput should be affected, and then only if it is used in a target.

If the namedInput is never used, no projects should be affected.

## Steps to Reproduce

* In a monorepo with multiple packages, create a temporary branch
* Choose a project.json and add the following namedInput:

    "namedInputs": {
        "foo": ["{workspaceRoot}/foo.js"]
    },

* Commit the changes to the temporary branch
* Run `nx print-affected --select=projects --base=HEAD`, confirm there are no affected packages
* Run `touch foo.js` to create the file (or modify it if it exists)
* Run `nx print-affected --select=projects --base=HEAD`

Every package is affected.

The reason seems to be code in `getImplicitlyTouchedProjects`. It collects `namedInputs` from all packages, and if they start with `{workspaceRoot}`, adds them to `globalFiles`. If any file matching `globalFiles` has changed, all packages are affected.

To work around this, I tried to reference the file using:

    "namedInputs": {
        "foo": ["{projectRoot}/../../foo.js"]
    },

but this fails to detect any change, because file paths in `fileChanges` never contain `..`.

So, there is an assumption that a file that exists outside of any package, must be depended on by all packages or by none, rather than a single package or some subset of packages.  In my case, this is not correct.

### Environment
    
       Node : 16.14.0
       OS   : darwin x64
       yarn : 1.22.19
       
       nx : 14.6.5
       @nrwl/angular : Not Found
       @nrwl/cypress : 14.6.5
       @nrwl/detox : Not Found
       @nrwl/devkit : 14.6.5
       @nrwl/eslint-plugin-nx : Not Found
       @nrwl/express : Not Found
       @nrwl/jest : 14.6.5
       @nrwl/js : 14.6.5
       @nrwl/linter : 14.6.5
       @nrwl/nest : Not Found
       @nrwl/next : Not Found
       @nrwl/node : Not Found
       @nrwl/nx-cloud : 14.6.1
       @nrwl/nx-plugin : Not Found
       @nrwl/react : Not Found
       @nrwl/react-native : Not Found
       @nrwl/schematics : Not Found
       @nrwl/storybook : Not Found
       @nrwl/web : 14.6.5
       @nrwl/workspace : 14.6.5
       typescript : 4.3.5
       ---------------------------------------
       Local workspace plugins:
       ---------------------------------------
       Community plugins:
    
    (node:39754) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/richard.ling/some/path/node_modules/tslib/package.json.
    Update this package.json to use a subpath pattern like "./*".
    (Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by tommyk** [comment]
+1

i was reading the code that is producing this list of global files, and i keep wondering why there would be a need for a "global" file.  seems like each project would have their own `namedInputs` that point to those files, which would get rid of the need for this "globals" and returning that all projects are affected via the value being `*`.

or if it was a `namedInput` in the root `nx.json` it would just be projects + targets that used said input.

ps. i am very new to `nx` itself (and the codebase) so i may be off in left field with these thoughts

https://github.com/nrwl/nx/blob/6d35fd4d85ca86d39a7518630f069b4d24fab887/packages/nx/src/project-graph/affected/locators/workspace-projects.ts#L31
