### ISSUE TITLE
Core Nx Tutorial - Step 1: Create Eleventy Blog

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [nrwl/nx#11926]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [X] Documentation improvement
- [X] Documentation feedback

### Is there a specific documentation page you are reporting?
[
Core Nx Tutorial - Step 1: Create Eleventy Blog](https://nx.dev/core-tutorial/01-create-blog)

### Additional context or description

There are some basic steps missing at the very beginning. When you have created a workspace there are not projects. By only adding a file to a directory without using a generator there will be no project files, hence `nx serve blog` will fail with `>  NX   Cannot find project 'blog'`

**Comment by sschneider-ihre-pvs** [comment]
Or, it is missing that you have to be inside package/blog for command execution

**Comment by ngoc199** [comment]
This issue is discussed [here](https://github.com/nrwl/nx/issues/11053).

You have to remove the `workspace.json` file for Nx to scan all the directories in the `packages` directory.
