### ISSUE TITLE
[Feature Request] Option --spec cli argument not exposed by the cypress builder

### ISSUE THREAD

**Issue by jordandlaman** [nrwl/nx#1192]
## Expected Behavior

Running ng e2e --headless --spec="app.spec.ts" should expose the spec flag that cypress has built in to allow you to selectively run a single spec.

## Current Behavior

Running ```ng e2e --headless --spec="app.spec.ts"``` pops 

```Unknown option: '--spec'```

Use case for this comes down to headless electron sometimes behaves differently than headed electron.  Need to be able to isolate a test with --headless to ensure the ci pipe runs smoothly.

**Comment by FrozenPandaz** [comment]
I think it would be a good feature. :) Does someone from the community want to try to implement it?

**Comment by ankeshdave** [comment]
@FrozenPandaz, I can look at this issue, can you provide me some direction on how to go about it :)

**Comment by jordandlaman** [comment]
Any updates?

**Comment by vsavkin** [comment]
Merged here: cf5ebf59d720e93ea78f92d58c69b3d126f9e703
