### ISSUE TITLE
Tutorial implies that `analyzeSourceFiles` is on by default

### ISSUE THREAD

**Issue by dwelch2344** [nrwl/nx#11933]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [X] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/core-tutorial/05-auto-detect-dependencies

### Additional context or description

Getting started with NX and building a few node applications + shared library, so needed to figure out how to create a distribution I could containerize. Discovered `generatePackageJson`, but the dependencies only listed `tslib` – finally realized it was because I didn't have `analyzeSourceFiles` set to `true` in my `nx.json`.

This makes sense and I'm not opposed to source scanning being off by default (if that's the intent) but the tutorial page doesn't specify you have to explicitly turn it on. I think it was easy to miss because the intro paragraph tells you it's possible, but then is immediately followed by a "side note" that shows you how to turn it off (implying it's on by default) 

I'd say either move the side note elsewhere, or have a heading along the lines of "how to turn on"

**Comment by AgentEnder** [comment]
Closing this, as its explicitly stated in the tutorial now.
