### ISSUE TITLE
Can't resolve 'dom' issue in lib folder

### ISSUE THREAD

**Issue by unrealisted** [nrwl/nx#11947]
## Current Behavior
Freshly created repo, 'dom' included in tsconfig.base.json, libs/features correctly extends. Tried to add manually 'dom' to tsconfigs of libs/features, nothing happened.

**tsconfig.base.json:**

{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "baseUrl": ".",
    "lib": [
      "es2020",
      "DOM",
      "WebWorker"
    ],
    "moduleResolution": "node",
    "typeRoots": [
      "node_modules/@types"
    ],
    "types": [
      "@types/node",
      "@types/jest",
      "@types/lodash",
      "moment",
      "network-information-types"
    ],
    "target": "es2020",
    "module": "esnext",
    "skipDefaultLibCheck": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "downlevelIteration": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "importHelpers": true,
    "alwaysStrict": true,
    "noImplicitThis": true,
    "strictFunctionTypes": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noImplicitAny": false,
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "declarationMap": true,
    "inlineSources": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noPropertyAccessFromIndexSignature": false,
    "strictPropertyInitialization": false,
    "paths": {
      "@front.ngnrwl/core": ["libs/core/src/index.ts"],
      "@front.ngnrwl/features": ["libs/features/src/index.ts"],
      "@front.ngnrwl/scss": ["libs/scss/src/index.ts"],
      "@front.ngnrwl/utils": ["libs/utils/src/index.ts"]
    }
  },
  "exclude": ["node_modules", "tmp"]
}

**features tsconfig:**

{
  "extends": "../../tsconfig.base.json",
  "files": [],
  "include": [],
  "references": [
    {
      "path": "./tsconfig.lib.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ],
  "compilerOptions": {
    "target": "es2020",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}

**features tsconfig.lib:**

{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "declaration": true,
    "declarationMap": true,
    "inlineSources": true,
    "types": []
  },
  "exclude": [
    "src/test-setup.ts",
    "**/*.spec.ts",
    "jest.config.ts",
    "**/*.test.ts"
  ],
  "include": ["**/*.ts"]
}

## Expected Behavior
Should inherit 'dom'.

### Failure Logs
`Error: libs/features/src/lib/directives/ifInViewport/ifInViewport.directive.ts:7:81 - error TS2304: Cannot find name 
'HTMLElement'.
protected readonly elementRef = inject(ElementRef<HTMLElement>);`

### Environment
`Node : 16.14.2
   OS   : darwin arm64
   npm  : 8.5.0
   
   nx : 14.6.5
   @nrwl/angular : 14.6.5
   @nrwl/cypress : 14.6.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.6.5
   @nrwl/eslint-plugin-nx : 14.6.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.6.5
   @nrwl/js : 14.6.5
   @nrwl/linter : 14.6.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.6.5
   @nrwl/web : 14.6.5
   @nrwl/workspace : 14.6.5
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @progress/kendo-angular-buttons: 8.0.0
         @progress/kendo-angular-common: 3.1.0
         @progress/kendo-angular-dateinputs: 7.1.1
         @progress/kendo-angular-dialog: 7.1.3
         @progress/kendo-angular-dropdowns: 7.1.0
         @progress/kendo-angular-grid: 7.2.4
         @progress/kendo-angular-indicators: 2.0.0
         @progress/kendo-angular-inputs: 9.0.4
         @progress/kendo-angular-intl: 4.1.0
         @progress/kendo-angular-l10n: 4.0.0
         @progress/kendo-angular-label: 4.0.1
         @progress/kendo-angular-layout: 7.1.2
         @progress/kendo-angular-menu: 4.0.1
         @progress/kendo-angular-notification: 4.0.0
         @progress/kendo-angular-popup: 5.0.0
         @progress/kendo-angular-progressbar: 3.1.1
         @progress/kendo-angular-ripple: 4.0.0
         @progress/kendo-angular-tooltip: 4.0.2
         @progress/kendo-angular-treeview: 7.1.1
         @rx-angular/cdk: 1.0.0-rc.1
         @rx-angular/state: 1.6.1
         @rx-angular/template: 1.0.0-rc.1`

**Comment by unrealisted** [comment]
Well, it was because of "webWorkerTsConfig": "apps/market/tsconfig.worker.json".
Somehow "lib" from this config affecting other directories

**Comment by tinesoft** [comment]
@unrealisted  did you find a proper fix?

I have the similar issue....

Your workaround of adding  "dom" in `"lib"` section of  the `tsconfig.worker.json` referenced in `"webWorkerTsConfig"` somehow worked...
 even if I obviously don't use DOM in my workers!

**Comment by unrealisted** [comment]
> 



> @unrealisted did you find a proper fix?
> 
> I have the similar issue....
> 
> Your workaround of adding "dom" in `"lib"` section of the `tsconfig.worker.json` referenced in `"webWorkerTsConfig"` somehow worked... even if I obviously don't use DOM in my workers!

No, i just deleted "tsconfig.worker.json", and then maybe created a new repo (can't remember)
