### ISSUE TITLE
process.cwd() refers to root and not the application directory

### ISSUE THREAD

**Issue by appsolutegeek** [nrwl/nx#1194]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Current Behavior

I created a node app (nestjs) and everything is working great but in the node app, I would like to use process.cwd() so that i can read a config file that i know is in the root of the application directory. The problem is launching this via

`ng serve`

`ng serve MyAppName`

the process.cwd always points to the location of where ng serve was run which is the root ... before the apps/myappname directory

Is there anyway to control this, what is everybody else doing ?

I could put some hacks in place by using the __filename and step back 1 directory from the main.ts - but its a kind of code smell.

I looked into the node-execute builder but I couldn't figure out anything there.

Any ideas ?

**Comment by appsolutegeek** [comment]
Ok, so I managed to get around it

I am using the following

`configFile = join(__dirname, "/config/.env")`

and I edited the angular.json and added to the asset block of the build. So this copies over the config directory to the dist directory and i am able to do the above.

SO this works, although it would be nice to know if the process.cwd can have the correct value.

**Comment by FrozenPandaz** [comment]
Hm.. There is no way to control this. We could accept the `cwd` as an option and pass it through. Is this because in `production` your application will be run from the same directory as the script? Using `__dirname` is generally more predictable in my experience.

**Comment by appsolutegeek** [comment]
Thanks @FrozenPandaz, agreed. I have it working now.

**Comment by charlie-nik** [comment]
I'm also running into this issue. Unfortunately, due to the way my project is set up, there's no way to work around it. @FrozenPandaz Would it be possible to include `cwd` as an option in the `@nrwl/node:node` executor? That'll make things much easier on my end. Much appreciated!
