### ISSUE TITLE
Core Nx Tutorial - Step 3: Share Assets

### ISSUE THREAD

**Issue by ngoc199** [nrwl/nx#11946]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

[https://nx.dev/core-tutorial/03-share-assets#tell-nx-about-the-dependencies](https://nx.dev/core-tutorial/03-share-assets#tell-nx-about-the-dependencies)

### Additional context or description

I have copied/pasted the `package.json` file to add the `ascii` as a dependency of the `blog` app. After adding, the blog does not display as before but shows the line `{% renderFile "../ascii/assets/cow.txt" %}` as the content instead.

To be sure this is not the `eleventy` issue, I have run the `nx graph` command and seen no connection between `blog` and `ascii`.

Does Nx know about the dependencies specified in the `package.json` file?

**Comment by ngoc199** [comment]
Moreover, the `blog` application is labeled as `Lib` in the Nx Graph.

Should the `blog` be an application?

**Comment by isaacplmann** [comment]
This tutorial is no longer linked from the getting started page.
