### ISSUE TITLE
virtual router token injection omitted for mfe architecture

### ISSUE THREAD

**Issue by kenatwex** [nrwl/nx#11954]
SUBJECT: virtual router token injection omitted for mfe architecture

## Current Behavior
this is about routing across the mfe spectrum and maintaining router context

Nx inspired manner to navigate across the mfe spectrum is to just use the router

- '/host-my-app'
- '/remote-cart'
- '/remote-home'

But the host <router-outlet> is required to initiate boot/load. But this host <router-outlet> gobbling up all subsequent routes preventing navigation or normal angular router modeling (ex side-nav outlet, canvas outlet... when I click a mfe route link in side-nav it targets the canvas route by virtue of the angular template but host gobbles it up and I am unable to navigate)

## Expected Behavior
A mechanism shold be implemented to virtualize mfe intended routers away from the isolated/separated (by nature) the browser dom. This was solved manually by Kyle Cannon in plain angular identifying this natural breach by angular alone

https://www.youtube.com/watch?v=fQrUGill9M0&ab_channel=ng-conf

https://github.com/kylecannon/angular-dream-stack

Nx should be guaranteeing our mfe routers 's are not victim to the gobbling up nature of plain angular or the browser

## Steps to Reproduce
implement a side-nav with links and a right hand side canvas all pointing to mfe routes
click link in side-nav
the entire page gets loaded instead of punched into the canvas
WHY?
because the host router config (which is needed on load) gobbles up all subsequent routes

Are standard plain vanilla named outlets the way forward to solve this?

Thanks for an elite product and any advice forward

more forum gabb on this issue

Im finding I cannot just route anywhere across mfe's... my host <router-outlet> is gobbling up mfe intended routes across the mfe spectrum... this issue appears to be addressed with plain angular manual implementation by Kyle Cannon https://www.youtube.com/watch?v=fQrUGill9M0&ab_channel=ng-conf by inducing virtual named outlets in order to synchronize a virtual token based router injection in order to virtualize the router per app/host/remote across the mfe spectrum contextualized and separated away from the browser dom... instead of a separated extrapolated isolated router injection anatomy across mfe's causing remotes to launch into their own isolated browser dom routing context destroying continuity across routers as they span across mfe's. Can someone from Nx team please attempt to address this? Has this been built into the Nx mfe architecture? Im finding Im heading into named outlets now but moreso the injected routers as well. Any feedback on this issue is greatly appreciated on what we need to do with the latest Nx release. My mfe monorepo is identical perfectly to the NX ng-module-federation example with regard to the routers and lazy loading entry modules and reachign into the shared libs and everything launches... But routing around the browser dom remain caught in nailing down the virtual router experience/implementation containing <router-outlet> coherency as they span mfe's . Im  wondering if this is already built into Nx and if not what are we to do?  my host <router-outlet> is gobbling up mfe intended routes across the mfe spectrum ... Thanks in advance

### Environment
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.17.0
   OS   : darwin arm64
   yarn : 1.22.18
   
   nx : 14.6.4
   @nrwl/angular : 14.6.4
   @nrwl/cypress : 14.6.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.6.4
   @nrwl/eslint-plugin-nx : 14.6.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.6.4
   @nrwl/js : 14.6.4
   @nrwl/linter : 14.6.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.6.4
   @nrwl/nx-cloud : 14.6.1
   @nrwl/nx-plugin : 14.6.4
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.6.4
   @nrwl/web : 14.6.4
   @nrwl/workspace : 14.6.4
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @fortawesome/angular-fontawesome: 0.10.2
   	 @ngrx/component-store: 14.2.0
   	 @ngrx/effects: 14.2.0
   	 @ngrx/entity: 14.2.0
   	 @ngrx/router-store: 14.2.0
   	 @ngrx/store: 14.2.0
   	 apollo-angular: 4.0.1
   	 @buildmotion/angular: 13.0.1
   	 @ngrx/schematics: 14.2.0
   	 @ngrx/store-devtools: 14.2.0
   	 @storybook/angular: 6.5.10

**Comment by kenatwex** [comment]
Will a supplemental config like this suffice?

const webpackConfig: Configuration = {
	output: {
		uniqueName: 'my-host',
		publicPath: '/',
	},
	experiments: {
		outputModule: true,
	},
	optimization: {
		runtimeChunk: false,
	},
	plugins: [
		new container.ModuleFederationPlugin({
			library: { type: 'module' },
			shared: {
				'@angular/core': { singleton: true },
				'@angular/common': { singleton: true },
				'@angular/router': { singleton: true },
				'@angular/common/http': { singleton: true },
				'@wex/ui-angular-components': { singleton: true }
			}
		})
	]
}

**Comment by Coly010** [comment]
Can you provide a repository with what you have so far so I can take a look?

It also might help me understand the problem better. I'm not entirely sure what you mean by "gobbling up all subsequent routes". 

To me it almost sounds like you want a child router-outlet that should load the contents of a side-nav page. This still feels like it could be solved using Angular primitives, but I need a repository of the problem to understand and investigate this issue.

**Comment by kenatwex** [comment]
Hi Column,

Im under way too much at this time to carve out a repo on this. My apologies.

Have you checked out Kyle Cannon's video? I mean its fairly easy to see what he implemented. A virtual dom coupled router obfuscator by a singleton root token injected router thats virtual across all MFE's. My sidenav is precisely how you stated with an embedded router-outler but since the browser and dom are dominating the routing (app/host/remote & its router) the host router is always the one who started routing on boot and subsequent routes thru the routing have to go back to the host for any/every remote.

I had hoped Nx implemented this mechanism via a static mfe vs dynamic mfe (which would imply static router token injected or dynamic browser dom router)

Anyway heres a blip of what I got

HOST (app.routing.module.ts)
```
const routes: Routes = [
  {
    path: '',
    redirectTo: '/remote-auth',
    pathMatch: 'full',
  },
  {
    path: 'remote-auth',
    loadChildren: () =>
      loadRemoteModule('remote-auth', './Module').then(
        (m) => m.RemoteEntryModule
      ),
  },
  {
    path: 'remote-nav',
    canActivate: [AuthenticatedGuard],
    loadChildren: () =>
      loadRemoteModule('remote-nav', './Module').then(
        (m) => m.RemoteEntryModule
      ),
  }
}
```

Login module loads fine I authenticate and control yeilds back to the host because login module routed (as you advised) using this cmd

`      this.router.navigate(['/remote-nav']);`

so that route takes control back to the host
code above shows where this route causes the host to navigate to which mfe and lazy load and its the NAV

Nav module loads fine but it does not get projected into the correct <router-outlet>
why?

because this is the host template
`<router-outlet></router-outlet>`

and so my nav template and its <router-outlet> never get reached

this obviates the need for virtual token injected routers to obfuscate the browser dom associated to each app/router

watch the video it really makes sense

and I need to know if Nx team implemented this mechanism or now

or what Im suppose to do at this point

Thank you

**Comment by kenatwex** [comment]
> To me it almost sounds like you want a child router-outlet that should load the contents of a side-nav page. 

I already have that Colum, see above

**Comment by kenatwex** [comment]
The only thing I can spot inside nxconsole is this parameter

```
dynamic
boolean
Default: false
Should the host application use dynamic federation?
```

and I think this only has to do with locating the actual module of the mfe

nothing to do with token based virtual routing across all MFE's

so this is a major show stopper for us

any help is greatly appreciated.

**Comment by Coly010** [comment]
I need to see your `NavigationModule` 

We view Federated apps as one single app, so there should only be one router. It's set up as a singleton across all places. So if your child routing setup has been done correctly, i.e. your remote app is using a router outlet with named router-outlet, then it should work fine

**Comment by kenatwex** [comment]
Okay I will provide that... but this discussion has a repo asking for this very thing too just for reference thanks Colum
https://github.com/nrwl/nx/discussions/10599

**Comment by kenatwex** [comment]
Here is the app.module for remote named **/remote-nav**

```
@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,

    RouterModule.forRoot(
      [
        {
          path: '',
          canActivate: [AuthenticatedGuard, RoleGuard],
          loadChildren: () =>
            import('./remote-entry/entry.module').then(
              (m) => m.RemoteEntryModule
            ),
        },
      ],
      { initialNavigation: 'enabledBlocking' }
    ),
  ],
  providers: [AdminGuard, RoleGuard, AuthenticatedGuard],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

**Comment by kenatwex** [comment]
and here is his entrymodule

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    RouterModule.forChild([
      {
        path: '',
        canActivate: [AuthenticatedGuard],
        loadChildren: () =>
          import('@wexinc/shared-root-ui-components').then(
            (m) => m.ComponentsModule
          ),
      },
    ]),
  ],
  providers: [],
})
export class RemoteEntryModule {}


we are lazy loading shared modules inside libs who have routes themselves

**Comment by kenatwex** [comment]
Okay I will provide that... but this discussion has a repo asking for this very thing too just for reference thanks Colum
https://github.com/nrwl/nx/issues/7268

**Comment by kenatwex** [comment]
> We view Federated apps as one single app, so there should only be one router. It's set up as a singleton across all places. So if your child routing setup has been done correctly, i.e. your remote app is using a router outlet with named router-outlet, then it should work fine

Thanks Colum.... I appreciate your assertion but what Im seeing is the route is being gobbled up by the host <router-outlet>
Now the previous post you commented on back in 2021 and your solution was PATHED route configurations? Am I correct for saying that?

Well this is good news fed apps are one big single app and one router singleton thats promising.

My route is still being gobbled up though

sorry to be a pest

**Comment by kenatwex** [comment]
So the lazy loaded Navigation module should have an empty index route of single quotes as follows just like a lazy loaded feature module

`          path: '',`

and your saying it might need to be

`          path: 'remote-nav',`

?

**Comment by kenatwex** [comment]
Our goal is to also be able to alter the url by hand and enter REST urls like 

```
http://localhost:4200/user/1
http://localhost:4200/user/2
http://localhost:4200/user
```

**Comment by Coly010** [comment]
@kenatwex Can you take a look at my repo, where I have tried to create an example based on what you've said, to determine what the key differences are?

This repo uses

Host -> Remote -> Lazy Loaded Side Nav -> Lazy loaded pages into portion beside Side Nav

https://github.com/Coly010/nx-ng-mf-route

**Comment by kenatwex** [comment]
Okay thanks COlum

maybe I can break it for you to show you what Im up against in my camp

I will try and get to it

definitely feedback tomorrow

**Comment by kenatwex** [comment]
Hi Colum,

I removed all my routes... 

```
core.mjs:7643 ERROR Error: Uncaught (in promise): Error: NG04002: Cannot match any routes. URL Segment: 'remote-auth'
Error: NG04002: Cannot match any routes. URL Segment: 'remote-auth'

```

So it seems I need to lazy load my initial module to kick start the routing experience.

But Im hoping it will work for our setup. They really deviated and went south on me so Im hoping to get this right Im maximizing separation its appropriate. I just hope my routes dont get lost anywhere so do you think I need to PATH the routes anywhere or name routes? Ours is fairly heavy 20 remotes... one host. For instance should I name each remotes router with the name of the remote? I think you advised that for a guy back in 2021 for his members page.

I try and repeat your pattern on our monorepo and see what gives.

Thanks so much for going out of your way on this

feedback pendiing

**Comment by kenatwex** [comment]
So I was wondering why you did an eager load instead of a lazy load

because your remote is mylib

my remote is remote-auth which does login or single sign on and lazy loads what I have for MYLIB which is my other MFE remote-nav

so my host funnels everything into remote-auth to get to remote-nav and everything is lazy loaded

and im still getting this

```
ERROR Error: Uncaught (in promise): Error: NG04002: Cannot match any routes. URL Segment: ''
Error: NG04002: Cannot match any routes. URL Segment: ''
    at ApplyRedirects.noMatchError (router.mjs:3644:16)

```

Do I need to specify remote-nav in my hosts list of remotes?

yours looks like this inside your host

```
module.exports = {
  name: 'host',
  remotes: ['remote1'],
};

```

do I need to specify remote-nav in my host like this?

```
module.exports = {
  name: 'host-yeti',
  remotes: ['remote-auth', 'remote-nav'],
};

```

or maybe I need to list all 20 remotes?

Thanks for any further feedback

**Comment by kenatwex** [comment]
its this line that I cannot get past from my login remote-auth mfe template when I click login

`      this.router.navigate(['remote-nav']);`
```

error-handling.service.ts:65 ERROR Error: Uncaught (in promise): Error: NG04002: Cannot match any routes. URL Segment: 'remote-nav'
Error: NG04002: Cannot match any routes. URL Segment: 'remote-nav'
```

**Comment by kenatwex** [comment]
Hi Colum sorry if I confused you

this is the difference between yours and mine

your eager loading a lib module and lib routes

Im lazy loading an MFE that lazy loads a LoginModule that does auth and then does a template route navigation from the login.component template (which you said was legal to do) that leads to another MFE named remote-nav

and the remote-nav eager loads my Navigation component

does that sound clearer?

any feedback at this point? You might think?

Thank you!

**Comment by kenatwex** [comment]
I will try to give this some attention today the continuity of routing across mfe's is the issue that if functional in all cases there should be a valid route config to operate it

This issue would discover anything that this topic of route navigation within Nx MFE fails to articulate

The main topic being that Nx can and should navigate across all MFE's unimpeded

results pending

**Comment by kenatwex** [comment]
Hi Colum

I am allowed 8 hours per week to focus on this and I am today

**MFE ROUTING**

This is the language I am working right now.

Okay we need go discriminate what and when

**What do we route?**

- Mfe load
- Std route

**When do we route?**

- Your navigating in and around
- Each scenario has its own flavor
- Load scenario is obvious
- Load host load auth route to login

So we have 2 mfe loads and a std route

And we can get to our nav okay

Now lets characterize the next leg

What do we route?
When do we route?
Do we have a load scenario? No
We have a Link scenario, everything is loaded, navigation shows with links
Click Navigate the links to their respective MFE and punch it in
So we do have a load scenario but its flipped now

**Comment by kenatwex** [comment]
Hi Colum

Im working this now...

I successfully added paths to the remoteEntry modules in tsconfig for the initial remotes I need to navigate thru for the side-nav layout no outlet projected punch as of yet but it rendered because I used loadChildren to explicitly grab the remote entry module.

I didnt prefer that BUT i found I could do this instead

```
  {
    path: 'remote-nav',
    canActivate: [AuthenticatedGuard],
    loadChildren: () =>
      loadRemoteModule('remote-nav', './Module').then(
        (m) => m.RemoteEntryModule
      ),
  },

```

but this is yielding this error

Error: Call setRemoteDefinitions or setRemoteUrlResolver to allow Dynamic Federation to find the remote apps correctly.

**Comment by kenatwex** [comment]
Hi COlum,

I noticed yout netlify series... and its doing specific added configuration to webpack.config.js

are these really still required for host to find remotes?


```
/**
 * We use the NX_TSCONFIG_PATH environment variable when using the @nrwl/angular:webpack-browser
 * builder as it will generate a temporary tsconfig file which contains any required remappings of
 * shared libraries.
 * A remapping will occur when a library is buildable, as webpack needs to know the location of the
 * built files for the buildable library.
 * This NX_TSCONFIG_PATH environment variable is set by the @nrwl/angular:webpack-browser and it contains
 * the location of the generated temporary tsconfig file.
 */
const tsConfigPath =
  process.env.NX_TSCONFIG_PATH ??
  path.join(__dirname, '../../tsconfig.base.json');

const workspaceRootPath = path.join(__dirname, '../../');
const sharedMappings = new mf.SharedMappings();
sharedMappings.register(
  tsConfigPath,
  [
    /* mapped paths to share */
    '@mfe-netlify/shared/auth',
  ],
  workspaceRootPath
);

module.exports = {
  output: {
    uniqueName: 'dashboard',
    publicPath: 'auto',
  },
  optimization: {
    runtimeChunk: false,
  },
  experiments: {
    outputModule: true,
  },
  resolve: {
    alias: {
      ...sharedMappings.getAliases(),
    },
  },
  plugins: [
    new ModuleFederationPlugin({
      remotes: {
        todo: 'https://lucid-cray-c41a7f.netlify.app/remoteEntry.js',
        login: 'https://wonderful-euclid-5a7ba0.netlify.app/remoteEntry.js',
      },
      shared: {
        '@angular/core': { singleton: true, strictVersion: true },
        '@angular/common': { singleton: true, strictVersion: true },
        '@angular/common/http': { singleton: true, strictVersion: true },
        '@angular/router': { singleton: true, strictVersion: true },
        ...sharedMappings.getDescriptors(),
      },
      library: {
        type: 'module',
      },
    }),
    sharedMappings.getPlugin(),
  ],
};

```

**Comment by kenatwex** [comment]
Hi Column,

Im doing some route configs and getting error

`Error: Call setRemoteDefinitions or setRemoteUrlResolver to allow Dynamic Federation to find the remote apps correctly. Error: Call setRemoteDefinitions or setRemoteUrlResolver to allow Dynamic Federation to find the remote apps correctly. at http://localhost:4201/libs_shared_root_security_auth-ui_src_lib_login_login_module_ts`

can you answer to what setRemoteDefinitions is?
also setRemoteUrlResolver ?

**Comment by kenatwex** [comment]
This is my libs/login.module

```
  {
    path: 'remote-nav',
    loadChildren: () =>
      import('@wexinc/remote-nav/app/remote-entry/entry.module').then((m) => m.RemoteEntryModule),
  },
```

Is it legal and correct to use loadChildren to have my login component navigate to my remote-nav MFE ?

Im doing this as I originally showed using

`      this.router.navigate(['/remote-nav']);`

It renders but Im not sure if this is the elite normal inspired way for Nx... I had to define a tsconfig path to get my lids module to see this in order to import also eslint is barking saying cannot import from apps

Thanks Colum

**Comment by kenatwex** [comment]
Hi Colum,

Im routing all over and got my sidenav rendering with links on left but still unable to transclude my MFE into the outlet... 
I tried naming the outlet
I left it as default
I added prefix path because my routerlink from the router is showing /remote/nav/remote-dashboard for my dashboard sidenav link

all looks okay anatomically less my curious wondering questions above.

But it seems Im doing outlet projection with lazy loaded modules and standalone components in some cases

But for this outlet punch into my content <router-outler></router-outlet> it seems im transcluding (doing outlet projection) entire MFE's specifically their entryModules which lead to some lib component 

Is this legal to do outlet projection from the libs folders with entryModules of remotes?

If you get some time to try and answer I would be greatful.

Im happy to paypal you anything for your time $120 hr Im sure your very busy and you work very hard and deserve it.

Im available anytime

**Comment by kenatwex** [comment]
To support my questions about transcluding MFE's thru the router-outlet within the libs folder libraries during route navigation... it compiled no problem from auth to nav pages but now Im unable to build

```
   libs/shared/root/ui-layout/src/lib/ui-layout.module.ts:24:18 - error TS6059: File '/Users/w509297/PR/150305/Yeti-UI/apps/remote-dashboard/src/app/remote-entry/entry.module.ts' is not under 'rootDir' '/Users/w509297/PR/150305/Yeti-UI/libs/shared/root/ui-layout/src'. 'rootDir' is expected to contain all source files.
   
   24           import('@wexinc/remote-dashboard/app/remote-entry/entry.module').then((m) => m.RemoteEntryModule),
```

**Comment by kenatwex** [comment]
Hi Colum,

Im rendering my sidenav and still not projecting yet due to this small issue
Im knocking on the door of finishing this... but Im really stuck.

routers can project components, redirects, modules

but MFE's ?

here is my routeconfig for my UI module below

FACT: both attempts to load my dashboard (which should punch into the **_content_** pane right hand side) are below and yeild errors

QUESTION: Is it legal from the libs area to load MFE's from apps folder? I feel strange about it and had to define tsconfig paths to get those

How can I successfully load an MFE from libs folder UI.MODULE.ts

**LIBS/UI.MODULE.TS**
const routes: Routes = [
  {
    path: '',
    component: NavigationComponent,
    children: [
      {
        path: 'remote-nav/remote-dashboard',
        outlet: 'content',
        canActivate: [AuthenticatedGuard],
        // loadChildren: () =>
        //   import('@wexinc/remote-dashboard/app/remote-entry/entry.module').then((m) => m.RemoteEntryModule),

        loadChildren: () =>
          loadRemoteModule('remote-dashboard', './Module').then(
            (m) => m.RemoteEntryModule
          ),
      }
  }
]
}

**Comment by kenatwex** [comment]
`crbug/1173575, non-JS module files deprecated.
`
is the latter attempt above

the attempt commented out was yeilding rootDir errors complaining about the remoteEntryModule not living under the root folder of libs

**Comment by kenatwex** [comment]
Hi COlum,

I should be able to do this from my auth.module

```
  {
    path: 'remote-nav',
    canActivate: [AuthenticatedGuard],
    loadChildren: () =>
      loadRemoteModule('remote-nav', './Module')
        .then((m) => m.RemoteEntryModule)
  },
```

and im receiving this errors

`Error: Uncaught (in promise): Error: Call setRemoteDefinitions or setRemoteUrlResolver to allow Dynamic Federation to find the remote apps correctly. Error: Call setRemoteDefinitions or setRemoteUrlResolver to allow Dynamic Federation to find the remote apps correctly.`

I have all the remotes listed in my module.federation.config.js

```
module.exports = {
  name: 'host',
  remotes: [
    'remote-dashboard',
    'remote-nav',
    'remote-auth',
  ]
};
```

why isnt dynamic federations finding my remotes?

**Comment by Coly010** [comment]
You don't need dynamic federation in your case. You just need a standard `import`

**Comment by kenatwex** [comment]
Can MFE's survive router transclusion into any outlet positioned anywhere on a single page? Im wondering is Kyle Cannon's work needs attention in Nx. We are transcluding (projecting) entire MFE's into outlet's everywhere.

Is this legal with current Nx release on this MFE stuff or are there limitations?

Thank you
