### ISSUE TITLE
Wrong package name when using --directory for @nrwl/js:library

### ISSUE THREAD

**Issue by ThePlenkov** [nrwl/nx#11956]
**The problem**

When using directory option we make generate a package with the name like this:
```
"name": "@workspace/directory/project",
```
which brakes standard npm installer.

**Proposed solution**
For consistency purpose as you already use kebab case in project name in workspace.json package name should contain same name
```
"name": "@workspace/directory-project",
```

What do you think? THanks!

**Comment by nartc** [comment]
Hi @ThePlenkov, thank you for reporting. However, this is the intended behavior for libraries with secondary entry points. If you're planning to install the library, then use `importPath` to adjust the package name as well as the path alias to your likings and not break npm standard.

**Comment by ThePlenkov** [comment]
ok I see it - that's what importPath is for. The point is - I use such modules - not even for publishing - but simply to installing as workspace ( to keep using also standard npm workspaces features ). But ok - importPath make sense to me - because it's not about convertion rule - there may be principally different name - for nx project and npm package. So may be it make sense to keep this things separate - yes. Thank you for the help!
