### ISSUE TITLE
How to remove the generated feature or resolver using nx workspace-generator

### ISSUE THREAD

**Issue by devangparekh1** [nrwl/nx#11951]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.

### Additional context or description

Provide any additional details here as needed.

**Comment by FrozenPandaz** [comment]
Sorry, there's not enough information here. Please open a new issue with more information.
