### ISSUE TITLE
Cypress Builder not copying all the needed files

### ISSUE THREAD

**Issue by persistence911** [nrwl/nx#1195]
# Prerequisites
I am using the cypress builder for building and running e2e test in an angular application. I am also using the https://www.npmjs.com/package/cypress-cucumber-preprocessor plugin  which allow you to have a .feature extension in the folder. 

## Expected Behavior
During the build process the feature file located in the integration directory are not begin copied across into the dist folder.  I was wondering if it would be  beneficial to  have an extra configuration that can allow us specify and  array of folder path or extensions that needs to be copied over following a build.

## Current Behavior

The build process currently leaves the feature files in the integration directory.

### Context

Please provide any relevant information about your setup:

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.2.2
@angular/cli                      7.2.2
@ngtools/webpack                  7.1.4
@schematics/angular               7.2.2
@schematics/update                0.12.2
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.27.1

**Comment by TroyHouston** [comment]
Without this I cannot use the nx cypress builder, which makes things more tedious to set-up.
Did you find any reasonable workaround to this at present?

**Comment by vsavkin** [comment]
This is definitely something we need to make work. Do you want contribute a PR?

**Comment by TroyHouston** [comment]
I gave it a shot adding an option to copy files based on regex, see the PR above.

Realised a bit late that I branched from master which is for angular 8, but that should be out soon anyway,..

**Comment by mehrad-rafigh** [comment]
@vsavkin This issue can be closed. It has been resolved, as it seems.

**Comment by vsavkin** [comment]
@mehrad-rafigh you are right. Closing this issue.
