### ISSUE TITLE
nx-plugin: create a generator which creates a generator wrapping an existing generator

### ISSUE THREAD

**Issue by gioragutt** [nrwl/nx#11958]
- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I want to see introduced a generator (probably supplied by `nx-plugin`) that would create a generator that would wrap an existing generator.

The generated generator should not create any additional behavior by default other than calling the wrapped generator.
The schema should be reused from the wrapped generator:
* in the `.d.ts` schema, it should `extend` the wrapped generator's schema
* in the `.json` schema, it should copy all properties of the wrapped generator's schema

## Motivation

Creating a custom generator that wraps an existing one is, in my experience and as far as I've seen so far from places like the nrwl slack workspace, one of the most common use cases of creating a generator.

You want to reuse an existing generator's behavior, but add your custom shticks that are relevant to your project, like altering configuration or some files.

This isn't very difficult, but requires some knowledge about generators from the get-go:
1. How to import an existing generator
2. What's the proper way (or at least A way) of reusing the generator's schema, both `.d.ts` and `.json`.

This is something that takes time to perform, and is also something that's difficult for devs without prior experience in implementing custom generators.

Having a generator that would create all the required boilerplate would:
1. Save time when creating a new generator
2. Will be a living source of documentation of how to implement this behavior.

Due to the two reasons above, it would also make creating custom generators even more accessible, since it cuts down on even more friction devs have when thinking about implementing a custom generator.

## Suggested Implementation

```sh
yarn nx generate @nrwl/nx-plugin:wrapping-generator --name=react-application --project=my-local-workspace-plugin --generator=@nrwl/react:application
```

Output:

## TS Schema definition

It should create an interface which extends the wrapped generator schema.
Potential edge case would be getting the name of the exported interface from the wrapped generator.
In nrwl generators it's exported as `Schema`, but it might not be the case.
Some typescript AST introspection and heuristics might be required to implement this properly.

```ts
// schema.d.ts
import {Schema as WrappedApplicationSchema} from '@nrwl/react/src/generators/application/schema';

export interface ApplicationSchema extends WrappedApplicationSchema { }
```

## JSON Schema definition

The JSON schema properties should be copied over from the wrapped generator schema

## Implementation

The generated implementation would import the generator, and call it. This would be a starting point for developers to add their own customizations.

```ts
import wrappedApplicationGenerator from '@nrwl/react/src/generators/application/generator';
import {ApplicationSchema} from './schema';

export default async function applicationGenerator(tree: Tree, schema: ApplicationSchema): Promise<GeneratorCallback> {
  const callback = await wrappedApplicationGenerator(tree, schema);
  return () => callback();
}
```

## Alternate Implementations

IDK honestly, would be happy to hear feedback and any alternative thoughts.

## Sidenote

Another one of the points of friction for creating custom generators is that schema normalization applied by the generator internally is not exposed outside, which means that devs implementing custom generators have to compromise when implementing their code: They either cut down on properties passed down to wrapped generators, or implement a lot of the normalizations manually, to be able to handle the generator output properly (file names, etc).

Exporting the normalized schema, as well as the `normalizeSchema` function, as a standard of all (official) generators would remove this compromise since you'll be able to more easily handle different inputs to generators.

**Comment by AgentEnder** [comment]
Hey @gioragutt , I'll talk this over with @FrozenPandaz this coming week. I think rather than a full generator to do this automatically, it may be better to just have a guide demonstrating the technique.

The major pain point IMHO is that you have to replicate the schema.json of the generator that you are wanting to extend, I think this would be solvable by adding an "extends" property to schmea.json. 

That would have the caveat of not working for angular cli use cases, but I think that's an acceptable caveat at this point in time.

**Comment by AgentEnder** [comment]
I'm going to close this one out - while its not 100% the same, the biggest pain point here is not being able to extend or reference external schema.json files. That will be tracked via: https://github.com/nrwl/nx/issues/10890
