### ISSUE TITLE
node-build, getting the original __filename value before bundling ?

### ISSUE THREAD

**Issue by iangregsondev** [nrwl/nx#1199]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Before using NX I was using a logger and I pass in the __filename which would represent the real filename before bundling i.e. main.ts, logger.ts.

I would like to get access to the original filename, obviously, __filename is a node feature so at build time it returns the main.js - which is technically true as its been bundled. Its the current filename.

In angular (web frontend) - I got around this problem by doing the following in a custom webpack config builder via the angular.json

```
"customWebpackConfig": {
 "path": "./extra-webpack.config.js"
},
```

```
module.exports = {
  node: {
    __filename: true,
    __dirname: true
  },
```

The simulates the __filename for a frontend app by adding automatically a variable __filename in each file.

Is there a way around this ? I never bundles my node files before - so i never had this problem. But ng serve, bundles the files into a main.js

## Current Behavior

For example, I am using a logger, and inside I am using __filename and it outputs this

```
[2019-03-23T09:21:33.859] [INFO] /Users/ian/Development/Work/Nest/projects/api/dist/apps/api/main.js - THIS IS THE REAL LOGGER!!!
```

As you can see it outputs the bundles filename i.e. main.js.

I would like for it to output the original filename which in this case was actually a service called service-test.ts

But this information isn't available via __filename, of course.

What is the current behavior?

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

console.log(__filename)

Returns the bundle filename i.e. main.js ...

I would like to somehow get the original filename before bundling.

--

If I can provide better info then please let me know.

**Comment by FrozenPandaz** [comment]
This makes sense, especially for logging :)

Would it make sense to have an option such as `ng build --mock-node`?

Caveat:
I tend to depend on `__dirname` and others might too so I don't want to make it a breaking change so we should have a flag which is opt-in but generated by default for new apps.. and maybe default to
```json
{
  __filename: true,
  __dirname: true
}
```

**Comment by FrozenPandaz** [comment]
I haven't had the chance to make this change. Would somebody from the community like to contribute this?

**Comment by kerolos-sss** [comment]
I am simply using it for logging when there is an error 
I am having the issue 
Uncaught ReferenceError: __filename is not defined
