### ISSUE TITLE
Support @cypress/react18

### ISSUE THREAD

**Issue by tyler-morrison** [nrwl/nx#12006]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
The Cypress team recently published their [`@cypress/react18`](https://www.npmjs.com/package/@cypress/react) component. We should update `@nrwl/react` generators to support this new feature. We would need to add conditional logic to our generators to ensure that any updates are backward compatible with React v17

## Motivation
The `ReactDom.render` method is no longer supported in React v18, which is bundled with the old `mount()` command in `@cypress/react`
<img width="1004" alt="@cypress:react - v18 Warning" src="https://user-images.githubusercontent.com/8642365/190006815-d57bbafb-55c2-4c5c-8c03-9309d5eac3ec.png">

## Suggested Implementation
- Add [`@cypress/react18`](https://www.npmjs.com/package/@cypress/react) to core dependencies
- Update the logic for [`@nrwl/react:cypress-component-configuration` generator](https://github.com/nrwl/nx/blob/master/packages/react/src/generators/cypress-component-configuration/cypress-component-configuration.ts) to check a workspace's React version.
- Update [`@nrwl/react:component-test` generator](https://github.com/nrwl/nx/blob/master/packages/react/src/generators/component-test/files/__fileName__.cy__ext__) to conditionally use `@cypress/react18`.
- Create a migration script to automatically update existing component tests.

## Alternate Implementations
- Additional changes may be required within `@nrwl/cypress:cypress-component-project` generator

**Comment by tyler-morrison** [comment]
I'm down to submit the PR.

Question - Where do we ensure the `@cypress/react{18}` packages get installed?

I don't see them specifically mentioned in any of the `installDependencies` tasks. But I might have cruised by them in my original check.

**Comment by barbados-clemens** [comment]
I believe cypress package embeds them within the binary, so you don't need to install it dynamically, just the test generation dynamically. 

[From the next package](https://github.com/nrwl/nx/blob/master/packages/next/src/executors/build/build.impl.ts#L31) it looks like this is the check made
```ts
const hasReact18 =
    reactDomVersion &&
    gte(checkAndCleanWithSemver('react-dom', reactDomVersion), '18.0.0');
```

and should just need to make that check in the react [component-test generator] and pass it to the template(https://github.com/nrwl/nx/blob/master/packages/react/src/generators/component-test/component-test.ts#L90) 

the migration can be apart of the react package
and will look something like this.

```ts
const isCyFile = new RegEx(".*(cy).[tj]sx?$");

export function updateMountForReact18(tree: Tree) {

forEachExecutorOptions<CypressExecutorOptions>(tree, '@nrwl/cypress:cypress', (options, projectName, targetName, configurationName) => {
const projectConfig = readProjectConfiguration(tree, projectName);

  if(options?.testingType !== 'component' || !isUsingReact18) {
      return 
  }

  visitNotIgnoredFiles(tree, projectConfig.sourceRoot, (filePath) => {
    if(!isCyFile.test(filePath)){
      return 
    }
// use tsquery in this function to grab import statements and update to cypress/react18
    updateComponentTestImport(tree, filePath)
    })


  })

}

**Comment by tyler-morrison** [comment]
Totally dropped the ball on this guy 🙈

I'll prep an MR with a proposed resolution later today.

**Comment by tyler-morrison** [comment]
@barbados-clemens Sanity check – Does `@nrwl/react` support older versions of React?

Looking at the [`versions.ts`](https://github.com/nrwl/nx/blob/master/packages/react/src/utils/versions.ts) it looks like all users of this package are upgraded to a consistent version.

We might be able to omit React 17 support

**Comment by barbados-clemens** [comment]
I think you're right, though technically someone can down level their packages and still run v17. But in that case, we should only generate v18 react code and if people still want to use v17 then they can change the import back to `cypress/react` instead of `cypress/react18`

so in this case should check for v17 react versions on in the migration and skip the migration if people are still on v17 and just generate new stuff with v18 support.

Let me know if you need any help or have more questions :)

**Comment by barbados-clemens** [comment]
is now the default for React CT projects.
