### ISSUE TITLE
NX sub builds fail due to not finding type declarations

### ISSUE THREAD

**Issue by PatchOnKnee** [nrwl/nx#12008]
## Current Behavior
When an app that requires a lib is built, the lib build that is triggered uses the app tsconfig. This causes issues with custom namespace typings, which wont be found will cause the build to fail.

## Expected Behavior
When a lib build is triggered from an app, the lib build should use the correct tsconfig

## Steps to Reproduce
I've created a repo that can demonstrate the issue. It can be found [here](https://github.com/PatchOnKnee/literate-giggle).
Running `npx nx run test-lib:build` will be successful, however running `npx nx run test-app:build` produces this error:

```
../../libs/test-lib/src/lib/test-lib.ts:1:27
Type error: Cannot find module 'sometype' or its corresponding type declarations.

> 1 | import { Something } from 'sometype';
    |                           ^
  2 | 
  3 | export function testLib(something: Something): string {
  4 |   return something.is;

 >  NX   Call retries were exceeded
```

**Comment by FrozenPandaz** [comment]
If you add the following, you'll be good to go.

```diff
+ import './@types/custom.d';
export * from './lib/test-lib';
```

This will include those types along with the lib.

I would avoid declaring modules if possible. I would prefer to import the type from the file/ other project:

```diff
- declare module 'sometype' {
export interface Something {
  is: string;
}
- }
```

```diff
- import { Something } from 'something';
+ import { Something } from '../@types/custom';

export function testLib(something: Something): string {
  return something.is;
}
```
