### ISSUE TITLE
@nrwl/angular does not provide eslint, requested by @typescript-eslint/type-utils

### ISSUE THREAD

**Issue by bulldog98** [nrwl/nx#12013]
Updated from nx 14.6.5 to 14.7.5

## Current Behavior
yarn3 complains:
`@nrwl/angular@npm:14.7.5 [315e8] doesn't provide eslint (p1b3b2), requested by @typescript-eslint/type-utils`

## Expected Behavior
Yarn does not complain about eslint as missing peerDependency of @nrwl/angular, did not complain with version 14.6.5

## Steps to Reproduce
* Install @nrwl/angular in repo
* Run yarn install

Can be fixed by adding
`"eslint": "^8.23.0"` to the peerDependencies section of the package.json

**Comment by FrozenPandaz** [comment]
I don't think `@nrwl/angular` directly needs `eslint`? It is a `peerDependency` of `@nrwl/linter` though.

Sorry, I don't quite understand the issue. Could you explain it more? What is our `package.json`?
