### ISSUE TITLE
memoryLimit or maxWorkers are not acceptable parameters to pass in schema

### ISSUE THREAD

**Issue by Astrofyziky** [nrwl/nx#12015]
Minor issue with a workaround.

The _memoryLimit_ and _maxWorkers_ are not accepted types within the options for serving an application.  If they're not passed then the project runs.

A list of the accepted types can be found here:
[https://nx.dev/packages/webpack/executors/dev-server](https://nx.dev/packages/webpack/executors/dev-server)

## Current Behavior
A build error is thrown when trying to pass _memoryLimit_ or _maxWorkers_.

## Expected Behavior
It's expected that I am able to pass these parameters as an option, per the website

## Steps to Reproduce
create a workspace: `nx g @nrwl/workspace:workspace --name=myApp`

change the options in the project.json file to include the following:
`"options": {
        "browserTarget": "myApp:build",
        "publicHost": "http://localhost:4200",
        "watch": true,
        "liveReload": true,
        "hmr": false,
        "open": true,
        "memoryLimit": 55,
        "maxWorkers": 43
      }`

open terminal and type: `nx serve myApp`

See the output console for the build failure.  Remove the commands:
`"memoryLimit": 55,`
        `"maxWorkers": 43`
type: `nx serve myApp` and the app builds

### Failure Logs
The console output: 
>  NX   'memoryLimit' is not found in schema
>  NX   'maxWorkers' is not found in schema

### Environment
Node : 18.7.0
   OS   : win32 x64
   npm  : 8.1.3

   nx : 14.7.5
   @nrwl/angular : 14.7.5
   @nrwl/cypress : 14.7.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.5
   @nrwl/eslint-plugin-nx : 14.7.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.5
   @nrwl/js : 14.7.5
   @nrwl/linter : 14.7.5
   @nrwl/nest : 14.7.5
   @nrwl/next : Not Found
   @nrwl/node : 14.7.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.5
   @nrwl/web : 14.7.5
   @nrwl/workspace : 14.7.5
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

**Comment by ndcunningham** [comment]
Can you retry with the latest?
