### ISSUE TITLE
phantom dependencies in nx and @nrwl packages

### ISSUE THREAD

**Issue by troywweber7** [nrwl/nx#12021]
## Current Behavior

When installing `@nrwl/storybook` or `@nrwl/workspace` using `pnpm`, there appear to be a couple phantom dependencies.

## Expected Behavior

If either of these packages publish JS which directly depends on phantom dependencies, those phantom dependencies should be added to the appropriate `package.json`'s dependencies (or `peerDependencies`, if appropriate) so that Nrwl Nx can better support `pnpm` as it claims to do. The phantom packages I currently identified are shown below:

- `@nrwl/storybook/src/generators/configuration/configuration.js` directly depends on the following
    - `tslib`
- `@nrwl/workspace/src/utils/ast-utils.js` directly depends on the following
    - `@angular-devkit/schematics`
    - `@angular-devkit/core`
- `nx/src/adapter/ngcli-adapter.js` directly depends on the following
    - `@angular-devkit/core`
    - `@angular-devkit/schematics`
    - `@angular-devkit/architect`

## Steps to Reproduce

Here is the [original issue that caused me to stumble upon these phantom dependencies](https://github.com/nxext/nx-extensions/issues/808). This original issue contains reproduction steps as well as additional information for how to workaround the issue using a `pnpmfile.cjs` file. In that file, I ultimately identified the above offenders.

### Environment

```bash

 >  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : linux x64
   pnpm : 7.11.0
   
   nx : 14.7.5
   @nrwl/angular : 14.7.5
   @nrwl/cypress : 14.7.5
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/eslint-plugin-nx : 14.7.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.5
   @nrwl/js : Not Found
   @nrwl/linter : 14.7.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.7.5
   typescript : 4.8.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @ionic/angular: 6.2.7
   	 @nxext/ionic-angular: 14.0.0
```

**Comment by troywweber7** [comment]
Another one to add (which only came up because I recently did an `nx migrate latest` which got me to **14.7.5**. All the above still seem to be necessary as well. But this one is necessary for a migration script that is published.

- `@nrwl/cypress/src/migrations/update-14-7-0/update-cypress-version-if-10.js` directly depends on the following
    - `semver`

**Comment by troywweber7** [comment]
In addition, another project I'm working on (also on the latest nx) identified the following phantom dependencies:

- `@nrwl/angular`
    - `src/executors/package/ng-packagr-adjustments/styles/stylesheet-processor.js` directly depends on
        - `browserslist`
    - `src/executors/package/ng-packagr-adjustments/ng-package/options.di.js` directly depends on
        - `find-cache-dir`
    - `src/executors/package/ng-packagr-adjustments/ng-package/entry-point/entry-point.di.js` directly depends on
        - `injection-js`
    - `src/executors/package/ng-packagr-adjustments/ng-package/entry-point/compile-ngc.transform.js` directly depends on
        - `ora`
- `@nrwl/nx-cloud`
    - `lib/utilities/distributed-task-execution-detection.js` directly depends on
        - `fs-extra`

**Comment by FrozenPandaz** [comment]
It will be more productive to address these one at a time.

Could you please open separate issues for each and describe the situation where it is an issue please?

**Comment by troywweber7** [comment]
Found another: `@nrwl/angular/src/executors/ng-packagr-lite/ng-packagr-adjustments/styles/stylesheet-processor.js` directly depends on `sass`.

**Comment by troywweber7** [comment]
@FrozenPandaz I did a migrate recently and I can see that some of these are fixed, but not all of them are. This should not be closed until fixed.

**Comment by troywweber7** [comment]
@FrozenPandaz Also, I do not feel I should have to "describe the situation where it is an issue". If you go to the indicated source file relating to the identified .js file, you should see it doing an import or require for the packages. If these are not listed in the package.json, they should be.

**Comment by troywweber7** [comment]
This should not be closed.
