### ISSUE TITLE
Dep graph: show/filter circular dependencies

### ISSUE THREAD

**Issue by tmtron** [nrwl/nx#12028]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

The dep graph should highlight circular dependencies in red, and add a filter to only show projects that have circular dependencies.

## Motivation

Then we can easily spot circular dependencies and find the related projects.

## Suggested Implementation

Calculate the dependencies and change the color of projects or arrows between projects with circular dependencies to red.

**Comment by abrahamsaanchez** [comment]
@philipjfulcher any updates on this?
