### ISSUE TITLE
Missing pipe in misc-data-persistence.md

### ISSUE THREAD

**Issue by chriscurnow** [nrwl/nx#12024]
### Documentation issue

- [ X] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/recipe/misc-data-persistence

### Additional context or description

There is a missing `.pipe(`,
Line 136 in `misc-data-persistance.md`

**Comment by chriscurnow** [comment]
I tried to create a pull request for this but I had an issue updating my fork, sorry.

**Comment by FrozenPandaz** [comment]
Indeed! Would somebody else like to open this quick PR?

**Comment by jrstrayhorn** [comment]
I'd like to take this one.

**Comment by jrstrayhorn** [comment]
@FrozenPandaz - PR submitted!
