### ISSUE TITLE
cypress json reporter options does not generate output file

### ISSUE THREAD

**Issue by lmordell** [nrwl/nx#12020]
## Current Behavior

Run cypress e2e tests with a json reporter and define an output file. The output file is not generated; or, if the file exists, the json output is not written to the file.

## Expected Behavior

When setting `--reporter json --reporterOptions output=results.json`, the output file should be generated and contain the results from the test run in JSON format.

## Steps to Reproduce

Run the e2e suite for a given app. Set the reporter to `json` and reportOptions to `output=results.json`

e.g. `nx e2e my-app-e2e --reporter json --reporterOptions output=results.json`

### Environment

```
 >  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : darwin x64
   npm  : 8.11.0

   nx : 14.5.6
   @nrwl/angular : 14.5.6
   @nrwl/cypress : 14.5.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.6
   @nrwl/eslint-plugin-nx : 14.5.6
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.6
   @nrwl/js : 14.5.6
   @nrwl/linter : 14.5.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.6
   @nrwl/web : 14.5.6
   @nrwl/workspace : 14.5.6
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @nguniversal/express-engine: 14.2.0
   	 @nguniversal/builders: 14.2.0
```

**Comment by barbados-clemens** [comment]
I just tried this with defining it also in the `cypress.json` file and the same behavior happens as the command line. Where it prints the JSON to the console, but doesn't write a file. 

Looks to be a bug with cypress and mocha reporter integration currently
https://github.com/cypress-io/cypress/issues/18014

**Comment by lmordell** [comment]
Thanks for the investigation @barbados-clemens . Hope it gets resolved on cypress' end soon.

**Comment by Co0olCat** [comment]
BUMP
