### ISSUE TITLE
Ability to pass --inspect-brk to ng serve ? (nestjs app using node-execute)

### ISSUE THREAD

**Issue by appsolutegeek** [nrwl/nx#1202]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Need a way of passing inspect-brk to ng serve. I know I can change the options via the angular.json like so on the node-execute builder - well I was looking at a pull request and it seemed to be added internally.

```
        "serve": {
          "builder": "@nrwl/builders:node-execute",
          "options": {
            "inspect": "inspect-brk",
            "buildTarget": "api:build",
            "port": 5880
          }
        },
```

Problem is that the majority of time I want to use the default "inspect", so i am able to attach a debugger when i need to - so this works great.  I also need the ability to use inspect-brk so that the debugger waits until i attach. I would like to be able to do this when and as needed.

If I change the above to inspect-brk, then its always going to be like that.

I wasn't able to figure out if I can pass parameters to ng serve.

### Context

Please provide any relevant information about your setup:

Using NX latest with nestJS and the builder that is in angular node-execute

**Comment by SebastianPodgajny** [comment]
You can use `node --inspect-brk ./node_modules/.bin/ng serve`

**Comment by FrozenPandaz** [comment]
Most options can be passed in via CLI arguments ;)

For this, you can use

`ng serve api --inspect inspect-brk`

**Comment by FrozenPandaz** [comment]
This question seems answered. Please re-open if this does not work for you.
