### ISSUE TITLE
Upgrading to 14.7.5 gives `The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined`

### ISSUE THREAD

**Issue by AndrewLeedham** [nrwl/nx#12030]
## Current Behavior
Getting `The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined` when running `nx affected:lint`.

## Expected Behavior
Upgrading to 14.7.5 to work as 14.5.2 did as it is not a major.

## Steps to Reproduce
I have a fairly minimal repo that is open-source showing this issue: https://github.com/xeroxinteractive/browserslist-tools/actions/runs/3060422016/jobs/4938917626 same happens locally.

1. Clone https://github.com/xeroxinteractive/browserslist-tools
2. Checkout `renovate/nrwl-monorepo` branch.
3. Run `yarn install`
4. Run `yarn lint` or `nx affected:lint`
5. See error.

### Failure Logs
```
> Run nx affected:lint

>  NX   No explicit --base argument provided, but found environment variable NX_BASE so using its value as the affected base: e5902027626aeb6132a52f486b39baee6012dd77


 >  NX   No explicit --head argument provided, but found environment variable NX_HEAD so using its value as the affected head: 83d0b1da8a17e7637897b4f5bfd1e[11](https://github.com/xeroxinteractive/browserslist-tools/actions/runs/3060422016/jobs/4938917626#step:7:12)2866cb0d9


 >  NX   Running target lint for 3 project(s):

    - adobe-analytics
    - browserstack
    - root

 

 

 >  NX   Successfully ran target lint for 3 projects



 >  NX   The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
```
### Environment
```
   Node : 16.14.2
   OS   : darwin x64
   yarn : 1.22.17
   
   nx : 14.5.2
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.5
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.5
   @nrwl/js : 14.7.5
   @nrwl/linter : 14.7.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.7.5
   @nrwl/nx-cloud : 14.6.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.7.5
   typescript : 4.8.3
   ---------------------------------------
   Community plugins:
```

**Comment by manendrabhel** [comment]
I'm also getting same issue in lint. any resolution on this please ?

**Comment by AndrewLeedham** [comment]
It turns out renovate wasn't grouping the `nx` package itself so it was still on `14.5.2` and that caused the issue. I am trying to figure out why `nx` wasn't grouped with https://github.com/renovatebot/renovate/issues/17886
