### ISSUE TITLE
Updating package.json in any capacity causes all projects to be affected

### ISSUE THREAD

**Issue by njlaw** [nrwl/nx#12033]
## Current Behavior
The implicit dependencies for `nx.json` and `package.json` are overridden in [`getImplicitlyTouchedProjects`](https://github.com/nrwl/nx/blob/42479565e909e97e88293d94ebb8f1932690f82f/packages/nx/src/project-graph/affected/locators/workspace-projects.ts#L34-L42) to make all projects implicitly dependent on any changes to them.  E.g., adding or updating a dependency in `package.json` causes all packages to be considered affected, regardless of the `implicitDependencies` setting in `nx.json`.
This is a regression from a previous version, although I haven't nailed down which version introduced this change yet.  It works correctly with `@nrwl/workspace@11.6.3` and 

## Expected Behavior
Adding or updating a dependency in `package.json` should only cause the packages that reference that dependency to be affected, plus any packages specified in `implicitDependencies` in `nx.json`.  

## Steps to Reproduce
1. Verify there are no outstanding affected projects.
```shell
> npx create-nx-workspace@latest --name package-json-test --preset angular --style scss --nxCloud=false --appName frontend
> cd package-json-test
> git status
On branch main
nothing to commit, working tree clean
> nx print-affected | jq '.projects'
[]
```
2. Add any package to package.json or edit package.json in any way.
```diff
  "dependencies": {
    ...
-   "zone.js": "~0.11.4"
+   "zone.js": "~0.11.4",
+   "random-package": "1.0.0"
  }
```
3. Print affected projects.
```shell
> nx print-affected | jq '.projects'
[
  "frontend-e2e",
  "frontend"
]
```
These projects (all the projects in the workspace) should not be present since nothing depends on `random-package`.

For comparison Nx 11 & 12 output:
```json
[
  "npm:random-package"
]
```
and Nx 13 outputs:
```json
[]
```

#### Reproduction 2
Here is another reproduction that shows the issue from the perspective of an existing dependency: https://github.com/nrwl/nx-examples/pull/227

### Environment
```
 >  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : linux x64
   pnpm : 7.11.0
   
   nx : 14.7.5
   @nrwl/angular : 14.7.5
   @nrwl/cypress : 14.7.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.5
   @nrwl/eslint-plugin-nx : 14.7.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.5
   @nrwl/js : 14.7.5
   @nrwl/linter : 14.7.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.5
   @nrwl/web : 14.7.5
   @nrwl/workspace : 14.7.5
   typescript : 4.8.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Other

In trying to see if I was setting options incorrectly, I traced the `nx print-affected` operation and think the issue lies at least partially in:
https://github.com/nrwl/nx/blob/42479565e909e97e88293d94ebb8f1932690f82f/packages/nx/src/project-graph/affected/locators/workspace-projects.ts#L34-L42

As I understand it, this code effectively ignores the `nx.json` `implicitDependencies` setting for `nx.json` and `package.json`, and treats it as though
```json
{
  "implicitDependencies": {
    "nx.json": "*",
    "package.json": "*"
  }
}
```
were present.

**Comment by FrozenPandaz** [comment]
For `nx.json`, this is accurate. Because we don't store `projects` in `nx.json` anymore, pretty much any change to the file will be affect how Nx runs commands (hence affecting all projects it would run)

As for `package.json`, @meeroslav is working on something that will fix this.

**Comment by njlaw** [comment]
> As for `package.json`, @meeroslav is working on something that will fix this.

Thank you kindly!  If there's anything I can do to help, please let me know.
