### ISSUE TITLE
Encoding error in documentation

### ISSUE THREAD

**Issue by hige-agusd** [nrwl/nx#12037]
### Documentation issue

- [x] Reporting a typo
- [x] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/core-tutorial/03-share-assets

### Additional context or description

Line 8 of the packages/blog/src/posts/ascii.md says:
`&#123;% renderFile "../ascii/assets/cow.txt" %&#125;`
When it should be:
`{% renderFile "../ascii/assets/cow.txt" %}`

**Comment by FrozenPandaz** [comment]
Fixed with https://github.com/nrwl/nx/pull/11768
