### ISSUE TITLE
Jest encountered an unexpected token "export" in React

### ISSUE THREAD

**Issue by kjrocker** [nrwl/nx#12046]
## Current Behavior
The error `Jest encountered an unexpected token` when writing a test for a library that depends on another library, coming from the export statement.

This is a fresh repository. https://github.com/kjrocker/nx-issue-repro

## Expected Behavior
Unit tests should work for libraries that depend on other libraries by default.

## Steps to Reproduce
With my repository:
Step 1: Clone https://github.com/kjrocker/nx-issue-repro
Step 2: Run `npm install && npx nx test feature-lib`

How I made my repository:
Created a TS workspace, installed `@nrwl/react`, created two react libraries, `base-lib` and `feature-lib`.
Added the `BaseLib` component as a child of the `FeatureLib` component to create the dependency between them.
Ran the tests, which failed.

### Failure Logs
```
> nx run feature-lib:test

 FAIL   feature-lib  packages/feature-lib/src/lib/feature-lib.spec.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/kevin.rocker/Developer/nx-test/packages/base-lib/src/index.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export * from './lib/base-lib';
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import { BaseLib } from '@nx-test/base-lib';
        | ^
      2 | import styles from './feature-lib.module.css';
      3 |
      4 | /* eslint-disable-next-line */

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1796:14)
      at Object.<anonymous> (src/lib/feature-lib.tsx:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.217 s
Ran all test suites.

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target test for project feature-lib (3s)

    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

### Environment

```
 >  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : darwin x64
   npm  : 8.19.1

   nx : 14.7.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.7.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.5
   @nrwl/eslint-plugin-nx : 14.7.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.5
   @nrwl/js : 14.7.5
   @nrwl/linter : 14.7.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.7.5
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.5
   @nrwl/web : 14.7.5
   @nrwl/workspace : 14.7.5
   typescript : 4.8.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
  ```

**Comment by kjrocker** [comment]
Adding `transformIgnorePatterns: ['/packages/(?!base-lib)']` in `feature-lib/jest.config.ts` fixes the immediate issue, but then the `import { render } from '@testing-library/react'` fails to recognize `import` as a valid token, so we haven't made any progress.

**Comment by ngoc199** [comment]
I am facing this issue too. Hope this will be noticed.

**Comment by sushruth** [comment]
Facing the same issue here.

**Comment by AndresVD21** [comment]
Same here!

**Comment by sushruth** [comment]
Update - after debugging why it only fails in other react libraries and doesnt fail in other js libraries, I found that using ts-jest instead of babel-jest in `jest.config.ts` fixed the issue - 

![image](https://user-images.githubusercontent.com/2114206/192640169-611ffe0d-2254-4f7c-9c68-1883f71fbfe4.png)

This could be a temporary workaround until babel configs are fixed.

**Comment by sebastiandg7** [comment]
Using the transform configuration for @nrwl/react generated apps works.

```typescript
export default {
  displayName: 'my-lib',
  preset: '../../jest.preset.js',
  transform: {
    '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': '@nrwl/react/plugins/jest',
    '^.+\\.[tj]sx?$': ['babel-jest', { presets: ['@nrwl/react/babel'] }],
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  coverageDirectory: '../../coverage/libs/my-lib',
};

```

**Comment by ngoc199** [comment]
> Using the transform configuration for @nrwl/react generated apps works.
> 
> ```ts
> export default {
>   displayName: 'my-lib',
>   preset: '../../jest.preset.js',
>   transform: {
>     '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': '@nrwl/react/plugins/jest',
>     '^.+\\.[tj]sx?$': ['babel-jest', { presets: ['@nrwl/react/babel'] }],
>   },
>   moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
>   coverageDirectory: '../../coverage/libs/my-lib',
> };
> ```

It works. I wonder why this is not generated by nx?

**Comment by yuripramos** [comment]
I'm still facing the same issue, worth mentioning that the libraries that I have the same use of case here. 
Added the BaseLib component as a child of the FeatureLib component to create the dependency between them.

**Comment by JSMike** [comment]
New NX projects with React are still running into this issue, the jest.config.ts is still using `babel-jest` which breaks import/export and the globals/tsconfig path isn't getting generated so jest types aren't recognized.

**Comment by barbados-clemens** [comment]
project should be generated with the babel-jest preset now set, please retry with latest version of Nx.

**Comment by MartinDevillers** [comment]
Ran into the same error running Nx 15 and React 18. After making below two changes I got Jest working:

1. Rename `/apps/my-app/.babelrc` to `/apps/my-app/babel.config.js` and wrap the JSON with a `module.exports = { ... }`
2. Add the following line to `/apps/my-app/jest.config.js`:
`  transformIgnorePatterns: ["<rootDir>/node_modules/(?!name-of-problematic-package)"],`

**Comment by Phaster911** [comment]
> Update - after debugging why it only fails in other react libraries and doesnt fail in other js libraries, I found that using ts-jest instead of babel-jest in `jest.config.ts` fixed the issue -
> 
> ![image](https://user-images.githubusercontent.com/2114206/192640169-611ffe0d-2254-4f7c-9c68-1883f71fbfe4.png)
> 
> ```js
>   globals: {
>     'ts-jest': {
>       tsconfig: '<rootDir>/tsconfig.spec.json',
>     },
>   },
>   transform: {
>     '^.+\\.[tj]sx?$': 'ts-jest',
>   },
> ```
> 
> This could be a temporary workaround until babel configs are fixed.

I had an issue in which my unit tests were running just fine on my machine but failing on jenkins, your solution caused jest to give me a warning  saying that `globals` are deprecated and then the tests took forever, I removed the `globals` and ended up with:
`export default {
  displayName: 'my-lib',
  preset: '../../jest.preset.js',
  transform: {
    '^.+\\.[tj]sx?$': 'ts-jest',
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  coverageDirectory: '../../coverage/libs/my-lib',
};`
Now everything is golden, my monorepo was made 5 days ago with `"nx": "15.9.2"` and `"@nrwl/react": "15.9.2"`
