### ISSUE TITLE
Module Federation with angular - dependencies not shared should be part of vendor.js

### ISSUE THREAD

**Issue by sonikasharma1403** [nrwl/nx#12041]
## Current Behavior

shared: (libraryName, defaultConfig) => {
      if (libraryName.startsWith('@some-lib)) {
        return { ...defaultConfig };
      }

    return false;
  },

## Expected Behavior
all the unshared dependencies should be part of `vendor.js`. Instead there's one file for each depedency

**Comment by Coly010** [comment]
This is something that is controlled by the ModuleFederationPlugin from webpack itself and unfortunately is therefore out of our control. Dependencies within Module Federation need to be set up and operated on differently than to a standard static webpack build so the resulting output is modified by the ModuleFederationPlugin to handle this.

Unfortunately, as there is nothing we can do about this, I'm going to close this issue.

**Comment by sonikasharma1403** [comment]
@Coly010, do you have any workarounds/suggestions for this?

I tried using `MinChunkSizePlugin`, but then the server hung for an indefinite time with no error
