### ISSUE TITLE
nx-cloud workflow doesn't work with karma test

### ISSUE THREAD

**Issue by DaSchTour** [nrwl/nx#12045]
The test target uses the ci flag which is only supported by jest and not by karma. This probably will also cause issues in setups with jest and karma tests mixed.

## Current Behavior
Test target fails with `'ci' is not found in schema`

## Expected Behavior
Test target should not fail

## Steps to Reproduce

- Create a project with karma as test suite
- Run the `@nrwl/workspace:ci-workflow` generator with Github as CI (probably also true for others)

### Failure Logs
`'ci' is not found in schema`

### Environment
   Node : 16.17.0
   OS   : darwin x64
   npm  : 8.15.0
   
   nx : 14.7.5
   @nrwl/angular : 14.7.5
   @nrwl/cypress : 14.7.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.5
   @nrwl/eslint-plugin-nx : 14.7.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.5
   @nrwl/js : 14.7.5
   @nrwl/linter : 14.7.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.6.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.5
   @nrwl/web : 14.7.5
   @nrwl/workspace : 14.7.5
   typescript : 4.8.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @jscutlery/semver: 2.27.0
         ngx-deploy-npm: 4.2.4

**Comment by StalkAltan** [comment]
Hi @DaSchTour !

The commands generated for the Nx Cloud workflow are just meant as a general example -- feel free to adjust them to fit the needs of your project. Whether that's moving the `ci` flag into a configuration for your jest targets, or renaming your karma/jest targets so they don't use the same name (ex: test => `test-jest`, `test-karma`), there are a variety of options to get this working for your needs!

For that reason, I'm going to close this issue, since this is fixable with user configuration.

**Comment by DaSchTour** [comment]
@StalkAltan well, that still is some unfortunate combination that from my experience will scare certain type of inexperienced developers.

**Comment by harellevy** [comment]
@DaSchTour Did you manage to solve this with mixed Karma and Jest workflows? This appears to be an issue for me also.

**Comment by DaSchTour** [comment]
@harellevy no I did not have mixed tests in one repo. Probably the only solution ist to create a configuration for ci and use --configuration=ci and add ci:true as an option to the ci configuration in jest targets.
Probably this could have been something NX could already do upfront. Would probably avoid a lot of trouble for some devs.
