### ISSUE TITLE
Recommended ngrx fetch with navigation will cause circular dependency

### ISSUE THREAD

**Issue by chriscurnow** [nrwl/nx#12055]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ X] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/recipe/misc-data-persistence

### Additional context or description

It seems like this is a long-standing issue that should be discussed in the documentation.

Under the heading **Data Fetching On Router Navigation**, the recommendation is to use the `navigation` operator. But this relies on importing the related component. (In the case of the example, this is the `TodoComponent`.)

This will immediately create a circular dependency between the `data-access` module and the `feature` module.

This issue was discussed here: https://github.com/nrwl/nx/issues/1889.

Using the `navigation` operator is really neat but I can't see how it can be implemented without breaking Nx guidelines.

In my view, the documentation should discuss this.

**Comment by isaacplmann** [comment]
The data-persistence features haven't been modified in a long time and we probably won't make any changes to them any time soon.  Its not worth it for us to update documentation about them.

If you would like to make a PR to update the documentation describing the problem and the solution, I'd be happy to help you through the review process.

Closing for now.
