### ISSUE TITLE
NX Dynamic MF - Child App failed to serve 

### ISSUE THREAD

**Issue by samartomar** [nrwl/nx#12059]
We just migrated from Manfred micro frontend to NX MF. 

We are using Dynamic Micro Federation. 

When we run shell everything works fine, MF and child modules load perfectly fine. 

But as soon as we try to run MF Child app stand alone. we are receiving  consume error

	"default-webpack_sharing_consume_default_angular_cdk_overlay_angular_cdk_overlay": [
		40314
	],

Uncaught Error: Shared module is not available for eager consumption: 51006
    at __webpack_require__.m.<computed> (consumes:220:1)
    at __webpack_require__ (bootstrap:19:1)
    at 89745 (main.js:10:76)
    at __webpack_require__ (bootstrap:19:1)
    at startup:5:1
    at __webpack_require__.O (chunk loaded:23:1)
    at startup:6:1

This is what my package.json contains. 

    "@angular/animations": "14.2.2",
    "@angular/cdk": "14.2.2",
    "@angular/common": "14.2.2",
    "@angular/compiler": "14.2.2",
    "@angular/core": "14.2.2",
    "@angular/elements": "14.2.2",
    "@angular/forms": "14.2.2",
    "@angular/material": "14.2.2",
    "@angular/material-moment-adapter": "14.2.2",
    "@angular/platform-browser": "14.2.2",
    "@angular/platform-browser-dynamic": "14.2.2",
    "@angular/router": "14.2.2",
    "@ckeditor/ckeditor5-angular": "4.0.0",
    "@ckeditor/ckeditor5-build-classic": "35.1.0",
    "@ngneat/transloco": "4.1.1",
    "@nrwl/angular": "14.7.5",
    "@okta/okta-angular": "5.2.0",
    "@okta/okta-auth-js": "6.8.1",

## Current Behavior

MF Child App serve fails with consume error. 

## Expected Behavior

We should be able to run Child App independently of Shell app.  

## Steps to Reproduce

Follow steps from NX guide and following packages to JSON then try to run Child App. 

    "@angular/animations": "14.2.2",
    "@angular/cdk": "14.2.2",
    "@angular/common": "14.2.2",
    "@angular/compiler": "14.2.2",
    "@angular/core": "14.2.2",
    "@angular/elements": "14.2.2",
    "@angular/forms": "14.2.2",
    "@angular/material": "14.2.2",
    "@angular/material-moment-adapter": "14.2.2",
    "@angular/platform-browser": "14.2.2",
    "@angular/platform-browser-dynamic": "14.2.2",
    "@angular/router": "14.2.2",
    "@ckeditor/ckeditor5-angular": "4.0.0",
    "@ckeditor/ckeditor5-build-classic": "35.1.0",
    "@ngneat/transloco": "4.1.1",
    "@nrwl/angular": "14.7.5",
    "@okta/okta-angular": "5.2.0",
    "@okta/okta-auth-js": "6.8.1", 

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by samartomar** [comment]
![image](https://user-images.githubusercontent.com/9993940/190895232-4add910d-8f9a-4858-92a4-1fd494afcd5b.png)

Also this is new issue popup recently now sure how to describe it. closing and re-opening VS solve this issue.

**Comment by samartomar** [comment]
it's surprise how things get twisted.  so it seems like Manfred MF allowed to use ag-grid module this way, but NX MF this produced error. 

import { LicenseManager } from 'ag-grid-enterprise';
import('./bootstrap').catch((err) => console.error(err));
LicenseManager.setLicenseKey('CompanyName=');

**Comment by Coly010** [comment]
In your `module-federation.config.js` add the following below the `remotes: [...]` array

```ts
shared: (libraryName, libraryConfig) => {
  if(libraryName === 'ag-grid-enterprise') {
    return {...libraryConfig, eager: true};
  } 
}
```

This is because you are attempting to use a library, which is shared, before Webpack Module Federation has initialized the shared scope. By setting this library to be `eager: true` it tells webpack it needs to be available before the shared scope is initialized.

**Comment by quicksilverr** [comment]
Hey @Coly010, how do we do this for multiple packages? 

```
shared: (libraryName, libraryConfig) => {
  if(libraryName === 'ag-grid-enterprise') {
    return {...libraryConfig, eager: true};
  } 
}
```

**Comment by Coly010** [comment]
Hi @quicksilverr 

There are multiple ways, it's all JS at the end of the day :)

For fine-grained control over each package:
```js
shared: (libraryName, libraryConfig) => {
  if(libraryName === 'package-a') {
    return {...libraryConfig, eager: true};
  } 
  if(libraryName === 'package-b') {
    return {...libraryConfig, eager: true};
  } 
}
```

or something like this to apply same changes to multiple packages

```js
if(['package-a', 'package-b'].includes(libraryName)) {
    return {...libraryConfig, eager: true};
  } 
```

**Comment by quicksilverr** [comment]
Hey @Coly010 Thanks a lot for this, saved a major blocker on my end.
