### ISSUE TITLE
move generator should support directories and single files

### ISSUE THREAD

**Issue by tmtron** [nrwl/nx#12058]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

The [move:generator](https://nx.dev/packages/workspace/generators/move) can only move a whole library.  
It would be great if we could also move a directory (including all files and subdirectories) or a single file to an existing lib and update all references (e.g. import statements)

## Motivation

When working with libraries for some time, they grow in size and after some threshold it makes sense to split the lib up into multiple small libs.

Currently the IDEs have no good support for this kind of move operation: see [Stackoverflow: IDE - auto-update imports when moving files between libs/barrels](https://stackoverflow.com/questions/61556751/ide-auto-update-imports-when-moving-files-between-libs-barrels)

## Suggested Implementation

Enhance the move generator:
* new option: `srcDir` to specify which directory in the src `--project` should be moved
* `--destination`: should allow a deep path into an existing lib: e.g. `shared/my-feature-lib/moved-dir`
* The move action should update all references to the moved files in the workspace (this logic already exists in the move generator)
  * in addition to that the old directory/file/s should be deleted
  * and, if applicable the old directory should be removed from `index.js` files in the src project

**Comment by Frankitch** [comment]
@tmtron  I am quite surprised there is not that many thumbs up for that feature... Does this mean that there is currently a way to do this automatically without the help of nx ? 

I am regularly splitting / reorganizing libs and it is a hell to move files from library to another. :sweat_smile:

**Comment by tmtron** [comment]
> @tmtron I am quite surprised there is not that many thumbs up for that feature... Does this mean that there is currently a way to do this automatically without the help of nx ?

I don't know a really good way to do this: the best workaround I know of is mentionened in my [Stackoverflow question](https://stackoverflow.com/a/68690970/1041641)]

**Comment by Frankitch** [comment]
Thanks @tmtron but I'm on vscode and I also tried `refactor-imports` but that didn't work either... :slightly_smiling_face:
