### ISSUE TITLE
Styles are not extracted for React application in production build

### ISSUE THREAD

**Issue by MiroslavKral** [nrwl/nx#12068]
## Current Behavior
I generate clean React application and generate a few components with global styles with package **@nrwl/react:component**.
These components imports styles directly in TypeScript files by default:

![image](https://user-images.githubusercontent.com/8074603/190993939-50b20b89-937c-44e0-ae93-855b67a2d939.png)

When I perform production build, styles are not extracted into separate file, but are included in final bundle:

![image](https://user-images.githubusercontent.com/8074603/190993378-242856e0-d519-4736-ba17-59a26e785303.png)

And it is wrong from my point of view and it is problem for our production application too. It is ok for development, but very bad for production.

## Expected Behavior
Styles should be extracted into file in production mode.

## Steps to Reproduce
There is minimal Github repo with example: https://github.com/MiroslavKral/nx-react-styles
Build instructions are in README.

### Environment
Node : 14.17.6
OS   : win32 x64
npm  : 6.14.15
   
nx : 14.7.5
@nrwl/angular : Not Found
@nrwl/cypress : 14.7.5
@nrwl/detox : Not Found
@nrwl/devkit : 14.7.5
@nrwl/eslint-plugin-nx : 14.7.5
@nrwl/express : Not Found
@nrwl/jest : 14.7.5
@nrwl/js : 14.7.5
@nrwl/linter : 14.7.5
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/nx-cloud : Not Found
@nrwl/nx-plugin : Not Found
@nrwl/react : 14.7.5
@nrwl/react-native : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : 14.7.5
@nrwl/web : 14.7.5
@nrwl/workspace : 14.7.5
typescript : 4.8.3
---------------------------------------
Local workspace plugins:
---------------------------------------
Community plugins:

**Comment by MiroslavKral** [comment]
Is there any problem with provided information?

**Comment by ndcunningham** [comment]
What do you mean by extracted?
Do you expect your styles file even though they are directly imported by your components not to be included in your components bundle?
