### ISSUE TITLE
nx run doesn't pick up Vite environment variable files

### ISSUE THREAD

**Issue by Ragura** [nrwl/nx#12062]
## Current Behavior
I find it hard to categorize this issue as a bug or a feature request because I don't know if it's intended behavior. Within a pnpm workspace, when running `pnpm nx dev myproject` NX doesn't pick up environment variables set in a Vite project's `.env.development` or `.env.development.local`. It does pick up what's in the regular `.env` file. Vite manages these environment variable files using dotenv.

## Expected Behavior
I understand NX has its own environment variable priority system, but I can't seem to find a way to manipulate it to read the other environment variable files. I would have expected it to respect a dotenv environment. Is this normal behavior? And if so, is there a workaround?

## Steps to Reproduce
Make any Vite project inside a pnpm workspace (or use the standard create Vite app CLI). Create a `.env.development`. It will not be picked up by NX.

### Environment
```
Node : 17.0.1
   OS   : darwin arm64
   pnpm : 7.11.0
   
   nx : 14.7.4
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : Not Found
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.6.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : Not Found
   typescript : Not Found
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by FrozenPandaz** [comment]
Could you please create an example repo that we can look at?
