### ISSUE TITLE
[React - Module Federation setup] baseHref only applies to "serve" target but not "serve-static" target

### ISSUE THREAD

**Issue by Elvis116** [nrwl/nx#12063]
Same issue as https://github.com/nrwl/nx/issues/10310.
We can add a new option for @nrwl/web:file-server such as "hasProjectContext", when it is true we can set the url context to http://localhost:4201/[project name]. That means if our "outputPath": "dist/apps/my-app", we can access it with http://localhost:4201/my-app instead of http://localhost:4201.
The code change is in fileServerExecutor function of https://github.com/nrwl/nx/blob/master/packages/web/src/executors/file-server/file-server.impl.ts.
let outputPath = getBuildTargetOutputPath(options, context);
if(hasProjectContext){
    outputPath = outputPath.substring(0, outputPath.lastIndexOf('/'));
}

Please apply this change if it is reasonable. Thanks.

**Comment by gerardcastell** [comment]
Same is happening for angular applications, any updated is welcome!
