### ISSUE TITLE
support "BUILD ONLY" mode for cypress builder

### ISSUE THREAD

**Issue by shlomiassaf** [nrwl/nx#1206]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

cypress builder should allow an opt-in option to skip the runner and only perform
the build task (compile TS specs, copy fixtures, etc...)

This option should also support watch mode.

## Current Behavior

Couldn't find a way to skip the runner, the builder will build TS specs and then run the dev server using the target defined.

## Other

Perhaps I get it all wrong, but with the current behaviour local development is great.

When working in the CI, the first action is to perform our build and then I would want to run cypress on the production build (using a standalone http server).

To do this I need the compiled files (TS spec, fixtures etc...)

Once I have them I can run cypress manually using the same `cypress.json`

This is a whole-lot faster then running cypress under the angular cli...

> If it's possible to perform a build of the app + build of the e2e app in one command it would be great (I don't know if multi-target builders are supported by the cli)

Thanks

**Comment by FrozenPandaz** [comment]
In other words, you want to skip the building/serving of the application and want to just run the tests against a separate server?

**Comment by shlomiassaf** [comment]
Not at all.

I want to be able to build the e2e application but not to serve.

**Comment by shlomiassaf** [comment]
@FrozenPandaz Also, another use case...

I'm in the middle of development, running the dev server **but not running the e2e for dev in watch mode**

Now, I want to add a test, this will require me to:

- Close the dev server
- Run the dev server through e2e

This is a long process, it takes a lot of time....

In general, running cypress is process and time consuming, I usually want to develop and then run test when I'm ready to.

The `cypress:builder` architect target builder the comes with **nrwl/nx** does 3 things:

1. Run an existing target spec (e.g `my-app:server`)
2. Build (watch) the e2e app (compile TS of e2e, copy fixtures etc...)
3. Run cypress

My suggestion is simply to allow users to run step 2 (build and build->watch) through a cli command.

Since Steps 1 & 3 can run easily without the builder.

This will also allow custom control over the cypress test-runner, right now every other configuration CLI command in cypress requires `cypress:builder` schema integration.

**Comment by allout58** [comment]
This seems to be partially supported currently (I tried with 7.4.0, might go back even further) with some simple config changes. If you set the `baseUrl` configuration parameter to anything, either as a CLI option or part of the architect options in `angular.json`, the dev server is not spun up.

This removes step 1 in @shlomiassaf 's comment above, but not step 3.

**Comment by vsavkin** [comment]
I think the use case is reasonable. You should be able to compile cypress tests withing running them.

**Comment by Mathyn** [comment]
Any updates on this? I want to run the e2e tests in a Docker container with a pre build Angular project and e2e project (both copied into the Docker image). However I would need to be able to build the e2e project without actually running the tests.

**Comment by intellix** [comment]
I'd like to be able to just build the tests and run them against a separate server. We already have an environment up and serving is a waste taking around 8 minutes until it starts running tests.

Perhaps with the above it'll be supported anyway?

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by MrJH** [comment]
Any news on this feature? Would be really useful for us!

**Comment by Amakaev** [comment]
> In other words, you want to skip the building/serving of the application and want to just run the tests against a separate server?

@FrozenPandaz does is possible right now?

**Comment by mehrad-rafigh** [comment]
@Amakaev you have to use a workaround to run your tests against a seperate server without building the app.
`npx nx e2e app-e2e --browser chromium --spec **/**test-{01,02}**.ts --dev-server-target="" --base-url https://your-server.com`

**Comment by allout58** [comment]
pinging to keep this active, I think this still could be a valuable feature.

**Comment by jhwegener** [comment]
@allout58 thx! it is still an issue on my side and this feature would be great!

**Comment by jhwegener** [comment]
Our current workaround:
Build the app with build script (npm run build), put it to docker image. Then, load this image and the cypress/included image (mounted e2e tests there) in a docker compose and run the tests with CYPRESS_baseUrl environment variable.

**Comment by pascalbe-dev** [comment]
pinging to keep this active, I think this still could be a valuable feature.

**Comment by pascalbe-dev** [comment]
If would love to have this feature still :)

**Comment by barbados-clemens** [comment]
After going back and forth on this it doesn't fully seem like something we'd support right now. maybe in the future.
