### ISSUE TITLE
Add optional "version" property to "project-schema.json"

### ISSUE THREAD

**Issue by ShiJuuRoku** [nrwl/nx#12070]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Add optional "version" property to "project-schema.json"

## Motivation
App project can't read package.json to version version number
More, we can set a version number by app

It could also be updated through a nx generator script before the build step (version take from package.json)

**Comment by FrozenPandaz** [comment]
Sorry, I'm not sure I understand. The `project-schema.json` is meant for `project.json` files, not `package.json` files. Did I misunderstand something?

**Comment by ShiJuuRoku** [comment]
That right.
Currently de had a warning on build if we had a version property into `project.json` file.

The need is to be able to specify the version of our application project.
Then we can use it to show the application version
