### ISSUE TITLE
[Feature] Cypress builder should act on spec file delete. 

### ISSUE THREAD

**Issue by shlomiassaf** [nrwl/nx#1208]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

When deleting a typescript spec file the target JS file is not deleted.  
This will cause the spec file to remain active in the test runner.

When a spec file is deleted the corresponding target file should also be removed.

## Current Behavior

The cypress builder delegates everything TS related to the typescript compiler which does not support this feature (https://github.com/Microsoft/TypeScript/issues/16057).

This is why I don't think it's a bug but a feature...

## Other

If #1207 is implemented, it will require a watcher which can be used also here to watch for spec files that are removed.

This should be an opt-in option, so files are not removed if not specifically instructed to.

**Comment by vsavkin** [comment]
This has been fixed when we transitioned to using webpack for bundling specs. So I'm going to close this issue. Thank you!

**Comment by mightyiam** [comment]
Thank you for following up, @vsavkin.
