### ISSUE TITLE
[Feature Request] FAQ section

### ISSUE THREAD

**Issue by lonix1** [nrwl/nx#1209]
Various things are not fully explained in the docs, and @FrozenPandaz [suggested](https://github.com/nrwl/nx/issues/1187#issuecomment-475711305) that one day we should have a FAQ section. I hope this issue is an appropriate way to keep track of those items?

- [Difference between](https://github.com/nrwl/nx/issues/1187#issuecomment-475711305) nx and similar tools (e.g. lerna, rush)
- Combining nx with other tooling to support publishing and versioning
- Testing typescript tests with jest. Was confusing to me because I'm used to using `ts-jest`. Nx uses `jest-preset-angular` which uses `ts-jest`. So for angular apps just use the nx defaults (which adds the preset to the `jest.config.js` file), but for express/nest apps, replace the preset with `ts-jest`. Or [merge](https://stackoverflow.com/a/52622141/9971404) multiple presets if necessary.
- [Split](https://github.com/nrwl/nx/issues/1089) large number of scripts into multiple `package.json` files
- ...

Feel free to add more below.

**Comment by bcabanes** [comment]
Hi @lonix1!
We implemented a full text search in the documentation website recently. We think it would improve the developer experience and will be easier to find what you're looking for. If we have more questions and don't have a good place to answer them, we would then create a FAQ section.

Thank you for pointing out the parts of the description that are confusing we'll look into it!
