### ISSUE TITLE
@nrwl/expo: Running "run-ios" on a freshly generated app fails

### ISSUE THREAD

**Issue by duro** [nrwl/nx#12106]
## Current Behavior
When a new app is generated with the @nrwl/expo:app generator, and immediately after you run the `run-ios` executor the run fails with the following error:

```
Command `pod install` failed.
└─ Cause: Invalid `Podfile` file: 859: unexpected token at 'info Run CLI with --verbose flag for more details.
'.

 #  from /Users/duro/Workspace/projects/pineapple/whoolias/apps/native/ios/Podfile:14
 #  -------------------------------------------
 #    use_expo_modules!
 >    config = use_native_modules!
 #  
 #  -------------------------------------------
```

## Expected Behavior
I would expect a freshly generated app to launch with the `run-ios` command (not just the `start` command)

## Steps to Reproduce
1. Generate an expo app with the @nrwl/expo app generator
2. After generation, run the `run-ios` executor

### Failure Logs

```
Command `pod install` failed.
└─ Cause: Invalid `Podfile` file: 859: unexpected token at 'info Run CLI with --verbose flag for more details.
'.

 #  from /Users/duro/Workspace/projects/pineapple/whoolias/apps/native/ios/Podfile:14
 #  -------------------------------------------
 #    use_expo_modules!
 >    config = use_native_modules!
 #  
 #  -------------------------------------------
```

### Environment

```
>  NX   Report complete - copy this into the issue template

   Node : 16.13.1
   OS   : darwin arm64
   yarn : 1.22.18
   
   nx : 14.7.6
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.7.6
   @nrwl/detox : 14.7.6
   @nrwl/devkit : 14.7.6
   @nrwl/eslint-plugin-nx : 14.7.6
   @nrwl/expo : 14.7.6
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.6
   @nrwl/js : 14.7.6
   @nrwl/linter : 14.7.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.7.6
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.6
   @nrwl/web : 14.7.6
   @nrwl/workspace : 14.7.6
   typescript : 4.8.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Cause/Workaround

This happens because the following dependencies that are detailed in the apps `package.json` are not included in the root `package.json`

```
"expo-splash-screen": "~0.16.2",
"expo-status-bar": "~1.4.0",
```

Adding these to the root package.json and then re-installing deps resolves this issue.

### Ultimate Fix

I am happy to help resolve this and send in a PR, but I'd first like to understand if there was a conscious decision by the plugin authors to not include those deps?

I would propose adding them to the list here:

https://github.com/nrwl/nx/blob/master/packages/expo/src/generators/init/init.ts#L71

I understand this may not be necessary for users who never use `run-ios` and instead only rely on Expo Go to run their apps. However, in my experience, any Expo app that is more than a toy / pet project, will eventually need to move to the bare workflow that is `run-ios/android` ejects us into.

**Comment by xiongemi** [comment]
```
"expo-splash-screen": "~0.16.2",
"expo-status-bar": "~1.4.0"
```

those are not needed for managed apps. when you eject the app, then those are needed.
