### ISSUE TITLE
request for ngrx grade state mgt devtools logging

### ISSUE THREAD

**Issue by kenatwex** [nrwl/nx#12109]
Nx is great for making the world a better place and continues to

Every-time google puts their hands on something it turns into $%@&^E%@&R

NgRX devtools router serializer is now broken it wont log anymore within the IDE console nor the chrome devtools console for debugging.

https://github.com/ngrx/platform/issues/3582

The best pattern ever introduced now ruined

## Description
Nx is good at making things better

us there some way the Nx team can override these lapses that are taking place and impacting the field everywhere?

## Motivation
because we cannot even debug a serialized router anymore

## Suggested Implementation
Yank NgRX away from the current committers and introduce a new flavor for Nx

**Comment by FrozenPandaz** [comment]
1. That sounds like a valid issue that you're describing.
2. You express quite a bit of frustration and it is not productive.
3. It's possible that the Redux devtools have updated and are incompatible with v9 of ngrx which is now over 2 years old: https://www.npmjs.com/package/@ngrx/store. It might very well be time to update to maintain a good dev experience.
4. Knowing [Brandon and the rest of the ngrx team](https://github.com/ngrx/platform/issues/3582#issuecomment-1251795406), if you can show the issue still presents itself with the latest versions of ngrx and you present it objectively and productively, I am positive that they will take a look.

Ngrx is still incredibly popular both in the community and especially in the enterprise world. I believe that there is a good reason for that and that the Ngrx team is doing a wonderful job.

That said, there are alternative state management libraries. I will let you explore for yourself.

I will be closing this issue as it is not actionable in the Nx repo.
