### ISSUE TITLE
[Feature Request] create-nx-workspace with fullstack-react preset

### ISSUE THREAD

**Issue by hmagrini** [nrwl/nx#1211]
## Expected Behavior

Running `create-nx-workspace some-project` allows to generate a full stack application with React and Express.

## Current Behavior

Running `create-nx-workspace some-project` only has Angular + NestJS available.

## Other

Reason: Being able to create that setup with a single command is more flashy and cool when showing off Nx to get buy-in from stakeholders to use it for React Monorepos.

I was considering to open a PR to add this, but before doing that I wanted to get your take on which approach you would prefer:

1) The simple way: just adding an extra preset to the `ng-new` schema and add the generation as an extra case on the switch statement when checking for the preset value.

2) The better but a bit more complex way:  make use of inquirer's [`when` option](https://www.npmjs.com/package/inquirer#question), which requires adding that property to the `PromptDefinition` on the angular-cli project first, and then making use of it to ask for angular+nestjs or react+express when `preset==full-stack`

**Comment by FrozenPandaz** [comment]
> React and Express
💯this is a good combination.

> The better but a bit more complex way: make use of inquirer's `when` option

I would love for the `when` option to be available via Angular CLI 👍 

>  adding an extra preset to the ng-new schema
What do you think of `--preset full-stack-minimal`? `--preset full-stack-react`?

**Comment by hmagrini** [comment]
>What do you think of --preset full-stack-minimal? --preset full-stack-react?

Those values sound great! I think they would be good options if we wanted to go with the first alternative though, due to how the prompts currently work on the CLI. AFAIK the CLI only allows a single question being asked per each property on your schema (based on their [`x-prompt` schema](https://github.com/angular/angular-cli/blob/master/docs/specifications/schematic-prompts.md#x-prompt-schema)). Meaning that if we want to ask conditional questions using `when`, we would need to have "optional" properties on the schema definitions.

To give an example, this is what both alternatives would (roughly) look like in terms of the schema we would need to define:

### First alternative (extending current `preset` options)
```json5
"preset": {
      ...
      "enum": ["empty", "angular", "react", "web-components", "full-stack-minimal", "full-stack-react"],
      "x-prompt": {
        ...
        "items": [
           ....
          {
            "value": "full-stack-minimal",
            "label": "full-stack        [a workspace with a full stack application (NestJS + Angular)]"
          },
          {
            "value": "full-stack-react",
            "label": "full-stack        [a workspace with a full stack application (React + Express)]"
          }
        ]
      }
    }
```

### Second alternative (using `when` from inquirer)

```json5
"preset": {
      ...
      "enum": ["empty", "angular", "react", "web-components", "full-stack"],
      "x-prompt": {
        ...
        "items": [
          ...
          {
            "value": "full-stack",
            "label": "full-stack        [a workspace with a full stack application]"
          }
        ]
      }
    },
"preset-full-stack": {
      ...
      "enum": ["empty", "angular", "react", "web-components", "full-stack-minimal", "full-stack-react"],
      "x-prompt": {
        ...
        "when": (answers) => answers.preset === 'full-stack'
        "items": [
           ....
          {
            "value": "full-stack-minimal",
            "label": "full-stack        [a workspace with a full stack application (NestJS + Angular)]"
          },
          {
            "value": "full-stack-react",
            "label": "full-stack        [a workspace with a full stack application (React + Express)]"
          }
        ]
      }
    }
```

What do you think? :)

**Comment by FrozenPandaz** [comment]
Can you please make an issue at https://github.com/angular/angular-cli/issues? I would love to discuss there. I can see why implementing it there would not be trivial and might require some discussion there to reach a good implementation.

I think `--full-stack-minimal` should be the flag for now. We can deprecate without a breaking change later if necessary.

**Comment by mehrad-rafigh** [comment]
This issue can be closed. When you use `npx --ignore-existing create-nx-workspace react-express-full-stack` you have the option `react-express     [a workspace with a full stack application (React + Express)]` as a preset.

**Comment by vsavkin** [comment]
Folks!

We have added a full-stack preset for React.  

```
npx create-nx-workspace --preset=react-express
```

So I'm closing this issue.
