### ISSUE TITLE
Running E2E-tests with Cypress in mfe tutorial does not work

### ISSUE THREAD

**Issue by yoolandes** [nrwl/nx#12118]
## Current Behavior
```
# npx nx e2e dashboard-e2e --watch

visit/ 
(uncaught exception)SyntaxError: Cannot use 'import.meta' outside a module
```

## Expected Behavior
E2E tests succeed

## Steps to Reproduce
1.`npx create-nx-workspace ng-mf`
2.`npm install --save-dev @nrwl/angular`
3.`npx nx g @nrwl/angular:host dashboard`
4. `npx nx e2e dashboard-e2e --watch`

or follow https://nx.dev/recipe/dynamic-module-federation-with-angular

### Environment
```
Node : 16.15.1
OS   : darwin arm64
npm  : 8.11.0
nx : 14.7.6
@nrwl/angular : 14.7.6
@nrwl/cypress : 14.7.6
@nrwl/detox : Not Found
@nrwl/devkit : 14.7.6
@nrwl/eslint-plugin-nx : 14.7.6
@nrwl/expo : Not Found
@nrwl/express : Not Found
@nrwl/jest : 14.7.6
@nrwl/js : 14.7.6
@nrwl/linter : 14.7.6
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/nx-cloud : Not Found
@nrwl/nx-plugin : Not Found
@nrwl/react : Not Found
@nrwl/react-native : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : 14.7.6
@nrwl/web : Not Found
@nrwl/workspace : 14.7.6
typescript : 4.8.3
---------------------------------------
Local workspace plugins:
---------------------------------------
Community plugins:
```

**Comment by Coly010** [comment]
Ah, thanks for this! We had an error handler for Cypress that is set up to ignore that error as it only exists in dev and is non-impactful.

But Cypress seems to have changed the file where this handler should go.

If you move the contents of `apps/dashboard-e2e/src/support/index.ts` to the bottom of `apps/dashboard-e2e/src/support/e2e.ts`, and run the e2e test again, you'll see that it works as expected.

I'll update our code to place this in the correct file.
