### ISSUE TITLE
Missing jasmine packages in new workspaces if using Protractor and Jest with Angular

### ISSUE THREAD

**Issue by esagawe** [nrwl/nx#1213]
## Expected Behavior

e2e tests should work with new workspaces if using Protractor and Jest with Angular. So `jasmine-spec-reporter`, `@types/jasmine` and `@types/jasminewd2` need to be installed by the CLI.

### Steps to Reproduce

1. `npx create-nx-workspace myorg`
2. select SCSS
3. skip naming a npm scope
4. select empty workspace
5. `ng g app my-app`
6. select Angular
7. skip naming a directory
8. select Jest
9. select Protractor
10. skip naming tags
11. `ng e2e my-app-e2e` will fail

### Context

- @nrwl/schematics: 7.7.2
- Angular CLI (global): 7.3.7
- Node JS: 10.15.3
- OS: Windows 10

## Other

After installing these packages on my own (`npm i jasmine-spec-reporter @types/jasmine @types/jasminewd2 -D`) everything works fine.

**Comment by vsavkin** [comment]
@FrozenPandaz we should include jasmine-spec-reporter as a dep of @nrwl/angular as part of the repackaging.
