### ISSUE TITLE
constructor coverage for angular is not correct anymore

### ISSUE THREAD

**Issue by bulldog98** [nrwl/nx#12132]
## Current Behavior
If you have an angular lib/app with an injection in the constructor then jest reports it as a not covered branch

## Expected Behavior
This is a regression I remember it working around 1-2 weeks ago (was 14.6.5 I think).

## Steps to Reproduce
Reproduction: https://github.com/nrwl/nx-examples/pull/229

* run `yarn nx products:test`
* observe the coverage info

**Comment by Blackbaud-SteveBrush** [comment]
I'm seeing this too. 
I'm on Nx version `14.7.13`.
Coverage is correct when using `@angular/compiler-cli@14.2.0`, but coverage drops (constructor, specifically) when I update to `@angular/compiler-cli@^14.2.1`. Any ideas?

**Comment by adbaran1** [comment]
We're also experiencing this issue with Nx 14.8.0. Downgrading `@angular/compiler-cli` does not change anything for us, unfortunately.

**Comment by adbaran1** [comment]
Update: in our case, downgrading `jest-preset-angular` from 12.2.2 to 12.2.0 resulted in the following behaviors (12.1.0 is not usable):
- `constructor` params (dependency injection) are no longer marked as branches for coverage
- Code coverage is not collected from all files (perhaps fixed in 12.2.2)
- Not all tests are able to run, as some result in errors like the following (perhaps also fixed in 12.2.2):
```
    Component 'AppComponent' is not resolved:
     - templateUrl: ./app.component.html
     - styleUrls: ["./app.component.scss"]
    Did you run and wait for 'resolveComponentResources()'?
```

Going to look deeper into `jest-preset-angular` to see why this might be the case.

**Comment by Blackbaud-SteveBrush** [comment]
I'll add that we're using Karma as our test runner. Unsure why downgrading `@angular/compiler-cli` works in our case.

**Comment by willyboy** [comment]
I found that I had a bunch of hardcoded istanbul deps (and old jasmine/karma deps) in my package.json. Removing these magically fixed the constructor error. Maybe this will help someone else.

**Comment by adbaran1** [comment]
Removing `emitDecoratorMetadata` from tsconfig.base.json also worked as a workaround for this issue (hesitant to call this a fix).

**Comment by Blackbaud-SteveBrush** [comment]
According to [this article](https://blog.ninja-squad.com/2021/05/12/angular-cli-12.0/#:~:text=The%20TS%20option%20emitDecoratorMetadata%20is,json%20.), it appears Angular 12+ no longer requires `emitDecoratorMetadata` to be set. 🤷‍♂️ 
>The TS option emitDecoratorMetadata is no longer needed by Angular, and can be safely removed from tsconfig.json.

**Comment by Blackbaud-SteveBrush** [comment]
The problem with disabling `emitDecoratorMetadata`, however, is that `/* istanbul ignore next */` on decoratored functions no longer works.

**Comment by Blackbaud-SteveBrush** [comment]
FYI, to reproduce the issue, run the following:
```
npx create-nx-workspace@15.1.1 --ci=github --nxCoud=true --preset=angular
npx nx g @nrwl/angular:lib ui --publishable --importPath=@skyux/ui --unitTestRunner=karma
npx nx g component todos --project=ui --export    
```

Add an injectable to the component's constructor (anything, really). For example:
```
  constructor(title: Title) {
    title.setTitle('foobar');
  }
```

Then, run the tests:
```
npx nx test ui --code-coverage   
```
You'll see the Branches coverage is at 75%, but when you look at the coverage report, it's highlighting something incorrectly.

<img width="437" alt="Screen Shot 2022-11-21 at 9 52 42 AM" src="https://user-images.githubusercontent.com/12497062/203085490-ccd976e4-d83d-45b1-82a0-9a7284ded2dc.png">

**Comment by barbados-clemens** [comment]
Hi all, this isn't really an Nx thing but an issue with istabul coverage reporter. @mandarini has an execllent write up over steps you can take to help resolve the issue. [mandarini/isolatedm-jest](https://github.com/mandarini/isolatedm-jest)
