### ISSUE TITLE
"nx graph" crashing immediately, no errors

### ISSUE THREAD

**Issue by iDVB** [nrwl/nx#12134]
![2022-09-20_16-09-07 (1)](https://user-images.githubusercontent.com/189506/191355001-48394b29-304c-4607-ab11-5d462bf8d4b3.gif)

## Current Behavior

1. run `pnpm nx graph`
2. console says: `Project graph started at http://127.0.0.1:4211`
3. browser pops up, brief flash of blue, then page says: `This site can’t be reached`

## Expected Behavior

browser stays open allowing user to interact with the graph.

## Steps to Reproduce

1. `git clone git@github.com:iDVB/nx-graph-crashing.git`
2. `pnpm install`
3. `pnpm nx graph`
4. console says: `Project graph started at http://127.0.0.1:4211`
5. browser pops up, brief flash of blue, then page says: `This site can’t be reached`

### Environment

```
Node : 18.8.0
   OS   : darwin x64
   pnpm : 7.11.0
   
   nx : 14.7.8
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : Not Found
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.6.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : Not Found
   typescript : 4.8.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by wolfie82** [comment]
Having the same issue, report below.

```
➜ nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : darwin arm64
   yarn : 1.22.19

   nx : 14.7.8
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.7.8
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.8
   @nrwl/eslint-plugin-nx : 14.7.8
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.8
   @nrwl/js : 14.7.8
   @nrwl/linter : 14.7.8
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.7.8
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.8
   @nrwl/web : 14.7.8
   @nrwl/workspace : 14.7.8
   typescript : 4.8.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @nx-plus/docusaurus: 14.1.0
   	 @theunderscorer/nx-semantic-release: 1.14.0
```

**Comment by clementcreusat** [comment]
Hi,

I created an issue related to the same problem. I think the problem occurs with `nx` version above 14.7.5.
- Everything is working fine with `14.7.5`
- Not working from `14.7.6`

@iDVB 
Can you try by setting specifically version `14.7.5` inside your `package.json` ?

**Comment by clementcreusat** [comment]
@wolfie82 
Can you try by setting specifically version 14.7.5 inside your package.json ?

**Comment by wgebczyk** [comment]
I have same/similar issue.
Replacing in root/workspace `package.json` `14.7.6` to `14.7.5`, does not exit `nx graph` command and serves graph page.
With newer version daemon ships graph, but `nx graph` command immediately exists without any message. Setting `NX_VERBOSE_LOGGING` does not help to show additional info.

How I can debug/diagnose more `graph` command/action?

**Comment by iDVB** [comment]
@clementcreusat Yup! `14.7.5` doesn't have the issue. 
`nx graph` now works the charm.

**Comment by iDVB** [comment]
@clementcreusat 
Should I close this issue then? Sounds like you already captured the bug in another issue?

**Comment by clementcreusat** [comment]
@iDVB 
I closed my issue and said it was a duplicated of yours 👍

**Comment by wolfie82** [comment]
This fixed it for me as well.

`"@nrwl/workspace": "14.7.5"`

**Comment by jefflage** [comment]
14.7.5 fixes it for me also

**Comment by philipjfulcher** [comment]
This seems to be caused by a `process.exit` being called after the `graph` command is run. Added by this commit: https://github.com/nrwl/nx/commit/a3e480b6d7cdaf510cf54ee3d0a2024cdb6e1a3e

Working with @vsavkin to see if that's safe to remove. In the mean time, you can use the static file option to view your graph: `nx graph --file graph.html`

**Comment by philipjfulcher** [comment]
This should be fixed with our next patch release.

**Comment by clementcreusat** [comment]
Nice ! Thank you
