### ISSUE TITLE
@nrwl/react: Error during Storybook generation (TypeError: Cannot read properties of undefined (reading 'text'))

### ISSUE THREAD

**Issue by Lonli-Lokli** [nrwl/nx#12155]
## Current Behavior
Error during storybook configguration creation

## Expected Behavior
No errors

## Steps to Reproduce
```
const AnyOfCustomOperatorComponentNew = (props: any) => {
  const onValueChanged = useCallback(
    e => {
      props.data.setValue(e.value && e.value.length ? e.value : null);
    },
    [props.data]
  );

 return (
    <div>test</div>
  );
};
```

### Failure Logs
  NX   Cannot read properties of undefined (reading 'text')

TypeError: Cannot read properties of undefined (reading 'text')
    at getComponentPropsInterface (D:\sources\rmboa\node_modules\@nrwl\react\src\utils\ast-utils.js:425:54)
    at getDefaultsForComponent (D:\sources\rmboa\node_modules\@nrwl\react\src\utils\component-props.js:23:71)
    at findPropsAndGenerateFile (D:\sources\rmboa\node_modules\@nrwl\react\src\generators\component-story\component-story.js:51:94)
    at D:\sources\rmboa\node_modules\@nrwl\react\src\generators\component-story\component-story.js:38:17
    at Array.forEach (<anonymous>)
    at createComponentStoriesFile (D:\sources\rmboa\node_modules\@nrwl\react\src\generators\component-story\component-story.js:37:28)
    at D:\sources\rmboa\node_modules\@nrwl\react\src\generators\component-story\component-story.js:68:9
    at Generator.next (<anonymous>)
    at D:\sources\rmboa\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)

### Environment
   Node : 16.17.0
   OS   : win32 x64
   npm  : 8.15.0
   
   nx : 14.7.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.7.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.5
   @nrwl/eslint-plugin-nx : 14.7.5
   @nrwl/express : 14.7.5
   @nrwl/jest : 14.7.5
   @nrwl/js : 14.7.5
   @nrwl/linter : 14.7.5
   @nrwl/nest : 14.7.5
   @nrwl/next : Not Found
   @nrwl/node : 14.7.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.7.5
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.5
   @nrwl/web : 14.7.5
   @nrwl/workspace : 14.7.5
   typescript : 4.8.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

**Comment by mandarini** [comment]
Hi there @Lonli-Lokli ! Thanks for filing an issue! Can you please give me a bit more context, to help me reproduce? The snippet you posted, is this a React component? Can you share a reproduction repository that I can clone and work on? Thank you so much! :)

**Comment by Lonli-Lokli** [comment]
@mandarini thanks for fix, I totally forget about repro request

**Comment by gpalomar** [comment]
Hi! I'm getting the same error when trying to run `nx g @nrwl/react:storybook-configuration [project_name]` to add storybook to an existing applicatin. All related @nrwl deps have 15.3.3 version. How can it be fixed?

**Comment by mandarini** [comment]
Hi @gpalomar ! Can I see your `nx report` please?

**Comment by gpalomar** [comment]
Sure!

`Node : 16.15.0
   OS   : linux x64
   yarn : 1.22.15
   
   nx : 15.3.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.3.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.3.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.3.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.3.3
   @nrwl/web : 15.3.3
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:`

**Comment by mandarini** [comment]
Hmm I see, that's weird. Can you please share a simple reproduction repository for me? And can you please run `nx g @nrwl/react:storybook-configuration [project_name] --verbose` and tell me where (in which file) the error is happening? You can paste the error stack here if you want!

**Comment by gpalomar** [comment]
TypeError: Cannot read properties of undefined (reading 'text')
    at getComponentPropsInterface (/home/user/Repositories/nx_project/node_modules/@nrwl/react/src/utils/ast-utils.js:440:54)
    at getDefaultsForComponent (/home/user/Repositories/nx_project/node_modules/@nrwl/react/src/utils/component-props.js:23:71)
    at findPropsAndGenerateFile (/home/user/Repositories/nx_project/node_modules/@nrwl/react/src/generators/component-story/component-story.js:51:94)
    at createComponentStoriesFile (/home/user/Repositories/nx_project/node_modules/@nrwl/react/src/generators/component-story/component-story.js:46:9)
    at /home/user/Repositories/nx_project/node_modules/@nrwl/react/src/generators/component-story/component-story.js:68:9
    at Generator.next (<anonymous>)
    at /home/user/Repositories/nx_project/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/user/Repositories/nx_project/node_modules/tslib/tslib.js:114:16)
    at componentStoryGenerator (/home/user/Repositories/nx_project/node_modules/@nrwl/react/src/generators/component-story/component-story.js:67:20)

**Comment by gpalomar** [comment]
Thanks for your quick response.

Changing that line error has gone, but it freezes and don't end. Also running with `--verbose` but only displays this:
adding .storybook folder to the root directory
adding .storybook folder to your application

**Comment by gpalomar** [comment]
Hi again! It finally worked after waiting a lot. Thanks for helping!

**Comment by mandarini** [comment]
Ok, so I'll just push the above mentioned fix. Thanks!
