### ISSUE TITLE
Configuration docs are now missing

### ISSUE THREAD

**Issue by arizonatribe** [nrwl/nx#12161]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Used to be the `project.json` doc in the `docs/shared/configuration/` directory of the NX repository.

### Additional context or description

I've been searching for the docs on the `project.json` configuration details and Google is routing me to a dead link.
It looks like [back on August 29th ](https://github.com/nrwl/nx/commit/e717660102dcf0b6bb660d18063752042753e97d#diff-05b76c01f67b416df433e0f8c8b24fc944e479d6c56ebee6d639bcf2d06d3ee6)all the docs in the `docs/shared/configuration/` directory were deleted. The squashed commit covers 175+ files and it's hard to tell if the content was moved. Normally, if a `git mv` was used it would show where the docs now reside, but maybe the content itself was just moved elsewhere.

Would @isaacplmann or anyone else mind explaining what happened to the docs on the NX `project.json`? There's been a lot of dead links on NX docs searches in Google this year, and it's getting difficult to get work done when information is shuffled around so frequently.

**Comment by isaacplmann** [comment]
You want this page:
https://nx.dev/reference/project-configuration
