### ISSUE TITLE
Running the yarn nx dep-graph doesn't work

### ISSUE THREAD

**Issue by Fawwad-Khan** [nrwl/nx#12176]
## Current Behavior
Running the yarn nx dep-graph doesn't work, the web page gets served but gets automatically terminated by the console before the webopage event loads.

<img width="705" alt="image" src="https://user-images.githubusercontent.com/41516971/191708427-a4987665-569a-4e6d-88f0-b9e85270e529.png">

## Expected Behavior
Running the yarn nx dep-graph should load the graph 

I'm new to nx and tried googling but to no avail can someone please help?

**Comment by arshia-gh** [comment]
I'm having a similar issue while using npm
![image](https://user-images.githubusercontent.com/76017461/191756656-27d0eb57-9bed-4ed8-95f7-395868dd872b.png)

**Comment by maboesanman** [comment]
I've also seen this.
![Screen Shot 2022-09-22 at 3 14 24 PM](https://user-images.githubusercontent.com/3190108/191842308-7b635893-fbe8-4581-98c0-6a0cd1e9064e.png)

it's broken on 14.7.6, and works on 14.7.5

**Comment by AgentEnder** [comment]
This is fixed in 14.7.10, or latest.
