### ISSUE TITLE
Incompatible peer dependency with jasmine-marbles (0.4.0 -> 0.4.1)

### ISSUE THREAD

**Issue by brandon-kiel-ascendlearning-com** [nrwl/nx#1219]
## Expected Behavior

When running the update @nx/schematics command in the CLI, I expect the package to be updated

## Current Behavior

Incompatible peer dependency found. Package "@nrwl/nx" has an incompatible peer dependency to "jasmine-marbles" (requires "0.4.0", would install "0.4.1")

## Failure Information (for bugs)

Package "@nrwl/nx" has an incompatible peer dependency to "jasmine-marbles" (requires "0.4.0", would install "0.4.1")

### Steps to Reproduce

1. yarn update

### Context

- version of Nx used - 7.7.0
- version of Angular CLI used - 7.3.1

## Other
I see commit 852 attempted to fix the issue. However, a specific version was referenced (0.4.0).
This bug will likely continue to bubble up until the team widens the range of accepted versions.

**Comment by vsavkin** [comment]
Thank you for submitting the issue.
