### ISSUE TITLE
/generate reference has duplicate descriptions

### ISSUE THREAD

**Issue by cmgriffing** [nrwl/nx#12196]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/nx/generate#defaults

### Additional context or description

The `defaults` and `dryRun` sections have the exact same description. Is this intended?

**Comment by rubiagatra** [comment]
I think it is not intended, I'll try to update the docs

**Comment by rubiagatra** [comment]
Please check the PR @cmgriffing @AgentEnder #13759
