### ISSUE TITLE
Nx Cache Daemon goes haywire - starts consuming 100% CPU until being force-quit

### ISSUE THREAD

**Issue by bjornharvold** [nrwl/nx#12201]
From one dev to another: Guessing this is a race condition.

We are having this issue on a 1200-module Nx monorepo.

## Current Behavior
This is an issue that occurs at random. It can happen when doing a build and it can happen when running serve.
This occurs both on our CI server (Ubuntu Linux) and locally (Mac OS).

The process that goes to 100% and stays there is:
`501 11051     1   0 10:43AM ??         3:13.73 /opt/homebrew/Cellar/node@16/16.17.0_1/bin/node /Users/crash/git/monorepo-typescript/node_modules/nx/src/daemon/server/start.js`

## Steps to Reproduce
We are unable to reproduce this issue somewhere else. Guessing this comes with the size of the monorepo.

Locally and on the build server, we can reproduce, at random by running a build or serving up the application. The freeze only occurs when there is something in the Nx cache. If we run `npx nx reset` and restart / rebuild, it does what it's supposed to do. This occurs on a daily basis for developers that are serving up the app. When making changes and the app recompiles, it happens most frequently. On the build server, the issue has occurred a couple of times with the build just hanging forever. We leverage Nx Cache on build server and do not reset it on every build.... That would just be dumb 🤓

### Failure Logs
Including what the activity monitor shows me
<img width="671" alt="Screen Shot 2022-09-23 at 1 28 24 PM" src="https://user-images.githubusercontent.com/641791/191903589-1e90e5a4-9057-4d25-94e2-33e9c6475e8f.png">
<img width="671" alt="Screen Shot 2022-09-23 at 1 28 16 PM" src="https://user-images.githubusercontent.com/641791/191903593-c3a9fc94-f150-48d5-8fab-f1dc45bd3e30.png">

### Environment
FYI when in this state, we cannot even execute `npx nx report`. It just hangs waiting for something.
```
 Node : 16.17.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 14.7.11
   @nrwl/angular : 14.7.11
   @nrwl/cypress : 14.7.11
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.11
   @nrwl/eslint-plugin-nx : 14.7.11
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.11
   @nrwl/js : 14.7.11
   @nrwl/linter : 14.7.11
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.11
   @nrwl/web : 14.7.11
   @nrwl/workspace : 14.7.11
   typescript : 4.8.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @fortawesome/angular-fontawesome: 0.11.1
   	 @ng-bootstrap/ng-bootstrap: 13.0.0
   	 @ngneat/transloco: 4.1.1
   	 @ngrx/component: 14.3.1
   	 @ngrx/component-store: 14.3.1
   	 @ngrx/data: 14.3.1
   	 @ngrx/effects: 14.3.1
   	 @ngrx/entity: 14.3.1
   	 @ngrx/router-store: 14.3.1
   	 @ngrx/store: 14.3.1
   	 @ngrx/store-devtools: 14.3.1
   	 angular-calendar: 0.30.1
   	 @compodoc/compodoc: 1.1.19
   	 @jscutlery/semver: 2.27.0
   	 @ngrx/schematics: 14.3.1
   	 @storybook/angular: 6.5.12
```

Hope this helps. Eager to find a solution. At your disposal.

🦸‍♂️

**Comment by vsavkin** [comment]
@bjornharvold thank you so much for submitting the issue. 

Do you by any chance have the contents of the daemon log file? By default it will be in the node_moduels/.cache/nx/d directly.

**Comment by bjornharvold** [comment]
Hi @vsavkin 

This log is from our build server that just hung and had to be restarted.

[daemon.log](https://github.com/nrwl/nx/files/9641286/daemon.log)

**Comment by vsavkin** [comment]
@bjornharvold Thank you. Looking at this issue today.

**Comment by vsavkin** [comment]
@bjornharvold could you please try updating to 14.7.14-beta.1? I think I was able to repro your issue and the version above fixes it for me.

**Comment by bjornharvold** [comment]
Hi @vsavkin 

Thank you for the quick response 🦸‍♂️ Will try that today and report back.

**Comment by bjornharvold** [comment]
Hi @vsavkin 

Developers and CI server have not been complaining the whole day.

Needle in a haystack 🪡

👏🏻

**Comment by vsavkin** [comment]
@bjornharvold thank you! Glad it worked.
