### ISSUE TITLE
Nx daemon throw error : Cannot read properties of null (reading 'write')

### ISSUE THREAD

**Issue by kunyan** [nrwl/nx#12200]
## Current Behavior

When I upgrade nx from 14.7.3 to 14.7.6 and latest 14.7.11

It will throw following errors

```
 >  NX   Cannot read properties of null (reading 'write')


TypeError: Cannot read properties of null (reading 'write')
    at /opt/app-root/src/node_modules/nx/src/daemon/client/client.js:170:29
    at new Promise (<anonymous>)
    at DaemonClient.<anonymous> (/opt/app-root/src/node_modules/nx/src/daemon/client/client.js:165:20)
    at Generator.next (<anonymous>)
    at /opt/app-root/src/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/opt/app-root/src/node_modules/tslib/tslib.js:114:16)
    at DaemonClient.sendMessageToDaemon (/opt/app-root/src/node_modules/nx/src/daemon/client/client.js:157:24)
    at /opt/app-root/src/node_modules/nx/src/daemon/client/client.js:112:54
    at PromisedBasedQueue.<anonymous> (/opt/app-root/src/node_modules/nx/src/utils/promised-based-queue.js:18:27)
```

I assume it should be some bug when nx daemon get OS socket.

event in nx 14.7.3, I always got error : nx daemon failed need to restart

## Expected Behavior

No errors
## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

```
 >  NX   Cannot read properties of null (reading 'write')


TypeError: Cannot read properties of null (reading 'write')
    at /opt/app-root/src/node_modules/nx/src/daemon/client/client.js:170:29
    at new Promise (<anonymous>)
    at DaemonClient.<anonymous> (/opt/app-root/src/node_modules/nx/src/daemon/client/client.js:165:20)
    at Generator.next (<anonymous>)
    at /opt/app-root/src/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/opt/app-root/src/node_modules/tslib/tslib.js:114:16)
    at DaemonClient.sendMessageToDaemon (/opt/app-root/src/node_modules/nx/src/daemon/client/client.js:157:24)
    at /opt/app-root/src/node_modules/nx/src/daemon/client/client.js:112:54
    at PromisedBasedQueue.<anonymous> (/opt/app-root/src/node_modules/nx/src/utils/promised-based-queue.js:18:27)
```

**Comment by AgentEnder** [comment]
What does `nx report` say? You can use `NX_DAEMON=false nx report` to disable the daemon for that command.

**Comment by kunyan** [comment]
```
 >  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : linux x64
   npm  : 8.3.1

   nx : 14.7.11
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.7.11
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.11
   @nrwl/eslint-plugin-nx : 14.7.11
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.11
   @nrwl/js : 14.7.11
   @nrwl/linter : 14.7.11
   @nrwl/nest : 14.7.11
   @nrwl/next : 14.7.11
   @nrwl/node : 14.7.11
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.7.11
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.11
   @nrwl/web : 14.7.11
   @nrwl/workspace : 14.7.11
   typescript : 4.8.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @compodoc/compodoc: 1.1.19
   	 @jscutlery/semver: 2.27.0
   	 @nx-tools/nx-prisma: 3.0.1
```



I also got errors
```
>  NX   Nx Daemon was not able to compute the project graph.

   Log file with the error: /opt/app-root/src/node_modules/.cache/nx/d/daemon-error.log
   Please file an issue at https://github.com/nrwl/nx
   Nx Daemon is going to be disabled until you run "nx reset".
```

In case of it's running in a openshift build pod, the daemon-error log can not be viewed since the build pod down.
I did found this issue in previous version of nx

**Comment by prmichaelsen** [comment]
I feel like half my dev experience with `nx` is fixing random build errors that suddenly crop up that weren't there a day before with very vague error messages that don't really provide any useful information or stacktrace. I'm questioning whether it's worth it to continue using `nx`..

**Comment by DaSchTour** [comment]
I get the same error after successful build of angular. This error only happens with the build inside Docker.

I added an `nx reset` before the build but I still get the error about nx deamon in the build directly after the nx reset.

I extracted the logfiles but they are not really helpful

daemon-error.log
```
#22 0.474 Failed to start the Nx Daemon process.
#22 0.474
#22 0.474 Messages from the log:
#22 0.474
#22 0.474
#22 0.474
#22 0.474 More information: /build/node_modules/.cache/nx/d/daemon.log
```

Sorry. But is this a joke? That's not a useful log.

daemon.log
```
#23 0.640 [NX Daemon Server] - 2022-10-19T12:55:37.141Z - Started listening on: /tmp/5c3174b74edc6f2b9e07/d.sock
#23 0.640 [NX Daemon Server] - 2022-10-19T12:55:37.203Z - [WATCHER]: Subscribed to changes within: /build
#23 0.640 [NX Daemon Server] - 2022-10-19T12:55:37.204Z - Established a connection. Number of open connections: 1
#23 0.640 [NX Daemon Server] - 2022-10-19T12:55:37.266Z - Closed a connection. Number of open connections: 0
#23 0.640 [NX Daemon Server] - 2022-10-19T12:57:08.893Z - [WATCHER]: 48 file(s) created or restored, 0 file(s) modified, 0 file(s) deleted
#23 0.640 [NX Daemon Server] - 2022-10-19T12:57:09.032Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
#23 0.640 [NX Daemon Server] - 2022-10-19T12:57:09.864Z - Time taken for 'hash changed files from watcher' 34.96209999918938ms
#23 0.640 [NX Daemon Server] - 2022-10-19T12:57:17.974Z - [WATCHER]: 74 file(s) created or restored, 0 file(s) modified, 0 file(s) deleted
#23 0.640 [NX Daemon Server] - 2022-10-19T12:57:18.200Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
```

Looks like there is no error in the nx deamon but it's not running correctly?
The behaviour is very very strange.

**Comment by AgentEnder** [comment]
Can you run nx report?

**Comment by eugenejeonme** [comment]
I'm having the same problem.
Is there a solution?

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/36671804/197993302-cca0c3ab-a2a3-4f14-bac4-2d4142fa8acd.png">

**Comment by DaSchTour** [comment]
> I'm having the same problem.
> 
> Is there a solution?
> 
> 
> 
> <img width="1097" alt="image" src="https://user-images.githubusercontent.com/36671804/197993302-cca0c3ab-a2a3-4f14-bac4-2d4142fa8acd.png">
> 
> 

set NX_DAEMON=false
I guess it's not needed on CI

**Comment by eugenejeonme** [comment]
> > I'm having the same problem.
> > Is there a solution?
> > <img alt="image" width="1097" src="https://user-images.githubusercontent.com/36671804/197993302-cca0c3ab-a2a3-4f14-bac4-2d4142fa8acd.png">
> 
> set NX_DAEMON=false I guess it's not needed on CI

Thank you so much.
Using Dockerfile, I ran it with Kaniko.
It passes and works for me.

<img width="768" alt="image" src="https://user-images.githubusercontent.com/36671804/198004344-f475b902-104e-498d-9f32-f9500ed631e6.png">
<img width="757" alt="image" src="https://user-images.githubusercontent.com/36671804/198004385-2889f3b6-a33c-47f5-9ec1-bcd74b2e65b8.png">

**Comment by FrozenPandaz** [comment]
So this only happens in Docker? The daemon is supposed to be disabled by default within docker. How are you all running your dockerfiles? Is it via `docker build`? Or something else?

**Comment by eugenejeonme** [comment]
> So this only happens in Docker? The daemon is supposed to be disabled by default within docker. How are you all running your dockerfiles? Is it via docker build? Or something else?


In my case, using K8s (Kubernetes).
So, using Kaniko, read Dockerfile and create Container Image.

**Comment by DaSchTour** [comment]
> So this only happens in Docker? The daemon is supposed to be disabled by default within docker. How are you all running your dockerfiles? Is it via `docker build`? Or something else?

In my case it was when using docker buildx because we have a multiplatform build.
Although I must admit that building inside docker maybe is not the ideal solution.
