### ISSUE TITLE
Update Prettier and include *.less files

### ISSUE THREAD

**Issue by SebastianPodgajny** [nrwl/nx#1220]
# Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

I expect `nx format` to use latest version of prettier and format "*.less" files 

## Current Behavior

`nx format` uses its own prettier in version 1.15.3 and doesn't include "*.less" files

## Failure Information (for bugs)

Prettier doesnt preserve surrounding line breaks
https://github.com/prettier/prettier/pull/5596

less is not included in extensions array
https://github.com/nrwl/nx/blob/256d83c3f98be9b87eca877864183a42e11b87e2/packages/schematics/src/command-line/format.ts#L13

### Steps to Reproduce

run `nx format:write`

### Context

Please provide any relevant information about your setup:

- version of Nx used 7.7.2
- version of Angular CLI used 7.3.5

**A minimal reproduce scenario using allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

Please include any relevant log snippets or files here.

## Other

Any other relevant information that will help us help you.

**Comment by FrozenPandaz** [comment]
Sounds good to me! Would someone like to contribute a PR?

**Comment by vsavkin** [comment]
@SebastianPodgajny I merged your PR. Thank you for your contribution!
