### ISSUE TITLE
[STORYBOOK] storyStoreV7, Webpack5 lazyCompilation and fsCache options don't work

### ISSUE THREAD

**Issue by ild0tt0re** [nrwl/nx#12219]
## Current Behavior
When i configure storybook webpack 5 with **code splitting**, **lazy compilation** and **filesystem caching**, storybook start without considering no one of that configuraton options: 
```js
// .storybook/main.js

module.exports = { 
  features: { 
     storyStoreV7: true 
  },
  core: {
    builder: {
      name: 'webpack5',
      options: {
        lazyCompilation: true,
        fsCache: true,
      },
    },
  },
};
```

## Expected Behavior
When I set `storyStoreV7: true`, `lazyCompilation: true` and  `fsCache: true`, storybook start with code splitting, lazy Compilation and file system cache. 

## Steps to Reproduce
Set storybook main file as below

```js
// .storybook/main.js

module.exports = { 
  features: { 
     storyStoreV7: true 
  },
  core: {
    builder: {
      name: 'webpack5',
      options: {
        lazyCompilation: true,
        fsCache: true,
      },
    },
  },
};
```
Official storybook doc: https://storybook.js.org/docs/react/builders/webpack

### Failure Logs
None! 
Storybook start without considering the provided webpack 5 configuration described above. 

### Environment
Nx v14.6.1
Storybook 6.5.4

**Comment by mandarini** [comment]
Hi there @ild0tt0re ! Thanks for filing an issue! :D 

I am working through it now. It seems that the `storyStoreV7` codesplitting feature works for me: https://app.warp.dev/block/lBlBBfRmgwTs7KS3o4z0z9

Check out [my repo](https://github.com/mandarini/storybook-import-type/tree/extra-build-features). You MUST checkout the `extra-build-features` (after you clone, `git checkout extra-build-features`), because I reused another repo I was using for some other tests, sorry!!

Looking at the `builder` options, now!

**Comment by mandarini** [comment]
Hello! So, to me it looks like the builder options **are** getting passed:

![Screenshot 2022-09-26 at 4 17 24 PM](https://user-images.githubusercontent.com/6603745/192286889-7b32cb1d-5494-486f-b3d8-581cedd31f1b.png)

If you attach a debugger in this file (`node_modules/@storybook/core-server/dist/cjs/utils/get-preview-builder.js`) on your local repository, on line 35/36, you can see that the builder options are getting passed alright to Storybook from Nx!

![Screenshot 2022-09-26 at 4 19 47 PM](https://user-images.githubusercontent.com/6603745/192287142-e6ffc0ce-8c5e-4001-a8ca-f86b7d15a095.png)


Can you provide me with a reproduction repository, where I can see that these do not work? Maybe retry with latest version of Nx? Although I don't see why any version would not work.. We're just using `.storybook/main.js` without making any adjustments, so it should work as is...

**Comment by mandarini** [comment]
If you observe a behaviour other than what you expect, maybe it's an issue on the Storybook side...

**Comment by ild0tt0re** [comment]
@mandarini thanks for your replies!

From Storybook blog article on the lazy compilation, we should notice a major improvement in performance as you can read here:
https://storybook.js.org/blog/storybook-lazy-compilation-for-webpack/

I updated to the latest version of `Nx 14.7.17` and `@storybook/react v6.5.12` but `lazyCompilation` and `fsCache` seem don't work since we don't notice any improvement in performance as for `next.js` with lazy compilation.

Here is my output:
https://app.warp.dev/block/UIy5kVd18JX44GrSyY1LFv

**Comment by mandarini** [comment]
I see. Maybe this an issue with Storybook? From our side, we are passing the parameters down to the Storybook builder.

**Comment by mandarini** [comment]
If you build, do you see the different chunks, from the code-splitting? Can you try the debugging I suggested, to verify that params are getting passed?

**Comment by ild0tt0re** [comment]
> If you build, do you see the different chunks, from the code-splitting? Can you try the debugging I suggested, to verify that params are getting passed?

- ✅  Yes, **code splitting**/`storyStoreV7` with `$ nx build-storybook my-project` work!
- ❌ `lazyCompilation` and `fsCache`with `$ nx storybook my-project` don't work

Params getting passed but I notice a strange thing:

If I start storybook extending the base configuration below with `module.exports = {
  ...rootMain, ... }` in `myProject/.storybook/main.js` _without repeating_ the `core` object, it gets passed while debugging the file but the output in the console gives me

>  It looks like you use Webpack 5 but your Storybook setup is not configured to leverage that
>  and thus falls back to Webpack 4.
>  Make sure you upgrade your Storybook config to use Webpack 5.
>
>  - https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324#upgrade

```
// .storybook/main.js
module.exports = {
  core: {
    builder: {
      name: 'webpack5',
      options: {
        lazyCompilation: true,
        fsCache: true,
      },
    },
  },
....
}
```

**Comment by mandarini** [comment]
Hmmm I still don't get it. I tried all the different combinations in my project and it still works as expected. Can I see your `nx report`? Also, is it possible that you create a minimum reproduction repository for me? In [my repository](https://github.com/mandarini/storybook-import-type/tree/extra-build-features) I have the same syntax as you, but still I am not getting that error message (which probably is the answer to everything). Can you please either make the changes to my repo, or create one, where you get that message: 

```
It looks like you use Webpack 5 but your Storybook setup is not configured to leverage that
and thus falls back to Webpack 4.
Make sure you upgrade your Storybook config to use Webpack 5.
```
Also, please can I see the `nx report`

**Comment by ild0tt0re** [comment]
I got the same error in the provided **repro** above. 

My **Nx report**:
```
   Node : 16.13.1
   OS   : darwin x64
   pnpm : 7.12.2

   nx : 14.7.17
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.7.17
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.17
   @nrwl/eslint-plugin-nx : 14.7.17
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.17
   @nrwl/js : 14.7.17
   @nrwl/linter : 14.7.17
   @nrwl/nest : Not Found
   @nrwl/next : 14.7.17
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.7.17
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.17
   @nrwl/web : 14.7.17
   @nrwl/workspace : 14.7.17
   typescript : 4.7.2
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @jscutlery/semver: 2.26.0
   	 ngx-deploy-npm: 4.1.0
```

**Comment by mandarini** [comment]
Ok! Perfect, thank you SO much for your reproduction! I figured out the issue and I'm putting in a PR now, that should fix the warning. The other part (not getting the optimizations you expect) I think it's on the Storybook side. Nx is passing all options as expected to the Storybook builder.

You can verify this [as I explained above](https://github.com/nrwl/nx/issues/12219#issuecomment-1258033308).

The confusing log fix will land soon! :D :D Thank you so so much!

**Comment by ild0tt0re** [comment]
Hey @mandarini I found what is missing for `lazyCompilation` and `fsCache` to work :tada:

> 🚀 We noticed a **huge performance improvement** -> **more than 10X :zap:** from **~90s to ~7s**  in **dev mode**:
```shell
$ nx storybook $myProject
```

### How Storybook work?
Setting the following builder ...
```
// .storybook/main.js

module.exports = {
  core: {
      builder: {
        name: 'builder-webpack5',
        options: {
          lazyCompilation: true,
          fsCache: true,
        },
      },
    },
  ...
```
... the **base webpack configuration** should be composed with the following options as a fresh install of **Storybook without Nx**
```js
const webpackBaseConfig = {

    // base config for `lazyCompilation` and `fsCache` to work
    optimization: {
        splitChunks: { chunks: 'all' },
        runtimeChunk: true,
        sideEffects: true,
        usedExports: false,
        moduleIds: 'named',
        minimizer: [],
    },
    cache: { type: 'filesystem' },
    experiments: { lazyCompilation: { entries: false } },

    // other base config....

}
```

### What needs to do Nx side?

Considering `lazyCompilation` and `fsCache` builder options as did by **Storybook** here:
https://github.com/storybookjs/storybook/blob/7035ea7389393da041985ebc491ee58dedb50d06/code/lib/builder-webpack5/src/preview/base-webpack.config.ts#L53-L55


### My final configuration for maximizing the performance (SWC + lazyCompilation + devtool = false)

```js
// .storybook/main.js

module.exports = {
  webpackFinal: async (config, { configType }) => {
      
       // not needed for `lazyCompilation` but you get fastest performance in rebuild with webpack
      config.devtool = false 
      
      config = {
        ...config,
        optimization: {
          splitChunks: { chunks: 'all' },
          runtimeChunk: true,
          sideEffects: true,
          usedExports: false,
          moduleIds: 'named',
          minimizer: [],
        },
        cache: { type: 'filesystem' },
        experiments: { lazyCompilation: { entries: false } },
      }
      return config
    },

  addons: [
    {
      name: 'storybook-addon-swc',
      options: {
        enable: true,
        enableSwcLoader: true,
        enableSwcMinify: false,
        swcLoaderOptions: {
          jsc: {
            experimental: {
              plugins: [
                [
                  // ONLY if you use styled-components lib
                  '@swc/plugin-styled-components',
                  {
                    displayName: true,
                    ssr: true,
                  },
                ],
              ],
            },
          },
        },
        swcMinifyOptions: {},
      },
    },

  features: {
    babelModeV7: true,
   // code splitting
    storyStoreV7: true,
  },
```

**Comment by mandarini** [comment]
Discussion transferred to [this issue](https://github.com/nrwl/nx/issues/12387)
