### ISSUE TITLE
Proxy error for a fresh Nx + Nestjs project

### ISSUE THREAD

**Issue by MilosStanic** [nrwl/nx#1221]
# Prerequisites

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

I expect to start blank application when running `ng serve appname`

## Current Behavior

The app compiles and runs, but I get an error in the console when I open the app in my browser at http://localhost:4200

```[HPM] Error occurred while trying to proxy request /api/hello from localhost:4200 to http://localhost:3333 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)```

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. npx create-nx-workspace appname
2. selected nestjs app during installation
3. cd appname
4. ng serve appname

### Context

Please provide any relevant information about your setup:

- version of Nx used latest
- version of Angular CLI used 7.3.1

### Failure Logs

```[HPM] Error occurred while trying to proxy request /api/hello from localhost:4200 to http://localhost:3333 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)```

Opening Chrome Dev console, in the Network section, the request to `/api/hello` returns the following message: 
```Error occured while trying to proxy to: localhost:4200/api/hello```

Another question, while I'm here, is there a canonical way to upgrade Nestjs to 6.0, as the current installation uses 5.5? Or should I wait for nx to publish upgrade to 6.0?

**Comment by MilosStanic** [comment]
My bad, I didn't know I was supposed to do `ng serve api` as well.

**Comment by SOHELAHMED7** [comment]
:+1: 

Adding more info that might help new comers/first timer

In CLI (Terminal for e.g.) open new tab

`user@host:/path/to/your/workspace$ ng serve api`

**Comment by chigix** [comment]
Although I have got the usage on launching api server and angular application separately, I'm still curious that whether there would be cons or risky problems if merge serving angular and api/nest server into one npm script ?

**Comment by kleky** [comment]
I got caught out by this as a newby. Saved with thanks to this issue

**Comment by mo-klue** [comment]
> 👍
> 
> Adding more info that might help new comers/first timer
> 
> In CLI (Terminal for e.g.) open new tab
> 
> `user@host:/path/to/your/workspace$ ng serve api`

still a valid point

**Comment by mikelyons** [comment]
Hmm, I've got
```
        "serve": {
          "executor": "@nrwl/web:dev-server",
          "options": {
            "buildTarget": "admin:build",
            "proxyConfig": "apps/admin/proxy.conf.json"
          },
          "configurations": {
            "production": {
              "buildTarget": "admin:build:production"
            }
          }
        },```
and proxy conf
```{
  "/api": {
    "target": "http://localhost:3333/api",
    "secure": false,
    "changeOrigin": true,
    "logLevel": "debug"
  }
}```
and the frontend server log shows proxy info
but my request to "/api" doesn't target port 3333 it just targets the port the front end is served from 4200 still

What could prevent the proxy from working when it is configured properly?

**Comment by tamirazrab** [comment]
![111](https://user-images.githubusercontent.com/38686510/133519976-566afcb7-4984-4fe1-ba15-ae430bd66bd2.png)

Actually it was pretty annoying, and after about 3 hours of wasting time, it was working the whole time, check the URL it isn't correct, but the request was being proxies to localhost:3333 as error can be seen sent from my back end. It might be actually working for you just in case it is working for me.
