### ISSUE TITLE
affected:test --all does not watch changes in files/specs

### ISSUE THREAD

**Issue by dtomaszewski** [nrwl/nx#1222]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

- [y] I am running the latest version
- [y] I checked the documentation and found no answer
- [y] I checked to make sure that this issue has not already been filed
- [y] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

`yarn affected:test --all` 
Runs tests for all libs and watches all libs

## Current Behavior

`yarn affected:test --all`
Runs tests for all libs and watches only apps

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create app with several libs
2. set `singleRun: false` in karma.conf.js
2. run `yarn affected:test --all`
3. make change in lib

### Context

Please provide any relevant information about your setup:

- version of Nx used - **7.7.2**
- version of Angular CLI used - **7.3.1**

I want to set development command to watch changes in files and rerun tests during development. I tried many combinations with `affected:` and failed. Do I need to run every lib/app test in separate cmd to make it work as I want to ?

**Comment by vsavkin** [comment]
@dtomaszewski could you provide a repro?

**Comment by dtomaszewski** [comment]
Hi @vsavkin, sure

It's hard to do it on stackblitz as it can be reproduced in console so I'll provide sample repo with clean Nx project :

https://github.com/dtomaszewski/gdanx-workspace
(see that karma singleRun option is set to false)

When You run
`yarn affected:test --all`

Some tests will pass and process will be watched, then after edition of test in `payments-data-access.module.spec.ts` nothing happens, when You'll edit test in `app.component.spec.ts` it will run only sinlge test again. 

I hope this explanation is enough :)

**Comment by kszafraniec** [comment]
My guess is that NX runs tests for each affected app/lib on the list and when it comes to karma test with `singleRun: false`, it waits forever for its end and does not proceed to next task. It behaves properly when nx command is run with `--parallel`, but then all tests are in infinite watch loop together.

**Comment by vsavkin** [comment]
@dtomaszewski thank you for providing the repro.

**Comment by vsavkin** [comment]
I'm sorry, but I'm going to close this issue. 

If the problem persists, could you reopen the issue with a min repro.
