### ISSUE TITLE
 Nx failed to create a workspace. with react

### ISSUE THREAD

**Issue by vihangamalinda** [nrwl/nx#12228]
## Current Behavior
Nx-Monorepo creation failed

## Expected Behavior
Creation of nx workspace.

## Steps to Reproduce
Creation of nx monorepo with react with the help of NX documentation.

Command line code:
C:\Users\vihangam\Desktop\Projects\R&D\Micro Front-end\test>npx create-nx-workspace --preset=react
√ Workspace name (e.g., org name)     · tst
√ Application name                    · store
√ Default stylesheet format           · scss
√ Enable distributed caching to make your CI faster · Yes

 >  NX   Nx is creating your v14.7.8 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

√ Installing dependencies with npm
× Creating your workspace in tst

 >  NX   Nx failed to create a workspace.

   Exit code: 1
   Log file: C:\Users\vihangam\AppData\Local\Temp\tmp-15304-fOV9jY2KK2AA\error.log

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

Error.log report:

>  NX  Generating @nrwl/workspace/generators.json:new

CREATE tst/package.json
CREATE tst/README.md
CREATE tst/tools/generators/.gitkeep
CREATE tst/tools/tsconfig.tools.json
CREATE tst/tsconfig.base.json
CREATE tst/.editorconfig
CREATE tst/.gitignore
CREATE tst/.prettierignore
CREATE tst/.vscode/extensions.json
CREATE tst/workspace.json
CREATE tst/nx.json
CREATE tst/.prettierrc
CREATE tst/apps/.gitkeep
CREATE tst/libs/.gitkeep

 >  NX   Command failed: npm install

   Pass --verbose to see the stacktrace.

npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm ERR! code 1
npm ERR! path C:\Users\vihangam\Desktop\Projects\R&D\Micro Front-end\test\tst\node_modules\@parcel\watcher
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp-build
npm ERR! The system cannot find the path specified.
npm ERR! node:internal/modules/cjs/loader:958
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module 'C:\Users\vihangam\Desktop\Projects\node-gyp-build\bin.js'
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:803:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:18:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.9.0

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vihangam\AppData\Local\npm-cache\_logs\2022-09-26T03_25_49_612Z-debug-0.log

**Comment by ndcunningham** [comment]
Can you try this with the latest version of nx?
