### ISSUE TITLE
Don't include workspace.json for workspaces with just Nx core features

### ISSUE THREAD

**Issue by pmbanugo** [nrwl/nx#12220]
- [x] I'd be willing to implement this feature if I know my way around([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I usually just want to use Nx's core feature and use package.json to specify my projects like it's described in [core tutorial](https://nx.dev/getting-started/core-tutorial). However, I don't read that tutorial all the time and skip the important part of deleting **workspace.json**. The first time I tried Nx for a small project I spent days looking for a fix without realising I need to delete this file. I've also encountered it in a recent project where a new workspace was setup using Nx and they forgot to delete that file.

I suggest that Nx should skip adding that file when setting up Nx for just the core feature. It's easy to forget this and spend hours debugging why Nx doesn't recognise this. This happened to me *again today* and it'd be nice if we have a way of skipping this file.

## Motivation

It would save me (and hopefully many others) from forgetting to delete workspace.json and not getting the desired behaviour when using nx.

## Suggested Implementation

Skip adding that file to a new workspace.

**Comment by FrozenPandaz** [comment]
Great idea :+1: 

https://github.com/nrwl/nx/pull/12127 :wink:

**Comment by pmbanugo** [comment]
Thank you all!
