### ISSUE TITLE
Code coverage is wrong for sibling libraries

### ISSUE THREAD

**Issue by KarmaCop213** [nrwl/nx#12222]
## Current Behavior
Not sure if this is jest or nx related, but here it goes...

When I run jest to collect the code coverage using the following command:

`nx run my-library:test --testFile=the-best.component.spec.ts --codeCoverage`

I only get code coverage for the library where I'm running the command (in this case `my-library`).

The problem is that I have inside `the-best.component.ts` an alias import to a service inside a different module (for example, like this: `import { ExternalService } from "@app/external-library"`, that I'm not mocking inside `the-best.component.spec.ts`. This means that if I debug the test on `the-best.component.spec.ts` I can hit a breakpoint on `ExternalService`.

My assumption is that if I can hit a breakpoint inside `ExternalService`, then that file should have that line marked has covered by my test on `the-best.component.spec.ts`

A quick diagram:

```
|- my-library
|  |- the-best.component.spec.ts
|  |- the-best.component.ts
|
|- external-library
|  |- external.service.ts
```

## Expected Behavior
When running code coverage for tests on `the-best.component.spec.ts` I'd like to see code on `external.service.ts` to be covered if I'm not mocking it on `the-best.component.spec.ts`.

## Steps to Reproduce
I believe you just need to create an nx project, have 2 libraries, and from one library call a service from the other library. In the unit tests on the first library don't mock the second library.

### Environment
```
  Node : 12.22.10
  OS   : darwin x64
  npm  : 6.14.16
  
  nx : Not Found
  @nrwl/angular : 12.10.1
  @nrwl/cli : 12.10.1
  @nrwl/cypress : 12.10.1
  @nrwl/devkit : 12.10.1
  @nrwl/eslint-plugin-nx : 12.10.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.10.1
  @nrwl/linter : 12.10.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.10.1
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.1
  @nrwl/web : Not Found
  @nrwl/workspace : 12.10.1
  @nrwl/storybook : 12.10.1
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

```

**Comment by barbados-clemens** [comment]
I believe you'll need to configure collectCoverageFrom for your jest configuration 
https://jestjs.io/docs/configuration/#collectcoveragefrom-array

**Comment by fknop** [comment]
> I believe you'll need to configure collectCoverageFrom for your jest configuration https://jestjs.io/docs/configuration/#collectcoveragefrom-array

That's interesting, is there a way to get all the globs of dependant libraries using NX APIs?

**Comment by barbados-clemens** [comment]
You could certainly do it with the project graph, but let me see if there are any utils that make it easier from devkit.

**Comment by barbados-clemens** [comment]
Going to closes as there is a valid workaround with `collectCoverageFrom` jest config property
