### ISSUE TITLE
nx not working after nx reset (NX Daemon process terminated and closed the connection)

### ISSUE THREAD

**Issue by atsjo** [nrwl/nx#12237]
## Current Behavior
After upgrading to 14.7.11, not even nx report works after nx reset, if nx console extension is enabled

## Steps to Reproduce
Use vs code with nx console and nx 14.7.11 (or 9 or 10), run nx reset, then try to run any nx command...

### Failure Logs
PS C:\Users\atles\source\repos\teve-no\task4s> yarn nx report
yarn run v1.22.19
$ C:\Users\atles\source\repos\teve-no\task4s\node_modules\.bin\nx report

 >  NX   Daemon process terminated and closed the connection

   Please rerun the command, which will restart the daemon.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\atles\source\repos\teve-no\task4s>
### Environment
 >  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : win32 x64
   yarn : 1.22.19

   nx : 14.7.11
   @nrwl/angular : 14.7.11
   @nrwl/cypress : 14.7.11
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.11
   @nrwl/eslint-plugin-nx : 14.7.11
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.11
   @nrwl/js : 14.7.11
   @nrwl/linter : 14.7.11
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.11
   @nrwl/web : Not Found
   @nrwl/workspace : 14.7.11
   typescript : 4.8.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

**Comment by Cammisuli** [comment]
Right, it definitely sounds like an issue with the daemon. Someone who's more familiar with that should be able to help out more

**Comment by atsjo** [comment]
I ended up disabling the daemon via "useDaemonProcess": false in nx.json. That works fine for me, as the workspace is quite small, and I also don't end up with orphaned daemon processes that keeps running after vs code is closed sometimes. I'd rather do that than keep with 14.7.5, as the new bundler options for js is very handy:-)

From what I can see in the release notes, I would guess the refactoring for the daemon process in 14.7.6 probably introduces the instability for my workspace.

- core: rework the daemon process communication to use a queue and a long running connection ([a3e480b](https://github.com/nrwl/nx/commit/a3e480b6d7cdaf510cf54ee3d0a2024cdb6e1a3e))

**Comment by B1Z1** [comment]
I'm trying to implement a distributed cache for our application with AWS and got the same error when the application builds. At this moment I don't why it's happening, but maybe it might be connected with this problem

**Comment by mmswi** [comment]
When I try to run nx reset, even on admin console, I get this error

`Error: EPERM: operation not permitted, lstat '\\?\D:\Projects\failed-next\node_modules\.cache\nx\d\daemon.log'`

Regarding this daemon, I can't do anything to delete it. Not even as administrator.

**Comment by itspers** [comment]
Sad that this happen when i again decided to give Vscode a chance... Unfortunately downgrading extension doesn't help - so its in daemon, not extension.

**Comment by flensrocker** [comment]
👀

I have similar problems, when I have opened a workspace in VS Code with the Nx Console and try to run a nx command in a terminal outside of VS Code. I don't have a reproduction at hand. I can only shutdown VS Code to get the commands working.

For now I disable Nx Console, since I don't need it that often.

Nx 14.7.13

**Comment by arthurgailes** [comment]
Same here. NX no longer works with VSCode

**Comment by NhatPhuong** [comment]
Just disable & Re-enable Nx-Console again

**Comment by deuriib** [comment]
Same issue here, I disabled Nx-Console and everything works fine.

**Comment by atsjo** [comment]
This works in 15.9.x and 16.x, so closing the issue...
