### ISSUE TITLE
nrwl/builders - Paths with wildcard can't be resolved

### ISSUE THREAD

**Issue by jbjhjm** [nrwl/nx#1223]
__Edit/Update:__
In root tsconfig.json, I define some paths pointing exactly to index.ts files, while other paths are using a wildcard operator. First ones work fine, but path resolving with wildcard operator fails - not in angular apps, but in nodejs apps.

I was able to track down the issue a little further and suspect it now to be inside @nrwl/builders.
When the serve builder is set to @angular-devkit/build-angular:dev-server, paths are resolved correctly.
When set to @nrwl/builders:node-execute, path mapping stops working.

Example:
```json
...
"paths":{
      "@local/user/backend/*": [
        "libs/user/user-backend/src/lib/*"
      ],
      "@local/user/backend": [
        "libs/user/user-backend/src/index.ts"
      ]
}
```

## Expected Behavior

`import { Something } from '@local/user/backend';` should load Something defined/re-exported in index.ts.

`import { Stuff } from '@local/user/backend/stuff';` should import Stuff located in libs/user/user-backend/src/lib/stuff/index.ts.

`import { PreciseClassFromFile } from '@local/user/backend/stuff/precise-path.class';` should find class in libs/user/user-backend/src/lib/stuff/precise-path.class.ts.

## Current Behavior

Only the first import works.
Interestingly, VScode is able to resolve the import paths correctly.
So before further investigation I want to make sure this is how it is intended to work or if this currently is a unsupported or buggy feature.

## Failure Information (for bugs)

As soon as I'm trying to import something using a path with wildcard operator, ng serve fails stating `Module not Found: Error: Can't resolve '@local/user/backend/stuff`.

### Context
```
@angular-devkit/architect         0.13.1
@angular-devkit/build-angular     0.13.1
@angular-devkit/build-optimizer   0.13.1
@angular-devkit/build-webpack     0.13.1
@angular-devkit/core              7.3.1
@angular-devkit/schematics        7.3.7
@angular/cdk                      7.3.5
@angular/cli                      7.3.7
@ngtools/webpack                  7.3.1
@schematics/angular               7.3.7
@schematics/update                0.13.7
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
@nrwl/nx                          7.7.2
````

**Comment by jbjhjm** [comment]
I was able to track down the issue a little further. I suspect it to be inside @nrwl/builders:
The issue only occurs in nest/node apps.
When the serve builder is set to @angular-devkit/build-angular:dev-server, paths are resolved correctly.
When set to @nrwl/builders:node-execute, path mapping stops working.

**Comment by FrozenPandaz** [comment]
Thanks for the debugging! Can you please provide a repro so I can take a look easily?

**Comment by jbjhjm** [comment]
> Thanks for the debugging! Can you please provide a repro so I can take a look easily?

Hi, will do so next week!

**Comment by jbjhjm** [comment]
> Thanks for the debugging! Can you please provide a repro so I can take a look easily?

I see you are already working on a fix so I assume a repro is not required anymore. Please correct me if I'm wrong.

**Comment by udnes99** [comment]
Still seems to be an issue; we are in the process of migrating a purely TypeScript framework agnostic node backend, see #11050.
