### ISSUE TITLE
Linting errors for enforce-module-boundaries are not detected when linting via Powershell

### ISSUE THREAD

**Issue by thomas-lucas1985** [nrwl/nx#12239]
## Current Behavior
A linting violation for @nrwl/nx/enforce-module-boundaries is not detected when the linting is run via Powershell. When I perform the linting via a bash shell (WSL2 - Ubuntu), the error is detected. Vscode however is also showing the error in my Windows environment.

Other type of linting errors are detected via both ways.

## Expected Behavior
This type of linting error should also be detected when linting is executed via Powershell.

## Steps to Reproduce
Create an import violation (Projects cannot be imported by a relative or absolule path, and must begin with an nmp scope).

run nx lint <lib> via Powershell => the linting violation is not detected.
run nx lint <lib> via bash => the linting violation is detected

### Environment
   Node : 16.14.0
   OS   : win32 x64
   npm  : 8.3.1

   nx : 14.5.4
   @nrwl/angular : 14.5.4
   @nrwl/cypress : 14.5.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.4
   @nrwl/eslint-plugin-nx : 14.5.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.4
   @nrwl/js : 14.5.4
   @nrwl/linter : 14.5.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.3.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.7
   @nrwl/web : 14.5.4
   @nrwl/workspace : 14.5.4
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
         @fortawesome/angular-fontawesome: 0.11.1
         @storybook/angular: 6.5.10

![afbeelding](https://user-images.githubusercontent.com/47103076/192300910-4eb3b895-1efd-481e-8c21-43f08bb51662.png)
![afbeelding](https://user-images.githubusercontent.com/47103076/192296867-4b024d50-5d1b-4ea3-9239-6bae5a057caf.png)
![afbeelding](https://user-images.githubusercontent.com/47103076/192298807-0d26f47f-9693-4c9a-bbc4-07331fe3311d.png)

**Comment by BarWeg** [comment]
I seem to have a similar issue: 
`npx nx run-many --all --target lint`
gives different results depending on the OS it's run on.
In my case, I'm running it locally and on an Azure DevOps pipeline.
Locally on windows and on a pipeline set to use windows-latest, the command returns no errors.
However, if I switch the pipeline to use ubuntu-latest or macos-latest I start getting errors and issues.
In my case the errors are incorrect and seem to loop, fixing the "Projects should use relative imports within the same project" then causes the linter to complain that "Projects cannot be imported by a relative or absolute path". 
Additionally, the mac and ubuntu scenarios seem to ignore any eslint-disable decorators while both windows scenarios respect them corectly.
All scenarios use the same exact command and commit. The only difference is the OS.
Regardless of the content of the errors I get, all environments should produce the same output and they do not.

**Comment by meeroslav** [comment]
Hi @BarWeg and @thomas-lucas1985,

Can any of you provide minimal repo where this error can be reproduced? (minus the Azure of course)

**Comment by BarWeg** [comment]
For me repro would require the use of Azure but @thomas-lucas1985 case seems  reproducable

**Comment by meeroslav** [comment]
@BarWeg can you provide a minimal repro?
If running it on windows vs ubuntu/macos gives different results that this is something we can easily test.

Is your use case also related to Powershell/Bash? Or it happens in the plain terminal as well?

**Comment by BarWeg** [comment]
I can't really go messing around with Azure and do not have access to different OSs but in my case, we have 3 nx projects set up with references to each other. Locally on windows, I do not get the boundary errors where I have references between projects, but if I run it on a non-windows Azure agent I do. 
As for Powershell we run the linter from an Azure task with this description: "Run a command line script using Bash on Linux and macOS and cmd.exe on Windows"

**Comment by meeroslav** [comment]
Hey @BarWeg, no need to mess around with Azure. Can you create a minimal repro that fails on your Windows?

I have access to different OSs, so I can check what the root cause of it is.
