### ISSUE TITLE
@nrwl/angular: Package subpath './src/utils/test-runners' is not defined by "exports"

### ISSUE THREAD

**Issue by pauleustice** [nrwl/nx#12248]
## Current Behavior

When importing from `@nrwl/angular/src/utils/test-runners` in a workspace generator, and running the generator, I see the message:

```
Package subpath './src/utils/test-runners' is not defined by "exports" in 
/Users/pauleustice/Repos/repoName/node_modules/@nrwl/angular/package.json
```

## Expected Behavior

I wish to be able to import types from this file to ensure my generator (which creates libs under the hood using `@nrwl/angular/generators`) complies with the test runners that Nx supports via the `UnitTestRunner` enum.

This is a regression as it occurs on Nx **14.7.13** but _not_ on **14.5.8**. The error message is accurate, in that the path doesn't exist in `package.json`, but on 14.5.8 an error was not produced.

## Steps to Reproduce

1. Create a new workspace-generator

The schema can be basically empty:

```
{
  "$schema": "http://json-schema.org/schema",
  "cli": "nx",
  "$id": "new-lib",
  "type": "object",
  "additionalProperties": false
}
```

In the `index.ts` file, add the following:

```
import { UnitTestRunner } from '@nrwl/angular/src/utils/test-runners';

export default function () {
  const testRunner = UnitTestRunner.Jest;
  console.log('hello');
}
```

2. Run `nx workspace-generator new-lib` and see the error message

### Failure Logs

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './src/utils/test-runners' is not defined by "exports" in /Users/pauleustice/Repos/repoName/node_modules/@nrwl/angular/package.json
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:340:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:619:3)
    at resolveExports (node:internal/modules/cjs/loader:492:36)
    at Module._findPath (node:internal/modules/cjs/loader:532:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:941:27)
    at Module._load (node:internal/modules/cjs/loader:803:27)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/pauleustice/Repos/repoName/dist/out-tsc/tools/generators/new-lib/index.js:5:22)
```

### Environment

<img width="315" alt="Screenshot 2022-09-26 at 17 15 54" src="https://user-images.githubusercontent.com/1677737/192328500-d2ed2453-f6a7-4593-840f-f5769055d3f6.png">

**Comment by Coly010** [comment]
Hey! 

This isn't a bug. You're just using the wrong import path :)

You should import the `UnitTestRunner` type from `@nrwl/angular/generators`.

The file you're looking for is exported at this export:
https://github.com/nrwl/nx/blob/master/packages/angular/generators.ts#L30

Closing this as the types are exported from the package.

I hope this helps!
