### ISSUE TITLE
Getting exception while npm build due to react router

### ISSUE THREAD

**Issue by riyaz-rz** [nrwl/nx#12240]
Exception occuring in node modules of react-router

##Exception while npm build 
ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(149,100)
      TS1110: Type expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(149,109)
      TS1005: '}' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(149,114)
      TS1128: Declaration or statement expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(149,115)
      TS1128: Declaration or statement expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(151,18)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(151,19)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(151,26)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(151,32)
      TS1109: Expression expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(153,18)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(153,19)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(153,26)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(159,18)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(159,19)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(159,26)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(159,33)
      TS1128: Declaration or statement expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(159,35)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(159,42)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(159,67)
      TS1161: Unterminated regular expression literal.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(160,31)
      TS1005: ':' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(160,48)
      TS1005: '}' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(160,53)
      TS1128: Declaration or statement expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(160,56)
      TS1005: ')' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(160,63)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(160,71)
      TS1128: Declaration or statement expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(163,18)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(163,19)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(163,26)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(163,33)
      TS1128: Declaration or statement expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(163,35)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(163,42)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(164,40)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(164,41)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(164,48)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(164,56)
      TS1005: ')' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(164,63)
      TS1005: ';' expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(164,71)
      TS1128: Declaration or statement expected.

ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts
[tsl] ERROR in C:\PolicyService-CC\policy-engine-ui\node_modules\@types\react-router\index.d.ts(199,1)
      TS1160: Unterminated template literal.
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = ./index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./public/index.html 689 bytes {0} [built]
    [2] (webpack)/buildin/global.js 472 bytes {0} [built]
    [3] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/sass-loader/dist/cjs.js!src/styles/scss/policy-engine.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader!./node_modules/sass-loader/dist/cjs.js!./src/styles/scss/policy-engine.scss 379 bytes {0} [built]
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/sass-loader/dist/cjs.js!src/styles/scss/popover.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader!./node_modules/sass-loader/dist/cjs.js!./src/styles/scss/popover.scss 639 bytes {0} [built]
        + 1 hidden module

**### ENVIRONMENT DETAILS**
##package.json
  "engines": {
    "npm": ">=8.5.0",
    "node": ">=16.14.2"
  },
 "dependencies": {
    "@types/react-router-dom": "^5.3.3",
    "auth-header": "1.0.0",
    "aws-sdk": "^2.964.0",
    "axios": "^0.20.0",
    "bootstrap": "^4.4.1",
    "express-http-proxy": "^1.6.2",
    "express-static-gzip": "^2.0.6",
    "font-awesome": "^4.7.0",
    "formik": "^2.1.4",
    "formiojs": "5.0.0-m.1",
    "prom-client": "^10.2.2",
    "prop-types": "^15.7.2",
    "puppeteer": "15.3.2",
    "query-string": "^6.10.1",
    "react": "16.13.1",
    "react-bootstrap": "^1.0.0-beta.16",
    "react-dnd": "^5.0.0",
    "react-dnd-html5-backend": "^3.0.2",
    "react-dom": "16.13.1",
    "react-formio": "5.0.0-m.2",
    "react-router-dom": "^5.3.3",
    "sequelize": "6.11.0",
    "string-hash": "^1.1.3",
    "uuid": "^8.1.0",
    "uuid-validate": "0.0.3"
  },
 "devDependencies": {
    "@babel/cli": "^7.0.0",
    "@babel/core": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-transform-modules-umd": "^7.0.0",
    "@babel/plugin-transform-react-jsx": "^7.0.0",
    "@babel/polyfill": "^7.0.0",
    "@babel/preset-env": "^7.9.6",
    "@babel/preset-react": "^7.9.4",
    "@commitlint/cli": "^9.1.1",
    "@commitlint/config-conventional": "^9.1.1",
    "@types/enzyme": "^3.10.5",
    "@types/enzyme-adapter-react-16": "^1.0.6",
    "@types/fetch-mock": "^7.3.1",
    "@types/jest": "24.0.18",
    "@types/node": "12.7.3",
    "@types/react": "^16.9.14",
    "@types/react-dom": "^16.9.14",
    "@types/react-redux": "^5.0.21",
    "@types/redux-form": "^7.5.5",
    "@types/uuid": "^8.0.0",
    "@types/webpack-env": "^1.15.2",
    "assets-webpack-plugin": "3.9.10",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "10.0.1",
    "babel-jest": "^23.4.2",
    "babel-loader": "^8.1.0",
    "babel-plugin-add-module-exports": "1.0.0",
    "babel-plugin-import": "1.13.0",
    "babel-plugin-module-resolver": "3.1.1",
    "babel-plugin-transform-imports": "2.0.0",
    "base-href-webpack-plugin": "^2.0.0",
    "brotli-webpack-plugin": "1.1.0",
    "classnames": "2.2.6",
    "clean-webpack-plugin": "3.0.0",
    "commitizen": "^4.1.2",
    "compression-webpack-plugin": "3.1.0",
    "concurrently": "4.1.0",
    "connect-history-api-fallback": "1.6.0",
    "convict": "4.3.1",
    "cookie-parser": "1.4.3",
    "copy-webpack-plugin": "5.1.1",
    "cross-env": "^7.0.2",
    "css-loader": "0.28.11",
    "date-fns": "^2.14.0",
    "dotenv-webpack": "1.7.0",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "enzyme-redux": "0.2.1",
    "enzyme-to-json": "^3.4.4",
    "eslint": "4.12.1",
    "eslint-loader": "2.1.1",
    "eslint-plugin-jest": "20.0.0",
    "eslint-plugin-react": "7.7.0",
    "express": "4.16.4",
    "file-loader": "2.0.0",
    "handlebars": "^4.7.6",
    "html-webpack-plugin": "3.2.0",
    "husky": "^4.2.5",
    "identity-obj-proxy": "3.0.0",
    "jest": "^26.0.1",
    "jest-fetch-mock": "^3.0.3",
    "less": "2.7.3",
    "less-loader": "4.1.0",
    "lint-staged": "^7.3.0",
    "mini-css-extract-plugin": "0.9.0",
    "nock": "10.0.3",
    "nodemon": "1.18.9",
    "npm-run-all": "4.1.5",
    "optimize-css-assets-webpack-plugin": "5.0.3",
    "react-redux": "5.0.7",
    "react-router": "4.3.1",
    "react-select": "2.2.0",
    "redux": "3.7.2",
    "redux-devtools-extension": "2.13.8",
    "redux-logger": "3.0.6",
    "redux-mock-store": "1.5.3",
    "redux-saga": "0.16.0",
    "reselect": "3.0.1",
    "sass": "^1.51.0",
    "sass-loader": "10.2.0",
    "sinon": "7.1.1",
    "style-loader": "0.19.1",
    "terser-webpack-plugin": "^3.0.3",
    "ts-jest": "^26.0.0",
    "ts-loader": "^7.0.5",
    "typescript": "^3.9.10",
    "url-loader": "0.5.9",
    "validate.js": "0.12.0",
    "validator": "10.11.0",
    "webpack": "4.46.0",
    "webpack-bundle-analyzer": "3.6.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-middleware": "3.4.0",
    "webpack-dev-server": "^3.11.0",
    "webpack-hot-middleware": "2.24.3",
    "webpack-md5-hash": "0.0.6",
    "webpack-merge": "4.2.2",
    "webpack-node-externals": "1.7.2"
  },

**Comment by ndcunningham** [comment]
Can you provide a minimal example or repo of this occurring?
