### ISSUE TITLE
Cypress Angular Component Test

### ISSUE THREAD

**Issue by basti-n** [nrwl/nx#12249]
## Current Behavior
`stylePreprocessorOptions` in `project.json` are not considered when running cypress component tests in an angular nx workspace.
Hence, the imported / used styles in `.scss`-files are not being resolved correctly, resulting in a failed module build.

```
        "stylePreprocessorOptions": {
          "includePaths": ["libs/shared/ui/src/lib/styles"] // aka the path where my scss files reside
        },
```

I would expect the path to `styleguide` being resolved correctly.

```
Module build failed (from ../../node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
2 │ @use 'styleguide' as *;
  │ ^^^^^^^^^^^^^^^^^^^^^^
```

Note: If this is simply a case of missing docs, I would be more than happy to contribute to the project by adding a section to the docs on how to correctly configure /  handle includedPaths for stylePreprocessorOptions.

## Expected Behavior

The component tests are started and the style (scss) paths are being resolved correctly.

## Steps to Reproduce

I am running Cypress v10.8.0 , I created a minimal repro project (https://github.com/basti-n/cypress-component-test)
Run `npm run test-cmp` to run the component tests.

### Failure Logs

```
Module build failed (from ../../node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
2 │ @use 'styleguide' as *;
  │ ^^^^^^^^^^^^^^^^^^^^^^
```

### Environment

```
 >  NX   Report complete - copy this into the issue template

   Node : 18.7.0
   OS   : darwin x64
   npm  : 8.15.0

   nx : 14.7.13
   @nrwl/angular : 14.7.13
   @nrwl/cypress : 14.7.13
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.13
   @nrwl/eslint-plugin-nx : 14.7.13
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.13
   @nrwl/js : 14.7.13
   @nrwl/linter : 14.7.13
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.6.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.13
   @nrwl/web : Not Found
   @nrwl/workspace : 14.7.13
   typescript : 4.8.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by barbados-clemens** [comment]
Looks like I missed this issue, but this should have been fixed already in the lasted nx.
