### ISSUE TITLE
Switch from TSLint to ESLint

### ISSUE THREAD

**Issue by AdamVig** [nrwl/nx#1224]
The post "[TSLint in 2019](https://medium.com/palantir/tslint-in-2019-1a144c2317a9)" announced that TSLint will be deprecated once it reaches feature parity with ESLint.

Will Nx be changed to support ESLint instead of TSLint, or perhaps both?

**Comment by vsavkin** [comment]
We added support for ESLint for all non-Angular projects. Once the Angular team adds support for ESLint, we are going to integrate it as well.
