### ISSUE TITLE
DTE not recording to stderr when running commands in parallel (Azure Pipelines)

### ISSUE THREAD

**Issue by mmruesch12** [nrwl/nx#12243]
## Current Behavior
I recently modified my team's implementation of DTE to run the affected commands in parallel. 

I went from running each set of tasks separately like this:
```
- script: npx nx affected --base=$(BASE_SHA) --head=$(HEAD_SHA) --target=lint --parallel=3
- script: npx nx affected --base=$(BASE_SHA) --head=$(HEAD_SHA) --target=build --parallel=3
- script: npx nx affected --base=$(BASE_SHA) --head=$(HEAD_SHA) --target=test --reporters=default --reporters=jest-junit --parallel=1 --maxWorkers=2 --ci --code-coverage`
```

To now running them in parallel, as the official documentation now shows.
```
- script: |
      npx nx affected --base=$(BASE_SHA) --head=$(HEAD_SHA) --target=lint --parallel=3 &
      npx nx affected --base=$(BASE_SHA) --head=$(HEAD_SHA) --target=build --parallel=3 &
      npx nx affected --base=$(BASE_SHA) --head=$(HEAD_SHA) --target=test --reporters=default --reporters=jest-junit --parallel=1 --maxWorkers=2 --ci --code-coverage
```

The former worked fine but was slower, since they weren't running in parallel.
But with the latter, I realized that broken builds were slipping through our quality gates. Essentially, only the last command in the script (--target=test), will write to stderr if any tests are broken. But if either of the other commands failed, it will not fail the pipeline task.

All errors across the commands show up in the Nx Cloud logs but only the final command will write to stderr.

## Expected Behavior
All affected targets should emit an error within Azure Pipelines.

## Steps to Reproduce
* Set up DTE in Azure Pipelines using this documentation:
https://nx.dev/recipe/monorepo-ci-azure#distributed-ci-with-nx-cloud

* Instead of running each set of affected tasks individually, run them as a single script in parallel.
  i.e. `npx nx affected -target=test & npx nx affected --target=build & npx nx affected --target=lint`

**Comment by AgentEnder** [comment]
A single ampersand tells the terminwl to run the preceding command in the background. As it is running in the background,  it has no way to print outputs properly. I recommend looking at something like `concurrently` to handle this.

It would look something like: `npx concurrently "nx affected:build" "nx affected:test"

**Comment by joh-klein** [comment]
It would be really great, if you would put this info in the docs! This took me quite a while to find the solution.
