### ISSUE TITLE
Allow switchMap for Data Persistence 

### ISSUE THREAD

**Issue by mohyeid** [nrwl/nx#1225]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version No
- [x] I checked the documentation and found no answer Yes
- [x] I checked to make sure that this issue has not already been filed Yes
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency) Yes

## Expected Behavior
When using the NX DataPersistence, it would be great if we can use switch map. The run function forces to use mergeMap. 

Please describe the behavior you are expecting

Example using pure NgRx: 

```

  @Effect()
  testActions$ = this.actions$.pipe(
    ofType('Test_Search'),
    switchMap(action => {
      return this.backendService.get(''/search').pipe(
        map(data => {
          return [{ type: 'SomethingLoaded', payload: data }];
        })
      );
    })
  );

```

## Current Behavior

What is the current behavior?
You can not do that from DataPersistence run operation. It would be great if this got supported by all functions like fetch, navigation, etc... 

Please provide any relevant information about your setup:

- version of Nx used 7.1.1
- version of Angular CLI used 7.1.3

**Comment by mohyeid** [comment]
This is already implemented if I provided the id function. Its working as expected.

**Comment by jarekzolnowski** [comment]
How about optimistic and pesimistic updates? Id function is provided only within fetch ? If somebody will click 10 times 'Add user' button very fast, how to get single request only?
