### ISSUE TITLE
[Feature Request] Support new @angular/cli v8 builder architecture

### ISSUE THREAD

**Issue by Domratchev** [nrwl/nx#1226]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Nx builders to work with Angular CLI v8

## Current Behavior

Nx builders are incompatible with @angular-devkit/architect@0.800.0.beta-11

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install latest Angular CLI beta.
2. Run `ng test`
3. Observe `Could not find the implementation for builder @nrwl/builders:jest` error

### Context

Please provide any relevant information about your setup:

- version of Nx = 7.7.2
- version of Angular CLI used = 8.0.0-beta.11
- version of Angular DevKit used = 0.800.0-beta.11

## Other

A brute-force approach of changing builders.json to include "implementation": "./jest/jest.builder" property does not work. It results in another error: `Builder is not a builder`.
The builders are completely redone in the new Angular CLI architecture.

Here is the documentation for new Architect API:
https://docs.google.com/document/d/1SpN_2XEooI9_CPjqspAcNEBjVY874OWPZqOenjuF0qo/view

**Comment by Domratchev** [comment]
https://github.com/angular/angular-cli/pull/13994

**Comment by FrozenPandaz** [comment]
I've begun working on converting the builders over to the new API (aka, I have Cypress done). For now, hold off on upgrading to `@angular/cli@8.0.0`.

**Comment by GrandSchtroumpf** [comment]
I just upgraded my nwrl repo, and I still have the problem : 
- `ng update @angular/core @angular/cli`
- `ng test` -> `Could not find the implementation for builder @nrwl/builders:jest`.
Should I downgrade until this is fixed, or can it be updated later on ?

**Comment by Domratchev** [comment]
@GrandSchtroumpf Nrwl package structure is different now. You need to use @nrwl/jest:jest there.
Here are the details: https://github.com/nrwl/nx/blob/master/docs/guides/nx7-to-nx8.md

**Comment by GrandSchtroumpf** [comment]
Oh ok great, thx.

**Comment by sajidali** [comment]
@Domratchev reading the guide nx7-to-nx8 helped me solve all the issues I was having. Thank you.

**Comment by vsavkin** [comment]
Closing this as we migrated all existing builders to the new API.

**Comment by killface** [comment]
For anyone upset that the above link doesn't work, it's now here: https://nx.dev/angular/guides/nx7-to-nx8
