### ISSUE TITLE
exist output match seems not match by hash instead by file directory structure

### ISSUE THREAD

**Issue by niudai** [nrwl/nx#12277]
I use nx to build packages, which has output dir in every project directories, and I checkout to another branch, rerun the build command again, I see "existing outputs match the cache, left as is", but the source file has been changed, also the output cache.

And I test it, even if I modify the output manually, NX still does not notice the output has been modified, so the output cache has not been re-copied

**Comment by vsavkin** [comment]
Thank you for submitting the issue. Could you run "npx nx report" and paste the results here?

**Comment by richard-ling** [comment]
Output of nx report

      $ npx nx report
      
       >  NX   Report complete - copy this into the issue template
      
         Node : 16.14.0
         OS   : darwin x64
         yarn : 1.22.19
         
         nx : 14.6.5
         @nrwl/angular : Not Found
         @nrwl/cypress : 14.6.5
         @nrwl/detox : Not Found
         @nrwl/devkit : 14.6.5
         @nrwl/eslint-plugin-nx : Not Found
         @nrwl/express : Not Found
         @nrwl/jest : 14.6.5
         @nrwl/js : 14.6.5
         @nrwl/linter : 14.6.5
         @nrwl/nest : Not Found
         @nrwl/next : Not Found
         @nrwl/node : Not Found
         @nrwl/nx-cloud : 14.6.1
         @nrwl/nx-plugin : Not Found
         @nrwl/react : Not Found
         @nrwl/react-native : Not Found
         @nrwl/schematics : Not Found
         @nrwl/storybook : Not Found
         @nrwl/web : 14.6.5
         @nrwl/workspace : 14.6.5
         typescript : 4.3.5
         ---------------------------------------
         Local workspace plugins:
         ---------------------------------------
         Community plugins:
      
      (node:87257) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /path/to/my/repo/node_modules/tslib/package.json.
      Update this package.json to use a subpath pattern like "./*".
      (Use `node --trace-deprecation ...` to show where the warning was created)
      $
