### ISSUE TITLE
Source maps cannot be disabled when running node dev server

### ISSUE THREAD

**Issue by BuckyMaler** [nrwl/nx#1228]
## Expected Behavior

`--source-map` is a recognized option and can be disabled when running `ng serve <project>` for node apps.

## Current Behavior

Source maps cannot be disabled when running `ng serve <project>` for node apps.

### Steps to Reproduce

1. `yarn create nx-workspace myworkspace`
2. `cd myworkspace`
3. `ng g node-app backend`
4. `ng serve backend --source-map false`

### Context

- version `7.7.2` of Nx

### Failure Logs

<img width="1277" alt="55282763-49442000-5319-11e9-8a2a-9fc273b6d4b7" src="https://user-images.githubusercontent.com/14145352/55602460-5f901880-572b-11e9-8314-a2011dbc7e3e.png">

**Comment by vsavkin** [comment]
I merged your PR. Thank you for your contribution.

**Comment by BuckyMaler** [comment]
@vsavkin this issue is unresolved. I referenced two new issues in [#1204](https://github.com/nrwl/nx/pull/1204#issuecomment-480142037) and was able to get around to submitting a PR for one, but not this one.
