### ISSUE TITLE
react-native: Images within libraries do not show correctly on Android

### ISSUE THREAD

**Issue by rmevans9** [nrwl/nx#12287]
## Current Behavior
When you have an image within a library when run on Android it does not show the image. iOS works fine.

## Expected Behavior
The image should show on both Android and iOS

## Steps to Reproduce
Pull https://github.com/rmevans9/nx-android-image-issue
Execute `yarn nx run-android without-fix` and note the resulting app launch does not contain the image
Execute `yarn nx run-android with-fix` and note the resulting app launch does contain the image.

They are two different applications however the source files are exactly the same.

The only difference between the two applications is that I applied a fix specifically for issues with `react-native` in monorepos:
https://github.com/rmevans9/nx-android-image-issue/commit/bca687f7a7901ae832ddad42c047c7ade6a82a35

This fix allows Metro to work right within a monorepo. I suggest this become something that is handled via the `@nrwl/react-native` `withNxMetro` code until such a time `react-native` supports it out of the box.

### Failure Logs
N/A

### Environment
This is using the latest NX (as of this morning)

**Comment by rishabhmhjn** [comment]
@rmevans9 I have been looking for a similar fix for a long time, and I am glad that it finally worked with this fix.

However, I was wondering if it is possible at all to fetch images (or similar assets) from a common asset library (/libs/assets/src/assets/**.png) via a custom path (such as `const Logo = require('@android-issue/assets/logo.png');`

Do you have any suggestions on how to achieve this, or is it just not possible?

**Comment by mtzfactory** [comment]
I'm having the same problem but can't make it work with @rmevans9 solution... :-(

This is the error I'm getting:

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
   > Android resource compilation failed
     ERROR:/Users/mtz/work/development/apps/trades-app/apps/demo-ui/android/app/build/generated/res/react/release/drawable-mdpi/dir_dir_dir_dir___libs_tradesui_src_core_photothumbnail_test_photo_1.png: AAPT: error: file failed to compile.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================
```

**Comment by mtzfactory** [comment]
My colleague @iledzka found out what was the problem: for some reason the PNG file wasn't well formatted, even you could open it and watch it as any other image file...

The solution was simple: just replace it with a new file.

Other solution was to [disable the PNG optimisation done by Android](https://developer.android.com/studio/build/optimize-your-build#disable_crunching)...

**Comment by lanceturbes** [comment]
@rmevans9 Thank you _very_ very much for this fix; been without images for so long, now, that finally seeing them was a nice surprise. :-)

**Comment by xiongemi** [comment]
closing this issue because it is not related to nx.
