### ISSUE TITLE
Disabling source maps still generates source maps

### ISSUE THREAD

**Issue by BuckyMaler** [nrwl/nx#1229]
## Expected Behavior

When running `ng build <project> --source-map false` for node apps I expect no source maps to be generated.

## Current Behavior

When running `ng build <project> --source-map false` for node apps source maps are generated inline in `main.js`.

### Steps to Reproduce

1. `yarn create nx-workspace myworkspace`
2. `cd myworkspace`
3. `ng g node-app backend`
4. `ng build backend --source-map false`

### Context

- version `7.7.2` of Nx

### Failure Logs

Below you'll see the second build didn't generate an external source map, but `main.js` bundle size is larger and that's because of inline source maps.

<img width="1275" alt="55282775-7395dd80-5319-11e9-87ad-8cd6b58c1414" src="https://user-images.githubusercontent.com/14145352/55602850-2ce71f80-572d-11e9-9b3b-11814decbc29.png">

**Comment by vsavkin** [comment]
@BuckyMaler merged you PR. thank you for your contribution!
