### ISSUE TITLE
Suggestion: avoid single letter variable names

### ISSUE THREAD

**Issue by jaufgang** [nrwl/nx#123]
I was surprised to see single letter variable names (`a` and `d`) in my  ngrx effects.ts file generated by nx.  Use of single letter variable names is generally considered bad practice. I would suggest that these be renamed `action` and `dataPersistence`.

**Comment by vsavkin** [comment]
@jaufgang Would you like to submit a PR fixing it?

**Comment by jaufgang** [comment]
I'm generally reluctant to submit PRs to repos when I don't have the time to properly familiarize myself with the codebase and make sure I'm doing it right, but this one seems pretty straightforward.  Is this all there is to it?
