### ISSUE TITLE
tsconfig.spec.json could include Jest __mocks__ directories

### ISSUE THREAD

**Issue by ajwootto** [nrwl/nx#12301]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

In the generators' outputs for tsconfig.spec.json, currently only files ending with `.spec.ts` and similar are considered as "test" files with access to jest types.

I think it would be useful to also include any files that are inside `__mocks__` directories which represent mock definitions for Jest to use automatically. 

## Motivation

It is very often the case that mock definitions require the use of the `jest` global object for things like defining a `jest.fn()` and setting up mock behaviour. Given that `jest` global is accessible in `__mocks__` files, and those should never be included in the real program, I think it makes sense to ensure that these files are only included in the `spec` Typescript and not the main program.

## Suggested Implementation

I think the only necessary change would be to the generators to specify this in the tsconfig.*.json files.

**Comment by barbados-clemens** [comment]
Hi @ajwootto, thanks for the feature request.

I just tried out using a mocks folder and didn't get any typing errors or issues running build/test. 

Do you have a repo I can try using to see the specific errors and test with?
