### ISSUE TITLE
feat(ngrx): support createAction

### ISSUE THREAD

**Issue by hadrien-toma** [nrwl/nx#1231]
In the latest version of NgRx (`7.4.0`), `createAction` seems to become a standard way to create actions (example [here](https://github.com/ngrx/platform/blob/master/projects/example-app/src/app/books/actions/book.actions.ts)), so it would be awesome if Nx could support this version update :heart: :relaxed:.

**Comment by vsavkin** [comment]
@hadrien-toma Yup. We should update it. It would be great if you could submit a PR making the change?

**Comment by hadrien-toma** [comment]
@vsavkin Not sure I am experienced enough to but I will try in the next couple of weeks 🤞.

**Comment by hadrien-toma** [comment]
Hey @vsavkin and @FrozenPandaz I come back to this issue now that the NgRx v8 is nearly released. Is the update into the Nx repo affected to someone? I think I can now handle it if you give me some pointers.

**Comment by hadrien-toma** [comment]
@vsavkin @FrozenPandaz may we close this issue? According to https://github.com/nrwl/nx/commit/6516176 Nx 8.3.0 seems to be compliant with NgRx 8 😍.
