### ISSUE TITLE
Custom workspace eslint rules somehow not found on precommit from WebStorm

### ISSUE THREAD

**Issue by pumano** [nrwl/nx#12314]
## Current Behavior

Custom eslint workpace rules not found in WebStorm. Problem only when pre-commit hook launch lint-staged with `nx affected:lint` with custom workspace eslint rules and problem only in WebStorm.
![2022-09-29 14 15 40](https://user-images.githubusercontent.com/17675259/193017672-709ffb62-f526-4f9b-b4c5-655f16931bd4.jpg)

![2022-09-29 14 21 19](https://user-images.githubusercontent.com/17675259/193018653-44716971-7afd-4dd6-aa53-874c4d9b7d5a.jpg)

## Expected Behavior
Should works properly and found eslint custom workspace rules

## Steps to Reproduce

I have example project with another rule where I use custom eslint rules: https://github.com/pumano/nx-eslint-workspace-rule-destroy-service

### Failure Logs

`Definition for rule '@nrwl/nx/workspace/no-destroy-without-provider' was not found`

**Comment by meeroslav** [comment]
Hi @pumano,

I'm confused. What is `@nrwl/nx/workspace/no-destroy-without-provider` and where is it coming from?
Nx has only one custom rule - enforce module boundaries. The name of this rule suggests it's published by `@nrwl` but we also don't have the package `@nrwl/nx` anymore.

**Comment by meeroslav** [comment]
That issue should likely be present in all IDEs and terminal, since the rule does not exist.

**Comment by pumano** [comment]
@meeroslav it's custom eslint rule its possible to create that. I use video from youtube nx channel about it and create

**Comment by meeroslav** [comment]
Unfortunately, I tried this in the latest Webstorm and the linter was reported correctly.

This is my husky `pre-commit` config:
```
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged -c lint-staged.config.js
```

and `lint-staged.config.js`:
```
module.exports = {
  '{apps,libs}/**/*.{ts,json,md,scss}': () => {
    return [
      "npx nx affected:lint  -- --uncommitted --fix --parallel"
    ]
  }
}
```

This is the error report as expected:
```
✔ Preparing lint-staged...
❯ Running tasks for staged files...
  ❯ lint-staged.config.js — 5 files
    ❯ {apps,libs}/**/*.{ts,json,md,scss} — 1 file
      ✖ npx nx affected:lint  -- --uncommitted --fix --parallel [FAILED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ npx nx affected:lint  -- --uncommitted --fix --parallel:

 >  NX   Affected criteria defaulted to --base=main --head=HEAD


 >  NX   Running target lint for 4 project(s):

    - some-library
    - customer-portal-e2e
    - customer-portal
    - utils
   
   With additional flags:
     --uncommitted=true
     --fix=true
     --parallel=true

 

> nx run customer-portal:lint --uncommitted --fix --parallel  [existing outputs match the cache, left as is]


Linting "customer-portal"...

All files pass linting.


> nx run customer-portal-e2e:lint --uncommitted --fix --parallel  [existing outputs match the cache, left as is]


Linting "customer-portal-e2e"...

All files pass linting.


> nx run utils:lint --uncommitted --fix --parallel  [existing outputs match the cache, left as is]


Linting "utils"...

All files pass linting.


> nx run some-library:lint --uncommitted --fix --parallel


Linting "some-library"...

/Users/miro/Dev/Playground/nx-eslint-workspace-rule-destroy-service/libs/some-library/src/lib/some-library.component.ts
   1:46  warning  'OnInit' is defined but never used                                                                                            @typescript-eslint/no-unused-vars
  12:18  error    The component / directive / etc providers section should contain DestroyService, when DestroyService injected in constructor  @nrwl/nx/workspace/no-destroy-without-provider

✖ 2 problems (1 error, 1 warning)

Lint warnings found in the listed files.

Lint errors found in the listed files.


 

 >  NX   Running target "lint" failed

   Failed tasks:
   
   - some-library:lint

husky - pre-commit hook exited with code 1 (error)
```

Perhaps your installation of Webstorm is corrupted? Can you try using the latest version?
I used `husky@^8.0.0` and `lint-staged@^13.0.3`
