### ISSUE TITLE
Environment to disable NxCloud

### ISSUE THREAD

**Issue by jonhamm** [nrwl/nx#12319]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Working with Nx Private Cloud you can have situations where there are problems with the Nx Private Cloud
In these situations build times increase manyfold as all cacheable requests will wait 10s before timing out requests to Nx Cloud
If the functionality of the --no-cloud CLI option could be achieved through an environment variable - e.g. NX_NO_CLOUD - then this problem could be alleviated while solving the problem in Nx Cloud by setting this environment variable in the CI/CD and/or locally at a developer.

Likewise it could be useful to have NX_SKIP_NX_CACHE to skip both local and global cache like the --skip-nx-cache CLI option.

## Motivation
It can be used to make quick temporary fix for annoying problem.

## Suggested Implementation

if NX_NO_CLOUD environment variable is set all nx commands should be invoked as if --no-cloud was present on the command line.

While implementing this it could be a good idea to introduce NX_SKIP_NX_CACHE to cause all nx commands to be invoked as if --skip-nx-cache was present on the command line

**Comment by StalkAltan** [comment]
`--skip-nx-cache` now prevents the task runner from connecting to Nx Cloud at all, as of @nrwl/nx-cloud@15.2.0.

Sorry for the delay.

**Comment by StalkAltan** [comment]
Apologies, interpreted the initial ask incorrectly. We should be able to address this in the coming week. Will update the issue again on release.

**Comment by StalkAltan** [comment]
This has been released in Nx Cloud 16.0.2 with the env variable `NX_NO_CLOUD=true`.
