### ISSUE TITLE
Angular host app fails to build with localize and extractLicenses options

### ISSUE THREAD

**Issue by minijus** [nrwl/nx#12317]
## Current Behavior
Building Angular host app with `localize` and `extractLicenses` fails on `license-webpack-plugin`:
![image](https://user-images.githubusercontent.com/3633549/193073404-6ff4e09c-8b21-4baf-9a5e-78acbc74c5fa.png)

## Expected Behavior
It should be possible to build localized Angular host apps with `--extractLicenses=true`.

## Steps to Reproduce
Repository with reproduction: https://github.com/minijus/mf-localize-demo
```bash
npx nx run mf-host:build --extractLicenses=true --verbose
```

### Environment
```

 >  NX   Report complete - copy this into the issue template

   Node : 16.17.0
   OS   : darwin arm64
   npm  : 8.19.2
   
   nx : 14.8.1
   @nrwl/angular : 14.8.1
   @nrwl/cypress : 14.8.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.1
   @nrwl/eslint-plugin-nx : 14.8.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.1
   @nrwl/js : 14.8.1
   @nrwl/linter : 14.8.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.1
   @nrwl/web : Not Found
   @nrwl/workspace : 14.8.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by Coly010** [comment]
After investigating this, the issue comes from `LicenseWebpackPlugin` and Angular Devkit abstracting away the actual setup of this plugin. We need to set the `moduleDirectories` option of `LicenseWebpackPlugin`.

This can still be achieved by keeping the `extractLicenses` to false, and manually setting up this plugin in your `webpack.prod.config.js`.

If you edit that file to replicate this:

```js
const { withModuleFederation } = require('@nrwl/angular/module-federation');
const config = require('./module-federation.config');
const LicenseWebpackPlugin =
  require('license-webpack-plugin').LicenseWebpackPlugin;
const path = require('path');

module.exports = async (wco) => {
  const wmf = await withModuleFederation(config);
  return wmf({
    ...wco,
    plugins: [
      ...(wco.plugins ?? []),
      new LicenseWebpackPlugin({
        stats: {
          warnings: false,
          errors: false,
        },
        perChunkOutput: false,
        outputFilename: '3rdpartylicenses.txt',
        skipChildCompilers: true,
        modulesDirectories: [path.resolve(__dirname, '../../node_modules')],
      }),
    ],
  });
};

```

You should be good to go!

As this isn't an Nx-level issue, I'm going to close this issue in favour of the workaround listed above.

**Comment by nayfin** [comment]
@Coly010 I understand that this isn't an Nx issue, but we are facing this as well when localizing our modularly federated angular app. We still see this even with `--extractLicenses=false`, and after applying your workaround. Are there any other things that you came across in your research that could cause this? I can't share the code in question, but if it helps I can try modify some code that I can share to repro the issue. Thank you and the rest of the Nx team for your great products and support!

**Comment by Coly010** [comment]
@nayfin If you could modify some code and share a repo that would be the best way for me to figure out what might be going wrong for you :)

**Comment by nayfin** [comment]
Apologies. I mis-implemented the fix. We're all good. Thanks again for providing support for a non-Nx issue!
