### ISSUE TITLE
nx-enforce-module-boundaries breaks on namespace imports

### ISSUE THREAD

**Issue by Roozenboom** [nrwl/nx#12316]
## Current Behavior

The nx-enforce-module-boundaries eslint rule breaks completely when you use a namespace import (* as foo) in your code. Because the compilation breaks it is not possible to see the violation in your IDE (vscode) or see any other possible violations in your code when you execute linting for the project. It is also not possible to suppress the violation with a `// eslint-disable-next-line @nrwl/nx/enforce-module-boundaries` comment.

```
Linting "products-home-page"...

 >  NX   Cannot read properties of undefined (reading 'name')

   Occurred while linting ~/nx-examples/libs/products/home-page/src/lib/home-page/home-page.component.ts:6
   Rule: "@nrwl/nx/enforce-module-boundaries"
   Pass --verbose to see the stacktrace.
   ```

![Screenshot 2022-09-29 at 16 09 14](https://user-images.githubusercontent.com/4587734/193058701-57d328c4-b3b7-4e41-8cb4-820d2f6754c0.png)

## Expected Behavior

I expect the rule to not break eslint and show a eslint violation message like it does when we use named imports.
![Screenshot 2022-09-29 at 16 10 09](https://user-images.githubusercontent.com/4587734/193058733-ac4400ae-ee72-4165-a5f8-a4dda9ce4e4c.png)

## Steps to Reproduce

I created a simple example of the issue in nx-examples: https://github.com/nrwl/nx-examples/pull/232

### Failure Logs

For logs see the screenshots above those include the output of the lint task and vscode inline output

### Environment

Node : 16.17.0
OS   : darwin arm64
yarn : 1.22.19
  
nx : 14.6.3
@nrwl/angular : 14.6.3
@nrwl/cypress : 14.6.3
@nrwl/detox : Not Found
@nrwl/devkit : 14.6.3
@nrwl/eslint-plugin-nx : 14.6.3
@nrwl/express : Not Found
@nrwl/jest : 14.6.3
@nrwl/js : 14.6.3
@nrwl/linter : 14.6.3
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/nx-cloud : 14.6.1
@nrwl/nx-plugin : Not Found
@nrwl/react : 14.6.3
@nrwl/react-native : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : 14.6.3
@nrwl/web : 14.6.3
@nrwl/workspace : 14.6.3
typescript : 4.7.2

Community plugins:
@ngrx/component-store: 14.0.2
@ngrx/effects: 14.0.2
@ngrx/entity: 14.0.2
@ngrx/router-store: 14.0.2
@ngrx/store: 14.0.2
@ngrx/store-devtools: 14.0.2

**Comment by pumano** [comment]
Nice catch! Hope will be fixed soon!

**Comment by meeroslav** [comment]
Thank you for reporting the bug and providing the reproduction. I will address this right away.
