### ISSUE TITLE
Inconsistency with CSS in dev and build NextJS

### ISSUE THREAD

**Issue by saubhagya23** [nrwl/nx#12311]
## Current Behavior
We're generating our next project with the nx command. After deploying the application we saw inconsistencies in styling. The issue was that the css written for specific component was getting overridden by global css.

We wanted to replicate this issue on localhost so made some changes to serve command (i.e. made dev to false) project.json file:

```
{
  "root": "apps/ui",
  "sourceRoot": "apps/ui",
  "projectType": "application",
  "targets": {
    "buildImage" : {
      "builder": "@nrwl/workspace:run-commands",
      "options": {
        "commands": [
          "nx build ui",
          "docker build -f ./apps/ui/Dockerfile . -t ui"
        ],
        "parallel": false
      }
    },
    "build": {
      "executor": "@nrwl/next:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "root": "apps/ui",
        "outputPath": "dist/apps/ui"
      },
      "configurations": {
        "production": {}
      }
    },
    "serve": {
      "executor": "@nrwl/next:server",
      "options": {
        "buildTarget": "ui:build",
        "dev": false
      },
      "configurations": {
        "production": {
          "buildTarget": "ui:build:production",
          "dev": false
        }
      }
    },
    "export": {
      "executor": "@nrwl/next:export",
      "options": {
        "buildTarget": "ui:build:production"
      }
    },
    "test": {
      "executor": "@nrwl/jest:jest",
      "outputs": ["coverage/apps/ui"],
      "options": {
        "jestConfig": "apps/ui/jest.config.js",
        "passWithNoTests": true
      }
    },
    "lint": {
      "executor": "@nrwl/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["apps/ui/**/*.{ts,tsx,js,jsx}"]
      }
    }
  },
  "tags": []
}

```

After this change when we executed the `nx serve ui` command it gives me the following error:

```
> nx run ui:serve

info  - Loaded env from apps\ui\.env.local
info  - Loaded env from apps\ui\.env
Could not start production server. Try building your app with `nx build ui`.

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "ui:serve" failed

   Failed tasks:

   - ui:serve

   Hint: run the command with --verbose for more details.
```
PS: Also tried `nx serve ui --configuration=production` and faced the same issue.
After that if we create a build and then try to serve the application, we don't get the error. But we are not able to replicate the issue on localhost and since `dev: false` , the application does not reload if we make any changes.

## Expected Behavior
Firstly, the styling should work as expected in both dev and build.

Secondly, There should be a way to replicate the issue on localhost. (Possibly config changes that allows us to do the same.)

## Steps to Reproduce
Can't publicly share the repo as it is a company project.
Create a nx repo with nextJS project and make the following change to the `project.json` file of the nextJS app:

```
"serve": {
      "executor": "@nrwl/next:server",
      "options": {
        "buildTarget": "<app>:build",
        "dev": false
      },
      "configurations": {
        "production": {
          "buildTarget": "<app>:build:production",
          "dev": false
        }
      }
    },
```
Then execute the command `nx serve <app>`

### Environment
 >  NX   Report 

```
   Node : 16.14.0
   OS   : win32 x64
   npm  : 8.5.2

   nx : 13.10.6
   @nrwl/angular : undefined
   @nrwl/cli : 13.7.0
   @nrwl/cypress : 13.7.0
   @nrwl/detox : undefined
   @nrwl/devkit : 13.7.0
   @nrwl/eslint-plugin-nx : 13.7.0
   @nrwl/express : undefined
   @nrwl/jest : 13.7.0
   @nrwl/js : 13.7.0
   @nrwl/linter : 13.7.0
   @nrwl/nest : undefined
   @nrwl/next : 13.7.0
   @nrwl/node : undefined
   @nrwl/nx-cloud : 13.1.6
   @nrwl/react : 13.7.0
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.7.0
   @nrwl/tao : 13.6.1
   @nrwl/web : 13.7.0
   @nrwl/workspace : 13.7.0
   typescript : 4.4.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         @nxrocks/nx-spring-boot: 3.0.0
```

**Comment by AgentEnder** [comment]
Hey @saubhagya23 , it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate 13.10.6, as that is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

**Comment by saubhagya23** [comment]
Hi @AgentEnder, I tried executing `nx migrate 13.10.6` and migrated the nx packages but it did not work. I'm still getting the same issues.

The dev and build styling is still inconsistent and I'm not able to replicate the same on local.

Is there another way I can resolve this?

**Comment by saubhagya23** [comment]
Hi @AgentEnder,
Any update on this?

**Comment by jaysoo** [comment]
@saubhagya23 Do you have a reproduction of this somewhere that we can take a look? e.g. what styes are in your global CSS vs local CSS module?

**Comment by jaysoo** [comment]
For `dev: false` to work you need to build the application beforehand (e.g. the built artifact must be in `dist` first).
