### ISSUE TITLE
14.8.2 is no long detecting any dependencies

### ISSUE THREAD

**Issue by valourus** [nrwl/nx#12339]
## Current Behavior
NX is building our monorepo alphabetically since it doesn't see any dependencies anymore since `14.8.0` (`14.7.18` works fine). I looked at `nx graph` which is just laying out our dependencies horizontally. 

Running a build now results in a lot of Typescript error's telling us that other declaration files weren't built. 
## Expected Behavior
I expected the same build behavior in `14.8.x` (I tested .0 & .1 & .2)

## Steps to Reproduce
We used to have a lerna repo setup but we migrated to NX using the add-nx-to-mono-repo command.

To reproduce this issue, in the `nx-example` repository, update `nx` and `nx-cloud` to the latest version and run `npm run dep-graph`.
The output before updating is as follows: 

![image](https://user-images.githubusercontent.com/28561232/193240523-24d4fa55-10ca-4777-906a-2f19c2befce6.png)

After updating the dependency graph looks like this:
![image](https://user-images.githubusercontent.com/28561232/193240718-c6ade03b-7832-4ed6-84cc-471107e23837.png)

While running builds the dependencies are no longer build in order
### Environment
For building we always use  `nx run-many --target=build`

<details>
<summary>report</summary> 
Node : 14.18.0

OS   : linux x64

npm  : 6.14.15

nx : 14.8.2

@nrwl/angular : Not Found
@nrwl/cypress : Not Found
@nrwl/detox : Not Found
@nrwl/devkit : Not Found
@nrwl/esbuild : Not Found
@nrwl/eslint-plugin-nx : Not Found
@nrwl/expo : Not Found
@nrwl/express : Not Found
@nrwl/jest : Not Found
@nrwl/js : Not Found
@nrwl/linter : Not Found
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/nx-cloud : 14.7.0
@nrwl/nx-plugin : Not Found
@nrwl/react : Not Found
@nrwl/react-native : Not Found
@nrwl/rollup : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : Not Found
@nrwl/web : Not Found
@nrwl/webpack : Not Found
@nrwl/workspace : Not Found
typescript : 4.7.3
Local workspace plugins:
Community plugins:

</details>

**Comment by skrtheboss** [comment]
Should be related to https://github.com/nrwl/nx/issues/12338

**Comment by AgentEnder** [comment]
Closing this as a suspected duplicate, try 14.8.3 and file a new issue if it persists.
