### ISSUE TITLE
Not possible to add assets from outside workspace root

### ISSUE THREAD

**Issue by woppa684** [nrwl/nx#12334]
## Current Behavior
When I try to include an asset from outside the workspace root folder, e.g. :
```
{
    "input": "../SomeFolder",
    "glob": "SomeScript.ps1",
    "output": "./scripts"
}
```
, I get the following error:

```
C:\MyWorkspace\node_modules\ignore\index.js:364
  throw new Ctor(message)
        ^

RangeError: path should be a `path.relative()`d string, but got "../SomeFolder/SomeScript.ps1"
    at throwError (C:\Repos\COES\COES\COES.NodeJS\node_modules\ignore\index.js:364:9)
    at checkPath (C:\Repos\COES\COES\COES.NodeJS\node_modules\ignore\index.js:383:12)
    at Ignore._test (C:\Repos\COES\COES\COES.NodeJS\node_modules\ignore\index.js:504:5)
    at Ignore.ignores (C:\Repos\COES\COES\COES.NodeJS\node_modules\ignore\index.js:549:17)
    at C:\Repos\COES\COES\COES.NodeJS\node_modules\@nrwl\js\src\utils\assets\copy-assets-handler.js:89:38
    at Array.reduce (<anonymous>)
    at CopyAssetsHandler.<anonymous> (C:\Repos\COES\COES\COES.NodeJS\node_modules\@nrwl\js\src\utils\assets\copy-assets-handler.js:86:37)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Repos\COES\COES\COES.NodeJS\node_modules\tslib\tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## Expected Behavior
I expect to be able to copy files from arbitrary file paths to my publishable package dist folder before publishing. 

## Steps to Reproduce
Include an asset from outside the workspace root folder

### Environment
```
 >  NX   Report complete - copy this into the issue template

   Node : 16.15.0
   OS   : win32 x64
   npm  : 8.16.0

   nx : 14.7.13
   @nrwl/angular : 14.7.13
   @nrwl/cypress : 14.7.13
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.13
   @nrwl/eslint-plugin-nx : 14.7.13
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.13
   @nrwl/js : 14.7.13
   @nrwl/linter : 14.7.13
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 14.7.13
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.13
   @nrwl/web : Not Found
   @nrwl/workspace : 14.7.13
   typescript : 4.8.3
   ---------------------------------------
   Local workspace plugins:
         @myorg/my-sdk
   ---------------------------------------
   Community plugins:
```

**Comment by AgentEnder** [comment]
Is your workspace not at the git repo root?

**Comment by woppa684** [comment]
Unfortunately, due to our company internal repository structures its not. We have repositories containing .NET Core backends end Angular frontends in one repository, where they are each in different sub folders of the repo.

**Comment by AgentEnder** [comment]
Yeah, that makes sense... This is the only case that I can think of where such functionality makes sense, and in general I'm not sure that it should be supported...

Can you try symlinking the asset directory into the monorepo? Its possible that could work as a workaround.

**Comment by woppa684** [comment]
Well, as a workaround I created a custom executor for now, that does take assets from wherever I want :) 

Fortunately we have more than enough build steps to fit in nicely here. I have a custom pack target that packs the resulting libraries as an NPM package where I now include the extra assets. We also have targets that version our libraries and their dependencies correctly and transform translation source files (we also have a company format there) to JSON etc. I would rather stay away from symlinks, but I might give it a try anyway!
