### ISSUE TITLE
HRM Chunk Load Errors for freshly installed remotes in local development for @nrwl/react projects

### ISSUE THREAD

**Issue by pcostanz** [nrwl/nx#12350]
## Current Behavior
Following instructions here on how to spin up a new empty workspace https://nx.dev/recipe/faster-builds - I'm able to generate a host application, and then a remote. When I go to do local development on the remote using `npx nx serve myRemote --open` I notice that HMR is not working as expected when I save a change to the root React app and the console is throwing an error about the polyfills chunk not loading.

## Expected Behavior
I would expect HMR to work when developing a remote. I don't know if this is a regression.

## Steps to Reproduce
`npx create-nx-workspace project --preset=empty`
`npm install --save-dev @nrwl/react`
`npx nx g @nrwl/react:host host`
`npx nx g @nrwl/react:remote remote`
`npx nx serve remote --open`
Edit something in the remote app.tsx, for example - change the title prop on the <NxWelcome> component.
See an HMR error in the console and live reload not work.

### Failure Logs
```
[HMR] Update failed: ChunkLoadError: Loading hot update chunk polyfills failed.
(missing: http://localhost:4201/polyfills.c5b62573f4f02c4b.hot-update.mjs)
    at http://localhost:4201/polyfills.js:21752:25
    at new Promise (<anonymous>)
    at loadUpdateChunk (http://localhost:4201/polyfills.js:21747:19)
    at http://localhost:4201/polyfills.js:22207:28
    at Array.forEach (<anonymous>)
    at __webpack_require__.hmrC.jsonp (http://localhost:4201/polyfills.js:22202:21)
    at http://localhost:4201/polyfills.js:21230:46
    at Array.reduce (<anonymous>)
    at http://localhost:4201/polyfills.js:21226:54
```

### Environment
```
🍕 npx nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : darwin x64
   npm  : 8.11.0

   nx : 14.8.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.8.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.2
   @nrwl/js : 14.8.2
   @nrwl/linter : 14.8.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.7.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.8.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : 14.8.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.2
   @nrwl/web : 14.8.2
   @nrwl/webpack : 14.8.2
   @nrwl/workspace : 14.8.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   ```

**Comment by michaellatman** [comment]
Having same issue

Remove pollyfills and styles from the project.json options resolves the issue.

**Comment by Cpt-Falcon** [comment]
This is a problem, HMR just doesn't work

**Comment by ryansevilla** [comment]
@michaellatman This worked for me. Will removing these items affect the project when you run a build for production thought?

**Comment by Cpt-Falcon** [comment]
> @michaellatman This worked for me. Will removing these items affect the project when you run a build for production though?

Possibly. Polyfills is supposed to enable backwards compatibility for higher versions of javascript on any browser.
