### ISSUE TITLE
workspace-lint shows workspace.json is out of sync when running in linux

### ISSUE THREAD

**Issue by yuchuan1** [nrwl/nx#12359]
## Current Behavior
nx workspace-lint shows workspace.json is out of sync when running on linux (Ubunto 22.04)
It works as expected on windows and macos

## Expected Behavior
It should be able to check the integrity of the workspace

## Steps to Reproduce
1. Create an angular monorepo with nx, accept all default values
2. run yarn install
3. run yarn nx workspace-lint

### Failure Logs
<img width="562" alt="Screen Shot 2022-10-01 at 1 21 40 PM" src="https://user-images.githubusercontent.com/684074/193393964-cc1af489-05c0-4d7f-a774-f0ee0a2b6a21.png">

### Environment
>  NX   Report complete - copy this into the issue template

   Node : 16.17.1
   OS   : linux arm64
   yarn : 1.22.19
   
   nx : 14.8.2
   @nrwl/angular : 14.8.2
   @nrwl/cypress : 14.8.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.2
   @nrwl/js : 14.8.2
   @nrwl/linter : 14.8.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.7.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.2
   @nrwl/web : Not Found
   @nrwl/webpack : 14.8.2
   @nrwl/workspace : 14.8.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

**Comment by MichaelKaaden** [comment]
Probably related to #12338.

**Comment by AgentEnder** [comment]
Fixed in 14.8.3
