### ISSUE TITLE
Official Kotlin support plugin?

### ISSUE THREAD

**Issue by algoflows** [nrwl/nx#12358]
## Description
- Official NX monorepo support for Kotlin/Android projects.

## Motivation

Kotlin is on the way to being huge, there's also currently no monorepo support for Kotlin Multiplatform, server or android development anywhere. Kotlin is and Jetbrains have an official partnership with google.

## Suggested Implementation
Be able to start, version and support Kotlin projects via NX monorepo tooling.

**Comment by khalilou88** [comment]
Hi @algoflows, I wrote an article (https://dev.to/gridou/kotlin-multiplatform-inside-nx-workspace-5cfn) to show how you can use `nx-gradle` plugin for this.

**Comment by algoflows** [comment]
@khalilou88 can we setup/scaffold all platforms (web, desktop, ios and android) through the plugin? Curious if we can scaffold libs and share them across app folder projects?

**Comment by khalilou88** [comment]
@algoflows I released a version of nx-gradle with first support of kotlin-multiplatform. To test it you can follow this steps :
- Create a nx workspace
- Install @jnxplus/nx-gradle
- Init workspace with gradle and kotlin-multiplatform: `nx generate @jnxplus/nx-gradle:init --preset kotlin-multiplatform`
- Scaffold kotlin multiplatform projects:  `nx generate @jnxplus/nx-gradle:kotlin-multiplatform my-multiplatform-projects`

Run the android app with android studio. (I didn't test the ios app yet)
Run the graph
