### ISSUE TITLE
Get name of current affected app

### ISSUE THREAD

**Issue by dan-cooke** [nrwl/nx#12353]
### Discussed in https://github.com/nrwl/nx/discussions/12352

<div type='discussions-op-text'>

<sup>Originally posted by **dan-cooke** September 30, 2022</sup>
I want to tag a docker image using `nx affected --target=docker --tags=myrepo.io/{APP}`

How can I get the current `APP` being executed by `nx affected`. I swore lerna had something for this, but I can't quite find it.

Any ideas?</div>

Creating an issue because I really don't see any way of achieving this without creating a custom docker executor, which seems wasteful as there already exists a great community executor.

It would be useful for performing dynamic commands based on the name of the currently affected app

**Comment by minijus** [comment]
Implementation of custom executor `docker` could use executorContext to get project name.

**Comment by dan-cooke** [comment]
Thanks for the usggestion ill have a look into it.

But long term - I think it would make more sense to build this behaviour into the `affected `command. 

Perhaps it could export its `executorContext` as environment variables so the executing scripts can access information there.

**Comment by minijus** [comment]
I see, if `docker` target is just using `run-commands` executor then there no access to `executorContext`.

Quick and clean solution (for now) would be to:
1. Generate local workspace nx-plugin
2. Generate new executor `docker` to nx-plugin
3. Add `docker` target implementation with needed context
4. Use new local nx-plugin:docker executor instead of `nx:run-commands`.

**Comment by AgentEnder** [comment]
This seems simple enough, we could add NX_PROJECT_NAME as an env variable in the forked process for each executor pretty easily I think ™️...

**Comment by dan-cooke** [comment]
@AgentEnder I just forked the repo and a quick play around, after attempting to make the fix, looks like its been in there for over a year.

https://github.com/nrwl/nx/commit/fe7ab82d914a40399b05c3c44ed56edf65c1326a

This should really be added to the docs somewhere, especially under the affected section

**Comment by dan-cooke** [comment]
Closing as already implemented, and docs have been updated
