### ISSUE TITLE
feat: share library source code in private monorepo

### ISSUE THREAD

**Issue by stefan-karlsson** [nrwl/nx#1235]
## Feature description
Currently me and my team is working in a **private** GIT repository. 
Nx gives us the opportunity to share both private and public packages thro NPM.

This sharing is awesome, thanks for that! 
But there is times where me and my team want to publish a public package **and** share its source code.

Why? Well let's face it, it's awesome to brag about the code, and also to get help from the community making the library better.

It would be nice if there was a way to mark a library as a multi-repo that uploads the source code to a separate GIT repo and created a new folder in the workspace.

`ng g lib feature-awesome-lib --publishable --multi-repo`

I know this causes issues like:
- CI/CD pipeline is needed for each repo
- Version mess
- Each library needs to be managed separately
- and so on...

But hey, problems is to solve right? I think this could be a great feature to enrich Nx.

What do you guys think? Maybee it easier to create a separate NX repo that is public?

**Comment by vsavkin** [comment]
@stefan-karlsson maybe you could do it using git submodules (see here: https://blog.nrwl.io/dev-workflow-using-git-submodules-and-yarn-workspaces-14fd06c07964)?

**Comment by stefan-karlsson** [comment]
@vsavkin thanks for pointing me in The right direction.
