### ISSUE TITLE
Add support fo setting environment variables into memory through plugins

### ISSUE THREAD

**Issue by PaulPopat** [nrwl/nx#12368]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

This is to introduce the ability to set environment variables at build time. This should probably be done through plugins, I would imagine that the executor plugins would be the most idiomatic method for this.

## Motivation

Often, it is useful to load environment variables at build time on large applications. This is so as to be able to use tools for managing config and secrets, such as the Parameter Store in AWS. These are useful to manage large numbers of configuration options and environment. It is also useful for convenience, such as syncing environment variables between developer environments, etc, without committing them to source control.

Currently, the only way to set environment variables is to either have them assigned before starting the NX process or to set environment files on the local disk. This is fine but environment files persist the build so setting them at build time risks unexpected side effects during local development.

## Suggested Implementation

I would probably vote for adding a method to do this to the ExecutorContext. Maybe a `setEnvironmentVariable` function? This could then call back to the parent process and set the environment variable in memory.

## Alternate Implementations

I know that certain systems have an object for environment variables in plugins and then listen for mutation. I think that this method is not as explicit but it does seem popular.

Also, it doesn't need to be in executors. If this is a use case that lots of people may want to do with ad hoc scripts then maybe a more general method for setting them could be useful.

**Comment by jbadeau** [comment]
I would be more interested in a context map that is passed by default to plugins could  so that they could read/write namespaced params to the context map


This context would also be accessible in the project.json maybe like ${pluginname.targetname.version}

**Comment by jbadeau** [comment]
jq read value into file

**Comment by bruceharrison1984** [comment]
@jbadeau I had a similar idea for this today. I feel like NX is missing the ability to easily pass output *values* from one plugin/target to one later down the line. In my case, a randomly generated S3 bucket name has to be referenced later to upload files. There isn't a great way to do this right now.

**Comment by jbadeau** [comment]
Yeah, I’m really annoyed by this gap as most pipeline tools have a way to export artifacts/values for subsequent steps to consume. I would be happy just with envvars and the ability to interpolate them in nx.json and project.json. Something like {env.FOO}. I often have the need to ref CI variables like branch_name or commmit_hash, secrets.
