### ISSUE TITLE
Generated graph is invalid 

### ISSUE THREAD

**Issue by pkonieczniak** [nrwl/nx#12366]
## Current Behavior
The current monorepo setup consists from nx and Yarn workspaces.
Every nx command is producing correct results except `graph` or `graph:affected`. Instead of showing a graph with relations all applications and libraries are drawn in one line one next to the other without any relations.
In the left navbar on the left side I can see correctly grouped projects under `app projects` or `lib projects`

I don't think that is any issues with project configuration, because symlinks are working correctly and other nx commands work fine.

Nx was added to the project via `npx add-nx-to-monorepo@latest`, and before we had a configuration with Lerna.
I checked version 14.8.0 and graph is generated correctly,

## Expected Behavior
The graph should correctly reflect relations between projects, and applications/libs should be drawn in one line

## Steps to Reproduce
I can't share the current configuration, because the repo is private. Below there is the main package.json  and nx configuration.
https://gist.github.com/pkonieczniak/de6d0cb0c2833c512088444bfc95e8a0

### Failure Logs
There are no failure logs. Dev server with the graph is running but the graph itself is broken 

### Environment
- Yarn-3.2.3
- nx-latest-14.8.2
- node-14.17.0
- WSL2 with Ubuntu 20.04.4 LTS

**Comment by maboesanman** [comment]
I believe there's some sort of caching issue here.

I've got something similar, and here's some additional info:

```bash
git clean -dXF
yarn
nx graph
```

the project graph is fully disconnected

then editing a project's dependencies makes that project's relations appear in the graph

finally, running nx clear-cache returns the graph to fully disconnected

**Comment by maboesanman** [comment]
confirmed it works on 14.8.1

**Comment by joshlartz** [comment]
I have the same behavior on 14.8.2.

**Comment by AgentEnder** [comment]
Can you check if this is working in 14.8.3 now?

**Comment by joshlartz** [comment]
14.8.3 fixed the graph for me. Thanks!

**Comment by abitbetterthanyesterday** [comment]
I have the same issue here, no relations showing up unless I specifically add them to my package.json.

I'm unsure if this is the expected behavior.

**Comment by AgentEnder** [comment]
@abitbetterthanyesterday does your nx.json file have an extends key?

**Comment by abitbetterthanyesterday** [comment]
`"extends": "nx/presets/npm.json"`

Yes it does @AgentEnder

**Comment by abitbetterthanyesterday** [comment]
![image](https://user-images.githubusercontent.com/17796338/207776865-1a56f99d-a15f-4bd7-b721-209e52e02429.png)


It looks like you put me on the right path ...
