### ISSUE TITLE
[Storybook] Fix Webpack5 lazyCompilation and fsCache in Nx project 

### ISSUE THREAD

**Issue by ild0tt0re** [nrwl/nx#12387]
Hey @mandarini 🙂, I found what is missing for `lazyCompilation` and `fsCache` to work :tada:

> 🚀 We noticed a **huge performance improvement** -> **more than 10X :zap:** from **~90s to ~7s**  in **dev mode**:
```shell
$ nx storybook $myProject
```

### How Storybook work?
Setting the following builder ...
```js
// .storybook/main.js

module.exports = {
  core: {
      builder: {
        name: 'builder-webpack5',
        options: {
          lazyCompilation: true,
          fsCache: true,
        },
      },
    },
  ...
```
... the **base webpack configuration** should be composed with the following options as a fresh install of **Storybook without Nx**
```js
const webpackBaseConfig = {

    // base config for `lazyCompilation` and `fsCache` to work
    optimization: {
        splitChunks: { chunks: 'all' },
        runtimeChunk: true,
        sideEffects: true,
        usedExports: false,
        moduleIds: 'named',
        minimizer: [],
    },
    cache: { type: 'filesystem' },
    experiments: { lazyCompilation: { entries: false } },

    // other base config....

}
```

### What needs to do Nx side?

Considering `lazyCompilation` and `fsCache` builder options as did by **Storybook** here:
https://github.com/storybookjs/storybook/blob/7035ea7389393da041985ebc491ee58dedb50d06/code/lib/builder-webpack5/src/preview/base-webpack.config.ts#L53-L55

### My final configuration for maximizing the performance (SWC + lazyCompilation + devtool = false)

```js
// .storybook/main.js

module.exports = {
  webpackFinal: async (config, { configType }) => {
      
      if (configType === 'DEVELOPMENT') {
        // not needed for `lazyCompilation` but you get fastest performance in rebuild with webpack
        config.devtool = false

        config = {
          ...config,
          optimization: {
            splitChunks: { chunks: 'all' },
            runtimeChunk: true,
            sideEffects: true,
            usedExports: false,
            moduleIds: 'named',
            minimizer: [],
          },
          cache: { type: 'filesystem' },
          experiments: { lazyCompilation: { entries: false } },
        }
      }

      return config
    },

  addons: [
    {
      name: 'storybook-addon-swc',
      options: {
        enable: true,
        enableSwcLoader: true,
        enableSwcMinify: false,
        swcLoaderOptions: {
          jsc: {
            experimental: {
              plugins: [
                [
                  // ONLY if you use styled-components lib
                  '@swc/plugin-styled-components',
                  {
                    displayName: true,
                    ssr: true,
                  },
                ],
              ],
            },
          },
        },
        swcMinifyOptions: {},
      },
    },

  features: {
    babelModeV7: true,
   // code splitting
    storyStoreV7: true,
  },
```

### REPORT

```
   Node : 16.13.1
   OS   : darwin x64
   pnpm : 7.13.0

   nx : 14.8.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.7.17
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.2
   @nrwl/js : 14.8.2
   @nrwl/linter : 14.8.2
   @nrwl/nest : Not Found
   @nrwl/next : 14.8.2
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.8.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : 14.8.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.2
   @nrwl/web : 14.8.2
   @nrwl/webpack : 14.8.2
   @nrwl/workspace : 14.8.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @jscutlery/semver: 2.26.0
   	 ngx-deploy-npm: 4.1.0
```

**Comment by mandarini** [comment]
Hi @ild0tt0re ! Thank you very much for taking the time to figure this out. So, let me understand a bit better. Have you managed to get your configuration to work? Or do we need to change something in the Nx code? The thing is that Nx sends the options as they are over to the Storybook builder, so I'm trying to understand why we should be overriding something, if we have to.

**Comment by mandarini** [comment]
Ah, so you manually added

```
    cache: { type: 'filesystem' },
    experiments: { lazyCompilation: { entries: false } },
```
in your code, whereas Storybook does that automatically [in the code you linked above](https://github.com/storybookjs/storybook/blob/7035ea7389393da041985ebc491ee58dedb50d06/code/lib/builder-webpack5/src/preview/base-webpack.config.ts#L53-L55).

**Comment by ild0tt0re** [comment]
Yes but not only, the webpack configuration of Nx, once you have set the two props above in the storybook manager, should have inside:
```
const webpackBaseConfig = {

    // base config for `lazyCompilation` and `fsCache` to work
    optimization: {
        splitChunks: { chunks: 'all' },
        runtimeChunk: true,
        sideEffects: true,
        usedExports: false,
        moduleIds: 'named',
        minimizer: [],
    },
    cache: { type: 'filesystem' },
    experiments: { lazyCompilation: { entries: false } },

    // other base config....

}
```

**Comment by mandarini** [comment]
I see! Ok, I'll see how I can fix this! :)

**Comment by mandarini** [comment]
Hi @ild0tt0re !

I'm sorry but I still cannot figure out why you are not getting the results you expect. I spent half the day looking into it, I swear!!

So, this file: 
`node_modules/@storybook/builder-webpack5/dist/cjs/presets/custom-webpack-preset.js`

Breakpoints in these lines and observe the value of `coreOptions`:
![Screenshot 2022-10-05 at 7 32 17 PM](https://user-images.githubusercontent.com/6603745/194113536-ad55fdf7-7876-47a3-918e-c740b684f99d.png)
![Screenshot 2022-10-05 at 7 32 08 PM](https://user-images.githubusercontent.com/6603745/194113547-69342b42-5caf-44e3-ae9c-73ddb5033f73.png)

```
```

**Comment by mandarini** [comment]
Ok. So:

SOLUTION:

In your project's `main.js` (eg. `apps/my-app/.storybook/main.js`), pass `disableWebpackDefaults: false` as an option to the `core` object:

```
const rootMain = require('../../../.storybook/main');

module.exports = {
  ...rootMain,
  core: {
    ...rootMain.core,
    disableWebpackDefaults: false,
    builder: {
      name: 'webpack5',
      options: {
        lazyCompilation: true,
        fsCache: true,
      },
    },
  },
...
```

**Comment by ild0tt0re** [comment]
> Ok @ild0tt0re . So:
> 
> SOLUTION:
> 
> In your project's `main.js` (eg. `apps/my-app/.storybook/main.js`), pass `disableWebpackDefaults: false` as an option to the `core` object:
> 
> ```
> const rootMain = require('../../../.storybook/main');
> 
> module.exports = {
>   ...rootMain,
>   core: {
>     ...rootMain.core,
>     disableWebpackDefaults: false,
>     builder: {
>       name: 'webpack5',
>       options: {
>         lazyCompilation: true,
>         fsCache: true,
>       },
>     },
>   },
> ...
> ```
> 
> Please let me know if that fixes your issue! And I'll reach out to the Storybook team to learn if it's the way to go.

No unfortunately it didn't work.

For repro you can simply create a fresh installation of nextjs (without Nx) and adds storybook with official CLI.
You will notice that no further parameters are required other than the basic configuration

```js
module.exports = {
  stories: [
    "../stories/**/*.stories.mdx",
    "../stories/**/*.stories.@(js|jsx|ts|tsx)",
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
  ],
  framework: "@storybook/react",
  features: {
    babelModeV7: true,
    interactionsDebugger: true,
    storyStoreV7: true,
  },
  core: {
    builder: {
      name: "@storybook/builder-webpack5",
      options: {
        lazyCompilation: true,
        fsCache: true,
      },
    },
  },
  webpackFinal: async (config, { configType }) => {
    // apply any global webpack configs

    return config;
  },
};

```

From CLI output you will notice that each time that you select a component from the sidebar, webpack pre-bundle only the asset of that specific component.

**Comment by ild0tt0re** [comment]
@mandarini you don't need a specific repro, just a fresh install to verify the issue from the terminal as described above

**Comment by mandarini** [comment]
Ok! I'll try that, thanks @ild0tt0re ! I'm also in contact with @ndelangen for any suggestions, because I think I'm stuck :(

**Comment by mandarini** [comment]
This [PR](https://github.com/storybookjs/storybook/pull/19376) was created on Storybook to address this issue!

**Comment by mandarini** [comment]
@ild0tt0re I have just confirmed (tested locally) that above PR fixes the issue!!!! You can try it out yourself, too. If you're not bored, you can clone the Storybook repository (https://github.com/storybookjs/storybook), then run `yarn` to install dependencies, then run `yarn bootstrap` and choose "build packages", then copy the `lib/builder-webpack5/dist` folder and replace it with `node_modules/@storybook/builder-webpack5/dist` folder. Then run Storybook again, and observe the lazy compilation!

**Comment by mandarini** [comment]
Linknig the [new PR](https://github.com/storybookjs/storybook/pull/19387) here, for reference

**Comment by ild0tt0re** [comment]
Thanks @mandarini!

**Comment by pumano** [comment]
it fixed against story book 7 only??

**Comment by mandarini** [comment]
@pumano https://github.com/storybookjs/storybook/pull/19387#issuecomment-1271250951
