### ISSUE TITLE
generators config is ignored when running `nx g d`

### ISSUE THREAD

**Issue by e-oz** [nrwl/nx#12388]
## Current Behavior

Content of `nx.json > generators > @nrwl/angular:directive` is ignored

## Expected Behavior

Would be nice to have it working to don't add `--standalone=true --flat=false` every time.

## Steps to Reproduce

1. Add to `nx.json > generators`:
```
    "@nrwl/angular:directive": {
        "standalone": true,
        "flat": false
    }
```
2. Create a library
3. Remove auto-generated module file (and link to that module from index.ts)
4. Run `nx g d example --project=yourLibName`

You'll see error:
```
 >  NX   Could not find an NgModule. Use the '--skip-import' option to skip importing in NgModule.
```

Now try `nx g d example --project=yourLibName --standalone=true` - directive will be generated.

<details>
<summary>Environment</summary>

```
>  NX   Report complete - copy this into the issue template

   Node : 18.9.0
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 14.8.2
   @nrwl/angular : 14.8.2
   @nrwl/cypress : 14.8.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.2
   @nrwl/js : 14.8.2
   @nrwl/linter : 14.8.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.7.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.2
   @nrwl/web : Not Found
   @nrwl/webpack : 14.8.2
   @nrwl/workspace : 14.8.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @ngrx/component-store: 14.3.1
         @ngrx/effects: 14.3.1
         @ngrx/store: 14.3.1
         @jefiozie/ngx-aws-deploy: 4.1.0
         @ngrx/eslint-plugin: 14.3.1
         @storybook/angular: 6.5.12
```
</details>

**Comment by FrozenPandaz** [comment]
Can you please retry with the latest version?

**Comment by AgentEnder** [comment]
Hey @e-oz! @nrwl/angular doesn't provide the generator for directives, its actually coming from @schematics/angular. As such, the key used should be `@schematics/angular:directive` This behaviour did change somewhat recently, but it is more correct now. Thanks for the report!

**Comment by e-oz** [comment]
Ok, thanks.

**Comment by e-oz** [comment]
Works great :)
