### ISSUE TITLE
Add paths to watch to @nrwl/builders:node-build

### ISSUE THREAD

**Issue by creadicted** [nrwl/nx#1239]
Since I work with multiple back-ends that share nest.js libraries which are outside of the source folder. I ask if there is a way to add watch paths to `the @nrwl/builders:node-build`  builder. Tried it with plugins in the webpack.config but was not successful.

**Comment by FrozenPandaz** [comment]
We depend on `webpack` to do the file watching. As long as the files are in the compilation graph, it should cause recompilation. How are the files imported?

**Comment by creadicted** [comment]
Hello @FrozenPandaz my smplified folder structure looks like this 
```
- tsconfig.json
- apps
  - backend/src/
      - app/app.module.ts
      - main.ts
- libs/backend/
   -  modulename/src/name.module.ts
```
I use ts paths in the tsconfig.ts file to define the paths: 
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "importHelpers": true,
    "sourceMap": false,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2017", "dom"],
    "baseUrl": ".",
    "outDir": "./dist",
    "rootDir": ".",
    "paths": { 
      "@backend/modulename": ["libs-backend/modulename/src"], 
    },
    "module": "es2015"
  },
  "exclude": ["node_modules", "tmp"]
}
```

**Comment by vsavkin** [comment]
Could you try using the latest version of Nx?

**Comment by creadicted** [comment]
Seems to work now.
