### ISSUE TITLE
addDependenciesToPackageJson filters the wrong dependencies

### ISSUE THREAD

**Issue by woppa684** [nrwl/nx#12419]
See this snippet https://github.com/nrwl/nx/blob/7de50ab407368dadfbdc0e44384b3114977668a8/packages/devkit/src/utils/package-json.ts#L42-L49

`dependencies` is filtered with `devDependencies` and the other way round. This seems wrong to me, or am I missing something?

**Comment by woppa684** [comment]
Ah, my bad, looking a bit closer it seems intentional :)

**Comment by woppa684** [comment]
Well, you know what, maybe it's not, I'll leave this open a bit longer.

**Comment by AgentEnder** [comment]
This is purposeful. It prevents adding duplicate entries to dependencies or devdependencies if they already exist.
