### ISSUE TITLE
Error running `ng test` after creating new workspace

### ISSUE THREAD

**Issue by frgul006** [nrwl/nx#1242]
## Expected Behavior

Should be able to run `npm run test` or `ng test` after initializing a new nx workspace

## Current Behavior

Executing `npm run test` in a new workspace throws an error.

## Failure Information (for bugs)

```
Can't find a root directory while resolving a config file path.
Provided path to resolve: C:\C\dev\sampleorg\apps\sampleorg\jest.config.js
cwd: C:\dev\sampleorg
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `create-nx-workspace sampleorg`
2. `cd sampleorg`
3. `npm run test`

### Context

- version of Nx used (@nrwl/schematics@7.8.0)
- Operating system: Windows 10

**Comment by jantilburgh** [comment]
I have to same issue. If you take a close look at the path then you can see that it tries to look for "C:\C\" which is not correct.

**Comment by jantilburgh** [comment]
Workaround is to downgrade to @nrwl/builders@7.7.2.

**Comment by ngfelixl** [comment]
Can reproduce, created with npm as nx-workspace.
Downgrading `@nrwl/builders` to 7.7.2 (before 7.8.0) works. Thanks @jantilburgh.

**Comment by vsavkin** [comment]
Thanks for submitting the issue. It has been fixed here: https://github.com/nrwl/nx/pull/1245
