### ISSUE TITLE
[ANGULAR][STORYBOOK] Storybook will not create story doc description and default value from angular component block comments.

### ISSUE THREAD

**Issue by marcopolo25** [nrwl/nx#12425]
Storybook is unable to create docs that documents a component's @input and @output using block comments. These comments should automatically create the description and default value in the docs pane of the components story.

## Current Behavior
Not creating the description and default value for component's @inputs and @ouputs from block comments.

## Expected Behavior
components @input and @ouput block comments should generate docs description and default values.

## Steps to Reproduce
Create a new angular nx workspace. Default all the other options.
``npx create-nx-workspace@latest``

Create a `shared` folder in the workspace libs folder.

Run nx nrwl genrator to create a new angular library - `storybook-test`.
``npx nx generate @nrwl/angular:library storybook-test --no-interactive --dry-run``

Run nx console to generate a new angular component `ui-storybook-test` in the `shared-storybook-test`.
``npx nx generate @nrwl/angular:component ui-storybook-test --no-interactive --dry-run``

Run nx console to generate a storybook configuration for the `storybook-test` lib.
``npx nx generate @nrwl/angular:storybook-configuration storybook-test-lib --no-interactive --dry-run``

Run nx console to generate stories for the `storybook-test` lib. This will create stories for every angular component in the `storybook-test` library, including the ui-storybook-test.
``npx nx generate @nrwl/angular:storybook-configuration storybook-test-lib --no-interactive --dry-run``

Use nx console to run the storybook for the `ui-storybook-test`.
``npx nx run storybook-test-lib:storybook``

In the canvas pane of the component story, the controls pane is not showing. Even if you toggle the add-on controls option in the storybook menu. 

Here's the my package.json 

```
"dependencies": {
    "@angular/animations": "~14.2.0",
    "@angular/common": "~14.2.0",
    "@angular/compiler": "~14.2.0",
    "@angular/core": "~14.2.0",
    "@angular/forms": "~14.2.0",
    "@angular/platform-browser": "~14.2.0",
    "@angular/platform-browser-dynamic": "~14.2.0",
    "@angular/router": "~14.2.0",
    "@compodoc/compodoc": "^1.1.19",
    "@nrwl/angular": "14.8.2",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  }
"devDependencies": {
    "@angular-devkit/build-angular": "~14.2.0",
    "@angular-eslint/eslint-plugin": "14.0.4",
    "@angular-eslint/eslint-plugin-template": "14.0.4",
    "@angular-eslint/template-parser": "14.0.4",
    "@angular/cli": "~14.2.0",
    "@angular/compiler-cli": "~14.2.0",
    "@angular/language-service": "~14.2.0",
    "@nrwl/cli": "14.8.2",
    "@nrwl/cypress": "14.8.2",
    "@nrwl/eslint-plugin-nx": "14.8.2",
    "@nrwl/jest": "14.8.2",
    "@nrwl/linter": "14.8.2",
    "@nrwl/nx-cloud": "14.7.0",
    "@nrwl/storybook": "14.8.2",
    "@nrwl/workspace": "14.8.2",
    "@storybook/addon-essentials": "^6.5.12",
    "@storybook/angular": "~6.5.9",
    "@storybook/builder-webpack5": "~6.5.9",
    "@storybook/core-server": "~6.5.9",
    "@storybook/manager-webpack5": "~6.5.9",
    "@types/jest": "28.1.1",
    "@types/node": "16.11.7",
    "@typescript-eslint/eslint-plugin": "5.39.0",
    "@typescript-eslint/parser": "5.39.0",
    "autoprefixer": "^10.4.0",
    "cypress": "^10.7.0",
    "eslint": "~8.15.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "jest": "28.1.1",
    "jest-environment-jsdom": "28.1.1",
    "jest-preset-angular": "12.2.2",
    "ng-packagr": "~14.2.0",
    "nx": "14.8.2",
    "postcss": "^8.4.5",
    "postcss-import": "~14.1.0",
    "postcss-preset-env": "~7.5.0",
    "postcss-url": "~10.1.3",
    "prettier": "^2.6.2",
    "tailwindcss": "^3.0.2",
    "ts-jest": "28.0.5",
    "ts-node": "10.9.1",
    "tslint": "~6.1.0",
    "typescript": "4.8.4",
    "webpack": "^5.64.0"
  }
```

### Failure Logs
No Failed logs

#### No story docs description and default values
```
/**
   * Is this the principal call to action on the page?
   */
   @Input()
   primary = false;

   /**
    * What background color to use
    */
   @Input()
   backgroundColor?: string;

   /**
    * How large should the button be?
    */
   @Input()
   size: 'small' | 'medium' | 'large' = 'medium';

   /**
    * Button contents
    *
    * @required
    */
   @Input()
   label = 'Button';
```
No description or default values even though they have been set.
![no docs description](https://user-images.githubusercontent.com/4663226/194105319-774e9e40-368b-4942-b736-d73d7538601d.png)

#### Expected behavior
![storybook-taskbox-docs-with-description-default-value](https://user-images.githubusercontent.com/4663226/194103725-33093a17-d1d0-46a1-8900-a03294478908.png)

**Comment by mandarini** [comment]
Hi there @marcopolo25 ! I am not sure what you mean, here!

Are you thinking of MDX? Can you point me to the documentation you are using? 

Can you also please create a project (I guess an independent - No Nx - Angular app), that uses the format you are referring to?

We are certainly not generating any docs, and on the Angular side of things, for Storybook, [we are using directly the Storybook builders](https://nx.dev/storybook/angular-storybook-targets). So, any features should be referred to the Storybook team directly...

**Comment by mandarini** [comment]
So! 

It turns out you do need to switch `compodoc` to `true`, install `@compodoc/compodoc`, but you also need to make a number of adjustments as well, to see everything working:

Here is my repo: https://github.com/mandarini/nx-sb-compodoc

And here is the commit that shows the adjustments you need to do, to make the docs appear as you expect:
https://github.com/mandarini/nx-sb-compodoc/commit/d6606b02cd5b9565c7b852678f23857c0f76ddc3

We definitely need to add this in the docs, and potentially create a generator for it. I'll do that as soon as I can!

**Comment by mandarini** [comment]
Here is the docs page for this: https://nx.dev/storybook/angular-storybook-compodoc
