### ISSUE TITLE
Module Federation with Dynamically Discoverable Remotes

### ISSUE THREAD

**Issue by pcurrivan** [nrwl/nx#12432]
## Description

Support for "dynamic dynamic" module federation as described in @manfredsteyer's article: https://www.angulararchitects.io/en/aktuelles/dynamic-module-federation-with-angular/

In other words, support for module federation in situations where the set of remote applications is not defined until after build time, and is discovered at runtime by host application.

## Motivation

This would enable creating a dynamic plugin system where plugins (remotes) can be added and removed dynamically on a deployed app.  This would allow new plugins (remotes) to be created and deployed without rebuilding or redeploying the host application.

## Suggested Implementation

The package @angular-architects/module-federation supports this with the Manifest concept as well as with loadRemoteEntry and loadRemoteModule.

## Alternative Implementation
Should we just use @manfredsteyer's package instead of Nx MF?

**Comment by Coly010** [comment]
This is supported :) 

https://nx.dev/recipe/dynamic-module-federation-with-angular
