### ISSUE TITLE
Cypress e2e no code coverage: Cannot find coverage file .nyc_output\out.json

### ISSUE THREAD

**Issue by Bogs-123** [nrwl/nx#12459]
I am unable to generate code coverage for e2e test ran by Cypress.

When following the [Cypress documentation](https://docs.cypress.io/guides/tooling/code-coverage#E2E-code-coverage) to add code coverage on a new (non-monorepo) Angular application, everything works. 

Following the same steps this error occurs when trying to run the e2e tests:
`Your project does not contain a default supportFile. We expect a file matching cypress/support/e2e.{js,jsx,ts,tsx} to exist`

This can be fixed by leaving the leaving the `nxE2EPreset` and adding the `setupNodes` to **cypress.config.ts**.

```typescript
import { nxE2EPreset } from '@nrwl/cypress/plugins/cypress-preset';
import { defineConfig } from 'cypress';

export default defineConfig({
  e2e: {
    ...nxE2EPreset(__dirname),
    setupNodeEvents(on, config) {
      require('@cypress/code-coverage/task')(on, config);
      // include any other plugin code...

      // It's IMPORTANT to return the config object
      // with any changed environment variables
      return config;
    },
  },
});
```

Now the tests run again. But the code coverage is not created because no output has been generated:
`Cannot find coverage file E:\nx-test\apps\testje-e2e\.nyc_output\out.json
Skipping coverage report`

**Comment by tommyc38** [comment]
You have to instrument the coverage yourself which I wish Nx would do out of the box.  I have an angular library which also uses Storybook.  In my `libs/my-lib/.storybook/main.js` I have this:

```
    if (configType !== 'PRODUCTION') {
      return merge(config, {
        module: {
          rules: [
            {
              test: /\.(js|ts)$/,
              loader: 'coverage-istanbul-loader',
              options: { esModules: true },
              enforce: 'post',
              include: require('path').join(__dirname, '../', 'src'),
              exclude: [
                /\*\/stories\/\*/,
                /\.(e2e|spec)\.ts$/,
                /node_modules/,
                /(ngfactory|ngstyle)\.js/,
              ],
            },
          ],
        },
      });
    }
```

**Comment by barbados-clemens** [comment]
is this a feature request for Nx to generate code coverage for cypress projects or is there an error with the cypress executor not correctly generating a report?

At this time I don't think we'll be setting up code coverage for cypress projects automatically, though we could maybe add some docs to help with any nx specific things that need to happen. 

As for the coverage report not generating, can you create a clone-able repo that i can take a look at to see what the error might be?
