### ISSUE TITLE
Add webpack-bundle-analyzer and related script to default Nx-created projects

### ISSUE THREAD

**Issue by IlCallo** [nrwl/nx#1246]
## Expected Behavior

It would be cool to have operations described in [this article](https://coryrylan.com/blog/analyzing-bundle-size-with-the-angular-cli-and-webpack) already done by default (or optional during workspace inizialization).

## Current Behavior

Nothing

## Context

It may probably be useful to promote a bundlesize budgeting culture in the Angular community.

http://webpackmonitor.com/ seems cool too and more "modern", but I haven't tried it out yet

**Comment by vsavkin** [comment]
100% agree with you. We need to give users the ability to analyze their bundles. But instead making it part of Nx, we decided to add the functionality to Angular Console, so it works with any CLI project.

You can read more about it here:
https://blog.nrwl.io/angular-console-7-4-release-2d4d3c654e8e

If this isn't sufficient, could you reopen the issue with more details.

Thanks!

**Comment by IlCallo** [comment]
I missed out that update because I'm not really a fan of CLI UIs.

But I guess it's ok like this, I'll just download the Angular console, ty :)

**Comment by timscullin** [comment]
Does the build analyzer still exist in the new UI?

**Comment by tommck** [comment]
@vsavkin - the Bundle Analyzer is no longer in the Angular Console.  Are we going to add support back in somewhere?

**Comment by mackelito** [comment]
Perhaps just add some docs on how to add it in a project.json file?
