### ISSUE TITLE
New NX Angular project - nx test command doesn't do anything

### ISSUE THREAD

**Issue by hassanasad** [nrwl/nx#12478]
## Current Behavior

I am very new to NX echo system. Sorry if i have missed something very basic. 
I am unable to run tests on a brand new nx workspace.
Everything installs correctly and application can serve the default NX angular page correctly.
e2e test also work fine.

However, If I run `nx test` - it just does nothing. There is no output, it doesn't open any browser window where tests can be seen running. I have never used Jest before so not sure what to expect. In Karma based testing it opens a browser and shows all the tests that ran.

## Expected Behavior

I expect the `nx test` command to show something, like the tests it ran

## Steps to Reproduce

npx create-nx-workspace@latest
Choose "Angular"
Choose SCSS
Choose NX Cloud
run `nx test`

### Environment

```
>  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : darwin x64
   npm  : 8.19.2
   
   nx : 14.8.3
   @nrwl/angular : 14.8.3
   @nrwl/cypress : 14.8.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.3
   @nrwl/js : 14.8.3
   @nrwl/linter : 14.8.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.7.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.3
   @nrwl/web : Not Found
   @nrwl/webpack : 14.8.3
   @nrwl/workspace : 14.8.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

Video of output - It just stays like this. I have tried this with two completely blank projects and is the same output.

https://user-images.githubusercontent.com/7580112/194749413-c2a70659-ea7d-443e-a474-39b50756397e.mov

**Comment by hassanasad** [comment]
Still the same issue with latest version:

```
 Node : 16.15.1
   OS   : darwin x64
   npm  : 8.19.2
   
   nx : 14.8.4
   @nrwl/angular : 14.8.4
   @nrwl/cypress : 14.8.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.4
   @nrwl/js : 14.8.4
   @nrwl/linter : 14.8.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.4
   @nrwl/web : Not Found
   @nrwl/webpack : 14.8.4
   @nrwl/workspace : 14.8.4
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   ```

**Comment by barbados-clemens** [comment]
Talked with @hassanasad in the community slack, (ref: https://nrwlcommunity.slack.com/archives/CMFKWPU6Q/p1665592834642879)

looks to be machine specific issue as it's not reproduce-able on my local machine and happens when just running `jest` without nx. 

here is the provided reproduce-able for completeness sake as well. 
https://github.com/hassanasad/nxtest

**Comment by hassanasad** [comment]
Issue resolved after uninstalling `watchman`.
Got some clue from here: https://stackoverflow.com/questions/55191638/jest-doesnt-run-hangs-indefinitely

**Comment by hassanasad** [comment]
Thanks to @barbados-clemens , @nartc and @StalkAltan
