### ISSUE TITLE
node_modules symlinks do not point to the dist folder

### ISSUE THREAD

**Issue by kerwanp** [nrwl/nx#12474]
## Current Behavior

When performing a `yarn install` with the default `package.json#workspaces` configuration the Symlinks created in the `node_modules` folder points to the project directory and not the `dist` directory.

## Expected Behavior

We should be able to define the `dist` folder where the build output is located so `yarn install` symlink the `dist` folder.

### Create a new NX Workspace

```bash
$ npx create-nx-workspace@latest
```

### Generate two Typescript libraries

```bash
$ nx g @nrwl/js:lib lib-1
$ nx g @nrwl/js:lib lib-2
```

### Import lib-2 into lib-1

```typescript
// packages/lib-2/src/index.ts

import * as lib2 from '@myorg/lib-2';
```

### Build lib-1

```bash
$ nx build lib-1
```

### Workaround

Currently in the `package.json` folder we change the workspaces configurtation to the `dist` folder.

```json
{
  "workspaces": [
    "dist/**"
  ]
}
```

Symlinks works but we have to:
- Run `yarn`
- Build projects
- Run `yarn` again to get the symlinks

### Environment

```
   Node : 16.17.1
   OS   : linux x64
   yarn : 1.22.19

   nx : 14.7.18
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.8.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.2
   @nrwl/eslint-plugin-nx : 14.8.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.0
   @nrwl/js : 14.8.2
   @nrwl/linter : 14.8.0
   @nrwl/nest : Not Found
   @nrwl/next : 14.8.2
   @nrwl/node : 14.8.2
   @nrwl/nx-cloud : 14.7.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.8.2
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.2
   @nrwl/web : 14.8.2
   @nrwl/workspace : 14.7.18
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by AgentEnder** [comment]
Hey @kerwanp , it is unrelated to the issue. but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate 14.8.2`. Alternatively, updating to latest with `nx migrate latest` would also work.
