### ISSUE TITLE
Build crashes on lint/TS error: ENV variables not forwarded to webpack

### ISSUE THREAD

**Issue by goldylucks** [nrwl/nx#12484]
When there's a TS/lint error, the build crashes ie can't see the UI

<img width="418" alt="image" src="https://user-images.githubusercontent.com/6963212/194825967-fe8b923a-d92b-4b30-aa03-39bf4abdc2ad.png">

Even tho I have the ENV variables that tell webpack to compile on error:

```sh
ESLINT_NO_DEV_ERRORS=true
TSC_COMPILE_ON_ERROR=true
```

## Expected Behavior
Should warn about error in console and terminal, but NOT crash

## Steps to Reproduce
1. create new workspace
2. put TS/lint error in the code
3. run in terminal and watch the build crash

### Environment

```
$ npx nx report


 >  NX   Report complete - copy this into the issue template

   Node : 17.6.0
   OS   : darwin arm64
   yarn : 1.22.18

   nx : 14.4.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.4.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.3
   @nrwl/eslint-plugin-nx : 14.4.3
   @nrwl/express : 14.4.3
   @nrwl/jest : 14.4.3
   @nrwl/js : 14.4.3
   @nrwl/linter : 14.4.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.4.3
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.4.3
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.3
   @nrwl/web : 14.4.3
   @nrwl/workspace : 14.4.3
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:

```

**Comment by Ofadiman** [comment]
Possibly resolved [here](https://github.com/nrwl/nx/issues/11536#issuecomment-1304493470).

**Comment by goldylucks** [comment]
continuing there, sorry for multiple issues 🤦‍♀️
