### ISSUE TITLE
Nx graph not generating dependency graph

### ISSUE THREAD

**Issue by Tex-Tang** [nrwl/nx#12501]
## Current Behavior
![image](https://user-images.githubusercontent.com/14901260/195038538-e837a2d2-2ee2-4160-bf1a-d490ac47f915.png)

## Expected Behavior
It should be a tree

## Steps to Reproduce

Run `nx reset`
Run `nx graph`

### Environment

```

 >  NX   Report complete - copy this into the issue template

   Node : 16.15.0
   OS   : darwin arm64
   npm  : 8.5.5
   
   nx : 14.8.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.8.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.2
   @nrwl/js : 14.8.2
   @nrwl/linter : 14.8.2
   @nrwl/nest : Not Found
   @nrwl/next : 14.8.2
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.7.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.8.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : 14.8.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.2
   @nrwl/web : 14.8.2
   @nrwl/webpack : 14.8.2
   @nrwl/workspace : 14.8.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by ajwootto** [comment]
seeing the same thing

**Comment by ajwootto** [comment]
@Tex-Tang this fixed it for me, maybe it will help
https://github.com/nrwl/nx/issues/10785#issuecomment-1158916416

opened an issue about it here
https://github.com/nrwl/nx/issues/12583

**Comment by Tex-Tang** [comment]
Thanks @ajwootto. Unfortunately, that doesn't solve the issue. The graph still showing no relationship at all. My temporary solution is run `nx graph --watch` and save all the files to trigger `Recalculating project graph...`. However, I need to keep doing this process if I terminated the `nx graph --watch` command.

**Comment by FrozenPandaz** [comment]
`nx graph` works for me on multiple repos.

@Tex-Tang can you please provide a repro where we can see the issue?

What is your `nx.json` configuration?

**Comment by kaltepeter** [comment]
I hit this same issue with nx version 14.8.2. I ran the upgrade and migrations to nx version 14.8.6, resolving the graph issue.

My repo was created with: `14.5.4`, configured with the empty apps preset (i think)

And run the migrations to `14.8.2` at a later date.
