### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by B1Z1** [nrwl/nx#12503]
Hi, sometimes on our CI NX throws an error. If you need more information from us, I can try to send you

## Current Behavior
NX Randomly throws an error on clean CI instance

## Expected Behavior
There are no random errors

## Steps to Reproduce
I don't know how to prepare repro steps. Small repository works well, but here's 300+ libraries and it's difficult to prepare repro steps

### Failure Logs

[2022-10-11T07:32:34.288Z]    Nx read the output from the cache instead of running the command for 243 out of 250 tasks.
[2022-10-11T07:32:34.288Z] 
[2022-10-11T07:32:34.288Z]    Nx Cloud made it possible to reuse 220 tasks: https://cloud.nx.app/runs/PcMlzby6D0q
[2022-10-11T07:32:34.288Z] 
[2022-10-11T07:32:34.288Z] 
[2022-10-11T07:32:34.288Z]  >  NX   ENOENT: no such file or directory, chmod '/home/ubuntu/workspace/PPM/REVIEW/FRONTEND_TESTS/ui/dist/libs/ppm/schedule/schedule-skeleton/esm2020/lib/ui/BoxSkeletonReadinessService.mjs'

### Environment

Node : 16.16.0
OS : darwin arm64
yarn : 1.22.4

nx : 14.7.13
@nrwl/angular : 14.7.13
@nrwl/cypress : 14.7.13
@nrwl/detox : Not Found
@nrwl/devkit : 14.7.13
@nrwl/eslint-plugin-nx : 14.7.13
@nrwl/expo : Not Found
@nrwl/express : Not Found
@nrwl/jest : 14.7.13
@nrwl/js : 14.7.13
@nrwl/linter : 14.7.13
@nrwl/nest : 14.7.13
@nrwl/next : Not Found
@nrwl/node : 14.7.13
@nrwl/nx-cloud : 14.6.2
@nrwl/nx-plugin : Not Found
@nrwl/react : Not Found
@nrwl/react-native : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : 14.7.13
@nrwl/web : 14.7.13
@nrwl/workspace : 14.7.13
typescript : 4.7.4
Local workspace plugins:
Community plugins:
@ngneat/transloco: 4.1.1
@ngrx/effects: 12.5.0
@ngrx/entity: 12.4.0
@ngrx/store: 12.5.0
@ngrx/store-devtools: 12.5.0
@rx-angular/cdk: 1.0.0-rc.1
@rx-angular/state: 1.6.0
@rx-angular/template: 1.0.0-beta.32
@storybook/angular: 6.5.12
@testing-library/angular: 11.0.4

**Comment by FrozenPandaz** [comment]
Sorry, I don't think there's enough information here for us to help.

I was able to view your Nx Cloud run and saw that that project was built to a different place than where your error message is referring to.

```diff
- /home/ubuntu/workspace/PPM/REVIEW/BUILD/ui/dist/libs/ppm/schedule/schedule-skeleton
+ /home/ubuntu/workspace/PPM/REVIEW/FRONTEND_TESTS/ui/dist/libs/ppm/schedule/schedule-skeleton
```

Does this perhaps help you? What commands are you running here?
