### ISSUE TITLE
Error: Project name already exists.

### ISSUE THREAD

**Issue by pegaltier** [nrwl/nx#12509]
## Current Behavior
Error: Project name already exists.

## Expected Behavior
test-nx-lib-2 should be created

## Steps to Reproduce
nx generate @nrwl/angular:library test-nx-lib-1 --style=scss --no-interactive 
nx generate @nrwl/angular:library test-nx-lib-2 --style=scss --no-interactive 

### Failure Logs
➜  test-nx-14 nx generate @nrwl/angular:library test-nx-lib-2 --style=scss --no-interactive 

>  NX  Generating @nrwl/angular:library

Error: Project name already exists.
    at ProjectDefinitionCollection.add (/Users/pierre-ed.galtier/Documents/repositories/experiments/test-nx-14/node_modules/@angular-devkit/core/src/workspace/definitions.js:89:19)
    at /Users/pierre-ed.galtier/Documents/repositories/experiments/test-nx-14/node_modules/@schematics/angular/library/index.js:64:28
    at /Users/pierre-ed.galtier/Documents/repositories/experiments/test-nx-14/node_modules/@schematics/angular/utility/workspace.js:55:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async callRuleAsync (/Users/pierre-ed.galtier/Documents/repositories/experiments/test-nx-14/node_modules/@angular-devkit/schematics/src/rules/call.js:78:18)

**Comment by FrozenPandaz** [comment]
These 2 names are normalized to the same name:

```
test-nx-lib-1 => test-nx-lib
test-nx-lib-2 => test-nx-lib
```

If you use these names instead, they will not be normalized to the same thing.

```
test-nx-lib1 => test-nx-lib1
test-nx-lib2 => test-nx-lib2
```

**Comment by mandarini** [comment]
I will be closing this, since it has a simple straightforward workaround that makes sense!
