### ISSUE TITLE
'nx serve' is not serving assets from other libraries

### ISSUE THREAD

**Issue by anthodb** [nrwl/nx#12522]
## Current Behavior

I just migrated to nx 14.8.3.
Previous was 14.4.0

I'm serving my application using this command:
```
nx myapp:serve:development
```

This is the project.json inside myapp :

```
"targets": {
    "build": {
      "executor": "@nrwl/next:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "dependsOn": [],
      "options": {
        "root": "apps/myapp",
        "outputPath": "dist/apps/myapp",
        "assets": [
          {
            "glob": "**/*",
            "input": "libs/auth/public/html",
            "output": "html"
          },
          {
            "glob": "**/*",
            "input": "libs/shared-ui/public/fonts",
            "output": "fonts"
          },
          {
            "glob": "**/*",
            "input": "libs/i18n/public/locales",
            "output": "locales"
          },
          {
            "glob": "**/*",
            "input": "libs/shared-ui/public/images",
            "output": "images"
          },
          {
            "glob": "**/*",
            "input": "libs/shared/public/images",
            "output": "images"
          }
        ]
      },
      "configurations": {
        "development": {},
        "production": {}
      }
    },
"serve": {
      "executor": "@nrwl/next:server",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "myapp:build",
        "port": 3000
      },
      "configurations": {
        "development": {
          "buildTarget": "myapp:build:development",
          "dev": true
        },
        "production": {
          "buildTarget": "myapp:build:production",
          "dev": false
        }
      }
    }
}
```

## Issue

The dev application is not serving anymore the asset files from other libraries. (logo, fonts, etc..)

## Expected Behavior
It was correctly serving the asset files from other libraries before (last version working was 14.4.0)
I tested all nx imports and the @nrwl/nx is creating the issue starting, all other libs can be updated to 14.8.3.

## Environment

NX   Report complete - copy this into the issue template

 Node : 16.13.2
 OS   : darwin x64
 npm  : 8.8.0
 
 nx : 14.8.3
 @nrwl/angular : Not Found
 @nrwl/cypress : 14.8.3
 @nrwl/detox : Not Found
 @nrwl/devkit : 14.4.0
 @nrwl/esbuild : Not Found
 @nrwl/eslint-plugin-nx : 14.8.3
 @nrwl/expo : Not Found
 @nrwl/express : Not Found
 @nrwl/jest : 14.8.3
 @nrwl/js : 14.4.0
 @nrwl/linter : 14.8.3
 @nrwl/nest : Not Found
 @nrwl/next : 14.8.3
 @nrwl/node : Not Found
 @nrwl/nx-cloud : Not Found
 @nrwl/nx-plugin : Not Found
 @nrwl/react : 14.8.3
 @nrwl/react-native : Not Found
 @nrwl/rollup : 14.8.3
 @nrwl/schematics : Not Found
 @nrwl/storybook : 14.8.3
 @nrwl/web : 14.8.3
 @nrwl/webpack : 14.8.3
 @nrwl/workspace : 14.8.3
 typescript : 4.7.3
 ---------------------------------------
 Local workspace plugins:
 ---------------------------------------
 Community plugins:

**Comment by alexfreska** [comment]
Hey @anthodb, few people with related problems commenting on this closed issue: https://github.com/nrwl/nx/issues/11524

**Comment by asotog** [comment]
we are facing same issue, we have images at root level, that are shared between apps, after upgrading they are broken, `serve` command seems only service from app scope, not from dist scope as well

**Comment by FrozenPandaz** [comment]
I reopened https://github.com/nrwl/nx/issues/11524. I'm going to close this as a duplicate.
