### ISSUE TITLE
Nx graph not starting server nor providing an error message

### ISSUE THREAD

**Issue by keygjones** [nrwl/nx#12547]
## Current Behavior
nx graph 
NX   Project graph started at http://127.0.0.1:4211 <- This is a lie :)
there is no server listening on the port... according to browser and netstat -a 
Tried nx repair and deamon reset

## Expected Behavior
Should start the server or show a error message with a cause explaining why

### Failure Logs
[NX Daemon Server] - 2022-10-12T11:46:08.878Z - Done responding to the client project-graph
[NX Daemon Server] - 2022-10-12T11:46:09.071Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2022-10-12T11:46:09.071Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2022-10-12T11:46:09.072Z - Time taken for 'total for creating and serializing project graph' 0.20159999933093786ms
[NX Daemon Server] - 2022-10-12T11:46:09.072Z - Done responding to the client project-graph
[NX Daemon Server] - 2022-10-12T11:46:09.096Z - Closed a connection

### Environment

   Node : 16.15.1
   OS   : win32 x64
   npm  : 8.11.0

   nx : 14.7.8
   @nrwl/angular : 14.7.8
   @nrwl/cypress : 14.7.8
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.8
   @nrwl/eslint-plugin-nx : 14.7.8
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.8
   @nrwl/js : 14.7.8
   @nrwl/linter : 14.7.8
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.6.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.8
   @nrwl/web : Not Found
   @nrwl/workspace : 14.7.8
   typescript : 4.7.2
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @compodoc/compodoc: 1.1.19
         @datorama/akita: 6.2.4
         @jscutlery/semver: 2.27.0
         @twittwer/compodoc: 1.5.3
         nx-stylelint: 13.3.0

**Comment by FrozenPandaz** [comment]
This was fixed in `14.7.11` via https://github.com/nrwl/nx/pull/12189. Please update your nx version and this will be fixed.
