### ISSUE TITLE
Docs: lazy routing

### ISSUE THREAD

**Issue by danieldanielecki** [nrwl/nx#1255]
## Expected Behavior

Have a clear steps how to proceed with lazy routing in Nx environment.

## Current Behavior

Couldn't find anything in the new docs, please see [this answer](https://github.com/nrwl/nx/issues/255#issuecomment-483239603) for more details.

**Comment by SebasG22** [comment]
@danieldanielecki I will submit a pr to have a dedicated section for this soon.

**Comment by vsavkin** [comment]
Merged the docs some time ago. Thanks!
