### ISSUE TITLE
Lib with the character '#' not show full how using it in the dep-graph

### ISSUE THREAD

**Issue by meifif** [nrwl/nx#12567]
## Current Behavior
A lib with # in the name (for being first in the import order), break the dependencies chain (for test and build)

## Expected Behavior
that the lib will act like any affected lib and will have a full dependencies chain 

## Steps to Reproduce
take a lib that is in use and has a chain of dependencies :
![image](https://user-images.githubusercontent.com/32955348/195584139-0585f285-baf6-4410-bd20-d7398949d0fa.png)

change the name to start with # and re-run the dep-graph

from the tsconfig.base.json file :
![image](https://user-images.githubusercontent.com/32955348/195584604-67a3dcd1-4abb-48f6-b581-653abee0151d.png)

you can see that now the lib that uses that will not be in the dep-graph as dependencies:
![image](https://user-images.githubusercontent.com/32955348/195584480-38a11274-638e-4e8d-9332-77279880cf70.png)

### Environment

```
 >  NX   Report complete - copy this into the issue template

   Node : 14.17.0
   OS   : darwin x64
   yarn : 1.22.19
   
   nx : 14.4.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.2
   @nrwl/eslint-plugin-nx : 14.4.2
   @nrwl/express : 14.4.2
   @nrwl/jest : 14.4.2
   @nrwl/js : 14.4.2
   @nrwl/linter : 14.4.2
   @nrwl/nest : 14.4.2
   @nrwl/next : 14.4.2
   @nrwl/node : 14.4.2
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.4.2
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.2
   @nrwl/web : 14.4.2
   @nrwl/workspace : 14.4.2
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
         @nx-aws-plugin/nx-aws-cache: 1.1.0
```

**Comment by FrozenPandaz** [comment]
Can you provide a repo that we can use to reproduce this issue please?

Did you only change the path in `tsconfig.base.json`? Did you also change the name in the library's `project.json` or `workspace.json`? It is not the path in `tsconfig.base.json` but the path in the `project.json`/`workspace.json` that determines the project's name in the graph.
