### ISSUE TITLE
Migration failure causing nx dependency graph to break

### ISSUE THREAD

**Issue by ajwootto** [nrwl/nx#12583]
## Current Behavior
In two separate Nx repositories, when I've upgraded to newer versions (most recently from 14.1.4 to 14.8.3) there ends up being an issue with the migrations which causes the whole Nx dependency graph to break for unclear reasons (eg. when I run `nx dep-graph` it just shows a large flat list of all my packages rather than a tree). Another symptom is that the `package.json` output of the built package / application (when using the generatePackageJson option) ends up with a blank dependencies list.

The fix for the problem appears to be this
https://github.com/nrwl/nx/issues/10785#issuecomment-1158916416

While I managed to track this down both times after several hours of troubleshooting, it seems like Nx should be fixing this scenario with a migration that corrects the problem. I don't fully understand what migration caused the original issue since it isn't mentioned in that comment.

## Expected Behavior

`nx migrate` should result in a working repository after migrations are finished.

Whatever migration issue caused this issue to begin with should be retroactively fixed by a new migration.

## Steps to Reproduce

It's not exactly clear what versions or upgrade paths have caused this issue, all I can say is that I've now run into it twice on two separate repositories which were updated at different times through different versions of Nx. It seems like others will run into this to, and the symptom of it is basically that Nx becomes silently nonfunctional with no error messages.

### Environment

```

   Node : 16.17.0
   OS   : darwin arm64
   yarn : 3.1.0

   nx : 14.8.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.8.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.3
   @nrwl/expo : Not Found
   @nrwl/express : 14.8.3
   @nrwl/jest : 14.8.3
   @nrwl/js : 14.8.3
   @nrwl/linter : 14.8.3
   @nrwl/nest : 14.8.3
   @nrwl/next : Not Found
   @nrwl/node : 14.8.3
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 14.8.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 14.8.3
   @nrwl/webpack : 14.8.3
   @nrwl/workspace : 14.8.3
   typescript : 4.8.4
```

Edit: After discussions on Slack, the problem appears to be specifically with the migration to 14.2 that was meant to enable analyzeSourceFiles for nx repos that extend the `npm` preset. The default value for that was changed to `false` in 14.2, so a migration was supposed to add the `true` setting back in to maintain backwards compatibility. However, in my case this migration did not appear to work.

**Comment by FrozenPandaz** [comment]
I generated a new 14.1.4 workspace with `npx create-nx-workspace@14.1.4 --preset core` and then ran the migrations via `npm i && nx migrate latest && nx migrate --run-migrations` and the following config was added successfully. Can you share your repo before migrating? Or at least an `nx.json` file? There is a migration that should happen when moving to or past `14.2.0`.

```
  "pluginsConfig": {
    "@nrwl/js": {
      "analyzeSourceFiles": true
    }
  }
```

**Comment by ajwootto** [comment]
@FrozenPandaz there was a discussion about this in Slack 
https://nrwlcommunity.slack.com/archives/CMFKWPU6Q/p1665690716270709

My understanding is that this only would affect repos where the nx.json extends from the `npm.json` preset (which it did in my case).
