### ISSUE TITLE
depConstraint with empty "onlyDependOnLibsWithTags" passes linting

### ISSUE THREAD

**Issue by quoctintran** [nrwl/nx#12597]
## Current Behavior
A depConstraint defined as 
`{
                "sourceTag": "scope:projectA",
                "onlyDependOnLibsWithTags": []
              }`
pass linting even if the project with tag "scope:projectA" depends on other projects with tags.

## Expected Behavior
Linting should fail if projectA depends on other projects and the defined constraint shows an empty array for the property "onlyDependOnLibsWithTags".
I dig into the code and I've seen that version 13.8.5 was the last working version with the expected behavior.
I guess this PR introduced the change of behavior: https://github.com/nrwl/nx/pull/8633

## Steps to Reproduce
1. create new nx workspace with `npx create-nx-workspace` (angular preset, scss and no Nx cloud)
2. create first lib: `npx nx g @nrwl/angular:lib projectA --tags "scope:projectA"`
3. create second lib: `npx nx g @nrwl/angular:lib projectB --tags "scope:projectB"`
4. replace the default depConstraint in the root .eslintrc.json with
```
              {
                "sourceTag": "scope:projectA",
                "onlyDependOnLibsWithTags": []
              },
              {
                "sourceTag": "scope:projectB",
                "onlyDependOnLibsWithTags": []
              }
```
5. In the projectA.module.ts file import the projectB module
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ProjectBModule } from '@eap1386/projectB';

@NgModule({
  imports: [CommonModule, ProjectBModule],
})
export class ProjectAModule {}
```

### Environment
```
❯ npx nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.17.0
   OS   : win32 x64
   npm  : 8.15.0

   nx : 13.8.6
   @nrwl/angular : 13.8.6
   @nrwl/cli : 13.8.6
   @nrwl/cypress : 13.8.6
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.6
   @nrwl/eslint-plugin-nx : 13.8.6
   @nrwl/express : undefined
   @nrwl/jest : 13.8.6
   @nrwl/js : undefined
   @nrwl/linter : 13.8.6
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.6
   @nrwl/tao : 13.8.6
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.6
   typescript : 4.5.5
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
         @angular/animations: 13.2.7
         @angular/common: 13.2.7
         @angular/compiler: 13.2.7
         @angular/core: 13.2.7
         @angular/forms: 13.2.7
         @angular/platform-browser: 13.2.7
         @angular/platform-browser-dynamic: 13.2.7
         @angular/router: 13.2.7
         @angular-devkit/build-angular: 13.2.6
         @angular/cli: 13.2.6
         @angular/compiler-cli: 13.2.7
         @angular/language-service: 13.2.7
```

What is the intention if "onlyDependOnLibsWithTags" is an empty array? In my interpretation it says that the project with the defined tag can't depend on other projects (if you can say 'depend on anything with "*"'). It may refer to #11236

Thank you for reviewing!

**Comment by meeroslav** [comment]
This only functioned in the past because there was an error. The `onlyDependOnLibsWithTags` was never designed to be empty. But it makes sense. The behavior, in that case, would be:

A package that `onlyDependsOnLibsWithTags: []` can only depend on libs that have no tags.

We do strongly discourage having projects with no tags, as it can lead to a lot of different issues and the whole rule starts to lose its purpose. But for the sake of feature completeness, we will add the above-mentioned logic to empty `onlyDependOnLibsWithTags`.
