### ISSUE TITLE
Testing Error/undo response

### ISSUE THREAD

**Issue by phsims** [nrwl/nx#126]
Ho would you go about testing the undoAction/onError in effects?

**Comment by Yonet** [comment]
You can check the how we test it here: https://github.com/nrwl/nx/blob/master/packages/nx/spec/data-persistence.spec.ts

**Comment by jasedwards** [comment]
I took a look at the link you posted above but am having trouble testing one of my effects.  It has an if statement in it and checks the state.  I thought I could just pass in two actions.  the first ends up setting the flag that I look at and the 2nd is what actually calls the effect.  Is there a way for me to do something with the state before calling the effect?  this is what my run method looks like.  this is a feature module.

 ```
run: (action: LoadDashboardMessages, state: DashboardsState) => {
      if (state.isLoaded) {
        return empty();
      }

      return this.service
        .fetchDashboardMessages()
        .pipe(map(messages => ({ type: DASHBOARD_MESSAGES_LOADED, payload: messages })));
    },
```
