### ISSUE TITLE
nx commands can't be used without npx in new apps workspace

### ISSUE THREAD

**Issue by geromegrignon** [nrwl/nx#12636]
## Current Behavior

By using a nx command like `nx g @nrwl/angular:app appName` in a 15 nx workspace created with `preset=apps` fails with a `The current directory isn't part of an Nx workspace.` error log.

By using `npx`, like`npx nx g @nrwl/angular:app appName`, it works.
I had to use npx for the `nx report` output too for this issue.

I can't reproduce it on a workspace created with the `preset=angular`option directly.

## Expected Behavior

The generator should create the application without `npx`.

## Steps to Reproduce

- Create a nx workspace with `npx create-nx-workspace --preset=apps`
- add angular package `npm install -D @nrwl/angular`
- create an angular application with `nx g @nrwl/angular:app appName`
- the generation fails with a `The current directory isn't part of an Nx workspace.`

Reproductible with express package as well.

### Failure Logs

`The current directory isn't part of an Nx workspace.`

### Environment

```
 Node : 16.16.0
   OS   : darwin x64
   npm  : 8.11.0
   
   nx : 15.0.0
   @nrwl/angular : 15.0.0
   @nrwl/cypress : 15.0.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.0
   @nrwl/expo : Not Found
   @nrwl/express : 15.0.0
   @nrwl/jest : 15.0.0
   @nrwl/js : 15.0.0
   @nrwl/linter : 15.0.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.0.0
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.0
   @nrwl/web : Not Found
   @nrwl/webpack : 15.0.0
   @nrwl/workspace : 15.0.0
   typescript : 4.8.4

```

**Comment by AgentEnder** [comment]
Hey 👋 

Can you check the version of your global nx install? It's likely out of date and failing because `workspace.json` doesn't exist.
