### ISSUE TITLE
404 on project-graph-plugins and project-inference-plugins page

### ISSUE THREAD

**Issue by PowerSupply** [nrwl/nx#12635]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[/recipe/project-graph-plugins](https://nx.dev/recipe/project-graph-plugins)
[/recipe/project-inference-plugins](https://nx.dev/recipe/project-inference-plugins)

**Comment by AgentEnder** [comment]
Those pages were moved. Since the links were not alive for very long, we have made the decision to not set up redirects as there is a maintenance burden associated. Here is the new location: https://nx.dev/recipes/advanced-plugins
