### ISSUE TITLE
Nx Expo not working with PNPM ?

### ISSUE THREAD

**Issue by fortezhuo** [nrwl/nx#12639]
## Current Behavior

An error "Cannot resolve domelementtype" occurs while run expo using nx with PNPM package manager

## Expected Behavior
Should run fine using PNP

## Steps to Reproduce

1. Create blank workspace using ```npx create-nx-workspace nx-expo-poetry --packageManager=pnpm ```
2. Run ```pnpm add @nrwl/expo -D```
3. Run ```nx generate @nrwl/expo:app poetry-app```
4. Add ```nx start poetry-app``` to package json script, let say "start"
5. Run ```pnpm start```
6. Will trigger error need to resolve ```@babel/runtime```, so I install ```@babel/runtime```
7. Run again to get error like captured image

### Failure Logs
![image](https://user-images.githubusercontent.com/9128724/195986018-feb5f18d-cb2b-4631-a51d-3c7d4d87e894.png)

### Environment

```
Node : 16.15.0
   OS   : darwin x64
   pnpm : 7.13.4
   
   nx : 15.0.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.0
   @nrwl/detox : 15.0.0
   @nrwl/devkit : 15.0.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.0
   @nrwl/expo : 15.0.0
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.0
   @nrwl/js : 15.0.0
   @nrwl/linter : 15.0.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.7.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.0
   @nrwl/web : 15.0.0
   @nrwl/webpack : 15.0.0
   @nrwl/workspace : 15.0.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

Link to https://github.com/xiongemi/nx-expo-poetry/issues/4

**Comment by fortezhuo** [comment]
I have solved this problem with add .npmrc file with config

```
strict-peer-dependencies=false
auto-install-peers=true
node-linker=hoisted 
```

**Comment by leggomuhgreggo** [comment]
Here's a [related discussion](https://github.com/nrwl/nx-labs/issues/34) that people running into this may find useful.
