### ISSUE TITLE
Explain options for creating custom workspace generators

### ISSUE THREAD

**Issue by jharrisonio** [nrwl/nx#12644]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?
 - [@nrwl/workspace:workspace](https://nx.dev/packages/workspace/generators/workspace)

### Additional context or description
I'm looking to create a custom workspace generator and I'm finding it hard to find a definitive approach to this. It seems the options are:
1. [Use create-nx-plugin](https://nx.dev/packages/nx-plugin#preset) with a generator called `preset`
2. Use [@nrwl/workspace:workspace-generator](https://nx.dev/packages/workspace/generators/workspace-generator#@nrwl/workspace:workspace-generator) to generate a workspace generator

Can anyone help me understand the differences?

**Comment by AgentEnder** [comment]
Hey 👋, I can understand how this was confusing.

`[@nrwl/workspace:workspace-generator](https://nx.dev/packages/workspace/generators/workspace-generator#@nrwl/workspace:workspace-generator)` creates a generator in the workspace, not a generator that creates a workspace.
