### ISSUE TITLE
After NX15 upgrade, docker image is not building because of esbuild 

### ISSUE THREAD

**Issue by jbarmash** [nrwl/nx#12642]
## Current Behavior

After upgrading to NX 15.0, the docker build stopped working.   We are using node:18.11-alpine3.16 on AWS linux. 

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/53616/195994606-c3e77f79-b776-4ccf-9ea4-7b7d2344742c.png">

## Expected Behavior
This is a regression, the only change is upgrading to nx 15. 

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

---> Running in affefbe933c6
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @esbuild/linux-loong64@0.15.5: wanted {"os":"linux","arch":"loong64"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  loong64
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

### Environment

KEEP IN MIND, this is a BUILD issue, so the OS is linux.x64, but here is my local.  ESBuild is installed locally only currently.  

Node : 16.16.0
   OS   : darwin arm64
   npm  : 8.11.0

   nx : 15.0.0
   @nrwl/angular : 15.0.0
   @nrwl/cypress : 15.0.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.0
   @nrwl/esbuild : 15.0.0
   @nrwl/eslint-plugin-nx : 15.0.0
   @nrwl/expo : Not Found
   @nrwl/express : 15.0.0
   @nrwl/jest : 15.0.0
   @nrwl/js : 15.0.0
   @nrwl/linter : 15.0.0
   @nrwl/nest : 15.0.0
   @nrwl/next : Not Found
   @nrwl/node : 15.0.0
   @nrwl/nx-cloud : 14.7.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.0
   @nrwl/web : Not Found
   @nrwl/webpack : 15.0.0
   @nrwl/workspace : 15.0.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @compodoc/compodoc: 1.1.19
   	 @trumbitta/nx-plugin-unused-deps: 1.12.1

➜  monorepo git:(jbarmash-nx-followup-build-fix) ✗ d

**Comment by jenjen75** [comment]
It look likes `createPackageJson` in v15 generate package.json file with all depedencies flattened. 

```
    "esbuild-android-64": "0.15.11",
    "esbuild-android-arm64": "0.15.11",
    "esbuild-darwin-64": "0.15.11",
    "esbuild-darwin-arm64": "0.15.11",
    "esbuild-freebsd-64": "0.15.11",
    "esbuild-freebsd-arm64": "0.15.11",
    "esbuild-linux-32": "0.15.11",
    "esbuild-linux-64": "0.15.11",
    "esbuild-linux-arm": "0.15.11",
    "esbuild-linux-arm64": "0.15.11",
    "esbuild-linux-mips64le": "0.15.11",
    "esbuild-linux-ppc64le": "0.15.11",
    "esbuild-linux-riscv64": "0.15.11",
    "esbuild-linux-s390x": "0.15.11",
    "esbuild-netbsd-64": "0.15.11",
    "esbuild-openbsd-64": "0.15.11",
    "esbuild-sunos-64": "0.15.11",
    "esbuild-windows-32": "0.15.11",
    "esbuild-windows-64": "0.15.11",
    "esbuild-windows-arm64": "0.15.11",
```

But esbuild should not appear in package.json, because everything are declared in devDepedencies.

```
jeanjean@Jean-mi-vivlab vivlab % npm ls esbuild           
vivlab@0.0.0 /Users/jeanjean/vivlab/vivlab
├─┬ @esbuild-kit/esm-loader@2.5.0
│ └─┬ @esbuild-kit/core-utils@3.0.0
│   └── esbuild@0.15.11 deduped
├─┬ esbuild-register@3.3.3
│ └── esbuild@0.15.11 deduped
├── esbuild@0.15.11
└─┬ vite@3.1.8
  └── esbuild@0.15.11 deduped
````

**Comment by derekkite** [comment]
Same thing with a node app in docker

**Comment by mehrad-rafigh** [comment]
@AgentEnder any timeline when this will be addressed by the NX team?

**Comment by mehrad-rafigh** [comment]
@meeroslav I would love to check that out. Since that PR isn't merged yet, how can I test that?

**Comment by meeroslav** [comment]
Go to node_modules/@nrwl/workspace/src/utilities/create-package-json.js and add wrap lines 57-59 in `else` branch.

**Comment by mehrad-rafigh** [comment]
@meeroslav yes that solves the issue! Thank you very much and looking forward to have that released
