### ISSUE TITLE
Explain duplicate commands for creating workspaces

### ISSUE THREAD

**Issue by jharrisonio** [nrwl/nx#12643]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?
- [Getting Started with Package-Based Repos](https://nx.dev/getting-started/package-based-repo-tutorial)
- [create-nx-workspace](https://nx.dev/nx/create-nx-workspace)
- [nx g @nrwl/workspace:workspace](https://nx.dev/packages/workspace/generators/workspace)
- [nx g @nrwl/workspace:new](https://nx.dev/packages/workspace/generators/new)

### Additional context or description
 1. The getting started guide talks about using `create-nx-workspace`
 2. There are a couple of generators that seem to do the same thing, e.g.  `@nrwl/workspace:workspace` and @nrwl/workspace:new`

I've had a quick look through the source code but each option for creating a workspace seems to use different code, e.g. `create-nx-workspace` is not a CLI wrapper around the `@nrwl/workspace` generator. Can someone help me understand what the differences are between each of these?

**Comment by AgentEnder** [comment]
You shouldn't need to invoke the @nrwl/workspace:workspace or @nrwl/workspace:new generators. They are implementation details that we invoke during create-nx-workspace.
