### ISSUE TITLE
build error in new version @nrwl/angular ^v14.7-v15.0

### ISSUE THREAD

**Issue by himyjan** [nrwl/nx#12655]
## Steps to Reproduce

# repo
https://github.com/himyjan/analog/tree/patch-3

# pr
https://github.com/analogjs/analog/pull/110

```
yarn;yarn run build
```

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

@nrwl/angular package version
v14.6.4 build work

v14.7.18 build not work
v14.8.4 build not work
v15.0.0 build not work
<img width="589" alt="image" src="https://user-images.githubusercontent.com/51815522/194993304-3e76573e-7acb-45d8-ba62-ed5a00d746f2.png">
```
/Users/user/Desktop/analog/node_modules/@nrwl/js/src/utils/package-json/update-package-json.js:51
        exports['.']['require'] = cjsMain;
                                ^

TypeError: Cannot create property 'require' on string './src/index.js'
    at getUpdatedPackageJsonContent (/Users/user/Desktop/analog/node_modules/@nr
```

after comment code build work
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/51815522/196085881-c0fcd62e-8ead-44b7-a254-30ea74cfce5f.png">

### Environment

```
   Node : 18.11.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 15.0.0
   @nrwl/angular : 15.0.0
   @nrwl/cypress : 15.0.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.0
   @nrwl/js : 15.0.0
   @nrwl/linter : 15.0.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.0
   @nrwl/web : Not Found
   @nrwl/webpack : 15.0.0
   @nrwl/workspace : 15.0.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @nx-plus/docusaurus: 14.1.0
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

A fix has already been merged for it https://github.com/nrwl/nx/pull/12613 and it should be released soon. Please keep an eye on the releases to get it.
