### ISSUE TITLE
Don't use `identity-obj-proxy` by default in the jest resolver 

### ISSUE THREAD

**Issue by craigbilner** [nrwl/nx#12653]
- [ x ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Allow the ability to handle `.css`, `.scss`,`.sass`,`.less`, `.styl` extensions rather than early exit in the default `@nrwl/jest/plugins/resolver` with `identity-obj-proxy`.

## Motivation

Using `@vanilla-extract` requires a `jest-transform` of the `css` files but it' not possible to handle/transform them because the default nx resolver catches all `css` files.

## Suggested Implementation

The resolver logic already checks the resolver options which could be used to opt out of `identify-obj-proxy`

## Alternate Implementations

Don't default to `identity-obj-proxy` and instead provide that as boilerplate config which would be easier to discover/change

**Comment by barbados-clemens** [comment]
Hmm interesting. How would you imagine this api is working/configured? Initially having a way to extend the resolver with your own custom resolver makes the most sense to me but unsure if that's really useful or not.

**Comment by asherccohen** [comment]
Do you have any recommended config that is known to work?

**Comment by asherccohen** [comment]
Do we know what could be the required change?
We can open a PR, but a guidance over how to make it work is appreciated.

My tests are broken and my projects are on hold due to this.

**Comment by barbados-clemens** [comment]
my recommendation would be to implement your own custom resolver that handles the files you want, then calls the nrwl/jest resolver as the fallback logic. 


```ts

import nrwlResolver from '@nrwl/jest/plugins/resolver';

module.exports = function(path: string, options: ResolveOptions) {
  if(isCssFile(path)) {
    return handleCssFile(path, options);
  }

  return nrwlResolver(path, options);
}
```

because as far as I can tell there isn't a way to configure the resolver behaviors since jest takes a path/import to the resolver to use.

**Comment by asherccohen** [comment]
tx @barbados-clemens 

How would u use that?
I have this in
//jest.config.ts
```
/* eslint-disable */
export default {
  displayName: "impaqt-plus-ui",
  preset: "../../jest.preset.js",
  transform: {
    // "^(?!.*\\.(js|jsx|ts|tsx|css|json)$)": "@nrwl/react/plugins/jest", //disabled this
    "^.+\\.[tj]sx?$": ["babel-jest", { presets: ["@nrwl/react/babel"] }],
    "^(?!.*\\.(js|jsx|ts|tsx|css|json)$)": "<rootDir>/cssTransformer.js",
  },
  moduleFileExtensions: ["ts", "tsx", "js", "jsx"],
  coverageDirectory: "../../coverage/apps/impaqt-plus-ui",
  setupFiles: ["./src/app/setupMocks.ts"],
  setupFilesAfterEnv: ["./src/app/setupTests.ts"],
};

```


and this as a custom transformer:


//cssTransformer.js

```
const nrwlResolver = require("@nrwl/jest/plugins/resolver");
const path = require("path");
const transformer = require("@vanilla-extract/jest-transform");

module.exports = {
  process(sourceText, sourcePath, options) {
    // if this is a vanilla-extract css.ts file then pass it to the vanilla-extract transformer
    if (sourcePath.endsWith(".css.ts")) {
      return transformer.default.process(sourceText, sourcePath, {
        config: options,
      });
    }
    // otherwise, we just return a simple string that exports the filename because
    // we don't want any CSS being transformed in Jest
    return nrwlResolver(path, options);
  },
};

```

**Comment by barbados-clemens** [comment]
You're mixing a jest resolver and jest transformer. 

The error you're seeing is that the `return nrwlResolver(path,options);` returns a file path which is not a transformer object. So jest isn't happy with that.

You'll need to set up the custom jest resolver to not use `identify-obj-proxy` by returning the resolved path yourself first (probably just needs to use the default resolver from jest (`options.defaultResolver`) or at least that is the issues preventing from using vanilla-extract according to @craigbilner. I'm unfamiliar with the package. 

and then you'll need to apply whatever transformer logic to transform the css files for your project. which looks to be just the transformer from @vanilla-extract/jest-transform

**Comment by asherccohen** [comment]
Thanks again @barbados-clemens, I'm surely messing up thing.
I have little understanding of jest internals.

Is the config to be set at the root level or project level?

Any chance you have a way to show how/where exactly I should be using the resolver?

**Comment by barbados-clemens** [comment]
the resolver can be set at the project or global level.
depends on if you want it to applied to all projects or not. 

if you want to apply it to all projects, then you can pass it in the jest.preset.js (which get's applied to all project)

so in this case
```js
const nxPreset = require('@nrwl/jest/preset').default

module.exports = {
  ...nxPreset,
  resolver: 'path/to/your/custom-resolver.js'
}
```

in `custom-resolver.js`
```js
module.exports = function(path, options) {
  // run your resolver logic first to prevent nrwl resolver handling css files
  if(isCssFile(path)) {
    return resolveCssFile(path, options); // this is probably just going to be options.defaultResolver(path, options) but idk 🤷 
  }

  return nrwlResolver(path, options); // pass to the nrwl resolver to handle the rest of the stuff
}
```

then you also need to set up a transformer to handle your css files. so in your project level jest.config.ts
```ts
/* eslint-disable */
export default {
  displayName: "impaqt-plus-ui",
  preset: "../../jest.preset.js",
  transform: {
    // "^(?!.*\\.(js|jsx|ts|tsx|json)$)": "@nrwl/react/plugins/jest", //disabled this
    "^.+\\.[tj]sx?$": ["babel-jest", { presets: ["@nrwl/react/babel"] }],
    "^(?!.*\\.(js|jsx|ts|tsx|css|json)$)": "<rootDir>/cssTransformer.js",
  },
  moduleFileExtensions: ["ts", "tsx", "js", "jsx"],
  coverageDirectory: "../../coverage/apps/impaqt-plus-ui",
  setupFiles: ["./src/app/setupMocks.ts"],
  setupFilesAfterEnv: ["./src/app/setupTests.ts"],
};
```
now you'll need to setup the `cssTransformer.js` file. 

```js
const nrwlReactTransformer = require("@nrwl/react/plugins/jest");
const path = require("path");
const transformer = require("@vanilla-extract/jest-transform");

module.exports = {
  process(sourceText, sourcePath, options) {
    // if this is a vanilla-extract css.ts file then pass it to the vanilla-extract transformer
    if (sourcePath.endsWith(".css.ts")) {
      return transformer.default.process(sourceText, sourcePath, {
        config: options,
      });
    }

    // send to the nrwl transformer
    return nrwlReactTransformer(path, options);
  },
};
```

I _think_ this will work. might have typo'd something. but the gist is there. 

there are two places to setup the resolver (in the root jest.preset.js or project level jest.config.ts). 

then setup the css transformer in the project level jest.config.ts so that your css files are transformed correctly.

**Comment by asherccohen** [comment]
Awesome, that did the trick. I can now see that NX is going through my custom resolver and custom transformer.

Unfortunately it's still not picking up .css.ts files.

If I log the path in the resolver or the sourcePath in the transformer I never see it importing files with extension .css.ts.

To give you a bit a context, I've created a theme library to share tokens with multiple apps through react context and consuming them in styled-components.

So the error is something like:

//button.styled

...
color: theme.colors.primary
//Cannot read property undefined of "primary"
...


Could it be that the style imports are "hidden" and are not directly exposed to jest?
Is there some other config I have to propagate to the theme library itself?

Thanks!!!

**Comment by craigbilner** [comment]
@asherccohen for my workaround I just took NXs resolver, put it in root and changed this piece of code to not catch css files:

```
if (
        ext === '.scss' ||
        ext === '.sass' ||
        ext === '.less' ||
        ext === '.styl'
    ) {
        return require.resolve('identity-obj-proxy');
    }
```

Then added `resolver: '../../resolver.js',` to all our `jest.config.js` files

**Comment by asherccohen** [comment]
@craigbilner That's also a solution (the first I tried) but then normal .css imports are broken.

![image](https://user-images.githubusercontent.com/34692625/215711121-4d23edf6-bf13-4b00-94ef-3bf1e00e5fe7.png)

**Comment by jd-oconnor** [comment]
> @craigbilner That's also a solution (the first I tried) but then normal .css imports are broken.
> 
> ![image](https://user-images.githubusercontent.com/34692625/215711121-4d23edf6-bf13-4b00-94ef-3bf1e00e5fe7.png)
> 
> UPDATE: I probably know why I can't capture files with .css.ts extension, NX was complaining that I can't import files with .ts extension, so my VE imports didn't have them. If I ts-ignore that warning and change all imports, then my VE setup breaks:
> 
> ![image](https://user-images.githubusercontent.com/34692625/215715928-77d6365f-0b90-493d-9b43-82d02fd8eb27.png)
> 
> So now I'm even more confused.

For your storybook issue, you need to import your styles in your `preview.js` file. 

I recommend updating SB to v7 if you aren’t already

`npx storybook@next upgrade --prerelease`

That will upgrade you to the latest beta version and offer some automigrations, to handle most/all of the breaking changes. If that’s not an option, I included the links for both the v6 and v7 docs below. Hope that helps!

Styling and CSS docs:
[v6.5](https://storybook.js.org/docs/react/configure/styling-and-css)

[v7](https://storybook.js.org/docs/7.0/react/configure/styling-and-css)

**Comment by asherccohen** [comment]
That part I was able to workaround, no big deal, I disabled the import and I was able to progress, so that's not the blocker at the moment.

I'm still at not being able to capture .css.ts file paths, because NX flags a ts error about importing .ts files,
When I update the imports to include .css.ts and ts-ignore it, I'm back to VE error shared above.

**Comment by craigbilner** [comment]
@asherccohen just to double check have you followed the config from the [docs](https://vanilla-extract.style/documentation/test-environments/) which is what transforma your vanilla files. You can then use indentity-obj-proxy for your plain css files with another regex matcher

**Comment by asherccohen** [comment]
Sure, here's my custom webpack config (with a few other workarounds due to other issues in NX):


```
const { merge } = require("webpack-merge");
const NodePolyfillPlugin = require("node-polyfill-webpack-plugin");
const { VanillaExtractPlugin } = require("@vanilla-extract/webpack-plugin");

module.exports = (config, context) => {
  // eslint-disable-next-line no-console
  console.log("🚀 ~ Loading Custom Webpack");

  //AC: Workaround for images not being loaded due to webpack 5 changes. https://github.com/nrwl/nx/issues/14532
  // eslint-disable-next-line no-param-reassign
  config.module.rules = config.module.rules.map((rule) => {
    if (/file-loader/.test(rule.loader)) {
      return {
        ...rule,
        test: /\.(eot|cur|jpg|png|webp|gif|otf|ttf|woff|woff2|ani)$/, //
        type: "javascript/auto", // This is fixing issue https://webpack.js.org/guides/asset-modules/
      };
    }

    return rule;
  });

  const newConfig = merge(config, {
    module: {
      rules: [
        {
          //AC: Testing that this works on its own
          test: /\.(pdf)$/,
          type: "asset/resource",
        },
        {
          test: /\.svg$/,
          use: ["@svgr/webpack", "url-loader"],
          type: "javascript/auto",
        },
      ],
    },
    resolve: {
      fallback: {
        fs: false,
      },
    },
    //AC: Workaround for https://github.com/nrwl/nx/issues/14389
    plugins: [
      new NodePolyfillPlugin(),
      new VanillaExtractPlugin()
    ],
    //AC: Workaround for https://stackoverflow.com/questions/70449352/reactstrap-typescript-nx-uncaught-referenceerror-global-is-not-defined
    node: {
      global: true,
    },
  });

  return newConfig;
};

```

The only difference in my setup is that I created a bit of an api to generate/override themes and light/dark modes.
I then expose them like explained here:

https://whoisryosuke.com/blog/2022/creating-a-design-system-using-vanilla-extract-css/

To give u an idea:

```
//dark-theme.css.ts
import { createTheme } from "@vanilla-extract/css";
import { vars } from "../theme-contract.css"; //this is where I can't define as .css.ts 
...other imports...

//Just my logic to override basic theme tokens
const darkTokens = {
  colors: overrideTokens(colors, overrides),
  lighting: overrideTokens(lighting, overrides),
  borders: overrideTokens(borders, overrides),,
};

const darkThemeClass = createTheme(vars, darkTokens);

export const dark = {
  class: darkThemeClass,
  tokens: vars,
};
```

Then export from my library as:
```
//theme.ts
import { base } from "./base.css";  //this is where I can't define as .css.ts 
import { dark } from "./dark-theme.css"; //this is where I can't define as .css.ts 
import { light } from "./light-theme.css"; //this is where I can't define as .css.ts 

export const theme = {
  base,
  light,
  dark,
};
```

All of this works flawlessly in the app.

**Comment by craigbilner** [comment]
Thanks, are we still talking about failing jest tests? The webpack config won't be involved. It should just work without your custom css transformer and using the vanilla jest tranformer out of the box, the altered NX resolver and a custom matcher for your css to use identity-object-proxy.

If you're still stuck we can check what your jest.config looks like

**Comment by asherccohen** [comment]
Thanks to you for the help.

Yes my problem is still with JEST tests failing.

I'm following @barbados-clemens suggestion.

https://github.com/nrwl/nx/issues/12653#issuecomment-1409076466

I also tried the combo together with the altered resolver.

Actually now that u mention the custom matcher, what would resolveCssFile do here?could this be the issue?

```
module.exports = function(path, options) {
  // run your resolver logic first to prevent nrwl resolver handling css files
  if(isCssFile(path)) {
    return resolveCssFile(path, options); // this is probably just going to be options.defaultResolver(path, options) is this correct?🤷 
  }

  return nrwlResolver(path, options); // pass to the nrwl resolver to handle the rest of the stuff
}
```

**Comment by craigbilner** [comment]
maybe try without the custom css matcher, just the documented vanilla config and another matcher for your css as that should just work

**Comment by asherccohen** [comment]
By matcher you mean resolver?
Could you show me an example please?

**Comment by asherccohen** [comment]
I apologize @craigbilner , is it possible to get an example of your last comment?

I didn't get the details of it.

Thanks.

**Comment by bart88** [comment]
I've been having the exact same issue with the jest resolver in an nx monorepo with vanilla-extract. 

@asherccohen  My solution was the same as @craigbilner. 

I ended up creating my own custom resolver and mostly copying the functionality of the resolver: 

I setup my jest-preset to point to my custom resolver:

```
const nxPreset = require("@nrwl/jest/preset").default;

module.exports = { ...nxPreset, resolver: "./jest-custom-resolver.js" };

```

and my jest-custom-resolver.js ended up like this : 

```
const pathModule = require("path");
const nrwlResolver = require("@nrwl/jest/plugins/resolver");
const resolveExports = require("resolve.exports");
let ts;
let compilerSetup;
function getCompilerSetup(rootDir) {
	const tsConfigPath =
		ts.findConfigFile(rootDir, ts.sys.fileExists, "tsconfig.spec.json") ||
		ts.findConfigFile(rootDir, ts.sys.fileExists, "tsconfig.test.json") ||
		ts.findConfigFile(rootDir, ts.sys.fileExists, "tsconfig.jest.json");
	if (!tsConfigPath) {
		console.error(
			`Cannot locate a tsconfig.spec.json. Please create one at ${rootDir}/tsconfig.spec.json`
		);
	}
	const readResult = ts.readConfigFile(tsConfigPath, ts.sys.readFile);
	const config = ts.parseJsonConfigFileContent(
		readResult.config,
		ts.sys,
		pathModule.dirname(tsConfigPath)
	);
	const compilerOptions = config.options;
	const host = ts.createCompilerHost(compilerOptions, true);
	return { compilerOptions, host };
}

module.exports = function (path, options) {
	// Handle css
	const extensionName = pathModule.extname(path);
	// Don't use the nrwl jest resolver directly, copy its functionality but ignore the top section
	if (extensionName === ".css") {
		try {
			try {
				return options.defaultResolver(path, options);
			} catch (e) {
				// Lets dive into the resolver here
				return options.defaultResolver(
					path,
					Object.assign(Object.assign({}, options), {
						pßackageFilter: (pkg) =>
							Object.assign(Object.assign({}, pkg), {
								main: pkg.main || pkg.es2015 || pkg.module,
							}),
						pathFilter: (pkg) => {
							if (!pkg.exports) {
								return path;
							}

							return resolveExports.resolve(pkg, path) || path;
						},
					})
				);
			}
		} catch (finalException) {
			if (
				path === "jest-sequencer-@jest/test-sequencer" ||
				path === "@jest/test-sequencer"
			) {
				return;
			}
			// Fallback to using typescript
			ts = ts || require("typescript");
			compilerSetup = compilerSetup || getCompilerSetup(options.rootDir);
			const { compilerOptions, host } = compilerSetup;
			return ts.resolveModuleName(
				path,
				options.basedir,
				compilerOptions,
				host
			).resolvedModule.resolvedFileName;
		}
	}

	// Pass to the nrwl transformer
	return nrwlResolver(path, options);
};

```

**Comment by asherccohen** [comment]
thanks @bart88. I assume u then also use the VE transformer like so:

![image](https://user-images.githubusercontent.com/34692625/218440369-8d551d43-5e25-4e59-ada2-060d730cace7.png)

When I do, I'm still getting the old issue I had:

![image](https://user-images.githubusercontent.com/34692625/218440495-3999107d-ee2e-4f93-b397-b56c6fa2efa5.png)

Any suggestion?

**Comment by bart88** [comment]
@asherccohen  Your regex for the jest-transform doesn't look quite right : 
```typescript
	transform: {
		'^.*\\.css\\.ts$': '@vanilla-extract/jest-transform',
                 "^(?!.*\\.(js|jsx|ts|tsx|css|json)$)": "@nrwl/react/plugins/jest",
		'^.+\\.(ts|tsx|js|jsx)$': ["babel-jest", { presets: ["@nrwl/react/babel"] }],
	},
```
Where are those errors coming from? Not sure if this is a configuration issue as the error messages themselves are coming from vanilla-extract so it looks like the transformer is working 🤷

**Comment by asherccohen** [comment]
Going crazy now :)

With that regex I still get
![image](https://user-images.githubusercontent.com/34692625/218702059-ed38cd6c-833b-4f93-b7a2-bc651958e958.png)


Let me recap and describe my setting:

jest.preset.js
![image](https://user-images.githubusercontent.com/34692625/218702660-fa090ed5-b87b-4f93-84e4-fbfa46105b64.png)

app jest.config.js:
![image](https://user-images.githubusercontent.com/34692625/218702765-a99a402b-1e92-46ac-a72e-5c09919798ae.png)

I have created a theme lib:
![image](https://user-images.githubusercontent.com/34692625/218702314-edb5127a-f7a3-4c86-a20c-bd80aaa943bd.png)


globals.css.ts looks like this:
![image](https://user-images.githubusercontent.com/34692625/218702978-63c0d5a9-2953-4d9d-96d2-498e52562d60.png)

theme-contract.css.ts
![image](https://user-images.githubusercontent.com/34692625/218703690-e01865e7-bf45-491f-9824-fce791ad9be1.png)


A bit ugly, but this is the api I export for a theme:
![image](https://user-images.githubusercontent.com/34692625/218703219-560689ea-1402-4153-ab06-8b74cc02e0fa.png)

I do this for: overriding a theme.contract and default tokens, expose an object so I can easily read base.class or base.tokens.
I also need pure values due to compatibility with some charting lib, but those are only consumed through Context.

I have light/dark modes, so I then pack everything:
![image](https://user-images.githubusercontent.com/34692625/218703899-96db351d-91eb-4c57-81a2-7157b5bff405.png)

The themes are injected in styled-components as well as in a Context Provider in case a dev wants to access the vars in a hook.

Finally I export from the lib:
![image](https://user-images.githubusercontent.com/34692625/218702404-0cd32966-8d73-4341-8b19-33a61b925977.png)

In app, all of this works perfectly. What am I doing wrong to get tests to work?
Help is highly appreciated.

**Comment by bart88** [comment]
@asherccohen 

🤔  Let's take a step back from all this. 

First create a dummy component that imports something very basic from a vanilla-extract file. 

```typescript 
// DummyComponent.css.ts
export const dummyStyle = style([
padding: "30px",
]);

// DummyComponent.ts
export function DummyComponent() {
    return <div className={dummyStyle}>This is a test</div>
}

// DummyComponent.test.ts
describe("DummyComponent", () => {
const { element } = render(<DummyComponent/>)
expect(element).toBeTruthy();
})

```

Run just this test. Does it work? If it does then the error is probably coming form vanilla-extract itself not the jest plugin. 
If it doesn't post the error message

**Comment by asherccohen** [comment]
Thanks @bart88 that's a good suggestion, so I tried.

The above works with no issues.

So I also extended it to:

//dummy.css.ts
![image](https://user-images.githubusercontent.com/34692625/219037330-d9a55465-ead8-47cb-aa9a-3dfc4d5a84da.png)

//dummy.tsx
![image](https://user-images.githubusercontent.com/34692625/219037419-75fe40db-eb61-4185-adb7-12af01971756.png)
Here I also try to read my injected vars using Context.

//dummy.spec.tsx
![image](https://user-images.githubusercontent.com/34692625/219037960-95c17467-3a69-459c-8fc9-b909485485a5.png)
Here I also wrap my Provider (forget about the store, that's just an additional dependency), so I can read my vars in the above component log.

This all passes, but check the logs:
![image](https://user-images.githubusercontent.com/34692625/219038282-f5d33215-3509-464a-8ad5-6c42410906fe.png)

- themeVars is an empty object, so no tokens in it (remember, this comes from the lib I created in nx)
- vars, which is a local theme contract pulled from dummy.css.ts is a string
- all styles are strings

The fun part? All of this is exactly the same with and WITHOUT the custom-resolver+jest-transformer

Tx for your patience btw.

**Comment by asherccohen** [comment]
@bart88 @craigbilner a while has passed since my last attempt to fix this but I've found no solution.

Is there anything else you suggest?
Could we jump on a call someday to have a look together?

**Comment by barbados-clemens** [comment]
At this time we aren't planning on changing the nx jest resolver, but since you can override the resolver with your own, which in turn can extend the nx resolver that's a valid work around for those that need it.

**Comment by asherccohen** [comment]
> At this time we aren't planning on changing the nx jest resolver, but since you can override the resolver with your own, which in turn can extend the nx resolver that's a valid work around for those that need it.

@barbados-clemens I understand, but my problem persists and it's locking us away from using vanilla-extract.

What am I missing in your opinion?

**Comment by barbados-clemens** [comment]
from all the logs you've shared the original issue of the resolver causing issues is resolved. what the logs are saying now appears to be a configuration issue with jest+vanilla-extract. 

This issue is about resolver so I do not want to further clutter it up. 

If you're having issues with @nrwl/jest then open a new issue with a minimal repo to cloned so it can be tracked separately.
