### ISSUE TITLE
Testing libraries separately from projects

### ISSUE THREAD

**Issue by JosepSalvat** [nrwl/nx#12657]
Hello, good morning!

As far I know, we can test projects but we should be able to test libs too, separately from projects.
Something like, npx nx test libs. 
Maybe I'm missing something, but I've only found the run-many

thanks!

**Comment by twittwer** [comment]
`run-many` will execute all kind of projects in your workspace.
Libs are just one kind of projects. If you have a look at your project definition (`project.json` or `workspace.json`) every project is `"projectType": "library"` or `"projectType": "application"`.

**Comment by barbados-clemens** [comment]
Hi there I think you're wanting support for being able to filter project more selectively when run many. You can up vote this pr which is for allowing you to use run many on tags.

https://github.com/nrwl/nx/pull/10085

**Comment by JosepSalvat** [comment]
Closed as I've some more problems and for now I'm not aiming to do this :) Thanks!
