### ISSUE TITLE
Nx generator updates pinned dependencies to the default

### ISSUE THREAD

**Issue by Lonli-Lokli** [nrwl/nx#12666]
## Current Behavior
Nx generator updates pinned dependencies to the default

## Expected Behavior
Dependenciies should stay the same

## Steps to Reproduce
1. Clone https://github.com/Lonli-Lokli/nx-update
2. Run `npx nx g @nrwl/workspace:lib data`

See changes in package.json
"tslib": "2.4.0", ->  "tslib": "^2.3.0"

I've created this reproduction but in another private project diff is much more

### Environment
```
Node : 16.17.0
   OS   : win32 x64
   npm  : 8.15.0

   nx : 15.0.0
   @nrwl/angular : 15.0.0
   @nrwl/cypress : 15.0.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.0
   @nrwl/js : 15.0.0
   @nrwl/linter : 15.0.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 12.8.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.0
   @nrwl/web : 12.8.0
   @nrwl/webpack : 15.0.0
   @nrwl/workspace : 15.0.0
   typescript : 4.8.2
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by Fafnur** [comment]
Also experiencing this.

**Comment by Lonli-Lokli** [comment]
@Coly010 @FrozenPandaz I think this (and some other package.json-related) might be related to this fix
https://github.com/nrwl/nx/pull/11443

I think this code will always be true, leading to update deps even when they are lower
https://github.com/nrwl/nx/blob/master/packages/devkit/src/utils/package-json.ts#L208-L211
