### ISSUE TITLE
Next.js build package.json contains a huge number of dependencies in v15

### ISSUE THREAD

**Issue by bojanbass** [nrwl/nx#12660]
## Current Behavior
Building a Next.js app generates dist successfully, but generate `package.json` contains around 850 dependencies in a clean NX workspace: https://github.com/bojanbass/nx15-nextjs-build-bug/blob/main/dist/apps/myapp/package.json

## Expected Behavior
Generated `package.json` contains only dependencies used in the application (7 for a clean nx workspace):
```
{
  "name": "myapp",
  "version": "0.0.1",
  "dependencies": {
    "@emotion/react": "11.10.4",
    "@emotion/styled": "11.10.4",
    "@nrwl/next": "14.8.6",
    "next": "12.3.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "~4.8.2"
  },
  "scripts": {
    "start": "next start"
  }
}
```

## Steps to Reproduce
Create new NX 15 workspace with Next.js template:
```
npx create-nx-workspace --name=my --preset=next --style=@emotion/styled --packageManager=yarn --appName=myapp --nxCloud=false
```
Build the app:
```
nx build myapp
```

Check `dist/apps/myapp/package.json` file.

Here is also a GitHub repo with the same setup, including `dist` folder. 
https://github.com/bojanbass/nx15-nextjs-build-bug

### Failure Logs
/

### Environment
```
   Node : 16.17.0
   OS   : darwin arm64
   yarn : 1.22.19

   nx : 15.0.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.0
   @nrwl/js : 15.0.0
   @nrwl/linter : 15.0.0
   @nrwl/nest : Not Found
   @nrwl/next : 15.0.0
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.0
   @nrwl/web : 15.0.0
   @nrwl/webpack : 15.0.0
   @nrwl/workspace : 15.0.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by skrtheboss** [comment]
I have the same issue, but with the `@nrwl/node:webpack` executor.

**Comment by skrtheboss** [comment]
I have managed to fix this for me by using the [GeneratePackageJsonPlugin](https://www.npmjs.com/package/generate-package-json-webpack-plugin) webpack plugin, instead of relying on the [generatePackageJson](https://nx.dev/packages/node/executors/webpack#generatepackagejson) option.

Custom webpack.config.js:

```
const GeneratePackageJsonPlugin = require('generate-package-json-webpack-plugin');
const { join: pathJoin } = require('node:path');
const { readFileSync } = require('node:fs');

module.exports = (config, { options }) => {
    config.plugins.push(
       new GeneratePackageJsonPlugin(
            {
                ...JSON.parse(readFileSync(pathJoin(options.root, options.projectRoot, 'package.json'))),
                main: options.outputFileName,
            },
            {
                useInstalledVersions: false,
                resolveContextPaths: [options.root],
                sourcePackageFilenames: [pathJoin(options.root, 'package.json')],
            }
        )
    );

    return config;
};

```

**Comment by aniravi24** [comment]
Built a custom executor using [this](https://github.com/nrwl/nx-labs/issues/31#issuecomment-1082037237) comment as a template, and noticing the same thing! package.json went from around 50 deps to 1000

**Comment by yharaskrik** [comment]
> I have managed to fix this for me by using the [GeneratePackageJson](https://www.npmjs.com/package/generate-package-json-webpack-plugin) webpack plugin, instead of relying on the [generatePackageJson](https://nx.dev/packages/node/executors/webpack#generatepackagejson) option.
> 
> Custom webpack.config.js:
> 
> ```
> const GeneratePackageJsonPlugin = require('generate-package-json-webpack-plugin');
> const { join: pathJoin } = require('node:path');
> const { readFileSync } = require('node:fs');
> 
> module.exports = (config, { options }) => {
>     config.plugins.push(
>        new GeneratePackageJsonPlugin(
>             {
>                 ...JSON.parse(readFileSync(pathJoin(options.root, options.sourceRoot, '..', 'package.json'))),
>                 main: options.outputFileName,
>             },
>             {
>                 useInstalledVersions: false,
>                 resolveContextPaths: [options.root],
>                 sourcePackageFilenames: [pathJoin(options.root, 'package.json')],
>             }
>         )
>     );
> 
>     return config;
> };
> ```

Thank you, I will try this for now!

**Comment by meeroslav** [comment]
Related to https://github.com/nrwl/nx/issues/12675. Please check the progress there.

**Comment by EliotBrown** [comment]
> I have managed to fix this for me by using the [GeneratePackageJson](https://www.npmjs.com/package/generate-package-json-webpack-plugin) webpack plugin, instead of relying on the [generatePackageJson](https://nx.dev/packages/node/executors/webpack#generatepackagejson) option.
> 
> Custom webpack.config.js:
> 
> ```
> const GeneratePackageJsonPlugin = require('generate-package-json-webpack-plugin');
> const { join: pathJoin } = require('node:path');
> const { readFileSync } = require('node:fs');
> 
> module.exports = (config, { options }) => {
>     config.plugins.push(
>        new GeneratePackageJsonPlugin(
>             {
>                 ...JSON.parse(readFileSync(pathJoin(options.root, options.sourceRoot, '..', 'package.json'))),
>                 main: options.outputFileName,
>             },
>             {
>                 useInstalledVersions: false,
>                 resolveContextPaths: [options.root],
>                 sourcePackageFilenames: [pathJoin(options.root, 'package.json')],
>             }
>         )
>     );
> 
>     return config;
> };
> ```

Thank you!
