### ISSUE TITLE
Cache is used even when changing "version" property in package.json

### ISSUE THREAD

**Issue by mlc-mlapis** [nrwl/nx#12668]
## Current Behavior
The latest Nx 15.0.0 behavior differs from earlier versions (tested for the last time with 14.7.5). Previously, changing the "version" property in `package.json` always led to a new build. But now, with version 15.0.0, changing "version" leads to the existing cached build.

## Expected Behavior
When "version" is changed, a new build should be processed.

**Comment by AgentEnder** [comment]
It sounds like your workspace is experiencing slightly different behavior with the migration that moved implicit dependencies to namedInputs. @FrozenPandaz I sent this your way since its related to that migration.

**Comment by FrozenPandaz** [comment]
By default, `package.json#version` is not considered an input into any targets. If you'd like this behavior, you can add `{workspaceRoot}/package.json` to `sharedGlobals` in your `namedInputs`. By default, we have intelligent parsing of which node_modules to hash.
