### ISSUE TITLE
Production Minification not working when using `withModuleFederation` webpack config

### ISSUE THREAD

**Issue by infoxicator** [nrwl/nx#12679]
## Current Behavior
Minification for production builds is not working when using the `withModuleFederation = require('@nrwl/react/module-federation')`; webpack config

## Expected Behavior
Production builds should have minification enabled.

## Steps to Reproduce
Create a new application that uses withModuleFederation = require('@nrwl/react/module-federation'); run a production build. The output is not minified.

The issue is caused by this line in here https://github.com/nrwl/nx/blob/master/packages/react/src/module-federation/with-module-federation.ts#L264

Yes, the bug can be reproduced using this example https://github.com/nrwl/react-module-federation

**Comment by veloware** [comment]
Also having the same issue.  Ive been scratching my head for days over this, I'm somewhat glad to hear I'm not the only one experiencing this issue.

**Comment by veloware** [comment]
I ended up getting the desired result when manually adding the `minimize` and `minimizer` config in `webpack.config.prod.js`

```
module.exports = async (config, context) => {
  const federatedModules = await withModuleFederation(prodConfig);

  return merge(federatedModules(config, context), {
    optimization: {
      minimize: true,
      minimizer: [
        new TerserPlugin({
          terserOptions: {
            mangle: true,
            keep_classnames: true,
          },
        }),
      ]
    },
  });
};
```

**Comment by Coly010** [comment]
Hey :) Thanks for reporting this! I'm taking a look at the PR submitted also :)

**Comment by infoxicator** [comment]
@veloware PR has been merged which fixes the issue, you shouldn't need to override the webpack config anymore 👍
