### ISSUE TITLE
SchematicsException [Error]: Project "foo" does not exist

### ISSUE THREAD

**Issue by Hypenate** [nrwl/nx#12673]
I'm trying to generate a new library in an existing app.
The same way I always did it in previous versions.

## Current Behavior
When I run the command (dry-run or run) I get the following errors:
Project 'library ui' contains extension with invalid name (files).
Project 'library utils' contains extension with invalid name (files).
Project 'library shared' contains extension with invalid name (files).
(you get the idea...off the libraries pop up here).

SchematicsException [Error]: Project "the name of my new library" does not exist.
    at C:\Users\foo\source\repos\bar\foo.ui\node_modules\@schematics\angular\component\index.js:99:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

## Expected Behavior
That the dry-run and run command don't throw errors 

## Steps to Reproduce
Create a new library:
 *  The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command yarn nx generate @nrwl/angular:library ui --style=scss --directory=foo/bar/registration --change-detection=OnPush --no-interactive --dry-run" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
 
### Failure Logs / Images / Videos

 *  The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command yarn nx generate @nrwl/angular:library ui --style=scss --directory=foo/bar/registration --change-detection=OnPush --no-interactive --dry-run" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

### Environment
  "dependencies": {
    "@angular/animations": "14.2.3",
    "@angular/cdk": "14.2.2",
    "@angular/common": "14.2.3",
    "@angular/compiler": "14.2.3",
    "@angular/core": "14.2.3",
    "@angular/fire": "^7.2.1",
    "@angular/forms": "14.2.3",
    "@angular/platform-browser": "14.2.3",
    "@angular/platform-browser-dynamic": "14.2.3",
    "@angular/router": "14.2.3",
    "@ngneat/dirty-check-forms": "^1.1.0",
    "@ngneat/error-tailor": "2.2.0",
    "@ngneat/transloco": "^4.1.1",
    "@ngneat/until-destroy": "^8.1.4",
    "@nrwl/angular": "15.0.0",
    "@nrwl/storybook": "15.0.0",
    "@storybook/builder-webpack5": "~6.5.4",
    "@storybook/core-server": "6.5.12",
    "@storybook/manager-webpack5": "~6.5.4",
    "convert-firebase-timestamp": "^0.0.4",
    "date-fns": "^2.28.0",
    "dexie": "^3.2.1",
    "eslint-plugin-unused-imports": "^2.0.0",
    "firebase": "^9.6.7",
    "luxon": "^2.3.1",
    "ng2-validation": "^4.2.0",
    "primeicons": "^5.0.0",
    "primeng": "^13.2.0",
    "rxfire": "^6.0.3",
    "rxjs": "^7.5.4",
    "tslib": "^2.0.0",
    "yarn": "^1.22.18",
    "zone.js": "0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "14.2.3",
    "@angular-eslint/eslint-plugin": "14.0.4",
    "@angular-eslint/eslint-plugin-template": "14.0.4",
    "@angular-eslint/template-parser": "14.0.4",
    "@angular/cli": "13.3.3",
    "@angular/compiler-cli": "14.2.3",
    "@angular/language-service": "14.2.3",
    "@nrwl/cli": "15.0.0",
    "@nrwl/cypress": "15.0.0",
    "@nrwl/eslint-plugin-nx": "15.0.0",
    "@nrwl/jest": "15.0.0",
    "@nrwl/linter": "15.0.0",
    "@nrwl/tao": "15.0.0",
    "@nrwl/workspace": "15.0.0",
    "@types/jest": "28.1.8",
    "@types/luxon": "^2.0.9",
    "@types/node": "14.14.33",
    "@typescript-eslint/eslint-plugin": "5.36.1",
    "@typescript-eslint/parser": "5.36.1",
    "autoprefixer": "^10.4.0",
    "cypress": "^8.3.0",
    "eslint": "8.15.0",
    "eslint-config-prettier": "^8.4.0",
    "eslint-plugin-cypress": "^2.12.1",
    "jest": "28.1.3",
    "jest-environment-jsdom": "28.1.1",
    "jest-preset-angular": "12.2.2",
    "postcss": "^8.3.11",
    "prettier": "2.6.2",
    "rxjs-spy": "^8.0.2",
    "tailwindcss": "^3.0.23",
    "ts-jest": "28.0.8",
    "ts-node": "10.9.1",
    "typescript": "4.8.4"
  }

**Comment by Hypenate** [comment]
After upgrading to 15.0.3 I face the same issue.

**Comment by willyboy** [comment]
We found a dependency (@compodoc/compodoc) was pinning angular-devkit/schematic to v13 causing this issue

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Could you provide a repo where this issue can be reproduced? With the information provided, I could not reproduce it, and without a reproduction, we won't be able to troubleshoot it.

@Hypenate did you check if https://github.com/nrwl/nx/issues/12673#issuecomment-1293851267 solves your issue?

**Comment by Hypenate** [comment]
I debugged it, and it ends up here throwing the error.
It's correct that the project doesn't exist, because I'm trying to make it.

WebStorm & VSCode give the same issue.

![image](https://user-images.githubusercontent.com/7478681/199182496-5931379a-bc7c-433d-8df8-4881e4f1f7eb.png)

**Comment by Hypenate** [comment]
I did a few things that were suggested in #11138

- removed the node_modules folder but also the yarn.lock file
- gave all my projects a tag in the angular.json file
