### ISSUE TITLE
Builds (at least for nest) fail when using package-lock@v3

### ISSUE THREAD

**Issue by lucavb** [nrwl/nx#12676]
The `build` or `test` command are failing when running. This seems to be linked to the used package-lock.json version since it works when using version 2. As far as I can tell this line crashes because in package-lock@v3 there is no `dependencies` key on the level where it is being destructured from

<img width="1062" alt="Screenshot 2022-10-18 at 09 48 29" src="https://user-images.githubusercontent.com/5306815/196369174-e727c3dd-6a1f-4edb-8fbb-0a9c4af58ae6.png">

[destructuring](https://github.com/nrwl/nx/blob/master/packages/nx/src/utils/lock-file/npm.ts#L39)
[Object.entries() call](https://github.com/nrwl/nx/blob/master/packages/nx/src/utils/lock-file/npm.ts#L59)

## Current Behavior

Crashes when running `build` or `test` with a project.

## Expected Behavior

I expect Nx to start the build / test process. Yes, this is a regression. In the last version from the 14 release this used to work.

## Steps to Reproduce

https://github.com/lucavb/package-lock-nx-demo

* Run `npm i`
* Make sure that the `package-lock.json` file is version 3
* Run `npx nx build my-nest-app`
* See the error ` NX   Cannot convert undefined or null to object` 

### Failure Logs

```
$ npx nx test my-nest-app

 >  NX   Cannot convert undefined or null to object


   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
```

### Environment
```
$ npx nx report (with version 3)

 >  NX   Cannot convert undefined or null to object


   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".

$ npx nx report (with version 2)

 >  NX   Report complete - copy this into the issue template

   Node : 18.6.0
   OS   : darwin x64
   npm  : 8.14.0

   nx : 15.0.0
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.0
   @nrwl/js : 15.0.0
   @nrwl/linter : 15.0.0
   @nrwl/nest : 15.0.0
   @nrwl/next : Not Found
   @nrwl/node : 15.0.0
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.0.0
   @nrwl/workspace : 15.0.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

```

**Comment by meeroslav** [comment]
Thank you for reporting this issue. We will add support for lock file v3 as soon as possible.
