### ISSUE TITLE
Accidentally publishing code on `nx.app` is way too easy

### ISSUE THREAD

**Issue by githorse** [nrwl/nx#12686]
My company considers my front-end repository, reasonably, to be confidential intellectual property. Yesterday when trying out `nx` for the first time I very narrowly avoided publishing my IP to the internet (i.e., to [anyone with a (free) nx.app account](https://nx.dev/nx-cloud/set-up/add-nx-cloud#connecting-your-workspace-to-your-nx-cloud-account)) by clicking "Yes" on this innocent-sounding default option during setup:

```
? Enable distributed caching to make your CI faster
  (Use arrow keys)
❯ Yes I want faster builds
  No
```

Frankly, it's nuts that with one keystroke here I could post my code to the public internet without any setup or registration. It never occurred to me that a build tool might do that. 

This default option during setup is the worst offender, but the `connect-to-nx-cloud` option is equally dangerous. The general point here is that it should not be trivially easy for me (or a junior colleague, say) to accidentally publish my private code to an unknown server.

`nx` has a financial incentive to entice me into the cloud build system. (You can tell that the marketing department wrote the option "Yes I want faster builds".) That's fine, and cloud build sounds like an awesome tool that I would probably be happy to pay for -- but not without understanding the implications first! Opting me in by default with no warning is irresponsible, if not outright sneaky.

Here are a few possible (non-mutually-exclusive) mitigations:
1. Default to "No", not "Yes", during setup
2. Add some red warning text next to the default option (`"Warning: this will publish your code to nx.app. Read more ..."`)
3. Add a confirmation screen after selecting "Yes" but before actually publishing code
4. Require some minimal account setup on `nx.app` (!)
5. Make the default `nx.app` account private, not public (!)
6. Read from an envar (`NX_CLOUD=false`) or an option in `nx.json` that disables cloud access (so no one on my team can accidentally use the command line flag to turn it on)

`nx` is super cool, and I appreciate convenience as much as the next dev, but until there are safety rails in place to prevent me or a colleague from exposing our company IP, I can't use it.

**Comment by FrozenPandaz** [comment]
Hi,

I understand your concern. Let me clarify a few points.

Example run from an unclaimed workspace: https://cloud.nx.app/runs/C5eHfDBJib

1. Yes, we do indeed intentionally try to make this easy and unintimidating because we honestly think it is a helpful feature.
2. When you have an unclaimed workspace, only _surface_ level information about your run is publicly available as seen above.
3. The actual artifacts, are hidden. To get them, you must run the same computation (with the **same source code**). There is intentionally, no way to retrieve artifacts via the UI.
4. The following warning is actually shown after choosing the option.

```terminal
 >  NX   Distributed caching via Nx Cloud has been enabled

   In addition to the caching, Nx Cloud provides config-free distributed execution,
   UI for viewing complex runs and GitHub integration. Learn more at https://nx.app

   Your workspace is currently unclaimed. Run details from unclaimed workspaces can be viewed on cloud.nx.app by anyone
   with the link. Claim your workspace at the following link to restrict access.
```

5. On adding a confirmation screen after saying yes to this prompt:
  1. Only the name of your workspace is sent to nx.app immediately after saying Yes.
  2. Artifacts will only be published after actually executing a build or tests.
6. On the financial incentive: While a workspace has been setup, there are still many steps before we would profit from this workspace.
  1. Workspaces get 500 hours per month for free. We do not profit from these.
  2. Billing setup is never required. You must set it up to beyond the 500 hours but even if you don't, there are no penalties. Your runs will just stop being cached until the next month.

What do you think? We are open to more discussion how we an improve the experience.

**Comment by githorse** [comment]
Thanks @FrozenPandaz - I appreciate the prompt and thoughtful response! Obviously I'm very happy to here that the artifact itself is not public. My first suggestion would be to clarify that in a few places in the docs, especially [here](https://nx.dev/nx-cloud/set-up/add-nx-cloud#connecting-your-workspace-to-your-nx-cloud-account). A big fat "Build artifacts are private; only you will be able to view them, once you have claimed your workspace" would go a long way towards reassuring guys like me.

Even given above, I would still vote to require some minimal setup on `nx.app` before enabling that option. My artifacts may be private, but I still find it surprising and disconcerting that they can so trivially be pushed to a server I don't know. If a user can't be bothered to go through a very simple sign-up process, do they really need cloud build all that badly?

That said, I do understand and appreciate the ease of the effortless cloud hookup, and that not all users might feel the same way about this. You may not be willing to sacrifice this (admittedly epic) level of convenience.

Either way, some suggestions:

1. Clarify the privacy of source code / build artifacts in the docs as suggested above.
2. Update the language in the post-prompt setup warning to clarify that artifacts are not visible:
```
Run details (but no source code or build artifacts) from unclaimed workspaces can be viewed on cloud.nx.app by anyone with the link ...
```
3. Add an additional confirmation prompt after clicking "Yes" in the setup. Something like:
```
 >  NX   Distributed caching via Nx Cloud has been enabled

In addition to the caching, Nx Cloud provides config-free distributed execution, UI for viewing complex runs and GitHub integration. Learn more at https://nx.app

Source code and artifacts are private blah blah blah [message from above]

❯ Continue
  Cancel distributed caching
```
3. Update the initial setup prompt to make it clear that "distributed caching" is via Nx Cloud:
```
? Enable distributed caching on Nx Cloud (learn more at https://nx.app/cloud-build):
  (Use arrow keys)
❯ Yes I want faster builds
  No
```
5. Consider adding the `NX_CLOUD=false` or equivalent config option. Obviously this is less of a concern with private artifacts, but I imagine I'm not the only one who still might want to opt out of pushing code to an unknown server (and make it hard for anyone on the team to accidentally do so).

**Comment by Mikoz93** [comment]
@githorse All good suggestions, I'd even change the option selected by default to 'No', to make the selecting 'Yes I want faster builds' a slightly more conscious decision.

**Comment by kaltepeter** [comment]
@FrozenPandaz I would like to be able to disable NX cloud with a config or env var, at the very least skip the prompt for automation. There seems to be no way to run the migrations command without answering this prompt as 'yes'. 

Effectively the way it is running at the moment I can answer yes or be prompted every time.

**Comment by a-coruble** [comment]
Hey there, I also reported the same issue / risky behaviour in #14753 !
I heavily agrees on the need for an env variable / project configuration option to disable totally any behaviour that could add `@nrwl/nx-cloud` dependency or have a way to blacklist certain commands from sending logs.
