### ISSUE TITLE
Support glob expansion with `esbuild` executor

### ISSUE THREAD

**Issue by dan-cooke** [nrwl/nx#12685]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Esbuild does not expand globs, normally users will handle this via their shell expansion, or programatically with the `glob` library. However with the `@nrwl/esbuild` plugin - there is currently no utilisation of the `glob` library.
## Motivation

When developing multiple services in a single "app" that don't necesarily have a single entry point, you could pass each of the services as follows:

```.json
  "build": {
      "executor": "@nrwl/esbuild:esbuild",
      "options": {
        "main": "apps/service/src/lambda1",
        "tsConfig": "apps/rtc-signal/tsconfig.json",
         "additionalEntryPoints": [ "apps/service/src/lambda2"],
        "outputPath": "dist/apps/service"
      }
    },
```

Which works fine, but to create generic workspace generators that use `esbuild` it would be less boilerplate to allow users to define their `entryPoints` using a glob pattern instead of a single `main` and then `additionalEntryPointsz`

## Suggested Implementation

**Keep original API, and support globs with the `main` property**
This approach keeps the plugin in sync with other build executors like webpack, as they all require a `main`

It would require a simple check in https://github.com/nrwl/nx/blob/master/packages/esbuild/src/executors/esbuild/lib/build-esbuild-options.ts to determine if the user has passed a glob:

Something like:
```.ts

  if (isValidGlob(options.main)) {
    // Set entry points to result of expansion

  }
```
## Alternate Implementations

**Modify the API to be more in tune with the esbuild semantics**
Instead of having `main` we would only offer a single `entryPoints: string[]` and a `entryPointsGlob: string`

**Comment by alfaproject** [comment]
I'd still love this because currently we are setting an arbitrary main for 1 of the function handlers, and then we set the other function handlers 1 by 1 in `entryPoints` and have to keep them in sync ):
