### ISSUE TITLE
Package-Based Repo Tutorial Does Not Work:  NX   Cannot find project 'is-even'

### ISSUE THREAD

**Issue by cgradwohl** [nrwl/nx#12689]
## Current Behavior
The tutorial found here: https://nx.dev/getting-started/package-based-repo-tutorial does not work.

After working through the tutorial adding the `is-even` package as expected, the `npx nx build is-even` command fails with the following message:
```
> NX   Cannot find project 'is-even'
```

## Expected Behavior

The tutorial found here: https://nx.dev/getting-started/package-based-repo-tutorial should work.

## Steps to Reproduce

Simply follow the steps in the tutorial here: https://nx.dev/getting-started/package-based-repo-tutorial 

### Failure Logs

```
> NX   Cannot find project 'is-even'
```

### Environment

```
> NX   Cannot find project 'is-even'
```

**Comment by AgentEnder** [comment]
Can you run `nx report` and check if workspace.json is present?

**Comment by cgradwohl** [comment]
> Can you run `nx report` and check if workspace.json is present?

@AgentEnder `workspace.json` is not present and is not generated by the `npx create-nx-workspace@latest package-based --preset=npm` command.

Here is the output of `nx report`:
```
package-based on  main [?] via  v16.13.1 on ☁️  (us-east-1) 
❯ npx nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.1
   OS   : darwin arm64
   npm  : 8.1.2
   
   nx : 15.0.0
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : Not Found
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : Not Found
   typescript : Not Found
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by AgentEnder** [comment]
Great, it shouldn't be. Can you run `nx graph` and send a screenshot?

**Comment by cgradwohl** [comment]
> Great, it shouldn't be. Can you run `nx graph` and send a screenshot?

@AgentEnder `nx graph` produces the following:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/15326707/196753699-a7daf7c4-1f22-4267-b8cf-e37c0f853935.png">

**Comment by cgradwohl** [comment]
@AgentEnder here is a repo that follows the steps from the tutorial:

https://github.com/cgradwohl/package-based

**Comment by AgentEnder** [comment]
For package based repos we use the name field in package.json as the project name. In your case, this is `@package-based/is-even`. You should change it to `is-even`.

**Comment by AgentEnder** [comment]
We should update the docs though, since the package name is meant to have the scope in this case.

**Comment by medmin** [comment]
the broken "Get Started" is a deal-breaker. I will try one more time with this tho.

**Comment by runninghare** [comment]
I think it's still having issues. I am following the tutorial but is-odd still couldn't find the is-even dependency (npx nx build is-odd failed with erro: Cannot find module 'is-even' or its corresponding type declarations.). VSCode also reports error on:

`import { isEven } from 'is-even';`

If I change it to:

`import { isEven } from '../is-even';`

then everything is fine but I believe this is not mean to be like that.

**Comment by runninghare** [comment]
Finally figured out why after reading [this article](https://earthly.dev/blog/setup-typescript-monorepo/)
NPM version must >= 7.0

It'd be better that Tutorial mentions this.
