### ISSUE TITLE
NX monorepo - using React jsx files in library with Angular App: Module not found

### ISSUE THREAD

**Issue by abf7d** [nrwl/nx#12693]
## Current Behavior
I have a React library in my NX monorepo that I generated using nx g @nrwl/react:lib mylib. I have some jsx files that I wish copy to the library and use without converting to tsx. My main app in my monorepo uses Angular 13. I wish to wrap the component defined in the jsx in a web component which I can use in my Angular app. I followed [this](https://medium.com/@fabianandrescano/working-with-nx-dev-using-react-angular-and-native-web-components-part-2-of-9-4883c314d217) tutorial. Creating a web component with tsx is working, but when I try to use a jsx file, it breaks.

## Expected Behavior

I expect to be able to wrap  a React component defined in a jsx file in a web component that is used in an angular app. I expect the component to render when load the page.

No

## Steps to Reproduce

```
Run: npx create-nx-workspace@13.3 my-nx-workspace
choose an angular app
cd test
npm i @nrwl/react@13.3
nx g @nrwl/react:lib jsx-sample
```
finish following [this tutorial](https://medium.com/@fabianandrescano/working-with-nx-dev-using-react-angular-and-native-web-components-part-2-of-9-4883c314d217) 

### Failure Logs

It doesn't seem to be recognizing the jsx files. I created a sample jsx file jsx-sample.jsx that I export from my index.ts file. When I try to run the app I get the following error: 
`Error: Module not found: Error: Can't resolve './lib/jsx-sample' in 'C:\test\my-nx-workspace\libs\my-react-lib\src'` 
and
`'./lib/jsx-sample'. 'C:/test/my-nx-workspace/libs/react-lib/src/lib/jsx-sample.jsx' implicitly has an 'any' type.`

### Environment

 NX  Report complete - copy this into the issue template

```
  Node : 12.22.12
  OS   : win32 x64
  npm  : 6.14.16

  nx : 13.3.12
  @nrwl/angular : 13.3.12
  @nrwl/cli : 13.3.12
  @nrwl/cypress : 13.3.12
  @nrwl/devkit : 13.3.12
  @nrwl/eslint-plugin-nx : 13.3.12
  @nrwl/express : undefined
  @nrwl/jest : 13.3.12
  @nrwl/linter : 13.3.12
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.3.12
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.12
  @nrwl/web : 13.3.12
  @nrwl/workspace : 13.3.12
  @nrwl/storybook : 13.3.12
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.1.3
         @angular/common: 13.1.3
         @angular/compiler: 13.1.3
         @angular/core: 13.1.3
         @angular/forms: 13.1.3
         @angular/platform-browser: 13.1.3
         @angular/platform-browser-dynamic: 13.1.3
         @angular/router: 13.1.3
         @angular-devkit/build-angular: 13.1.4
         @angular/cli: 13.1.4
         @angular/compiler-cli: 13.1.3
         @angular/language-service: 13.1.3
```

**Comment by FrozenPandaz** [comment]
That's a very fascinating approach! Unfortunately, it is very hard to help you unless a repo is provided. Could you please provide a repo and we could take a look?

**Comment by abf7d** [comment]
I added a sample repo [here](https://github.com/abf7d/render) for you to look at. The names are different, but it has my react library and my angular app. The `viv-viewer` is the react library I am trying to import. The component viv-viewer is tsx and works, but when I include jsx-viewer which is jsx in the index.ts in the react library I get errors. Thank you!
