### ISSUE TITLE
.env variables are undefined in Storybook (NX + Next.js + Storybook).

### ISSUE THREAD

**Issue by kaguya3222** [nrwl/nx#12696]
## Current Behavior
When I try to get variables from the `.env.local` file in Storybook they are undefined.

## Expected Behavior
`.env.local` variables should be defined in Storybook.

## Steps to Reproduce
1. Clone [this](https://github.com/kaguya3222/nx-nextjs-storybook-env-issue) repository.
2. Install dependencies with `npm install`.
3. Run storybook with `npx nx storybook` command.
4. Open `Button` story, then open console, you will se `undefined` log of `console.log(process.env.NEXT_PUBLIC_TEST)` from Button component.

### Environment
```
Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : linux x64
   npm  : 8.18.0
   
   nx : 15.0.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.0
   @nrwl/js : 15.0.0
   @nrwl/linter : 15.0.0
   @nrwl/nest : Not Found
   @nrwl/next : 15.0.0
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.7.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.0
   @nrwl/web : 15.0.0
   @nrwl/webpack : 15.0.0
   @nrwl/workspace : 15.0.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

```

### Additional info

My setup is NX + Storybook + Next.js. When I run the application with `npx nx serve` and open console, i see `test` in console, because environment variables are defined while running the application, but not Storybook.

**Comment by mandarini** [comment]
Hi there @kaguya3222 ! I'll look into this issue at some point later this week. In the meantime, can you look at the docs of Storybook and see if you are doing what is instructed here? Just to cross out the possibility that maybe it's just a config issue. Here's the docs: https://storybook.js.org/docs/react/configure/environment-variables

**Comment by kaguya3222** [comment]
@mandarini Hello, thanks for the response! I think .env variables should work via `storybook-addon-next`. I have a similar application (without NX) that uses next.js, storybook and storybook-addon-next and .env variables works fine here: https://github.com/kaguya3222/next-storybook

**Comment by mandarini** [comment]
I'm still looking into this 😬 
It's not just for next.js, it's for Storybook on Nx in general. Will fix it.

You can solve your problem if you run storybook like this:

```
MY_ENV_VAR=something nx storybook my-app
```

**Comment by kaguya3222** [comment]
@mandarini It works, thank you! Didn't notice it in docs

**Comment by MartinDavi** [comment]
Agreed with @grumpyoldman-io - any work around for this? My application code needs to use NEXT_PUBLIC prefix, so I can't define a special NX_ prefix just for storybook.
