### ISSUE TITLE
Nx-Cloud: issue with migration to v15.0.0, nx-cloud@15.0.0 not found

### ISSUE THREAD

**Issue by sebpalluel** [nrwl/nx#12717]
## Current Behavior
I've just upgraded my Nx project to the last version following those steps:
```sh
npx nx migrate latest
npx nx migrate --run-migrations
```
All went well but the Main Job on Nx Cloud is not finding the package nx-cloud@15.0.0:
```logs
npm WARN exec The following package was not found and will be installed: nx-cloud@15.0.0
[11](https://github.com/sebpalluel/web3-monorepo/actions/runs/3283572229/jobs/5408457292#step:22:12)
NX CLOUD ERROR
[12](https://github.com/sebpalluel/web3-monorepo/actions/runs/3283572229/jobs/5408457292#step:22:13)
---------------------------------------
[13](https://github.com/sebpalluel/web3-monorepo/actions/runs/3283572229/jobs/5408457292#step:22:14)
This version of Nx Cloud is incompatible with the @nrwl/* packages in your workspace.
[14](https://github.com/sebpalluel/web3-monorepo/actions/runs/3283572229/jobs/5408457292#step:22:15)
Match your @nrwl/nx-cloud version to the same major version of your @nrwl/* packages and try again.
[15](https://github.com/sebpalluel/web3-monorepo/actions/runs/3283572229/jobs/5408457292#step:22:16)
---------------------------------------
```

## Expected Behavior
All nx packages including nx-cloud are at v15.0.0 so it shouldn't cause any issue on the CI.

## Steps to Reproduce
[The branch where the issue is happening](https://github.com/sebpalluel/web3-monorepo/tree/69-client-create-a-storybook-project-with-basic-components-and-tests)

### Failure Logs
https://github.com/sebpalluel/web3-monorepo/actions/runs/3283572229/jobs/5408457292

### Environment
```logs
Node : 16.15.1
   OS   : darwin arm64
   pnpm : 7.13.2
   
   nx : 15.0.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.0
   @nrwl/js : 15.0.0
   @nrwl/linter : 15.0.0
   @nrwl/nest : Not Found
   @nrwl/next : 15.0.0
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.0
   @nrwl/nx-plugin : 15.0.0
   @nrwl/react : 15.0.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.0
   @nrwl/web : 15.0.0
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.0.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
         @boilerplate/workspace
   ---------------------------------------
   Community plugins:
```

**Comment by StalkAltan** [comment]
Hi!

It looks like your Volta install step is failing.

The `nx-cloud stop-all-agents` command is failing because the rest of your Nx packages aren't getting installed -- Volta's failure is causing the install step to never run.

I'd expect fixing Volta would resolve this issue, but let me know if you continue to have issues!

**Comment by AgentEnder** [comment]
If you happen to be using `nrwl/ci`, bumping to v0.8 will fix volta.

**Comment by sebpalluel** [comment]
> If you happen to be using `nrwl/ci`, bumping to v0.8 will fix volta.

It worked thanks 😀 https://github.com/sebpalluel/web3-monorepo/commit/43a3ffa634da83f7064e02b251c323a9d74f0f41
