### ISSUE TITLE
Nx cache is not working for custom targets that generates new output

### ISSUE THREAD

**Issue by gerardcastell** [nrwl/nx#12715]
## Current Behavior

Create a new task:
```    
"deploy": {
      "executor": "nx:run-commands",
      "outputs": [],
      "options": {
        "command": "([ -d \"nginx\" ] && find nginx ! -type d -exec rm {} \\; rm -rf nginx/assets) || mkdir -p nginx && cp -r apps/shell/* nginx",
        "cwd": "dist"
          }
      }
```

It is also added as cachable operation in the nx.json. When retrieving the cache from the nx cloud nor the local cache it is not restoring the nginx folder.

## Expected Behavior

It should store the output generated, which is the nginx folder within the dist. In the official documentation of the Nx you say that if I do not define the outputs attribute it should cache by default the dist folder itself.
## Steps to Reproduce

Do the steps explained above.

### Environment

 >  NX   Report complete - copy this into the issue template

   Node : 16.17.1
   OS   : darwin arm64
   npm  : 8.15.0
   
   nx : 14.8.3
   @nrwl/angular : 14.8.3
   @nrwl/cypress : 14.8.3
   @nrwl/detox : 14.8.3
   @nrwl/devkit : 14.8.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.3
   @nrwl/js : 14.8.3
   @nrwl/linter : 14.8.3
   @nrwl/nest : 14.8.3
   @nrwl/next : Not Found
   @nrwl/node : 14.8.3
   @nrwl/nx-cloud : 14.7.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.8.3
   @nrwl/react-native : 14.8.3
   @nrwl/rollup : 14.8.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.3
   @nrwl/web : 14.8.3
   @nrwl/webpack : 14.8.3
   @nrwl/workspace : 14.8.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @ng-bootstrap/ng-bootstrap: 13.0.0
   	 @ngrx/component-store: 14.0.2
   	 @ngrx/effects: 14.0.2
   	 @ngrx/entity: 14.0.2
   	 @ngrx/router-store: 14.0.2
   	 @ngrx/store: 14.0.2
   	 ngx-bootstrap: 9.0.0
   	 ngx-spinner: 14.0.0
   	 @fortawesome/angular-fontawesome: 0.11.1
   	 @ngrx/schematics: 14.0.2
   	 @ngrx/store-devtools: 14.0.2

**Comment by AgentEnder** [comment]
What does your project.json and nx.json look like?

**Comment by gerardcastell** [comment]
project.json:
`{
  "projectType": "application",
  "sourceRoot": "apps/shell/src",
  "prefix": "multi-frontend",
  "targets": {
    "build": {
      "executor": "@nrwl/angular:webpack-browser",
      "outputs": ["{options.outputPath}"],
      "options": {
        "allowedCommonJsDependencies": [
          "snakecase-keys",
          "ua-parser-js",
          "camelcase-keys",
          "chart.js",
          "deep-map-object",
          "map-obj",
          "moment",
          "deepmerge",
          "@fortawesome/angular-fontawesome",
          "@fortawesome/fontawesome-svg-core",
          "@fortawesome/free-brands-svg-icons",
          "@fortawesome/pro-duotone-svg-icons",
          "@fortawesome/pro-light-svg-icons",
          "@fortawesome/pro-regular-svg-icons",
          "@fortawesome/pro-solid-svg-icons"
        ],
        "outputPath": "dist/apps/shell",
        "index": "apps/shell/src/index.html",
        "main": "apps/shell/src/main.ts",
        "polyfills": "apps/shell/src/polyfills.ts",
        "tsConfig": "apps/shell/tsconfig.app.json",
        "inlineStyleLanguage": "scss",
        "assets": [
          {
            "glob": "**/*",
            "input": "libs/core/assets/src/lib",
            "output": "assets"
          },
          {
            "glob": "**/*",
            "input": "libs/core/i18n/assets",
            "output": "assets"
          },
          "apps/shell/src/assets",
          "apps/shell/src/robots.txt",
          "apps/shell/src/manifest.webmanifest"
        ],
        "styles": [
          "node_modules/animate.css/animate.min.css",
          "node_modules/bootstrap/dist/css/bootstrap.min.css",
          "node_modules/intl-tel-input/build/css/intlTelInput.css",
          "libs/core/stylesheets/src/lib/main.scss",
          "apps/shell/src/styles.scss"
        ],
        "stylePreprocessorOptions": {
          "includePaths": [
            "libs/core/stylesheets/src/lib/styles/",
            "libs/core/stylesheets/src/lib/main.scss"
          ]
        },
        "scripts": [],
        "customWebpackConfig": {
          "path": "apps/shell/webpack.config.js"
        }
      },
      "configurations": {
        "production": {
          "budgets": [
            {
              "type": "initial",
              "maximumWarning": "3mb",
              "maximumError": "5mb"
            },
            {
              "type": "anyComponentStyle",
              "maximumWarning": "6kb",
              "maximumError": "10kb"
            }
          ],
          "fileReplacements": [
            {
              "replace": "apps/shell/src/assets/module-federation.manifest.json",
              "with": "apps/shell/src/assets/module-federation/module-federation.manifest.staging.json"
            }
          ],
          "index": "apps/shell/src/index.html",
          "optimization": true,
          "sourceMap": true,
          "namedChunks": true,
          "extractLicenses": true,
          "vendorChunk": true,
          "buildOptimizer": true,
          "outputHashing": "all",
          "customWebpackConfig": {
            "path": "apps/shell/webpack.prod.config.js"
          }
        },
        "beta": {
          "fileReplacements": [
            {
              "replace": "apps/shell/src/assets/module-federation.manifest.json",
              "with": "apps/shell/src/assets/module-federation/module-federation.manifest.beta.json"
            }
          ],
          "index": {
            "input": "apps/shell/src/index.dev.html",
            "output": "index.html"
          },
          "optimization": true,
          "outputHashing": "all",
          "sourceMap": true,
          "namedChunks": true,
          "extractLicenses": true,
          "vendorChunk": true,
          "buildOptimizer": true,
          "budgets": [
            {
              "type": "initial",
              "maximumWarning": "3mb",
              "maximumError": "5mb"
            },
            {
              "type": "anyComponentStyle",
              "maximumWarning": "6kb",
              "maximumError": "10kb"
            }
          ]
        },
        "staging": {
          "fileReplacements": [
            {
              "replace": "apps/shell/src/assets/module-federation.manifest.json",
              "with": "apps/shell/src/assets/module-federation/module-federation.manifest.staging.json"
            }
          ],
          "index": {
            "input": "apps/shell/src/index.dev.html",
            "output": "index.html"
          },
          "optimization": true,
          "outputHashing": "all",
          "sourceMap": true,
          "namedChunks": true,
          "extractLicenses": true,
          "vendorChunk": true,
          "buildOptimizer": true,
          "budgets": [
            {
              "type": "initial",
              "maximumWarning": "3mb",
              "maximumError": "5mb"
            },
            {
              "type": "anyComponentStyle",
              "maximumWarning": "6kb",
              "maximumError": "10kb"
            }
          ]
        },
        "development": {
          "buildOptimizer": false,
          "optimization": false,
          "vendorChunk": true,
          "extractLicenses": false,
          "sourceMap": true,
          "namedChunks": true,
          "index": {
            "input": "apps/shell/src/index.dev.html",
            "output": "index.html"
          }
        }
      },
      "defaultConfiguration": "production"
    },
    "serve": {
      "executor": "@nrwl/angular:module-federation-dev-server",
      "configurations": {
        "production": {
          "browserTarget": "shell:build:production"
        },
        "development": {
          "browserTarget": "shell:build:development"
        }
      },
      "defaultConfiguration": "development",
      "options": {
        "port": 4200,
        "publicHost": "http://localhost:4200"
      }
    },
    "serve-without-mfe": {
      "executor": "@nrwl/angular:webpack-server",
      "configurations": {
        "production": {
          "browserTarget": "shell:build:production"
        },
        "development": {
          "browserTarget": "shell:build:development"
        }
      },
      "defaultConfiguration": "development",
      "options": {
        "port": 4200,
        "publicHost": "http://localhost:4200"
      }
    },
    "extract-i18n": {
      "executor": "@angular-devkit/build-angular:extract-i18n",
      "options": {
        "browserTarget": "shell:build"
      }
    },
    "lint": {
      "executor": "@nrwl/linter:eslint",
      "options": {
        "lintFilePatterns": ["apps/shell/**/*.ts", "apps/shell/**/*.html"]
      }
    },
    "test": {
      "executor": "@nrwl/jest:jest",
      "outputs": ["coverage/apps/shell"],
      "options": {
        "jestConfig": "apps/shell/jest.config.ts",
        "passWithNoTests": true
      }
    },
    "deploy": {
      "executor": "nx:run-commands",
      "outputs": [],
      "options": {
        "command": "([ -d \"nginx\" ] && find nginx ! -type d -exec rm {} \\; rm -rf nginx/assets) || mkdir -p nginx && cp -r apps/shell/* nginx",
        "cwd": "dist"
      }
    }
  },
  "tags": [],
  "implicitDependencies": []
}
`

nx.json:
`{
  "implicitDependencies": {
    "workspace.json": "*",
    "angular.json": "*",
    "package.json": {
      "dependencies": "*",
      "devDependencies": "*"
    },
    "tslint.json": "*",
    "nx.json": "*",
    "tsconfig.base.json": "*",
    ".eslintrc.json": "*",
    "libs/core/stylesheets/**/*.scss": "*"
  },
  "affected": {
    "defaultBase": "master"
  },
  "npmScope": "multi-frontend",
  "tasksRunnerOptions": {
    "default": {
      "runner": "@nrwl/nx-cloud",
      "options": {
        "cacheableOperations": ["build", "lint", "test", "e2e"],
        "accessToken": "*******",
        "canTrackAnalytics": false,
        "showUsageWarnings": true,
        "parallel": 3
      }
    }
  },
  "landing-global-view-products-portfolio": {
    "tags": []
  },
  "generators": {
    "@nrwl/workspace": {
      "library": {
        "linter": "eslint"
      }
    },
    "@nrwl/cypress": {
      "cypress-project": {
        "linter": "eslint"
      },
      "convert-tslint-to-eslint": {
        "removeTSLintIfNoMoreTSLintTargets": false
      }
    },
    "@nrwl/react": {
      "application": {
        "linter": "eslint"
      },
      "library": {
        "linter": "eslint"
      }
    },
    "@nrwl/next": {
      "application": {
        "linter": "eslint"
      }
    },
    "@nrwl/web": {
      "application": {
        "linter": "eslint"
      }
    },
    "@nrwl/node": {
      "application": {
        "linter": "eslint"
      },
      "library": {
        "linter": "eslint"
      }
    },
    "@nrwl/nx-plugin": {
      "plugin": {
        "linter": "eslint"
      }
    },
    "@nrwl/nest": {
      "application": {
        "linter": "eslint"
      }
    },
    "@nrwl/express": {
      "application": {
        "linter": "eslint"
      }
    },
    "@nrwl/angular:application": {
      "style": "scss",
      "linter": "eslint",
      "unitTestRunner": "jest",
      "e2eTestRunner": "cypress",
      "strict": false
    },
    "@nrwl/angular:library": {
      "linter": "eslint",
      "unitTestRunner": "jest",
      "strict": false
    },
    "@nrwl/angular:component": {
      "style": "scss"
    },
    "@nrwl/angular": {
      "convert-tslint-to-eslint": {
        "removeTSLintIfNoMoreTSLintTargets": true
      }
    },
    "@nrwl/angular:remote": {
      "host": "shell",
      "style": "scss",
      "strict": false
    }
  },
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build"]
    }
  },
  "defaultProject": "shell"
}
`

**Comment by AgentEnder** [comment]
For `deploy` you specify `outputs: []`, this tells Nx that there is no on-disk outputs for the given task. You should provide a path to the outputs in that array.

**Comment by gerardcastell** [comment]
Hi! I have tested declaring the outputs as well but it didn't succeed.
I try with:
```
"outputs":["dist", "dist/nginx"]
```
in the project.json and in the nx.json but it does not work. You can try yourself with a new repo, I could not perform it in new ones neither.
