### ISSUE TITLE
simple coverage server

### ISSUE THREAD

**Issue by JessieMercurial** [nrwl/nx#12718]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

after generating test coverage with npx nx test --coverage, while using codespaces and locally, it would be convenient if it does not already exist to be able to enter the coverage directory and npx nx serve-coverage (or something like that) and be able to click into the coverage of the different libs/apps and navigate from there.

an example server I've been using
```
var host = "127.0.0.1";
var port = 1337;
var express = require("express");

var app = express();
app.use('/', express.static('/workspaces/nx-monorepo/digital-defiance/coverage/libs/brightchain-quorum'));
app.listen(port, host);
```

## Motivation

Saves end users from having to copy in this boilerplate code into the coverage directory space. It would be nice if it was just already there.

## Suggested Implementation

npx nx test --coverage produces both the coverage and a node js server script in the coverage root along with one more index.html at the toplevel that gives all the apps/libs. It already works to view coverage within a lib/app.

## Alternate Implementations

n/a?

**Comment by FrozenPandaz** [comment]
I don't think we will implement this. But it does seem handy to have a plugin that handles this.

Would anybody be interested in publishing the plugin?

**Comment by barbados-clemens** [comment]
Probably can simple use the @nrwl/web:file-server to statically serve the file directory

**Comment by barbados-clemens** [comment]
Looks like there isn't anyone who can take this up, 

but leveraging `@nrwl/web:file-server` to do this should be straight forward. target would look something like this. 

```json
"serve-coverage": {
  "executor": "@nrwl/web:file-server",
    "options": { 
      "staticFilePath": "dist/path/to/coverage/directory"
    }
  }
```
