### ISSUE TITLE
Excluding project from affected:build makes the build fail for that project

### ISSUE THREAD

**Issue by trumbitta** [nrwl/nx#1271]
## Expected Behavior

Command:
```
nx affected:build --all --prod --exclude=foo --vendor-chunk --no-progress
```
Running this command builds all apps except for `foo` and exits with success.

## Current Behavior

The command builds every app except for `foo`, but then exists with the following error about `foo`:

```
Running build for affected projects failed.
Failed projects: foo
```

### Context

- version of Nx used: 7.8.0
- version of Angular CLI used: ~7.3.5
- version of Angular DevKit used: ~0.13.0

### Failure Logs

Here's the full redacted log:

```
Running build for affected projects failed.
Failed projects: rest-simulator
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myMonorepo@0.0.0-semantically-released affected:build: `nx affected:build "--all" "--prod" "--exclude=foo" "--vendor-chunk" "--no-progress"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myMonorepo@0.0.0-semantically-released affected:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/williamghelfi/.npm/_logs/2019-04-17T09_01_40_636Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myMonorepo@0.0.0-semantically-released build:ci: `npm run affected:build -- --all --prod --exclude=foo --vendor-chunk --no-progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myMonorepo@0.0.0-semantically-released build:ci script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/williamghelfi/.npm/_logs/2019-04-17T09_01_40_668Z-debug.log
```

**Comment by trumbitta** [comment]
I just tested it with a new workspace and it works as expected.

The difference with my workspace is that the excluded app is a Sails.js app. Is there anything `affected:build` expects to find in the app even if it's excluded with `--exclude`?

**Comment by trumbitta** [comment]
Yep there is: `src/main.ts`.

I added a empty one and the build worked as expected.

I'm not sure `--exclude` should need to check if the excluded app is a "valid" one, though.

**Comment by vsavkin** [comment]
Could you retry with the recent version of Nx?
