### ISSUE TITLE
Input 'production' is not defined after migrating to the last version

### ISSUE THREAD

**Issue by JosepSalvat** [nrwl/nx#12728]
When I run npx nx test features it throws this error

I was working at version 13. something. Now I've updated NX to the last version and it doesn't work. Before that it wasn't working but it was a different error, a test error.

nx report

   Node : 16.14.2
   OS   : linux x64
   yarn : 1.22.18
   
   nx : 15.0.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.0
   @nrwl/js : 15.0.0
   @nrwl/linter : 15.0.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.0
   @nrwl/web : 15.0.0
   @nrwl/webpack : 15.0.0
   @nrwl/workspace : 15.0.0
   typescript : 4.6.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 rxjs: 6.5.5

**Comment by AgentEnder** [comment]
Hey @JosepSalvat can you provide a repo demonstrating the issue for us to investigate?

**Comment by JosepSalvat** [comment]
I did so much things that I don't remember how I solved the issue, sorry. I'll close this issue
