### ISSUE TITLE
Nx tailwind util (globPatternforDependencies) behavior changed after Nx 14.6.2

### ISSUE THREAD

**Issue by aniravi24** [nrwl/nx#12721]
Sorry if this is a duplicate issue, I've looked around and found some similar issues but not sure if any matched this in particular.

## Current Behavior

I started noticing `...createGlobPatternsForDependencies(__dirname)` returns an empty list. It stopped working as I expected with NX 14.6.2. I used to use 14.5.7 and upgraded to the latest version and discovered there was an issue.

It only started working again after the project-specific commands (with the `nx:run-commands` executor and the `cwd` option for that executor) that relied on tailwind were modified to run from the root of the NX monorepo, instead of from the project directory itself (i.e. removing the `cwd` option in the executor). Is this expected behavior going forward? I opened this issue because I wasn't sure if that's the expected behavior going forward (although ideally it could work without being dependent on being run from the root).

## Expected Behavior
I expect it to resolve our project graph and the libraries, instead of returning no results.

It works fine from within a specific app directory in 14.6.1 and below.

I noticed in this release that there's a PR related to tailwind; not sure if this broke the expected behavior.

https://github.com/nrwl/nx/releases/tag/14.6.2 (specific [PR](https://github.com/nrwl/nx/issues/11747))

## Steps to Reproduce

The app-specific tailwind config looks like this, and I run tailwind CLI in that specific app's directory to generate the styles for one of our projects. For another vite-based project, I have a postcss.config.js and our vite config is executed within that project directory.

```

const { join } = require("path");

// available since Nx v 12.5
const { createGlobPatternsForDependencies } = require("@nrwl/react/tailwind");

/** @type {import('tailwindcss').Config} */
module.exports = {
  presets: [require("../../tailwind-workspace-preset.js")],
  content: [
    join(__dirname, "app/**/*.{ts,tsx}"),
    ...createGlobPatternsForDependencies(__dirname)
  ]
};

```

### Failure Logs
I noticed it started showing this error with no changes having been made.

```
[createGlobPatternsForDependencies] WARNING: There was no ProjectGraph available to read from, returning an empty array of glob patterns
```

### Environment

This is the version that it stops working in.

```
 >  NX   Report complete - copy this into the issue template

   Node : 16.18.0
   OS   : linux x64
   yarn : 3.2.4
   
   nx : 14.6.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.6.2
   @nrwl/detox : 14.6.2
   @nrwl/devkit : 14.6.2
   @nrwl/eslint-plugin-nx : 14.6.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.6.2
   @nrwl/js : 14.6.2
   @nrwl/linter : 14.6.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.6.2
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 14.6.2
   @nrwl/react : 14.6.2
   @nrwl/react-native : 14.6.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.6.2
   @nrwl/web : 14.6.2
   @nrwl/workspace : 14.6.2
   typescript : 4.8.4
   ---------------------------------------
   Community plugins:
   	@nrwl/remix: 14.7.0
   	@trumbitta/nx-plugin-unused-deps: 1.12.1
   	nx-plugin-vite: 2.2.1
```

**Comment by ViktorPontinen** [comment]
Hello, got the same issue here using `v15.0.0` of nx.
We also use targets with `nx:run-commands` and `cwd` options pointing to inside each application.
Haven't found any workaround yet but did some debugging in the source code for `createGlobPatternsForDependencies` and it does seem path related as described by OP.
