### ISSUE TITLE
Interactive Tutorials link on default NextJS app is broken

### ISSUE THREAD

**Issue by matjahs** [nrwl/nx#12724]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/react-tutorial/01-create-application?utm_source=nx-project

### Additional context or description

Steps to reproduce:
1. `npx nx generate @nrwl/next:application frontend --style=@emotion/styled --standaloneConfig --no-interactive`
2. `npx nx serve frontend --configuration=development`.
3. Open browser and visit `http://localhost:4200/`.
4. Click the 'Interactive Tutorials` link.

**Comment by AgentEnder** [comment]
This should be fixed in latest, the link changed.
