### ISSUE TITLE
workspace-generator with `wrapAngularDevkitSchematic` and `@nrwl/angular:library` schematic fails with Nx 14+

### ISSUE THREAD

**Issue by adbaran1** [nrwl/nx#12734]
## Current Behavior

After generating a workspace-generator with `npx nx generate workspace-generator` and then modifying it with the following (taken from [Nx Devkit and Angular Devkit](https://nx.dev/more-concepts/nx-devkit-angular-devkit)):
```ts
  const libraryGenerator = wrapAngularDevkitSchematic(
    '@nrwl/angular',
    'library'
  );

  await libraryGenerator(tree, schema);
  ```
 attempting to use the new generator fails with an error (see below).

## Expected Behavior

The generator succeeds and creates an Angular library with the `@nrwl/angular:library` schematic.

## Steps to Reproduce

1. Clone https://github.com/adbaran1/nx-playground
2. `npm i`
3. Attempt `npx nx workspace-generator angular-library sample-lib --dryRun`

### Failure Logs

 ```
 -> % npx nx workspace-generator angular-library sample-lib --dryRun

>  NX  Generating /Users/adbaran/Development/GitHub/adbaran1/nx-playground/dist/out-tsc/tools/generators/workspace-generators.json:angular-library

[NX] Angular devkit called `writeWorkspace`, this may have created 'workspace.json' or 'angular.json
[NX] Double check workspace configuration before proceeding
FileDoesNotExistException [Error]: Path "/libs/sample-lib/.browserslistrc" does not exist.
    at SwitchMapSubscriber.project (/Users/adbaran/Development/GitHub/adbaran1/nx-playground/node_modules/@angular-devkit/core/src/virtual-fs/host/record.js:206:51)
    at SwitchMapSubscriber._next (/Users/adbaran/Development/GitHub/adbaran1/nx-playground/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:47:27)
    at SwitchMapSubscriber.Subscriber.next (/Users/adbaran/Development/GitHub/adbaran1/nx-playground/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:66:18)
    at /Users/adbaran/Development/GitHub/adbaran1/nx-playground/node_modules/rxjs/dist/cjs/internal/operators/switchMap.js:17:192
    at OperatorSubscriber._this._next (/Users/adbaran/Development/GitHub/adbaran1/nx-playground/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at OperatorSubscriber.Subscriber.next (/Users/adbaran/Development/GitHub/adbaran1/nx-playground/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
    at SafeSubscriber.__tryOrUnsub (/Users/adbaran/Development/GitHub/adbaran1/nx-playground/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Users/adbaran/Development/GitHub/adbaran1/nx-playground/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/Users/adbaran/Development/GitHub/adbaran1/nx-playground/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/Users/adbaran/Development/GitHub/adbaran1/nx-playground/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:66:18)

 >  NX   Path "/libs/sample-lib/.browserslistrc" does not exist.

   Pass --verbose to see the stacktrace.
   ```

### Environment

```
 >  NX   Report complete - copy this into the issue template

   Node : 16.15.0
   OS   : darwin arm64
   npm  : 8.5.5

   nx : 15.0.0
   @nrwl/angular : 15.0.0
   @nrwl/cypress : 15.0.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.0
   @nrwl/js : 15.0.0
   @nrwl/linter : 15.0.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.0
   @nrwl/web : Not Found
   @nrwl/webpack : 15.0.0
   @nrwl/workspace : 15.0.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   ```

**Comment by adbaran1** [comment]
From my understanding, the generator attempts to delete the .browserslistrc file. However, that file never gets created in the first place.

In our monorepo, we noticed a number of our libraries contain this file, and are wondering if something changed to include/exclude this file for libraries.

**Comment by srqdeveloper** [comment]
FWIW, commenting out this line seems to get the generator working again. Not sure of the broader implications of that since I couldn't find the source where the `.browserslistrc` was originally created.
[angular/src/generators/library/lib/update-project.js](https://github.com/nrwl/nx/blob/b20c309466c6935c3483b27294396472e31fde0e/packages/angular/src/generators/library/lib/update-project.ts#L53)

**Comment by AgentEnder** [comment]
Can you run `npm ls @angular/core` and respond with its outputs?

**Comment by AgentEnder** [comment]
Additionally, @nrwl/angular is provided as a generator so you may get more perf from using `import {libraryGenerator} from '@nrwl/angular/generators'`

**Comment by adbaran1** [comment]
@AgentEnder 

`npm ls @angular/core` output:
```
├─┬ @angular/animations@14.2.7
│ └── @angular/core@14.2.7 deduped
├─┬ @angular/common@14.2.7
│ └── @angular/core@14.2.7 deduped
├─┬ @angular/compiler@14.2.7
│ └── @angular/core@14.2.7 deduped
├── @angular/core@14.2.7
├─┬ @angular/forms@14.2.7
│ └── @angular/core@14.2.7 deduped
├─┬ @angular/platform-browser-dynamic@14.2.7
│ └── @angular/core@14.2.7 deduped
├─┬ @angular/platform-browser@14.2.7
│ └── @angular/core@14.2.7 deduped
├─┬ @angular/router@14.2.7
│ └── @angular/core@14.2.7 deduped
└─┬ jest-preset-angular@12.2.2
  └── @angular/core@14.2.7 deduped
```
  
Although the `libraryGenerator` does generate a library successfully, it doesn't modify it to become an Angular library, e.g. using `jest-preset-angular` in jest.config.ts, additional ESLint config, etc. If there is a way to specify an additional schematic with `libraryGenerator` so that it can make the proper modifications, that would be great (I have not been able to find a way to do this).

**Comment by AgentEnder** [comment]
Make sure you import the library generator from @nrwl/angular, vs another plugin as that would be required. The function is the same function that runs when you use `nx g @nrwl/angular:lib`, so it should certainly contain the same setup.

**Comment by adbaran1** [comment]
Ah, I totally missed that detail; my mistake!

That seemed to do the trick! Thank you for your help @AgentEnder!

**Comment by Mathieu-DA** [comment]
@AgentEnder  @leosvelperez 

I'm getting the same error as OP when using `@nrwl/angular` **lib generator** in an `@angular-devkit/schematics` **chain** as such:
```
export default function (schema: Schema): Rule {
  return (tree: Tree, context: SchematicContext) =>
    chain([
      () =>
        externalSchematic('@nrwl/angular', 'lib', {
          ...schema,
          unitTestRunner: 'jest',
        }),
      () => schematic('custom-post-lib-logic', { name: schema.name }),
    ])(tree, context)
}
```

I commented the following lines (see below) in `@nrwl/angular/src/generators/library/lib/update-project.js` and without these lines my custom generator works fine. 

```
host.delete((0, devkit_1.joinPathFragments)(options.projectRoot, '.browserslistrc'));
host.delete((0, devkit_1.joinPathFragments)(options.projectRoot, 'karma.conf.js'));
host.delete((0, devkit_1.joinPathFragments)(options.projectRoot, 'src/test.ts'));
```

Please note, I am running this on `nx@15.8.0-beta.5` 

Any idea what may be causing this?
