### ISSUE TITLE
Linting errors aren't thrown in Nx serve

### ISSUE THREAD

**Issue by ribrown-bishs** [nrwl/nx#12748]
## Current Behavior
I have a couple of (intentional) linting errors in my host applications app.tsx file. These show as errors in VSCode from the eslint config/plugin. 
When I run `nx lint` the linting fails, recognizing the errors. 
When I run `nx serve` the linting errors are ignored and the serve/watch continues without showing the errors or exiting. 

Seems that this person has the inverse problem, but I don't even see warnings or errors:
https://github.com/nrwl/nx/issues/12484

This person had a similar question:
https://stackoverflow.com/questions/70304053/how-to-run-nx-serve-for-app-with-lint-errors/74048063#74048063
but it seems that the lint dependency only fails the `npm start` on startup, not while watching.

## Expected Behavior
Errors in the linter should break the serve watch.

## Steps to Reproduce
This setup isn't much further beyond the setup steps provided here:
https://nx.dev/recipes/module-federation/faster-builds

e.g. `nx g @nrwl/react:host host --remotes=shop,cart,about`

This can be reproduced in the example repo. However, I notice that repository is suggesting TSLint as a plugin for the repo.

https://github.com/nrwl/nx-examples/pull/239

### Failure Logs
N/A

### Environment
```
   Node : 16.15.1
   OS   : win32 x64
   npm  : 8.11.0

   nx : 14.8.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.8.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.4
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.8.4
   @nrwl/react-native : Not Found
   @nrwl/rollup : 14.8.4
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.4
   @nrwl/web : 14.8.4
   @nrwl/webpack : 14.8.4
   @nrwl/workspace : 14.8.4
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by AgentEnder** [comment]
Hey @ribrown-bishs! We tend to recommend running lint as a separate step. Linting errors don't prevent the app building by default, and it can slow down the rebuild time and the time it takes devs to iterate.

If you wish to enable this, you'd need to specify it in a custom webpack configuration.
