### ISSUE TITLE
Allow to running unit tests based on tags

### ISSUE THREAD

**Issue by alfaproject** [nrwl/nx#1274]
## Expected Behavior

It would be possible to run test suites based on tags.

## Current Behavior

It's not possible to run test suites based on tags.

### Context

As far as I'm aware tags are only used for linting, but I was wondering why not use the tag system to run tests (or other tasks) for a given tag. One of my monorepos have apps and libs for backend and frontend and it would be really helpful for me to run the test suites only for frontend or only for backend (or other tags).

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.
