### ISSUE TITLE
support for cucumber e2e tests

### ISSUE THREAD

**Issue by remkoboschker** [nrwl/nx#1276]
Have you considered / would you consider supporting (or accepting a pr for) running cucumber tests? It would be nice to have schematics to scaffold feature and step definition files and include the configuration required to run cucumber tests using cypress. There is a cypress plugin that seems a good fit https://github.com/TheBrainFamily/cypress-cucumber-preprocessor.

**Comment by joelmuskwe** [comment]
Any luck with this when i add cypress-cucumber-preprocessor i get the attached error.
<img width="1680" alt="Screenshot 2019-06-18 at 07 14 37" src="https://user-images.githubusercontent.com/5989937/59655355-4cbda980-919a-11e9-9aec-cb318dc8dc7e.png">

I dont know how possible is it to allow the following [`](https://docs.cypress.io/guides/tooling/typescript-support.html#Transpiling-TypeScript-test-files) as per Cypress documentation to enable transpiling TypeScript test files.

**Comment by hnryjms** [comment]
Hi there....

I was able to find a way to do this:

**First, write an alternative `preprocessTypescript()` function** by modifying your `src/plugins/index.js` file like so:

```js
const wp = require('@cypress/webpack-preprocessor');
const { getWebpackConfig } = require('@nrwl/cypress/plugins/preprocessor');

function preprocessTypescript(config) {
   if (!config.env.tsConfig) {
       throw new Error(
           'Please provide an absolute path to a tsconfig.json as cypressConfig.env.tsConfig'
       );
   }

   const webpackConfig = getWebpackConfig(config);

   webpackConfig.node = { fs: "empty", child_process: "empty", readline: "empty" };
   webpackConfig.module.rules.push({
       test: /\.feature$/,
       use: [{
           loader: "cypress-cucumber-preprocessor/loader"
       }]
   }, {
       test: /\.features$/,
       use: [{
           loader: "cypress-cucumber-preprocessor/lib/featuresLoader"
       }]
   });

   return async (...args) => wp({
       webpackOptions: webpackConfig
   })(...args);
}

module.exports = (on, config) => {
   // `on` is used to hook into various events Cypress emits
   // `config` is the resolved Cypress config

   // Preprocess Typescript file using Nx helper
   on('file:preprocessor', preprocessTypescript(config));
};
```

**Then, add a `.cypress-cucumber-preprocessorrc` file to the root of your repo** (or in each `-e2e` app) with this configuration:

```json
{
    "stepDefinitions": "src/support/step_definitions"
}
```

Without the updated `stepDefinitions` configuration, cucumber will continue searching the `cypruss/` instead of `src/` directory of your `-e2e/` folders.

---

It would be nicer if the built-in `preprocessTypescript()` function gave us an optional second argument for modifying the Webpack config file, so we wouldn't need to fork the work of that function. That way we wouldn't be duplicating the `throw new Error` and `return async` parts of NX.

**Comment by hnryjms** [comment]
^ Storybook has a paradigm for [custom webpack config](https://storybook.js.org/docs/configurations/custom-webpack-config/) which may be a good approach here.

**Comment by bhavyamathur** [comment]
@hnryjms I created a similar nx repo and used your suggested cypress cucumber preprocessor plugin configuration, still when I run cypress it creates a cypress folder and tries to find the step definition file in it's new support folder. Can you share how your cypress and tsconfig looks like?

**Comment by vinayakpatil** [comment]
@hnryjms Your solution worked but I have seen a degradation in the test run times. Have you faced anything like it?

I have already logged a separate issue here: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/336

**Comment by D0rmouse** [comment]
@hnryjms Your solution worked, thanks for that.

I'm not able to debug my steps in Cypress though, because the source doesn't seem to be attached. Is that something we could add to the webpack config, or is it a `cypress-cucumber-preprocessor` issue?

**Comment by thinuspainter** [comment]
Can you please get cucumber/gherkin integrated!?

**Comment by dbartholomae** [comment]
@hnryjms Do you have an example repo with your solution? Unfortunately I couldn't get it to run :(

**Comment by remkoboschker** [comment]
I have it running just fine with:
package.json
```
   "cypress": "^4.6.0",
        "cypress-cucumber-preprocessor": "^2.3.1",
.....
 "cypress-cucumber-preprocessor": {
        "nonGlobalStepDefinitions": true,
        "stepDefinitions": "./src/integration",
        "cucumberJson": {
            "generate": true,
            "outputFolder": "./cucumber"
        }
```
/src/plugins/index.js
```
const { getWebpackConfig } = require('@nrwl/cypress/plugins/preprocessor');
const wp = require('@cypress/webpack-preprocessor');

module.exports = function(on, config) {
    const wpConfig = getWebpackConfig(config);
    wpConfig.node = { fs: 'empty', child_process: 'empty', readline: 'empty' };
    wpConfig.module.rules.push({
        test: /\.feature$/,
        use: [
            {
                loader: 'cypress-cucumber-preprocessor/loader'
            }
        ]
    });
    on('file:preprocessor', wp({ webpackOptions: wpConfig }));
};
```
cypress.json
```
{
    "fileServerFolder": "./",
    "fixturesFolder": "./src/fixtures",
    "integrationFolder": "./src/integration",
    "pluginsFile": "./src/plugins/index.js",
    "supportFile": "./src/support/index.ts",
    "video": true,
    "videosFolder": "../../dist/videos",
    "screenshotsFolder": "../../dist/screenshots",
    "chromeWebSecurity": false,
    "testFiles": "**/*.{feature,features}",
    "baseUrl": "https://localhost:4200",
    "ignoreTestFiles": "*.{js,ts}"
}
```

**Comment by huantaoliu** [comment]
> const wp = require('@cypress/webpack-preprocessor');

your solution doesn't work for me, I got error 
`An unhandled exception occurred: The "path" argument must be of type string. Received type undefined`

looking at your setting in package.json (I suppose it is in root), 
`        "stepDefinitions": "./src/integration",
`
wondering how it can find the right location of stepDefinitions since it is under `apps/xx-e2e/src`

**Comment by dbartholomae** [comment]
I didn't get the same error, but got it to work in two steps:
1. I am using TypeScript so I had to include `preprocessTypescript` in the `plugins/index.js` function:
```javascript
const { preprocessTypescript } = require('@nrwl/cypress/plugins/preprocessor');

module.exports = function(on, config) {
  on('file:preprocessor', preprocessTypescript(config, (wpConfig) => {
    wpConfig.node = { fs: 'empty', child_process: 'empty', readline: 'empty' };
    wpConfig.module.rules.push({
      test: /\.feature$/,
      use: [{
        loader: 'cypress-cucumber-preprocessor/loader'
      }]
    });
    return wpConfig
  }));
};
```
2. With the configuration above the step definitions need to be in `src/integration/nameOfFeature/**/*` where `nameOfFeature` is the name of the feature file or `common`. If you disable `nonGlobalStepDefinitions` in `package.json`, step files will be checked directly in `src/integration`.

**Comment by kbradl16** [comment]
@dbartholomae Do you happen to have a working example you can share? I'm not able to get it working with what you have.

I get this error:
`
ReferenceError: The following error originated from your test code, not from Cypress.

  > require is not defined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

Check your console for the stack trace or click this message to see where it originated from.
    at Object.eval (http://localhost/__cypress/tests?p=e2e\src\integration\BasePage.feature:413:1)
    at __webpack_require__ (http://localhost/__cypress/tests?p=e2e\src\integration\BasePage.feature:20:30)
    at Object.eval (http://localhost/__cypress/tests?p=e2e\src\integration\BasePage.feature:91:19)
    at __webpack_require__ (http://localhost/__cypress/tests?p=e2e\src\integration\BasePage.feature:20:30)
    at Object.eval (http://localhost/__cypress/tests?p=e2e\src\integration\BasePage.feature:388:5)
    at __webpack_require__ (http://localhost/__cypress/tests?p=e2e\src\integration\BasePage.feature:20:30)
    at Object.eval (http://localhost/__cypress/tests?p=e2e\src\integration\BasePage.feature:368:18)
    at __webpack_require__ (http://localhost/__cypress/tests?p=e2e\src\integration\BasePage.feature:20:30)
    at eval (http://localhost/__cypress/tests?p=e2e\src\integration\BasePage.feature:84:18)
    at eval (http://localhost/__cypress/tests?p=e2e\src\integration\BasePage.feature:87:10)
From previous event:
    at Object.runScripts (http://localhost/__cypress/runner/cypress_runner.js:176237:96)
    at $Cypress.onSpecWindow (http://localhost/__cypress/runner/cypress_runner.js:166148:18)
`

**Comment by dbartholomae** [comment]
Unfortunately not :(

**Comment by agborkowski** [comment]
@kbradl16 ill publish the completed integration of NX workspace with angular and cucumber. watch my GitHub profile. cheers

**Comment by mattgek** [comment]
any update on cypress + cucumber in nx ?

**Comment by zjkipping** [comment]
Is there any update on this? The above example @dbartholomae listed doesn't work with webpack5 on nx12.3.4, cypress 6.0.1, & cypress-cucumber-preprocessor 4.1.0.

**Comment by rkrisztian** [comment]
### For Webpack 5

I got a working solution, practically using @dbartholomae 's config, with the same solutions as the ones I googled up before for a regular Angular CLI 12 generated project (without using @nrwl/nx).

My idea was to:

* let both Cucumber and regular tests be executed (can be handy)
* have the step definitions inside `src/integration` (this is the new way recommended by the preprocessor)

Based on that:

1. Add to `cypress.json`:

```javascript
{
  // ...
  "testFiles": "*.{ts,feature,features}",
  "ignoreTestFiles": "**/*.js"
}
```

2.  Add to `package.json`:

```javascript
{
  // ...
  "cypress-cucumber-preprocessor": {
  "nonGlobalStepDefinitions": true,
  "stepDefinitions": "./src/integration"
  }
}
```

3. Set up `support/index.js` like this (I've removed the comments for brevity here, but you keep them if you want):

```javascript
const { preprocessTypescript } = require('@nrwl/cypress/plugins/preprocessor');
const webpack = require('webpack');

module.exports = (on, config) => {
  on('file:preprocessor', preprocessTypescript(config, (wpConfig) => {
    wpConfig.resolve.fallback = {
      ...wpConfig.resolve.fallback,
      "path": require.resolve("path-browserify")
    };
    wpConfig.plugins = [
      ...wpConfig.plugins,
      new webpack.ProvidePlugin({
        process: 'process/browser',
      })
    ];
    wpConfig.module.rules.push(
      {
        test: /\.feature$/,
        use: [{
          loader: 'cypress-cucumber-preprocessor/loader'
        }]
      },
      {
        test: /\.features$/,
        use: [{
          loader: "cypress-cucumber-preprocessor/lib/featuresLoader"
        }]
      }
    );
    return wpConfig
  }));
};
```

**Comment by rkrisztian** [comment]
With a more recent version of `@nrwl/cypress`, you may have seen this message:

```none
preprocessTypescript is now deprecated since Cypress has added typescript support.
If you would still like preprocess files with webpack, use the "@cypress/webpack-preprocessor" package.
```

That is a problem because **we still need a webpack configuration, but now we don't have the help of Nx**. According to [Nx's `preprocessor.ts`](https://github.com/nrwl/nx/blob/master/packages/cypress/src/plugins/preprocessor.ts), `getWebpackConfig` is not yet deprecated, and still a publicly available function, but something tells me it's going to get removed along with the deprecation, so I don't think the following code should be used to remove the deprecation:

<details>
<summary>Click to expand the *wrong* solution...</summary>
Only showing the changes to my previous example code:

```diff
diff --git a/path-to-project/src/plugins/index.js b/path-to-project/src/plugins/index.js
index 968157c..d5cc2f2 100644
--- a/path-to-project/src/plugins/index.js
+++ b/path-to-project/src/plugins/index.js
@@ -1,8 +1,11 @@
-const { preprocessTypescript } = require('@nrwl/cypress/plugins/preprocessor');
+const webpackPreprocessor = require('@cypress/webpack-preprocessor')
+const { getWebpackConfig } = require('@nrwl/cypress/plugins/preprocessor');
 const webpack = require('webpack');
     
 module.exports = (on, config) => {
-  on('file:preprocessor', preprocessTypescript(config, (wpConfig) => {
+  on('file:preprocessor', webpackPreprocessor((() => {
+    const options = { webpackOptions: getWebpackConfig(config) };
+    const wpConfig = options.webpackOptions;
     wpConfig.resolve.fallback = {
       ...wpConfig.resolve.fallback,
       'path': require.resolve('path-browserify')
@@ -26,6 +29,6 @@ module.exports = (on, config) => {
         }]
       }
     );
-    return wpConfig
-  }));
+    return options;
+  })()));
 };
```
</details>

However, a more future-proof solution may look like this (you might need to install some packages if Nx no longer provides them transitively). Sadly it's quite some code copied out of `preprocessor.ts`, and I don't know any better, but it works at least:

```javascript
/// <reference types="cypress" />

const webpackPreprocessor = require('@cypress/webpack-preprocessor')
const webpack = require('webpack');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
const nodeExternals = require('webpack-node-externals');

/**
 * @type {Cypress.PluginConfig}
 */
module.exports = (on, config) => {
  on('file:preprocessor', webpackPreprocessor({
    webpackOptions: {
      resolve: {
        extensions: ['.ts', '.tsx', '.mjs', '.js', '.jsx'],
        plugins: [
          new TsconfigPathsPlugin({
            configFile: config.env.tsConfig,
            extensions: ['.ts', '.tsx', '.mjs', '.js', '.jsx']
          }),
        ],
        fallback: {
          'path': require.resolve('path-browserify')
        }
      },
      module: {
        rules: [
          {
            test: /\.([jt])sx?$/,
            loader: 'ts-loader',
            exclude: [/node_modules/],
            options: {
              configFile: config.env.tsConfig,
              // https://github.com/TypeStrong/ts-loader/pull/685
              experimentalWatchApi: true,
              transpileOnly: true
            }
          },
          {
            test: /\.feature$/,
            use: [{
              loader: 'cypress-cucumber-preprocessor/loader'
            }]
          },
          {
            test: /\.features$/,
            use: [{
              loader: 'cypress-cucumber-preprocessor/lib/featuresLoader'
            }]
          }
        ]
      },
      plugins: [
        new ForkTsCheckerWebpackPlugin({
          typescript: {
            enabled: true,
            configFile: config.env.tsConfig,
          },
        }),
        new webpack.ProvidePlugin({
          process: 'process/browser',
        })
      ],
      externals: [nodeExternals()]
    },
  }));
}
```

**Comment by wrslatz** [comment]
> What do you think about this config ? It works running cypress run but not nx e2e
> I saw somewhere that TS was supported by default for Cypress and we don't need preprocessing anymore

I tried the `browserify` + `resolve` setup and it works fine for TypeScript but doesn't work for configured `paths` aliases, which is what we're trying to find a solution for here.

**Comment by Yohandah** [comment]
> > What do you think about this config ? It works running cypress run but not nx e2e
> > I saw somewhere that TS was supported by default for Cypress and we don't need preprocessing anymore
> 
> I tried the `browserify` + `resolve` setup and it works fine for TypeScript but doesn't work for configured `paths` aliases, which is what we're trying to find a solution for here.
> 

I thought we were trying to find a solution to use cucumber tests with nx? And I'm using typescript aliases and it works fine as well

**Comment by MRisto** [comment]
Hey guys. I have the same problem with cypres cucumber and paths. Did you find a solution, where all 3 of them work? And do you still use the nx preprocessor?

**Comment by wrslatz** [comment]
The custom webpack config in https://github.com/nrwl/nx/issues/1276#issuecomment-934324523 along with merging the `tsconfig.e2e.json` into `tsconfig.json` as described in https://github.com/nrwl/nx/issues/6917#issuecomment-962011692 fixed loading paths for us 🎉 (sorry for the delay in getting back to y'all)

**Comment by zauni** [comment]
Just adding it here if anyone comes to this thread later. With the new [@badeball/cypress-cucumber-preprocessor](https://github.com/badeball/cypress-cucumber-preprocessor) you can simplify the configuration in the `plugins/index.js` file.

First you have to install the dependencies:
`npm install --save-dev @badeball/cypress-cucumber-preprocessor @bahmutov/cypress-esbuild-preprocessor`

Then you  can add to your `plugins/index.js` file:

```javascript
/** @see https://on.cypress.io/plugins-guide */
const createBundler = require('@bahmutov/cypress-esbuild-preprocessor');
const {
  createEsbuildPlugin,
} = require('@badeball/cypress-cucumber-preprocessor/esbuild');
const {
  addCucumberPreprocessorPlugin,
} = require('@badeball/cypress-cucumber-preprocessor');

/// <reference types="cypress" />

/**
 * @type {Cypress.PluginConfig}
 */
module.exports = async (on, config) => {
  await addCucumberPreprocessorPlugin(on, config);

  on(
    'file:preprocessor',
    createBundler({
      plugins: [createEsbuildPlugin(config)],
    })
  );

  return config;
};
```

You also have to change your config, for example in `.cypress-cucumber-preprocessorrc.json`:

```diff
{
-  "nonGlobalStepDefinitions": true,
-  "stepDefinitions": "./src/integration",
-  "commonPath": "./src/integration/common"
+  "stepDefinitions": [
+    "./src/integration/[filepath]/**/*.ts",
+    "./src/integration/common/*.ts"
+  ]
}
```

But please be aware that with the `esbuild` based preprocessor you can not use Node.js APIs in your spec files or in your `support` files. In my case I had to replace my calls to the `path` lib. For example I used the `path.join` and `path.basename` calls. Probably webpack is using a shim for the Node.js libraries, but esbuild is not adding them.
If you need Node.js libraries or just want to stick to webpack, the preprocessor also offers this. Please see [here](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/examples/webpack-cjs/cypress.config.js).
