### ISSUE TITLE
Project dependencies does not recognize files inside nested git repositories

### ISSUE THREAD

**Issue by ramyhhh** [nrwl/nx#12767]
## Current Behavior

If an app or a lib is a part of nested git repo the `dep-graph` does not recognize their dependencies. Much like the old [issue](https://github.com/nrwl/nx/issues/10903) regarding git submodules. This limitation will affect all project dependency related operations such as the flag `generatePackageJson`.

## Expected Behavior

Project dependencies should recognize all files inside the folder regardless if those files are tracked by a nested git repo or not.

## Steps to Reproduce

* Create a nx workspace
* Navigate to `libs` dir
* Clone an empty repo (example `git clone lib-a`)
* Generate library project inside `lib-a`
* Create a project and import the generated library
* run `dep-graph` and it won't show that the app has a dependency on the library

### Environment

```
Node : 18.3.0
OS   : darwin x64
npm  : 8.11.0

nx : 14.4.0
@nrwl/angular : 14.4.3
@nrwl/cypress : 14.4.3
@nrwl/detox : Not Found
@nrwl/devkit : 14.4.3
@nrwl/eslint-plugin-nx : 14.4.3
@nrwl/express : 14.4.3
@nrwl/jest : 14.4.3
@nrwl/js : 14.4.3
@nrwl/linter : 14.4.3
@nrwl/nest : 14.4.3
@nrwl/next : Not Found
@nrwl/node : 14.4.3
@nrwl/nx-cloud : Not Found
@nrwl/nx-plugin : Not Found
@nrwl/react : Not Found
@nrwl/react-native : Not Found
@nrwl/schematics : 8.12.11
@nrwl/storybook : 14.4.3
@nrwl/web : 14.4.3
@nrwl/workspace : 14.4.3
typescript : 4.7.4
---------------------------------------
Community plugins
```

**Comment by ramyhhh** [comment]
I have a good idea why this is happening as I wrote the previous [PR](https://github.com/nrwl/nx/pull/11334) that was fixing a pretty similar issue, however this time the fix is more profound because `git-hasher` will not be able to immediately learn about the nested repos.

I agree that nested repos are not used that much frequently and I think lots changes are required to cover for this.

**Comment by agallardol** [comment]
Last week I was fighting with this issue and trying to solve it. I was building a PR very similar to #11334 but then I noticed it was reverted.

After a lot of tests I noticed when you do inside a git project:

```
git clone lib-a
```

It clones the project but It doesn't create the ```./.git/modules``` folders and if we review NX code about file-hasher

https://github.com/nrwl/nx/blob/8fcc2b4a58e0f427c04f9940d265f6ce30c58838/packages/nx/src/hasher/file-hasher.ts#L17

We are checking If that folder exists, so in this "buggy" case we hash files our repository with submodules as a classic git repository and this behavior produces that generatePackageJson flag or nx-graph doesn't work with submodules because the project graph is calculated over an empty folder (no hashes are created).

**Comment by ramyhhh** [comment]
To be honest, I'm not sure why dependencies are built based on files tracked by `git` instead of just listing existing files using the file system.
Dependencies should work on a workspace even if it's not a part of git repository at all, and in that approach all issues related to `git` won't occur in addition to making the code cleaner by avoiding the 3 methods in `git-hasher` to merge tracked, staged, and untracked files.

**Comment by agallardol** [comment]
According to my understanding about NX the GitHasher is used only when the project doesn't has submodules. All other cases It uses NodeBasedFileHasher which read files using fs.

I think GitHasher is used to improve the performance of some tasks recurrent tasks (I still need to understand better the whole process)

https://github.com/nrwl/nx/blob/5837715aeed4f46188ffa23305d85514b496df37/packages/nx/src/hasher/git-based-file-hasher.ts#L10

**Comment by ramyhhh** [comment]
I can see that git is tracking changes and therefore no need to walk through directories each time. However, that can be optimized and the big win here is to decouple Nx from git.

**Comment by FrozenPandaz** [comment]
Yes the hasher should handle this case as you've mentioned.

Could somebody please provide a repo which we can use to reproduce the issue?
