### ISSUE TITLE
Can't test one folder of lib separatly, even without creating a project.json

### ISSUE THREAD

**Issue by JosepSalvat** [nrwl/nx#12774]
I've been struggle with this problem for almost a week and I can't find a solution
We've a nx repo with 2 apps, 1 folder (libs) with many libs and I want to test with one command, all the features inside libs.

The structure of the project more or less is:

apps
----app1
----app2
 libs
----lib1 (redux)
----lib2 (uiComponents)
----lib3 (features)
----feature1
----feature2
   - ...
   
 I tried to add a project.json to libs/features, so then I can aim then to test only features (one by one). I can throw the command but it fails with error: `npx nx test feature1`
 
 `● Test suite failed to run

    Cannot find module '@myApp/api' from '../stores/someStoreFromRedux/src/lib/epics/Epic.ts'
`

Another example
`Cannot find module '@myApp/ui/components' from 'feature1/src/lib/SomeComponent/SomeSubComponent/Component.tsx'`

It seems that for some reason, doesn't find the other libs inside one lib when running tests.

## Expected Behavior
I should have the possibility to test libs one by one

## Steps to Reproduce
npx nx test libName

Note on the versions. I tried to update to v15 and then the last one of v14 (I had some issues with V15) and it's happening the same.

 nx : 13.4.6
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.3
  @nrwl/cypress : 13.4.3
  @nrwl/devkit : 13.4.3
  @nrwl/eslint-plugin-nx : 13.4.3
  @nrwl/express : undefined
  @nrwl/jest : 13.4.3
  @nrwl/linter : 13.4.3
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : 13.0.2
  @nrwl/react : 13.4.3
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.3
  @nrwl/web : 13.4.3
  @nrwl/workspace : 13.4.3
  @nrwl/storybook : 14.4.3
  @nrwl/gatsby : undefined
  typescript : 4.6.3
  rxjs : 6.5.5
  ---------------------------------------
  Community plugins:
  	 @nrwl/js: 13.4.3
  	 
  	 
 Project.json on the feature lib
 `{
    "root": "features",
    "sourceRoot": "libs/features",
    "projectType": "library",
    "jestConfig": "./jest.config.js",
    "namedInputs": {
      "default": ["{projectRoot}/**/*"],
      "production": ["!{projectRoot}/**/*.spec.tsx"]
    },
    "targets": {
      "test": {
        "executor": "@nrwl/jest:jest",
        "inputs": ["default", "^production"],
        "outputs": [],
        "options": {
            "jestConfig": "libs/features/jest.config.js",
            "passWithNoTests": true
        }
      }
    }
  }`

**Comment by FrozenPandaz** [comment]
That command should work.

Can you please share a repo where we can reproduce the issue? It will help us help you.

**Comment by barbados-clemens** [comment]
Sounds like your root jest.preset.js isn't set up correct and is missing the nx resolver from the nxPreset. Can you please provide a reproducible?
