### ISSUE TITLE
how to add a third party package to a nx project?

### ISSUE THREAD

**Issue by xwillmadeit** [nrwl/nx#12779]
Sorry I cannot find the nx command to add a package like angular-cli does, such as "ng add ng-zorro"

**Comment by bulldog98** [comment]
install the package manually and then run nx g ng-zorro:ng-add

**Comment by xwillmadeit** [comment]
> install the package manually and then run nx g ng-zorro:ng-add

SchematicsException [Error]: Bootstrap call not found
    at findBootstrapModulePath (/Users/xwill/work/learn-nx/iris/node_modules/@schematics/angular/utility/ng-ast-utils.js:66:15)
    at getAppModulePath (/Users/xwill/work/learn-nx/iris/node_modules/@schematics/angular/utility/ng-ast-utils.js:85:32)

**Comment by AgentEnder** [comment]
@xwillmadeit you probably need to pass `--project {my-ng-app}` as well.

**Comment by xwillmadeit** [comment]
> nx g ng-zorro:ng-add

pass --project also not works

**Comment by readonlyden** [comment]
While it works, it's not very convenient and it seems that `ng` decoration is not working properly
