### ISSUE TITLE
`@nrwl/angular:package` + `@zerollup/ts-transform-paths` - how to use?

### ISSUE THREAD

**Issue by Azbesciak** [nrwl/nx#12778]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?
No really, I have checked https://nx.dev/recipes/other/customize-webpack but the refeference for angular is a bit obsolere and not strict to my needs; angular 14 (15), generating lib.

The issue is that I have no idea how to use `@zerollup/ts-transform-paths` with the `@nrwl/angular:package` executor.
- I did as described in https://www.npmjs.com/package/@zerollup/ts-transform-paths
  - tsconfig's plugins do not work
  - custom webpack is not attached
  - rollup config is not picked up
 - also `@nrwl/angular:package` does not accept `webpackConfig` field, so I cannot do anything.
 
- I also saw https://github.com/nrwl/nx/issues/7123 and I am a bit lost...
- https://github.com/nrwl/nx/issues/3259 -  there I even do not know what is going on, these files are no longer available. I would understand that you managed to flatten aliases on your own, except that this is not the truth for now.

So what shall I do? I have a bit complex (4 years of development) app, which parts (95%) I need to extract to the lib. The problem is I have used path aliases a lot.

Thanks

**Comment by leosvelperez** [comment]
Thanks for reporting this!

The `@nrwl/angular:package` doesn't directly build libraries. It uses `ng-packagr` under the hood which is the Angular official tool for building libraries. Please note that `ng-packagr` doesn't use webpack and it doesn't use Rollup to compile the library source code, only to create the bundles defined by the Angular Package Format.

You can ask in the `ng-packagr` repo whether it is possible to use ` @zerollup/ts-transform-paths` with it.
