### ISSUE TITLE
nx affected ignores --configuration argument

### ISSUE THREAD

**Issue by devhid** [nrwl/nx#12789]
## Current Behavior

Given a configuration in my app's `project.json` for testing a certain configuration:
```
        "test": {
            "executor": "@nrwl/jest:jest",
            "outputs": ["coverage/apps/app-server"],
            "options": {
                "jestConfig": "apps/app-server/jest.config.ts",
                "passWithNoTests": true
            },
            "configurations": {
                "pact": {
                    "jestConfig": "apps/app-server/jest.pacts.config.ts",
                    "passWithNoTests": true,
                    "testFile": "apps/app-server/tests/pact/consumer/app-api.pact.ts"
                }
            }
        }
```

Running `nx affected --target=test --configuration=pact` still runs all affected tests despite that I specified the `--configuration=pact` argument.

## Expected Behavior

I expect that only affected projects with a target of `test` AND configuration of `pact` to be targeted.

## Steps to Reproduce

I think the easiest way to reproduce is to just create two projects with `test` targets, but add a configuration to one of them and run `nx affected --target=test --configuration=<configuration>`

### Failure Logs

```
> nx affected --target=test --configuration=pact --parallel
>  NX  Running target test for 12 project(s):
  - app-api
  - app-server
  - config-base
  - config-nest
  - core-app-server
  - core-app-api
  - logger
  - config-ng
  - front-end-app
  - core-front-end
  - dto
  - entities
```

### Environment

```
  Node : 14.20.0
  OS   : darwin x64
  npm  : 6.14.17
  
  nx : 13.1.4
  @nrwl/angular : 13.1.4
  @nrwl/cli : 13.1.4
  @nrwl/cypress : 13.1.4
  @nrwl/devkit : 13.1.4
  @nrwl/eslint-plugin-nx : 13.1.4
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.4
  @nrwl/linter : 13.1.4
  @nrwl/nest : 13.10.6
  @nrwl/next : Not Found
  @nrwl/node : 13.1.4
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.4
  @nrwl/web : 13.10.6
  @nrwl/workspace : 13.1.4
  @nrwl/storybook : 13.1.4
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by FrozenPandaz** [comment]
A long time ago, this actually used to be the behavior. We intentionally changed it but unfortunately I don't recall off the top of my head why we did so.

Question for you, why do some of those projects have that configuration while others don't?

If they are a separate set of tests, I would suggest creating 2 different targets for them: `test` vs `test-pact`. And that will give you the behavior you want as well as a cleaner API (`nx test-pact proj1` vs `nx test proj1 --configuration pact`).
