### ISSUE TITLE
Generators having a `project.json` are now included in `run-many` & `affected`

### ISSUE THREAD

**Issue by Erazihel** [nrwl/nx#12781]
Hey there 👋 

## Current Behavior
When I run commands like:

```
nx run-many --target=test
nx affected --target=type --base=main
```

Generators are now included in these commands.

    ✖    3/28 targets failed, including the following:
         - nx run tools-generators-container-files:test
         - nx run tools-generators-micro-frontend-files:test
         - nx run tools-generators-lib-files:test

## Expected Behavior

Generators should not be taken in account when using `run-many` or `affected` commands.

This is a regression since it was working fine in `v15.0.0`.

I guess this has something to do with [this commit](https://github.com/nrwl/nx/commit/272abb4f3ee8134269ffa0863dcaee6de63a1254).

## Steps to Reproduce

Clone this [repo](https://github.com/Erazihel/nx-examples).

Run the following command:

```
nx run-many target=test
```

The following error will be thrown:

    >    NX   Ran target test for 10 projects (1m)

    ✔    9/10 succeeded [0 read from cache]

    ✖    1/10 targets failed, including the following:
         - nx run tools-generators-micro-frontend-files:test

### Failure Logs

>    ✖    3/28 targets failed, including the following:
         - nx run tools-generators-container-files:test
         - nx run tools-generators-micro-frontend-files:test
         - nx run tools-generators-lib-files:test

### Environment

```
~> nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.3.0
   OS   : darwin x64
   yarn : 1.22.19

   nx : 15.0.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.1
   @nrwl/js : 15.0.1
   @nrwl/linter : 15.0.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.1
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.1
   @nrwl/web : 15.0.1
   @nrwl/webpack : 15.0.1
   @nrwl/workspace : 15.0.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   	 undefined
   ---------------------------------------
   Community plugins:
   	 @jscutlery/semver: 2.27.1
   	 @nx-tools/nx-docker: 3.0.5
```

PS: If this a desired behaviour then I'm sorry for reporting this issue. I found no documentation about it though.

**Comment by woppa684** [comment]
This is probably related to https://github.com/nrwl/nx/commit/272abb4f3ee8134269ffa0863dcaee6de63a1254

**Comment by AgentEnder** [comment]
This is related to above, but would be an issue regardless when moving away from `workspace.json`. You should update those paths to be `project.json__tmpl__` or similar, in the same way that you do with typescript files to prevent them from being compiled.

**Comment by Erazihel** [comment]
@AgentEnder I don't know why I did not think about this. Works like a charm 👌 Thank you so much!
