### ISSUE TITLE
ng build command gives always same error for an existing angular + nestjs project

### ISSUE THREAD

**Issue by akash-mahmud** [nrwl/nx#12800]
this is my nx report

` >  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : win32 x64
   yarn : 1.22.19
   
   nx : 14.3.6
   @nrwl/angular : 14.3.6
   @nrwl/cypress : 14.3.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : 14.3.6
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.6
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.3.6
   @nrwl/nest : 14.3.6
   @nrwl/next : Not Found
   @nrwl/node : 14.3.6
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.3.6
   @nrwl/web : 14.3.6
   @nrwl/workspace : 14.3.6
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
         apollo-angular: 3.0.1
         ng-zorro-antd: 13.4.0
         @nxrocks/nx-flutter: 3.0.2`

I don't know why the project is successfully running on docker but whenever I am trying to build it on my local machine or I am trying to serve an app I am getting this issue. The project is in angular, nest js, and flutter. But I just need to work on the server so I need to run it on my local. But the server app is not running at all and gives this issue. 
![image](https://user-images.githubusercontent.com/87032071/197680571-d466555d-b573-4ec6-8970-1c3be2c52783.png)
![image](https://user-images.githubusercontent.com/87032071/197680652-ae4fa9ee-4373-43d6-ada6-07603157f01f.png)
I have deleted node_modules multiple times. No matter what I am doing but it is not working at all. All the time I am getting this same issue `Error: Cannot find module 'nx/src/utils/app-root'`
And one please help me. Any help or suggestion will be appreciated. 
Thanks in advance.

**Comment by Coly010** [comment]
It looks like this is an issue with `@nxrocks/nx-flutter` rather than Nx. They must be using an outdated version of Nx being resolved for their package as I can see the `@nrwl/devkit` package is being resolved under a separate `node_modules` under `nx-flutter`.

Can you try migrate to latest, for both Nx and Nx Flutter, their latest version is 5 and our latest version is 15?

`nx migrate latest && nx migrate --run-migrations`

**Comment by akash-mahmud** [comment]
Hi, 
The first command has completed its process successfully. But in the second command, I got this issue 
![image](https://user-images.githubusercontent.com/87032071/198681362-9f42002a-8069-47f6-9b81-5b11d529a3f7.png)

**Comment by Coly010** [comment]
Yes, it looks like you have a package resolution issue with `@nxrocks`. It's hoisting an old version of Nx which is being used. You'll need to update to the latest versions of those packages first, and then run the migrations.

**Comment by akash-mahmud** [comment]
what command should I use? This is a script that is purchased from codecanyon. And my client wants to do some external modifications. The project is running and building using their official docker images. In this case, probably that is updated. But as I am saying here we are adding new features according to our needs we are trying to build the project locally and also changing the docker-compose files with local file build context instead of docker hub live images. 
At that time I am getting this issue. 
No matter where I am trying to build but this issue is happening. 
If you suggest some commands which I should use to update specific packages it will be better. Because if we update all dependencies of the whole package.json it can break the whole project because of the version-changing features.
Thanks in advance.

**Comment by Coly010** [comment]
try: `npm install @nxrocks/nx-flutter@latest`

**Comment by Coly010** [comment]
It'll probably be better to talk to the author of the script you purchased for support. This is an issue outside of Nx.

Because of this, I'll close the issue, but if I have time, I'll continue to assist.
