### ISSUE TITLE
Nx "ignore" parameter inside package.json doesn't work in Nx 15.0.1

### ISSUE THREAD

**Issue by B1Z1** [nrwl/nx#12807]
Hi! In your documentation I found that I can ignore application from graph by adding "ignore" parameter to package.json

https://nx.dev/reference/project-configuration#ignoring-a-project

## Current Behavior
It doesn't work. Application is visible in graph application and every affected command fails to build this application

## Expected Behavior
Dependency graph doesn't show the app and affected commands ignore application with parameter "ignore"

## Steps to Reproduce
Try to clone this repo

https://github.com/B1Z1/nx-package-error

and execute:

yarn nx dep-graph

or

Change something inside dev/dev-test/index.js
yarn nx affected --target="test"

### Failure Logs
 >  NX   Ran target test for 1 projects (1s)
 
    ✔    0/1 succeeded [0 read from cache]
 
    ✖    1/1 targets failed, including the following:
         - nx run dev-test:test
       
<img width="2026" alt="Screenshot 2022-10-25 at 14 40 10" src="https://user-images.githubusercontent.com/38375468/197775426-4c69bb1c-3cd0-4072-a485-a2cf3c55035b.png">

### Environment
   Node : 16.16.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 14.8.6
   @nrwl/angular : 14.8.6
   @nrwl/cypress : 14.8.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.6
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.6
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.6
   @nrwl/js : 14.8.6
   @nrwl/linter : 14.8.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.6
   @nrwl/web : Not Found
   @nrwl/webpack : 14.8.6
   @nrwl/workspace : 14.8.6
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   Unable to construct project graph
   ---------------------------------------
   Community plugins:

**Comment by FrozenPandaz** [comment]
The workaround would be to add the directory to `.nxignore`.

**Comment by B1Z1** [comment]
Workaround helped

**Comment by B1Z1** [comment]
@AgentEnder are you sure that we can close the ticket? Because main feature doesn't work properly. "ignore" parameter in package.json is ignored by nx :D

**Comment by AgentEnder** [comment]
It was never implemented, the fix was to change the docs

**Comment by B1Z1** [comment]
Ok, thank you
