### ISSUE TITLE
The "affected" command shows not existing projects

### ISSUE THREAD

**Issue by kazamov** [nrwl/nx#12808]
## Current Behavior
After the update from 14.8.3 to 15.0.2 when I run the "affected" command for the workspace I see the projects those do not exist in my workspace. As I see their names are built from the projects' paths instead of using them from the workspace.json file.

E.g. I have a library in the "libs/shared/components". In the workspace.json I have a record in the **"projects" section _"constants": "libs/shared/constants"_**. When I run the "affected" command I get the "component" and the "shared-components".

## Expected Behavior
When I run the "affected" command I should get the projects described in the workspace.json if it exists. 

## Steps to Reproduce
1. Create an Nx workspace version 14.8.3.
2. Generate a library in the "libs/shared/components" and use it in the app.
3. Update the alias in the workspace.json file in the "projects" section from "shared-components" to "components".
4. Migrate Nx to the 15.0.2.
5. Run the "affected" command e.g. for linting. You will see two projects instead of one.

**Comment by AgentEnder** [comment]
This is a known issue that a fix is coming for.
