### ISSUE TITLE
generateFiles doesn't write to outputPath when called inside a watcher

### ISSUE THREAD

**Issue by skog-newglue** [nrwl/nx#12802]
## Current Behavior
Calling `generateFiles` from `@nrwl/devkit` works fine when doing it once but if you also want to have a watcher listen for file changes it doesn't create or update the file at the output path when the watcher callback runs.

## Expected Behavior
I would expect the same behavior regardless of when `generateFiles` is called. From my investigations `tree.write` inside `generateFiles` runs properly, but the file is never written.. I tried looking inside that function to see what is happening but I couldn't see what is actually writing the file in the first place. I'm not sure if this is a regression or not but most likely isn't.

## Steps to Reproduce

1. Create a `.env` file with any variable and value
2. Create a `.env.d.ts__tmpl__` file in the same scope as the generator `index.ts` file with the following code:

```
declare global {
  namespace NodeJS {
    interface ProcessEnv {
      <% for(const prop in env) { -%>
        <%- JSON.stringify(prop) %>: string;
      <% } %>
    }
  }
}
export {};
```

3. Add a generator with the following code:

```
import * as dotenv from 'dotenv';
dotenv.config();

import { generateFiles, Tree } from '@nrwl/devkit';
import { output } from '@nrwl/workspace/src/utils/output';
import watch from 'node-watch';

import { NxEnvOptions } from './types';

const NAME = 'nx-env';
const templatesPath = `tools/generators/${NAME}`;

function title(key = '') {
  return [NAME, key].filter(Boolean).join(': ');
}

function createTypeDefinitionFile(tree: Tree) {
  // Load the updated variables into process.env
  dotenv.config();

  const outputPath = '__generated__';

  generateFiles(tree, templatesPath, outputPath, {
    tmpl: '',
    env: process.env,
  });

  output.success({ title: title(`Files generated at: ${outputPath}`) });
}

export default async function (tree: Tree, schema: NxEnvOptions) {
  output.note({ title: title('Generating...') });

  watch('.env', { persistent: true }, () => {
    createTypeDefinitionFile(tree);
  });

  createTypeDefinitionFile(tree);

  return async () => {
    output.note({ title: title('Listening for changes...') });
  };
}
```

4. Run the generator with `nx workspace-generator nx-env`
5. Check that the generated `.env.d.ts` file has been created in the `__generated__` folder
6. Add a new variable to `.env` or change the existing variable name (not value)
7. Notice how the file isn't updated.

### Failure Logs
No errors are thrown.

### Environment
```
 Node : 16.18.0
   OS   : darwin x64
   npm  : 8.19.2
   
   nx : 14.3.2
   @nrwl/angular : 14.3.2
   @nrwl/cypress : 14.3.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.2
   @nrwl/eslint-plugin-nx : 14.3.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.2
   @nrwl/js : Not Found
   @nrwl/linter : 14.3.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.1.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.3.2
   @nrwl/web : Not Found
   @nrwl/workspace : 14.3.2
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
   	 @nguniversal/express-engine: 13.0.2
   	 rxjs: 6.6.7
   	 @nguniversal/builders: 14.0.1
   	 @storybook/angular: 6.5.9
```

**Comment by AgentEnder** [comment]
Generators don't write to disk until after they complete. This is by design, as it enables dry run and similar. This reads more like an executor to me.

If you want to still use `generateFiles` as provided in `@nrwl/devkit`, you could do so by splitting out the watching behavior into an executor, which invokes your generator.

I'd recommend updating it to an executor along the lines of:

```
export default async function runExecutor(
  options: Schema,
  context: ExecutorContext,
) {
  watch('.env', { persistent: true }, () => {
	execSync('nx g @workspace/plugin:typedef-file')
  });

	execSync('nx g @workspace/plugin:typedef-file')

  return async () => {
    output.note({ title: title('Listening for changes...') });
  };
}
```

**Comment by skog-newglue** [comment]
@AgentEnder Ok thanks for clarifying that. What is this `@workspace/plugin:typedef-file` thing? Are you suggesting I create a plugin for the general behavior of the generator/executor? If so, why?

**Comment by AgentEnder** [comment]
It's much, much cleaner to use a workspace plug-in for executors, and I'm working on migrations as we speak for converting existing workspace-generators to a plug-in.

**Comment by skog-newglue** [comment]
@AgentEnder Gotcha. Been reading the docs on plugins now but it's still a bit hard to grasp.

Am I correct that I should create one plugin for my entire workspace where I put all my generators and executors that just helps with the development experience? Like a `workspace-automation` plugin for example.

**Comment by AgentEnder** [comment]
Yeah, unless you are planning to publish it there's no reason to separate things out.

**Comment by skog-newglue** [comment]
@AgentEnder Gotcha. What about the `Tree` though, how do you access that in an executor if I am to use `generateFiles` in an executor instead of a generator?

**Comment by AgentEnder** [comment]
I'd invoke the generator through execsync or similar inside your executor code. You don't have access to a tree as you have seen.

Alternatively, use node fs to write the files and you can use ejs directly for any templating rather than the devkit helper

**Comment by skog-newglue** [comment]
@AgentEnder Gotcha. Got it working now finally but I found a problem, and I'm not sure if it's fixable. When you run a generator from within an executor with `execSync('nx g @my-org/automation:env-type-def');`, any `output` calls within the generator aren't logged despite the generator running as intended (I can see that it creates the file I want). Here I would expect to see 2 more logs from the generator but they aren't there. Is this because it's running in a different process? And is there any way to fix it?

![Screenshot 2022-10-27 at 08 46 35](https://user-images.githubusercontent.com/83581833/198210959-8ed5d1cb-9165-4f9b-862b-e50c384cba03.png)

**Comment by AgentEnder** [comment]
You can pass options to execsync to inherit stdio, which is what you want. It should be easy to find on Google/node docs from that.
