### ISSUE TITLE
Unexpected lib directory

### ISSUE THREAD

**Issue by ri8ika** [nrwl/nx#12801]
Previously, I was able to have separate directories `apps` and `libs`. But today, I tried to create a workspace with the latest version and it generates the libraries inside the `packages` folder itself. I want it to be in the root folder.

I also tried:
```
nx g move --project mylib shared/mylib
```

But it still creates folder inside the `packages`. I am afraid to move them manually because, I'll need to fix many things if I do it manually.

I also tried:

```
nx g @nrwl/js:lib mylib --directory=../shared/
```

Now, this time it has the expected directory structure. But it creates weird file name: `../mylib.tsx`. This seems to be a bug.

I have checked this [PR fix](https://github.com/nrwl/nx/issues/10687) but I think that fix is really unnecessary and weird. It should be reverted. Otherwise, we could not get expected directory structure. In that PR case, they can use `--directory` to have folder in the same package, but getting folder generated in the root workspace, it's weird. So, it must be fixed please.

**Comment by AgentEnder** [comment]
The placement of your projects depends on `workspaceLayout` inside `nx.json`. If you wish them to be relative to root, you'd want a configuration similar to that on this repo:
```json
{
   "workspaceLayout": {
    "libsDir": "",
    "appsDir": ""
  },
}
```
