### ISSUE TITLE
Cannot build application after update to nx 15.0.1

### ISSUE THREAD

**Issue by B1Z1** [nrwl/nx#12803]
I try to update our application to version 15.0.1, but for some reason NX cannot build the application locally. An interesting fact, that our CI builds it without problems. Execution command for CI and Local environment the same. Also when I'm trying to build a library separately, after several tries without clearing the cache it completes correctly

## Current Behavior
Application/Libraries build fails randomly

## Expected Behavior
Application build completes without errors

## Steps to Reproduce
We have a private repository and I cannot share an application.  

### Failure Logs
First execution:

   libs/ngplant/date-utils/date-utils/src/lib/operations/min.ts:1:25 - error TS6059: File '/Users/illia.mishkin/workspace/ppm-branch1/ui/libs/util/src/index.ts' is not under 'rootDir' '/Users/illia.mishkin/workspace/ppm-branch1/ui/libs/ngplant/date-utils/date-utils/src'. 'rootDir' is expected to contain all source files.
     The file is in the program because:
       Imported via '@bp/util' from file '/Users/illia.mishkin/workspace/ppm-branch1/ui/libs/ngplant/date-utils/date-utils/src/lib/operations/min.ts'
       Imported via '@bp/util' from file '/Users/illia.mishkin/workspace/ppm-branch1/ui/libs/ngplant/date-utils/date-utils/src/lib/operations/max.ts'
   
   1 import { Spodash } from '@bp/util';
                             ~~~~~~~~~~
   
     libs/ngplant/date-utils/date-utils/src/lib/operations/max.ts:1:25
       1 import { Spodash } from '@bp/util';
                                 ~~~~~~~~~~
       File is included via import here.

Second execution without clearing cache:

 >  NX   Successfully ran target build for project ngplant-core and 75 task(s) it depends on (2m)
 
   Nx read the output from the cache instead of running the command for 8 out of 76 tasks.
 
   See Nx Cloud run details at https://cloud.nx.app/runs/OWwchmbNgJ

### Environment
 >  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : darwin arm64
   yarn : 1.22.4
   
   nx : 15.0.1
   @nrwl/angular : 15.0.1
   @nrwl/cypress : 15.0.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.1
   @nrwl/js : 15.0.1
   @nrwl/linter : 15.0.1
   @nrwl/nest : 15.0.1
   @nrwl/next : Not Found
   @nrwl/node : 15.0.1
   @nrwl/nx-cloud : 15.0.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.1
   @nrwl/web : 15.0.1
   @nrwl/webpack : 15.0.1
   @nrwl/workspace : 15.0.1
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
         dev-schematics
   ---------------------------------------
   Community plugins:
         @ngneat/transloco: 4.1.1
         @ngrx/effects: 12.5.0
         @ngrx/entity: 12.4.0
         @ngrx/store: 12.5.0
         @ngrx/store-devtools: 12.5.0
         @rx-angular/cdk: 1.0.0-rc.1
         @rx-angular/state: 1.6.0
         @rx-angular/template: 1.0.0-beta.32
         @storybook/angular: 6.5.12
         @testing-library/angular: 11.0.4

**Comment by FrozenPandaz** [comment]
Sorry, it will be very difficult to help you if we don't have a repro.

If it works on CI, have you tried to re-clone your workspace and see if the issue still persists locally?

**Comment by B1Z1** [comment]
Okay, but this type of error occurs in every version that I remember. And this is annoying that it only breaks up in our repository. When I tried to create an example application with mock components it doesn't help. If you have an idea, of how I can create repro steps, I can do it. Our repository was created without any additional configuration for NX. It's just a simple NX application with a default configuration. It started blowing on this type of errors when we moved 80~ modules into buildable libraries

Please help us, we are fighting with it until June/July

**Comment by B1Z1** [comment]
Also, we have enterprise nx cloud, so probably we have nx support hours, maybe I can use them to create a call with one of your developers?
