### ISSUE TITLE
Only exported components should have stories generated for them

### ISSUE THREAD

**Issue by rek** [nrwl/nx#12806]
## Current Behavior

When generating stories
```
nx g @nrwl/react:stories --project=common-ui
```
This will generate for all components, not just the exported ones.

## Expected Behavior

Only exported components should have stories generated for them

## Steps to Reproduce

```
nx g @nrwl/react:stories --project=common-ui
```
When you have a component like this in your lib:
```
import styles from './common-ui.module.css';

const InternalOnly = () => {
  return <h1>Should not be exported</h1>;
};

export const CommonUi = () => {
  return (
    <div className={styles['container']}>
      <h1>Welcome to CommonUi!</h1>
      <InternalOnly />
    </div>
  );
};

```

### Environment

```
>  NX   Report complete - copy this into the issue template

   Node : 16.17.0
   OS   : linux x64
   npm  : 8.15.0
   
   nx : 15.0.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.0
   @nrwl/js : 15.0.0
   @nrwl/linter : 15.0.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.0
   @nrwl/web : 15.0.0
   @nrwl/webpack : 15.0.0
   @nrwl/workspace : 15.0.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by mandarini** [comment]
Hi @rek ! Thanks for filing an issue! Can you explain the rationale behind this enhancement? 

I would argue that it would be nice to have stories for all the components, exported or not, since the stories would serve as a "catalogue" of the components, and also as parts of the e2e tests.. But I would definitely be open to discuss any suggestions towards a different approach!

**Comment by rek** [comment]
If you think it's useful for the patterns you have seen used, i'm happy to have this closed :)

Though for the record, here is my opinion:

Non-exported components are normally the 'implementation details' and don't make much sense alone, if they did they should be refactored into their own files instead. The fact that they are sitting in a file with the main exported component indicates that it does not make sense to expose it and its only purpose there is for ordering some internal logic/performance. This leads me to the opinion that we should not auto make stories for non exported components.
