### ISSUE TITLE
yarn audit --force breaks Nx

### ISSUE THREAD

**Issue by kenatwex** [nrwl/nx#12839]
yarn audit --force breaks Nx

## Current Behavior

cannot build anymore

## Expected Behavior
should be able to build

## Steps to Reproduce
yarn audit --force 

### Failure Logs
nx build shared-root-services   

> nx run shared-root-services:build

 >  NX   Cannot find module '../../utils/assets/copy-assets-handler'

   Require stack:
   - /Users/UI/node_modules/@nrwl/js/src/executors/tsc/tsc.impl.js
   - /Users/UI/node_modules/nx/src/config/workspaces.js
   - /Users/UI/node_modules/nx/src/command-line/run.js
   - /Users/UI/node_modules/nx/bin/run-executor.js
   Pass --verbose to see the stacktrace.

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for project shared-root-services (162ms)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]

copy-assets-handler is no where to be found in any of this workspace source code

### Environment
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.17.0
   OS   : darwin arm64
   yarn : 1.22.18
   
   nx : 15.0.3
   @nrwl/angular : 15.0.3
   @nrwl/cypress : 15.0.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.3
   @nrwl/js : 15.0.3
   @nrwl/linter : 15.0.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.0.3
   @nrwl/nx-cloud : 15.0.0
   @nrwl/nx-plugin : 15.0.3
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.3
   @nrwl/web : 15.0.3
   @nrwl/webpack : 15.0.3
   @nrwl/workspace : 15.0.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @fortawesome/angular-fontawesome: 0.10.2
   	 @ngneat/transloco: 4.1.1
   	 @ngrx/component: 14.3.2
   	 @ngrx/component-store: 14.3.2
   	 @ngrx/effects: 14.3.2
   	 @ngrx/entity: 14.3.2
   	 @ngrx/router-store: 14.3.2
   	 @ngrx/store: 14.3.2
   	 @ngrx/store-devtools: 14.3.2
   	 apollo-angular: 4.1.0
   	 @buildmotion/angular: 13.0.1
   	 @ngrx/schematics: 14.3.2
   	 @ngrx/store-devtools: 14.3.2
   	 @storybook/angular: 6.5.13

**Comment by FrozenPandaz** [comment]
I am not able to reproduce this. `yarn audit --force` doesn't actually make any changes for me.

Could you please post a repo where we can reproduce the issue?

**Comment by kenatwex** [comment]
Hi

I dont have a repo

I created the libs using NxConsole in webstorm... a very nice product.

These libs were generated as buildable

the executor was @nrwl/js as

```
    "build": {
      "executor": "@nrwl/js:tsc",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/libs/shared/root/constants",
        "main": "libs/shared/root/constants/src/index.ts",
        "tsConfig": "libs/shared/root/constants/tsconfig.lib.json",
        "assets": ["libs/shared/root/constants/*.md"]
      }
    },
```

within the project.json

and im receiving this error on build

```
✖  nx run shared-root-constants:build
       >  NX   Cannot find module '../../utils/assets/copy-assets-handler'
       
          Require stack:
          - /Users/me/node_modules/@nrwl/js/src/executors/tsc/tsc.impl.js
          - /Users/me/node_modules/nx/src/config/workspaces.js
          - /Users/me/node_modules/nx/src/command-line/run.js
          - /Users/me/node_modules/nx/bin/run-executor.js
          Pass --verbose to see the stacktrace.
```

this sholdnt be happening

I did the `nx migrate latest`

**Comment by kenatwex** [comment]
and this started after I did the yarn audit It could be a coincidence...

but these libs BUILDABLE are confusing me I have no index on what should be sharable or even buildable with or without the buildable option

are there documentaries that tell how libraries are shared like this for all categories of creation clearly some flag is being omitted either in the NxConsole or maybe what Nx has documented seems to suffice though it differs with what NxConsole provides for all options.

I wish I could get my libs to build it shouldnt be this difficult

**Comment by kenatwex** [comment]
so if I remove the buildable section inside all my project.json libs I can build and see errors now in my code

eventually I end up at the rootDir issue when trying to share code across libraries across other libraries and the compiler quits thats another entire can of worms Im very discouraged about... 

if you have any info on how to get around that rootDIR ISSUE THAT would be generous of you

Thanks in advance

**Comment by kenatwex** [comment]
I was able to break things out though using `nx dep-graph` and separate my libs to avoid circular dependencies that was nice tool
