### ISSUE TITLE
Routes from remote app doesn't work when it's serve in host.  

### ISSUE THREAD

**Issue by Chemazeve** [nrwl/nx#12831]
### Documentation issue

- [ x ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/recipes/module-federation/dynamic-module-federation-with-angular

### Additional context or description

I have a workspace with two apps (host and remote). Remote app is relatively complex app with a lot of routes. Host app is only a sidenav with two links one for component create by nx by defect and another for remote app. 

Host app is in http://localhost:4200 
![host](https://user-images.githubusercontent.com/116741013/198070416-d5c8fd1c-01a3-4c43-aae2-5d0b0403358c.png)

Remote app is in http://localhost:4201
![Remote app](https://user-images.githubusercontent.com/116741013/198070594-668fca3d-9afa-4b28-a95a-ae37e438cc84.png)

When I click in the link for remote app redirect correctly to http://localhost:4200/(remote)/auth/login

![Remote entry app](https://user-images.githubusercontent.com/116741013/198070817-f9b62d12-9a6d-455a-831a-c887b6046c41.png)

After login can't redirect and all routes of remote app doesn't work. 

![Remote redirect](https://user-images.githubusercontent.com/116741013/198071019-8a742c44-db27-4410-86da-289cf7ae2f14.png)

I can force the url to charge the component of remote app including path of remote entry

![Force url to remote app](https://user-images.githubusercontent.com/116741013/198072633-474a3bc0-0a2a-43e6-ba22-8c5699429d94.png)

But any of the routes of remote app doesn't work when it's serve in host app. Have you encountered similar problems with host and remote apps?

**Comment by FrozenPandaz** [comment]
Sorry, there is a lot at play here. I don't think we can help you via a github issue especially without a repo to look at...

Routing when there are 2 somewhat separate applications is difficult to understand and there are many ways to go about it.

Perhaps the community slack would be a better medium to get help though it will still be difficult.

**Comment by Chemazeve** [comment]
Thank you for the response. Do you recommended some aproach with nx?
