### ISSUE TITLE
No latestOutputsHashes folder in cache

### ISSUE THREAD

**Issue by luisxiaomai** [nrwl/nx#12830]
## Current Behavior

No latestOutputsHashes folder in cache, tested nx version: 15.0.3, 14.8.3 ,14.7.0 has no such folder
## Expected Behavior
Cache folder has latestOutputsHashes folder.  It's ok in 14.4.2 ,14.5.0, 14.6.0 nx version.

**Comment by FrozenPandaz** [comment]
This is an implementation detail that we changed. What are you specifically trying to do with the contents of `latestOutputsHashes`?

**Comment by luisxiaomai** [comment]
@FrozenPandaz I used the latestOutputsHashes to do the CI cache management, I need this latestOutputsHashes to always keep latest caches in CI env. If no this folder the cache size will become very large,  can you consider add latestOutputsHashes back? 

Many thanks.

**Comment by FrozenPandaz** [comment]
How were you using this to manage the size of the cache?

Nx has a built-in [mechanism to prune the cache which should prune entries over a week old](https://github.com/nrwl/nx/blob/master/packages/nx/src/tasks-runner/remove-old-cache-records.ts#L5).

Are you seeing this not work or is this time period still too long?

**Comment by luisxiaomai** [comment]
@FrozenPandaz our frontend project artifact is over 300MB，everyday it has about dozens of builds. If we keep all old cache records it will become very large and too slow to download. So after build we use *latestOutputsHashes* to keep only the latest caches to upload. Shorten the cache time is not very effective for the case like mine. It seems only the latestOutputsHashes can help us keep the latest cache records and reduce CI download cache time. 
````shell
for hash in .cache/nx/latestOutputsHashes/*;do
      hash_value=$(cat $hash);
      for file in .cache/nx/*;do
          if [[ "${file}" =~ "$hash_value" ]]; then mv $file temp/nx;fi
      done
 done
 mv .cache/nx/latestOutputsHashes .cache/nx/nxdeps.json .cache/nx/terminalOutputs temp/nx
````
Appreciate any other idea, thanks.

**Comment by luisxiaomai** [comment]
@FrozenPandaz is it possible to add latestOutputsHashes back? Thanks

**Comment by luisxiaomai** [comment]
@FrozenPandaz Any workaround in latest version? Appreciate it.
