### ISSUE TITLE
It is difficult to find the page on how to update Nx

### ISSUE THREAD

**Issue by wescopeland** [nrwl/nx#12832]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/core-features/automate-updating-dependencies
https://nx.dev/recipes/other/advanced-update

### Additional context or description

"Automate Updating Dependencies" leads me to believe the page is about updating non-Nx related dependencies. As a result, when searching for "how to update nrwl nx to latest" I skipped over this completely and instead landed on the `migrate` docs and "Advanced Update" docs (which do not cross link to the Automate Updating Dependencies) page.

I propose:
* Changing "Automate Updating Dependencies" to something else to be more clear this is where the instructions live for how to update Nx.
* Adding a cross-link to the "Advanced Update" guide that links to the "Automate Updating Dependencies" page.

**Comment by isaacplmann** [comment]
I changed the first heading in https://nx.dev/core-features/automate-updating-dependencies to say `Update to the latest Nx version` instead of `Migrating to the latest Nx version` so you'll see that text in the description of the google search results.
