### ISSUE TITLE
Swagger api's not showing correctly when built using yarn create nx-workspace

### ISSUE THREAD

**Issue by DouglasWebster** [nrwl/nx#1283]
- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed
- [ x ] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

I created a workspace using yarn create nx-workspace then a nestjs project using nx cli to try out the swagger example on the nestjs github site.  Everything compiles OK but the api page does not show 
any parameter input or show the model.

I created the same project using the nest cli and copied over the code from the nx workspace.  The code still compiles and runs OK but this time I can enter parameter details in the API page and it also shows the model.

The nx scaffolded project can be found at https://github.com/DouglasWebster/nx-swagger and the nestjs scaffolded project can be found at  https://github.com/DouglasWebster/nestjs-swagger

Below is a screen shot of the API page for the nx scaffolded project.
![SwaggerUnderNx](https://user-images.githubusercontent.com/15690702/56506282-e7409a00-6515-11e9-9889-53b2f668026b.png)

The nestjs generated API page is below
![SwaggerUnderNest](https://user-images.githubusercontent.com/15690702/56506398-41d9f600-6516-11e9-9071-197c3a51b3cc.png)

Any indication of what I'm doing wrong or how to fix it would be gratefully appreciated.

**Comment by Cammisuli** [comment]
Hi @DouglasWebster, sorry for such a long delay to reply to this issue, but I think I solved it. 

![image](https://user-images.githubusercontent.com/4332460/74939911-a710a900-53be-11ea-9e59-7852556d2c2b.png)

Essentially, the default `tsconfig.json` that is created with Nx has `es5` as the target. Changing it to `es6` (like it is in the nest repo that you provided) allows it to work. But for nx, we should change it in the `tsconfig.app.json` in the cats folder. 

I found an issue on the Nest repo where someone mentions this as well:
https://github.com/nestjs/swagger/issues/88

I'll make a PR to make the default target for nest apps `es6`/`es2015`
