### ISSUE TITLE
 Jest encountered an unexpected token from vue 2 application

### ISSUE THREAD

**Issue by ashif25** [nrwl/nx#12853]
## Current Behavior
![image](https://user-images.githubusercontent.com/40867499/198351559-ecd39b7d-767f-461c-94a2-ac2292d00c61.png)

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

I'm trying to update the node version from 12 to 16 and all node packages. I'm able to build successfully and clean up errors from 
ESLint but while running jest most of the test failed due to that import underscore issue.

**Comment by FrozenPandaz** [comment]
Sorry, it's hard to help you without a reproduction. Also, this seems more like an issue with `jest` + `underscore`. I don't think this is the best forum for your question. Perhaps try searching in the underscore or jest issues?
