### ISSUE TITLE
Jest fails while testing Angular 14 standalone component: SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by luishcastroc** [nrwl/nx#12858]
## Current Behavior
when running `pnpm test` i get an error message

`Details:

    /Users/luiscastrocabrera/Projects/angular-jest/node_modules/.pnpm/@okta+okta-angular@6.0.0_ukskawregmejmv3lgrudtbgin4/node_modules/@okta/okta-angular/fesm2015/okta-angular.js:12
    import { __awaiter } from 'tslib';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import { Component, inject } from '@angular/core';
    > 2 | import { OKTA_AUTH } from '@okta/okta-angular';`

## Expected Behavior
Test should run properly

## Steps to Reproduce
I'm using a library called Okta-Angular in order to implement their OAuth functionalities, for this an InjectionToken is used in order to get the proper functionality, the actual application have more libraries like NGXS for state management.

i'm using @ng-neat/spectator to do my testing and a simple reproduction of the issue may be found here.

[Reproduction using Stackblitz Codeflow](https://stackblitz.com/~/github.com/luishcastroc/angular-14-jest)

[https://github.com/luishcastroc/angular-14-jest](https://github.com/luishcastroc/angular-14-jest)

### Failure Logs
Details:

    /Users/luiscastrocabrera/Projects/angular-jest/node_modules/.pnpm/@okta+okta-angular@6.0.0_ukskawregmejmv3lgrudtbgin4/node_modules/@okta/okta-angular/fesm2015/okta-angular.js:12
    import { __awaiter } from 'tslib';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import { Component, inject } from '@angular/core';
    > 2 | import { OKTA_AUTH } from '@okta/okta-angular';`

### Environment
 NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : darwin arm64
   pnpm : 7.14.0

   nx : 15.0.3
   @nrwl/angular : 15.0.3
   @nrwl/cypress : 15.0.3
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.3
   @nrwl/js : Not Found
   @nrwl/linter : 15.0.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.0.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @ngneat/spectator: 11.3.0

**Comment by barbados-clemens** [comment]
@luishcastroc you'll need to set up jest to transform the okta dep to commonjs since jest doesn't understand the ESM code that the okta-angular library ships. 

I made a PR to your repo with the changes required to make the tests pass. 

```diff
-  transformIgnorePatterns: ['node_modules/(?!.*\\.mjs$)'],
+  transformIgnorePatterns: ['node_modules/(?!(@okta/okta-angular)|(.*\\.mjs$|))'],
```

```shell
pnpx nx test angular-jest
.../Library/pnpm/store/v3/tmp/dlx-51219  | +130 +++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/caleb/Library/pnpm/store/v3
  Virtual store is at:             ../../../Library/pnpm/store/v3/tmp/dlx-51219/node_modules/.pnpm
.../Library/pnpm/store/v3/tmp/dlx-51219  | Progress: resolved 138, reused 130, downloaded 0, added 130, done

 >  NX   Running global Nx CLI with PNPM may have issues.

   Prefer to use "pnpm" (https://pnpm.io/cli/exec) to execute commands in this workspace.
    TIP  create a shortcut such as: alias pnx="pnpm nx --"



> nx run angular-jest:test

 PASS   angular-jest  apps/angular-jest/src/app/app.component.spec.ts
  AppComponent
    ✓ should create the App (16 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.794 s, estimated 67 s
Ran all test suites.

 ———————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target test for project angular-jest (3s)

   See Nx Cloud run details at https://nx.app/runs/4W2uktOVQ7
```

there is also an error with your code where the OKTA_AUTH token wasn't provided so added that so you can see the tests working without getting a different error. :)

**Comment by luishcastroc** [comment]
> @luishcastroc you'll need to set up jest to transform the okta dep to commonjs since jest doesn't understand the ESM code that the okta-angular library ships.
> 
> I made a PR to your repo with the changes required to make the tests pass.
> 
> ```diff
> -  transformIgnorePatterns: ['node_modules/(?!.*\\.mjs$)'],
> +  transformIgnorePatterns: ['node_modules/(?!(@okta/okta-angular)|(.*\\.mjs$|))'],
> ```
> 
>  ```shell
> pnpx nx test angular-jest
> .../Library/pnpm/store/v3/tmp/dlx-51219  | +130 +++++++++++++
> Packages are hard linked from the content-addressable store to the virtual store.
>   Content-addressable store is at: /Users/caleb/Library/pnpm/store/v3
>   Virtual store is at:             ../../../Library/pnpm/store/v3/tmp/dlx-51219/node_modules/.pnpm
> .../Library/pnpm/store/v3/tmp/dlx-51219  | Progress: resolved 138, reused 130, downloaded 0, added 130, done
> 
>  >  NX   Running global Nx CLI with PNPM may have issues.
> 
>    Prefer to use "pnpm" (https://pnpm.io/cli/exec) to execute commands in this workspace.
>     TIP  create a shortcut such as: alias pnx="pnpm nx --"
> 
> 
> 
> > nx run angular-jest:test
> 
>  PASS   angular-jest  apps/angular-jest/src/app/app.component.spec.ts
>   AppComponent
>     ✓ should create the App (16 ms)
> 
> Test Suites: 1 passed, 1 total
> Tests:       1 passed, 1 total
> Snapshots:   0 total
> Time:        1.794 s, estimated 67 s
> Ran all test suites.
> 
>  ———————————————————————————————————————————————————————————————————————————————————————————————————————
> 
>  >  NX   Successfully ran target test for project angular-jest (3s)
> 
>    See Nx Cloud run details at https://nx.app/runs/4W2uktOVQ7
> ```
> 
> there is also an error with your code where the OKTA_AUTH token wasn't provided so added that so you can see the tests working without getting a different error. :)

thanks a lot I'll check it out
