### ISSUE TITLE
angular.json is missing 

### ISSUE THREAD

**Issue by InesSehili** [nrwl/nx#12850]
Hello, I am creating my workspace, and angular applications in it, all work well but the problem is only when I create an application using:
nx generate @nrwl/angular:app customer-portal --routing

a warning message is displayed: [NX] Angular devkit called `writeWorkspace`, this may have created 'workspace.json' or 'angular.json
[NX] Double check workspace configuration before proceeding
Skipping employees since apps\employees\project.json already exists.

the angular.json file is not created but it is the project.json file for each application is created.
![issues](https://user-images.githubusercontent.com/64504390/198309818-29c8dc71-7141-4bbf-9127-9271355af5b3.PNG)

before I had no problem but when I want to share the media from a lib I still have to configure the shared assets in angular.json . but this is not the case in my structure.

**Comment by FrozenPandaz** [comment]
`angular.json` is intentionally missing because its not needed anymore. You can safely ignore the warnings. We will be removing them soon as well.

**Comment by InesSehili** [comment]
@FrozenPandaz 
thank you for your answer, the workspace.json file also does not exist, my question is the following: how to configure the assets folder and make it shareable from the library?  do I have to configure the project.json file for each application or what?  thank you :)

**Comment by FrozenPandaz** [comment]
Yes you should configure it in the `project.json` for each application that uses it. This is not too much different from having the configuration in `angular.json` because you'd have to make the change for each project in 1 file. Now its just across multiple files.
