### ISSUE TITLE
TypeError: (0 , _sharp.default) is not a function

### ISSUE THREAD

**Issue by skog-newglue** [nrwl/nx#12867]
## Current Behavior
Trying to use `sharp` function from `import sharp from 'sharp';` results in the error `TypeError: (0 , _sharp.default) is not a function` when using this inside a plugin. 

## Expected Behavior
I expect to be able to run the `sharp` function without getting an error. This works fine in a workspace generator but not in a generator within my plugin. I've tried adding `"esModuleInterop": true` to my `tsconfig.json` as described here `https://github.com/lovell/sharp/issues/1913` but it doesn't work. I did notice I had the same issue with `import debounce from lodash.debounce`, so it's not related to just the `sharp` package.

## Steps to Reproduce
1. Create a workspace
2. Create a plugin in your workspace
3. `npm install sharp`
4. Import sharp with `import sharp from 'sharp'` in the example generator
5. Add a `sharp()` call in the example generator
6. Notice the error thrown

### Failure Logs
```
TypeError: (0 , _sharp.default) is not a function
at <redacted>/libs/automation/src/generators/assets/generator.ts:40:10
```

### Environment
   Node : 19.0.0
   OS   : darwin x64
   npm  : 8.19.2
   
   nx : 15.0.3
   @nrwl/angular : 15.0.3
   @nrwl/cypress : 15.0.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.3
   @nrwl/js : 15.0.3
   @nrwl/linter : 15.0.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.1.1
   @nrwl/nx-plugin : 15.0.3
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.3
   @nrwl/web : Not Found
   @nrwl/webpack : 15.0.3
   @nrwl/workspace : 15.0.3
   typescript : 4.7.3
   ---------------------------------------
   Local workspace plugins:
   	 @newglue-frontend/automation
   ---------------------------------------
   Community plugins:
   	 @nguniversal/express-engine: 14.2.0
   	 rxjs: 6.6.7
   	 @nguniversal/builders: 14.2.0

**Comment by FrozenPandaz** [comment]
Could you please create a repo to help us reproduce the issue? Where exactly are you adding `esModuleInterop: false`?

**Comment by skog-newglue** [comment]
@FrozenPandaz Here you go https://github.com/skog-newglue/esmodules-repro, run the generator with `nx g @esmodules-repro/my-plugin:my-plugin` and you'll see the error. I've added `esModuleInterop: true` to `my-plugin`'s `tsconfig.json`.

**Comment by skog-newglue** [comment]
This issue still persist.

**Comment by skog-newglue** [comment]
@FrozenPandaz Is anyone looking at this?
