### ISSUE TITLE
Running local executor fails when including types definition files in tsconfig.base.json

### ISSUE THREAD

**Issue by sdjnes** [nrwl/nx#12869]
## Current Behavior
Running a local executor (created following the [local executor recipe](https://nx.dev/recipes/executors/creating-custom-executors)) results in an error when the root `tsconfig.base.json` has type definition files in the `include` array.

## Expected Behavior
The local executor should run as it does with a fresh workspace.

## Steps to Reproduce
1. Create a fresh workspace `npx create-nx-workspace`
2. Create a local executor following [local executor recipe](https://nx.dev/recipes/executors/creating-custom-executors)
3. Create a file in the root such as `types.d.ts` (contents aren't important)
4. Add `"include": ["./types.d.ts"]` to the root `tsconfig.base.json`
5. Run the target using the executor to see it failing

If the array is empty, the executor runs OK.

### Failure Logs
```
nx run my-plugin-e2e:echo --verbose

> nx run my-plugin-e2e:echo


 >  NX   Cannot use import statement outside a module


/Users/sam/projects/nx-test/libs/my-plugin/src/executors/build/executor.ts:1
import type { ExecutorContext } from '@nrwl/devkit';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1055:15)
    at Module._compile (node:internal/modules/cjs/loader:1090:27)
    at Module._compile (/Users/sam/projects/nx-test/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.newLoader [as .ts] (/Users/sam/projects/nx-test/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

### Environment
```
 >  NX   Report complete - copy this into the issue template

   Node : 16.17.0
   OS   : darwin arm64
   npm  : 8.15.0

   nx : 15.0.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.3
   @nrwl/js : 15.0.3
   @nrwl/linter : 15.0.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 15.0.3
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.0.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
         @nx-test/my-plugin
   ---------------------------------------
   Community plugins:
 ```
 
 Also occurring in `14.7.9`

**Comment by minuz** [comment]
I'm seeing the same behaviour on `15.3.3`. Tried to create a plugin using `tsc` and `swc` and both fails to execute with the same error msg. It feels like it's trying to run using the ts files directly instead of a transpiled version.

**Comment by minuz** [comment]
> Have the same issue with creating local executor via [doc](https://nx.dev/recipes/executors/creating-custom-executors)
> 
> ```
> import {IVersionExecutorSchema} from './schema';
> ^^^^^^
> SyntaxError: Cannot use import statement outside a module
> ```
> 
> Version: 15.5.0
> 
> Any workarounds ?

The problem I had was that for whatever reason, the plugin was generated without a `.babelrc` file. Once I put one on the lib directory, it started to work. Not sure if that's the problem you're having though.

**Comment by AgentEnder** [comment]
There's a decent chance #14610 will fix these issues, after it's merged and released we will see.

**Comment by AgentEnder** [comment]
There is a known issue relating to a recent swc-node update that is breaking things for fresh workspaces. I'm currently looking into a workaround / fix for that. You can try uninstalling swc-node, s.t. nx will fall back on ts-node for the time being.

**Comment by ruslanpixellu** [comment]
under 15.7.0 works well
