### ISSUE TITLE
writeJsonFile should add written paths to Tree

### ISSUE THREAD

**Issue by skog-newglue** [nrwl/nx#12873]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
When testing, `generateFiles` adds the written paths to `Tree` which makes it easy to write generator tests. The same is not true for `writeJsonFile`, the path is not added to the `Tree` that has been created in the testing environment with `createTreeWithEmptyWorkspace`, nor has it been written in the actual tree so I can't test for that either. The only solution I see would be to have a __tmpl__ file that I populate the JSON data with using `generateFiles`. However, that kinda eliminates the whole point of having the `writeJsonFile` in the first place.

## Motivation
It would make it possible to write tests to check if json files exists in the tree. Right now you'll write tests that are false positives since you can't actually check if the file was written.

## Suggested Implementation
Mirror the behavior of `generateFiles` and add the written paths to `Tree` when `writeJsonFile` runs.

## Alternate Implementations
Create a new function that allows you to write any file type, and mirror the behavior of `generateFiles` as explained above.

There are probably limitations here that I'm unaware of so my suggestions might not work, but I'm sure someone more experienced with Nx can come up with something here.

**Comment by leosvelperez** [comment]
The `writeJsonFile` utility makes the changes directly on the filesystem. That utility is not meant to be used with the Nx DevKit `Tree`. For your use case, you should instead use the `writeJson` utility from `@nrwl/devkit` which makes changes on the virtual `Tree`.

I'm closing this since it's not an issue.

**Comment by skog-newglue** [comment]
@leosvelperez Gotcha. If I need to write a bunch of `webp` files to a location, what is a `writeJson` equivalent of that? I don't see one when going through the devkit.
