### ISSUE TITLE
Add comparison to nix to your docs

### ISSUE THREAD

**Issue by adrian-gierakowski** [nrwl/nx#12897]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Additional context or description

Seems like what you’re doing is very similar in essence to [nix](https://nixos.org/). It would useful to have an overview of how your approach compares to nix and why would someone choose nx over nix.
Thanks!

**Comment by gioragutt** [comment]
From my couple of minutes of looking at the Nix homepage (thanks for the link btw, looks like a cool project), the purpose of Nix and NX are very different.

Nix seems to deal with dev-env/dev-ops related manners, whereas NX is about managing a monorepo and some sprinkles of magic on-top.

https://monorepo.tools/ is a great resource to define what `managing a monorepo` means.

Nix and NX could definitely live side-by-side, just like Nix could live side-by-side in any project.

**Comment by isaacplmann** [comment]
I think @gioragutt answered this well.  Closing.

**Comment by adrian-gierakowski** [comment]
hi, apologies for the delayed response

What prompted me to ask is similarities in what you describe [on your doc page about caching](https://nx.dev/concepts/how-caching-works) and what nix does. Seems like you could benefit by leveraging nix for this.
