### ISSUE TITLE
add-nx-to-monorepo fails with confusing error for minimal package.json

### ISSUE THREAD

**Issue by AbdealiLoKo** [nrwl/nx#12893]
I am trying to add nx to a monorepo I am trynig to create for my python packages
 - I am using nx for the first time
 - I am trying to structure my code in a monorepo for the first time (package based monorepo)

## Current Behavior
`npx add-nx-to-monorepo` fails with an unclear error

## Expected Behavior

I was expecting it to ask some questions or at the very least tell me why it can't ask me questions

## Steps to Reproduce

The `package.json` I have in my python project was added mainly for commitlint
```
{
  "devDependencies": {
    "@commitlint/cli": "^17.0.0",
    "@commitlint/config-conventional": "^17.0.0",
    "cz-conventional-changelog": "^3.3.0"
  },
  "config": {
    "commitizen": {
      "path": "./commitizen.js"
    }
  }
}
```
When I try to run `$ npx add-nx-to-monorepo` - it fails.

Easiest way to reproduce seems to be:
```
$ mkdir /tmp/test_nx
$ echo '{}' > package.json
$ npx add-nx-to-monorepo
```

### Failure Logs

```
$ npx add-nx-to-monorepo

 >  NX   🐳 Nx initialization


 >  NX   🧑‍🔧 Please answer the following questions about the scripts found in your workspace in order to generate task runner configuration

/home/abdealijk/.npm/_npx/dcff4b037c44fe4f/node_modules/enquirer/lib/types/array.js:38
      throw new Error('At least one choice must be selectable');
            ^

Error: At least one choice must be selectable
    at MultiSelect.reset (/home/abdealijk/.npm/_npx/dcff4b037c44fe4f/node_modules/enquirer/lib/types/array.js:38:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MultiSelect.initialize (/home/abdealijk/.npm/_npx/dcff4b037c44fe4f/node_modules/enquirer/lib/types/array.js:25:5)
    at async /home/abdealijk/.npm/_npx/dcff4b037c44fe4f/node_modules/enquirer/lib/prompt.js:236:7
```

### Environment

I am using Ubuntu 18.04 with WSL2 on Windows 10

**Comment by marty331** [comment]
I'm getting a the same error on Windows 11.
`$ npx add-nx-to-monorepo

 >  NX   🐳 Nx initialization


 >  NX   🧑‍🔧 Please answer the following questions about the scripts found in your workspace in order to generate task runner configuration

C:\Users\martyballard\AppData\Local\npm-cache\_npx\dcff4b037c44fe4f\node_modules\enquirer\lib\types\array.js:38
      throw new Error('At least one choice must be selectable');
            ^

Error: At least one choice must be selectable
    at MultiSelect.reset (C:\Users\martyballard\AppData\Local\npm-cache\_npx\dcff4b037c44fe4f\node_modules\enquirer\lib\types\array.js:38:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MultiSelect.initialize (C:\Users\martyballard\AppData\Local\npm-cache\_npx\dcff4b037c44fe4f\node_modules\enquirer\lib\types\array.js:25:5)
    at async C:\Users\martyballard\AppData\Local\npm-cache\_npx\dcff4b037c44fe4f\node_modules\enquirer\lib\prompt.js:236:7

Node.js v18.12.1`

**Comment by DRenaud** [comment]
Same for me on Mac OS Ventura.

Node v16.15.1
Npm v8.11.0

**Comment by DRenaud** [comment]
I found a little trick : 
npx add-nx-to-monorepo --yes no

But no task runner configuration was generated...

**Comment by freedom9x** [comment]
same issue in Mac ventuna.
Thanks @DRenaud , it's worked!

**Comment by nedkelly** [comment]
Thanks @DRenaud, that workaround also worked with `yarn dlx nx@latest init --yes no`

**Comment by jase88** [comment]
Same error if calling `npx nx init` like [suggested in the docs](https://nx.dev/recipes/adopting-nx/migration-angular) to migrate from Angular CLI project 

MacOS Ventrua 13.1
node 18.12.1
npm 9.2.0

`npx nx init --yes` goes through, but only adds `nx` as npm dependency as well as `nx.json` file with nearly zero configuration.

**Comment by szahn** [comment]
Getting the same error after following the documentation on https://nx.dev/recipes/adopting-nx/migration-angular. Tried with an existing repository and a new Angular project. Using Node 16.16.0. Wish this could be resolved, as it's a major hurdle to adopting NX.
