### ISSUE TITLE
NX cannot create workspace on cypress downloading using angular preset

### ISSUE THREAD

**Issue by scriptlord** [nrwl/nx#12899]
Anyone with any assistance would be much appreciated
I am trying to install nx workspace with angular preset and I am getting this error on cypress downloading. Here is the log:

<details>
<summary>Details</summary>

NX Generating @nrwl/workspace/generators.json:new

CREATE myorg/.editorconfig
CREATE myorg/.gitignore
CREATE myorg/.prettierignore
CREATE myorg/.vscode/extensions.json
CREATE myorg/package.json
CREATE myorg/tools/generators/.gitkeep
CREATE myorg/tools/tsconfig.tools.json
CREATE myorg/tsconfig.base.json
CREATE myorg/nx.json
CREATE myorg/.prettierrc
CREATE myorg/decorate-angular-cli.js
CREATE myorg/apps/.gitkeep
CREATE myorg/libs/.gitkeep

myorg@0.0.0 postinstall
node ./decorate-angular-cli.js

NX Angular CLI has been decorated to enable computation caching.

added 1037 packages, and audited 1038 packages in 59s

98 packages are looking for funding
run npm fund for details

found 0 vulnerabilities

NX Generating @nrwl/workspace:preset

UPDATE nx.json
UPDATE package.json
CREATE jest.config.ts
CREATE jest.preset.js
UPDATE .vscode/extensions.json
UPDATE .gitignore
CREATE apps/modeller/.browserslistrc
CREATE apps/modeller/tsconfig.app.json
CREATE apps/modeller/tsconfig.spec.json
CREATE apps/modeller/src/favicon.ico
CREATE apps/modeller/src/index.html
CREATE apps/modeller/src/main.ts
CREATE apps/modeller/src/polyfills.ts
CREATE apps/modeller/src/styles.scss
CREATE apps/modeller/src/assets/.gitkeep
CREATE apps/modeller/src/environments/environment.prod.ts
CREATE apps/modeller/src/environments/environment.ts
CREATE apps/modeller/src/app/app.module.ts
CREATE apps/modeller/src/app/app.component.scss
CREATE apps/modeller/src/app/app.component.html
CREATE apps/modeller/src/app/app.component.spec.ts
CREATE apps/modeller/src/app/app.component.ts
CREATE apps/modeller/project.json
CREATE apps/modeller/tsconfig.editor.json
CREATE apps/modeller/tsconfig.json
CREATE apps/modeller/src/app/nx-welcome.component.ts
CREATE .eslintrc.json
CREATE apps/modeller/.eslintrc.json
CREATE apps/modeller/jest.config.ts
CREATE apps/modeller/src/test-setup.ts
CREATE apps/modeller-e2e/cypress.config.ts
CREATE apps/modeller-e2e/src/e2e/app.cy.ts
CREATE apps/modeller-e2e/src/fixtures/example.json
CREATE apps/modeller-e2e/src/support/app.po.ts
CREATE apps/modeller-e2e/src/support/commands.ts
CREATE apps/modeller-e2e/src/support/e2e.ts
CREATE apps/modeller-e2e/tsconfig.json
CREATE apps/modeller-e2e/project.json
CREATE apps/modeller-e2e/.eslintrc.json

NX Command failed: npm install

Pass --verbose to see the stacktrace.

NX Workspace creation failed, see above.

Pass --verbose to see the stacktrace.

npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
[NX] Angular devkit called writeWorkspace, this may have created 'workspace.json' or 'angular.json
[NX] Double check workspace configuration before proceeding
Skipping modeller since apps/modeller/project.json already exists.
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm ERR! code 1
npm ERR! path /Users/mac/Desktop/PROJECTS/ECOMMERCE-ANGULAR/myorg/node_modules/cypress
npm ERR! command failed
npm ERR! command sh -c -- node index.js --exec install
npm ERR! Installing Cypress (version: 10.11.0)
npm ERR!
npm ERR! [STARTED] Task without title.
npm ERR! [TITLE] Downloading Cypress 0% 0s
npm ERR! [TITLE] Downloading Cypress 1% 70s
npm ERR! [TITLE] Downloading Cypress 1% 108s
npm ERR! [TITLE] Downloading Cypress 1% 118s
npm ERR! [TITLE] Downloading Cypress 1% 127s
npm ERR! [TITLE] Downloading Cypress 1% 162s
npm ERR! [TITLE] Downloading Cypress 1% 172s
npm ERR! [TITLE] Downloading Cypress 1% 182s
npm ERR! [TITLE] Downloading Cypress 2% 95s
npm ERR! [TITLE] Downloading Cypress 2% 100s
npm ERR! [TITLE] Downloading Cypress 2% 105s
npm ERR! [TITLE] Downloading Cypress 2% 110s
npm ERR! [TITLE] Downloading Cypress 2% 115s
npm ERR! [TITLE] Downloading Cypress 2% 120s
npm ERR! [TITLE] Downloading Cypress 2% 147s
npm ERR! [TITLE] Downloading Cypress 2% 152s
npm ERR! [TITLE] Downloading Cypress 2% 163s
npm ERR! [TITLE] Downloading Cypress 2% 168s
npm ERR! [TITLE] Downloading Cypress 2% 186s
npm ERR! [TITLE] Downloading Cypress 3% 126s
npm ERR! [TITLE] Downloading Cypress 3% 134s
npm ERR! [TITLE] Downloading Cypress 3% 137s
npm ERR! [TITLE] Downloading Cypress 3% 143s
npm ERR! [TITLE] Downloading Cypress 3% 146s
npm ERR! [TITLE] Downloading Cypress 3% 150s
npm ERR! [TITLE] Downloading Cypress 3% 153s
npm ERR! [TITLE] Downloading Cypress 3% 156s
npm ERR! [TITLE] Downloading Cypress 3% 159s
npm ERR! [TITLE] Downloading Cypress 3% 163s
npm ERR! [TITLE] Downloading Cypress 4% 123s
npm ERR! [TITLE] Downloading Cypress 4% 126s
npm ERR! [TITLE] Downloading Cypress 4% 136s
npm ERR! [TITLE] Downloading Cypress 4% 138s
npm ERR! [TITLE] Downloading Cypress 4% 144s
npm ERR! [TITLE] Downloading Cypress 4% 146s
npm ERR! [TITLE] Downloading Cypress 4% 149s
npm ERR! [TITLE] Downloading Cypress 4% 159s
npm ERR! [TITLE] Downloading Cypress 5% 128s
npm ERR! [TITLE] Downloading Cypress 5% 132s
npm ERR! [TITLE] Downloading Cypress 5% 134s
npm ERR! [TITLE] Downloading Cypress 5% 138s
npm ERR! [TITLE] Downloading Cypress 5% 140s
npm ERR! [TITLE] Downloading Cypress 5% 147s
npm ERR! [TITLE] Downloading Cypress 6% 123s
npm ERR! [TITLE] Downloading Cypress 6% 124s
npm ERR! [TITLE] Downloading Cypress 6% 126s
npm ERR! [TITLE] Downloading Cypress 6% 132s
npm ERR! [TITLE] Downloading Cypress 6% 134s
npm ERR! [TITLE] Downloading Cypress 6% 137s
npm ERR! [TITLE] Downloading Cypress 7% 117s
npm ERR! [TITLE] Downloading Cypress 7% 119s
npm ERR! [TITLE] Downloading Cypress 7% 120s
npm ERR! [TITLE] Downloading Cypress 7% 121s
npm ERR! [TITLE] Downloading Cypress 7% 123s
npm ERR! [TITLE] Downloading Cypress 7% 124s
npm ERR! [TITLE] Downloading Cypress 7% 125s
npm ERR! [TITLE] Downloading Cypress 7% 127s
npm ERR! [TITLE] Downloading Cypress 7% 128s
npm ERR! [TITLE] Downloading Cypress 7% 129s
npm ERR! [TITLE] Downloading Cypress 7% 131s
npm ERR! [TITLE] Downloading Cypress 7% 132s
npm ERR! [TITLE] Downloading Cypress 7% 136s
npm ERR! [TITLE] Downloading Cypress 8% 119s
npm ERR! [TITLE] Downloading Cypress 8% 120s
npm ERR! [TITLE] Downloading Cypress 8% 122s
npm ERR! [TITLE] Downloading Cypress 8% 125s
npm ERR! [TITLE] Downloading Cypress 8% 126s
npm ERR! [TITLE] Downloading Cypress 8% 127s
npm ERR! [TITLE] Downloading Cypress 8% 128s
npm ERR! [TITLE] Downloading Cypress 8% 129s
npm ERR! [TITLE] Downloading Cypress 8% 131s
npm ERR! [TITLE] Downloading Cypress 8% 132s
npm ERR! [TITLE] Downloading Cypress 8% 133s
npm ERR! [TITLE] Downloading Cypress 8% 134s
npm ERR! [TITLE] Downloading Cypress 9% 119s
npm ERR! [TITLE] Downloading Cypress 9% 120s
npm ERR! [TITLE] Downloading Cypress 9% 121s
npm ERR! [TITLE] Downloading Cypress 9% 125s
npm ERR! [TITLE] Downloading Cypress 9% 126s
npm ERR! [TITLE] Downloading Cypress 9% 129s
npm ERR! [TITLE] Downloading Cypress 9% 130s
npm ERR! [TITLE] Downloading Cypress 9% 135s
npm ERR! [TITLE] Downloading Cypress 10% 121s
npm ERR! [TITLE] Downloading Cypress 10% 123s
npm ERR! [TITLE] Downloading Cypress 10% 124s
npm ERR! [TITLE] Downloading Cypress 10% 125s
npm ERR! [TITLE] Downloading Cypress 10% 126s
npm ERR! [TITLE] Downloading Cypress 10% 131s
npm ERR! [TITLE] Downloading Cypress 10% 132s
npm ERR! [TITLE] Downloading Cypress 10% 134s
npm ERR! [TITLE] Downloading Cypress 11% 121s
npm ERR! [TITLE] Downloading Cypress 11% 124s
npm ERR! [TITLE] Downloading Cypress 11% 125s
npm ERR! [TITLE] Downloading Cypress 11% 126s
npm ERR! [TITLE] Downloading Cypress 11% 127s
npm ERR! [TITLE] Downloading Cypress 11% 128s
npm ERR! [TITLE] Downloading Cypress 11% 129s
npm ERR! [TITLE] Downloading Cypress 11% 134s
npm ERR! [TITLE] Downloading Cypress 12% 123s
npm ERR! [TITLE] Downloading Cypress 12% 126s
npm ERR! [TITLE] Downloading Cypress 12% 127s
npm ERR! [TITLE] Downloading Cypress 12% 129s
npm ERR! [TITLE] Downloading Cypress 13% 118s
npm ERR! [TITLE] Downloading Cypress 13% 119s
npm ERR! [TITLE] Downloading Cypress 13% 120s
npm ERR! [TITLE] Downloading Cypress 13% 121s
npm ERR! [TITLE] Downloading Cypress 13% 124s
npm ERR! [TITLE] Downloading Cypress 13% 125s
npm ERR! [TITLE] Downloading Cypress 13% 127s
npm ERR! [TITLE] Downloading Cypress 13% 128s
npm ERR! [TITLE] Downloading Cypress 13% 130s
npm ERR! [TITLE] Downloading Cypress 14% 120s
npm ERR! [TITLE] Downloading Cypress 14% 121s
npm ERR! [TITLE] Downloading Cypress 14% 124s
npm ERR! [TITLE] Downloading Cypress 14% 125s
npm ERR! [TITLE] Downloading Cypress 14% 126s
npm ERR! [TITLE] Downloading Cypress 14% 127s
npm ERR! [TITLE] Downloading Cypress 14% 128s
npm ERR! [TITLE] Downloading Cypress 15% 119s
npm ERR! [TITLE] Downloading Cypress 15% 122s
npm ERR! [TITLE] Downloading Cypress 15% 123s
npm ERR! [TITLE] Downloading Cypress 15% 124s
npm ERR! [TITLE] Downloading Cypress 15% 125s
npm ERR! [TITLE] Downloading Cypress 15% 126s
npm ERR! [TITLE] Downloading Cypress 16% 117s
npm ERR! [TITLE] Downloading Cypress 16% 118s
npm ERR! [TITLE] Downloading Cypress 16% 119s
npm ERR! [TITLE] Downloading Cypress 16% 120s
npm ERR! [TITLE] Downloading Cypress 16% 121s
npm ERR! [TITLE] Downloading Cypress 16% 125s
npm ERR! [TITLE] Downloading Cypress 16% 126s
npm ERR! [TITLE] Downloading Cypress 16% 127s
npm ERR! [TITLE] Downloading Cypress 16% 128s
npm ERR! [TITLE] Downloading Cypress 17% 119s
npm ERR! [TITLE] Downloading Cypress 17% 120s
npm ERR! [TITLE] Downloading Cypress 17% 121s
npm ERR! [TITLE] Downloading Cypress 17% 122s
npm ERR! [TITLE] Downloading Cypress 17% 123s
npm ERR! [TITLE] Downloading Cypress 17% 124s
npm ERR! [TITLE] Downloading Cypress 18% 116s
npm ERR! [TITLE] Downloading Cypress 18% 117s
npm ERR! [TITLE] Downloading Cypress 18% 119s
npm ERR! [TITLE] Downloading Cypress 18% 120s
npm ERR! [TITLE] Downloading Cypress 18% 121s
npm ERR! [TITLE] Downloading Cypress 18% 122s
npm ERR! [TITLE] Downloading Cypress 19% 115s
npm ERR! [TITLE] Downloading Cypress 19% 116s
npm ERR! [TITLE] Downloading Cypress 19% 117s
npm ERR! [TITLE] Downloading Cypress 19% 118s
npm ERR! [TITLE] Downloading Cypress 19% 119s
npm ERR! [TITLE] Downloading Cypress 19% 120s
npm ERR! [TITLE] Downloading Cypress 19% 121s
npm ERR! [TITLE] Downloading Cypress 20% 114s
npm ERR! [TITLE] Downloading Cypress 20% 115s
npm ERR! [TITLE] Downloading Cypress 20% 116s
npm ERR! [TITLE] Downloading Cypress 20% 117s
npm ERR! [TITLE] Downloading Cypress 21% 110s
npm ERR! [TITLE] Downloading Cypress 21% 111s
npm ERR! [TITLE] Downloading Cypress 21% 112s
npm ERR! [TITLE] Downloading Cypress 21% 114s
npm ERR! [TITLE] Downloading Cypress 21% 115s
npm ERR! [TITLE] Downloading Cypress 22% 108s
npm ERR! [TITLE] Downloading Cypress 22% 109s
npm ERR! [TITLE] Downloading Cypress 22% 110s
npm ERR! [TITLE] Downloading Cypress 22% 111s
npm ERR! [TITLE] Downloading Cypress 22% 112s
npm ERR! [TITLE] Downloading Cypress 23% 107s
npm ERR! [TITLE] Downloading Cypress 23% 108s
npm ERR! [TITLE] Downloading Cypress 23% 109s
npm ERR! [TITLE] Downloading Cypress 23% 110s
npm ERR! [TITLE] Downloading Cypress 23% 111s
npm ERR! [TITLE] Downloading Cypress 23% 112s
npm ERR! [TITLE] Downloading Cypress 24% 106s
npm ERR! [TITLE] Downloading Cypress 24% 107s
npm ERR! [TITLE] Downloading Cypress 24% 108s
npm ERR! [TITLE] Downloading Cypress 24% 109s
npm ERR! [TITLE] Downloading Cypress 24% 110s
npm ERR! [TITLE] Downloading Cypress 25% 104s
npm ERR! [TITLE] Downloading Cypress 25% 106s
npm ERR! [TITLE] Downloading Cypress 25% 107s
npm ERR! [TITLE] Downloading Cypress 25% 108s
npm ERR! [TITLE] Downloading Cypress 26% 103s
npm ERR! [TITLE] Downloading Cypress 26% 104s
npm ERR! [TITLE] Downloading Cypress 26% 105s
npm ERR! [TITLE] Downloading Cypress 26% 106s
npm ERR! [TITLE] Downloading Cypress 27% 101s
npm ERR! [TITLE] Downloading Cypress 27% 102s
npm ERR! [TITLE] Downloading Cypress 27% 103s
npm ERR! [TITLE] Downloading Cypress 27% 104s
npm ERR! [TITLE] Downloading Cypress 28% 99s
npm ERR! [TITLE] Downloading Cypress 28% 101s
npm ERR! [TITLE] Downloading Cypress 28% 102s
npm ERR! [TITLE] Downloading Cypress 28% 104s
npm ERR! [TITLE] Downloading Cypress 29% 99s
npm ERR! [TITLE] Downloading Cypress 29% 100s
npm ERR! [TITLE] Downloading Cypress 29% 101s
npm ERR! [TITLE] Downloading Cypress 29% 102s
npm ERR! [TITLE] Downloading Cypress 30% 97s
npm ERR! [TITLE] Downloading Cypress 30% 98s
npm ERR! [TITLE] Downloading Cypress 30% 99s
npm ERR! [TITLE] Downloading Cypress 31% 95s
npm ERR! [TITLE] Downloading Cypress 31% 96s
npm ERR! [TITLE] Downloading Cypress 31% 97s
npm ERR! [TITLE] Downloading Cypress 31% 98s
npm ERR! [TITLE] Downloading Cypress 32% 94s
npm ERR! [TITLE] Downloading Cypress 32% 95s
npm ERR! [TITLE] Downloading Cypress 32% 96s
npm ERR! [TITLE] Downloading Cypress 32% 97s
npm ERR! [TITLE] Downloading Cypress 32% 98s
npm ERR! [TITLE] Downloading Cypress 33% 94s
npm ERR! [TITLE] Downloading Cypress 33% 95s
npm ERR! [TITLE] Downloading Cypress 34% 91s
npm ERR! [TITLE] Downloading Cypress 34% 92s
npm ERR! [TITLE] Downloading Cypress 34% 93s
npm ERR! [TITLE] Downloading Cypress 34% 94s
npm ERR! [TITLE] Downloading Cypress 34% 95s
npm ERR! [TITLE] Downloading Cypress 35% 91s
npm ERR! [TITLE] Downloading Cypress 35% 92s
npm ERR! [TITLE] Downloading Cypress 35% 93s
npm ERR! [TITLE] Downloading Cypress 35% 94s
npm ERR! [TITLE] Downloading Cypress 35% 95s
npm ERR! [TITLE] Downloading Cypress 36% 91s
npm ERR! [TITLE] Downloading Cypress 36% 92s
npm ERR! [TITLE] Downloading Cypress 36% 93s
npm ERR! [TITLE] Downloading Cypress 36% 94s
npm ERR! [TITLE] Downloading Cypress 37% 90s
npm ERR! [TITLE] Downloading Cypress 37% 91s
npm ERR! [TITLE] Downloading Cypress 37% 92s
npm ERR! [TITLE] Downloading Cypress 37% 93s
npm ERR! [TITLE] Downloading Cypress 38% 89s
npm ERR! [TITLE] Downloading Cypress 38% 90s
npm ERR! [TITLE] Downloading Cypress 38% 91s
npm ERR! [TITLE] Downloading Cypress 38% 92s
npm ERR! [TITLE] Downloading Cypress 39% 88s
npm ERR! [TITLE] Downloading Cypress 39% 89s
npm ERR! [TITLE] Downloading Cypress 39% 90s
npm ERR! [TITLE] Downloading Cypress 39% 91s
npm ERR! [TITLE] Downloading Cypress 40% 87s
npm ERR! [TITLE] Downloading Cypress 40% 88s
npm ERR! [TITLE] Downloading Cypress 40% 89s
npm ERR! [TITLE] Downloading Cypress 40% 90s
npm ERR! [TITLE] Downloading Cypress 41% 87s
npm ERR! [TITLE] Downloading Cypress 41% 88s
npm ERR! [TITLE] Downloading Cypress 42% 85s
npm ERR! [TITLE] Downloading Cypress 42% 86s
npm ERR! [TITLE] Downloading Cypress 43% 83s
npm ERR! [TITLE] Downloading Cypress 43% 84s
npm ERR! [TITLE] Downloading Cypress 43% 85s
npm ERR! [TITLE] Downloading Cypress 44% 82s
npm ERR! [TITLE] Downloading Cypress 44% 83s
npm ERR! [TITLE] Downloading Cypress 44% 84s
npm ERR! [TITLE] Downloading Cypress 45% 80s
npm ERR! [TITLE] Downloading Cypress 45% 81s
npm ERR! [TITLE] Downloading Cypress 45% 82s
npm ERR! [TITLE] Downloading Cypress 46% 79s
npm ERR! [TITLE] Downloading Cypress 46% 80s
npm ERR! [TITLE] Downloading Cypress 47% 77s
npm ERR! [TITLE] Downloading Cypress 47% 78s
npm ERR! [TITLE] Downloading Cypress 47% 79s
npm ERR! [TITLE] Downloading Cypress 48% 76s
npm ERR! [TITLE] Downloading Cypress 48% 77s
npm ERR! [TITLE] Downloading Cypress 49% 74s
npm ERR! [TITLE] Downloading Cypress 49% 75s
npm ERR! [TITLE] Downloading Cypress 50% 73s
npm ERR! [TITLE] Downloading Cypress 50% 74s
npm ERR! [TITLE] Downloading Cypress 51% 71s
npm ERR! [TITLE] Downloading Cypress 51% 72s
npm ERR! [TITLE] Downloading Cypress 52% 69s
npm ERR! [TITLE] Downloading Cypress 52% 70s
npm ERR! [TITLE] Downloading Cypress 53% 67s
npm ERR! [TITLE] Downloading Cypress 53% 68s
npm ERR! [TITLE] Downloading Cypress 53% 69s
npm ERR! [TITLE] Downloading Cypress 54% 67s
npm ERR! [TITLE] Downloading Cypress 54% 68s
npm ERR! [TITLE] Downloading Cypress 55% 65s
npm ERR! [TITLE] Downloading Cypress 55% 66s
npm ERR! [TITLE] Downloading Cypress 56% 64s
npm ERR! [TITLE] Downloading Cypress 56% 65s
npm ERR! [TITLE] Downloading Cypress 57% 62s
npm ERR! [TITLE] Downloading Cypress 57% 63s
npm ERR! [TITLE] Downloading Cypress 57% 64s
npm ERR! [TITLE] Downloading Cypress 58% 61s
npm ERR! [TITLE] Downloading Cypress 58% 62s
npm ERR! [TITLE] Downloading Cypress 59% 59s
npm ERR! [TITLE] Downloading Cypress 59% 60s
npm ERR! [TITLE] Downloading Cypress 60% 58s
npm ERR! [TITLE] Downloading Cypress 61% 56s
npm ERR! [TITLE] Downloading Cypress 61% 57s
npm ERR! [TITLE] Downloading Cypress 62% 55s
npm ERR! [TITLE] Downloading Cypress 62% 56s
npm ERR! [TITLE] Downloading Cypress 63% 53s
npm ERR! [TITLE] Downloading Cypress 63% 54s
npm ERR! [TITLE] Downloading Cypress 64% 52s
npm ERR! [TITLE] Downloading Cypress 64% 53s
npm ERR! [TITLE] Downloading Cypress 65% 51s
npm ERR! [TITLE] Downloading Cypress 66% 49s
npm ERR! [TITLE] Downloading Cypress 67% 47s
npm ERR! [TITLE] Downloading Cypress 67% 48s
npm ERR! [TITLE] Downloading Cypress 68% 46s
npm ERR! [TITLE] Downloading Cypress 68% 47s
npm ERR! [TITLE] Downloading Cypress 69% 44s
npm ERR! [TITLE] Downloading Cypress 69% 45s
npm ERR! [TITLE] Downloading Cypress 70% 43s
npm ERR! [TITLE] Downloading Cypress 71% 42s
npm ERR! [TITLE] Downloading Cypress 72% 40s
npm ERR! [TITLE] Downloading Cypress 73% 39s
npm ERR! [TITLE] Downloading Cypress 74% 37s
npm ERR! [TITLE] Downloading Cypress 75% 36s
npm ERR! [TITLE] Downloading Cypress 76% 34s
npm ERR! [TITLE] Downloading Cypress 77% 33s
npm ERR! [TITLE] Downloading Cypress 78% 31s
npm ERR! [TITLE] Downloading Cypress 78% 32s
npm ERR! [TITLE] Downloading Cypress 79% 30s
npm ERR! [TITLE] Downloading Cypress 80% 28s
npm ERR! [TITLE] Downloading Cypress 80% 29s
npm ERR! [TITLE] Downloading Cypress 81% 27s
npm ERR! [TITLE] Downloading Cypress 82% 26s
npm ERR! [TITLE] Downloading Cypress 83% 24s
npm ERR! [TITLE] Downloading Cypress 84% 23s
npm ERR! [TITLE] Downloading Cypress 85% 21s
npm ERR! [TITLE] Downloading Cypress 86% 20s
npm ERR! [TITLE] Downloading Cypress 87% 18s
npm ERR! [TITLE] Downloading Cypress 87% 19s
npm ERR! [TITLE] Downloading Cypress 88% 17s
npm ERR! [TITLE] Downloading Cypress 89% 16s
npm ERR! [TITLE] Downloading Cypress 90% 14s
npm ERR! [TITLE] Downloading Cypress 91% 13s
npm ERR! [TITLE] Downloading Cypress 92% 11s
npm ERR! [TITLE] Downloading Cypress 93% 10s
npm ERR! [TITLE] Downloading Cypress 94% 8s
npm ERR! [TITLE] Downloading Cypress 95% 7s
npm ERR! [TITLE] Downloading Cypress 96% 6s
npm ERR! [TITLE] Downloading Cypress 97% 4s
npm ERR! [TITLE] Downloading Cypress 98% 3s
npm ERR! [TITLE] Downloading Cypress 99% 1s
npm ERR! [TITLE] Downloading Cypress 100% 0s
npm ERR! [TITLE] Downloaded Cypress
npm ERR! [SUCCESS] Downloaded Cypress
npm ERR! [STARTED] Task without title.
npm ERR! The Cypress App could not be unzipped.
npm ERR!
npm ERR! Search for an existing issue or open a GitHub issue at
npm ERR!
npm ERR! https://github.com/cypress-io/cypress/issues
npm ERR!
npm ERR! ----------
npm ERR!
npm ERR! Error: EACCES: permission denied, mkdir '/Users/mac/Library/Caches/Cypress/10.11.0'
npm ERR!
npm ERR! ----------
npm ERR!
npm ERR! Platform: darwin-x64 (20.2.0)
npm ERR! Cypress Version: 10.11.0
npm ERR! [FAILED] The Cypress App could not be unzipped.
npm ERR! [FAILED]
npm ERR! [FAILED] Search for an existing issue or open a GitHub issue at
npm ERR! [FAILED]
npm ERR! [FAILED] https://github.com/cypress-io/cypress/issues
npm ERR! [FAILED]
npm ERR! [FAILED] ----------
npm ERR! [FAILED]
npm ERR! [FAILED] Error: EACCES: permission denied, mkdir '/Users/mac/Library/Caches/Cypress/10.11.0'
npm ERR! [FAILED]
npm ERR! [FAILED] ----------
npm ERR! [FAILED]
npm ERR! [FAILED] Platform: darwin-x64 (20.2.0)
npm ERR! [FAILED] Cypress Version: 10.11.0

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/mac/.npm/_logs/2022-10-30T00_08_28_511Z-debug-0.log

</details>

**Comment by barbados-clemens** [comment]
Sounds like there's a directory access issue to the cypress cache directory. Are you able to install cypress manually in other projects? You could manually set the cache directory with the env var as well. 
This is the default location for cypress and isn't modified for nx workspaces. 

`export CYPRESS_CACHE_FOLDER="some path"`

**Comment by scriptlord** [comment]
I am still having the same issue. Any help would be appreciated

**Comment by barbados-clemens** [comment]
have you tried any of the follow steps?

manually install cypress in a project?
manually change the install path to something you have write permissions to?
