### ISSUE TITLE
Support latest CLI and Service Worker.

### ISSUE THREAD

**Issue by xban1x** [nrwl/nx#129]
Title is quite self explanatory.

**Comment by Yonet** [comment]
Check out the answer here: https://github.com/nrwl/nx/wiki/FAQ

**Comment by Chris1308** [comment]
But i think the FAQ is wrong. It says that the fix-cli-build is the latest master of cli but in reality it's version 1.5 or am i missing something?

**Comment by Yonet** [comment]
CLI 1.6 is released last week, we'll update to latest one soon.

**Comment by xban1x** [comment]
Has this been updated?
