### ISSUE TITLE
Next JS v13 peer deps not correct

### ISSUE THREAD

**Issue by perscrew** [nrwl/nx#12903]
Hi, I get some trouble when migrating to the last version of NX (15.0.4). 

I would like to update my next js project to the last version (v13) but I found that in the @nwrl/next package.json there is a peer dependency set up to `next 12.1.0`.

## Current Behavior

```
nx migrate latest
nx migrate --run-migrations
```

I got : 

![image](https://user-images.githubusercontent.com/2781581/198990997-b882069f-3adb-4466-a0de-053178a22b95.png)

Here an extract of the @nwrl/next package.json v15.0.4, from my node_modules : 

![Capture d’écran 2022-10-31 à 11 49 25](https://user-images.githubusercontent.com/2781581/198991494-a2d28964-5368-4afa-b1fb-dffce454e161.png)

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by ckaeslin** [comment]
same as https://github.com/nrwl/nx/issues/12895

**Comment by FrozenPandaz** [comment]
This was fixed in https://github.com/nrwl/nx/pull/12866 released in `15.0.5`.
