### ISSUE TITLE
Adding storybook to webcomponent project fails at runtime

### ISSUE THREAD

**Issue by herrKlein** [nrwl/nx#12908]
## Current Behavior
Running storybook on a 'ui' lib project fails cause NX searches for react: 
```Cannot find module '@storybook/react/package.json```
Also storybook config in vscode extension points to ```[object Object]```
which is an indicator something went wrong

## Expected Behavior
Running storybook in 'ui' lib folder with correct storybook version. ie pointing to ```@storybook/web-components```

## Steps to Reproduce
Create new NX workspace ```npx create-nx-workspace```
Generate a lib called 'ui'
Add storybook to the lib
Run storybook
( All from the NX vscode extension )

### Environment

![Screenshot 2022-10-31 at 15 17 28](https://user-images.githubusercontent.com/6085660/199029507-d60ebe6e-1b7e-4204-8bd3-51421579a883.png)

  NX  Report complete - copy this into the issue template

  Node : 16.13.2
  OS   : darwin x64
  npm  : 8.1.2
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.6.3
  @nrwl/cypress : 11.6.3
  @nrwl/devkit : 11.6.3
  @nrwl/eslint-plugin-nx : 11.6.3
  @nrwl/express : Not Found
  @nrwl/jest : 11.6.3
  @nrwl/linter : 11.6.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.6.3
  @nrwl/web : 11.6.3
  @nrwl/workspace : 11.6.3
  @nrwl/storybook : 15.0.4
  @nrwl/gatsby : Not Found
  typescript : 4.0.8

**Comment by mandarini** [comment]
Hi there @herrKlein ! Thanks for filing an issue. I can see that you are on Nx 11 but you are using `@nrwl/storybook` version 15.0.4. Can you please either update all your `@nrwl/*` packages to the latest version (or to version `15.0.4`) or downgrade your `@nrwl/storybook` package version to `11.6.3`? The `@nrwl/*` packages versions need to be aligned.

I could not reproduce your issue on the latest version, [here](https://github.com/mandarini/sb-webcomponents-nx) is my repository.

**Comment by herrKlein** [comment]
I see, thats weird. Looks like the initial project was made with an older version and when adding storybook it took the latest. Thanks for looking into that!
