### ISSUE TITLE
nx print-affected --target=test prints unwanted tasks

### ISSUE THREAD

**Issue by DanielRosenkranz** [nrwl/nx#12918]
## Current Behavior
Running on nx version 15.0.4 (14.8.3 works fine)
When running nx print-affected --base=origin/develop --target=test it prints unwanted tasks (see code stub below). 

Local on OSX it works fine.
On Jenkins it prints out te unwanted tasks.

## Expected Behavior
When running  nx print-affected --base=origin/develop --target=test it should only print the affected tasks and not for example 
```
    {
      "id": "@packages/net-stubbing:test",
      "overrides": {
        "__overrides_unparsed__": []
      },
      "target": {
        "project": "@packages/net-stubbing",
        "target": "test"
      },
      "hash": "5a7a4762240e828dfac24e85f51b0e78cb7681815da9cfb1c2f5cbc48b0dffd0",
      "command": "npx nx run @packages/net-stubbing:test",
      "outputs": []
    },
```

## Steps to Reproduce
- install nx version 15.0.4
- run: nx print-affected --base=origin/develop --target=test

### Environment
Problem environment:
 Node : 16.14.2
   OS   : linux x64
   npm  : 8.5.0
   
   nx : 15.0.4
   @nrwl/angular : 15.0.4
   @nrwl/cypress : 15.0.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.4
   @nrwl/js : 15.0.4
   @nrwl/linter : 15.0.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.4
   @nrwl/web : Not Found
   @nrwl/webpack : 15.0.4
   @nrwl/workspace : 15.0.4
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @fortawesome/angular-fontawesome: 0.10.2
   	 @ng-bootstrap/ng-bootstrap: 11.0.1
   	 @ngrx/effects: 14.3.2
   	 @ngrx/store: 14.3.2
   	 @ngrx/store-devtools: 14.3.2
   	 @ngneat/spectator: 12.0.1
   	 ng-mocks: 14.3.2

Working environment:
 Node : 16.13.0
   OS   : darwin x64
   npm  : 8.1.0
   
   nx : 15.0.2
   @nrwl/angular : 15.0.2
   @nrwl/cypress : 15.0.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.2
   @nrwl/js : 15.0.2
   @nrwl/linter : 15.0.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.2
   @nrwl/web : Not Found
   @nrwl/webpack : 15.0.2
   @nrwl/workspace : 15.0.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @fortawesome/angular-fontawesome: 0.10.2
         @ng-bootstrap/ng-bootstrap: 11.0.1
         @ngrx/effects: 14.3.2
         @ngrx/store: 14.3.2
         @ngrx/store-devtools: 14.3.2
         @ngneat/spectator: 11.3.0
         ng-mocks: 14.3.1

**Comment by FrozenPandaz** [comment]
Sorry, I am having trouble understanding your expected behavior.

You executed `nx print-affected --target test` and expect for that `test` task you posted **NOT** to be there? Can you clarify why that is the expected behavior? Is it because you think it shouldn't have been affected by the changes? If so, we need more information on the changes.

Could you please provide a repo we can use to reproduce the issue? It would help us identify the cause of the issue and fix the issue sooner.

**Comment by JHacin** [comment]
A similar thing is happening to us on GitLab CI.

When running the following in a bash script:

`npx nx affected --target=test --runInBand --ci --base=origin/main --head=${GIT_COMMIT_SHA:-@}`

... NX includes "packages" that we haven't defined in our workspace, which causes our pipelines to fail:

```
>  NX   Running target test for 63 project(s):
    ...
    [our apps and libs]
    ...
    - @cypress/webpack-batteries-included-preprocessor
    - @packages/server
    - @packages/net-stubbing
    - @packages/proxy
    - @packages/errors
    - @packages/data-context
    - @packages/launcher
    - @packages/config
    - @packages/electron
    - @cypress/webpack-preprocessor
    - @packages/scaffold-config
    - @cypress/webpack-dev-server
    - @packages/resolve-dist
    - @packages/https-proxy
    - @cypress/vite-dev-server
    - @packages/extension
    - @packages/launchpad
    - @packages/rewriter
    - @packages/example
    - @packages/network
    - @packages/socket
    - @packages/icons
    - @packages/app
    - @packages/ts
```

These all seem to be related to Cypress. Locally it works fine for us on MacOS and Linux.

- GitLab runner version: `gitlab-runner 15.5.0`
- Docker Node image: `node:16-bullseye`

Packages:

```
"dependencies": {
    "@editorjs/editorjs": "^2.25.0",
    "@fortawesome/fontawesome-free": "^6.2.0",
    "@nrwl/next": "15.0.5",
    "broadcast-channel": "^4.18.1",
    "clsx": "^1.2.1",
    "core-js": "^3.23.4",
    "dayjs": "^1.11.6",
    "editorjs-html": "^3.4.2",
    "esprima": "^4.0.1",
    "formik": "^2.2.9",
    "html-react-parser": "^3.0.4",
    "i18next-scanner": "^3.3.0",
    "immer": "^9.0.16",
    "ioredis": "^5.2.0",
    "lodash": "^4.17.21",
    "next": "13.0.0",
    "next-translate": "^1.6.0",
    "nextjs-progressbar": "^0.0.14",
    "react": "18.2.0",
    "react-cookie": "^4.1.1",
    "react-dom": "18.2.0",
    "react-is": "18.2.0",
    "react-query": "^3.39.1",
    "react-transition-group": "^4.4.5",
    "regenerator-runtime": "0.13.7",
    "swiper": "^8.4.4",
    "tslib": "^2.4.1",
    "ua-parser-js": "^1.0.32",
    "yup": "^0.32.11",
    "zustand": "^4.1.4"
  },
  "devDependencies": {
    "@babel/core": "7.12.13",
    "@babel/preset-typescript": "7.12.13",
    "@nrwl/cli": "15.0.5",
    "@nrwl/cypress": "15.0.5",
    "@nrwl/devkit": "15.0.5",
    "@nrwl/eslint-plugin-nx": "15.0.5",
    "@nrwl/jest": "15.0.5",
    "@nrwl/js": "15.0.5",
    "@nrwl/linter": "15.0.5",
    "@nrwl/next": "15.0.5",
    "@nrwl/node": "15.0.5",
    "@nrwl/react": "15.0.5",
    "@nrwl/web": "15.0.5",
    "@nrwl/workspace": "15.0.5",
    "@storybook/react": "~6.5.13",
    "@svgr/webpack": "^5.5.0",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "13.4.0",
    "@testing-library/user-event": "^14.4.3",
    "@types/jest": "28.1.8",
    "@types/lodash": "^4.14.187",
    "@types/node": "18.7.18",
    "@types/react": "18.0.20",
    "@types/react-dom": "18.0.6",
    "@types/react-is": "17.0.3",
    "@types/react-transition-group": "^4.4.5",
    "@types/ua-parser-js": "^0.7.36",
    "@typescript-eslint/eslint-plugin": "5.42.0",
    "@typescript-eslint/parser": "5.42.0",
    "@welldone-software/why-did-you-render": "^7.0.1",
    "babel-jest": "28.1.3",
    "babel-loader": "8.1.0",
    "cypress": "10.10.0",
    "cypress-fail-fast": "^5.0.1",
    "cypress-terminal-report": "^4.1.2",
    "eslint": "8.15.0",
    "eslint-config-next": "13.0.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-jsx-a11y": "6.6.1",
    "eslint-plugin-react": "7.31.8",
    "eslint-plugin-react-hooks": "4.6.0",
    "husky": "^7.0.4",
    "jest": "28.1.3",
    "jest-environment-jsdom": "28.1.1",
    "jest-junit": "^14.0.1",
    "json-server": "^0.17.0",
    "lint-staged": "^12.3.7",
    "msw": "^0.36.8",
    "nodemon": "^2.0.19",
    "nx": "15.0.5",
    "prettier": "2.7.1",
    "quicktype-core": "^6.0.71",
    "react-test-renderer": "18.2.0",
    "sass": "1.55.0",
    "ts-jest": "28.0.8",
    "ts-node": "10.9.1",
    "typescript": "4.8.4",
    "url-loader": "^3.0.0",
    "whatwg-fetch": "^3.6.2"
  },
  "optionalDependencies": {
    "@nrwl/storybook": "15.0.7",
    "@storybook/addon-essentials": "~6.5.13",
    "@storybook/addon-storysource": "^6.5.13",
    "@storybook/builder-webpack5": "~6.5.13",
    "@storybook/manager-webpack5": "~6.5.13",
    "http-proxy-middleware": "^2.0.6",
    "quicktype": "^15.0.261"
  }
```

This started happening after we upgraded our NX workspace. Previously it was fine and the package versions were:

```
"@nrwl/cli": "13.9.7",
    "@nrwl/cypress": "14.8.5",
    "@nrwl/devkit": "13.9.7",
    "@nrwl/eslint-plugin-nx": "13.9.7",
    "@nrwl/jest": "13.9.7",
    "@nrwl/js": "13.9.7",
    "@nrwl/linter": "13.9.7",
    "@nrwl/next": "13.9.7",
    "@nrwl/node": "13.9.7",
    "@nrwl/react": "13.9.7",
    "@nrwl/web": "13.9.7",
```

I guess I'm just wondering what could cause 3rd party stuff to be included when running `nx affected`...

**Comment by JHacin** [comment]
Hm, in our case it seems like Cypress cache was the issue.

Found this thread: https://github.com/nrwl/nx/issues/8646

We are setting the `CYPRESS_CACHE_FOLDER` environment variable in our gitlab CI config to `/cache` (relative to project root), adding `/cache` to `.gitignore` seems to resolve the issue.
