### ISSUE TITLE
Support Installing specific version of React Native 

### ISSUE THREAD

**Issue by SeongwoonHong** [nrwl/nx#12911]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I'd like to Install specific version of React Native

## Motivation

 For those who want to introduce NX to their workplace but their React Native version is not up-to-date. To minimize the regression by updating the version to the latest which is the current behaviour by NX, It'd be nice to be able to initialize NX project by specifying exact version of React Native.
 For instance, my company uses 0.66.4 version of React Native. but when I initialize NX using react-native preset, it's 0.70 which is the latest version. Therefore, a lot of them are not compatible and start breaking. I'd like to keep our current version of React Native.

## Suggested Implementation

Something like
```
npx create-nx-workspace happynrwl --preset=react-native --appName=mobile --veresion=0.66.4
```

**Comment by deepakkumardk** [comment]
Anyone looking into this, would be a beneficial feature for the react-native community.
