### ISSUE TITLE
Failing nx commands due to yargs issue - upgrade package to resolve this issue

### ISSUE THREAD

**Issue by davidslaby** [nrwl/nx#12930]
## Current Behavior
Can't run any nx command due to issue of `yargs` package

https://github.com/yargs/yargs/pull/2242

Bump the version of `yargs` to `17.6.0`

## Expected Behavior
Possible to run nx commands

## Steps to Reproduce
Run `LANG=cs_CZ nx migrate` command on machine 

### Failure Logs
`syntax error in /node_modules/yargs/locales/cs.json`

**Comment by AgentEnder** [comment]
The fix in the linked issue would be present in version 17.6.1, which isn't released yet

**Comment by AgentEnder** [comment]
https://github.com/yargs/yargs/pull/2257

**Comment by AgentEnder** [comment]
Fixed in #12978
