### ISSUE TITLE
Ability to upgrade Nx without upgrading React/Angular

### ISSUE THREAD

**Issue by Lonli-Lokli** [nrwl/nx#12937]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Ability to upgrade Nx without upgrading React/Angular versions

## Motivation
Sometimes we need to have the latest Nx but do not want to upgrade to the latest framework

## Suggested Implementation
optional flag --skip-ng or --skip-react

**Comment by FrozenPandaz** [comment]
I understand the concern of only wanting to update nx and nothing that would change the behavior of your application.

You are free to undo some of the changes that `nx migrate` makes to your `package.json` and remove any related migrations from `migrations.json`. We recommend the versions that we migrate to but you can respectfully decline the updates but we can't guarantee all the versions will work together. This manual process would get you the result that you want. 

I don't think Nx should have flags that are specific to Angular or React. It would have to be more general than that.

Personally I don't think we need a flag at all but I'm open to suggestions on what a general flag and behavior would be.

**Comment by Lonli-Lokli** [comment]
Generally I would like to have separate @nx/angular package fixed, while @nx/web be upgradable

**Comment by isaacplmann** [comment]
Nx 15.8 brings the ability to interactively run `nx migrate` and only update Nx while leaving the frameworks at an older version.

See: https://nx.dev/recipes/other/advanced-update#choosing-optional-package-updates-to-apply

**Comment by Lonli-Lokli** [comment]
Wow!!! Thanks you!!
