### ISSUE TITLE
v15 includes folders not included in v14

### ISSUE THREAD

**Issue by markgoho** [nrwl/nx#12948]
## Current Behavior
v15 includes folders as apps/libs not previously included in v14

## Expected Behavior
Only folders explicitly defined in nx.json, tsconfig.json, or angular.json should be included in list of apps/libs

## Steps to Reproduce
I have a firebase functions folder `/functions` in the root of my workspace. Previous to v14 this folder was completely ignored. Now in v15, it shows up in the list of projects (apps/libs) and because it doesn't work the same way as nx projects, my CI build is failing.

### Failure Logs
``` bash
> nx run functions:test


> functions@ test /home/runner/work/active-branch-tracker/active-branch-tracker/functions
> jest --runInBand --detectOpenHandles

● Validation Error:

  Module @swc/jest in the transform option was not found.
         <rootDir> is: /home/runner/work/active-branch-tracker/active-branch-tracker/functions

  Configuration Documentation:
  https://jestjs.io/docs/configuration
```

### Environment
I don't think this is environment-specific and I'm experiencing this same thing happening across mac/windows/linux

**Comment by markgoho** [comment]
Tried to do this in the package.json of the `/functions` project -- Nx continues to view this as an included project
``` json
"nx": {
  "ignore": true
}
```

**Comment by FrozenPandaz** [comment]
Yes, this is true.

We now also look for other `package.json` projects. You can ignore this project by adding that directory to `.nxignore` (in the root of your workspace)

**Comment by markgoho** [comment]
@FrozenPandaz I understand this is expected behavior in v15 -- is there an opportunity to note this may be a breaking change from 14->15?

**Comment by FrozenPandaz** [comment]
I updated the docs: https://nx.dev/reference/project-configuration#ignoring-a-project
and added a note here: https://github.com/nrwl/nx/releases/tag/15.0.1

I think we're good to close this issue now?

**Comment by markgoho** [comment]
Thanks!
