### ISSUE TITLE
Conflicting types due to both nextjs and react apps being present

### ISSUE THREAD

**Issue by sudo-vaibhav** [nrwl/nx#12950]
## Current Behavior

Building a next JS app is failing. There is a shared UI library which has components used by different react and next apps. The issue is that importing image using the import keyword in next assigns the image the type StaticImageData while importing in react gives the image a string type. So when I build the next app, I get the error

![image](https://user-images.githubusercontent.com/53619134/199567445-cd9c0552-b7d3-4ac2-8dc1-8f092b3f5e90.png)

The type of logo should be a string and even shows up as string in VS Code as you can see
![image](https://user-images.githubusercontent.com/53619134/199567592-be0a2a54-266a-43fb-a6d4-73af6be75503.png)

And the weird part is that this particular file is not even used anywhere in the next app, they just happen to be located in a library which has some stuff which next uses (NOT this component though)

My project structure is like this

- apps
	- nextapp
	- reactapp
- libs
	- shared
		- ui

## Expected Behavior
when I run """nx build nextapp""", it should build without parsing and checking type of files its not even using, or at least I should be able to disable type checking for this library while building next app to prevent this error from occurring and build to occur successfully.

**Comment by ndcunningham** [comment]
This looks like you have a typings inconsistency. 
Maybe your `tsconfig.json` is pointing to the wrong definition? 

Try pointing to the right definition files
- `@nrwl/packages/react/typings/image.d.ts`
- `@nrwl/packages/next/typings/image.d.ts`

This should be working correctly in a fresh project.
