### ISSUE TITLE
DependsOn workspace root.

### ISSUE THREAD

**Issue by Fnxxxxo** [nrwl/nx#12962]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

A way to specify a workspace root as a dependency in targetDefaults. 

## Motivation

 For some reason, my project have a workspace root as web container. All projects implicit depend on it.
I think this support will help some other imformal monorepo.

## Suggested Implementation

Maybe something like  
```
{
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build:root"]
    }
  }
}
```

## Alternate Implementations

Some configuration to say that the root is also a project and should run script first.

**Comment by FrozenPandaz** [comment]
This is planned! :wink: We'll have more details soon.

**Comment by AgentEnder** [comment]
This is added, via `nested projects`. Your root package.json can be found as an Nx project by adding an `nx` key to it, like `"nx": {}`.

Afterwards, you can register the implicit dependency between your projects and the root project, and use the existing dependsOn syntax to reference the build on your root project.
