### ISSUE TITLE
Component testing guidelines/best practices

### ISSUE THREAD

**Issue by blessanm86** [nrwl/nx#12960]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/cypress/cypress-component-testing

### Additional context or description

I am trying to setup component testing in our NX workspace. Many of our apps are very thin and imports components from libraries. The component libraries include all the associated business/UI logic. 

There is not much guidance on where you should put your component tests. I was thinking of putting in my library. But our libraries are not buildable and cypress needs a `devServerTarget`. We use a custom webpack executor to build our apps and copied that into our lib to make it work. Im not sure if this is the right approach.

It would also be great if the docs were improved for custom webpack users. [This is an issue](https://github.com/nrwl/nx/issues/12844) I filed to figure how to get it working.

**Comment by barbados-clemens** [comment]
Thanks for the report @blessanm86, component testing works in any project (library or app) when using in a library the framework specific generators will try to find a valid build config that the library is being included in. you can also manually provide a --build-target=<some-app>:<build-target> to use if the library isn't apart of a buildable app. 

I'll update the docs to make that more clear, thanks for the feedback :)

**Comment by blessanm86** [comment]
@barbados-clemens I got component testing working for our lib by specifying a build target. I'm just unsure about the need for a build target given that we are giving a webpack config in `cypress.config.ts`. It just feels redundant.

**Comment by barbados-clemens** [comment]
the build-target is leveraged via the nxComponentTestingPreset. if you're not using the preset then you don't need to set it.
