### ISSUE TITLE
CLI doesn't works as expected when running task for the defualt project

### ISSUE THREAD

**Issue by haven2world** [nrwl/nx#12986]
## Current Behavior
I have set default project to "main-app", and 
`nx lint` works, `nx run main-app:lint:fix` also works, but `nx lint: fix`  doesn't. Is this as expected?

## Expected Behavior
`nx lint: fix` should work like  `nx run main-app:lint:fix`

### Failure Logs
Error: Cannot find configuration for task main-app:server:dev
    at getExecutorNameForTask (main-app/node_modules/nx/src/tasks-runner/utils.js:123:15)
    at getExecutorForTask (main-app/node_modules/nx/src/tasks-runner/utils.js:129:22)
    at getCustomHasher (main-app/node_modules/nx/src/tasks-runner/utils.js:136:25)
    at TasksSchedule.<anonymous> (main-app/node_modules/nx/src/tasks-runner/tasks-schedule.js:111:62)
    at Generator.next (<anonymous>)

### Environment

   Node : 18.9.0
   OS   : darwin x64
   npm  : 8.19.1
   
   nx : 14.3.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.3.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.4
   @nrwl/eslint-plugin-nx : 14.7.11
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.4
   @nrwl/js : 14.3.4
   @nrwl/linter : 14.3.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.8.6
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 14.3.4
   @nrwl/react : 14.3.4
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.3.4
   @nrwl/web : 14.3.4
   @nrwl/workspace : 14.3.4
   typescript : 4.8.4
   ---------------------------------------
   Community plugins:
         @ns3/nx-jest-playwright: 3.2.0

**Comment by AgentEnder** [comment]
This is expected, when running `nx {target}`, you are using what we call "infix" notation. That is more obvious when you specify a project, since it looks like `nx {target} {project}`. To specify a configuration, you can run `nx lint -c fix`
