### ISSUE TITLE
Serve command fails on TS error, TSC_COMPILE_ON_ERROR=true doesn't work

### ISSUE THREAD

**Issue by goldylucks** [nrwl/nx#12983]
## Current Behavior
Serve command crashes when there are TS errors, even tho `TSC_COMPILE_ON_ERROR=true` is set in `.env`

## Expected Behavior
Should not crash according to flag.
I don't know if this is a regression.

## Steps to Reproduce
1. create nx workspasce with a lib/app
2. Set `TSC_COMPILE_ON_ERROR=true` in `.env`
3. put a TS error in your code
4. serve the app/lib 

### Failure Logs
Any TS error

### Environment
```
$ npx nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.18.0
   OS   : darwin arm64
   yarn : 1.22.18

   nx : 14.4.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.4.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.3
   @nrwl/eslint-plugin-nx : 14.4.3
   @nrwl/express : 14.4.3
   @nrwl/jest : 14.4.3
   @nrwl/js : 14.4.3
   @nrwl/linter : 14.4.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.4.3
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.4.3
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.3
   @nrwl/web : 14.4.3
   @nrwl/workspace : 14.4.3
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:

```

**Comment by goldylucks** [comment]
FYI, fixing the TS error requires a server restart to fix the browser crash

**Comment by Ofadiman** [comment]
Possibly resolved [here](https://github.com/nrwl/nx/issues/11536#issuecomment-1304493470).

**Comment by goldylucks** [comment]
continuing there, sorry for multiple issues 🤦‍♀️
