### ISSUE TITLE
Extend schematics

### ISSUE THREAD

**Issue by tfiwm** [nrwl/nx#130]
Hi is the a way to extend the nx schematics with own?
Would be a nice feature if not :)

**Comment by vsavkin** [comment]
You can build your own schematics and run them in the same fashion.

Say you create a npm package called "myschematics" that contains schematic named "myscheamtic". Add that package to the project and then run:

```
ng g myschematic someName --someParam --collection=myschematics
```

Currently the CLI has a limitation where you can only have one default collection, so you will have to provide the collection name when running your custom schematics. Other than that, they will work in exactly the same way.

**Comment by sprov03** [comment]
I'm having an issue with this.
https://nrwl.io/nx/workspace-specific-schematics

That is the current link to your documentation as of 10/8/2018.

When I follow the instructions exactly.  I end up on the last step where it says, 
"Finally, invoke it to generate a new data-access lib."

There are no instructions as to how "Invoke it".

The new command dose does not show up in the Angular Console. Or When I run "ng g -h" directly in the workspace the data-access-lib command is not an option
