### ISSUE TITLE
Fix documentation - Set up Compodoc for Storybook on Nx

### ISSUE THREAD

**Issue by technbuzz** [nrwl/nx#13007]
### Documentation issue

- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/storybook/angular-storybook-compodoc#3.-enable-and-configure-it

### Additional context or description

This sections tells that `compodoc: true` will be true in **project.json** but this is not the case if nx version is `13.9.0`. I found out when I upgrated to version **15**.
I didn't went through `nx migrate` path but `nx generate change-storybook-target` helped me properly update the config

**Comment by mandarini** [comment]
Hi there @technbuzz ! Thanks for filing an issue! :) Our documentation applies to the latest version of Nx!

Moving from version to version you should be using `nx migrate`, ideally, to take advantage of our migrators, and bring your workspace up to date with the version to which you are migrating to. 

I assume you tried setting up `compodoc` and when you realized that your `storybook` target looked different than what it was in the guide, you somehow ended up [this docs page](https://nx.dev/storybook/angular-storybook-targets), and used the migrator? Was that the case? If yes, how did you find that docs page? Or did you just upgrade to the latest version?

I am asking all these questions to understand how I could improve the info on that page to indicate that it corresponds to the latest version..
