### ISSUE TITLE
(v7.8.0) create-nx-workspace fails on Windows with npm

### ISSUE THREAD

**Issue by jdnierth** [nrwl/nx#1300]
After successfully installing angular\cli and nrwl\schematics via npm, running the following command on Windows `create-nx-workspace <project_name>` fails with:

> C:\Users\xxx\ is not recognized as an internal or external command in create-nx-workspace.js line 61

(see screenshots in section "Failure logs")

## Context & Steps to Reproduce

1. Node v10.15.3
2. NVM v1.1.7
2. Windows 10 x64
3. Successfully installed angular-cli: `npm install @angular/cli`
4. Successfully installed nrwl schematics: `npm install @nrwl/schematics`

![angular-version](https://user-images.githubusercontent.com/12001981/56865727-70057d00-69d1-11e9-838b-27e6c3d91d35.PNG)

### Failure Logs

![create-nx-workspace-error](https://user-images.githubusercontent.com/12001981/56865784-25d0cb80-69d2-11e9-8dfe-46def3b9605f.PNG)

## Other information

- This issue seems to be related to how npm finds its modules. The space in the path which should point to the nrwl/schematics node module seems to be failing because of not being in quotes.

**Comment by FrozenPandaz** [comment]
Fixed with https://github.com/nrwl/nx/commit/a074edf3f9b49b089543616f435b0887eacafd8a
