### ISSUE TITLE
Conflicting react dependencies in @nrwl/expo

### ISSUE THREAD

**Issue by whoisdominic** [nrwl/nx#13005]
## Current Behavior

I have added @nrwl/expo to my workspace using the NX Console. After the dependency installs successfully I am not able to download my dependencies due to a react conflict

## Expected Behavior

I expect to be able to use the nx packages in a basic repo and not have conflicting react dependencies when dealing with expo or the react native packages

## Steps to Reproduce

1. Create a new workspace using `npx create-nx-workspace@latest`
2. Run `npm i @nrwl/expo`
3. Generate a new expo project using the NX Console
4. Run `npm i`

### Failure Logs

![Screenshot 2022-11-04 at 5 16 58 PM](https://user-images.githubusercontent.com/32504814/200091945-f44fc7ec-624e-4e4f-9e49-2dffcf49588a.png)

`
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-native@0.69.6
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR!   peer react@">=16.8.0" from @emotion/react@11.10.5
npm ERR!   node_modules/@emotion/react
npm ERR!     @emotion/react@"^11.10.5" from the root project
npm ERR!     peer @emotion/react@"^11.0.0-rc.0" from @emotion/styled@11.10.5
npm ERR!     node_modules/@emotion/styled
npm ERR!       @emotion/styled@"^11.10.5" from the root project
npm ERR!       4 more (@mui/lab, @mui/material, @mui/styled-engine, @mui/system)
npm ERR!     4 more (@mui/lab, @mui/material, @mui/styled-engine, @mui/system)
npm ERR!   25 more (@emotion/styled, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"18.0.0" from react-native@0.69.6
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.69.6" from the root project
npm ERR!   peer react-native@"*" from @react-native-community/cli@8.0.6
npm ERR!   node_modules/@react-native-community/cli
npm ERR!     @react-native-community/cli@"^8.0.4" from react-native@0.69.6
npm ERR!   5 more (@tanstack/react-query, @testing-library/jest-native, ...)
npm ERR! 
npm ERR! Conflicting peer dependency: react@18.0.0
npm ERR! node_modules/react
npm ERR!   peer react@"18.0.0" from react-native@0.69.6
npm ERR!   node_modules/react-native
npm ERR!     react-native@"0.69.6" from the root project
npm ERR!     peer react-native@"*" from @react-native-community/cli@8.0.6
npm ERR!     node_modules/@react-native-community/cli
npm ERR!       @react-native-community/cli@"^8.0.4" from react-native@0.69.6
npm ERR!     5 more (@tanstack/react-query, @testing-library/jest-native, ...)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
`

**Comment by xiongemi** [comment]
currently, it does not support to have both @nrwl/react-native and @nrwl/expo in the same repo, due to the conflicting version of react-native.

**Comment by xiongemi** [comment]
closing this issue for now. use `npm install --foce` to overcome the error
