### ISSUE TITLE
lib with Ng-packagr subentries and implicit return types - Cannot find module

### ISSUE THREAD

**Issue by Azbesciak** [nrwl/nx#13019]
## Current Behavior
Issues with lib generation, when return type is not explicit set; in the declaration import path is not correct, one nesting is missing:
The error is:
```ts
Building entry point '@impl-dep/my-lib/configuration/consumer'
------------------------------------------------------------------------------
× Compiling with Angular sources in Ivy partial compilation mode.

 >  NX   dist/libs/bundle/configuration/service/service.d.ts:5:26 - error TS2307: Cannot find module '../../../../dist/libs/bundle/some/nested/dependency' or its corresponding type declarations.

   5     dependency(): import("../../../../dist/libs/bundle/some/nested/dependency").Dependency;
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```
when the correct path should contain an additional `../`; it is reproducible, this behavior occurred in a much bigger project on other samples.

_Explicit import/type declaration solves the issue_.

## Expected Behavior
The compilation does not fail.

## Steps to Reproduce
https://github.com/Azbesciak/Nx-packagr-lib-issue-cannot-find-module

clone and run `nx build my-lib`

> please notice that this dir structure is by design, my lib is created from the part of the existing (quite big) app, when I extensively use typescript aliases... as we know these may not be used 1:1 in libs, therefore I am going to have a postprocessing step in my lib generation, which wraps every file in a single module (yes, the compilation is terribly slow, and it cannot be concurrent as I see) like in the repo's structure.

### Failure Logs
placed above, except this sublibs compile

### Environment

   Node : 16.14.2
   OS   : win32 x64
   npm  : 8.5.0

   nx : 15.0.10
   @nrwl/angular : 15.0.10
   @nrwl/cypress : 15.0.10
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.10
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.10
   @nrwl/js : 15.0.10
   @nrwl/linter : 15.0.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : 8.12.11
   @nrwl/storybook : 15.0.10
   @nrwl/web : Not Found
   @nrwl/webpack : 15.0.10
   @nrwl/workspace : 15.0.10
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

**Comment by AgentEnder** [comment]
Hey @Azbesciak , it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate latest`.
