### ISSUE TITLE
error: ReferenceError: SHA-1 for file node_modules/react-native/index.js is not computed

### ISSUE THREAD

**Issue by gopalreddyzonofi** [nrwl/nx#13016]
## Current Behavior

Getting SHA-1 error when we upgrade Nx and react native and when we enable debug log in metro config we could see it is throwing error for all the libs we have

![image](https://user-images.githubusercontent.com/97211916/200184862-e50c2033-a80f-430f-ab4e-bfdb15e012f7.png)

**[Nx] Unable to resolve with default Metro resolver:_**libName**_**

![image](https://user-images.githubusercontent.com/97211916/200184812-4672741e-9830-44de-becf-b48baa73d06b.png)

MetroConfig

`const { withNxMetro } = require('@nrwl/react-native');
const { getDefaultConfig } = require('metro-config');
const exclusionList = require('metro-config/src/defaults/exclusionList');

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig();
  const { projectRoot, ...cfg } = withNxMetro(
    {
      transformer: {
        getTransformOptions: async () => ({
          transform: {
            experimentalImportSupport: false,
            inlineRequires: true,
          },
        }),
        babelTransformerPath: require.resolve('react-native-svg-transformer'),
      },
      resolver: {
        assetExts: assetExts.filter((ext) => ext !== 'svg'),
        sourceExts: [...sourceExts, 'svg'],
        blockList: exclusionList([/^(?!.*node_modules).*\/dist\/.*/]),
      },
    },
    {
      // Change this to true to see debugging info.
      // Useful if you have issues resolving modules
      projectRoot: __dirname,
      watchFolders: [],
      debug: false,
      // all the file extensions used for imports other than 'ts', 'tsx', 'js', 'jsx'
      extensions: [],
    }
  );
  cfg.watchFolders = [projectRoot]; // <- using the projectRoot for watchFolders

  return cfg;
})();`

## Expected Behavior

App should run 

  
  **nx report**
   Node : 18.8.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 15.0.9
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.9
   @nrwl/detox : 15.0.9
   @nrwl/devkit : 15.0.9
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.9
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.9
   @nrwl/js : 15.0.9
   @nrwl/linter : 15.0.9
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.0.10
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.9
   @nrwl/react-native : 15.0.9
   @nrwl/rollup : 15.0.9
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.9
   @nrwl/web : 15.0.9
   @nrwl/webpack : 15.0.9
   @nrwl/workspace : 15.0.9
   typescript : 4.8.4
   
   @xiongemi Please help

**Comment by quicksilverr** [comment]
Hey, this is due to circular dependencies, in your repo. 
Use the package dpdm, to figure out the circular dependencies and remove the critical ones.
