### ISSUE TITLE
Generated js code uses '\' in import when configuring external projects.

### ISSUE THREAD

**Issue by janwiebedroid** [nrwl/nx#13011]
## Current Behavior
When running nx build on a project that has a dependency to another project the paths are generated like this: `import { child } from "..\..\child\src";`

## Expected Behavior
I expect that the paths are generated like: `import { child } from "../../child/src";` or `import { child } from "..\\..\\child\\src";`

## Steps to Reproduce
* Create two new buildable libs (child and parent)
* Configure parent like this:

tsconfig.json
```
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "module": "ESNext",
    "target": "es2017",
    "sourceMap": false,
    "declaration": true,
    "moduleResolution": "Node",
    "esModuleInterop": true,
    "skipLibCheck": true,
  },
  "files": [],
  "include": [],
  "references": [
    {
      "path": "./tsconfig.lib.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ]
}
```

package.json
```
{
  "name": "nx-import-bug-parent",
  "version": "0.0.1",
  "type": "module"
}
```
project.json
```
...
"build": {
  "options": {
         ...
        "updateBuildableProjectDepsInPackageJson": false,
        "external": ["@external/child"]
   }
}
```

* Run `nx build parent`
* Js is generated with incorrect path

Reproducable here: https://github.com/janwiebedroid/nx-externals-bug

### Environment
```
   Node : 16.17.0
   OS   : win32 x64
   npm  : 7.22.0

   nx : 15.0.8

```

The issue only occurs on windows and is probably in [inline.js](https://github.com/janwiebedroid/nx/blob/master/packages/js/src/utils/inline.ts). I will try to solve it myself.

**Comment by AgentEnder** [comment]
If you want to put up a PR to fix this, it does sound like it is in inline.js. You could try replacing path.join, with @nrwl/devkit's method `joinPathFragments`
