### ISSUE TITLE
The loader-utils dependency has a critical vulnerability.

### ISSUE THREAD

**Issue by ManuelSLemos** [nrwl/nx#13027]
Hi, I have found a possible vulnerability with the loader-utils dependency.

Currently nx has as dependency loader-utils v1.2.3 and three days ago a vulnerability with these details has been reported:

loader-utils <2.0.3
Severity: critical
Prototype pollution in webpack loader-utils

[More details](https://github.com/advisories/GHSA-76p3-8jx3-jpfq)

In my case, I found it using `npm audit`. 

I hope it helps.

**Comment by PKief** [comment]
@skrtheboss already created an MR for it: https://github.com/nrwl/nx/issues/13027

**Comment by jansgescheit** [comment]
is there a timeline for release?
