### ISSUE TITLE
SVG ReactComponent Typescript Error

### ISSUE THREAD

**Issue by baesku789** [nrwl/nx#13023]
## Current Behavior

i'm using nx with nextjs, so i import  svg file as ReactComponent. but i got typescript Error 
<code>Module '"*.svg"' has no exported member 'ReactComponent'. Did you mean to use 'import ReactComponent from "*.svg"' instead?</code>

my ```custom.d.ts```   in tsconfig.js

```
declare module '*.svg' {
  import React = require('react');

  export const ReactComponent: REact.FC<React.SVGProps<SVGSVGElement>>;
  const src: string;
  export default src;
}
```

## Expected Behavior

No Typescript Error. i'm very sad...
## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by Cirelion** [comment]
Did you end up fixing this? If so, how?

**Comment by jaysoo** [comment]
Remove your own type definitions as the one from Next.js already declares the following:

```
declare module '*.svg' {
  /**
   * Use `any` to avoid conflicts with
   * `@svgr/webpack` plugin or
   * `babel-plugin-inline-react-svg` plugin.
   */
  const content: any

  export default content
}
```

If you really want to you can include ours that provides a more correct type: `@nrwl/react/typings/image.d.ts`. For example, in your `tsconfig.json` you can put the following:

```
"include": [
    "**/*.ts",
    "**/*.tsx",
    "**/*.js",
    "**/*.jsx",
    "next-env.d.ts",
    "../../node_modules/@nrwl/react/types/image.d.ts"
]
```
