### ISSUE TITLE
Emotion babel plugin not working properly when upgrading to NX 14.6.0+

### ISSUE THREAD

**Issue by ureciocais** [nrwl/nx#13055]
Upgrading from the latest 14.5 to 14.6.0 and beyond throws an error when using component selectors via libraries.
Something like:
```
// component in a lib
const ComponentOne = styled.div``

export const ComponentWithCompSelector = styled.div`
${ComponentOne} {
    background: white;
  }
`
```

```
// usage on an app (running via a jest test)
function App () {
  return <ComponentWithCompSelector />
}
```

## Current Behavior

Error when running tests with jest:
`Component selectors can only be used in conjunction with @emotion/babel-plugin, the swc Emotion plugin, or another Emotion-aware compiler transform.`

## Expected Behavior

Tests work

## Steps to Reproduce

Setup an NX app on 14.5.8 and migrate to any version that's >= 14.6

### Failure Logs

`Component selectors can only be used in conjunction with @emotion/babel-plugin, the swc Emotion plugin, or another Emotion-aware compiler transform.`

### Environment

```
 Node : 16.14.0
   OS   : darwin x64
   yarn : 1.22.19

   nx : 15.0.11
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.11
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.11
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.11
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.11
   @nrwl/js : 15.0.11
   @nrwl/linter : 15.0.11
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.11
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.11
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.11
   @nrwl/web : 15.0.11
   @nrwl/webpack : 15.0.11
   @nrwl/workspace : 15.0.11
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by barbados-clemens** [comment]
does this only happen in tests @ureciocais? if so do you have a repo I can take a look at to investigate with?

**Comment by ureciocais** [comment]
Sure @barbados-clemens, here is the repo https://github.com/ureciocais/issue-emotion-babel
It only happens on tests, yes -> `yarn nx test issue-app`

**Comment by barbados-clemens** [comment]
This looks to be just because babel-jest isn't picking up the .babelrc file. 
you can copy the contents of the babelrc and add it to the inlined babel-jest options. 
i.e.
```ts
transform: {
    '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': '@nrwl/react/plugins/jest',
    '^.+\\.[tj]sx?$': ['babel-jest', {
  presets: [
    [
      "@nrwl/react/babel",
      {
        "runtime": "automatic",
        "importSource": "@emotion/react"
      }
    ]
  ],
  plugins: ["@emotion/babel-plugin"]
}],
  },
```
you can force it by passing the path to the .babelrc file in the jest config
i.e.
```ts
transform: {
    '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': '@nrwl/react/plugins/jest',
    '^.+\\.[tj]sx?$': ['babel-jest', { configFile: path.join(__dirname, '.babelrc') }],
  },
```

I think also renaming the .babelrc file to babel.config.json can also work. this tells babel that this is the root config. 

Let me know if any of those options work for you.

**Comment by ureciocais** [comment]
Awesome! that worked! Thank you @barbados-clemens :)
