### ISSUE TITLE
Nx can't find any projects in our repository from the 15.0.11 release

### ISSUE THREAD

**Issue by Will956** [nrwl/nx#13063]
Hello 👋 

## Current Behavior

We have a repository that uses Nx and our setup is set as follows:
```
/package-a
  package.json
/package-b
  package.json
/directory
package.json
nx.json
```

The root package.json does not have a `workspace` entry, we do not use npm workspace.

Since the release of 15.0.11, `nx graph` can't find any projects.

The error message from the `nx print-affected` command:
```
NX   Nx could not find any projects. Check if you need to configure workspaces in package.json or pnpm-workspace.yaml
```

## Expected Behavior
Before that release, Nx can find our projects: `package-a` and `package-b`.

According to the error message, it looks like we have to use `workspace` now but I didn't find any documentation that push in that direction _(but maybe I missed something)_.

### Environment
```
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : darwin x64
   npm  : 8.1.2
   
   nx : 15.0.12
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.8
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.8
   @nrwl/js : Not Found
   @nrwl/linter : 14.5.8
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 14.5.8
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

Thanks 🙏

**Comment by Will956** [comment]
Ok, I guess I have to add `plugins: ["package-json"]` in my `nx.json` 🕵️  But now I get another issue:
```
 >  NX   unable to find tsconfig.base.json or tsconfig.json
```
We do not have a root `tsconfig.json` in our repository, there are located in each package.

**Comment by Will956** [comment]
Hey @FrozenPandaz, can you 👀 at this please? Or if you can send any documentation that can help us, thanks 🙏

**Comment by FrozenPandaz** [comment]
Yes, a new plugin is available: `nx/plugins/package-json`. What this plugin does is that it will re-enable the behavior prior to `15.0.11` find all `package.json` files as projects even without npm/yarn workspaces. After adding that to your workspace, the projects that showed up before should show up. Let me know if you have any issues.

Sorry for the delay.

**Comment by Will956** [comment]
Thanks @FrozenPandaz, works like a charm ❤️
