### ISSUE TITLE
provide option to create nx workspace with karma and protractor

### ISSUE THREAD

**Issue by lokeshdaiya** [nrwl/nx#1306]
## Expected Behavior
Provide option to generate workspace with karma and protractor .

## Current Behavior

When I run command `npx create-nx-workspace myworkspace` it asks for framework, after selecting  angular it generates angular project with jest and cypress, but I want karma and protractor 

- version of Nx used 7.8.1
- version of Angular CLI used 7.3.1

**Comment by vsavkin** [comment]
Presets, which you select when running create-nx-workspace, are just shortcuts--to help you set up your workspace with a single command. 

If you want to use karma and protractor, run: 
* `create-nx-worskpace myworkspace --preset=empty`
* `ng g app angularapp --unit-test-runner=karma --e2e-test-runner=proctractor`

You can also set defaults values in angular.json, such that `ng g app` will always default to karma and protractor.

**Comment by admir86** [comment]
@vsavkin not working with 8.0.0-rc.1
```
Cannot parse arguments. See below for the reasons.
    Argument --unit-test-runner could not be parsed using value "karma". Valid values are: "jest", "none".
```

**Comment by lokeshdaiya** [comment]
@vsavkin Can you add this in help section or some where in your documentation ?

**Comment by lokeshdaiya** [comment]
`create-nx-worskpace myworkspace --preset=empty` is not working with 8.0.0-rc.2

**Comment by SaliZumberi** [comment]
ng g app XXX-app --unit-test-runner=karma --e2e-test-runner=protractor

where xxx is your project-name

**Comment by oletrn** [comment]
Finally, I've managed to generate a project with Karma runner this way:

1. `npx create-nx-workspace --preset=empty --name=my-app`
2. `cd my-app`
3. `npm install @nrwl/angular`
4. `nx generate @nrwl/angular:app foobar --style=scss --unitTestRunner=karma`
