### ISSUE TITLE
Cannot mark optional deps like pg-native as external with the esbuild builder

### ISSUE THREAD

**Issue by marbemac** [nrwl/nx#13072]
## Current Behavior

Running the `@nrwl/esbuild:esbuild` executor on any project that leverages the `pg` library (which tons of packages do, e.g. `prisma`), that does also not use the optional `pg-native` dep, results in an error:

<img width="717" alt="Screen Shot 2022-11-08 at 2 48 12 PM" src="https://user-images.githubusercontent.com/847542/200672145-5f5a90f5-7548-42bd-80b4-24dc9df19a0c.png">

Marking `pg-native` as external (which should be OK, since it's an optional dep) results in this error:

<img width="631" alt="Screen Shot 2022-11-08 at 2 49 48 PM" src="https://user-images.githubusercontent.com/847542/200672388-cb69798c-19ba-4062-8479-f3b3eee95dd9.png">

Boils down to the check over here -> https://github.com/nrwl/nx/blob/master/packages/esbuild/src/executors/esbuild/esbuild.impl.ts#L43-L47

## Expected Behavior

One can mark the entire `pg` as external, but it'd be much preferred if we could mark `pg-native` as external so that the `pg` dep is bundled in.

## Steps to Reproduce

1. Create an app or lib with the esbuild builder, e.g. `nx g @nrwl/js:lib mylib --bundler=esbuild`.
2. `yarn/npm install pg`
3. In your app/lib main, `import * as pg from 'pg'` and `console.log(pg)` to make sure it's not tree-shaken out
4. `nx build mylib` to see the first error
5. Add `"external": ["pg-native"]` in the `project.json` build target
6. `nx build mylib` to see the second error

### Environment

```
   Node : 18.7.0
   OS   : darwin arm64
   yarn : 3.2.4

   nx : 15.0.12
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.12
   @nrwl/esbuild : 15.0.12
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.12
   @nrwl/js : 15.0.12
   @nrwl/linter : 15.0.12
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.0.12
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @nx-tools/nx-container: 4.0.0-alpha.11
```

**Comment by chaseholdren** [comment]
workaround for anyone that's struggling, move the "external" option into a "esbuildOptions" object.

so this:
```
"options": {
    "external": ["whatever"]
}
```

becomes this:

```
"options": {
    "esbuildOptions": {
        "external": ["whatever"]
    }
}
```

**Comment by JBryan98** [comment]
Did you fix this issue?

**Comment by jtlapp** [comment]
This is a pretty serious issue. Nx is presently incompatible with the node postgres [pg](https://github.com/brianc/node-postgres) package. Looks like I need to spend time trying to find a workaround...

**Comment by jtlapp** [comment]
@marbemac, maybe you could change the title to something that expresses the seriousness of this issue? E.g "Nx is presently incompatible with the pg package"

I'm having this problem trying to build an app generated with `@nrwl/node`.

**Comment by jtlapp** [comment]
What about solving the problem by adding a project field such as `ignoreDeps`? I admit, this is a hack based not fully understanding the problem:

```ts
    options.external.map((name) => {
      const externalNode = context.projectGraph.externalNodes[`npm:${name}`];
      if (!externalNode && !options.ignoreDeps?.includes(name))
        throw new Error(
          `Cannot find external dependency ${name}. Check your package.json file.`
        );
      return {
        name,
        outputs: [],
        node: externalNode,
      };
    });
```

Meanwhile, I have to determine whether to replace Nx with maybe Turborepo. I'm stuck.

**Comment by griZZZly8** [comment]
@jtlapp since this issue is only related to esbuild I found a workaround for this in my monorepo setup. I switched to `@nrwl/webpack:webpack` executor. Not sure if it can help you though.
