### ISSUE TITLE
[Testing with readFirst] Observable type error on nx version 15.0.6 and above

### ISSUE THREAD

**Issue by tigatujuhlima** [nrwl/nx#13081]
Hi,

I have an angular application and am currently on nx version 15.0.5 with rxjs version 7.5.6 and have the problem that the unit test fail when I update to all the newer patch versions.

## Current Behavior
The unit test fail on the `readFirst`, as it seems that the Observable import is not the same as the Observable import of rxjs, which confuses me. The exact error:

> Argument of type 'import("/.../node_modules/rxjs/dist/types/internal/Observable").Observable<boolean>' is not assignable to parameter of type 'import("/.../node_modules/@nrwl/angular/node_modules/rxjs/internal/Observable").Observable<boolean>'.

> Type 'Observable<boolean>' is missing the following properties from type 'Observable<boolean>': _isScalar, _trySubscribe, _subscribe

## Expected Behavior
No type error, unit test succeeds just like in nx version 15.0.5.

## Steps to Reproduce
Use readFirst for a unit test in nx version 15.0.6 or above.

**Comment by sjimenez77** [comment]
Same error here after upgrading to Nx 15.3.2 and NgRx 15.0.0

**Comment by sjimenez77** [comment]
After upgrading to Nx 15.3.3 the error is still present. Any updates on this @AgentEnder? Thanks!

**Comment by Coly010** [comment]
Can you provide a repo that contains this?

My assumption is that you're using the DataPersistence API from `@nrwl/angular`. 

`@nrwl/angular` is unfortunately pinned to `rxjs 6` as `angular-devkit` has not updated to `rxjs 7`.

**Comment by Coly010** [comment]
You might be able to the the `firstValueFrom` operator from RxJS itself https://rxjs.dev/api/index/function/firstValueFrom

**Comment by sjimenez77** [comment]
Yes, you are right @Coly010! I forgot completely `firstValueFrom` operator 😄
