### ISSUE TITLE
NX doesn't import my Stencil package into another Stencil Package

### ISSUE THREAD

**Issue by IgorSteps** [nrwl/nx#13080]
I have an NX monorepo set up with two Stencil packages: Package-A and Package-B.

## Current Behavior

When I do import '@nx-workspace/Package-A' inside Package-B and run build - I never get Package-A included in the Package-B dist folder. It works fine when I serve my project. The tsconfig.base.json is set up by nxwith paths like so:
```
"@nx-workspace/Package-A": ["dist/packages/Package-A"],
      "@nx-workspace/Package-A/loader": [
        "dist/packages/Package-A/loader"
      ],
"@nx-workspace/Package-B": ["dist/packages/Package-B"],
"@@nx-workspace/Package-B/loader": [
        "dist/packages/Package-B/loader"
      ],
```
I also tried to change this path instead:
`@nx-workspace/Package-A": ["packages/src/index.ts"]
`, howver it seems nx doesn't export any of my Stencil components.

## Expected Behavior

I expected Package-B dist folder to include Package-A  so that I can distribute one within the other. I guess the question is:

Is this a bug with the  the path that doesn't make sure when Package-B is built, it includes Package-A build files in Package-B dist folder? 
**OR** 
Is it supposed be in such way: You still `npm i` Package-A into Package-B and `tsconfig.base` just allows you to use local version of Package-A rather then npm one?

**Comment by IgorSteps** [comment]
> Package-A would still need to be in Package-B's package.json for consumers of Package-B, unless some kind of bundling occurred when building it.

That's what path to index.ts in Package-A should be doing, but doesn't...
I have two other packages in there with import paths like:
```
  "@nx-workspace/Package-C": ["packages/Package-C/src/index.ts"],
  "@nx-workspace/Package-D": ["packages/Package-C/src/index.ts"]
```
which includes them two in Package-B's `dist` folder without `npm installing` them. One difference is they are not stenciljs projects...

**Comment by AgentEnder** [comment]
Hey @IgorSteps! Sorry for the long period of inactivity on this guy. 

What executor are you using to build your stencil project? Any inlining / bundling is handled by the executor, not Nx itself, and not all executors do any inlining / bundling. 

The tsconfig paths are for editor support only, but some tooling (such as Nx's dependency graph, webpack, rollup, etc) supports using them at build time. For some more info on that, check out why ts-node doesn't support tsconfig-paths by default: https://typestrong.org/ts-node/docs/paths/#why-is-this-not-built-in-to-ts-node

In any case, my gut is that your other packages that are non-stencil are using an executor which handles this,
