### ISSUE TITLE
Unable to read workspace file angular.json: Invalid format version detected - Expected:[ 1 ] Found: [ 2 ]

### ISSUE THREAD

**Issue by michaelwijnands** [nrwl/nx#13097]
## Current Behavior
When I try to start our app after upgrading to Angular 13 I get the following error message:
`Unable to read workspace file '/Users/michael/Projects/app-frontend/angular.json': Invalid format version detected - Expected:[ 1 ] Found: [ 2 ]`

When I change the version in angular.json back to 1 I get the following error: 
`No projects support the 'serve' target.`

## Expected Behavior
I would expect my app to start properly. 

## Steps to Reproduce
I followed the following steps to update to Angular 13:
1. Nrwl update to 12.10.1 as it's the latest version for Angular 12 which we were previously using.
2. Update angular.json to version 2.
3. Update to latest version of Angular 13 through NRWL migrations. I chose to use the latest version of NRWL 13 because some packages we use don't support NRWL 14 yet.
4. Update from a full nx.json and angular.json file to configuration per project; every lib has its own project.json file (`nx g @nrwl/workspace:convert-to-nx-project --all`)

Because at this point I got the errors named above I tried switching back and forth angular version 1 and version 2 but that doesn't help. When I try to run migrations with version 1 there is nothing to be migrated, the same goes for version 2.

### Failure Logs
```
ng serve
Unable to read workspace file '/Users/michael/Projects/app-frontend/angular.json': Invalid format version detected - Expected:[ 1 ] Found: [ 2 ]

ng serve
No projects support the 'serve' target.
```

### Environment
   Node : 16.15.0
   OS   : darwin x64
   npm  : 8.5.5
   
   nx : 13.10.6
   @nrwl/angular : 13.10.6
   @nrwl/cypress : 13.10.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.6
   @nrwl/eslint-plugin-nx : 13.10.6
   @nrwl/express : 13.10.6
   @nrwl/jest : 13.10.6
   @nrwl/js : 13.10.6
   @nrwl/linter : 13.10.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 13.10.6
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.6
   @nrwl/web : Not Found
   @nrwl/workspace : 13.10.6
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         @ionic/angular: 6.2.9
         @nguniversal/express-engine: 13.1.1
         @nxtend/capacitor: 13.0.0
         @nxtend/ionic-angular: 13.1.0
         ngx-bootstrap: 5.1.2
         @ionic/angular-toolkit: 5.0.3
         @nguniversal/builders: 13.1.1
         @ngxs/schematics: 0.0.1-alpha.5

Angular CLI version: 13.3.9

**Comment by AgentEnder** [comment]
Can you try using `nx serve` instead of `ng`?

**Comment by Coly010** [comment]
As this has been sitting for over a month, I'm going to close it.

If further information is provided, feel free to tag me in a new comment and we will readdress it.

Thank you!
