### ISSUE TITLE
how to run in docker? 

### ISSUE THREAD

**Issue by peter-coastpay-com** [nrwl/nx#13091]
is there a guide on how to get this to run in docker?  it looks like there are a ton of hidden / uninstalled dependencies when i try to install (python, make, gcc, ++g, more ? ) it there

**Comment by MichaelKaaden** [comment]
On my build server (Jenkins), I successfully use a "node:16-bullseye" or "node:18-bullseye" container image to build apps in an Nx monorepo.

Inside the running container, I just check out the repo, install the repo's packages, and then run the Nx commands using "npm run nx ..." or "yarn nx ...".

**Comment by dereekb** [comment]
You can check out my project and the docker configs here: https://github.com/dereekb/dbx-components

I just base off the node:16.18-bullseye image:
https://github.com/dereekb/dbx-components/blob/develop/Dockerfile

There is also CircleCI configuration here:
https://github.com/dereekb/dbx-components/blob/develop/.circleci/config.yml
