### ISSUE TITLE
Permission denied deleting nx/d/daemon.log (Windows)

### ISSUE THREAD

**Issue by Robert-Fish** [nrwl/nx#13094]
## Current Behavior
I'm trying to run rimraf on my workspace's node modules and i'm getting operation not permitted on open node_modules\.cache\nx\d\daemon.log

## Expected Behaviour
It should delete the file inside node_modules

## Steps to Reproduce
Run rimraf on a workspace that node_modules already installed on windows using powershell

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs
 >  NX   EPERM: operation not permitted, open 'C:\Users\myusername\Projects\workspace-names\node_modules\.cache\nx\d\daemon.log'

### Environment
I encounter this running rimraf on node_modules

**Comment by AgentEnder** [comment]
This is due to the daemon still being active... you can run `nx reset` to ensure it is shut down before attempting to delete the file.

**Comment by Yves-F-A** [comment]
Hello. I have the same issue with command npx nx reset in Visual Studio Code terminal.

**Comment by Robert-Fish** [comment]
Closed as i've been able to solve my issue
