### ISSUE TITLE
New components added with wrong path

### ISSUE THREAD

**Issue by nedzvedz** [nrwl/nx#131]
Running `ng generate component new-component --app=app-name` command generates component with path `/apps/app-name/src/apps/app-name/src/app/new-component/new-component.component.ts`.
Same for libs.

**Comment by Yonet** [comment]
I couldn't reproduce this. Can you give us a link. You can fork nx-examples repo to reproduce if you like: https://github.com/nrwl/nx-examples.

**Comment by nedzvedz** [comment]
I have this issue at newly created apps (global @angular/cli v1.5.5 & @nrwl/schematics v0.2.2).
Same for nx-examples app:
![image](https://user-images.githubusercontent.com/17314099/33502766-6abcc4e8-d6f2-11e7-8760-db108e1aa180.png)
https://github.com/nedzvedz/nx-examples/tree/repro/wrong-path-for-generated-comps/libs/school-ui/src here is the result.

It seems that when `@schematics/angular` creates new component at `addDeclarationToNgModule` function, it has passed `options` object with `sourceDir` and `path` properties which are the same (`/libs/school-ui/src` in this case).

**Comment by nedzvedz** [comment]
Sorry for the inconvenience, it was a known issue of the angular-cli on windows https://github.com/angular/angular-cli/issues/7960.
