### ISSUE TITLE
Ability to add directives and add directives/components/services to secondary entry points

### ISSUE THREAD

**Issue by sir-captainmorgan21** [nrwl/nx#13105]
## Description
This feature request is two fold:
- Ability to add directives: Right now there is only a `scam-directive` schematic available from @nrwl/angular. There is no way to create a non scam directive, and you cant make it standalone
- Ability to add directives/components/services to secondary entry points: Right now, there is no way to add these things to secondary entry point directories with defining the entire path. We have to add it to the root of the package and then move it down into the secondary entry point.

## Motivation
- Using nx's generators are awesome and a huge productivity boost. Just looking for more tools :) 

## Suggested Implementation
First one is straight forward, but not sure what to suggest for the second one since secondary entry points are unknown to NX atm once they are created.

## Alternate Implementations
Got nothing here

**Comment by Coly010** [comment]
The Angular CLI has a `directive` schematic, and it supports `--standalone` so you can use that:

`nx g @schematics/angular:directive myDirective --standalone`.

As for generating it under the secondary entry point, you should be able to do:

`nx g @schematics/angular:directive myDirective --standalone --project=my-lib --path=libs/my-lib/path-to-secondary-entry-point`

https://github.com/angular/angular-cli/blob/main/packages/schematics/angular/directive/schema.json#L63

**Comment by sir-captainmorgan21** [comment]
@Coly010

Right, though it is odd that there is a basic component and service generators through NX, but not a directive. Also we are required to add @angular/schematics, no?

For the second one, I know we are able to specify the entire path, and I mentioned that as the issue in the original post of the feature request. Mentioning the entire path is pretty tedious. An example path could be `packages/my-package/secondary/src/lib`. It would be nice to be able to mention the package name and then the secondary entry point. Its a feature request, like a nice to have. I would love to keep this open, at least for that.
