### ISSUE TITLE
--outputPath does not copy to output path if cash is used

### ISSUE THREAD

**Issue by ahmedhmf** [nrwl/nx#13104]
## Current Behavior
Building an app using --outputPath won't copy to the folder if it is using the cache. On the other hand, if we use the command with no --outputPath, then it copies it even if it is using the cache.

## Expected Behavior
I would expect it will have the same behavior both ways and copy the files if they are not available, even if cash is being used.

## Steps to Reproduce

**1. using --outputPath**

  A. I am using CLI to build my app with the following command 
    `npx nx build my-app --outputPath="C:\build\my-app"`
  B. it will build and copy the files correctly 
  C.  then I delete the folder C:\build\my-app 
  D. I rerun the command with no changes in my project -> nx will use cash to build it, then it won't copy the folder.
  E. I use the same command with --skip-nx-cache -> **_nx build, it and move it to the correct folder_**

2. without using --outputPath
  A. using CLI to build my app with the following command
       npx nx build my-app
  B.  it will build, and the files are available at dist\apps\my-app
  C. Delete this folder
  D. rerun the command -> **_it will use the build cache but in this case, it will also copy the missing files_**

**Comment by AgentEnder** [comment]
How is outputs defined in your target? My gut says that this is either a misconfiguration there or related to the specified output path being outside of the Nx monorepo.

**Comment by kanidjar** [comment]
Hello @AgentEnder, same issue here. When specifying --output-path in the command, the cached build is not published in the specified path, but it works when there is not cache hit.

`````
Node : 18.12.1
   OS   : darwin arm64
   pnpm : 7.18.1
   
   nx : 15.3.0
   @nrwl/angular : 15.3.0
   @nrwl/cypress : 15.3.0
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : Not Found
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.3.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @ngx-matomo/router: 4.0.1
   	 @ngx-matomo/tracker: 4.0.1
   	 ng2-charts: 3.1.2
```````

**Comment by xeinebiu** [comment]
Same issue here.

Steps to reproduce

1. Execute `npx nx build <project name here> --delete-output-path --output-path <...output path here>`
2. Go to output path and delete genereated files
3. Execute the same script  `npx nx build <project name here> --delete-output-path --output-path <...output path here>`
4. Build finishes from cache
5. Go to output path
6. No files are generated here

Workaround
Use `--skip-nx-cache`
