### ISSUE TITLE
addDepsToPackageJson from @nrwl/workspace fails to add the dependency provided to the function 

### ISSUE THREAD

**Issue by bleakcon** [nrwl/nx#13121]
## Current Behavior

I am using addDepsToPackageJson from "@nrwl/workspace" in a custom generator.

I add a dependency to the "dependencies" input and nothing for "devDependencies" input.

my default function looks like this:

```typescript
export default async function( tree: Tree, options: Schema){
  addDepsToPackageJson({"@some/dep" : "^1.0.0-alpha.111"}, {})
await applicationGenerator(tree, options);
}
```

The application is generated successfully but the package does not get added to the package json 

## Expected Behavior
The package JSON should be updated with the dependency

## Steps to Reproduce

* Create a plugin minimal
* Create a generator
* add the above code with the applicationGenerator coming from react
* run the generator

### Failure Logs
no fialure log

### Environment
Node 16
Amazon Linux

**Comment by AgentEnder** [comment]
Hey, sorry that util is for use in ng cli schematics and only really present for legacy reasons. We have plans to clean up this story a bit soon. You should use `addDependenciesToPackageJson` from `@nrwl/devkit` instead.
