### ISSUE TITLE
HMR not working - webpack custom config issue v15.4.2

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#13125]
## Current Behavior

After updating the project from v14x to v15x the HMR stopped working. Now, whenever I make a change in a react component, a whole screen gets reloaded.

## Expected Behavior

Yes, this is a regression. HMR used to work.

## Code 
```ts
"serve": {
      "executor": "@nrwl/webpack:dev-server",
      "options": {
        "buildTarget": "app:build:development",
        "port": 4203,
        "hmr": true,
        "liveReload": false
      },
      "configurations": {
        "qas": {
          "buildTarget": "app:build:qas",
          "hmr": false
        },
        "production": {
          "buildTarget": "app:build:production",
          "hmr": false
        }
      }
    },
```

### Failure Logs

The same behavior is with or without the Live Reloading option enabled.
```ts
[webpack-dev-server] Server started: Hot Module Replacement enabled, Live Reloading disabled, Progress disabled, Overlay enabled.
log.js:24 [HMR] Waiting for update signal from WDS...
```
And although the HMR reports that it is ready and waiting for updates, the whole screen reload still occurs.

### Environment

```ts
   Node : 16.14.0
   OS   : linux x64
   yarn : 3.3.1
   
   nx : 15.4.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.2
   @nrwl/js : 15.4.2
   @nrwl/linter : 15.4.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.2
   @nrwl/schematics : 8.12.11
   @nrwl/storybook : 15.4.2
   @nrwl/web : 15.4.2
   @nrwl/webpack : 15.4.2
   @nrwl/workspace : 15.4.2
   @nrwl/vite : 15.4.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

```

**Comment by nemonemi** [comment]
Hey guys, any progress on this?

**Comment by nemonemi** [comment]
It looks like I'm the only one experiencing this, even now on the latest v15.2.1.

**Comment by nemonemi** [comment]
@AgentEnder do you know if anyone else recognized this behavior, or am I the only one here?

**Comment by ndcunningham** [comment]
@nemonemi I created a new workspace, and this is not occurring for me.
Can you provide a sample repo with this issue?

**Comment by stolenng-carelon** [comment]
I had same issue also, tried to play with the versions but didn't help.
I disabled `hmr: false` in `project.json` and then added custom webpack with:
```
const { merge } = require('webpack-merge');
const nxConfig = require('@nrwl/react/plugins/webpack');
const ReactRefreshPlugin = require('@pmmmwh/react-refresh-webpack-plugin');

module.exports = (config, context) => {
  const isProduction = config.mode === 'production';


  if (!isProduction) {
    config.devServer = {
      ...config.devServer,
      hot: true,
    };

    config.plugins.push(new ReactRefreshPlugin());
  }


  return merge(config, nxConfig);
};

```

found this guide for reference: https://dev.to/rexebin/enable-hot-module-replacement-hmr-in-nrwl-nx-react-project-1hh5

**Comment by nemonemi** [comment]
I've actually used this solution before the NX implemented its support through the config, so for it to stop working, I would call it a regression.

@ndcunningham I'll make a reproducible sample as soon as I find time (asap).

**Comment by nemonemi** [comment]
It is still very active.

**Comment by nemonemi** [comment]
I have tried the custom Webpack configuration with the react-refresh, but the behavior remains unchanged.

**Comment by manimau01** [comment]
Same here. Started seeing this message after the Angular 14 -> Angular 15 update.
[webpack-dev-server] Server started: Hot Module Replacement disabled, Live Reloading enabled, Progress disabled, Overlay enabled.

**Comment by nemonemi** [comment]
I found out what causes the issue. 
If I use the default Webpack config "@nrwl/react/plugins/webpack" it works, however, if I extend it, then it stops working.

This should be enough to reproduce the error:
`project.json`
```ts
"webpackConfig": "apps/not-working/webpack.config.ts"
```

`apps/not-working/webpack.config.ts`
```ts
// this config has to be referenced inside the project.json for the build target
import { merge } from 'webpack-merge';

module.exports = (config: any) => {
  return merge(config, {
    module: {
      rules: [
        {
          test: /\.pdf$/i,
          use: ['file-loader'],
        },
      ],
    },
  });
};
```

**Comment by nemonemi** [comment]
Any idea? @ndcunningham

**Comment by nemonemi** [comment]
Even updating to the v15.4.2 hasn't helped.

**Comment by nemonemi** [comment]
After updating to 15.6.2, nothing improved.

NX report:
   Node : 16.14.0
   OS   : linux x64
   yarn : 3.3.1
   
   nx : 15.6.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.6.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.2
   @nrwl/js : 15.6.2
   @nrwl/linter : 15.6.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.6.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.6.2
   @nrwl/schematics : 8.12.11
   @nrwl/storybook : 15.6.2
   @nrwl/web : 15.6.2
   @nrwl/webpack : 15.6.2
   @nrwl/workspace : 15.6.2
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

**Comment by nemonemi** [comment]
If I remove the custom file-loader webpack config extension, then the HMR works as expected, however, I need the loader.
Please fix this regression bug.

**Comment by nemonemi** [comment]
I assume this ticket got lost in the backlog. Could we see some progress here, please?
It's a regression bug, and the ticket contains all the needed information.
@vsavkin , @FrozenPandaz, @bcabanes, @jaysoo, @meeroslav ...

**Comment by jaysoo** [comment]
@nemonemi The problem is that our executors are not adding React Refresh by default, since not all webpack projects are React ones.

If you use our `@nrwl/react/plugins/webpack` (Nx 15.4) and call it in your webpack config file then it'll work.

e.g.
```
// this config has to be referenced inside the project.json for the build target
import { merge } from 'webpack-merge';

module.exports = (config: any) => {
  const withReact = require('@nrwl/react/plugins/webpack');
  return withReact(merge(config, {
    module: {
      rules: [
        {
          test: /\.pdf$/i,
          use: ['file-loader'],
        },
      ],
    },
  }));
};
```

We've also (in 15.5) updated our config setup so it is easier to customize.

```
import { composePlugins, withNx } from '@nrwl/webpack';
import { withReact } from '@nrwl/react';
import { merge } from 'webpack-merge';

module.exports = composePlugins(withNx(), withReact(), (config) => {
return merge(config, {
    module: {
      rules: [
        {
          test: /\.pdf$/i,
          use: ['file-loader'],
        },
      ],
    },
  });
});
```

The updated configuration guide is here: https://nx.dev/packages/webpack/documents/webpack-config-setup#configure-webpack-on-your-nx-workspace

Let me know if you have any more issues.

**Comment by nemonemi** [comment]
That did the trick!
Thanks for letting me know, @jaysoo .
