### ISSUE TITLE
"Skipping project found at"

### ISSUE THREAD

**Issue by LavaToaster** [nrwl/nx#13126]
## Current Behavior

When running commands NX CLI is complaining about multiple projects being named the same thing.

## Expected Behavior

Ideally, it should know these are unique projects and not complain. I haven't seen any problems in the day-to-day running.

## Steps to Reproduce

Setup a project structured in the following way

apps/grouping1/mfe
apps/grouping1/service
apps/grouping2/mfe
apps/grouping2/service

Ensure each app has it's own project.json in the folder, in standaloneConfig mode.

Tie it all up in the workspace.json which contains the actual name. so grouping1-me, grouping1-service, grouping2-mfe, grouping2-service. 

This is where I'm getting confused about it seeing the same project, since they're independently registered in the workspace.json

### Failure Logs

```
Skipping project found at apps/grouping1/mfe since project mfe already exists at apps/grouping2/mfe! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at apps/grouping1/service since project service already exists at apps/grouping2/service! 
```

### Environment

```
 Node : 16.15.0
   OS   : darwin arm64
   yarn : 3.2.0
   
   nx : 15.0.11
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.11
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.11
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.11
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.11
   @nrwl/js : 15.0.11
   @nrwl/linter : 15.0.11
   @nrwl/nest : 15.0.11
   @nrwl/next : Not Found
   @nrwl/node : 15.0.11
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 15.0.11
   @nrwl/react : 15.0.11
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.11
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.11
   @nrwl/web : 15.0.11
   @nrwl/webpack : 15.0.11
   @nrwl/workspace : 15.0.11
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nx-tools/nx-docker: 2.3.0
```

**Comment by AgentEnder** [comment]
Hey @LavaToaster, you should add a `name` field to these projects. To support some complex workspace layouts, we now glob for the project files even in the presence of `workspace.json`. As such, the correct move is likely to remove your workspace.json and inline the names in each project file.

**Comment by AgentEnder** [comment]
There is a migration in v15.0.12 that should address this as well.

**Comment by LavaToaster** [comment]
Ah, fantastic. Should have checked the release notes before submitting the issue, I only did the migration from NX 14 to NX 15 this week 😅.
