### ISSUE TITLE
Compile errors in custom workspace-generator while using @nrwl/workspace generators

### ISSUE THREAD

**Issue by DirkoOdendaal** [nrwl/nx#13127]
## Current Behavior

While creating a custom workspace generator to rename some of our projects, we make use of the moveGenerator.
`import { moveGenerator } from '@nrwl/workspace/generators';`
When running this generator we get some Typescriptm compile errors:
``` TS
node_modules/@nrwl/workspace/src/generators/library/schema.d.ts:2:1 - error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.

2 const { Linter } = require('@nrwl/linter');
  ~~~~~

node_modules/@nrwl/workspace/src/generators/library/schema.d.ts:2:20 - error TS1254: A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference.

2 const { Linter } = require('@nrwl/linter');
                     ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@nrwl/workspace/src/generators/library/schema.d.ts:12:12 - error TS2749: 'Linter' refers to a value, but is being used as a type here. Did you mean 'typeof Linter'?

12   linter?: Linter;
              ~~~~~~


Found 3 errors in the same file, starting at: node_modules/@nrwl/workspace/src/generators/library/schema.d.ts:2
```

## Expected Behavior

We expect the code to compile fine without any TS errors.

## Steps to Reproduce

- Create new generator
- Add `import { moveGenerator } from '@nrwl/workspace/generators'`;
- Call generator for a project:
``` TS
await moveGenerator(tree, {
      projectName: 'project-original',
      destination: 'project-destination',
      updateImportPath: true
});
```
- Execute the new generator

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

See error log in current behaviour.

### Environment

Node : 18.12.0
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 15.0.13
   @nrwl/angular : 15.0.13
   @nrwl/cypress : 15.0.13
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.13
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.13
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.13
   @nrwl/js : 15.0.13
   @nrwl/linter : 15.0.13
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.0.13
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.13
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.13
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.13
   @nrwl/web : 15.0.13
   @nrwl/webpack : 15.0.13
   @nrwl/workspace : 15.0.13
   typescript : 4.8.4

**Comment by AgentEnder** [comment]
This should be fixed in Nx 16, since workspace-generator's don't exist any more.
