### ISSUE TITLE
graph resets zoom level (or UI state in general) after couple seconds

### ISSUE THREAD

**Issue by alexciesielski** [nrwl/nx#13145]
## Current Behavior

I am starting to use the graph more and more for dependency analysis, it is a really amazing tool.

Unfortunately, when zooming in into a quite large dependency graph the zoom level gets reset after a couple of seconds. This happens continuously. On top of that this also happens for when I hover over a project to highlight it - after a couple seconds the highlighting is gone.

## Expected Behavior
Once zoomed in I would want the graph to stay that way (or any other UI state for that matter).

## Steps to Reproduce
1. Open graph
2. Focus on any project
3. Zoom in
4. Observe that the zoom level is reset after a couple of seconds

### Environment

```
   Node : 16.13.2
   OS   : darwin arm64
   npm  : 8.16.0

   nx : 15.0.13
   @nrwl/angular : 15.0.13
   @nrwl/cypress : 15.0.13
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.13
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.13
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.13
   @nrwl/js : 15.0.13
   @nrwl/linter : 15.0.13
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.13
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.13
   @nrwl/web : 15.0.13
   @nrwl/webpack : 15.0.13
   @nrwl/workspace : 15.0.13
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @datorama/akita: 7.1.1
   	 @fortawesome/angular-fontawesome: 0.11.1
   	 @ngneat/hot-toast: 4.1.0
   	 @ngneat/tailwind: 7.0.3
   	 @storybook/angular: 7.0.0-alpha.33
   	 ng-mocks: 14.0.1
   	 nx-stylelint: 13.5.3
```

**Comment by juristr** [comment]
@alexciesielski did you launch the graph in `--watch` mode?

**Comment by alexciesielski** [comment]
Yes I did

**Comment by isaacplmann** [comment]
Clarifying for anyone who finds this, this bug still exists, but only with the `--watch` flag.  If you omit that flag, the zoom level does not reset.
