### ISSUE TITLE
Modifying files with a generator documentation appears to be wrong

### ISSUE THREAD

**Issue by bleakcon** [nrwl/nx#13140]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/recipes/generators/modifying-files

### Additional context or description

String replace code example appears to be wrong:

``` tree.read``` returns a ```Buffer``` not a string as the documentation seems to suggest?

```toString` will help you but even then ```.replace` on ```string``` does not mutate the original ```string```

I would think it would need to be something like:

```
export default async function (tree: Tree, schema: any) {
  const filePath = `path/to/index.ts`;
  let contents = tree.read(filePath).toString();
  contents = contents.replace(/thomasEdison/g, 'nikolaTesla');
  tree.write(filePath, contents);
}
```

**Comment by AgentEnder** [comment]
Hey! It looks like that code block does need an update. Do you want to open a PR?

**Comment by bleakcon** [comment]
I can do so, give me a few days

**Comment by rubiagatra** [comment]
I create the PR please check @bleakcon and @AgentEnder #13757
