### ISSUE TITLE
Documentation on setting up tests for generators

### ISSUE THREAD

**Issue by bleakcon** [nrwl/nx#13147]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

I could not find a documentation page for testing generators, so I went [here](https://github.com/nrwl/nx/blob/master/packages/react/src/generators/application/application.spec.ts).

It might be useful to add some documentation on the testing methods available for generators, some examples would be helpful.

I am currently working through testing my own generator and am learning as we speak, so perhaps I could eventually put something together but for now wondered if anyone has anything hiding away?

## Why specifically would I like documentation?

As part of my generator, I have imported ```applicationGenerator``` from the 'react' package into my generator.

When I do this, I get an error, documentation would help me understand whether this is something to do with my configuration or something to do with nx which I should raise a ticket for

```
  Cannot find module './src/executors/dev-server/schema' from '../../node_modules/@nrwl/webpack/index.js'
```

**Comment by isaacplmann** [comment]
This section has some documentation on testing plugins and generators.  Please open another issue if there are specific things you would like to be documented.
https://nx.dev/packages/nx-plugin#testing-your-plugin
