### ISSUE TITLE
First class support for Cypress Component Testing

### ISSUE THREAD

**Issue by lmiller1990** [nrwl/nx#13148]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

Happy to help out, I don't know a whole lot about Angular or Nx, but I'd like to learn. I can also help with Cypress-specific questions or required patches in the Cypress repo.

## Description
Nx has support for Cypress E2E out of the box. Cypress Component Testing is no longer beta as of Cypress 11, so I wonder if we can have support for that, too? https://www.cypress.io/blog/2022/11/08/announcing-cypress-11/

## Motivation

I tried to add Component Testing to my project manually, but I'm running into all kinds of problems. I think it's due to conflicting assumptions both Nx and Cypress make about project structure. Here's my attempt to get it working: https://github.com/cypress-io/cypress/discussions/24400#discussioncomment-4131029

## Suggested Implementation
Same as E2E, I suppose - I'm not very familiar with the Nx way, but we should just make it work like other Nx plugins/presets.

Related issue in Cypress: https://github.com/cypress-io/cypress/issues/24666 we can add some configuration options if needed, for example adding an `angularJson` property to `cypress.config` under `component` if that would be useful.

## Alternate Implementations
I was able to get it working by creating my own `angular.json`, but I have feeling I'm duplicating the original Angular app's `angular.json` which is probably buried in the `node_modules/@nx` somewhere. My repo: https://github.com/lmiller1990/angular-nx-cypress

**Comment by barbados-clemens** [comment]
Nx already has first class support for angular and react component testing and the cypress v11 support PR has been merged and will be in the next minor release of Nx. 

Angular:https://nx.dev/packages/angular/generators/cypress-component-configuration
React: https://nx.dev/packages/react/generators/cypress-component-configuration
PR for cypress v11: #13075

**Comment by lmiller1990** [comment]
Great, thanks. I look forward to using it!
