### ISSUE TITLE
Issues when using middleware with custom express server

### ISSUE THREAD

**Issue by binitgutka** [nrwl/nx#13150]
While using the middleware functionality with my custom express server in a NX workspace I am facing this issue
![image](https://user-images.githubusercontent.com/17779861/201655208-56b88852-fcda-4a3e-96fa-2231437777f6.png)

Please let me know if any more info is needed 
Here is the nx report
![image](https://user-images.githubusercontent.com/17779861/201657045-d8251d3e-f9d9-476d-8cbd-e71768b556d8.png)

**Comment by AgentEnder** [comment]
Can you post a reproduction for this issue? At a glance, this sounds like the issue is happening outside of Nx (e.g. with built files), so it shouldn't be Nx specific. 

If there is something in the repro that makes it clear that it is on Nx's side of things, it would need to be seen.

**Comment by binitgutka** [comment]
@AgentEnder 
I am using the NX workspace I have created a custom node server, which in turn has a custom express server, which serves the app.
When I am trying to add the middleware file at the app root level I am getting the above error.

Let me know if you want me to share a specific part of code from project.json or any other file..
