### ISSUE TITLE
Jest unable to find module

### ISSUE THREAD

**Issue by LechoDecho** [nrwl/nx#13165]
## Current Behavior

When running a test case of a component containing another module from the monorepository the test case will fail with following error message: 

● Test suite failed to run
    Cannot find module '@workspace-name/app-name/services/api'

Same Error occurs when using a non npm scope import but still absolute. 
The absolute path looks like follows : "libs/app-name/service/api/src/index

Relative paths however are working. 
## Expected Behavior

Absolute paths should also be accepted by Jest

### Environment

Angular 14.0.2 
NX 14.5.10
Jest 28.0.0

**Comment by LechoDecho** [comment]
Not yet sadly

**Comment by barbados-clemens** [comment]
do you have a reproducible @LechoDecho or @KunalBurangi?

it _probably_ is something to do with the nx jest resolver not running which is apart of the `nxPreset` that should be imported in the root level jest.preset.js.

**Comment by LechoDecho** [comment]
I'm not able to provide reproducible code, unfortunately. But this is what my jest.preset.js looks like: 

const nxPreset = require('@nrwl/jest/preset');

module.exports = { ...nxPreset };

**Comment by barbados-clemens** [comment]
change it to 
```js
const nxPreset = require('@nrwl/jest/preset').default // Notes the .default;

module.exports = { ...nxPreset };
```
