### ISSUE TITLE
Cannot produce verbose @nrwl/next:build logs

### ISSUE THREAD

**Issue by robertn702** [nrwl/nx#13164]
## Current Behavior
Adding `--verbose` and / or `NX_VERBOSE_LOGGING=true` do not produce additional logs when running the `@nrwl/next:build` executor.

Example commands
`$ nx run --verbose {app}:build:development` 
`$ NX_VERBOSE_LOGGING=true nx run --verbose {app}:build:development` 

## Expected Behavior
Adding `--verbose` or `NX_VERBOSE_LOGGING=true` to the `build` command in Next applications should display all logs from that command.

## Steps to Reproduce
Create next app using `nrwl/next` generator and build using default target settings
```json
{
  "targets": {
    "build": {
      "executor": "@nrwl/next:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "root": "apps/webapp",
        "outputPath": "dist/apps/webapp"
      },
      "configurations": {
        "development": {
          "outputPath": "apps/webapp"
        },
        "production": {}
      }
    }
  }
}
```

### Environment

```
   nx : 15.0.13
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.13
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.13
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.13
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.13
   @nrwl/js : 15.0.13
   @nrwl/linter : 15.0.13
   @nrwl/nest : Not Found
   @nrwl/next : 15.0.13
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.13
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.13
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.13
   @nrwl/web : 15.0.13
   @nrwl/webpack : 15.0.13
   @nrwl/workspace : 15.0.13
   typescript : 4.8.4
```

**Comment by elucidsoft** [comment]
This is broken in 13.10.6 as well...

**Comment by davidfloegel** [comment]
Can someone confirm whether this is still an issue? We're currently trying to get additional logging on our builds on Vercel but neither flag is doing anything.

**Comment by jason-stoudt** [comment]
Just came across this because I'm having same issue.

**Comment by ndcunningham** [comment]
What additional logs were you looking for?

**Comment by robertn702** [comment]
@ndcunningham I would like to have an option to pass the [`--debug` flag to `next build`](https://nextjs.org/docs/api-reference/cli#build). This could either be automatically applied if `NX_VERBOSE_LOGGING=true` or `--verbose` is provided to `@nrwl/next:build` or explicitly via task options as shown below:

```json
{
  "build": {
      "executor": "@nrwl/next:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "root": "apps/webapp",
        "outputPath": "dist/apps/webapp",
        "debug": true // <-- maybe add this option
      },
  }
}
```

Is there already a way to achieve this?

**Comment by ndcunningham** [comment]
That should be fine to add  `--debug` will be propagated to `next.js` `build`
