### ISSUE TITLE
Getting a 404 on this link

### ISSUE THREAD

**Issue by oimediaDev** [nrwl/nx#13181]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.
https://nx.dev/recipes/generators
### Additional context or description
These generator pages seem to be missing
Provide any additional details here as needed.

**Comment by AgentEnder** [comment]
I can't replicate this. Is there a certain link giving you issues?

**Comment by deepa** [comment]
All of the links in the pages https://nx.dev/recipes/generators and https://nx.dev/recipes/executors return 404.

I created another issue before seeing this issue https://github.com/nrwl/nx/issues/13213 with a couple of examples. Please feel free to merge these two.

**Comment by AbdealiLoKo** [comment]
https://github.com/nrwl/nx/issues/13183 is another similar issue which I had created

**Comment by AgentEnder** [comment]
Yes, I can replicate this this morning.

**Comment by isaacplmann** [comment]
This was fixed by #13210
