### ISSUE TITLE
VS Code cannot find @nrwl/nx/workspace custom eslint rules without Nx Console extension installed

### ISSUE THREAD

**Issue by zjkipping** [nrwl/nx#13187]
## Current Behavior
VS Code shows error `Definition for rule '@nrwl/nx/workspace/my-custom-rule' was not found.eslint(@nrwl/nx/workspace/my-custom-rule)` when Nx Console extension isn't installed on the VS Code editor. This occurs when looking at a file the custom rule is applied to from the `.eslintrc.json`.

## Expected Behavior
I would expect there to be an easy way to configure this if the Nx Console extension is the thing orchestrating the wiring of the custom workspace rules to the VS Code ESLint extension (or however it works). 

Or just for this to work regardless of Nx Console being installed. Some of us in the community don't bother with it since we only really use the terminal CLI. It also isn't obvious that the reason the lookup of the rule fails is because of Nx Console extension not being installed.

## Steps to Reproduce

I created a fresh nx15 workspace with a custom workspace linting rule generated. The README explains how to reproduce the error.
https://github.com/zjkipping/nx-custom-workspace-eslint-rules

The gist of the repo is that without the Nx Console extension installed you get an error in VS Code while the eslint extension tries to lookup the custom workspace rule. If you install the Nx Console extension and restart the ESLint Server you won't get the error anymore.

### Environment

   Node : 18.12.0
   OS   : win32 x64
   npm  : 8.19.2

   nx : 15.1.0
   @nrwl/angular : 15.1.0
   @nrwl/cypress : 15.1.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.1.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.1.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.1.0
   @nrwl/js : 15.1.0
   @nrwl/linter : 15.1.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.1.0
   @nrwl/web : Not Found
   @nrwl/webpack : 15.1.0
   @nrwl/workspace : 15.1.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

**Comment by zjkipping** [comment]
As a side note, I tried making use of the eslint options `rulePaths` in the VS Code `.vscode/settings.json` file following this [stackoverflow](https://stackoverflow.com/questions/68089992/how-can-i-add-eslint-custom-rules-directory-to-vscode) without much luck.

**Comment by zjkipping** [comment]
@AgentEnder @meeroslav Any updates with this? Has it been picked up at all?

**Comment by meeroslav** [comment]
Unfortunately, I could not reproduce it.

Here is the scenario I tried (each try was with ESLint server restart + full VS Code reload):
- Running with Nx Console -> PASS
- Running with Nx Console Disabled -> PASS
- Running with Nx Console Uninstalled -> PASS

This was on Mac. I will give it another go on Windows

**Comment by meeroslav** [comment]
Same results on Windows. It's (or was) likely an issue with your installation of packages or VS Code. Try following:
- `npx nx reset` (resets potentially stuck daemon process)
- remove `node_modules` and reinstall all packages with `npm ci`

**Comment by zjkipping** [comment]
I will try this, but it doesn't make too much sense given I was able to reproduce in a separate repo with different machines. On my actual work project this is affecting all the developers (30+).

**Comment by meeroslav** [comment]
Ok, I'll ask my colleagues working on Nx Console to investigate this further as I didn't manage to reproduce it.

**Comment by meeroslav** [comment]
@zjkipping Are all your colleagues using Windows machines and similar versions of Node/Npm?

**Comment by zjkipping** [comment]
@meeroslav Yes on the node versions, most folks are on Windows machines & a few on Mac. We are either on LTS or slightly below on the node Versions.

**Comment by meeroslav** [comment]
As you can see, the Nx Console is not installed and there are no link errors in `app.component.ts`. My node version is 18.12.1 but I tried also with v16 and there were no differences.

![Screenshot 2022-12-09 at 14 07 44](https://user-images.githubusercontent.com/881612/206709324-f4fc9c5a-8d6e-430b-9700-7214f93fa788.png)

**Comment by zjkipping** [comment]
I will try using a clean vs-code instance Monday! Thanks for going through this so much @meeroslav, it's appreciated.

**Comment by zjkipping** [comment]
Having disabled and then re-enabled all my extensions it looks like I can't reproduce this anymore... I guess something went haywire with the eslint extension in tangent with another extension (or possibly not). Either way I'll close this issue. thanks for the help @meeroslav!

**Comment by Hypenate** [comment]
We're having the same issue with Webstorm.
Not using the official plugins from NX, but the community ones.

**Comment by meeroslav** [comment]
@Hypenate 

Unfortunately, we can't help you out with the community plugin-related issues. You would have to contact the original authors. Assuming you are referring to https://plugins.jetbrains.com/plugin/15000-nx-console-ui please contact @etkachev

That being said, there is now also an official IntelliJ plugin for Nx so you might try to see if the same issue appears there as well: https://plugins.jetbrains.com/plugin/21060-nx-console

**Comment by GrumpyMeow** [comment]
@meeroslav I've just upgraded my NX-workspace from v15.0.13 to v15.8.9 and also get errors on my CI-pipeline about that my custom eslint-rules are not found.
```
/__w/1/s/libs/shared/core-lib/src/lib/whitelabel/components/message/message.component.spec.ts(9,1): error @nrwl/nx/workspace/validate-component-template : Definition for rule '@nrwl/nx/workspace/validate-component-template' was not found.
/__w/1/s/libs/shared/core-lib/src/lib/whitelabel/components/message/message.component.ts(1,1): error @nrwl/nx/workspace/validate-core-lib-refs : Definition for rule '@nrwl/nx/workspace/validate-core-lib-refs' was not found.
```
* Can it be related to the "angular.json" being deleted as part of the migration?
* Can it be related to running NX in a DevContainer (via VSCode, so Windows>WSL2>DevContainer) ?
* Can it be related to Node v16.14.x upgrade to v18.14.1 ?
