### ISSUE TITLE
@nrwl/vite does not contain executors or generators

### ISSUE THREAD

**Issue by simonnepomuk** [nrwl/nx#13197]
## Current Behavior

When installing `@nrwl/vite`  through `npm i -D @nrwl/vite` it installs `15.0.13` which has an empty `executors.json` and empty `generators.json` 

## Expected Behavior
I saw in the repo that executors and generators have been added to the package and merged into main. These changes should probably be published to the @nrwl/vite package

**Comment by nodegin** [comment]
Same here, migrating from nxext
In the official doc it says "The planned release date for the stable plugin is December, 2022."
Is that mean we have to wait until Dec? No alpha version to use atm?

**Comment by simonnepomuk** [comment]
Was just informed via Slack that `15.2.0` should include the new package. `@nxext/vite` should provide smooth migrations to the official bundler once it is released.
