### ISSUE TITLE
React client components don't work in Nx shared library. ('use client') Nextjs 13

### ISSUE THREAD

**Issue by TheodorTomas** [nrwl/nx#13194]
## Current Behavior
When trying to use a client component exported in a shared React component library within a Nextjs 13 app using the new NextJS `app` directory, Nx strips `'use client';` from the component resulting in the following error provided below.

## Expected Behavior
Nx should recognize the `'use client';` syntax so that the component doesn't mount on the server but is instead recognized as a client component.

## Steps to Reproduce
1. Create a Nextjs app using the Nx generator.
2. Enable the `app` directory by adding `experimental: { appDir: true },` to `next.config.js`.
3. Create a React shared library using the Nx generator.
4. Add `const [test, setTest] = useState('test');` to the auto generated component in the React lib.
5. Add `'use client';` to the top of the component.
6. Import the React component within the Nextjs app.
7. Run `yarn start`.
8. Notice the error message stating that `'use client';` is required to use client components.

### Failure Logs

```You're importing a component that imports client-only. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.```

### Environment

 NX   Report complete - copy this into the issue template

   Node : 18.11.0
   OS   : darwin x64
   yarn : 1.22.19
   
   nx : 15.0.13
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.13
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.13
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.13
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.13
   @nrwl/js : 15.0.13
   @nrwl/linter : 15.0.13
   @nrwl/nest : Not Found
   @nrwl/next : 15.0.13
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.13
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.13
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.13
   @nrwl/web : 15.0.13
   @nrwl/webpack : 15.0.13
   @nrwl/workspace : 15.0.13
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

**Comment by NachoVazquez** [comment]
I'm having the same issue.

**Comment by yuvalotem1** [comment]
also for me

**Comment by TheodorTomas** [comment]
There is one workaround to this bug.
1. Create a client component within your NextJS 13 app using the `'use client';` syntax.
2. Export your shared component from this new client component.
3. Use this new component solely within your app.

**note if you are `export * from './lib'` within your shared library you will need to make it so the client components are not exported any more from your library.

**Comment by anvelicon** [comment]
I am having the exact same issue.

I think, having to create a client component file in the app directory is not a sustainable solution; especially if the application consists of many components.

**Comment by TheodorTomas** [comment]
> I am having the exact same issue.
> 
> I think, having to create a client component file in the app directory is not a sustainable solution; especially if the application consists of many components.

Yeah, I gave up on using the new app directory because I started getting the opposite issue with server components which was just causing too much of a headache. I think this actually might just be a Nextjs 13 issue. As you can see [here](https://beta.nextjs.org/docs/app-directory-roadmap#supported-and-planned-features) shared components are still a work in progress.

**Comment by Brian-McBride** [comment]
> make the library tree shakeable

I thought all React component libs in Nx were tree shakable. Unless I've missed something huge anyway. It seems it is more about not stripping out `"use client";`

**Comment by atanaskanchev** [comment]
> We have the very same problem, if someone is looking for "workaround" we have decided to have a file in `app` root (`app/sharedClientComponents.ts`), which reexports any "client components" that would otherwise fail, the refactor wont be hard once we come up with proper solution. :-)
> 
> ```ts
> "use client";
> 
> import AddToCartButton from "@store/AddToCartButton";
> import Cart from "@store/Cart";
> import Input from "@store/Input";
> 
> export { AddToCartButton, Cart, Input };
> ```

Unfortunately this workaround didn't work for me with `"next": "^13.0.7-canary.3",`
```   Node : 16.18.1
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 15.3.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.3.0
   @nrwl/detox : 15.3.0
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.0
   @nrwl/expo : 15.3.0
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : 15.3.0
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.3.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.3.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.3.0
   @nrwl/webpack : 15.3.0
   @nrwl/workspace : 15.3.0
   typescript : 4.9.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nrwl/vite: 15.3.0`

**Comment by hakobpogh** [comment]
> We have the very same problem, if someone is looking for "workaround" we have decided to have a file in `app` root (`app/sharedClientComponents.ts`), which reexports any "client components" that would otherwise fail, the refactor wont be hard once we come up with proper solution. :-)
> 
> ```ts
> "use client";
> 
> import AddToCartButton from "@store/AddToCartButton";
> import Cart from "@store/Cart";
> import Input from "@store/Input";
> 
> export { AddToCartButton, Cart, Input };
> ```

This workaround worked for me. But I think this is a big issue. And it needs a fix.

**Comment by hugobb** [comment]
The workaround is working if you only use the client component in the `app` folder.
But I would like to be able to define a shared library of server component that my used client component from another shared library.
Any idea how this could be done ?

**Comment by jamiter** [comment]
I'm hoping for a way to tell Babel to leave the comment alone. Has anybody been able to do that?

**Comment by mrjomp** [comment]
@TheodorTomas how were you able to add `appDir`?

The type `WithNxOptions` only includes `nx` which is very "restrictive". Do we need to open a new issue to update `WithNxOptions` type  which is passed as a parameter of `withNx`  to  include `experimental` as well?

Right now by default I'm getting this error.

```
Type '{ nx: { svgr: false; }; experimental: { appDir: boolean; }; }' is not assignable to type 'WithNxOptions'.
```

**Comment by ndcunningham** [comment]
> @TheodorTomas how were you able to add `appDir`?
> 
> The type `WithNxOptions` only includes `nx` which is very "restrictive". Do we need to open a new issue to update `WithNxOptions` type which is passed as a parameter of `withNx` to include `experimental` as well?
> 
> Right now by default I'm getting this error.
> 
> ```
> Type '{ nx: { svgr: false; }; experimental: { appDir: boolean; }; }' is not assignable to type 'WithNxOptions'.
> ```

I am not sure which version of Nx you are on but `WithNxOptions` extends `NextConfig` which should allow you to add that experimental property. https://github.com/nrwl/nx/blob/master/packages/next/plugins/with-nx.ts#L3 

@TheodorTomas thanks for reporting the issue, can you create a small repo so I can accurately look into this?

**Comment by dankins** [comment]
@ndcunningham I took a stab at a small repo to reproduce the issue. I am actually seeing different behavior than my main app - I can't get any client components to load, but in my main app Client Components work fine when they are in the app, or from shared libraries that are re-exported with "use client" in the app.

Happy to help in any way with this - it is causing us a lot of pain since we have two apps in the same monorepo that need to share components. 
https://github.com/dankins/nx-nextjs-13194

![image](https://user-images.githubusercontent.com/61657/224434343-583c8a89-7da9-4477-ba01-586eca3b1540.png)

**Comment by FrozenPandaz** [comment]
This should work with https://github.com/nrwl/nx/pull/15650

**Comment by dankins** [comment]
Thanks for this! I migrated to 15.9.0-beta.2 in my minimal example and can confirm that things work as expected 🎉 
![image](https://user-images.githubusercontent.com/61657/225469193-53b7c3d5-487e-4085-a5bc-24c495d5f75a.png)
