### ISSUE TITLE
Docs for Migrating off of workspace.json? - 14.3.5->15.1.0

### ISSUE THREAD

**Issue by fbartho** [nrwl/nx#13191]
### Documentation issue

- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/deprecated/workspace-json#removing-workspace.json

### Additional context or description

We've had a stuck dependabot PR trying to upgrade us from NX 14 to 15 for a while now. Finally went in to understand what was going on, and some of the migrations were partially failing (specifically 2 migrations from beta.0 versions around our jest configs).

Skipping those two failures manually produced a *ton* of changes in our monorepo, and specifically, they don't appear to be fully complete.

The main changes appear to be taking the `architect` fields from workspace.json, and copying most of their data into a new `nx` node in each project's package.json.

The problem is that workspace.json still exists, and I don't know what's supposed to be in there. I assume we're not supposed keep the targets/commands in *both* places.

Am I supposed to delete workspace.json? or what's supposed to remain in there?

Please advise, & thanks in advance!

**Comment by DaSchTour** [comment]
I think it would be very useful to have some information about when this was deprecated, which version introduced this change. Because with the given documentation I'm not confident to remove `workspace.json` as I'm not sure which version I need to be able to do it.

**Comment by zjkipping** [comment]
Looks like you probably missed the migration to "per project config" during Nx v12.5: https://blog.nrwl.io/per-project-configuration-storybook-support-for-angular-12-auto-refresh-for-dependency-graph-and-bcd2d1e06658

In my project we just ran `nx g @nrwl/workspace:convert-to-nx-project --all` to migrate to this project.json setup. Once that is done you should be fine to upgrade to Nx v15 (?) and delete the workspace.json after the migrations/upgrades (if it wasn't removed).

**Comment by isaacplmann** [comment]
Here's a guide documenting the `convert-to-nx-project` process:
https://nx.dev/deprecated/workspace-json
