### ISSUE TITLE
node_module paths in angular-cli.json should be updated when migrating an existing project

### ISSUE THREAD

**Issue by mrmeku** [nrwl/nx#132]
When migrating an existing project to an nx workspace I had to manually change many paths to node_module paths for the app that was created. It mostly involved adding ../../ to the existing paths since the old ./src directory now resided within ./apps/APP_NAME/src. I think fixing this issue should be as simple as doing a depth first search through each key of the created app within angular-cli.json. If that key begins with '[./]*node_modules/' then we should add the prefix '../../' to that key

**Comment by FrozenPandaz** [comment]
This should be handled by the Angular 6 migration as those paths, ideally are updated.
