### ISSUE TITLE
Allowing one-level deep library importing (nx-enforce-module-boundaries)

### ISSUE THREAD

**Issue by abierbaum** [nrwl/nx#1320]
## Expected Behavior

The nx-enforce-module-boundaries tslint rule enforces good behavior for importing.  This is great, but we have libraries where we want to prevent deep imports but allow first level imports.  So for example:

```
import {xxx} from '@my_org/my_lib/area1';
import {xxx} from '@my_org/my_lib/area2';
```

## Current Behavior

Currently all the symbols have to be exposed through the index.js barrel for @my_org/my_lib.

## Discussion

Is this something that would be of interest to others in the community and from nrwl?  

If it is, I would be willing to put up a PR if someone can point me to any guide about how to do development on nx itself and extend any tests.  (I am comfortable with the tslint side of it, just want to make sure I follow / extend any conventions for nx development)

**Comment by matheo** [comment]
I'm currently adding this to my tsconfig paths, per library:
```
  "@myproject/api/*": ["libs/api/src/lib/*"],
```
and then allowing the specific subfolder in the tslint:
```
"nx-enforce-module-boundaries": [
      true,
      {
        "allow": [
          "@sudshare/api/auth",
          "@sudshare/api/operators",
```

**Comment by FrozenPandaz** [comment]
This was added with #1897.

See https://nx.dev/angular/guides/monorepo-tags#exceptions for more information!

**Comment by tmtron** [comment]
@matheo: but when you use `allow`, then the tag-constraint checking will also not work for those paths, right?  i.e. then we can use those classes in all libs/apps, no matter what tags (scopes) they have
