### ISSUE TITLE
Nx mfe angular - 30+ applications

### ISSUE THREAD

**Issue by todorpavlovic** [nrwl/nx#13200]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Current behavior `npx nx serve shell --devRemotes=name-of-app` will build and serve all applications. When projects are started it takes too much time to build project at first start, and also 30 opened servers can slow down development.
 

## Motivation
Faster development in large enterprise applications.

## Suggested Implementation
Build and serve only what is specified in --devRemotes and as a host app, inside the shell application don't check for other apps that are specified in app-routings.module.ts so the application won't stop working.

**Comment by Coly010** [comment]
This isn't really possible.

we can't control the routing within angular. That is your code + logic and we can't alter that at serve time to simply ignore some routes.

As you're probably aware, not serving some of the remotes will cause the angular host application to fail. 


If you want to serve only 1 remote, you can always just serve that remote without serving the host. 

You can set up your `app.module.ts` to route to the `RemoteEntryModule` as the default route. 

If you need any app_initializer config from your host app, you can copy it into your app.module.ts for your remote.
