### ISSUE TITLE
docs(angular-generators): `cypress-component-project` used instead of `cypress-component-configuration` 

### ISSUE THREAD

**Issue by AdditionAddict** [nrwl/nx#13217]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/packages/angular/generators/cypress-component-configuration

Enter the URL or documentation section here.

### Additional context or description

Provide any additional details here as needed.

`cypress-component-project` used instead of `cypress-component-configuration` within body of page

**Comment by AdditionAddict** [comment]
Actually I think this page is just wrong.

e.g. running the following to try to get component testing working for `shared-pdf` library is not working
```
nx generate @nrwl/angular:application component-testing-app --e2eTestRunner=none --skipTests
nx g @nrwl/angular:cypress-component-configuration --project=component-testing-app
nx g @nrwl/angular:cypress-component-configuration --project=shared-pdf --build-target:component-testing-app:build
```

**Comment by barbados-clemens** [comment]
fixed in https://github.com/nrwl/nx/pull/13613
