### ISSUE TITLE
Support MiniCssExtractPlugin options for executor @nrwl/web:webpack

### ISSUE THREAD

**Issue by gamegee** [nrwl/nx#13224]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
For the executor `@nrwl/web:webpack` be able to pass custom `MiniCssExtractPlugin` config.

## Motivation
I am working on a codebase where we have multiple chunks of JS. 
And I am running on an issue with css-modules imports order, it outputs a lot of warning. The good news is theses warning can be safely ignored and the `MiniCssExtractPlugin` already provide an option for that: `ignoreOrder: boolean`

Example of logs:
```
WARNING in chunk default-src_app_scenes_Plannings_Modals_index_ts-src_app_components_FormNewUser_FormNewUser_m-1d9765 [mini-css-extract-plugin]
Conflicting order. Following module has been added:
* css ../../node_modules/@nrwl/web/node_modules/css-loader/dist/....
```

## Suggested Implementation
Be able to provide a custom config for `MiniCssExtractPlugin` in the `project.json`, at least for the property `ignoreOrder`:

```json
{
  "build": {
    "executor": "@nrwl/web:webpack",
    "options": {
      "miniCssExtract": {
        "ignoreOrder": true
      }
    }
  }
}
```

## Alternate Implementations
Pass this config as inline property:

```json
{
  "build": {
    "executor": "@nrwl/web:webpack",
    "options": {
      "ignoreOrder": true
    }
  }
}
```

**Note:** Maybe there is a workaround to do that with the existing implementation ?

**Comment by AgentEnder** [comment]
You would need to provide a custom webpack config for this. In the executor options, we allow some customization but not for every webpack plugin / option.

**Comment by jaysoo** [comment]
The merge won't work because it results in two instances of `MiniCssExtractPlugin`. You can find the existing instance by checking the plugin name.

Like:

```
config.plugins = config.plugins.filter(plugin => plugin.name !== 'MiniCssExtractPlugin');
config.plugins.push(/* your plugin */);
```

**Comment by gamegee** [comment]
Thx this is working fine, here is my implementation:


```tsx
// Filter the existing plugin
config.plugins.filter(
  plugin => plugin.constructor.name !== 'MiniCssExtractPlugin'
)

// Then add your own plugin configuration
new MiniCssExtractPlugin({
  ignoreOrder: true
}),
```

Note, I am currently in nrwl version `14.5.0`, and I had to use the same dependency version of `mini-css-extract-plugin` as nrwl, which is "~2.4.7"

```tsx
// package.json
"mini-css-extract-plugin": "~2.4.7"
```
