### ISSUE TITLE
[Vite] fileReplacements is not working

### ISSUE THREAD

**Issue by nodegin** [nrwl/nx#13246]
### Current Behavior

The `fileReplacements` option is not working

### Expected Behavior

It should be able to resolve the file, but currently it won't resolve the file for replacement correctly

### Steps to Reproduce

1. Specify the `fileReplacements` in project.json
```
          "fileReplacements": [
            {
              "replace": "apps/core/src/config/config.staging.ts",
              "with": "apps/core/src/config/config.production.ts"
            }
          ],
```
2. Edit the `@nrwl/vite/plugins/rollup-replace-files.plugin.js` and add some log

<img width="592" alt="Screen Shot 2022-11-18 at 20 33 20" src="https://user-images.githubusercontent.com/8536244/202696131-6c723dbe-b168-4fc9-ac46-59254bf6b649.png">

4.  Build the app
`npx nx build core --configuration production  --verbose  --skip-nx-cache`

5. Observe the log
<img width="503" alt="Screen Shot 2022-11-18 at 20 33 50" src="https://user-images.githubusercontent.com/8536244/202696214-ed656774-1120-492b-ba5f-a3111bb99fe5.png">

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : darwin arm64
   npm  : 8.11.0
   
   nx : 15.2.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.2.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.0
   @nrwl/js : 15.2.0
   @nrwl/linter : 15.2.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.2.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.2.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.2.0
   @nrwl/web : 15.2.0
   @nrwl/webpack : 15.2.0
   @nrwl/workspace : 15.2.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @nrwl/vite: 15.2.0
```

**Comment by nodegin** [comment]
@mandarini  Sorry I tested your code but I found the problem was the `source` being undefined
I added this line:
`console.log('source', source);`
And this is the result:
```
source /Users/nodegin/Desktop/cms-fe/react
source /Users/nodegin/Desktop/cms-fe/react-dom/client
source /Users/nodegin/Desktop/cms-fe/react
source /Users/nodegin/Desktop/cms-fe/react-dom/client
```

From my side, there was no modules coming from the `apps` folder,
did I missed something on the usage?

**Comment by nodegin** [comment]
So I created a PR #13261 by changing the code I got it working correctly.

<img width="593" alt="Screen Shot 2022-11-19 at 2 32 53" src="https://user-images.githubusercontent.com/8536244/202766564-ffd27a7c-6e25-4462-8108-fc0debb2dd43.png">

<img width="952" alt="Screen Shot 2022-11-19 at 2 33 26" src="https://user-images.githubusercontent.com/8536244/202766658-448aa521-ebbe-4563-a805-7ab50a366666.png">

**Comment by nodegin** [comment]
Turns out I found the existing "rollup-plugin-replace-files" is a Vite Plugin... not rollup
that's why it's not working expected, it should be moved to vite config instead

**Comment by mandarini** [comment]
@nodegin yep, that's the main issue! :) I moved it out of rollup, but made sure to test the `endsWith` instead of full match, just to make sure! :)
