### ISSUE TITLE
Eslint executor has a conflict with another plugin

### ISSUE THREAD

**Issue by havenchyk** [nrwl/nx#13241]
### Current Behavior

If you specify `reportUnusedDisableDirectives` as a part project.json, no matter which value is specified, another [plugin](https://www.npmjs.com/package/eslint-plugin-eslint-comments) converts the value to boolean, so `off` becomes true.
So maybe it makes sense to set the default value for `reportUnusedDisableDirectives` to `null` instead of `off`

Even if it's not really a problem of nx executor, Eslint doesn't threat this config as a rule, instead it's a boolean config (true/false) values are considered

https://eslint.org/docs/latest/user-guide/configuring/rules#report-unused-eslint-disable-comments
https://github.com/eslint/eslint/blob/436f712843360f98b2bd63256bf0c4f77013b54c/conf/config-schema.js#L37
https://github.com/eslint/eslint/blob/436f712843360f98b2bd63256bf0c4f77013b54c/lib/eslint/eslint.js#L168

### Expected Behavior

When we specify `reportUnusedDisableDirectives` config in project.json, the boolean value is passed to the Eslint constructor, so it treated correctly by other plugins

### Steps to Reproduce

1. specify `reportUnusedDisableDirectives` in the project json, set the value to "off"
2. add https://www.npmjs.com/package/eslint-plugin-eslint-comments to the eslint config with the rule `no-unused-disable` https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/no-unused-disable.html
3. run `nx lint yourProject`
4. `reportUnusedDisableDirectives` is true

### Nx Report

```shell
   Node : 16.17.0
   OS   : darwin x64
   pnpm : 7.14.2
   
   nx : 15.0.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.1.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.1.0
   @nrwl/js : Not Found
   @nrwl/linter : 15.1.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : Not Found
   typescript : 4.6.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Additional Information

it's mostly a question, whether you think it makes sense. We can provide a PR to change this behaviour

**Comment by meeroslav** [comment]
Thank you @havenchyk for reporting this.

You are correct that Nx configuration was correct, however, we don't want to unintentionally break other plugins so we merged in the PR from @palexandrefernandes.

Thank you both!
