### ISSUE TITLE
node-sass installs even when CSS is selected

### ISSUE THREAD

**Issue by tanepiper** [nrwl/nx#1326]
## Expected Behavior

When creating a new workspace with `npx create-nx-workspace` and selected CSS as the styling method, I don't expect node-sass to install

## Current Behavior

node-sass tries to install, but currently is node supported in node 12

```
> node-sass@4.11.0 install /path/to/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-72_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.11.0 postinstall /path/to/node_modules/node-sass
> node scripts/build.js
```

## Failure Information (for bugs)

When running `npx create-nx-workspace` this tries to download node-sass, it fails and runs a build process to create it.  This step doesn't fail but does take up a lot of time.

However running `ng generate library` does fail when it attempts to do this a second time

### Steps to Reproduce

1. Use the latest node 12 version via nvm
2. Run `npx create-nx-workspace`
3. Run `ng generate library`

### Context

Please provide any relevant information about your setup:

- version of Angular CLI used - 7.3.1

### Logs

Build exits with 1 at the end after attempting to build:

```
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.11.0 (node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.11.0 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by xmlking** [comment]
Angular CLI 8 now using **sass** module instead of  **node-sass**

**Comment by tanepiper** [comment]
Not using Angular 8, but the issue seems to have resolved itself.
