### ISSUE TITLE
Allow using {projectRoot} in my commands

### ISSUE THREAD

**Issue by AbdealiLoKo** [nrwl/nx#13272]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
I was trying the following command with `run-commands`

```json
    "lint": {
      "executor": "nx:run-commands",
      "options": {
        "commands": [
          "venv/bin/flake8 libs/lib1/pkg",
          "venv/bin/black --check libs/lib1/pkg",
          "venv/bin/isort --check libs/lib1/pkg"
        ]
      },
      "inputs": ["{projectRoot}/pkg/**/*", "{projectRoot}/pkg_test/**/*"]
    },
```
Looks like in the `command` part I need to explicitly provide the `libs/lib1` multiple times.
Which is quite repetitive.

## Motivation

It will reduce user overhead from typing the paths continuously in run-command base commands, and also reduce errors in the `projects.json` file due to wrong paths etc

## Suggested Implementation

If I can use some way to access metadata about my project in my commands (either via template strings or environment variables) that would be useful.
For example:
```json
    "lint": {
      "executor": "nx:run-commands",
      "options": {
        "commands": [
          "../../venv/bin/flake8 ${projectRoot}/pkg",
          "../../venv/bin/black --check ${projectRoot}/pkg",
          "../../venv/bin/isort --check ${projectRoot}/pkg"
        ]
      },
      "inputs": ["{projectRoot}/pkg/**/*", "{projectRoot}/pkg_test/**/*"]
    },
```
or

```json
    "lint": {
      "executor": "nx:run-commands",
      "options": {
        "cwd": "${projectRoot}",
        "commands": [
          "../../venv/bin/flake8 pkg",
          "../../venv/bin/black --check pkg",
          "../../venv/bin/isort --check pkg"
        ]
      },
      "inputs": ["{projectRoot}/pkg/**/*", "{projectRoot}/pkg_test/**/*"]
    },
```

## Alternate Implementations

I tried to use the `cwd` approach by doing:
```json
    "lint": {
      "executor": "nx:run-commands",
      "options": {
        "cwd": "libs/lib1",
        "commands": [
          "../../venv/bin/flake8 pkg",
          "../../venv/bin/black --check pkg",
          "../../venv/bin/isort --check pkg"
        ]
      },
      "inputs": ["{projectRoot}/pkg/**/*", "{projectRoot}/pkg_test/**/*"]
    },
```
But in this case I need to give `../../venv` multiple times - which is also not nice and can be easily mistaken.
Eventually I had to do something like:
```json
    "lint": {
      "executor": "nx:run-commands",
      "options": {
        "cwd": "libs/lib1",
        "command": "ln -s ../../venv venv; venv/bin/flake8 pkg; venv/bin/black --check pkg; venv/bin/isort --check pkg"
      },
      "inputs": ["{projectRoot}/pkg/**/*", "{projectRoot}/pkg_test/**/*"]
    },
```
Which is not ideal because:
  1. There is a extra symlink lying around 
  2. I had to remove the parallelization that `commands` gives me to ensure the symlink creation works first
  3. While `venv` supports the symlink approach - not everything can be done line this

**Comment by divideby0** [comment]
Alternatively, it seems like a more generalized `env` parameter would be helpful. It looks like we can currently set `envFile` but that's both static and a level of indirection if you want to see what variables are passed without navigating to a different file. It could work something like this:

```json
{
  "lint": {
    "executor": "nx:run-commands",
    "options": {
      "commands": [
        "../../venv/bin/flake8 ${PROJECT_ROOT}/pkg",
        "../../venv/bin/black --check ${PROJECT_ROOT}/pkg",
        "../../venv/bin/isort --check ${PROJECT_ROOT}/pkg",
        "echo $FOO"
      ],
      "env": {
        "PROJECT_ROOT": "${projectRoot}",
        "FOO": "bar"
      }
    }
  }
}
```

It seems like this feature is pretty fundamental to the run-command executor. As highlighted by @AbdealiLoKo, many commands require a path as an argument while also accessing resources at the workspace root (which is where `cwd` might fall apart).

**Comment by jbadeau** [comment]
Strange that such a fundamental feature like string interpolation of envvars and context props are not supported.

**Comment by jbadeau** [comment]
Any priority on this?

**Comment by adlion** [comment]
Any update on this?
