### ISSUE TITLE
source-map-support not bundled into output file

### ISSUE THREAD

**Issue by IonFoXx** [nrwl/nx#1327]
## Expected Behavior

`@nrwl/builders:node-build` with option `externalDependencies: none` bundles all dependencies into one single file.

## Current Behavior

The generated output file has everything bundled within except `source-map-support`. This seems to be introduced through this change:
https://github.com/nrwl/nx/pull/1204

### Steps to Reproduce

1. Create a new backend app
2. Change the `externalDependencies` to `none` under the newly generated app
3. run `ng build <your-app-name-goes-here> --sourceMap=true --statsJson`
4. Open the generated file
5. It contains at the first line `require("source-map-support").install();`

**Comment by FrozenPandaz** [comment]
Seems to be a breaking change.

@BuckyMaler We should switch to the CLI form.

**Comment by BuckyMaler** [comment]
I'll have a PR in soon.

**Comment by BuckyMaler** [comment]
@FrozenPandaz should I target `master` or `7.8.x` in the PR?
