### ISSUE TITLE
Nice typo

### ISSUE THREAD

**Issue by anthonyskentzos** [nrwl/nx#13305]
### Documentation issue

- [x] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/node-tutorial/4-workspace-optimization

### Additional context or description

👀 😏  `apps/products-clit/src/main.ts`

**Comment by mandarini** [comment]
I'm fixing this. Please edit the title/description to match our culture :)
