### ISSUE TITLE
nx format:check results in FATAL ERROR..Aborted (core dumped) from Node

### ISSUE THREAD

**Issue by rpd10** [nrwl/nx#13337]
### Current Behavior

When running `npx nx format:check` in CircleCI, we are encountering a seemingly random error from Node.  I've included the stack trace below in Failure Logs.  So far I cannot find a pattern between affected projects or other conditions to make it happen.

So far, it only happens in CircleCI jobs.  I have not yet personally made it happen on my local machine, though it's possible that others in my organization have and just haven't reported it yet.

- it does not occur on every CircleCI build
- If I use CircleCI's SSH functionality to tunnel into a running container, I can run the command multiple times - it will fail 60-80% of the time, but run successfully the rest of the time (using same `NX_BASE` and `NX_HEAD`)

### Expected Behavior

nx format:check completes successfully in CircleCI

### Steps to Reproduce

1.  Create a pull request
2. In CircleCI, run a job that runs `npx nx format:check`

We are not using Nx Cloud.

### Nx Report

```shell
circleci@b39c6223e530:~/repo$ npx nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.1
   OS   : linux x64
   npm  : 8.1.2

   nx : 15.1.1
   @nrwl/angular : 15.1.1
   @nrwl/cypress : 15.1.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.1.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.1.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.1.1
   @nrwl/js : 15.1.1
   @nrwl/linter : 15.1.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.1.1
   @nrwl/web : Not Found
   @nrwl/webpack : 15.1.1
   @nrwl/workspace : 15.1.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @ionic/angular: 6.3.2
   	 @ngrx/component-store: 14.0.2
   	 @ngrx/effects: 14.0.2
   	 @ngrx/entity: 14.0.2
   	 @ngrx/router-store: 14.0.2
   	 @ngrx/store: 14.0.2
   	 ngx-pendo: 1.10.0
   	 @compodoc/compodoc: 1.1.19
   	 @ngrx/schematics: 14.0.2
   	 @ngrx/store-devtools: 14.0.2
   	 @nxext/capacitor: 14.0.0
   	 @nxext/ionic-angular: 14.0.0
   	 @storybook/angular: 6.5.13
   	 @testing-library/angular: 10.11.1
   	 eslint-plugin-ngrx: 2.1.2
   	 ng-mocks: 14.3.0
```

### Failure Logs

```shell
#!/bin/bash -eo pipefail
npx nx format:check
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0xb00d90 node::Abort() [node]
 2: 0xa1823b node::FatalError(char const*, char const*) [node]
 3: 0xced90a v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: 0xb04c1d node::fs::FileHandle::CloseReq::Resolve() [node]
 5: 0xb04d79  [node]
 6: 0x1555bad  [node]
 7: 0x155a336  [node]
 8: 0x156c7a4  [node]
 9: 0x155ac68 uv_run [node]
10: 0xa3dfe5 node::SpinEventLoop(node::Environment*) [node]
11: 0xbc96c2 node::worker::Worker::Run() [node]
12: 0xbc9e58  [node]
13: 0x7f263261e609  [/lib/x86_64-linux-gnu/libpthread.so.0]
14: 0x7f2632545293 clone [/lib/x86_64-linux-gnu/libc.so.6]
Aborted (core dumped)

Exited with code exit status 1
CircleCI received exit code 1
```

### Additional Information

Things I'm going to try next:
1. Invalidating the NPM cache in CircleCI to force a fresh install of dependencies
2. Updating the Node/NPM version in CircleCI to 16.18.1 (latest maintenance version supported with the Angular version we're using)

**Comment by FrozenPandaz** [comment]
Sorry, we'll need more information the reproduce this. We run `nx format:check` for this repo in CircleCI and it has been working fine. Is there any more information that you can provide to help us reproduce this issue?

**Comment by rpd10** [comment]
I think we traced this back to a version update of a Prettier plugin: `prettier-plugin-sh`.  Upgrading from 0.11.0 to 0.12.8 seems to have introduced this behavior.  We've downgraded back to 0.11.0 and it no longer happens.  Closing this as it's unrelated to Nx.
