### ISSUE TITLE
Plugins support for package-based monorepos

### ISSUE THREAD

**Issue by jeniabrook** [nrwl/nx#13330]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
To have an ability to use code generators in a packaged-base monorepo. Currently the code generators are created in terms of integrated monorepo (correct me if I wrong).

## Motivation
As we can see in [Victor Savkin's awesome persentation](https://youtu.be/nVYprf3-5GM?t=1470) there is a strong demand for package-based monorepos, so I think it is reasonable to have this support to ease and improve DX for those who are using that kind of monorepo structure.
 
## Suggested Implementation
I don't have any knowledge on how the things are built behind the scenes, but I can think of how people might use it.

**Suggestion 1:**
Use `generate` command:
```
nx generate <collection:generator> --packageBase
```
Example:
```
nx generate @nrwl/react:app myapp --packageBase
```

**Suggestion 2:**
Use `create-nx-workspace` command and add a step for configuration to ask what kind of repo is it, after the monorepo is configured the code generators will be aware of what style of monorepo has been chosen.

## Alternate Implementations
Scaffolding and building manually.

**Comment by jeniabrook** [comment]
@FrozenPandaz added the `scope: react`, my intention was for all generators (`@nrwl/react:app` was an example), sorry for the confusion, I will update the description.

**Comment by isaacplmann** [comment]
As of 15.8, you should be able to install an Nx plugin and run `nx g app my-app` as normal and everything will be configured for you.  The main piece that was missing was adding a `tsconfig.base.json` file at the root of the repo.
