### ISSUE TITLE
--routing is ignored when creating a new application

### ISSUE THREAD

**Issue by eduardoRoth** [nrwl/nx#1333]
## Expected Behavior

When running `ng g application customer-portal --style=scss --routing --prefix=app` I should get the `app-routing.module.ts` inside my `app` folder.

## Current Behavior

After I run `ng g application customer-portal --style=scss --routing --prefix=app`, `app-routing.module.ts` is not created.

### Steps to Reproduce

1. `npm install -g @angular/cli`
2. `npx create-nx-workspace myworkspace`
3. `ng g application customer-portal --style=scss --routing --prefix=app`

**Comment by eduardoRoth** [comment]
Related to https://github.com/nrwl/nx/issues/1193

**Comment by vsavkin** [comment]
We don't create a separate module for routing and instead update `app.module.ts`. This is by design.
