### ISSUE TITLE
Definition for rule '@nrwl/nx/workspace/...' was not found

### ISSUE THREAD

**Issue by rpd10** [nrwl/nx#13340]
### Current Behavior

We have implemented a few custom workspace lint rules (using `nx generate @nrwl/linter:workspace-rule`).  This works well under most circumstances.

Randomly, when we run `affected:lint`, we get errors like this (where `no-standalone-components` is the name of our lint rule
```
1:1       error  Definition for rule '@nrwl/nx/workspace/no-standalone-components' was not found.    @nrwl/nx/workspace/no-standalone-components
```

This error has occurred both locally on developer machines, and in CircleCI.  

### Expected Behavior

affected:lint runs successfully with our custom workspace ESLint rules

### Steps to Reproduce

1. Add a new workspace ESLint rule using the generator
2. Configure the eslintrc.json to apply the rule
3. Run affected:lint

### Nx Report

```shell
circleci@b39c6223e530:~/repo$ npx nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.1
   OS   : linux x64
   npm  : 8.1.2

   nx : 15.1.1
   @nrwl/angular : 15.1.1
   @nrwl/cypress : 15.1.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.1.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.1.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.1.1
   @nrwl/js : 15.1.1
   @nrwl/linter : 15.1.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.1.1
   @nrwl/web : Not Found
   @nrwl/webpack : 15.1.1
   @nrwl/workspace : 15.1.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @ionic/angular: 6.3.2
   	 @ngrx/component-store: 14.0.2
   	 @ngrx/effects: 14.0.2
   	 @ngrx/entity: 14.0.2
   	 @ngrx/router-store: 14.0.2
   	 @ngrx/store: 14.0.2
   	 ngx-pendo: 1.10.0
   	 @compodoc/compodoc: 1.1.19
   	 @ngrx/schematics: 14.0.2
   	 @ngrx/store-devtools: 14.0.2
   	 @nxext/capacitor: 14.0.0
   	 @nxext/ionic-angular: 14.0.0
   	 @storybook/angular: 6.5.13
   	 @testing-library/angular: 10.11.1
   	 eslint-plugin-ngrx: 2.1.2
   	 ng-mocks: 14.3.0
```

### Failure Logs

```shell
1:1       error  Definition for rule '@nrwl/nx/workspace/no-standalone-components' was not found.    @nrwl/nx/workspace/no-standalone-components
```

### Additional Information

When this occurs, we have found at least a temporary workaround, but since it involves manual intervention it's not ideal especially in CircleCI:
```
npm cache clean --force
npm ci
npx nx affected:lint
```

**Comment by meeroslav** [comment]
Hmm... this is interesting. If you could create a repo where it's reproducible that would allow us to get to the bottom of it.

Next time it happens, instead of running:
```bash
npm cache clean --force
npm ci
npx nx affected:lint
```

can you try?
```bash
npx nx reset # resets daemon process
npx nx affected:lint
```

That would help us figure out whether it's the stuck daemon process that's causing this.

**Comment by srqdeveloper** [comment]
@meeroslav, after running your suggested commands, the issue still persists

**Comment by meeroslav** [comment]
If you can provide some repo where this is reproducible, I will gladly reopen the issue and investigate what is going on.

**Comment by mklinke** [comment]
I implemented some rules, too, based on the YT video: https://www.youtube.com/watch?v=tEVNYmJ05Ew

I've been experiencing the issue before and after an upgrade to 15.7.2 (both on local machine and CI). 

`npx nx reset` does not help. The OP's workaround doesn't help either.

**Comment by rpd10** [comment]
I am pretty sure that the `@swc` packages are added explicitly by Nx during recent migrations.  

Is this enough information to go on?  I'm struggling to create a reproduction in a shareable repository.

**Comment by meeroslav** [comment]
There are migrations that add and remove packages. Your repo might be in a broken state (not necessarily due to your fault) so it's hard to tell what is the root cause.

Unfortunately without a reproduction, I can't help.
