### ISSUE TITLE
Run MF host with broken remote app

### ISSUE THREAD

**Issue by jewe11er** [nrwl/nx#13355]
How can we serve host when some of app in MF are broken? 
In MF if one of apps is broken the host is broken too. We expect the Host app to work in conjunction with the working apps

**Comment by Coly010** [comment]
Can you explain what you mean by broken?

The host application still needs to be able to find the `remoteEntry` file for the remotes so that it can set up the correct `imports` to register to the Router.

**Comment by jewe11er** [comment]
If one mf didn't build we expect application continue working without one element

**Comment by Coly010** [comment]
Would you be able to provide me with a repo that reproduces this behaviour so that we can investigate further?
