### ISSUE TITLE
Unnecessary tsconfig settings: "compilerOptions.outDir" and "tmp" in "exclude"

### ISSUE THREAD

**Issue by ALeschinsky** [nrwl/nx#1336]
I apologise in advance if there's actually a reason for these options, but so far my research and testing shows that these options have no effect and should be removed from the auto-generated files.

1) In a newly generated app, the files `tsconfig.app.json` and `tsconfig.spec.json` both contain a line for `outDir` under `compilerOptions` that looks like this:

```
"outDir": "../../dist/out-tsc/apps/app-name/",
```

Same line exists in `tsconfig.e2e.json` in the e2e directory. But no actual files are created under `dist/` while running `serve` or `build` commands. If this option is manually changed to any string whatsoever, including any non-existing path, nothing breaks. Seems like this setting is completely ignored - is it overridden somewhere? Is it safe to delete this line? If so, it should probably be deleted in the schematics template.

2) In root `tsconfig.json`, there's `"tmp"` in `"exclude"` array - but there are no directories or files with this name anywhere. From my research it looks like it was added a long time ago (in 2014?) for some unit tests that were creating physical temporary files under this folder. Can this exclusion option be deleted?

Please forgive me if these things seem unimportant, but I would really like to only have settings that have effect in our project. Thank you!

**Comment by vsavkin** [comment]
@ALeschinsky the files are compiled in memory by webpack/cli, so you don't see anything in the dist folder. We keep the outDir property in case you want to run `ngc` against tsconfig.app.json, at which point you will see the files on disk.

The default Angular CLI project has those properties set as well. So it's another reason why we keep it.

Cheer!

**Comment by ALeschinsky** [comment]
Thanks for the answer, it makes sense.

What about the 2nd point, `"tmp"` in `"exclude"` array?
