### ISSUE TITLE
Share assets between libraries

### ISSUE THREAD

**Issue by yonitou** [nrwl/nx#13363]
### Current Behavior

Hi

I'm trying to share my assets between my libraries. 
I have an assets library containing a `test.png` image and I want to use it in another library called `components`.
I'm able to use this test.png image into my app folder using the glob pattern : 
```
{
    "input": "libs/assets/src/lib",
    "glob": "**/*",1
    "output": "assets"
  }
```
But I don't find a way to do the same thing into another library. I looked everywhere and don't find an answer. 

### Expected Behavior

I should be able to use an asset into another library

### Steps to Reproduce

1. 

### Nx Report

```shell
Node : 16.13.1
   OS   : darwin arm64
   npm  : 8.1.2
   
   nx : 15.2.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.2.0
   @nrwl/detox : 15.2.1
   @nrwl/devkit : 15.2.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.0
   @nrwl/expo : 15.2.1
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.0
   @nrwl/js : 15.2.0
   @nrwl/linter : 15.2.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.2.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.2.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.2.0
   @nrwl/web : 15.2.0
   @nrwl/webpack : 15.2.0
   @nrwl/workspace : 15.2.0
   typescript : 4.9.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```
```


### Failure Logs

_No response_

### Additional Information

_No response_

**Comment by FrozenPandaz** [comment]
You can already sort of use assets in libraries as long as they are included in the app that uses the library.

The way it works is, the app is responsible for copying over the assets as part of its build. Then the library is built into the app and its able to use the assets. Is something not working for you?

**Comment by eglyte** [comment]
I have similar issue, as you mentioned assets was copied during build 
Storybook config main.js
`staticDirs: [{from: '../../shared/assets/src/lib', to: '../ui/assets'}],`
but when I run Storybook locally, I'm getting not found error

**Comment by yonitou** [comment]
Sorry, my question wasn't clear. I meant how to do it in an Expo app ?
