### ISSUE TITLE
Implicit dependencies for yaml files and directories

### ISSUE THREAD

**Issue by robinojw** [nrwl/nx#13374]
## Description
We'd like to ensure all projects in our monorepo are affected if any files in our `.github` folder are changed.

listing `".github/**/*.yml": "*"` in our `nx.json` doesn't seem to affect any projects and we've only been able to add this functionality with the following function.

```
export const implicitDependency = (base: string, head: string): boolean => {
  const committedFiles = JSON.parse(
    execSync(
      `files=($(git diff --name-only ${base}...${head}))` +
        ' | jq --compact-output --null-input \'$ARGS.positional\' --args -- "${files[@]}"',
      {
        encoding: 'utf8',
        maxBuffer: TEN_MEGABYTES,
      },
    ),
  );

  const { implicitDependencies } = JSON.parse(nxJson);
  let regex: any = '';

  for (const path of Object.keys(implicitDependencies)) {
    if (path.includes('/**')) {
      const directory = path.split('/**')[0];
      regex = `${regex}|^${directory}*`;
    }
  }

  regex = RegExp(regex);
  return committedFiles.some(file => regex.test(file));
};
```

## Motivation
We've built our CI around Nx, we trigger E2E tests, builds and checks depending on whats affected by the current changeset. We'd like to set the `.github` folder as an implicit dependency so we can always test changes to our workflows and actions.

**Comment by FrozenPandaz** [comment]
This should already work. It works for me. Can you please provide a repo which we can use to reproduce the issue?
