### ISSUE TITLE
Noisy logs and warning messages after running nx migrate --run-migrations

### ISSUE THREAD

**Issue by ElecTreeFrying** [nrwl/nx#13371]
### Current Behavior

Getting these logs and warning messages after my `nx migrate --run-migrations`.

I'm worried about the "Skipping migration for project..." warning message, there might be something that don't get updated or migrated based on the `migrations.json`.

Saw this stackoverlow and github issue link saying the logs doesn't affect anything.
https://github.com/nrwl/nx/issues/11138
https://stackoverflow.com/questions/73004040/project-extension-with-invalid-name-found-in-angular-with-nx

Can somebody explain what are these logs and warning messages?

```
...
Project '....'
Project 'users-api' contains extension with invalid name (files).
Project 'api-core' contains extension with invalid name (files).
    Skipping migration for project api-common. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project api-core. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project ...
    ...
    ...
```

### Expected Behavior

No logs and warning messages upon running `nx migrate --run-migrations`

`→ Project 'users-api' contains extension with invalid name (files).`
`→ Skipping migration for project api-common. Unable to determine 'tsconfig.json' file in workspace config.`

### Steps to Reproduce

1. nx migrate latest
2. nx migrate --run-migrations

### Nx Report

```shell
Node : 14.18.1
   OS   : win32 x64
   npm  : 6.14.15
   
   nx : 15.2.1
   @nrwl/angular : 15.2.1
   @nrwl/cypress : 15.2.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.1
   @nrwl/js : 15.2.1
   @nrwl/linter : 15.2.1
   @nrwl/nest : 15.2.1
   @nrwl/next : Not Found
   @nrwl/node : 15.2.1
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.2.1
   @nrwl/web : Not Found
   @nrwl/webpack : 15.2.1
   @nrwl/workspace : 15.2.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nguniversal/express-engine: 15.0.0
         @nguniversal/builders: 15.0.0
```

**Comment by FrozenPandaz** [comment]
> Skipping migration for project api-common. Unable to determine 'tsconfig.json' file in workspace config.

This is actually from `@angular/material`. Can you open an issue on https://github.com/angular/components?

> Project 'users-api' contains extension with invalid name (files).

This should have been fixed already. Can you retry with the latest version?

**Comment by ElecTreeFrying** [comment]
Okay. Thanks for the response, I'm closing this issue
