### ISSUE TITLE
Dependencies used in additional entry point are not included in the generated package.json

### ISSUE THREAD

**Issue by weiwen-chi** [nrwl/nx#13376]
### Current Behavior

We are currently using @nrwl/webpack:webpack to build my nest.js application with generatePackageJson being set as true. Lately, we added an additionalEntryPoints which is a tool we would like to run to run typeORM migration. One thing we noticed is that the chalk package which is only used in the tool was not included in the generatedPackageJson.

### Expected Behavior

All the dependencies in the additional entry points should be included in the generated pakcage.json

### Steps to Reproduce

1. Add an additional entry point to the project and only import a package (e.g. chalk) in that file.
2. Build the project 
3. Check if the package added in step 1 is included in the generated package.json

### Nx Report

```shell
n/a
```

**Comment by abrahamsaanchez** [comment]
I'm in the latest NX version and I'm using esbuild and this keeps failing

**Comment by hanstf** [comment]
we also have the same case to do a knex and mongo migration in the additionalEntryPoint and its not included also

**Comment by ndcunningham** [comment]
Sorry for the lack of updates.

I tried to reproduce your behaviour, however, it is working on my end.
It is possible at that time there could've been an issue which has now been resolved.

Here is a repo following your instructions: https://github.com/ndcunningham/issue-13376

I also added building with `esbuild` for  @abrahamsaanchez 

Can you retry with latest?
