### ISSUE TITLE
run-many exclude option is string instead of array

### ISSUE THREAD

**Issue by joh-klein** [nrwl/nx#13390]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/nx/run-many#exclude

### Additional context or description

It seems, that the exclude option is expecting [a string like the projects option](https://nx.dev/nx/run-many#projects) and not an array. See also [this discussion about it](https://github.com/nrwl/nx/discussions/10942).

**Comment by isaacplmann** [comment]
Correct, this option accepts a comma separated list.
