### ISSUE TITLE
Add exact match to NX dep-graph filter

### ISSUE THREAD

**Issue by danjor** [nrwl/nx#13394]
## Description
I would like to display only libraries/projects modified in nx graph dependency, and not all affected ones.
As there is no option to do this, I'm retreiving them using a git command and write whem in the input filter from the dep graph UI.

If I have the following libs that have been modified :
```
-lib1
-lib2
```

and the following that have not been modified :
```
-lib1-e2e
-lib2-e2e
```

If I write in the filter input the following : 

`lib1,lib2`

The search will be done using "contains", `like *lib1* *lib2*`, so the graph will display :
`lib1, lib1-e2e, lib2, lib2-e2e`

instead of only 

`lib1, lib2`

It's probably the intented behavior.
Could it be possible to add an option (a checkbox or something else), to have the filter matching exactly the name of libraries from the input filter ?

I'm using NX 14.5.6

**Comment by FrozenPandaz** [comment]
What if the search bar in the left only affected the list that you see on the left?

So you type and click `lib1` and `lib2`

**Comment by danjor** [comment]
> What if the search bar in the left only affected the list that you see on the left?
> 
> So you type and click `lib1` and `lib2` and only those 2 will show up.
> 
> cc @philipjfulcher

Thanks for your suggestion.

I could indeed display only modified projects by clicking on each item on the left panel rather than using the filter bar.
