### ISSUE TITLE
Nx graph not picking up pre-release dependencies with caret (^)

### ISSUE THREAD

**Issue by MartinDawson** [nrwl/nx#13405]
### Current Behavior

Parent:

    "childPackage": "^1.0.0-dev.3",

Child:

    "name": "childPackage",
    "version": "1.0.0-dev.3",
  
Then run `nx graph`

No dependencies are found between parent and child.

The following works:

Parent:

    "childPackage": "1.0.0-dev.3",

Child:

    "name": "childPackage",
    "version": "1.0.0-dev.3",
  
Running `nx graph` correctly has dependencies linked.

### Expected Behavior

Dependencies should be picked up between parent and child for ^ pre-release packages.

### Steps to Reproduce

See current behaviour.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : linux x64
   npm  : 8.11.0
   
   nx : 14.8.2
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.2
   @nrwl/js : 14.8.6
   @nrwl/linter : 14.8.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.8.6
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 14.8.6
   @nrwl/workspace : 14.8.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @theunderscorer/nx-semantic-release: 1.14.0
```

**Comment by FrozenPandaz** [comment]
Can you please provide a repo which exhibits the issue so we can reproduce it?

**Comment by ajmal-bash** [comment]
@FrozenPandaz  here is the link to repo which exhibits the issue
https://mobius-gitlab.bt.com/assets-public/demo-monorepo
