### ISSUE TITLE
Use nrwl/express app with pm2

### ISSUE THREAD

**Issue by ArielGueta** [nrwl/nx#13403]
There are no docs about using the `nrwl/express` application with a different command for serving. I want to [use](https://pm2.keymetrics.io/) `pm2` for both development and production. How can I do this?

Thanks.

**Comment by FrozenPandaz** [comment]
The ideal way would be to create a plugin or custom executor does something very similar to what `@nrwl/node:node` does but runs `pm2` instead.

The other thing you can do is
```
nx build node-app --watch
```

Separate terminal:
```
pm2 dist/apps/node-app/main.js
```

**Comment by ArielGueta** [comment]
Thanks.
