### ISSUE TITLE
--bundler=vite option apparently ignored.

### ISSUE THREAD

**Issue by cefn** [nrwl/nx#13427]
### Current Behavior

After running the commands below, following the [nx documentation about vite](https://nx.dev/packages/vite#generate-an-application-using-vite)
 
```sh
npm install --save-dev @nrwl/vite @nrwl/web
npm exec nx generate @nrwl/web:app my-app --bundler=vite
```

I end up with an app (with no package.json) and e2e tests all of which rely on Webpack and have no reference to vite at all. Vite has not been installed in the top level `node_modules`, there is no vite.config.js anywhere and the bundler argument seems to have been completely ignored.

### Expected Behavior

A vite-based project is created

### Steps to Reproduce

Create an nx monorepo, run the above command.

### Nx Report

```shell
[github/watchable]$ npm exec nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.12.1
   OS   : linux x64
   npm  : 9.1.1
   
   nx : 15.1.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.2.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.1.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.1.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.1
   @nrwl/js : 15.1.0
   @nrwl/linter : 15.1.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.2.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.2.1
   @nrwl/webpack : 15.2.1
   @nrwl/workspace : 15.1.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nrwl/vite: 15.2.1
         lerna: 6.0.3
```

### Failure Logs

$ npm exec nx run my-app:serve

> nx run my-app:serve

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:4200/, http://[::1]:4200/
<i> [webpack-dev-server] 404s will fallback to '/index.html'

>  NX  Web Development Server is listening at http://localhost:4200/

Entrypoint main 166 KiB = runtime.76e97c7a53fb704f.js 1.25 KiB main.7f0345943888a830.js 164 KiB
Entrypoint polyfills 213 KiB = runtime.76e97c7a53fb704f.js 1.25 KiB polyfills.e4c7a9473addda75.js 212 KiB
Entrypoint styles 121 KiB = runtime.76e97c7a53fb704f.js 1.25 KiB styles.ef46db3751d8e999.css 0 bytes styles.7eec08eab83498d4.js 119 KiB
chunk (runtime: runtime) main.7f0345943888a830.js (main) 206 KiB [initial] [rendered]
chunk (runtime: runtime) polyfills.e4c7a9473addda75.js (polyfills) 458 KiB [initial] [rendered]
chunk (runtime: runtime) styles.ef46db3751d8e999.css, styles.7eec08eab83498d4.js (styles) 157 KiB (javascript) 80 bytes (css/mini-extract) [initial] [rendered]
chunk (runtime: runtime) runtime.76e97c7a53fb704f.js (runtime) 3.37 KiB [entry] [rendered]
webpack compiled successfully (aa2531bbb91ab686)

**Comment by mandarini** [comment]
Ohhhhhhhhh!!!!! I see. So, the [vite generators commit](https://github.com/nrwl/nx/commit/f394608658fb19e46c82fc120de612fdc840026b) is not in a release yet :(

It should be available in our next release (`15.3.0`), which is coming soon! I should make a note of that in the documentation, thank you!

Bear with us! The generators will be there soon!!!

**Comment by mandarini** [comment]
I will close that, but when `15.3.0` comes out please give this another shot, and if there's still an issue let me know and we can reopen!

In the meantime, if you need any help [setting up your project manually](https://nx.dev/packages/vite#set-up-your-apps-to-use-vite.js-manually), let me know! I'm super happy to help!

**Comment by cefn** [comment]
Thanks for looking into it, @mandarini . I restructured my approach to remove nx in the end and to have my own idempotent [package.json patches and filesystem skeletons](https://github.com/cefn/watchable/tree/main/tooling/validate) which can be reapplied at will, as there were too many bugs and mismatches with my nx attempts (not just this case). I don't think I can easily 'rerun' nx scaffolding steps to benefit from later bugfixes or releases in my existing packages. I may layer it back in for task caching when pipelines are getting too slow.

**Comment by mandarini** [comment]
@cefn Oh no I am so sorry to hear that. Can you please tell me what other issues you experienced with Nx? It will be really helpful for us to understand the issues our users face.

**Comment by cefn** [comment]
Thanks for the followup. I'm happy to share in detail or engage in hallway testing if there's an appetite to iterate on the DX. I'd love to have tooling to satisfy this scaffolding role (which embeds best practice and caching optimisations) but sometimes I speculate the complexity and black-box nature makes it unmanageable for maintainer OR user. I already shared some commentary on Slack at https://nrwlcommunity.slack.com/archives/CRXERGDA9/p1669293739088169?thread_ts=1669293739.088169&cid=CRXERGDA9

**Comment by mandarini** [comment]
Thank you @cefn . I am looking at the slack message, as well, now. I asked one of my team-mates to help, since maybe their take will be more accurate!
