### ISSUE TITLE
Nx react application is not generating optimized bundle for production build

### ISSUE THREAD

**Issue by kalingaCoder** [nrwl/nx#13426]
### Current Behavior

When I build the application in production mode, the bundle generated is not minimized & not performance optimized. In project.json, flags were set for optimized code, but they were not being honoured.

In project.json, if I replace the value of *targets > build > options > "webpackConfig"* from **custom webpack path** to **"@nrwl/react/plugins/webpack"**, it honors the optimization flags and works as expected, but it doesnt generate remoteEntry.js file which is required by the host app to render the micro frontend app.

### Expected Behavior

NX build should honor the optimization flags set under targets > build > configurations > production in project.json with custom webpack & generate uglified build,

### Github Repo

https://github.com/kalingaCoder/react_MF

### Steps to Reproduce

1. Code exists here as well: https://stackblitz.com/edit/react-ts-azwv9t 

2. Do npm install

3. Do npm run build-cart

4. check bundle output here: dist\apps\cart ( files should be minimized, but that is not happening)

**Files to check:**

apps\cart\project.json : *targets > build > configurations > production* 
apps\cart\webpack.config.js 
apps\host\module-federation.config.js

My requirement is to generate prod optimized build whether with custom webpack / nrwl react executor.

### Nx Report

```shell
Node : 18.12.0
   OS   : win32 x64
   yarn : 1.22.19
   
   nx : 14.1.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.1
   @nrwl/eslint-plugin-nx : 14.1.1
   @nrwl/express : 14.4.2
   @nrwl/jest : 14.1.1
   @nrwl/js : 14.1.1
   @nrwl/linter : 14.1.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.4.2
   @nrwl/nx-cloud : 14.0.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.1.1
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.1
   @nrwl/web : 14.1.1
   @nrwl/workspace : 14.1.1
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by FrozenPandaz** [comment]
I updated your repo to the latest version and it is no longer an issue. Can you please confirm?

**Comment by kalingaCoder** [comment]
> I updated your repo to the latest version and it is no longer an issue. Can you please confirm?

I dont see any Pull Requests/ changes on my GIT repo. Did you made any changes.

**Comment by kalingaCoder** [comment]
Issue is fixed now, Earlier I was using @nrwl version 14, after migrating to latest, the issue is resolved.
Ran the below command to upgrade
nx migrate latest # same as nx migrate @nrwl/workspace@latest
