### ISSUE TITLE
jest configured with deprecated setupTestFrameworkScriptFile option

### ISSUE THREAD

**Issue by pburkindine** [nrwl/nx#1343]
## Expected Behavior

Be able to add `setupFilesAfterEnv` to jest config

## Current Behavior

Receive error `Options: setupTestFrameworkScriptFile and setupFilesAfterEnv cannot be used together.` despite not using `setupTestFrameworkScriptFile`in our code.

Appears to be caused by `node_modules/@nrwl/builders/src/jest/jest.builder.js~61`

**Comment by yannickglt** [comment]
For my part, I could resolve it by simply removing any `setupTestFrameworkScriptFile` entry from `jest-config` and `jest-preset` files. 
The Nx Jest builder is already in charge of declaring this file, and it corresponds to the `setupFile` entry in your `angular.json`:
```json
"test": {
  "builder": "@nrwl/jest:jest",
  "options": {
    "jestConfig": "apps/myapp/jest.config.js",
    "tsConfig": "apps/myapp/tsconfig.spec.json",
    "setupFile": "apps/myapp/src/test-setup.ts"
  }
}
```

**Comment by jdpearce** [comment]
I'll change the jest builder to provide `setupFilesAfterEnv` instead of `setupTestFrameworkScriptFile` but that just means we'll override whatever you have set in `jest-config.js` rather than you seeing the reported error. 🤷‍♀️

Should be a very small PR...
