### ISSUE TITLE
Inconsistant README generation on the @nrwl/react generators

### ISSUE THREAD

**Issue by ZackDeRose** [nrwl/nx#13445]
### Current Behavior

+ `create-nx-workspace` > `integrated` > `react`: does not create root-level readme
+ `@nrwl/react:application`: does not create a project level README
+ `@nrwl/react:library`: does create a project level REAME.

### Expected Behavior

I would think all three of the above would either all create or all not create REAME's.

### Github Repo

https://github.com/ZackDeRose/good-and-bad-calendars

### Steps to Reproduce

1. `npx create-nx-workspace example` > `integrated` > `react`
2. `npx nx g @nrwl/react:lib test`

^ the lib will have a readme, the app and root level will not.

### Nx Report

```shell
n/a
```

### Failure Logs

```shell
n/a
```

### Additional Information

n/a

**Comment by FrozenPandaz** [comment]
The root-level readme has been re-added in #13329.

@jaysoo can you take a look at why the application has no readme now?
