### ISSUE TITLE
Nx shouldn't give back cached output when env var is introduced in command

### ISSUE THREAD

**Issue by mcmxcdev** [nrwl/nx#13463]
### Current Behavior

When using `nx build xyz`, the output is cached as expected. 

When running `ANALYZE=true nx build xyz` afterwards, I would expect the run to bust the cache due to the introduced env var on the command, but it doesn't and takes the result from the cache.

That env is necessary for example to run https://www.npmjs.com/package/@next/bundle-analyzer on nextjs output, so I think env vars which change the command should bust the cache.

### Expected Behavior

`ANALYZE=true nx build xyz` runs without cache the first time around.

### Steps to Reproduce

1. run command without any env
2. run same command with env
3. expect result is taken from cache instead of new run

### Nx Report

```shell
Node : 18.12.1
   OS   : linux x64
   pnpm : 7.17.1
   
   nx : 15.2.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.2.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.1
   @nrwl/js : 15.2.1
   @nrwl/linter : 15.2.1
   @nrwl/nest : 15.2.1
   @nrwl/next : 15.2.1
   @nrwl/node : 15.2.1
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.2.1
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.2.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.2.1
   @nrwl/web : 15.2.1
   @nrwl/webpack : 15.2.1
   @nrwl/workspace : 15.2.1
   typescript : 4.9.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by StalkAltan** [comment]
Hi @mcmxcdev !

You need to tell Nx *which* environment variables are important. Fortunately, this should be straightforward to set up. I'd recommend looking at https://nx.dev/reference/project-configuration#inputs-&-namedinputs for an example.
