### ISSUE TITLE
Nx Cli fails without error message on Gitlab private runner

### ISSUE THREAD

**Issue by eemelipa** [nrwl/nx#13461]
### Current Behavior

We are using Gitlab to run our CICD. Running Nx on Gitlab provided runners work ok. If I run the same CI jobs on our own private runners Nx is not able to run the scripts in workspace packages. Nx would just fail without any error message about the actual reason. The root level commands work ok.

### Expected Behavior

Nx is expected to fail _with_ error message so it is possible to troubleshoot the issue.

### Steps to Reproduce

This is difficult since the problem relates to private Gitlab runners which are not available publicly. I suspect it has something to do with runner's security settings which prevent Nx cli using the nodejs `child_process#fork` function for running the subcommands. Thus, potential reproduction would be to run Nx in environment where nodejs child process `fork` cannot be used.

### Nx Report

```shell
Node : 16.15.1
   OS   : darwin x64
   npm  : 8.11.0
   
   nx : 14.8.6
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : Not Found
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.7.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
$ npx nx run app:build
> nx run app:build
 
 >  NX   Running target "app:build" failed
   Failed tasks:
   
   - app:build
   
   Hint: run the command with --verbose for more details.
```

### Additional Information

Silent failure could potentially be fixed by adding relevant log line to `packages/nx/src/tasks-runner/task-orchestrator.ts#runTaskInForkedProcess` try-catch statement.

**Comment by FrozenPandaz** [comment]
So your private runner has a patched version of `node` which doesn't allow for `child_process#fork`? Is this common?

**Comment by eemelipa** [comment]
> So your private runner has a patched version of `node` which doesn't allow for `child_process#fork`? Is this common?

The nodejs version is 16.15.1 so it is just one of the widely used versions. In my case the Nx runs in a docker container, and that docker container is ran on the private Gitlab runner. I suspect the problem is that the runner's virtual machine has some security setting turned on which causes the failure. Cannot say for sure as there isn't any hints what the error might be. So it could be the `child_process#fork` but it could be something else as well.

The container itself and the nodejs version in it should be ok since it works ok on a different runner (i.e. host machine).

**Comment by marcosnc08** [comment]
Similar error is happening to me on an AWS App runner environment, we are running nx serve API inside a Docker container and we get this.

```
02-09-2023 11:02:22 AM > nx run api:serve:production
02-09-2023 10:42:09 AM    Hint: run the command with --verbose for more details.
02-09-2023 10:42:09 AM    
02-09-2023 10:42:09 AM    - api:serve:production
02-09-2023 10:42:09 AM    
02-09-2023 10:42:09 AM    Failed tasks:
02-09-2023 10:42:09 AM  >  NX   Running target "api:serve" failed
```

I tried to add **--verbose** but it does not help.
