### ISSUE TITLE
Nx could not find process's output. Run the command without --parallel

### ISSUE THREAD

**Issue by Indronil** [nrwl/nx#13476]
### Current Behavior

Hi,

I have a CI(Github Actions) which runs a command `npx nx affected --target=deploy --parallel --max-parallel=3 --stage=pr --base=remotes/origin/main --head=HEAD --skip-nx-cache`.

I recently started seeing this 
<img width="1280" alt="Screen Shot 2022-11-29 at 10 48 58 AM" src="https://user-images.githubusercontent.com/10157698/204587981-40b62eb4-66ab-40b3-88e4-c79ef35a08ac.png">

in one of the agents for 1 app at a time. We have a mono-repo which builds and deploys around 22 angular apps . I am not sure why this happens. Also this happens sporadically, We are building angular apps using` "executor": "@angular-devkit/build-angular:browser"` and **not** webpack.

Any help would be truly appreciated.

### Expected Behavior

All builds should be successful.

### Steps to Reproduce

1.

### Nx Report

```shell
Node : 14.17.4
  OS   : darwin x64
  yarn : 1.16.0
  
  nx : 12.10.0
  @nrwl/angular : 12.10.0
  @nrwl/cli : 12.10.0
  @nrwl/cypress : 12.10.0
  @nrwl/devkit : 12.10.0
  @nrwl/eslint-plugin-nx : 12.10.0
  @nrwl/express : 12.10.0
  @nrwl/jest : 12.10.0
  @nrwl/linter : 12.10.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.10.0
  @nrwl/nx-cloud : 12.3.6
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.10.0
  @nrwl/storybook : 12.10.0
  @nrwl/gatsby : Not Found
  typescript : 4.2.3
```

### Failure Logs

```shell
Compare To Similar Tasks
no terminal output
```

**Comment by AgentEnder** [comment]
Can you run `nx report` in your terminal and paste the output in a code block below?

**Comment by Indronil** [comment]
we will be upgrading the version soon to 14.1.9. But not sure why we started getting this problem lately. That when the DTE is turned on and --parallel flag is on it causes one app to return "No Terminal Output" but when I turn --parallel=1 it works just fine.
