### ISSUE TITLE
jest-project generator fails with `Cannot read properties of undefined (reading 'test')`

### ISSUE THREAD

**Issue by joelday** [nrwl/nx#13489]
### Current Behavior

Running the jest-project generator fails with `Cannot read properties of undefined (reading 'test')`

### Expected Behavior

Running the jest-project generator succeeds in generating for the 'is-even' package.

### Github Repo

https://github.com/nrwl/nx-recipes

### Steps to Reproduce

1. Run `git clone https://github.com/nrwl/nx-recipes`
2. Run `cd nx-recipes/package-based`
3. Run `npm install`
4. Verify that the example successfully builds by running `npx nx build is-odd`, which builds both 'is-even' and 'is-odd'.
5. Following the instructions here: https://nx.dev/packages/jest, run `npm install --save-dev @nrwl/jest`
6. Run `npx nx g @nrwl/jest:jest-project --project=is-even`

Result:
 >  NX   Cannot read properties of undefined (reading 'test')
 
Also attempted:
1. (continuing from step 5), Run `npx nx g @nrwl/jest:init`
2. Again, run `nx g @nrwl/jest:jest-project --project=is-even`

Result:
 >  NX   Cannot read properties of undefined (reading 'test')

### Nx Report

```shell
Node : 18.12.1
   OS   : darwin arm64
   npm  : 8.19.2
   
   nx : 15.2.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.3
   @nrwl/js : Not Found
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : Not Found
   typescript : 4.9.3
```

### Failure Logs

```shell
>  NX   Cannot read properties of undefined (reading 'test')

TypeError: Cannot read properties of undefined (reading 'test')
    at checkForTestTarget (/Users/joel.day/repos/nx-recipes/package-based/node_modules/@nrwl/jest/src/generators/jest-project/lib/check-for-test-target.js:7:31)
    at /Users/joel.day/repos/nx-recipes/package-based/node_modules/@nrwl/jest/src/generators/jest-project/jest-project.js:46:56
    at Generator.next (<anonymous>)
    at /Users/joel.day/repos/nx-recipes/package-based/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/joel.day/repos/nx-recipes/package-based/node_modules/tslib/tslib.js:114:16)
    at jestProjectGenerator (/Users/joel.day/repos/nx-recipes/package-based/node_modules/@nrwl/jest/src/generators/jest-project/jest-project.js:43:20)
    at Object.<anonymous> (/Users/joel.day/repos/nx-recipes/package-based/node_modules/nx/src/command-line/generate.js:250:36)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/joel.day/repos/nx-recipes/package-based/node_modules/tslib/tslib.js:115:62)
```

**Comment by barbados-clemens** [comment]
this was fixed in 15.3 with the whole 'standalone' project effort. 
#13353

You can see the null checks merged in that PR
https://github.com/nrwl/nx/blob/master/packages/jest/src/generators/jest-project/lib/check-for-test-target.ts#L6
