### ISSUE TITLE
--cli=angular is not adding angular deps in package.json and not generating decorate-angular-cli file

### ISSUE THREAD

**Issue by iKrishnaSahu** [nrwl/nx#13491]
### Current Behavior

The command `npx create-nx-workspace@15.2.0 --cli=angular` is not adding angular deps in package.json and not generating decorate-angular-cli file.

This was working fine till v15.1.1.

1. Is this an expected change introduced in v15.2.0?
2. If yes, this seems like a breaking change. We should have a breaking change section in changelog
3. If --cli=angular is not supported anymore, How can I initialize my new empty workspace with angular? Will it create decorator file as well?

### Expected Behavior

Should add angular deps and create decorate angular cli file

### Steps to Reproduce

1. npx create-nx-workspace@15.2.0 --cli=angular
2. select integrated
3. select apps (create empty workspace)

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.18.1
   OS   : win32 x64
   npm  : 8.19.2

   nx : 15.2.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.3
   @nrwl/js : Not Found
   @nrwl/linter : 15.2.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.2.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by FrozenPandaz** [comment]
We no longer allow non-Angular workspaces to be created with the Angular CLI. The Nx CLI does more and we'd recommend using that. What is the reason that you would like the Angular CLI to be there? Familiarity?

**Comment by iKrishnaSahu** [comment]
We have our own in house schematics which initializes custom application and internally initializes angular as well.
`ng g` commands suddenly stopped working for us. We are checking what else we can do from our side to fix this issue.

But again this seems like a breaking change. We should have a breaking change section in Changelog.

**Comment by iKrishnaSahu** [comment]
@FrozenPandaz do you have any updates for me on above queries?

**Comment by iKrishnaSahu** [comment]
So nx is still generating `decorate-angular-cli.js` file in 2 scenarios - 

1. When you select angular while creating a nx workspace
2. While migrating angular-cli based project to nx based project ie `ng add @nrwl/angular`

**Comment by Azbesciak** [comment]
> We no longer allow non-Angular workspaces to be created with the Angular CLI. The Nx CLI does more and we'd recommend using that. What is the reason that you would like the Angular CLI to be there? Familiarity?

If NX CLI does more why does it fail when I try `nx g @angular/material:ng-add --project=olp-helper`?
