### ISSUE TITLE
Docs: linked stackoverflow tag is wrong

### ISSUE THREAD

**Issue by kiwikern** [nrwl/nx#1351]
The tag [nx] has been split into [nrwl-nx] and [nomachine-nx], see https://meta.stackoverflow.com/q/382809/4694994. 

The nrwl website https://nx.dev/ links to https://stackoverflow.com/questions/tagged/angular+nx (on the bottom of the page under Help).

This link should be updated to https://stackoverflow.com/questions/tagged/nrwl-nx

**Comment by bcabanes** [comment]
Thank you @kiwikern!
Will fix it!

**Comment by bcabanes** [comment]
Closing, fix is done and in flight for next release.
