### ISSUE TITLE
Node-forge license issue as it is installed as dependency

### ISSUE THREAD

**Issue by AshishUpadhyayCivica** [nrwl/nx#13517]
### Current Behavior

I am facing a problem of licensing((BSD-3-Clause OR GPL-2.0)) when I am using @nrwl/angular.
The issue is regarding one of the package that is installed as part of dependency.
Consider below 
![node-forge license dependency](https://user-images.githubusercontent.com/119533725/204890180-ab3c083f-7057-4f9e-b44a-7c57d1bb8678.jpg)

So I am installing @nrwl/angular and all of its dependent packages are installed under MIT license except node-forge.
My security scan detects this as problem as we don't want to use BSD-3-Clause license.

### Expected Behavior

I expect the node-forge should be removed as part of dependency of @nrwl/angular as this is creating lot of problems of licensing whilst using @nrwl/angular.

### Steps to Reproduce

1. You can check by installing @nrwl/angular and check the node-forge license.

### Nx Report

```shell
"node_modules/node-forge": {
      "version": "1.3.1",
      "license": "(BSD-3-Clause OR GPL-2.0)",
      "engines": {
        "node": ">= 6.13.0"
      }
    },
```

**Comment by FrozenPandaz** [comment]
This is a `webpack-dev-server` issue. Can you raise the issue there?

**Comment by AgentEnder** [comment]
I'm going to close this out, since its pretty removed from our stuff.
