### ISSUE TITLE
Compatibility Matrix missing current versions

### ISSUE THREAD

**Issue by michalbencur** [nrwl/nx#13521]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[URL](https://nx.dev/workspace/nx-nodejs-typescript-version-matrix)

### Additional context or description

Provide any additional details here as needed.

**Comment by isaacplmann** [comment]
This page has been updated
