### ISSUE TITLE
NX Vite should use same propretie names as Vite

### ISSUE THREAD

**Issue by AlmarAubel** [nrwl/nx#13535]
### Current Behavior

To set the base path in Vite you could set the option [`base`](https://vitejs.dev/config/shared-options.html#base) in you vite.config.ts. But the NX vite executor uses baseRef which overwrites the `base` config.  

Maybe it's a documentation thing but it's a little bit confusing now. 

### Expected Behavior

use base instead of baseHref in project.json to keep the behavior between vite and vite nx executor the same

### Steps to Reproduce

1. Create a NX vite project
2. Set base path
3. It's overwrittten by baseHref (default empty)

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.13.0
   OS   : win32 x64
   npm  : 8.1.0

   nx : 14.7.13
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.7.13
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.13
   @nrwl/eslint-plugin-nx : 14.7.13
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.13
   @nrwl/js : 14.7.13
   @nrwl/linter : 14.7.13
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.7.13
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.13
   @nrwl/web : Not Found
   @nrwl/workspace : 14.7.13
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nrwl/vite: 15.2.3
         nx-plugin-vite: 2.2.1
```

**Comment by FrozenPandaz** [comment]
`base` is an alias so it works as well. I guess we could reverse it if that makes more sense for `vite` users. The docs also don't make it clear that this is an alias?

**Comment by mandarini** [comment]
Hi there @AlmarAubel ! Thanks for filing an issue! :)

1. The "overwrite" is already fixed, and will be available in the next version of Nx (`15.3.0`).
2. I changed the name to be `base`, and added as alias the `baseHref`. The reason we used `baseHref` initially, instead of `base`, is because we wanted to keep compatibility with the `nxext/vite` package. But I can see that it will create confusion. So, default name is `base`, alias `baseHref`.

**Comment by mandarini** [comment]
![Screenshot 2022-12-02 at 2 37 55 PM](https://user-images.githubusercontent.com/6603745/205294704-be9be967-d4a1-41ef-82a5-7d999cfa4a3d.png)

That's how it looks in the docs now. `base` is the alias. After above PR is merged, this will be reversed! But the alias will work with Nx version `15.3.0` and on. And the "not overwrite" part.

**Comment by AlmarAubel** [comment]
Thanks for your quick action👍🏻

**Comment by mandarini** [comment]
No worries! You just have to wait until next version to use this, though!! :D
