### ISSUE TITLE
Invalid generator name in https://nx.dev/packages/angular/generators/cypress-component-configuration

### ISSUE THREAD

**Issue by yjaaidi** [nrwl/nx#13531]
### Documentation issue

- [X] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[Enter the URL or documentation section here.](https://nx.dev/packages/angular/generators/cypress-component-configuration)

### Additional context or description

`nx g @nrwl/angular:cypress-component-project` => `nx g cypress-component-configuration`

**Comment by FrozenPandaz** [comment]
Good catch. Would you like to open a PR to fix the issue?

**Comment by yjaaidi** [comment]
Done! I couldn't find the docs initially, otherwise, I would have sent the PR directly. 😅
Maybe we could add a link to the file on github on the docs website?
