### ISSUE TITLE
nx generator issue 

### ISSUE THREAD

**Issue by LordOfTheMoon228** [nrwl/nx#13567]
### Current Behavior

When creating new lib with custom generator by default libraryGenerator function try to add projects: "<rootDir>/libs/a/a" field in jest.config.js, if he cant do this he throw error 
<img width="635" alt="image" src="https://user-images.githubusercontent.com/110964181/205254384-0ebcd0c9-6044-4541-9fe1-0d6dfa01ef59.png">

### Expected Behavior

Like user i want to prevent modifying jest.config.js by option, or by some methods, because now i cant hide this error when generating lib

### Steps to Reproduce

1.

### Nx Report

```shell
?
```

### Failure Logs

```shell
<img width="635" alt="image" src="https://user-images.githubusercontent.com/110964181/205254384-0ebcd0c9-6044-4541-9fe1-0d6dfa01ef59.png">
```

**Comment by barbados-clemens** [comment]
can you run `nx report` and share what's in your root level jest.config.js preset?
