### ISSUE TITLE
Scss or css not showing after installing library 

### ISSUE THREAD

**Issue by yanirmanor** [nrwl/nx#13566]
### Current Behavior

Library component includes scss or css styling.
After publishing the library then install it.
In the install version style not appear. 

### Expected Behavior

The styling will showing. 

### Steps to Reproduce

1. Create library with scss
2. Then build it
3. The create new application that not related to nx
4. Install the library
5. Style not showing 

### Nx Report

```shell
?
```

**Comment by mandarini** [comment]
Hi there @yanirmanor ! Can you please provide a reproduction repository for your issue? I could not reproduce with the steps you suggested!
