### ISSUE TITLE
Runnung nx affected:libs on pipeline returns with ERROR : "fatal: Not a valid object name master"

### ISSUE THREAD

**Issue by beynya** [nrwl/nx#1356]
Runnung nx affected:libs on Azure DevOps.
Everything is working locally on mac and windows  

## Expected Behavior

`nx affected:libs --base=master` should return affected libs

## Current Behavior

Failing :(

### Context

Please provide any relevant information about your setup:

- version of Nx used - `7.4.0`
- version of Angular CLI used - `^7.2.2`
 
### Failure Logs
```bash
> nx affected:libs --base=master
fatal: Not a valid object name master
Command failed: git merge-base master HEAD
fatal: Not a valid object name master
```

**Comment by ernie58** [comment]
@beynya did you manage to find a solution, having this problem as well lately

**Comment by beynya** [comment]
@ernie58, instead of doing `--base=master` => ` --base=remotes/origin/master`

**Comment by ernie58** [comment]
thx @beynya worked!

**Comment by hoang-innomizetech** [comment]
@beynya I still getting the same error even with `--base=remotes/origin/master`. @ernie58 are you manage to fix this issue? If so can you share some ideas?

Note, the current git repo only has one branch which is the current branch of the PR (the master or base branch isn't checked out yet). Maybe this caused this error

```
nx affected:apps --base=remotes/origin/master
```

This is the error I am getting
```
fatal: Not a valid object name remotes/origin/master

>  NX   ERROR  There was a critical error when running your command

  Command failed: git merge-base remotes/origin/master HEAD
fatal: Not a valid object name remotes/origin/master
```

**Comment by statyan** [comment]
With latest update it does not work anymore. But there is a right way to put command-line arguments if you have a main branch name different from master and want to use '--all' argument:
`nx affected:build --all -- trunk HEAD`
Notice the space after '--' before the branch name (trunk in my case) That will do the trick.

**Comment by m4r4c00ch0** [comment]
Have anyone managed to run `nx affected:test` on Gitlab CI? I get this error, even after using the solution proposed by @beynya.

I have also tried using leading double-dashes, as @statyan proposes.

And I have also tried using `remotes/origin/master`, `origin/master` and `master` as the `--base` to no avail.

**Comment by srosato** [comment]
I had the same problem with GitLab, and using remotes/origin/master did not work at first. 

But I found out that **I had a merge request with so many commits** that it was failing with `Error: Command failed: git merge-base --fork-point "remotes/origin/master" "HEAD"`. git merge-base was returning an empty string because it could not find the base commit to "merge from" (to detect what is affected).

When you look at the defaults settings of GitLab it fetches at depth **50**. Increasing that makes it work again (or switching to clone strategy).

**Comment by kevinolivar** [comment]
Hi there,

got the same issue in gitlab with `nx affected:test`

## Error log

```
$ yarn affected:test
yarn run v1.22.5
$ nx affected:test
>  NX   NOTE  Affected criteria defaulted to --base=master --head=HEAD
fatal: Not a valid object name master
fatal: No such ref: 'master'
nx affected:test
Test projects affected by changes
Run command using --base=[SHA1] (affected by the committed, uncommitted and
untracked changes):
  --base  Base of the current branch (usually master)                   [string]
or using --base=[SHA1] --head=[SHA2] (affected by the committed changes):
  --base  Base of the current branch (usually master)                   [string]
  --head  Latest commit of the current branch (usually HEAD)            [string]
or using:
  --files        Change the way Nx is calculating the affected command by
                 providing directly changed files, list of files delimited by
                 commas                                                  [array]
  --uncommitted  Uncommitted changes                                   [boolean]
  --untracked    Untracked changes                                     [boolean]
Options:
  --help           Show help                                           [boolean]
  --version        Show version number                                 [boolean]
  --parallel       Parallelize the command (default: false)            [boolean]
  --maxParallel    Max number of parallel processes. This flag is ignored if the
                   parallel option is set to `false`. (default: 3)      [number]
  --all            All projects                                        [boolean]
  --exclude        Exclude certain projects from being processed
                                                           [array] [default: []]
  --runner         This is the name of the tasks runner configured in nx.json
                                                                        [string]
  --skip-nx-cache  Rerun the tasks even when the results are available in the
                   cache                              [boolean] [default: false]
  --configuration  This is the configuration to use when performing tasks on
                   projects                                             [string]
  --only-failed    Isolate projects which previously failed
                                                      [boolean] [default: false]
  --verbose        Print additional error stack trace on failure
Error: Command failed: git merge-base --fork-point "master" "HEAD"
fatal: No such ref: 'master'
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at getFilesUsingBaseAndHead (/builds/rail-delivery-group/rdg-nre/nre-apps/node_modules/@nrwl/workspace/src/command-line/shared.js:55:37)
    at Object.parseFiles (/builds/rail-delivery-group/rdg-nre/nre-apps/node_modules/@nrwl/workspace/src/command-line/shared.js:31:20)
    at projectsToRun (/builds/rail-delivery-group/rdg-nre/nre-apps/node_modules/@nrwl/workspace/src/command-line/affected.js:97:108)
    at Object.<anonymous> (/builds/rail-delivery-group/rdg-nre/nre-apps/node_modules/@nrwl/workspace/src/command-line/affected.js:27:26)
    at Generator.next (<anonymous>)
    at fulfilled (/builds/rail-delivery-group/rdg-nre/nre-apps/node_modules/@nrwl/workspace/node_modules/tslib/tslib.js:114:62) {
  status: 128,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 66 61 74 61 6c 3a 20 4e 6f 20 73 75 63 68 20 72 65 66 3a 20 27 6d 61 73 74 65 72 27 0a>
  ],
  pid: 41,
  stdout: <Buffer >,
  stderr: <Buffer 66 61 74 61 6c 3a 20 4e 6f 20 73 75 63 68 20 72 65 66 3a 20 27 6d 61 73 74 65 72 27 0a>
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Environment:

    "@nrwl/cli": "12.5.8",
    "@nrwl/cypress": "12.5.8",
    "@nrwl/eslint-plugin-nx": "12.5.8",
    "@nrwl/express": "12.5.8",
    "@nrwl/jest": "12.5.8",
    "@nrwl/linter": "12.5.8",
    "@nrwl/next": "12.5.8",
    "@nrwl/node": "12.5.8",
    "@nrwl/react": "12.5.8",
    "@nrwl/storybook": "12.5.8",
    "@nrwl/tao": "12.5.8",
    "@nrwl/web": "12.5.8",
    "@nrwl/workspace": "12.5.8",

**Comment by vNNi** [comment]
For anynone looking for gitlab `fetch-depth` change, add to your yaml:

```yaml
variables:
  GIT_DEPTH: 0

#... rest of pipe

```

**Comment by sovanny** [comment]
Had the same problem in Azure Pipeline and and adding this to the calculate affected job this fixed it:
```
steps:
  - checkout: self
    fetchDepth: 0
```

**Comment by danbilokha** [comment]
> - checkout: self
>     fetchDepth: 0

That actually helped me, thanks. I added it as a first step of my yml file.

**Comment by IlyaNakhaichuk** [comment]
@vNNi For gitlab ci, the set Git Depth: 0 does not work, maybe there are some other solutions?
