### ISSUE TITLE
Add `node_modules` to `ignorePatterns` in generated `.eslintrc.json` files

### ISSUE THREAD

**Issue by gioragutt** [nrwl/nx#13611]
- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

In `.eslintrc.json` files generated by `@nrwl/linter`, add `node_modules` to `ignorePatterns`, like so:

```diff
diff --git a/path/to/project/.eslintrc.json b/path/to/project/.eslintrc.json
index 9d9c0db5..b5a18096 100644
--- a/path/to/project/.eslintrc.json
+++ b/path/to/project/.eslintrc.json
@@ -1,6 +1,6 @@
 {
   "extends": ["../../.eslintrc.json"],
-  "ignorePatterns": ["!**/*"],
+  "ignorePatterns": ["!**/*", "node_modules"],
   "overrides": [
     {
       "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],

```

## Motivation

So far, there's not much in `@nrwl/linter` that prevents it from being used in package-based workspaces.

All it does is properly manage versions of eslint/prettier, and provide a boilerplate for a scalable `.eslintrc.json`. Basically the dream of every JS developer.

One thing missing from supporting package-based repos properly? Ignore `node_modules`.
The default generated `ignorePatterns` un-ignores all the content in a project, and it works in integrated workspaces because in such projects it won't have a node_modules - all the files are content of the project.

In package-based workspaces, projects can have their own node_modules, and this causes linting to be unnecessarily longer.

Adding `node_modules` does not handle all package-based workspaces cases. It's true for any `dist`/`converage`/`build` or whatever folders that are output of commands (if only `.eslintrc.json` could use `project.json['targets'][*]['output'` ah?).

However, it's a good start.

## Suggested Implementation

Update the file template to include `node_modules`.

## Alternate Implementations

Aside from the suggested implementation, other heuristics could be made to cover more cases, but IMO this is out-of-scope.

**Comment by FrozenPandaz** [comment]
I think `node_modules` should be added to a `.eslintignore` file.

**Comment by gioragutt** [comment]
> I think `node_modules` should be added to a `.eslintignore` file.

Agree. Just need to make sure it catches nested `node_modules` as well, not only the root one.
