### ISSUE TITLE
Unit tests failure after this step of tutorial

### ISSUE THREAD

**Issue by gonglei** [nrwl/nx#13610]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[Angular Tutorial - Part 2: Project Graph](https://nx.dev/angular-tutorial/2-project-graph)

### Additional context or description

Provide any additional details here as needed.

Unit tests failed in store app:
nx run store:test

NG0304: 'myorg-banner' is not a known element (used in the 'AppComponent' component template)

In the common-ui lib, the banner component is exported:
@NgModule({
  imports: [CommonModule],
  declarations: [BannerComponent],
  exports: [BannerComponent],
})
export class CommonUiModule {}

In the store app, the common ui module is imported:
@NgModule({
  declarations: [AppComponent, NxWelcomeComponent],
  imports: [BrowserModule, CommonUiModule],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {}

In the store app, AppComponent refers <myorg-banner ...> in its template.

Environment:
I am running latest nx cli currently, in package.json, devDependencies:
    "@nrwl/cli": "15.2.4",
    "@nrwl/cypress": "15.2.4",
    "@nrwl/eslint-plugin-nx": "15.2.4",
    "@nrwl/jest": "15.2.4",
    "@nrwl/linter": "15.2.4",
    "@nrwl/workspace": "15.2.4",
Angular version is 15.0.0.

**Comment by Dgotin** [comment]
@gonglei you have to add BannerComponent in spec.ts `beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [AppComponent, NxWelcomeComponent, BannerComponent],
    }).compileComponents();
  });`

Because spec.ts won't add recently added components to your tests you have to do it manually

You also have to change the full spec.ts because it is a default generated spec.ts as it won't find the expected h1 afterwards and return an error: value undefined

**Comment by Dgotin** [comment]
@gonglei could you post a screenshot of your error pls

**Comment by Dgotin** [comment]
@gonglei okay I found out that there is a bigger issue with the docs, e.g., in my-banner you deliver a title but BannerComponent awaits an Input called test not title

But there are also other issues. I recommend you to following issue https://github.com/nrwl/nx/issues/13619 as @alansegar mentioned above

**Comment by gonglei** [comment]
@Dgotin yes mismatching of @Input names in component (text) and usages (title) is the problem. I also followed issue #13619 to fix some unit tests. Thanks for your help.
