### ISSUE TITLE
readProjectConfig(tree, 'appName') and readJson(tree, 'project.json') produce different results for standalone app

### ISSUE THREAD

**Issue by ZackDeRose** [nrwl/nx#13617]
### Current Behavior

Running a set of operations on a project.json file during the course of a generator results in only the last change occurring. I expect this is because the `readProjectConfig()` utility fn from nx-devkit is actually reading from the file system, not the Tree.

### Expected Behavior

Should read from Tree / Should see all changes occur in my example.

### Github Repo

https://github.com/ZackDeRose/advent-of-code-starter/tree/bug-showcase

### Steps to Reproduce

1. `npx nx g @advent-of-code-starter/nx-advent-of-code-plugin:all-days`
2. inspect project.json file
3. find only the last (25th) day has it's targets present.
(note that by replacing `readProjectConfiguration()` with `readJson()` I can get the expected behavior!)

===

## Places of interest:

https://github.com/ZackDeRose/advent-of-code-starter/blob/bug-showcase/tools/nx-advent-of-code-plugin/src/generators/day-generator/generator.ts#L26 - this is where `readProjectConfig()` is being called

https://github.com/ZackDeRose/advent-of-code-starter/blob/bug-showcase/tools/nx-advent-of-code-plugin/src/generators/all-days/generator.ts - the `allDays` generator calls the `dayGenerator` for days 1-25

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 15.3.0-beta.12
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.0-beta.12
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.4
   @nrwl/js : 15.2.4
   @nrwl/linter : 15.3.0-beta.12
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.2.4
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 15.2.4
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.2.4
   @nrwl/workspace : 15.3.0-beta.12
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
         @advent-of-code-starter/nx-advent-of-code-plugin
   ---------------------------------------
   Community plugins:
```
```


### Failure Logs

_No response_

### Additional Information

_No response_

**Comment by ZackDeRose** [comment]
looking a bit closer tonight (now that 15.3 is out)

**Comment by ZackDeRose** [comment]
Took a closer look - this was not a simple case of just reading from the original file structure.

After debugging, I was able to resolve the issue by adding a workspace.json to my given example to specify the location of the root level application.

my `workspace.json`:
```json
{
  "version": 2,
  "projects": {
    "advent-of-code-starter": "."
  }
}
```

Given this, my next hypothesis was that this utility of the nx-devkit is broken for "root projects".

I added the following unit tests, expecting it to fail given my hypothesis, but it passes:

```ts
it('should reflect changes made in the tree over time w/ root level apps', async () => {
        await applicationGenerator(tree, {
          rootProject: true,
          name: 'proj1',
          bundler: 'vite',
          e2eTestRunner: 'none',
          unitTestRunner: 'vitest',
          style: 'css',
          linter: Linter.EsLint,
          standaloneConfig: true,
        });
        const originalReadProjectConfig = readProjectConfiguration(
          tree,
          'proj1'
        );
        expect(originalReadProjectConfig).toEqual(
          expect.objectContaining({
            name: 'proj1',
            sourceRoot: './src',
            projectType: 'application',
            tags: [],
            root: '.',
            $schema: 'node_modules/nx/schemas/project-schema.json',
          })
        );
        const originReadJson = readJson(tree, 'project.json');
        expect(originReadJson).toEqual(
          expect.objectContaining({
            name: 'proj1',
            $schema: 'node_modules/nx/schemas/project-schema.json',
            sourceRoot: './src',
            projectType: 'application',
            tags: [],
          })
        );
        updateProjectConfiguration(tree, 'proj1', {
          targets: { foo: {} },
          root: '.',
        });
        const updatedReadJson = readJson(tree, 'project.json');
        expect(updatedReadJson.targets).toEqual({ foo: {} });
        const updatedReadProjectConfig = readProjectConfiguration(
          tree,
          'proj1'
        );
        expect(updatedReadProjectConfig.targets).toEqual({ foo: {} });
      });
```

The hypothesis that I'm left with is that the example repo (assuming I remove the `workspace.json` file) is misconfigured as to how it should inform Nx that there is project at the root. I'll look to verify this later.

**Comment by tbinna** [comment]
I figured this one out. As I understand, this has to do with the way node resolves modules. My plugin project was called `forge` and the package name is `@toolsplus/nx-forge`. [This article](https://www.bennadel.com/blog/2169-where-does-node-js-and-require-look-for-modules.htm) guided me in the right direction.
Since I renamed my plugin project to `nx-forge` the tests are passing. Maybe this is useful to anyone passing by here.

**Comment by mandarini** [comment]
@ZackDeRose 

I just tried it in the latest version of Nx:

```
  const projConf = readProjectConfiguration(tree, 'mystand');
  const projJson = readJson(tree, 'project.json');
```

`projConf` and `projJson` are identical, so I will be closing this issue now!

Here's my repro repo: https://github.com/mandarini/read-project-conf

and the two files: https://github.com/mandarini/read-project-conf/blob/main/my-plugin/src/generators/my-generator/projConf.json
https://github.com/mandarini/read-project-conf/blob/main/my-plugin/src/generators/my-generator/projJson.json

and the code that gets the output: https://github.com/mandarini/read-project-conf/blob/main/my-plugin/src/generators/my-generator/generator.ts#L11
