### ISSUE TITLE
Dependency calculator too brittle with regards to path aliasing

### ISSUE THREAD

**Issue by MaximSagan** [nrwl/nx#1361]
## Expected Behavior

In large monorepos, some libs can be nested fairly deeply, e.g. `libs/shared/features/navigation-features/navigation-feature-1`.

For commonly used libs, it may be beneficial to alias the path (using tsconfig.json's `compilerOptions.paths` property) to such libs as something like `@{npmScope}/navigation-feature-1` (or even just `@navigation-feature-1` if the user wishes, although I agree it would be best practise to include the scope) rather than `@{npmScope}/shared/features/navigation-features/navigation-feature-1`.

Using the former (abbreviated) alias should not break the dependency calculator.

## Current Behavior

In the above example, using any alias than the latter (verbose) alias, the dependency calculator will fail to add the dependency.

See the [addDepIfNeeded](https://github.com/nrwl/nx/blob/cbd35e05831edd54ec5a666e4f0197ebfd8000b6/packages/workspace/src/command-line/deps-calculator.ts#L323) method from `nx/packages/workspace/src/command-line/deps-calculator.ts`:

```ts
  private addDepIfNeeded(
    /**
     * 'expr' is essentially the string at the end of your import expression
     * following 'from'
     **/
    expr: string,
    filePath: string,
    depType: DependencyType
  ) {
    const matchingProject = this.projects.filter(a => {
      /**
       * 'normalizedRoot' is just project.root without the 'apps/' or 'libs/'
       **/
      const normalizedRoot = normalizedProjectRoot(a);
      return (
        expr === `@${this.npmScope}/${normalizedRoot}` ||
        expr.startsWith(`@${this.npmScope}/${normalizedRoot}#`) ||
        expr.startsWith(`@${this.npmScope}/${normalizedRoot}/`)
      );
    })[0];

    if (matchingProject) {
      this.setDependencyIfNotAlreadySet(
        this.deps.files,
        filePath,
        matchingProject.name,
        depType
      );
    }
  }
```

Clearly, if we look at the above code, we can see that we are extremely limited in our ability to alias any paths. As we see [in the tsconfig.json in nrwl/nx-examples](https://github.com/nrwl/nx-examples/blob/master/tsconfig.json), all we are really able to do with path aliasing is to remove the `/src/index.ts` suffix, e.g. `"@nx-examples/teach/app1": ["libs/teach/app1/src/index.ts"]`.

Is it not possible or us to extract path definitions from TS config for use in the dependency calculator?

**Comment by vsavkin** [comment]
We are planning to support Bazel for Nx 9 (opt-in only), which has a more restrictive way of defining path mappings. I think the feature request is meaningful, but I'm not sure if we will be able to make it work given the bazel constraints.
