### ISSUE TITLE
Angular Tutorial Improvements

### ISSUE THREAD

**Issue by alansegar** [nrwl/nx#13619]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/angular-tutorial/2-project-graph
https://nx.dev/angular-tutorial/4-workspace-optimization

### Additional context or description
In addition to https://github.com/nrwl/nx/issues/13614 and https://github.com/nrwl/nx/issues/13610 I found a few other changes helped me to understand NX and the content of the tutorial (this is my first experience using NX)

- In `apps/admin/src/app/app.component.ts`
  - Changing `selector: 'my-app',` to `selector: 'myorg-root',`
  - Changing `<common-ui-banner title="Welcome to our admin app."> </common-ui-banner>` to `<myorg-banner text="Welcome to our admin app."> </myorg-banner>` 
    - (`title=` changed to `text=` and `common-ui-banner` changed to `myorg-banner`)
    - Alternative would be to change `@Input() text = '';` to `@Input() title = '';` in `libs/common-ui/src/lib/banner/banner.component.ts`
- In `apps/store/src/app/app.component.ts`
  -  Changing `<myorg-banner title=` to `<myorg-banner text=` to match `libs/common-ui/src/lib/banner/banner.component.ts`
- In `libs/common-ui/src/lib/banner/banner.component.css`
  - Changing  the file contents for https://nx.dev/angular-tutorial/4-workspace-optimization to: 
     ```css
      header {
        color: blue;
      }
     ```
       so that the text renders in blue when viewing the apps
- In `libs/common-ui/src/lib/banner/banner.component.ts`
  -  Adding `styleUrls: ['banner.component.css'],` so that the CSS change in https://nx.dev/angular-tutorial/4-workspace-optimization can be seen when viewing the apps
- In `apps/admin/project.json` adding a port (`3100`) so that both admin and store apps can be started together
   ```typescript
    "options": {
      "port": 3100
    }
   ```
 - In `apps/store/project.json` adding a different port (`3000`) so that both admin and store apps can be started together
   ```typescript
    "options": {
      "port": 3000
    }
   ```
- Explain that the apps can be viewed in a browser by running `npx nx run-many --target=serve --projects=store,admin`  
  - I'm new to NX so unsure if this is the best way but it seemed to show what I was expecting at http://localhost:3000/ and http://localhost:3100/ 
- As mentioned in https://github.com/nrwl/nx/issues/13610 the unit tests require changes to make them pass after https://nx.dev/angular-tutorial/2-project-graph
  - console.error 
  ```
  console.error
    NG0304: 'myorg-banner' is not a known element (used in the 'AppComponent' component template):
    1. If 'myorg-banner' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
    2. If 'myorg-banner' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    ```
    seemed to be suppressed by the following change (I don't have the experience to know if this is the best fix)
    ```typescript
    import {CUSTOM_ELEMENTS_SCHEMA} from '@angular/core';
    
    describe('AppComponent', () => {
      beforeEach(async () => {
        await TestBed.configureTestingModule({
          declarations: [AppComponent],
          schemas: [
            CUSTOM_ELEMENTS_SCHEMA
          ]
        }).compileComponents();
      });
    ```
    - The following seemed to check the text is correct in the rendered banner:
    ```typescript
        expect(compiled.querySelector('myorg-banner')?.getAttribute('text')).toContain(
      'Welcome to the store!' // Change to 'Welcome to our admin app.' for the admin app
    );
    ```
    - Some possible options for the store test:
    ```typescript
    it(`should have sample data as products`, () => {
      const fixture = TestBed.createComponent(AppComponent);
      const app = fixture.componentInstance;
      expect(app.products.length).toEqual(2);
      expect(app.products).toContainEqual({"id": "1", "name": "Product 1", "price": 100});
      expect(app.products).toContainEqual({"id": "2", "name": "Product 2", "price": 200});
      // OR 
      expect(app.products.find(product => product.id === "1")?.name).toEqual( "Product 1");
      expect(app.products.find(product => product.id === "1")?.price).toEqual( 100);
  
      expect(app.products.find(product => product.id === "2")?.name).toEqual( "Product 2");
      expect(app.products.find(product => product.id === "2")?.price).toEqual( 200);
    });
    ```
- Explain how to run all tests locally. Based on https://github.com/nrwl/nx/issues/3191, I think this is the command but it's not mentioned in the tutorial `npx nx run-many --all --target=test`
  - It's easy to misunderstand and think that `npx nx test` will run all the tests but that only runs the project store tests

**Comment by Dgotin** [comment]
@alansegar I re-followed the docs and could not find more issues. Thanks for your big summary of failures!

**Comment by Coly010** [comment]
I will update the docs to fix the bugs in the code listed versus the code that is generated.

Regarding some of your other comments:
1. serving both apps at once; this is outside the scope of the tutorial and is not something we would often see in practice. 
2. running _all_ tests; this goes against Nx's mantra of only testing code that has changed. This is why the tutorial specifically mentions using `nx affected --target=test`
3. The console.error logs in the tests when run individually; I'll added a callout in the docs to warn users about it
