### ISSUE TITLE
Generated jest configs should have `collectCoverageFrom` set

### ISSUE THREAD

**Issue by mcmxcdev** [nrwl/nx#13622]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Currently when running e.g. `nx test project-a --codeCoverage`, it outputs a folder under `coverage` with an `index.html` that has the detailed code coverage stats.

I would expect the code coverage only to include the nested package that I ran code coverage on, but it displays coverage for the whole monorepo.

By adding `collectCoverageFrom: ['**/*.{ts,tsx}']` to the jest config, I was able to only see relevant files for a e.g. Nextjs project in this case.

## Motivation
Clearer path to work with code coverage

## Suggested Implementation
In my opinion, `nx` should have this set by default with the correct file extensions defined.

## Alternate Implementations
N/A

**Comment by barbados-clemens** [comment]
I'm not sure we should make this the default or have an extra option for the jest project generator to set this value?

I for sure see the validity in having that property set, but some folks do prefer using test coverage of their whole monorepo.

Open to hear arguments for either, 
but I'm leaning towards adding it as option for the generators so it can be controlled, but defaulting it to "on" and it can be opt out of by anyone who does want to collect coverage from the whole repo.

**Comment by barbados-clemens** [comment]
Going to close as this can be configured after project generating and this is one of the options that is now a 'global' setting which is causing extra warning in local project configs as a bug so adding it just introduces more warnings and extra things to migrate in the future.

**Comment by mcmxcdev** [comment]
> this is one of the options that is now a 'global' setting which is causing extra warning in local project configs

Yeah, we do get jest warnings due to `Unknown option "coverageDirectory"` for a while already. 

Has this to be fixed by jest or do we need to change anything related to `coverageDirectory` option which is currently in every jest config throughout our monorepo? Or will there be a nx migration to auto update configs?

**Comment by barbados-clemens** [comment]
It's an upstream issue by Jest, when that bug is fixed and a migration paths is provided Nx will provide a migration. 
Follow along with this issue 
#15752
