### ISSUE TITLE
upgrading from nx 14 -> 15 breaks typescript webworkers

### ISSUE THREAD

**Issue by hevans90** [nrwl/nx#13628]
### Current Behavior

In my project (using nx 14, with a standard react app setup), I am using a web worker with TS using the following constructor:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/12142999/205638440-bacd9549-4e45-40aa-9397-636de876492f.png">

This works perfectly fine.

However when I migrate my repo to `nx 15`, this happens:

![image](https://user-images.githubusercontent.com/12142999/205638720-29c80ccd-b111-413e-9f6a-f033c064a50e.png)

I have tried this, and it has no effect:

<img width="687" alt="image" src="https://user-images.githubusercontent.com/12142999/205638903-d0bd8b99-be6f-4ba7-b527-5437b816f1a6.png">

### Expected Behavior

Should work normally as before. This is a webpack configuration issue.

### Steps to Reproduce

1.

```typescript
export const worker = new Worker(new URL('./worker.ts', import.meta.url));
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : darwin x64
   yarn : 1.22.19

   nx : 15.2.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.2.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.4
   @nrwl/js : 15.2.4
   @nrwl/linter : 15.2.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.2.4
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.2.4
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.2.4
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.2.4
   @nrwl/web : 15.2.4
   @nrwl/webpack : 15.2.4
   @nrwl/workspace : 15.2.4
   typescript : 4.8.4
```

### Additional Information

I think this is an underlying webpack config issue.

**Comment by hevans90** [comment]
I dug through the yarn lock and node modules and found that this issue is because of the introduction of `@nrwl/webpack`, and hence a new webpack config which sets `output.scriptType` to `module` rather than `text/javascript`... changing it back fixes this issue but I am guessing you don't wanna do that for ESM purposes... I am a but out of my depth here, but can anyone with more webpack experience chime in?

https://webpack.js.org/configuration/output/#outputscripttype

<img width="703" alt="image" src="https://user-images.githubusercontent.com/12142999/205647865-3205e689-0bf4-460b-8932-50e4abf82cb5.png">

**Comment by sancelot** [comment]
I have similar issue, my webworker is defined in a workspace library.
and I can not run it

**Comment by flippidippi** [comment]
This is an issue for us too. We had to create a custom webpack config to change it back. This should be configurable or just go off what the default is from `output.module`

**Comment by hevans90** [comment]
Any update on this from the nx team @FrozenPandaz ?

**Comment by SandeepThomas** [comment]
@hevans90 if you just want to change the output.module type in nx [15.6.3](https://github.com/nrwl/nx/releases/tag/15.6.3), you can do this

```
const { composePlugins, withNx } = require('@nrwl/webpack');
const { withReact } = require('@nrwl/react');

// Nx plugins for webpack.
module.exports = composePlugins(withNx(), withReact(), (config) => {
  config.output.scriptType = 'text/javascript'
  return config;
});

```

tested in sample repo for nx-react with web worker: https://github.com/SandeepThomas/nx-react-worker

**Comment by sancelot** [comment]
using either vite or webpack ths issues will not be the same, here is an example using vite build https://github.com/sancelot/nx-webworker-example
