### ISSUE TITLE
Nx is very slow in a large monorepo (>500k files) due to globbing of `**/project.json`

### ISSUE THREAD

**Issue by elado** [nrwl/nx#13637]
### Current Behavior

Reopening https://github.com/nrwl/nx/issues/9660

I'm trying to integrate nx in an existing large monorepo (>500k files), but it only has ~25 workspaces.
When nx initializes, it tries to get the list of workspaces by globbing both `**/project.json` and all the `workspaces` items from `package.json`:

https://github.com/nrwl/nx/blob/61d7d74378305ba96f9e94707aefeecb438328ca/packages/nx/src/config/workspaces.ts#L703

This `**/project.json` forces the glob to crawl every file, and that takes 5+s in my case, just the init phase of every command.

Dropping `**/project.json` from the glob makes the glob operation instantaneous.
A fix would be to have something similar to `getGlobPatternsFromPackageManagerWorkspaces` that only reads package path entries from package.json workspaces instead, and appends `project.json`.

https://github.com/nrwl/nx/blob/61d7d74378305ba96f9e94707aefeecb438328ca/packages/nx/src/config/workspaces.ts#L687

### Expected Behavior

To have a faster nx boot time.

### Steps to Reproduce

Any repo with hundreds of thousands of files should show the slowness.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.18.0
   OS   : darwin arm64
   yarn : 3.2.4
   
   nx : 15.2.4
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.0.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.0
   @nrwl/js : Not Found
   @nrwl/linter : 14.0.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 14.0.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by FrozenPandaz** [comment]
Are there perhaps directories that you don't expect to ever have Nx projects that you think Nx shouldn't scan?

For instance, we by default ignore `.git` and `node_modules`. If so, you can add those directories to `.nxignore` and it will make this time faster. 

Do you think it's possible to provide us a repo which exhibits the slowness? We have pretty large repos and it doesn't take 20-40s

**Comment by elado** [comment]
Apologies, 20-40s was the behavior in v14. I just verified the speed with v15. It's adding 5-6s to each run. Commenting out `**/project.json` brings the globbing time down to 20ms.

I am inside a monorepo of an entire company so there are hundreds of additional folders and hundreds of thousands of files that are unrelated to the frontend code that nx is supposed to handle.

I am noticing that the globs end up being something like

```
[
  'project.json',
  '**/project.json',
  'proj1/web/package.json',
  'proj2/web/package.json',
  'proj3/package.json',
  'js/packages/*/package.json',
]
```

and it'd be much faster if it were:

```
[
  'project.json',
  'proj1/web/package.json',
  'proj1/web/project.json',
  'proj2/web/package.json',
  'proj2/web/project.json',
  'proj3/package.json',
  'proj3/project.json',
  'js/packages/*/package.json',
  'js/packages/*/project.json',
]
```

(replaced `**/project.json` with individual entries like `package.json`'s)

**Comment by elado** [comment]
Not stale

**Comment by elado** [comment]
Not stale

**Comment by vdumitraskovic** [comment]
Hello there! Did anyone find a solution for this?

**Comment by elado** [comment]
@vdumitraskovic I created this patch (yarn patch or patch-package):

```diff
diff --git a/src/config/workspaces.js b/src/config/workspaces.js
index 5dad79d352ed3ffa6dc4a3f6cda0656fad099262..2473944ed2c7a3c1c9405f60dad8821af735cfb9 100644
--- a/src/config/workspaces.js
+++ b/src/config/workspaces.js
@@ -464,9 +464,14 @@ function getGlobPatternsFromPackageManagerWorkspaces(root) {
 }
 exports.getGlobPatternsFromPackageManagerWorkspaces = getGlobPatternsFromPackageManagerWorkspaces;
 function normalizePatterns(patterns) {
-    return patterns.map((pattern) => removeRelativePath(pattern.endsWith('/package.json')
+    // Return both package.json and project.json per pattern.
+    // See https://github.com/nrwl/nx/issues/13637
+    const paths = patterns.map((pattern) => removeRelativePath(pattern.endsWith('/package.json')
         ? pattern
         : (0, path_2.joinPathFragments)(pattern, 'package.json')));
+
+
+    return paths.flatMap(pattern => [pattern, pattern.replace(/package\.json$/, 'project.json')]);
 }
 function removeRelativePath(pattern) {
     return pattern.startsWith('./') ? pattern.substring(2) : pattern;
@@ -489,7 +494,9 @@ function globForProjectFiles(root, nxJson, ignorePluginInference = false) {
         .map((glob) => (glob.startsWith('/') ? glob.substring(1) : glob));
     const projectGlobPatterns = [
         'project.json',
-        '**/project.json',
+        // '**' glob causes a major slowdown. The normalizePatterns function is patched to bring back project.json
+        // See https://github.com/nrwl/nx/issues/13637
+        // '**/project.json',
         ...globsToInclude,
     ];
     if (!ignorePluginInference) {
```

**Comment by vdumitraskovic** [comment]
Thank you, @elado I was hoping that the NX team has their own solution to this. I guess the NX team will work on the performance in the future when they have time to do so.

**Comment by AgentEnder** [comment]
Hey, sorry for the lack of answers on this one. Its certainly not stale, and the globbing performance is something that we are aware of. Generally tuning .nxignore can help out quite a bit, but there are some similar issues that would probably shake out to work for this one too.

For instance, #13843 would be solved by a similar solution.

We don't want to adopt the package.json workspaces field in particular because that ties Nx down to JS and requiring the root package.json. Additionally, the current setup allows you to have some projects managed by npm workspaces and some only by Nx. I could see a world where we add a similar field into nx.json, but I'm not sure exactly what that would look like. I'll try to get with @FrozenPandaz and see what his thinking is, probably need some input from @vsavkin on this one too.

**Comment by dgreif** [comment]
I'm working on setting up a JS monorepo within a very large Ruby monolith, and running into this same issue. The `**/project.json` causes all of the directories to be crawled, while we only care about a small subset. I've tried leveraging `.nxignore` to speed it up, but it doesn't seem to help.  I think the problem lies in this section of code: https://github.com/nrwl/nx/blob/73bc2e1c915fac40e29db930297121646362733b/packages/nx/src/config/workspaces.ts#L630-L646

Note that the `globSync` call is made _without_ taking `.nxignore` into consideration. The `ig` value is passed into `deduplicateProjectFiles`, but not until _after_ we have already globed the file system without considering `.nxignore`. Would it be possible to parse the `.nxignore` and add the values to `ALWAYS_IGNORE` before calling `globSync`? Something like this:

```ts
  try {
    const nxIgnoreContent = readFileSync(`${root}/.nxignore`, 'utf-8')
    nxIgnoreContent.split('\n').forEach((rawLine) => {
      const line = rawLine.trim()
      if (line) {
        ALWAYS_IGNORE.push(line)
      }
    })
    ig.add(nxIgnoreContent);
  } catch {}
```

**Comment by seansfkelley** [comment]
If you want to count how many files it's probably scanning, this snippet will do it:

```sh
find -E . -regex '.*/(node_modules|\.git|dist).*' -prune -o -type f -print | wc -l
```

In my case, I have 91k files, and I see a ~2 second delay on every invocation. I have 142 project.jsons.

An option in `nx.json` to specify exactly the glob to scan for project.jsons that overrides all the defaults set seems like a straightforward solution from the user's side. (I'm surprised that there is no such option... am I missing something in the documentation? Is this globbing the only supported way to find project.jsons?)

**Comment by AgentEnder** [comment]
> Note that the globSync call is made without taking .nxignore into consideration. The ig value is passed into deduplicateProjectFiles, but not until after we have already globed the file system without considering .nxignore. Would it be possible to parse the .nxignore and add the values to ALWAYS_IGNORE before calling globSync? Something like this:

This was addressed by #15242

> An option in nx.json to specify exactly the glob to scan for project.jsons that overrides all the defaults set seems like a straightforward solution from the user's side.

We are investigating how we can better support this, or improve perf to the point that its not needed. More info as its available.

**Comment by seansfkelley** [comment]
This is still an issue.

**Comment by FrozenPandaz** [comment]
The performance for this should've gotten much better on the latest versions of Nx. Could you please retry with the latest version?
