### ISSUE TITLE
Nx 8 and Ivy Support

### ISSUE THREAD

**Issue by vsavkin** [nrwl/nx#1364]
Hey folks,

Many of you are excited about the coming Ivy support in Angular 8. Even though Ivy is still experimental, and I personally encourage you not to use in production, you can use it in an Nx repo.

```
npx --ignore-existing create-nx-workspace@next ivy --preset=angular
```

Add the following to `tsconfig.app.json`:

```
{
  "angularCompilerOptions": {
    "enableIvy": true
  }
}
```

And you should be good to go!

Please let us know if you have any issues with using Ivy

**Comment by marcus-sa** [comment]
For me, my app just takes forever to build, since Ivy tries to compile ALL modules that I'm using.

**Comment by un33k** [comment]
@vsavkin Since Ivy is already released with Ng 8.0 as an opt-in, do you think you could update your comment above, or you still encourage people to not use it in production?

**Comment by vsavkin** [comment]
I'm still not encouraging folks to use it in production. I'd wait till the Angular team switches to Ivy as the default rendering engine.

**Comment by vsavkin** [comment]
Closing this. We have had Ivy support for a while, and Nx 9 will come with Ivy on by default.
