### ISSUE TITLE
1st class integration with changesets

### ISSUE THREAD

**Issue by maximveksler** [nrwl/nx#13643]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

[Changeset](https://github.com/changesets) is a tool for effective version and changelog management, mostly for npm based projects (with limited support for blackbox projects).

I would like the abiliby to invoke `changesets publish` based on `nx affected`.

## Motivation

This would support clear and efficient integration flows

## Suggested Implementation

Changeset should get it's changes graph from the Nx engine, and implement version bumps accordinly.

**Comment by FrozenPandaz** [comment]
You can do this with `nx:run-commands` or a custom executor.

Perhaps someone wants to write a plugin?
