### ISSUE TITLE
Expose command line utilities

### ISSUE THREAD

**Issue by comatory** [nrwl/nx#13650]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Currently functions such as `parseFiles` or `getProjectRoots` located in `nx/src/utils/command-line-utils.ts` are not exposed.

## Motivation
I need to expose information for my own tooling outside of NX and it would be great to re-use the implementation.

## Suggested Implementation
Create public utilities package.

## Alternate Implementations
Create wrapper NPM lib that calls CLI NX commands and parses them into data structures.

**Comment by FrozenPandaz** [comment]
`getProjectRoots` is a really simple function you're welcome to copy it:

```ts
export function getProjectRoots(
  projectNames: string[],
  { nodes }: ProjectGraph
): string[] {
  return projectNames.map((name) => nodes[name].data.root);
}
```

All of the information would be available in `createProjectGraphAsync()`. The data type is public API so if anything changes, it would be a breaking change and you would know about it.

As for `parseFiles()`, it is basically `git` parsing. There are probably `git` js sdks such as https://www.npmjs.com/package/simple-git that would be better for providing utils.

What exactly, would you like to do with this information?
