### ISSUE TITLE
tslib class-transformer @nestjs/platform-socket.io is not included in generated package.json

### ISSUE THREAD

**Issue by ubeytdemirr** [nrwl/nx#13659]
### Current Behavior

When I build my nestjs application with nx to ship it to elasticbeanstalk via pulumi, it does not include follwing packages in generated package.json

- tslib
- class-transformer
- @nestjs/platform-socket.io

I'm using pnpm as package manager.

### Expected Behavior

I was expecting all dependencies would be bundled if I don't use "generatePackageJson": true

Or If I use it they would show up in package.json.

My current workaround is adding them into the main.ts file

### Steps to Reproduce

1. Create Nestjs API with NX Console ("@nrwl/nest": "15.2.4") 
2. Use the following packages:  tslib,class-transformer, @nestjs/platform-socket.io
3. Set generatePackageJson:true in project.json
4. Run build command with production config.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : darwin arm64
   npm  : 9.1.3
   
   nx : 15.2.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.2.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.4
   @nrwl/js : 15.2.4
   @nrwl/linter : 15.2.4
   @nrwl/nest : 15.2.4
   @nrwl/next : Not Found
   @nrwl/node : 15.2.4
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.2.4
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.2.4
   @nrwl/web : 15.2.4
   @nrwl/webpack : 15.2.4
   @nrwl/workspace : 15.2.4
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @nx-plus/docusaurus: 14.1.0
   	 @wanews/nx-typescript-project-references: 0.21.0
   	 @nx-tools/nx-prisma: 4.0.1
   	 @trumbitta/nx-plugin-unused-deps: 1.12.1
   	 @wanews/nx-pulumi: 0.26.0
```

**Comment by ubeytdemirr** [comment]
If the problem is unrelated to nx but if you know how to fix that, we can move the topic here:https://stackoverflow.com/questions/74704282/how-do-i-ensure-that-tslib-class-transformer-and-nestjs-platform-socket-io-ar  

thanks :)

**Comment by swcm-mpilz** [comment]
Probably related to the issue we had #13625 - can you confirm that `generatePackageJson` works fine with nx `15.2.1`?
