### ISSUE TITLE
how to use nx to separate env when build iOS and android app?

### ISSUE THREAD

**Issue by frankA10019** [nrwl/nx#13652]
## Description
There is a api connect library in my project. I want to use different api address according my environment. I only can find some article to do this with react native project, but not do this combine with nx.

## Motivation
Many user use nx to build their react native project. It is a big advantage if there is some easy approach to complete this feature.
Thanks.

**Comment by xiongemi** [comment]
@nx/react-native does not support env variable out of the box.
you can use library such as react-native-config to add env variable.

as for separate env for ios and android, react native has a constant called Platform: https://reactnative.dev/docs/platform#os

```
import {Platform} from 'react-native';
```

you can do something like:
```
export function getVariable() {
  if (Platform.OS  === 'ios') return ' ...';
  if (Platform.OS === 'android') return '...';
}
```
