### ISSUE TITLE
Nuxt 3 app: Cannot overwrite directory 'my-project/node_modules/.cache/nx/...' with non-directory

### ISSUE THREAD

**Issue by mklueh** [nrwl/nx#13684]
### Current Behavior

Build of one of my Nuxt 3 applications fails with this error. 

Nuxt has a static build mode by executing the `generate` script and a normal SSR / CSR mode by running `build`.

While `generate` seems to create a dist shortcut that is pointing to `.output/public`, which somehow clashes with Nx caching when executing `build` afterwards, where the `dist` is created as a real directory.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/1553757/206120995-efafd9e6-6c1f-40e6-a53f-02ac675ac85b.png">

https://nuxt.com/docs/guide/concepts/server-engine#standalone-server

For some reason I could not reproduce yet, it fails likely with the same error when I run `yarn install` in GitHub CI. Sadly the error logs are not displayed in stderr but created as a file I do not know how to access but I assume it is the same issue

### Expected Behavior

Threating shortcuts as shortcuts, and not as directories if possible or maybe ignore them entirely.

### Steps to Reproduce

1. Create an Nx workspace
2. Add a Nuxt 3 application by running
3. Run `nx run your-app:generate --verbose`
4. Run `nx run your-app:build --verbose`

### Nx Report

```shell
Node : 16.18.1
   OS   : linux x64
   yarn : 3.3.0

   nx : 15.2.4
   @nrwl/angular : 15.2.4
   @nrwl/cypress : 15.2.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.4
   @nrwl/js : 15.2.4
   @nrwl/linter : 15.2.4
   @nrwl/nest : Not Found
   @nrwl/next : 15.2.4
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.2.4
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.2.4
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.2.4
   @nrwl/web : 15.2.4
   @nrwl/webpack : 15.2.4
   @nrwl/workspace : 15.2.4
   typescript : 4.9.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @jscutlery/semver: 2.29.0
         @nxext/vite: 15.0.0
         @nxtend/capacitor: 13.0.0
         @nxtend/firebase: 12.1.0
         @trumbitta/nx-plugin-openapi: 1.12.1
         @trumbitta/nx-plugin-unused-deps: 1.12.1
         nx-electron: 13.2.1
```

### Failure Logs

```shell
>  NX   Cannot overwrite directory '/home/user/workspace/my-project/node_modules/.cache/nx/b12c071b889025df7bdc393ba3dc82d86a854661663668c300604e64c199b965/outputs/apps/demo/dist' with non-directory '/home/user/workspace/my-project/apps/demo/dist'.


Error: Cannot overwrite directory '/home/user/workspace/my-project/node_modules/.cache/nx/b12c071b889025df7bdc393ba3dc82d86a854661663668c300604e64c199b965/outputs/apps/demo/dist' with non-directory '/home/user/workspace/my-project/apps/demo/dist'.
    at /home/user/workspace/my-project/node_modules/nx/node_modules/fs-extra/lib/util/stat.js:55:19
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

```
```


### Additional Information

_No response_

**Comment by agdimech** [comment]
I also am experiencing a similar issue.
