### ISSUE TITLE
Libs with routing and apps are not created

### ISSUE THREAD

**Issue by YonatanKra** [nrwl/nx#1368]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed
- [ x ] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

I expect `ng g lib my-lib-name` to create a lib and `ng g app my-app-name` to create an app.

## Current Behavior

When trying to create a lib with routing it doesn't create the lib
When trying to create an APP it doesn't create the app (with no relation to with or without routing).

## Failure Information (for bugs)

It fails silently without any message.
![image](https://user-images.githubusercontent.com/6459899/58175576-1da23e00-7ca9-11e9-970c-a4ae8f5a1a49.png)

![image](https://user-images.githubusercontent.com/6459899/58175634-3dd1fd00-7ca9-11e9-9ff4-9c97611c8fe4.png)

### Steps to Reproduce

I have no idea. It used to work, and not it doesn't work.

### Context

- version of Nx used - 7.8.6
```
Angular CLI: 7.3.6
Node: 10.15.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, core, elements, forms, http
... platform-browser, platform-browser-dynamic, router, upgrade

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.6
@angular-devkit/build-angular      <error>
@angular-devkit/build-ng-packagr   <error>
@angular-devkit/core               7.3.6
@angular-devkit/schematics         7.3.6
@angular/cdk                       7.3.7
@angular/cli                       7.3.6
@angular/compiler-cli              7.2.2
@angular/flex-layout               7.0.0-beta.24
@angular/language-service          7.2.2
@angular/material                  7.3.7
@ngtools/json-schema               1.1.0
@schematics/angular                7.3.6
@schematics/update                 0.13.6
ng-packagr                         4.7.1
rxjs                               6.5.2
typescript                         3.1.6
```

### Failure Logs

Is there a way to generate a log to get the failure? As you can see in the images, it just shows nothing and doesn't create anything.

**Comment by vsavkin** [comment]
@YonatanKra could you try creating a new workspace using `npx --ignore-existing create-nx-worspace myworkspace` and then try creating an app in it?

**Comment by YonatanKra** [comment]
@vsavkin for some reason I get this:
```
npm ERR! code E404
npm ERR! 404 Not Found: create-nx-worspace@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yonatan.kr\AppData\Roaming\npm-cache\_logs\2019-05-26T14_46_42_310Z-debug.log
Install for create-nx-worspace@latest failed with code 1
```
When I try to create the workspace. Any idea what can cause that? 
I've tried several internet connections to make sure it's not a firewall issue of some kind. I also tried to install the `create-nx-workspace` globally which worked. It's just that using the command itself fails for some reason.

**Comment by YonatanKra** [comment]
I'm getting this error:
```
c:\projects>npx --ignore-existing create-nx-workspace WM.Editor
npx: installed 53 in 9.482s
Creating a sandbox with Nx...
warning ..\..\..\..\package.json: No license field
[#############################################################################################################] 702/702
ng new "WM.Editor" --collection=@nrwl/schematics
? Which stylesheet format would you like to use? SCSS   [ http://sass-lang.com   ]
? What is the npm scope you would like to use for your Nx Workspace?
? What to create in the new workspace (You can create other applications and libraries at any point using 'ng g') empty
            [an empty workspace]
ERROR! wm.editor/angular.json already exists.
ERROR! wm.editor/nx.json already exists.
ERROR! wm.editor/package.json already exists.
ERROR! wm.editor/README.md already exists.
ERROR! wm.editor/tsconfig.json already exists.
ERROR! wm.editor/tslint.json already exists.
ERROR! wm.editor/.editorconfig already exists.
ERROR! wm.editor/.gitignore already exists.
ERROR! wm.editor/.prettierignore already exists.
ERROR! wm.editor/.prettierrc already exists.
ERROR! wm.editor/libs/.gitkeep already exists.
ERROR! wm.editor/tools/tsconfig.tools.json already exists.
ERROR! wm.editor/tools/schematics/.gitkeep already exists.
The Schematic workflow failed. See above.
Command failed: "C:\Users\yonatan.kr\AppData\Local\Temp\tmp-123604m30C5VBqIOs"\node_modules\.bin\ng new "WM.Editor" --collection=@nrwl/schematics
```
Is there an issue with `ignore-existing`?

**Comment by vsavkin** [comment]
@YonatanKra I think it's telling you that you are trying to create it in a folder where this project already exists.

**Comment by vsavkin** [comment]
I'm going to close this. If the problem present, please reopen the issue. Thank you!
