### ISSUE TITLE
[@nrwl/react/plugins/storybook] Doesn't apply css variables

### ISSUE THREAD

**Issue by robertn702** [nrwl/nx#13699]
### Current Behavior

When using Storybook with a UI library, [NextUI](https://nextui.org/) in this case, which uses [Stitches](https://stitches.dev/) for CSS-in-JS. CSS variables are correctly applied from components definitions, but not when dynamically setting them using the component's `css` prop.

I have verified that the CSS variables are correctly applied when using NextUI library in Storybook without NX. The components also work correctly when only using the UI library within the NextJS application. This leads me to believe that `@nrwl/react/plugins/storybook` is causing the issue.

Example css output

![image](https://user-images.githubusercontent.com/8119609/206308547-445e2019-0aaa-4d78-b76c-47b6c791c414.png)

### Expected Behavior

Expected output should be the following:

![image](https://user-images.githubusercontent.com/8119609/206309541-0f99fb07-b2da-4a17-9aef-b2007d90d628.png)

### Github Repo

https://github.com/robertn702/nx-nextui-storybook-test

### Steps to Reproduce

1. Run `yarn install`
2. Run `yarn nx run ui:storybook`
3. View Storybook component `PulseIcon`

### Nx Report

```shell
nx : 15.3.0
@nrwl/angular : Not Found
@nrwl/cypress : 15.3.0
@nrwl/detox : Not Found
@nrwl/devkit : 15.3.0
@nrwl/esbuild : Not Found
@nrwl/eslint-plugin-nx : 15.3.0
@nrwl/expo : Not Found
@nrwl/express : Not Found
@nrwl/jest : 15.3.0
@nrwl/js : 15.3.0
@nrwl/linter : 15.3.0
@nrwl/nest : Not Found
@nrwl/next : 15.3.0
@nrwl/node : Not Found
@nrwl/nx-cloud : 15.0.2
@nrwl/nx-plugin : Not Found
@nrwl/react : 15.3.0
@nrwl/react-native : Not Found
@nrwl/rollup : 15.3.0
@nrwl/schematics : Not Found
@nrwl/storybook : 15.3.0
@nrwl/web : 15.3.0
@nrwl/webpack : 15.3.0
@nrwl/workspace : 15.3.0
typescript : 4.8.4
```

**Comment by robertn702** [comment]
@mandarini Thanks for the reply. I ran `nx migrate latest` and retried. I'm still seeing the same issue.

Here is the branch with updates: https://github.com/robertn702/nx-nextui-storybook-test/tree/nx-migrate-latest
main.js: https://github.com/robertn702/nx-nextui-storybook-test/blob/nx-migrate-latest/libs/ui/.storybook/main.ts

**Comment by mandarini** [comment]
So, @robertn702 ! I just migrated to the latest, ran migrations, and now it shows up as red. So it seems to me that the CSS is getting applied?
![Screenshot 2023-01-19 at 12 56 24 PM](https://user-images.githubusercontent.com/6603745/213424651-f48db188-980a-4f43-841d-cd153c59bbae.png)

![Screenshot 2023-01-19 at 12 56 37 PM](https://user-images.githubusercontent.com/6603745/213424690-67d3c9a6-d6b3-4f81-bdc5-be014c10c50b.png)

[Here are my changes](https://github.com/robertn702/nx-nextui-storybook-test/pull/1).

**Comment by robertn702** [comment]
Thank you for investigating this and resolving quickly.
