### ISSUE TITLE
Generating react library failure - Required package xxx is missing. 

### ISSUE THREAD

**Issue by mwarger** [nrwl/nx#13697]
### Current Behavior

Currently, running this command fails for me after initializing an existing project, even after the dependency has been installed.

`npx nx generate @nrwl/react:library mylib --no-interactive --dry-run --verbose`

See the reproduction steps below.

However, after installing the missing jest dependency using the command provided, the library command still does not work.

The trick is, moving this dependency from devDependencies to dependencies in the package.json and reinstalling, fixes the issue!

It is somehow finding the dependency when listed in the dependencies section but not when it's listed as a devDependency, and the suggested command to install the dependency is what places it as a devDependency (the `-D` flag).

### Expected Behavior

This should work and output the expected dry-run command.

### Github Repo

WIP

### Steps to Reproduce

1. Migrate an existing non-nx project to NX using `npx nx@latest init` (I am not sure if this is specific to existing NX projects or only "migrated" ones)
2. Attempt to create react library - `npx nx generate @nrwl/react:library mylib --no-interactive --dry-run --verbose`
3. See the following output:
```
Generating @nrwl/react:library


 >  NX   Required package @nrwl/jest@15.3.0 is missing. Run "npm install -D @nrwl/jest@15.3.0", and then try again.
```

4. Run the command to install the dependency.
5. Try running the command again after the dev dependency is installed, and get the same error.

Note: IF you now move the dependency from the dev section to the dependencies section, and reinstall, the issues goes away.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : darwin arm64
   npm  : 8.11.0
   
   nx : 15.3.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.3.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.3.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.3.0
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.3.0
   typescript : 4.9.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nrwl/vite: 15.3.0
```

**Comment by mandarini** [comment]
I'm pretty sure this is fixed, and I can no longer reproduce. Can you please retry with the latest version? I will be closing this issue now, but if you retry with latest and you can reproduce, please ping me and I will reopen! Thanks! :D
