### ISSUE TITLE
Cannot find module when executing Generator

### ISSUE THREAD

**Issue by bosycom** [nrwl/nx#13696]
### Current Behavior

After upgrading to NX 15.3.0 my generators cannot be executed anymore.

### Expected Behavior

The generator should be invoked successfully

### Steps to Reproduce

 Not sure if this is a mistake on my end, so I quickly created a fresh nx workspace to test it out following along https://nx.dev/nx/create-nx-workspace:

`yarn create nx-workspace`
integrate monorepo
repository name temp
application name tempapp
default stylesheet css

I followed https://nx.dev/recipes/generators/local-generators to create a plugin and generator

`npm install @nrwl/nx-plugin@15.3.0`
`nx g @nrwl/nx-plugin:plugin my-plugin`
`nx generate @nrwl/nx-plugin:generator my-generator --project=my-plugin`

Trying to execute the generator results in an error:

`
nx generate @temp/my-plugin:my-generator mylib --verbose
`

```
Unable to find local plugin [ 'libs\\my-plugin\\src\\index.ts' ] Map(4) {
  'apps/my-plugin-e2e' => 'my-plugin-e2e',
  'apps/tempapp' => 'tempapp',
  'apps/tempapp-e2e' => 'tempapp-e2e',
  'libs/my-plugin' => 'my-plugin'
}

NX   Unable to resolve @temp/my-plugin:my-generator.

   Unable to resolve local plugin with import path @temp/my-plugin

Error: Unable to resolve @temp/my-plugin:my-generator.
Unable to resolve local plugin with import path @temp/my-plugin
    at Workspaces.readGenerator (C:\code\temp\temp\node_modules\nx\src\config\workspaces.js:156:19)
    at Object.<anonymous> (C:\code\temp\temp\node_modules\nx\src\command-line\generate.js:212:92)
    at Generator.next (<anonymous>)
    at fulfilled (C:\code\temp\temp\node_modules\tslib\tslib.js:115:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Using TS 4.9.4
Did I miss something or is this really a bug? I noticed that libs/my-plugin/src/index.ts is empty, but maybe that is supposed to be like that!?

### Nx Report

```shell
Node : 18.12.0
OS   : win32 x64
npm  : 8.19.2

nx : 15.3.0
@nrwl/angular : Not Found
@nrwl/cypress : 15.3.0
@nrwl/detox : Not Found
@nrwl/devkit : 15.3.0
@nrwl/esbuild : Not Found
@nrwl/eslint-plugin-nx : 15.3.0
@nrwl/expo : Not Found
@nrwl/express : Not Found
@nrwl/jest : 15.3.0
@nrwl/js : 15.3.0
@nrwl/linter : 15.3.0
@nrwl/nest : Not Found
Local workspace plugins:
	 @temp/my-plugin
---------------------------------------
Community plugins:
```

**Comment by mottet** [comment]
Thanks for the workaround. I had the same issue with version 15.3.0. No issue with version 15.2.0.

**Comment by mottet** [comment]
After investigation I found that it was a Windows path format related issue. A fix to the problem is already merge https://github.com/nrwl/nx/pull/13801 so I guess the issue should be gone in close futur release :)

**Comment by bosycom** [comment]
Thanks @mottet for investigating!

For everyone who cannot wait for the fixed version, you can simply patch the src file in `node_modules/nx/src/utils/nx-plugin.js` like that which has fixed it for me:

Add new line 14
```javascript
const { normalizePath } = require("./path");
```

Change line 134:
```javascript
const possiblePaths = (_a = tsConfigPaths[importPath]) === null || _a === void 0 ? void 0 : _a.map((p) => normalizePath(path.relative(root, path.join(root, p))));
```
