### ISSUE TITLE
Nest.js applications not workin in 15.3.0

### ISSUE THREAD

**Issue by phihochzwei** [nrwl/nx#13701]
### Current Behavior

While starting any of our Nest.js applications, they fail with an error 'Cannot find module 'nx/src/utils/create-package-json''

### Expected Behavior

That they start :)

### Steps to Reproduce

1. Take a 15.2.4 version project with Nest.js-applications
2. Run nx migrate latest
3. Run npm install
4. Start any of the Nest.js applications

### Nx Report

```shell
Since I had to revert the version this is unfortunately not at hand
```

**Comment by div-cowboy** [comment]
@MaxKless any word on upcoming solutions for this? What packages can be downgraded in the meantime?

**Comment by nartc** [comment]
@phihochzwei thank you for reporting the issue and providing the reproduce steps. Unfortunately, I couldn't reproduce the issue. I've tested with:
- Generate a `latest` workspace with NestJS applications
- Generate a `15.3.0` workspace with NestJS applications then migrate to `latest`
- Generate a `15.2.4` workspace with NestJS applications then migrate to `15.3.0`
- Generate a `15.2.4` workspace with NestJS applications then migrate to `latest`

In all 4 cases, both `nx serve` and `nx build` work fine **pre** and **post** migration. The commands used are as follow

```shell
npx create-nx-workspace@<version> my-org
- Integrated
- Nest preset

cd my-org # runs nx serve and nx build
npx nx migrate <to-version>
npm i
nx serve
nx build
```

If you have other reproduce steps, please let us know. Additionally, if you have a reproduce repo, that'd be much better. Thank you
