### ISSUE TITLE
Vite application can't use prisma if it's imported via a library

### ISSUE THREAD

**Issue by jackall3n** [nrwl/nx#13704]
### Current Behavior

For projects using the `vite` bundler and `prisma` it's not possible to use enums within a `vite` application _if_ it's imported using a library.

### Example 
```typescript
/apps
    /my-vite-app
        /main.tsx // import { UserType } from '@test-nx-vite/my-vite-lib'
/libs
    /my-vite-lib
        /index.ts // (export * from `@prisma/client`)
```

### Error

> .../test-nx-vite/libs/my-vite-lib/src/index.ts' does not provide an export named 'UserType'

### Full Demo Repository

I've created an example repository here and implementation: https://github.com/jackall3n/test-nx-vite/blob/master/apps/my-vite-app/src/app/app.tsx

### Additional Information

* It works if you import directly from `@prisma/client`.
* It works in `webpack` bundled applications.
* I am using `pnpm`

### Expected Behavior

The `vite` application should run as expected while importing from a library and directly from a package.

### Github Repo

https://github.com/jackall3n/test-nx-vite

### Steps to Reproduce

1. Create NX Workspace
2. Generate `react` application with `vite` bundler
3. Generate `workspace` or `react` library (using `vite` bundler for the latter)
4. Setup `prisma` and export contents from `@prisma/client` from your library.
5. Attempt to use `prisma` objects in your `React` code such as an enum.

### Nx Report

```shell
Node : 16.13.0
   OS   : darwin x64
   pnpm : 7.5.0
   
   nx : 15.3.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.3.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.3.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.3.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.3.0
   @nrwl/webpack : 15.3.0
   @nrwl/workspace : 15.3.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nrwl/vite: 15.3.0
```

### Failure Logs

```shell
.../test-nx-vite/libs/my-vite-lib/src/index.ts' does not provide an export named 'UserType' (at app.tsx:4:10)
```

**Comment by jaysoo** [comment]
This is an issue with Vite it seems. See this plain Vite setup: https://github.com/jaysoo/vite-prisma-barrel-exports/tree/main

**Comment by jackall3n** [comment]
Thanks @jaysoo. For various reasons I can't import directly, but I'll raise with them.

**Comment by baptisteArno** [comment]
@jackall3n, have you found a solution? I'm hitting the exact same issue.

**Comment by jackall3n** [comment]
Sorry, I've not made any more progress on this issue @baptisteArno
