### ISSUE TITLE
I wish the remote cache prompt more eye-catching

### ISSUE THREAD

**Issue by lmk123** [nrwl/nx#13711]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I wish the remote cache prompt more eye-catching.
## Motivation

When I run test code, there are some codes that run fine locally, but report errors in CI (example: when using headful chrome in GitHub Actions.) .

However, since I'm using @nx/cloud, this error is only thrown the next time the cache is not hit. It often took me a while to figure out that the last time it worked was because I was using a locally generated remote cache.

The existing `[remote cache]` flag is very unobtrusive in a large piece of output. In particular, in GitHub Actions, all of the project's output is displayed without being collapsed.

I'd like to see a more prominent alert for remote cache, so that when there is a problem in CI, I can quickly associate it with the cache from the logs.
## Suggested Implementation

Make the font color of the `[remote cache]` tips darker and bolder and the font size larger.

Provide information at the end of the output log so that I can know which commands used the cache and which did not.

The current information is not detailed:

```
>  NX   Successfully ran target test:ci for 7 projects

   Nx read the output from the cache instead of running the command for 7 out of 14 tasks.

   View logs and investigate cache misses at https://cloud.nx.app/runs/…………
```

**Comment by AgentEnder** [comment]
I'm going to merge this request with #14471, while not entirely the same I think they go hand in hand.

One of the key pieces here (larger font size) is also not possible in the terms of console logs.
