### ISSUE TITLE
[createGlobPatternsForDependencies] WARNING: There was no ProjectGraph available to read from, returning an empty array of glob patterns

### ISSUE THREAD

**Issue by GeorgeKnap** [nrwl/nx#13713]
### Current Behavior

NX 15.3.0
freshly generated integrated repo with Angular app by command
`npx create-nx-workspace@latest`
 and generated tailwind support using the generator 
`npx nx g @nrwl/angular:setup-tailwind my-app`

when run `nx serve` there is a console warning
`[createGlobPatternsForDependencies] WARNING: There was no ProjectGraph available to read from, returning an empty array of glob patterns`

As a result tailwind does not work for components in libraries, because `createGlobPatternsForDependencies` return empty array.

While attempting to debug I got to a file 
`find-project-for-path.js`  where a function `findProjectForPath` attempts to get path `.` from the `projectRootMap` which is not there and the code throws error..

### Expected Behavior

no errors

### Steps to Reproduce

1.

### Nx Report

```shell
Node : 18.10.0
   OS   : win32 x64
   npm  : 9.1.2

   nx : 15.3.0
   @nrwl/angular : 15.3.0
   @nrwl/cypress : 15.3.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.0
   @nrwl/workspace : 15.3.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by luchsamapparat** [comment]
It's a Windows-related issue. I already mentioned this here:

https://github.com/nrwl/nx/pull/13362#issuecomment-1339649942

**Comment by GeorgeKnap** [comment]
NX version 15.2.4 is fine so this problem occurs only in 15.3.0.  Tested on Win 11

**Comment by HaasStefan** [comment]
Is there a workaround for 15.3.0?

**Comment by morbargig** [comment]
This problem happened to me also
I was upgrade from nx 15.1.1 to 15.3.3

Someone has a fix for ~15.3.0 or any version of angular 15 ?

**Comment by maartencardinaels** [comment]
as a temporary workaround on Windows we created this patch (by using[ patch-package](https://www.npmjs.com/package/patch-package)) for file

`node_modules/@nrwl/workspace/src/utilities/generate-globs.js`:

```
-   const filenameRelativeToWorkspaceRoot = (0, path_1.relative)(workspace_root_1.workspaceRoot, dirPath);
+   const filenameRelativeToWorkspaceRoot = (0, path_1.relative)(workspace_root_1.workspaceRoot, dirPath).replaceAll('\\','/');
```

**Comment by roldengarm** [comment]
In my case, it seems to have broken Tailwind, some of the styles are no longer applied, e.g. `gap-4`.
Some other styles still work fine.

I'll stay at Angular 14 for now.
