### ISSUE TITLE
Affected doesn't respect semantic versionning

### ISSUE THREAD

**Issue by thollander** [nrwl/nx#13720]
### Current Behavior

Given an app that looks like this : 

<img width="1493" alt="image" src="https://user-images.githubusercontent.com/23191482/206552426-ac9b2636-cea1-474f-bd1d-dc9bb187058b.png">

with : 
- `@thollander/myapp` depending on `@thollander/mylib@^1.0.0` (note the caret `^` here)
- `@thollander/myapp2` depending on `@thollander/mylib@1.0.0` (note the fixed version here)

After bumping `@thollander/mylib` from `1.0.0` to `1.0.1`, I get while running `nx print-affected` : 

```json
{
  "tasks": [],
  "projects": [
    "@thollander/mylib",
    "@thollander/myapp2",
    "@thollander/myapp"
  ],
  "projectGraph": {
    "nodes": [
      "@thollander/myapp2",
      "@thollander/myapp",
      "@thollander/mylib"
    ],
    "dependencies": {
      "@thollander/myapp2": [
        {
          "source": "@thollander/myapp2",
          "target": "@thollander/mylib",
          "type": "static"
        }
      ],
      "@thollander/myapp": [
        {
          "source": "@thollander/myapp",
          "target": "@thollander/mylib",
          "type": "static"
        }
      ],
      "@thollander/mylib": []
    }
  }
}
```

### Expected Behavior

_I don't know if it's a bug or a new feature that could be added but :_

As `@thollander/myapp2` depends on a fixed version `@thollander/mylib@1.0.0`, I would expect `@thollander/myapp2` not to be in the "affected list" : it's not really affected until I will bump the version of `@thollander/mylib` inside its package. 

I understand that it is actually because `myapp2` has `mylib` in the dependencies, but I would want to be able having only my packages respecting semver inside the affected projects. 
Is it somehow achievable ? 

### Github Repo

https://github.com/thollander/nx-semver-link

### Steps to Reproduce

1. `git clone https://github.com/thollander/nx-semver-link`
2. `cd nx-semver-link`
3. `npm i`
4. `git checkout bump`
5. `nx print-affected`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.18.0
   OS   : darwin x64
   npm  : 8.19.2

   nx : 15.3.0
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : Not Found
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : Not Found
   typescript : Not Found
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by FrozenPandaz** [comment]
Nx is isn't really meant to be able to tell when `^1.0.0` results in a different installed version just from publishing a file.

I understand that both of these packages are in your workspace.

But setting the version to `1.0.0` or `^1.0.0` in your `package.json` actually installs those packages from the npm registry.

The easier (and safer) way to do this is to have a `package-lock.json` or equivalent which will codify the installed dependencies into a file. Nx will then parse the lockfile to see if your installed dependencies have changed. Then the `affected` logic will work as expected.

Does this work for you?

**Comment by thollander** [comment]
Thanks for your swift answer. 

Not sure what you mean by "codify the installed dependencies" but I actually do have a `package-lock.json` in my project : https://github.com/thollander/nx-semver-link/blob/bump/package-lock.json 

But it's still printing all the projects in `affected` : 

```
❯ nx affected --target=test

    ✔  nx run @thollander/mylib:test
    ✔  nx run @thollander/myapp:test  [existing outputs match the cache, left as is]
    ✔  nx run @thollander/myapp2:test  [existing outputs match the cache, left as is]

 >  NX   Successfully ran target test for 3 projects (21ms)
```

So it doesn't seem to work as I would like to.

**Comment by thollander** [comment]
_Removing stale, still an issue for us._

Do you need more info that could help on this topic ?

**Comment by clemenscodes** [comment]
Having a similar issue. Modifying the package.json of a project in any way, even if no version or dependency changed, will mark the project as affected and thus its dependend projects. This is the case even if I explicitly set the inputs to ignore package.json updates. I would like to be able to bump the versions of my projects without it causing invalidated caches.
