### ISSUE TITLE
Nx affected/graph doesn`t work without root config in project json

### ISSUE THREAD

**Issue by anastasia-anisimova** [nrwl/nx#13727]
### Current Behavior

After upgrade to 14.8.6 from 13 nx version the root field in project.json was removed by convert-to-nx-project schematic.
And after nx affected/nx graph not working (graph is empty).
I know that this schematic should add the root field itself, but it doesn't work for me. 

### Expected Behavior

Nx graph is correct
(Root field doesn`t removed from project config or schematic adds this field)

### Steps to Reproduce

We have a separate folder with libs/projects configs
for example:
```
 - nx-configs (main folder)
   - libs
     - test
         project.json
   - projects
     - test2
         project.json

```
In angular.json:
```
...   
"lib-test": "nx-configs/libs/test",   
"test2": "nx-configs/projects/test2"   
...  
```
project.json for test
```

{
  "name": "lib-test",
  "projectType": "library",
  "targets": {
......
    }
  }
}

```

project,json for test2
```

{
  "name": "test2",
  "projectType": "application",
  "targets": {
......
    }
  }
}
```

1. Test2 application uses test library
2. Change library code
3. Run yarn nx affected --target=test (result 0 affected)
4. Run yarn nx graph (graph without dependencies between test and test2)
5. If add "root" field to configs - everything will be ok (graph is correct)
6. But if run convert-to-nx-project schematic - root field will be remove from all project.json and it won't work again.

### Nx Report

```shell
Node : 16.13.1                                           
   OS   : win32 x64                                         
   yarn : 3.1.1                                             
   
   nx : 14.8.6
   @nrwl/angular : 14.8.6
   @nrwl/cypress : 14.8.6
   @nrwl/detox : 14.8.6
   @nrwl/devkit : 14.8.6
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.6
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.6
   @nrwl/js : 14.8.6
   @nrwl/linter : 14.8.6
   @nrwl/nest : 14.8.6
   @nrwl/next : Not Found
   @nrwl/node : 14.8.6
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.8.6
   @nrwl/react-native : 14.8.6
   @nrwl/rollup : 14.8.6
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.6
         @ngneat/transloco: 3.2.0
         @ngrx/effects: 14.0.2
         @ngrx/store: 14.0.2
         @ngrx/store-devtools: 14.0.2
         @nguniversal/express-engine: 14.2.0
         @ngx-pwa/local-storage: 13.0.5
         angular-calendar: 0.29.0
         ng-zorro-antd: 14.1.0
         ngx-bootstrap: 9.0.0
         ngx-extended-pdf-viewer: 14.5.3
         @nguniversal/builders: 14.2.0
         @storybook/angular: 6.5.12
         ng-mocks: 12.5.1
```

**Comment by AgentEnder** [comment]
It would also help if you could provide a reproduction for this, as its behaviour that I've not seen before.

**Comment by anastasia-anisimova** [comment]
@AgentEnder Hi! I tried to update nx (15.1), but i have the same problem
Can you explain please how nx builds a dependency graph now? (without a root field in project.json file)
In the weekend I will try to create stackblitz reproduction

**Comment by AgentEnder** [comment]
The dependency / project graph contains a root property, its added based on the location of the project.json at runtime when reading in the configuration.

**Comment by anastasia-anisimova** [comment]
Thanks, I guess I understood the reason of my problem: root property added based on the location of project.json config  
But in my case project.json config is located in separate folder, not in the project folder  
that is why root properties are incorrect for my case  
The reason why I have a separate folder for configs - https://github.com/nrwl/nx/issues/9860 (optimized docker build process)  

And now I don't understand how to fix it...
