### ISSUE TITLE
`@nrwl/expo` expo peer dep out of sync

### ISSUE THREAD

**Issue by hiddenist** [nrwl/nx#13722]
### Current Behavior

Running `npm install` after `nx migrate latest` results in a peer dependency issue.

https://github.com/nrwl/nx/blob/15.3.0/packages/expo/package.json#L47
https://github.com/nrwl/nx/blob/42618c7e1dc6e14dc9f1eabb636de0023bcd8ba2/packages/expo/package.json#L46-L48

https://github.com/nrwl/nx/blob/15.3.0/packages/expo/src/utils/versions.ts#L3
https://github.com/nrwl/nx/blob/42618c7e1dc6e14dc9f1eabb636de0023bcd8ba2/packages/expo/src/utils/versions.ts#L3

### Expected Behavior

The version of `expo` that's installed matches the peer dependency version in the `@nrwl/expo` package.

### Steps to Reproduce

1. Upgrade to `@nrwl/expo` at 15.3.0
2. Run `npm install` without using `--legacy-peer-deps` or `--force`
3. See peer dependency issues

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : darwin arm64
   npm  : 8.11.0
   
   nx : 15.3.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.3.0
   @nrwl/detox : 15.3.0
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.0
   @nrwl/expo : 15.3.0
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : 15.3.0
   @nrwl/next : Not Found
   @nrwl/node : 15.3.0
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.3.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.3.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.3.0
   @nrwl/webpack : 15.3.0
   @nrwl/workspace : 15.3.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @prisma-utils/prismerge: 1.7.0
```

### Failure Logs

```shell
npm ERR! Could not resolve dependency:
npm ERR! peer expo@"^46.0.16" from @nrwl/expo@15.3.0
npm ERR! node_modules/@nrwl/expo
npm ERR!   dev @nrwl/expo@"15.3.0" from the root project
```

**Comment by xiongemi** [comment]
i believe this issue has been resolved. closing it.
