### ISSUE TITLE
Unable to resolve local plugin after upgrade

### ISSUE THREAD

**Issue by maartencardinaels** [nrwl/nx#13736]
### Current Behavior

We upgraded Nx from 15.0.10 to 15.3.0. We have a local plugin in our repo. Since the upgrade this plugin can't be retrieved anymore resulting in the error message `Unable to resolve local plugin with import path xyz` when executing Nx commands.

### Expected Behavior

The local plugin should correctly be retrieved.

### Github Repo

[repro](https://github.com/nrwl/nx/files/10205264/repro.zip)

### Steps to Reproduce

 1. Have an Nx < 15.3.0 workspace with a local plugin
 2. Migrate to 15.3.0
 3. Try to execute Nx commands

### Nx Report

```shell
Node : 16.15.0
   OS   : win32 x64
   yarn : 1.22.15

   nx : 15.3.0
   @nrwl/angular : 15.3.0
   @nrwl/cypress : 15.3.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.3.0
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 15.3.0
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.3.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.3.0
   @nrwl/web : 15.3.0
   @nrwl/webpack : 15.3.0
   @nrwl/workspace : 15.3.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
         @grizzly/nx-plugin
   ---------------------------------------
   Community plugins:
         @auth0/auth0-angular: 1.11.0
         @cumul.io/ngx-cumulio-dashboard: 3.0.5
         @ngneat/edit-in-place: 1.6.1
         @ngneat/transloco: 4.1.1
         @ngrx/component: 14.3.2
         ng2-charts: 4.0.1
         single-spa-angular: 7.1.0
         @compodoc/compodoc: 1.1.19
         @ngneat/spectator: 12.0.1
         @storybook/angular: 6.5.13
```

### Failure Logs

```shell
Unable to resolve local plugin with import path xyz
```

### Additional Information

When debugging and comparing [nx-plugin.ts](https://github.com/nrwl/nx/blob/master/packages/nx/src/utils/nx-plugin.ts) to an older version we noticed that relative paths are being used now to retrieve plugins.

By referring to the screenshot below, however we noticed too that:

`tsConfigPath` (1) is being used to find (2) a project for that path based on `projectRootMappings`. However, if you look at the values (3) of `projectRootMappings`, you see that the project root is being used as the key and not the file path, resulting in the plugin project not being retrieved correctly.

![image](https://user-images.githubusercontent.com/64408852/206734698-e58a2717-ef7b-47c4-9e91-af9e544a9344.png)

**Comment by rm-aclark** [comment]
We are also encountering this issue. I believe it is because the path.relative (a few lines up from point 1) converts the string to OS format, a backslash on windows, making the subsequent comparison fail.
If I add a string replace '\\' to '/' it fixes it for me.
As a workaround, changing workspace.json to add '\\' in place of '/' also works but may cause linux issues, I havent tested.

**Comment by Releef** [comment]
We also encounter this same issue. Although fail to implement a quick fix. @rm-aclark where did you implement the string replace?
