### ISSUE TITLE
[nx-enforce-module-boundaries] "allow" entries should cover all deep imports for given libs

### ISSUE THREAD

**Issue by MaximSagan** [nrwl/nx#1373]
For large apps, full migration to the recommended NX project structure can be very time consuming (particularly isolation of functionalities into self-contained libs), so it may be beneficial to contain the majority of "unmigrated" code in its own lib. Obviously, setting up a barrel file (`index.ts`) to export absolutely everything from that lib is not realistic, so we may have to perform deep imports on that particular lib.

## Expected Behavior

When TSLint is set up with `nx-enforce-module-boundaries` and `"allow": [ "@my-root/old-app" ]` as shown below, we expect all imports starting with `"@my-root/old-app"` (e.g. `import { ThingyService } from "@my-root/old-app/services/thingy.service";`) to be excepted from the rule.

```json
{
  "rulesDirectory": [
    "node_modules/@nrwl/schematics/src/tslint",
    "node_modules/codelyzer"
  ],
  "rules": {
    ...
    "nx-enforce-module-boundaries": [
      true,
      {
        "allow": [ "@my-root/old-app" ],
        "depConstraints": [
          {
            "sourceTag": "*",
            "onlyDependOnLibsWithTags": ["*"]
          }
        ]
      }
    ],
  }
}
```

## Current Behavior

Currently, only the exact strings listed in the `allow` array will be excepted from the rule.

## Proposal

[This line in nx/packages/workspace/src/tslint/nxEnforceModuleBoundariesRule.ts](https://github.com/nrwl/nx/blob/4bce6f7dddba9734ee415af1bd651037ca412e1a/packages/workspace/src/tslint/nxEnforceModuleBoundariesRule.ts#L100) is where we see the exact string comparison.
```ts
if (this.allow.indexOf(imp) > -1) {
```
It should be changed to something like this:
```ts
if (this.allow.some(a => imp.startsWith(a))) {
```

Alternatively, so as not to affect existing behavior, we could allow the use of a wildcard, e.g. `"allow": [ "@my-root/old-app/*" ]`.
```ts
if (this.allow.some(a => matchImportWithWildcard(a, imp))) {
```

where the matching function is something like
```ts
function matchImportWithWildcard(
  allowableImport: string, // This may contain wildcards ("*")
  extractedImport: string,
): boolean {
  const regex = new RegExp("^" + allowableImport.split("*").join(".*") + "$");
  return regex.test(extractedImport);
}
```

```

**Comment by MaximSagan** [comment]
@vsavkin @FrozenPandaz Any thoughts on this and/or my corresponding PR?
As things stand, the `nx-enforce-module-boundaries` rule is essentially useless for organizations such as mine that are mid-migration to NX, because if this rule is turned on, it will light up everything that pulls content from within the "old-app" lib (the lib that needs to be gradually broken down into smaller libs), unless we want to make a temporary `index.ts` barrel for said lib containing 1000s of exports. Therefore,  we have no choice but to turn the rule off, which in turn makes it difficult to enforce good practices for our proper libs.

**Comment by vsavkin** [comment]
@MaximSagan thank you very much for submitting the PR. I merged it a few hours ago: https://github.com/nrwl/nx/commit/82898f7d212b4801288998d5fe5ac04ca84d67ca
