### ISSUE TITLE
How to use `@nrwl/expo` generator?

### ISSUE THREAD

**Issue by mocon** [nrwl/nx#13738]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[Package link](https://www.npmjs.com/package/@nrwl/expo)

### Additional context or description

Hello, I am attempting to add an Expo app to my Nx monorepo. Following the documentation leads to a 404 at https://nx.dev/expo/overview, and I haven't been able to add the generator manually. Can you point me in the right direction? Thank you!

**Comment by rubiagatra** [comment]
You can check https://nx.dev/packages/expo/generators/init @mocon 

or you can check it by CLI `nx list @nrwl/expo`

**Comment by rubiagatra** [comment]
If you solve this issue, please consider closing the issue by yourself

**Comment by mocon** [comment]
Thanks @rubiagatra.
