### ISSUE TITLE
@nrwl/next too large dist folder 

### ISSUE THREAD

**Issue by renehauck** [nrwl/nx#13732]
### Current Behavior

When I run a build in an nx project that uses @nrwl/next, which is empty except for the example, I get the following package.json:
```json
{
  "name": "myFe",
  "version": "0.0.1",
  "dependencies": {
    "@nrwl/next": "15.2.1",
    "next": "13.0.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-is": "18.2.0",
    "sass": "1.56.1",
    "styled-components": "5.3.5",
    "typescript": "4.8.4"
  },
  "scripts": {
    "start": "next start"
  }
}
```
If I now run `npm install`, the `node_modules` is about 400MB big. The reason for this is that, for example, `cypress` is also installed via the `@nrwl/next` dependency.

### Expected Behavior

no packages like cypress should be installed in production

### Steps to Reproduce

install nx with nextjs according to instructions: https://nx.dev/packages/next

### Nx Report

```shell
Node : 14.17.0
   OS   : linux x64
   pnpm : 6.24.4
   
   nx : 15.2.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.2.1
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.1
   @nrwl/js : Not Found
   @nrwl/linter : 15.2.1
   @nrwl/nest : Not Found
   @nrwl/next : 15.2.1
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.2.1
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.2.1
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.2.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by mcmxcdev** [comment]
I agree, we are using Playwright, so no need to have Cypress defined anywhere.

**Comment by ckaeslin** [comment]
Shouldn't `@nrwl/next` be in the `devDependencies`?
I had once a similar issue https://github.com/nrwl/nx/issues/12150 and it got solved by separating withNx.

**Comment by renehauck** [comment]
@ckaeslin Hi, thanks for the help, what do you mean by "separating". Just remove it, or write it in a different place? Thanks

**Comment by ckaeslin** [comment]
@renehauck can you put @nrwl/next into devDependencies or why do you need it in dependencies.
