### ISSUE TITLE
NX   Cannot read properties of undefined (reading 'split') when workspace.json is missing or root project object config is changed to string

### ISSUE THREAD

**Issue by mklueh** [nrwl/nx#13749]
### Current Behavior

I'm running into this issue as well after using the workspace.json migration command.

> NX   Cannot read properties of undefined (reading 'split') 

Only those targets specified in the project.json are affected, while normal package.json scripts work

```
{
  "projectType": "application",
  "root": "apps/my-app",
  "targets": {
    "deploy": {
      "dependsOn": [
        {
          "projects": "dependencies",
          "target": "prepack"
        }
      ]
    },
    "dev": {
      "dependsOn": [
        {
          "projects": "dependencies",
          "target": "prepack:stub"
        }
      ]
    }
  }
}
```

### Expected Behavior

To work as before the migration

### Steps to Reproduce

**This happens as soon as the workspace.json is either missing, or the project definition changes from**

```
   "my-app": {
      "root": "apps/my-app"
    },
```

**to**

```
   "my-app": "apps/my-app"
```

I create a new issue, as this does not seem to be related to the executor

### Nx Report

```shell
Node : 16.18.1
   OS   : linux x64
   yarn : 3.3.0
   
   nx : 15.3.0
   @nrwl/angular : 15.3.0
   @nrwl/cypress : 15.3.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : 15.3.0
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.3.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.3.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.3.0
   @nrwl/web : 15.3.0
   @nrwl/webpack : 15.3.0
   @nrwl/workspace : 15.3.0
   typescript : 4.9.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @jscutlery/semver: 2.29.2
         @nxext/vite: 15.0.0
         @nxtend/capacitor: 13.0.0
         @nxtend/firebase: 12.1.0
         @theunderscorer/nx-semantic-release: 1.14.0
         @trumbitta/nx-plugin-openapi: 1.12.1
         @trumbitta/nx-plugin-unused-deps: 1.12.1
         nx-electron: 13.2.1
```

### Failure Logs

```shell
>  NX   Cannot read properties of undefined (reading 'split')


TypeError: Cannot read properties of undefined (reading 'split')
    at getExecutorForTask (/home/user/workspace/my-app/node_modules/nx/src/tasks-runner/utils.js:176:49)
    at getCustomHasher (/home/user/workspace/my-app/node_modules/nx/src/tasks-runner/utils.js:181:21)
    at /home/user/workspace/my-app/node_modules/nx/src/hasher/hash-task.js:21:58
    at Generator.next (<anonymous>)
    at /home/user/workspace/my-app/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/user/workspace/my-app/node_modules/tslib/tslib.js:114:16)
    at hashTask (/home/user/workspace/my-app/node_modules/nx/src/hasher/hash-task.js:20:20)
    at TasksSchedule.<anonymous> (/home/user/workspace/my-app/node_modules/nx/src/tasks-runner/tasks-schedule.js:65:48)
    at Generator.next (<anonymous>)

```

### Additional Information

This reminds me of another issue I once had https://github.com/nrwl/nx/issues/9971#issuecomment-1179727414

Where I figured out that the project config has to be of **type object and not string** and contain the **root property** in order to work for me.

However, according to the docs

https://nx.dev/deprecated/workspace-json#removing-workspace.json

a valid workspace.json config should look like

```
{
  "version": 2,
  "projects": {
    "my-app": "apps/my-app",
    "some-lib": "libs/some-lib"
  },
  "$schema": "./node_modules/nx/schemas/workspace-schema.json"
}

```

and the command removes the object config in favor of the string config as well and therefore breaks it

> nx g @nrwl/workspace:convert-to-nx-project --all

**Comment by AgentEnder** [comment]
Hey @mklueh! The formatting looks right. Can you provide a reproduction for this? It sounds like you probably have a project.json with a  target defined that has no `executor` property.

**Comment by mklueh** [comment]
@AgentEnder I'll try to reproduce it.

Btw, can't the error message give at least some hint, if a certain project's config has issues? Would be more convenient to see where the issue might be coming from

**Comment by AgentEnder** [comment]
Yeah, this should probably have some better error messaging. You could add some logging around these lines to figure it out easier in your specific case: 

/home/user/workspace/my-app/node_modules/nx/src/tasks-runner/utils.js:176:49
