### ISSUE TITLE
@nrwl/workspace:move fails on tsconfig.json with comments

### ISSUE THREAD

**Issue by Den-dp** [nrwl/nx#13740]
### Current Behavior

`@nrwl/workspace:move` generator fails while trying to move around a lib in a newly created (via angular cli) project, since from the start `tsconfig.json` has comments inside (I guess it affects all newcomers trying to use nx in their projects).

### Expected Behavior

```
npx nx generate @nrwl/workspace:move libs --project-name=some-lib --verbose
```
should work with `tsconfig.json` which uses `json5` file format (comments).

### Steps to Reproduce

1. `ng new ng14-minimal --minimal --inline-style --inline-template --skip-tests --routing false --style=css`
2. `cd ng14-minimal`
3. `ng g library some-lib`
4. `cat tsconfig.json`
```
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "compileOnSave": false,
```
5. `npm i @nrwl/workspace -D`
6. `npx nx generate @nrwl/workspace:move libs --project-name=some-lib --verbose`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 14.20.0
   OS   : win32 x64
   npm  : 6.14.17

   nx : 15.3.0
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : Not Found
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.3.0
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
npx nx generate @nrwl/workspace:move libs --project-name=some-lib --verbose

>  NX  Generating @nrwl/workspace:move


 >  NX   Unexpected token / in JSON at position 0


SyntaxError: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
    at updateImports (C:\temp\ng14-minimal\node_modules\@nrwl\workspace\src\generators\move\lib\update-imports.js:29:25)
    at C:\temp\ng14-minimal\node_modules\@nrwl\workspace\src\generators\move\move.js:28:44
    at Generator.next (<anonymous>)
    at C:\temp\ng14-minimal\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\temp\ng14-minimal\node_modules\tslib\tslib.js:114:16)
    at moveGenerator (C:\temp\ng14-minimal\node_modules\@nrwl\workspace\src\generators\move\move.js:22:20)
    at Object.<anonymous> (C:\temp\ng14-minimal\node_modules\nx\src\command-line\generate.js:222:36)
    at Generator.next (<anonymous>)
```

**Comment by Coly010** [comment]
There's a specific move generator for Angular workspaces

`nx g @nrwl/angular:move`

Can you try that instead? https://nx.dev/packages/angular/generators/move

**Comment by Den-dp** [comment]
@Coly010 unfortunately I see the same error
![image](https://user-images.githubusercontent.com/1770529/207862312-4b25373a-c57c-4291-b00b-5034b2538441.png)

looks like internally it uses `@nrwl/workspace:move` anyway
https://github.com/nrwl/nx/blob/c3c9b2d24d384ce1b39d78461eb86c7c0c84bb75/packages/angular/src/generators/move/move.ts#L1-L25

**Comment by Coly010** [comment]
It does, but it does extra things required for angular, let me take a look
