### ISSUE TITLE
Cannot read properties of null (reading 'length') - while using "setup-mf" in a clean application

### ISSUE THREAD

**Issue by leonandroid** [nrwl/nx#13748]
### Current Behavior

Hello,

So i'm a starter here in the NX world, hope this is not a mistake.
I'm trying to create an application from scratch to test the module-federation approach, as seen in this tutorial:
https://www.youtube.com/watch?v=JkcaGzhRjkc&t=340s

The command i'm trying is:
`nx generate @nrwl/angular:setup-mf pricing-main --mfType=host`
When I follow those steps, I get this error:  I get the "Cannot read properties of null (reading 'length')" error.

If I run the verbose command like this; I get as following:
`nx generate @nrwl/angular:setup-mf pricing-main --mfType=host --verbose`

```
**Error: ENOENT: no such file or directory, open** 'D:\TestingSite\unified-pricing\apps\pricing-main\src\app\app.routes.ts'
    at Object.openSync (node:fs:600:3)
    at readFileSync (node:fs:468:35)
    at FsTree.fsReadFile (D:\TestingSite\unified-pricing\node_modules\nx\src\generators\tree.js:192:44)
    at FsTree.read (D:\TestingSite\unified-pricing\node_modules\nx\src\generators\tree.js:22:32)
    at updateHostAppRoutes (D:\TestingSite\unified-pricing\node_modules\@nrwl\angular\src\generators\setup-mf\lib\update-host-app-routes.js:20:38)
    at D:\TestingSite\unified-pricing\node_modules\@nrwl\angular\src\generators\setup-mf\setup-mf.js:14:43
    at Generator.next (<anonymous>)
    at D:\TestingSite\unified-pricing\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (D:\TestingSite\unified-pricing\node_modules\tslib\tslib.js:114:16)
```

I saw there is also an option to be added to configure Route, which ends in the same error above
`nx generate @nrwl/angular:setup-mf pricing-main --mfType=host --verbose --routing`

**Looks like it is looking for a "app.routes.ts" which is not generated by default by the commands, when creating a workspace.
The file, of course does not exists.
(And quite honest, I never saw the app.router.ts file in any other nx application, so not sure why it asks for it)**

### Expected Behavior

To configure the application properly, to be ready for module-federation settings.

### Github Repo

https://github.com/leonandroid/nxTesting

### Steps to Reproduce

In order to reproduce, I did this:

1. Create a folder in any drive, open a CMD in that folder. 
2. Installed globally like this `npm install -g nx`
3. Create workspace like this: `npx create-nx-workspace unified-pricing --preset=angular`
- I'm using MONOREPO, with the option that says "create lib and app folders" or similar...
- I'm not using distributed cache.
- I'm using SASS
5. Open code and navigate
6. Just for the sake of the testing, not really necessary I created 2 libraries "header" and "footer" by doing
`npx ng generate lib header`
`npx ng generate lib footer`
7. Now that i'm ready, I want to configure my app to be module-federated, so I typed:
`nx generate @nrwl/angular:setup-mf pricing-main --mfType=host`

And here, the error is:
Cannot read properties of null (reading 'length')

### Nx Report

```shell
NX   Report complete - copy this into the issue template

   Node : 18.12.1
   OS   : win32 x64
   npm  : 8.19.2

   nx : 15.3.0
   @nrwl/angular : 15.3.0
   @nrwl/cypress : 15.3.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.0
   @nrwl/workspace : 15.3.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
**Error: ENOENT: no such file or directory, open** 'D:\TestingSite\unified-pricing\apps\pricing-main\src\app\**app.routes.ts'**
    at Object.openSync (node:fs:600:3)
    at readFileSync (node:fs:468:35)
    at FsTree.fsReadFile (D:\TestingSite\unified-pricing\node_modules\nx\src\generators\tree.js:192:44)
    at FsTree.read (D:\TestingSite\unified-pricing\node_modules\nx\src\generators\tree.js:22:32)
    at updateHostAppRoutes (D:\TestingSite\unified-pricing\node_modules\@nrwl\angular\src\generators\setup-mf\lib\update-host-app-routes.js:20:38)
    at D:\TestingSite\unified-pricing\node_modules\@nrwl\angular\src\generators\setup-mf\setup-mf.js:14:43
    at Generator.next (<anonymous>)
    at D:\TestingSite\unified-pricing\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (D:\TestingSite\unified-pricing\node_modules\tslib\tslib.js:114:16)
```

**Comment by Coly010** [comment]
Yes, the default app created with the Angular Preset does not set up routing.

Module Federation requires routing.

What you should do instead is:

1. Create an empty Nx Workspace `npx -y create-nx-workspace@latest`
2. Install the angular plugin `npm install --save-dev @nrwl/angular`
3. Use the host and remote generators to generate an application which is set up to use Module Federation `nx g @nrwl/angular:host name-of-host --remotes=name-of-remote`

More info: https://www.youtube.com/watch?v=JkcaGzhRjkc

**Comment by madipta** [comment]
> Yes, the default app created with the Angular Preset does not set up routing.
> 
> Module Federation requires routing.
> 
> What you should do instead is:
> 
>     1. Create an empty Nx Workspace `npx -y create-nx-workspace@latest`
> 
>     2. Install the angular plugin `npm install --save-dev @nrwl/angular`
> 
>     3. Use the host and remote generators to generate an application which is set up to use Module Federation `nx g @nrwl/angular:host name-of-host --remotes=name-of-remote`
> 
> 
> More info: https://www.youtube.com/watch?v=JkcaGzhRjkc

can we just convert from angular preset?
