### ISSUE TITLE
Nx-Electron fails to run, or being installed in Nx 15.3, but works fine in Nx 14

### ISSUE THREAD

**Issue by tbogard** [nrwl/nx#13746]
### Current Behavior

In a clean Nx 15.3 repo, installing Nx Electron makes the install to fail in the postinstall process

- Tested in a windows 10 machine
- node 16 LTS
- powershell/CMD/Git Bash/WSL tested

![image](https://user-images.githubusercontent.com/1978642/206818993-64e070e7-24da-4ba2-9e1a-6e7db95554a4.png)

### Expected Behavior

in a clean Nx 15.3 repo with React/vite app in an integrated monorepo, installing Nx Electron should be straightforward and should not generate errors after postinstall scripts

### Steps to Reproduce

1. npx create-nx-workspace@latest, or `yarn create nx-workspace@latest`. Set an integrated monorepo with a react app
2. after install, run `npm i --save-dev nx-electron` in npm repos, or `yarn add nx-electron -D` in yarn
3. setup will fail:
![image](https://user-images.githubusercontent.com/1978642/206819794-efd210aa-de6c-4cbf-988b-59ce4765298b.png)

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.18.1
   OS   : win32 x64
   yarn : 1.22.19

   nx : 15.3.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.3.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.3.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.3.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.3.0
   @nrwl/webpack : 15.3.0
   @nrwl/workspace : 15.3.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nrwl/vite: 15.3.0
```

**Comment by AgentEnder** [comment]
`nx-electron` is a community plugin. I see that you have already opened an issue on its github. I'm going to close this out, since the proper issue is already filed where it belongs.

https://github.com/bennymeg/nx-electron/issues/189
