### ISSUE TITLE
Improve nxComponentTestingPreset  

### ISSUE THREAD

**Issue by blessanm86** [nrwl/nx#13750]
We have a couple of app using the cypress component testing and we use a custom webpack configuration.
Its all working fine, the only issue is we have the `cypress.config.ts` in each app which imports our webpack config from our custom nx-plugins lib folder.

The issue is, any time we make a change to any of the our nx-plugins, all apps also get rebuilt due to the import from the `cypress.config.ts`.

So we tried to create a custom cypress plugin where the `cypress.config.ts` is also included. 
And then quickly realized we cannot create `nxComponentTestingPreset` as it expects a `pathToConfig` to the project/lib it uses to create the executor context. Currently it uses `__filename`.

is there another approach to this problem? Another way i guess would be to extract our webpack config into its own lib, where our nx-plugins and apps import from. Not sure about having too many tiny libs for import issues

```
import { ExecutorContext } from '@nrwl/devkit';
import cypressExecutor, {
  CypressExecutorOptions,
} from '@nrwl/cypress/src/executors/cypress/cypress.impl';
import { join } from 'path';

export default async function executor(
  options: CypressExecutorOptions,
  context: ExecutorContext,
) {
  options.cypressConfig = join(__dirname, './cypress.config.ts');
  options.skipServe = true;
  return cypressExecutor(options, context);
}
```

**Comment by barbados-clemens** [comment]
What you're seeing is the default Nx behavior. as Nx analyzes the imports and that is used to build the graph. the main issue you're seeing that link between your local nx plugin and the applications is causing the build to rerun. 

the best way to do this is to just exclude the `cypress.config.ts` from the inputs of the targets you don't care about in your nx.json. [Docs on inputs/namedInputs](https://nx.dev/more-concepts/customizing-inputs)

if you have the default setup for `namedInputs` you can just add it to the list of 'production' to be ignored since build should be using that fileset. 

> Nx actually [adds this for you when running the component-testing generators](https://github.com/nrwl/nx/blob/master/packages/cypress/src/generators/cypress-component-project/cypress-component-project.ts#L121-L126)

i.e.
```json
// nx.json
{
  "namedInputs": {
    "default": ["{projectRoot}/**/*", "sharedGlobals"],
    "production": [
      "default",
      // will want to add these
      "!{projectRoot}/cypress/**/*", // exclude the cypress folder
      "!{projectRoot}/**/*.cy.[jt]s?(x)", // exclude any component test files
      "!{projectRoot}/cypress.config.[jt]s", // exclude the cypress config
      // bunch of other stuff
    ]
  },
"targetDefaults": {
    "build": {
      "inputs": ["production", "^production"], // build depends on production files which excludes cypress.config.ts now
      "dependsOn": ["^build"]
    },
    "component-test": {
      "inputs": ["default", "^production"]
    }
  }
}
```

**Comment by barbados-clemens** [comment]
as noted above this is just nx following imports and creating the relationships based on those imports. you can manually exclude an import with the `// nx-ignore`
