### ISSUE TITLE
Allow rollup assets to be inside project root (not only source root)

### ISSUE THREAD

**Issue by DaSchTour** [nrwl/nx#13767]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
`"assets": ["libs/<lib-path>/*.md"]` should work with `@nrwl/rollup:rollup`

Currently this throws `asset path must start with the project source root`

## Motivation
Should work similar to `@nrwl/js:tsc`

## Suggested Implementation
 similar to `@nrwl/js:tsc`

## Alternate Implementations
No idea

**Comment by JoA-MoS** [comment]
Have you tried the glob object to define assets?

https://nx.dev/packages/rollup/executors/rollup?ref=root/properties/assets/items/oneOf/0
