### ISSUE TITLE
nx:run-commands executor doesn't pipe interrupt signal to underlying command

### ISSUE THREAD

**Issue by caioaao** [nrwl/nx#13766]
### Current Behavior

If you use `nx:run-commands` executor for stuff like `serve` and then interrupt it (eg: by pressing ctrl+C) the interrupt signal doesn't seem to be piped to the command. This presented itself when I tried using it for a docker compose based "app": in this case, after running `nx serve docker-compose-app` and then closing it with `ctrl+C` the containers are still up.

Here's a gif to better represent this behavior:
![not-interrupting](https://user-images.githubusercontent.com/1395990/207071609-71890a5c-1b10-4252-953e-557196cc57c5.gif)

### Expected Behavior

When interrupting the execution, it should behave as if you were interrupting the underlying process itself, and not leave it running in the background. This is the expected behavior when using docker-compose directly:

![graceful-stop](https://user-images.githubusercontent.com/1395990/207071798-61e71e82-0f06-4a4c-b75a-29c356647753.gif)

### Github Repo

https://github.com/caioaao/nx-cmd-interrupt-signal-repro

### Steps to Reproduce

1. serve the app with `yarn nx serve echo-server`
2. Stop it by sending an interrupt signal (CTRL+C in most cases)

### Nx Report

```shell
[~/reps/nx-cmd-interrupt-signal-repro]$ yarn nx report    [main]
yarn run v1.22.19
$ /home/caiotiny/reps/nx-cmd-interrupt-signal-repro/node_modules/.bin/nx report

 >  NX   Report complete - copy this into the issue template

   Node : 19.2.0
   OS   : linux x64
   npm  : 8.19.3

   nx : 15.3.0
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : Not Found
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.3.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

Done in 0.64s.
```

**Comment by ZiiMakc** [comment]
Decided to try `nx` and stumbled on this in the first step using `zx` scripts. Any plans to fix this in near future?

**Comment by caioaao** [comment]
@ZiiMakc  it was fixed in #13885 and I just forgot to close the issue. Closing now

**Comment by arthurgubaidullin** [comment]
@caioaao No, the issue has not been resolved. I have encountered it as well.

```txt
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 16.14.2
   OS     : darwin arm64
   npm    : 8.5.5
   Hasher : Native
   
   nx                 : 16.2.1
   @nx/js             : 16.2.1
   @nx/jest           : 16.2.1
   @nx/linter         : 16.2.1
   @nx/workspace      : 16.2.1
   @nx/devkit         : 16.2.1
   @nx/esbuild        : 16.2.1
   @nx/eslint-plugin  : 16.2.1
   @nrwl/tao          : 16.2.1
   typescript         : 5.0.4
```

**Comment by ilanyehez** [comment]
I'm having this issue too on 16.2.2

**Comment by davidmwhynot** [comment]
Same issue here as well.
```
   Node   : 16.15.1
   OS     : win32 x64
   npm    : 8.12.2
   Hasher : Native

   nx (global)        : 16.3.2
   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/nest           : 16.3.2
   @nx/node           : 16.3.2
   @nx/react          : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/vite           : 16.3.2
   @nx/web            : 16.3.2
   typescript         : 4.9.5
```
