### ISSUE TITLE
React App Fails To Build 15.3.0

### ISSUE THREAD

**Issue by enchorb** [nrwl/nx#13764]
### Current Behavior

Fails to build complaining about missing dependencies, more specifically `@pmmmwh/react-refresh-webpack-plugin` 

### Expected Behavior

Build

### Steps to Reproduce

Everything was working fine in 15.2.4, fairly certain this is caused by changes made in this PR https://github.com/nrwl/nx/pull/13525

### Nx Report

```shell
N/A
```

**Comment by AgentEnder** [comment]
Can you please provide the output of Nx report, and the full stack trace as requested?

**Comment by ndcunningham** [comment]
Did you run the migrations when you updated to NX 15.3?

Running `nx migrate 15.3.0` should've included changes to address the issue you are highlighting.
The worst-case scenario is you have to install those packages yourself, but that shouldn't be the case.

I'm closing the issue but feel free to open it if the migrations do not work.
