### ISSUE TITLE
nx fails after angular:cypress-component-configuration, when using npm

### ISSUE THREAD

**Issue by xel-x** [nrwl/nx#13777]
### Current Behavior
after `npx nx generate @nrwl/angular:cypress-component-configuration --project=compotest --generateTests` most nx commands start creating the following output:
``` 
 >  NX   Cannot read properties of undefined (reading 'data')

   
   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
```

Running `nx reset`does not change anything.

It will go away after running `yarn install` or removing `@cypress/webpack-dev-server` and running `npm i`.

### Expected Behavior

run all nx commands as usual, without needing to have a yarn.lock file

### Github Repo

https://github.com/xel-x/nx-angular-15_3_3

### Steps to Reproduce

Repository was created using the following command, so instead of cloing it, everyone can create it on their own:

```
npx create-nx-workspace@15.3.3 compotest2 --preset=angular-monorepo --appName=compotest --interactive=false --style=css --nx-cloud=false
```
1. npm i
2. npx nx generate @nrwl/angular:cypress-component-configuration --project=compotest --generateTests
3. run any nx command. like `npx nx run compotest:component-test`or `npx nx report`

### Nx Report

```shell
before using yarn: 

>  NX   Cannot read properties of undefined (reading 'data')

   
   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".

after using yarn install:

   Node : 16.16.0
   OS   : darwin x64
   yarn : 1.22.19
   
   nx : 15.3.3
   @nrwl/angular : 15.3.3
   @nrwl/cypress : 15.3.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Additional Information

The issue is instantly resolved when using yarn install.
It will appear again as soon as yarn.lock is deleted.

**Comment by AgentEnder** [comment]
I think this should be fixed with #13803
