### ISSUE TITLE
Security issues with current version of Storybook

### ISSUE THREAD

**Issue by nikolaidk** [nrwl/nx#13785]
### Current Behavior

added 1123 packages, and audited 2320 packages in 24s

306 packages are looking for funding
  run `npm fund` for details

22 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

### Expected Behavior

0 high severity vulnerabilities

### Steps to Reproduce

In NX
1. Create workspace with web component app
2. Add Storybook to app
3. Watch npm report

Whitout NX:
If running with latest "npx sb@next init" on template generated using "npm create vite@latest my-webcomponents -- --template lit-ts" all security warnings are fixed.

### Nx Report

```shell
added 1123 packages, and audited 2320 packages in 24s

306 packages are looking for funding
  run `npm fund` for details

22 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details
```

### Failure Logs

```shell
22 high severity vulnerabilities
```

### Additional Information

Should be:
0 high severity vulnerabilities

**Comment by mandarini** [comment]
Hi there! Storybook is now updated to the latest stable version, so I think the issue should be fixed. So I'm closing the issue for now. Feel free to ask me to reopen if issue persists!
