### ISSUE TITLE
Nx's default `--parallel` value not correctly set to 3

### ISSUE THREAD

**Issue by mike-fam** [nrwl/nx#13782]
### Current Behavior

If the `--parallel` tag is not explicitly set, then it defaults to `undefined`, although the documentation specifies that 3 is the default value.

### Expected Behavior

It should be defaulted to 3, or the documentation should be updated to say the default value is `undefined`, meaning sequential execution

### Github Repo

https://github.com/nrwl/nx/blob/master/packages/nx/src/utils/command-line-utils.ts#L168-L180

### Steps to Reproduce

1. Run `nx run-many --target=lint --all`, without the `--parallel` tag.
2. All projects are linted sequentially.

### Nx Report

```shell
NA
```

### Failure Logs

```shell
NA
```

### Additional Information

I believe the problem lies within this snippet:
https://github.com/nrwl/nx/blob/master/packages/nx/src/utils/command-line-utils.ts#L168-L180

If `args['parallel']` is `undefined`, which it is when it’s not specified, then `nxArgs['parallel']` is not set and defaults to `undefined` too.

I've tested this by adding this line directly below the snippet above:
```
	output.note({
		title: `Run with args.parallel being '${args['parallel']}', so nxArgs.parallel is set to '${nxArgs['parallel']}'`,
	});
```

Running `nx run-many --target=lint --all` on my repository (or any nx repository for that matter) gives:
```
>  NX   NOTE  Run with args.parallel being 'undefined', so nxArgs.parallel is set to 'undefined'
```

I can create a PR, but I need to know the Nx team's decision. Do you want this `parallel` value to default to 3 or do you want to update the documentation to match the current behaviour?

**Comment by AgentEnder** [comment]
It should default to 3, you can proceed with a PR if you'd like.
