### ISSUE TITLE
@nrwl/vite Uses wrong package.json as base

### ISSUE THREAD

**Issue by summer-jordan** [nrwl/nx#13798]
### Current Behavior

Using `@nrwl/vite` to generate a library creates a `package.json` in the output directory but it is a copy of the root `package.json` instead of the one from the library.

### Expected Behavior

The output `package.json` should be created from the `package.json` inside the library root, not the project root.

### Github Repo

https://github.com/summer-jordan/vite-lib-package-error

### Steps to Reproduce

1. Add @nrwl/vite to workspace - `nx g @nrwl/vite:init`
2. Generate library using vite as the bundler - `nx g @nrwl/js:lib my-lib --bundler=vite`
3. Update the library `package.json` to have type=module and a peer dependency
4. Build library - `nx run my-lib:build`
5. View the output `package.json` file and see that there is no type defined, no exports, and no peer dependencies. Instead, the `devDependencies` are defined to match the root package.json along with the rest of the root `package.json` contents.

### Nx Report

```shell
Node : 16.18.1
   OS   : darwin x64
   pnpm : 7.16.1
   
   nx : 15.3.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.3.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nrwl/vite: 15.3.3
```

**Comment by ales-albert-kilbergr** [comment]
Hi.

I run into the same problem, after debugging the `@nrwl/vite` plugin, something caught my attention:

https://github.com/nrwl/nx/blob/578ecb67856613304cd39811b8a74897b8feb236/packages/vite/src/executors/build/build.impl.ts#L26

The `@nrwl/vite:build` executor is copying the `package.json` like this:
```ts
await copyAssets(
      {
        outputPath: options.outputPath,
        assets: [
          {
            input: '.',
            output: '.',
            glob: 'package.json',
          },
        ],
      },
```
I presume that because the script is running from the root of nx workspace, this will pick the package.json from there instead the one from a library.

**Comment by ozee** [comment]
@ndcunningham your PR is what I ended up doing yesterday and worked for me.
