### ISSUE TITLE
Is there a version that works on Windows coming out?

### ISSUE THREAD

**Issue by kevincam3** [nrwl/nx#138]
This doesn't work on windows since the scripts it calls are bash scripts. Any plans to make a Windows compatible version?

**Comment by dereklin** [comment]
I was able to use git bash on windows

**Comment by kevincam3** [comment]
Yeah, it seems to be some other problem now. 
Error: tree.branch is not a function
tree.branch is not a function

**Comment by davidwuerfel** [comment]
As a workaround for now you could use [Cygwin ](https://www.cygwin.com/) (with all defaults and curl as optional net package installed). You only need it to call the initial script. Afterwards you can switch to your favorite win-editor.

**Comment by vsavkin** [comment]
The current version works on windows. Just use create-nx-workspace (see here https://nrwl.io/nx/guide-getting-started) to create a new workspace.
