### ISSUE TITLE
A git.exe process slows down 20 sec all NX commands

### ISSUE THREAD

**Issue by jvallesf** [nrwl/nx#13809]
### Current Behavior

Hello,

Executing nx commands in my repo takes a very long time because a git.exe process is executed before anything actually happens. This only happens if I execute the commands with Powershell or the Windows command line. It doesn't happen if I do it with Bash for Windows.

For example, the command "nx report" takes 4 seconds with Bash and 26 seconds with the Windows cmd.

Because there is this git.exe process taking 15% CPU executing during 20 seconds or so when I run the command, I am quite sure it has something to do with the problem. I don't know if the size of the ".git" folder can have something to do, but it is quite large, 8Gb.

I don't know if this is a bug, or how NX is related to Git... None of my colleagues are having the same issue (with the same repo), and I don't know how to reproduce it. Could you please give me some indication/ideas of what I should look at? I am totally lost.

### Expected Behavior

The same execution times (or similar) with the Windows CMD and Bash for Windows.

### Steps to Reproduce

I haven't been able to reproduce the problem with other repos.

### Nx Report

```shell
Node : 16.16.0
   OS   : win32 x64
   npm  : 8.11.0

   nx : 15.2.1
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : Not Found
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : Not Found
   typescript : 4.9.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by AgentEnder** [comment]
Can you retry this with a fresh clone of the repo on your machine? Nx uses git behind the scenes for several things (computing hashes, checking changes between base + head, etc).

**Comment by jvallesf** [comment]
Hello, I have tried cloning to a new repo and no change at all. And my colleagues with the same repo have normal times... How can I print logs for the operation done with Git? By the way, is this hashing process and checking base/head done in every nx command?
Thank you

**Comment by jvallesf** [comment]
Hi, any updates on this?
Is there any way to print logs to see what git.exe is doing?

**Comment by jvallesf** [comment]
Still with the same issues. Do you have any insights I can use to try to find the problem?
Thanks
