### ISSUE TITLE
NX cannot successfully read lockfile

### ISSUE THREAD

**Issue by jkalberer** [nrwl/nx#13806]
### Current Behavior

I have a lerna project set up using npm workspaces. I have a lockfile v2 for npm.

I run the command `npx lerna run build --verbose` and see the following:

```
TypeError: Cannot read properties of undefined (reading 'debug')
    at /Users/jkalberer/Desktop/dev/cx-portal/node_modules/nx/src/lock-file/npm.js:52:65
    at Array.forEach (<anonymous>)
    at /Users/jkalberer/Desktop/dev/cx-portal/node_modules/nx/src/lock-file/npm.js:47:26
    at Array.forEach (<anonymous>)
    at mapPackages (/Users/jkalberer/Desktop/dev/cx-portal/node_modules/nx/src/lock-file/npm.js:39:34)
    at parseNpmLockFile (/Users/jkalberer/Desktop/dev/cx-portal/node_modules/nx/src/lock-file/npm.js:21:23)
    at parseLockFile (/Users/jkalberer/Desktop/dev/cx-portal/node_modules/nx/src/lock-file/lock-file.js:73:43)
    at /Users/jkalberer/Desktop/dev/cx-portal/node_modules/nx/src/project-graph/build-project-graph.js:61:109
    at Generator.next (<anonymous>)
    at /Users/jkalberer/Desktop/dev/cx-portal/node_modules/tslib/tslib.js:118:75
```

If I add some logging around this I can see that it's attempting to index this JSON from the root lockfile:
```
  "node_modules/webpack-virtual-modules": {
      "version": "0.4.6",
      "resolved": "https://registry.npmjs.org/webpack-virtual-modules/-/webpack-virtual-modules-0.4.6.tgz",
      "integrity": "sha512-5tyDlKLqPfMqjT3Q9TAqf2YqjwmnUleZwzJi1A5qXnlBCdj2AtOJ6wAWdglTIDOPgOiOrXeBeFcsQ8+aGQ6QbA==",
      "dev": true
    },
```
The issue here being that `dependency.dependencies['debug']` doesn't exist (`dependencies` is not a field on this JSON)

### Expected Behavior

NX should successfully parse the npm lockfile.

### Steps to Reproduce

1. `npx lerna init`
2. cd `packages`
3. `npm init gatsby` (gatsby installs a lot of dependencies where I've seen this issue)
4. `npx lerna run build`

### Nx Report

```shell
npx nx report

 >  NX   Cannot read properties of undefined (reading 'debug')
```

### Failure Logs

```shell
TypeError: Cannot read properties of undefined (reading 'debug')
    at /Users/jkalberer/Desktop/dev/cx-portal/node_modules/nx/src/lock-file/npm.js:52:65
    at Array.forEach (<anonymous>)
    at /Users/jkalberer/Desktop/dev/cx-portal/node_modules/nx/src/lock-file/npm.js:47:26
    at Array.forEach (<anonymous>)
    at mapPackages (/Users/jkalberer/Desktop/dev/cx-portal/node_modules/nx/src/lock-file/npm.js:39:34)
    at parseNpmLockFile (/Users/jkalberer/Desktop/dev/cx-portal/node_modules/nx/src/lock-file/npm.js:21:23)
    at parseLockFile (/Users/jkalberer/Desktop/dev/cx-portal/node_modules/nx/src/lock-file/lock-file.js:73:43)
    at /Users/jkalberer/Desktop/dev/cx-portal/node_modules/nx/src/project-graph/build-project-graph.js:61:109
    at Generator.next (<anonymous>)
    at /Users/jkalberer/Desktop/dev/cx-portal/node_modules/tslib/tslib.js:118:75
```

**Comment by AgentEnder** [comment]
Hey @jkalberer! What version lockfile are you using?

**Comment by jkalberer** [comment]
> I have a lockfile v2 for npm.
It's there but I should have given its own line. 

Node: v16.14.2
NPM: 8.5.0

**Comment by AgentEnder** [comment]
Ah, my bad. I'll let @meeroslav take a look from here.

**Comment by meeroslav** [comment]
Hi @jkalberer, can you tell me which version of nx you are using (obviously report fails for you, so check in root project.json)?

If you are using anything lower than 15.3.3, can you please try that version?

**Comment by meeroslav** [comment]
Actually, based on the error, it seems you already have the latest version.

**Comment by meeroslav** [comment]
Is there a chance you could send me your lock file? Based on the code, there should be a package with the path:
```
node_modules/webpack-virtual-modules/node_modules/{unknown package}
```

Which would suggest that `webpack-virtual-modules` has a dependency on that package. But perhaps there is something specific in place

**Comment by jkalberer** [comment]
@meeroslav - I'll try to create a simple repro and get you a link

**Comment by jkalberer** [comment]
Ok, so clone https://github.com/jkalberer/gatsby-lerna-repro

Then run
```
npx lerna bootstrap
npx lerna run build
```

The `build` command will fail.
