### ISSUE TITLE
Intermittent ngcc errors in CI pipeline

### ISSUE THREAD

**Issue by johnbwoodruff** [nrwl/nx#13807]
### Current Behavior

When running the following command:

```shell
$ nx run-many --all --parallel --maxParallel=3 --target=test --browsers=ChromeHeadlessNoSandbox
```

We get intermittent failures throughout the testing processes with the following information:

```
./path/to/lib/src/test.ts - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.

Error: Failed to initialize Angular compilation - ngcc is already running at process with id 1266.
If you are running multiple builds in parallel then you might try pre-processing your node_modules via the command line ngcc tool before starting the builds.
(If you are sure no ngcc process is running then you should delete the lock-file at /opt/atlassian/pipelines/agent/build/client/node_modules/.ngcc_lock_file.)
```

This then fails that libs tests because it obviously can't run them.

### Expected Behavior

We shouldn't have this intermittent error behavior, it should correctly build and test

### Steps to Reproduce

As this is an intermittent error I have not been able to figure out a way to consistently reproduce this issue. Our nx workspace consists of 50 projects (two apps and many libs) as well as thousands of unit tests.

### Nx Report

```shell
Node : 14.19.0
OS   : darwin x64
npm  : 6.14.16

nx : 14.8.6
@nrwl/angular : 14.8.6
@nrwl/cypress : 14.8.6
@nrwl/detox : Not Found
@nrwl/devkit : Not Found
@nrwl/esbuild : Not Found
@nrwl/eslint-plugin-nx : 14.8.6
@nrwl/expo : Not Found
@nrwl/express : Not Found
@nrwl/jest : 14.8.6
@nrwl/js : 14.8.6
@nrwl/linter : 14.8.6
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/nx-cloud : 15.0.2
@nrwl/nx-plugin : Not Found
@nrwl/react : Not Found
@nrwl/react-native : Not Found
@nrwl/rollup : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : 14.8.6
@nrwl/web : Not Found
@nrwl/webpack : 14.8.6
@nrwl/workspace : 14.8.6
typescript : 4.8.4
---------------------------------------
Local workspace plugins:
---------------------------------------
Community plugins:
      @ngrx/component-store: 14.3.2
      @ngrx/effects: 14.3.2
      @ngrx/entity: 14.3.2
      @ngrx/router-store: 14.3.2
      @ngrx/store: 14.3.2
      @ngrx/store-devtools: 14.3.2
      ng-mocks: 14.3.2
```

### Failure Logs

```shell
./path/to/lib/src/test.ts - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.

Error: Failed to initialize Angular compilation - ngcc is already running at process with id 1266.
If you are running multiple builds in parallel then you might try pre-processing your node_modules via the command line ngcc tool before starting the builds.
(If you are sure no ngcc process is running then you should delete the lock-file at /opt/atlassian/pipelines/agent/build/client/node_modules/.ngcc_lock_file.)
```

### Additional Information

This started occurring immediately after upgrading from `13.8.3` to `14.8.6` and has been happening ever since. We recently updated to `15.1.1` and the issue is still present. We make sure to run ngcc prior to the run test command to preprocess the node_modules as recommended by the error using the following command:

```shell
$ ngcc --properties es2020 browser module main
```

This makes it happen somewhat less frequently, but does not eliminate the problem.

I originally thought maybe the ngcc lockfile was sticking around and needed to be cleared before the pipeline runs, but that ended up not being the case as it happens intermittently somewhere in the middle of the pipeline.

**Comment by Coly010** [comment]
Are you able to migrate to latest and try again?

NGCC shouldn't fail the tests. It just compiles the node_modules that are built with Angular View Engine rather than Angular Ivy to allow them to work with Angular Ivy. It locks the node_modules to do this, but it should free them up, then run the tests. Each instance of NGCC that is running will wait for the node_modules to free up before running, which should block running the tests for any project that is waiting for an instance of NGCC to complete.

**Comment by johnbwoodruff** [comment]
Yeah I can attempt that. By the way, I put the wrong nx report in the original comment, I was on the wrong branch when I ran it. 🤦‍♂️  Here's what it actually is currently with the correct `15.1.1` version:

```
Node : 14.19.0
OS   : darwin x64
npm  : 6.14.16

nx : 15.1.1
@nrwl/angular : 15.1.1
@nrwl/cypress : 15.1.1
@nrwl/detox : Not Found
@nrwl/devkit : 15.1.1
@nrwl/esbuild : Not Found
@nrwl/eslint-plugin-nx : 15.1.1
@nrwl/expo : Not Found
@nrwl/express : Not Found
@nrwl/jest : 15.1.1
@nrwl/js : 15.1.1
@nrwl/linter : 15.1.1
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/nx-cloud : 15.0.2
@nrwl/nx-plugin : Not Found
@nrwl/react : Not Found
@nrwl/react-native : Not Found
@nrwl/rollup : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : 15.1.1
@nrwl/web : Not Found
@nrwl/webpack : 15.1.1
@nrwl/workspace : 15.1.1
typescript : 4.8.4
---------------------------------------
Local workspace plugins:
---------------------------------------
Community plugins:
      @ngrx/component-store: 14.3.2
      @ngrx/effects: 14.3.2
      @ngrx/entity: 14.3.2
      @ngrx/router-store: 14.3.2
      @ngrx/store: 14.3.2
      @ngrx/store-devtools: 14.3.2
      ng-mocks: 14.3.2
```

I'll check with the latest release and update here when I determine if this is still an issue.

**Comment by Coly010** [comment]
I'm going to close this issue, but it can be reopened if there are further updates :)

**Comment by marleypowell** [comment]
@johnbwoodruff any update on this?

I am also experiencing the same behaviour. Although it might only occur when using DTE.

```
  Node : 16.16.0
   OS   : win32 x64
   yarn : 1.22.19
   
   nx : 14.5.10
   @nrwl/angular : 14.5.10
   @nrwl/cypress : 14.5.10
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.10
   @nrwl/eslint-plugin-nx : 14.5.10
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.10
   @nrwl/js : 14.5.10
   @nrwl/linter : 14.5.10
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.7.0
   @nrwl/nx-plugin : 14.5.10
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.10
   @nrwl/web : 14.5.10
   @nrwl/workspace : 14.5.10
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
         @exclaimer/workspace-plugin
   ---------------------------------------
   Community plugins:
         @nx-dotnet/core: 1.16.3
         @storybook/angular: 6.5.15
         @trumbitta/nx-plugin-openapi: 1.12.1
         ng-mocks: 14.5.3
```

**Comment by johnbwoodruff** [comment]
Unfortunately I haven't received the go-ahead to update our repo to latest yet so I can't validate if it happens on latest.

**Comment by marleypowell** [comment]
@Coly010 update - this looks to be related to [#36119](https://github.com/angular/angular/issues/36119)

I tried to manually run `ngcc` manually on the dist folder so that the tests wouldn't have to re-run it. The problem I had with this was that `ngcc` didn't like the format of the package outputs and didn't recognise them as [compiledByAngular](https://github.com/angular/angular/blob/baa3e18812127e7266580f4cd202a4cb3204cbcb/packages/compiler-cli/ngcc/src/packages/entry_point.ts#:~:text=const%20compiledByAngular%20%3D%20entryPointConfig%20!%3D%3D%20undefined%20%7C%7C%20fs.exists(metadataPath)%3B). I'm guessing this is because of the NX [ng-packgr-lite](https://nx.dev/packages/angular/executors/ng-packagr-lite) compiler.

**Comment by dlarr** [comment]
Experiencing same issue

- Angular : 14
- nrwl/angular : 15
- Distributed build on Openshift Jenkins CI platform 

That ngcc still running is stilla thing and it's a pain.

On regular builds we had to 

- run ngcc at postinstall step
- as we run parallel builds within same slave executor, we made a delay between each parallel step so they never start at the same time...

As of today, we are stucked on this matter :x
