### ISSUE TITLE
Cache Invalidate

### ISSUE THREAD

**Issue by harshagarwal-mono** [nrwl/nx#13819]
### Current Behavior

I am using nx in my monorepo and i am passing all the arguments needed by different parts of the app at once. Which is getting forwarded to all of its dependencies. The problem here is , suppose i have an app _A_ and it has dependency _B_ and _C_. now B require argument **a** and _C_ require argument **b**.
I am passing **a** & **b** to the app A at once. So when i am changing argument **a** value then cache of _C_ is also getting invalidated rather than only **B**. Due to which i am not getting the full benefit of NX cache. Is there anything which can help me right now or is it a feature that is not implemented yet but can be implemented in future ?

### Expected Behavior

If i change argument **a** then only B should be recalculated and C should come from cache

### Steps to Reproduce

1. Create Any workspace containing three libs A, B and C
2. B and C are the dependencies of A
3. lib B should use argument a and lib C should use argument c.
4. now pass argument a & c to A which will forward them to B and C
5. now change argument a value
6. C should not be recalculated as b is not changed but is not coming from cache

### Nx Report

```shell
Node : 16.17.0
   OS   : darwin x64
   npm  : 8.15.0
   
   nx : 14.6.5
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.6.5
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.6.5
   @nrwl/js : Not Found
   @nrwl/linter : 14.6.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.6.5
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by AgentEnder** [comment]
Hey @harshagarwal-mono! Currently there is no way to determine which parameters pertain to which targets that are being ran. As such, all parameters affect the cache of the run. Our recommendation to mitigate this is that you instead make use of configurations in the project.json targets to avoid passing flags via the CLI in CI (which is where most cache hits occur)

**Comment by harshagarwal-mono** [comment]
Hi @AgentEnder Thanks for the clarification on this. But can you please also give an example how to mitigate this or resource link where i can learn about these configurations. As i am not finding it in the documentation.
