### ISSUE TITLE
nx run throws error Cannot read properties of undefined (reading 'tslib')

### ISSUE THREAD

**Issue by piotrroda** [nrwl/nx#13814]
### Current Behavior

After update all @nrwl packages from 15.3.0 to 15.3.3 this error occured.

nx run test:app

 >  NX   Cannot read properties of undefined (reading 'tslib')

   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".

### Expected Behavior

No errors

### Steps to Reproduce

1. update packages from 15.3.0 to 15.3.3
2. execute command nx run

### Nx Report

```shell
nx report

 >  NX   Cannot read properties of undefined (reading 'tslib')


   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
```

**Comment by AgentEnder** [comment]
This may have been fixed by #13803. Can you retry after the next release?
