### ISSUE TITLE
Component testing with Cypress ignores cypress configuration

### ISSUE THREAD

**Issue by Ognengineer** [nrwl/nx#13820]
### Current Behavior

With a clearly edited config for video recording tests set to false, cypress ignores that specific setting and it is always picked up as the default value "true"
![image](https://user-images.githubusercontent.com/88880270/207604619-dd2bee9e-4cb4-4ed2-8183-562dbec798ad.png)

Cypress gui opened with --watch option shows that config has a default value set to "true"
![image](https://user-images.githubusercontent.com/88880270/207605142-73bf7e74-1236-4197-9ca6-b2406e064669.png)

### Expected Behavior

video not to be recorded, cypress to read the setting. 

### Steps to Reproduce

1. Probably reproducible on all Nx projects, as i can't reproduce on other projects that we just use plain cypress 

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.17.1
   OS   : win32 x64
   yarn : 1.22.19

   nx : 15.0.7
   @nrwl/angular : 15.0.7
   @nrwl/cypress : 15.0.7
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.7
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.7
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.7
   @nrwl/js : 15.0.7
   @nrwl/linter : 15.0.7
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.7
   @nrwl/web : Not Found
   @nrwl/webpack : 15.0.7
   @nrwl/workspace : 15.0.7
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @fortawesome/angular-fontawesome: 0.11.1
         @ngneat/transloco: 4.1.1
         @ngrx/component-store: 14.0.2
         @ngrx/effects: 14.0.2
         @ngrx/entity: 14.0.2
         @ngrx/router-store: 14.0.2
         @ngrx/store: 14.0.2
         @nguniversal/express-engine: 14.0.3
         ng-mocks: 14.4.0
         @ngrx/schematics: 14.0.2
         @ngrx/store-devtools: 14.0.2
         @nguniversal/builders: 14.0.3

Done in 1.03s.
```

**Comment by barbados-clemens** [comment]
this is the correct behavior as this is how cypress works. 
docs: https://docs.cypress.io/guides/references/configuration#Testing-Type-Specific-Overrides

config options specified in the root are overridden by the more specific e2e/component testing type keys. 

if you want to change a setting then you can just spread the preset return values and set the values after. i.e.

```ts
export default defineConfig({
  component: {
    ...nxComponentTestingPreset(__filename),
    video: false,
  }
})
```
