### ISSUE TITLE
Missing --project flag in React storybook documentation example.

### ISSUE THREAD

**Issue by GrzywN** [nrwl/nx#13826]
### Documentation issue

- [x] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[Set up Storybook for React Projects](https://nx.dev/storybook/overview-react)

### Additional context or description

`nx g @nrwl/react:stories feature-ui` does not generate stories for feature-ui project/library. It should be `nx g @nrwl/react:stories --project=feature-ui`.

**Comment by mandarini** [comment]
Thanks for the report! Would you like to make that change?

**Comment by mandarini** [comment]
Thank you !!!!! :D
