### ISSUE TITLE
jest 'testMatch' expressions are incorrect

### ISSUE THREAD

**Issue by andrewalderson** [nrwl/nx#13838]
### Current Behavior

With a new Nrwl Nx 15.3.0 Angular project none of the Jest tests can be found. This seems to be because the 'testMatch' expressions in the root jest.config.ts file do not follow the Jest docs https://jestjs.io/docs/configuration#testmatch-arraystring and have had ```<rootDir>/src/``` prepended to them. Removing this prefix and using the default jest config fixes this problem.

### Expected Behavior

For my tests to be found and run.

### Steps to Reproduce

1. Create a new Angular standalone app with Nrwl NX 15.3.0
2. Run the default tests (app.component.spec.ts)
3. The tests will not be found

### Nx Report

```shell
Node : 16.18.0
   OS   : win32 x64
   npm  : 8.19.2
   
   nx : 15.3.0
   @nrwl/angular : 15.3.0
   @nrwl/cypress : 15.3.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.3.0
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.0
   @nrwl/workspace : 15.3.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @storybook/angular: 6.5.14
         @testing-library/angular: 13.0.0
```

**Comment by barbados-clemens** [comment]
Can you try updating to latest? and or share the workspace you're seeing this issue on

I just ran this on a new workspace for 15.3.3 and the tests were correctly picked up (which is also verified in our jest e2e tests)

the reason we update the test match is when you add a new project then the apps tests runner will match against any other specs in the workspace so we preemptively set it to only match in the src directory since that's the default location for the ng standalone src files.

![WkMacM1-JUEZUObn_12201740](https://user-images.githubusercontent.com/23272162/208787087-70c777f5-5a9b-4212-97cd-7692e5af2df1.png)

**Comment by andrewalderson** [comment]
@barbados-clemens This seems to be a Windows issue. I ran the same commands as you in WSL on Ubuntu and everything works as expected. 


It doesn't work on Windows though. I get the

**Comment by andrewalderson** [comment]
@barbados-clemens This seems to be a Windows issue.  I created two separate projects, one on Linux and one on Windows.

When I run the same commands that you did on Ubuntu with WSL it works as expected.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/16738284/208796702-ef686964-38b0-48a7-91f2-2d601efa1725.png">

On Windows with the same commands I get no tests found

<img width="273" alt="image" src="https://user-images.githubusercontent.com/16738284/208796783-cfcede6f-06c3-4fc7-9584-57e548fcfef1.png">

**Comment by barbados-clemens** [comment]
Thanks I'll look into this.

**Comment by barbados-clemens** [comment]
Not stale. Thanks though github bot 👍

**Comment by AgentEnder** [comment]
@barbados-clemens I removed the blocked label, which is why stalebot was marking it so soon

**Comment by barbados-clemens** [comment]
looks like this is a bug within Jest. 
https://github.com/facebook/jest/issues/7914
