### ISSUE TITLE
Please don't spam these lines

### ISSUE THREAD

**Issue by e-oz** [nrwl/nx#13839]
### Current Behavior

Too many lines is being printed.
<img width="1134" alt="Screenshot 2022-12-15 at 10 35 24" src="https://user-images.githubusercontent.com/526352/207824853-d2be4b6a-ea2e-412a-b53a-d41ee5f1b5dc.png">

### Expected Behavior

Please do not print them at all - it's better than have important information lost in that forest.

### Steps to Reproduce

nx test does that sometimes.
It's not 100% reproducible, but happens quite often.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 19.2.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 15.3.3
   @nrwl/angular : 15.3.3
   @nrwl/cypress : 15.3.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.9.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @ngrx/component-store: 15.0.0
         @ngrx/effects: 15.0.0
         @ngrx/store: 15.0.0
         @jefiozie/ngx-aws-deploy: 5.0.0
         @ngrx/eslint-plugin: 15.0.0
```

### Additional Information

macOS 13.1

**Comment by AgentEnder** [comment]
@barbados-clemens I am not sure that this is testing related, but the report mentions it happening under `test` command. Can you take a look? Feel free to unscope it if you find its not related.

**Comment by barbados-clemens** [comment]
@AgentEnder looks to happen when the terminal window is small/resized and results are bring printed. doesn't look to be test related as I can _kind of_ reproduce it with running all builds. but still doesn't look like above. most likely an issue with core in the dynamic terminal output.

**Comment by e-oz** [comment]
Not sure what size should be terminal. This is the WebStorm built-in Terminal, wasn't resized after IDE launch today:
<img width="1614" alt="Screenshot 2022-12-30 at 09 40 44" src="https://user-images.githubusercontent.com/526352/210051514-82e95d75-ac49-431e-94d8-4b9c00200667.png">
<img width="1614" alt="Screenshot 2022-12-30 at 09 40 57" src="https://user-images.githubusercontent.com/526352/210051518-989d6818-87ff-44bc-a724-2393893ff468.png">
<img width="1615" alt="Screenshot 2022-12-30 at 09 41 18" src="https://user-images.githubusercontent.com/526352/210051521-c4ce4d33-4498-4662-bfc6-393fab170925.png">
<img width="1615" alt="Screenshot 2022-12-30 at 09 41 37" src="https://user-images.githubusercontent.com/526352/210051523-ab9f9193-8fd7-4d64-9031-79eb6dc54a80.png">
<img width="1615" alt="Screenshot 2022-12-30 at 09 41 49" src="https://user-images.githubusercontent.com/526352/210051524-10bad1a9-ba53-4952-ad20-b21fcee0d3a3.png">

**Comment by e-oz** [comment]
It is still annoying issue, 16.4
