### ISSUE TITLE
Add support for cypress 12.x

### ISSUE THREAD

**Issue by keth-dev** [nrwl/nx#13846]
## Description
Cypress v12 added feature to test multiple origins in a single test with the new [cy.origin()](https://docs.cypress.io/api/commands/origin) command.

## Suggested Implementation
Support Cypress v12 and provide migration script.

**Comment by tracymazelin** [comment]
Another plus 1 for supporting Cypress v12!

**Comment by atanaskanchev** [comment]
+1

**Comment by barbados-clemens** [comment]
It's in the works, Cypress 12 has quite a lot of breaking changes and some are quite subtle so working on the best way forward to help migrate what we can and not break everything along the way.
