### ISSUE TITLE
Add support for Next 13 app directory and client components

### ISSUE THREAD

**Issue by atanaskanchev** [nrwl/nx#13849]
## Description
Add support for the Next.js 13/React 18 client components.

## Motivation
Currently, at 15.3.3 the "use client" directive is not being passed to the compiled files in a shared library

**Comment by caioquirino** [comment]
I also would like to see the app directory working

**Comment by Shooshte** [comment]
Currently seems to be working fine for me while developing, but this happens when trying to build: https://github.com/nrwl/nx/issues/14558

**Comment by simonpeters** [comment]
anyone found a solution for this?

**Comment by ndcunningham** [comment]
This is currently supported as of v16.0.0
Release: https://github.com/nrwl/nx/releases/tag/16.0.0
PR: https://github.com/nrwl/nx/pull/16132
