### ISSUE TITLE
@nrwl/angular - Prototype pollution in webpack loader-utils

### ISSUE THREAD

**Issue by jansgescheit** [nrwl/nx#13869]
### Current Behavior

`npm audit` throws 3 critical severity vulnerabilities

### Expected Behavior

a npm audit report without critical vulnerabilities

### Steps to Reproduce

1.  run `npm audit` or `npm i`

### Nx Report

```shell
Node : 18.7.0
   OS   : darwin x64
   npm  : 8.19.3
   
   nx : 14.8.6
   @nrwl/angular : 14.8.6
   @nrwl/cypress : 14.8.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.1.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.6
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.6
   @nrwl/js : 14.8.6
   @nrwl/linter : 14.8.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.6
   @nrwl/web : Not Found
   @nrwl/webpack : 14.8.6
   @nrwl/workspace : 14.8.6
   typescript : 4.8.4
```

### Failure Logs

```shell
# npm audit report

loader-utils  <=1.4.1
Severity: critical
Prototype pollution in webpack loader-utils - https://github.com/advisories/GHSA-76p3-8jx3-jpfq
loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS) via url variable - https://github.com/advisories/GHSA-3rfm-jhwj-7488
loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS) - https://github.com/advisories/GHSA-hhq3-ff78-jv3g
fix available via `npm audit fix --force`
Will install @nrwl/angular@15.3.3, which is a breaking change
node_modules/@nrwl/webpack/node_modules/loader-utils
  @nrwl/webpack  <=15.0.10
  Depends on vulnerable versions of loader-utils
  node_modules/@nrwl/webpack
    @nrwl/angular  14.7.6-beta.0 - 15.0.10
    Depends on vulnerable versions of @nrwl/webpack
    node_modules/@nrwl/angular
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This has been fixed in later versions of `@nrwl/webpack` as the `npm audit` report mentions. You need to update your `@nrwl/*` and `nx` packages to a version that is fixed. You have a couple of options depending on whether you can/want to update to Angular v15:

- If you can/want to update to Angular v15, you can run `nx migrate latest`
- If you can't update to Angular v15, you can run `nx migrate 15.1.1` ([recommended Nx version that supports Angular v14](https://nx.dev/packages/angular/documents/angular-nx-version-matrix))

Doing any of the above solves the issue.

I'm closing this since the issue has been resolved in the latest versions of Nx.

**Comment by jansgescheit** [comment]
> Thanks for reporting this!
> 
> This has been fixed in later versions of `@nrwl/webpack` as the `npm audit` report mentions. You need to update your `@nrwl/*` and `nx` packages to a version that is fixed. You have a couple of options depending on whether you can/want to update to Angular v15:
> 
> * If you can/want to update to Angular v15, you can run `nx migrate latest`
> * If you can't update to Angular v15, you can run `nx migrate 15.1.1` ([recommended Nx version that supports Angular v14](https://nx.dev/packages/angular/documents/angular-nx-version-matrix))
> 
> Doing any of the above solves the issue.
> 
> I'm closing this since the issue has been resolved in the latest versions of Nx.

thanks! i assumed that nx5 requires angular15, but `nx migrate 15.1.1` does the job.
