### ISSUE TITLE
Tests are failing to run after migrating from 14.5.10 to 14.6.0 or higher

### ISSUE THREAD

**Issue by DePavlenko** [nrwl/nx#13888]
### Current Behavior

I've migrated from 14.5.10 to 14.6.0 (also tried higher versions) with **@nrwl/workspace@14.6.0** and **nx migrate --run-migrations**. After successful migrating I started getting this error - **Test environment jest-environment-jsdom cannot be found. Make sure the testEnvironment configuration option points to an existing node module.**  To fix it I run **yarn add -D jest-environment-jsdom**.  But now my tests just wont run.

It seems to be related to this issue - https://github.com/nrwl/nx/issues/12744. But I tried 15.0.1 and higher with the same luck.

### Expected Behavior

Tests should at least run

### Steps to Reproduce

1. Update from 14.5.10 to 14.6.0 or higher
2. Try to run tests

### Nx Report

```shell
Node : 16.18.1
OS   : darwin x64
yarn : 1.22.19

nx : 15.0.1
@nrwl/angular : Not Found
@nrwl/cypress : 15.0.1
@nrwl/detox : Not Found
@nrwl/devkit : 15.0.1
@nrwl/esbuild : Not Found
@nrwl/eslint-plugin-nx : 15.0.1
@nrwl/expo : Not Found
@nrwl/express : Not Found
@nrwl/jest : 15.0.1
@nrwl/js : 15.0.1
@nrwl/linter : 15.0.1
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/nx-cloud : 15.0.2
@nrwl/nx-plugin : Not Found
@nrwl/react : 15.0.1
@nrwl/react-native : Not Found
@nrwl/rollup : 15.0.1
@nrwl/schematics : Not Found
@nrwl/storybook : 15.0.1
@nrwl/web : 15.0.1
@nrwl/webpack : 15.0.1
@nrwl/workspace : 15.0.1
typescript : 4.8.4
---------------------------------------
Local workspace plugins:
---------------------------------------
Community plugins:

✨  Done in 1.29s.
```

### Failure Logs

```shell
yarn test                 
yarn run v1.22.19
$ nx test

> nx run admin:test

Test Suites: 0 of 18 total
Tests:       0 total
Snapshots:   0 total
Time:        0 s

 >  NX   Ran target test for project admin (4s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by barbados-clemens** [comment]
do you have a repo I can clone to look at? I'm unable to reproduce this.
