### ISSUE TITLE
create-nx-workspace doesn't ask if I need cypress

### ISSUE THREAD

**Issue by e-oz** [nrwl/nx#13886]
### Current Behavior

create-nx-workspace doesn't ask if I need cypress, even with --allPrompts=true and --interactive

So after creating a new angular workspace, I need to remove all these cypress-related things first :(

### Expected Behavior

Please ask if I need cypress added to dependencies, and if e2e apps and configs should be generated.

### Steps to Reproduce

1. npx create-nx-workspace@latest --interactive=angular --allPrompts=true --packageManager=yarn 

### Nx Report

```shell
does not exist yet ;)
```

**Comment by Coly010** [comment]
This isn't supported by a preset, and it won't be.

However, you can achieve the same by doing:

1. `npx create-nx-workspace --preset=empty`
2. `npm install --save-dev @nrwl/angular`
3. `nx g @nrwl/angular:app app1 --rootProject --e2eTestRunner=none`
