### ISSUE TITLE
@nrwl/vite:build should expose cssCodeSplit as an option

### ISSUE THREAD

**Issue by ozee** [nrwl/nx#13881]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
To have `cssCodeSplit` exposed as an executor option.

## Motivation
I am trying to use vite as a build tool for a Lit library where we would normally build the css into the js bundle.

## Suggested Implementation
Inside your `project.json` under your build target using the `@nrwl/vite:build` executor we could pass an option for `cssCodeSplit` or as apart of the `vite.config.ts` config file.

```json
{
  ...
  "targets": {
    "build": {
      "executor": "@nrwl/vite:build",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "build/packages/some-package",
        "cssCodeSplit": false
      }
    }
  }
  ...
}
```

**Comment by mandarini** [comment]
Hi there @ozee ! Thanks for the feature request. You can pass `cssCodeSplit` in your project's `vite.config.ts` file under the `build` options, as normal. Is there a reason why you would prefer to pass this through `project.json` instead?

**Comment by mandarini** [comment]
We are supporting all the Vite CLI options, but the [configuration options](https://vitejs.dev/config/) we suggest it's better to add them in your `vite.config.ts` file instead. However, do let me know if you are working on a use case that needs the `project.json` options instead, and I can re-open this issue!

**Comment by ozee** [comment]
hey @mandarini, whenever I passed it in my `vite.config.ts` file I still had css output, although it was also in my js file.

**Comment by mandarini** [comment]
Hm I see! Maybe that's an issue with `vite` then! Whatever is in `vite.config.ts` get directly sent to vite! Can you make sure that this is an issue with just `vite` and not Nx? You can try this by setting a pure vite app!
