### ISSUE TITLE
Workspace-generator not working as expected with Nx 15.3.3

### ISSUE THREAD

**Issue by IThordGray** [nrwl/nx#13897]
### Current Behavior

I create a new workspace generator called dummy-lib [SUCCESS]
I run the dummy generator [FAILED]

Error messages
node_modules/@nrwl/workspace/src/generators/library/schema.d.ts:2:1 - error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.

2 const { Linter } = require('@nrwl/linter');
  ~~~~~

node_modules/@nrwl/workspace/src/generators/library/schema.d.ts:2:20 - error TS1254: A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference.

2 const { Linter } = require('@nrwl/linter');
                     ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@nrwl/workspace/src/generators/library/schema.d.ts:12:12 - error TS2749: 'Linter' refers to a value, but is being used as a type here. Did you mean 'typeof Linter'?

12   linter?: Linter;

If I add @ts-ignore in my node modules on those lines, it seems to work.

### Expected Behavior

It should generate and work without having to modify node_module files

### Steps to Reproduce

1. Create new workspace; npx create-nx-workspace@latest
2. Use Nx console to generate new workspace-generator (nx generate @nrwl/workspace:workspace-generator dummy-lib)
3. Use Nx console to use the new generator (npx nx workspace-generator dummy-lib dummy)

### Nx Report

```shell
Node : 18.12.1
   OS   : win32 x64
   npm  : 8.19.2
   
   nx : 15.3.3
   @nrwl/angular : 15.3.3
   @nrwl/cypress : 15.3.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
2 const { Linter } = require('@nrwl/linter');
  ~~~~~

node_modules/@nrwl/workspace/src/generators/library/schema.d.ts:2:20 - error TS1254: A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference.

2 const { Linter } = require('@nrwl/linter');
                     ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@nrwl/workspace/src/generators/library/schema.d.ts:12:12 - error TS2749: 'Linter' refers to a value, but is being used as a type here. Did you mean 'typeof Linter'?

12   linter?: Linter;
```

**Comment by bosycom** [comment]
This issue might depend on which options you chose when starting the workspace. So which options did you choose? Just want to let you know that it worked for me when I followed the same steps you mentioned and I chose the option monorepo, react, CSS. Also maybe clearing the npm cache works? Only difference that I noticed is that I am on Node 8.12.0

Here is my nx report
```
   Node : 18.12.0
   OS   : win32 x64
   npm  : 8.19.2

   nx : 15.3.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.3.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.3.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.3.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.3.3
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by isaacplmann** [comment]
Closing.  For anyone coming here later, please use local plugin generators and not workspace-generators.
https://nx.dev/deprecated/workspace-generators

**Comment by garydex** [comment]
@isaacplmann Is there any recommended way to convert an existing workspace-generator to a local plugin?

**Comment by isaacplmann** [comment]
@garydex , yes.  The link I shared has instructions for converting your generators.  You generate a plugin with a generator and then copy the code over.
