### ISSUE TITLE
Bug 15.3.3: can not find configuration if colon (`:`) is used in a name of npm script, like `build:dev`

### ISSUE THREAD

**Issue by valorkin** [nrwl/nx#13898]
### Current Behavior

` npx nx run lib-zero:build:dev --verbose` 

results in

Important: I am running `build:dev`, but task graph is run with `build` target, because colon has a special meaning

```bash
 >  NX   Cannot find configuration for task lib-zero:build


Error: Cannot find configuration for task lib-zero:build
    at ProcessTasks.createTask (__root_folder__\client-generate\node_modules\nx\src\tasks-runner\create-task-graph.js:98:19)
    at ProcessTasks.processTasks (__root_folder__\client-generate\node_modules\nx\src\tasks-runner\create-task-graph.js:19:35)
    at createTaskGraph (__root_folder__\client-generate\node_modules\nx\src\tasks-runner\create-task-graph.js:133:21)    
    at __root_folder__\client-generate\node_modules\nx\src\tasks-runner\run-command.js:83:71
    at Generator.next (<anonymous>)
    at __root_folder__\client-generate\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (__root_folder__\client-generate\node_modules\tslib\tslib.js:114:16)
    at __root_folder__\client-generate\node_modules\nx\src\tasks-runner\run-command.js:79:114
    at __root_folder__\client-generate\node_modules\nx\src\utils\params.js:10:26
```

### Expected Behavior

should build :D

### Steps to Reproduce

1. npx create-nx-workspace with react
2. generate react lib with config:npmScripts
3. rename `build` to `build:dev` in `package.json` of lib
4. try to build it

### Nx Report

```shell
Node : 18.12.1
   OS   : win32 x64
   npm  : 9.2.0

   nx : 15.3.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 15.3.3
   @nrwl/react : 15.3.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.3.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.3.3
   typescript : 4.8.4
```

**Comment by valorkin** [comment]
as a workaround, you can use something like:
```
{
  "name": "__your_project_name__",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "tags": [],
  "targets": {
    "build": {
      "executor": "nx:run-script",
      "options": {
        "script": "build:prod"
      },
      "configurations": {
        "dev": {
          "script": "build:dev"
        },
        "prod": {
          "script": "build:prod"
        }
      }
    }
  }
}
```

**Comment by AgentEnder** [comment]
This works, but there are a few caveats to know with the `run` syntax combined with this case:

`nx build:dev __your_project_name__` should work w/o caveats
`nx affected --target build:dev` should work w/o caveats

`nx run __your_project_name__:"build:dev"` **_should_** work (note the quotes).
- Unfortunately in a lot of cases the shell will consume the quotes before they are passed to Nx. You have to escape them. Try `nx run __your_project_name:\"build:dev\"`

**Comment by valorkin** [comment]
Then NX plugin for vs code should be updated to use this approach. Makes sense?

**Comment by valorkin** [comment]
Plus enabling caching for 'build:dev' has no effect, but caching for 'build' works.
I believe you closed to fast :)

**Comment by AgentEnder** [comment]
Caching should work, but I can validate that. If there is an issue with the console integration for these, can you open an issue on the console repo? https://github.com/nrwl/nx-console

**Comment by zackarychapple** [comment]
This is a combination of issues, the CLI itself is not working as expected and requires a workaround which is mentioned [here](https://github.com/nrwl/nx/issues/13898#issuecomment-1357789598). 

The second issue is the code that is being generated by the vs code plugin for the console is generating code that does not match the required workaround.

**Comment by valorkin** [comment]
@AgentEnder none of `nx run` options didn't worked
nx build and nx run-many and nx affected works as expected

**Comment by valorkin** [comment]
repo to reproduce https://github.com/valorkin/nx-cache-issue-13898

**Comment by AgentEnder** [comment]
Here is an example of it working, as expected, including the cache. The second issue is an nx-console issue and I'd recommend opening one there.

![image](https://user-images.githubusercontent.com/6933928/208496419-d8279709-c10b-4c43-b315-ce2a7633f126.png)

**Comment by AgentEnder** [comment]
Here's similar logs from the repo you uploaded: 
![image](https://user-images.githubusercontent.com/6933928/208497517-4c999b4a-4f21-45df-8626-372d4bb4e7bf.png)

**Comment by valorkin** [comment]
![image](https://user-images.githubusercontent.com/1107171/208497980-96913cf0-f7d5-452a-a4a3-1286af767312.png)
win PS, sorry forgot to mention

**Comment by AgentEnder** [comment]
You **_have_** to escape the quotes, or your shell will consume them

**Comment by AgentEnder** [comment]
> - Unfortunately in a lot of cases the shell will consume the quotes before they are passed to Nx. You have to escape them. Try nx run __your_project_name:\"build:dev\"

**Comment by valorkin** [comment]
@AgentEnder this is not expected behavior, and escaping quotes in PS is fun https://www.rlmueller.net/PowerShellEscape.htm#:~:text=Finally%2C%20if%20your%20PowerShell%20strings,%22%20characters%20with%20%22%22).

cc @juristr what do you think about it?

**Comment by Coly010** [comment]
@valorkin Does this work: 

```
npx nx run lib-npm-scripts:\`"build:dev\`"
```

If so, unfortunately, that's a limitation from PS. It's unrelated to Nx.

out of curiosity, does running this work for you?

```
npx nx build:dev lib-npm-scripts
```

The issue around Nx Console _not_ doing this should be raised as an issue on that repo.

**Comment by AgentEnder** [comment]
Escaping the quotes wouldn't be that hard... In PS the command looks something like this: 
```shell
npx nx run '"lib-npm-scripts:build:dev"'
```

As evidence that this should work, consider the following:
![image](https://user-images.githubusercontent.com/6933928/208500313-70c6c257-032d-44de-83f4-2e432143bdc5.png)
