### ISSUE TITLE
Hybrid Public-Private Monorepo: make some projects open source and some closed

### ISSUE THREAD

**Issue by JonathanWilbur** [nrwl/nx#13903]
- [ ] ~~I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))~~ (We'll see, depending on the approach that is decided upon, if there is one.)

Disclaimer: I don't know if everything I'm asking for is even possible. Even if my solution is not viable, I wanted to write up this feature request to at least get some discussion going on this topic. I have to imagine somebody out there has had this idea as well and might have come up with a solution already, in which case, closing this feature request would just be a matter of adding some documentation.

Yes, I have read [this issue](https://github.com/nrwl/nx/issues/1235) which only handles interrelated NPM packages.

## Description

I personally like to publish most libraries I create freely and open-sourced, but I use them to build applications that I would like to keep closed-source and proprietary. I would like all of these projects to be in one monorepo, however. Ideally, I would be able to publish a public subset of my monorepo to GitHub while still somehow obscuring the private repos from non-authorized people.

The repository might look like this if you were me, and you had access to everything in the monorepo:

```
/packages
  /libjpeg
  /libgif
  /libpng
  /photo-editing-app   <--   closed source / proprietary application
```

But if you looked at this same project on GitHub, you would see:

```
/packages
  /libjpeg
  /libgif
  /libpng
```

## Motivation

For the same reason that a monorepo is beneficial in general, it is beneficial to have _all_ of my code in a single repository, regardless of its intended secrecy: shared tooling, caching, etc. My current (unfortunate) approach is to have two monorepos: one for public code and one for private code.

## Suggested Implementation

I _think_ the easiest way to do something like this might rest primarily on git: the idea is that the whole repo would be public, but there would be a git submodule whose origin is private. There would be a `.gitignore` at the root of the monorepo that tells Git to ignore the folders of private projects, so that they don't accidentally get committed to the public repo. Then maybe, the `.gitignore` on the submodule would override the root `.gitignore` so that the private submodule could still have commits. (I'm not sure that's how it even works. I haven't used Git submodules, but I am thinking there must be a solution like this.)

At the very least, a solution like this would entail that:

1. Nx uses and supports the `project.json` style workspace (meaning that `workspace.json` just has a file path to a `project.json` in a subfolder), and
2. Nx can simply ignore a project being missing from the monorepo. (I just tested this locally by adding `"partyboi": "libs/partyboi",` to my `workspace.json` and running `nx run-many --target=test --all` and it immediately crashed, so this requirement is definitely not met.)

Finally, the above approach would still disclose the names of private projects in the monorepo. An even better modification to the above approach would be to support _recursive workspaces_: instead of the root-level `workspace.json` pointing to individual projects by name (e.g. `apps/proprietary-photo-editor`), it could refer to a _sub-workspace_ (e.g. `private/`).

## Alternate Implementations

I won't elaborate on these too much unless asked further, but I have two ideas that I think would be less desirable:

1. Nx tracking which projects and public and private and installing Git hooks that block commits of private code to public repos. (Problematic, because you can just skip hooks, and this could interfere with some workflows, possibly.)
2. Some kind of freaky mechanism for encrypting private code prior to commit, so it lives on public GitHub, encrypted. (Even worse.)

**Comment by AgentEnder** [comment]
`workspace.json` is no longer used, so this is solved in the recommended fashion already. Missing project.json's aren't a problem, because there is no record of that project ever having existed. You could combine this with git submodules or some mirroring mechanism to publish a portion of the workspace.
