### ISSUE TITLE
@nrwl/angular:move broken for moving a library in a subfolder

### ISSUE THREAD

**Issue by abf7d** [nrwl/nx#13910]
### Current Behavior

I created an angular library in my Nx workspace:
```
npx nx g @nrwl/angular:lib --name=my-library --importPath=@myorg/my-library
```

I then moved it into a sub folder of my libs folder:
nx g @nrwl/angular:move --project my-library shared/my-lib

It moves into the correct foler. After awhile I needed to move it agian. I try with the command:
```
nx g @nrwl/angular:move --project shared/my-library shared/lib-new-name
```
I get the following error:
```
>  NX  Generating @nrwl/angular:move
>  NX   Cannot find configuration for 'shared/my-library'
```

How do I fix this? Do I just make a copy of the library, delete it, generate a new one in the right subfolder, and copy the code into it? It seems to be a problem with moving a library in a sub folder.

### Expected Behavior

I expect that the library in the subfolder specified on the command line to be moved to the desired location.

### Steps to Reproduce

1) npx nx g @nrwl/angular:lib --name=my-library --importPath=@myorg/my-library
2) nx g @nrwl/angular:move --project my-library shared/my-lib
3) nx g @nrwl/angular:move --project shared/my-library shared/lib-new-name

### Nx Report

```shell
NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : win32 x64
   npm  : 8.1.2

   nx : 15.3.0
   @nrwl/angular : 15.3.0
   @nrwl/cypress : 15.3.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.0
   @nrwl/workspace : 15.3.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
>  NX  Generating @nrwl/angular:move
>  NX   Cannot find configuration for 'shared/my-library'
```

**Comment by DmitryEfimenko** [comment]
I got the same issue.
Here's my project: https://github.com/DmitryEfimenko/ngspot
The command I tried:  `nx g move --project remote-data remote-data/remote-data`
The error I get:
>  NX   Cannot find packages/remote-data/remote-data/project.json

Feel free to clone the project and try it for yourself.

**Comment by DmitryEfimenko** [comment]
bump

**Comment by abf7d** [comment]
When executing cli commands you need to swap out '/' for '-'.
So your command below 
nx g move --project remote-data remote-data/remote-data
 
Changes to

nx g move --project remote-data remote-data-remote-data

**Comment by amakhrov** [comment]
> When executing cli commands you need to swap out '/' for '-'.

This sounds accidentally insane. Is there a reason some commands/arguments accept the path, while other accept the "dashed" project name from angular.json? How does one memorize when to use what?

**Comment by DmitryEfimenko** [comment]
bump
