### ISSUE TITLE
Can't deselect not cacheable scripts in the init prompt

### ISSUE THREAD

**Issue by Maxim-Mazurok** [nrwl/nx#13916]
### Current Behavior

I ran `npx nx@latest init` command, it says:
```
? Which of the following scripts are cacheable? (Produce the same output given the same input, e.g. build, test and lint usually are, serve and start are not) ... 
√ bla
√ blabla
√ compile
```
I can't seem to find a way to remove checkmarks from any of the scripts. I've tried using space and "x" keys, but nothing works.	

### Expected Behavior

When I press the space or "x" key on the keyboard - it marks script as not cacheable (deselects it)

### Steps to Reproduce

1. Open cmd on existing project
2. Run `npx nx@latest init`
3. Try to unselect a script, observe that you can't

### Nx Report

```shell
The current directory isn't part of an Nx workspace.
```

### Additional Information

```
  System:
    OS: Windows 10 10.0.19044
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900H
    Memory: 43.45 GB / 63.68 GB
  Binaries:
    Node: 19.2.0 - ~\AppData\Local\nvs\default\node.EXE
    npm: 8.19.3 - ~\AppData\Local\nvs\default\npm.CMD
  Managers:
    pip3: 22.2.2 - ~\AppData\Local\Programs\Python\Python310\Scripts\pip3.EXE
  Utilities:
    Git: 2.39.0.
  SDKs:
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.19041.0, 10.0.20348.0, 10.0.22621.0
  IDEs:
    VSCode: 1.74.1 - C:\Users\maxim.mazurok\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
    Visual Studio: 17.3.32929.385 (Visual Studio Professional 2022)
  Languages:
    Bash: 5.1.16 - C:\WINDOWS\system32\bash.EXE
    Python: 3.10.6
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.46)
    Internet Explorer: 11.0.19041.1566
```

**Comment by Maxim-Mazurok** [comment]
Ok, actually it seems to work, but very confusing. Instead of changing "√" to "x" - it just changes the color.
First, I was expecting the "√" to go away or change to "x", but also I didn't notice the color change because it's very subtle. If it was changing from red to green - I'd notice, but going from grey to light green - I didn't notice the change. Might be a good idea to consider improving UX, cheers!

![image](https://user-images.githubusercontent.com/7756211/208539196-3b9255c0-6b30-4c30-9c89-a6d397f9ea93.png)

**Comment by AgentEnder** [comment]
Interesting, we don't do anything special here. Its a multiselect from `enquirer`, I'd recommend opening the issue there.
