### ISSUE TITLE
React commands ends up with an error: NX   Cannot find module 'typescript'

### ISSUE THREAD

**Issue by meitarkfuel** [nrwl/nx#13928]
### Documentation issue

- [ ] Reporting a typo
- [X ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.

### Additional context or description
>  NX   Cannot find module 'typescript'

   Require stack:
   - c:\projects\test\monorepo\node_modules\nx\src\project-graph\build-dependencies\typescript-import-locator.js
   - c:\projects\test\monorepo\node_modules\nx\src\project-graph\build-dependencies\explicit-project-dependencies.js
   - c:\projects\test\monorepo\node_modules\nx\src\project-graph\build-dependencies\index.js
   - c:\projects\test\monorepo\node_modules\nx\src\project-graph\build-project-graph.js
   - c:\projects\test\monorepo\node_modules\nx\src\project-graph\project-graph.js
   - c:\projects\test\monorepo\node_modules\nx\src\command-line\generate.js
   - c:\projects\test\monorepo\node_modules\nx\src\command-line\nx-commands.js
   - c:\projects\test\monorepo\node_modules\nx\bin\init-local.js
   - c:\projects\test\monorepo\node_modules\nx\bin\nx.js

Provide any additional details here as needed.

**Comment by meitarkfuel** [comment]
Verbose error:
Error: Cannot find module 'typescript'
Require stack:
- c:\projects\test\monorepo\node_modules\@nrwl\workspace\src\utilities\typescript\compilation.js
- c:\projects\test\monorepo\node_modules\@nrwl\workspace\src\utilities\typescript.js
- c:\projects\test\monorepo\node_modules\@nrwl\cypress\src\generators\cypress-project\cypress-project.js
- c:\projects\test\monorepo\node_modules\@nrwl\cypress\index.js
- c:\projects\test\monorepo\myorg\node_modules\@nrwl\react\src\generators\init\init.js
- c:\projects\test\monorepo\myorg\node_modules\@nrwl\react\src\generators\application\application.js
- c:\projects\test\monorepo\myorg\node_modules\@nrwl\react\src\generators\host\host.js
- c:\projects\test\monorepo\myorg\node_modules\nx\src\config\workspaces.js
- c:\projects\test\monorepo\myorg\node_modules\nx\src\config\configuration.js
- c:\projects\test\monorepo\myorg\node_modules\nx\src\command-line\generate.js
- c:\projects\test\monorepo\myorg\node_modules\nx\src\command-line\nx-commands.js
- c:\projects\test\monorepo\myorg\node_modules\nx\bin\init-local.js
- c:\projects\test\monorepo\myorg\node_modules\nx\bin\nx.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (c:\projects\test\monorepo\myorg\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (c:\projects\test\monorepo\node_modules\@nrwl\workspace\src\utilities\typescript\compilation.js:7:12)
    at Module._compile (c:\projects\test\monorepo\myorg\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)

c:\projects\test\monorepo\myorg>node -v
v18.12.1

**Comment by fsgreco** [comment]
Are you using a `package-based` monorepo? 
If yes then this issue could be related (I've also added my temporal solution to the problem): https://github.com/nrwl/nx/issues/13977

**Comment by isaacplmann** [comment]
We'll need some steps to reproduce in order to do anything here.
