### ISSUE TITLE
jasmine-marbles should not be a peer dependency

### ISSUE THREAD

**Issue by alfaproject** [nrwl/nx#1394]
## Expected Behavior

`jasmine-marbles` should not be a required peer dependency, because not everyone uses `jasmine`.

## Current Behavior

I'm trying to update my workspace to the latest rc and I get an error message saying my workspace has a missing peer dependency of `jasmine-marbles`.

```console
$ ./node_modules/.bin/ng update @nrwl/nx --next
    Package "@nrwl/nx" has a missing peer dependency of "jasmine-marbles" @ "*".
Incompatible peer dependencies found. See above.
```

### Steps to Reproduce

1. Create a workspace using the current stable version
2. Remove `jasmine-marbles` (because I don't use it)
3. Try to update workspace to `next` version

### Context

- version of Nx used: `7.8.1`
- version of Angular CLI used: `7.3.8`
- version of Angular DevKit used: `0.13.8`

**Comment by vsavkin** [comment]
Yup. This is a left-over from earlier times when we assume that you use Jamine. We should remove it. We should also update ng-add scripts not to add jasmine-marbles to `package.json`.

Would you like to send a PR making the change? I can give you some pointers.

**Comment by SebasG22** [comment]
I had the same problem when tried to upgrade some workspaces to nx8.
@alfaproject thanks for the fix.
While a new version with the patch is released, you can do :
```bash
$ yarn install jasmine-marbles
$ yarn update
```

**Comment by SebasG22** [comment]
@vsavkin @alfaproject  Waiting for this be released. 👍

**Comment by SebasG22** [comment]
I'm getting this error when try to make an update to NX8.
![image](https://user-images.githubusercontent.com/17608169/58755863-21f10700-84b2-11e9-98fc-c0486a65fdfd.png)

**Comment by vsavkin** [comment]
@SebasG22 could you try updating to 8.0.2?

**Comment by SebasG22** [comment]
Hey @vsavkin, 
Seems like I have some problems with global dependency to NX and angular CLI.
I removed it using: 
```bash
yarn global list 
yarn global remove @angular/cli 
```
Then run `rm -rf node_modules` on the monorepo and install the dependencies again `yarn install`.
Finally use `yarn update` and the command finish successfully.
Thanks 👍

**Comment by vsavkin** [comment]
Cool. I'm going to close this issue then.
