### ISSUE TITLE
[Vite] add a target for type checking

### ISSUE THREAD

**Issue by vicb** [nrwl/nx#13954]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

It would be great to have a `typecheck` target when vite is used to check the types.

Probably `build:production` should depend on this target.

## Motivation

If you create a vite app and set the content of main.ts to:

```typescript
function error(param: number) {
    console.log(param);
}

error("abc");

export {};
```

_(Notice `"abc"` vs the expected `number` type.)_

The `build` target will happily compiles this code.

While it's great to skip type check in to have a better (=faster) dev experience there should be a way to check the types and it would be nice to do it when building the production configuration.

## Suggested Implementation

Use `tsc --noEmit` to check types.

**Comment by mandarini** [comment]
Hi there @vicb ! Thanks for creating this feature request. I see you are happy to implement this feature. Do you want to give this a shot, and assign the PR to me for review? I can help you if you need!

**Comment by vicb** [comment]
I could try to take a look at that but I will certainly need help.

As I'm getting more familiar with Nx I think the steps would be:

1. Add a `typecheck` executor in the JS package,
2. Generate a `typecheck` target using this executor from in the `vite:configuration` generator.

Would that be a good start?

**Comment by mandarini** [comment]
How would you do this typechecking outside of Nx context, if you had a pure React+Vitejs app? I mean, if it's a script you set up, maybe there's no need to create a new executor. Maybe you can just create a new target that calls `run-commands`. But I am not sure how this would be set up.

**Comment by mandarini** [comment]
Yes, I think the [vite-plugin-checker](https://vite-plugin-checker.netlify.app/) seems like a better option in this case.

**Comment by vicb** [comment]
[vite-plugin-checker](https://vite-plugin-checker.netlify.app/) after updating the plugins config as:

```ts
// vite.config.ts
import { checker } from 'vite-plugin-checker';

// ...

  plugins: [
    checker({
      typescript: {
        tsconfigPath: 'tsconfig.app.json',
      },
    }),
    viteTsConfigPaths({
      root: '../../',
    }),
  ],
```

requires
```
npm i -D vite-plugin-checker
```

**Comment by mandarini** [comment]
A typecheck target could look like: 

```
    "vite-typecheck": {
      "executor": "nx:run-commands",
      "options": {
        "command": "tsc --noEmit -p <prjoject-root>/tsconfig.app.json"
      }
    }
```

You can check out [this PR](https://github.com/nrwl/nx/pull/11101) which does something along these lines.

**Comment by vicb** [comment]
Hey @mandarini do you want me to work on a PR along the lines of your last message?
My understanding from your [previous comment](https://github.com/nrwl/nx/issues/13954#issuecomment-1370055273) was that we should use the vite plugin instead?

**Comment by mandarini** [comment]
Hello @vicb ! Yes, sure, work on that PR! :)

**Comment by vicb** [comment]
We can probably use https://github.com/nrwl/nx/blob/master/packages/js/src/utils/typescript/run-type-check.ts

I'll take a look at that next

**Comment by jonybekov** [comment]
Any news regarding this https://github.com/nrwl/nx/blob/master/packages/js/src/utils/typescript/run-type-check.ts?

**Comment by Lonli-Lokli** [comment]
According to the documentation https://nx.dev/nx-api/vite/executors/build#skiptypecheck
it should just work. Unfortunately in my project with (publishabl & buildablee)library generation no TypeScript errors are reported

**Comment by mandarini** [comment]
I am closing this issue because indeed it should work, and we are shifting things around with targets, too, at the moment.
