### ISSUE TITLE
Getting error: NX   Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by manojgetwealthy** [nrwl/nx#13974]
### Current Behavior

Getting the following error while running any of the nx commands:

 NX   Cannot read properties of undefined (reading 'data')

### Expected Behavior

nx commands should work as expected

### Steps to Reproduce

1. Add a next application using following document: https://nx.dev/packages/next/documents/overview
2. Install a local package in tgz format: e.g-> (Entry in package.json is -> "wealthy-ui-utils": "wealthy-ui-utils-1.0.35.tgz"). npm i wealthy-ui-utils
3. Run any nx command

### Nx Report

```shell
NX   Cannot read properties of undefined (reading 'data')
```

### Additional Information

This error comes after installing a local package (made using npm pack).

**Comment by AgentEnder** [comment]
Hey @manojgetwealthy! This should be fixed in 15.4.0, can you migrate and try?

**Comment by manojgetwealthy** [comment]
@AgentEnder The issue has been resolved with nx version 15.4.2
