### ISSUE TITLE
do not install e2e dependencies when using --no-e2e

### ISSUE THREAD

**Issue by tbogard** [nrwl/nx#13989]
I'm facing an issue that is affecting a proposal of a new codebase in the company I work which has strict download policies.

when using `npx create-nx-workspace my-workspace --preset=angular --e2e=none` I was expecting that cypress won't be installed (I am proposing on the place I work to allow downloads, but for the moment I need to start working on code) until we got the approval.

## Description

if using 
```
$ npx create-nx-workspace --e2e=none
```

the workspace should not have in the list of dependencies cypress. 

the user later on can add cypress (when is available and allowed in my case) I should be able to run the required generator to run Cypress tests

## Motivation

in certain workplaces that run artifactory, you won't be able to download the binaries of (for example) cypress. this will prevent Nx to break in situations where there's no need of e2e, or, in my case, to break while proposing the use Nx for future company projects. Once the situation with cypress is fixed, I can just run the generator

## Suggested Implementation

if I run 
```
$ npx create-nx-workspace --e2e=none
```

cypress won't be listed on the list of dependencies in the package.json of the project, and the installation of the workspace won't be breaking because it can't download the binaries in places where have strict download policies.

## Alternate Implementations

we could potentially provide a binary path to create-nx-workspace where it can pick the binaries for cypress:

```
$ npx create-nx-workspace --e2e=cypress --e2e-setup-binary=/c/users/myuser/downloads/cypressSetup.exe
```
in that way, we can tell cypress to take the binary from that path instead of the default one.

**Comment by FrozenPandaz** [comment]
Have you tried to use these environment variables?

https://docs.cypress.io/guides/references/advanced-installation#Environment-variables

**Comment by tbogard** [comment]
yes, still in my workplace I can't do that to all devs while we feature Nx to stakeholders. I can't afford to fail the setup @FrozenPandaz .

Rather, it would be useful to use `npx create-nx-workspace --e2e=none` and avoid having to have in package dependencies cypress. 

If we got approved, and in the process we onboard cypress, then the installation should run as usual with `npx create-nx-workspace`  where cypress is in the list of dependencies.

**Comment by barbados-clemens** [comment]
as a work around you can just make a new empty workspace

`npx create-nx-workspace --preset=apps`

then install the angular plugin
`npm i -E @nrwl/angular` (note the -E, we want to use the exact version as that's the next convention)

then generate a new app without an e2e test runner

`npx nx g app --e2e-test-runner=none`
`npx nx g app --help` to see all options (or use Nx Console VSCode extension)


Unsure if create-nx-workspace should pass extra args down or not. 

it seems to see the args and attempt to pass the args to the underlying generator
https://github.com/nrwl/nx/blob/master/packages/create-nx-workspace/bin/create-nx-workspace.ts#L244
so surprised `npx create-nx-workspace --preset=angular --e2e-test-runner=none` doesn't work. 

though there is a couple layers of arg passing and I'm not super familiar with this part. doesn't look to be specific to testing though.

**Comment by tbogard** [comment]
Thanks for keeping an eye on this request. in theory if you don't need a e2e test runner from create-nx-workspace, it shouldn't install cypress. Later on, a different generator can help to fix the issue

any news @FrozenPandaz ?
