### ISSUE TITLE
@nrwl/js package.json inconsistent output location

### ISSUE THREAD

**Issue by dustyhorizon** [nrwl/nx#13991]
### Current Behavior

Building via the `@nrwl/js:tsc` executor writes package.json to `outputPath` relative to the workspace root (repo root) whilst artifacts produced by tsc is written to `outputPath` relative to project root.

I stumbled upon this when I am trying to configure the `dist` (output folder) to be under each project instead of anchoring it at repo root.

### Expected Behavior

Building via the `@nrwl/js:tsc` executor `outputPath` should write artifacts (*.js files and package.json) to a consistent location (either relative to workspace root or project root)

### Steps to Reproduce

0. Sorry for not having a repo ready.
1. Configure a target to use `@nrwl/js:tsc` executor with the necessary options, configure `outputPath` to `dist`
2. Run `pnpm nx run <project>:<target>`
3. `package.json` should be in `<repo root>/dist` whilst the produced *.js files should be `<project root>/dist`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.17.1
   OS   : linux x64
   npm  : 8.15.0

   nx : 15.3.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.3.3
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.9.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nx-go/nx-go: 2.7.0
```

### Additional Information

This is probably due to `nx` being run in the context of the repo root but `tsc` is running in the context of project root. This [line](https://github.com/nrwl/nx/blob/8572eed44ebe9ffd6eb492a92e034b865537cdfc/packages/js/src/utils/package-json/update-package-json.ts#L61) should probably check/ensure the correct path to write to (maybe resolve absolute path from option?)

**Comment by gxxcastillo** [comment]
Seeing this as well, though I'm running the `@nrwl/vite:build` executor and using tsc as the compiler.  The fix for me has been to manually update my outputPath from `dist/libs/project` to `dist/libs`
