### ISSUE TITLE
updating to --next is trying to install non-existent package @nrwl/angular@8.0.0

### ISSUE THREAD

**Issue by fxck** [nrwl/nx#1399]
Did 

> ng update @nrwl/schematics --next

which failed with

```
.....

UPDATE 
node_modules/@nrwl/workspace/src/schematics/workspace/files/tools/tsconfig.tools.json (212 bytes)
UPDATE tools/tsconfig.tools.json (212 bytes)
UPDATE tsconfig.json (672 bytes)
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/angular@8.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by FrozenPandaz** [comment]
Thanks for reporting this issue. This won't be an issue once the stable release is out. For now, please update your `package.json` with the latest RC: `8.0.0-rc.2`

**Comment by emilio-martinez** [comment]
@fxck if helpful, you can install `@nrwl/angular@next` and `@nrwl/workspace@next` first and then run the update schematic. That will circumvent the matching version error if you're intent with upgrading now.

**Comment by FrozenPandaz** [comment]
The stable version has been released so this issue should be fixed.
