### ISSUE TITLE
React component inside Angular app: import scss files issue 

### ISSUE THREAD

**Issue by maxwellfargoseCactus** [nrwl/nx#14003]
### Current Behavior

I am using react library  inside angular app but getting compilation issue 

![image](https://user-images.githubusercontent.com/49706940/209341785-0d6aad62-c088-42ff-b646-d9b48b27496a.png)

### Expected Behavior

solution should work 

### Steps to Reproduce

1.
no data

### Nx Report

```shell
nx
```

**Comment by AgentEnder** [comment]
Can you add a reproduction of this issue to help us better understand your expectations?

**Comment by maxwellfargoseCactus** [comment]
Please find below link I have created sample project for your reference 

[https://github.com/maxwellfargoseCactus/NxUpdateSample.git](url)

Issue 
![image](https://user-images.githubusercontent.com/49706940/213391587-f5f6156e-ac2c-4b4d-8c06-037596bd7ab9.png)


similar issue occurs in react lib also

**Comment by maxwellfargoseCactus** [comment]
Any updates ????????

**Comment by Coly010** [comment]
We don't support multi-framework Module Federation out of the box with Nx.

It leads to [Micro Frontend Anarchy](https://www.thoughtworks.com/radar/techniques/micro-frontend-anarchy).

Manfred Steyer has techniques that you could employ.

https://www.angulararchitects.io/aktuelles/multi-framework-and-version-micro-frontends-with-module-federation-your-4-steps-guide/

Closing as this is a Non-Issue for Nx

**Comment by maxwellfargoseCactus** [comment]
We are using angular 13 with react libraries  using  Nx and module federation its working fine but now we are using nx migration tool which will create an issue for us.

**Comment by maxwellfargoseCactus** [comment]
any updates??????
