### ISSUE TITLE
Feature request: simple API for reading the graph in node

### ISSUE THREAD

**Issue by edbzn** [nrwl/nx#14009]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Hello team, merry Christmas! :santa: 

I would like to read the Nx graph from outside Nx context, I'm actually writing several ESLint rules related to workspace organization and I need to read the graph to build the rules. 

## Motivation

I inspected the [enforce-module-boundaries](https://github.com/nrwl/nx/blob/d3e2d616d5da84c1e1ed42a28a535fcb9055dc64/packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts) rule and I noticed that there's some dark magic to access the Nx graph in ESLint, cf: [this logic in particular](https://github.com/nrwl/nx/blob/d3e2d616d5da84c1e1ed42a28a535fcb9055dc64/packages/eslint-plugin-nx/src/utils/project-graph-utils.ts) that set global variables, etc...

My question is simple, would it make sense to expose a simple API for reading the graph using node? Actually, it's not easily doable and it seems fragile to do it by calling internal APIs.

## Suggested Implementation

We could imagine a function in `@nrwl/devkit` that does all the necessary work to return the graph.

## Alternate Implementations

N/A

**Comment by AgentEnder** [comment]
Both readCachedProjectGraph and createProjectGraphAsync are exported from devkit, is there some functionality that you are wishing for?

**Comment by edbzn** [comment]
Closing as `readCachedProjectGraph` does the job. Thank you @AgentEnder.
