### ISSUE TITLE
nextjs 13.0.3 causes imported global css in libs to build error 

### ISSUE THREAD

**Issue by boompikachu** [nrwl/nx#14015]
### Current Behavior

If a component in a library has a global css import, the build will fail with error:

```
Global CSS cannot be imported from files other than your Custom <App>. Due to the Global nature of stylesheets, and to avoid conflicts, Please move all first-party global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://nextjs.org/docs/messages/css-global
```
It seems that next 13.0.3 causes the imported global .css from node_modules to fail due to global css conflict constraint. From what I found, it only happen when the import statement is in the lib. If imported directly in the nextjs pages, the build is successful.

It seems that (not sure) this is the culprit that cause NX lib to import global css to fail in nextjs. https://github.com/vercel/next.js/pull/42615

https://stackoverflow.com/questions/74862708/how-to-import-css-files-from-react-library-inside-libs-to-next-js-app-in-nx-inte/74908688#74908688

### Expected Behavior

The next application should build successful even if global import is present in the lib. 

If the global import is in the next application `/apps/next-project/*` instead of `/libs/ui/*`, the build will pass

importing global css from node_module is allowed in nextjs
https://nextjs.org/docs/basic-features/built-in-css-support#import-styles-from-node_modules 

### Steps to Reproduce

Note that nextjs version should be 13.0.3 or higher and nx 15.3 or higher
 
1. `pnpm i react-nice-dates date-fns`
2. create nextjs app and react lib component
3. add `import 'react-nice-dates/build/style.css'` to component
4. import component into next app

### Nx Report

```shell
Node : 18.12.1
   OS   : darwin arm64
   pnpm : 7.18.2
   
   nx : 15.3.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.3.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : 15.3.3
   @nrwl/next : 15.3.3
   @nrwl/node : 15.3.3
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 15.3.3
   @nrwl/react : 15.3.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.3.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.3.3
   @nrwl/web : 15.3.3
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.9.4
   ---------------------------------------
   Community plugins:
         @nx-plus/docusaurus: 12.2.0
```

**Comment by gocreating** [comment]
same here

**Comment by lukehillonline** [comment]
Also experiencing this.

**Comment by soniktrooth** [comment]
I have this issue as well.

**Comment by victorcarvalhosp** [comment]
Same issue here

**Comment by sauldeleon** [comment]
Still happening. Thanks for raising the issue @boompikachu

**Comment by dawinValenzuela** [comment]
samme issue here

**Comment by ndcunningham** [comment]
Yes, this is a known issue. Global styles cannot be imported like that with Next.js: 
Here is the RFC https://github.com/vercel/next.js/discussions/27953

You would have to import them inside your `_app.tsx` or `layout.tsx` depending on your router (app/page)
