### ISSUE TITLE
Latest nx and @nrwl/angular:webpack-server executor gives schema validation error when running "serve"

### ISSUE THREAD

**Issue by dkrantsberg** [nrwl/nx#14025]
### Current Behavior

We're using `@nrwl/angular:webpack-browser` and `@nrwl/angular:webpack-server` executors.
After upgrading to latest (v15.4.1) version of `nx` and `@nrwl/angular` serve command started throwing an error:  
**Required property 'outputPath' is missing** 

The error is being thrown inside validateOptsAgainstSchema() > validateObject() function: 

https://github.com/nrwl/nx/blob/d13bcfe12368eaf981d77a5790aca74ad08abc28/packages/nx/src/utils/params.ts#L269

### Expected Behavior

Angular app should be served without an error being thrown.

### Github Repo

https://github.com/dkrantsberg/nx-angular-monorepo

### Steps to Reproduce

1. Create monorepo `npx create-nx-workspace@latest`: 
        ✔ Choose your style                     · integrated
        ✔ What to create in the new workspace   · angular
        ✔ Repository name                       · nx-angular-monorepo
        ✔ Application name                      · an-angular-app
        ✔ Default stylesheet format             · scss
        ✔ Enable distributed caching to make your CI faster · Yes 
2.  Edit project.json to replace `@angular-devkit/build-angular:browser` and `@angular-devkit/build-angular:dev-server` with `@nrwl/angular:webpack-browser` and `@nrwl/angular:webpack-server` respectively. 
3. Run `nx run an-angular-app:serve:development`

### Nx Report

```shell
Node : 16.18.1
   OS   : darwin arm64
   npm  : 8.19.2
   
   nx : 15.4.1
   @nrwl/angular : 15.4.1
   @nrwl/cypress : 15.4.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.1
   @nrwl/js : 15.4.1
   @nrwl/linter : 15.4.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.4.1
   @nrwl/workspace : 15.4.1
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by Coly010** [comment]
Hey :)

You've replaced the serve target with the wrong executor.

You should use `@nrwl/angular:webpack-dev-server` instead of `@nrwl/angular:webpack-server` for the `serve` target.

Just as an FYI, the `@nrwl/angular:webpack-server` executor is for building SSR applications :).

**Comment by dkrantsberg** [comment]
@Coly010 That worked, thank you! 
For some reason `@nrwl/angular:webpack-serve` executor worked in previous versions.
