### ISSUE TITLE
Code coverage generate bad package name

### ISSUE THREAD

**Issue by Authfix** [nrwl/nx#14021]
### Current Behavior

When we run tests via command `nx test <project-name> --code-coverage` with cobertura reporter, the generated xml (cobertura-coverage.xml) file does not have an explicit package name. 

The name of the package is simply 'main' for apps. 

`
<package name="main" line-rate="1" branch-rate="1"> // Content inside package remove for brevity // </package>
`

So when we  generate a code coverage report it will lead to the following screen

![image](https://user-images.githubusercontent.com/3940727/209555807-953e800f-3c9b-4e78-8428-6d92e9b429fb.png)

### Expected Behavior

In a monorepo structure, maybe we can expect to have the project name inside the package name to help us understand what systems was under test (like 'sample1.main').

### Github Repo

https://github.com/Authfix/nx-tests-package-name-issue

### Steps to Reproduce

1. (Optional) Use visual studio code dev. container provided
2. Run `npm install`
3. Run `nx test sample1 --code-coverage`
4. Go to folder coverage/apps/sample1 and open cobertura-coverage.xml. You'll see the package name as only 'main'. 

Do the same for sample2.

### Nx Report

```shell
Node : 16.19.0
OS   : linux x64
npm  : 8.19.3

nx : 15.3.3
@nrwl/angular : 15.4.1
@nrwl/cypress : 15.4.1
@nrwl/detox : Not Found
@nrwl/devkit : 15.3.3
@nrwl/esbuild : Not Found
@nrwl/eslint-plugin-nx : 15.4.1
@nrwl/expo : Not Found
@nrwl/express : Not Found
@nrwl/jest : 15.4.1
@nrwl/js : 15.4.1
@nrwl/linter : 15.4.1
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/nx-cloud : Not Found
@nrwl/nx-plugin : Not Found
@nrwl/react : Not Found
@nrwl/react-native : Not Found
@nrwl/rollup : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : Not Found
@nrwl/web : Not Found
@nrwl/webpack : 15.4.1
@nrwl/workspace : 15.3.3
typescript : 4.8.4
---------------------------------------
Local workspace plugins:
---------------------------------------
Community plugins:
```

### Additional Information

Thank you for nx, it's an amazing tool !

**Comment by barbados-clemens** [comment]
this is the source code from the reporter
https://github.com/istanbuljs/istanbuljs/blob/fb8cb4bb99c9e5d36c8b011338d2ab5d3c72ff9c/packages/istanbul-reports/lib/cobertura/index.js#L63

You can see if the ReportNode is the root it will default to "main" 
This is how the reporter sees the test results. 

I'm not sure what sets that value, but even in a non nx workspace the same behavior happens. this looks to be an upstream issue with the reporter. 
https://github.com/barbados-clemens/cobertura-reporter-repro

Ideally the reporter would change this to the displayName value for the given jest.config.ts

since the coverage reports are output into a directory of the project name you could write a small script to go update the node with the parent folder name (which is the project name) as a potential workaround.

**Comment by Authfix** [comment]
An issue is actually opened on Istanbuljs project (https://github.com/istanbuljs/istanbuljs/issues/552) and it seems that the "problem" is on a shared component and not really the reporter itself. 

I will take a look if I can contribute on this one and will update the node manually in the CI for the moment.

Thank you for putting me on the right direction and your quick and kind response.

Happy New Year's eve to the whole nrwl team

**Comment by Authfix** [comment]
For people who have the same issue, I created the following powershell script. My repository is not huge so I can't guarantee that I cover every case but it can be a base

``` powershell
[CmdletBinding()]
param (
    [Parameter(Mandatory=$true)]
    [string] $Directory
)

# Update "name" attribute in "package" node on the selected file
function UpdateXMLFile([string] $file, [string] $folderName)
{
    [xml]$xml = Get-Content $file

    $xml.coverage.packages.package | ForEach-Object {
        # Generate the new name with project prefix
        $newName = "$folderName."+$_.name
        # Remove default folder's name
        $_.name = $newName.Replace(".src.lib", "").Replace(".main", "")
    }

    $xml.Save($file)
}

$files = Get-ChildItem $Directory -Recurse -Filter "cobertura-coverage.xml"

Write-Output "Found $($files.Count) files"
Write-Output "Files :"
$files | ForEach-Object { Write-Output $_.FullName }

$files | ForEach-Object {
    $folderName = Split-Path $_.DirectoryName -Leaf
    UpdateXMLFile $_.FullName $folderName
}
```

and use like this in GitHub actions
``` yaml
- name: Update Coverage package name
  shell: pwsh
  run: |
    ./deployment/coverage-update-package.ps1 -Directory .
```
