### ISSUE TITLE
Storybook fails to run when importing function from another lib

### ISSUE THREAD

**Issue by atralice** [nrwl/nx#14030]
### Current Behavior

> nx run ui:storybook

=> Loading Nrwl React Storybook preset from "@nrwl/react/plugins/storybook"

webpack built preview fbb5aaf09e5265deb2e2 in 14608ms
ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '/home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/lib'
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/Compilation.js:2016:28
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:975:5
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/neo-async/async.js:6883:13
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:958:45
    at finishWithoutResolve (/home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/forEachBail.js:16:12
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/AliasPlugin.js:125:14
    at next (/home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/forEachBail.js:14:3)
    at forEachBail (/home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/forEachBail.js:24:9)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/AliasPlugin.js:51:5
    at _next1 (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:41:15
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
resolve 'fs' in '/home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/lib'
  Parsed request is a module
  using description file: /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/lib/node_modules doesn't exist or is not a directory
      looking for modules in /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/node_modules
        single file module
          using description file: /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/package.json (relative path: ./node_modules/fs)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/node_modules/fs doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/node_modules/fs.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/node_modules/fs.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/node_modules/fs.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/node_modules/fs.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/node_modules/fs.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/node_modules/fs.json doesn't exist
            .cjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/node_modules/fs.cjs doesn't exist
        /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/node_modules/fs doesn't exist
      /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node_modules doesn't exist or is not a directory
      /home/atralice/Projects/totono.xyz/get-deli/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /home/atralice/Projects/totono.xyz/get-deli/node_modules
        single file module
          using description file: /home/atralice/Projects/totono.xyz/get-deli/package.json (relative path: ./node_modules/fs)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/fs doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/fs.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/fs.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/fs.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/fs.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/fs.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/fs.json doesn't exist
            .cjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/fs.cjs doesn't exist
        /home/atralice/Projects/totono.xyz/get-deli/node_modules/fs doesn't exist
      /home/atralice/Projects/totono.xyz/node_modules doesn't exist or is not a directory
      /home/atralice/Projects/node_modules doesn't exist or is not a directory
      /home/atralice/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '/home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/lib'
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/Compilation.js:2016:28
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:975:5
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/neo-async/async.js:6883:13
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:958:45
    at finishWithoutResolve (/home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/forEachBail.js:16:12
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/AliasPlugin.js:125:14
    at next (/home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/forEachBail.js:14:3)
    at forEachBail (/home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/forEachBail.js:24:9)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/AliasPlugin.js:51:5
    at _next1 (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:41:15
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
resolve 'fs' in '/home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/lib'
  Parsed request is a module
  using description file: /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/lib/node_modules doesn't exist or is not a directory
      looking for modules in /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/node_modules
        single file module
          using description file: /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/package.json (relative path: ./node_modules/fs)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/node_modules/fs doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/node_modules/fs.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/node_modules/fs.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/node_modules/fs.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/node_modules/fs.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/node_modules/fs.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/node_modules/fs.json doesn't exist
            .cjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/node_modules/fs.cjs doesn't exist
        /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/node_modules/fs doesn't exist
      /home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node_modules doesn't exist or is not a directory
      /home/atralice/Projects/totono.xyz/get-deli/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /home/atralice/Projects/totono.xyz/get-deli/node_modules
        single file module
          using description file: /home/atralice/Projects/totono.xyz/get-deli/package.json (relative path: ./node_modules/fs)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/fs doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/fs.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/fs.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/fs.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/fs.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/fs.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/fs.json doesn't exist
            .cjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/fs.cjs doesn't exist
        /home/atralice/Projects/totono.xyz/get-deli/node_modules/fs doesn't exist
      /home/atralice/Projects/totono.xyz/node_modules doesn't exist or is not a directory
      /home/atralice/Projects/node_modules doesn't exist or is not a directory
      /home/atralice/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '/home/atralice/Projects/totono.xyz/get-deli/node_modules/@mapbox/node-pre-gyp/lib'
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/Compilation.js:2016:28
    at /home/atralice/Projects/totono.

.....
(3000 lines of the same errors later)
.....

            .cjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/net.cjs doesn't exist
        /home/atralice/Projects/totono.xyz/get-deli/node_modules/net doesn't exist
      /home/atralice/Projects/totono.xyz/node_modules doesn't exist or is not a directory
      /home/atralice/Projects/node_modules doesn't exist or is not a directory
      /home/atralice/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve 'tls' in '/home/atralice/Projects/totono.xyz/get-deli/node_modules/tunnel-agent'
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/Compilation.js:2016:28
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:975:5
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/neo-async/async.js:6883:13
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/webpack/lib/NormalModuleFactory.js:958:45
    at finishWithoutResolve (/home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/forEachBail.js:16:12
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/AliasPlugin.js:125:14
    at next (/home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/forEachBail.js:14:3)
    at forEachBail (/home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/forEachBail.js:24:9)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/AliasPlugin.js:51:5
    at _next1 (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/atralice/Projects/totono.xyz/get-deli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/atralice/Projects/totono.xyz/get-deli/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:41:15
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
resolve 'tls' in '/home/atralice/Projects/totono.xyz/get-deli/node_modules/tunnel-agent'
  Parsed request is a module
  using description file: /home/atralice/Projects/totono.xyz/get-deli/node_modules/tunnel-agent/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/atralice/Projects/totono.xyz/get-deli/node_modules/tunnel-agent/node_modules doesn't exist or is not a directory
      /home/atralice/Projects/totono.xyz/get-deli/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /home/atralice/Projects/totono.xyz/get-deli/node_modules
        single file module
          using description file: /home/atralice/Projects/totono.xyz/get-deli/package.json (relative path: ./node_modules/tls)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/tls doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/tls.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/tls.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/tls.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/tls.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/tls.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/tls.json doesn't exist
            .cjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/atralice/Projects/totono.xyz/get-deli/node_modules/tls.cjs doesn't exist
        /home/atralice/Projects/totono.xyz/get-deli/node_modules/tls doesn't exist
      /home/atralice/Projects/totono.xyz/node_modules doesn't exist or is not a directory
      /home/atralice/Projects/node_modules doesn't exist or is not a directory
      /home/atralice/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory

 

 >  NX   Running target storybook for project ui failed

   Failed tasks:
   
   - ui:storybook
   
   Hint: run the command with --verbose for more details.

### Expected Behavior

I would expect storybook to run.

### Steps to Reproduce

1. Import a Function from another lib, in my particular case a lib called 'utils'
2. nx run ui:storybook

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : linux x64
   npm  : 9.1.1
   
   nx : 15.4.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.1
   @nrwl/expo : Not Found
   @nrwl/express : 15.4.1
   @nrwl/jest : 15.4.1
   @nrwl/js : 15.4.1
   @nrwl/linter : 15.4.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.4.1
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.1
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.4.1
   @nrwl/web : 15.4.1
   @nrwl/webpack : 15.4.1
   @nrwl/workspace : 15.4.1
   @nrwl/vite : 15.4.1
   typescript : 4.9.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 nx-plugin-prisma: 0.2.2
   	 nx-plugin-workspace: 0.5.5
```

### Additional Information

If I don't import any function from an external lib, storybook runs OK.

All the libs where created using NX generators.

**Comment by mandarini** [comment]
Hi there @atralice ! Can you try adding the paths for that library into your Storybook `tsconfig.json`? Also,  if you're using React, you need to do the following to make sure it works (I'm pushing a fix soon):

```
yarn add -D @storybook/react@latest @storybook/builder-vite@latest
```

Let me know if this works!

**Comment by mandarini** [comment]
Can you also try the solution suggested here: https://github.com/nrwl/nx/issues/11728

**Comment by mandarini** [comment]
Also, can you please create a simple reproduction repository and link it here, if you try the above solutions and you still experience the same issue?

**Comment by mandarini** [comment]
[Here's a repo](https://github.com/mandarini/imported-libs) I created that shows that importing works for Webpack but does not work for Vite, for Storybook.

**Comment by mandarini** [comment]
Let me know if these solve your issue. If they do not, we can reopen, and revisit! Thank you so much for reporting this issue!

**Comment by atralice** [comment]
Hi, @mandarini , thanks for responding. I was out last month.

mmm, tried what you mentioned but I still get the same errors.
Also, I'm not using vite builder, I'm using webpack5.

**Comment by mandarini** [comment]
Hi @atralice ! Can you please send me a minimum reproduction repository?

**Comment by atralice** [comment]
@mandarini Thanks for the help.

I started again, using vite as the builder for storybook.

But still, when I import something from another lib I get unexpected behaivour.

Here is an example repo:
https://github.com/atralice/nx-demo

When you import `toFixed` in the file: ProductLine.tsx

Then storybook fails to load. If you don't import that function, everything seems to work fine.

**Comment by atralice** [comment]
It seems that the problems appears when importing `jsonwebtoken` in the lib I was trying to import from storybook.

I'm getting this error:
`TypeError: Object prototype may only be an Object or null: undefined`.

Any ideas on what might cause this?

Thanks for the help!!
