### ISSUE TITLE
Missing documentation about fonts

### ISSUE THREAD

**Issue by Markus-Bader** [nrwl/nx#14040]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.
https://nx.dev/recipes/other/adding-assets-react
### Additional context or description

Provide any additional details here as needed.

There is no information about how to handle fonts in nx - found some workarounds with adopting the webpack-config manually, but it would be nice to have a official documentation how to add font-files (e.g. *.ttf)

**Comment by isaacplmann** [comment]
We don't plan to add this documentation ourselves, but if you want to open a PR, I'd be happy to guide you through the review process.  Reopen the issue if you want to make a PR.
