### ISSUE TITLE
can not create library with karma

### ISSUE THREAD

**Issue by admir86** [nrwl/nx#1405]
# Prerequisites

A new empty workspace created with `npx create-nx-workspace@next myworkspace`. (@nrwl/workspace: 8.0.0-rc.2)

## Expected Behavior

Running `ng g library common --unit-test-runner=karma` should create a new library with karma as test runner.

## Current Behavior

The command throws an error: 
```
Cannot parse arguments. See below for the reasons.
    Argument --unit-test-runner could not be parsed using value "karma". Valid values are: "jest", "none".
```
see: https://github.com/nrwl/nx/issues/1306#issuecomment-495622411

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a new empty workspace `npx create-nx-workspace@next myworkspace`
2. Try to create a library in the new workspace `ng g library common --unit-test-runner=karma`

### Context

devDependencies from the new empty workspace:

```
"devDependencies": {
    "@nrwl/workspace": "8.0.0-rc.2",
    "@types/node": "~8.9.4",
    "dotenv": "6.2.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.4.5",
    "prettier": "1.16.4",
    "@angular/cli": "8.0.0-rc.3"
  }
```

my global ng cli version:
```
Angular CLI: 8.0.0-rc.4
Node: 10.14.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.800.0-rc.4
@angular-devkit/core         8.0.0-rc.4
@angular-devkit/schematics   8.0.0-rc.4
@schematics/angular          8.0.0-rc.4
@schematics/update           0.800.0-rc.4
rxjs                         6.4.0
```

**Comment by FrozenPandaz** [comment]
Thanks for trying out the latest `@nrwl/workspace`!

Let me start with the bad news. We highly recommend using Jest for unit testing and do not really recommend Karma for non-Angular projects (apps or libs). Ideally, Karma would be split out like `@nrwl/jest` but to reduce the amount of packages where we could, we decided to keep it as a part of Angular.

The good news is that there is technically a way you can achieve this:

```sh
npx create-nx-workspace karma-ws && cd karma-ws
ng add @nrwl/angular --unit-test-runner karma --e2e-test-runner protractor # Adds Angular Capabilities with Karma and Protractor
ng g @nrwl/workspace:lib lib1 --unit-test-runner none # Generates a library with no Unit Testing
ng g @nrwl/angular:karma-project --project lib1 # Adds Karma Unit Testing to any project
```

This is a chore to do every time so I'd recommend creating a [Workspace Schematic](https://nx.dev/api/workspace/schematics/workspace-schematic). Here's also a blog post which has more details: https://auth0.com/blog/create-custom-schematics-with-nx/. Sorry that we do not have better documentation on this topic yet (I should put some together) but basically you can do the following:

```sh
ng g @nrwl/workspace:workspace-schematic karma-lib # Create a schematic which can generate the code we want
yarn workspace-schematic karma-lib libName # Invoke the schematic
```

To implement the a schematic in `tools/schematics/karma-lib/index.ts` such as this:
```ts
import { chain, externalSchematic } from '@angular-devkit/schematics';

export default function(schema: any) {
  return chain([
    externalSchematic(
      '@nrwl/workspace',
      'lib',
      {
        unitTestRunner: 'none',
        name: schema.name
      }
    ),
    externalSchematic(
      '@nrwl/angular',
      'karma-project',
      {
        project: schema.name
      }
    ),
  ]);
}
```

**Comment by admir86** [comment]
you are right, I had no @nrwl/angular.
With the current release it works fine. I just followed the [getting started](https://nx.dev/getting-started/getting-started).

I'm checking nx to move multiple existing projects to a monorepo, these projects already have tests with karma and jasmine so I would like to stay with karma.

And I trust the [statement on ng-conf](https://www.youtube.com/watch?v=4d1HYKL2tt4&feature=youtu.be&t=709) of stephen fluin that karma gets better :)

thx for support!
