### ISSUE TITLE
module-boundaries could detect parent library buildability

### ISSUE THREAD

**Issue by g-cheishvili** [nrwl/nx#14053]
## Description
"buildable" could be inherited from parent(?), I do not know how to describe it better

## Motivation
So I have a structure like this in Angular Libraries
- core <- library
  - button <- library
  - link <- library
  - table <- library
  - 100ish more libraries
- platform <- library
  - table <- library, which uses things from the core like this `core/{something}` and that something is registered in `paths`, also they are libraries in the sense of Nx
- docs <- application

If that "something" is not buildable, lint will throw an error, but "something"s parent, in this case, `core` is buildable, since those "somethings" are inside of the core, they end up as secondary entry points for APF and in reality, It is acceptable for Angular to have a layout like that. I need other targets(things like `test`, or `lint`) for those small libraries, but I do not want them to be buildable, I do not need them to be, but if they are not linter cries, but if they are, build becomes way longer, because of the quantity of those small libs.

## Suggested Implementation
I have no idea

**Comment by g-cheishvili** [comment]
You can take a look at the [PR](https://github.com/SAP/fundamental-ngx/pull/9154)

**Comment by g-cheishvili** [comment]
I could have created dummy `build` targets all over the place and used another name for actually building stuff, like `build-umbrella`, but that's a kinda hacky way

**Comment by g-cheishvili** [comment]
> Did you use the `library-secondary-entry-point` generator to create those `somethings`? https://nx.dev/packages/angular/generators/library-secondary-entry-point

Thank you for your reply, sorry that I noticed it late.
The secondary entry point generator is different from ordinary module creation only with the `ng-package.json`. We need those secondary entry-point modules to be NX projects, otherwise, we will not have this granular vision over the graph and affected task executions. Those small `somethings` have their own targets like `test` and `lint` and we love that only the subprojects which had changed get triggered units and lints.

**Comment by meeroslav** [comment]
This feature request doesn't seem to pick any interest so i'll close it.

If someone wants to implement this, please let me know and I will gladly reopen it.
