### ISSUE TITLE
run dependent script make it stuck on the first script

### ISSUE THREAD

**Issue by rocknatt** [nrwl/nx#14051]
### Current Behavior

I have two project inside nx repository, they have script call "ts-watch" that watch if files change and then build typescript declaration.

- This is the actual dependency
- ![image](https://user-images.githubusercontent.com/31058789/209945077-fc56371c-db8e-4a35-98a1-5b0ee4181609.png)
- When i run the script `npx nx run client:watch`, it detect the dependency of the project, but it stuck (probably because it run "component" in watch mode)
- ![image](https://user-images.githubusercontent.com/31058789/209945239-9d02e454-c7b7-48a8-9b0f-f90b80e27ac8.png)
- I tryed to run `npx nx run-many --parallel --target=watch --projects=client,components`, but still I have the problem.
- ![image](https://user-images.githubusercontent.com/31058789/209945390-5dddf867-8067-4a9d-8e8a-e0acd659ad0b.png)

### Expected Behavior

- It should not block on one task, it should be able to run after a watch was completed 

### Github Repo

https://github.com/rocknatt/nx-watch.git

### Steps to Reproduce

1. Install the project
2. run `yarn install` for the dependencies
3. execute `npx nx run-many --parallel --target=watch --projects=client,components` or `npx nx run client:watch`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : win32 x64
   yarn : 1.22.18

   nx : 15.4.2
   @nrwl/angular : 15.3.0
   @nrwl/cypress : 15.3.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.3.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.0
   @nrwl/workspace : 15.3.0
   @nrwl/vite : Not Found
   typescript : 4.9.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by AgentEnder** [comment]
Long lived scripts are not currently well supported within target dependencies. This isn't really a bug, just something that isn't supported currently. There are a few other issues and feature requests for this, so I'll close this one out.

See:
- https://github.com/nrwl/nx/discussions/12836#discussioncomment-3984329
- https://github.com/nrwl/nx/issues/3748
- https://github.com/nrwl/nx/issues/5803
