### ISSUE TITLE
Nx version 15.4 not forwarding arguments to run-many?

### ISSUE THREAD

**Issue by jgarciaokode** [nrwl/nx#14050]
### Current Behavior

In Nx v14.8.3 when you run ```nx run-many --target deploy --options="--all"``` then the options arg is being passed to all executors, therefore as we have a cdk with multiple stacks, the pipeline does not exit with error asking to supply which cdk stack should be deployed

<img width="764" alt="Screenshot 2022-12-29 at 12 38 40" src="https://user-images.githubusercontent.com/79897391/209945960-64513408-f7a9-449b-abb5-42271eb90f1d.png">

However, in Nx v15.4.1, when you run exactly the same command, the arg is not being passed (it seems) and therefore, the pipeline exists with error

<img width="787" alt="image" src="https://user-images.githubusercontent.com/79897391/209945449-d7d1e75b-79a0-4a93-8f6a-4c6a53d228e0.png">

I tried with nx:run-commands executors and the same applies, the thing is that if you run nx run <project-name>:deploy --all it is working since the arguments are being forwarded

### Expected Behavior

As described, same behaviour than Nx 14.8.3, arguments being forwarded in run-many command

### Steps to Reproduce

1.
d

### Nx Report

```shell
 >  NX   Report complete - copy this into the issue template

   Node : 16.18.1
   OS   : darwin arm64
   npm  : 8.19.2

   nx : 15.4.1
   @nrwl/angular : 15.4.1
   @nrwl/cypress : 15.4.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.1
   @nrwl/js : 15.4.1
   @nrwl/linter : 15.4.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.4.1
   @nrwl/web : 15.4.1
   @nrwl/webpack : 15.4.1
   @nrwl/workspace : 15.4.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @otterdev/nx-cdk: 0.0.14
         @storybook/angular: 6.5.15

```

**Comment by jgarciaokode** [comment]
In nx version 15.3.3 it is working correctly, it seems like the change in run-many command in 15.4 broke this behaviour

<img width="797" alt="image" src="https://user-images.githubusercontent.com/79897391/209946366-c8f662f9-3dbf-4301-8573-4daab9c09470.png">

**Comment by ysdidenko** [comment]
Same here. In 15.4.2 just ignores params we pass to nx:affected

**Comment by AgentEnder** [comment]
@jgarciaokode I believe this should have been fixed by #14031. Can you try 15.4.2 and see if it is working for you?

**Comment by jgarciaokode** [comment]
@AgentEnder yes, it is working in 15.4.2 Thanks for the quick answer

**Comment by ysdidenko** [comment]
Hi @AgentEnder, it works locally, but still swallowing the arguments on Azure with nx-cloud, could you advise, please?
