### ISSUE TITLE
[Vite] worker build should use the viteTsConfigPaths plugin

### ISSUE THREAD

**Issue by vicb** [nrwl/nx#14059]
### Current Behavior

My project has a few libs imported via aliases.

The aliases are resolved as expected for all the files but the workers.

### Expected Behavior

The aliases should also apply to the workers

### Github Repo

n/a

### Steps to Reproduce

1. Create a project with a web app using vite
2. Create a lib imported via `@alias`
3. Create a worker in your web app. Add an `import * from '@alias';` in the worker lib
4. Import the worker in your web app: `import MyWorker from 'worker?worker';`
5. Build in production mode
6.You should see an error:
```
file: /.../worker.ts?worker

 >  NX   [vite]: Rollup failed to resolve import "@alias" from "/.../worker.ts".
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.10.0
   OS   : linux x64
   npm  : 8.19.2
   
   nx : 15.4.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.2
   @nrwl/expo : Not Found
   @nrwl/express : 15.4.2
   @nrwl/jest : 15.4.2
   @nrwl/js : 15.4.2
   @nrwl/linter : 15.4.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.4.2
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.4.2
   @nrwl/webpack : 15.4.2
   @nrwl/workspace : 15.4.2
   @nrwl/vite : 15.4.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
*  Executing task in folder [...]: npx nx build [...] --configuration=production 


> nx run [...]:build:production

vite v4.0.3 building for production...
✓ 54 modules transformed.
[vite:worker] [vite]: Rollup failed to resolve import "@[...]" from "[...].ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
file: [...].ts?worker

 >  NX   [vite]: Rollup failed to resolve import "@[...]" from "[...].ts".

   This is most likely unintended because it can break your application at runtime.
   If you do want to externalize this module explicitly add it to
   `build.rollupOptions.external`
   Pass --verbose to see the stacktrace.


 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target undefined for project [...] (2s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

### Additional Information

The issue is that the `viteTsConfigPaths` does not apply to workers.

It can be solved by explicitly adding it to the worker config in `vite.config.ts`:

```
// vite.config.ts
[...]

  // Existing
  plugins: [
    viteTsConfigPaths({
      root: '../../',
    }),
  ],

 // This needs to be added:
  worker: {
    plugins: [
      viteTsConfigPaths({
        root: '../../',
      }),
    ],
  },
```

**Comment by mandarini** [comment]
Hi there @vicb ! I think we do not need to add this in a generator, since it does not apply to all projects. Since you can add it manually and it works, I think that people can use it like this exactly. The `vite.config.ts` file is pure Vite, so one can configure it however they see fit to their needs! 

In any case, thank you very much for providing this solution, since someone else may run into this and it's nice that you have it here.

If you think that we should add this in our generator, regardless, let me know and I am happy to discuss and reopen this issue!!

Thank you so much for this! :)

**Comment by vicb** [comment]
>  I think we do not need to add this in a generator, since it does not apply to all projects

Nx [encourages](https://nx.dev/more-concepts/applications-and-libraries#misconception) to put most of the logic inside libs. So I still think it would be a nice addition to the vite plugin.

Without that developers should know/figure out how to configure vite workers and that  `viteTsConfigPaths` is the plugin used to map the TS aliases which is not trivial.

> The vite.config.ts file is pure Vite, so one can configure it however they see fit to their needs!

Sure but if you already to it for the non-worker case, why not doing it for workers as well ? 

I don't see any negatives of adding the plugin for workers in the default configuration. Do you see some ?

**Comment by mandarini** [comment]
Ah I see what you mean, thank you.

The reason we are adding the plugin for non-worker case, is that if we don't then Vite will not work in the monorepo setup, meaning that it will not be able to resolve paths of imported libs, which is the main usecase that people use Nx for.

I see what you are saying, that the worker case is no less frequent or no less important.

The only "negative" I see in automatically adding the `workers` configuration in `vite.config.ts`, is that we are trying to keep the `vite.config.ts` to the bare minimum setup for Nx to work, and then anyone can add their own things. But I do see what you are saying. Give me a moment to take a second opinion on this, and we can add this in the generator potentially.

**Comment by mandarini** [comment]
Ok, adding the `worker` in there! :D
