### ISSUE TITLE
Dependency graph is flat

### ISSUE THREAD

**Issue by goldylucks** [nrwl/nx#14052]
### Current Behavior

The dependency graph is flat
![Uploading image.png…]()

### Expected Behavior

should show dependencies

### Github Repo

https://github.com/goldylucks/nx-graph-bug

### Steps to Reproduce

1. Create new nx workspace
2. create an app and a lib
3. import something from the lib in the app
4. nx graph (works fine)
5. Change tsconfig (see below)
6. nx graph (everything is flat)

5. Change tsconfig
```
// tsconfig.base.json
    "paths": {
      "@nx-graph-bug/my-lib": ["../../../libs/my-lib/src/index.ts"],
            "~/*": ["./*"],
    }

// apps/example-app/tsconfig.json
  "compilerOptions": {
    "baseUrl": "src",
}
```

I actually made these changes according to a suggestion from one of nx contributors. The idea is to have absolute imports in the projects, so instead of `import foo from "../../../foo" I could do `import foo from ~/foo`

This works great, but breaks the graph for some reason 🤷‍♀️

### Nx Report

```shell
I literally did `npx create-nx-workspace@latest` 20 minutes ago

 Node : 16.18.0
   OS   : darwin arm64
   npm  : 8.19.2

   nx : 15.4.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.2
   @nrwl/js : 15.4.2
   @nrwl/linter : 15.4.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.4.2
   @nrwl/webpack : 15.4.2
   @nrwl/workspace : 15.4.2
   @nrwl/vite : 15.4.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by AgentEnder** [comment]
Using `baseUrl` inside of a project's tsconfig will cause the paths to resolve as relative to that new baseUrl. This is why it was required for you to use `../../../`. I wouldn't recommend setting it personally, but if doing so the paths relative to the new baseUrl should be contained within the tsconfig that sets the baseurl. Otherwise you set yourself up for footguns when creating libraries at different path deps. (e.g. libs/shared/core vs libs/feature). 

In your case, Nx is looking at your tsconfig.base.json and isn't able to map the paths properly since they point to a folder outside the workspace, since the baseUrl isn't set at this point.

**Comment by goldylucks** [comment]
I actually have libs/domains/domain-a and libs/utils and it works fine, just the dependency graph is broken (and I suspect `affected` as well)

> but if doing so the paths relative to the new baseUrl should be contained within the tsconfig that sets the baseurl

So you're saying the base tsconfig should be "normal", and then each tsconfig inside an app/lib should redeclare it's relative paths? so I'll end up with multiple duplications of paths across each project's tsconfig?

Is there a more "nx" way of achieving my goal of `import foo from `~/foo` instead of `../../../foo` ?

**Comment by AgentEnder** [comment]
I don't recommend any kind of setup that involves setting up an absolute path shorthand. If the relative paths are getting crazy long or anything it's more a sign that you should break up the library into smaller libs than anything else.

**Comment by goldylucks** [comment]
> I don't recommend any kind of setup that involves setting up an absolute path shorthand

Why not? it's a pretty common practice.

I think this can be relatively simply solved by having a base tsconfig which is "normal" as far as nx is concerned, and then every lib/app will have it's own tsconfig with the relative paths.

I can have a script running to keep them in sync, e.g. when adding a new library to the base config, all apps/libs tsconfig update automatically.

Do you see any drawbacks here?

**Comment by goldylucks** [comment]
@AgentEnder ?

**Comment by AgentEnder** [comment]
I don't personally like doing something like that for a few reasons, none of which are major I guess. If you want to do it, go ahead and do it. If you notice pain points you can always undo the setup, albeit that won't be great fun.
