### ISSUE TITLE
nx add make keyboard not working with angular

### ISSUE THREAD

**Issue by robertIsaac** [nrwl/nx#14074]
### Current Behavior

run `nx add @angular/fire`
when it asks for which options to choose, you can move up/down or do anything

### Expected Behavior

it works

### Steps to Reproduce

1. in any nx project with angular try `nx add @angular/fire`

### Nx Report

```shell
Node : 16.18.1l
   OS   : win32 x64soft Corporation. All rights reserved.
   npm  : 8.19.2
   
   nx : 15.3.3
   @nrwl/angular : 15.3.3
   @nrwl/cypress : 15.3.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : 15.3.3
   @nrwl/next : Not Found
   @nrwl/node : 15.3.3
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nguniversal/express-engine: 15.0.0
         @nguniversal/builders: 15.0.0
         ng-mocks: 14.5.1
```

### Failure Logs

```shell
nothing, it just don't work
```

### Additional Information

running `nx g @angular/fire:ng-add` afterward works as expected, which is very weird

**Comment by AgentEnder** [comment]
RE: `nx g ...:ng-add` working, that is the expected path. I would have expected a log telling you to run it when you attempted `nx add`. Did it not display properly?

**Comment by robertIsaac** [comment]
it was displayed properly, the command got executed I can see the options, but the terminal isn't seeing my keyboard interaction
I tried it twice from different terminals, same error

**Comment by robertIsaac** [comment]
> RE: `nx g ...:ng-add` working, that is the expected path. I would have expected a log telling you to run it when you attempted `nx add`. Did it not display properly?

do you mean the message
```
Ng add is not natively supported by Nx
Instead, we recommend running `npm install @angular/fire && npx nx g @angular/fire:ng-add`
```
?

**Comment by AgentEnder** [comment]
Yeah, thats the message I would expect.

**Comment by robertIsaac** [comment]
> Yeah, thats the message I would expect.

I didn't notice it the first time, till I read your comment again now
so in the future I should instead of running `nx add @angular/fire` I should run `npm install @angular/fire && npx nx g @angular/fire:ng-add`?

**Comment by AgentEnder** [comment]
Yeah, there's no `add` command in Nx, so you have to run the 2 commands separately.
