### ISSUE TITLE
Cannot convert complex app with ng add @nrwl/schematics

### ISSUE THREAD

**Issue by nathanhokanson** [nrwl/nx#1409]
## Expected Behavior

ng add @nrwl/schematics updates the application to be a nrwl workspace.

## Current Behavior

When you run the command you see the following errors:

± |master ?:1 ✗| → ng add @nrwl/schematics
Skipping installation: Package already installed
? What is the npm scope you would like to use for your Nx Workspace? fox
    Path: karma.conf.js does not exist
    Path: tsconfig.app.json does not exist
    Path: tsconfig.spec.json does not exist
    Path: apps/fox-angular-cli/tslint.json already exists
    Path: apps/fox-angular-cli already exists
Path: apps/fox-angular-cli already exists

 2019-05-28 13:01:39 ⌚  |2.3.0| cf-mp-nhokanson in ~/src/clean-nrwl

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.
1 - clone this git repo:  https://github.com/nathanhokanson/nrwl
2 - npm install
3 - ng add @nrwl/schematics

Note:  This is a new application generated by the angular-cli and then the package.json and angular.json moved over from our main git repository which cannot be shared.

### Context

Please provide any relevant information about your setup:

Angular CLI: 7.3.9
Node: 10.15.3
OS: darwin x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.9
@angular-devkit/build-angular      0.13.9
@angular-devkit/build-optimizer    0.13.9
@angular-devkit/build-webpack      0.13.9
@angular-devkit/core               7.3.9
@angular-devkit/schematics         7.3.9
@angular/cdk                       7.3.7
@angular/cli                       7.3.9
@angular/material                  7.3.7
@angular/material-moment-adapter   7.3.7
@ngtools/webpack                   7.3.9
@schematics/angular                7.3.9
@schematics/update                 0.13.9
rxjs                               6.5.2
typescript                         3.2.4
webpack                            4.29.0

**Comment by nathanhokanson** [comment]
Any ideas?  We are kinda stuck moving our project forward.

**Comment by maxime1992** [comment]
I had absolutely no hope at all that the migration would go smoothly on our app.
(Spoiler alert, it didn't).

I created an empty nx repo and started to import things. Tedious but I'm getting there, I've got the server running, frontend too and few libs :raised_hands: 

Now I've got to work on the E2E tests and others but it's a good start :) 

Good luck with your migration @nathanhokanson

**Comment by vsavkin** [comment]
Folks,

I'm going to close this one. We have made some changes to `ng-add`  and wrote a guide on using it: https://github.com/nrwl/nx/blob/master/docs/angular/guides/transition-to-nx.md. 

If you are still having the problem, please reopen the issue. 

Thank you!

**Comment by ashokkumar9892** [comment]
I have same issue @nathanhokanson , i have multiple apps in side apps folder and when i am trying to add ng add @nrwl/schematics , getting error 👍 
Can only convert projects with one app

any solution?
