### ISSUE TITLE
Worker issue with NX module federation - Failed to execute 'importScripts' on 'WorkerGlobalScope': Module scripts don't support importScripts()

### ISSUE THREAD

**Issue by ashish-nagose-incontact** [nrwl/nx#14109]
### Current Behavior

While using module federation with worker created using comlink, when I browse application after serve, I get below error

<img width="952" alt="image" src="https://user-images.githubusercontent.com/85344164/210383818-076b8043-116c-4305-b2dd-9dc61e091568.png">

Because of above error, not able to execute any functionality on worker thread.

_PS: We are using same worker in nx application without module federation for more than a year where it works smoothly._

Are there any specific config changes to be done to make it work with Module federation?

I have added sample worker in reference repo and changes can be found at https://github.com/ashish-nagose-incontact/react-module-federation-with-worker

Yarn install and nx serve host --devRemotes=shop,cart --> to run the application

This error occurs in both host app and shop (wherein worker is incorporated).

We have tried blob approach as mentioned below after which error goes away but worker thread code never gets executed.

export function initUtilWorker() { const workerContent = UtilWorker.toString();  const blob = new Blob([workerContent], { type: 'application/javascript' }); const worker_script = URL.createObjectURL(blob); const worker = new Worker(new URL(worker_script, import.meta.url), { name: 'util-worker', type: 'module', }); return wrap<UtilWorker>(worker);

Please let us know if any additional information required.

### Expected Behavior

Worker should work seemlessely even with Module federation, the way it works without it.

### Github Repo

 https://github.com/ashish-nagose-incontact/react-module-federation-with-worker

### Steps to Reproduce

1. Yarn install 
2.  nx serve host --devRemotes=shop,cart --> to run the application
3. console logs the mentioned error.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : win32 x64
   yarn : 1.22.10

   nx : 14.1.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.1
   @nrwl/eslint-plugin-nx : 14.1.1
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.1
   @nrwl/js : 14.1.1
   @nrwl/linter : 14.1.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.0.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.1.1
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.1
   @nrwl/web : 14.1.1
   @nrwl/workspace : 14.1.1
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

### Additional Information

Same issue is created @ https://github.com/nrwl/react-module-federation/issues/6

**Comment by ashish-nagose-incontact** [comment]
Any updates on this ?

**Comment by Manuparashar1995** [comment]
Is there any update on this one? I am also facing similar issues.

**Comment by santoshyadavdev** [comment]
I am facing the same issue with Angular + module federation

**Comment by mparashar22** [comment]
@FrozenPandaz Is there any finding on the issue?

**Comment by rbrzoska** [comment]
I have the same for angular

**Comment by nviv77** [comment]
I am also facing the same issue for angular with module-federation.
  "@angular-architects/module-federation": "^14.3.14",
    "@angular-architects/module-federation-tools": "^14.3.14",

Is there any update on the issue?

**Comment by ankurrai2602** [comment]
I am also facing same issue, using angular16

**Comment by Coly010** [comment]
This appears to be a limitation with Webpack Module Federation itself and not an issue with Nx.

This issue would likely be best served being posted to the webpack repo: https://github.com/webpack/webpack/
