### ISSUE TITLE
Add qwik-nx to list of community plugins

### ISSUE THREAD

**Issue by benediktms** [nrwl/nx#14102]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

The community plugin section: https://nx.dev/community?#search

### Additional context or description

The qwik team has added a plugin for nx to allow users to add qwik apps to their workspaces: https://github.com/qwikifiers/qwik-nx I think this should be added to the communioty plugin list.

**Comment by AgentEnder** [comment]
We have been in contact with the people behind `qwik-nx`, it will be added as soon as they are ready for it to be.
