### ISSUE TITLE
Configure the Webpack module federation to work with the outside world

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#14101]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I would like to configure the Webpack module federation in NX to consume components from outside of NX, and provide the components to the outside world.

## Motivation

In order to more easily integrate work built within one domain into other applications, and vice versa.

## Suggested Implementation

Provide the configuration options to define the URL from which the fragments can be loaded from.

## Alternate Implementations

At the moment, this is doable configuring the Webpack module federation manually, but this is not optimal.

**Comment by Coly010** [comment]
This is supported already with Tuple Syntax in the module-federation.config.js file, and by passing --skipRemotes.

https://nx.dev/packages/devkit/documents/index#remotes

https://nx.dev/packages/angular/executors/module-federation-dev-server#skipremotes

closing as feature is supported

**Comment by nemonemi** [comment]
@Coly010 would you mind updating your first link? It seems to be broken.
Thanks!

**Comment by Coly010** [comment]
Done
