### ISSUE TITLE
Compile all ts file to js on src folder

### ISSUE THREAD

**Issue by morbargig** [nrwl/nx#14113]
### Current Behavior

![image](https://user-images.githubusercontent.com/51287453/210397101-44cff6c5-7226-4d13-aa9c-3ce6bd4fbfed.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/51287453/210397280-08544891-ac2c-4a8d-93e8-61b472f97420.png)

### Steps to Reproduce

1.
Run nest app with NX
git pull some changes or in random times or cause 

some bug on nx version 15.4.2

### Nx Report

```shell
Node : 19.3.0
   OS   : darwin x64
   npm  : 9.2.0
   
   nx : 15.2.4
   @nrwl/angular : 15.2.4
   @nrwl/cypress : 15.2.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.4
   @nrwl/js : 15.2.4
   @nrwl/linter : 15.2.4
   @nrwl/nest : 15.2.4
   @nrwl/next : Not Found
   @nrwl/node : 15.2.4
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.2.4
   @nrwl/web : Not Found
   @nrwl/webpack : 15.2.4
   @nrwl/workspace : 15.2.4
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by PPRobitaille** [comment]
Same issue too

**Comment by morbargig** [comment]
> Same issue too, problem seems to be webpack compiler for me. I switched to:
> 
> ```
>  {
>   "build": {
>     "executor": "@nrwl/js:tsc",
> ...
> ```
> 
> But if you need webpack for angular with some optimizations, I guess there's a settings to change that to build folder structure..

Thanks I will check it,
But the best solution will be migration of nx migrate latest because if I will start do everything custom it can do me a damage with future migration and support.
