### ISSUE TITLE
Add formulas used to the docs

### ISSUE THREAD

**Issue by ndrean** [nrwl/nx#14121]
- [ x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I would like to have the formulas used in your calculations, or a reference to the formula used in the calculus

## Motivation

You must guess what most functions do by the name rather than being sure of what you calculate

## Suggested Implementation

Write formulas in Latex!
Sometimes, you can write a formula in text. An example: 
[Nx.standard_deviation](https://hexdocs.pm/nx/Nx.html#standard_deviation/2) is the square root of [Nx.variance](https://hexdocs.pm/nx/Nx.html#variance/2)

Note: you can't use `Nx.standard_deviation`with this Latex  \text{} command.

[Nx.variance](https://hexdocs.pm/nx/Nx.html#variance/2) : $\frac 1n \sum(x_i - \text{Nx.mean}(x))^2$ where:
[Nx.mean](https://hexdocs.pm/nx/Nx.html#mean/2): $\text{Nx.mean}(x)  = \frac 1n \sum x_i$

**Comment by drewxs** [comment]
I think you might have the wrong Nx. I believe you meant to go [here](https://github.com/elixir-nx/nx/issues).

**Comment by ndrean** [comment]
ooops!!!!! Sorry!!
