### ISSUE TITLE
Allow generatePackageJson without package-lock.json

### ISSUE THREAD

**Issue by DaSchTour** [nrwl/nx#14120]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Additionally to generatePackageJson with true/false it should be possible to also configure if a package-lock.json should be generated.

## Motivation
I somehow missed the introduction of this new feature and had failing builds because the npm install in my Dockerfile was not prepared to handle the install with a package-lock.json
So I spend today searching for the reason of the failing builds until I discovered that a package-lock.json was generated.

## Suggested Implementation
Additionally to true/false add options like packageJsonOnly or withoutPackageLock.

## Alternate Implementations
In the meantime I'll have to add a new line to my Dockerfile that will remove the package-lock.json

**Comment by vicb** [comment]
> I'll have to add a new line to my Dockerfile that will remove the package-lock.json

You would typically use a [`.dockerignore`](https://docs.docker.com/engine/reference/builder/#dockerignore-file) file in this case

**Comment by DaSchTour** [comment]
> > I'll have to add a new line to my Dockerfile that will remove the package-lock.json
> 
> 
> 
> You would typically use a [`.dockerignore`](https://docs.docker.com/engine/reference/builder/#dockerignore-file) file in this case 

Thanks for the hint. I didn't know that the ignore file also impacts COPY. Still I wonder when and why the generating of lockfiles was introduced and what the usecase is.

**Comment by vicb** [comment]
> Still I wonder when and why the generating of lockfiles was introduced and what the usecase is.

I'm not sure of when it was introduced either (I'm new to Nx).

However the use case makes a lot of sense: without the lockfile there is no guarantee about the version of the packages that will be installed by your package manager. They might differ from what you have installed locally meaning you might end up with different versions from what you have tested locally with is definitely not something you would want.

**Comment by DaSchTour** [comment]
I know what lockfiles in general are used for. But I haven't seen packages published on NPM having a lockfile.

**Comment by vicb** [comment]
> But I haven't seen packages published on NPM having a lockfile.

That's because most pkg manager will ignore those - see [this article](https://www.twilio.com/blog/lockfiles-nodejs) for more details.

It kind of makes sense as when you develop locally you probably want to grab the latest version of your dependency. 
Then when you create a Docker image you most likely want to install the exact same versions of your deps meaning. Those are in the lockfile. So your Dockerfile should contain:

```Dockerfile
ENV NODE_ENV production

COPY package*.json ./

RUN npm ci
```

**Comment by DaSchTour** [comment]
Yeah I know that I should. But as I have a private npm repository it makes the build inside docker on the CI a lot more complicated although I don't actually need the dependencies from my private repo in the npm install in docker.
And it was a breaking change within an update in NX as suddenly my build stopped working. I guess with 15.3 everything was fine and with 15.4 it broke because suddenly there was a lockfile and npm install wanted to install with the URLs from the lockfile.
And as the package.json ist generated in has mainly fixed versions. So although some subdependencies might change I still would like to have the option to control the behaviour of generatePackageJson and not been feed with stuff I never ordered.

**Comment by vicb** [comment]
> not been feed with stuff I never ordered

Yeah we should never forget that OSS is mostly free lunch and be thankful to the contributors for that.

I understand your frustration because of this unfortunate breaking change. However I personally think it makes sense to generate both the files with `generatePackageJson: true`. Having too many configuration options would make the Nx harder to use for little benefits. My 2 cents.

**Comment by DaSchTour** [comment]
Yeah, you are absolutely right. If NX wouldn't have this hidden gems that many developer don't figure out they wouldn't hire me as a consultant 👨🏼‍💼

**Comment by DaSchTour** [comment]
I wasn't the only one having trouble with this: #14106
