### ISSUE TITLE
run-many CLI parallel example is confusing/unclear

### ISSUE THREAD

**Issue by janeklb** [nrwl/nx#14124]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

No, it's regarding the "Examples:" section of `run-many --help`'s output:

```
// ... trimmed for brevity

Options:
// ... trimmed for brevity
      --parallel           Max number of parallel processes [default is 3]              [string]
// ... trimmed for brevity

Examples:
  run-many --target=test                                          Test all projects
  run-many --target=test --projects=proj1,proj2                   Test proj1 and proj2
  run-many --target=test --projects=proj1,proj2 --parallel=2      Test proj1 and proj2 in parallel
  // ... trimmed for brevity

```

### Additional context or description

The 3rd example is described with "Test proj1 and proj2 in parallel"; however, afaiu, the 2nd example should also test proj1 and proj2 in parallel (because the `--parallel` default is `3`)

**Comment by FrozenPandaz** [comment]
Yes, that is confusing and you understand correctly. Would you like to update the docs to make it more clear?

* `run-many --target test --projects proj1,proj2` = Test proj1 and proj2 in parallel
* `run-many --target test --projects proj1,proj2 --parallel 5` = Test proj1 and proj2 in parallel using 5 workers
* `run-many --target test --projects proj1,proj2 --parallel false` = Test proj1 and proj2 in sequence.

**Comment by janeklb** [comment]
> Yes, that is confusing and you understand correctly. Would you like to update the docs to make it more clear?
> 
> * `run-many --target test --projects proj1,proj2` = Test proj1 and proj2 in parallel
> * `run-many --target test --projects proj1,proj2 --parallel 5` = Test proj1 and proj2 in parallel using 5 workers
> * `run-many --target test --projects proj1,proj2 --parallel false` = Test proj1 and proj2 in sequence.

sure thing https://github.com/nrwl/nx/pull/14335
