### ISSUE TITLE
e2e apps generating outside of the apps directory

### ISSUE THREAD

**Issue by deegansiwicki** [nrwl/nx#14138]
### Current Behavior

after one of the recent updates, when using the nextjs application generator, the e2e app gets generated outside of the apps directory

### Expected Behavior

for the e2e app to be generated in the apps directory like before

### Steps to Reproduce

1. use the @nrwl/next:application generator

### Nx Report

```shell
CREATE apps/client/index.d.ts
CREATE apps/client/next-env.d.ts
CREATE apps/client/next.config.js
CREATE apps/client/pages/index.module.css
CREATE apps/client/pages/index.tsx
CREATE apps/client/pages/_app.tsx
CREATE apps/client/pages/styles.css
CREATE apps/client/public/.gitkeep
CREATE apps/client/specs/index.spec.tsx
CREATE apps/client/tsconfig.json
CREATE apps/client/project.json
CREATE client-e2e/cypress.config.ts
CREATE client-e2e/src/e2e/app.cy.ts
CREATE client-e2e/src/fixtures/example.json
CREATE client-e2e/src/support/app.po.ts
CREATE client-e2e/src/support/commands.ts
CREATE client-e2e/src/support/e2e.ts
CREATE client-e2e/tsconfig.json
CREATE client-e2e/project.json
CREATE client-e2e/.eslintrc.json
CREATE apps/client/jest.config.ts
CREATE apps/client/tsconfig.spec.json
CREATE apps/client/.eslintrc.json
```

**Comment by barbados-clemens** [comment]
do you have a project.json in the root of your project?

**Comment by deegansiwicki** [comment]
> do you have a project.json in the root of your project?

A package.json yeah 
<img width="925" alt="Screenshot 2023-01-04 at 12 19 07 PM" src="https://user-images.githubusercontent.com/71299723/210622892-515c4685-eace-4b4f-80e1-6ed120a2f784.png">

**Comment by barbados-clemens** [comment]
does the `package.json` have an `nx` key in it?

like 
```json
{
  "nx": {
    // stuff
  }
}
```

**Comment by deegansiwicki** [comment]
> does the `package.json` have an `nx` key in it?
> 
> like
> 
> ```json
> {
>   "nx": {
>     // stuff
>   }
> }
> ```

<img width="572" alt="Screenshot 2023-01-04 at 12 57 08 PM" src="https://user-images.githubusercontent.com/71299723/210629106-29103601-9c09-4128-a89c-b644b587fa5d.png">

**Comment by barbados-clemens** [comment]
that's why. 
cypress-project generator (generator that nrwl/next:app calls) is seeing that as you have setup a project at the root of your project so it's following the 'standalone' approach for generating projects. 

if you delete that nx entry in the package.json, then it shouldn't do that any more.

try that and let me know if it works

**Comment by barbados-clemens** [comment]
As a workaround, You can remove the nx key when generating and then add it back
or you can just use nrwl/workspace:move to move it to the location you want

but I'll make the change in the cypress generator to prevent this from happening. 👍

**Comment by deegansiwicki** [comment]
> As a workaround, You can remove the nx key when generating and then add it back or you can just use nrwl/workspace:move to move it to the location you want
> 
> but I'll make the change in the cypress generator to prevent this from happening. 👍

Awesome, thank you!
