### ISSUE TITLE
Page error 404 | https://nx.dev/getting-started/react-tutorial

### ISSUE THREAD

**Issue by giri-jeedigunta** [nrwl/nx#14134]
### Documentation issue

- [ ] Reporting a typo
- [X] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[[Enter the URL or documentation section here.](https://nx.dev/getting-started/react-tutorial)](https://nx.dev/getting-started/react-tutorial) 

### Additional context or description

404 page do not exist.

**Comment by FrozenPandaz** [comment]
May I ask where you found that link?

The new page is here: https://nx.dev/getting-started/react-standalone-tutorial

@bcabanes can we add a redirect?

**Comment by bcabanes** [comment]
> @bcabanes can we add a redirect?

Yes! I will, I also find the Angular one is in the same boat, I'll add redirect rules for both.
