### ISSUE TITLE
Allow flag in nx migrate --run-migrations to skip if migrations.json does not exist instead of failing

### ISSUE THREAD

**Issue by samuelfernandez** [nrwl/nx#14131]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I want to use Renovate to automate the process of `nx migrate`, in the package [`@nx-squeezer/workspace`](https://github.com/nx-squeezer/squeezer/tree/main/packages/workspace/src/generators/renovate). Right now there is an integration issue in the way it should check if `migrations.json` and later run it.

The issue is well explained here https://github.com/renovatebot/renovate/issues/7767

## Motivation

Simplify the usage of `nx migrate`  in Renovate runners

## Suggested Implementation

Similar as with `npm run`, add a new flag `--if-present` that would not cause the `nx` command to fail if the `migrations.json` file does not exist

**Comment by FrozenPandaz** [comment]
I agree :)

I still think it should warn though in case the path is incorrect.

Would you like to make a contribution?

**Comment by samuelfernandez** [comment]
> I agree :)
> 
> 
> 
> I still think it should warn though in case the path is incorrect.
> 
> 
> 
> Would you like to make a contribution?

Yes, can work on it next week.

When you mention validation if path is incorrect, what do you have in mind? It should support nonexistent paths

**Comment by samuelfernandez** [comment]
@FrozenPandaz I also wonder if it would be useful to remove migrations.json after migrations are run. This is useful in CI environments as renovate that commit files after migration to push a PR

**Comment by samuelfernandez** [comment]
@FrozenPandaz PR submitted
