### ISSUE TITLE
Turbopack for Next.js apps

### ISSUE THREAD

**Issue by exsesx** [nrwl/nx#14153]
## Description
Hey! Recently Next.js introduced a [Turbopack](https://turbo.build/pack) - The Rust-powered successor to Webpack, which is fast.

AFAIK we cannot add a `--turbo` flag to our `serve` executor. Could this be added to the Nx roadmap and developed in the future?

## Motivation
The primary motivation is to build front-end apps blazingly fast.

## Suggested Implementation
Allow bypassing args to the `serve` executor?

**Comment by nowlena** [comment]
Is there any plan to support this in the future?

**Comment by shlomich** [comment]
Hello?

**Comment by gauthierelcapitan** [comment]
Very interested in this feature as well !

**Comment by michaelangrivera** [comment]
+1

**Comment by nickcanarelli** [comment]
Any update on this? Would definitely like to take advantage of the perceived 700x faster than Webpack claim.

**Comment by fcisio** [comment]
Any update on this?

**Comment by ndcunningham** [comment]
This has been added as of release `16.3.0` 
Release: https://github.com/nrwl/nx/releases/tag/16.3.0 
PR: https://github.com/nrwl/nx/pull/17069
