### ISSUE TITLE
Lint rules are not applied

### ISSUE THREAD

**Issue by takthetank** [nrwl/nx#14157]
### Current Behavior

I have created a new Nx project with Angular and ESLint and some rules are not working. 
The same rules when configured in a plain Angular project are working fine, same happens in `typescript-eslint` playground (check [here](https://typescript-eslint.io/play#ts=4.8.4&sourceType=module&showAST=es&code=PQKhAIDMHtvBjANgQwM6vCYBYAUAUwA8AHaAJwBcEV1wAxWcAbz3HFAgoAt9xULkFAJbxwAW3zdoAE0w5cbYgFcARohF8Bw0cgDKWkQFlJXGQAoAlAC5wAN2hDZLBW3bBNSyJFbgAvnh8OcG5eZTUNYjJoYnxKAE85HzD1HQAFKOIbADslMRVY8ABecABWAG4AlyCQhGgs-jIleApyRJdkjXg6hqaWsktmHzZgd3wxYgo4n39cGaA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6AW0XYCNFpaA9tAAmfZgHN0YANrhsOPtCGQANHPlZ52SKIBmAQwT4psrVsjJ8+-JTK1O+ABYDhq9WaiXrt2rsqJ4VzUPbWJYbkY7Zi8mMkRff0C3EJwwiJ99bktofTI6PwCg9zNIYiV8RDzEYVpoq1j4gqTglNLyyoqazOzc-MSilKgyygA3a3i6-QaEwuTWsgEmbNg85RaQ0vDI2qX6uPtEJxc5jbTt7vwcvIOjgdaygQqqmsnph2c70-bn2gurunex3WHjao3GOxi+0BrmK2AAurCAL7uOHAvBEUjICjUOgMZhsJgCHa6RSZJC0DEoEywyACXS6E7YTQlSjiQnQRAABX0OQcfFQGEusEQSJRcmRiKAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA) for a working demo).
In order to reproduce the issue please check the provided repo.

### Expected Behavior

ESLint rules should behave the same, both in plain and Nx Angular projects.

### Github Repo

https://github.com/takthetank/eslint-repro

### Steps to Reproduce

1. Clone eslint-repo
2. If running from outside of `tfs.qualco.int` network delete lock file first
3. Run `yarn install`
4. Run `yarn lint:all` 
5. Check output for lint failures.

### Nx Report

```shell
Node : 16.17.0
   OS   : win32 x64
   yarn : 1.22.19

   nx : 15.4.4
   @nrwl/angular : 15.4.4
   @nrwl/cypress : 15.4.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.4
   @nrwl/js : 15.4.4
   @nrwl/linter : 15.4.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.4.4
   @nrwl/workspace : 15.4.4
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nguniversal/builders: 15.0.0
```

### Failure Logs

```shell
$ nx run-many --target=lint --parallel=1 --nx-bail=true --all


    ×  nx run demo-app:lint
       Linting "demo-app"...

C:\git\eslint-repro\apps\demo-app\src\repro.ts
  9:4  error  Member aProp should be declared before all static method definitions          @typescript-eslint/member-ordering
  9:4  error  Type number trivially inferred from a number literal, remove type annotation  @typescript-eslint/no-inferrable-types

✖ 2 problems (2 errors, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

Lint errors found in the listed files.



 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Ran target lint for project demo-app (7s)

    √    0/1 succeeded [0 read from cache]

    ×    1/1 targets failed, including the following:
         - nx run demo-app:lint
```

**Comment by meeroslav** [comment]
Thank you, @takthetank, for reporting it.

Unfortunately, this is not a bug but rather a slight misconfiguration on your side. You have overridden the configuration for `@typescript-eslint/member-ordering` and `@typescript-eslint/no-inferrable-types` in the root `.eslintrc.json` but you application's eslint config has following config:

```json
{
  "files": ["*.ts"],
  "rules": {},
  "extends": ["plugin:@nrwl/nx/angular"]
}
```

This means that whatever configuration is set in the root will be overridden for `.ts` files with rules set by `@nrwl/nx/angular` plugin.

There are two ways how you can fix this:
- Apply the initial overrides on the application level or
- Create a single `overrides` config that you would extend in each application: 

Application's `.eslintrc.json`
```json
{
  "extends": ["../../.eslintrc.json"],
  "ignorePatterns": ["!**/*"],
  "overrides": [
    {
      "files": ["*.ts"],
      "rules": {},
      "extends": ["plugin:@nrwl/nx/angular",  "../../eslintrc-custom-overrides.json"]
    }
  ]
}
```

Root overrides `eslint-custom-overrides.json`:
```jsonc
{
  "overrides": [
    {
      "files": ["*.ts"],
      "rules": {
         // you overrides here
      }
    }
  ]
}
```  

Please find an old issue explaining this here: https://github.com/nrwl/nx/issues/5866

**Comment by takthetank** [comment]
I see, however these `.eslint.rc` files are generated like that from nx. When I generate a project and libs from Angular `ng` cli, they are generated fine and no override issues occur :)
