### ISSUE TITLE
enforce-module-boundaries by libs NOT containing sourceTag

### ISSUE THREAD

**Issue by jakeensor-8451** [nrwl/nx#14173]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Support some means of negating the `sourceTag` being matched on for `enforce-module-boundaries` eslint plugin.

## Motivation
We are trying to setup a lib in NX with a `scope:example` tag, such that it can only be imported by other libs with a `scope:example` tag.

We were hoping to set it up like this:

```
{
  "sourceTag": "*",
  "notDependOnLibsWithTags": ["scope:example"]
},
{
   "sourceTag": "scope:example",
   "onlyDependOnLibsWithTags": ["scope:example"]
}
```

This doesn't work, because the 1st rule applies even to the `scope:example` libs, preventing them from importing other `scope:example` libs.

We could fix this by adding a new tag to all of our existing libs, so we can replace the `*` in the second rule with that new tag.

This is not ideal, because if other devs make a new lib, the rule will not be enforced unless they manually add the new tag to it.

## Suggested Implementation
I think this would be a pretty trivial update in the enforce-module-boundary plugin code. It could look something like:

```
{
   "sourceTag": "scope:example",
   "onlyDependOnLibsWithTags": ["scope:example"]
},
{
  "libsNotContainingSourceTag": "scope:example",
  "notDependOnLibsWithTags": ["scope:example"]
}
```

Or possibly allow the sourceTag field to be negated with a `!` like:

```
{
   "sourceTag": "scope:example",
   "onlyDependOnLibsWithTags": ["scope:example"]
},
{
  "sourceTag": "!scope:example",
  "notDependOnLibsWithTags": ["scope:example"]
}
```

## Alternate Implementations
Open to ideas!

If there's some "right" way to achieve this that I'm missing, please let me know!

**Comment by meeroslav** [comment]
Hi @jakeensor-8451,

This is a helpful feature, albeit very specific. My suggestion would be to allow regexes as the `sourceTag`. 

This would:
- Save us from polluting rule API with yet another property
- Give us more flexibility for any special requirements in the future

Currently, tags support:
- Full text
- Wildcard `*`

We can introduce a convention where regex is wrapped in `/.../`.
The only place that needs to be changed then is: https://github.com/nrwl/nx/blob/master/packages/eslint-plugin-nx/src/utils/runtime-lint-utils.ts#L87

So in your case you would specify the constraints as:
```JSON
{
  "sourceTag": "/^(?!scope:example)/",
  "notDependOnLibsWithTags": ["scope:example"]
},
{
   "sourceTag": "scope:example",
   "onlyDependOnLibsWithTags": ["scope:example"]
}
```
