### ISSUE TITLE
Using library generator downgrades jest

### ISSUE THREAD

**Issue by janeklb** [nrwl/nx#14196]
### Current Behavior

- run `nx generate @nrwl/node:library mylibrary` on a project with `jest@28.1.3`
- your `package.json` will now have `jest@28.1.1`

### Expected Behavior

jest version is not changed when generating a library project

### Steps to Reproduce

1. add/upgrade to `jest@28.1.3` in your NX project
2. run `nx generate @nrwl/node:library mylibrary`
3. `package.json` will have downgraded to `jest@28.1.1`

### Nx Report

```shell
npm run nx report

> nx
> nx report


 >  NX   Report complete - copy this into the issue template

   Node : 16.18.1
   OS   : darwin x64
   npm  : 8.19.3

   nx : 15.4.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.2
   @nrwl/expo : Not Found
   @nrwl/express : 15.4.2
   @nrwl/jest : 15.4.2
   @nrwl/js : 15.4.2
   @nrwl/linter : 15.4.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.4.2
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.4.2
   @nrwl/web : 15.4.2
   @nrwl/webpack : 15.4.2
   @nrwl/workspace : 15.4.2
   @nrwl/vite : 15.4.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Additional Information

I'm not sure if this should be treated as a problem with the generator, or if nx's jest is support is currently pinned to 28.1.1 -- maybe im missing something here?

**Comment by amakhrov** [comment]
It is effectively the same as https://github.com/nrwl/nx/issues/13687?

**Comment by amakhrov** [comment]
In addition to `jest` itself, NX also tries to downgrade `@types/jest` from the latest patch 28.1.8 to 28.1.1.
And `jest-enviromnent-jsdom`

**Comment by janeklb** [comment]
> It is effectively the same as #13687?

Looks like it!

**Comment by barbados-clemens** [comment]
I am not seeing this behavior with the reproduceable steps. Jest is staying at the version that is specified in the package.json. Can you try this with the latest version of nx (15.5.0 at the time of comment)

![image of terminal output which is shown below this image as text](https://user-images.githubusercontent.com/23272162/212362276-2fdb98ef-ab93-489c-a22f-9b22cb92a1a6.png)

```
❯ npm ls jest
dep-downlevel-example@0.0.0 /Users/caleb/Work/sandbox/dep-downlevel-example
├── jest@28.1.3
└─┬ ts-jest@28.0.5
  └── jest@28.1.3 deduped

❯ npx nx g lib sample
✔ Which generator would you like to use? · @nrwl/node:library

>  NX  Generating @nrwl/node:library

CREATE libs/sample/README.md
CREATE libs/sample/.babelrc
CREATE libs/sample/src/index.ts
CREATE libs/sample/src/lib/sample.spec.ts
CREATE libs/sample/src/lib/sample.ts
CREATE libs/sample/tsconfig.json
CREATE libs/sample/tsconfig.lib.json
UPDATE tsconfig.base.json
CREATE libs/sample/project.json
CREATE libs/sample/.eslintrc.json
CREATE libs/sample/jest.config.ts
CREATE libs/sample/tsconfig.spec.json
❯ bat package.json | grep jest
    "@nrwl/jest": "15.5.0",
    "@types/jest": "28.1.1",
    "jest": "28.1.3",
    "jest-environment-jsdom": "28.1.1",
    "ts-jest": "28.0.5",
❯ npm ls jest
dep-downlevel-example@0.0.0 /Users/caleb/Work/sandbox/dep-downlevel-example
├── jest@28.1.3
└─┬ ts-jest@28.0.5
  └── jest@28.1.3 deduped
```

**Comment by janeklb** [comment]
Still happening to me with nx 15.5.1, though it's not on a fresh project

**Comment by barbados-clemens** [comment]
@janeklb do you have a project I can clone that is showing this behavior. I can't reproduce it as I mentioned in my comment so wondering if there's something else at play?

**Comment by janeklb** [comment]
@barbados-clemens here's a repo to illustrate: https://github.com/janeklb/nx-14196

Then run 
```

**Comment by janeklb** [comment]
Theres a handful of references to this specific version in nrwl/nx -- eg. https://github.com/nrwl/nx/blob/c6adec7f9d9536eee9507cdc38a0209af69dce02/packages/jest/src/utils/versions.ts#L2


https://github.com/search?q=repo%3Anrwl%2Fnx%2028.1.1&type=code

**Comment by barbados-clemens** [comment]
Okay tracked this down to the @nrwl/devkit function [`addDependenciesToPackageJson`](https://github.com/nrwl/nx/blob/c6adec7f9d9536eee9507cdc38a0209af69dce02/packages/devkit/src/utils/package-json.ts#L120-L140) where if any of the incoming versions was greater than all deps get added to the package.json instead of just those that are greater. 

I'll get a PR up for that later this week.
