### ISSUE TITLE
MF typescript support

### ISSUE THREAD

**Issue by codrin-iftimie** [nrwl/nx#14194]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Module federation is a great feature that applies well to monorepos. What would be nice is to get the best developer experience out of it. Currently, we are forced to manually create types for our external libraries and apps. There are ways around it but they don't work [that well](https://github.com/ruanyl/webpack-remote-types-plugin). I was waiting until this topic would get more traction, and I've stumbled upon [@module-federation/typescript](https://github.com/module-federation/universe/tree/main/packages/typescript). Looks like a good project.

## Motivation
It would benefit most of the developers that use MF and typescript. I, for one, want to create a library of components and utilities without the hassle of versioning / publishing / hosting it.

## Suggested Implementation
I've noticed that for the SSR the node version of it is used. Similarly to this, instead of using the webpack `ModuleFederation` it would be a simple swap to use the @module-federation/typescript plugin. I've already hacked a version for myself locally where I used most of the configuration overwrites from `withModuleFederation` and pushed the `FederatedTypesPlugin` 

<details>
  <summary>Hacked Version</summary>

  ```js
const moduleFederationConfig = require('./module-federation.config');
const FederatedTypesPlugin = require('@module-federation/typescript').default;

module.exports = function (config) {
  config.plugins.push(
    new FederatedTypesPlugin({
      federationConfig: {
          ...moduleFederationConfig,
          remotes: {
            app1: 'http://localhost:4202/remoteEntry.js',
            app2: 'http://localhost:4201/remoteEntry.js',
          },
        },
      })
    );

    config.output.uniqueName = moduleFederationConfig.name;
    config.output.publicPath = 'auto';

    config.optimization = {
      runtimeChunk: false,
    };

    config.experiments = {
      ...config.experiments,
      outputModule: true,
    };

    return config;
};
```

</details>

Even managed to hack the tsconfig.json to comply with the plugin. This part is a bit messy and I'm not 100% how to glue everything together. I might need some pointers.
```json
"paths": {
    "*": ["./apps/host/@mf-types/*"]
 }
 ```

**Comment by codrin-iftimie** [comment]
The only blocker is this small issue upstream: https://github.com/module-federation/universe/issues/486, but the fix is already filed and it in pretty soon.

**Comment by stefan-karlsson** [comment]
If using Vite as the bundler you can use https://github.com/originjs/vite-plugin-federation

**Comment by JoaoPLGomes** [comment]
What's the status on this?

**Comment by jgarciaokode** [comment]
@codrin-iftimie could you share the webpack config from host and remote, or even better the repo? I can't get it to work

Nx team, please could you provide some details on how it should be implemented? I thought we could use custom webpack config but it seems it is not so easy
