### ISSUE TITLE
ng update for v8 not making changes to app.module or tsconfig in apps folders or root directory

### ISSUE THREAD

**Issue by goelinsights** [nrwl/nx#1419]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

## Expected Behavior

On ng update to v8, changes to tsconfig and app.module are supposed to happen with ng update to enable lazy loading template change, differential loading, etc
`The CLI's build command now automatically creates a modern ES2015 build with minimal polyfills and a compatible ES5 build for older browsers, and loads the appropriate file based on the browser. You may opt-out of this change by setting your target back to es5 in your tsconfig.json.`
`For lazy loaded modules via the router, importing via string is deprecated. ng update will take care of this automatically. The new syntax leverages the ecosystem wide support for import rather than our custom rewrites. Your loadChildren route configs should be changed from a string such as loadChildren: './admin/admin.module#AdminModule' to an import statement such as loadChildren: () => import('./admin/admin.module').then(m => m.AdminModule). Learn more on angular.io.`

## Current Behavior

What is the current behavior?
the ng update doesn't make the stated changes in my nx-powered repo

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

ng update @angular/core @angular/cli in an existing nx repo

### Context

upgraded to latest version of nx and angular

### Failure Logs

N.A, appears to fail silently

## Other

Wondering if the workspace configuration with multiple apps and multiple tsconfigs isn't accounted for in the ng update schematics code and if therefore NX should extend the schematic.

**Comment by FrozenPandaz** [comment]
Thanks for reporting this issue!

We recommend you run `npm run update` to update `@angular/core` and `@angular/cli` through the Nx migration. There's a separate issue at the moment so please run `npm run update -- @angular/core` for now.

Please let me know if this solves the issue.

Also if you can provide a repo, I can identify if there is indeed an issue with the `@angular` migrations.

**Comment by goelinsights** [comment]
I'm getting the following, Seems like maybe the migrations directory installed incorrectly?: 


Error: ENOENT: no such file or directory, scandir ...
at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/vijay/ng2_projects/chfl/node_modules/@nrwl/workspace/migrations/legacy-migrations'

**Comment by goelinsights** [comment]
Hmm...went back to a pre-migration version and tried it again with ng update @nrwl/schematics and strangely it seemed to work!
