### ISSUE TITLE
[JSON]: make parsing lenient by default and display better errors

### ISSUE THREAD

**Issue by vicb** [nrwl/nx#14203]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Nx uses [`JSON.parse`](https://github.com/nrwl/nx/blob/e8b2731a479c365a7191b610f983fcc3f863f9dd/packages/nx/src/utils/json.ts#L45)

It has several pain points:
- It does not support trailing comma - while TS is happy with them i.e. when reading `tsconfig.json`,
- The error messages are helpless: `Error in JSON at position 1234`

It should be easy to switch parser.

Typescript uses https://www.npmjs.com/package/jsonc-parser (as a devDependency)

https://www.npmjs.com/package/parse-json seems to have nice error messages.

The hard part for this issue is probably to pick the right parser...

**Comment by Phillip9587** [comment]
Nx already uses `jsonc-parser`. I implemented the json utils in #5859. 

Take a look at:

- https://nx.dev/packages/devkit/documents/index#parsejson
- https://nx.dev/packages/devkit/documents/index#serializejson
- https://nx.dev/packages/devkit/documents/index#stripjsoncomments

- https://nx.dev/packages/devkit/documents/index#readjson
- https://nx.dev/packages/devkit/documents/index#readjsonfile

- https://nx.dev/packages/devkit/documents/index#writejson
-  https://nx.dev/packages/devkit/documents/index#writejsonfile

**Comment by vicb** [comment]
Oh thanks!

https://github.com/nrwl/nx/blob/e8b2731a479c365a7191b610f983fcc3f863f9dd/packages/nx/src/utils/json.ts#L40-L58

Sorry I stopped parsing the code at `return JSON.parse(input);` :(

Because we already use `jsonc-parser` I wonder if:

- it would make sense to make `parseJson` lenient by default (allow comment and trailing commas),
- it woud be possible to display better error message than `Error in JSON at position 1234` - it wonder if `getLocation` could help here.
