### ISSUE TITLE
Express in not found when installing with pnpm 

### ISSUE THREAD

**Issue by morbargig** [nrwl/nx#14219]
### Current Behavior

clone new project
install dependencies with pnpm
use express for few features 
get error module not found

`ERROR in ./apps/mor/src/main.ts 11:18-36
Module not found: Error: Can't resolve 'express' in '/Users/morbargig/Desktop/Projects/ideo/Phoenix/B2B/test-2/apps/mor/src'

webpack compiled with 1 error (532660906b382153)
There was an error with the build. See above.
/Users/morbargig/Desktop/Projects/ideo/Phoenix/B2B/test-2/dist/apps/mor/main.js was not restarted.
Type-checking in progress...
ERROR in ./apps/mor/src/main.ts:9:34
TS2307: Cannot find module 'express' or its corresponding type declarations.
     7 | import { NestFactory } from '@nestjs/core';
     8 | import { AppModule } from './app/app.module';
  >  9 | import { json, urlencoded } from 'express';
       |                                  ^^^^^^^^^
    10 |
    11 | async function bootstrap() {
    12 |   const app = await NestFactory.create(AppModule);

Found 1 error in 2352 ms.`

when install via npm everything works fine

![image](https://user-images.githubusercontent.com/51287453/211203541-a7f4a807-4177-47fd-9965-1c0c1bffe172.png)

### Expected Behavior

Expect the code to understand the dependency of the package `@nestjs/platform-express`
and it @types from express, which in NPM works just fine.

Is the package @nestjs/platform-express depended on `express`
it can also make sure the dependency clean to any package manager.
Or even export the types and features of it.

### Github Repo

https://github.com/morbargig/repo-for-nestjs-bug

### Steps to Reproduce

// not working
1. git clone https://github.com/morbargig/repo-for-nestjs-bug.git
2. pnpm install
3. pnpm nx run mor:serve

// working
1. git clone https://github.com/morbargig/repo-for-nestjs-bug.git
2. npm install
3. npx nx run mor:serve

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 19.4.0
   OS   : darwin x64
   pnpm : 7.22.0
   
   nx : 15.4.5
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.5
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.5
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.5
   @nrwl/js : 15.4.5
   @nrwl/linter : 15.4.5
   @nrwl/nest : 15.4.5
   @nrwl/next : Not Found
   @nrwl/node : 15.4.5
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.4.5
   @nrwl/workspace : 15.4.5
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
> nx run mor:serve

chunk (runtime: main) main.js (main) 2.95 KiB [entry] [rendered]

ERROR in ./apps/mor/src/main.ts 11:18-36
Module not found: Error: Can't resolve 'express' in '/Users/morbargig/Desktop/Projects/ideo/Phoenix/B2B/test-2/apps/mor/src'

webpack compiled with 1 error (532660906b382153)
There was an error with the build. See above.
/Users/morbargig/Desktop/Projects/ideo/Phoenix/B2B/test-2/dist/apps/mor/main.js was not restarted.
Type-checking in progress...
ERROR in ./apps/mor/src/main.ts:9:34
TS2307: Cannot find module 'express' or its corresponding type declarations.
     7 | import { NestFactory } from '@nestjs/core';
     8 | import { AppModule } from './app/app.module';
  >  9 | import { json, urlencoded } from 'express';
       |                                  ^^^^^^^^^
    10 |
    11 | async function bootstrap() {
    12 |   const app = await NestFactory.create(AppModule);

Found 1 error in 2201 ms.
```

### Additional Information

I am using NestJS in my enterprise production products.
So this is very important to me. 
Any help will be very handy.

**Comment by cohoren** [comment]
Yes, the same issue here.
Looks like a bug in the nx version.
Hopefully they will fix it soon...

**Comment by AgentEnder** [comment]
This doesn't really sound like a bug on our side, can you try to repro in a plain nestjs project and open an issue on the nest github?
