### ISSUE TITLE
workspace-schematics guide is empty

### ISSUE THREAD

**Issue by fxck** [nrwl/nx#1421]
Not sure if it was moved, or removed, but it's linked from a couple of resources (some blog posts, SO answers) https://nx.dev/guides/tools-workspace-schematics and it's empty save for the title.

https://stackoverflow.com/q/51610745/301596
https://medium.com/@simonb90/create-workspace-specific-schematics-with-nrwl-nx-9a1b7cd65345

**Comment by FrozenPandaz** [comment]
Hm, I don't think it ever existed.

It would be a nice page to write but I have not had the time.

**Comment by Hotell** [comment]
This can be closed cc @FrozenPandaz  -> https://connect.nrwl.io/app/cookbook/4in0DECnRZILfXVMh7Mdtr
