### ISSUE TITLE
Print-affected fails on maximum call stack in NX 15.4.4+

### ISSUE THREAD

**Issue by belaczek** [nrwl/nx#14224]
### Current Behavior

`nx print-affected` script fails with `Maximum call stack size exceeded` error message. 
At the same time, nx postinstall script is sometimes hanging indefinitely with a fresh install. I feel like these two might be related since postinstall script runs `./bin/compute-project-graph`. 

### Expected Behavior

Postinstall script doesn't hang indefinitely. `print-affected` script returns a list of affected projects instead of failing with error.

### Steps to Reproduce

Installation failure
1. run `yarn install` in a project with nx 15.4.5
Print affected failure
1. execute `nx print-affected`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 19.2.0
   OS   : darwin arm64
   yarn : 1.22.19

   nx : 15.4.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.5
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.5
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.5
   @nrwl/js : 15.4.5
   @nrwl/linter : 15.4.5
   @nrwl/nest : Not Found
   @nrwl/next : 15.4.5
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.5
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.5
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.4.5
   @nrwl/web : 15.4.5
   @nrwl/webpack : 15.4.5
   @nrwl/workspace : 15.4.5
   @nrwl/vite : 15.4.5
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
node:internal/errors:863
  const err = new Error(message);
              ^

Error: Command failed: nx print-affected --select=projects

    at __node_internal_genericNodeError (node:internal/errors:863:15)
    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:298:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'nx print-affected --select=projects',
  stdout: '\n' +
    ' >  NX   Maximum call stack size exceeded\n' +
    '\n' +
    '   \n' +
    '   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.\n' +
    '   If the error persists, please run "nx reset".\n' +
    '\n',
  stderr: ''
}
```

### Additional Information

Since both errors are quite unpredictable and hard to reproduce reliably, I have to apologize for not being able to provide more useful info. However, the issue was reported by multiple members of our team. The issue never appeared before with version 15.4.2.

**Comment by belaczek** [comment]
Thanks, that's a good point I forgot to mention: It actually fails 100% in our CI too. We use Gitlab CI with node:alpine image and these are last few lines from the install-dependencies step, where it hangs until timeout
```
Progress: resolved 2865, reused 0, downloaded 2850, added 2864
Progress: resolved 2865, reused 0, downloaded 2851, added 2865, done
.../node_modules/core-js-pure postinstall$ node -e "try{require('./postinstall')}catch(e){}"
.../core-js@3.26.1/node_modules/core-js postinstall$ node -e "try{require('./postinstall')}catch(e){}"
.../node_modules/@parcel/watcher install$ node-gyp-build
.../node_modules/core-js-pure postinstall: Done
.../node_modules/postinstall-postinstall postinstall$ node ./run.js
.../core-js@3.26.1/node_modules/core-js postinstall: Done
.../node_modules/postinstall-postinstall postinstall: Done
.../node_modules/@parcel/watcher install: Done
.../esbuild@0.15.18/node_modules/esbuild postinstall$ node install.js
.../esbuild@0.16.14/node_modules/esbuild postinstall$ node install.js
.../esbuild@0.15.18/node_modules/esbuild postinstall: Done
.../esbuild@0.16.14/node_modules/esbuild postinstall: Done
.../node_modules/msw postinstall$ node -e "try{require('./config/scripts/postinstall')}catch(e){}"
.../node_modules/msw postinstall: Done
.../.pnpm/nx@15.4.5/node_modules/nx postinstall$ node ./bin/compute-project-graph
.../.pnpm/nx@15.4.5/node_modules/nx postinstall:  >  NX   Daemon Server - Stopped
ERROR: Job failed: execution took longer than 1h0m0s seconds
```

**Comment by FrozenPandaz** [comment]
Is anybody able to provide a reproduction for this?

**Comment by aniravi24** [comment]
Not sure if I can provide a repro, but it's still happening on the latest version (15.5.2) for me. I combed through the release notes and this is one PR in the 15.4.3 changes 
(since the issue happens > 15.4.2) that looks suspect but it's mainly a guess: https://github.com/nrwl/nx/pull/13138/files

I noticed there were some functions refactored here that probably get called a lot, but I'm not sure why the error would only occur in CI and not locally. The call stack sizes are the same between the CI environment and my local environment, so the error could be slightly misleading and caused by something else entirely.

Any thoughts on debugging steps I could try (or building NX myself with some commits reverted)? Or maybe other changes in [15.4.3](https://github.com/nrwl/nx/releases/tag/15.4.3) that look of interest to you that are related to core, misc, or graph? The other ones wouldn't apply to me.

**Comment by ghardin1314** [comment]
Also having the same issues in CI using v15.6.3. Does not happen in development. Can't even get a trace using `--verbose` on the failing commands. Reverting to v15.4.2 solved the issue

**Comment by aniravi24** [comment]
Still seeing this in 15.7.1 so bumping to avoid closing

**Comment by aniravi24** [comment]
This issue has gotten worse for my project in the newer versions of NX (the project has increased in size with more dependencies so it could be that too). Before it used to fail with this error only when running `print-affected`, but now running `yarn` in CI is enough to trigger it (so the `postinstall` script doesn't run without crashing). Using yarn 3 with the node-modules linker.

Unfortunately, it's a private project so if there are any alternate ways I can debug or print more information to give you, let me know.

**Comment by aniravi24** [comment]
Using the latest Nx, I'm actually not seeing this issue anymore in my project, at least for now. Was able to actually upgrade! 😁
