### ISSUE TITLE
npx -c 'nx watch --all -- echo \$NX_PROJECT_NAME' outputs \$NX_PROJECT_NAME instead of the actual project name

### ISSUE THREAD

**Issue by AkumaTen** [nrwl/nx#14222]
### Current Behavior

When I run the command **npx -c 'nx watch --all -- echo \\$NX_PROJECT_NAME'** as per documentation in a VS Code terminal (Windows), with Nx Console v17.27.1 and Nx 15.4.5, I expect to get the project name as the output of the echo command. 
The following is what I get when --verbose is used

- about to run commands with these environments: [{"NX_PROJECT_NAME":"playground","NX_FILE_CHANGES":"apps/playground/src/app/app.tsx"}]
- \\$NX_PROJECT_NAME (this is the actual output of the echo command)

The terminal is PowerShell

### Expected Behavior

the project name, in my case **playground** instead of \\$NX_PROJECT_NAME

### Steps to Reproduce

execute **npx -c 'nx watch --all -- echo \\$NX_PROJECT_NAME'** as per documentation  in a powershell terminal in VS Code for Windows

### Nx Report

```shell
Node : 16.17.1
   OS   : win32 x64
   npm  : 8.19.2

   nx : 15.4.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.5
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.5
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.5
   @nrwl/js : 15.4.5
   @nrwl/linter : 15.4.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.4.5
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.5
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.5
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.4.5
   @nrwl/webpack : 15.4.5
   @nrwl/workspace : 15.4.5
   @nrwl/vite : 15.4.5
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Additional Information

The goal is to be able to run **nx run \\$NX_PROJECT_NAME:build:development** instead of the echo example

**Comment by AkumaTen** [comment]
It turned out that in Windows the working command is **npx -c 'nx watch --all --verbose -- echo %NX_PROJECT_NAME%'**

After inspected watch.js I found that a child process is created with an environment containing NX_PROJECT_NAME. The child process is  a command prompt even if the main process is the PowerShell Terminal in VS Code. That's why % is needed instead of that \\$ stated in the doc.

Please make the documentation clearer especially for Windows user. Thanks! :)

**Comment by Cammisuli** [comment]
Oh, thanks for checking that out. It totally makes sense and I will update the documentation to reflect that. 

Thank you!

**Comment by dopenguin** [comment]
I had a similar issue occurring when invoking `nx watch` through a npm script.
Instead of powershell I used Git bash and using the syntax described by @AkumaTen fixed the issue as well.
