### ISSUE TITLE
nx affected option for "--exclude" not working with a list of projects with "target=test" and "target=lint"

### ISSUE THREAD

**Issue by jessewilliams1** [nrwl/nx#14221]
### Current Behavior

We currently have a monorepo with around 30 projects in  it.
When running the `nx affected` command, the `--exclude` option has no effect. The listed projects are not excluded.

`nx affected --target=test --exclude=api, frontend, admin-api`

NX then proceeds to run for all projects, ignoring the `--exclude` list:

```
 >  NX   Running target lint for 30 projects:
    - api
    - frontend
    - admin-api
    ...
```

This is happening for both `target=lint` and `target=test` as far as we can tell.

When running `nx affected` with a single option, i.e. `--exclude=api` it works as you would expect and that single project is indeed excluded.

Perhaps the documentation is just off?
https://nx.dev/packages/nx/documents/affected

### Expected Behavior

The projects listed in the `--exclude` option should be excluded

### Steps to Reproduce

1.Run the `nx affected` command with the `exclude` option as a list.

### Nx Report

```shell
Node : 18.12.1
   OS   : win32 x64
   npm  : 8.1.3

   nx : 15.4.5
   @nrwl/angular : 15.4.5
   @nrwl/cypress : 15.4.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.5
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.5
   @nrwl/expo : Not Found
   @nrwl/express : 15.4.5
   @nrwl/jest : 15.4.5
   @nrwl/js : 15.4.5
   @nrwl/linter : 15.4.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.4.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.4.5
   @nrwl/workspace : 15.4.5
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @fortawesome/angular-fontawesome: 0.12.0
         @ng-bootstrap/ng-bootstrap: 14.0.0
         ng2-charts: 4.1.1
         @nx-tools/nx-container: 4.0.2
```

### Additional Information

__Update:__ This was previously working as expected in nx `14.6.2`

**Comment by AgentEnder** [comment]
Can you try this without the space after the `,`? Its likely that the args are not being interpreted as a group.

**Comment by jessewilliams1** [comment]
> Can you try this without the space after the `,`? Its likely that the args are not being interpreted as a group.

Same result!
