### ISSUE TITLE
@nrwl/cypress upgrade for supporting Cypress v12

### ISSUE THREAD

**Issue by mi4i0** [nrwl/nx#14225]
- [ ] @nrwl/cypress need to be upgraded for supporting Cypress v12

## Description
Cypress max version should be updated to include v12 as for now max is v11

![image](https://user-images.githubusercontent.com/18115147/211312548-fbff5a29-b661-4598-bea5-de7ba1f5bfb3.png)

**Comment by AgentEnder** [comment]
See: #13846
