### ISSUE TITLE
What is the purpose of the pnpm alias?

### ISSUE THREAD

**Issue by JP3tri3** [nrwl/nx#14220]
### Current Behavior

- When using nx cli with pnpm to generate, the cli advises to use an alias specifically stating `create a shortcut such as: alias pnx="pnpm nx --"`
- After setting up this alias, nx commands are no longer recognized due to the `--`
- setting up the alias using just 'pnpm nx' works fine.

### Expected Behavior

- CLI suggestion should suggest `create a shortcut such as: alias pnx="pnpm nx"` or not provide an alias recommendation since it appears to work fine with only utilizing nx.

### Steps to Reproduce

1. Using a workspace preference with pnpm, run any nx generate command and view suggested alias.
2. Setup suggested alias `alias pnx="pnpm nx --"`
3. Use alias to generate, example `pnx generate @nrwl/angular:library-secondary-entry-point ....`
4. Notice it executes but does nothing if the command is invalid, but does throw an nx report error if the command is valid.

### Nx Report

```shell
ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command failed with ENOENT: nx-- generate @nrwl/angular:library-secondary-entry-point --library=library-name --name=name-of-
spawn nx-- ENOENT
```

**Comment by wSedlacek** [comment]
https://github.com/nrwl/nx/pull/4556

@bekos I don't suppose you know why this warning was added?
I saw your PR but there wasn't a description as to what the alias fixes

**Comment by bekos** [comment]
@wSedlacek The alias wasn't fixing anything, it was just a tip, as a shortcut to using `pnpm run nx`.
PNPM 7 has changed the way that extra arguments are handled, so I suppose the tip is not fully correct atm.

**Comment by wSedlacek** [comment]
But is `nx` installed globally doing something that doesn't work with pnpm that would need to execute the local bin instead?

**Comment by bekos** [comment]
It was in some cases :) But many things have changed since then, both on Nx and pnpm so maybe that is not relevant anymore.

**Comment by wSedlacek** [comment]
@bekos Thank you very much for the context!

**Comment by FrozenPandaz** [comment]
It seems to me like this isn't needed anymore. `nx` commands work for me. Why don't we remove it and we can restore it if we find there are still issues?

Would somebody like to send a PR?
