### ISSUE TITLE
Getting the current build configuration name

### ISSUE THREAD

**Issue by flippidippi** [nrwl/nx#14242]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

The ability to identify the current configuration that is being used to build the project.

## Motivation

- This would allow us to reference a single environment file that can change values according to the current configuration name.
- It would also allow knowing the current configuration without multiple environment files to reference

## Suggested Implementation

We could add a new `NX_TARGET_CONFIGURATION_NAME` environment variable for configuration name.
We could also add `NX_TARGET_NAME` that could be useful.

## Alternate Implementations

Allow custom env values in configuration

**Comment by FrozenPandaz** [comment]
Can you provide a more specific example please? Would you expect Nx to pick up new [files like these](https://nx.dev/recipes/environment-variables/define-environment-variables#define-environment-variables) based on the configuration?

**Comment by flippidippi** [comment]
No we aren't using the `.env` files. We have environments files and switch them out with file replacements. We do this because we load secrets from AWS in the TS env files. 

So for example if we have a bunch of dev sites that all need the same settings except the name of the subdomain.
So we have `environments/dev1.ts`, `environments/dev2.ts`, etc. 
We uses file replacements in the `project.json` for each configuration to replace the default `environments/default.ts`.
Where the dev site envs look something like (1 file for each dev site in configurations)
```ts
export default async () => {
  const secrets = getFromAWS('dev')

  return { 
    apiEndpoint: `https://dev1.blah.com/api`
    key: secrets.apiKey
  }
}
```

What we would like to do is have each dev site reference the same environment file and get the configuration name like this
```ts
export default async () => {
  const secrets = getFromAWS('dev')

  return { 
    apiEndpoint: `https://${process.env.NX_TARGET_CONFIGURATION_NAME}.blah.com/api`
    key: secrets.apiKey
  }
}
```
