### ISSUE TITLE
Tutorial for migrating CRA app is wrong

### ISSUE THREAD

**Issue by alexiusp** [nrwl/nx#14248]
### Documentation issue

[ ] Reporting a typo
[x ] Reporting a documentation bug
[ ] Documentation improvement
[ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/recipes/adopting-nx/migration-cra

### Additional context or description

Documentation says I should just run `npx nx init` inside my app created with cra. But when I run this command nx tells me:

>  NX  The current directory isn't part of an Nx workspace.
  To create a workspace run:
  npx create-nx-workspace@latest <workspace name>
>  NX   NOTE  For more information please visit https://nx.dev/

**Comment by FrozenPandaz** [comment]
If you run `npm install nx` then it will work. Would you like to contribute the fix for the docs?

**Comment by alexiusp** [comment]
So I should run `npm install nx` inside the app manually before running `npx nx init`? I thought nx init should install all dependencies a project needs.

**Comment by isaacplmann** [comment]
This is working with the latest CRA and Nx versions
