### ISSUE TITLE
Starting inspector on localhost:5880 failed: address already in use

### ISSUE THREAD

**Issue by appsolutegeek** [nrwl/nx#1424]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

When NG rebuilds the project, i expect that it should continue to build.

## Current Behavior

It appears if i am in a debug session and then change the code which fires of NG to rebuild the project I get the following

```
Starting inspector on localhost:5880 failed: address already in use
```

I have to restart CtRL + C AND NG SERVE again..

### Context

Please provide any relevant information about your setup:

- version of Nx latest
- version of Angular CLI used 7.3.8
 Running on a MAC with Node 11

## Other

Any other relevant information that will help us help you.

**Comment by vsavkin** [comment]
@appsolutegeek thanks for submitting the issue. 

WebPack keeps the port open, so it cannot restart it. There is not much we can do about it. One thing you can do is to set the port to 0 in angular.json, which will tell webpack to use a random port. The build will work but your debugging session won't persist.
