### ISSUE TITLE
Unable to debug jest on Windows

### ISSUE THREAD

**Issue by remackgeek** [nrwl/nx#1425]
## Expected Behavior

Jest debugging in windows should work

## Current Behavior

Debugging errors out when attaching the chrome debugger:

F:\Dev\myworkspace>node --inspect-brk ./node_modules/.bin/ng test myworkspace
Debugger listening on ws://127.0.0.1:9229/9261bbcc-cc1c-4c3f-9b3e-ac5c36e77e2f
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
F:\Dev\myworkspace\node_modules\.bin\ng:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
Waiting for the debugger to disconnect...

## Failure Information (for bugs)

This only occurs on windows -- the same steps work on Ubuntu desktop

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a new project following the Getting Started Steps:
	npx --ignore-existing create-nx-workspace myworkspace
  choose SASS and regular angular

2. Verify  'ng serve' and 'ng test work'

3.  Start debug session:
       node --inspect-brk ./node_modules/.bin/ng test myworkspace

4. In chrome://inspect, click inspect link to attach, error occurs

### Context

latest (8.0.0) nx

F:\Dev\myworkspace>ng version
Angular CLI: 8.0.0
Node: 10.15.1
OS: win32 x64
Angular: 8.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@ngtools/webpack                  8.0.0
@schematics/angular               8.0.0
@schematics/update                0.800.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

### Failure Logs

Please include any relevant log snippets or files here.

## Other

Any other relevant information that will help us help you.

**Comment by peterblazejewicz** [comment]
just wondering if you have the same problem in non-NX project (while still on Windows box)?
facebook/jest#3750

**Comment by remackgeek** [comment]
@peterblazejewicz --
 I set up the example here:  [https://jestjs.io/docs/en/getting-started](https://jestjs.io/docs/en/getting-started)
Then followed the instructions here: [https://jestjs.io/docs/en/troubleshooting](https://jestjs.io/docs/en/troubleshooting)

This worked:
`node --inspect-brk ./node_modules/jest/bin/jest.js --runInBand`

**Comment by remackgeek** [comment]
Found it!  

The documentation ( [https://nx.dev/guides/modernize-jest](https://nx.dev/guides/modernize-jest) ) says to  use this command:
 `node --inspect-brk ./node_modules/.bin/ng test myworkspace`

But under Windows, this works: 
`node --inspect-brk ./node_modules/@angular/cli/bin/ng test myworkspace`

**Comment by vsavkin** [comment]
Yeah. It's an issue with the documentation. Could you send a PR updating the docs?
