### ISSUE TITLE
Create e2e folder inside application folder

### ISSUE THREAD

**Issue by na-ji** [nrwl/nx#14250]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

This is a feature request to be able to put the e2e folder inside the app itself, instead of having a separate app for it. This has already been asked for numerous times: #743, #4812 and even on [stackoverflow](https://stackoverflow.com/q/51763075/1058331). A PR was also proposed: #770.
Back then, the official answer, provided by vsavkin, was that it was made like this because NX schematics extended Angular CLI schematics that had this behavior. Starting Angular CLI 8, this behavior is no longer the default and the e2e folder is always created inside an app. So why NX didn't allow the possibility to create the e2e folder inside an application?

## Motivation

This behavior will allows reducing the clutter inside the folder listing applications, by reducing the number of application by two. 

## Suggested Implementation

I don't know how exactly is implemented NX, but providing to the users the possibility to create the e2e folder inside the application itself via a flag would be great.

**Comment by barbados-clemens** [comment]
With the most recent work with standalone and nested projects you should be able to do this now with the directory flag on the cypress-project generator. the directory will be prefixed with what is set as the apps directory by default. so you just need to provide the name of the folder the for the app you wish to test it in and the project name will be the folder name that the project goes in. i.e. 
if you have an app located in `apps/my-existing-project/`
then running
```bash
npx nx g @nrwl/cypress:cypress-project e2e --project=my-existing-project --directory=my-existing-project
```
will produce a cypress project in the `apps/my-existing-project/e2e/` folder 

if you have an existing project you want to nested, then you can use the `@nrwl/workspace:move` generator to move it into a subfolder.

**Comment by na-ji** [comment]
Thank you, it wasn't clear for me on how to do that.
