### ISSUE TITLE
Allow for path tokens (`{workspaceRoot}` & `{projectRoot}`) in `options.cwd` in targets

### ISSUE THREAD

**Issue by ItamarGronich** [nrwl/nx#14251]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Allow for interpolating path tokens such as `{projectRoot}` and `{workspaceRoot}` in `options.cwd` when defining a target.
Possibly, you could even generalize it further and maybe make tokens a first class citizen in any Nx configuration, kinda like go templates, where you could define your own custom ones, or use from an existing pool of predefined useful ones.

## Motivation

When defining a custom run commands target in a project.json, you must also supply the relative path from the workspace root to the project root.
Like so:
```json
{
  "dev": {
    "command": "webpack serve",
    "options": {
      "cwd": "apps/authentication"
    }
  }
}
```
But what if i want to move that project to another parent directory?
I would have to remember to change the `apps/authentication` to `new_folder/authentication`.
Or maybe write a custom plugin to do the move for me.

if i had tokens here i could avoid this refactoring step and simplify the process.

## Suggested Implementation

Maybe in one of these ways (possibly both?):
1. Make custom run commands inside project.json default to projectRoot instead of workspaceRoot.
2. allow using tokens in cwd to change it to where ever you need.
something like:
```json
{
  "dev": {
    "command": "webpack serve",
    "options": {
      "cwd": "{projectRoot}"
    }
  }
}
```
```json
{
  "dev": {
    "command": "webpack serve",
    "options": {
      "cwd": "{workspaceRoot}/some/where/else"
    }
  }
}
```

## Alternate Implementations

Just use tokens without changing the default to projectRoot.
```json
{
  "dev": {
    "command": "webpack serve",
    "options": {
      "cwd": "{projectRoot}"
    }
  }
}
```

**Comment by FirstWhack** [comment]
+1, currently have to copy entire task definitions only to change the `cwd`

**Comment by arimgibson** [comment]
To add onto this, would love to see the same functionality built into `envFile`!

Agree that option 1 will break existing configurations but doesn't seem like option 2 has any side effects. Just builds off current functionality

**Comment by miluoshi** [comment]
Not stale. It's still relevant for us.

**Comment by AgentEnder** [comment]
Hey there @miluoshi / @ItamarGronich - this is fully supported. The only exception thats worth knowing is that `{workspaceRoot}` isn't handled quite as you may imagine, and is only usable at the beginning of an option.
