### ISSUE TITLE
[Web/Vite] to fileReplace or not?

### ISSUE THREAD

**Issue by vicb** [nrwl/nx#14256]
### Current Behavior

When you generate a new web app using vite: `nx generate @nrwl/web:application test --bundler=vite`

It will generate
```
CREATE apps/test/src/environments/environment.prod.ts
CREATE apps/test/src/environments/environment.ts
```

But the configuration does not use those files:
```
// project.json
    "build": {
      "executor": "@nrwl/vite:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "outputPath": "dist/apps/test"
      },
      "configurations": {
        "development": {
          "mode": "development"
        },
        "production": {
          "mode": "production"
        }
      }
    },
```

I was expecting to see something like:
```
      "configurations": {
        "production": {
          "fileReplacements": [
            {
              "replace": "apps/test/src/environments/environment.ts",
              "with": "apps/test/src/environments/environment.prod.ts"
            }
          ]
        }
      }
```

### Expected Behavior

I first thought that the `fileReplacements` should be added the project.json.

But digging into [the code](https://github.com/nrwl/nx/blob/5970246b51c17428b8d9f04123b06f780ac824bc/packages/web/src/generators/application/application.ts#L193-L195) it seems that the intent is to remove the `src/environments/...` files and have the users use `import.meta.env.MODE` instead.

So [this line](https://github.com/nrwl/nx/blob/5970246b51c17428b8d9f04123b06f780ac824bc/packages/web/src/generators/application/application.ts#L195) obviously doesn't work.

### Github Repo

n/a

### Steps to Reproduce

See the description

### Nx Report

```shell
Node : 18.10.0
   OS   : linux x64
   npm  : 8.19.2
   
   nx : 15.4.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.5
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.5
   @nrwl/expo : Not Found
   @nrwl/express : 15.4.5
   @nrwl/jest : 15.4.5
   @nrwl/js : 15.4.5
   @nrwl/linter : 15.4.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.4.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.5
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.4.5
   @nrwl/webpack : 15.4.5
   @nrwl/workspace : 15.4.5
   @nrwl/vite : 15.4.5
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nx-tools/nx-container: 4.0.2
```

### Additional Information

I am not sure how this is best fixed.

One way is to make sure that deleting the `src/environments/*` files work as expected.

On the other hand I see no reason why not to support file replacement with vite out of the box? Users would have a similar way to work whatever the bundler they use and they could still use `import.meta.env.MODE` if they prefer.

_(I have been using file replacement with vite and so far it works great)_

**Comment by mandarini** [comment]
@vicb thanks for reporting this. I want to take a look at this but also discuss this with @jaysoo. I will most probably get to this next week.

**Comment by jaysoo** [comment]
@vicb Thanks for reporting the issue. We definitely want to make sure the `environments` folder is not generated.

The reason we are moving away from `fileReplacement` is that you can achieve the same things with `import.meta.env.MODE` checks or `import.meta.env.VITE_*` checks. We kept the option around to users can migrate from the community plugin more seemlessly.
