### ISSUE TITLE
--targets does not work properly

### ISSUE THREAD

**Issue by nalnir** [nrwl/nx#14263]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[Docs](https://nx.dev/packages/nx/documents/run-many)

### Additional context or description

So I'm trying to run multiple targets on multiple apps. According to docs https://nx.dev/packages/nx/documents/run-many
nx can take --targets as an argument specifying multiple targets I want to run. However on trying the command the error is following: `Missing required argument: target` 

I'm not sure if it's a documentation problem, or nx bug. When runing the same command with flag --target instead of --targets, the message is: Successfully ran target build,serve for 0 projects

I guess it's expecting target name to be `build,serve` rather then treating it as two separate targets.

**Comment by FrozenPandaz** [comment]
Which version are you on? The `targets` flag was added in `15.4.0`

**Comment by nalnir** [comment]
Ah ok, that makes sense. I am on "14.7.4"
