### ISSUE TITLE
React Library with Tailwind - Storybook does not reflect changes on save

### ISSUE THREAD

**Issue by brenden-ef** [nrwl/nx#14271]
### Current Behavior

We are currently working on building a publishable component library within a new integrated repo. The library is built in React with Tailwind and we use Storybook to develop our components. 

We are currently experiencing an issue that occurs after editing classes on a component. After saving the changes, the Storybook webpack build completes and refreshes in the browser, but the changes are not displayed. The changes are only displayed on Chromium-based browsers after manually refreshing the page. On Firefox dev edition, the changes are not displayed after refresh. If the classes weren't in use when Storybook was started, they aren't applied after the refresh.

**Example**  
![The user add classes text-blue-700 font-bold to the component markup, saves the changes, and clicks over to storybook. The build finishes and the changes are not displayed on the refresh. After refreshing the changes are visible. The user repeats this process with another class to show how the original classes are stripped away if the new classes haven't been used yet.](https://user-images.githubusercontent.com/75320861/211816531-ef7db61c-5864-4fd0-b081-f6fb428997b4.gif)

### Expected Behavior

Changes to component CSS and structure are reflected in Storybook after webpack build is complete without manual intervention.

### Github Repo

https://github.com/brenden-ef/tailwind-storybook-repro

### Steps to Reproduce

After running `npm ci` to install dependencies:

1. start storybook `nx storybook repro` and open it in a browser
2. in `packages/repro/src/lib/repro.tsx` add `p-8` class to the root `div` and  change the `h1` classes to `text-red-500 text-8xl font-bold`. Save the file after making these changes
3. note that none of the styles are applied after webpack finishes building the preview
4. refresh the page manually
5. note that now the styles are applied

Reproduced in Firefox Developer Edition (v109.0b9 ), Chrome (v109.0.5414.87), and Sizzy (v70.6) on MacOS and Windows.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : darwin arm64
   npm  : 8.5.5
   
   nx : 15.4.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.5
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.5
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.5
   @nrwl/js : 15.4.5
   @nrwl/linter : 15.4.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.5
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.5
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.4.5
   @nrwl/web : 15.4.5
   @nrwl/webpack : 15.4.5
   @nrwl/workspace : 15.4.5
   @nrwl/vite : 15.4.5
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Additional Information

For reference, here is the Tailwind configuration that was created by the `setup-tailwind` generator  in the repro: 
```ts
const { createGlobPatternsForDependencies } = require('@nrwl/react/tailwind');
const { join } = require('path');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    join(
      __dirname,
      '{src,pages,components}/**/*!(*.stories|*.spec).{ts,tsx,html}'
    ),
    ...createGlobPatternsForDependencies(__dirname),
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
```

We have found a workaround that will help with development by adding _all_ classes to the safelist in the Tailwind config: 
```
  safelist: [
    {
      pattern: /^(.*?)/,
    },
  ],
```

However, this approach will not be suitable for production as we would risk bundling many unused classes and it ignores Tailwind best practices of [letting configured content determine which classes are generated](https://tailwindcss.com/docs/content-configuration#safelisting-classes)

**Comment by mandarini** [comment]
Hi there @brenden-ef ! Thank you for filing an issue. This sounds like an issue with Storybook and the Storybook server itself. Do you mind creating an issue on their repo, linking this issue, and mentioning me as well, just so that I see what the Storybook team replies?

**Comment by brenden-ef** [comment]
@mandarini Sure thing!
