### ISSUE TITLE
After upgrade to 15.4.5 peerDependancies are no longer added to lib package.jsons (@nrwl/js:tsc)

### ISSUE THREAD

**Issue by SuPuL** [nrwl/nx#14275]
### Current Behavior

Hello,
I upgraded our project to `15.4.5` from `14.x`. I ran all migrations and the internal apps do run without any problems. 

But I recognized that our libs build is missing all peer dependencies from the root. All internal libs are added without a problem. 

### Expected Behavior

All peer dependencies from the root for all libs are included in the created package.json of each lib.

### Steps to Reproduce

1. npm install
2. nx run X:build 

### Nx Report

```shell
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.18.0
   OS   : darwin arm64
   npm  : 8.19.2
   
   nx : 15.4.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.5
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.5
   @nrwl/expo : Not Found
   @nrwl/express : 15.4.5
   @nrwl/jest : 15.4.5
   @nrwl/js : 15.4.5
   @nrwl/linter : 15.4.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.4.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.5
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.4.5
   @nrwl/webpack : 15.4.5
   @nrwl/workspace : 15.4.5
   @nrwl/vite : 15.4.5
   typescript : 4.9.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
no logs
```

### Additional Information

After some hours of debugging, I narrowed the problem down to the `package.lock` parsing.

While building the dependencys graph the missing packages are not found because not all have a version in the runtime object. They only have a property called `actualVersion`. The source of this lies in the npm.ts resolving [here](https://github.com/nrwl/nx/blob/b4dbdf60b5a080ba9b0c4f4a5fee8d44a60e86a0/packages/nx/src/lock-file/npm.ts#L163) and [here](https://github.com/nrwl/nx/blob/b4dbdf60b5a080ba9b0c4f4a5fee8d44a60e86a0/packages/nx/src/lock-file/npm.ts#L206).

We have a lot of dependencies like the following:

```
{
  version: "3.7.0",
  license: "MIT",
  dependencies: {
    ...
  },
  peerDependencies: {
    ...
  },
  peerDependenciesMeta: {
    ...
  },
}
```

The problem is that they have a `version` but no `integrity` and `resolved` property. So the used version is `undefined`. And the metadata stored in the graph is:

```
{
    actualVersion: "3.7.0",
    version: undefined,
}
```

And the `undefined` version is used while building to write the `package.json` for the libs. As the JSON serializer ignores these undefined the peer dependencies are missing.

**Comment by FrozenPandaz** [comment]
@meeroslav can you take a look at this one please?

**Comment by sushruth** [comment]
This may be related to #14106

**Comment by SuPuL** [comment]
Hey @meeroslav,
we have some private packages on github. So we use `https://npm.pkg.github.com` in our `.npmrc` to access them. All others not private should be delegated by github.

The packages that have no version are pretty common ones. They only have a hash set. 

Maybe I can find some more time soon to create a very small example repository.

greets

**Comment by meeroslav** [comment]
Can you copy a body from one of those packages from your package-lock.json. Something like:

```
    "node_modules/react": {
      "version": "18.2.0",
      "resolved": "https://registry.npmjs.org/react/-/react-18.2.0.tgz",
      "integrity": "sha512-/3IjMdb2L9QbBdWiW5e3P2/npwMBaU9mHCSCUzNln0ZCYbcfTsGbTJrU/kGemdH2IWmB2ioZ+zkxtmq6g09fGQ==",
      "dependencies": {
        "loose-envify": "^1.1.0"
      },
      "engines": {
        "node": ">=0.10.0"
      }
    },
```

Please note that we missing versions for standard packages might mean your npm installation is off. We had this issue with one of our clients in the past.

**Comment by SuPuL** [comment]
Hi @meeroslav,
sure. There are plenty and some are ok. E.g.:

```
...
,
  "node_modules/snake-case": {
    "version": "3.0.4",
    "license": "MIT",
    "dependencies": {
      "dot-case": "^3.0.4",
      "tslib": "^2.0.3"
    }
  },
  "node_modules/sockjs": {
    "version": "0.3.24",
    "resolved": "https://registry.npmjs.org/sockjs/-/sockjs-0.3.24.tgz",
    "integrity": "sha512-GJgLTZ7vYb/JtPSSZ10hsOYIvEYsjbNU+zPdIHcUaWVNUEPivzxku31865sSSud0Da0W4lEeOPlmw93zLQchuQ==",
    "dev": true,
    "dependencies": {
      "faye-websocket": "^0.11.3",
      "uuid": "^8.3.2",
      "websocket-driver": "^0.7.4"
    }
  },
...
```

The first is broken and the second seems to be ok. I already deleted the lock multiple times nd recreated it.

**Comment by meeroslav** [comment]
This is, unfortunately an issue with the current implementation. Hopefully, the refactored one will be merged soon.

**Comment by sushruth** [comment]
@meeroslav cant wait for it to merge!

**Comment by SuPuL** [comment]
Awesome. 👍

**Comment by ianldgs** [comment]
@meeroslav could you link the PR with the fix so we can subscribe to it? Any workarounds?

**Comment by meeroslav** [comment]
Sure, this is the PR - https://github.com/nrwl/nx/pull/13864

**Comment by meeroslav** [comment]
With new functionality, this should no longer be an issue, since we only check `resolved` when version is missing and the `integrity` is ignored altogether now.
