### ISSUE TITLE
React Native 0.70.6 IOS : failed to load configuration of your project 

### ISSUE THREAD

**Issue by affansk** [nrwl/nx#14294]
### Current Behavior

After upgrading react native version to 0.70.6 i am getting failed to load configuration of your project

### Expected Behavior

Successfull build

### Steps to Reproduce

1. upgrade react native
2. run the app in ios
3. check the error
4. failed to load configuration of your project 

### Nx Report

```shell
Ios failed to load configuration of your project
```

**Comment by skoob13** [comment]
I had the similar problem when one of NPM packages in package.json of the RN project was not in the root package.json. You could get more information logging the error on [this line](https://github.com/react-native-community/cli/blob/be3cb6a9fce4eaecfa62179221edf7e4201c89cc/packages/cli/src/index.ts#L162).

**Comment by affansk** [comment]
@skoob13 this happens to me when i upgrade to 70 version. no problem below that version
