### ISSUE TITLE
`affected` scripts do not work with Bazel workspaces

### ISSUE THREAD

**Issue by rolaveric** [nrwl/nx#1432]
## Expected Behavior

Running `nx affected:apps` on a workspace converted to use Bazel should return the same results as before the conversion.
i.e. running `nx affected:apps --uncommitted` with an uncommitted change in a library should return a list of apps that depend, directly or indirectly, on that library.

## Current Behavior

`nx affected:apps` returns nothing, as though there were no changes at all, or the changes were no consequence to the application code.

### Steps to Reproduce

1. Setup nx repo with 2 apps and a library:
```
npx --ignore-existing create-nx-workspace myworkspace
cd myworkspace
ng g @nrwl/angular:application first
ng g @nrwl/angular:application second
ng g @nrwl/angular:library common
```
2. Import the library from both applications, using nx format: `@myworkspace/common`
3. Commit changes (so `--uncommitted` test will work)
4. Make a change in the common library (eg. Add comment)
5. Run `npm run affected:apps` - Output should be `first second`
6. Change `tsconfig.json` so `paths` matches bazel format: `"myworkspace/*": ["./*"]`
7. Change import paths to use bazel format: `myworkspace/libs/common/src`
8. Commit changes
9. Make a change in the common library (eg. Add comment)
10. Run `npm run affected:apps` - Output should be `first second`, but comes out empty

This repo replicates these steps:
https://github.com/rolaveric/nx-affected-with-bazel

### Context

The current standard for handling typescript with Bazel currently doesn't support custom `paths` configuration.
Instead it provides a single mapping to the root of the workspace, using the name declared in the WORKSPACE file - which cannot include at (@) or dash (-) symbols.
https://github.com/bazelbuild/rules_nodejs/blob/master/packages/typescript/docs/install.md#writing-typescript-code-for-bazel

This conflicts with nx's standard which requires that imports to libraries use an at (@) prefixed name, as per npm group convention. Unfortunately this standard is codified in the `DepsCalculator` class used by the affected scripts.

*Doesn't Bazel effectively make "affected" redundant though?*

Yes, if fully implemented.
But this doesn't help with "gradual adoption" of Bazel.

For a non-trivial codebase, the best strategy for converting to Bazel is to start from the leaf most libraries. The dependencies required in `BUILD.bazel` is smaller to begin with, and you only need to go as far as getting tests running under bazel.
Once you move beyond those outer-most leaf libraries, you're forced to write imports for nx or Bazel - you can't do both.

**Comment by rolaveric** [comment]
Solution wise, I've found I can fix my scenario by altering the `addDepIfNeeded()` method in `DepsCalculator`:
https://github.com/nrwl/nx/blob/master/packages/workspace/src/command-line/deps-calculator.ts#L329

The two main things I do is:
1. Use `project.root` with trailing slashes normalised.
2. Drop the at ("@") prefix
From there I can just alter the `npmScope` in `nx.json` to match the name from my `WORKSPACE` file.
To keep it backwards compatible, and forgo requiring additional configuration switches, I can chain my tests onto the end of line 333, like so:

```
const normalizedRoot = normalizedProjectRoot(a);
const projectRoot = a.root.replace(/\/$/, '');
return (
  expr === `@${this.npmScope}/${normalizedRoot}` ||
  expr.startsWith(`@${this.npmScope}/${normalizedRoot}#`) ||
  expr.startsWith(`@${this.npmScope}/${normalizedRoot}/`) ||
  expr === `${this.npmScope}/${projectRoot}` ||
  expr.startsWith(`${this.npmScope}/${projectRoot}#`) ||
  expr.startsWith(`${this.npmScope}/${projectRoot}/`)
);
```

What I'm unsure of is the greater ramifications of a change like this.
Is there anything else in the nx toolset that would be broken by a change like this?

**Comment by vsavkin** [comment]
Sorry about it. The bazel support was experimental. We are hoping to make it properly supported by Nx 9, which should be released in Oct/Nov 2019.

**Comment by vsavkin** [comment]
I'm going to close this. The new bazel support is in the works. We will post updates as we keep making progress.
