### ISSUE TITLE
Doc bug in projectConfiguration > implicitDependencies > glob pattern example

### ISSUE THREAD

**Issue by computnik** [nrwl/nx#14332]
### Documentation issue
- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?
Link - https://nx.dev/reference/project-configuration#implicitdependencies 
Section - `An implicit dependency could also be a glob pattern:`

### Additional context or description
The code comment looks wrong, and it seems it was copied over from the previous section. 

### Suggestion
```diff
-  "implicitDependencies": ["shop-*"] # regardless of what Nx thinks, "mylib" doesn't depend on "anotherlib"
+  "implicitDependencies": ["shop-*"] # regardless of what Nx thinks, "mylib" depends on all packages matching "shop-*" glob pattern
```

**Comment by FrozenPandaz** [comment]
Yes, that is a mistake. Would you be interested in opening a PR?

**Comment by bcabanes** [comment]
It seems to have been updated and fixed by https://github.com/nrwl/nx/pull/14539. Closing!
