### ISSUE TITLE
@nrwl/workspace - library creates TSLint config path with double slash

### ISSUE THREAD

**Issue by peterblazejewicz** [nrwl/nx#1435]
This is minor problem. Running `@nrwl/workspace - library` schema generates a TSLint path with double slashes. 

Template:
https://github.com/nrwl/nx/blob/master/packages/workspace/src/schematics/library/files/lib/tslint.json#L2

# Prerequisites
n/a
## Expected Behavior

The path within library `tslint.json` should not contain double slash

```json
{
  "extends": "../../tslint.json",
  "rules": []
}
```

## Current Behavior

The path contains double slash:

```json
{
  "extends": "../..//tslint.json",
  "rules": []
}
```

## Failure Information (for bugs)

n/a, minor issue

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. run `@nrwl/workspace - library` to get TS only library
2. open library `tslint.json` file

### Context

- version of Nx used:  8.1.0
- version of Angular CLI used: 8.0.1
- `angular.json` configuration: n/a
- version of Angular DevKit used: n/a
- 3rd-party libraries and their versions: n/a
- and most importantly - a use-case that fails: n/a

### Failure Logs

n/a

## Other

Mac OS, *nix based file system

**Comment by vsavkin** [comment]
The fix has been merged here: https://github.com/nrwl/nx/pull/1451

Thanks for submitting the issue.
