### ISSUE TITLE
nx run-many --output-style=stream-without-prefix does not output task logs to stdout

### ISSUE THREAD

**Issue by jeffhertzler** [nrwl/nx#14350]
### Current Behavior

nx run-many --output-style=stream-without-prefix does not output task logs to stdout

### Expected Behavior

nx run-many --output-style=stream-without-prefix does output task logs to stdout

### Github Repo

https://github.com/jeffhertzler/nx-parallel-output-bug

### Steps to Reproduce

1. `npm start` or `npm run start-with-stream-without-prefix`

if you run `npm start-with-stream` it will correctly output logs

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.12.1
   OS   : linux x64
   npm  : 8.19.2

   nx : 15.5.0
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : Not Found
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : Not Found
   @nrwl/vite : Not Found
   typescript : Not Found
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by FrozenPandaz** [comment]
The correct flag is the following. Then, logs should show up.

```terminal
nx run-many --output-style=stream-without-prefixes
```

**Comment by jeffhertzler** [comment]
> The correct flag is the following. Then, logs should show up.
> 
> ```
> nx run-many --output-style=stream-without-prefixes
> ```

whoops. yes that works. what is the default supposed to be though? if no option is provided then there will be no output whatsoever. is that the intent?
