### ISSUE TITLE
Support Cypress Component Testing with Next.js

### ISSUE THREAD

**Issue by dallonf** [nrwl/nx#14363]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Cypress Component Testing seems like it would be a very useful workflow, but unfortunately Nx doesn't seem to support it for Next.js projects.

Running a command like: 
```
nx g @nrwl/react:cypress-component-configuration --project=my-project --build-target=web:build
```
_(by the way, the [official documentation](https://nx.dev/packages/react/generators/cypress-component-configuration) states to run `react:cypress-component-project` instead of `-configuration`, which is incorrect)_

results in this errors:

```
 ERROR  The provided build target, web:build, uses the '@nrwl/next:build' executor.
But only the follow executors are allowed
- @nrwl/webpack:webpack
```

## Motivation

I was pretty excited to use Cypress Component Testing to have a visual debugging environment for UI component tests, and Nx seemed to support it, but I was frustrated to discover the support was only for vanilla React projects, not Next.js.

## Suggested Implementation

Since Nx already supports Cypress Component Testing and Cypress Component already [supports Next.js](https://docs.cypress.io/guides/component-testing/overview#Supported-Frameworks), it seems like there's only a small missing piece required to allow it to use a Next build executor instead of Webpack.

## Alternate Implementations

If it's already possible to do this and I just haven't figured it out, extending the documentation to explain what to do for this use case would be extremely helpful.

**Comment by barbados-clemens** [comment]
this is on the roadmap to start working on in the coming months

**Comment by shawngustaw** [comment]
+1 this is something we'd love to have as well. Anything I can do to help move this along please lmk :)

**Comment by lumiiartan** [comment]
Does anyone know if Vue will be supported soon for Cypress component testing in Nx, considering that Nx currently supports Angular and React?
