### ISSUE TITLE
nx.dev website not rendering correctly

### ISSUE THREAD

**Issue by pvds** [nrwl/nx#14368]
### Current Behavior

The nx.dev website is not rendering correctly.
It seems like some tailwind classes are not provided resulting in unconstrained svg files.

The whole website seems to be affected but just for visual reference (tested on chrome 108.0.5359.124 on a mac).

**Homepage** 
<img width="1718" alt="Screenshot 2023-01-14 at 18 35 32" src="https://user-images.githubusercontent.com/1928947/212487273-a551e034-4d75-49b9-af92-3ec77f228357.png">

**Getting started page**
<img width="1728" alt="Screenshot 2023-01-14 at 18 39 34" src="https://user-images.githubusercontent.com/1928947/212487368-138744b8-644a-48bf-9ae8-bf08110647a9.png">

### Expected Behavior

Correctly rendering nx.dev site

### Github Repo

[https://github.com/nrwl/nx/tree/master/nx-dev/nx-dev](https://github.com/nrwl/nx/tree/master/nx-dev/nx-dev)

### Steps to Reproduce

1. Visit [https://nx.dev](https://nx.dev)

### Nx Report

_Not relevant

### Additional Information

The are some cors error and a failed fetch (partytown script)
<img width="540" alt="Screenshot 2023-01-14 at 18 42 37" src="https://user-images.githubusercontent.com/1928947/212487460-69933629-30d0-467e-861b-8cbae77546a0.png">

**Comment by pvds** [comment]
It seems only specific tailwind utility classes are missing.
In the tailwind css file I am missing a lot of `h-*` and `w-*` classes which are used in the html.

Possibly something to do with tailwind purging or configuration?

**Comment by felipe2g** [comment]
Same here, tested on safari and mozilla. MacOS.

**Comment by bcabanes** [comment]
Hey 👋 
Thank you for reaching out!
The website has been restored and should be operational for all.

**Comment by AgentEnder** [comment]
Noting that this was an infrastructure issue, no code changes needed (or config)

**Comment by pvds** [comment]
@AgentEnder @bcabanes seems like the infrastructure issue is back.

**Comment by bcabanes** [comment]
@pvds Thank you! 

We restored the website and will investigate further what is happening.
