### ISSUE TITLE
Excluding dependencies using the implicitDependency array not working

### ISSUE THREAD

**Issue by NiclasHaderer** [nrwl/nx#14377]
### Current Behavior

In version 15.4.2 you could exclude dependencies using a !.  
In version 15.5.1 this is no longer working 

```json
{
  "root": "/libs/mylib",
  "implicitDependencies": ["!anotherlib"] // regardless of what Nx thinks, "mylib" doesn't depend on "anotherlib"
}
```
but currently seems to be broken - perhaps related to -
https://github.com/nrwl/nx/blob/a806feed0eb8572e51262de9b08910bedb21f07c/packages/nx/src/project-graph/build-nodes/workspace-projects.ts#L157-L172
 as suggested in https://github.com/nrwl/nx/issues/10290.

### Expected Behavior

The library is excluded

### Steps to Reproduce

1. Use the dependency array to exclude another nx library and see that it is not working in 15.5.1

### Nx Report

```shell
Node : 19.0.0
   OS   : linux x64
   yarn : 1.22.19
   
   nx : 15.5.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.5.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.1
   @nrwl/js : 15.5.1
   @nrwl/linter : 15.5.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.5.1
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.5.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.5.1
   @nrwl/webpack : 15.5.1
   @nrwl/workspace : 15.5.1
   @nrwl/vite : 15.5.1
   typescript : 4.9.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @jscutlery/semver: 2.29.3
```

**Comment by asilvadesigns** [comment]
I'm encountering this issue as well.

**Comment by alvaro450** [comment]
We are experiencing this issue as well. Downgrading to 15.4.2 keeps the same behavior as before (as specified in the description). 

NX team, can you please clarify if this will be expected behavior going forward, or if this is a legitimate regression that will be addressed at some point in the future?

Thank you in advance!

**Comment by alvaro450** [comment]
@FrozenPandaz can you please comment on this issue?

**Comment by vlwkaos** [comment]
Having the same issue here.

**Comment by asilvadesigns** [comment]
👋

**Comment by NiclasHaderer** [comment]
I just updated to the latest nx version and is seems to work again, at least for me. If it is also working for you I'd close the issue

**Comment by alvaro450** [comment]
It is working for me as well in the latest v15.x version!
