### ISSUE TITLE
how to override Nx default config template files

### ISSUE THREAD

**Issue by mathpaquette** [nrwl/nx#1437]
## Expected Behavior
I'd like to override the default template files provided by Nx schematics. 

As per example, when creating new library, I need to provide customized properties in karma.conf.js so this is why I'm asking if I can provide my own template file to override karma.conf.js__tmpl__ file, which is the default one.

## Current Behavior
Seems to be impossible in version 7.3+

**Comment by mathpaquette** [comment]
looks like possible by extending the existing collection of schematics with the extends property but I would have think of something more configurable. What do you guys think?

**Comment by FrozenPandaz** [comment]
Yes, we recommend you look at Workspace Schematics: https://auth0.com/blog/create-custom-schematics-with-nx/.

With this you can define your own set of schematics. Which can help your organization enforce it's own best practices. Unfortunately we do not have the best documentation on it but I hope to provide some soon.
