### ISSUE TITLE
React Export SVG like ReacComponent not working in version 15.5.1

### ISSUE THREAD

**Issue by dmytro-podolianskyi-ew** [nrwl/nx#14383]
### Current Behavior

I want to put SVG Icon as ReactComponent

import { ReactComponent as CloseIcon } from "./icons/close.svg";

It's working properly in version 15.4.5.

In version 15.5.1, I got an error:

export 'ReactComponent' (imported as 'CloseIcon') was not found in './icons/close.svg' (possible exports: default)

### Expected Behavior

Import svg as ReactComponent without any error or warning

### Steps to Reproduce

1.
Put any SVG icon like ReactComponent

import { ReactComponent as CloseIcon } from "./icons/close.svg";

and try to run dev server or build mode

### Nx Report

```shell
NX   Report complete - copy this into the issue template

   Node : 18.12.1
   OS   : win32 x64
   npm  : 9.2.0
   
   nx : 15.5.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.5.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.1
   @nrwl/js : 15.5.1
   @nrwl/linter : 15.5.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.5.1
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.5.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.5.1
   @nrwl/webpack : 15.5.1
   @nrwl/workspace : 15.5.1
   @nrwl/vite : 15.5.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by ms-tng** [comment]
I'm running into the same problem. My analysis so far:
I found that it's because the `@svgr/webpack` loader isn't applied by default anymore when using React. It looks like you need to use `composePlugins` as demonstrated [here](https://github.com/nrwl/nx/blob/master/packages/web/src/generators/application/files/app-webpack/webpack.config.js__tmpl__) and then add the `withReact()` plugin of `@nrwl/react`. This will add an `@svgr/webpack` rule for SVGs. Since this rule needs to come before the rule using `file-loader` added by  `withWeb()`, you need to add `withReact()` before `withWeb()`. However, Nx currently always applies `withNx()` and `withWeb()` in the beginning for compatibility reasons, see [here](https://github.com/nrwl/nx/blob/e4bf7065a99756cdc478899b0b6bb0424bbfe7c9/packages/webpack/src/executors/webpack/lib/get-webpack-config.ts#L23), so the `@svgr/webpack` rule ends up after `file-loader` in any case. My current workaround is to find the `@svgr/webpack` rule and move it to the front in a custom Webpack config.

**Comment by dolayas** [comment]
> I'm running into the same problem. My analysis so far: I found that it's because the `@svgr/webpack` loader isn't applied by default anymore when using React. It looks like you need to use `composePlugins` as demonstrated [here](https://github.com/nrwl/nx/blob/master/packages/web/src/generators/application/files/app-webpack/webpack.config.js__tmpl__) and then add the `withReact()` plugin of `@nrwl/react`. This will add an `@svgr/webpack` rule for SVGs. Since this rule needs to come before the rule using `file-loader` added by `withWeb()`, you need to add `withReact()` before `withWeb()`. However, Nx currently always applies `withNx()` and `withWeb()` in the beginning for compatibility reasons, see [here](https://github.com/nrwl/nx/blob/e4bf7065a99756cdc478899b0b6bb0424bbfe7c9/packages/webpack/src/executors/webpack/lib/get-webpack-config.ts#L23), so the `@svgr/webpack` rule ends up after `file-loader` in any case. My current workaround is to find the `@svgr/webpack` rule and move it to the front in a custom Webpack config.

Can you show a solution to fix that? I have the same problem after migrating.

**Comment by ms-tng** [comment]
@dolayas Something like this should do the trick:
```
const { composePlugins, withNx, withWeb } = require('@nrwl/webpack');
const { withReact } = require('@nrwl/react');

const moveRuleToFront = (config, loaderPattern) => {
  const { rule, index } = config.module.rules
    .map((rule, index) => ({ rule, index }))
    .find(({ rule }) => rule.use && rule.use.some(entry => entry.loader.includes(loaderPattern)));
  config.module.rules.splice(index, 1);
  config.module.rules.unshift(rule);
};

// This `composePlugins` approach is not needed right now, but I guess it will be needed in Nx 16
// Then it will be important that `withReact()` comes before `withWeb()`
module.exports = composePlugins(withNx(), withReact(), withWeb(), config => {
  moveRuleToFront(config, '@svgr');
  return config;
});
```
Save this as `webpack.config.js` and configure it as the `webpackConfig` for your `@nrwl/webpack:webpack` executor.
It's a bit hacky, so you may consider waiting for a proper bugfix.

**Comment by jamieathans** [comment]
I think I'm seeing a similar issue as described here - https://github.com/nrwl/nx/issues/14378.

Difference being that I'm using SVG directly in an image tag.

```
import React from 'react';
import logo from './logo.svg';

const Header = () => <img src={logo} alt="Logo" />;

export default Header;
```

**Comment by merobal** [comment]
It works well with v15.4.5 and it's broken at 15.4.6 and above (still with 15.5.3).

**Comment by jaysoo** [comment]
Thanks @danr-za for a fix here https://github.com/nrwl/nx/pull/14695

Adding e2e to guard against this in the future https://github.com/nrwl/nx/pull/14707

**Comment by francisco-gs-colpal** [comment]
I am with 15.6.3 and this is still an issue.

**Comment by merobal** [comment]
It seems the fixes are not released yet, I'm waiting for the next version too

**Comment by francisco-gs-colpal** [comment]
Does someone knows the release schedule?

**Comment by overbit** [comment]
@FrozenPandaz do we know when the next release will happen? I can see this fix in the beta version

**Comment by francisco-gs-colpal** [comment]
I update to 15.7.0 storybook works my app stopped working :(
