### ISSUE TITLE
Allow adding root level scripts as dependencies to projects tasks `dependsOn`

### ISSUE THREAD

**Issue by ItamarGronich** [nrwl/nx#14386]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Allow adding root-level scripts in project tasks `dependsOn`.
For example, I have a nx root-level script that copies that assets folder to the dist.
And all other projects depend on it, i want to be able to specify that `build` task for every project depends on the root level copy assets script.
something like so:
`root level package.json`
```json
{
  "scripts": {
    "copy-assets": "nx exec -- mkdir -p static/dist/assets && cp -R assets static/dist/assets"
  },
  "nx": {
    "targets": {
      "copy-assets": {
        "inputs": ["{workspaceRoot}/assets/**/*"],
        "outputs": ["{workspaceRoot}/static/dist/assets"]
      }
    }
  },
}
```
`nx.json`
```json
"targetDefaults": {
    "build": {
      "inputs": ["production", "^production"],
      "dependsOn": ["^build", "^copy-assets"]
    }
  },
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": [
          "copy-assets",
          "build",
          "lint",
          "test"
        ]
      }
    }
  }
```

## Motivation

It's useful to have the ability to also depend on root level scripts.

## Suggested Implementation

Not sure

## Alternate Implementations

Not sure

**Comment by AdditionAddict** [comment]
Adding a root level `project.json` allows for doing this for things like codegen / task pre and build step of any library

see https://twitter.com/zackderose/status/1648961171733766146?s=20

**Comment by AgentEnder** [comment]
This is fixed 🎉.
