### ISSUE TITLE
@nrwl/js library generator use rollup bundler build error

### ISSUE THREAD

**Issue by cbl980226** [nrwl/nx#14393]
### Current Behavior

```bash
npx create-nx-workspace@latest --pm=pnpm --preset=ts
pnpm nx g lib rollup-lib --bundler=rollup --buildable
pnpm nx build rollup-lib
```

console error: NX   Required property 'project' is missing

### Expected Behavior

executor @nrwl/rollup:rollup options has default project property, or like webpack executor, this property is not required.

### Steps to Reproduce

1. npx create-nx-workspace@latest --pm=pnpm --preset=ts
2. pnpm nx g lib rollup-lib --bundler=rollup --buildable
3. pnpm nx build rollup-lib

### Nx Report

```shell
Node : 18.13.0
   OS   : win32 x64
   pnpm : 7.25.0

   nx : 15.5.1
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.1
   @nrwl/js : 15.5.1
   @nrwl/linter : 15.5.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.5.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.5.1
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

> nx run rollup-lib:build

 >  NX   Required property 'project' is missing

 ———————————————————————————————————————————————————————————————————————————————————————
——————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for project rollup-lib (333ms)

    ×    1/1 failed
    √    0/1 succeeded [0 read from cache]

**Comment by cbl980226** [comment]
## About package.json

rollup after the build is completed, then update package.  json(module, type, main), the module or main not use outputFileName, if set @nrwl/rollup:rollup options.outputFileName

project.json build target options
```json
"build": {
      "executor": "@nrwl/rollup:rollup",
      "outputs": ["{options.outputPath}"],
      "options": {
        "project": "packages/rollup-lib/package.json",
        "outputPath": "dist/packages/rollup-lib",
        "outputFileName": "rollup-lib.js",
        "main": "packages/rollup-lib/src/index.ts",
        "tsConfig": "packages/rollup-lib/tsconfig.lib.json",
        "rollupConfig": "packages/rollup-lib/rollup.config.js",
        "format": ["esm", "cjs"],
        "assets": []
      }
    }
```

![image](https://user-images.githubusercontent.com/55084702/212721831-cb8f489a-02d1-4318-8420-93ab168abad9.png)

package.json
```json
{
  "name": "@cbl/rollup-lib",
  "version": "0.0.1",
  "type": "module",
  "module": "./index.js",
  "main": "./index.cjs",
  "types": "./src\\index.d.ts"
}
```

### Expected Behavior

package.json
```json
{
  "name": "@cbl/rollup-lib",
  "version": "0.0.1",
  "type": "module",
  "module": "./rollup-lib.js",
  "main": "./rollup-lib.cjs",
  "types": "./src\\rollup-lib.d.ts"
}
```

**Comment by ndcunningham** [comment]
Should be fixed with: https://github.com/nrwl/nx/pull/15179
