### ISSUE TITLE
Does nx have a feature to build a typescript package like tsup?

### ISSUE THREAD

**Issue by jon9090** [nrwl/nx#14398]
Does nx have a feature to build a typescript package like [tsup](https://tsup.egoist.dev/#bundle-formats) does? 

`tsup` takes the code and creates a library with a format like `esm`, `cjs`, `iife`, and more.

See here the explanation: https://www.youtube.com/watch?v=eh89VE3Mk5g.

Right now when I create `@nrwl/js:lib` it output only `commonjs` format. and I want `esm` and `commonjs` and so on formats.

Does nx support that?

**Comment by FrozenPandaz** [comment]
[The `format` option on the `@nrwl/js:rollup` executor](https://nx.dev/packages/rollup/executors/rollup#format) is an array and can be set to `['esm', 'commonjs']` which should do what you want.
