### ISSUE TITLE
Error Creating new App

### ISSUE THREAD

**Issue by miguelramos** [nrwl/nx#144]
Just got a fresh install and when running command to create new app got this error:

![image](https://user-images.githubusercontent.com/495720/33690698-b1bf64e8-dadc-11e7-82db-44da38abe6b7.png)

Current project structure:

![image](https://user-images.githubusercontent.com/495720/33690855-6042241a-dadd-11e7-9f30-d88256251fc1.png)

Installation i have done the global step with  yarn.

Creation of lib works like a charm.

**Comment by mtabaj** [comment]
I had the same error.

**Comment by jschwarty** [comment]
That error comes from schematics when one of the files already exists in the filesystem. Maybe your editor wasn't refreshing to show it but it was actually there if you browse the filesystem? You can use the `--force` option flag to override any existing matching files (add the `--dry-run` flag to confirm what it will do without doing it).
```
ng g app platform --routing --force --dry-run
```

**Comment by vsavkin** [comment]
Closing this issue. If it is still present, please reopen it with a repro.
