### ISSUE TITLE
Splitting libraries by app name, currently all mixed :-( ?

### ISSUE THREAD

**Issue by appsolutegeek** [nrwl/nx#1440]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Architecture Question - Libraries

I am looking for a bit of guidance with regards to splitting out libraries but i want to do it in a way that follows the patterns of NX or at least not breaking anything that it stands for :-)

I have 2 x Apps...   Lets say for argument sake, 

1. UI (angular) 
2. SERVER (nestjs)

```
/apps
   /ui
   /server
```

And my libs are here

```
/libs
   /lib1 (belongs to angular)
   /lib2 . (belongs to nestjs)
   /lib3 . (belongs to nestjs)
```

As you can see there are a number of libraries, some for angular and some for nestjs.

What's the best way of splitting these out, I was thinking

```
 /libs
  /ui/lib1
  /server/lib2
  /server/lib3
```
and then mapping the TSCONFIG config paths to use 2 x workspace names i.e.

```
@ui-ws/
@server-ws/
```

using 2 x different workspace names is ok ?

Can anyone comment or have a better idea on the above.

The fact of the matter is that I have a number of libraries now and they are mixed between angular and nestjs and its very confusing tracking what is what.

I just want to ensure I follow the correct NX patterns.

Any ideas ?

**Comment by FrozenPandaz** [comment]
That's a wonderful idea 👍

Also read this book to find out more best practices: https://connect.nrwl.io/app/books/enterprise-angular-monorepo-patterns
