### ISSUE TITLE
New react-native app displays an error (Deprecated transform-react-jsx-self Babel plugin)

### ISSUE THREAD

**Issue by math15t6** [nrwl/nx#14407]
### Current Behavior

On a clean, newly installed Mac, I get this error message: Duplicate __self prop found. You are most likely using the deprecated transform-react-jsx-self Babel plugin.

I've also tested with react-native-cli and that runs fine, but it might just be my setup / config. But all I've done is setup my Mac, followed the react-native-cli environment setup guide. 

### Expected Behavior

Run the app without the red error screen

### Steps to Reproduce

1. npx create-nx-workspace --allPrompts true
2. I choose pnpm,  integrated monorepo and the react-native template.
3. Run the app on either your device or an emulator, I used the IOS emulator and an android device

### Nx Report

```shell
Node : 16.19.0
   OS   : darwin arm64
   pnpm : 7.25.0
   
   nx : 15.5.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.5.1
   @nrwl/detox : 15.5.1
   @nrwl/devkit : 15.5.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.1
   @nrwl/js : 15.5.1
   @nrwl/linter : 15.5.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.5.1
   @nrwl/react-native : 15.5.1
   @nrwl/rollup : 15.5.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.5.1
   @nrwl/webpack : 15.5.1
   @nrwl/workspace : 15.5.1
   @nrwl/vite : 15.5.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
src/app/App.tsx: /Users/[MyUserName]/Documents/testapp/apps/mobile/src/app/App.tsx: Duplicate __self prop found. You are most likely using the deprecated transform-react-jsx-self Babel plugin. Both __source and __self are automatically set when using the automatic runtime. Please remove transform-react-jsx-source and transform-react-jsx-self from your Babel config.
  19 |   return (
  20 |     <>
> 21 |       <StatusBar barStyle="dark-content" />
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  22 |       <SafeAreaView>
  23 |         <ScrollView
  24 |           ref={(ref) => {

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_drain
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
0x0
```

**Comment by wasurocks** [comment]
Facing the same bug here as well.

**Comment by whalemare** [comment]
Same after upgrading from `14.7.4` -> `15.5.2`

**Comment by math15t6** [comment]
@whalemare & @wasurocks 

I might have found a solution, but test it yourself as i have no idea if somethings else could break. I went to the babel github and read the changelog where I saw some fixed issues relating to the "transform-react-jsx" problem.

So my solution was simply to update "@babel/runtime". 

[package.json]
From:
`"@babel/runtime": "7.20.1",`

To:
`"@babel/runtime": "^7.20.13",`

**Comment by josephfh** [comment]
I faced the same issue, and **can confirm that it is related to choosing pnpm as a package manager** when running npx create-nx-workspace

## These steps work

npx create-nx-workspace --allPrompts true
Choose **npm**, integrated monorepo and the react-native template.

**Comment by HadiModarres** [comment]
I use yarn and still have this problem

**Comment by apostopher** [comment]
I changed the `babel.config.json` inside `apps/[appName]` folder to this:

```
{
  "presets": [["module:metro-react-native-babel-preset", { "useTransformReactJSXExperimental": true }]]
}
```

That fixed the issue. my deps versions are:

```
// devDependencies

"@babel/core": "7.21.0",
"@babel/preset-react": "7.18.6",
"@babel/preset-typescript": "7.21.0",
"@babel/runtime": "7.21.0",
"metro": "0.74.1",
"metro-babel-register": "0.74.1",
"metro-config": "0.74.1",
"metro-react-native-babel-preset": "0.74.1",
"metro-react-native-babel-transformer": "0.74.1",
"metro-resolver": "0.74.1",

// dependencies

"react": "18.2.0",
"react-native": "0.71.3",
```

**Comment by curthipster** [comment]
I'm running into this issue on an existing project using npm package manager. I had a very similar error months ago and tried the same babel config workaround, but it caused other issues in jest configuration. 

Ultimately a change that @xiongemi made in `nx` fixed it. I believe it was caused by mismatched versions of metro packages and react-native. I have combed through the changes today and I cannot find the culprit.

More here: https://github.com/nrwl/nx/issues/11939#issuecomment-1309045103

@apostopher are you still using the babel config workaround? Are your jest unit tests passing?

**Comment by apostopher** [comment]
@curthipster yes, the babel config fixed the build for me in the new nx project. i just tested the jest command and its failing for me with

```
node_modules/.pnpm/@react-native+polyfills@2.0.0/node_modules/@react-native/polyfills/error-guard.js:14
    type ErrorHandler = (error: mixed, isFatal: boolean) => void;
         ^^^^^^^^^^^^

    SyntaxError: Unexpected identifier
```

but this is because the `js` file `error-guard.js` contains TS sytax. so i guess thats a separate issue and not related to this one.

**Comment by curthipster** [comment]
@apostopher do the tests pass without that config change? They do for me with a fresh project.

**Comment by xiongemi** [comment]
based on previous comments, seems like this issue is fixed. close this ticket.

**Comment by dasheck0** [comment]
Solution of @apostopher worked for me. Thanks!
