### ISSUE TITLE
Nx Google Pay: Missing annotations With stripe

### ISSUE THREAD

**Issue by affansk** [nrwl/nx#14414]
### Current Behavior

while trying to build with nx getting this googlepay_button_dark.xml: Error: is not annotated 
react native version 0.71.0

### Expected Behavior

the app should built without any issue

### Steps to Reproduce

upgrade to react native 0.71.0 with stripe available in package
2) run nx command
3) user will see similar error **googlepay_button_dark.xml is not annotated as @Input**

### Nx Report

```shell
upgrade to react native 0.71.0 with stripe available in package
2) run nx command
3) user will see similar error **googlepay_button_dark.xml is not annotated as @Input**
```

**Comment by affansk** [comment]
https://github.com/stripe/stripe-react-native/issues/1078

**Comment by affansk** [comment]
@FrozenPandaz  Any Solution you can suggest for this  issue ?

**Comment by Peeeep** [comment]
Posting here for visibility, in case someone stumbles over the same problem:

> I've fixed this issue by using `patch-package` to patch the `@react-native-community/cli-platform-android` package so it loads the dependencies from the root `node_modules` folder. The issue definitely seems to be related to symlinks, which gradle doesn't know how to handle (at least it seems that way from my research). Here's the patch:
> 
> ```
> diff --git a/node_modules/@react-native-community/cli-platform-android/native_modules.gradle b/node_modules/@react-native-community/cli-platform-android/native_modules.gradle
> index 4a63eaf..05b4511 100644
> --- a/node_modules/@react-native-community/cli-platform-android/native_modules.gradle
> +++ b/node_modules/@react-native-community/cli-platform-android/native_modules.gradle
> @@ -469,7 +469,7 @@ class ReactNativeModules {
>          def nameCleansed = name.replaceAll('[~*!\'()]+', '_').replaceAll('^@([\\w-.]+)/', '$1_')
>          reactNativeModuleConfig.put("name", name)
>          reactNativeModuleConfig.put("nameCleansed", nameCleansed)
> -        reactNativeModuleConfig.put("androidSourceDir", androidConfig["sourceDir"])
> +        reactNativeModuleConfig.put("androidSourceDir", androidConfig["sourceDir"].replace('apps/your-app-name/', ""))
>          reactNativeModuleConfig.put("packageInstance", androidConfig["packageInstance"])
>          reactNativeModuleConfig.put("packageImportPath", androidConfig["packageImportPath"])
>          reactNativeModuleConfig.put("libraryName", androidConfig["libraryName"])
> ```

_Originally posted by @retro in https://github.com/stripe/stripe-react-native/issues/1078#issuecomment-1353158856_
