### ISSUE TITLE
Cypress component test not loading stylePreprocessorOptions when run on lib using other app devServerTarget

### ISSUE THREAD

**Issue by lydemann** [nrwl/nx#14416]
### Current Behavior

For Angular app, when running component tests for lib: todo-app-feature which is setting the devServerTarget to app todo-app (apps/todo-app) the scss imports are not working. It's like the stylePreprocessorOptions are not referining to the right path anymore. It works when I run just the todo-app.

https://www.loom.com/share/b24c7fdd78a24aa8b279441e1c95b103
https://github.com/lydemann/Todo-monorepo/tree/component-test

### Expected Behavior

It should load the scss imports using the stylePreprocessorOptions specified in the app.

### Steps to Reproduce

1. Create app with stylePreprocessorOptions to some folder and do an scss import
2. Create lib set up with a component and Cypress component tests using the app as devServerTarget
3. See it won't load scss imports.

### Nx Report

```shell
Node : 16.14.2
   OS   : darwin arm64
   yarn : 1.22.18
   
   nx : 15.5.1
   @nrwl/angular : 15.5.1
   @nrwl/cypress : 15.5.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.1
   @nrwl/js : 15.5.1
   @nrwl/linter : 15.5.1
   @nrwl/nest : 15.5.1
   @nrwl/next : Not Found
   @nrwl/node : 15.5.1
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.5.1
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.5.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.5.1
   @nrwl/webpack : 15.5.1
   @nrwl/workspace : 15.5.1
   @nrwl/vite : 15.5.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @ngrx/effects: 15.0.0
         @ngrx/entity: 15.0.0
         @ngrx/router-store: 15.0.0
         @ngrx/store: 15.0.0
         @ngrx/store-devtools: 15.0.0
         ngx-build-plus: 9.0.6
         @ngneat/spectator: 13.0.0
         @storybook/angular: 6.5.15
         ng-mocks: 14.5.1
```

**Comment by barbados-clemens** [comment]
retry with latest [as mentioned in this comment](https://github.com/nrwl/nx/issues/12987#issuecomment-1402265297), it looks to be fixed in latest versions of nx/ng/cypress. 

Repo of it working. 
https://github.com/barbados-clemens/cy-asset-style-demo

**Comment by mandarini** [comment]
I will be closing this since it seems to have been fixed in the latest version. Feel free to ping me and I will reopen if it persists on the latest version.
