### ISSUE TITLE
[docs] Storybook 7 Plugin version

### ISSUE THREAD

**Issue by andreyantipov** [nrwl/nx#14435]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/packages/storybook/documents/storybook-7-setup

### Additional context or description
its says that its available in nx 15.6.0 but latest version is 15.5.1 (Should be 15.0.6?) or related to @nrwl/storybook package separately?
```
Available on Nx v15.6
This is a new feature available on Nx v15.6.0. If you are using an older version of Nx, please [upgrade](https://nx.dev/packages/nx/documents/migrate).
```

Provide any additional details here as needed.

https://github.com/nrwl/nx/releases/tag/15.5.1

https://www.npmjs.com/package/nx?activeTab=versions
```
latest nx version is 15.5.1 (2023-01-13)
and also 15.5.0-beta.1 is marked as next but older than latest version
```

**Comment by StalkAltan** [comment]
This feature is upcoming and will be released in Nx 15.6.
