### ISSUE TITLE
Allow the {workspaceRoot} token in the middle of target default options

### ISSUE THREAD

**Issue by bcallaghan-et** [nrwl/nx#14436]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Currently, the `{workspaceRoot}` token is allowed in the options of a target default, but only if it appears at the beginning of the option string. Attempting to use the token in any other position results in the following error.
```sh
 >  NX   >  NX  The {workspaceRoot} token is only valid at the beginning of an option. (test)
```
This token or one like it should be allowed at any position within the option string, and it should evaluate to the path containing the nx.json file.

## Motivation

I attempted to set the following target default within my workspace, only to see the error listed above.
```json
"@nx-dotnet/core:test": {
  "options": {
    "logger": "\"junit;LogFilePath={workspaceRoot}/test-results/{projectRoot}\"",
    "noBuild": true
  },
  "dependsOn": ["build"],
  "inputs": ["default", "^production", "{workspaceRoot}/jest.preset.js"],
  "outputs": ["{workspaceRoot}/test-results/{projectRoot}"]
},
```
My goal was to remove similar configuration from the 70+ projects in my workspace, which are all identical, except for the path specified in the `outputs` and `logger` fields. In this example, the executor wraps a third-party CLI, and that tool expects the `logger` path to be relative from the project root. The tool also accepts absolute paths. My current configurations contain a lot of `../../../` relative pathing which is difficult to maintain, especially if a project is moved into a new directory of a different depth.

## Suggested Implementation

The rule requiring that `{workspaceRoot}` is at the start of the string should be removed, and the token should evaluate to the absolute path of the workspace root.

## Alternate Implementations

If changing the behavior of `{workspaceRoot}` is too breaking of a change, then a new token, possibly named `{absoluteWorkspaceRoot}` could be added. This new token should be allowed anywhere within the option string and should evaluate to the absolute path of the workspace root.

A third option is to introduce a new token, possibly named `{workspaceOffset}`. This token should be allowed anywhere within the option string and should evaluate to the relative path from the project root back to the workspace root (likely containing a value similar to `../../..`).

**Comment by Tungsten78** [comment]
I'm needing this for a very similar use-case (for code coverage) also wrt `@nx-dotnet/core:test`.

Of note, it appears that even if the `{workspaceRoot}` token is at the beginning of option it doesn't work as expected. It gets replaced by ''.

Is this a bug?

cc: @AgentEnder  - sorry to name drop.   Have seen you having commented on similar token substitutions and thought you might be able to give a hand with our use cases in nx-dotnet.

**Comment by AgentEnder** [comment]
Its expected behavior - `{workspaceRoot}` is just replaced by an empty string, as in the absence of `{projectRoot}`, paths are assumed to be based on the workspace's root. This makes it essentially just a visual indicator.

RE: nx-dotnet use cases, the issue is that the dotnet command execution's cwd is inside of the project root, and you want a way to abstract out the proper '../../' offset or an absolute path right?

**Comment by mattfysh** [comment]
Another use case, I'm trying to automate cluster creation using nx and pulumi, and this is a bit of config that is currently not working so I'm hard coding the token to my `/Users/matt/...` path:

```json
"executor": "@wanews/nx-pulumi:up",
"options": {
  "envVars": [
    "PULUMI_BACKEND_URL=file://{workspaceRoot}/envs/local"
```

I can see the fix could be as easy as updating these two functions, but wanted to check if there is a reason for this error before submitting a PR:

1. https://github.com/nrwl/nx/blob/54bae6588a7100c5cc8a1da033dd277f75110cf8/packages/nx/src/project-graph/utils/project-configuration-utils.ts#L538-L566
2. https://github.com/nrwl/nx/blob/54bae6588a7100c5cc8a1da033dd277f75110cf8/packages/nx/src/tasks-runner/utils.ts#L219-L249

**Comment by mattfysh** [comment]
A couple of other points:
1. `{projectName}` is supported by `resolveNxTokensInOptions` ... but not by `interpolate`
2. A `{configurationName}` would also be useful

**Comment by Avivbens** [comment]
HI man 👋 

I've used this in one of my projects, and might solve it for you:
`your-command --some-flag=$(PWD)/<SOME_PATH>/{projectName}`


See the reference [in here](https://github.com/Avivbens/c-programming-uni-portfolio/blob/master/projects/task2/project.json#L11-L12)
