### ISSUE TITLE
Unable to connect to self-hosted gitlab

### ISSUE THREAD

**Issue by Akxe** [nrwl/nx#14466]
### Current Behavior

I wanted to use Gitlab Integration. I followed the https://nx.dev/nx-cloud/set-up/gitlab guide. But after filling everything in according to the guide I am getting the `Could not authenticate. Verify your repository name is correct and your access token is valid.` error.

### Expected Behavior

It should work

### Steps to Reproduce

1. Create NX Cloud account
2. Follow instructions
3. Try to set up "VCS Integrations"
4. Select GitLab
5. Fill in data

In my case I pasted there these data:
* Repository URL: https://gitlab.agereklama.cz/akxe/rita and also akxe/rita
* token: *****
* (Optional) Override Gitlab API URL: https://gitlab.agereklama.cz, //gitlab.agereklama.cz, https://gitlab.agereklama.cz/api/v4, https://gitlab.agereklama.cz/api

### Nx Report

```shell
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : win32 x64
   npm  : 8.1.3
   
   nx : 15.5.1
   @nrwl/angular : 15.5.1
   @nrwl/cypress : 15.5.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.1
   @nrwl/js : 15.5.1
   @nrwl/linter : 15.5.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.5.1
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.5.1
   @nrwl/workspace : 15.5.1
   @nrwl/vite : Not Found
   typescript : 4.9.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @ngrx/effects: 15.1.0
         @ngrx/store: 15.1.0
         @ngrx/store-devtools: 15.1.0
```

### Failure Logs

```shell
Could not authenticate. Verify your repository name is correct and your access token is valid.
```

### Additional Information

Link to the private workplace: https://cloud.nx.app/orgs/63c7f43f5f1a3b000ead5a1d/workspaces/63c7f48285ec1a087ec8a9e0/set-up-vcs-integration

**Comment by StalkAltan** [comment]
Hi, it does look like something is wrong when using override urls, we are taking a look and will keep you updated here.

**Comment by StalkAltan** [comment]
Hi @Akxe and @bboehm86 

We've fixed this issue and it should be released to nx.app production late next week (roughly Feb 2nd or 3rd). Apologies for the inconvenience here! I'll leave the issue open until it's released.
