### ISSUE TITLE
@nrwl/next/plugins/with-nx module not found when next.config file changed to .mjs instead of .js

### ISSUE THREAD

**Issue by ixahmedxi** [nrwl/nx#14470]
### Current Behavior

Supposedly you want to change the next config file from `next.config.js` to `next.config.mjs`, changing the next configuration with the nx plugin to the following:

```javascript
//@ts-check

// eslint-disable-next-line @typescript-eslint/no-var-requires
import { withNx } from '@nrwl/next/plugins/with-nx';

/**
 * @type {import('@nrwl/next/plugins/with-nx').WithNxOptions}
 **/
const nextConfig = {
  nx: {
    svgr: false,
  },
};

export default withNx(nextConfig);
```

Yields the following error while the editor is not complaining, and `node_modules` does have the with-nx file in the correct location. Changing the file to `next.config.js` and the syntax to require imports fixes the issue.

### Expected Behavior

The expected behaviour would be that the `with-nx` plugin can be used in configurations that are both `mjs` and `js` files.

### Steps to Reproduce

1. create a new integrated repo with a next.js app
2. change the `next.config.js` to `next.config.mjs`
3. change the require import statement of the with-nx plugin to an esm import
4. change module.exports to export default
5. run `nx run my-app:serve` or build and observe that the module not found error is displayed and the process exits with due to the error.

### Nx Report

```shell
Node : 18.13.0
   OS   : linux x64
   pnpm : 7.25.0
   
   nx : 15.5.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.5.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.2
   @nrwl/js : 15.5.2
   @nrwl/linter : 15.5.2
   @nrwl/nest : Not Found
   @nrwl/next : 15.5.2
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.5.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.5.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.5.2
   @nrwl/webpack : 15.5.2
   @nrwl/workspace : 15.5.2
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by martdavidson** [comment]
If you do `import { withNx } from '@nrwl/next/plugins/with-nx.js';` it works. I don't know why, I just tried it because of the error message:

```
   Did you mean to import @nrwl/next/plugins/with-nx.js?
   Pass --verbose to see the stacktrace.
```

**Comment by StringKe** [comment]
```
// eslint-disable-next-line @typescript-eslint/no-var-requires
import {withNx} from '@nrwl/next/plugins/with-nx.js';

/**
 * @type {import('@nrwl/next/plugins/with-nx').WithNxOptions}
 **/
const nextConfig = {
  reactStrictMode: true, i18n: {
    locales: ['zh-CN'], defaultLocale: 'zh-CN',
  }, nx: {
    // Set this to true if you would like to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: false,
  },
}

module.exports = withNx(nextConfig)
```

```
 >  NX   module is not defined in ES module scope


ReferenceError: module is not defined in ES module scope
```

**Comment by ndcunningham** [comment]
This is expected: https://nodejs.org/api/esm.html#esm_mandatory_file_extensions

**Comment by Brian-McBride** [comment]
> https://nodejs.org/api/esm.html#esm_mandatory_file_extensions

I'm getting this error now as well. 
```
>  NX   module is not defined in ES module scope
```

Any ideas on how to remove that? It is related to converting the file to `.mjs` and setting the monorepo's package.json to `"type":"module"`
