### ISSUE TITLE
Mention defaults for "outputs" in project configuration

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [nrwl/nx#14472]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/reference/project-configuration#outputs

### Additional context or description

`outputs` defaults to checking some default directories if they aren't specified in project configuration. But what are those default directories?

@AgentEnder poked into this locally and -unless I took poor notes- they are:

* Root project: `dist/`
* Within packages: `build/`, `dist/`, and `public/`

Can this be mentioned on the page please? I'd be happy to add that in!

**Comment by AgentEnder** [comment]
I can't imagine anyone having an issue with the change. It should be added in this document: https://github.com/nrwl/nx/blob/master/docs/shared/reference/project-configuration.md

Tag me on the PR and I'll get it merged.
