### ISSUE TITLE
[vite] error while updating dependencies with fresh install

### ISSUE THREAD

**Issue by Loghrenar** [nrwl/nx#14490]
### Current Behavior

Hello, 

I created a nx workspace with 3 react applications and 2 libraries all bundled by vite.
If I `serve` a single app it's fine, I have my libs content and dependencies but when I use `nx run-many --parallel --target=serve --projects=console,accounts,back-office` 
To run my 3 projects at the same time (all being on different ports obviously), only the first one works and when I try to reach the other ones I have 504 errors on deps.

What I noticed is that the deps folder under .vite folder is nicely filled the first time but when I switch on the second it erase all the content (see the images below)

I'm running with the latest versions of nx and vite and followed the doc here: 
https://nx.dev/getting-started/react-standalone-tutorial
https://nx.dev/packages/vite/documents/set-up-vite-manually#6.-use-vite.js
https://nx.dev/recipes/other/using-tailwind-css-in-react#using-tailwind-css-in-react-and-next.js

It's maybe a mistake from my side (or not) but it seems like I can't find some documentation about this behaviour anywhere else.

<img width="317" alt="Screenshot 2023-01-19 at 12 33 51" src="https://user-images.githubusercontent.com/10399443/213433159-c9232682-8c03-4317-8a5d-260f818c45e3.png">
<img width="1389" alt="Screenshot 2023-01-19 at 12 32 34" src="https://user-images.githubusercontent.com/10399443/213432925-6071ee30-f26b-4071-b8e9-53a1e73f86eb.png">
<img width="347" alt="Screenshot 2023-01-19 at 12 33 02" src="https://user-images.githubusercontent.com/10399443/213433279-e3833477-dc58-47a2-bf16-485ed1c83e48.png">
<img width="502" alt="Screenshot 2023-01-19 at 12 45 51" src="https://user-images.githubusercontent.com/10399443/213434339-d571435c-32b9-4509-bbda-2a07ea3ff168.png">

### Expected Behavior

Being able to serve multiple react/vite apps at the same time I guess and not having the vite folder emptied every time we switch from apps to apps

### Steps to Reproduce

1. Follow the documentation here
https://nx.dev/getting-started/react-standalone-tutorial
https://nx.dev/packages/vite/documents/set-up-vite-manually#6.-use-vite.js
https://nx.dev/recipes/other/using-tailwind-css-in-react#using-tailwind-css-in-react-and-next.js

### Nx Report

```shell
Node : 18.13.0
   OS   : darwin arm64
   npm  : 8.19.3
   
   nx : 15.5.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.5.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.1
   @nrwl/js : 15.5.1
   @nrwl/linter : 15.5.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.5.1
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.5.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.5.1
   @nrwl/webpack : 15.5.1
   @nrwl/workspace : 15.5.1
   @nrwl/vite : 15.5.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Additional Information

Tested with 15.5.2 too

**Comment by Loghrenar** [comment]
To add some context, it seems linked to that issue:
https://github.com/vitejs/vite/issues/9986

Funny thing is, it fix the error with turborepo but not with nx

**Comment by jaysoo** [comment]
It's a Vite issue with the default cache directory. It's a race condition where multiple projects are trying to access the same folder `node_modules/.vite`.

There are two ways to solve this:

1. Force re-optimization `npx nx run-many -t serve --force`
2. Set different cache directories in your `vite.config.ts` file.


For (2) see the example here https://github.com/jaysoo/multiple-apps-vite-nx

I'll close this issue for now, but let us know if you run into another problem.
