### ISSUE TITLE
Metadata mismatch

### ISSUE THREAD

**Issue by suburbanantihero** [nrwl/nx#145]
ERROR in Error: Metadata version mismatch for module /Development/workspace-nextgen/chimera-workspace/node_modules/@nrwl/nx/src/data-persistence.d.ts, found version 4, expected 3, resolving symbol NxModule.forRoot in /Development/workspace-nextgen/chimera-workspace/node_modules/@nrwl/nx/src/nx.module.d.ts, resolving symbol AppModule in /Development/workspace-nextgen/chimera-workspace/apps/chimera-web/src/app/app.module.ts, resolving symbol AppModule in /Development/workspace-nextgen/chimera-workspace/apps/chimera-web/src/app/app.module.ts

I had to modify each *metadata.json file to switch the version from 4 to 3 and then it worked fine.

**Comment by wbhob** [comment]
This error happens when you try using an Angular 5 library with Angular 4. Update your angular versions and you should be fine.

**Comment by vsavkin** [comment]
+1 to what @wbhob said. Closing this issue.
