### ISSUE TITLE
Cypress thrashing refreshing when using watch option with nxE2EPreset->option->bundler: "vite"

### ISSUE THREAD

**Issue by ZackDeRose** [nrwl/nx#14505]
### Current Behavior

Cypress thrashes when attempting to run the tests

### Expected Behavior

no thrashing

### Steps to Reproduce

1. Create a react app using vite as the bundler
2. run e2e target with watch command, i.e.: `npx nx e2e foo-e2e --watch`
3. click in cypress interface to the app.cy.ts file
4. where tests should run we see constant refreshes

### Nx Report

```shell
n/a
```

**Comment by chrismcleod** [comment]
@ZackDeRose @barbados-clemens im having this issue.  as this was marked closed as completed, what was the fix?

**Comment by barbados-clemens** [comment]
unable to reproduce. try with latest nx if it still happening please open a new issue with a clone-able reproducible repo so I can take a look.

**Comment by MarkvanderSalm** [comment]
I'm also running into this problem. I've made a repo [here](https://github.com/MarkvanderSalm/nx-react-vite-e2e-issue). Follow the instructions in the README.md file and you should be able to reproduce the issue.

**Comment by MarcRoemmelt** [comment]
I was running into the same when running Cypress in `--watch` mode on a React app that is bundled with Vite (same setup as @MarkvanderSalm).

Without the `bundler: 'vite'` option in the `cypress.config.ts` file it is working properly so I guess it is definitely related to Vite somehow .-)

@chrismcleod
