### ISSUE TITLE
NX Serve Builds Successfully But Fails To Restart On Watched Changes, No Error Messages

### ISSUE THREAD

**Issue by chasemaier** [nrwl/nx#14509]
### Current Behavior

(Reset just in case, works fine)

`$ node_modules/nx/bin/nx.js reset`

```
 >  NX   Resetting the Nx workspace cache and stopping the Nx Daemon.

   This might take a few minutes.

 >  NX   Daemon Server - Stopped
 >  NX   Successfully reset the Nx workspace.
```

---

(Serve the clean unmodified auto-generated "fastify" app generated by the generator in a workspace generated -- the page is served, and the JSON response is sent on the port as expected, the first run seems to work fine -- universally, when a file is changed it detects it, rebuilds seemingly successfully, then fails to restart with no log or error messages to indicate why. It appears the server started initially never terminates and continues to respond to traffic, though without the changes reflected. If you Ctrl-C break out of the `serve` session, the inspector port will usually also not be cleared and will fail to bind on second run of `serve`.)

`$ node_modules/nx/bin/nx.js run rpc-api:serve`

```
> nx run rpc-api:serve

Debugger listening on ws://localhost:9229/a9a9d922-6eba-4151-aa68-c6cc31bdcb1a
For help, see: https://nodejs.org/en/docs/inspector
[ watch ] build succeeded, watching for changes...
[ watch ] build succeeded, watching for changes...
There was an error with the build. See above.
.../dist/apps/rpc-api/main.cjs was not restarted.
```

---

(Attempt a stand-alone build to verify the build itself isn't an issue in the new state, it works fine -- build output files in `dist` seem to reflect changes made, they just aren't restarted)

`^C$ node_modules/nx/bin/nx.js run rpc-api:build`

```
> nx run rpc-api:build
 >  NX   Successfully ran target build for project rpc-api (2s)
```

### Expected Behavior

When changes are made the fastify app would restart and reflect the latest changes. Instead, the first instance continues to run despite new built JS files being present in the dist folder.

### Steps to Reproduce

`npx create-nx-workspace@latest`

```
✔ Choose what to create                              · integrated
✔ What to create in the new workspace                · apps
✔ Repository name                                    · hdc
✔ Enable distributed caching to make your CI faster  · No
```

---

`npm install -D @nrwl/node`

`npx nx g @nrwl/node:application rpc-api --pascalCaseFiles --js --framework fastify --port 4322`

---

`node_modules/nx/bin/nx.js run rpc-api:serve`

### Nx Report

```shell
Node : 18.13.0
   OS   : linux x64
   npm  : 8.19.3
   
   nx : 15.5.2
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.2
   @nrwl/esbuild : 15.5.2
   @nrwl/eslint-plugin-nx : 15.5.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.2
   @nrwl/js : 15.5.2
   @nrwl/linter : 15.5.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.5.2
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.5.2
   @nrwl/workspace : 15.5.2
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
[ watch ] build succeeded, watching for changes...
[ watch ] build succeeded, watching for changes...
There was an error with the build. See above.       #Nothing actually above
.../dist/apps/rpc-api/main.cjs was not restarted.
```

### Additional Information

I also generated a new workspace and new fastify JS app from generators and results were the same the second time.

**Comment by chasemaier** [comment]
I can also confirm that build alone (without serve) does not produce the same error.

```
$ npx nx build rpc-api --watch

> nx run rpc-api:build --watch

[ watch ] build succeeded, watching for changes...
[ watch ] build succeeded, watching for changes...
[ watch ] build succeeded, watching for changes...
[ watch ] build succeeded, watching for changes...
[ watch ] build succeeded, watching for changes...
```

It seems to be related to the stopping/serving/restarting. Where I can I find more logs/etc about this process? (I have also attempted adding `--verbose` to various commands like serve without seeing any additional output)

**Comment by kalp-lathia** [comment]
any updated on the issue?
