### ISSUE TITLE
Angular remote application in standalone doesn't generate environment files

### ISSUE THREAD

**Issue by KevinBonnoron** [nrwl/nx#14510]
### Current Behavior

When generating an angular remote app with the "standalone" flag, the generated "boostrap.ts" contains an error about not finding the file "environments/environment".

### Expected Behavior

Either the "environments/environment.ts" file is generated or the "apps/cart/src/boostrap.ts" should not use it.

### Github Repo

https://github.com/KevinBonnoron/nx-angular-standalone-remote-bug

### Steps to Reproduce

1. yarn create nx-workspace mf-app --preset=apps --nxCloud=false
2. cd mf-app
3. yarn add -D @nrwl/angular
4. yarn nx g @nrwl/angular:host web --remotes=shop,cart --standalone
5. yarn nx serve web --devRemotes=shop,cart

### Nx Report

```shell
Node : 18.12.1
OS   : linux x64
yarn : 1.22.19

nx : 15.5.2
@nrwl/angular : 15.5.2
@nrwl/cypress : 15.5.2
@nrwl/detox : Not Found
@nrwl/devkit : 15.5.2
@nrwl/esbuild : Not Found
@nrwl/eslint-plugin-nx : 15.5.2
@nrwl/expo : Not Found
@nrwl/express : Not Found
@nrwl/jest : 15.5.2
@nrwl/js : 15.5.2
@nrwl/linter : 15.5.2
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/nx-cloud : Not Found
@nrwl/nx-plugin : Not Found
@nrwl/react : Not Found
@nrwl/react-native : Not Found
@nrwl/rollup : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : Not Found
@nrwl/web : Not Found
@nrwl/webpack : 15.5.2
@nrwl/workspace : 15.5.2
@nrwl/vite : Not Found
typescript : 4.8.4
---------------------------------------
Local workspace plugins:
---------------------------------------
Community plugins:
```

### Failure Logs

```shell
./apps/cart/src/bootstrap.ts:1:0-57 - Error: Module not found: Error: Can't resolve './environments/environment' in '/workspaces/nx-angular15/apps/cart/src'

Error: apps/cart/src/bootstrap.ts:1:29 - error TS2307: Cannot find module './environments/environment' or its corresponding type declarations.

1 import { environment } from './environments/environment';
```

**Comment by byjokese** [comment]
Angular 15 changed the generation of the environment file, no longer gets generated by default. Although you can generate it using `ng generate environments` (requires Angular CLI 15.1).

I suppose all tools need to get a small patch not to import it by default?? The same happened to me in other libraries and tools.

**Comment by jgarciaokode** [comment]
Hi @byjokese , do you know how to generate environments in nx? ng is not installed and if i run `nx generate environments` i get this error
<img width="640" alt="image" src="https://user-images.githubusercontent.com/79897391/214019196-0644cbb9-e50e-4360-bd5e-a31812cf10db.png">

**Comment by byjokese** [comment]
@jgarciaokode You should have @angular/cli >15.1 (You can check your version with `ng version`, or in your `package.json`)

And normally should output something like:
![imagen](https://user-images.githubusercontent.com/5951126/214026650-d01aa057-fe4b-4c36-8285-eb2c140a8860.png)

On NX, haven't test it yet. On a quick test, I did get:
![imagen](https://user-images.githubusercontent.com/5951126/214026931-6660d39b-5cd5-4eb9-be41-64c2c666c0a4.png)

Will give it a go later, if I have some time.

**Comment by jgarciaokode** [comment]
@byjokese many thanks, the problem was i created the nx workspace with an older version of angular 15.0.0. It is working with the latest version -->  npx create-nx-workspace@latest

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/79897391/214033496-ccba4fe8-2d5a-4504-bfd9-d92d2b02c5c0.png">
