### ISSUE TITLE
run-many crash on packages lacking specified target in 15.4.3

### ISSUE THREAD

**Issue by miluoshi** [nrwl/nx#14511]
### Current Behavior

This is [the same bug](https://github.com/nrwl/nx/issues/13223) that was [created in 15.1.0](https://github.com/nrwl/nx/pull/11659), then [was fixed in 15.2.0](https://github.com/nrwl/nx/pull/13232) and then again was broken by [this PR in 15.4.3](https://github.com/nrwl/nx/pull/13138).

If run-many is run with list of packages and some of those packages are lacking the specified target the command ends with fail state.

### Expected Behavior

The run-many runs on successfully and skips projects without the target as in nx prior 15.4.3.

### Steps to Reproduce

1. run `nx run-many --projects=<existing_projects_list> --target=<non-existent-target>`
2. command fails with following error:
    ```
    Error: No projects found for project patterns
      at projectsToRun (/path-to-project/node_modules/nx/src/command-line/run-many.js:59:15) 
    ```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.12.1
   OS   : darwin x64
   yarn : 1.22.18
   
   nx : 15.4.3
   @nrwl/angular : 15.4.3
   @nrwl/cypress : 15.4.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.3
   @nrwl/js : 15.4.3
   @nrwl/linter : 15.4.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.4.3
   @nrwl/web : 15.4.3
   @nrwl/webpack : 15.4.3
   @nrwl/workspace : 15.4.3
   @nrwl/vite : 15.4.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @ngrx/component-store: 15.0.0
         @ngrx/effects: 15.0.0
         @ngrx/entity: 15.0.0
         @ngrx/store: 15.0.0
         @ngrx/schematics: 15.0.0
         @storybook/angular: 6.5.15
         @testing-library/angular: 13.1.0
```

**Comment by AgentEnder** [comment]
This should be fixed in latest. The PR fixing it was https://github.com/nrwl/nx/pull/14238/. Any version over 15.4.5 should contain the fix.
