### ISSUE TITLE
React Vite not loading envs

### ISSUE THREAD

**Issue by amal-chandran** [nrwl/nx#14528]
### Current Behavior

The vite builder is not loading the environment variables while building react app 

### Expected Behavior

As described in the documentation it should load the environment variables 
Reference:
https://nx.dev/recipes/environment-variables/use-environment-variables-in-react
https://nx.dev/recipes/environment-variables/define-environment-variables
https://vitejs.dev/guide/env-and-mode.html

### Github Repo

https://github.com/amal-chandran/nx-issues/tree/main/react-vite-test

### Steps to Reproduce

1. create an nx application repo
2. install nx react
3. create an app with "npx nx generate @nrwl/react:application app-react --bundler=vite --compiler=swc --e2eTestRunner=none --minimal "
4. create an env file and define a variable 
5. try to access the app in react app eg: {process.env.NX_API_URL}
6. it will throw an error / 

### Nx Report

```shell
Node : 14.18.1
   OS   : linux x64
   npm  : 6.14.15

   nx : 15.5.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : 15.5.3
   @nrwl/linter : 15.5.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.5.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.5.3
   @nrwl/vite : 15.5.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by mandarini** [comment]
I will update the docs, sorry. You need to prefix your variable with `VITE_` instead of Nx. See in the [docs](https://vitejs.dev/guide/env-and-mode.html):

![Screenshot 2023-01-23 at 5 24 07 PM](https://user-images.githubusercontent.com/6603745/214078261-603a263b-b524-4ab3-b20d-a3cd28da728d.png)
