### ISSUE TITLE
Allow `dependsOn` to specify the configuration it wants to depend on

### ISSUE THREAD

**Issue by josh-braid** [nrwl/nx#14525]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I'd like it to be possible for a target to specify which configuration of its dependencies it wants.

So:
```json
  "targetName": {
    "dependsOn": ["^build:scriptname"]
  }
```

## Motivation

Currently, I have a `build` target that uses different configurations to build different scripts.

So for example, here is an example that allows `nx run db:build:psql` and `nx run db:build:migrate`:
```json
"build": {
"executor": "@nrwl/node:webpack",
"options": {
  "outputPath": "dist/libs/db",
  "tsConfig": "libs/db/tsconfig.lib.json",
  "main": "libs/db/src/index.ts"
},
"configurations": {
  "psql": {
    "main": "libs/db/src/psql.ts",
    "outputFileName": "psql.js"
  },
  "migrate": {
    "main": "libs/db/src/scripts/migrate.ts",
    "outputFileName": "migrate.js"
  }
}
```
What I'd like to do, is create some run targets that specify a particular configuration they depend on:
```json
    "migrate": {
      "executor": "nx:run-commands",
      "dependsOn": ["^build:migrate"],
      "options": {
        "command": "node dist/libs/db/migrate.js"
      }
    }
```
But, `"dependsOn": ["^build:migrate"]` isn't legal. The only way to get the `build:migrate` output specifically (that I have found) is for `migrate` to also have a `migrate` configuration, which gets passed up to `build`. This means I have to do:

```
```json
    "migrate": {
      "executor": "nx:run-commands",
      "dependsOn": ["^build:migrate"],
      "options": {
        "command": "node dist/libs/db/migrate.js"
      },
      "configuration": {
        "migrate": {}
      }
    }
```
Which is weirdly redundant, but also I have to invoke it like `nx run db:migrate:migrate` which is also redundant.

## Suggested Implementation

If the configuration is specified in `dependsOn` then that is used, rather than the configuration of the target itself.

## Alternate Implementations

I could work around this by not using configurations and making a separate target for every script, like `build-migrate`, `build-psql` etc, but now I have to remember to go in and add all of these to the cacheable array in `nx.json`. This seems bad, they are basically all build targets, just different configurations. So it makes sense to be able to reuse the cacheability of `build`

**Comment by ciriousjoker** [comment]
This would make some configurations a lot simpler.

**Example:**
target "analyze" depends on target "build:analyze".

Without this, we have to duplicate the whole build block just to add an analysis target. We then have to keep them in sync so the bundle size analysis always matches the production configuration.

(we're using Angular)

**Comment by AgentEnder** [comment]
Although this issue is older, there has been more discussion on #15064, so I'm going to close this one out as a duplicate. 

Feel free to chime in there, the main complexity comes in when you have something like

```
a
b - dependsOn: a:test
c - dependsOn: a:prod
d - dependsOn b, c
```

How should we resolve that? Do we error, or do we run both? The outputs from a:test and a:prod will likely clobber each other.
