### ISSUE TITLE
Angular application options are not passed through during `angular-standalone` preset for `create-nx-workspace`

### ISSUE THREAD

**Issue by zjkipping** [nrwl/nx#14526]
### Current Behavior

Currently the application options are ignored by the `create-nx-workspace` when running with a specific preset.

The only way to make this "work" would be to:
* Create a `--preset=empty` workspace
* Run `nx g @nrwl/angular:init`
* Run `nx g @nrwl/angular:application test-app --routing --standalone --style=scss`

Though this workspace setup doesn't have the parity to the angular cli `ng new` that the simplified `angular-standalone` preset workspace does.

### Expected Behavior

Application option flags such as `--standalone` or `--routing` should be passed to the generated angular application in the `angular-standalone` preset.

Was hoping this would be a good replacement until the Angular CLI supports generating an application using standalone api by default with `ng new`.

### Steps to Reproduce

1. npx create-nx-workspace@latest test-workspace --preset=angular-standalone --nxCloud=false --style=scss --standalone --routing

### Nx Report

```shell
create-nx-workspace@latest

   Node : 18.12.0
   OS   : win32 x64
   npm  : 8.19.2

   nx : 15.5.2
   @nrwl/angular : 15.5.2
   @nrwl/cypress : 15.5.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.2
   @nrwl/js : 15.5.2
   @nrwl/linter : 15.5.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.5.2
   @nrwl/workspace : 15.5.2
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by Coly010** [comment]
This support has been added with: https://github.com/nrwl/nx/pull/14886 https://github.com/nrwl/nx/pull/14953
