### ISSUE TITLE
pnpm installs aren't working well with nx-cloud (breaks npx/pnpx and ci)

### ISSUE THREAD

**Issue by ALMaclaine** [nrwl/nx#14534]
### Current Behavior

I started a new project on `v15.5.3` with `nextjs/react/ts`.

I'm installing using `pnpm`.

I'm running into the following issues:

`pnpm nx-cloud <commands>` work sometimes, but occasionally hands on `start-agent`.

`pnpx nx-cloud <commands>` error out with: `This version of Nx Cloud is incompatible with the @nrwl/* packages in your workspace.`

`npx nx-cloud <commands>` work sometimes, but occasionally hangs on `start-agent` and can give the above version error on `stop-all-agents`

### Expected Behavior

nx-cloud commands + ci scripts work in a consistent way when using pnpm.

### Github Repo

https://github.com/boostcollective/boost-test

### Steps to Reproduce

Create new project, use next/react/ts.

Install using `pnpm`.

Try to run nx-cloud commands with `npx/pnpx/pnpm`.

Try to get a github ci build to work.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : darwin x64
   pnpm : 7.25.1
   
   nx : 15.5.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.5.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.3
   @nrwl/js : 15.5.3
   @nrwl/linter : 15.5.3
   @nrwl/nest : Not Found
   @nrwl/next : 15.5.3
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.5.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.5.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.5.3
   @nrwl/webpack : 15.5.3
   @nrwl/workspace : 15.5.3
   @nrwl/vite : 15.5.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
This causes my github ci actions to either fail or hang:


Run npx nx-cloud stop-all-agents
npm WARN exec The following package was not found and will be installed: nx-cloud@15.0.2
NX CLOUD ERROR
---------------------------------------
This version of Nx Cloud is incompatible with the @nrwl/* packages in your workspace.

Match your @nrwl/nx-cloud version to the same major version of your @nrwl/* packages and try again.
---------------------------------------
Error: Process completed with exit code 1.
```

![Screen Shot 2023-01-21 at 10 37 54 PM](https://user-images.githubusercontent.com/16461670/213900878-1a96af28-e0bb-4668-9385-80666be1bb4a.png)
```


### Additional Information

_No response_

**Comment by Zamiell** [comment]
I tried migrating my repo from yarn to pnpm today and ran into this nightmare of an issue.

To start with, `pnpx` is [deprecated](https://pnpm.io/6.x/pnpx-cli) in favor of `pnpm exec`, so let's discuss `pnpm exec` instead.

I discovered that `pnpm exec` has a bug with `package.json` files, which I documented here: https://github.com/pnpm/pnpm/issues/6030

That bug is likely related to this issue.

**Comment by ltetreault-va** [comment]
Have you found a resolution for this?

**Comment by Zamiell** [comment]
Well, it looks like they haven't responded to my issue in a month, so I'm not sure what that means.
For now, the resolution is that you should use yarn, which works perfectly with monorepos, and works perfectly with `npx`.

**Comment by ALMaclaine** [comment]
@AgentEnder any updates?

**Comment by ALMaclaine** [comment]
@Zamiell @ltetreault-va Does this fix for you? I haven't tested but want to hear from you before closing.

**Comment by ltetreault-va** [comment]
@ALMaclaine yes I discovered that setting later on and was able to get it working. Thank you

**Comment by Zamiell** [comment]
My issue is different from the OP, and is described [here](https://github.com/pnpm/pnpm/issues/6030).
