### ISSUE TITLE
Nx.dev broken on Edge

### ISSUE THREAD

**Issue by OzBob** [nrwl/nx#1453]
Nx.dev website shows blank content on Edge (v42)

https://nx.dev/getting-started/what-is-nx

Content displayed for a second, then relaced with blank. Menu and footer all OK.

Full error stack from console:
CONSOLE1810304: console.memory is not implemented and will return 0 for all attributes. Please use the memory profiler to monitor memory utilization.
SCRIPT5007: Object expected base.js (1051,19)
ERROR TypeError: Object doesn't support property or method 'scrollTo'

**Comment by bcabanes** [comment]
Hi @OzBob and thank you for the report, we will check this out!

**Comment by OzBob** [comment]
https://nx.dev/
now displays on Edge.

but 'mat-input-0' search input field does nothing on Chrome or Edge. On Chrome the search results does show, but is blank.  I tried searching for 'create-nx-workspace' by pasting it. Then I typed 'create-', and a blank search results div appeared, no 'no results' message etc. just white empty div.

Testing on https://nx.dev/getting-started/what-is-nx, typing 'create-': 
<div class="search-results search-results-white ng-star-inserted" _ngcontent-serverapp-c1=""><h1 class="ng-star-inserted" _ngcontent-serverapp-c1="">No Results.</h1></div>
now displays with the words "No Results",

Re-testing on the homepage, still brings up blank search results

**Comment by bcabanes** [comment]
Hi @OzBob!
This is because there is actually no result for that. The search in place is not looking through the content yet. It only looks at sections and section titles. I agree this is not optimal. It will be improve as soon as we have time! 👍
