### ISSUE TITLE
nx cli looses passed configuration ID (nx e2e, nx test, nx serve)

### ISSUE THREAD

**Issue by jbjhjm** [nrwl/nx#14542]
### Current Behavior

When executing `nx serve my-project:serve:production`,

CLI transforms it to nx run - and executes serve target without the given configuration.

Console output states:
```
> nx run sandbox-frontend:serve
```

### Expected Behavior

`nx serve my-project:serve:production` should execute `nx run sandbox-frontend:serve:production`.

### Steps to Reproduce

Use any project, execute a target with configuration ID NOT using `nx run` but `nx serve`, `nx build` etc.

### Nx Report

```shell
Node : 16.17.0
   OS   : win32 x64
   npm  : 8.15.0

   nx : 15.5.1
   @nrwl/angular : 15.5.1
   @nrwl/cypress : 15.5.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.1
   @nrwl/js : 15.5.1
   @nrwl/linter : 15.5.1
   @nrwl/nest : 15.5.1
   @nrwl/next : Not Found
   @nrwl/node : 15.5.1
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.5.1
   @nrwl/workspace : 15.5.1
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @fortawesome/angular-fontawesome: 0.12.1
         @ngrx/effects: 15.1.0
         @ngrx/router-store: 15.1.0
         @ngrx/store: 15.1.0
         @nguniversal/express-engine: 15.1.0
         @ngrx/schematics: 15.1.0
         @ngrx/store-devtools: 15.1.0
         @nguniversal/builders: 15.0.0
         ng-mocks: 14.5.3
```

### Additional Information

Digged into the nx CLI bin entry point and found the following:
in nx/bin/init local:

- isKnownCommand does not "know" the commands `nx e2e`, `nx test`, `nx build`, `nx serve`. (Not sure if thats a regression or intended.)
- rewritePositionalArguments is then called to convert these args into `nx run`. The way it works, it will loose configuration if one was passed. 

Checking out the documentation, I could not find mentions of `nx e2e`, `nx test`, `nx build`, `nx serve` anymore.
I guess these are only legacy API and not intended to be used anymore?

In that case, a fix is not needed... but console should log a warning/error to update repo commands to use `nx run` instead.

**Comment by cbl980226** [comment]
I think you should add defaultConfiguration in target

project.json
```json
{
  "targets": {
    "serve": {
      "executor": "@nrwl/next:server",
      "defaultConfiguration": "development", // or production
      "options": {
        "buildTarget": "blog:build",
        "dev": true
      },
      "configurations": {
        "development": {
          "buildTarget": "blog:build:development",
          "dev": true
        },
        "production": {
          "buildTarget": "blog:build:production",
          "dev": false
        }
      }
    },
  }
}
```

**Comment by AgentEnder** [comment]
The command you specified is invalid. For infix notation, you would pass configuration with the `-c` flag. 

The two valid ways to pass configuration are:
- `nx run {myProject}:{myTarget}:{myConfiguration}`
- `nx {myTarget} {myProject} -c {myConfiguration}`
