### ISSUE TITLE
Next.js Custom Server Express causes an infinite loop with Nx on a Linux environment

### ISSUE THREAD

**Issue by a-nxtsens** [nrwl/nx#14550]
### Current Behavior

This bug concerns the Next.js Custom Server Express compatibility with Nx. In fact, after creating a Next.js project using Nx and when you include a Next.js Custom Server Express into the project, you will notice that the project would not be able to start using the development mode and it will be always stuck in a infinite compiling loop.

Each time, Nx CLI will say that `File change detected. Starting incremental compilation...` and it will recompile the whole project again without being able to start the app. I am not sure about the reason behind this issue but I would guess that the new Next.js Custom Server dependency does create some new files and so Nx would think that these files are related to the project code and so it will recompile the project again.

This bug concerns only the development mode and so for the production mode the application would correctly start.
However, this bug seems occur only in Linux (for my case I have tested the issue with Ubuntu 20.04.4 LTS) because in MacOS the combination works fine without any issues.

### Expected Behavior

The project should be able to start in the development mode without any infinite loop or a need to recompile the project again like the case of MacOS.

### Github Repo

https://github.com/ericschaal/nx-bug

### Steps to Reproduce

Pleasure ensure to test the previous repository with a Linux environment.

1. Clone the previous specified Github repository.
2. npm i (for installing project dependencies).
3. npx nx serve.

You will immediately notice that the project would not be able to start and it will be always stuck in an infinite loop.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : linux x64
   npm  : 8.11.0
   
   nx : 15.5.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.5.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.2
   @nrwl/js : 15.5.2
   @nrwl/linter : 15.5.2
   @nrwl/nest : Not Found
   @nrwl/next : 15.5.2
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.5.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.5.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.5.2
   @nrwl/webpack : 15.5.2
   @nrwl/workspace : 15.5.2
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
10:47:27 - File change detected. Starting incremental compilation...


10:47:28 - Found 0 errors. Watching for file changes.
Debugger listening on ws://localhost:9229/...
For help, see: https://nodejs.org/en/docs/inspector
event - compiled client and server successfully in 335 ms (166 modules)
```

### Additional Information

**Configuration :**

OS : Ubuntu 20.04.4 LTS (in dual boot with Windows 10).

PC Model : Lenovo ThinkPad 20XL.

Processor : AMD® Ryzen 5 pro 5650u with radeon graphics.

Memory : 16 Gb.

**Comment by wadamek65** [comment]
@a-nxtsens Did you perhaps find a workaround for this?

**Comment by ndcunningham** [comment]
@wadamek65 This is a default behaviour of Next.js' CLI.
I'm glad you found a workout you could also try with `create-next-app` to see if the behaviour is the same.

@enk0de can you try his suggestion. 
I'll close the issue because I do not think this is related to Nx.
