### ISSUE TITLE
node - esbuild bundler are not attaching debugger - sourcemap not generated

### ISSUE THREAD

**Issue by gaurang171** [nrwl/nx#14556]
### Current Behavior

When I build the node application with esbuild, break pints on typescripts are not working but instead in need to go to main.cjs under dist to break. 

I created a the workspace with express preset. webpack builds are attaching break points correctly but that doesn't allow me to import esmodules so I tried esbuiids with node application. es modules works but now can not attach break points on TS file.

### Expected Behavior

For ES Builds TS break points should work.

### Steps to Reproduce

1. npx nx create-nx-workspace --preset=express  
2. npx nx generate @nrwl/node:application myAppES --no-interactive             (builds esbuild  optionaly can use  `--bundler=esbuild`)
3. npx nx generate @nrwl/node:application myAppWP --bundler=webpack --no-interactive  

now 
`npx nx serve myAppES`   add break points on typescript file. it won't work

same works for myAppWP  

### Nx Report

```shell
Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : win32 x64
   npm  : 8.19.3

   nx : 15.5.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.3
   @nrwl/esbuild : 15.5.3
   @nrwl/eslint-plugin-nx : 15.5.3
   @nrwl/expo : Not Found
   @nrwl/express : 15.5.3
   @nrwl/jest : 15.5.3
   @nrwl/js : 15.5.3
   @nrwl/linter : 15.5.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.5.3
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.5.3
   @nrwl/workspace : 15.5.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by gaurang171** [comment]
It appears esbuilds are missign sourcemap even is the flag is set to true. in main.cjs I am not seeing any references to soucemap.

**Comment by gaurang171** [comment]
adding sourcemap both to esbuildOptions under options in project.json file creates the sourcemap and now able to use breakpoints in Ts file. 
still assets are not copied to the dist folder when in the watch mode similar to   #12901 

```
"options": {
        "esbuildOptions": { "sourcemap":"both" },
........
.........
}
```

**Comment by DibyodyutiMondal** [comment]
@jaysoo given the changes in the PR that closed this, I assume that the "sourcemap" option for the executor is going to become deprecated and that we're to migrate to "esbuildOptions" for it?
