### ISSUE TITLE
Replace Prettier and ESLint with Rome

### ISSUE THREAD

**Issue by DarkBitz** [nrwl/nx#14576]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Replace Prettier and ESLint with [Rome|https://github.com/rome/tools].

## Motivation
Less dependencies and faster checks.

## Suggested Implementation
-

## Alternate Implementations
-

**Comment by DaSchTour** [comment]
Looks like a very ambitious project. I wouldn't jump straight into replacing something. I remember how webpack struggled to get a foundation of maintainers to have continuous development.
And it will take a lot of time to build a full working ecosystem.
Replacing prettier would be a dealbreaker for me as I doubt it has the plugins ready which I use. The same is true for ESLint.

**Comment by AgentEnder** [comment]
Adding support for a new linter is as simple as adding an executor in a plugin. Formatters are a bit of a different story, but we are hoping they trend in the same direction as we figure out exactly what that will look like with our current prettier integration.

I'd recommend a community plugin, but there's not one for Rome right now. But it would certainly be cool to see one, so feel free to start working on it 😄

**Comment by lzm0x219** [comment]
mark.

**Comment by FabienDehopre** [comment]
The project has been archived and the website is not accessible anymore.
