### ISSUE TITLE
Enabling Default TypeScript Linting in JavaScript Projects

### ISSUE THREAD

**Issue by arthurgubaidullin** [nrwl/nx#14579]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Enable linting of TypeScript files by default in all JavaScript projects for improved code quality and consistency.

Command example:
```sh
npx nx generate @nrwl/js:library entity --unitTestRunner=jest --directory=entity --compiler=swc --importPath=@myspace/entity --js --testEnvironment=node
```

## Motivation

It seems peculiar that TypeScript files are not being linted in this project. I need to manually edit the 'lintFilePatterns' configuration to include them.

## Suggested Implementation

Perhaps this could be the third `JS + TS` option.

## Alternate Implementations

I don't know.

**Comment by AgentEnder** [comment]
Passing `--js` tells us that you aren't going to be using TS files, so we trim the list of patterns down. I feel that fits most use cases, but perhaps there is one I've not considered. 

What use case has led to having .ts files that you want to be linted within a project that was generated with --js?

**Comment by meeroslav** [comment]
Does using a standard TS project restrict you from having JS files in there somehow? If manually changing `lintFilePatterns` works for you, then that concludes the issue. 

We will not be changing the `lintFilePatterns` for `JS` projects to include also `TS` files, as that is in contradiction with the intent when passing `--js`.
