### ISSUE TITLE
Having nx key in package.json breaks "enforce-module-boundaries" linting

### ISSUE THREAD

**Issue by diginikkari** [nrwl/nx#14571]
### Current Behavior

If workspace has `nx` key in root package.json (e.g. ). Linter complains if there is any import from e.g. `path` or `fs` in some project with `enforce-module-boundaries` eslint rules.

### Expected Behavior

There should not be lint errors

### Github Repo

https://github.com/diginikkari/nx-lint-issue

### Steps to Reproduce

1. run `pnpm exec nx lint some-lib --verbose --skip-nx-cache`

### Nx Report

```shell
Node : 16.19.0
   OS   : darwin x64
   pnpm : 7.25.1
   
   nx : 15.6.0
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.0
   @nrwl/js : 15.6.0
   @nrwl/linter : 15.6.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.6.0
   @nrwl/vite : Not Found
   typescript : 4.8.4
```

### Failure Logs

```shell
✖  nx run some-lib:lint
       Linting "some-lib"...
       
       /Users/timo/repos/nx-lint-issue/packages/some-lib/src/lib/some-lib.ts
         1:1  error    Buildable libraries cannot import or export from non-buildable libraries  @nrwl/nx/enforce-module-boundaries
         1:8  warning  'path' is defined but never used                                          @typescript-eslint/no-unused-vars
       
       ✖ 2 problems (1 error, 1 warning)
       
       Lint warnings found in the listed files.
       
       Lint errors found in the listed files.
```

### Additional Information

Started after upgrading to 15.6.0

**Comment by mcmxcdev** [comment]
Can confirm this, removing it again fixes the issue.

**Comment by StringKe** [comment]
Has there been any progress on this issue with the same error?

**Comment by JoA-MoS** [comment]
I can confirm I am seeing the same error with 

```
import { setTimeout } from 'timers/promises'
```

and also

```
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
```

**Comment by meeroslav** [comment]
Hmm... this is a very interesting problem. The problem is actually in the `findProjectForPath` https://github.com/nrwl/nx/blob/master/packages/nx/src/project-graph/utils/find-project-for-path.ts#L43-L59

When `nx` is added to the `package.json`, our `projectRootMappings` go from:
```
Map(2) { 'packages/some-lib' => 'some-lib' }
```
to
```
Map(2) { 'packages/some-lib' => 'some-lib', '.' => 'nx-lint-issue' }
```

The function above will take `path` and call `dirname` on it, which will eventually return `.` and map it to `nx-lint-issue`.

Error aside, should the `'.' => 'nx-lint-issue'` be there at all @AgentEnder?

**Comment by meeroslav** [comment]
This error will be present for all the node native imports.

**Comment by AgentEnder** [comment]
Yes, `'.' => 'nx-lint-issue'` represents the root project, which exists when a project.json is located at root, or there is an nx key in the root package.json
