### ISSUE TITLE
Add E2E project generation option to nest application generator

### ISSUE THREAD

**Issue by FurlanLuka** [nrwl/nx#14572]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I would like to add E2E project generation option to nest application generator schema
## Motivation

In most recent version, node application generator has been updated to generate E2E project by default. Nest application generator which uses node generator was not updated and therefore it always generates E2E project.
## Suggested Implementation

Add E2E generation option to nest application schema and pass the option to node application generator when generating nest application

**Comment by creadicted** [comment]
@FurlanLuka Do you have a sample of how your proposal of the e2e should be used?
