### ISSUE TITLE
loadChildren (angular v8) and tsconfig paths ?

### ISSUE THREAD

**Issue by appsolutegeek** [nrwl/nx#1458]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

I couldn't get the loadchildren to use the tsconfig paths, whats the recommended way of doing this, adding an additional tsconfig path just for the module, i.e. currently i am doing this, its not pretty :-), using multiple "../" to get back to where i need to be to find the actualy library and register.module

```
@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule,    RouterModule.forRoot(
    [{ path: '', loadChildren: () => import("../../../../libs/register/src/lib/register.module").then(m => m.RegisterModule)}],
    { initialNavigation: 'enabled', enableTracing: true }
  ),
    HttpClientModule],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

of course, i have the following in my tsconfig

```
    "paths": {
      "@userinterface-ws/register": ["libs/register/src/index.ts"]
    }
```

But there is no way of getting the register.module filename that i need, using the above.

There are many ways to fix this, what is NX considering adopting ?

Adding a new tsonfig path specifically for the lazy load module, mutliple ?

Please provide any relevant information about your setup:

- version of Nx latest
- version of Angular CLI  8

**Comment by yannickglt** [comment]
If the `libs/register/src/index.ts ` file exports the `RegisterModule` and your tsconfig's declared as you described, then you should be able to declare your route as below:

```ts
RouterModule.forRoot(
  [{ path: '', loadChildren: () => import("@userinterface-ws/register").then(m => m.RegisterModule)}]
)
```

**Comment by appsolutegeek** [comment]
Oh man, thank you, I was really over thinking it :-) I thought i had to point it at a file.

Thank you - solved!
