### ISSUE TITLE
Virtual / fake tasks

### ISSUE THREAD

**Issue by dobesv** [nrwl/nx#14593]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

It would be nice if there was a way that I could tell nx that a certain task is actually just there to run other tasks and it shouldn't actually run it.

## Motivation

Our packages have a number of build steps they run from the `"scripts"` in `package.json`, for generating typescript & javascript & json files from graphql, running i18n processing, stuff like that.

Currently in these projects the `"build"` script runs all the separate builds.  It would be nice if nx could also be aware of these separate build steps and their dependencies, and I think it can be.  However, when it comes time to tell nx to build everything the package, I have to list off all the different tasks separately currently.  If I run `build` it'll run all the build steps first, then run `build` which will run all the build steps again.

## Suggested Implementation

If tasks had an boolean option called, say, `virtual` which could tell nx that I want it to use that task only for calculating dependencies but not to actually run it, it could work.

## Alternate Implementations

It might also be possible to do this with a custom executor, called `virtual-task` or similar.

**Comment by AgentEnder** [comment]
@dobesv You can use `nx:noop` for the executor on targets which do not need to actually do anything

**Comment by dobesv** [comment]
Ah thanks, is that documented somewhere?

**Comment by AgentEnder** [comment]
Eh, kind of? https://nx.dev/packages/nx/executors/noop

Nothing showing how to use it for this goal, but it has a doc page.

**Comment by dobesv** [comment]
Ah OK I was hunting around and didn't find it.  Thanks again!
