### ISSUE TITLE
Storybook can't load scss files when they are not *.module.scss

### ISSUE THREAD

**Issue by farhin00farhin** [nrwl/nx#14595]
### Current Behavior

When creating a basic react library with scss, trying to load storybook fails to load with following error:
```
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.

options.sourceMap should be a boolean.
   -> Enables/Disables generation of source maps.
   -> Read more at https://github.com/webpack-contrib/sass-loader#sourcemap
    at validate (/Users/sadiaafrin/sass-test/node_modules/webpack/node_modules/schema-utils/dist/validate.js:105:11)
    at Object.getOptions (/Users/sadiaafrin/sass-test/node_modules/webpack/lib/NormalModule.js:585:19)
    at Object.loader (/Users/sadiaafrin/sass-test/node_modules/sass-loader/dist/index.js:27:24)
    at processResult (/Users/sadiaafrin/sass-test/node_modules/webpack/lib/NormalModule.js:758:19)
    at /Users/sadiaafrin/sass-test/node_modules/webpack/lib/NormalModule.js:860:5
    at /Users/sadiaafrin/sass-test/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /Users/sadiaafrin/sass-test/node_modules/loader-runner/lib/LoaderRunner.js:252:18 
```

I created a new react application and then added a basic react library to it. Even after selecting `globalCss=true` it created `*.module.scss` files. After that I updated the `module.scss` file to be a `.scss` file and then added it to `preview.ts` to load it as a global style for all stories. That's how I encountered the error when trying to load/run storybook.

I'm working on a much bigger repo but it's basically running into the same issue and wanted to create a simple repo to see if I can reproduce the issue.

### Expected Behavior

Storybook should build with scss.

### Steps to Reproduce

1. create new workspace `npx create-nx-workspace <name>` <img width="566" alt="image" src="https://user-images.githubusercontent.com/15885390/214490354-e54c765c-a59b-4925-98df-5b778ff33b64.png">
2. Install webpack `npm i -d @nrwl/webpack`
3. Create a library `nx g lib mylib  --compiler=swc globalCss=true`  (globalCss had no effect?)
5. Add storybook with typescript
6. Update .module.scss files to be .scss file 

run storybook and you should see it fail.

### Nx Report

```shell
Node : 16.19.0
   OS   : darwin arm64
   npm  : 8.19.3
   
   nx : 15.5.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.5.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.3
   @nrwl/js : 15.5.3
   @nrwl/linter : 15.5.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.5.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.5.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.6.2
   @nrwl/web : 15.5.3
   @nrwl/webpack : 15.6.2
   @nrwl/workspace : 15.5.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.

options.sourceMap should be a boolean.
   -> Enables/Disables generation of source maps.
   -> Read more at https://github.com/webpack-contrib/sass-loader#sourcemap
    at validate (/Users/sadiaafrin/sass-test/node_modules/webpack/node_modules/schema-utils/dist/validate.js:105:11)
    at Object.getOptions (/Users/sadiaafrin/sass-test/node_modules/webpack/lib/NormalModule.js:585:19)
    at Object.loader (/Users/sadiaafrin/sass-test/node_modules/sass-loader/dist/index.js:27:24)
    at processResult (/Users/sadiaafrin/sass-test/node_modules/webpack/lib/NormalModule.js:758:19)
    at /Users/sadiaafrin/sass-test/node_modules/webpack/lib/NormalModule.js:860:5
    at /Users/sadiaafrin/sass-test/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /Users/sadiaafrin/sass-test/node_modules/loader-runner/lib/LoaderRunner.js:252:18
```

### Additional Information

The issue disappears if I downgrade `@nrwl/react` and `@nrwl/webpack` to `15.4.5`. `15.4.6` brings it back.

**Comment by farhin00farhin** [comment]
I didn't change anything from the basic options provided by Nx other than turning .module.scss files to .scss files.

**Comment by mandarini** [comment]
[This PR should fix this](https://github.com/nrwl/nx/pull/14577)

**Comment by farhin00farhin** [comment]
Awesome! Thank you so much @mandarini

**Comment by farhin00farhin** [comment]
> @farhin00farhin how are you importing the styles in your component? Can you please send me a reproduction repository? I want to try something out!

Ideally, we would like to add all styles in preview.ts for storybook. So it would be a simple .scss file import. It's a bit late where I am (11 pm), so I wouldn't be able to get you a reproduction repository super quickly. You can just follow my reproduction steps and that should reveal the issue to you :)

Here are some screenshots in the meantime 
<img width="365" alt="image" src="https://user-images.githubusercontent.com/15885390/214533308-73aedf95-08be-45c3-ac50-7c1b0c113921.png">
<img width="329" alt="image" src="https://user-images.githubusercontent.com/15885390/214533714-b4639636-38ba-4005-9854-c1ea027434ce.png">
<img width="348" alt="image" src="https://user-images.githubusercontent.com/15885390/214533860-0c544aaf-e239-4a07-ac8b-15fbb451b3a0.png">

**Comment by mandarini** [comment]
Perfect!! Thanks!!! :D

**Comment by mandarini** [comment]
Yep, I just verified, that PR fixes it! :D

**Comment by mandarini** [comment]
It was [bashaus](https://github.com/bashaus) PR that fixed it!
