### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'defaultProject')

### ISSUE THREAD

**Issue by jonsoku2** [nrwl/nx#14592]
### Current Behavior

````javascript
    calculateDefaultProjectName(cwd, projects, nxJson) {
        console.log(nxJson)
        const relativeCwd = this.relativeCwd(cwd);
        if (relativeCwd) {
            const matchingProject = Object.keys(projects.projects).find((p) => {
                const projectRoot = projects.projects[p].root;
                return (relativeCwd == projectRoot ||
                    relativeCwd.startsWith(`${projectRoot}/`));
            });
            if (matchingProject)
                return matchingProject;
        }
        return nxJson.defaultProject
    }
````

TypeError: Cannot read properties of undefined (reading 'defaultProject')

`CalculateDefaultProjectName` generates an error when nxJson is undefined.

### Expected Behavior

I think, it will be...
````javascript
    calculateDefaultProjectName(cwd, projects, nxJson) {
        console.log(nxJson)
        const relativeCwd = this.relativeCwd(cwd);
        if (relativeCwd) {
            const matchingProject = Object.keys(projects.projects).find((p) => {
                const projectRoot = projects.projects[p].root;
                return (relativeCwd == projectRoot ||
                    relativeCwd.startsWith(`${projectRoot}/`));
            });
            if (matchingProject)
                return matchingProject;
        }
        return nxJson?.defaultProject ?? "";
    }
````

### Steps to Reproduce

1. npm publish via ngx-deploy-npm 

### Nx Report

```shell
Node : 18.12.1
   OS   : darwin arm64
   pnpm : 7.18.1
   
   nx : 15.6.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.6.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.0
   @nrwl/js : 15.6.0
   @nrwl/linter : 15.6.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.6.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.6.0
   @nrwl/web : 15.6.0
   @nrwl/webpack : 15.6.0
   @nrwl/workspace : 15.6.0
   @nrwl/vite : Not Found
   typescript : 4.9.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @jscutlery/semver: 2.29.3
         lerna: 6.4.1
         ngx-deploy-npm: 4.3.10
```

**Comment by patzj** [comment]
Try to use the latest `nx` version in your project dependencies.

**Comment by matheushf** [comment]
Downgrading to `"nx": "15.0.3"` fixed it for me

**Comment by miguelmoreba** [comment]
I'm experiencing this as well.

For me, it only happens during the first run of

`npx nx affected --base=last-release --target=version  --parallel=1`

after a change in one or many of the projects

subsequent runs come back fine

**Comment by miguelmoreba** [comment]
> ### Current Behavior
> 
> ```js
>     calculateDefaultProjectName(cwd, projects, nxJson) {
>         console.log(nxJson)
>         const relativeCwd = this.relativeCwd(cwd);
>         if (relativeCwd) {
>             const matchingProject = Object.keys(projects.projects).find((p) => {
>                 const projectRoot = projects.projects[p].root;
>                 return (relativeCwd == projectRoot ||
>                     relativeCwd.startsWith(`${projectRoot}/`));
>             });
>             if (matchingProject)
>                 return matchingProject;
>         }
>         return nxJson.defaultProject
>     }
> ```
> 
> TypeError: Cannot read properties of undefined (reading 'defaultProject')
> 
> `CalculateDefaultProjectName` generates an error when nxJson is undefined.
> ### Expected Behavior
> 
> I think, it will be...
> 
> ```js
>     calculateDefaultProjectName(cwd, projects, nxJson) {
>         console.log(nxJson)
>         const relativeCwd = this.relativeCwd(cwd);
>         if (relativeCwd) {
>             const matchingProject = Object.keys(projects.projects).find((p) => {
>                 const projectRoot = projects.projects[p].root;
>                 return (relativeCwd == projectRoot ||
>                     relativeCwd.startsWith(`${projectRoot}/`));
>             });
>             if (matchingProject)
>                 return matchingProject;
>         }
>         return nxJson?.defaultProject ?? "";
>     }
> ```
> 
> ### Github Repo
> 
> _No response_
> ### Steps to Reproduce
> 
>     1. npm publish via ngx-deploy-npm
> 
> 
> ### Nx Report
> 
> ```shell
> Node : 18.12.1
>    OS   : darwin arm64
>    pnpm : 7.18.1
>    
>    nx : 15.6.0
>    @nrwl/angular : Not Found
>    @nrwl/cypress : 15.6.0
>    @nrwl/detox : Not Found
>    @nrwl/devkit : 15.6.0
>    @nrwl/esbuild : Not Found
>    @nrwl/eslint-plugin-nx : 15.6.0
>    @nrwl/expo : Not Found
>    @nrwl/express : Not Found
>    @nrwl/jest : 15.6.0
>    @nrwl/js : 15.6.0
>    @nrwl/linter : 15.6.0
>    @nrwl/nest : Not Found
>    @nrwl/next : Not Found
>    @nrwl/node : Not Found
>    @nrwl/nx-cloud : Not Found
>    @nrwl/nx-plugin : Not Found
>    @nrwl/react : 15.6.0
>    @nrwl/react-native : Not Found
>    @nrwl/rollup : Not Found
>    @nrwl/schematics : Not Found
>    @nrwl/storybook : 15.6.0
>    @nrwl/web : 15.6.0
>    @nrwl/webpack : 15.6.0
>    @nrwl/workspace : 15.6.0
>    @nrwl/vite : Not Found
>    typescript : 4.9.4
>    ---------------------------------------
>    Local workspace plugins:
>    ---------------------------------------
>    Community plugins:
>          @jscutlery/semver: 2.29.3
>          lerna: 6.4.1
>          ngx-deploy-npm: 4.3.10
> ```
> 
> ### Failure Logs
> 
> _No response_
> ### Additional Information
> 
> _No response_



> ### Current Behavior
> 
> ```js
>     calculateDefaultProjectName(cwd, projects, nxJson) {
>         console.log(nxJson)
>         const relativeCwd = this.relativeCwd(cwd);
>         if (relativeCwd) {
>             const matchingProject = Object.keys(projects.projects).find((p) => {
>                 const projectRoot = projects.projects[p].root;
>                 return (relativeCwd == projectRoot ||
>                     relativeCwd.startsWith(`${projectRoot}/`));
>             });
>             if (matchingProject)
>                 return matchingProject;
>         }
>         return nxJson.defaultProject
>     }
> ```
> 
> TypeError: Cannot read properties of undefined (reading 'defaultProject')
> 
> `CalculateDefaultProjectName` generates an error when nxJson is undefined.
> ### Expected Behavior
> 
> I think, it will be...
> 
> ```js
>     calculateDefaultProjectName(cwd, projects, nxJson) {
>         console.log(nxJson)
>         const relativeCwd = this.relativeCwd(cwd);
>         if (relativeCwd) {
>             const matchingProject = Object.keys(projects.projects).find((p) => {
>                 const projectRoot = projects.projects[p].root;
>                 return (relativeCwd == projectRoot ||
>                     relativeCwd.startsWith(`${projectRoot}/`));
>             });
>             if (matchingProject)
>                 return matchingProject;
>         }
>         return nxJson?.defaultProject ?? "";
>     }
> ```
> 
> ### Github Repo
> 
> _No response_
> ### Steps to Reproduce
> 
>     1. npm publish via ngx-deploy-npm
> 
> 
> ### Nx Report
> 
> ```shell
> Node : 18.12.1
>    OS   : darwin arm64
>    pnpm : 7.18.1
>    
>    nx : 15.6.0
>    @nrwl/angular : Not Found
>    @nrwl/cypress : 15.6.0
>    @nrwl/detox : Not Found
>    @nrwl/devkit : 15.6.0
>    @nrwl/esbuild : Not Found
>    @nrwl/eslint-plugin-nx : 15.6.0
>    @nrwl/expo : Not Found
>    @nrwl/express : Not Found
>    @nrwl/jest : 15.6.0
>    @nrwl/js : 15.6.0
>    @nrwl/linter : 15.6.0
>    @nrwl/nest : Not Found
>    @nrwl/next : Not Found
>    @nrwl/node : Not Found
>    @nrwl/nx-cloud : Not Found
>    @nrwl/nx-plugin : Not Found
>    @nrwl/react : 15.6.0
>    @nrwl/react-native : Not Found
>    @nrwl/rollup : Not Found
>    @nrwl/schematics : Not Found
>    @nrwl/storybook : 15.6.0
>    @nrwl/web : 15.6.0
>    @nrwl/webpack : 15.6.0
>    @nrwl/workspace : 15.6.0
>    @nrwl/vite : Not Found
>    typescript : 4.9.4
>    ---------------------------------------
>    Local workspace plugins:
>    ---------------------------------------
>    Community plugins:
>          @jscutlery/semver: 2.29.3
>          lerna: 6.4.1
>          ngx-deploy-npm: 4.3.10
> ```
> 
> ### Failure Logs
> 
> _No response_
> ### Additional Information
> 
> _No response_

I tried the proposed solution (manually substituting the code in `node_modules` and it seems to kick the error further along:

`[shared-ui] 🆕 Calculated new version "0.1.0".
[shared-ui] 📜 Generated CHANGELOG.md.
[shared-ui] 📝 Updated package.json version.
[shared-ui] 📦 Committed "chore(shared-ui): release version 0.1.0".
[shared-ui] 🔖 Tagged "shared-ui-0.1.0".
[shared-ui] ❌ [object Object]`

**Comment by XIshArkIX** [comment]
Saw same issue, but in pre-commit husky hook.

I researched how `nx lint` (`nx run <project>:lint`) works and here some notes:
- Looks like husky uses own shell, so in my case i have `cwd` = `C:\Users\roman\Documents\test-project` in **Powershell** and `cwd` = `c:\Users\roman\Documents\test-project` in **husky shell**.
- It leads to buggy code at `node_modules/nx/src/command-line/run-one.js` in function `calculateDefaultProjectName`, so `relativeCwd` contains only one element.

Here my workaround:
Get project directory by running `node -p 'process.cwd()'`
In `package.json` add to start of the `lint` script `cross-env NX_WORKSPACE_ROOT_PATH=<project_directory> ...`
Bad thing here is that these steps need to be unique for every member of your team.

**Comment by FrozenPandaz** [comment]
Closed with https://github.com/nrwl/nx/pull/15432
