### ISSUE TITLE
NX expo create new app issue

### ISSUE THREAD

**Issue by satheshsat** [nrwl/nx#14597]
### Current Behavior

npx nx g @nrwl/expo:app expo-mvp --verbose

>  NX  Generating @nrwl/expo:application

 >  NX   Cannot parse apps\expo-mvp\package.json: InvalidEscapeCharacter in JSON at 14:30

   ...
   11:     "react-native-web": "*"
   12:   },
   13:   "scripts": {
   14:     "eas-build-pre-install": "cd ../../ && cp package-lock.json ./apps\expo-mvp/",
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ InvalidEscapeCharacter
   15:     "postinstall": "rm -r node_modules && cd ../../ && npm install && npx nx sync-deps expo-mvp && npx nx ensure-symlink expo-mvp"
   16:   }
   17: }
   ...

Error: Cannot parse apps\expo-mvp\package.json: InvalidEscapeCharacter in JSON at 14:30
...
11:     "react-native-web": "*"
12:   },
13:   "scripts": {
14:     "eas-build-pre-install": "cd ../../ && cp package-lock.json ./apps\expo-mvp/",
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ InvalidEscapeCharacter
15:     "postinstall": "rm -r node_modules && cd ../../ && npm install && npx nx sync-deps expo-mvp && npx nx ensure-symlink expo-mvp"
16:   }
17: }
...

### Expected Behavior

Expected: greate the new app

### Steps to Reproduce

1. Create workspace with nestjs
2. Create new expo app

### Nx Report

```shell
Node : 18.13.0
   OS   : win32 x64
   npm  : 9.3.1

   nx : 15.2.1
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : 15.6.2
   @nrwl/devkit : 15.2.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.1
   @nrwl/expo : 15.6.2
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.1
   @nrwl/js : 15.2.1
   @nrwl/linter : 15.2.1
   @nrwl/nest : 15.2.1
   @nrwl/next : Not Found
   @nrwl/node : 15.2.1
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.6.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.2.1
   @nrwl/workspace : 15.2.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Additional Information

"dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.0.0",
    "tslib": "^2.3.0"
  },
  "devDependencies": {
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@nrwl/cli": "15.2.1",
    "@nrwl/eslint-plugin-nx": "15.2.1",
    "@nrwl/expo": "^15.6.2",
    "@nrwl/jest": "15.2.1",
    "@nrwl/linter": "15.2.1",
    "@nrwl/nest": "15.2.1",
    "@nrwl/node": "15.2.1",
    "@nrwl/nx-cloud": "latest",
    "@nrwl/workspace": "15.2.1",
    "@types/jest": "28.1.1",
    "@types/node": "18.7.1",
    "@typescript-eslint/eslint-plugin": "^5.36.1",
    "@typescript-eslint/parser": "^5.36.1",
    "eslint": "~8.15.0",
    "eslint-config-prettier": "8.1.0",
    "jest": "28.1.1",
    "jest-environment-jsdom": "28.1.1",
    "nx": "15.2.1",
    "prettier": "^2.6.2",
    "ts-jest": "28.0.5",
    "ts-node": "10.9.1",
    "typescript": "~4.8.2"
  }

**Comment by xiongemi** [comment]
i could not replicate this issue with latest nx. closing it for now.
