### ISSUE TITLE
wrapAngularDevkitSchematic('@nrwl/angular', 'library') does not work in nx 15

### ISSUE THREAD

**Issue by Lightw3ight** [nrwl/nx#14594]
### Current Behavior

When I create a custom plugin that in turn composes the angular library generator, I get the following error.

`Path "/libs/hello-world/.browserslistrc" does not exist.`

The full stack trace is as follows:

[NX] Angular devkit readJsonWorkspace fell back to Nx workspaces logic
Project 'my-plugin-e2e' contains extension with invalid name (files).
Project 'my-app-e2e' contains extension with invalid name (files).
Project 'my-plugin' contains extension with invalid name (files).
Project 'my-app' contains extension with invalid name (files).
[NX] Angular devkit readJsonWorkspace fell back to Nx workspaces logic
Project 'my-plugin-e2e' contains extension with invalid name (files).
Project 'my-app-e2e' contains extension with invalid name (files).
Project 'my-plugin' contains extension with invalid name (files).
Project 'my-app' contains extension with invalid name (files).
[NX] Angular devkit called `writeWorkspace`, this may have created 'workspace.json' or 'angular.json
[NX] Double check workspace configuration before proceeding
Project 'my-plugin-e2e' contains extension with invalid name (files).
Project 'my-app-e2e' contains extension with invalid name (files).
Project 'my-plugin' contains extension with invalid name (files).
Project 'my-app' contains extension with invalid name (files).
FileDoesNotExistException [Error]: Path "/libs/hello-world/.browserslistrc" does not exist.
    at SwitchMapSubscriber.project (C:\packages\angular_devkit\core\src\virtual-fs\host\record.ts:276:31)
    at SwitchMapSubscriber._next (C:\projects\myorg\node_modules\@angular-devkit\core\node_modules\rxjs\src\internal\operators\switchMap.ts:121:21)
    at SwitchMapSubscriber.Subscriber.next (C:\projects\myorg\node_modules\@angular-devkit\core\node_modules\rxjs\src\internal\Subscriber.ts:99:12)
    at C:\projects\myorg\node_modules\rxjs\src\internal\operators\switchMap.ts:115:42
    at OperatorSubscriber._this._next (C:\projects\myorg\node_modules\rxjs\src\internal\operators\OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (C:\projects\myorg\node_modules\rxjs\src\internal\Subscriber.ts:75:12)
    at SafeSubscriber.__tryOrUnsub (C:\projects\myorg\node_modules\@angular-devkit\core\node_modules\rxjs\src\internal\Subscriber.ts:265:10)
    at SafeSubscriber.next (C:\projects\myorg\node_modules\@angular-devkit\core\node_modules\rxjs\src\internal\Subscriber.ts:207:14)
    at Subscriber._next (C:\projects\myorg\node_modules\@angular-devkit\core\node_modules\rxjs\src\internal\Subscriber.ts:139:22)
    at Subscriber.next (C:\projects\myorg\node_modules\@angular-devkit\core\node_modules\rxjs\src\internal\Subscriber.ts:99:12)

### Expected Behavior

It should create an angular library

### Steps to Reproduce

1. `npx create-nx-workspace@latest myorg --preset=angular-monorepo --app-name=my-app --style=scss --nx-cloud`
2. Change directory to the new monorepo `myorg`
3. `npm install -D @nrwl/nx-plugin@latest`
4. `nx g @nrwl/nx-plugin:plugin my-plugin`
5. `nx g @nrwl/nx-plugin:generator my-generator --project=my-plugin`
6. Edit the file `libs\my-plugin\src\generators\my-generator\generator.ts` and replace its contents with the following code
```
import { formatFiles, Tree } from '@nrwl/devkit';
import { wrapAngularDevkitSchematic } from '@nrwl/devkit/ngcli-adapter';

export default async function (tree: Tree) {
  const libraryGenerator = wrapAngularDevkitSchematic(
    '@nrwl/angular',
    'library'
  );
  await libraryGenerator(tree, {
    name: 'hello-world',
  });
  await formatFiles(tree);
}
```
7. `nx generate @myorg/my-plugin:my-generator mylib --dry-run`

### Nx Report

```shell
Node : 16.18.1
   OS   : win32 x64
   npm  : 8.19.2

   nx : 15.6.2
   @nrwl/angular : 15.6.2
   @nrwl/cypress : 15.6.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.2
   @nrwl/js : 15.6.2
   @nrwl/linter : 15.6.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : 15.6.2
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.2
   @nrwl/workspace : 15.6.2
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
         @myorg/my-plugin
   ---------------------------------------
   Community plugins:
```

### Additional Information

I actually get a completely different error in our companies main monorepo.

When I try and run my custom generator, I get the following output
```
[NX] Angular devkit readJsonWorkspace fell back to Nx workspaces logic
Project 'xyz' contains extension with invalid name (files). (repeated for every project in the monorepo)
[NX] Angular devkit called `writeWorkspace`, this may have had unintended consequences in angular.json
[NX] Double check angular.json before proceeding
```
Then the console hangs, never to complete.

When trying to replicate this error in a brand new monorepo, I get the error I have reported above

**Comment by Coly010** [comment]
I think the issue here is that you're trying to wrap an Nx Generator as though it were an Angular Schematic.

You don't need to wrap a call to `@nrwl/angular:library` as it is already a generator, you can just call it as a function:

```ts
import { formatFiles, Tree } from '@nrwl/devkit';
import { libraryGenerator } from '@nrwl/angular';

export default async function (tree: Tree) {
  
  await libraryGenerator(tree, {
    name: 'hello-world',
  });
  await formatFiles(tree);
}
```

**Comment by Lightw3ight** [comment]
> ```ts
> import { libraryGenerator } from '@nrwl/angular';
> ```

`libraryGenerator` is not exported from `@nrwl/angular`

In the past, the docs have said to use `wrapAngularDevkitSchematic` to access to lib/app generators

**Comment by leosvelperez** [comment]
hey @Lightw3ight!

> `libraryGenerator` is not exported from `@nrwl/angular`

That was a typo, please import it from `@nrwl/angular/generators`.

> In the past, the docs have said to use `wrapAngularDevkitSchematic` to access to lib/app generators

I see an example of such a conversion in our current docs that needs to be corrected. I've created a PR to address it https://github.com/nrwl/nx/pull/14716.

The `wrapAngularDevkitSchematic` is a utility to allow Nx DevKit generators to invoke Angular CLI schematics. The `@nrwl/angular` generators are already using the Nx DevKit, and therefore, they don't need to be converted.

**Comment by leosvelperez** [comment]
I'm going to close this. If you still have issues after using the generator directly, please don't hesitate to reopen the issue or leave a comment.
