### ISSUE TITLE
Extra type definitions required when using nrwl/workspace schematic utils

### ISSUE THREAD

**Issue by emilio-martinez** [nrwl/nx#1460]
## Expected Behavior

To be able to use the utils within `@nrwl/workspace` ideally without having to install extra type definitions, if at all avoidable. This perhaps would require making some type definitions such as `@types/yargs` and `@types/prettier`  dependencies of `@nrwl/workspace`, but not sure if that's a great idea—looking for your thoughts, see below.

## Current Behavior

This is not really a bug, but maybe an inconvenience?

When working with workspace schematics, using the utilities exposed by `@nrwl/workspace`, e.g., `formatFiles`, `getNpmScope`, `readJsonInTree`, will result in the error below (see failure logs). This can be avoided by performing deep imports such as `import { readJsonInTree } from '@nrwl/workspace/src/utils/ast-utils';`, which isn't convenient but certainly doable. Currently, I'm using this last approach to avoid installing the extra type defs. 

### Context

Please provide any relevant information about your setup:

- Nx version: `8.1.0`
- Angular CLI version: `8.0.1`

In terms of usage, this will occur when running any workspace schematic making use of imports within `@nrwl/workspace` such as `import { formatFiles, getNpmScope, readJsonInTree } from '@nrwl/workspace';`.

### Failure Logs

```sh
> npx nx workspace-schematic schematic-name
 
node_modules/@nrwl/workspace/src/command-line/affected.d.ts:1:24 - error TS7016: Could not find a declaration file for module 'yargs'. '/path/to/project/dole-front/node_modules/@nrwl/workspace/node_modules/yargs/index.js' implicitly has an 'any' type.
  Try `npm install @types/yargs` if it exists or add a new declaration (.d.ts) file containing `declare module 'yargs';`

1 import * as yargs from 'yargs';
                         ~~~~~~~

node_modules/@nrwl/workspace/src/command-line/nx-commands.d.ts:2:24 - error TS7016: Could not find a declaration file for module 'yargs'. '/path/to/project/dole-front/node_modules/@nrwl/workspace/node_modules/yargs/index.js' implicitly has an 'any' type.
  Try `npm install @types/yargs` if it exists or add a new declaration (.d.ts) file containing `declare module 'yargs';`

2 import * as yargs from 'yargs';
                         ~~~~~~~

node_modules/@nrwl/workspace/src/utils/common.d.ts:1:25 - error TS7016: Could not find a declaration file for module 'prettier'. '/path/to/project/dole-front/node_modules/@nrwl/workspace/node_modules/prettier/index.js' implicitly has an 'any' type.
  Try `npm install @types/prettier` if it exists or add a new declaration (.d.ts) file containing `declare module 'prettier';`

1 import { Options } from 'prettier';
                          ~~~~~~~~~~


Found 6 errors.
```

**Comment by jadams88** [comment]
I actually think this should be put down as a bug. `noImplicitAny` (or `strict`) seems to expose this pretty often.
 
TypeScript seems pretty clear cut on this and that and declarations that are exposed and are not bundled with the external package should be under dependencies and not a devDependencies.

Relevant TypeScript docs.

[Publishing Dependencies](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies)

**Comment by jadams88** [comment]
On closer look it might not be as simple as above.

I was going to submit a PR but on closer look I can see that prettier is under **peerDependencies** and isn't part of the workspace package.

I have prettier installed but is run as a git hook with with "pretty-quick" for staged files and that's possible why I have not been bitten by this before.

My workaround right now is to set `strict: false` in `tsconfig.tools.json`

**Comment by jaysoo** [comment]
@jadams88 What complications did you run into? 

@FrozenPandaz @vsavkin Perhaps defaulting to `strict: false` is a workaround for now?

**Comment by jadams88** [comment]
@jaysoo If I have `strict: true` set in `tsconfig.tools.json`, when I run a workspace schematic I get the following

```bash
node_modules/@nrwl/workspace/src/utils/common.d.ts:1:25 - error TS7016 Could not find a declaration file for module 'prettier'. 'C:/ ... /node_modules/prettier/index.js' implicitly has an 'any' type.
  Try `npm install @types/prettier` if it exists or add a new declaration (.d.ts) file containing `declare module 'prettier';`

1 import { Options } from 'prettier';
```
 
My setup is that I use `prettier` and `pretty-quick` along with `lint-staged` to format all staged files with pre-commit git hook. The relevant `package.json` fields are below

```json
  "scripts": {
    "format:fix": "pretty-quick --staged",
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run lint-staged"
    }
  },
  "lint-staged": {
    "*.ts": [
      "npm run format:fix"
    ]
  },
  "devDependencies":{
    "prettier": "^1.19.1",
    "pretty-quick": "^2.0.1"
  }
```

I think the issue I'm facing is because I don't use prettier programmatically the combination of `strict: true` and no type definitions does not present an issues but the schematic throws an error because it satisfies the peerDependencies.

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.
