### ISSUE TITLE
Not able to create an nx workspace with npx-create-nx-workspace

### ISSUE THREAD

**Issue by codecusp** [nrwl/nx#1461]
## Expected Behavior

Successfully create NX workspace

## Current Behavior

```
PS D:\angular-projects\angular-advanced> npx create-nx-workspace myworkspace
npx: installed 53 in 5.584s
Creating a sandbox with Nx...
[--------------------------------------------------------------------------------------------] 3/609ng new "myworkspace" --collection=@nrwl/workspace
The system cannot find the path specified.
Command failed: "C:\Users\arind\AppData\Local\Temp\tmp-15508MdhdSygkVDBL\node_modules\.bin\ng" new "myworkspace" --collection=@nrwl/workspace
```

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. ...

### Context

Please provide any relevant information about your setup:

```
Angular CLI: 8.0.1
Node: 10.16.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.800.1
@angular-devkit/core         8.0.1
@angular-devkit/schematics   8.0.1
@schematics/angular          8.0.1
@schematics/update           0.800.1
rxjs  
```

 I watched all the related issues and each of them seems to be closed and still am not able to do such a basic thing! Please help! I am really excited about nx.

**Comment by FrozenPandaz** [comment]
Thanks for reporting this issue.

I cannot seem to replicate this issue. It seems like you are on Windows. I tried to replicate on windows and could not replicate. There's nothing suspicious about your path.

Can you try the following and see if it works?
```sh
npx create-nx-workspace@latest myworkspace
```

**Comment by codecusp** [comment]
Thanks @FrozenPandaz

**Comment by FrozenPandaz** [comment]
It seems like that fixed the issue. Let us know if you continue running into this issue.

**Comment by ruslanguns** [comment]
In my case I noticed that the npm cache route was broken (my HOME directory has my firstname and my lastname, so the space between the names broke the configuration path), the way I fixed it was by reinstalling NodeJs just after cleaning all AppData cache data and changing the installation folder into another shorter. D:\\NodeJs\
