### ISSUE TITLE
Installing @nrwl/workspace fails with camel-cased Angular app names

### ISSUE THREAD

**Issue by jonr-elsewhen** [nrwl/nx#1463]
## Expected Behavior

If my Angular app has a camel-cased name, e.g. "myFunkyApp", it should be possible to install Nx workspace to it:

```
ng new myFunkyApp
cd myFunkyApp
ng add @nrwl/workspace
```

## Current Behavior

Fails with error:

```
Cannot read property 'architect' of undefined
```

## Failure Information (for bugs)

The problem seems to be happening because the ng-add schematic converts the schema name to kebab-case here: https://github.com/nrwl/nx/blob/master/packages/workspace/src/schematics/ng-add/ng-add.ts#L547

It then tries to use the kebab-cased name as a key into the angular.json projects here: https://github.com/nrwl/nx/blob/master/packages/workspace/src/schematics/ng-add/ng-add.ts#L369

### Steps to Reproduce

```
ng new myFunkyApp
cd myFunkyApp
ng add @nrwl/workspace
```

### Context

Please provide any relevant information about your setup:

Nx: 8.1.0
Angular CLI: 8

### Failure Logs

```
Installing packages for tooling via npm.
+ @nrwl/workspace@8.1.0
added 53 packages from 36 contributors and audited 19200 packages in 5.195s
found 0 vulnerabilities

Installed packages for tooling via npm.
Cannot read property 'architect' of undefined
```

**Comment by roksanaaghajanpoor** [comment]
I want to Add Nx to an Existing Angular CLI workspace, but when run 'ng add @nrwl/workspace' command, this error will occur:

Skipping installation: Package already installed
Cannot read property 'architect' of undefined

how to solve this issue?
Thank you
