### ISSUE TITLE
Cannot build multiple apps in same Nx workpace

### ISSUE THREAD

**Issue by rpspall** [nrwl/nx#14643]
### Current Behavior

TWO React applications living in the same Nx workspace with 3 shared libs.. When I try and build one followed by the other (production or development build), only the first one successfully builds! The second one does not generate its build artifacts in the dist\apps folder

### Expected Behavior

Would expect to be able to build either application in any order

### Steps to Reproduce

Assume Application 1 called app1 and Application 2 called app2 - both react applications

1. Delete contents of \dist folder
2. Build app1 "npx nx build app1 --configuration=production --verbose"
- Successfully builds the app1 into \dist\apps\app1 and I can successfully deploy the artifacts or access from a local webserver
3. Build app2 "npx nx build app2 --configuration=production --verbose"
- Build completes with errors and no dist\apps\app2 folder created

I can also reverse the steps with the same effect:

1. Delete contents of \dist folder
2. Build app2 "npx nx build app2 --configuration=production --verbose"
- Successfully builds the app2 into \dist\apps\app2 and I can successfully deploy the artifacts or access from a local webserver
3. Build app1 "npx nx build app1 --configuration=production --verbose"
- Build completes with errors and no dist\apps\app1 folder created

### Nx Report

```shell
N/A
```

### Failure Logs

```shell
PS D:\workspaces\Yamaha\BusinessConnectReact> npx nx build ydsus --configuration=production --verbose

 >  NX   Running target build for project ydsus and 1 task it depends on:

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

> nx run ydsus:build:production  [local cache]

assets by info 1.67 MiB [immutable]
  assets by path *.js 1.02 MiB 9 assets
  assets by chunk 664 KiB (auxiliary name: main)
    assets by path *.jpg 546 KiB 3 assets
    + 3 assets
  assets by path *.css 0 bytes
    asset main.ef46db3751d8e999.css 0 bytes [emitted] [immutable] [minimized] (name: main)
    asset styles.ef46db3751d8e999.css 0 bytes [emitted] [immutable] [minimized] (name: styles)
assets by path assets/ 130 bytes
  asset assets/CVS/Repository 44 bytes [emitted] [from: src/assets/CVS/Repository] [copied]
  asset assets/CVS/Root 44 bytes [emitted] [from: src/assets/CVS/Root] [copied]
  asset assets/CVS/Entries 42 bytes [emitted] [from: src/assets/CVS/Entries] [copied]
  asset assets/.gitkeep 0 bytes [emitted] [from: src/assets/.gitkeep] [copied]
asset 3rdpartylicenses.txt 56.6 KiB [emitted]
asset favicon.ico 14.7 KiB [emitted] [from: src/favicon.ico] [copied]
Entrypoint main [big] 578 KiB (664 KiB) = runtime.b19927a45d1a3064.js 3.62 KiB main.ef46db3751d8e999.css 0 bytes main.0cf75affb2215440.js 574 KiB 6 auxiliary assets
Entrypoint polyfills 103 KiB = runtime.b19927a45d1a3064.js 3.62 KiB polyfills.e3bc8663cbd48311.js 99.2 KiB
Entrypoint styles 3.62 KiB = runtime.b19927a45d1a3064.js 3.62 KiB styles.ef46db3751d8e999.css 0 bytes

webpack 5.75.0 compiled successfully (af18709fa305f6d4)

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Successfully ran target build for project ydsus and 1 task it depends on

   Nx read the output from the cache instead of running the command for 2 out of 2 tasks.

PS D:\workspaces\Yamaha\BusinessConnectReact> npx nx build ydsca --configuration=production --verbose

 >  NX   Running target build for project ydsca and 2 tasks it depends on:

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

> nx run common-utils:build

Compiling TypeScript files for project "common-utils"...
Done compiling TypeScript files for project "common-utils".

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Successfully ran target build for project ydsca and 2 tasks it depends on



 >  NX   Failed to start or connect to the Nx Daemon process.


   Messages from the log:
   [NX Daemon Server] - 2023-01-26T14:36:55.052Z - [REQUEST]: Client Request for Project Graph Received
   [NX Daemon Server] - 2023-01-26T14:36:55.052Z - [REQUEST]: Responding to the client. project-graph
   [NX Daemon Server] - 2023-01-26T14:36:55.055Z - Time taken for 'total for creating and serializing project graph' 233.45080000162125ms
   [NX Daemon Server] - 2023-01-26T14:36:55.059Z - [REQUEST]: Client Request for Project Graph Received
   [NX Daemon Server] - 2023-01-26T14:36:55.060Z - [REQUEST]: Responding to the client. project-graph
   [NX Daemon Server] - 2023-01-26T14:36:55.069Z - Done responding to the client project-graph
   [NX Daemon Server] - 2023-01-26T14:36:55.069Z - Time taken for 'total for creating and serializing project graph' 0.403700053691864ms
   [NX Daemon Server] - 2023-01-26T14:36:55.069Z - Closed a connection. Number of open connections: 5
   [NX Daemon Server] - 2023-01-26T14:36:55.069Z - Closed a connection. Number of open connections: 4
   [NX Daemon Server] - 2023-01-26T14:36:55.069Z - Done responding to the client project-graph
   [NX Daemon Server] - 2023-01-26T14:36:55.070Z - Done responding to the client project-graph
   [NX Daemon Server] - 2023-01-26T14:36:55.070Z - Closed a connection. Number of open connections: 3
   [NX Daemon Server] - 2023-01-26T14:36:55.346Z - Established a connection. Number of open connections: 4
   [NX Daemon Server] - 2023-01-26T14:36:55.346Z - Established a connection. Number of open connections: 5
   [NX Daemon Server] - 2023-01-26T14:36:55.349Z - [REQUEST]: Client Request for Project Graph Received
   [NX Daemon Server] - 2023-01-26T14:36:55.349Z - [REQUEST]: Responding to the client. project-graph
   [NX Daemon Server] - 2023-01-26T14:36:55.352Z - Time taken for 'total for creating and serializing project graph' 0.15070003271102905ms
   [NX Daemon Server] - 2023-01-26T14:36:55.352Z - Closed a connection. Number of open connections: 4
   [NX Daemon Server] - 2023-01-26T14:36:55.352Z - Done responding to the client project-graph



   More information: D:\workspaces\Yamaha\BusinessConnectReact\node_modules\.cache\nx\d\daemon.log

Error: Failed to start or connect to the Nx Daemon process.

Messages from the log:
[NX Daemon Server] - 2023-01-26T14:36:55.052Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-01-26T14:36:55.052Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2023-01-26T14:36:55.055Z - Time taken for 'total for creating and serializing project graph' 233.45080000162125ms
[NX Daemon Server] - 2023-01-26T14:36:55.059Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-01-26T14:36:55.060Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2023-01-26T14:36:55.069Z - Done responding to the client project-graph
[NX Daemon Server] - 2023-01-26T14:36:55.069Z - Time taken for 'total for creating and serializing project graph' 0.403700053691864ms
[NX Daemon Server] - 2023-01-26T14:36:55.069Z - Closed a connection. Number of open connections: 5
[NX Daemon Server] - 2023-01-26T14:36:55.069Z - Closed a connection. Number of open connections: 4
[NX Daemon Server] - 2023-01-26T14:36:55.069Z - Done responding to the client project-graph
[NX Daemon Server] - 2023-01-26T14:36:55.070Z - Done responding to the client project-graph
[NX Daemon Server] - 2023-01-26T14:36:55.070Z - Closed a connection. Number of open connections: 3
[NX Daemon Server] - 2023-01-26T14:36:55.346Z - Established a connection. Number of open connections: 4
[NX Daemon Server] - 2023-01-26T14:36:55.346Z - Established a connection. Number of open connections: 5
[NX Daemon Server] - 2023-01-26T14:36:55.349Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-01-26T14:36:55.349Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2023-01-26T14:36:55.352Z - Time taken for 'total for creating and serializing project graph' 0.15070003271102905ms
[NX Daemon Server] - 2023-01-26T14:36:55.352Z - Closed a connection. Number of open connections: 4
[NX Daemon Server] - 2023-01-26T14:36:55.352Z - Done responding to the client project-graph



More information: D:\workspaces\Yamaha\BusinessConnectReact\node_modules\.cache\nx\d\daemon.log
    at daemonProcessException (D:\workspaces\Yamaha\BusinessConnectReact\node_modules\nx\src\daemon\client\client.js:307:23)
    at DaemonClient.<anonymous> (D:\workspaces\Yamaha\BusinessConnectReact\node_modules\nx\src\daemon\client\client.js:269:32)
    at Generator.next (<anonymous>)
    at fulfilled (D:\workspaces\Yamaha\BusinessConnectReact\node_modules\tslib\tslib.js:115:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
PS D:\workspaces\Yamaha\BusinessConnectReact>
```

### Additional Information

Below is contents of daemon.log for app1 followed by app2 buid:

[NX Daemon Server] - 2023-01-26T14:38:56.198Z - Started listening on: \\.\pipe\nx\C:\Users\ROGERS~1\AppData\Local\Temp\7df05826d66bf8e97aa2\d.sock
[NX Daemon Server] - 2023-01-26T14:38:57.268Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-01-26T14:38:57.269Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-01-26T14:38:57.270Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-01-26T14:38:57.270Z - [WATCHER]: Subscribed to changes within: D:\workspaces\Yamaha\BusinessConnectReact
[NX Daemon Server] - 2023-01-26T14:38:57.272Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-01-26T14:38:57.303Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-01-26T14:38:57.554Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2023-01-26T14:38:57.557Z - Time taken for 'total for creating and serializing project graph' 281.66780000925064ms
[NX Daemon Server] - 2023-01-26T14:38:57.557Z - Done responding to the client project-graph
[NX Daemon Server] - 2023-01-26T14:38:57.619Z - [REQUEST]: Responding to the client. outputsHashesMatch
[NX Daemon Server] - 2023-01-26T14:38:57.619Z - Done responding to the client outputsHashesMatch
[NX Daemon Server] - 2023-01-26T14:38:57.654Z - [REQUEST]: Responding to the client. recordOutputsHash
[NX Daemon Server] - 2023-01-26T14:38:57.654Z - Done responding to the client recordOutputsHash
[NX Daemon Server] - 2023-01-26T14:38:57.660Z - [REQUEST]: Responding to the client. outputsHashesMatch
[NX Daemon Server] - 2023-01-26T14:38:57.660Z - Done responding to the client outputsHashesMatch
[NX Daemon Server] - 2023-01-26T14:38:57.691Z - [REQUEST]: Responding to the client. recordOutputsHash
[NX Daemon Server] - 2023-01-26T14:38:57.691Z - Done responding to the client recordOutputsHash
[NX Daemon Server] - 2023-01-26T14:38:57.697Z - Closed a connection. Number of open connections: 0
[NX Daemon Server] - 2023-01-26T14:38:58.287Z - Started listening on: \\.\pipe\nx\C:\Users\ROGERS~1\AppData\Local\Temp\281ef335618b03f94be1\d.sock
[NX Daemon Server] - 2023-01-26T14:38:59.402Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-01-26T14:38:59.402Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-01-26T14:38:59.403Z - [WATCHER]: Subscribed to changes within: d:\workspaces\Yamaha\BusinessConnectReact
[NX Daemon Server] - 2023-01-26T14:38:59.406Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-01-26T14:38:59.427Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-01-26T14:38:59.648Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2023-01-26T14:38:59.651Z - Time taken for 'total for creating and serializing project graph' 241.97600001096725ms
[NX Daemon Server] - 2023-01-26T14:38:59.655Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-01-26T14:38:59.655Z - Done responding to the client project-graph
[NX Daemon Server] - 2023-01-26T14:38:59.938Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-01-26T14:38:59.938Z - Established a connection. Number of open connections: 3
[NX Daemon Server] - 2023-01-26T14:38:59.938Z - Closed a connection. Number of open connections: 2
[NX Daemon Server] - 2023-01-26T14:38:59.944Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-01-26T14:38:59.944Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2023-01-26T14:38:59.947Z - Time taken for 'total for creating and serializing project graph' 0.3295000195503235ms
[NX Daemon Server] - 2023-01-26T14:38:59.947Z - Done responding to the client project-graph
[NX Daemon Server] - 2023-01-26T14:39:46.162Z - Started listening on: \\.\pipe\nx\C:\Users\ROGERS~1\AppData\Local\Temp\7df05826d66bf8e97aa2\d.sock
[NX Daemon Server] - 2023-01-26T14:39:47.237Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-01-26T14:39:47.237Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-01-26T14:39:47.238Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-01-26T14:39:47.238Z - [WATCHER]: Subscribed to changes within: D:\workspaces\Yamaha\BusinessConnectReact
[NX Daemon Server] - 2023-01-26T14:39:47.241Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-01-26T14:39:47.268Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-01-26T14:39:47.532Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2023-01-26T14:39:47.535Z - Time taken for 'total for creating and serializing project graph' 291.428200006485ms
[NX Daemon Server] - 2023-01-26T14:39:47.537Z - Done responding to the client project-graph
[NX Daemon Server] - 2023-01-26T14:39:47.600Z - [REQUEST]: Responding to the client. outputsHashesMatch
[NX Daemon Server] - 2023-01-26T14:39:47.600Z - Done responding to the client outputsHashesMatch
[NX Daemon Server] - 2023-01-26T14:39:48.288Z - Started listening on: \\.\pipe\nx\C:\Users\ROGERS~1\AppData\Local\Temp\281ef335618b03f94be1\d.sock
[NX Daemon Server] - 2023-01-26T14:39:49.465Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-01-26T14:39:49.466Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-01-26T14:39:49.466Z - Established a connection. Number of open connections: 3
[NX Daemon Server] - 2023-01-26T14:39:49.466Z - Established a connection. Number of open connections: 4
[NX Daemon Server] - 2023-01-26T14:39:49.467Z - Established a connection. Number of open connections: 5
[NX Daemon Server] - 2023-01-26T14:39:49.467Z - [WATCHER]: Subscribed to changes within: d:\workspaces\Yamaha\BusinessConnectReact
[NX Daemon Server] - 2023-01-26T14:39:49.467Z - Established a connection. Number of open connections: 6
[NX Daemon Server] - 2023-01-26T14:39:49.471Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-01-26T14:39:49.491Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-01-26T14:39:49.702Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2023-01-26T14:39:49.710Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-01-26T14:39:49.710Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2023-01-26T14:39:49.713Z - Time taken for 'total for creating and serializing project graph' 231.33160001039505ms
[NX Daemon Server] - 2023-01-26T14:39:49.716Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-01-26T14:39:49.717Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2023-01-26T14:39:49.726Z - Done responding to the client project-graph
[NX Daemon Server] - 2023-01-26T14:39:49.726Z - Time taken for 'total for creating and serializing project graph' 0.29809999465942383ms
[NX Daemon Server] - 2023-01-26T14:39:49.726Z - Closed a connection. Number of open connections: 5
[NX Daemon Server] - 2023-01-26T14:39:49.726Z - Closed a connection. Number of open connections: 4
[NX Daemon Server] - 2023-01-26T14:39:49.727Z - Done responding to the client project-graph
[NX Daemon Server] - 2023-01-26T14:39:49.727Z - Done responding to the client project-graph
[NX Daemon Server] - 2023-01-26T14:39:49.727Z - Closed a connection. Number of open connections: 3
[NX Daemon Server] - 2023-01-26T14:39:49.987Z - Established a connection. Number of open connections: 4
[NX Daemon Server] - 2023-01-26T14:39:49.988Z - Established a connection. Number of open connections: 5
[NX Daemon Server] - 2023-01-26T14:39:49.991Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-01-26T14:39:49.991Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2023-01-26T14:39:49.994Z - Time taken for 'total for creating and serializing project graph' 0.21500003337860107ms
[NX Daemon Server] - 2023-01-26T14:39:49.994Z - Closed a connection. Number of open connections: 4
[NX Daemon Server] - 2023-01-26T14:39:49.994Z - Done responding to the client project-graph

**Comment by AgentEnder** [comment]
Its definitely weird that you are getting daemon errors. Can you get the output of `nx report` it should help us be able to provide more troubleshooting info and steps.

Additionally, since it is a daemon error showing up, can you try running with the daemon disabled temporarily? https://nx.dev/more-concepts/nx-daemon#turning-it-off

**Comment by rpspall** [comment]
Turning the deamon off fixed the issue...

To follow up with your request for nx report, I turned deamon back on, reran the steps to repeat the issue and nx report is below:

Node : 18.13.0
   OS   : win32 x64
   npm  : 9.1.3
   
   nx : 15.4.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.5
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.5
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.5
   @nrwl/js : 15.4.5
   @nrwl/linter : 15.4.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.5
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.5
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.4.5
   @nrwl/webpack : 15.4.5
   @nrwl/workspace : 15.4.5
   @nrwl/vite : 15.4.5
   typescript : 4.8.4

Out of curiosity what does the daemon do?

**Comment by AgentEnder** [comment]
A lot of times when folks have weird issues like this, it turns out they have some versions out of sync but they look good in your report.

Can you try migrating to the latest version and seeing if that helps? Its possible that a bug like this has been addressed.

**Comment by AgentEnder** [comment]
Its interesting, because I don't actually see any errors in the daemon log.

**Comment by rpspall** [comment]
That fixed it... Thank you.

I was running an older version because the image serving was broken, but checked and that bug is also fixed.
