### ISSUE TITLE
NX CLI dry-run with @nrwl/react:application not working as expected

### ISSUE THREAD

**Issue by ruslanguns** [nrwl/nx#14649]
### Current Behavior

Error when using --dry-run with @nrwl/react:application seems that the `--dry-run` option is not recognizing the installed dependencies.

### Expected Behavior

The command should generate the application without installing any dependencies.

### Steps to Reproduce

1. Run: `nx g  @nrwl/react:application myapp --no-interactive --dry-run`

### Nx Report

```shell
❯ nx report                                                     

 >  NX   Report complete - copy this into the issue template

   Node : 18.12.1
   OS   : linux x64
   pnpm : 7.25.1
   
   nx : 15.6.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.6.2
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : Not Found
   @nrwl/linter : 15.6.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.6.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.6.2
   @nrwl/vite : 15.6.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
>  NX  Generating @nrwl/react:application


 >  NX   Cannot install required package @nrwl/cypress during a dry run. Run the generator without --dryRun, or install the package with "pnpm add -D @nrwl/cypress@15.6.2" and try again.

   Pass --verbose to see the stacktrace.
```

### Additional Information

* Without the --dry-run it creates the application as expected.
* Unselecting Cypress from e2eTestRunner it also works as expected.

**Comment by jaysoo** [comment]
I'm not able to see this behavior. Can you provide a reproduction?

This is what I tested with: https://github.com/jaysoo/issue-14649

**Comment by ruslanguns** [comment]
I have been able to make it work by uninstalled the dev dependencies and everything has worked as expected. (Very strange)

Thanks for the support, apologize for the inconvenience, closing the issue.
