### ISSUE TITLE
Unit test for custom schematics fails with 'cannot find nx.json'

### ISSUE THREAD

**Issue by EvtK** [nrwl/nx#1464]
# Expected Behavior

I can run unit test for custom schematics, without getting errors that are related to the way I use the schematics testing framework.

## Current Behavior

We have some custom schematics for generating apps, libs, components etc. Nothing fancy in particular. I'm in the process of writing unit tests for these schematics, but I fail to succeed on this. While the actually schematic is running fine, I cannot get the unit test to work. 

### Steps to Reproduce

I have a basic schematic that is adding some sugar to generating a new app. I'm chaining on ''@nrwl/schematics', 'application''.

here is my test:

```
import { SchematicTestRunner, UnitTestTree } from '@angular-devkit/schematics/testing';
import * as path from 'path';

const collectionPath = path.join(__dirname, '../collection.json');

describe('funnel', () => {
  let runner: SchematicTestRunner;
  let workspaceTree: UnitTestTree;

  beforeEach(() => {
    runner = new SchematicTestRunner('funnel', collectionPath);
    workspaceTree = runner.runSchematic('funnel');
  });

it('should have done something', () => {
      const contents = workspaceTree.readContent('/angular.json');

// other content of the test left out
     
    });
```

it already fails on getting the workspaceTree. I get the following error:

```
Cannot find nx.json

      at Object.readJsonInTree (../../node_modules/@nrwl/schematics/src/utils/ast-utils.js:415:15)
      at Object.getNpmScope (../../node_modules/@nrwl/schematics/src/utils/cli-config-utils.js:19:24)
      at normalizeOptions (../../node_modules/@nrwl/schematics/src/collection/application/index.js:365:44)
      at ../../node_modules/@nrwl/schematics/src/collection/application/index.js:285:23

```
### Context
- version of Nx used: 7.8.6
- version of Angular CLI used: 7.1.0
- version of Angular DevKit used7.1.0

I'm sure I'm overlooking something :). Thanks for any suggestions.

**Comment by ZachJW34** [comment]
I recently finished writing unit tests for some custom schematics that we have at our organization. Have you tried extending `@nrwl/schematics` inside your `collection.json`?

**Comment by EvtK** [comment]
Hi ZachJW34, thanks for checking in. Yes I am extending the ``@nrwl/schematics` inside the `collection.json`.

This is my collection.json:

```
{
  "name": "@myrepo/schematics",
  "version": "0.1",
  "extends": "@nrwl/schematics",
    "funnel": {
      "factory": "./funnel/index#funnel",
      "schema": "./funnel/schema.json",
      "description": "Generates a new funnel"
    },
}
```

do you perhaps see anything misconfigured here?

**Comment by EvtK** [comment]
I think the problem lies in the fact that I'm chaining on `@nrwl/schematics` in the actual schematic:

```
return chain([
      externalSchematic('@nrwl/schematics', 'application', { })
]);

```
But it seems I'm not doing anything wrong here, since the actual schematic behaves normally. It only runs in errors, when firing the unit test.

**Comment by ZachJW34** [comment]
We also chain off of the application schematic. I see that your `collection.json` does not have the `schematic` property but I think that was a typo. Can you try adding a beforeEach similar to below?
```
let appTree: Tree;
beforeEach(() => {
  appTree = new VirtualTree();
  appTree = createEmptyWorkspace(appTree);
});
```

**Comment by vsavkin** [comment]
Sorry, but I'm going to close this issue.

Currently, we don't provide any utilities for testing schematics. So testing Nx-oriented schematics is no different than testing say default Angular schematics or NestJS schematics. So I think https://github.com/angular/angular-cli is a better place for such questions. 

Thank you.

**Comment by mehrad-rafigh** [comment]
Hi @ZachJW34 @EvtK @vsavkin 
I am experiencing the same issue one year later. How did you guys manage to get the tests working?

@vsavkin Maybe the documentation could be updated to add some sort of guidance on how to unit test custom schematics.

**Comment by EvtK** [comment]
I'm sorry to say that I actually never managed to fix it, so finally decided to remove the unit tests for the schematics.

**Comment by mehrad-rafigh** [comment]
Somewhat good news. I managed to get passed the cannot find nx.json Problem. But now I get **Cannot read property 'engineHost' of null** which comes from [here](https://github.com/nrwl/nx/blob/b55a1a96dd74fc1ecc209eb4f42959933102bd75/packages/workspace/src/schematics/shared-new/shared-new.ts#L113)
