### ISSUE TITLE
tslib missing from prod dependencies after upgrade to 15.0.10

### ISSUE THREAD

**Issue by frank-long** [nrwl/nx#14657]
### Current Behavior

tslib is added as a production dependency
after building the app, tslib is missing from the package.json of the built app
tslib is used by nx, in nx config, so I get an error:  'tslib not found' starting the app

  ```
const tslib_1 = require("tslib");
  function regexEqual(x, y) {
      return (x instanceof RegExp &&
          y instanceof RegExp &&
          x.source === y.source &&
          x.global === y.global &&
          x.ignoreCase === y.ignoreCase &&
          x.multiline === y.multiline);
```

Before upgrade, tslib used to be in the built app package.json, now it's present in the .pnpm folder

### Expected Behavior

tslib available in the production package.json

### Steps to Reproduce

1. Add tslib to a project
2.  Set "importHelpers": true, in tsconfig
3. Build the app
4. tslib is missing from the package.json file of the build app

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node : 16.19.0
OS   : linux x64
pnpm : 7.26.1

nx : 15.5.1
@nrwl/angular : Not Found
@nrwl/cypress : 15.5.1
@nrwl/detox : Not Found
@nrwl/devkit : 15.5.1
@nrwl/esbuild : Not Found
@nrwl/eslint-plugin-nx : 15.5.1
@nrwl/expo : Not Found
@nrwl/express : 15.5.1
@nrwl/jest : 15.5.1
@nrwl/js : 15.5.1
@nrwl/linter : 15.5.1
@nrwl/nest : Not Found
@nrwl/next : 15.5.1
@nrwl/node : 15.5.1
@nrwl/nx-cloud : 15.0.2
@nrwl/nx-plugin : Not Found
@nrwl/react : 15.5.1
@nrwl/react-native : Not Found
@nrwl/rollup : 15.5.1
@nrwl/schematics : Not Found
@nrwl/storybook : 15.5.1
@nrwl/web : 15.5.1
@nrwl/webpack : 15.5.1
@nrwl/workspace : 15.5.1
@nrwl/vite : 15.5.1
typescript : 4.8.4
---------------------------------------
Local workspace plugins:
      @onyx/local-plugins/ui-components
---------------------------------------
Community plugins:
      @mands/nx-playwright: 0.1.30
      nx-stylelint: 13.5.3       
```

### Additional Information

 "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2021",
    "module": "esnext",
    "lib": ["es2021", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "noEmit": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "strict": true,
    "incremental": true,
    "types": ["node", "jest", "@testing-library/jest-dom"],
    "resolveJsonModule": true,

**Comment by robstadnick** [comment]
Not helpful just adding some more wood to the fire that helps resolve this.

I've been having issues since NX 15+ off/on with it created the package.json with all the required dependancies. CI runs and all the sudden the containers are in crash loops because it can not book the application with missing packages.

**Comment by jbarmash** [comment]
I wonder this is related to this issue, which I think may be about pruning dependencies when generating package.json for an app. 

https://github.com/nrwl/nx/issues/14096
