### ISSUE TITLE
http-proxy-middleware configuration not working

### ISSUE THREAD

**Issue by rpspall** [nrwl/nx#14651]
### Current Behavior

Migrating an application from CRA to Nx...

Webpack supports advanced proxy configuration via its dependency on "http-proxy-middleware":

https://webpack.js.org/configuration/dev-server/
- search for "http-proxy-middleware":

Current application uses a setupProxy.js file in the root folder, and this is automatically loaded by http-proxy-middleware and provides advanced proxying configuration - it appears that webpack:dev-server already knows to look for and expect this file name!

After migrating the application to NX, the setupProxy.js file is placed in application root, but is not loaded:

<monorepo_root>\apps\<myappname>\setupProxy.js

Also tried

<monorepo_root>\apps\<myappname>\src\setupProxy.js
<monorepo_root>\apps\<myappname>\src\app\setupProxy.js

I can get basic proxying working with 

"proxyConfig": "apps/<appname>/proxy.conf.json"
- in project.json for application

Unfortunately, this doesn't provide the required capabilities. Forgive my lack of understanding, but I don't fully understand how @nrwl/webpack:dev-server relates to the real webpack. However, shouldn't webpack still be looking for and recognizing the setupProxy.js file under Nx?

Also tried installing "http-proxy-middleware" as a direct monorepo dependency (even though it is included as part of webpack), and still doesn't work.

Sample setupProxy.js file is attached (as a text file)
[setupProxy.txt](https://github.com/nrwl/nx/files/10513673/setupProxy.txt)

### Expected Behavior

Expected setupProxy.js file to be automatically picked up by webpack in the same way as a CRA application

### Steps to Reproduce

1.Copied setupProxy.js from old CRA project to multiple Nx application directories:
<monorepo_root>\apps\<myappname>\setupProxy.js
<monorepo_root>\apps\<myappname>\src\setupProxy.js
<monorepo_root>\apps\<myappname>\src\app\setupProxy.js

2.Restarted serve application

### Nx Report

```shell
Node : 18.13.0
   OS   : win32 x64
   npm  : 9.1.3

   nx : 15.4.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.5
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.5
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.5
   @nrwl/js : 15.4.5
   @nrwl/linter : 15.4.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.5
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.5
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.4.5
   @nrwl/webpack : 15.4.5
   @nrwl/workspace : 15.4.5
   @nrwl/vite : 15.4.5
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by lekhasy** [comment]
We're also migrating to NX, do we have any work around at the moment?

**Comment by rpspall** [comment]
You can get basic webpack proxying working with no issues....

Just add the usual proxy.conf.json file to your React apps/<appname> root folder and then add a proxyConfig statement to your application's project.json serve config:

"serve": {
      "executor": "@nrwl/webpack:dev-server",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "ydsca:build",
        "hmr": true,
        "ssl": true,
        "port": 4443,
        "baseHref": "/caconnect/",
        "sslKey": "certs/localhost.key.pem",
        "sslCert": "certs/localhost.crt.pem",
        **"proxyConfig": "apps/ydsca/proxy.conf.json"**
      },

I have not been able to get the more powerful http-proxy-middleware configuration to work - making do with proxy.conf.json just fine for now!
