### ISSUE TITLE
@nrlw/schematics missing tslint in v 8.1.0

### ISSUE THREAD

**Issue by appsolutegeek** [nrwl/nx#1469]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

The tslint file has the following

```
{
  "rulesDirectory": [
    "node_modules/@nrwl/schematics/src/tslint",
    "node_modules/codelyzer"
  ],
```

but my IDE complains that the schematics/src/tslint cannot be found and i checked,its not there

Has there been a change on v8.1.0 ???

### Context

Please provide any relevant information about your setup:

- version of Nx used 8
- version of Angular CLI 8

**Comment by appsolutegeek** [comment]
I presume that this is becasue I went to version 8 ? Its new location is where ?

**Comment by FrozenPandaz** [comment]
If you updated with `yarn update` or `ng update @nrwl/schematics`, you would be updated to the latest version of the code.

The lint rules have moved to `@nrwl/workspace/src/tslint` but a lot of other things have changed too so please use `yarn update` when updating Nx

**Comment by appsolutegeek** [comment]
Yes, thanks. I must remember not to update manually next time. Checked everything that was upgraded via a new project and then passed everything over. Thanks, again
