### ISSUE TITLE
Is there a good example of microservices with nestjs and nx?

### ISSUE THREAD

**Issue by jon9090** [nrwl/nx#14718]
I want to build microservices application with nx and nestjs.

Is there a good example to start? (including API gateway and example of two services that communicate between them by best practices)

I found this: https://github.com/Denrox/nestjs-microservices-example/blob/master/task/src/main.ts
But it without nx, and I not sure how to have the microservice is app or lib? how I serve two or more services? how services know about each other? what the build process need to be?

so good example of nx and nest in microservices will be helpful.

**Comment by synerp** [comment]
Nx is just a way to organise your apps - I don't think this is the place to find this type of information.  I would try a youtube search for nestjs microservices and then nestjs discord for any questions.

**Comment by FurlanLuka** [comment]
hey @jon9090  I have just release a project that helps streamline microservices with NX and Nestjs. Its all opensource! Check it out!
https://github.com/FurlanLuka/microservice-stack

**Comment by jon9090** [comment]
@FurlanLuka, that's very cool!! Would you happen to have an example application for using this project?

**Comment by FurlanLuka** [comment]
Yes! https://github.com/FurlanLuka/microservice-stack-shop-demo . There is also whole section in documentation related to this demo project https://docs.microservice-stack.com/introduction/demo-project/project-overview

**Comment by isaacplmann** [comment]
Looks like the OP found what they needed.  Closing
