### ISSUE TITLE
nx.dev Localization support

### ISSUE THREAD

**Issue by billyma128** [nrwl/nx#1472]
## Expected Behavior

Thank you guys for your great job!👋
Is there any plan to support i18n document? Such a great project deserves to be known by more developers.

## Current Behavior

English only.

**Comment by vsavkin** [comment]
Thank you! We would really want to make this happen, but unfortunately we don't have the bandwidth to do it right now. If you are interested in championing it, we will help!

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by mehrad-rafigh** [comment]
Hey @vsavkin I like to tackle this and add a german translation. How should I start? Do have any wishes?

**Comment by douglasward** [comment]
Why did this get closed? Did I miss something?
