### ISSUE TITLE
buildableProjectDepsInPackageJsonType is not respected in the @nrwl/js:tsc executor

### ISSUE THREAD

**Issue by aqemi** [nrwl/nx#14735]
### Current Behavior

Setting `buildableProjectDepsInPackageJsonType: peerDependencies` is not working; all dependencies are going to the `dependencies` section.

### Expected Behavior

Setting `buildableProjectDepsInPackageJsonType: peerDependencies` will force setting dependencies in the `peerDependencies` package.json section.

### Steps to Reproduce

1. Generate library with @nrwl/js generator
2. Install some third party dependency and import it in the library
3. In project.json, `build` target set 
`buildableProjectDepsInPackageJsonType: peerDependencies` 
`updateBuildableProjectDepsInPackageJson: true `
4. Run `build` target
5. Check generated package.json in the `dist` folder

### Nx Report

```shell
Node : 16.13.2
   OS   : darwin x64
   npm  : 8.1.2
   
   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 15.6.3
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
```

### Additional Information

The issue is on this line 
https://github.com/nrwl/nx/blob/4ba43630a7be667c4a443406264748a5d4ebd497/packages/js/src/utils/package-json/update-package-json.ts#L56

Before setting dependencies tsc executor calls to the `createPackageJson` method of the @nrwl/devkit package which in it turn adds dependencies by itself
https://github.com/nrwl/nx/blob/f3465a9c0760692c39bba97ab72fc21a4b12ff19/packages/nx/src/utils/create-package-json.ts#L53

**Comment by sushruth** [comment]
I encountered the same issue right now.

**Comment by dominicegginton** [comment]
I am also expirancing the same issue. Setting the _analyzeSourceFiles_ confuration option for the **@nx/js** plugin to `true`, along with the _updateBuildableProjectDepsInPackageJson_ to `true` and the _buildableProjectDepsInPackageJsonType_ option to `"peerDependencies"` unexpectedly adds found deps to the _dependencies_ property in the genorated **package.json** and not the _peerDependencies_ property.

- `nx@16.1.4`
- `@nx/js@16.1.4`

**nx.json**
```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "extends": "nx/presets/core.json",
  "pluginsConfig": {
    "@nx/js": {
      "analyzeSourceFiles": true
    }
  }
}

```
**project.json**
```json
{
  ...
  "targets": {
    "build": {
      "executor": "@nx/js:tsc",
      "outputs": ["{options.outputPath}"],
      "options": {
        ...
        "updateBuildableProjectDepsInPackageJson": true,
        "buildableProjectDepsInPackageJsonType": "peerDependencies"
      }
    }
  }
}

```

**Comment by PowerSupply** [comment]
Pretty much the same problem for me with:
- nx@16.3.2
- nx/js@16.3.2

I do not get any dependencies (except tslib) at all with a newly generated js library built with executor `@nx/js:tsc`. I got `"updateBuildableProjectDepsInPackageJson"`: true and `"buildableProjectDepsInPackageJsonType": "dependencies"`.
