### ISSUE TITLE
From @nrwl/webpack@15.4.6 on the bundle generated from a react app using webpack is 4 times bigger than before

### ISSUE THREAD

**Issue by vdaskalov-ext** [nrwl/nx#14732]
### Current Behavior

When build a react app with the latest @nrwl libs the resulting artefacts are **4 times** bigger than with an older version.
- the resulting code is not minified
- there are multiple copies of class definitions within the resulting artefacts coming from libraries
- hypothesis: no treeshaking is being done

### Expected Behavior

The resulting production code is minifed, obfuscated and does not contain multiple copies of libraries.

### GitHub Repo

https://github.com/vdaskalov-ext/nrwl-webpack-issue-example

### Steps to Reproduce

1. checkout
- "main" branch works as intended (nrwl@15.4.6)
- "latest" branch represents the issue (nrwl@after 15.4.6)
3. yarn
4. yarn build

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.7.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 15.7.0-alpha.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.7.0-beta.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.7.0-alpha.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.7.0-alpha.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.7.0-alpha.2
   @nrwl/js : 15.7.0-alpha.2
   @nrwl/linter : 15.7.0-alpha.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.7.0-alpha.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.7.0-alpha.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.7.0-alpha.2
   @nrwl/webpack : 15.7.0-alpha.2
   @nrwl/workspace : 15.7.0-alpha.2
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by jaysoo** [comment]
This has been fixed here https://github.com/nrwl/nx/pull/14695

We can release a patch for it. A workaround for now is to have the following in your `webpack.config.js` file.

```js
const { composePlugins, withNx } = require('@nrwl/webpack');
const TerserPlugin = require('terser-webpack-plugin');
const { withReact } = require('@nrwl/react');

module.exports = composePlugins(withNx(), withReact(), (config) => {
  config.optimization.minimizer.push(new TerserPlugin({
    parallel: true,
  }));
  return config;
});
```

And make sure it is used in `project.json`.

```json
    "build": {
      "executor": "@nrwl/webpack:webpack",
      "outputs": [
        "{options.outputPath}"
      ],
      "defaultConfiguration": "production",
      "options": {
         ...
        "webpackConfig": "apps/app/webpack.config.js"
      },
  }
```

**Comment by vdaskalov-ext** [comment]
Hi @jaysoo, thanks for the prompt response.

I've tried the workaround inside the "latest" branch of the example repo.
There is an improvement but still the resulting bundle is roughly **2x** at 1.3 MB comapred with before.

**Comment by vdaskalov-ext** [comment]
Hi @jaysoo, could you reopen the issue since the workaround didn't completely resolve the problem?
