### ISSUE TITLE
Unwanted connection to Nx Cloud public services

### ISSUE THREAD

**Issue by a-coruble** [nrwl/nx#14753]
### Current Behavior

Hello there, I encountered a security issue while using Nx today.

As usual, while working on my repository, I launched an Nx task to lint my monorepo. After failing on some of my packages, Nx gave a hint to run `nx view-logs`, which is a command that I don't know at all and can't find documentation for, so I went ahead and tried it. It then gave me a link, on the `nx.app` domain, that is publicly available and can give some information about my repository & tasks. This is not a behaviour I expected at all, and I don't know how I can get some support from your team.

### Expected Behavior

I expect Nx to never automatically connect me to some kind of public cloud, or have documentation & clear warnings about the security implications before doing so.

### Steps to Reproduce

1. Have a git repo with Nx set-up
2. Make sure to have Nx >= 15.0.7
3. Run any command that could fail
4. You should see a hint to use `view-logs`
5. Run the `view-logs` command and see the url that gets generated

### Nx Report

```shell
NX   Report complete - copy this into the issue template

   Node : 16.18.0
   OS   : darwin arm64
   pnpm : 7.22.0

   nx : 15.3.0
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : Not Found
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : Not Found
   typescript : 4.6.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by jbadeau** [comment]
I agree, the command is misleading and actually stores the cash of premise. Please make this clear with a warning label of the implications. Perhaps with a note that orgs can install the service on premises

**Comment by a-coruble** [comment]
Maybe we can have a flag / configuration option to ensure we never get connected to Nx Cloud & enforce the local runner?

**Comment by FrozenPandaz** [comment]
Hey all, I understand the concern of accidentally uploading the logs to a public service. Let's talk about how we can make it harder to mistakenly upload things.

1. We should definitely document this command more. We will add information to nx.dev.

2. For the record, there is indeed a prompt which must be answered before actually uploading to Nx Cloud:

![image](https://user-images.githubusercontent.com/8104246/216186992-66a1bc44-6c39-448f-8e7f-a708faa323a9.png)

We are open to improving the message here. How can we change this message to make it more clear that the logs are being **uploaded** to Nx Cloud?

3. No artifacts are being uploaded. Mostly logs

The "run details" that are being uploaded are your logs (which could contain sensitive information), timing (how long it took to execute) and some details like the machine specs. No artifacts are being uploaded. And, even if they were uploaded (they're not), someone would need your source code to retrieve them.

**Comment by a-coruble** [comment]
> We are open to improving the message here. How can we change this message to make it more clear that the logs are being uploaded to Nx Cloud?

Honestly, I would add a warning or something around the fact that this operation will install some dependencies, and automatically connect & upload data that can be sensitive to a public cloud.

Something along those lines:
> To view the logs, Nx needs to connect your workspace to Nx Cloud and upload the most recent run details.

>Yes - Be careful, this will install @nrwl/nx-cloud and automatically connect & upload your logs to Nx's public cloud
> No

I'm going to reiterate, and maybe contribute (if you have some information on where I can start contributing), but I would like to ensure that some of these commands that trigger a connection to the cloud can be disabled entirely.

**Comment by jbadeau** [comment]
@FrozenPandaz Maybe I misunderstand but this command adds the following to the nx.json file

```json
  "tasksRunnerOptions": {
    "default": {
      "runner": "@nrwl/nx-cloud",
      "options": {
        "cacheableOperations": [
          "build",
          "lint",
          "test",
          "e2e"
        ],
        "accessToken": "ZTdhY2ZmNTgtODc5Ni00OGY3LTgwMjItMTRkODY3NmUzZmFkfHJlYWQtd3JpdGU="
      }
    }
  },
```

which I believe enables distributed caching and the cache is loaded on the cloud?

**Comment by jbadeau** [comment]
Anyhow. Thankyou for taking this serious and I guess a very prominent notice of what the Sideeffects are is enough.
