### ISSUE TITLE
unclear how input files listed in 'nx graph --file' relate to targets

### ISSUE THREAD

**Issue by janzwanenburg** [nrwl/nx#14765]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?
No, not really.
It is related to
[https://nx.dev/recipes/other/troubleshoot-cache-misses](https://nx.dev/recipes/other/troubleshoot-cache-misses)

Enter the URL or documentation section here.

### Additional context or description
I am troubleshooting cache misses.
As per above page, I can use nx graph --file=.. to see what Nx considers to be the input files for my targets.
Now I have several targets, with different inputs definitions. But the output of nx graph has just one list of files. To which target does that correspond? Or is the union of all target inputs?

**Comment by isaacplmann** [comment]
The files listed in that json object are the files that are associated with that project.  I agree that it would be nice to have a way to list all the files that are viewed as inputs for a given target.  Unfortunately that command doesn't exist right now.

You have to piece it together yourself by taking the list of files for the project and looking at the `input` definitions for each of the targets on that project.

**Comment by janzwanenburg** [comment]
Ok, thanks Isaac. 
Piecing it together yourself is not that straightforward. E.g. the input definitions may include global folders as well.

By the way, what exactly is the set of files associated with a project? It does not seem to be the list of all files minus the .nxignore set. Does it also exclude certain standard patterns or patterns listed in .gitignore files? 
That would also be great to have clearly documented.

**Comment by isaacplmann** [comment]
Nx will ignore files specified in `.gitignore` and also files specified in `.nxignore`
