### ISSUE TITLE
@nrwl/js:node can't work with @nrwl/vite:build

### ISSUE THREAD

**Issue by lengerrong** [nrwl/nx#14760]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I have a build target build by vite build executor.

"build": {
      "executor": "@nrwl/vite:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "outputPath": "dist/apps/my-app"
      },
      "configurations": {
        "development": {
          "mode": "development"
        },
        "production": {
          "mode": "production"
        }
      }
    },
    
 I want to use js:node executer to run from the build target

    "vite-serve": {
      "executor": "@nrwl/js:node",
      "defaultConfiguration": "development",
      "configurations": {
        "development": {
          "buildTarget": "my-app:build:development"
        },
        "production": {
          "buildTarget": "my-app:build:production",
          "inspect": false
        }
      }
    },

but I am not able to run it.

> nx run my-app:vite-serve:development

 >  NX   Property 'watch' does not match the schema. 'true' should be a 'object'.

 ————————————————————————————————————————————————————————————————————

 >  NX   Ran target vite-serve for project my-app (627ms)

### **Most executors are having 'watch' option with boolean type.
while vite:build executor requires 'watch' schema to be an object.**

**Comment by lengerrong** [comment]
seems related.
https://github.com/nrwl/nx/pull/14756

**Comment by mandarini** [comment]
Hi there @lengerrong ! I am not sure I understand this feature request! The [`@nrwl/js:node` executor](https://nx.dev/packages/js/executors/node#@nrwl/js:node) is a different executor than the `@nrwl/vite:build` executor. If you want to use the `@nrwl/js:node` executor you can do so, and you have to configure it with the settings that it can be configured with, all mentioned in the [documentation](https://nx.dev/packages/js/executors/node#@nrwl/js:node). 

You can take a look at the documentation of the [`@nrwl/js`](https://nx.dev/packages/js) package, to see how you can generate a project using `@nrwl/js:node`.

**Comment by lengerrong** [comment]
> 

The major change I want for @nrwl/vite:build is the schema change.

Most executors are having 'watch' option with boolean type, but @nrwl/vite:build requires an object for it.

which leads to we can't use other executor such as @nrwl/js:node to run the js build out by  @nrwl/vite:build

so if it possible to make change to its schema like below?

      "oneOf": [
        {
          "type": "boolean"
        },
        {
          "type": "object"
        }
      ],
      "default": false
  
  I found below PR is raised.
  https://github.com/nrwl/nx/pull/14756/files

**Comment by mandarini** [comment]
Oh ok! I see! :) That PR is merged now, so if you think that it fixes your issue, we can close this feature request, what do you think?

**Comment by lengerrong** [comment]
yup, the schema error should be gone with that PR.
I just tested in my local, schema error is gone
but faced a new issue:

built in 107ms.
Debugger listening on ws://localhost:9229/5a4b0970-dea1-43cc-b6b1-e213492b7ca1
Debugger listening on ws://localhost:9229/5a4b0970-dea1-43cc-b6b1-e213492b7ca1
For help, see: https://nodejs.org/en/docs/inspector
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at validateString (internal/validators.js:124:11)
    at Module.require (internal/modules/cjs/loader.js:967:3)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/eleng/Work/vite-ssr/activate/packages/js/src/executors/node/node-with-require-overrides.ts:20:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)

**Comment by lengerrong** [comment]
it looks like @nrwl/vite:build will not generate an output file which cause this issue.

**Comment by lengerrong** [comment]
you can reproduce the issue with below example:

steps:
1. git clone https://github.com/lengerrong/nx-vite-ssr-react-app
2. npm install
3. change the schema to allow boolean watch value.
node_modules/@nrwl/vite/src/executors/build/schema.json
node_modules/@nrwl/vite/src/executors/build/schema.d.ts
3. edit apps/activate/project.json to serve via @nrwl/js:node from the vite build

    "ssr-serve": {
      "executor": "@nrwl/js:node",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "activate:ssr-vite-build"
      },
      "configurations": {
        "development": {
          "buildTarget": "activate:ssr-vite-build:development"
        },
        "production": {
          "buildTarget": "activate:ssr-vite-build:production"
        }
      }
    },

4. nx run activate:ssr-serve
then you will see the error.

**Comment by mandarini** [comment]
Thanks for the repro. I'll take a look tomorrow. But just so I understand. You want to run a dev server using `@nrwl/js:node` but point to `@nrwl/vite:build` as the buildTarget? And if yes, which problem does this solution solve? I mean, why not use the vite dev-server?

**Comment by lengerrong** [comment]
for the app https://github.com/lengerrong/nx-vite-ssr-react-app, 
I want to debug ssr react app via ViteDevServe followed its guide: https://vitejs.dev/guide/ssr.html
the vite dev-server can't fit there.
because it will be a backend node.js app and I want to custom the index html request handling.

so I want to use js:node which has watch feature to start app while server side js file changes.
and in the server.js, I use vite as a middleware of express.

though finally I found a workaround to let my app working
use webpack to build out the app and js:node to debug it.

but if we can let vite build executor works with js node executor that would be awesome!
since I really like the fast build and debug that vite provides.

**Comment by jaysoo** [comment]
It's technically possible, but we need to relax the schema so `watch: boolean` is supported. It'll need to be normalized before passing to Vite since Vite only supports objects.

**Comment by lengerrong** [comment]
@mandarini  @jaysoo 
any update on this one?

I temporarily make the schema check pass(the watch schema).
but still can't work out.

TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
at new NodeError (internal/errors.js:322:7)
at validateString (internal/validators.js:124:11)
at Module.require (internal/modules/cjs/loader.js:967:3)
at require (internal/modules/cjs/helpers.js:101:18)
at Object. (/Users/eleng/Work/vite-ssr/activate/packages/js/src/executors/node/node-with-require-overrides.ts:20:1)

looks like js:node executor expect an output file from build target.
but vite:build exectutor didn't generate it.

**Comment by mandarini** [comment]
I will be closing this issue, since it should be fixed in the latest version. If the issue persists, please feel free to ping me and I will reopen!

**Comment by lengerrong** [comment]
> I will be closing this issue, since it should be fixed in the latest version. If the issue persists, please feel free to ping me and I will reopen!

No, the issue still there.
js:node executor still can't work with target build via vite:build exector.

You can reproduce the issue with this branch code.

git clone https://github.com/lengerrong/nx-vite-ssr-react-app.git
git checkout vite-build
npm install
npm server
npm start 

attach my log:

> activate@0.0.0 start nx-vite-ssr-react-app
> nx serve


> nx run activate:serve:development

vite v4.1.1 building SSR bundle for development...
✓ 1 modules transformed.
../../dist/apps/activate/server/server.mjs  1.67 kB
Debugger listening on ws://localhost:9229/a939ed6f-3132-42c0-908f-3bad48e53218
Debugger listening on ws://localhost:9229/a939ed6f-3132-42c0-908f-3bad48e53218
For help, see: https://nodejs.org/en/docs/inspector
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at validateString (internal/validators.js:124:11)
    at Module.require (internal/modules/cjs/loader.js:967:3)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (nx-vite-ssr-react-app/packages/js/src/executors/node/node-with-require-overrides.ts:20:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)

 >  NX   Unknown error caught

   Pass --verbose to see the stacktrace.

**Comment by mandarini** [comment]
Can you try it with the latest version of Nx? `nx migrate 15.7.0-beta.5`?

**Comment by lengerrong** [comment]
@mandarini 
just tried latest nx (https://github.com/lengerrong/nx-vite-ssr-react-app/blob/vite-build/package.json#L46), still same error.

**Comment by lengerrong** [comment]
@mandarini 

just want to see if vite executor build can make below implementation change:

      outfile: resolve(normalizedOptions.outputPath, watcherOrOutput.output[0].fileName)

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/12043120/218610671-dced4300-c974-468c-9ec9-36920ad5e8f7.png">

**Comment by mandarini** [comment]
@lengerrong perfect, do you want to make this change and put a PR in? Mention me as well, and I can approve it.

**Comment by mandarini** [comment]
I tried it with your suggestion and I'm still getting some errors! So, I'm waiting for your PR with the fixes that make this work! :)

**Comment by mandarini** [comment]
Linking [this issue](https://github.com/nrwl/nx/issues/14868) here

**Comment by lengerrong** [comment]
@mandarini 

glad to see https://github.com/nrwl/nx/pull/14989/files commits.

but that change is for rollup executor.
 I don't think it  will work for vite:build exectutor.

we might still have to put another PR to change vite:build exectutor.

**Comment by mandarini** [comment]
Hey @lengerrong ! Are you still working on this? Let me know if you need help!

**Comment by lengerrong** [comment]
test with latest @nx/vite:build
it works well with @nx/js:node now

a sample project.json for your reference:
```
"vite-build": {
      "executor": "@nx/vite:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "outputPath": "dist/apps/your-backend",
        "ssr": "src/main.ts",
        "outputFileName": "main.mjs"
      },
      "configurations": {
        "development": {},
        "production": {}
      }
    },
    "vite-serve": {
      "executor": "@nx/js:node",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "your-backend:vite-build"
      },
      "configurations": {
        "development": {
          "buildTarget": "your-backend:vite-build:development"
        },
        "production": {
          "buildTarget": "your-backend:vite-build:production"
        }
      }
    }
```
>
One key point: remember set "outputFileName", otherwise you might get an error.
 >  NX   The "path" argument must be of type string. Received undefined
