### ISSUE TITLE
Creating workspace with outdated preset fails with cryptic message

### ISSUE THREAD

**Issue by meeroslav** [nrwl/nx#14776]
When running `npx create-nx-workspace@latest my-blog --preset=@nrwl/gatsby --verbose` we get:

![Screenshot 2023-02-02 at 16 25 10](https://user-images.githubusercontent.com/881612/216368317-0b156247-1575-44fa-a50e-8f5d7bd09dcb.png)

### Current Behavior

Generating workspace using outdated preset fails with a non-helpful message.
The code should not reach generators/preset in the @nrwl/workspace as this is clearly unknown preset.

### Expected Behavior

If workspace generation fails, we should provide more meaningful message and bail sooner, without going to @nrwl/workspace preset logic.

### Steps to Reproduce

1. npx create-nx-workspace@latest my-blog --preset=@nrwl/gatsby --verbose

### Nx Report

```shell
Workspace creation fails, so there is no `nx report`.

The current version is `v15.6.3`
```

### Failure Logs

```shell
>  NX   Invalid preset undefined


Error: Invalid preset undefined
    at /Users/miro/Dev/Forks/miro-rs/node_modules/@nrwl/workspace/src/generators/preset/preset.js:143:19
    at Generator.next (<anonymous>)
    at /Users/miro/Dev/Forks/miro-rs/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/miro/Dev/Forks/miro-rs/node_modules/tslib/tslib.js:163:16)
    at createPreset (/Users/miro/Dev/Forks/miro-rs/node_modules/@nrwl/workspace/src/generators/preset/preset.js:21:20)
    at /Users/miro/Dev/Forks/miro-rs/node_modules/@nrwl/workspace/src/generators/preset/preset.js:10:15
    at Generator.next (<anonymous>)
    at /Users/miro/Dev/Forks/miro-rs/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 >  NX   Failed to apply preset: @nrwl/gatsby
```

**Comment by stevenbdf** [comment]
@meeroslav Did you manage to create a gatsby project in a Nx monorepo?

It looks like there isn't documentation on how to add gatsby website and Nx has removed or deprecated that `@nrwl/gatsby` package.
