### ISSUE TITLE
Support for multiple workspace scopes ?

### ISSUE THREAD

**Issue by iangregsondev** [nrwl/nx#1477]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Would be nice if Angular Console and the cli supports creating multiple workspace scopes, meaning I can create a library and decide which scope it goes in.

## Current Behavior

Currently, everything goes in the same scope i.e The tsconfig paths are like so

```
    "paths": {
      "@test/register": ["libs/test-ui/register/src/index.ts"]
    }
```
so I had 2 thoughts one was to manually edit it and prefix the path with ui like so

```
    "paths": {
      "@test/ui-register": ["libs/test-ui/register/src/index.ts"]
    }
```

but what would make better sense would be something like this ( here is an example with 2 libraries, 1 for the ui and 1 for server, as you can see I use 2 different scopes and no prefixing

```
    "paths": {
      "@test-ui/register": ["libs/test-ui/register/src/index.ts"],
      "@test-server/register": ["libs/test-server/register/src/index.ts"]
    }
```
 In angular console, you can already provide a directory which covers my "test-ui/test-server" directories above - but the scope is still only singular..

Sure we can edit this manually - but would be cool if it supported something like this out of the box 

What do you think? 

- version of Nx used 8
 version of Angular CLI 8

**Comment by appsolutegeek** [comment]
Any technical reason why 2 different scopes could no be used ? These are, at  the end of the day, just used for paths within tsconfig -right ?

**Comment by vsavkin** [comment]
There is no technical reason why we only allow for a single scope.

**Comment by iangregsondev** [comment]
@vsavkin it would be really nice to be able to pass in a --npmScope when creating libraries / apps etc etc

My project is growing :-)

and right now if I have a library in both the UI and the Server that is named the same - there would be a conflict

Of course, its easy to update it manually but would be great to allow the passing of this via the CLI and when using Angular Console.

**Comment by iangregsondev** [comment]
Actually this is not a conflict on the import path :-) It would be a conflict on the exported named. So I will close this although - it still would be nice to have the option of creating multiple scopes.
