### ISSUE TITLE
No clear path on creating react project+library in package-based documentation

### ISSUE THREAD

**Issue by samparhizkar** [nrwl/nx#14784]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/getting-started/package-based-repo-tutorial

### Additional context or description
I feel like there is no clear path to how can we actually create a package-based monorepo with actual framework like react using this documentation page. I think it was also mentioned in one other issue as well. The examples mentioned on this page are unrealistic, people would want to set up a react libray (shared-ui) and a react-app in most scenarios. not a is-even and is-odd package(!). This is completely covered in the integrated pathway. But I honestly to this day don't know how can I actually make a package-base scenario with nx and benefit from that. It's definitely possible to create a workspace, but what happens after that? How do you link real-life react project and how do you utlize from nx to create those (pacakges)?

**Comment by isaacplmann** [comment]
With a package-based approach, you're intentionally opting out of the Nx way of connecting packages (the integrated approach).  Nx will happily allow you to use whatever system you want.  If you would like Nx to manage that aspect, then you want the integrated approach.
