### ISSUE TITLE
Generated Cypress project will not run

### ISSUE THREAD

**Issue by jonrimmer** [nrwl/nx#1479]
## Expected Behavior

If I use the `@nrwl/cypress:cypress-project` schematic to add Cypress to my workspace, the resulting Cypress project should work.

## Current Behavior

The resulting Cypress project does not work:

```
The plugins file is missing or invalid.

Your `pluginsFile` is set to `/Users/jon/GitHub/nx-e2e-test/dist/out-tsc/apps/test-e2e/src/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js` or `.coffee` file.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.
```

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

```
ng new nx-e2e-test
cd nx-e2e-test
ng add @nrwl/workspace
ng add @nrwl/cypress
ng generate @nrwl/cypress:cypress-project test-e2e
ng e2e test-e2e
```

### Context

Nx: 8.1
Angular: 8

**Comment by FrozenPandaz** [comment]
The issue is in `ng add @nrwl/workspace`. You can workaround the issue by adding `"rootDir": "."` to the root `tsconfig.json`.
