### ISSUE TITLE
Executor args applied to non relevant commands

### ISSUE THREAD

**Issue by krszktc** [nrwl/nx#14794]
### Current Behavior

Call local executor with param provided

![image](https://user-images.githubusercontent.com/24602491/216619855-d03438a7-e0be-4a79-b5d7-3feb5a3b6983.png)

![image](https://user-images.githubusercontent.com/24602491/216621025-6637d92d-a3ab-4510-8531-c013cd63642e.png)

### Expected Behavior

Args parameters applier to relevant command

### Steps to Reproduce

1. Create local executor
2. add two commands
3. pass param to second of them

### Nx Report

```shell
nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : 15.6.3
   @nrwl/next : Not Found
   @nrwl/node : 15.6.3
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
```

**Comment by AgentEnder** [comment]
You need to set forwardAllArgs to false. Try something like this:

```
"webpack": {
    "executor": "nx:run-commands",
    "options": {
        "commands": [
            {
                "command": "webpack",
                "forwardAllArgs": false
            }
        ]
    }
}
```

See: https://nx.dev/packages/nx/executors/run-commands

**Comment by krszktc** [comment]
Hi @AgentEnder, 

Thanks for update but don't exactly understand how it should work. I already read the documentation on page which you pointed. There is an example like that:
![image](https://user-images.githubusercontent.com/24602491/217600076-69690d56-f97b-4d15-9da0-fa27245c5b20.png)

Regarding to this, I'm trying to pass params to one of my commands
![image](https://user-images.githubusercontent.com/24602491/217600442-10ca9ebb-1a75-4012-85b0-4a78ff77ee61.png)

And later I call the executor like:
`pnpm nx docker music --port=4000`
or 
`nx run music:docker --port=4000`

Regarding to my piece of config, should it looks like that?
![image](https://user-images.githubusercontent.com/24602491/217600223-781222ed-87f9-41a3-8abc-6ea31eee3201.png)

If yes, it still doesn't work

**Comment by AgentEnder** [comment]
Can you try `args.port` instead of `args:port`?

**Comment by krszktc** [comment]
It' working! Great thanks for help. Maybe just my understanding but It wasn't obvious.
