### ISSUE TITLE
incorrect path when using sourceMaps in the __webpack_require__ (path does not include the sourceRoot for the project.json)

### ISSUE THREAD

**Issue by icameron** [nrwl/nx#14799]
### Current Behavior

webpack generates the dist main.js 
`const` app_service_1 = __webpack_require__("./src/app/app.service.ts");`

So when using vscode to debug it cannot map the the correct file 

### Expected Behavior

webpack should generates the dist main.js with 
`const` app_service_1 = __webpack_require__("./apps/test/src/app/app.service.ts");`

(note this what happing on previous versions)

### Steps to Reproduce

1. npx create-nx-workspace my-workspace2 --preset=nest 
2. Application name: test
3. Enable distributed caching to make your CI faster :No
4. cd my-workspace
5. npx nx run test:build

review ./dist/apps/test/main.js

### Nx Report

```shell
Node : 18.12.1
   OS   : win32 x64
   npm  : 8.19.2
   
   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : 15.6.3
   @nrwl/next : Not Found
   @nrwl/node : 15.6.3
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Additional Information

another user with this issue and a workaround
https://nrwlcommunity.slack.com/archives/CMFKWPU6Q/p1675339244023509

**Comment by samuelsweet** [comment]
Can someone post the workaround here?

**Comment by icameron** [comment]
Something like this from Arthur Breton should work where you hard code the path in the launch.json
`"sourceMapPathOverrides": {
        "webpack:///./src/*": "${workspaceFolder}/packages/backend/src/*",
        "webpack://../*": "${workspaceFolder}/packages/*"
      },`

this shouldn't be required as previous versions uses the relative path
