### ISSUE TITLE
angular/cli 1.6.0 support

### ISSUE THREAD

**Issue by rernens** [nrwl/nx#148]
When can we expect the support of angular/cli 1.6  ?

**Comment by dereklin** [comment]
I was about to ask a related question.  Right now, we have to use:
```
"@angular/cli": "nrwl/fix-cli-build"
```
Otherwise, the paths are wrong.

Is nrwl/fix-cli-build picking up the performance enhancements done in 1.6.0 and going forward?

**Comment by ankemp** [comment]
Seems like they are merging 1.6 into their build: https://github.com/nrwl/fix-cli-build/tree/release16

You can find reasoning behind having their own build in their [FAQs](https://github.com/nrwl/nx/wiki/FAQ#why-using-httpsgithubcomnrwlfix-cli-build-instead-of-angularcli)

**Comment by vsavkin** [comment]
Fixed here a477bb9fc953e3b44d696945cc259119f701fb78
