### ISSUE TITLE
Feature: support Github package registry

### ISSUE THREAD

**Issue by stefan-karlsson** [nrwl/nx#1480]
## Other

Github will soon release their package registry. 
It would be awesome if the NX workspace would support publishing npm packages to that registry out of the box.

https://help.github.com/en/articles/about-github-package-registry

**Comment by xmlking** [comment]
would be great if we have builder for   
```bash
ng publish myapp --registry=github
ng publish mylib --registry=github
```

**Comment by stefan-karlsson** [comment]
GitHub is no longer in beta. Would be awesome to get this feature into a NX workspace. Please let me know if any help is needed.

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.
