### ISSUE TITLE
nx generate @nrwl/workspace:library fails with error in newly-created monorepo

### ISSUE THREAD

**Issue by masonmark** [nrwl/nx#14800]
### Current Behavior

Using VS Code GUI extension "generate" command, or the command line, `npx nx generate @nrwl/workspace:library` crashes with the error  `NX   Cannot convert undefined or null to object`

### Expected Behavior

The lib should be generated successfully.

### GitHub Repo

https://github.com/masonmark/nx-bug-demo-2023-02-04

### Steps to Reproduce

1. Run `npx create-nx-workspace@latest` and choose 'angular' to create a new monorepo.

2. Run the command `npx nx generate @nrwl/workspace:library any --buildable --importPath=@axhxrx/any --pascalCaseFiles --standaloneConfig --no-interactive` (either using the VS Code extension, or on the command line)

Boom! It fails with an error.

### Nx Report

```shell
➜ git:(main) nx report  

 >  NX   Report complete - copy this into the issue template

   Node : 18.12.1
   OS   : darwin arm64
   npm  : 8.19.2
   
   nx : 15.6.3
   @nrwl/angular : 15.6.3
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

➜ git:(main)
```

### Failure Logs

```shell
➜ npx nx generate @nrwl/workspace:library any --buildable --importPath=@axhxrx/any --pascalCaseFiles --standaloneConfig --no-interactive --verbose

>  NX  Generating @nrwl/workspace:library


 >  NX   Cannot convert undefined or null to object


TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at findLintTarget (/blah/node_modules/@nrwl/linter/src/generators/init/init-migration.js:22:25)
    at /blah/node_modules/@nrwl/linter/src/generators/init/init-migration.js:12:28
    at Array.forEach (<anonymous>)
    at migrateConfigToMonorepoStyle (/blah/node_modules/@nrwl/linter/src/generators/init/init-migration.js:11:14)
    at /blah/node_modules/@nrwl/linter/src/generators/lint-project/lint-project.js:91:67
    at Generator.next (<anonymous>)
    at /blah/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/blah/node_modules/tslib/tslib.js:163:16)
```

### Additional Information

The problem is in the file `node_modules/@nrwl/linter/src/generators/init/init-migration.js`.

Line 22 starts with `return (_a = Object.entries(project.targets).find(`... but immediately before the error, `project` is `{ root: 'any', sourceRoot: 'any', projectType: 'library' }` so `project.targets` is undefined.

**Workaround:** 
Manually edit that file so Line 22 starts with: `return (_a = Object.entries(project.targets ?? {}).find(`...

**Comment by AgentEnder** [comment]
This should probably work, but that said @nrwl/workspace:library is deprecated. You probably want to use @nrwl/js:library.
