### ISSUE TITLE
ts @types without code not being referenced correctly

### ISSUE THREAD

**Issue by acroyear** [nrwl/nx#14809]
### Current Behavior

Follow the steps to create a monorepo react (1 or 2 apps, 1 js lib, 1 react lib).

In the JS lib, include the attached file (Chromecast), and rename it back to .ts suffix.

In the JS lib or in the root, npm install --save @types/chrome @types/chromecast-caf-sender

Note that both have added @types but because in Chrome, the variables chrome and cast are global and supplied by the browser runtime, there are no .js files involved. This only adds types.

[Cast.txt](https://github.com/nrwl/nx/files/10611590/Cast.txt)

Editor and/or build will get something like the following:

```
Module not found: Error: Can't resolve 'chrome' in '/Users/joe/Projects/subfirenx/libs/core/src'
resolve 'chrome' in '/Users/joe/Projects/subfirenx/libs/core/src'
  Parsed request is a module
  using description file: /Users/joe/Projects/subfirenx/libs/core/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/joe/Projects/subfirenx/libs/core/src/node_modules doesn't exist or is not a directory
      looking for modules in /Users/joe/Projects/subfirenx/libs/core/node_modules
        single file module
          using description file: /Users/joe/Projects/subfirenx/libs/core/package.json (relative path: ./node_modules/chrome)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/joe/Projects/subfirenx/libs/core/node_modules/chrome doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/joe/Projects/subfirenx/libs/core/node_modules/chrome.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/joe/Projects/subfirenx/libs/core/node_modules/chrome.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/joe/Projects/subfirenx/libs/core/node_modules/chrome.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/joe/Projects/subfirenx/libs/core/node_modules/chrome.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/joe/Projects/subfirenx/libs/core/node_modules/chrome.jsx doesn't exist
        /Users/joe/Projects/subfirenx/libs/core/node_modules/chrome doesn't exist
```

I managed to tweak ts settings somehow to get the lib to work but the app continues to report this problem and I really don't remember what bit of 'magic incantation' actually got the lib to work in the first place.

### Expected Behavior

It is referenced without error, in both the lib and the subsequent app.

### Steps to Reproduce

listed above.

### Nx Report

```shell
% nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : darwin arm64
   npm  : 9.4.1
   
   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.6.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.6.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.6.3
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @badgers-ua/nx-react-pwa: 1.0.4
```

### Failure Logs

```shell
listed above
```

**Comment by acroyear** [comment]
I tried removing types: ['node'] from the tsconfig files and that didn't seem to do it...at least, not right away. Again, I don't know what happened that finally fixed it on the lib folder.

**Comment by acroyear** [comment]
This combination of compilerOptions seems to be the trick in the app (along with moving 'extends' to the top of the tsconfig file instead of the bottom, but I have no idea which of these actually caused the change:
```
    "module": "ESNext",
    "composite": false,
    "moduleResolution": "node",
    "forceConsistentCasingInFileNames": true,
    "strict": false,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": false,
    "noFallthroughCasesInSwitch": true,
    "checkJs": false,
    "allowJs": true
 ```

**Comment by acroyear** [comment]
nope. that didn't resolve it.

    "allowSyntheticDefaultImports": false,

if that's true, then the @types cases fail for the two files above. *in the app* - the library still works just fine independently.

if that's false, then import React fails

```
TS1259: Module '"/Users/joe/Projects/subfirenx/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
  > 1 | import React, { useState } from "react";
```

**Comment by acroyear** [comment]
and i guess a heart of my issue is why is NX building the libraries with the app's rules when it builds the apps?

the libraries should be independent. they should build under their own rules, and the app just import them as if it was importing them from node_modules, which is how lerna's monorepo generally does it.

This current setup is just not suiting my needs if I can't get past these blatant contradictions in the tsconfigs that I need from react vs js modes.

**Comment by acroyear** [comment]
actually that never resolved it. it just buried the error. if there were other errors, the types case got short-cutted and didn't give this full dump.

**Comment by xiongemi** [comment]
under the app's tsconfig.app.json, in files, add `    "../../node_modules/@nrwl/@types/chrome/index.d.ts"`, in types, add "chrome". the tsconfig.app.json would become:
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "types": ["node", "chrome"]
  },
  "files": [
    "../../node_modules/@nrwl/react/typings/cssmodule.d.ts",
    "../../node_modules/@nrwl/react/typings/image.d.ts",
    "../../node_modules/@nrwl/@types/chrome/index.d.ts"
  ],
  "exclude": ["**/*.spec.ts", "**/*.spec.tsx", "jest.config.ts"],
  "include": ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx"]
}

```

you do not need to import form chrome. you can remove these 2 lines:
```
import "chrome";
import "chromecast-caf-sender";
```

now you got the global namespace "chrome" to use.

**Comment by xiongemi** [comment]
closing this issue
