### ISSUE TITLE
Build failure for Storybook with Typescript configuration in freshly generated project

### ISSUE THREAD

**Issue by OttoG** [nrwl/nx#14814]
### Current Behavior

In a fresh integrated workspace, when running the generators to create a fresh React library or web app project and set up Storybook, subsequent attempts to build Storybook fail if Typescript was chosen as the configuration file format for Storybook. (That is, the auto-generated `build-storybook` target fails, and in addition, the `storybook` target fails with the same error message.)

The error messages imply that the `@nrwl/storybook:build` executor does not compile the auto-generated *.ts configuration files and instead treats them as Javascript. It does not matter whether the recommended `@nrwl/react:storybook-configuration` generator or the `@nrwl/storybook:configuration` generator is used to set up Storybook for the project.

With the `@nrwl/react:storybook-configuration` generator:

```bash
npx create-nx-workspace@latest nx-integrated-ts-sb --preset=ts --nxCloud=false
cd nx-integrated-ts-sb
npm install -D @nrwl/react
npx nx g @nrwl/react:lib react-library --bundler=vite --style=scss --unitTestRunner=none
npx nx g @nrwl/react:storybook-configuration react-library --tsConfiguration=true --configureCypress=false --generateStories=true --generateCypressSpecs=false
npx nx build-storybook react-library
# Error:
# nx-integrated-ts-sb/packages/react-library/.storybook/main.ts: Unexpected token, expected "from" (3:12)
```

With the `@nrwl/storybook:configuration` generator:

```bash
npx create-nx-workspace@latest nx-integrated-ts-sb --preset=ts --nxCloud=false
cd nx-integrated-ts-sb
npm install -D @nrwl/react @nrwl/storybook
npx nx g @nrwl/react:lib react-library --bundler=vite --style=scss --unitTestRunner=none
npx nx g @nrwl/storybook:configuration react-library --uiFramework=@storybook/react --tsConfiguration=true --configureCypress=false --bundler=vite
npx nx build-storybook react-library
# Error:
# nx-integrated-ts-sb/packages/react-library/.storybook/main.ts: Unexpected token, expected "from" (3:12)
```

### Expected Behavior

The `build-storybook` and `storybook` targets generated by the `@nrwl/react:storybook-configuration` and `@nrwl/storybook:configuration` are expected to work.

If the `--tsConfiguration=true` flag is changed to `--tsConfiguration=false` in the above examples, the Storybook targets work as expected.

### GitHub Repo

https://github.com/OttoG/nx-storybook-ts-error

### Steps to Reproduce

1. `git clone https://github.com/OttoG/nx-storybook-ts-error`
2. `cd nx-storybook-ts-error/nx-integrated-ts-sb`
3. `npm install`
4. `npx nx build-storybook react-library`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.14.0
   OS   : darwin x64
   npm  : 9.3.1
   
   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.6.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.6.3
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.6.3
   @nrwl/vite : 15.6.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
> nx run react-library:build-storybook

>  NX  ui framework: @storybook/react

>  NX  Storybook builder starting ...

info => Cleaning outputDir: ./nx-storybook-ts-error/nx-integrated-ts-sb/dist/storybook/react-library

 >  NX   ./nx-storybook-ts-error/nx-integrated-ts-sb/packages/react-library/.storybook/main.ts: Unexpected token, expected "from" (3:12)

   
     1 | import { rootMain } from '../../../.storybook/main';
     2 |
   > 3 | import type { StorybookConfig, Options } from '@storybook/core-common';
       |             ^
     4 |
     5 | import { mergeConfig } from 'vite';
     6 | import viteTsConfigPaths from 'vite-tsconfig-paths';
   Pass --verbose to see the stacktrace.


————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build-storybook for project react-library (2s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

**Comment by mandarini** [comment]
@OttoG thanks. 

Can you remove `"useBuiltIns": "usage"` from your project's `.babelrc` file? I'll figure out why this messes things up, and I may remove it from the generator. Thanks! :D

**Comment by mandarini** [comment]
I'll push a fix to install `ts-node`, and maybe a comment saying to use Node 16 if you're using the vite builder!

**Comment by OttoG** [comment]
Hi @mandarini thank you for the very speedy replies!

However, first of all, I am indeed able to build and run Storybook with Node 18, as long as the Storybook configuration is JS-based. (That is, with `--tsConfiguration=false` when configuring Storybook.) I just have to run this before building:

```bash
export NODE_OPTIONS=--openssl-legacy-provider
```

At least in simple cases such as building and running Storybook for the single component that is added by the generators, it works fine with Node 18. I was going to mention that in the original report but forgot about it – sorry!

However, after installing `ts-node`, I get a different kind of error:

```
 >  NX   ⨯ Unable to compile TypeScript:

   packages/react-library/.storybook/main.ts:17:9 - error TS2322: Type '{ core: { builder: string; disableWebpackDefaults?: boolean | undefined; channelOptions?: Partial<Options> | undefined; disableProjectJson?: boolean | undefined; disableTelemetry?: boolean | undefined; enableCrashReports?: boolean | undefined; crossOriginIsolated?: boolean | undefined; }; ... 11 more ...; previewAnn...' is not assignable to type 'StorybookConfig'.
     Object literal may only specify known properties, and 'viteFinal' does not exist in type 'StorybookConfig'.
   
   17   async viteFinal(config: any) {
              ~~~~~~~~~
   
   Pass --verbose to see the stacktrace.


 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build-storybook for project react-library (3s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

VS Code complains about the same issue in the editor. It has done so all the time in my environment, but I was not sure if that would prevent the build from working:

![image](https://user-images.githubusercontent.com/5548343/217052886-bd2e9a76-1b20-433b-a29c-d7430e964388.png)

**Comment by mandarini** [comment]
Oh yeah, you can just do `as StorybookConfig`. The Storybook team has fixed this in Storybook v7!

**Comment by OttoG** [comment]
Thank you, that got me past the errors in `main.ts`. However, now I get this error instead:

```
> nx run react-library:build-storybook

>  NX  ui framework: @storybook/react

>  NX  Storybook builder starting ...

info => Cleaning outputDir: ./nx-storybook-ts-error/nx-integrated-ts-sb/dist/storybook/react-library
info => Loading presets
info => Compiling manager..
./nx-storybook-ts-error/nx-integrated-ts-sb/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:143
			throw new TypeError(
			^

TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (./nx-storybook-ts-error/nx-integrated-ts-sb/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:143:10)
    at ./nx-storybook-ts-error/nx-integrated-ts-sb/node_modules/terser-webpack-plugin/dist/index.js:566:67
    at SyncHook.eval (eval at create (./nx-storybook-ts-error/nx-integrated-ts-sb/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:85:1)
    at SyncHook.lazyCompileHook (./nx-storybook-ts-error/nx-integrated-ts-sb/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (./nx-storybook-ts-error/nx-integrated-ts-sb/node_modules/@storybook/manager-webpack4/node_modules/webpack/lib/Compiler.js:631:26)
    at ./nx-storybook-ts-error/nx-integrated-ts-sb/node_modules/@storybook/manager-webpack4/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (./nx-storybook-ts-error/nx-integrated-ts-sb/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (./nx-storybook-ts-error/nx-integrated-ts-sb/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (./nx-storybook-ts-error/nx-integrated-ts-sb/node_modules/@storybook/manager-webpack4/node_modules/webpack/lib/Compiler.js:662:28)
    at ./nx-storybook-ts-error/nx-integrated-ts-sb/node_modules/@storybook/manager-webpack4/node_modules/webpack/lib/Compiler.js:321:11

Node.js v18.14.0

————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build-storybook for project react-library (6s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]

```

**Comment by mandarini** [comment]
Here is my PR with the fixes to your repo: https://github.com/OttoG/nx-storybook-ts-error/pull/1

**Comment by OttoG** [comment]
Hi @mandarini this is a bit strange, but I downgraded to Node 16.19.0, applied your pull request (which made zero changes to my workspace compared to what I had after manually following your instructions), deleted `node_modules`, ran `npx nx build-storybook react-library --skipNxCache`, and I still get the same error: `TypeError: The 'compilation' argument must be an instance of Compilation`

This is on macOS 13.2, Intel. What environment are you using? Maybe there is some difference in some globally installed package?

**Comment by srweeks** [comment]
@OttoG did you ever manage to get this working? Is still failing to build for me

**Comment by OttoG** [comment]
@srweeks no I am sorry, we just figured we will use a setup with `--tsConfiguration=false` for the time being—and then perhaps try again with TypeScript config files when a stable version of Storybook 7 becomes available.
