### ISSUE TITLE
generated package.json contains peerDependencies collected from dev dependencies

### ISSUE THREAD

**Issue by stixx200** [nrwl/nx#14811]
### Current Behavior

When building a library which uses devDependencies that declare peerDependencies, these peerDependencies will be forwarded to the generated package.json.

Example:
A library uses the `jest-when` package. This package declares a peerDependency to `jest`. The package.json output (after running `nx build <libName>`) of the library also contains a peer dependency to `jest` (build it with executor `@nrwl/js:tsc`):

```
"peerDependencies": {
  "jest": "28.1.1", // no need to add jest as peerDependency for is-even package
  "tslib": "2.5.0"
}
```

### Expected Behavior

I don't expect peerDependencies of devDependencies to be collected into the generated package.json for a library with `@nrwl/js:tsc` executor.

### GitHub Repo

https://github.com/stixx200/reproduce-nx-issue-14811

### Steps to Reproduce

- Generate a new project with a new library
1. `npx create-nx-workspace@latest myorg --preset=ts`
2. `npx nx generate @nrwl/js:library is-even --publishable --importPath @myorg/is-even`
- Write a test which uses jest-when
1. `npm install --save-dev jest-when @types/jest-when`
2. Use jest-when in test (see github repo)
3. build is-even library
4. Check generated package.json

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.19.0
   OS   : win32 x64
   npm  : 8.19.3
   
   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by stixx200** [comment]
There is another issue with the generated package.json:
If a dependency is declared as "normal" dependency (e.g. because a different library in the Repository uses this dependency as production dependency) and only used in a spec file, the dependency will be written to `dependencies` section in the generated package.json.
Do you think this is worth another issue/bug report?
I think the solution could be the same as here: 
> Don't look at spec files when generating the production package.json

**Comment by stixx200** [comment]
Thank your for your response.
Are there any plans to enhance the project graph to distinguish between production and development dependencies?
And can you imagine a workaround to avoid this issue?
I thought about temporarily manipulate the .nxignore file to exclude spec files from project graph analyser.

**Comment by cloudratha** [comment]
We are seeing this as well, we have a nx plugin that leverages the `@nrwl/next` plugin. When building we have `next`, `react`, and `react-dom` as fixed peerDependencies. This doesn't make sense as those libraries only get added when running one of the generators. We wouldn't expect our users to have to install those dependencies as thats the plugin's responsibility!

**Comment by meeroslav** [comment]
@stixx200, can you please open another issue with your scenario? After looking into the source repo, it turns out this is a slightly different issue requiring a different fix.

**Comment by meeroslav** [comment]
@cloudratha can you provide a minimal repo or copy-paste here your generated package.json?

**Comment by cloudratha** [comment]
@meeroslav https://github.com/cloudratha/nx-dependency-issue

if you run `npx nx build plugin` the `peerDependencies` include `next`, `nx`, `react`, and `react-dom`
