### ISSUE TITLE
@nrwl/js - Required property 'project' is missing

### ISSUE THREAD

**Issue by JaedeokK** [nrwl/nx#14810]
### Current Behavior

project.json
```
"targets": {
  ...
  "build": {
    ...
    "options": {
      ...
      // project property is not exist
    }
  },
}
```

### Expected Behavior

project.json
```
"targets": {
  ...
  "build": {
    ...
    "options": {
      ...
      "project": "packages/${project-name}/package.json",
    }
  },
}
```

### Steps to Reproduce

1. check buildable option
![스크린샷 2023-02-06 오후 5 34 00](https://user-images.githubusercontent.com/64330699/216923179-4853a4db-08d7-41b4-b2cb-ee4ad37dbad2.png)

2. run command
```
yarn nx generate @nrwl/js:library test --unitTestRunner=none --no-interactive
```

3. run build command
```
yarn nx build test
```

4. error occur

### Nx Report

```shell
nx run test:build


 >  NX   Required property 'project' is missing



 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for project test (729ms)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
 
   View structured, searchable error logs at https://nx.app/runs/dC8sw59dxl
```

**Comment by ndcunningham** [comment]
I am unsure as to what is required here. 
Can you give a small repo for this? 
I tried this and it's working as expected (without project). See here: https://github.com/ndcunningham/issue-14810-

**Comment by JaedeokK** [comment]
I found out what the difference is.
When setting up packages using bundler. The above issue occurs when using rollup.
And Typescript error when using webpack.
See here: https://github.com/JaedeokK/issue-14810
