### ISSUE TITLE
@nrwl/esbuild doesn't support `plugins` in `esbuildOptions`

### ISSUE THREAD

**Issue by shellscape** [nrwl/nx#14823]
### Current Behavior

The esbuild plugin purports to support `plugins` via this line: https://github.com/nrwl/nx/blob/f38268bf533292e6c7d97cc39c8ac4e855d07eec/packages/esbuild/src/executors/esbuild/esbuild.impl.ts#L101

But as esbuild itself requires the `plugins` property to contain an array of objects, this can never be used as the code was written, as there's no way to convey what esbuild wants via `project.json` (and I'm not going to rant about why Nx doesn't support .js config files so don't worry, plenty of others already have)

### Expected Behavior

Some ability to use plugins.

### Steps to Reproduce

n/a

### Nx Report

```shell
n/a
```

### Failure Logs

```shell
n/a
```

### Additional Information

n/a

**Comment by ndcunningham** [comment]
I am not sure I understand, could you provide a repo highlighting your expectation?

**Comment by shellscape** [comment]
I'm not sure I understand what you aren't sure you understand.

To use esbuild plugins as explained here https://esbuild.github.io/plugins/#using-plugins, you have to be able to initialize them within a js file. esbuild provides no means to load plugins by name, and provides no means to load plugins via the command line (which you aren't using so that's moot). There's no reproduction to give because there's no way to create a reproduction, citing the info just given.

The gist is that the line I lined to does nothing, it has no purpose, because the user can never pass in anything via project.json that would be valid for esbuild to use there. So while the code purports to support user-provided plugins, it in fact does not, because Nx doesn't support anything but JSON in project.json.

**Comment by jaysoo** [comment]
We discussed this, and we can get plugins to work if we support a `.js` config file for esbuild, just like we do for rollup, vite, and webpack.

So you can define something like:

```js
// esbuild.config.ts
export default {
  //...
  plugins: [require('foo-plugin')]
}
```

or

```js
// esbuild.config.js
module.exports = {
  // ...
  plugins: [require('foo-plugin')]
};
```

**Comment by shellscape** [comment]
Being able to use a companion `.js` or `.ts` file would be ideal. That's up to you all if you'd like to support that, and would be cool for the community if you did. The purpose of my original issue was to highlight that there's currently code in the plugin that cannot be used, so I'm just pleased that it's getting attention.
