### ISSUE TITLE
[BUG] - Can't reference an asset in lib styles (postCss loader issue?)

### ISSUE THREAD

**Issue by nawlbergs** [nrwl/nx#14828]
### Current Behavior

I have an angular app and a lib with some standalone components.
I have an assets dir in the root of my lib and a glob pattern in the app.... basically exactly what this is telling you to do: https://www.youtube.com/watch?v=iU2PKRaTGQ0&t=45s

- /app
  - /myapp
     - /project.json (glob pattern)
- /libs
  - /mylib
     - /src
        - /assets
          - /grid.svg

the glob pattern in myapp/project.json: targets > build > options > assets:
```
{
  "glob": "**/*",
  "input": "libs/mylib/src/assets",
  "output": "assets"
}
```

So... my app is obviously trying to use one of my components.. and in my component I am doing:
```
template: '<div class="grid"></gid>'
styles: [`
  .grid {
    background: url('assets/grid.svg');     <!-- ERROR
  }
`]
```
error  Error: Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
C:\Users\......grid.ts:3:6: Can't resolve './assets/grid.svg' in 'C:\Users\.......\mylib\src\lib\ui\grid.component'

After messing around a ton:
```
template: `
    <img src="assets/grid.svg" /> <!-- WORKS
    <div style="background: url('assets/grid.svg')"></div>  <!-- WORKS
    <div class=" bg-[url(assets/grid.svg)]"></div> <!-- ERROR  (TAILWIND)
  `,
  styles: [`
    .someClasss {
      background: url('assets/grid.svg');   <!--- ERROR
    }
  `]

### Expected Behavior

App wont error and would generate the correct css and path to asset dir.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Create an app
2. Create a lib
3. Add an asset directory to the lib
4. Add a glob pattern in your app to include this directory
5. Reference the asset in your lib
6. Compile your app

Its the same setup as this:
https://www.youtube.com/watch?v=iU2PKRaTGQ0&t=45s

### Nx Report

```shell
Node : 18.13.0
   OS   : win32 x64
   npm  : 8.10.0

   nx : 15.6.3
   @nrwl/angular : 15.6.3
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : 15.6.3
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.6.3
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @fortawesome/angular-fontawesome: 0.12.1
         @ngrx/component-store: 15.1.0
         @ngrx/effects: 15.1.0
         @ngrx/entity: 15.1.0
         @ngrx/router-store: 15.1.0
         @ngrx/store: 15.1.0
         @ngrx/store-devtools: 15.1.0
```

**Comment by MeMeMax** [comment]
I got the same behaviour on Angular 13. The assets folder is not correctly copied to the dist folder. Thats the problem.

**Comment by MeMeMax** [comment]
@nawlbergs I had another look at this problem and maybe I can help you and others: My problem was that I had version 13.0.0 of ng-packagr. But they introduced later a way to put assets which are not referenced into the compiled lib. Therefore I upgraded ng-packagr to 15.1.1 (see [copy-assets.md](https://github.com/ng-packagr/ng-packagr/blob/main/docs/copy-assets.md)).

What I think you have to do is the following:
In order to build your app, your lib has to be built and published first. Your app will then access the built version of your lib. To include your assets to the lib do the following in the **ng-package.json of your lib**:

```
{
...
"assets": [{ "input": "./src/assets", "glob": "**/*.svg", "output": "assets" }],
...
}
```

This will output the svg into your assets folder in the compiled version of the lib and the glob pattern in your app will pick up the libs assets.

**Comment by nawlbergs** [comment]
@MeMeMax sigh... couple questions then:

1. how does this affect dev-server (watch)?  usually you don't build until deploy. 
2. Any resources on how to convert a lib with no build config into one that will build?

As a developer since 2000.. I feel like workspace/dev environments are a bigger challenge than code these days.

**Comment by nawlbergs** [comment]
This will kill hmr on the lib files then as well.. blah..

**Comment by Coly010** [comment]
This would be an issue with Angular and their Browser Builder. You can open an issue on their repo: https://github.com/angular/angular-cli/issues

If I get some time, I'll look into a possible workaround that allows you to keep your assets in the libs/ folder.

But, a short term solution would be to place that asset in the app's assets folder

**Comment by nawlbergs** [comment]
For anyone else trying to deal with this... this is how I'm moving forward.

![image](https://user-images.githubusercontent.com/1325984/219129295-a90551eb-969f-44df-937b-bd487163b892.png)

I decided to move library assets into a root level directory (the one I was using for all the static assets that will get copied into my dist during a build/deploy.    And any references in my lib will absolute.

Probably not the best solution... but
- There's one copy of the asset
- I don't have to add additional config to any projects
- it works.. and its not confusing

I'm using docker and running on `www.myapp.local` with apache proxies etc...  so this will work locally.... but wont work for you if you want to run your apps just on localhost etc. :(

**Comment by Coly010** [comment]
I'm going to close this as there is a workaround provided and as the fix lies outside of Nx.
