### ISSUE TITLE
Make e2e utils publicly available

### ISSUE THREAD

**Issue by dmitry-stepanenko** [nrwl/nx#14826]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

`e2e/utils/index.ts` contains a lot of useful functions that can be used in e2e tests for nx plugins. Such as: `promisifiedTreeKill`, `killPorts`, `runCommandUntil`, `expectJestTestsToPass`, etc.

 Would be awesome to be able to import it from `@nrwl/nx-plugin/testing`, right now I have to just copy-paste them.

**Comment by AgentEnder** [comment]
Hey @dmitry-stepanenko! This would be a welcome contribution if you have the time to work on it? @nrwl/nx-plugin's testing utils should have been kept in sync with the shared utils a bit better, but they have grown apart a bit as things have progressed.

**Comment by dmitry-stepanenko** [comment]
Sure thing @AgentEnder ! Just to clarify: it would be expected to copy them over, right? From what I see, e2e utils tend to not reuse code from packages

**Comment by AgentEnder** [comment]
Hey, I'm going to close this out as a duplicate of #10992. We are working on this area soon, stay tuned. 📺
