### ISSUE TITLE
React: ts-loader configuration produces error

### ISSUE THREAD

**Issue by zachnewburgh** [nrwl/nx#1484]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

[Redoc](https://github.com/Redocly/redoc)'s `RedocStandalone` should render API documentation when provided a spec.

## Current Behavior

The application fails to compile when [Redoc](https://github.com/Redocly/redoc)'s `RedocStandalone` is used in a React application.

## Failure Information (for bugs)

`TypeError: Cannot read property 'kind' of undefined` is thrown on compile.

### Steps to Reproduce

Repository: https://github.com/zachnewburgh/nx-issue/tree/redoc

As instructed by the [Redoc's documentation](https://github.com/Redocly/redoc):

1. `yarn add redoc mobx@^4.2.0 styled-components`
2. `import { RedocStandalone } from 'redoc';`
3. 
```
<RedocStandalone
  specUrl="http://rebilly.github.io/RebillyAPI/openapi.json"
  options={{
    nativeScrollbars: true,
    theme: { colors: { primary: { main: '#dd5522' } } },
  }}
/>
```

### Context

I was hesitant to post this since I initially thought that this was an issue with Redoc. However,  I was able to successfully use Redoc with two other builds: `create-react-app` and custom React-Typescript.

Since the error only manifests in an Nx workspace, I figured that it was important to raise in anticipation of it appearing in other scenarios.

### Failure Logs

![Screen Shot 2019-06-11 at 11 57 18 AM](https://user-images.githubusercontent.com/9732085/59306671-c7526a80-8c6a-11e9-9e04-f3bde5cd1b65.png)

## Other

N/A

**Comment by jaysoo** [comment]
@zachnewburgh There appears to be something different when running the app through `ts-loader` and `babel-loader` with `babel-preset-typescript`.

For now, a workaround would be to replace `ts-loader` with `babel-loader` in your project.

1. Modify `angular.json` and specify a custom webpack config path.

```

  "projects": {
    "nx-issue": {
      ...
      "architect": {
        "build": {
          "builder": "@nrwl/web:build",
          "options": {
            "webpackConfig": "apps/nx-issue/webpack.config.js",
            ...
```

2. Add `webpack.config.js` to your project.

```module.exports = config => {
  // Replace ts-loader with babel-loader.
  const tsIdx = config.module.rules.findIndex(
    rule => rule.loader === "ts-loader"
  );
  config.module.rules.splice(tsIdx, 1, {
    use: {
      loader: "babel-loader",
      options: {
        presets: [
          "@babel/preset-env",
          "@babel/preset-react",
          ["@babel/preset-typescript", { isTSX: true, allExtensions: true }]
        ]
      }
    },
    test: /\.tsx?|jsx?$/,
    exclude: /node_modules/
  });

  // Some libraries import Node modules but don't use them in the browser.
  // Tell Webpack to provide empty mocks for them so importing them works.
  config.node = {
    module: "empty",
    dgram: "empty",
    dns: "mock",
    fs: "empty",
    http2: "empty",
    net: "empty",
    tls: "empty",
    child_process: "empty"
  };

  return config;
};
```

3. Install packages.

```
yarn add babel-loader @babel/preset-env @babel/preset-react @babel/preset-typescript
```

---

I will close this issue since there is a workaround and we'll look into making babel support better. Let me know if you still run into any more issues with this setup.

**Comment by zachnewburgh** [comment]
Hi @jaysoo, thanks for the reply. I can't seem to modify the `config` object since it's not defined. Where does that happen?
