### ISSUE TITLE
is it deprecated or not - affected:apps & affected:libs

### ISSUE THREAD

**Issue by LongLiveCHIEF** [nrwl/nx#14843]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/packages/nx/documents/affected-apps

### Additional context or description

This page says that `affected:apps` command is deprecated and was supposed to be removed in v15.  However, it's not removed, and usage of this command doesn't even display a deprecation warning. 

The new recommended command additionally has _drastically_ different output

What's the plan here?

**Comment by isaacplmann** [comment]
Yes, it is deprecated.  The recommended command on the docs page needs to be updated to match recommended CLI command:

```
nx print-affected --type=app --select=projects
```
