### ISSUE TITLE
Convert an NX angular library component into web component

### ISSUE THREAD

**Issue by karanbedre** [nrwl/nx#14858]
I have created an NX-integrated mono repo with angular as the base application(store). I have also created an NX angular library(UI) in the same repo. I would like to convert angular library components into web components using angular/elements. 
I have not found any documentation regarding this. 

PS: I am able to convert app(store) components into web components using angular/elements.

**Project folder structure**

| apps
      store - able to convert components inside app store into web components using angular/elements
| libs
      UI - not able to convert

I am finding it difficult to convert the same with an angular library.  
Here is my package.json
{
  "dependencies": {
    "@angular/animations": "~14.2.0",
    "@angular/common": "~14.2.0",
    "@angular/compiler": "~14.2.0",
    "@angular/core": "~14.2.0",
    "@angular/elements": "^14.2.0",
    "@angular/forms": "~14.2.0",
    "@angular/platform-browser": "~14.2.0",
    "@angular/platform-browser-dynamic": "~14.2.0",
    "@angular/router": "~14.2.0",
    "@nrwl/angular": "14.6.4",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "webpack": "^5.75.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~14.2.0",
    "@angular-eslint/eslint-plugin": "~14.0.0",
    "@angular-eslint/eslint-plugin-template": "~14.0.0",
    "@angular-eslint/template-parser": "~14.0.0",
    "@angular/cli": "~14.2.0",
    "@angular/compiler-cli": "~14.2.0",
    "@angular/language-service": "~14.2.0",
    "@nrwl/cli": "14.6.4",
    "@nrwl/cypress": "14.6.4",
    "@nrwl/eslint-plugin-nx": "14.6.4",
    "@nrwl/jest": "14.6.4",
    "@nrwl/linter": "14.6.4",
    "@nrwl/nx-cloud": "latest",
    "@nrwl/workspace": "14.6.4",
    "@types/jest": "28.1.1",
    "@types/node": "16.11.7",
    "@typescript-eslint/eslint-plugin": "~5.33.1",
    "@typescript-eslint/parser": "~5.33.1",
    "concat": "^1.0.3",
    "cypress": "^10.2.0",
    "eslint": "~8.15.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "fs-extra": "^11.1.0",
    "jest": "28.1.1",
    "jest-environment-jsdom": "28.1.1",
    "jest-preset-angular": "~12.2.0",
    "ng-packagr": "~14.2.0",
    "nx": "14.6.4",
    "postcss": "^8.4.5",
    "postcss-import": "~14.1.0",
    "postcss-preset-env": "~7.5.0",
    "postcss-url": "~10.1.3",
    "prettier": "^2.6.2",
    "ts-jest": "28.0.5",
    "ts-node": "10.9.1",
    "typescript": "~4.7.2"
  }
}

**Comment by senthanal** [comment]
Would be very helpful to have project generator with this possibility, generating angular elements from the angular library.

**Comment by Coly010** [comment]
Feel free to correct me if I've misunderstood the Angular Docs, but only Angular applications can be used to create Web Components? https://angular.io/guide/elements#example-a-popup-service

This would appear to be a limitation from Angular itself rather than Nx.  

You could generate a new angular application specifically for the library you want to convert to a web component and follow the steps in the docs linked earlier in this comment to transform it into web component. You would just need to import the component from the library into the AppComponent
