### ISSUE TITLE
Support for @cloudflare/next-on-pages to deploy SSR apps to Cloud-flare pages

### ISSUE THREAD

**Issue by afaq-karim** [nrwl/nx#14857]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Currently, we don't have support to run or execute @cloudflare/next-on-pages in the NX mono repo because the nx executors are not allowed to use other packages except @nrwl 

## Motivation
Cloudflare is now supporting SSR apps to host in their platform using next js edge runtime which I believe many people are waiting for this

**Comment by AgentEnder** [comment]
This would be a good use case for a community plugin! Executors can be published by any npm package, see https://nx.dev/community

**Comment by NachoVazquez** [comment]
What does the team consider to be better? 

A community plugin or an option on the `@nx/next:build` executor to support custom Next builders.

For example, in the Nx source code, the `next build` command is called. I propose an optional property, `nextBuildCommand` that uses `next build` as the default. That way, we could be able to support other providers besides Vercel that want to support NextJS.

I would be willing to implement either a plugin or this adaptation. But I would like to hear what are the preferences of the team.

The following is a sample of the Next build executor at the moment of writing this comment.

```ts
  const args = createCliOptions({ experimentalAppOnly, profile, debug });
  const isYarnBerry =
    detectPackageManager() === 'yarn' &&
    gte(getPackageManagerVersion('yarn', workspaceRoot), '2.0.0');
  const buildCommand = isYarnBerry
    ? `yarn next build ${projectRoot}`
    : 'npx next build';

  const command = `${buildCommand} ${args.join(' ')}`;
  const execSyncOptions: ExecSyncOptions = {
    stdio: 'inherit',
    encoding: 'utf-8',
    cwd: projectRoot,
  };
  try {
    execSync(command, execSyncOptions);
  } catch (error) {
    logger.error(`Error occurred while trying to run the ${command}`);
    logger.error(error);
    return { success: false };
  }
```

**Comment by NachoVazquez** [comment]
I created a plugin that adds supports for this feature:

https://www.npmjs.com/package/@naxodev/nx-cloudflare

Any feedback is welcomed.
