### ISSUE TITLE
Importing nodejs modules in integrated repo --preset=ts is issuing the error @nrwl/nx/enforce-module-boundaries

### ISSUE THREAD

**Issue by LowArmour** [nrwl/nx#14853]
### Current Behavior

When I am importing nodejs modules in "@nrwl/node:application my-new-app" /src/main.ts, it gives the following error @nrwl/nx/enforce-module-boundaries.

I am using the integrated repo workspace.

For example when I am importing "path" or "fs" modules:
```
import * as path from 'node:path'
import fs from 'fs'
```
The above error is issued by eslint.

This does not happen when I am importing a module from package.json, such as:
`import { PDFDocument } from 'pdf-lib'`

### Expected Behavior

The eslint error @nrwl/nx/enforce-module-boundaries should not be issued when importing nodejs modules, just like any other package.json module.

### Steps to Reproduce

1. create an integrated repo workspace
2. choose typescript
3. install npm install -D @nrwl/node
4. nx g @nrwl/node:application my-new-app
5. in packages/my-new-app/src/main.ts, import a nodejs module

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : linux x64
   npm  : 8.19.3
   
   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : 15.6.3
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.6.3
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
The error issued by eslint is: packages/my-new-app/src/main.ts|1 col 1-34 error| [eslint] Projects should use relative imports to import from other files within the same project. Use "./path/to/file" instead of import from "node:path" (@nrwl/nx/enforce-module-boundaries)
```

**Comment by AgentEnder** [comment]
@meeroslav I think that you arleady have a fix for this? Is there a PR that can be tagged.

**Comment by meeroslav** [comment]
It's a slightly [different issue](https://github.com/nrwl/nx/issues/14571), but the [fix](https://github.com/nrwl/nx/pull/14846) is the same.

Closing it as a duplicate
