### ISSUE TITLE
@nrwl/rollup rollup executor returns outfile

### ISSUE THREAD

**Issue by cm-ayf** [nrwl/nx#14868]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
@nrwl/rollup:rollup currently does not return outfile like @nrwl/webpack:webpack or @nrwl/js:tsc, but there is a demand for that; bundling files into a native ES Module js for node instead of Webpack.

## Motivation
Because our project's production environment prefers native ES Module, output for production should be bundled by rollup, but this makes it difficult for @nrwl/js:node to accept the target as buildTarget (setting "format": ["esm", "cjs"] on rollup executor produces both esm and cjs file).

## Suggested Implementation
- Adding `outfile` in the return value of [rollupExecutor](https://github.com/nrwl/nx/blob/main/packages/rollup/src/executors/rollup/rollup.impl.ts#L108)
```diff
-             obs.next({ success: true });
+             obs.next({
                success: true,
                outfile: resolve(
                  context.root,
                  options.outputPath,
                  options.outputFileName
                ),
              });
```
*options.outputFileName could require some normalization

## Alternate Implementations
No other ideas.

**Comment by mandarini** [comment]
@cm-ayf thanks for submitting a feature request. I see you are willing to implement this feature! Please create a PR if you want, and tag me, and I'll take a look!
