### ISSUE TITLE
generatePackageJson does not include local publishable dependencies

### ISSUE THREAD

**Issue by LonguCodes** [nrwl/nx#14867]
### Current Behavior

When building an application with `generatePackageJson: true`, used publishable libraries should be included in the dependency list

### Expected Behavior

The libraries are omitted

### Steps to Reproduce

1. Generate new monorepo `yarn create nx-monorepo`
2. Generate any library and application (I used node:library i node:application `nx g @nrwl/node:application app && nx g @nrwl/library lib --publishable --importPath @test/lib`
3. Set `generatePackageJson` for the app to `true`
4. Add any usage of the lib `import '@test/lib'`
5. `nx build app`

### Nx Report

```shell
Node : 18.14.0
   OS   : linux x64
   yarn : 1.22.19
   
   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : 15.6.3
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.6.3
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by ndcunningham** [comment]
Hey, thanks for posting this issue will be addressed in the next release `15.7.3`

A workaround would be the run `npx nx build my-app --bundle=true`

Should this issue still exist after the release feel free to reopen the issue.
