### ISSUE TITLE
css problem after migration 15.4.4 => 15.6.3 

### ISSUE THREAD

**Issue by sancelot** [nrwl/nx#14871]
### Current Behavior

nx serve app does not render anymore css images (fontawsome / primereact ...)

and the message is displayed : 
The request url "myrepo/node_modules/@fortawesome/fontawesome-free/webfonts/fa-solid-900.woff2" is outside of Vite serving allow list.
The request url "myrepo/node_modules/@fortawesome/fontawesome-free/webfonts/fa-solid-900.ttf" is outside of Vite serving allow list.
The request url "myrepo/numalliance.com/node_modules/primeicons/fonts/primeicons.woff2" is outside of Vite serving allow list.

### Expected Behavior

no error and image rendered 

### Steps to Reproduce

1. either include fontawsome or primereact css in styles.css
```
@import 'primeicons/primeicons.css';
@import '@fortawesome/fontawesome-free/css/all.css';
```
2. render an icon in your application 
3. 

### Nx Report

```shell
Node : 16.18.0
   OS   : win32 x64
   npm  : 9.2.0

   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.6.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.6.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.6.3
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : 15.6.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by JulioC** [comment]
Might be related to the changes that caused https://github.com/nrwl/nx/issues/14378
