### ISSUE TITLE
ng g c myComponentName not creating SCSS files but CSS

### ISSUE THREAD

**Issue by jdavidhermoso** [nrwl/nx#1488]
Hi!

I am sorry for disturbing. I can't generate SCSS files using `ng g c myComponentName` command.

I know there were an issue opened related to that, but I could not make kit work following the same steps: [#158](https://github.com/nrwl/nx/issues/158)

I created a repo where it can be reproduced: https://github.com/jdavidhermoso/nx-not-generating-scss

These are the steps I followed:
1. Create workspace: `npx --ignore-existing create-nx-workspace myorg`
2. Add capability to create Angular Apps `ng add @nrwl/angular --defaults`
3. Create Angular App: `ng g @nrwl/angular:application todos`
4. Setting `styleext` prop to `scss`: `ng config 
schematics.@nrwl/schematics:component.styleext scss`
5. Generate component in the `todos` app: `ng g c myComponentName --project=todos`

I'm probably making something bad, but I can't figure out what.

Thanks in advance.

**Comment by kylecannon** [comment]
I am seeing the same issue too after the upgrade to v8

**Comment by vsavkin** [comment]
Since we moved all the angular functionality into `@nrwl/angular`, you need to change the collection.

So instead of 

```
Setting styleext prop to scss: ng config schematics.@nrwl/schematics:component.styleext scss
```

You need to do

```
Setting styleext prop to scss: ng config schematics.@nrwl/angular:component.styleext scss
```

**Comment by vsavkin** [comment]
@FrozenPandaz maybe we can update our migration to print a warning about `@nrwl/schematics` defaults in `angular.json`?

**Comment by tcoz** [comment]
Thank you for this one, I noticed it as well, wasn't sure if it was something I was doing wrong.

**Comment by jdavidhermoso** [comment]
Thanks, @vsavkin :)

**Comment by nukec** [comment]
thanks

**Comment by ilyasKerbal** [comment]
The solution is not working for `"@angular/cli": "9.1.0"`
