### ISSUE TITLE
Cypress Component Testing - styles excluded from build target if not a direct dependency

### ISSUE THREAD

**Issue by Tungsten78** [nrwl/nx#14881]
### Current Behavior

Styles get excluded from the component test unless the ct project is a direct dependency of the build target project.
Component Test in `shared-ui`.   `app` is the build target.

<img width="405" alt="image" src="https://user-images.githubusercontent.com/3805338/217654820-d334c5a9-4013-4451-a51f-be8167460c95.png">

@barbados-clemens indicated the [following code block](https://github.com/nrwl/nx/blob/master/packages/angular/plugins/component-testing.ts#L196-L200) in #12758.   Does the implementation account for transitive dependencies?

### Expected Behavior

Styles should be present.

### GitHub Repo

https://github.com/Tungsten78/nx-integrated-angular

### Steps to Reproduce

1. `nx component-test shared-ui --watch`

expected: black div from tailwind
actual: black div is absent, styles are missing

Workarounds:
- [add an import](https://github.com/Tungsten78/nx-integrated-angular/blob/84591107c0e44f28c87a8c17f181e1267aa4846d/apps/app/src/app/app.module.ts#L13)
- add `"implicitDependencies": ["shared-ui"]` to app's project.json

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 19.5.0
   OS   : darwin arm64
   npm  : 9.3.1
   
   nx : 15.6.3
   @nrwl/angular : 15.6.3
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by barbados-clemens** [comment]
Now looking into this. it seems that the `isCtProjectUsingBuildProject` util function only is checking direct dependencies. I'll PR a change here in a bit to make sure it checks for all project decedents, which should fix this for you.

**Comment by Tungsten78** [comment]
Thank you!
