### ISSUE TITLE
@nrwl/expo: `Missing package "metro"` error occurs when running `nx start my-app`

### ISSUE THREAD

**Issue by willdspd** [nrwl/nx#14897]
### Current Behavior

If I run the following commands:

1) `pnpm i -D @nrwl/expo --save-exact`
2) `nx g @nrwl/expo:app my-app`
3) `nx start my-app`

I get this error:

```
Error: Missing package "metro" in the project at: /Users/williamdespard/Desktop/glideshark/apps/my-app
This usually means "react-native" is not installed. Please verify that dependencies in package.json include "react-native" and run `yarn` or `npm install`.
Error: Missing package "metro" in the project at: /Users/williamdespard/Desktop/glideshark/apps/my-app
This usually means "react-native" is not installed. Please verify that dependencies in package.json include "react-native" and run `yarn` or `npm install`.
```

- I have all the necessary tools installed on my machine as referenced here: https://docs.expo.dev/get-started/installation/
- When using expo outside of my nx monorepo everything works fine.
- The following packages are successfully installed when running the second command above:

Deps
- "@expo/metro-config": "0.5.2",
- "@expo/webpack-config": "~0.17.4",
- "expo": "47.0.13",
- "expo-splash-screen": "~0.17.5",
- "expo-status-bar": "~1.4.2",
- "react-native": "0.70.5",
- "react-native-svg": "13.4.0",
- "react-native-svg-transformer": "1.0.0",
- "react-native-web": "~0.18.10",

Dev deps
- "@expo/cli": "0.4.11",
- "@nrwl/detox": "15.6.3",
- "@nrwl/expo": "15.6.3",
- "@testing-library/jest-dom": "5.16.5",
- "@testing-library/jest-native": "5.3.0",
- "@testing-library/react-native": "11.5.0",
- "@types/react-native": "0.70.7",
- "babel-preset-expo": "~9.2.2",
- "detox": "20.1.1",
- "eas-cli": "3.3.2",
- "expo-cli": "6.1.0",
- "jest-circus": "28.1.1",
- "metro-resolver": "0.74.1",

### Expected Behavior

This shouldn't throw an error

### Steps to Reproduce

Steps outlined above

### Nx Report

```shell
https://cloud.nx.app/runs/QX3GpjleRg
```

**Comment by xiongemi** [comment]
fixed and added e2e test in https://github.com/nrwl/nx/pull/15400
