### ISSUE TITLE
How to deploy (dist) a project containing server, client, and common lib

### ISSUE THREAD

**Issue by MingC0re** [nrwl/nx#1489]
I know this isn't a bug, but I wasn't able to find documentation/examples on how to run the NX (client, server, lib) solution with only the dist.   

# Prerequisites

Follow the example from NX website on setting up a server, client and lib

https://nx.dev/getting-started/what-is-nx 
https://nx.dev/getting-started/getting-started

## Expected Behavior

Once the solution(s) are compiled in production, relocate the ./dist folder to c:\proj\ and run a command to serve the system (client and server).

Could someone please provide step by step procedure on how to accomplish this.  It would be great if the example could bundle everything into one solution to include option for port and cert.

## Current Behavior

Tutorial only shows how to run the application with "ng serve myapp" which is great for development but does not work for production or distribution.

**Comment by vsavkin** [comment]
Hi there,

Deploying is very env specific and depends where you are deploying the code too. For instance, if you are serving the frontend code using the server you author in the same repo, you could copy `dist/apps/client` into `dist/apps/server` and then push that to say Azure cloud.

More likely, though, you will deploy your client and server code separately. The `dist/apps/client` will probably be deployed to some CDN, and `dist/apps/server` to some cloud provider. 

Thanks!
Victor

**Comment by MingC0re** [comment]
Thanks for the reply.  For my specific use case I'd like to deploy both server and client as a single app with the uses of http-server, lite-server, or any other that you'd recommend.   

As per the recommendation, I copied the content of client into ./dist/apps/server.  This resulted in conflicting files that had to be overridden (main.js, main.js.map, and stats.json).  This probably isn't the correct way so I tried copying the client folder into ./dist/apps/server/client/.  When running lite-server in the new client directory, the system loads the initial page but I'm getting a 404 Not Found.    I believe Angular is running but the back-end express server is still not started and/or requests are being denied.

This only happens when trying to deploy the system without the source code.  I'm able to run the server and client without issue in the dev environment (ng serve server and ng serve client).  

Could you provide an example of how to run this using the example solution from the NX tutorial.  My setup is essentially the same.

Thanks in advance.

**Comment by Ibraheem-adeyemo** [comment]
I'm also facing exactly the same issue.
