### ISSUE TITLE
Updating global yarn.lock file always affects all projects in yarn monorepo and invalidates cache

### ISSUE THREAD

**Issue by sam-revanoor** [nrwl/nx#14891]
### Current Behavior

When we add a package to a specific app/library and run `yarn`, the global `yarn.lock` file is updated (expected).
However, when we then run NX affected, it runs it for all services in the monorepo and invalidates cache.

We tried excluding the `yarn.lock` from the task inputs and added empty `implicitDependencies` but this did not help:
```json
  "targetDefaults": {
    "lint": {
      "inputs": ["default", "{workspaceRoot}/.eslintrc.json", "!{workspaceRoot}/yarn.lock"]
    }
  },
  "implicitDependencies": {},
```

### Expected Behavior

We expect NX affected to only run for the app/library that has a modified `package.json` file and ignore changes to global `yarn.lock`.

We have a monorepo with over 120 projects and this behaviour triggers the worst-case scenario on our pipelines, which happens frequently as developers add dependencies to services often.

### GitHub Repo

https://github.com/kuba-gaj/nx-lock-affected

### Steps to Reproduce

1. Clone the repo above
2. Run `yarn`
3. `cd packages/is-odd`
4. `yarn add 'just-diff'` (example package, any package can be added)
5. `git status` shows:
```
        modified:   packages/is-odd/package.json
        modified:   yarn.lock
```
6. Run `yarn nx print-affected --target=lint --uncommitted --select=projects`. This shows:
```
is-odd, service1-e2e, service2-e2e, service1, service2, is-even
```

### Nx Report

```shell
Node : 14.17.6
   OS   : darwin x64
   yarn : 3.4.1
   
   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : 15.6.3
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.6.3
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Additional Information

We created the example repo following the NX tutorial for integrated repo. We added two libraries and two apps using nrwl generators. This works as expected with NPM as it creates a `package-lock.json` file for each individual project, whereas yarn always updates the root-level `yarn.lock` file.

**Comment by kuba-gaj** [comment]
Hi, this is negatively affecting our pipelines. I'm happy to discuss potential solutions and work on a fix if needed.

Thank you for your work on this project!

**Comment by kuba-gaj** [comment]
We are investigating switching to pnpm and the same problem exists. Any change to global lock file (in this case, `pnpm-lock.yaml`) makes `nx affected` include all projects and libraries, even though it is excluded from `inputs` and `implicitDependencies`

**Comment by kuba-gaj** [comment]
This is related (or even duplicate) of this one here: https://github.com/nrwl/nx/issues/15116

**Comment by meeroslav** [comment]
Closing this as a duplicate to #15116
