### ISSUE TITLE
why ViewEncapsulation.None

### ISSUE THREAD

**Issue by zpydee** [nrwl/nx#149]
A question: why have you chosen to use ViewEncapsulation.None in your schematics? This loses the capability to restrict class styles to a per component basis?

**Comment by mrmeku** [comment]
I agree (especially since NX creates a monorepo containing any number of components whose styles could collide with one another). where style collisions . I think that we should default to using ViewEncapsulation.Emulated personally

**Comment by jschwarty** [comment]
I think this came over from a copy of the schematics option from the Angular CLI at the time when that was configured in there as a default (something that has been fixed in the Angular CLI). We just need to update the Nx schematic to remove that default of "none".

**Comment by ankemp** [comment]
From what I've experienced, it only places the `ViewEncapsulation.None` on the `app.component.ts` in the root of each of your apps.
