### ISSUE TITLE
wrapAngularDevkitSchematic('@nrwl/angular', 'remote') affects multiple projects.json

### ISSUE THREAD

**Issue by sac-cas** [nrwl/nx#14910]
### Current Behavior

Running my custom generator wrapping an existing generator (@nrwl/angular:remote) affects all `project,json` of my workspace.

### Expected Behavior

Wrapping an existing generator does only affect the new app and the host config.

### Steps to Reproduce

1. Create local generator witch wraps @nrwl/angular:remote:
```
const appGenerator = wrapAngularDevkitSchematic('@nrwl/angular', 'remote');
await appGenerator(tree, { name: 'foo', host: 'bar' });
```
2. Run the generator with `nx g @<workspace>/<lib>:test-generator` creates the remote as expected but also affects all `project.json` files of this workspace. Running the generator with `nx g @nrwl/angular:remote foo --host=bar` works fine.

### Nx Report

```shell
nx report                                                       
 >  NX   Report complete - copy this into the issue template

   Node : 18.14.0
   OS   : darwin arm64
   pnpm : 7.27.0
   
   nx : 15.6.3
   @nrwl/angular : 15.6.3
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 15.6.3
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.6.3
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
         @caipi/plugins
   ---------------------------------------
   Community plugins:
         @fortawesome/angular-fontawesome: 0.12.1
         @compodoc/compodoc: 1.1.19
         @storybook/angular: 6.5.16
```

**Comment by AgentEnder** [comment]
What behaviors are you seeing when you say it "affects" multiple project.json files? `wrapAngularDevkitSchematic` goes through Nx's compatibility layer which requires inlining + rebreaking up `angular.json`, hence listing the project.json files as changed even if they are not.

In any case, @nrwl generators are written as generators and should be imported directly without `wrapAngularDevkitSchematic`.

**Comment by sac-cas** [comment]
The `project.json` contains some lines in the `build` and `lint` configuration:
```
"dependsOn": ["^build"],
 "inputs": ["production", "^production"],
....
"inputs": ["default", "{workspaceRoot}/.eslintrc.json"],
```

and an `files` array on root level:
```
"files": [
    {
      "file": "apps/<myApp>/.eslintrc.json",
      "hash": "96cf98cfcde4db156c57311e2bf5dc4b5881f271"
    },
....
```

But your advice is right: importing the generator made it work as expected: 
```
await remote(tree, options);
```

Thank you!
