### ISSUE TITLE
Docs: Typo on Getting Started Docs 

### ISSUE THREAD

**Issue by iamkdev** [nrwl/nx#1492]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

On https://nx.dev/getting-started/nx-and-cli has a typo.

![image](https://user-images.githubusercontent.com/1850968/59552700-0143a980-8fa8-11e9-8455-e26588dfeaa9.png)

## Expected Behavior

`ng add @nrwl/angular`

## Current Behavior

`ng addd @nrwl/angular`

**Comment by FrozenPandaz** [comment]
Thanks for the report! This will be fixed next time we publish the site.
