### ISSUE TITLE
Migrating Existing React Native App to Nx

### ISSUE THREAD

**Issue by rdick** [nrwl/nx#14929]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ X] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

There is no up to date documentation on how to migrate an existing React Native Application (not expo) to NX workspace. If this is provided it would be greatly appreciated. There was a previous document create by Jack Hsu that is out of date now. This article is here https://blog.nrwl.io/introducing-react-native-support-for-nx-48d335e90c89.

**Comment by xiongemi** [comment]
currently there is no easy way to migrate it over. the easiest way to to do it just create a new nx workspace, the move your current source file over into to app's source file. this might be a feature request to have a command similar to the one in @nrwl/react.
