### ISSUE TITLE
Newly created angular application has node references

### ISSUE THREAD

**Issue by Brocco** [nrwl/nx#14930]
### Current Behavior

When creating a new workspace (`--preset angular`) reference to common JS features, specifically `setTimeout` are being recognized as Node, not web/browser.

See the steps below for more details.

### Expected Behavior

The inferred type of `setTimeout` should be `number`.

### Steps to Reproduce

1. Create a workspace: `npx create-nx-workspace@latest foo --preset angular` (accept default values)
2. Open the newly generated workspace and add this code to app.component.ts
```
constructor() {
  const foo: number | undefined = setTimeout(() => console.log('foo'), 10);
  console.log(foo);
}
```
3. In the editor this shows an error as the return type of `setTimeout` is `NodeJs.Timeout` which is the node version of the function so the error is that the types are not compatible. To be clear this is not an editor issue as the same error is returned as a result of running a build in the terminal.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.14.0
   OS   : linux x64
   npm  : 9.3.1

   nx : 15.6.3
   @nrwl/angular : 15.6.3
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
Error: apps/demo/src/app/app.component.ts:12:11 - error TS2322: Type 'Timeout' is not assignable to type 'number'.

12     const foo: number | undefined = setTimeout(() => console.log('foo'), 10);
             ~~~
```

**Comment by Brocco** [comment]
Thanks for taking a deeper look, I just re-created an example repo [here](https://github.com/Brocco/nx-angular-repro). Hopefully this helps.

The command I used to build is: `npx nx run foo:build`

node version is 18.12.1
npm version is 9.3.1

**Comment by Coly010** [comment]
That's very interesting. The workaround I had for a standalone Angular application isn't working in your reproduction repo 🤔

I'll need to spend a bit more time on this, this is strange behaviour. Thanks for raising this issue!

**Comment by leosvelperez** [comment]
hey @Brocco!

I tracked this issue down to an RxJs issue https://github.com/ReactiveX/rxjs/issues/7072. This has been solved in RxJs 7.6.0+, so make sure to bump its version to get your build to pass.

The IDE would still show up the issue but your build will succeed. I'll work on a fix for the editor.

**Comment by Brocco** [comment]
Can confirm this is working locally for me as well.

Would the solution be to update the schematic/builder for new this configuration to reference this newer version in the generated package.json file? (or at least a potential solution)

**Comment by leosvelperez** [comment]
Yes, I'll bump the version that gets generated shortly in a PR. A separate fix would be needed for the editor.
