### ISSUE TITLE
[@nrwl/js:tsc] transformers option does not resolve workspace-local packages

### ISSUE THREAD

**Issue by dannymcgee** [nrwl/nx#14943]
### Current Behavior

The `transformers` option of the `@nrwl/js:tsc` executor fails to resolve packages that aren't present in `node_modules`, even if a matching package exists in the Nx workspace

### Expected Behavior

The executor checks for matching Nx workspace packages when trying to resolve custom transformers

### GitHub Repo

https://github.com/dannymcgee/nx-tsc-workspace-local-transformers-repro

### Steps to Reproduce

1. Clone the attached minimal repro repo
2. Install dependencies with `pnpm`
3. Run `pnpm nx build consumer`
   * Note the warning about not being able to find `@repro/transformer`
5. Check the build output for `@repro/consumer`
   * Note that `src/index.js` only has the `"use strict"` directive
6. Run `pnpm link ./dist/packages/transformer` to symlink the built `transformer` package to `node_modules`
7. Run `pnpm nx build consumer --skip-nx-cache`
   * Note the build completes with no warnings
8. Check the build output for `@repro/consumer`
   * Note that `src/index.js` now includes a call to `console.log("Hello, world!")` due to the transformer

### Nx Report

```shell
Node : 18.13.0
   OS   : win32 x64
   pnpm : 7.26.2

   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
"@repro/transformer" plugin could not be found!
@repro/transformer is not a Transformer Plugin. It does not provide neither before(), after(), nor afterDeclarations()
```

### Additional Information

I suppose this could be considered a feature request, but I _was_ genuinely surprised that it didn't work when I attempted it, so I guess that qualifies as "unexpected behavior." 🙂 

I think implementing this would create more internal consistency within the Nx ecosystem, since this type of intra-workspace awareness already works for many other features (like, for example, being able to use executors and generators from a workspace-local Nx plugin package without needing to build and link it first).

I'd be happy to help implement the fix with a PR if there are no objections. I tracked down the source of the issue to [this line](https://github.com/nrwl/nx/blob/3f65438208bea5207cb49b9b5cdbf56164b3344e/packages/js/src/utils/typescript/load-ts-transformers.ts#L36). The following is an outline for a proposed fix, but please let me know if there's anything I've failed to consider:

* Find all workspace projects that meet these conditions:
  * Has a `build` target defined
  * Has a `package.json` file
  * `package.json` name field matches a provided transformer name
* For each found match:
  * Add it to the consuming project's dependency graph if it's not already there
    * If that's not possible at this stage of the build, log a warning asking the user to add it to the consuming project's `implicitDependencies`
  * Look up the output directory for the matching project's `build` target
  * Add that directory to the `nodeModulePaths` array linked above
  
If there are performance concerns about doing all that eagerly, it could instead be postponed until the happy-path `node_modules` resolution fails [at this point](https://github.com/nrwl/nx/blob/3f65438208bea5207cb49b9b5cdbf56164b3344e/packages/js/src/utils/typescript/load-ts-transformers.ts#L48).

**Comment by nartc** [comment]
Hey @dannymcgee, thanks for bringing this up. I'm happy to review the PR if you're down to implementing this.
