### ISSUE TITLE
Angular module federation show blank page

### ISSUE THREAD

**Issue by madipta** [nrwl/nx#14942]
### Current Behavior

host showing blank page
remote works fine

### Expected Behavior

host not show a blank page 

### Steps to Reproduce

1. yarn create nx-workspace ecom --preset=empty
2. yarn add -W -D @nrwl/angular
3. yarn nx g @nrwl/angular:host dashboard --remotes=home
4. yarn nx serve dashboard --open (also try yarn nx serve dashboard --open --devRemotes=home)

### Nx Report

```shell
Node : 18.14.0
   OS   : win32 x64
   yarn : 1.22.19

   nx : 15.6.3
   @nrwl/angular : 15.6.3
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
```

### Failure Logs

```shell
Compiled successfully.
(node:11184) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by Coly010** [comment]
I cant reproduce this in latest version of Nx.

Can you retry with the latest?

If you follow the same repo steps you have provided here, you will need to run the following after `yarn add -W -D @nrwl/angular`


`yarn add -D @angular-devkit/core @angular-devkit/build-angular @angular-devkit/schematics @schematics/angular`
`yarn add rxjs`

**Comment by Coly010** [comment]
Alternatively, you can just run `nx migrate latest && nx migrate --run-migrations` in your workspace

**Comment by madipta** [comment]
yes it works now with nx 15.7.1

thank you
