### ISSUE TITLE
Vite executor doesn't replace TSConfig paths for buildable libraries

### ISSUE THREAD

**Issue by pulecka** [nrwl/nx#14955]
### Current Behavior

Vite executor doesn't replace TSConfig paths for buildable libraries with build output paths.
This leads to `TS6059` Typescript errors (`File is not under 'rootDir'`) whenever you try to run type check on library which depends on another buildable library.

### Expected Behavior

Vite executor would replace TSConfig paths for buildable libraries with build output paths.

### GitHub Repo

https://github.com/pulecka/nx-vite-buildable-libs

### Steps to Reproduce

1. run `npm install`
2. run `npm run build` (this is alias for `nx run is-odd:build --skip-nx-cache` command)
3. see `TS6059` errors in output

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 19.4.0
   OS   : darwin x64
   npm  : 9.2.0

   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.6.3
   @nrwl/vite : 15.6.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
> nx run is-odd:build

vite v4.0.4 building for production...
✓ 4 modules transformed.
../../dist/packages/is-odd/index.mjs  0.10 kB │ gzip: 0.09 kB
../../dist/packages/is-odd/index.js  0.15 kB │ gzip: 0.15 kB

[vite:dts] Start generate declaration files...
packages/is-even/src/index.ts:1:15 - error TS6059: File '/Users/pulecka/Developer/nx-vite-buildable-libs/packages/is-even/src/lib/is-even.ts' is not under 'rootDir' '/Users/pulecka/Developer/nx-vite-buildable-libs/packages/is-odd'. 'rootDir' is expected to contain all source files.

1 export * from './lib/is-even';
                ~~~~~~~~~~~~~~~
packages/is-odd/src/lib/is-odd.ts:1:24 - error TS6059: File '/Users/pulecka/Developer/nx-vite-buildable-libs/packages/is-even/src/index.ts' is not under 'rootDir' '/Users/pulecka/Developer/nx-vite-buildable-libs/packages/is-odd'. 'rootDir' is expected to contain all source files.

1 import { isEven } from '@pulecka/is-even';
                         ~~~~~~~~~~~~~~~~~~

[vite:dts] Declaration files built in 863ms.
```

**Comment by pulecka** [comment]
I can tackle this as it is a blocking issue for us adopting Vite.
My initial thought is to:
- move `vite-tsconfig-paths' & 'vite-plugin-dts` plugins from user config to executor as they need to access the updated paths/tsconfig
- calculate the paths using some utils from `utilities/buildable-libs-utils`
- pass the updated tsconfig to  `vite-tsconfig-paths' &  'vite-plugin-dts` plugins in the executor

which all seems like a large/breaking change so it would be great if someone from the core team would confirm that this is the right direction

**Comment by mandarini** [comment]
@pulecka thanks for this issue. I am looking into it now.

**Comment by mandarini** [comment]
[Here is my reproduction repository](https://github.com/mandarini/nx-packages-import-paths), using Nx version `15.7.0-beta.5`. Imports seem to work. Can you check out my repo, and then try updating your repo to that version using `nx migrate 15.7.0-beta.5` and let me know if it works?

**Comment by mandarini** [comment]
Hmmmm, I am wrong, I am getting that error when I build the libraries individually. Looking into it a bit more!

**Comment by mandarini** [comment]
Ok, found the issue. Putting in a PR now.

[Here's the solution to the issue.](https://github.com/pulecka/nx-vite-buildable-libs/pull/2)

**Comment by pulecka** [comment]
Fix in the linked PR solves the Typescript errors in output logs but the resulting DTS files are not in list folder (see logs below).

```
> nx run is-odd:build

vite v4.0.4 building for production...
✓ 4 modules transformed.
../../dist/packages/is-odd/index.mjs  0.10 kB │ gzip: 0.09 kB
../../dist/packages/is-odd/index.js  0.15 kB │ gzip: 0.15 kB

[vite:dts] Start generate declaration files...
[vite:dts] Declaration files built in 15ms.

 >  NX   Successfully ran target build for project is-odd and 1 task it depends on (3s)

pulecka@ ~/Developer/nx-vite-buildable-libs ((51b77027)|✔) > ls -a dist/packages/is-odd
./            ../           index.js      index.mjs     package.json
```

Also the timing (`[vite:dts] Declaration files built in 15ms.`) looks too quick - even with `skipDiagnostics: true` the DTS step did run at least about `500ms` on my machine.

**Comment by mandarini** [comment]
Did you try running with `skipNxCache`?

**Comment by mandarini** [comment]
Also, what are you expecting to see in the dist folder? Can you try and tweak the `dts` plugin settings to see if you get the desired result?

**Comment by pulecka** [comment]
Yes, I just cut out that part from the output log for brevity. Full output:
```
pulecka@ ~/Developer/nx-vite-buildable-libs ((51b77027)|✔) > npm run build

> nx-vite-buildable-libs@0.0.0 build
> nx run is-odd:build --skip-nx-cache


   ✔    1/1 dependent project tasks succeeded [0 read from cache]

   Hint: you can run the command with --verbose to see the full dependent project outputs

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


> nx run is-odd:build

vite v4.0.4 building for production...
✓ 4 modules transformed.
../../dist/packages/is-odd/index.mjs  0.10 kB │ gzip: 0.09 kB
../../dist/packages/is-odd/index.js  0.15 kB │ gzip: 0.15 kB

[vite:dts] Start generate declaration files...
[vite:dts] Declaration files built in 37ms.


 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target build for project is-odd and 1 task it depends on (3s)
 ```

**Comment by mandarini** [comment]
@pulecka I see what you mean. Can you try to tweak the `dts` plugin settings to see if you get what you expect? Also, I see that if we set `skipDiagnostics: true` it works, however I understand that the output is not consistent.

So, I will look into this more tomorrow, but two questions for now:

1. Is there a set of settings for the `dts` plugin that produce for you the desired output?
2. Does using `skipDiagnostics: true` has a different effect?

**Comment by pulecka** [comment]
1. ok, so this config for the dts plugin seems to work without errors & results in `d.ts` files being generated (i.e. `dist/packages/is-odd` contains `index.js` and `index.d.ts`) 
basically what was needed was to "rebase" some options from `tsconfig.lib.json` to the new `root` path - e.g. `include: ['src/**/*.ts']` doesn't match anything when applied from root folder so we need to put full path there (such as `include: ['packages/is-odd/src/**/*.ts']`)

```
dts({
  root: '../../',
  entryRoot: 'packages/is-odd/src',
  tsConfigFilePath: 'packages/is-odd/tsconfig.lib.json',
  include: ['packages/is-odd/src/**/*.ts'],
  outputDir: 'dist/packages/is-odd',
  skipDiagnostics: false,
  noEmitOnError: true,
}),
```

2. with `skipDiagnostics: true` the config can be a bit simplified.
since the original `rootDir` error only happens during type check, which is not run with `skipDiagnostics` - the `root` config option is not needed at all and the following config results in the same output as the one above.
downside is that you need to run type check in another command which could be slower or more cumbersome depending on a given project setup.

```
dts({
  entryRoot: 'src',
  tsConfigFilePath: 'tsconfig.lib.json',
  skipDiagnostics: true,
}),
```

**Comment by mandarini** [comment]
Perfect, thank you @pulecka ! I'll update my PR and add some documentation around this!
