### ISSUE TITLE
upgrade to ngrx 8

### ISSUE THREAD

**Issue by alexanderPastornicky** [nrwl/nx#1496]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

For example.. after generating actions I want to use createAction()

## Current Behavior

There is used old style with enums, classes, type and so on

**Comment by mehrad-rafigh** [comment]
With Nx 8.3 the new ngrx Syntax has arrived. 
For more information refer to the medium article from @brandonroberts 
https://blog.nrwl.io/updated-schematics-for-ngrx-and-improved-logging-in-nx-8-3-2b00c8ef6123

This issue can be closed right?

**Comment by juristr** [comment]
@alexanderPastornicky you have to pass the `--syntax=creators` afaik, like

```
ng g @nrwl/angular:ngrx issues --module=apps/nxv8app/src/app/app.module.ts --syntax=creators --defaults
```

**Comment by alexanderPastornicky** [comment]
https://github.com/nrwl/nx/pull/1650

**Comment by brandonroberts** [comment]
The PR for clarifying usage with the creators syntax is still open, but this issue has been resolved.
