### ISSUE TITLE
Update docs that Tailwind with Dynamic MFE requires implicitDependencies to be set

### ISSUE THREAD

**Issue by benpsnyder** [nrwl/nx#14970]
### Documentation issue

- [X] Documentation improvement

### Is there a specific documentation page you are reporting?

https://nx.dev/recipes/other/using-tailwind-css-with-angular-projects#using-tailwind-css-with-angular-projects

### Additional context or description

Given:
- Dynamics MFE where we have commented out static imports from `module-federation.config.js`
![image](https://user-images.githubusercontent.com/707567/218549898-1f84d181-de76-4e50-ae32-c24b2c742a4c.png)
- We use this `module-federation.manifest.json` for development
![image](https://user-images.githubusercontent.com/707567/218550280-c5123ee7-d60a-4e88-973f-245a7511dd95.png)
- We use this "non-dev" manifest for production/staging deployment
![image](https://user-images.githubusercontent.com/707567/218550370-4090bd81-ae85-430b-a59a-5aabf874d9a8.png)
- We use `stylePreprocessorOptions` in the shell/host MFE to source a SCSS down in a shared lib
![image](https://user-images.githubusercontent.com/707567/218550926-b977e1f5-3d8a-40a2-98db-eb45098dc07e.png)
- Which allows us to use this one-liner in the shell/host MFE's styles.scss
![image](https://user-images.githubusercontent.com/707567/218551021-cd4c4efb-3947-477d-b3ed-066fa27f165c.png)
- Down in the library, we use SCSS like so:
![image](https://user-images.githubusercontent.com/707567/218551158-3c54107b-3499-463c-9765-aae596444a3f.png)
![image](https://user-images.githubusercontent.com/707567/218551193-2574576f-b0fa-4293-bb93-f0bb187cbd4c.png)
![image](https://user-images.githubusercontent.com/707567/218551220-f2fcfbeb-10b4-4eb8-b553-d4f715663fa2.png)
(note that pbsh-overrides.scss is at the end)
- Finally I'll share our simple tailwind config file:
![image](https://user-images.githubusercontent.com/707567/218551401-d6a31da3-4f95-44d7-a2b1-9cb135ad1de9.png)
- and note that our libraries are in fact sourcing the workspace shared preset
![image](https://user-images.githubusercontent.com/707567/218551474-34c46958-da5e-463a-bbb2-ef6ae1f5c483.png)

I believe we should document that, in a Dynamic MFE situation, Tailwind and associated libraries like DaisyUI will not work correctly without the implicit dependency being set.
![image](https://user-images.githubusercontent.com/707567/218551699-660f4d2b-4b03-4acd-96b1-2fcfa0f75638.png)
![image](https://user-images.githubusercontent.com/707567/218552086-1d4156f5-271e-438e-9b07-027e0e41cbe7.png)

**Comment by Coly010** [comment]
this should occur in static module federation also.

It's because of how Tailwind itself functions. Tailwind scans the files in your application to extract the classes that it needs to keep after it does its `purge` step.

You don't _have_ to use implicit dependencies here, you can just add another path to the tailwind config. however, implicit dep will ensure the host application will get rebuilt, allowing for tailwind to find any new classes that have been added to the HTML. 

I can update the docs
