### ISSUE TITLE
Nrwl/Nx workspace with Test framework option - Don't want Jest and Cypress.

### ISSUE THREAD

**Issue by SWGeekPD** [nrwl/nx#1498]
When I am creating Nx workspace for angular application it is taking Jest as a test runner and Cypress for e2e testing. 
I don't want to use Cypress and Jest . How can I have any other test framework in workspace.
Do we have any command to choose test framework while creating workspace.
Please suggest.

**Comment by FrozenPandaz** [comment]
There is no command but you can do it 2 steps:

```sh
npx create-nx-workspace@latest my-proj
cd my-proj
ng add @nrwl/angular # This will prompt for a unit test runner and e2e test runner
ng g app app1
```

**Comment by SWGeekPD** [comment]
This doesn't solve the problem.
1. npx create-nx-workspace@latest my-proj
executing above command create a worspace and the App inside the workspace with all the Jest configuration.
And it is not prompting for any test framework selection.
