### ISSUE TITLE
15.7.0 migration /  @nrwl/workspace:fix-configuration fails for workspace without "root" property

### ISSUE THREAD

**Issue by kklocker** [nrwl/nx#14986]
### Current Behavior

tried to migrate workspace, but it failed in the migration script
```
Failed to run 15-7-0-split-configuration-into-project-json-files from @nrwl/workspace. This workspace is NOT up to date!
 >  NX   The "path" argument must be of type string. Received undefined
``` 

### Expected Behavior

Migration should work :+1:

### Steps to Reproduce

I tried to run `npx nx g @nrwl/workspace:fix-configuration --all --verbose`
and got the following output:

```bash
 >  NX   The "path" argument must be of type string. Received undefined


TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at join (node:path:429:7)
    at <PATH>\node_modules\@nrwl\workspace\src\generators\convert-to-nx-project\convert-to-nx-project.js:59:50
    at Generator.next (<anonymous>)
    at fulfilled (<PATH>\node_modules\@nrwl\workspace\node_modules\tslib\tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I think the main problem here is the expected format of `workspace.json`, It seems that it expects a "root" - property for the projects, but this is apparently missing.

From `convert-to-nx-project.js`: ![image](https://user-images.githubusercontent.com/25065744/218750500-199ca943-584f-4e23-b053-896bc995ab72.png)

The workspace.json looks ~ like this, where `shared` and `styleguide` lives in `libs/`, and `myApp` is defined in `apps/`
```json
{
    "defaultProject": "myApp",
    "projects": {
        "myApp": {
            "tags": ["myApp"]
        },
        "shared": {
            "tags": ["shared"]
        },
        "styleguide": {
            "tags": ["shared"]
        }
    },
    "$schema": "./node_modules/nx/schemas/workspace-schema.json"
}

```

### Nx Report

```shell
Node : 16.13.1
   OS   : win32 x64
   yarn : 3.2.1

   nx               : 15.7.0
   @nrwl/jest       : 15.7.0
   @nrwl/linter     : 15.7.0
   @nrwl/workspace  : 15.7.0
   @nrwl/angular    : 15.7.0
   @nrwl/cli        : 15.7.0
   @nrwl/cypress    : 15.7.0
   @nrwl/devkit     : 15.7.0
   @nrwl/js         : 15.7.0
   @nrwl/tao        : 15.7.0
   @nrwl/webpack    : 15.7.0
   typescript       : 4.9.4
   ---------------------------------------
   Community plugins:
   @ngrx/effects        : 15.0.0
   @ngrx/entity         : 15.0.0
   @ngrx/store          : 15.0.0
   @ngrx/store-devtools : 15.0.0
   eslint-plugin-ngrx   : 2.1.2
```

### Additional Information

**EDIT**: It seems that, after the proper "root" - property was added in `workspace.json`, the schematic simply deleted the file 🤷‍♂️🤷‍♂️. After that, i could run some further migrations :)

**Comment by AgentEnder** [comment]
The `root` property is required in `workspace.json`, that file appears to have been invalid. The `tags` property should be inside the `project.json` file or `package.json` (under an nx key) for the projects. 

I'm going to close this out. Unfortunately migrations don't always work for configs that are not correct before they run, and in those cases the route we go is generally to answer questions / provide guidance as to what the migration was doing and mitigation steps.

**Comment by kklocker** [comment]
Suspected that was the case :) However there has only been nx-migrations touching this file, so there is probably a migration somewhere that has messed up the file. Would perhaps also be nice with some user-feedback on missing required props in config files? :)
