### ISSUE TITLE
VSCode TSLint official plugin not working

### ISSUE THREAD

**Issue by alfaproject** [nrwl/nx#1500]
## Expected Behavior

Linting works in VSCode using the official TSLint plugin: [ms-vscode.vscode-typescript-tslint-plugin](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin)

## Current Behavior

Linting is not working in VSCode using the official TSLint plugin.

## Failure Information (for bugs)

Checking TS Server logs in VSCode I get this trace:
```
Info 591  [15:33:27.766] [typescript-tslint-plugin] "(runTsLint) start"
Info 592  [15:33:27.767] [typescript-tslint-plugin] "(runTsLint) Loaded tslint library"
Info 593  [15:33:27.767] [typescript-tslint-plugin] "(runTsLint) About to validate /test/test.ts"
Info 594  [15:33:27.767] [typescript-tslint-plugin] "(doRun) starting validation for test.ts"
Info 595  [15:33:27.767] [typescript-tslint-plugin] "(doRun) Changed directory to /test"
Info 596  [15:33:27.767] [typescript-tslint-plugin] "(doRun) About to getConfiguration"
Info 597  [15:33:27.767] [typescript-tslint-plugin] "(getConfiguration) Starting for /test/test.ts"
Info 598  [15:33:27.767] [typescript-tslint-plugin] "(doRun) Configuration fetched"
Info 599  [15:33:27.767] [typescript-tslint-plugin] "(doRun) Linting: start linting"
Info 600  [15:33:27.770] [typescript-tslint-plugin] "tslint error ENOENT: no such file or directory, open '/test/node_modules/typescript/lib/angular.json'"
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a new nx workspace
2. Configure VSCode to use the workspace TypeScript version using the status bar or by adding this to `settings.json`: `"typescript.tsdk": "node_modules/typescript/lib"`
3. Verify that the linting stops working within VSCode

If I remove `"rulesDirectory": ["node_modules/@nrwl/workspace/src/tslint"]` from `tslint.json` then linting works again.

**Comment by vsavkin** [comment]
The issue has been fixed in 8.2.
