### ISSUE TITLE
NX cloud won't upload cache result generated in CI runs (in Github Actions)

### ISSUE THREAD

**Issue by appleearth008** [nrwl/nx#15003]
### Current Behavior

Hey, have a question, can Nx cloud use cache result derived from CI runs? based on this post (https://nx.dev/core-features/share-your-cache), I saw that we can use cache results in CI from a local machine, but not the opposite.

In short, I wanna use a cache result generated in my CI run, and hope this cache result can be uploaded to Nx cloud server so that in the future, it can be used either in CI or locally.

========================
ps: sorry, if this is not a bug.

### Expected Behavior

NX cloud should also be able to use cache result generated in CI in addition to cache result generated locally on a machine.

### Steps to Reproduce

1. seen above

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.13.0
   OS   : darwin x64
   yarn : 1.22.19
   
   nx : 15.2.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.2.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.4
   @nrwl/js : 15.2.4
   @nrwl/linter : 15.2.4
   @nrwl/nest : 15.2.4
   @nrwl/next : 15.2.4
   @nrwl/node : 15.2.4
   @nrwl/nx-cloud : 15.0.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.2.4
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.2.4
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.2.4
   @nrwl/web : 15.2.4
   @nrwl/webpack : 15.2.4
   @nrwl/workspace : 15.2.4
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nx-tools/nx-prisma: 2.0.0-alpha.4
```

**Comment by meeroslav** [comment]
Actually, this is how it already works. 

You will always benefit from runs on CI (both for subsequent CI runs and local runs) as long as you have a read-write token set in the `nx.json` or on your `CI`. 

Your local runs can only send cache to Nx Cloud if you set up a read-write token in `nx.json`. Hope that helps

**Comment by appleearth008** [comment]
Thanks for your comment. 
I agree with what you said. In fact, what fails in my CI is that Nx cloud computes a different cache for a project even if I didn't change anything for that project. so it tests that project every time instead of using the previous cache.
I will open another issue bc I think it is not related to this one.

**Comment by appleearth008** [comment]
@meeroslav 
Hey, I have a follow up question, in this doc: https://nx.dev/core-features/share-your-cache, at the top it says:
`You can either build an implementation of the cache or use Nx Cloud.`

How can I build an implementation of the cache and let NX cloud upload it and share it across CIs and different locals?
I may misunderstand this statement.

**Comment by meeroslav** [comment]
What that sentence means is that you can either use `Nx Cloud` and `@nrwl/nx-cloud` task runner for remote caching or build everything yourself.

The runner is rather simple, it will make an HTTP call to Nx Cloud API asking if there is a cache for a specific task (each task has task details and a unique hash). If there is, it will ask for the cached logs and artifacts (if any) and will replay them back on your local machine or CI. Additionally, it will send local results to Nx Cloud after the run.

The complex part is the Nx Cloud, especially the DTE. It took us several years to bring it to this state.

There's not much point in trying to rebuild it when the `Nx Cloud` already does what it's supposed to. But you still have an option if you choose to.

**Comment by meeroslav** [comment]
Closing this as answered
