### ISSUE TITLE
@nrwl/react/plugins/storybook unusable with SCSS relative imports

### ISSUE THREAD

**Issue by bogris** [nrwl/nx#15012]
### Current Behavior

Im am working in a NX monorepo with next apps and sepaprate UI libs. 
We use SCSS and css modules imposed by next.js

In order to centralize scss partials, the solution we found was tu update the next config with: 
`  sassOptions: {
    includePaths: [
      path.join(__dirname, 'style'),
      path.join(__dirname, '../../libs/react/styles'),
    ],
  },`
  
in react/styles, hte relevant files are: 
`libs/react/styles/@shared-styles/partials/_breakpoints.scss
libs/react/styles/@shared-styles/partials/_colors.scss
libs/react/styles/@shared-styles/partials/_mixins.scss
libs/react/styles/@shared-styles/partials/_typography.scss`

  this allows us to import relative SCSS partials from react-styles lib as below:  this would be any scss file:
`@use '@shared-styles/partials/_colors' as *;
@use 'partials/_mixins' as *;
@use '@shared-styles/partials/_typography' as *;`

======= PROBLEM =========
The problem is that we don't know how to tell webpack in Storybook about this central SCSS folder that we use. 
The sotrybook works. 

We are sunning NX version: 15.7.0
Storybooks: v7 beta

---------- relevant sotrybook config -----------
`import type { StorybookConfig } from '@storybook/react-webpack5';

const config: StorybookConfig = {
  stories: ['../src/lib/**/*.stories.@(js|jsx|ts|tsx|mdx)'],
  addons: [
    '@storybook/addon-essentials',
    '@nrwl/react/plugins/storybook',
    'storybook-addon-next-router',
    "storybook-css-modules", // 👈 The addon for scss modules
  ],
  framework: {
    name: '@storybook/react-webpack5',
    options: {},
  },
};

export default config;`

### Expected Behavior

the relative SCSS imports we use in scss files should not break the storybook

### Steps to Reproduce

1. create a new NX monorepo
2. initialize a next app
3. create a react lib fot styles, add a subfolder @shared-styles, in this subfolder add a file _partials.scss
4. create a component library
5. add a new component in this library with scss
6. in the component scss file, import the partials from step 3: 
7. `@use '@shared-styles/_partials' as *;
8. add storybook (v7) for this lib with react/typescript/webpack config
9. configure a sotry for the component at step 5
10. sotrybook will fail with an error that will not find the import at line 7

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : darwin arm64
   yarn : 1.22.15
   
   nx                      : 15.7.0
   @nrwl/jest              : 15.7.0
   @nrwl/linter            : 15.7.0
   @nrwl/workspace         : 15.7.0
   @nrwl/cli               : 15.7.0
   @nrwl/cypress           : 15.7.0
   @nrwl/detox             : 15.7.0
   @nrwl/devkit            : 15.7.0
   @nrwl/eslint-plugin-nx  : 15.7.0
   @nrwl/expo              : 15.7.0
   @nrwl/js                : 15.7.0
   @nrwl/next              : 15.7.0
   @nrwl/node              : 15.7.0
   @nrwl/react             : 15.7.0
   @nrwl/rollup            : 15.7.0
   @nrwl/storybook         : 15.7.0
   @nrwl/tao               : 15.7.0
   @nrwl/web               : 15.7.0
   @nrwl/webpack           : 15.7.0
   @nrwl/nx-cloud          : 15.0.3
   typescript              : 4.8.4
```

### Failure Logs

```shell
ERROR in ./node_modules/@nrwl/webpack/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[11].oneOf[1].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[11].oneOf[1].use[2]!./node_modules/@nrwl/webpack/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[11].oneOf[1].use[3]!./libs/web/bits/src/lib/sotry-test/sotry-test.module.scss undefined
Module build failed (from ./node_modules/@nrwl/webpack/node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
2 │ @use '@shared-styles/partials/_colors' as *;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  libs/web/bits/src/lib/sotry-test/sotry-test.module.scss 2:1  root stylesheet
```

**Comment by mandarini** [comment]
Hi there @bogris ! Thank you for filing an issue, and for the detailed description! Can you please put together the reproduction repository you are mentioning, and link it here? It will be very helpful for me!

**Comment by mandarini** [comment]
Also, do you want to check out [this issue](https://github.com/storybookjs/storybook/issues/17768), maybe it is related? If not, did you try adding the paths in `preview.js`?

**Comment by mandarini** [comment]
Check out [these docs](https://storybook.js.org/docs/react/configure/styling-and-css), too.

**Comment by Integrayshaun** [comment]
Hi @bogris!!

I'm a Developer Experience Engineer for Storybook. I wanted to poke my head in here to see if I could help out.

As of Storybook 7 we have official support for NextJS which should handle the configuration of scss and css modules for you.

First of all, install the [`@storybook/nextjs`](https://github.com/storybookjs/storybook/tree/next/code/frameworks/nextjs#documentation) package with your package manager of choice

```shell
yarn add -D @storybook/nextjs@next
```

Then update your `.storybook/main.ts` file

```diff
-import type { StorybookConfig } from '@storybook/react-webpack5';
+import type { StorybookConfig } from '@storybook/nextjs';

const config: StorybookConfig = {
  stories: ['../src/lib/**/*.stories.@(js|jsx|ts|tsx|mdx)'],
  addons: [
    '@storybook/addon-essentials',
    '@nrwl/react/plugins/storybook',
-   'storybook-addon-next-router',
-   "storybook-css-modules", // 👈 The addon for scss modules
  ],
  framework: {
-   name: '@storybook/react-webpack5',
+   name: '@storybook/nextjs,
    options: {},
  },
};

export default config;
```

**Comment by bogris** [comment]
> Also, do you want to check out [this issue](https://github.com/storybookjs/storybook/issues/17768), maybe it is related? If not, did you try adding the paths in `preview.js`? Or add `import '!style-loader!css-loader!sass-loader!./style-loader.scss';` in `preview.js`?

for me this did not work. The issue is not loading the scss loader, but resolving the files to another folder in the repo. 

I think the bottom line is that SCSS files grouped in a library and sahred troughout your NX monorepo is not a supported feature in NX yet :( what we use are workarounds and apparently I was not able to replicate the workaround from the NX config to storybook config in NX monorepo.

**Comment by bogris** [comment]
@Integrayshaun Thanks for this info. 

I managed to get sorybook up and running trough your solution.
Steps to make it work were: 
1. int the ui lib folder, we initialized storybook. 
2. we updated the config with your lines. 
3. we just added the path to one of the nextJS config files in the monorepos, as they all included manual reff to the scss shared folder. 

`  "framework": {
    "name": "@storybook/nextjs",
    "options": {
            nextConfigPath: path.resolve(__dirname, '../../../../apps/nftview/next.config.js')
    }
  },`
4. we run storybbok from the ui lib as a standalone install. 

For now it works and it unblocked our flow. Thank you!

As for next steps, NX team soulb ne able to replicate this behaviour if we add sotrybook in a NextJS UI library folder and allwo us to run it trough NX. 

sidenote: if we try to run this trough NX, we get the following error:

'> nx run bits:storybook

info => Starting manager..
WARN You (or an addon) are using the 'config' preset field. This has been replaced by 'previewAnnotations' and will be removed in 8.0
info Addon-docs: using MDX2
=> Loading Nx React Storybook Addon from "@nrwl/react/plugins/storybook"
info => Using default Webpack5 setup
WARN Force closed manager build

 >  NX   Cannot read properties of undefined (reading 'indexOf')


/Users/sorin/code/foodfix/foodFixMega/node_modules/html-webpack-plugin/index.js:1027
    if (template.indexOf('!') === -1) {
                 ^

TypeError: Cannot read properties of undefined (reading 'indexOf')
    at null.getFullTemplatePath (/Users/sorin/code/foodfix/foodFixMega/node_modules/html-webpack-plugin/index.js:1027:18)
    at null.hookIntoCompiler (/Users/sorin/code/foodfix/foodFixMega/node_modules/html-webpack-plugin/index.js:174:22)
    at null.<anonymous> (/Users/sorin/code/foodfix/foodFixMega/node_modules/html-webpack-plugin/index.js:104:9)
    at Array.forEach (<anonymous>)
    at null.<anonymous> (/Users/sorin/code/foodfix/foodFixMega/node_modules/html-webpack-plugin/index.js:103:20)
    at Hook.eval [as call] (eval at create (/Users/sorin/code/foodfix/foodFixMega/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:7:1)
    at Hook.CALL_DELEGATE (/Users/sorin/code/foodfix/foodFixMega/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at null.createCompiler (/Users/sorin/code/foodfix/foodFixMega/node_modules/webpack/lib/webpack.js:81:28)
    at null.create (/Users/sorin/code/foodfix/foodFixMega/node_modules/webpack/lib/webpack.js:134:16)
    at null.webpack (/Users/sorin/code/foodfix/foodFixMega/node_modules/webpack/lib/webpack.js:158:32)

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target storybook for project bits failed

   Failed tasks:
   
   - bits:storybook
   
   Hint: run the command with --verbose for more details.


 >  NX   RunEnd. Completed tasks'

**Comment by mandarini** [comment]
@Integrayshaun thank you SO much for jumping in!

@bogris I am so happy you got it working and you are now unblocked!
If the only error you are getting from Nx is the "cannot read properties of ", then please check out [this issue](https://github.com/storybookjs/storybook/issues/20652). Probably you have an outdated Storybook 7 dependency. I suggest you delete your `node_modules` and install again. Which version of Storybook 7 are you using? Can I see the versions of your `@storybook/*` packages in your `package.json`?

Also, I am not sure I understand what feature you are saying is not supported by Nx? Can you please send me a reproduction repository, so that I understand? Also, if I understand correctly, it is working for you now? So, you are on a Nx workspace and it is working?

**Comment by bogris** [comment]
I did not have time to redo the node modules, but the feature of NX I was assumig mising is:

- create a central SCSS  library that we can import with @use in the UI component libs and in the app. 
Q: is there a way to create this scss lib with NX and propagate the required info automatically? (like you do for TS config i guess). 

>> in order to emulate this, we are using manually aded sass path under sassOptions in next config. I can;t probide a repo reproduction, but check out my first post. I detailed all the relavant files and relevant content in them .

**Comment by mandarini** [comment]
Ok @bogris ! If you find time to do the `node_modules` and verify that the issue persists, let me know, and I will reopen this issue! :D 

I will also check for that feature that we may be missing. Thank youu!! :D
