### ISSUE TITLE
@nrwl/workspace upgrade from 15.6.3 to 15.7.0 breaks Angular build - Unable to read angular.json

### ISSUE THREAD

**Issue by geometryzen** [nrwl/nx#15013]
### Current Behavior

Exception raised causing the build to fail.

### Expected Behavior

Normal Angular build

### Steps to Reproduce

Unable to provide an example repo or further steps at this time.
I tried using the nx_examples repo with latest dependencies and was unable to reproduce the issue.

### Nx Report

```shell
Node : 17.5.0
   OS   : linux x64
   npm  : 8.4.1
   
   nx                      : 15.7.0
   @nrwl/jest              : 15.7.0
   @nrwl/linter            : 15.7.0
   @nrwl/workspace         : 15.7.0
   @nrwl/angular           : 15.7.0
   @nrwl/cli               : 15.7.0
   @nrwl/cypress           : 15.7.0
   @nrwl/devkit            : 15.7.0
   @nrwl/eslint-plugin-nx  : 15.7.0
   @nrwl/js                : 15.7.0
   @nrwl/rollup            : 15.7.0
   @nrwl/tao               : 15.7.0
   @nrwl/web               : 15.7.0
   @nrwl/webpack           : 15.7.0
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngrx/store-devtools : 15.3.0
```

### Failure Logs

```shell
Unable to read angular.json
RangeError: Maximum call stack size exceeded
    at arrayBufferToString (/home/david/Development/stemcmono/node_modules/nx/src/adapter/ngcli-adapter.js:256:32)
    at /home/david/Development/stemcmono/node_modules/nx/src/adapter/ngcli-adapter.js:241:73
    at /home/david/Development/stemcmono/node_modules/rxjs/dist/cjs/internal/operators/map.js:10:37
    at OperatorSubscriber._this._next (/home/david/Development/stemcmono/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at OperatorSubscriber.Subscriber.next (/home/david/Development/stemcmono/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
    at SafeSubscriber.__tryOrUnsub (/home/david/Development/stemcmono/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/home/david/Development/stemcmono/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/home/david/Development/stemcmono/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/home/david/Development/stemcmono/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/home/david/Development/stemcmono/node_modules/@angular-devkit/core/node/host.js:130:17)
```

### Additional Information

Issue appears to be caused by @nrwl/workspace package as other packages can be upgraded with out problems.

**Comment by ChristopherBuller** [comment]
I have the exact same outcome after upgrade to 15.7, unable to read angular.json, prior solution state had a workspace.json, I ran the command that the console instructions printed. All the project.json files work for the libs, but the web project no longer builds. Same error as original reported

**Comment by leosvelperez** [comment]
Thanks for reporting this!

I couldn't reproduce the issue migrating a fresh 15.6.3 Nx workspace to 15.7.0. Please provide a repo where it can be reproduced or detailed reproduction steps so we can troubleshoot the issue.

**Comment by geometryzen** [comment]
I'm doing some debugging. It may be related to this...

https://github.com/manuels/texlive.js/issues/18

**Comment by geometryzen** [comment]
I can't say why the 15.7.3 upgrade is taking the new code path of

NxScopedHost.read (with path="angular.json")
NxScopedHost.readMergedProjectConfiguration
NxScopedHost.readExistingAngularJson
arrayBufferToString

However, the problem does seem to be caused by String,fromCharCode.

I tried the following to work around the limitations of String.fromCharCode and it worked.

function arrayBufferToString(buffer) {
    const ns = new Uint8Array(buffer);
    let str = "";
    const chunk = 8 * 1024;
    let i = 0;
    for (i = 0; i < ns.length / chunk; i++) {
        str += String.fromCharCode.apply(null, ns.subarray(i * chunk, (i + 1) * chunk));
    }
    str += String.fromCharCode.apply(null, ns.subarray(i * chunk));
    return str;
    // return String.fromCharCode.apply(null, ns);
}

Note that this is essentially the fix that was applied for the issue in the previous comment.

As extra context, my angular.json file refers to around 150 libs and 3 angular apps. This gives rise to a Unit8Array length of 158407.

I'm afraid I'm going to have to leave the PR to someone who is more versed in nx as I don't feel qualified to complete the full resolution. I hope that helps.

**Comment by JelleBruisten** [comment]
Not sure if related but our workspace used to use angular.json to figure out what projects there were in a workspace in a few custom scripts. These break now angular.json has been removed and adding it back is causing nx to error.

similarly we use transloco for translations, their extraction of keys from applications also breaks with nx 15.7.0
```  
npx transloco-keys-manager extract 
Unable to load workspace config from angular.json, .angular.json, workspace.json. Defaulting source root to 'src'
Input path provided doesn't exists!
 ```

**Comment by chromey** [comment]
Very similar issue here, but with a different call stack:
```
Unable to read angular.json
TypeError: Cannot read properties of undefined (reading 'data')
    at /Users/chris/dev/src/dc-app-xsp/dc-angular-apps/node_modules/nx/src/adapter/ngcli-adapter.js:154:108
    at Array.forEach (<anonymous>)
    at /Users/chris/dev/src/dc-app-xsp/dc-angular-apps/node_modules/nx/src/adapter/ngcli-adapter.js:152:22
    at /Users/chris/dev/src/dc-app-xsp/dc-angular-apps/node_modules/rxjs/dist/cjs/internal/operators/map.js:10:37
    at OperatorSubscriber._this._next (/Users/chris/dev/src/dc-app-xsp/dc-angular-apps/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at Subscriber.next (/Users/chris/dev/src/dc-app-xsp/dc-angular-apps/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
    at /Users/chris/dev/src/dc-app-xsp/dc-angular-apps/node_modules/rxjs/dist/cjs/internal/observable/zip.js:50:36
    at OperatorSubscriber._this._next (/Users/chris/dev/src/dc-app-xsp/dc-angular-apps/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at Subscriber.next (/Users/chris/dev/src/dc-app-xsp/dc-angular-apps/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
    at /Users/chris/dev/src/dc-app-xsp/dc-angular-apps/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:28:28
```

**Comment by geometryzen** [comment]
@chromey My hunch is that the aspect that is common here is that code related to angular.json is being executed that was not being executed before. If that hunch is correct then your issue may point to another bug lurking in neighboring code. My approach was to manually change and log the code in node_modules/nx/src/adapter/ngcli-adapter.js to discover what was going on. I was uniquely placed to do this because I alone had a repo in which the bug was reproducable. I'm now convinced that I understand the problem and have the right fix. Now the challenge is the mechanics of providing a PR in an unfamiliar codebase! The cause of your issue seems to be different. It might be useful to investigate the problem a bit more in your environment to see if there is another fix to be applied?

**Comment by leosvelperez** [comment]
hey @geometryzen! Thanks for the details provided!

I'd say you're on the right track. Have you confirmed that replacing the problematic code in your `node_modules` works? I'll spend time on this tomorrow and try to reproduce it with a large `angular.json` or many `project.json` files.

**Comment by mikedeklerkneocles** [comment]
Not a fix, but a workaround. Goto ngcli-adapter.js, find method `arrayBufferToString` and make it call the following code instead:

    function _arrayBufferToString(buffer) {
        var string = '';
        var bytes = new Uint8Array(buffer);
        var len = bytes.byteLength;
        for (var i = 0; i < len; i++) {
            string += String.fromCharCode( bytes[ i ] );
        }
        return string;
    }

    function arrayBufferToString(buffer) {
        // debugger;
        //const string = String.fromCharCode.apply(null, new Uint8Array(buffer));
        const string = _arrayBufferToString(buffer);
        return string;
    }

![image](https://user-images.githubusercontent.com/118175125/219466424-5bf0c052-98b8-4f9f-8f96-920dfdd35358.png)

**Comment by nthonymiller** [comment]
> Very similar issue here, but with a different call stack:

I got the same error after upgrading to 15.7.1, I don't have a `angular.json` file at all for my angular project.

**Comment by stemcstudio** [comment]
@leosvelperez I did indeed test the fix over my own repo and that is the code that I provided. I was looking today at how to creatre a PR but I couldn't see how to run unit tests. I actually raised a documentation issue for CONTRIBUTING.md. It seems to me that the best fix would look like an isolated arrayBufferToString(0 function with its own unit tests. The alternative of creating a huge angular.json file and associated repo as a unit test doesn't make so much sense to me. I'm a bit surprised that there isn't a standalone library for just this "shortcoming" of String.fromCharCode. @mikedeklerkneocles has an interesting solution too that looks quite elegant.

**Comment by nthonymiller** [comment]
> > Very similar issue here, but with a different call stack:
> 
> I got the same error after upgrading to 15.7.1, I don't have a `angular.json` file at all for my angular project.

After some more detailed investigation I discovered not all my `project.json` contained `name` property for the library. Not sure why some of my libraries had these and others did not.

**project.json**
```json 
{
  "name": "ui-shared-components", // <- This was missing and need to add it to project
  "$schema": "../../../../node_modules/nx/schemas/project-schema.json",
  "projectType": "library",
  "sourceRoot": "libs/ui/shared/dialog/src",
  "prefix": "cts",
...
}

```

After fixing all my `project.json` files, the error went away.

Another interesting collision that occurred with the name is that it needs to be not only be unique (which I already knew), but the you cannot use have suffix names

* ui-shared-components
* ui-shared-components-input

Having the library called `ui-shared-components` will cause the `ui-shared-components-input` to fail. This caused an issue with the e2e project namings as well `my-app` and `my-app-e2e` caused a conflict.

**Comment by stemcstudio** [comment]
@nthonymiller That seems like a different issue to me. Are you suggesting that there is a connection with the arrayBufferToString problem?

**Comment by stemcstudio** [comment]
@leosvelperez I tried the @mikedeklerkneocles solution and that worked also. Here is the JavaScript that I monkey-patched in node_modules:

function arrayBufferToString(buffer) {
    let s = '';
    const bytes = new Uint8Array(buffer);
    const len = bytes.byteLength;
    for (let i = 0; i < len; i++) {
        s += String.fromCharCode( bytes[ i ] );
    }
    return s;
    // return String.fromCharCode.apply(null, new Uint8Array(buffer));
}

**Comment by nthonymiller** [comment]
My fix is related to @chromey, but still very much related to `Unable to read angular.json` error.

**Comment by hoeferbe** [comment]
The workaround doesn't work for me.
I can serve nestjs applications but no angular applications.
I'm wondering why is an angular.json being read at all, if it was deleted from the migration?

**Comment by chromey** [comment]
Thanks a lot @nthonymiller, this worked for me as well! Out of the 43 projects in my workspace, exactly one was missing the `name` property, don't know why. Perhaps the migration script could double-check that.

**Comment by hoeferbe** [comment]
I also searched the libraries for missing "name" properties and fixed two. After that it works.
I think the error message is a bit confusing here.

**Comment by nthonymiller** [comment]
I agree, the error message is misleading. I'm glad this has helped you.

**Comment by jeffschulzusc** [comment]
@nthonymiller 

for me too: 

after:
`nx g @nrwl/workspace:convert-to-nx-project --all`

none of my project.json files have a "name" property

and at `nx build ...` i get 

`
Unable to read angular.json
TypeError: Cannot read properties of undefined (reading 'data')
    at /Users/jeffschulzuscmacmini/TEMP/vhap.ws.nx-migrate-test/node_modules/nx/src/adapter/ngcli-adapter.js:154:108
    at Array.forEach (<anonymous>)
    at /Users/jeffschulzuscmacmini/TEMP/vhap.ws.nx-migrate-test/node_modules/nx/src/adapter/ngcli-adapter.js:152:22
    at /Users/jeffschulzuscmacmini/TEMP/vhap.ws.nx-migrate-test/node_modules/rxjs/dist/cjs/internal/operators/map.js:10:37
    at OperatorSubscriber._this._next (/Users/jeffschulzuscmacmini/TEMP/vhap.ws.nx-migrate-test/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:28:21)
    at OperatorSubscriber.Subscriber.next (/Users/jeffschulzuscmacmini/TEMP/vhap.ws.nx-migrate-test/node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
    at /Users/jeffschulzuscmacmini/TEMP/vhap.ws.nx-migrate-test/node_modules/rxjs/dist/cjs/internal/observable/zip.js:50:36
    at OperatorSubscriber._this._next (/Users/jeffschulzuscmacmini/TEMP/vhap.ws.nx-migrate-test/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:28:21)
    at OperatorSubscriber.Subscriber.next (/Users/jeffschulzuscmacmini/TEMP/vhap.ws.nx-migrate-test/node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
    at SafeSubscriber.__tryOrUnsub (/Users/jeffschulzuscmacmini/TEMP/vhap.ws.nx-migrate-test/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:205:16)
`

i have 35 projects in my workspace
