### ISSUE TITLE
Workspace creation failed, EACCES: permission denied, mkdir '/home/mint/.cache/Cypress'

### ISSUE THREAD

**Issue by AnatoleLucet** [nrwl/nx#1502]
Hello,

I am having some trouble while creating a workspace with `yarn create nx-workspace <app_name>`.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

I am just trying to create a new workspace.

## Current Behavior

When I do a `yarn create nx-workspace my-app`; I am having this error :

```
> cypress@3.3.1 postinstall /home/mint/dev/Learn/Nx/my-app/node_modules/cypress
> node index.js --exec install

Cypress cannot write to the cache directory due to file permissions

See discussion and possible solutions at
https://github.com/cypress-io/cypress/issues/1281

----------

Failed to access /home/mint/.cache/Cypress:

EACCES: permission denied, mkdir '/home/mint/.cache/Cypress'

----------

Platform: linux (Linux Mint - )
Cypress Version: 3.3.1
npm WARN @ngtools/webpack@8.0.1 requires a peer of @angular/compiler-cli@>=8.0.0-beta.0 < 9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@3.3.1 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress@3.3.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mint/.npm/_logs/2019-06-18T21_51_47_231Z-debug.log
Package install failed, see above.
Workspace creation failed, see above.
```

### Steps to Reproduce

Actually i don't really know how you can reproduce this without messing up your `.cache/`'s permission.

### Context

- version of Nx used : I am ussing it with `yarn create` (same error with `npx`).
- version of Angular CLI used : 8.0.0
- `angular.json` configuration : There's no workspace.
- version of Angular DevKit used : 
```
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
```
- 3rd-party libraries and their versions : There's no workspace.
- and most importantly - a use-case that fails : I don't really know what to answer but i think it is this `yarn create nx-workspace <app_name>` (?)

## Other

Here is the `.cache/`'s permission on my local machine : `drwx------  6 root root   4096 juin  18 23:37 .cache`

I don't think this issue is related to Cypress because i can install it globally with `sudo yarn global add cypress`.

This dosen't sovled it : [#3081](https://github.com/cypress-io/cypress/issues/3081)

Thank you for any responses.

**Comment by AnatoleLucet** [comment]
**Edit :** This issue is not really coming from `yarn create nx-workspace`, it came from `yarn ng add @nrwl/react`. So i can create a workspace but i can't add `@nrwl/react` to it.

**Comment by vsavkin** [comment]
@AnatoleLucet the issue is with installing cypress. Are you able to do:

```
npm init -y
npm install cypress
```

**Comment by AnatoleLucet** [comment]
@vsavkin it seems like I am having the same issue. I will go open an issue on the Cypress's repo.
