### ISSUE TITLE
Cannot find module 'my-plugin/package.json'

### ISSUE THREAD

**Issue by mikemfleming** [nrwl/nx#15024]
### Current Behavior

I'm following the documentation from the official NX page on [Local Generators](https://nx.dev/recipes/generators/local-generators).

I'm starting from a completely fresh workspace. The following commands succeed:
```
npx create-nx-workspace --preset=ts

npm install @nrwl/nx-plugin@latest 
# ^ as per the documentation above, I match "latest" with the nx version in my workspace package.json file

npx nx g @nrwl/nx-plugin:plugin my-plugin
npx nx g @nrwl/nx-plugin:generator my-generator --project=my-plugin
```

This last command fails.
```
> npx nx generate my-plugin:my-generator mylib

 >  NX   Unable to resolve my-plugin:my-generator.

   Cannot find module 'my-plugin/package.json'
   Require stack:
   - .../node_modules/nx/src/utils/package-json.js
   - .../node_modules/nx/src/utils/package-manager.js
   - .../node_modules/nx/bin/init-local.js
   - .../node_modules/nx/bin/nx.js
   Pass --verbose to see the stacktrace.
```

### Expected Behavior

I would expect that I'm able to generate a new library called `mylib`.

### Steps to Reproduce

1. npx create-nx-workspace --preset=ts
2. npm install @nrwl/nx-plugin@latest, as per the documentation above, I match "latest" with the nx version in my workspace package.json file
3. npx nx g @nrwl/nx-plugin:plugin my-plugin
4. npx nx g @nrwl/nx-plugin:generator my-generator --project=my-plugin
5. npx nx generate my-plugin:my-generator mylib

### Nx Report

```shell
> npx nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.18.1
   OS   : darwin x64
   npm  : 8.19.2

   nx                      : 15.7.0
   @nrwl/jest              : 15.7.0
   @nrwl/linter            : 15.7.0
   @nrwl/workspace         : 15.7.0
   @nrwl/cli               : 15.7.0
   @nrwl/devkit            : 15.7.0
   @nrwl/eslint-plugin-nx  : 15.7.0
   @nrwl/js                : 15.7.0
   @nrwl/nx-plugin         : 15.7.0
   @nrwl/tao               : 15.7.0
   @nrwl/nx-cloud          : 15.0.3
   typescript              : 4.8.4
   ---------------------------------------
   Local workspace plugins:
         $MY_WORKSPACE/my-plugin
```

**Comment by AgentEnder** [comment]
@mikemfleming Under the local workspace plugin section in your report it shows the full name of the plugin, thats how you should be invoking it. 

In this case for example, you should run `npx nx generate @MY_WORKSPACE/my-plugin:my-generator mylib`

The docs don't include an npm scope since its not always a requirement. You can change the import path by updating the package.json for the plugin, as well as the tsconfig.base.json entry that points to it.

**Comment by mikemfleming** [comment]
That got it! Thank you!

**Comment by mikemfleming** [comment]
Also wow thanks for the quick response 😄
