### ISSUE TITLE
Dependecies from @storybook/addon-essentials get included in build for a library

### ISSUE THREAD

**Issue by yzhou-willow** [nrwl/nx#15039]
### Current Behavior

We're using Nx to manage our component library and will publish the components as a npm package. And there are a few configuration for storybook in those files:
`workspaceFolder/libs/ui/.storybook/main.ts` and `workspaceFolder/libs/ui/.storybook/preview.tsx`.

In these 2 files, we have several imports from `@storybook/core-common`, `@storybook/addons`, `@storybook/theming`, ect. 

And those packages were installed via `@storybook/addon-essentials` in workspace package.json:
```
// workspace package.json
{
  "devDependencies": {
    "@storybook/addon-essentials": "~6.5.9",
    // ...
  }
}
```

After running `nx build ui`, we will get this package.json for the ui library:
```
// dist/libs/ui/package.json
{
  "peerDependencies": {
    "@storybook/core-common": "6.5.12",
    "@storybook/addons": "6.5.12",
    "@storybook/addon-docs": "6.5.12",
    "@storybook/theming": "6.5.12",
    "@storybook/addon-actions": "6.5.12",
    // ...
  }
}
```

Which includes those storybook addon packages even though we have **excluded all** the storybook related files in our build.

After a few investigation, I found a solution to exclude them from the build package. Which is to install those addons in workspace devDenpendecies, like this:
```
// workspace package.json
{
  "devDependencies": {
    "@storybook/addon-docs": "^6.5.16",
    "@storybook/addon-essentials": "~6.5.9",
    "@storybook/addons": "^6.5.16",
   // ...
  }
}
```

And this will produce the expected dependency list in dist/libs/ui/package.json (see Expected Behavior).

I'm not sure whether my solution for this problem is correct. I'd expect some configuration could solve this problem but didn't find any. Could anyone provide any idea? Much appreciated. 

### Expected Behavior

Expect all the storybook addon packages removed in dist/libs/ui/package.json:
```
// dist/libs/ui/package.json
{
  "peerDependencies": {
    ~"@storybook/core-common": "6.5.12",~
    ~"@storybook/addons": "6.5.12",~
    ~"@storybook/addon-docs": "6.5.12",~
    ~"@storybook/theming": "6.5.12",~
    ~"@storybook/addon-actions": "6.5.12",~
    // ...
  }
}
```

### Steps to Reproduce

1. Make sure install `@storybook/addon-essentials` in the workspace package.json;
2. Import a few functions into a library project's `./storybook/main.ts`;
3. Run `nx build {projectName}`;
4. Check the result in `dist/libs/ui/package.json`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : darwin arm64
   npm  : 8.3.1
   
   nx : 15.0.13
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.13
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.13
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.13
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.13
   @nrwl/js : 15.0.13
   @nrwl/linter : 15.0.13
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 15.0.13
   @nrwl/react : 15.0.13
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.13
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.13
   @nrwl/web : 15.0.13
   @nrwl/webpack : 15.0.13
   @nrwl/workspace : 15.0.13
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
         @xxxx/xxxx-ui-component-generator
   ---------------------------------------
   Community plugins:
```

### Additional Information

I have located the code who adds those dependencies when build, which is the `updateBuildableProjectPackageJsonDependencies` function in `./node_modules/@nrwl/workspace/src/utilities/buildable-libs-utils.js`

And the logic takes effect is:
```
 // If an npm dep is part of the workspace devDependencies, do not include it the library
 if (!!((_a = workspacePackageJson.devDependencies) === null || _a === void 0 ? void 0 : _a[entry.node.data.packageName])) {
     return;
 }
```

**Comment by mandarini** [comment]
HI there @yzhou-willow , thanks for filing an issue. Can you do something for me please? Can you try to update to the latest version of Nx (`nx migrate latest`) and let me know if this issue persists?

**Comment by yzhou-willow** [comment]
> HI there @yzhou-willow , thanks for filing an issue. Can you do something for me please? Can you try to update to the latest version of Nx (`nx migrate latest`) and let me know if this issue persists?

Thank you for the reply. 

I have updated my nx packages as below:
 >  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : darwin arm64
   npm  : 8.3.1
   
   nx                      : 15.7.1
   @nrwl/jest              : 15.7.1
   @nrwl/linter            : 15.7.1
   @nrwl/workspace         : 15.7.1
   @nrwl/cli               : 15.7.1
   @nrwl/cypress           : 15.7.1
   @nrwl/devkit            : 15.7.1
   @nrwl/eslint-plugin-nx  : 15.7.1
   @nrwl/js                : 15.7.1
   @nrwl/nx-plugin         : 15.7.1
   @nrwl/react             : 15.7.1
   @nrwl/rollup            : 15.7.1
   @nrwl/storybook         : 15.7.1
   @nrwl/tao               : 15.7.1
   @nrwl/web               : 15.7.1
   typescript              : 4.8.4
   ---------------------------------------
   Local workspace plugins:


So I ran then `npm install`, and then re-ran `nx build ui --skip-nx-cache --verbose`. And still find those storybook addons appears in `peerDependecies` of `dist/lib/ui/pakcage.json`

**Comment by mandarini** [comment]
Ok thank you. I can take a look next week!

**Comment by herrKlein** [comment]
My issue looks related: https://github.com/nrwl/nx/issues/15039

**Comment by Chanki-Min** [comment]
I think dependency list should respect `tsconfig.lib.json` given by project configuration

**Comment by mandarini** [comment]
Once [this PR](https://github.com/nrwl/nx/pull/13966) is merged, I think your issue will be resolved, and you can have better control on the dependencies!

**Comment by Chanki-Min** [comment]
@mandarini refreshed my start of day! thank you
