### ISSUE TITLE
nx watch crashes when switching branches.

### ISSUE THREAD

**Issue by bryhasagithub** [nrwl/nx#15033]
### Current Behavior

When switching branches with the watcher running in a different window, the watcher connection will close and prompt a manual restart. 

[1]  >  NX   Watch connection closed
[1]
[1]    The daemon has closed the connection to this watch process.
[1]    Please restart your watch command.

### Expected Behavior

When switching branches with the watcher still running, it shouldn't close with a prompt to inform the user to take manual action. It should automatically restart the watcher knowing that there's been a change on the current branch. 

### GitHub Repo

 https://github.com/nrwl/nx-examples

### Steps to Reproduce

1. Run the nx watcher while on "branch A".
2. While the watcher is still running, In a separate window, switch or checkout a different branch, "branch B".
3. The watcher will then fail with the following error.
> [1]  >  NX   Watch connection closed
> [1]    The daemon has closed the connection to this watch process.
> [1]    Please restart your watch command.

### Nx Report

```shell
Node : 16.17.0
   OS   : darwin arm64
   npm  : 8.15.0

   nx : 15.5.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : Not Found
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : Not Found
   @nrwl/vite : Not Found
   typescript : 4.6.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
> [1]  >  NX   Watch connection closed
> [1]    The daemon has closed the connection to this watch process.
> [1]    Please restart your watch command.
```

**Comment by bryhasagithub** [comment]
I suppose this could also be considered a feature request?

**Comment by bryhasagithub** [comment]
I suppose a possible way of going about [this](https://github.com/nrwl/nx/blob/75c34c3d8d30441a6ede905ed84843598a27280b/packages/nx/src/command-line/watch.ts#L173) would be to provide a feature config that people could set in their nx.json for determining whether or not nx should restart the watcher's connection if it gets closed.

**Comment by bryhasagithub** [comment]
Alternative solution for anybody also experiencing this issue:

have your watcher run a script as so:
``` bash

set -eu

# cd to repo root
cd "$(dirname "$0")/../.."

packages=$(./scripts/packages/get-packages.sh)
packagesList=$(jq -r <<<"$packages" '.[] | select(startswith("./packages/")) | .[11:] | "@repoName/" + .')

# Comma delimit the list of packages to watch and build
packagesList=$(tr '\n' ',' <<<"$packagesList")
  
echo "Watching Packages 👀" 

# Since nx doesn't have an exclude param, we list all the things we want that are packages.
while true
do
npx nx watch "--projects=$packagesList" -- nx run \$NX_PROJECT_NAME:build
echo "NX watcher crashed 😱 restarting..."
sleep 5
done

```

**Comment by nclskfm** [comment]
This shouldn't be closed. I'm facing the same issue, and in my opinion, the workaround you provided @bryhasagithub isn't convenient.

**Comment by bryhasagithub** [comment]
Oh I agree, it's definitely not convenient and I would love a feature over a workaround solution any day :)

**Comment by CyanoFresh** [comment]
same here
