### ISSUE TITLE
NrWl/Nx how to configure Libs to have different CSS for different application inside workspace.

### ISSUE THREAD

**Issue by SWGeekPD** [nrwl/nx#1503]
I have generated 2 apps (app1,app2) inside workspace. I also created 1 lib called loginPage.

I want a different css of controls inside libs for my app1 and app2.
If i define css inside libs component than the same will be loaded for app1 and app2.

How can the same lib have the different css for app1 and app2.

Please suggest.

**Comment by Destreyf** [comment]
@SWGeekPD The easiest way i can think of is to use some sort of variable/management system and reference those variables inside the main styles.less/scss file inside of each application.

For example, i am using a theme/library called Nebular, i create a generic theme library, but then i extend it and init it separately in my different apps, this allows customization per app with a solid base theme setup.
