### ISSUE TITLE
Support provide `cwd` in `dependOn`

### ISSUE THREAD

**Issue by splincode** [nrwl/nx#15034]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Current

```json
"build": {
  "dependsOn": [{ "projects": "self", "target": "pre-build", "params": "forward" }]
}
```

New

```
"build": {
  "dependsOn": [{ 
        "projects": "dependencies",
        "target": "build", 
        "params": "forward",
        "cwd": "submodule"
   }]
}
```

## Motivation

In our project, we use git submodules, so in one mono-repository, we use many repositories

```
├── nx.json
├── package-lock.json
├── package.json
├── projects
│   ├── proprietary-cdk
│   ├── proprietary-core
│   └── proprietary-demo
├── public
│   ├── nx.json
│   ├── package-lock.json
│   ├── package.json
│   ├── projects
│   │   ├── addon-charts
│   │   ├── addon-commerce
│   │   ├── addon-doc
│   │   ├── addon-editor
│   │   ├── addon-mobile
│   │   ├── addon-preview
│   │   ├── addon-table
│   │   ├── addon-tablebars
│   │   ├── cdk
│   │   ├── core
│   │   ├── demo
│   │   ├── demo-integrations
│   │   ├── eslint-plugin
│   │   ├── i18n
│   │   ├── icons
│   │   ├── kit
│   │   ├── styles
│   │   ├── taiga-schematics
│   │   └── testing
```

https://github.com/tinkoff/taiga-ui

We have several nx.json, and a lot of project.json files. However, due to the fact that public projects do not know that they can be run in a different environment, we have problems. For example public/projects/core/project.json

```json
{
    "name": "core",
    "$schema": "../../node_modules/nx/schemas/project-schema.json",
    "root": "projects/core",
    "sourceRoot": "projects/core",
    "projectType": "library",
    "prefix": "tui",
    "targets": {
        "build": {
            "executor": "@angular-devkit/build-angular:ng-packagr",
            "outputs": ["dist/core"],
            "options": {
                "tsConfig": "tsconfig.build.json",
                "project": "projects/core/ng-package.json"
            },
            "dependsOn": [
                {
                    "target": "build",
                    "projects": "dependencies",
                    "params": "forward"
                }
            ]
        }
    }
}
```

But when our project (https://github.com/tinkoff/taiga-ui) is used as a submodule, and we try run `nx buiild core`, we have error:

```
no such file or directory
~/taiga-ui/projects/cdk/ng-package.json
```

Alternative fix

```
cd ~/taiga-ui/public/
nx buiild core
```

But if we run `nx build proprietary-core` it is trying to build dependOn `core` and failed, due to the fact that it cannot be built from the correct directory.

## Suggested Implementation

we need help to pass from which directory the nx command will be built

```
  "dependsOn": [{ 
        "projects": "dependencies",
        "target": "build", 
        "params": "forward",
        "cwd": "submodule" // <--- 
   }]
```

**Comment by marwan38** [comment]
Can I suggest an alternative to this because I'm facing the same thing.

`.gitmodules` stores all the data about the submodules the repo has. So, we can use that data to match dependencies listed in package.json and automatically pick them up. If I have't missed anything then it should work like nothing changed. Might want to include a flag in there to disable submodule resolution though.

Btw @splincode how are you linking your dependencies in `package.json`? Are you using `*`, `workspace:*` or a direct link `file:../projects/foo`?
