### ISSUE TITLE
Default Collection is Angular, ng commands not working as expected

### ISSUE THREAD

**Issue by tcoz** [nrwl/nx#1504]
Installed /cli@latest, created an Angular CLI project:

ng new myNewProject

Added NX extensions:

ng add @nrwl/schematics

(note that if you aren't using the latest CLI, this doesn't work, but ok on that). 

Checked package.json, angular is default collection:

  "cli": {
    "defaultCollection": "@nrwl/angular"
  }

Ran ng g app myApp --directory=components

Reported error, "directory" is unknown option (no other error info, just a single red line). 

Looked up docs, saw that some package rearrangement incurs modifying commands, ran this:

ng g @nrwl/angular:app myApp --directory=components

This succeeded. 

According to the 7-8 update docs, this should not be necessary:

"If @nrwl/angular is the default collection in the workspace, you can continue using ng g app."

Short version:

- Current: Angular is default collection but commands don't run with ng g [command] [option]. 
- Expected: If Angular is default collection, should not have to prepend command with @nrwl/angular:

**Comment by vsavkin** [comment]
Unfortunately I cannot reproduce it. In my case, the default collection isn't set. Could you provide a repro?

**Comment by tcoz** [comment]
Unfortunately no, when I attempt to repro now the @nrwl install terminates with Cannot find 'architect' of undefined error.

Console:

```
TCOZ:GitHub tcoz$ ng new TestDefault
? Would you like to add Angular routing? No
? Which stylesheet format would you like to use? SCSS   [ http://sass-lang.com/documentation/file.SASS_REFERENCE.html#syntax ]
CREATE TestDefault/README.md (1028 bytes)
CREATE TestDefault/.editorconfig (246 bytes)
CREATE TestDefault/.gitignore (629 bytes)
CREATE TestDefault/angular.json (3553 bytes)
CREATE TestDefault/package.json (1285 bytes)
CREATE TestDefault/tsconfig.json (470 bytes)
CREATE TestDefault/tslint.json (1985 bytes)
CREATE TestDefault/browserslist (429 bytes)
CREATE TestDefault/karma.conf.js (1023 bytes)
CREATE TestDefault/tsconfig.app.json (210 bytes)
CREATE TestDefault/tsconfig.spec.json (270 bytes)
CREATE TestDefault/src/favicon.ico (5430 bytes)
CREATE TestDefault/src/index.html (298 bytes)
CREATE TestDefault/src/main.ts (372 bytes)
CREATE TestDefault/src/polyfills.ts (2838 bytes)
CREATE TestDefault/src/styles.scss (80 bytes)
CREATE TestDefault/src/test.ts (642 bytes)
CREATE TestDefault/src/assets/.gitkeep (0 bytes)
CREATE TestDefault/src/environments/environment.prod.ts (51 bytes)
CREATE TestDefault/src/environments/environment.ts (662 bytes)
CREATE TestDefault/src/app/app.module.ts (314 bytes)
CREATE TestDefault/src/app/app.component.scss (0 bytes)
CREATE TestDefault/src/app/app.component.html (1120 bytes)
CREATE TestDefault/src/app/app.component.spec.ts (993 bytes)
CREATE TestDefault/src/app/app.component.ts (216 bytes)
CREATE TestDefault/e2e/protractor.conf.js (810 bytes)
CREATE TestDefault/e2e/tsconfig.json (214 bytes)
CREATE TestDefault/e2e/src/app.e2e-spec.ts (640 bytes)
CREATE TestDefault/e2e/src/app.po.ts (251 bytes)

> fsevents@1.2.9 install /Users/tcoz/Documents/GitHub/TestDefault/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/tcoz/Documents/GitHub/TestDefault/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> core-js@2.6.9 postinstall /Users/tcoz/Documents/GitHub/TestDefault/node_modules/babel-runtime/node_modules/core-js
> node scripts/postinstall || echo "ignore"


> core-js@2.6.9 postinstall /Users/tcoz/Documents/GitHub/TestDefault/node_modules/karma/node_modules/core-js
> node scripts/postinstall || echo "ignore"


> @angular/cli@8.0.3 postinstall /Users/tcoz/Documents/GitHub/TestDefault/node_modules/@angular/cli
> node ./bin/postinstall/script.js

added 1083 packages from 1058 contributors and audited 19005 packages in 33.747s
found 0 vulnerabilities

    Successfully initialized git.
TCOZ:GitHub tcoz$ cd TestDefault/
TCOZ:TestDefault tcoz$ ng add @nrwl/workspace
Installing packages for tooling via npm.
+ @nrwl/workspace@8.1.2
added 59 packages from 41 contributors and audited 19197 packages in 7.654s
found 0 vulnerabilities

Installed packages for tooling via npm.
Cannot read property 'architect' of undefined
TCOZ:TestDefault tcoz$ 




```

**Comment by tcoz** [comment]
Here's what I'm seeing:

- Install Angular CLI (using fresh install of 8.0.3)
- ng new test-default
- ng add @nrwl/workspace
- ng g app my-mod --directory=widgets

Unknown option: '--directory'

It's already an angular project, so one may expect ng to work normally even after installing the workspace package, but I looked in the angular.json and the default collection wasn't set:

`  "defaultProject": "test-default" (last line of angular.json)`

I figured an explicit install of your angular package may fix:

- ng add @nrwl/angular

That seemed to go fine, and now I see the schematics and default collection is set in the angular.json.

```
"defaultProject": "test-default",
  "schematics": {
    "@nrwl/angular:application": {
      "unitTestRunner": "jest",
      "e2eTestRunner": "cypress"
    },
    "@nrwl/angular:library": {
      "unitTestRunner": "jest"
    }
  },
  "cli": {
    "defaultCollection": "@nrwl/angular"
  } 
```

Having done that step, it now seems to work as expected. 

Thanks for looking at it :)

**Comment by vsavkin** [comment]
Thank you for troubleshooting it.

To summarize:
It looks like the issue is that the `ng-add` schematic doesn't set the default collection.

**Comment by brandonroberts** [comment]
@tcoz can you verify this is still an issue with the latest release?

**Comment by vsavkin** [comment]
I'm sorry, but I'm going to close this. If the problem persists, please reopen the issue and we will take a look
