### ISSUE TITLE
Task dependency on task in other package

### ISSUE THREAD

**Issue by jwefers** [nrwl/nx#15044]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Allow adding a task dependency to a specific task in another package, so that for a given packages target, another packages target is executed, but without that other package being a code-level dependency

## Motivation
I have several packages, that represent serverless functions at some cloud provider. Some of these functions will HTTP REST-call each other during runtime. This is therefore a dependency, but not on a nodejs dependency level, but at the deployment level.

Unfortunately, nx does not seem to give me the opportunity to declare this fact. When i add the dependent package to `implicitDependencies`, it will wrongly include this package in the generated `package.json`. And i cannot make the deploy task for a package depend on specifically the deploy task in another package

## Suggested Implementation

project.json
```json
{
  ...
  "targets": {
    "deploy": {
      "dependsOn": [ "neighbourPackage:deploy" ]
    }
  }
}
```

## Alternate Implementations
implicitDependencies, but excluding it from the generated package.json in some form

## Workaround

project.json
```json
{
  ...
  "targets": {
    "otherPackageDeploy": {
      "command": "nx run neighbourPackage:deploy"
    },
    "deploy": {
      "dependsOn": [ "otherPackageDeploy" ]
    }
  }
}
```

**Comment by AgentEnder** [comment]
This is supported now 🎉
