### ISSUE TITLE
Nx build: Derived tsconfig is not working when project has 0 dependencies.

### ISSUE THREAD

**Issue by janwiebedroid** [nrwl/nx#15043]
### Current Behavior

When building a lib with 0 dependencies, which uses a derived tsconfig.base the nx build commands gives an error:
`Cannot read properties of undefined (reading 'paths')`.

This is because the derived tsconfig is not taken into account when building a lib that doesn't have any dependencies.

### Expected Behavior

When running nx build on a project without any dependencies I would expect that the `extends` property is still taken into account.

Also Nx build should succeed without any error in such a scenario.

### GitHub Repo

https://github.com/janwiebedroid/nx-tsconfig-bug/tree/main/nx-ts-config-bugs

### Steps to Reproduce

1. Ensure that there are no compiler options in packages/testlib1/tsconfig.lib.json
2. Run `nx build testlib1`
3. Error occurs

When running nx build on a project with dependencies it works:
1. Ensure that there are no compiler options in packages/testlib-with-deps/tsconfig.lib.json
2. Run `nx build testlib-with-deps`
3. No error occursn

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.17.0
   OS   : win32 x64
   npm  : 8.15.0

   nx                      : 15.7.1
   @nrwl/linter            : 15.7.1
   @nrwl/workspace         : 15.7.1
   @nrwl/cli               : 15.7.1
   @nrwl/devkit            : 15.7.1
   @nrwl/eslint-plugin-nx  : 15.7.1
   @nrwl/js                : 15.7.1
   @nrwl/tao               : 15.7.1
   typescript              : 4.8.4
```

### Additional Information

The issue seems to be in [check-dependencies.ts](https://github.com/nrwl/nx/blob/master/packages/js/src/utils/check-dependencies.ts).

If there are 0 dependencies a temp tsconfig is never created.

**Comment by jaysoo** [comment]
This has been patched here https://github.com/nrwl/nx/commit/afb37c8691159081ff919a9d593dd11848859847

Will be in the 15.9.3 patch release and Nx 16 major release this week.
