### ISSUE TITLE
Allow sharding when running nx run-many

### ISSUE THREAD

**Issue by valtersantosmatosmanulife** [nrwl/nx#15040]
## Description
Allow to pass a shard option to the run many so we can use it like jest using any CI [jest docs](https://jestjs.io/docs/cli#--shard).

## Motivation
Currently, to do the above we would manually trigger `nx run many` for each set of projects which is quite tedious and error prone. Unfortunately we can't always run `affected` (in my case is mandatory, for audit, that we run tests, linters, etc in all files).

## Suggested Implementation
Allow passing `--shard=1/3` and this would randomly run 1/3 of the projects in the `nx run many` command.

## Alternate Implementations
Nothing I can think of.

**Comment by Nightbr** [comment]
+1 on this, could be really useful when you have many app with the same target (for example deploy target needs to deploy 10 apps) could be great to be able to parallelize and run this in different jobs in CI.

**Comment by AgentEnder** [comment]
For speeding up these kinds of things, we generally recommend Nx Cloud's DTE feature. There's a guide on it here, and the benefits of it over sharding / binning. https://nx.dev/concepts/dte
