### ISSUE TITLE
Unable to follow the CONTRIBUTING.md section related to testing

### ISSUE THREAD

**Issue by geometryzen** [nrwl/nx#15057]
### Documentation issue

Unable to comprehend the guidelines regarding testing given in CONTRIBUTING.md

### Is there a specific documentation page you are reporting?

CONTRIBUTING.md

### Additional context or description

I'd like to create a PR for nx but I don't understand how to run unit tests over nx itself or what the tests are running (they appear to be for separate workspaces that you define yourself). Does nx have any "intrinsic" tests? There should be more context about *what* is being tested in CONTRIBUTING.md and *where* testing commands should be run from.

**Comment by AgentEnder** [comment]
`nx affected:test` will run jest for all spec files in proejcts marked as affected by your changes. You can run that command from anywhere ideally. Alternatively, you can run single spec files through IDE tooltips or similar.

**Comment by isaacplmann** [comment]
We'd love to make the docs more clear, but we need more information about what is confusing.  Closing for now.  Reopen the issue if you have more specifics.
