### ISSUE TITLE
New flags (`--routing` & `--standaloneApi`) on `angular-standalone` create-nx-workspace preset cause errors

### ISSUE THREAD

**Issue by zjkipping** [nrwl/nx#15058]
### Current Behavior

Doing the command from the [blog](https://blog.nrwl.io/nx-15-7-node-support-angular-lts-lockfile-pruning-46f067090711) `npx create-nx-workspace@latest ngapp --preset=angular-standalone --standaloneApi` throws an error log file that states:

```
 >  NX   Property 'standaloneApi' does not match the schema. '' should be a 'boolean'.
```

If I run `npx create-nx-workspace@latest ngapp --preset=angular-standalone --standaloneApi=true` it works.

---

Also, when adding the `--routing` flag the process still prompts whether you want to add routing or not...

Running `npx create-nx-workspace@latest ngapp --preset=angular-standalone --standaloneApi --routing`

Immediately prompts for:
```
? Would you like to add routing? ...
Yes
No
```

If I run `npx create-nx-workspace@latest ngapp --preset=angular-standalone --standaloneApi --routing=true`
I am not prompted to add routing.

### Expected Behavior

Using just the shorthand `--standaloneApi` flag should work without being forced to give it a boolean value.

I am not prompted to add routing to my standalone-preset workspace when I add the shorthand `--routing` flag/argument.

### Steps to Reproduce

Run `npx create-nx-workspace@latest ngapp --preset=angular-standalone --standaloneApi --routing`

### Nx Report

```shell
Created via v15.7.1
```

**Comment by zjkipping** [comment]
@Coly010 Any ideas on this front? I am really looking forward to this feature for our class workshops 😄

**Comment by Coly010** [comment]
@zjkipping working on it!
