### ISSUE TITLE
Nx run-many command fails outside of workspace root

### ISSUE THREAD

**Issue by corbinday** [nrwl/nx#15068]
### Current Behavior

When I navigate to any subfolder within my workspace and then run `nx run-many --target=build`, the command fails with this error:

    >  NX   Could not resolve entry module "apps/app1/index.html".

### Expected Behavior

According to Nrwl, `nx` commands should work anywhere in the workspace, but that is not what I was finding as of nx v15.7.1
[see this slack thread](https://nrwlcommunity.slack.com/archives/CMFKWPU6Q/p1676561082150659?thread_ts=1676558822.136729&cid=CMFKWPU6Q)

### GitHub Repo

https://github.com/corbinday/nx-arbitrary-child-dir-regression

### Steps to Reproduce

1. Clone repo
2. Run `nx run-many --target=build` from the workspace root directory and see that it works.
3. Navigate into any subfolder
4. Run `nx run-many --target=build` (should fail)

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : darwin arm64
   npm  : 8.19.3
   
   nx                      : 15.7.1
   @nrwl/linter            : 15.7.1
   @nrwl/workspace         : 15.7.1
   @nrwl/cli               : 15.7.1
   @nrwl/cypress           : 15.7.1
   @nrwl/devkit            : 15.7.1
   @nrwl/eslint-plugin-nx  : 15.7.1
   @nrwl/js                : 15.7.1
   @nrwl/react             : 15.7.1
   @nrwl/tao               : 15.7.1
   @nrwl/vite              : 15.7.1
   typescript              : 4.8.4
```

### Failure Logs

```shell
➜  app1 git:(master) ✗ nx run-many --target=build


    ✖  nx run app1:build:production
       vite v4.1.1 building for production...
✓ 0 modules transformed.
       Could not resolve entry module "apps/app1/index.html".
       
        >  NX   Could not resolve entry module "apps/app1/index.html".
       
          Pass --verbose to see the stacktrace.
       

    ✖  nx run app2:build:production
       vite v4.1.1 building for production...
✓ 0 modules transformed.
       Could not resolve entry module "apps/app2/index.html".
       
        >  NX   Could not resolve entry module "apps/app2/index.html".
       
          Pass --verbose to see the stacktrace.
       

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for 2 projects (452ms)
 
    ✔    0/2 succeeded [0 read from cache]
 
    ✖    2/2 targets failed, including the following:
         - nx run app1:build:production
         - nx run app2:build:production
```

### Additional Information

[related slack thread](https://nrwlcommunity.slack.com/archives/CMFKWPU6Q/p1676558822136729)

**Comment by AgentEnder** [comment]
I'm assigning this to `bundlers` since it appears to be that the `vite` builder is failing.

**Comment by mandarini** [comment]
Hi @corbinday ! I'll take a look at this soon! Thanks for reporting!
