### ISSUE TITLE
@nrwl/js:tsc includes non-toplevel dependencies when building the package.json

### ISSUE THREAD

**Issue by jessecollier** [nrwl/nx#15070]
### Current Behavior

Given three buildable and publishable packages depending on each other:
```
A -> B -> C
```

Building package `A` generates a package.json with a dependency on `B` and `C`.

### Expected Behavior

Package `A` should only have dependency on `B`.

This issue here is that ALL dependencies in the graph are used:
https://github.com/nrwl/nx/blob/master/packages/js/src/executors/tsc/tsc.impl.ts#L168

Compared to @nrwl/angular:package which uses only topLevel dependencies:
https://github.com/nrwl/nx/blob/422c8c735a8a4d7a7f343a176c1ca05ba2f12e98/packages/angular/src/executors/package/package.impl.ts#L104

### Steps to Reproduce

1. Create 3 typescript packages using tsc compiler (packageA, packageB, packageC)
2. Import packageB in package A
3. Import packageC in packageB
4. Build.

### Nx Report

```shell
npx nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.12.1
   OS   : darwin arm64
   npm  : 9.2.0

   nx : 15.3.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.3.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.3.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.3.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.3.3
   @nrwl/web : 15.3.3
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```
```


### Failure Logs

_No response_

### Additional Information

_No response_

**Comment by AgentEnder** [comment]
Can you try to repro this in latest? A lot has changed in this area recently.

**Comment by JosefBredereck** [comment]
See my comment in another issue where I listet everything https://github.com/nrwl/nx/issues/10227#issuecomment-1427064452

There are two similar issues open right now and in one its stated that there are no recent updates.

IMHO other executors could have the same issue because they also don't use the `shallow` option of `calculateProjectDependencies`. Only `rollup` has this working right now.

**Comment by jessecollier** [comment]
> Can you try to repro this in latest? A lot has changed in this area recently.

I'll give it a shot, but I linked to master branch code that has the issue
