### ISSUE TITLE
npx create-nx-workspace: in certain prompts, pressing the insert key produces a loop of "undefined" words

### ISSUE THREAD

**Issue by tbogard** [nrwl/nx#15079]
### Current Behavior

in multiple selection prompts, you can filter by typing **ANYTHING**. if happens you press the "insert" key it produces an "undefined" string

![Code_MGrfdhjcWH](https://user-images.githubusercontent.com/1978642/219565671-70f75185-1ccf-4abb-8216-5b7462c35893.gif)

The second prompt has the same problem, and you could delete the "undefined" string, however it will not let you continue and pick what you want to build. The only option is to press esc and end the wizard

![Code_tywTDHd0x3](https://user-images.githubusercontent.com/1978642/219566352-8db9a36d-2fa3-4981-b5c4-925fe4c30cdb.gif)

result is consistent in all windows terminals (including wsl)

### Expected Behavior

if pressing special keys, it shouldn't accept any "undefined" string

### Steps to Reproduce

1. please follow the current behavior

### Nx Report

```shell
Nx Report can't be run since this happens before the repo is initialized.
```

### Additional Information

terminal: windows/git bash

**Comment by AgentEnder** [comment]
Nx uses enquirer for prompts, can you open this with them?

**Comment by tbogard** [comment]
@AgentEnder can you tell me if this was solved?

**Comment by AgentEnder** [comment]
I don't think an issue was ever opened for enquirer, where this would need to be solved.
