### ISSUE TITLE
@nrwl/workspace:remove: while removing a previous existing app, the next removal still thinks the removed project exists and marks it as part of its dependencies

### ISSUE THREAD

**Issue by tbogard** [nrwl/nx#15077]
### Current Behavior

Running on WSL.
I removed a failed api from the project and this happens: it seems the command still things a previous removed e2e dependency app still exists

![image](https://user-images.githubusercontent.com/1978642/219557473-88a3223d-2691-4705-955f-8d0558858782.png)

### Expected Behavior

It should verify that the dependency is removed from the project. not sure why it throws this error

### GitHub Repo

https://github.com/tbogard/project

### Steps to Reproduce

1. run:
npx nx @nrwl/workspace:remove api-e2e -> it tells all the other projects are dependencies, or it deletes it properly

2. run 
npx nx @nrwl/workspace:remove api -> it tells it can't delete it because api-e2e exists

### Nx Report

```shell
Node : 18.12.1
   OS   : linux x64
   npm  : 8.19.2

   nx                      : 15.7.1
   @nrwl/jest              : 15.7.1
   @nrwl/linter            : 15.7.1
   @nrwl/workspace         : 15.7.1
   @nrwl/cli               : 15.7.1
   @nrwl/cypress           : 15.7.1
   @nrwl/devkit            : 15.7.1
   @nrwl/esbuild           : 15.7.1
   @nrwl/eslint-plugin-nx  : 15.7.1
   @nrwl/js                : 15.7.1
   @nrwl/node              : 15.7.1
   @nrwl/react             : 15.7.1
   @nrwl/tao               : 15.7.1
   @nrwl/vite              : 15.7.1
   @nrwl/webpack           : 15.7.1
   typescript              : 4.8.4
```

**Comment by AgentEnder** [comment]
I can't repro this, I'm not sure whats going on. On my machine (with WSL), I didn't hit the same issue: 
![image](https://user-images.githubusercontent.com/6933928/221700332-d573db68-d8d3-4113-8554-ee8c48eba004.png)


In any case, `nx reset` should clear this if it happens again on your end.
