### ISSUE TITLE
Warn about using --all

### ISSUE THREAD

**Issue by vsavkin** [nrwl/nx#1507]
Many developers use `affected:*` commands with `--all`. It's a convenient way to start with a small repo, but it's almost always the wrong thing to do. 

We need to print a warning message saying that `--all` should not be used in CI or for any large project

**Comment by alfaproject** [comment]
Actually, we use `--all` to run all tests in the `master` branch. It also allows us to use a docker image without git in that scenario. (;

If you have custom builders like we have, it also allows you to run custom builders for all projects (depends on what they do exactly, obviously)

**Comment by vsavkin** [comment]
@alfaproject we aren't removing the option, so you could still use it. For most use cases, however, it is problematic:

- It makes CI slower
- It couples unrelated projects together. So changing one can break other projects in CI. Say you have project1 and project2. You make a change to project1, and suddenly a flaky test in project2 fails. This isn't the best dev experience, and is the main reason why people say that monorepos "do not work".

If it works for you, that's totally cool. You can keep using --all. Most folks, however, should use affected:* or build individual projects. 

Side note:
If you are using jenkins you can add a new stage with a docker image that has git in to get the list of affected projects.

**Comment by vsavkin** [comment]
Closed here: https://github.com/nrwl/nx/commit/815a3b5595e35ffff282e536d7cabfb1f9a73ebf

**Comment by alfaproject** [comment]
Yes, we do that for all non master branches, but in master we always run all tests, so that's where we use this option.
