### ISSUE TITLE
Can't move or rename angular libs

### ISSUE THREAD

**Issue by R0M3** [nrwl/nx#15080]
### Current Behavior

Using the  @nrwl/angular:move generator to move or rename a lib result in the following error, even though the file is present: 

 NX   Cannot find libs\cases\project.json

![image](https://user-images.githubusercontent.com/7732738/219611383-7d997440-0d36-4477-8099-0ba6d1525ce1.png)

### Expected Behavior

Lib should be moved or renamed

### Steps to Reproduce

1. on Windows
2. create an integrated monorepo with an app and a lib
3. attempt to move the lib or rename it
4. fail

### Nx Report

```shell
nx                      : 15.7.1
   @nrwl/jest              : 15.7.1
   @nrwl/linter            : 15.7.1
   @nrwl/workspace         : 15.7.1
   @nrwl/angular           : 15.7.1
   @nrwl/cli               : 15.7.1
   @nrwl/cypress           : 15.7.1
   @nrwl/devkit            : 15.7.1
   @nrwl/eslint-plugin-nx  : 15.7.1
   @nrwl/js                : 15.7.1
   @nrwl/tao               : 15.7.1
   @nrwl/webpack           : 15.7.1
   typescript              : 4.8.4
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Could you post the exact command you ran? Also, could you run it with `--verbose` and post the error stack trace here?

**Comment by R0M3** [comment]
Hi, can't comment on whether it happens on mac unfortunately.

I've tried every variation of the command but the one that should work is `nx g @nrwl/angular:move --project my-feature-lib --destination shared/my-feature-lib`

Verbose stack trace:
![image](https://user-images.githubusercontent.com/7732738/219639761-c704419d-67b5-4162-85fb-65727e317206.png)

**Comment by the-ult** [comment]
Same on Mac with generating an `@nrwl/angular:library`

Other, like `@nrwl/js:library` work

**Comment by R0M3** [comment]
is there a workaround for this at the mo? as i can't currently move or rename any projects which is causing some issues

**Comment by eskres** [comment]
@leosvelperez I've run the command `npx nx g mv --project server --destination packages/apps/server` on windows in a brand new workspace and have the same error. Stack trace below.

`Error: Cannot find packages\server\project.json
    at readJson (node_modules\nx\src\generators\utils\json.js:14:15)
    at node_modules\nx\src\generators\utils\project-configuration.js:120:119
    at buildProjectsConfigurationsFromGlobs (node_modules\nx\src\config\workspaces.js:479:35)
    at readAndCombineAllProjectConfigurations (node_modules\nx\src\generators\utils\project-configuration.js:120:66)
    at getProjects (node_modules\nx\src\generators\utils\project-configuration.js:99:23)    
    at updateBuildTargets (node_modules\@nrwl\workspace\src\generators\move\lib\update-build-targets.js:9:30)
    at node_modules\@nrwl\workspace\src\generators\move\move.js:37:55
    at Generator.next (<anonymous>)
    at node_modules\tslib\tslib.js:167:75
    at new Promise (<anonymous>)`

**Comment by leosvelperez** [comment]
hey all! I'm trying to get a Windows VM setup to reproduce and troubleshoot the issue. I'll get back to you as soon as I have any news. Thanks for the details provided!

**Comment by R0M3** [comment]
Great, thanks. Happy to jump on a call if i can help as i'm on windows atm

**Comment by R0M3** [comment]
I still seem to be getting the same issue, any help would be greatly appreciated
