### ISSUE TITLE
Loop detected while pruning.

### ISSUE THREAD

**Issue by Rafarel** [nrwl/nx#15093]
### Current Behavior

Hi there,

I've migrated my NX workspace from NX `15.4.2` to `15.7.1` but I have some errors.

First, I was unable to run `npm i`without the `--legacy-per-deps` argument.

Then one of my project (An API made with nest) crashes on build or on serve command with the following message :
```
Loop detected while pruning. Please report this issue.
```

So, here I am reporting the issue ^^

I think this happens here with webpack : 
https://github.com/nrwl/nx/blob/8d0c09fffab5e22fcbc64d976ab870697721cbef/packages/nx/src/lock-file/npm-parser.ts#L530

If in my package json I set `@nrwl/webpack` to `15.4.2` instead of `15.7.1` the error disappears. 

### Expected Behavior

Everything should be up to date and able tu run as usual :)

### Steps to Reproduce

1. Have an NX `15.4.2` repo with a Nest app
2. Run `nx migrate latest` that bring my repo to `15.7.1`
3. Build or serve your nest app => Crash

### Nx Report

```shell
Node : 18.13.0
   OS   : darwin arm64
   npm  : 8.19.3
   
   nx                      : 15.7.1
   @nrwl/jest              : 15.7.1
   @nrwl/linter            : 15.7.1
   @nrwl/workspace         : 15.7.1
   @nrwl/angular           : 15.7.1
   @nrwl/cli               : 15.7.1
   @nrwl/cypress           : 15.7.1
   @nrwl/devkit            : 15.7.1
   @nrwl/eslint-plugin-nx  : 15.7.1
   @nrwl/express           : 15.7.1
   @nrwl/js                : 15.7.1
   @nrwl/nest              : 15.7.1
   @nrwl/node              : 15.7.1
   @nrwl/tao               : 15.7.1
   @nrwl/webpack           : 15.7.1
   @nrwl/nx-cloud          : 15.0.3
   typescript              : 4.8.4
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.12.1
   @nguniversal/express-engine      : 15.1.0
   @nguniversal/builders            : 15.1.0
   ng-extract-i18n-merge            : 2.4.0
```

**Comment by ntrehout** [comment]
Same problem, i migrated from 15.5.2 to 15.7.1.

**Comment by icastillejogomez** [comment]
Some here with a Node app
