### ISSUE TITLE
React build output is not working when you use aws-amplify-react

### ISSUE THREAD

**Issue by jcvalerio** [nrwl/nx#1509]
# Prerequisites

- [ X] I am running the latest version
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed
- [ X] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

The output artifacts work without any issue

## Current Behavior

When you publish the output files the react app didn't load. an exception was thrown in the console `Uncaught ReferenceError: process is not defined`

## Failure Information (for bugs)

![image](https://user-images.githubusercontent.com/2169894/59886055-b98f9a00-937a-11e9-80ca-e40bd8903e34.png)

### Steps to Reproduce

Create an empty workspace, add react, create a react application

```
npx --ignore-existing create-nx-workspace myworkspace --preset=empty
cd myworkspace
ng add @nrwl/react
ng g @nrwl/react:app frontend
yarn add aws-amplify aws-amplify-react
```

Update the app file located at `apps/frontend/src/app/app.tsx`

```javascript
import React from 'react';
import { withAuthenticator } from 'aws-amplify-react';
import './app.css';

const App = () => {
  return (
      <div>
          <h1>Welcome to Nx!</h1>
      </div>
  );
};

export default withAuthenticator(App, true);

```

Then just build the project and try to serve locally with serve for example

```
ng build frontend  --prod
http://localhost:5000
```

**Comment by FrozenPandaz** [comment]
You can do this by polyfilling node via webpack:

Create `apps/frontend/webpack.config.js`
```js
module.exports = (config) => {
  return {
    ...config,
    node: {
      global: true,
      process: true
    }
  };
}
```

Add to `angular.json`:
```diff
            "tsConfig": "apps/frontend/tsconfig.app.json",
+           "webpackConfig": "apps/frontend/webpack.config.js",
            "assets": [
              "apps/frontend/src/favicon.ico",
              "apps/frontend/src/assets"
            ],
```

I'm guessing this is the expected result:
![image](https://user-images.githubusercontent.com/8104246/59950149-135b9700-9443-11e9-8b4a-53344d11ad59.png)

Let me know if this works for you.

**Comment by jcvalerio** [comment]
Thanks, @FrozenPandaz that works  :+1:

Would be great to have that in the documentation, or maybe scaffolding the basic configuration, because at the end of the day many of us are going to need to add some polyfill 

Thanks again
