### ISSUE TITLE
 NX   Could not find bootstrapApplication call in apps/re-portal/src/main.ts

### ISSUE THREAD

**Issue by iChintanSoni** [nrwl/nx#15106]
### Current Behavior

I am trying to add package: @angular/material into the workspace using below command:

`npx nx g @angular/material:ng-add --project=re-portal`

but it is throwing below error:

```
 >  NX   Could not find bootstrapApplication call in apps/re-portal/src/main.ts

Error: Could not find bootstrapApplication call in apps/re-portal/src/main.ts
    at addModuleImportToStandaloneBootstrap (/Users/chintansoni/Work/ar-micro-frontend/node_modules/@schematics/angular/private/standalone.js:43:15)
    at addAnimationsModuleToStandaloneApp (/Users/chintansoni/Work/ar-micro-frontend/node_modules/@angular/material/schematics/ng-add/setup-project.js:84:67)
    at /Users/chintansoni/Work/ar-micro-frontend/node_modules/@angular/material/schematics/ng-add/setup-project.js:62:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async callRuleAsync (/Users/chintansoni/Work/ar-micro-frontend/node_modules/@angular-devkit/schematics/src/rules/call.js:78:18)
```

### Expected Behavior

It should add package and allow to use material components into the project.

### Steps to Reproduce

1. Create workspace with dynamic host and remotes
2. Try hitting the below command into terminal:
`npx nx g @angular/material:ng-add --project=re-portal`
3. Throws error

### Nx Report

```shell
Node : 19.6.0
   OS   : darwin arm64
   npm  : 9.4.0
   
   nx                      : 15.8.0-beta.1
   @nrwl/jest              : 15.8.0-beta.1
   @nrwl/linter            : 15.8.0-beta.1
   @nrwl/workspace         : 15.8.0-beta.1
   @nrwl/angular           : 15.8.0-beta.1
   @nrwl/cli               : 15.8.0-beta.1
   @nrwl/cypress           : 15.8.0-beta.1
   @nrwl/devkit            : 15.8.0-beta.1
   @nrwl/eslint-plugin-nx  : 15.8.0-beta.1
   @nrwl/js                : 15.8.0-beta.1
   @nrwl/tao               : 15.8.0-beta.1
   @nrwl/webpack           : 15.8.0-beta.1
   typescript              : 4.8.4
```

**Comment by Coly010** [comment]
This isn't an issue that can be resolved when you use Module Federation.

The `@angular/material:ng-add` generator looks for `bootstrapModule` or `bootstrapApplication` in the `main.ts` file, however, for Module Federation to function correctly, the `main.ts` file needs to dynamically import a file that contains these `bootstrap` functions, so they are placed in a `bootstrap.ts` file.

The workaround is:

1. Make a copy of your `main.ts` file
2. Replace the contents of the original `main.ts` file with the contents of `bootstrap.ts`.
3. Run the `ng-add` generator.
4. Replace the main.ts file with the copy you had made.

I'm going to close this issue as there is a workaround, and we have no reasonable way to modify the Angular schematic
