### ISSUE TITLE
--routing and --standaloneApi are boolean, not string in create-nx-workspace

### ISSUE THREAD

**Issue by LowArmour** [nrwl/nx#15118]
### Documentation issue

- [ ] Reporting a typo
- [x ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[https://nx.dev/packages/nx/documents/create-nx-workspace](https://nx.dev/packages/nx/documents/create-nx-workspace)

### Additional context or description

The documentation linked above states that --routing and --standaloneApi is of type "string", which is actually "boolean".
Only the following works:
`npx create-nx-workspace@latest --name=myorg --appName=myapp --preset=angular-monorepo --style=scss --standaloneApi=true --routing=true --nxCloud=false`

The following issues error:
`npx create-nx-workspace@latest --name=myorg --appName=myapp --preset=angular-monorepo --style=scss --standaloneApi --routing --nxCloud=false`

**Comment by AgentEnder** [comment]
Fix is in flight, #15083
