### ISSUE TITLE
nx src/app/app.module.ts is absent in app angular

### ISSUE THREAD

**Issue by TatyanaMolchanova** [nrwl/nx#15111]
### Current Behavior

I create workspace with standalone Angular app and trying in 5th time to repeat the code from the nx tutorial https://nx.dev/angular-standalone-tutorial/2-project-graph but in my project with standalone Angular or multirepos with Angular always is absent file app.module.ts.

https://github.com/TatyanaMolchanova/nx-angular-standalone

### Expected Behavior

App.module.ts has to be in project - in tutorial it's described.

### GitHub Repo

https://github.com/TatyanaMolchanova/nx-angular-standalone

### Steps to Reproduce

1. https://nx.dev/getting-started/angular-standalone-tutorial#creating-a-new-workspace

### Nx Report

```shell
No report - just absent file app.module.ts
```

### Failure Logs

```shell
No app.module.ts in NX project with Angular standalone and/or multi repos project with Angular.
```

**Comment by Coly010** [comment]
@TatyanaMolchanova I think you may have followed the CNW prompts incorrectly. The repo you have linked is set up to use Standalone Components, which doesn't use `app.module.ts` hence why it is not present.


When I enter the prompt options with the following answers, it creates the `app.module.ts` file as expected

```
npx -y create-nx-workspace@latest nxappstd --preset=angular-standalone

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Would you like to use Standalone Components in your application? · No
✔ Would you like to add routing? · Yes
✔ Default stylesheet format             · css
✔ Enable distributed caching to make your CI faster · No

 >  NX   Nx is creating your v15.7.2 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✔ Nx has successfully created the workspace: nxappstd.

 >  NX   Successfully initialized git.
```
