### ISSUE TITLE
15.7 doesn't recognize workspace anymore

### ISSUE THREAD

**Issue by DaSchTour** [nrwl/nx#15112]
### Current Behavior

nx commands fail with `The current directory isn't part of an Nx workspace.` Only when using npx in front the commands work.

### Expected Behavior

nx commands work normally without npx

### Steps to Reproduce

1. Migrate to 15.7 or later and run migrations so that workspace.json or angular.json is removed
2. Try to run an nx command without npx in front.

### Nx Report

```shell
Node : 18.13.0
   OS   : darwin x64
   npm  : 8.19.3
   
   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/angular           : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/esbuild           : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/nest              : 15.7.2
   @nrwl/node              : 15.7.2
   @nrwl/nx-plugin         : 15.7.2
   @nrwl/rollup            : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/webpack           : 15.7.2
   @nrwl/nx-cloud          : 15.0.3
   typescript              : 4.8.4
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.12.1
   @ionic/angular                   : 6.3.9
   @nestjs/ng-universal             : 7.0.1
   @ngrx/component                  : 15.3.0
   @ngrx/component-store            : 15.3.0
   @ngrx/data                       : 15.3.0
   @ngrx/effects                    : 15.3.0
   @ngrx/entity                     : 15.3.0
   @ngrx/router-store               : 15.3.0
   @ngrx/store                      : 15.3.0
   @ngrx/store-devtools             : 15.3.0
   @nguniversal/common              : 15.1.0
   @nguniversal/express-engine      : 15.1.0
   apollo-angular                   : 4.2.0
   @compodoc/compodoc               : 1.1.19
   @jscutlery/semver                : 2.27.0
   @ngneat/spectator                : 14.0.0
   @ngrx/eslint-plugin              : 15.3.0
   @ngrx/schematics                 : 15.3.0
   @nguniversal/builders            : 15.1.0
   @nx-tools/nx-container           : 4.0.2
   @nxext/capacitor                 : 15.2.0
   @nxext/ionic-angular             : 15.1.0
   @trellisorg/make-buildable       : 0.0.12
   @twittwer/compodoc               : 1.8.0
   ng-mocks                         : 14.5.3
   ngx-build-plus                   : 15.0.0
   ngx-deploy-npm                   : 5.0.0
   nx-stylelint                     : 14.0.2
   ---------------------------------------
   Local workspace plugins:
   	 @footage.one/nx-version
```

**Comment by elizww** [comment]
same to me using Windows

**Comment by mlc-mlapis** [comment]
Same for me.

**Comment by AgentEnder** [comment]
You probably need to update your global install of Nx, with whatever package manager you installed it globally with.

**Comment by sergidt** [comment]
Same here, angular.json and workspace.json have been deleted

**Comment by AgentEnder** [comment]
> You probably need to update your global install of Nx, with whatever package manager you installed it globally with.

**Comment by DaSchTour** [comment]
Is there any troubleshooting guide in the documentation? Maybe it should be mentioned that an npm ls -g nx can display the currently installed global nx version and npm update -g nx will update.
Maybe nx could check the globally installed nx version and report deviations?

**Comment by AgentEnder** [comment]
We don't currently have any guides which show how to troubleshoot your global install, partially because of how many ways there are to create a global install. Each of the package managers can do so, and each place it in a slightly different place. If you install globally with yarn, `npm ls -g` will not show the package at all since yarn manages it and such.

Personally, I tend to just opt to not use a global install, and have aliased `nx = npx nx` in my `.bashrc` file. This works for repos that use either yarn or npm, but may fail in some cases for pnpm IIRC. You could of course set an equivalent alias if your repos use pnpm.

We had added a check for outdated global installs at some point, but it was a source of more pain than one may imagine. I know we removed it due to some bugginess, its perhaps something that could eventually come back though.
