### ISSUE TITLE
Test files within src/app are not considered for an standalone workspace with Angular

### ISSUE THREAD

**Issue by jase88** [nrwl/nx#15121]
### Current Behavior

If creating a fresh nx standalone workspace with an angular app, tests within the default `src` folder are not picked up by jest.

Test files within created libraries are picked up.

### Expected Behavior

The default workspace should also consider tests within the main app and execute them if running `nx test example`.

### Steps to Reproduce

1. `npx create-nx-workspace@latest --preset angular-standalone --appName example --standaloneApi true --style css --routing false --nxCloud false`
2. create a file in `example\src\app\example.spec.ts` 
```
describe('example test', () =>
  it('should test', () => expect(true).toBeTruthy())
);
````
3. `nx run example:test`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.14.0
   OS   : win32 x64
   npm  : 9.5.0

   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/angular           : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/webpack           : 15.7.2
   typescript              : 4.8.4
```

### Failure Logs

```shell
No tests found, exiting with code 0
```

**Comment by Coly010** [comment]
@jase88 Can you provide a repo that reproduces this issue?

I tried following the steps you provided but everything worked as expected

<img width="664" alt="image" src="https://user-images.githubusercontent.com/12140467/220456978-d25f8779-6420-4ec8-b54c-3cdc8814ba22.png">

**Comment by jase88** [comment]
Sure https://github.com/jase88/nx-standalone-test-example

![image](https://user-images.githubusercontent.com/804836/220548419-0ebc14cc-28e1-47fd-a599-d663b43fa701.png)

Maybe only occuring on Windows?

**Comment by Coly010** [comment]
Yep, it's a windows issue. I cloned on windows and I cloned on MacOS. It works on mac, but not windows

**Comment by leosvelperez** [comment]
Hey @jase88! A fix was merged for new workspaces and it will be released soon. To apply the fix in your workspace, please make sure to update the `testMatch` option of your `jest.config.ts` files replacing `<rootDir>/src/**/?(*.)+(spec|test).[jt]s?(x)` with `<rootDir>/src/**/*(*.)@(spec|test).[jt]s?(x)`.

**Comment by jase88** [comment]
@leosvelperez thanks this works fine!
