### ISSUE TITLE
generateLockfile fail with pnpm on some specific packages

### ISSUE THREAD

**Issue by BatmanTheBlind** [nrwl/nx#15123]
### Current Behavior

When enabling generateLockfile in a node library, the build of the library fail with the following error for packages using glob package as dependency : 
```
Compiling TypeScript files for project "test"...
Done compiling TypeScript files for project "test".
E:\test-integrated\node_modules\.pnpm\nx@15.7.2\node_modules\nx\src\lock-file\project-graph-pruning.js:128
        if (packageJsonDeps[current.data.packageName] === current.data.version) {
                                    ^

TypeError: Cannot read properties of undefined (reading 'data')
    at pathLengthToIncoming (E:\test-integrated\node_modules\.pnpm\nx@15.7.2\node_modules\nx\src\lock-file\project-graph-pruning.js:128:37)
    at E:\test-integrated\node_modules\.pnpm\nx@15.7.2\node_modules\nx\src\lock-file\project-graph-pruning.js:97:34
    at Array.forEach (<anonymous>)
    at E:\test-integrated\node_modules\.pnpm\nx@15.7.2\node_modules\nx\src\lock-file\project-graph-pruning.js:96:25
    at Map.forEach (<anonymous>)
    at rehoistNodes (E:\test-integrated\node_modules\.pnpm\nx@15.7.2\node_modules\nx\src\lock-file\project-graph-pruning.js:87:23)
    at pruneProjectGraph (E:\test-integrated\node_modules\.pnpm\nx@15.7.2\node_modules\nx\src\lock-file\project-graph-pruning.js:17:5)
    at createLockFile (E:\test-integrated\node_modules\.pnpm\nx@15.7.2\node_modules\nx\src\lock-file\lock-file.js:117:75)
    at updatePackageJson (E:\test-integrated\node_modules\.pnpm\@nrwl+js@15.7.2_iewltepy45s5cyhsd2ythsmlha\node_modules\@nrwl\js\src\utils\package-json\update-package-json.js:42:57)
    at E:\test-integrated\node_modules\.pnpm\@nrwl+js@15.7.2_iewltepy45s5cyhsd2ythsmlha\node_modules\@nrwl\js\src\executors\tsc\tsc.impl.js:86:57 
```

### Expected Behavior

The pnpm-lock.yaml file should be generated in dist folder without error.

### Steps to Reproduce

1. Create a new workspace with TypeScript preset and specifying pnpm as the package manager:
`npx create-nx-workspace@latest test-integrated --preset=ts --packageManager=pnpm`

2. Install the required dependencies with pnpm
`pnpm i @types/node @babel/core @nrwl/node`

3. Create a node library
`npx nx g @nrwl/node:lib test --publishable --importPath @test/test`

4. Install the tsoa package with pnpm (this package reference @tsoa/cli which reference glob)
`pnpm i tsoa`

5. Update the file in `packages\test\src\lib\test.ts` with the following content:
```
export * from "tsoa"
```

6. Build the test project
```
npx nx build test
```

The build fails with the error described above.

### Nx Report

```shell
Node : 16.17.0
   OS   : win32 x64
   pnpm : 7.27.1

   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/cli               : 15.7.1
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/node              : 15.7.2
   @nrwl/tao               : 15.7.1
   typescript              : 4.8.2
   ---------------------------------------
```

### Additional Information

- This issue doens't occur if the glob package is explicitly referenced in the package.json at the root of the workspace
- This issue doesn't occur with another package like express (which, I assume, doesn't have glob as dependency).
- This issue doesn't occur if workspace and packages are installed with npm

**Comment by meeroslav** [comment]
Fixed with [#15052](https://github.com/nrwl/nx/pull/15052)
