### ISSUE TITLE
When building a new angular app the build will not finish

### ISSUE THREAD

**Issue by Rofer11607** [nrwl/nx#15127]
### Current Behavior

This is the output of the build:

✔ Browser application bundle generation complete.

./apps/bildtest/src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Transform failed with 1 error:
/Users/goose/Documents/programming/the-tech-goose/apps/bildtest/src/app/app.component.css:64:84: ERROR: Unterminated string token

./node_modules/css-loader/dist/runtime/api.js - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
BrowserslistError: [BABEL] /Users/goose/Documents/programming/the-tech-goose/node_modules/css-loader/dist/runtime/api.js: Unknown version 110 of edge (While processing: "base$0$0")

./node_modules/css-loader/dist/runtime/noSourceMaps.js - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
BrowserslistError: [BABEL] /Users/goose/Documents/programming/the-tech-goose/node_modules/css-loader/dist/runtime/noSourceMaps.js: Unknown version 110 of edge (While processing: "base$0$0")

./node_modules/zone.js/fesm2015/zone.js - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
BrowserslistError: [BABEL] /Users/goose/Documents/programming/the-tech-goose/node_modules/zone.js/fesm2015/zone.js: Unknown version 110 of edge (While processing: "base$0$0")

./apps/bildtest/src/styles.css?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
BrowserslistError: [BABEL] /Users/goose/Documents/programming/the-tech-goose/node_modules/css-loader/dist/runtime/noSourceMaps.js: Unknown version 110 of edge (While processing: "base$0$0")

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for project bildtest (4s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]

### Expected Behavior

The package should build.

### GitHub Repo

https://github.com/Rofer11607/the-tech-goose

### Steps to Reproduce

1. 'npx nx g @nrwl/angular:app testApp'
2. 'npx nx build testApp'

### Nx Report

```shell
Node : 16.19.0
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 15.6.3
   @nrwl/angular : 15.6.3
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : 15.6.3
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : 15.6.3
   @nrwl/next : Not Found
   @nrwl/node : 15.6.3
   @nrwl/nx-cloud : 15.0.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.6.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : 15.6.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
already provided
```

### Additional Information

I have a similar issue with @nrwl/nest

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This is not an Nx issue but an issue with `browserslist`. Make sure to run `npx browserslist --update-db` to get the browsers data updated in your repo.

Please note the repo you shared has two different lock files (`package-lock.json` and `yarn.lock`). I removed `package-lock.json` and ran the above command and the issue goes away.

I'm closing this since there's no issue with Nx.
