### ISSUE TITLE
what is the purpose of updateBuildableProjectDepsInPackageJson

### ISSUE THREAD

**Issue by GaryB432** [nrwl/nx#15135]
### Documentation issue

I cannot learn why my package [@gb-nx/workspace - npm](https://www.npmjs.com/package/@gb-nx/workspace) was having dependency issues installing with latest NX.
I am using `@nrwl/js:tsc` and see the option `updateBuildableProjectDepsInPackageJson` but the purpose is not discussed.
Investigating some other more popular plugins from `nx list` (viz [nxkit/playwright](https://github.com/nxkit/nxkit/blob/main/packages/playwright/project.json)) I see that they have that option set to `false`.
Thanks for a great product! I can't work without it anymore!

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

[@nrwl/js:tsc | Nx](https://nx.dev/packages/js/executors/tsc#updatebuildableprojectdepsinpackagejson)

### Additional context or description

Guided by [The Parable of Chesterton’s Fence](https://latterdaysaintmag.com/the-parable-of-chestertons-fence/), I would like to better understand the implications of turning it off.

**Comment by isaacplmann** [comment]
https://nx.dev/more-concepts/buildable-and-publishable-libraries#publishable-libraries

"Nx [also analyzes](https://nx.dev/packages/angular/executors/package#updatebuildableprojectdepsinpackagejson) the library’s dependencies and automatically compiles the dependencies in the resulting package.json file."

This property controls whether the `tsc` executor should update the `peerDependencies` of the `package.json` in your `dist` folder to include all the packages that your project uses.
