### ISSUE TITLE
.env.production does not override environment variables in .env file

### ISSUE THREAD

**Issue by jarodburchill** [nrwl/nx#15130]
### Current Behavior

a `.env.production` file does not override environment variables in a `.env` file when serving in a production configuration

### Expected Behavior

a `.env.production` file should override environment variables in a `.env` file when serving in a production configuration 

### GitHub Repo

https://github.com/jarodburchill/nx-env-issue-example

### Steps to Reproduce

Setup (can skip if using provided repo):
1. `npx create-nx-workspace nx-env-issue-example --preset=react-monorepo --appName=myapp --bundler=vite --style=css --nxCloud=false`
2. `cd nx-env-issue-example`
3. `echo 'VITE_MOCK=enabled' > ./apps/myapp/.env`
4. `echo 'VITE_MOCK=disabled' > ./apps/myapp/.env.production`
5. `echo '/// <reference types="vite/client" />' > ./apps/myapp/src/vite-env.d.ts` (I personally think this file should be part of the preset template)
6. `echo 'console.log(import.meta.env.VITE_MOCK)' >> ./apps/myapp/src/main.tsx`

Serve in development configuration:
1. `npx nx serve myapp --configuration development`
2. NOTE: browser console logs `enabled` (expected)

Serve in production configuration:
1. `npx nx serve myapp --configuration production`
2. NOTE: browser console logs `enabled` (unexpected, should log `disabled`)

Workaround:
`mv ./apps/myapp/.env ./apps/myapp/.env.development`
with this workaround, when serving in production the browser will now log `disabled` but this workaround requires you to maintain a `.env.[mode]` file for every configuration and not have a shared `.env` file

### Nx Report

```shell
Node : 18.12.1
   OS   : darwin arm64
   npm  : 8.19.2
   
   nx                      : 15.7.0
   @nrwl/linter            : 15.7.0
   @nrwl/workspace         : 15.7.0
   @nrwl/cli               : 15.7.0
   @nrwl/cypress           : 15.7.0
   @nrwl/devkit            : 15.7.0
   @nrwl/eslint-plugin-nx  : 15.7.0
   @nrwl/js                : 15.7.0
   @nrwl/react             : 15.7.0
   @nrwl/tao               : 15.7.0
   @nrwl/vite              : 15.7.0
   typescript              : 4.8.4
```

**Comment by AgentEnder** [comment]
This was added in v15.8.0, betas are currently released but latest hasn't been updated yet.

**Comment by jarodburchill** [comment]
@AgentEnder just tried with `create-nx-workspace@15.8.0-beta.1` and the issue still persists. 

I have updated my example [repo](https://github.com/jarodburchill/nx-env-issue-example) accordingly.

**Comment by jarodburchill** [comment]
@AgentEnder It works if I use `.env.serve.production` though, is there a reason `.env.production` isn't supported?

**Comment by jarodburchill** [comment]
Could Vite's [Env Variables and Modes](https://vitejs.dev/guide/env-and-mode.html) be conflicting?

**Comment by PointSingularity** [comment]
Having the same issue ```15.8.5```.
