### ISSUE TITLE
Migration from nx 13 to nx 15.1.1 and angular 13 to angular 14

### ISSUE THREAD

**Issue by DimitriLib** [nrwl/nx#15141]
### Current Behavior

Generated migrations script. Executing migration script causing migration fail.

### Expected Behavior

Migration should be successful.

### GitHub Repo

https://github.com/DimitriLib/nx-angular-upgrade13-14

### Steps to Reproduce

1. created empty workspace with angular preset: npx create-nx-workspace@13.10.1 --preset=angular
2. answered all prompts, workspace generated
3. added material/cdk libraries to dependency in package.json file
4. added dev-dependencies "@angular-architects/ddd": "2.0.0"
5.  executed the following commands to generate libs:
ng g @angular-architects/ddd:domain hello
ng generate @angular-architects/ddd:ui --name=hello --domain=hello
ng g @angular-architects/ddd:feature hello --domain hello --entity hello --app test 
6. Run migration: nx migrate 15.1.1
7. Run npx nx migrate --run-migrations
8. Received the following error:
 >  NX   Failed to run migration-entry-components from @angular/core. This workspace is NOT up to date!
 >  NX   Could not find any tsconfig file. Cannot remove `entryComponents`.
9. Removed previous failing step from migrations.js fails on the next step 
 >  NX   Failed to run migration-v14-typed-forms from @angular/core. This workspace is NOT up to date!
 >  NX   Could not find any tsconfig file. Cannot migrate to Typed Forms.
If you would remove that one as well and run it again.
10. After removing those 2 steps from migration it passes.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.12.1
   OS   : win32 x64
   npm  : 8.19.2

   nx : 15.1.1
   @nrwl/angular : 15.1.1
   @nrwl/cypress : 15.1.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.1.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.1.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.1.1
   @nrwl/js : 15.1.1
   @nrwl/linter : 15.1.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.1.1
   @nrwl/web : Not Found
   @nrwl/webpack : 15.1.1
   @nrwl/workspace : 15.1.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by petr-konopelko** [comment]
Same for me. In my case 

1. I migrated from angular 12 to angular 13. 
2. Updated to project.json based configuration from angular.json https://nx.dev/more-concepts/nx-and-angular#angular-cli-has-some-limitations,-and-nx-addresses-them.
3. Migrated to angular 14 from angular 13
4. Run migrations nx migrate --run-migrations
It fails on the migration
{
      "version": "14.0.0-beta",
      "description": "As of Angular version 13, `entryComponents` are no longer necessary.",
      "factory": "./migrations/entry-components/index",
      "package": "@angular/core",
      "name": "migration-entry-components"
}
I logged some additional information in js files to get better understanding what is going on

__Skipping invalid project value; expected an object.
Skipping invalid project value; expected an object.
Skipping invalid project value; expected an object.
{
  projects: ProjectDefinitionCollection {
    _listener: [Function: collectionListener],
    _map: Map(0) {}
  },
  extensions: {
    version: 1,
    projects: [Object: null prototype] {
      demo: 'apps/demo',
      components: 'libs/components',
      'components-beta': 'libs/components-beta'
    }
  },
  [Symbol(@angular/core:workspace-json)]: JsonWorkspaceMetadata {
    filePath: 'angular.json',
    ast: { type: 'object', offset: 0, length: 117, children: [Array] },
    raw: '{"version":1,"projects":{"demo":"apps/demo","components":"libs/components","components-beta":"libs/components-beta"}}',
    changes: Map(0) {},
    hasLegacyTargetsName: true
  }
}
SchematicsException [Error]: Could not find any tsconfig file. Cannot remove `entryComponents`.
    at SchematicImpl.<anonymous> (D:\Users\Petro.Konopelko\wk\Project\source\WizNG.UI.Components\node_modules\@angular\core\schematics\migrations\entry-components\index.js:45:23)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Users\Petro.Konopelko\wk\Project\source\WizNG.UI.Components\node_modules\@angular\core\schematics\migrations\entry-components\index.js:11:58)__

It seems that it reads the angular.json in not modified format. But in my case the version in angular.json = 2, bit in the log I can see that it shows me as 1.

**To fix that issue I moved revert changes of migrating to project.json format and merged to one angular .json. After that al the migrations were passed successfuly** 
@DimitriLib , maybe it will help as temporary solution

**Comment by leosvelperez** [comment]
Thanks for reporting this!

I've reproduced the issue and I'm working on a fix. In the meantime, to workaround the issue, you can run the migrations setting the `NX_MIGRATE_USE_LOCAL` env variable to `true`:

```shell
# Unix-like OS
NX_MIGRATE_USE_LOCAL=true yarn nx migrate --run-migrations

# Windows CMD
set "NX_MIGRATE_USE_LOCAL=true" && yarn nx migrate --run-migrations
```
