### ISSUE TITLE
Example repos that embrace the book "Enterprise Angular Monorepo Patterns" by nrwl

### ISSUE THREAD

**Issue by appsolutegeek** [nrwl/nx#1515]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

I have been reading the Enterprise Angular Monorepo patterns, and although its be a great journey - I still have many questions :-)

I was hoping that there was an example repo that embraces the standards inside the book.

For example, some concerns I have right now, is where should i put the pages ? Should they be in their specific libraries ? IT mentions - UI SHELL in the book, should there just be one UI Shell ?

I think have a repo that embraces the book would help to fill in the gaps a little for me.

I would just like a little more visibility on the folder structure inside a library when it comes to smart components vs dumb components.

I am using Angular with NEST.

Nest I understand fully and this isn't where my question rise from, its more from the angular part and underlining structure for organizing pages, components etc.

Does anybody know of a good resource - I can't be the only one that still has questions after reading the book ? :-) Or maybe I am :-)

**Comment by appsolutegeek** [comment]
For example, the main layout (app.component) - should we still be using this in the main app or should it be pulled out into a feature ? 

Or should it in fact be part of the lib/shared ?

**Comment by FrozenPandaz** [comment]
We don't have a good simple canonical example. You can refer to the [Angular Console repo](https://github.com/nrwl/angular-console) for a real world example.

I'm planning on starting one. It would be an e-commerce site. (I can post more details once I flush it out)

Would people find this useful? Would anybody be interested in contributing?

**Comment by ramarivera** [comment]
I for one spent more than a week discussing and thinking where would I put every thing I now have on a "vanilla" Angular App, and thinking about libraries relationships, types, etc . It was a good excercise, for example after some thinking/tweeting I realized the better place for all my interfaces and classes for models would be an util type library called types/models.

So yes, I would find it very useful even if I already kinda have my structure working, to see how it compares to that. As far as contributing, I unfortunately have some very streesfull weeks coming in the near future, but I would love to after that ^^

**Comment by appsolutegeek** [comment]
Yes, I would find it very useful. I think the book does a good job about setting up a base - but having a real repo that follows  the book would be really helpful.

Also maybe having a repo that does full stack, so Angular + NestJS backend and what what be really cool ( i believe a reference is made to it in the book but it doesnt good further) - creating a UI library for components, we are currently doing this in its own NX library using storybook.

This will give a good understanding of all the both can interact together etc.

**Comment by appsolutegeek** [comment]
@FrozenPandaz Also what would be handy is having some kind of slack (or other medium), support channel - where everyone can get involved and ask questions about doubts.

**Comment by FrozenPandaz** [comment]
I've updated the `nx-examples` repo: http://github.com/nrwl/nx-examples!

It uses the concepts in the book. It's not full stack yet but I plan on moving the data into microservices. Please let me know your thoughts about the repo.

**Comment by FrozenPandaz** [comment]
@appsolutegeek

There is the gitter channel: https://gitter.im/nrwl-nx/community
And a slack community: https://join.slack.com/t/nrwlcommunity/shared_invite/enQtNzU5MTE4OTQwOTk0LTgxY2E0ZWYzMWE0YzA5ZDA2MWM1NDVhNmI2ZWMyYmZhNWJiODk3MjkxZjY3MzU5ZjRmM2NmNWU1OTgyZmE4Mzc

**Comment by Tucaen** [comment]
Sorry, but it doesn't look like the nx-examples reflects the best-practices of the book 🤔 
@ramarivera would you mind sharing your structure?

There is also already an issue for this on the nx-example repo: https://github.com/nrwl/nx-examples/issues/75

**Comment by jczacharia** [comment]
@Tucaen If you are still interested, this helped me out A LOT. https://www.softwarearchitekt.at/aktuelles/sustainable-angular-architectures-2/
