### ISSUE TITLE
'proxyConfig' is not found in schema

### ISSUE THREAD

**Issue by ratoi-crysty** [nrwl/nx#15156]
### Current Behavior

Using 'proxyConfig' with `@nrwl/web:dev-server` is not possible anymore as the option is not available anymore.

```
// "executor": "@nrwl/web:dev-server", 
// "options": 
{
  "buildTarget": "<string>",
  "port": 18,
  "host": "<string>",
  "ssl": true,
  "sslKey": "<string>",
  "sslCert": "<string>",
  "watch": true,
  "liveReload": true,
  "hmr": true,
  "publicHost": "<string>",
  "open": true,
  "allowedHosts": "<string>",
  "memoryLimit": 55,
  "maxWorkers": 43,
  "baseHref": "<string>"
}
```

### Expected Behavior

Using proxyConfig option with  `@nrwl/web:dev-server` should work.

### Steps to Reproduce

1. Create a NX workspace with an React application using webpack as build option
2. Add proxyConfig to serve.options in project.json (targets.serve.options)
3. Start the application

### Nx Report

```shell
nx serve web

> nx run web:serve:development


 >  NX   'proxyConfig' is not found in schema



 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target serve for project web failed

   Failed tasks:
   
   - web:serve:development
   
   Hint: run the command with --verbose for more details.

error Command failed with exit code 1.
```

### Additional Information

The documentation seems to be in sync with the missing option from schema. 
Was this removed on purpose? If yes, is there an alternative, besides switching to Vite.

**Comment by jaysoo** [comment]
Use `@nrwl/webpack:dev-server` and it'll work. 

Make sure you are creating workspaces with `npx create-nx-workspace@latest`, and for existing workspaces you run `nx migrate@latest`.

We're using the `proxyConfig` ourselves here: https://github.com/nrwl/nx-coding-assignment
