### ISSUE TITLE
Unsatisfied version 1.0.0 from fgis-core of shared singleton module @hookform/resolvers/yup

### ISSUE THREAD

**Issue by ko22009** [nrwl/nx#15150]
### Current Behavior

I have installed @hookform/resolvers 2.9.11 in packege.json of project.
But in my code I use @hookform/resolvers/yup.
I using shared module federation plugin.

Your stupid devtool didn't recognize correct version.
@hookform/resolvers/yup has 1.0.0 version in root dep: @hookform/resolvers.
But you script take version from @hookform/resolvers.

### Expected Behavior

@hookform/resolvers/yup should not take version of its parent.

I suggested fix, but your reviewer didn't get it.
https://github.com/nrwl/nx/pull/15114

### Steps to Reproduce

1. install @hookform/resolvers to your package.json file
2. import @hookform/resolvers/yup and use in app.

### Nx Report

```shell
-
```

**Comment by Coly010** [comment]
Let's refrain from the anger, please.

I can't do anything until I have an actual reproduction, preferably a repository that I can clone.

**Comment by ko22009** [comment]
@Coly010, https://github.com/ko22009/nx-error-shared-example

**Comment by ko22009** [comment]
@Coly010, hi, how is it going? did you manage to figure it out?

**Comment by ko22009** [comment]
up

**Comment by doiya46** [comment]
I also get same error. Host build use newest version but remote doesn't use the same version like host.

**Comment by jamesiwat** [comment]
```

consumes:49 
        
       Uncaught (in promise) Error: Unsatisfied version 1.0.0 from landing-page of shared singleton module @hookform/resolvers/zod (required ^2.9.11)
    at getStrictSingletonVersion (consumes:49:1)
    at consumes:130:1
    at consumes:82:1
    at 959 (consumes:156:1)
    at consumes:253:1
    at Array.forEach (<anonymous>)
    at __webpack_require__.f.consumes (consumes:236:1)
    at ensure chunk:6:1
    at Array.reduce (<anonymous>)
    at __webpack_require__.e (ensure chunk:5:1)
```

I think it is similar issue.

**Comment by zecamacho** [comment]
I have the same issue with same library as well

**Comment by ko22009** [comment]
> Let's refrain from the anger, please.
> 
> I can't do anything until I have an actual reproduction, preferably a repository that I can clone.

What will we doing?

**Comment by ko22009** [comment]
up

**Comment by TejaswiniAmzur** [comment]
what is the solution for this
