### ISSUE TITLE
Remove dependency on `@nrwl/cypress` for `@nrwl/next` and `@nrwl/storybook`

### ISSUE THREAD

**Issue by mcmxcdev** [nrwl/nx#15177]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Looking at our lockfile, I see that `@nrwl/cypress` is installed by both next and storybook nx dependencies. We use https://github.com/microsoft/playwright and have no use for `cypress` being part of our dependencies.

## Motivation
Less dependency bloat, only install what you need

**Comment by mandarini** [comment]
Hi there @mcmxcdev ! Thank you for filing this feature request! I see you are willing to implement it! Do you want to give this a shot, and tag me in the PR? I can help you if you need!

**Comment by mcmxcdev** [comment]
I didn't tick the box for implementing the change, but I can still attempt it if you guys give me a hint of what is necessary to improve.

**Comment by mandarini** [comment]
Haha ohhh that's right!! Ok, I'll take a look maybe next week then! :D Thank youuuuu!!!

**Comment by mandarini** [comment]
Hey @mcmxcdev sorry I unassigned myself from this! :( You can try giving this a shot, if you want! Look for uses of [`ensurePackage`](https://nx.dev/packages/devkit/documents/nrwl_devkit#ensurepackage) to get an idea of how this could be implemented!

Thank youuuuu! :D
