### ISSUE TITLE
Don't install deprecated `url-loader` and `file-loader` as part of `@nrwl/webpack` migration and use suggested asset modules instead

### ISSUE THREAD

**Issue by mcmxcdev** [nrwl/nx#15173]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
In some recent nx version, `@nrwl/webpack` dependency had a migration to install it's peer dependencies if I remember correctly. Some of the dependencies that got added to the `package.json` were [url-loader](https://github.com/webpack-contrib/url-loader) and [file-loader](https://github.com/webpack-contrib/file-loader) which are both deprecated.

Get rid of them for the migration and use https://webpack.js.org/guides/asset-modules/ instead.

## Motivation

Running into `> NX ajvKeywords is not a function` error on Vercel deployments.

Investigation points to mixed version usage of `loader-utils` as culprit, which is pulled in by nx dependencies.

(Output of `pnpm why`)
```
@nrwl/nest 15.7.2
└─┬ @nrwl/node 15.7.2
  └─┬ @nrwl/webpack 15.7.2
    ├─┬ file-loader 6.2.0
    │ └── loader-utils 2.0.4
    └── loader-utils 2.0.4
@nrwl/next 15.7.2
├─┬ @nrwl/webpack 15.7.2
│ ├─┬ file-loader 6.2.0
│ │ └── loader-utils 2.0.4
│ └── loader-utils 2.0.4
└─┬ url-loader 4.1.1
  └── loader-utils 2.0.4
@nrwl/node 15.7.2
└─┬ @nrwl/webpack 15.7.2
  ├─┬ file-loader 6.2.0
  │ └── loader-utils 2.0.4
  └── loader-utils 2.0.4
@nrwl/web 15.7.2
└─┬ @nrwl/rollup 15.7.2
  └─┬ rollup-plugin-postcss 4.0.2
    └─┬ postcss-modules 4.3.1
      └─┬ generic-names 4.0.0
        └── loader-utils 3.2.0
@nrwl/webpack 15.7.2
├─┬ file-loader 6.2.0
│ └── loader-utils 2.0.4
└── loader-utils 2.0.4
url-loader 4.1.1
└── loader-utils 2.0.4
```

**Comment by mcmxcdev** [comment]
Not sure if still relevant, but commenting to remove stale

**Comment by alexeymarunin** [comment]
Still relevant
```
warning "@nx/react > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0"
```

**Comment by jaysoo** [comment]
I have a PR to remove `url-loader`, but `file-loader` will need to wait until Nx 20 to remove due to a breaking change with existing SVGR behavior.

https://github.com/nrwl/nx/pull/22698

**Comment by jaysoo** [comment]
Will close this for now, but it's already scheduled for removal in Nx 20: https://github.com/nrwl/nx/blob/master/packages/next/plugins/with-nx.ts#L340
