### ISSUE TITLE
nx report :   > NX  Cannot set properties of undefined (setting 'name')

### ISSUE THREAD

**Issue by hoeferbe** [nrwl/nx#15186]
### Current Behavior

i was waiting for the fix #15052 and so i migrated to nx 15.8.0-beta.3 in my repo.
so `nx serve <nestjs-app>` and also `nx format` no longer works. but an `nx reset` works

`nx format`

 >  NX   Cannot set properties of undefined (setting 'name')
   
   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".

`nx reset`

 >  NX   Resetting the Nx workspace cache and stopping the Nx Daemon.

   This might take a few minutes.

 >  NX   Daemon Server - Stopped

 >  NX   Successfully reset the Nx workspace.

Even after `nx reset` there is the same error

### Expected Behavior

I expected at least one 'nx report' or 'format' should to work

### Steps to Reproduce

I don't have an example repo, mine is an organization repo.

I've just done a `nx migrate 15.8.0-beta.3` on my nx lastest repo

### Nx Report

```shell
`nx report`   

 >  NX   Cannot set properties of undefined (setting 'name')

   
   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
```

**Comment by hoeferbe** [comment]
`env |grep NX`
NX_DAEMON=false
NX_VERBOSE_LOGGING=true

`nx report `

 >  NX   Cannot set properties of undefined (setting 'name')
TypeError: Cannot set properties of undefined (setting 'name')
    at addNodes (/Users/hoeferbe/GIT/dua-monorepo/node_modules/nx/src/lock-file/npm-parser.js:53:26)
    at parseNpmLockfile (/Users/hoeferbe/GIT/dua-monorepo/node_modules/nx/src/lock-file/npm-parser.js:15:5)
    at parseLockFile (/Users/hoeferbe/GIT/dua-monorepo/node_modules/nx/src/lock-file/lock-file.js:76:50)
    at /Users/hoeferbe/GIT/dua-monorepo/node_modules/nx/src/project-graph/build-project-graph.js:63:62
    at Generator.next (<anonymous>)
    at /Users/hoeferbe/GIT/dua-monorepo/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/hoeferbe/GIT/dua-monorepo/node_modules/tslib/tslib.js:114:16)
    at buildProjectGraphUsingProjectFileMap (/Users/hoeferbe/GIT/dua-monorepo/node_modules/nx/src/project-graph/build-project-graph.js:36:20)
    at /Users/hoeferbe/GIT/dua-monorepo/node_modules/nx/src/project-graph/build-project-graph.js:31:23

deamon.log

> [NX Daemon Server] - 2023-02-23T20:23:07.744Z - There are 2 open connections. Reset inactivity timer.
[NX Daemon Server] - 2023-02-23T20:23:27.559Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-02-23T20:23:33.247Z - Closed a connection. Number of open connections: 0
[NX Daemon Server] - 2023-02-23T20:24:44.913Z - [WATCHER]: 0 file(s) created or restored, 2 file(s) modified, 0 file(s) deleted
[NX Daemon Server] - 2023-02-23T20:24:52.146Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-02-23T20:24:52.674Z - Time taken for 'hash changed files from watcher' 234.12508404254913ms
[NX Daemon Server] - 2023-02-23T20:24:57.948Z - Time taken for 'total execution time for createProjectGraph()' 5780.8405829668045ms
[NX Daemon Server] - 2023-02-23T20:26:27.171Z - [WATCHER]: Unsubscribed from changes within: /Users/hoeferbe/GIT/dua-monorepo (sources)
[NX Daemon Server] - 2023-02-23T20:26:27.177Z - [WATCHER]: Unsubscribed from changes within: /Users/hoeferbe/GIT/dua-monorepo (outputs)
[NX Daemon Server] - 2023-02-23T20:26:27.177Z - Server stopped because: "received process SIGTERM"

**Comment by FrozenPandaz** [comment]
Fixed in https://github.com/nrwl/nx/pull/15229
