### ISSUE TITLE
Ng commands are run outside of a workspace after migration to Nx 15.7.x

### ISSUE THREAD

**Issue by mlc-mlapis** [nrwl/nx#15195]
### Current Behavior

After correct migration from Nx 15.6.3 to Nx 15.7.0, 15.7.1, or 15.7.2 (with Angular projects based on version 15.1.6), all commands started with `ng ...` ended with an error: `This command is not available when running the Angular CLI outside a workspace.`

### Expected Behavior

The `ng` commands should run the same way as under Nx 15.6.3 without any errors.

### Steps to Reproduce

1. Create a new workspace under Nx 15.6.3 with a simple Angular `app` application.
2. Migrate the workspace to Nx 15.7.2 using `nx migrate 15.7.2`.
3. Run the command `ng serve app`.

### Nx Report

```shell
Node : 16.14.0
   OS   : win32 x64
   npm  : 8.3.1

   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/angular           : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/webpack           : 15.7.2
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   ngx-spinner : 15.0.1
```

### Additional Information

If the command `nx serve app` is used instead of `ng serve app`, it works correctly.

**Comment by AgentEnder** [comment]
This is purposeful. We are decoupling some things from the angular CLI, including removing this wrapper by default. You should be 100% safe to just use the Nx command directly, as previously thats all that was happening when you were running `ng` anyways.

**Comment by mlc-mlapis** [comment]
OK, and fine. I was just not sure that it was by purpose. Not mentioned as a breaking change.
