### ISSUE TITLE
Proper usage of @total-typescript/ts-reset within scope of an Nx monorepo

### ISSUE THREAD

**Issue by benpsnyder** [nrwl/nx#15196]
Several of our projects are built with the very latest Typescript enhancements and we run "bleeding edge", such as using TS `5.0.0-beta` (which works great). Typesafety is a priority for our team. I am also looking into using this new library https://github.com/total-typescript/ts-reset and appreciated the video the author posted: https://www.youtube.com/watch?v=bUts4HJJjV4

Could an Nx Core team member comment on `tsconfig.json` and if setting `module` to `NodeNext` or `Node16` is a bad idea? Perhaps this should just be scoped to backend apps such as NestJS implementations, and not be used for Angular apps?

Currently I am testing this in a shared domain library that is imported into both front-end and backend apps.

Thank you for the time taken to provide brief insight!

**Comment by benpsnyder** [comment]
FYI -- Angular seems to not like it.
![image](https://user-images.githubusercontent.com/707567/220977815-c8a3a655-9684-40c0-a2b1-1251d5e65add.png)

I backed off applying this monorepo-wide
![image](https://user-images.githubusercontent.com/707567/220978250-2520a3c8-d35e-4040-85a9-7a7408044b85.png)

And am focusing just on testing against isolated NestJS apps.
![image](https://user-images.githubusercontent.com/707567/220978403-f9fb2583-50de-45bf-bf25-8a96eb637c00.png)

TS builds are back to working.

Hoping to get some good commentary from the author (whom I asked to review this thread) so that any other people interested in using his library in the context of Nx monorepos can benefit.

thx

**Comment by benpsnyder** [comment]
Ahh! I love it. This is exactly what I wanted to see:
![image](https://user-images.githubusercontent.com/707567/220980287-3fc9e373-b833-48d4-a01a-1a014ea4c5d1.png)

I'm implementing via a `reset.d.ts` on an app-by-app basis, instead of using it down in the libs.
![image](https://user-images.githubusercontent.com/707567/220980694-7f7f534b-bfd2-4479-a5c4-29965c15b955.png)

**Comment by AgentEnder** [comment]
The usage seems fine, I've seen the lib floating around recently and like it myself too. That said, its still a new library that may or may not stick around, so we would be unlikely to add docs suggesting it or around its implementation currently.
