### ISSUE TITLE
"@angular/cli": "nrwl/fix-cli-build#release16" can't be installed behind proxy

### ISSUE THREAD

**Issue by dereklin** [nrwl/nx#152]
I can't install the nrwl version of angular cli due to git dependencies.  I am getting these errors:
```
npm ERR! git clone --template=/u1/cibuild/.npm/_git-remotes/_templates --mirror git@github.com:nrwl/fix-cli-build.git /u1/cibuild/.npm/_git-remotes/git-github-com-nrwl-fix-cli-build-git-557b9db3: Cloning into bare repository '/u1/cibuild/.npm/_git-remotes/git-github-com-nrwl-fix-cli-build-git-557b9db3'...

```

Are these versions only temporary and soon we will be able to use the regular versions like 1.6.0?

**Comment by nathagey** [comment]
I don't understand why this points to github, why wouldn't this be in NPM?

**Comment by vsavkin** [comment]
See here: https://github.com/nrwl/nx/wiki/FAQ

Once the CLI team fixes the issue, we will switch to getting `@angular/cli` from npm.

**Comment by dereklin** [comment]
@vsavkin file:.angular-cli.tgz is static right?  So for existing projects, we need to check the file at https://github.com/nrwl/nx/tree/master/packages/schematics/src/collection/application/files/__directory__ regularly and replace our existing file with the latest one, right?
