### ISSUE TITLE
Add generatePackageJson option to @nrwl/angular:webpack-server

### ISSUE THREAD

**Issue by Gkleinereva** [nrwl/nx#15206]
## Description
The `@nrwl/webpack:webpack` and `@nrwl/node:webpack` executors both allow for the `generatePackageJson` option in project.json.  This option generates a `package.json` file when the app/library is built that only includes those dependencies used by a production build of that app/library.   This `package.json` file can then be used to limit the dependencies installed on the server running the bundled application.

While such an option certainly doesn't make sense when bundling client applications, I'm curious if it could be added to the `@nrwl/angular:webapck-server` executer that is used to run Angular Universal servers.  If not, is there another way we could remove extraneous dependencies from our Angular Universal servers?

## Motivation
Angular universal servers are often very simple, so adding this option would drastically reduce the footprint of Angular Universal servers built with Nx.  

## Suggested Implementation
No idea whatsoever

## Alternate Implementations
⏫

**Comment by Coly010** [comment]
Hey @Gkleinereva 

I'd like to first confirm if this is necessary.

When you build your Angular Universal application, does it not bundle the dependencies it requires into the main.js file?

**Comment by Gkleinereva** [comment]
Hey @Coly010,

Oh my gosh you're right!  I copied my `./dist` folder to a random local folder, ran the copied `main.js`, and it just worked!  ...I had no idea these dependencies were getting bundled, and it never occurred to me that Nx/ng-universal might handle this for us.

Is this mentioned anywhere in the documentation (either Nx or Angular) that I missed?  If not, might be worth a shoutout.  

Otherwise, thank you very much for reviewing my issue  :)  And my servers thank you for a lot of reclaimed disk space  lol

**Comment by Coly010** [comment]
Hey! Glad that it worked out, and that you wont be running of disk space 😅

I'm not sure it is documented so i may create a follow up PR just to add a call out.

I'm going to close this issue now however, thanks for reaching out and I'm happy I was able to help :)
