### ISSUE TITLE
Dep graph should use path mappings

### ISSUE THREAD

**Issue by arnaudpourbaix** [nrwl/nx#1520]
# Prerequisites

Using version 8.1.2
I am using directories to organize my apps and libs.

Consider this simple project named `myapp` (package name)
Let's add 2 libraries:
```shell
ng generate @nrwl/angular:library lib1 --directory=client --publishable 
ng generate @nrwl/angular:library lib2 --directory=client --publishable 
```

tsconfig will looks like:
```json
    "paths": {
      "myapp/client/lib1": ["libs/client/lib1/src/index.ts"],
      "myapp/client/lib2": ["libs/client/lib2/src/index.ts"]
    }
```

lib1 package.json:
```json
{
  "name": "myapp/client-lib1"
}
```

angular.json:
```json
"projects": {
    "client-lib1": {},
    "client-lib2": {}
}
```

nx.json:
```json
"projects": {
    "client-lib1": {},
    "client-lib2": {}
}
```

At this point, you can create a dependancy between lib1 and lib2 (by using some imports) and dep graph will be good.

But this configuration doesn't work for me because there is a difference between package's name and path mapping: `myapp/client-lib1` vs `myapp/client/lib1`.
This a very small difference, right ? But this leads to a particular issue !

I can import my lib1 everywhere within my monorepo using the path `myapp/client/lib1`.
```typescript
import { TestService } from 'myapp/client/lib1';
```

But this library is also publishable and will be used by other projects. There, consumers would expect using package name:
```typescript
import { TestService } from 'myapp/client-lib1';
```

So, I changed path mapping, thinking it was just a slight modification without any negative impact.
Updated tsconfig:
tsconfig will looks like:
```json
    "paths": {
      "myapp/client-lib1": ["libs/client/lib1/src/index.ts"],
      "myapp/client-lib2": ["libs/client/lib2/src/index.ts"]
    }
```

In fact, it breaks nx dependancies. Despite the fact that everything seems well-configured, it just doesn't work anymore.

In my previous attempts, I wasn't using folders to organize my work.
It was something like:
```shell
ng generate @nrwl/angular:library client-lib1 --publishable 
ng generate @nrwl/angular:library client-lib2 --publishable 
```
It was working fine, but a less convenient folder structure.

**Comment by christianacca** [comment]
Not sure if this is related or another issue that I'm experiencing...

I have one lib that has a different npm scope compared to the other libraries in the same repo (in the json below it's the one named '@mri-platform/angular-wfe-proxy-oidc')

```json
    "paths": {
      "@mri-ag/admin-applications": ["libs/admin-applications/src/index.ts"],
      "@mri-ag/admin-core": ["libs/admin-core/src/index.ts"],
      "@mri-ag/admin-common-ui": ["libs/admin-common-ui/src/index.ts"],
      "@mri-ag/admin-shell": ["libs/admin-shell/src/index.ts"],
      "@mri-platform/angular-wfe-proxy-oidc": ["libs/angular-wfe-proxy-oidc/src/index.ts"]
    }
```

The graph produced does not include/discover the dependencies to this lib. However, if I change the npm scope for this library to be the same as all the other libs then dependencies are graphed as expected.

See images below for what this graph looks like exactly for me.

## Current graph

![image](https://user-images.githubusercontent.com/886590/73576466-6cc48380-4472-11ea-9c41-d1d467ae7b70.png)


## The expected graph 

once I change the npm scope to be the same for all libs I see this:

![image](https://user-images.githubusercontent.com/886590/73576347-2838e800-4472-11ea-8814-872e4693fac9.png)

**Comment by FrozenPandaz** [comment]
This issue should be fixed now as of v9. We are able to detect dependencies that resolved via path mappings. Please try with the latest version. Also, if possible, please share a repo that exhibits the issue.
