### ISSUE TITLE
Serverless (via AWS SAM) support?

### ISSUE THREAD

**Issue by studds** [nrwl/nx#1523]
Hello there

Love nx, very brilliant.

We're a serverless shop, using [AWS SAM ](https://aws.amazon.com/serverless/sam/). Would you consider a PR adding schematics for serverless? Or is it better to do it as an independent lib?

Cheers

Daniel

**Comment by FrozenPandaz** [comment]
#1, I think that would be an amazing tool.

I think it would be better if it is an independent library for now. I'm not sure if we would be able to maintain it well at the moment. If it works well, we'd love to recommend. 👍 We can help you make it happen.

@vsavkin What do you think?

**Comment by studds** [comment]
Thanks @FrozenPandaz :-)

I've made a start with this here: https://github.com/studds/nx-sam

Feedback would be very welcome :-) I'm starting with the builder first, so far just building on top of the nx node builder. I'll need to add new builders to run the package / deploy steps. Then the schematics. I assume that's a sensible way to approach it?

A couple of questions:

- Is it possible to export the `run` function from https://github.com/nrwl/nx/blob/4bf61ed695e394e13770e487f106538ec4f20265/packages/node/src/builders/build/build.impl.ts so that I can reuse it rather than rewriting it?
- My existing build has some codegen, generating ts validation functions from typescript interfaces. And / or hints on how best to approach this as a ng builder? Any prior art you can point me to?

**Comment by vsavkin** [comment]
Thank you for your work. 

Exporting the run function is an interesting idea. @FrozenPandaz do you know if there is a way to invoke a builder without doing it? Similar to externalSchematic?

**Comment by alfaproject** [comment]
Isn't it what the e2e task does? It builds another target

**Comment by studds** [comment]
@vsavkin @alfaproject quick update, tried to use `context.scheduleBuilder` but it fails because `context.target.project` is undefined at: 

https://github.com/nrwl/nx/blob/e51c7a4069874d7da3f876cf3a33610f38d9649c/packages/node/src/builders/build/build.impl.ts#L80

I assume `scheduleTarget` would work, but that would mean adding an additional target to angular.json, which might not be so bad in the scheme of things... but it would be kinda nice to be able to 'extend' the existing builder. This seems to be what the angular-cli builders do (or at least enable): https://github.com/angular/angular-cli/blob/8e97df38889b201aebf361ce7e8e07673411cb31/packages/angular_devkit/build_angular/src/browser/index.ts#L170 (I think I recall coming across a clear example where the full builder was reused in the angular source, but I can seem to find it now.)

**Comment by FrozenPandaz** [comment]
Fantastic work @studds!

`scheduleBuilder` should be the way to go. `@nrwl/node:build` should consider the fact that target is optional. We use it in the following places:

1. https://github.com/nrwl/nx/blob/4bf61ed695e394e13770e487f106538ec4f20265/packages/node/src/builders/build/build.impl.ts#L80
  a. It's a bit awkward but we can accept a `sourceRoot` option instead of using the `context.target` to get it.
2. https://github.com/nrwl/nx/blob/4bf61ed695e394e13770e487f106538ec4f20265/packages/node/src/builders/build/build.impl.ts#L44
  a. This one is simple, we can send `undefined`

I do wish that the context would be inherited... I'll reach out to the Angular CLI team.

**Comment by studds** [comment]
@FrozenPandaz thanks for the feedback. For now, I've copied and pasted the node build.impl.ts to my project, in anticipation of being able to use `scheduleBuilder` down the track. By the by, any reason this project doesn't use `strictNullChecks`, which would've made these issues apparent immediately?

I'd offer to do a PR for the changes you've outlined, but I'm guessing there would also need to be a migration done, and I haven't learnt that part yet. I've very limited time to work on this builder at all, over my breakfast :-)

**Comment by studds** [comment]
I've published a rough version as https://www.npmjs.com/package/@nx-aws/sam with builders for building, packaging, and deploying. 

Note the lack of a readme :-) Early days.

**Comment by wickstargazer** [comment]
Hi i have published a simple version to use with serverless framework...it works with the angular only currently... 
https://www.npmjs.com/package/@flowaccount/nx-serverless

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by ajhool** [comment]
In the ínterim, can aws sam (or cloudformation templates) be manually integrated into the nx deployment process?

**Comment by studds** [comment]
It's possible to manually integrate sam / cloudformation manually using https://nx.dev/angular/workspace/builders/run-commands-builder - I use run-commands quite a bit. That said, I wasn't satisfied with this myself, so I've invested a bit of time creating builders specifically for sam.

I'm using https://www.npmjs.com/package/@nx-aws/sam daily, and it's working well for my use case (which is quite complex - stacks in multiple regions, inter-dependencies, dev and prod deployments). There's also a [deploy builder for s3](https://www.npmjs.com/package/@nx-aws/sam). The documentation is not really up to snuff, though - something I've been meaning to find the time to work on. If you've got any questions, raise an issue here: https://github.com/studds/nx-aws/issues

**Comment by studds** [comment]
@ajhool definitely no additional burden. You can run the same webpack and Sam commands as you’re using now. So really, if you’ve only got a single stack and everything is working fine, then run-commands is probably all you need. 

A few of the main differences: @nx-was/sam inspects your cloudformation template and generates an appropriate webpack build, and saves a step there. It also has some smarts around parameter overrides when deploying. It makes managing nested stacks easier, by modelling them as separate nx projects. It also makes it easier to manage “soft” dependencies between stacks (as opposed to “hard” dependencies using exported stack outputs).

**Comment by bryantbiggs** [comment]
noooooooo!

**Comment by bryantbiggs** [comment]
I have worked on several serverless monorepos and I would love to use NX to manage. I think it would be great if there was at minimum an example of how one might setup a serverless/SAM monorepo using NX

**Comment by studds** [comment]
@bryantbiggs check out https://github.com/studds/nx-aws - it's rough in places but I use it on a few complex projects and it works great. Always happy to try to improve to handle new cases.

**Comment by bryantbiggs** [comment]
thanks for sharing @studds - I'm still a bit perplexed at how much configuration is required when trying to manage JS/TS based projects. I prefer using a monorepo to cut down on the amount of configurations and duplication but it seems like to work in a javascript/serverless based monorepo it takes a ton of custom configuration and manipulation to get it to work. Seems like you are probably better off just going polyrepo and copy+paste just to keep things simple and understandable.

**Comment by studds** [comment]
Hey @bryantbiggs you're not wrong, it can be a bit of a nightmare. I take the webpack approach, although with the `@nrwl/node:package` it's now very achievable to deploy a zipfile with node modules if that's what you prefer. `@nrwl/node:package` will inspect your app and pull out the runtime dependencies into an dist-specific `package.json`.

Having done both, I do find the mono repo approach much more efficient, and I am only able to use that approach thanks to nx. For me personally, the litmus test is: do I need to share code between apps (frontend and backend, multiple frontend apps, multiple backend apps, whatever)? As soon as I need to reach for `npm publish` it's a sign that I'm on my way to hell. (Due to the specific requirements of a recent project, I was forced to split one particular app into its own repo - now that I'm used to being able to update shared code on the fly, without any rebuilding relinking reinstalling or anything else, I don't know how I ever did it any other way.)
