### ISSUE TITLE
Angular - root jest.config.ts does nothing

### ISSUE THREAD

**Issue by TomONeill** [nrwl/nx#15249]
### Current Behavior

The root `jest.config.ts` file doesn't seem to do anything.

### Expected Behavior

That I can add custom options that get applied in all of my apps/libs, such as adding a custom reporter (like `jest-junit`)

### Steps to Reproduce

The file seems to be completely ignored when running a test:
`nx test <lib-name>`

Example:
```ts
// jest.config.ts
import { getJestProjects } from '@nrwl/jest';

export default {
  projects: getJestProjects().map(x => {
    throw new Error("this never happens");
    return x;
  })
}
```

Gives me no trouble at all.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.14.2
   OS   : win32 x64
   npm  : 9.5.1

   nx                      : 15.7.0
   @nrwl/jest              : 15.7.0
   @nrwl/linter            : 15.7.0
   @nrwl/workspace         : 15.7.0
   @nrwl/angular           : 15.7.0
   @nrwl/cli               : 15.7.0
   @nrwl/cypress           : 15.7.0
   @nrwl/devkit            : 15.7.0
   @nrwl/eslint-plugin-nx  : 15.7.0
   @nrwl/js                : 15.7.0
   @nrwl/storybook         : 15.7.0
   @nrwl/tao               : 15.7.0
   @nrwl/webpack           : 15.7.0
   typescript              : 4.8.4
   ---------------------------------------
   Community plugins:
   @storybook/angular : 6.5.16
```

### Failure Logs

```shell
none
```

**Comment by barbados-clemens** [comment]
to apply settings across all your projects you'll need to use the root `jest.preset.js`. the root level `jest.config.ts` just tells jest [what projects exist within the repo](https://jestjs.io/docs/configuration#projects-arraystring--projectconfig).

all of the generated project level `jest.config.ts` files extend the root preset, denoted by the setting
```ts
export default {
  preset: '../../jest.preset.js', // actual path will change on how nested a project is
  // other properties
}
```

**Comment by TomONeill** [comment]
Thanks for the explanation, @barbados-clemens, it works perfectly!
