### ISSUE TITLE
passing --prod to ng cli for nestjs - builds but INCLUDES sourcemaps

### ISSUE THREAD

**Issue by appsolutegeek** [nrwl/nx#1524]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

When running 

ng build --prod

fro a nestjs project, the sourcemaps are still produced.

--prod should mean they are not right ?

### Context

Please provide any relevant information about your setup:

- version of Nx latest
- version of Angular CLI 7
- `angular.json` configuration

```
   "architect": {
        "build": {
          "builder": "@nrwl/builders:node-build",
          "options": {
            "webpackConfig": "extra-webpack.config.js",
            "outputPath": "dist/apps/vault-api",
            "main": "apps/vault-api/src/main.ts",
            "tsConfig": "apps/vault-api/tsconfig.app.json",
            "assets": [
              "apps/vault-api/src/assets",
              "apps/vault-api/src/config",
              "apps/vault-api/src/database",
              {
                "glob": "**/graphql/schema/**/*.graphql",
                "input": "libs/",
                "output": "support-files/"
              }
            ]
          },
          "configurations": {
            "production": {
              "optimization": true,
              "extractLicenses": true,
              "inspect": false,
              "fileReplacements": [
                {
                  "replace": "apps/vault-api/src/environments/environment.ts",
                  "with": "apps/vault-api/src/environments/environment.prod.ts"
                }
              ]
            }
          }
        },
```

**A minimal reproduce scenario using allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

**Comment by FrozenPandaz** [comment]
I think `source-maps` are desirable for a production backend application so that you can trace errors to the source code location. I also think it's rare to have the application code for your backend be available. You can turn sourcemaps off if you'd like though.

**Comment by appsolutegeek** [comment]
Ok, yep. Agreed. Thanks for the confirmation. Closing this.
