### ISSUE TITLE
Can't upgrade angular workspace v14 to v15

### ISSUE THREAD

**Issue by webmandman** [nrwl/nx#15259]
### Current Behavior

When I try `npx nx migrate latest` or `npx nx migrate nx@14` or `npx nx migrate nx@14.8.6` my package.json is updated. However, `npm install` results in peer deps issues for all three versions. 

Issues:
Jest-angular complains about angular packages. 
rxjs complains about angular packages.

### Expected Behavior

I expect a clearer picture of how I should upgrade to v15

### GitHub Repo

https://github.com/webmandman/nxworkspace

### Steps to Reproduce

1. npm install --legacy-peer-deps
2. npx nx migrate nx@14.8.6
3. npm install

### Nx Report

```shell
Node : 16.15.1
   OS   : win32 x64
   npm  : 9.3.1

   nx : 14.2.4
   @nrwl/angular : 14.2.4
   @nrwl/cypress : 14.2.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.2.4
   @nrwl/eslint-plugin-nx : 14.2.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.2.4
   @nrwl/js : Not Found
   @nrwl/linter : 14.2.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.1.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.2.4
   @nrwl/web : Not Found
   @nrwl/workspace : 14.2.4
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
```

### Additional Information

Caleb Ukle in the nrwl slack community has been helping out and suggested I create an issue. 

I've spent atleast 5 hours diligently trying everything I could to find the correct upgrade path but I can't figure it out.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

There's a combination of a couple of things here:

- `rxjs` needs to be updated to a version equal to or greater than **7.5.0**, you can set it to **^7.8.0** (I'll add migration for that)
- Delete `package-lock.json` and `node_modules`. `npm` is doing some funky things and for some reason, it complains about what's installed even though it will be updated by new versions the migration applied to the `package.json`.

The last point can be seen in the error thrown:

```shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: mynxworkspace@0.0.0
npm ERR! Found: @angular-devkit/build-angular@14.0.7
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"15.2.1" from the root project
npm ERR!   peer @angular-devkit/build-angular@">=0.1002.4" from jest-preset-angular@11.1.2
npm ERR!   node_modules/jest-preset-angular
npm ERR!     dev jest-preset-angular@"13.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"15.2.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/compiler-cli@15.2.1
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   peer @angular/compiler-cli@"^15.0.0" from @angular-devkit/build-angular@15.2.1
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"15.2.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

You can see how it's complaining about `jest-preset-angular@11.1.2` requiring `@angular-devkit/build-angular@">=0.1002.4"` which results in what's currently installed `@angular-devkit/build-angular@14.0.7`. But `jest-preset-angular@11.1.2` is the currently installed version and the migration is updating the `package.json` to install `jest-preset-angular@13.0.0` which doesn't have such an issue.

The last issue is unfortunate and we can do little about it. Npm has some funky behaviors we can't influence, it's not too deterministic.

After doing the steps described above, when you run `nx migrate --run-migrations` if you come across the following error:

```
>  NX   Failed to run update-typescript-target from @nrwl/angular. This workspace is NOT up to date!

 >  NX   Cannot find module '@schematics/angular/utility/workspace-models'
```

Please run `nx migrate --run-migrations` again; it should solve itself. I'll spend some time on that one to see if we can avoid it to happen for others.
