### ISSUE TITLE
on migration angular.json not updated for proper schematics

### ISSUE THREAD

**Issue by jasedwards** [nrwl/nx#1525]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

When I generate a component the stylesheet should have extension of .scss

## Current Behavior

it has an extension of .css

I created a new workspace using npx and selected scss as my stylesheet.  the application generated fine with .scss files.  However, when I create a component using ``` ng g c mycomp``` it generates a .css file instead.  Here is the app part of angular.json file.

```
 "buildertest": {
      "projectType": "application",
      "schematics": {
        "@nrwl/workspace:component": {
          "style": "scss"
        }
      },
```

and my version info:

Angular CLI: 8.0.0                                                     
Node: 10.16.0                                                          
OS: win32 x64                                                          
Angular: 8.0.2                                                         
... animations, common, compiler, compiler-cli, core, forms            
... language-service, platform-browser, platform-browser-dynamic       
... router                                                             
                                                                       
Package                           Version                              
-----------------------------------------------------------            
@angular-devkit/architect         0.800.1                              
@angular-devkit/build-angular     0.800.4                              
@angular-devkit/build-optimizer   0.800.4                              
@angular-devkit/build-webpack     0.800.4                              
@angular-devkit/core              8.0.1                                
@angular-devkit/schematics        8.0.1                                
@angular/cli                      8.0.0                                
@ngtools/webpack                  8.0.4                                
@schematics/angular               8.0.1                                
@schematics/update                0.800.0                              
rxjs                              6.4.0                                
typescript                        3.4.5                                
webpack                           4.30.0

**Comment by ViceIce** [comment]
I thin `@nrwl/workspace:component` should be `@nrwl/angular:component`

**Comment by FrozenPandaz** [comment]
Thank you for reporting this issue.

Schematics should be migrated as well.

**Comment by FrozenPandaz** [comment]
Sorry, I was not able to find time to do this.

It's also been quite a while. To gauge the value of this migration could people comment if they're waiting for this change?

Someone from the community should be able to implement this as well.

**Comment by rarmatei** [comment]
As there hasn't been any activity on this for a while now, I'll close it for now. Please open a new issue or PR if this is still a problem.
