### ISSUE TITLE
nx-release is not working under windows with yarn2+

### ISSUE THREAD

**Issue by lislon** [nrwl/nx#15278]
### Current Behavior

`yarn nx-release` leads to error when using yarn2 (berry) and windows os

### Expected Behavior

yarn nx-release command should work

### GitHub Repo

https://github.com/nrwl/nx.git

### Steps to Reproduce

1. Make sure you are on yarn2+ verson: `yarn --version` should be `3.x`
2. Open `cmd.exe` 
3. Run `yarn nx-release`

### Nx Report

```shell
Node : 18.12.1
   OS   : win32 x64
   yarn : 3.4.1

   nx                      : 15.7.2
   lerna                   : 6.0.0
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/next              : 15.7.2
   @nrwl/react             : 15.7.2
   @nrwl/rollup            : 15.7.2
   @nrwl/storybook         : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/web               : 15.7.2
   @nrwl/webpack           : 15.7.2
   @nrwl/nx-cloud          : 15.2.0-beta.1
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @monodon/rust         : 1.0.0
   @ngrx/effects         : 15.3.0
   @ngrx/router-store    : 15.3.0
   @ngrx/store           : 15.3.0
   @nguniversal/builders : 15.2.0
   @storybook/angular    : 6.5.15
   rxjs                  : 6.6.7
   ---------------------------------------
   Local workspace plugins:
         @nrwl/react-native
         @nrwl/nx-plugin
         @nrwl/storybook
         @nrwl/workspace
         @nrwl/angular
         @nrwl/cypress
         @nrwl/esbuild
         @nrwl/express
         @nrwl/webpack
         @nrwl/linter
         @nrwl/rollup
         @nrwl/detox
         @nrwl/react
         @nrwl/expo
         @nrwl/jest
         @nrwl/nest
         @nrwl/next
         @nrwl/node
         @nrwl/vite
         @nrwl/web
         @nrwl/js
         nx
```

### Failure Logs

```shell
Error: Command failed: yarn local-registry clear
    at checkExecSyncError (node:child_process:871:11)
    at execSync (node:child_process:943:15)
    at C:\nx\scripts\nx-release.ts:29:13
    at Generator.next (<anonymous>)
    at C:\nx\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\nx\node_modules\tslib\tslib.js:114:16)
    at C:\nx\scripts\nx-release.ts:25:13
    at Object.<anonymous> (C:\nx\scripts\nx-release.ts:149:3)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module.m._compile (C:\nx\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (C:\nx\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12) {
  status: 1,
  signal: null,
  output: [ null, Buffer(0) [Uint8Array] [], Buffer(0) [Uint8Array] [] ],
  pid: 14684,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(0) [Uint8Array] []
}
```

### Additional Information

Yarn2 uses https://yarnpkg.com/package/@yarnpkg/shell as a portability layer to run scripts across of Windows, Linux, and macOS, but it doesn't support including other `.sh` scripts:

```
    "local-registry": "./scripts/local-registry.sh",
```

Do you think the proper way to fix it would be rewriting [local-registry.sh](https://github.com/nrwl/nx/blob/677cb98a793498bf3a309bdff3cd1e6ecf5611fe/scripts/local-registry.sh) from `.sh` to `.js`?

**Comment by AgentEnder** [comment]
For working on the Nx codebase on windows, the recommendation currently is to make use of WSL2. There are a few issues that we'd like to address, but it will be a little bit before we can address them.

**Comment by lislon** [comment]
@AgentEnder Do you think its something I can help with? If so maybe you can give me some directions / related issues you aware of. For example, I can try rewriting this `sh  into to `js`

**Comment by AgentEnder** [comment]
If you want to put a PR in for some improvements it would certainly be appreciated, I'd recommend .ts instead of .js, similar to the existing TS scripts.

**Comment by Den-dp** [comment]
> For working on the Nx codebase on windows, the recommendation currently is to make use of WSL2. There are a few issues that we'd like to address, but it will be a little bit before we can address them.

I hope the final solution will not require WSL2

**Comment by AgentEnder** [comment]
No, it won't. It works as is perfectly on WSL2, which is how I dev. I was referring to known issues on regular windows for the repo that I was commenting on.
