### ISSUE TITLE
nx.dev website is looking messy

### ISSUE THREAD

**Issue by wizardnet972** [nrwl/nx#15270]
### Current Behavior

<img width="1610" alt="image" src="https://user-images.githubusercontent.com/4997825/221399397-598a1a2b-19fa-4ba3-a296-1362f2cb8db3.png">

### Expected Behavior

...

### Steps to Reproduce

goto nx.dev

### Nx Report

```shell
chrome: Version 110.0.5481.100 (Official Build) (arm64)
edge
```

**Comment by elmpp** [comment]
Tested in multiple browsers

There are a bunch of console.logs in the console also

**Comment by wizardnet972** [comment]
Resolved.
