### ISSUE TITLE
Unknown jest option: '--findRelatedTests'

### ISSUE THREAD

**Issue by vinayakpatil** [nrwl/nx#1527]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior
findRelatedTests option should be available for jest

**Comment by FrozenPandaz** [comment]
This is a good first issue if somebody would like to work on it.

**Comment by BuckyMaler** [comment]
@FrozenPandaz I'd like to work on this. My team has an open issue to add testing to our pre-commit hook, so we'll likely make use of this option.

**Comment by LuukMoret** [comment]
I believe `--testLocationInResults` should also be available because `I'm getting Unknown option: '--testLocationInResults'` at the moment.

**Comment by Mayjest** [comment]
@LuukMoret Are you getting that from vscode-jest? Because that's where I'm seeing it. It appears to be a hard-coded option in that plugin as well, so enabling support in the jest builder is required to be able to use it.

**Comment by LuukMoret** [comment]
> @LuukMoret Are you getting that from vscode-jest? Because that's where I'm seeing it. It appears to be a hard-coded option in that plugin as well, so enabling support in the jest builder is required to be able to use it.

Yes I'm getting the error from vscode-jest and I am unable to use it now because jest builder does not know the `--testLocationInResults` option.
