### ISSUE TITLE
Vite - cannot import libs using tsconfig paths in vite.config.ts

### ISSUE THREAD

**Issue by danr-za** [nrwl/nx#15277]
### Current Behavior

When trying to import from a lib in the repo into `vite.config.ts` file, it fails to resolve this path.
e.g., the following will fail:
```ts
import { defaultSvgConfig } from '@myorg/build'

export default defineConfig({ ... })
```

Relative imports works, but requires disabling `enforce-module-boundaries` rule.

### Expected Behavior

Should allow importing from other project paths that are declared in `tsconfig.base.json`

### Steps to Reproduce

1. Create a repo
2. Add a React app with Vite config
3. Add a JS lib and export anything from it
4. Import the lib code into your `vite.config.ts` in React project
5. Run server/build

### Nx Report

```shell
Node : 16.17.0
   OS   : darwin arm64
   yarn : 3.4.1
   
   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/node              : 15.7.2
   @nrwl/nx-plugin         : 15.7.2
   @nrwl/react             : 15.7.2
   @nrwl/rollup            : 15.7.2
   @nrwl/storybook         : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/vite              : 15.7.2
   @nrwl/web               : 15.7.2
   @nrwl/webpack           : 15.7.2
   @nrwl/nx-cloud          : 15.0.3
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   nx-stylelint : 14.0.2
```

**Comment by mandarini** [comment]
Hi @danr-za ! Thanks for filing an issue! Just to check, are you using `vite-tsconfig-paths` plugin?

**Comment by danr-za** [comment]
Hey @mandarini , yes indeed.
It seems like an issue in the execution context rather than vite, but maybe I'm wrong.

**Comment by mandarini** [comment]
@danr-za I asked a question in the vite discord, just to see if they have any idea why this is happening! I also created [a repro here](https://github.com/mandarini/vite-paths).

**Comment by danr-za** [comment]
I think that you should register the TS paths on Nx executor level when you import/require it, like we do in Webpack no?
with `ts-node` register
