### ISSUE TITLE
Broken UI layout in Nx Dev documentation

### ISSUE THREAD

**Issue by wardvisual** [nrwl/nx#15271]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Perhaps the entire layout of the documentation is broken, but I came first at this link.
https://nx.dev/packages/nx/documents/generate

### Additional context or description

As of now, I noticed that the UI layout of the Nx Dev documentation is currently broken, making it difficult to read and navigate the documentation. Specifically, I have encountered issues with broken formatting and spacing, which makes it hard to understand and follow the content. I have tried accessing the documentation from multiple devices, but the same issues persist.

 
### Screenshots
![image](https://user-images.githubusercontent.com/64777371/221401132-b966f2b7-be66-416a-ad72-8ca8d477c76e.png)
![image](https://user-images.githubusercontent.com/64777371/221401197-27c68cd8-6e4a-4f8b-b46f-048a60fa4f61.png)
![image](https://user-images.githubusercontent.com/64777371/221401309-808675f9-f160-4c92-ba7b-6327997305c3.png)

**Comment by elmpp** [comment]
https://github.com/nrwl/nx/issues/15270

**Comment by ko22009** [comment]
If you want see content.
![image](https://user-images.githubusercontent.com/11016041/221404845-147f846e-f9b5-46dd-ad4e-ed07b8411b02.png)

**Comment by ko22009** [comment]
It's problem connected with big icons.

**Comment by ko22009** [comment]
It doesn't apply h-4, w-4 classes.
![image](https://user-images.githubusercontent.com/11016041/221404939-c899e571-91b9-4299-a6bb-2093583c56a0.png)

**Comment by romandott** [comment]
any updates on that issue?

**Comment by EthanSK** [comment]
LMAOOOOO WHAT IS THIS CHECK YOURSELF LOOOOOL

https://blog.hubspot.com/website/center-div-css#:~:text=With%20CSS%2C%20you%20can%20center,content%20and%20align%2Ditems%20properties.

**Comment by wardvisual** [comment]
This issue is resolved.
