### ISSUE TITLE
A lint rule for testing project configuration

### ISSUE THREAD

**Issue by alexandrzavalii** [nrwl/nx#15282]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Would be good if we could specify a list of all possible tags as a lint rule, and if a lib is using a tag which is not in that predefined list, lint would complain.

## Motivation
there is nothing that stops you from creating a misspelled tag name. Its easy to make mistakes.

**Comment by meeroslav** [comment]
Thank you for creating this request. We have a new plugin on our list that would lint the configuration files, but it currently has low priority.

We will address this in the upcoming months.

**Comment by alexandrzavalii** [comment]
@meeroslav Nice, thats great to hear, is there a link to the feature so I can track?

**Comment by meeroslav** [comment]
Not yet, it's currently on our internal board.
