### ISSUE TITLE
prettier version should upgrade to 1.9

### ISSUE THREAD

**Issue by chgc** [nrwl/nx#153]
I am not sure if install prettier as devDependences will effect VSCode Prettier Extension. VSCode keeps complaining about prettier `proseWrap` options should be boolean not string.

However, in Prettier version 1.9. they change `proseWrap` option.
> [WARNING] proseWrap with boolean value is deprecated, use "always", "never" or "preserve" instead.

Currently, prettier package version in Nx template is 1.8.6. I have to manually upgrade it to 1.9 to solve the problem as I described before.

Reference: [Prettier package 1.9 release note](https://github.com/prettier/prettier/releases/tag/1.9.0)

**Comment by vsavkin** [comment]
@chgc could you submit a PR?
