### ISSUE TITLE
nx 15.7.2 is not generating default scripts in package.json

### ISSUE THREAD

**Issue by iKrishnaSahu** [nrwl/nx#15313]
### Current Behavior

nx 15.7.2 is not generating default scripts in package.json

default scripts (which was getting added in pacakge.json in some old nx version) - 

1. "start": "nx serve",
2.  "build": "nx build",
3. "test": "nx test"

If this change is intentional, what is the reason behind this change? 

Is there any alternate way to generate those scripts?

Generated package.json -
```
{
  "name": "ws-nx1572",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
  },
  "private": true,
  "dependencies": {
  },
  "devDependencies": {
    "nx": "15.7.2",
    "@nrwl/workspace": "15.7.2",
    "typescript": "~4.8.2",
    "prettier": "^2.6.2"
  }
}

```

### Expected Behavior

It should generate default scripts

### Steps to Reproduce

1. run `npx create-nx-workspace@15.7.2`
2. Once step 1 is done, check pacakge.json's script section

### Nx Report

```shell
C:\Projects\projects\workspaces2\5.10\ws-nx1572>nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.19.0
   OS   : win32 x64
   npm  : 8.19.3
   
   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/angular           : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/webpack           : 15.7.2
   typescript              : 4.8.4
   ---------------------------------------
   Community plugins:
   @****/shell      : 5.10.0-beta4
   @****/schematics : 5.10.0-beta2
```

**Comment by TomONeill** [comment]
Instead of only posting the reproduction, can you also include the generated `package.json` `scripts` portion?

**Comment by AgentEnder** [comment]
We don't generate those scripts for certain presets, as we now support root-projects and they can lead to certain footguns. Also, its an attempt at seeming less daunting as a tool, so we generate less by default for new workspaces.

As far as a way of getting those scripts back, you can always do that part manually. If your org has adopted a pattern that leads to creating several Nx repos for whatever reason, you can always create a custom preset generator and do it in there as well.

For now, the following presets would still include them:
- Angular Standalone
- React Standalone
- Node Server
