### ISSUE TITLE
withModuleFederation Library type 

### ISSUE THREAD

**Issue by infoxicator** [nrwl/nx#15316]
### Current Behavior

the `withModuleFederation` plugin doesn't allow the library type to be configured using the `module-federation.config.js` file because the value is hardcoded here https://github.com/nrwl/nx/blob/master/packages/react/src/module-federation/with-module-federation.ts#L55

I will be raising a PR shortly to fix it

### Expected Behavior

Whe you pass a library type to the `module-federation.config.js` the value should be reflected in the module federation plugin configuration

### Steps to Reproduce

1. Overrdie the library type here 
```
module.exports = {
  name: 'test-app',
  // bug with NX this is not being passed here https://github.com/nrwl/nx/blob/master/packages/react/src/module-federation/with-module-federation.ts#L55
  library: { type: 'var', name: 'test-app' },
  exposes: {
    './Test': './src/index',
  },
  // remotes: [],
};
```

the value is not updated 

### Nx Report

```shell
Node : 16.14.2
   OS   : darwin x64
   npm  : 8.5.0
   
   nx : 14.8.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.1.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.1.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.13
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.1.1
   @nrwl/js : 15.1.1
   @nrwl/linter : 15.1.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.0.13
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.1.1
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.1.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.1.1
   @nrwl/web : 15.1.1
   @nrwl/webpack : 15.1.1
   @nrwl/workspace : 15.0.13
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by jaysoo** [comment]
Thanks for the reportg @infoxicator Let me know if you get the PR up, or if dont' mind we can make this change as well.

**Comment by infoxicator** [comment]
> Thanks for the reportg @infoxicator Let me know if you get the PR up, or if dont' mind we can make this change as well.

Here is the PR https://github.com/nrwl/nx/pull/15385 👍

**Comment by infoxicator** [comment]
@jaysoo PR merged and closed 👏 do you know when is it released so I can use it in my project?

thanks
