### ISSUE TITLE
@nrwl/nx v8.2.0 not in the NPM registry

### ISSUE THREAD

**Issue by jerryorta-dev** [nrwl/nx#1532]
The latest @nrwl/nx package I see in the npm is 7.8.7. Are the stable 8.x versions supposed to be published in NPM yet?

**Comment by FrozenPandaz** [comment]
This is intentional. The functionality within `@nrwl/nx`, DataPersistence, has been moved to `@nrwl/angular` and is deprecated after `7.8.7`. There is a migration for `8.0.0` that handles the migration.
