### ISSUE TITLE
Expo v48 support

### ISSUE THREAD

**Issue by robertn702** [nrwl/nx#15333]
## Description
[Expo v48](https://blog.expo.dev/expo-sdk-48-ccb8302e231) support

## Motivation
[Expo v48](https://blog.expo.dev/expo-sdk-48-ccb8302e231) includes several updates including upgrading [react-native](https://github.com/facebook/react-native) from [0.70.5](https://github.com/facebook/react-native/releases/tag/v0.70.5) to [0.71.3](https://github.com/facebook/react-native/releases/tag/v0.71.3)

## Suggested Implementation
Bump version of expo and its dependencies

## Alternate Implementations
N/A

**Comment by xiongemi** [comment]
i will try to work on it this week if I have time

**Comment by xiongemi** [comment]
i submit a pr to update expo: https://github.com/nrwl/nx/pull/15400
