### ISSUE TITLE
Azure CI Pipeline throwing error not received locally

### ISSUE THREAD

**Issue by 72gm** [nrwl/nx#15347]
### Current Behavior

When running NX in my Azure pipeline I get the following error 

    NX Expected ":" or blank space but "\n" found.

Everything is fine locally, no problems

Seems to occur when I do any of the following build, lint, format:check

Full output:

 

       Starting: NX checks
    ==============================================================================
    Task         : Command line
    Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
    Version      : 2.212.0
    Author       : Microsoft Corporation
    Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
    ==============================================================================
    Generating script.
    ========================== Starting Command Output ===========================
    "C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\62006c3f-dbd7-4eed-9fdc-7e64db8c1da7.cmd""
    
     >  NX   Expected ":" or blank space but "\n" found.
    
    
    ##[error]Cmd.exe exited with code '1'.
    Finishing: NX checks

### Expected Behavior

That this error doesn't happen.

I have deleted node modules and reinstalled but still works fine locally

### Steps to Reproduce

Not sure how you would reproduce

### Nx Report

```shell
Node : 16.18.0
   OS   : win32 x64
   yarn : 1.22.19

   nx : 15.4.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.5
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.5
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.5
   @nrwl/js : 15.4.5
   @nrwl/linter : 15.4.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.5
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.5
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.4.5
   @nrwl/web : 15.4.5
   @nrwl/webpack : 15.4.5
   @nrwl/workspace : 15.4.5
   @nrwl/vite : 15.4.5
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by 72gm** [comment]
I ended up deleting my yarn.lock file which caused a number of other issues that I had to fix .... 

I had no choice as I'd already spent best part of day trying to work out where the original issue was... this error really should be identifying where the issue is as it could be anywhere

**Comment by Coly010** [comment]
Was the issue with the lock file then? Do you have any way for us to reproduce this issue?

**Comment by 72gm** [comment]
highly unlikely given we run npm in CI (as it's more complicated to get yarn working in Azure)... was just a last resort
