### ISSUE TITLE
@nrwl/rollup:rollup cannot correctly read rollupConfig of type string

### ISSUE THREAD

**Issue by WAHsss** [nrwl/nx#15346]
### Current Behavior

[The document](https://nx.dev/packages/rollup/executors/rollup#rollupconfig) says that `oneOf [Array<string>, string]` is supported, but [the code](https://github.com/nrwl/nx/blob/master/packages/rollup/src/executors/rollup/rollup.impl.ts#:~:text=options.rollupConfig.reduce) only supports`Array<string>`, which is very confusing.

my `project.json` is not worked:
```
{
...,
"targets": {
    "build": {
      ...,
        "rollupConfig": "rollup.config.js"
      }
    },
}
```
but it's worked when I  change config `"rollupConfig": "rollup.config.js"` to  `"rollupConfig": ["rollup.config.js"]` ;

### Expected Behavior

Support string type, Keep in sync with docs

Current implementation:
```typescript
return options.rollupConfig.reduce((currentConfig, plugin) => {
      return require(plugin)(currentConfig, options);
    }, rollupConfig);
```

Mybe wen can support string type, just add some code
```diff
+  if(typeof options.rollupConfig === 'string'){
+    return require(options.rollupConfig)(currentConfig,options)
+  }
return options.rollupConfig.reduce((currentConfig, plugin) => {
      return require(plugin)(currentConfig, options);
    }, rollupConfig);
```

### Steps to Reproduce

1. `yarn nx generate @nrwl/js:library myproject --unitTestRunner=none --bundler=rollup --no-interactive --dry-run`
2.   Initialize `rollup.config.js` in the root
```js
module.exports = (config) => {
   console.log(config)
    return config
}

```
3.  add code to `myproject/project.json`, seems like
```
{
"targets": {
    "build": {
        "rollupConfig":"rollup.config.js"
      }
    },
}
``` 
4. `yarn nx build myproject`
Then, we can not see `config` output in the console

### Nx Report

```shell
Node : 18.14.1
   OS   : darwin x64
   yarn : 1.22.19
   
   nx                      : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/react             : 15.7.2
   @nrwl/rollup            : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/nx-cloud          : 15.1.1
   typescript              : 4.8.4
```

**Comment by rmjwilbur** [comment]
@WAHsss ran across your issue while looking for something else. The string option works for me, but I had to add the path:
`"rollupConfig": "libs/my-lib/customRollupConfig.ts",`
