### ISSUE TITLE
affected:lint --file option

### ISSUE THREAD

**Issue by JochenDiekenbrock** [nrwl/nx#1535]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

https://nx.dev/api/npmscripts/affected-lint mentions a --file option, but `yarn affected:lint --all --file=.vis/output.json` results in the message `Unknown option: '--file` for each app.

`yarn affected:lint --help` does not show this option.

Is this a bug or a mistage in https://nx.dev/api/npmscripts/affected-lint?

How would I use yarn affected:lint to create either one checkstyle format file for the complete workspace or one checkstyle format file for each app?

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. setup a new workspace
2. call `yarn affected:lint --help`

### Context

Please provide any relevant information about your setup:

- version of Nx used: 8.2.0
- version of Angular CLI used: Angular CLI: 8.0.0
- `angular.json` configuration
- version of Angular DevKit used: 8.0.1

**Comment by FrozenPandaz** [comment]
This seems like a bug in our documentation generation. @bcabanes can you take a look please?
