### ISSUE TITLE
NX Migrate Not working

### ISSUE THREAD

**Issue by 72gm** [nrwl/nx#15352]
### Current Behavior

As per the screen shot... I am on 15.4.5 and I run nx migrate and it tells me nothing to migrate even though the lastest version is 15.8.1

somehow, after deleting mu yarn.lock file and reinstalling I seem to be on version 15.8.1 of nx and 15.4.5 of everything else.. so nothing works as I need to upgrade all the other versions

![image](https://user-images.githubusercontent.com/12847881/222152175-5fb15e6b-28d5-4d1c-99da-99c4e906eea7.png)

### Expected Behavior

It would migrate successfully

### Steps to Reproduce

1.
no idea

### Nx Report

```shell
Node : 16.18.0
   OS   : win32 x64
   yarn : 1.22.19

   nx                      : 15.8.1
   @nrwl/js                : 15.4.5
   @nrwl/jest              : 15.4.5
   @nrwl/linter            : 15.4.5
   @nrwl/workspace         : 15.4.5
   @nrwl/cli               : 15.8.1
   @nrwl/cypress           : 15.4.5
   @nrwl/devkit            : 15.4.5
   @nrwl/eslint-plugin-nx  : 15.4.5
   @nrwl/react             : 15.4.5
   @nrwl/rollup            : 15.4.5
   @nrwl/storybook         : 15.4.5
   @nrwl/tao               : 15.8.1
   @nrwl/vite              : 15.4.5
   @nrwl/web               : 15.4.5
   @nrwl/webpack           : 15.4.5
   typescript              : 4.8.4
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/js@15.4.5
     - @nrwl/jest@15.4.5
     - @nrwl/linter@15.4.5
     - @nrwl/workspace@15.4.5
     - @nrwl/cypress@15.4.5
     - @nrwl/devkit@15.4.5
     - @nrwl/eslint-plugin-nx@15.4.5
     - @nrwl/react@15.4.5
     - @nrwl/rollup@15.4.5
     - @nrwl/storybook@15.4.5
     - @nrwl/vite@15.4.5
     - @nrwl/web@15.4.5
     - @nrwl/webpack@15.4.5

   To fix this, run `nx migrate nx@15.8.1`
```

**Comment by 72gm** [comment]
I update my package json manually.. but this caused problems with the workspace.json no longer being used so had to run 

`nx g @nrwl/workspace:fix-configuration
`
then webpack was missing so

`yarn add @nrwl/webpack
`

**Comment by 72gm** [comment]
i've just reverted everything back 15.4.5 as I need to get on with my day job... 

3 times I've tried to migrate from 15.4.5 (last pre webpack 5 version) and 3 times it just hasn't worked

- Is it supposed to work without issues? 
- IS there guidance? 
- Are we supposed to get the "breakinG CHANGE: webpack < 5 used to include polyfills for node.js core modules by default." error or should this be dealt with by the migration process
- 15.8.1 seems to have done away with workspace.json - again is there guidance on this?
-

**Comment by AgentEnder** [comment]
- Yes... It should work. 
- There is some guidance for migrate here: https://nx.dev/core-features/automate-updating-dependencies
- The migrations do not add polyfills by default, as your app may or may not need them. If it does, add them.
- Yes, there is guidance: https://nx.dev/deprecated/workspace-json
