### ISSUE TITLE
NX Console  "View full details" link is broken

### ISSUE THREAD

**Issue by joeldbirch** [nrwl/nx#15369]
### Documentation issue
<img width="1453" alt="Screen Shot 2023-03-02 at 1 44 42 pm" src="https://user-images.githubusercontent.com/75602/222317700-08ca3483-2631-404e-892d-cd5b40c879ee.png">

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/packages/nx-cloud/generators/init

### Additional context or description

NX Console > Generate & Run Target > generate > "View full details" link is broken

**Comment by isaacplmann** [comment]
This generator is actually an internal generator that shouldn't be run directly.  We need to mark it as hidden.  You should run `nx connect-to-nx-cloud` to set up Nx cloud for your repo.

**Comment by StalkAltan** [comment]
Thanks for reporting this. This generator will be hidden from nx-console from the next release of @nrwl/nx-cloud onward (likely 15.2)
