### ISSUE TITLE
15.8.1-3: .nxignore not respected in native hasher

### ISSUE THREAD

**Issue by atsjo** [nrwl/nx#15377]
### Current Behavior

folder in .nxignore doesn't excludes deps referenced in folder

### Expected Behavior

folder in .nxignore excludes deps referenced in folder

### Steps to Reproduce

exclude a folder in a project, which is not part of the source-code for the project (I have a test folder...). When using nx graph you can se the deps are included anyways. This worked in 15.7.2...

### Nx Report

```shell
Node : 18.14.2
   OS   : win32 x64
   yarn : 4.0.0-rc.39

   nx                      : 15.8.1
   @nrwl/js                : 15.8.1
   @nrwl/jest              : 15.8.1
   @nrwl/linter            : 15.8.1
   @nrwl/workspace         : 15.8.1
   @nrwl/angular           : 15.8.1
   @nrwl/cli               : 15.8.1
   @nrwl/cypress           : 15.8.1
   @nrwl/devkit            : 15.8.1
   @nrwl/esbuild           : 15.8.1
   @nrwl/eslint-plugin-nx  : 15.8.1
   @nrwl/tao               : 15.8.1
   @nrwl/webpack           : 15.8.1
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngrx/component       : 15.3.0
   @ngrx/component-store : 15.3.0
   angular-calendar      : 0.31.0
```

### Additional Information

I have a workspace with client and server side code, and use esbuild to bundle functions for firebase. As of release 15.8, the esbuild executor adds all dependencies from the root/workspace package.json to the server side functions bundle... But I can now see this is due to .nxignore not being respected as before, it also shows up in via nx grapch...

**Comment by atsjo** [comment]
seems that .nxignore is not respected for these dependencies... I have a folder with some tests in the server side project which is excluded via nxignore... I can se the problem via nx graph... will try to get nxignore working again...

**Comment by atsjo** [comment]
I have verified that this is related to the change of default hasher to native... opting out of this by setting NX_NON_NATIVE_HASHER=true resolves the problem

**Comment by atsjo** [comment]
same for 15.8.2

**Comment by Cammisuli** [comment]
Whats in your `.nxignore` file?

**Comment by atsjo** [comment]
# firestore-tests folder includes files directly from shared-web, but is only used for testing 
apps/firebase/firestore-test/

**Comment by atsjo** [comment]
btw, I also think the native hasher causes more issues when upgrading... I get errors like this when running yarn when upgrading from 15.8.1  to 15.8.2. This is probably due to nx console locking the old version.

```
Error: EPERM: operation not permitted, unlink 'C:\Users\atles\source\repos\teve-no\task4s\node_modules\@nrwl\nx-win32-x64-msvc\nx.win32-x64-msvc.node'
```

It works when disabling the native hasher... I had several issues with running the daemon process, whick I now have disabled via nx.json... It would be nice to be able to disable the native hasher via the workspace as well.... putting the variable in .env in the workspace does not work, I hade to add it to my account...

**Comment by Cammisuli** [comment]
interesting.. let me investigate this further.

**Comment by Cammisuli** [comment]
I got it reproducing with a test case on Windows. I'm working on a fix.

**Comment by atsjo** [comment]
great! Just tested with 15.8.3, and I can se that the fix is not out yet...

**Comment by Cammisuli** [comment]
> btw, I also think the native hasher causes more issues when upgrading... I get errors like this when running yarn when upgrading from 15.8.1 to 15.8.2. This is probably due to nx console locking the old version.
> 
> ```
> Error: EPERM: operation not permitted, unlink 'C:\Users\atles\source\repos\teve-no\task4s\node_modules\@nrwl\nx-win32-x64-msvc\nx.win32-x64-msvc.node'
> ```
> 
> It works when disabling the native hasher... I had several issues with running the daemon process, whick I now have disabled via nx.json... It would be nice to be able to disable the native hasher via the workspace as well.... putting the variable in .env in the workspace does not work, I had to add it to my account...

I actually got this too, and it looks like its because the daemon still has a handle on the file. I'll have to figure out a way to release that handle. That will come in a separate PR. 

A fix for the main issue regarding .nxignore is coming soon.
