### ISSUE TITLE
Create react app support

### ISSUE THREAD

**Issue by AnatoleLucet** [nrwl/nx#1537]
Hello, this is a following to this issue : #1510 

So apparently I am not the only one to be interested about a [create-react-app](https://github.com/facebook/create-react-app) support. I have created this issue to dive in more details and see if someone has some ideas on how to integrate create-react-app to nx.

Ideas to implement it : 
1. I think it could be an option in the `angular.json`.
2. A flag in the angular cli's generate command, for exemple : `ng g @nrwl/react:application my-app --create-react-app`.
3. A nx package like : `ng g @nrwl/create-react-app`.

I don't know which of these proposal could be the more viable, and somebody probably has a better idea (please share it).

Anyway, CRA need to be booted up with node. For exemple if you try to eject an app you can see in the `scripts/` folder some node files that basically permit you to start, build, test, and more.. the app. Here is for example the [`start` script](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/scripts/start.js) that start the app on a dev server.

CRA create an app via [this script](https://github.com/facebook/create-react-app/blob/master/packages/create-react-app/createReactApp.js) which can be executed via `npx`, `yarn create`, and more... Maybe we could use this script to generate up the app ?

Well there is a lot of things to talk about. This is just a little entry to the subject.
If you have any idea(s) / suggestion(s) please comment it 😉

**Comment by jaysoo** [comment]
@AnatoleLucet 

I think CRA's features are a subset of what Nx+React provides. We've improved React support a lot in the past little while (eslint support, babel support, etc.).

I don't think it makes sense to directly integrate with CRA, but if there are any features there that's missing, please open new issues outlining what you're looking for. :)

For example, CRA's `yarn start` will prompt to switch port when the default one is taken--we don't do that.

Thanks!
