### ISSUE TITLE
ESLint Imports of lazy-loaded libraries are forbidden NX 15.8

### ISSUE THREAD

**Issue by MarcusElevait** [nrwl/nx#15372]
### Current Behavior

We have a routes.ts where we place our route configuration like this:
``` typescript
import { AuthGuard } from '@aicosy/angular/auth-guard';
import { BackendGuard } from '@aicosy/angular/backend';
import { ForceLeaveConfirmationGuard } from '@aicosy/angular/force-leave-confirmation-guard';
import { DOCUMENTS_PATH } from '@aicosy/shared/primitive-constants';
import { Routes } from '@angular/router';
import { FormsEditorShellComponent } from '@elevait/forms-editor';
import { CustomTitleResolver } from './resolver/custom-title.resolver';

export const COLLECTIONS_ROUTES: Routes = [
    {
        path: `:collectionUuid/${DOCUMENTS_PATH}/:documentPageUuid/forms-editor`,
        loadChildren: () => import('@elevait/forms-editor').then(module => module.FormsEditorModule),
        component: FormsEditorShellComponent,
        canActivate: [AuthGuard, BackendGuard],
        canDeactivate: [ForceLeaveConfirmationGuard],
        title: CustomTitleResolver,
    },
];
```

After migration to nx 15.8.1 we're now getting a lint error for the FormsEditorShellComponent that says '_Imports of lazy-loaded libraries are forbidden_'.

### Expected Behavior

I don't expect any error here, because i see no other way of defining the entry component for this route here.

### Steps to Reproduce

1. Create a library with a module and a component.
2. Add a routes file like it is above defined and place the module and the component there
3. Add an app and use the routes in there
4. Run lint for this app

### Nx Report

```shell
Node : 18.12.0
   OS   : linux x64
   npm  : 8.19.2
   
   nx                      : 15.8.1
   @nrwl/js                : 15.8.1
   @nrwl/jest              : 15.8.1
   @nrwl/linter            : 15.8.1
   @nrwl/workspace         : 15.8.1
   @nrwl/angular           : 15.8.1
   @nrwl/cli               : 15.8.1
   @nrwl/cypress           : 15.8.1
   @nrwl/devkit            : 15.8.1
   @nrwl/eslint-plugin-nx  : 15.8.1
   @nrwl/nest              : 15.8.1
   @nrwl/node              : 15.8.1
   @nrwl/nx-plugin         : 15.8.1
   @nrwl/tao               : 15.8.1
   @nrwl/webpack           : 15.8.1
   @nrwl/nx-cloud          : 15.0.3
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @datorama/akita       : 2.2.4
   @ngrx/component-store : 15.3.0
   @ngrx/effects         : 15.3.0
   @ngrx/entity          : 15.3.0
   @ngrx/router-store    : 15.3.0
   @ngrx/store           : 15.3.0
   @rx-angular/cdk       : 1.0.0
   @rx-angular/template  : 1.0.0
   @ngrx/schematics      : 15.3.0
   @ngrx/store-devtools  : 15.3.0
   ng-mocks              : 14.6.0
   ---------------------------------------
   Local workspace plugins:
         @aicosy/nx-tools
```

**Comment by JamesHenry** [comment]
Hi @MarcusElevait, please review the Angular documentation regarding lazy loading: https://angular.io/guide/lazy-loading-ngmodules#lazy-loading-basics

`loadChildren` is designed to be used instead of `component` - it's one or the other, not both together - so the lint rule is correctly warning you about an incorrect setup here.

**Comment by MarcusElevait** [comment]
Hi @JamesHenry this helped a lot. Thanks and sorry for the inconvenience.

**Comment by piotrroda** [comment]
Hi @JamesHenry , I have another problem.

I've got ESLint error 'Imports of lazy-loaded libraries are forbidden' when I imported some model from lib, which is used in lazy-loaded routes.

```
import { PersonVM } from "@sls/sls-partners"; //<-- ERROR HERE !!

export class FoundObjectVM {
    Id: number;
    Ver: number;
    VehiclePartners: PersonVM[];

    constructor() {
        this.VehiclePartners = [];
    }
}

```

Problem is only when this module is lazy-loaded.
`{ path: 'partners', loadChildren: () => import('@sls/sls-partners').then(m => m.SlsPartnersModule) }`

**Comment by JamesHenry** [comment]
@piotrroda As with the OP it's important to consider why this rule exists and what it is telling you.

You are trying to lazy load something, but you are undermining that lazy loading attempt when you then statically import from the same module. When you statically import, you pay the penalty for loading that code, and the use of `loadChildren` provides no benefit.

In some cases, you will need to consider refactoring things out into multiple libraries to avoid such issues with your code, but one important thing in this specific case is that you are only try to use `PersonVM` as a type. Therefore, it does not need to incur a runtime overhead at all.

The way you can be explicit around this intention is to add the `type` keyword on the import.

```ts
import type { PersonVM } from "@sls/sls-partners";
```

The lint rule will now be able to know that you do not ever use `PersonVM` as a value, only as a type, and know you are safe from accidentally including its code in your bundles statically.

Hope that helps!

**Comment by JamesHenry** [comment]
@forivall please open a new issue, as you say yourself this is not related to the OP’s case
