### ISSUE TITLE
DataPersistence navigation run method is not triggered when using RouterState.Minimal

### ISSUE THREAD

**Issue by ramarivera** [nrwl/nx#1538]
## Expected Behavior

I am not sure about what the expected behaviour should be regarding the effect, since I understand that the navigation logic requires access to the routed component in order to match it and fire the run trigger. However, some documentation warning us that this combination is not compatible or some kind of runtime checks (if that were possible) instead of silently ignoring the effect would be nice.

## Current Behavior

When trying to use a navigation effect, the run block only gets fired if the RouterState serialization strategy is not Minimal. The reason for this is that the [findSnapshot](https://github.com/nrwl/nx/blob/master/packages/angular/src/runtime/nx/data-persistence.ts#L422) function requires access to the routed Component, which is not included when using the [RouterState.Minimal](https://ngrx.io/guide/router-store/configuration#routerstateminimal) serializer.
As far as I understand, this serializer is useful for having fully serializable actions, which the default serializer doesn't provide.

### Context
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.1.0-beta.2
Node: 10.15.0
OS: win32 x64
Angular: 8.1.0-next.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0-beta.2
@angular-devkit/build-angular     0.801.0-beta.2
@angular-devkit/build-optimizer   0.801.0-beta.2
@angular-devkit/build-webpack     0.801.0-beta.2
@angular-devkit/core              8.1.0-beta.2
@angular-devkit/schematics        8.1.0-beta.2
@angular/cdk                      8.0.1
@angular/cli                      8.1.0-beta.2
@angular/flex-layout              8.0.0-beta.26
@angular/http                     8.0.0-beta.10+1.sha-a28b3e3
@angular/material                 8.0.1
@ngtools/webpack                  8.1.0-beta.2
@schematics/angular               8.0.1
@schematics/update                0.801.0-beta.2
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.34.0
```

Ngrx related packages version:
```
"@ngrx/store": "^8.0.1",
"@ngrx/effects": "^8.0.1",
"@ngrx/entity": "^8.0.1",
"@ngrx/router-store": "^8.0.1",
```

**Comment by ramarivera** [comment]
One idea to solve this could be to write a custom serializer which instead of dropping the component alltogether serialized it as a string, so then `navigation` could do the match based on said string. Is that something (the name) that can be extracted from the metadata, even while running on an AOT build?

**Comment by vsavkin** [comment]
@ramarivera Using the component class name will work because the minifier won't change the class/function name. It, however, will still be broken when using `Minimal`.

**Comment by ramarivera** [comment]
Yes, I know. But writing a new route serializer that complies with fully serializable state and action and at the same time with  a data persistence that does the look up based on the component name is something I could do, of you are interested :)

**Comment by rovshenn** [comment]
Any progress on this? I am having issues where the component is frozen, which causes errors as explained in the below [SO](https://stackoverflow.com/questions/51410091/angular-and-error-of-attempting-to-configure-source-for-routeroutlet-and-ngif). Look at the answer by Klaster_1.

**Comment by brandonroberts** [comment]
We have fixed this upstream in NgRx so that you can use the serialization/immutability checks with the full router state, so these workarounds aren't needed. See https://github.com/ngrx/platform/pull/2491 and https://github.com/ngrx/platform/pull/2351 for context

**Comment by ramarivera** [comment]
@brandonroberts thanks for the fix. It took me some time to actually realize that the aforementioned fix only applies to actions, meaning that it is now possible to use `strictActionImmutability` and `strictActionSerializability` whilst using `RouterState.Full` and DataPersistence. Is doing the same for the state inmutability and serializabilty runtime checks (i.e. ignoring if it belongs to router state) something on the roadmap for Ngrx? if not, is there someway to circumvent it and still have state runtime checks?

**Comment by ramarivera** [comment]
Alternatively, would you accept PR that makes DataPersistence navigation method able to work based only on the routed component name, alongiside a custom router state serializer for this purpose?
