### ISSUE TITLE
Nx hangs in Podman container and nx daemon is deactivated when node_modules is mounted in a volume

### ISSUE THREAD

**Issue by remdash** [nrwl/nx#15389]
### Current Behavior

Hello Nx Team,

#### Context 

I'm trying to use nx to build a monorepository in a Podman container for local development.

#### Technical details

-  package manager: pnpm@7.9.4
- nx v15.0.13
- This container uses a dedicated volume for the node_modules for performances reasons
- The code files are mounted as volume from the filesystem 
- Image based on node:16-alpine3.16 with root user 
- Image built for mac M1 amd64 architecture

#### Observed behavior  
<br>

1. Nx hangs at the post-install step:

 `.../.pnpm/nx@15.0.13/node_modules/nx postinstall: > NX Daemon Server - Stopped`

I have to use Ctrl+C to stop it and the following error message is then displayed:
`Cannot read properties of undefined (reading 'slice')`

2. I can then check that nx daemon is indeed not running, even when trying to run `nx reset` or `nx setup` before

3. If I try to build my project using nx, I have the following output:

`nx build my-project`
 `NX   Nx Daemon was not able to compute the project graph.`
` `
 `Log file with the error: /__path__/my-project/node_modules/.cache/nx/d/daemon-error.log`
 `Please file an issue at https://github.com/nrwl/nx`
 `Nx Daemon is going to be disabled until you run "nx reset".`
` `
  ` ⠹    Nx is waiting on 41 dependent project tasks before running tasks from my-project...`
` `
`———————————————————————————————————————————————————————————————`
` `
`NX   Ran target build for project my-project and 41 task(s) it depends on (1s)`
` `
  `  ✖    0/0 failed`
   ` ✔    0/0 succeeded [0 read from cache]`
` `
`NX   Cannot read properties of null (reading 'write')`
` `
  `Pass --verbose to see the stacktrace.`
  
  Additionally,  no output is displayed for several minutes after the line `Nx Daemon is going to be disabled until you run "nx reset".`.

### Expected Behavior

I expect:

1. Nx not to hang at post-install step even when Nx daemon deactivates itself.
2. Nx to be able to build my project in a local Podman container even with its daemon deactivated.

### Steps to Reproduce

Try to build and run a monorepository in a Podman container with nx under the following conditions :

1.  package manager: pnpm@7.9.4
2. nx v15.0.13
3. This container uses a dedicated volume for the node_modules for performances reasons
4. The code files are mounted as volume from the filesystem 
5. Image based on node:16-alpine3.16 with root user 
6. Image built for amd64 and running on Mac M1

Then, you should observe:

1. The install will hang on nx post-install step
2. the build will hang and then finally fail

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.19.1
   OS   : linux x64
   pnpm : 7.9.4

   nx : 15.0.13
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : Not Found
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : Not Found
   typescript : 4.9.5
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by FrozenPandaz** [comment]
Could you please also add the contents of the error log file?

> Log file with the error: /__path__/my-project/node_modules/.cache/nx/d/daemon-error.log

**Comment by remdash** [comment]
Hello,

here are the daemon-error.log and the daemon.log (as the first one refers
to the second one, I did add it).

Tell me if you need any additional information.

Regards,
Rémi Pujo

**Comment by remdash** [comment]
Hello, do you need any additional info on this one ?
