### ISSUE TITLE
Following Angular tutorial is not working as docs say it should

### ISSUE THREAD

**Issue by danwellman** [nrwl/nx#15384]
### Current Behavior

I am following the Angular monorepo setup tutorial here: https://nx.dev/angular-tutorial/1-code-generation

I have successfully completed all steps as described up to step 3 (Task Running) and using same inputs/options as shown in the tutorial, e.g I have `myorg` root directory containing `apps` directory, `libs` directory, and all expected configuration files. All prior steps completed successfully and matched output shown in the tutorial.

At step three, I am not able to run the unit tests, when I try it gives error that Jest failed to parse a file:
![image](https://user-images.githubusercontent.com/373222/222490386-e65cef8b-c4dc-4265-ac97-1e95fc7aeada.png)

I've made no changes to any files except as specified by the tutorial.

Running the lint task *does* work

I am using Windows.

### Expected Behavior

Examples should work out of the box, as shown in the tutorial

### Steps to Reproduce

1. `npx create-nx-workspace@latest` and choose options according to tutorial
2. `cd myorg`
3. `npx nx g @nrwl/angular:app admin`
4. `npx nx g @nrwl/angular:lib common-ui`
5. `npx nx g @nrwl/js:lib products`
6. `npx nx g @nrwl/angular:component banner --project=common-ui --export`
7. Create banner component in banner.component.ts and include in app.component.ts/app.module.ts as described in tutorial
8. Create products as described in tutorial
9. Use banner and products in store app as described in tutorial
10. `npx nx test common-ui` - fails with error 

### Nx Report

```shell
Node : 14.19.0
   OS   : win32 x64
   npm  : 6.14.16

   nx                      : 15.8.1
   @nrwl/js                : 15.8.1
   @nrwl/jest              : 15.8.1
   @nrwl/linter            : 15.8.1
   @nrwl/workspace         : 15.8.1
   @nrwl/angular           : 15.8.1
   @nrwl/cli               : 15.8.1
   @nrwl/cypress           : 15.8.1
   @nrwl/devkit            : 15.8.1
   @nrwl/eslint-plugin-nx  : 15.8.1
   @nrwl/tao               : 15.8.1
   @nrwl/webpack           : 15.8.1
   typescript              : 4.9.5
```

### Failure Logs

```shell
Validation Warning:

  Unknown option "coverageDirectory" with value "../../coverage/libs/common-ui" was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration

 FAIL   common-ui  libs/common-ui/src/lib/banner/banner.component.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    D:\Repo\nx\myorg\libs\common-ui\src\lib\banner\banner.component.ts:10
        static { this.propDecorators = {
               ^

    SyntaxError: Unexpected token '{'

      1 | import { ComponentFixture, TestBed } from '@angular/core/testing';
      2 |
    > 3 | import { BannerComponent } from './banner.component';
        | ^
      4 |
      5 | describe('BannerComponent', () => {
      6 |   let component: BannerComponent;

      at Runtime.createScriptFromCode (../../node_modules/@jest/core/node_modules/jest-runtime/build/index.js:1495:14)
      at Object.<anonymous> (src/lib/banner/banner.component.spec.ts:3:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        8.295 s
Ran all test suites.

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target test for project common-ui (16s)

    ×    1/1 failed
    √    0/1 succeeded [0 read from cache]
```

### Additional Information

I hope I provided enough information. I did not provide a test repo as I literally just followed the tutorial step-by-step, word-for-word. If a test repo is needed I can try to provide one. Am happy to answer any further questions.

**Comment by barbados-clemens** [comment]
Hi there @danwellman, I just tried the tutorial you pointed out not working for you, 
and it works for me.
![terminal output of nx test common-ui showing it ran successfully](https://user-images.githubusercontent.com/23272162/222534953-f9f044ed-b2ce-4da7-be3f-eeab9f8fab76.png)

I noticed you mentioned windows so I wonder if that's at play since I'm on macOS. 

While I track down a windows computer to sanity check, would you mind committing and uploading the repo to github so I can clone it down and make sure it's not something else?

here is the working repo for me. https://github.com/barbados-clemens/nx-angular-tut-test-repro
you can try cloning this down and running the `nx test common-ui` to see if you get the same behavior.

**Comment by danwellman** [comment]
Thanks Caleb, I will try to upload the repo tonight after work, but I'll give yours a quick try now and see if I face the same issue

**Comment by danwellman** [comment]
I get the same issue in your repo Caleb. I cloned repo, npm install'ed, then ran test command -

![image](https://user-images.githubusercontent.com/373222/222687187-f790b974-26c4-455d-827c-41b48dc2b78b.png)

Must be a Windows thing. Do you still require me to upload my test repo?

**Comment by barbados-clemens** [comment]
We reran the tutorial on a windows machine and it passed for us so there must be something environmental on your machine that isn't being accounted for. Can you go ahead a upload that git repo to github so we can take a look as well?

Another thing I noticed, is you're using node v14. Can you try updating to the latest node LTS and re installing/running, though it should still work on v14 of node I'd imagine.

**Comment by danwellman** [comment]
Thanks, here is my pushed test repo with the issue: https://github.com/danwellman/nx 

I cannot change version of node on my current machine, but I will try this later this evening when I am on my own machine (also Windows) and let you know if it makes a difference

**Comment by barbados-clemens** [comment]
Thanks for pushing the repo @danwellman, but looks like there might be some missing commits. none of the libraries (common-ui) are in that repo. 

but projects that do have a test target setup do pass on my machine if that was also an issue for you. 


I'd also recommend into using something like [volta](https://volta.sh) that allow you to change your node version as needed. so you can keep working with node v14 for one project, but v18 for another etc. just an idea :)

**Comment by danwellman** [comment]
Eek, pushed repo before committing, like it was my first time using git 😳
Apologies, latest is committed and pushed now @barbados-clemens

**Comment by barbados-clemens** [comment]
Thanks! and looks like it does "work on my machine"
![nx test common-ui task completing successfully](https://user-images.githubusercontent.com/23272162/222779146-79d9477c-4164-40d6-a528-6aeb227b3c21.png)

I did try using node v14 and sure enough it fails with the same error, even if I don't use nx and just run jest. 

though both jest and jest-preset-angular (the transformer that make jest work with angular) state to support node v14.15+.0 and v16+ so it should work. 

personally since node v14 is end of life soon I'd just update to at least node v16. ideally latest node LTS (v18 as of commenting)

https://github.com/nodejs/Release

and as mentioned using tools like [volta](https://volta.sh) or [nvm](https://github.com/nvm-sh/nvm) or [n](https://github.com/tj/n) are an easy way to do this without having to do much effort than just running a command.

Let me know if upgrading to v16+ of node fixes it for you!

**Comment by danwellman** [comment]
Yep, can confirm on another Windows machine, with a higher version of Node installed, it works as expected:
![image](https://user-images.githubusercontent.com/373222/222901990-a498fe13-fb67-4b4f-a22d-c8874d32c5f9.png)

Thanks for looking into it, sorry to have wasted your time

**Comment by barbados-clemens** [comment]
No time wasted, happy to help and just glad we figured it out! 😃

**Comment by Elte156** [comment]
I'm running into the same issue but confirming that moving from Node 14 to Node 16 worked.

```console
>:myorg XXX$ node --version
v14.19.0
>:myorg XXX$ npx nx test common-ui --skip-nx-cache

> nx run common-ui:test

● Validation Warning:

  Unknown option "coverageDirectory" with value "../../coverage/libs/common-ui" was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration

 FAIL   common-ui  libs/common-ui/src/lib/banner/banner.component.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/XXX/Documents/GitHub/myorg/libs/common-ui/src/lib/banner/banner.component.ts:10
        static { this.propDecorators = {
               ^

    SyntaxError: Unexpected token '{'

      1 | import { ComponentFixture, TestBed } from '@angular/core/testing';
      2 |
    > 3 | import { BannerComponent } from './banner.component';
        | ^
      4 |
      5 | describe('BannerComponent', () => {
      6 |   let component: BannerComponent;

      at Runtime.createScriptFromCode (../../node_modules/@jest/core/node_modules/jest-runtime/build/index.js:1495:14)
      at Object.<anonymous> (src/lib/banner/banner.component.spec.ts:3:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.521 s
Ran all test suites.

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target test for project common-ui (7s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```


```console
>:myorg XXX$ node --version
v16.19.1
>:myorg XXX$ npx nx test common-ui --skip-nx-cache

> nx run common-ui:test

● Validation Warning:

  Unknown option "coverageDirectory" with value "../../coverage/libs/common-ui" was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration

 PASS   common-ui  libs/common-ui/src/lib/banner/banner.component.spec.ts
  BannerComponent
    ✓ should create (62 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        4.073 s
Ran all test suites.

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target test for project common-ui (7s)
```

**Comment by ddubrava** [comment]
Thank you, guys! I also faced the same issue and didn't even notice that v14 was selected 😅
