### ISSUE TITLE
create-nx-workspace does not generate a project if you use vite, not webpack

### ISSUE THREAD

**Issue by TheMrBlackLord** [nrwl/nx#15388]
### Current Behavior

If you run `npx create-nx-workspace --preset=react-monorepo` with version 15.8.1 as in the screenshot below and grab the vite bundler instead of webpack, an error occurs:
![image](https://user-images.githubusercontent.com/56202260/222502610-9f638b49-da98-402f-9c5c-405023d70f10.png)

Error log file
[error.log](https://github.com/nrwl/nx/files/10873999/error.log)

### Expected Behavior

The project should be created without errors

### Steps to Reproduce

1. start `npx create-nx-workspace --preset=react-monorepo`

### Nx Report

```shell
I can't attach the nx report because the directory is not part of the nx workspace.
```

### Failure Logs

```shell
warning "@nrwl/react > @phenomnomnominal/tsquery@4.1.1" has unmet peer dependency "typescript@^3 || ^4".
warning "@nrwl/cypress > @nrwl/devkit@15.8.1" has unmet peer dependency "nx@>= 14.1 <= 16".
warning "@nrwl/cypress > @phenomnomnominal/tsquery@4.1.1" has unmet peer dependency "typescript@^3 || ^4".
warning " > @nrwl/vite@15.8.1" has unmet peer dependency "vite@^4.0.1".
warning " > @nrwl/vite@15.8.1" has unmet peer dependency "vitest@^0.25.8".
warning "@nrwl/vite > @phenomnomnominal/tsquery@4.1.1" has unmet peer dependency "typescript@^3 || ^4".
warning "@nrwl/vite > @nrwl/devkit@15.8.1" has unmet peer dependency "nx@>= 14.1 <= 16".
error Command failed with exit code 1.
error Command failed with exit code 1.
```

### Additional Information

If you use npm, not yarn, then an error also occurs, but you can see it in the console:
![image](https://user-images.githubusercontent.com/56202260/222503611-a6cc570b-f554-4a8d-9796-4a4eb11bdf7c.png)

**Comment by sancelot** [comment]
same pb here

**Comment by mandarini** [comment]
@sancelot @TheMrBlackLord Hey! Thanks for filing an issue! Sorry, but I cannot reproduce :( 

Are you both on Windows? I am on a mac, but I will try to test on windows, too.

Here is my logs:

<details> <summary>`npx create-nx-workspace@latest --preset=react-monorepo` - Click to see log </summary>
```
npx create-nx-workspace@latest --preset=react-monorepo

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Repository name                       · test-repo
✔ Application name                      · web
✔ Bundler to be used to build the application · vite
✔ Default stylesheet format             · css
✔ Enable distributed caching to make your CI faster · Yes

 >  NX   Nx is creating your v15.8.5 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✔ Nx has successfully created the workspace: test-repo.
✔ NxCloud has been set up successfully

 >  NX   Successfully initialized git.


 ————————————————————————————————————————————————————————————————————————————————————————————


 >  NX   Nx CLI is not installed globally.

   This means that you might have to use "yarn nx" or "npx nx" to execute commands in the workspace.
   Run "yarn global add nx" or "npm install -g nx" to be able to execute command directly.


 ————————————————————————————————————————————————————————————————————————————————————————————


 >  NX   First time using Nx? Check out this interactive Nx tutorial.

   https://nx.dev/react-tutorial/1-code-generation


 >  NX   Distributed caching via Nx Cloud has been enabled

   In addition to the caching, Nx Cloud provides config-free distributed execution,
   UI for viewing complex runs and GitHub integration. Learn more at https://nx.app

   Your workspace is currently unclaimed. Run details from unclaimed workspaces can be viewed on cloud.nx.app by anyone
   with the link. Claim your workspace at the following link to restrict access.

   https://cloud.nx.app/orgs/workspace-setup?accessToken=MzQ3ZjY4Y2EtMjE4MC00ZjMyLTgzNzUtZDU3OWRkZjgxYmY0fHJlYWQtd3JpdGU=

```
</details>

**Comment by mandarini** [comment]
![Screenshot 2023-03-07 at 1 26 27 PM](https://user-images.githubusercontent.com/6603745/223409126-548e10c1-e70a-4ed0-a3a7-7020531ef2c2.png)

**Comment by elartix** [comment]
**Command**:
`npx -y create-nx-workspace@latest temp-workspace --appName=skeleton --preset=react-standalone --style=scss --bundler=vite --packageManager=npm --verbose`

**Result**:
```
added 348 packages, and audited 349 packages in 15s

32 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

>  NX  Generating @nrwl/workspace:preset


added 332 packages in 10s

30 packages are looking for funding
  run `npm fund` for details

added 333 packages in 9s

30 packages are looking for funding
  run `npm fund` for details

 >  NX   generateFiles: No files found in "/Users/MY_USER_NAME/AppData/Local/Temp/tmp-13148-Pg5wCsXdAlyB/node_modules/@nrwl/vite/src/generators/vitest/files". Are you sure you specified the correct path?

   Pass --verbose to see the stacktrace.


 >  NX   Workspace creation failed, see above.

   Pass --verbose to see the stacktrace.

```

I guess that something wrong with path on Windows environment. If we will review error log we can see that disk letter is missing

**Comment by sancelot** [comment]
> @sancelot @TheMrBlackLord Hey! Thanks for filing an issue! Sorry, but I cannot reproduce :(
> 
> Are you both on Windows? I am on a mac, but I will try to test on windows, too.
> 
> Here is my logs:
> 
> `npx create-nx-workspace@latest --preset=react-monorepo` - Click to see log

yes, I am using windows too

**Comment by sancelot** [comment]
If I use --verbose option I don't have any logs available

**Comment by mandarini** [comment]
I think @Cammisuli you were looking into these Windows issues?

**Comment by sancelot** [comment]
I tried to launch the same command in different contexts :
from my C: hdd drive , in the temp folder => it works
from my E: ssd drive => it failed

**Comment by sancelot** [comment]
> I tried to launch the same command in different contexts : from my C: hdd drive , in the temp folder => it works from my E: ssd drive => it failed

and today for unknown reason it fails ..... !!!!!!!!
I think there may be a cache problem
