### ISSUE TITLE
create-nx-workspace does not understand ng new options

### ISSUE THREAD

**Issue by DUBANGARCIA** [nrwl/nx#1539]
## Expected Behavior

When I try to create a new project with "ng new" options I would expect it to be created normally

## Current Behavior

When I run "yarn create nx-workspace example-app --create-application = false --prefix wiedii-apps --verbose --dry-run" fails because you do not understand the option --create-application and --prefix

## Failure Information (for bugs)

ng new "example-app" "--create-application=false" "--prefix" "example-app" "--verbose" "--dry-run" --collection=@nrwl/workspace
Unknown option: '--create-application'
Unknown option: '--prefix'
Unknown option: 'example-app'
child_process.js:669
    throw err;
    ^

Error: Command failed: "/tmp/tmp-3246wvBhKHmzpiSb/node_modules/.bin/ng" new "example-app" "--create-application=false" "--prefix" "example-app" "--verbose" "--dry-run" --collection=@nrwl/workspace

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. yarn create nx-workspace example-app --create-application = false --prefix wiedii-apps --verbose --dry-run

### Context

Please provide any relevant information about your setup:

- create-nx-workspace@8.2.0
- @angular/cli@8.0.6
- yarn: 1.17.0
- OS: debian 9.9   x64

**Comment by juristr** [comment]
@DUBANGARCIA do you actually want to create a new application inside an existing workspace or an entirely new workspace?

**Comment by DUBANGARCIA** [comment]
It is a completely new workspace

**Comment by juristr** [comment]
@DUBANGARCIA hmm..you might have used the wrong command. Try having a look at https://nx.dev/getting-started/getting-started.

Something like this should work:

```
npx --ignore-existing create-nx-workspace myworkspace
```

Also, if you want to use yarn, you can set that to be the default via

```
ng config -g cli.packageManager yarn
```

Hope that helps.

**Comment by DUBANGARCIA** [comment]
I still get the same error when I use npx:

![Captura de pantalla 2019-07-02 a la(s) 1 40 03 p  m](https://user-images.githubusercontent.com/17387158/60537928-33a31580-9ccf-11e9-9ad2-e6f64804fa18.png)

**Comment by vsavkin** [comment]
@DUBANGARCIA `@nrwl/workspace` is a different collection from `@schematics/angular` and it supports different options.  For instance, `create-nx-workspace` doesn't create any applications by default, so `--create-application` isn't meaningful here.

You can find the list of available options here: https://github.com/nrwl/nx/blob/master/packages/workspace/src/schematics/ng-new/schema.json

**Comment by DUBANGARCIA** [comment]
![Screenshot_20190709_150726](https://user-images.githubusercontent.com/17387158/60919902-8430ea80-a25c-11e9-82a7-466e9f2f38cf.png)

@vsavkin Then I had a confusion with the documentation because, according to the command line you can pass the same ng new options, therefore it would be a mistake to present this documentation in create-nx-workspace

**Comment by exequiel09** [comment]
Still occuring. Passing the `ng new` options in the create commands in the nx.dev documentation still fails.

<img width="1655" alt="Screen Shot 2020-03-16 at 9 33 32 AM" src="https://user-images.githubusercontent.com/1289472/76715903-349aab00-6769-11ea-90a4-4d458354c674.png">
