### ISSUE TITLE
yarn update upgrades to Angular 8.1.0-rc.0 release 🤔

### ISSUE THREAD

**Issue by juristr** [nrwl/nx#1540]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

I'm currently working on #1110 (having a local fix I'll push soon) and while doing so I tried to upgrade an NX 7 workspace I have to the latest version of NX. Strangely it results in getting Angular v8.1.0-rc.0 instead 🤔. I observed the upgrade process and first it upgrades to v8 correctly, but when the process comes at the point of upgrading the Angular CLI, it looks like it upgrades the Angular core deps again, now from v8 to v8 RC.

### Steps to Reproduce & Failure Information (for bugs)

To reproduce:

1. Create a v7 repo: `npx --ignore-existing create-nx-workspace@7.8.6 nxupgradetest`
1. Add a publishable lib which adds `ng-packagr` as dep (`ng g lib core --publishable=true`)
1. Execute the upgrade script `yarn update`

Here's an example JSON with which I'm able to reproduce the bug:

```json
{
  "name": "nxupgradetest",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "./node_modules/.bin/nx lint && ng lint",
    "e2e": "ng e2e",
    "affected:apps": "./node_modules/.bin/nx affected:apps",
    "affected:libs": "./node_modules/.bin/nx affected:libs",
    "affected:build": "./node_modules/.bin/nx affected:build",
    "affected:e2e": "./node_modules/.bin/nx affected:e2e",
    "affected:test": "./node_modules/.bin/nx affected:test",
    "affected:lint": "./node_modules/.bin/nx affected:lint",
    "affected:dep-graph": "./node_modules/.bin/nx affected:dep-graph",
    "affected": "./node_modules/.bin/nx affected",
    "format": "./node_modules/.bin/nx format:write",
    "format:write": "./node_modules/.bin/nx format:write",
    "format:check": "./node_modules/.bin/nx format:check",
    "update": "ng update @nrwl/schematics",
    "update:check": "ng update",
    "workspace-schematic": "./node_modules/.bin/nx workspace-schematic",
    "dep-graph": "./node_modules/.bin/nx dep-graph",
    "help": "./node_modules/.bin/nx help"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.0.0",
    "@angular/cdk": "~7.3.7",
    "@angular/common": "^7.0.0",
    "@angular/compiler": "^7.0.0",
    "@angular/core": "^7.0.0",
    "@angular/forms": "^7.0.0",
    "@angular/material": "7.3.7",
    "@angular/platform-browser": "^7.0.0",
    "@angular/platform-browser-dynamic": "^7.0.0",
    "@angular/router": "^7.0.0",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "rxjs": "6.3.3",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "jest-preset-angular": "7.0.0",
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular-devkit/build-ng-packagr": "~0.13.0",
    "@angular/cli": "7.3.1",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "^7.0.0",
    "@nrwl/builders": "7.8.6",
    "@nrwl/schematics": "7.8.6",
    "@types/jest": "24.0.9",
    "@types/jquery": "3.3.6",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "cypress": "3.1.0",
    "dotenv": "6.2.0",
    "jest": "24.1.0",
    "ng-packagr": "^4.2.0",
    "prettier": "1.16.4",
    "ts-node": "~7.0.0",
    "tsickle": ">=0.34.0",
    "tslib": "^1.9.0",
    "tslint": "~5.11.0",
    "typescript": "3.2.2"
  }
}
```

It looks like this happens due to the 2-step upgrade and only if `ng-packagr` is included (which I cannot explain to myself why this is the case, I'd have to dig further). With the Angular CLI, normally the update command is something like `ng update @angular/cli @angular/core`, which means in 1 step both are being updated.

In NX though, first the `@angular/core` deps are updated (using `--force --allow-dirty`), which upgrades all deps successfully to `v8`, but then when the update for `@angular/cli` is done, it upgrades the already upgraded `v8` deps to the latest RC.

**Comment by juristr** [comment]
Just updated the original description to better reflect my latest findings.

**Comment by vsavkin** [comment]
It appears to be an issue with `ng-packagr` peer dependencies. 

```
    "@angular/compiler": "^6.0.0 || ^7.0.0 || ^8.0.0-beta.0 || ^8.1.0-beta.0 || ^8.2.0-beta.0 || ^8.3.0-beta.0 || ^8.4.0-beta.0 || >=9.0.0-beta < 9",
    "@angular/compiler-cli": "^6.0.0 || ^7.0.0 || ^8.0.0-beta.0 || ^8.1.0-beta.0 || ^8.2.0-beta.0 || ^8.3.0-beta.0 || ^8.4.0-beta.0 || >=9.0.0-beta < 9",
```

`ng packagr` needs to be updated, there is not much we can do on the Nx side.

**Comment by vsavkin** [comment]
I'm going to close this one. Since we can't do much with the way `ng update` works, we have built a different ways to keep your projects up to date: `nx migrate`. It's a lot more straightforward and doesn't rely on peer dependencies.

**Comment by juristr** [comment]
@vsavkin 👍
