### ISSUE TITLE
nx:run-script doc

### ISSUE THREAD

**Issue by electroheadfx** [nrwl/nx#15428]
### Documentation issue

- [ X] Documentation improvement

I have a script in apps/app-test in project.json
```json
"deploy-sh": {
      "executor": "nx:run-script",
      "options": {
        "script": "scripts/deploy"
      }
    },
```
I have created a file in scripts/deploy.sh in bash
NX can't find the file to run, any help ?
is NX I don't know if it run node by default or bash ? is the extension needed ? is the root is the apps/app-test ?

**Comment by AgentEnder** [comment]
You want run-commands, run-script runs an npm script. 

https://nx.dev/packages/nx/executors/run-script#nx:run-script

Vs

https://nx.dev/packages/nx/executors/run-commands#nx:run-commands
