### ISSUE TITLE
Cypress move generator makes assumptions about what props are set

### ISSUE THREAD

**Issue by willyboy** [nrwl/nx#15433]
### Current Behavior

When using the cypress move generator with a cypress.json (or cypress.config.ts) file that doesn't contain a videosFolder (because videos is set to false) or a screenshotsFolder property, the generator fails with "cannot read replace of undefined".

### Expected Behavior

The move generator should noop if either of these properties don't exist.

### GitHub Repo

https://github.com/nrwl/nx-examples

### Steps to Reproduce

1.
remove videosFolder from https://github.com/nrwl/nx-examples/blob/master/apps/cart-e2e/cypress.config.ts
2. run move generator on the project
```npx nx g move --project=cart-e2e```

### Nx Report

```shell
N/A - exists on v14 and v15
```

**Comment by AgentEnder** [comment]
Can you add a stack trace from the issue? Passing --verbose should help.

**Comment by willyboy** [comment]
> Can you add a stack trace from the issue? Passing --verbose should help.

I'm working on opening a PR - not sure that's necessary?

**Comment by willyboy** [comment]
@AgentEnder opened PRs for this in HEAD and 14.4.x (where we have the issue). Do you want fixes for the other 14.x versions or can you cherry pick the HEAD into those?
