### ISSUE TITLE
Storybook not working for new NX workspace  | Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by bhvyaV** [nrwl/nx#15430]
ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)

    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:442:9)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

info => Loading presets
95% emitting emit
 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target storybook for project shared-components (9s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]

_Originally posted by @github-actions[bot] in https://github.com/nrwl/nx/issues/14093#issuecomment-1453585428_
            

Story book only works when i downgrade node version 16 from 18. how can i fix it using node version 18 LTS .

**Comment by bhvyaV** [comment]
@AgentEnder i created new project using NX latest and not able to work with Storybook.

**Comment by mandarini** [comment]
Hi @bhvyaV, thanks for filing an issue! Which builder are you using for Storybook? The `@storybook/builder-vite` only works with Node version 16, unfortunately, and this is not related to Nx. If you want to use Node 18, you have to [upgrade to Storybook version 7](https://nx.dev/packages/storybook/documents/storybook-7-setup). Take a look at [this issue](https://github.com/storybookjs/builder-vite/issues/414#issuecomment-1287536049).

**Comment by bhvyaV** [comment]
storybook 7 is still in Beta version. :(

**Comment by mandarini** [comment]
Hi @bhvyaV ! I understand. This is not an issue with Nx however. I suggest you leave a reply in the issues I linked above, but I expect the Storybook team will suggest you use Storybook 7 if you want to use Node 18. :( Storybook 7 will come out of beta really soon, though!
