### ISSUE TITLE
--js flag doesn't omit the Typescript setup

### ISSUE THREAD

**Issue by Kycermann** [nrwl/nx#15447]
### Current Behavior

When I run `nx g @nrwl/expo:app client --js`, I expect there not to be Typescript.

### Expected Behavior

When I run `nx g @nrwl/expo:app client --js`, there is Typescript.

There are still these files: `tsconfig.app.json`, `tsconfig.json`, `tsconfig.spec.json`

### Steps to Reproduce

1. `npx create-nx-workspace example --preset=empty --js`
2. `cd example`
3. `npx nx generate @nrwl/expo:app client --js`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : darwin arm64
   npm  : 8.3.1
   
   nx                      : 15.8.5
   @nrwl/js                : 15.8.5
   @nrwl/jest              : 15.8.5
   @nrwl/linter            : 15.8.5
   @nrwl/workspace         : 15.8.5
   @nrwl/cli               : 15.8.5
   @nrwl/detox             : 15.8.5
   @nrwl/devkit            : 15.8.5
   @nrwl/eslint-plugin-nx  : 15.8.5
   @nrwl/expo              : 15.8.5
   @nrwl/react             : 15.8.5
   @nrwl/tao               : 15.8.5
   @nrwl/webpack           : 15.8.5
   @nrwl/nx-cloud          : 15.1.1
   typescript              : 4.9.5
```

**Comment by xiongemi** [comment]
i think it is intentional. if you create any library with --js flag, not just form @nrwl/expo, it will still keep tsconfig files even though these files have no effects.
closing this issue for now.
