### ISSUE TITLE
Error "Cannot read property 'root' of undefined" when NgRx schematic is used without "--project" flag

### ISSUE THREAD

**Issue by nicky-lenaers** [nrwl/nx#1545]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

## Expected Behavior
Please describe the behavior you are expecting

When running the below command without a `--project` flag, I expect the error message to reflect the missing flag, instead of the message `Cannot read property 'root' of undefined`, as it is non-descriptive. The command I ran:

```sh
$ ng generate @ngrx/schematics:store State --root --module app.module.ts
```

The message could be improved by something like:

```
Could not determine the Angular project. Please provide a '--project' flag.
```

## Current Behavior

What is the current behavior?

The current behavior is that when running the above command, it **does not** generate the expected files. Instead, it presents the non-descriptive error message `Cannot read property 'root' of undefined`. When running the below command, it **does** generate the expected files.

```sh
$ ng generate @ngrx/schematics:store State --root --module app.module.ts --project my-angular-project
```

Note that `my-angular-project` should obviously be defined in you `angular.json` file.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a new Nx Workspace, say `my-workspace` and be sure to include an Angular project
2. Step 1 generates the Angular files. Now, delete the full Angular app and create one with a different name, say `my-different-angular-project`.
3. Now, generate the NgRx root store using the command:

```sh
$ ng generate @ngrx/schematics:store State --root --module app.module.ts
```

4. Now, you should see the error.

### Context

Please provide any relevant information about your setup:

- version of Nx used
**"@nrwl/workspace": "8.2.0"**
- version of Angular CLI used
**@angular/cli@8.0.1**
- `angular.json` configuration
**Can't share**
- version of Angular DevKit used
**"@angular-devkit/build-angular": "^0.800.0",**
- 3rd-party libraries and their versions
**@ngrx/schematics": "^8.0.1"**
- and most importantly - a use-case that fails
**See the above reproduction steps.**

**A minimal reproduce scenario using allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

Please include any relevant log snippets or files here.
![image](https://user-images.githubusercontent.com/2785350/60469620-ad022000-9c5d-11e9-9697-8dbdc5bccae8.png)

## Other

Any other relevant information that will help us help you.
According to [this issue](https://github.com/nrwl/nx/issues/641), it could be caused by a mismatch between the Angular Project name in `angular.json` and the name used in `package.json`, but I'm not sure about that.

**Comment by brandonroberts** [comment]
@nicky-lenaers this is not an issue with Nx itself, but with `@ngrx/schematics`. You should open an issue there instead https://github.com/ngrx/platform/issues/new/choose

**Comment by vsavkin** [comment]
Since it's not an Nx issue, I'm going to close it. We can track it on the NgRx side.
