### ISSUE TITLE
Using `NX_CACHE_DIRECTORY` causes error when running on a "clean" clone

### ISSUE THREAD

**Issue by swcm-mnestler** [nrwl/nx#15468]
### Current Behavior

With nx `15.8.5`, setting `NX_CACHE_DIRECTORY` to an empty directory and running `npx nx run <project>:<task>` causes an error `Could not find 'nx' module in this workspace`(see below for full error). This causes an issue for us in CI, where we set `NX_CACHE_DIRECTORY=.nx` and sometimes run without a cache present.

Calling `nx reset`  after the failure seems to initialize the cache fine.

### Expected Behavior

Like in `15.7.2`, an empty cache should be populated as necessary (including the now-missing `cache/nxdeps.json`) instead of throwing an error.

### GitHub Repo

https://github.com/swcm-mnestler/nx-missing-cache-reproducer

### Steps to Reproduce

Steps to reproduce:

1. Clone repository
2. Run `npm ci`
3. Run `npm run reproduce` -> Error
4. Run `npx nx reset`
5. Run `npm run reproduce` -> Success

### Nx Report

```shell
Node : 18.14.0
OS   : linux x64
npm  : 9.3.1
   
nx                      : 15.8.5
@nrwl/js                : 15.8.5
@nrwl/linter            : 15.8.5
@nrwl/workspace         : 15.8.5
@nrwl/cli               : 15.8.5
@nrwl/devkit            : 15.8.5
@nrwl/eslint-plugin-nx  : 15.8.5
@nrwl/tao               : 15.8.5
typescript              : 4.9.5
```

### Failure Logs

```shell
Could not find 'nx' module in this workspace. Error: [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.

If you are leveraging \`readCachedProjectGraph()\` directly then you will need to refactor your usage to first ensure that
the ProjectGraph is created by calling \`await createProjectGraphAsync()\` somewhere before attempting to read the data.

If you encounter this error as part of running standard \`nx\` commands then please open an issue on https://github.com/nrwl/nx
    at readCachedProjectGraph (/home/user/nx-missing-cache-reproducer/node_modules/nx/src/project-graph/project-graph.js:28:15)
    at run (/home/user/nx-missing-cache-reproducer/node_modules/nx/src/command-line/run.js:171:69)
    at requireCli (/home/user/nx-missing-cache-reproducer/node_modules/nx/bin/run-executor.js:17:23)
    at Object.<anonymous> (/home/user/nx-missing-cache-reproducer/node_modules/nx/bin/run-executor.js:12:1)
```

**Comment by ianldgs** [comment]
Happened to us not only for the `NX_CACHE_DIRECTORY` environment variable, but also for the `cacheDirectory` in nx.json.

**Comment by icedcrow** [comment]
Same issue here, 16.1.1

I found two ways to solve my problem:

1. `pnpm install`
2. `mkdir -p .nx-cache`
3. `pnpm build` -> Error `Failed to process the project graph with "nx-js-graph-plugin".`
4. `pnpm build` -> Success

or

1. `pnpm install`
2. `mkdir -p .nx-cache`
3. `CI=true pnpm build` -> Success

**Comment by seeplusplus** [comment]
> Happened to us not only for the `NX_CACHE_DIRECTORY` environment variable, but also for the `cacheDirectory` in nx.json.

Same here on 15.9.2.

**Comment by Pkearney2021** [comment]
Same on `15.9.4`
