### ISSUE TITLE
[Question / Feature request] Use Nx workspace to build an ng lib that has dependencies on another lib in the same workspace

### ISSUE THREAD

**Issue by githendrik** [nrwl/nx#1547]
## Expected Behavior

In a large codebase we have the following setup:

webapp1
webapp2
core-lib
publishable-lib
testapp-for-publishable-lib

where 

webapp1->core-lib
webapp2->core-lib
publishable-lib->core-lib
testapp-for-publishable-lib->publishable-lib->core-lib

Core question/issue: We need to publish the publishable-lib to an internal npm registry.

## Current Behavior
Running the apps or the test app works fine, all typescript gets compiled during runtime, hot reload of any app from inside the core-lib works etc (due to the path rewrite imports inside tsconfig).

What doesn't work is building the publishable-lib in order to publish it. This fails due to `error TS6059: File 'libs/core-lib/src/index.ts' is not under 'rootDir' 'libs/publishable-lib/src'. 'rootDir' is expected to contain all source files.`

### Steps to Reproduce

1. ng g lib core-lib --directory="" --style="css"
2. ng g lib publishable-lib --publishable --directory="" --style="css"
3. import CoreLibModule into PublishableLibModule
4. ng build publishable-lib

### Context
- @nrwl/angular: 8.2.0
- @angular/cli: 8.0.6
- @angular-devkit/core: 8.0.6

Any help in this matter is appreciated. My gut feeling is that it has something to do with RollupJS/ng-packagr (because it works with the apps, or with the karma tests of the publishable-lib (where the core-lib is used as well)).

The only workaround I know of is building the core-lib to /dist and then re-writing the @myproj/core imports of the publishable lib to consume the dist output. But that defeats the nice autocompile/watch etc modes.

**Comment by un33k** [comment]
Let's close this as it is being tracked via https://github.com/nrwl/nx/issues/602

**Comment by githendrik** [comment]
Okay, sure, sorry for the dupe. I wonder why I didn't find that one before.

Duplicate of #602
