### ISSUE TITLE
Unknown jest option: colors, reporters, verbose, coverage, coverageReporters, and coverageDirectory

### ISSUE THREAD

**Issue by bmarti44** [nrwl/nx#1548]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

The jest options for colors, reporters, verbose, coverage, coverageReporters, and coverageDirectory should be known and passed to jest

## Current Behavior

Currently the jest options for colors, reporters, verbose, coverage, coverageReporters, and coverageDirectory are unknown and throw an error

I have created https://github.com/nrwl/nx/pull/1546 to add the above options - if additional tests are necessary, please let me know and I will get those added.

**Comment by sroettering** [comment]
I think testPathPattern is missing, too.
Could you add it?

**Comment by appsolutegeek** [comment]
I am little confused, it is merged but when we it be built and available to be upgraded ? via npm or ng update ?

**Comment by appsolutegeek** [comment]
It is currently not possible to debug tests in webstorm as it is passing parameters to ng test that it does not understand.

**Comment by bmarti44** [comment]
@appsolutegeek yes, I use webstorm as well, and noticed I couldn't get code coverage integrated without these options. I would assume you can use the next version to get access (I'm actually about to try it out).

@sroettering I only needed the options in this issue for webstorm, unfortunately... But, if you open another issue, I'll be more than happy to take a look, it's really easy to add. I'll be on a work trip through this next week so might have limited availability.

For now, since this is merged, I'm closing this issue. But overall, just wanna note that the way things are setup, it's very, very easy to add more of these options.

**Comment by sroettering** [comment]
Sorry, did not see that your PR was already merged.
Created my own now for the testPathPattern parameter https://github.com/nrwl/nx/pull/1563
