### ISSUE TITLE
NX 15.8 shows: `NX   Cannot find module '@nrwl/nx-freebsd-x64'`

### ISSUE THREAD

**Issue by mfechner** [nrwl/nx#15492]
### Current Behavior

NX 15.8 does not work on FreeBSD anymore.

### Expected Behavior

NX 15.8 should work like NX 15.7.

### Steps to Reproduce

On a FreeBSD machine execute:

1. npx create-nx-workspace@15.8.2
✔ Choose what to create                 · integrated
✔ What to create in the new workspace   · nest
✔ Repository name                       · test1582
✔ Application name                      · backend
✔ Enable distributed caching to make your CI faster · No

fails.

It is working fine with:
npx create-nx-workspace@15.7.2
✔ Choose what to create                 · integrated
✔ What to create in the new workspace   · nest
✔ Repository name                       · test1572
✔ Application name                      · backend
✔ Enable distributed caching to make your CI faster · No

### Nx Report

```shell
❯ npx nx report
Need to install the following packages:
  nx
Ok to proceed? (y)

 >  NX   The current directory isn't part of an Nx workspace.

   To create a workspace run:
   npx create-nx-workspace@latest <workspace name>

   To add Nx to existing workspace run with a workspace-specific nx.json:
   npx add-nx-to-monorepo@latest

   To add the default nx.json file run:
   nx init


 >  NX   For more information please visit https://nx.dev/
```
```


### Failure Logs

```shell
added 891 packages, and audited 892 packages in 13s

96 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

 >  NX   Cannot find module '@nrwl/nx-freebsd-x64'

   Require stack:
   - /usr/home/idefix/tmp/text-nx-15.7.2/test1582/node_modules/nx/src/native/index.js
   - /usr/home/idefix/tmp/text-nx-15.7.2/test1582/node_modules/nx/src/hasher/native-file-hasher.js
   - /usr/home/idefix/tmp/text-nx-15.7.2/test1582/node_modules/nx/src/hasher/file-hasher.js
   - /usr/home/idefix/tmp/text-nx-15.7.2/test1582/node_modules/nx/src/project-graph/build-project-graph.js
   - /usr/home/idefix/tmp/text-nx-15.7.2/test1582/node_modules/nx/src/project-graph/project-graph.js
   - /usr/home/idefix/tmp/text-nx-15.7.2/test1582/node_modules/nx/src/command-line/generate.js
   - /usr/home/idefix/tmp/text-nx-15.7.2/test1582/node_modules/nx/src/command-line/nx-commands.js
   - /usr/home/idefix/tmp/text-nx-15.7.2/test1582/node_modules/nx/bin/init-local.js
   - /usr/home/idefix/tmp/text-nx-15.7.2/test1582/node_modules/nx/bin/nx.js


 >  NX   Workspace creation failed, see above.

   Pass --verbose to see the stacktrace.


npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
```
```


### Additional Information

I think with version 15.8.x something was changed that requires now a FreeBSD related file which does not exist.

**Comment by tamaserdfalvi** [comment]
I could second that, on our Bitbucket Pipelines CI/CD it's
`>  NX   Cannot find module '@nrwl/nx-linux-x64-gnu'`

but I believe that's the same issue. If you issue a 
`npm install @nrwl/nx-linux-x64-gnu` before ANY given step it's working, but of course that cannot be a solution

**Comment by Cammisuli** [comment]
Oh, we don't build binaries for FreeBSD. But we can. 

For my curiosity, whats your use case here? Is this a CI system?

**Comment by tamaserdfalvi** [comment]
> Oh, we don't build binaries for FreeBSD. But we can.
> 
> For my curiosity, whats your use case here? Is this a CI system?

As a matter of fact, like I said same happens for us on bitbucket pipelines, which isn't FreeBSD, it might be something else

**Comment by Cammisuli** [comment]
yea, @tamaserdfalvi your issue is related to this https://github.com/nrwl/nx/issues/15380, and if you dont mind, can you post your package.json to that thread? I want to see if I can reproduce it. 

I want to keep this thread for FreeBSD support, thank you!

**Comment by mfechner** [comment]
> For my curiosity, whats your use case here? Is this a CI system?

@Cammisuli yes it is a CI system (gitlab) that is running on FreeBSD.
