### ISSUE TITLE
reporter options are not passed to jest-junit

### ISSUE THREAD

**Issue by dmcweeney** [nrwl/nx#15499]
### Current Behavior

I am trying to generate junit reports from the test runs and save them to a folder off the workspace root for feeding into the PublishTestResults ado pipeline task. However the jest-junit reporter just saves them to a file called junit.xml in the workspace root.

### Expected Behavior

Honor the settings I have specified!

### Steps to Reproduce

package project.json

```
    "test": {
      "executor": "@nrwl/jest:jest",
      "outputs": ["{workspaceRoot}/coverage/{projectRoot}"],
      "options": {
        "jestConfig": "packages/base/jest.config.ts",
        "passWithNoTests": true,
        "reporters": [
          "default",
          [
            "jest-junit",
            {
              "outputDirectory": "<rootDir>../../reports",
              "outputName": "unit-tests-report.xml",
              "suiteName": "unit tests - base"
            }
          ]
        ]
      },
      "configurations": {
        "ci": {
          "ci": true,
          "codeCoverage": true,
          "verbose": true,
          "debug": true,
          "reporters": ["default", "jest-junit"]
        }
      }
    }

```

run command: `nx run base:test:ci`

Generated output is `{workspaceroot}/junit.xml `in workspace root.
It should be `{workspaceroot}/reports/unit-tests-report.xml`

Also the specified `suiteName` is not set in the generated junit.xml

NOTE I have tried various combinations of the `outputDirectory` specification but all are ignored.

Also with debug turned on the printed configuration for reporters is:
```
"reporters": [
      [
        "default",
        {}
      ],
      [
        "C:\\username\\Repos\\project\\project-libs\\node_modules\\jest-junit\\index.js",
        {}
      ]
    ],

```

Which again would point to the specified configuration not being passed through.

### Nx Report

```shell
Node : 16.15.0
   OS   : win32 x64
   npm  : 8.5.5
   
   nx                      : 15.8.5
   @nrwl/js                : 15.8.5
   @nrwl/jest              : 15.8.5
   @nrwl/linter            : 15.8.5
   @nrwl/workspace         : 15.8.5
   @nrwl/cli               : 15.8.5
   @nrwl/devkit            : 15.8.5
   @nrwl/eslint-plugin-nx  : 15.8.5
   @nrwl/tao               : 15.8.5
   typescript              : 4.8.4
   ---------------------------------------
   Community plugins:
   @jscutlery/semver : 2.30.1
```

### Additional Information

I did find this issue ([https://github.com/jest-community/jest-junit/issues/201](https://github.com/jest-community/jest-junit/issues/201)) but I have no reference to testResultsProcessor in my configurations

**Comment by barbados-clemens** [comment]
I just tried it and jest doesn't allow for options like that passed into the reporters object. so it's not a valid schema type for Nx either.

You can instead place this in your jest config or use the env vars provided by jest-junit, which I've confirmed work

```bash
JEST_SUITE_NAME="unit tests -base" JEST_JUNIT_OUTPUT_DIR="<rootDir>/custom/something" JEST_JUNIT_OUTPUT_NAME="custom.xml" nx test --coverage
```
```ts
export default {

// other config options

  reporters: [
    'default',
    [
      'jest-junit',
      {
        outputDirectory: '<rootDir>/reports',
        outputName: 'unit-tests-report.xml',
        suiteName: 'unit tests - base',
      },
    ],
  ],
}

```

**Comment by dmcweeney** [comment]
Hi @barbados-clemens,
Thanks for looking into this.
Based on your tip I eventually got it working by creating a `.env.test` file in each package folder and these env vars contains the required jest-junit [configuration](https://github.com/jest-community/jest-junit#configuration).

Thanks again, mush appreciated.

Donal
Donal
