### ISSUE TITLE
Module federation remoteEntry file extension

### ISSUE THREAD

**Issue by Akkora** [nrwl/nx#15513]
## Description

Option to generate `remoteEntry` with `.js` extension instead of `.mjs`

Background:
We have an angular project with module federation. One host and two remotes. When building we get the remoteEntry files with `.mjs` extension. If we manually rename them to `.js` and update the host `main.js` to use them as well, it works without any issues.

## Motivation

We don't want to configure our server to allow access to mjs next to js files in this case, since js files work just fine without extra effort on server side.

## Suggested Implementation

Introduce a configuration option like `remoteEntryExt: '.js' | '.mjs'`

**Comment by ryanjpburgos** [comment]
![image](https://user-images.githubusercontent.com/49457859/225994357-0a3112c6-8eaa-4b3b-ac64-87c524513c4d.png)
I'm facing this problem, I think that it's related

**Comment by Coly010** [comment]
It should be a small effort to support .mjs on the server side. As Angular uses ESM now, we're not going to be making a change to configure the file extension for the remote entry file.

The MJS file contains ESM code and therefore it makes more sense for the extension to stay as mjs.
