### ISSUE TITLE
Fail to serve | generate new project with MacOS

### ISSUE THREAD

**Issue by tunguyensss** [nrwl/nx#15529]
### Current Behavior

when init new `nx` project I run command to generate | serve new project but it won't work

### Expected Behavior

it's work, generate new project | serving project

### Steps to Reproduce

1. node: v16.18.1
2. npm: v8.19.2
3. nx: v15.8.5
4. run `npx create-nx-workspace project-name --preset=empty`
5. install `@nrwl/next` and Nx extensions in VSCode
6. generate  new project with `@nrwl/next:app`

### Nx Report

```shell
dlopen(/Users/path-to-project/node_modules/@nrwl/nx-darwin-x64/nx.darwin-x64.node, 1): no suitable image found.  Did find:

   	/Users/path-to-project/node_modules/@nrwl/nx-darwin-x64/nx.darwin-x64.node: cannot load 'nx.darwin-x64.node' (load command 0x80000034 is unknown)
   	/Users/path-to-project/node_modules/@nrwl/nx-darwin-x64/nx.darwin-x64.node: cannot load 'nx.darwin-x64.node' (load command 0x80000034 is unknown)
```

### Failure Logs

```shell
dlopen(/Users/path-to-project/node_modules/@nrwl/nx-darwin-x64/nx.darwin-x64.node, 1): no suitable image found.  Did find:

   	/Users/path-to-project/node_modules/@nrwl/nx-darwin-x64/nx.darwin-x64.node: cannot load 'nx.darwin-x64.node' (load command 0x80000034 is unknown)
   	/Users/path-to-project/node_modules/@nrwl/nx-darwin-x64/nx.darwin-x64.node: cannot load 'nx.darwin-x64.node' (load command 0x80000034 is unknown)
```

**Comment by mandarini** [comment]
Hi there @tunguyensss ! Thanks for filing an issue! I am sorry, but I cannot reproduce your issue.

Steps I followed:

1. `npx create-nx-workspace@latest project-name --preset=empty`
2. `cd project-name`
3. `yarn add -D @nrwl/next`
4. `npx nx g @nrwl/next:app --name=my-app --style=css`
5. `npx nx serve my-app`
 
And all commands work as expected.

Can you please give me some more context? Are you following the above steps?

**Comment by tunguyensss** [comment]
Thank @mandarini for your help, I've reset my Mac and all of these things are gone with the wind 😄 
by the way, could you tell me more about this error?

**Comment by tunguyensss** [comment]
> Hi @tunguyensss ! That's so good to hear, that the error went away! I am afraid I don't know what to tell you! I think it was most probably bad cache issue?

that okay, I think cache is not the problem cause I have clean cache many times
