### ISSUE TITLE
How do we avoid updateDependencies from application schematics

### ISSUE THREAD

**Issue by sgunasekaran-gs** [nrwl/nx#1552]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

nrwl application schematic updating npm dependency after creating the app which could be an optional.

- [ ] Running NX 7.8.5
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

This should be an optional to update the npm depedency.

## Current Behavior
After the app generated, its updating package.json which impacting my other dependency in the package json

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

@nrwl/schematics/src/collection/application/index.js
**updateDependencies(options)**

### Context

Please provide any relevant information about your setup:

- 7.8.5 version of Nx used
- 7.3.9 version of Angular CLI used
- `angular.json` configuration

**Comment by FrozenPandaz** [comment]
I think a `--skip-dependencies` option would be nice to have and could be done by a contributor.

Would anybody be interested in implementing this?
