### ISSUE TITLE
Removal of angular.json should have been a breaking change/major version update

### ISSUE THREAD

**Issue by alexciesielski** [nrwl/nx#15527]
### Current Behavior

Currently lots of our generators and scripts rely on `angular.json` being present and defining a mapping of `ProjectName` to `ProjectLocation`.

What seemingly looked like a simple `nx migrate latest` turns out to be a major pain because practically everything breaks now, after something that should have been at least warned about and deprecated for some time before just removing it in a minor version update.

### Expected Behavior

At the very least deprecation warnings for a couple of weeks, possibly also not throwing an error on `nx serve` just because an `angular.json` file exists.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.14.1
   OS   : darwin arm64
   npm  : 9.3.1

   nx                      : 15.8.5
   @nrwl/js                : 15.8.5
   @nrwl/jest              : 15.6.3
   @nrwl/linter            : 15.8.5
   @nrwl/workspace         : 15.8.5
   @nrwl/angular           : 15.8.5
   @nrwl/cli               : 15.8.5
   @nrwl/cypress           : 15.8.5
   @nrwl/devkit            : 15.8.5
   @nrwl/eslint-plugin-nx  : 15.8.5
   @nrwl/rollup            : 15.8.5
   @nrwl/storybook         : 15.8.5
   @nrwl/tao               : 15.8.5
   @nrwl/web               : 15.8.5
   @nrwl/webpack           : 15.8.5
   @nrwl/nx-cloud          : 15.1.1
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.11.1
   @ngneat/hot-toast                : 5.0.1
   @ngneat/tailwind                 : 7.0.3
   @storybook/angular               : 7.0.0-beta.62
   ng-mocks                         : 14.6.0
   nx-stylelint                     : 13.5.3
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/jest@15.6.3

   To fix this, run `nx migrate nx@15.8.5`
```

### Additional Information

This is more of a rant with the hope for future improvements in communication of breaking changes, than a bug report.

**Comment by Coly010** [comment]
What version did you migrate from -> to?

We've been phasing out root project configurations since September https://github.com/nrwl/nx/releases/tag/14.7.18

**Comment by Coly010** [comment]
Given we have means of achieving the same result, I'm going to close this issue. Feel free to continue discussing this within this issue.
