### ISSUE TITLE
Running Script with local import resulting "Cannot find module"

### ISSUE THREAD

**Issue by maxime4000** [nrwl/nx#15521]
### Current Behavior

So I'm looking to run a script file that will seed the database. My seed file is referencing function from an other module which is referencing an other module. To make a quick summary, I'm using Prisma, I generate the PrismaClient, I'm also generating factory function, inserting function and a seed file which will connect relation using previously inserted object. 

So I have those packages: 
- @org/db
  - @org/db/src/index.ts is only exporting the @prisma/client
  - Contains Prisma schema and the generator is call like this `provider = "ts-node ../prisma-generator/src/index.ts"`
- @org/factories
  - export createFakerXYZ()
- @org/seeding
  - Function that will generate data and insert it in the DB.
  - Contain seed.ts file which is the script file I would like to launch 
- @org/prisma-generator
  - The generator use to generate code for @org/factories and @org/seeding
  - Does not import code from an other package

It looks like if the code is in a "lib" package, import between package won't work using `nx:run-commands` or `ts-node`. If it's a "app" package, import will work using serve, but it's not a proper solution... 

### Expected Behavior

So before having this setup, I was working on the generator in a basic repo. Every import was local i.e. (`./index`, `../factories/index`, `@prisma/client`, ...). Launching command like `ts-node src/seed.ts` was all that was need to run the script. Yes it was local, but it was working. Why would it not work when the code is split into multiple package in a Mono-Repo environment ? How could I run the script file without having error of "module not found"?

### GitHub Repo

https://github.com/maxime4000/nx-integrated

### Steps to Reproduce

The repo I made for this issue has 4 libs and 1 app. The 4 libs should replicate my real case and the app was simply to try to execute the same code in an app. 

There is 4 ways to run the same code that I try, but only one work (and that's not the way I want it to work)
1. `ts-node libs/is-script/src/seed.ts`
2. `npx nx run is-script:seed`
3. `npx nx run is-script:build && node dist/libs/is-script/src/seed.js`
4. `npx nx serve web`

Only option 4 will work but you understand that is not acceptable as a solution. I'm not sure if I'm not using the right tools to do what I'm trying to do

### Nx Report

```shell
Node : 16.19.1
   OS   : darwin arm64
   npm  : 8.19.3
   
   nx                      : 15.8.5
   @nrwl/js                : 15.8.5
   @nrwl/jest              : 15.8.5
   @nrwl/linter            : 15.8.5
   @nrwl/workspace         : 15.8.5
   @nrwl/cli               : 15.8.5
   @nrwl/cypress           : 15.8.5
   @nrwl/devkit            : 15.8.5
   @nrwl/eslint-plugin-nx  : 15.8.5
   @nrwl/next              : 15.8.5
   @nrwl/react             : 15.8.5
   @nrwl/tao               : 15.8.5
   @nrwl/webpack           : 15.8.5
   typescript              : 4.9.5
```

### Failure Logs

```shell
ts-node libs/is-script/src/seed.ts
Error: Cannot find module '@nx-integrated/is-even'
Require stack:
- /Users/maxime/Repo/nx-import/nx-integrated-1/libs/is-script/src/seed.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/opt/homebrew/lib/node_modules/ts-node/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._load (node:internal/modules/cjs/loader:866:27)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/Users/maxime/Repo/nx-import/nx-integrated-1/libs/is-script/src/seed.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Module.m._compile (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Object.require.extensions.<computed> [as .ts] (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1458:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/maxime/Repo/nx-import/nx-integrated-1/libs/is-script/src/seed.ts'
  ]
}
```

### Additional Information

Thanks for your time

**Comment by AgentEnder** [comment]
`ts-node` option should work, but you need to provide tsconfig-paths as well. See their docs:

https://typestrong.org/ts-node/docs/paths/

For running built output after a build, the errors expected if not using a bundler. Tsc or swc don't bundle, and the tsconfig paths just tell typescript that node should be able to resolve the built modules. 

When running serve we deal with this for you by patching require, when running directly with node you'll need to make it available somewhere. Generally this is by installing the built libs as node modules with npm link or similar, but I've also had success with updating the dist folder to mimic a node modules directory and using NODE_PATH=dist
