### ISSUE TITLE
Bug: @nrwl/js:tsc Invalid extends in tmp tsConfig - path.relative not being aware of current working dir

### ISSUE THREAD

**Issue by alexandrebodin** [nrwl/nx#15530]
### Current Behavior

When running the tsc executor to build a package, if I run the command from the root directory of the monorepo or the pacakge itself one (root) will work just fine while the other will not transpile anyfile.

I pinpointed the issue here https://github.com/nrwl/nx/blob/master/packages/workspace/src/utilities/buildable-libs-utils.ts#L161. 

where path.relative should make sure that tsConfigPath is an absolute so it is valid weather you run the command from the root or the package folder itself. We can probably join the workspaceRoot here to fix this. https://github.com/nrwl/nx/blob/master/packages/workspace/src/utilities/buildable-libs-utils.ts#L238

Happy to make a PR if that can help move it forward. In the meantime we will just only run the commands from the root folder.

### Expected Behavior

The 2 commands should give the same results

### Steps to Reproduce

1. Create a monorepo
2. Create a project with typescript
3. Add tsc runner following the documentation example
4. run `nx run project:build` from root folder & `nx build` from the project folder
5. One will build the files correctly the other will be a folder with just package.json

### Nx Report

```shell
Node : 16.19.0
   OS   : darwin arm64
   yarn : 1.22.19

   nx               : 15.8.3
   lerna            : 6.5.1
   @nrwl/js         : 15.8.3
   @nrwl/jest       : 15.8.3
   @nrwl/linter     : 15.8.3
   @nrwl/workspace  : 15.8.3
   @nrwl/cli        : 15.8.3
   @nrwl/devkit     : 15.8.3
   @nrwl/tao        : 15.8.3
   typescript       : 4.6.2
```

### Failure Logs

```shell
No failure just invalid behavior
```

**Comment by alexandrebodin** [comment]
Hey 👋  

I would be happy to make a PR if that can help. Can you confirm the issue and would that you would be willing to accept a fix as described in the issue description ?

**Comment by cutiful** [comment]
That path is passed from here:
https://github.com/nrwl/nx/blob/8c9ad0da69b76def41ef1af615d0795272a0b78f/packages/js/src/executors/tsc/tsc.impl.ts#L46-L49

There's a normalized `options` object, in which all paths are absolute. Removing the underscore should fix the issue. The raw `_options` object is also used further down, I'm not sure if that's intentional or a mistake too.
