### ISSUE TITLE
NX 15.8.5 debug error

### ISSUE THREAD

**Issue by janosroska** [nrwl/nx#15536]
### Current Behavior

When trying to debug the application from VSCode, run-one.js throws an error.

### Expected Behavior

The expected functionality would be to be able to debug the application without errors.

### GitHub Repo

https://github.com/janosroska/latest

### Steps to Reproduce

1. create a new nestjs application with NX 15.8.5 or upgrade your repository from NX 13.10.2 to 15.8.5
2. After creation/migration, try debugging the application
3. observe the error in VSCode DEBUG CONSOLE	

### Nx Report

```shell
Node : 16.19.1
   OS   : win32 x64
   npm  : 8.19.3

   nx                      : 15.8.5
   @nrwl/js                : 15.8.5
   @nrwl/jest              : 15.8.5
   @nrwl/linter            : 15.8.5
   @nrwl/workspace         : 15.8.5
   @nrwl/cli               : 15.8.5
   @nrwl/devkit            : 15.8.5
   @nrwl/eslint-plugin-nx  : 15.8.5
   @nrwl/nest              : 15.8.5
   @nrwl/node              : 15.8.5
   @nrwl/tao               : 15.8.5
   @nrwl/webpack           : 15.8.5
   typescript              : 4.9.5
```

### Failure Logs

```shell
C:\Program Files\nodejs\npx.cmd nx serve myapp --inspect .\apps\myapp\src\main.ts
2
Debugger attached.
nx.js run [project][:target][:configuration] [_..]

Run a target for a project
    (e.g., nx run myapp:serve:production).

    You can also use the infix notation to run a target:
    (e.g., nx serve myapp --configuration=production)

    You can skip the use of Nx cache by using the --skip-nx-cache option.

Options:
      --version           Show version number  [boolean]
  -c, --configuration     This is the configuration to use when performing tasks on projects  [string]
      --output-style      Defines how Nx emits outputs tasks logs  [string] [choices: "dynamic", "static", "stream", "stream-without-prefixes", "compact"]
      --exclude           Exclude certain projects from being processed  [string] [default: ""]
      --parallel          Max number of parallel processes [default is 3]  [string]
      --runner            This is the name of the tasks runner configured in nx.json  [string]
      --verbose           Prints additional information about the commands (e.g., stack traces)  [boolean] [default: false]
      --nx-bail           Stop command execution after the first failed task  [boolean] [default: false]
      --nx-ignore-cycles  Ignore cycles in the task graph  [boolean] [default: false]
      --skip-nx-cache     Rerun the tasks even when the results are available in the cache  [boolean] [default: false]
      --project           Target project  [string]

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at calculateDefaultProjectName (d:\NX_BUG_REPROD\latest\node_modules\nx\src\command-line\run-one.js:103:31)
    at parseRunOneOptions (d:\NX_BUG_REPROD\latest\node_modules\nx\src\command-line\run-one.js:58:32)
    at Object.<anonymous> (d:\NX_BUG_REPROD\latest\node_modules\nx\src\command-line\run-one.js:22:22)
    at Generator.next (<anonymous>)
    at fulfilled (d:\NX_BUG_REPROD\latest\node_modules\tslib\tslib.js:164:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2
Waiting for the debugger to disconnect...
```

### Additional Information

The value of the cwd and root variables are different, root starts with a lowercase letter and the cwd with an uppercase. The first character is the drive letter, for ex. "**d**:\NX_BUG_REPROD\latest\", "**D**:\NX_BUG_REPROD\latest\"

The original (13.10.2) code checks whatever the relativeCwd variable is undefined or not. We did not invastigate any other places but probably there are more places where this problem exists in the new (15.8.5) version. 

function calculateDefaultProjectName(cwd, root, projectsConfigurations, nxJsonConfiguration) {
    var _a;
    let relativeCwd = cwd.replace(/\\/g, '/').split(root.replace(/\\/g, '/'))[1];
    relativeCwd = relativeCwd.startsWith('/')
        ? relativeCwd.substring(1)
        : relativeCwd;

**Comment by natrixofficial** [comment]
On windows 10, x64. After migrating NX from 13 to latest (15.8.5), experiencing the same. 
(Windows drive letter casing mismatch problems are annoying)

**Comment by robc123** [comment]
Not 100% sure if this is related, but it feels like it might be similar issue, so added here as comment rather than new issue.

```
Node : 16.19.0
   OS   : win32 x64
   npm  : 8.19.3

   nx                      : 15.8.5
   @nrwl/js                : 15.8.5
   @nrwl/jest              : 15.8.5
   @nrwl/linter            : 15.8.5
   @nrwl/workspace         : 15.8.5
   @nrwl/angular           : 15.8.5
   @nrwl/cli               : 15.8.5
   @nrwl/cypress           : 15.8.5
   @nrwl/devkit            : 15.8.5
   @nrwl/eslint-plugin-nx  : 15.8.5
   @nrwl/nest              : 15.8.5
   @nrwl/node              : 15.8.5
   @nrwl/tao               : 15.8.5
   @nrwl/webpack           : 15.8.5
   typescript              : 4.9.5
```
   ---------------------------------------
   Community plugins:
   @ngrx/effects        : 15.3.0
   @ngrx/entity         : 15.3.0
   @ngrx/router-store   : 15.3.0
   @ngrx/store          : 15.3.0
   @ngrx/eslint-plugin  : 15.3.0
   @ngrx/schematics     : 15.3.0
   @ngrx/store-devtools : 15.3.0
   @twittwer/compodoc   : 1.9.0  

### Node Breakpoint error
Can get debugger to attach to Node and debug console sees the api logger messages, but is failing to link breakpoints.
This works ok in NX 15.5.2

**launch.json**
```
  {
      "type": "node",
      "request": "attach",
      "name": "Attach to Api",
      "sourceMaps": true,
      "port": 9229,
      "localRoot": "${workspaceFolder}",
      "remoteRoot": "${workspaceFolder}",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "outFiles": [
        "${workspaceFolder}/dist/apps/api/**/*.js"
      ]
    },
```
Debug Diagnostics help on "why my breakpoints don't bind":

> ✅ This breakpoint was initially set in:
> 
> C:\d_drive\github\tools-web\apps\api\src\setup\tag.service.ts line 58 column 1
> 
> ❓ We couldn't find a corresponding source location, but found some other files with the same name:
> 
> c:\d_drive\github\tools-web\apps\api\src\setup\tag.service.ts
> If this is the same file, you may need to adjust your build tool to correct the paths.

### Chrome Launch Error
Similar to above but this may also be related to issues I've researched on Chrome version. 
It worked in NX15.5.2 until yesterday - it does not today (hence suspect chrome).

**launch.json**
```
{
      "name": "Launch Chrome",
      "request": "launch",
      "type": "chrome",
      "url": "http://localhost:4200",
      "webRoot": "${workspaceFolder}"
    },
```
In this case the launched browser opens but actually fails to load the angular application (maybe the unrelated chrome error).  navigation manually to http://localhost:4200 is all fine.
Investigation of Debug Diagnostics has a similar path related warning:



> C:\d_drive\github\tools-web\apps\frontend\src\app\projects\+state\project.facade.ts line 1085 column 1
> 
> ❓ We couldn't find a corresponding source location, and didn't find any source with the name project.facade.ts.
> 
> How did you expect this file to be loaded? (If you have a compilation step, you should pick 'sourcemap')
> Loaded in directlyBe parsed from a sourcemap
> Here's some hints that might help you:
> Make sure you have "sourceMap": true in your tsconfig to generate sourcemaps.
> It looks like you narrowed the outFiles in your launch.json. 
> Try removing this: it now defaults to the whole workspace, and overspecifying it can unnecessarily narrow places where we'll resolve sourcemaps.

**Comment by AgentEnder** [comment]
I believe this PR likely fixed the issue with casing that was noted: https://github.com/nrwl/nx/pull/15643

If so, this would be fixed in 15.8.7

**Comment by natrixofficial** [comment]
Hi, 

We have tried with the latest but still can't debug. We have read others' comments of other tickets, and found out how to debug:
https://github.com/nrwl/nx/issues/14708#issuecomment-1457996600

The problem was with the webpack config.

In one sentence: With the latest version (15.8.7) and with the modified webpack.config.js everything works on windows 10 and windows 11. Build, run, debug with WSCode...

**Comment by janosroska** [comment]
Many thx @AgentEnder @natrixofficial
