### ISSUE TITLE
'ProxyZone' not found after migration from 15.1.1 to 15.8.5

### ISSUE THREAD

**Issue by smithpb** [nrwl/nx#15577]
### Current Behavior

After running the migration to 15.8.5, a lot of our unit tests are failing with the error message: "Expected to be running in 'ProxyZone', but it was not found." It points to the loader function on TestbedHarnessEnvironment, but looking into it, the issue seems to be tied to @testing-library/angular. It seemed best to file the issue here since there are multiple libraries are involved.

There are two tests in the demo repo below to illustrate the problem. The test were run with two versions of @testing-library/angular: 10.11.0 and 13.3.0 (current latest).

### Expected Behavior

We expected our tests to continue to pass without error.

### GitHub Repo

https://github.com/smithpb/proxyzone-error

### Steps to Reproduce

1. running `nx test test-app` will return the error we've seen

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.14.0
   OS   : darwin x64
   npm  : 9.3.1
   
   nx                      : 15.8.5
   @nrwl/js                : 15.8.5
   @nrwl/jest              : 15.8.5
   @nrwl/linter            : 15.8.5
   @nrwl/workspace         : 15.8.5
   @nrwl/angular           : 15.8.5
   @nrwl/cli               : 15.8.5
   @nrwl/cypress           : 15.8.5
   @nrwl/devkit            : 15.8.5
   @nrwl/eslint-plugin-nx  : 15.8.5
   @nrwl/tao               : 15.8.5
   @nrwl/webpack           : 15.8.5
   @nrwl/nx-cloud          : 15.1.1
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @testing-library/angular : 13.3.0
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This is an issue related to https://github.com/nrwl/nx/issues/15390. Even though the errors are different, the underlying issue is the same and the solution is to set `"target": "ES2016"` in your `tsconfig.spec.json` file as mentioned in https://github.com/nrwl/nx/issues/15390#issuecomment-1457792176.

For more reference: https://github.com/angular/components/issues/21632#issuecomment-764975917.

We'll add a migration to ensure it's automatically set for projects using `jest-preset-angular`.

**Comment by smithpb** [comment]
Thank you for looking into this and providing a solution. Really appreciate the help.

**Comment by e-oz** [comment]
Angular runs with target ES2022 - I don't understand how you can rely on your tests afterward. The behavior of these targets is very different. You had to adjust your tests, instead, we got this dirty patch, just hiding the real issue under the rug.
