### ISSUE TITLE
Tree doesn't handle moves properly

### ISSUE THREAD

**Issue by willyboy** [nrwl/nx#15576]
### Current Behavior

When using the move generator to move a generated directory, files that exist in a sub-directory that was deleted before a file is created in the sub-directory don't get moved. They disappear into the ether.

### Expected Behavior

When moving a generated directory, all of the files in the directory should be moved.

### Steps to Reproduce

Obviously a very contrived example but still:

1. tree.delete('folder/abc')
2. tree.write('folder/abc/def.txt', 'my text')
3. tree.children('folder')
4. // should be 'abc' but it's an empty array - meanwhile tree.exists('folder/abc/def.txt') is true

### Nx Report

```shell
nx 14.4.3 (but seems to have the same issue on master)
```

### Additional Information

So the issue is in tree.ts and there's a bunch of them.

If you delete a path, it sets the path to "isDeleted" in the recorded changes. To solve this, you would think that you could just set isDeleted to false in the write function when a new file is written to a folder previously deleted. 

That backfires a bit because isDeleted is used to determine if something is a file. So now the tree thinks that this folder is actually a file which means that the "visitNotIgnoredFiles" function that recursively checks folders thinks this path is a file.

To fix that, in the delete function, you can set isDeleted to true ONLY in the case that filePath is a folder. This also makes more sense in the output for a generator because right now, it shows folders and files as deleted (which is weird, just show me that the folder is deleted OR the files that were deleted, not both).

**Comment by willyboy** [comment]
I guess this should really be "tree doesn't handle deleting and adding back directories properly". But the use case came up when moving stuff.

**Comment by AgentEnder** [comment]
This is fixed 🎉 , see #16554
