### ISSUE TITLE
Generate react library with bundler option webpack fails

### ISSUE THREAD

**Issue by rj-wowza** [nrwl/nx#15579]
### Current Behavior

Library generation fails when generating a react library using the option bundler=webpack 

`> NX   Property 'bundler' does not match the schema. 'webpack' should be one of none,vite,rollup.`

### Expected Behavior

Library should generate with webpack bundler. 

### Steps to Reproduce

1. `npx create-nx-workspace@latest my-workspace --preset=react-monorepo --bundler=webpack`
2. `cd my-workspace`
3. `nx g @nrwl/react:lib my-lib --bundler=webpack`

### Nx Report

```shell
Node : 19.7.0
OS   : darwin arm64
npm  : 9.5.0

nx                      : 15.8.5
@nrwl/js                : 15.8.5
@nrwl/jest              : 15.8.5
@nrwl/linter            : 15.8.5
@nrwl/workspace         : 15.8.5
@nrwl/cli               : 15.8.5
@nrwl/cypress           : 15.8.5
@nrwl/devkit            : 15.8.5
@nrwl/eslint-plugin-nx  : 15.8.5
@nrwl/react             : 15.8.5
@nrwl/tao               : 15.8.5
@nrwl/webpack           : 15.8.5
typescript              : 4.9.5
```

### Failure Logs

```shell
>  NX   Property 'bundler' does not match the schema. 'webpack' should be one of none,vite,rollup.
```

### Additional Information

This is the result of following the documentation here: https://nx.dev/packages/webpack

**Comment by mandarini** [comment]
Hi there @rj-wowza ! Thanks for filing an issue. [You cannot generate a React library with `webpack`](https://nx.dev/packages/react/generators/library#bundler). You are right, we must update the documentation!
