### ISSUE TITLE
NX   'assets' is not found in schema 

### ISSUE THREAD

**Issue by josipfrljic** [nrwl/nx#15593]
### Current Behavior

`{
  "name": "playbook",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "nx": "nx",
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test --testTimeout=20000",
    "test:all": "nx run-many --all --silent --target=test --testTimeout=20000",
    "lint": "nx workspace-lint && nx lint",
    "lint:all": "nx run-many --all --silent --target=lint --testTimeout=20000",
    "e2e": "nx e2e",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint": "nx affected:lint",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected": "nx affected",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "update": "nx migrate latest && npm install && nx migrate --run-migrations=migrations.json",
    "workspace-generator": "nx workspace-generator",
    "dep-graph": "nx dep-graph",
    "help": "nx help",
    "my-app": "nx serve my-app --port=4201 --host=0.0.0.0",
    "my-app:build": "nx build my-app ",
    "my-app:build:stats": "nx build my-app --skip-nx-cache -- --memoryLimit=8192 --statsJson",

  },
  "private": true,
  "dependencies": {
    "@date-io/date-fns": "^1.3.13",
    "@emotion/react": "11.10.5",
    "@emotion/styled": "11.10.5",
    "@loadable/component": "5.14.1",
    "@mdx-js/react": "^1.6.21",
    "@mui/lab": "*",
    "@mui/material": "^5.0.3",
    "@mui/x-date-pickers": "^5.0.5",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.7",
    "@svgr/webpack": "^6.5.1",
    "@types/js-cookie": "^2.2.6",
    "cookie-js": "^0.0.1",
    "core-js": "^3.6.5",
    "date-fns": "^2.29.3",
    "deepmerge": "^4.2.2",
    "document-register-element": "1.13.1",
    "fastest-levenshtein": "^1.0.12",
    "i18next": "^19.8.4",
    "js-cookie": "^2.2.1",
    "lz-string": "^1.4.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-i18next": "^11.8.5",
    "react-markdown": "^8.0.5",
    "react-number-format": "^4.7.3",
    "react-quill": "^2.0.0",
    "react-refresh": "^0.14.0",
    "react-remark": "^2.1.0",
    "react-router": "^6.8.0",
    "react-router-dom": "^6.8.0",
    "react-router-native": "^6.8.0",
    "react-test-renderer": "18.2.0",
    "regenerator-runtime": "0.13.7",
    "rehype-slug": "^5.1.0",
    "remark-gfm": "^3.0.1",
    "rxjs": "^6.6.3",
    "tslib": "^2.3.0",
    "video.js": "^7.18.1",
    "webpack": "^5.28.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "15.0.5",
    "@babel/core": "7.9.6",
    "@babel/plugin-proposal-class-properties": "7.8.3",
    "@babel/plugin-proposal-decorators": "7.8.3",
    "@babel/plugin-syntax-dynamic-import": "7.8.3",
    "@babel/plugin-transform-modules-commonjs": "^7.20.11",
    "@babel/plugin-transform-runtime": "7.13.15",
    "@babel/preset-env": "7.9.6",
    "@babel/preset-react": "^7.14.5",
    "@babel/preset-typescript": "7.9.0",
    "@emotion/babel-plugin": "11.10.5",
    "@emotion/babel-preset-css-prop": "11.0.0",
    "@nrwl/cli": "15.8.5",
    "@nrwl/cypress": "15.8.5",
    "@nrwl/eslint-plugin-nx": "15.8.5",
    "@nrwl/jest": "15.8.5",
    "@nrwl/js": "15.8.5",
    "@nrwl/nx-cloud": "15.2.0",
    "@nrwl/react": "15.8.5",
    "@nrwl/vite": "15.8.5",
    "@nrwl/web": "15.8.5",
    "@nrwl/webpack": "15.8.5",
    "@nrwl/workspace": "15.8.5",
    "@testing-library/react": "13.4.0",
    "@types/classnames": "^2.3.1",
    "@types/jest": "29.4.0",
    "@types/loadable__component": "^5.13.4",
    "@types/node": "18.11.9",
    "@types/react": "18.0.25",
    "@types/react-dom": "18.0.9",
    "@types/react-router-dom": "5.3.3",
    "@types/webpack": "4.41.21",
    "@typescript-eslint/eslint-plugin": "5.46.1",
    "@typescript-eslint/parser": "5.46.1",
    "@vitejs/plugin-react": "3.1.0",
    "@vitest/coverage-c8": "0.25.8",
    "@vitest/ui": "0.25.8",
    "babel-jest": "29.4.3",
    "babel-loader": "8.1.0",
    "babel-plugin-parameter-decorator": "1.0.16",
    "babel-plugin-transform-typescript-metadata": "0.3.2",
    "camelcase": "6.2.0",
    "cypress": "5.5.0",
    "dotenv": "10.0.0",
    "eslint": "8.29.0",
    "eslint-config-prettier": "8.6.0",
    "eslint-plugin-cypress": "2.10.3",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-jsx-a11y": "6.6.1",
    "eslint-plugin-react": "7.31.11",
    "eslint-plugin-react-hooks": "4.6.0",
    "eslint-utils": "3.0.0",
    "jest": "29.4.3",
    "jest-environment-jsdom": "29.4.3",
    "jest-fetch-mock": "^3.0.3",
    "jsdom": "~20.0.3",
    "npm-run-all": "4.1.5",
    "nx": "15.8.5",
    "paths.macro": "3.0.1",
    "prettier": "2.2.1",
    "reflect-metadata": "0.1.13",
    "sass": "^1.55.0",
    "ts-jest": "29.0.5",
    "ts-node": "10.9.1",
    "tslint": "6.1.0",
    "typescript": "4.4.3",
    "url-loader": "3.0.0",
    "utility-types": "^3.10.0",
    "vite": "4.1.4",
    "vite-plugin-dts": "1.7.3",
    "vite-plugin-eslint": "1.8.1",
    "vite-tsconfig-paths": "4.0.5",
    "vitest": "0.25.8",
    "webpack-bundle-analyzer": "^4.5.0"
  },
  "resolutions": {
    "terser": "4.8.0"
  }
}
`

`
{
	"name": "my-app",
	"$schema": "../../../../node_modules/nx/schemas/project-schema.json",
	"sourceRoot": "apps/supersport/web/supersport-mobile/src",
	"projectType": "application",
	"targets": {
		"build": {
			"executor": "@nrwl/web:webpack",
			"outputs": ["{options.outputPath}"],
			"dependsOn": [],
			"options": {
				"outputPath": "dist/apps/supersport/web/supersport-mobile",
				"index": "apps/supersport/web/supersport-mobile/src/index.html",
				"main": "apps/supersport/web/supersport-mobile/src/main.tsx",
				"tsConfig": "apps/supersport/web/supersport-mobile/tsconfig.app.json",
				"styles": [],
				"scripts": [],
				"webpackConfig": "./apps/supersport/web/supersport-mobile/webpack.js"
			},
			"configurations": {
				"production": {
					"fileReplacements": [
						{
							"replace": "apps/my-app/src/environments/environment.ts",
							"with": "apps/my-app/src/environments/environment.prod.ts"
						}
					],
					"optimization": true,
					"outputHashing": "all",
					"sourceMap": false,
					"extractCss": true,
					"namedChunks": false,
					"extractLicenses": true,
					"vendorChunk": false,
					"budgets": [
						{
							"type": "initial",
							"maximumWarning": "2mb",
							"maximumError": "5mb"
						}
					]
				}
			}
		},
		"serve": {
			"executor": "@nrwl/web:dev-server",
			"options": {
				"buildTarget": "my-app:build",
				"assets": [
					"apps/supersport/web/supersport-mobile/src/favicon.ico",
					"apps/supersport/web/supersport-mobile/src/assets",
					{
						"glob": "**/*.@(json)",
						"input": "libs/core/playbook-resources/src/locales/sbk",
						"output": "./assets/locales/sbk"
					},
					{
						"glob": "**/*.@(jpg|png|svg)",
						"input": "libs/core/playbook-resources/src/themes",
						"output": "./themes"
					},
					{
						"input": "libs/core/playbook-resources/src/assets/images",
						"glob": "**/*.@(jpg|png|svg|jpeg)",
						"output": "assets/playbook-images"
					},
					{
						"glob": "**/*.@(ttf|otf|woff|woff2|eot)",
						"input": "libs/core/playbook-resources/src/themes/supersport/assets/fonts",
						"output": "./"
					},
					{
						"glob": "**/*.@(md)",
						"input": "libs/core/playbook-resources/src/help/markdown",
						"output": "./assets/markdown"
					},
					{
						"glob": "**/*.@(jpg|png|svg|json)",
						"input": "libs/core/playbook-resources/src/bonuses",
						"output": "./assets/bonuses"
					},
					{
						"glob": "**/*.@(jpg|png|svg|json)",
						"input": "libs/core/playbook-resources/src/community",
						"output": "./assets/community"
					}
				]
			},
			"configurations": {
				"production": {
					"buildTarget": "my-app:build:production"
				},
				"development": {
					"buildTarget": "my-app:build:development"
				}
			},
			"defaultConfiguration": "development"
		},
		"lint": {
			"executor": "@nrwl/linter:eslint",
			"options": {
				"lintFilePatterns": [
					"apps/supersport/web/supersport-mobile/**/*.{ts,tsx,js,jsx}"
				]
			}
		},
	
	"tags": []
}

`

### Expected Behavior

On previous version (15.3), i use workspace.json and everything works fine, after i  made update at nx15.8.5, and split worspace.json (in migration)  to project.json , my app doesn't work anymore

### Steps to Reproduce

- Create app with nx15.3 version with workspace.json setup 
- migrate to nx15.8.5

### Nx Report

```shell
NX  The current directory isn't part of an Nx workspace.

  To create a workspace run:
  npx create-nx-workspace@latest <workspace name>
```

### Failure Logs

```shell
nx serve smy-app --port=4201 --host=0.0.0.0



> nx run my-app:serve:development --port=4201 --host=0.0.0.0


 >  NX   'assets' is not found in schema





 >  NX   Running target serve for project  my-app failed

   Failed tasks:

   - my-app:serve:development


or 


 nx run supersport-web-mobile:build


 >  NX   Cannot destructure property 'options' of 'undefined' as it is undefined.

   Pass --verbose to see the stacktrace.
```

**Comment by 4javier** [comment]
It would be better if you'd format your message and add syntax highlighting.
In any case, `assets` is a property of `build` target, not `serve`.
You got to move that property to the correct block.
