### ISSUE TITLE
`updateProjectConfiguration` fail with package.json configured projects

### ISSUE THREAD

**Issue by edbzn** [nrwl/nx#15595]
### Current Behavior

In the context of a generator, when projects are configured using package.json instead of project.json file, the devkit util function `updateProjectConfiguration` fails with the following error: 

```
Cannot update project [name] at [path]. It doesn't exist or use package.json configuration.
```

### Expected Behavior

I'm expecting this function to handle package.json based projects. Otherwise, what is the recommended way to handle this?

Thanks in advance.

### Steps to Reproduce

1. setup a fresh monorepo with package.json projects based (no project.json) 
2. try to use `updateProjectConfiguration` to update those projects

### Nx Report

```shell
Node : 16.18.1
   OS   : linux x64
   yarn : 3.4.1
   
   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 15.6.3
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.9.5
   ---------------------------------------
   Local workspace plugins:
         @jscutlery/semver
   ---------------------------------------
   Community plugins:
         ngx-deploy-npm: 5.2.0
```

### Additional Information

Related issue https://github.com/jscutlery/semver/issues/634.

**Comment by AgentEnder** [comment]
Package json based projects aren't handled by update project configuration, it is meant for project.json based projects only. If you want to support them, currently you'd need to do so with updateJson or similar.
