### ISSUE TITLE
affected:build with multiple but different languages per app

### ISSUE THREAD

**Issue by sroettering** [nrwl/nx#1559]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

I want to migrate an existing vanilla angular multi project setup to NX and was not able to find any solution for our specific i18n usecase.
Besides some libraries we have multiple apps that use angular's built in i18n features and are built in different languages. However, not every app is built for every language.

A little example:
App1 is built for english and german
App2 is built for german and dutch
App3 is built for french and ukranian

Now we want to leverage the `affected:build` command in CI to speed up builds. Of course, we don't want / can't build all Apps in all languagees.
Are there any configuration options which would achieve this?

**Comment by vsavkin** [comment]
@sroettering what you want is to define another target for every app called `build-with-i18n`. That target can invoke build with whatever languages necessary. The target defined for App1 can look like this: 

````
projects: {
  app1: {
    architect: {
      "build-with-i18n": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "commands": [
              {
                "command": "ng build build --i81n-locale=en"
              },
              {
                "command": "ng build build --i81n-locale=ge"
              }
            ]
          }
        }
    }
  } 
}

```

You can then do:

```
yarn affected --target=build-with-i18n
```

**Comment by sroettering** [comment]
Thank you, I will try that!
