### ISSUE TITLE
npx create-nx-workspace@15.8.5 is not adding typescript as dev dep in package.json

### ISSUE THREAD

**Issue by iKrishnaSahu** [nrwl/nx#15598]
### Current Behavior

`npx create-nx-workspace@15.8.5` is not adding typescript as dev dep in package.json

If it was removed intentionally, what was the reason behind it?

sample package.json - 

```
{
  "name": "test-ws-nx1585",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
  },
  "private": true,
  "dependencies": {
  },
  "devDependencies": {
    "nx": "15.8.5",
    "@nrwl/workspace": "15.8.5",
    "prettier": "^2.6.2"
  }
}
```

### Expected Behavior

It should add `typescript` as dev dep

### Steps to Reproduce

1. Run `npx create-nx-workspace@15.8.5` to create a new nx workspace
2. Open package.json and check the `devDependancies` section

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.19.0
   OS   : win32 x64
   npm  : 8.19.3
   
   nx               : 15.8.5
   @nrwl/js         : 15.8.5
   @nrwl/jest       : 15.8.5
   @nrwl/linter     : 15.8.5
   @nrwl/workspace  : 15.8.5
   @nrwl/angular    : 15.8.5
   @nrwl/cli        : 15.8.5
   @nrwl/cypress    : 15.8.5
   @nrwl/devkit     : 15.8.5
   @nrwl/tao        : 15.8.5
   @nrwl/webpack    : 15.8.5
```

**Comment by iKrishnaSahu** [comment]
Because of this issue, `nx g @nrwl/angular:ng-add` is breaking.

Steps to reproduce - 
- Create new ws - `npx create-nx-workspace@15.8.5`
- Run `npm i @nrwl/angular`
- Run `nx g @nrwl/angular:ng-add`

Error - 

```
C:\Projects\projects\workspaces2\5.10\test-ws-nx1585>nx g @nrwl/angular:ng-add  

>  NX  Generating @nrwl/angular:ng-add


 >  NX   Cannot find module 'typescript'

```

**Comment by mandarini** [comment]
I think this is fixed in the latest version. I will be closing this, but feel free to reopen if it persists!
