### ISSUE TITLE
Duplicate dist outputs for nodejs

### ISSUE THREAD

**Issue by kdawgwilk** [nrwl/nx#15604]
### Current Behavior

fresh node-server workspace build target produces duplicate outputs

<img width="143" alt="image" src="https://user-images.githubusercontent.com/7799267/224375463-7b9f83da-518d-4b6d-b022-172333cd6a34.png">

### Expected Behavior

build results should not be duplicated

### Steps to Reproduce

1. Create fresh node-server workspace
2. nx build

### Nx Report

```shell
Node : 16.14.0
   OS   : darwin arm64
   npm  : 8.3.1
   
   nx                      : 15.8.5
   @nrwl/js                : 15.8.5
   @nrwl/jest              : 15.8.5
   @nrwl/linter            : 15.8.5
   @nrwl/workspace         : 15.8.5
   @nrwl/cli               : 15.8.5
   @nrwl/devkit            : 15.8.5
   @nrwl/esbuild           : 15.8.5
   @nrwl/eslint-plugin-nx  : 15.8.5
   @nrwl/node              : 15.8.5
   @nrwl/tao               : 15.8.5
   @nrwl/webpack           : 15.8.5
   typescript              : 4.9.5
```

**Comment by kdawgwilk** [comment]
Looks like the top level `server.js` is just a wrapper around the app itself?  it seems like we should at least name that top level file something different to make that more clear?

**Comment by PointSingularity** [comment]
Have the same problem, generating a new node application (with express) with esbuild produces the same result.
It creates this wrapper file, with an additional folder, but also the package.json created has no dependencies.

If the same application created with the webpack bundler, no wrapper file and folder are created, and the package.json is filled with the proper dependencies.
