### ISSUE TITLE
@swc/helpers is added as a dependency instead of a devDependency

### ISSUE THREAD

**Issue by ZackTherrien** [nrwl/nx#15607]
### Current Behavior

When installing SWC from generating a new Nx package with the SWC compiler option selected it auto installs @swc/cli, @wwc/core, @swc/jest in its devDependencies, but @swc/helpers is in the dependencies.

### Expected Behavior

Using SWC as the compiler option to download its helpers in the devDependencies (cli, core, jest were downloaded as such)

### Steps to Reproduce

1. make a new Nx package (when you dont have swc previously installed)
2. select swc for compiler
3. hit generate
4. inspect package.json

### Nx Report

```shell
Node : 19.7.0
   OS   : darwin x64
   yarn : 1.22.19
   
   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/esbuild           : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/node              : 15.7.2
   @nrwl/react             : 15.7.2
   @nrwl/rollup            : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/web               : 15.7.2
   @nrwl/webpack           : 15.7.2
   typescript              : 4.9.5
```

**Comment by AgentEnder** [comment]
@swc/helpers is a runtime dependency, similar to tslib. See: https://swc.rs/docs/configuration/compilation#jscexternalhelpers

**Comment by ZackTherrien** [comment]
> You must add @swc/helpers as a dependency in addition to @swc/core.

@swc/core is added as a dev dependency, is this OK?

**Comment by AgentEnder** [comment]
Yes, @swc/core is a build time dep
