### ISSUE TITLE
Nx Can't find version 8 on npmjs

### ISSUE THREAD

**Issue by tieppt** [nrwl/nx#1560]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Can install Nx version 8 by npmjs

## Current Behavior

I can't install v8 by running `npm i @nrwl/nx@~8.2.0` even the release tab said the latest version is 8.2.0
<img width="1326" alt="Screen Shot 2019-07-05 at 5 50 01 PM" src="https://user-images.githubusercontent.com/7151365/60718053-d9fc4e80-9f4d-11e9-9458-f5ae117165a0.png">
<img width="1050" alt="Screen Shot 2019-07-05 at 5 54 14 PM" src="https://user-images.githubusercontent.com/7151365/60718086-f13b3c00-9f4d-11e9-9945-7d797cc6048a.png">

**Comment by vsavkin** [comment]
Hi there. We repackaged Nx to make it more pluggable. `@nrwl/angular` is the new package that contains all the utilities that have been provided by `@nrwl/nx` before. If you run `ng update` on the existing repo, it should remove `@nrwl/nx` and update all your files to import from `@nrwl/angular`.

**Comment by tieppt** [comment]
thank @vsavkin
