### ISSUE TITLE
@nrwl/jest:jest - how to run test with custom webpack config

### ISSUE THREAD

**Issue by hoang-innomizetech** [nrwl/nx#1561]
We are able to build and serve angular with custom webpack config using https://github.com/meltedspark/angular-builders/tree/7.x.x/packages/custom-webpack but we ran into an issue when running jest test with @nrwl/jest:jest. 

How can we update @nrwl/jest:jest builder to run custom webpack configuration when running testing?

**Comment by vsavkin** [comment]
@FrozenPandaz could you reply:

**Comment by FrozenPandaz** [comment]
@hoang-innomizetech 

I'm afraid webpack isn't used when running the jest tests. Is there something specific that does not work?

**Comment by hoang-innomizetech** [comment]
@FrozenPandaz Yeah, the `@nrwl/jest:jest` builder doesn't support any additional properties to allow us to specify a custom webpack configuration, so it is ignored. So I am asking whether that builder can support, if not do you have any recommendation?

**Comment by FrozenPandaz** [comment]
Sorry I may have been unclear the first time. Normally, jest runs do not use webpack at all under the hood. So specifying a custom webpack config would not be used anywhere. Jest has a separate resolver and pre processor configuration completely unrelated to webpack.

If you provide more details about what specifically you are trying to achieve, I can provide more assistance. 

This link may also clarify things:
https://jestjs.io/docs/en/webpack#a-webpack-example

**Comment by FrozenPandaz** [comment]
I hope that clarified things. I'm going to close this issue for now.

If you have more questions feel free to reopen.
