### ISSUE TITLE
nx 15.8  after yarn create nx-workspace test I selected "Standalone Angular app" does not work... still ngModule

### ISSUE THREAD

**Issue by koempf** [nrwl/nx#15624]
### Current Behavior

after yarn create nx-workspace test  I selected "Standalone Angular app"... but it does not work... it generates not a standalone App.

### Expected Behavior

after yarn create nx-workspace test  and select "Standalone Angular app", I want a standalone app :-)

### Steps to Reproduce

1.yarn create nx-workspace test
2. select "Standalone Angular app"

### Nx Report

```shell
yarn create nx-workspace test
```

**Comment by StalkAltan** [comment]
Hi, this is a misunderstanding. "Standalone" for Nx refers to a single project at the root of the workspace, rather than multiple projects. You can see more information here: https://nx.dev/getting-started/angular-standalone-tutorial

**Comment by koempf** [comment]
Hi there,
thanks for your reply :-) but when I choose "Standalone Angular app" in the
wizard... the wizard don't ask me if I want to create a "standalone
component Angular app"... this worked in earlier versions.
best regards from Steffen

Am Mo., 13. März 2023 um 03:13 Uhr schrieb Altan Stalker <
***@***.***>:
