### ISSUE TITLE
--preset ts does not do what it is supposed to

### ISSUE THREAD

**Issue by DominicGBauer** [nrwl/nx#15621]
### Current Behavior

When I run `npx create-nx-workspace@latest myorg --preset=ts` it does not generate the files it should for ts as it stipulates in the read me https://nx.dev/getting-started/integrated-repo-tutorial

### Expected Behavior

I expect it to follow this folder structure 

```
myorg/
├── packages/
├── tools/
├── nx.json
├── package.json
├── README.md
└── tsconfig.base.json
```

there is no `tsconfig.base.json`

### Steps to Reproduce

1. Run `npx create-nx-workspace@latest myorg --preset=ts` and you will see what I mean

### Nx Report

```shell
There is no report
```

### Additional Information

Here's the command that shows what I mean, note there is no tsconfig.base.json. 

<img width="985" alt="image" src="https://user-images.githubusercontent.com/46312751/224544461-f4f3500b-8b11-40f6-8950-ae202bf53b3a.png">

Also there is no `typescript` installed in `package.json`:

```
{
  "name": "myorg",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {},
  "private": true,
  "dependencies": {},
  "devDependencies": {
    "@nrwl/js": "15.8.6",
    "@nrwl/workspace": "15.8.6",
    "nx": "15.8.6",
    "prettier": "^2.6.2"
  }
}
```

**Note that when I run this using nx version 15.7.2 it does create the `tsconfig.base.json` and installs `typescript`**

**Comment by mandarini** [comment]
Possibly related: https://github.com/nrwl/nx/issues/15598

**Comment by DominicGBauer** [comment]
@AgentEnder why does this need more info?

**Comment by mandarini** [comment]
I'll be closing this since it seems to be fixed in the latest version. Feel free to ping me to reopen if issue persists!
