### ISSUE TITLE
nx does not find projects with `__something__` in folder name

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [nrwl/nx#15625]
### Current Behavior

After the removal of the workspace.json it seems that nx now has problems finding projects that have `__` at the start of the name and at the end of their name, or maybe other characters are excluded also. The project.json name doesn't seem to be effected though.
```
_generated // works
__generated // works
__generated_ // works
__generated__ // doesn't work
__generated___ //works
```

### Expected Behavior

1. project resolution should work independent of the folder names
2. there should be a schema of what folder names are allowed
3. there should be a warning of some kind that there is a project with a folder name not allowed

### Steps to Reproduce

1. name a libs folder with `__generated__`
2. nx show projects

### Nx Report

```shell
Node : 16.14.2
   OS   : win32 x64
   pnpm : 7.27.0

   nx                      : 15.8.6
   @nrwl/js                : 15.8.6
   @nrwl/jest              : 15.8.6
   @nrwl/linter            : 15.8.6
   @nrwl/workspace         : 15.8.6
   @nrwl/cli               : 15.8.6
   @nrwl/cypress           : 15.8.6
   @nrwl/devkit            : 15.8.6
   @nrwl/eslint-plugin-nx  : 15.8.6
   @nrwl/nest              : 15.8.6
   @nrwl/node              : 15.8.6
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @jscutlery/semver : 2.30.1
```

### Additional Information

This bug was introduced with version 15.8.0-beta.7

**Comment by sschneider-ihre-pvs** [comment]
Any progress on this issue?

**Comment by sschneider-ihre-pvs** [comment]
Still an issue in 16.3.2

**Comment by sschneider-ihre-pvs** [comment]
might be related to #17426 since there is also a problem with resolution of the path in windows.

**Comment by sschneider-ihre-pvs** [comment]
Ok the error is even more specific. the folder with in the `libs/*` sub folder structure cannot start with a `g`

**Comment by sschneider-ihre-pvs** [comment]
`libs/shared/rgraphql-schema-types`

![image](https://github.com/nrwl/nx/assets/86342787/437c6f08-5e71-4b13-ade7-59b02c2b5e79)

`libs/shared/rgraphql-schema-types`

![image](https://github.com/nrwl/nx/assets/86342787/4511e596-ef32-4418-bd2f-c4aaf05a930d)

**Comment by sschneider-ihre-pvs** [comment]
Additionally, when I rename the folder I have to execute `nx reset` too.

**Comment by sschneider-ihre-pvs** [comment]
guess what, after trying to do the same thing again with a different name, I am unable to reproduce a working example, now again that project fails to be found and I still have no idea why. and why only that single one.

**Comment by sschneider-ihre-pvs** [comment]
So what I did  is:
1. Move libs/shared/__generated__ to libs/shared/graphql-schema-types in nx 15.6.3
2. Migrated to latest nx
3. run nx show projects, project does not show
4. Renamed the folder in the explorer to libs/shared/rgraphql-schema-types
5. run nx show projects, project does show
6. Renamed the folder in the explorer to libs/shared/graphql-schema-types
7. run nx show projects, project does not show

**Comment by sschneider-ihre-pvs** [comment]
Ok I think I found the error.
https://github.com/nrwl/nx/blob/6dd652095c07cf26635b5e583249b0bdaa400902/packages/nx/src/utils/ignore.ts#L17
This change seem to have worked in the way that the actually .gitignore is now regarded in the acquiring of projects which before didn't seem to work.
I generate files in the project which should be ignored but not the project itself, but since it showed up in the .gitignore since 15.8.0-beta.7 that seems to be an issue.
is it possible to tell nx not to ignore any stuff from .gitignore?

**Comment by hinogi** [comment]
so I guess it is a bug because according to 
https://nx.dev/concepts/affected#ignoring-files-from-affected-commands

affected should ignore those but not the graph builder @AgentEnder

**Comment by AgentEnder** [comment]
Hey @hinogi 👋, I'm going to close this out. We have made the decision that projects should never come from files listed in .gitignore, or .nxignore. You may be able to get around this by adding `!path/to/some/__project__` in .nxignore.

**Comment by hinogi** [comment]
Fine with me, I removed all references from the gitignore just in case :D So it works for me. I guess I have to fine grain the glob a bit better.
