### ISSUE TITLE
Empty object in the Http options causes the application to be unreachable

### ISSUE THREAD

**Issue by pascal-klesse** [nrwl/nx#15635]
### Current Behavior

By passing an empty object the application is not accessible. Reponse is: Error Empty Reponse.

`app = await NestFactory.create(AppModule, {});`

### Expected Behavior

Application is accessible and no http options will set.

### Steps to Reproduce

1. create app with empty object for options

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.14.1
   OS   : darwin arm64
   npm  : 9.3.1
   
   nx                      : 15.7.2
   @nrwl/jest              : 15.8.5
   @nrwl/linter            : 15.8.5
   @nrwl/workspace         : 15.8.5
   @nrwl/angular           : 15.8.5
   @nrwl/cli               : 15.8.5
   @nrwl/cypress           : 15.8.5
   @nrwl/devkit            : 15.8.5
   @nrwl/eslint-plugin-nx  : 15.8.5
   @nrwl/js                : 15.8.5
   @nrwl/nest              : 15.8.5
   @nrwl/node              : 15.8.5
   @nrwl/tao               : 15.7.2
   @nrwl/webpack           : 15.8.5
   typescript              : 4.8.4
   ---------------------------------------
   Community plugins:
   apollo-angular : 4.2.1
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/jest@15.8.5
     - @nrwl/linter@15.8.5
     - @nrwl/workspace@15.8.5
     - @nrwl/angular@15.8.5
     - @nrwl/cli@15.8.5
     - @nrwl/cypress@15.8.5
     - @nrwl/devkit@15.8.5
     - @nrwl/eslint-plugin-nx@15.8.5
     - @nrwl/js@15.8.5
     - @nrwl/nest@15.8.5
     - @nrwl/node@15.8.5
     - @nrwl/webpack@15.8.5
```

### Additional Information

Workaround at the moment is:
` let app;
  if (ssl) {
    app = await NestFactory.create(AppModule, httpsOptions);
  } else {
    app = await NestFactory.create(AppModule);
  }`

**Comment by AgentEnder** [comment]
Hey @pascal-klesse , it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.
