### ISSUE TITLE
generate command JavaScript override not working

### ISSUE THREAD

**Issue by manjunath-teachmint** [nrwl/nx#15641]
### Current Behavior

`npx create-nx-workspace my-app --js `  is not supporting javascript. creates workspace with typescript

### Expected Behavior

npx generate to create the workspace with JavaScript instead of TypeScript

### Steps to Reproduce

simply pass --js to any generate command

### Nx Report

```shell
NA
```

**Comment by AgentEnder** [comment]
--js is only supported for certain generators, what preset are you using?
