### ISSUE TITLE
Allow custom location create-nx-workspace - tmpDir forbidden by IT Admin

### ISSUE THREAD

**Issue by ebeltran1981** [nrwl/nx#1564]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

I know this is more like a feature, but for me is a bug 😢 

When run `npx create-nx-workspace myworkspace` should create the workspace.

## Current Behavior

The organization I work for has a global policy, that wont be changed, to block any executable from the `$USER\AppData` folder. This is the error I am getting:

![image](https://user-images.githubusercontent.com/1435275/60730545-6a696d80-9f13-11e9-81fe-eef638fbccf1.png)

**Comment by vsavkin** [comment]
Would you like to contribute a PR implementing this change?

You need to add tmpDir to 

```
const parsedArgs = yargsParser(process.argv, {
  string: ['directory'],
  boolean: ['help']
});
```

in create-nx-workspace.ts.

**Comment by mehrad-rafigh** [comment]
@ebeltran1981 would adding the --directory flag help you? The reason I am asking is the PR I am working on :)

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.
