### ISSUE TITLE
Make current library buildable

### ISSUE THREAD

**Issue by anastasia-anisimova** [nrwl/nx#15652]
There is nx library generator option (--buildable) but this is only for new library
It would be nice if nx can make current library buildable

**Comment by mandarini** [comment]
Hi there @anastasia-anisimova ! Thanks for filing a feature request!

If you have a React or JS library, you can actually use the [`@nx/vite:configuration` generator](https://nx.dev/nx-api/vite/generators/configuration) and make your library buildable.

There are no plans for a more generalized generator, but let me know if that would work for you! Thank you very much for creating this feature request, and I hope what I suggested helps you!
