### ISSUE TITLE
A utility to get Module Federation config 

### ISSUE THREAD

**Issue by fyodorovandrei** [nrwl/nx#15667]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
I am currently [working](https://github.com/module-federation/universe/pull/598) on implementing a Storybook addon that supports Module Federation. In order to complete the pull request, I need to create two React Module Federation apps using Nx.

To achieve this, I have started to create two apps using the command `nx g @nrwl/react:host react-storybook --remotes=react-remote-ui` and have added Storybook to `react-storybook`. However, I am encountering a problem with extracting the Module Federation config from `withModuleFederation` and changing the `library` config.

I would appreciate any suggestions or solutions for resolving these issues, as they are critical for completing my PR.

Thank you for your help!

**Comment by Coly010** [comment]
It should be possible to access the ModuleFederationPlugin by doing something like this in the webpackConfig

```ts
module.exports = async (wco) => {
  const wmf = await withModuleFederation(config);
  const webpackConfig = wmf({
    ...wco,
  });
  // do something with webpackConfig to change ModuleFederationPlugin
};
```

**Comment by fyodorovandrei** [comment]
###  Configuration of the addon will be in this way

In file `./storybook/main.js`:
```js
const moduleFederationConfig = {
    // Module Federation config
};

const storybookConfig = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    // other addons,
    {
      name: "@module-federation/storybook-addon",
      options: {
        moduleFederationConfig // <- pass to the addon MF config
      }
    }
  ],
  "framework": "@storybook/react",
  "core": {
    "builder": "@storybook/builder-webpack5" // is required webpack 5 builder
  }
};
module.exports = storybookConfig;
```

@Coly010  Your example can be applied only for the `webpack.config.js` file. But I'm asking a utility to extract the MF config and pass it to the addon. I have a hunch that won't be possible because `@nrwl/react:module-federation-dev-server` also update webpack config to support library type module:
```js
new ModuleFederationPlugin({
      // ...
      library: {
        type: "module"
      },
     //...
    })
```

**Comment by fyodorovandrei** [comment]
> 

![image](https://user-images.githubusercontent.com/46130932/226738105-b08edf72-9d28-48fb-b302-a8f9eb6d18a9.png)

Also, I tried to update webpack but I got this error @Coly010

**Comment by Coly010** [comment]
I need to have a deep think about this.

We've intentionally abstracted away the config that needs to be configured for the ModuleFederationPlugin.

I don't overly like the idea of allowing someone to pass in their own configuration for that, because there's a strong chance it will break as our executors will not be able to account for it fully. 

There's a possibility that I could do something that returns the final MFConfig from `withModuleFederation` if a certain flag is passed in, but that config will exist in the webpack.config.js file. Having some way of referencing that in the storybook's main.js file could get tricky.

Can the `@module-federation/storybook-addon` use our `withModuleFederation` function?

Then the `main.js` setup could be something like:

```
const nxMFConfig = require('apps/my-app/module-federation.config');
"addons": [
    // other addons,
    {
      name: "@module-federation/storybook-addon",
      options: {
        useNx: true,
        nxMfConfig
      }
    }
  ],
```

**Comment by Coly010** [comment]
@fyodorovandrei I have a workaround that you might be able to use?

```
const { withModuleFederation } = require('@nrwl/angular/module-federation');
const ModuleFederationPlugin = require('webpack/lib/container/ModuleFederationPlugin');
const config = require('./module-federation.config');
module.exports = async (wco) => {
  const wmf = await withModuleFederation(config);
  const conf = wmf({ ...wco });

  for (const plugin of conf.plugins) {
    if (plugin instanceof ModuleFederationPlugin) {
      // plugin.options is the ModuleFederation Config
      // If you need to change the library type, you can by doing this.
      // But I can't guarantee that the rest of the plugin will work
      plugin._options.library = { type: 'var' };
    }
  }
  return conf;
};

```

**Comment by fyodorovandrei** [comment]
@Coly010 Yes. I have made some progress. I added some fixes in utils `withWeb()` to have a working example.

 Now I don't know how to fix this issue:

![image](https://user-images.githubusercontent.com/46130932/230591264-098cba96-f993-4998-b960-e4dd768df9ae.png)

**Comment by fyodorovandrei** [comment]
@Coly010 I can close this issue because I found another way to fix my problem.
