### ISSUE TITLE
How To Get Projects & Paths Without Workspace JSON

### ISSUE THREAD

**Issue by enchorb** [nrwl/nx#15675]
We were using the `workspace.json` file in various internal helper libraries, however with its removal is there a way to get a list of all projects and their path similar to what was in the `workpace.json`. Was looking into the devkit but can't seem to generate it.

**Comment by enchorb** [comment]
Doing this at the moment as a workaround, not sure if there is a more efficient/recommended way

```
import { workspaceLayout } from '@nrwl/devkit';
import { sync } from 'glob';
import { readFileSync, statSync } from 'fs';

 const { appsDir } = workspaceLayout();

  const workspace = {};
  sync(`${appsDir}/**/project.json`, { strict: false }).filter((filePath) => {
    if (statSync(filePath).isFile() && !filePath.includes('e2e')) {
      const project = JSON.parse(readFileSync(filePath, 'utf8'));
      workspace[project.name] = filePath.replace('/project.json', '');
    }
  });
```

**Comment by AgentEnder** [comment]
You should use the project graph directly in most cases, via `createProjectGraphAsync()`. The nodes on the graph represent projects.
