### ISSUE TITLE
eslint error for every import of node modules

### ISSUE THREAD

**Issue by dgesteves** [nrwl/nx#15690]
### Current Behavior

When I try to import any package from node_modules I get this eslint error: 
`ESLint: Projects should use relative imports to import from other files within the same project. Use "./path/to/file" instead of import from ".....`

`import { v4 as uuid } from 'uuid';`

### Expected Behavior

I want to be able to import packages from node_modules without having to use a relative path like `node_modules/package`.
Also for this uuid example since I am using a typescript, the relative path will not work because types are in another package.

### Steps to Reproduce

1. just try to import any package from node modules.

### Nx Report

```shell
Node : 16.19.1
   OS   : darwin arm64
   npm  : 8.19.3
   
   nx                      : 15.8.6
   @nrwl/js                : 15.8.6
   @nrwl/linter            : 15.8.6
   @nrwl/workspace         : 15.8.6
   @nrwl/cli               : 15.8.6
   @nrwl/cypress           : 15.8.6
   @nrwl/devkit            : 15.8.6
   @nrwl/eslint-plugin-nx  : 15.8.6
   @nrwl/react             : 15.8.6
   @nrwl/tao               : 15.8.6
   @nrwl/vite              : 15.8.6
   typescript              : 4.9.5
```

### Failure Logs

```shell
ESLint: Projects should use relative imports to import from other files within the same project. Use "./path/to/file" instead of import from "uuid"(@nrwl/nx/enforce-module-boundaries)
```

**Comment by meeroslav** [comment]
I could not reproduce this. Can you please provide a minimal repo?

**Comment by ewaff** [comment]
I am also experiencing this issue. Here is a minimal example. I put together a basic react library project that tries to import classnames in the default component that it generates. 

https://github.com/ewaff/node_nx_issue

Here is my NX Report:

`>  NX  Unable to locate swc-node or ts-node. Nx will be unable to run local ts files without transpiling.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node : 16.9.1
   OS   : darwin x64
   npm  : 7.21.1
   
   nx                      : 15.8.7
   @nrwl/js                : 15.8.7
   @nrwl/linter            : 15.8.7
   @nrwl/workspace         : 15.8.7
   @nrwl/cli               : 15.8.7
   @nrwl/devkit            : 15.8.7
   @nrwl/eslint-plugin-nx  : 15.8.7
   @nrwl/react             : 15.8.7
   @nrwl/tao               : 15.8.7
   @nrwl/vite              : 15.8.7
   typescript              : 4.9.5`

**Comment by ewaff** [comment]
The error I see is: 

Projects should use relative imports to import from other files within the same project. Use "./path/to/file" instead of import from "classnames" eslint@nrwl/nx/enforce-module-boundaries

**Comment by ewaff** [comment]
I tested the same setup on 15.5.2 and it works as expected: 

https://github.com/ewaff/nx_node_issue_15.5.2

` >  NX   Report complete - copy this into the issue template

   Node : 16.9.1
   OS   : darwin x64
   npm  : 7.21.1
   
   nx : 15.5.2
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.8.7
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : 15.8.7
   @nrwl/linter : 15.8.7
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.8.7
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.5.2
   @nrwl/vite : 15.8.7
   typescript : 4.9.5
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
`

**Comment by meeroslav** [comment]
Surprisingly enough, I could not reproduce the error on your repo @ewaff:
![Screenshot 2023-03-27 at 11 29 05](https://user-images.githubusercontent.com/881612/227901485-c5c7bfee-b9c4-4fdc-9ceb-a4a5a689d4ed.png)

Can you try to:
- remove node_modules completely (potentially also run `npm cache clean --force`) 
- re-install dependencies again
- see if the error is still there

I tried with both Node v16 and v18.

On a side note, the `classnames` package you are importing in the `test-lib.tsx` does not exist in `package.json` nor the lock file. Installing it via `npm i -D classnames` makes no difference to lint output though.
