### ISSUE TITLE
Picking version of Angular LTS when running create-nx-workspace --interactive

### ISSUE THREAD

**Issue by tbogard** [nrwl/nx#15718]
## Description
It would be nice that when your run `npx create-nx-workspace --interactive` that you were able to pick the version of Angular in case you pick either standalone Angular or integrated monorepo.

## Motivation
Currently, at my work, they haven't declared Angular 15 to be ok for work, So I can't use the latest updates of Nx in new projects.

## Suggested Implementation
by using `--interactive` in `npx create-nx-worspace`, by either creating a standalone angular application or an integrated monorepo (by picking angular) you should be able to pick what LTS you want to work with.

## Alternate Implementations
N/A

**Comment by AgentEnder** [comment]
Hey @tbogard! For this behavior you should be able to initialize a new v14 workspace with Angular CLI, and then run `nx init` to add Nx to it and keep the version. We aren't planning to add support for creating new workspaces with the latest versions of Nx, but older versions of target frameworks as it would increase the maintenance burden of LTS support by quite a bit.
