### ISSUE TITLE
Implement custom module federation config path in angular/src/builders/utilities/module-federation.ts

### ISSUE THREAD

**Issue by peppoasap** [nrwl/nx#15739]
- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Currently, the Nx Angular Module Federation Dev Server when calling the _getStaticRemotes_ method use the default path for the module-federation.config(in project root folder 'module-federation.config.js'), which can be inconvenient in certain scenarios and make unable to use a typescript config file(like my module-federation.config.ts). It would be helpful to have the ability to specify a custom path for the module-federation.config file when starting the dev server. This would allow users to load the config from a specific location(ex. a libs containing all the manifest) and to use a ts config.

## Motivation

Implementing a custom module-federation.config path in the Nx Angular Module Federation Dev Server would provide more flexibility, capabilities to use typed config file and convenience for users who need to work with it in non-standard scenarios.
## Suggested Implementation

- Adding a customModuleFederationConfig?: object; options in builders/module-federation-dev-server/schema.d.ts and schema.json;
```json
"customModuleFederationConfig": {
        "type": "object",
        "description": "use a custom module federation config file",
        "properties": {
              "path": { "type": "string" }
         }
}
```

- Change the _getStaticRemotes_ method to use the new path when declaring _const mfConfigPath_.

**Comment by Coly010** [comment]
If you're willing to implement this, feel free to open a PR.

There's also a chance you'll need to ensure the executor/builder will be able to handle the import of TS file correctly.

**Comment by peppoasap** [comment]
Okay thanks. I will start to work on it as soon as possibile, hope to do my best to contribute to the project :)
