### ISSUE TITLE
Upgrade to `@phenomnomnominal/tsquery` v5.0.1 to unblock Typescript v5 usage

### ISSUE THREAD

**Issue by mcmxcdev** [nrwl/nx#15748]
## Description
Related issue: https://github.com/phenomnomnominal/tsquery/issues/87
Related PR was merged: https://github.com/phenomnomnominal/tsquery/pull/88

**Comment by BlackAF** [comment]
Any updates on this? We would appreciate this as well, Typescript v5 now finally allows tsconfig's `extends` field to be an array which [allows you to combine multiple tsconfig files](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#supporting-multiple-configuration-files-in-extends) (`tsconfig.base.json`, `tsconfig.browser.json`, `tsconfig.paths.json`, etc) which makes the monorepo structure cleaner. It would be nice to be able to upgrade to it, but is currently blocked by the installed version of `@phenomnomnominal/tsquery` (`v4.1.1`) so this fix would be about upgrading this package to `v5.0.1` which fixes the peer dependency version. The upgrade from `v4.1.1` to `v5.0.1` contains one breaking change detailed [here](https://github.com/phenomnomnominal/tsquery/pull/76) which relates to the `tsquery.map()` which doesn't seem to be used(?) within the repo from a quick check (though I could have missed it) so this should be a fairly straightforward fix, well hopefully 😄

**Comment by mandarini** [comment]
I think [that's done](https://github.com/nrwl/nx/blob/master/package.json#L75), so we can close this issue!
