### ISSUE TITLE
How long does it take you to save a recompile boot

### ISSUE THREAD

**Issue by jiayisheji** [nrwl/nx#1574]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

If you solve the problem of saving slow compilation

## Current Behavior

vs code save at a time need how much time？

I've tried dropping my project into nx in the same amount of time as a normal ng-cli.

cli: 45s
nx: 45s
If I use a compiled libs and load it into my app, ng-cli will compile much faster than nx.

cli: 5-10s
nx: 45s

**Comment by vsavkin** [comment]
Nx doesn't have a cache of compiled libs it can use in between the builds. So if you have a single app that needs all the libs, then the compilation time will be identical to the cli. The unit test time won't be as nx can retest libs independently.

We are working on adding bazel support to nx, which will decrease a recompilation time.

**Comment by jiayisheji** [comment]
`Bazel` is not stable at present, can we open `ng build libs` function

I can only manually modify `angular.json`, and `libs` is an optional feature in `angular-cli`
