### ISSUE TITLE
Installing Expo packages doesn't work

### ISSUE THREAD

**Issue by Kycermann** [nrwl/nx#15759]
### Current Behavior

When installing `expo-image`, I expect `package.json` or `apps/test/package.json` to have `expo-image` as a dependency.

### Expected Behavior

When installing `expo-image`, in `package.json` or `apps/test/package.json` there are no mentions of `expo-image`.

### Steps to Reproduce

1. `npx create-nx-workspace --preset=expo`
2. Answer with "test" to all prompts
3. `cd test`
4. `npx nx install test --packages=expo-image`
5. Look in `package.json` and `apps/test/package.json` - neither contain any reference to `expo-image`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : darwin arm64
   npm  : 8.3.1
   
   nx                      : 15.8.7
   @nrwl/js                : 15.8.7
   @nrwl/jest              : 15.8.7
   @nrwl/linter            : 15.8.7
   @nrwl/workspace         : 15.8.7
   @nrwl/cli               : 15.8.7
   @nrwl/detox             : 15.8.7
   @nrwl/devkit            : 15.8.7
   @nrwl/eslint-plugin-nx  : 15.8.7
   @nrwl/expo              : 15.8.7
   @nrwl/react             : 15.8.7
   @nrwl/tao               : 15.8.7
   @nrwl/webpack           : 15.8.7
   typescript              : 4.9.5
```

### Additional Information

The responses to the install commands appear successful.

**Comment by Kycermann** [comment]
This could arise from https://github.com/expo/expo/issues/21768

**Comment by xiongemi** [comment]
i just tried locally. you don't need to `cd test`. at the workspace root, I run command `nx install test --packages=expo-image`. in workspace root package.json, i see `expo-image` is added.
Note: it updates workspace root's package.json rather than app's package.json.
