### ISSUE TITLE
`projectFilePatterns` produces different results in NX 15 compared to results from NX 14

### ISSUE THREAD

**Issue by GreenTea124** [nrwl/nx#15755]
### Current Behavior

It seems that NX 14 generates `name` of the inferred project as a relative project path from root in kebab case, and NX 15 simply takes the last directory name. New behaviour can lead to project name collisions.

### Expected Behavior

It would be nice to be able to choose between both these behaviours.

Or even better, maybe there could be a `registerProjectMeta` function that would work similarly to `registerProjectTargets`, but could be used to modify the name (and possibly other properties) of the inferred project.

### Steps to Reproduce

If your folder structure looks like this:

```
libs
  app-1
     componnets
        project-index.ts
  app-2
     componnets
        project-index.ts
nx.json
```

If you have a custom plugin like this:
```ts
exports.projectFilePatterns = ['project-index.ts'];

```

And if you won't define project names explicitly in `nx.json` or using `package.json` or `project.json` files, then:
- **NX 14.6.3** - will create a `app-1-components` project and `app-2-components` project.
- **NX 15.8.7** - will create a `components` project, and than will fail to create 2nd one, since `components` name is already taken

It seems that NX 14 generates name as relative project path from root in kebab case, and NX 15 simply takes last directory name.

### Nx Report

```shell
Node : 16.14.0
   OS   : win32 x64
   npm  : 8.3.1

   nx          : 15.8.7
   @nrwl/cli   : 15.8.7
   @nrwl/tao   : 15.8.7
   typescript  : 5.0.2
```

**Comment by AgentEnder** [comment]
The change here was intended - but it does represent a breaking change that likely wasn't pointed out in the release notes. The project file patterns API is still pretty experimental. I personally added it, and I also personally hate the current API. It **_will_** change, likely in the next 2 months or so. 

This change will probably be large, but will probably be backwards compatible. In any case, the change noted in this issue won't be reverted - it was made to increase compatibility with some other ecosystem tooling
