### ISSUE TITLE
Add ng-packagr assets option to @nrwl/angular:ng-packagr-lite executor

### ISSUE THREAD

**Issue by alessio-libardi** [nrwl/nx#15757]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
I would love to be able to copy assets to my libraries using the packagr [assets option](https://github.com/ng-packagr/ng-packagr/blob/main/docs/copy-assets.md).

## Motivation
Because I think many others would use this option.

## Suggested Implementation
Simply adding the option to the executor schema and passing it to the packagr instance should be enough.

## Alternate Implementations
None

**Comment by leosvelperez** [comment]
Thanks for the suggestion!

Unfortunately, `ng-packagr` doesn't provide a way for us to provide the options from `ng-package.json`. It directly reads those options from that file and is not configurable.

You can still use the [assets option](https://github.com/ng-packagr/ng-packagr/blob/main/docs/copy-assets.md) you mentioned in the `ng-package.json` file of your buildable library to copy your assets.

**Comment by alessio-libardi** [comment]
Lovely, thanks for the suggestion @leosvelperez !
