### ISSUE TITLE
Requesting for a preview of commands to be executed with --verbose option

### ISSUE THREAD

**Issue by leobastiani** [nrwl/nx#15750]
## Description
I would like the `--verbose` option in Nx to output what is going to be run. Currently, it doesn't provide any indication of what commands will be executed.

## Motivation
Providing a preview of the commands that will be run can be helpful for debugging purposes, as well as for understanding what's going on under the hood.
https://github.com/nrwl/nx/issues/15455#issuecomment-1474853626

## Suggested Implementation
One way to implement this feature could be to modify the `test.impl.ts` file in the `detox` package, as well as other places that use `fork`, to include a preview of the commands that will be executed when the `--verbose` option is used.

## Alternate Implementations
Another approach could be to create a separate option, such as `--dry-run`, that specifically provides a preview of the commands without actually executing them. This could be useful in situations where you want to see what commands will be run, but don't actually want to run them yet.

- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

**Comment by AgentEnder** [comment]
We are working on making the ergonomics better, but currently the recommendation for this is to use the task graph. 

Currently, you can run `nx graph` and then flip over to it in the top left corner.

In the future, you should be able to run `nx run-many -t build --graph` or similar and have it open with the targets populated.
