### ISSUE TITLE
Type a new way to type reference.

### ISSUE THREAD

**Issue by louiss0** [nrwl/nx#15758]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

A way to tell typescript what types to refer to when creating a package. 

## Motivation

I recently created a mono-repo that used Astro Components. The problem was that Astro doesn't support Generic types so had to create a `d.ts` file that lead me to do that. But since I had no type information I needed to instead use my library outside of the mono-repo I cost me time and I had to do many releases just to see if the types were correct. 

## Suggested Implementation

You might have to stop using typescript paths but instead make the user specify a file then where the file's type def's are.

I think the nx.json file should be used instead of the paths for the types. This way people can do this in publishable of non-publishable libraries. 

**This is what the code would look like inside of it**

![nx-project-with-types-example](https://user-images.githubusercontent.com/29028601/226195003-454c8652-57af-4f09-a93d-03dcdb538f91.png)

 

## Alternate Implementations

You can also do this.  
![nx-path-with-types-example](https://user-images.githubusercontent.com/29028601/226200953-dd861e15-db1a-4282-81ff-a3b5127e95b4.png)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

I'm not sure I properly understand the issue you're facing. Could you please expand on what you mean by "don't support Generic types"? Could you provide a repro where the issue can be seen to help us understand the issue so we can troubleshoot it better?

**Comment by louiss0** [comment]
> Thanks for reporting this!
> 
> I'm not sure I properly understand the issue you're facing. Could you please expand on what you mean by "don't support Generic types"? Could you provide a repro where the issue can be seen to help us understand the issue so we can troubleshoot it better?

**Here is the link to the reproduction**

https://github.com/louiss0/frontmatter-cms-test.

**Comment by leosvelperez** [comment]
I see, thanks for the repro. This is a limitation of Astro and I suggest you to ask in their repo for supporting TS generics for `Props`.

I also created a PR in your repro https://github.com/louiss0/frontmatter-cms-test/pull/2#pullrequestreview-1354177113 to show how you can workaround that limitation within the workspace. You can use such a setup to support your use case.

I'm closing this issue since we don't plan to change how we handle internal libraries to accommodate such a limitation from a separate tool and workaround is provided.

**Comment by louiss0** [comment]
I helped with the page generator issue. I don't know how people get email's from GitHub but here it is. https://github.com/nxtensions/nxtensions/issues/31
