### ISSUE TITLE
connect ETIMEDOUT 10.200.0.50:4873

### ISSUE THREAD

**Issue by MaraZ1** [nrwl/nx#1575]
## Expected Behavior

This command worked a few hours ago
`yarn create nx-workspace my-app`

## Current Behavior

After a moment:
`error An unexpected error occurred: "http://10.200.0.50:4873/create-nx-workspace: connect ETIMEDOUT 10.200.0.50:4873"`

`ping 10.200.0.50:4873` won´t find the host

### Steps to Reproduce

1. `yarn create nx-workspace my-app`
2. Fails with error:  An unexpected error occurred: "http://10.200.0.50:4873/create-nx-workspace: connect ETIMEDOUT 10.200.0.50:4873

OR

1. If you already have a project that uses @nrwl - delete node_modules and then just run yarn
2. It fails with the same message

### Context

- YARN version: 1.10.1

**Comment by MaraZ1** [comment]
It seems like a problem with my local npm. Not related to the nx.

**Comment by vsavkin** [comment]
Closing this issue
