### ISSUE TITLE
@nrwl/esbuild plugin doesn't re-export main entypoint exports

### ISSUE THREAD

**Issue by iamhosseindhv** [nrwl/nx#15772]
### Current Behavior

`@nrwl/esbuild` plugin is great and takes care of a lot of things. However, it can be used to build an AWS lambda function.

AWS Lambda invokes a function exported from lambda source code:

```js
// my-main.js

const handler = (event, context) => {
   // handle lambda function
}

module.exports { handler }
``` 

However `esbuild` plugin wraps the code in a `main-with-require-overrides.js` file to resolve workspace dependencies. This is great, but this wrapper doesn't re-export what is exported from my `my-main.js` file. It instead simply requires it:

https://github.com/nrwl/nx/blob/9ef2dd90dd23448f70827bcaebad1b14e18226e3/packages/esbuild/src/executors/esbuild/lib/build-esbuild-options.ts#L280-L281

For this reason, AWS lambda is unable to find my `handler` function and invoke it, since no such thing is exported from `main-with-require-overrides.js`.

### Expected Behavior

The wrapper file should re-export everything that's exported from user's entry point / main file. e.g. be something like:
```js
module.exports = require('./path-to-package-main.js')
```

### Steps to Reproduce

1. 

### Nx Report

```shell
Node : 16.13.2
   OS   : darwin x64
   npm  : 8.1.2
   
   nx                      : 15.8.6
   @nrwl/js                : 15.8.6
   @nrwl/jest              : 15.8.6
   @nrwl/linter            : 15.8.6
   @nrwl/workspace         : 15.8.6
   @nrwl/cli               : 15.8.6
   @nrwl/devkit            : 15.8.6
   @nrwl/esbuild           : 15.8.6
   @nrwl/eslint-plugin-nx  : 15.8.6
   @nrwl/nx-plugin         : 15.8.6
   @nrwl/tao               : 15.8.6
   typescript              : 4.9.5
```
```


### Failure Logs

_No response_

### Additional Information

_No response_

**Comment by iamhosseindhv** [comment]
To confirm, this is still an issue

**Comment by realityfilter** [comment]
Any other workarounds? This is quite annoying. Any option to get rid of the wrapper entirely?
