### ISSUE TITLE
(express): when serving, "Debugger listening..." message gets printed twice

### ISSUE THREAD

**Issue by karmasakshi** [nrwl/nx#15793]
### Current Behavior

"Debugger listening on..." message gets printed twice when serving an Express app.

<img width="596" alt="Screen Shot 2023-03-21 at 5 12 56 PM" src="https://user-images.githubusercontent.com/4698762/226616644-46dc2737-dbfc-4d42-a672-da39d82a9899.png">

### Expected Behavior

Message should be printed once.

### Steps to Reproduce

1. `npx create-nx-workspace@latest xxx --preset express`
2. Application name: `abc`
3. Enable distributed caching to make your CI faster: No
4. `cd xxx`
5. `npx nx serve abc`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.15.0
   OS   : darwin arm64
   npm  : 9.5.0
   
   nx                      : 15.8.7
   @nrwl/js                : 15.8.7
   @nrwl/jest              : 15.8.7
   @nrwl/linter            : 15.8.7
   @nrwl/workspace         : 15.8.7
   @nrwl/cli               : 15.8.7
   @nrwl/devkit            : 15.8.7
   @nrwl/eslint-plugin-nx  : 15.8.7
   @nrwl/express           : 15.8.7
   @nrwl/node              : 15.8.7
   @nrwl/tao               : 15.8.7
   @nrwl/webpack           : 15.8.7
   typescript              : 4.9.5
```

**Comment by timonmasberg** [comment]
I experience the same.
