### ISSUE TITLE
Use storybook7Configuration Command not generate version 7 storybook

### ISSUE THREAD

**Issue by yxqme** [nrwl/nx#15812]
### Current Behavior

Generated the 6.5 version of the storybook

### Expected Behavior

Use storybook7Configuration Generate version 7 storybook

### Steps to Reproduce

 nx g @nrwl/storybook:configuration editor --storybook7UiFramework=@storybook/react-vite --storybook7Configuration
 

### Nx Report

![image](https://user-images.githubusercontent.com/5998046/226793299-288ca959-8453-44b5-a3cf-400a5064641a.png)

### Additional Information

nx 15.8.7
node v16.19.1

OS

ProductName:		macOS
ProductVersion:		13.0.1
BuildVersion:		22A400

**Comment by mandarini** [comment]
Hi there @yxqme ! If you are on a version smaller than `15.9`, [as it says in the docs](https://nx.dev/packages/storybook/documents/storybook-7-setup#generating-storybook-configuration), you have to use the old flag, named `storybook7betaConfiguration` instead.

However, I do agree that it's confusing, so I will push for a fix to the older version to accept both flags.
