### ISSUE TITLE
Rename generator

### ISSUE THREAD

**Issue by amal-chandran** [nrwl/nx#15817]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
- rename project generator. 
- similar to nx move / nx remove the generator. 
- helps us to rename an app/lib 

## Motivation
- Normally when we start a project we create one serverless lambda app with @ns3/nx-serverless
- But as the application progress we might need to move them to sub-folders and make the group of serverless functions based on domain/deployment patterns
- The way we do it now is to move the application and manually update the names in each place it is referenced
- If we have a generator that does in one go the process got simplified

## Suggested Implementation
- similar to the move generator it accepts the project name & new project name
- when we run the generator it will update the typescript references & nx configs with a new name

**Comment by mandarini** [comment]
@amal-chandran thanks for the feature request. You can actually use the move generator to rename your projects, as described here: https://nx.dev/more-concepts/grouping-libraries#move-generator

Did you find that the move generator does not achieve what you want when renaming a project?
