### ISSUE TITLE
nx --version should not check if in a nx workspace

### ISSUE THREAD

**Issue by DaSchTour** [nrwl/nx#15825]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
When running `nx --version` it should always print the version and not check if executed in a nx workspace

## Motivation
Some errors, especially 'The current directory isn't part of an Nx workspace.' and maybe in future also other errors might depend on the current nx version. But that can't be checked because first the nx workspace is checked.

It may also be useful for `nx --help`

**Comment by AgentEnder** [comment]
We've discussed this to some extent - In essence, right now `nx --version` checks the version of the **_local_** install. It would be nice if it could check both, but there are some complexities that one may not expect. Mostly this boils down to not being able to check the global version when its the local version doing the bootstrapping.

For `--help`, the current behavior is what we'd like as the help text should be accurate to the version of Nx that is running.
