### ISSUE TITLE
Cannot create a Nestjs app

### ISSUE THREAD

**Issue by bhaidar** [nrwl/nx#1583]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior
Using the `ng g node-app myapp --framework=nestjs` is expected to create a nestjs app.

## Current Behavior
What is the current behavior?

I am getting an exception:

````
Cannot parse arguments. See below for the reasons.
Argument --framework could not be parsed using value "nestjs". Valid values are: "express", "none".
````

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `npm install -g @angular/cli @nrwl/schematics`
2. `ng g node-app --framework=nestjs`

### Context

Please provide any relevant information about your setup:

- Nx latest
- Angular CLI 7.0.1
- Angular DevKit ~0.801.1

**Comment by wesleygrimes** [comment]
Hi Bilal,

By default, the Angular CLI refers to `angular.json` > `cli` > `defaultCollection` for which set of schematics to use. In your example, the CLI is still using default angular schematics.

You first need to convert your workspace to `nx` or generate a brand new `nx` workspace...

1) First, make sure you are inside an `nx` workspace. If not, create a new one like this:  `npx create-nx-workspace my-workspace`

2) If you have an existing angular cli project you can convert to `nx` workspace by running this: `ng add @nrwl/schematics`

Once you are inside an `nx` workspace you can generate a `nest` app by doing the following:

1) `ng add @nrwl/nest --defaults`
2) `ng g @nrwl/nest:app your-node-app`

Let me know if this approach works.

Thanks,
Wes

**Comment by bhaidar** [comment]
Hey @wesleygrimes Thanks for your feedback.

I found this tutorial https://nx.dev/angular/tutorial/01-create-application really helpful in getting me started with Nx Workspace! 

Things are now working like a charm :-)

Regards
Bilal

**Comment by wesleygrimes** [comment]
Fantastic. Anything else you need help with before I close this issue?

**Comment by bhaidar** [comment]
Thanks for your time!

**Comment by wesleygrimes** [comment]
You're welcome!
