### ISSUE TITLE
Some features in local executors not working when swc installed

### ISSUE THREAD

**Issue by kwiniarski97** [nrwl/nx#15851]
### Current Behavior

Decorators (and maybe some other issues of typescript) is not working when compiling local executors with swc. It complains with an error
```
Unexpected token `@`. Expected identifier, string literal, numeric literal or [ for the computed key
``` 

If the swc is purged from package.json/package-lock.json/node_modules then it shows a warning that it is using a ts-node as legacy compiler, but code compiles properly.

A simple executor I've made for reproduction purposes that is failing:
```
class Schema {
  @IsString()
  name = 'name';
}

export default async function runExecutor(
  options: MyExecutorExecutorSchema,
) {
  const schema = new Schema();
  console.log(schema.name)
  console.log('Executor ran for MyExecutor', options);
  return {
    success: true
  };
}
```

### Expected Behavior

Executor should compile and should be executed.

Optionally, there should be a way to force local plugin to use ts-node instead of swc.

### GitHub Repo

https://github.com/kwiniarski97/nx-reproduction

### Steps to Reproduce

1. clone repo
2. run `nx run nx:execute`

More convoluted way
1. Have a repository with a local executor
2. Use decorators in it
3. Have swc installed even as peer dep
4. Try to run executor

### Nx Report

```shell
Node : 16.18.1
   OS   : win32 x64
   npm  : 8.19.2

   nx                      : 15.8.7
   @nrwl/js                : 15.8.7
   @nrwl/jest              : 15.8.7
   @nrwl/linter            : 15.8.7
   @nrwl/workspace         : 15.8.7
   @nrwl/angular           : 15.8.7
   @nrwl/cli               : 15.8.7
   @nrwl/cypress           : 15.8.7
   @nrwl/devkit            : 15.8.7
   @nrwl/eslint-plugin-nx  : 15.8.7
   @nrwl/nx-plugin         : 15.8.7
   @nrwl/tao               : 15.8.7
   @nrwl/webpack           : 15.8.7
   typescript              : 4.9.5
```

### Failure Logs

```shell
Unexpected token `@`. Expected identifier, string literal, numeric literal or [ for the computed key
      ,-[C:\nx-reproduction\apps\nx\src\executors\my-executor\executor.ts:2:1]
    2 | import {IsString} from 'class-validator';
    3 | 
    4 | class Schema {
    5 |   @IsString()
      :   ^
    6 |   name = 'name';
    7 | }
      `----
```

### Additional Information

I think this has been working in previous versions of nx, as I haven't changed much in my project except dependencies numbers.

**Comment by AgentEnder** [comment]
I think this is fixed now, can you try with latest and let me know if its still happening? If so we will reopen.

**Comment by epechuzal** [comment]
@AgentEnder I still hit the issue on 16.1.4 - I can only run my local executors/generators if I uninstall anything related to swc

**Comment by johannesnormannjensen** [comment]
> @AgentEnder I still hit the issue on 16.1.4 - I can only run my local executors/generators if I uninstall anything related to swc

I experienced the same thing. Funny enough if i remove and reinstall then it suddenly works: 
 - Uninstall swc dependencies 
   - npm rm @swc/core
   - npm rm @swc/helpers
   - npm rm @swc-node/register
 - Reinstall swc dependencies 
   - npm i -D @swc/core
   - npm i -D @swc/helpers
   - npm i -D @swc-node/register
