### ISSUE TITLE
Installing dependencies in gitlab CI failes on @nrwl/tao index file not found

### ISSUE THREAD

**Issue by Donorlin** [nrwl/nx#15875]
### Current Behavior

Hello,

when we are installing dependencies in our gitlab CI, installation fails on:

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /tmp/PROJECT/node_modules/@nrwl/tao/index
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/tmp/PROJECT/node_modules/@nrwl/tao/index'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/.npm/_logs/2023-03-24T09_32_[45](GITLAB/PROJECT/-/jobs/274223#L45)_166Z-debug.log
```

We are using Node v16.14.0 with npm 7.20.2
Our package.json contains latest `lerna` version `6.6.0`, no `nx` specified
with clean package.lock (deleted node_modules and lock and generated new one with latest possible versions)

This change to "index" file was made in this commit [6834b65](https://github.com/nrwl/nx/commit/6834b658f71d5415f3d53fe3cb4a2c90efb17232)
this means `@nrwl/tao@15.8.8` has this problem (which is in package.lock)

### Expected Behavior

`npm ci` or `npm install` runs successfully in CI environment

### Steps to Reproduce

We tried this in our gitlab ci with clean project that just has `lerna@6.6.0` as dependency.
Lock had `@nrwl/tao@15.8.8`
1. `npm ci`
Installation fails with mentioned error.

### Nx Report

```shell
no nx report
```

**Comment by justinpenguin45** [comment]
Exact same issue. Started yesterday in Azure build pipelines

**Comment by muhlbeier** [comment]
Same issue both locally and in azure build pipeline.
OS:  ubuntu-22.04

error code ENOENT
error syscall chmod
error path /home/vsts/work/1/s/node_modules/@nrwl/cli/node_modules/@nrwl/tao/index
error errno -2
error enoent ENOENT: no such file or directory, chmod '/home/vsts/work/1/s/node_modules/@nrwl/cli/node_modules/@nrwl/tao/index'
error enoent This is related to npm not being able to find a file.

**Comment by justinpenguin45** [comment]
so annoying how this just randomly happens and breaks builds :/

**Comment by justinpenguin45** [comment]
seems this is what broke it
https://github.com/nrwl/nx/pull/15438

**Comment by FrozenPandaz** [comment]
Fixed with https://github.com/nrwl/nx/pull/15883
