### ISSUE TITLE
Rename serializer in example DefaultRouterStateSerializer  => FullRouterStateSerializer

### ISSUE THREAD

**Issue by solshark** [nrwl/nx#15879]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.
https://nx.dev/recipes/other/misc-data-persistence#using-data-persistence-operators

### Additional context or description
`FullRouterStateSerializer` should be used instead of `DefaultRouterStateSerializer` 

Provide any additional details here as needed.

**Comment by sumitparakh** [comment]
Can I take this up?
