### ISSUE TITLE
@nrwl/next:build styles option don't load the css file

### ISSUE THREAD

**Issue by victorcarvalhosp** [nrwl/nx#15870]
### Current Behavior

I want to be able to load a CSS file into our application using the "styles" option on project.json, but it doesn't load the style file as expected.

I have my build step configured like this on project.json:

```
"build": {
      "executor": "@nrwl/next:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "root": "apps/project-web",
        "outputPath": "dist/apps/project-web",
        "styles": ["apps/project-web/src/styles/styles.css"]
      },
      "configurations": {
        "development": {
          "outputPath": "apps/project-web"
        },
        "production": {}
      }
    },
```

But it doesn't load the CSS file. Nothing happens and it's like the styles configuration is ignored.

### Expected Behavior

I expect the css file to be loaded without the need to import it directly into some component. Doing the same for a project using @nrwl/webpack:webpack executor works fine and the CSS file is properly loaded.

### Steps to Reproduce

1. Create a new project using nx g @nrwl/next:app my-new-app
2. Create a CSS file and add some style to it
3. Modify project.json to add the style under build > options > styles. Example:

```
"build": {
      "executor": "@nrwl/next:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "root": "apps/project-web",
        "outputPath": "dist/apps/project-web",
        "styles": ["apps/project-web/src/styles/styles.css"]
      },
      "configurations": {
        "development": {
          "outputPath": "apps/project-web"
        },
        "production": {}
      }
    },
```

Run the project, and the style will not be loaded. We can as a workaround import the style file directly from some component, but this is not ideal as we can't load CSS files from other libs this way, which could be achieved using the style property on project.json. Example:

```
"styles": [
          "apps/project-web/src/styles/styles.css",
          {
            "input": "./libs/shared/src/styles/colors.css"
          }
        ],
```

### Nx Report

```shell
Node : 18.7.0
   OS   : darwin arm64
   npm  : 8.15.0
   
   nx                      : 15.8.7
   @nrwl/js                : 15.8.7
   @nrwl/jest              : 15.8.7
   @nrwl/linter            : 15.8.7
   @nrwl/workspace         : 15.8.7
   @nrwl/cli               : 15.8.7
   @nrwl/cypress           : 15.8.7
   @nrwl/devkit            : 15.8.7
   @nrwl/eslint-plugin-nx  : 15.8.7
   @nrwl/next              : 15.8.7
   @nrwl/react             : 15.8.7
   @nrwl/rollup            : 15.8.7
   @nrwl/storybook         : 15.8.7
   @nrwl/tao               : 15.8.7
   @nrwl/web               : 15.8.7
   @nrwl/webpack           : 15.8.7
   typescript              : 4.9.5
```

**Comment by jaysoo** [comment]
Hi @victorcarvalhosp We don't support `styles` option for `@nrwl/next:build` because it isn't the recommended way of importing global styles. See [here](https://nx.dev/packages/next/executors/build#@nrwl/next:build) for the supported options.

To import global styles, you should add the import statement directly in your `_app.tsx` file (There should be one generated by Nx already). See the [Next.js docs](https://nextjs.org/learn/basics/assets-metadata-css/global-styles) for more information.
