### ISSUE TITLE
Add `.env*` to the .gitignore that is generated when `npx create-nx-workspace` is run.

### ISSUE THREAD

**Issue by ICEDLEE337** [nrwl/nx#15881]
- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Add `.env*` to the .gitignore that is generated when `npx create-nx-workspace` is run.

## Motivation
Having `.env` in the .gitignore would prevent people from accidentally checking in .env files.

## Suggested Implementation
Just add the string `.env*` to the preconfigured set of entries that are currently being written to the .gitignore.

## Alternate Implementations
N/A

**Comment by AgentEnder** [comment]
This seems fine to me. Feel free to throw a PR up - you'll need to touch these 3 files:
<img width="793" alt="image" src="https://user-images.githubusercontent.com/6933928/228066427-bab1ec00-0609-4063-9955-7d14577cf79a.png">
