### ISSUE TITLE
Cypress tests in a NX workspace can't use paths defined in the tsconfig.base

### ISSUE THREAD

**Issue by styriandev** [nrwl/nx#15906]
### Current Behavior

I am actually not sure if this is really a bug or just a configuration issue. But we are using Cypress to test our application that is set up in a NX workspace and we have some issues when we are trying to use a cypress library in the cypress test. 

To be exact, we are getting a webpack issue when we are trying to use paths defined in the tsconfig.base.json

The following doesn't work:
`import { Class } from '@ui/some-models-lib';`

If I exactly specify the import it works:
`import { Class } from '../../../../../libs/some-models-lib/path/to/file/class';`

However, these full paths are not a really good solution which is why we need some solution for that.
If I only reference the index.ts of the "some-models-lib" I face the same issue ( so `import { Class } from '../../../../../libs/some-models-lib`)

The following issue is produced:
```
Error: Webpack Compilation Error
C:/Develop/Program_A_toolchain/libs/models/src/lib/layout/route-elements/edge-element/index.ts 4:9
Module parse failed: Unexpected token (4:9)
File was processed with these loaders:
 * ../../../../@packages/server/node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
```

The interesting part here is that the webpack issue is not directly referencing the lib that I am actually referencing, it is referencing a sub dependency of the "some-models-lib".
So to make that clear:
The E2E test is using the some-models-lib which is using another models lib.  

From what I saw, this issue was already mentioned by https://github.com/nrwl/nx/issues/5713 and referenced here https://github.com/nrwl/nx/issues/3037#issuecomment-884817269. 

The existing tickets do not mention a solution for a nx workspace with Angular.

At the moment we are using Cypress 10.6.0 but I tried to upgrade to Cypress 12 which also doesn't make a difference there.

Maybe this is related to this issue: 
We needed to setup polyfills for our frontend as our models lib is using class-validator which contains a dependency to import 'reflect-metadata';. 

From what I understand we don't have to configure anything so that Cypress in a NX workspace works with libraries, is this correct? Do we have to add anything so that the tsconfig is interpreted correctly?

### Expected Behavior

The imports can be used with the paths defined in the tsconfig.base.ts.

### Steps to Reproduce

1. Create a models lib
2. Reference it in an E2E test

### Nx Report

```shell
Node : 18.14.2
   OS   : win32 x64
   npm  : 9.5.0

   nx                      : 15.8.5
   @nrwl/js                : 15.8.5
   @nrwl/jest              : 14.5.8
   @nrwl/linter            : 15.8.5
   @nrwl/workspace         : 15.8.5
   @nrwl/angular           : 15.8.5
   @nrwl/cli               : 15.8.5
   @nrwl/cypress           : 15.8.5
   @nrwl/devkit            : 15.8.5
   @nrwl/eslint-plugin-nx  : 15.8.5
   @nrwl/express           : 15.8.5
   @nrwl/nest              : 15.8.5
   @nrwl/node              : 15.8.5
   @nrwl/storybook         : 15.8.5
   @nrwl/tao               : 15.8.5
   @nrwl/webpack           : 15.8.5
   typescript              : 4.8.2
   ---------------------------------------
   Community plugins:
   @ngrx/effects        : 15.3.0
   @ngrx/store          : 15.3.0
   @ngrx/store-devtools : 15.3.0
   ngx-bootstrap        : 10.3.0
   @storybook/angular   : 6.5.16
   ---------------------------------------
```

### Failure Logs

```

Error: Webpack Compilation Error
C:/Develop/Program_A_toolchain/libs/models/src/lib/layout/route-elements/edge-element/index.ts 4:9
Module parse failed: Unexpected token (4:9)
File was processed with these loaders:
 * ../../../../Users/user/AppData/Local/Cypress/Cache/10.6.0/Cypress/resources/app/node_modules/@packages/server/node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
| export { EdgeDirectionIcons } from './edge-direction-icons.enum';
| export { EdgeElement } from './edge-element';
> export * as EdgeConfig from './edge-config';
| export { DuplicatedEdgesHelper } from './duplicated-edges-helper';
| 
 @ C:/Develop/project/libs/models/src/lib/layout/route-elements/index.ts 4:0-31 4:0-31
 @ C:/Develop/project/libs/models/src/lib/layout/index.ts
 @ C:/Develop/project/libs/models/src/lib/index.ts
 @ C:/Develop/project/libs/models/src/index.ts
 @ C:/Develop/project/libs/hmi/hmi-models/src/lib/data-table-event-icon-cell.ts
 @ C:/Develop/project/libs/hmi/hmi-models/src/lib/index.ts
 @ C:/Develop/project/libs/hmi/hmi-models/src/index.ts
 @ ./src/e2e/pages/test.cy.ts
```
```

```

**Comment by styriandev** [comment]
Ok, it seems like this issue happens because of some index.ts files that contain a export * as Blabla from './file'. If I change that to export { A, B, C } from './' file everything works like a charm. In a new NX project this issue does not happen but maybe this is related to the number of index.ts files in our lib. I know, it is a better practise to have smaller libs with the scope of a specific use case and we are adapting to that but in the moment we have a models lib with 1000+ files. 
Is anything like this known? As described, we managed to solve the error but as typescript can compile the lib it would be fine if the lib can be used in the same way for cypress too.

**Comment by barbados-clemens** [comment]
do you have a repo I can clone and take a look at?

As you mentioned in new projects you're not seeing this, and I'm not able to reproduce locally on a new workspace, so it's probably some older configuration laying around that could be the issue.
