### ISSUE TITLE
Using scripts with interactive libs like stdio or prompt not showing prompt messages

### ISSUE THREAD

**Issue by vitto** [nrwl/nx#15924]
### Current Behavior

Maybe this is not the appropriate way to use NX, there are situations where I need interactive prompts, and it seems they are not shown for some reason. Basically everything works, but prompt message which expect use input is not shown, you can write the input and confirming it with return, but you can't see the prompt message.

In my sub project `package.json`:

```json
"scripts": {
  "publish.isolate.component": "npx ts-node --skipProject ./scripts/isolate-component.ts",
}
```

My command performs interactive questions:

```ts
import chalk from 'chalk'
import { ask } from 'stdio'

const main = async (): Promise<void> => {
  console.log(`This script will ${chalk.green('isolate')} a stencil component and will create package.json if missing into a an isolated stencil project, ready to be published`)

  if (!nonInteractive) {
    const continueTask = await ask('Continue?', { options: ['Y', 'n', ''] })
    if (continueTask === 'n') {
      return
    }
  }
  // do other stuff
}

main()
```

The script accepts inputs and wait user input, but nothing is visible:

<img width="1242" alt="Screenshot 2023-03-28 alle 11 58 09" src="https://user-images.githubusercontent.com/461484/228201401-dec281bb-2772-425c-b80f-b08685c96e94.png">

I've tried with other libraries like `prompt` and i get the exact same problem, prompt messages are not shown, but everything is interactive.

### Expected Behavior

I would expect to see prompt messages like if I run the same command with `npm` directly:

<img width="1250" alt="Screenshot 2023-03-28 alle 11 58 26" src="https://user-images.githubusercontent.com/461484/228201674-38e3c6b3-3b74-4c16-ac0c-c015ecbcb101.png">

### GitHub Repo

Unfortunately, my repo is private and I cannot share it.

### Steps to Reproduce

1. Use interactive IO libraries like `stdio` or `prompt`
2. Write a simple command like this:

```ts
import chalk from 'chalk'
import { ask } from 'stdio'

const main = async (): Promise<void> => {
  console.log(`This script will ask you to write Y or n (this message shows):`)
  const response = await ask('Continue? (this message is not shown)', { options: ['Y', 'n', ''] })
  console.log(response)
}

main()
```

### Nx Report

```shell
Node : 18.12.1
   OS   : darwin x64
   yarn : 1.22.19

   nx               : 15.8.9
   @nrwl/js         : 15.8.9
   @nrwl/linter     : 15.8.9
   @nrwl/workspace  : 15.8.9
   @nrwl/cli        : 15.8.9
   @nrwl/devkit     : 15.8.9
   @nrwl/tao        : 15.8.9
   typescript       : 5.0.2
```

### Additional Information

I've updated to `typescript: 5.0.2` but it wasn't working also on `typescript: 4.x.x`

**Comment by FrozenPandaz** [comment]
@Coly010 @AgentEnder I think you looked into something like this?

**Comment by Coly010** [comment]
Yes we did. We looked into changing `run-commands` to support interactive scripts, but we're pretty certain it has undesired consequences. 

That said, it should be possible to write a custom executor in the workspace that can execute scripts in interactive mode. 

I'll speak with @AgentEnder and confirm this, and also confirm the best way to build an executor to handle this.

**Comment by Coly010** [comment]
I've created a gist here: https://gist.github.com/Coly010/5477132c9477a2a23c23ac902819cce3

This contains the code for an executor that will allow for running interactive commands.

You can create a local Nx Plugin for your workspace that contains an executor that then uses this code.

In the project.json file of the projects where you need to run an interactive command, you can use your custom executor.

You can see docs on creating a local plugin here: https://nx.dev/recipes/executors/creating-custom-executors
