### ISSUE TITLE
Add `yarn.lock` or `package-lock.json` to default values of `implicitDependencies`

### ISSUE THREAD

**Issue by gaetanmaisse** [nrwl/nx#1592]
## Context

In my `package.json` there are some dependencies allowing patch/minor version range, like this: 

```
...
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.801.0"
    ...
  }
...
```

When I updated some of these `dependencies` only my `yarn.lock` was updated because version range defined in `package.json` is still ok. 
But when I ran `nx affected --target test --parallel` no test was run, because no apps/libs depend directly on this file. To fix that I added `yarn.lock` in `implicitDependencies` attribute of `nx.json` file. 

## Question

Doing this makes me wonder if `yarn.lock` (or `package-lock.json`) shouldn't be added to defaults values of `implicitDependencies`? 

If you think it's useful I'm motivated to make a PR for this, I already took a look and spot the default values here: https://github.com/nrwl/nx/blob/master/packages/workspace/src/schematics/ng-add/ng-add.ts#L444
Is there an easy way to know if the dependency manager used in the project is `npm` or `yarn`? or should I test if  `yarn.lock` or `package-lock.json` exist?

**Comment by jaysoo** [comment]
I'm not sure if we need to have those files be included if `package.json` is already there.

My suggestions:

1. Use a fixed version in `package.json` so updates will always force it to be changed.
2. Manually add those entries to `implicitDependencies` if it makes sense for your own workspace.
