### ISSUE TITLE
The experience creating a new workspace is not good

### ISSUE THREAD

**Issue by Cpt-Falcon** [nrwl/nx#15942]
### Current Behavior

`npx create-nx-workspace --preset=react` is not a particularly good first experience when trying to set something up

1. This command from the website is out of date. You need to specify standalone or mono repo. 
2. Critical packages are missing:
![image](https://user-images.githubusercontent.com/10540204/228373373-7fc5ee8a-acad-49f7-a5ca-5c8b80325a4b.png)
![image](https://user-images.githubusercontent.com/10540204/228373470-bf2eec6e-38fc-4a68-8ebf-73b49900bd79.png)
![image](https://user-images.githubusercontent.com/10540204/228373505-1958ed3f-f087-413f-a53a-1fcaf091dd2a.png)

### Expected Behavior

Should be easy and work right away and the instructions online should match

### Steps to Reproduce

1. Following the create workspace example and try to run

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.15.0
   OS   : win32 x64
   yarn : 3.5.0
   
   nx                      : 15.8.9
   @nrwl/js                : 15.8.9
   @nrwl/jest              : 15.8.9
   @nrwl/linter            : 15.8.9
   @nrwl/workspace         : 15.8.9
   @nrwl/cypress           : 15.8.9
   @nrwl/eslint-plugin-nx  : 15.8.9
   @nrwl/react             : 15.8.9
   @nrwl/webpack           : 15.8.9
   typescript              : 4.9.5
```

**Comment by jaysoo** [comment]
@Cpt-Falcon Thanks for reporting the issue. I will update the docs. As for the missing dependency on `@babel/core`, that has been fixed in the latest version of Nx.

```
npx create-nx-workspace@latest --preset=react-standalone
```
