### ISSUE TITLE
`--generatePackageJson` produces wrong `package.json` when using `pnpm@8.0.0`

### ISSUE THREAD

**Issue by Tirke** [nrwl/nx#15960]
### Current Behavior

`pnpm@8.0.0` has introduced a new `pnpm-lock.yaml` format and I know that `nx` is using the file to produce a `package.json` with correctly resolved versions. Currently it's failing for us on package `@anatine/zod-nestjs` producing this line:

`"@anatine": "zod-openapi@1.12.0(openapi3-ts@3.2.0)(zod@3.21.4)",`

which can't be resolved as a correct version by `pnpm` on install.

### Expected Behavior

We can use `pnpm@8.0.0` with `nx` and generate correct `package.json` file.

### GitHub Repo

No repro at this time will do if needed

### Steps to Reproduce

1. Use `pnpm@8.0.0` and `@anatine/zod-nestjs` in a service
2. Build the service with the `--generatePackageJson`
3. You now have a broken `package.json`

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node : 18.15.0
   OS   : darwin arm64
   pnpm : 8.0.0

   nx                      : 15.8.9
   @nrwl/js                : 15.8.9
   @nrwl/jest              : 15.8.9
   @nrwl/linter            : 15.8.9
   @nrwl/workspace         : 15.8.9
   @nrwl/cli               : 15.8.9
   @nrwl/cypress           : 15.8.9
   @nrwl/devkit            : 15.8.9
   @nrwl/esbuild           : 15.8.9
   @nrwl/eslint-plugin-nx  : 15.8.9
   @nrwl/nest              : 15.8.9
   @nrwl/next              : 15.8.9
   @nrwl/node              : 15.8.9
   @nrwl/react             : 15.8.9
   @nrwl/rollup            : 15.8.9
   @nrwl/storybook         : 15.8.9
   @nrwl/tao               : 15.8.9
   @nrwl/web               : 15.8.9
   @nrwl/webpack           : 15.8.9
   @nrwl/nx-cloud          : 15.3.2
   typescript              : 4.9.5
```

**Comment by roderik** [comment]
I've seen this PR which is in progress to support it: https://github.com/nrwl/nx/pull/15925
