### ISSUE TITLE
shared code not being shared among host and remote in MFE

### ISSUE THREAD

**Issue by ak274** [nrwl/nx#15975]
### Current Behavior

While Updating from nx 13.3.2 to nx 15.8.8
We have a workspace with many angular apps and we use Nx's implementation of  MFE configuration...everything was working fine prior to update but once I updated the workspace MFE configuration fails and I haven't made any changes in MFE config...
We are using à la carte approach of configuring the MFE where we only share the libs which are required between host and remotes.
Now I'm not sure what's broken but I feel that the shared libs are not being shared by the MFE config for host because issue is with the DI its not able to find Injection token which is being in a shared libs and also shared in MFE config
if I serve remote apps standalone with their own app module they works fine.. only in the host is not able to load them...

[InjectionToken](https://angular.io/api/core/InjectionToken) in a shared lib which is being shared between host and remote too also when I use the same token in remote app and provide it in host its not being registered in Injector.

### Expected Behavior

It should be registered  and remote entry code should get the instance of the injectionToken

### GitHub Repo

https://github.com/ak274/mfe-issue

### Steps to Reproduce

1. nx serve and click on remote One or remote two link 
2. You can see the error in console

### Nx Report

```shell
Node : 18.15.0
   OS   : win32 x64
   npm  : 9.5.0
   
   nx                      : 15.8.9
   @nrwl/js                : 15.8.9
   @nrwl/jest              : 15.8.9
   @nrwl/linter            : 15.8.9
   @nrwl/workspace         : 15.8.9
   @nrwl/angular           : 15.8.9
   @nrwl/cli               : 15.8.9
   @nrwl/cypress           : 15.8.9
   @nrwl/devkit            : 15.8.9
   @nrwl/eslint-plugin-nx  : 15.8.9
   @nrwl/tao               : 15.8.9
   @nrwl/webpack           : 15.8.9
   typescript              : 4.9.5
```

### Failure Logs

```shell
core.mjs:8416 ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(RemoteEntryModule)[ConfigService -> ConfigService -> InjectionToken Application Config -> InjectionToken Application Config -> InjectionToken Application Config]: 
  NullInjectorError: No provider for InjectionToken Application Config!
NullInjectorError: R3InjectorError(RemoteEntryModule)[ConfigService -> ConfigService -> InjectionToken Application Config -> InjectionToken Application Config -> InjectionToken Application Config]: 
  NullInjectorError: No provider for InjectionToken Application Config!
    at NullInjector.get (core.mjs:7509:27)
    at R3Injector.get (core.mjs:7930:33)
    at R3Injector.get (core.mjs:7930:33)
    at R3Injector.get (core.mjs:7930:33)
    at injectInjectorOnly (core.mjs:633:33)
    at Module.ɵɵinject (core.mjs:637:60)
    at Object.ConfigService_Factory [as factory] (config.service.ts:5:27)
    at R3Injector.hydrate (core.mjs:8031:35)
    at R3Injector.get (core.mjs:7919:33)
    at R3Injector.get (core.mjs:7930:33)
    at resolvePromise (zone.js:1214:31)
    at resolvePromise (zone.js:1168:17)
    at zone.js:1281:17
    at _ZoneDelegate.invokeTask (zone.js:409:31)
    at core.mjs:23891:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:23891:36)
    at _ZoneDelegate.invokeTask (zone.js:408:60)
    at Object.onInvokeTask (core.mjs:24192:33)
    at _ZoneDelegate.invokeTask (zone.js:408:60)
    at Zone.runTask (zone.js:178:47)
```
```


### Additional Information

_No response_

**Comment by barrymichaeldoyle** [comment]
@ak274 does this new fix work for you? My MFE setup still has the same issue after using the latest version 😢

**Comment by ak274** [comment]
Fix is still not released in the latest v15.9.2..I'm  keeping eye when the fix will be released I'll try and let you know.

**Comment by ak274** [comment]
@barrymichaeldoyle This issue is fixed in v15.9.2.. I missed it in the release notes. 
After updating my workspace to latest it resolved the issue.

**Comment by barrymichaeldoyle** [comment]
Ah that sucks, it doesn’t work for me :/

**Comment by ak274** [comment]
Run nx reset after migrations done. I was also having issues with apps not
recognising the dependencies. But started working after that.
