### ISSUE TITLE
@nrwl/rollup:rollup cannot be resolved

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nrwl/nx#15986]
### Current Behavior

I am performing dependency updates in a monorepo right now. 15.9.0 was released during, so, from a stable point, I introduced this diff:

![image](https://user-images.githubusercontent.com/298435/228948373-52107b96-6920-4a5e-b3a3-91cc459f7e85.png)
![image](https://user-images.githubusercontent.com/298435/228948404-79a24687-78a7-4b09-a292-ac18c430df02.png)

![image](https://user-images.githubusercontent.com/298435/228948451-2420c82e-c80f-433b-bcd1-6dc7750d7bcc.png)

This is from https://github.com/nrwl/nx/pull/15797 - released in a minor.

### Expected Behavior

I can upgrade without incident.

### Steps to Reproduce

In the previous cell

### Nx Report

```shell
➜ npx nx report                        
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node : 18.15.0
   OS   : darwin x64
   npm  : 9.5.0
   
   nx                      : 15.9.0
   @nrwl/js                : 15.9.0
   @nrwl/jest              : 15.9.0
   @nrwl/linter            : 15.9.0
   @nrwl/workspace         : 15.9.0
   @nrwl/cli               : 15.9.0
   @nrwl/cypress           : 15.9.0
   @nrwl/devkit            : 15.9.0
   @nrwl/eslint-plugin-nx  : 15.9.0
   @nrwl/next              : 15.9.0
   @nrwl/react             : 15.9.0
   @nrwl/storybook         : 15.9.0
   @nrwl/tao               : 15.9.0
   @nrwl/web               : 15.9.0
   @nrwl/webpack           : 15.9.0
   typescript              : 4.8.4
```

**Comment by paviln** [comment]
I think so. 15.9.0 not working for me aswell, doing a "npx create-nx-workspace@latest myorg --preset=ts", results in failed to create workspace, without any error message...

**Comment by jcasastech** [comment]
Our Lerna Repo just died because of this update. Breaking changes should not be updated like this...

**Comment by bmuenzenmeyer** [comment]
I know how to fix it ; I shouldn't have to on a minor update.

**Comment by AgentEnder** [comment]
Its a missing migration - we are making sure its added.
