### ISSUE TITLE
Feature: Update configuration to Add Debug button for NestJs

### ISSUE THREAD

**Issue by Tyler-V** [nrwl/nx#1602]
Using the Angular Console in VSCode, its a great addition and makes it convenient to launch an app and api without opening additional terminals in vscode. Thank you for that.

My questions is, how can I add a Debug task that would allow me to set breakpoints and debug NestJs? I'm assuming these tasks are pulled from the architect section in angular.json.

Is it possible to create a task that serves the app and starts the debugger to attach to the node process?

Currently I am serving the API from the angular console extension and just running VSCode - Debug from the application but it seems like this could be incorporated? Any tips?

```
{
    "type": "node",
    "request": "attach",
    "name": "Debug NestJs",
    "sourceMaps": true,
    "port": 7777
  } 
```

https://github.com/nrwl/angular-console/issues/614

**Comment by johannesschobel** [comment]
Dear @Tyler-V ,

you may want to look at the solution proposed in this issue here https://github.com/nrwl/nx/issues/1506

Especially this GIST here ( https://gist.github.com/toddwseattle/71f1c2b7b439c6523cc543edab030842 ) is a life-changer for me!

All the best

**Comment by rarmatei** [comment]
Hey @Tyler-V please check the related issue posted above.

Here's another related VSCode template useful for debugging: https://gist.github.com/juristr/66955e0c362d0a9e7c8d84825f7b71ef

As there hasn't been a lot of other activity around here - I'll close this. But please free to comment on the above related issue, or open a new one. Thanks!
