### ISSUE TITLE
NX 15.9.0 - @nrwl/devkit injects unexpected things into project.json when using updateProjectConfiguration

### ISSUE THREAD

**Issue by fbartho** [nrwl/nx#16028]
### Current Behavior

We just upgraded to NX 15.9.0, and that switched us from using workspace.json so we're changing some code that was parsing workspace.json and enforcing certain conventions and standards.

Instead of directly accessing workspace.json we're now using `@nrwl/devkit` to get the project configs.
So far so good!

One of our linting rules is that `generatePackageJson` (and certain other `build::options`) must be explicitly specified instead of left to the default, and applications vs libraries have certain rules around them. We're able to access the `targets` and check the options.

Unfortunately, when we call `updateProjectConfiguration` with this newly set option and subsequently `flushChanges` to disk, we see some additional fields being written.

```diff
diff --git a/apps/firestore-data-extraction-scripts/project.json b/apps/firestore-data-extraction-scripts/project.json
index 62d10f073..e0f740ca2 100644
--- a/apps/firestore-data-extraction-scripts/project.json
+++ b/apps/firestore-data-extraction-scripts/project.json
@@ -6,16 +6,23 @@
 	"tags": ["sync"],
 	"targets": {
 		"build": {
+			"dependsOn": [
+				"^build",
+				{
+					"target": "build",
+					"projects": "dependencies"
+				}
+			],
 			"executor": "@nrwl/webpack:webpack",
 			"outputs": ["{options.outputPath}"],
 			"options": {
 				"outputPath": "apps/firestore-data-extraction-scripts/dist",
 				"main": "apps/firestore-data-extraction-scripts/src/main.ts",
 				"tsConfig": "tsconfig.json",
 				"webpackConfig": "libs/server-shared-configs/webpackConfig.application.js",
 				"target": "node",
-				"compiler": "tsc"
+				"compiler": "tsc",
+				"generatePackageJson": false
 			},
 			"configurations": {
 				"production": {
@@ -60,22 +67,26 @@
 			}
 		},
 		"lint": {
+			"inputs": ["default", "{workspaceRoot}/.eslintrc.json"],
 			"executor": "@nrwl/linter:eslint",
 			"outputs": ["{options.outputFile}"],
 			"options": {
 				"hasTypeAwareRules": true,
 				"lintFilePatterns": ["apps/firestore-data-extraction-scripts/**/*.ts"],
 				"outputFile": "reports/eslint/firestore-data-extraction-scripts.json"
-			}
+			},
+			"configurations": {}
 		},
 		"test": {
+			"inputs": ["default", "^default", "{workspaceRoot}/jest.preset.js"],
 			"executor": "@nrwl/jest:jest",
 			"outputs": ["{options.outputFile}"],
 			"options": {
 				"jestConfig": "apps/firestore-data-extraction-scripts/jest.config.ts",
 				"outputFile": "reports/jest/firestore-data-extraction-scripts.json",
 				"passWithNoTests": true
-			}
+			},
+			"configurations": {}
 		},
 		"deploy": {
 			"executor": "nx:run-commands",
```

Notice in particular, the unexpected `"inputs"` and the `dependsOn … "^build"` entries (and also the blank `configurations` hashes -- less worried about that 3rd case, however).

### Expected Behavior

I expected only the field I modified to be written in the project.json (Ideally this would be a 1-line change! but I was prepared for field reorganization)

I had just migrated from workspace.json using the automatic migration provided by NX, so I know that I didn't customize or otherwise manipulate `project.json`. I expected the automatic migration to produce the same results that I would get from `updateProjectConfiguration` -- since the behavior of both is controlled by NX code.

- Is there a different `updateProjectConfiguration` that doesn't include these fields?
- Is there a way to sanitize the output?
- Is this output harmful?

### Steps to Reproduce

1. Start with an NX workspace setup with some build targets
2. Pick a project, target in that project, and a target-option you want to change. eg. `generatePackageJson`

As pseudo code:
```typescript
import {
	readAllWorkspaceConfiguration,
	updateProjectConfiguration,
} from "@nrwl/devkit";
import { FsTree, flushChanges, printChanges } from "nx/src/generators/tree"; 

const tree = new FSTree(workspaceRootPath);
const config = readAllWorkspaceConfiguration();
const projectName = "firestore-data-extraction-scripts";
const projectConfig = config.projects[projectName];
const buildTargetConfig = projectConfig.targets["build"];

// Mutate the option we want to change
const buildTargetConfig.options["generatePackageJson"] = false;

updateProjectConfiguration(tree, projectName, projectConfig);
flushChanges(tree.listChanges());
```
3. use git to inspect the diff in your project.json

### Nx Report

```shell
$ [snipped]/node_modules/.bin/nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.11.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx                      : 15.9.0
   @nrwl/js                : 15.9.0
   @nrwl/jest              : 15.9.0
   @nrwl/linter            : 15.9.0
   @nrwl/workspace         : 15.9.0
   @nrwl/cli               : 15.9.0
   @nrwl/devkit            : 15.9.0
   @nrwl/eslint-plugin-nx  : 15.9.0
   @nrwl/express           : 15.9.0
   @nrwl/node              : 15.9.0
   @nrwl/nx-plugin         : 15.9.0
   @nrwl/tao               : 15.9.0
   @nrwl/web               : 15.9.0
   @nrwl/webpack           : 15.9.0
   @nrwl/nx-cloud          : 15.3.3
   typescript              : 4.9.5
   ---------------------------------------
   Local workspace plugins:
   	 @hca/package-generator
```

### Failure Logs

```shell
N/A
```

**Comment by AgentEnder** [comment]
Update project configuration should use the output from read project configuration as the starting point- readAllWorkspaceConfiguration reads from the project graph which has extra fields
