### ISSUE TITLE
NX report unsatisfied version for date-fns-tz

### ISSUE THREAD

**Issue by zeskysee** [nrwl/nx#16031]
### Current Behavior

I have installed date-fns-tz to in my nx angular module federation project.

It did not recognise the version and complain that the version is not found.
When I load my page, it show blank screen.

I get following error in browser:
- Error: Unsatisfied version 0 from maintenance of shared singleton module date-fns-tz (required =2.0.0)

I get the following warning in console:
- Warning: No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file /my-project/node_modules/date-fns-tz/esm/package.json, or manually specify version in shared config.

I have to workaround by adding the following configuration to `module-federation-config.js` then my page can be rendered.
```
  shared: (name, config) => {
    if (name === 'date-fns-tz') {
      return {
        ...config,
        strictVersion: false,
      }
    }
  },
```

### Expected Behavior

NX module federation able to read date-fns-tz esm version properly and able to render the page instead of blank screen.

### GitHub Repo

https://github.com/zeskysee/nx-module-fed-with-unsatify-dep

### Steps to Reproduce

1. Clone project
2. npm start
3. Click on remote link in home page

### Nx Report

```shell
 >  NX   Report complete - copy this into the issue template

   Node : 19.6.0
   OS   : darwin x64
   npm  : 9.4.0

   nx (global)             : 15.9.2
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
```

### Failure Logs

```shell
Error: Unsatisfied version 0 from maintenance of shared singleton module date-fns-tz (required =2.0.0)
```

### Additional Information

https://github.com/marnusw/date-fns-tz/blob/master/src/esm/package.json

**Comment by AgentEnder** [comment]
Can you please fill in the `nx report` section?

**Comment by zeskysee** [comment]
Updated with `nx report`

**Comment by Coly010** [comment]
No, this makes sense.

Your Host application is not using `date-fns-tz` therefore you need to tell your remote application via the module-federation.config.js that it should not expect this dependency to be shared and instead that it should be downloaded with your remote bundle when you access your remote via your host.

Your host will fetch the remote bundle across the wire.
Your remote is set up to assume that certain dependencies will be available on the host.
`date-fns-tz` is not used in the host, so it's not included in the bundle.
When trying to load the remote, webpack realises that `date-fns-tz` does not exist on the host, and an error is thrown.

The better solution would be to do this:

```
if (name === 'date-fns-tz') {
      return false;
    }
```

To specify that this dependency is not intended to be shared and should be bundled in your remote.

An alternative is to set up an implicit dependency from your host to your remote, this way, the graph can be analysed to see what dependencies remote will require and they can be bundled and shared from your host.

We call out in our docs that there are times you need to configure sharing: https://nx.dev/recipes/module-federation/faster-builds#excluding-or-overriding-shared-libraries

**Comment by zeskysee** [comment]
@Coly010 May I know how to setup implicit dependency from my host to my remotes?

For the documentation, could we add the error message / warning in the documentation so when google search, it can bring toward that section?

Thanks for the quick feedback.

**Comment by Coly010** [comment]
Add the name of the remotes to an `implicitDependencies` array in your host's project.json

```
"implicitDependencies": ["remoteName"]
```
