### ISSUE TITLE
Support for local executors, generators and plugins with `.ts` extension

### ISSUE THREAD

**Issue by GreenTea124** [nrwl/nx#16033]
## Description

Support for local executors, generators and plugins written in TypeScript (without manual transpilation).

## Motivation

More and more tools allow `.ts` configuration files. For example:
- Webpack supports `webpack.config.ts`
- Taiwlind CSS added support for `tailwind.config.ts` in recent v3.3
- Storybook is fully configurable via `main.ts` / `manager.ts` / `preview.ts` files since v7.0

It would be nice if NX would support custom workspace executors, generators and plugins written in `.ts` out of the box too.

Currently, it's achievable with solution like this:
```ts
// ./nx.json
{ plugins: ['./nx-plugins/plugin.dist.js'] }

// ./nx-plugins/plugin.dist.js
require("ts-node").register();
module.exports = require("./plugin.ts");

// ./nx-plugins/plugin.ts
import path from "path";
```

But a native support could be more performant (better caching) and more accessible developers.

## Suggested Implementation

NX could transiple custom plugins "on the fly" with one of these packages:
https://www.npmjs.com/package/ts-node
https://www.npmjs.com/package/jiti
https://www.npmjs.com/package/@swc/register

More are mentioned here:
https://github.com/privatenumber/ts-runtime-comparison

Developer would be able to write executor/generator/plugin using common.js/ESM/TypeScript, and NX based on the file extension would decide how it will load it.

**Comment by AgentEnder** [comment]
This is already supported - see: https://nx.dev/recipes/generators/local-generators

**Comment by GreenTea124** [comment]
@AgentEnder 
Oh I didn't know it's already supported for generators. It seems however that it's not supported for custom plugins:

### Setup

nx.json
```jsonc
{ 
   "plugins": ["./plugin.ts"],
   // Other config
}
```

plugin.ts
```ts
import { NxPlugin } from "@nrwl/devkit";

export const projectFilePatterns: NxPlugin["projectFilePatterns"] = [
	"project.json",
	"package.json"
];

// More code...
```

## Output

```
npx nx --version      
15.8.7
npx nx graph --verbose

 >  NX   Cannot use import statement outside a module
```

**Comment by AgentEnder** [comment]
It should be - generate the plugin via the nx plugin generator and use it via its import path
