### ISSUE TITLE
NX 15.9.2 - Unable to import custom library with @nrwl/js into a Node app generated with @nrwl/node 

### ISSUE THREAD

**Issue by SebasG22** [nrwl/nx#16030]
### Current Behavior

I'm trying to import a custom library that was generated with @nrwl/js into a Node app that was generated with @nrwl/node, but I'm running into issues.

I've tried using both esbuild and webpack as the bundler for the Node app, but neither of them seems to work. When I try to import the library, I get an error message that says "Module not found".

### Expected Behavior

The module from the custom library should be successfully imported into the Node app and the app should run without any issues.

### GitHub Repo

https://github.com/SebasG22/nx-demo-node

### Steps to Reproduce

1.  Generate a new custom library with @nrwl/js.
2. Generate a new Node app with @nrwl/node.
4. Try to import a function from the custom library in the Node app.
5. Run the Node app with either esbuild or webpack as the bundler.

### Nx Report

```shell
Node : 16.19.0
   OS   : linux x64
   yarn : 1.22.19
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/esbuild           : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/vite              : 15.9.2
   @nrwl/webpack           : 15.9.2
   @nrwl/nx-cloud          : 15.3.5
   typescript              : 4.9.5
```

### Additional Information

I've tried searching through the Nx documentation and the issue tracker, but I couldn't find any information on this specific issue. Any help would be greatly appreciated.

**Comment by jaysoo** [comment]
Hi @SebasG22 I think this workspace was created as a package-based workspace, which is supposed to be like a normal npm/yarn/pnpm workspaces, where dependencies must be setup with the respective workspace settings. 

e.g. with npm (https://docs.npmjs.com/cli/v7/using-npm/workspaces)

```
"workspace": ["packages/a", "packages/b"]
```

Then when you install packages, those workspace libs will be linked correctly.

To enable a more integrated experience with Nx, remove this line from your `nx.json` and you should see the connections being made when running `npx nx graph`.

```
"extends": "nx/presets/npm.json",
```

We will be reviewing the package-based experience, and converting between that and integrated in May/June, so hopefully that will address any confusion here.
