### ISSUE TITLE
lockfile generation is still buggy with 15.9.2

### ISSUE THREAD

**Issue by vicb** [nrwl/nx#16047]
### Current Behavior

```
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Missing: @types/geojson@7946.0.10 from lock file
```

### Expected Behavior

`npm ci` should work

### GitHub Repo

https://github.com/vicb/flyxc

### Steps to Reproduce

1. Run `nx deploy` in the root dir. In fact this deploy to GCP so you might just want to build `fxc-server` and `npm ci` the lock file. There are details in the previous issue #15366

The code is the *fail* branch

### Nx Report

```shell
$ nx report
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node : 18.10.0
   OS   : linux x64
   npm  : 8.19.2
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/express           : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/vite              : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-container : 4.0.3
```

### Failure Logs

```shell
See above
```

### Additional Information

Not that this is a follow up issue of #15366 and a few other issues that predated.

Lockfile generation doesn't seem like an easy problem to solve... good luck.

**Comment by waitingsong** [comment]
got same issue

**Comment by nehalist** [comment]
Are there any workarounds for now? I'm using `npm i` now on CI, which surely isn't a good idea (but at least my builds aren't failing anymore).

**Comment by nehalist** [comment]
Fixed it in my case: I found out that the reason my lock file was out of sync was a different node/npm version on CI. Switching locally to the same CI versions and re-generating the lock file solved my issue.

**Comment by vicb** [comment]
Oh interesting...
I'm actually using the lock file from a Docker image and it might be pain to sync those the npm use there with my local version.
@nehalist were you versions vastly different ?

**Comment by nehalist** [comment]
> Showing 1 changed file with 1,769 additions and 524 deletions.

Went from Node `v16.13` to `v16.20`. Used [nvm](https://github.com/nvm-sh/nvm) to switch locally, which made it fairly easy to switch.

**Comment by vicb** [comment]
Should be linked to npm. Would be good to know if a minor version
difference broke it or major.

**Comment by nehalist** [comment]
According to nvm `v16.13` uses npm `v8.1.2`, while `v16.20` uses `v8.19.4`

**Comment by meeroslav** [comment]
Sorry for the delay, @vicb 

I could not reproduce it locally on npm `v8.19.2`.

Is upgrading the `npm` an option for you?

**Comment by meeroslav** [comment]
Using npm `v8.1.2` with node `v18.12.1` still passes for me.
It must be some combo of versions that makes it fail.

If you can reproduce it constantly still and have time, I would gladly hop on a meeting to debug this with you.

**Comment by vicb** [comment]
Thanks for looking into that @meeroslav 

I have just updated to 

```
$ node --version
v18.16.0
$ npm --version
9.5.1
```

And it seems to work now.

It it still not clear to me if the issue is with `npm` or `nx`?
I never had any problem deploying to App Engine before switching to a Nx mono repo with the lockfile.

But as I now have a working solution I don't think there is a need to spend time trying to understand what could have gone wrong.

If this issue re-appear we can still try to investigate at that point.

Have a great day

**Comment by meeroslav** [comment]
Sometimes the installations get messed up. We had this occasionally before the lock file parsing/pruning was implemented. Deleting node_modules and reinstalling packages was usually the solution for those cases.

Without a way to reproduce it's hard to tell if `nx` missed something while parsing or if the lock file/installation was not correct.
