### ISSUE TITLE
Allow generateFile to return a promise after invoking `tree.write`

### ISSUE THREAD

**Issue by terrymun** [nrwl/nx#16041]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
I encountered an issue when working with `nx workspace-generator`. In my generator, I am invoking `generateFiles` from `@nrwl/devkit` to create files: that worked without any issue.

However, the next step in my generator involves performing some operations on the generated files (in my use-case, they're generated in new folders that did not exist before). Attempting to access this newly created path will result in an error, because by the time `generateFiles` is finished running, the folders are not guaranteed to have been created in the file system.

Based on my (very limited) understanding of the inner workings of `generateFiles`, it calls `tree.write` internally, which [internally calls `tree.overwrite` or `tree.create`](https://github.com/nrwl/nx/blob/6ba60a0d2f9c46cf7167aa9f3b11f538dceeec49/packages/devkit/src/utils/invoke-nx-generator.ts#L204-L208). The [`write` method contains async logic](https://github.com/nrwl/nx/blob/6ba60a0d2f9c46cf7167aa9f3b11f538dceeec49/packages/devkit/src/utils/invoke-nx-generator.ts#L34-L40) but we are [not returning the promise from `tree.write`](https://github.com/nrwl/nx/blob/6ba60a0d2f9c46cf7167aa9f3b11f538dceeec49/packages/devkit/src/generators/generate-files.ts#L99).

## Motivation
In some complex workspace generation workflow, there might be additional steps after the invocation of `generateFiles` that depends on the files/folders created by this function. However, since this function has some internal async logic, it is not possible to guarantee that the file paths are accessible in the filesystem after `generateFiles` is called.

I hope my request/suggestion makes sense: please let me know if I should add more information or furnish you with additional details ❤️ 

## Suggested Implementation
I do not have a great suggestion for a forward migration path, as returning a promise from `generateFiles()` might break existing workflows of others :( perhaps an Nx maintainer/contributer can help shed some light on a possible implementation suggestion?

## Alternate Implementations
_n.a._

**Comment by AgentEnder** [comment]
Inside of a generator, **_nothing_** is written to disk until after the generator has ran. This is what powers --dry-run, and not leaving bad files on disk in case of error.

If you need to execute a post-generate task, you can do so by returning a callback from your generator. If you need to modify files after a generateFiles call, you can use tree.read / tree.write rather than node fs ops.

**Comment by terrymun** [comment]
@AgentEnder Thanks for the clarification and explanation 👍
