### ISSUE TITLE
Parallel tests with BABEL TypeError 

### ISSUE THREAD

**Issue by keithchan-bowtie** [nrwl/nx#16063]
### Current Behavior

When I enable parallel run for my tests, sometimes the tests would fail with the following error message on CircleCI.

```
FAIL  src/lib/image/Image.spec.tsx
  ● Test suite failed to run

    TypeError: [BABEL]: _interopRequireDefault is not a function (While processing: /home/circleci/my-project/node_modules/babel-plugin-macros/dist/index.js)

      at Object.<anonymous> (../../node_modules/babel-plugin-macros/dist/index.js:5:17)
      at Object.newLoader (../../node_modules/pirates/lib/index.js:141:7)
```
if I updated the `nx.json` as following, I configure `parallel` to 1.
```json
"tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "parallel": 1
      }
    }
  },
```
The tests will be fine.

My project graph is simple as following:
App depends on Lib_A and Lib_B

The babel error will be shown if Lib_A and Lib_B tests running in parallel at the same time.

My project is a react-native project and it runs on CircleCI (android img)[https://discuss.circleci.com/t/linux-machine-executor-update-2023-q1-update/47059]

### Expected Behavior

Tests can be run in parallel without errors.

### Steps to Reproduce

1. `yarn nx run-many --all --target=test --skip-nx-cache`

### Nx Report

```shell
Node : 18.15.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/detox             : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/react-native      : 15.9.2
   @nrwl/storybook         : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/nx-cloud          : 15.3.5
   typescript              : 4.9.4
   ---------------------------------------
   Community plugins:
   @jscutlery/semver : 2.30.1
```

**Comment by barbados-clemens** [comment]
@keithchan-bowtie do you have a reproducible repo I clone to take a look at?

**Comment by keithchan-bowtie** [comment]
@barbados-clemens I might need some time to make a test project for this.
But the error only shown on CircleCI machine which is a linux machine. (My local machine is a MacOS apple silicon)

Do you think it is just linux issue?
