### ISSUE TITLE
Angular migration from 14.4.3 to latest failed 

### ISSUE THREAD

**Issue by madipta** [nrwl/nx#16077]
### Current Behavior

failed to migrate latest

### Expected Behavior

success migrate latest

### GitHub Repo

https://github.com/madipta/web-scraping

### Steps to Reproduce

1. clone the project
2. yarn install
3. yarn nx migrate latest
4. yarn install
5. yarn nx migrate --run-migrations

### Nx Report

```shell
Node : 16.19.1
   OS   : win32 x64
   yarn : 1.22.19

   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/nest              : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   apollo-angular : 2.6.0
   ng-zorro-antd  : 14.3.0
```

### Failure Logs

```shell
>  NX   Failed to run update-platform-server-exports from @nrwl/angular. This workspace is NOT up to date!


 >  NX   rule is not a function


TypeError: rule is not a function
    at callRuleAsync (J:\projects\web-scraping\node_modules\@angular-devkit\schematics\src\rules\call.js:78:24)
    at J:\projects\web-scraping\node_modules\@angular-devkit\schematics\src\rules\call.js:73:40
    at Observable._subscribe (J:\projects\web-scraping\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\observable\defer.js:10:21)
    at Observable._trySubscribe (J:\projects\web-scraping\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (J:\projects\web-scraping\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Observable.js:30:22)
    at MapOperator.call (J:\projects\web-scraping\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\map.js:32:23)
    at Observable.subscribe (J:\projects\web-scraping\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Observable.js:25:31)
    at Object.innerSubscribe (J:\projects\web-scraping\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\innerSubscribe.js:102:23)
    at MergeMapSubscriber._innerSub (J:\projects\web-scraping\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:80:50)
    at MergeMapSubscriber._tryNext (J:\projects\web-scraping\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:74:14)
error Command failed with exit code 1.
```

**Comment by Coly010** [comment]
Hi, I know this might sound counter productive, but for the best results when migrating, it would be better to do this in multiple steps given the version of Nx that you are currently on.

Try doing:

1. `yarn nx migrate 15.2.0` - This will take you to Angular 15
2. `yarn nx migrate --run-migrations`
3. `yarn nx migrate  15.5.0` - This will take you to Angular 15.1
4. `yarn nx migrate --run-migrations`
5. `yarn nx migrate 15.8.0` - This will take you to Angular 15.2
6. `yarn nx migrate --run-migrations`
7. `yarn nx migrate latest` - This will bring you up to latest Nx
8. `yarn nx migrate --run-migrations`

I know there are a lot of steps here, but many things have changed between Nx 14.4 and the current version of Nx. This more verbose migration path will be the safest path through the migration.

**Comment by wolsk1** [comment]
For me it worked with running again `nx migrate latest` followed by `nx mirgrate --run-migrations` maybe it will actually help you

**Comment by madipta** [comment]
> Hi, I know this might sound counter productive, but for the best results when migrating, it would be better to do this in multiple steps given the version of Nx that you are currently on.
> 
> Try doing:
> 
>     1. `yarn nx migrate 15.2.0` - This will take you to Angular 15
> 
>     2. `yarn nx migrate --run-migrations`
> 
>     3. `yarn nx migrate  15.5.0` - This will take you to Angular 15.1
> 
>     4. `yarn nx migrate --run-migrations`
> 
>     5. `yarn nx migrate 15.8.0` - This will take you to Angular 15.2
> 
>     6. `yarn nx migrate --run-migrations`
> 
>     7. `yarn nx migrate latest` - This will bring you up to latest Nx
> 
>     8. `yarn nx migrate --run-migrations`
> 
> 
> I know there are a lot of steps here, but many things have changed between Nx 14.4 and the current version of Nx. This more verbose migration path will be the safest path through the migration.

migrate to 15.2.0 completed with warning:

Skipping migration for project admin-e2e. Unable to determine 'tsconfig.json' file in workspace config.
Skipping migration for project auth. Unable to determine 'tsconfig.json' file in workspace config.
Skipping migration for project gql. Unable to determine 'tsconfig.json' file in workspace config.
Skipping migration for project orm. Unable to determine 'tsconfig.json' file in workspace config.
Skipping migration for project public-e2e. Unable to determine 'tsconfig.json' file in workspace config.
Skipping migration for project pubsub. Unable to determine 'tsconfig.json' file in workspace config.
Skipping migration for project scrape-queue. Unable to determine 'tsconfig.json' file in workspace config.
Skipping migration for project scraper. Unable to determine 'tsconfig.json' file in workspace config.

but the app is working

thank you, i will try the next step later

**Comment by madipta** [comment]
> > Hi, I know this might sound counter productive, but for the best results when migrating, it would be better to do this in multiple steps given the version of Nx that you are currently on.
> > Try doing:
> > ```
> > 1. `yarn nx migrate 15.2.0` - This will take you to Angular 15
> > 
> > 2. `yarn nx migrate --run-migrations`
> > 
> > 3. `yarn nx migrate  15.5.0` - This will take you to Angular 15.1
> > 
> > 4. `yarn nx migrate --run-migrations`
> > 
> > 5. `yarn nx migrate 15.8.0` - This will take you to Angular 15.2
> > 
> > 6. `yarn nx migrate --run-migrations`
> > 
> > 7. `yarn nx migrate latest` - This will bring you up to latest Nx
> > 
> > 8. `yarn nx migrate --run-migrations`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I know there are a lot of steps here, but many things have changed between Nx 14.4 and the current version of Nx. This more verbose migration path will be the safest path through the migration.
> 
> migrate to 15.2.0 completed with warning:
> 
> Skipping migration for project admin-e2e. Unable to determine 'tsconfig.json' file in workspace config. Skipping migration for project auth. Unable to determine 'tsconfig.json' file in workspace config. Skipping migration for project gql. Unable to determine 'tsconfig.json' file in workspace config. Skipping migration for project orm. Unable to determine 'tsconfig.json' file in workspace config. Skipping migration for project public-e2e. Unable to determine 'tsconfig.json' file in workspace config. Skipping migration for project pubsub. Unable to determine 'tsconfig.json' file in workspace config. Skipping migration for project scrape-queue. Unable to determine 'tsconfig.json' file in workspace config. Skipping migration for project scraper. Unable to determine 'tsconfig.json' file in workspace config.
> 
> but the app is working
> 
> thank you, i will try the next step later

migrate  15.5.0 error:
react component svg

migrate 15.8.0 error
Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/mini-css-extract-plugin/dist/loader.js)

**Comment by harleyz** [comment]
Also had this issue today.  I am going to to upgrade to a lower 15 version
