### ISSUE TITLE
Next public folder is not served in dev mode

### ISSUE THREAD

**Issue by anthodb** [nrwl/nx#16079]
### Current Behavior

This is the same bug as this one which is closed: https://github.com/nrwl/nx/issues/11524
Files are correcly copied using the output path but not served from there using the serve executor for next

### Expected Behavior

The files copied in the output public folder should be used with the "serve" command.

### Steps to Reproduce

1. use a shared UI library with public folder.
2. in your app project.json, use the options/assets glob system as this one
3. "build": {
      "executor": "@nrwl/next:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "dependsOn": [],
      "options": {
        "root": "apps/myApp",
        "outputPath": "dist/apps/myApp",
        "assets": [
          {
            "glob": "**/*",
            "input": "./libs/shared-ui/public/fonts",
            "output": "/fonts/"
          },
          {
            "glob": "**/*",
            "input": "libs/i18n/public/locales",
            "output": "locales"
          },
          {
            "glob": "**/*",
            "input": "libs/shared-ui/public/images",
            "output": "images"
          }
        ]
      },
4. use nx serve command 
5. the assets are correctly copied in the "dist/apps/myApp/public" folder.
6. But we got 404 issue because the "serve" executor is trying to reach the apps/myApp/public folder (not the dist/apps/.. from the output path)

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : darwin x64
   npm  : 8.3.1
   
   nx                      : 15.8.9
   @nrwl/js                : 15.8.9
   @nrwl/jest              : 15.8.9
   @nrwl/linter            : 15.8.9
   @nrwl/workspace         : 15.8.9
   @nrwl/cli               : 15.8.9
   @nrwl/cypress           : 15.8.9
   @nrwl/devkit            : 15.8.9
   @nrwl/eslint-plugin-nx  : 15.8.9
   @nrwl/next              : 15.8.9
   @nrwl/nx-plugin         : 15.8.9
   @nrwl/react             : 15.8.9
   @nrwl/rollup            : 15.8.9
   @nrwl/storybook         : 15.8.9
   @nrwl/tao               : 15.8.9
   @nrwl/web               : 15.8.9
   @nrwl/webpack           : 15.8.9
   typescript              : 5.0.2
```

**Comment by anthodb** [comment]
@mandarini Thanks for your fast reply, I confirm the issue is also there on the latest version 15.9.2. Assets are served from the app folder, not the dist folder. So public assets from shared library are not correctly served when using the "serve" command. This is a regression as this was a bug some months ago, then it was resolved, then it's back again :/

**Comment by jaysoo** [comment]
@anthodb The `outputPath` should point to the app folder not dist when running in development mode.

For example:

```json
{
  "name": "demo",
  ...
  "targets": {
    "build": {
      "executor": "@nrwl/next:build",
      "outputs": [
        "{options.outputPath}"
      ],
      "defaultConfiguration": "production",
      "options": {
        "root": "apps/demo",
        "outputPath": "dist/apps/demo",
        "assets": [...]
      },
      "configurations": {
        "development": {
          "outputPath": "apps/demo"
        },
        "production": {}
      }
  },
  ...
}
```

This means that when running `nx serve`, the assets are copied in to the `<app-dir>/public` folder rather than `dist/<app-dir>/public`. Note that this means you should also add some entries to your `.gitignore` file to not commit those files.

**Comment by jaysoo** [comment]
I'll close this issue, but if you still have problems feel free to re-open with a reproduction repo.

**Comment by anthodb** [comment]
@jaysoo This doesn't look like a proper solution for our project. 
We have multiple files in the public apps folders (robots.txt, favicon, etc..) and those must be saved in the version control. 
Making all the files in shared public libraries copied into the app public folder means we need to add gitignore entries for all the files and folders that will be added from the shared libs public folders. 
It was working in previous versions, and it seemed more intuitive to have the dist folder used for serving the assets.
Is there a specific reason why it was done this way? Do you have any other recommandation on the way to structure our project if we want shared public folder ?
Thanks a lot already for your reply and the great work done on NX!

**Comment by lourd** [comment]
I also just ran into this. I've made a repro here https://github.com/lourd/nx-next-generated-static-file-bug-repro. Please take a look @jaysoo and let me know if there's any more information I can provide!
