### ISSUE TITLE
targetDefaults settings not working

### ISSUE THREAD

**Issue by ak274** [nrwl/nx#16071]
### Current Behavior

After updating nx  15.8.8 to 15.9.2 `nx test app_name`  doesn't reflect on the targetDefaults settings in the nx.json. I have configured that whenever I run test target it should run the test with all the deps but its just running the app only and not its deps.
![image](https://user-images.githubusercontent.com/16129430/229583206-2276c575-583f-455c-bea0-c4cb53921d57.png)

Note: These configs were working till v15.8.8

### Expected Behavior

It should run all the deps of a app

### Steps to Reproduce

1. Add a dependency in your angular app and run tests for app you can see the dep tests are not running 

### Nx Report

```shell
Node : 18.15.0
   OS   : win32 x64
   npm  : 9.5.0

   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/nx-plugin         : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ng-bootstrap/ng-bootstrap : 14.1.0
   @ngrx/effects              : 15.3.0
   @ngrx/entity               : 15.3.0
   @ngrx/router-store         : 15.3.0
   @ngrx/store                : 15.3.0
   @ngrx/schematics           : 15.3.0
   @ngrx/store-devtools       : 15.3.0
   ---------------------------------------
   Local workspace plugins:
         @app/plugins
```

**Comment by AgentEnder** [comment]
Does this work if you use the "^test" syntax rather than the expanded object? I'm investigating on our side.

**Comment by AgentEnder** [comment]
I can't repro this in a new repository - can you provide a sample repo? 
![image](https://user-images.githubusercontent.com/6933928/229606893-b6a6676c-6d3b-4bcc-bd00-d7fc255cd0b5.png)

This was created with:
1. `npx create-nx-workspace@latest test-deps --preset react-monorepo --no-nxCloud --appName react-app
2. npx nx g lib react-lib
3. Update nx.json with `"dependsOn": [{ "target": "test", "projects": "dependencies", "params": "forward"}]`
4. Update apps/react-app/src/app/nx-welcome.tsx with `import { ReactLib } from "@target-deps/react-lib"`
5. npx nx test react-app

**Comment by ak274** [comment]
I have a project where I have MFE set up, Now after digging deep I have realized that tests with deps not running for remote applications and their dependent deps...

If you run tests for host app ie. `nx test host` you can see that it running tests for deps also.

But try running tests for remote-one and remote-two apps. You can see that its not waiting to run tests on deps and directly running them for the app only.

Here is the repo with reproduction of the issue:-- 

https://github.com/ak274/mfe-issue

**Comment by ak274** [comment]
@AgentEnder I think this issue can be that nx is not able to define the dependencies between libs. Because I can see that libs which are directly dependent of my app graph is not showing them as dependent?

**Comment by AgentEnder** [comment]
After running `nx reset`, I started to see the correct behavior. Your correct that the dependencies were not present prior to that. Let me check if @FrozenPandaz can repro it.

**Comment by ak274** [comment]
`nx reset ` resolved the issue with dependencies not being  recognized after update.
