### ISSUE TITLE
nx report reports packages as "Community plugins" when they are not:

### ISSUE THREAD

**Issue by PowerSupply** [nrwl/nx#16085]
### Current Behavior

`nx report` reports things that are not community plugins as community plugins.

Example:
Having "@twittwer/compodoc": "1.5.3" in package.json causes it to be reported as a plugin:
```
   ---------------------------------------
   Community plugins:
   @twittwer/compodoc          : 1.5.3
```

### Expected Behavior

@twittwer/compodoc should not be reported as community plugin.

### Steps to Reproduce

1. Run `nx report` with "@twittwer/compodoc": "1.5.3" as a dependency in package.json

### Nx Report

```shell
...
   ---------------------------------------
   Community plugins:
   @twittwer/compodoc          : 1.5.3
```

**Comment by AgentEnder** [comment]
That package provides generators and executors, according to its package.json

https://cdn.jsdelivr.net/npm/@twittwer/compodoc/package.json
```json
{
  "name": "@twittwer/compodoc",
  "version": "1.9.0",
  "main": "src/index.js",
  **"generators": "./generators.json",**
  **"executors": "./executors.json",**
  "dependencies": {
    "@nrwl/devkit": "^15.0.0",
    "nx": "^15.0.0",
    "tslib": "^2.4.0"
  },
  "peerDependencies": {
    "@compodoc/compodoc": "^1.1.15"
  },
  "private": false,
  "license": "MIT",
  "author": "Tobias Wittwer <t.wittwer95@gmail.com>",
  "repository": {
    "type": "git",
    "url": "https://github.com/twittwer/nx-tools.git"
  },
  "homepage": "https://github.com/twittwer/nx-tools/tree/main/packages/compodoc#readme",
  "bugs": {
    "url": "https://github.com/twittwer/nx-tools/issues"
  },
  "keywords": [
    "nx-plugin",
    "compodoc",
    "documentation"
  ],
  "types": "./src/index.d.ts"
}
```

This means it is effectively a community plugin. We can also see that in the keywords its an nx-plugin, which is a community plugin. It is also in the community plugin registry: https://nx.dev/community#plugin-directory
