### ISSUE TITLE
Removed library still affects NX repo

### ISSUE THREAD

**Issue by jaqua** [nrwl/nx#16091]
### Current Behavior

I removed a library from the monorepo using nx console. The library and its folder is deleted and library is removed in tsconfig.base.json file. Everythin seems fine.

But running all tests gives me an error for the removed library:

      nx run project-data-access-new-case:test
       >  NX   Can't find a root directory while resolving a config file path.
       
          Provided path to resolve: /Users/source/libs/project/data-access-new-case/jest.config.ts
          cwd: /Users/source
          Pass --verbose to see the stacktrace.

Yes of course the jest.config.ts file is not existing, as it is removed. I don't understand why NX is looking for this library, although it shouldn't exist anymore.

Even the nx console remembers the library: If I want to remove another library, the autocomplete function still shows the removed library. Of course it fails to run the remove, as the files aren't existing anymore.

### Expected Behavior

Removed library shouldn't affect NX in any way...

### Steps to Reproduce

1.

### Nx Report

```shell
Node : 18.12.1
   OS   : darwin arm64
   npm  : 8.19.2
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/detox             : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/nest              : 15.9.2
   @nrwl/next              : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/react-native      : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
```

**Comment by geraparra** [comment]
I'm facing the same issue here with the same version, just waiting for info about it.

**Comment by jaqua** [comment]
I would like to know how NX is calculating which apps/libs are affected by the command. For example `nx run-many --all --target=test` is also looking for the removed lib. Obviously NX is not using tsconfig file, nor is it looking for folders. So there have to be another place, where the info about the removed lib is persisting...

**Comment by PointSingularity** [comment]
I had a similar problem, but I useing ```nx reset``` fixed it, by clearing the cache.

**Comment by jaqua** [comment]
@PointSingularity You are right. That helped. Thanks for that.

**Comment by PointSingularity** [comment]
@jaqua I think this wasn't the case in previous versions of NX. You didn't have to use ```nx reset```. So this might be a bug, maybe it should stay open.

**Comment by meeroslav** [comment]
Please keep this open until we investigate it. 

Possibly related to https://github.com/nrwl/nx/issues/15964

**Comment by the-ult** [comment]
Same thing is happening with linting.
Still get linting errors about removed/moved projects:

- Removing `./cache` folder and `node_modules/.cache` or even removing everything (.cache and node_modules) did not help.
- `npx nx reset` does not work either


```
✖  nx run shared-info:lint
       Linting "shared-info"...
       
        >  NX   All files matching the following patterns are ignored:
       
          - 'libs/shared/info/src/**/*.ts'
          - 'libs/shared/info/src/**/*.html'
          
          Please check your '.eslintignore' file.
          Pass --verbose to see the stacktrace.
```



```
❯ npx nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.14.0
   OS   : darwin x64
   npm  : 9.3.1
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @testing-library/angular : 13.4.0
```
