### ISSUE TITLE
New nx workspace doesn't support custom cypress commands

### ISSUE THREAD

**Issue by ca136** [nrwl/nx#1609]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

## Expected Behavior

Adding a custom Cypress command with the generated schematics should not cause an error when the tests run.

## Current Behavior

The custom commands aren't registered to due `supportFile: false` in the cypress.json file.

## Failure Information (for bugs)

Adding the minimal steps to reproduce here:
https://github.com/ca136/cypress-nx-commands/commit/d9991391140e6aa826b9242ab70ad04bfaf6bb40

### Context

Please provide any relevant information about your setup:

Used nx 8.2.0

**A minimal reproduce scenario using allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**
see github repo above

### Failure Logs

Either:
```
[tsl] ERROR in /Users/caleb.amsden/myapp/apps/myapp-e2e/src/integration/app.spec.ts(6,6)
      TS2339: Property 'login' does not exist on type 'Chainable<undefined>'.
```

Or:
```
The support file is missing or invalid.

Your `supportFile` is set to `/Users/caleb.amsden/myapp/apps/myapp-e2e/src/support/index`, but either the file is missing or it's invalid. The `supportFile` must be a `.js` or `.coffee` file or, if you're using a preprocessor plugin, it must be supported by that plugin.

Correct your `cypress.json`, create the appropriate file, or set `supportFile` to `false` if a support file is not necessary for your project.

Learn more at https://on.cypress.io/support-file-missing-or-invalid
```

## Other

Any other relevant information that will help us help you.

**Comment by yglin** [comment]
I had this issue, too, after upgrading to nx 8.
You can specifically set the path to your **support/index.ts** in **cypress.json**.
to me it looks like

` "supportFile": "./src/support/index.ts",`

And it works for me.

**Comment by FrozenPandaz** [comment]
> You can specifically set the path

Yup, please do this manually for the time being.

@bcabanes Do you remember why this was changed in this PR? https://github.com/nrwl/nx/pull/853

**Comment by ca136** [comment]
I think it might be more of a documentation issue or just user error. Something broke with our typings.d.ts for custom commands during the migration, but moving the typings inside commands.ts eventually worked.

Seems like Cypress custom commands and TypeScript don't play super well together at the moment. Feel free to close to reduce noise @FrozenPandaz!

**Comment by Amakaev** [comment]
@FrozenPandaz after adding custom commands, for instance :
`Cypress.Commands.add('login', login)`
got an error **Cannot use namespace 'Cypress' as a value.**

**Comment by vsavkin** [comment]
@FrozenPandaz @bcabanes any update on this?

**Comment by Foxandxss** [comment]
I was going to open a related issue to this so I add my information in here.

There should be a support file for custom commands typing or documentation in  how to do it yourself.

If you open `commands.ts` and you write a custom one, say:

```
const approverLogin = () => {
  return cy.get('#foo');
};

Cypress.Commands.add('approverLogin', approverLogin);
```

Something silly, but just to get the point.

You get an expected `Property 'approverLogin' does not exist on type 'cy'.ts(2339)` if you try to use it.

Some pages recommends you to create a `index.d.ts` at `support/` to do something like:

```
declare namespace Cypress {
  interface Chainable {
    approverLogin: Chainable;
  }
}
```

and perhaps wire it with a `typeRoots` in the `tsconfig` file. That doesn't fix it. The typing I wrote may be wrong, but it is still not something typescript would find. Moving the declaration to `commands.ts` would probably make it work but I believe that NX should offer a specific `d.ts` file for custom commands.

**Comment by bcabanes** [comment]
@FrozenPandaz @vsavkin I created a PR adding the capability and default examples.

**Comment by Foxandxss** [comment]
Not a big fan of that solution tho. I would love to have a separate d.ts file. To keep things simple, but I guess that would work as well.

**Comment by Foxandxss** [comment]
As @juristr mentions in another place, He found a solution:

If inside `commands.ts` you do something like: 

```
declare namespace Cypress {
  interface Chainable {
    /**
     * Custom command to select DOM element by data-cy attribute.
     * @example cy.dataCy('greeting')
    */
    dataCy(value: string): Chainable<Element>
  }
}


Cypress.Commands.add('dataCy', (value) => {
  return cy.get(`[data-cy=${value}]`)
});
```

VScode will say, hey, there is a new command, I won't give you a red wiggle anymore when you use it. Now, running `ng e2e` will say... what is that `dataCy` I don't know about? But if inside the spec file where you use it, you do a `import ../support` (or your correct path to the support folder), it will actually find it and work.

So you need to do two extra steps for a command. Create the type and import the file with the type where you use it. In a good world you only need to do the former and even better if it is in its own `d.ts` file.

**Comment by prudhvidandamudi** [comment]
> I had this issue, too, after upgrading to nx 8.
> You can specifically set the path to your **support/index.ts** in **cypress.json**.
> to me it looks like
> 
> ` "supportFile": "./src/support/index.ts",`
> 
> And it works for me.


I am facing the same issue, I have manually entered my support file path which is like this
    `"supportFile": "cypress/support/index.ts"  `
When I am running my cypress tests using test runner (**ng e2e --watch**) the tests are running fine.
 but when I am trying to run my tests using command line (**ng e2e**) it's opening the browser for 4 minutes and not running any tests. I am just seeing the window in the below screenshot for 4 mins without any test execution.

![image](https://user-images.githubusercontent.com/46937269/67233087-96502680-f410-11e9-80c8-1e0ecc306a4b.png)

Can some help me with this issue, I am actually stuck over here.

**Comment by bcabanes** [comment]
Hi @prudhvidandamudi 
We are looking currently at this issue.

**Comment by prudhvidandamudi** [comment]
Hi @bcabanes 
Thanks for replying. Is there any specific timeline for this issue to be fixed. 
Our team is blocked here, as our tests are failing when we are running through CI, as we are using the command line to trigger our tests.

**Comment by EugeneCh** [comment]
@FrozenPandaz can you please release this fix?

**Comment by dherges** [comment]
With @nrwl/workspace@8.12.0 the problem continuied to exist for me.

### Error Message

```
Oops...we found an error preparing this test file:

  src/integration/app.spec.ts

The error was:

<...>/apps/frontend-e2e/src/integration/app.spec.ts
ERROR in <...>/apps/frontend-e2e/src/integration/app.spec.ts(22,14):
TS2339: Property 'matchImageSnapshot' does not exist on type 'Chainable<JQuery<HTMLElement>>'.

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```

### Solution

`commands.ts`:

```ts
export {}

declare global {
  namespace Cypress {
    interface Chainable<Subject> {
      login(email: string, password: string): void;
      matchImageSnapshot(): Chainable<Subject>;
      matchImageSnapshot(name: string): Chainable<Subject>;
      matchImageSnapshot(options: any): Chainable<Subject>;
      matchImageSnapshot(name: string, options: any): Chainable<Subject>;
    }
  }
}
```

### Version Info

```
$ node_modules/.bin/nx --version
8.12.0
$ node_modules/.bin/cypress --version
Cypress package version: 3.8.3
Cypress binary version: 3.8.3

```

**Comment by kkoo95** [comment]
Same as @dherges.  
the subtle change
```typescript
declare global {
  namespace Cypress {
    interface Chainable<Subject> { ... }
  }
}
```

instead of the default
```ts
declare namespace Cypress {
  interface Chainable<Subject> { ... }
}
```

did the trick for me.
Note that Intellij warned me that it couldn't find my custom commands. I thought it would be just an IDE thing but running my tests failed as well

**Comment by panraj01** [comment]
> > I had this issue, too, after upgrading to nx 8.
> > You can specifically set the path to your **support/index.ts** in **cypress.json**.
> > to me it looks like
> > ` "supportFile": "./src/support/index.ts",`
> > And it works for me.
> > @FrozenPandaz
> 
> I am facing the same issue, I have manually entered my support file path which is like this
> `"supportFile": "cypress/support/index.ts" `
> When I am running my cypress tests using test runner (**ng e2e --watch**) the tests are running fine.
> but when I am trying to run my tests using command line (**ng e2e**) it's opening the browser for 4 minutes and not running any tests. I am just seeing the window in the below screenshot for 4 mins without any test execution.
> 
> ![image](https://user-images.githubusercontent.com/46937269/67233087-96502680-f410-11e9-80c8-1e0ecc306a4b.png)
> 
> **My folder structure contains .d.ts files for interfaces and .ts files for custom commands**
> ![image](https://user-images.githubusercontent.com/46937269/67233610-900e7a00-f411-11e9-8e6a-a3dbb8b6bf45.png)
> 
> Can some help me with this issue, I am actually stuck over here.

I have this same issue. Is there a solution? only difference in my case is - I moved my entire test folder outside apps/. If i reference the cypress.json under apps in workspace.json the tests work fine, but if i reference client specific cypress.json in the standalone folder like below then my test fails after 4 min saying cannot fetch the supportFile. The same test work fine in watch mode.

![image](https://user-images.githubusercontent.com/42047303/103379996-2544de00-4aad-11eb-9b9c-c5bfbefa7fc1.png)
