### ISSUE TITLE
Local generators should use available tsconfig without warnings

### ISSUE THREAD

**Issue by RolginRoman** [nrwl/nx#16107]
### Current Behavior

Warning about non-existent tsconfig.base.json

>  NX  Unable to load tsconfig-paths, workspace libraries may be inaccessible.
>  - To fix this, install tsconfig-paths with npm/yarn/pnpm

### Expected Behavior

No warnings as `{workspaceRoot}/tsconfig.json` available.

With recent changes (https://github.com/nrwl/nx/pull/15438) local plugins work correctly without tsconfig.base.json but later they're requesting non-existent tsconfig.base.json (https://github.com/nrwl/nx/blob/master/packages/nx/src/utils/nx-plugin.ts#L268).

### GitHub Repo

https://github.com/RolginRoman/tsconfig-paths-nx-example-repro

### Steps to Reproduce

1. we use tsconfig.json at the top level of repo, not tsconfig.base.json
2. generate local nx-plugin (I've generated `test-plugin`)
3. run new plugin (`yarn nx g test-plugin`)
4. warning's shown

### Nx Report

```shell
Node : 18.14.1
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/nx-plugin         : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   @nrwl/nx-cloud          : 15.3.5
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 15.3.0
   @ngrx/effects         : 15.3.0
   @ngrx/entity          : 15.3.0
   @ngrx/router-store    : 15.3.0
   @ngrx/store           : 15.3.0
   @ngrx/store-devtools  : 15.3.0
   ---------------------------------------
   Local workspace plugins:
   	 @nx-example/test-plugin
```

### Additional Information

Btw, it would be great, if nx team did update the [nx-examples-repo](https://github.com/nrwl/nx-examples/blob/master/package.json) 😄  as some of packages still at 15.9.0-rc.2

**Comment by AgentEnder** [comment]
This was fixed 🎉

**Comment by RolginRoman** [comment]
@AgentEnder thank you! When it will land? 16.0?

**Comment by AgentEnder** [comment]
Yes, we are prepping for 16 release currently. Feel free to try out the RCs to confirm that things are working as intended
