### ISSUE TITLE
Invalid dev remote provided when adding comma separated app names in --devRemotes param 

### ISSUE THREAD

**Issue by ak274** [nrwl/nx#16117]
### Current Behavior

In latest Nx v15.9.2 if I try to run multiple remote apps with host its not working.
`nx serve host --devRemotes=remote-one,remote-two`

Invalid dev remote provided: remote-one remote-two.

### Expected Behavior

It should run the remote app as dev remotes so that if dev make a change in any of the apps it will rebuild the updates.

### GitHub Repo

https://github.com/ak274/mfe-issue

### Steps to Reproduce

1. `nx serve host --devRemotes=remote-one,remote-two`

### Nx Report

```shell
Node : 18.15.0
   OS   : win32 x64
   npm  : 9.5.0

   nx (global)             : 15.9.2
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
```

### Failure Logs

```shell
nx run host:serve:development --devRemotes=remote-one remote-two


 >  NX   Invalid dev remote provided: remote-one remote-two.

   Pass --verbose to see the stacktrace.


 ——————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Running target serve for project host failed

   Failed tasks:

   - host:serve:development

   Hint: run the command with --verbose for more details.
```

**Comment by Coly010** [comment]
I can't reproduce this on MacOS, so it might relate to a parsing issue on Windows.

Can you run `nx serve host --devRemotes="remote-one,remote-two"`

**Comment by ak274** [comment]
@Coly010  putting --devRemotes inside inverted commas it works fine on Windows too. Closing this for now. But I feel it should also work without inverted commas which is not the case now atleast on Windows. Thanks!

> I can't reproduce this on MacOS, so it might relate to a parsing issue on Windows.
> 
> Can you run `nx serve host --devRemotes="remote-one,remote-two"`
