### ISSUE TITLE
in MFE Change in code trigger the build for all the apps(static-served and devRemotes) 

### ISSUE THREAD

**Issue by ak274** [nrwl/nx#16118]
### Current Behavior

When Dev makes a change in one of the library which has dependency on only one app (passed in --devRemotes) instead of building only that app it retrigger the build for all the remote apps statically served one too. 

### Expected Behavior

It should only build the app whose dependency has updated with new changes.

### GitHub Repo

https://github.com/ak274/mfe-issue

### Steps to Reproduce

1. `nx serve host --devRemotes=remote-one`
2. try update `ui-form` library which is dependency of `remote-one` App only you will see that change will trigger the build for `remote-two ` also which is static-served.

Note: Because its an empty project the rebuild of both the apps is still fast but in my production app only a small change took ages to reflect on screen as We have 6-7 huge apps.

### Nx Report

```shell
Node : 18.15.0
   OS   : win32 x64
   npm  : 9.5.0

   nx (global)             : 15.9.2
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
```

**Comment by ak274** [comment]
@AgentEnder @Coly010 Its really a blocker for a dev who use command `nx serve host --devRemotes=remote-app ` because while updating the code it retrigger the build for all the remotes in the host app. 

Please let me know if you were able to reproduce it in the repo? 
Or if there's a workaround for this until its fixed.

**Comment by Coly010** [comment]
Hi @ak274, From your example repo, I can see that is doing a rebuild of remote-two. However, it's pulling it from cache, it's not actually rebuilding.

What I can say, is that the repo you've provided appears to have some kind of graphing issue. At least when I run `nx graph` the graph I'm presented with does not appear to have the edges drawn between the projects correctly. This could be why you're seeing weird behaviour. I'll need to investigate this more to understand what is going on in the workspace.

**Comment by ak274** [comment]
@Coly010 Thanks for looking into it!

 Yes I agree that it takes from the cache and its fine. But it should only rebuild or pick from the cache those projects which are dependent of a lib where you make change and should not start picking all the apps from cache. In my actual project because I have around 10 remote apps. Even caching is not good DX. 

And it used to work fine in the older versions. I have updated my workspace from v15.2.0 to v15.9.2

**Comment by ak274** [comment]
Hi @Coly010, Were you able to figure out what's wrong here?

**Comment by Coly010** [comment]
@ak274 Not yet, still looking into. Nx v16 will fix the graphing issues when it's released, but I'll need to look further into why remote-two is still triggering

**Comment by Coly010** [comment]
@ak274 Yep, I've figured out the problem! 

Before, the static file server was not watching for changes by default, but when we switched to a common static file server to be used across all frameworks supported by Nx, that one does watch for changes by default. 

The fix is to add `watch: false` to the options of your remote's serve static target:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/12140467/234317498-bf7d59ba-fa75-46e2-95aa-90124147db7d.png">

I'll create a PR that adds this when we generate new remotes.

I can't write a migration to do this as it's expected functionality for some `serve-static` targets

**Comment by ak274** [comment]
@Coly010

  Adding `watch:false` has introduce a new issue now build is not triggering for `--devRemotes` also.
  
 I added `watch:false` to all the remotes and made a change to a lib which is dependency for only one remote app and its not triggering the build for the app. App was served with `--devRemotes ` .

**Comment by Coly010** [comment]
`watch:false` should only be added to serve-static targets. 

It shouldn’t be affecting devRemotes as they use a different target. Can you push your changes to your repo so I can take a look?

**Comment by ak274** [comment]
My bad, its working fine. I was just looking in my terminal when I hit `ctrl+s`  its not showing if something is building.. but browser reload with new changes. So its fine. Sorry to bother you on this! Thanks!
