### ISSUE TITLE
Combining projects targets into a single task

### ISSUE THREAD

**Issue by OSRSBlue** [nrwl/nx#16133]
Hey all, I am wondering if their is a way to support combining targets for a project into a single executable task. I have web services that require building the swagger documentation before building the service. My current approach is to create two new targets for the project: build:docs for building the documentation, and build:app for building the service. Then, when I run my nx build I use the run-commands executor to execute both targets as a single build. Does anyone know if their is a better way to do this or if this is a valid request for my pattern?

It feels clunky having two targets that need to be combined into my single build target to build my service correctly.

Here is my example project.json
```
    "build:docs": {
      "executor": "nx:run-commands",
      "options": {
        "cwd": "apps/authentication-api",
        "command": "swag init"
      }
    },
    "build:app": {
      "executor": "@nx-go/nx-go:build",
      "options": {
        "outputPath": "dist/apps/authentication-api",
        "main": "apps/authentication-api/main.go"
      }
    },
    "build": {
      "executor": "nx:run-commands",
      "options": {
        "commands": ["nx build:docs authentication-api", "nx build:app authentication-api"],
        "parallel": false,
      }
    },
```

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
The ability to combine project targets into a single target if my use case is applicable. Their may be a better way of handling this that I do not know.

## Motivation
project targets can be complicated, so being able to split up targets and combine them into a single target would be beneficial for complex flows.

## Suggested Implementation
Not sure yet since there may be a better way to handle my scenario above.

## Alternate Implementations
You specify targets as parts that can be combined together as a single target.

**Comment by AgentEnder** [comment]
You can do this with the `nx:noop` executor and `dependsOn`
