### ISSUE TITLE
Migrating to NX 15.9.0 loses support for discovering babel.config.json -- only looks for .babelrc

### ISSUE THREAD

**Issue by fbartho** [nrwl/nx#16134]
### Current Behavior

We have a script `libs/postgres/scripts/postgres-migration.ts` that is executed through an NX build command during our "package-for-deploy" process. This script references a file in `libs/postgres/src` in order to bundle instructions for any active migrations.

After upgrading to NX 15.9.0, we get this error:
```log
> nx run postgres:build-migrate

chunk (runtime: main) main.js (main) 39 bytes [entry] [rendered]

ERROR in ./scripts/postgres-migration.ts
Module build failed (from ../../node_modules/@nrwl/webpack/src/utils/web-babel-loader.js):
Error: Cannot find module '/home/runner/work/backend/backend/libs/postgres/.babelrc'
Require stack:
- /home/runner/work/backend/backend/node_modules/@babel/core/lib/config/files/configuration.js
- /home/runner/work/backend/backend/node_modules/@babel/core/lib/config/files/index.js
- /home/runner/work/backend/backend/node_modules/@babel/core/lib/index.js
- /home/runner/work/backend/backend/node_modules/babel-loader/lib/index.js
- /home/runner/work/backend/backend/node_modules/@nrwl/webpack/src/utils/web-babel-loader.js
- /home/runner/work/backend/backend/node_modules/loader-runner/lib/loadLoader.js
- /home/runner/work/backend/backend/node_modules/loader-runner/lib/LoaderRunner.js
- /home/runner/work/backend/backend/node_modules/webpack/lib/NormalModuleFactory.js
- /home/runner/work/backend/backend/node_modules/webpack/lib/Compiler.js
- /home/runner/work/backend/backend/node_modules/webpack/lib/webpack.js
- /home/runner/work/backend/backend/node_modules/webpack/lib/index.js
- /home/runner/work/backend/backend/node_modules/@nrwl/webpack/src/utils/with-nx.js
- /home/runner/work/backend/backend/node_modules/@nrwl/webpack/src/executors/webpack/lib/get-webpack-config.js
- /home/runner/work/backend/backend/node_modules/@nrwl/webpack/src/executors/webpack/webpack.impl.js
- /home/runner/work/backend/backend/node_modules/nx/src/config/workspaces.js
- /home/runner/work/backend/backend/node_modules/nx/src/command-line/run.js
- /home/runner/work/backend/backend/node_modules/nx/bin/run-executor.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
    at resolve (node:internal/modules/cjs/helpers:114:19)
    at loadConfig (/home/runner/work/backend/backend/node_modules/@babel/core/lib/config/files/configuration.js:209:5)
    at loadConfig.next (<anonymous>)
    at buildRootChain (/home/runner/work/backend/backend/node_modules/@babel/core/lib/config/config-chain.js:65:47)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/home/runner/work/backend/backend/node_modules/@babel/core/lib/config/partial.js:79:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at Object.<anonymous> (/home/runner/work/backend/backend/node_modules/@babel/core/lib/config/partial.js:122:25)
    at Generator.next (<anonymous>)

webpack compiled with 1 error (35b1dd6f51464c3b)
```

We were able to workaround this issue by renaming `babel.config.json` to `.babelrc`

### Expected Behavior

We expect that NX 15.9.0 (and or its webpack plugin) automatically discovers `babel.config.json` whenever it needs to, instead of forcing `.babelrc` `babel.config.json` is the recommended "default config" for babel in the current babel docs.

### Steps to Reproduce

1. Make a library that has a `babel.config.json`
2. Make a script in that library that uses code covered by that babel.config.json
3. Notice that it searches for `.babelrc` and dies

### Nx Report

```shell
yarn run v1.22.19
$ […snipped…]/node_modules/.bin/nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.11.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx                      : 15.9.0
   @nrwl/js                : 15.9.0
   @nrwl/jest              : 15.9.0
   @nrwl/linter            : 15.9.0
   @nrwl/workspace         : 15.9.0
   @nrwl/cli               : 15.9.0
   @nrwl/devkit            : 15.9.0
   @nrwl/eslint-plugin-nx  : 15.9.0
   @nrwl/express           : 15.9.0
   @nrwl/node              : 15.9.0
   @nrwl/nx-plugin         : 15.9.0
   @nrwl/tao               : 15.9.0
   @nrwl/web               : 15.9.0
   @nrwl/webpack           : 15.9.0
   @nrwl/nx-cloud          : 15.3.3
   typescript              : 4.9.5
   ---------------------------------------
   Local workspace plugins:
   	 @hca/package-generator
```

### Failure Logs

```shell
(Error log already included in "Current Behavior" section above
```

### Additional Information

N/A

**Comment by jarpoole** [comment]
Might be related to https://github.com/nrwl/nx/issues/15903?

**Comment by JuniorTour** [comment]
Possible Solution: Update your root babel config to use app's .babelrc

```
// ./babel.config.json
{
  "babelrcRoots": [
    "./apps/*"
  ]
}
```

I got similar error:
```
Error during bundle: Cannot find module './.config/babel.config'
Require stack:
- project/node_modules/@babel/core/lib/config/files/configuration.js
- project/node_modules/@babel/core/lib/config/files/index.js
- project/node_modules/@babel/core/lib/index.js
- project/node_modules/@nx/rollup/node_modules/@rollup/plugin-babel/dist/index.js
- project/node_modules/@nx/rollup/src/executors/rollup/rollup.impl.js
- project/node_modules/nx/src/config/schema-utils.js
- project/node_modules/nx/src/command-line/run/executor-utils.js
- project/node_modules/nx/src/command-line/run/run.js
- project/node_modules/nx/bin/run-executor.js
```

**Comment by jaysoo** [comment]
The `babel.config.json` file is meant for monorepos where this file establishes the root of the monorepo. Individual projects should be using `.babelrc` if you do not need the monorepo root behavior (See: https://babeljs.io/docs/config-files#root-babelconfigjson-file).

In short, to fix your error you can set `"babelUpwardRootMode": true` in your `project.json` file for the `@nx/rollup:rollup` and `@nx/webpack:webpack` executors.

**Longer explanation:**

In Nx prior to 15.7, we set babel to look upwards for `babel.config.json` (from project root), and once found, babel will then load both `babel.config.json` and the project's `.babelrc` file. This behavior lead to issues where babel configuration could be inconsistent between libs, thus leading to build errors. 

In Nx 15.7, we disabled the upward behavior by default, which allows `apps/demo/.babelrc` to be applied to all libs, rather than relying on each lib to duplicate the same `.babelrc` file (e.g. `libs/mylib/.babelrc`). This is behavior leads to less surprises.

There is a migration to set `babelUpwardMode` to `true` for existing projects, but perhaps this was missed? https://github.com/nrwl/nx/blob/master/packages/webpack/src/migrations/update-15-7-2/add-babelUpwardRootMode-flag.ts

In Nx 15.7 we changed the default babel behavior to not look upwards for
