### ISSUE TITLE
baseUrl is ignored during e2e tests

### ISSUE THREAD

**Issue by dpsthree** [nrwl/nx#1614]
## Current Behavior
E2E tests only ever check against localhost:4200.

### Steps to Reproduce
Run ng e2e my-app-e2e --baseUrl=anyurl 

or

set baseUrl in cypress.json then run e2e tests

### Context
v 8.2.0 of nx

I've tried many different combinations (ng e2e, ng e2e --watch, ng e2e my-project-e2e) they all have the same result.

**Comment by dpsthree** [comment]
I dug into the source code and it appears as though the baseUrl is ignored when the devServerTarget is specified in angular.json. I was able to remove this option and verify that it picks up the baseUrl. However, removing this option also appears to prevent nx from building standing up the application. For my usage this is great!

However, it may be worth documenting this a bit more for folks trying to achieve non-trivial things during CI/CD.

**Comment by FrozenPandaz** [comment]
@dpsthree That is correct.

Would someone like to contribute a fix? The line to change would be here:
https://github.com/nrwl/nx/blob/master/packages/cypress/src/builders/cypress/schema.json#L49

Make sure to run `yarn documentation` afterwards to regenerate the documentation.

**Comment by Steven-Harris** [comment]
I believe this is an code issue too. I really like nrwl serving the angular application but I need to override cypress's baseUrl

**Comment by mehrad-rafigh** [comment]
Hey Folks. Does anybody have a repo where I could test my patch?

**Comment by Steven-Harris** [comment]
@mehrad-rafigh, I would still expect for the dev server to be started if the baseUrl is passed in,

**Comment by Steven-Harris** [comment]
![image](https://user-images.githubusercontent.com/7720242/64971285-1660fa80-d86d-11e9-9282-fd1eeef7380e.png)
The CLI is overriding any baseUrl set in cypress.json

**Comment by mehrad-rafigh** [comment]
Hi @Steven-Harris
You are right. I will update my PR asap

**Comment by dpsthree** [comment]
Reading through these comments and thinking back to what I wanted to achieve it sounds like this one setting is conflating two ideas. IMO e2e should always serve but also respect the baseUrl. It would be nice if there were a second command that respects all of the Nx settings and runs cypress without serving the application. This command should also respect the baseUrl setting.

**Comment by mattmbrightside** [comment]
Yes it would be very useful to be able to run my cypress specs against both local and hosted environments and compare the results.

**Comment by ZachJW34** [comment]
I think this issue can be solved by:
* Adding a new flag called `skipServe` which will skip the builder serving your application. This is equivalent to the `devServerTarget` being empty but reads better and makes it easy to invoke come CI. We can keep the same behavior so there is no breaking change.
* Refactor the handling of the baseUrl such that the baseUrl specified via command line or config takes precedence over the output of the dev server build.

Examples:
* nx e2e my-app -> Serves app and opens cypress with baseUrl from dev server output
* nx e2e my-app --baseUrl http://localhost:4200/other-route -> Serves app and opens cypress with specified baseUrl
* nx e2e my-app --baseUrl http://localhost:4200/other-route --skipServe -> Does not serve app and opens cypress at specified baseUrl

What do you all think? I can submit a PR for these changes if they are desired.

**Comment by stefan-karlsson** [comment]
@ZachJW34 I really like your ideas, please let me know if you want help. 

>Adding a new flag called skipServe which will skip the builder serving your application. This is equivalent to the devServerTarget being empty but reads better and makes it easy to invoke come CI. We can keep the same behavior so there is no breaking change.

The only thing to add here is the naming, i think that `serve` with a default value of true is enough.

**Comment by mehrad-rafigh** [comment]
@stefan-karlsson you can bypass the app being build with `--dev-server-target=''`

**Comment by dtodt** [comment]
Greetings, I've managed to run the tests without re-create the frontend, using the command below:
```sh
yarn e2e:watch --skipServe --devServerTarget=
```

**Comment by mehrad-rafigh** [comment]
Has this been resolved?

**Comment by PBartrina** [comment]
I am still having issues with this
