### ISSUE TITLE
withNx Sass configuration not working

### ISSUE THREAD

**Issue by lourd** [nrwl/nx#16142]
### Current Behavior

Reading through the source of the `withNx` plugin in @nrwl/next, it appears that it's kind of supposed to configure the Sass loader to automatically support Sass imports from libs in your Nx repo https://github.com/nrwl/nx/blob/master/packages/next/plugins/with-nx.ts#L272-L286

It doesn't have any effect though. The way Next.js accepts this configuration is now with the [`sassOptions.includePaths` property](https://nextjs.org/docs/basic-features/built-in-css-support#customizing-sass-options) on the config object.

### Expected Behavior

It would be awesome if the `withNx` plugin was updated for the new form and the docs mentioned this feature! So each application doesn't need to specify this in its next.config.js file

```
module.exports = withNx({
  sassOptions: {
    includePaths: [path.join(repoRoot, "libs")],
  }
})
```

### Steps to Reproduce

1. Generate a new Nx repo and Next.js app with Sass
2. Make a separate, shared library with some Sass files that have a variable or mixin
3. Try and import the variable or mixin from the library using root-relative paths, i.e. `@use libs/my-shared-lib/src/variables";`
4. The import fails, the Sass compiler can't find that path.

### Nx Report

```shell
Node : 16.14.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/detox             : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/next              : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/react-native      : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
```

**Comment by ndcunningham** [comment]
Does `@import` work?

**Comment by ndcunningham** [comment]
So looking at the documentation `includePaths` is not supposed to function as a loader.
It acts similarly to `tsconfig` `paths` where 
Example:
`@import 'libs/my-lib/src/deeply-nested-folder/my-lib-variables`

Can be rewritten to:
`@import 'my-lib-variables'`

Discussion: https://github.com/vercel/next.js/discussions/12771#discussioncomment-13275

There may be an issue with using the `@use` syntax instead of `@import` which I could reproduce.

As a workaround try using `@import` we will look into the `@use` issue

**Comment by lourd** [comment]
I appreciate you looking into this!

My team's codebase only uses `@use` and the [Sass team explicitly recommends against using `@import`](https://sass-lang.com/documentation/at-rules/import#:~:text=The%20Sass%20team%20discourages%20the%20continued%20use%20of%20the%20%40import%20rule). Using the `includePaths` option has worked just fine for quite a while, so I don't think we'll switch.

I don't quite understand the distinction between configuring the Sass loader for import paths vs the Sass compiler for import paths. It seems like configuring the compiler is somehow also configuring the loader?

**Comment by ndcunningham** [comment]
Sorry about the lack of updates.
After looking into this we believe that it would be better suited to have a recipe/tutorial to expose this functionality.

As to my earlier comment 
> As a workaround try using @import we will look into the potential @use issue

Using `@use` should be fine.
Here is an example repo https://github.com/ndcunningham/issue-16142
