### ISSUE TITLE
broken link https://nx.dev/guides/nx7-to-nx8

### ISSUE THREAD

**Issue by joeldbirch** [nrwl/nx#16151]
> npm WARN deprecated @nrwl/nx@7.8.7: This package has been replaced by @nrwl/workspace. See https://nx.dev/angular/guides/nx7-to-nx8 on how to upgrade.

The above link is 404.

**Comment by AgentEnder** [comment]
We've removed that guide at this point as it was for Nx 7 - 8, and we are on Nx 25 now. Your best bet would be checking out the 9.0.0 tag or similar and checking the docs folder.

**Comment by FrozenPandaz** [comment]
The guide is at https://github.com/nrwl/nx/blob/9.0.0/docs/angular/guides/nx7-to-nx8.md. The message has been updated as well.
