### ISSUE TITLE
Support Angular's standalone migration schematic

### ISSUE THREAD

**Issue by nekkon** [nrwl/nx#16162]
Seems Angular's standalone migration schematic does not work in a nx monorepo that does not have the angular.json file. I have recently updated my nx workspace (is now v15.9.2) in order to be able to use the standalone migration schematic to gradually migrate a large Angular project to use standalone components as it requires at least Angular v15.2.0. (https://angular.io/guide/standalone-migration)

When running `ng generate @angular/core:standalone` I get the following error:

`Error: This command is not available when running the Angular CLI outside a workspace.`

From what I understand, the reason is that the angular.json does not exist anymore and angular/cli does not detect that I am running the schematic inside an Angular project.

Is Nx going to support Angular's standalone migration schematic? 

Is there any workaround to the missing angular.json or to the error above?

This is something critical for our team, as our project is very large and the standalone schematic seems a very helpful option.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

The issue is that you're trying to run a generator with the Angular CLI (`ng`). If you run `nx generate @angular/core:standalone`, it works as expected. Please note the usage of the Nx CLI (`nx`) instead of the Angular CLI (`ng`).
