### ISSUE TITLE
Wrong schematics for component

### ISSUE THREAD

**Issue by lares83** [nrwl/nx#1617]
# Prerequisites
Generate `scss` files when create a new component

## Current Behavior

Generating components generate `css` file instead of `scss`

### Steps to Reproduce

Create new workspace using `npx create-nx-workspace@latest app-test`.
Select the following answers: 
```
Which stylesheet format would you like to use? SASS(.scss)  [ http://sass-lang.com   ]
What to create in the new workspace (You can create other applications and libraries at any point using 'ng g') angular [a workspace with a single Angular application]
```

After you install all dependencies, create new component using the following command 
`ng g c test`

The following files are being created:
```
CREATE apps/app-test/src/app/test/test.component.css (0 bytes)
CREATE apps/app-test/src/app/test/test.component.html (19 bytes)
CREATE apps/app-test/src/app/test/test.component.spec.ts (614 bytes)
CREATE apps/app-test/src/app/test/test.component.ts (266 bytes)
UPDATE apps/app-test/src/app/app.module.ts (450 bytes)
```

Which is wrong because it should generate `test.component.scss` instead of `css`.

I've noticed that in `angular.json` the following schema has been generated
```
"schematics": {
      "@nrwl/workspace:component": {
          "style": "scss"
        }
 },
```

When I change it to 
```
"schematics": {
        "@nrwl/angular:component": {
          "style": "scss"
        }
},
```

It starts working fine.

### Context

Please provide any relevant information about your setup:

- version of Nx used
8.3.0

-version of npx 
10.2.0

```
Angular CLI: 8.1.1
Node: 10.15.3
OS: darwin x64
Angular: 8.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.1
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.1.1
@angular-devkit/schematics        8.1.1
@angular/cli                      8.1.1
@ngtools/webpack                  8.0.6
@schematics/angular               8.1.1
@schematics/update                0.801.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
```

**Comment by FrozenPandaz** [comment]
Good catch. The offending line is here: https://github.com/nrwl/nx/blob/2b646f8eb4839d7b3b47bf703016e33bf1dbd2fe/packages/angular/src/schematics/application/application.ts#L219

Would somebody like to contribute a fix?

**Comment by mehrad-rafigh** [comment]
@FrozenPandaz I would love to contribute!
