### ISSUE TITLE
@nrwl/react-native - select default storage and env package 

### ISSUE THREAD

**Issue by omniviewsports** [nrwl/nx#16181]
- [ X] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Currently, when you create a new react-native app or add a library, nx installs @react-native-async-storage/async-storage
and react-native-config.

However, I prefer using react-native-mmkv and react-native-ultimate-config. Thus, I'd like the option not to use those two default packages/

## Motivation
Developers would like the opportunity to select what storage and config packages they use.

## Suggested Implementation
When you run `nx g @nrwl/react-native:init ...,` an option is presented to use either the default @react-native-async-storage/async-storage or react-native-config packages or not. If not for either nx sets up the react-native app without installing or setting up the two packages.

## Alternate Implementations
remove those two default packages, and let developers select what they want to use.

**Comment by xiongemi** [comment]
removed in pr https://github.com/nrwl/nx/pull/16504. should be available in next release
