### ISSUE TITLE
NODE_ENV is undifined or conflicts when building Angular with webpack

### ISSUE THREAD

**Issue by qwadrox** [nrwl/nx#16194]
### Current Behavior

NODE_ENV is undifined 
Tried to use webpack based on this article: https://nx.dev/recipes/environment-variables/use-environment-variables-in-angular

If NODE_ENV production manually set, build fails with typescipt error:

> Could not find a declaration file for module 'crypto-js'. '/app/node_modules/crypto-js/index.js' implicitly has an 'any' type

### Expected Behavior

Should be true:

>  By default, Angular only provides the NODE_ENV variable when building the application. You may use process.env.NODE_ENV anywhere in your TS/JS source, and the build will inline this value in the output chunks.

The provided code in article cannot be used. 
```
if (process.env['NODE_ENV'] === 'production') {
  enableProdMode();
} 

```
### Workaround
**i have found this post and modified my webpack.config as below:** 

@jaysoo pls check the documentation about custom environment variables:
https://nx.dev/guides/environment-variables#using-environment-variables-in-angular-applications

the suggested changes about webpack, cause the warning.
I temporarily fixed changing from this:

```javascript  
const raw = Object.keys(process.env)
    .filter((key) => NX_APP.test(key))
    .reduce(
      (env, key) => {
        env[key] = process.env[key];
        return env;
      },
      {
        NODE_ENV: process.env.NODE_ENV || configuration,
      }
    );
```

to this:

```javascript
  const raw = Object.keys(process.env)
    .filter((key) => NX_APP.test(key))
    .reduce(
      (env, key) => {
        env[key] = process.env[key];
        return env;
      },
      process.env.NODE_ENV === 'production' ? {
        NODE_ENV: process.env.NODE_ENV || configuration,
      } : {}
    );
```

_Originally posted by @MoiseScalzo in https://github.com/nrwl/nx/issues/9719#issuecomment-1155195602_

### Env

 ```
Node : 16.14.2
   OS   : win32 x64
   npm  : 8.5.5

   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngrx/component              : 15.4.0
   @nxkit/playwright            : 2.2.0
   @trumbitta/nx-plugin-openapi : 1.12.1
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

As you have discovered the hard way, this statement is not exactly correct:

> By default, Angular only provides the NODE_ENV variable when building the application. You may use process.env.NODE_ENV anywhere in your TS/JS source, and the build will inline this value in the output chunks.

Angular builders set the [webpack mode](https://webpack.js.org/guides/production/#specify-the-mode) based on the values of the `scriptsOptimization` and `stylesOptimization.minify` options in the build configuration. Setting the webpack `mode` also sets the `NODE_ENV` environment variable and therefore, your application can access it. So, that bit of the docs is partially true, but misleading. While you can access it, you can't exactly override the `NODE_ENV` variable directly unless you use the `DefinePlugin` as explained in that doc.

I'll amend the docs to provide more clarity on this.
