### ISSUE TITLE
MF React Example doesn't render expected results

### ISSUE THREAD

**Issue by tbrannam** [nrwl/nx#16199]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/recipes/module-federation/module-federation-with-ssr#install-your-framework-plugin

Following the React instructions results in a workspace that does not display links for "/product", or "/checkout" at the top of the rendered output.

### Additional context or description

Following the same instructions but choosing Angular instead renders the correct results.   Those following React instructions find things somewhat confusing.

**Comment by xiongemi** [comment]
it should be fixed in https://github.com/nrwl/nx/pull/19565

closing this for now
