### ISSUE TITLE
Comprehensive `project.json` reference

### ISSUE THREAD

**Issue by dlqqq** [nrwl/nx#16191]
# Description

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

There doesn't appear to be comprehensive documentation for `project.json`. My specific concerns that are not answered by the documentation are as follows:

1. **What fields are allowed in `project.json`?** There doesn't appear to be a comprehensive list of fields and an accompanying description. In fact, the `project.json::root` field, one of the most important fields, is conspicuously missing from the [Project Configuration page](https://nx.dev/reference/project-configuration#implicitdependencies).

  - In fact, the only description I can find on this field is a vague statement within [a tutorial page](https://nx.dev/core-tutorial/02-create-cli#project.json-syntax):
  > root, sourceRoot and application are properties that help Nx know more about your project.

2. **How is project configuration synthesized from `package.json` and `project.json`?** Does `project.json` always take precedence over `package.json`?

3. **Are there any fields that are exclusively be declared in either `package.json` or `project.json`**? For example, [`implicitDependencies` declared in `package.json` are not being respected](https://github.com/nrwl/nx/issues/9065); these can only be declared in `project.json`. I suspect there are other "official" examples of this that aren't the result of a bug.

4. **Why `project.json`?** It would be helpful to provide context and possible motivations on why a developer might use `project.json`, either adding to or replacing `package.json`. One clear motivation that should be included is that projects may not necessarily be JavaScript projects. This is briefly touched on in the same tutorial page:
  > There are a few reasons to choose project.json for the CLI project.
  > 1. The presence of package.json might cause other developers to think there is javascript code in this project.
  > 2. As the scripts in the project get more complex, project.json tends to have a flatter structure - rather than a long horizontal line in package.json with all the cli flags.
  > 3. The easiest method to run scripts provided in Nx plugins is to use a project.json file.

# Proposal

I believe that the current project configuration page, although very useful, is insufficient to serve as a reference. The current project configuration page should probably be moved to some other section like "Core features" or "Concepts". Finally, point 4 should be addressed in this page.

In its place, there should be a new documentation page titled "Project configuration reference" under the "Reference" section. This page should address points 1-3 outlined above. I think the only tricky thing to work out here is what reference point to use when describing project configuration fields. If you use `package.json` as a reference point, then it's not clear how to explain fields that are not declarable via `package.json`. I think the best strategy here is to first determine what "intermediate format" both files get serialized to. For example, does `package.json` get coerced into `project.json`, or do both get serialized to some internal format X? Then, use that as a reference point and discuss how that field's value is synthesized from `package.json` and `project.json`.

Again, this is just a proposal; I'm very open to hearing feedback!

**Comment by pauleustice** [comment]
I agree wholeheartedly.

**Comment by isaacplmann** [comment]
These are good suggestions and I'll work on making the documentation clearer, but let me answer your questions in the meantime.

1. You can put whatever json you want in the `project.json`, but there are only certain fields that will actually be read by Nx core or plugins.  The most definitive information is [the typescript type](https://github.com/nrwl/nx/blob/master/packages/nx/src/config/workspace-json-project-json.ts#L42), although you can also look at the less extensive [json schema](https://github.com/nrwl/nx/blob/master/packages/nx/schemas/project-schema.json) which is used to auto-complete in your editor.

1.b.  `root` at this point is an unnecessary field as Nx can infer the root as the folder that contains the `project.json` or `package.json` file.

2. `project.json` does take precedence over `package.json`.  You can test this by defining an npm script in `package.json` and a target in `project.json` that have the same name and see which one is called.

3. No.  Everything that can be defined in `project.json` should also be definable in `package.json`. If you find a situation where that isn't the case, it's a bug.

4. Yes, we should make the reason for using `project.json` more explicit.  The biggest reason for using `project.json` isn't in the list you found.  The only way to use executors is to use a `project.json` file.  If you're debating between using `run-commands` or npm scripts, there isn't a big difference and you should probably stick with whatever exists in your repo.  But if you want to have an Nx plugin manage your build script for you, then you need to switch to `project.json`.

I'm still thinking about what the best way to document all this would be, but I'll keep you posted.  And thanks for the clearly defined post.

**Comment by AgentEnder** [comment]
Just clarifying a point here:
> 3. No. Everything that can be defined in project.json should also be definable in package.json. If you find a situation where that isn't the case, it's a bug.

This is **_almost_** the case, and the clarification is kind of covered by point 4, but just to reinforce it: You **_can not_** specify the executor for a target via the `nx` property of `package.json`

**Comment by plutotv-aaa** [comment]
This information has helped with my current situation. I appreciate you and thank you for this discussion.

**Comment by FrozenPandaz** [comment]
The reference is here: https://nx.dev/reference/project-configuration

Please open a new issue if there is something missing from that guide.
