### ISSUE TITLE
unable to create local generators for libraries which does not have their package.json

### ISSUE THREAD

**Issue by hrishikeshjoshi91** [nrwl/nx#16192]
### Current Behavior

Hello team NX,
we are using NX for our new project. The initial setup was done 14.X version which was working for. We recently migrated the setup to nx 15.9.2 version.
After that migration, we are unable to create any custom generator for the project 

we are getting the following error on the console    
![image](https://user-images.githubusercontent.com/20990398/230788978-5053096c-c677-486d-a0a9-de27c85ee3c1.png)

we had revert all our migrations back to 14.x version. We wanted to use the latest feature of NX but this problem is blocking us from migrations.

because of this great generator feature :- all our developers are spoiled, and we dont wish to create those files manually again .

would you be able to suggest any workaround for this problem ?   

### Expected Behavior

nx-plugin:generator should generate the schema.json file and then same generator should be prompted on nx-console

### Steps to Reproduce

1. create a nx workspace with latest ( 15.9.2) version 
2. point to Libs folder --> as library base folder
3. create react component library 
4. try to create a generator for the same library using the command **"npx nx generate @nrwl/nx-plugin:generator {generator-name} --project={library-name}"**
5. user should ideally see the following error
6. 
![image](https://user-images.githubusercontent.com/20990398/230789338-701832be-6c66-4154-9f36-cd0a3b4e8828.png)

### Nx Report

```shell
Report complete - copy this into the issue template

   Node : 16.15.0
   OS   : win32 x64
   npm  : 9.6.4
   
   nx (global)             : 15.9.2
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/nx-plugin         : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
```

**Comment by AgentEnder** [comment]
To generate a local generator, you should first generate a plugin and then select that plugin as the project for the generator. I think with that approach you should be fine.
