### ISSUE TITLE
create-nx-workspace not found

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#1619]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

`create-nx-workspace` should exists

## Current Behavior

create-nx-workspace not found after install 8.3.0

## Failure Information (for bugs)

create-nx-workspace not found

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Just install the latests version (8.3.0)
2. Run `create-nx-workspace demo-project`

### Context

Please provide any relevant information about your setup:

- version of Nx used: 8.3.0
- version of Angular CLI used
- `angular.json` configuration
- version of Angular DevKit used
- 3rd-party libraries and their versions
- and most importantly - a use-case that fails

**A minimal reproduce scenario using allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

Please include any relevant log snippets or files here.

## Other

Any other relevant information that will help us help you.

**Comment by FrozenPandaz** [comment]
> 1. Just install the latests version (8.3.0)

I am not sure which package you are installing here.

You can run `npx create-nx-workspace@latest demo-project` to automate the installation.

**Comment by gperdomor** [comment]
@FrozenPandaz the package is `@nrwl/workspace`, installed with `npm install -g @nrwl/workspace`... Also missing in version 8.4.0

**Comment by jaysoo** [comment]
@gperdomor You can install it globally via `npm install -g create-nx-workspace`. We reworked the packages in 8.x so `@nrwl/schematics` does not provide this binary anymore.

We recommend running the create workspace using one of the three methods below.

**npx**
```
npx create-nx-workspace myworkspace
```

**npm**
```
npm init nx-workspace myworkspace
```

**yarn**
```
yarn create nx-workspace myworkspace
```

**Comment by jaysoo** [comment]
Closed this issue, let us know if you have any further problems.
