### ISSUE TITLE
Library is compiled to a single index.js file and can't be tree shaken by the consumer

### ISSUE THREAD

**Issue by dands1** [nrwl/nx#16195]
### Current Behavior

Hi,

When I build my library, all the code bundles up in to a single index.js file.
This prevents tree shaking by the consuming application (outside of the monorepo).

### Expected Behavior

The index.js file should export the build files from thier directories as they appear in the source code.
Ex
`
export * from "./Button";
export * from "./Checkbox";
...
`

### GitHub Repo

https://github.com/dands1/dan-test

### Steps to Reproduce

1. `git clone https://github.com/dands1/dan-test.git`
2. run `npm i`
3. `nx build test-1`

### Nx Report

```shell
Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : darwin x64
   npm  : 8.19.1
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/rollup            : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
```

**Comment by ofirrifo** [comment]
I have the same issue

**Comment by jaysoo** [comment]
Hi @dands1 The library support currently always bundle the output when using rollup or vite (since both are bundlers).

You could try esbuild and disable bundling. This will only transpile files, so the output files are 1:1 with their source. But note that this option does not support CSS.

```
npm i -D @nrwl/esbuild

# This will prompt for the project (skip validation to overwrite existing build target)
nx g @nrwl/esbuild:esbuild-project --skipValidation

nx build <project> --bundle=false
```

We have no plans to support non-bundled builds for React/UI libraries, but feel free to add a [discuss](https://github.com/nrwl/nx/discussions) around this topic if it's something you'd like to see.

**Comment by LironHazan** [comment]
@jaysoo 
Hey Jay, do you think replacing the default rollup config may help here?
The intended result in dist is:
```
- components lib:
  - componentA:
      - index.mjs
  - componentB:
      -index.mjs
index.mjs - wich looks like:
export * from componentA
export * from componentB 
```     
It needs to be tree-shakeable so currently checking a lead of extending the rollup config to include those abilities
