### ISSUE TITLE
root level script issue

### ISSUE THREAD

**Issue by slavik-lvovsky** [nrwl/nx#16207]
### Current Behavior

my 2 package level "build" scripts fail when I have root level "build" script.
in my package.json I have defined nx: {} block that configures a script (not the "build" one) 

when I remove the package.json "nx": {} block everything works as expected

### Expected Behavior

root level script should be ignored at least while it is not specified in the package.json nx: {} block

### Steps to Reproduce

1. create monorepo with 2 packages
2. define "build" script in both packages
3. define nx: {} (even empty) in the monorepo root level package.json
4. create script in the package.json with name "build" that looks like: "nx run-many --target=build"

### Nx Report

```shell
Node : 18.14.1
   OS   : win32 x64
   npm  : 9.3.1

   nx          : 15.9.2
   @nrwl/cli   : 15.9.2
   @nrwl/tao   : 15.9.2
   typescript  : 4.9.5
```

**Comment by AgentEnder** [comment]
You can limit which scripts are picked up in your root package by expanding the `nx` block as so:

> https://nx.dev/reference/project-configuration#ignoring-package.json-scripts
```jsonc
{
  // other package.json sections
  "nx": {
    // empty array = no targets, otherwise place script names here.
    "includedScripts": []
  }
