### ISSUE TITLE
nx run command missing --all arguments for single target to run on multiple projects with parameters

### ISSUE THREAD

**Issue by jackykwandesign** [nrwl/nx#16214]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

For example, i added a new eslint rules with override pattern due to this issue https://github.com/nrwl/nx/issues/5866

I tried to run eslint --fix to apply auto fix

When i run `yarn nx affected --target=lint --fix`, it show
```
 >  NX   Affected criteria defaulted to --base=main --head=HEAD

 >  NX   Successfully ran target lint for 0 projects (8ms)
 
         With additional flags:
           --fix=true
```

And there is no command to run single `target ` with extra arguments for lint fix

I tried `yarn nx run-many --all --target=lint --fix`, but this command cannot pass arguments `--fix`

i tried `yarn nx run lint --fix`, but this command only run for default project

## Motivation

missing function in nx command

## Suggested Implementation

add --all arguments to `nx run` simular to `nx run-many`

## Alternate Implementations

Run lint fix on every libs / apps, but this is not pratical with human mistake

**Comment by al-shivani** [comment]
Try this command to fix lint issues in all the apps & libs inside your project

nx run-many --all  --target lint --fix=true

**Comment by AgentEnder** [comment]
You should definitely be able to pass `--fix` via run-many, `run` is for running 1 target for 1 project, so `--all` wouldn't make sense.

**Comment by AgentEnder** [comment]
I confirmed this morning that passing `--fix` works with latest. We won't be adding a `--all` option to `nx run`, so I'm going to close this out.

If for some reason passing `--fix` to `run-many` isn't working as you expect, that would likely be a bug. Feel free to raise an issue.
