### ISSUE TITLE
[@nrwl/react-native] listDevices option in the run-android command is not configurable

### ISSUE THREAD

**Issue by skoob13** [nrwl/nx#16221]
### Current Behavior

`listDevices` option of the `run-android` executor in the React Native package is a flag and it doesn't accept a boolean value, e.g. `--list-devices false` doesn't skip listing devices. Currently, listDevices set to `false` by default, so there isn't a way to disable this option because it is always passed to the React Native CLI. The executor asks to select a device every time when I run this command.

### Expected Behavior

`listDevices` should be optional in schema.json, so the device selection step can be skipped.

### Steps to Reproduce

1. create a NX project with React Native
2. execute `nx run project:run-android`
3. observe that the device selection is required despite the fact that it is `false` in the schema.

### Nx Report

```shell
Node : 16.17.0
   OS   : darwin x64
   yarn : 1.22.19

   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/detox             : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/next              : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/react-native      : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
```

**Comment by omniviewsports** [comment]
@skoob13 - I encountered the same problem
