### ISSUE TITLE
Add `microbundle` for bundling publishable libraries

### ISSUE THREAD

**Issue by Lonli-Lokli** [nrwl/nx#16227]
## Description
It will be great to have build of publishable libraries in multiple formats. In order to do that I propose to incorporate https://github.com/developit/microbundle

## Motivation
Creates multiple output formats for each entry (CJS, UMD & ESM)

## Suggested Implementation
Use https://github.com/developit/microbundle package for nx publish

**Comment by AgentEnder** [comment]
This would be a good use case for a community plugin, in the same vein as the official @nrwl/{webpack, rollup, vite} plugins.
