### ISSUE TITLE
NX_TARGET_TASK_PROJECT is always empty (again)

### ISSUE THREAD

**Issue by prewk** [nrwl/nx#16225]
### Current Behavior

Similar to [#14838](https://github.com/nrwl/nx/issues/14838), I can't get `NX_TARGET_TASK_PROJECT` to be set. I think it was incorrectly closed?

I create a target in a lib called `foobar`:

```
"asdfasdf": {
      "builder": "@nrwl/workspace:run-commands",
      "options": {
        "commands": [
          "echo \"HELLO $NX_TARGET_TASK_PROJECT\" >> test.txt"
        ],
        "parallel": false
      }
    }
```

I run the target: `yarn nx affected -t asdfasdf`

`test.txt` now contains `HELLO `, one for every lib that has that target.

### Expected Behavior

`test.txt` should contain "HELLO foobar" and a similar line for every lib that target exists in.

### GitHub Repo

https://github.com/nrwl/nx-examples

### Steps to Reproduce

1. Try to use `$NX_TARGET_TASK_PROJECT` in a project target
2. It'll always be empty/unset!

### Nx Report

```shell
Node : 16.18.0
   OS   : darwin arm64
   yarn : 1.22.19

   nx : 15.6.3
   @nrwl/angular : 15.6.3
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.6.3
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.9.5
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @ngrx/component: 15.2.1
   	 @ngrx/component-store: 15.2.1
   	 @ngrx/effects: 15.2.1
   	 @ngrx/entity: 15.2.1
   	 @ngrx/router-store: 15.2.1
   	 @ngrx/store: 15.2.1
   	 @ngneat/spectator: 14.0.0
   	 @ngrx/schematics: 15.2.1
   	 @ngrx/store-devtools: 15.2.1
   	 @storybook/angular: 6.5.16
   	 @testing-library/angular: 13.1.0
```

### Additional Information

Silly question, but - why doesn't `NX_TARGET_TASK_PROJECT` [exist in the nx codebase anywhere](https://github.com/search?q=org%3Anrwl+NX_TARGET_TASK_PROJECT&type=code)? It's only present in docs/examples.

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/640102/231176897-9ea43a5c-d94c-4f8c-97f0-c5093cc6955a.png">

**Comment by AgentEnder** [comment]
The docs are wrong here - it should be NX_TASK_TARGET_PROJECT. I'll update the examples files.

**Comment by prewk** [comment]
Ah, that explains it! (not sure if you'll get the notification so I'll ping you again @Tristan2357)

**Comment by AgentEnder** [comment]
Fixed by: https://github.com/nrwl/nx/pull/16236
