### ISSUE TITLE
nx commit base argument overrides vite base path

### ISSUE THREAD

**Issue by benfriebe** [nrwl/nx#16243]
### Current Behavior

When using the `@nrwl/vite:build executor` the base path gets passed down as the base commit from the nx run command.

Example is when building a frontend project using vite with the following command with commits:

`nx run frontend:build --base=xxxxx --head=xxxxx`

Will result in the vite executor receiving the `base` arg and using that for the [base path](https://vitejs.dev/guide/build.html#public-base-path)

### Expected Behavior

@nrwl/vite:build executor should either:

-  Ignore the nx base commit argument
-  Be allowed to override it (currently passed in args will override the configured base path in the project.json)
-  Have the `forwardAllArgs` option like the `nx:run-commands` executor to allow toggling of arg forwarding

### Steps to Reproduce

1. Use the `nrwl/vite:build` executor to build a frontend project
2. Pass in a `--base` with a commit to the nx build command
3. vite will put the commit into the base path 

### Nx Report

```shell
Node : 16.13.0
   OS   : linux x64
   npm  : 8.4.0

   nx : 15.6.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.6.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.2
   @nrwl/js : 15.6.2
   @nrwl/linter : 15.6.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.6.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.6.2
   @nrwl/vite : 15.6.2
   typescript : 4.9.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @ago-dev/nx-aws-cdk-v2: 1.3.1
```

**Comment by AgentEnder** [comment]
`--base` and `--head` don't make sense for running a singular target, so we don't consume them in that format. Can you check if you have the same issue when running with `nx affected`, which does consume those flags?

**Comment by AgentEnder** [comment]
I can't reproduce this with `nx run` or `nx build` directly, see: 
<img width="785" alt="image" src="https://user-images.githubusercontent.com/6933928/232914654-16d69aac-9abb-40e1-8bb1-05018a9727d4.png">

If you need to base `base` or similar in `nx affected`, you should be able to via: `nx affected --target build -- --base /something`
