### ISSUE TITLE
Azure DevOps Pipeline Example: fatal: ambiguous argument 'master': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by marc-wilson** [nrwl/nx#16241]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.
https://nx.dev/recipes/ci/monorepo-ci-azure

### Additional context or description

Provide any additional details here as needed.

The code snippet for the azure-pipelines.yaml file does not work in Devops. As soon as the below step is ran, DevOps throws an error

`- script: npx nx format:check`

> fatal: ambiguous argument 'master': unknown revision or path not in the working tree.

Full Log
```
Starting: CmdLine
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.212.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
npx nx format:check
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/79102d64-d806-43d7-ba5b-38f3870d1b15.sh
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
apps/api-e2e/jest.config.ts
apps/api-e2e/src/api/api.spec.ts
apps/api-e2e/src/support/global-setup.ts
apps/api-e2e/src/support/test-setup.ts
apps/api/jest.config.ts
apps/api/src/app/app.controller.spec.ts
apps/api/src/app/app.controller.ts
apps/api/src/app/app.module.ts
apps/api/src/app/app.service.spec.ts
apps/api/src/app/app.service.ts
apps/api/src/main.ts
apps/api/webpack.config.js
apps/app/src/app/app.component.ts
jest.config.ts
jest.preset.js
##[error]Bash exited with code '1'.
Finishing: CmdLine
```

Using npx 9.5.0

If I run `npx nx format:check` locally, it works fine. Are there additional arguments that need to be passed here?

**Comment by marc-wilson** [comment]
If you get past this step, the next issue that comes up is this line:

`- script: npx nx affected --base=$(BASE_SHA) -t lint --parallel=3`

Similar errors

> Error: Command failed: git diff --name-only --no-renames --relative "master" "HEAD"
> fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'
> 
>     at checkExecSyncError (node:child_process:885:11)
>     at execSync (node:child_process:957:15)
>     at parseGitOutput (/home/vsts/work/1/s/node_modules/nx/src/utils/command-line-utils.js:204:41)
>     at getFilesUsingBaseAndHead (/home/vsts/work/1/s/node_modules/nx/src/utils/command-line-utils.js:201:12)
>     at parseFiles (/home/vsts/work/1/s/node_modules/nx/src/utils/command-line-utils.js:160:20)
>     at /home/vsts/work/1/s/node_modules/nx/src/command-line/affected.js:115:155
>     at Generator.next (<anonymous>)
>     at /home/vsts/work/1/s/node_modules/tslib/tslib.js:167:75

**Comment by StalkAltan** [comment]
Hi there! This issue is caused by Nx not having enough Git history available to compute affected projects.

There are two things to check here:
1) Do you *have* and *use* a branch called `master`? If not, you'll want to update `defaultBase` in nx.json to the correct value. Sometimes you will have to prefix this value with `origin` (ex. `origin/main`) if you do not manually want to fetch and track it in your pipeline.
2) Does your Azure Pipeline have "shallow fetches" enabled? (https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops&tabs=yaml#shallow-fetch) Microsoft changed this setting last fall to default to being "on". We recommend setting your `fetch-depth` here to "0", which will check out the entirety of your Git history. This will ensure that Nx can always calculate the affected projects in your pipeline.

We should mention this in the docs as well, so I'll leave this open until that has been updated.

Let me know if this resolves your issue!

**Comment by marc-wilson** [comment]
Thanks, @StalkAltan. A couple of follow up questions:

1. Why would a format check care about git history? Formatting/linting have nothing do with your git history at all.
2. Why would this work locally, but not in a devops pipeline?
3. Why are you assuming `main` is the default branch? git still defaults to `master`. It should be documented that you assume people use `main` and not the default `master`. I don't really understand why the branch name matters at all.
4. If the issue is the lack of git history, how do you propose to run the initial build/release of the project?
5. It seems Nx wants the developer to configure quite a bit of things that should be handled out of the box by git. Putting in all the variables that is essentially doing the logic for what two diffs get compared seems odd. There is a short blurb about this in the docs but no real explanation around why we need to do this. It seems like there is quite a bit of bias in that setup since not everyone only wants to run pipelined on pr's to a specific branch name. For example, I want to run build on every single commit to the origin, regardless of branch name.. Seeing now that I need to (disable?) "shallow fetches" seems kind of odd. Why all the configuration on top of something that should "just work?"

**Comment by marc-wilson** [comment]
Also, the `defaultBase` is already set to `master` in the nx.json file.

**Comment by StalkAltan** [comment]
@marc-wilson 

> Why would a format check care about git history? Formatting/linting have nothing do with your git history at all. I'm assuming this is because it's only trying to format the affected files opposed to the entire repo?

`nx format:check` will run the `lint` target on all your `affected` projects. To determine whether a project was affected by the current commit, relative to some other commit, we need history available. If you don't want this behavior, you can change this to `nx run-many -t lint --all`

> Why would this work locally, but not in a devops pipeline?

Locally, you have ALL the Git history available from every branch you've ever fetched/checked out/worked on. It's very unlikely you'd be running tests against a branch you hadn't already intentionally pulled, but you CAN experience this issue locally. To emulate this scenario, you can manually set the `--base` argument to a branch that doesn't exist.

> Why are you assuming main is the default branch? git still defaults to master. It should be documented that you assume people use main and not the default master. I don't really understand why the branch name matters at all.

This varies per-platform. New Github repositories, for example, set their primary branch to `main`.

> If the issue is the lack of git history, how do you propose to run the initial build/release of the project?

I'm not sure I understand this question.

>It seems Nx wants the developer to configure quite a bit of things that should be handled out of the box by git. Putting in all the variables that is essentially doing the logic for what two diffs get compared seems odd. There is a short blurb about this in the docs but no real explanation around why we need to do this. It seems like there is quite a bit of bias in that setup since not everyone only wants to run pipelined on pr's to a specific branch name. For example, I want to run build on every single commit to the origin, regardless of branch name.. Seeing now that I need to (disable?) "shallow fetches" seems kind of odd. Why all the configuration on top of something that should "just work?"

It's well within your power to rebuild everything every commit -- however, you can save a lot of time and CI budget by leveraging the `nx affected` commands. Since Nx understands your workspace, you are getting the same guarantee of working code, while performing the minimum work possible. I'd recommend taking a look at this docs page to further understand the value: https://nx.dev/concepts/affected

**Comment by marc-wilson** [comment]
Thanks, @StalkAltan. I'll take a look at the documentation and see if that starts to makes sense. I think I'm still confused on question 4. I have a master branch with a fresh nx/nest app. I made a feature branch, made a subtle change, and PR'd the feature branch into master.

When the pipeline runs, I get the error I mentioned above on the `format:check` step. I have printed out the variables to the logs and see a few red flags:

- NX_BRANCH: This ends up just being a string ($(System.PullRequest.PullRequestNumber)) and not the actual PR Number. The Build.Reason is Pull Request so I'm not sure why this isn't getting the actual PR number. But, I see no usage of NX_BRANCH so i'm guessing that is used behind the scenes somewhere in nx.
- TARGET_BRANCH is set to origin/master which is correct as that is the branch i am PRing into.
- BASE_SHA: $(git merge-base origin/master HEAD) string. The $(TARGET_BRANCH) resolved fine, but doesn't look like the git command actually ran and returned the SHA.

Here's the chunk from the documentation I am referring to.
```
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    NX_BRANCH: $(System.PullRequest.PullRequestNumber)
    TARGET_BRANCH: $[replace(variables['System.PullRequest.TargetBranch'],'refs/heads/','origin/')]
    BASE_SHA: $(git merge-base $(TARGET_BRANCH) HEAD)
```
Can you please try verifying what you have documented works with a basic setup?

**Comment by marc-wilson** [comment]
Found the first issue. `$(System.PullRequest.PullRequestNumber)` is only populated by GitHub. Not Azure DevOps. You have to use `$(System.PullRequest.PullRequestId)` instead.

> The number of the pull request that caused this build. This variable is populated for pull requests from GitHub which have a different pull request ID and pull request number. This variable is only available in a YAML pipeline if the PR is affected by a branch policy.

Ref: https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

**Comment by marc-wilson** [comment]
After some more testing, it doesn't appear that $(git merge-base $(TARGET_BRANCH) HEAD) works either. I'm guessing this why the documentation states to try some of the other methods? In any case, it is starting to feel like the documentation is in dire need of an update because it's not designed to work with Azure DevOps. If I can get this working, I'll gladly contribute an accurate example.

Similar issue: https://stackoverflow.com/questions/57382551/ambiguous-argument-from-git-merge-base-on-azure-deveops

**Comment by marc-wilson** [comment]
As @StalkAltan suggested, disabling Shallow Fetches did the trick. Once you do that, things work great.

The documentation would benefit from the following updates:

- Explanation of what is happening in the `variables` section and who this setup is for. I think most people starting with nx want to compare the latest build in the pr/feature branch with master.
- **Disabling Shallow Fetches is a requirement**. If you don't disable this, you need to figure out some sort of process to pull in the history. I would assume that checking out the master branch alongside the feature branch would work too.
- Use **orgain/branch-name**, not just **branch-name**
- `--base` needs to be passed with the `nx format:check` command.
- `$(System.PullRequest.PullRequestNumber)` is not a valid variable in Azure DevOps. Use `$(System.PullRequest.PullRequestId)` instead. I don't think this step is needed unless someone is after the specific use case with the current `variables` setup.
- Use the method outlined [here](https://nx.dev/recipes/other/azure-last-successful-commit) instead of doing `BASE_SHA: $(git merge-base $(TARGET_BRANCH) HEAD)`

```
    jobs:
      - job: main
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: npm ci
          - script: npx nx format:check --base=origin/master
          - script: npx nx affected --base=origin/master -t lint
          - script: npx nx affected --base=origin/master -t test
          - script: npx nx affected --base=origin/master -t build
```
