### ISSUE TITLE
How to run one specific test in one specific project

### ISSUE THREAD

**Issue by LukasMachetanz** [nrwl/nx#1625]
Is it possible to just run one specific test in one specific project? For me, the expected behavior would be the support of features like `fit` and `test.only`. Unfortunately I could not find any resources or solutions for this topic. I would appreciate every help. Thanks in advance.

**Comment by tcoz** [comment]
This might work, run “ng test mylib —watch” 

It runs all the tests, then gives you options. One of them is to run a test by a regex pattern. You just enter the name of the spec file (or a piece of it if unique enough) and it’ll watch on that file until you tell it differently.

**Comment by mehrad-rafigh** [comment]
You should be able to use ng test your_project --test-name-pattern=regex

If your test is called AuthService for example you can run ng test your_project --test-name-pattern=AuthService
This will only run tests which match the regex. 
Hope this helps. If so, please close the issue :)

**Comment by LukasMachetanz** [comment]
Thank you guys.
