### ISSUE TITLE
can not run ng commands

### ISSUE THREAD

**Issue by jeffschulzusc** [nrwl/nx#16265]
### Current Behavior

latest nx cannont run ng commands ex.

```
$ ng version
 >  NX   Cannot find configuration for task vha:version
   Pass --verbose to see the stacktrace.

$ nx version
 >  NX   Cannot find configuration for task vha:version
   Pass --verbose to see the stacktrace.

$ ng cache clean
 >  NX   Cannot find project 'clean'

$ nx cache clean
 >  NX   Cannot find project 'clean'
```

does nx interact with angular caching ? 
why does 'nx cache clean' result in 'Cannot find project 'clean'' ?
https://angular.io/cli/cache

### Expected Behavior

shouldnt all (latest version) ng command be available thru the nx angular cli decoration ?

### Steps to Reproduce

1. $ ng version
2. $ ng cache clean

### Nx Report

```shell
Node : 16.16.0
   OS   : darwin arm64
   npm  : 8.11.0
   
   nx                      : 15.7.1
   @nrwl/jest              : 15.7.1
   @nrwl/linter            : 15.7.1
   @nrwl/workspace         : 15.7.1
   @nrwl/angular           : 15.7.1
   @nrwl/cli               : 15.7.1
   @nrwl/cypress           : 15.7.1
   @nrwl/devkit            : 15.7.1
   @nrwl/eslint-plugin-nx  : 15.7.1
   @nrwl/js                : 15.7.1
   @nrwl/nest              : 15.7.1
   @nrwl/node              : 15.7.1
   @nrwl/tao               : 15.7.1
   @nrwl/webpack           : 15.7.1
   @nrwl/nx-cloud          : 15.0.3
   typescript              : 4.8.4
   ---------------------------------------
   Community plugins:
   @ngrx/effects        : 15.0.0
   @ngrx/entity         : 15.0.0
   @ngrx/router-store   : 15.0.0
   @ngrx/schematics     : 15.0.0
   @ngrx/store          : 15.0.0
   @ngrx/store-devtools : 15.0.0
```

**Comment by jeffschulzusc** [comment]
```
$ ng config cli.cache.environment ci
Using Nx to run Angular CLI commands is deprecated and will be removed in a future version.
To run Angular CLI commands, use \`ng\`.
Error: Confguration file cannot be found.
```
is there doc page for this ?

```
$ \`ng\` cache clean
bash: `ng`: command not found
```

not sure how to use  or what it is doing, seems like opens up default shell

**Comment by Coly010** [comment]
Hey :)

Does your repository contain a postInstall script to decorate the angular cli?

**Comment by Coly010** [comment]
Ok, in that case, it'll be worth removing that.

Then removing your node_modules folder

Then running `npm install`

Your ng commands should now function for Angular CLI commands correctly.

However, the commands you intend to run with Nx, you'll need to now use `nx serve` etc

**Comment by jeffschulzusc** [comment]
ah i see ...
https://github.com/nrwl/nx/releases?page=7

but is kinda significant change,no ? https://github.com/nrwl/nx/pull/14226
"We want Nx to be seen and used as a standalone CLI tool, therefore remove the linking between angular cli + nx"

https://github.com/nrwl/nx/pull/14266 "Reinstate the script but log a warning"
is there a warning logged when i build/install if i still have decorate-angular-cli.js ?

and is this no longer true: "Nx and AngularCLI commands are interchangeable" 
https://nx.dev/more-concepts/nx-and-angular
at least if you replace angular.json with individual project.json(s) ?

thanks much

**Comment by jeffschulzusc** [comment]
maybe this:
```nx g @nrwl/workspace:convert-to-nx-project --all```

could also remove decorating ?

**Comment by Coly010** [comment]
If you aren't using `npm run` in any CI files or JS scripts, then yes, you can feel free to remove those too. 

Everything can be done with just the `nx` CLI.

`nx g @nrwl/workspace:convert-to-nx-project --all` must handle more than Angular repositories so it's not a good fit to remove decorating
