### ISSUE TITLE
how to configure the angular workspace when have nx.json

### ISSUE THREAD

**Issue by jeffschulzusc** [nrwl/nx#16267]
### Current Behavior

i migrated to nx.json and individual project files ...

but i still need to do some angular workspace configurations:
https://angular.io/guide/workspace-config

for example: { "cli" { "cache": "..." } }
https://angular.io/cli/cache

how do i do when have  nx.json ?

### Expected Behavior

expect to be able to configure angular workspace for all projects

### Steps to Reproduce

1. migrate to latest nx, so have nx.json and individual project files
2. where can i configure ng workspace ?

### Nx Report

```shell
Node : 16.16.0
   OS   : darwin arm64
   npm  : 8.11.0
   
   nx                      : 15.7.1
   @nrwl/jest              : 15.7.1
   @nrwl/linter            : 15.7.1
   @nrwl/workspace         : 15.7.1
   @nrwl/angular           : 15.7.1
   @nrwl/cli               : 15.7.1
   @nrwl/cypress           : 15.7.1
   @nrwl/devkit            : 15.7.1
   @nrwl/eslint-plugin-nx  : 15.7.1
   @nrwl/js                : 15.7.1
   @nrwl/nest              : 15.7.1
   @nrwl/node              : 15.7.1
   @nrwl/tao               : 15.7.1
   @nrwl/webpack           : 15.7.1
   @nrwl/nx-cloud          : 15.0.3
   typescript              : 4.8.4
   ---------------------------------------
   Community plugins:
   @ngrx/effects        : 15.0.0
   @ngrx/entity         : 15.0.0
   @ngrx/router-store   : 15.0.0
   @ngrx/schematics     : 15.0.0
   @ngrx/store          : 15.0.0
   @ngrx/store-devtools : 15.0.0
```

**Comment by Coly010** [comment]
You shouldn't need the Angular Incremental Cache when using Nx. In any case, you will not be able to use it in such a manner with Nx.

Nx has its own caching layer which is separate to Angular. Angular Incremental Caching will use the default options, but it should also not actually get used all that often due to the cache hits from Nx, which mean you don't need to rebuild the project.

**Comment by jeffschulzusc** [comment]
.angular folder grows by 50MB or so each time clean build of a project ... 
in my case with many projects, my .angular folder becomes huge quickly ... like 90GB  ...
i have also submitted an issue to angular github
