### ISSUE TITLE
withNx changes broke compatibility with other NextJS plugins

### ISSUE THREAD

**Issue by raphzandrade** [nrwl/nx#16278]
### Current Behavior

Apps that use other Next.js plugins, such as remove-imports [[ref](https://github.com/uiwjs/next-remove-imports)], may not function properly with the latest version of Nx.

### Example

Here's an example of a library component import failure that occurred when using a previously functioning plugin:

![image](https://user-images.githubusercontent.com/16387849/231589410-7d6c9da9-36de-481b-bea5-2b6f299348b2.png)

The `next.config.ts` file of the application:

![image](https://user-images.githubusercontent.com/16387849/231589926-22662cc5-e2a0-44c9-bba2-0415fdc49df6.png)

Removing the plugin resolves the error.

### Expected Behavior

It should continue to function with the plugins that were previously operational.

### GitHub Repo

https://github.com/raphzandrade/next-errors

### Steps to Reproduce

1. Add any plugin to a NextJS application;
2. Make sure it uses any component imported from a library;
3. Serve the application.

### Nx Report

```shell
Node : 18.13.0
   OS   : darwin x64
   pnpm : 7.26.2
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/next              : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/nx-cloud          : 15.3.5
   typescript              : 4.9.5
```

**Comment by lourd** [comment]
Related issue at https://github.com/nrwl/nx/issues/16141 with a fix linked.

**Comment by jaysoo** [comment]
I think we need to add a `composePlugins` util similar to `@nrwl/webpack` so these things are easier to do. The example outlined here is how it can be done for now: https://github.com/nrwl/nx/issues/15794#issuecomment-1485782908.

**Comment by jaysoo** [comment]
We'll add something to Nx 16 to make this easier to work with:

```
const plugins = [
  // Add as many plugins here
  withMDX,
  withNx
  // ...
];

// The composed function will know how to handle normal plugins and plugins that return an async function (e.g. `withNx`).
module.exports = composePlugins(...plugins)({
  // normal next.js config
});
```
