### ISSUE TITLE
nx/angular nx generate component cli asking to choose a generator

### ISSUE THREAD

**Issue by AlixRoyere** [nrwl/nx#16275]
### Current Behavior

In an nx/angular project with latest nx dependencies, when using the cli to generate a component, it lags, (sometimes) opens a black windows command prompt and closes it, and always prompts to choose a generator.
```
nx g c toto
? Which generator would you like to use? ... 
@nrwl/angular:component
@schematics/angular:component
```
Choosing a generator is useless as @schematics/angular:component is not taking in account nx project properties. For example, it generates .css file when the project is set to use .scss.
Prompting for choice also leads to wrong user choices, as for other generation commands (nx generate <service, interface, class, enum, module>), which are working properly without choice, @schematics/angular:<something,not component> is automatically selected.

### Expected Behavior

nx cli should execute generation commands by itself, without user having to think about nx inner machinery stuff

Edit: having no lag and no new windows command prompt opening would be nice too

### Steps to Reproduce

1. install nx/angular repository with latest nx version
2. launch in cli `nx g c toto`
3. (possibly see that there is a weird new command prompt opening and closing without a reason)
4. see the cli asking to choose between two generators

### Nx Report

```shell
Node : 16.14.2
   OS   : win32 x64
   npm  : 8.5.0
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
```

**Comment by AlixRoyere** [comment]
If this is not a bug, then is it possible to set somewhere a configuration to choose the correct generator by default? 
And why is it the only one generating conflicts with angular commands?
And how are we supposed to know what generator to use?
Nx has done the choice to prevent the use of ng commands and has deleted angular.json configuration, but it gets less easy to use since our upgrade to angular 15

**Comment by Coly010** [comment]
You definitely raise a good point.

The generator you want is always one prefixed with `@nrwl` or `@nx`.

That said, we'll discuss internally if there's anything we can do to help
