### ISSUE TITLE
generatePackageJson exports wrong dependencies

### ISSUE THREAD

**Issue by JumBay** [nrwl/nx#16282]
### Current Behavior

I have a node app that uses this package `@mailchimp/mailchimp_marketing`. Running the app works fine, but when I build the app, the generated `pacakge.json` has this dependency (see https://github.com/JumBay/nx-package-issue/blob/main/dist/packages/my-node-app/package.json):
```json
"dependencies": {
    "@mailchimp": "mailchimp",
```
instead of (see https://github.com/JumBay/nx-package-issue/blob/main/package.json#L8)
```json
  "dependencies": {
    "@mailchimp/mailchimp_marketing": "^3.0.80",
```

### Expected Behavior

Generate the right dependencies

### GitHub Repo

https://github.com/JumBay/nx-package-issue

### Steps to Reproduce

From the given repository:
1. run `pnpm i` 
2. run `pnpm nx run my-node-app:build:production` 
3. check the generated package.json in `dist/packages/my-node-app`

From a new nx project (using pnpm):
1. Create a new app ` nx g @nrwl/node:app my-node-app --bundler=webpack`
4. In the project.json of this new app (packages/my-node-app/project.json), add this to the build option` "generatePackageJson": true` (https://github.com/JumBay/nx-package-issue/blob/main/packages/my-node-app/project.json#L20)
5. Install mailchimp pacakge: `pnpm add @mailchimp/mailchimp_marketing`
6. In the main.ts file use mailchimp: 
```js
import * as mailchimp from '@mailchimp/mailchimp_marketing';

export function mailchimpRun() {
    console.log({ mailchimp });

}
mailchimpRun();
```
8. Build the app `pnpm nx run my-node-app:build:production`

### Nx Report

```shell
$ nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.12.1
   OS   : darwin x64
   pnpm : 8.1.1

   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
```

**Comment by exsesx** [comment]
Okay, that's nasty; the nx version 15.8.7 doesn't align with the new pnpm lock file (v6). So, everything is resolved correctly when I downgrade to pnpm version 7 and regenerate the lock file.

**Comment by jaysoo** [comment]
pnpm lockfile v7 is now supported by Nx. I forked the original repo and added a PR here that is working.

https://github.com/JumBay/nx-package-issue/pull/1
