### ISSUE TITLE
nx lint - 8.3.0

### ISSUE THREAD

**Issue by pburkindine** [nrwl/nx#1628]
After upgrading to nx 8.3.0, `nx lint` is failing with a bunch of stylelint errors (we normally run stylelint separately with different config for app and spec files).

My understanding was that `nx lint` only runs a nrwl-specific linter of the workspace structure.  Has this changed?

## Expected Behavior

`nx lint` should not run other linters

## Current Behavior

`nx lint` runs stylelint

**Comment by pburkindine** [comment]
Some digging reveals the command is changed to `workspace-lint`

I think this should be reflected in the release notes

**Comment by FrozenPandaz** [comment]
This is correct. I've edited the release notes to mention it in `8.3.0`. This should have been automatically migrated for you. You can rerun the migration by executing the following:

```bash
yarn update --from 8.2.0 --to 8.3.0 --migrate-only
```

**Comment by alfaproject** [comment]
Don't assume that migrations do everything. In our case we run `nx lint` in our pipeline in parallel with `ng lint` and I just found out that `nx lint` is delegating to `ng lint` <.<
