### ISSUE TITLE
@nrwl/esbuild:esbuild ignores esbuildOptions

### ISSUE THREAD

**Issue by thefill** [nrwl/nx#16286]
### Current Behavior

@nrwl/esbuild:esbuild completely ignores esbuildOptions from project.json

### Expected Behavior

@nrwl/esbuild:esbuild should merge default esbuildOptions with provided esbuildOptions.

### Steps to Reproduce

1. Create a new app using esbuild bundler
2. provide options in the app's project.json for esbuildOptions
3. build an app
4. check dist

### Nx Report

```shell
Node : 14.17.6
   OS   : darwin x64
   npm  : 6.14.15

   nx                      : 15.9.1
   @nrwl/js                : 15.9.1
   @nrwl/jest              : 15.9.1
   @nrwl/linter            : 15.9.1
   @nrwl/workspace         : 15.9.1
   @nrwl/cli               : 15.9.1
   @nrwl/devkit            : 15.9.1
   @nrwl/esbuild           : 15.9.1
   @nrwl/eslint-plugin-nx  : 15.9.1
   @nrwl/node              : 15.9.1
   @nrwl/tao               : 15.9.1
   @nrwl/web               : 15.9.1
   @nrwl/webpack           : 15.9.1
   typescript              : 4.9.5
```

**Comment by h4de5** [comment]
still an issue

**Comment by bramjoosten** [comment]
Unfortunately this has cost me an afternoon to figure out.  Bump.

**Comment by jaysoo** [comment]
This is no longer an issue. Demo here: https://github.com/jaysoo/esbuild-test
