### ISSUE TITLE
Allow for generated package.json to include dependency range from root package.json

### ISSUE THREAD

**Issue by VirtuaBoza** [nrwl/nx#16293]
One of my favorite features of Nx is that I don't have to think about managing my package.json for publishable packages because Nx will ensure the generated package.json will have all the dependencies I used and none that I didn't use. This is no longer the case in v15 as it's using the strict versions from my package-lock file, and it's making managing dependencies across my projects very difficult. I understand the position of the team (below), but I'm wondering if we can be provided with the _option_ to use the same version (range) from the root package.json.

> Also, the new generated pacakge json may have adverse impacts for publishable npm packages as the range specified is important and needs to be included in the generated package json. This also impacts any publishable package using the @nrwl/js:tsc executor.

For publishable packages we suggest creating manual package.json instead of using generated one, **because** it gives you the freedom to specify ranges as you see fit. For example my library could support `@angular/core: >= 10 < 15` but my root package.json would have probably something like `@angular/core: ^14.2.0`. Using root package json ranges for publishable libs is bad practice, as they tend to be more restrictive than needed.

_Originally posted by @meeroslav in https://github.com/nrwl/nx/issues/12675#issuecomment-1301366002_

**Comment by AgentEnder** [comment]
@meeroslav assigning this to you since you are working on similar stuff.

**Comment by meeroslav** [comment]
Thank you @VirtuaBoza, for raising this issue again.

I will create a fix for libraries to not fallback to fixed versions if local `package.json` is missing.
