### ISSUE TITLE
Add video option to cypress executor

### ISSUE THREAD

**Issue by JesseZomer** [nrwl/nx#16305]
- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I would like to be able to set the [video option](https://docs.cypress.io/guides/references/configuration#Videos) from the cypress executor options
## Motivation

Currently we have a "ci" configuration for running our e2e tests in Jenkins. We don't want it to create video's on this run, however the only way to set that currently (afaik) is by copying cypress.config.ts and overriding the "cypressConfig" option. It would be cleaner if I was able to set it as a configuration option in the project.json
## Suggested Implementation

See [PR](https://github.com/nrwl/nx/pull/16306)

**Comment by barbados-clemens** [comment]
As I mentioned in the PR closing comment, this can be controlled in other ways such as a plugin or environment variables, which folks finding this issue down the road [can read](https://github.com/nrwl/nx/pull/16306#issuecomment-1508576784)

But the gist of it is. 

You can look at setting configurations options dynamically via the [`setupNodeEvents`](https://docs.cypress.io/guides/references/configuration#setupNodeEvents)

```ts
export default defineConfig({
  e2e: {
    ...nxE2EPreset(__filename),
    setupNodeEvents(on, config) {
      return {
        ...config,
        video: !process.env.CI
      }
    }
  }
})
```
or via [environment variables ](https://docs.cypress.io/guides/guides/environment-variables#Option-3-CYPRESS_)

```shell
CYPRESS_VIDEO=false nx affected e2e
```

or just define it globally which will depend on your CI provider.

Optionally you can write a .env file with that value and Nx will load that file for you automatically.
https://nx.dev/recipes/environment-variables/define-environment-variables

**Comment by JesseZomer** [comment]
@barbados-clemens thanks for listing some alternatives, I had tried using env vars, but not in the setupNodeEvents. I'll try that :+1:
