### ISSUE TITLE
Linting with affected or run-many --all fails when creating libraries and switching branches

### ISSUE THREAD

**Issue by lourd** [nrwl/nx#16301]
### Current Behavior

When creating a new library and then checking out out another branch or commit, and running use `npx nx run-many --target=lint --all`, it fails. It also fails with `npx nx affected` if you've made a change to a file that affects all projects (e.g. package.json). I've seen two different cases of errors — `No ESLint configuration found` in the newly created directory,  or `NX Invalid lint configuration. Nothing to lint. Please check your lint target pattern(s).`

It even fails when adding `--skip-nx-cache`.

### Expected Behavior

The linting should not fail, as the directories do not exist. 

### Steps to Reproduce

1. Make a workspace
2. Make an initial commit
3. Make a @nrwl/js library
4. `npx nx run-many --all --target=lint` — it passes
5. `git commit`
6. `git checkout HEAD^`
7. `npx run-many --all --target=lint` — it fails

Alternatively, starting with the 4th step:

4. `npx nx affected --target=lint` — it passes
5. `git commit`
6. Make another @nrwl/js library
7. `npx nx affected --target=lint` — it passes
8. `git commit` 
6. `git checkout HEAD^`
10. Install some random package - `npm i cowsay`
11. `npx nx affected --target=lint` — it fails.

### Nx Report

```shell
Node : 16.14.0
   OS   : darwin arm64
   npm  : 8.3.1
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/tao               : 15.9.2
   typescript              : 4.9.5
```

**Comment by AgentEnder** [comment]
I think this may be fixed by: #16210

Can you try with the v16 betas?

**Comment by lourd** [comment]
Just tried with 16.0.0-beta.0 and the error no longer happens 👍 

What's the ETA for v16 release?

**Comment by AgentEnder** [comment]
ASAP, blocked by a few breaking change PRs that are waiting to be merged. Going to close this, since it is fixed.
