### ISSUE TITLE
nx-plugin: cant execute local generator after creation plugin from nx-plugin

### ISSUE THREAD

**Issue by LordOfTheMoon228** [nrwl/nx#16322]
### Current Behavior

I have created new local-plugin called  @finance/tools and generator named lib

On version 13.1.4 of @nrwl/cli and @nrwl/nx-plugin, when trying to execute local generator brings the error

Unable to resolve @finance/tools:lib.
Cannot find module '@finance/tools/package.json'

Current problem in how reading of generators.json is happening

In 13.1.4 version readGeneratorsJson function takes from @nrwl/tao/src/shared/workspace.json

And reading of this throws error

Compare with latest version of nx, readGeneratorsJson takes from nx/src/config/workspaces

And reading of json didnt throws error

Is problem in it, or maybe i have missed something?

### Expected Behavior

Execution of generator produce files and works fine

### Steps to Reproduce

Just create nx-workspace on version 13.1.4 and install @nrwl/nx-plugin, generate plugin and then try to execute local generator

### Nx Report

```shell
Node : 14.21.3
  OS   : darwin x64
  npm  : 6.14.18
  
  nx : 13.1.4
  @nrwl/angular : 13.1.4
  @nrwl/cli : 13.1.4
  @nrwl/cypress : 13.1.4
  @nrwl/devkit : 13.1.4
  @nrwl/eslint-plugin-nx : 13.1.4
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.4
  @nrwl/linter : 13.1.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 13.1.4
  @nrwl/nx-cloud : 12.5.4
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.4
  @nrwl/web : Not Found
  @nrwl/workspace : 13.1.4
  @nrwl/storybook : 13.1.4
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

### Failure Logs

```shell

```

**Comment by AgentEnder** [comment]
Local plugin support was added in 13.10, if you are on a prior version they will not work:  https://blog.nrwl.io/what-is-new-in-nx-13-10-a58d2051d73
