### ISSUE TITLE
create-nx-workspace fails with Yarn berry

### ISSUE THREAD

**Issue by gremlin896** [nrwl/nx#16336]
### Current Behavior

Running `npx create-nx-workspace@latest myorg --preset=ts --nxCloud=false --packageManager=yarn` with `yarn@3.5.0` results in the following output

``` 
>  NX   Nx failed to create a workspace.

   Error:
```

Running the same command with `yarn@1.22.19` creates the workspace as expected

### Expected Behavior

The workspace should be created.

### Steps to Reproduce

Run the following commands (assuming [volta](https://volta.sh/) is installed)

1. `volta install yarn@3`
2. `npx create-nx-workspace@latest myorg --preset=ts --nxCloud=false --packageManager=yarn` 

### Nx Report

```shell
n/a
```

### Failure Logs

```shell
>  NX   Nx failed to create a workspace.

   Error:
```

**Comment by a88zach** [comment]
+1

**Comment by Krimax0** [comment]
+1

**Comment by amartincolby** [comment]
I'm on Windows 11 with the newest version of everything and it works for me now.
