### ISSUE TITLE
Consuming a react library component package that created with NX is not tree shakeable

### ISSUE THREAD

**Issue by ofirrifo** [nrwl/nx#16331]
### Current Behavior

I'm using NX 14.x.x in order to create a react NPM package library for UI component.
The issue is the build create a one index.js file which is not tree shakeable.
So when I consume the library and use just one component for example Button I still get all other components in the library For example Checkbox.

It seems it related to how the default nrwl rollup bundler config.

### Expected Behavior

The build of the react component library should be build as a tree shakeable so consumer bundler can remove un used components

### Steps to Reproduce

1. Create an NX react library using Rollup
2. Create 2 components that can consume by any app
3. Build project 
4. Publish as NPM package
5. Create another mono repo with NX and add react app
6. install the react library 
7. consume only one of the component in the react app
8. build the app 
9. take a look on the build 

the build contain both component beside we use just one of them

### Nx Report

```shell
Node : 16.10.0
   OS   : darwin x64
   npm  : 7.10.0
   
   nx : 14.5.8
   @nrwl/angular : 14.8.6
   @nrwl/cypress : 14.5.8
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.8
   @nrwl/eslint-plugin-nx : 14.5.8
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.8
   @nrwl/js : 14.5.8
   @nrwl/linter : 14.5.8
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.8
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.8
   @nrwl/web : 14.5.8
   @nrwl/workspace : 14.5.8
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nxext/stencil: 14.0.6
```

**Comment by razvan-tudosa** [comment]
I have the same issue. @ofirrifo  did you find anything on this topic?
