### ISSUE TITLE
Add ability to watch files for changes in nx:run-commands executor

### ISSUE THREAD

**Issue by skynetigor** [nrwl/nx#16341]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

For certain cases it might be useful for developers to have ability to run commands through nx:run-commands executer when something changes in specific files

## Motivation

For custom build commands being able to rerun these commands once specific files change.

## Suggested Implementation

For the nx:run-commands executre there might be added a property called watchGlob (or some better name) that would indicate what files have to be watched. Example:
![image](https://user-images.githubusercontent.com/20903171/232507709-489d166a-4aa7-436c-9fbe-e59e1b2f9337.png)

With this property, if a developer runs **nx customCommandTarget --watch** nx:run-commands will be able to work as well as for example @nrwl/angular:webpack-browser executor - will watch for file changes by specified watchGlob and re-run commands.

## Alternate Implementations

This is rather a workaround than an alternate implementation. But it would be nice if NX supported this natively.
For my use case, I implemented a small JS script that in case of having "--watch" flag uses onchange NPM package in order to observe file changes. If I don't pass "--watch" flag the script just executes "--command".

### Script:
![image](https://user-images.githubusercontent.com/20903171/232509607-f13b04b1-c671-4878-aeac-1e098ca39985.png)

### package.json:
![image](https://user-images.githubusercontent.com/20903171/232510076-2bfa1be5-672f-4d48-9f7a-6adacbedabd1.png)

### Usage in nx:run-commands:
![image](https://user-images.githubusercontent.com/20903171/232510381-de8d8e86-8a1e-49ed-8dd2-019a7b79ba50.png)

**Comment by Coly010** [comment]
Could you use the `nx watch` command? It does watch changes for the listed projects instead of a files glob, but it should give you desired behaviour right?

https://nx.dev/packages/nx/documents/watch
https://nx.dev/recipes/other/workspace-watching

**Comment by skynetigor** [comment]
@Coly010 yes, it could help. But, the idea was to make **nx:run-commands** based targets act the same as @nrwl/angular:webpack-browser when you put --watch flag.
So using it, developers could have the same interface for both cases:
nx build --watch (@nrwl/angular:webpack-browser)
nx customBuild --watch (nx:run-commands)

nx watch I think is also acceptable, but it requires more work to be done than just --watch flag

**Comment by skynetigor** [comment]
However, having nx watch could possibly replace --watch flag in @nrwl/angular:webpack-browser. So if this is the case, we can close this feature request.
