### ISSUE TITLE
react-native - Android assets bug

### ISSUE THREAD

**Issue by k0rnl** [nrwl/nx#16346]
### Current Behavior

When I create a react-native application in a deeper folder structure, the assets of the embedded shared libraries are not displayed in Android. (works fine on iOS)

Android simulator: Pixel 6 Pro API 33 (Tiramisu - Android 13.0 Google APIs arm64-v8a)
iOS simulator: iPhone 14 - iOS 16.2

----

react-native app name: `test-app` [iOS: it works fine ; Android: it works fine]
path: `packages/test-app`

<details>
<summary>test-app - App.tsx</summary>
<br>

```jsx
import React from 'react';
import { SafeAreaView, Text } from 'react-native';

import { Button } from '@testgithub/lemit/shared-ui/button';

export const App = () => {
  return (
    <SafeAreaView>
      <Text>test-app</Text>
      <Button label="LoremIpsum component" />
    </SafeAreaView>
  );
};

export default App;
```

</details>

<details>
<summary>test-app screenshots</summary>
<br>
<img width="260" alt="Screenshot 2023-04-17 at 17 26 04" src="https://user-images.githubusercontent.com/128637540/232539586-4c594ea5-d8f8-4982-bc7e-79b0cab63681.png">

<img width="260" alt="Screenshot 2023-04-17 at 17 30 52" src="https://user-images.githubusercontent.com/128637540/232539601-20102698-fb5b-4cff-9ff5-1af397ace822.png">
</details>

----

react-native app name: `lemit-features-lemit-app` [iOS: it works fine ; **Android: Not working well**]
path: `packages/lemit/features/lemit-app`

<details>
<summary>lemit-app - App.tsx</summary>
<br>

```jsx
import React from 'react';
import { SafeAreaView, Text } from 'react-native';

import { Button } from '@testgithub/lemit/shared-ui/button';

export const App = () => {
  return (
    <SafeAreaView>
      <Text>lemit-app</Text>
      <Button label="LoremIpsum component" />
    </SafeAreaView>
  );
};

export default App;
```

</details>

<details>
<summary>test-app screenshots</summary>
<br>
<img width="260" alt="Screenshot 2023-04-17 at 17 25 36" src="https://user-images.githubusercontent.com/128637540/232539573-ae24d74b-3df7-4fe1-904e-df8a699723a3.png">

<img width="260" alt="Screenshot 2023-04-17 at 17 28 33" src="https://user-images.githubusercontent.com/128637540/232539593-d4e25072-3696-4252-9c99-5f989d2da60b.png">
</details>

----
<details>
<summary>button component code</summary>
<br>

```jsx
import React from 'react';
import { Image, View, Text } from 'react-native';

export function Button({ label }: { label: string }) {
  return (
    <View style={{ flexDirection: 'row', alignItems: 'center' }}>
      <Image source={require('./assets/bananas.png')} />
      <Text>{label}</Text>
    </View>
  );
}

export default Button;
```

</details>

### Expected Behavior

The behaviour I expect is that if an application is deeper on Andorid , assets are displayed.

### GitHub Repo

https://github.com/k0rnl/nx-bug

### Steps to Reproduce

1. npm install
2. npx nx run test-app:run-android
3. npx nx run lemit-features-lemit-app:run-android

### Nx Report

```shell
n/a
```

**Comment by omniviewsports** [comment]
@k0rnl - I had the same error. The only way I could fix it was by using a remote image source. I created a free Cloudinary account to store my images. Alternatively, you could store your images in an AWS S3 bucket.

**Comment by k0rnl** [comment]
If I run it in release mode, the images appear. 🚀 It's fine as a temporary solution, but it would be great if it would work in debug mode too.

https://nx.dev/packages/react-native/executors/run-android#mode
```json
    "run-android": {
      "executor": "@nrwl/react-native:run-android",
      "options": {
        "mode": "release"
      }
    },
```

<details open>
<summary>screenshot</summary>
<br>
<img width="399" alt="Screenshot 2023-04-18 at 9 26 25" src="https://user-images.githubusercontent.com/128637540/232703975-4a3dc8a7-a8ff-4ca5-b774-a53767b264d9.png">
</details>

**Comment by xiongemi** [comment]
Tltr: i tried a few ways, but I could not get it to work. 

i could replicate itthis error. I noticed when try to bundle android with command `nx bundle-android <app>`, there is one command saying 
```
warn Assets destination folder is not set, skipping...
```
so it is deliberately skipping bundling the assets because `Assets destination folder` is not set by default. I think it is related to https://github.com/react-native-community/cli/blob/main/packages/cli-plugin-metro/README.md#--assets-dest-string. 
This error comes from https://github.com/react-native-community/cli/blob/main/packages/cli-plugin-metro/src/commands/bundle/saveAssets.ts#L33. 
This needs to be set when building Android.
I tried to specify this in app's /android/app/build.gradle:
```
    extraPackagerArgs = ['assets-dest', '$buildDir/intermediates/assets/debug']
```

however, this does not work. 


i was reading the documentation https://github.com/react-native-community/cli/blob/main/packages/cli-plugin-metro/README.md#--bundle-output-string, it says i need to set `bundleInDebug` to true, but i do think this doc is way out of date.

**Comment by mtzfactory** [comment]
Hi! I could solve the problem using [react-native-monorepo-tools](https://github.com/mmazzarolo/react-native-monorepo-tools), just install it and update the `metro.config.js` in the app folder, this is how it should looks like:

```javascript
const {
  getMetroAndroidAssetsResolutionFix,
} = require('react-native-monorepo-tools');

const androidAssetsResolutionFix = getMetroAndroidAssetsResolutionFix();

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig();
  return withNxMetro(
    {
      resolver: {
        assetExts: assetExts.filter((ext) => ext !== 'svg'),
        blockList: exclusionList([/^(?!.*node_modules).*\/dist\/.*/]),
        resolverMainFields: ['sbmodern', 'browser', 'main'],
        sourceExts: [...sourceExts, 'svg'],
      },
      server: {
        enhanceMiddleware: (middleware) => {
          return androidAssetsResolutionFix.applyMiddleware(middleware);
        },
      },
      transformer: {
        babelTransformerPath: require.resolve('react-native-svg-transformer'),
        getTransformOptions: async () => ({
          transform: {
            experimentalImportSupport: false,
            inlineRequires: true,
          },
        }),
        publicPath: androidAssetsResolutionFix.publicPath,
      },
    },
    {
      // Change this to true to see debugging info.
      // Useful if you have issues resolving modules
      debug: false,
      // all the file extensions used for imports other than 'ts', 'tsx', 'js', 'jsx', 'json'
      extensions: [],
      // the project root to start the metro server
      projectRoot: __dirname,
      // Specify folders to watch, in addition to Nx defaults (workspace libraries and node_modules)
      watchFolders: [],
    }
  );
})();
```
