### ISSUE TITLE
Serving Storybook From WSL Results in Empty Response in Browser

### ISSUE THREAD

**Issue by ajs11174** [nrwl/nx#16359]
### Current Behavior

The browser receives an empty response from the storybook server when running `nx run ui:storybook` from WSL.

### Expected Behavior

The browser should receive and render the storybook page. 

### GitHub Repo

https://github.com/ajs11174/storybook-wsl

## WSL - Storybook Repo

---

This repo is to demonstrate that Storybook does not respond when started from WSL2. If you clone this repo into WSL2 it will not serve any data. If you clone this repo into Windows it will start.

Here's a screenshot of what Chrome responds with when served from WSL2:

![image](https://user-images.githubusercontent.com/26338484/232643968-a834208e-7842-4513-89bc-260e35279f46.png)

I can confirm that hitting the server with a curl from either WSL or Windows returns the index page. However, the browser does not receive any data (Tested with Chrome and Edge.)

---

### Set up an nx workspace

```bash
nx create-nx-workspace@latest --preset=ts
```

Change the apps and libs folders to `/apps` and `/libs` in `nx.json`

### Set up a React library
```bash
npm i @nrwl/react@latest
nx g @nrwl/react:library ui --style=none --unitTestRunner=jest --bundler=none
nx g @nrwl/react:component input --project=ui --export=true --style=none
```
Remove the auto generated `ui` component

### Set up Storybook and Generate Stories
```bash
npm i -D @nrwl/storybook
nx g @nrwl/storybook:configuration ui --uiFramework=@storybook/react --tsConfiguration=true --configureCypress=true
nx g @nrwl/react:stories ui
```

### Run the Storybook server
```bash
export NODE_OPTIONS=--openssl-legacy-provider
nx run ui:storybook
```

### Nx Report

```shell
# Windows

>  NX   Report complete - copy this into the issue template

   Node : 18.16.0
   OS   : win32 x64
   npm  : 9.5.1

   nx (global)             : 15.9.2
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/storybook         : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5

---

# WSL

 >  NX   Report complete - copy this into the issue template

   Node : 18.16.0
   OS   : linux x64
   npm  : 9.5.1
   
   nx (global)             : 15.9.2
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/storybook         : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
```

**Comment by mandarini** [comment]
Hi there @ajs11174 ! Thanks for filing this bug! I am not sure that this is an issue with Nx. Have you tried this with just a pure storybook app?

Can you try the steps described here: https://storybook.js.org/tutorials/intro-to-storybook/react/en/get-started/
and tell me if it works on WSL?

**Comment by ajs11174** [comment]
I found a workaround by setting the port to 80. This then prompts that port 80 is not available and suggests a random port (e.g. 38503). I'm able to connect to this recommended port and storybook works as expected.

If I stop the server, update the settings to use the previously recommended port, and then start the server, I run into the same issue.

I'll be honest my knowledge of WSL, networking, and storybook are quite low but it feels like there is a bug here. 

Also to confirm I don't have anything running on port 80 that prompts storybook to recommend a different port. I feel like I'm playing whac-a-mole here debugging this, but the above solution does work.

**Comment by mandarini** [comment]
I'll be closing this, but feel free to ping me and I'll reopen. It is not an issue with Nx, and there is a workaround available.
