### ISSUE TITLE
enable jest runner to fail when errorOnUnknownElements or errorOnUnknownProperties

### ISSUE THREAD

**Issue by fegyi001** [nrwl/nx#16352]
## Description
When I run my Jest tests in my Angular Nx monorepo I see that whenever a component or property is not properly imported in the .spec.ts file the test does not fail, although in the console an error is clearly visible. 
Such as
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/4125222/232591125-20e393a0-f54b-4162-9e11-17ddac9b0ab2.png">

After looking for solutions I found that Angular has a way to fix it as described here: https://github.com/angular/angular/issues/36430#issuecomment-1117801535

I would like to configure at a root level my projects. I do not intend to configure every single test files for catching these errors. I would like to alter e.g. the root `jest.preset.js` file.

At another library (https://thymikee.github.io/jest-preset-angular/docs/getting-started/test-environment/) I saw that it should be possible with proper setup, adding `errorOnUnknownElements: true` and `errorOnUnknownProperties: true` to the jest config (at the `testEnvironmentOptions` property which in theory exists in `jest.preset.js` as well), but adding it to the file did not affect at all.

## Motivation
I think if an error occures on the console a test should fail. The current behaviour is quite misleading, allowing tests to pass, although they did not.

## Suggested Implementation
With adding some configurations to the root `jest.preset.js` file one should be able to toggle this behaviour. In my opinion this should be the default behaviour.

## Alternate Implementations
This could also be set at an app/lib level, but it is code duplication and can be opted out which is not good in my opinion.

**Comment by barbados-clemens** [comment]
@fegyi001 do you have a repo I can test/experiment with on this?
