### ISSUE TITLE
One Storybook for all - affected build

### ISSUE THREAD

**Issue by AsmisAlan** [nrwl/nx#16374]
## Description
Is there any way to run the build affected for storybook with a project with just one storybook configured as you recommend in this tutorial: https://nx.dev/recipes/storybook/one-storybook-for-all?
I tried this https://github.com/nrwl/nx/issues/3397 but it didn't work, because the files changed are outside the storybook project.
If I have to build the entire "storybook" project just if some library have been changed its ok for me.

## Suggested Implementation
I tried to configure my nx.json file with an implicit dependency but I don't know if its the correct way to deal with it. 

```json
{
    "implicitDependencies": {
        ....
        "./my-folder/**/*.[ts,scss,html]": ["storybook"]
    },
    ....
}
```

**Comment by mandarini** [comment]
Hi there @AsmisAlan ! Yes, the correct way to do this is to configure your dependencies manually through nx.json! Check out this page in our documentation: https://nx.dev/reference/project-configuration#implicitdependencies

It explains how you can manually add your dependencies!

**Comment by mandarini** [comment]
I will be closing this, but let me know if you need more support! I will try to add this in the documentation, to make sure ppl know how to deal with it! Thank you for pointing it out!
