### ISSUE TITLE
Affected not working with non-ascii directories

### ISSUE THREAD

**Issue by zy2ba** [nrwl/nx#16406]
### Current Behavior

if some files contains in their directory non-ascii symbols (for example russian lang), then `nx affected` can't detects changes in this files and, obviously, not detect that project is affected

### Expected Behavior

changes in any files of project pass project to affected (obviously, if named inputs not redefined to some strange custom strategy, lol)

### GitHub Repo

https://github.com/zy2ba/nx-affected-wrong-working-example

### Steps to Reproduce

1. pull [repo](https://github.com/zy2ba/nx-affected-wrong-working-example) 
2. npm ci
3. switch to branch `feature/some-changes`
4. run `nx print-affected --type=lib --select=projects`
5. gets empty input. Thats it! (in fact, lib `a.что-то-по-русски` must be printed as affected)

### Nx Report

```shell
C:\tools\nvm\v16.20.0\npm.cmd run nx-report

> wrong-affected-example@0.0.0 nx-report
> nx report


 >  NX   Report complete - copy this into the issue template

   Node : 16.20.0
   OS   : win32 x64
   npm  : 8.19.4

   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/tao               : 15.9.2
   typescript              : 4.9.5


Process finished with exit code 0
```

### Failure Logs

```shell
C:\Projects\wrong-affected-example>git diff --name-only --no-renames --relative 148a4afb476be8808fd1da3868fc3ac80751820f HEAD 
"packages/a.\321\207\321\202\320\276-\321\202\320\276-\320\277\320\276-\321\200\321\203\321\201\321\201\320\272\320\270/src/index.ts"
C:\Projects\wrong-affected-example>nx print-affected --type=lib --select=projects
<empty result>
```

### Additional Information

nx use `git diff --name-only --no-renames --relative <base-commit-in-base-branch> HEAD` under the hood.
If directory of file contains non-ascii symbols, then git with standard settings, in returned result, wraps that dirs with quotes and replace symbols with their codes.
when process of matching changed files with project goes into nx/src/project-graph/utils/find-project-for-path#findProjectForPath, then it corrupts, because node function just path.dirname cuts string to next slash. In result, matching of currentPath and any project in projectRootMap not happens

Also repo generated with this steps:

1. `npx create-nx-workspace wrong-affected-example`
2. select package based template
3. npm i -D @nrwl/workspace
4. nx g @nrwl/workspace:lib a.что-то-по-русски
5. commit
6. create new branch
7. change const in `a.что-то-по-русски` lib
8. commit

**Comment by PavelMinev** [comment]
I was also confused when faced the same problem in my project
