### ISSUE TITLE
Angular 15, Nx 15.9.2 w Storybook 7

### ISSUE THREAD

**Issue by tyanders1987** [nrwl/nx#16415]
### Current Behavior

I have several components that extend base classes that include additional properties. When I run the Nx stories generator for a component that extends another component, the generated stories only resolve the properties that are local to the actual component file and doesn't seem to resolve the extended components properties. 

### Expected Behavior

I would expect the generator to resolve properties from extended classes and add them to the "args" section on the story.

### GitHub Repo

https://github.com/tyanders1987/sb-test

### Steps to Reproduce

1. Create nx workspace for Angular Standalone Project
2. Create lib with a single component
3. Add a base class for 'common' properties.
4. Extend this class in the component created in Step 2.
5 Install and set up Storybook 7 using Nx schematics.
6. Generate stories.

### Nx Report

```shell
Node : 16.16.0
   OS   : win32 x64
   npm  : 8.11.0

   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/storybook         : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @storybook/angular : 7.0.6
```

### Failure Logs

```shell
Does not seem to produce any errors or failures.
```

**Comment by Coly010** [comment]
Hi!

Thanks for raising an issue about this, however, the path to do this is extremely complex as it cannot be done via standard AST parsing alone. A TS Program would need to be created to analyse the files and create the relationships between the classes and their heritages. 

This is not something we're going to address. I'm sorry that this is not the response you would have liked to hear!
