### ISSUE TITLE
Why command `build-ios` invoke `run-ios`?

### ISSUE THREAD

**Issue by whalemare** [nrwl/nx#16419]
### Current Behavior

https://github.com/nrwl/nx/blob/0fc3d4441eb6900f8bdf0091c39f65e3cd1977ba/packages/react-native/src/executors/build-ios/build-ios.impl.ts#L85

### Expected Behavior

Expected that it will invoke `build-ios`

### Steps to Reproduce

https://github.com/nrwl/nx/blob/0fc3d4441eb6900f8bdf0091c39f65e3cd1977ba/packages/react-native/src/executors/build-ios/build-ios.impl.ts#L85

### Nx Report

```shell
https://github.com/nrwl/nx/blob/0fc3d4441eb6900f8bdf0091c39f65e3cd1977ba/packages/react-native/src/executors/build-ios/build-ios.impl.ts#L85
```

**Comment by xiongemi** [comment]
fixed in pr https://github.com/nrwl/nx/pull/16624. should be in nx release > 16
