### ISSUE TITLE
[pnpm8] lock file format not supported by pnpm-parser in @nrwl/nx resulting in wrong projectGraph.externalNodes

### ISSUE THREAD

**Issue by krema** [nrwl/nx#16427]
### Current Behavior

Incorrect package information is cached for __@vendia/serverless-express__ in `node_modules/.cache/nx/nxdeps.json`, resulting in a wrongly generated `package.json` file when using the option `"generatePackageJson": true` within `@nrwl/webpack:webpack` task.

node_modules/.cache/nx/nxdeps.json:

    "npm:@vendia": { <------ wrong
      "type": "npm",
      "name": "npm:@vendia", <------ wrong
      "data": {
        "version": "serverless-express@4.10.1", <----- wrong
        "packageName": "@vendia",
        "hash": "sha512-8FM/GnQ8bbp1fynAWLGzNIy3Hyhoevixwh2Aj8qBPpw7rkbWZ1I7RC2XhZZaTZo/1JTDlff4cDDmkgY0CzUV7g=="
      }
    },

The generated package.json for the app in _dist/apps/my-app_

    {
      "name": "my-app",
      "version": "0.0.1",
      "dependencies": {
        "@vendia": "serverless-express@4.10.1",
      },
      "main": "main.js"
    }
    
`nx reset` does not help

    

### Expected Behavior

node_modules/.cache/nx/nxdeps.json

    "npm:@vendia/serverless-express": {
      "type": "npm",
      "name": "npm:@vendia/serverless-express",
      "data": {
        "version": "^4.10.1",
        "packageName": "@vendia/serverless-express",
        "hash": "e0f0e7bb459d1246cbbbabf52ab92f0c80de87291ff513174be4373009714960"
      }
    },

The generated package.json for the app in _dist/apps/my-app_

     {
      "name": "my-app",
      "version": "0.0.1",
      "dependencies": {
        "@vendia/serverless-express": "4.10.1",
      },
      "main": "main.js"
    }

### Steps to Reproduce

1. Install the latest version of @vendia/serverless-express using npm.
2. Create a nodejs app
3. Configure `@nrwl/webpack:webpack` to generate a `package.json` file with the option `"generatePackageJson": true`.
4. Run the build process with nx build.

### Nx Report

```shell
Node : 16.20.0
   OS   : darwin arm64
   pnpm : 8.3.0
   
   nx (global)             : 15.9.2
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/nest              : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/nx-plugin         : 15.9.2
   @nrwl/tao               : 15.9.2
   typescript              : 4.8.4
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 14.3.3
   @ngrx/effects         : 14.3.3
   @ngrx/entity          : 14.3.3
   @ngrx/router-store    : 14.3.3
   @ngrx/store           : 14.3.3
   @ngrx/eslint-plugin   : 14.3.3
   @ngrx/schematics      : 14.3.3
   @ngrx/store-devtools  : 14.3.3
```

**Comment by krema** [comment]
I was able to identify the root cause of the issue. It appears that the pnpm-parser used by @nrwl/nx does not support the new lock file format of pnpm8.

You can see this in the pnpm-parser.ts file on line 247:
https://github.com/nrwl/nx/blob/15.9.2/packages/nx/src/plugins/js/lock-file/pnpm-parser.ts#L247

    return key.slice(key.lastIndexOf('/') + 1);

This line of code assumes that the lock file entry for a package will always be in the format 

**pnpm7**: `/package-name/version-number:`

However, in 

**pnpm8**, the format has changed to `/package-name@version-number:`. 

This causes the pnpm-parser to fail when attempting to parse the lock file.

**Comment by PointSingularity** [comment]
@krema ```15.9.2``` Still doesn't have support for pnpm 8.
The upcoming version 16 does: https://github.com/nrwl/nx/releases/tag/16.0.0-beta.0
You could try to update your version to the newest beta and see if it works.

**Comment by krema** [comment]
@PointSingularity Thanks, that makes sense. 

I quickly tried to upgrade it but wasn't successful. I can't build any project due to the error `HookWebpackError: Cannot read properties of undefined (reading 'data')`. However, it seems that the nxdeps.json file now has a different structure, and at first glance, it looked okay. I will close this ticket for now and retest it when a stable release is available
