### ISSUE TITLE
E2e tests fail on workspace created by create-nx-plugin

### ISSUE THREAD

**Issue by vuggy17** [nrwl/nx#16453]
### Current Behavior

E2e test fail on --tag test suite

### Expected Behavior

All e2e tests should pass without any error

### Steps to Reproduce

1. create a plugin: `npx create-nx-plugin electron-v3 --pluginName electron-v`
2. run e2e test on plugin's e2e project by nx-console vscode extension

### Nx Report

```shell
Node : 16.17.0
   OS   : win32 x64
   npm  : 8.15.0
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/nx-plugin         : 15.9.2
   @nrwl/tao               : 15.9.2
   typescript              : 4.9.5
   ---------------------------------------
   Local workspace plugins:
         @electron-v3/electron-v
```

### Additional Information

Try 1: Copy tags test command to run it separately on the console => run perfectly
Try 2: comment other tests, then rerun the e2e test again => test past

I think there is a conflict with the file system. Can you guys take a look at it. 

Test error log: 

Command failed: node C:\Users\user1\nx-practices\electron-v3\node_modules\nx\bin\nx.js new proj --nx-workspace-root=C:\Users\user1\nx-practices\electron-v3/tmp/nx-e2e --no-interactive --skip-install --collection=@nrwl/workspace --npmScope=proj --preset=empty

      at runNxNewCommand (../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:15:18)
      at newNxProject (../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:72:3)
      at ensureNxProject (../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:86:3)
      at tests/electron-v.spec.ts:50:22
      at ../../node_modules/tslib/tslib.js:167:75
      at Object.__awaiter (../../node_modules/tslib/tslib.js:163:16)
      at Object.<anonymous> (tests/electron-v.spec.ts:48:53)

**Comment by vuggy17** [comment]
Extra info: 
After play with it for a couple minutes, I find that there is a ensureNxProject call in --tag test case, that makes my test fail. Then I decided to remove that line => all my test passed. My testcase is refresh generated by nx console.

This should pass: 
```
 describe('--tags', () => {
    it('should add tags to the project', async () => {
      const projectName = uniq('electron-vite');
      // ensureNxProject(
      //   '@electron-v4/electron-vite',
      //   'dist/packages/electron-vite'
      // );
      await runNxCommandAsync(
        `generate @electron-v4/electron-vite:app ${projectName} --tags e2etag,e2ePackage`
      );
      const project = readJson(`libs/${projectName}/project.json`);
      expect(project.tags).toEqual(['e2etag', 'e2ePackage']);
    }, 120000);
  });
```
And this won't
```
describe('--tags', () => {
    it('should add tags to the project', async () => {
      const projectName = uniq('electron-vite');
      ensureNxProject(
        '@electron-v4/electron-vite',
        'dist/packages/electron-vite'
      );
      await runNxCommandAsync(
        `generate @electron-v4/electron-vite:app ${projectName} --tags e2etag,e2ePackage`
      );
      const project = readJson(`libs/${projectName}/project.json`);
      expect(project.tags).toEqual(['e2etag', 'e2ePackage']);
    }, 120000);
  });
```

**Comment by AgentEnder** [comment]
Awesome, thanks for digging into that a bit deeper. These E2E tests have been updated on master, so I'm going to go ahead and close this out.
