### ISSUE TITLE
Can't use interactive command if called by NX

### ISSUE THREAD

**Issue by bastienlemaitre** [nrwl/nx#16457]
### Current Behavior

If I execute this command directly in the application folder, I can interact with the prompt by choosing my options with the arrows : `npx --package=@capacitor/cli cap run ios --livereload --external`

If this time I go through NX, via the command `nx run app-insured:run:ios`, I can't interact with the arrows and I see special characters :  `^[[B^[[A^[[C^[[B^[[D^[[A^[[D`

Here is the command:

```json
"run": {
  "executor": "@nxext/capacitor:cap",
  "options": {
    "cmd": "run"
  },
  "configurations": {
    "ios": {
      "cmd": "run ios --livereload --external"
    },
    "android": {
      "cmd": "run android --livereload --external"
    }
  }
},
```

### Expected Behavior

Have access to the interactive controls in the same way 

### Steps to Reproduce

1. Run `nx run app-insured:run:ios` which will propose options in the terminal to choose with the arrows.
2. Choose your option with the arrow.
3. Special characters will appear, not works
4. Try to run the command associated with the last nx alias directly in the application folder
5. Works, you can choose your option

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 19.4.0
   OS   : darwin arm64
   npm  : 9.2.0
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/storybook         : 16.0.0-beta.1
   @nrwl/tao               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @nestjs/ng-universal        : 7.0.0
   @nguniversal/express-engine : 15.2.0
   @nguniversal/builders       : 15.2.0
   @nxext/capacitor            : 15.7.0
   @storybook/angular          : 7.0.5
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/storybook@16.0.0-beta.1
   
   To fix this, run `nx migrate nx@16.0.0-beta.1`
```

**Comment by AgentEnder** [comment]
This is something that the executor author may be able to fix, there's some context here: https://github.com/nrwl/nx/issues/15924

I'd suggest opening an issue on the nxext repo though, since this isn't on our side.
