### ISSUE TITLE
vite cannot handle the contents of third-party packages containing process.env.

### ISSUE THREAD

**Issue by StringKe** [nrwl/nx#16452]
### Current Behavior

I'm re-exporting the `mantine ui` and I'm running into some problems when I compile

Problem: importing `umd` `js` file in the browser after compilation encounters `Uncaught ReferenceError: process is not defined` 

Tried to fix it

Add the

```
    define: {
        'process.env': {}.
    }.
```

This solves the `Uncaught ReferenceError: process is not defined` problem

But this introduces another problem in the file `libs/ui-lib/src/components/atomic/Others/index.ts` on line 19 20 21, I can't export these three components if I export them I get a new error

```
[commonjs--resolver] Unexpected token (370:8) in PROJECTE_ROOT/node_modules/.pnpm/prop-types@15.8.1/node_modules/prop-types/ factoryWithTypeCheckers.js
file: PROJECTE_ROOT/node_modules/.pnpm/prop-types@15.8.1/node_modules/prop-types/index.js:370:8
368: function createUnionTypeChecker(arrayOfTypeCheckers) {
369: if (!Array.isArray(arrayOfTypeCheckers)) {
370: process.env.NODE_ENV ! == 'production' ? printWarning('Invalid argument supplied to oneOfType, expected an insta...
             ^
371: return emptyFunctionThatReturnsNull.
372: }
```

### Expected Behavior

Compile all content normally

### GitHub Repo

https://github.com/StringKe/nx-vite-define-watch-error

### Steps to Reproduce

1. `pnpm install`
2. `pnpm nx run ui-lib:serve`
3. or run `pnpm nx run ui-lib:build`

### Nx Report

```shell
>  NX  Unable to locate swc-node or ts-node. Nx will be unable to run local ts files without transpiling.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node : 18.15.0
   OS   : darwin arm64
   pnpm : 8.3.1
   
   nx (global)             : 15.9.2
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/vite              : 15.9.2
   typescript              : 4.9.5
```

### Failure Logs

```shell
[commonjs--resolver] Unexpected token (370:8) in PROJECTE_ROOT/node_modules/.pnpm/prop-types@15.8.1/node_modules/prop-types/ factoryWithTypeCheckers.js
file: PROJECTE_ROOT/node_modules/.pnpm/prop-types@15.8.1/node_modules/prop-types/index.js:370:8
368: function createUnionTypeChecker(arrayOfTypeCheckers) {
369: if (!Array.isArray(arrayOfTypeCheckers)) {
370: process.env.NODE_ENV ! == 'production' ? printWarning('Invalid argument supplied to oneOfType, expected an insta...
             ^
371: return emptyFunctionThatReturnsNull.
372: }
```

**Comment by StringKe** [comment]
> ### Current Behavior
> I'm re-exporting the `mantine ui` and I'm running into some problems when I compile
> 
> Problem: importing `umd` `js` file in the browser after compilation encounters `Uncaught ReferenceError: process is not defined`
> 
> Tried to fix it
> 
> Add the
> 
> ```
>     define: {
>         'process.env': {}.
>     }.
> ```
> 
> This solves the `Uncaught ReferenceError: process is not defined` problem
> 
> But this introduces another problem in the file `libs/ui-lib/src/components/atomic/Others/index.ts` on line 19 20 21, I can't export these three components if I export them I get a new error
> 
> ```
> [commonjs--resolver] Unexpected token (370:8) in PROJECTE_ROOT/node_modules/.pnpm/prop-types@15.8.1/node_modules/prop-types/ factoryWithTypeCheckers.js
> file: PROJECTE_ROOT/node_modules/.pnpm/prop-types@15.8.1/node_modules/prop-types/index.js:370:8
> 368: function createUnionTypeChecker(arrayOfTypeCheckers) {
> 369: if (!Array.isArray(arrayOfTypeCheckers)) {
> 370: process.env.NODE_ENV ! == 'production' ? printWarning('Invalid argument supplied to oneOfType, expected an insta...
>              ^
> 371: return emptyFunctionThatReturnsNull.
> 372: }
> ```
> 
> ### Expected Behavior
> Compile all content normally
> 
> ### GitHub Repo
> https://github.com/StringKe/nx-vite-define-watch-error
> 
> ### Steps to Reproduce
> 1. `pnpm install`
> 2. `pnpm nx run ui-lib:serve`
> 3. or run `pnpm nx run ui-lib:build`
> 
> ### Nx Report
> ```shell
> >  NX  Unable to locate swc-node or ts-node. Nx will be unable to run local ts files without transpiling.
>   - To fix this, ensure @swc-node/register and @swc/core have been installed
> 
>  >  NX   Report complete - copy this into the issue template
> 
>    Node : 18.15.0
>    OS   : darwin arm64
>    pnpm : 8.3.1
>    
>    nx (global)             : 15.9.2
>    nx                      : 15.9.2
>    @nrwl/js                : 15.9.2
>    @nrwl/linter            : 15.9.2
>    @nrwl/workspace         : 15.9.2
>    @nrwl/cypress           : 15.9.2
>    @nrwl/eslint-plugin-nx  : 15.9.2
>    @nrwl/react             : 15.9.2
>    @nrwl/vite              : 15.9.2
>    typescript              : 4.9.5
> ```
> 
> ### Failure Logs
> ```shell
> [commonjs--resolver] Unexpected token (370:8) in PROJECTE_ROOT/node_modules/.pnpm/prop-types@15.8.1/node_modules/prop-types/ factoryWithTypeCheckers.js
> file: PROJECTE_ROOT/node_modules/.pnpm/prop-types@15.8.1/node_modules/prop-types/index.js:370:8
> 368: function createUnionTypeChecker(arrayOfTypeCheckers) {
> 369: if (!Array.isArray(arrayOfTypeCheckers)) {
> 370: process.env.NODE_ENV ! == 'production' ? printWarning('Invalid argument supplied to oneOfType, expected an insta...
>              ^
> 371: return emptyFunctionThatReturnsNull.
> 372: }
> ```
> 
> ### Additional Information
> _No response_

If I try to use `'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),` it works fine, can anyone tell me why this is?

I've searched google for solutions for vite handling process is not defined and they all use `'process.env': {}. `

**Comment by StringKe** [comment]
up

**Comment by jacobtipp** [comment]
@StringKe I am also facing this issue, and in my apps vite config I also provide:

```ts
define: {
    'process.env.NODE_ENV': JSON.stringify(process.env['NODE_ENV']),
  },
  ```

This works when using serve, however, with preview the error is showing up again. 

`Uncaught ReferenceError: process is not defined`

**Comment by Coly010** [comment]
`process.*` including `process.env` etc are only available in a Node context and are not available in a Browser context (`process` doesn't exist in the browser). 

If you need `process` to be defined, then `define: {}` in your `vite.config` is the correct way to do this. 

This is a browser + vite limitation and not an Nx issue, including the issue regarding `preview` as that is also a function of `vite` itself.
