### ISSUE TITLE
 Getting "Unable to import class CommonModule" error while importing a one library into another library

### ISSUE THREAD

**Issue by Sathishkumarcbre** [nrwl/nx#16461]
### Current Behavior

Nx serve throws below error when I used Icon lib inside Button lib.
<img width="1120" alt="Screenshot 2023-04-21 at 8 33 33 PM" src="https://user-images.githubusercontent.com/108940398/233672270-0bbc8e7f-ac95-4107-847b-fa24ae87c40e.png">

Em***-Icon's module
```
import { CUSTOM_ELEMENTS_SCHEMA, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { EmeraldIconComponent } from './emerald-icon/emerald-icon.component';

@NgModule({
  imports: [CommonModule],
  declarations: [EmeraldIconComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  exports: [EmeraldIconComponent],
})
export class EmeraldIconModule {}
```

Eme**-button's module
```
import { CUSTOM_ELEMENTS_SCHEMA, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { EmeraldButtonComponent } from './emerald-button/emerald-button.component';
import {  EmeraldIconModule } from '@emerald-ngmaterial/emerald-icon';

@NgModule({
  imports: [CommonModule,
   EmeraldIconModule
  ],
  declarations: [EmeraldButtonComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  exports: [CommonModule, EmeraldButtonComponent],
})
export class EmeraldButtonModule {}
```

<img width="1405" alt="Screenshot 2023-04-21 at 8 38 18 PM" src="https://user-images.githubusercontent.com/108940398/233673059-7cc56681-e406-4472-a349-00ecd9ee0f73.png">

Building of these two libraries run successfully.

But application serve throws error, when I used Button library which imported Icon Library.

app modules ts
<img width="1127" alt="Screenshot 2023-04-21 at 8 39 32 PM" src="https://user-images.githubusercontent.com/108940398/233673751-a675cd54-be7f-4e53-b4e2-73565d738419.png">

My app works fine below scenarios,
- If I include Icon library alone in app
- If I include Button library without using Icon library

### Expected Behavior

Libraries need to be imported internally. (Library inside another library)
<img width="264" alt="Screenshot 2023-04-21 at 8 52 43 PM" src="https://user-images.githubusercontent.com/108940398/233674600-f29db4e1-b2f2-4df1-a8d3-5f337012383e.png">

### Steps to Reproduce

1.Create two libaries A & B
2. Import Library BModule inside Library AModule
3. Import Library AModule in your App Module file of Angular app(demo-app).
4. Use Library A in your Angular app components
5. do run 'nx serve demo-app'

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.14.0
   OS   : darwin arm64
   npm  : 9.3.1
   
   nx : 14.1.9
   @nrwl/angular : 14.1.9
   @nrwl/cypress : 14.1.9
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.9
   @nrwl/eslint-plugin-nx : 14.1.9
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.9
   @nrwl/js : Not Found
   @nrwl/linter : 14.1.9
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.9
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.9
   typescript : 4.6.4
```

### Failure Logs

```shell
Error: libs/emerald-button/src/lib/emerald-button.module.ts:7:13 - error NG3004: Unable to import class CommonModule.
  The symbol is not exported from /Users/SKumar51/Documents/Emerald/Library/emerald-mono-ngmaterial/node_modules/@angular/common/common.d.ts (module '@angular/common').

7   imports: [CommonModule,
              ~~~~~~~~~~~~

  libs/emerald-button/node_modules/@angular/common/common.d.ts:118:1
    118 export declare class CommonModule {
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    119     static ɵfac: i0.ɵɵFactoryDeclaration<CommonModule, never>;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ... 
    121     static ɵinj: i0.ɵɵInjectorDeclaration<CommonModule>;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    122 }
        ~
    The class is declared here.


Error: libs/emerald-button/src/lib/emerald-button.module.ts:14:14 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

Is it missing an @NgModule annotation?

14 export class EmeraldButtonModule {}
                ~~~~~~~~~~~~~~~~~~~




✖ Failed to compile.
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

I couldn't reproduce the issue with the information and steps provided. Could you please share a minimal repo where the issue can be reproduced?
