### ISSUE TITLE
Affected runs target while inputs did not change

### ISSUE THREAD

**Issue by boschni** [nrwl/nx#16478]
### Current Behavior

The documentation states the following:
```
"test": {
  "inputs": [ "default", "^production" ]
}
```
_"The configuration above means that the test target depends on all source files of a given project and only prod sources (non-test sources) of its dependencies. In other words, it treats test sources as private."_

See https://nx.dev/reference/project-configuration#using-^

Given this I would assume it would be possible to remove `^production` to indicate that the target is only dependent on its own source files.

Surprisingly, the `affected` command still runs the target even if its own source files did not change.

### Expected Behavior

If a target is configured to only depend on its own source files, I would expect `affected` not to run the target when its own source files did not change.

### Steps to Reproduce

1. Create `package-a`
```
{
  "name": "package-a",
  "scripts": {
    "build": "ng build",
    "lint": "ng lint"
  }
}
```
2. Create `package-b`
```
{
  "name": "package-b",
  "scripts": {
    "build": "ng build",
    "lint": "ng lint"
  },
  dependencies: {
    "package-a": "*"
  }
}
```
3. Create `nx.json`
```
{
  "extends": "nx/presets/npm.json",
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build", "lint"]
      }
    }
  },
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build"],
      "inputs": ["{projectRoot}/src/**/*"]
    },
    "lint": {
      "inputs": ["{projectRoot}/src/**/*"]
    }
  }
}
```
4. Change a file in `package-a`
5. Run affected command
```
nx affected --target=lint

    ✔  nx run package-a:lint (385ms)
    ✔  nx run package-b:lint (386ms)

Successfully ran target lint for 2 projects (393ms)
```
6. `package-b` is linted even though its own source files did not change.

### Nx Report

```shell
Node : 16.14.0
   OS   : darwin arm64
   npm  : 8.3.1
   
   nx (global)  : 15.9.2
   nx           : 15.9.2
   @nrwl/cli    : 15.9.2
   @nrwl/tao    : 15.9.2
```

**Comment by AgentEnder** [comment]
This is known + expected currently. 

- `inputs` + `outputs` can be thought of as configuration for the hasher, which `affected` is separate from.
- Affected operates at the project level, not the task level, so it can't vary based on the configuration of a target

You should see the target marked as affected, but the task be a cache hit. Its not a bad idea to make affected able to be target-dependant, but its not currently. We will likely work on this at some point, no ETA currently.

I'm going to close this out, as the work is being tracked by #15414

**Comment by boschni** [comment]
Thank you for your response. Hope to see this functionality some day🤞
