### ISSUE TITLE
create-nx-workspace ALWAYS shows "NX   NOTE  Nx CLI is not installed globally." - even though it is installed.

### ISSUE THREAD

**Issue by appsolutegeek** [nrwl/nx#1647]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

For the error message not to be shown as the nx CLI is installed globally

## Current Behavior

Creating a new project with 

```
npx create-nx-workspace@latest a-test-app
```

gives this

```
>  NX   NOTE  Nx CLI is not installed globally.

  This means that you might have to use "yarn nx" or "npm nx" to execute commands in the workspace.
  Run "yarn global add @nrwl/cli" or "npm install -g @nrwl/cli" to be able to execute command directly.

```

but as you can see it is installed and I have installed it many times

```
➜  typescript npm list -g --depth=0
/Users/ian/.nvm/versions/node/v10.14.2/lib
├── @angular/cli@8.0.3
├── @nestjs/cli@6.5.0
├── @nrwl/cli@8.4.0 .       <<<<<<<<<<  here
```

### Steps to Reproduce

```
npx create-nx-workspace@latest a-test-app
```

### Context

Please provide any relevant information about your setup:

- version of Nx 8.4

**Comment by appsolutegeek** [comment]
I can confirm that I have done this many times

```
npm install -g @nrwl/cli
```

but coming back to create a new app always displays the warning, saying that its not installed.

**Comment by mehrad-rafigh** [comment]
The output comes from https://github.com/nrwl/nx/blob/192a6a083d15a283726d59b0918e2ae8a7f53568/packages/create-nx-workspace/bin/create-nx-workspace.ts#L326

It checks whether the @nrwl/cli is installed, but it does not check it in the workspace it created. So it errors and the note is printed out. I opened a PR

**Comment by mehrad-rafigh** [comment]
Hey @vsavkin, I rebased my PR #1656. Would you please take a look at it?

**Comment by vsavkin** [comment]
@mehrad-rafigh Merged your PR. Thank you!
