### ISSUE TITLE
 Intellij with NX + Next + Tailwind Css

### ISSUE THREAD

**Issue by cyrsis** [nrwl/nx#16472]
### Current Behavior

Intellij Do not show  complete tailwind class 

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/731087/233716746-975458a9-c004-4c33-b23f-f51d8cc3f937.png">

### Expected Behavior

is there a config that make intellij show up all the tailwind css class?

<img width="656" alt="image" src="https://user-images.githubusercontent.com/731087/233717046-1ed39cad-d56e-4e44-89ec-96415617c2e4.png">

### Steps to Reproduce

1.
 generate @nrwl/next:page --project=site --name=about --style=css --no-interactive 

2. node node_modules/@nrwl/cli/bin/nx.js generate @nrwl/react:setup-tailwind --project=site --buildTarget=build 

### Nx Report

```shell
Node : 16.13.1
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/next              : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/nx-cloud          : 16.0.1
   typescript              : 4.9.5
```

**Comment by ndcunningham** [comment]
This does not seem like a Next.js issue, it seems to be more suited for a forum like StackOverflow
