### ISSUE TITLE
Serve task fails on latest Next.js version (13.3.1)

### ISSUE THREAD

**Issue by Jasonkoolman** [nrwl/nx#16479]
### Current Behavior

When upgrading Next.js to the latest version (13.3.1 at the time of writing), the `serve` task of `@nrwl/next:server` no longer works. It fails almost immediately with the following error:

> (0 , next_1.default) is not a function

I've managed to track down the issue: it breaks on [v13.3.1-canary.12](https://github.com/vercel/next.js/releases/tag/v13.3.1-canary.12). Not sure what the cause is, it might be related to [this PR](https://github.com/vercel/next.js/pull/48400).

Good to note is that the `build` task works just fine.

### Expected Behavior

`nx serve` commands works for Next.js applications

### GitHub Repo

https://github.com/Jasonkoolman/next-level

### Steps to Reproduce

1. Open `package.json` and bump Next.js to `13.3.1-canary.12`
2. Run `npm install`
3. Run `npm run dev`

### Nx Report

```shell
Node : 18.15.0
   OS   : win32 x64
   npm  : 8.5.3

   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/next              : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/tao               : 15.9.2
   typescript              : 4.9.5
```

**Comment by danyhiol** [comment]
I'm also having this same issue. The `build` work just fine, but not the `serve`.
Here is a trace:
```
 >  NX   (0 , next_1.default) is not a function


TypeError: (0 , next_1.default) is not a function
    at /.../node_modules/@nrwl/next/src/executors/server/lib/default-server.js:14:40
    at Generator.next (<anonymous>)
    at /.../node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/.../node_modules/tslib/tslib.js:163:16)
    at defaultServer (/.../node_modules/@nrwl/next/src/executors/server/lib/default-server.js:13:20)
    at runNextDevServer_1 (/.../node_modules/@nrwl/next/src/executors/server/server.impl.js:60:35)
    at runNextDevServer_1.next (<anonymous>)
    at resume (/.../node_modules/tslib/tslib.js:279:48)
    at /.../node_modules/tslib/tslib.js:278:125
```

**Comment by Brian-McBride** [comment]
Looking at the source code, it seems that their builder didn't compile correctly. 

This is what `node_modules/next/dist/server/next.js` ends with now:

```js
// Support commonjs `require('next')`
module.exports = createServer;
const _default = createServer;
```

Before it used to be:
```js
// Support commonjs `require('next')`
module.exports = createServer;
exports = module.exports;
var _default = createServer;
exports.default = _default;
```

So, you can either patch your own file in the Next JS file. 
Or it looks like you might be able to change the import in the Nx executor in `default-server.ts` to import `createServer` function directly. 

```ts
import * as express from 'express';
import * as path from 'path';
import { createServer } from 'next';
import { NextServerOptions, ProxyConfig } from '../../../utils/types';

/**
 * Adapted from https://github.com/zeit/next.js/blob/master/examples/with-custom-reverse-proxy/server.js
 * @param settings
 */
export async function defaultServer(
  settings: NextServerOptions,
  proxyConfig?: ProxyConfig
): Promise<void> {
  const app = createServer(settings);
  const handle = app.getRequestHandler();

  await app.prepare();

  const server: express.Express = express();
  server.disable('x-powered-by');

  // Set up the proxy.
  if (proxyConfig) {
    const proxyMiddleware =
      require('http-proxy-middleware').createProxyMiddleware;
    Object.keys(proxyConfig).forEach((context) => {
      server.use(proxyMiddleware(context, proxyConfig[context]));
    });
  }

  // Default catch-all handler to allow Next.js to handle all other routes
  server.all('*', (req, res) => handle(req, res));

  server.listen(settings.port, settings.hostname);
}
```

**Comment by michaelangrivera** [comment]
Have the same issue! This should be a hot fix; we shouldn't need to patch package, IMO.

**Comment by simonpeters** [comment]
yeah nx serve seems to broken since I updated as well. can't serve next project.

**Comment by olegshilov** [comment]
have same issue

**Comment by matsuby** [comment]
Next.js maintaier says this is not a bug🤔 
https://github.com/vercel/next.js/pull/48098#discussion_r1168298395

**Comment by jaysoo** [comment]
The problem is that Nx is compiled as CommonJS, and Next.js 13.3.1 no longer has `exports.default` defined in the entry file. This means that `import next from 'next'` no longer works since it assumes `exports.default` exists.

If we convert our `import` to `require`

**Comment by jaysoo** [comment]
We'll put a patch, and it'll be in Nx 16 as well.
