### ISSUE TITLE
Tailwind not working with 15.9.2 migrations versions

### ISSUE THREAD

**Issue by morbargig** [nrwl/nx#16485]
### Current Behavior

Tailwind not been generating in windows os (Linux fine).

### Expected Behavior

Tailwind should been generating in windows & linux os .

### GitHub Repo

https://github.com/morbargig/nx

### Steps to Reproduce

1. npx nx migrate latest
2. npx nx migrate --run-migrations

Tailwind not been generating in windows os (Linux fine).

### Nx Report

```shell
none
```

### Failure Logs

```shell
none
```

### Additional Information

sorry about the little info the project is private and it not allow to share any more Information than the one i gives.
the problem is very clear in version 15.9.2 tailwind stopes working i know that you are on the 16 releases but until we will get there it will be amazing if you fix it.
me and all my teams waiting for this bug-fix.

**Comment by AgentEnder** [comment]
We are going to need some form of error logs (preferably a stack trace) to be able to debug this. I appreciate having the reproduction repo, but we will also need to know what commands to run and the expected / observed outcomes are.
