### ISSUE TITLE
Add configuration environment via NestJS jest test

### ISSUE THREAD

**Issue by morbargig** [nrwl/nx#16486]
- [x] I'd be willing to help implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

npx nx run api:test:mock

the project.json will get the mock configuration and replace the environment file accordingly.
and than i can run the NestJS test with any configuration i want such as the server address or any other setup variable.

## Motivation

this future almost prevent us from implementing tests for the NestJS Api because we cano't test it with mock data or with changing environment like via serve
 
## Suggested Implementation

some project.json configuration that will allow npx nx run api:test:<configuration> with NestJS jest.

**Comment by AgentEnder** [comment]
Nx loads environment variables from several places. These files include:
```
- {projectRoot}/.env.[target-name].[configuration-name]
- {projectRoot}/.env.[target-name]
```

So, for a nest app located in `apps/my-nest-app`, you could load environment variables specifically for a test target by putting them in a .env file called:
```
- apps/my-nest-app/.env.test
```

If you run your jest tests against multiple environments, you can add configurations representing those environments to your target configuration, and add environment variables as:
```
- apps/my-nest-app/.env.test.mocks
- apps/my-nest-app/.env.test.stage
```

A full list of those is here: https://nx.dev/recipes/environment-variables/define-environment-variables#define-environment-variables

**Comment by morbargig** [comment]
> Nx loads environment variables from several places. These files include:
> 
> ```
> - {projectRoot}/.env.[target-name].[configuration-name]
> - {projectRoot}/.env.[target-name]
> ```
> 
> So, for a nest app located in `apps/my-nest-app`, you could load environment variables specifically for a test target by putting them in a .env file called:
> 
> ```
> - apps/my-nest-app/.env.test
> ```
> 
> If you run your jest tests against multiple environments, you can add configurations representing those environments to your target configuration, and add environment variables as:
> 
> ```
> - apps/my-nest-app/.env.test.mocks
> - apps/my-nest-app/.env.test.stage
> ```
> 
> A full list of those is here: https://nx.dev/recipes/environment-variables/define-environment-variables#define-environment-variables

But we are using environment like how we used it in angular
With file replacement do you have solution for it also?
