### ISSUE TITLE
nx format seems to be looking for 'main' branch

### ISSUE THREAD

**Issue by GaryB432** [nrwl/nx#16481]
### Current Behavior

`nx format` is showing the following error in the console

```
fatal: ambiguous argument 'main': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

### Expected Behavior

Files should be formatted per the `nx format` documentation without showing errors in console.

### Steps to Reproduce

These commands in a fresh directory will reproduce the message
```
npm init -y
echo node_modules > .gitignore
npm install prettier -D
git init --initial-branch master
git add .
git commit -m "initial commit"
npx nx@latest init
nx format
```

### Nx Report

```shell
Node : 18.7.0
OS   : win32 x64
npm  : 8.16.0

nx         : 15.9.2
@nrwl/cli  : 15.9.2
@nrwl/tao  : 15.9.2
```

### Failure Logs

```shell
fatal: ambiguous argument 'main': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

### Additional Information

I do see the default branch set properly in `nx.json` if I  understand the scope of that property in relation to `nx format`.

**Comment by GaryB432** [comment]
my `defaultBase` property in `nx.json` is set to `master`.  I mentioned that under Additional Information above but I called it "default branch".  In any event it is defaultBase: master.

**Comment by GaryB432** [comment]
```
{
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build"]
      }
    }
  },
  "defaultBase": "master"
}
```

**Comment by AgentEnder** [comment]
Default base should be under an `affected` key, like this:
```json
{
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build"]
      }
    }
  },
  "affected": {
    "defaultBase": "master"
  }
}
```

You can see that here: https://nx.dev/reference/nx-json

**Comment by iSuslov** [comment]
@AgentEnder this is how nx generates config file when you run `init`. Probably error in the template

**Comment by AgentEnder** [comment]
Thanks iSuslov - this is a bug in `nx init`, the behavior is correct for `create-nx-workspace`. I'm fixing it now.
