### ISSUE TITLE
Import path duplication in module when generating component using '@nrwl/angular:component' schematics

### ISSUE THREAD

**Issue by geraldcsoftware** [nrwl/nx#16493]
### Current Behavior

When generating a component using "@nrwl/angular:component" schematics, the import path in the module has a duplication of the component directory.

For example, generating a component using `nx g @nrwl/angular:component test` gives `import { TestComponent } from './test/test/test.component';` in the declaring module. Note the duplicate '/test' in the path, which makes the import path wrong.

### Expected Behavior

The import path should be generated correctly.

### GitHub Repo

https://github.com/geraldcsoftware/nx-examples

### Steps to Reproduce

1. Run `npx create-nx-workspace@latest --name myworkspace --preset angular-monorepo --appName myapp`
2. Execute `nx g @nrwl/angular:component test --project myapp`

The app module will have the import path 
import { TestComponent } from './test/test/test.component';
instead of
import { TestComponent } from './test/test.component';
![image](https://user-images.githubusercontent.com/16701085/233941020-5549c0f1-e2fa-462c-a5fe-7f51621814d1.png)

### Nx Report

```shell
Node : 18.16.0
   OS   : win32 x64
   npm  : 9.6.4
   
   nx (global)             : 15.9.2
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
```

### Additional Information

Using @schematics/angular, the generated import path is correct.

E.g. running `nx g @schematics/angular:component test` gives the import path 
import { TestComponent } from './test/test.component';

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This was already fixed in https://github.com/nrwl/nx/pull/16364 and the change should be released soon. Please keep an eye on the releases to get the fix.
