### ISSUE TITLE
nx serve not working

### ISSUE THREAD

**Issue by Mithun-codes** [nrwl/nx#16494]
## Current Behavior

Not able to run nx serve project-name

## Expected Behavior
It should run app

### Failure Logs / Images / Videos

![image](https://user-images.githubusercontent.com/65484460/233763745-1417f192-245e-46c2-8fa2-d3f4209fe739.png)

### Environment
Windows

- Nx Console version:
I have installed below dependencies

"@angular/animations": "^15.2.5",
    "@angular/cdk": "^15.2.5",
    "@angular/common": "^15.2.5",
    "@angular/compiler": "^15.2.5",
    "@angular/core": "^15.2.5",
    "@angular/forms": "^15.2.5",
    "@angular/material": "^15.2.5",
    "@angular/material-moment-adapter": "^15.2.5",
    "@angular/platform-browser": "^15.2.5",
    "@angular/platform-browser-dynamic": "^15.2.5",
    "@angular/router": "^15.2.5",
    "@nrwl/angular": "^15.9.2",
    "@nrwl/cli": "^15.9.2",
    "@nrwl/express": "^15.9.2",
    "@nrwl/nest": "^15.9.2",
    "@nrwl/next": "^15.9.2",
    "@nrwl/node": "^15.9.2",
    "@nrwl/nx": "^7.8.7",
    "@nrwl/rspack": "^15.9.0",
    "@nrwl/schematics": "^8.12.11",
    "@schematics/angular": "^15.2.4",

"@angular-devkit/build-angular": "^15.2.4",
    "@angular-devkit/core": "^15.2.4",
    "@angular-devkit/schematics": "^15.2.4",
    "@angular-eslint/eslint-plugin": "^15.2.1",
    "@angular-eslint/eslint-plugin-template": "^15.2.1",
    "@angular-eslint/schematics": "^15.2.1",
    "@angular-eslint/template-parser": "^15.2.1",
    "@angular/cli": "^15.2.4",
    "@angular/compiler-cli": "^15.2.5",
    "@angular/language-service": "^15.2.5",
    "@babel/preset-react": "^7.18.6",
    "@nrwl/cypress": "^15.9.2",
    "@nrwl/eslint-plugin-nx": "^15.9.2",
    "@nrwl/jest": "^15.9.2",
    "@nrwl/js": "^15.9.2",
    "@nrwl/linter": "^15.9.2",
    "@nrwl/nx-cloud": "^15.3.5",
    "@nrwl/nx-plugin": "^15.9.2",
    "@nrwl/react": "^15.9.2",
    "@nrwl/web": "15.9.2",
    "@nrwl/webpack": "^15.9.2",
    "@nrwl/workspace": "^15.9.2",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.10"

- VSCode version:
 vs code version : 1.77.1
I used noth vscode terminal as well as command prompt but face same issue

**Comment by AgentEnder** [comment]
Can you run `nx report` and paste the output here? The `project.json` file for the project you are trying to serve would be helpful as well.
