### ISSUE TITLE
"Creating files with a generator"  page is outdated.

### ISSUE THREAD

**Issue by MaurerKrisztian** [nrwl/nx#16500]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/recipes/generators/creating-files

### Additional context or description

It's possible that the documentation is not up to date. If I follow the documentation steps it leads to errors. The correct command to run the local generator is ["nx workspace-generator [name],"](https://nx.dev/packages/nx/documents/workspace-generator) not "nx generate my-generator mylib" if I put it to the "/tools/generators" directory without a plugin. Additionally, using the generator requires a schema.json which is not added in the example.

**Comment by AgentEnder** [comment]
Yeah, this page needs some updates - it looks like its half split between the workspace-generator and local plugin flows right now. This should resolve itself soon though. In Nx 16 we are removing workspace-generators and migrating folks to use a local plugin instead.

We are also overhauling our plugin docs a bit, see #16314

**Comment by AgentEnder** [comment]
@MaurerKrisztian I'm going to go ahead and close this out. That page doesn't explicitly mention workspace-generators anywhere, and the file tree could be valid if the workspace plugin was configured as part of the root project or just in the tools directory.

#16314 should also clean it up a bit.
