### ISSUE TITLE
Tutorial e2e test in Step 2 only working with --prod flag

### ISSUE THREAD

**Issue by Halt001** [nrwl/nx#1651]
## Expected Behavior
The e2e test in the tutorial should start up the page (and then fail the tests). See tutorial here: https://nx.dev/angular/tutorial/02-add-e2e-test

## Current Behavior
The e2e test fails to load the page in the `beforeEach(() => cy.visit('/'));` step. An exception is thrown and it looks like the Angular App component is not instantiated/loaded.

When running the e2e test with the production configuration it does work as expected.  `ng e2e todos-e2e --watch --prod` 

The build option '"optimization": true' (which is part of --prod) is what makes the difference.

## Failure Information (for bugs)
The exception output is:

```
Uncaught SyntaxError: Invalid or unexpected token

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application

Because this error occurred during a 'before each' hook we are skipping the remaining tests in the current suite: 'TodoApps'
```

### Steps to Reproduce

1. Follow tutorial step 1: https://nx.dev/angular/tutorial/01-create-application
2. Follow tutorial step 2: https://nx.dev/angular/tutorial/02-add-e2e-test
3. See it fail  when running: ng e2e todos-e2e --watch
4. See it succeed when running ng e2e todos-e2e --watch --prod

### Context
- version of Nx used. 
8.4.0
- version of Angular CLI used
8.1.1
- `angular.json` configuration
As  created by the tutorial

**Edit:**
After looking into the problem some more it seem to come from a problem in vendor.js, probably code coming from @angular/core. There seems to be a problem with unicode characters in a function name.

The offending line is: `const interpolatedValue = ��ɵinterpolation5(prefix, v0, i0, v1, i1, v2, i2, v3, i3, v4, suffix);`

The strange thing is that only in the Cypress browser window this is the case for this line. Opening another Chrome Window on the same server and looking at the same line reveals this: 
`const interpolatedValue = ɵɵinterpolation5(prefix, v0, i0, v1, i1, v2, i2, v3, i3, v4, suffix);` And also loads the page without problem.

To make matters even more confusing, I've tried a non Nx Angular project with Cypress of the same versions and then there is no problem.

**Edit2**:
Uninstalling Cypress 3.4.0 and installing Cypress 3.2.0 fixed the problem. Higher than that and it will not visit the page unless you use --prod. So it looks like a Cypress problem but it breaks the tutorial.

**Comment by vsavkin** [comment]
@Halt001 unfortunately I'm not able to repro it. 

Could you provide a github repo with a repro?

**Comment by Halt001** [comment]
While trying to create a repo I discovered that the problem is related to the path where the tutorial is installed. If I rename the path or project directory the problem goes away. Hence my repo is not going to help finding the problem.

I have a feeling that it is related to some cache that the angular compiler uses. Changing the build to 'optimized' also fixes the problem probably because it can't use the (same) cache.

I haven't yet been able to find how to clear a possible angular compiler cache or force ng e2e to use a clean full rebuild (if that is even possible).

So for me the mystery remains but I think it is not very likely to effect other people because it is related to my computer. So hence I close this but I hope somebody can still point me in the right direction to get this fixed.

**Comment by dubcdr** [comment]
I was able to recreate with a fresh workspace today using nest and angular going through the tutorial. Adding `--prod` flag did resolve issue. But so did changing cypress to `3.2.0`.

node v10.16.3

**Comment by Halt001** [comment]
It appeared to be a Cypress bug with Unicode characters. They are working on it: See https://github.com/cypress-io/cypress/issues/1746
