### ISSUE TITLE
Latest documentation says you can use nx run-many and filter by tags but functionality only works in beta version.

### ISSUE THREAD

**Issue by brandoncollins7** [nrwl/nx#16518]
### Current Behavior

I have wasted hours wondering why when I run my command nx run-many --projects=tags:knex is running 0 projects. Turns out this only works in the beta. This should be made more clear.

### Expected Behavior

Documentation should be reflective of the current release not the beta or otherwise clearly noted

### Steps to Reproduce

N/A

### Nx Report

```shell
N/A
```

**Comment by AgentEnder** [comment]
This is indeed an Nx 16 feature - the docs site reflects the current state of `master`, not necessarily the latest release. We try to label things appropriately where we can, but the documentation you are referencing is autogenerated from our `--help` output for run-many.
