### ISSUE TITLE
Major build issue with tsc webpack

### ISSUE THREAD

**Issue by An0nie** [nrwl/nx#16531]
### Current Behavior

Hello!

Recently we've found a major bug in our code that uses NestJS through Nx, I tracked it down to something build related.
It seems like it tries to optimize the code but does it incorrectly?

```ts
const str = 'str';

if (`${str}${str}` === `${str}str` && true) {
  console.log('hello');
}
```

When the project is built, this code turns into

```js
const str = 'str';
if (`${str}${str}` === `${str}str` && 0) {}
```

It seems to be related to template literals.
This is the simplest form I could shorten it to, but this happens when it's not just one variable.
Every condition in the if after the template literal comparison turns into 0 and the body of the if statement gets removed.

### Expected Behavior

When I tried the same in a NestJS project without Nx, it gave the correct code.

### GitHub Repo

https://github.com/An0nie/nx-build-issue

### Steps to Reproduce

1. Create an integrated Nx workspace targeting NestJS
2. Place the example code anywhere in the app
3. Run build and check the dist code

I've created a brand new monorepo and I could reproduce the issue.
https://github.com/An0nie/nx-build-issue/blob/main/apps/build-test/src/main.ts#L27
Turns into
https://github.com/An0nie/nx-build-issue/blob/main/dist/apps/build-test/main.js#L157

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.16.0
   OS   : win32 x64
   npm  : 9.5.1
   
   nx (global)             : 15.9.2
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/nest              : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/webpack           : 15.9.2
   @nrwl/nx-cloud          : 16.0.2
   typescript              : 4.9.5
```

### Additional Information

It is very possible that it's an upstream issue, but this bug happens with the default Nx settings and with build optimization turned off.

**Comment by ndcunningham** [comment]
Looks like there is an issue with `webpack` and `tsc`. As a workaround, you could use `swc` by manually updating your `project.json` and setting `'compiler': "swc"` and then install `@swc/core` and `swc-loader`

**Comment by An0nie** [comment]
Thank you!

**Comment by An0nie** [comment]
I've changed the compiler to swc, put together an swcrc, but it seems to generate the same buggy code.
It's probably more related to webpack than tsc.

**Comment by ndcunningham** [comment]
It shouldn't generate the same, my output with swc + webpack is 
```js
var str = "str";
if ("" + str + str === "" + str + "str" && true) {
    console.log("hello");
}
```

**Comment by ndcunningham** [comment]
Looking further into it, this doesn't seem like a Nx issue. There seems to be a problem with webpack and tsc where the `tsconfig` target is set to `es2015`+  Here is a sample repo without Nx that still fails: https://github.com/ndcunningham/webpack-tsc-no-nx

So the solutions or workarounds are:
- update tsconfig and set `"target": "ES5",` using `webpack` + `tsc`
- use `swc` as mentioned earlier in the post
