### ISSUE TITLE
NX MFE Host App: ERROR TypeError: type is undefined

### ISSUE THREAD

**Issue by sandeepcodework** [nrwl/nx#16535]
### Our team is running into this issue when we try to convert one of our angular apps to a host app with a module federation.  

We executed the **nx setup-mf command**, and updated the **shared package**s but we are facing this issue **(ERROR TypeError: type is undefined)**.  

**Our monorepo has a lot of libraries that need to be consumed into the host app while also allowing the development of microfront ends.**  We can't share a demo repo since we can only reproduce this on our code base.  Using the NX examples we can't reproduce it.

If we set up module federation using webpack config directly we can get the app to load properly.  We could like to know if this deviation is appropriate.  Basically, we directly add our webpack config to the webpack.config.js file and it works.

We would appreciate any advice regarding this problem.  We can share more information regarding our set up so please ask for anything that might be relevant.

**NX MFE has created/updated the following pages.**

**New**

1. module-federation.config.js
2. webpack.config.js
3. webpack.prod.config.js

**Update**

1. project.json
2. tsconfig.app.json
3. tsconfig.spec.json

### Code

**module-federation.config.js**
```
module.exports = {
  name: 'host',
  remotes: [],
  additionalShared: [
    '@angular/platform-browser',
    '@angular/platform-browser-dynamic',
    '@angular/forms',
    '@angular/core',
    '@angular/common',
    '@angular/router',
    '@ngrx/effects',
    '@ngrx/entity',
    '@ngrx/router-store',
    '@ngrx/store'
  ]
};
```

**Error**
![Screenshot 2023-04-19 at 6 09 59 PM](https://user-images.githubusercontent.com/5619364/234033170-6d5fc8b1-49be-4c45-9424-80c1725a72ae.png)

**Comment by Coly010** [comment]
You shouldn't need the `additionalShared` our `withModuleFederation` plugin should find all those packages correctly.

If you remove them does it work?

Also, if your own webpack config works, it should be good enough to just run with that.

**Comment by ktordoff13** [comment]
@Coly010 
We are using NX v14.8.6 and when we execute `npx nx generate @nrwl/angular:setup-mf host-app --mfType=host --federationType=dynamic --routing --no-interactive` and then run the `serve` command without modifying the `additionalShared` we get this error 

<img width="611" alt="image" src="https://user-images.githubusercontent.com/23196667/234590307-30e91beb-35cf-409e-a794-05dc350cbe80.png">

If using the webpack config directly is acceptable that can be a good solution for us.  If we bypass `withModuleFederation` what are we going to be missing out on?

**Comment by Coly010** [comment]
The `withModuleFederation` function does three things

1. creates the webpack config such that it can accept Module Federation Plugin
2. Traverses the workspace tree to find all the projects (libraries etc) that are used by the application and adds them to the shared config along with the npm packages they depend on
3. Sets up the ModuleFederationPlugin with the shared packages and the remote/host configuration

**Comment by ktordoff13** [comment]
@Coly010 Thanks for that summary. 

Do you have any insight to the error in the screenshot?

**Comment by Coly010** [comment]
It usually occurs when a shared package is required on load. 

Just to confirm, do you have a bootstrap.ts file that usually contains the application startup code?

```
platformBrowserDynamic().bootstrapModule(AppModule);
``` 

Then your main.ts should have:

```
import('./bootstrap);
```

**Comment by ktordoff13** [comment]
main.ts
```
import { setRemoteDefinitions } from '@nrwl/angular/mf';

fetch('/assets/module-federation.manifest.json')
  .then(res => res.json())
  .then(definitions => setRemoteDefinitions(definitions))
  .then(() => import('./bootstrap').catch(err => console.error(err)));
```

bootstrap.ts has
```
platformBrowserDynamic()
  .bootstrapModule(CoreModule)
  .catch(err => console.error(err));
 ```

**Comment by ktordoff13** [comment]
@Coly010 Just a reminder.  Please let me know your thoughts on my previous comment.

**Comment by Coly010** [comment]
Your host app appears to be set up correctly, which makes me believe there is some code running before the lazy-load of bootstrap.ts. 

It could be something that is injected by the angular builder. The best way to find that out is if you investigate the module that is being mentioned in the error.

**Comment by ktordoff13** [comment]
@Coly010 I think I've have some momentum regarding this. Is there a way to NOT share everything when using ` withModuleFederation`? 

Is there a way with NX to set up Angular as shell and react as a remote in the same repo using the Web Compoment approach described here? 
https://www.angulararchitects.io/aktuelles/multi-framework-and-version-micro-frontends-with-module-federation-your-4-steps-guide/

**Comment by Coly010** [comment]
@ktordoff13 Yes, you can add the following to your `module-federation.config.js`

```
shared: (libraryName, defaultConfig) => {
    // Returning false means the library is not shared.
    return false;
},
```

This may not be desirable for certain libraries, it will break singleton pattern in Angular for example. You can see here how to set it up to only share core libraries: https://nx.dev/more-concepts/micro-frontend-architecture#shared-libraries

We do not support mixing technologies with MFE: https://nx.dev/more-concepts/micro-frontend-architecture#summary
