### ISSUE TITLE
@nrwl/esbuild Is severely bugged

### ISSUE THREAD

**Issue by JakeAi** [nrwl/nx#16539]
### Current Behavior

nx g @nrwl/node:app
I named it `sdk-generator/sap`
`generatePackageJson` does not include dependencies.
Assets do not get copied on `build` or `serve`.
Output gets compiled to `dist/apps/sdk-generator/sap` AND `dist/apps/sdk-generator/sap/apps/sdk-generator/sap`

I manually switched back to `@nrwl/webpack:webpack`

### Expected Behavior

I expected it to behave like `@nrwl/webpack:webpack`

### Steps to Reproduce

1 .nx g @nrwl/node:app
2. I named it `sdk-generator/sap`
3. serve app

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 17.9.1
   OS   : win32 x64
   npm  : 8.11.0

   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/esbuild           : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/rollup            : 15.6.3
   @nrwl/tao               : 15.9.2
```

**Comment by PointSingularity** [comment]
@JakeAi check this for how to actually get a package.json that is filled in:
https://github.com/nrwl/nx/issues/15716#issuecomment-1476524017
