### ISSUE TITLE
Nx 15.9.2 cannot resolve dependency between libraries

### ISSUE THREAD

**Issue by B1Z1** [nrwl/nx#16532]
### Current Behavior

We want to migrate from 15.7.1 to 15.9.2, but for some reason, the new version of Nx cannot find a dependency between two connected libraries. 

![Screenshot 2023-04-25 at 09 47 55](https://user-images.githubusercontent.com/38375468/234209795-df1f4ee9-b81e-4b06-a5aa-de1037efafe0.png)
<img width="803" alt="Screenshot 2023-04-25 at 09 49 16" src="https://user-images.githubusercontent.com/38375468/234210070-d2970a8b-34d7-42be-ba78-4ed9b0efbef2.png">

When I try to add something to a file inside the library, Nx resolves the dependency between them:

<img width="842" alt="Screenshot 2023-04-25 at 09 51 12" src="https://user-images.githubusercontent.com/38375468/234210601-a88145eb-a9df-418b-80e2-812fede4b98f.png">

![Screenshot 2023-04-25 at 09 51 41](https://user-images.githubusercontent.com/38375468/234210701-6e05cfc9-b8be-4768-87cc-356ec7ea31b1.png)

If I remove this line of code and make a clear cache, after I will try to execute the dep-graph dependency, the dependency hides. 

Also because of this error, I cannot build libraries:

File 'library/path' is not under 'rootDir'

I used:

yarn nx migrate latest
yarn nx migrate --run-migrations

The whole migration was without problems. 

### Expected Behavior

Nx resolves dependencies correctly and build whole workspace without problems

### Steps to Reproduce

1. Migrate workspace with 400 libraries from 15.7.1 to 15.9.2

### Nx Report

```shell
Node : 16.16.0
   OS   : darwin arm64
   yarn : 1.22.4
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/nest              : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/storybook         : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   @nrwl/nx-cloud          : 16.0.2
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngneat/transloco        : 4.2.6
   @ngrx/effects            : 15.3.0
   @ngrx/entity             : 15.3.0
   @ngrx/store              : 15.3.0
   @ngrx/store-devtools     : 15.3.0
   @rx-angular/cdk          : 1.0.0
   @rx-angular/state        : 1.7.0
   @rx-angular/template     : 1.0.0
   @storybook/angular       : 6.5.15
   @testing-library/angular : 13.1.0
```

### Additional Information

I cannot provide you with repro steps, because our repository is private. If you'll need more information I can provide you. It looks like a problem with the newest version, because before we had good stable build

**Comment by wizardnet972** [comment]
I think it's related to https://github.com/nrwl/nx/issues/15113

**Comment by B1Z1** [comment]
@wizardnet972 oh, I see your ticket from February. Long term bug :DDD

**Comment by jaysoo** [comment]
@B1Z1 Can you check that your `nx.json` does not have this entry?

```"extends": "nx/presets/npm.json"```

Does running `nx reset` show the connection?

**Comment by HWouters** [comment]
nx reset fixed the issue for me

**Comment by B1Z1** [comment]
@jaysoo just updated nx to 16.0.1 and same problem. Yes, we don't have: `"extends": "nx/presets/npm.json"`

Also tried to execute nx reset, and got the same. Dependency between libraries doesn't visible

**Comment by B1Z1** [comment]
Hey, @jaysoo. Maybe I can share more information about the bug? It's blocking us from updating Angular to the newest version

**Comment by B1Z1** [comment]
Also want to mention. I just need to do a change inside my file and revert it and nx handles dependency. When CI tries to build an app It crashes in the same place as locally. Probably mechanism doesn't search for all libraries until I do a change inside a library. If I'll do sth inside files, that cannot build, because of dependency, it builds application without problem. When I clear the cache it crashes from the beginning

**Comment by B1Z1** [comment]
node_modules/.cache/nx/nxdeps.json - doesn't contain dependency between ngplant-l10n and ngplant-tools-permission

**Comment by B1Z1** [comment]
Currently I can close the issue. Can someone verify @jaysoo ?

**Comment by B1Z1** [comment]
The problem still exists. After updating to the newest version, everything was good until we removed import from one library. The problem looks like same, I have imported the library but dep-graph doesn't see dependency. If I'll move the library to another folder, the dep-graph shows the connection between libraries. If I'll create the same library with the same files, the connection isn't visible. If I'll build the imported library, it builds correctly with all files inside dist/libs folder. 

![image](https://github.com/nrwl/nx/assets/38375468/c8c555e4-311c-4fb4-89c0-a7543504cd28)
![image](https://github.com/nrwl/nx/assets/38375468/c6abace5-9f50-4191-8c47-a0414601689a)

I have done nx reset/nx clear-cache. Doesn't help, the only workaround is to move ngplant/util/persist/local-storage library to another destination. For example ngplant/util/local-storage

**Comment by B1Z1** [comment]
Of course, I cannot reproduce it on another repository. When I try to create the same structure it works perfectly. I compared all possible files to find differences between our repository and the newly created repository. Every project.json/nx.json/tscofnig.json are same as ours

**Comment by B1Z1** [comment]
Here's report:

 >  NX   Report complete - copy this into the issue template

   Node   : 16.16.0
   OS     : darwin arm64
   yarn   : 1.22.4
   Hasher : Native

   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/angular        : 16.2.2
   @nx/cypress        : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nx/nest           : 16.2.2
   @nx/node           : 16.2.2
   @nx/plugin         : 16.2.2
   @nx/storybook      : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/web            : 16.2.2
   @nx/webpack        : 16.2.2
   nx-cloud           : 16.0.5
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc       : 1.1.21
   @ngneat/transloco        : 4.2.6
   @ngrx/effects            : 15.1.0
   @ngrx/entity             : 15.1.0
   @ngrx/store              : 15.1.0
   @ngrx/store-devtools     : 15.1.0
   @rx-angular/cdk          : 15.0.0
   @rx-angular/state        : 15.0.0
   @rx-angular/template     : 15.2.0
   @storybook/angular       : 7.0.18
   @testing-library/angular : 13.1.0
   ---------------------------------------
   Local workspace plugins:
   	 @bp/workspace-generators

**Comment by B1Z1** [comment]
Finally, I found a problem, creating a repro repository and send you soon

**Comment by B1Z1** [comment]
Fixed....

![image](https://github.com/nrwl/nx/assets/38375468/f74a5d07-4d58-4664-a3de-d519fe41251a)
