### ISSUE TITLE
Wiki section on "How to set default options for a specific schematic?" is outdated for nx8

### ISSUE THREAD

**Issue by virtuoushub** [nrwl/nx#1653]
The following does not work for nx8.
```json
// angular.json
"schematics": {
  "@nrwl/schematics:component": {
    "styleext": "scss"
  }
},
```
Source: https://github.com/nrwl/nx/wiki/FAQ#how-to-set-default-options-for-a-specific-schematic

Adding a subsection for nx8 that looks like the below might help those coming to that wiki using nx8
```json
// angular.json(nx8)
"schematics": {
  "@nrwl/angular:component": {
    "styleext": "scss"
  }
},
```

relates to #158 #533 
See also: https://github.com/nrwl/nx/blob/ccd5854a981df28ba38f2013e3ebbb87057650b7/docs/angular/guides/nx7-to-nx8.md#schematics

**Comment by mehrad-rafigh** [comment]
Good catch @virtuoushub! I tried to update the wiki, but I can not push to master. Did not find any contribution guideline for the wiki sites. Asked @bcabanes, but I have that fixed that. See diff below

```diff
index 0f66572..3442d6b 100644
--- a/FAQ.md
+++ b/FAQ.md
@@ -30,7 +30,7 @@ Will update the `angular.json` of your project like this:
 ```javascript
 // angular.json
 "schematics": {
-  "@nrwl/schematics:component": {
+  "@nrwl/angular:component": {
     "styleext": "scss"
   }
 },
```

**Comment by FrozenPandaz** [comment]
Good catch! I just updated the guide. :tada:
