### ISSUE TITLE
Pre-Commit Hook Test

### ISSUE THREAD

**Issue by LukasMachetanz** [nrwl/nx#1655]
How would you run the unit tests of all affected tests in a pre-commit hook?

**Comment by mehrad-rafigh** [comment]
@LukasMachetanz if you are using `husky` you could add this to your `package.json`

```json
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS",
      "pre-commit": "npm run affected:test -- --base=origin/master --head=HEAD --uncommitted"
    }
  },
```

You can change your base to be the Branch you want to check against. Hope this helps

**Comment by bcabanes** [comment]
Hi @LukasMachetanz!
Yes Husky is a good way to implement a pre-commit hook!
See how to do it: https://github.com/typicode/husky.

Closing the issue.
