### ISSUE TITLE
Running nx run-many with pnpm fails on outdated cache entries

### ISSUE THREAD

**Issue by butterybread** [nrwl/nx#16573]
### Current Behavior

When running `nx run-many -t {script}` it runs all scripts, but fails on scripts that no longer exist.
These projects seem to exist in the cache. But in the repository they no longer exist.

```
ERR_PNPM_NO_IMPORTER_MANIFEST_FOUND  No package.json (or package.yaml, or package.json5) was found in "{path to sub package root that no longer exists}"
```

Running nx via lerna does not cause any problems. Running nx directly does have this issue.

### Expected Behavior

nx does not fail. nx just ignores or removes cache entries that no longer have an actual project in the repository.

### Steps to Reproduce

1. use pnpm
2. create a new package (within a monorepo)
3. Add a cacheable task to the package
4. execute the task from root with run-many
5. remove the package containing the task
4. execute the task from root with run-many
5. nx fails 

### Nx Report

```shell
Node : 18.12.1
OS   : darwin arm64
pnpm : 8.2.0

nx          : 15.9.2
@nrwl/cli   : 15.9.2
@nrwl/tao   : 15.9.2
typescript  : 5.0.4
```

### Failure Logs

```shell
ERR_PNPM_NO_IMPORTER_MANIFEST_FOUND  No package.json (or package.yaml, or package.json5) was found in "{path to sub package root that no longer exists}"
```

**Comment by butterybread** [comment]
This is resolved by running 'nx reset'. But when using nx via lerna, it just works. No need to reset the cache.

**Comment by AgentEnder** [comment]
This should be fixed in the v16 betas, can you confirm?

**Comment by butterybread** [comment]
I have not been able to replicatie the issue with 16.0.1. 👍
