### ISSUE TITLE
[Feature Request] Support for Azure Function Apps

### ISSUE THREAD

**Issue by cwmrowe** [nrwl/nx#1659]
I'd like to be able to serve, build and test Azure Function Apps with NX in the same way that you can builds apps for NestJS and ExpressJS.

Minimum requirements as I see it
- Works with [Azure Functions VS Code Plugin](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions)
- Serve application locally with [Azure Functions Core Tools](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local)
- Build application ready for deployment
-- Importing code from TypeScript NX Libraries
-- Minimizing bundle size to reduce cold starts
- Test using Jest
- NX affected etc should work as expected. 

Even if this is something that the NX team do not want to support themselves, some pointers on how it can be achieved would be greatly appreciated.

**Comment by cwmrowe** [comment]
For anyone else that stumbles upon this I have found this article really helpful https://blog.angular.io/introducing-cli-builders-d012d4489f1b

**Comment by mehrad-rafigh** [comment]
Shouldn't we try to include the serverless framework, so you can deploy your functions not only to Azure, but to AWS and GCP as well?

**Comment by ntziolis** [comment]
@cwmrowe Did you manage to get this up and running with nx or did you create your own custom cli builder via angular console? Any code or snippets to share?

**Comment by cwmrowe** [comment]
@ntziolis sorry we didn't proceed down this route in the end

**Comment by MitkoTschimev** [comment]
Hi, we are working on something like this. Maybe you can create an issue as a feature request there?
https://github.com/Dev-Thought/ng-deploy-it

**Comment by ntziolis** [comment]
Will do. does anyone know if there is a central space for community packages for nx? If not ill open an issue to create such a space.

**Comment by jaysoo** [comment]
@ntziolis and whoever is interested, the community plugins can be found on this page https://nx.dev/nx-plugins. And also if if you run `nx list`.

Going to close this one since we're not planning to add serverless support to the main repo for the time being. If there is anything in the main repo that will help support serverless please re-open a new issue. Cheers!
