### ISSUE TITLE
Undo optimistic updates

### ISSUE THREAD

**Issue by FallenRiteMonk** [nrwl/nx#166]
Is it possible to pass the original dispatched actions from the ```optimisticUpdate.run``` function to the ```optimiticUpdate.undoAction``` function?

The reason I'm asking is because I would like to use https://github.com/brechtbilliet/ngrx-undo for undoing an action upon failure.

**Comment by vsavkin** [comment]
Are you asking about the action that is passed into run or returned from run? Cause if `run` returns a successful action, undoAction won't be called. undoAction will be called only when `run` fails. The action passed into run is also passed into `undoAction` as the first argument.

**Comment by FallenRiteMonk** [comment]
I'm asking about the returned action from run!

Let me explain what I mean/need using a example:
1) My app dispatches an action UPDATE_COUNT
2) Action gets handled by optimisticUpdate which:
   * makes a http request to the backend to update the count
   * returns action COUNT_UPDATED
3) COUNT_UPDATED action gets handled by reducer to update state
4) Http request fails which leads to optimisticUpdate.undoAction is called

Now I have to, in order to have the state consistent with the backend, revert the COUNT_UPDATED action, which is why I would need the optimisticUpdate.run returned action in order to be able to use the above mentioned library.

**Comment by vsavkin** [comment]
Thank you for your reply.

The optimisticUpdate function is meant to be called once the local state has been updated, and is meant to return and action indicating that **the operation is completed on the backend**.

In your case `UPDATE_COUNT` can be handled by both the reducer and the effect. The reducer will update the state, and the effect will update it on the backend. 

Closing this issues.

**Comment by FallenRiteMonk** [comment]
Now I understand. Sorry for the problem, I'm pretty new to NgRx, and thank you for your help!
