### ISSUE TITLE
Nx commands stop working when using Yarn classic with nohoist

### ISSUE THREAD

**Issue by igilham** [nrwl/nx#16603]
### Current Behavior

The Nx tool does nothing anymore. It doesn't log anything or attempt to run any commands/scripts. Even `nx reset` doesn't do anything.

Running via npx (installed in workspace root package):

```shell
npx nx affected --target=build
# no output
```

Via Yarn (installed in workspace root package):

```shell
yarn nx affected --target=build
yarn run v1.22.19
$ /Users/ian/code/project-backend/node_modules/.bin/nx affected --target=build
✨  Done in 0.40s.
```

The same behaviour is observed when the script is written in the `package.json` as in: `"build": "nx affected --target=build"`

Installed globally by Yarn or NPM (only stopped working since I started using Yarn):

```shell
nx affected --target=build
# no output
```

I've confirmed that the Nx command is definitely being run by manually adding debug logging to the script.

### Expected Behavior

The Nx tool should log something and perform some actions based on its CLI arguments.

### GitHub Repo

[igilham/nx-yarn-nohoist-repro](https://github.com/igilham/nx-yarn-nohoist-repro)

### Steps to Reproduce

It's not clear if this is reproducible or not yet, but I will attempt to provide what information I can.

**package.json**

```json
"dependencies": {
  "@nrwl/nx-cloud": "^15.3.5",
  "lerna": "^6.6.1",
   "nx": "15.8.9",
},
"workspaces": {
  "packages": [ "REDACTED..." ],
  "nohoist": [ "*", "**" ]
}
```

Note that due to some legacy build scripts and terrible dependencies, I'm making heavy use of `resolutions` and `nohoist`.

**lerna.json**

```json
{
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "useNx": true,
  "command": {
    "init": {
      "exact": true
    }
  }
}
```

**nx.json**

```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "affected": {
    "defaultBase": "develop"
  },
  "cli": {
    "packageManager": "yarn"
  },
  "namedInputs": {
    "sharedGlobals": [
      "{workspaceRoot}/.node-version",
      "{workspaceRoot}/package.json",
      "{workspaceRoot}/tsconfig.json"
    ],
    "sharedLinter": ["{workspaceRoot}/.eslintrc.json", "sharedGlobals"],
    "packageConfigs": [
      "{projectRoot}/package.json",
      "{projectRoot}/tsconfig.json",
      "{projectRoot}/tsconfig-build.json",
      "{projectRoot}/jest.config.js",
      "{projectRoot}/jest.config.all.js",
      "{projectRoot}/jest.config.integration.js",
      "{projectRoot}/.mocharc.json"
    ],
    "packageLinter": [
      "{projectRoot}/.eslintrc.json",
      "{projectRoot}/.prettierrc.cjs",
      "{projectRoot}/.prettierrc.js",
      "{projectRoot}/.prettierignore",
      "sharedLinter"
    ],
    "default": [
      "{projectRoot}/src/**/*.ts",
      "{projectRoot}/src/**/*.tsx",
      "{projectRoot}/src/**/*.js",
      "{projectRoot}/src/**/*.jsx",
      "{projectRoot}/src/**/*.json",
      "sharedGlobals",
      "packageConfigs"
    ],
    "linter": ["default", "packageLinter"],
    "production": ["default"]
  },
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build"],
      "inputs": ["default", "^default"],
      "outputs": ["{projectRoot}/lib"]
    },
    "tsc-check": {
      "dependsOn": ["^build"],
      "inputs": ["default", "^default"]
    },
    "test": {
      "dependsOn": ["^build", "tsc-check"],
      "inputs": ["default", "^default"]
    },
    "test:int": {
      "dependsOn": ["^build", "tsc-check"],
      "inputs": ["default", "^default"]
    },
    "test:all": {
      "dependsOn": ["^build", "tsc-check"],
      "inputs": ["default", "^default"]
    },
    "test:cover": {
      "dependsOn": ["^build", "tsc-check"],
      "inputs": ["default", "^default"],
      "outputs": ["{projectRoot}/coverage"]
    },
    "lint": {
      "inputs": ["linter", "^linter"]
    },
    "lint:fix": {
      "inputs": ["linter", "^linter"]
    },
    "prettier": {
      "inputs": ["linter", "^linter"]
    },
    "prettier:check": {
      "inputs": ["linter", "^linter"]
    }
  },
  "tasksRunnerOptions": {
    "default": {
      "runner": "@nrwl/nx-cloud",
      "options": {
        "cacheableOperations": [
          "build",
          "tsc-check",
          "test",
          "test:cover",
          "lint",
          "lint:fix",
          "prettier",
          "prettier:check"
        ],
        "accessToken": "REDACTED"
      }
    }
  }
}

```

### Nx Report

```shell
Does not print anything due to the described issue.

Tested with Nx 15.8.9 and 15.9.2 with the same results.

I added some manual logging to debug the CLI as run via Yarn. You can see some of the data collected in the tool here:

nx start
getting compile cache
observable polyfill
resolved localNx /Users/ian/code/newsletter-backend/node_modules/nx/bin/nx.js
isLocalInstall: false
local version 15.9.2
global version 15.9.2
nx global hand-off
require local
require local done

Notably, it ends up in the bottom `else` statement as


else {
  console.log('require local');
  require(localNx);
  console.log('require local done');
}
```

### Failure Logs

```shell
Nothing is logged
```

### Additional Information

I'm migrating a small monorepo from NPM/Lerna/Nx (without workspaces) to Yarn with workspaces. Somewhere along the way, the Nx CLI stopped working. It doesn't produce any output and exits immediately. I guess my installation is messed up somehow but I'm having difficulty finding the cause.

It seems that when Nx is installed by Yarn either globally or in the monorepo root, it does not run any commands at all.

I can work around this issue for now by using the Lerna CLI to run the scripts but longer-term I'm hoping to drop the Lerna dependency when Nx can be relied upon enough to simply work.

I've tried removing all my local node_modules and running `yarn cache clean` then reinstalling but it hasn't helped.

**Comment by meeroslav** [comment]
Thank you @igilham for reporting this. Unfortunately, without a repo to look at its hard to say what might go wrong.

Can you try to remove your node_modules and reinstall them with `yarn --frozen-lockfile`?

If there was an error in the `nx` you would likely get something printed to your console. The fact that there is nothing being printed out, suggests that the command is not run at all.

**Comment by igilham** [comment]
Hi @meeroslav. I'm happy to spend a little time trying to reproduce this in a toy repo but there's no guarantee that'll work.

I've confirmed that the nx tool is being run by manually adding extra `console.log`s to debug which branches it's taking. I'm not familiar with the CLI's architecture but as far as I can tell it is intended to launch the locally installed instance and process the commands from there.

What I think I understand from the debugging is that it believes it is running globally when it is not - so it `require`s the local version, but since that file is already running, it is cached by the runtime and therefore a no-op.

Naïvely, it seems like this could be solved by calling a function in the `require`d module, but that would not address the root cause for why this is happening.

**Comment by igilham** [comment]
I've reproduced the issue here https://github.com/igilham/nx-yarn-nohoist-repro

**Comment by igilham** [comment]
I've found a quick and hacky fix as well. In the entry point of the Nx CLI:

```javascript
const isLocalInstall = localNx && resolveNx(null).includes(localNx.replace('/bin/nx.js', ''));
```

Something similar (but more robust) may be sufficient for yarn. I've not looked at the impact on other package managers.

**Comment by igilham** [comment]
It looks like there is another solution involving the `nohoist` configuration for Yarn.

The reason I'm using `nohoist: [ "**" ]` is that I have an inefficient Docker build that dumps a copy of the repo filesystem in a container and uses relative imports to wire up the applications. The top-level `**` appears to be overkill for this purpose. I can get nx to work if I change it to something like the following:

```json
"nohoist": [
    "@myowgname/**",
  ]
```

Then `yarn nx run-many --target=lint --all` works again. The same embedded in the `scripts` block also works.

```json
"scripts": {
    "lint": "nx run-many --target=lint --all"
}
```

**Comment by igilham** [comment]
I've moved on to Yarn 3.5.1 and no longer have this issue. This version does hoisting in a different way that seems to work without much config or messing around.

The issue remains for the old version and combination of settings used in the repro repo. Feel free to just consider this issue a "feature" of what happens when abusing Yarn's `nohoist` configuration.

**Comment by meeroslav** [comment]
Thank you @igilham for reporting the issue and the investigation. 

We have identified the cause of the issue and will try to resolve it soon
