### ISSUE TITLE
On the 15inch screen of the laptop, on many pages there are eaten words

### ISSUE THREAD

**Issue by WizardFromBlizzard** [nrwl/nx#16610]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

There are many pages with the same issue (ex. https://nx.dev/recipes/module-federation/faster-builds#distributed-computation-caching-with-nx-cloud)

In the picture below, please check out the right side of the text, some words are eaten
![image](https://user-images.githubusercontent.com/44235008/234898666-ef597083-241b-485a-9ad3-0eae1a68d503.png)

The width of the screen is ~1919px

Provide any additional details here as needed.

**Comment by isaacplmann** [comment]
This was fixed by #16592 yesterday
