### ISSUE TITLE
React Native - Can't configure storybook for a "library"

### ISSUE THREAD

**Issue by dylan-westbury** [nrwl/nx#16622]
### Current Behavior

Currently it appears not possible to add storybook configuration to a react native library generated by nx. Once generate storybook configuration command is run an incomplete set up occurs, including "undefined": "^7.0.0-rc.0", added to package.json

### Expected Behavior

Be able to add a storybook a configuration to a react native library generated by nx. 

### Steps to Reproduce

1. nx generate @nrwl/react-native:library design-system-app
2. nx generate @nrwl/react-native:storybook-configuration design-system-app

### Nx Report

```shell
Node : 18.15.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx (global)             : 15.9.2
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/detox             : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/react-native      : 15.9.2
   @nrwl/storybook         : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/vite              : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/nx-cloud          : 15.3.5
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @storybook/angular : 7.0.6
```

### Failure Logs

```shell
Unable to add storybook to design-system-app. It is not a Nx React Native / Expo project.
Updating import for packages/design-system-app/src/main.tsx
Unable to update import in packages/design-system-app/src/main.tsx for project packages/design-system-app.
Updating resolverMainFields for packages/design-system-app/metro.config.js
Unable to update packages/design-system-app/metro.config.js for project packages/design-system-app.
```

### Additional Information

Is there an alternate way that should be followed to create a storybook for a react native library of components that can be published as an npm package?

**Comment by xiongemi** [comment]
since storybook can only be view on mobile app, to view stories under a lib:
- run the storybook-configuration on app:
-  in the mobile app's project.json, target storybook, in searchDir, add path to lib, for example"
```
 "storybook": {
      "executor": "@nrwl/react-native:storybook",
      "options": {
        "searchDir": ["apps/mobile/src", "lib/ui/src"],
```
- run `npx nx storybook <your app>`

then you can view storybook for for your library.
