### ISSUE TITLE
Module parse failed: Unexpected token (24:7)

### ISSUE THREAD

**Issue by simonpeters** [nrwl/nx#16658]
### Current Behavior

when running nx serve or nx build on any project that relies on a nx lib package I get the same error.

```
Module parse failed: Unexpected token (24:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
``` 

### Expected Behavior

for the build or serve to work

### GitHub Repo

https://github.com/simonpeters/nx-bug-repo

### Steps to Reproduce

I have no idea what of my project is causing this issue so its hard to reproduce. I stripped down my own repo until I got the error with 2 projects and 1 component still in it.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.19.0
   OS   : darwin arm64
   npm  : 8.19.3
   
   nx (global)             : 15.9.2
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/next              : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/nx-cloud          : 16.0.2
   typescript              : 4.9.5
```

### Failure Logs

```shell
> nx run ronnie:serve:development

error - ../ui/src/icons/FacebookIcon.tsx
Module parse failed: Unexpected token (3:34)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { Icon, IconProps } from "@chakra-ui/react";
| 
> export const FacebookIcon = (props: IconProps) => (
|   <Icon viewBox='0 0 27 26' {...props}>
|     <path d="M26.475 13.0886C26.475 5.98911 20.7198 0.233873 13.6203 0.233873C6.52086 0.233873 0.765625 5.98911 0.765625 13.0886C0.765625 19.5047 5.4664 24.8228 11.6118 25.7871V16.8044H8.34789V13.0886H11.6118V10.2565C11.6118 7.03481 13.5309 5.25524 16.4672 5.25524C17.8736 5.25524 19.3447 5.50631 19.3447 5.50631V8.66977H17.7237C16.1269 8.66977 15.6289 9.66066 15.6289 10.6772V13.0886H19.194L18.6241 16.8044H15.6289V25.7871C21.7742 24.8228 26.475 19.5047 26.475 13.0886Z" fill="currentColor"/>

Import trace for requested module:
../ui/src/icons/FacebookIcon.tsx
../ui/src/icons/index.tsx
../ui/src/index.ts
[ ready ] on http://localhost:4200
```

### Additional Information

I'm creating a new issue because I was unable to re-open https://github.com/nrwl/nx/issues/16516 myself.

**Comment by simonpeters** [comment]
I'm also having this issue when I start a refresh nx repo and paste in my project files (excluding project.json, tsconfig.json,...) I get the error from the moment I try to import a component from the UI package. no clue whats going on, never had this issue before on any other nx project.

**Comment by ndcunningham** [comment]
Hi, thanks for reporting this.
It seems like `next.js` is not picking up that your lib is a part of your build

One thing you can do is add `transpilePackages` to your `next.config.js` 
```ts
const nextConfig = {
  nx: {
    // Set this to true if you would like to to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: false,
  },
  images: {
    domains: ['cdn.sanity.io'],
  },
  transpilePackages: ["ui"]
};

```

Which should work, I tried without using `withNx` and it failed running just `next build` 
I am not sure why this repo is generated as a package based which could be why you are having weird issues.
I would strongly recommend selecting:
- Integrated: For monorepo solutions
<img width="1091" alt="Screenshot 2023-05-01 at 1 18 54 PM" src="https://user-images.githubusercontent.com/338948/235514506-6b2c921e-4f61-4718-b5d6-fa936bb617f2.png">

- Standalone
<img width="1102" alt="Screenshot 2023-05-01 at 1 19 35 PM" src="https://user-images.githubusercontent.com/338948/235514603-5773e9b9-c1bb-49bf-83bb-1924ba9780e1.png">

Both would accurately describe what you are trying to accomplish.

**Comment by maximkoretskiy** [comment]
@simonpeters 
I had the same issue with `next@13.2.*` and it has gone after changing next version to `13.1.1`.

**Comment by jaysoo** [comment]
We'll patch this to workspace libs are transpiled. In the meantime, if you add an entry to `transpilePackages` to your next config it'll work.
