### ISSUE TITLE
npx create-nx-workspace setup ends with error with 16.x.x

### ISSUE THREAD

**Issue by hdhami** [nrwl/nx#16659]
### Current Behavior

I am getting below error while creating nx workspace with latest version 16.0.1 =>
NX   Failed to create a workspace

✔ Choose what to create                 · integrated
✔ What to create in the new workspace   · next
✔ Repository name                       · kkkm
✔ Application name                      · gfg
✔ Default stylesheet format             · styled-components

 >  NX   Command failed: npm install

   Pass --verbose to see the stacktrace.

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/js@16.0.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

### Expected Behavior

it should have created the workspace as requested

### Steps to Reproduce

1. run npx create-nx-workspace
2. select Standalone React app
3. select Next.js
4. provide Application name
5. select Do you want to use experimental app/ in this project as yes
6. Default stylesheet format as styled-components
7. Enable distributed caching to make your CI faster as No

### Nx Report

```shell
NX   Could not find Nx modules in this workspace.
```

**Comment by AgentEnder** [comment]
I double-checked, and nrwl/js has a 16.0.1 published.

The error mentioned it not being present.

There are a few things that could cause that, but you'll need to help narrow it down.

- You are using a custom registry and behind a firewall, but that registry isnt being respected, causing the request to fail

- You happened to attempt the command in the middle of our publish flow, and @nrwl/js@16.0.1 wasn't published yet, but create-nx-workspace@16.0.1 was

- Your network experienced some flakiness and caused the error.

The last 2 would likely be resolved if you retry the command. For the first or a similar class of errors I'd need some more information. 

Are you pointing to a custom registry? If so, are you using an env variable (NPM_CONFIG_REGISTRY), or an npmrc to point to it? (Where is the npmrc if you are using it)

Is this machine on a corporate network that's locked down, or is it happening on a personal network? Can anyone else repro it?

**Comment by hdhami** [comment]
thanks, It worked today when I retried first time since I had reported this issue.
