### ISSUE TITLE
CypressError: The 'task' event has not been registered in the setupNodeEvents method.

### ISSUE THREAD

**Issue by abf7d** [nrwl/nx#16664]
### Current Behavior

I am building an Angular Nx application and I wish to print out a message to the console to help me debug a cypress test. I am trying to use my fixture data and verify that the data is loading:

```
before(function () {
    cy.fixture('project.json').then(function (json) {
        data = json;
        cy.task('log', {message: 'This will be output to the terminal'})
    });
});
```
When I run ` nx component-test mylib` I get the following error: 
`CypressError: `cy.task('log')` failed with the following error:
The 'task' event has not been registered in the setupNodeEvents method. You must register it before using cy.task()
Fix this in your setupNodeEvents method here:
C:\Work\Master\myproj\libs\mylib\cypress.config.ts
https://on.cypress.io/api/task`

Here is what my full 
Because this error occurred during a `before all` hook we are skipping all of the remaining tests.

### Expected Behavior

I expect a message will print out to the console.

### GitHub Repo

https://github.com/abf7d/critical-pass/tree/cypress-tests

### Steps to Reproduce

1. Clone the project
2. Run `npm i` to install the dependencies
3. Run the tests with the command ` nx component-test charts`
4. In the console you will see the error for the ArroChartComponent:
```
Running:  arrow-chart/arrow-chart.component.cy.ts                                        (2 of 12)

  1) "before all" hook for "renders"
  0 passing (432ms)
  1 failing
  1) ArrowChartComponent
       "before all" hook for "renders":
     CypressError: `cy.task('log')` failed with the following error:
The 'task' event has not been registered in the setupNodeEvents method. You must register it before using cy.task()
Fix this in your setupNodeEvents method here:
C:\Work\Master\critical-pass\libs\charts\cypress.config.ts
https://on.cypress.io/api/task
Because this error occurred during a `before all` hook we are skipping all of the remaining tests.
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : win32 x64
   npm  : 8.1.2

   nx : 15.3.0
   @nrwl/angular : 15.3.0
   @nrwl/cypress : 15.3.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.0
   @nrwl/workspace : 15.3.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
The 'task' event has not been registered in the setupNodeEvents method. You must register it before using cy.task()
Fix this in your setupNodeEvents method here:
C:\Work\Master\critical-pass\libs\charts\cypress.config.ts
https://on.cypress.io/api/task
Because this error occurred during a `before all` hook we are skipping all of the remaining tests.
```

**Comment by barbados-clemens** [comment]
Thanks for the reproducible @abf7d. 

Looking the errors you're seeing and the reproducible, I noticed that the cypress.config.ts doesn't have the `setupNodeEvents` entry in the config file. This is coming from you calling `cy.task('log')` task but not setting it up. The `nxComponentTestingPreset` does not provide any default tasks which is why the error message is saying that they have to be setup to be used.

You can do it like so

```ts
// in the cypress.config.ts
import { defineConfig } from 'cypress';
import { nxComponentTestingPreset } from '@nrwl/angular/plugins/component-testing';

export default defineConfig({
    component: {
      ...nxComponentTestingPreset(__filename),
      setupNodeEvents(on,config) {
        on('task', {
          log(message) {
            console.log(message);
            return null;
           }
        }
    }
});
```

More info about tasks from the cypress docs:
https://docs.cypress.io/api/commands/task

I PR'd your project so you can see the setup.
