### ISSUE TITLE
Recipe for existing Angular project migration to integrated monorepo is not working

### ISSUE THREAD

**Issue by vilanelle** [nrwl/nx#16660]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/recipes/adopting-nx-angular/angular-integrated

### Additional context or description

The provided recipe for migrating an existing Angular project into integrated monorepo is not working:

`npx nx@latest init --integrated`

You previously (in March) listed the following command for migration and it was working fine:

`ng add @nrwl/angular@<version_number>`

Should the docs be updated or is this command no longer recommended? Is there an actual automated way to migrate Angular project?

**Comment by leosvelperez** [comment]
Thanks for reporting this!

The listed command `npx nx@latest init --integrated` is the way to migrate an Angular CLI workspace to an integrated Nx workspace. The previous way (`ng add @nrwl/angular@<version_number>`) is no longer recommended and while that generator is still available, it won't receive any updates or fixes and it might be removed soon.

You mentioned that `npx nx@latest init --integrated` is not working but don't provide any details about what issues you are facing. Could you provide details about the issue you're having? Detailed reproduction steps or even better, a repo where the issue can be reproduced will speed up troubleshooting it.

**Comment by vilanelle** [comment]
Thanks for the quick response, @leosvelperez and sorry about the lack of information in the original issue. Repro steps below:

1. On an existing Angular 14.2 project, run `npx nx@latest init --integrated`.
2. Result: `nx.json` file is generated: 
```
{
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": []
      }
    }
  }
}
```
3. Expected result (result of running `ng add @nrwl/angular@14`): 
- moves applications to `apps` folder
- updates global config files: `tsconfig.*.json`, eslint, karma, prettier etc. and adds config files for individual apps and libs
- generates `project.json` files for existing apps and libs based on `angular.json` file and references them in the updated `angular.json` file
- updates `package.json` to use nx
- adds `decorate-angular-cli.js`
- adds `nx.json` file:
```
{
  "affected": {
    "defaultBase": "main"
  },
  "implicitDependencies": {
    "package.json": {
      "dependencies": "*",
      "devDependencies": "*"
    },
    ".eslintrc.json": "*"
  },
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": [
          "build",
          "lint",
          "test",
          "e2e"
        ]
      }
    }
  },
  "targetDefaults": {
    "build": {
      "dependsOn": [
        "^build"
      ]
    },
    "lint": {
      "inputs": [
        "default",
        "{workspaceRoot}/.eslintrc.json"
      ]
    }
  },
  "cli": {
    "schematicCollections": [
      "@ngrx/schematics"
    ],
    "analytics": false
  },
  "generators": {
    "@schematics/angular:class": {
      "skipTests": true
    },
    "@schematics/angular:component": {
      "prefix": "cp",
      "style": "scss"
    },
    "@schematics/angular:directive": {
      "prefix": "cp"
    }
  },
  "defaultProject": "my-default-project"
}
```

**Comment by leosvelperez** [comment]
@vilanelle thanks for those details!

Unfortunately, I still can't reproduce it. I performed the following steps based on the details provided above:

- Created an Angular CLI 14.2.x workspace,
- Ran `npx --yes nx@latest init --integrated`

The result is a workspace with `apps` and `libs` folders. The initial Angular app was correctly moved to the `apps` folder and the `nx.json` file was populated as expected. Maybe the project you're migrating has a specific setup that causes an issue, but without a reproduction would be hard to guess what could be going on.

**Comment by vilanelle** [comment]
@leosvelperez Many thanks for checking that. Was misled by the fact that `@nrwl/angular` migration worked seamlessly for the project. 
Closing as apparently caused by the local setup.

**Comment by leosvelperez** [comment]
@vilanelle there could be a valid issue on the `nx init --integrated` logic, but if we can't reproduce it, it's hard to imagine what could be. If you later have more details that can help us to troubleshoot it, please feel free to reopen the issue.

**Comment by vilanelle** [comment]
Thanks for your support! I'll be in touch, if I'll have any updates on this.

**Comment by karanbedre** [comment]
Hi @leosvelperez i am facing the same issue with angular 14.2 cli project. when I run the nx init@14.6.0 --integrated cmd, it generates the nx.json file as mentioned by @vilanelle but it does not create any apps folder nor libs folder or anything which has to be generated after running the cmd

am I missing something here?
