### ISSUE TITLE
cypress component tests cannot be run in parallel

### ISSUE THREAD

**Issue by wiegell** [nrwl/nx#16690]
### Current Behavior

```
nx run-many -t component-test --skip-nx-cache
```
Fails with a tsconfig related error

It does however work if running sequential:
```
nx run-many -t component-test --skip-nx-cache --parallel=false
```

### Expected Behavior

Should not fail

### GitHub Repo

Minimal reproduction: https://github.com/wiegell/component-test

### Steps to Reproduce

1. Create new nx monorepo
2. add angular app
3. add two libs with the angular lib generator
4. add cypress component tests with the official nx package

### Nx Report

```shell
Report complete - copy this into the issue template

   Node   : 16.19.1
   OS     : darwin arm64
   yarn   : 1.22.19
   Hasher : Native

   nx (global)        : 16.0.1
   nx                 : 16.0.1
   @nx/js             : 16.0.1
   @nx/jest           : 16.0.1
   @nx/linter         : 16.0.1
   @nx/workspace      : 16.0.1
   @nx/angular        : 16.0.1
   @nx/cypress        : 16.0.1
   @nx/devkit         : 16.0.1
   @nx/eslint-plugin  : 16.0.1
   @nrwl/tao          : 16.0.1
   @nx/web            : 16.0.1
   @nx/webpack        : 16.0.1
   typescript         : 4.9.5
```

### Failure Logs

[pastebin terminal output](https://pastebin.com/HChYr2YG)

**Comment by Reizoukodesu** [comment]
I've got a similar issue, it seems that the port reservation fails if `npx nx run-many --target=component-test --skip-nx-cache` is ran in parallel.

Test Setup:
```
npx create-nx-workspace@latest angular-monorepo-test --preset=angular-monorepo
cd .\angular-monorepo-test\

npx nx g @nx/angular:library test-1 --directory=libs/test-1 --standalone
npx nx g @nx/angular:library test-2 --directory=libs/test-2 --standalone

npx nx g @nx/angular:cypress-component-configuration --project=test-1 --build-target=angular-monorepo-test:build
npx nx g @nx/angular:cypress-component-configuration --project=test-2 --build-target=angular-monorepo-test:build
```

`npx nx run-many --target=component-test --skip-nx-cache` fails, whereas `npx nx run-many --target=component-test --skip-nx-cache --parallel=1` works fine.

Output:
```
 >  NX   Running target component-test for 2 projects
    ×  nx run test-2:component-test

       DevTools listening on ws://127.0.0.1:59742/devtools/browser/3eedc8cd-4a94-4eef-9f7d-704f8b8f123b
       - Generating browser application bundles (phase: setup)...
Your configFile threw an error from: cypress.config.ts

We stopped running your tests because your config file crashed.

Error: listen EADDRINUSE: address already in use 127.0.0.1:8081
    at Server.setupListenHandle [as _listen2] (node:net:1751:16)
    at listenInCluster (node:net:1799:12)
    at doListen (node:net:1948:7)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)


    √  nx run test-1:component-test (11s)

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target component-test for 2 projects (11s)

    √    1/2 succeeded [0 read from cache]

    ×    1/2 targets failed, including the following:
         - nx run test-2:component-test
```

**Comment by zayehalo** [comment]
Also having this exact issue in our nx monorepo. Setting the `port` in `basCypressConfig` did not solve the problem.

**Comment by tar-aldev** [comment]
Any update on this?

**Comment by therk** [comment]
Any update on this issue?

**Comment by kralphs** [comment]
We are also having this problem

**Comment by Coly010** [comment]
Unfortunately, this is an issue with the design of Cypress Component Testing.

CCT requires a dev-server to "host" the component for Cypress to run the tests against it. 

Each project that uses CCT will therefore create a dev-server at the port defined in the `cypress.config.ts`, which cypress then also uses to connect to the dev-server when running the tests.

This value being the same in multiple cypress.config files means that conflicts will happen when they are run in parallel.

There may be some fix I could implement for this, but for now, the workaround provided by @tar-aldev is the best solution:

> The workaround I could find so far is putting hardcoded port right into cypress.config.ts of every project. 

If you wanted to improve it, rather than having a hardcoded port, you could create a function `findAvailablePort` which would return a port that is free to use. Race conditions still might occur when running in parallel, however.

**Comment by mcaverick** [comment]
We have centralized our component-testing configuration for our different libraries and have used the project name to uniquely create a port to allow parallel test runs.
