### ISSUE TITLE
nx migrate next - messed up PNG and xlsx files

### ISSUE THREAD

**Issue by nosaku** [nrwl/nx#16706]
### Current Behavior

I ran the below:

nx migrate next
npm install
npx nx migrate --run-migrations

Apart from changing files like project.json etc. it also modified many of my PNG and xlsx files and corrupted them. For example, I can't open the .PNG file any more. Same is the case with xlsx. All there were in "assets" folder of my angular app.

### Expected Behavior

PNG and xlsx files should not get modified

### Steps to Reproduce

1. nx migrate next
2. npm install
3. npx nx migrate --run-migrations

### Nx Report

```shell
Could not copy as I was behind corporate firewall.
```

**Comment by nosaku** [comment]
It happened at the below step:

Ran update-16-0-0-add-nx-packages from @nrwl/eslint-plugin-nx
  Replace @nrwl/eslint-plugin-nx with @nx/eslint-plugin

**Comment by jaysoo** [comment]
Is this one 16.0.2? It has been patched here https://github.com/nrwl/nx/blob/master/packages/devkit/src/utils/binary-extensions.ts#L253

**Comment by AgentEnder** [comment]
Like @jaysoo mentioned, running `nx migrate next` will hit the v16 RC. This has been fixed in 16.0.2, can you try with `nx migrate latest`?

**Comment by nosaku** [comment]
Sure I will try. Also noticed that it is hitting extensions with uppercase, like PNG, JPG etc. I am running on Windows and there are few files like this.

Sent from Yahoo Mail on Android 
 
  On Wed, May 3, 2023 at 2:46 AM, Craigory ***@***.***> wrote:   


Like @jaysoo mentioned, running nx migrate next will hit the v16 RC. This has been fixed in 16.0.2, can you try with nx migrate latest?

**Comment by nosaku** [comment]
Just ran "nx migrate latest" and xlsx files are not modified. This seems to be fixed. But I have some files with uppercase PNG and JPG extensions... these are modified. Can the code not check for extensions in a case insensitive manner?

**Comment by nosaku** [comment]
Can this change help?

`export function isBinaryPath(path: string): boolean {
  return binaryExtensions.has(extname(path).toLowerCase());
}`

**Comment by Cammisuli** [comment]
@nosaku Yea that seems to be the right way. Sorry about that 😅

I can make a PR to fix it, or you can if you're feel up to doing it. 🙂

**Comment by nosaku** [comment]
@Cammisuli Sure let me do it... my first little contribution to this awesome tool :-)

**Comment by nosaku** [comment]
Closed by PR #16727
