### ISSUE TITLE
Angular publishable library not recognizing JS publishable library as buildable

### ISSUE THREAD

**Issue by NachoVazquez** [nrwl/nx#16715]
### Current Behavior

When importing a new JS publishable library from a previous Angular Publishable library or their secondary entry points I'm getting the following error:

> error  Buildable libraries cannot import or export from non-buildable libraries  @nrwl/nx/enforce-module-boundaries

This is the structure of the code that it is failing:

![lumberjack-structure](https://user-images.githubusercontent.com/9338604/235896671-f3d20b60-2080-4418-8f00-83433bf6b344.png)

### Expected Behavior

I should be able to import buildable libraries inside other buildable libraries without having any issues.

### GitHub Repo

https://github.com/ngworker/lumberjack/tree/previous-variation

### Steps to Reproduce

1. Clone the repository
2. `yarn install`
3. `yarn ci`

### Nx Report

```shell
Node : 18.12.1
   OS   : darwin arm64
   yarn : 1.22.19

   nx : 15.3.0
   @nrwl/angular : 15.3.0
   @nrwl/cypress : 15.3.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.0
   @nrwl/workspace : 15.3.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @jscutlery/semver: 2.29.2
   	 ngx-deploy-npm: 4.3.10
```

### Additional Information

I also tried on the latest version of Nx, but that didn't work.

**Comment by Coly010** [comment]
The problem is because the eslint-plugin we have is only looking for a target of name `build` to determine if the project is buildable. Your `webworker` project has `build-package` as it's build target so it's not correctly determining that it's buildable.

**Comment by NachoVazquez** [comment]
> The problem is because the eslint-plugin we have is only looking for a target of name `build` to determine if the project is buildable. Your `webworker` project has `build-package` as it's build target so it's not correctly determining that it's buildable.

Thanks for the replay @Coly010 ! That makes sense! 

The problem now is that if I change its build I start having issues with "files not in rootDir" haha.

Any ideas about that?

**Comment by Coly010** [comment]
We're going to work on adding support for specifying the name of the build target, that way you can keep it as `build-package`. However, I would be interested in a new issue for `build` causing the new error!

**Comment by NachoVazquez** [comment]
Awesome, I'll create a couple more of issues for you then :). Thanks again!

**Comment by NachoVazquez** [comment]
Alright, this is the error I was mentioning https://github.com/nrwl/nx/issues/16733.

My other issue is unrelated so I won't mention it in this thread.

Thanks again!
