### ISSUE TITLE
defaultProject not accepting params

### ISSUE THREAD

**Issue by cotneit** [nrwl/nx#16723]
### Current Behavior

Unable to specify executor params when using `defaultProject`

`npx nx serve` works as expected, but `npx nx serve --port 4201` does not:
```shell
PS E:\dev\dissect\nx-default-project-issue> npx nx serve --port 4201

 >  NX   Cannot find project '4201'
```

### Expected Behavior

I expect `npx nx serve --port 4201` to have the same result as `npx nx serve <defaultProject> --port 4201`

### Steps to Reproduce

1. Init integrated nx monorepo with angular app: 
   - `npx create-nx-workspace@latest --name nx-default-project-issue --preset angular-monorepo --app-name ng-app`
2. Specify `"defaultProject": "ng-app"` in `nx.json`
3. Try running `npx nx serve --port 4201`, it fails while `npx nx serve` and `npx nx serve ng-app --port 4201` work just fine

### Nx Report

```shell
PS E:\dev\dissect\nx-default-project-issue> npx nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.12.1
   OS     : win32 x64
   npm    : 8.19.2
   Hasher : Native

   nx                 : 16.0.3
   @nx/js             : 16.0.3
   @nx/jest           : 16.0.3
   @nx/linter         : 16.0.3
   @nx/workspace      : 16.0.3
   @nx/angular        : 16.0.3
   @nx/cypress        : 16.0.3
   @nx/devkit         : 16.0.3
   @nx/eslint-plugin  : 16.0.3
   @nrwl/tao          : 16.0.3
   @nx/web            : 16.0.3
   @nx/webpack        : 16.0.3
   typescript         : 4.9.5
```

**Comment by xiongemi** [comment]
i think the command is `npx nx serve -- --port 4201`, then it would work with the default project.
