### ISSUE TITLE
Duplicate 'common' Chunks in Federated Angular Modules with NX Monorepo #16720

### ISSUE THREAD

**Issue by Barrier-Theo** [nrwl/nx#16721]
Hello everyone, 

# Context 

We have implemented Module Federation with Angular in a mono repository using NX. Our application consists of a shell (host application) and several remote applications (admin, planner, etc.). To avoid code duplication, we've created a shared library containing generic services, third-party packages, and UI components that can be used across the host and remote applications.

The architecture is structured as follows:

```
nx
  - apps
    - admin
    - planner
    - shell
  - libs
    - shared
      - auth
      - material
  - dist 
  - node_modules
```
Everything seems to be functioning as expected: remote applications can be opened within the shell, routing works correctly, and shared services are instantiated as singletons by sharing the dependencies and packages.

However, we encountered an issue when building and deploying the application locally. We discovered that a duplicate chunk called `common.e3cc36ae858c004c.js for (shell`), `common.44bca7a639887484.js (planner)`, `common.df902aabf28e01c7.js (admin)` ' are generated in dist folder, which includes and contains same code from shared services like  `auth`. This duplicated chunk appears in every remote application as well as the shell. When running the application and navigating to a remote application which using the shared library, each remote's 'common' chunk is loaded, but the code only references the 'common' chunk from the shell (host application) and never accesses the one from the remote application.

# Question 

This leads us to the following questions:

Why is the 'common' chunk created in the remote applications if the code from that chunk is never reach/used?
Is it possible to prevent the generation of these duplicate chunks in remote applications, or is this the intended behavior?

Thank you in advance for any help or guidance on this issue. We appreciate your time and expertise.
If you require any additional information, please do not hesitate to reach me.

Best regards.
![common_chunk_admin](https://user-images.githubusercontent.com/32095273/235916730-1254f0bf-bab7-4b00-88e6-ac6b8523b9e1.png)
![common_chunk_planner](https://user-images.githubusercontent.com/32095273/235916733-ef7f773a-a4cc-46e6-ba77-1f9100dc3b93.png)
![common_chunk_shell](https://user-images.githubusercontent.com/32095273/235916734-9a519e6c-87f1-45fb-b32d-d024eb2a0d8b.png)

_Originally posted by @Barrier-Theo in https://github.com/nrwl/nx/discussions/16720_

**Comment by Coly010** [comment]
It is intention.

Imagine a scenario where you generate a new host and do not wish to share certain packages with the remote. The remote still needs some way to access and reach that code. Therefore, it can do it from it's own common chunk.
