### ISSUE TITLE
Breaking up a single target:project script run with Distributed Task Execution (e.g. as an alternative to jest sharding)

### ISSUE THREAD

**Issue by jamesbhobbs** [nrwl/nx#16735]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
I want to be able to run one target for one project (e.g. jest for a big package) across N agents (e.g. with jest sharding).

I cannot see a documented way to do this, so the runtime minimum for DTE is the length of the longest single target:project script runtime combination.

## Motivation
TLDR: I have DTE setup on a branch and I'd like to replace a current jest sharding matrix I have in my default branch with it. However, the DTE setup seems to run each target for each project on one agent.

To be more specific, I have a couple of very large projects where if tests are run on a single agent then runtime would be >=30 mins. In my default branch we resolve this with jest sharding. But while attempting to implement DTE it seems as though there is no way to breakup our target for a single project, so it will always run for a very long time on one agent while the others remain idle (as the other things finish far earlier).

Am I missing a feature/some documentation for this or is this a feature request?

## Suggested Implementation

I either pass the shard to the DTE in the script, or have another way to split up the subset of the target:project script, which in my use case are jest tests.

## Alternate Implementations

This seems somewhat related to https://github.com/nrwl/nx/issues/15040 as being able to put the shard into run-many or affected might help.

**Comment by benjaminhobbs** [comment]
@StalkAltan thanks for the super quick reply. As you may see I've opened quite a few more feature requests, all of which I came up with while iterating and experimenting on the same codebase mentioned above. 

Only one is directly related, and that is [point 1 in this issue re documentation of DTE](https://github.com/nrwl/nx/issues/16949). I feel the content of the issue I am now commenting on ought to be addressed in the docs as it's a major consideration for potential users to consider.

For example, in my case, while I had a lot of fun with DTE and found many nice features the missing functionality mentioned here (and several of my other unrelated issues e.g. #16945, #16943, #16942) meant that despite substantial efforts there was no value in adopting DTE at this time.

**Comment by FrozenPandaz** [comment]
This is now possible for Cypress and Playwright.

We can look into using this for Jest as well.

**Comment by FrozenPandaz** [comment]
This is now available for jest: https://nx.dev/nx-api/jest#splitting-e2e-tests :tada:
