### ISSUE TITLE
 nx serve fails with out-of-memory exception

### ISSUE THREAD

**Issue by Markus-Ende** [nrwl/nx#16731]
### Current Behavior

JavaScript heap out of memory

### Expected Behavior

should serve happily like in the previous version :)

### Steps to Reproduce

unfortunately I can't create a repro repo and it happens in a closed source project

### Nx Report

```shell
Node   : 16.18.0
   OS     : linux x64
   npm    : 8.19.2
   Hasher : Native
   
   nx                 : 16.0.3
   @nx/js             : 16.0.3
   @nx/jest           : 16.0.3
   @nx/linter         : 16.0.3
   @nx/workspace      : 16.0.3
   @nx/angular        : 16.0.3
   @nx/cypress        : 16.0.3
   @nx/devkit         : 16.0.3
   @nx/eslint-plugin  : 16.0.3
   @nx/nest           : 16.0.3
   @nx/node           : 16.0.3
   @nx/plugin         : 16.0.3
   @nx/storybook      : 16.0.3
   @nrwl/tao          : 16.0.3
   @nx/webpack        : 16.0.3
   nx-cloud           : 16.0.5
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   @ionic/angular               : 6.7.4
   @nestjs/ng-universal         : 6.1.0
   @ngrx/component-store        : 15.3.0
   @ngrx/effects                : 15.3.0
   @ngrx/entity                 : 15.3.0
   @ngrx/router-store           : 15.3.0
   @ngrx/store                  : 15.3.0
   @mands/nx-playwright         : 0.4.0
   @ngrx/schematics             : 15.3.0
   @ngrx/store-devtools         : 15.3.0
   @nguniversal/builders        : 15.1.0
   @nxext/capacitor             : 15.7.0
   @nxext/ionic-angular         : 15.7.0
   @storybook/angular           : 7.0.7
   @testing-library/angular     : 13.4.0
   @trumbitta/nx-plugin-openapi : 1.12.1
   ---------------------------------------
   Local workspace plugins:
         @qupaya/workspace-plugin
```

### Failure Logs

![image](https://user-images.githubusercontent.com/19502754/235961803-c6ecba86-ef53-4541-b6c2-665909945576.png)

### Additional Information

* tried with 16.0.1 and 16.0.3
* runs inside Docker
* tried with both native and NX_NON_NATIVE_HASHER hasher

**Comment by pumano** [comment]
got that problems too, and memory footprint about 7+ gb when use angular 16 instead of 15 (4-4.7gb for my project). Can't wait properly working `browser-esbuild`

**Comment by Markus-Ende** [comment]
update: did the full delete node_modules and cache, refresh package-lock cycle. It seems to work now (with NX_NON_NATIVE_HASHER still set). I'll keep it open for now, and try a bit longer, but the memory crash did not occur again (still 16.0.3).
