### ISSUE TITLE
Issues aren't being answered let alone being resolved

### ISSUE THREAD

**Issue by 72gm** [nrwl/nx#16757]
### Current Behavior

Issues aren't being resolved

### Expected Behavior

Issues are resolved in a timely manner

### Steps to Reproduce

Raise an issue and watch nobody deal with it

### Nx Report

```shell
Not very good report
```

### Additional Information

It would be good if a statement could be provided as the level of support has dropped of a cliff (for whatever reason) and is becoming a factor in dropping NX as a product even though they seem to be well funded

**Comment by Coly010** [comment]
Closing this due to: https://github.com/nrwl/nx/issues/16366#issuecomment-1534537039
