### ISSUE TITLE
nx migrate next giving error @nestjs/common

### ISSUE THREAD

**Issue by nosaku** [nrwl/nx#16752]
### Current Behavior

 >  NX   The migrate command failed.

 >  NX   Command failed: npm install @nestjs/common@^9.1.0

   npm ERR! code ETARGET
   npm ERR! notarget No matching version found for @nestjs/common@9.1.0.
   npm ERR! notarget In most cases you or one of your dependencies are requesting
   npm ERR! notarget a package version that doesn't exist.

   npm ERR! A complete log of this run can be found in:
   npm ERR!    xxxx-debug-0.log

   Run migrate with --to="package1@version1,package2@version2"
   Pass --verbose to see the stacktrace.

### Expected Behavior

migration should be successful

### Steps to Reproduce

1. nx migrate next

### Nx Report

```shell
NA
```

**Comment by jaysoo** [comment]
@nosaku Thanks for reporting the issue. Can you run your migration using `latest` rather than `next`? We're testing a RC with Angular 16 upgrade, so things are still being patched.

**Comment by nosaku** [comment]
I have another issue which I opened and fixed too,  #16706 hence was testing with "next".

**Comment by jaysoo** [comment]
Okay thanks. This is fixed here https://github.com/nrwl/nx/pull/16771
