### ISSUE TITLE
v8.4.13 dependencies outdated

### ISSUE THREAD

**Issue by matheo** [nrwl/nx#1676]
## Expected Behavior

The latest `@nrwl/*` versions using the latest `@angular-devkit/*` and `@angular/compiler*` versions.

## Current Behavior

`@nrwl/*` libraries are still relying on `@angular-devkit/*` `0.801.1` and `8.1.1` is 22 days old and `8.1.3` is out and should not have breaking-changes right? `8.2.0` was released just before `8.4.2`.

### Context

- Nx 8.4.2
- Angular 8.2.0
- CLI 8.2.0
- Angular devkit 0.802.0

**Comment by alfaproject** [comment]
Is there a reason for them not to be peer dependencies? I keep having duplicates in my node modules <.<

**Comment by vsavkin** [comment]
@matheo does it cause any issues?

**Comment by matheo** [comment]
@vsavkin it just duplicates dependencies and keeps "outdated" versions in our projects, not a big deal but I wonder if you guys have a policy about fixing those versions instead using the latest patch like `~0.801.1` which later in that month will be able to use the `0.801.3` release.

**Comment by vsavkin** [comment]
@matheo the devkit wasn't very stable at one point, so Nx got broken by the latest patch. That's the main reason why the dependencies are set up the way they are. The devkit is more stable now though. So we can reconsider.

We aren't planning to make them peer deps because it will introduce unnecessary coupling.

**Comment by matheo** [comment]
@vsavkin as the time goes on, we're getting more warnings whle updating:
```
warning "@nrwl/node > @nrwl/linter > @angular/compiler-cli@8.1.2" has incorrect peer dependency "typescript@>=3.4 <3.5".
warning "@nrwl/node > @nrwl/linter > @angular-devkit/build-angular@0.801.1" has incorrect peer dependency "typescript@>=3.1 < 3.5".
warning "@nrwl/node > @nrwl/linter > @angular-devkit/build-angular > @ngtools/webpack@8.1.1" has incorrect peer dependency "typescript@>=3.4 < 3.5".
```

**Comment by mehrad-rafigh** [comment]
@matheo There is a PR https://github.com/nrwl/nx/pull/1757 coming. Soon I hope :)

**Comment by matheo** [comment]
Thanks for the info @mehrad-rafigh!

**Comment by vsavkin** [comment]
Closing this issue. The deps have been updated.
