### ISSUE TITLE
run-many filter by tags is wrong in documentation

### ISSUE THREAD

**Issue by dstoyanoff** [nrwl/nx#16760]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/packages/nx/documents/run-many#run-many

### Additional context or description

The example has a filter by tag that uses `--projects=tag:api-*` which doesn't seem to work. At the same type, there is a CLI flag `--tags`, which does work, but is not documented.

**Comment by AgentEnder** [comment]
What's `nx report` say for you?

The correct syntax is the `--projects=tag:{blah}`, mentioned in the docs, and I just double checked and there is no CLI flag called `--tags` for `run-many`

**Comment by AgentEnder** [comment]
Tags should be an array, not a string, so it's likely not being interpreted correctly

**Comment by dstoyanoff** [comment]
How do I express an array? Tested `--projects=tag:{lib}`, `--projects=tag:lib`, `--projects=tag:{lib,lib1}`, `--projects=tag:lib,lib1`. Even changed the tag to `lib-utils` and then ran with `--projects=tag:lib-*` like in the docs, but it errored with `no matches found`.

Thanks

**Comment by AgentEnder** [comment]
In the package.json file, not on the command ljne

**Comment by AgentEnder** [comment]
e.g.:
> package.json
```json
{
  "tags": ["my-tag"]
}
```
```shell
> nx run-many -p tag:my-tag
```

**Comment by dstoyanoff** [comment]
Oh, sorry, thank you. This seems to work

**Comment by ahernd2** [comment]
@AgentEnder How do we use the tags command with the affected command instead of run-many or is it not supported on the affected command?
