### ISSUE TITLE
Claim workspace links do not work

### ISSUE THREAD

**Issue by mvaljento** [nrwl/nx#16778]
The NX cli gives links to claim the workspace such as:

https://nx.app/orgs/workspace-setup?accessToken=...

These lead to an error page stating "500 - Internal Server Error! Sorry, an error occurred while we were loading this page."

**Comment by AgentEnder** [comment]
Can you provide `nx report` in your workspace? The link should point to `cloud.nx.app` rather than just `nx.app`.

**Comment by nixallover** [comment]
@mvaljento thanks for reporting this! It looks like we lost a redirect to the new application URL, which we're putting back in place. As a temporary workaround, you can change the origin to `https://cloud.nx.app/...` to connect your workspace. Apologies for the inconvenience.

**Comment by nixallover** [comment]
@mvaljento the redirect is back in place. Thanks again for bringing it to our attention!
