### ISSUE TITLE
nx migrate mess with binary files

### ISSUE THREAD

**Issue by vicb** [nrwl/nx#16781]
### Current Behavior

I migrated https://github.com/vicb/flyxc/tree/b9d8776bd341fe2ffd895d5a4688038574029987 from 15.9.2 to 16.0.3 running:

```
npx nx migrate latest
npx nx migrate --run-migrations
```

### Expected Behavior

The migration should only update text files and should not mess with binary files.

I had a few binary files that got corrupted by the migrations:

- `.pbf` files (protocol buffer files in binary format),
- `.glb` files (3D models).

### GitHub Repo

vicb/flyxc

### Steps to Reproduce

Check out the repo at the SHA given in the current behavior and run

```
npx nx migrate latest
npx nx migrate --run-migrations
```

### Nx Report

```shell
Node   : 18.16.0
   OS     : linux x64
   npm    : 9.5.1
   Hasher : Native
   
   nx                 : 16.0.3
   @nx/js             : 16.0.3
   @nx/jest           : 16.0.3
   @nx/linter         : 16.0.3
   @nx/workspace      : 16.0.3
   @nx/cypress        : 16.0.3
   @nx/devkit         : 16.0.3
   @nrwl/devkit       : 15.9.3
   @nx/eslint-plugin  : 16.0.3
   @nx/express        : 16.0.3
   @nx/node           : 16.0.3
   @nrwl/tao          : 16.0.3
   @nx/vite           : 16.0.3
   @nx/web            : 16.0.3
   @nx/webpack        : 16.0.3
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-container : 4.0.3
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/devkit@15.9.3
   
   To fix this, run `nx migrate nx@16.0.3`
```

### Failure Logs

```shell
n/a
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This seems to be related to https://github.com/nrwl/nx/issues/16706

However that issue is about testing file extensions which I don't think is a great test. It would be better to check if the files are text or binary files and only migrate text files.

Something like https://www.npmjs.com/package/isbinaryfile could probably help here

**Comment by vicb** [comment]
@AgentEnder could you please consider re-opening this and do not filter on extension but on actual file content as described in the "Additional Information" above?

**Comment by AgentEnder** [comment]
I think for now we want to continue forward with the extension based filter, since it should be faster perf wise and this is applied to every file in your repo. 

If we continue seeing these pop up we can reevaluate

**Comment by vicb** [comment]
I think perf do not matter that much for migrations as it should not be very frequent.

And also you can be smart and have a whitelist for text file extensions to skip checking those.
