### ISSUE TITLE
Global install Error: The current directory isn't part of an Nx workspace 

### ISSUE THREAD

**Issue by pomomayu** [nrwl/nx#16791]
### Current Behavior

After globally installing NX it is not possible to create workspaces.

`npm install --global nx@latest`

`npm list --global nx`

    `-- nx@16.1.0`
      `-- @nrwl/tao@16.1.0`
        `-- nx@16.1.0 deduped`

`nx create-nx-workspace@latest`

  Error:
    `The current directory isn't part of an Nx workspace.`

The version flag does not work either:
`nx --version`
  `The current directory isn't part of an Nx workspace `

Tried all the steps in the [NX docs]( https://nx.dev/more-concepts/global-nx)
 
Same error is stated in  [Issue #12439](https://github.com/nrwl/nx/issues/12439) but it appears to be a mixture of issues without any definitive problems or solutions.

### Expected Behavior

Ability to create workspaces with a global installation, without prefixing `npx` to the commands.

### Steps to Reproduce

1. Install NX via Power Shell
2. Open VS code
3. Create workspace in VS code terminal

### Nx Report

```shell
`nx report`
`The current directory isn't part of an Nx workspace.`
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Environment:
  Windows 10
  Nodejs v18.16.0
  VS code v1.78.0

Attempted to install NX with and without an administrative shell.

**Comment by AgentEnder** [comment]
Your command is incorrect, create-nx-workspace isn't a subcommand of the main nx package but rather a separate package. You should use `npx create-nx-workspace`
