### ISSUE TITLE
jest-preset-angular giving error after migration to latest

### ISSUE THREAD

**Issue by nosaku** [nrwl/nx#16794]
### Current Behavior

npm ERR! Found: @angular-devkit/build-angular@16.0.0
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"16.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular-devkit/build-angular@">=13.0.0 <16.0.0" from jest-preset-angular@13.0.1
npm ERR! node_modules/jest-preset-angular
npm ERR!   dev jest-preset-angular@"13.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### Expected Behavior

npm install should install all dependencies correctly

### Steps to Reproduce

1. nx migrate latest
2. npm install

### Nx Report

```shell
NA
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

The `jest-preset-angular` package must update its peer dependencies range and extend it to include Angular 16. There's an issue on their repo to do this but it hasn't been done yet https://github.com/thymikee/jest-preset-angular/issues/2058. From what we've tested, it works correctly with Angular v16.

As a workaround until they update the package, please install your dependencies with `--legacy-peer-deps`.

**Comment by PieterjanDeClippel** [comment]
Waiting for the following PR:

https://github.com/thymikee/jest-preset-angular/pull/2061

**Comment by PieterjanDeClippel** [comment]
A compatible version of `jest-preset-angular` has just been released
