### ISSUE TITLE
@nx/storybook angular compodoc configuration not showing docs tab in storybook

### ISSUE THREAD

**Issue by jerryorta-dev** [nrwl/nx#16807]
### Current Behavior

In a new repo using the following documentation:
- [@nx/storybook](https://nx.dev/packages/storybook#nxstorybook)
- [Set up Compodoc for Storybook on Nx](https://nx.dev/packages/storybook/documents/angular-storybook-compodoc)

The "Docs" and "Canvas" tabs are not showing in storybook.

<img width="696" alt="storybook-current-behavior" src="https://user-images.githubusercontent.com/341155/236453302-b114ffa5-ee9a-474f-b0c3-fd2005907135.png">

### Expected Behavior

The "Canvas" and "Docs" tabs display Compodoc information.

![image](https://user-images.githubusercontent.com/341155/236453669-e2477e21-fb06-4be1-842f-ed1ba3d149fc.png)

### GitHub Repo

https://github.com/jerryorta-dev/nx-storybook-compodoc-example/tree/main/apps/storybook/storybook-app/.storybook

### Steps to Reproduce

1. Create a new nx angular workspace: 
`npx create-nx-workspace@latest --preset=angular-monorepo --name=airlines --appName=booking --style=scss --nxCloud=false --packageManager=yarn  --routing=true --standaloneApi=true
`
2. Add dependencies: 
    ```
    yarn add -D @nx/storybook
    yarn add -D @storybook/angular
    yarn add -D @compodoc/compodoc
    ```
3. Create an app to compile and run storybook for entire repo. [See configurations here](https://github.com/jerryorta-dev/nx-storybook-compodoc-example/tree/main/apps/storybook/storybook-app/.storybook)
4. Configure per instructions:
   - https://nx.dev/packages/storybook#nxstorybook
   - Compodoc with angular - https://nx.dev/packages/storybook/documents/angular-storybook-compodoc
5. Run storybook:
   ```npm run storybook```

### Nx Report

```shell
Node   : 16.18.0
   OS     : darwin x64
   yarn   : 1.22.19
   Hasher : Native
   
   nx                 : 16.1.0
   @nx/js             : 16.1.0
   @nx/jest           : 16.1.0
   @nx/linter         : 16.1.0
   @nx/workspace      : 16.1.0
   @nx/angular        : 16.1.0
   @nx/cypress        : 16.1.0
   @nx/devkit         : 16.1.0
   @nx/eslint-plugin  : 16.1.0
   @nx/plugin         : 16.1.0
   @nx/storybook      : 16.1.0
   @nrwl/tao          : 16.1.0
   @nx/web            : 16.1.0
   @nx/webpack        : 16.1.0
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc    : 1.1.19
   @ngpat/schematics     : 16.0.1
   @ngrx/component       : 15.4.0
   @ngrx/component-store : 15.4.0
   @ngrx/effects         : 15.4.0
   @ngrx/entity          : 15.4.0
   @ngrx/schematics      : 15.4.0
   @ngrx/store           : 15.4.0
   @ngrx/store-devtools  : 15.4.0
   @storybook/angular    : 7.0.8
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by pumano** [comment]
when adding docs to config, it appears but from left sidebar

`main.js`

```js

...
 docs: {
    autodocs: true,
    defaultName: 'Docs', // set to change the name of generated docs entries
  },
...
```

**Comment by jerryorta-dev** [comment]
@pumano , thank you this worked. See Below.
<img width="710" alt="Screenshot 2023-05-05 at 8 22 57 PM" src="https://user-images.githubusercontent.com/341155/236590724-97575396-2cb8-455c-a8a9-209de34ff642.png">

> Looks like it should be added via migration by default.

Also in a fresh repo not migrated using nx 16.1.1, the schematics `@nx/angular:storybook-configeration` and `@nx/storybook:configuration` do not add that configuration.

**Comment by jerryorta-dev** [comment]
Here is the [main.ts](https://github.com/jerryorta-dev/nx-storybook-compodoc-example/blob/main/apps/storybook/storybook-app/.storybook/main.ts) that works from @pumano's fix:

```typescript
import type { StorybookConfig } from '@storybook/angular';

const config: StorybookConfig = {
  stories: [
    '../../../../apps/**/*.stories.@(js|jsx|ts|tsx|mdx)',
    '../../../../libs/**/*.stories.@(js|jsx|ts|tsx|mdx)',
  ],
  // stories: ['../src/app/**/*.stories.@(js|jsx|ts|tsx|mdx)'],
  addons: ['@storybook/addon-essentials'],
  framework: {
    name: '@storybook/angular',
    options: {},
  },
  docs: {
    autodocs: true,
    defaultName: 'Docs', // set to change the name of generated docs entries
  },
};

export default config;

// To customize your webpack configuration you can use the webpackFinal field.
// Check https://storybook.js.org/docs/react/builders/webpack#extending-storybooks-webpack-config
// and https://nx.dev/packages/storybook/documents/custom-builder-configs
```

**Comment by pumano** [comment]
Looks like migration add this, but fresh project - not. 
Note to @mandarini

**Comment by mandarini** [comment]
Hi there @pumano @jerryorta-dev thanks for writing here how one can make the docs tab appear!

The migration does indeed add the `docs` object in `main.ts`, and our generator does not. The reason why I did not add this to our generator was that we generate Storybook configuration with the minimum options for it to work, but then someone can go ahead and add their own configurations how they see fit.

If you think that we should by default enable docs in all new configurations, and it makes sense for everyone, I can add this to the generated code! What do you think?

**Comment by jerryorta-dev** [comment]
@mandarini thank you. imo the migration scripts are fine.  For me was a lack of awareness of what/where to find the storybook documentation to configure the compodoc feature. So maybe add info to the NX docs ( https://nx.dev/packages/storybook/documents/angular-storybook-compodoc ), either in the example code or a link to the storybook documentation ( https://storybook.js.org/docs/react/writing-docs/autodocs#page-top ) ?

Or for the generator, I add an option like `--addDocs=true`.  But the documentation alone is fine.

**Comment by mandarini** [comment]
@jerryorta-dev oh thanks for the quick feedback! I'll make sure to add the link of the original Storybook documentation on how to set up compodoc in our [compodoc guide](https://nx.dev/packages/storybook/documents/angular-storybook-compodoc)!

**Comment by mandarini** [comment]
@jerryorta-dev @pumano I updated both our [compodoc guide](https://nx.dev/packages/storybook/documents/angular-storybook-compodoc), and the example repository that's linked there!
