### ISSUE TITLE
findOriginalKeys is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by yharaskrik** [nrwl/nx#16825]
### Current Behavior

Generating a lockfile fails

App builds correctly just the lockfile fails to generate

### Expected Behavior

Should generate a lockfile correctly.

### Steps to Reproduce

Generate a nest app and try and use the generate package json flag to create a pruned lockfile.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin arm64
   yarn   : 1.22.17
   Hasher : Native
   
   nx                 : 16.1.0
   @nx/js             : 16.1.0
   @nx/jest           : 16.1.0
   @nx/linter         : 16.1.0
   @nx/workspace      : 16.1.0
   @nx/angular        : 16.1.0
   @nx/cypress        : 16.1.0
   @nx/devkit         : 16.1.0
   @nx/eslint-plugin  : 16.1.0
   @nx/express        : 16.1.0
   @nx/nest           : 16.1.0
   @nx/node           : 16.1.0
   @nx/plugin         : 16.1.0
   @nx/storybook      : 16.1.0
   @nrwl/tao          : 16.1.0
   @nx/webpack        : 16.1.0
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
```
```


### Failure Logs

```shell
>  NX   An error occured while creating pruned lockfile

   Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
   To prevent the build from breaking we are returning the root lock file.
   
Original error: findOriginalKeys is not a function or its return value is not iterable


   TypeError: findOriginalKeys is not a function or its return value is not iterable
    at /Users/jaybell/WebstormProjects/shinkansen/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:190:41
    at Array.forEach (<anonymous>)
    at mapSnapshots (/Users/jaybell/WebstormProjects/shinkansen/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:189:26)
    at stringifyYarnLockfile (/Users/jaybell/WebstormProjects/shinkansen/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:131:23)
    at createLockFile (/Users/jaybell/WebstormProjects/shinkansen/node_modules/nx/src/plugins/js/lock-file/lock-file.js:132:60)
    at /Users/jaybell/WebstormProjects/shinkansen/node_modules/@nx/webpack/src/plugins/generate-package-json-plugin.js:42:124
    at fn (/Users/jaybell/WebstormProjects/shinkansen/node_modules/@nx/webpack/node_modules/webpack/lib/Compilation.js:478:10)
    at _next0 (eval at create (/Users/jaybell/WebstormProjects/shinkansen/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (/Users/jaybell/WebstormProjects/shinkansen/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
    at eval (eval at create (/Users/jaybell/WebstormProjects/shinkansen/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
```
```


### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by meeroslav** [comment]
Thank you @yharaskrik for reporting this.

Can you provide a test repo where I can get this error. I tried generating workspace with nest locally, but I could not get the error (the version I used was 16.1.1 but afaik nothing in this patch could be influencing lock file parsing).

![Screenshot 2023-05-08 at 13 22 11](https://user-images.githubusercontent.com/881612/236811869-fb959900-7b0e-41c0-b53b-968e5bae6866.png)

**Comment by meeroslav** [comment]
Just to be sure I generated one repo with yarn as well. Same result:
![Screenshot 2023-05-08 at 13 28 00](https://user-images.githubusercontent.com/881612/236812698-d9848ff8-fde1-4dea-9cdb-5acec64f7ed1.png)

**Comment by yharaskrik** [comment]
Hmm ya the patch may have affected it I don't think I tried after updating to 16.1.1. will get back to you!

**Comment by yharaskrik** [comment]
Hmm ya still happening for me on 16.1.1, will see if I can create a repro.

**Comment by yharaskrik** [comment]
Haven't been able to repro it yet but I have some additional info. Reading the `findOriginalKeys` function the package that is failing `wrap-ansi` never hits this condition

```
// standard package
        if (snapshot.version === node.data.version) {
            return [keys, snapshot];
        }
```

There is no snapshot with the same version as the Node being checked (7.0.0)

**Comment by yharaskrik** [comment]
Miro I dm'd you out lockfile. Not sure if its helpful or not.

**Comment by meeroslav** [comment]
Thank you @yharaskrik, I found the issue thanks to your `lock-file`.

```yaml
"wrap-ansi-cjs@npm:wrap-ansi@^7.0.0", wrap-ansi@^7.0.0:
  version "7.0.0"
  resolved "https://registry.yarnpkg.com/wrap-ansi/-/wrap-ansi-7.0.0.tgz#67e145cff510a6a6984bdf1152911d69d2eb9e43"
  integrity sha512-YVGIj2kamLSTxw6NsZjoBxfSwsn0ycdesmc4p+Q21c5zPuZ1pl+NfxVdxPtdHvmNVOQ6XSYG4AUtyt/Fi7D16Q==
  dependencies:
    ansi-styles "^4.0.0"
    string-width "^4.1.0"
    strip-ansi "^6.0.0"
```

The second key gets ignored. I will try to create a fix as soon as possible.

**Comment by yharaskrik** [comment]
> Thank you @yharaskrik, I found the issue thanks to your `lock-file`.
> 
> ```yaml
> "wrap-ansi-cjs@npm:wrap-ansi@^7.0.0", wrap-ansi@^7.0.0:
>   version "7.0.0"
>   resolved "https://registry.yarnpkg.com/wrap-ansi/-/wrap-ansi-7.0.0.tgz#67e145cff510a6a6984bdf1152911d69d2eb9e43"
>   integrity sha512-YVGIj2kamLSTxw6NsZjoBxfSwsn0ycdesmc4p+Q21c5zPuZ1pl+NfxVdxPtdHvmNVOQ6XSYG4AUtyt/Fi7D16Q==
>   dependencies:
>     ansi-styles "^4.0.0"
>     string-width "^4.1.0"
>     strip-ansi "^6.0.0"
> ```
> 
> The second key gets ignored. I will try to create a fix as soon as possible.

Amazing thank you!

**Comment by greaterweb** [comment]
My team is experiencing this bug as well, is there any sort of temporary workaround that can be done in the short term?

**Comment by yharaskrik** [comment]
> My team is experiencing this bug as well, is there any sort of temporary workaround that can be done in the short term?

Would also love to know if there is a workaround for this for the time being.

**Comment by yharaskrik** [comment]
Maybe have found a workaround. Not sure what the unintended side effects are but if you use yarn you can add this to your resolutions in package.json
`"**/wrap-ansi-cjs": "npm:wrap-ansi"`

This is the diff that is produced from that in the lock file.
<img width="1728" alt="image" src="https://github.com/nrwl/nx/assets/9469090/e778dbee-aaad-481b-815f-acaeeee56818">

**Comment by meeroslav** [comment]
Your new lock file on the right incorrectly maps `v7` to `v8.1.0`. It **could** work, but it could also break horribly.
I'm hoping to have this potentially patched today.

cc @FrozenPandaz

**Comment by yharaskrik** [comment]
> Your new lock file on the right incorrectly maps `v7` to `v8.1.0`. It **could** work, but it could also break horribly.
> I'm hoping to have this potentially patched today.
> 
> cc @FrozenPandaz 

Haha figured so. I think it's a dev dependency from what I can't tell and out CI is entirely green 🤷‍♂️ but it would be great to have it patched lll be on the lookout!
