### ISSUE TITLE
[ESBUILD] Library are not being watched/rebuilt when change occurs in them 

### ISSUE THREAD

**Issue by Akxe** [nrwl/nx#16824]
### Current Behavior

Changes in libraries are **not** being watched by `@angular-devkit/build-angular:browser-esbuild` when serving an Angular application. 

### Expected Behavior

Changes in libraries **should be** watched by `@angular-devkit/build-angular:browser-esbuild`.

### GitHub Repo

https://github.com/nrwl/nx-examples

### Steps to Reproduce

1. Switch `apps/products/project.json` to use `"executor": "@angular-devkit/build-angular:browser-esbuild"`
2. Run `nx serve products` and wait for the initial compilation
3. Change anything in `libs/products`
4. **Change do not trigger rebuild**does

### Nx Report

```shell
Node   : 18.16.0
   OS     : win32 x64
   npm    : 9.1.2
   Hasher : Native

   nx (global)        : 16.1.0
   nx                 : 16.1.0
   @nx/js             : 16.1.0
   @nx/jest           : 16.1.0
   @nx/linter         : 16.1.0
   @nx/workspace      : 16.1.0
   @nx/angular        : 16.1.0
   @nx/cypress        : 16.1.0
   @nx/devkit         : 16.1.0
   @nx/esbuild        : 16.1.0
   @nx/eslint-plugin  : 16.1.0
   @nx/node           : 16.1.0
   @nrwl/storybook    : 13.9.5
   @nrwl/tao          : 16.1.0
   @nx/webpack        : 16.1.0
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/storybook@13.9.5

   To fix this, run `nx migrate nx@16.1.0`
```

### Operating System

- [x] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

This will probably be true for every platform and may affect React too...

**Comment by pumano** [comment]
got the same behaviour when testing `browser-esbuild`. It's only works for /apps/YOUR_APP but any changes in libs not watched/rebuilt

**Comment by Akxe** [comment]
On what platform? Linux?

**Comment by pumano** [comment]
@Akxe for me macos

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This is an issue with the Angular CLI esbuild builder. The only thing Nx does here is to schedule a task to run with that builder. I was able to reproduce the issue in an Angular CLI workspace where there's no Nx.

I can see there's already an issue in the Angular CLI repo https://github.com/angular/angular-cli/issues/25011. That's the better place to track this.
