### ISSUE TITLE
Cannot find module 'typescript'

### ISSUE THREAD

**Issue by nathanhokanson** [nrwl/nx#1682]
## Expected Behavior

A workspace is created.

## Current Behavior

○ → npx create-nx-workspace@8.3.0 test2
npx: installed 142 in 5.957s

>  NX  Creating a sandbox...

added 324 packages from 218 contributors and audited 2993 packages in 6.88s
found 0 vulnerabilities

>  NX  Running: ng new "test2" --collection=@nrwl/workspace

An unhandled exception occurred: Cannot find module 'typescript'
Require stack:
- /home/nathan/src/node_modules/@nrwl/workspace/src/utils/ast-utils.js
- /home/nathan/src/node_modules/@nrwl/workspace/src/schematics/shared-new/shared-new.js
- /home/nathan/src/node_modules/@nrwl/workspace/src/schematics/ng-new/ng-new.js
- /tmp/tmp-20755jZnN3HaFByjE/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /tmp/tmp-20755jZnN3HaFByjE/node_modules/@angular-devkit/schematics/tools/index.js
- /tmp/tmp-20755jZnN3HaFByjE/node_modules/@angular/cli/utilities/json-schema.js
- /tmp/tmp-20755jZnN3HaFByjE/node_modules/@angular/cli/models/command-runner.js
- /tmp/tmp-20755jZnN3HaFByjE/node_modules/@angular/cli/lib/cli/index.js
- /tmp/tmp-20755jZnN3HaFByjE/node_modules/@angular/cli/lib/init.js
- /tmp/tmp-20755jZnN3HaFByjE/node_modules/@angular/cli/bin/ng
See "/tmp/ng-NUmSNh/angular-errors.log" for further details.
Command failed: "/tmp/tmp-20755jZnN3HaFByjE/node_modules/.bin/ng" new "test2" --collection=@nrwl/workspace

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. run the command:   npx create-nx-workspace@8.3.0 test2

### Context

This is on Ubuntu with node 12.7.0, npm/x 6.10.2, with angular-cli@8.2.0 installed globally

**Comment by mehrad-rafigh** [comment]
@bcabanes This happened here as well https://github.com/nrwl/nx/issues/1581

**Comment by vsavkin** [comment]
Do you have the same issue when trying to create it outside `/home/nathan/src`?

**Comment by nathanhokanson** [comment]
Ok, that does work.  Funky.  Is it going to be a problem if I move the directory in ~/src/ after I create it?

**Comment by vsavkin** [comment]
Node resolves modules recursively, which creates all sorts of problems like this. 

`create-nx-workspace` creates a sandbox where it installs `@nrwl/workspace` and `typescript`. In your case, however, it uses `@nrwl/workspace` from `/home/nathan/src/node_modules`, and I imagine there is not typescript next to it.

You can fix it:
- You can move the directory into `src` after you create it
- You can remove `@nrwl/workspace` from `/home/nathan/src/node_modules`

You can also look through your globally installed packages and remove all @nrwl packages except `@nrwl/cli`. No other nrwl packages should be installed globally.

I'm going to close this issue. If you have further problems, please reopen it, and I'll help you out.
