### ISSUE TITLE
Remove Redundant Head Component in Generated NextJS Layout Component

### ISSUE THREAD

**Issue by ruslanguns** [nrwl/nx#16832]
### Current Behavior

When appDir is enabled in a new NextJS application, the generated layout.tsx file component is using a Head component from next/head, and also implementing the Metadata API. This leads to a warning message that says, "Warning: You're using next/head inside the app directory, please migrate to the Metadata API."

### Expected Behavior

The generated code for the layout.tsx file component should use only the Metadata API and not include the Head component from next/head, as it creates redundancy and leads to a warning message.

### GitHub Repo

https://github.com/ruslanguns/nextjs-metadata-api/blob/main/apps/demo/app/layout.tsx

### Steps to Reproduce

1. Generate a NextJS application, make sure appDir is enabled
2. Resultant code will contain Head component implemented.

### Nx Report

```shell
➜ nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.15.0
   OS     : linux x64
   pnpm   : 8.2.0
   Hasher : Native

   nx (global)        : 16.1.0
   nx                 : 16.1.1
   @nx/js             : 16.1.1
   @nx/jest           : 16.1.1
   @nx/linter         : 16.1.1
   @nx/workspace      : 16.1.1
   @nx/eslint-plugin  : 16.1.1
   @nx/next           : 16.1.1
   @nx/react          : 16.1.1
   typescript         : 5.0.4
```

### Failure Logs

```shell
➜ nx serve mantine

> nx run mantine:serve:development

warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

event - compiled client and server successfully in 2.4s (265 modules)
wait  - compiling...
[ ready ] on http://localhost:4200
event - compiled client and server successfully in 602 ms (265 modules)
wait  - compiling /page (client and server)...
Warning: You're using `next/head` inside the `app` directory, please migrate to the Metadata API. See https://beta.nextjs.org/docs/api-reference/metadata for more details.
event - compiled client and server successfully in 3.8s (523 modules)
wait  - compiling...
event - compiled successfully in 1263 ms (197 modules)
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Closing as this has been addressed
