### ISSUE TITLE
nx migrate latest is looking for yarn even though npm is specified

### ISSUE THREAD

**Issue by anthony-b-dev** [nrwl/nx#16836]
### Current Behavior

I have npm specified as the package manager, but running `nx migrate` gives an error that yarn is not installed.

### Expected Behavior

`nx migrate` should just use npm to update all dependencies.

### GitHub Repo

https://github.com/nrwl/nx-examples

### Steps to Reproduce

1. Ensure the package manager in `nx.json` is specified to be "npm".
2. Run `nx migrate latest` in the terminal.

### Nx Report

```shell
Node : 20.1.0
   OS   : win32 x64
   npm  : 9.6.6

   nx (global)             : 16.1.1
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/esbuild           : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/express           : 15.9.2
   @nrwl/nest              : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 15.3.0
   @ngrx/effects         : 15.3.0
   @ngrx/entity          : 15.3.0
   @ngrx/router-store    : 15.3.0
   @ngrx/store           : 15.3.0
   @ngrx/store-devtools  : 15.3.0
   @ngrx/eslint-plugin   : 15.3.0
   @ngrx/schematics      : 15.3.0
```

### Failure Logs

```shell
'yarn' is not recognized as an internal or external command,
operable program or batch file.

 >  NX   Command failed: yarn --version

   'yarn' is not recognized as an internal or external command,
   operable program or batch file.


Error: Command failed: yarn --version
'yarn' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at getPackageManagerVersion (C:\Users\antbl\AppData\Local\Temp\tmp-2240-D9WjUibkW8wf\node_modules\nx\src\utils\package-manager.js:103:41)       
    at Object.yarn (C:\Users\antbl\AppData\Local\Temp\tmp-2240-D9WjUibkW8wf\node_modules\nx\src\utils\package-manager.js:44:33)
    at getPackageManagerCommand (C:\Users\antbl\AppData\Local\Temp\tmp-2240-D9WjUibkW8wf\node_modules\nx\src\utils\package-manager.js:94:36)        
    at C:\Users\antbl\AppData\Local\Temp\tmp-2240-D9WjUibkW8wf\node_modules\nx\src\command-line\migrate.js:759:68
    at Generator.next (<anonymous>)
    at C:\Users\antbl\AppData\Local\Temp\tmp-2240-D9WjUibkW8wf\node_modules\tslib\tslib.js:167:75
    at new Promise (<anonymous>)
Command failed: C:\Users\antbl\AppData\Local\Temp\tmp-2240-D9WjUibkW8wf\node_modules\.bin\nx _migrate latest --verbose
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

nx.json file:

`  "cli": {
    "packageManager": "npm"
  },`

If I am missing something, please let me know. I have tried to use PNPM as well but it keeps looking for yarn. Seems like this should be a fairly easy to migrate, but I don't understand what steps are missing. I was not getting this error 2 months ago.

**Comment by Releef** [comment]
It seems to be an issue with the new implementation of the `detectPackageManager`:
```typescript
/** NEW **/
/**
 * Detects which package manager is used in the workspace based on the lock file.
 */
export function detectPackageManager(dir: string = ''): PackageManager {
  const nxJson = readNxJson();
  return nxJson.cli?.packageManager ?? existsSync(join(dir, 'yarn.lock'))
    ? 'yarn'
    : existsSync(join(dir, 'pnpm-lock.yaml'))
    ? 'pnpm'
    : 'npm';
}

/** OLD **/
 * Detects which package manager is used in the workspace based on the lock file.
 */
export function detectPackageManager(dir: string = ''): PackageManager {
  return existsSync(join(dir, 'yarn.lock'))
    ? 'yarn'
    : existsSync(join(dir, 'pnpm-lock.yaml'))
    ? 'pnpm'
    : 'npm';
}
```

The logic of the new function seems to be correct, if the nxJson is retrieved correctly and the root dir is correct. I do not have a yarn.lock file in my project and still I have the same issue. This suggests that the root dir is not correctly set and the nxJson is not correctly retrieved. 

Upon further inspection, NX creates a temporary map with node_modules and within those node_modules are several yarn.lock files. So my guess is that it searches a yarn.lock file relative to the temporary map and finds it. 

Sorry for not pinpointing to the code, but hope this helps.

**Comment by anthony-b-dev** [comment]
I likewise do not have a yarn.lock file in my directory, never have. 
Even if nxJson is not correctly retrieved, it should just default to "npm in the end. But I think you're right in that it has something to do with the dependencies as I was going manually through my `package-lock.json` file searching for "yarn" and noticed some of the dependencies did not have "npm" listed as one of their engines even though they had "yarn" listed. 

Not sure if this has anything to do with it though as this didn't seem to matter a little while ago...

**Comment by the-ult** [comment]
Same seems to be happening with `pnpm` as well


```
❯ pnpm nx migrate --run-migrations

 >  NX   Running 'yarn' to make sure necessary packages are installed

yarn install v1.22.19
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning @nrwl/angular > magic-string > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
⡀ universalify@^2.0.0^C
```

```
❯ pnpm nx report                  
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node : 18.16.0
   OS   : darwin x64
   pnpm : 8.4.0
   
   nx                      : 15.9.4
   @nrwl/js                : 15.9.4
   @nrwl/jest              : 15.9.4
   @nrwl/linter            : 15.9.4
   @nrwl/workspace         : 15.9.4
   @nrwl/angular           : 15.9.4
   @nrwl/cli               : 15.9.4
   @nrwl/cypress           : 15.9.4
   @nrwl/devkit            : 15.9.4
   @nrwl/eslint-plugin-nx  : 15.9.4
   @nrwl/tao               : 15.9.4
   @nrwl/webpack           : 15.9.4
   @nrwl/nx-cloud          : 16.0.5
   typescript              : 4.9.4
   ---------------------------------------
   Community plugins:
   @testing-library/angular : 13.4.0
```

**Comment by seyfert** [comment]
Having same problem. I have an Nx workspace that uses pnpm that I am trying to upgrade to the latest 15.x version.  However, since `nx migrate` always uses the latest version of Nx it is failing due to this issue.

**Comment by znorman-harris** [comment]
Same errorfor me. I have exclusively used npm (never even installed yarn on my machine) and was baffled I had this error pop up when trying to migrate to the latest version.

Error for `nx migrate next`:

![image](https://user-images.githubusercontent.com/31664668/236686246-87f067b8-fef5-40e2-af04-df1d6648d057.png)

And here is the `nx report` for me:

```
   Node : 18.12.1
   OS   : win32 x64
   npm  : 9.2.0
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/esbuild           : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   rxjs              : 6.6.7
   @ngneat/transloco : 4.2.6
```

**Comment by anthony-b-dev** [comment]
@johnhwhite such a simple fix! Thanks for the quickness in addressing this!

**Comment by Signaturo** [comment]
Sorry, I'm a noob, help me :) I understand that the bug has been fixed, but how can I fix it in my project now? I need to somehow pull the changes into my project, but I can't figure out how. Could you help me or write what to study in order to understand this.

**Comment by anthony-b-dev** [comment]
A patched version should be released in the next few days.
