### ISSUE TITLE
TypeError with NextJS 13.4 installation due to missing 'serverActions' property in experimental config

### ISSUE THREAD

**Issue by ruslanguns** [nrwl/nx#16845]
### Current Behavior

After installing NextJS 13.4, a TypeError is being thrown with the message "Cannot read properties of undefined (reading 'serverActions')" when running the code. This bug was introduced in the PR https://github.com/nrwl/nx/pull/16819, which aimed to add support for NextJS 13.4.

The issue appears to be caused by the experimental configuration missing the 'serverActions' property. This error can be found in `line 165` of the `with-nx.ts` file (https://github.com/nrwl/nx/blob/832fa71488c9afb48fa255b76808385977bedd35/packages/next/plugins/with-nx.ts#L165).

Error wouldn't happen if the `serverActions `is provided

### Expected Behavior

A potential solution to this issue is to validate if the 'serverActions' property has been provided in the _nextConfig.experimental object. For example:

```ts
_nextConfig.experimental && _nextConfig.experimental['serverActions'] ? 'experimental' : 'next';
```

This fix should be implemented as soon as possible to ensure the proper functioning of the code.

### GitHub Repo

https://github.com/ruslanguns/nx-issue-16845

### Steps to Reproduce

1. Add Next project 
2. Install NextJS >= 13.4
3. Serve the project

### Nx Report

```shell
❯ nx report              

 >  NX   Report complete - copy this into the issue template

   Node   : 18.15.0
   OS     : linux x64
   pnpm   : 8.2.0
   Hasher : Native
   
   nx (global)        : 16.1.0
   nx                 : 16.1.1
   @nx/js             : 16.1.1
   @nx/jest           : 16.1.1
   @nx/linter         : 16.1.1
   @nx/workspace      : 16.1.1
   @nx/eslint-plugin  : 16.1.1
   @nx/next           : 16.1.1
   @nx/react          : 16.1.1
   typescript         : 5.0.4
```

### Failure Logs

```shell
❯ nx serve demo --verbose

> nx run demo:serve:development


 >  NX   Cannot read properties of undefined (reading 'serverActions')


TypeError: Cannot read properties of undefined (reading 'serverActions')
    at /home/rus/Projects/RG/nx/nx-issue/node_modules/.pnpm/@nx+next@16.1.1_@babel+core@7.21.8_@types+node@20.1.0_eslint@8.40.0_next@13.4.1_nx@16.1.1_typ_2ulqouxg5pgxadp6lsg2huryy4/node_modules/@nx/next/plugins/with-nx.js:110:37
    at forNextVersion (/home/rus/Projects/RG/nx/nx-issue/node_modules/.pnpm/@nx+next@16.1.1_@babel+core@7.21.8_@types+node@20.1.0_eslint@8.40.0_next@13.4.1_nx@16.1.1_typ_2ulqouxg5pgxadp6lsg2huryy4/node_modules/@nx/next/src/utils/config.js:70:9)
    at withNx (/home/rus/Projects/RG/nx/nx-issue/node_modules/.pnpm/@nx+next@16.1.1_@babel+core@7.21.8_@types+node@20.1.0_eslint@8.40.0_next@13.4.1_nx@16.1.1_typ_2ulqouxg5pgxadp6lsg2huryy4/node_modules/@nx/next/plugins/with-nx.js:107:33)
    at /home/rus/Projects/RG/nx/nx-issue/node_modules/.pnpm/@nx+next@16.1.1_@babel+core@7.21.8_@types+node@20.1.0_eslint@8.40.0_next@13.4.1_nx@16.1.1_typ_2ulqouxg5pgxadp6lsg2huryy4/node_modules/@nx/next/src/utils/compose-plugins.js:12:40
    at Generator.next (<anonymous>)
    at fulfilled (/home/rus/Projects/RG/nx/nx-issue/node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:164:62)
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This comment could be useful for reference when the bug has been introduced: https://github.com/nrwl/nx/pull/16819#pullrequestreview-1415742460

**Comment by jonsoku2** [comment]
same issue

**Comment by malord** [comment]
For anyone else reaching this page from search, temporary solution is to add `experimental: {}` to next.config.js:

```js
/**
 * @type {import('@nrwl/next/plugins/with-nx').WithNxOptions}
 */
const nextConfig = {
  nx: {
    // Set this to true if you would like to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: false,
  },

  experimental: {}, // <-- add this
};
```

**Comment by jaysoo** [comment]
We'll patch this. For now use @malord 's workaround.

PR is open now https://github.com/nrwl/nx/pull/16909
