### ISSUE TITLE
"nx migrate" starts the process with yarn package manager, but nx.json is specified as npm.

### ISSUE THREAD

**Issue by Signaturo** [nrwl/nx#16842]
### Current Behavior

 >  NX   Running 'yarn' to make sure necessary packages are installed

yarn install v1.22.19
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.

### Expected Behavior

Running nx commands starts the npm package manager. If someone starts running yarn, an error should pop up so that only npm is used.

### GitHub Repo

https://github.com/Signaturo/printi-price/tree/migrate_to_nx14

### Steps to Reproduce

1. npm i
2. nx migrate --run-migrations

### Nx Report

```shell
$ nx report

 >  NX   Cannot find module '@yarnpkg/parsers'

   Require stack:
   - /home/satyadev/PROJECTS/13to14/printi-price/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js
   - /home/satyadev/PROJECTS/13to14/printi-price/node_modules/nx/src/plugins/js/lock-file/lock-file.js
   - /home/satyadev/PROJECTS/13to14/printi-price/node_modules/nx/src/plugins/js/index.js
   - /home/satyadev/PROJECTS/13to14/printi-price/node_modules/nx/src/utils/nx-plugin.js
   - /home/satyadev/PROJECTS/13to14/printi-price/node_modules/nx/src/config/workspaces.js
   - /home/satyadev/PROJECTS/13to14/printi-price/node_modules/nx/src/config/configuration.js
   - /home/satyadev/PROJECTS/13to14/printi-price/node_modules/nx/src/utils/package-manager.js
   - /home/satyadev/PROJECTS/13to14/printi-price/node_modules/nx/bin/init-local.js
   - /home/satyadev/PROJECTS/13to14/printi-price/node_modules/nx/bin/nx.js
   - /usr/local/lib/node_modules/nx/bin/nx.js
```

### Failure Logs

```shell
Error: Command failed: yarn
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at runInstall (/tmp/tmp-119675-b5PGr6ANREoX/node_modules/nx/src/command-line/migrate.js:883:34)
    at /tmp/tmp-119675-b5PGr6ANREoX/node_modules/nx/src/command-line/migrate.js:950:13
    at Generator.next (<anonymous>)
    at /tmp/tmp-119675-b5PGr6ANREoX/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/tmp/tmp-119675-b5PGr6ANREoX/node_modules/tslib/tslib.js:163:16)
    at runMigrations (/tmp/tmp-119675-b5PGr6ANREoX/node_modules/nx/src/command-line/migrate.js:948:20)
Command failed: /tmp/tmp-119675-b5PGr6ANREoX/node_modules/.bin/nx _migrate --run-migrations --verbose
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I have been using the npm package manager since the beginning of the project. During the migration, some package was not installed using npm and it was suggested to use yarn, where I agreed. I realized that I didn't need to use several package managers and removed the yarn from the project, but the lock files remained and I manually deleted the yarn data. But still, for some reason, when the migration command is run, it launches Yarn, although the engine indicates that npm should be used by default. Can you please tell me how can I disable the use of yarn and leave only npm as the default.

**Comment by anthony-b-dev** [comment]
Sorry to see you also having this issue. Duplicate. Merge with #16836.

**Comment by AgentEnder** [comment]
Closed as duplicate
