### ISSUE TITLE
react-native build-ios ignores sync-deps options

### ISSUE THREAD

**Issue by ste7en** [nrwl/nx#16856]
### Current Behavior

When defining a list of include and exclude dependencies for the `sync-deps` executor, these are ignored when the script is called by `run-ios` or `build-ios`, resulting in an inconsistency of the output (package.json).

### Expected Behavior

Nx's `@nrwl/react-native:sync-deps` executor should be called with its options when called by another executor (i.e. android and iOS build/run).

### Steps to Reproduce

1. Define a list of dependencies to include or exclude in your sync-deps target
2. Call the run-ios target
3. You'll notice it is rewriting the package.json with excluded dependencies

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : darwin arm64
   yarn : 3.4.1
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/detox             : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/expo              : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/react-native      : 15.9.2
   @nrwl/storybook         : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   @nrwl/nx-cloud          : 15.3.5
   typescript              : 5.0.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
you can set the sync option to false for build and run target:
```
 "build-ios": {
      "executor": "@nx/react-native:build-ios",
      "options": {
        "sync": false
      }
    },
    "run-ios": {
      "executor": "@nx/react-native:run-ios",
      "options": {
        "simulator": "iPhone 14 Pro",
        "sync": false
      }
    },
``` and it will disable the sync deps when these targets are invokded
