### ISSUE TITLE
package.json is generated differently depending on import order

### ISSUE THREAD

**Issue by kaifresh** [nrwl/nx#16857]
### Current Behavior

With `generatePackageJson` set to true in the default build step, I observe that changing the order of imports in my app results in different dependencies being written into the generated `package.json`. 

### Expected Behavior

Regardless of import order, the generated dependencies should be the same.

### Steps to Reproduce

1. I don't know exactly how to reproduce this behaviour without showing you my project. I have used `nx` previously and I haven't seen this behaviour. 

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 19.9.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 15.3.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.3.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : 15.3.0
   @nrwl/node : 15.3.0
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.3.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.3.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.3.0
   @nrwl/webpack : 15.3.0
   @nrwl/workspace : 15.3.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @nx-tools/nx-container: 4.0.2
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
We've moved a bit a round in this area recently, can you try migrating to latest and see if you still experience the issue?

**Comment by kaifresh** [comment]
@AgentEnder ok I will do this! Thanks
