### ISSUE TITLE
Error updating to Nx v8

### ISSUE THREAD

**Issue by yharaskrik** [nrwl/nx#1685]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Have a repository that is using Angular v8 and was on Nx 7 prior to update to Angular v8.

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Updating Nx, will update the correct packages and not fail

Please describe the behavior you are expecting

## Current Behavior

When running yarn update it tries to update @nrwl/workspace but fails because that dependency does not exist. If I yarn add @nrwl/workspace it adds it and then yarn update does not do anything as everything is up to date. If I try and `ng g lib test` it fails after selecting options with `Cannot read property 'types' of undefined`

```
± |jaybell/nx-8 {20} U:2 ?:1 ✗| → ng g lib test
? In which directory should the library be generated? 
? What framework should this library use? Angular    [ https://angular.io/             ]
? Which stylesheet format would you like to use? SCSS   [ http://sass-lang.com   ]
? Which tags would you like to add to the library? (used for linting) 
? Which Unit Test Runner would you like to use for the library? Jest [https://jestjs.io/]
Cannot read property 'types' of undefined
```

After installing workspace my packages are 
```
        "@nrwl/builders": "^7.8.7",
        "@nrwl/nx": "^7.8.6",
        "@nrwl/schematics": "^7.8.6",
        "@nrwl/workspace": "^8.4.3",
```

Before the install they were:
```
        "@nrwl/nx": "^7.8.6",
        "@nrwl/builders": "^7.8.7",
        "@nrwl/schematics": "^7.8.6",
```

I have looked on npm and @nrwl/nx does not have a release for 8+ even though it is in the Github Releases. Is Nx failing to update to 8 and thus not running migrations because npm does not have a v8 for nx?

### Context

Please provide any relevant information about your setup:

- Nx 7.8.7 => Nx 8.x.x
- Angular v8.2
- upgrading to nx 8

As a note, if I change all of the versions in my package.json to 8+ for nrwl packages and install then try and generate a lib I get

```
        "@nrwl/builders": "^8.0.2",
        "@nrwl/nx": "nrwl/nx.git#8.4.3",
        "@nrwl/schematics": "^8.4.3",
        "@nrwl/workspace": "^8.4.3",
```

```
± |jaybell/nx-8 {20} U:2 ?:1 ✗| → ng g lib test
? In which directory should the library be generated? 
? Which stylesheet format would you like to use? SASS(.scss)  [ http://sass-lang.com   ]
ERROR! jest.config.js already exists.
The Schematic workflow failed. See above.
```

**Comment by yharaskrik** [comment]
Ok update, I got `ng g lib test` to work

I had to go into my angular.json file after installing @nrwl/workspace and add
```,
    "@nrwl/angular:application": {
      "unitTestRunner": "jest",
      "e2eTestRunner": "cypress"
    },
    "@nrwl/angular:library": {
      "unitTestRunner": "jest"
    }
```

To `schematics` and make sure that all of my builders were using @nrwl/angular instead of their prior values, as well as make sure `cli.defaultCollection` was using @nrwl/angular as well.

Maybe my workspace wasn't setup correctly before or something as this project was not generated with nx but rather migrated to it about 5 months ago.

**Comment by vsavkin** [comment]
@yharaskrik thanks for submitting the issue. Would it be possible for you to create a repro of the repo (the before state)?

**Comment by yharaskrik** [comment]
@vsavkin I can definitely spend some time trying to recreate that. Our project in production is still in the before state so ill just trim that down to a minimal repo.

**Comment by vsavkin** [comment]
@yharaskrik I released 8.4.4 which fixed some issues regarding updating from 7x. Could you try updating to it instead?

```
ng update @nrwl/schematics@8.4.4
```

**Comment by yharaskrik** [comment]
@vsavkin I can for sure! Just in the midst of implementing a PWA right now but I will try and update using 8.4.4 tonight on our current repo and see what happens!

**Comment by vsavkin** [comment]
@yharaskrik thank you!

**Comment by yharaskrik** [comment]
@vsavkin I tried to upgrade our currently working prod branch on Angular 7 and Nx 7 using 
```ng update @nrwl/schematics@8.4.4``` and it worked fine, but then this:

```
± |jaybell/nx-upgrade-test {23} U:207 ✗| → ng g lib test
? In which directory should the library be generated? 
? Which stylesheet format would you like to use? SASS(.scss)  [ http://sass-lang
.com   ]
? Which tags would you like to add to the library? (used for linting) 
? Which Unit Test Runner would you like to use for the library? Jest [https://je
stjs.io/]
Project name "test" is not a supported name.
```

Unsure if requirements on the name of libs changed or if this is something else.

**Comment by vsavkin** [comment]
@yharaskrik the angular cli had this restriction for a while. You cannot use test as the project name.

**Comment by vsavkin** [comment]
It looks the upgrade process is working. So I'm going to close this issue. If you have further problems, just reopen the issue with a repro.

Btw, when moving from 7 to 8, you need to run ng update twice.

ng update @nrwl/schematics
ng update @nrwl/workspace

**Comment by yharaskrik** [comment]
@vsavkin awesome thank you! Seems as though it all works for me now. Just wanted to make sure if anyone else had the issues I did they could find an answer.
