### ISSUE TITLE
performance: slow graph load

### ISSUE THREAD

**Issue by cdaringe** [nrwl/nx#16869]
### Current Behavior

some consider performance issues a bug, others a feature. i flipped a coin :)

## Problem statement

Construction of workspace metadata is **slow**, **serial**, and **sync**. In our large project, just inlinining project.json's takes >4s on all devs computers.

![image](https://user-images.githubusercontent.com/1003261/236875907-a75ca59a-eb2b-4d79-a49a-9a982dac27e0.png)

### Expected Behavior

faster workspace load. Minimally, concurrency in slow fs-ops used to constructing the workspace model.

In some cases, I plain _don't care about the graph_. For example, `pnpm run nx test foo`, I never care about the graph. Some people might--they may use the graph to build dependencies pre-test. However, in many of my cases, it would be great to just _skip_ all of that and get right to work.

### GitHub Repo

n/a

### Steps to Reproduce

1. make a big nx workspace of arbitrary size. in my case, 1.5k projects
2. run nx against the project, with node profiling
3. observe seconds of overhead

### Nx Report

```shell
> walmart-web@0.0.1 nx /Users/c0d01a5/src/walmart-2
> NODE_OPTIONS="$NODE_OPTIONS --max-old-space-size=12192" nx "report"


 >  NX   Report complete - copy this into the issue template

   Node : 16.10.0
   OS   : darwin arm64
   pnpm : 7.25.0
   
   nx : 14.0.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 12.8.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.0.0
   @nrwl/eslint-plugin-nx : 14.0.0
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.0
   @nrwl/js : 14.0.0
   @nrwl/linter : 14.0.0
   @nrwl/nest : Not Found
   @nrwl/next : 14.0.0
   @nrwl/node : 14.0.0
   @nrwl/nx-cloud : 15.0.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.0.0
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.0.0
   @nrwl/web : 14.0.0
   @nrwl/workspace : 14.0.0
   typescript : 4.3.2
   rxjs : 6.6.3
   ---------------------------------------
   Community plugins:
   	 @nrwl/gatsby: 12.8.0
   	 @testcafe-community/nx-builder: 1.1.0
```

### Failure Logs

```shell
n/a
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

n/a

**Comment by AgentEnder** [comment]
Hey @cdaringe! This is something that should be significantly reduced in latest, especially with the presence of the daemon. We are actively working on improving certain facets of this still, but as there is no regression in recent versions and it is something that we are aware of I'm going to go ahead and close this out.

The main reason behind this is that:
- You are several versions behind, and it has improved in the meantime.
- There are not actionable steps to be taken from this issue.

My recommendation would be to update as soon as is reasonable for your organization, and ensure that the daemon is running properly.

**Comment by cdaringe** [comment]
hey @AgentEnder, despite improvements, even in the latest, workspace load & inlining is still entirely synchronous. minimally, i'd think nx should be loading all projects into the workspace model concurrently

**Comment by AgentEnder** [comment]
I agree, some of it needs to be moved async, but there are public APIs which are syncronous that we can't easily swap over. Like I said, we are working on this but a large portion of it should be faster with the daemon.

The inlining and load is only ran as part of the daemon in 99% of local dev use cases now, so its less of a big deal.

**Comment by cdaringe** [comment]
got it. ya, i'm looking at it from a lens of CI and local. sounds like there are some challenges to making it _rip_ in all scenarios. given that the daemon really only applies to local, i'm prone to keeping the issue open. thoughts?
