### ISSUE TITLE
createLockFile doesn't handle file: resolutions with yarn berry

### ISSUE THREAD

**Issue by vneogi199** [nrwl/nx#16871]
### Current Behavior

When using yarn berry with `file:` resolution in root package.json and calling `createLockFile`,
` >  NX   Pruned lock file creation failed. The following package was not found in the root lock file: lib1@0.0.1`.

**Root package.json:**
`
"dependencies": {
   "lib1": "*"
},
"resolutions": {
   "lib1": "packages/lib1"
}
`

**package.json for lib1**
`
"version": "0.0.1"
`

This problem occurs with yarn berrry only, not with yarn1.

Seems like the problem is because we dont handle `file:` or `link:` here:
[https://github.com/nrwl/nx/blob/dc911051aa6f91de7ee4ec440fcbb7b9345f45fa/packages/nx/src/plugins/js/lock-file/yarn-parser.ts#L135-L142](https://github.com/nrwl/nx/blob/dc911051aa6f91de7ee4ec440fcbb7b9345f45fa/packages/nx/src/plugins/js/lock-file/yarn-parser.ts#L135-L142)

Above we are returning resolution consisting of `file:` which causes us to not find a version below: [https://github.com/nrwl/nx/blob/d02c2cbfe76b1ac923e7b765649d032bae48cb38/packages/nx/src/plugins/js/lock-file/project-graph-pruning.ts#L96](https://github.com/nrwl/nx/blob/d02c2cbfe76b1ac923e7b765649d032bae48cb38/packages/nx/src/plugins/js/lock-file/project-graph-pruning.ts#L96)

### Expected Behavior

yarn.lock file for lib1 should get created with version from package.json of lib1 when using `file:` resolution with yarn3.

### Steps to Reproduce

1. Setup yarn3.
2. Create lib1 with package.json version 0.0.1.
3. Create lib2 dependent on lib1 and use `nx/js:tsc` with generateLockFile or `createLockFile` method from a custom NX plugin `@nx-example/my-plugin`.
4. It fails with error `NX   Pruned lock file creation failed. The following package was not found in the root lock file: lib1@0.0.1`

### Nx Report

```shell
Node   : 19.9.0
   OS     : linux x64
   yarn   : 3.1.1
   Hasher : Native
   
   nx                 : 16.1.0
   @nx/js             : 16.1.0
   @nx/jest           : 16.1.0
   @nx/linter         : 16.1.0
   @nx/workspace      : 16.1.0
   @nx/angular        : 16.1.0
   @nx/cypress        : 16.1.0
   @nx/devkit         : 16.1.0
   @nx/eslint-plugin  : 16.1.0
   @nx/plugin         : 16.1.0
   @nx/react          : 16.1.0
   @nrwl/tao          : 16.1.0
   @nx/web            : 16.1.0
   @nx/webpack        : 16.1.0
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 15.3.0
   @ngrx/effects         : 15.3.0
   @ngrx/entity          : 15.3.0
   @ngrx/router-store    : 15.3.0
   @ngrx/store           : 15.3.0
   @ngrx/store-devtools  : 15.3.0
   @nx-example/my-plugin : 0.0.1
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by meeroslav** [comment]
Thank you @vneogi199 for reporting this issue. Please create a small repo where this can be reproduced.

**Comment by vneogi199** [comment]
@meeroslav Please find the repo branches below.

[When lib is added to root package.json](https://github.com/vneogi199/nx-examples/tree/lock-file-issue-when-added-in-package-json)

[When lib is not added to root package.json](https://github.com/vneogi199/nx-examples/tree/lock-file-issue-when-not-added-in-package-json)

Run `yarn exec nx run shared-product-ui:build` (only using yarn3)
Throws:
`Original error: Pruned lock file creation failed. The following package was not found in the root lock file: shared-jsxify@0.0.1`



Also do let me know if it is required to list `shared-jsxify` in the example above as part of the root package.json. I dont know what is the right approach. I only need `shared-jsxify` listed in the lock file for `shared-product-ui` with version listed in its package.json.

**Comment by meeroslav** [comment]
Thank you @vneogi199 for providing the reproduction.

Out of curiosity, what is the scenario where you would need pruned lock file pointing to your internal library?

The intent of the lock file pruning was to add `package.json` and lock file to compiled app that would provide info about necessary packages that needs to be installed based on the target environment. 

If we would keep that file link to local library and try to push that output to server to build it there, how would server fetch it?

**Comment by vneogi199** [comment]
I don't need to link to local library, I found this [issue](https://github.com/nrwl/nx/issues/15020) with same error message as mine which suggested to try file/link resolutions so I tried them. (I think I need to edit the title of this issue if file/link is not the correct approach)

For context, we are using the generated lock file more for dependency tracking and their versions.
Something like:
shared-product-ui@0.0.1 -> shared-jsxify@0.0.1 -> lodash@4.17.21
shared-product-ui@0.0.1 -> shared-jsxify@0.0.1 -> react@18.0.0
shared-product-ui@0.0.1 -> express@4.18.1
For now we have found an alternative way to do this.

Only thing we are blocked with is when we have a dependency between two NX packages, we are unable to generate lock file with error `Original error: Pruned lock file creation failed. The following package was not found in the root lock file: shared-jsxify@0.0.1`

shared-jsxify is absent in root lock file as it is managed by tsconfig path mappings. I dont know what is the correct approach to resolve this.

This [diff](https://github.com/nrwl/nx-examples/compare/master...vneogi199:nx-examples:lock-file-issue-when-not-added-in-package-json) shows the scenario.

I would prefer NX generate lock file for shared-product-ui with shared-jsxify@0.0.1 (pick version for shared-jsxify from it's package.json) for the case when dependency shared-product-ui -> shared-jsxify

**Comment by meeroslav** [comment]
I don't think you should reference those shared libraries in your `package.json`.

You should use `tsconfig.json` for handling alias imports e.g.:
```jsonc
{
  "compilerOptions": {
    // ...
    "paths": {
      "shared-product-ui": ["packages/shared-product-ui"],
     }
   }
}    
```

The application bundle will ensure all those dependencies are bundled.

**Comment by meeroslav** [comment]
Ok, so I found the issue in your setup.

You are trying to build libraries with `generateLockFile` but that flag was never intended for libraries, only for applications.
It makes no sense to generate lock file for the library. If you want to handle versioning and generate `package.json` for publishing running the plain `@nx/js:tsc` with `updateBuildableProjectDepsInPackageJson: true` will do:

```jsonc
{
  "name": "shared-jsxify",
  "$schema": "../../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "libs/shared/jsxify/src",
  "projectType": "library",
  "generators": {},
  "targets": {
    "build": {
      "executor": "@nx/js:tsc",
      "options": {
        "buildableProjectDepsInPackageJsonType": "dependencies",
        "clean": true,
        // "generateLockfile": true, <= This is obsolete and it's causing an error
        "updateBuildableProjectDepsInPackageJson": true,
        "main": "libs/shared/jsxify/src/index.ts",
        "outputPath": "dist-example/jsxify",
        "tsConfig": "libs/shared/jsxify/tsconfig.lib.json"
      }
    },
    "lint": {
      "executor": "@nx/linter:eslint",
      "options": {
        "lintFilePatterns": [
          "libs/shared/jsxify/src/**/*.ts",
          "libs/shared/jsxify/src/**/*.html"
        ]
      },
      "outputs": ["{options.outputFile}"]
    }
  },
  "tags": ["scope:shared", "type:types"]
}
```
