### ISSUE TITLE
Modifying tree removes all external nodes's dependencies

### ISSUE THREAD

**Issue by meeroslav** [nrwl/nx#16879]
### Current Behavior

Move command removes all external node's dependencies

### Expected Behavior

Move command leaves external nodes's dependencies intact

### GitHub Repo

https://github.com/meeroslav/test-nx-move-removing-external-deps

### Steps to Reproduce

1. Install deps with `yarn` and run any `nx` command e.g. `yarn nx report`
2. Check graph in `node_modules/.cache/nx/mxdeps.json` (there should be dependencies of external nodes)
![Screenshot 2023-05-09 at 11 35 30](https://user-images.githubusercontent.com/881612/237056636-f92d8f23-60c2-42cd-ad5b-fe2e1ac32873.png)

3. Rename a package
```
yarn nx g @nx/workspace:move --project conzumable --destination consumable
```
4. Check again the graph  in `node_modules/.cache/nx/mxdeps.json` - all the external nodes's dependencies are gone
![Screenshot 2023-05-09 at 11 33 54](https://user-images.githubusercontent.com/881612/237056257-ed92547e-ad5c-41ec-bb9a-bca9082bda03.png)

### Nx Report

```shell
Node   : 20.0.0
   OS     : darwin arm64
   yarn   : 1.22.19
   Hasher : Native
   
   nx                 : 16.1.0
   @nx/js             : 16.1.0
   @nx/jest           : 16.1.0
   @nx/linter         : 16.1.0
   @nx/workspace      : 16.1.0
   @nx/devkit         : 16.1.0
   @nx/eslint-plugin  : 16.1.0
   @nrwl/tao          : 16.1.0
   typescript         : 5.0.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This is likely related to JS-code splitting from `nx`, where we now re-generate the graph when files are removed, but we never re-apply lock file parsing.

The error happens after the first tree modification:
https://github.com/nrwl/nx/blob/master/packages/workspace/src/generators/move/move.ts#L30

This line causes the tree to rebuild the graph:
https://github.com/nrwl/nx/blob/master/packages/nx/src/generators/utils/project-configuration.ts#L122

**Comment by pelukron** [comment]
Hello there, I'm same problem on nx@16.0.0

This is on root project as said official doc

**Comment by meeroslav** [comment]
This has been fixed
