### ISSUE TITLE
'neverConnectToCloud' doesn't work

### ISSUE THREAD

**Issue by suhinini** [nrwl/nx#16870]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/nx-cloud/reference/config#disabling-connections-to-nx-cloud

### Additional context or description

`neverConnectToCloud` does not work when used on 16.0.5 - seems like a typo in documentation. I couldn't find this field in nx github repo outside of the documents

**Comment by StalkAltan** [comment]
Can you describe what isn't working about it?

**Comment by StalkAltan** [comment]
@suhinini We can add a clarification in the docs about this, but this property is meant to disable the initial connection to Nx Cloud.

If you want to disable Nx Cloud in a workspace that has already connected, you can do the following:
1. To temporarily disable Nx Cloud, you can run your command with the `--no-cloud` flag, or set the `NX_NO_CLOUD=true` environment variable
2. To permanently disable Nx Cloud, go to your `nx.json` and change the `runner` property to `nx/tasks-runners/default` and remove the `accessToken` property. If you have a `url` property specified, you can also remove that.

Let me know if this achieves what you are looking for.

**Comment by suhinini** [comment]
Got it, thanks. #2 helped.

For the documentation, this line does not mention anything about the "initial connection":

> If your organization has a security reason to disable Nx Cloud, you can cause all methods of connection to fail by adding the neverConnectToCloud property to nx.json.

So I have expected it to work as a killswitch whenever it's added - apparently not the case :) 

Thanks!
