### ISSUE TITLE
Unable to add a new `express` app to an existing `nx workspace` (including a nextjs app)

### ISSUE THREAD

**Issue by MohammadProAcc** [nrwl/nx#16893]
### Current Behavior

$ nx g app
✔ Which generator would you like to use? · @nx/express:application

>  NX  Generating @nx/express:application

✔ What name would you like to use for the node application? · server-core

>  NX   Cannot find module 'nx/src/plugins/js/lock-file/lock-file'

Require stack:
- /home/mohammad/work/projects/main/portfolio/node_modules/@nx/js/src/utils/package-json/update-package-json.js
- /home/mohammad/work/projects/main/portfolio/node_modules/@nx/js/src/utils/package-json/index.js
- /home/mohammad/work/projects/main/portfolio/node_modules/@nx/js/src/index.js
- /home/mohammad/work/projects/main/portfolio/node_modules/@nx/jest/src/generators/init/init.js
- /home/mohammad/work/projects/main/portfolio/node_modules/@nx/jest/src/generators/jest-project/jest-project.js
- /home/mohammad/work/projects/main/portfolio/node_modules/@nx/jest/index.js
- /home/mohammad/work/projects/main/portfolio/node_modules/@nx/node/src/generators/application/application.js
- /home/mohammad/work/projects/main/portfolio/node_modules/@nx/node/index.js
- /home/mohammad/work/projects/main/portfolio/node_modules/@nx/express/src/generators/application/application.js
- /home/mohammad/work/projects/main/portfolio/node_modules/nx/src/config/workspaces.js
- /home/mohammad/work/projects/main/portfolio/node_modules/nx/src/config/configuration.js
- /home/mohammad/work/projects/main/portfolio/node_modules/nx/src/command-line/generate.js
- /home/mohammad/work/projects/main/portfolio/node_modules/nx/src/command-line/nx-commands.js
- /home/mohammad/work/projects/main/portfolio/node_modules/nx/bin/init-local.js
- /home/mohammad/work/projects/main/portfolio/node_modules/nx/bin/nx.js
- /home/mohammad/.snm/releases/18.16.0/lib/node_modules/nx/bin/nx.js
Pass --verbose to see the stacktrace.

### Expected Behavior

nx g app
✔ Which generator would you like to use? · @nx/express:application

>  NX  Generating @nx/express:application

✔ What name would you like to use for the node application? · server-core

>  NX   Application `server-core` generated successfully

### Steps to Reproduce

1.nx g app
2.✔ Which generator would you like to use? · @nx/express:application
3.✔ What name would you like to use for the node application? · server-core

### Nx Report

```shell
$ nx report

>  NX   Report complete - copy this into the issue template

Node : 18.16.0
OS   : linux x64
yarn : 1.22.19

nx                      : 15.7.2
@nrwl/jest              : 15.7.2
@nrwl/linter            : 15.7.2
@nrwl/workspace         : 15.7.2
@nrwl/cli               : 15.7.2
@nrwl/cypress           : 15.7.2
@nrwl/devkit            : 15.7.2
@nrwl/eslint-plugin-nx  : 15.7.2
@nrwl/express           : 16.1.3
@nrwl/js                : 15.7.2
@nrwl/next              : 15.7.2
@nrwl/node              : 16.1.3
@nrwl/react             : 15.7.2
@nrwl/tao               : 15.7.2
@nrwl/vite              : 15.7.2
@nrwl/webpack           : 15.7.2
typescript              : 4.8.4
---------------------------------------
The following packages should match the installed version of nx
- @nrwl/express@16.1.3
- @nrwl/node@16.1.3

To fix this, run `nx migrate nx@16.1.3`
```

### Failure Logs

```shell
typed on `Current Behavior` section
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AdditionAddict** [comment]
You have mismatching versions of Nx. In your nx report most of your versions are 15.7.2 but `nrwl/express` is version 16. I believe they should always be the same and the report gives you the action to take:

Run `nx migrate nx@16.1.3`. 

Incidentally I opened an issue https://github.com/nrwl/nx/issues/16483 to make `nx migrate latest` more prominent because it’s an easy mistake to make.

Note `nrwl/express` is getting replaced by `nrwl/node` or from v16 `nx/node` where you can specify `—framework=express`

**Comment by leosvelperez** [comment]
Thanks for reporting this!

As mentioned by @AdditionAddict in https://github.com/nrwl/nx/issues/16893#issuecomment-1540889290, the issue is that you have a version mismatch in your installed Nx plugins. Please downgrade `@nrwl/express` to `15.7.2` so it matches the installed version of Nx and the rest of the plugins.
