### ISSUE TITLE
Target serve-static doesn't work with run-many

### ISSUE THREAD

**Issue by pcurrivan** [nrwl/nx#16897]
### Current Behavior

When I attempt to run many serve-static targets using run-many, it seems to hang.

The command I'm running is something like:
`nx run-many --target=serve-static --projects=my-app-*`

The last message I see in the console is something like:
`Running target serve-static for 7 projects`
`Executing 3/7 remaining tasks in parallel`
`nx run my-app-1:serve-static:development`
`nx run my-app-2:serve-static:development`
`nx run my-app-3:serve-static:development`

Seems like maybe the tasks are never returning because they just start a server and stay active, so nx never moves onto the other tasks?

### Expected Behavior

It should be possible to run many serve-static targets in a single terminal with run-many.

### Steps to Reproduce

1. Try to execute many serve-static targets with run-many

### Nx Report

```shell
Node : 14.21.1
   OS   : linux x64
   npm  : 8.19.4
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/nest              : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/storybook         : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   ngx-build-plus      : 14.0.0
```

### Operating System

- [ ] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Nx defaults to 3 parallel tasks. If you need more, you can spec if: `nx run-many --target serve-static --parallel {someNumber}`
