### ISSUE TITLE
Bug: nx cli tool only shows version or help if called in an nx workspace 

### ISSUE THREAD

**Issue by joelkesler** [nrwl/nx#16901]
### Current Behavior

If `nx` does not detect a workspace when it is called, it outputs a standard error message:
```
>  NX  The current directory isn't part of an Nx workspace.

  To create a workspace run:
  npx create-nx-workspace@latest <workspace name>


>  NX   NOTE  For more information please visit https://nx.dev/
```

This can be difficult when troubleshooting. Recently I ran into a bug where an older version of `nx` (v8) was being loaded instead of the current version (v16).  The older version could not parse the newer workspace and gave the above error message.

### Expected Behavior

Being able to run `nx --version`, `nx --help`,  and `nx report` should work to show version information even if the cli tool can't detect an nx workspace. 

This will help with future troubleshooting.

### Steps to Reproduce

1. run `nx --version` in a directory where nx can't find a workspace.

### Nx Report

```shell
The proper, up-to-date version of nx:

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin x64
   npm    : 9.5.1
   Hasher : Native
   
   nx (global)        : 16.1.3
   nx                 : 16.1.3
   @nx/js             : 16.1.3
   @nx/jest           : 16.1.3
   @nx/linter         : 16.1.3
   @nx/workspace      : 16.1.3
   @nx/angular        : 16.1.3
   @nx/cypress        : 16.1.3
   @nx/devkit         : 16.1.3
   @nx/eslint-plugin  : 16.1.3
   @nx/plugin         : 16.1.3
   @nx/storybook      : 16.1.3
   @nx/webpack        : 16.1.3
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @ngneat/spectator  : 14.0.0
   @rx-angular/state  : 1.7.0
   @storybook/angular : 7.0.10
   angular-calendar   : 0.31.0
   ng2-charts         : 4.1.1
   ---------------------------------------
   Local workspace plugins:
         @galaxy/workspace-plugin
```

Where as the version of `nx` that was being used by npm outputs
```
 nx report


>  NX  The current directory isn't part of an Nx workspace.

  To create a workspace run:
  npx create-nx-workspace@latest <workspace name>


>  NX   NOTE  For more information please visit https://nx.dev/
```
```


### Failure Logs

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by joelkesler** [comment]
This happened during our upgrade to nx 16 and Angular 16.  An old dependency (`@nrwl/schematics`) was not removed and was overriding the project's version of the `nx` cli when any npm commands were run, causing confusion.

**Comment by AgentEnder** [comment]
`report` and `--help` will still not work, but I don't think they really should. `--version` should be fixed by the linked PR.

**Comment by joelkesler** [comment]
Thanks! That is very helpful
