### ISSUE TITLE
Running Nestjs application on Nx 16.1.4 

### ISSUE THREAD

**Issue by elviscoly** [nrwl/nx#16914]
### Current Behavior

I'm trying to run nx serve api on my nx monorepo application.

### Expected Behavior

Suppose to run successful

### Steps to Reproduce

1.
Error: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

### Nx Report

```shell
Error: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```

### Failure Logs

```shell
Error: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by danielritter** [comment]
Duplicates https://github.com/nrwl/nx/issues/16908 https://github.com/nrwl/nx/issues/16834 https://github.com/nrwl/nx/pull/16911 https://github.com/nrwl/nx/issues/16847

**Comment by davidzem** [comment]
I have the same issue , my node version  19.9.0 , 
![nxNestError](https://github.com/nrwl/nx/assets/73611795/b4f3d52f-8cd0-46fc-9092-be581b76d876)

**Comment by AgentEnder** [comment]
Hey 👋 I'm closing this out since its a duplicate and already solved. Stay tuned for next release 📺
