### ISSUE TITLE
Integrating Vite and Vitest with Angular in Nx: Any Examples?

### ISSUE THREAD

**Issue by jon9090** [nrwl/nx#16939]
Is it possible to use Vite and Vitest in conjunction with Angular within Nx? If so, are there any existing examples available?

Can I use Vitest as a substitute for Jest in projects involving Node.js, Nest.js, Angular, or similar frameworks?

**Comment by Coly010** [comment]
We currently do not have support for it, but you may be interested in the following project that does: https://analogjs.org/
