### ISSUE TITLE
8.4.4 running 1 tests (webstorm), runs them all, but the earlier issues are fixed

### ISSUE THREAD

**Issue by appsolutegeek** [nrwl/nx#1693]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Choosing one test, should only run / debug 1 test.. i.e.

![image](https://user-images.githubusercontent.com/2370364/62598963-3f47b480-b8eb-11e9-8bae-0bf43461c56a.png)

## Current Behavior

Currnetly it runs ALL tests but DEBUG does work etc

![image](https://user-images.githubusercontent.com/2370364/62598940-2ccd7b00-b8eb-11e9-86fb-1060aff2e697.png)

This was the latest PR to hit, done by @vsavkin , which fixed the majority of issues https://github.com/nrwl/nx/pull/1657

## Failure Information (for bugs)

Choosing just 1 test, actually runs them all - but debugging seems to work which is a plus because previous they didn't

Previously you wasn't able to even run tests, 2 pul requests were released and it now seems to be in a better place - but still not running as expected.

### Steps to Reproduce

See above images for info

### Context

Please provide any relevant information about your setup:

- version of Nx used 8.4.4

**Comment by appsolutegeek** [comment]
I specifically chose to run just 1 test in debug, it started running all other tests but sure enough when it eventually got to mind, the debug breakpoint was stopped upon.

But running previous tests takes a long while to just get to the test i was interested in.

**Comment by sroettering** [comment]
I upgraded nx to v8.4.4 and tested running a single test with intellij ultimate 2019.2.

![image](https://user-images.githubusercontent.com/2598613/62607501-77a4be00-b8fe-11e9-84b0-f4769ad49cb9.png)

intellij seems to list more tests than it executed but the execution times next to the tests indicate that only one test case was executed.

I also changed another test (which is listed in the results) to always fail. Overall test result from running the single test case was green, though. So I assume this is a display problem from intellij/webstorm.

**Comment by appsolutegeek** [comment]
Thanks for the feedback - yes this does seems to be the case :-( Ok I think we can close this unless anybody else sees any issues ?

**Comment by mehrad-rafigh** [comment]
Yes I think we should close this. It works as expected, but there is a UI Bug in the IntelliJ Product Line

**Comment by appsolutegeek** [comment]
Sure, I will close this as i was the original reporter. Thanks everyone for the help and confirmation.

**Comment by dgsmith2** [comment]
Are we sure this was fixed?  It seems that `testPathPattern` is not being honored and all the other tests are processed only to be skipped, thus the "display problem" @sroettering mentions.

**Comment by dgsmith2** [comment]
Create PR #1854 to address the remaining issue.
