### ISSUE TITLE
Unable to create @nx/node:app in an integrated repo

### ISSUE THREAD

**Issue by cjbland** [nrwl/nx#16941]
### Current Behavior

When trying to add an "app" to an integrated repo after creating the workspace, the "generate" command fails because it cannot find a tsconfig.json file

### Expected Behavior

I would expect `nx generate @nx/node:app appname` to complete successfully.

### Steps to Reproduce

1.  npx create-nx-workspace@latest testrepo
2. Select "integrated", then "apps", then "no" to faster builds
3. cd testrepo
4. npx nx generate @nx/node:app core

The error appears after running the last command.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.12.1
   OS     : linux x64
   npm    : 8.19.2
   Hasher : Native

   nx             : 16.1.4
   @nx/workspace  : 16.1.4
   @nx/devkit     : 16.1.4
   @nrwl/tao      : 16.1.4
```

### Failure Logs

```shell
[usser@hostname testrepo]$ npx nx generate @nx/node:app core

 >  NX   Unable to resolve @nx/node:app.

   unable to find tsconfig.base.json or tsconfig.json
   Pass --verbose to see the stacktrace.
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by cjbland** [comment]
For what it's worth, trying to go the "ts" route fails with a different error:

  1. `npx create-nx-workspace@latest testrepo`
  2. Select "integrated", then "ts", then "no" for faster builds
  3. `cd testrepo`
  4. `npx nx generate @nx/node:app core`

That will give the following error:

```
 >  NX   Unable to resolve @nx/node:app.

   Cannot find module '@nx/node/package.json'
   Require stack:
   - /home/ec2-user/code/testrepo/node_modules/nx/src/utils/package-json.js
   - /home/ec2-user/code/testrepo/node_modules/nx/src/utils/package-manager.js
   - /home/ec2-user/code/testrepo/node_modules/nx/bin/init-local.js
   - /home/ec2-user/code/testrepo/node_modules/nx/bin/nx.js
   Pass --verbose to see the stacktrace.
```

**Comment by StalkAltan** [comment]
Hi @cjbland 

Based on `nx report`, it looks like you need to install the `@nx/node` package first. Can you give that a try and let us know if the issue still persists?
