### ISSUE TITLE
Application name is not taken into account when creating workspace

### ISSUE THREAD

**Issue by jospotargent** [nrwl/nx#1694]
## Expected Behavior

Executing  "npx create-nx-workspace@8.4.4 someproject --preset angular"
Gives the following prompts (and giving the answers at the end):
? Application name                               someapp
? Which stylesheet format would you like to use? SASS(.scss)  [ http://sass-lang.com   ]

I expect a folder someproject be created (it does) and in there in the apps folder 2 subfolders with name "someapp" and "someapp-e2e", containing the correct items (not correct).

## Current Behavior

It creates in the apps folder 2 subfolders called "undefined" and "undefined-e2e". Those folders contain items.

## Failure Information (for bugs)

npx create-nx-workspace@8.4.4 someproject --preset angular
npx: installed 168 in 16.584s
? Application name                               someapp
? Which stylesheet format would you like to use? SASS(.scss)  [ http://sass-lang.com   ]
Creating a sandbox with Nx...
added 326 packages from 218 contributors and audited 3105 packages in 17.073s
found 0 vulnerabilities

new someproject "--preset" "angular" --style=scss --collection=@nrwl/workspace
CREATE someproject/nx.json (202 bytes)
CREATE someproject/tsconfig.json (509 bytes)
CREATE someproject/package.json (1200 bytes)
CREATE someproject/README.md (2698 bytes)
CREATE someproject/.editorconfig (245 bytes)
CREATE someproject/.gitignore (503 bytes)
CREATE someproject/.prettierignore (57 bytes)
CREATE someproject/.prettierrc (26 bytes)
CREATE someproject/angular.json (96 bytes)
CREATE someproject/apps/.gitkeep (1 bytes)
CREATE someproject/libs/.gitkeep (0 bytes)
CREATE someproject/tools/tsconfig.tools.json (218 bytes)
CREATE someproject/tools/schematics/.gitkeep (0 bytes)
CREATE someproject/.vscode/extensions.json (164 bytes)

> core-js-pure@3.1.4 postinstall C:\Users\jptr\Documents\projects\crbp\gitlab\crbp\someproject\node_modules\core-js-pure
> node scripts/postinstall || echo "ignore"

> @angular/cli@8.1.1 postinstall C:\Users\jptr\Documents\projects\crbp\gitlab\crbp\someproject\node_modules\@angular\cli
> node ./bin/postinstall/script.js

npm WARN @cypress/webpack-preprocessor@4.1.0 requires a peer of webpack@^4.18.1 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@8.0.6 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.

added 594 packages from 326 contributors and audited 5691 packages in 31.746s
found 0 vulnerabilities

CREATE jest.config.js (275 bytes)
CREATE tslint.json (2214 bytes)
CREATE apps/undefined/tsconfig.json (123 bytes)
CREATE apps/undefined-e2e/tslint.json (48 bytes)
CREATE apps/undefined-e2e/cypress.json (365 bytes)
CREATE apps/undefined-e2e/tsconfig.e2e.json (152 bytes)
CREATE apps/undefined-e2e/tsconfig.json (126 bytes)
CREATE apps/undefined-e2e/src/fixtures/example.json (80 bytes)
CREATE apps/undefined-e2e/src/integration/app.spec.ts (226 bytes)
CREATE apps/undefined-e2e/src/plugins/index.js (811 bytes)
CREATE apps/undefined-e2e/src/support/app.po.ts (47 bytes)
CREATE apps/undefined-e2e/src/support/commands.ts (838 bytes)
CREATE apps/undefined-e2e/src/support/index.ts (599 bytes)
CREATE apps/undefined/browserslist (429 bytes)
CREATE apps/undefined/tsconfig.app.json (193 bytes)
CREATE apps/undefined/tslint.json (203 bytes)
CREATE apps/undefined/src/favicon.ico (5430 bytes)
CREATE apps/undefined/src/index.html (340 bytes)
CREATE apps/undefined/src/main.ts (375 bytes)
CREATE apps/undefined/src/polyfills.ts (2836 bytes)
CREATE apps/undefined/src/styles.css (80 bytes)
CREATE apps/undefined/src/assets/.gitkeep (0 bytes)
CREATE apps/undefined/src/environments/environment.prod.ts (51 bytes)
CREATE apps/undefined/src/environments/environment.ts (662 bytes)
CREATE apps/undefined/src/app/app.module.ts (297 bytes)
CREATE apps/undefined/src/app/app.component.html (632 bytes)
CREATE apps/undefined/src/app/app.component.spec.ts (982 bytes)
CREATE apps/undefined/src/app/app.component.ts (221 bytes)
CREATE apps/undefined/src/app/app.component.css (0 bytes)
CREATE apps/undefined/tsconfig.spec.json (233 bytes)
CREATE apps/undefined/jest.config.js (267 bytes)
CREATE apps/undefined/src/test-setup.ts (30 bytes)
UPDATE angular.json (4045 bytes)
UPDATE package.json (1918 bytes)
UPDATE nx.json (294 bytes)
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()

etc...

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Executing  "npx create-nx-workspace@8.4.4 someproject --preset angular"
2. answer to the prompts:
? Application name                               someapp
? Which stylesheet format would you like to use? SASS(.scss)  [ http://sass-lang.com   ]

### Context

Please provide any relevant information about your setup:

- Nx 8.4.4

**Comment by vsavkin** [comment]
Thank you for filing the issue. I fixed here: https://github.com/nrwl/nx/pull/1697
