### ISSUE TITLE
Importing file with "user server" directive from lib in a Next.js app results in error: Module parse failed: Identifier 'callServer' has already been declared

### ISSUE THREAD

**Issue by amosbastian** [nrwl/nx#16956]
### Current Behavior

Getting this error when trying to use [zact](https://github.com/pingdotgg/zact) in an Nx monorepo, but only when putting it in a separate lib:

```
error - ../../libs/feature/src/lib/action.ts
Module parse failed: Identifier 'callServer' has already been declared (8:9)
| }
|
> import { callServer } from "next/dist/client/app-call-server";
| function __build_action__(action, args) {
|     return callServer(action.$$id, args);

Import trace for requested module:
../../libs/feature/src/lib/action.ts
../../libs/feature/src/lib/t3test.tsx
```

I'm using the same component as the example app in their repository

```ts
// This doesn't work:
import { T3TestComponent } from '@zact-nx/feature';

// This works:
// import { T3TestComponent } from './t3test';

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <T3TestComponent />
    </main>
  );
}
```

If I put the action and client component in the app directory and import that, it works fine. If I put it in a different lib and import it from there, it does not work.

As a side note, I also noticed that the example app has `transpilePackages: ['zact']` in its `next.config.js`, but if I set that, then I get this error:

```
../../libs/feature/src/lib/t3test.tsx
ReactServerComponentsError:

The "use client" directive must be placed before other expressions. Move it to the top of the file to resolve this issue.

   ╭─[/Users/amosbastian/Development/zact-nx/node_modules/zact/client.mjs:1:1]
 1 │ // client.ts
 2 │ import { useMemo, useRef, useState } from "react";
 3 │ "use client";
   · ─────────────
 4 │ function useZact(action) {
 5 │   const doAction = useRef(action);
 6 │   const [data, setData] = useState(null);
   ╰────

The error was caused by importing 'zact/client.mjs' in '../../libs/feature/src/lib/t3test.tsx'.

Import path:
  ../../libs/feature/src/lib/t3test.tsx
```

### Expected Behavior

If I put the files in the same folder as the Next.js app it works fine, so I expect it to work when putting in a separate lib too. In this case it somehow works fine when removing the "use server" directive, but obviously when actually using server code this wouldn't work.

### GitHub Repo

https://github.com/amosbastian/zact-nx

### Steps to Reproduce

```
npm i
npx nx serve web
```

and visit http://localhost:4200

### Nx Report

```shell
Node   : 18.14.0
   OS     : darwin arm64
   npm    : 9.3.1
   Hasher : Native

   nx                 : 16.1.4
   @nx/js             : 16.1.4
   @nx/jest           : 16.1.4
   @nx/linter         : 16.1.4
   @nx/workspace      : 16.1.4
   @nx/cypress        : 16.1.4
   @nx/devkit         : 16.1.4
   @nx/eslint-plugin  : 16.1.4
   @nx/next           : 16.1.4
   @nx/react          : 16.1.4
   @nrwl/tao          : 16.1.4
   @nx/web            : 16.1.4
   typescript         : 5.0.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by amosbastian** [comment]
I confirmed that it has nothing to do with the `zact` package as the same happens with normal server actions described here: https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions

**Comment by alanmontgomery** [comment]
I'm also seeing this issue. Is there any further progress on this bug? All i'm doing is calling a server action function that lives in a lib.

If i bring that action into the app itself, it works.

**Comment by amosbastian** [comment]
I'm going to try a package based monorepo setup instead of an integrated one and see if it makes any difference
