### ISSUE TITLE
generating library with --unitTestRunner=karma fails

### ISSUE THREAD

**Issue by DmitryEfimenko** [nrwl/nx#16950]
### Current Behavior

> nx -- g @nx/angular:library karma-test --publishable  --unitTestRunner=karma  -d

> Property 'unitTestRunner' does not match the schema. 'karma' should be one of jest,none

### Expected Behavior

should work

### Steps to Reproduce

1. Run the command 👆

### Nx Report

```shell
npm    : 8.19.2
Hasher : Native

nx                 : 16.1.4
@nx/js             : 16.1.4
@nx/jest           : 16.1.4
@nx/linter         : 16.1.4
@nx/workspace      : 16.1.4
@nx/angular        : 16.1.4
@nx/cypress        : 16.1.4
@nx/devkit         : 16.1.4
@nx/eslint-plugin  : 16.1.4
@nrwl/tao          : 16.1.4
@nx/webpack        : 16.1.4
nx-cloud           : 16.0.5
typescript         : 5.0.4
---------------------------------------
Community plugins:
@jscutlery/semver   : 2.30.1
@ngneat/spectator   : 14.0.0
angular-cli-ghpages : 1.0.6
ng-mocks            : 14.10.0
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Karma generation support has been intentionally removed from Nx. However, Karma can still work in an Nx Workspace. We just don’t provide generators to do the setup for you. You can still set up Karma and use Angular’s karma builder to run your tests.

But as an organization, we’ve moved away from generating Karma support and as @Olster has stated, Angular has also indicated that they will be transitioning away from Karma. 

Nx has always preferred and defaulted to Jest for unit testing. We do offer multiple-version support for Angular. Still, part of the mentality for that is that you can get the latest security patches, fixes, performance and features from the latest versions of Nx without having to upgrade your Angular version.

We have always moved a bit faster than the Angular team itself when it comes to tooling and patterns. With the Angular team investigating Jest support themselves, it’s another indication of the direction in which Angular is moving. For example, we had support for generating Standalone applications for months before Angular decided to also provide support for it. This is another case of where we are simply moving slightly faster.

You can take a look at the Karma generators we had here:

https://github.com/nrwl/nx/tree/15.9.x/packages/angular/src/generators/karma-project
https://github.com/nrwl/nx/tree/15.9.x/packages/angular/src/generators/karma

And you can create your own local Nx Plugin with replica generators to do this for you if you wish to continue to use Karma.
