### ISSUE TITLE
@nrwl/angular is being added to dependencies in package.json

### ISSUE THREAD

**Issue by tthrash** [nrwl/nx#1695]
When I run `yarn add @nrwl/angular` @nrwl/angular is being added to dependencies in package.json. Shouldn't this be a devDependency? I should also note that @nrwl/angular is on version 8.4.x.  I tested this with @nrwl/cli installed globally via yarn. I tried both 8.4.x and 8.3.0 versions with the same result (global @nrwl/cli).

**Comment by tthrash** [comment]
In the latest release, this is no longer occurring. Closing this issue.

**Comment by skorunka** [comment]
What if you do `import { DataPersistence } from '@nrwl/angular';` and use `DataPersistence ` in your effects. Should `@nrwl/angular` still go to devDependencies?
