### ISSUE TITLE
NextJS 13.4 and NX cause warning 'Detect multiple renderers concurrently'

### ISSUE THREAD

**Issue by sergio-milu** [nrwl/nx#16964]
### Current Behavior

I'm in NX 16.1.4 and I updated from NextJS 13.3 to 13.4.1, since them, when I start the dev server, I'm seen the following warnings in routes under app/ directory.

```
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
    at Router (webpack-internal:///(sc_client)/../../node_modules/next/dist/client/components/app-router.js:86:11)
    at ErrorBoundaryHandler (webpack-internal:///(sc_client)/../../node_modules/next/dist/client/components/error-boundary.js:62:9)
    at ErrorBoundary (webpack-internal:///(sc_client)/../../node_modules/next/dist/client/components/error-boundary.js:86:11)
    at AppRouter (webpack-internal:///(sc_client)/../../node_modules/next/dist/client/components/app-router.js:359:13)
    at Lazy
    at Lazy
    at ServerComponentWrapper (/Users/sergiofernandez/Repositories/milu-web/node_modules/next/dist/server/app-render/create-server-components-renderer.js:78:31)
    at ServerComponentWrapper (/Users/sergiofernandez/Repositories/milu-web/node_modules/next/dist/server/app-render/create-server-components-renderer.js:78:31)
    at InsertedHTML (/Users/sergiofernandez/Repositories/milu-web/node_modules/next/dist/server/app-render/app-render.js:835:33)

Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
    at AppContainer (/Users/sergiofernandez/Repositories/milu-web/node_modules/next/dist/server/render.js:337:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/sergiofernandez/Repositories/milu-web/node_modules/next/dist/server/render.js:373:57)
    at div
    at Body (/Users/sergiofernandez/Repositories/milu-web/node_modules/next/dist/server/render.js:673:21)

Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
    at PathnameContextProviderAdapter (/Users/sergiofernandez/Repositories/milu-web/node_modules/next/dist/shared/lib/router/adapters.js:78:11)
    at AppContainer (/Users/sergiofernandez/Repositories/milu-web/node_modules/next/dist/server/render.js:337:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/sergiofernandez/Repositories/milu-web/node_modules/next/dist/server/render.js:373:57)
    at div
    at Body (/Users/sergiofernandez/Repositories/milu-web/node_modules/next/dist/server/render.js:673:21)
```

why I think this is a NX issue?
because I changed from using the nx next server to the nextjs server (using npm run dev) and all works as expected. Also try to reproduce this creating a new nextjs app without NX.

### Expected Behavior

Not show any warning at all.

### Steps to Reproduce

Create a NX app with latest NextJS version. 
Boot the dev server using `const { withNx } = require('@nx/next/plugins/with-nx');` in next.config.js and `nx serve` command.
Create a route under /app directory
Start playing around with the url (I see this happening when refreshing cleaning the browser cache or going from one page to another, event to pages that don't exists that show the 404 default view). 

### Nx Report

```shell
Report complete - copy this into the issue template

   Node   : 18.15.0
   OS     : darwin arm64
   npm    : 9.5.0
   Hasher : Native
   
   nx                 : 16.1.4
   @nx/js             : 16.1.4
   @nx/jest           : 16.1.4
   @nx/linter         : 16.1.4
   @nx/workspace      : 16.1.4
   @nx/cypress        : 16.1.4
   @nx/devkit         : 16.1.4
   @nrwl/devkit       : 15.9.4
   @nx/eslint-plugin  : 16.1.4
   @nx/nest           : 16.1.4
   @nx/next           : 16.1.4
   @nx/node           : 16.1.4
   @nx/plugin         : 16.1.4
   @nx/react          : 16.1.4
   @nrwl/tao          : 16.1.4
   @nx/web            : 16.1.4
   @nx/webpack        : 16.1.4
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @mands/nx-playwright   : 0.4.0
   @nx-tools/nx-container : 4.0.3
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/devkit@15.9.4
   
   To fix this, run `nx migrate nx@16.1.4`
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
Do you have `experimental.serverActions` enabled, and are you setting the `__NEXT_PRIVATE_PREBUNDLED_REACT` environment variable anywhere?

**Comment by sergio-milu** [comment]
> Do you have `experimental.serverActions` enabled, and are you setting the `__NEXT_PRIVATE_PREBUNDLED_REACT` environment variable anywhere?

No, I dont have `experimental.serverActions`, and neither setting `__NEXT_PRIVATE_PREBUNDLED_REACT`  anywhere

**Comment by jaysoo** [comment]
Can you set `__NEXT_PRIVATE_PREBUNDLED_REACT=next`, for example in your `.env` file and see if that helps?

I have this example using Next.js 13.4.1 and Nx 16.1.4 and I'm not seeing the warnings. https://github.com/jaysoo/example-16964

Do you have a repo I can check?

**Comment by king0120** [comment]
I have also been experiencing this issue when migrating some of my new code to the app router.  Even with the `__NEXT_PRIVATE_PREBUNDLED_REACT=next` env variable set.  It's been very difficult to track down exactly what is happening here. 

I will note that when looking at the @next/bundle-analyzer output, it seems to be duplicating a lot of npm modules into each page component.

**Comment by sergio-milu** [comment]
> Can you set `__NEXT_PRIVATE_PREBUNDLED_REACT=next`, for example in your `.env` file and see if that helps?
> 
> I have this example using Next.js 13.4.1 and Nx 16.1.4 and I'm not seeing the warnings. https://github.com/jaysoo/example-16964
> 
> Do you have a repo I can check?

Hi, I've just reproduce the issue with your repo, just clone it, run `npm i` and `npx nx serve`, open the page and there is the error (see screenshot)
<img width="741" alt="Screenshot 2023-05-11 at 22 06 10" src="https://github.com/nrwl/nx/assets/129851693/70a7aef1-c425-423f-b01a-e9793a32dc93">

**Comment by king0120** [comment]
One thing that I just noticed is that this message seems to always be preceded by 
`wait compiling /_error (client and server)...`

This file doesn't exist in my app or pages directory, so I imagine it's being pull from next itself?

<img width="855" alt="Screenshot 2023-05-11 at 4 57 18 PM" src="https://github.com/nrwl/nx/assets/7226194/46284580-f215-4b2b-b6e2-f5cb0d9a0010">

**Comment by vitosnatios** [comment]
Hey there! Before I start, my current Version is:  
```js
"next": "13.4.1",
"react": "18.2.0",
```

Im with a similar problem, the error is:
```node
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
    at AppContainer (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:337:29)
    at AppContainerWithIsomorphicFiberStructure (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:373:57)
    at div
    at Body (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:673:21)
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
    at AppContainer (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:337:29)
    at AppContainerWithIsomorphicFiberStructure (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:373:57)
    at div
    at Body (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:673:21)
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
    at PathnameContextProviderAdapter (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\shared\lib\router\adapters.js:78:11)
    at AppContainer (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:337:29)
    at AppContainerWithIsomorphicFiberStructure (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:373:57)
    at div
    at Body (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:673:21)
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
    at PathnameContextProviderAdapter (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\shared\lib\router\adapters.js:78:11)
    at AppContainer (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:337:29)
    at AppContainerWithIsomorphicFiberStructure (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:373:57)
    at div
    at Body (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:673:21
```
In my case, thats the context of the problem:
I do have a nested route that includes a Form component that uses the experimental "server actions".
This error occurs everytime i do submit this form.
Thats the nested route code:
```tsx
import PostsFromThisPage from '@/app/components/pages/board/PostsFromThisPage';
import { Metadata } from 'next';

export const metadata: Metadata = {
  description:
    'A board that contains a list of threads with random content and cat images',
};

const pages = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'];

export const dynamicParams = false;

export const generateStaticParams = () => {
  return pages.map((page) => ({ pageNumber: page }));
};

export const revalidate = 10;

const HelloWorldPage = ({ params }: { params: { pageNumber: string } }) => {
  if (pages.includes(params.pageNumber)) {
    const page = Number(params.pageNumber);
    metadata.title = `Hello, World! Página ${page}`;
    return <PostsFromThisPage page={page} />;
  }
};

export default HelloWorldPage;

```
Obs: Whenever I do remove the "generateStaticParams"/"dynamicParams" and the routes goes from static to dynamic again, the Form starts working again without this error, but i do want it to be static, so i can use the revalidatePath() to perform the "on-demand revalidation" after every Form submit.
The form code:
```tsx
'use client';
import FormTextarea from './FormTextarea';
import Input from './Input';
import classes from './Form.module.css';
import Button from './Button';
import Reminder from './Reminder';
import Centralizer from '@/app/components/layout/Centralizer';
import { useRef } from 'react';
import { addReply, addThread } from '@/serverActions/actions';
import { useRouter } from 'next/navigation';

type Props = { op: boolean; threadNumber?: number };

export const dynamic = 'force-dynamic';

const Form = ({ op, threadNumber }: Props) => {
  const emailRef = useRef<HTMLInputElement>(null);
  const assuntoRef = useRef<HTMLInputElement>(null);
  const postContentRef = useRef<HTMLTextAreaElement>(null);
  const passwordRef = useRef<HTMLInputElement>(null);
  const router = useRouter();

  const clearInputs = () => {
    if (
      emailRef.current instanceof HTMLInputElement &&
      assuntoRef.current instanceof HTMLInputElement &&
      postContentRef.current instanceof HTMLTextAreaElement &&
      passwordRef.current instanceof HTMLInputElement
    ) {
      emailRef.current.value = '';
      assuntoRef.current.value = '';
      postContentRef.current.value = '';
      passwordRef.current.value = '';
    }
  };

  const handleReply = async (formData: FormData) => {
    await addReply(formData, threadNumber as number);
    clearInputs();
    router.push('/hw/1');
  };

  const handleAddThread = async (formData: FormData) => {
    await addThread(formData);
    clearInputs();
  };

  return (
    <Centralizer>
      <form
        action={op ? handleAddThread : handleReply}
        className={classes.form}
      >
        <div className={classes.inputs}>
          <Input
            name='email'
            placeholder='E-mail / sage (Opcional)'
            type='text'
            refProp={emailRef}
          />
          <Input
            name='assunto'
            placeholder='Assunto (Opcional)'
            type='text'
            refProp={assuntoRef}
          />
          <FormTextarea
            name='postContent'
            placeholder='Post (Obrigatório)'
            refProp={postContentRef}
          />
          <Input
            name='password'
            placeholder='Senha (Obrigatório)'
            type='password'
            refProp={passwordRef}
          />
          <div className={classes.checkboxContainer}>
            <input
              id='allowCatImage'
              name='allowCatImage'
              type='checkbox'
              disabled={op}
              defaultChecked={true}
            />
            <label htmlFor='allowCatImage'>Random Cat Images</label>
          </div>
        </div>
        <Button>{op ? 'Novo tópico' : 'Responder'}</Button>
      </form>
      <Reminder />
    </Centralizer>
  );
};

export default Form;
```

**Comment by miroslavrut** [comment]
Having the same issue

next 13.4.2
react 18.2.0
nx 16.1.4

**Comment by datner** [comment]
For what its worth, for me the `__NEXT_PRIVATE_PREBUNDLED_REACT=next` worked 😄

**Comment by sergio-milu** [comment]
> For what its worth, for me the `__NEXT_PRIVATE_PREBUNDLED_REACT=next` worked 😄

this didn't work for me

**Comment by jchamale** [comment]
It's happening to me as well and pages seems to not reload/revalidate content.

**Comment by TobiasViskum** [comment]
I'm experiencing the same issue, but as @vitosnatios mentioned, the error seems to disappear when I remove generateStaticParams.

**Comment by cleverjam** [comment]
I am seeing the same issue, the `__NEXT_PRIVATE_PREBUNDLED_REACT=next` env does not seem to help, I also see the `wait compiling /_error (client and server)...` message before things go south...

**Comment by Brian-McBride** [comment]
I'm not using server actions. I have a route using Trpc, but I don't think that is the issue.

For me, it started when I dropped in a slightly compiled [Jotai](https://jotai.org/) atom. I also find that the dev server crashes out of memory after a while. I also tried to update from node 18 to node 20, just randomly. Same thing there.

Memory Error:
```
<--- Last few GCs --->

[1054:0x130008000]  4236022 ms: Scavenge 4057.7 (4095.5) -> 4053.9 (4096.3) MB, 2.29 / 0.00 ms  (average mu = 0.642, current mu = 0.369) allocation failure;
[1054:0x130008000]  4236247 ms: Mark-Compact (reduce) 4115.4 (4154.4) -> 4090.6 (4133.9) MB, 52.79 / 0.04 ms  (+ 109.8 ms in 14 steps since start of marking, biggest step 26.6 ms, walltime since start of marking 198 ms) (average mu = 0.551, current mu = 0

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10411214c node::Abort() [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
 2: 0x104112334 node::ModifyCodeGenerationFromStrings(v8::Local<v8::Context>, v8::Local<v8::Value>, bool) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
 3: 0x10428f4f4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
 4: 0x104463b9c v8::internal::Heap::GarbageCollectionReasonToString(v8::internal::GarbageCollectionReason) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
 5: 0x104462678 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
 6: 0x104458e90 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
 7: 0x1044596f0 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
 8: 0x10443dfb8 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
 9: 0x104431db0 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
10: 0x104723f70 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocate(v8::internal::Isolate*, int, v8::internal::AllocationType) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
11: 0x1047267ec v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>, int) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
12: 0x104723d5c v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::EnsureGrowable(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
13: 0x10481dcd4 v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
14: 0x104b84c44 Builtins_CEntry_Return1_ArgvOnStack_NoBuiltinExit [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
15: 0x104b5492c Builtins_MapPrototypeSet [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
16: 0x10ad69e68
17: 0x10a0e4b88
18: 0x10a393c2c
19: 0x109fd76f8
20: 0x10a06504c
21: 0x10b191ea0
22: 0x10ad089fc
23: 0x10a51ee30
24: 0x10a0d156c
25: 0x10a0537ec
26: 0x109e61428
27: 0x10a0d19c0
28: 0x10ada8984
29: 0x10a8b0c88
30: 0x10a395bf4
31: 0x10a1abe70
32: 0x109eb3c2c
33: 0x10b24e8b4
34: 0x10a2b588c
35: 0x10a4352a4
36: 0x10a2b6604
37: 0x109b256e8
38: 0x10a4ceb2c
39: 0x104afa50c Builtins_JSEntryTrampoline [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
40: 0x104afa1f4 Builtins_JSEntry [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
41: 0x1043d114c v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
42: 0x1043d0598 v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
43: 0x1042aae80 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
44: 0x104048ff8 node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
45: 0x10405f4c4 node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
46: 0x104117b78 node::fs::FSReqCallback::Resolve(v8::Local<v8::Value>) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
47: 0x1041182a0 node::fs::AfterNoArgs(uv_fs_s*) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
48: 0x10410e078 node::MakeLibuvRequestCallback<uv_fs_s, void (*)(uv_fs_s*)>::Wrapper(uv_fs_s*) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
49: 0x104ad6e5c uv__work_done [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
50: 0x104ada618 uv__async_io [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
51: 0x104aecbcc uv__io_poll [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
52: 0x104adaae8 uv_run [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
53: 0x104049754 node::SpinEventLoopInternal(node::Environment*) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
54: 0x104150124 node::NodeMainInstance::Run() [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
55: 0x1040de44c node::LoadSnapshotDataAndRun(node::SnapshotData const**, node::InitializationResultImpl const*) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
56: 0x1040de76c node::Start(int, char**) [/Users/brianmcbride/.nvm/versions/node/v20.2.0/bin/node]
57: 0x190dd3f28 start [/usr/lib/dyld]
```

**Comment by sergio-milu** [comment]
> Can you set `__NEXT_PRIVATE_PREBUNDLED_REACT=next`, for example in your `.env` file and see if that helps?
> 
> I have this example using Next.js 13.4.1 and Nx 16.1.4 and I'm not seeing the warnings. https://github.com/jaysoo/example-16964
> 
> Do you have a repo I can check?

hey, any updates on this? I reproduced the same error with your own repo in this comment

thanks

**Comment by sameera** [comment]
I'm new to next.js and I just started created a next.js project with nx and added a page using `nx generate` and getting this warning. 
Where would I set 
`__NEXT_PRIVATE_PREBUNDLED_REACT=next`? I don't see a `.env` file in my project folder.

**Comment by chipcullen** [comment]
@sameera you have to create a new file at the root of your application - for local development you would call it ".env.local". https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#loading-environment-variables

**Comment by sameera** [comment]
@chipcullen Thanks so much for the screenshot. Looks the same to me except for the fact that yours seems to be a Next.js only project where mine was generated from NX with typescript. I'm not sure, how much that makes a difference.

**Comment by Brian-McBride** [comment]
Setting `__NEXT_PRIVATE_PREBUNDLED_REACT=next` did not change the issue for me.

**Comment by iquabius** [comment]
I fixed this by moving `apps/web/src/pages/404.tsx` to `apps/web/src/app/NotFoundPage.tsx` and added the `"use client"` directive:

![image](https://github.com/nrwl/nx/assets/3139777/61e967c9-6413-4889-a3af-e3128eac69c5)

Then I rendered the `<NotFoundPage />` in `apps/web/src/app/not-found.tsx`:

```tsx
import type { NextPage } from "next";
import { NotFoundPage } from "./NotFoundPage";

const NotFound: NextPage = () => {
  return <NotFoundPage />;
};

export default NotFound;
```

I could not make the `useMediaQuery()` work though, maybe `<NoSsr />` could help here, but I didn't try it yet.

**Comment by miroslavrut** [comment]
@iquabius thanks a ton!
this did it for me. Just created a custom not found page similarly and it solved bunch of issues, including these multiple rendering one

**Comment by amir-khoshbakht** [comment]
> I'm new to next.js and I just started created a next.js project with nx and added a page using `nx generate` and getting this warning. Where would I set `__NEXT_PRIVATE_PREBUNDLED_REACT=next`? I don't see a `.env` file in my project folder.

.env Worked for me 👌👌👌
I created an .env file in the repository _"root path"_ (where is NX.json) and put the mentioned line in it and it no longer shows that message:
```ts
__NEXT_PRIVATE_PREBUNDLED_REACT=next
```
you probably need to restart your next.js project

**Comment by amir-khoshbakht** [comment]
> @iquabius thanks a ton! this did it for me. Just created a custom not found page similarly and it solved bunch of issues, including these multiple rendering one

✅ creating "not-found.tsx" or "not-found.js" also works for me.
the .env method didnt work !

**Comment by sergio-milu** [comment]
> I fixed this by moving `apps/web/src/pages/404.tsx` to `apps/web/src/app/NotFoundPage.tsx` and added the `"use client"` directive:
> 
> ![image](https://user-images.githubusercontent.com/3139777/241341667-61e967c9-6413-4889-a3af-e3128eac69c5.png)
> 
> Then I rendered the `<NotFoundPage />` in `apps/web/src/app/not-found.tsx`:
> 
> ```tsx
> import type { NextPage } from "next";
> import { NotFoundPage } from "./NotFoundPage";
> 
> const NotFound: NextPage = () => {
>   return <NotFoundPage />;
> };
> 
> export default NotFound;
> ```
> 
> I could not make the `useMediaQuery()` work though, maybe `<NoSsr />` could help here, but I didn't try it yet.

more than a fix I would say that is a work around, this shouldn't be needed, as this issue is not happening to me in a project without nx.

(an yes, you cannot use useMediaQuery in server-side components)

**Comment by sameera** [comment]
> more than a fix I would say that is a work around, this shouldn't be needed, as this issue is not happening to me in a project without nx.

I must agree. It takes minimal steps to run in to this issue:
1. Create a new NX repo with a Next.js app
2. Add a page
3. Build, serve and navigate to the newly added page.

It's too much to leave to a novice to workaround an issue at this early stage fo te project.

**Comment by Brian-McBride** [comment]
When I added a `not-found.tsx` page to my app dir, the error seems to have gone. 
I still have some BS error about __typedef because Next shoves in some lame info into your exports file when using an external lib. If Astro gets a client-side router in place, I'm bailing hard on NextJS. They keep building this framework on the assumption that you only use their tools, their way, and only deploy on Vercel. 

Thanks for the find @iquabius, on the not-found file. This is highly likely not an Nx issue at all, and just some random error inside of NextJS.

**Comment by sergio-milu** [comment]
> Thanks for the find @iquabius, on the not-found file. This is highly likely not an Nx issue at all, and just some random error inside of NextJS.

you sure? did you test a NextJS app without NX? I created a next app, run it with its own dev server and couldn't reproduce this issue (maybe I missed something), so it doesn't seem a next issue

**Comment by king0120** [comment]
I recently installed one of the beta's for NX 16.3, in the upcoming version NX uses the `next` CLI directly instead of the custom server. This has seemed to fix most of my issues!

**Comment by sergio-milu** [comment]
just tested with the latest version (16.3.0) and the error seems to be fixed now

**Comment by sameera** [comment]
> just tested with the latest version (16.3.0) and the error seems to be fixed now

I can confirm this too. Did a `nx migrate latest` and followed through. No longer seeing the issue.

**Comment by Mamenzul** [comment]
> Hey there! Before I start, my current Version is:
> 
> ```js
> "next": "13.4.1",
> "react": "18.2.0",
> ```
> 
> Im with a similar problem, the error is:
> 
> ```js
> Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
>     at AppContainer (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:337:29)
>     at AppContainerWithIsomorphicFiberStructure (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:373:57)
>     at div
>     at Body (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:673:21)
> Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
>     at AppContainer (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:337:29)
>     at AppContainerWithIsomorphicFiberStructure (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:373:57)
>     at div
>     at Body (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:673:21)
> Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
>     at PathnameContextProviderAdapter (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\shared\lib\router\adapters.js:78:11)
>     at AppContainer (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:337:29)
>     at AppContainerWithIsomorphicFiberStructure (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:373:57)
>     at div
>     at Body (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:673:21)
> Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
>     at PathnameContextProviderAdapter (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\shared\lib\router\adapters.js:78:11)
>     at AppContainer (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:337:29)
>     at AppContainerWithIsomorphicFiberStructure (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:373:57)
>     at div
>     at Body (C:\Users\Vitor\Desktop\imageboard\next-js-imageboard\node_modules\next\dist\server\render.js:673:21
> ```
> 
> In my case, thats the context of the problem: I do have a nested route that includes a Form component that uses the experimental "server actions". This error occurs everytime i do submit this form. Thats the nested route code:
> 
> ```tsx
> import PostsFromThisPage from '@/app/components/pages/board/PostsFromThisPage';
> import { Metadata } from 'next';
> 
> export const metadata: Metadata = {
>   description:
>     'A board that contains a list of threads with random content and cat images',
> };
> 
> const pages = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'];
> 
> export const dynamicParams = false;
> 
> export const generateStaticParams = () => {
>   return pages.map((page) => ({ pageNumber: page }));
> };
> 
> export const revalidate = 10;
> 
> const HelloWorldPage = ({ params }: { params: { pageNumber: string } }) => {
>   if (pages.includes(params.pageNumber)) {
>     const page = Number(params.pageNumber);
>     metadata.title = `Hello, World! Página ${page}`;
>     return <PostsFromThisPage page={page} />;
>   }
> };
> 
> export default HelloWorldPage;
> ```
> 
> Obs: Whenever I do remove the "generateStaticParams"/"dynamicParams" and the routes goes from static to dynamic again, the Form starts working again without this error, but i do want it to be static, so i can use the revalidatePath() to perform the "on-demand revalidation" after every Form submit. The form code:
> 
> ```tsx
> 'use client';
> import FormTextarea from './FormTextarea';
> import Input from './Input';
> import classes from './Form.module.css';
> import Button from './Button';
> import Reminder from './Reminder';
> import Centralizer from '@/app/components/layout/Centralizer';
> import { useRef } from 'react';
> import { addReply, addThread } from '@/serverActions/actions';
> import { useRouter } from 'next/navigation';
> 
> type Props = { op: boolean; threadNumber?: number };
> 
> export const dynamic = 'force-dynamic';
> 
> const Form = ({ op, threadNumber }: Props) => {
>   const emailRef = useRef<HTMLInputElement>(null);
>   const assuntoRef = useRef<HTMLInputElement>(null);
>   const postContentRef = useRef<HTMLTextAreaElement>(null);
>   const passwordRef = useRef<HTMLInputElement>(null);
>   const router = useRouter();
> 
>   const clearInputs = () => {
>     if (
>       emailRef.current instanceof HTMLInputElement &&
>       assuntoRef.current instanceof HTMLInputElement &&
>       postContentRef.current instanceof HTMLTextAreaElement &&
>       passwordRef.current instanceof HTMLInputElement
>     ) {
>       emailRef.current.value = '';
>       assuntoRef.current.value = '';
>       postContentRef.current.value = '';
>       passwordRef.current.value = '';
>     }
>   };
> 
>   const handleReply = async (formData: FormData) => {
>     await addReply(formData, threadNumber as number);
>     clearInputs();
>     router.push('/hw/1');
>   };
> 
>   const handleAddThread = async (formData: FormData) => {
>     await addThread(formData);
>     clearInputs();
>   };
> 
>   return (
>     <Centralizer>
>       <form
>         action={op ? handleAddThread : handleReply}
>         className={classes.form}
>       >
>         <div className={classes.inputs}>
>           <Input
>             name='email'
>             placeholder='E-mail / sage (Opcional)'
>             type='text'
>             refProp={emailRef}
>           />
>           <Input
>             name='assunto'
>             placeholder='Assunto (Opcional)'
>             type='text'
>             refProp={assuntoRef}
>           />
>           <FormTextarea
>             name='postContent'
>             placeholder='Post (Obrigatório)'
>             refProp={postContentRef}
>           />
>           <Input
>             name='password'
>             placeholder='Senha (Obrigatório)'
>             type='password'
>             refProp={passwordRef}
>           />
>           <div className={classes.checkboxContainer}>
>             <input
>               id='allowCatImage'
>               name='allowCatImage'
>               type='checkbox'
>               disabled={op}
>               defaultChecked={true}
>             />
>             <label htmlFor='allowCatImage'>Random Cat Images</label>
>           </div>
>         </div>
>         <Button>{op ? 'Novo tópico' : 'Responder'}</Button>
>       </form>
>       <Reminder />
>     </Centralizer>
>   );
> };
> 
> export default Form;
> ```

Exact same issue, did you solve it ?
