### ISSUE TITLE
Jest-junit reporter configured in 'jest.config.js' is not executed since version 8.4.4

### ISSUE THREAD

**Issue by cbossi** [nrwl/nx#1696]
When I upgrade `@nrwl/jest` from `8.4.3` to `8.4.4`, my configured `jest-junit` reporter is not executed anymore.

When looking at the release notes of `8.4.4`, I assume the problem it is related to this change:
https://github.com/nrwl/nx/commit/ec9ed17
However, when I look at the diff, I cannot explain why the behavior is as described below:

## Expected Behavior

When running `npm test`, the `junit-jest` reporter specified in `jest.config.js` are executed.

## Current Behavior

The the `junit-jest` reporter specified in `jest.config.js` is NOT executed (or at least, no output files are generated).

## Failure Information (for bugs)

My `jest.config.js` looks like the following:
```js
module.exports = {
  testMatch: ['**/+(*.)+(spec|test).+(ts|js)?(x)'],
  transform: {
    '^.+\\.(ts|js|html)$': 'ts-jest'
  },
  resolver: '@nrwl/jest/plugins/resolver',
  moduleFileExtensions: ['ts', 'js', 'html'],
  reporters: [
    "default",
    ["jest-junit", {outputDirectory: "reports/test", outputName: `test-${Date.now()}.xml`}]
  ],
  coverageReporters: ['html']
};
```

The relevant parts of the `package.json`:
```
{
  "scripts": {
    "test": "ng test --passWithNoTests",
  },
  devDependencies {
    "@nrwl/jest": "8.4.4",
    "jest": "24.8.0",
    "jest-junit": "7.0.0",
    "jest-preset-angular": "7.1.1",
  },
}
```

### Steps to Reproduce
1. Upgrade `@nrwl/jest` from `8.4.3` to `8.4.4`
2. Execute `npm run test`

### Context
- Nx version: 8.4.4
- Angular version: 8.2.0

**Comment by vsavkin** [comment]
Thanks for filing the issue. It's a regression. Fixed it here: https://github.com/nrwl/nx/pull/1697

I'll cut a patch release later today.

**Comment by StickNitro** [comment]
I am getting the same issue with `@nrwl/jest @13.4.3`

relevant section from jest.config.js

```
  reporters: [
    'default',
    [
      'jest-junit',
      {
        suiteName: 'cdo-connect-pim Jest Tests',
        outputDirectory: '../../coverage/apps/cdo-connect-pim/junit',
        ancestorSeparator: ' > ',
        usePathForSuiteName: true,
        outputName: 'TESTS.xml'
      }
    ],
    'jest-progress-bar-reporter'
  ]
```

relevant parts from package.json

```
  "scripts": {
    "test": "nx test"
  },
  "devDependencies": {
    "@nrwl/jest": "13.4.3",
    "jest": "27.2.3",
    "jest-junit": "^13.0.0"
  }
```

and the relevant section from angular.json

```
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": ["coverage/apps/cdo-connect-pim"],
          "options": {
            "jestConfig": "apps/cdo-connect-pim/jest.config.js",
            "passWithNoTests": true
          }
        }
```

Running `npx jest --collectCoverage` works and generates the jest-junit output

**Comment by plumcoding** [comment]
I've faced the same issue but `npx jest --collectCoverage` wasn't solution for me because of running in monorepo

If you have **relative path** in the output path like `../../coverage/something` you need to prefix it with `<rootDir>`
```
reporters: [
    'default',
    [
      'jest-junit',
      {
        suiteName: 'some name',
        outputDirectory: '<rootDir>/../../coverage/junit',
      }
    ]
]
```

Have created PR with `README.md` update: [#243](https://github.com/jest-community/jest-junit/pull/243)
