### ISSUE TITLE
NX Cannot find module @angular-devkit/architect

### ISSUE THREAD

**Issue by amirhosseinak20** [nrwl/nx#16979]
### Current Behavior

running angular dev server with `@angular-devkit/build-angular` not working and throws the error 
`NX cannot find module `@angular-devkit/architect`

### Expected Behavior

to run the angular dev server without any error

### GitHub Repo

https://github.com/amirhosseinak20/nx-angular-devkit-architect-error

### Steps to Reproduce

1. npm install
2. npx nx serve nx-angular-devkit-architect

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information
npm version: 9.5.0
node version: 18.15.0

related to https://github.com/nrwl/nx/issues/4636

patches to fix the issue is:
1. using yarn instead of npm
2. install the required `@angular-devkit/architect` version in my case it was:  `"@angular-devkit/architect": "0.1502.4"`

**Comment by Coly010** [comment]
I can't reproduce on MacOS so confirming this is a Windows issue.

Can you try the following:

1. delete node_modules folder
2. `npm cache verify`
3. `npm install`

**Comment by amirhosseinak20** [comment]
the issue fixed with the suggested commands, thanks
