### ISSUE TITLE
@nx/vite:test impossible to use a custom config file located inside a project root

### ISSUE THREAD

**Issue by ClementMindflow** [nrwl/nx#16985]
### Current Behavior

When using @nx/vite:test you can specify a custom file using the `config` option.

Seems like there is a bug when the custom config file is located at the root of the project:

Let's assume we are in a lib called `my-test` in a workspace located at `/User/Marie/Dev` 
The custom config file is located in `/User/Marie/Dev/libs/my-test/vite.config.integration.ts`

If you provide a custom config file like: 

```
"test:integration": {
      "executor": "@nx/vite:test",
      ...
      "options": {
        "config": "vite.config.integration.ts",
      }
    }
```

The "resolved" config file path passed to vitest will be `/User/Marie/Dev/vite.config.integration.ts`
Note that the resolved path is not relative to the lib root but to the workspace root.

The [startVitest function is called](https://github.com/nrwl/nx/blob/e8c31d7ac72a6eeb98d07b61f6ae945a2612d8ac/packages/vite/src/executors/test/vitest.impl.ts#L62) with the following (partial) attributes:

```
{
  config: 'vite.config.integration.ts',
  root: 'libs/my-test',
}
```

So to fix that you'll want to use this path instead:

```
"test:integration": {
      "executor": "@nx/vite:test",
      ...
      "options": {
        "config": "libs/my-test/vite.config.integration.ts",
      }
    }
```

The [startVitest function is called](https://github.com/nrwl/nx/blob/e8c31d7ac72a6eeb98d07b61f6ae945a2612d8ac/packages/vite/src/executors/test/vitest.impl.ts#L62) with the following (partial) attributes:

```
{
  config: 'libs/my-test/vite.config.integration.ts',
  root: 'libs/my-test',
}
```

And since vitest seems to be executed using a PWD equal to the workspace root, it will end up trying to load the following config file:

`/User/Marie/Dev/libs/my-test/libs/my-test/vite.config.integration.ts` which does not exist.

### Expected Behavior

Specifying a custom config file should work no matter where it's located.

### Steps to Reproduce

1. Use a "@nx/vite:test" executor in one of your lib
2. Create a custom vitest config file a the root of your lib
3. try to reference it using the config option

### Nx Report

```shell
Node   : 16.17.1
   OS     : darwin arm64
   yarn   : 1.22.19
   Hasher : Native
   
   nx                 : 16.0.3
   @nx/js             : 16.0.3
   @nx/jest           : 16.0.3
   @nx/linter         : 16.0.3
   @nx/workspace      : 16.0.3
   @nx/devkit         : 16.0.3
   @nx/esbuild        : 16.0.3
   @nx/eslint-plugin  : 16.0.3
   @nx/node           : 16.0.3
   @nx/plugin         : 16.0.3
   @nx/react          : 16.0.3
   @nrwl/tao          : 16.0.3
   @nx/vite           : 16.0.3
   @nx/web            : 16.0.3
   typescript         : 4.9.5
```

### Failure Logs

```shell
✘ [ERROR] Could not resolve "/User/Marie/Dev/libs/my-test/libs/my-test/vite.config.integration.ts"
failed to load config from /User/Marie/Dev/libs/my-test/libs/my-test/vite.config.integration.ts
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

IMHO the fix would be to path an absolute path to the startVitest function:

Adding `config: viteConfigPath,` around the line 113 of packages/vite/src/executors/test/vitest.impl.ts solved the issue for me.

**Comment by i-bajrai** [comment]
Is a work around to this issue? I'm experiencing the same thing and no matter how I change my pathing it keeps dying.

**Comment by kaceycleveland** [comment]
I am also blocked by this; I am working on a work around by just using `vite.config.ts` instead directly and using the `test` field in that. I always run into typing issues with that though:

https://stackoverflow.com/questions/72146352/vitest-defineconfig-test-does-not-exist-in-type-userconfigexport/72149404#72149404

**Comment by Dhq** [comment]
I'm also having this problem, wont pick up the config file no matter what I write after upgrade to 16.3.
