### ISSUE TITLE
Create Workspace with Angular defaults to Jest for testing

### ISSUE THREAD

**Issue by Sharondio** [nrwl/nx#1698]
## Expected Behavior
When generating an angular app via nx-cli, either as part of an initial workspace setup, or to add to an existing ng-cli generated workspace, I expect to get all of the angular options, such as configure routing, and which testing framework to use.  

## Current Behavior
When generating a new nx workspace, and choose either the angular or the angular + nest options to pre-populate an application, the nx-cli no longer asks the user which testing framework to use. It also does not ask about configuring routing. 

Additionally, when adding an app to an nx-cli generated workspace, same issue. It defaults to jest, but *does* ask to configure routing. 

Creating an empty workspace, but using nx-cli, and then adding an angular app = same result.
Creating an empty workspace, but using angular-cli to run it, and then adding an angular app works as expected.

Note: It did previously ask for the testing option before I upgraded nx-cli. I do not recall exactly what version I was running before upgrading.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create nx workspace: npx create-nx-workspace@latest my-app
2. When asked what to create in new workspace, choose either "angular" or "angular-nest"
3. Give application name
4. Choose stylesheet format
5. Notice no further options.

### Context

Please provide any relevant information about your setup:

- version of Nx used: 8.4.4
- angular-cli version: 8.1.1
- node version: v10.16.0
- osX 10.14.6 Mojave

### Failure Logs

No errors reported.

## Other

Any other relevant information that will help us help you.

**Comment by kjbetz** [comment]
Per docs, you can pass the `--unit-test-runner` flag to specify which test runner you'd like to set up.

> **Using Karma**
>
>To use Karma instead of Jest, run `ng g @nrwl/angular:application frontend --unit-test-runner=karma.`

**Comment by Sharondio** [comment]
Hopefully that will work for adding an application to an existing nx-generated workspace. But what about when you're generating a workspace and initializing an app at that time? I'd still consider that a bug.

**Comment by jaysoo** [comment]
The thinking is that new workspaces will want to use Jest as the default, so there isn't an option when creating new workspaces.

@FrozenPandaz @vsavkin Any thoughts? We could prompt for this when creating an app.

**Comment by adgoncal** [comment]
In `angular.json`, I have the following section:
```
// ...
"schematics": {
    "@nrwl/schematics:component": {
      "styleext": "scss"
    },
    "@nrwl/schematics:library": {
      "unitTestRunner": "karma",
      "framework": "angular"
    },
    "@nrwl/schematics:application": {
      "unitTestRunner": "karma",
      "e2eTestRunner": "protractor"
    },
    "@nrwl/schematics:node-application": {
      "framework": "express"
    }
  }
}
```

However, `ng g lib` still uses jest. Is there something wrong with my configuration? If not, what is the point of this configuration in angular.json if the schematics don't honor it?

**Comment by vsavkin** [comment]
@Sharondio Agree about the docs. We should add a guide, maybe on configuring Karma and Protractor. If you would like to do it, I'll be happy to merge it.

Another thing we could do is to print a message after `ng-add` executes saying that the test runners are defaulted to Jest and Cypress, and pointing to the guide showing how to change to Karma and Protractor.

**Comment by vsavkin** [comment]
Folks. I"m going to close this issue.

We will use this one to track the docs update: https://github.com/nrwl/nx/issues/1903
