### ISSUE TITLE
NX withModuleFederation doesn't support type var, dynamic remotes or promiseBased Remotes

### ISSUE THREAD

**Issue by infoxicator** [nrwl/nx#16983]
### Current Behavior

When trying to use module federation `type var` instead of the NX default (module), dynamic remotes don't load with the following error:

`Remote loaded successfully but cart could not be found! Verify that the name is correct in the Webpack configuration!`

Tried disabling the `withModuleFederation` plugin completely and passing my own modulefederation plugin config and same results. Seems to be something in the NX webpack configuration.

related https://github.com/nrwl/nx/pull/16011

### Expected Behavior

NX should work with non ESM targets and module federation library type `var` or `window` as well as support `dynamicRemotes` and `promiseBasedRemotes`

### GitHub Repo

https://github.com/infoxicator/nx-import-module-bug

### Steps to Reproduce

1.
Change the remote library type to `var`:

```module.exports = {
  name: 'about',
  library: { type: 'var', name: 'about' },
  exposes: {
    './Module': './src/remote-entry.ts',
  },
};
```

2. disable the `outputModule` experimental flag to turn off esm
```module.exports = composePlugins(
  withNx(),
  withReact(),
  withModuleFederation(config),
  (config) => {
    return { ...config, experiments: { outputModule: false } };
  }
);
```
3. use dynamic remotes [importModule](https://www.npmjs.com/package/@module-federation/utilities) or `promiseBased` Remotes to import the remote

```
const About = React.lazy(() =>
  importRemote({
    scope: 'about',
    module: './Module',
    url: `http://localhost:4203`,
  })
);
```

The error `Remote loaded successfully but cart could not be found! Verify that the name is correct in the Webpack configuration!` appears when trying to load the remote 

### Nx Report

```shell
Node : 18.14.2
   OS   : darwin arm64
   npm  : 9.6.4
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   @nrwl/nx-cloud          : 15.3.5
   typescript              : 4.9.5
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I will be working with @ScriptedAlchemy the creator of module federation to address this issue, opening the issue here for visibility and to link to the repo that reproduces the problem

**Comment by infoxicator** [comment]
@ScriptedAlchemy created this issue to track this problem we discussed a while back, and added the example repo and steps to reproduce.

**Comment by computnik** [comment]
@infoxicator configuring webpack output `scriptType` to `text/javascript` solves this problem. Here is the PR for solution infoxicator/nx-import-module-bug#1

@AgentEnder & nx team, can we include this as a bug fix to default nx configuration for withModuleFederationPlugin? 

CC: @ScriptedAlchemy

**Comment by infoxicator** [comment]
Thanks for figuring it out @computnik 🎉. The issue is the NX module federation plugin defaults to ESM and that is incompatible with module federation `importRemote` and dynamic remotes that need to use the type `var`. 

The key is turning off esm completely setting outputModule to false, module to false and setting the scriptType to `text/javascript` as above. here is a complete example:

module-federation.config.js
``` 
{ 
  name: 'about',
  library: { type: 'var', name: 'about' },
  exposes: {
    './Module': './src/remote-entry.ts',
  },
};
```

webpack.config.js
```
const { composePlugins, withNx } = require('@nrwl/webpack');
const { withReact } = require('@nrwl/react');
const { withModuleFederation } = require('@nrwl/react/module-federation');

const baseConfig = require('./module-federation.config');

const config = {
  ...baseConfig,
};

// Nx plugins for webpack to build config object from Nx options and context.
module.exports = composePlugins(
  withNx(),
  withReact(),
  withModuleFederation(config),
  (config) => {
    return {
      ...config,
      experiments: { outputModule: false },
      output: {
        ...config.output,
        scriptType: 'text/javascript',
      },
    };
  }
);
```

I have also update the reproduction repo


Changing the NX default will probably be a breaking change, so I am happy to close this as a work around, or happy to discuss with @Coly010 and @ScriptedAlchemy regarding using ESM with module federation

**Comment by infoxicator** [comment]
> I’ll try speak to @ScriptedAlchemy about this. I was certain we had made affordances for ESM in the ModuleFederationPlugin itself.
> 
> If this isn’t the case, we can look into changing the Config we provide that can override our defaults

Thanks @Coly010, just to clarify the current ModuleFederationPlugin plugin defaults to ESM, which is causing issues with DynamicRemotes and PromiseBased remotes (to make it work I turned it off overriding the config above). Last time I talked to Zack the recommendation (at least for React) was to use module type `var` without ESM

**Comment by infoxicator** [comment]
**UPDATE:**

After making the changes **[above](https://github.com/nrwl/nx/issues/16983#issuecomment-1567733799)** (adding  `scriptType: 'text/javascript',`) dynamic remote containers (`importRemote`) work but the `import remote from 'remote/Module'` breaks.

To completely disable ESM and ensure module federation works as expected with any import syntax there are further changes to the host app to make it work. I have added the steps and the webpack config overrides to this [PR](https://github.com/infoxicator/nx-import-module-bug/pull/3) to the Reproduction repository.

**Next steps:**

Those are all the required changes to enable `remoteType: var` and disable ESM. 

The next steps on the NX side are to look at the webpack configuration I am overriding in the repro and provide a single config override in the `module-federation.config` file

In the meantime, anyone looking at fixing this manually for now, you can override the config manually as I did in the PR above

**Comment by MarcusResell** [comment]
Even after applying any and all fixes described here, I get `Remote loaded successfully but Foo could not be found! Verify that the name is correct in the Webpack configuration!` when using importRemote. Trying to move away from esm, with a hard requirement on dynamic remotes. Currently not getting wiser, any ideas?

**Comment by infoxicator** [comment]
> Even after applying any and all fixes described here, I get `Remote loaded successfully but Foo could not be found! Verify that the name is correct in the Webpack configuration!` when using importRemote. Trying to move away from esm, with a hard requirement on dynamic remotes. Currently not getting wiser, any ideas?

I think the fix for that particular error is to make sure you set `remoteType: 'script',` 

https://github.com/infoxicator/nx-import-module-bug/pull/3/files#diff-b5dd52c601b86ea4420f8a73e93379499dec4fef38f6c4b3256afe2c0f6159d6R40

It took us a while to find that was causing the issue.

**Comment by MarcusResell** [comment]
@infoxicator thanks for the reply. I believe I tried all of these fixes, one for one and all at the same time. But it might have been disturbed by some other configuration I guess. We have zero known remotes at build time, and rely 100% on dynamic remotes. I wonder if that somehow plays a role

**Comment by infoxicator** [comment]
@MarcusResell I tested this with Dynamic Remotes and works fine for me 🤔 what function to load dynamic remotes are you using?

**Comment by RussellCanfield** [comment]
@infoxicator - this is now supported using the importRemote function in @module-federation/utilities. Previously this library/method relied on webpack putting a window variable in place once a script is loaded. When its loading a ESM module, this never happens and a simple import statement needs to be relied on. Check out the new version, and note the additional "esm" property:

https://www.npmjs.com/package/@module-federation/utilities/v/3.0.3-0

cc: @Coly010

**Comment by Coly010** [comment]
Interesting, that’s helpful!

this issue also should have been closed with this PR that was merged https://github.com/nrwl/nx/pull/19192
