### ISSUE TITLE
Remove outdated `@types/react-router-dom`

### ISSUE THREAD

**Issue by tyler-morrison** [nrwl/nx#16992]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
The `@nrwl/react` package brings in outdated type definitions for `react-router-dom`. The current version of [`react-router-dom`](https://github.com/nrwl/nx/blob/8460c63bd6bd59d3bb130bfa5eafcb6b39d27c3d/packages/react/src/utils/versions.ts#L29) comes bundled with its own type definitions, while [`@types/react-router-dom`](https://github.com/nrwl/nx/blob/8460c63bd6bd59d3bb130bfa5eafcb6b39d27c3d/packages/react/src/utils/versions.ts#LL30C1-L30C51) refers to the older v5 definitions.

## Motivation
Reduce package dependencies while simplifying the usage of `react-router-dom`

## Suggested Implementation
1. Remove `typesReactRouterDomVersion` from [`versions.ts`](https://github.com/nrwl/nx/blob/8460c63bd6bd59d3bb130bfa5eafcb6b39d27c3d/packages/react/src/utils/versions.ts#LL30C1-L30C51)
2. Remove dependency from [`add-routing.ts`](https://github.com/nrwl/nx/blob/8460c63bd6bd59d3bb130bfa5eafcb6b39d27c3d/packages/react/src/generators/application/lib/add-routing.ts#L47)
3. Remove dependency from [`update-app-routes.ts`](https://github.com/nrwl/nx/blob/8460c63bd6bd59d3bb130bfa5eafcb6b39d27c3d/packages/react/src/generators/library/lib/update-app-routes.ts#LL50C1-L50C1)
4. Create a migration script to remove the dependency from legacy projects

**Comment by tyler-morrison** [comment]
Need a quick sanity check that `@types/react-router-dom` is not required for other packages. Otherwise, I'm good to make this PR shortly

**Comment by xiongemi** [comment]
i did a quick check on https://github.com/nrwl/nx-examples for @types/react-router-dom, it seems it is not required in other packages. i can submit a pr or you are welcome to submit one.

**Comment by xiongemi** [comment]
@tyler-morrison i submitted a pr https://github.com/nrwl/nx/pull/17078 to remove @types/react-router-dom and ugrade react-router-dom to latest version
