### ISSUE TITLE
Cannot run build command with latest @angular-devkit/build-angular

### ISSUE THREAD

**Issue by ahnpnl** [nrwl/nx#1700]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Should be able to run `nx build` successfully.

## Current Behavior

When upgrading `@angular-devkit/build-angular` to the latest version `0.802.1`, `nx build` failed to build apps.

## Failure Information (for bugs)
- If I use latest version of `@angular-devkit/build-angular`, `nx build` failed.
- If I use version 0.800.6 of `@angular-devkit/build-angular`, `nx build` succeeded.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Clone/Download https://github.com/ahnpnl/nx-devkit-build-angular-bug
2. Install dependencies with `yarn`
3. Run `yarn build` and observe the error like in the screenshot

### Context

Please provide any relevant information about your setup:

- version of Nx used: 8.4.6
- 3rd-party libraries and their versions: **N.A.**
- and most importantly - a use-case that fails

A sample repo at https://github.com/ahnpnl/nx-devkit-build-angular-bug

### Failure Logs

![image](https://user-images.githubusercontent.com/27772165/62768107-70b0b380-ba96-11e9-8f27-b2876d01dcb9.png)

## Other

`nx-build` failure already happened starting from version 0.801.x of `@angular-devkit/build-angular`

**Comment by brandonroberts** [comment]
This is due to https://github.com/angular/angular-cli/blob/c7135fae357ffe16bd420b59b80b002632806a45/packages/angular_devkit/build_angular/src/utils/version.ts#L41

A workaround is to install the `@angular/cli` using `yarn add @angular/cli --dev` to satisfy the dependency.

**Comment by brandonroberts** [comment]
This has been fixed. Please verify with the latest release of Nx.
