### ISSUE TITLE
package.json and pnpm-lock.yaml missing all dependencies after build

### ISSUE THREAD

**Issue by sgtsquiggs** [nrwl/nx#17004]
### Current Behavior

Build output in dist has no dependencies in package.json and no dependencies in pnpm-lock.yaml.

`nx docker-build backend` should produce a docker image that has all dependencies. The image depends on `RUN npm --prefix backend --omit=dev -f install` as seen [here](https://github.com/nrwl/nx/blob/c71027fbfbd74a025c90e73b8f273c2334a090a7/packages/node/src/generators/setup-docker/files/Dockerfile__tmpl__#LL22C3-L22C3).

### Expected Behavior

Build output should include dependencies so that it can be distributed.

Expected to see `express` at minimum.

### GitHub Repo

https://github.com/sgtsquiggs/nx-no-imports-example

### Steps to Reproduce

```bash
pnpm create nx-workspace nxtest
cd nxtest
pnpm add -wD @nx/node
nx g @nx/node:app backend --docker --framework=express --unitTestRunner=none --e2eTestRunner=none
nx build backend
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.14.0
   OS     : darwin arm64
   pnpm   : 8.2.0
   Hasher : Native
   
   nx (global)        : 16.1.4
   nx                 : 16.1.4
   @nx/js             : 16.1.4
   @nx/linter         : 16.1.4
   @nx/esbuild        : 16.1.4
   @nx/eslint-plugin  : 16.1.4
   @nx/node           : 16.1.4
   @nrwl/tao          : 16.1.4
   typescript         : 5.0.4
```

### Failure Logs

```shell
# package.json

{
  "name": "backend",
  "version": "0.0.1",
  "main": "./main.js"
}



# pnpm-lock.yaml

lockfileVersion: '6.0'
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by sgtsquiggs** [comment]
<details>
<summary>Reproducible in 15.9.4</summary>

```
   Node : 16.14.0
   OS   : darwin arm64
   pnpm : 8.2.0
   
   nx (global)             : 16.1.4
   nx                      : 15.9.4
   @nrwl/js                : 15.9.4
   @nrwl/linter            : 15.9.4
   @nrwl/esbuild           : 15.9.4
   @nrwl/eslint-plugin-nx  : 15.9.4
   @nrwl/node              : 15.9.4
   @nrwl/tao               : 15.9.4
   typescript              : 4.9.5
```

</details>

<details>
<summary>Reproducible in 15.8.1</summary>

```
   Node : 16.14.0
   OS   : darwin arm64
   pnpm : 8.2.0
   
   nx                      : 15.8.1
   @nrwl/js                : 15.8.1
   @nrwl/jest              : 15.8.1
   @nrwl/linter            : 15.8.1
   @nrwl/workspace         : 15.8.1
   @nrwl/cli               : 15.8.1
   @nrwl/devkit            : 15.8.1
   @nrwl/esbuild           : 15.8.1
   @nrwl/eslint-plugin-nx  : 15.8.1
   @nrwl/node              : 15.8.1
   @nrwl/tao               : 15.8.1
   @nrwl/webpack           : 15.8.1
   typescript              : 4.9.5
```

</detals>

**Comment by xiongemi** [comment]
i think it is possibly related to https://github.com/nrwl/nx/issues/19773. the fix just got merge, i think it will be in the next release (17.1.0).
