### ISSUE TITLE
Cannot install nrwl packages '@nrwl/workspace@16.0.1' is not in this registry  

### ISSUE THREAD

**Issue by nikbabchenko** [nrwl/nx#17017]
### Current Behavior

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nrwl%2fworkspace - Not found
npm ERR! 404 
npm ERR! 404  '@nrwl/workspace@16.0.1' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nickbabchenko/.npm/_logs/2023-05-15T09_54_48_890Z-debug-0.log

### Expected Behavior

package installed 

### Steps to Reproduce

Try to install @nrwl/workspace

### Nx Report

```shell
....
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Also the issues with most of all packages in NPM

**Comment by CircleCode** [comment]
it appears that at this date, it is also impossible to install v15.9.2:

```
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error Could not write file "…/frontend/yarn-error.log": "EACCES: permission denied, open '…/frontend/yarn-error.log'"
error An unexpected error occurred: "https://registry.yarnpkg.com/@nrwl/workspace/-/workspace-15.9.2.tgz: Request failed \"404 Not Found\"".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by Simon-Hayden-iteratec** [comment]
I looks like the NPM packages have gone private? Going to npmjs.org, I can't open any of the Nx/nrwl packages:

https://www.npmjs.com/search?q=%40nx%2Fworkspace

**Comment by kulichkoff** [comment]
I have the same issue trying to create nx monorepo. I can also agree with @Simon-Hayden-iteratec the package is not public now.

**Comment by IanMontes** [comment]
Having the same issue here:
```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nrwl/workspace/-/workspace-15.9.2.tgz - Not found
npm ERR! 404 
npm ERR! 404  '@nrwl/workspace@https://registry.npmjs.org/@nrwl/workspace/-/workspace-15.9.2.tgz' is not in this registry.
```

**Comment by guilhermeIO** [comment]
Might be either a coincidence or the underlying reason, but NPM is currently mitigating Authentication issues:

[NPM Status](https://status.npmjs.org/)

**Comment by mandarini** [comment]
@nikbabchenko came here to write what @guilhermeIO wrote. There's some issue on Npm, I think if you try again there's not going to be an issue! :)

**Comment by Simon-Hayden-iteratec** [comment]
The NPM status page still says major outage, but I was able to build an uncached Docker container now. Looks like it's about to be marked as fixed?

**Comment by mandarini** [comment]
I will close this issue now, but ping me if you believe that it should stay open! :)
