### ISSUE TITLE
generatePackageJson Yarn 2 missing @babel/types

### ISSUE THREAD

**Issue by orgaizer** [nrwl/nx#17010]
### Current Behavior

When building the service with `generatePackageJson: true`, the yarn.lock file is missing packages, thus `immutable` flag throws.

I am not sure why, but an inner dependency `@babel/types` is installed by `@babel/parser` even though it's not a dependency/devDependency/peerDependency.

When removing the `--immutable` flag and installing, yarn why output:
<img width="1101" alt="image" src="https://github.com/nrwl/nx/assets/111685852/dc3bfc50-0f74-4cbf-a7c5-12c85057c5f8">

### Expected Behavior

`yarn install --immutable` works

### GitHub Repo

https://github.com/gaizeror/nx-yarn-issue

### Steps to Reproduce

1. clone the reproduction repo 
```sh
git clone https://github.com/gaizeror/nx-yarn-issue.git
cd nx-yarn-issue
```
2. configure yarn if required
3. 
```sh
yarn
yarn nx build --prod --project=example
cd dist/services/example
yarn --immutable
```

### Nx Report

```shell
➜  nx-yarn-issue git:(main) ✗ yarn nx report
 >  NX   Report complete - copy this into the issue template

   Node   : 18.12.1
   OS     : darwin x64
   yarn   : 3.5.1
   Hasher : Native

   nx             : 16.1.4
   @nx/js         : 16.1.4
   @nx/workspace  : 16.1.4
   @nx/devkit     : 16.1.4
   @nrwl/tao      : 16.1.4
   @nx/webpack    : 16.1.4
   typescript     : 4.9.4
```

### Failure Logs

```shell
➜  example git:(main) yarn --immutable
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 1s 609ms

➤ YN0000: ┌ Post-resolution validation
➤ YN0000: │ @@ -4,8 +4,20 @@
➤ YN0000: │  __metadata:
➤ YN0000: │    version: 6
➤ YN0000: │    cacheKey: 8
➤ YN0000: │
➤ YN0028: │ +"@babel/helper-string-parser@npm:^7.21.5":
➤ YN0028: │ +  version: 7.21.5
➤ YN0028: │ +  resolution: "@babel/helper-string-parser@npm:7.21.5"
➤ YN0028: │ +  languageName: node
➤ YN0028: │ +  linkType: hard
➤ YN0028: │ +
➤ YN0028: │ +"@babel/helper-validator-identifier@npm:^7.19.1":
➤ YN0028: │ +  version: 7.19.1
➤ YN0028: │ +  resolution: "@babel/helper-validator-identifier@npm:7.19.1"
➤ YN0028: │ +  languageName: node
➤ YN0028: │ +  linkType: hard
➤ YN0028: │ +
➤ YN0000: │  "@babel/parser@npm:^7.20.15":
➤ YN0000: │    version: 7.21.8
➤ YN0000: │    resolution: "@babel/parser@npm:7.21.8"
➤ YN0000: │    bin:
➤ YN0000: │ @@ -13,8 +25,18 @@
➤ YN0000: │    checksum: 1b9a820fedfb6ef179e6ffa1dbc080808882949dec68340a616da2aa354af66ea2886bd68e61bd444d270aa0b24ad6273e3cfaf17d6878c34bf2521becacb353
➤ YN0000: │    languageName: node
➤ YN0000: │    linkType: hard
➤ YN0000: │
➤ YN0028: │ +"@babel/types@npm:^7.8.3":
➤ YN0028: │ +  version: 7.21.5
➤ YN0028: │ +  resolution: "@babel/types@npm:7.21.5"
➤ YN0028: │ +  dependencies:
➤ YN0028: │ +    "@babel/helper-string-parser": ^7.21.5
➤ YN0028: │ +    "@babel/helper-validator-identifier": ^7.19.1
➤ YN0028: │ +    to-fast-properties: ^2.0.0
➤ YN0028: │ +  languageName: node
➤ YN0028: │ +  linkType: hard
➤ YN0028: │ +
➤ YN0000: │  "@google-cloud/paginator@npm:^4.0.0":
➤ YN0000: │    version: 4.0.1
➤ YN0000: │    resolution: "@google-cloud/paginator@npm:4.0.1"
➤ YN0000: │    dependencies:
➤ YN0000: │ @@ -1290,8 +1312,14 @@
➤ YN0000: │    checksum: 8b1214654182575124498c87ca986ac53dc76ff36e8f0e0b67139a8d221eaecfdec108c0e6ec54d76f49f1f72ab9325500b246f562b926f85bcdfca8bf35df9e
➤ YN0000: │    languageName: node
➤ YN0000: │    linkType: hard
➤ YN0000: │
➤ YN0028: │ +"to-fast-properties@npm:^2.0.0":
➤ YN0028: │ +  version: 2.0.0
➤ YN0028: │ +  resolution: "to-fast-properties@npm:2.0.0"
➤ YN0028: │ +  languageName: node
➤ YN0028: │ +  linkType: hard
➤ YN0028: │ +
➤ YN0000: │  "tr46@npm:~0.0.3":
➤ YN0000: │    version: 0.0.3
➤ YN0000: │    resolution: "tr46@npm:0.0.3"
➤ YN0000: │    checksum: 726321c5eaf41b5002e17ffbd1fb7245999a073e8979085dacd47c4b4e8068ff5777142fc6726d6ca1fd2ff16921b48788b87225cbc57c72636f6efa8efbffe3
➤ YN0000: │
➤ YN0028: │ The lockfile would have been modified by this install, which is explicitly forbidden.
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 1s 634ms
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by robert-king** [comment]
I got the same thing started happening:

>> cat dist/apps/my-nest-app/package.json 
{
  "name": "staplesvr-nest",
  "version": "0.0.1",
  "dependencies": {
    "tslib": "2.5.0"
  },
  "main": "main.js"
}


it's missing dependencies it previously had, and now my builds are broken:

Error: Cannot find module '@nestjs/common'

**Comment by orgaizer** [comment]
> I got the same thing started happening:
> 
> > > cat dist/apps/my-nest-app/package.json
> > > {
> > > "name": "my-nest-app",
> > > "version": "0.0.1",
> > > "dependencies": {
> > > "tslib": "2.5.0"
> > > },
> > > "main": "main.js"
> > > }
> 
> it's missing dependencies it previously had, and now my builds are broken:
> 
> Error: Cannot find module '@nestjs/common'
> 
> edit: I manually created a base package.json to apps/my-app/package.json by repeatedly building until no more errors come:
> 
> { "dependencies": { "tslib": "2.5.0", "@nestjs/common": "9.4.0", "@nestjs/core": "^9.0.0", "@nestjs/swagger": "6.3.0" } }
> 
> now after nx build my-app it produces this:
> 
> cat dist/apps/my-app/package.json
> 
> { "dependencies": { "@nestjs/common": "9.4.0", "@nestjs/core": "^9.0.0", "@nestjs/platform-express": "9.4.0", "@nestjs/platform-socket.io": "9.4.0", "@nestjs/swagger": "6.3.0", "@nestjs/websockets": "9.4.0", "class-transformer": "0.5.1", "class-validator": "0.14.0", "reflect-metadata": "0.1.13", "rxjs": "7.8.1", "tslib": "2.5.0" }, "main": "main.js" }

I don't think it's the same problem, I faced the same thing but it was because my `namedInputs` were configured wrong in the `nx.json` file if I remember correctly

**Comment by meeroslav** [comment]
@robert-king please create a separate issue

**Comment by meeroslav** [comment]
@orgaizer your repo uses Yarn PnP, which is not officially supported by Nx yet.

On top of that, running `yarn` on that repo reports that several peer deps are not resolved (Yarn Berry is as you might know strict about peers). This leads to build breaking completely when run on a clean yarn cache (`yarn cache clean`).

Please provide a repo example that works on a clean cache in order for me to investigate the issue further.

**Comment by orgaizer** [comment]
@meeroslav Hey, thanks for your help.
I have updated the repo with the `nodeLinker` parameter and will check out the peer dependency issue tomorrow. thanks!

**Comment by meeroslav** [comment]
For reference, this is what we get when running on a clean store: https://app.warp.dev/block/S7pAVk0Gfmm6N4tqMdWf6U 

Additionally, adding `PubSub` and referencing it in the project makes 'bundler's life very difficult (not sure if it's bundler's issue or Yarn Berry). I've tested this on M1 and Intel i9 machines, and both were suffering while bundling.

**Comment by meeroslav** [comment]
Closing as stale
