### ISSUE TITLE
`create-nx-workspace` failed to initialize using `yarn` as the `packageManager`

### ISSUE THREAD

**Issue by JeromeDeLeon** [nrwl/nx#17023]
### Current Behavior

It's been a while since I last use `nx` from v15 but coming back, I'm having problem to initialize package using `yarn`.

```
$ npx create-nx-workspace@latest package-based --preset=ts --packageManager=yarn

>  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Enable distributed caching to make your CI faster · No

 >  NX   Creating your v16.1.4 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "yarn install" several times. Please wait.

✔ Installing dependencies with yarn
✖ Creating your workspace in package-based

 >  NX   Failed to create a workspace.

   Error: error Command failed with exit code 1.
```

While it does work via `npm`

```
$ npx create-nx-workspace@latest package-based --preset=ts --packageManager=npm --verbose

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Enable distributed caching to make your CI faster · No

 >  NX   Creating your v16.1.4 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✔ Successfully created the workspace: package-based.

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————


 >  NX   Nx CLI is not installed globally.

   This means that you might have to use "yarn nx" or "npx nx" to execute commands in the workspace.
   Run "yarn global add nx" or "npm install -g nx" to be able to execute command directly.


————————————————————————————————————————————————————————————————————————————————————————————————————————————


 >  NX   First time using Nx? Check out this interactive Nx tutorial.

   https://nx.dev/tutorials/integrated-repo-tutorial
```

### Expected Behavior

I expected it to work similarly to how it outputted the `npm` version

### Steps to Reproduce

1. Run this in your CLI `npx create-nx-workspace@latest package-based --preset=ts --packageManager=yarn`

### Nx Report

```shell
I copied this from another nx project

Node   : 16.18.0
OS     : darwin arm64
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I'm not sure if it helps but the reason I'm doing this is because I'm trying to migrate my nx `15.5.3` version to `16.1.4` but I stumbled upon an issue with 

```json
{
  "version": "16.0.0-beta.4",
  "description": "Generates a plugin called 'workspace-plugin' containing your workspace generators.",
  "cli": "nx",
  "implementation": "./src/migrations/update-16-0-0/move-workspace-generators-to-local-plugin",
  "package": "@nrwl/workspace",
  "name": "16-0-0-move-workspace-generators-into-local-plugin"
}
```

Saying that 

```
YARN_NODE_LINKER=node-modules yarn nx migrate --run-migrations --verbose

>  NX   Running 'yarn' to make sure necessary packages are installed

➤ YN0000: ┌ Resolution step
➤ YN0002: │ @nrwl/devkit@npm:16.2.0-beta.1 doesn't provide nx (paaad1), requested by @nx/devkit
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 217ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 432ms
➤ YN0000: Done with warnings in 0s 902ms

>  NX   Running migrations from 'migrations.json'

Fetching @nx/plugin...
Internal Error: The "yarn-path" option has been set (in /private/var/folders/7q/7yqv8j1s4sg7prf_q8nbm8l00000gr/T/tmp-24679-xpD4rXM6on00/.yarnrc.yml), but the specified location doesn't exist (/private/var/folders/7q/7yqv8j1s4sg7prf_q8nbm8l00000gr/T/tmp-24679-xpD4rXM6on00/.yarn/releases/yarn-3.5.1.cjs).
at i (/dummy-path/.yarn/releases/yarn-3.5.1.cjs:446:11180)
at async t (/dummy-path/.yarn/releases/yarn-3.5.1.cjs:446:10283)

>  NX   Failed to run 16-0-0-move-workspace-generators-into-local-plugin from @nrwl/workspace. This workspace is NOT up to date!


>  NX   Command failed: yarn add -D @nx/plugin@16.2.0-beta.1


Error: Command failed: yarn add -D @nx/plugin@16.2.0-beta.1
at checkExecSyncError (node:child_process:861:11)
at execSync (node:child_process:932:15)
at ensurePackage (/dummy-path/node_modules/@nx/devkit/src/utils/package-json.js:270:34)
at /dummy-path/node_modules/@nx/workspace/src/migrations/update-16-0-0/move-workspace-generators-to-local-plugin.js:118:36
at Generator.next (<anonymous>)
at /dummy-path/node_modules/tslib/tslib.js:167:75
at new Promise (<anonymous>)
at Object.__awaiter (/dummy-path/node_modules/tslib/tslib.js:163:16)
at createNewPlugin (/dummy-path/node_modules/@nx/workspace/src/migrations/update-16-0-0/move-workspace-generators-to-local-plugin.js:117:20)
Command failed: yarn exec nx _migrate --run-migrations --verbose

>  NX   Command failed: yarn exec nx migrate --run-migrations --verbose


Error: Command failed: yarn exec nx migrate --run-migrations --verbose
at checkExecSyncError (node:child_process:861:11)
at execSync (node:child_process:932:15)
at runNxSync (/private/var/folders/7q/7yqv8j1s4sg7prf_q8nbm8l00000gr/T/tmp-24661-2Mk0Q2fHJUkb/node_modules/nx/src/utils/child-process.js:26:34)
at /private/var/folders/7q/7yqv8j1s4sg7prf_q8nbm8l00000gr/T/tmp-24661-2Mk0Q2fHJUkb/node_modules/nx/src/command-line/migrate.js:955:43
at Generator.next (<anonymous>)
at /private/var/folders/7q/7yqv8j1s4sg7prf_q8nbm8l00000gr/T/tmp-24661-2Mk0Q2fHJUkb/node_modules/tslib/tslib.js:167:75
at new Promise (<anonymous>)
at Object.__awaiter (/private/var/folders/7q/7yqv8j1s4sg7prf_q8nbm8l00000gr/T/tmp-24661-2Mk0Q2fHJUkb/node_modules/tslib/tslib.js:163:16)
at runMigrations (/private/var/folders/7q/7yqv8j1s4sg7prf_q8nbm8l00000gr/T/tmp-24661-2Mk0Q2fHJUkb/node_modules/nx/src/command-line/migrate.js:948:20)
Command failed: /var/folders/7q/7yqv8j1s4sg7prf_q8nbm8l00000gr/T/tmp-24661-2Mk0Q2fHJUkb/node_modules/.bin/nx _migrate --run-migrations --verbose
```

**Comment by AgentEnder** [comment]
The package registries were experiencing an issue earlier. Can you try rerunning the migrations with verbose and see what happens?

**Comment by JeromeDeLeon** [comment]
Same output as above but I don't think it has something to do with the npm registries as it works using `npm` but not `yarn`.

**Comment by JeromeDeLeon** [comment]
Using `16.2.1` fixed the `create-nx-workspace` with `yarn` and with regards to the migration from `15.5.3`, I somehow managed to make it work in `yarn berry` from `15.5.3` to `16.2.1`.

Here are my findings:
1. This PR #16652 caused an issue because it creates a temp dir but doesn't respect the location of the `yarnPath` defined in `.yarnrc.yml`. My workaround is to replace the `yarnPath` with an absolute path but it then creates another issue if you have a yarn plugin installed like mine because it has to verify the plugin path but since it is included in the temp dir, it throws an error so I had to temporarily remove all the plugins as well.
2. The next error I encountered was regarding the `16-0-0-move-workspace-generators-into-local-plugin` migration where it cannot find `.eslintrc.json` for whatever reason but I have `.eslintrc.js`. Luckily, I was able to convert it to json config but for someone that has a complex ESLint setup, it may be a huge deal.
3. Next issue is around the `prettier` package that the migration automatically installed in the root directory even though I didn't want it and also creates `jest.preset.js`. I think it has something to do with the migration itself that it does all this even though all it has to do was to migrate the generator to workspace-plugin like any other migration or maybe the `@nx/plugin` requires all of these that I don't know about as this is my first time using the `@nx/plugin`.

**Comment by AgentEnder** [comment]
Hey 👋, there's some good information here.

1. We do copy yarnrc's as part of this, and its certainly true that the `yarnPath` would break. Can you grab a copy of your yarnrc for me to check over? I'll work on updating our logic to handle  a few of the relative path args.
2. Yeah, the migration should be a bit more resilient to that. I'll work on updating it.

**Comment by JeromeDeLeon** [comment]
Here's the `.yarnrc.yml` 

```yaml
nmHoistingLimits: workspaces

nmSelfReferences: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
```

The `yarnPath` and `plugins` caused the issue on my end.

One thing to note if possible is to have the option to disable generating/installing prettier, eslint, and jest in setting up the `@nx/plugin` for the first time as I got too many changes that I suddenly have to remove. It could also just be a ME problem where I only needed the `generator` to generate another project with a template.

**Comment by JeromeDeLeon** [comment]
Yeah totally make sense to me. I just remembered some option like `--skip-lint` and thought that could also be applied in here. Thanks for fixing it. 🔥
