### ISSUE TITLE
nx migrate 15.9.4 -> 16.x.x fails

### ISSUE THREAD

**Issue by hevans90** [nrwl/nx#17031]
### Current Behavior

`nx migrate latest` throws a reproducible error for the `16.0.0-remove-nrwl-cli from nx` migration:

```
 >  NX   Failed to run 16.0.0-remove-nrwl-cli from nx. This workspace is NOT up to date!


 >  NX   Unable to determine implementation path for "/Users/harri/source/idleverse/node_modules/nx/migrations.json:16.0.0-remove-nrwl-cli"


Error: Unable to determine implementation path for "/Users/harri/source/idleverse/node_modules/nx/migrations.json:16.0.0-remove-nrwl-cli"
    at getImplementationPath (/Users/harri/source/idleverse/node_modules/@nrwl/tao/node_modules/nx/src/command-line/migrate.js:1069:15)
    at isAngularMigration (/Users/harri/source/idleverse/node_modules/@nrwl/tao/node_modules/nx/src/command-line/migrate.js:1100:42)
    at /Users/harri/source/idleverse/node_modules/@nrwl/tao/node_modules/nx/src/command-line/migrate.js:892:22
    at Generator.next (<anonymous>)
    at /Users/harri/source/idleverse/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/harri/source/idleverse/node_modules/tslib/tslib.js:114:16)
    at executeMigrations (/Users/harri/source/idleverse/node_modules/@nrwl/tao/node_modules/nx/src/command-line/migrate.js:886:20)
    at /Users/harri/source/idleverse/node_modules/@nrwl/tao/node_modules/nx/src/command-line/migrate.js:976:47
    at Generator.next (<anonymous>)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: yarn nx _migrate --run-migrations --verbose
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 >  NX   Command failed: yarn nx migrate --run-migrations --verbose


Error: Command failed: yarn nx migrate --run-migrations --verbose
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at runNxSync (/private/var/folders/3v/33y6c_rs081cmjtjkp1d4b3m0000gn/T/tmp-12178-cqJdm5lTXQtp/node_modules/nx/src/utils/child-process.js:26:34)
    at /private/var/folders/3v/33y6c_rs081cmjtjkp1d4b3m0000gn/T/tmp-12178-cqJdm5lTXQtp/node_modules/nx/src/command-line/migrate.js:955:43
    at Generator.next (<anonymous>)
    at /private/var/folders/3v/33y6c_rs081cmjtjkp1d4b3m0000gn/T/tmp-12178-cqJdm5lTXQtp/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/private/var/folders/3v/33y6c_rs081cmjtjkp1d4b3m0000gn/T/tmp-12178-cqJdm5lTXQtp/node_modules/tslib/tslib.js:163:16)
    at runMigrations (/private/var/folders/3v/33y6c_rs081cmjtjkp1d4b3m0000gn/T/tmp-12178-cqJdm5lTXQtp/node_modules/nx/src/command-line/migrate.js:948:20)
Command failed: /var/folders/3v/33y6c_rs081cmjtjkp1d4b3m0000gn/T/tmp-12178-cqJdm5lTXQtp/node_modules/.bin/nx _migrate --run-migrations --verbose
```

### Expected Behavior

The migrations should work as they usually do :)

### Steps to Reproduce

1. get a repo on `nx 15.9.x` and try `nx migrate latest`

### Nx Report

```shell
This is kinda bricked by the migration attempt:


➜  idleverse git:(build/migrate-nx-to-16) ✗ nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.16.0
   OS   : darwin arm64
   yarn : 1.22.19

   nx (global)             : 16.1.4
   nx                      : 15.9.4
   @nrwl/js                : 16.1.4
   @nrwl/jest              : 16.1.4
   @nrwl/linter            : 16.1.4
   @nrwl/workspace         : 16.1.4
   @nrwl/cli               : 15.9.4
   @nrwl/cypress           : 16.1.4
   @nrwl/devkit            : 16.1.4
   @nrwl/eslint-plugin-nx  : 16.1.4
   @nrwl/node              : 16.1.4
   @nrwl/react             : 16.1.4
   @nrwl/tao               : 16.1.4
   @nrwl/web               : 16.1.4
   @nrwl/nx-cloud          : 16.0.5
   typescript              : 5.0.4
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/js@16.1.4
     - @nrwl/jest@16.1.4
     - @nrwl/linter@16.1.4
     - @nrwl/workspace@16.1.4
     - @nrwl/cypress@16.1.4
     - @nrwl/devkit@16.1.4
     - @nrwl/eslint-plugin-nx@16.1.4
     - @nrwl/node@16.1.4
     - @nrwl/react@16.1.4
     - @nrwl/tao@16.1.4
     - @nrwl/web@16.1.4

   To fix this, run `nx migrate nx@16.1.4`
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by hevans90** [comment]
Manually removing `@nrwl/cli` from `package.json` and deleting this migration entry from the `migrations.json` file and rerunning migrations fixes the issue.

However `@nrwl/webpack` was not migrated to `@nx/webpack` - this had to be manually installed. This is a long-standing issue and it's extremely disappointing that [this is still a problem.](https://github.com/nrwl/nx/issues/14531)

**Comment by ac-ih** [comment]
My nx pkg upgraded fine to 6.1.4, but I am also facing issues during the migration:

```
..\node_modules\@angular\cdk\schematics\update-tool\index.js:62
        limitToDirectory &&= this._fileSystem.resolve(limitToDirectory);

`SyntaxError: Unexpected token '&&='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (..\node_modules\nx\src\adapter\compat.js:35:40)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (..\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:12:23)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
Command failed: npx nx _migrate --run-migrations --verbose

 >  NX   Command failed: npx nx migrate --run-migrations --verbose
```

**Comment by jihoun** [comment]
> Based on your `nx report`, it looks like the main `nx` package is somehow not been updated. Can you bump it to Nx 16.1.4 and rerun migrations? Its likely not able to find the v16 migrations since the package is under v16.
> 

I have a similar issue (outdated nx version in report). But I do not have nx as a dependency in my package.json. So, I do not really know where it picks it up from.

**Comment by AgentEnder** [comment]
You should have nx in your package.json, what does 'npm ls nx' say?

**Comment by AgentEnder** [comment]
> My nx pkg upgraded fine to 6.1.4, but I am also facing issues during the migration:
> 
> ```
> ..\node_modules\@angular\cdk\schematics\update-tool\index.js:62
>         limitToDirectory &&= this._fileSystem.resolve(limitToDirectory);
> 
> `SyntaxError: Unexpected token '&&='
>     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
>     at Module._compile (internal/modules/cjs/loader.js:1049:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
>     at Module.load (internal/modules/cjs/loader.js:950:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
>     at Module.require (internal/modules/cjs/loader.js:974:19)
>     at Module.require (..\node_modules\nx\src\adapter\compat.js:35:40)
>     at require (internal/modules/cjs/helpers.js:101:18)
>     at Object.<anonymous> (..\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:12:23)
>     at Module._compile (internal/modules/cjs/loader.js:1085:14)
> Command failed: npx nx _migrate --run-migrations --verbose
> 
>  >  NX   Command failed: npx nx migrate --run-migrations --verbose
> ```


This is a different issue, most likely due to an outdated node version that doesn't support &&=. 

Mdn says it was added in Node 15, so very possible. See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND_assignment

**Comment by ac-ih** [comment]
@AgentEnder that was indeed the issue, thank you! I had updated it to 16.x and then switched it to 14.x while debugging.

I was able to migrate from 15.x to 16.x. Now I get errors like 'xyz is not a known element':

`'router-outlet' is not a known element`

**Comment by AgentEnder** [comment]
@ac-ih I can't speak to that. Please open a new issue for things not related to the parent, so that things don't get lost and threads don't get off topic.

**Comment by hevans90** [comment]
> Based on your `nx report`, it looks like the main `nx` package is somehow not been updated. Can you bump it to Nx 16.1.4 and rerun migrations? Its likely not able to find the v16 migrations since the package is under v16.
> 

This is the issue, how can I be more clear? Running `nx migrate latest` on `15.9.x` doesn't work. Go try it yourself!

I shouldn't have to manually bump the cli for migrations to work, that defeats the entire point.
