### ISSUE TITLE
nrwl/linter:lint "-- fix" not an option

### ISSUE THREAD

**Issue by Jordan-Hall** [nrwl/nx#1703]
Running into issues with using lint --fix. Part of the git hooks we require to fix any linting and formatting rules. Recently created four new libraries and running into an issue with auto fix. two using eslint and two using tslint

## Expected Behavior

ng lint "project name" --fix 

should attempt to fix any linting issues

## Current Behavior

Unknown option: '--fix'

## Failure Information (for bugs)

command
```ng "lint" "tmp-mapper" "--fix"```

```
"tmp-mapper": {
      "root": "libs/mapper",
      "sourceRoot": "libs/mapper/src",
      "projectType": "library",
      "schematics": {},
      "architect": {
        "lint": {
          "builder": "@nrwl/linter:lint",
          "options": {
            "linter": "tslint",
            "tsConfig": [
              "libs/mapper/tsconfig.lib.json",
              "libs/mapper/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**",
              "!libs/mapper/**"
            ]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "libs/mapper/jest.config.js",
            "tsConfig": "libs/mapper/tsconfig.spec.json"
          }
        }
      }
    },
```

**Comment by mehrad-rafigh** [comment]
@Jordan-Hall Can you please provide a repo where I can reproduce this?

**Comment by Jordan-Hall** [comment]
@mehrad-rafigh  https://github.com/Jordan-Hall/nx-lint-reproduce

It appears this time for tslint it used the angular tslint. However, the eslint one still fails. I have changed the angular.json to use the  ```@nrwl/linter:lint``` with the linter option to tslint. It appears  ```@nrwl/linter:lint``` just doesn't support auto fixing
