### ISSUE TITLE
Unable to start Node app after upgrade

### ISSUE THREAD

**Issue by slewis30328** [nrwl/nx#17057]
### Current Behavior

Upgraded from 16.1.0 to 16.1.4 this morning.  Was able to build project with no problem after upgrade, but was unable to start node app.  Angular project started fine. Using node 17.4.  I went down the compilerOptions rabbit hole and pealed back the main.ts, but wasn't making much progress.  Figured it would be best to understand what occurred after 16.1.0 to trigger this.  I just rolled back to 16.1.0 and everything is working again.  Thanks for any assistance.  Would really like to stay current with the updates if possible.

**Error Message from Debugger:**

Uncaught SyntaxError C:\sca-repos\SMART-NX\apps\smart-server-node\src\main.ts:9
import * as debug from 'debug';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at compileFunction (vm:352:18)
    at wrapSafe (internal/modules/cjs/loader:1026:15)
    at Module._compile (internal/modules/cjs/loader:1061:27)
    at Module._extensions..js (internal/modules/cjs/loader:1149:10)
    at Module.load (internal/modules/cjs/loader:975:32)
    at Module._load (internal/modules/cjs/loader:822:12)
    at executeUserEntryPoint (internal/modules/run_main:77:12)
    at <anonymous> (internal/main/run_main_module:17:47)

**Error Message from Console:**

Error: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:371:5)
    at throwIfUnsupportedURLProtocol (node:internal/modules/esm/resolve:996:11)
    at defaultResolve (node:internal/modules/esm/resolve:1070:3)  
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ESMLoader.import (node:internal/modules/esm/loader:332:22) 
    at importModuleDynamically (node:internal/modules/cjs/loader:1036:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:437:21)
    at importModuleDynamically (node:vm:381:46)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)

### Expected Behavior

Successful start to Node Server. Command I use to start:
nx run smart-server-node:serve 

### Steps to Reproduce

1. Not necessary at this time

### Nx Report

```shell
Do not have.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

{
  "name": "smart-nx",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test",
    "postinstall": ""
  },
  "private": true,
  "devDependencies": {
    "@angular-devkit/build-angular": "~16.0.1",
    "@angular-eslint/eslint-plugin": "~16.0.1",
    "@angular-eslint/eslint-plugin-template": "~16.0.1",
    "@angular-eslint/template-parser": "~16.0.1",
    "@angular/cli": "~16.0.1",
    "@angular/compiler-cli": "~16.0.1",
    "@angular/language-service": "~16.0.1",
    "@angular/localize": "~16.0.1",
    "@nx/angular": "^16.1.4",
    "@nx/cypress": "16.1.4",
    "@nx/eslint-plugin": "16.1.4",
    "@nx/express": "^16.1.4",
    "@nx/jest": "16.1.4",
    "@nx/js": "16.1.4",
    "@nx/linter": "16.1.4",
    "@nx/node": "^16.1.4",
    "@nx/workspace": "16.1.4",
    "@types/express": "4.17.17",
    "@types/jest": "^29.5.1",
    "@types/node": "20.1.7",
    "@typescript-eslint/eslint-plugin": "~5.59.6",
    "@typescript-eslint/parser": "~5.59.6",
    "cypress": "^12.12.0",
    "eslint": "~8.40.0",
    "eslint-config-prettier": "8.8.0",
    "eslint-plugin-cypress": "^2.13.3",
    "jest": "29.5.0",
    "jest-environment-jsdom": "29.5.0",
    "jest-preset-angular": "13.1.1",
    "ng-packagr": "^16.0.1",
    "postcss": "^8.4.23",
    "postcss-import": "^15.1.0",
    "postcss-preset-env": "^8.3.2",
    "postcss-url": "^10.1.3",
    "prettier": "^2.8.8",
    "supertest": "^6.3.3",
    "ts-jest": "^29.1.0",
    "ts-node": "10.9.1",
    "typescript": "~5.0.4"
  },
  "dependencies": {
    "@angular/animations": "~16.0.1",
    "@angular/cdk": "^16.0.1",
    "@angular/common": "~16.0.1",
    "@angular/compiler": "~16.0.1",
    "@angular/core": "~16.0.1",
    "@angular/forms": "~16.0.1",
    "@angular/platform-browser": "~16.0.1",
    "@angular/platform-browser-dynamic": "~16.0.1",
    "@angular/router": "~16.0.1",
    "@ckeditor/ckeditor5-angular": "^6.0.1",
    "@ckeditor/ckeditor5-build-decoupled-document": "^37.1.0",
    "@clarivate/angular-image-viewer": "^2.0.8",
    "@fortawesome/fontawesome-pro": "^6.4.0",
    "@ngxs/devtools-plugin": "^3.8.0",
    "@ngxs/logger-plugin": "^3.8.0",
    "@ngxs/storage-plugin": "^3.8.0",
    "@ngxs/store": "^3.8.0",
    "@progress/kendo-angular-buttons": "^12.0.1",
    "@progress/kendo-angular-charts": "^12.0.1",
    "@progress/kendo-angular-common": "^12.0.1",
    "@progress/kendo-angular-dateinputs": "^12.0.1",
    "@progress/kendo-angular-dialog": "^12.0.1",
    "@progress/kendo-angular-dropdowns": "^12.0.1",
    "@progress/kendo-angular-excel-export": "^12.0.1",
    "@progress/kendo-angular-gauges": "^12.0.1",
    "@progress/kendo-angular-grid": "^12.0.1",
    "@progress/kendo-angular-inputs": "^12.0.1",
    "@progress/kendo-angular-intl": "^12.0.1",
    "@progress/kendo-angular-l10n": "^12.0.1",
    "@progress/kendo-angular-label": "^12.0.1",
    "@progress/kendo-angular-layout": "^12.0.1",
    "@progress/kendo-angular-notification": "^12.0.1",
    "@progress/kendo-angular-pager": "^12.0.1",
    "@progress/kendo-angular-pdf-export": "^12.0.1",
    "@progress/kendo-angular-popup": "^12.0.1",
    "@progress/kendo-angular-progressbar": "^12.0.1",
    "@progress/kendo-angular-sortable": "^12.0.1",
    "@progress/kendo-angular-toolbar": "^12.0.1",
    "@progress/kendo-angular-tooltip": "^12.0.1",
    "@progress/kendo-angular-treeview": "^12.0.1",
    "@progress/kendo-angular-upload": "^12.0.1",
    "@progress/kendo-data-query": "^1.6.0",
    "@progress/kendo-drawing": "^1.17.5",
    "@progress/kendo-licensing": "^1.3.0",
    "@progress/kendo-theme-bootstrap": "^6.3.0",
    "@types/hammerjs": "^2.0.41",
    "adm-zip": "^0.5.10",
    "amqp-ts": "^1.8.0",
    "bootstrap": "^5.2.3",
    "canvas": "^2.11.2",
    "chartjs-to-image": "^1.2.1",
    "easy-pdf-merge": "^0.2.6",
    "exceljs": "^4.3.0",
    "express": "4.18.2",
    "express-fileupload": "^1.4.0",
    "hammerjs": "^2.0.8",
    "html-to-pdfmake": "^2.4.20",
    "jsbarcode": "^3.11.5",
    "ldapjs": "^3.0.2",
    "morgan": "^1.10.0",
    "nodemailer": "^6.9.2",
    "nodemailer-express-handlebars": "^6.1.0",
    "nodemailer-smtp-transport": "^2.4.2",
    "oracledb": "^5.5.0",
    "pdfmake": "^0.2.7",
    "rxjs": "~7.8.1",
    "tslib": "^2.5.0",
    "winston": "^3.8.2",
    "xss": "^1.0.14",
    "zone.js": "~0.13.0"
  }
}

**Comment by AdditionAddict** [comment]
Duplicate of https://github.com/nrwl/nx/issues/16973 (patched)

the 16.1.5 betas include the fix
