### ISSUE TITLE
workspace-lint: possibility to exclude projects from workspace linting

### ISSUE THREAD

**Issue by ahnpnl** [nrwl/nx#1705]
I'm not sure if this is a bug or a suggested feature. 

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

A possibility to configure `nx workspace-lint` to ignore some folders.

## Current Behavior

I have a folder named `scss` inside `libs`. I put some scss files there. When running `nx workspace-lint`, I get the error. I tried to configure `linterOptions` in `tslint.json` but this didn't help.

## Failure Information (for bugs)

![image](https://user-images.githubusercontent.com/27772165/62936660-af15dd80-bdca-11e9-9bb1-2d36fcac1062.png)

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Clone example https://github.com/ahnpnl/workspace-lint
2. Install dependencies with `yarn`
3. Run `yarn lint`.
4. Observe error in the console (like screenshot above).

### Context

Please provide any relevant information about your setup:

- version of Nx used: **8.4.8**
- 3rd-party libraries and their versions: **N.A.**
- and most importantly - a use-case that fails

Example repo: https://github.com/ahnpnl/workspace-lint

### Failure Logs

The same as screenshot in **Failure information**

## Other

**N.A.**

**Comment by mehrad-rafigh** [comment]
@ahnpnl Is your lib a style only lib? 

If so, you can create a new directory under `libs`, add your styles there and include your styles in the apps with with: 
```json
"stylePreprocessorOptions": {
  "includePaths": ["libs/shared-styles/styles/"]
},
``` 
This needs to be added to the `build.options` of `angular.json`

**Comment by ahnpnl** [comment]
Hi,

Yes the intention is I want to create a style lib folder which includes shared utils for stylings, like mixins, functions etc. between features. I came across xplat samples and I found https://github.com/nstudio/xplat-sample/tree/master/frontend/libs . Therefore I decided to put the styling only folder inside libs.

I think it would be nice if somehow I can configure workspace lint to exclude some specific folders, similar to exclude option in tslint.

I've tried your suggestion and it works. However, making workspace lint more configurable will bring more flexibility imo

**Comment by mehrad-rafigh** [comment]
Yeah, I like xplat approach with the scss files.
This has been discussed in https://github.com/nrwl/nx/issues/1542 as well.
@ahnpnl Let's close this issue and open a feature request for easier shared styles consumption in the workspace. What do you say?

**Comment by ahnpnl** [comment]
I agree. I will close this and open a feature request for configurable workspace lint.
