### ISSUE TITLE
remoteEntry.mjs net::ERR_EMPTY_RESPONSE NX with HTTPS in angular with microfrontend application

### ISSUE THREAD

**Issue by anandjaisy** [nrwl/nx#17058]
### Current Behavior

GET http://localhost:4201/remoteEntry.mjs net::ERR_EMPTY_RESPONSE

![image](https://github.com/nrwl/nx/assets/84489031/b10ea482-bc30-45ca-af3b-2ed5540258a0)

Browsing the application on `https://localhost:4201` is working fine, however from the host getting an exception as  `net::ERR_EMPTY_RESPONSE`

### Expected Behavior

The application should be server over HTTPS in local development.

### Steps to Reproduce

Create a brand new NX micro front-end angular application and change the server option in one of the remote app, then serve the application and observe the result on the console.

On one of the remote applications change the package.json file 

```
"serve": {
  "executor": "@nx/angular:webpack-dev-server",
  "configurations": {
    "production": {
      "browserTarget": "product:build:production"
    },
    "development": {
      "browserTarget": "product:build:development"
    }
  },
  "defaultConfiguration": "development",
  "options": {
    "port": 4201,
    "publicHost": "https://localhost:4201",
    "ssl": true,
    "sslKey": "././certificate/localhost.key",
    "sslCert": "././certificate/localhost.crt"
  }
},
```

Server the multi-application and check the output on the console

### Nx Report

```shell
N/A
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Angular 16 with Nx 16

**Comment by VanTigranyan** [comment]
try to set host to 0.0.0.0

**Comment by anandjaisy** [comment]
> try to set host to 0.0.0.0

What does, this mean can you please show an sample

**Comment by Coly010** [comment]
@anandjaisy Can you provide a repo where I can test a fix out?

**Comment by anandjaisy** [comment]
> @anandjaisy Can you provide a repo where I can test a fix out?
> 
> Also, can you try add `"host": "https://localhost:4201"` to your remote's `serve` options?
> 
> Our Module Federation utils look for the `host` property or else we fall back to `http://`. As you're using SSL, this will be an incorrect protocol for your remote.

@Coly010 here is the repo - https://github.com/anandjaisy/httpsIssuenxMicronaut

**Comment by Coly010** [comment]
SSL works fine.

I created a PR on your repo that shows the correct setup: https://github.com/anandjaisy/httpsIssuenxMicronaut/pull/1

As this is working as expected, I'm going to close this issue

**Comment by anandjaisy** [comment]
@Coly010 Are you able to run the repo application, I am getting an exception as with the changes merged

```
/Users/san/project/Sample/https-folder/node_modules/@nx/angular/src/builders/module-federation-dev-server/module-federation-dev-server.impl.js:65
                throw new Error(`Remote '${remote}' failed to serve correctly due to the following: \r\n${err.toString()}`);
                      ^

Error: Remote 'shop' failed to serve correctly due to the following: 
Error: getaddrinfo ENOTFOUND https://localhost
    at /Users/san/project/Sample/https-folder/node_modules/@nx/angular/src/builders/module-federation-dev-server/module-federation-dev-server.impl.js:65:23
```

**Comment by Coly010** [comment]
I am yes, see attached video

https://github.com/nrwl/nx/assets/12140467/eab988b6-4ddc-4055-b0f2-cfc587a78c0b

**Comment by anandjaisy** [comment]
@Coly010 Yes, I can run with `nx serve shell`, however, getting error on `nx serve shell --open --devRemotes=cart,shop`


```
/Users/san/project/Sample/https-folder/node_modules/@nx/angular/src/builders/module-federation-dev-server/module-federation-dev-server.impl.js:65
                throw new Error(`Remote '${remote}' failed to serve correctly due to the following: \r\n${err.toString()}`);
                      ^

Error: Remote 'shop' failed to serve correctly due to the following:
Error: getaddrinfo ENOTFOUND https://localhost
    at /Users/san/project/Sample/https-folder/node_modules/@nx/angular/src/builders/module-federation-dev-server/module-federation-dev-server.impl.js:65:23

Node.js v19.1.0
```
