### ISSUE TITLE
Is it possible to prevent sending maxParallel flag to dependsOn tasks?

### ISSUE THREAD

**Issue by ahernd2** [nrwl/nx#17067]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Apologies if this is already possible, im trying to figure out if it is, 

So take this scenario. We are running sonar analysis tests on our CI build. One of the complications of sonar is that it can only run a single task in parallel so we have to specify maxParallel flag of 1. 

```bash
pnx affected --target=sonar --maxParallel=1
```

Before sonar analysis can run we are running the unit tests for each affected project to get code coverage reports, so we have a dependsOn in our nx.json file like so

```json
"targetDefaults": {
    "sonar": {
      "dependsOn": ["test"]
    }
  },
```

This works fine, however because we are setting a maxParallel flag of 1, it forces the tests to run sequentially, which is not optimal. 

Is there a way to prevent sending the maxParallel flag to the dependsOn tasks and have it use the default maxParallel which is 3?

## Motivation
Being forced to run dependsOn tasks sequentially is not optimal for us as it takes a while to run all the tasks

**Comment by AgentEnder** [comment]
`--parallel` (or the deprecated `maxParallel`) is sent to the tasks runner, not any of the tasks individually. As such, its not feasible to separate it out per task.

One thing you could do to accomplish a similar result, would be to run the test task first manually, so that it would be a cache hit during the sonar run.
