### ISSUE TITLE
@nx/react unitTestRunner returning error for library generation

### ISSUE THREAD

**Issue by viniciusbsneto** [nrwl/nx#17076]
### Current Behavior

I'm trying to execute `nx g @nx/react storybook-host` but it's not possible to generate the library through the CLI. I can't get past the `unitTestRunner` step. There's an error regarding `cypress` (screenshot in the reproduction section). It's possible to create the library with args though. By executing `nx g @nx/react --name=storybook-host --style=none --bundler=vite --unitTestRunner=none`.

### Expected Behavior

@nx/react generator should be able to generate a library with the CLI.

### Steps to Reproduce

1. nx g @nx/react:library my-lib
2. Choose any stylesheet format
3. Choose any bundler
4. Verify that it's not possible to choose the test runner. Instead the following message is returned:
![image](https://github.com/nrwl/nx/assets/17788722/72cff987-00df-46eb-ad8c-4f24ac441545)

### Nx Report

```shell
Node   : 16.20.0
   OS     : linux x64
   yarn   : 3.5.1
   Hasher : Native
   
   nx (global)        : 16.0.0
   nx                 : 16.2.1
   @nx/js             : 16.2.1
   @nx/linter         : 16.2.1
   @nx/workspace      : 16.2.1
   @nx/cypress        : 16.2.1
   @nx/devkit         : 16.2.1
   @nx/eslint-plugin  : 16.2.1
   @nx/react          : 16.2.1
   @nrwl/tao          : 16.2.1
   @nx/vite           : 16.2.1
   @nx/web            : 16.2.1
   typescript         : 5.0.4
```

### Failure Logs

```shell
>  NX  Generating @nx/react:library

✔ Which stylesheet format would you like to use? · none
✔ Which bundler would you like to use to build the library? Choose 'none' to skip build setup. · vite

 >  NX   Property 'unitTestRunner' does not match the schema. 'cypress' should be one of jest,vitest,none.
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by viniciusbsneto** [comment]
There's a similar error with `uiFramework` in the `nx g @nx/storybook:configuration` generator. Should I open another issue?

**Comment by AgentEnder** [comment]
What does your nx.json look like? `cypress` isn't a valid unitTestRunner so it makes sense that it would fail. Its not an option available on the react library generators schema either, so I wouldn't expect it to be present in a prompt

**Comment by viniciusbsneto** [comment]
That makes sense. Is it because my generators are setup like this in `nx.json`?
```
"generators": {
    "@nx/react": {
      "application": {
        "babel": false
      },
      "library": {
        "unitTestRunner": "cypress"
      }
    }
  },
```
If that's the case. Should `nx.json` inform that `cypress` is not an accepted option for the `unitTestRunner`?

**Comment by AgentEnder** [comment]
We can't really give advanced validations for that field, since the generator that runs determines the appropriate values and it could be any number of generators
