### ISSUE TITLE
Adding new library should not mark everything as affected. 

### ISSUE THREAD

**Issue by marekwalach** [nrwl/nx#17082]
### Current Behavior

When you add new library (or app) it makes changes to `tsconfig.base.json` and if you are adding new scope then you must add it to `depConstraints` in `.eslintrc.json` as well. Changes in both those files marks every app and lib in monorepo as affected. This makes using `affected` command useless as most of the times it will run on every target anyway. 

I understand that in some cases changes to those files might actually make meaningful changes everywhere but most of the times chanes to those files are just adding new stuff without breaking changes.  

### Expected Behavior

There should be at least option to exclude those files so that `affected` skips those. 

### Steps to Reproduce

1. Have multiple apps/libs
2. Make any change (e.g. add new lib) to `tsconfig.base.json` or `.eslintrc.json`
3. Run any `nx affected:graph` to see that everything is marked as affected.

### Nx Report

```shell
Node   : 16.19.0
   OS     : darwin arm64
   npm    : 9.2.0
   Hasher : Native
   
   nx                 : 16.2.1
   @nx/js             : 16.2.1
   @nx/jest           : 16.2.1
   @nx/linter         : 16.2.1
   @nx/workspace      : 16.2.1
   @nx/angular        : 16.2.1
   @nx/cypress        : 16.2.1
   @nx/devkit         : 16.2.1
   @nx/eslint-plugin  : 16.2.1
   @nx/node           : 16.2.1
   @nrwl/tao          : 16.2.1
   @nx/webpack        : 16.2.1
   typescript         : 5.0.4
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by abrahamsaanchez** [comment]
If you install or update any package, all projects will also be marked as affected, I think if for example I update `lodash` and I am only using it in one library, that library should be the one that will be marked as affected, not the entire monorepo.

**Comment by Lp-Francois** [comment]
Agree, following 👀

**Comment by marekwalach** [comment]
The only solution  that I found is to add `tsconfig.base.json` and `.eslintrc.json` to `.nxignore` file. It works for me but I don't know if it will have some negative implications.

**Comment by xiongemi** [comment]
this is expected behaviour, any change with tsconfig, package.json, eslint at workspace root will invalidate the cache, so it will mark the projects as affected. as mentioned above, you can add those files in `.nxignore`, https://nx.dev/reference/nxignore which contains the files not taken into account in the affected calculations. the downside would be if your change is actually needed for a task. you can pass in the `--skip-nx-cache` to not use any cache.
