### ISSUE TITLE
Problem building production version of preexisting nextjs app

### ISSUE THREAD

**Issue by brandoncollins7** [nrwl/nx#17084]
### Current Behavior

I am currently porting an old nextjs application into nx. When I run nx serve my-app the application is running file. When I run nx build my-app it appears to compile fine but it is not producing a .next directory in the dist folder and so when I try and start the application I am getting an error that the application has not been compiled and that I should run next build.

Actually, it looks like the .next folder is being generated to the src directory as opposed to the dist output....

### Expected Behavior

I should be able to start application from dist dir using pnpm start. .next folder should be created in the dist output.

### Steps to Reproduce

1. I am not sure, the issue does not seem to occur with a new nextjs generated via a generator and my existing project is quite large and not something I can share....

### Nx Report

```shell
Node   : 18.15.0
   OS     : win32 x64
   pnpm   : 7.32.2
   Hasher : Native

   nx (global)        : 16.1.4
   nx                 : 16.2.1
   @nx/js             : 16.2.1
   @nx/jest           : 16.2.1
   @nx/linter         : 16.2.1
   @nx/workspace      : 16.2.1
   @nx/cypress        : 16.2.1
   @nx/esbuild        : 16.2.1
   @nx/eslint-plugin  : 16.2.1
   @nx/next           : 16.2.1
   @nx/react          : 16.2.1
   @nx/storybook      : 16.2.1
   @nx/web            : 16.2.1
   @nx/webpack        : 16.2.1
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-container : 4.0.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
> When I run nx build my-app it appears to compile fine but it is not producing a .next directory in the dist folder

Can you check your app's `project.json` 

It should have something similar to 
```json
  "build": {
      "executor": "@nrwl/next:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "root": "apps/next-app",
        "outputPath": "dist/apps/next-app"  // <---- Where your build goes
      },
```

You need to **build** your project to create a **production** ready app before attempting to run it

**Comment by ndcunningham** [comment]
Closing because stale. if you still have an issue feel free to open another issue!
