### ISSUE TITLE
need way to migrate down Nx versions

### ISSUE THREAD

**Issue by nhhockeyplayer** [nrwl/nx#17099]
No feature to downgrade Nx exists beyond docs for migration which mute when attempting to manipulate its interface cli

## Description
downgrade Nx

## Motivation
mistakes happen
project workspaces get altered
packages get altered
migrations get altered
attempting to migrate up and then finding out maybe some extensions plugin or package is not compatible with latest Nx

@nxext is a case in point, only works with Nx 14 and not Nx 15 or Nx 16

I initially migrated my project to latest (brought my macbook to Nx 16)
then I tried to create a nxext mobile app and it fails because Nx 16 is already hard installed and it is only compatible with Nx 14

currently there is no way to downgrade global nx release regardless of what migration's impact has occurred to any project

only option is brute force uninstall nx and brute force install nx @ version

this area needs attention, its unfair the field is at such a level of usage and this remains wide open

## Suggested Implementation
help please

## Alternate Implementations
help please

Just trying to run with this at high velocity

**Comment by nhhockeyplayer** [comment]
I have attempted the following to no avail just keeps Nx at latest regardless of minimal changes on my starter workspace

even for prototyping this feature would be useful

but some 3rd party plugins, libraries, extensions are compatible to specific Nx versions and can create a tangle dependent after a developer unknowingly migrates to latest

`nx migrate 14.5.1 --exclude-applied-migration`

currently stuck at Nx 16

can anyone offer what they would do in this situation?

I would like to operate NxExt/ionic-angular for mobile development and its only compatible with Nx 14

thank you for any assist

**Comment by Coly010** [comment]
Attempting to downgrade Nx to previous versions is more complicated than just changing package versions. It would also involve reversing the automatic migrations that get run that alter code and config files. This can be extremely error prone.

Have you tried reverting the commit that upgraded the repo?
