### ISSUE TITLE
building multiple apps in one cmd copying files to wrong output

### ISSUE THREAD

**Issue by jasedwards** [nrwl/nx#171]
Apologies if this is not in the correct place.  I have 3 apps.  I am trying to set something up so that if there is a change in the libs folder that teamcity has a command it can run to build all apps.  For now I just tested it by creating an npm script that calls "ng build --app app1 && ng build --app app2 && ng build --app app3".  All of the apps are built but for some reason the lazy chunks from app 1 and app 2 are deployed to the dist folder for app 3.  apps 1 and 2 also have their files which are correct.  So something like this:

   - app1
      - lazy1
  - app2
      - lazy2
  - app3
      - lazy1
      - lazy2
      - lazy3

**Comment by Yonet** [comment]
@jasedwards are you using the latest version of nx? Do you have a repo for this we can take a look?

**Comment by jasedwards** [comment]
I am on 0.5.2 right now.  I will try to create a public repo in the morning that you can access reproducing it.  The history of my project:  I was on an old version and then updated to 0.5.2.  I had created a couple of those apps before I updated so maybe that is the issue.

**Comment by jasedwards** [comment]
I had to do some manual upgrades before nx-migrate was available and I missed a couple things.  I just went through and fixed all of that and it is working now so the issue was on my end.  Thanks.
