### ISSUE TITLE
nx migrate with multiple packages

### ISSUE THREAD

**Issue by iKrishnaSahu** [nrwl/nx#17101]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

nx migrate with multiple packages

Currently when we run `nx migrate @angular/core@latest @angular/cli@latest @angular/material@latest`, it only runs package update and migration for the first package ie @angular/core.

## Motivation

Now nx is not updating angular dependencies while running `npx nx migrate latest`, it would be great if we can allow nx migrate with multiple packages.

See - https://github.com/nrwl/nx/issues/17100

**Comment by Coly010** [comment]
I'm going to close this issue in preference of #17100 because it's more of a bug that `nx migrate latest` should be updating your angular versions

**Comment by Coly010** [comment]
`nx migrate` should be used to update nx packages. Doing this will update the underlying tools if there are updates to be done.

All nx packages in your repo should be on the same version at all times (with the exception of the nx cloud package).

There's a documented case here to upgrade certain packages to versions that we _do not recommend_ as we cannot confirm compatibility: https://nx.dev/recipes/other/advanced-update#overriding-versions
