### ISSUE TITLE
Next.js assets were copy only with serve target. When building the app those are not copied

### ISSUE THREAD

**Issue by icastillejogomez** [nrwl/nx#17117]
### Current Behavior

With this package.json file:

```json
{
  "name": "website",
  "$schema": "../../../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/bullflix/frontend/website",
  "projectType": "application",
  "targets": {
    "build": {
      "executor": "@nx/next:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "root": "apps/bullflix/frontend/website",
        "outputPath": "dist/apps/bullflix/frontend/website",
        "assets": [
          {
            "input": "libs/bullflix/frontend/ui/themes/src/assets",
            "glob": "**/*",
            "output": "css/theme"
          }
        ]
      },
      "configurations": {
        "development": {
          "outputPath": "apps/bullflix/frontend/website"
        },
        "production": {}
      }
    },
    "serve": {
      "executor": "@nx/next:server",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "website:build",
        "dev": true
      },
      "configurations": {
        "development": {
          "buildTarget": "website:build:development",
          "dev": true
        },
        "production": {
          "buildTarget": "website:build:production",
          "dev": false
        }
      }
    },
    "export": {
      "executor": "@nx/next:export",
      "options": {
        "buildTarget": "website:build:production"
      }
    },
    "test": {
      "executor": "@nx/jest:jest",
      "outputs": ["{workspaceRoot}/coverage/apps/bullflix/frontend/website"],
      "options": {
        "jestConfig": "apps/bullflix/frontend/website/jest.config.ts",
        "passWithNoTests": true
      }
    },
    "lint": {
      "executor": "@nx/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["apps/bullflix/frontend/website/**/*.{ts,tsx,js,jsx}"]
      }
    },
    "stylelint": {
      "executor": "nx:run-commands",
      "options": {
        "parallel": false,
        "commands": ["stylelint 'apps/bullflix/frontend/website/**/*.{css,scss}'"]
      }
    }
  },
  "tags": []
}
```
The content inside the lib located in `libs/bullflix/frontend/ui/themes/src/assets` was copy only running `nx serve` and not `nx build`. This implies that assets need to be record by git and this cause several problems.

### Expected Behavior

If this assets are copied in the serve target, should be copied in the build target also.

### Steps to Reproduce

1. Create a fresh Nx workspace
2. Create a Next.js application
3. Create a Next.js lib with some global SCSS files
4. Set up your project.json file to copy those files
5. Run `nx serve` and look the files are copied inside the public folder
6. Remove those copied files
7. Run build target
8. Where are the files?

### Nx Report

```shell
❯ nx report
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin x64
   npm    : 9.5.1
   Hasher : Native
   
   nx (global)        : 16.0.0
   nx                 : 16.2.1
   @nx/js             : 16.2.1
   @nrwl/js           : 15.8.9
   @nx/jest           : 16.2.1
   @nx/linter         : 16.2.1
   @nrwl/linter       : 15.8.9
   @nx/workspace      : 16.2.1
   @nrwl/workspace    : 15.8.9
   @nx/cypress        : 16.2.1
   @nx/devkit         : 16.2.1
   @nrwl/devkit       : 15.8.9
   @nx/esbuild        : 16.2.1
   @nx/eslint-plugin  : 16.2.1
   @nx/express        : 16.2.1
   @nx/next           : 16.2.1
   @nx/node           : 16.2.1
   @nx/react          : 16.2.1
   @nx/rollup         : 16.2.1
   @nx/storybook      : 16.2.1
   @nrwl/tao          : 16.2.1
   @nx/vite           : 16.2.1
   @nx/web            : 16.2.1
   @nx/webpack        : 16.2.1
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @nx-extend/strapi : 3.5.1
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/js@15.8.9
     - @nrwl/linter@15.8.9
     - @nrwl/workspace@15.8.9
     - @nrwl/devkit@15.8.9
   
   To fix this, run `nx migrate nx@16.2.1`

❯ nx --version
Nx Version:
- Local: v16.2.1
- Global: v16.0.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
After running `nx build` a `dist` folder should be created.

If you look into this dist folder, you should see a folder containing your built application.

I can verify that the assets are being copied correctly into this dist folder.
<img width="204" alt="image" src="https://github.com/nrwl/nx/assets/12140467/74636fa0-3c36-446f-ab21-9b3bcae29b56">

**Comment by icastillejogomez** [comment]
Thanks @Coly010 for the reply. I have one question I hope you can clarify to me... In my Next.js project I import the css (SCSS in my case) file use a normal typescript import like `import styles from './styles.module.scss`. If I ignore on git the `public/css/theme` folder in order to get it from the library with the Nx assets feature.. I'm getting a build when I add some new css file into my library o run my project before run `nx serve`. In this scenario my project does not have the assets folder copied and when I try to build it the files are not there and the typescript transpiler throws an error. I suppose it will occur in the pipeline becase these file are not tracking by git. 

What could be a solution in your opinion for that case?

PD: I have the CSS files in a library cause my UI elements are splited into some libreary following the amotic design pattern so it's necessary for these libraries and the main application access this styles files.

Thank you so much for your time :)
