### ISSUE TITLE
Workspace with React native preset fails

### ISSUE THREAD

**Issue by mchamorro7** [nrwl/nx#17125]
### Current Behavior

When i running `npx create-nx-workspace@latest` and choosing the React Native integrated solution the workspace generation fails with this error:

![image](https://github.com/nrwl/nx/assets/32496861/aab08706-22a4-431b-8c54-7d286abc0dc0)

But when I go to the log error, seems all works correctly:

![image](https://github.com/nrwl/nx/assets/32496861/8ffff4b7-3c63-41ca-8efa-0e1e61324ee8)

I went to the ios folder on the failed workspace, run `pod install` and everything work as expected:

![image](https://github.com/nrwl/nx/assets/32496861/66e315d2-8904-4102-8a73-182ff34413ee)

I only have CocoaPods with Homebrew.

### Expected Behavior

`npx create-nx-workspace@latest `should create an React Native integrated workspace correctly.

### Steps to Reproduce

1. `npx create-nx-workspace@latest`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.12.0
   OS     : darwin x64
   npm    : 8.1.0
   Hasher : Native
   
   nx (global)        : 16.2.1
   nx                 : 16.2.1
   @nx/js             : 16.2.1
   @nx/jest           : 16.2.1
   @nx/linter         : 16.2.1
   @nx/workspace      : 16.2.1
   @nx/detox          : 16.2.1
   @nx/devkit         : 16.2.1
   @nx/eslint-plugin  : 16.2.1
   @nx/react          : 16.2.1
   @nx/react-native   : 16.2.1
   @nrwl/tao          : 16.2.1
   @nx/web            : 16.2.1
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
i tried to run it with latest version and it works for me:
```
npx create-nx-workspace@latest
Need to install the following packages:
  create-nx-workspace@16.2.2
Ok to proceed? (y) y

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Choose what to create                 · integrated
✔ What to create in the new workspace   · react-native
✔ Repository name                       · nx-react-native-16-2-2
✔ Application name                      · mobile
✔ Enable distributed caching to make your CI faster · No

 >  NX   Creating your v16.2.2 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✔ Successfully created the workspace: nx-react-native-16-2-2.

 >  NX   Directory is already under version control. Skipping initialization of git.
```

i think what happened is one off case where pod install failed at the point of application creation.

**Comment by john-redd** [comment]
This issue occurs because a deprecation warning produced by the child process that invokes `pod install` is being routed to stderr. I've documented this issue more in detail in this [issue](https://github.com/nrwl/nx/issues/17249).

**Comment by xiongemi** [comment]
i pushed a pr to not throw error for stderr: https://github.com/nrwl/nx/pull/17382
it should be in the next release 16.4.0

**Comment by mchamorro7** [comment]
Thanks! @xiongemi
