### ISSUE TITLE
Question regarding this solution

### ISSUE THREAD

**Issue by aserdarevic** [nrwl/nx#17130]
I managed to solve my issue first in the reproduction and later in the actual pipeline:

not sure if it was needed but `CI: 'true'` was missing in the pipeline files

 In nx.json there is a property called namedInputs: 
 ```
  "namedInputs": {
    "default": ["{projectRoot}/**/*", "sharedGlobals"],
    "sharedGlobals": [
      "{workspaceRoot}/tsconfig.base.json",
      "{workspaceRoot}/tslint.json",
      "{workspaceRoot}/nx.json",
      "{workspaceRoot}/babel.config.json"
    ],
```
In the previous version it also had a:
`"{workspaceRoot}/angular.json",` 

Removing this and adding the `CI: 'true'`

Seemed to have resolved the issue

_Originally posted by @JelleBruisten in https://github.com/nrwl/nx/issues/15708#issuecomment-1494048902_

Hey @JelleBruisten. I have the same issue with Angular and nx upgrade, where after we upgraded Angular to 16.14.0 and nx to the 15.6.3 versions, nx affected:test is failing for a strange reason. Here you've mentioned that  for you adding `CI: 'true' worked, so I just wonder where did you add this parameter to the root of the nx.json file, or iside of namedInputs parameter?

**Comment by JelleBruisten** [comment]
Not sure if still needed but it was in the pipeline files themself so `mypipeline.yml` for example

**Comment by aserdarevic** [comment]
Thanks @JelleBruisten , I guess that nx commands works differently (or at least there are minor difference) if you set variable CI to true on the pipeline yaml file. Thanks again. But unfortunately it didn't solve my issue I have with Angular and nx upgrade.
