### ISSUE TITLE
Swagger `_OPENAPI_METADATA_FACTORY` not included for nestjs apps

### ISSUE THREAD

**Issue by amustaque97** [nrwl/nx#17133]
### Current Behavior

I'm working on a node backend API NestJS framework where I added `@nestjs/swagger`.  When I run this project or build it. This should automatically add `static _OPENAPI_METADATA_FACTORY` for the DTOs so that I can see those fields on the Swagger docs. But unfortunately, that is not happening in my case. It doesn't show both the request query params and response. 

<img width="1502" alt="image" src="https://github.com/nrwl/nx/assets/21127788/ff26ee68-a416-45b0-8d55-ca477ac35345">

However, if I take out the app from the nx mono repo and convert it to a standalone app in `nestjs` and run the code it works out of the box. I can see all the fields on the Swagger docs. 

### Expected Behavior

When I run the project from my _nx monorepo_ it should include all the required info in the Swagger docs. I assume this might be the issue with the webpack but I'm not 100% sure about it and how to determine whether it's an `nx` issue or `web pack`.

Expected output screenshot:
<img width="1470" alt="image" src="https://github.com/nrwl/nx/assets/21127788/b277e22b-0764-4e28-a3ed-97e44b88f84b">

### GitHub Repo

https://github.com/amustaque97/debug-swagger

### Steps to Reproduce

1. clone the repo 
2. cd into it
3. run `pnpm i`
4. run `pnpm run start debug-swagger`
5. Navigate to the URL in the browser `http://[::1]:3000/swagger#/`
6. Expand each controller/API endpoint and see there is no request/response schema

### Nx Report

```shell
Node : 14.18.3
   OS   : darwin x64
   pnpm : 7.13.5

   nx : 14.5.1
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/eslint-plugin-nx : 14.5.1
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.1
   @nrwl/js : Not Found
   @nrwl/linter : 14.5.1
   @nrwl/nest : 14.8.8
   @nrwl/next : Not Found
   @nrwl/node : 14.5.1
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.5.1
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I have also noticed often times when I generate a new app and follow the same setup, swagger DTO information is generated perfectly. Also, I was going through the internet and found some similar issues in the link https://dev.to/antongolub/nestjs-esbuild-workarounds-99i

Here is the swagger setup in the code.
https://github.com/amustaque97/debug-swagger/blob/main/apps/debug-swagger/src/main.ts#L10-L16

**Comment by AgentEnder** [comment]
Hey @amustaque97, it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

**Comment by amustaque97** [comment]
I tried what you said. Unfortunately no luck :(
