### ISSUE TITLE
@nrwl/cli v16 missing

### ISSUE THREAD

**Issue by kchojhu** [nrwl/nx#17140]
### Current Behavior

When upgrading to Angular 16, I notice that @nrwl/cli v16 is missing.  Last version deployed to npm repo is v15.9.4

https://www.npmjs.com/package/@nrwl/cli?activeTab=versions

I imagine this should've been updated with all v16 version.  For me, I do need v16.1.4 but probably all v16 version should've been there.  I'm sure you guys will fix it so thanks!

### Expected Behavior

All v16 versions available for @nrwl/cli v16 on npm repo

### Steps to Reproduce

1. Go to https://www.npmjs.com/package/@nrwl/cli?activeTab=versions and see that latest version is v15.9.4

### Nx Report

```shell
Not applicable
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
The `@nrwl/cli` package is no longer published. That package was replaced by the `nx` package and has been deprecated for a while now. A migration called `16.0.0-remove-nrwl-cli` should have been run in your workspace when you migrated to Nx v16.0.0+ if you ran the proper migrations with `nx migrate latest` and `nx migrate --run-migrations`.

If for some reason that migration was not run and you still have the package in your `package.json`, please make sure to remove it and replace it with `nx` instead.

**Comment by kchojhu** [comment]
Thanks! I just remove that and then I got this

ng-app@0.0.0 postinstall
> node ./decorate-angular-cli.js


 >  NX   Decoration of the Angular CLI did not complete successfully

Does that mean I need to delete decorate-angular-cli.js? Thanks so much!

**Comment by kchojhu** [comment]
Just did some search.  So looks like I have to change 'ng' in package.json to 'nx', remove 'postinstall', and then I can delete decorate-angular.cli.js.  Not sure what happened on the upgrade.  I upgraded from v14 to v15.9.4 (angular 15 upgrade) then to v16.1.4.  Somehow that upgrade step didn't happen.
