### ISSUE TITLE
Allow skipAllRemotes option to @nrwl/angular:module-federation-dev-server

### ISSUE THREAD

**Issue by Michael-Ziluck** [nrwl/nx#17145]
## Description
Currently there is the ability to ignore individual remotes when running the Module Federation dev server but there is no option to ignore all of them. Maintaining a list of them can become quite cumbersome.

## Motivation
My team uses NRWL's Module Federation system to develop many different apps across almost as many teams. We have a system for dynamically registering new applications that even add Angular routes dynamically as well. The only part left to automate is when trying to do local development. Every time a new remote is added, we need to go into the `package.json` and add a new app name to our `npm run serve` alias or type them _all_ out on the command line. This becomes quite cumbersome.
 
## Suggested Implementation
Instead of requiring a list of remote names, simply accept that none of them need to be in the same repository. Unless I misunderstand the mechanisms at play, this should be even easier to implement than the `--skipRemotes` option.

## Related Issues & PRs
Issues:
- #13064 

PRs:
- #13086 
- #13090

**Comment by Michael-Ziluck** [comment]
@AgentEnder Your fix broke `skipRemotes` entirely. It finds matching projects based on the `projectGraph`. If the projects are in a different repository and are not running (which is my use-case and is also other's use-case as well I'm sure), it won't be able to find them. Then `remotesToSkip` ends up being empty causing an error when you start the project.

**Comment by AgentEnder** [comment]
Can you open a new issue regarding the breakage and it can reference this issue / the pr and be handled that way? I'm out on vacation but am sure it's something @jaysoo or @Coly010 can handle.
