### ISSUE TITLE
Migration to NX 16 Module parse failed React Library

### ISSUE THREAD

**Issue by allencoded** [nrwl/nx#17151]
### Current Behavior

Updated NX 15 to NX 16 and ran all the migrations. Everything appears to be successful until I go to run the application. Our react typescript libraries are throwing the error 

Module parse failed: Unexpected token (13:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

```
 return (
>     <Rails>
```

I looked at the .babelrc for this library and see only one change from `"@nrwl/react/babel",` to `"@nx/react/babel",`. 

```
{
  "presets": [
    [
      "@nx/react/babel",
      {
        "runtime": "automatic",
        "useBuiltIns": "usage"
      }
    ]
  ],
  "plugins": [["styled-components", { "pure": true, "ssr": true }]]
}
```

This library was originally generated in nx 15 and still runs fine under that version. 

### Expected Behavior

When updating to NX16 would expect that it would not throw errors in our nx 15 generated react libraries.

### Steps to Reproduce

1. On a nx 15 repo `nx migrate latest`
2. `nx migrate --run-migrations`

### Nx Report

```shell
Node   : 18.9.0
   OS     : darwin arm64
   npm    : 8.19.1
   Hasher : Native

   nx                 : 16.2.1
   @nx/js             : 16.2.1
   @nx/jest           : 16.2.1
   @nx/linter         : 16.2.1
   @nx/workspace      : 16.2.1
   @nx/cypress        : 16.2.1
   @nx/devkit         : 16.2.1
   @nrwl/devkit       : 15.9.4
   @nx/eslint-plugin  : 16.2.1
   @nx/express        : 16.2.1
   @nx/next           : 16.2.1
   @nx/node           : 16.2.1
   @nx/plugin         : 16.2.1
   @nx/react          : 16.2.1
   @nrwl/tao          : 16.2.1
   @nx/web            : 16.2.1
   @nx/webpack        : 16.2.1
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @nx-extend/gcp-functions : 6.5.0
   @nx-tools/nx-container   : 4.0.3
   ---------------------------------------
   Local workspace plugins:
   	 @mono/cloudrun-deploy
   	 @mono/k8s-deploy
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/devkit@15.9.4

   To fix this, run `nx migrate nx@16.2.1`
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
@allencoded Do you mind sharing your `webpack.config.js` file and your `project.json` file for the app?

My initial thoughts is that either the webpack or the project config is incorrect. 

The `project.json` should set `isolatedConfig: true` for the build target. Setting this option to `false` disables the deprecated behavior of Nx applying its own webpack configuration automatically.

The `webpack.config.js` file should look something like this:


```js
const { composePlugins, withNx } = require('@nx/webpack');
const { withReact } = require('@nx/react');

// Nx plugins for webpack.
module.exports = composePlugins(withNx(), withReact(), (config) => {
  return config;
});
```

There was a migration back in 15.6 to set both of these configurations up, but perhaps it was skipped or wasn't applied correctly?

**Comment by allencoded** [comment]
We don't alter or change anything out of the box for the `webpack.config.js` file. Because of that we don't have any in our react application/libs code.

I checked the `project.json` we certainly don't have a `isolatedConfig: true` set in our build target. In fact its nowhere in the project. 

```
    "build": {
      "executor": "@nx/next:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "root": "apps/frontend/web-admin",
        "outputPath": "dist/apps/frontend/web-admin",
        "generatePackageJson": true
      },
      "configurations": {
        "development": {
          "outputPath": "apps/frontend/web-admin"
        },
        "production": {}
      }
    },
```

**Comment by jaysoo** [comment]
@allencoded Ah okay, it's a Next.js project. Ignore what I said about webpack config and `isolatedModules`. Let me take a look.

**Comment by allencoded** [comment]
@jaysoo Thank you this helped point me in the right direction. The withNx() function we had was calling the wrong nxconfig and after resolving that our migration worked perfectly.
