### ISSUE TITLE
cannot generate nx g @nx/angular:service  with nx version 16.2.1 also no class 

### ISSUE THREAD

**Issue by koempf** [nrwl/nx#17162]
### Current Behavior

NX   Cannot find module '../adapter/compat'

   Require stack:
   - /home/isc-kst/git_checkout/nsis-client/node_modules/nx/src/command-line/generate/generate.js
   - /home/isc-kst/git_checkout/nsis-client/node_modules/nx/src/command-line/generate/command-object.js
   - /home/isc-kst/git_checkout/nsis-client/node_modules/nx/src/command-line/nx-commands.js
   - /home/isc-kst/git_checkout/nsis-client/node_modules/nx/bin/init-local.js
   - /home/isc-kst/git_checkout/nsis-client/node_modules/nx/bin/nx.js
   - /home/isc-kst/.config/yarn/global/node_modules/nx/bin/nx.js

### Expected Behavior

I want to generate an Service or class 

### Steps to Reproduce

1.
nx g @nx/angular:service ...

### Nx Report

```shell
NX   Cannot find module '../adapter/compat'

   Require stack:
   - /home/isc-kst/git_checkout/nsis-client/node_modules/nx/src/command-line/generate/generate.js
   - /home/isc-kst/git_checkout/nsis-client/node_modules/nx/src/command-line/generate/command-object.js
   - /home/isc-kst/git_checkout/nsis-client/node_modules/nx/src/command-line/nx-commands.js
   - /home/isc-kst/git_checkout/nsis-client/node_modules/nx/bin/init-local.js
   - /home/isc-kst/git_checkout/nsis-client/node_modules/nx/bin/nx.js
   - /home/isc-kst/.config/yarn/global/node_modules/nx/bin/nx.js
```

### Failure Logs

```shell
NX   Cannot find module '../adapter/compat'

   Require stack:
   - /home/isc-kst/git_checkout/nsis-client/node_modules/nx/src/command-line/generate/generate.js
   - /home/isc-kst/git_checkout/nsis-client/node_modules/nx/src/command-line/generate/command-object.js
   - /home/isc-kst/git_checkout/nsis-client/node_modules/nx/src/command-line/nx-commands.js
   - /home/isc-kst/git_checkout/nsis-client/node_modules/nx/bin/init-local.js
   - /home/isc-kst/git_checkout/nsis-client/node_modules/nx/bin/nx.js
   - /home/isc-kst/.config/yarn/global/node_modules/nx/bin/nx.js
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
This is fixed on master, but waiting to be released. You can see: https://github.com/nrwl/nx/commit/d786fae2d017333bd1c8df98e0ab69b3bc37aec6

It is in the latest betas, if you are comfortable trying them.

**Comment by vamshi130** [comment]
I am also facing the same error is that resolved?
Thanks

**Comment by AgentEnder** [comment]
It should be fixed in latest
