### ISSUE TITLE
Creating a publishable library using @nx/js:library doesn't build type declarations

### ISSUE THREAD

**Issue by 72gm** [nrwl/nx#17160]
### Current Behavior

When building a publishable typescript library that was built with @nx/js:library it doesn't build the typescript declaration files when building

It uses swc compiler and just ignores the TS files

I had to change to a react library to get this to work... but the @nx/react:library doesn't have the publish command even if you generate it with the publishable flag (so you have to do npm publish to get it to work)

### Expected Behavior

its a publishable library and if you type "create nx typescript library" it recommends @nx/js:library ... so surely this should generate type declarations???

### Steps to Reproduce

1.
Create a publishable typescript library using the above method
Add a typescript interface 
Export it in index.ts
build the library

no typescript declarations............

### Nx Report

```shell
Node   : 18.16.0
   OS     : win32 x64
   npm    : 9.5.1
   Hasher : Native
   
   nx                 : 16.2.1
   @nx/js             : 16.2.1
   @nx/linter         : 16.2.1
   @nx/workspace      : 16.2.1
   @nx/cypress        : 16.2.1
   @nx/devkit         : 16.2.1
   @nx/eslint-plugin  : 16.2.1
   @nx/react          : 16.2.1
   @nx/rollup         : 16.2.1
   @nrwl/tao          : 16.2.1
   @nx/vite           : 16.2.1
   @nx/web            : 16.2.1
   typescript         : 5.0.4
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by PaulACoroneos** [comment]
This also applies to @nx/js:swc as well. I actually had to bail out of using swc compiler exactly for the above issue. Probably related to https://github.com/nrwl/nx/issues/9059 as well
