### ISSUE TITLE
[Feature request]: Allow workspace-lint to be configurable

### ISSUE THREAD

**Issue by ahnpnl** [nrwl/nx#1717]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

As discussed in #1705 , `workspace-lint` should have possibility to configure. The use case is:
a project might have a styling-only folder within `libs`. In this case, `workspace-lint` fail because it isn't possible to exclude folders.

`workspace-lint` should have possibility to configure to exclude folders, similar to `tslint` exclude. This will provide more flexible options to the users to customize their workspace.

## Current Behavior

`workspace-lint` fail when running lint for a project with a `libs` structure similar to https://github.com/nstudio/xplat-sample-ionic-web/tree/master/libs

## Failure Information (for bugs)

**N.A.**

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

* Clone example https://github.com/ahnpnl/workspace-lint
* Install dependencies with yarn
* Run yarn lint.
* Observe error in the console:
![image](https://user-images.githubusercontent.com/27772165/63005345-9a921d80-be7c-11e9-94e6-368af6fc4d3c.png)

### Context

Please provide any relevant information about your setup:

- version of Nx used: 8.4.8
- 3rd-party libraries and their versions: **N.A.**
- and most importantly - a use-case that fails

Example repo: https://github.com/ahnpnl/workspace-lint

### Failure Logs

As screenshot above

## Other

**N.A.**

**Comment by jaysoo** [comment]
@vsavkin @FrozenPandaz Sounds reasonable. We would adding a config option in `nx.json` to exclude files for `workspace-lint`. What do you think?

**Comment by jaysoo** [comment]
@ahnpnl Nx now supports a `.nxignore` file that uses the same glob format as `.gitignore`. Files/directories that match an entry in this file will not be used in workspace lint.

**Comment by ahnpnl** [comment]
Thank you. That's great !

**Comment by jaysoo** [comment]
Looks like new docs will need to be deployed, but this feature should be mentioned here https://nx.dev/angular/fundamentals/monorepos-automation (https://github.com/nrwl/nx/blob/master/docs/angular/fundamentals/monorepos-automation.md).

**Comment by johannesschobel** [comment]
Dear @jaysoo ,
the `.nxignore` file is not working for me. It still tries to lint some files in `**/generated` which contains auto-generated sources from 3rd-party-packages. Obviously, those files shall not be processed.

Any ideas?

**Comment by billyjov** [comment]
Same here. `.nxignore` not working for me with the latest version.

**Comment by sijakret** [comment]
does .nxignore only affect linting and no other operations like build, test etc..?  if so i think the name might be a bit missleading

**Comment by ahnpnl** [comment]
it seems like `.nxignore` doesn't impact how ESLint works but only impacts `workspace-lint`, which is a different command
