### ISSUE TITLE
npmScope in nx.json showing as deprecated

### ISSUE THREAD

**Issue by william-kerr** [nrwl/nx#17173]
### Current Behavior

The `npmScope` variable is showing as deprecated in nx.json.

You can see the code here:
https://github.com/nrwl/nx/blob/5ef9ea68cda9e9027038b49951ecbd139704f251/packages/nx/src/config/nx-json.ts#L71

It mentions getNpmScope, which is located here:
https://github.com/nrwl/nx/blob/5ef9ea68cda9e9027038b49951ecbd139704f251/packages/workspace/src/utilities/get-import-path.ts#L12

```
function getNpmScope(tree: Tree) {
  const nxJson = readNxJson(tree);

  // TODO(v17): Remove reading this from nx.json
  if (nxJson.npmScope) {
    return nxJson.npmScope;
  }

  const { name } = tree.exists('package.json')
    ? readJson<{ name?: string }>(tree, 'package.json')
    : { name: null };

  if (name?.startsWith('@')) {
    return name.split('/')[0].substring(1);
  }
}
```

The package.json located in the workspace root directory should be able to contain a name that does not begin with @.  Currently, if I remove `npmScope` from nx.json, and my package.json name isn't scoped, getNpmScope doesn't return anything.

### Expected Behavior

I should be able to have a name that doesn't begin with @ in package.json in the workspace root directory, and I should be able to remove deprecated `npmScope` from nx.json.  Then, when I generate something, it should be scoped with the name from package.json.

### GitHub Repo

https://github.com/nrwl/nx

### Steps to Reproduce

1. Use unscoped name in package.json in workspace root directory.
2. Remove `npmScope` from nx.json.
3. Generate something with a command like `nx generate @nx/js:library example --unitTestRunner=jest --no-interactive`.
4. Notice that what's generated isn't scoped from the name in package.json like it would have been if `npmScope` had been defined in nx.json.

### Nx Report

```shell
Node   : 18.16.0
   OS     : linux x64
   yarn   : 1.22.19
   Hasher : Native
   
   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/cypress        : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nx/next           : 16.2.2
   @nx/react          : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/web            : 16.2.2
   typescript         : 5.0.4
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by william-kerr** [comment]
> Hey @william-kerr 👋.
> 
> This is intentional behavior, if you would like to have packages generate with a scope, we'd recommend having a name along the lines of `@{workspaceScope}/source` or similar for the root package. `npmScope` is indeed deprecated, and will eventually be removed in favor of only reading the scope from the root package.json.

What was the "intentional" reason for forcing a root package to have a name like `@{workspaceScope}/source` instead of just `{workspaceScope}`?  For example, let's say a business is named **acme** and there's a monorepo for all of **acme**'s code, the name might be `acme`.  What's a default suggestion for a scoped name then, `@acme/monorepo`?  That name doesn't seem that ideal.  Is there some standard naming convention for a monorepo package name?

**Comment by AgentEnder** [comment]
If your root package is itself a publishable project, you may not want it to be named the same as the scope for your other projects. For instance, this repo used to have an @nrwl scope. If we had the main `nx` package as a root project rather than in `packages` folder, that scope is different.

You can specify the exact import path you want in most cases with `--import-path`, if for some reason you don't want to have the name in your root package.json.
