### ISSUE TITLE
Node executor doesn't work with a webpack build target

### ISSUE THREAD

**Issue by marcus-sa** [nrwl/nx#17170]
### Current Behavior

Using node executor with a webpack build target doesn't do anything. It's simply stuck.

### Expected Behavior

For it to run correctly. It worked fine with version 16.1.4.

### Steps to Reproduce

Setup an app with a webpack build target for the node executor.

### Nx Report

```shell
Node   : 20.1.0
   OS     : darwin x64
   pnpm   : 8.5.1
   Hasher : Native
   
   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/esbuild        : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nx/node           : 16.2.2
   @nx/react          : 16.2.2
   @nx/rollup         : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/web            : 16.2.2
   @nx/webpack        : 16.2.2
   nx-cloud           : 16.0.5
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   @nrwl/remix         : 16.1.2
   @nx-tools/nx-prisma : 4.0.3
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Hi @marcus-sa ! Can you please share a minimum reproduction repository, or at least the steps you followed? Or maybe how your `project.json` looks like? This will help us debug your issue more easily! At first try, I could not reproduce your issue. Here is my reproduction repository: [https://github.com/mandarini/webpack-node-nx](https://github.com/mandarini/webpack-node-nx). It. seems that my Node app can build successfully with `webpack`
