### ISSUE TITLE
NextJS custom server failing to find config in jest

### ISSUE THREAD

**Issue by olafkrawczyk** [nrwl/nx#17178]
### Current Behavior

I'm creating this with version 16.1.4 because on the latest (version 16.2.2) I couldn't get the custom server running. Probably because of https://github.com/nrwl/nx/issues/17123.

I'm running custom server in NextJS app. Sever creation is moved to separate function. This function is also used in the tests.  To test some endpoints response. 

While build & serve custom server is working just fine. While running tests I'm getting error that next config could not be found. 

On version [15.8.5](https://npmjs.com/package/@nrwl/next) prior to refactor I had no issues with config being unavailable in the tests.

### Expected Behavior

Config for the Next application with custom server should be available while running tests.

### GitHub Repo

https://github.com/olafkrawczyk/nx-next-bug

### Steps to Reproduce

1. Clone repo
2. run `npm instal`
3. run tests via `NODE_ENV=development NODE_OPTIONS=--experimental-vm-modules npx nx test app --skip-nx-cache --verbose`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.14.2
   OS     : darwin x64
   npm    : 9.6.0
   Hasher : Native
   
   nx                 : 16.1.4
   @nx/js             : 16.1.4
   @nx/jest           : 16.1.4
   @nx/linter         : 16.1.4
   @nx/workspace      : 16.1.4
   @nx/cypress        : 16.1.4
   @nx/devkit         : 16.1.4
   @nx/eslint-plugin  : 16.1.4
   @nx/next           : 16.1.4
   @nx/react          : 16.1.4
   @nrwl/tao          : 16.1.4
   @nx/web            : 16.1.4
   typescript         : 5.0.4
```

### Failure Logs

```shell
> nx run app:test

● Validation Warning:

  Unknown option "coverageDirectory" with value "../../coverage/packages/app" was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration

(node:51544) ExperimentalWarning: VM Modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 FAIL   app  packages/app/specs/index.spec.tsx
  Index
    ✕ inits custom server for testing (827 ms)

  ● Index › inits custom server for testing

    Could not determine the config for this Next application.

      at getNxContext (../next/plugins/with-nx.ts:108:11)
      at ../next/plugins/with-nx.ts:199:11
      at fulfilled (../../node_modules/tslib/tslib.js:164:62)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.791 s
Ran all test suites.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

In the bug repo only thing I did is to move server creation to separate function and invoke that function in the test. All code was generated by nx plugins.

**Comment by ndcunningham** [comment]
This should be addressed in the next version of Nx which maybe be released this week or next.
You should not have a config error. Here is the reference PR: https://github.com/nrwl/nx/pull/17819
