### ISSUE TITLE
--publishable doesn't work with `@nrwl/react:lib`

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#1719]
## Expected Behavior

Please describe the behavior you are expecting

Following, should generate npm-publishable library package ( generating ambient types etc )
```
yarn nx g @nrwl/react:lib shared --publishable=true --linter=eslint
```

## Current Behavior

`--publishable` is ignored and we get "standard nx" monorepo lib 

### Context

Please provide any relevant information about your setup:

- version of Nx used `8.4.8`
- 3rd-party libraries and their versions
- and most importantly - a use-case that fails

**A minimal reproduce scenario using allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

related https://github.com/nrwl/nx/issues/1521

**Comment by jaysoo** [comment]
Dup of #1521. Let's keep the discussion there. :)
