### ISSUE TITLE
Add ability to specify library name not based on directory path using @nrwl/react:library

### ISSUE THREAD

**Issue by sir-captainmorgan21** [nrwl/nx#17207]
- [ X] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Basically looking for the same feature that was introduced as a result of this feature request for @nx/nest: #14654 

But just to keep the descr here as well. Basically copying over the other feature request:

Using the following command, the following output is generated:

`yarn nx generate @nrwl/react:library item --directory=api/feature --no-interactive --dry-run`

```
CREATE libs/api/feature/item/README.md
CREATE libs/api/feature/item/src/index.ts
CREATE libs/api/feature/item/tsconfig.json
CREATE libs/api/feature/item/tsconfig.lib.json
CREATE libs/api/feature/item/project.json
UPDATE tsconfig.base.json
CREATE libs/api/feature/item/.eslintrc.json
CREATE libs/api/feature/item/jest.config.ts
CREATE libs/api/feature/item/tsconfig.spec.json
CREATE libs/api/feature/item/src/lib/api-feature-item.module.ts
```

However, the module file that is created contains the directory path name. But what if I just wanted it to be called item.module.ts rather than api-feature-item.module.ts?

It doesn't look like this is possible with the current implementation of the CLI.

## Motivation
Following this NX implementation [here](https://gist.github.com/trungk18/7ef8766cafc05bc8fd87be22de6c5b12), where every lib has a feature, data-access, utils sub-libs, it would be convenient to have shorter file names within these sub-libs. It makes so sense to have such long names IMO, since the directory paths are different, there would be no collisions.

It's not only the file names that are extra long but the class names within these files follow the same structure, only using camel case. (i.e., class ApiFeatureItemController for example)

## Suggested Implementation
Add a `simpleName` generator option to @nx/react:library to not include the directory path in the file name

**Comment by mandarini** [comment]
Hi @sir-captainmorgan21 ! Thanks for the feature request! I see you are willing to implement this feature! Do you want to get started on this, and tag me on your PR to help you out if you need to?

**Comment by sir-captainmorgan21** [comment]
@mandarini For sure! And yes. I actually have the work done, going through testing now. Will have a PR shortly. Ill tag you. Thanks!
