### ISSUE TITLE
enforce-module-boundaries hangout with incorrect prisma import

### ISSUE THREAD

**Issue by robertIsaac** [nrwl/nx#17201]
### Current Behavior

using `import { User } from '.prisma/client';`, make nx lint hangout forever if there is `enforce-module-boundaries` rule

### Expected Behavior

for the lint to throw error for that import

I think it can also succeed, since it's technically correct import, since inside `node_modules` there is actually package `.prisma/client`

but it definitely shouldn't hang forever, it took me ages to figure out that silly mistake

### GitHub Repo

https://github.com/robertIsaac/enforce-module-boundaries-lint-reprod

### Steps to Reproduce

1. clone the reproduce project
2. run `nx lint enforce-module-boundaries-lint-reprod` it will hangout
3. go to `apps/enforce-module-boundaries-lint-reprod/src/app/app.service.ts`
4. comment line 2, uncomment line 4
5. run again `nx lint enforce-module-boundaries-lint-reprod` it will work fine

### Nx Report

```shell
Node   : 18.16.0
   OS     : win32 x64
   npm    : 9.6.7
   Hasher : Native

   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nx/nest           : 16.2.2
   @nx/node           : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/webpack        : 16.2.2
   typescript         : 5.0.4
```

### Failure Logs

```shell
there is no logs, it just hangout forever (waiting more than 10 minutes)
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by meeroslav** [comment]
Hey @robertIsaac can you bring back the test repo?

Sorry for not taking this earlier.

**Comment by robertIsaac** [comment]
> Hey @robertIsaac can you bring back the test repo?
> 
> Sorry for not taking this earlier.

What do you mean?
I can access it normally
