### ISSUE TITLE
Broken recipe Module Federation with SSR for Angular

### ISSUE THREAD

**Issue by LadaBr** [nrwl/nx#17216]
### Current Behavior

I just follow all steps in: https://nx.dev/recipes/module-federation/module-federation-with-ssr
and when I run **npx nx serve-ssr store --devRemotes=checkout** it throws error:

**Error: Shared module is not available for eager consumption: 4112**

4112 = @angular/platform-server

It is required as eager module because it is imported in main.server.ts for bootstrap of ngExpressEngine

### Expected Behavior

It should start the server without any errors.

### Steps to Reproduce

1. Follow steps in https://nx.dev/recipes/module-federation/module-federation-with-ssr
2. Get error on last step

### Nx Report

```shell
Node   : 20.2.0
   OS     : win32 x64
   npm    : 9.6.6
   Hasher : Native

   nx (global)        : 16.2.2
   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/angular        : 16.2.2
   @nx/cypress        : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/web            : 16.2.2
   @nx/webpack        : 16.2.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @nguniversal/builders       : 16.0.2
   @nguniversal/express-engine : 16.0.2
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by hamedbavafa** [comment]
Hi @LadaBr, We also had this issue #15562 . The only workaround we could have was to run it inside a docker container. You might also have the option to mark certain modules as 'eager' in federation configs; However, this is somewhat cumbersome as you need to do this manually for each problematic dependency. Hope it helps.

**Comment by hardikpatel043** [comment]
Any update on this? I am still facing this problem?

**Comment by hardikpatel043** [comment]
Issue still persist
