### ISSUE TITLE
nx should be hermetic

### ISSUE THREAD

**Issue by dudicoco** [nrwl/nx#17214]
## Description

NX should automatically install required libraries and dependencies in an isolated environment.
The [go plugin](https://github.com/nx-go/nx-go) for example requires go to be installed on your system, which could produce different results between different systems with different go versions.

## Motivation

Building in a hermetic environment gives a higher guarantee of reproducible builds that are not affected by the system environment and libraries.

## Suggested Implementation

Perhaps a similar implementation to Bazel's:
https://bazel.build/basics/hermeticity
https://bazel.build/docs/sandboxing

## Alternate Implementations

Docker images could be used for isolation, but those have their own downsides and complexity involved.

**Comment by AgentEnder** [comment]
Hey @dudicoco! Managing the tools installed to the machine is outside the scope of Nx (for the time being at least).

At the plugin level this could be managed by scaffolding apps with an input that references the installed go version, or a custom hasher which checks the go version, either way.

**Comment by AgentEnder** [comment]
Installation of developer tooling (e.g. node, go, rust, .NET) isn't part of Nx's scope. We don't install node_modules for you either, as another example. The hasher + cache can take inputs into account that would invalidate the cache when the node, dotnet, go version etc are different, but that's at the plugin level.

We aren't a dev container, "just" task orchestration and codegen

**Comment by dudicoco** [comment]
@AgentEnder again I will clarify that this is not developer tooling, these are tools that are required by the build system in order to guarantee hermetic, deterministic and reproducible builds, no matter on which system the build runs on.
This prevents issues where the build fails on one machine but passes on another machine.
I have also included links to Bazel's docs on the subject.

The real question here is if NX is intended to be a hermetic, deterministic and reproducible build tool or not.
