### ISSUE TITLE
how to enable enable SSL on my next app

### ISSUE THREAD

**Issue by alihussain575** [nrwl/nx#17210]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
I have an nx react app and an nx next js app. I have enabled SSL on the React app but for some reason, I cannot use it in the next js app. So Is there a way to enable SSL on my next app? It should run my Next js app on `https` not `http` as my React app does.

**Comment by Coly010** [comment]
Looking through the Next.js docs, they do not support any flag that would enable SSL. 

If you think this is something they should offer, you can create an issue on their repo: https://github.com/vercel/next.js/issues/new/choose

**Comment by alihussain575** [comment]
@Coly010 

I see what you are trying to say but Next js does support enabling SSL as I have done it only on a Next app which is not in the NX workspace an it works fine for me

**Comment by Coly010** [comment]
Can you replicate those steps for the app in Nx?

I've seen a blog post that shows a manual implementation of changing the server code to use https server, but that's outside the bounds of what nx does.

**Comment by alihussain575** [comment]
@Coly010 Okay Let me try implementing it manually it

**Comment by puku0x** [comment]
1. Generate a custom server
<img width="519" alt="image" src="https://github.com/nrwl/nx/assets/2607019/2f439df1-ea87-4f3b-a9f6-f107c55d9d96">


2. Switch from `http` to `https`
```ts
/*
 * This is only a minimal custom server to get started.
 * You may want to consider using Express or another server framework, and enable security features such as CORS.
 *
 * For more examples, see the Next.js repo:
 * - Express: https://github.com/vercel/next.js/tree/canary/examples/custom-server-express
 * - Hapi: https://github.com/vercel/next.js/tree/canary/examples/custom-server-hapi
 */
import { createServer } from 'https';
import { parse } from 'url';
import * as path from 'path';
import next from 'next';
import { readFileSync } from 'fs';

// Next.js server options:
// - The environment variable is set by `@nx/next:server` when running the dev server.
// - The fallback `__dirname` is for production builds.
// - Feel free to change this to suit your needs.
const dir = process.env.NX_NEXT_DIR || path.join(__dirname, '..');
const dev = process.env.NODE_ENV === 'development';

// HTTP Server options:
// - Feel free to change this to suit your needs.
const hostname = process.env.HOST || 'localhost';
const port = process.env.PORT ? parseInt(process.env.PORT) : 4200;

async function main() {
  const nextApp = next({ dev, dir });
  const handle = nextApp.getRequestHandler();

  await nextApp.prepare();

  const httpsOptions = {
    key: readFileSync('./localhost-key.pem'),
    cert: readFileSync('./localhost.pem'),
  };

  const server = createServer(httpsOptions, (req, res) => {
    const parsedUrl = parse(req.url ?? '', true);
    handle(req, res, parsedUrl);
  });

  server.listen(port, hostname);

  console.log(`[ ready ] on https://${hostname}:${port}`)
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
```

3. Fix `project.json`

```js
"serve": {
  :
  "dependsOn": ["build-custom-server"]
},
```
```js
"build-custom-server": {
  "executor": "@nx/js:tsc",
  "defaultConfiguration": "production",
  "options": {
    "outputPath": "dist/apps/<your-nextjs-app-name>",
    "outputFileName": "server/main.js",
    "main": "apps/<your-nextjs-app-name>/server/main.ts",
    "tsConfig": "apps/<your-nextjs-app-name>/tsconfig.server.json",
    "clean": false,
    "assets": []
  },
  :
```

**Comment by alihussain575** [comment]
@puku0x 

Apparently, My project is using `@nrwl/next` and it has been generated through the command `nx generate @nrwl/next` so I can not generate it a custom server using the above command
