### ISSUE TITLE
question: how to use custom .babelrc or babel.config.js with @nrwl/react

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#1721]
**Question:**
Is `babel.config.js`/`.babelrc` supported per lib/app (similarily to eslint/tsconfig) ? 
if no, is it on the roadmap ?

thanks!

**Comment by jaysoo** [comment]
Hi @Hotell, yes the you can create a custom `.babelrc` file for your React app! Make sure it is located in your app's folder (e.g. `apps/my-app/.babelrc`, and it'll be picked up.

---

Also, make sure you specify our provided webpack config for using babel in your `workspace.json` file. You should see an entry like this:

```
"webpackConfig": "@nrwl/react/plugins/babel"
```

If you created a React workspace when using `create-nx-workspace`, then babel should already be set up for you.

Let us know if you run into any problems.
