### ISSUE TITLE
cache miss

### ISSUE THREAD

**Issue by robertIsaac** [nrwl/nx#17228]
### Current Behavior

there is a lot of cache miss
I finally discovered why
I ran `nx graph --focus=fe --file=output.json` to compare the output between the my runs
I found this line `import firebase from 'firebase/compat/app';` sometimes output `"target": "npm:firebase/compat/app"` and some other times `"target": "npm:firebase"`
even though the hash of the file is the same 
here is the comparison using WebStorm
![image](https://github.com/nrwl/nx/assets/14242054/ee89ed48-1252-43bc-a167-aafea2aac058)
 

### Expected Behavior

the output to always be `"target": "npm:firebase"` and the cache to always hit

### Steps to Reproduce

1. it's hard to reproduce, because it flaky, sometimes it happens then it stop happening

### Nx Report

```shell
Node   : 18.16.0
   OS     : win32 x64
   npm    : 9.6.7
   Hasher : Native

   nx                 : 16.2.1
   @nx/js             : 16.2.1
   @nx/jest           : 16.2.1
   @nx/linter         : 16.2.1
   @nx/workspace      : 16.2.1
   @nx/angular        : 16.2.1
   @nx/cypress        : 16.2.1
   @nx/devkit         : 16.2.1
   @nx/eslint-plugin  : 16.2.1
   @nx/nest           : 16.2.1
   @nx/node           : 16.2.1
   @nrwl/tao          : 16.2.1
   @nx/webpack        : 16.2.1
   nx-cloud           : 16.0.5
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   @nguniversal/builders       : 16.0.2
   @nguniversal/express-engine : 16.0.2
   ng-mocks                    : 14.10.1
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by meeroslav** [comment]
Thank you @robertIsaac for reporting this issue. Can you provide a minimal repo where this can be reproduced (even if only occasionally due to flakyness)?

Can you try running `npx nx reset` and check if that changes anything?

The expected external node is `npm:firebase`

**Comment by robertIsaac** [comment]
> Thank you @robertIsaac for reporting this issue. Can you provide a minimal repo where this can be reproduced (even if only occasionally due to flakyness)?
> 
> Can you try running `npx nx reset` and check if that changes anything?
> 
> The expected external node is `npm:firebase`

I can give you access to my repo if that helps

**Comment by robertIsaac** [comment]
running `nx reset` then running `nx graph --focus=fe --file=output.json` output the dependency as `npm:firebase`
but if I deleted the `login.component.ts` and ran `git reset --hard` to restore it then called `nx graph --focus=fe --file=output.json` it will output  `npm:firebase/compat/app`

**Comment by meeroslav** [comment]
> I can give you access to my repo if that helps

Please do, so I can try to reproduce it and see where this is coming from.

**Comment by robertIsaac** [comment]
> > I can give you access to my repo if that helps
> 
> Please do, so I can try to reproduce it and see where this is coming from.

done, I also sent you messages in twitter on how to reproduce it
