### ISSUE TITLE
Project file not picked up after migration to nx 16 if the source dir is in gitignore

### ISSUE THREAD

**Issue by Azbesciak** [nrwl/nx#17239]
### Current Behavior

I have a lib project which is generated on the CICD from other code. The generated dir is in `.gitignore`.
Before there was the `angular.json` which contained path to the `project.json` file in the generated placeholder dir (everything was working, there was a mock dir with empty `project.json` file, updated before the lib was generated).

Since `angular.json` was removed, I suppose you choose to search for `project.json` files - ok.
But it does not pick up my gen project, even after it is generated.
Even when I add an exclamation for that file like
```
/libs/my-gen-lib/**/*
!/libs/my-gen-lib/project.json
```
https://stackoverflow.com/questions/5533050/gitignore-exclude-folder-but-include-specific-subfolder

Not to mention that the project.json file is committed to the repository.

### Expected Behavior

The generated project is picked up

### Steps to Reproduce

1. create 2 projects
2. add the second one as a dir to `.gitignore`, with exception for the `project.json` there as described in the current behavior

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template
                                                            
   Node   : 18.14.0                                         
   OS     : win32 x64                                       
   npm    : 9.3.1                                           
   Hasher : Native                                          
                                                            
   nx             : 16.2.2                                  
   @nx/js         : 16.2.2                                  
   @nx/jest       : 16.2.2                                  
   @nx/linter     : 16.2.2                                  
   @nx/workspace  : 16.2.2                                  
   @nx/angular    : 16.2.2                                  
   @nx/cypress    : 16.2.2                                  
   @nx/devkit     : 16.2.2
   @nrwl/tao      : 16.2.2
   @nx/webpack    : 16.2.2
   typescript     : 5.0.4
   ---------------------------------------
   Community plugins:
   @ngneat/transloco  : 4.2.7
   devextreme-angular : 23.1.2-beta
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Hey this is semi-expected, and a known issue. Its being tracked here: https://github.com/nrwl/nx/issues/15760
