### ISSUE TITLE
npx nx init  breaking

### ISSUE THREAD

**Issue by leopascual** [nrwl/nx#17234]
### Current Behavior

 >  NX   🐳 Nx initialization

 >  NX   🧑‍🔧 Please answer the following questions about the scripts found in your package.json in order to generate task runner configuration

/Users/lpascual/.npm/_npx/973fb08ee51bb939/node_modules/enquirer/lib/types/array.js:38
      throw new Error('At least one choice must be selectable');

### Expected Behavior

Following https://nx.dev/recipes/adopting-nx-angular/angular-multiple steps on video, breaks when trying to init nx on mono repo, with two angular cli apps in apps folder. 

### GitHub Repo

nrwl/nx 

### Steps to Reproduce

1.   minute 9:15 of site video https://nx.dev/recipes/adopting-nx-angular/angular-multiple 

### Nx Report

```shell
╰─ sudo npx nx init                
Need to install the following packages:
  nx@16.2.2
Ok to proceed? (y) y

 >  NX   🐳 Nx initialization


 >  NX   🧑‍🔧 Please answer the following questions about the scripts found in your package.json in order to generate task runner configuration

/Users/lpascual/.npm/_npx/973fb08ee51bb939/node_modules/enquirer/lib/types/array.js:38
      throw new Error('At least one choice must be selectable');
            ^

Error: At least one choice must be selectable
    at MultiSelect.reset (/Users/lpascual/.npm/_npx/973fb08ee51bb939/node_modules/enquirer/lib/types/array.js:38:13)
    at async MultiSelect.initialize (/Users/lpascual/.npm/_npx/973fb08ee51bb939/node_modules/enquirer/lib/types/array.js:25:5)
    at async /Users/lpascual/.npm/_npx/973fb08ee51bb939/node_modules/enquirer/lib/prompt.js:236:7

Node.js v18.16.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Package JSON file
{
    "name": "utm-nx-client",
    "author": "",
    "version": "0.0.0",
    "private": true,
    "dependencies": {
      "@angular/animations": "^14.2.0",
      "@angular/common": "^14.2.0",
      "@angular/compiler": "^14.2.0",
      "@angular/core": "^14.2.0",
      "@angular/forms": "^14.2.0",
      "@angular/material": "^14.2.7",
      "@angular/platform-browser": "^14.2.0",
      "@angular/platform-browser-dynamic": "^14.2.0",
      "@angular/router": "^14.2.0",
      "bootstrap": "^5.2.3",
      "rxjs": "~7.5.0",
      "tslib": "^2.3.0",
      "zone.js": "~0.11.4",
      "oidc-client": "1.7.0"
    },
    "devDependencies": {
      "@angular-devkit/build-angular": "^14.2.11",
      "@angular/cli": "~14.2.11",
      "@angular/compiler-cli": "^14.2.0",
      "@types/jasmine": "~4.0.0",
      "jasmine-core": "~4.3.0",
      "karma": "~6.4.0",
      "karma-chrome-launcher": "~3.1.0",
      "karma-coverage": "~2.2.0",
      "karma-jasmine": "~5.1.0",
      "karma-jasmine-html-reporter": "~2.0.0",
      "typescript": "~4.7.2"
    }
  }

**Comment by leosvelperez** [comment]
Thanks for reporting this!

I pushed a fix for this. If you want to unblock yourself without waiting for a release with the fix, please add an empty script to your `package.json` and then run `nx init` again, e.g:

```json
{
  ...
  "scripts": {
    "noop": "echo"
  },
  ...
}
```

**Comment by leopascual** [comment]
👍  Worked Great haha. Thanks so much.
