### ISSUE TITLE
nx-post-install breaking after upgrading to 16.2.2

### ISSUE THREAD

**Issue by WarrenBuffering** [nrwl/nx#17231]
### Current Behavior

I'm unable to install pods and build a previously working react-native application after upgrading to 16.2.2. Running `npx pod-install` and/or `pod install` from the app directory fails because the Podfile can't find the `/@nx/react-native/nx_post_install` file, rightfully so because the file doesn't exist in node_modules.

I've tired refreshing everything as well with no luck, more specifically:
 
- running `react-native-clean-project` inside app dir
- deleting both node_modules folders
- deleting /ios/Pods and ios/Podfile.lock
- back in the root running `watchman watch-del-all` and `rm -rf ~/Library/Developer/Xcode/DerivedData`
- then, still in root running `yarn`
- back in mobile running `yarn`
- back in root running `yarn nx run mobile:sync-deps` and then `yarn nx run mobile:ensure-symlink`
- then trying to build the app again and skipping the nx cache for the fresh build at the end via `yarn nx run mobile:run-ios --skip-nx-cache`

The symlink and sync deps fix referenced in #11260 isn't working for me. I wouldn't really expect it to because the Podfile is still looking for a post install hook that doesn't exist.

### Expected Behavior

Pods should install

### Steps to Reproduce

Install `@nx/react-native` and no `@nx/react-native/nx_post_install` exists

### Nx Report

```shell
Node   : 16.19.1
   OS     : darwin x64
   yarn   : 1.22.19
   Hasher : Native
   
   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/cypress        : 16.2.2
   @nx/detox          : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nx/express        : 16.2.1
   @nx/nest           : 16.2.2
   @nx/node           : 16.2.2
   @nx/plugin         : 16.2.2
   @nx/react          : 16.2.2
   @nx/react-native   : 16.2.2
   @nx/storybook      : 16.2.2
   @nrwl/tao          : 15.7.2
   @nx/web            : 16.2.2
   @nx/webpack        : 16.2.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @ns3/nx-serverless : 3.8.0
   ---------------------------------------
   Local workspace plugins:
   	 @{repoName}/internal
```

### Failure Logs

```shell
[!] Invalid `Podfile` file: cannot load such file -- /Users/{me}/Dev/{repoName}/node_modules/@nx/react-native/nx_post_install.

 #  from /Users/{me}/Dev/{repoName}/apps/mobile/ios/Podfile:3
 #  -------------------------------------------
 #  require_relative '../../../node_modules/@react-native-community/cli-platform-ios/native_modules'
 >  require_relative '../../../node_modules/@nx/react-native/nx_post_install'
 #  
 #  -------------------------------------------


 >  NX   

   Running pod install failed, see above.
   Do you have CocoaPods (https://cocoapods.org/) installed?
   
   Check that your XCode path is correct:
   sudo xcode-select --print-path
   
   If the path is wrong, switch the path: (your path may be different)
   sudo xcode-select --switch /Applications/Xcode.app
   
   Pass --verbose to see the stacktrace.


 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target run-ios for project mobile (2s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by kaaterskil** [comment]
Same problem here. MacBookPro M1 running Ventura 13.4. What's the fix - this issue looks closed?

**Comment by john-redd** [comment]
@kaaterskil you might be running into this [issue](https://github.com/nrwl/nx/issues/17249).
