### ISSUE TITLE
apps/my-app/.env is not applied when running tasks of my-app on the Agent.

### ISSUE THREAD

**Issue by KamikazeZirou** [nrwl/nx#17240]
### Current Behavior

Suppose the folder structure is as follows.

```
/
└── apps
    └── my-app
        ├── .env
        └── project.json
```

Suppose my-app has a build task called ```test```.

```
    "test": {
      "executor": "nx:run-commands",
      "options": {
        "command": "echo test=${FOO}",
        "cwd": "apps/my-app"
      }
    }
```

The contents of the .env file should be as follows.

```
FOO=BAR
```

When my-app's ```test``` is run on Nx's Agent, the output of ```test``` is as follows.

```
> nx run my-app:test
test=
```

This means that when we run tasks on the Nx Agent, the apps/my-app/.env is not applied.

### Expected Behavior

apps/my-app/.env should be applied when running tasks of my-app on the Agent.

### GitHub Repo

https://github.com/KamikazeZirou/nx-go-sample-2

### Steps to Reproduce

1. define a build task whose executor is nx:run-commands
2. run the task on Nx Agent

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : linux x64
   npm    : 9.5.1
   Hasher : Native
   
   nx             : 16.2.2
   @nx/workspace  : 16.2.2
   @nx/devkit     : 16.2.2
   @nrwl/tao      : 16.2.2
   nx-cloud       : 16.0.5
   ---------------------------------------
   Community plugins:
   @nx-go/nx-go : 2.7.0
```

### Failure Logs

```shell
> nx run my-app:test
test=
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

When I ran the build task directly without the Agent, this problem did not occur.
When the Nx version was 15.6.3 and the nx-cloud version was 15.0.3, this problem did not occur.

**Comment by xiongemi** [comment]
@KamikazeZirou I tried to do this setup locally, but I could not replicate this issue with the latest nx 17.
could you try to upgrade nx to 17 and see whether you still have this issue?
