### ISSUE TITLE
docs: the Edit this page URLs are broken

### ISSUE THREAD

**Issue by LayZeeDK** [nrwl/nx#17253]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?
Any nx.dev documentation page.

Example: https://nx.dev/packages/nx/documents/run-many

#### Expected behavior
1. I click the *Edit this page* button on any documentation page, for example https://nx.dev/packages/nx/documents/run-many
2. I'm redirected to the Markdown source document, for example https://github.com/nrwl/nx/blob/master/docs/generated/packages/nx/documents/run-many.md

#### Actual behavior
1. I click the *Edit this page* button on any documentation page, for example https://nx.dev/packages/nx/documents/run-many
2. I'm redirected to an incorrect URL, for example https://github.com/nrwl/nx/blob/master/public/documentation/generated/packages/nx/documents/run-many.md

#### Solution
In the *Edit this page* URL, `public/documentation` needs to be replaced with `docs`.

For example
```
https://github.com/nrwl/nx/blob/master/public/documentation/generated/packages/nx/documents/run-many.md
                                       ^^^^^^^^^^^^^^^^^^^^
```
becomes
```
https://github.com/nrwl/nx/blob/master/docs/generated/packages/nx/documents/run-many.md
                                       ^^^^
```

**Comment by LayZeeDK** [comment]
The proposed solution is wrong. We shouldn't edit documents in the `generated` folder directly.

What is the correct way to fix *Edit this page* URLs?

**Comment by LayZeeDK** [comment]
Bad bot!

This is still an unresolved issue.

**Comment by ndcunningham** [comment]
This should be working now thanks!
