### ISSUE TITLE
NX does not restart the project in "serve" mode

### ISSUE THREAD

**Issue by amir-khoshbakht** [nrwl/nx#17265]
### Current Behavior

there is integrated monorepo with only one nestjs app in it.
if I make a file that is syntactically incorrect. for exmple :

```ts
exportttt class ServeTest {

}
```
 in that it will detect the change and will restart the app and will show this error:
![image](https://github.com/nrwl/nx/assets/68753961/ed8fa74b-b72f-41a0-82ed-a8dd6e9d5dc0)
but in the next change even if I correct the problem it will say:
![image](https://github.com/nrwl/nx/assets/68753961/e33d805b-dd5c-4f0c-b184-9cdacb3d45f3)

### Expected Behavior

The server must be restarted in any case with the new changes

### Steps to Reproduce

1. npx create-nx-workspace@latest serve-test --pm=yarn
2. Create a file in path: " serve-test/apps/serve-test" with content similar to this:
```ts
exportttt class ServeTest {

}
```
3. run the app: yarn nx run serve-test:serve

Note: This problem does not exist on the same system in a project with Nx version 15.9.2

### Nx Report

```shell
Node   : 18.16.0
   OS     : win32 x64
   yarn   : 1.22.19
   Hasher : Native

   nx (global)        : 16.2.2
   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nx/nest           : 16.2.2
   @nx/node           : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/webpack        : 16.2.2
   typescript         : 5.0.4
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by JonWallsten** [comment]
I have the same issue. Whenever there's an error in some remote or library it terminatates the build:
![image](https://github.com/nrwl/nx/assets/5993909/29b49165-e627-4e88-a908-167de457fa1f)

It's obviously really annorying. Let me know if you need any debug information.
