### ISSUE TITLE
[NX 15 - 16][Ubuntu]:  Nest does not appear in chrome inspect

### ISSUE THREAD

**Issue by redplane** [nrwl/nx#17269]
### Current Behavior

I have create a brand new **nx workspace** with **nest** app on **Ubuntu** OS.
However, when I use `nx serve my-nest-app`, and open `chrome://inspect`, it does not show up in the inspect tab:

![1](https://github.com/nrwl/nx/assets/7974095/28f88235-9f81-43b0-a6ae-905e1239cf7e)

![2](https://github.com/nrwl/nx/assets/7974095/a4c79aa6-791f-4c70-b45d-7db5f1c8537e)

**P/S**: Using nx 16 to create a new project, I face the same situation

### Expected Behavior

When I use `npx nx serve my-nest-app`, I can debug with `chrome://inspect`

### GitHub Repo

https://github.com/redplane/nx-15-debug/tree/main

### Steps to Reproduce

By following the official tutorial at: https://nx.dev/recipes/getting-started/set-up-a-new-workspace

1. I used `npx create-nx-workspace@15` to create a blank workspace.
2. I used these commands to add a nest app into the created workspace:

```
npm install -D @nx/nest
nx g @nx/nest:app my-nest-app
```

The commands ran successfully and I could nx serve my-nest-app the project:
![3](https://github.com/nrwl/nx/assets/7974095/a2287e80-097b-4592-8e5d-3644c6691376)
![4](https://github.com/nrwl/nx/assets/7974095/c0f0af09-682c-4dc6-aa4d-c15b4f38677a)

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : linux x64
   npm  : 9.6.7
   
   nx                      : 15.9.4
   @nrwl/js                : 16.2.2
   @nrwl/jest              : 16.2.2
   @nrwl/linter            : 16.2.2
   @nrwl/workspace         : 15.9.4
   @nrwl/cli               : 15.9.4
   @nrwl/devkit            : 15.9.4
   @nrwl/eslint-plugin-nx  : 16.2.2
   @nrwl/nest              : 16.2.2
   @nrwl/node              : 16.2.2
   @nrwl/tao               : 15.9.4
   @nrwl/webpack           : 16.2.2
   typescript              : 5.0.4
   ---------------------------------------
   Community plugins:
   @nx/eslint-plugin : 16.2.2
   @nx/jest          : 16.2.2
   @nx/js            : 16.2.2
   @nx/linter        : 16.2.2
   @nx/nest          : 16.2.2
   @nx/node          : 16.2.2
   @nx/webpack       : 16.2.2
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/js@16.2.2
     - @nrwl/jest@16.2.2
     - @nrwl/linter@16.2.2
     - @nrwl/eslint-plugin-nx@16.2.2
     - @nrwl/nest@16.2.2
     - @nrwl/node@16.2.2
     - @nrwl/webpack@16.2.2
   
   To fix this, run `nx migrate nx@16.2.2`
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

OS: Ubuntu

**Comment by redplane** [comment]
Any updates ?

**Comment by cwoebker** [comment]
Possibly related to https://github.com/nrwl/nx/issues/17327
