### ISSUE TITLE
Marking workspace root as project breaks `analyzeSourceFiles` feature

### ISSUE THREAD

**Issue by GreenTea124** [nrwl/nx#17276]
### Current Behavior

Once you mark a root directory as a project by adding `"nx": {}` to `package.json` (as explained in the official guide here https://www.youtube.com/watch?v=PRURABLaS8s&t=110s ) dependencies between projects based on `import` statements are no longer detected.

### Expected Behavior

Dependency detection should continue to work.

### Steps to Reproduce

1. Create NX project that enables`analyzeSourceFiles` feature in `nx.json`.
2. Add 2 examples of JS/TS projects, import first one into the second one
3. Run `nx reset && nx graph` dependency should be correctly detected
4. Add `"nx": {}` to root level package json
5. Run `nx reset && nx graph` again (calling `nx reset` is crucial here), the third project will appear in the project graph but the detected dependency will be gone.

### Nx Report

```shell
Node   : 16.14.0
   OS     : win32 x64
   npm    : 8.3.1
   Hasher : Native

   nx          : 16.2.1
   @nx/devkit  : 16.2.1
   @nrwl/tao   : 16.2.1
   typescript  : 5.0.4
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by GreenTea124** [comment]
As of version 16.4.0 it's even more broken.
Now using this plugin "https://nx.dev/recipes/other/include-all-packagejson" also leads to broken "analyzeSourceFiles" feature.

Also, any updates?

**Comment by xiongemi** [comment]
@GreenTea124  do you mean you can see the root project specified in package.json now shows up in the dep graph? i think that is kinda expected.

**Comment by GreenTea124** [comment]
> i think that is kinda expected.

Yes, expected and what I wanted. That part works fine, all project including root ones are still in the project graph. What broke after adding `nx` field into root `project.json` were connection between these projects, as if `enablesanalyzeSourceFiles` was disabled.

**Comment by xiongemi** [comment]
@GreenTea124 do you have a repo to replicate this issue.
i still could not replicate this issue. i tried with the latest nx.

this is what i tried:
i created a root project, then added lib1 and lib2. i mport lib2 into lib1, using relative path: `import { Lib2 } from '../../lib2';`.


when i use the default root project.json (without any change) and added empty `"nx": {}` in package.json, i got:
<img width="1261" alt="Screenshot 2023-10-31 at 4 02 38 PM" src="https://github.com/nrwl/nx/assets/16211801/508912b3-a366-4e69-b973-97e8a558a1a6">

when i use add explicitly disable analyzeSourceFiles in  package.json, i got:
```
"nx": {
    "pluginsConfig": {
      "@nx/js": {
        "analyzeSourceFiles": false
      }
    }
  }
```

![graph (4)](https://github.com/nrwl/nx/assets/16211801/548c2138-50bb-4ac6-9c16-2227727f7822)

**Comment by GreenTea124** [comment]
@xiongemi 
Sure, here is a minimal repo that mirrors my setup:
https://github.com/GreenTea124/nx-dep-detection-bug-demo

While creating this repo, I've noticed that a `baseUrl` in `tsconfig.base.json` seems to be the culprit. When I set it to `.` things seem to work fine.

**Comment by matheo** [comment]
I just created an Angular monorepo with `nx 18.1.1` and it detects the root as a "lib project" without "nx" in the `package.json` nor `project.json` in the root. I'm wondering why :man_shrugging:
