### ISSUE TITLE
Tailwind generator to include Tailwind Prettier Plugin

### ISSUE THREAD

**Issue by mj-meyer** [nrwl/nx#17271]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Include `prettier-plugin-tailwindcss` as part of the tailwind generator installation. 

## Motivation
I believe this is a good default that helps keep your tailwind classes in an order that makes sense, without needing to use a personal style, or worse, no style at all. 

## Suggested Implementation
I had some trouble getting this to work initially. I found that converting `.prettierrc` to `prettierrc.js` and adding the following works quite well:
```js
module.exports = {
  // other prettier settings here
  plugins: ['prettier-plugin-tailwindcss'],
}
```

## Alternate Implementations
1. Add these steps to the documentation so it's easy for someone to manually add
2. Add a flag that'll add this step automatically (eg: `nx g @nx/react:setup-tailwind --prettier-sorting`
3. Both 1 and 2

**Comment by Arindam200** [comment]
Can I work on this?
