### ISSUE TITLE
nx 16 - Ngrx state is undefined with fresh install

### ISSUE THREAD

**Issue by bizappzone** [nrwl/nx#17288]
### Current Behavior

New angular app with NGRX added.   When application loads the state is undefined (viewed in redux tools)

### Expected Behavior

 Ngrx initial state should load and be registered.

### GitHub Repo

https://github.com/bizappzone/min-repo-latest-nx

### Steps to Reproduce

1. Create new workspace (angular application) 
2. After install generate ngrx for root
3. serve application
4. view in redux tools - state is undefined
5. Note the initial state has a loading: false and should be shown

### Nx Report

```shell
Node   : 19.6.0
   OS     : darwin x64
   npm    : 9.4.0
   Hasher : Native
   
   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/angular        : 16.2.2
   @nx/cypress        : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/web            : 16.2.2
   @nx/webpack        : 16.2.2
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 16.0.0
   @ngrx/effects         : 16.0.0
   @ngrx/entity          : 16.0.0
   @ngrx/router-store    : 16.0.0
   @ngrx/schematics      : 16.0.0
   @ngrx/store           : 16.0.0
   @ngrx/store-devtools  : 16.0.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

also tried a package setup workspace ... then added angular app (as above), with same results

**Comment by leosvelperez** [comment]
Thanks for reporting this!

The application state is correctly registered, but the NgRx `StoreDevtoolsModule` is not set up. You must [set it up](https://ngrx.io/guide/store-devtools) so you can see your Store info in the Redux devtools.

The NgRx doesn't set it up since Angular 15. I will add it behind a flag so users can opt in to generate the setup.

**Comment by bizappzone** [comment]
perfect... worked like a charm!  pushed the updates incase someone has issue.  Also great to have a flag option
