### ISSUE TITLE
add TypeScript option on npx @nx/angular:setup-tailwind 

### ISSUE THREAD

**Issue by morbargig** [nrwl/nx#17301]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

`npx @nx/angular:setup-tailwind --ts`

allow writing tailwind as typescript file "tailwind.config.ts"

## Motivation

this will allow me to create tailwind with some typescript feature like disallow some chars in some tailwind configuration such as colors

## Suggested Implementation

https://tailwindcss.com/docs/guides/remix

**Comment by Coly010** [comment]
Hi @morbargig !

Thanks for raising an Issue around this.

Unfortunately, we will not be implementing a method of generating a typescript Tailwind Config.

That said, you can still do this yourself manually, by changing the tailwind.config to a typescript file and/or writing a local workspace generator that wraps our `setup-tailwind` generator and converts the config file that is created to typescript.

You can read more about creating workspace generators here: https://nx.dev/plugins/tutorials/create-plugin#create-a-local-plugin
