### ISSUE TITLE
@nrwl/angular: Schematic "add" not found in collection "@nrwl/angular".

### ISSUE THREAD

**Issue by ahnpnl** [nrwl/nx#1730]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Should be able to add `@angular/pwa` to an Angular app in the workspace which is using **Nx CLI**. Expecting that `nx g add @angular/pwa --project <app_name>` runs similarly to `ng add @angular/pwa --project <app_name>`

## Current Behavior

Adding `@angular/pwa` to an app in Nx workspace which is using **Nx CLI** is not possible with command `nx g add @angular/pwa --project <app-name>`.

## Failure Information (for bugs)

I got an error in the console: 
```
Schematic "add" not found in collection "@nrwl/angular".
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Clone sample repo https://github.com/ahnpnl/nx-add-issue
2. Run `nx g add @angular/pwa --project my-app`.
3. Observe an error in the console.

### Context

Please provide any relevant information about your setup:

- version of Nx used: 8.4.10
- 3rd-party libraries and their versions: **N.A.**
- and most importantly - a use-case that fails

Example repo: https://github.com/ahnpnl/nx-add-issue

### Failure Logs

![image](https://user-images.githubusercontent.com/27772165/63174691-c6f79680-c042-11e9-9c59-9b2684039a97.png)

## Other

**N.A.**

**Comment by brandonroberts** [comment]
Nx does not currently support an `add` command, but the command to run when using the Angular CLI is `ng add @angular/pwa --project my-app`. If you want to run it manually, try:

```ts
yarn add @angular/pwa --dev
nx g @angular/pwa:ng-add --project my-app`
```

**Comment by ahnpnl** [comment]
Hi, maybe this should be documented somewhere in the meanwhile waiting for Nx to support add ? I think that will be helpful for others to refer to.

**Comment by brandonroberts** [comment]
@ahnpnl are you using Angular primarily? If you are, you should power your workspace using the Angular CLI and use the `ng` commands. The `Nx CLI` is primarily for react and web component projects at the moment.

**Comment by ahnpnl** [comment]
Hi, the reason I went for Nx CLI because the workspace might extend to contain React/Vue or web components later. Therefore my team wants to try out Nx CLI as a generic workspace to be easily extended for future

**Comment by mehrad-rafigh** [comment]
@ahnpnl Can you please close this issue, as it seemed resolved from your side

**Comment by ahnpnl** [comment]
I wonder if there should be a fix for this instead of workaround ?

**Comment by mehrad-rafigh** [comment]
Just as Brandon mentioned, NX is not feature par with ng and this will take time. I do not even know, if that is the plan of the nx team. 
If you want to use any angular related things, please use ng!

**Comment by tcoz** [comment]
I think the reason for this is that unless you explicitly install the angular Nx package, the default schematics collection for the workspace won’t be set, so you’ll have to fully qualify your angular commands. If you do install it, that’ll set the default schematics to angular and no commands will run normally. This may, however, compromise the agnostic nature of the workspace.

**Comment by vsavkin** [comment]
Folks. I'm going to close this issue. We aren't going to add `add` to the Nx cli in the near future. So the solution provided by Brandon is what we recommend.
