### ISSUE TITLE
Cannot use cypressComponentConfigGenerator within another generator on a newly created project

### ISSUE THREAD

**Issue by kaceycleveland** [nrwl/nx#17316]
### Current Behavior

When I run a custom generator that runs `libraryGenerator` from `@nx/react`, I can read from the created library by name via `readProjectConfiguration`. However, I have noticed it does not update the project graph. If I use either `readCachedProjectGraph` or `createProjectGraphAsync` and read the given nodes in the graph, it does not show my created library.

If I were to check the project graph AFTER the generator is run, it does exist.

This becomes an issue if a chained generator depends on the existence of the library created. My specific case is when I wanted to combine `libraryGenerator` from `@nx/react` and then follow it up with `cypressComponentConfigGenerator` from `@nx/react` which fails to get the build target because it cannot find it in the project graph.

### Expected Behavior

I expect the project graph to reflect newly created libs before the generator is finished executing.

### Steps to Reproduce

1. Create a custom generator and use `libraryGenerator` from `@nx/react`
2. Try to run `cypressComponentConfigGenerator` from `@nx/react` afterwards in the same custom generator.
3. Step 2 should fail.

### Nx Report

```shell
Node   : 16.14.2
   OS     : darwin arm64
   yarn   : 3.2.1
   Hasher : Native
   
   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/cypress        : 16.2.2
   @nx/detox          : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nx/next           : 16.2.2
   @nx/node           : 16.2.2
   @nx/plugin         : 16.2.2
   @nx/react          : 16.2.2
   @nx/react-native   : 16.2.2
   @nx/rollup         : 16.2.2
   @nx/storybook      : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/vite           : 16.2.2
   @nx/web            : 16.2.2
   @nx/webpack        : 16.2.2
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @trumbitta/nx-plugin-unused-deps : 1.12.1
   ---------------------------------------
   Local workspace plugins:
         @arrived/nx
```

### Failure Logs

```shell
TypeError: Cannot read properties of undefined (reading 'targets')
    at readTargetOptions (/Users/kaceycleveland/Projects/my-proj/packages/devkit/src/executors/read-target-options.ts:19:52)
    at findInTarget (/Users/kaceycleveland/Projects/my-proj/packages/cypress/src/utils/find-target-options.ts:103:27)
    at /Users/kaceycleveland/Projects/my-proj/packages/cypress/src/utils/find-target-options.ts:45:17
    at Generator.next (<anonymous>)
    at fulfilled (/Users/kaceycleveland/Projects/my-proj/node_modules/tslib/tslib.js:164:62)

 >  NX   Error trying to find build configuration. Try manually specifying the build target with the --build-target flag.

   Provided project? my-lib
   Provided build target? my-lib:build
   Provided Executors? @nx/webpack:webpack, @nx/vite:build, @nrwl/webpack:webpack, @nrwl/vite:build
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
The project graph reflects what is resolvable by Nx at that time, and it is not aware of the virtual FS that we use in the tree. Its working as expected in regards to not being updated yet, but it does hurt the composability of the generator as you pointed out.

I think this is something that can be addressed on the generator side.

**Comment by kaceycleveland** [comment]
> The project graph reflects what is resolvable by Nx at that time, and it is not aware of the virtual FS that we use in the tree. Its working as expected in regards to not being updated yet, but it does hurt the composability of the generator as you pointed out.
> 
> I think this is something that can be addressed on the generator side.

That makes sense; when I was looking through some other generators, I saw one that included a `isNewProject` flag which can probably be used to circumvent some of these issues. Thanks for the quick reply.

**Comment by kaceycleveland** [comment]
An example being the `viteConfigurationGenerator`, I am not sure if it is utilizing the flag for this exact purpose though:

```
    const viteTask = await viteConfigurationGenerator(host, {
      uiFramework: 'react',
      project: options.name,
      newProject: true,
      includeLib: true,
      inSourceTests: options.inSourceTests,
      includeVitest: options.unitTestRunner === 'vitest',
      skipFormat: true,
    });
    ```

**Comment by barbados-clemens** [comment]
Issue should be resolved in the linked PR. 
You'll want to manually provide the `buildTarget` and `bundler` option to bypass trying to read the graph and validate the target. The `bundler` option is only for react so if you use the angular one it's only `buildTarget` to bypass the valiation. 

That being said make sure the buildTarget is an project with that the preset is designed for which is an @nx/webpack:webpack or @nx/vite:vite executor otherwise you could run into various runtime issues with the nx preset trying to read options of the build target (vite less so, but for sure with webpack).
