### ISSUE TITLE
create-nx-workspace does not generate Dockerfile (node-standalone/nest)

### ISSUE THREAD

**Issue by Ionaru** [nrwl/nx#17343]
### Current Behavior

No Dockerfile is generated when running the `create-nx-workspace` command using NestJS as the framework and the `--docker` option enabled.

### Expected Behavior

A Dockerfile should be created, allowing the application to run in docker, OR the `--docker` option should not be allowed in this configuration and the CLI should not ask whether to generate a Dockerfile when running without the `--docker` option defined.

<img width="481" alt="image" src="https://github.com/nrwl/nx/assets/3472373/8a8e4057-ac0d-4cbb-bc03-813639a45f30">

### GitHub Repo

N/A

### Steps to Reproduce

1. Run `npx create-nx-workspace@latest new-workspace --nxCloud false --preset node-standalone --framework nest --docker true`
2. Inspect the generated files, no Dockerfile is present.

### Nx Report

```shell
N/A
```

### Failure Logs

```shell
N/A
```

### Operating System

- [x] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by kobyzskyi** [comment]
The same story for macOS.

**Comment by pde201** [comment]
Is there an ETA for this bug?

**Comment by alexmacavei** [comment]
Yep, same issue here.

**Comment by pkimtani** [comment]
Same issue here. Running on MacOS (ARM CPU).

**Comment by sir-captainmorgan21** [comment]
Ya same here
