### ISSUE TITLE
 >  NX   desiredImplicitDeps.filter is not a function

### ISSUE THREAD

**Issue by SPokhriyal123** [nrwl/nx#17355]
### Current Behavior

The application is not getting build while running the command ca-app:serve:alpha-next:
It shows an error : >  NX   desiredImplicitDeps.filter is not a function

### Expected Behavior

The application use to build and compile successfully after running ng run ca-app:serve:alpha-next

### Steps to Reproduce

1. While doing migration from angular 14 to 15, ran the following commands:

1. npm install -g nx@latest
2. npm install -g @angular/cli@15.2.0
3. npm install -g @angular/core@15.2.0
4. npm update nx --force
5. ng update @angular/core@15.2.0 @angular/cli@15.2.0 --force
6. nx migrate latest
7. npm install --force
8. nx migrate --run-migrations
9. ca-app:serve:alpha-next

After running the  command ca-app:serve:alpha-next I am getting an error : >  NX   desiredImplicitDeps.filter is not a function
 
 Note: I do not have any array named desiredImplicitDeps in my application.

### Nx Report

```shell
>  NX   desiredImplicitDeps.filter is not a function
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by SPokhriyal123** [comment]
![image](https://github.com/nrwl/nx/assets/72793185/3fbd9176-8834-4c85-a262-9e1b40cf0f11)

**Comment by iamamanbhardwaj** [comment]
@AgentEnder this issue of different from https://github.com/nrwl/nx/issues/17349 . but after solving one, other fails. 

can you help us with this . i am not able to run any command for nx after this new package is used to decorate cli

**Comment by jerkovicl** [comment]
@AgentEnder yeah same for me, after change path of package to decorate cli i am also not able to run any nx commands

![image](https://github.com/nrwl/nx/assets/5444153/b8aeb9d9-ae32-4e33-9e54-7b8a7a8fb61f)

```
 npx nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : win32 x64
   npm    : 9.5.1
   Hasher : Native

   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/angular        : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/plugin         : 16.3.2
   @nx/storybook      : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/web            : 16.3.2
   @nx/webpack        : 16.3.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc : 1.1.21
   @storybook/angular : 7.1.0-alpha.32
   ngx-build-plus     : 16.0.0
```

**Comment by iamamanbhardwaj** [comment]
is this issue getting any attention? @vsavkin @FrozenPandaz  please tag someone who could help us with such errors!

**Comment by FrozenPandaz** [comment]
Just to confirm, do you all happen to have `implicitDependencies: "*"` anywhere? :eyes:

I suspect this could be the reason you are seeing this error.
