### ISSUE TITLE
NX workspace CLI - missing upgrade command

### ISSUE THREAD

**Issue by appsolutegeek** [nrwl/nx#1735]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Using the angular cli you have access to the upgrade script via the package.json, it is recommended to run this because as things are deprecated then the CLI takes care of renaming things - so its not just upgrading packages etc..

In the NX cli this command seems to be missing - this can't be right ??

So what is the way to upgrade, go through it manually and update anything in the workspace.json by hand ?

## Current Behavior

Currently no way to upgrade the nx schematics i.e. the folllwing is missing in the NX cli implementation

```
    "update": "ng update @nrwl/schematics",
    "update:check": "ng update",
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Create a new project (empty) and choose NX cli and then add a NEST api for example...

### Context

Please provide any relevant information about your setup:

- version of Nx used : latest - used NPX

**Comment by appsolutegeek** [comment]
I am currently using NCU to update my packages but I was told before that this isn't the correct way as when things become deprecated or renamed the "upgrade" command takes care of these changes automatically

```
[====================] 24/24 100%

 @nestjs/common                           ^6.2.4  →   ^6.5.3 
 @nestjs/core                             ^6.2.4  →   ^6.5.3 
 @nestjs/platform-express                 ^6.2.4  →   ^6.5.3 
 reflect-metadata                        ^0.1.12  →  ^0.1.13 
 @types/node                              ~8.9.4  →  ~12.7.2 
 dotenv                                    6.2.0  →    8.1.0 
 prettier                                 1.16.4  →   1.18.2 
 ts-node                                  ~7.0.0  →   ~8.3.0 
 tslint                                  ~5.11.0  →  ~5.18.0 
 typescript                               ~3.4.5  →   ~3.5.3 
 jest                                     24.1.0  →   24.9.0 
 @types/jest                              24.0.9  →  24.0.17 
 ts-jest                                  24.0.0  →   24.0.2 
 @nestjs/schematics                       ^6.3.0  →   ^6.4.3 
 @nestjs/testing                          ^6.2.4  →   ^6.5.3 
 @typescript-eslint/parser         2.0.0-alpha.4  →    2.0.0 
 @typescript-eslint/eslint-plugin  2.0.0-alpha.4  →    2.0.0 

```

**Comment by mehrad-rafigh** [comment]
It should work with the NX CLI. Using NCU might break your app, because it updates all dependencies.
I created a test-workspace with `npx create-nx-workspace@8.4.9 myworkspace-needs-update` and used the `react` preset. 
Running `ng update` will shou a list of dependencies, which can be updated. 

But running `ng update @nrwl/workspace` I got the following error:
```
ng update @nrwl/workspace
Using package manager: 'yarn'
Collecting installed dependencies...
Found 35 dependencies.
Fetching dependency metadata from registry...
                  Package "@nrwl/eslint-plugin-nx" has an incompatible peer dependency to "@nrwl/workspace" (requires "8.4.9", would install "8.4.12").
Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
```

Running `ng update @nrwl/workspace --force` updated the nrwl dependencies to their latest version. 
Unfortunately, it did not update the react dependencies. @jaysoo Do you know why the react dependencies have not been updated to their latest version?
Running ng update with an angular workspace updates angular to it's latest version.

**Comment by appsolutegeek** [comment]
Thanks @mehrad-rafigh , I missed that :-) I think the NX cli had replaced the ng cli when using with NON angular apps.

I think it would be better for consistency at least if they scripts were still there.

What would be even better would be for NX to implement the upgrade rather having a dependency on NG.

I am thinking now of returning to NG - would this be a better policy ?

There seems to be a difference between the two, apart from the obvious ANgualr vs OTHER framework.

It would be nice for some input about what i should do here.

I always used to use NG but recently if my project wasn't angular related then i opted for NX.

**Comment by mehrad-rafigh** [comment]
@appsolutegeek NX does not replace ng, but rather builds on top of the Angular CLI. This is the reason, why you can create react and web apps and components :)

When you are running a non Angular workspace you should use the nx CLI. 
The only time you have to run ng, is when you want to update. 

Maybe `nx update` can be added in the future.
What do you think @vsavkin @FrozenPandaz @jaysoo?

**Comment by appsolutegeek** [comment]
Hi @mehrad-rafigh , Yes i understand that nx is built ontop of ng but what i really mean is that what seems to be recommended is that we use NX when using NON angular apps. In fact the ng cli isn't even a dependency.

I wouldn't have a problem using 1 or the other, I just think for consistency sake it would be better for the upgrade to be able to done via NX and left in the scripts of the package.json.

Looking forward to other comments from others, hopefully we can have this for the future.

**Comment by jaysoo** [comment]
I think we still need to discuss how update can be handled by the Nx CLI. For now @mehrad-rafigh is correct that update will only work through Angular CLI.

> I thought the NX cli had replaced the ng cli when using with NON angular apps.

This was the intention, at least when it comes to builders and schematics. However, Nx CLI isn't at feature parity with Angular CLI, so some things are missing (such as update).

**Comment by appsolutegeek** [comment]
ok - thanks for the confirmation.

**Comment by vsavkin** [comment]
Folks. The migrate command is in 8.5.2.

It might take a few releases before we iron out all the details, but the core of the functionality is in place.
