### ISSUE TITLE
nextjs pages are generated in the wrong directory

### ISSUE THREAD

**Issue by AliRadmanesh** [nrwl/nx#17352]
## Current Behavior

When I want to generate a new page in my Next.js app using `@nx/next` command of nx-console extension in VSCode, it generates files in `pages` directory instead of `apps/pages` (I'm talking about new Next app routing in v13)

## Expected Behavior

Pages must be created in the `app` directory.

### Environment

- Nx Console version: 18.1.2
- VSCode version: 1.78.2

**Comment by mandarini** [comment]
I'll take a look sometime today maybe! :)

**Comment by mandarini** [comment]
@AliRadmanesh hello! Thanks for the bug report. Is this a new behaviour, or did this happen in older versions of Nx too?

**Comment by AliRadmanesh** [comment]
@mandarini Hi!
This bug is relatively new and caused after Next.js changed the routing system from the `pages` directory to the `app` (Next.js v13.4 was released about one month ago)

**Comment by ndcunningham** [comment]
@AliRadmanesh just to clarify 
1. You are using the new Next.js router `app/`.
2. You are creating a page called `about` using Nx next.js page generator.
3. Your workspace that contains the next.js project  is *not* standalone

If these are true, running the command `npx nx generate @nx/next:page about --project=site`

This should generate the following at minimum:
```
└── app
    └── about
        └── page.tsx
```

This needs to be updated on our end.
When we updated our next.js package to support the new router we missed updating this generator. Sorry about that.
