### ISSUE TITLE
`nx build` with buildable dependencies fails to run when in the project directory

### ISSUE THREAD

**Issue by JoA-MoS** [nrwl/nx#17362]
### Current Behavior

Running `npx nx build` or `npx nx build app-a` from inside app-a directory fails to build the buildable library `lib-a`. Running `npx nx build app-a` from the root of the repo works correctly.

### Expected Behavior

running the `nx build` command from inside the app directory should work the same as when you run the command with the project defined from the repo root, using the project directory as the context for the current project.

### GitHub Repo

https://github.com/JoA-MoS/repro-dep-build

### Steps to Reproduce

1. Clone the Repo
2. Run `npm ci`
3. Run `npx nx build app-a` (this should work)
4. change directories `cd apps/app-a`
5. Run `npx nx build`  (this will fail)

You can repeat this process with app-b

### Nx Report

```shell
❯ npx nx report
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.13.0
   OS     : darwin x64
   npm    : 8.19.3
   Hasher : Native
   
   nx                 : 16.3.0
   @nx/js             : 16.3.0
   @nx/jest           : 16.3.0
   @nx/linter         : 16.3.0
   @nx/workspace      : 16.3.0
   @nx/devkit         : 16.3.0
   @nx/esbuild        : 16.3.0
   @nx/eslint-plugin  : 16.3.0
   @nx/node           : 16.3.0
   @nrwl/tao          : 16.3.0
   typescript         : 5.0.4
   ---------------------------------------
   Local workspace plugins:
         @repro-dep-build/lib-a
```

### Failure Logs

```shell
❯ cd apps/app-b
❯ nx build

> nx run lib-a:build

Compiling TypeScript files for project "lib-a"...
error TS6059: File '/Users/_______/code/github/repro-dep-build/libs/lib-a/src/index.ts' is not under 'rootDir' 'libs/lib-a'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Root file specified for compilation
../../libs/lib-a/src/index.ts:1:15 - error TS6059: File '/Users/_______/code/github/repro-dep-build/libs/lib-a/src/lib/lib-a.ts' is not under 'rootDir' 'libs/lib-a'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Imported via './lib/lib-a' from file '/Users/_______/code/github/repro-dep-build/libs/lib-a/src/index.ts'
    Root file specified for compilation

1 export * from './lib/lib-a';
                ~~~~~~~~~~~~~
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Frikki** [comment]
This is also an issue in Nx v16.3.2 with a Next.js app with lib dependencies, even when the build is executed from the workspace root.

**Comment by jorgeramirezamora** [comment]
I am also experiencing this going from 16.5.5 to 16.6.0.

This error only happens when the buildable library is using @nx/rollup:rollup. It does not happen when is @nx/vite:build

**Comment by Frikki** [comment]
I may have found the culprit. Check that the file(s) in question isn’t added to the _tsconfig.json_ `include` array in the application that fails to build.

**Comment by JoA-MoS** [comment]
@Frikki can you clarify, are you saying the file(s) should be included in the tsconfig or that they shouldn't be included?

**Comment by Frikki** [comment]
@JoA-MoS It **shouldn’t** be included. If it’s in the `include` array, the application build will fail with error TS6059.

**Comment by Miladxsar23** [comment]
You need to specify the scope of each project through the ``'tags'`` field in the ``project.json`` file. This ensures that the typing script does not complain during import, and your problem is resolved. Please pay attention to the following code.

for lib-a project edit the project.json file like this: 

```
{
  // ... more project configuration here
  "tags": ["scope:lib-a"]
}
```

You can find much more information in the [Nx documentation](https://nx.dev/core-features/enforce-module-boundaries#tags)
