### ISSUE TITLE
Dynamic host (MF) is generating and using a webpack.config.prod.js

### ISSUE THREAD

**Issue by Foxandxss** [nrwl/nx#17378]
### Current Behavior

When generating a host like:

`nx g @nx/angular:host host --dynamic`

It is generating a `webpack.prod.config.js` and using it for production.

### Expected Behavior

Should not generate a `webpack.prod.config.js` since it is dynamic and remotes shouldn't be hardcoded. Also production build should use the other webpack config.

### Steps to Reproduce

1. Create empty integrated repo
2. npm i -D @nx/angular
3. nx g @nx/angular:host host --dynamic
4. Check that the file exists and it is referenced at project.json

### Nx Report

```shell
There is no report
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by 4javier** [comment]
I second this one, and add that even if alternate `webpack.config.*.js` files can be used for more than just defining different remotes for different stages, at the moment it can be confusing, considering that generated `.prod.js` one differs from default only for the comment suggesting to override remotes address.
