### ISSUE TITLE
Support for esm in local executors

### ISSUE THREAD

**Issue by Schmale97** [nrwl/nx#17390]
## Description

Firstly, thank you for all the work that has gone into this package

When I create a local executor through the commands:
```
npx nx g @nx/plugin:plugin my-plugin
npx nx g @nx/plugin:executor my-executor --project=my-plugin
``` 
I am unable use this plugin transpiled to esm

I am able to configure the build command of 'my-plugin' to generate esm files (via the tsconfig.json/package.json) however when the plugin is referenced to be used as an executor for another library, it seems to always use commonjs. 

This becomes and issue when trying to import external esm only modules for use in the local executor (in my case I am using inquirer). There is a work around of downgrading the version to when it support commonjs, but if it would be possible to allow esm, that would be great

## Motivation

Be able to use external esm-only packages in local executors written in typescript

## Suggested Implementation

I can see in [this file](https://github.com/nrwl/nx/blob/6d86742f9d9ccc4f34fa03ffcd30de27ecee8d31/packages/nx/src/utils/nx-plugin.ts#LL275C5-L275C23) that the module is being hard coded to commonJs.

I am not sure of the implications of allowing this to be overwritten, but could it be done by moving the module being set before the object spread, i.e. 
```
    registerTranspiler({
      experimentalDecorators: true,
      emitDecoratorMetadata: true,
      module: ts.ModuleKind.CommonJS,
      ...tsConfig.options,
      lib: ['es2021'],
      target: ts.ScriptTarget.ES2021,
      inlineSourceMap: true,
      skipLibCheck: true,
    });
```

**Comment by AgentEnder** [comment]
Nx doesn't support esm plugins currently, due to the way we synchronously load the executor code.

See https://github.com/nrwl/nx/issues/15682
