### ISSUE TITLE
npx create-nx-workspace --preset=angular isn't working

### ISSUE THREAD

**Issue by robertIsaac** [nrwl/nx#17398]
### Current Behavior

empty nx workspace is created

### Expected Behavior

nx workspace to include angular application

### Steps to Reproduce

1. run `npx create-nx-workspace --preset=angular` then choose whatever, here are my choices
```
 npx create-nx-workspace --preset=angular

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

√ Where would you like to create your workspace? · org
√ Application name · app
√ Default stylesheet format · css
√ Would you like to use Standalone Components in your application? · Yes
√ Would you like to add routing? · No
√ Enable distributed caching to make your CI faster · No
```

### Nx Report

```shell
Node   : 18.16.0
   OS     : win32 x64
   npm    : 9.6.7
   Hasher : Native

   nx             : 16.3.2
   @nx/workspace  : 16.3.2
   @nx/devkit     : 16.3.2
   @nrwl/tao      : 16.3.2
```

### Failure Logs

```shell
N/A
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

running `npx create-nx-workspace` without `--preset=angular` does work as a work around, so it's not urgent

**Comment by FrozenPandaz** [comment]
This seems to have been fixed. Please retry with the latest version.

**Comment by robertIsaac** [comment]
> This seems to have been fixed. Please retry with the latest version.

still not working
