### ISSUE TITLE
add "outputFileName" to @nx/js:tsc schema

### ISSUE THREAD

**Issue by ghardin1314** [nrwl/nx#17397]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/packages/js/executors/tsc

### Additional context or description

Missing docs for custom entry point file when using an executor like @nx/js:node. The executor looks for `main.js` in the dist folder. To override, must use `outputFileName` option in tsc executor (for instance if entrypoint file is `src/main.js`)

**Comment by tukusejssirs** [comment]
I am not sure if you want me to create a new issue, however, `outputFileName` is also missing in [`nx@18.0.4/schemas/project-schema.json`](https://github.com/nrwl/nx/blob/11c849afabc9dd2ee840355d4e6df3e7e7a36b48/packages/nx/schemas/project-schema.json).

When it is not set in `apps/app/project.json`, anytime I run `nx serve app` (which runs either `app:serve:production` or `app:serve:development`), I get a warning that is is not set for the app and that it uses the fallback value of `dist/apps/app/main.js`.

When I set it in `apps/app/project.json`, I get an error that `outputFileName` is not found in schema.

**Comment by joshuawwright** [comment]
@tukusejssirs I have the exact same problem, tried to fix it just like you did.
