### ISSUE TITLE
Clean up NgRx schematic

### ISSUE THREAD

**Issue by vsavkin** [nrwl/nx#174]
We are already doing a good job at generating some NgRx boilerplate. We can do a lot more though. Some improvements we should consider (ordered highest-to-lowest priority):

* Add store-freeze
*  Use `@ngrx/schematics` to generate much of the scaffolding

**Comment by vsavkin** [comment]
Add entity (see here https://github.com/nrwl/nx/issues/75)

**Comment by ThomasBurleson** [comment]
@vsavkin -  would like to work in thus

**Comment by jschwarty** [comment]
It might be nice to have a `--directory` option to use a different name than +state if needed.

**Comment by ThomasBurleson** [comment]
I will start looking into this on week of Jan 30.

**Comment by ankemp** [comment]
Ngrx added their own schematics: https://github.com/ngrx/platform/tree/master/modules/schematics

**Comment by ankemp** [comment]
@jschwarty, That exists: #137

**Comment by netwobble** [comment]
Any update on adding Entity?  What does this mean if ngrx has their own generator?  Can NX extend ngrx??  

Interesting to see the wiring up of these.. eg Router-Store, RootState, FeatureState, extending EntityState and wire in Workspace.

**Comment by dhknudsen** [comment]
Just curious, with ngrx [adding their own schematics](https://medium.com/ngrx/ngrx-5-and-schematics-2d8cc3906506), is there any plans to make nx compatible with their scheme, or would you encourage people to use your own solution?

**Comment by ThomasBurleson** [comment]
@dhknudsen - the nrwl schematics will extend the ngrx schematics. And we will use @ngrx/schematics to generate the initial ngrx **feature**: actions, reducer, effects. Then we enhance those generated documents with our own Nx extras. See this:

*  [ngrx.md](https://github.com/nrwl/nx/blob/68e34d494fdca1c57a757c889ea8105e8a0a7a6e/packages/schematics/src/collection/ngrx/ngrx.md)
*  [ngrx schematics PR #359 ](https://github.com/nrwl/nx/pull/359)
