### ISSUE TITLE
@nx/expo: the option `install` for expo:run doesn't behave as expected

### ISSUE THREAD

**Issue by Singloo** [nrwl/nx#17409]
### Current Behavior

When I'm running `nx run-ios XXX`, I set `install` to false and I expected should skip the installation step, but it ran anyway.

### Expected Behavior

if I set `install` to false, should skip installation when run `nx run-ios XXX`.

### Steps to Reproduce

1. Set option `install` to false
1. nx run-ios XXX

### Nx Report

```shell
Node   : 16.13.1
   OS     : darwin x64
   pnpm   : 7.27.0
   Hasher : Native
   
   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/detox          : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/expo           : 16.3.2
   @nx/react          : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/web            : 16.3.2
   @nx/webpack        : 16.3.2
   typescript         : 5.0.4
   ---------------------------------------
   Local workspace plugins:
         @muse/types
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

After I upgraded to nx 16, expo keeps warning that some deps are incompatible. Trying to use options to skip dependency installation, but I found that in the source code, the value of `install` does not really control the installation. Please provide a way to skip expo install. 

```
Some dependencies are incompatible with the installed expo version:
  typescript@5.0.4 - expected version: ^4.9.4
Your project may not work correctly until you install the correct versions of the packages.
Install individual packages by running npx expo install typescript@^4.9.4
```

<img width="649" alt="Screenshot 2023-06-04 at 17 36 10" src="https://github.com/nrwl/nx/assets/17946476/b7c0768c-fc40-4fe4-bd19-4ce3e19bcf4e">

**Comment by xiongemi** [comment]
should be fixed as a part of pr https://github.com/nrwl/nx/pull/17372/files
the fix is already in [16.4.0-beta.2](https://github.com/nrwl/nx/compare/16.4.0-beta.1...16.4.0-beta.2)
it will be in next release 16.4.0
