### ISSUE TITLE
Unsatisfied version 1.0.0 from login of shared singleton module @hookform/resolvers/yup (required ^3.1.0)

### ISSUE THREAD

**Issue by fcomabella** [nrwl/nx#17408]
### Current Behavior

I'm using react-hook-form, yup and @hookform/resolvers to manage and validate the forms for my mfe react app.

And I'm having the issue title error.
I've seen that this error has been reported before on #15150.
The original reporter also made a PR #15114, but both the issue and the PR have been closed.

Since I'm having the same error mesaage and I'm willing to continue using nx, I've created a github repo where you can reproduce the issue.

@Coly010 I'm taggin you, because I've seen that you actively commented on both the previous PR and Issue.

I've tried the workarounds commented on the issue, but i wasn't successful.

Thanks for your help

### Expected Behavior

Module federation should require the subpackage version (1.0.0) instead of the general package version (^3.1.0).

### GitHub Repo

https://github.com/fcomabella/nx-mfe-yup-error

### Steps to Reproduce

1. Create an Integrated Monorepo.
2. Install react-hook-form, yup and @hookform/resolvers.
3. Generate a react host and remote using module federation.
4. Set up a react-hook-form managed form validated with yup using yupResolver from @hookform/resolvers/yup.

### Nx Report

```shell
Node   : 18.16.0
   OS     : linux x64
   yarn   : 1.22.19
   Hasher : Native
   
   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/react          : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/web            : 16.3.2
   @nx/webpack        : 16.3.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
If you make sure to not share `@hookform/resolvers` and `@hookform/resolvers/yup` from your login app, then the error is avoided.

Something like the following in your `module-federation.config.js`:

```ts
const sharedLibraries = new Set([
  '@hookform/resolvers',
  '@hookform/resolvers/yup',
]);

module.exports = {
  name: 'login',
  exposes: {
    './Module': './src/remote-entry.ts',
  },
  shared: (library, defaultConfig) => {
    console.log(library);
    if (sharedLibraries.has(library)) {
      return false;
    }
  },
};
```

Then if you also remove those from being shared in your `dashboard` app:

```ts
const deps = require('../../package.json').dependencies;

const sharedLibraries = new Set([
  'react',
  'react-dom',
  'react-hook-form',
  'react-router-dom',
  'yup',
]);

module.exports = {
  name: 'dashboard',
  remotes: ['login'],
  shared: (library, defaultConfig) => {
    console.log(library);
    if (sharedLibraries.has(library)) {
      return {
        ...defaultConfig,
        singleton: true,
        eager: true,
        requiredVersion: deps[library],
      };
    }

    return false;
  },
};
```

This workaround definitely works, and I've added a PR to your repo to showcase this: https://github.com/fcomabella/nx-mfe-yup-error/pull/1

**Comment by fcomabella** [comment]
I've managed to workaround the issue and to keep the `@hookform/resolvers/yup` as a singleton.

The workaround involves no changes to the `module-federation.config.js` file in the host, the `dashboard` project.

The `module-federation.config.js` in the host has to be changed this way:

````Typescript
module.exports = {
  name: 'login',
  exposes: {
    './Module': './src/remote-entry.ts',
  },
  shared: (library, defaultConfig) => {
    if (library === '@hookform/resolvers/yup') {
      return {
        ...defaultConfig,
        strictVersion: false,
      };
    }

    return defaultConfig;
  },
};
````
As the host application doesn't use the `@hookform/resolvers/yup` subpackage, it doesn't need a shared library config, thus it is not present.

When the remote runs its `module-federation.config.js` it does add a config with the `strictVersion` property set to false, and it runs fine.

I'm gonna create a second remote app, to check if all the remotes need the `module-federation.config.js` set up this way.

**Comment by fcomabella** [comment]
After a couple of tests, I've seen that you need to put the snippet

````typescript
shared: (library, defaultConfig) => {
    if (library === '@hookform/resolvers/yup') {
      return {
        ...defaultConfig,
        strictVersion: false,
      };
    }

    return defaultConfig;
  },
````
on all of the remotes that use the library. Ugly, but doable.

you can check it in the branch: https://github.com/fcomabella/nx-mfe-yup-error/tree/validated-form

**Comment by Coly010** [comment]
Glad you found a workaround! As there isn't much else that can be done in this regard, I'm going to close this issue.
