### ISSUE TITLE
"enforce-module-boundaries" fails only on CI

### ISSUE THREAD

**Issue by wojtekolek** [nrwl/nx#17425]
### Current Behavior

For some reason, the linter rule: `enforce-module-boundaries` fails on `Gitlab CI`, which caused tons of unexpected errors. Locally everything works as expected. Everything is configured as should be following the docs (tags etc.).

### Expected Behavior

The `enforce-module-boundaries` check will pass on the CI.

### Steps to Reproduce

Hard to provide some valid steps to reproduce.

### Nx Report

```shell
Node   : 18.16.0
   OS     : darwin arm64
   yarn   : 1.22.19
   Hasher : Native

   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/react          : 16.3.2
   @nx/storybook      : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/web            : 16.3.2
   @nx/webpack        : 16.3.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The issue occurs when we decided to update nx from 15.7.* to 16.3.2.
Any idea what may be causing this sort of unexpected thing?

**Comment by miluoshi** [comment]
The same happens for us after updating from 15.4.2 to 16.2.2. 
It fails with the following error only in CI (Github actions cloud runner Ubuntu 22.0.4): `Imports of lazy-loaded libraries are forbidden`

#### Nx Report

```
Node   : 19.9.0
   OS     : darwin arm64
   yarn   : 1.22.19
   Hasher : Native
   
   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/angular        : 16.2.2
   @nx/cypress        : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nrwl/nx-plugin    : 16.0.0-beta.1
   @nx/react          : 16.2.2
   @nx/rollup         : 16.2.2
   @nx/storybook      : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/web            : 16.2.2
   @nx/webpack        : 16.2.2
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @ngrx/component-store    : 15.3.0
   @ngrx/effects            : 15.3.0
   @ngrx/entity             : 15.3.0
   @ngrx/schematics         : 16.0.0
   @ngrx/store              : 15.3.0
   @nx/nx-plugin            : 16.0.0-beta.1
   @storybook/angular       : 7.0.11
   @testing-library/angular : 13.0.2
   ng2-charts               : 4.1.1
```

**Comment by meeroslav** [comment]
I'm surprised this passes locally if you are getting `Imports of lazy-loaded libraries are forbidden` on CI. What this error means is that you are trying to explicitly import a library that is already being imported lazily in the same file e.g.

```ts
// static import
import { Something } from 'my-library';

if (someCondition) {
  // dynamic import
  const { SomethingElse } = require('my-library');
}
```

This wasn't working properly in the older version, so that's why you weren't getting those errors.

If you think your code is correct and those imports are intentional you can disable the check with
`// eslint-disable-next-line @nx/enforce-module-boundaries` placed before the static import.

Most likely your local install is not clean, so that is the reason you are not getting those errors locally.

**Comment by miluoshi** [comment]
@meeroslav This is not a case here. We don't have any lazy-loaded libraries in our code (neither `require()` nor `import()`) so this really seems like a bug in the eslint rule.

**Comment by meeroslav** [comment]
Can you share the contents of the file that reports this issue? I would like to see what might be triggering that message.

**Comment by miluoshi** [comment]
After clearing all the caches (including eslint caches) it started failing locally. 

> What this error means is that you are trying to explicitly import a library that is already being imported lazily in the same file

This is almost correct, except it checks across the codebase, not only within the same file.

We have a route with lazy-loaded module like this 
```
loadChildren: () => import('@slido/admin-core').then((m) => m.MonitoringModule)
```
And the `@nx/enforce-module-boundaries` rule then throws errors in all imports of that library throughout the repo.
So in the end **I guess** the rule works correctly. The remaining problem for me is that this behaviour is not documented in [the docs](https://nx.dev/packages/eslint-plugin/documents/enforce-module-boundaries) at. Also the error message `Imports of lazy-loaded libraries are forbidden` is too generic for me - `Static imports of lazy-loaded libraries are forbidden` would be much clearer. I could make a PR to update the error message (or the docs), if you are up for it.

**Comment by meeroslav** [comment]
You are correct that this restriction does not end with the file, but spans across the entire project. If you make a static import in one file, there's no point in having a dynamic in another. But it should not be across the entire codebase.

Can you make a minimal repo where this is happening? It could be that something is broken.

Your feedback on the error message is good. This should be fixed. Please feel free to create a PR with a fix.

**Comment by miluoshi** [comment]
> If you make a static import in one file, there's no point in having a dynamic in another. But it should not be across the entire codebase.

Sorry, I was not specific enough. There **is** a dynamic and a static import of the same lib within the same Nx project (app) so I think the rule reports it correctly when I understand it now. 
I just wasn't aware of such check until the upgrade as the lint was passing all along.

**Comment by eliraneliassy** [comment]
@meeroslav I know this one is closed but...the same thing happens to me as well. 
Github CI fails with enforce-module-boundaries errors (which are really exist), but passed locally.

Any suggestions?

**Comment by zargham-leanix** [comment]
`After clearing all the caches (including eslint caches) it started failing locally.`
@miluoshi  I couldn't find eslint cache in an nx workspace, it still passes locally after clearing nx cache.

**Comment by miluoshi** [comment]
> @miluoshi I couldn't find eslint cache in an nx workspace, it still passes locally after clearing nx cache.

@zargham-leanix There's a [global eslint cache](https://eslint.org/docs/latest/use/command-line-interface#caching) if you have it enabled. You can run a eslint command (or `@nx/linter:eslint` executor) without eslint cache by running it with flag `--no-cache`.

**Comment by meeroslav** [comment]
The issue was in bad dependency mapping when using daemon, which has been fixed.
If you are still experiencing this please update to the latest version.
