### ISSUE TITLE
@nx/vite:test duplicates config path for vitest

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [nrwl/nx#17426]
### Current Behavior

When there is no config entry for the executor, it will look in projectRoot. It errors.
If you enter a path and none is found. It errors.
If you enter a path where a vitest.config.ts is found. It duplicates the base path and errors.

Example:

root `C:\\Project\\`
apps `C:\\Project\\apps`
app1 `C:\\Project\\apps\\app1`

```json
"vitest": {
      "executor": "@nx/vite:test",
      "options": {
        "config": "apps/app1/vitest.config.ts"
      }
  }
```
✘ [ERROR] Could not resolve `C:\\Project\\apps\\app1\\apps\\app1\\vitest.config.ts`

### Expected Behavior

Resolve the config correctly

### Steps to Reproduce

1. add a @nx/vite:test target to project.json
2. add path to config file vitest.config.ts
3. run npx nx run ...

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.14.0
   OS     : win32 x64
   npm    : 9.6.7
   Hasher : Native

   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/nest           : 16.3.2
   @nx/node           : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/vite           : 16.3.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @jscutlery/semver : 2.30.1
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by barbados-clemens** [comment]
this should be fixed in #17396 and should be in the next release.
