### ISSUE TITLE
Nrwl compatibility with Next js 13.4

### ISSUE THREAD

**Issue by Ruchika-saini** [nrwl/nx#17428]
### Current Behavior

Working on upgrading the Next JS version to v13.4.4 for the AT&T application. Currently, we are on Nrwl 14 (v14.5.8).
When updating the next JS version from v12.2.3 to v13.4.4, we are facing issues.
Version details:
Next JS version: 13.4.x
Nrwl version: 14.5.8

While doing the analysis, came across the github issues  where nrwl contributor mentioned:
https://github.com/nrwl/nx/issues/17247
-----------------------------------------
_Hi, there we don't fully support Next.js 13.4.0 as yet due to the fact that they are mixing renderers when you are using the pages layout:
https://github.com/vercel/next.js/issues/49169

Initially, we did a migration but undone this change due to issues we found. https://github.com/nrwl/nx/pull/17049

Once Nx 16.3.0 is out it should support it since we will be using the Next.js CLI_

---------------------------------------------------

I see Nrwl v16.3.2 is out  https://www.npmjs.com/package/@nrwl/next?activeTab=readme

**Is NRWL v16.3.2 is compatible with Next JS v13.4 ?**
If not, what's the plan to make it compatible with Next js v13.4?

### Expected Behavior

NRWL packages should work accurately with latest of next js v13.4.4

### Steps to Reproduce

NA

### Nx Report

```shell
NA
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
Hi @Ruchika-saini Is it possible to update to the latest Nx version? Since Next.js 13.2 there was some re-architecture on their end such that our Nx integration is no longer working. This has been patched in Nx 15.9 and Nx 16.x, but 14.x version is no longer supported.

**Comment by Ruchika-saini** [comment]
Thanks @jaysoo for the quick response.
Sure, we will work on upgrading the NX version to the latest v16.

**Just to make sure on this point so that we have clarity on our roadmap:
In Next JS 13.4, there is an app dir release (https://nextjs.org/blog/next-13-4 ) by Vercel which is bringing new major features.
Is NX v16 compatible with Next JS v13.4 as well?**

**Comment by jaysoo** [comment]
Yes, we are 100% compatible with all of the 13.4 Next.js features.
