### ISSUE TITLE
@nx/js:node executor ignores `buildTargetOptions` in version 16.3.0

### ISSUE THREAD

**Issue by DanEscudero** [nrwl/nx#17429]
### Current Behavior

`buildTargetOptions` is ignored in executor `@nx/js:node` in nx@16.3.0. This bug seems to be introduced by [this commit](https://github.com/nrwl/nx/commit/dc7122984e5a6be7c9aa28fd492b8ad310f7a709).

### Expected Behavior

`buildTargetOptions` should be merged into build target options in executor.

### Steps to Reproduce

1. Create a build target;
2. Create another target, that runs `@nx/js:node`, references buildTarget, but adds `buildTargetOptions`;
3. Run the other target, and notice that buildTargetOptions do not apply to build target.

### Nx Report

```shell
Node   : 18.16.0
   OS     : linux x64
   yarn   : 1.22.19
   Hasher : Native
   
   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/nest           : 16.3.2
   @nx/node           : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/webpack        : 16.3.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @pushstart/kolab-nx-package-tools : 0.5.24
   ---------------------------------------
   Local workspace plugins:
         @kolab-back-end/database-authentication
         @kolab-back-end/database-dynamics-proxy
         @kolab-back-end/database-stories-proxy
         @kolab-back-end/database-registration
         @kolab-back-end/database-scheduler
         @kolab-back-end/register-client
         @kolab-back-end/shared-base-app
         @kolab-back-end/database-core
         @kolab-back-end/shared-common
         @kolab-back-end/database-log
         @kolab-back-end/shared-utils
         @kolab-back-end/core-client
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This project.json can be used to reproduce this problem.
When running `yarn nx base test`, test-1/main.js runs, as expected; However, when running `yarn nx other test`, test-2/main.js is expected to run, due to buildTargetOptions; Instead, test-1/main.js is executed.

```
{
  "name": "test",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "libs/test/src",
  "projectType": "library",
  "targets": {
    "base": {
      "executor": "nx:run-script",
      "options": {
        "script": "node ./test-1/main.js",
        "outputPath": "test-1"
      }
    },
    "other": {
      "executor": "@nx/js:node",
      "options": {
        "buildTarget": "test:base",
        "buildTargetOptions": {
          "script": "node ./test-2/main.js",
          "outputPath": "test-2"
        }
      }
    }
  },
  "tags": []
}
```

It seems to me that this bug was introduced in [this commit](https://github.com/nrwl/nx/commit/dc7122984e5a6be7c9aa28fd492b8ad310f7a709) where we can see buildTargetOptions no longer being used.

I believe that the fix is quite easy: merging buildTargetOptions into buildOptions seems to be enough. If so, I'm available to open a PR.

**Comment by mandarini** [comment]
Yep, I'm looking into it! :D

**Comment by mandarini** [comment]
Related: https://github.com/nrwl/nx/issues/17451

**Comment by sergio-milu** [comment]
> Related: #17451

This is still broken because of [this](https://github.com/nrwl/nx/blob/ae698a72748d9f33aa5395aeeaa7b7af436a1dc5/packages/js/src/executors/node/node.impl.ts#L114) all is not passing down the `buildTargetOptions`.
This was working till [16.1.4](https://github.com/nrwl/nx/blob/16f098804653374057eff7e2f9565fb4c7a90b29/packages/js/src/executors/node/node.impl.ts#L208) , as you can see here the `buildTargetOptions` is passed down

**Comment by ekselys** [comment]
I can say also that outputPath is not taken from the specified buildTarget, but from the default buildTarget instead.
In my case this is causing a file not found error:

```
throw new Error(`Could not find ${fileToRun}. Make sure your build succeeded.`);
      ^

Error: Could not find C:\Users\davdi\IdeaProjects\mida_project\dist\apps\mida-server\main.js. Make sure your build succeeded.    
    at fileToRunCorrectPath (C:\Users\davdi\IdeaProjects\mida_project\node_modules\@nx\js\src\executors\node\node.impl.js:235:23)
    at C:\Users\davdi\IdeaProjects\mida_project\node_modules\@nx\js\src\executors\node\node.impl.js:108:102
    at new Promise (<anonymous>)
    at C:\Users\davdi\IdeaProjects\mida_project\node_modules\@nx\js\src\executors\node\node.impl.js:103:40
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\davdi\IdeaProjects\mida_project\node_modules\tslib\tslib.js:114:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by arivera-xealth** [comment]
This is also effecting us. Please reopen. @jaysoo @mandarini

**Comment by gabrielo91** [comment]
Same problem after migrating to the last version of nx

**Comment by mandarini** [comment]
Yeah, we're fixing this.

First things first. `buildTargetOptions` are indeed getting passed @sergio-milu :  https://github.com/nrwl/nx/blob/master/packages/js/src/executors/node/node.impl.ts#L53

So the issue relies on `fileToRun` which we will be fixing asap. I have a PR open, and there's another one by @skrtheboss . I will evaluate today which of these should go through, if not both.

So, I'm closing this issue, since `buildTargetOptions` are getting passed down. The `fileToRun` issue is tracked here: https://github.com/nrwl/nx/issues/17800 and here: https://github.com/nrwl/nx/issues/17946
