### ISSUE TITLE
Add cacheability option to targets

### ISSUE THREAD

**Issue by MJez29** [nrwl/nx#17443]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I would like to define cacheability on a target level. Rather than specifying

```json
"taskRunnerOptions": {
  "default": {
    "options": {
      "cacheableOperations": ["build", "test"]
    }
  }
}
```

I would like to do

```json
"targets": {
  "build": {
    "cacheable": true
  },
  "test": {
    "cacheable": true
  },
  "publish": {
    // or could be omitted (default = false)
    "cacheable": false
  }
}
```

This can also be set in targetDefaults to emulate the current behaviour

## Motivation

I would like to specify cacheable operations by project+target rather than just target. This allows for the configuration to be defined with the target rather than in a separate config field. It also allows for more fine-grained control over the operations that are cached.

## Suggested Implementation

Modify the implementation of [isCacheableTask](https://github.com/nrwl/nx/blob/master/packages/nx/src/tasks-runner/utils.ts#L351) to be

```ts
const cacheableOperations = options.cacheableOperations || options.cacheableTargets;
const isOperationCacheable = !!cacheable &&cacheable.indexOf(task.target.target) > -1
const isTargetCacheable = task.target.cacheable; // This field will needed to be added
return (isOperationCacheable || isTargetCacheable) && ...
```

**Comment by meeroslav** [comment]
This is interesting proposal @MJez29.

Can you explain a scenario where this would be necessary? What would be the target that you want cacheable for some projects but not for others?

In our experience, certain targets are always cacheable e.g. `build` and some never are e.g. `publish`.

Help us understand the requirement behind this change proposal.

**Comment by MJez29** [comment]
Hi @meeroslav 

I'm currently preparing a monorepo to bring in multiple large actively developed applications. These apps don't have fully standardized package.json scripts so I'd end up with a long list of `cacheableOperations` where many of the targets are for a single project.

By controlling caching on a project + target level this will allow me to disable caching for an application that I've just brought in. This reduces the critical path of work needed to move over the app from its own repository and allows me to configure inputs and outputs after performing the migration so that I am actually caching the operations for this application effectively.

This is also nice to have because it allows application owners to have full control over their projects' ci and it increases visibility into what targets are cached because developers (who may have never used nx before) will only need to look at `project.json#targets` and `nx.json#targetDefaults` to understand how their targets behave.

**Comment by meeroslav** [comment]
I feel there are several challenges in your set up, none if which should strictly be solved by suggested configuration.

When importing non-standardized scripts, you can simply set all targets to be non-cacheable until you are ready to have them cacheable.

If you have multiple projects with the same target, but only some of those should be cacheable, you can control cache-ability of a single project/target by adding a dynamic input to it's target that would always change e.g.
```jsonc
{
  "targets": {
    "build": {
      "dependsOn": ["^build"],
      // this runtime command will generate unique timestamp leading to cache miss
      "inputs": ["prod", { "runtime": "date +%s" }], 
      "executor": "@nx/js:tsc",
      "outputs": ["dist/{projectRoot}"],
    },
  },
}
```

While this is not as explicit as using something like `cacheable` flag, I believe it's a very specialized corner case requirement that even for you would be just temporary, so I don't see a point of adding more complexity to the existing config API for it.

Nx is modular and config of a project is a combination of the defaults, targetDefaults from `nx.json` and config in the `project.json` or `package.json` so you can't really be sure if you just look at one place. I don't think that having cacheability setup in `nx.json` leads to complexity or lesser readability of the config.

**Comment by MJez29** [comment]
I ended up coming up with something pretty similar to what you're suggesting, the main difference is that if the runtime input is being calculated in a ci environment it'll return the build ID so that it can be replayed via DTE on the main agent without rerunning

Thanks!
