### ISSUE TITLE
Nx + Nextjs app with custom baseUrl won't load assets

### ISSUE THREAD

**Issue by dlarroder** [nrwl/nx#17454]
### Current Behavior

I have a nextjs app that has a baseUrl configured, I ran the latest migration of `nx migrate latest` which was successful in updating all my deps. But after updating we seem to not be able to load our assets without specifying the baseUrl.

Previous Code

```
<Image  src="/images/blackcat.jpeg" />
```

Now we have to
```
<Image  src="nextjs/images/blackcat.jpeg" />
```
`nextjs` being our basePath.

### Expected Behavior

Our asset should load normally without specifying the basePath in our code.
```
<Image  src="/images/blackcat.jpeg" />
```
### GitHub Repo

https://github.com/dlarroder/nx-nextjs-repros

### Steps to Reproduce

1. Clone the repo
2. Install deps with `yarn` on the root
3. Run the next-app with `nx serve next-app`
4. Go to http://localhost:4200/nextjs
5. See that image is not loading correctly without specifying the basePath

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin arm64
   yarn   : 1.22.19
   Hasher : Native
   
   nx (global)        : 16.2.2
   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/next           : 16.3.2
   @nx/react          : 16.3.2
   @nx/storybook      : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/web            : 16.3.2
   typescript         : 5.0.4
   ---------------------------------------
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
This was a Nx-specific feature, but moving forward we decided to match the behaviour of Next.js.

Therefore, this does not work for Next.js' image component as you need to specify the `baseUrl` as documented on Next.js: 

https://nextjs.org/docs/app/api-reference/next-config-js/basePath

> When using the [next/image](https://nextjs.org/docs/pages/api-reference/components/image) component, you will need to add the `basePath` in front of `src`.
