### ISSUE TITLE
@nx/angular fetch is undefined in tests

### ISSUE THREAD

**Issue by alessandro-verdura-maersk** [nrwl/nx#17455]
### Current Behavior

When trying to upgrade from `@nx/angular@16.1.x` to `@nx/angular@16.3.x`, any tests related to code using [`fetch`](https://nx.dev/recipes/other/misc-data-persistence#data-fetching) starts to fail, with this error:

```ts
// TypeError: (0, angular_1.fetch) is not a function

class OneOfMyEffects {
  public someEffect$ = createEffect(() =>
    this.actions$.pipe(
      ofType(MyActions.someAction),
      fetch({ // <-- error is thrown here
        run: () => {}
      })
    )
  );
}
```

It actually seems that anything imported from `@nx/angular` is `undefined` when the code is running in the test environment
 
I tracked the issue coming from something added to [`16.3.0-beta.8`](https://github.com/nrwl/nx/compare/16.3.0-beta.7...16.3.0-beta.8), but couldn't figure out the exact issue : /

### Expected Behavior

That `fetch` is available as before in the test environment

### Steps to Reproduce

1. Bump `@nx/angular` to a version equal to or greater than `16.3.0-beta.8`
2. Tests some code that imports the module's `fetch` function
3. Should get an error saying that `fetch` is undefined

### Nx Report

```shell
Node   : 18.16.0
OS     : darwin x64
npm    : 9.5.1
Hasher : Native

nx                 : 16.3.2
@nx/js             : 16.3.2
@nx/jest           : 16.3.2
@nx/linter         : 16.3.2
@nx/workspace      : 16.3.2
@nx/angular        : 16.3.2
@nx/cypress        : 16.3.2
@nx/devkit         : 16.3.2
@nx/eslint-plugin  : 16.3.2
@nx/express        : 16.3.2
@nx/node           : 16.3.2
@nrwl/tao          : 16.3.2
@nx/web            : 16.3.2
@nx/webpack        : 16.3.2
nx-cloud           : 16.0.5
typescript         : 4.8.4
---------------------------------------
Community plugins:
@compodoc/compodoc    : 1.1.21
@ngrx/component-store : 14.3.3
@ngrx/effects         : 14.3.3
@ngrx/entity          : 14.3.3
@ngrx/router-store    : 14.3.3
@ngrx/schematics      : 14.3.3
@ngrx/store           : 14.3.3
@ngrx/store-devtools  : 14.3.3
ngrx-immer            : 2.0.1
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by swcm-mnestler** [comment]
I also ran into this issue when updating to 16.3. 
Looks like this was caused by the new `index.cts` - [index.ts](https://github.com/nrwl/nx/blob/0e88b12d4a5e7d3d7faae92f4fe957cd0e13f794/packages/angular/index.ts) exports `fetch`, [index.cts](https://github.com/nrwl/nx/blob/0e88b12d4a5e7d3d7faae92f4fe957cd0e13f794/packages/angular/index.cts) doesn't. 

I worked around this by setting `'^@nx/angular$': __dirname + '/node_modules/@nx/angular/index.js'` in my `jest.preset.js`

**Comment by alessandro-verdura-maersk** [comment]
@swcm-mnestler thanks a lot, it works!
