### ISSUE TITLE
Failing to add @nrwl/angular to a new workspace

### ISSUE THREAD

**Issue by joelmuskwe** [nrwl/nx#1745]
## Expected Behavior

Expecting to be able to run `ng add @nrwl/angular`

## Current Behavior
Getting the below attached error:
<img width="904" alt="Screenshot 2019-08-22 at 06 59 44" src="https://user-images.githubusercontent.com/5989937/63487187-93859380-c4aa-11e9-87d0-53fc019f41df.png">

## Failure Information (for bugs)

Error message i am getting is: **_The add command requires to be run in an Angular project, but a project definition could not be found._**

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. npx create-nx-workspace@latest myworkspace
2. cd myworkspace/
3. ng add @nrwl/angular

**Comment by ahnpnl** [comment]
When choosing Nx CLI to generate a workspace,the original ng command won't work. You just need to run yarn add --dev @nrwl/angular, it is stated in the README.

**Comment by joelmuskwe** [comment]
@ahnpnl that would only add the @nrwl/angular as a package in your package.json the project is then even refusing to open with angular-console both the standalone app and the vscode extension find attached files generated in the project and as you can see there is no angular.json file that has been generated.

<img width="1059" alt="Screenshot 2019-08-22 at 08 15 02" src="https://user-images.githubusercontent.com/5989937/63490561-478c1c00-c4b5-11e9-93a4-d478aae6ad03.png">

**Comment by ahnpnl** [comment]
That is the trade-off of choosing Nx CLI. If generating workspace choosing Angular CLI, you will get angular.json . I encountered the same issue as yours, but my team had to figure out by ourselves about that. You can't find this in Nx documentation.

**Comment by joelmuskwe** [comment]
@ahnpnl thank you the command line is confusing.

**Comment by sardapv** [comment]
this still gives same error, can somebody help how to proceed with this. documentation doesn't state anything just that command with npm add --dev... works but next command throws same error!

**Comment by irowbin** [comment]
@sardapv Yeah, looks like `yarn add @nrwl/angular` works instead of `ng add @nrwl/angular` but the doc suggest `ng add @nrwl/angular` which throws an error. 

 @meeroslav I followed this [nx doc](http://nx.dev/latest/angular/examples/react-and-angular) but got an error. Are we forced to use yarn for  empty workspace? 

I ended up here cause the above issue and it works with `yarn` but not with `ng` for empty workspace.

Thanks. 😎

**Comment by meeroslav** [comment]
Hey @irowbin,

Thank you for reporting this error in the docs. Until we change it there, please use:
```bash
npm install -D @nrwl/angular
# or
yarn add -D @nrwl/angular
# or
pnpm add -D @nrwl/angular
```

Although most of the `ng ...` commands would still be translated to `nx ...`, add is unfortunately not among them. If you generate workspace with `create-nx-workspace --cli=angular`, you would still have full access to `ng` commands.

**Comment by sardapv** [comment]
I had opened a PR already 😢..  @meeroslav 
https://github.com/nrwl/nx/pull/6407

**Comment by meeroslav** [comment]
Sorry about that @sardapv. I was hoping my PR was not merged in when I saw your message.

Please in the future link the original issue so it shows here in the thread.
Also providing a description makes it easier for a person checking PRs to know what it's about.

I hope your next PR will be successful. Thank you for your help!
