### ISSUE TITLE
Changes to the way the proxyConfig file (@angular-devkit/build-angular:dev-server executor) is invoked

### ISSUE THREAD

**Issue by nspire909** [nrwl/nx#17452]
### Current Behavior

In NX 16.3.2, calling process.argv in the proxyConfig file (proxy.conf.js) in the executor @angular-devkit/build-angular:dev-server yields:
```
[
  '...\\node.exe',
  '...\\repo\\node_modules\\nx\\bin\\run-executor.js'
]
```

### Expected Behavior

In previous releases (at least NX 16.1.0 and before; I didn't try releasees in between 16.1.0 and 16.3.2), calling process.argv in the proxyConfig file (proxy.conf.js) in the executor @angular-devkit/build-angular:dev-server yields:
```
[
  '...\\node.exe',
  '...\\repo\\node_modules\\nx\\bin\\run-executor.js',
  '{"targetDescription":{"project":"ibs-ui","target":"serve","configuration":"localdev1"},"overrides":{"__overrides_unparsed__":[]},"isVerbose":false}'
]
```

The third param has been removed. My proxyConfig relies on knowing the configuration value ("localdev1" in the above example.) Is there another way to obtain this information in the proxyConfig file? If not, whatever change caused the third param to be removed needs to be reverted.

### Steps to Reproduce

1. Create an Angular app with a proxyConfig JavaScript file using NX 16.3.2
2. Add `console.log(process.argv);` to the proxyConfig file
3. Run the app
4. Console output will show two args.
5. Repeat 1-4 with NX 16.1.1
6. Console output will show three args, including the configuration value

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.2.0
   OS     : win32 x64
   yarn   : 1.22.19
   Hasher : Native

   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/angular        : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/nest           : 16.3.2
   @nx/node           : 16.3.2
   @nx/plugin         : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/webpack        : 16.3.2
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @ngx-pwa/local-storage : 16.3.0
   nx-stylelint           : 15.0.0
   ---------------------------------------
   Local workspace plugins:
         @ibs/ibs-plugins
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

My repo is in a locked down env. Let me know if you need me to recreate a minimal example in github.

**Comment by Coly010** [comment]
Hey there!

Instead of accessing the `configuration` from `process.argv` you can get it from an env var that we set: `NX_TASK_TARGET_CONFIGURATION` which should be accessible from `process.env.NX_TASK_TARGET_CONFIGURATION` 

You can see more env vars that we set here: https://nx.dev/reference/environment-variables#environment-variables

**Comment by nspire909** [comment]
Excellent. ty.
