### ISSUE TITLE
--code-coverage not printing coverage to console

### ISSUE THREAD

**Issue by jared-christensen** [nrwl/nx#1746]
## Expected Behavior

when running  the command
ng test libName --codeCoverage=true
I expect the console to show a coverage report

## Current Behavior

Test run but no coverage report is shown in the console.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

**Comment by mehrad-rafigh** [comment]
@jared-christensen This is the default behaviour. Please refer to https://github.com/nrwl/nx/issues/1337 and close this issue, as it is a duplicate :)

**Comment by bcabanes** [comment]
This issue is a duplicate of #1337, closing.
