### ISSUE TITLE
Keys defined in .env files that reference another env variable for vite are not working

### ISSUE THREAD

**Issue by tlehtimaki** [nrwl/nx#17461]
### Current Behavior

If you have this in your .env
```
KEY=123
API_PATH=/api/v2/$KEY
```
and run `nx build your-app` which runs `"build": "tsc && vite build"` from the `package.json` of `your-app` with its depencies. The passed envs will have these values:
```
KEY=123
API_PATH=/api/v2/$KEY
```

### Expected Behavior

Expectation would be for the values to be:
```
KEY=123
API_PATH=/api/v2/123
```
the problem is that they are passed to runtime so vite does not do anything to those dollar signs anymore and that causes havoc.

### Steps to Reproduce

1. Create `.env` file
2. Create KEY=123 value
3. Create API_PATH value that references the KEY value
4. Do referenching like this API_PATH=/api/v2/$KEY
5. See that vite is not processing your .env as you would expect

### Nx Report

```shell
Node   : 16.14.2
 OS     : darwin arm64
 pnpm   : 7.27.1
 Hasher : Native
   
 nx (global)  : 16.3.2
 nx           : 16.3.2
 @nrwl/tao    : 16.3.2
 typescript   : 4.9.5
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
I'll try to look into this today, but just for the record, running `nx build your-app` __only__ runs `vite build`, and not `tsc && vite build` (yet).

**Comment by mandarini** [comment]
Ohhh sorry @tlehtimaki  I misunderstood! :) I thought you meant that the existing built-in behaviour of our `@nx/vite:build` executor runs `tsc` as well, and this is why I said what I said. I meant that the existing built-in behaviour of our `@nx/vite:build` executor does not run `tsc`. If you have set it up to do so, it will most certainly do so! :) Sorry for the confusion, I hope I cleared this up.

In any case, once [this PR](https://github.com/nrwl/nx/pull/17487) is merged, the existing built-in behaviour of our `@nx/vite:build` executor will also run type checking.

**Comment by mandarini** [comment]
@tlehtimaki make sure you prepend your variables with `VITE_` as noted in the Vite docs: https://vitejs.dev/guide/env-and-mode.html

I put in a PR which should fix your issue!

**Comment by mandarini** [comment]
This is going to be fixed in the future, see this comment here: https://github.com/nrwl/nx/pull/17495#issuecomment-1582827800
