### ISSUE TITLE
Explore testing improvements

### ISSUE THREAD

**Issue by vsavkin** [nrwl/nx#175]
We should generate opinionated tests for modules, lazy-loaded modules, components, etc. The CLI generates some tests, but they are so basic that they are not really usable.

**Comment by mrmeku** [comment]
I chatted with @vsavkin a bit and here was my first suggestion of how to improvde the default module tests

```
import {SomeModule} from './some.module';

describe('SomeModule', () => {
  beforeEach(async(() => {
    TestBed
        .configureTestingModule({imports: [SomeModule]})
        .compileComponents();
  }));

  it('should compile', () => {});
});
```

**Comment by vsavkin** [comment]
At the moment we decided to give folks more control over what kind of libs and tests they generate. They can create workspace schematics and use those to enforce org-specific best practices.
