### ISSUE TITLE
nx affected:build using origin/master

### ISSUE THREAD

**Issue by Jordan-Hall** [nrwl/nx#1750]
It appears you can't compare with a remote branch. 

```
added 2553 packages in 309.571s
+ npm run affected:build --base=origin/master --parallel

> rina-eas@0.0.0 affected:build /var/lib/jenkins/workspace/project-name
> nx affected:build

fatal: Not a valid object name master

>  NX   ERROR  There was a critical error when running your command

  Command failed: git merge-base master HEAD
fatal: Not a valid object name master

```

**Comment by dave-gohyperion** [comment]
@Jordan-Hall did you find a resolution for this? I'm running into this same error why trying to run `nx affected:build` inside Gitlab CI/CD.

**Comment by FazioNico** [comment]
> @Jordan-Hall did you find a resolution for this? I'm running into this same error when trying to run `nx affected:build` inside Gitlab CI/CD.
> 
> Nevermind, figured it out, for anyone else... Gitlab settings for CI by default doesn't fetch all the branches.

Hi, you've test this https://github.com/nrwl/nx/issues/1356 ? it work for me.

**Comment by tommck** [comment]
`npm run affected:build --base=origin/master --parallel`

Don't you have to add an extra `--` in there to pass the commands to `nx`?

`npm run affected:build -- --base=origin/master --parallel`

**Comment by Jordan-Hall** [comment]
@tommck that correct why i closed it. believe their was another issue too but cant remember
