### ISSUE TITLE
@nx/js:node executor ignores `waitUntilTargets` options

### ISSUE THREAD

**Issue by chromey** [nrwl/nx#17524]
### Current Behavior

The `@nx/js:node` executor is no longer evaluating the `waitUntilTargets` option. This seems to be a regression introduced in #16924. I realise that #17451 and #17429 already exist, but this seems to be a separate problem.

### Expected Behavior

`waitUntilTargets` should be supported.

### Steps to Reproduce

1. Create a target with the `@nx/js:node` executor
2. Define an `options` object with a `waitUntilTargets` options
3. When executing the target, the `waitUntilTargets` are ignored. If the `waitUntilTargets` do not exist, the error is not reported

### Nx Report

```shell
Node   : 18.16.0
   OS     : darwin arm64
   npm    : 9.5.1
   Hasher : Native
   
   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/devkit         : 16.3.2
   @nrwl/devkit       : 15.9.4
   @nx/eslint-plugin  : 16.3.2
   @nx/nest           : 16.3.2
   @nx/node           : 16.3.2
   @nx/plugin         : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/webpack        : 16.3.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc     : 1.1.21
   @nx-tools/nx-container : 4.0.4
   @nx-tools/nx-docker    : 3.0.8
   @twittwer/compodoc     : 1.9.0
   ---------------------------------------
   Local workspace plugins:
         @dc-nest-apps/workspace-plugin
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
@chromey In the meantime, can you use `dependsOn` on the serve target (in `project.json`) to run those required targets before starting serve?

```json
"serve":{
  "dependsOn": ["target1", "target2", ...]
  ...
}
```

**Comment by chromey** [comment]
@jaysoo Thanks, in fact this works for me. Which makes me wonder what the justification for `waitUntilTargets` actually is. Is there a semantic difference? I guess nx will run cacheable `dependsOn` tasks only if needed, whereas `waitUntilTargets` are always executed, but other than that?

**Comment by jaysoo** [comment]
It was added before `dependsOn` was a thing in Nx. It should have been a migration to move those targets into `dependsOn` option. I will add that migration for the next release.

**Comment by jaysoo** [comment]
We'll add back support since some cases are not possible using `dependsOn` (e.g. specifying configurations that differ from current `--configuration=<config>`). We might deprecate it later and remove it more carefully in the future.
