### ISSUE TITLE
Recommended configuration to support MFE setup on Caddyserver v2

### ISSUE THREAD

**Issue by benpsnyder** [nrwl/nx#17533]
### Documentation issue

We used NGINX for a long time and we have a preferred setup for hosting MFEs. I'd be glad to share that config. However, we wanted to make the switch to [Caddyserver](https://caddyserver.com/) and ditch NGINX. For a while, we had to use Caddy on the front for :443 and proxy to NGINX on 127.0.0.1:80 or 127.0.0.1:8080 to handle the remotes.

Until now .....

We renamed our company as "acme" in this example config. We made this config for a monorepo where there are three shells:
- **colleague** (for our employees to use a suite of apps)
- **client** (for our clients to use a suite of apps)
- **partner** (for partners of ours to access apps in our ecosystem, purpose built for them)

In this example, we demonstrate the following **colleague** remotes, each of which handle specific segments of our business:
- **accounting**
- **integrations**
- **licensing**
- **marketing**
- **merit**
- **projects**
- **sales**
- **service**
- **settings**
- **time**
- **user**

Here is a working configuration for Caddy. _**Trailing slashes really matter**_!

```sh
# /etc/caddy/Caddyfile
{
	email systems@acme-corp.com
}

(publicApiHandlers) {
	# core
	handle_path {args.0}/core/bff/exchange* {
		uri strip_prefix {args.0}/core/bff/exchange
		reverse_proxy 127.0.0.1:36406
	}
	# edge
	handle_path {args.0}/edge/bff/client* {
		uri strip_prefix {args.0}/edge/bff/client
		reverse_proxy 127.0.0.1:36401
	}
	handle_path {args.0}/edge/bff/colleague* {
		uri strip_prefix {args.0}/edge/bff/colleague
		reverse_proxy 127.0.0.1:36400
	}
	handle_path {args.0}/edge/bff/legacy* {
		uri strip_prefix {args.0}/edge/bff/legacy
		reverse_proxy 127.0.0.1:36403
	}
	handle_path {args.0}/edge/bff/partner* {
		uri strip_prefix {args.0}/edge/bff/partner
		reverse_proxy 127.0.0.1:36402
	}
}

# {args.0}=/colleague
(mfeShell) {
	handle {
		root * /var/www/production/acme-apps/dist/apps/edge/mfe/shell{args.0}/
		encode zstd gzip
		try_files {path} /index.html
		file_server
	}
}

# {args.0}=/colleague | {args.1}=/accounting
(mfeRemote) {
	handle_path {args.0}{args.1}/* {
		root * /var/www/production/acme-apps/dist/apps/edge/mfe/ecosystem{args.0}{args.1}/
		uri strip_prefix {args.0}{args.1}/
		try_files {path}
		file_server {
			index off
		}
	}
	handle_errors {
		@404 {
			expression `{http.error.status_code} == 404`
		}
		handle @404 {
			import mfeShell "{args.0}"
		}
	}
}

v5-app.acme-corp.com {
	handle /api* {
		# handle secure public APIs on the /api/** sub-URI
		encode zstd gzip
		header Access-Control-Allow-Methods "POST, GET, OPTIONS"
		import publicApiHandlers "/api"
	}
	import mfeRemote "/colleague" "/accounting"
	import mfeRemote "/colleague" "/integrations"
	import mfeRemote "/colleague" "/licensing"
	import mfeRemote "/colleague" "/marketing"
	import mfeRemote "/colleague" "/merit"
	import mfeRemote "/colleague" "/projects"
	import mfeRemote "/colleague" "/sales"
	import mfeRemote "/colleague" "/service"
	import mfeRemote "/colleague" "/settings"
	import mfeRemote "/colleague" "/time"
	import mfeRemote "/colleague" "/user"

	# fallback handler
	import mfeShell "/colleague"
}

```

**Comment by Coly010** [comment]
Would you like to make a short blog post on this? We could link to it then from our docs page

**Comment by benpsnyder** [comment]
Thanks @Coly010! Sure I will get that in the works and post back here when ready.
