### ISSUE TITLE
Feature Request: Make config files optional

### ISSUE THREAD

**Issue by mann-david** [nrwl/nx#1754]
## Expected Behavior
Generating libs gives you the option of **not** creating the config and ReadMe files and just inheriting from up the folder hierarchy

## Current Behavior
Generating libs creates all of the config files and a ReadMe in each generated library

## Other

For smaller or less-complex setups, having all of the config/etc. files in **each** lib is just clutter.  Most of the time, they just point to a file further up the chain so they're kind of superfluous.  It would be nice to be able to not create them and then if need be, I can manually add them only where necessary.

**Comment by FrozenPandaz** [comment]
This would be a good first issue for someone from the community to contribute. Would somebody be willing to take a look?

**Comment by tonivj5** [comment]
I was looking this issue! I'm with @mann-david. An option to disable creation of all superfluous files (tsconfig*, tslint/eslint, jest config and readme) when those files doesn't change at all.

Maybe I could take a look at this. @FrozenPandaz, where should I start?

**Comment by tonivj5** [comment]
Up

**Comment by Jordan-Hall** [comment]
What are you thinking? For example jest for react is different from angular. I also believe some tsconfig are different too regarding compiling (ill take a look in morning) 

The readme work make sense but you in essence enforcing the root to contain all the options. I could see the use of generate each integration type into the tools folder and always reference the config from the tools. I believe this would work in 90% of cases.

Could add an option to the workspace.json or angular.json to show its a minified library. We can use the app src property and inject it into the builder.

**Comment by tonivj5** [comment]
> Up

**Comment by tonivj5** [comment]
> > Up
> 
>
