### ISSUE TITLE
Module '"react"' has no exported member 'cache'

### ISSUE THREAD

**Issue by sebpalluel** [nrwl/nx#17555]
### Current Behavior

I'm trying to build a library using the latest react `cache` function.

I get the following error during build using rollup:
```ts
libs/client/react-query/src/lib/getQueryClient.ts:2:10 - error TS2305: Module '"react"' has no exported member 'cache'.

  1 | import { QueryClient } from '@tanstack/query-core';
> 2 | import { cache } from 'react';
    |          ^
  3 | 
  4 | export const getQueryClient = cache(() => new QueryClient());
  5 | 

Found 1 error.
```

### Expected Behavior

The issue is documented [here](https://github.com/vercel/next.js/issues/49707) and should be fixed by using the latest `@types/react` version.

The react types should not be fixed but parsed from the root `package.json`

https://github.com/nrwl/nx/blob/18c1be8b86024076aeccbf95e6282a1f480bbb18/packages/react/src/utils/versions.ts#L11

### GitHub Repo

https://github.com/sebpalluel/nx-examples

### Steps to Reproduce

1. `pnpm install`
2. `nx run react-query:build`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.1.0
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx                 : 16.4.0-beta.3
   @nx/js             : 16.4.0-beta.3
   @nx/jest           : 16.4.0-beta.3
   @nx/linter         : 16.4.0-beta.3
   @nx/workspace      : 16.4.0-beta.3
   @nx/angular        : 16.4.0-beta.3
   @nx/cypress        : 16.4.0-beta.3
   @nx/devkit         : 16.4.0-beta.3
   @nx/eslint-plugin  : 16.4.0-beta.3
   @nx/react          : 16.4.0-beta.3
   @nx/rollup         : 16.4.0-beta.3
   @nx/web            : 16.4.0-beta.3
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 16.0.0
   @ngrx/effects         : 16.0.0
   @ngrx/entity          : 16.0.0
   @ngrx/router-store    : 16.0.0
   @ngrx/store           : 16.0.0
   @ngrx/store-devtools  : 16.0.0
   ---------------------------------------
   Local workspace plugins:
   	 @nx-example/react-query
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by sebpalluel** [comment]
Hi !
The issue is not coming from `@types/react` after all. `cache` is provided by nextjs as explained [here](https://stackoverflow.com/a/75854179/10679851) so i've added "next" into the types for build and it worked. Would be better to have it by default for nextjs libs tho ;).
https://github.com/nrwl/nx-examples/commit/e3ac1282590de0d617c4057a898d3c02de9f51d1

**Comment by mandarini** [comment]
Oh cool! Thanks! :D

**Comment by mandarini** [comment]
So, @sebpalluel I think you are right, we should add the `next` types in the `tsconfig.lib.json` of `@nx/next` libs! So I will create a PR with this fix! :) I will also update the React types version as you suggested!

In your case, however, this was a React library, so I think it makes sense that `next` and the `next` types were not added!
