### ISSUE TITLE
Error with graph extension plugin after upgrading to 16.3.2

### ISSUE THREAD

**Issue by leggomuhgreggo** [nrwl/nx#17563]
### Current Behavior

Any action which triggers the project graph to be computed, causes an error with nx-vue graph extension plugin

### Expected Behavior

Should be able to run without error

### GitHub Repo

https://github.com/leggomuhgreggo/nx-vue-error-repro

### Steps to Reproduce

1. clone, install
2. run yarn nx format:write
3. observe error

### Nx Report

```shell
Node   : 16.15.1
   OS     : darwin x64
   yarn   : 1.22.19
   Hasher : Native
   
   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/esbuild        : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/node           : 16.3.2
   @nrwl/tao          : 16.3.2
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   nx-vue : 1.1.0

✨  Done in 0.51s.


NOTE: this actually errors too, but commented out the plugin in nx.json as a work around
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Searching the nx-vue repo for the "some" keyword -- [this](https://github.com/search?q=repo%3Aagmonks%2Fnx-vue%20some&type=code) seems most likely candidate:

```
118 | for (const r of res) {
119 | if (
120 | !graph.nodes[r.sourceProjectName].data.files.some(
121 | (f: FileData) => f.file == r.sourceProjectFile
122 | )
123 | ) {

```

Commenting it out seems to alleviate, although presumably breaks the feature.

**EDIT:** Opened an issue on the nx-vue repo [here](https://github.com/agmonks/nx-vue/issues/3)

**Comment by khalilou88** [comment]
files attribute was removed from ProjectConfiguration type in version 16.3.0

**Comment by leggomuhgreggo** [comment]
Figured out the issue here -- just waiting on a PR to merge on the plugin repo. I'm going to close this. Thanks for your help @khalilou88!
