### ISSUE TITLE
@nx/rollup does not pick up exact version of root package.json dependencies

### ISSUE THREAD

**Issue by davidren-apt** [nrwl/nx#17591]
### Current Behavior

If I have a library dependency - `a@^1.0.0` in root `package.json`, after build using `@nx/rollup` bundler, the version is picked up partially with `1.0.0` instead of `^1.0.0` which would cause some potential upgrade issue when I try to consume this component in other applications.

```package.json
{
  //...
  "dependencies": {
    "a": "1.0.0",
  },
}
```

Just to compare, for another component I wrote, executor `@nx/js:tsc` is used as it is pure typescript library, the version is picked up correctly with `^1.0.0`.

### Expected Behavior

The dependency version in my publishable component bundle should be:

```package.json
{
  //...
  "dependencies": {
    "a": "^1.0.0",
  },
}
```

### Steps to Reproduce

1. Generate a component using:
  `npx nx g @nx/react:library ${COMPONENT_NAME} --bundler=rollup --style="styled-components" --publishable --importPath="@myOrg/${COMPONENT_NAME}"`

2. Define build executor for this library using:

```
"executor": "@nx/rollup:rollup",
"options": {
  // ...
  "external": "all",
  "buildableProjectDepsInPackageJsonType": "dependencies",
  "updateBuildableProjectDepsInPackageJson": true,
  // ...
}
```

3. Write code with global dependency defined in root package.json.

4. Run `npx nx run component:build`.

5. Check the `package.json` file in `dist` folder bundle resources.

### Nx Report

```shell
Node   : 16.19.0
   OS     : darwin arm64
   npm    : 8.19.3
   Hasher : Native

   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/express        : 16.3.2
   @nx/next           : 16.3.2
   @nx/node           : 16.3.2
   @nx/react          : 16.3.2
   @nx/rollup         : 16.3.2
   @nx/storybook      : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/web            : 16.3.2
   @nx/webpack        : 16.3.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @jscutlery/semver : 3.0.0
   ---------------------------------------
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by davidren-apt** [comment]
@mandarini any update on this? Thanks!

**Comment by mandarini** [comment]
@davidren-apt no sorry, no updates yet :( I will try to see if anyone has time to look at it this week, or else I can take a look next week maybe! Have you managed to find any workarounds, maybe?
