### ISSUE TITLE
'styles' object key always sets its value as an array with Jest testing

### ISSUE THREAD

**Issue by davideasaf** [nrwl/nx#1759]
## Expected Behavior
When running a Jest test for an Angular application that was setup using the NX workspace, the key `styles` in any object should be allowed to be mutated.

## Current Behavior

Running Jest tests for an Angular application that was setup using the NX workspace, the key `styles` in an object is always set to an array `[]`.

### Steps to Reproduce
1. Create a brand new nx-workspace with `npx create-nx-workspace@8.4.12 test-workspace` (I used latest at the time)
2. Make the below selections:
       1. angular
       2. test-workspace
       3. sass
       4. Yes
![Screen Shot 2019-08-27 at 4 09 26 PM](https://user-images.githubusercontent.com/11589969/63805863-55dc9c80-c8e8-11e9-8eb7-bacde790858c.png)

![Screen Shot 2019-08-27 at 4 09 37 PM](https://user-images.githubusercontent.com/11589969/63805864-56753300-c8e8-11e9-90df-74434698c683.png)

3. Run
```bash
cd nx-workspace
```
4.  Change the `apps/test-workspace/src/app/app.component.spec.ts` file to only be the below:
```javascript
describe('BIZARRE TEST', () => {
  it('', () => {
    const foo = { styles: 'hello world' };
    if (Array.isArray(foo.styles)) {
      console.log('THIS SHOULD NOT PRINT');
    }
    console.log('FOO IS:', foo);
    expect(Array.isArray(foo.styles)).toBe(false);
  });
});
```
5. Run
```bash
yarn test
```
6. Result: The test does not pass. This indicates that using `styles` as an object key always sets the value to `[]`. 

## Other
- I have created a minimal Jest application to test if this issue was only relevant for Jest, but the issue was not present in Jest. 
- Repo with above steps reproduced: https://github.com/davideasaf/nx-jest-bug

**Comment by jaysoo** [comment]
This should have been fixed in `jest-preset-angular`: https://github.com/thymikee/jest-preset-angular/pull/261
