### ISSUE TITLE
Generators migrations commands not working

### ISSUE THREAD

**Issue by RomainFallet** [nrwl/nx#17598]
### Documentation issue

- [ ] Reporting a typo
- [X] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

<https://nx.dev/deprecated/workspace-generators>

### Additional context or description

Following the steps does not work.

The command `nx g my-generator` returns an error:

```txt
 >  NX   Unable to resolve @nx/workspace:my-generator.

   Cannot find generator 'my-generator' in /home/.../node_modules/@nx/workspace/generators.json.
```

The right command is:

```bash
nx g @my-workspace/my-plugin:my-generator
```

**Comment by isaacplmann** [comment]
I just checked the command on Nx 16.3.2.  It works correctly.  Closing.  Feel free to reopen if there's something I'm missing.
