### ISSUE TITLE
CI Integrations (Azure and Jenkins)

### ISSUE THREAD

**Issue by vsavkin** [nrwl/nx#176]
Provide examples for different CI providers

Azure example: https://github.com/nrwl/nx-azure-build

**Comment by maku** [comment]
I am looking for an "idomatic" way to handle a nx project in gitlab CI / CD. Is there anything planned to provide this? Or can anybody give me an example?

**Comment by danieldanielecki** [comment]
Definitely waiting for this!

**Comment by saadshahd** [comment]
Hi @vsavkin any progress in this? Where could I contribute to add Jenkins X example?

**Comment by vsavkin** [comment]
We are in the process of making distributed CI setups more straightforward. It's wrapping up.

I'm about to publish an example of a Jenkins setup with multiple agent nodes. Should be done next week.

@isaacplmann is also working on a course that will cover CI. It should come out in the next month or so.

**Comment by johnhainline** [comment]
How's this going? Any updates?

**Comment by JoA-MoS** [comment]
I am currently trying to implement this in Jenkins so very interested in what you come up with. Currently I can't even get past `format:check` I get the error `fatal: Not a valid object name origin/develop`

```
+ npm run format:check -- --base=origin/develop



> @myscope/member-portal-webui@0.0.0-automated-do-not-use format:check /opt/appserver/jenkins/workspace/webui_feature_migrate-to-nx-repo

> nx format:check "--base=origin/develop"

fatal: Not a valid object name origin/develop
```

**Comment by lithqube** [comment]
> Sorry for the wait, folks.
> 
> We are in the process of making distributed CI setups more straightforward. It's wrapping up.
> 
> I'm about to publish an example of a Jenkins setup with multiple agent nodes. Should be done next week.
> 
> @isaacplmann is also working on a course that will cover CI. It should come out in the next month or so.

Any update on this one? I'm also really struggling with a good config with a couple of angular and a react  projects 😓

**Comment by vsavkin** [comment]
@mbriggs is working on it

**Comment by JoA-MoS** [comment]
@mbriggs - can I get a preview :-) is there a special way that you need to configure your Jenkins multi-branch pipeline so that the affected scripts will work? Do you have to do something so that it fetches all branches?

**Comment by hoang-innomizetech** [comment]
Is there any way I can use origin/master instead of master? The branch hasn't been pulled yet, so we need to use from origin (or remote)

**Comment by isaacplmann** [comment]
Here are example repos for Azure and Jenkins:

https://github.com/nrwl/nx-azure-build
https://github.com/nrwl/nx-jenkins-build

The readmes  from these repos will soon be included in the nx.dev docs.

**Comment by danieldanielecki** [comment]
Great job! GitLab would have been also really appreciated though.

**Comment by FrozenPandaz** [comment]
Closing this issue as we now have guides for Azure and Jenkins :tada:
