### ISSUE TITLE
create-nx-workspace fails with Exit code: 1

### ISSUE THREAD

**Issue by jerryhowe** [nrwl/nx#17609]
### Current Behavior

When creating a new NX-workspace (current latest NX version is 16.13.2) using `npx create-nx-workspace@latest [project-name]`  and following the prompts with the following selections:

Prompt 1: select `React`
Prompt 2: select `None`
Prompt 3: select `Standalone`
Prompt 4: select `Rspack`
Prompt 5: select `SASS(.scss)`
Prompt 6: select `No`

I will get the following error:
```sh
 >  NX   Failed to create a workspace.
Exit code: 1
 Log file: /var/folders/rq/ckv7m29d4knbtxlr7xgxffg40000gn/T/tmp-94932-0HiRLvczxjGx/error.log
```

And inside the aforementioned log file, I can see:
```sh
Fetching prettier...
Fetching @nx/rspack...

 >  NX   Cannot find module 'license-webpack-plugin'
```

My dev environment is:
Processor: Apple Silicon M1 Max
OS: OSX 13.4
Node v16.13.2
NPM 8.1.2

### Expected Behavior

The new NX project should be generated without any errors.

### Steps to Reproduce

run `npx create-nx-workspace@latest [project-name]`  and following the prompts with the following selections:

Prompt 1: select `React`
Prompt 2: select `None`
Prompt 3: select `Standalone`
Prompt 4: select `Rspack`
Prompt 5: select `SASS(.scss)`
Prompt 6: select `No`

### Nx Report

```shell
Node   : 16.13.2
   OS     : darwin arm64
   npm    : 8.1.2
   Hasher : Native
   
   nx (global)    : 16.2.2
   nx             : 16.3.2
   @nx/js         : 16.3.2
   @nx/jest       : 16.3.2
   @nx/linter     : 16.3.2
   @nx/workspace  : 16.3.2
   @nx/cypress    : 16.3.2
   @nx/devkit     : 16.3.2
   @nx/react      : 16.3.2
   @nrwl/tao      : 16.3.2
   @nx/web        : 16.3.2
```

### Failure Logs

```shell
>  NX  Generating @nx/workspace:preset

Fetching prettier...
Fetching @nx/rspack...

 >  NX   Cannot find module 'license-webpack-plugin'

   Require stack:
   - /private/var/folders/rq/ckv7m29d4knbtxlr7xgxffg40000gn/T/tmp-95009-iZwdiQfELrNU/node_modules/@nx/rspack/src/utils/with-nx.js
   - /private/var/folders/rq/ckv7m29d4knbtxlr7xgxffg40000gn/T/tmp-95009-iZwdiQfELrNU/node_modules/@nx/rspack/src/index.js
   - .../node_modules/@nx/devkit/src/utils/package-json.js
   - .../node_modules/@nx/devkit/src/generators/to-js.js
   - .../node_modules/@nx/devkit/public-api.js
   - .../node_modules/@nx/devkit/index.js
   - .../node_modules/@nx/workspace/src/generators/preset/preset.js
   - .../node_modules/nx/src/config/workspaces.js
   - .../node_modules/nx/src/config/configuration.js
   - .../node_modules/nx/src/utils/package-manager.js
   - .../node_modules/nx/bin/init-local.js
   - .../node_modules/nx/bin/nx.js
   Pass --verbose to see the stacktrace.


 >  NX   Workspace creation failed, see above.

   Pass --verbose to see the stacktrace.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
Thanks for reporting this issue. It looks like `@nx/rspack` is missing a dependency, so it is failing upon import. I'll publish a new rspack version today.

**Comment by jaysoo** [comment]
A new version of `@nx/rspack` has been published with the fix.
