### ISSUE TITLE
express app "serve" fails (in docker) when dependant on js lib built with tsc

### ISSUE THREAD

**Issue by donatcranburi** [nrwl/nx#17608]
### Current Behavior

I was attempting to move my dev environment into docker and setup a little alpine image that basically just installs node and runs `npx nx serve webserver`.

The server was crashing with an error `watch error: Daemon closed the connection`.

Bashed my head against google a bit, tried disabling the nx_dameon, clearing node_modules, nx resettin, etc, to no avail. Started a [repro repo](https://github.com/donatcranburi/nx-repro-docker-crash) and was able to get a minimal reproduction up. Seems like if I have an app built with @nx/express, that imports a lib built with @nx/js _and using tsc as the builder_, then I can reproduce the issue. 

If I instead use a lib generated for node, or js with _none_ selected as the builder, everything is fine.

Nothing I need resolved as I just moved my shared library to one without a build step, but figured I'd post it up since I had the reproduction lying around.

### Expected Behavior

I'd have expected the "express" app to be able to be served regardless of its dependency on a js lib built with a tsc build step.

### GitHub Repo

https://github.com/donatcranburi/nx-repro-docker-crash

### Steps to Reproduce

- clone repo
- run docker compose up
- note that server starts
- uncomment L6 at [./apps/test-nx-express/src/main.ts](https://github.com/donatcranburi/nx-repro-docker-crash/blob/main/apps/test-nx-express/src/main.ts#L6)
- note the server crashes

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.9.0
   OS     : linux x64
   yarn   : 1.22.19
   Hasher : Native
   
   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/express        : 16.3.2
   @nx/node           : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/webpack        : 16.3.2
   typescript         : 5.0.4
   ---------------------------------------
   Local workspace plugins:
   	 @test-nx-express/test-js-lib
```

### Failure Logs

```shell
test-nx-express  | 
test-nx-express  | > nx run test-nx-express:serve:development
test-nx-express  | 
test-nx-express  | Debugger listening on ws://localhost:9229/87a30f57-8a9a-4f85-a7b5-7ccd2be0c51b
test-nx-express  | For help, see: https://nodejs.org/en/docs/inspector
test-nx-express  | 
test-nx-express  | Listening at http://localhost:3333/api
test-nx-express  | 
test-nx-express  | >  NX  File change detected. Restarting...
test-nx-express  | 
test-nx-express  | Watch error: Daemon closed the connection
test-nx-express  | 
test-nx-express  |  
test-nx-express  | 
test-nx-express  |  >  NX   Running target serve for project test-nx-express failed
test-nx-express  | 
test-nx-express  |    Failed tasks:
test-nx-express  |    
test-nx-express  |    - test-nx-express:serve:development
test-nx-express  |    
test-nx-express  |    Hint: run the command with --verbose for more details.
test-nx-express  | 
test-nx-express exited with code 1
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by xendarboh** [comment]
Note: I experience this issue to be introduced somewhere between
nx `16.0.2` (works !) and nx `16.3.2` (! works).

**Comment by xendarboh** [comment]
update: made a number of changes including `nx migrate`, more cjs-->esm (back to esbuild from webpack), and still found this error: `Watch error: Daemon closed the connection`.

I was able to resolve it by removing a docker volume on the failing service. Unknown why something is watching, why watcher could not be disabled, or why it errors in the way it does.
