### ISSUE TITLE
Request for NX Library to Support NODE 18 Version 

### ISSUE THREAD

**Issue by sunilnalumachucb** [nrwl/nx#17619]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I want to have node 18 support for NX Library, when can we have a new version of NX that will provide node18 support?

## Motivation

Now all applications are migrating to node 18 and AWS SDK V3 also supports node 18, which will benefit many consumers to have NX library to support node 18 in there projects.

## Suggested Implementation

We need to update the NX library to have support for node 18 version.

## Alternate Implementations

It will benefit many consumers to easily switch there NX library to latest version of Node 18 support  and helps them to use AWS SDK V3 version.

**Comment by FrozenPandaz** [comment]
Nx does support Node 18. What exact issue are you seeing where it seems to not support Node 18?

**Comment by n4imLess** [comment]
I am using node 18 and don't see any issues either.  
But it would make sense to put it in the compatibility matrix if it is officially supported: https://nx.dev/packages/workspace/documents/nx-nodejs-typescript-version-matrix
