### ISSUE TITLE
@nrwl/react:library and @nrwl/react:appication generators update package versions in root package.json

### ISSUE THREAD

**Issue by sarahquigley** [nrwl/nx#17625]
### Current Behavior

We are using @nrwl/react:library and @nrwl/react:appication generators in our nx monorepo. When we run these generators, a bunch of package versions in our monorepo root `package.json` are updated unexpectedly. If kept, these changes break our project build. We tried adding `skipPackageJson` but this had no effect. 

This image shows an example of the changes we're seeing in `package.json`.
![Screenshot 2023-06-15 at 12 27 45 PM](https://github.com/nrwl/nx/assets/1569881/631afd43-eca1-4837-84ca-107a69959029)

### Expected Behavior

When running these generators, either:
- package versions in root `package.json` should not be changed.
OR
- there should be an option to suppress updates to package versions in root `package.json`

### Steps to Reproduce

1. Run @nrwl/react:library and @nrwl/react:appication generators and check `package.json`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 15.3.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.3.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : 15.3.0
   @nrwl/eslint-plugin-nx : 15.3.0
   @nrwl/expo : Not Found
   @nrwl/express : 15.3.0
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.3.0
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 15.3.0
   @nrwl/react : 15.3.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.3.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.3.0
   @nrwl/web : 15.3.0
   @nrwl/webpack : 15.3.0
   @nrwl/workspace : 15.3.0
   typescript : 4.9.5
   ---------------------------------------
   Local workspace plugins:
         @jane/tools/workspace
   ---------------------------------------
   Community plugins:
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
i think this is intended. pass in the flag --skipPackageJson=true [skipPackageJson](https://nx.dev/packages/react/generators/library#skippackagejson) when generating library and application, it will not update deps in package.json

**Comment by xiongemi** [comment]
closing this issue for now.
