### ISSUE TITLE
Allow enforcing a collection for generators

### ISSUE THREAD

**Issue by rlmestre** [nrwl/nx#17656]
- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Even though you can set a `defaultCollection` in `nx.json`, others can still be run by specifying them or selecting it in Nx console. 

## Motivation
We'd like to enforce our collection be used whenever possible. Our generators are created with specific constraints in mind that we want everyone to follow. If someone uses `nx g @nrwl/angular:lib my-lib` or selects `@nrwl/angular:lib` in Nx console, for instance,  it would work, but they are opting out of our customization. 

## Suggested Implementation
The `defaultCollection` option could be expanded to accept `string|object` with a configuration that considers this by throwing an error if used via command line and hiding or disabling the Nx console options.

## Alternate Implementations
None

**Comment by rlmestre** [comment]
I just realized `defaultCollection` is actually deprecated... Maybe another implementation can be considered, though I think `defaultCollection` should stay. I understand the CLI is now smart enough to show an interactive prompt for matching generators, but that's not desirable in many cases.

**Comment by prewk** [comment]
I can relate, I've gone from recommending this in our contributing docs:

`yarn nx g lib shared/util/foo --tags=type:util,scope:frontend`

To:

`yarn nx g @nx/angular:library foo --directory libs/shared/util --importPath="@acme/shared/util/foo" --tags=type:util,scope:frontend`

The new incantation is bit harder to remember by heart 😅
