### ISSUE TITLE
generatePackageJson creates incompatible package.json and package-lock.json in certain scenarios. 

### ISSUE THREAD

**Issue by jonapgar-groupby** [nrwl/nx#17653]
### Current Behavior

When using `generatePackageJson: true` in the webpack plugin, nested dependencies can be missing from generated package-lock.json, causing `npm ci` to fail. 

Consider the following package-lock.json

```json
    "node_modules/auth0": {
      "version": "3.4.0",
      "resolved": "https://registry.npmjs.org/auth0/-/auth0-3.4.0.tgz",
      "integrity": "sha512-qaRVZfykFhROZlKa6i/G7Tlo4Df6GXdtMdvO41XuJ2XlJ/AMUAxL0u/FJJyII/HWwosVtypD92nHB2gqRwIbYg==",
      "dependencies": {
        "axios": "^0.27.2",
        "form-data": "^3.0.1", // <==== requires an older version of form-data
        "jsonwebtoken": "^9.0.0",
        "jwks-rsa": "^3.0.1",
        "lru-memoizer": "^2.1.4",
        "rest-facade": "^1.16.3",
        "retry": "^0.13.1",
        "uuid": "^9.0.0"
      },
      "engines": {
        "node": ">=14"
      }
    },
    "node_modules/auth0/node_modules/axios": {
      "version": "0.27.2",
      "resolved": "https://registry.npmjs.org/axios/-/axios-0.27.2.tgz",
      "integrity": "sha512-t+yRIyySRTp/wua5xEr+z1q60QmLq8ABsS5O9Me1AsE5dfKqgnCFzwiCZZ/cGNd1lq4/7akDWMxdhVlucjmnOQ==",
      "dependencies": {
        "follow-redirects": "^1.14.9",
        "form-data": "^4.0.0" <=== but this one requires a newer one
      }
    },
    
    //---------------- the below entry is missing (pruned) when using generatePackageJson, but will be added if you run `npm install` manually in the build folder
    
    "node_modules/auth0/node_modules/axios/node_modules/form-data": {
      "version": "4.0.0",
      "resolved": "https://registry.npmjs.org/form-data/-/form-data-4.0.0.tgz",
      "integrity": "sha512-ETEklSGi5t0QMZuiXoA/Q6vcnxcLQP5vdugSpuAyi6SVGi2clPPp+xgEhuMaHC+zGgn31Kd235W35f7Hykkaww==",
      "dependencies": {
        "asynckit": "^0.4.0",
        "combined-stream": "^1.0.8",
        "mime-types": "^2.1.12"
      },
      "engines": {
        "node": ">= 6"
      }
    },
    // ---------------------------------------------------------------------------------------------------
    
    "node_modules/auth0/node_modules/form-data": {
      "version": "3.0.1",
      "resolved": "https://registry.npmjs.org/form-data/-/form-data-3.0.1.tgz",
      "integrity": "sha512-RHkBKtLWUVwd7SqRIvCZMEvAMoGUp0XU+seQiZejj0COz3RI3hWP4sCv3gZWWLjJTd7rGwcsF5eKZGii0r/hbg==",
      "dependencies": {
        "asynckit": "^0.4.0",
        "combined-stream": "^1.0.8",
        "mime-types": "^2.1.12"
      },
      "engines": {
        "node": ">= 6"
      }
    },
    // ------------------------------------- Note that form-data@4.0.0 is here, but it should also be in 
    // "node_modules/auth0/node_modules/axios/node_modules/form-data" as well
     "node_modules/form-data": {
      "version": "4.0.0",
      "resolved": "https://registry.npmjs.org/form-data/-/form-data-4.0.0.tgz",
      "integrity": "sha512-ETEklSGi5t0QMZuiXoA/Q6vcnxcLQP5vdugSpuAyi6SVGi2clPPp+xgEhuMaHC+zGgn31Kd235W35f7Hykkaww==",
      "dependencies": {
        "asynckit": "^0.4.0",
        "combined-stream": "^1.0.8",
        "mime-types": "^2.1.12"
      },
      "engines": {
        "node": ">= 6"
      }
    },
     "node_modules/openai": {
      "version": "3.2.1",
      "resolved": "https://registry.npmjs.org/openai/-/openai-3.2.1.tgz",
      "integrity": "sha512-762C9BNlJPbjjlWZi4WYK9iM2tAVAv0uUp1UmI34vb0CN5T2mjB/qM6RYBmNKMh/dN9fC+bxqPwWJZUTWW052A==",
      "dependencies": {
        "axios": "^0.26.0",
        "form-data": "^4.0.0" // <======== is responsible for the node_modules/form-data@4.0.0 install...
      }
    },
```

The missing package results in the following error when running `npm ci` (i.e. in a Dockerfile)

```
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Missing: form-data@4.0.0 from lock file
npm ERR! 
npm ERR! Clean install a project
```

### Expected Behavior

Generated package-lock.json is valid and `npm ci` succeeds.

### Steps to Reproduce

1. Create an nx project with an app/lib that has a imports dependencies that create two copies of the same version of the same package.  For example, `auth0` and `openai`, which both ultimately import `form-data@4.0.0` but will do so in different folders in node_modules, due to auth0 having a direct dependency on an earlier version of form-data.

### Nx Report

```shell
Node   : 18.15.0
   OS     : linux arm64
   npm    : 9.5.0
   Hasher : Native
   
   nx (global)        : 16.2.2
   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/nest           : 16.3.2
   @nx/node           : 16.3.2
   @nx/plugin         : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/webpack        : 16.3.2
   typescript         : 5.0.4
   ---------------------------------------
```

### Failure Logs

```shell
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Missing: form-data@4.0.0 from lock file
npm ERR! 
npm ERR! Clean install a project
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The root package-lock.json for the project is not missing the dependency.

Also, 

Because these have the same version, perhaps one is pruned by this code:

https://github.com/nrwl/nx/blob/0848031dd9c19672ab795e0494e54bbef61240c5/packages/nx/src/plugins/js/lock-file/project-graph-pruning.ts#L52-L57

**Comment by MarcusElevait** [comment]
I came across the same issue with the `@nrwl/webpack:webpack` executor. Also setting `includeDevDependenciesInPackageJson` to false doesn't help.

**Comment by fedenusy** [comment]
This issue prevents me from upgrading from 1.x to 2.x

**Comment by icastillejogomez** [comment]
Same here 🥲

**Comment by Markus-Ende** [comment]
Same issue, my setup:

```
Node   : 18.18.2
   OS     : linux-x64
   npm    : 10.2.4
   
   nx (global)        : 17.0.3
   nx                 : 17.0.3
   @nx/js             : 17.0.3
   @nx/jest           : 17.0.3
   @nx/linter         : 17.0.3
   @nx/eslint         : 17.0.3
   @nx/workspace      : 17.0.3
   @nx/angular        : 17.0.3
   @nx/cypress        : 17.0.3
   @nx/devkit         : 17.0.3
   @nx/eslint-plugin  : 17.0.3
   @nx/nest           : 17.0.3
   @nx/node           : 17.0.3
   @nx/plugin         : 17.0.3
   @nx/storybook      : 17.0.3
   @nrwl/tao          : 17.0.3
   @nx/web            : 17.0.3
   @nx/webpack        : 17.0.3
   typescript         : 5.1.6
```

**Comment by roryf** [comment]
Encountered this issue only after upgrading `typeorm` from `0.3.17` to `0.3.19`. Really struggling to [see what changed](https://github.com/typeorm/typeorm/compare/0.3.17...0.3.19) in typeorm to cause this.

```
   Node   : 18.17.1
   OS     : darwin-arm64
   npm    : 9.6.7
   
   nx (global)        : 17.0.3
   nx                 : 17.0.3
   @nx/js             : 17.0.3
   @nx/jest           : 17.0.3
   @nx/linter         : 17.0.3
   @nx/eslint         : 17.0.3
   @nx/workspace      : 17.0.3
   @nx/cypress        : 17.0.3
   @nx/devkit         : 17.0.3
   @nx/esbuild        : 17.0.3
   @nx/eslint-plugin  : 17.0.3
   @nx/nest           : 17.0.3
   @nx/next           : 17.0.3
   @nx/node           : 17.0.3
   @nx/react          : 17.0.3
   @nx/storybook      : 17.0.3
   @nrwl/tao          : 17.0.3
   @nx/vite           : 17.0.3
   @nx/web            : 17.0.3
   @nx/webpack        : 17.0.3
   typescript         : 5.3.2
```

**Comment by roryf** [comment]
After a slightly painful `nx migrate`, issue remains. Error seems to be

```
npm ERR! Missing: string-width-cjs@4.2.3 from lock file
npm ERR! Missing: strip-ansi-cjs@6.0.1 from lock file
npm ERR! Missing: wrap-ansi-cjs@7.0.0 from lock file
```

The relevant lines from `typeorm` diff seem to be here, I won't pretend to know what caused these or what it actually means

```
12064 - "node_modules/string-width": {
12971 + "node_modules/string-width-cjs": {
12972 +      "name": "string-width",
12973        "version": "4.2.3",
```

It's amazing the amount of harm one individual can do to an ecosystem just because of their ego and idea of "technical correctness" 😢

**Comment by saez0pub** [comment]
Hello,

I have also a problem with the pruned lock missing some versions of a dependency.
I'm wondering what is the benefit of pruning this lockfile ? a pruned package.json isn't sufficient for reducing the size of the node_modules ?
I'm currently patching it with a copy or the lockfile in the workspace root after the build or before using npm ci.
Am I missing something ?

Thank you.

**Comment by kdawgwilk** [comment]
I have been digging into this issue quite a bit and even have a failing test written for it.  It appears that when the pruning process sees a aliased package it treats it as a duplicate and removes it?  @meeroslav Any thoughts?  You can repro this pretty easily from the `__fixtures__/mixed-keys/package.json` by creating a lock file with `npm i` and then attempting to prune that generated lock file and a bunch of the deps are stripped away

**Comment by SirPhemmiey** [comment]
any heads on on this with `yarn`? I'm still having this issue with `generatePackageJson` set as `true` 😢

**Comment by CyanoFresh** [comment]
same issue

**Comment by pbintcha** [comment]
> After a slightly painful `nx migrate`, issue remains. Error seems to be
> 
> ```
> npm ERR! Missing: string-width-cjs@4.2.3 from lock file
> npm ERR! Missing: strip-ansi-cjs@6.0.1 from lock file
> npm ERR! Missing: wrap-ansi-cjs@7.0.0 from lock file
> ```
> 
> The relevant lines from `typeorm` diff seem to be here, I won't pretend to know what caused these or what it actually means
> 
> ```
> 12064 - "node_modules/string-width": {
> 12971 + "node_modules/string-width-cjs": {
> 12972 +      "name": "string-width",
> 12973        "version": "4.2.3",
> ```
> 
> It's amazing the amount of harm one individual can do to an ecosystem just because of their ego and idea of "technical correctness" 😢

May be related to https://github.com/isaacs/jackspeak/issues/5

The workaround i have found was to downgrade  @fastify/static package to v6 instead of v7
You can use command `npm ls @isaacs/cliui` to find which package depends on this lib.

**Comment by Avivbens** [comment]
Hi team 👋 

Same issue in here, see this:


## Trying to `npm ci` over the generated package:
![CleanShot 2024-04-11 at 12 14 24@2x](https://github.com/nrwl/nx/assets/77183871/56b75a8c-ab25-486e-a23a-1d2b27c24751)



## Different with the original `package.json`

![CleanShot 2024-04-11 at 12 13 23](https://github.com/nrwl/nx/assets/77183871/9f4faf6b-e657-4ed7-8724-79c4d5368346)


## Configuration

![CleanShot 2024-04-11 at 12 44 21](https://github.com/nrwl/nx/assets/77183871/df7d3ca4-c4d6-4db4-9aa3-3232f8064d5a)


## Summary
The `esbuild` coping the lock file, but filters just needed deps for package.json.
Result - lock file is out of sync.

**Comment by Avivbens** [comment]
## Temp solution

As a walkaround, currently added this `build` target to force sync the lock file:

![CleanShot 2024-04-11 at 13 25 02](https://github.com/nrwl/nx/assets/77183871/01f0ea92-20f9-45a2-8a62-40dde5e9eb55)

**Comment by ImTemporaryHere** [comment]
same here

**Comment by leosvelperez** [comment]
Hey all! 👋🏻 

A few fixes have been released in recent Nx versions (the last one landing on Nx 19.3.0). Could you please update to the latest version and try again?

If you still have issues after updating, please provide a reproduction so we can have a look. It's hard to troubleshoot these issues without a proper reproduction.

**Comment by Avivbens** [comment]
> Hey all! 👋🏻
> 
> A few fixes have been released in recent Nx versions (the last one landing on Nx 19.3.0). Could you please update to the latest version and try again?
> 
> If you still have issues after updating, please provide a reproduction so we can have a look. It's hard to troubleshoot these issues without a proper reproduction.

Well, I've got the following error while trying to bump up all `Nx` dependencies (seems like the `postinstall` script for `Nx` failing to do some OS things):

```shell
npm i nx@latest @nx/esbuild@latest @nx/eslint@latest @nx/eslint-plugin@latest @nx/express@latest @nx/jest@latest @nx/js@latest @nx/node@latest @nx/workspace@latest
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @vendor-to-engagement-pipeline/source@0.0.1
npm WARN Found: nx@18.0.8
npm WARN node_modules/nx
npm WARN   nx@"18.0.8" from @nrwl/tao@18.0.8
npm WARN   node_modules/@nrwl/tao
npm WARN     @nrwl/tao@"18.0.8" from nx@18.0.8
npm WARN   2 more (@nx/devkit, the root project)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer nx@">= 16 <= 18" from @nx/devkit@18.2.4
npm WARN node_modules/@nx/devkit
npm WARN   @nx/devkit@"18.2.4" from @nrwl/devkit@18.2.4
npm WARN   node_modules/@nrwl/devkit
npm WARN   1 more (@zie/nx-sonar)
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@vendor-to-engagement-pipeline/source@0.0.1',
npm WARN EBADENGINE   required: { node: '20.11.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.1', npm: '10.2.4' }
npm WARN EBADENGINE }
npm ERR! code 1
npm ERR! path /Users/******/<REPO_LOCATION>/node_modules/nx
npm ERR! command failed
npm ERR! command sh -c node ./bin/post-install
npm ERR! /Users/******/<REPO_LOCATION>/node_modules/nx/src/native/native-bindings.js:244
npm ERR!     throw loadError
npm ERR!     ^
npm ERR!
npm ERR! Error: dlopen(/private/var/folders/rw/z_n8j7kd5_18t2bdrx7s65vw0000gq/T/nx-native-file-cache-84f6168/19.3.0-nx.darwin-arm64.node, 0x0001): tried: '/private/var/folders/rw/z_n8j7kd5_18t2bdrx7s65vw0000gq/T/nx-native-file-cache-84f6168/19.3.0-nx.darwin-arm64.node' (code signature invalid in <3024199E-150A-31E2-8827-BAE84FBD48CF> '/private/var/folders/rw/z_n8j7kd5_18t2bdrx7s65vw0000gq/T/nx-native-file-cache-84f6168/19.3.0-nx.darwin-arm64.node' (errno=85) sliceOffset=0x00000000, codeBlobOffset=0x0057F860, codeBlobSize=0x0000B078), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/rw/z_n8j7kd5_18t2bdrx7s65vw0000gq/T/nx-native-file-cache-84f6168/19.3.0-nx.darwin-arm64.node' (no such file), '/private/var/folders/rw/z_n8j7kd5_18t2bdrx7s65vw0000gq/T/nx-native-file-cache-84f6168/19.3.0-nx.darwin-arm64.node' (code signature invalid in <3024199E-150A-31E2-8827-BAE84FBD48CF> '/private/var/folders/rw/z_n8j7kd5_18t2bdrx7s65vw0000gq/T/nx-native-file-cache-84f6168/19.3.0-nx.darwin-arm64.node' (errno=85) sliceOffset=0x00000000, codeBlobOffset=0x0057F860, codeBlobSize=0x0000B078)
npm ERR!     at Module._extensions..node (node:internal/modules/cjs/loader:1452:18)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1197:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:1013:12)
npm ERR!     at Module._load (/Users/******/<REPO_LOCATION>/node_modules/nx/src/native/index.js:60:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1225:19)
npm ERR!     at require (node:internal/modules/helpers:177:18)
npm ERR!     at Object.<anonymous> (/Users/******/<REPO_LOCATION>/node_modules/nx/src/native/native-bindings.js:135:29)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1356:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1197:32) {
npm ERR!   code: 'ERR_DLOPEN_FAILED'
npm ERR! }
npm ERR!
npm ERR! Node.js v18.19.1

npm ERR! A complete log of this run can be found in: /Users/******/.npm/_logs/2024-06-14T10_49_00_593Z-debug-0.log
```

**Comment by Avivbens** [comment]
The file `/private/var/folders/rw/z_n8j7kd5_18t2bdrx7s65vw0000gq/T/nx-native-file-cache-84f6168/19.3.0-nx.darwin-arm64.node` does exists:

![CleanShot 2024-06-14 at 13 54 19@2x](https://github.com/nrwl/nx/assets/77183871/21683846-9099-437f-9e4e-85320d6f66f4)

**Comment by Avivbens** [comment]
> Hey all! 👋🏻
> 
> A few fixes have been released in recent Nx versions (the last one landing on Nx 19.3.0). Could you please update to the latest version and try again?
> 
> If you still have issues after updating, please provide a reproduction so we can have a look. It's hard to troubleshoot these issues without a proper reproduction.

### Still having this issue

```shell
> npm ci

npm ERR! code EUSAGE
npm ERR!
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR!
npm ERR! Missing: @grpc/proto-loader@0.7.13 from lock file
npm ERR! Missing: long@5.2.3 from lock file
npm ERR! Missing: protobufjs@7.3.2 from lock file
npm ERR! Missing: yargs@17.7.2 from lock file
npm ERR! Missing: cliui@8.0.1 from lock file
npm ERR! Missing: yargs-parser@21.1.1 from lock file
npm ERR!
npm ERR! Clean install a project
npm ERR!
npm ERR! Usage:
npm ERR! npm ci
npm ERR!
npm ERR! Options:
npm ERR! [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
npm ERR! [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
npm ERR! [--include <prod|dev|optional|peer> [--include <prod|dev|optional|peer> ...]]
npm ERR! [--strict-peer-deps] [--foreground-scripts] [--ignore-scripts] [--no-audit]
npm ERR! [--no-bin-links] [--no-fund] [--dry-run]
npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
npm ERR!
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR!
npm ERR! Run "npm help ci" for more info

npm ERR! A complete log of this run can be found in: /Users/aviv.benshahar/.npm/_logs/2024-06-14T11_24_52_514Z-debug-0.log
```

**Comment by Avivbens** [comment]
### `Nx` Dependencies

```tree
npm ls
├── @nx/esbuild@19.3.0
├── @nx/eslint-plugin@19.3.0
├── @nx/eslint@19.3.0
├── @nx/express@19.3.0
├── @nx/jest@19.3.0
├── @nx/js@19.3.0
├── @nx/node@19.3.0
├── @nx/workspace@19.3.0
├── @zie/nx-sonar@1.0.5
├── nx@19.3.0
```

**Comment by leosvelperez** [comment]
I see. Unfortunately, we'll need more information to reproduce the issue. These issues are very difficult to reproduce with only the failure logs and the `nx report` output. We've unsuccessfully tried to do so. Could you please provide a repo we can use to reproduce it and troubleshoot it?

Thanks for the patience!

**Comment by Avivbens** [comment]
> I see. Unfortunately, we'll need more information to reproduce the issue. These issues are very difficult to reproduce with only the failure logs and the `nx report` output. We've unsuccessfully tried to do so. Could you please provide a repo we can use to reproduce it and troubleshoot it?
> 
> Thanks for the patience!

### Cannot create such a repo

I'd be more than happy to help, but seems like we cannot create a public repo that has the issue. 
I've tried, but seems like all of the problematic packages I've posted above related to internal dependencies (for now - of my company). 

I can help you debug that on a Zoom call, if you'd like to 🥷

A quick guess - the `Nx` engine looking into public repos dependencies, instead of getting all dependencies tree from the `npm ls` command (?)
