### ISSUE TITLE
Nx16 - Angular 16 not updated to the latest with warning (npm)

### ISSUE THREAD

**Issue by kwood-gmr** [nrwl/nx#17652]
### Current Behavior

After attempting to upgrade angular to the latest (16.1.0) "npm install" reports peer dependency issues.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @xxx/source@0.0.0
npm ERR! Found: @angular-devkit/build-angular@16.0.6
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"~16.1.0" from the root project
npm ERR!   peer @angular-devkit/build-angular@">= 14.0.0 < 17.0.0" from @nx/angular@16.3.2
npm ERR!   node_modules/@nx/angular
npm ERR!     @nx/angular@"16.3.2" from the root project
npm ERR!     @nx/angular@"16.3.2" from @nrwl/angular@16.3.2
npm ERR!     node_modules/@nrwl/angular
npm ERR!       @nrwl/angular@"16.3.2" from @nx/angular@16.3.2
npm ERR!   1 more (jest-preset-angular)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"~16.1.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/compiler-cli@16.1.1
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   peer @angular/compiler-cli@"^16.1.0" from @angular-devkit/build-angular@16.1.0
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~16.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\kswood\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     ...\AppData\Local\npm-cache\_logs\2023-06-16T19_39_19_351Z-debug-0.log

### Expected Behavior

upgrade and install libraries without error

### Steps to Reproduce

1. start with Angular 16.0.0 application in NX Workspace
2. upgrade to 16.1.0
3. run "npm install"
4. observe error

### Nx Report

```shell
Node   : 18.16.0
   OS     : win32 x64
   npm    : 8.6.0
   Hasher : Native

   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/angular        : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/web            : 16.3.2
   @nx/webpack        : 16.3.2
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @ngrx/effects            : 16.0.1
   @ngrx/entity             : 16.0.1
   @ngrx/router-store       : 16.0.1
   @ngrx/store              : 16.0.1
   @ngrx/store-devtools     : 16.0.1
   angular-auth-oidc-client : 15.0.5
```

### Failure Logs

```shell
118 error While resolving: [1m@portal/source[22m@[1m0.0.0[22m
118 error Found: [1m@angular-devkit/build-angular[22m@[1m16.0.6[22m[2m[22m
118 error [2mnode_modules/@angular-devkit/build-angular[22m
118 error   [33mdev[39m [1m@angular-devkit/build-angular[22m@"[1m~16.1.0[22m" from the root project
118 error   [35mpeer[39m [1m@angular-devkit/build-angular[22m@"[1m>= 14.0.0 < 17.0.0[22m" from [1m@nx/angular[22m@[1m16.3.2[22m[2m[22m
118 error   [2mnode_modules/@nx/angular[22m
118 error     [1m@nx/angular[22m@"[1m16.3.2[22m" from the root project
118 error     [1m@nx/angular[22m@"[1m16.3.2[22m" from [1m@nrwl/angular[22m@[1m16.3.2[22m[2m[22m
118 error     [2mnode_modules/@nrwl/angular[22m
118 error       [1m@nrwl/angular[22m@"[1m16.3.2[22m" from [1m@nx/angular[22m@[1m16.3.2[22m
118 error   1 more (jest-preset-angular)
118 error
118 error Could not resolve dependency:
118 error [33mdev[39m [1m@angular-devkit/build-angular[22m@"[1m~16.1.0[22m" from the root project
118 error
118 error Conflicting peer dependency: [1m@angular/compiler-cli[22m@[1m16.1.1[22m[2m[22m
118 error [2mnode_modules/@angular/compiler-cli[22m
118 error   [35mpeer[39m [1m@angular/compiler-cli[22m@"[1m^16.1.0[22m" from [1m@angular-devkit/build-angular[22m@[1m16.1.0[22m[2m[22m
118 error   [2mnode_modules/@angular-devkit/build-angular[22m
118 error     [33mdev[39m [1m@angular-devkit/build-angular[22m@"[1m~16.1.0[22m" from the root project
118 error
118 error Fix the upstream dependency conflict, or retry
118 error this command with --force, or --legacy-peer-deps
118 error to accept an incorrect (and potentially broken) dependency resolution.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
We will be adding angular 16.1 support here: #17155.

There are still a few outstanding incompatibilities with some 3rd party plugins at the moment. We will have a version as soon as possible.
