### ISSUE TITLE
NestJS failed during "nx serve <APP>" when import nx/js lib

### ISSUE THREAD

**Issue by gevagt10** [nrwl/nx#17654]
### Current Behavior

Failed during running `nx serve my-nest-app`

### Expected Behavior

print `data-access` to console

### Steps to Reproduce

1. Create  integrated app:
2. npx create-nx-workspace@latest myorg --preset=ts
3. Create simple lib:
4. `npx nx generate @nx/js:library data-access --publishable --importPath @myorg/data-access`
5. Create nestjs app:
6. nx g @nx/nest:app my-nest-app
7. In `main.ts` just print(console.log) the function from `data-access` (create automaticly)
8. `nx serve my-nest-app` - failed

### Nx Report

```shell
C:\Users\gevag\OneDrive\Desktop\User\test\myorg>nx report                                                                                 
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : win32 x64
   npm    : 9.6.7
   Hasher : Node

   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/nest           : 16.3.2
   @nx/node           : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/webpack        : 16.3.2
   typescript         : 5.0.4
   ---------------------------------------
   Local workspace plugins:
         @myorg/data-access
```

### Failure Logs

```shell
C:\Users\gevag\OneDrive\Desktop\User\test\myorg>nx serve myorg

> nx run myorg:serve:development

Watch error: Daemon closed the connection

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Running target serve for project my-nest-app failed

   Failed tasks:

   - myorg:serve:development

   Hint: run the command with --verbose for more details.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

It's basically just to **share** a data-access library with a number of apps
NestJS App:
`import {Logger} from '@nestjs/common';
import {NestFactory} from '@nestjs/core';

import {AppModule} from './app/app.module';
import {dataAccess} from "@myorg/data-access";

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const globalPrefix = 'api';
  app.setGlobalPrefix(globalPrefix);
  const port = process.env.PORT || 3000;
  await app.listen(port);
  console.log(dataAccess)
  Logger.log(
    🚀 Application is running on: http://localhost:${port}/${globalPrefix}
  );
}
bootstrap();`

----------------------
Data access lib:
`export function dataAccess(): string {
  return 'data-access';
}`
And index file that route to this file

**Comment by mikhin** [comment]
try `nx reset`
