### ISSUE TITLE
Cannot find module '@nx/react/package.json'

### ISSUE THREAD

**Issue by lmkerr** [nrwl/nx#17651]
### Current Behavior

In a fresh Nx repo (Nx 16.3.2), using the following command to generate a react app using vite with pnpm on mac OS-X:

`nx g @nx/react:app my-app --bundler=vite`

Returns the following error:

`Cannot find module '@nx/react/package.json'`

I've tried deleting `node_modules` and the `pnpm-lock.yaml` file, while using `npx` instead of the global installation, same result.

### Expected Behavior

I should be able to successfully create a React app that uses Vite as a bundler with TypeScript using pnpm.

### Steps to Reproduce

1. Generate new Integrated MonoRepo with npx: `npx create-nx-workspace@latest myorg --preset=ts`
2. Generate react app with vite: `npx nx g @nx/react:application my-app`

### Nx Report

```shell
Node   : 18.15.0
   OS     : darwin x64
   pnpm   : 8.4.0
   Hasher : Native

   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/vite           : 16.3.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.2
   ---------------------------------------
   Local workspace plugins:
   	 @dex/helpers
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
You forgot to install `@nx/react`. You must install `@nx/react` before you are able to generate an application with it. 

Though I agree the error message could be better. Would someone be open to exposing a nicer error here?
