### ISSUE TITLE
nx graph command doesn't show relationships anymore

### ISSUE THREAD

**Issue by urielzen** [nrwl/nx#17664]
### Current Behavior

When running `nx graph`, the graphs shows like this:

![image](https://github.com/nrwl/nx/assets/7947179/0c5b5ba5-1b2c-4a01-ba91-107cc62ca911)
 

### Expected Behavior

It used to show lines between projects and libraries to show the dependencies between them.

### Steps to Reproduce

run `nx graph`

### Nx Report

```shell
Node   : 16.16.0
OS     : win32 x64
npm    : 8.11.0
Hasher : Native
   
   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/angular        : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/webpack        : 16.3.2
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.13.0
   @ngrx/component-store            : 16.0.1
   @ngrx/store                      : 16.0.1
   ---------------------------------------
   Local workspace plugins:
         @l-f/feature/card-progress-spinner
         @l-f/feature/terms-and-conditions
         @l-f/feature/confirmation-modal
         @l-f/feature/form-validators
         @l-f/feature/button-wrapper
         @l-f/feature/global-loading
         @l-f/feature/social-button
         @l-f/feature/card-title
         @l-f/feature/form-error
         @l-f/feature/footer
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

This used to work for us some versions back (14 maybe), but after migrate to 15 and now 16. The issues is still there.

Thanks.

**Comment by mandarini** [comment]
Hi there @urielzen ! Can you please share a simple reproduction repository?

**Comment by urielzen** [comment]
I was in the process of creating the sample repo.

I copied (including node modules folder) from my original folder to another folder where I could manipulate it and trim down the files in order to upload a manageable project size.

After copying finalized I ran `nx graph` in the new folder and it worked?! how?

This is from the new copy.
![image](https://github.com/nrwl/nx/assets/7947179/a5731d97-0a02-4e55-bd97-d31eabf52ef0)

The original still shows no relationships
![image](https://github.com/nrwl/nx/assets/7947179/196879db-8883-4469-b025-a8a15a00edc0)

I am not sure I will be able to create a repo with the problem.

**Comment by harikasin** [comment]
I have the same problem. Before upgrading to angular 16 it showed me the joints correctly and now it doesn't show me any.

**Comment by urielzen** [comment]
@mandarini I think I was able to reproduce the issue in the repo below, even after copying it to different folder. Hopefully you are also able to see the issue on your end. Thanks so much for looking into this.

https://github.com/urielzen/nxgraphissue

**Comment by urielzen** [comment]
@mandarini  I was able to fix the issue in my app by manually changing the paths in the `tsconfig.base.json` file, then fixing all the references to the new paths names and rebuilding the app. Then after undoing all these changes and putting it back as they were and rebuilding again. Now the graph shows the dependencies correctly. Hope this helps in some way.

![image](https://github.com/nrwl/nx/assets/7947179/48cd1396-a4d4-4138-998e-3d9c1d6a2a71)

**Comment by mandarini** [comment]
Ohhh thanks @urielzen ! Good to know! I was going to look at this during this week but glad you found the issue!

**Comment by urielzen** [comment]
@mandarini Unfortunately this issue keeps coming randomly from time to time. I tried following your recommendation of deleting the node modules folder and do a fresh install, but that didn't help.

The only work around seems to be doing the hack I mentioned above by changing all the paths names, and then reverting the change.
