### ISSUE TITLE
Dynamic module federation remote with similar name in different projects throws same error

### ISSUE THREAD

**Issue by st-clair-clarke** [nrwl/nx#17696]
### Current Behavior

I have an original nx dyanamic module federation project medsoft, at ~/workspace/nx/mf/mds/medsoft. I started to get the following error when running the app with

``` nx serve medsoft --devRemotes=registration```

```ERROR Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203```

I examined the project in detail and corrected all inject() functions, but the error still persists.

I then created a new project with the same name ie medsoft at ~/workspace/nx/mf/med-soft/medsoft.

The projects are both created with the identical commands:
1. create an empty workspace
```pnpm dlx create-nx-workspace@latest med-soft --preset=empty --pm=pnpm''
2. create the dynamic host
``` nx g @nx/angular:host medsoft --dynamic --standalone --standaloneConfig --no-interactive```

3. create the remote
nx g @nx/angular:remote registration --host medsoft --standalone --standaloneConfig --no-interactive   



### Expected Behavior

The project builds and the host opens as expected.

However, clicking the 'Registration' link for the remote always generates the error above.

### GitHub Repo

https://github.com/st-clair-clarke/med-soft.git

### Steps to Reproduce

The projects are both created with the identical commands:
1. create an empty workspace
```pnpm dlx create-nx-workspace@latest med-soft --preset=empty --pm=pnpm''
2. create the dynamic host
``` nx g @nx/angular:host medsoft --dynamic --standalone --standaloneConfig --no-interactive```

3. create the remote
nx g @nx/angular:remote registration --host medsoft --standalone --standaloneConfig --no-interactive   


### Nx Report

```shell
NX   Report 

   Node   : 20.3.0
   OS     : linux x64
   pnpm   : 8.6.1
   Hasher : Native
   
   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/angular        : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/web            : 16.3.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.2
```

### Failure Logs

```shell
default-node_modules_pnpm_angular_core_16_1_1_rxjs_7_8_1_zone_js_0_13_1_node_modules_angular_-e25049.js:1 ERROR Error: Uncaught (in promise): Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (core.mjs:644:15)
    at ɵɵinject (core.mjs:655:60)
    at Object.factory (core.mjs:21758:46)
    at R3Injector.hydrate (core.mjs:9290:35)
    at R3Injector.get (core.mjs:9178:33)
    at definition.getStandaloneInjector (core.mjs:21773:31)
    at ComponentFactory.create (core.mjs:13028:57)
    at ViewContainerRef.createComponent (core.mjs:23333:47)
    at RouterOutlet.activateWith (router.mjs:2474:35)
    at ActivateRoutes.activateRoutes (router.mjs:3030:40)
    at resolvePromise (zone.js:1193:31)
    at resolvePromise (zone.js:1147:17)
    at zone.js:1260:17
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:25948:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:25948:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (core.mjs:26249:33)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:173:47)
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information
My instructions came from [Advanced Angular Micro Frontends with Dynamic Module Federation](https://nx.dev/recipes/module-federation/dynamic-module-federation-with-angular)
_No response_

**Comment by st-clair-clarke** [comment]
The bug lies either in @angular/* version greater than 16.0.3 or @nx/* version greater than 16.2.2. I went back to my git and saw that the problem actually started after those upgrades. I create new app with different versions downgrading from current versions to the above versions when the problem no longer occurred.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Angular 16.1 is still not supported by Nx. You must have updated it manually since Nx generators and migrations will only set it to 16.x.x. Please note that Angular 16.1 will be supported in Nx 16.4.0 which should be released soon.

I'm closing this since this issue was fixed by https://github.com/nrwl/nx/pull/17155 where we added that support. Please, keep an eye on the releases to migrate to the latest version.
