### ISSUE TITLE
nx seems to be failed to start

### ISSUE THREAD

**Issue by harasai** [nrwl/nx#17695]
### Current Behavior

When yarn install command executed on Jenkins CI, getting hung at building fresh packages.
I can see the node process  ./bin/compute-project-graph"
I could not see the nx daemon logs . All I can see is the node_modules/.cache/nx/nxdeps.json

Node: 18.16.0
nx: 14.3.6
yarn : 1.22.5
OS: MacOS BigSur 12.6.6,  Ventura 13.4

It is happening randomly and did cleared  yarn cache multiple times.

### Expected Behavior

yarn install should be succeeded.

### Nx Report

```shell

```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

with Node16 i don't see any issues,

**Comment by AgentEnder** [comment]
Can you run `nx report` and fill in the section above?
