### ISSUE TITLE
nx module boundries errors on @angular/router

### ISSUE THREAD

**Issue by ryanbas21** [nrwl/nx#17709]
### Current Behavior

Projects should use relative imports to import from other files within the same project. Use "./path/to/file" instead of import from "@angular/router"eslint@nx/enforce-module-boundaries

### Expected Behavior

@angular/router shouldn't be triggered by nx module boundries, i end up adding it to the allow list.

### GitHub Repo

dont have one right now

### Steps to Reproduce

unsure really, its popped up inconsistently here and there

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.12.1
   OS     : darwin x64
   npm    : 8.19.2
   Hasher : Native
   
   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nrwl/js           : 15.8.9
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nrwl/linter       : 15.8.9
   @nx/workspace      : 16.3.2
   @nrwl/workspace    : 15.8.9
   @nx/angular        : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nrwl/devkit       : 15.8.5
   @nx/esbuild        : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/express        : 16.3.2
   @nx/node           : 16.3.2
   @nx/react          : 16.3.2
   @nx/rollup         : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/vite           : 16.3.2
   @nx/web            : 16.3.2
   @nx/webpack        : 16.3.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @enio.ai/typedoc      : 1.0.8
   @mands/nx-playwright  : 0.6.2
   @nx-extend/e2e-runner : 2.3.2
   @nx-extend/playwright : 1.2.1
   ---------------------------------------
   Local workspace plugins:
   	 token-vault-suites
   	 embedded-login
   	 autoscript-suites
   	 @forgerock/token-vault-proxy
   	 central-login
   	 @forgerock/token-vault
   	 @plugins/wait-for-api
   	 angular-todo
   	 reactjs-todo
   	 autoscript-apps
   	 @forgerock/token-vault-app
   	 todo-api
   	 @shared/network
   	 @shared/workers
   	 mock-api
   	 @shared/types
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/js@15.8.9
     - @nrwl/linter@15.8.9
     - @nrwl/workspace@15.8.9
     - @nrwl/devkit@15.8.5
   
   To fix this, run `nx migrate nx@16.3.2`
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

n/a

**Comment by AgentEnder** [comment]
Hey @ryanbas21, it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

**Comment by ryanbas21** [comment]
I've aligned everything and i still have the issue.

```
Report complete - copy this into the issue template

   Node   : 18.12.1
   OS     : darwin x64
   npm    : 8.19.2
   Hasher : Native
   
   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/angular        : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/esbuild        : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/express        : 16.3.2
   @nx/node           : 16.3.2
   @nx/react          : 16.3.2
   @nx/rollup         : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/vite           : 16.3.2
   @nx/web            : 16.3.2
   @nx/webpack        : 16.3.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @mands/nx-playwright : 0.6.2
   ---------------------------------------
   Local workspace plugins:
         token-vault-suites
         embedded-login
         autoscript-suites
         token-vault-proxy
         central-login
         @plugins/wait-for-api
         angular-todo
         reactjs-todo
         autoscript-apps
         token-vault-app
         todo-api
         mock-api
  ```
  
  I can try to see if i can reproduce this somehow in a minimal repro.
  
  
![Screenshot 2023-06-23 at 4 22 14 PM](https://github.com/nrwl/nx/assets/18267769/91a7fb33-52fa-44c3-a3c3-f7bf0ac06993)

**Comment by meeroslav** [comment]
This type of error happens when we can't properly detect target project so then typescript resolver resolves it back to the source. This is usually caused by broken configuration.

It vitally we have a repro so we can see what is exactly happening there.

Otherwise, you can try to debug it yourself by logging parts of the rule (in `node_modules/@nx/eslint-plugin/src/rules/enforce-module-boundaries.js` and then follow the path to target project discovery.

**Comment by meeroslav** [comment]
This code should find that `@angular/router` is an external package - https://github.com/nrwl/nx/blob/master/packages/nx/src/plugins/js/project-graph/build-dependencies/target-project-locator.ts#L169-L173

If it doesn't that either means that the package is not installed or that lock file parsing got broken.
Can you confirm that there is `@angular/router` in your `package.json` and that `node_modules/.cache/nx/parsed-lock-file.json` contains `npm:@angular/router` in the `externalNodes`?
