### ISSUE TITLE
Incorrect @nx/enforce-module-boundaries lint error flagged for importing lazy-loaded libs in tests

### ISSUE THREAD

**Issue by gkamperis** [nrwl/nx#17737]
### Current Behavior

linting the a lib that has a reference to a lazy loaded lib triggers a `@nx/enforce-module-boundaries` when importing from that lazy loaded lib **in a test.**

I understand importing directly should be flagged as it effectively cancels out the lazy loading, but this is a test and the issue that is intended to prevent does not apply.

### Expected Behavior

No lint error to be flagged as the import is valid.

This was working fine in 15.1.1.

Got the issue after upgrading to 16.3.2

### GitHub Repo

https://github.com/gkamperis/nx-boundaries-lint-bug

### Steps to Reproduce

1. `nx lint ui-br`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 19.3.0
   OS     : win32 x64
   npm    : 9.2.0
   Hasher : Native

   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/angular        : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/web            : 16.3.2
   @nx/webpack        : 16.3.2
   typescript         : 5.0.4
```

### Failure Logs

```shell
nx\deps\libs\ui-br\src\lib\lib.routes.spec.ts
  3:1  error  Imports of lazy-loaded libraries are forbidden  @nx/enforce-module-boundaries

✖ 1 problem (1 error, 0 warnings)

Lint errors found in the listed files.

 >  NX   Ran target lint for project ui-br (4s)

    ×    1/1 failed
    √    0/1 succeeded [0 read from cache]
```

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by meeroslav** [comment]
Thank you @gkamperis for reporting this behaviour. 

Test runner has no knowledge of production build, so it cannot distinguish which imports are used in test and which are not.

There are several solutions to your problem that don't require changes to `nx`:
- Disable linting of `*.spec.ts` (in project's eslintrc `"ignorePatterns": ["!**/*", "**/*.spec.ts"]`) 
- Disable the linting of that import with line comment (`// eslint-disable-next-line @nx/enforce-module-boundaries`)
- Use the same type (e.g. `dynamic`) import in the test as well

Calculating which dependencies are `prod` and which are `dev-only` would be too expensive for runtime so we would not want to include that. Especially given the potential other solutions mentioned above.

**Comment by gkamperis** [comment]
@meeroslav thanks for the response. 

Can you pls explain how this was ok in v15.1.1 and what has changed since that version?

Disabling linting on specs is not a good solution.
Disabling the line is again not a good solution for many reasons.

Can you pls provide an example on the usage of `dynamic` import based on the repo I provided?

**Comment by meeroslav** [comment]
@gkamperis, this was never ok. But before v15.1.1 our graph had a bug where the information on the type of the import was lost while creating the graph so dynamic dependencies were treated as static when analyzing code.

Once we fixed that a lot of folks started getting these errors.

Instead of this:
```ts
// instead of static import
import { UiCrModule } from '@deps/ui-cr/*';

describe('Routing test', () => {
  it('should load specific module', () => {
    const r = router.config.find((r) => r.path === 'c');
    if (r?.loadChildren) {
      expect(r.loadChildren()).toEqual(UiCrModule);
    }
  });
});
```

You can write it like this:
```ts
describe('Routing test', () => {
  it('should load specific module', async () => {
    // we can import it dynamically inside the test or lifetime hook
    const { UiCrModule } = await import('@deps/ui-cr/*'); 
    
    const r = router.config.find((r) => r.path === 'c');
    if (r?.loadChildren) {
      expect(r.loadChildren()).toEqual(UiCrModule);
    }
  });
});
```
