### ISSUE TITLE
Image processing misconfiguration in withWeb() plugin?

### ISSUE THREAD

**Issue by ziacik** [nrwl/nx#17736]
### Current Behavior

I think there might be a misconfiguration in the `withWeb()` plugin related to image processing?

https://github.com/nrwl/nx/blob/1e8de7a00e7543ee85b708237ec96b72a8c07c57/packages/webpack/src/utils/with-web.ts#L412-L427

The file-loader along with the "asset" configuration seems to be duplicated, leading to (possible?) double-processing of images and generating files with content like `export default __webpack_public_path__ + "minus.800c76ad9918b99b1b26.png";`.

According to the documentation, the "asset" configuration is meant to replace the file-loader, so it shouldn't need to be there both. However, I may be wrong.

It's possible that the duplicated configuration was meant for files that do not meet the `dataUrlCondition`, but I think it's unnecessary since those files are still processed by the first rule.

Additionally, there are different sets of extensions in both rules, and I'm not sure why. It might be better to just list all extensions as assets.

Note: It would be nice if these configuration plugins were more customizable, or if there was a way to specify what should be included and what should not. Currently, I have to test the rules in my webpack config and remove all image-related ones, then add them back in myself.

### Expected Behavior

I think there should be just one image-related rule, specifically the "asset" one.

### Steps to Reproduce

1. Create a frameworkless web app, with isolated config, with withNx() and withWeb() plugins.
2. Build the app
3. See the images being processed with file-loader, generating the "export" image files instead of just inlining.

### Nx Report

```shell
Node   : 16.17.1
   OS     : linux x64
   npm    : 9.6.3
   Hasher : Native
   
   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/react          : 16.3.2
   @nx/rollup         : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/web            : 16.3.2
   @nx/webpack        : 16.3.2
   typescript         : 5.0.4
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
It looks like the images like `png` have duplicate rules, as you mentioned. We should patch this by separating the font assets rule from the image asset rule so there isn't any conflict. And `file-loader` should be removed as well.

**Comment by iamamanbhardwaj** [comment]
https://github.com/nrwl/nx/issues/17355 can anyone look into this .
