### ISSUE TITLE
Angular and Angular-Nest Presets have react styling options

### ISSUE THREAD

**Issue by mehrad-rafigh** [nrwl/nx#1773]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior
When selecting the `angular` or `angular-nest` presets, **styled-components** and **emotion** should not be available as styling options for an Angular App

## Current Behavior
When creating a new workspace with `npx create-nx-workspace myworkspace` and selecting `angular` as a preset, nx lets me choose styled-components and emotion as my styling.
These options are react only.

### Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1.`npx create-nx-workspace my-workspace`
2. Select `angular` as the preset

**Comment by beckend** [comment]
This then needs to be marked as a bug, no?

**Comment by mehrad-rafigh** [comment]
Yes you are right. This is a bug, according to your issue. Would you like to contribute?
The offending function is here https://github.com/nrwl/nx/blob/fa05f1171a7dc09e3fb695d94b098f142f14562e/packages/create-nx-workspace/bin/create-nx-workspace.ts#L293

Currently there is only a check if no preset is selected. Otherwise it returns the entire list of styling options for the monorepo. 

With Angular only css, scss, less and stylus are valid options.

**Comment by jdpearce** [comment]
@beckend, @mehrad-rafigh - this one bothered me, so I've created a PR already 🤓
