### ISSUE TITLE
PWA: Install option not showing in address bar in PWA App in chrome 76.

### ISSUE THREAD

**Issue by SWGeekPD** [nrwl/nx#1775]
As per Google doc the new chrome version 76 should show the install option in the address bar but I m not getting any install option.

On the other hand if I lower down my chrome version to 75, I can see the install option in the 3 dot options.

**Comment by vsavkin** [comment]
Could you provide a repro for the issue?

**Comment by SWGeekPD** [comment]
this is fixed with Chrome 77 version.
