### ISSUE TITLE
nextjs server - cli options should not be kebab cased

### ISSUE THREAD

**Issue by davidosomething** [nrwl/nx#17765]
### Current Behavior

in https://github.com/nrwl/nx/blob/ae698a72748d9f33aa5395aeeaa7b7af436a1dc5/packages/next/src/utils/create-cli-options.ts#L6  there is code to manually kebab case options passed to next  

The options are only used by nx/packages/next/src/executors/server/server.impl.ts  
and passed to the next js bin (cli)  https://github.com/nrwl/nx/blob/master/packages/next/src/executors/server/server.impl.ts#L54-L58

### Expected Behavior

next.js only takes camelCased options, and the only such option is `keepAliveTimeout`
- https://nextjs.org/docs/app/api-reference/next-cli#development

the option is already camelcased in the nx docs: https://nx.dev/packages/next/executors/server

### Steps to Reproduce

1. Generate next.js app, use next.js server executor https://nx.dev/packages/next/executors/server
2. Give it a keepAliveTimeout
3. Try to project:serve, it will complain 

```
Unknown or unexpected option: --keep-alive-timeout
```

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : linux x64
   pnpm   : 8.5.0
   Hasher : Native

   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/esbuild        : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/next           : 16.3.2
   @nx/node           : 16.3.2
   @nx/react          : 16.3.2
   @nx/rollup         : 16.3.2
   @nx/storybook      : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/web            : 16.3.2
   @nx/webpack        : 16.3.2
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   @trumbitta/nx-plugin-unused-deps : 1.12.1
   ---------------------------------------
   Local workspace plugins:
```

### Failure Logs

```shell
Unknown or unexpected option: --keep-alive-timeout
```
```


### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by ndcunningham** [comment]
Hey, thanks for pointing this out.
There are a few things to clarify here:
1. We use `create-cli-options` for both `serve` and `build` executors
2. Most of there are 4 options Next.js can take for `build` 3 of them **are** kebab case: 
```
      Options
      --profile                 Can be used to enable React Production Profiling
      --no-lint                 Disable linting
      --no-mangling             Disable mangling
      --experimental-app-only   Only build 'app' routes
 ```
 3. `keepAliveOptions` for serve is only valid to be passed in `production`
 
That being said I put a PR out for this.
