### ISSUE TITLE
Wrong hint about --dry-run

### ISSUE THREAD

**Issue by lazarljubenovic** [nrwl/nx#17776]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/packages/jest#adding-jest-to-an-existing-project

### Additional context or description

Near the end of the [Adding Jest to an Existing Project](https://nx.dev/packages/jest#adding-jest-to-an-existing-project) section, there's a hint telling the reader to use the `--dry-run` flag to see what will be generated.

![image](https://github.com/nrwl/nx/assets/7661457/efd3fc76-b70f-45a3-9c3b-8a234edf93e1)

When I run the command with this flag, however, I get the following error:

>  This generator does not support --dry-run. If you are running this in Nx Console, it should execute fine once you hit the "Run" button.

**Comment by lazarljubenovic** [comment]
Then it doesn't really "execute fine" as promised, either 😄 

> Cannot set properties of undefined (setting 'test')

```text
TypeError: Cannot set properties of undefined (setting 'test')
    at updateWorkspace (/.../node_modules/@nx/jest/src/generators/jest-project/lib/update-workspace.js:8:32)
    at /.../node_modules/@nx/jest/src/generators/jest-project/jest-project.js:46:48
    at Generator.next (<anonymous>)
    at fulfilled (/.../node_modules/tslib/tslib.js:164:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by AgentEnder** [comment]
Does the existing project have a project.json file? If so, is there a targets option inside it?

**Comment by lazarljubenovic** [comment]
Nope, it's a relatively new package-based project.

**Comment by AgentEnder** [comment]
The generators provided by the various plugins only really support integrated projects.

**Comment by lazarljubenovic** [comment]
The least it should do then is to report an error like “Expected a `project.json` file to exist” then.
