### ISSUE TITLE
setup-verdaccio generator includes undesired targets from package.json

### ISSUE THREAD

**Issue by dmitry-stepanenko** [nrwl/nx#17779]
### Current Behavior

The new verdaccio generator `nx g @nx/js:setup-verdaccio` may create a buggy behavior with repositories that were created with older versions of Nx

This generator adds a project.json to the root so nx treats the root of the workspace as another target and pulls scripts from package.json as its targets. Older versions of `create-nx-plugin` (e.g. 15.1) added `"build": "nx build"` script to the package.json. That script is treated as a project target. And now it means if we run `nx affected --target=build`, it will throw an error since `nx build` is not a valid command in itself.

### Expected Behavior

generator should not present breaking behavior

Do you think it is worth adding the following to the package.json when we run the setup-verdaccio generator?
```json
  "nx": {
    "includedScripts": []
  }
```

If you're happy with the change, I can create a PR

### Steps to Reproduce

1. npx create-nx-plugin@15.1 
2. npx nx migrate latest
3. npx nx g @nx/js:setup-verdaccio
4. npx affected --target=build

### Nx Report

```shell
-
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Hey @dmitry-stepanenko 👋.

Thanks for bringing this to our attention, its certainly an unintended side affect of setting up the root project. I believe the change should look something like this:

> packages/js/src/generators/setup-verdaccio/generator.ts
```diff
if (!tree.exists('project.json')) {
    const { name } = readJson(tree, 'package.json');
+    updateJson(tree, 'package.json', (json) => {
+      if (!json.nx) {
+        json.nx = {
+          includedScripts: []
+        };
+      }
+      return json;
+    })
    addProjectConfiguration(tree, name, {
      root: '.',
      targets: {
        ['local-registry']: verdaccioTarget,
      },
    });
  } else {
```

This logic works by saying:
- We are creating a new project.json at the root, which will cause Nx to register the root project
- The root package.json does not contain an "nx" key, so its not already setup as an Nx project
- Add some default configuration to prevent all of your scripts from suddenly being targets.

Does this sound good to you? You can put the PR in if you are interested, or @xiongemi or myself can get it slotted in.

**Comment by dmitry-stepanenko** [comment]
Thanks @AgentEnder! I'll create a PR in the morning
