### ISSUE TITLE
NX cache failed to process symlink: "Cannot overwrite directory with non-directory."

### ISSUE THREAD

**Issue by imrim12** [nrwl/nx#17775]
### Current Behavior

**NX cache failed to process the symlink 'dist' created by Nuxt**

As Nuxt 3 generates the static files, it creates an .output folder with all the stuff inside, and for ease of deployment, it creates a 'fake' dist folder outside as a symlink that points to .output/public.

![image](https://github.com/nrwl/nx/assets/46400321/f6740ee2-0b9d-4606-bebc-f30d814b4df1)

### Expected Behavior

I actually don't know what to expect, perhaps it would copy the symlink as NX output as well? As long as it doesn't fail the build process

### Steps to Reproduce

1. Use Nuxt generate on a fresh Nuxt 3 project with NX cache

### Nx Report

```shell
Error: Cannot overwrite directory '/workspaces/project/node_modules/.cache/nx/6820557377151550718/outputs/client/dist' with non-directory '/workspaces/project/client/dist'.
    at /workspaces/sannatour.com/node_modules/.pnpm/fs-extra@11.1.1/node_modules/fs-extra/lib/util/stat.js:55:19
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by RLaursen** [comment]
+1 to expecting symlink in output

**Comment by MayaraRMA** [comment]
Anyone knows a workaround for this?

**Comment by FrozenPandaz** [comment]
This was fixed with: https://github.com/nrwl/nx/pull/22548 :tada:
