### ISSUE TITLE
ng add @nrwl/workspace angular.json paths off 

### ISSUE THREAD

**Issue by CharlieGreenman** [nrwl/nx#1778]
_[Please make sure you have read the submission guidelines before posting an iss

# Prerequisites
Angular V7.2.15
## Expected Behavior
Addition of nrwl workspace should be seamless

## Current Behavior
angular.json has old file paths of cli, and not that of workspace

### Steps to Reproduce
Create an angular application using the cli for v7.2.15 and use `ng add @nrwl/workspace` as specified here: https://nx.dev/angular/getting-started/getting-started

Thank you, appreciate all of Nrwl's hard work as always 

Update: Also noticed that absolute paths are also not updated with usage of ng add @nrwl/workspace

**Comment by brandonroberts** [comment]
Is this still an issue with the latest version of Nx?

**Comment by CharlieGreenman** [comment]
@brandonroberts unfortunately I am no longer on the project that caused this. Funny enough, I'm on a different project wherein I was unable to use ng add @nrwl/workspace all together. Ended up created a new workspace, porting over current Angular CLI project, and merging back over to original repo(to save commit history). 

There is alot of work to be done in tiny bits and pieces for this one, as well as unit testing. However, I'm not going to be writing it, so I can't say anything.

**Comment by vsavkin** [comment]
I think instead of trying to make `ng-add` work well, we should implement `nx import`, where you can import an existing project into the workspace. In this case you would do something like that:

```
npx create-nx-workspace myorg --preset=empty
cd myorg
nx import /path-to-project
```

A lot of folks want to move more than one project into a workspace, and ng-add doesn't handle that. Implementing `import` isn't simpler than implementing `ng-add`, but it covers a lot more use cases.

**Comment by CharlieGreenman** [comment]
My apologies, my notifications for github are going to wrong e-mail. Going to work on fixing that right now. 

That would be nice. The only thing I had to do in this process to make sure worked as expected.
1. I moved over from non-workspace repo, and replaced workspace repo app/src + app/assets + app/environments.
2. I kept `package.json` of app importing. In addition, completely cleaned out package.json with the exception of `@nrwl/` imports added. I tried to keep everything else when possible, and remove some files I realized would not be necessary

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by brandonroberts** [comment]
We have some progress with `ng add @nrwlworkspace --preserveAngularCLILayout`. Going to close this one for now
