### ISSUE TITLE
"yarn install" fails with "Error: Source project does not exist: @my-workspace/my-module" after 16.4.0

### ISSUE THREAD

**Issue by mklueh** [nrwl/nx#17781]
### Current Behavior

Yarn install fails for some reason because of the NX postinstall hook. 

```
# This file contains the result of Yarn building a package (nx@virtual:4f281d15987f5e0cb84dd847db787e4a7f982d268a3a083830c8bab28d22913183f2966ee750ecb920b0bb750373ab14031c58763d511fb1dfa184d355050473#npm:16.4.0)
# Script name: postinstall

node:internal/event_target:1011
  process.nextTick(() => { throw err; });
                           ^

Error: Source project does not exist: @my-workspace/demo-sdk
    at ProjectGraphBuilder.addDependency (/home/user/workspace/my-workspace/node_modules/nx/src/project-graph/project-graph-builder.js:175:19)
    at ProjectGraphBuilder.addStaticDependency (/home/user/workspace/my-workspace/node_modules/nx/src/project-graph/project-graph-builder.js:80:14)
    at ProjectGraphBuilder.addExplicitDependency (/home/user/workspace/my-workspace/node_modules/nx/src/project-graph/project-graph-builder.js:131:14)
    at /home/user/workspace/my-workspace/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:81:29
    at Array.forEach (<anonymous>)
    at Worker.<anonymous> (/home/user/workspace/my-workspace/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:80:38)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:236:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)

```

demo-sdk path is within the `tsconfig.base.json` paths, and the entire setup worked for months now and seemed to broke down with 16.4.0.

The error also occured with one package that is no where used.

I haven't upgraded with "nx migrate", and update my packages with yarn upgrade-interactive most of the time. 

### Expected Behavior

My packages to be installable again and / or to get a clearer error message, preferrably with a provided hint or solution.

### Steps to Reproduce

Hard to tell as I assume I did nothing special except for upgrading my packages here and then

### Nx Report

```shell
>  NX   Daemon process terminated and closed the connection

   Please rerun the command, which will restart the daemon.
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mklueh** [comment]
I've used the CLI to downgrade to 16.3.2 and then upgrade to 16.4.0 again.

A problem with `@nrwl/cypress@16.4.0` appeared, so I ran `yarn add @nrwl/cypress@16.4.0`
and then the migration command again and now it works.

**Comment by lughino** [comment]
I'm experiencing the same issue. Could you please reopen this issue?

**Comment by mklueh** [comment]
I think I've found a way around that issue. 

I've added a project.json to the affected library and set the name accordingly, and the issue was gone.

In case the project.json is now mandatory for every single package (not sure about that) I think the error message should be more revealing.

"Package xyz needs a valid project.json" or similar.

**Comment by lughino** [comment]
Thanks @mklueh.
Yes, I'm wondering the same. I use the monorepo with `package.json` so I don't have any `project.json` anywhere. I'd like to keep that way. But it's impossible to understand from the documentation.

**Comment by tido64** [comment]
I think I found the culprit: If you have `npmScope` set in `nx.json`, try removing it. More details here: https://github.com/nrwl/nx/issues/17987#issuecomment-1625057264
