### ISSUE TITLE
@nx/node:app build is creating nested directory

### ISSUE THREAD

**Issue by debasispanda** [nrwl/nx#17793]
### Current Behavior

Create an integrated mono repo with a node express app.

The node app build is creating following output.

```
-- dist
|   `-- apps
|       `-- server
|           |-- apps
|           |   `-- server
|           |       `-- src
|           |           `-- main.js
|           |-- main.js
|           |-- package-lock.json
|           `-- package.json
```

### Expected Behavior

It shoud create

```
-- dist
|   `-- apps
|       `-- server
|           `-- src
|           |     `-- main.js
|           |-- main.js
|           |-- package-lock.json
|           `-- package.json
```

### Steps to Reproduce

1. Create node express integreated mono repo
2. Build app
3. The dist directory will be cretaed with repeated paths.

### Nx Report

```shell
Node   : 18.12.1
   OS     : linux x64
   npm    : 8.19.2
   Hasher : Native
   
   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/esbuild        : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/node           : 16.3.2
   @nrwl/tao          : 16.3.2
   typescript         : 5.0.4
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
This is expected and working as intended.
It was purposefully changed to accommodate workspace libs for a Node app: https://github.com/nrwl/nx/pull/15069
