### ISSUE TITLE
Support running nest with swc

### ISSUE THREAD

**Issue by mcmxcdev** [nrwl/nx#17791]
## Description
Nest v10 release introduced the possibility to run nest with swc
See more: https://trilon.io/blog/nestjs-10-is-now-available#nestjs-%EF%B8%8F-swc

## Motivation
Quicker development iterations than with tsc

**Comment by DobroslavR** [comment]
Any update? Would love to use it 👀

**Comment by zimiovid** [comment]
Any updates? I try use direct commands in `project.json` but no profit

**Comment by Andr-07** [comment]
Any updates?

**Comment by ilesar** [comment]
You can use [this section](https://docs.nestjs.com/recipes/swc#monorepo) in the docs to setup SWC. Unfortunately, you have to do it in every NestJS application.

Basically, you just have to paste this code in your webpack.config.js in every app.

```js
const { composePlugins, withNx } = require('@nx/webpack');

const swcDefaultConfig =
  require('@nestjs/cli/lib/compiler/defaults/swc-defaults').swcDefaultsFactory()
    .swcOptions;

module.exports = composePlugins(withNx(), (config) => {
  config.module.rules.push({
    test: /\.ts$/,
    exclude: /node_modules/,
    use: {
      loader: 'swc-loader',
      options: swcDefaultConfig,
    },
  });
  return config;
});


```

Of course, make sure that you have the nestjs/cli installed locally in the project.

**Comment by jacqueslareau** [comment]
Probably related to: https://github.com/nrwl/nx/issues/8900

**Comment by lstanden** [comment]
I *think* this does the trick:

```ts
const { composePlugins, withNx } = require('@nx/webpack');

// Nx plugins for webpack.
module.exports = composePlugins(
  withNx({
    target: 'node',
    compiler: 'swc',
  }),
  (config) => {
    // Update the webpack config as needed here.
    // e.g. `config.plugins.push(new MyPlugin())`
    return config;
  }
);
```

**Comment by timonmasberg** [comment]
> I _think_ this does the trick:
> 
> ```ts
> const { composePlugins, withNx } = require('@nx/webpack');
> 
> // Nx plugins for webpack.
> module.exports = composePlugins(
>   withNx({
>     target: 'node',
>     compiler: 'swc',
>   }),
>   (config) => {
>     // Update the webpack config as needed here.
>     // e.g. `config.plugins.push(new MyPlugin())`
>     return config;
>   }
> );
> ```

For me, it is the same as the solution above, no speed improvement.

**Comment by santhitak** [comment]
Any updates?.. In my case I've tried few different ways yet still can't run nest with swc under nx.

**Comment by gperdomor** [comment]
I would like to having this too 🙏🏻

**Comment by ndcunningham** [comment]
Sorry for the late response.

This should already be supported. Enabling it should be to change the `compiler` options the webpack config via `withNx({ compiler: 'swc' })` this should add the appropriate loader.

If this does not work for you please feel free to open a new issue with a small repo!
