### ISSUE TITLE
Implement Lighthouse integration

### ISSUE THREAD

**Issue by vsavkin** [nrwl/nx#178]

**Comment by Yonet** [comment]
First implementation will include:

- Add `npm run perf` script to schematics. 
- Add a perf folder and sub folders for each app to save lighthouse view html. Add the subfolders to .gitignore. Name each file created by lighthouse as 'app-name+timestamp.html'.
- Implement REPL to get input "Which app"?
- Run the lighthouse directly if there is only one app.
- Update nx-upgrade scripts to include lighthouse changes.

@vsavkin @jeffbcross

**Comment by vsavkin** [comment]
Closing this. No immediate plans to add lighthouse support.
