### ISSUE TITLE
Cypress builder should fail early for compilation errors

### ISSUE THREAD

**Issue by ZachJW34** [nrwl/nx#1780]
## Expected Behavior

Cypress Angular builder should fail early if either the application or integration tests fail to compile and watch is not enabled.

## Current Behavior

Cypress will still run if application or integration tests fail to compile (without watch).

### Steps to Reproduce

1. `npm init nx-workspace my-app`
2. Change `app.component.ts` in `my-app` to cause a compile error
3. `ng e2e`
4. Change `app.spec.ts` in `my-app-e2e` to cause a compile error
5. `ng e2e`

### Context

[Cypress Builder](https://github.com/nrwl/nx/blob/master/packages/cypress/src/builders/cypress/cypress.impl.ts)
The output of the devServer build and integration tests compilation can be used to throw an error if watch is not enabled.

I can submit a PR for this issue!

**Comment by mehrad-rafigh** [comment]
Hi @ZachJW34, please contribute with a PR.

**Comment by vsavkin** [comment]
@ZachJW34 if you could submit a PR, that would be awesome!
