### ISSUE TITLE
Cannot find file "./translations/portfolio/pt-BR.json" with any of the following extensions: .js, .cjs, .mjs

### ISSUE THREAD

**Issue by felipeblobo** [nrwl/nx#17834]
### Current Behavior

I bump the NX version in our project (from 14.5.8 to 16.3.2) but we can't build the project because when @nx/next executor try to build, he find a .json file and throw an error because in this version (16.3.2) the files should be .js .cjs or .mjs. There is any workaround that we can do? 

### Expected Behavior

Build the app successfully. 

### Steps to Reproduce

1. Only build the app using nx build

### Nx Report

```shell
Node   : 18.15.0
   OS     : darwin x64
   npm    : 8.19.3
   Hasher : Native
   
   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/next           : 16.3.2
   @nx/react          : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/web            : 16.3.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Can you try the latest version this should be already addressed: https://github.com/nrwl/nx/pull/17623

**Comment by felipeblobo** [comment]
Tks!
