### ISSUE TITLE
Migrating to 16.4.0 from 15.4.4 with angular upgrade to 16.1 failing while running migration.json 

### ISSUE THREAD

**Issue by lak-dev** [nrwl/nx#17847]
### Current Behavior

When migrating project from nx 15.4.4 to 16.4.0 with angular upgrade to 15.1 to 16.1 , I'm getting this error while running migration.json file 

```
Failed to run update -to-cypress-12 from @nwrl/cypress
 This workspace is NOT up to date!!
Can not find module './ast'
```
I have tried installing cypress before running migration.json file, then it was giving same error for @nwrl/jest package.

Note : when I run following command it working fine - it properly updates package.json and migration.json file is created:

`npx nx migrate latest --interactive `

I'm getting error when I run below command

`npx yarn nx migrate --run-migrations --verbose`

### Expected Behavior

Migration should complete without error

### Steps to Reproduce

I don't have custom stuff in project so I believe any migration from 15.4.4 to 16.4.0 will create this problem.

### Nx Report

```shell
Node 18.16.1
OS    win32-x64
yarn. 1.22.19

nx : 16.4.0
@nx/js : 16.4.0
@nx/jest : 16.4.0
@nx/workspace:16.4.0
@nx/linter :16.4.0
@nx/angular: 16.4.0
@nx/cypress:16.4.0
@nx/devkit: 16.4.0
@nx/eslint-plugin: 16.4.0
@nwrl/Tao:16.4.0
@nx/webpack:16.4.0
@nx/nx-cloud:16.0.5
Typescript: 5.1.6
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by lak-dev** [comment]
Any update for this? Facing issues since last weeks. Tried multiple ways

**Comment by barbados-clemens** [comment]
@lak-dev can you rerun with the --verbose flag and get a full stack trace?

it seems like maybe an issue with tsquery running and makes me think there was an issue installing deps. so you can try removing node_modules and reinstalling.
