### ISSUE TITLE
NX 16 (React JS18)throwing javascript heap memory issue in pipeline

### ISSUE THREAD

**Issue by JagadeesanDuraisamy** [nrwl/nx#17849]
### Current Behavior

NX 16 throwing javascript heap memory issue in pipeline

### Expected Behavior

NX 16 should NOT throw javascript heap memory issue in pipeline

### Steps to Reproduce

1.Build the nx https://github.com/JagadeesanDuraisamyreact js 18.2 project in the pipeline
2. It throws Javascript heap issue
Tried the below command.  It is NOT working.
**"nx": "node --max_old_space_size=5048 ./node_modules/bin/nx",**

### Nx Report

```shell
1.Build the nx react js 18.2 project in the pipeline
2. It throws Javascript heap issue
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JagadeesanDuraisamy** [comment]
It is working after adding below command in build task

build : "node --max_old_space_size=12400 ./node_modules/nx/bin/nx run {your appname}:build"

**Comment by skazaz-utila** [comment]
I've also started to experience
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```
After the latest update in an Angular workspace

**Comment by harellevy** [comment]
same here...

**Comment by harellevy** [comment]
<img width="1281" alt="image" src="https://github.com/nrwl/nx/assets/2623446/2f9ea60b-8373-47e6-9233-cfff82e8ce08">

**Comment by harellevy** [comment]
even on 16 cores runners.

**Comment by asbrum** [comment]
Still not working

Nx: 18.0.1
Angular: 17.1.2

"nx": "node --max_old_space_size=12400 ./node_modules/nx/bin/nx",

**Comment by jorgeramirezamora** [comment]
This happens to me sometimes when building the image of my React project. I am using:
- Node: `20.15.1`
- Nx: `19.4.2`
I am delimiting the memory usage using `ENV NODE_OPTIONS="--max_old_space_size=4096"` but is still happening

**Comment by jaysoo** [comment]
Unfortunately without a repro this will be hard to debug. @jorgeramirezamora Can you open a new issue if you have a repro?

If the application is very large, there might not be much we can do except to increase memory for Node process, or switch to a more efficient transpiler/bundler (e.g. Babel -> SWC, Webpack -> Rspack, etc.). You can also try `skipTypeChecking` option for `@nx/webpack:webpack` executor or the [`withNx()` plugin](https://nx.dev/recipes/webpack/webpack-plugins#skiptypechecking).

**Comment by jorgeramirezamora** [comment]
> Unfortunately without a repro this will be hard to debug. @jorgeramirezamora Can you open a new issue if you have a repro?
> 
> If the application is very large, there might not be much we can do except to increase memory for Node process, or switch to a more efficient transpiler/bundler (e.g. Babel -> SWC, Webpack -> Rspack, etc.). You can also try `skipTypeChecking` option for `@nx/webpack:webpack` executor or the [`withNx()` plugin](https://nx.dev/recipes/webpack/webpack-plugins#skiptypechecking).

Alright @jaysoo thanks. I will try using `skipTypeChecking`. I know is a different question but do you guys have a migration for going from Babel to SWC? I think we cannot migrate to Rspack right now.
