### ISSUE TITLE
Cannot read property 'getChildAt' of undefined

### ISSUE THREAD

**Issue by zpydee** [nrwl/nx#1785]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

to be able to add both options `"inlineStyle": true` and `"inlineTemplate": true` to the schematics for `"@nrwl/angular:application"`

## Current Behavior

If I add both, an error is thrown `Cannot read property 'getChildAt' of undefined`

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

1. This is my schematics setup in angular.json

```
"@nrwl/angular:application": {
      "prefix": "spwn",
      "routing": true,
      "inlineTemplate": true,
      "inlineStyle": true,
      "style": "scss",
      "unitTestRunner": "jest",
      "e2eTestRunner": "cypress",
      "tags": "frontend,app"
    },
```

2. running his command `ng g @nrwl/angular:application app --directory my-directory`

3. results in

![Screenshot 2019-09-04 at 13 14 46](https://user-images.githubusercontent.com/6129162/64250341-28aa7280-cf16-11e9-9b27-df263307c507.png)

**Comment by jdpearce** [comment]
This seems to be down to the use of backticks in `nrwlHomeTemplate.html`. I noticed that if you set `inlineStyle` to `false` then you get the error : 

```
    Could not format /apps/another-app/src/app/app.component.ts because Invalid character. (60:2)
      58 |         <summary>Add UI library</summary>
      59 |         <pre>
    > 60 | `# Generate UI lib
         |  ^
      61 | ng g @nrwl/angular:lib ui
      62 |
      63 | # Add a component
```

Replacing these backticks with `&acute;` seems to fix the problem (and you can then set `inlineStyles` to `true` and it works).

I'll create a PR to that effect shortly.
