### ISSUE TITLE
@nx/js:node executor continues to watch the files with option `"watch": false`

### ISSUE THREAD

**Issue by mrfratello** [nrwl/nx#17868]
### Current Behavior

`@nx/js:node` executor continues to watch changes in files when option [`watch`](https://nx.dev/packages/js/executors/node#watch) is equal `false`

### Expected Behavior

`@nx/js:node` executor should not restart the build when option `watch` is equal `false`

### GitHub Repo

https://github.com/mrfratello/nx-node-server-issue

### Steps to Reproduce

1. Generate node project with [`create-nx-workspace`](https://nx.dev/node-server-tutorial/1-code-generation#creating-an-nx-workspace): 
  ```bash
  ✔ Which stack do you want to use? · node
  ✔ What framework should be used? · express
  ✔ Standalone project or integrated monorepo? · integrated
  ```
2. Add option `"watch": false` in node server app `project.json` by path `targets.serve.optons`
3. Run serve target: `nx run server:serve`
4. Change file `apps/server/src/main.ts`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin-arm64
   npm    : 9.5.1

   nx                 : 16.4.0
   @nx/js             : 16.4.0
   @nx/jest           : 16.4.0
   @nx/linter         : 16.4.0
   @nx/workspace      : 16.4.0
   @nx/devkit         : 16.4.0
   @nx/esbuild        : 16.4.0
   @nx/eslint-plugin  : 16.4.0
   @nx/node           : 16.4.0
   @nrwl/tao          : 16.4.0
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by sedx** [comment]
We faced same issue on our project.

We have SSR server with hot module reload. Executor restart whole server instead HMR update when change some file. 

Looks like registerFileWatcher should called [here](https://github.com/nrwl/nx/blob/3008be1e7afc1cfb30c866f4385153e92bdd9612/packages/js/src/executors/node/node.impl.ts#L216C5-L216C10) based on watch option value.

**Comment by jaysoo** [comment]
Thanks for taking the time to report the issue. A PR is opened with the fix.
