### ISSUE TITLE
Wrong folder structure while creating a RemixJS app

### ISSUE THREAD

**Issue by jdnichollsc** [nrwl/nx#17864]
### Current Behavior

There's no an "/apps" folder containing the application projects, the structure is wrong while creating a new RemixJS app with Nx cli.

### Expected Behavior

We're expecting to have this folder structure: https://nx.dev/more-concepts/folder-structure

### Steps to Reproduce

1. Create a new RemixJS app with Nx cli:
```sh
jdnichollsc@Juans-MacBook-Pro remix % npx create-nx-workspace@latest projectx \
--preset=@nx/remix \
--project=demo
```
2. The workspace folder structure is wrong (there's not an apps folder):
```
jdnichollsc@Juans-MacBook-Pro remix % cd projectx && ls
README.md		node_modules		project.json		test-setup.ts
app			nx.json			public			tools
jest.config.ts		package-lock.json	remix.config.js		tsconfig.json
jest.preset.js		package.json		remix.env.d.ts		tsconfig.spec.json
```

### Nx Report

```shell
Node   : 20.3.1
   OS     : darwin-arm64
   npm    : 9.6.7
   
   nx             : 16.4.0
   @nx/js         : 16.4.0
   @nx/jest       : 16.4.0
   @nx/linter     : 16.4.0
   @nx/workspace  : 16.4.0
   @nx/devkit     : 16.4.0
   @nx/react      : 16.4.0
   @nrwl/tao      : 16.4.0
   @nx/web        : 16.4.0
   typescript     : 5.1.6
   ---------------------------------------
   Community plugins:
   @nx/remix : 16.4.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jdnichollsc** [comment]
Getting the same error while creating a new lib from this project:
1. create a new lib: `npx nx g @nx/remix:lib ui`
2. there's no a `libs` folder:
```

jdnichollsc@Juans-MacBook-Pro projectx % ls  
README.md		node_modules		public			tsconfig.base.json
app			nx.json			remix.config.js		tsconfig.json
jest.config.app.ts	package-lock.json	remix.env.d.ts		tsconfig.spec.json
jest.config.ts		package.json		test-setup.ts		ui
jest.preset.js		project.json		tools
```

**Comment by Coly010** [comment]
We’ll need to look at what the preset is intending because we support Standalone repos and Integrated monorepos. 

So what you’re seeing is a correct repo and the subsequent behaviour of the library generator is also correct for a standalone repo

https://nx.dev/concepts/integrated-vs-package-based#standalone-applications

**Comment by jdnichollsc** [comment]
@Coly010 hello mate, thanks for your help!
I'm checking the docs and the cli from terminal and I'm not sure how can I create a monorepo with RemixJS using Nx.
I tried the below command:
`npx create-nx-workspace@latest projectx`

But I can't select RemixJS for the react preset:
```sh
✔ Which stack do you want to use? · react
? What framework would you like to use? … 
None          I only want react and react-dom
Next.js       [ https://nextjs.org/      ]
Expo          [ https://expo.io/         ]
```

Can you explain me what command can I use in order to make this monorepo project please? 🤔 
I'm trying to build a monorepo to debug issues migrating and old RemixJS project using workspace.json instead of project.json files for the projects! 

Thanks for your support! <3

**Comment by jdnichollsc** [comment]
My old project is using the previous folder structure for an Integrated Repo: https://nx.dev/more-concepts/folder-structure
So I'm trying to create a new project from scratch to help with this migration! <3

**Comment by Coly010** [comment]
Yeah sure!

This docs page should help with that! https://nx.dev/recipes/other/remix#remix-with-nx

**Comment by jdnichollsc** [comment]
It works perfect, thanks a lot Colum! <3
