### ISSUE TITLE
Angular application Build and Serve targets broken after updating to 16.4.0 (and 16.4.1 as well)

### ISSUE THREAD

**Issue by FabienDehopre** [nrwl/nx#17874]
### Current Behavior

After having update my nx workspace to the latest nx version 16.4.0 (yesterday) and 16.4.1 (today), the build and serve target of the applications breaks with a ton of warnings and errors.
Most of the warnings are related to comments in CSS and most (if not all) errors are releated to Babel and the css-load that cannot find a module (see logs).

The build of libraries still work.

### Expected Behavior

The build and serve targets of Angular application should work as before.

### GitHub Repo

private azure devops repo (However, I can provide a zip archive)

### Steps to Reproduce

1. run serve or build target on angular application after updating the repo to 16.4.0 or 16.4.1

### Nx Report

```shell
Node   : 18.15.0
   OS     : win32-x64
   yarn   : 1.22.19

   nx                 : 16.4.1
   @nx/js             : 16.4.1
   @nx/jest           : 16.4.1
   @nx/linter         : 16.4.1
   @nx/workspace      : 16.4.1
   @nx/angular        : 16.4.1
   @nx/cypress        : 16.4.1
   @nx/devkit         : 16.4.1
   @nx/eslint-plugin  : 16.4.1
   @nx/plugin         : 16.4.1
   @nrwl/tao          : 16.4.1
   @nx/webpack        : 16.4.1
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @jscutlery/semver        : 3.0.0
   @ngneat/spectator        : 15.0.1
   @ngneat/transloco        : 4.3.0
   @ngrx/component-store    : 16.0.1
   @nx-dotnet/core          : 1.22.0
   angular-auth-oidc-client : 15.0.5
   devextreme-angular       : 23.1.3
   ng-mocks                 : 14.11.0
   nx-stylelint             : 15.0.0
   ---------------------------------------
   Local workspace plugins:
         @eq/workspace-plugin
         @equans/components
         @equans/nx-plugin
         @equans/security
         @equans/i18n
         @equans/core
```

### Failure Logs

[nx-error.txt](https://github.com/nrwl/nx/files/11914496/nx-error.txt)

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Unfortunately I can't reproduce it in a new workspace.

Looking at the provided error logs, something weird must be going on with your installed packages:

```
./apps/example-oidc-app/src/main.ts - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/tools/babel/webpack-loader.js):
Error: [BABEL] C:\Projects\equans-belux-frontend-framework\apps\example-oidc-app\src\main.ts: Cannot find module '../core-js-compat/data.js'
Require stack:
- C:\Projects\equans-belux-frontend-framework\node_modules\babel-plugin-polyfill-corejs3\lib\index.js
```

The error originates from the `babel-plugin-polyfill-corejs3` package trying to require `../core-js-compat/data.js`. Checking the published package contents I can see that path exists and the `require` has the correct relative path to it:

https://unpkg.com/babel-plugin-polyfill-corejs3@0.8.1/lib/index.js
https://unpkg.com/babel-plugin-polyfill-corejs3@0.8.1/core-js-compat/data.js

I would suggest you to delete your `node_modules` and try installing again. If the problem persists, we'll need a minimal repo where the issue can be reproduced.

**Comment by FabienDehopre** [comment]
Weird indeed. I looked at my node_modules/babel-plugin-polyfill-corejs3 folder and there is no core-js-compat folder.
I'm using yarn as a package manager. Can it be the source of the issue?
I also tried on ubuntu and the issue does not happen.

**Comment by leosvelperez** [comment]
Did you try deleting `node_modules` and installing again? Clearing the Yarn cache might help as well. I don't know what could cause the issue, but it looks like something specific to your environment.

**Comment by FabienDehopre** [comment]
I did delete the node_modules several times but I didn't think about cleaning the yarn cache before.
It fixed the issue. 
Thanks a lot @leosvelperez 
I close the issue since the issue is solved.
