### ISSUE TITLE
React component schematic creates all components under root if no --directory

### ISSUE THREAD

**Issue by dfmartin** [nrwl/nx#1788]
The docs using nx/react when creating a component with 
`nx g @nrwl/react:component todo` show an image of what should be the resulting folder structure.  This is inconsistent with what I am seeing.

## Expected Behavior

that using the command `nx g @nrwl/react todo` would create a `todo` folder and place the files in the `workspace/libs/lib_project_name/src/lib/todo` directory 

## Current Behavior

All supporting files (*.tsx, *.spec.tsx, etc) for all components are placed in the lib directory ( `workspace/libs/lib_project_name/src/lib`).  not into a directory specifically for that component.

I realize that I may use the `--directory` parameter, but a) the docs are inconsistent with behavior, and b) placing components in a folder named for that component is, from my experience, standard practice, and it would be nice to not have to always include the directory parameter each time when it will 95% of the time be the exact name of the component.

using the latest version of @nrwl/react

**Comment by jaysoo** [comment]
The `--directory` is there to provide flexibility on where components are generated (in response to #1702). 

I don't think automatic grouping is necessarily standard or better. However, we could consider an enhancement where `directory` option is type `string | boolean`. This way `--no-directory` will use flat structure, whereas `--directory` (default) will group by component name. And lastly, `--directory foo` will generate it under the `foo` directory.
