### ISSUE TITLE
Github vulnerability warning for "mem"

### ISSUE THREAD

**Issue by jeffbcross** [nrwl/nx#1789]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Current Behavior

What is the current behavior?

Github warns me that there's a vulnerable dependency in my project after creating a new workspace. 

![image](https://user-images.githubusercontent.com/463703/64302627-13930b00-cf39-11e9-890e-bfaef9cb8602.png)

![image](https://user-images.githubusercontent.com/463703/64302683-3fae8c00-cf39-11e9-84ff-6e6aef31c698.png)

Granted, this might be coming from something other than Nx itself...

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a new workspace with yarn create nx-workspace@8.4.13
2. Push to Github
3. See warning on Github project page

### Context

Please provide any relevant information about your setup:

- version of Nx used: 8.4.13
- 3rd-party libraries and their versions
- and most importantly - a use-case that fails

It looks like bumping it to 4+ fixes.

**Comment by vsavkin** [comment]
We don't directly depend on mem, it's a dependency three levels down. Tried to repro it, but wasn't able it. Maybe they remove the warning for it. I'll take a deeper look.

@jeffbcross does your workspace still show the warning?

**Comment by nodesmichael** [comment]
Same Github warning for us

**Comment by vsavkin** [comment]
From, what I can tell the issue has been fixed. The version of mem has been updated.
