### ISSUE TITLE
[Bug] Invalid path when generating a library

### ISSUE THREAD

**Issue by listepo** [nrwl/nx#179]
Angular CLI 1.6.2(npm version) + @nrwl/schematics 0.6.0

`ng g app test`
`ng g lib demo`

Output:

```
  create libs/demo/apps/test/src/demo.module.spec.ts (158 bytes)
  create libs/demo/apps/test/src/demo.module.ts (160 bytes)
  create libs/demo/index.ts (58 bytes)
```
`apps/test` invalid path

**Comment by dereklin** [comment]
My experience is that you need to use nrwl forked versions of the cli like:
```
"@angular/cli": "nrwl/fix-cli-build#release16"
```

**Comment by matthewharwood** [comment]
Even with #release16 the generating libs and applications is very wonky.

**Comment by matthewharwood** [comment]
It would seem the workspace path or something is off.  As generating an application or library seems to generate a dir structure more inline with a workspace.

**Comment by JamesHenry** [comment]
@dereklin is correct, you have to use the patched version of the CLI for this to work.

We have recently changed exactly how this works in new setups, we download a tgz of the CLI package and reference that in the package.json, but as @dereklin shows, referencing the 1.6 version of the patched CLI from github should also work.

If you want to download the tgz file and put it in the root of project, you can find it here: https://github.com/nrwl/nx/blob/master/packages/schematics/src/collection/application/files/__directory__/.angular_cli.tgz

You would then reference it in your package.json like so:
```"@angular/cli": "file:.angular_cli.tgz",```

We want to switch to the standard CLI project as soon as possible, but we are waiting on the functionality related to this issue to be merged before we can.

**Comment by dereklin** [comment]
The .tgz file worked fine for a while until I upgrade angular to 5.1.3.  Now I am getting:

```
module.js:544
    throw err;
    ^

Error: Cannot find module './config/config'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
```
As of now, I need to use 
```
"@angular/cli": "nrwl/fix-cli-build#release16"
```
for development,

And then check in using 
```
"@angular/cli": "1.6.3"
```
for production build because I am behind a proxy.

I hope this issue will be smoothed out soon
