### ISSUE TITLE
Default base should be configurable

### ISSUE THREAD

**Issue by hoang-innomizetech** [nrwl/nx#1791]
When running NX command, the default base is master. However, when we use GitFlow, our mainline is develop branch, so that would be great if we can change that setting without using --base option.

is there any way we can customize the default base option?

**Comment by vsavkin** [comment]
Not right now, but you are right--it should be configurable. We are working generalizing how we execute tasks, so you can have different task executors (local, distributed). The ability to configure defaults is part of that effort.

**Comment by FrozenPandaz** [comment]
Would somebody from the community be interested in contributing this feature?

I think it should work as follows.

Add a `nx.json` field for `defaultRef` which would be used if available.

**Comment by Wizyma** [comment]
Hey @FrozenPandaz  
I am trying to implement nx in my current company, not and easy task because this feat is one of the requirement due to the size of our org and the projects we have, but i would be glad to look into it, if i can do something i'll make a PR :) 

But anyway, awsome project !

**Comment by vsavkin** [comment]
@Wizyma if you want to submit a PR, we can help!

**Comment by Doginal** [comment]
I almost have this feature implemented. I will open a PR sometime this week!
