### ISSUE TITLE
@nx/webpack:webpack ignoring webpackConfig

### ISSUE THREAD

**Issue by drakedeatonuk** [nrwl/nx#17929]
### Current Behavior

I have a node server called 'api' with a `project.json` in which I am calling the `@nx/js:node` executor with a `buildTarget` set to call a `@nx/webpack:webpack` executor. These two executors can be seen below:

```
 "build": {
    "executor": "@nx/webpack:webpack",
    "outputs": [
      "{options.outputPath}"
    ],
    "options": {
      "target": "node",
      "compiler": "tsc",
      "tsconfig": "apps/api/tsconfig.json",
      "outputPath": "dist/apps/api",
      "tsConfig": "apps/api/tsconfig.app.json",
      "generatePackageJson": true,
      "main": "apps/api/src/main.ts",
      "externalDependencies": "all",
      "webpackConfig": "apps/api/webpack.config.ts"
    },
    "configurations": {
      "loc": {
        "optimization": false,
        "extractLicenses": false
      }
    },
    "defaultConfiguration": "loc"
  },
  "serve": {
    "executor": "@nx/js:node",
    "configurations": {
      "loc": {
        "buildTarget": "api:build:loc"
      }
    },
    "defaultConfiguration": "loc"
  }
}
```

Currently, when I call `nx serve api`, the webpack.config.ts is not being ran.

### Expected Behavior

I would expect that when running `nx serve api`, that the webpack.config.ts file would be ran.

The webpack.config.ts is ran if I run the `@nx/webpack:webpack` executor directly by calling `nx build api`, so I would expect the webpack.config.ts to also be called when running the serve command.

Please could someone check the repo I've made and confirm if this is indeed a bug?

### GitHub Repo

https://github.com/drakedeatonuk/nx-webpack-issue-reprod

### Steps to Reproduce

Follow the steps in the README:
1. run `yarn`
2. run `nx build api`. you'll see that the webpack.config.ts runs, because the `console.log` "Hello World" is printed.
3. run `nx serve api`. you'll see that the webpack.config.ts is not run.

### Nx Report

```shell
Node   : 19.8.1
OS     : darwin-arm64
yarn   : 3.5.0
   
nx                 : 16.4.2
@nx/js             : 16.4.2
@nx/jest           : 16.4.2
@nx/linter         : 16.4.2
@nx/workspace      : 16.4.2
@nx/angular        : 16.4.2
@nx/cypress        : 16.4.2
@nx/devkit         : 16.4.2
@nx/eslint-plugin  : 16.4.2
@nx/express        : 16.4.2
@nx/nest           : 16.4.2
@nx/node           : 16.4.2
@nx/plugin         : 16.4.2
@nx/storybook      : 16.4.2
@nrwl/tao          : 16.4.2
@nx/webpack        : 16.4.2
nx-cloud           : 16.0.5
typescript         : 5.1.6
---------------------------------------
Community plugins:
@nx-tools/nx-prisma : 4.0.3
```

### Failure Logs

```shell
N/A
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Thank you in advance to the NX team for having a look at this issue!

**Comment by aparij** [comment]
same issue on 16.5.3

**Comment by aparij** [comment]
@drakedeatonuk Why your webpack config is ts extenstion, shouldn't it be .js ?
