### ISSUE TITLE
`buildLibsFromSource: false` doesn't work with Vite executors

### ISSUE THREAD

**Issue by ms-tng** [nrwl/nx#17922]
### Current Behavior

Suppose an app `my-app` uses the `@nx/vite:build` and/or `@nx/vite:dev-server` executors and depends on a lib `my-lib`. Then when the `buildLibsFromSource` option of the executor is set to `false`, `my-lib` is still built from source within `my-app`.

I created a reproducible example, see below.

This seems to be caused by a combination of two faulty behaviors:
1. When the executor generates a temporary `tsconfig.generated.json` file, it tries to figure out whether the lib is buildable. It does so by checking if it has a target with the same name as the target currently being executed for the app, see https://github.com/nrwl/nx/blob/50d01d15677eb9165e24d759d790f60af22b9fff/packages/vite/src/utils/executor-utils.ts#L43 That means when the target currently being executed is called `serve`, it looks for a target called `serve` in the lib, which doesn't make sense. The `@nx/webpack:dev-server` executor uses a hard-coded `'build'` here, which is probably not optimal either but should work in most cases.
2. When one fixes point 1. by patching `@nx/vite`, the `tsconfig.generated.json` file is generated correctly. However, it is still not respected by the build. I haven't figured out why, but I suspect it's because Nx Vite apps use the `vite-tsconfig-paths` plugin, which needs to be made aware of the generated `tsconfig` file, but isn't.

### Expected Behavior

`my-lib` is not built from source, but its build artifact is used instead.

### GitHub Repo

https://github.com/ms-tng/nx-buildlibsfromsource-repro

### Steps to Reproduce

1. Create a Vite app and a lib, where the app depends on the lib
2. Set `"buildLibsFromSource": false` for the `build` and `serve` targets of the app
3. Build the lib and build or serve the app
4. Open the app in a browser and observe that the lib is built from its sources

### Nx Report

```shell
Node   : 16.14.2
OS     : win32-x64
npm    : 8.5.0

nx                 : 16.4.2
@nx/js             : 16.4.2
@nx/linter         : 16.4.2
@nx/workspace      : 16.4.2
@nx/cypress        : 16.4.2
@nx/devkit         : 16.4.2
@nx/eslint-plugin  : 16.4.2
@nx/react          : 16.4.2
@nrwl/tao          : 16.4.2
@nx/vite           : 16.4.2
@nx/web            : 16.4.2
typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
There's already a PR in the process, and it will be merged soon.

**Comment by ms-tng** [comment]
Thanks! Looking forward to trying the fix. :)

**Comment by ms-tng** [comment]
Note that this still doesn't work in Nx 16.6.0, for two reasons:
- https://github.com/nrwl/nx/issues/18458, which is the same as point 1 above
- https://github.com/nrwl/nx/issues/18459, which is a problem with the new Vite plugin
