### ISSUE TITLE
Incorrect generated directory structure in dist for nodejs apps

### ISSUE THREAD

**Issue by catch-the-elephant** [nrwl/nx#17936]
### Current Behavior

In an integrated monorepo, when building a nodejs app(let's call it `myapp`), specifically in `cjs` format (which is default), the build step generates the following path for the app's code:

`dist -> apps -> myapp -> apps -> myapp -> src`.

Please note that the issue doesn't seem to exist when building in the `esm` format.

### Expected Behavior

The path for the app's code should be:

`dist -> apps -> myapp` or something similar.

### Steps to Reproduce

1. Create a workspace using  `npx create-nx-workspace@latest myorg`
2. Choose Nodejs, Express, and integrated monorepo.
3. Choose some app name
4. Run `nx run [YOU_APP_NAME]:build
`

### Nx Report

```shell
Node   : 19.6.0
   OS     : darwin-arm64
   npm    : 9.4.0
   
   nx (global)        : 16.4.2
   nx                 : 16.4.3
   @nx/js             : 16.4.3
   @nx/jest           : 16.4.3
   @nx/linter         : 16.4.3
   @nx/workspace      : 16.4.3
   @nx/devkit         : 16.4.3
   @nx/esbuild        : 16.4.3
   @nx/eslint-plugin  : 16.4.3
   @nx/node           : 16.4.3
   @nrwl/tao          : 16.4.3
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
This is expected and working as intended. Please see https://github.com/nrwl/nx/issues/17793#issuecomment-1609994082 for more context.
