### ISSUE TITLE
Can't serve Next custom server due to 'Could not find ${fileToRun}' error

### ISSUE THREAD

**Issue by MarkComerford** [nrwl/nx#17946]
### Current Behavior

When using a custom server for a Next app project and then trying to serve it the following error occurs:

Error: Could not find /Users/xxx/TestProjects/nxws16/dist/apps/my-next-app/apps/my-next-app/server/main.js. Make sure your build succeeded.
    at fileToRunCorrectPath (/Users/xxx/TestProjects/nxws16/node_modules/@nx/js/src/executors/node/node.impl.js:244:23)
    at /Users/xxx/TestProjects/nxws16/node_modules/@nx/js/src/executors/node/node.impl.js:115:102
    at new Promise (<anonymous>)
    at /Users/xxx/TestProjects/nxws16/node_modules/@nx/js/src/executors/node/node.impl.js:110:40
    at Generator.next (<anonymous>)
    at fulfilled (/Users/xxx/TestProjects/nxws16/node_modules/tslib/tslib.js:166:62)

This worked fine in Nx v15. Nx serve also works correctly when not using a custom server.

### Expected Behavior

Next application server should start correctly

### Steps to Reproduce

1. npx create-nx-workspace@latest --preset=next
2. `✔ Where would you like to create your workspace? · nxws16
✔ Application name · my-next-app
✔ Would you like to use the App Router (recommended)? · Yes
✔ Default stylesheet format · css
✔ Enable distributed caching to make your CI faster · No`
3. nx g custom-server my-next-app
4. nx serve my-next-app
5. The error occurs when attempting to start the server

### Nx Report

```shell
Node   : 18.16.1
   OS     : darwin-x64
   npm    : 9.5.1
   
   nx (global)        : 16.4.0
   nx                 : 16.4.3
   @nx/js             : 16.4.3
   @nx/jest           : 16.4.3
   @nx/linter         : 16.4.3
   @nx/workspace      : 16.4.3
   @nx/cypress        : 16.4.3
   @nx/devkit         : 16.4.3
   @nx/eslint-plugin  : 16.4.3
   @nx/next           : 16.4.3
   @nx/react          : 16.4.3
   @nrwl/tao          : 16.4.3
   @nx/web            : 16.4.3
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Similar error here: https://github.com/nrwl/nx/issues/17429
