### ISSUE TITLE
visualizing/generating 3rd party dependency tree

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#1796]
## Expected Behavior

Does nx support dependency tree visualisations for 3rd party dependencies?

**Why would I do that?**

As  nx uses root package.json as source of truth for all 3rd party packages (which is very good practice 👌) we still need local package.json for various reasons like:
- "ejecting" particular library out from nx and publish it as open source. Manually aggregating real dependencies for a lib is real pain...

This feature would be also very helpful as it would allow to re-generate local package.json files with proper versions used in root ( can be combined with yarn workspaces as well)

Slightly related to https://github.com/nrwl/nx/issues/1777

**Comment by FrozenPandaz** [comment]
We are currently working on this feature.

**Comment by Hotell** [comment]
> We are currently working on this feature.

amazing! 👌

**Comment by Hotell** [comment]
hey folks. any updates on this ? 🙏

**Comment by FrozenPandaz** [comment]
We currently have the information in the dep-graph but have not figured out a graceful way to expose it in the visualization.

**Comment by hertzg** [comment]
Hello @FrozenPandaz, It's great to hear that it was in progress 👏. Is there any way we could track the progress? Maybe a PR?

**Comment by hertzg** [comment]
@github-actions 

![](https://media.giphy.com/media/7zJZgRRVrKfzo71lnR/giphy.gif)

**Comment by ild0tt0re** [comment]
Any news?

**Comment by fider** [comment]
`nx prepare-production-deployment-for-single-servie service-x` please.

(installed npm dependencies only for service-x and it's internal dependencies).
If @nrwl/js is able to deduce internal dependencies from .ts source code, it should be possible to create list of npm external dependencies for single service also.

**Comment by Elyahou** [comment]
@FrozenPandaz Any news on this ?
