### ISSUE TITLE
Misleading message when Jest not installed in workspace

### ISSUE THREAD

**Issue by jdpearce** [nrwl/nx#1797]
### Steps to Reproduce

(Assuming `npm install -g @nrwl/cli` has been run)

`$> npx create-nx-workspace@latest test-workspace`
`$> cd test-workspace`
`$> yarn add --dev @nrwl/jest`
`$> nx g @nrwl/workspace:lib my-lib`
>             "jest" is not installed as a dependency.
>            Add "jest" via "yarn add --dev @nrwl/jest" or "npm install -D @nrwl/jest"

**The library is actually created as expected though**

## Expected Behavior

Should the message refer to simply `jest` rather than `@nrwl/jest`?

NB - if you attempt to run `nx g @nrwl/workspace:lib my-lib` before adding `@nrwl/jest`, you get no helpful response from `nx`, just a `Could not find module "@nrwl/jest"` response.

### Context & Notes

- Nx 8.4.13

The message comes from here :

https://github.com/nrwl/nx/blob/2b646f8eb4839d7b3b47bf703016e33bf1dbd2fe/packages/jest/src/schematics/jest-project/jest-project.ts#L111-L116

You can see the code is looking for the `jest` library in packageJson, not `@nrwl/jest`

**Comment by vsavkin** [comment]
Fixed it here: https://github.com/nrwl/nx/commit/c3f21324368b4ebe84bd9e45e22b88506f44116a

Now, we initialize jest any time we are running `jest-project`, similar to how we do it with other packages.
