### ISSUE TITLE
NX-Cloud Selfhosted: Gitlab-Integration - Failed to find merge request

### ISSUE THREAD

**Issue by rryter** [nrwl/nx#17982]
### Current Behavior

Unfortunately the Gitlab Integration for Selfhosted aka Enterprise does not work properly.

First of all when filling out the form with the Project ID, Access Token and the Gitlab URL, the gui does not update correctly. After reloading the page, I can see that it worked:

![nx-cloud-gitlab](https://github.com/nrwl/nx/assets/798709/2eda5952-d0de-418c-889c-9a051c9e4b1d)

After a successful run of `nx affected` on the CI, I can see this output in the log of `nx-cloud-nx-api` pod:

```
07:12:00.889 [Thread-18] INFO VCSIntegration - GitlabIntegration / 25e4bd18-eaf8-4086-8731-4ba5275d07fa - Failed to find merge request with id 11 for project 928
```

Hover I was able to confirm that the API request works as expected with the same access token, i ran this within the `nx-cloud-nx-api`:
```
/ $ wget "https://gitlab.visana.ch/api/v4/projects/928/merge_requests/11?private_token=REDACTED" --no-check-certificate -O-
Connecting to gitlab.visana.ch (192.168.60.33:443)
writing to stdout
{"id":16745,"iid":11,"project_id":928
... omited for brevity
```

To be nitpicking: `id` is 16745 and not 11, that would be `iid`

### Expected Behavior

It should just work.

### Steps to Reproduce

1. Follow the setup guides

### Nx Report

```shell
Node   : 18.15.0
   OS     : linux x64
   npm    : 9.5.0
   Hasher : Native

   nx (global)        : 16.4.0
   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/angular        : 16.2.2
   @nx/cypress        : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nx/storybook      : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/web            : 16.2.2
   @nx/webpack        : 16.2.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc         : 1.1.19
   @ng-bootstrap/ng-bootstrap : 15.0.0
   @ngneat/input-mask         : 6.1.0
   @storybook/angular         : 7.0.18
   ng-mocks                   : 14.7.3
   nx-stylelint               : 15.0.0
```

### Failure Logs

```shell
07:12:00.889 [Thread-18] INFO VCSIntegration - GitlabIntegration / 25e4bd18-eaf8-4086-8731-4ba5275d07fa - Failed to find merge request with id 11 for project 928
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

To be frank trying to get this thing to run "self hosted" very painful. There have been so many problems, and after two months, it is still not working 100%.

**Comment by rryter** [comment]
Also there is this, the distribution of the tasks is extremely odd: 
![gitlab-agent-distribution](https://github.com/nrwl/nx/assets/798709/002f5c21-0925-4e5d-ac3a-654f04f41767)

**Comment by StalkAltan** [comment]
Hi! We offer support for self-hosting to our enterprise customers. You can find more information about that at `nx.app/enterprise`. I'll be closing this issue as it is outside of the scope we can support through GitHub.
