### ISSUE TITLE
Nx 16 Storybook 7 (Angular)

### ISSUE THREAD

**Issue by fitimsijarinaa** [nrwl/nx#17983]
### Current Behavior

I followed the instructions https://nx.dev/packages/storybook to setup storybook in our Angular project where we are using nx 16. When trying to start storybook with `nx run ui-components:storybook` it just is getting stuck 
<img width="674" alt="image" src="https://github.com/nrwl/nx/assets/34582738/05822acc-f30d-4be1-a128-54e921ca49f1">
.

### Expected Behavior

The command `nx run ui-components:storybook` should run the storybook or at least throw any error to know what's the issue.

### Steps to Reproduce

1. Follow the instructions for setup of storybook for angular https://nx.dev/packages/storybook
2. Try to run the storybook
3. It doesn't start at all

### Nx Report

```shell
Node   : 18.16.0
   OS     : darwin arm64
   npm    : 9.5.1
   Hasher : Native
   
   nx                 : 16.3.1
   @nx/js             : 16.3.1
   @nx/jest           : 16.3.1
   @nx/linter         : 16.3.1
   @nx/workspace      : 16.3.1
   @nx/angular        : 16.3.1
   @nx/cypress        : 16.3.1
   @nx/devkit         : 16.3.1
   @nx/eslint-plugin  : 16.3.1
   @nx/plugin         : 16.3.1
   @nx/storybook      : 16.3.1
   @nrwl/tao          : 16.3.1
   @nx/web            : 16.3.1
   @nx/webpack        : 16.3.1
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @ionic/angular           : 7.0.7
   @ionic/angular-toolkit   : 9.0.0
   @ngrx/component          : 16.0.1
   @ngrx/component-store    : 16.0.1
   @ngrx/effects            : 16.0.1
   @ngrx/entity             : 16.0.1
   @ngrx/router-store       : 16.0.1
   @ngrx/store              : 16.0.1
   @ngrx/store-devtools     : 16.0.1
   @storybook/angular       : 7.0.24
   @testing-library/angular : 13.3.0
   nx-stylelint             : 13.5.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Hi there @fitimsijarinaa ! Thanks for filing an issue. I cannot reproduce however. Here is my repository (https://github.com/mandarini/sb-ng-1631), please read the README, I followed the steps as you said and all worked for me.

Please share a reproduction repository with me so that I can help you out!

**Comment by fitimsijarinaa** [comment]
It was caused by how my package-lock.json was generated. Still couldn't figure out why it stuck. After somebody else generated the package-lock.json everything worked for me.

**Comment by mandarini** [comment]
That's great to hear! Thanks @fitimsijarinaa !
