### ISSUE TITLE
nx native integration with ngx-deploy-npm for publishing lib modules 

### ISSUE THREAD

**Issue by xmlking** [nrwl/nx#1800]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

`ng g lib mylib --publishable` generate publishable library

with `ngx-deploy-npm` we can publish  a library to `npm` with `ng deploy mylib`  command

`ng add ngx-deploy-npm` will add package and also update all library modules(publishable and non-publishable) in `angular.json` with **deploy** command. 

it doesn't know if the lib is publishable or not. that is way we need deep integration with  `ngx-deploy-npm`

when we create publishable library with `ng g lib mylib --publishable`  we could automatically add  **deploy** command to `angular.json` for publishable library

we can eventually able to build and publish all publishable libraries,  affected by changes with one command: `nx affected:deploy` 

## Current Behavior

What is the current behavior?

manual cleanup is needed to remove deploy command from `angular.json`  for non-publishable modules.

**Comment by dianjuar** [comment]
ngx-deploy-npm [have plans](https://github.com/bikecoders/ngx-deploy-npm#-next-milestones-) to work with Nx compatibility to set the deployer only to publishable Angular libraries.

In any case, with the new feature of the Angular CLI `ng deploy` would be nice to have an `affected:deploy`. With that we can deploy our applications to the platform that we want, even packages.

**Comment by dianjuar** [comment]
There is a discussion on #633 related with this issue

**Comment by vsavkin** [comment]
Folks,

You can define the deploy target manually and then run `nx affected --target=deploy`. It will calculate what is affected and deploy that. 

The main reason we abstained from wiring up deployment stuff automatically is that it tends to be org specific. Everyone does it differently. Can we change ngx-deploy-npm to be more Nx-aware so it will only add the deploy target to the libs that have the build target defined?

**Comment by dianjuar** [comment]
> Folks,
> 
> You can define the deploy target manually and then run `nx affected --target=deploy`. It will calculate what is affected and deploy that.
> 
> The main reason we abstained from wiring up deployment stuff automatically is that it tends to be org specific. Everyone does it differently. Can we change ngx-deploy-npm to be more Nx-aware so it will only add the deploy target to the libs that have the build target defined?

Yes, it is possible and it has high priority on the backlog

![image](https://user-images.githubusercontent.com/7026066/64742367-967c0e80-d4c1-11e9-88f6-8c885214afd0.png)

**Comment by dianjuar** [comment]
It's done

The [last version](https://github.com/bikecoders/ngx-deploy-npm/blob/master/src/CHANGELOG.md#features) of `ngx-deploy-npm` introduces Nx compatibility

FYI @vsavkin @xmlking

**Comment by vsavkin** [comment]
That's great! I'm going to mention it on our readme and then will close the issue.

**Comment by dianjuar** [comment]
FYI @vsavkin ngx-deploy-npm is now part of the [Angular's official documentation](https://angular.io/guide/deployment#automatic-deployment-with-the-cli).

You can use it to mention the deployer on the readme 

---------

![image](https://user-images.githubusercontent.com/7026066/68499422-2a025f00-0227-11ea-86f0-177031def1ff.png)

**Comment by brandonroberts** [comment]
Closing as resolved
