### ISSUE TITLE
emitDecoratorMetadata is only needed for nestjs apps and jest testing

### ISSUE THREAD

**Issue by xmlking** [nrwl/nx#1801]
for angular 8.1 and above `emitDecoratorMetadata` is removed from `tsconfig.json`
https://blog.ninja-squad.com/2019/07/03/angular-cli-8.1/
we only need it for `nestJs` and `jest` testing.

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.
