### ISSUE TITLE
Failed to run update-16-5-0 from @nx/storybook

### ISSUE THREAD

**Issue by simeon-raykov** [nrwl/nx#18014]
### Current Behavior

My team can't upgrade to v.16.5.0 because of storybook. It now requires us to have a local level tsconfig.json but we don't think we need that because it will only inherit from the base config and it will add additional complexity. This is a demo of our project structure:

├── .storybook/
│   ├── main.ts
│   ├── manager.ts
│   ├── preview-head.html
│   ├── test-runner.ts
│   ├── tsconfig.json
├── apps/
│   ├── demo/
│   │   ├── host/
|   │   │   ├── components/
|   │   │   ├───*.stories.tsx
│   │   ├── remote/
|   │   │   ├── components/
|   │   │   ├───*.stories.tsx
│   │   ├── storybook/
|   │   │   ├── .storybook/
|   │   │   ├─── main.ts
|   │   │   ├─── manager.ts
|   │   │   ├─── preview.ts
|   │   │   ├─── test-runner.ts
|   │   │   ├─── project.json
├── libs/
│   ├── demo/
│   │   ├── ui/
|   │   │   ├── src/
|   │   │   ├───*.stories.tsx

We have made all of the configurations needed in our root level .storybook and only inherit them in our demo scoped storybook app. Our demo scoped storybook main.ts file only imports the stories like this:
```
 stories: [
    `${workspacePath}/libs/demo/ui/src/**/*.mdx`,
    `${workspacePath}/libs/demo/ui/src/**/*.stories.@(js|jsx|ts|tsx)`,
    `${workspacePath}/apps/demo/app/**/*.stories.@(js|jsx|ts|tsx)`
  ]
```

### Expected Behavior

Migration should run successfully without the need of additional tsconfig.json

### Nx Report

```shell
Node   : 19.7.0
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx                 : 16.4.1
   @nx/js             : 16.4.1
   @nx/jest           : 16.4.1
   @nx/linter         : 16.4.1
   @nx/workspace      : 16.4.1
   @nx/cypress        : 16.4.1
   @nx/devkit         : 16.4.1
   @nx/eslint-plugin  : 16.4.1
   @nx/next           : 16.4.1
   @nx/react          : 16.4.1
   @nx/storybook      : 16.4.1
   @nrwl/tao          : 16.4.1
   @nx/vite           : 16.4.1
   @nx/web            : 16.4.1
   @nx/webpack        : 16.4.1
   nx-cloud           : 16.0.5
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @jscutlery/semver : 3.0.0
```

### Failure Logs

```shell
>  NX   Failed to run update-16-5-0 from @nx/storybook. This workspace is NOT up to date!


 >  NX   Cannot find apps/demo/storybook/.storybook/tsconfig.json

   Pass --verbose to see the stacktrace.

error Command failed with exit code 1.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by LouisLecouturier** [comment]
Hey Simeon ! I think I had the same issue (see #17966) I think they are working on it

**Comment by mandarini** [comment]
Hi there @simeon-raykov ! Thanks for filing an issue! It would be super useful if you could provide a small reproduction repository of the issue you are experiencing, and how this is causing you trouble in this case! If you don't want the project-level tsconfig you may remove it, but please let me know how this is blocking you!

**Comment by simeon-raykov** [comment]
@mandarini It is blocking me because there is now a test that searches for tsconfig.json when running the command "yarn nx migrate --run-migrations"

**Comment by mandarini** [comment]
I adjusted our migrator to change that as well. Can I see your `eslintrc` file please? Does it contain the path to that file?

**Comment by mandarini** [comment]
Yes, that's what I added in the migrator! :)
