### ISSUE TITLE
@nx/nx-win32-x64-msvc@16.4.3 detected by some AV as trojan

### ISSUE THREAD

**Issue by CSchulz** [nrwl/nx#18019]
### Current Behavior

The uploaded binary for windows https://www.npmjs.com/package/@nx/nx-win32-x64-msvc/v/16.4.3 is detected by some AV as trojan.

Detection report:
https://www.virustotal.com/gui/file/fbea03eaaf479dfed5afb7bcf676100aad43c11e15bceb947002756abb8bee8a/detection

### Expected Behavior

AV should not recognize the binary as trojan

### Steps to Reproduce

1. Download binary and upload to virustotal.com

### Nx Report

```shell
Node   : 18.12.1
   OS     : win32-x64
   pnpm   : 8.6.6

   nx                 : 16.4.3
   @nx/js             : 16.4.3
   @nx/jest           : 16.4.3
   @nx/linter         : 16.4.3
   @nx/workspace      : 16.4.3
   @nx/angular        : 16.4.3
   @nx/cypress        : 16.4.3
   @nx/devkit         : 16.4.3
   @nx/esbuild        : 16.4.3
   @nx/eslint-plugin  : 16.4.3
   @nx/node           : 16.4.3
   @nx/plugin         : 16.4.3
   @nrwl/tao          : 16.4.3
   @nx/webpack        : 16.4.3
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @ngneat/transloco : 4.3.0
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by salihsagdilek** [comment]
same here, i tried update to 16.5.

bitdefender TS;

Infected file detected: node_modules\@nx\nx-win32-x64-msvc\nx.win32-x64-msvc.node 
The file node_modules\@nx\nx-win32-x64-msvc\nx.win32-x64-msvc.node is infected with Gen:Variant.Tedy.395994 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

**Comment by edkotkas** [comment]
+1, also on windows here and bitdefender.

**Comment by ElijahKSmith** [comment]
+1 on Bitdefender Endpoint Security Tools, product version 7.9.3.298 (security content version 7.94933).

```
On-Access scanning has detected a threat. The file has been deleted. C:\Users\elijah\AppData\Local\npm-cache\_npx\973fb08ee51bb939\node_modules\@nx\nx-win32-x64-msvc\nx.win32-x64-msvc.node is malware of type Gen:Suspicious.Cloud.4.@x4@ay3GRzj
```

**Comment by CSchulz** [comment]
It seems to be gone with the newest signature update.
