### ISSUE TITLE
Get name of all libraries/apps in v16 without using nx print-affected

### ISSUE THREAD

**Issue by mjbertenburg** [nrwl/nx#18022]
Hey,
I came across the referenced issue since I was looking for a solution to get all the names of affected libraries/apps. The solution of using`nx print-affected --type=libs|apps` is rather a temporary one since the `nx print-affected` command will be removed in Nx 18 (see [print-affected](https://nx.dev/packages/nx/documents/print-affected#print-affected)).

Is there any other way to achieve the functionality of `nx print-affected --type=app --base=""`?

Unfortunately, `nx show projects` has no option `type` which would be great.

> Thank you for the hint. 
I changed my command to `nx print-affected --type=app --select=projects` and changed parsing of the resulting string to split by `, ` instead of just ` ` (space). 
Everything works as expected with this again.

_Originally posted by @motabass in https://github.com/nrwl/nx/issues/16676#issuecomment-1532868519_

**Comment by MJez29** [comment]
On a similar note is setting `projectType` in project.json deprecated? I no longer see it mentioned in the [project configuration docs](https://nx.dev/reference/project-configuration)

**Comment by zjkipping** [comment]
I am very interested in this as well. Currently wrapping up a Nx 16 upgrade on my large client project monorepo and wanting to swap our `print-affected` in our CI systems to use `show projects`. This works well for checking based on `target` with the `withTarget` argument, but we also use this system for our versioning setup and only want a list of applications that are affected.

The `show projects` command is honestly a lot better so far in dealing with it then the `print-affected` is, but I feel like we are stepping backwards slightly on the functionality it should have kept from the `print-affected`.

Closest thing I might have is using the `build` target and manually pruning the `library` projects that have a `build` target. Plugins, eslint rules, ect... Though having to do this post processing of this output is rather annoying and prone to falling over.

**Comment by Tramb-dev** [comment]
I don't know if this answer to your need, here what I do in my Azure CI to list all projects affected and store this list in separate variables:
```YAML
- script: |
          projects_list=$(npx nx show projects --type app --affected --base=$(BASE_SHA))
          echo Affected projects: $projects_list
          IFS=$'\n'
          for project_name in $projects_list; do
            echo "##vso[task.setvariable variable=$project_name-exists;isoutput=true]true"
          done
        name: affectedApps
        displayName: Create affected apps variables
```
So I'll have app1-exists and app2-exists variables if theses apps are affected.

**Comment by mjbertenburg** [comment]
Thank you, actually the `--type` option has been added for `nx show projects` in version 17.0.0, as a result I can close actually close this issue. :)
