### ISSUE TITLE
[NestJS] Problem with shutdown application hooks (reopen #9237)

### ISSUE THREAD

**Issue by ecSpl01t** [nrwl/nx#18037]
### Current Behavior

The shutdown hook doesn't support async.
Log:
`onModuleDestroy before wait`

### Expected Behavior

Log:
`onModuleDestroy before wait`
`onModuleDestroy after wait`
`onApplicationShutdown`

### GitHub Repo

https://gist.github.com/mark-b-ab/8f74919944d5dac9330ff864a7ed9f6f

### Steps to Reproduce

1 Create an empty NestJS app using Nx
2 Use [the following AppModule](https://gist.github.com/mark-b-ab/8f74919944d5dac9330ff864a7ed9f6f)
3 [Enable shutdown hooks](https://docs.nestjs.com/fundamentals/lifecycle-events#application-shutdown)
4 Start the app using nx serve
5 Send SIGTERM (Ctrl + C)

### Nx Report

```shell
Node   : 18.12.1
   OS     : darwin-arm64
   npm    : 8.19.2
   
   nx (global)        : 16.5.0
   nx                 : 16.5.0
   @nx/js             : 16.5.0
   @nx/jest           : 16.5.0
   @nx/linter         : 16.5.0
   @nx/workspace      : 16.5.0
   @nx/cypress        : 16.5.0
   @nx/detox          : 16.5.0
   @nx/devkit         : 16.5.0
   @nx/eslint-plugin  : 16.5.0
   @nx/nest           : 16.5.0
   @nx/node           : 16.5.0
   @nx/react          : 16.5.0
   @nx/react-native   : 16.5.0
   @nrwl/tao          : 16.5.0
   @nx/web            : 16.5.0
   @nx/webpack        : 16.5.0
   nx-cloud           : 16.0.5
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jkossis** [comment]
@ecSpl01t @ndcunningham anything on this one? I've been running into this as well, all the way back to when [this issue first came to light](https://github.com/nrwl/nx/issues/9237).

**Comment by kosiakMD** [comment]
I'm facing the same issue, OnModuleDestroy doesn't work
The NestJS App is not being restarted by nx webpack properly after 1-st change, after next changes it "restarts" with 2 (m..b more) instances and cli gives the error that the port is already in use
nx v17/v18
