### ISSUE TITLE
npm create nx-workspace & npx nx generate @nx/angular:application not working

### ISSUE THREAD

**Issue by quickseries** [nrwl/nx#18034]
### Current Behavior

# Unable to create a workspace or app

## Hardware
* MacBook Pro 16"
* Apple M2 Max
* 64 GB memory
* MacOs Sonoma Beta

## Software
* NVM v0.39.3
* Node (does not matter which version) same results

The following commands were executed with different results:

## Scenario 1

On a clean install of NodeJS, running `npm create nx-workspace` creates the project directory correctly, but all sub-folders are empty. In other words, it does not create the angular app and yields the following error.

```sh
npm create nx-workspace

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Where would you like to create your workspace? · qs
✔ Which stack do you want to use? · angular
✔ Standalone project or integrated monorepo? · integrated
✔ Application name · erp
✔ Default stylesheet format · scss
✔ Would you like to use Standalone Components in your application? · Yes
✔ Would you like to add routing? · Yes
✔ Enable distributed caching to make your CI faster · No

 >  NX   Creating your v16.4.3 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✖ Creating your workspace in qs

 >  NX   Failed to create a workspace.

   Error: npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead


npm ERR! code 1
npm ERR! path /Users/justinledoux/dev
npm ERR! command failed
npm ERR! command sh -c -- create-nx-workspace
```

## Scenario 2

After running the above commands, running `npx nx generate @nx/angular:application --name=erp --routing=true --standalone=true --no-interactive --verbose` from inside the `qs` directory yields the following error:

```sh
npx nx generate @nx/angular:application --name=erp --routing=true --standalone=true --no-interactive --verbose

>  NX  Generating @nx/angular:application

Fetching prettier...

up to date, audited 1 package in 621ms

found 0 vulnerabilities

 >  NX   Cannot find module 'prettier'

   Require stack:
   - /Users/justinledoux/dev/qs/node_modules/@nx/devkit/src/utils/package-json.js
   - /Users/justinledoux/dev/qs/node_modules/@nx/devkit/src/generators/to-js.js
   - /Users/justinledoux/dev/qs/node_modules/@nx/devkit/public-api.js
   - /Users/justinledoux/dev/qs/node_modules/@nx/devkit/index.js
   - /Users/justinledoux/dev/qs/node_modules/@nx/angular/src/generators/application/application.js
   - /Users/justinledoux/dev/qs/node_modules/nx/src/config/workspaces.js
   - /Users/justinledoux/dev/qs/node_modules/nx/src/config/configuration.js
   - /Users/justinledoux/dev/qs/node_modules/nx/src/utils/package-manager.js
   - /Users/justinledoux/dev/qs/node_modules/nx/bin/init-local.js
   - /Users/justinledoux/dev/qs/node_modules/nx/bin/nx.js

Error: Cannot find module 'prettier'
Require stack:
- /Users/justinledoux/dev/qs/node_modules/@nx/devkit/src/utils/package-json.js
- /Users/justinledoux/dev/qs/node_modules/@nx/devkit/src/generators/to-js.js
- /Users/justinledoux/dev/qs/node_modules/@nx/devkit/public-api.js
- /Users/justinledoux/dev/qs/node_modules/@nx/devkit/index.js
- /Users/justinledoux/dev/qs/node_modules/@nx/angular/src/generators/application/application.js
- /Users/justinledoux/dev/qs/node_modules/nx/src/config/workspaces.js
- /Users/justinledoux/dev/qs/node_modules/nx/src/config/configuration.js
- /Users/justinledoux/dev/qs/node_modules/nx/src/utils/package-manager.js
- /Users/justinledoux/dev/qs/node_modules/nx/bin/init-local.js
- /Users/justinledoux/dev/qs/node_modules/nx/bin/nx.js
```

No matter what command I use, or even using the VSCode plugin, nothing seems to work.

I've tried installing `prettier` locally and globally without success.

### Expected Behavior

Each of the commands should execute without errors.

### Steps to Reproduce

1. Install MacOS Sonoma Beta
2. Install NVM
3. Install any latest version of NodeJS
4. Run commands detailed in the `Current behaviour`

### Nx Report

```shell
Node   : 18.16.1
   OS     : darwin-arm64
   npm    : 9.8.0

   nx (global)    : 16.5.0
   nx             : 16.5.0
   @nx/js         : 16.5.0
   @nx/jest       : 16.5.0
   @nx/linter     : 16.5.0
   @nx/workspace  : 16.5.0
   @nx/angular    : 16.5.0
   @nx/cypress    : 16.5.0
   @nx/devkit     : 16.5.0
   @nrwl/tao      : 16.5.0
   @nx/webpack    : 16.5.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AndreasZaschka** [comment]
Same for me with version v16.5.3

**Comment by dackyD** [comment]
Same here using nx v16.5.5 and node v16.20

`
$ npx create-nx-workspace@latest

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Where would you like to create your workspace? · angular-mono-16
✔ Which stack do you want to use? · angular
✔ Standalone project or integrated monorepo? · integrated
✔ Application name · web
✔ Default stylesheet format · scss
✔ Would you like to use Standalone Components in your application? · Yes
✔ Would you like to add routing? · Yes
✔ Enable distributed caching to make your CI faster · No

 >  NX   Creating your v16.5.5 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✖ Creating your workspace in angular-mono-16

 >  NX   Failed to create a workspace.

   Error: npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
`

**Comment by Captainnik53** [comment]
Possible duplicate of #18299 ?

**Comment by mandarini** [comment]
@quickseries thanks for reporting this. This is no longer reproducible, so I will be closing this issue. Please retry with latest version, and if it persists, please feel free to ping me and I will reopen and investigate more!
