### ISSUE TITLE
nextjs project unable to import jsx from my libraries after upgrade to 16.5.0

### ISSUE THREAD

**Issue by brandoncollins7** [nrwl/nx#18030]
### Current Behavior

Module parse failed: Unexpected token (27:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| const Badge = ({children, ...otherProps}) => (
>   <StyledRmwcBadge {...otherProps}>{children}</StyledRmwcBadge>
| )

### Expected Behavior

Should compile and run like it did before

### Steps to Reproduce

1.

### Nx Report

```shell
Node   : 18.15.0
   OS     : win32-x64
   pnpm   : 7.32.2

   nx (global)        : 16.1.4
   nx                 : 16.5.0
   @nx/js             : 16.5.0
   @nx/jest           : 16.5.0
   @nx/linter         : 16.5.0
   @nx/workspace      : 16.5.0
   @nx/cypress        : 16.5.0
   @nx/devkit         : 16.5.0
   @nx/esbuild        : 16.5.0
   @nx/eslint-plugin  : 16.5.0
   @nx/nest           : 16.5.0
   @nx/next           : 16.5.0
   @nx/node           : 16.5.0
   @nx/react          : 16.5.0
   @nx/storybook      : 16.5.0
   @nx/vite           : 16.5.0
   @nx/web            : 16.5.0
   @nx/webpack        : 16.5.0
   nx-cloud           : 16.0.5
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-container : 5.0.2
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Hi @brandoncollins7 thank you for filing an issue! Can you please provide a simple reproduction repository? That would be super helpful for us!

**Comment by brandoncollins7** [comment]
Unfortunately my project is very large and I do not know what is is about this version upgrade that would have triggered this issue so I do not know how to produce a smaller project at this time. However I can confirm that this issue also exists when upgrading to 16.4.1.

I am upgrading from 16.2.2.

I will have to skip upgrading for now as I am under a tight deadline and unfortunately don't have any further time to debug this right now:(

**Comment by brandoncollins7** [comment]
Turns out that this issue was because the migration didn't upgrade my nextjs version.... after running a generator to generate a new nextjs project, it upgraded some libs and my app started working fine again
