### ISSUE TITLE
Nx binning - documentation is bit incomplete

### ISSUE THREAD

**Issue by govindappaarun** [nrwl/nx#18042]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/concepts/dte#approach-2:-binning

### Additional context or description

The documentation talks how to achieving binning, but doesn't describe how to use them with CI sys like Jenkins / Circle CI

**Comment by MaxKless** [comment]
Hey @govindappaarun!
Nx doesn't use binning in Nx Cloud, it's just an example of how to do parallelization. We're trying to explain the various approaches to give some rationale to why Nx Cloud is a good solution.
If you're looking to implement binning in your CI pipeline, there's no simple command or anything using Nx.
