### ISSUE TITLE
Rollup config to support also configPlugins

### ISSUE THREAD

**Issue by ThePlenkov** [nrwl/nx#18047]
Rollup CLI supports custom [plugins](https://rollupjs.org/command-line-interface/#configplugin-plugin). However from the code I see that we use hardcoded predefined plugins: https://github.com/nrwl/nx/blob/master/packages/rollup/src/executors/rollup/rollup.impl.ts#L206

What would be nice - if we could have also configPlugins array available as an option for @nx/rollup that's how we can use extra features available for rollup beyond predefined nx plugins.

One of possible use cases - usage of [rollup.config.ts](https://rollupjs.org/command-line-interface/#configplugin-plugin) instead of js with help of @rollup/plugin-typescript plugin.

Could you please add that support?

Thanks!

**Comment by BYREDO777** [comment]
+

**Comment by Jedliu** [comment]
I added a replacement plugin by the code below. 
You can check [docs: Extend/Change the rollup configuration used to build libs](https://github.com/nrwl/nx/issues/2212#top) for your reference.
I hope this helps. Good luck!

File: `rollup.config.js`
```
const replace = require('@rollup/plugin-replace').default;

module.exports = (config) => {
    // console.log('config', JSON.stringify(config, null, 2));
    return {
        ...config,
        output: {
            ...config.output,
            sourcemap: true
        },
        plugins: [
            ...config.plugins,
            replace({
                preventAssignment: true,
                'nxRollup': 'nxRollup2'
            }),
        ]
    }
};
```

And here is the `project.json` config.
```
"build": {
      "executor": "@nx/rollup:rollup",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "main": "packages/nx-rollup/src/index.ts",
        "outputPath": "packages/nx-rollup/dist",
        "tsConfig": "packages/nx-rollup/tsconfig.lib.json",
        "compiler": "tsc",
        "project": "packages/nx-rollup/package.json",
        "format": ["esm", "cjs"],
        "rollupConfig":["packages/nx-rollup/rollup.config.js"],
        "assets": [
          {
            "glob": "packages/nx-rollup/README.md",
            "input": ".",
            "output": "."
          }
        ]
      },
      "configurations": {
        "production": {
          "optimization": true,
          "sourcemap": false,
          "namedChunks": false,
          "extractLicenses": true,
          "vendorChunk": false
        }
      }
    },
```
The important part is 
```
"rollupConfig":["packages/nx-rollup/rollup.config.js"],
```

**Comment by Coly010** [comment]
There seems to be a valid workaround here as you can use a rollup config where you define additional plugins, so I'm going to close this issue.
