### ISSUE TITLE
CLI tutorial link is broken

### ISSUE THREAD

**Issue by Yonet** [nrwl/nx#18055]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[Integrated repo tutorial.](https://nx.dev/tutorials/integrated-repo-tutorial)

### Additional context or description

When creating a new workspace, there is a link for to learn more for first time users that is 404. See images for detail
<img width="786" alt="Screenshot 2023-07-10 at 19 53 30" src="https://github.com/nrwl/nx/assets/3523671/3ba3e199-48f0-45c3-a06d-a5dd71a6e801">

<img width="991" alt="Screenshot 2023-07-10 at 19 52 42" src="https://github.com/nrwl/nx/assets/3523671/2efd31aa-a3a0-4f1c-914f-fcb34d0f21a9">

**Comment by MunchyYDL** [comment]
I guess the correct link to show is: https://nx.dev/getting-started/tutorials/integrated-repo-tutorial
