### ISSUE TITLE
v16.5.0 - can't import from other libs in Cypress CT using Vite

### ISSUE THREAD

**Issue by danr-za** [nrwl/nx#18063]
### Current Behavior

Vite cannot resolve the lib path for imports from other libs, e.g.:
```tsx
import Shared from './shared';
import { Button } from '@vite-cypress/ui'; // <== this one

describe('shared', () => {
  it('should render', () => {
    cy.mount(
      <Shared>
        <Button />
      </Shared>
    );
    cy.get('button').should('be.visible');
  });
});
```

This works if the following paths are removed from `excluded` array in `tsconfig.lib.json`:
```json
  "**/*.cy.ts",
   "**/*.cy.js",
   "**/*.cy.tsx",
   "**/*.cy.jsx"
```

This looks similar to this one https://github.com/nrwl/nx/issues/17257

### Expected Behavior

Should be able to import from other libs

### GitHub Repo

https://github.com/danr-za/vite-cypress-tsconfig

### Steps to Reproduce

1. Clone repo
2. run `nx component-test shared --watch`

### Nx Report

```shell
Node   : 16.17.0
   OS     : darwin-arm64
   npm    : 8.15.0
   
   nx (global)        : 16.0.1
   nx                 : 16.5.1
   @nx/js             : 16.5.1
   @nx/jest           : 16.5.1
   @nx/linter         : 16.5.1
   @nx/workspace      : 16.5.1
   @nx/cypress        : 16.5.1
   @nx/devkit         : 16.5.1
   @nx/eslint-plugin  : 16.5.1
   @nx/react          : 16.5.1
   @nrwl/tao          : 16.5.1
   @nx/vite           : 16.5.1
   @nx/web            : 16.5.1
   typescript         : 5.1.6
```

### Failure Logs

```shell
plugin:vite:import-analysis] Failed to resolve import "@vite-cypress/ui" from "src/lib/shared.cy.tsx". Does the file exist?
/Users/d/projects/vite-cypress/libs/shared/src/lib/shared.cy.tsx:2:23
1  |  import { jsxDEV } from "react/jsx-dev-runtime";
2  |  import Shared from "./shared";
3  |  import { Button } from "@vite-cypress/ui";
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by barbados-clemens** [comment]
this is very strange because I fixed this issue with the nxComponentTestingPreset. 

https://github.com/nrwl/nx/pull/16475 

but might have regressed?

we aren't able to run e2e tests on it because an upstream issue with vite that causes the test to become flaky.
https://github.com/cypress-io/cypress/issues/25913

the tsconfig part is the strange thing to me, as the `cypress/tsconfig.json` should be the file that contains the settings to use.

**Comment by danr-za** [comment]
tried with both the nxPreset and without, unfortunately both produce the same error

**Comment by danr-za** [comment]
Hey @barbados-clemens 
any news about this?
It currently prevents us from upgrading

**Comment by barbados-clemens** [comment]
Nothing new. I did quickly look into this and didn't have any issues with test repos, but something specific about the repo you provided is causing issues. I'll try to look into it more this week.

**Comment by danr-za** [comment]
Awesome thanks!
