### ISSUE TITLE
Nx CLI Add Dependency Documentation Missing

### ISSUE THREAD

**Issue by nathan-moore-97** [nrwl/nx#18072]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

This page does not seem to answer the question "what CLI command do I need to input to add a dependency to my nx repo?"
[Nx Console Add Dependency Command](https://nx.dev/recipes/nx-console/console-add-dependency-command)

Even if this is not the appropriate page for this nx use case, it is still confusing. 
![nx issue](https://github.com/nrwl/nx/assets/27966747/7c88ad8e-ef5b-400e-81e8-099c08b82eb9)

**Comment by MaxKless** [comment]
As you can see in the website title, the page talks about Nx Console, which has a command to install dependencies to your workspace using your package manager.
Other than that, you can just use your package manager yourself to install dependencies. 
What kind of information are you looking for here?
