### ISSUE TITLE
[@nx/js:tsc] Support custom tsconfig paths inline dependencies.

### ISSUE THREAD

**Issue by lucasvieirasilva** [nrwl/nx#18078]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

When the `@nx/js:tsc` executor is configured to `external: none` only root module imports are replaced.

Example:

In the Nx workspace there are 2 `@nx/js` libraries 

1. lib1 (@example/lib1)
2. lib2 (@example/lib2)

With the following `tsconfig.base.json`

```json
{
  ...
  "compilerOptions": {
    ...
    "paths": {
      "@example/lib1": ["libs/lib1/src/index.ts"],
      "@example/lib1/*": ["libs/lib1/*"],
      "@example/lib2": ["libs/lib2/src/index.ts"],
      "@example/lib2/*": ["libs/lib2/*"],
    },
    ...
  },
  ...
}
```

When the `lib2` imports something from `lib1` using specific module path like `@example/lib1/src/some-module`

Example:
```typescript
import { RootExport } from '@example/lib1'
import { MyModule } from '@example/lib1/src/some-module'

...
```

And the `lib2` / `project.json` is configured to use `external: none` as follow:

```json
{
  ...,
  "targets": {
    ...
    "build": {
      "executor": "@nx/js:tsc",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/libs/lib2",
        "main": "libs/lib2/src/index.ts",
        "tsConfig": "libs/lib2/tsconfig.lib.json",
        "assets": ["libs/lib2/*.md"],
        "external": "none"
      }
    },
    ...
  },
  ...
}
```

The generated JavaScript file that imported the `@example/lib1/src/some-module` stays the same, and it should be replaced by the relative path, something like `../../lib1/src/some-module`.

Example:

```javascript
const { RootExport } = require('../../lib1/src')
const { RootExport } = require('@example/lib1/src/some-module')
```

Currently, only modules imported using the root module path (`@example/lib1`) are replaced with the relative path.

The generated JavaScript file should be:

```javascript
const { RootExport } = require('../../lib1/src')
const { RootExport } = require('../../lib1/src/some-module')
```

## Motivation

There are some cases where it's not necessary to export all the modules from the `<projectRoot>/src/index.ts`, for many reasons:

1. Esbuild bundle tree shaking (when you import a specific path the bundle javascript file is smaller).
2. Naming conflicts.

## Suggested Implementation

Change the `updateImports` regex (e.g. `["'](${pathAlias}.*)["']`)

https://github.com/nrwl/nx/blob/cf9f5cbe6a7ce3b916ec6505dc8488f669cbc52b/packages/js/src/utils/inline.ts#L281-L286

And change the `recursiveUpdateImport` function to normalize the import.

Not ideal example (because of the hard-coded `src`)

```typescript
...
function recursiveUpdateImport(
  dirPath: string,
  importRegex: RegExp,
  inlinedDepsDestOutputRecord: Record<string, string>,
  rootParentDir?: string,
) {
        ....
        let targetPath: string | undefined;
        if (result.indexOf('/src') !== -1) {
          const moduleName = result.substring(0, result.indexOf('/src'));
          const modulePath = result.substring(result.indexOf('/src') + 1);
          targetPath = `${inlinedDepsDestOutputRecord[moduleName]}/${modulePath}`;
        } else {
          targetPath = inlinedDepsDestOutputRecord[result];
        }

        if (!targetPath) {
          return matched;
        }

        const importPath = `"${relative(dirPath, targetPath)}"`;
       ...
...
```

**Comment by Bielik20** [comment]
Having the exact same issue. @lucasvieirasilva workaround worked for me, with small adjustment:
```
          const moduleName = result.substring(0, result.indexOf('/src')) + '/*';
```

This `+ '/*'`. 

@leosvelperez I know this is only a workaround but I wanted to ask if there are plans to address this use case? We are using `'/*'` paths almost exclusively for convenience reasons:

* IDE handles refactors better when moving files between libs
* tree shaking is simpler.

We (me and my team) am planning to introduce Nx to the rest of the company. To do so we will have to share some utility code we are currently using in our monorepo. I would like to know upfront how to estimate the effort. If we were to rewrite all the imports it would be a lot of work. Note it is about 6 months+ effort anyway so I am not expecting this to be supported right away, I would just like to know what I can count on.

**Comment by Bielik20** [comment]
@leosvelperez Would you be open to merging PR for that feature? It's been almost a year, and it is a very important issue, especially given that wildcard exports are gaining popularity.

I would be willing to contribute, I will have to either do it here, or create a dirty workaround for our repository, and I would much rather prefer it to be done here for everyone to use.

**Comment by yasinkocak** [comment]
Same issue with another workaround https://github.com/nrwl/nx/issues/7892
