### ISSUE TITLE
Update dotenv to support multiline environment variables.  

### ISSUE THREAD

**Issue by itxch** [nrwl/nx#18089]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Updated the version of `dotenv` in use to the latest version 16.3.1, to support multiline environment variables.

## Motivation
At the moment `nx` uses the `dotenv` library to load environment variables. It's using v10.0.0, (which is around 2 years old) while the current version is v16.3.1. 
The newer versions add multiple new features, most notably support for **multiline environment variables**, which is crucial for loading certificates in PKCS#8 format.

At the moment to get round this you either have to:
1. Manually install and use dotenv within your application, but this has the drawback of not being able to take advantage of nx's auto loading of .env files
2. Use an `overrides` fields within package.json to force all packages to use dotenv 16.3.1. E.g. 
```json
{
  "overrides": {
    "dotenv": "^16.3.1"
  },
}
```
This may, and likely will have unintended side affects.

## Suggested Implementation
Updating the package.json(s) within the nx mono repo and making sure all tests pass.

## Alternate Implementations

N/A

**Comment by Inatiye0911905991** [comment]
-3c0c5d20abc1bd604c849da31c94820e

**Comment by Inatiye0911905991** [comment]
> * [x]  I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))
> 
> ## Description
> Updated the version of `dotenv` in use to the latest version 16.3.1, to support multiline environment variables.
> 
> ## Motivation
> At the moment `nx` uses the `dotenv` library to load environment variables. It's using v10.0.0, (which is around 2 years old) while the current version is v16.3.1. The newer versions add multiple new features, most notably support for **multiline environment variables**, which is crucial for loading certificates in PKCS#8 format.
> 
> At the moment to get round this you either have to:
> 
> 1. Manually install and use dotenv within your application, but this has the drawback of not being able to take advantage of nx's auto loading of .env files
> 2. Use an `overrides` fields within package.json to force all packages to use dotenv 16.3.1. E.g.
> 
> ```json
> {
>   "overrides": {
>     "dotenv": "^16.3.1"
>   },
> }
> ```
> 
> This may, and likely will have unintended side affects.
> 
> ## Suggested Implementation
> Updating the package.json(s) within the nx mono repo and making sure all tests pass.
> 
> ## Alternate Implementations
> N/A

**Comment by Inatiye0911905991** [comment]
> * [x]  I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))
> 
> ## Description
> Updated the version of `dotenv` in use to the latest version 16.3.1, to support multiline environment variables.
> 
> ## Motivation
> At the moment `nx` uses the `dotenv` library to load environment variables. It's using v10.0.0, (which is around 2 years old) while the current version is v16.3.1. The newer versions add multiple new features, most notably support for **multiline environment variables**, which is crucial for loading certificates in PKCS#8 format.
> 
> At the moment to get round this you either have to:
> 
> 1. Manually install and use dotenv within your application, but this has the drawback of not being able to take advantage of nx's auto loading of .env files
> 2. Use an `overrides` fields within package.json to force all packages to use dotenv 16.3.1. E.g.
> 
> ```json
> {
>   "overrides": {
>     "dotenv": "^16.3.1"
>   },
> }
> ```
> 
> This may, and likely will have unintended side affects.
> 
> ## Suggested Implementation
> Updating the package.json(s) within the nx mono repo and making sure all tests pass.
> 
> ## Alternate Implementations
> N/A



> -3c0c5d20abc1bd604c849da31c94820e

**Comment by AgentEnder** [comment]
We are looking at moving to `dotenv-expand`, this may fix this too.

**Comment by itxch** [comment]
> We are looking at moving to `dotenv-expand`, this may fix this too.

That looks really cool - I'd happy to put together a PR implementing that, I assume as part of it we'd also  update `dotenv` to the latest version.
