### ISSUE TITLE
@nx/node:package does not exist

### ISSUE THREAD

**Issue by rogatec** [nrwl/nx#18088]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.
[include-assets-in-build](https://nx.dev/recipes/other/include-assets-in-build#including-assets-in-your-build)

### Additional context or description

When using the described documentation to copy assets to the build path I'll get the following error in the console:
`Unable to resolve @nx/node:package`

the following npm package is installed `"@nx/node": "^16.5.1",`

**Comment by maxkrieger** [comment]
For `@nx/react` I solved it by adding a devDependency: `yarn add -D @nx/react`
