### ISSUE TITLE
Merge multiple jest test result reports

### ISSUE THREAD

**Issue by deser** [nrwl/nx#18092]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
When I run jest tests for multiple project (nx affected or run-many) jest produces multiple test result reports for evert app/lib. 
It will be nice to merge all of these reports into single junit/html file in the monorepo root.

## Motivation
It will make reviewing test failures on CI easier.

**Comment by ziacik** [comment]
Second that, we have to "hack" CI to achieve test reporting, would be nice if this was integrated.

**Comment by deser** [comment]
Could u share?

**Comment by ziacik** [comment]
@deser Well, we have this in `jest.preset.js`

`reporters: process.env["CI"] === "1" ? ["default", ["jest-junit", { outputDirectory: "reports", outputName: `test-${Date.now()}.xml` }]] : ["default"],`

Which creates unique report name for each run.

Then we pass this
`testResultsFiles: reports/test-*.xml`
in our CI test publish task

**Comment by deser** [comment]
Thanks. No way today to put project name to report name?

**Comment by deser** [comment]
Sorry, this is not about test coverage  this is about reporting , see https://jestjs.io/docs/configuration#reporters-arraymodulename--modulename-options

**Comment by deser** [comment]
Btw, @ziacik I found another solution: here's `append` option in https://github.com/Hargne/jest-html-reporter

**Comment by lukket** [comment]
> @deser Well, we have this in `jest.preset.js`
> 
> ```
> reporters: process.env["CI"] === "1" ? ["default", ["jest-junit", { outputDirectory: "reports", outputName: `test-${Date.now()}.xml` }]] : ["default"],
> ```
> 
> Which creates unique report name for each run.
> 
> Then we pass this `testResultsFiles: reports/test-*.xml` in our CI test publish task

Jest also has a parameter `uniqueOutputName` to create unique file names.

**Comment by deser** [comment]
hey @barbados-clemens could u re-open this again? This is not a duplicate of https://github.com/nrwl/nx/issues/10423
