### ISSUE TITLE
enhance enforce project boundaries on directory level

### ISSUE THREAD

**Issue by mikelgo** [nrwl/nx#18098]
## Description
Currently we have the eslint rule `@nx/enforce-module-boundaries` which is already a great possibility to enforce architecture rules on project level. However within the project itself there's right now no possibility to add also some linting rules to prevent imports (e.g. from some directory).

So let's take following project structure: 
```
apps
  shell
libs
  domain-a
    feature (tag: type:feat)
       smart-components (no library, just simple folder)
       ui-components (no lib, just simple folder)
    types (tag: type:types)
    data-access (tag: type:data-access)
    util (tag: type:util)
```

Via `@nx/enforce-module-boundaries` we can restrict that `feat` can depend on `data-access`. However the missing piece would be 
to restrict a rule that within a project tagged with `feat` and files located within `ui-components/**` are not allowed to import e.g. from `data-access`

## Motivation
This would extend the ability to enforce architecture rules even more. 

## Suggested Implementation
```
"@nx/enforce-xxx-boundaries": [
    "error",
    {
      "allow": [],
      // update depConstraints based on your tags
      "depConstraints": [
        {
          "sourceTag": "type:feat",
          "onlyDependOnLibsWithTags": ["type:data-access"],
           // this is new  
          "onlyDependOnDirectories": ["smart-components/**"],
        },

      ]
```

I believe that there are many more possible use cases within the community.

**Comment by meeroslav** [comment]
Thank you, @mikelgo for requesting this.

It has been mentioned already by some of our Nx Champions.

To be honest, this might be a completely separate linter rule that borrows some functionality from the project-based one.
Some of the dependency constraints cannot apply on the folder level so the entire logic needs to be redesigned.

The enforce module boundaries was designed to create boundaries between modules (projects). If two folders represent different modules, perhaps they should be separate projects as well.

While we do have this planned, currently, it has super low priority. If you are using Angular you might want to try out https://github.com/softarc-consulting/sheriff by @manfredsteyer

**Comment by meeroslav** [comment]
Looking at your original issue, I think the best would be to split the feature library into UI lib and data access lib.
This way you can set granular restrictions for UI park and data access part.

Otherwise, this should likely be handled with file globs, which is already mentioned in another issue: https://github.com/nrwl/nx/issues/18151
