### ISSUE TITLE
Couldn't find package "@nx/nx-linux-arm-gnueabihf@16.5.2" required by "nx" on the "npm" registry

### ISSUE THREAD

**Issue by nicholas-paro** [nrwl/nx#18128]
### Current Behavior

running `yarn add nx` fails on error:

```
Couldn't find package "@nx/nx-linux-arm-gnueabihf@16.5.2" required by "nx" on the "npm" registry
```

### Expected Behavior

`nx` should successfully install after running `yarn add nx`

### Steps to Reproduce

1. open terminal
2. run `yarn add nx` OR `npm install nx`
3. see failure happen

### Nx Report

```shell
x
```

### Failure Logs

```shell
yarn workspace v1.22.19
yarn add v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
error Couldn't find package "@nx/nx-linux-arm-gnueabihf@16.5.2" required by "nx" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
error Command failed.
Exit code: 1
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

this issue is failing on `yarn add nx` for both local macOS usage and on a virtual github hosted runner using the latest ubuntu version.

**Comment by nicholas-paro** [comment]
```bash
yarn workspace v1.22.19
yarn add v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
error Couldn't find package "@nx/nx-linux-arm-gnueabihf@16.5.2" required by "nx" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Couldn't find package "@nx/nx-linux-arm64-musl@16.5.2" required by "nx" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "@nx/nx-win32-x64-msvc@16.5.2" required by "nx" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed.
Exit code: 1
```

**Comment by wSedlacek** [comment]
Just noticed this too. But with other packages too like `@ucast/js`

**Comment by nicholas-paro** [comment]
do we know if this an issue that's internal to `nx` and is it something which could be resolved today?

**Comment by kmalone-thescore** [comment]
```

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nx/vite/-/vite-16.1.0.tgz - Not found
npm ERR! 404 
npm ERR! 404  '@nx/vite@https://registry.npmjs.org/@nx/vite/-/vite-16.1.0.tgz' is not in this registry.
```

**Comment by wSedlacek** [comment]
On `main` (working yesterday)
```
ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@nx/react/-/react-16.5.0.tgz: Not Found - 404
```

On update branch for 16.5.2
```
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@nrwl/detox/-/detox-16.5.2.tgz: Not Found - 404
```

Seems to be an issue with npm as both of these seem like they were working earlier today.

**Comment by Lawndlwd** [comment]
same issue here

**Comment by rlindgren** [comment]
`@nx/angular` is currently not found as well

**Comment by bhelzer** [comment]
This seems to affect lot's of packages. Including:

1. npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nx/react/-/react-16.1.0.tgz - Not found
2. Not Found - GET https://registry.npmjs.org/@nx%2fjest - Not found
3. npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nx%2fangular - Not found

**Comment by felipelube** [comment]
There is an unresolved incident at NPM - I think this is impacting us:

![image](https://github.com/nrwl/nx/assets/77070869/89ba2bd1-20a3-4bf8-8db8-1843142303c2)


https://status.npmjs.org/

**Comment by FrozenPandaz** [comment]
As others have mentioned, this is likely a side effect of npm having issues at the moment. Those packages are indeed published so they should continue to work as expected when npm resolves the issues they are currently having.

Thanks everyone!
