### ISSUE TITLE
@nx/web:file-server fails with 'Build target failed' for an Angular app

### ISSUE THREAD

**Issue by vladorbulescu** [nrwl/nx#18131]
### Current Behavior

I have an Nx monorepo that has an Angular app. Trying to run `nx run project-name:serve-static` (which uses the `@nx/web:file-server` executor) fails when trying to build the app.

The app builds just fine by running the same build command, but not through the executor.

Initially, I thought I might have messed something up in my project, but then I tried creating a standalone Angular app by using `create-nx-workspace@latest myngapp --preset=angular-standalone`. It behaves the same there as well, with no change from my side whatsoever, so I'm assuming it's a spread issue.

### Expected Behavior

The executor should build the app and serve the files.

### GitHub Repo

https://github.com/vladorbulescu/myngapp

### Steps to Reproduce

I'll write the steps assuming the GitHub repo above was cloned.

1. Install dependencies
2. Run `nx run myngapp:serve-static` (which fails)
3. Run `nx run myngapp:build` (which works)

### Nx Report

```shell
Node   : 18.15.0
OS     : win32-x64
pnpm   : 8.6.7

nx (global)        : 16.5.1
nx                 : 16.5.2
@nx/js             : 16.5.2
@nx/jest           : 16.5.2
@nx/linter         : 16.5.2
@nx/workspace      : 16.5.2
@nx/angular        : 16.5.2
@nx/cypress        : 16.5.2
@nx/eslint-plugin  : 16.5.2
@nx/web            : 16.5.2
nx-cloud           : 16.0.5
typescript         : 5.1.3
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

I used pnpm, but I also tried npm and both behave the same. I left both lockfiles in the repo.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

I couldn't reproduce it, but I'm not on a Windows machine, so I'm guessing it might be an OS-dependent issue. Do you have access to a non-Windows machine you could try this on and confirm whether it only happens on Windows?

Also, could you share what error you are receiving?
