### ISSUE TITLE
Starting inspector  : address already in use

### ISSUE THREAD

**Issue by limordryer** [nrwl/nx#18134]
### Current Behavior

I created monorepo with 2  apps nest js based , I am trying to run them both  with different ports
nx run-many --all --target=serve
I get the following error for one of them (on nx 15 there was no issue) 

 
 Please help!!!!

### Expected Behavior

Starting inspector
 on localhost:9229 failed: address already in use

### Steps to Reproduce

1.
nx run-many --all --target=serve

### Nx Report

```shell
Node   : 18.16.0
   OS     : win32-x64
   npm    : 9.6.7

   nx                 : 16.5.2  
   @nx/js             : 16.5.2  
   @nx/jest           : 16.5.2  
   @nx/linter         : 16.5.2  
   @nx/workspace      : 16.5.2  
   @nx/devkit         : 16.5.2  
   @nx/eslint-plugin  : 16.5.2  
   @nx/nest           : 16.5.2  
   @nx/node           : 16.5.2  
   @nrwl/tao          : 16.5.2  
   @nx/webpack        : 16.5.2  
   nx-cloud           : 16.1.0  
   typescript         : 5.1.6
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by JoseAntpr** [comment]
We are suffering the same issue all the time. Our operating system is the same. We did the migration from nx 12 and maybe could be something bad in migration ??
