### ISSUE TITLE
Vite plugin should not default to ESNext!

### ISSUE THREAD

**Issue by vicb** [nrwl/nx#18148]
I'm using NX 16.5.1

I broke my app last week for Mac users. Safari <= 16.3.

I got to the bottom of it after a fun debug session...

The problem is this line: https://github.com/nrwl/nx/blob/59f696c85b99cce6583121fcd1845a8c10dfca98/packages/vite/src/utils/options-utils.ts#L160

By default the target is set to `esnext` making it super easy to break people with older safari (in this case) version.

My problem was with static initialization blocks which are only supported on Safari 16.4+

To fix that Nx should **not** set the target when it is not specified in the config. Vite has a reasonable [default](https://vitejs.dev/config/build-options.html#build-target).

Note that the current code has 2 flaws:
- setting the target to `esnext` which makes it very easy to break users,
- also because the `target` is always set there is no way to override it in `vite.config.ts`. It took me a while to understand why updating the `build .target` there had no effect.

/cc @mandarini

**Comment by vicb** [comment]
I believe https://github.com/evanw/esbuild/pull/3167 might have been the change breaking my app after an npm update.

**Comment by mandarini** [comment]
Thanks for this @vicb ! I'll look into it some time this week!

**Comment by mandarini** [comment]
@vicb I will not have time to look at this soon, I'm sorry!

**Comment by vicb** [comment]
@mandarini if you can at least take a quick look at the description and tell me if you think fixing the 2 points I mentioned is worth it, I can probably get to it by then end of the month.

**Comment by mandarini** [comment]
@vicb give me some time I'm looking into it now!

**Comment by mandarini** [comment]
Ok @vicb sorry it turned out to be much simpler than I thought. I just removed the `?? 'esnext'` and I think that should do it! :) Let me know if that does not work for this use case!

**Comment by vicb** [comment]
I think we still need to make sure it can be overridden by a vite config
file.
Setting the key only when the value is defined would for sure work.

**Comment by mandarini** [comment]
@vicb I just checked again, and the `target` you set in vite.config does get passed. If `target` is left undefined in the Nx options, then it reaches Vite as undefined, so the value you set in `vite.config` gets used. If nothing is set in vite.config either, then the default of vite gets used ([_"Vite will replace 'modules' to ['es2020', 'edge88', 'firefox78', 'chrome87', 'safari14']"_](https://vitejs.dev/config/build-options.html#build-target)).

Here are the results from my debugger:

Set `build.target` in `vite.config.ts` to a value - the value is what gets passed in the vite builder:
<img width="1300" alt="Screenshot 2023-08-03 at 12 07 35 PM" src="https://github.com/nrwl/nx/assets/6603745/d9afcf69-1a4f-44fd-9fd6-036d69ebe8ba">

Leave `build.target` undefined in `vite.config.ts` - the value of target is the default of vite:
<img width="1322" alt="Screenshot 2023-08-03 at 12 08 35 PM" src="https://github.com/nrwl/nx/assets/6603745/ddd39bd0-d60b-4faf-bba5-86df9be62c70">

**Comment by vicb** [comment]
Cool, thanks for checking!
