### ISSUE TITLE
[nextjs] output: 'standalone', directory not included in output 

### ISSUE THREAD

**Issue by scottrepreneur** [nrwl/nx#18150]
### Current Behavior

coming from #14112 ([comment](https://github.com/nrwl/nx/issues/14112#issuecomment-1587531644)), experiencing a similar issue still. Opening this issue so it doesn't get lost.

### Expected Behavior

Standalone mode should appropriately create an exported next.js build

### Repro

[Sandbox](https://codesandbox.io/p/github/scottrepreneur/nx-next-standalone/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clisz8ff4000b3b6ocbwzwtg1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clisz8ff4000d3b6ooj1d39ed%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clisz8ff4000b3b6ocbwzwtg1%2522%253A%257B%2522id%2522%253A%2522clisz8ff4000b3b6ocbwzwtg1%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapps%252Fweb%252Fnext.config.js%2522%252C%2522id%2522%253A%2522cliszccvl00p23b6orj2l74ie%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cliszccvl00p23b6orj2l74ie%2522%257D%252C%2522clisz8ff4000d3b6ooj1d39ed%2522%253A%257B%2522id%2522%253A%2522clisz8ff4000d3b6ooj1d39ed%2522%252C%2522activeTabId%2522%253A%2522cliszcv1g00qi3b6oduva1w9h%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cliszb0n100c13b6oahagtdgc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cliszb2xs001mfzg2fixt8q88%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cliszcv1g00qi3b6oduva1w9h%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to Reproduce

1. create new nx/next app from default template
2. set `output: 'standalone'` in the `next.config.js`
3. `$ yarn nx run web:build:production`
4. `$ node dist/apps/web/standalone/server.js`

Standalone dir might be missing (since 16.5). CSS & images (from the default page) will be broken/missing.

### Nx Report

```shell
   Node   : 16.17.0
   OS     : linux-x64
   yarn   : 1.22.19
   
   nx                 : 16.5.2
   @nx/js             : 16.5.2
   @nx/jest           : 16.5.2
   @nx/linter         : 16.5.2
   @nx/workspace      : 16.5.2
   @nx/cypress        : 16.5.2
   @nx/devkit         : 16.5.2
   @nx/eslint-plugin  : 16.5.2
   @nx/next           : 16.5.2
   @nx/react          : 16.5.2
   @nrwl/tao          : 16.5.2
   @nx/web            : 16.5.2
   nx-cloud           : 16.1.0
   typescript         : 5.0.4
```

### Failure Logs

```shell
➜  workspace git:(draft/competent-murdock) ✗ ls
apps               jest.preset.js  package.json        yarn-error.log
babel.config.json  libs            README.md           yarn.lock
dist               node_modules    tools
jest.config.ts     nx.json         tsconfig.base.json
➜  workspace git:(draft/competent-murdock) ✗ cd dist
➜  dist git:(draft/competent-murdock) ✗ ls
apps
➜  dist git:(draft/competent-murdock) ✗ cd apps
➜  apps git:(draft/competent-murdock) ✗ ls
web
➜  apps git:(draft/competent-murdock) ✗ cd web
➜  web git:(draft/competent-murdock) ✗ ls
next.config.js  package.json  public
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Struggling to reproduce the weird directory error from `16.3.2`, but not getting a `standalone` directory all together from `16.5`.

**Comment by ndcunningham** [comment]
I am not sure I understand. 
Are you saying that the `standalone` folder is *not* being generated in your output when you run `nx build` for your `nextjs` app?
Or does it create the `standalone` folder, but when you run `node [path-to-standalone-server.js]` and view the app on the browser, it looks broken?

**Comment by ndcunningham** [comment]
The standalone directory will *not* be listed at the root of your build.
It is inside nextjs' generated directory `.next` folder.

```shell
❯ tree -al -L 2
.
└── nextjs-standalone-test
    ├── .next
    │   ├── BUILD_ID
    │   ├── app-build-manifest.json
    │   ├── app-path-routes-manifest.json
    │   ├── build-manifest.json
    │   ├── cache
    │   ├── server
    │   ├── standalone
    │   └── ...
    ├── .nx-helpers
    ├── next.config.js
    ├── package.json
    └── public
```
