### ISSUE TITLE
Support Nx commands to run from any workspace folder

### ISSUE THREAD

**Issue by lucasvieirasilva** [nrwl/nx#18154]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Currently, when you run the Nx build command from a workspace sub-folder it throws an exception:

```text
Compiling TypeScript files for project "lib1"...
error TS6059: File '/Users/myuser/Projects/issues/nx/any-folder/packages/lib1/src/index.ts' is not under 'rootDir' 'packages/lib1'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Root file specified for compilation
../lib1/src/index.ts:1:15 - error TS6059: File '/Users/myuser/Projects/issues/nx/any-folder/packages/lib1/src/lib/lib1.ts' is not under 'rootDir' 'packages/lib1'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Imported via './lib/lib1' from file '/Users/myuser/Projects/issues/nx/any-folder/packages/lib1/src/index.ts'
    Root file specified for compilation

1 export * from './lib/lib1';
                ~~~~~~~~~~~~
```

I understand that's working as intended, however, sometimes is confusing to the developer that is new in the Nx world that's the expected behavior.

That said, I guess Nx should notify (terminal warning) or change the `cwd` when the command is not executed at the workspace root.

Steps to reproduce:

1. `npx create-nx-workspace any-folder`
2. `cd any-folder/`
3. `npx nx g @nrwl/js:library --name=lib1`
4. `npx nx g @nrwl/js:library --name=lib2`
5. Import lib1 from lib2 `import { lib1 } from '@any-folder/lib1';` (`packages/lib2/src/lib/lib2.ts`)
6. `cd packages/lib2`
7. `npx nx build lib2 --verbose --skip-nx-cache`

## Motivation

New Nx users could get confused with this behavior.

## Suggested Implementation

A warning message or change the `cwd` when the command is not executed at the workspace root.

**Comment by AgentEnder** [comment]
Nx commands should support this already. If you are noticing an issue, it should be considered a bug. I'll change this over.
