### ISSUE TITLE
Support projectRoot and workspaceRoot interpolation for cwd

### ISSUE THREAD

**Issue by Elyahou** [nrwl/nx#18158]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
When using `run-commands` executor with cwd of the project path or some subfolder of it, it would be very useful to have `{projectRoot}` interpolation to avoid setting manually these path.

## Motivation
- Avoid mistakes in paths
- Add ability to set project root cwd from the targets default in `nx.json` file.

**Comment by AgentEnder** [comment]
`targetDefaults` supports this already for all options - we are looking at support in the general case as well.

**Comment by AgentEnder** [comment]
This is released now 🎉
