### ISSUE TITLE
Azure Pipelines Setup Incorrect Yaml

### ISSUE THREAD

**Issue by joshd-7** [nrwl/nx#18170]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?
https://nx.dev/recipes/ci/monorepo-ci-azure

### Additional context or description
The yaml build on the setup page is not valid with the current Azure pipelines.
The format is incorrect and looks like the usage is also incorrect in multiple areas.

**Comment by kklocker** [comment]
Related / duplicate? #17172
