### ISSUE TITLE
Unable to use nx package across libs

### ISSUE THREAD

**Issue by rpanigra18** [nrwl/nx#18199]
### Current Behavior

Project structure

Root
---Apps
            -----App1
            -----App1-e2e
---Libs
            -----Lib1
            -----Lib2
            -----test-cypress

I have a test-cypress core package that is laid out similar to other packages under libs folder. When I try to import the lib that is defined in tsconfig.base.json as @test/test-cypress in my App1-e2e, I am getting a webpack compilation error

Interestingly, when I use the relative path with "../,../" it works.

Does any one know why are my libs not importable ?

All of this worked prior to the dependency upgrade our team did on the entire project. We also upgraded from 7.x Cypress to 12.x.

Thanks

### Expected Behavior

Nx libs should be importable.

### Steps to Reproduce

1
Libs export is not working.

### Nx Report

```shell
NA
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by barbados-clemens** [comment]
@rpanigra18 do you have a repo I can look at?

as this should _just work_ assuming the tsconfig.base.json work and the tsconfig.json being used by cypress is extending that tsconfig.base.json. 

example repo: https://github.com/barbados-clemens/cy-shared-lib
