### ISSUE TITLE
How to integrate with Loopback4

### ISSUE THREAD

**Issue by hack2024** [nrwl/nx#1821]
Hi! is possible to integrate Loopback4 into nx workspace?

Thanks!

**Comment by vsavkin** [comment]
I'm not really familiar with loopback. Let me describe how our Node.js support works now to see if it answers your question.

- We have `@nrwl/node`, `@nrwl/express`, and `@nrwl/nest` packages. 
- They all use the same builders to run and build applications. The only difference between them is the schematics they use to generate applications.
- If the builders we have work for you, create a custom workspace schematic should be easy.
- If the builders don't work for you, you can build your own builder that wrap the loopback cli. It's not super hard, but requires some work. Nex.js builders are a good place to look. 

Does it answer your question? If not, could you provide more details?

Thanks!

**Comment by codephobia** [comment]
Have also been looking into using Loopback 4 with Nx. Did you have any luck with getting it working @hack2024 ?

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by Cethy** [comment]
nice.

**Comment by quicksilverr** [comment]
Hey, are there any updates on this? @FrozenPandaz @codephobia @vsavkin

**Comment by zscott** [comment]
I am also trying to get this to work. Any updates would be helpful. Thanks

**Comment by Cethy** [comment]
@zscott @quicksilverr For what it worth : with LB4, i'm using yarn workspaces instead and it works like a charm. :man_shrugging:

**Comment by quicksilverr** [comment]
Hey Guys, I've created a [simple package](https://www.npmjs.com/package/nx-loopback) for now...works with nx and loopback 

Thanks to @Cethy and @codephobia
