### ISSUE TITLE
Nx Cloud DTE doesn't deduplicate tasks

### ISSUE THREAD

**Issue by Bielik20** [nrwl/nx#18237]
### Current Behavior

Let's say you have two project:
* **api** 
  * with deploy target
* **api-e2e** 
  * with e2e target that dependsOn: ['^deploy']

When you run:
```
parallel-commands-on-agents: |
  npx nx affected --target=e2e --parallel=3
  npx nx affected --target=deploy --parallel=3
```

Nx Cloud will schedule `api:deploy` twice. Once from _affected-deploy_ and the second one from _affected-e2e-dependsOn_.

This not only is redundant but will fail in case of a AWS CloudFormation because you cannot have two deployments of the same resource running in parallel.

### Expected Behavior

When multiple sources are to run the same target it should be deduplicated.

### Steps to Reproduce

Follow the setup from "Current Behaviour". Id doesn't have to be deployment, it can be something simple.

### Nx Report

```shell
Node   : 18.16.0
   OS     : darwin-arm64
   npm    : 9.5.1

   nx                 : 16.5.0
   @nx/js             : 16.5.0
   @nx/jest           : 16.5.0
   @nx/linter         : 16.5.0
   @nx/workspace      : 16.5.0
   @nx/devkit         : 16.5.0
   @nx/eslint-plugin  : 16.5.0
   @nx/plugin         : 16.5.0
   @nrwl/tao          : 16.5.0
   @nx/webpack        : 16.5.0
   nx-cloud           : 16.0.5
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @ns3/nx-core       : 4.2.2
   @ns3/nx-serverless : 4.2.2
   ---------------------------------------
   Local workspace plugins:
   	 @argus/workspace-plugin
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Ah, I see. This isn't something that's something the nx cloud side of things get access to. Lets back out from the github actions flow to get an idea of why that's not feasible.

This is essentially the same as having two separate terminals, and running `npx nx affected --target=e2e --parallel=3` inside one, and `npx nx affected --target=deploy --parallel=3` in the other. Its 2 separate instances of your tasks runner, two separate process etc.

The solution would be to instead do something like:
```yaml
parallel-commands-on-agents: |
  npx nx affected --target=e2e,deploy --parallel=3
```
