### ISSUE TITLE
Prettier markdown support

### ISSUE THREAD

**Issue by maxime1992** [nrwl/nx#1824]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Running `yarn run format:write --all` should run prettier on Markdown files

## Current Behavior

It does on ts files, scss etc but not on markdown ones

### Steps to Reproduce

1. Create a markdown file into an nx repo
2. write a double space between 2 words
3. run `yarn run format:write --all` (it should remove the double space)

### Context

Please provide any relevant information about your setup:

- version of Nx used: 8.4.12
- 3rd-party libraries and their versions: prettier 1.18.2

**Comment by FrozenPandaz** [comment]
Can you please retry with the latest version of Nx? Nx now formats md files

If you still encounter this issue, you please provide a reproduction of this issue?

**Comment by FrozenPandaz** [comment]
Closing this issue as I'm quite certain this issue has been resolved and no reproduction of the issue has been produced. If you encounter this issue in the future, please open a new issue.
