### ISSUE TITLE
prettier@3+ integration or declare strict version dependency

### ISSUE THREAD

**Issue by pascalmann** [nrwl/nx#18252]
Nx ([@nx/workspace](https://npmjs.com/package/@nx/workspace) and [@nx/devkit](https://npmjs.com/package/@nx/devkit)) use Prettier@2 to format files without declare it in package.json.

When Prettier@3 is referenced in a project, Nx still use this depency and fail by calling the new async format function.

- upgrading to Prettier@3
or
- declare a strict version dependence

**Comment by AgentEnder** [comment]
Prettier v3 should be fully supported at this time. If anyone is experiencing issues after updating please open a new issue. We will migrate existing repos soon, in the meantime anyone should be able to update via `npm i --save-dev prettier@latest`
