### ISSUE TITLE
Lazy loaded library in unused blocked of code adds to main.js bundle

### ISSUE THREAD

**Issue by zmara** [nrwl/nx#18251]
### Current Behavior

Two libraries: LibA, LibB... LibA is imported in App.module, LibB is imported via import in unused method. 
Lodash is imported in LibB, so we are testing if it affects main.js

`import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

@NgModule({
  imports: [CommonModule],
})
export class Group1LibAModule {
  constructor() {
  }

  ha() {
    // this line adds to mains.js another 30kb
    const promise = import('@xx/group1/libB');
  }
}`

Example repo: https://github.com/zmara/xx

### Expected Behavior

It should be lazy. Unused method and unresolved promise should not add to final main.js bundle.

### Steps to Reproduce

1. Create nx monoreport with angular (not standalone)
2. generate two libraries, A and B
3. Add and use lodash in lib B, add lib A to app.module, add unused method lazy import of lib B to lib A
4. Test adding and removing lodash import and how it affects main.js bundle

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.1
   OS     : win32-x64
   npm    : 9.5.1

   nx                 : 16.5.5
   @nx/js             : 16.5.5
   @nx/jest           : 16.5.5
   @nx/linter         : 16.5.5
   @nx/workspace      : 16.5.5
   @nx/angular        : 16.5.5
   @nx/cypress        : 16.5.5
   @nx/devkit         : 16.5.5
   @nx/eslint-plugin  : 16.5.5
   @nrwl/tao          : 16.5.5
   @nx/web            : 16.5.5
   @nx/webpack        : 16.5.5
   typescript         : 5.1.6
   ---------------------------------------
   Local workspace plugins:
         @xx/group1/libA
         @xx/group1/libB
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

    "@angular/animations": "~16.1.0",
    "@angular/common": "~16.1.0",
    "@angular/compiler": "~16.1.0",
    "@angular/core": "~16.1.0",
    "@angular/forms": "~16.1.0",
    "@angular/platform-browser": "~16.1.0",
    "@angular/platform-browser-dynamic": "~16.1.0",
    "@angular/router": "~16.1.0",
    "@angular-devkit/build-angular": "~16.1.0",
    "@angular-devkit/core": "~16.1.0",
    "@angular-devkit/schematics": "~16.1.0",
    "@angular-eslint/eslint-plugin": "~16.0.0",
    "@angular-eslint/eslint-plugin-template": "~16.0.0",
    "@angular-eslint/template-parser": "~16.0.0",
    "@angular/cli": "~16.1.0",
    "@angular/compiler-cli": "~16.1.0",
    "@angular/language-service": "~16.1.0",

**Comment by Coly010** [comment]
Hey :)

This isn't a problem with Nx.

This is an issue with Angular itself. I was able to reproduce this here: https://github.com/Coly010/ng-lodash-treeshake-issue

You should open this issue on the Angular GitHub Repo: https://github.com/angular/angular-cli
