### ISSUE TITLE
How to setup HMR for a React app

### ISSUE THREAD

**Issue by andreasasprou** [nrwl/nx#1826]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

- HMR for components in a React application or a library
- HMR for redux reducers

## Current Behavior

No HMR

**Comment by jaysoo** [comment]
@andreasasprou Thanks for the question. We currently don't support HMR, only livereload.

We'll look into adding it for the future so please stay tuned.

**Comment by nemanjamilosavljevic-newtron** [comment]
There's another issue with the same topic. Just wanted to link them for further reference https://github.com/nrwl/nx/issues/1881
