### ISSUE TITLE
Node v20 test runner

### ISSUE THREAD

**Issue by CyanoFresh** [nrwl/nx#18276]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Node internal test runner is stable now and much faster & lightweight than other test runners (e.g. jest). @nx/node should support it as a test runner.

Link to node docs: https://nodejs.org/api/test.html

## Motivation

Faster & more optimised development workflows and CI builds

**Comment by barbados-clemens** [comment]
Hi @CyanoFresh, currently Nx supports LTS where the node test runner isn't marked stable and some features, like `watch` are still aren't stable. So we don't want to add a this feature _just yet_ but is something we are keeping an eye on as it looks like a great choice for node based projects.
