### ISSUE TITLE
@nrwl/next build does not treeshake @nrwl/next library

### ISSUE THREAD

**Issue by astrodomas** [nrwl/nx#18271]
### Current Behavior

Currently I have 2 client components exported from my `@mylib/next` but if I import 1 client component via `index` to my app then my bundlesize increases if it is a direct import - then it decreases.

Can this be due to `SWC`?

```
// Increased bundle size
// apps/next-app/pages/carousel

import { MyCarousel } from '@mylib/next'

export const page = () => <MyCarousel />

export default page;
```

```
'use client'
// Reduced bundle size
// apps/next-app/pages/carousel
import { MyCarousel } from '@mylib/next/components/Carousel'

export const page = () => <MyCarousel />

export default page;

```

Root index:
```
'use client'
// libs/my-lib/src/index.ts
export * from './client'
```

Components index:
```
// libs/my-lib/src/components/index.ts
export * from './Carousel'
```

Component index:
```
// libs/my-lib/src/components/Carousel/index.ts
export * from './Carousel'
export {default as MyCarousel} from './Carousel'
```

## Before direct import:
![image](https://github.com/nrwl/nx/assets/134293602/4d10c1d5-9363-4ee9-96d1-f4aede681217)

### Expected Behavior (after direct import)

The bundlesize should be reduced:
![image](https://github.com/nrwl/nx/assets/134293602/7bf22c12-f904-4abf-a526-bcf3da973dc0)

### Steps to Reproduce

1. Create a `@nx/next` application
2. Create a `@nx/next` library
3. Create 2 heavy components inside the library
4. Export them to a single `index.ts`
5. Import a component into a next.js app page
6. After importing - run the build with bundle analyzer to see the bundlesize of each page
7. Change the import path to be a direct component path
8. After the change - run the build again and the bundlesize should be reduced

### Nx Report

```shell
$ npx nx report
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : win32 x64
   npm    : 9.5.1
   Hasher : Native
   
   nx                 : 16.2.1
   @nx/js             : 16.2.1
   @nx/jest           : 16.2.1
   @nx/linter         : 16.2.1
   @nx/workspace      : 16.2.1
   @nx/cypress        : 16.2.1
   @nx/devkit         : 16.2.1
   @nx/eslint-plugin  : 16.2.1
   @nx/next           : 16.2.1
   @nx/react          : 16.2.1
   @nx/rollup         : 16.2.1
   @nx/storybook      : 16.2.1
   @nrwl/tao          : 16.2.1
   @nx/web            : 16.2.1
   @nx/webpack        : 16.2.1
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @nxkit/style-dictionary : 3.0.1
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by astrodomas** [comment]
Any news on this?

**Comment by victorcarvalhosp** [comment]
I'm facing the exact same issue at work. Our First Load JS becomes bigger than 1mb in case we import just a single component from a shared library

**Comment by astrodomas** [comment]
Still persistent as of `nx v17.2.0`. By changing imports got a huge bundlesize improvement
![image](https://github.com/nrwl/nx/assets/134293602/36db874c-5ca3-498a-99ff-8b0718b25199)
![image](https://github.com/nrwl/nx/assets/134293602/027d678b-cae3-4ed2-a1a3-c8fb71d9b26d)

**Comment by victorcarvalhosp** [comment]
> Still persistent as of `nx v17.2.0`. By changing imports got a huge bundlesize improvement ![image](https://private-user-images.githubusercontent.com/134293602/291610263-36db874c-5ca3-498a-99ff-8b0718b25199.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTc3ODAsIm5iZiI6MTcwMjk5NzQ4MCwicGF0aCI6Ii8xMzQyOTM2MDIvMjkxNjEwMjYzLTM2ZGI4NzRjLTVjYTMtNDk4YS05OWZmLThiMDcxOGIyNTE5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxNDUxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmIyNzI2NThhMGEyYjQ0YmI0M2U4Mzc5N2QxMTkyZTY0NTYwYmI3YTMwNTkzM2I1MTk0MjA2MWI1NjhiMmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0U6dVbnBHEQyMQjFCqYNVDgdePBxCL7-9_emtV5xKNE) ![image](https://private-user-images.githubusercontent.com/134293602/291610976-6495d377-3361-4c80-9a9f-6584111dd29a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTc3ODAsIm5iZiI6MTcwMjk5NzQ4MCwicGF0aCI6Ii8xMzQyOTM2MDIvMjkxNjEwOTc2LTY0OTVkMzc3LTMzNjEtNGM4MC05YTlmLTY1ODQxMTFkZDI5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxNDUxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDIxMDk3NDYzOTUwNzU1NDgyOGRiZTg5ZmFlZjU4NDA2NDg5ZGE5YmRlYzkwNDdmMjc0ODJjNDJjZDM4MzdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ooK0eIcuLGrm0AN5dZjYtgml9SUuRx9AJ1Ge84BqYww)

Not related to the issue itself, but I was not able to sent you a private message. How were you able to set this % of Budget that you're showing in the first screenshot?

**Comment by astrodomas** [comment]
> > Still persistent as of `nx v17.2.0`. By changing imports got a huge bundlesize improvement ![image](https://private-user-images.githubusercontent.com/134293602/291610263-36db874c-5ca3-498a-99ff-8b0718b25199.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTc3ODAsIm5iZiI6MTcwMjk5NzQ4MCwicGF0aCI6Ii8xMzQyOTM2MDIvMjkxNjEwMjYzLTM2ZGI4NzRjLTVjYTMtNDk4YS05OWZmLThiMDcxOGIyNTE5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxNDUxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmIyNzI2NThhMGEyYjQ0YmI0M2U4Mzc5N2QxMTkyZTY0NTYwYmI3YTMwNTkzM2I1MTk0MjA2MWI1NjhiMmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0U6dVbnBHEQyMQjFCqYNVDgdePBxCL7-9_emtV5xKNE) ![image](https://private-user-images.githubusercontent.com/134293602/291610976-6495d377-3361-4c80-9a9f-6584111dd29a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTc3ODAsIm5iZiI6MTcwMjk5NzQ4MCwicGF0aCI6Ii8xMzQyOTM2MDIvMjkxNjEwOTc2LTY0OTVkMzc3LTMzNjEtNGM4MC05YTlmLTY1ODQxMTFkZDI5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxNDUxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDIxMDk3NDYzOTUwNzU1NDgyOGRiZTg5ZmFlZjU4NDA2NDg5ZGE5YmRlYzkwNDdmMjc0ODJjNDJjZDM4MzdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ooK0eIcuLGrm0AN5dZjYtgml9SUuRx9AJ1Ge84BqYww)
> 
> @astrodomas Not related to the issue itself, but I was not able to send you a private message. How were you able to set this % of Budget that you're showing in the first screenshot?

This is a PR comment generated by the bot

By using https://github.com/hashicorp/nextjs-bundle-analysis , specifically the setup for app router described here:
https://github.com/hashicorp/nextjs-bundle-analysis/issues/83 . But basically it takes nextjs app router build, inside the master branch it uploads an artifact to github and then compares the PR's bundlesize to the masters bundlesize and makes a PR comment on the bundlesize.
