### ISSUE TITLE
Can't add new phases to project[name].architect

### ISSUE THREAD

**Issue by Offtree** [nrwl/nx#1828]
## Expected Behavior
After following the cookbook example: https://connect.nrwl.io/app/cookbook/1BarpEG6zfxCv4evBvJSWi 
adding a "deploy" option to a single projects architect scripts, I'd expect to be able to run:
```
nx run project:lint
nx run project:build
nx run project:deploy
```
all successfully.

## Current Behavior

What is the current behavior?

Instead, I get a schema validation error that doesn't let me run any of the standard commands, but does let me run the new deploy command.

## Failure Information

```
~/D/foo❯❯❯ ng run project-name:build                                                                                                                                               ⏎
An unhandled exception occurred: Workspace config file cannot be loaded: /bar/Documents/foo/angular.json
Schema validation failed with the following errors:
  Data path ".projects['project-name']" should NOT have additional properties(deploy).
See "/private/var/folders/xq/x65sypp96lqd59t092r_4zc5pzmrq7/T/ng-bpr7eF/angular-errors.log" for further details.


// contents of the error log file
[error] Error: Workspace config file cannot le loaded: /Documents/foo/angular.json
Schema validation failed with the following errors:
  Data path ".projects['project-name']" should NOT have additional properties(deploy).
    at Object.getWorkspace (/Documents/foo/node_modules/@angular/cli/utilities/config.js:59:15)
    at RunCommand.validateScope (/Documents/foo/node_modules/@angular/cli/models/command.js:97:60)
    at RunCommand.validateAndRun (/Documents/foo/node_modules/@angular/cli/models/command.js:122:24)
    at Object.runCommand (/Documents/runt/node_modules/@angular/cli/models/command-runner.js:185:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

follow this cookbook example in a new angular workspace https://connect.nrwl.io/app/cookbook/1BarpEG6zfxCv4evBvJSWi

**Comment by vsavkin** [comment]
@Offtree thank you for opening this issue! could you provide an example repo?

**Comment by Offtree** [comment]
Holy smokes, asking for an example repo is always the way to go.

I feel like a doofus and had the deploy command on the wrong part of the schema on one of my projects. No issues running deploy after fixing that! Looking forward to experimenting more with nx, thanks for responding!
