### ISSUE TITLE
add support for the new eslint flat configuration

### ISSUE THREAD

**Issue by robertIsaac** [nrwl/nx#18285]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
eslint has a [new flat configuration](https://eslint.org/docs/latest/use/configure/configuration-files-new)
but this doesn't work currently with nx lint

## Motivation
the new flat configuration already has better IDE support (at least with WebStorm), and it will be the default starting with ESLint 9.0

## Suggested Implementation
to work same way eslint work
1. check if `ESLINT_USE_FLAT_CONFIG` environment variable exist and if yes then true will use flat, no won't use it.
2. check in the project root if there is `eslint.config.js` file, if yes to use flat, if not then won't use it.

## Alternate Implementations
to add a new executor `@nx/linter:eslint-flat` and the developers needs to manually change it to use it

## reproduce repo
this is [sample project](https://github.com/robertIsaac/nx-eslint-flat-config) with flat configuration and the problems it has now is

the output says it all

```
PS C:\Users\rober\WebstormProjects\nx-eslint-flat-config\ui> eslint **/*.ts
PS C:\Users\rober\WebstormProjects\nx-eslint-flat-config\ui> nx lint       

> nx run ui:lint


Linting "ui"...

Error: You have attempted to use a lint rule which requires the full TypeScript type-checker to be available, but you do not have `parserOptions.project` configured to point at your project tsconfig.json files in the relevant TypeScript file "overrides" block of your project ESLint config `ui/.eslintrc.json`

Please see https://nx.dev/guides/eslint for full guidance on how to resolve this issue.


 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Ran target lint for project ui (922ms)

    ×    1/1 failed
    √    0/1 succeeded [0 read from cache]

   View structured, searchable error logs at https://nx.app/runs/YneE1wZewN
```

I opened it as a feature not a bug, because I don't see in the docs you say you support the new flat configuration, but feel free to make it a bug

**Comment by robertIsaac** [comment]
I see there are some implementation 
https://github.com/nrwl/nx/blob/master/packages/linter/src/executors/eslint/lint.impl.ts#L47
so I think it should be a bug then

**Comment by meeroslav** [comment]
The support is added and the issue with using outdates eslint version is fixed.

The converter is in progress here: https://github.com/nrwl/nx/pull/17532

**Comment by robertIsaac** [comment]
> The support is added and the issue with using outdates eslint version is fixed.
> 
> The converter is in progress here: #17532

glad to see good progress here
