### ISSUE TITLE
Performance Issue - Nx lint taking longer than ng lint after migrating Angular repo to Nx

### ISSUE THREAD

**Issue by shivom2k** [nrwl/nx#18297]
### Current Behavior

Nx lint is taking noticeably longer than ng lint for the same executor, despite there being no discernible code differences.

### Expected Behavior

Nx lint should have a comparable execution time to ng lint for the same executor and codebase. Since Nx is designed to optimize and speed up development workflows, the linting process should not incur such a significant performance overhead.

### Steps to Reproduce

1. Create a new Nx workspace or migrate an existing Angular repository to Nx.
2. Run `ng lint` to lint the project using the standard Angular CLI linting.
3. Run `nx lint` with the same executor configuration and observe the execution time.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

   Node : 18.16.0
   OS   : win32 x64
   npm  : 9.5.1

   nx               : 15.7.0
   @nrwl/jest       : 15.9.4
   @nrwl/linter     : 15.9.4
   @nrwl/workspace  : 15.7.0
   @nrwl/angular    : 15.9.4
   @nrwl/cli        : 15.7.0
   @nrwl/cypress    : 15.9.4
   @nrwl/devkit     : 15.9.4
   @nrwl/js         : 15.9.4
   @nrwl/nx-plugin  : 16.5.5
   @nrwl/tao        : 15.7.0
   @nrwl/webpack    : 15.9.4
   typescript       : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngrx/effects              : 15.3.0
   @ngrx/store                : 15.3.0
   @nx/webpack                : 16.2.1
   rxjs                       : 6.6.7
   @ng-bootstrap/ng-bootstrap : 14.0.1
   @ngrx/store-devtools       : 15.3.0
   @reef/fwk                  : 4.0.0-pr-60.2
   ngx-build-plus             : 15.0.0
   ---------------------------------------
   The following packages should match the installed version of nx   
     - @nrwl/jest@15.9.4
     - @nrwl/linter@15.9.4
     - @nrwl/angular@15.9.4
     - @nrwl/cypress@15.9.4
     - @nrwl/devkit@15.9.4
     - @nrwl/js@15.9.4
     - @nrwl/nx-plugin@16.5.5
     - @nrwl/webpack@15.9.4

   To fix this, run `nx migrate nx@16.5.5`
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I recently migrated my Angular repository to Nx in order to take advantage of its powerful capabilities for monorepo management. However, I've noticed a significant performance degradation with Nx lint compared to ng lint. Nx lint is taking approximately twice as long as ng lint for the same executor, even though there are no apparent code differences.

The executor is `@angular-eslint/builder:lint`

**Comment by meeroslav** [comment]
The linter executor you refer to is a third-party executor, which we do not maintain. The `nx` team has `@nrwl/linter:eslint` executor that is recommended.

Your `nx report` reports a version mismatch between `nx` packages. Please fix that using the suggested command and see if the error persists. Also, you are using a fairly old version of `nx`. Migrate at least to the latest `15.x` version.

**Comment by shivom2k** [comment]
using @nx/linter:eslint (@nx/linter in the 16.x versions) also there is no improvement in performance


 current nx report  
Node: 18.16.0
   OS     : win32 x64
   npm    : 9.5.1
   Hasher : Native

   nx (global)      : 16.2.2
   nx               : 16.0.0
   @nx/js           : 16.0.0
   @nrwl/js         : 16.0.0
   @nrwl/jest       : 16.0.0
   @nrwl/linter     : 16.0.0
   @nx/workspace    : 16.0.0
   @nrwl/workspace  : 16.0.0
   @nx/angular      : 16.0.0
   @nrwl/angular    : 16.0.0
   @nx/cypress      : 16.0.0
   @nrwl/cypress    : 16.0.0
   @nx/devkit       : 16.0.0
   @nrwl/devkit     : 16.0.0
   @nrwl/tao        : 16.0.0
   @nx/webpack      : 16.0.0
   @nrwl/webpack    : 16.0.0
   typescript       : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngrx/effects              : 15.3.0
   @ngrx/store                : 15.3.0
   rxjs                       : 6.6.7
   @ng-bootstrap/ng-bootstrap : 14.0.1
   @ngrx/store-devtools       : 15.3.0
   @reef/fwk                  : 4.0.8
   ngx-build-plus             : 15.0.0

**Comment by JamesHenry** [comment]
@shivom2k I'm afraid these are still outdated versions of these dependencies across the board.

We can take a deep look into a reproducible issues once you are up to date with both the Angular and Nx side of things. I created and maintain angular-eslint, and I work for Nx, so I'm in a good position to be able to do so. But it won't be possible for us to go back to specific older versions and troubleshoot them.

**Comment by meeroslav** [comment]
Can you replace your `@angular-eslint/builder:lint` with `@nx/linter:eslint` and if that is still significantly slower, we would need a repo where we can see this.

Also, to be more precise, what does "noticeably slower" in this case mean? Can you provide the average run duration with one and the other? You can use [hyperfine](https://github.com/sharkdp/hyperfine) to automate this.
