### ISSUE TITLE
Forked process task runner is stripping blank log lines

### ISSUE THREAD

**Issue by mattfysh** [nrwl/nx#18290]
### Current Behavior

Tasks using the forked process task runner have their stdio piped through `strong-log-transformer` before piping into the console. This transformer is causing blank log lines to be stripped. For example, when running a test suite using the `@nx/vite:test` executor, putting a `console.log('X\n\nY')` in a test case causes the output:

```
X
Y
```

The implementation of this behaviour is located here:

https://github.com/nrwl/nx/blob/master/packages/nx/src/tasks-runner/forked-process-task-runner.ts#L176-L177

### Expected Behavior

The output from the example above should be:

```
X

Y
```

Blank log lines are significant in almost all circumstances, and should not be stripped by the task runner

### GitHub Repo

https://github.com/mattfysh/nx-strips-loglines

### Steps to Reproduce

1. `git clone https://github.com/mattfysh/nx-strips-loglines`
2. `cd nx-strips-loglines`
3. `pnpm install`
4. `nx test mylib`
5. observe the blank line is stripped from log output

### Nx Report

```shell
Node   : 20.5.0
   OS     : darwin-arm64
   pnpm   : 8.6.10
   
   nx (global)        : 16.5.5
   nx                 : 16.5.5
   @nx/js             : 16.5.5
   @nx/linter         : 16.5.5
   @nx/workspace      : 16.5.5
   @nx/eslint-plugin  : 16.5.5
   @nx/vite           : 16.5.5
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

In the example above, the content printed to stdout exists within the test case. If you assume the content to be printed is under the users control, and easy fix might be to suggest putting a "." or space character on the blank line to preserve it

However, please consider the content being printed to stdout is not typically owned by the developer who is printing to stdout

**Comment by jaysoo** [comment]
This has been fixed in the latest Nx release and no longer an issue.
