### ISSUE TITLE
The option --target should be available for both :libs and :apps

### ISSUE THREAD

**Issue by dianjuar** [nrwl/nx#1830]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

## Expected Behavior

The parameter ` --target` is not present on `affected:libs` or `affected:apps`. It exists for all the stuff in your workspace `nx affected --target=deploy` but is going "deploy" my apps and libraries and if I want only deploy my libraries and I can't do that.

The option `--target` should available for both `:libs` and `:apps`

## Current Behavior

When I run `nx affected:libs --target=deploy` or `nx affected:apps --target=deploy`

![image](https://user-images.githubusercontent.com/7026066/64743805-f1643480-d4c6-11e9-986c-ef1ac7335efa.png)

And nothing more happens. Should run the `deploy` architect of my libraries or apps

#### For projects 
1. run `nx affected:apps --target=deploy`

#### For libraries
1. Have a library in your workspace
2. run `nx affected:libs --target=deploy`

### Context

- version of Nx used
   - 8.5.0

## Other

I'm trying to use a new feature of the Angular CLI, [`ng deploy`](https://angular.schule/blog/2019-08-ng-deploy) to only deploy the libraries with [ngx-deploy-npm](npmjs.com/ngx-deploy-npm)

**Comment by FrozenPandaz** [comment]
This makes sense.

Would somebody be interested in contributing this feature?

**Comment by ashbrener** [comment]
I am having the same issue. I need to use the deploy target to publish libs to npm.

**Comment by dianjuar** [comment]
> Would somebody be interested in contributing this feature?

I would love to do so

**Comment by dianjuar** [comment]
Any recommendations for my adventure besides to the [`CONTRIBUTING.md`](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md) guidelines and [How to contribute to Nx Video](https://www.youtube.com/watch?v=o11p0zSm0No&feature=youtu.be) @FrozenPandaz ?

**Comment by FrozenPandaz** [comment]
Sorry, I thought you were only expecting those projects to be printed when I first read the issue.

In regards to being able to "deploy" libs and apps separately, I think it makes more sense to give them different target names.

The way I see it, apps get _deployed_ to a hosting service while libs more specifically get _published_ to a registry. Thus, I would call the target `"publish"`. You might not be able to use `ng deploy` as you want... but you can use `nx publish` because we accept any target name. You can also use the more verbose `ng run proj-name:publish` or `nx run proj-name:publish`. Having separate target names means that you can use `nx affected --target publish` to publish affected projects to npm and `nx affected --target deploy` to deploy affected projects to a hosting service.

Sorry for the confusion.

**Comment by dianjuar** [comment]
> Sorry, I thought you were only expecting those projects to be printed when I first read the issue.
> 
> In regards to being able to "deploy" libs and apps separately, I think it makes more sense to give them different target names.
> 
> The way I see it, apps get _deployed_ to a hosting service while libs more specifically get _published_ to a registry. Thus, I would call the target `"publish"`. You might not be able to use `ng deploy` as you want... but you can use `nx publish` because we accept any target name. You can also use the more verbose `ng run proj-name:publish` or `nx run proj-name:publish`. Having separate target names means that you can use `nx affected --target publish` to publish affected projects to npm and `nx affected --target deploy` to deploy affected projects to a hosting service.
> 
> Sorry for the confusion.

Sorry about the delay.

I know that _publish_ has a lot more sense than _deploy_ but I'm not pretty sure if that's possible, in Angular, [the deployers builders](https://angular.io/guide/deployment#automatic-deployment-with-the-cli) pretty used across the framework, I think your suggestion is the right way to go though.

---

@JohannesHoppe @mgechev I would like to have your feedback on this, do you think is possible to have our builders with all the features if we just change the name of _deploy_ to _publish_?

**Comment by JohannesHoppe** [comment]
You can call it as you want, if you use the old builder syntax:

`ng run your-angular-project:publish`

But "deploy" is super generic, I don't see a reason why we can't deploy to a registry. The docker "deploy" schematic is not a "publish" to docker, too.

**Comment by dianjuar** [comment]
Very good point, also the world  _deploy_ is already on the Angular Community, change it for another one could lead into a confusion of what it does.
