### ISSUE TITLE
importing library generator breaks NX plugin test cases

### ISSUE THREAD

**Issue by sonikasharma1403** [nrwl/nx#18303]
### Current Behavior

Create a generator and use `import { libraryGenerator } from '@nrwl/angular/generators';`
`  await libraryGenerator(host, {
      name: schema.name + '/app',
      directory: options.directory,
      linter: Linter.None,
      simpleModuleName: false
    });`

try to now add test cases for this wrapper generator.

Notice that the test cases breaks with 
<img width="742" alt="image" src="https://github.com/nrwl/nx/assets/86649832/c8b481e9-617f-488a-9ced-44371d69c6c9">

### Expected Behavior

Should not break test cases

### Steps to Reproduce

Create a generator and use `import { libraryGenerator } from '@nrwl/angular/generators';`
`  await libraryGenerator(host, {
      name: schema.name + '/app',
      directory: options.directory,
      linter: Linter.None,
      simpleModuleName: false
    });`

try to now add test cases for this wrapper generator.

Notice that the test cases breaks with 
<img width="742" alt="image" src="https://github.com/nrwl/nx/assets/86649832/c8b481e9-617f-488a-9ced-44371d69c6c9">

### Nx Report

```shell
Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : darwin x64
   yarn : 1.22.10
   
   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/angular           : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/nx-plugin         : 15.7.2
   @nrwl/storybook         : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/webpack           : 15.7.2
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngrx/effects        : 15.3.0
   @ngrx/router-store   : 15.3.0
   @ngrx/store          : 15.3.0
   @ngrx/store-devtools : 15.3.0
   @storybook/angular   : 6.5.16
   @torque/nx-plugin    : 11.0.0-build.12
   ng-mocks             : 14.6.0
   nx-stylelint         : 13.4.0
   ---------------------------------------
   Local workspace plugins:
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by sonikasharma1403** [comment]
@AgentEnder  - any update on this?

**Comment by Coly010** [comment]
I can't reproduce this on latest Nx. 

Can you try this again with the latest version of Nx? And can you also provide a reproduction repo?

`nx migrate latest && nx migrate --run-migrations`

**Comment by Coly010** [comment]
Hi @sonikasharma1403 

thanks, I did try that and it worked fine, could you try again on latest and provide a repo with a reproduction
