### ISSUE TITLE
migrations for package '@nrwl/angular' cause an error

### ISSUE THREAD

**Issue by admir86** [nrwl/nx#1831]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

## Expected Behavior

when running `ng update @nrwl/angular @nrwl/workspace` the migration should work or emit better error in the log.

e.g: Invalid Version: ^8.3.3, Version x.x.x required of package x

## Current Behavior

running `ng update @nrwl/angular @nrwl/workspace` cause an error:
```
** Executing migrations for package '@nrwl/angular' **
Invalid Version: ^8.3.3
```
I'm updating from:
```
Name                                  Version                  Command to update
-----------------------------------------------------------------------------------
@angular/cdk                          8.0.2 -> 8.2.0           ng update @angular/cdk
@angular/cli                          8.3.3 -> 8.3.4           ng update @angular/cli
@nrwl/angular                         8.2.0 -> 8.5.0           ng update @nrwl/angular
@nrwl/workspace                       8.2.0 -> 8.5.0           ng update @nrwl/workspace
```
Same error even if I update angilar/cli to latest before updating @nrwl/...

**Comment by jdpearce** [comment]
Thanks for raising this issue!

This looks to be a bug in the way the migration is using `semver` : 

https://github.com/nrwl/nx/blob/14da0ff4b224b27b0075369126956dbbd55c022e/packages/angular/src/migrations/update-8-5-0/upgrade-cli-8-3.ts#L20

A temporary workaround would be to edit the version in your `package.json` to remove the caret (e.g. `^8.3.3` -> `8.3.3`) _before_ you call `ng update`.
