### ISSUE TITLE
Regression in @nx/js@16.5.3

### ISSUE THREAD

**Issue by rosslavery** [nrwl/nx#18311]
### Current Behavior

Configuration is a Node / Express app that is served using @nx/js and has a `buildTarget` that uses `@nx/esbuild`.

The project it's building has a `typeorm` dependency, meaning we use a custom `esbuildConfig` and use the [esbuild-plugin-tsc](https://github.com/thomaschaaf/esbuild-plugin-tsc) plugin to compile with support for `emitDecoratorMetadata` by using `tsc` under the hood when needed.

After updating to `@nx/js@16.5.3`, the build succeeds but execution fails with errors that seem to indicate `emitDecoratorMetadata` didn't work properly.

Downgrading to `@nx/js@16.5.2` fixes this.

### Expected Behavior

For the app to serve without errors. See repro below.

### GitHub Repo

https://github.com/rosslavery/nx-js-regression

### Steps to Reproduce

# Broken Example (16.5.3)
1. Clone example repo
2. Switch to branch `16.5.3`
3. `pnpm install`
4. `pnpm nx serve broken-node`
5. Observe error `ColumnTypeUndefinedError: Column type for ExampleEntity#name is not defined and cannot be guessed. Make sure you have turned on an "emitDecoratorMetadata": true option in tsconfig.json.`

# Working Example (16.5.2)
1. Clone example repo
2. Switch to branch `16.5.2`
3. `pnpm install`
4. `pnpm nx serve broken-node`
5. Observe server starts / rebuilds without issue

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.13.0
   OS     : win32-x64
   pnpm   : 8.6.10

   nx                 : 16.5.3
   @nx/js             : 16.5.3
   @nx/jest           : 16.5.3
   @nx/linter         : 16.5.3
   @nx/workspace      : 16.5.3
   @nx/angular        : 16.5.3
   @nx/cypress        : 16.5.3
   @nx/devkit         : 16.5.3
   @nx/esbuild        : 16.5.3
   @nx/eslint-plugin  : 16.5.3
   @nx/node           : 16.5.3
   @nx/react          : 16.5.3
   @nrwl/tao          : 16.5.3
   @nx/web            : 16.5.3
   @nx/webpack        : 16.5.3
   nx-cloud           : 16.1.0
   typescript         : 5.1.3
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 16.0.0
   @ngrx/effects         : 16.0.0
   @ngrx/entity          : 16.0.0
   @ngrx/router-store    : 16.0.0
   @ngrx/store           : 16.0.0
   @ngrx/store-devtools  : 16.0.0
```

### Failure Logs

```
ColumnTypeUndefinedError: Column type for ExampleEntity#name is not defined and cannot be guessed. Make sure you have turned on an "emitDecoratorMetadata": true option in tsconfig.json.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Very likely related to [this PR](https://github.com/nrwl/nx/pull/18145).

**Comment by rosslavery** [comment]
As an update here -- adding `runBuildTargetDependencies: true` to the project's `serve-app` target resolves this issue -- although it feels like a breaking change (?).

**Comment by Maxim-Mazurok** [comment]
Same issue, here's my project config, your workaround helped, cheers!

```json
{
  "name": "analyze",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "packages/analyze/src",
  "projectType": "library",
  "targets": {
    "build": {
      "executor": "@nx/js:tsc",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/packages/analyze",
        "main": "packages/analyze/src/index.ts",
        "tsConfig": "packages/analyze/tsconfig.lib.json",
        "assets": [],
        "outputFileName": "src/index.js"
      }
    },
    "lint": {
      "executor": "@nx/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["packages/analyze/**/*.ts"]
      }
    },
    "test": {
      "executor": "@nx/vite:test",
      "outputs": ["{workspaceRoot}/coverage/packages/analyze"],
      "options": {
        "passWithNoTests": true,
        "reportsDirectory": "../../coverage/packages/analyze"
      }
    },
    "run": {
      "executor": "@nx/js:node",
      "options": {
        "buildTarget": "analyze:build",
        "watch": false,
        "runBuildTargetDependencies": true // HAD TO ADD THIS
      }
    },
    "spell-check": {
      "executor": "@nx/nx-stuff:spell-check"
    }
  },
  "tags": []
}
```

**Comment by Maxim-Mazurok** [comment]
Keeping it active
