### ISSUE TITLE
@nx/esbuild: excludeLibsInPackageJson is not removing lib packages referenced by the package being built

### ISSUE THREAD

**Issue by luiz290788** [nrwl/nx#18346]
### Current Behavior

Trying to run `@nx/esbuild:esbuild` to build bundle one application before adding it to a container.

I want to install the minimal dependencies inside of the container. So I'm using the `"generatePackageJson": true` to generate the `package.json` with `"excludeLibsInPackageJson": true`.

But the lib dependencies referenced in the package being built are still in the package.json. The lib dependencies of other dependencies are not included which is good. 

### Expected Behavior

Remove all lib dependencies from package.json so I can install only the external dependencies inside of the container.

### Steps to Reproduce

1. Create a monorepo with two packages, one lib and one app
2. Configure `@nx/esbuild` to build the app using: `"generatePackageJson": true` and `"excludeLibsInPackageJson": true`.
3. Build the app.
4. Verify that the libs are still in the generated package.json.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.1
   OS     : darwin-arm64
   npm    : 9.5.1
   
   nx             : 16.5.5
   @nx/js         : 16.5.5
   @nx/jest       : 16.5.5
   @nx/linter     : 16.5.5
   @nx/workspace  : 16.5.5
   @nx/devkit     : 16.5.5
   @nx/esbuild    : 16.5.5
   @nx/plugin     : 16.5.5
   @nrwl/tao      : 16.5.5
   nx-cloud       : 16.1.1
   typescript     : 5.1.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by luiz290788** [comment]
It is still happening in 16.6.0 and now it does not generate the lock file anymore.

**Comment by jaysoo** [comment]
@luiz290788 Can you try with 16.7.4, and use `"thirdParty": true` when configuring `@nx/esbuild:esbuild` for the project. If you're still having issues can you provide a repro for us to investigate?
