### ISSUE TITLE
Unresponsive Next.js application when using "nx serve"

### ISSUE THREAD

**Issue by gbrlmngr** [nrwl/nx#18347]
### Current Behavior

Serving a Next.js 13.4 application using `nx serve` would work well, on the first serve, but any subsequent modifications to the code (on hot reload) would render the entire application unresponsive, prompting the browser window to freeze. The terminal shows that the client and server bundles has been compiled successfully in a relatively normal time (200ms-1s on my machine, although I haven't benchmarked previous Next.js app runs).

I have also noticed that the machine (Macbook Air M1 2020) would start to heat up suddenly, hinting to a memory leak (maybe?).

This is happening on both Mozilla Firefox and Google Chrome browsers (no noticeable difference between the two).

### Expected Behavior

Hot reload should not crash the application.

### Steps to Reproduce

1. `npm install -D @nx/next`
2. `nx g @nx/next:app ui`
3. `nx serve ui`
4. Modify any component/page and notice the compilation is successful
5. Check the browser window for unresponsiveness

### Nx Report

```shell
Node   : 18.15.0
   OS     : darwin-arm64
   npm    : 9.5.0
   
   nx (global)        : 16.2.1
   nx                 : 16.5.5
   @nx/js             : 16.5.5
   @nx/jest           : 16.5.5
   @nx/linter         : 16.5.5
   @nx/workspace      : 16.5.5
   @nx/cypress        : 16.5.5
   @nx/devkit         : 16.5.5
   @nx/eslint-plugin  : 16.5.5
   @nx/nest           : 16.5.5
   @nx/next           : 16.5.5
   @nx/node           : 16.5.5
   @nx/react          : 16.5.5
   @nrwl/tao          : 16.5.5
   @nx/vite           : 16.5.5
   @nx/web            : 16.5.5
   @nx/webpack        : 16.5.5
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This seems to affect the versions 13.4+ of Next.js. I haven't experienced this thing with older version, on the same machine, using Nx.

**Comment by ndcunningham** [comment]
Hi, I tried to reproduce your issue on the latest version of Nx and I am not experiencing any unresponsiveness or freezing inside the browser.
Could you provide a small repo?

**Comment by gbrlmngr** [comment]
Hello @ndcunningham,

Sorry for replying so late. Unfortunately, I cannot send the repro repository, yet, but I've experimented a bit with it and the issue might be caused by using `emotion` with the new App Router. AFAIK, `emotion` might not currently be supported by the App Router because it conflicts with the server components or `use client` directives.

Given the new findings, I guess we can close this. I'll re-open if I'll encounter the issue under different conditions (i.e. not with the combination of `emotion` and App Router), if that's the case, though.

Thank you!

**Comment by gbrlmngr** [comment]
Closing with "not reproducible".
