### ISSUE TITLE
Question:  Guidance on importing 3rd party libraries that have a forRoot() method call in Libs?

### ISSUE THREAD

**Issue by tommyc38** [nrwl/nx#1835]
I wanted to ensure I import 3rd party libs that have a call to forRoot() correctly in Nx Lib modules.  For example, I needed rich text editing capabilities with my own custom @Mention implementation.  I chose to go with QuillJs and found an angular package to use it, Ngx-Quill.  I have a shared Nx Lib and created a new module, MentionsModule, in it which wraps around Ngx-Quill's editor component.  However, Ngx-Quill expects that you will import their module into your root application in order to use it, in which case you use QuillModule.forRoot() (which essentially sets up global config defaults).  All of my Feature Libs will import from Shared Lib / Mentions Module whenever I need text editing and not QuillModule directly.

Going back to my question, I need to add QuillModule in my MentionModule's imports to use it....BUT, do I use the QuillModule.forRoot() or import it as QuillModule and then in my App Root Module import QuillModule.forRoot()? Or, is it fine to import QuillModule.forRoot() in MentionModule with no further QuillModule imports into App Root Module or Feature Lib Module?  How do I handle these scenarios correctly?

**Comment by brandonroberts** [comment]
Thank @tommyc38, this question would be better answered on StackOverflow, or by referencing the forRoot/forFeature Angular docs
