### ISSUE TITLE
Migration failure: Project '@nrwl/workspace' could not be found in workspace.

### ISSUE THREAD

**Issue by wKovacs64** [nrwl/nx#1838]
## Expected Behavior

I would expect the `migrate` command to migrate my workspace from 8.4.10 to 8.5.0.

## Current Behavior

```sh
$ nx migrate @nrwl/workspace
Project '@nrwl/workspace' could not be found in workspace.
```

### Steps to Reproduce

1. Enter an existing 8.4.10 (or 8.4.13, maybe others) workspace. (Alternatively, generate a new 8.4.10 workspace. Choose `empty` and `nx` at the prompts.)
2. Follow the [Updating Nx](https://nx.dev/react/guides/update) instructions by trying to generate a `migrations.json` file by running `nx migrate @nrwl/workspace`.
3. Observe the following error: `Project '@nrwl/workspace' could not be found in workspace.`

### Context

- Workspace originally created with Nx 8.4.10, discovered issue when attempting to update to 8.5.0
- Simplified reproduction repository (freshly created with 8.5.0, downgraded to 8.4.10 purely to demonstrate the migration issue): https://github.com/wKovacs64/nx-migration-test

### Failure Logs

```
Project '@nrwl/workspace' could not be found in workspace.
```

## Other

Not sure what else may be helpful. Feel free to request additional information.

**Comment by jdpearce** [comment]
Thanks for raising the issue, @wKovacs64 - confirmed! 

Creating a brand new empty workspace with `npx create-nx-workspace@8.4.10` (choose `empty` and `nx`) does indeed show create a workspace that uncovers this bug 😰

**Comment by asherccohen** [comment]
I also run into this issue when trying to upgrade from 8.5.0 to 8.5.1:
`$ nx migrate @nrwl/workspace code-tank-monorepo
'.' is not recognized as an internal or external command,
operable program or batch file.
\node_modules\yargs\yargs.js:1133 else throw err`

**Comment by wKovacs64** [comment]
That's funny, I was just logging a new issue for that. 🙂 

#1882

**Comment by vsavkin** [comment]
The migrate command is still very experimental, but we are getting there.

I fixed the known issues in 8.5.2 and tested it out. So migrating from 8.5.2 should work well.

I'll keep this issue open to make sure upgrading from 8.5.2 to 8.5.3 works well.

**Comment by wKovacs64** [comment]
@vsavkin 8.5.2 to 8.6.0 failed trying to upgrade `@nrwl/angular` (which isn't even in our project, as we don't use Angular):

```
npm ERR! notarget No matching version found for @nrwl/angular@8.5.3
```

Let me know if you'd like a new issue.

**Comment by vsavkin** [comment]
Yeah. Sorry about it. We hit a bunch of issues with the migrate command, so the easiest way to make it work is to:

```
npm install --save-dev @nrwl/workspace@8.9.0
nx migrate @nrwll/workspace@8.9.0 --from='@nrwl/workspace:8.5.2' 
``` 

In this case you will use the fixed version of the migrate command but will still run all the migrations.

**Comment by vsavkin** [comment]
Folks. I'm going to close this issue due to inactivity. We fixed a few migration-related problems since December. If you find any that are still present, please open another issue and we will take a look asap. Thank you!
