### ISSUE TITLE
repair CLI command docs are lacking

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [nrwl/nx#18385]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

I just learned that `nx repair` exists and don't know what _"repair"_ means in the context of Nx. The CLI command docs page neither explains what it is nor links to an explanation. The closest sentence to an explainer is:

> Repair any configuration that is no longer supported by Nx.

### Is there a specific documentation page you are reporting?

https://nx.dev/packages/nx/documents/repair

### Additional context or description

I'd be happy to send a PR if given a pointer or two 🙂

**Comment by AgentEnder** [comment]
Hey @JoshuaKGoldberg 👋 

The repair command runs every migration within the `nx` package itself against the current repository. The idea being that the migrations are all idempotent, and would fix any configuration left behind if a developer updates to a later Nx version without using `nx migrate`.

I'd love to see a PR, if you are up for it. I think the updates would all be in:
- packages/nx/src/command-line/repair/command-object.ts
