### ISSUE TITLE
NX React Library Build Does not work with Vite apps

### ISSUE THREAD

**Issue by MalikBagwala** [nrwl/nx#18383]
### Current Behavior

I have a buildable and publishable library called `grass-core` and when I try using `nx build` the output file includes `process.env` which is not supported by vite, This use to work in nx 15 so I am sure what changed.

![image](https://github.com/nrwl/nx/assets/23068029/502364c6-4628-4306-b329-81c23aab05c9)

NX Version - v16.5.5

### Expected Behavior

The output file should not contain `process` to make it more compatible with other build systems.

### Steps to Reproduce

1. Upgrade to nx 16.5.5
2. Build a React Library (with `@nrwl/rollup` builder)
3. Check out the outputed js file

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.16.0
   OS     : linux-x64
   yarn   : 1.22.19
   
   nx (global)        : 16.5.5
   nx                 : 16.5.5
   @nx/js             : 16.5.5
   @nx/jest           : 16.5.5
   @nx/linter         : 16.5.5
   @nx/workspace      : 16.5.5
   @nx/cypress        : 16.5.5
   @nx/devkit         : 16.5.5
   @nx/esbuild        : 16.5.5
   @nx/eslint-plugin  : 16.5.5
   @nx/next           : 16.5.5
   @nx/plugin         : 16.5.5
   @nx/react          : 16.5.5
   @nx/rollup         : 16.5.5
   @nx/storybook      : 16.5.5
   @nrwl/tao          : 16.5.5
   @nx/vite           : 16.5.5
   @nx/web            : 16.5.5
   @nx/webpack        : 16.5.5
   typescript         : 5.1.6
   ---------------------------------------
   Local workspace plugins:
   	 @vesatogo/workspace-plugin
   	 @vesatogo/grass-scrollarea
   	 @vesatogo/grass-carousel
   	 @vesatogo/grass-dropzone
   	 @vesatogo/grass-assets
   	 @vesatogo/nextjs-utils
   	 @vesatogo/grass-dates
   	 @vesatogo/grass-login
   	 @vesatogo/grass-table
   	 @vesatogo/grass-core
   	 @vesatogo/constants
   	 @vesatogo/graphql
   	 @vesatogo/hooks
   	 @vesatogo/state
   	 @vesatogo/utils
   	 @vesatogo/auth
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Hi there @MalikBagwala ! Do you want to try what we suggest in the docs and see if it fixes your issue? https://nx.dev/recipes/react/use-environment-variables-in-react#for-react-applications-using-vite

**Comment by MalikBagwala** [comment]
@mandarini I am using a buildable library built using rollup in a Vite application created with create vite app so the above instructions do not apply in my case.

**Comment by meeroslav** [comment]
@MalikBagwala can you provide a small repo where this can be reproduced?

**Comment by meeroslav** [comment]
I think @jaysoo might be the right person to help with this.
