### ISSUE TITLE
root .env is not loading.

### ISSUE THREAD

**Issue by nicezic** [nrwl/nx#18391]
### Current Behavior

https://nx.dev/recipes/tips-n-tricks/define-environment-variables

./.env file is not loading.
only ./apps/my-app/.env is loading.

### Expected Behavior

https://nx.dev/recipes/tips-n-tricks/define-environment-variables

the root ./.env file should be loaded.

### Steps to Reproduce

1. create nestjs apps.
2. make ./.env file at root and set variable.
3. load it from the app.

### Nx Report

```shell
$ nx report
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.1
   OS     : linux-x64
   npm    : 9.5.1
   
   nx (global)        : 16.5.5
   nx                 : 16.5.5
   @nx/js             : 16.5.5
   @nx/jest           : 16.5.5
   @nx/linter         : 16.5.5
   @nx/workspace      : 16.5.5
   @nx/devkit         : 16.5.5
   @nx/eslint-plugin  : 16.5.5
   @nx/nest           : 16.5.5
   @nx/node           : 16.5.5
   @nrwl/tao          : 16.5.5
   @nx/webpack        : 16.5.5
   nx-cloud           : 16.1.1
   typescript         : 5.1.6
   ---------------------------------------
   Local workspace plugins:
         @yhpark-nx/auth
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information
1. it was working preview nx version.

**Comment by nicezic** [comment]
I don't know why. but... it read now... cache problem?
Anyone know why?

**Comment by fernandomunizz89** [comment]
I have the same problem.

Basically it doesn't load the environment variables even after clearing the cache.

**Comment by AgentEnder** [comment]
I'm not sure why you would have hit this, but if its not happening now and we can't repro it I'm going to go ahead and close this issue. If it comes back up feel free to open a new report.
