### ISSUE TITLE
CLI generate component command not working with SCSS schematics

### ISSUE THREAD

**Issue by vash72** [nrwl/nx#1839]
# Prerequisites

- [ ] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Before

in angular.json i added:
```
"schematics": {

>   "@nrwl/angular:component": {
>     "styleext": "scss"
>   }

},
```

## Expected Behavior

when i run the command:

    ng generate component <niceName> 

it will create a component with **scss** file as style file

## Current Behavior

when i run the command:

    ng generate component <niceName> 

it create a component with **css** file as style file

### Context

Please provide any relevant information about your setup:

```
   "@nrwl/angular": "8.4.6",

   "@angular/cli": "8.1.1",
```

may be a regression? -> https://github.com/nrwl/nx/issues/1617

**Comment by mehrad-rafigh** [comment]
Hi @vash72 . 
I took a look and it does not seem to be a regression. The offending line in the original issue has been fixed and still says @nrwl/angular
You can take a look here 
https://github.com/nrwl/nx/blob/fa05f1171a7dc09e3fb695d94b098f142f14562e/packages/angular/src/schematics/application/application.ts#L486

**Comment by jdpearce** [comment]
@vash72 - I've just tried this with the latest `@nrwl/angular` and it seems to work as expected.  Are you able to update and try again?

**Comment by vash72** [comment]
Yes , update alone @nrwl/angular to 8.5.0 fixed the problem
