### ISSUE TITLE
Creating a next.js application on an existing workspace fails with workspace_1.addPackageWithinit is not a function

### ISSUE THREAD

**Issue by asherccohen** [nrwl/nx#1840]
## Expected Behavior

I can create a next.js application on an existing workspace

## Current Behavior

I add next.js capabilities to my workspace and try to create an application. It fails with error "workspace_1.addPackageWithinit is not a function"

## Failure Information (for bugs)

This bug affects existing workspaces. Workaround is to create a new clean workspace and then next works as expected.

### Steps to Reproduce

1. cd into an existing workspace's root folder
2. add next capabilities with yarn add --dev @nrwl/next
3. try to create a new application with nx g @nrwl/next:app tuskdesk
4. Select what styling you want to use
5. error workspace_1.addPackageWithinit is not a function appears

### Context

Please provide any relevant information about your setup:

- version of Nx used: "@nrwl/workspace": "8.4.13",
- 3rd-party libraries and their versions:     "@nrwl/next": "^8.5.0",

### Failure Logs

workspace_1.addPackageWithinit is not a function

**Comment by jdpearce** [comment]
Hi @asherccohen, thanks for raising this. Can you retry with the latest Nx, please? Next support was only just released with Nx 8.5.0.

**Comment by asherccohen** [comment]
Sure, latest Nx resolved this issue!Thanks.

**Comment by vsavkin** [comment]
Great. Closing this issue.
