### ISSUE TITLE
Issue with Webpack v5 Overlay Feature Not Working as Expected

### ISSUE THREAD

**Issue by jaimepater** [nrwl/nx#18411]
### Current Behavior

The overlay feature in Webpack, which should be enabled by default using the Webpack v5 notation, seems to be using the Webpack v4 notation instead, as evident from the code in get-dev-server-config.ts (https://github.com/nrwl/nx/blob/master/packages/webpack/src/executors/dev-server/lib/get-dev-server-config.ts#L79). This discrepancy in notation might cause the overlay feature to not work as expected.

### Expected Behavior

The overlay feature should work as intended, following the Webpack v5 configuration (https://webpack.js.org/configuration/dev-server/), enabling the overlay to display error messages or warnings when there are issues during development, providing a better development experience for users.

### Steps to Reproduce

1.

### Nx Report

```shell
nx : 15.4.8
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.8
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.8
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.8
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.8
   @nrwl/js : Not Found
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.4.8
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.8
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.4.8
   @nrwl/web : 15.4.8
   @nrwl/webpack : 15.4.8
   @nrwl/workspace : 15.4.8
   @nrwl/vite : 15.4.8
   typescript : 4.8.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I am not using the lasted version of nx but I reviewed the code on master and sees that it is using the V4 notation 
https://github.com/nrwl/nx/blob/master/packages/webpack/src/executors/dev-server/lib/get-dev-server-config.ts#L79

**Comment by Vgbire** [comment]
Hello, when can this problem be fixed
