### ISSUE TITLE
Hash value inconsistency between local and pipeline (Jenkins) despite identical commit number and node version

### ISSUE THREAD

**Issue by shivom2k** [nrwl/nx#18412]
### Current Behavior

I have encountered a perplexing issue in our Nx workspace where the hash value of a specific project differs between my local development environment and our pipeline (Jenkins), even though both are on the same commit and using the same Node.js version.

Despite following the same commit and Node.js version, the hash value of the built artifact differs between the local development environment and the Jenkins pipeline.

### Expected Behavior

The hash value of the built artifact should be the same both locally and in the Jenkins pipeline when using the same commit number and Node.js version.

### Steps to Reproduce

1. Clone the Nx workspace to your local machine.
2. Check out the latest commit on the master branch.
3. Ensure that your Node.js version matches the one used in the Jenkins pipeline.
4. Run the command nx build <project-name> on your local machine.
5. Compare the hash value of the built artifact with the one produced by the Jenkins pipeline for the same project

### Nx Report

```shell
Node   : 18.16.0
   OS     : win32 x64
   npm    : 9.5.1
   Hasher : Native
   
   nx (global)      : 16.2.2
   nx               : 16.0.0
   @nx/js           : 16.0.0
   @nrwl/js         : 16.0.0
   @nx/jest         : 16.5.5
   @nrwl/jest       : 16.0.0
   @nx/linter       : 16.5.5
   @nrwl/linter     : 16.0.0
   @nx/workspace    : 16.0.0
   @nrwl/workspace  : 16.0.0
   @nx/angular      : 16.0.0
   @nrwl/angular    : 16.0.0
   @nx/cypress      : 16.0.0
   @nrwl/cypress    : 16.0.0
   @nx/devkit       : 16.0.0
   @nrwl/devkit     : 16.0.0
   @nrwl/nx-plugin  : 16.5.5
   @nrwl/tao        : 16.0.0
   @nx/webpack      : 16.0.0
   @nrwl/webpack    : 16.0.0
   typescript       : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngrx/effects              : 15.3.0
   @ngrx/store                : 15.3.0
   rxjs                       : 6.6.7
   @ng-bootstrap/ng-bootstrap : 14.0.1
   @ngrx/store-devtools       : 15.3.0
   @reef/fwk                  : 4.0.0-pr-60.4
   ngx-build-plus             : 15.0.0
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/jest@16.5.5
     - @nx/linter@16.5.5
     - @nrwl/nx-plugin@16.5.5

   To fix this, run `nx migrate nx@16.5.5`
```

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

1. We are using the default Nx hashing mechanism for caching and build optimizations.
2. The issue is specific to a particular project within the Nx workspace.
3. Both environments are running on the same Node.js version, and no other build tools or dependencies 
   seem to be causing conflicts.
4. in local we are using windows os and in pipeline linux os is there

**Comment by FrozenPandaz** [comment]
You should be able to compare the two tasks via the Nx Cloud UI:

![image](https://github.com/nrwl/nx/assets/8104246/bb39fda3-1b99-4dcc-b648-2e71cd8d2a51)
https://nx.dev/recipes/troubleshooting/troubleshoot-cache-misses#troubleshoot-cache-misses

Does that UI show any differences?

Differences would be highlighted in red. Example:
https://cloud.nx.app/orgs/5e45db27d8058f000575e4b6/workspaces/5e4b5235e25f2900058192c4/compare-tasks?baseId=64c44224324a93247b1b08fd&comparorRunLinkId=zt8ho51mQs

**Comment by shivom2k** [comment]
Using custom task runner, Hash value for particular task like lint in CI/CD(Jenkins pipeline) is different from run in local system(developement)

**Comment by govindappaarun** [comment]
@FrozenPandaz what if in the above case we are not using NxCloud? in that case how do we compare the cache
