### ISSUE TITLE
Nx dep-graph on selected projects in workspace

### ISSUE THREAD

**Issue by JVHeerden** [nrwl/nx#1841]
## Expected Behavior

Running a command like `nx dep-graph my-project-name` would only list the dependency chain of the specified project in the workspace, omitting other unrelated projects from the graph

## Current Behavior

Running `nx dep-graph my-project-name` still displays the dependency chain of all projects in the workspace

### Context

Nrwl Version: 8.5.0

#### Use case

I current have a workspace with around 50+ feature libraries (and several shared libraries) that all get used in a single portal application. I would like to view the dependency chain of a single one of these feature libraries without seeing all of the other projects in the workspace in the graph.

**Comment by JoshMentzer** [comment]
@JVHeerden - check out 8.7, I did a PR on this for similar reason as you mention here, imagine it'll meet your use case as well.

**Comment by vsavkin** [comment]
Yup. @JoshMentzer fixed it here: https://github.com/nrwl/nx/commit/f6ad171450a7f3fcf7d4f5f061ee62597b6a1d3c

I cut 8.7.0 yesterday, which has the commit.
