### ISSUE TITLE
Arguments interpolating doesn't work properly

### ISSUE THREAD

**Issue by ThePlenkov** [nrwl/nx#18423]
### Current Behavior

Following this [guide ](https://nx.dev/packages/nx/executors/run-commands#examples) I try to run a command like:
```
npx nx run docs:build-pages --vp-base /docs/
```

where project.json is:
```
{
    "name": "docs",
    "targets": {
        "build-pages": {
            "executor": "nx:run-commands",
            "options": {
                "commands": [
                    "rm -rf public",
                    "mkdir public",
                    "vitepress build docs --base {args.vp-base}",
                    "mv docs/.vitepress/dist/* public"
                ],
                "parallel": false
            }
        }
    }
}
```

However I get an error:
```
nx run docs:build-pages --vp-base=/docs/

rm: unrecognized option '--vp-base=/docs/'
Try 'rm --help' for more information.
Warning: run-commands command "rm -rf public --vp-base=/docs/" exited with non-zero status code
```

So what it does - it tries to apply arguments to all commands while it should interpolcate them into it.

### Expected Behavior

According to the documentation it should replace {args.vp-base} with my argument value and execute commands without additionally added custom argument to each command.

In general I propose that forwardAllArgs should be false for commands and true for command.

### Steps to Reproduce

Just add the task as mentioned above - it should work.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.3.1
   OS     : linux-x64
   npm    : 9.6.7
   
   nx                 : 16.5.5
   @nx/js             : 16.5.5
   @nx/linter         : 16.5.5
   @nx/workspace      : 16.5.5
   @nx/devkit         : 16.5.5
   @nx/eslint-plugin  : 16.5.5
   @nrwl/tao          : 16.5.5
   @nx/vite           : 16.5.5
   nx-cloud           : 16.1.1
   typescript         : 5.1.6
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ThePlenkov** [comment]
So the current solution which works looks like this:
```
{
  "name": "docs",
  "$schema": "node_modules/nx/schemas/project-schema.json",
  "targets": {
    "build-pages": {
      "executor": "nx:run-commands",
      "options": {
        "commands": [
          {
            "command": "rm -rf public",
            "forwardAllArgs": false
          },
          {
            "command": "mkdir public",
            "forwardAllArgs": false
          },
          {
            "command": "vitepress build docs --base {args.vp-base}",
            "forwardAllArgs": false
          },
          {
            "command": "mv docs/.vitepress/dist/* public",
            "forwardAllArgs": false
          }
        ],
        "parallel": false
      }
    }
  }
}
```
and is [described ](https://nx.dev/packages/nx/executors/run-commands)in the documentation too 

So what I suggest here - could you please leave arguments forwarding true only for a command, but not for commands. Because it doesn't make sense to apply arguments to each line. I'd say it's even dangerous zone!

**Comment by ThePlenkov** [comment]
One more alternative solution - is to allow us to use JS/TS configs as all other tools support:
For example same example could look like in project.ts
```typescript
export default {
  name: 'docs',
  $schema: 'node_modules/nx/schemas/project-schema.json',
  targets: {
    'build-pages': {
      executor: 'nx:run-commands',
      options: {
        commands: [
          'rm -rf public',
          'mkdir public',
          'vitepress build docs --base {args.base}',
          'mv docs/.vitepress/dist/* public',
        ].map((command) => ({ command, forwardAllArgs: false })),
        parallel: false,
      },
    },
  },
};

```

**Comment by ThePlenkov** [comment]
And I've managed to support project.ts with such a tiny code:
```
import {
  ProjectGraph,
  ProjectGraphBuilder,
  ProjectGraphProcessorContext,
} from '@nx/devkit';
import path = require('path');

import { deepmerge } from 'deepmerge-ts';

export async function processProjectGraph(
  graph: ProjectGraph,
  context: ProjectGraphProcessorContext
): Promise<ProjectGraph> {
  for (const project of Object.values(graph.nodes)) {
    //check if it has project.ts
    const getFilePath = (file: string) =>
      project.data.root === '.' ? file : path.join(project.data.root, file);

    const projectTs = getFilePath('project.ts');

    if (context.fileMap[project.name].some(({ file }) => file === projectTs)) {
      //import project ts
      try {
        const config = await import(projectTs);
        project.data = deepmerge(project.data, config.default);
      } catch (error) {
        console.error(error);
      }
    }
  }

  const builder = new ProjectGraphBuilder(graph);
  // We will see how this is used below.
  return builder.getUpdatedProjectGraph();
}


```

**Comment by AgentEnder** [comment]
Hey @ThePlenkov! We chatted on the community slack about this, but I'm going to copy some of it here. We aren't interested in supporting TS / JS for our configuration files as one of the key things Nx provides is code generation and migrations, which are **_much_**, **_much_** harder to support when your config isn't a DSL. 

It does seem like it may make sense for run-commands to not forward args to every command like that, but it would be a somewhat breaking change to update the behaviour. I'll check with some team mates to get their opinion.

**Comment by crusoexia** [comment]
> So the current solution which works looks like this:
> 
> ```
> {
>   "name": "docs",
>   "$schema": "node_modules/nx/schemas/project-schema.json",
>   "targets": {
>     "build-pages": {
>       "executor": "nx:run-commands",
>       "options": {
>         "commands": [
>           {
>             "command": "rm -rf public",
>             "forwardAllArgs": false
>           },
>           {
>             "command": "mkdir public",
>             "forwardAllArgs": false
>           },
>           {
>             "command": "vitepress build docs --base {args.vp-base}",
>             "forwardAllArgs": false
>           },
>           {
>             "command": "mv docs/.vitepress/dist/* public",
>             "forwardAllArgs": false
>           }
>         ],
>         "parallel": false
>       }
>     }
>   }
> }
> ```
> 
> and is [described ](https://nx.dev/packages/nx/executors/run-commands)in the documentation too
> 
> So what I suggest here - could you please leave arguments forwarding true only for a command, but not for commands. Because it doesn't make sense to apply arguments to each line. I'd say it's even dangerous zone!

@AgentEnder the repeated `forwardAllArgs: false` is pretty tedious, at least can we design this option at the top-level of the `run-command`?:

```json
  "targetDefaults": {
    "nx:run-commands": {
      "options": {
        "cwd": "{projectRoot}",
        "forwardAllArgs": false
      }
    }
  }
```

**Comment by AgentEnder** [comment]
`forwardAllArgs` has been pulled up to the top level now. See #22753
