### ISSUE TITLE
Lack of intellisense in spec/test files in generated node app

### ISSUE THREAD

**Issue by joaoschoen** [nrwl/nx#18434]
### Current Behavior

When the application is generated, the tsconfig.spec.ts inside the app has the following code:
`  "include": [
    "jest.config.ts",
    "src/**/*.test.ts",
    "src/**/*.spec.ts",
    "src/**/*.d.ts"
  ]`
This makes it so TS doesn't know about .ts files for the sake of autocomplete and import suggestion.

### Expected Behavior

Change it to:
`  "include": [
    "jest.config.ts",
    "src/**/*.ts",
    "src/**/*.test.ts",
    "src/**/*.spec.ts",
    "src/**/*.d.ts"
  ]`
This way test files will automatically have intellisense.

### Steps to Reproduce

1. Generate Node app using:
`nx g @nx/node:application <appname>`

### Nx Report

```shell
Node   : 18.12.1
   OS     : win32-x64
   npm    : 9.8.0

   nx (global)        : 16.6.0
   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/esbuild        : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/node           : 16.6.0
   @nrwl/tao          : 16.6.0
   typescript         : 5.1.6
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by barbados-clemens** [comment]
Closing as, this is a larger topic at hand and simply adding the ts globs most likely isn't the best solution long term for all workspaces. Other projects using the solution based approach also encounters similar behavior. 

People can add 'src/**/*.ts' for their workspaces if they desire but for now it won't be generated until a larger investigation is taken place into the TS setup for Nx. For updates follow https://github.com/nrwl/nx/issues/3106
