### ISSUE TITLE
Invalid Cache Hit on Dependency Update

### ISSUE THREAD

**Issue by twittwer** [nrwl/nx#18442]
### Current Behavior

The update of `@ngrx/eslint-plugin` from 16.0.1 to 16.1.0 breaks the linting. This is hidden by the cached linting result.

### Expected Behavior

Dependency updates should invalidate cache results, based on the following docs:

> sharedGlobals contains root level files that should invalidate the cache for all projects. Note that tsconfig.base.json and the package.json lock files are handled behind the scenes by Nx so that when you modify the specific properties that affect your project, the cache is invalidated.  
> https://nx.dev/concepts/more-concepts/customizing-inputs

### GitHub Repo

https://github.com/twittwer/repro-invalid-nx-cache

### Steps to Reproduce

1. `npm run lint:withoutCache` -> succeeds
2. `npm run lint` -> succeeds
3. `npm run upgrade` -> upgrades `@ngrx/eslint-plugin` to broken 16.1.0
4. `npm run lint` -> succeeds by cache -> **should fail**
5. `npm run lint:withoutCache` -> fails

### Nx Report

```shell
Node   : 18.16.0
   OS     : win32-x64
   npm    : 9.5.1

   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/angular        : 16.6.0
   @nx/cypress        : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nrwl/tao          : 16.6.0
   @nx/web            : 16.6.0
   @nx/webpack        : 16.6.0
   nx-cloud           : 16.2.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 16.0.1
   @ngrx/effects         : 16.0.1
   @ngrx/entity          : 16.0.1
   @ngrx/eslint-plugin   : 16.0.1
   @ngrx/router-store    : 16.0.1
   @ngrx/schematics      : 16.0.1
   @ngrx/store           : 16.0.1
```

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Hm, so it's not an issue in the cache busting. It's that the dependency, `@ngrx/eslint-plugin` is not depended upon by the projects in the Project Graph even though it is used in the `eslint` config. We don't analyze eslint configs to create dependencies. In theory, we could but it would take quite some effort.

I don't think there's a solution for this currently. Maybe the new eslint flat configs will solve this problem inheritently because the eslint configs will be analyzed by our typescript analysis?

@meeroslav would know best.

**Comment by meeroslav** [comment]
Yes, as @FrozenPandaz mentioned, when you use JSON-based `.eslintrc.json` the eslint converts plugin names (e.g. `@ngrx`) to qualified package names and calls `require` under the hood. This is, unfortunately, outside of Nx's reach.

The new flat config that will land soon in Nx enforces explicit reference to all the external plugins (this is one of the main features of the new config). In the meantime, the only thing you can do is to have a dummy file that is ignored by your `production` named input and import all those plugins.

// my-eslint-plugins-importer.js
```js 
import * from `@ngrx/eslint-plugin`
```

// nx.json
```jsonc
{
  "namedInputs": {
    // ...
    "production": [
      // ...
      "!{projectRoot}/my-eslint-plugins-importer.js"
    ]
  }
}
```
