### ISSUE TITLE
Nx unable to copy new output to locale cache (macOS Darwin Arm64)

### ISSUE THREAD

**Issue by samijaber** [nrwl/nx#18448]
### Current Behavior

When trying to run a simple `build` command using `yarn nx build`, with the following default config in `nx.json`:

```json
{
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build", "prebuild"],
      "outputs": ["{projectRoot}/dist"]
    }
  }
}
```

The build step will succeed, but fail when trying to copy its contents to the locale cache:

<img width="1419" alt="CleanShot 2023-08-02 at 15 42 16@2x" src="https://github.com/nrwl/nx/assets/1393142/4867c5c9-ad89-4e5c-a22a-7d226ad83225">

NOTE: This only happens on my local M1 Mac machine, but the CI for the monorepo works fine.

### Expected Behavior

The content copies successfully to the locale cache

### Steps to Reproduce

1. clone https://github.com/BuilderIO/builder/pull/2521
2. go to `packages/`
3. run `yarn`
4. go to `packages/core`
5. run `yarn nx build`

### Nx Report

```shell
Node   : 16.14.0
   OS     : darwin-arm64
   npm    : 8.3.1
   
   nx (global)  : 16.6.0
   nx           : 16.6.0
   lerna        : 3.20.2
   @nrwl/tao    : 16.6.0
   nx-cloud     : 16.2.0
   typescript   : 5.1.6
   ---------------------------------------
   Local workspace plugins:
         @e2e/next-app-dir-client
         @e2e/next-pages-dir
         @builder.io/sdk-vue-3
         @builder.io/sdk-vue-2
         @e2e/next-app-dir
         @e2e/gen1-react
         @e2e/solid-start
         @e2e/gen1-next
         @e2e/sveltekit
         @e2e/qwik-city
         @e2e/solid
         @e2e/svelte
         @e2e/react
         @e2e/vue3
         @e2e/vue2
         @builder.io/react
         @builder.io/sdks
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I think this is a bug in how the Nx `copy` commands is run, at least in macOS Darwin Arm64... IIRC it executes:

https://github.com/nrwl/nx/blob/1dcb80d447f115c0054b8782fdf1a2dd118d0cdd/packages/nx/src/tasks-runner/cache.ts#L187

```
cp -a src/foo .cache/nx/*/outputs/src/foo
```

but up until then, only `.cache/nx/*/outputs` is created. `cp` is OK with 1 more folder coming up afterwards, but not 2 levels of nesting. So we need to

```
mkdir .cache/nx/*/outputs/src
```

at some point beforehand. Afterwards, the `cp -a src dest` command works fine.

**Comment by samijaber** [comment]
Seems like maybe this part of the native rust `copy` code isn't executing properly on my machine...
 https://github.com/nrwl/nx/blob/1dcb80d447f115c0054b8782fdf1a2dd118d0cdd/packages/nx/src/native/cache/file_ops.rs#L19

Not sure why/how 🤷🏽

**Comment by FrozenPandaz** [comment]
We're not sure how but it was resolved by clearing node_modules / dist folders. Now it's not reproducible anymore.

Copying nested directories does work.. but something else must've been interfering.

I'll close this issue as its not reproducible.
