### ISSUE TITLE
NX caching issue with zlib

### ISSUE THREAD

**Issue by arvindnama** [nrwl/nx#18446]
### Current Behavior

```
NX_TASKS_RUNNER<name-of-task-runner-with-s3-caching-enabled> npx nx run-many --target=<cache-able-target>
```

Every third or fourth attempt with a remote cache hit would result in Zlib error:

![image](https://github.com/nrwl/nx/assets/2868087/dc5dde2d-75e1-49e7-b1a7-c68d854d3f55)

### Expected Behavior

successful remote cache hit without 

### Steps to Reproduce

```
NX_TASKS_RUNNER<name-of-task-runner-with-s3-caching-enabled> npx nx run-many --target=<cache-able-target>
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin-x64
   npm    : 9.5.1

   nx                 : 16.5.1
   @nx/js             : 16.5.1
   @nx/jest           : 16.5.1
   @nx/linter         : 16.5.1
   @nx/workspace      : 16.5.1
   @nx/angular        : 16.5.1
   @nx/cypress        : 16.5.1
   @nx/devkit         : 16.5.1
   @nx/eslint-plugin  : 16.5.1
   @nx/plugin         : 16.5.1
   @nx/storybook      : 16.5.1
   @nrwl/tao          : 16.5.1
   @nx/web            : 16.5.1
   @nx/webpack        : 16.5.1
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   @storybook/angular : 6.5.15
   apollo-angular     : 4.2.1
```
```


### Failure Logs

_No response_

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by StalkAltan** [comment]
Hi, as I understand it you are using a 3rd party tasks runner? We are unfortunately unable to provide support for that as it's not a project we control.

**Comment by arvindnama** [comment]
Hi @StalkAltan , 
   Apart from S3 bucket, I don't see a 3rd party, this is Nx's own implementation of remote distributed Caching.  ( please let me know if I am missing anything)  
   
From what I see, Nx is trying to unzip the file that it downloads from S3 bucket and it fails.

**Comment by StalkAltan** [comment]
@arvindnama You are not using the nx-cloud task runner, correct?

**Comment by arvindnama** [comment]
@StalkAltan  we are using `nx-remotecache-minio`

**Comment by arvindnama** [comment]
I think I get it , for some reason I assumed `nx-remotecache-minio` is owned by Nx. my bad.

**Comment by StalkAltan** [comment]
@arvindnama all good! Just means that we can’t be that helpful here :( Nx exposes an interface that people can implement, but we don’t control what happens from that point on.

Gonna close this for now! Maybe the maintainer of your runner will have some ideas.

**Comment by arvindnama** [comment]
Thanks @StalkAltan , But can you point me to that Interface/documentation So I can build my own remote cache?
