### ISSUE TITLE
create-nx-workspace presets documentation

### ISSUE THREAD

**Issue by maksnester** [nrwl/nx#18457]
### Documentation issue

- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/packages/nx/documents/create-nx-workspace#preset

### Additional context or description

I do not understand where I can read about the differences between different presets. How can I know what is the difference between "npm", "react-monorepo" and "react" without actually generating things?

**Comment by mathpaquette** [comment]
https://github.com/nrwl/nx/blob/master/packages/create-nx-workspace/src/utils/preset/preset-options.ts

**Comment by SampsonM-SBG** [comment]
Having the same thoughts now. 
As a new user of nx I don't know the difference between presets, or even what presets are available! 

Searching online only shows me docs for internal schemas 👀

**Comment by dfenerski** [comment]
Bump. Nx is very versatile but the website forces you into some pre-picked setup, without info about other initial options.

**Comment by dfenerski** [comment]
The landing page for the create-nx-workspace command still does not describe what the options mean
![image](https://github.com/user-attachments/assets/233105e5-5900-4c39-b239-549d6fd29f01)

**Comment by isaacplmann** [comment]
Note: the documentation changes are merged into master, but not yet deployed to the production site.  That will happen when a new version of Nx is released.  You can see the latest dev changes here:

https://canary.nx.dev/nx-api/nx/documents/create-nx-workspace#presets
