### ISSUE TITLE
nx-win32-x64-msvc is not optional when on windows os

### ISSUE THREAD

**Issue by TimoPot** [nrwl/nx#18453]
### Current Behavior

NX 15

When doing a npm i --omit=optional the package nx-win32-x64-msvc is not installed because it is marked as optional, then NX wont work.  

When I do: nx run my-project

I get the error: Error: Cannot find module '@nrwl/nx-win32-x64-msvc'

and the build fails.

After doing a npm i the package gets installed and nx run will work.

### Expected Behavior

I expect the pacakage not the be optional when during npm the proces sees it's on windows.

Or the package is mandatory.

### Steps to Reproduce

The company I work for forbids putting it on github.

steps I hope it will reproduce.

Create a NX with Angular 15 project.

remove node_modules folder (if any)
remove package-lock.json (if any)

run: npm i --no-fund --omit=optional --legacy-peer-deps

No I expect the package-lock.json to have:

      "optionalDependencies": {
        "@nrwl/nx-darwin-arm64": "15.9.4",
        "@nrwl/nx-darwin-x64": "15.9.4",
        "@nrwl/nx-linux-arm-gnueabihf": "15.9.4",
        "@nrwl/nx-linux-arm64-gnu": "15.9.4",
        "@nrwl/nx-linux-arm64-musl": "15.9.4",
        "@nrwl/nx-linux-x64-gnu": "15.9.4",
        "@nrwl/nx-linux-x64-musl": "15.9.4",
        "@nrwl/nx-win32-arm64-msvc": "15.9.4",
        "@nrwl/nx-win32-x64-msvc": "15.9.4"                        <====== the culprit
      },

run: nx run your-project

### Nx Report

```shell
no report
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

node: v16.20.1

**Comment by AgentEnder** [comment]
We can't move those to non-optional, or every installation would include them, including on other platforms. This is a fairly typical setup with napi, consider @parcel/watcher as another example: https://unpkg.com/@parcel/watcher@2.2.0/package.json

I'd recommend not using `--omit optional`, as though things are marked as optional it would almost certainly affect the behaviors of other packages.

**Comment by TimoPot** [comment]
Then the install process should be able to determine which OS it’s installing on and use the right package.Met vriendelijke groet,Timo Op 11 aug. 2023 om 20:51 heeft Craigory Coppola ***@***.***> het volgende geschreven:﻿
We can't move those to non-optional, or every installation would include them, including on other platforms. This is a fairly typical setup with napi, consider @parcel/watcher as another example: ***@***.******@***.***/package.json
I'd recommend not using --omit optional, as though things are marked as optional it would almost certainly affect the behaviors of other packages.

**Comment by AgentEnder** [comment]
It does, if you don't explicitly tell it not to

**Comment by TimoPot** [comment]
Ah yes of course.RegardsTimo Op 13 aug. 2023 om 22:51 heeft Craigory Coppola ***@***.***> het volgende geschreven:﻿
It does, if you don't explicitly tell it not to
