### ISSUE TITLE
angular 15 using withModuleFederation errors on startup

### ISSUE THREAD

**Issue by etkachev** [nrwl/nx#18450]
### Current Behavior

On angular 14/nx 14, running an application with module federation (via `withModuleFederation`) works fine

Once upgraded to angular 15/nx 15, for whatever reason, I get a white screen and get the following errors: 
```
Uncaught Error: Automatic publicPath is not supported in this browser
```

for both polyfills.js and main.js

Digging into the compiled js, I noticed with angular14, the area where it errors, it uses `import.meta.url` to check the url, and the url of bundle file exists. (see below)

<img width="555" alt="image" src="https://github.com/nrwl/nx/assets/9970746/c2391ae9-b699-4e50-92b8-3b107b6bcbfa">

But with angular 15/nx 15, the same code snippet area looks like this (see below). Notice its a variable (`Er`) that is just an object defined at top of the file. It doesn't use `import.meta`.

<img width="594" alt="image" src="https://github.com/nrwl/nx/assets/9970746/c2879655-fbbc-4fc3-baed-474c2408827d">

This is the main difference I see between the 2 versions of angular/nx.

Here is the webpack config for the host app that is failing:

```javascript
const { withModuleFederation } = require('@nrwl/angular/module-federation');
const config = require('./module-federation.config');
module.exports = withModuleFederation(config);
```

### Side note:

We have a separate application in the same repo that runs just fine with the angular upgrade. We are not using the `withModuleFederation` util and rather setting it manually.

The webpack config of the app that works looks like this:

```javascript
module.exports = {
  output: {
    uniqueName: 'shell',
    publicPath: 'auto',
    scriptType: 'text/javascript',
  },
  optimization: {
    runtimeChunk: false,
  },
  resolve: {
    alias: {
      ...sharedMappings.getAliases(),
    },
  },
  plugins: [
    new ModuleFederationPlugin({
      name: 'shell',
      filename: 'remoteEntry.js',
      exposes: suitesShellExposedEntrypoints('shell'),
      remotes: suitesShellAvailableRemotes['suitesShell'],
      shared: sharedShellLibs,
    }),
    new ExternalTemplateRemotesPlugin(),
    sharedMappings.getPlugin(),
    findReplaceAllScorpionEnvVars(),
  ],
};
```

Ideally I would like to continue using `withModuleFederation` without manually overriding too many options, but would like to better understand which configuration is different with webpack.

### Expected Behavior

Be able to upgrade to Angular 15/ Nx 15 using webpack and `withModuleFederation` util without getting just a white screen when running that the application.

### Steps to Reproduce

1. We have a large repo. will try to create a basic setup to see if it's reproducible with empty app.

### Nx Report

```shell
Node : 16.16.0
   OS   : darwin arm64
   pnpm : 7.30.3

   nx                      : 15.9.4
   @nrwl/js                : 15.9.4
   @nrwl/jest              : 15.9.4
   @nrwl/linter            : 15.9.4
   @nrwl/workspace         : 15.9.4
   @nrwl/angular           : 15.9.4
   @nrwl/cli               : 15.9.4
   @nrwl/cypress           : 15.9.4
   @nrwl/devkit            : 15.9.4
   @nrwl/eslint-plugin-nx  : 15.9.4
   @nrwl/node              : 15.9.4
   @nrwl/storybook         : 15.9.4
   @nrwl/tao               : 15.9.4
   @nrwl/web               : 15.9.4
   @nrwl/webpack           : 15.9.4
   @nrwl/nx-cloud          : 16.0.5
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ionic/angular        : 5.9.4
   @ngrx/component       : 15.3.0
   @ngrx/component-store : 15.3.0
   @ngrx/effects         : 15.3.0
   @ngrx/entity          : 15.3.0
   @ngrx/router-store    : 15.3.0
   @ngrx/store           : 15.3.0
   apollo-angular        : 4.2.1
   rxjs                  : 6.6.7
   @ngneat/spectator     : 10.0.1
   @ngrx/schematics      : 15.3.0
   @ngrx/store-devtools  : 15.3.0
   @nxext/capacitor      : 15.7.0
   @nxext/ionic-angular  : 15.7.0
   @storybook/angular    : 6.5.16
   ngx-build-plus        : 14.0.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Are you able to provide a reproduction repo of this issue?

I've tried to reproduce it locally and have been unable to.

**Comment by etkachev** [comment]
Yes almost done with getting a reproduction repo setup. I'll have it setup as private, then send an invite to you.

**Comment by etkachev** [comment]
Ok sent you invite to the private repo. Let me know if you need others added. I was able to reproduce it there too. Repro steps:

1. If you checkout the initial commit, then run `pnpm nx run console-dashboard-host:serve:production`. Opening localhost:4203 you'll see no errors on startup (might redirect you to sso, but that's fine).
2. If you then checkout the latest commit, that will include the nx 15 and angular 15 upgrade. Running the same serve command, you will see the error mentioned in this issue.

**Comment by etkachev** [comment]
@Coly010 let me know if anything else is needed for the repro

**Comment by Coly010** [comment]
Hey @etkachev !

Apologies its been a few days.
I just tried to accept the invitation to the private repo there and it told me the invitation had expired, could you send through another invite?

**Comment by etkachev** [comment]
Just re-sent it

**Comment by etkachev** [comment]
@Coly010 Just following up to make sure you were able to get access to the repo.

**Comment by etkachev** [comment]
Just responding again to keep this active

**Comment by etkachev** [comment]
@Coly010  I'm seeing comments that may be similar to what is mentioned in this issue? https://github.com/nrwl/nx/issues/10017 maybe related?

**Comment by etkachev** [comment]
I've been able to add the following config that was mentioned in the [issue](https://github.com/nrwl/nx/issues/10017#issuecomment-1723087634). This allows me to get past the white screen and at least load the main host page, but trying to load any of the MFEs results in other errors:

New error: `Error: Uncaught (in promise): ReferenceError: require is not defined`

Updated prod file to:
```js
const { withModuleFederation } = require('@nrwl/angular/module-federation');
const config = require('./module-federation.config');
module.exports = withModuleFederation({
  ...config,
  /*
   * Remote overrides for production.
   * Each entry is a pair of an unique name and the URL where it is deployed.
   *
   * e.g.
   * remotes: [
   *   ['app1', 'https://app1.example.com'],
   *   ['app2', 'https://app2.example.com'],
   * ]
   */
}).then((webpackConfigFunc) =>
  webpackConfigFunc({
    output: {
      scriptType: 'text/javascript',
    },
  }),
);
```

In that issue linked above, there were mentioned about this config breaking MFE? But not sure if that is related to the new error I'm getting.

**Comment by etkachev** [comment]
Commenting to keep this issue open

**Comment by Coly010** [comment]
Hi @etkachev Sorry for the delay on this. 

I'll be looking at this today

**Comment by Coly010** [comment]
@etkachev An update. I believe you were correct with where this error lies. `import.meta.url` is being optimized and transformed into an empty object by webpack for production configuration.

I'm investigating how/where this can be avoided.

**Comment by Coly010** [comment]
@etkachev Can you try adding:

```json
"optimization": {
   "scripts": false
}
```

to `dashboard-host`'s build targets in the `project.json` and see if this works? 

It looks like it should from my investigations on the repo you shared with me, but that repo appears to be missing some files that are throwing a different for me.

**Comment by etkachev** [comment]
@Coly010 the `"optimization": { "scripts": false }` seemed to have helped! Should I resume with that configuration for production builds?

**Comment by Coly010** [comment]
It might be worth investigating the bundle size impact it has, if any. 

I would also view it as a workaround for now. I’m going to continue to investigate to see if I can nail down the exact cause of the issue.

**Comment by etkachev** [comment]
That seems to only affect the main host app (where I added the optimization config update). The rest of the MFEs don't seem to be affected.

**Comment by Coly010** [comment]
Yeah, I was worried about that. I'll keep digging to see if i can find the root cause

**Comment by Coly010** [comment]
bump

**Comment by etkachev** [comment]
We just upgraded our workspace to 15. Will be doing followup to see if we can upgrade to latest at some point early next year. Let me know if you find anything in the meantime.

**Comment by etkachev** [comment]
keeping this open

**Comment by etkachev** [comment]
bumping to keep open

**Comment by IanWangTaiwan** [comment]
my angular app is v15, using nx and module federation,when i add .browserslistrc and build is not error,but in runtime i have same error as yours, and i add "optimization": false in the project.json is reslove that problem, thanks a lot!

**Comment by etkachev** [comment]
bump to keep open. while we investigate further

**Comment by etkachev** [comment]
bumping to keep open

**Comment by etkachev** [comment]
bumping to keep open.

**Comment by etkachev** [comment]
bump to keep open

**Comment by Coly010** [comment]
I wonder if there's a way we could get the bot to skip this issue...

@etkachev Have you been able to investigate if adding `optimization: false` helps resolve this issue?
I note that it has for IanWangTaiwan: https://github.com/nrwl/nx/issues/18450#issuecomment-1911311989

**Comment by etkachev** [comment]
Yea issue was resolved with that set to false, but wasn't sure if we wanted to keep this open to find solution without needing to set the optimization to false for that case? Or open up separate issue to keep track of?
