### ISSUE TITLE
React-native upgrade from 0.71.10 to 0.72.3 failing

### ISSUE THREAD

**Issue by HarlicWork** [nrwl/nx#18479]
### Current Behavior

Getting error after run migration script from nx react-native 0.71.10 to 0.72.3. 

After running `yarn upgrade:deps` and checking migration.json file, it have some beta tags. Is this correct?

`{
  "migrations": [
    {
      "cli": "nx",
      "version": "16.6.0-beta.6",
      "description": "Prefix outputs with {workspaceRoot}/{projectRoot} if needed",
      "implementation": "./src/migrations/update-15-0-0/prefix-outputs",
      "package": "nx",
      "name": "16.6.0-prefix-outputs"
    },
    {
      "cli": "nx",
      "version": "16.6.0-beta.0",
      "description": "Explicitly set 'updateBuildableProjectDepsInPackageJson' to 'true' in targets that rely on that value as the default.",
      "factory": "./src/migrations/update-16-6-0/explicitly-set-projects-to-update-buildable-deps",
      "package": "@nx/js",
      "name": "explicitly-set-projects-to-update-buildable-deps"
    },
    {
      "cli": "nx",
      "version": "16.6.0-beta.0",
      "description": "Add dependsOn like ensure-symlink or sync-deps to targets",
      "implementation": "./src/migrations/update-16-6-0/add-depends-on",
      "package": "@nx/react-native",
      "name": "update-16-6-0-add-dependsOn"
    },
    {
      "cli": "nx",
      "version": "16.6.0-beta.0",
      "description": "Update metro.config.js to use the new metro config format",
      "implementation": "./src/migrations/update-16-6-0/update-metro-config",
      "package": "@nx/react-native",
      "name": "update-16-6-0-update-metro-config"
    }
  ]
}
`

### Expected Behavior

able to run application with react-native 0.72.3

### Steps to Reproduce

1. Run `yarn upgrade:deps` to update packages.
2. Verify package.json which packages will be updated.
3. Run `yarn nx migrate --run-migrations` throw the error and unable to update using RN 0.72.3

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.17.0
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx (global)        : 16.3.2
   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/detox          : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/react          : 16.6.0
   @nx/react-native   : 16.6.0
   @nrwl/tao          : 16.6.0
   @nx/web            : 16.6.0
   typescript         : 5.1.6
```

### Failure Logs

```shell
>  NX   Running migrations from 'migrations.json'


 >  NX   Failed to run update-16-6-0-add-dependsOn from @nx/react-native. This workspace is NOT up to date!


 >  NX   Cannot set properties of undefined (setting 'dependsOn')

   Pass --verbose to see the stacktrace.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: yarn nx _migrate --run-migrations
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 >  NX   Command failed: yarn nx migrate --run-migrations

   Pass --verbose to see the stacktrace.

Command failed: /var/folders/jj/m5v_4b753cdfw23ycf27qwxw0000gn/T/tmp-21858-byyCflToqdJM/node_modules/.bin/nx _migrate --run-migrations
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Beta tags inside migrations.json are normal, they let us test the migrations during the beta release.

**Comment by robertn702** [comment]
I was also getting this error because my expo app's `project.json` didn't have an `export` target. Adding it fixed the issue for me. Make sure your project has all the target's expected in the [`update-16-6-0/add-depends-on.ts`](https://github.com/nrwl/nx/blob/fa513731d4e6a960f112a5af6b0d725b2e624b36/packages/expo/src/migrations/update-16-6-0/add-depends-on.ts) migration file.

**Comment by curthipster** [comment]
Thank you @robertn702! In my case, I was missing several of the dependencies that it's trying to update. Notably, several of them including `export`, are not included in a new project generated using `npx create-nx-workspace your-workspace-name
--preset=react-native
--appName=your-app-name`.

In case it's helpful to others struggling with this, here's what I did to get past this step:

In `apps/<your-app-nam>/project.json`, add the missing targets to the `"targets"` object, for example:

```json
    "export": {
      "executor": "nx:noop"
    }
```

**Comment by airowe** [comment]
Any update from the maintainers on this one to get fixed in the repo migrations?

**Comment by aslamanver** [comment]
Any solutions ?

**Comment by xiongemi** [comment]
should be fixed in pr https://github.com/nrwl/nx/pull/19160/files
