### ISSUE TITLE
Any plan for a LIT plugin?

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#18473]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Should be great to having a lit library generator

## Motivation
LIT is very helpful for create agnostics ui kits for design systems

**Comment by AgentEnder** [comment]
We don't have plans at this time for a first party lit plugin, although we do use lit for nx console's UI IIRC. It would be a good candidate for a community plugin, if someone wants to take it up

**Comment by dazraf** [comment]
FWIW, I would dearly love to have a LIt (+vitejs) NX plugin!
