### ISSUE TITLE
Share a common vendor bundle between multiple apps

### ISSUE THREAD

**Issue by ctaepper** [nrwl/nx#1847]
## Expected Behavior

I have multiple apps in my Nx workspace and I want them to share a common vendor bundle, so it needs to be loaded once and can be fetched from browser cache in the other apps

## Current Behavior

I can seem to find an option on how to create such a bundle

**Comment by johannesschobel** [comment]
what do you mean by `Common Vendor Bundle` in your specific scenario? Is it some kind of `lib` or a `node_module`?

If you aim for a common `lib` (that is framework agnostic, i.e., it is not specifically tailored for angular), just create one via `ng g @nrwl/workspace:lib LIBNAME`. This will create a new library in `/libs/LIBNAME` and will be properly scaffolded.

**Comment by ctaepper** [comment]
Ok so I have multiple separate apps in my Nx workspace, let's call them "micro apps". They are all served at the same domain under different paths and make up one "large app". They all have their `main.js` and or `vendor.js` at around 800kb (unzipped). So I was wondering, since they all use the same angular dependencies of the workspace, if I can have a common vendor.js bundle across all of them to improve cashing and load time of the app.

I know you are going to say "make them one app with lazy loaded feature modules" but thats just something I cannot do currently

**Comment by johannesschobel** [comment]
ok, just to understand you.. you have a `shoppingcart` app and a `login` app and an `account management` app, right?

Just as an idea.. cant you just make an `shared shop` angular application (or library) and have this one shared / included in the others? This `shared shop` application would just export the `vendor.js`?

**Comment by ctaepper** [comment]
> ok, just to understand you.. you have a `shoppingcart` app and a `login` app and an `account management` app, right?

yes, exactly!

> Just as an idea.. cant you just make an `shared shop` angular application (or library) and have this one shared / included in the others? This `shared shop` application would just export the `vendor.js`?

>> I know you are going to say "make them one app with lazy loaded feature modules" but thats just something I cannot do currently

**Comment by johannesschobel** [comment]
How about this:
You can just create a new `startup` library that contains the `vendor.js` or `main.js` files for all of these mentioned applications.

Then, in your `shoppingcart application / main.ts` file, include (load) the `startup library / main.ts` file that is shared across all your applications. Repeat this for all other apps..

Does this work / help you?

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by nahue** [comment]
Did anyone found a workaround for this? I created a couple react apps and a UI library with some dependencies. It would be nice if i could have a single vendor file shared across apps. So they don't load vendor deps for each one.
