### ISSUE TITLE
The "to" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by gxxcastillo** [nrwl/nx#18481]
### Current Behavior

I'm getting an error when executing the following task, however the error occurs even if there are no tests in the package:

```
    "test": {
      "executor": "@nx/vite:test",
      "outputs": ["{projectRoot}/reports/coverage"],
      "options": {
        "passWithNoTests": true
      }
    },
```

error:
```
 >  NX   The "to" argument must be of type string. Received undefined
```

### Expected Behavior

The tests should run

### Steps to Reproduce

1. create a package, 
2. try to run unit tests using the vitest executor
3. note the error

### Nx Report

```shell
Node   : 18.15.0
   OS     : darwin-x64
   yarn   : 3.2.4
   
   nx (global)        : 16.3.2
   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nrwl/tao          : 16.6.0
   @nx/vite           : 16.6.0
   nx-cloud           : 16.2.0
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I only started seeing this error after upgrade to v16.6.0

**Comment by mandarini** [comment]
Hi there @gxxcastillo ! I tried reproducing your issue, but I could not reproduce it, unfortunately. Can you please provide a minimum reproduction repository?

What I did was I created a new workspace, I added a React library with vitest, and tests run. I added a js library with vitest and the tests run.

**Comment by gxxcastillo** [comment]
@mandarini, I've tried updating to v16.7.1 and I'm still seeing the issue - we have a large repo with many packages and are using some custom NX plugins, I wonder if the issue might be related to our custom plugins? The error message, `The "to" argument must be of type string. Received undefined` is quite broad - any thoughts on what it is referring to?  Note, things are working fine pre-v16.6.0

**Comment by mandarini** [comment]
@gxxcastillo thanks for providing more info. is there a way you can try to reproduce this in a smaller repo which you can share?

**Comment by CodesisAB** [comment]
@gxxcastillo @mandarini I had the same issue. It seems that in "node_modules/@nx/vite/src/utils/options-utils.js" options property "outputPath" is mandatory and it is not resolved correctly from the project.json configuration from the project/application that is being built. Adding outputPath to general "options" (not in a specific configuration) path solves it: 
```
{
  ...
  "targets": {
    "build": {
      "options": {
         ...
        "outputPath": "dist/apps/my-path"
         ...
       },
...
}
```

My guess would be that it doesn't resolve the default configuration options from the project that is being built. Or maybe we should provide the configuration for tests in some form, if someone knows a better way to solve it, please improve this solution.

**Comment by mandarini** [comment]
Thanks @CodesisAB , I'll look into it.
