### ISSUE TITLE
`nx run projectA:build --watch` gets stuck watching its dependency projectB

### ISSUE THREAD

**Issue by Kim716** [nrwl/nx#18480]
### Current Behavior

When using the `--watch` flag with `projectA:build`, it starts watching its dependency projectB, but then gets stuck at that point.

This issue is similar with this closed issue: [Issue#9406](https://github.com/nrwl/nx/issues/9406)

### Expected Behavior

Using the --watch flag with projectA:build should watch and build both projectB and projectA simultaneously.

### GitHub Repo

[nx-watch-issue-demo](https://github.com/Kim716/nx-watch-issue-demo/tree/main)

### Steps to Reproduce

1. Having two projects, where projectA depends on projectB.
2. In the nx.json file, the below code should be set:
```
"targetDependencies": {
    "build": [
      {
        "target": "build",
        "projects": "dependencies"
      }
    ]
  },
```
3. Execute `nx run projectA:build --watch`
4. Observe that the watch process gets stuck on projectB.

### Nx Report

```shell
Node : 16.15.0
   OS   : darwin arm64
   npm  : 8.5.5
   
   nx : 14.1.9
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.9
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.9
   @nrwl/eslint-plugin-nx : 14.1.9
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.9
   @nrwl/js : 14.4.2
   @nrwl/linter : 14.1.9
   @nrwl/nest : Not Found
   @nrwl/next : 14.1.9
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.4.2
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 12.1.1
   @nrwl/web : 14.1.9
   @nrwl/workspace : 14.1.9
   typescript : 4.9.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Could you please provide a repo that we can use to reproduce the issue?

**Comment by Kim716** [comment]
no problem, please bear with me as I've been quite occupied recently. 🙏

**Comment by Kim716** [comment]
Hi, @FrozenPandaz! Thank you for your patience.
I have created a demo repository for this issue, which you can access by [clicking here](https://github.com/Kim716/nx-watch-issue-demo/tree/main).

Additionally, I've outlined the steps to reproduce the issue in the README.md file. If any information is missing or unclear, please don't hesitate to let me know. Thank you!

**Comment by jiaojiaojiaoCpbr** [comment]
We still stuck in this issue. As @Kim716  said, we cannot use watch mode when build dependent libraries.

Please help to check this issue. 🙏

**Comment by esp10mm** [comment]
Hey bot, we still have this issue. Please keep it open. Thanks !

**Comment by mandarini** [comment]
@esp10mm conversation is moved to #20886 . Can you please retry with latest version of Nx? It's been almost 2 years since version 14, so a lot of things have changed, have been fixed and have been improved since then!
