### ISSUE TITLE
Unable to import .json files in jest.config.ts when running tests

### ISSUE THREAD

**Issue by MiiZZo** [nrwl/nx#18489]
### Current Behavior

I get this error when trying to import json in jest.config.ts
`"Cannot find module './tsconfig.json'. Consider using '--resolveJsonModule' to import module with '.json' extension."` 

### Expected Behavior

No errors with `"resolveJsonModule": true` in tsconfig.json

### Steps to Reproduce

1. Generate application with jest as test runner.
2. Import a generated application tsconfig.json in jest.config.ts.
3. Run command `nx run APPLICATION_NAME:test`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.17.0
   OS     : win32-x64
   yarn   : 1.22.19
   
   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/cypress        : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/nest           : 16.6.0
   @nx/next           : 16.6.0
   @nx/node           : 16.6.0
   @nx/react          : 16.6.0
   @nx/storybook      : 16.6.0
   @nrwl/tao          : 16.6.0
   @nx/web            : 16.6.0
   @nx/webpack        : 16.6.0
   nx-cloud           : 16.2.0
   typescript         : 5.1.6
```

### Failure Logs

```shell
TSError: ⨯ Unable to compile TypeScript: packages/server/jest.config.ts:2:33 - error TS2732: Cannot find module './tsconfig.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.

2 import { compilerOptions } from './tsconfig.json';
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Related issue #14888

**Comment by barbados-clemens** [comment]
This is because that tsconfig isn't being used when the `jest.config.ts` is being read.

there are a couple ways around this.

1. set the `TS_NODE_PROJECT=<path to tsconfig> nx test <my-project>`
2. use `require` to load the json file
3. use `fs` to load the json file
