### ISSUE TITLE
Build-time environment variables for web apps

### ISSUE THREAD

**Issue by wKovacs64** [nrwl/nx#1848]
## Desired Behavior

It would be great if there was a built-in way to expose build-time environment variables to web/React/Angular projects.

## Current Behavior

`process.env` is not exposed, so you have to jump through some hoops and craft a custom solution (e.g. copying files around in a build script, using [`babel-plugin-preval`](https://github.com/kentcdodds/babel-plugin-preval#readme) which comes with `babel-loader` caching issues, etc.) to read environment variables in web projects (as far as I can tell, anyway).

## Other

Prior art for this exists in other popular web frameworks/libraries. [`create-react-app`](https://create-react-app.dev/docs/adding-custom-environment-variables) automatically embeds any environment variable prefixed with `REACT_APP_` and [`Next.js`](https://nextjs.org/docs#build-time-configuration) includes an `env` key in the main config file (evaluated during build) that you can populate as you see fit.

Would either of these approaches be appropriate for Nx, or is there another way that would be even better? Or does an idiomatic way already exist?

Thanks.

**Comment by EranSch** [comment]
Yeah, just encountered this in setting up my first NX project's deployment. Didn't see anything in the docs but I did some across [this](https://github.com/nrwl/nx/issues/1721) question. Given you're already referencing a Babel plugin perhaps you've already explored this but it looks like (CI running now) I should be able to move forward with using good 'ole [`transform-inline-environment-variables`](https://babeljs.io/docs/en/babel-plugin-transform-inline-environment-variables).

Here were the changes required on my end:

1. Add `"webpackConfig": "@nrwl/react/plugins/babel"` to my app's build options  
   ![image](https://user-images.githubusercontent.com/1479206/65131472-49ba9b00-d9cd-11e9-86dc-096cf1adaf28.png)
2. Add `.babelrc` to my app's root (`apps/client-web`)  
   ```json
   {
      "plugins": ["transform-inline-environment-variables"]
   }
   ```
3. Add required dependencies:  
   ```sh
   yarn add --dev babel-plugin-transform-inline-environment-variables

   # I got errors on build for these missing, you may already have them?
   yarn add --dev @babel/plugin-proposal-decorators @babel/preset-react @babel/preset-typescript
   ```

Hopefully that helps get you on your way!

**Comment by wKovacs64** [comment]
Yep, that's another way. Thanks for the detailed instructions!

I think one of these approaches should be baked-in, otherwise we'll have various teams doing it different ways in different projects which negates one of the big benefits of something like Nx (IMHO).

**Comment by EranSch** [comment]
Definitely agreed. It feels like something that can be addressed on the
framework level for sure.

That said, I could see an argument for the idea that baked in environment
variable support is overly prescriptive in the face of an alternative like
using a secrets manager or something too.

**Comment by weblancaster** [comment]
@wKovacs64 @jdpearce @EranSch

We at Blackberry started working on this feature to be part of the framework.

**Comment by footyapps27** [comment]
@weblancaster Any luck with the PR?

**Comment by weblancaster** [comment]
@footyapps27 made some time and opened https://github.com/nrwl/nx/pull/2502

**Comment by PrmJf** [comment]
I just lost over 2 hours of time because of the horrible implementation of this feature.

> These env variables are passed at build time and used at the runtime of an app.

Build time variables MUST NOT be conflated with environment variables: they are simply not the same.
It is unacceptable that `process.env` be replaced during build-time, because `process.env` is per definition **runtime**, i.e. in fact there even does not exist a `process` at build time. 

If you want to replace variables at build time, this should be done through another api. Be it `buildvars.MY_VAR` or something else - I don't care, but right now it is just plain confusing. People even [go as far as to recommend](https://stackoverflow.com/questions/58090082/process-env-node-env-always-development-when-building-nestjs-app-with-nrwl-nx) `process.env["NODE" + "_ENV"]` because of this conflated idea.

Apart from this behavior being counter-intuitive, it can also lead to security issues:
- Build artifacts might be stored on less-secure servers (ie inferior to production servers)
- Build artifacts might be accessible to devs, whilst a true production environment might not

I really, really think the replacement of `process.env` at build time should be revisited. And I believe I'm not the only one, considering there are over 3 stackoverflow posts of confused people.

**Comment by Dhq** [comment]
Very much agree with @PrmJf  - The case of having all env variables ready at build time simply isn't true for a lot of scenarios, definitely not for ours. The assumption that this is the case must surely be seen as a mistake in retrospect, and a way to easily opt out of it provided.

**Comment by n18l** [comment]
I need to echo @PrmJf on this as well. I've lost many hours over this issue this week prior to finding this thread, and stand to lose more looking for a workaround.

In my team's case, we're deploying an app built on nx to a server via an Azure CI/CD pipeline. The app requires several secret keys to function. Locally, each developer keeps these keys in a git-ignored `.env` file. For the deployed environment, we've defined these same keys in the pipeline's configuration UI, which makes them available to the server hosting the app so the app can access them at runtime.

In my experience this is a fairly common pattern, supported by CI/CD services from Azure, GitLab, GitHub, Vercel, and others.

Except nx appears to _actively prevent_ the app from referencing these configured server variables at runtime. It replaces any references to `process.env` with a static object containing only the environment variables it knows about at build time. This is incredibly unintuitive; it took us quite a bit of time to figure out why our app wasn't able to read our server's environment variables despite the fact that we could tunnel in and see that they were successfully being set by the pipeline.

I really hope someone can fill me in on what I'm doing wrong, or on a clean and easy way to work around nx' behaviour here. As far as I can tell, this is an inconvenient and seemingly insecure feature that would have saved me a lot of time by not existing.
