### ISSUE TITLE
Conflicting errors: "Storybook 6 is no longer maintained. Please upgrade to Storybook 7." + "No Storybook packages installed"

### ISSUE THREAD

**Issue by lindseybradford** [nrwl/nx#18499]
### Current Behavior

Existing monorepo. Added Lerna and ran the `npx lerna add-caching` command to add NX task caching. 

Tried to install storybook but get conflicting errors that I should migrate to 7 but because there are no existing instances, the migration fails with "no packages found".

### Expected Behavior

Run storybook setup configuration successfully

### Steps to Reproduce

1. Removed existing storybook instances, removed `node_modules` and `package-lock.json`
2. Attempt storybook install:
- `npm install -D @nx/storybook` (success)
- `nx g @nx/storybook:configuration {project-name} --tsConfiguration=true --uiFramework=@storybook/react-vite` (error: `Storybook 6 is no longer maintained. Please upgrade to Storybook 7`)
3. Ran requested storybook 6-7 migration (despite no instances of storybook -7): 
- `npx nx g @nx/storybook:migrate-7` (error: `No Storybook packages installed. 🚨 Nx did not find any Storybook packages installed in your workspace.  So no migration is necessary.`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.14.0
   OS     : darwin-arm64
   npm    : 9.3.1

   nx (global)    : 16.5.5
   nx             : 16.6.0
   lerna          : 7.1.4
   @nx/js         : 16.6.0
   @nx/linter     : 16.6.0
   @nx/workspace  : 16.6.0
   @nx/cypress    : 16.6.0
   @nx/devkit     : 16.6.0
   @nx/storybook  : 16.6.0
   @nrwl/tao      : 16.6.0
   typescript     : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   	 webapp_smoke_tests
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
HI there @lindseybradford ! Interesting issue! Can you please share a minumum reproduction repository that I can take a quick look at?

Or at least can you share your `package.json` for starters?

The check we're doing for logging that error during `storybook:configuration` is the following:

```
  if (storybookMajorVersion() === 6) {
    throw new Error(pleaseUpgrade());
  }
```

and the `storybookMajorVersion` function looks like this:
```
export function storybookMajorVersion(): number | undefined {
  try {
    const storybookPackageVersion = require(join(
      '@storybook/core-server',
      'package.json'
    )).version;
    return major(storybookPackageVersion);
  } catch {
    return undefined;
  }
}
```

So maybe you have `storybook/core-server` installed?
