### ISSUE TITLE
unable to run @nrwl/react:cypress-component-configuration for a build target is a nextjs project

### ISSUE THREAD

**Issue by dukemai** [nrwl/nx#18495]
### Current Behavior

I tried to run nx generate @nrwl/react:cypress-component-configuration --project={project} --generateTests=true --buildTarget={app}:build --no-interactive --dry-run

and I got
the provided build target, {project}:build, uses the '@nrwl/next:build' executor.
But only the follow executors are allowed
- @nrwl/webpack:webpack
- @nrwl/vite:build

### Expected Behavior

I can run the command to create configurations for component tests

### Steps to Reproduce

1. create component test project
2. use nx generate @nrwl/react:cypress-component-configuration to generate the configuration

### Nx Report

```shell
ERROR  The provided build target, project:build, uses the '@nrwl/next:build' executor.
But only the follow executors are allowed
- @nrwl/webpack:webpack
- @nrwl/vite:build

This is most likely because the provided --build-target is not a build target for an application.
For example, the provide build target, 'project:build' is:
- the build target for a buildable/publishable library instead of an app.
- using a different framework than expected like react library using an angular app build target.

If you do not have an app in the workspace to you can make a new app with 'nx g app' and use it just for component testing

Error: The provided --build-target does not use an executor in the allow list of executors defined.
    at findInTarget (/Users/computer/project/node_modules/@nrwl/cypress/src/utils/find-target-options.js:56:15)
    at /Users/computer/project/node_modules/@nrwl/cypress/src/utils/find-target-options.js:16:29
    at Generator.next (<anonymous>)
    at fulfilled (/Users/computer/project/node_modules/tslib/tslib.js:164:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

 >  NX   Error trying to find build configuration. Try manually specifying the build target with the --build-target flag.

   Provided project? project
   Provided build target? project:build
   Provided Executors? @nrwl/webpack:webpack, @nrwl/vite:build
   Pass --verbose to see the stacktrace.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by barbados-clemens** [comment]
hi @dukemai, the @nx/react generator assumes a react app will be used. 
since you're using next, you'll want to use the `@nx/next` generator instead. 
https://nx.dev/packages/next/generators/cypress-component-configuration#@nx/next:cypress-component-configuration
