### ISSUE TITLE
Documentation cleanup routing ...

### ISSUE THREAD

**Issue by netwobble** [nrwl/nx#185]
Hi folks,
Just spent a few days trying to get routing in multi apps and libs working.  Some quick documentation that might help others...

**1. Generating a new app with --routing** 
Currently places the routes in the app.module.ts file and not in the app-routing.module.ts file as the documentation states.  is this a bug?  Preference is to have in a separate file. In fact I think its best for all libs also for consistency, repeatable code pattern.   

**2. Documentation for lazy loading.**
While refactoring I converted some modules to lazy load.  This started to cause a lot of errors such as cant find module or not part of output.  Digging around I found tsconfig.app.ts contains pointers to any lazy loading modules that are part of the app.  In fact comments are as follows 

`/* add all lazy-loaded libraries here: "../../../libs/my-lib/index.ts" */`

It would be helpful `if` documentation stated the output and also the configurations to wire this up.  And additionally of the error message could direct to tsconfig.app.ts 

Overall super powerful and thanks for all the great work.

cheers,
AJ

**Comment by jschwarty** [comment]
@netwobble Thanks for pointing these out! We are actually working on updating the docs today and will make sure these are covered.

**Comment by jschwarty** [comment]
The update to the docs is live. [https://nrwl.io/nx/guide-nx-workspace](https://nrwl.io/nx/guide-nx-workspace)
