### ISSUE TITLE
Setting generatePackageJson to false doesn't prevent package.json from being created

### ISSUE THREAD

**Issue by aaronmccall** [nrwl/nx#18503]
### Current Behavior

I have set "generatePackJson": false in all of my publishable packages' project.json but every time I build them a package.json file is generated in the dist directory.

### Expected Behavior

Setting generatePackageJson to false would prevent package.json from being created.

### Steps to Reproduce

1. Create a project with the --bundler=vite --publishable options
2. Set targets.build.options.generatePackageJson to false
3. Run nx build <project-name>
4. Note that package.json is created in the outputPath

### Nx Report

```shell
Node   : 16.14.2
   OS     : darwin-x64
   yarn   : 1.22.19
   
   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/react          : 16.6.0
   @nrwl/tao          : 16.6.0
   @nx/vite           : 16.6.0
   @nx/web            : 16.6.0
   nx-cloud           : 16.2.0
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by meeroslav** [comment]
Thank you for reporting this @aaronmccall. It's a bug. Setting `generatePackageJson` to false should not copy the `package.json` over.

That being said, please note that `generatePackageJson` flag is being deprecated in favor of `@nx/dependency-checks` rule and in the future every publishable library will be automatically built with `package.json`.

**Comment by jaysoo** [comment]
@aaronmccall You probably have a `package.json` file in your library. We don't generate the `package.json` (i.e. automatically populate `dependencies`) in dist, but we do copy it over from source if it exists.

You have a few options:
1. Remove the `package.json` file if you really don't want it from your libraries.
2. Create a post-build script to remove the file after the fact

Generally, I don't think you want to exclude the `package.json` file if the library is intended to be published/shared. 

Closing this as `generatePackageJson` was not intended to control this behavior (and as Miro noted, it is going away soon). I would try the two options outlined above, but if you want to request a new feature you can create a new issue. Thanks.
