### ISSUE TITLE
Standardizing expo output directories

### ISSUE THREAD

**Issue by leggomuhgreggo** [nrwl/nx#18507]
### Current Behavior

Currently build output to a project dist folder eg: `apps/my-app/dist`

Also some processes output to an artifacts directory eg: `apps/my-app/artifacts`

### Expected Behavior

It seems like the convention is to put compiled outputs in a root-level folder eg: `dist/apps/my-app`, `coverage/apps/my-app`, etc

And it probably makes sense to align on either `dist` or `artifacts`

### Steps to Reproduce

_Didn't think a repro is required for this one but happy to oblige if people feel otherwise_

### Nx Report

```shell
Node   : 18.16.1
   OS     : darwin-x64
   yarn   : 1.22.19
   
   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/detox          : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/expo           : 16.6.0
   @nx/react          : 16.6.0
   @nrwl/tao          : 16.6.0
   @nx/web            : 16.6.0
   @nx/webpack        : 16.6.0
   nx-cloud           : 16.2.0
   typescript         : 5.1.6
```

### Failure Logs

```shell
n/a
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Having default output paths that are consistent with other apps is helpful in simplifying CI and cache related processes.

For example in CircleCI we want to save artifacts test results etc -- much easier to just define one root level directory for all the projects in the monorepo. 

I think it'd be useful to align the output paths for these related processes
- eas build (remote / local)
- eas download
- detox processes
- web build

<details>

<summary>Additional Considerations</summary>

Worth noting that this issue is complicated slightly by the fact that expo projects typically have multiple build targets, for each supported platform (eg iOS Android Web). And, then, there are also typically multiple build profiles (eg devclient, preview, release, etc).

In order to take advantage of Nx caching it might make sense to have some way to differentiate for each platform + profile combo -- either separate folders or filename conventions. 

</details>

Thanks for your consideration!

**Comment by guillempuche** [comment]
This is still relevant.
