### ISSUE TITLE
nx graph does not show self referencing loops 

### ISSUE THREAD

**Issue by labeled** [nrwl/nx#18519]
It would be great if the nx graph feature had a better way of showing self referenced imports. I had a developer with an issue and it wasn't easy to find where the reference was at. The error says "self referencing loop" but does not give any information as to where the bad reference is. A lot of times these bad references are because the IDE suggests the @ reference when they tab or auto import. We use the nx graph feature to see circular references easily between libraries. It doesn't show when the library references itself.

For Example,

A library `@my/lib` is being developed and has a model in it, this model file is exported via the index.ts file. Our IDE suggests importing the library via `@my/lib` and also `./models/model.ts`. I hit tab and it picks the @ reference. I now have a circular internal reference.

**Comment by meeroslav** [comment]
Closing this as not planned.
