### ISSUE TITLE
Missing documentation for Storybook translations (eg ngx-translate for Angular)

### ISSUE THREAD

**Issue by CMadden8** [nrwl/nx#18529]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

[NX Storybook Angular Docs](https://nx.dev/packages/storybook/documents/overview-angular)

### Additional context or description

This request is a follow-up to [this issue](https://github.com/nrwl/nx/issues/18510), where I mentioned `ngx-translate` as being a good candidate for documentation, as it's very common to add this library to Angular apps.

Presently, I can't get `ngx-translate` to work with Storybook.

I've recreated the issue with the least amount of code I could in [this repo](https://github.com/CMadden8/storybooktest/tree/main/org).

Note, I'm also using `ngx-translate-multi-http-loader` to merge translations from a 'shared translations' lib. That doesn't seem to be the issue, however, as Storybook won't load the translations, even with just `ngx-translate`.

**Comment by mandarini** [comment]
@CMadden8 have you managed to use `ngx-translate` with Storybook on a non-Nx repo? It seems to me that this may not be Nx-specific?

**Comment by CMadden8** [comment]
@mandarini I've opened the issue here: https://github.com/storybookjs/storybook/issues/23758

If there is no obvious solution from the NX-side, I think you can close this issue. Anyone with a similar problem can then track the solution offered from the Storybook via the provided link.

**Comment by CMadden8** [comment]
@mandarini Finally have this working, so closing the ticket. I think it would definitely be useful to have docs on `ngx-translate` for NX, as the issue does seem to be related to the NX architecture after all.

Ie - The fix requires a) a specific translateModule config for the app and another for a storybook that resides in a lib; b) a specific assets array for the app's assets and another for storybook's assets.

`project.json` assets config for the **Angular app**:

```
"assets": [
          "apps/my-app/src/favicon.ico", 
          "apps/my-app/src/assets",
          {
            "glob": "**/*",
            "input": "libs/translations-shared/src/lib/assets/il8n/",
            "output": "./assets/i18n/shared"
          }
        ],
```
`project.json` assets config for the lib's `storybook` and `build-storybook`:

```
        "assets": [
          {
            "glob": "**/*",
            "input": "apps/my-app/src/assets/il8n/",
            "output": "./assets/standard-translations"
          },
          {
            "glob": "**/*",
            "input": "libs/translations-shared/src/lib/assets/il8n/",
            "output": "./assets/shared-translations"
          }
        ]
```

The issue seems to be the `sourceRoot` defined in the lib's `project.json`. Therefore it breaks if trying to specify `"apps/my-app/src/assets"`.

Also, trying to use iln8 twice for storybook assets config results in duplicate iln8 folders in the assets folder (if you run build storybook). This actually works but looks off.

I've changed it to the above and it requires you to adjust the paths then for the storybook-specific translateModule that was created.

It's not overly complex, but it may not be the neatest solution to the issue. Either way, it's working now for both and that's good enough for me.

**Comment by mandarini** [comment]
thank you very much @CMadden8 for all the details. I will take a closer look next week, and maybe we can write a blog post about it, or a recipe. again, thank you very much!
