### ISSUE TITLE
Expandable Env Variables - revisiting

### ISSUE THREAD

**Issue by chriszrc** [nrwl/nx#18525]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I want to know if it's possible use https://github.com/motdotla/dotenv-expand? This issue was already opened here:
https://github.com/nrwl/nx/issues/4172

And saw a bunch of interest but was closed without a resolution. For everyone coming from CRA (myself included), dotenv-expand was already built-in:

https://create-react-app.dev/docs/adding-custom-environment-variables/#expanding-environment-variables-in-env

So I think it makes sense to have the default react app scaffold to implement this as well-

## Motivation

I will avoid a lot of DRY using this approach.

## Suggested Implementation

https://github.com/motdotla/dotenv-expand

**Comment by mandarini** [comment]
Adding this PR to the conversation: https://github.com/nrwl/nx/pull/17495

**Comment by chriszrc** [comment]
Vite already uses dotenv-expand:

https://vitejs.dev/guide/env-and-mode.html#:~:text=Also%2C%20Vite%20uses%20dotenv%2Dexpand%20to%20expand%20variables%20out%20of%20the%20box.

So why wouldn't it work currently?

**Comment by FrozenPandaz** [comment]
This was implemented in #18622. :tada:
