### ISSUE TITLE
Missing = in documentation for affected --exclude

### ISSUE THREAD

**Issue by radozebra** [nrwl/nx#18522]
### Documentation issue
- [ ] Reporting a typo
- [x ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/packages/nx/documents/affected#examples

### Additional context or description

this
``` nx affected -t build --exclude '*,!tag:dotnet' ```

should be this:
```  nx affected -t build --exclude='*,!tag:dotnet' ```

Without the = it did not work on my environment

Windows 11
node v16.15.1
Nx 16.5.5

**Comment by AgentEnder** [comment]
Huh, yeah this appears to work correctly on linux and mac but not windows.

**Comment by radozebra** [comment]
also for consistency sake. Everything else in this document has the long form options set with a "="
