### ISSUE TITLE
NX   Unable to resolve @nx/angular:app

### ISSUE THREAD

**Issue by tamtakoe** [nrwl/nx#18533]
### Current Behavior

When I run `nx generate @nx/angular:app web` or `nx generate @nx/angular:nest api` etc. inside any workspace (except workspace with angular/nest/etc. accordingly) I get

```
NX   Unable to resolve @nx/angular:app.

   Cannot find module '@nx/angular/package.json'
```
NX version 16.6.0

### Expected Behavior

no bug

### Steps to Reproduce

1. `npx create-nx-workspace@latest org --preset=ts --nxCloud=false`
2. `cd org`
3. `nx generate @nx/angular:app web`

### Nx Report

```shell
Node   : 18.16.0
   OS     : darwin-x64
   npm    : 9.5.1

   nx (global)        : 16.6.0
   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/nest           : 16.6.0
   @nx/node           : 16.6.0
   @nrwl/tao          : 16.6.0
   @nx/webpack        : 16.6.0
   nx-cloud           : 16.2.0
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Hi there @tamtakoe ! This is how it is supposed to work, it's expected behaviour. In order to use one of the plugins, first you have to install it, as we say in our documentation: https://nx.dev/packages/angular#setting-up-the-angular-plugin!

Please let me know if you have any other questions!
