### ISSUE TITLE
NX run commands no longer working after upgrade to > 16.4.0

### ISSUE THREAD

**Issue by RobertKievits** [nrwl/nx#18531]
### Current Behavior

After migrating / upgrading from nx 16.3.2 to 16.4.0 the NX cli can no longer find any projects. Any project that we try to run results in `Cannot find project ...`

For example:
<img width="322" alt="Scherm­afbeelding 2023-08-08 om 17 21 01" src="https://github.com/nrwl/nx/assets/3050411/4916aa4e-311b-4006-b52e-5979c482e21d">

### Expected Behavior

Nx commands should still run

### Steps to Reproduce

1. Migrate to nx > 16.4.0
2. Add: `"useDaemonProcess": false` to `tasksRunnerOptions` to make sure the daemon is not used to build the project graph
3. Run any `nx run` command

### Nx Report

```shell
>  NX   Cannot find project '${projectName}'
```

### Failure Logs
Our nx.json:
```
{
  "affected": {
    "defaultBase": "master"
  },
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx-cloud",
      "options": {
        "cacheableOperations": ["build", "lint", "test", "e2e", "build-storybook"],
        "parallel": 1,
        "useDaemonProcess": false
      }
    }
  },
  "defaultProject": "example-application",
  "generators": {
    "@nrwl/angular:application": {
      "style": "scss",
      "linter": "eslint",
      "unitTestRunner": "jest",
      "e2eTestRunner": "webdriverio"
    },
    "@nrwl/angular:library": {
      "linter": "eslint",
      "unitTestRunner": "jest",
      "strict": false
    },
    "@nrwl/angular:component": {
      "style": "scss"
    },
    "@nx/angular": {
      "application": {
        "linter": "eslint"
      },
      "library": {
        "linter": "eslint"
      },
      "storybook-configuration": {
        "linter": "eslint"
      }
    }
  },
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build"],
      "inputs": ["production", "^production"]
    },
    "lint": {
      "inputs": ["default", "{workspaceRoot}/.eslintrc.json"]
    },
    "build-storybook": {
      "inputs": ["default", "^production", "{workspaceRoot}/.storybook/**/*"]
    },
    "test": {
      "inputs": ["default", "^production", "{workspaceRoot}/jest.preset.js"]
    }
  },
  "namedInputs": {
    "default": ["{projectRoot}/**/*", "sharedGlobals"],
    "sharedGlobals": [],
    "production": [
      "default",
      "!{projectRoot}/.eslintrc.json",
      "!{projectRoot}/.storybook/**/*",
      "!{projectRoot}/**/*.stories.@(js|jsx|ts|tsx|mdx)",
      "!{projectRoot}/**/?(*.)+(spec|test).[jt]s?(x)?(.snap)",
      "!{projectRoot}/tsconfig.spec.json",
      "!{projectRoot}/jest.config.[jt]s"
    ]
  }
}
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

It breaks on both Mac and linux. After doing some investigation it seems that it breaks when not running with Daemon (as is the case on our CI environment)
And only happens when the Daemon is not running.

It seems to originate from this change: https://github.com/nrwl/nx/pull/17472/files#diff-99ba420c13a38d0aefbe2678e6ee1e0bb432c6ce0c30e95d79590ad2d0de2a35

As the `retrieveWorkspaceFiles` function called in `buildProjectGraphWithoutDaemon ` returns no projects in the projectConfiguration
When using the daemon everything works fine.

**Comment by AgentEnder** [comment]
A significant number of fixes to that area have landed since 16.4.0, can you try with latest?

**Comment by RobertKievits** [comment]
I tried with 16.6.0 and it has the same issue. It now even seems to fail when I remove the `"useDaemonProcess": false`.
I am sure something is wrong in our configuration, or more people would have reported this, but I can't seem to find what. It works perfectly up until 16.4.0-beta.6. From beta.7 upwards it can not find any projects

**Comment by FrozenPandaz** [comment]
Could you please provide a repo that we can use to reproduce the issue?

If not, could you run with `NX_NATIVE_LOGGING=nx` and post the logs please?

**Comment by RobertKievits** [comment]
I'm guessing you are not going to look into this? There are no further reports of any issues? I retried with v16.8.1 and still no luck
