### ISSUE TITLE
WARNING environments/environment.prod.ts is part of the TypeScript compilation but it's unused

### ISSUE THREAD

**Issue by mohijalili** [nrwl/nx#1853]
## Expected Behavior

remove warning during compile

## Current Behavior

```
[WDS] Warnings while compiling.
../src/environments/environment.prod.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
```

### Steps to Reproduce

1. Update to Nx 8.5.0
2. serve the poject
3. Observe the following warning: ``` ../src/environments/environment.prod.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.```

### Context

- discovered issue when attempting to update to 8.5.0

### Failure Logs

```
[WDS] Warnings while compiling.
../src/environments/environment.prod.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
```

## Other

***I removed `enableIvy: true` from `tsconfig.app.json` then the warning disappeared***

**Comment by mehrad-rafigh** [comment]
Hi @mohijalili 
Did you enable Ivy? If so, there is an issue [`here`](https://github.com/angular/angular-cli/issues/15491)

**Comment by mohijalili** [comment]
> Hi @mohijalili
> Did you enable Ivy? If so, there is an issue [`here`](https://github.com/angular/angular-cli/issues/15491)

Hey @mehrad-rafigh 
Yes, it's enabled by default. it seems it will be fixed in next update. Thanks bro.

**Comment by mehrad-rafigh** [comment]
You're welcome :) 
Would you please close the issue, since it is not related to NX?

**Comment by aegkaluk** [comment]
**tsconfig.app.json**
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "types": []
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

**Comment by MikePiper** [comment]
Is it safe to delete the file in question if it is unused?

**Comment by FadiNouh1** [comment]
> Is it safe to delete the file in question if it is unused?

No , the production build will fail

**Comment by DCHIRAGR** [comment]
i have problem

WARNING in /home/pinak/code/buyerpix/src/app/variables/charts.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
