### ISSUE TITLE
@nx/angular:webpack-browser - cached build does not respect output path

### ISSUE THREAD

**Issue by raphael22** [nrwl/nx#18532]
### Current Behavior

Same issue as https://github.com/nrwl/nx/issues/3152
but with angular:webpack-browser ?

Default dist path don't have issues.

### Expected Behavior

Custom path should work with cache.

### Steps to Reproduce

1. Create angular workspace with nx/cloud and an angular app
2. Replace default builder with @nx/angular:webpack-browser
3. Replace default outputPath
4. Build -> Output in custom path as expected.
5. Delete artifact
6. Second build with cache -> not find in custom path (nor dist)

### Nx Report

```shell
Node   : 18.16.0
   OS     : linux-x64
   npm    : 9.5.1

   nx (global)        : 16.0.3
   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/angular        : 16.6.0
   @nx/cypress        : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/plugin         : 16.6.0
   @nx/storybook      : 16.6.0
   @nrwl/tao          : 16.6.0
   @nx/web            : 16.6.0
   @nx/webpack        : 16.6.0
   nx-cloud           : 16.2.0
   typescript         : 5.1.3
   ---------------------------------------
   Community plugins:
   @jscutlery/semver       : 3.1.0
   @ngrx/data              : 16.2.0
   @ngrx/effects           : 16.2.0
   @ngrx/entity            : 16.2.0
   @ngrx/eslint-plugin     : 16.2.0
   @ngrx/router-store      : 16.2.0
   @ngrx/store             : 16.2.0
   @ngrx/store-devtools    : 16.2.0
   ngx-extended-pdf-viewer : 17.4.6
   rxjs                    : 6.6.7
   ---------------------------------------
```

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Can you try this again with the latest version of Nx?

`nx migrate latest && nx migrate --run-migrations`
or
`npx -y create-nx-workspace@latest myorg --preset=angular-monorepo`

I've just tried this out and I couldn't reproduce it.

Here's the repo I created, let me know if I changed anything incorrectly: https://github.com/Coly010/nx-custom-path-cache-issue

**Comment by raphael22** [comment]
Seems to be related to renaming "build" step.
I have a "build-lib" step which require "output" to be set for example.
Otherwise, the files built by webpack during build-lib won't output to dist when cache occurred.

```json
"build-lib": {
      "executor": "nx:run-commands",
      "outputs": ["{workspaceRoot}/dist/libs/theme"],
```

I often use "build" as wrap for build + postbuild :

```json
    "build": {
      "executor": "nx:run-commands",
      "options": {
        "commands": ["nx run theme:build-lib", "nx run theme:postbuild"],
```
