### ISSUE TITLE
Pattern flag is missing in nx show projects documentation

### ISSUE THREAD

**Issue by anckaert1998** [nrwl/nx#18542]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/packages/nx/documents/show#projects

### Additional context or description

When checking 'nx show projects --help' we see there is a --pattern flag to filter on for example "apps/*", but this is not in the documentation.

**Comment by AgentEnder** [comment]
The docs is correct, the flag should be `--projects` but the help text was incorrect for a few minor versions. Should be updated in latest.
