### ISSUE TITLE
Upgrade version @testing-library/react

### ISSUE THREAD

**Issue by tyankatsu0105** [nrwl/nx#1855]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Please describe the behavior you are expecting

Upgrade version @testing-library/react over v9.0.0

## Current Behavior

What is the current behavior?
When input `npx create-nx-workspace@latest`, generated project has `"@testing-library/react": "8.0.5"`
However react-testing/react's latest version is v9.1.4.

detail is here
https://stackoverflow.com/questions/57983635/why-we-need-aftereachcleanup

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. npx create-nx-workspace@latest

### Context

Please provide any relevant information about your setup:

- version of Nx used 8.5.0
- 3rd-party libraries and their versions @testing-library/react: 8.0.5

**A minimal reproduce scenario using allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

Please include any relevant log snippets or files here.

## Other

Any other relevant information that will help us help you.

**Comment by vsavkin** [comment]
@tyankatsu0105 would you be interested in submitting a PR? I'm happy to help you

**Comment by tyankatsu0105** [comment]
@vsavkin 
Of course!!
I'll do that :)
