### ISSUE TITLE
format:check parses file excluded via .nxignore / .gitignore

### ISSUE THREAD

**Issue by pongells** [nrwl/nx#18568]
### Current Behavior

Running `nx format:check` parses all files, even the ones that are excluded via .gitignore / .nxignore.

### Expected Behavior

Ignored files should not be parsed by `format:check`

### Steps to Reproduce

1. in the repository root create a file called `do_not_check.mjs` with some random text inside
2. add the file to `.nxignore`
3. run `nx forrmat:check`

### Nx Report

```shell
Node   : 18.16.1
   OS     : darwin-arm64
   yarn   : 3.6.1
   
   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/cypress        : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/react          : 16.6.0
   @nx/rollup         : 16.6.0
   @nx/vite           : 16.6.0
   @nx/web            : 16.6.0
   typescript         : 5.1.6
   ---------------------------------------
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Format is not filtering out ignored files in the `patterns` array:

https://github.com/nrwl/nx/blob/master/packages/nx/src/command-line/format/format.ts#L91

It can be easily fixed by adding the following:

```
import {getIgnoreObject} from "../../utils/ignore";
...
const nonIgnoredPatterns = getIgnoreObject().filter(patterns);
```

I'd create a PR but I am not sure this is the best way to fix the issue. Let me know.

**Comment by FrozenPandaz** [comment]
Sure, please open a PR. :pray:
