### ISSUE TITLE
Playwright e2e test runner doesn't run any tests

### ISSUE THREAD

**Issue by jafaircl** [nrwl/nx#18566]
### Current Behavior

When starting an Angular project with version 16.7.0-beta.x and using Playwright as the e2e test runner, no tests are actually run with the `e2e` command. They don't fail and no obvious errors are thrown. But, no tests are run.

### Expected Behavior

The test runner should find and run at least the default test.

### GitHub Repo

https://github.com/jafaircl/nx-playwright-bug

### Steps to Reproduce

1. Create a new workspace with `npx create-nx-workspace@16.7.0-beta.3` as an integrated monorepo with no initial apps.
2. Install the Angular plugin with `npm install @nx/angular@16.7.0-beta.3 --save-dev`.
3. Create an Angular app with `npx nx g @nx/angular:application`. Choose all of the default options EXCEPT to use playwright as the e2e test runner. (I named the app "my-app").
4. Run `npx nx e2e my-app-e2e`.
5. Run `npx playwright show-report dist/.playwright/apps/my-app-e2e/playwright-report` and observe that no tests actually ran

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.17.1
   OS     : darwin-arm64
   npm    : 9.6.7

   nx                 : 16.7.0-beta.3
   @nx/js             : 16.7.0-beta.3
   @nx/jest           : 16.7.0-beta.3
   @nx/linter         : 16.7.0-beta.3
   @nx/workspace      : 16.7.0-beta.3
   @nx/angular        : 16.7.0-beta.3
   @nx/cypress        : 16.7.0-beta.3
   @nx/devkit         : 16.7.0-beta.3
   @nx/eslint-plugin  : 16.7.0-beta.3
   @nx/playwright     : 16.7.0-beta.3
   @nrwl/tao          : 16.7.0-beta.3
   @nx/webpack        : 16.7.0-beta.3
   typescript         : 5.1.6
```

### Failure Logs

```shell
N/A
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I traced the issue to this line of code: https://github.com/nrwl/nx/blob/052792530209511d6c44d88ba7922cae0833e7e8/packages/playwright/src/generators/configuration/files/playwright.config.ts.template#L19

Playwright is looking in `./<>` rather than `./src` for tests. Changing the folder to `./src` fixes the issue. It's possible that #18558 may fix this behavior but I'm not sure. I'm happy to open a PR if not.

**Comment by barbados-clemens** [comment]
thanks for testing out the beta playwright plugin. 
those issues will be fixed in https://github.com/nrwl/nx/pull/18559/
