### ISSUE TITLE
Support wildcard targets in `cacheableOperations`

### ISSUE THREAD

**Issue by sdgluck** [nrwl/nx#18564]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Support for wildcard targets in the `cacheableOperations` configuration. For example:

```
  "tasksRunnerOptions": {
    "default": {
      "runner": "@vercel/remote-nx",
      "options": {
        "parallel": 3,
        "cacheableOperations": [
          "build", "test", "lint", "ts-check",
          "test:*" <-------- matches all targets beginning "test:"
        ]
      }
    }
  },
```

## Motivation

I work in a monorepo with a large number of unit tests within a single package, and logical groupings of unit tests are able to run with specific npm scripts, eg. `test:services`. Rather than have to register all of these targets directly with Nx, it would be great if Nx could accept a wildcard in targets.

## Suggested Implementation

I don't know but I'm happy to be pointed to the right place and attempt to implement this myself.

## Alternate Implementations

Similar to how the wildcard works in the `run-many` command:

```
yarn exec nx run-many -t test --projects=packages/*
```

**Comment by liqMats** [comment]
Would appreciate this feature as well!

**Comment by sdgluck** [comment]
I have made an attempt to implement this functionality [here](https://github.com/nrwl/nx/pull/18929). Let me know if this is acceptable? Happy to make any changes.

**Comment by AgentEnder** [comment]
Hey, we are working on moving in a different direction for most of the tasks runner options and won't be expanding this support here. Thanks for the idea though, if other things weren't changing it may have made sense to go this route.
