### ISSUE TITLE
Build is broken in NX 16.6.0

### ISSUE THREAD

**Issue by abrahamsaanchez** [nrwl/nx#18562]
### Current Behavior

I updated to NX 16.6.0 and I created a library with an interface, them I implement this interface in another library and when I try to build the implementation an "Cannot find module" or "File is not under 'rootDir'" error is raised.

### Expected Behavior

I should be able to build the library without errors.

### GitHub Repo

https://github.com/abrahamsaanchez/build-error

### Steps to Reproduce

1. Create an NX workspace.
2. Create a library that contains an interface.
3. Create a library that have a class implementing the interface.
4. Build the library that implements the interface.

### Nx Report

```shell
Node   : 18.15.0
OS     : linux-x64
npm    : 9.5.0

nx                 : 16.6.0
@nx/js             : 16.6.0
@nx/jest           : 16.6.0
@nx/linter         : 16.6.0
@nx/workspace      : 16.6.0
@nx/devkit         : 16.6.0
@nx/eslint-plugin  : 16.6.0
@nx/node           : 16.6.0
@nrwl/tao          : 16.6.0
typescript         : 5.1.6
---------------------------------------
Local workspace plugins:
      @build-error/infrastructure.translator
      @build-error/domain.interfaces.translator
```

### Failure Logs

```shell
Compiling with SWC for infrastructure-translator-in-memory-translator...
Successfully compiled: 2 files with swc (10.98ms)
packages/domain/interfaces/translator/src/index.ts:1:15 - error TS6059: File '.../build-error/packages/domain/interfaces/translator/src/lib/translator.ts' is not under 'rootDir' 'packages/infrastructure/translator/in-memory-translator'. 'rootDir' is expected to contain all source files.

> 1 | export * from './lib/translator';
    |               ^
  2 | 

packages/infrastructure/translator/in-memory-translator/src/lib/in-memory-translator.ts:1:28 - error TS6059: File '.../build-error/packages/domain/interfaces/translator/src/index.ts' is not under 'rootDir' 'packages/infrastructure/translator/in-memory-translator'. 'rootDir' is expected to contain all source files.

> 1 | import { Translator } from '@build-error/domain.interfaces.translator';
    |                            ^
  2 | 
  3 | export class InMemoryTranslator implements Translator {
  4 |   translate(): void {

Found 2 errors.
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

In other project, I have some interfaces created before updating to NX 16.6.0 and I can build all the libraries that depends on this interfaces, but I can not build a library created after updating to NX 16.6.0 that use the new interface or a old interface.

**Comment by FrozenPandaz** [comment]
How exactly did you configure the workspace? It seems to have some configuration issues.

1. If you are using the package-based preset, you must make dependencies via `package.json`.
2. If not, you can remove the `"extends": "nx/presets/npm.json",` extension in `nx.json` and the dependencies will be analyzed.
3. The workspace is missing target defaults for `build` to depend on `^build` which is necessary for building libraries which depend on other libraries in the correct order.

**Comment by abrahamsaanchez** [comment]
@FrozenPandaz I use the create-nx-workspace tool, I don't remember if I choose integrated or package based monorepo... I can give you more details in a few days if the repo provided do not help you

**Comment by FrozenPandaz** [comment]
Yes please, more details would help. I suspect the build logic is okay. However, the config is wrong so I would like to understand how you got into that state.

**Comment by abrahamsaanchez** [comment]
@FrozenPandaz I follow these steps:
1. Run `npx create-nx-workspace@latest`

```
✔ Where would you like to create your workspace? · build-error
✔ Which stack do you want to use? · none
✔ Package-based monorepo, integrated monorepo, or standalone project? · package-based

✔ Enable distributed caching to make your CI faster · No
```
2. Run `npm i @nx/node`
3. Generate the library with the interface using the NX generator `npx nx generate @nx/js:library --name=translator --unitTestRunner=jest --bundler=swc --directory=domain/interfaces --importPath=@build-error/domain.interfaces.translator --publishable=true --simpleName=true --no-interactive`
4. Generate the library with the implementation `npx nx generate @nx/js:library --name=in-memory-translator --unitTestRunner=jest --bundler=swc --directory=infrastructure/translator --importPath=@build-error/infrastructure.translator.in-memory-translator --publishable=true --simpleName=true --no-interactive`
5. Implement the interface in the class.

When you build the implementation, the error is raised.

Can you tell me what is wrong with the configuration? Like I said, the same thing happens in a old project when I update NX (also fails in NX 17.0.0)

**Comment by jorgeramirezamora** [comment]
I am also experiencing this going from `16.5.5` to `16.6.0`. 

This error only happens when the buildable library is using `@nx/rollup:rollup`. It does happen when is `@nx/vite:build` @FrozenPandaz

**Comment by mandarini** [comment]
@abrahamsaanchez and anyone else, is it possible that your `build` target names (of two interdependent libs) are different? This bug can appear if you are importing one buildable lib into the other, and the `build` target names are different.

related: https://github.com/nrwl/nx/issues/11289

**Comment by abrahamsaanchez** [comment]
> @abrahamsaanchez and anyone else, is it possible that your `build` target names (of two interdependent libs) are different? This bug can appear if you are importing one buildable lib into the other, and the `build` target names are different.
> 
> 
> 
> related: https://github.com/nrwl/nx/issues/11289

All my `build` targets are named `build` so this is not the error in my case

**Comment by mandarini** [comment]
@abrahamsaanchez thanks, good to know! Just checking! :)

**Comment by leosvelperez** [comment]
@abrahamsaanchez are you still facing this issue? I can't access the reproduction provided in the issue description.

Based on this thread, and as explained in https://github.com/nrwl/nx/issues/18562#issuecomment-1675403581, you seem to have `"extends": "nx/presets/npm.json"` in `nx.json`. That preset is meant to be used in package-based repos and it disables analyzing your TypeScript file sources to identify the dependencies between projects. Therefore, dependencies between projects are not picked up automatically based on your source code imports.

You have two ways of addressing this:

- Delete `"extends": "nx/presets/npm.json"` from `nx.json`, or
- Configure your dependencies in your `package.json` files

Also, make sure your target defaults are correctly configured. You can see an example setting up a package-base workspace in https://nx.dev/getting-started/tutorials/package-based-repo-tutorial.
