### ISSUE TITLE
Allow for executors in root-level scripts

### ISSUE THREAD

**Issue by ItamarGronich** [nrwl/nx#18570]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Allow for full Nx capabilities around root level scripts.
Support executors and root level `project.json` files.
Not just npm scripts.

## Motivation
In my Nx implementation, i made a semantic rule that we no longer use npm to run tasks of any kind. Only nx.
This is to avoid confusion by having multiple ways to run things.
We use custom executors that we write to wrap each task we want to run.
We want to use root level commands that run on the workspace root but we still want to use Nx executors for it since they include special logic that is useful and saves us hassle.
Npm scripts are way to limited. 

## Suggested Implementation
supporting project.json files for the root workspace too.

**Comment by AgentEnder** [comment]
This already works, you just have to create the project.json yourself.

**Comment by ItamarGronich** [comment]
@AgentEnder There's no documentation for it.
I managed to make it work.
But it's a little confusing.

Adding the project json and adding the task:
```json
{
 "targets": {
    "prettier": {
      "executor": "some-executor"
    }
  }
}
```
Then running `nx run <workspace name>:prettier` doesn't work.

It will say it doesn't know the workspace, although it exists in the package json of course.
I would expect it to pick it up from there.

While running `nx prettier` does work.
It will transalte to:
```
nx prettier

> nx run .:prettier
```
I can't find the documentation for this `.:<target>` syntax anywhere.

Adding the name property to `project.json` solves this.

Maybe some more documentation needed in the run root level scripts and in the run package documentation.
