### ISSUE TITLE
Move command misses updating export paths

### ISSUE THREAD

**Issue by neilm813** [nrwl/nx#18572]
### Current Behavior

The move CLI command appears to miss `export` statements.

In `libs/foo/src/lib/index.ts`:

`export * from @proj/bar`

When lib `bar` is renamed with the move command, this `export` statement will not be updated with the new name.

### Expected Behavior

The move command also finds `export` statements and updates the path to the new path.

### Steps to Reproduce

1. In any lib, re-export all the contents of another lib: `export * from '@proj/bar'
2. Use the move command to rename the `bar` lib
3. Observe the `export` path doesn't get updated and becomes a `Cannot find module` error.

### Nx Report

```shell
Node   : 16.18.0
   OS     : win32-x64
   npm    : 8.19.2

   nx                 : 16.5.0
   @nx/js             : 16.5.0
   @nx/jest           : 16.5.0
   @nx/linter         : 16.5.0
   @nx/workspace      : 16.5.0
   @nx/cypress        : 16.5.0
   @nx/devkit         : 16.5.0
   @nx/eslint-plugin  : 16.5.0
   @nx/express        : 16.5.0
   @nx/node           : 16.5.0
   @nx/react          : 16.5.0
   @nrwl/tao          : 16.5.0
   @nx/web            : 16.5.0
   @nx/webpack        : 16.5.0
   typescript         : 5.1.6
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Hi there @neilm813 ! I could not reproduce your issue, unfortunately! I just tried it renamed all instances of `@proj/bar`, including the exports. Can you please create a simple reproduction repository, where I can test this out?
