### ISSUE TITLE
Any plans to add ` @nx/nest:swc` ?

### ISSUE THREAD

**Issue by dfenerski** [nrwl/nx#18576]
In recent developments, `swc` is gaining popularity. 2 of my favorite technologies - nx & nest support it, but smooth migration is yet to happen.

Using the migration tool https://nx.dev/packages/js/generators/convert-to-swc one can easiliy migrate libraries, however when attempting to run it on a `nest:app` one gets the following error message:

![image](https://github.com/nrwl/nx/assets/48520530/d563c0e6-96db-43e8-af4c-1a4254d6d46c)

- [ X ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I'd love if this migration could happen automatically

## Motivation
`swc` is getting more popular

## Suggested Implementation
Writing the missing generator

## Alternate Implementations
Providing step-by-step guide to manually replace the build process of a nest app in the context of `nx` monorepo using nest's guide:
https://docs.nestjs.com/recipes/swc

**Comment by dfenerski** [comment]
Hey @AgentEnder, any hints on how to get started PRing this in case its not on the backlog?

Thanks

**Comment by ndcunningham** [comment]
Hi sorry for the late response.
 Reference the nest docs: https://docs.nestjs.com/recipes/swc  
 Their recommendation is for a monorepo is to use webpack
 > If your repository is a monorepo, then instead of using swc builder you have to configure webpack to use swc-loader.

Currently, you can enable this by update the compiler options of `withNx` or `NxWebpackAppPlugin`
https://github.com/nrwl/nx/blob/fix/node-e2e-test/packages/webpack/src/plugins/nx-webpack-plugin/nx-app-webpack-plugin-options.ts#L78

That being said I could see this working for standalone applications where the `projectRoot` is the same as the `workspaceRoot`. 
I am not sure if there is a strong motivation for this but starting off you could follow: https://nx.dev/extending-nx/recipes/local-generators
