### ISSUE TITLE
Can't find project if project root is included in .gitignore

### ISSUE THREAD

**Issue by andrey59412678** [nrwl/nx#18584]
### Current Behavior

Some of my projects are from different repositories for different reasons (I use npm meta to manage them) so naturally they are included in the workspace .gitignore file.

However, since upgrading to Nx 16 these projects are never found for any target I try to execute.

Error message is ` >  NX   Cannot find project 'myapp'`
Error can also be `The following implicitDependencies point to non-existent project(s):` depending on the case.

They also don't show up on "nx show projects" command.

I don't know the exact version this started to happen, but definitely didn't happen on 15.x

Solution I found for now: replace the pattern inside .gitignore, adding `/**`. For example:
```
// .gitignore file

// this works, project is found normally
apps/foobar/**

// this doesn't work, project not found
apps/foobar
```
So if anyone has the same problem as me, this change should probably work.

The downside of this approach is that git will not ignore the folders, even though it will never add any of the files within it, but still, it looks a bit messy.

### Expected Behavior

Nx should locate all projects containing a `project.json` file in their root folder, regardless of whether these projects are ignored by Git.

### GitHub Repo

https://github.com/nrwl/nx-examples

### Steps to Reproduce

1. Include the project root directory in the workspace's .gitignore file, such as `apps/myapp`.
2. Attempt to execute a command against it, such as `nx build myapp`; an error will be thrown saying project couldn't be found.
3. Remove the project from the .gitignore file, and it will be detected normally.

### Nx Report

```shell
Node   : 18.16.0
   OS     : linux-x64
   yarn   : 1.22.19
   
   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/cypress        : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/esbuild        : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/nest           : 16.6.0
   @nx/next           : 16.6.0
   @nx/node           : 16.6.0
   @nx/plugin         : 16.6.0
   @nx/react          : 16.6.0
   @nx/rollup         : 16.6.0
   @nx/storybook      : 16.6.0
   @nrwl/tao          : 16.6.0
   @nx/web            : 16.6.0
   @nx/webpack        : 16.6.0
   nx-cloud           : 16.2.0
   typescript         : 5.1.6
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I'm using pnpm, not sure if matters.

**Comment by AgentEnder** [comment]
Yeah, project's can't be included in gitignore. Nx uses a combination of `.gitignore` and `.nxignore` for determining which directories to parse, but one thing you should look out for is that ignored files also don't play into the hash for tasks which is a whole other can of worms.

This is intentional though, your projects need to be part of git. If you are pulling in outside repos, look into git submodules.

**Comment by andrey59412678** [comment]
> Yeah, project's can't be included in gitignore. Nx uses a combination of `.gitignore` and `.nxignore` for determining which directories to parse, but one thing you should look out for is that ignored files also don't play into the hash for tasks which is a whole other can of worms.
> 
> This is intentional though, your projects need to be part of git. If you are pulling in outside repos, look into git submodules.

git submodules solved the problem. thank you for the info
