### ISSUE TITLE
nx graph not picking up svelte files, breaking a community plugin

### ISSUE THREAD

**Issue by kryptus36** [nrwl/nx#18598]
### Current Behavior

I know svelte isn't officially supported, but there's a great plugin at https://github.com/nxext/nx-extensions and I'm hoping this is a quick fix and won't just get closed.

When you run nx graph, if you have a svelte app, none of it's dependencies are picked up.

### Expected Behavior

Svelte files should be scanned for deps and correctly reflected in the graph.

### GitHub Repo

https://github.com/kryptus36/graph-test

### Steps to Reproduce

1. clone that repo
2. run pnpm i to install deps
3. run nx graph
4. select to view all. You'll see the nestjs app shows it's lib correctly but the svelte app does not.

![image](https://github.com/nrwl/nx/assets/8608478/63793688-3bae-4d3c-94f0-1ee930aaa3c3)

### Nx Report

```shell
N/A
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

If the dep graph is broken it can affect other NX functions. The one case in point for my usage is the official nx plugins for react, angular have a script called createGlobPatternsForDependencies which is used as a helper for tailwind css to correctly scan your source tree. Otherwise you have to glob scan your entire tree. In trying to adapt that to my project, I discovered this.

I think it probably also affects nx caching functionality, though I haven't verified that.

**Comment by AgentEnder** [comment]
Nx's plugin API allows community plugins to add dependencies to the graph, and it looks like that plugin doesn't implement it. Implementing that capability is up to the plugin authors, and is why you do not see edges. Feel free to open an issue on the nx-extensions repo requesting support, but its not something that we would add here since we don't officially support svelte files.

**Comment by kryptus36** [comment]
Thanks for the quick answer!
