### ISSUE TITLE
nx-enforce-module-boundaries for source project with multiple tags

### ISSUE THREAD

**Issue by hoang-innomizetech** [nrwl/nx#1859]
# Prerequisites

I have a workspace that contains some projects with multiple tags likes below nx.json file
```
{
  "booking-api": {
    "tags": ["type:app", "scope:server", "service:booking"]
  },
  "booking-data-access": {
    "tags": ["service:booking", "scope:server"]
  },
  "booking-api-interfaces": {
    "tags": ["service:booking"]
  }
}
```

The enforce module boundaries rule is defined in the tslint.json file as below
```
"nx-enforce-module-boundaries": [
      true,
      {
        "allow": [],
        "depConstraints": [
          {
            "sourceTag": "service:booking",
            "onlyDependOnLibsWithTags": ["service:booking"]
          },
          {
            "sourceTag": "type:app",
            "onlyDependOnLibsWithTags": ["scope:shared", "scope:util"]
          },
          {
            "sourceTag": "scope:server",
            "onlyDependOnLibsWithTags": ["scope:server", "scope:shared", "scope:util"]
          },
          {
            "sourceTag": "scope:util",
            "onlyDependOnLibsWithTags": ["scope:util"]
          }
        ]
      }
    ]
```

From the `booking-api` app, I tried to import the data access from the `booking-api-interfaces`, I am getting an error

```
A project tagged with "type:app" can only depend on libs tagged with "scope:shared", "scope:util" (nx-enforce-module-boundaries)tslint(1)
```

## Expected Behavior

`booking-api` and `booking-data-access` have same tag `service:booking` so we should allow import without error. 

## Current Behavior

Lint error that prevents importing. I think right now the link only check the first tag of the source project, so the `service` tag is ignored.

**Comment by twittwer** [comment]
Why not adding a `type:xyz` to `booking-data-access` & `booking-api-interfaces`, so every project contains the same set of prefixed tags and constrains can be defined for each prefix.

```
type:(app|data-access|util|interfaces)
scope:(shared|booking)
```

```
// type constraints
{
    "sourceTag": "type:app",
    "onlyDependOnLibsWithTags": ["type:data-access", "type:util", "type:interfaces"]
},
{
    "sourceTag": "type:data-access",
    "onlyDependOnLibsWithTags": ["type:data-access", "type:util", "type:interfaces"]
},
{
    "sourceTag": "type:util",
    "onlyDependOnLibsWithTags": ["type:util", "type:interfaces"]
},
{
    "sourceTag": "type:interfaces",
    "onlyDependOnLibsWithTags": ["type:interfaces"]
},
// scope constraints
{
    "sourceTag": "scope:shared",
    "onlyDependOnLibsWithTags": ["scope:shared"]
},
{
    "sourceTag": "scope:booking",
    "onlyDependOnLibsWithTags": ["scope:booking", "scope:shared"]
}
```

```
{
  "booking-api": {
    "tags": ["platform:server", "type:app", "scope:booking"]
  },
  "booking-data-access": {
    "tags": ["platform:server", "type:data-access", "scope:booking"]
  },
  "booking-api-interfaces": {
    "tags": ["type:interfaces", "scope:booking"]
  }
}
```

**Comment by hoang-innomizetech** [comment]
@twittwer yeah, we can add `type:data-access` and `type:interfaces` tags, but it still not working. I noted that the link only picks up the last item. I have created this repo https://github.com/innomizetech/nx-dep-boundaries-example to demo. If we remove the below item, link will passed

```
{
    "sourceTag": "scope:booking",
    "onlyDependOnLibsWithTags": ["scope:booking", "scope:shared"]
}
```

**Comment by FrozenPandaz** [comment]
1. `booking-api` and `booking-data-access` have the tag `scope:server`.
2. projects with tag `scope:server` are constrained to only be able to import from projects with a tag of `scope:server`, `scope:util`, OR `scope:shared`.
3. `booking-api-interfaces` project has none of the above tags.

I would also recommend keeping all dimensions labeled on all projects.

`scope:server` should be expanded to be able to import `scope:isomorphic` and projects which are isomorphic, such as `booking-api-interfaces`, should be labeled with that tag.

I don't believe any tags are currently skipped in the lint rule.

**Comment by hoang-innomizetech** [comment]
`booking` app has 3 tags `["type:app", "scope:booking", "platform:client"]` and `api-interfaces` has the tag `api-interfaces`. Based on the rule, the booking app should able to import libs with the following tags
`"type:data-access", "type:util", "type:interfaces"` (source tag `type:app`)
`"scope:booking"` (source tag `scope:booking`)
`"platform:client"` (source tag `platform:client`)

When I try to import api-interfaces from the booking app (apps/booking/src/app/app.component.ts)
```
import { Message } from '@nx-dep-boundaries-example/api-interfaces';
import { setCookie } from '@nx-dep-boundaries-example/shared/ui-util';
```
 I am getting the following errors
```
ERROR: /github/nx-dep-boundaries-example/apps/booking/src/app/app.component.ts[3, 1]:  A project tagged with "platform:client" can only depend on libs tagged with "platform:client", "scope:shared"
ERROR: /github/nx-dep-boundaries-example/apps/booking/src/app/app.component.ts[4, 1]: A project tagged with "scope:booking" can only depend on libs tagged with "scope:booking"
```

I am not sure why the source tag `type:app` ignored/skipped. What I am missing here?

**Comment by vsavkin** [comment]
@hoang-innomizetech could you provide a whole repro? I'm not sure about the configuration you have.

**Comment by hoang-innomizetech** [comment]
@vsavkin I've provided the link on the above comment, but here you are https://github.com/innomizetech/nx-dep-boundaries-example

**Comment by ttma1046** [comment]
My guess is the constraints are like 'and' relationship not 'or'.
Since your `booking-api` has three tags, all these three need to match with the constraints.

**Comment by vdiaz1130** [comment]
I'm having a similar problem. I have a shared library under `libs/shared/entities`. In nx.json, I have the following entry:
```
"shared-entities": {
  "tags": [
    "scope:shared-entities",
    "type:entities"
  ]
}
```
I also have a data lib under `libs/data/authentication-state` and  in tslint.json I have the following:
```
{
  "sourceTag": "scope:data-authentication-state",
  "onlyDependOnLibsWithTags": ["scope:data-api", "scope:shared-entities", "type:entities"]
}
```

However, in my authentication state library, I get the following error:
```
A project tagged with "scope:data-authentication-state" can only depend on libs tagged with
 "scope:data-api", "scope:shared-entities", "type:entities"
```

It works in some cases but failing here and I can't pin-point why.

**Comment by PeterBenko** [comment]
I'd still be interested in this functionality

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by PeterBenko** [comment]
All good, just wanted to make sure the bot doesn't go through with closing or anything :)

**Comment by fbaba-nibtravel** [comment]
Hi, I'm having a similar issue. I'm trying to setup my project based on this [article](https://medium.com/showpad-engineering/how-to-programmatically-enforce-boundaries-between-applications-and-libraries-in-an-nx-monorepo-39bf8fbec6ba) which is using a similar structure described on the initial issue. But this boundaries are not working as expected on both eslint and tslint.

**Comment by Splaktar** [comment]
Are projects with multiple tags still not supported with this lint rule?

**Comment by hoang-innomizetech** [comment]
I haven't tried the latest version yet, maybe @FrozenPandaz can give us some feedback.

**Comment by meeroslav** [comment]
Nx boundary rules work as **AND** vertically and **OR** horizontally. In the following example:
```json
[
  {
    "sourceTag": "scope:first",
    "onlyDependOnLibsWithTags": ["scope:second", "scope:third"]
  },
  {
     "sourceTag": "scope:first",
      "onlyDependOnLibsWithTags": ["type:one", "type:two", "type:three"]
  }
]
```

each project imported into project marked with `scope:first` will have to defined in `nx.json` with:
 * `scope:second` **OR** `scope:third`
 **AND**
 * `type:one` **OR** `type:two` **OR** `type:three`

At least one tag in the `onlyDependOnLibsWithTags` has to be satisfied (unless defined as `*`) and **all** of the rules apply.

In the original code from @hoang-innomizetech, he defined restriction for all `type:app` to only import `scope:shared` or `scope:util` (same for third rule for `scope:server`), but then tried to import `booking-api-interfaces` which included none of these.

If you get stuck, try reducing the tags and plan them carefully (correct naming is half of the work).  If the boundaries start to feel too strict, you have probably overdone it.

**Comment by und3fin3d** [comment]
@meeroslav 
what about tags in project.json file ("project" tags)? if we have 3 tags (as from @hoang-innomizetech example) - all conditions in them have to be fullfiled or one of them (is it AND or OR in that case)?
I can't figure it out

so lets assume that "type:app" from @hoang-innomizetech  example is fulfiiled but not "scope:server", do we still get an error?

**Comment by meeroslav** [comment]
The logic stays the same. It's just moved from `nx.json` to multiple `project.json` files.

**Comment by vdiaz1130** [comment]
This is still an issue in 14.5.10.

**Comment by meeroslav** [comment]
Hi @und3fin3d, sorry for missing your question.

1. Conditions for both of the tags have to be satisfied - **AND**.
2. Yes, you would still get an error, because the second tag is not fulfilled

This of this as a dimension - first dimension (e.g. scope) is fulfilled, but the second (e.g. type) is not, so this should result in error

**Comment by meeroslav** [comment]
@vdiaz1130 can you explain what is exactly an issue on your side?

The original code has been rewritten since this issue was originally posted (in 2019) and the issue was actually a lack of understanding of how tagging work.

Check my comment above and/or read this article: https://blog.nrwl.io/mastering-the-project-boundaries-in-nx-f095852f5bf4

Let me know if this still doesn't solve your problem.
