### ISSUE TITLE
Support tsx to serve NodeJS applications

### ISSUE THREAD

**Issue by galah92** [nrwl/nx#18606]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I'd like to be able to use [tsx](https://github.com/esbuild-kit/tsx) to serve applications while developing.

## Motivation

Because it's better than all alternatives, see the [features list](https://github.com/esbuild-kit/tsx#features).

## Suggested Implementation

I'm not well versed in the Nx ecosystem, but I assume this will require a new executor.

**Comment by AgentEnder** [comment]
I'd recommend using a target that looked something like this:
```json
{
  "targets": {
    "serve": {
      "command": "tsx watch --tsconfig path/to/my/app/tsconfig.app.json path/to/my/app/main.ts"
    }
  }
}
```

Theres no current plans to add tsx as an executor to our current plugins, but a community plugin could always do so if they wished.
