### ISSUE TITLE
Webpack's withNx options is not working (specifically `skipTypeChecking`)

### ISSUE THREAD

**Issue by deser** [nrwl/nx#18618]
### Current Behavior

Trying to utilize skipTypeChecking for withNx, and ... it doesn't work.

This is how I'm doing it:
`composePlugins(withNx({ skipTypeChecking: true }), withReact(), (config)`
I added console logs directly into withNx implementation and I see the next:
```
 --------- withNx 


 undefined (this is supposed to be pluginOptions)


```

### Expected Behavior

`composePlugins(withNx({ skipTypeChecking: true }), withReact(), (config)`
Does not add `ForkTsCheckerWebpackPlugin` to webpack config. 

### Steps to Reproduce

1. Create nx workspace with ts and react built by webpack
2. Add custom webpack plugin (keeping `isolatedConfigs: false`)
3. Add there `composePlugins(withNx({ skipTypeChecking: true }), withReact(), (config) ...`

### Nx Report

```shell
nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 16.16.0
   OS     : darwin-arm64
   npm    : 8.11.0
   
   nx (global)        : 16.5.0
   nx                 : 16.5.4
   @nx/js             : 16.5.4
   @nx/jest           : 16.5.4
   @nx/linter         : 16.5.4
   @nx/workspace      : 16.5.4
   @nx/devkit         : 16.5.4
   @nx/eslint-plugin  : 16.5.4
   @nx/node           : 16.5.4
   @nx/react          : 16.5.4
   @nrwl/tao          : 16.5.4
   @nx/web            : 16.5.4
   @nx/webpack        : 16.5.4
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   nx-stylelint : 14.0.2
```

### Operating System

- [X] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

I dived a little bit into nx source code and found the reason:

Get webpack config function does not respect withNx plugin options: 

<img width="612" alt="Pasted Graphic 1" src="https://github.com/nrwl/nx/assets/3010698/45835d67-e464-4f47-b050-117a01118fb6">

<img width="772" alt="Pasted Graphic" src="https://github.com/nrwl/nx/assets/3010698/ef8f2d33-cf20-4f89-b448-437fff37e1d1">

Hope that helps

**Comment by PengyuApp** [comment]
I can reproduce this issue as well.
