### ISSUE TITLE
Option for simple output for affected:apps and affected:libs

### ISSUE THREAD

**Issue by jemerald** [nrwl/nx#1861]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Running `nx affected:apps` or `nx affected:libs` prints simple parsable console outputs.

## Current Behavior

Console output is nice looking for human, but not very parsable.

### Context

Our CI/CD pipeline parses the output of `nx affected:apps` to determine what to deploy, the output used to be simple space separated project names: `app1 app2 app3`, but now it's all fancy:

```

>  NX  Affected apps:

  - app1
  - app2
  - app3

```

And depends on the parameter passed in, it may also print out extra notes or warnings

While it does look nice to human user, it broke our pipeline.

## Suggested solution

Add a new parameter `--simple` to bring back the old behaviour of only printing space delimited affected application names.

**Comment by jemerald** [comment]
@jdpearce I'm happy to raise a PR if needed

**Comment by jdpearce** [comment]
@jemerald Thanks! It's a design change so we may have to discuss it briefly, but the idea sounds ok to me. We could probably be a bit more UNIXy with some of the nx output, but I think we've taken cues from the Angular CLI. 🤷‍♀️

**Comment by jemerald** [comment]
Sure. Any preference for the simple output format? probably the most common would be newline delimited, e.g.

```
app1
app2
app3
```

**Comment by mehrad-rafigh** [comment]
This is a diuplicate. We should move the discussion to [this issue](https://github.com/nrwl/nx/issues/1571)
