### ISSUE TITLE
"nx test libraryName" will not work after upgrading to 8.5

### ISSUE THREAD

**Issue by SeeeD** [nrwl/nx#1862]
## Expected Behavior
Running the command "nx test libname" will start jest tests for the library I defined.

## Current Behavior
After updating to 8.5 the tests will not start and the console will raise an exception containing the message: 
"An unhandled exception occurred: Project 'libname' does not support the 'test' target."

## Failure Information (for bugs)
It worked well with version 8.4.13 - after running "yarn update" the workspace and jest version is 8.5 and the error occurres.

### Context
Nrwl Version: 8.5.0

### Steps to Reproduce
1. npm init nx-workspace sample
2. ng g lib libname
3. nx test libname (this will work)
4. yarn update
5. nx test libname (this will no longer work)

You can check this repository, I did the "steps to reproduce" in 3 commits:
https://github.com/SeeeD/nrwl-jest-issue-demonstration

**Comment by FrozenPandaz** [comment]
Thank you for the repository! Unfortunately, I pulled down the repository and running `yarn test libname` works for me. I installed dependencies with `npm`. Does running `yarn test libname` work for you and is there any more information you can provide to help me reproduce the issue?

**Comment by SeeeD** [comment]
Hi @FrozenPandaz , I tested the repository on my office pc and got the same issue as on my desktop at home.

Maybe this happens in reason of my windows system? 
Here are some more machine information: 
* windows 10
* Node 10.16.3
* Yarn 1.17.3
* npm 6.9.0
* global angular cli: 7.3.4 (Maybe this, I'll update this later)

**Comment by vsavkin** [comment]
Unfortunately I cannot repro the issue. Can you try to repro it with the latest version of Nx?

**Comment by rarmatei** [comment]
as there hasn't been activity on this issue I will close for now - can you please update to latest Nx and create a new issue with some repro steps if this is still a problem? Thank you!
