### ISSUE TITLE
webpack - don't set process.env.NODE_ENV by "optimization" configuration property

### ISSUE THREAD

**Issue by danr-za** [nrwl/nx#18649]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

process.env.NODE_ENV should be set by the relevant configuration regardless of webpack optimization.

## Motivation

I encountered it now when I created a NestJS project, and running `nx build app --production` was still running with `process.env.NODE_ENV = 'development'`.
As I work with Nx for the past 5-6 years, it was a bit weird, but then I saw in the source code that it is set by the `optimization` property in the webpack configuration. The difference was that in React/Angular projects, the property is set to `true` upon generation, and in Nestjs `production` configuration is empty.

Although it is specified in Angular's documentation (only) it is not intuitive and I think that the relevant configuration should set it.
Nx (at least webpack) comes with development + production configurations by default and optionally additional ones that are added by the user. 
It would be great to have a new option to set that environment variable regardless of webpack optimization settings.

## Suggested Implementation

Add `nodeEnv` property to webpack configuration which would be set to `development` by default and `production` in production configurations.

**Comment by danr-za** [comment]
anything?

**Comment by ndcunningham** [comment]
This should be corrected with the new webpack api.
