### ISSUE TITLE
Support for @typescript-eslint/parser@v6

### ISSUE THREAD

**Issue by lucavb** [nrwl/nx#18641]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Currently the eslint-package contains this [line](https://github.com/nrwl/nx/blob/master/packages/eslint-plugin/package.json#L27) which prevents us from migrating to [typescript-eslint@^6](https://github.com/typescript-eslint/typescript-eslint). I guess this might make it a breaking change for nx as well so this will only be included in version 17? 

I also tried to find another issue targeting tihs but I was unable to find one. 

## Motivation

Well, pretty much the next major version with improvements being done by them. 

## Suggested Implementation

Updating the referenced line in the package.json and creating a migration.

**Comment by k3nsei** [comment]
Just add this to your package.json
```
"overrides": {
  "@nx/eslint-plugin": {
    "@typescript-eslint/eslint-plugin": "^6.4.0",
    "@typescript-eslint/parser": "^6.4.0",
    "eslint-config-prettier": "^9.0.0"
  },
}
`

**Comment by meeroslav** [comment]
It's already on our roadmap.

@k3nsei, it's not that simple, as it requires some code migrations.

**Comment by k3nsei** [comment]
I don't know that works for me and allowed me to have all packages to their latest versions. I don't saying that this should be solution for NX. I just quick issue solver for @lucavb

**Comment by meeroslav** [comment]
Sure, thank you @k3nsei

**Comment by JamesHenry** [comment]
The main thing we will need to do on the Nx side is update the module resolution configuration for TS: https://github.com/typescript-eslint/typescript-eslint/issues/7284

This is a more significant change than just bumping packages, and we will need to make sure we think through the ramifications for all Nx users

**Comment by eddiemonge** [comment]
Any progress on this? I know people still want to support Node versions older than 18, but 16 was end of life'd a month ago. Node 10 was EOL 3 and a half years ago. If people want to stay on dead Node versions, then they can lock their deps to versions that support that.

**Comment by meeroslav** [comment]
It's not a matter of node version. Our codebase dropped support for pre Node 16 versions some time ago. It's rather the changes this brings. 

Switching to `nodenext` means all CommonJS packages will cease to work and their import will have to be hacked. 

We will likely do this once v17 is out, due to the scope of the changes needed (check draft PR here https://github.com/nrwl/nx/pull/19368)
