### ISSUE TITLE
Nrwl: tslint - nx-enforce-module-boundaries is not finding deep import issue.

### ISSUE THREAD

**Issue by SWGeekPD** [nrwl/nx#1865]
I configured the lint rules to find the deep import issue in workspace.

But even if I am using deep import running ng lint is not finding the issue.

 **"nx-enforce-module-boundaries": [
      true,
      {
        "allow": [],
        "depConstraints": [
          {
            "sourceTag": "scope:core",
            "onlyDependOnLibsWithTags": [
              "*"
            ]
          },
          {
            "sourceTag": "scope:shared",
            "onlyDependOnLibsWithTags": [
              "scope:shared",
              "scope:api"
            ]
          }
}]**

**Comment by twittwer** [comment]
Are you running on windows? Then it may be related to #1832

**Comment by SWGeekPD** [comment]
@twittwer Yes I am running on windows.
Strange thing is when I am deploying my code into AWS , Lint is able to find those deep import issues and build is failing.

**Comment by SWGeekPD** [comment]
@FrozenPandaz  please let me know what else I need to share.

**Comment by twittwer** [comment]
> @twittwer Yes I am running on windows.
> Strange thing is when I am deploying my code into AWS , Lint is able to find those deep import issues and build is failing.

I think in AWS it's running on Linux so it can detect the violation. That sounds like the OS problem I addressed in the PR.

**Comment by SWGeekPD** [comment]
@twittwer thanks for your valuable inputs.

**Comment by twittwer** [comment]
Is your issue fixed with version 8.5.1?

**Comment by vsavkin** [comment]
Thank you for filling the issue!

It looks like the fix has been merged: https://github.com/nrwl/nx/pull/1832
