### ISSUE TITLE
enforce-module-boundaries rule not working for projects at workspace root top-level dir (no initial nested dir)

### ISSUE THREAD

**Issue by mikehaas763** [nrwl/nx#18662]
### Current Behavior

If I have projects in the workspace root top-level dir, and not nested under an initial dir such as apps, libs, packages, or projects, the enforce-module-boundaries rule fails to do any linting. It will allow root-relative paths, and relative paths. I've been able to replicate this with a new small repo on my own machine.

### Expected Behavior

The enforce-module-boundaries rule should work for workspace root level projects

### Steps to Reproduce

1. create workspace
2. create a lib or app project, can be nested or not nested, makes no difference e.g. `libs/my-lib`
3. create a lib project, placing it at the workspace root e.g. `<workspace-root>/my-other-lib`
4. in the first project created in step 2, notice how imports like these do not cause linting issues
  ```
    import { myOtherLib } from "../../../../my-lib/src";
    import { myOtherLib } from "my-lib/src";
  ```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.16.1
   OS   : darwin arm64
   npm  : 9.5.1
   
   nx : 14.5.4
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.4
   @nrwl/eslint-plugin-nx : 14.5.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.4
   @nrwl/js : 14.5.4
   @nrwl/linter : 14.5.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.3.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.5.4
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by meeroslav** [comment]
You are using a version that is now one year old. Can you migrate your solution to the latest version or at least the latest 15.x?

The error you are describing should not be happening, but we have limited capacity so we can only support 15.9.x and 16.x versions.
