### ISSUE TITLE
Not compatible with your version of node/npm: @yarnpkg/parsers@3.0.0-rc.49 when using node v16 for nx v15.8.7

### ISSUE THREAD

**Issue by LoganDupont** [nrwl/nx#18676]
### Current Behavior

Currently i'm not able to do an `npm i` for a project which use `nx v15.8.7` running on `node v16.18.1` 
I receive the follwing error
```
npm ERR! code EBADENGINEnpm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: @yarnpkg/parsers@3.0.0-rc.49
npm ERR! notsup Not compatible with your version of node/npm: @yarnpkg/parsers@3.0.0-rc.49
npm ERR! notsup Required: {"node":">=18.12.0"}
npm ERR! notsup Actual:   {"npm":"8.19.2","node":"v16.18.1"}
```
This is caused because `nx` requires `"@yarnpkg/parsers": "^3.0.0-rc.18"`

### Expected Behavior

I should be able to do an `npm install`

### Steps to Reproduce

Run npm install with node v16.8.1 and nx v15.8.7

### Nx Report

```shell
/
```

### Failure Logs

```shell
npm ERR! code EBADENGINEnpm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: @yarnpkg/parsers@3.0.0-rc.49
npm ERR! notsup Not compatible with your version of node/npm: @yarnpkg/parsers@3.0.0-rc.49
npm ERR! notsup Required: {"node":">=18.12.0"}
npm ERR! notsup Actual:   {"npm":"8.19.2","node":"v16.18.1"}
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

/

**Comment by meeroslav** [comment]
I'm wondering how your repo got that version. That must have been a manual install.

The `nx` requires version `3.0.0-rc.46` which supports node `>=14.15.0` as you can see here https://github.com/nrwl/nx/blob/master/packages/nx/package.json#L37

You can still keep that version, though, if you like, but you have to run install with `--ignore-engines`. But I would strongly suggest you use the version that `nx` requires.

**Comment by alexvy86** [comment]
Is there any suggestion for what to do for people using npm? In our case nx 15.5.2 is coming as a transitive dependency, and that version seems to be using a caret dependency that did take rc.49 (`"@yarnpkg/parsers": "^3.0.0-rc.18"`).

**Comment by LoganDupont** [comment]
@meeroslav At the time I created this bug ticket I didn't had the time to create an example repo starting from nx-examples and downgrade it to the right version. But I found another fork from some time ago which was still on `nx v15.2.4`. But when I tried to do an `npm install` it also failed with the same error when using `node v16.17.0` on this laptop 
https://github.com/LoganDupont/nx-examples-bug-angular-eslint

**Comment by LoganDupont** [comment]
After some investigation I found this change https://github.com/nrwl/nx/pull/17860 and is released in `nx v16.5.0` https://github.com/nrwl/nx/releases/tag/16.5.0.  This means that all projects that aren't using this version and are still on `node v16` are currently broken because they are using an nx version which has a dependency on `"@yarnpkg/parsers": "^3.0.0-rc.18"`. But if we take a look at the Compatibility Matrix we should move from `node v16` to `v18` starting from `nx v16`

**Comment by LoganDupont** [comment]
@AgentEnder is it possible to reopen this issue? The answer of @meeroslav is only valid when you are using at least `nx v16.5.0`

**Comment by meeroslav** [comment]
@LoganDupont, we have fixed this also in the latest `15.x` version - https://www.unpkg.com/nx@15.9.6/package.json

**Comment by LoganDupont** [comment]
Indeed, I saw this some days ago but it wasn't the case when I initially created this ticket. But thanks for fixing it!
