### ISSUE TITLE
NestJS micro-service

### ISSUE THREAD

**Issue by its-ratikant** [nrwl/nx#18688]
Just the way we have host/remote options to create micro frontends, do we have any such commands to create microservices for NestJS applications?

**Comment by its-ratikant** [comment]
Any update?

**Comment by its-ratikant** [comment]
Any update?

**Comment by ndcunningham** [comment]
Sorry for the late reply, no we do not have such commands.
Although, you are free to create a new plugin or enhance the existing ones!
