### ISSUE TITLE
@nx/dependency-checks doesn't find dependencies used by library

### ISSUE THREAD

**Issue by rafal2228** [nrwl/nx#18704]
### Current Behavior

After creating new publishable library with `@nx/js` generator, bundled with `tsc` (checked also with `rollup` bundler). The automatically added rule `@nx/dependency-checks` doesn't seem to work.

There are 2 unexpected behaviors of this rule:
- It doesn't seem to notice that used `axios` dependency is missing in `package.json` file of the project
- After manually adding it there it complains about unused dependency in `package.json`
 
 I have created a minial repro here - https://github.com/rafal2228/nx-dependency-checks-min-repro

### Expected Behavior

- Using dependency within the library should notify user that it's missing in `package.json`
- Adding dependency manually to `package.json` should not trigger an error

### GitHub Repo

https://github.com/rafal2228/nx-dependency-checks-min-repro

### Steps to Reproduce

1. Pull provided repro
2. Try running `lint` task of `test` package

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : linux-x64
   npm    : 9.5.1
   
   nx (global)        : 16.7.1
   nx                 : 16.7.1
   @nx/js             : 16.7.1
   @nx/jest           : 16.7.1
   @nx/linter         : 16.7.1
   @nx/workspace      : 16.7.1
   @nx/devkit         : 16.7.1
   @nx/eslint-plugin  : 16.7.1
   @nrwl/tao          : 16.7.1
   typescript         : 5.1.6
```

### Failure Logs

```shell
5:5  error  The "axios" package is not used by "test" project  @nx/dependency-checks

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

Lint errors found in the listed files.


 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target lint for project test (1s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
 

 *  The terminal process "/usr/bin/zsh '-c', 'npx nx run test:lint'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
Your workspace does not have JS source analysis enabled currently. We should probably enable this feature when a lib is added that requires it (e.g. for the lint rule).

For now, you can add this to your `nx.json` to manually enable it.

```json5
  "pluginsConfig": {
    "@nx/js": {
      "analyzeSourceFiles": true
    }
  }
```

**Comment by rafal2228** [comment]
> Your workspace does not have JS source analysis enabled currently. We should probably enable this feature when a lib is added that requires it (e.g. for the lint rule).
> 
> For now, you can add this to your `nx.json` to manually enable it.
> 
> ```js
>   "pluginsConfig": {
>     "@nx/js": {
>       "analyzeSourceFiles": true
>     }
>   }
> ```

That's it! Not sure why it's not on by default after generating the library, but maybe it would be a good idea to add this somewhere in the docs? I was following [this guide](https://nx.dev/packages/eslint-plugin/documents/dependency-checks#dependency-checks-rule) and wasn't aware that it is needed 🤷

**Comment by jaysoo** [comment]
We should be enabling it as needed, I'll create a PR to fix this. Nothing wrong on your end in terms of the steps you followed.
