### ISSUE TITLE
Support local env file with biggest priority

### ISSUE THREAD

**Issue by jbojcic1** [nrwl/nx#18707]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Currently, the env vars work as described [here](https://nx.dev/recipes/tips-n-tricks/define-environment-variables) and the order of the files is as follows:

1. apps/my-app/.env.[target-name].[configuration-name]
2. apps/my-app/.[target-name].[configuration-name].env
3. apps/my-app/.env.[configuration-name]
4. apps/my-app/.[configuration-name].env
5. apps/my-app/.env.[target-name]
6. apps/my-app/.[target-name].env
7. apps/my-app/.env.local
8. apps/my-app/.local.env
9. apps/my-app/.env
10. .env.[target-name].[configuration-name]
11. .[target-name].[configuration-name].env
12. .env.[configuration-name]
13. .[configuration-name].env
14. .env.[target-name]
15. .[target-name].env
16. .local.env
17. .env.local
18. .env

This means there is no way to have some local settings that can be ignored in git that would have bigger priority than `apps/my-app/.env.[target-name].[configuration-name]` for example. In my case, I have .env.development for shared dev settings but I also need the ability for each dev to have some local development settings that have bigger priority than the shared one. In next.js the order is different as it can be seen [here](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#environment-variable-load-order) but with this setup in nx it's impossible

## Motivation

It should be possible to have local non-committed file that has bigger priority than any other env file. 

## Suggested Implementation

Make it work like in next.js. One way would be to move `apps/my-app/.env.local` (and `apps/my-app/.local.env`) before other config files in `apps/my-app/`

## Alternate Implementations

Another way is to make any described path overrideable by allowing a .local suffix. So order could look something like this:

1. apps/my-app/.env.[target-name].[configuration-name].local
2. apps/my-app/.env.[target-name].[configuration-name]
3. apps/my-app/.[target-name].[configuration-name].env.local
4. apps/my-app/.[target-name].[configuration-name].env
5. apps/my-app/.env.[configuration-name].local
6. apps/my-app/.env.[configuration-name]
7. ...

**Comment by jbojcic1** [comment]
The current behavior is especially confusing when you start the app and then see the logs printed by [@next/env](https://github.com/vercel/next.js/blob/canary/packages/next-env/index.ts#L75):
```
- info Loaded env from /Users/jbojcic/playground/testing-nx/apps/testing-nx/.env.local
- info Loaded env from /Users/jbojcic/playground/testing-nx/apps/testing-nx/.env.development
- info Loaded env from /Users/jbojcic/playground/testing-nx/apps/testing-nx/.env
```

**Comment by jbojcic1** [comment]
@AgentEnder how does the fix implement what I suggested here? 

The bug was that the order from the docs is not respected, this ticket is about not having the ability to have local file (ignored in git) that has the biggest priority.

The ways how it could be achieved are explained above.

The current approach is especially confusing when you take into account that normally in Next.js .env.local has a bigger priority than .env.development which is not the case anymore when you use Next.js in Nx. And it's even more confusing that when using Next.js with Nx. if you have .env.development you will see the logs:
```
- info Loaded env from /Users/jbojcic/playground/testing-nx/apps/testing-nx/.env.local
- info Loaded env from /Users/jbojcic/playground/testing-nx/apps/testing-nx/.env.development
- info Loaded env from /Users/jbojcic/playground/testing-nx/apps/testing-nx/.env
```
even though the order from those logs is not respected with nx

**Comment by jbojcic1** [comment]
@AgentEnder is this something that might be worth implementing or you don't see this as a problem?

**Comment by stefan-schweiger** [comment]
@jbojcic1 I have created a PR which should align local files a bit more with next.js behavior, lets see if this gets accepted
https://github.com/nrwl/nx/pull/19163

**Comment by fasani-tx** [comment]
@stefan-schweiger I have an issue that my `app/.env.development` no longer seems to be loaded before `app/.env` any insight there, I also use Next + Lerna(NX).

Also, I was not able to find what `[target-name].[configuration-name]` variables are?
I think in Next `NODE_ENV` was considered, should I now pass these variables in somewhere else during dev?

**Comment by stefan-schweiger** [comment]
I'm not part of the nx team and only created the mentioned PR which was never actually merged. So for general problem with nx try the community discord or open a new issue if you think this is a new problem.
