### ISSUE TITLE
create-nx-workspace --packageManager=yarn breaks without .yarnrc

### ISSUE THREAD

**Issue by johnstew** [nrwl/nx#18705]
### Current Behavior

When we are attempting to create a workspace with the package manager set to yarn we are experiencing issues with it completing.

**Example Command**
```
npx create-nx-workspace@16.0.3 my-workspace --preset=@custom/workspace --nxCloud=false --packageManager=yarn
```

If I run the above command without a `.yarnrc` file it fails stating that it cannot find the package `@custom/workspace` which makes sense since we are using a private registry at work. 

However, we do have an `.npmrc` that should be telling yarn where to resolve the packages but when opting to use yarn as the package manager it is unable to read the correct registry from the `.npmrc` file. 

Weirdly, if I navigate to the workspace after the failure and run `yarn` it works just fine.

If I create a `.yarnrc` file with the registry information and then rerun the command it also works just fine.

Worth noting that the install works completely fine with `npm` without any issues.

### Expected Behavior

Yarn is supposed to be a drop in replacement for npm and work directly with a `.npmrc` file so from a developer experience perspective I'd expect using yarn or npm should work without having to create an additional `.yarnrc` file.

### Steps to Reproduce

1. You will need a different registry to point to in order to resolve some packages that exist there, specifically speaking a custom workspace preset would be ideal.
2. This registry will need to be configured in your `.npmrc` file. Only have an `.npmrc` file.
3. Run `npx create-nx-workspace@16.0.3 my-workspace --preset=@custom/workspace --nxCloud=false --packageManager=yarn`
4. Should see it fail

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.17.1
   OS     : darwin arm64
   yarn   : 1.22.19
   Hasher : Native

   nx             : 16.0.3
   @nx/workspace  : 16.0.3
   @nx/devkit     : 16.0.3
   @nrwl/tao      : 16.0.3
   ---------------------------------------
   Community plugins:
   @custom/workspace : 0.0.30
```

### Failure Logs

```shell
Arguments:
  /Users/John.Smith/n/bin/node /Users/John.Smith/.yarn/bin/yarn.js

PATH:
  /var/folders/ss/gym1z_wd48db267sss1llyhh0000gp/T/yarn--1692363756720-0.911088369623839:/private/var/folders/ss/gym1z_wd48db267sss1llyhh0000gp/T/tmp-74311-6VQ02joO3eRb/node_modules/.bin:/Users/John.Smith/.config/yarn/link/node_modules/.bin:/Users/John.Smith/n/libexec/lib/node_modules/npm/bin/node-gyp-bin:/Users/John.Smith/n/lib/node_modules/npm/bin/node-gyp-bin:/Users/John.Smith/n/bin/node_modules/npm/bin/node-gyp-bin:/Users/John.Smith/.npm/_npx/19d7bdaf4b960753/node_modules/.bin:/Users/John.Smith/Dev/node_modules/.bin:/Users/John.Smith/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/Users/John.Smith/n/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/Users/John.Smith/.yarn/bin:/Users/John.Smith/.config/yarn/global/node_modules/.bin:/Users/John.Smith/.rd/bin:/Users/John.Smith/.bun/bin:/Users/John.Smith/google-cloud-sdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/John.Smith/n/bin

Yarn version:
  1.22.19

Node version:
  18.17.1

Platform:
  darwin arm64

Trace:
  Error: https://registry.yarnpkg.com/@custom%2fworkspace: Not found
      at params.callback [as _callback] (/Users/John.Smith/.yarn/lib/cli.js:66145:18)
      at self.callback (/Users/John.Smith/.yarn/lib/cli.js:140890:22)
      at Request.emit (node:events:514:28)
      at Request.<anonymous> (/Users/John.Smith/.yarn/lib/cli.js:141862:10)
      at Request.emit (node:events:514:28)
      at IncomingMessage.<anonymous> (/Users/John.Smith/.yarn/lib/cli.js:141784:12)
      at Object.onceWrapper (node:events:628:28)
      at IncomingMessage.emit (node:events:526:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

npm manifest:
  {
    "name": "my-workspace",
    "version": "0.0.0",
    "license": "MIT",
    "scripts": {},
    "private": true,
    "dependencies": {
      "@custom/workspace": null
    },
    "devDependencies": {
      "@nx/workspace": "16.0.3",
      "nx": "16.0.3"
    }
  }

yarn manifest:
  No manifest

Lockfile:
  No lockfile
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

My `.npmrc` file is located in the home dir `~`.

**Comment by meeroslav** [comment]
Thank you, @johnstew for reporting this.

Our create-nx-workspace has two steps - first one runs in the temp folder to ensure installing nx is possible.
This one runs outside of your user folder so yarn doesn't detect `.npmrc` properly. This is likely related to how yarn works.

We will check the necessity for the two step process, and also consult yarn team for the direction.

**Comment by meeroslav** [comment]
So after looking a bit into how Yarn Berry (PnP) is different from Yarn Classic, we found out the Yarn Berry **does not support** reading registry from global `.npmrc`. This is not related to Nx implementation but instead dictated by Yarn.

Read more about it here: 
- https://github.com/yarnpkg/berry/issues/543#issuecomment-544455465
- https://github.com/yarnpkg/berry/issues/765#issuecomment-578422873
Or check Verdaccio's guide on how to set it up locally:
- https://verdaccio.org/fr-fr/docs/setup-yarn/#yarn-modern-2x

In order to use the local registry you need to have `.yarnrc.yml` in your user's root, which would tell yarn where to look for packages.

**Comment by johnstew** [comment]
@meeroslav We are not using yarn berry. We are using Yarn v1. I saw the PR #18767 that was doing a check for the npmrc. I believe this would solve the issue for Yarn v1 users.

**Comment by meeroslav** [comment]
Hi @johnstew, sorry for closing the issue prematurely. I was working in parallel on another Berry-related issues and had those two confused.
