### ISSUE TITLE
Micro frontend app fails when created with --standalone mode

### ISSUE THREAD

**Issue by its-ratikant** [nrwl/nx#18713]
### Current Behavior

npx create-nx-workspace rms
npm install -D @nx/angular
npx nx g @nx/angular:host dashboard --standalone
npx nx g @nx/angular:remote login --host=dashboard --standalone

nx run dashboard:serve

Failed to serve the project

### Expected Behavior

should be able to serve

### Steps to Reproduce

npx create-nx-workspace rms
npm install -D @nx/angular
npx nx g @nx/angular:host dashboard --standalone
npx nx g @nx/angular:remote login --host=dashboard --standalone

nx run dashboard:serve

### Nx Report

```shell
node_modules\@nx\angular\src\builders\module-federation-dev-server\module-federation-dev-server.impl.js:68
                throw new Error(`Remote '${remote}' failed to serve correctly due to the following: \r\n${err.toString()}`);
                      ^

Error: Remote 'ilib-user' failed to serve correctly due to the following:
Error: Invalid buildTarget: ilib-user:build:development
    at E:\Study\Projects\temp\ilibrary\node_modules\@nx\angular\src\builders\module-federation-dev-server\module-federation-dev-server.impl.js:68:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.17.0
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
I can't reproduce this on macos, assigning windows label and will try there

**Comment by Coly010** [comment]
I can't reproduce this on windows with nx version `16.7.3`.

Can you try again with the latest version of nx?

`nx migrate latest && nx migrate --run-migrations`

**Comment by its-ratikant** [comment]
works fine with v16.7.4 - thank you!
