### ISSUE TITLE
run affected after processProjectGraph

### ISSUE THREAD

**Issue by ahmadqwer** [nrwl/nx#18728]
### Current Behavior

Hello, 

I am using `processProjectGraph` in a custom plugin to edit the graph, I am editing a lot in the graph (adding new nodes, files, staticDependencies).
My issue is that when I run `nx affected` it does not take the changes i made to the graph, it seems that the affected is working before  `processProjectGraph`
Is there a way to run affected after `processProjectGraph` ?
Thank you.

### Expected Behavior

Run `affected` after `processProjectGraph`

### Steps to Reproduce

1.Edit the monorepo graph using processProjectGraph (adding new nodes, files, staticDependencies).
2.Run `nx affected`.
3. `affected` is running before the graph edits.

### Nx Report

```shell
Node   : 18.12.1
   OS     : linux x64
   pnpm   : 8.6.1
   Hasher : Native
   
   nx (global)  : 16.3.2
   nx           : 16.2.2
   @nx/devkit   : 16.7.0
   @nrwl/tao    : 16.2.2
   nx-cloud     : 16.3.0
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Can you please create a reproduction with a custom project graph plugin that shows the issue? It's hard to debug your issue without more information about what the plugin does.
