### ISSUE TITLE
projects can not be found since 16.6

### ISSUE THREAD

**Issue by DaSchTour** [nrwl/nx#18730]
### Current Behavior

`npx nx show projects` shows empty list

### Expected Behavior

`npx nx show projects` should list all projects

### Steps to Reproduce

This worked fine with 16.5, the update somehow broke it.

### Nx Report

```shell
➜ nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.17.0
   OS     : darwin-x64
   npm    : 9.6.7
   
   nx (global)        : 16.6.0
   nx                 : 16.7.2
   @nx/js             : 16.7.2
   @nx/jest           : 16.7.2
   @nx/linter         : 16.7.2
   @nx/workspace      : 16.7.2
   @nx/angular        : 16.7.2
   @nx/cypress        : 16.7.2
   @nx/devkit         : 16.7.2
   @nx/esbuild        : 16.7.2
   @nx/eslint-plugin  : 16.7.2
   @nx/nest           : 16.7.2
   @nx/node           : 16.7.2
   @nx/plugin         : 16.7.2
   @nx/rollup         : 16.7.2
   @nrwl/tao          : 16.7.2
   @nx/webpack        : 16.7.2
   nx-cloud           : 16.4.0-beta.1
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc               : 1.1.21
   @fortawesome/angular-fontawesome : 0.13.0
   @ionic/angular                   : 6.7.5
   @jscutlery/semver                : 3.0.0
   @nestjs-fixed/ng-universal       : 7.0.3
   @ngneat/spectator                : 15.0.1
   @ngrx/component                  : 16.1.0
   @ngrx/component-store            : 16.1.0
   @ngrx/data                       : 16.1.0
   @ngrx/effects                    : 16.1.0
   @ngrx/entity                     : 16.1.0
   @ngrx/eslint-plugin              : 16.1.0
   @ngrx/router-store               : 16.1.0
   @ngrx/schematics                 : 16.1.0
   @ngrx/store                      : 16.1.0
   @ngrx/store-devtools             : 16.1.0
   @nguniversal/builders            : 16.1.1
   @nguniversal/common              : 16.1.1
   @nguniversal/express-engine      : 16.1.1
   @nx-tools/nx-container           : 5.0.2
   @nxext/capacitor                 : 16.3.0
   @nxext/ionic-angular             : 16.2.0
   @trellisorg/make-buildable       : 0.0.12
   @twittwer/compodoc               : 1.10.0
   apollo-angular                   : 5.0.0
   ng-mocks                         : 14.11.0
   ngx-build-plus                   : 16.0.0
   ngx-deploy-npm                   : 7.0.1
   nx-stylelint                     : 15.0.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I actually have no idea how to debug this. I tried with nx repair but it didn't help. I have no idea where to look out for logs. I also looked into this issue https://github.com/nrwl/nx/issues/18584 and tried to comment some of my entries in my .gitignore but it didn't help.

```
# Node artifact files
node_modules/
dist/

# Compiled Java class files
*.class

# Compiled Python bytecode
*.py[cod]

# Log files
*.log

# Package files
*.jar

# Maven
target/

# Unit test reports
TEST*.xml

# Generated by MacOS
.DS_Store

# Generated by Windows
Thumbs.db

# Applications
*.app
*.exe
*.war

# Large media files
*.mp4
*.tiff
*.avi
*.flv
*.mov
*.wmv

# Coverage
coverage/

# Cache and Temp
/.angular/cache
/tmp

# additional

libs/**/src/**/*.js
apps/**/src/**/*.js
!apps/**-e2e/src/**/*.js
libs/**/src/**/*.jsx
apps/**/src/**/*.jsx
localhost+1-key.pem
localhost+1.pem
/apps/asset-search/src/generated/
/apps/asset-manager/src/generated/
/apps/**/src/environments/version.ts
/libs/**/src/environments/version.ts
/tools/executors/version/impl.js
/tools/executors/xliff-merge/impl.js
/libs/configuration/src/lib/interface.ts
/.gradle/
.idea/dataSources

.angular
**/*.gql.ts
**/generated/graphql.ts
**/generated/types.ts
/libs/model/graphql/src/graphql.ts
.env.local
.idea/sonarlint.xml
.nx-container/
```

**Comment by DaSchTour** [comment]
With this reported version everything works fine. Although a lot of projects are listed as local community plugins.

 >  NX   Report complete - copy this into the issue template

   Node   : 18.17.0
   OS     : darwin-x64
   npm    : 9.6.7
   
   nx (global)        : 16.6.0
   nx                 : 16.5.5
   @nx/js             : 16.5.5
   @nx/jest           : 16.5.5
   @nx/linter         : 16.5.5
   @nx/workspace      : 16.5.5
   @nx/angular        : 16.5.5
   @nx/cypress        : 16.5.5
   @nx/devkit         : 16.5.5
   @nx/esbuild        : 16.5.5
   @nx/eslint-plugin  : 16.5.5
   @nx/nest           : 16.5.5
   @nx/node           : 16.5.5
   @nx/plugin         : 16.5.5
   @nx/rollup         : 16.5.5
   @nrwl/tao          : 16.5.5
   @nx/webpack        : 16.5.5
   nx-cloud           : 16.1.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc               : 1.1.21
   @fortawesome/angular-fontawesome : 0.13.0
   @ionic/angular                   : 6.7.5
   @jscutlery/semver                : 3.0.0
   @nestjs-fixed/ng-universal       : 7.0.1
   @ngneat/spectator                : 15.0.1
   @ngrx/component                  : 16.1.0
   @ngrx/component-store            : 16.1.0
   @ngrx/data                       : 16.1.0
   @ngrx/effects                    : 16.1.0
   @ngrx/entity                     : 16.1.0
   @ngrx/eslint-plugin              : 16.1.0
   @ngrx/router-store               : 16.1.0
   @ngrx/schematics                 : 16.1.0
   @ngrx/store                      : 16.1.0
   @ngrx/store-devtools             : 16.1.0
   @nguniversal/builders            : 16.1.1
   @nguniversal/common              : 16.1.1
   @nguniversal/express-engine      : 16.1.1
   @nx-tools/nx-container           : 4.0.4
   @nxext/capacitor                 : 16.3.0
   @nxext/ionic-angular             : 16.2.0
   @trellisorg/make-buildable       : 0.0.12
   @twittwer/compodoc               : 1.10.0
   apollo-angular                   : 5.0.0
   ng-mocks                         : 14.11.0
   ngx-build-plus                   : 16.0.0
   ngx-deploy-npm                   : 6.0.0
   nx-stylelint                     : 15.0.0
   ---------------------------------------
   Local workspace plugins:
   	 @my-nx-scope/feature-backoffice-accounts
   	 @my-nx-scope/client-settings
   	 @my-nx-scope/feature-global-search
   	 @my-nx-scope/feature-asset-rights
   	 @my-nx-scope/state-asset-keywords
   	 @my-nx-scope/material-datepicker
   	 @my-nx-scope/shared-asset-rights
   	 @my-nx-scope/shared-distribution
   	 @my-nx-scope/state-global-search
   	 @my-nx-scope/ng-resize-observer
   	 @my-nx-scope/model-subscription
   	 @my-nx-scope/shared-user-rights
   	 @my-nx-scope/state-asset-rights
   	 @my-nx-scope/state-distribution
   	 @my-nx-scope/hateoas-operators
   	 @my-nx-scope/passport-keycloak
   	 @my-nx-scope/workspace-plugin
   	 @my-nx-scope/connector-angular
   	 @my-nx-scope/data-asset-rights
   	 @my-nx-scope/data-distribution
   	 @my-nx-scope/ng-configuration
   	 @my-nx-scope/model-server-log
   	 @my-nx-scope/sharp-operators
   	 @my-nx-scope/feature-storage
   	 @my-nx-scope/keyword-mapping
   	 @my-nx-scope/server-keywords
   	 @my-nx-scope/shared-feedback
   	 @my-nx-scope/state-clipboard
   	 @my-nx-scope/feature-toggle
   	 @my-nx-scope/connector-core
   	 @my-nx-scope/connector-nest
   	 @my-nx-scope/feature-upload
   	 @my-nx-scope/material-chips
   	 @my-nx-scope/shared-episode
   	 @my-nx-scope/shared-toolbar
   	 @my-nx-scope/common-dialog
   	 @my-nx-scope/configuration
   	 @my-nx-scope/testing-utils
   	 @my-nx-scope/feature-login
   	 @my-nx-scope/model-graphql
   	 @my-nx-scope/model-testing
   	 @my-nx-scope/ng-link-utils
   	 @my-nx-scope/service-asset
   	 @my-nx-scope/shared-search
   	 @my-nx-scope/shared-upload
   	 @my-nx-scope/state-account
   	 @my-nx-scope/state-backend
   	 @my-nx-scope/state-episode
   	 @my-nx-scope/state-keyword
   	 @my-nx-scope/state-message
   	 @my-nx-scope/state-storage
   	 @my-nx-scope/context-menu
   	 @my-nx-scope/connector-fo
   	 @my-nx-scope/data-account
   	 @my-nx-scope/data-billing
   	 @my-nx-scope/data-episode
   	 @my-nx-scope/data-keyword
   	 @my-nx-scope/data-storage
   	 @my-nx-scope/keyword-core
   	 @my-nx-scope/model-helper
   	 @my-nx-scope/model-labels
   	 @my-nx-scope/model-server
   	 @my-nx-scope/shared-album
   	 @my-nx-scope/shared-asset
   	 @my-nx-scope/state-upload
   	 @my-nx-scope/log-service
   	 @my-nx-scope/ng-download
   	 @my-nx-scope/data-search
   	 @my-nx-scope/feature-job
   	 @my-nx-scope/feature-map
   	 @my-nx-scope/model-album
   	 @my-nx-scope/model-asset
   	 @my-nx-scope/model-utils
   	 @my-nx-scope/state-album
   	 @my-nx-scope/state-asset
   	 @my-nx-scope/state-share
   	 @my-nx-scope/state-utils
   	 @my-nx-scope/date-utils
   	 @my-nx-scope/decorators
   	 @my-nx-scope/file-input
   	 @my-nx-scope/file-utils
   	 @my-nx-scope/keywording
   	 @my-nx-scope/nest-utils
   	 @my-nx-scope/nx-version
   	 @my-nx-scope/ui-actions
   	 @my-nx-scope/data-album
   	 @my-nx-scope/data-asset
   	 @my-nx-scope/data-share
   	 @my-nx-scope/model-core
   	 @my-nx-scope/shared-job
   	 @my-nx-scope/shared-map
   	 @my-nx-scope/state-auth
   	 @my-nx-scope/state-team
   	 @my-nx-scope/json-view
   	 @my-nx-scope/ng-shared
   	 @my-nx-scope/web-utils
   	 @my-nx-scope/data-core
   	 @my-nx-scope/data-team
   	 @my-nx-scope/ng-upload
   	 @my-nx-scope/state-job
   	 @my-nx-scope/ng-utils
   	 @my-nx-scope/data-job
   	 @my-nx-scope/state-ui
   	 @my-nx-scope/ng-auth
   	 @my-nx-scope/prismic
   	 @my-nx-scope/ng-spinner
   	 @my-nx-scope/camera-service
   	 @my-nx-scope/icons
   	 @my-nx-scope/utils
   	 @my-nx-scope/form
   	 @my-nx-scope/team
   	 @my-nx-scope/geo
   	 @my-nx-scope/ui

**Comment by AgentEnder** [comment]
Hey @DaSchTour, can you provide a way to reproduce this issue? A small repo that illustrates the issue would be super helpful, as this isn't something that I can reproduce.

**Comment by DaSchTour** [comment]
Well after digging through my project for days I found a `.ignore` file that contained following

```
*.json
project.json
tsconfig.json
tsconfig.*.json
projects/
```

I have no idea where it came from and why NX started using this file. But removing it solved my problem.

**Comment by josetapadas** [comment]
solved it for me too :)
