### ISSUE TITLE
Using lintProjectGenerator fails without an options.eslintFilePatterns param

### ISSUE THREAD

**Issue by jbean96** [nrwl/nx#18740]
### Current Behavior

When using a custom generator we build, it fails on the call to `lintProjectGenerator` with the following parameters:
```
const initLint = await lintProjectGenerator(tree, {
    project: projectConfig.name,
    linter: Linter.EsLint,
    skipFormat: false,
  });
```

The resulting failure is: ` >  NX   Cannot read properties of undefined (reading 'push')`

### Expected Behavior

Call to `lintProjectGenerator` does not fail.

### Steps to Reproduce

1. Create a generator that uses `lintProjectGenerator`
2. Do not provide a `eslintFilePatterns` param to the options of the generator call
3. Use the created generator

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 19.6.0
   OS     : darwin-arm64
   yarn   : 3.2.1
   
   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/cypress        : 16.6.0
   @nx/detox          : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/expo           : 16.6.0
   @nx/next           : 16.6.0
   @nx/node           : 16.6.0
   @nx/plugin         : 16.6.0
   @nx/react          : 16.6.0
   @nx/react-native   : 16.6.0
   @nx/rollup         : 16.6.0
   @nx/storybook      : 16.6.0
   @nrwl/tao          : 16.6.0
   @nx/vite           : 16.6.0
   @nx/web            : 16.6.0
   @nx/webpack        : 16.6.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @trumbitta/nx-plugin-unused-deps : 1.12.1
   ---------------------------------------
   Local workspace plugins:
         @arrived/features-verification-stepper
         @arrived/features-property-details
         @arrived/features-cash-accounts
         @arrived/features-questionnaire
         @arrived/features-checkout
         @arrived/features-tooltips
         @arrived/features-webinar
         @arrived/features-invest
         @arrived/city-pages-app
         @arrived/error-pages
         @arrived/mobile-app
         @arrived/public-app
         @arrived/bricks
         @arrived/admin-app
         @arrived/theme
         @arrived/learn-app
         @arrived/web-app
         @arrived/nx
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by meeroslav** [comment]
How do you expect the linter to work if you don't provide `eslintFilePatterns`? What paths should linter lint then?

The `lintProjectGenerator` is not meant to be a silver bullet. If it doesn't work for you, you can:
- pass an empty array as `eslintFilePatterns`
- pass any paths are remove them later using `updateJson` function from `@nx/devkit`
- implement your own lint project generator

I'm sorry this is not the answer you were looking for.

**Comment by jbean96** [comment]
> How do you expect the linter to work if you don't provide `eslintFilePatterns`? What paths should linter lint then?
> 
> The `lintProjectGenerator` is not meant to be a silver bullet. If it doesn't work for you, you can:
> 
> * pass an empty array as `eslintFilePatterns`
> * pass any paths are remove them later using `updateJson` function from `@nx/devkit`
> * implement your own lint project generator
> 
> I'm sorry this is not the answer you were looking for.

You saw the PR I put up attached to this issue but just closing the thread on this issue for others that see it. This was more about consistency with the optional argument type which we came to a resolution on here: https://github.com/nrwl/nx/pull/18741?notification_referrer_id=NT_kwDOAVvymbM3NDUxNDc2MzEwOjIyODAzMDk3#discussion_r1302011816
