### ISSUE TITLE
🐞 Nx 16.7.2: Storybook 7 not working with ReactNative

### ISSUE THREAD

**Issue by rudgal** [nrwl/nx#18756]
### Current Behavior

I'm trying to create a Nx workspace with React Native and Storybook, using corresponding Nx generators.

Unfortunately when  I try to start the App, Metro bundling fails with an error (both an Android & iOS)
` ERROR  SyntaxError: 166876:8:'import.meta' is currently unsupported, js engine: hermes`

![Screenshot 2023-08-22 at 09 19 38](https://github.com/nrwl/nx/assets/16487735/eb429a85-8aad-4db9-ad09-ea90bacda763)

### Expected Behavior

- App can be built and runs on simulator/emulator
- Storybook Toggle mechanism works
- Storybook is able to render stories for components

### GitHub Repo

https://github.com/rudgal/nx-rn-sb-issue

### Steps to Reproduce

1. Create Nx workspace: `npx create-nx-workspace nx-from-scracth --preset=react-native --appName=client/app`
2. add a simple component for Storybook
3. add Storybook: `nx g storybook-configuration client-app`
4. add async storage: `npm i @react-native-async-storage/async-storage`
    - async-storage was removed in react-native recently but is required by storybook
5. try to run app with target `run-ios` or `run-android`

These steps mirror the commit history from https://github.com/rudgal/nx-rn-sb-issue

### Nx Report

```shell
Node   : 20.5.1
   OS     : darwin-arm64
   npm    : 9.8.0
   
   nx                 : 16.7.2
   @nx/js             : 16.7.2
   @nx/jest           : 16.7.2
   @nx/linter         : 16.7.2
   @nx/workspace      : 16.7.2
   @nx/cypress        : 16.7.2
   @nx/detox          : 16.7.2
   @nx/devkit         : 16.7.2
   @nx/eslint-plugin  : 16.7.2
   @nx/react          : 16.7.2
   @nx/react-native   : 16.7.2
   @nx/storybook      : 16.7.2
   @nrwl/tao          : 16.7.2
   @nx/web            : 16.7.2
   typescript         : 5.1.6
```

### Failure Logs

```shell
ERROR  SyntaxError: 166876:8:'import.meta' is currently unsupported, js engine: hermes 
    at ToggleStorybook (http://10.0.2.2:8081/src/main.tsx.bundle//&platform=android&dev=true&minify=false&app=com.clientapp&modulesOnly=false&runModule=true:122747:41)
    at _default
    at RCTView
    at View (http://10.0.2.2:8081/src/main.tsx.bundle//&platform=android&dev=true&minify=false&app=com.clientapp&modulesOnly=false&runModule=true:59582:43)
    at RCTView
    at View (http://10.0.2.2:8081/src/main.tsx.bundle//&platform=android&dev=true&minify=false&app=com.clientapp&modulesOnly=false&runModule=true:59582:43)
    at AppContainer (http://10.0.2.2:8081/src/main.tsx.bundle//&platform=android&dev=true&minify=false&app=com.clientapp&modulesOnly=false&runModule=true:59443:36)
    at ClientApp(RootComponent) (http://10.0.2.2:8081/src/main.tsx.bundle//&platform=android&dev=true&minify=false&app=com.clientapp&modulesOnly=false&runModule=true:108221:28)
 ERROR  TypeError: Cannot read property 'default' of undefined

This error is located at:
    in ToggleStorybook (created by _default)
    in _default
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in ClientApp(RootComponent), js engine: hermes
 ERROR  TypeError: Cannot read property 'default' of undefined
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
also reference ticket https://github.com/nrwl/nx/issues/19682 here. these tickets rely on @storybook/react-native package, this package needs to be updated for storybook 7
