### ISSUE TITLE
Missing entries in the Nx dependency cache while generating federated modules.

### ISSUE THREAD

**Issue by ashish-koshy-hrblock** [nrwl/nx#18761]
### Current Behavior

While generating NX repo with federated modules, the Nx dependency cache is created with missing entries :

Associated Nx dependencies cached at:
`\node_modules\.cache\nx\nxdeps.json`:

Missing dependencies 1:
![image](https://github.com/nrwl/nx/assets/89448810/77603e1b-ddb8-4ead-8636-65b4c1047ac8)

Missing dependencies 2:
![image](https://github.com/nrwl/nx/assets/89448810/9f935274-3c5d-4a3a-bad8-ec989a42c78a)

Missing dependencies 3:
![image](https://github.com/nrwl/nx/assets/89448810/b40022b9-5615-4d74-a927-082750c0be1e)

These missing entries prevents the remote app from properly loading inside the host app when executed in a browser :
`npx nx serve user-directory --devRemotes=user-search`
![nx-botched](https://github.com/nrwl/nx/assets/89448810/eab48f98-b41f-45ed-a38a-bed7b5445219)

### Expected Behavior

The Nx dependencies must be properly resolved. The host and the federated modules must be visible in the browser:
`npx nx serve user-directory --devRemotes=user-search`
![nx-proper](https://github.com/nrwl/nx/assets/89448810/2a907dab-49ac-4fc7-b901-37bfbdf0cd7b)

### GitHub Repo

https://github.com/ashish-koshy-hrblock/nx-botched

### Steps to Reproduce

Execute the following sequence of commands as is:

1. Execute `npx create-nx-workspace@15.5.0 org`:
![image](https://github.com/nrwl/nx/assets/89448810/bb24e880-8e2f-4867-9bc5-64fc8b35f0b8)

2. Change working directory into `./org`
3. Execute `npm install --save-dev @nrwl/angular@15.5.0`
3. Execute `npx nx g @nrwl/angular:host user-directory --remotes=user-search --dynamic` :
![image](https://github.com/nrwl/nx/assets/89448810/257eb3cb-7013-43be-af67-a591b3968d97)

4. Execute `npx nx serve user-directory --devRemotes=user-search` to launch in browser.

### Nx Report

```shell
Node : 18.17.1
   OS   : win32 x64
   npm  : 9.6.7

   nx : 15.5.0
   @nrwl/angular : 15.5.0
   @nrwl/cypress : 15.5.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.0
   @nrwl/js : 15.5.0
   @nrwl/linter : 15.5.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 16.4.0-beta.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.5.0
   @nrwl/workspace : 15.5.0
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Could you please retry the same steps with the latest version of Nx? And could you provide a repo where the issue can be reproduced? The repo that you provided does not have the code that we can use to reproduce the issue.
