### ISSUE TITLE
nx 13.1.3 has an unbounded dependency on itself

### ISSUE THREAD

**Issue by OrangeDog** [nrwl/nx#18776]
### Current Behavior

When installing `nx==13.1.3` it installs a later major version (`nx==15.9.3`) as a dependency of itself.

### Expected Behavior

Packages should not depend on themselves, and especially not on newer versions of themselves.

### Steps to Reproduce

1. `npm install nx==13.1.3`  (or e.g. `@angular-devkit/core==13.3.11`)

### Nx Report

```shell
N/A
```

### Failure Logs

```shell
N/A
```

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

The problem is caused by the dependencies of `nx@13.1.3`

```
"requires": {
  "@nrwl/cli": "*"
}
```

That should instead be e.g. `"^13.1.0"`.

**Comment by FrozenPandaz** [comment]
`13.1.3` is an old version and this issue was already fixed in versions `13.3.0` and above.
