### ISSUE TITLE
js executor mistakenly treat --args "--help" as executor help instead of passing it as argument

### ISSUE THREAD

**Issue by hanstf** [nrwl/nx#18774]
### Current Behavior

Currently we are using this config
```
"serve": {
      "executor": "@nx/js:node",
      "defaultConfiguration": "local",
      "options": {
        "buildTarget": "command:build"
      },
      "configurations": {
        "local": {
          "buildTarget": "command:build",
          "inspect": false
        }
      }
    }
```
our app is a command line tools and can be passed with "--help" to get our command help

when we are running it with 
``nx run command:serve --args "--help"``

it will not display our application command help but instead it shows the @nx/js:node help

as a workaround, we run it with this:
``nx run command:serve --args ",--help"``
but this seems a bit hackish

### Expected Behavior

when calling ``nx run command:serve --args "--help"``, it should pass the help as the args instead of showing executor help

### Steps to Reproduce

1. create a cli monorepo that takes "--help" as args
2. add this targets
```
"build": {
      "executor": "@nx/webpack:webpack",
      "outputs": ["{options.outputPath}"],
      "options": {
        "target": "node",
        "compiler": "tsc",
        "outputPath": "dist/apps/command",
        "main": "apps/command/src/main.ts",
        "tsConfig": "apps/command/tsconfig.app.json",
        "isolatedConfig": true,
        "webpackConfig": "apps/command/webpack.config.js",
        "generatePackageJson": true
      }
    },
    "serve": {
      "executor": "@nx/js:node",
      "defaultConfiguration": "local",
      "options": {
        "buildTarget": "command:build"
      },
      "configurations": {
        "local": {
          "buildTarget": "command:build",
          "inspect": false
        }
      }
    }
```
3. run ``nx run command:serve --args "--help"``, it will show executor help instead of application help

### Nx Report

```shell
Node   : 16.14.2
   OS     : darwin-arm64
   npm    : 8.5.0
   
   nx                 : 16.5.2
   @nx/js             : 16.5.2
   @nx/jest           : 16.5.2
   @nx/linter         : 16.5.2
   @nx/workspace      : 16.5.2
   @nx/devkit         : 16.5.2
   @nx/eslint-plugin  : 16.5.2
   @nx/nest           : 16.5.2
   @nx/node           : 16.5.2
   @nx/plugin         : 16.5.4
   @nrwl/tao          : 16.5.2
   @nx/webpack        : 16.5.2
   typescript         : 4.8.4
   ---------------------------------------
   Local workspace plugins:
         generator
   ---------------------------------------
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
The quotes surrounding `--help` get consumed by the shell, so there's not really anything we can directly do to help support this use case. Instead, I'd recommend passing it as `--args="--help"`, which I believe should work today.

**Comment by AgentEnder** [comment]
I'm going to go ahead and close this out with the workaround provided, I don't believe there is another way to do this without drastically overcomplicating our yargs setup.
