### ISSUE TITLE
HOW to inject dynamic process.env vars

### ISSUE THREAD

**Issue by undefinederror** [nrwl/nx#18781]
I would like to access the package.json version from FE.

I am using nx 16.5.0 with React and "executor": "@nx/webpack:webpack".

I have tried to use a custom webpack.config.js with DefinePlugin or custom plugin that writes into process.env. 
DefinePlugins does nothing, the custom plugin does write (I can see the variable in console.log) but the new variable disappears when trying to access it from FE. 
Only way that works is to  define static variables  in a .env file, but this variable (version) needs to be dynamic, taken from package.json.
I have already wasted many hours on this. Any help would be much appreciated.

**Comment by ponchicken** [comment]
I have the same issue. I don't get how to define such variables properly.
We can always run custom script before every needed command, like:
```json
{
  ...
  "scripts": {
    "someapp:serve": "./apps/someapp/custom_env_script.sh && nx run someapp:serve",
    "someapp:build": "./apps/someapp/custom_env_script.sh && nx run someapp:build",
    ...
  }
}
```
and run it as `npm run someapp:build`
But it doesn't look like a handy solution

**Comment by undefinederror** [comment]
Hi @ponchicken 

Eventually I managed to set dynamic vars via DefinePlugin
https://stackoverflow.com/questions/76945536/set-package-version-as-env-var-in-nx/76970805#76970805
