### ISSUE TITLE
modules are not added to the generated package.json

### ISSUE THREAD

**Issue by LirazRom** [nrwl/nx#18808]
### Current Behavior

i have created a simple nx workspace with one app and one lib. the lib has dependency on 3 aws modules

`"dependencies": {
    "@aws-sdk/client-dynamodb": "^3.395.0",
    "@aws-sdk/client-s3": "^3.395.0",
    "@aws-sdk/lib-dynamodb": "^3.395.0"
  }`

the app code call a function of the lib. when i serve the app, build docker file - the app fail to start as it cannot find the modules. the generated package.json is

`"dependencies": {
    "@fastify/autoload": "5.7.1",
    "@fastify/sensible": "5.2.0",
    "fastify": "4.13.0",
    "fastify-plugin": "4.5.0"
  }`

why it doesnt add all the dependencies?

### Expected Behavior

to have in the package.json file also the lib dependencies

### Steps to Reproduce

1. create NX workspace
2. generate application - fastify based for example
3. generate lib
4. add in the lib npm module and use it
5. expose a function from the lib
6. consume the lib from the app
7. try to serve the app

### Nx Report

```shell
none
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Hey @LirazRom 🙂 

Apologies that it has taken a while to address this issue.

Are you still encountering this issue?
Also, would it be possible, if you are, to provide a reproduction repo?
