### ISSUE TITLE
ui frameworks for react template - chakra ui

### ISSUE THREAD

**Issue by tqmvt** [nrwl/nx#18816]
## Description
Is there a way to generate next.js project with Chakra UI?

## Motivation
For now, I see some options with CSS, Sass, Less, Styled-components, Emotion, and css-in-jsx but I don't see for Chakra ui and Tailwind CSS. It would be great to have modern ui frameworks integrated into nextjs template.

**Comment by FrozenPandaz** [comment]
No, there is no built in preset. but you should be able to add it manually afterwards.

Are you running into issues doing so?

**Comment by tqmvt** [comment]
I didn't add it manually. But if I need to, I can do that. I am just asking if we have that feature, then it would be great
