### ISSUE TITLE
SyntaxError: Invalid Unicode escape sequence

### ISSUE THREAD

**Issue by MiiZZo** [nrwl/nx#18824]
### Current Behavior

Get this error when run `pnpm nx run web:serve --prod`
C:\Users\user\Documents\projects\app\dist\packages\web\.nx-helpers\with-nx.js:19
workspaceRoot: 'C:\Users\user\Documents\projects\app',
                        ^^^^^^

There are no errors if I replace all `\` with `/` manually in workspaceRoot.

### Expected Behavior

No errors

### GitHub Repo

https://github.com/MiiZZo/rsc-posts-app

### Steps to Reproduce

1. Copy repo
2. run `nx run web:serve --prod`

### Nx Report

```shell
-
```

### Package Manager Version

pnpm@8.6.12 or yarn@1.22.19

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AlexWind96** [comment]
I have the same issue. @MiiZZo Did you find a solution to fix this?
