### ISSUE TITLE
Not able to run unit test cases (jest) _interopRequireDefault is not a function

### ISSUE THREAD

**Issue by Rajeshkumar-sivaprakasam** [nrwl/nx#18848]
### Current Behavior

 FAIL   employer-app  apps/employer-app/src/app/features/authentication/signin/signin.spec.tsx
  ● Test suite failed to run

    TypeError: [BABEL] /Users/xxxx/Desktop/code/third/XXX/node_modules/@babel/runtime/helpers/interopRequireDefault.js: _interopRequireDefault is not a function

      at Object.<anonymous> (../../node_modules/@nrwl/js/node_modules/babel-plugin-macros/dist/index.js:5:17)
      at require.extensions.<computed> (../../node_modules/ts-node/src/index.ts:1608:43)
      at require.extensions.<computed> (../../node_modules/ts-node/src/index.ts:1608:43)
      at Object.newLoader (../../node_modules/pirates/lib/index.js:141:7)

Test Suites: 1 failed, 1 total

### Expected Behavior

- White running test case it need to run. it always failing
- i am seeking some help from people

### Steps to Reproduce

1. in nx repo create react project
2. add router and other plugins what you need 
3. now if you run that test case it not running it 
4. giving config error

### Nx Report

```shell
nx test employer-app --testPathPattern=apps/employer-app/src/app/features/authentication/signin/signin.spec.tsx

> nx run employer-app:test --testPathPattern=apps/employer-app/src/app/features/authentication/signin/signin.spec.tsx

 FAIL   employer-app  apps/employer-app/src/app/features/authentication/signin/signin.spec.tsx
  ● Test suite failed to run

    TypeError: [BABEL] /Users/rajesh.kumar/Desktop/code/third/mono/node_modules/@babel/runtime/helpers/interopRequireDefault.js: _interopRequireDefault is not a function

      at Object.<anonymous> (../../node_modules/@nrwl/js/node_modules/babel-plugin-macros/dist/index.js:5:17)
      at require.extensions.<computed> (../../node_modules/ts-node/src/index.ts:1608:43)
      at require.extensions.<computed> (../../node_modules/ts-node/src/index.ts:1608:43)
      at Object.newLoader (../../node_modules/pirates/lib/index.js:141:7)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.22 s
Ran all test suites matching /apps\/employer-app\/src\/app\/features\/authentication\/signin\/signin.spec.tsx/i.

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target test for project employer-app (2s)
 
         With additional flags:
           --testPathPattern=apps/employer-app/src/app/features/authentication/signin/signin.spec.tsx
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
 
   View structured, searchable error logs at https://nx.app/runs/kC1O2FWrOI

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Operating System

- [X] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Unfortunately, I can't reproduce this issue. Could you please provide a repo where this can be reproduced?
