### ISSUE TITLE
task execution rule to not be parralel

### ISSUE THREAD

**Issue by DerHerrGammler** [nrwl/nx#18853]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description & Motivation

So my difficulty is that i got two e2e tasks that will both automaticly starts the frontend they are depending on. The problem is now that a --run-many in my ci pipeline will start them at the same time in parralel so what would be nice to habe is a configuration that said that task1 and task2 can never be running at the same time but the order of this tasks doesn't matter. So task1 can come first or task2 can come first.

## Suggested Implementation

just like the `dependsOn` array we could implement something like a `nonParallel: ["task1", "task2"]`

**Comment by DerHerrGammler** [comment]
bump

**Comment by FrozenPandaz** [comment]
I think you can join the discussion here: #23273 

I think this may solve your issue.

For now, the best way to ensure that those 2 tasks are not running at the same time, is to use `--parallel 1`.
