### ISSUE TITLE
`CreateNodes` from `NxPluginV2` should allow multiple patter for creating nodes

### ISSUE THREAD

**Issue by jogelin** [nrwl/nx#18854]
- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
In the new `NxPluginV2` interface, the property `createNodes` only allows a simple tuple like: `[projectFilePattern: string, createNodesFunction: CreateNodesFunction]`

It would be nice if multiple patterns could be specified in one plugin.

## Motivation
The current approach does not allow flexibility in how you want to group configurations. It does not allow to specify multiple patterns in one plugin. Only multiple plugins could be configured. 

For example, if I want to create a configuration for all apps, I could use the configuration:
```typescript
export const createNodes: CreateNodes = [
  'packages/**-app/project.json',
  (configFilePath, context) => {
    const name = toProjectName(configFilePath);
    return {
      root: dirname(configFilePath),
      projects: {
        [name]: {
          targets: createApplicationTargets(configFilePath)
        },
      },
    };
  },
];
```
But Then I cannot add another pattern for example now I want for `feature library` a pattern that looks like `packages/feature-**/project.json`

When you start creating project types for multiple domain dimensions and types, it can be complicated to maintain a lot of plugins. Having the possibility to group configuration on bigger plugins would help.

## Suggested Implementation
Instead of allowing only one tuple, we could allow a list of tuple:
```typescript
export type NxPluginV2 = {
  name: string;
  createNodes?: CreateNodes | CreateNodes[]; // <<<<<< HERE!
  createDependencies?: CreateDependencies;
};
```
then I could do something like:
```typescript
export const createNodes: CreateNodes = [
  [
    'packages/**-app/project.json',
    (configFilePath, context) => {
      const name = toProjectName(configFilePath);
      return {
        root: dirname(configFilePath),
        projects: {
          [name]: {
            targets: createAPPLICATIONTargets(configFilePath)
          },
        },
      };
    },
  ],
  [
    'packages/feature-**/project.json',
    (configFilePath, context) => {
      const name = toProjectName(configFilePath);
      return {
        root: dirname(configFilePath),
        projects: {
          [name]: {
            targets: createLIBRARYTargets(configFilePath)
          },
        },
      };
    },
  ];
]
```

@AgentEnder I can make a PR if it's make sense ;)

**Comment by AgentEnder** [comment]
Hey @jogelin 👋, @FrozenPandaz and I discussed a few forms of this API when we were working on the initial V2 PR. Initially, `createNodes` was an object, with key-value pairs with the same shape as the tuple that we have now. The key was the glob pattern, and the value was the `CreateNodes` function.

This offered the affordances you are wishing for, but there was a cost in that most plugins will only have 1 pattern they are recognizing. They would likely only have one implementation of the `CreateNodes` function as well. Complicating the API for them, didn't seem worth it in the end.

If you need multiple patterns, our recommendation **_today_** is to combine them into one pattern, and use a library like minimatch to determine which of your patterns the current file matches inside `CreateNodes`.

**Comment by jogelin** [comment]
@AgentEnder, Ok thanks for your response. 

This is what I am already doing with the v1 of the plugin as I explained here: [Nx Targets Elevated](https://jgelin.medium.com/nx-targets-elevated-part-two-9edc56cf1a00)

We can close it then ;)

**Comment by jogelin** [comment]
For people who are interested, I wrote something about that: [✌️ Nx Plugin v2: Dynamic Project Configurations](https://jgelin.medium.com/%EF%B8%8F-nx-plugin-v2-dynamic-project-configurations-6055ba700105
)

![image](https://github.com/nrwl/nx/assets/954509/56a89b7f-9910-4b42-9b73-56bec409dc82)
