### ISSUE TITLE
nx serve-ssr doesn't work correctly in MF + SSR case (live reload issue)

### ISSUE THREAD

**Issue by tamtakoe** [nrwl/nx#18850]
### Current Behavior

I create and run MF + SSR angular project, but `nx serve-ssr` can't properly refresh the page after changes.
I can see my changes for a split second during the page flicker when the page reloads, but I can't see the changes in `nx-welcome.component.ts` at all.

So, the first time there are no errors in the console, but after some changes and reboots I end up seeing:

```sh
NG0912: Component ID generation collision detected. Components 'NxWelcomeComponent' and 'NxWelcomeComponent' with selector 'app-ssr-nx-welcome' generated the same component ID. To fix this, you can change the selector of one of those components or add an extra host attribute to force a different ID. Find more at https://angular.io/errors/NG0912
```
I removed NxWelcomeComponents from the remotes projects and am using the module from the host project. This helped, but I see the lint warning wherever I import the component

```ts
import { NxWelcomeComponent } from '../../../../host/src/app/nx-welcome.component';
```

So I run my project with `nx serve-ssr host --devRemotes="demo,ozon"`. Everything works fine, but if I make some changes in the template of any component, I see a reload in the console, but no changes on the page, and also no changes after hard reloading the page. I stop the service and restart `nx serve-ssr` and only then I see my changes.

----

Please fix the demo project for MF + SSR angular, live reloading and documentation

### Expected Behavior

I am making some changes within the components (host and remotes) and need to see my changes on the page

### Steps to Reproduce

1.
```sh
npm install --global nx@latest
npx create-nx-workspace@latest app-ssr --preset=ts --nxCloud=false
cd app-ssr
npm install -D @nx/angular
npx nx g @nx/angular:host host --ssr --remotes=demo,ozon --e2eTestRunner="none" --style="scss"
nx serve-ssr host --devRemotes="demo,ozon"
```

2. Then I change some text inside template of all components
3. Reload page

### Nx Report

```shell
Node   : 18.16.0
   OS     : darwin-x64
   npm    : 9.5.1

   nx (global)        : 16.7.4
   nx                 : 16.7.4
   @nx/js             : 16.7.4
   @nx/jest           : 16.7.4
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.7.4
   @nx/angular        : 16.7.4
   @nx/cypress        : 16.7.4
   @nx/devkit         : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nrwl/tao          : 16.7.4
   @nx/web            : 16.7.4
   @nx/webpack        : 16.7.4
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @nguniversal/builders       : 16.2.0
   @nguniversal/express-engine : 16.2.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Hey @tamtakoe 👋 , I'll pass this on to the module federation folk. In the meantime, the tags portion of this is unrelated so I've edited the issue to remove it and improve clarity.

**Comment by johnitvn** [comment]
Any update for this bug. Even changing the code on the host will not trigger reload source code

**Comment by Coly010** [comment]
Sorry for the delay in updates on this.

We're aware of issues with live reload and HMR with SSR for Angular Module Federation. It's on our list to tackle and will be fixed after we investigate it more deeply.

There is also likely a change coming to our SSR implementation for Module Federation which may solve this issue outright.
