### ISSUE TITLE
@nx/react keeps moving itself in dependency tree

### ISSUE THREAD

**Issue by justinhandley** [nrwl/nx#18865]
### Current Behavior

Every time I run nx commands, @nx/react moves itself from production dependencies to dev dependencies.  Netlify, when trying to build my site, fails to build saying it can't find @nx/react/tailwind.,

### Expected Behavior

The dependency stays where I put it in package.json

### Steps to Reproduce

1. Put @nx/react in production dependencies 
2.  Upgrade NX ( and I think this may happen on more command like 

### Nx Report

```shell
Node   : 18.10.0
   OS     : darwin-x64
   pnpm   : 8.6.12
   
   nx (global)        : 16.5.1
   nx                 : 16.7.1
   @nx/js             : 16.7.1
   @nx/jest           : 16.7.1
   @nx/linter         : 16.7.1
   @nx/workspace      : 16.7.1
   @nx/cypress        : 16.7.1
   @nx/detox          : 16.7.1
   @nx/devkit         : 16.7.1
   @nx/eslint-plugin  : 16.7.1
   @nx/nest           : 16.7.1
   @nx/node           : 16.7.1
   @nx/plugin         : 16.7.1
   @nx/react          : 16.7.1
   @nx/react-native   : 16.7.1
   @nx/vite           : 16.7.1
   @nx/web            : 16.7.1
   @nx/webpack        : 16.7.1
   nx-cloud           : 16.4.0-beta.1
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @nx/remix : 16.4.0
   ---------------------------------------
   Local workspace plugins:
         @biztobiznownow/tools
```

### Package Manager Version

pnpm 8.6.12

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
the quick way of fixing it is to pass in the flag skipPackageJson https://nx.dev/nx-api/react/generators/application#skippackagejson when you try to generate a library or an application.
i don't think it will move the dependency around if you run the migration scripts.

**Comment by xiongemi** [comment]
i am closing this issue for now
