### ISSUE TITLE
[ESlint] `parserOptions.project` can't resolve relative path

### ISSUE THREAD

**Issue by ptu14** [nrwl/nx#18860]
### Current Behavior

When using a relative `parserOptions.project` path in the ESLint configuration, it seems that the path is not relative to the configuration file (e.g. `.eslintrc.json`) but instead relative to the working directory of the process running the CLI. This causes an error, as the `tsconfig.eslint.json` file is not found where expected.

```json
{
    "extends": ["../../.eslintrc.json"],
    "ignorePatterns": ["!**/*"],
    "overrides": [
        {
            "files": ["*.ts"],
            "parserOptions": {
                *project": ["./tsconfig.eslint.json"]
            },
        }
    ]
}
```

### Expected Behavior

I expect the `parserOptions.project` path in the ESLint configuration (`eslintrc.json`) to resolve relative to the configuration file itself, rather than the process running the CLI.

### Steps to Reproduce

1. Create an ESLint configuration file (eslintrc.json) and specify a relative path for `parserOptions.project`.
1. Navigate to a different working directory.
1. Run the ESLint CLI on a file located in a different directory without specifying the --config parameter.
1. Observe the error indicating the `tsconfig.json` file could not be found in the working directory of the process.

### Nx Report

```shell
Node   : 18.17.0
   OS     : darwin-arm64
   npm    : 9.6.7
   
   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/angular        : 16.6.0
   @nx/cypress        : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/plugin         : 16.6.0
   @nx/storybook      : 16.6.0
   @nrwl/tao          : 16.6.0
   @nx/webpack        : 16.6.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc         : 1.1.21
   @ng-bootstrap/ng-bootstrap : 15.1.1
   @ngneat/spectator          : 15.0.1
   @ngneat/transloco          : 4.3.0
   @ngrx/component-store      : 16.2.0
   @storybook/angular         : 7.2.3
   ng-mocks                   : 14.11.0
   ngx-build-plus             : 16.0.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

## Possible Solution
Switching to an `eslintrc.js` configuration and specifying the tsconfigRootDir might resolve the issue:

```javascript
module.exports = {
    parserOptions: {
        project: './tsconfig.json',
        tsconfigRootDir: __dirname,
    },
}
```

## Help us help you! 
We know that your time is precious and hate to ask for any more of it, but perhaps this issue should be addressed by the '[typescript-eslint](https://github.com/typescript-eslint/typescript-eslint)' team, and given the influence of *Nx* as a major solution, you might have the leverage to persuade the creators of that library to fix or improve this behavior.

**Comment by wszydlak** [comment]
Also eslint in v9 will switch to new configuration files:

https://eslint.org/docs/latest/use/configure/configuration-files
https://eslint.org/docs/latest/use/configure/configuration-files-new
https://eslint.org/docs/latest/use/configure/migration-guide

Maybe switching to new config files in `nx` will be good option, we can use path resolutions in `.js` files.

**Comment by AgentEnder** [comment]
There's not anything on our side that we can do to fix this, as we don't handle the parsing of eslint config files when eslint is being ran. Unfortunately, it also sounds like there isn't anything that can be done on the ts-eslint team, and they've already addressed that above.

I'm going to close this out, as mentioned when we swap over to flat configs or using a .js config file you can work around this with `__dirname`.

**Comment by ptu14** [comment]
@AgentEnder can you point me to the PR/Issue/Roadmap where you want to switch to flat-config? Don't get me wrong, but I want to make sure this issue is taken care of.
