### ISSUE TITLE
Changes to the way the proxyConfig file (@angular-devkit/build-angular:dev-server executor) is invoked

### ISSUE THREAD

**Issue by IKatsuba** [nrwl/nx#18881]
### Current Behavior

It is like #17452, but with a question. 

In NX 16.7.4, calling `process.argv` in the proxyConfig file (proxy.conf.js) in the executor @angular-devkit/build-angular:dev-server yields:
```json
[
  "...\\node.exe",
  "...\\repo\\node_modules\\nx\\bin\\run-executor.js"
]
```

I tried to use environment variables (NX_TASK_TARGET_*) instead of the third parameter, but there are no variables for the `overrides` field.

### Expected Behavior

In previous releases, calling `process.argv` in the `proxyConfig` file (proxy.conf.js) in the executor @angular-devkit/build-angular:dev-server yields:

```json
[
  "...\\node.exe",
  "...\\repo\\node_modules\\nx\\bin\\run-executor.js",
  "{"targetDescription":{"project":"ibs-ui","target":"serve","configuration":"localdev1"},"overrides":{"__overrides_unparsed__":[]},"isVerbose":false}"
]

```
The third parameter has been removed. My proxyConfig relies on knowing the configuration value ("localdev1" in the above example.) Is there another way to obtain this information in the `proxyConfig` file? If not, whatever change caused the third parameter to be removed needs to be reverted.

### Steps to Reproduce

1. Create an Angular app with a `proxyConfig` JavaScript file using NX 16.7.4
2. Add console.log(process.argv); to the proxyConfig file
3. Run the app
4. Console output will show two args.
5. Repeat 1-4 with NX 16.1.1
6. Console output will show three args, including the configuration value

### Nx Report

```shell
Node   : 18.16.0
   OS     : darwin-arm64
   npm    : 9.5.1
   
   nx                 : 16.7.4
   @nx/js             : 16.7.4
   @nx/jest           : 16.7.4
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.7.4
   @nx/angular        : 16.7.4
   @nx/cypress        : 16.7.4
   @nx/devkit         : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nx/node           : 16.7.4
   @nx/playwright     : 16.7.4
   @nrwl/tao          : 16.7.4
   @nx/web            : 16.7.4
   @nx/webpack        : 16.7.4
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @maskito/angular         : 1.4.0
   @nxkit/playwright        : 2.3.0
   @taiga-ui/cdk            : 3.26.0
   @taiga-ui/core           : 3.26.0
   @testing-library/angular : 14.1.1
   ---------------------------------------
   Local workspace plugins:
         @tree/plugin
```

### Package Manager Version

npm@9.5.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
That arg in there is an implementation detail that shouldn't be relied on. You can read `process.env.NX_TASK_TARGET_CONFIGURATION` directly if you need it. It is accurate that you can't read the overrides property from that, but those are meant for consumption by the executor.

**Comment by IKatsuba** [comment]
But what do you think I should do with this? I am already using `overrides`.

I have a lot of micro-frontend apps. And start them all too complex operations.
I start the host app with a list of remotes.
```
nx serve --devRemotes=app1,app3
```
In the proxy file, I read `overrides` and configured the proxy target; if it is included in the remotes list, the micro-frontend is proxying to the local server; if it is not, the micro-frontend is proxying to the dev stand.

With overrides, I have the flexibility to start the host with a specific child app. Without overrides, I have to be a sad developer.
