### ISSUE TITLE
load local json confused on nx

### ISSUE THREAD

**Issue by jeffkenz89** [nrwl/nx#189]
i tried but failed to load local json file in angular nx from service on  apps folder  always direction to localhost and not local folder
![image](https://user-images.githubusercontent.com/21219550/34668642-e92a504a-f4a0-11e7-853e-8f8263e99b9e.png)
 this is my angular cli  ss 
![image](https://user-images.githubusercontent.com/21219550/34668707-269506d2-f4a1-11e7-9699-f9537803eae7.png)

  
![image](https://user-images.githubusercontent.com/21219550/34668740-4c89bd6a-f4a1-11e7-934d-6ff66808fec6.png)
always error 404 because directed to localhost & not path

**Comment by vsavkin** [comment]
This is the correct request.

```
http.get('assets/db.json').subscribe(value => {
      console.log('value', value);
    });
```

**Comment by jeffkenz89** [comment]
if u have shared-asset on libs add this to your angular-cli.json 
  "assets": [
        {
          "input": "../../../libs/shared-assets/",
          "output": "assets/",
          "glob": "**/*"
        },
