### ISSUE TITLE
format: Can no longer format just app & lib files

### ISSUE THREAD

**Issue by TroyHouston** [nrwl/nx#1890]
## Expected Behavior

Before version 8.5.0 I could run format --all to format all my files inside of apps & libs & tools. 

## Current Behavior

The above behaviour no longer works as of #1776, as this functionality has been removed to instead make -all format all files in the workspace. (Does NX aim to follow SemVer?)

This causes many issues where there are auto-generated files contained in the workspace that I do not want to check for formatting, e.g. angular /dist/ folder, unit test results, etc.

For now I've had to revert to the previous version, as this stops both the developer experience and the CI builds.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Build an angular app using NX >= 8.5.0
2. Run format script
3. See errors regarding files in the /dist/ folder

### Failure Logs

![image](https://user-images.githubusercontent.com/4496632/65686496-c7129980-e0b8-11e9-8be9-fd0894ee5e7f.png)

**Comment by twittwer** [comment]
You can use a [`.prettierignore` (docs)](https://prettier.io/docs/en/ignore.html) file to exclude the auto generated files

**Comment by TroyHouston** [comment]
Didn't realise, thanks! This isn't an issue then.
