### ISSUE TITLE
How can I rerun schematics for update workspace 7 -> 8?

### ISSUE THREAD

**Issue by EvtK** [nrwl/nx#1891]
Not reporting an issues here, but a question: how can I rerun the schematics to update a workspace?

I have recently upgraded from 7.8.6 to 8.5.1 and in that process a lot of files were automatically changed due to applied schematics (changes in NgRx 8 and Angular 8). This action has been performed on the develop branch, but there are some feature branches that have added angular projects or libraries. These have been added based on 7.8.6 and so they lack to applied updates. If these features are rebased on the develop branch, I want to re-apply the schematics. 

I have tried:

`npm run update -- --from 7.8.6 --to 8.5.1 --migrate-only`

But this will not run the same actions on the files, as was done while performing the initial upgrade.

Is this in anyway possible?

**Comment by vsavkin** [comment]
> But this will not run the same actions on the files, as was done while performing the initial upgrade.

What actions aren't performed?

**Comment by EvtK** [comment]
@vsavkin thanks for checking in!. I did some further research and as it turns out, only the schematics from 8.0.0 and on were applied. I had to trick my repo with installing `@nrwl/schematics@7.8.6` to be able to get the schematics applied for upgrading to 8.0.0 :)

while this is a little hacky, it works and it is maybe not something worth provisioning something for within the nrwl schematics.

**Comment by jaysoo** [comment]
Closing this as the workaround has been found, and doesn't seem to warrant fixes in Nx.
