### ISSUE TITLE
Disabling "sub-rules" of `@nrwl/nx/enforce-module-boundaries`

### ISSUE THREAD

**Issue by gioragutt** [nrwl/nx#18918]
- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

As it stands, @nrwl/nx/enforce-module-boundaries is implemented as a single rule with different checks.
This makes it difficult, especially in a repository in a transition period, to work with the rule.
Moreover, there's clearly a bug in the rule that makes any scoped import considered an app import, which also worsens the signal2noise ratio.

I'm not sure what the performance implications of splitting the rule to different rules might be (since I guess they'd do the same work, just react to different signals in the code), but at least having the option to disable different validations of the rule would allow to improve the signal2noise ratio.

## Motivation

Improving the signal2noise ratio of a lint rule makes it so that it's less likely for people to dismiss the warnings it emits, as well as be less annoying because it would emit less false positives.

## Suggested Implementation

Provide configuration options via the eslint config to disable or otherwise configure the different validations of the rule.

## Alternate Implementations

Split the rule into several rules. But, as previously mentioned, it may have performance implications.

Another advantage of separate rules is the option to use the standard eslint comments to disable/enable parts of the validations in a file without affecting the other ones.

**Comment by meeroslav** [comment]
The rule is built as a self-propagating set of checks where checks are organized hierarchically.

Having the rule as an atomic operation makes more sense. In your case, it would maybe make sense to change the rule to run as a `warning` until you resolve the blocking issues.

Some checks are already toggleable. If you believe some others would benefit from this as well, feel free to propose that change.

But splitting the rule is currently not planned.
