### ISSUE TITLE
angular library + storybook

### ISSUE THREAD

**Issue by drodval** [nrwl/nx#18911]
### Current Behavior

when running storybook, installed as the documentation indicates, on an angular library there is the next error showed on the storybook:

`TypeError: Cannot read properties of undefined (reading 'selector')
    at computesTemplateFromComponent (http://localhost:4400/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_mjs-node_modules_storybo-10fc68.iframe.bundle.js:77897:28)
    at prepareMain (http://localhost:4400/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_mjs-node_modules_storybo-10fc68.iframe.bundle.js:78786:82)
    at http://localhost:4400/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_mjs-node_modules_storybo-10fc68.iframe.bundle.js:78772:17
    at http://localhost:4400/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_mjs-node_modules_storybo-10fc68.iframe.bundle.js:78766:14
    at cleanArgsDecorator (http://localhost:4400/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_mjs-node_modules_storybo-10fc68.iframe.bundle.js:78815:10)
    at http://localhost:4400/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_mjs-node_modules_storybo-10fc68.iframe.bundle.js:78765:28
    at http://localhost:4400/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_mjs-node_modules_storybo-10fc68.iframe.bundle.js:78766:14
    at withOutline (http://localhost:4400/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_mjs-node_modules_storybo-10fc68.iframe.bundle.js:77615:43)
    at hookified (http://localhost:4400/sb-preview/runtime.js:7:18973)
    at http://localhost:4400/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_mjs-node_modules_storybo-10fc68.iframe.bundle.js:78765:28`

### Expected Behavior

is expected to see the component rendered

### GitHub Repo

https://github.com/drodval/nx-angular-lib

### Steps to Reproduce

1. npx nx run multitodo-components-library:storybook

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.1
   OS     : darwin-x64
   npm    : 9.8.0

   nx                 : 16.5.1
   @nx/js             : 16.7.4
   @nx/jest           : 16.5.1
   @nx/linter         : 16.5.1
   @nx/workspace      : 16.5.1
   @nx/angular        : 16.5.1
   @nx/cypress        : 16.5.1
   @nx/devkit         : 16.5.1
   @nx/eslint-plugin  : 16.5.1
   @nx/storybook      : 16.7.4
   @nrwl/tao          : 16.5.1
   @nx/web            : 16.7.4
   @nx/webpack        : 16.5.1
   nx-cloud           : 16.0.5
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc : 1.1.21
   @storybook/angular : 7.4.0
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/js@16.7.4
     - @nrwl/js@16.7.4
     - @nx/storybook@16.7.4
     - @nrwl/storybook@16.7.4
     - @nx/web@16.7.4
     - @nrwl/web@16.7.4
```

### Package Manager Version

npm 9.8.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

the storybook portal is showed correctly, but the button component is not renderized in the upper part of the portal

**Comment by geromegrignon** [comment]
Hi @drodval, the repository linked is empty.

**Comment by drodval** [comment]
sorry, didn't publish it. UPDATED now. 

Thanks

**Comment by mandarini** [comment]
@drodval thanks for filing an issue! I submitted a PR to your repo: https://github.com/drodval/nx-angular-lib/pull/1

All your `@nx/*` packages should have the same version. If that's true, then you can run storybook successfully!

![Screenshot 2023-08-31 at 4 26 10 PM](https://github.com/nrwl/nx/assets/6603745/b3018b1a-3c96-4593-9243-bd74475be184)
