### ISSUE TITLE
Problem with generation of apps with Nest

### ISSUE THREAD

**Issue by aroksetx** [nrwl/nx#1894]
I am using the latest version of NX and I am stuck with issue.
I can't start the server API that was created with yarn nx g @nrwl/nest:application api command.
Every time it says Project 'api' could not be found in workspace.
I have attached a video link, please help me.
https://www.loom.com/share/bf25db39e54848f480d92ca2acedec47

**Comment by mehrad-rafigh** [comment]
Hi @aroksetx 
Can you provide a repo where someone from the community could take a look at?

**Comment by aroksetx** [comment]
> Hi @aroksetx
> Can you provide a repo where someone from the community could take a look at?

Sure link on repo:
https://github.com/aroksetx/nxhelp

**Comment by aroksetx** [comment]
I have found where was an issue.
During the workspace initialization process, it asks 

> In which directory should the node application be generated?

And I have put **'.'** because of this it created the wrong config file.
