### ISSUE TITLE
Does not build buildable libs with rollup correctly

### ISSUE THREAD

**Issue by rluvaton** [nrwl/nx#18946]
### Current Behavior

When I run `nx run lib2:build` I get the following error:
```
> nx run lib2:build

Bundling lib2...
Error during bundle: Error: libs/lib2/src/lib/lib2.tsx:1:22 - error TS2307: Cannot find module '@test/lib1' or its corresponding type declarations.

1 import { Lib1 } from '@test/lib1';
```

### Expected Behavior

to not have errors at all

### GitHub Repo

[Repro](https://github.com/rluvaton/nx-bug-18946)

### Steps to Reproduce

nx run `nx run lib2:build`

### Nx Report

```shell
nx report
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 16.18.1
   OS     : darwin-arm64
   npm    : 8.19.2

   nx                 : 16.7.4
   @nx/js             : 16.7.4
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.7.4
   @nx/devkit         : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nx/react          : 16.7.4
   @nx/rollup         : 16.7.4
   @nrwl/tao          : 16.7.4
   @nx/vite           : 16.7.4
   @nx/web            : 16.7.4
   typescript         : 5.1.6
```

### Failure Logs

```shell
❯ nx run lib2:build --verbose --skip-nx-cache

 >  NX   Running target build for project lib2 and 1 task it depends on:

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

> nx run lib1:build

Bundling lib1...
  index.esm.js 234 Bytes
⚡ Done in 1.04s

> nx run lib2:build

Bundling lib2...
Error during bundle: Error: libs/lib2/src/lib/lib2.tsx:1:22 - error TS2307: Cannot find module '@test/lib1' or its corresponding type declarations.

1 import { Lib1 } from '@test/lib1';
                       ~~~~~~~~~~~~

Bundle failed: lib2

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target build for project lib2 and 1 task it depends on failed

   Failed tasks:

   - lib2:build

   Hint: run the command with --verbose for more details.
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

if you look at the `dist` folder, the lib1 package json shows this:
```json
{
  "name": "@test/lib1",
  "version": "0.0.1",
  "main": "./index.js",
  "types": "./index.d.ts",
  "exports": {
    ".": {
      "import": "./index.mjs",
      "require": "./index.js"
    }
  },
  "module": "./index.esm.js",
  "type": "module"
}
```

while the folder content is this (`main` and `types` does not point to the right file):
```
❯ ls dist/libs/lib1
README.md        index.esm.css    index.esm.d.ts   index.esm.js     package.json     src              vite.config.d.ts
```

**Comment by KamalAman** [comment]
It seems like all of these issues reported are probably released to this:

https://github.com/nrwl/nx/issues/16821
https://github.com/nrwl/nx/issues/17019
https://github.com/nrwl/nx/issues/18349

**Comment by KamalAman** [comment]
Switching await from @nx/rollup to vite seems to be a workaround, and probably for the better.

**Comment by steve-lorenz** [comment]
@KamalAman I was experiencing similar issues, using vite for `@nx/react` seemed to work, but I was also trying to do the same for `@nx/react-native` that seems to use `@nx/rollup` would this be a web only workaround?

**Comment by KamalAman** [comment]
I guess so, hopefully nx starts prioritizing this issue.

I have no idea why they switched the updateBuildableProjectDepsInPackageJson flag for that eslint rule. I think these issues are all related to that switch.

**Comment by mandarini** [comment]
@rluvaton  and anyone else, is it possible that your `build` target names (of two interdependent libs) are different? This bug can appear if you are importing one buildable lib into the other, and the `build` target names are different. I am not saying that's the issue you are facing, I'm just saying that this issue can appear under this circumstance.

related: https://github.com/nrwl/nx/issues/11289

**Comment by rluvaton** [comment]
Checked and it's not the case

**Comment by rluvaton** [comment]
So I checked it and I found that this problem happened when moving `@nx/rollup` from 16.5.5 to 16.6.0

**Comment by steve-lorenz** [comment]
Just wanted to update this thread, I migrated and upgraded to `v17.1.3` and this works for me now. @rluvaton not sure if that's an option for you or not, but just wanted to ping the thread as this might be fixed now

**Comment by rluvaton** [comment]
The issue still happening on the latest version
