### ISSUE TITLE
[FR] Possibility to disable NX Cloud caching on a per-project basis

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [nrwl/nx#18984]
## Description

Our webapp has a big assets folder (At the moment, 6454 files, 450 MB).
We're looking into migrating to NX and are encountering this error: "Request body larger than maxBodyLength limit (code: ERR_BAD_REQUEST)"
The reason seems obvious after reading this issue: https://github.com/nrwl/nx/issues/7688
Ideally we would like to store all our assets in one NX project and disable NX cloud caching for that project.
Could be that we opt for another approach as most files (4871 files) are specific to one module, so could be that we just add them to the corresponding NX project and disable NX cloud caching for that NX project.
However, all that is dependent on being able to disable NX cloud caching on a per-NX-project basis.

## Motivation

As applications that are used by NX grow in size and start to have bigger assets (and other deliverables) and more apps (and libs) it will become more important that some parts of these apps can opt out of caching where it doesn't make sense while other parts don't.
And it's exactly these sort of big projects that probably have this the most that also need remote caching the most.

## Suggested Implementation

A per-project configuration item in project.json: isOptingOutOfCloudCache
if present and if true; this will not cache the project in NX Cloud.

**Comment by AgentEnder** [comment]
Solved in v17
