### ISSUE TITLE
Jest options `watch` and `watch-all`  do not currently work for new Angular projects, but are present in the documentation

### ISSUE THREAD

**Issue by Exac** [nrwl/nx#18982]
### Current Behavior

https://nx.dev/packages/jest/executors/jest#watch
The developer reads the documentation for jest, and assumes that watch mode will work for Angular.

### Expected Behavior

When creating a new Angular project, running the unit tests with the `--watch` or `--watch-all` commands should make the unit tests run when the files are changed.

### GitHub Repo

https://github.com/Exac/nx-watch-repro/tree/main/example

### Steps to Reproduce

1. Clone
2. Change to the `example` directory
3. Run `nx run exampleapp:test --watch` or `nx run exampleapp:test --watch-all`
4. The unit tests will run
5. Change `app.component.ts`

At this point we expect the jest tests to run again because the file has changed. This doesn't happen.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template
                                                            
   Node   : 18.17.1                                         
   OS     : linux-x64                                       
   yarn   : 1.22.19                                         
                                                            
   nx (global)        : 16.7.4                              
   nx                 : 16.7.4                              
   @nx/js             : 16.7.4                              
   @nx/jest           : 16.7.4                              
   @nx/linter         : 16.7.4                              
   @nx/workspace      : 16.7.4                              
   @nx/angular        : 16.7.4                              
   @nx/cypress        : 16.7.4                              
   @nx/devkit         : 16.7.4                              
   @nx/eslint-plugin  : 16.7.4                              
   @nrwl/tao          : 16.7.4                              
   @nx/web            : 16.7.4
   @nx/webpack        : 16.7.4
   typescript         : 5.1.6
```

### Package Manager Version

yarn 1.22.19

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

We discussed this in Discord: https://discord.com/channels/1143497901675401286/1147306104569729084

I am not sure, but I believe that it could be related to this: https://stackoverflow.com/a/76189518

Jest is available as a developer preview for Angular, but the `watch` target option for jest is not yet implemented: https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/build_angular/src/builders/jest/schema.json

I believe the watch mode _used_ to work for Angular nx projects.

We should at least add a note in the documentation page that `watch` and `watch-all` do not currently work for Angular. I think it is pretty critical considering the first step most devs will take when beginning a new project is to start the dev server and run the unit tests in watch mode.

**Comment by LayZeeDK** [comment]
I had a chance to try your repo. It works when I do
```shell
nx test exampleapp -- --watch
```
or
```shell
nx test exampleapp -- --watch-all
```
(notice `--` between the command and its parameters)

**Comment by LayZeeDK** [comment]
If I change your repo from Yarn Classic (1.x) to latest (3.x), the `--` forwarding parameter isn't needed.

**Comment by AgentEnder** [comment]
I'm going to go ahead and close this out, as @LayZeeDK mentioned it appears your yarn command is consuming the flags before they get to Nx

**Comment by Exac** [comment]
Many thanks to @LayZeeDK for checking out the repo. I switched from Windows 10 LTSC + WSL 2, to Windows 11 22621 and it works. Seems like the file system watcher was broken in earlier versions of WSL.
