### ISSUE TITLE
running nx format --uncommitted goes through all files if using prettier 3

### ISSUE THREAD

**Issue by leon** [nrwl/nx#18992]
### Current Behavior

I'm running `nx format --uncommitted` om a husky pre-commit.

it runs through all files in our monorepo taking over 20sec

### Expected Behavior

to only run on the uncommitted files.

### Steps to Reproduce

1. take whatever nx repo and update to prettier 3
2. run `nx format --uncommitted`
3. see how it goes through all files

### Nx Report

```shell
Node   : 18.15.0
   OS     : darwin-arm64
   pnpm   : 8.5.1
   
   nx                 : 16.7.4
   @nx/js             : 16.7.4
   @nx/jest           : 16.7.4
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.7.4
   @nx/angular        : 16.7.4
   @nx/cypress        : 16.7.4
   @nx/devkit         : 16.7.4
   @nx/esbuild        : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nx/nest           : 16.7.4
   @nx/node           : 16.7.4
   @nrwl/tao          : 16.7.4
   @nx/webpack        : 16.7.4
   nx-cloud           : 16.3.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @testing-library/angular : 14.3.0
   ng2-charts               : 5.0.3
```

### Package Manager Version

pnpm 8.5.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by minijusl** [comment]
Observing the same issue after update to prettier v3.

**Comment by karlismelderis-mckinsey** [comment]
Seems like `nx format:write --files` is also ignoring `--files` and is formatting whole project now

**Comment by minijusl** [comment]
Temporary fix could be to use [patch-package](https://www.npmjs.com/package/patch-package) with this patch applied:
```patch
diff --git a/node_modules/nx/src/command-line/format/format.js b/node_modules/nx/src/command-line/format/format.js
index 4691116..f8f9cf2 100644
--- a/node_modules/nx/src/command-line/format/format.js
+++ b/node_modules/nx/src/command-line/format/format.js
@@ -51,8 +51,7 @@ async function getPatterns(args) {
             return getPatternsFromProjects(args.projects, graph);
         }
         const p = (0, command_line_utils_1.parseFiles)(args);
-        const supportedExtensions = prettier
-            .getSupportInfo()
+        const supportedExtensions = (await prettier.getSupportInfo())
             .languages.flatMap((language) => language.extensions)
             .filter((extension) => !!extension)
             // Prettier supports ".swcrc" as a file instead of an extension

```

**Comment by tnrich** [comment]
Also experiencing this and it is making my commits very slow. Can we get a fix for this please :)

**Comment by karlismelderis-mckinsey** [comment]
we just stopped used NX for formatting.
Replaced all with `pnpm prettier` and lint staged is passing in list of files that chagned

Less dependencies, Less things that can get broken 🤷
