### ISSUE TITLE
@nx/js run-type-check.ts getTypeCheckResult support exclude node_modules error

### ISSUE THREAD

**Issue by cbl980226** [nrwl/nx#18994]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

https://github.com/microsoft/TypeScript/issues/47387#issuecomment-1421563426

## Suggested Implementation

https://github.com/nrwl/nx/blob/master/packages/js/src/utils/typescript/run-type-check.ts#L154
.filter((d) => !d.file.fileName.includes("node_modules"))

**Comment by FrozenPandaz** [comment]
Sorry, I'm not sure what the issue is here. Please open a new issue with more information.
