### ISSUE TITLE
{   "projects": [...],   "projectGraph": {...},   "hashes": {     "my-app": {        "current": "4b669d95627bf6724502d7b4ff6f41d3654c50ba9e3b1cf31e72c138370423f8",        "previous": "0bdb20fbd1788957302f4cf356ff0449ee3c2d10960814f6c34fd399fa64f5d3"     }   } }

### ISSUE THREAD

**Issue by Moxita33** [nrwl/nx#18991]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

**Comment by AgentEnder** [comment]
This looks like an incomplete issue. If you are experiencing a bug, can you open a new issue with the bug template and fill in the requested information? Thanks.
