### ISSUE TITLE
Expose a way to generate e2e tests for a route

### ISSUE THREAD

**Issue by mrmeku** [nrwl/nx#190]
Imagine a scenario wherin there is a developer creating a new primary route.

First thing to do is invoke `ng generate component routerComponent --app=app-name`

Then imagine this developer wants to do some test driven development and start writing unit and e2e tests right off the bat. It'd be nice for this developer either to have already generated (via a flag to ng generate component) or be able to generate (via a new command) to generate a basic page object and e2e-spec files in a new subdirectory of the e2e testing directory.

**Comment by vsavkin** [comment]
I think having a separate command is probably a better option. E2E tests often cross component boundaries.
