### ISSUE TITLE
Cannot select Webpack when generating a react library

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#19001]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[Enter the URL or documentation section here.](https://nx.dev/packages/webpack/documents/overview#setting-up-a-new-nx-workspace-with-webpack)

### Additional context or description

Here it states that it is possible to generate a library with webpack config, however, that is not possible, and the rest of the documentation states it correctly.

> You can generate a [React](https://nx.dev/packages/react) application **or library** or a [Web](https://nx.dev/packages/web) application that uses Webpack in an existing Nx workspace.

**Comment by ndcunningham** [comment]
Hey, thanks for pointing this out we must have missed it.
