### ISSUE TITLE
Wrong extension of the webpack.config file generated

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#19005]
### Current Behavior

A new react application generates webpack.config.**js** and not webpack.config.**ts**.

Also, converting it to ts proves to be a nuisance.

### Expected Behavior

A new react application should be generated with webpack.config.**ts** instead of **js**.

### Steps to Reproduce

* nx g @nx/react:app new-app
* open it and find the webpack.config.js 

### Nx Report

```shell
Node   : 18.15.0
   OS     : linux-x64
   yarn   : 3.6.3
   
   nx                 : 16.5.3
   @nx/js             : 16.5.3
   @nx/jest           : 16.5.3
   @nx/linter         : 16.5.3
   @nx/workspace      : 16.5.3
   @nx/cypress        : 16.5.3
   @nx/eslint-plugin  : 16.5.3
   @nx/react          : 16.5.3
   @nx/vite           : 16.5.3
   @nx/webpack        : 16.5.3
   typescript         : 5.1.6
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Currently, this is working as expected. 
However, we may look into supporting this in the near future. 

I will leave this post open but it's not a bug more of an enhancement.
