### ISSUE TITLE
@nx/js - @babel/plugin-proposal-class-properties deprecated 

### ISSUE THREAD

**Issue by vadimka123** [nrwl/nx#19016]
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.

**Comment by jesusvallez** [comment]
WARN  deprecated @babel/plugin-proposal-unicode-property-regex@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-unicode-property-regex instead.

**Comment by FrozenPandaz** [comment]
@svgr/rollup 8.0.1
@svgr/webpack 8.0.1

Both seem to use this dependency. @ndcunningham can you investigate if updating will get rid of the deprecated dependency please?
