### ISSUE TITLE
Component testing not working at all

### ISSUE THREAD

**Issue by wiegell** [nrwl/nx#19013]
### Current Behavior

There is a cypress bug since 12.17.4 where component tests cannot run if the component-index.html file is set as an absolute path (which is what the nx component testing generator is doing):
https://github.com/cypress-io/cypress/issues/27750
So when creating a completely new nx repo, adding an angular component and then component testing via the official generators, the testing will fail.

### Expected Behavior

Should not fail, can be worked around by setting relative path via the component-testing generator - see this:
https://github.com/wiegell/cypress-bug/blob/main/libs/my-standalone-lib/cypress.config.ts
At least the docs should be updated with the relative path workaround until the cypress issue is fixed

### GitHub Repo

https://github.com/wiegell/cypress-bug

### Steps to Reproduce

1. `yarn`
2. `yarn nx run my-standalone-lib:component-test`

See the fail.

### Nx Report

```shell
Node   : 18.15.0
   OS     : darwin-arm64
   yarn   : 1.22.19

   nx                 : 16.7.4
   @nx/js             : 16.7.4
   @nx/jest           : 16.7.4
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.7.4
   @nx/angular        : 16.7.4
   @nx/cypress        : 16.7.4
   @nx/devkit         : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nrwl/tao          : 16.7.4
   @nx/web            : 16.7.4
   @nx/webpack        : 16.7.4
   typescript         : 5.1.6
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
This issue was fixed by #18839 and released in Nx v16.8.0. Please also note the upstream issue was also addressed by the Cypress team in https://github.com/cypress-io/cypress/pull/28324.
