### ISSUE TITLE
Cannot install 16.8.0 on Node.js 14

### ISSUE THREAD

**Issue by danez** [nrwl/nx#19022]
### Current Behavior

![1000007726](https://github.com/nrwl/nx/assets/231804/1a43744e-f83b-44aa-a75e-aa9c8e8c9390)

https://github.com/reactjs/react-docgen/actions/runs/6093955626/job/16534536915#step:5:1

### Expected Behavior

Install works

### Steps to Reproduce

1. Install nx on Node.js 14

### Nx Report

```shell
Irrelevant
```

### Package Manager Version

pnpm 7

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by lheringer-bt** [comment]
Workaround for now is to use previous version:
`yarn global add nx@15.9.6`
Works for me.

**Comment by FrozenPandaz** [comment]
Yes, please use `15.9.6` if you must use Node 14. I will update our nodejs compatibility table on nx.dev.

**Comment by danez** [comment]
So far v16 worked fine on node 14 until this update. Nx should drop node versions on major versions and not just on a minor version.

**Comment by mandarini** [comment]
Should this issue be closed @FrozenPandaz ?

**Comment by AgentEnder** [comment]
Yeah, this should be closed at this point. The compatibility table is updated, and we will try to not change compat mid version.
