### ISSUE TITLE
Add a guide showing how to set up an Angular project with Karma and Protractor

### ISSUE THREAD

**Issue by vsavkin** [nrwl/nx#1903]
We default to Jest and Cypress when create an Angular project. And we don't give an option to use Karma when folk using presets.

To create a project with karma, you need to do something like this:

```
npx create-nx-workspace myorg --preset=empty --cli=angular
ng add @nrwl/angular
ng g app myapp --unit-test-runner=karma
```

We should document it

**Comment by juristr** [comment]
@vsavkin If you want I can take this one. Could take a look at this next week, at max in 2 weeks. So I get to know a bit better the docs part of this repo as well. let me know

**Comment by maartentibau** [comment]
I actually have a small "guide" for it.

```
npx create-nx-workspace@latest {workspace-name}

npx ng config cli.packageManager npm

npx ng add @nrwl/angular@latest --registry=npm --interactive=true

npx ng g @nrwl/angular:application {application-name} --routing=true --style=scss --e2e-test-runner=protractor

npx ng config schematics.@schematics/angular:component.styleext scss
```

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by Blackbaud-SteveBrush** [comment]
The above comments weren't working for me, but this got me to my desired state (Angular CLI, Karma, NPM):
```
npx create-nx-workspace --cli=angular --defaultBase=main --name=my-monorepo --nxCloud --packageManager=npm --preset=empty

cd my-monorepo

npx ng add @nrwl/angular --skip-confirmation --style=scss --unitTestRunner=karma

npx nx generate @nrwl/angular:application --name=my-app --prefix=app --routing --strict --style=scss --unitTestRunner=karma
```

**Comment by oletrn** [comment]
Finally, I've managed to generate a project with Karma runner this way:

1. `npx create-nx-workspace --preset=empty --name=my-app`
2. `cd my-app`
3. `npm install @nrwl/angular`
4. `nx generate @nrwl/angular:app foobar --style=scss --unitTestRunner=karma`
