### ISSUE TITLE
Failing to use Selectors Composition

### ISSUE THREAD

**Issue by joelmuskwe** [nrwl/nx#1906]
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

I am expecting to be able to compose selectors form multiple data-access libs from two or more other data libs

## Current Behavior

I am currently getting an error in the createSelectors about No overload matches this call.

## Failure Information (for bugs)

<img width="1677" alt="Screenshot 2019-10-01 at 11 33 38" src="https://user-images.githubusercontent.com/5989937/65950948-5dd7b100-e43f-11e9-9d3c-6331eb559e92.png">

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. I created an empty nrwl workspace
2. Created two feature libs and two data-access libs (airplanes-feature-shell, airplanes-data-access, categories-feature-shell, categories-data-access)
3. I then imported the airplanes-data-access module into the categories-data-access lib.
4. I then imported getAllAirplanes selector from airplanes-data-access lib.
5. created new selector with getAllCategories and getAllAirplanes.

online repo: [Stackblitz](https://stackblitz.com/github/joelmuskwe/demo-airlines?file=libs%2Fcategories%2Fdata-access%2Fsrc%2Flib%2F%2Bstate%2Fcategories.selectors.ts)

### Context

Please provide any relevant information about your setup:

- version of Nx used 8.5.2

### Failure Logs

<img width="1629" alt="Screenshot 2019-10-01 at 11 40 10" src="https://user-images.githubusercontent.com/5989937/65951389-43ea9e00-e440-11e9-87b8-2e9d268ccfa1.png">

**Comment by mhamel06** [comment]
It's pretty verbose, but would something like this work for now?
```
// Tell create selector to expect a partial state with both Airplane and Category features
export const getAllCategoriesWithAirplanes = createSelector<
  CategoriesPartialState & AirplanesPartialState,
  CategoriesEntity[],
  AirplanesEntity[],
  any[]
  >(
  getAllCategories,
  getAllAirplanes,
  (categories, airplanes) => {
    return [];
  }
);
```

**Comment by brandonroberts** [comment]
The `getCategoriesState` is restricted to the `CategoriesPartialState` by default, so you can do what @mhamel06 mentioned above or:

```ts
export const getCategoriesState = createFeatureSelector<
  CategoriesPartialState & AirplanesPartialState,
  State
>(CATEGORIES_FEATURE_KEY);
```

Then your types will flow correctly.

**Comment by joelmuskwe** [comment]
Thank you works like a charm.
