### ISSUE TITLE
`@nx/js:tsc` brutally overwrites the `package.json.main` field

### ISSUE THREAD

**Issue by k-paxian** [nrwl/nx#19062]
### Current Behavior

I have the following `package.json`
```json
{   ...
  "main": "./dist/src/index.js",
  "types": "./dist/src/index.d.ts",
  "generators": "./dist/generators.json",
  "executors": "./dist/executors.json",
...
}
```

after running executor "executor": "@nx/js:tsc" in the nx target

`package.json` in the output folder has the following content:

```json
{   ...
  "main": "./src/index.js", <- Why this field is being overwritten during the build?  That is a new behaviour since `16.7.0`
  "types": "./dist/src/index.d.ts",
  "generators": "./dist/generators.json",
  "executors": "./dist/executors.json",
...
}
```

I'm guessing this [line](https://github.com/nrwl/nx/blob/f71f2ac1f029a85f17139e7416296034a1cf286b/packages/js/src/utils/package-json/update-package-json.ts#L270) is doing the damage 👎 

### Expected Behavior

I'd like to retain my own settings in the `package.json` exactly as it was originally, 
I know better what I need to be there in the "main" field 😄 
This behaviour basically ruining my package output. I'd like at least an option to skip this default behaviour.

### Steps to Reproduce

1. With "@nx/js": "16.6.0" it works as expected
2. With "@nx/js": "16.7.0+" it works NOT as expected
3. After this commit https://github.com/nrwl/nx/commit/d63d3573c4cf9b643554e24ae579761396a4d556 unwanted side effect introduced

### Nx Report

```shell
Node   : 16.15.0
   OS     : win32-x64
   yarn   : 1.22.19

   nx                 : 16.7.4
   @nx/js             : 16.8.0
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.8.0
   @nx/devkit         : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nrwl/tao          : 16.7.4
   @nx/vite           : 16.7.4
   typescript         : 5.1.6
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by k-paxian** [comment]
Any progress on that? I can't upgrade nx to the latest for two months already 😔

**Comment by k-paxian** [comment]
Endup with this patch, seems this issue will be never resolved 😞 

```ts
import { tscExecutor } from '@nx/js/src/executors/tsc/tsc.impl'
import { type ExecutorContext, workspaceRoot, joinPathFragments, writeJsonFile, readJsonFile } from '@nx/devkit'
import { type BuildTscExecutorSchema } from './schema'

interface ExecutorResult {
  success: boolean
}

/**
 * This workarond for https://github.com/nrwl/nx/issues/19062 issue
 * can be obviously removed when it'll be fixed
 * This executor can be replaced back by native "@nx/js:tsc" executor
 */
export default async function (options: BuildTscExecutorSchema,
  context: ExecutorContext): Promise<ExecutorResult> {
  let executionResult: ExecutorResult = { success: false }
  for await (const result of tscExecutor(options, context)) {
    executionResult = result
    if (executionResult.success) {
      const distPackageJson = joinPathFragments(workspaceRoot, options.outputPath, 'package.json')
      const originalPackageJson = joinPathFragments(workspaceRoot, options.packageJson)
      const originalPkgJson = readJsonFile(originalPackageJson)
      const distPkgJson = readJsonFile(distPackageJson)
      writeJsonFile(distPackageJson, { ...distPkgJson, main: originalPkgJson.main })
    }
  }
  return executionResult
}
```

**Comment by ntrp** [comment]
Please fix this, we have the same exact problem..

**Comment by k-paxian** [comment]
Potential fix is [here](https://github.com/nrwl/nx/pull/21415)
Thanks @xiejay97
