### ISSUE TITLE
Non publishable libraries shouldn't have to manage dependencies in local package.json

### ISSUE THREAD

**Issue by jamesousby** [nrwl/nx#19071]
### Current Behavior

As of nx v16.5 the @nx/js:lib library generator now generates a library that includes a local package.json that has a 'dependencies' section in it and includes an new eslint rule @nx/depenendency-check that fails the lint task if your library is using any dependencies that aren't listed in the local package.json.

There is an explanation from @meeroslav on [this issue](https://github.com/nrwl/nx/issues/18851#issuecomment-1696953346) as to the motivation behind these changes. 

After upgrading my existing repo past v16.5 to v16.7.4, my shared library packages (these are not publishable, and are just used locally to facilitate code sharing across microservice apps) now fail the lint task.

It seems like the recommended way forward is to start using the @nx/dependency-check rule with the --fix flag to update a package local package.json with a list of dependencies that the library uses. I really liked the fact that i could centrally manage my dependencies and versions in the workspace root package.json. I'm not looking forward to having dependencies listed in multiple package.json files even if there is a linting rule to help reconcile/fix mismatches with the root package.json. I appreciate that intent here is to fix how package.json files are created for libraries that are publishable. But can we maintain the pre v16.5 behaviour where dependencies were just managed in the root workspace package.json if the library is generated with the publishable=false flag?

### Expected Behavior

Library generation for non publishable libraries continues to work as it did pre v16.5 where there is no 'dependencies' block in the library package.json file. Dependencies are only managed/listed in the root workspace package.json.

### Steps to Reproduce

1. Create a empty workspace (framework = none)
2. `nx g @nx/js:init`
3. `ns g @nx/js:lib mylib`
4. Install a 3rd party dep to use in your new lib i.e `npm install ulid`
5. Update the mylib.ts file to use the new dep added in step 4

```
import { ulid } from "ulid"

export function mylib(): string {
  const id = ulid()
  return id
}
```

6. Run the lint task `nx lint mylib`. Lint task will fail on the @nx/dependency-check rule saying that the ulid package is not listed in the local package.json.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.13.0
   OS     : linux-x64
   npm    : 8.19.3

   nx                 : 16.7.4
   @nx/js             : 16.7.4
   @nx/jest           : 16.7.4
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.7.4
   @nx/cypress        : 16.7.4
   @nx/devkit         : 16.7.4
   @nx/esbuild        : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nx/next           : 16.7.4
   @nx/plugin         : 16.7.4
   @nx/react          : 16.7.4
   @nrwl/tao          : 16.7.4
   @nx/vite           : 16.7.4
   @nx/web            : 16.7.4
   nx-cloud           : 16.3.0
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @ago-dev/nx-aws-cdk-v2 : 1.6.1
   ---------------------------------------
   Local workspace plugins:
         @droidmap/workspace-plugin
```

### Failure Logs

```shell
Linting "mylib"...

/home/jousby/code/scratch/nx-pkg-json-issue/mylib/package.json
  1:1  error  Dependency sections are missing from the "package.json" but following dependencies were detected:
- "ulid",
- "tslib"  @nx/dependency-checks

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

Lint errors found in the listed files.
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by berenddeboer** [comment]
Fully agree, when the package is just internal, this is just annoying.

**Comment by meeroslav** [comment]
We still believe having `package.json` even for internal projects makes sense as it will give you a hint when you (accidentally) import some new dependency that was not previously explicitly listed. Your version ranges can be set wide to avoid constant updates when the base `package.json` changes.

You can however simply disable/remove this rule from the eslint config of the libraries that are not meant to be published if this turns out to be too annoying to you.

**Comment by jamesousby** [comment]
I don't understand this comment:

> We still believe having package.json even for internal projects makes sense as it will give you a hint when you (accidentally) import some new dependency that was not previously explicitly listed.

Prior to 16.5 if I tried using a dependency in my library that hadn't been explicitly added to the root package.json my library would not compile. I'm not sure what additional protection around dependency management the local package.json is adding? 

Seperately i'm also not clear why the generated package.json and the new eslint rule insist on having 'tslib' as a runtime dependency in the local package.json. My library's don't depend on 'tslib' at runtime. 

Happy to concede that I'm not understanding something here, but for what its worth as a data point I'll be using my own library generator going forward to mimic the prior behavior. I'm not keen to take on the burden of keeping multiple package.json files correct without understanding what the upside is. The single package.json for my monorepo was one of the main reasons for choosing Nx.

**Comment by jamesousby** [comment]
Also just mentioning this because I want Nx to continue to be successful (its a great product). If i had come to Nx for the first time at 16.5+ and spun up a sample monorepo only to find i had to do 'npm installs' in my libraries package.json and then also do 'npm installs' in the root package.json i probably wouldn't have proceeded and got to the point where i worked out how to turn this off. 

I think Nx is under estimating the impact this will have on new user experience.

**Comment by Gkleinereva** [comment]
@meeroslav has NX considered a generator option on libraries to generate `.eslintrc.json` without the `@nx/dependency-checks` rule automatically inserted?  

I can see that it makes sense to include it in the root `.eslintrc.json` by default.  But it is pretty annoying that it is also automatically added to each individual library `.eslintrc.json` (at least by the `@nx/angular:library` generator) and then has to be removed manually to avoid these lint errors.

**Comment by ryan-mcginty-alation** [comment]
@meeroslav in the documentation it says that devDependencies will be filtered out, however I am getting errors for many devDependencies in the eslint runs. tslib is just one example
