### ISSUE TITLE
Next.js composePlugins overriding Sass includePaths configuration

### ISSUE THREAD

**Issue by lourd** [nrwl/nx#19083]
### Current Behavior

Re-opening #16142

I just tried changing my next.config.js to use the `composePlugins` helper, and it appears that my `sassOptions` are either getting cleared or overridden by the `withNx` plugin.

Reading through the source of the withNx plugin in @nrwl/next, it appears that it's kind of supposed to configure the Sass loader to automatically support Sass imports from libs in your Nx repo https://github.com/nrwl/nx/blob/master/packages/next/plugins/with-nx.ts#L267-L270

It doesn't have any effect though, and appears to be somehow overriding the `sassOptions` set in my next.config. The way Next.js accepts this configuration is now with the [sassOptions.includePaths property](https://nextjs.org/docs/pages/building-your-application/styling/sass#customizing-sass-options) on the config object.

This is causing my build to fail, with errors like this:

```
SassError: Can't find stylesheet to import.
  ╷
1 │ @use "theme/src/screens";
  │ ^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  ../../libs/web/core/src/css/components/modal.module.scss 1:1  root stylesheet
```

Where `theme/src/screens` is located in `libs/theme/src/screen.scss`.

### Expected Behavior

The withNx plugin should use the form supported by Next.js instead of trying to modify the loaders. So each application doesn't need to specify this in its next.config.js file

```
module.exports = withNx({
  sassOptions: {
    includePaths: [path.join(repoRoot, "libs")],
  }
})
```

### Steps to Reproduce

1. Make a new next.js app
2. Make a library with a sass stylesheet you want to import from the Next.js app
3. Import the shared stylesheet from a component's sass module, e.g. `@use mysharedlib/src/foo`, and in some block use a variable or mixin from the shared stylesheet.
4. Update the next.config.js `sassOptions.includePaths` property to be an array with a single value that's equal to `path.join(repoRoot, "libs")`
5. Run the build and see that there's an error with the `@use` line of the shared stylesheet.

### Nx Report

```shell
Node   : 18.17.1
   OS     : darwin-arm64
   yarn   : 1.22.19

   nx                 : 16.5.5
   @nx/js             : 16.5.5
   @nx/jest           : 16.5.5
   @nx/linter         : 16.5.5
   @nx/workspace      : 16.5.5
   @nx/detox          : 16.5.5
   @nx/devkit         : 16.5.5
   @nx/eslint-plugin  : 16.5.5
   @nx/next           : 16.5.5
   @nx/node           : 16.5.5
   @nx/react          : 16.5.5
   @nx/react-native   : 16.5.5
   @nrwl/tao          : 16.5.5
   @nx/web            : 16.5.5
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @ns3/nx-jest-playwright : 4.2.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Hey, this should be working did you try this repo https://github.com/ndcunningham/issue-16142.

The problem is that Next.js does not compile files that are outside of the source folder .i.e workspace libs.
Hopefully, the repo provided helps as it does exactly what you are describing for your reproduction steps.
