### ISSUE TITLE
Platform not support

### ISSUE THREAD

**Issue by DOnlyone** [nrwl/nx#19080]
### Current Behavior

I use nx create worksapce  like this
`npx create-nx-workspace `
and then report a error 
>  NX   Failed to create a workspace.
 Exit code: 1
   Log file: /var/folders/6d/870l5mqn66x7w1mpt5jhpxj00000gn/T/tmp-66608-x3zwBcxbl7F7/error.log

### Expected Behavior

npx create-nx-workspace  can create a new worksapce

### Steps to Reproduce

npx create-nx-workspace 

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Where would you like to create your workspace? · mindx
✔ Which stack do you want to use? · none
✔ Package-based monorepo, integrated monorepo, or standalone project? · package-based
✔ Enable distributed caching to make your CI faster · Yes

 >  NX   Creating your v16.8.1 workspace.

### Nx Report

```shell
I need creat new workspace .so this command can't execute
```

### Failure Logs

```shell
>  NX   Missing Platform Dependency

   The Nx CLI could not find or load the native binary for your supported platform (darwin-x64).
   This likely means that optional dependencies were not installed correctly, or your system is missing some system dependencies.
   For more information please see https://nx.dev/recipes/troubleshooting/troubleshoot-nx-install-issues
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

macos 10.14.5 
v16.20.0
nx v16.8.1

**Comment by FrozenPandaz** [comment]
Sorry, we do not support MacOS 10 at the moment.

[Only MacOS 11+](https://nx.dev/recipes/troubleshooting/troubleshoot-nx-install-issues)

MacOS 10 is over 20 years old and not supported by Apple anymore either.

Sorry for the inconvenience.
