### ISSUE TITLE
Unable to create new library in same folder

### ISSUE THREAD

**Issue by rajatgupta-dev** [nrwl/nx#19098]
### Current Behavior

I'm able to create library under a new folder but unable to create new library in same folder.

![image](https://github.com/nrwl/nx/assets/87616531/b3ea18da-56e3-401e-8b0b-93f1d2cb82a4)

### Expected Behavior

I'm should be able to create new library under the existing library's folder

### Steps to Reproduce

1. npx nx g @nx/angular:lib products --directory=libraries --standalone --simpleName
2. npx nx g @nx/angular:lib orders --directory=libraries --standalone --simpleName

### Nx Report

```shell
NX   Cannot create a new project orders at modules. It already exists.
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Jordan-Hall** [comment]
Looking at the screenshot you have done order twice. The first order has generated.

**Comment by rajatgupta-dev** [comment]
> Looking at the screenshot you have done order twice. The first order has generated.

I apologise for uploading the wrong image. I updated the screenshot. Could you please check it now.

**Comment by Lyca0n** [comment]
@rajatgupta-dev  

I think you're misusing the directory argument
if your intention is to create 
- libraries /
  - products
  - orders


the instructions would be 

1. npx nx g @nx/angular:lib products --directory=libraries/products --standalone --simpleName
2. npx nx g @nx/angular:lib orders --directory=libraries/orders --standalone --simpleName

the current instruction it's just causing your products library to be created in a folder "libraries", therefore the subsequent command will fail as there is already a library created in it.


[integrated-repo-tutorial](https://nx.dev/getting-started/tutorials/integrated-repo-tutorial#create-a-package)

**Comment by AgentEnder** [comment]
@Lyca0n is spot-on, I'm going to go ahead and close this out.

**Comment by rajatgupta-dev** [comment]
@Lyca0n Thanks you for helping me out from here.
@AgentEnder  Thanks for closing it.

Great!!!
