### ISSUE TITLE
Executors for Bun

### ISSUE THREAD

**Issue by marcus-sa** [nrwl/nx#19093]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Implement executors for the following Bun CLI commands
- build
- run
- test

My suggestion for the package name would be `@nx/bun`

## Motivation
Bun recently released version 1.0.0 and it has been gaining in popularity.

**Comment by Jordan-Hall** [comment]
They still alot to do on bun yet before it could be considered main repo. Just like the deno work in nx-lab.

If you want to help and start using bun now checkout https://github.com/Jordan-Hall/nx-bun/blob/master/packages/nx-bun/src/generators/create/schema.json

**Comment by AgentEnder** [comment]
Yeah, lets keep bun discussion in the discussions, its been a pretty active one and I don't see benefit to moving it here. Our stance has currently not changed, but its something we are watching.
