### ISSUE TITLE
@nx/esbuild:esbuild - allow `define` property to accept custom values

### ISSUE THREAD

**Issue by vixncu** [nrwl/nx#19106]
## Description
Right now `@nx/esbuild:esbuild` executor, when esbuild options are being parsed, it completely overrides the `define` option (https://esbuild.github.io/api/#define) and there is no way for us to pass our own custom `define` values.

Here is the line that overrides the `define` property in `build-esbuild-options.ts`: https://github.com/nrwl/nx/blob/660bfb3dc5c6a66c0170c9edfcf810255d2846e5/packages/esbuild/src/executors/esbuild/lib/build-esbuild-options.ts#L52

The `getClientEnvironment()` method filters existing `process.env.*` variables and only allows variables that start with the prefix `NX_`. 

## Motivation
We found a workaround for now, as we defined all our environment variables to start with `NX_`, but it would be very nice not to be forced to apply the `NX_` prefix. Might also have other implications if other parts of `nx` rely on these variables, but I'm not sure of all the use cases.

## Suggested Implementation
A simple implementation would be to allow us (nx users) to specify our own `define` properties as well. It can be either through a dedicated property in the nx executor schema or through the already existing `esbuildOptions` property.

A code suggestion: 
``` 
if (options.platform === 'browser') {
    const userDefine = userDefinedBuildOptions?.define || {}
    esbuildOptions.define = { ...userDefine, ...getClientEnvironment() };
}

```

## Alternate Implementations
Or any other way in which we can provide our own `define` property values

**Comment by BrRenat** [comment]
```esbuildOptions.define = { ...userDefine, ...getClientEnvironment() };```
a good choice!

My external library uses the env variable and I can't replace it at compile time. Of course, some npm package doesn't know anything about your `NX_` prefix rule for envs.

**Comment by alljinx** [comment]
+1 very annoying.
I wanted tu use this to substitute another missing feature : fileReplacements (https://github.com/nrwl/nx/issues/19962)

**Comment by PhilipWee** [comment]
I've made a simple plugin to fix this behaviour, but its quite worrying that nx tends to willy nilly override user defined options in several cases, and seldom has the documentation for such behaviour

```
const additionalDefinePlugin = {
  name: 'additional-define-plugin',
  setup(build) {
    build.initialOptions.define.global = 'window';
    console.log(build.initialOptions);
  },
};
```

I find that the best way to use nx is often to just read the source code, because the documentation tends to be rather barebones because the api layer they are trying to support is incredibly large and the documentation is lacking for all but the most common use cases
