### ISSUE TITLE
Make Nx migrators and generators compatible for an angular cli application

### ISSUE THREAD

**Issue by sonikasharma1403** [nrwl/nx#19118]
We have created a library using NX and have migrations and generators in place.. which work perfectly fine on a brand-new NX application. the issue is that they don't work as expected on applications created using angular CLI.

would it be possible to have Out of the box support for this?

**Comment by AgentEnder** [comment]
This already exists 🎉, see: https://nx.dev/concepts/more-concepts/nx-devkit-angular-devkit#conversions
