### ISSUE TITLE
Failed to create a workspace in NX v16.8.1

### ISSUE THREAD

**Issue by xmd5a** [nrwl/nx#19123]
### Current Behavior

When I try to create a new nx workspace (integrated monorepo), I get an npm error

### Expected Behavior

Workspace should be created

### Steps to Reproduce

1. execute `npx create-nx-workspace@latest` command
2. provide details, which are:
3. stack: `react`
4. framework: `none`
5. integrated or standalone project: `integrated`
6. bundler: `vite`
7. test runner: `none`
8. default stylesheet format: `@emotion/styled`
9. enable distributed caching: `yes`

### Nx Report

```shell
Node   : 18.17.1
   OS     : linux-x64
   npm    : 9.6.7

   nx (global)    : 16.7.4
   nx             : 16.8.1
   @nx/js         : 16.8.1
   @nx/jest       : 16.8.1
   @nx/linter     : 16.8.1
   @nx/workspace  : 16.8.1
   @nx/devkit     : 16.8.1
   @nx/plugin     : 16.8.1
   @nx/react      : 16.8.1
   @nrwl/tao      : 16.8.1
   @nx/vite       : 16.8.1
   @nx/web        : 16.8.1
   nx-cloud       : 16.4.0
   typescript     : 5.1.6
```

### Package Manager Version

npm 9.6.7

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Hey, what's the error look like?

**Comment by xmd5a** [comment]
I'm attaching a screenshot from my console
![workspace-fail](https://github.com/nrwl/nx/assets/4546209/e018abd0-aca8-4050-81f4-7aa578254af2)

**Comment by xmd5a** [comment]
sorry for bothering you - now everything works as expected - I'm able to create new workspace
