### ISSUE TITLE
Creating new app DOES NOT use eslint ?

### ISSUE THREAD

**Issue by iangregsondev** [nrwl/nx#1912]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Creating a new app does not use eslint, it did before - I am almost certain of it :-)

I tried my different apps but even doing a standard angular app i.e. do the follow and choose angular

npx create-nx-workspace new-work-test3

This creates TSLINT.

Can somebody let us know the current state on this, as I say it was working before or at least creating the eslintrc file but now it creates an tslint config instead.

Thanks

**Comment by fvanwijk** [comment]
I can't imagine that eslint config was created before (never seen it myself). Angular is using TS by default, so tslint makes more sense. Just curious: why do you want eslint?

**Comment by bcabanes** [comment]
Hi @iangregsondev!
I don't think we supported _EsLint_ with Angular in previous release. If you are sure, please point us to the release version we shipped it, it would have been a mistake from our side.

The _EsLint_ feature should come from the Angular CLI, they are working on it for next Angular releases.

Closing for now.

**Comment by iangregsondev** [comment]
Yes, my mistake, it was on another project type.

**Comment by demisx** [comment]
Are there plans to switch to ESLint since TSLint is being deprecated?

**Comment by josecolella** [comment]
@demisx Is there a plan to change to eslint?

**Comment by demisx** [comment]
@demisx My understanding the team is waiting until Angular implements ESLint support.

Related:
* https://github.com/angular/angular-cli/issues/13732
