### ISSUE TITLE
VS Code shows types conflict between Jest and Cypress when using a library that depends on Cypress

### ISSUE THREAD

**Issue by zilia-gmethot** [nrwl/nx#19132]
### Current Behavior

Importing code from a package that depends on Cypress in a Cypress component test file makes VS Code's TypeScript Language Server show typing errors in Jest test files. In my case, the issue is specifically with the library [@badeball/cypress-cucumber-preprocessor](https://github.com/badeball/cypress-cucumber-preprocessor).

I'm assuming that a different configuration of the TypeScript configuration files could solve the issue but I wasn't able to.

### Expected Behavior

Importing code from a package that depends on Cypress in a Cypress component test file **should not** make VS Code's TypeScript Language Server show typing errors in Jest test files.

### GitHub Repo

https://github.com/zilia-gmethot/jest-cypress-conflict

### Steps to Reproduce

1. Open the repository with the latest version of VS Code
2. Open the file `apps/frontend-device/src/app/app.component.spec.ts` and notice the typing errors.
3. Open the file `apps/frontend-device/src/app/app.component.cy.ts` and comment out line 3, which contains `import '@badeball/cypress-cucumber-preprocessor';`
4. Open the file `apps/frontend-device/src/app/app.component.spec.ts` and notice that the typing errors are gone.

Here is the repository creation stack trace:
```
❯ npx create-nx-workspace@15.9.2

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Choose what to create                 · integrated
✔ What to create in the new workspace   · angular-monorepo
✔ Repository name                       · jest-cypress-conflict
✔ Application name                      · frontend-device
✔ Would you like to use Standalone Components in your application? · No
✔ Would you like to add routing? · Yes
✔ Default stylesheet format             · scss
✔ Enable distributed caching to make your CI faster · No
```

The component testing was configured using the Nx VS Code extension, which under the hood uses the command `nx generate @nrwl/angular:cypress-component-configuration`.

### Nx Report

```shell
❯ npx nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.19.0
   OS   : linux x64
   npm  : 8.19.3
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
```

### Package Manager Version

8.19.3

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Please move the `tsconfig.editor.json` reference in `tsconfig.json` to be the first reference:

```diff
// apps/frontend-device/tsconfig.json
{
  ...
  "references": [
+    {
+      "path": "./tsconfig.editor.json"
+    },
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.spec.json"
    },
-    {
-      "path": "./tsconfig.editor.json"
-    },
    {
      "path": "./cypress/tsconfig.cy.json"
    }
  ],
  ...
}
```

I'll update our generators to make sure it's generated like that and I'll also make sure to exclude the non-runtime files from the `tsconfig.editor.json`.
