### ISSUE TITLE
Guideline for affected commands

### ISSUE THREAD

**Issue by hoang-innomizetech** [nrwl/nx#1914]
Do we have any document about how NX detect affected apps by using GIT history and current change? What are the best practices to avoid making a change that affects to all applications? Some changes we made shouldn't be affected all services but it is, but not sure why?

* Should we exclude package.json, nx.json, tslint.json files from affected commands?

**Comment by bcabanes** [comment]
Hi @hoang-innomizetech!

We have a guide on using the affected command (including a part on how to use it in CI). [You can find it here](https://nx.dev/angular/guides/monorepo-affected). We also have a tutorial about it: _"[Step 10: Test Affected Projects](https://nx.dev/angular/tutorial/10-test-affected-projects)"_. Finally you can find more information on the API documentation of the command [via this link](https://nx.dev/angular/api/workspace/npmscripts/affected).

_For all these links, I presumed you were developing with Angular, if not, make sure to select another framework, but the information are essentially the same._
