### ISSUE TITLE
Cannot create gard using nx

### ISSUE THREAD

**Issue by dales** [nrwl/nx#19142]
### Current Behavior

```
nx g @nx/angular:guard athenticated --project=shared/data-access-user
>  NX  Generating @nx/angular:guard
? Which type of guard would you like to create? ›
```

### Expected Behavior

Have a select list of available options as specified in schematic

https://github.com/angular/angular-cli/blob/main/packages/schematics/angular/guard/schema.json

### Steps to Reproduce

1. ❯ nx g @nx/angular:guard athenticated --project=shared/data-access-user                                                                                        

### Nx Report

```shell
NA
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
@FrozenPandaz marking this one as core as well as it may be something with how we handle prompts
