### ISSUE TITLE
Request: print list  of affected e2e

### ISSUE THREAD

**Issue by Kunepro** [nrwl/nx#1915]
As per documentation:
https://nx.dev/angular/guides/monorepo-affected
We can currently print out the list of affected apps or libs, but there's no way to print out the list of affected e2e.

My request comes from the desire to parallelised each e2e test in a different process.
I know that I can run test in parallel with nx with `--parallel --maxParallel=8`, it works and it is great. However if a test fails I get a huge stacktrace and I don't know which test did fail, or I have to scroll through an unreadable log.
In a CI pipeline instead I can easily parallelise and isolate each test using the list provided nx affected:apps|libs and run them individually in a different process, so I know immediately which app or lib test has failed. These commands however do not include E2E tests so I can't do the same for them.

BR

**Comment by EvtK** [comment]
Checking to report that I have been looking forward to this implementation as well.

**Comment by vsavkin** [comment]
`nx print-affected --target=e2e` will emit a json document with a list of projects with the e2e target defined. I believe that should be enough to cover your use case.

Thank you!

**Comment by EvtK** [comment]
@vsavkin yep, have succesfully aplied it following the instructions for the distibuted CI project.
