### ISSUE TITLE
[Feature] Allow library import for specific file types

### ISSUE THREAD

**Issue by twittwer** [nrwl/nx#1916]
Regarding the latest improvements on the linting rule for module boundaries (#1897), it would be nice to restrict the allowance of imports to specific file types.

### Use Case

LibOne
- `@myorg/scope/lib-one`
- `@myorg/scope/lib-one/testing`

LibTwo
- `@myorg/scope/lib-two`
- `@myorg/scope/lib-two/testing`

LintRule
```json
"allow": ["@myorg/**/testing"]
```

This will allow all files to import from `@myorg/**/testing`, but the content is intended only for test files.
So it would be nice to restrict the import to `.spec` files.

### Proposal

Extending the lint configuration
```json
"allow": [
	{ "path": "@myorg/**/testing", "file": ".spec" },
	"@some/other/path"
]
```

If the idea is appreciated, I would like to attempt the implementation.

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.
