### ISSUE TITLE
Allow local overwrites for target/configuration specific .env files

### ISSUE THREAD

**Issue by stefan-schweiger** [nrwl/nx#19161]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Currently you can only overwrite environment variables locally through the .env.local file which is the second lowest priority. It should be allowed to overwrite all .env files with a higher order `<prefix>.local` file.

## Motivation
Sometimes you need to overwrite some settings for a specific configuration only and you want that to take precedence. For example a .env.test.local file in which you overwrite a shared test user account with your personal one.

For example the [vite loading order of .env files](https://vitejs.dev/guide/env-and-mode.html) looks like this:

1. `.env.[mode].local`
2. `.env.[mode]`
3. `.env.local `
4. `.env`

But such a behavior is currently not achievable with nx.

## Suggested Implementation
Current implementation:

1. `apps/my-app/.env.[target-name].[target-configuration-name]`
2. `apps/my-app/.env.[target-name]`
3. `apps/my-app/.[target-name].[target-configuration-name].env`
4. `apps/my-app/.[target-name].env`
5. `apps/my-app/.env.local`
6. `apps/my-app/.local.env`
7. `apps/my-app/.env`
8. `.env.[target-name].[target-configuration-name]`
9. `.env.[target-name]`
10. `.[target-name].[target-configuration-name].env`
11. `.[target-name].env`
12. `.env.local`
13. `.local.env`
14. `.env`

Suggested implementation:

(I'm not 100% sure where to put the `.local` for files ending with `.env`

1. `apps/my-app/.env.[target-name].[target-configuration-name].local`
2. `apps/my-app/.env.[target-name].[target-configuration-name]`
3. `apps/my-app/.env.[target-name].local`
4. `apps/my-app/.env.[target-name]`
5. `apps/my-app/.[target-name].[target-configuration-name].local.env`
6. `apps/my-app/.[target-name].[target-configuration-name].env`
7. `apps/my-app/.[target-name].local.env`
8. `apps/my-app/.[target-name].env`
9. `apps/my-app/.env.local`
10. `apps/my-app/.local.env`
11. `apps/my-app/.env`
12. `.env.[target-name].[target-configuration-name].local`
13. `.env.[target-name].[target-configuration-name]`
14. `.env.[target-name].local`
15. `.env.[target-name]`
16. `.[target-name].[target-configuration-name].local.env`
17. `.[target-name].[target-configuration-name].env`
18. `.[target-name].local.env`
19. `.[target-name].env`
20. `.env.local`
21. `.local.env`
22. `.env`

## Alternate Implementations
1. `apps/my-app/.env.[target-name].[target-configuration-name].local`
2. `apps/my-app/.env.[target-name].[target-configuration-name]`
3. `apps/my-app/.env.[target-name].local`
4. `apps/my-app/.env.[target-name]`
5. `apps/my-app/.local.[target-name].[target-configuration-name].env`
6. `apps/my-app/.[target-name].[target-configuration-name].env`
7. `apps/my-app/.local.[target-name].env`
8. `apps/my-app/.[target-name].env`
9. `apps/my-app/.env.local`
10. `apps/my-app/.local.env`
11. `apps/my-app/.env`
12. `.env.[target-name].[target-configuration-name].local`
13. `.env.[target-name].[target-configuration-name]`
14. `.env.[target-name].local`
15. `.env.[target-name]`
16. `.local.[target-name].[target-configuration-name].env`
17. `.[target-name].[target-configuration-name].env`
18. `.local.[target-name].env`
19. `.[target-name].env`
20. `.env.local`
21. `.local.env`
22. `.env`

**Comment by stefan-schweiger** [comment]
Next.js for example also allows you to overwrite all environments with .local files
https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#default-environment-variables

**Comment by AgentEnder** [comment]
Fixed by #19163
