### ISSUE TITLE
Issue with ImportMeta when generating a build

### ISSUE THREAD

**Issue by MoeedthePessimist** [nrwl/nx#19179]
### Current Behavior

I am getting an error while generating a build of my react app.

Error: 
Property 'env' does not exist on type 'ImportMeta'

libs\constants\src\lib\environment.ts:11:55 - error TS2339: Property 'env' does not exist on type 'ImportMeta'.

I have attached screen shots for the
-> Console error
-> tsconfig of the node library
-> environment.ts file showing that the typescript compiler recognizes the import.meta.env but despite that throws an error. 

![2](https://github.com/nrwl/nx/assets/63580699/8e385558-b52d-4354-82c6-958d6f0a58de)
![1](https://github.com/nrwl/nx/assets/63580699/9b8c949c-5f4b-4360-9131-0b623dca570d)
![3](https://github.com/nrwl/nx/assets/63580699/fa98c242-4024-47c3-abdc-e8a774f2e1bd)

### Expected Behavior

Application should build successfully without any errors.

### GitHub Repo

https://github.com/apollo-e-dev/dispatch-one

### Steps to Reproduce

-> Create an nx react project.
-> Create a node library for shared constants and export environment variables directly from there using import.meta.env.VITE_VAR.
-> Change the module type in tsconfig to ES2022 and also add vite/client to the types property of tsconfig of the library.
-> Run nx build app-name.

### Nx Report

```shell
Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.17.0
   OS     : win32-x64
   yarn   : 1.22.19
   
   nx (global)        : 16.5.5
   nx                 : 16.4.2
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.4.2
   @nx/workspace      : 16.4.2
   @nx/cypress        : 16.4.2
   @nx/detox          : 16.6.0
   @nx/devkit         : 16.4.2
   @nx/esbuild        : 16.4.2
   @nx/eslint-plugin  : 16.4.2
   @nx/express        : 16.4.2
   @nx/next           : 16.4.2
   @nx/node           : 16.4.2
   @nx/react          : 16.4.2
   @nx/react-native   : 16.6.0
   @nrwl/tao          : 16.4.2
   @nx/vite           : 16.4.2
   @nx/web            : 16.4.2
   @nx/webpack        : 16.4.2
   nx-cloud           : 16.0.5
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @nx-extend/strapi : 6.1.2
   ---------------------------------------
   Local workspace plugins:
         @apollo-e/financial-dashboard
         @apollo-e/dispatch-dashboard
         @apollo-e/email-integration
         @apollo-e/smart-load-board
         @apollo-e/carrier-network
         @apollo-e/chat-center
         @apollo-e/shared-auth
         @apollo-e/smart-maps
         @apollo-e/shared-ui
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/js@16.6.0
     - @nrwl/js@16.6.0
     - @nx/jest@16.6.0
     - @nrwl/jest@16.6.0
     - @nx/detox@16.6.0
     - @nrwl/detox@16.6.0
     - @nx/react-native@16.6.0
     - @nrwl/react-native@16.6.0

   To fix this, run `nx migrate nx@16.6.0`
```

### Failure Logs

```shell
error TS2339: Property 'env' does not exist on type 'ImportMeta'.

> 1 | export const Backend_url: string = import.meta.env.VITE_BACKEND_URL;
    |                                                ^
  2 | export const frontend_url: string = import.meta.env.VITE_FRONTEND_URL;
  3 | export const Google_map_api_key: string = import.meta.env.VITE_GOOGLE_MAPS_API_KEY;
  4 | export const Carrier_network: boolean = import.meta.env.VITE_CARRIER_NETWORK === 'true';
```

### Package Manager Version

yarn 1.22.19

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Application runs fine in dev mode.

**Comment by sancelot** [comment]
Have you tried "npm install" ?

**Comment by MoeedthePessimist** [comment]
> Have you tried "npm install" ?

Yes I have tried everything. The code works totally fine in development mode but when I try to generate a build, I end up with these errors.
