### ISSUE TITLE
libs folder missing from monorepo generation in Nx 16.8.1

### ISSUE THREAD

**Issue by jawahar273** [nrwl/nx#19184]
### Current Behavior

`libs` folder is missing from mono repo generated in react + next js.
![image](https://github.com/nrwl/nx/assets/7668497/1b897ade-bafa-47a0-84f7-0275f27feb14)

### Expected Behavior

`libs` folder should has generated 

### Steps to Reproduce

<img width="1226" alt="image" src="https://github.com/nrwl/nx/assets/7668497/25863822-ef59-450e-a997-ea8d54a23a44">

command: `npx create-nx-workspace@latest --name admin-panel -a --appName admin`

### Nx Report

```shell
❯ npx nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.17.1
   OS     : darwin-arm64
   npm    : 9.6.7

   nx                 : 16.8.1
   @nx/js             : 16.8.1
   @nx/jest           : 16.8.1
   @nx/linter         : 16.8.1
   @nx/workspace      : 16.8.1
   @nx/cypress        : 16.8.1
   @nx/devkit         : 16.8.1
   @nx/eslint-plugin  : 16.8.1
   @nx/next           : 16.8.1
   @nx/react          : 16.8.1
   @nrwl/tao          : 16.8.1
   @nx/web            : 16.8.1
   nx-cloud           : 16.4.0
   typescript         : 5.1.6
```

### Package Manager Version

npm 9.6.7

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jawahar273** [comment]
Downgrading the nx verison from `16.8.1` to `16.7.4`

<img width="664" alt="image" src="https://github.com/nrwl/nx/assets/7668497/05115ca4-a612-423f-a9f2-5a477ac203dd">

![image](https://github.com/nrwl/nx/assets/7668497/60c14d6d-8cdc-41ec-9b54-d5c2b5d3d739)


```
npx nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.17.1
   OS     : darwin-arm64
   npm    : 9.6.7

   nx                 : 16.7.4
   @nx/js             : 16.7.4
   @nx/jest           : 16.8.1
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.7.4
   @nx/cypress        : 16.8.1
   @nx/devkit         : 16.7.4
   @nx/eslint-plugin  : 16.8.1
   @nx/next           : 16.7.4
   @nx/react          : 16.7.4
   @nrwl/tao          : 16.7.4
   @nx/web            : 16.7.4
   nx-cloud           : 16.4.0
   typescript         : 5.1.6
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/jest@16.8.1
     - @nrwl/jest@16.8.1
     - @nx/cypress@16.8.1
     - @nrwl/cypress@16.8.1
     - @nx/eslint-plugin@16.8.1
     - @nrwl/eslint-plugin-nx@16.8.1

   To fix this, run `nx migrate nx@16.8.1`

```

**Comment by FrozenPandaz** [comment]
This is the new expected behavior for `16.8.0` and above.

See the documentation here:
https://nx.dev/reference/nx-json#workspace-layout

**Comment by jawahar273** [comment]
Can I know why this decision was made?

**Comment by jawahar273** [comment]
https://blog.nrwl.io/nx-16-8-release-e38e3bb503b5
