### ISSUE TITLE
@nx/enforce-module-boundaries ignores tsconfig.lib.json "exclude" setting

### ISSUE THREAD

**Issue by smallstepstoday** [nrwl/nx#19203]
### Current Behavior

The `@nx/enforce-module-boundaries` rule fires when a library is loaded dynamically within a test file (`*.spec.*`) ignoring the `"exclude"` field in `tsconfig.lib.json`.

```json
{
  "exclude": ["**/*.spec.ts", "**/*.test.ts", "jest.config.ts"],
}
```
We dynamically load modules that we are mocking via Jest:
```ts
// test.spec.ts
jest.mock('@project/api/db', () => {
  const { layoutPrefs } = require('../../__mocks__/live/layout-prefs');
  const { someFn } = require('@project/library');
  return {
    __esModule: true,
    ...
  };
});
```
Based on the excerpt above, the rule will fire wherever we import `@project/library`.

### Expected Behavior

The `@nx/enforce-module-boundaries` rule should ignore files when they are specified in the `"exclude"` field in `tsconfig.lib.json`.

### GitHub Repo

https://github.com/smallstepstoday/mod-bound-issue

### Steps to Reproduce

The only dynamic import is in a test file:
https://github.com/smallstepstoday/mod-bound-issue/blob/71d588c325cbe3b958d1bf9cfef384062337fd20/apps/app/src/api.spec.ts#L4

Check the following lines of code:
- https://github.com/smallstepstoday/mod-bound-issue/blob/71d588c325cbe3b958d1bf9cfef384062337fd20/apps/app/src/main.ts#L1
- https://github.com/smallstepstoday/mod-bound-issue/blob/71d588c325cbe3b958d1bf9cfef384062337fd20/apps/app/src/db.ts#L1

### Nx Report

```shell
Node   : 16.18.1
   OS     : darwin-arm64
   pnpm   : 8.6.1
   
   nx                 : 16.8.1
   @nx/js             : 16.8.1
   @nx/jest           : 16.8.1
   @nx/linter         : 16.8.1
   @nx/workspace      : 16.8.1
   @nx/devkit         : 16.8.1
   @nx/esbuild        : 16.8.1
   @nx/eslint-plugin  : 16.8.1
   @nx/node           : 16.8.1
   @nrwl/tao          : 16.8.1
   typescript         : 5.1.6
```

### Failure Logs

```shell
pnx lint app

> nx run app:lint


Linting "app"...
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.1.0

YOUR TYPESCRIPT VERSION: 5.1.6

Please only submit bug reports when using the officially supported version.

=============

/Users/david/Projects/mod-bound-issue/apps/app/src/api.ts
  2:1  error  Static imports of lazy-loaded libraries are forbidden.

Library "libs/utils" is lazy-loaded in these files:
- apps/app/src/api.spec.ts  @nx/enforce-module-boundaries

/Users/david/Projects/mod-bound-issue/apps/app/src/db.ts
  1:1  error  Static imports of lazy-loaded libraries are forbidden.

Library "libs/utils" is lazy-loaded in these files:
- apps/app/src/api.spec.ts  @nx/enforce-module-boundaries

/Users/david/Projects/mod-bound-issue/apps/app/src/main.ts
  1:1  error  Static imports of lazy-loaded libraries are forbidden.

Library "libs/utils" is lazy-loaded in these files:
- apps/app/src/api.spec.ts  @nx/enforce-module-boundaries

✖ 3 problems (3 errors, 0 warnings)

Lint errors found in the listed files.


 —————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target lint for project app (1s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by meeroslav** [comment]
This rule is meant to test both production files as well as test files.

It depends on the `tsconfig.json` not the `tsconfig.lib.json`, so your excludes in the lib one will not be respected.

Your tests should not have different imports than those in your production files. If they do, you can always use:
```
// eslint-ignore-next-lint @nx/enforce-module-boundaries
```
to ignore those instances or `// nx-ignore` to tell Nx not to parse that line when constructing the graph.

**Comment by smallstepstoday** [comment]
@meeroslav Thank you for your response. I have tried the following in the affected `spec` file, with no solution working:

ESLint Ignore next line
```typescript
// eslint-ignore-next-line @nx/enforce-module-boundaries
import {
  Cadence,
  CampaignType,
  JobGlobalUpdateInput,
  Timezone,
} from '@.../api/utils-api';
```

`nx-ignore`
```typescript
// nx-ignore
import {
  Cadence,
  CampaignType,
  JobGlobalUpdateInput,
  Timezone,
} from '@.../api/utils-api';
```

I don't know if the placement is correct, but I have not been able to dislodge this error, making it impossible to migrate to the latest Nx version...

**Comment by steven87vt** [comment]
I would like to ask a followup question to this @meeroslav if you wouldn't mind?

Basically, I find it a common setup in Jest of ViTest to async import inside a test for augmentation of the mocking behavior. It comes in handy as the static imports represent Mock functions and your able to manipulate mock state per test, etc. The issue here: as soon as you import it using async in a test function the import everywhere in the app says your have broken module boundaries.

Is this really true even when the library is only `async` imported in test files?

Example:

```ts
// packages/apps/app1/test/etc.test.ts

import { createModuleInitializer, createMutationObservers } from '@ezwebproductions/lib-vue'  // packages/lib/lib1: Static imports of lazy-loaded libraries are forbidden.

import { type Mock, it } from 'vitest'

vi.mock('@ezwebproductions/lib-vue', async () => {
  const original = await import('@ezwebproductions/lib-vue') <-- now triggers everywhere

  return {
    ...original,
    createModuleInitializer: vi.fn(() => vi.fn()),
    createMutationObservers: vi.fn()
  }
})

describe('my-test-suite', () => {
    // ... etc
})

**Comment by meeroslav** [comment]
@smallstepstoday sorry for super late reply.

When you have multiline imports you can use `/* eslint-disable @nx/enforce-module-boundaries */` before and `/* eslint-enable @nx/enforce-module-boundaries */` after the import block.

**Comment by meeroslav** [comment]
@steven87vt if your lib already imports that package directly, why would you import it asynchronously in the test?
What would be the purpose of that?
