### ISSUE TITLE
The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by PabloAznarez** [nrwl/nx#19222]
### Current Behavior

When i launch the command 

`nx g @nx/react:remote react-app --host=root --directory apps/react-app`

I get the title error

### Expected Behavior

Must create a react app

### GitHub Repo

https://github.com/pasblin/nx-microfront-angular-taiwind

### Steps to Reproduce

1. clone the repo and launch the command mentioned above

### Nx Report

```shell
Node   : 18.17.1
 OS     : darwin-x64
 npm   : 10.1.0
 
 nx                 : 16.8.1
 @nx/js             : 16.8.1
 @nx/jest           : 16.8.1
 @nx/linter         : 16.8.1
 @nx/workspace      : 16.8.1
 @nx/angular        : 16.8.1
 @nx/cypress        : 16.8.1
 @nx/devkit         : 16.8.1
 @nx/eslint-plugin  : 16.8.1
 @nx/playwright.    : 16.8.1
 @nx/webpack        : 16.8.1
 @nx/web            : 16.8.1
 typescript         : 5.1.3
```

### Package Manager Version

10.1.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
@PabloAznarez i think the issue is that the --host flag must point to a react app that is already existed in the monorepo. that is why the path returns undefined because there is no apps/host path in your repo.

**Comment by PabloAznarez** [comment]
Hi @xiongemi , in the project exist an angular host and I want this host to load an application in react, is this possible? 
I understand that one of the advantages of microfrontends is being able to use different apps with different frameworks.

**Comment by xiongemi** [comment]
sorry @PabloAznarez I misunderstood your question earlier. the command does not work out of the box. currently, the command line only supports the same framework host/remote.
Technically, it is possible to have an angular shell with a react remote. 
You can generate a react remote without the --host flag, but you have to wire up the host/remote config and routing manually.

**Comment by PabloAznarez** [comment]
Hi @xiongemi ,
I have also tried to do it that way but I have not been able to make it work, it would be good if you could give an example of how to do it in the documentation. 
Greetings and thank you

**Comment by xiongemi** [comment]
i pushed up a pr to your repo: https://github.com/pasblin/nx-microfront-angular-taiwind/pull/1. this is a solution i found:

here are the steps of add react remote in angular container:
1. add react remote
in my case, i just run `nx g @nx/react:remote react-app`

2. in the react app, add bootstrap to exposes in the module-federation.config.js
in my apps/react-app/module-federation.config.js, it will become:
```
module.exports = {
  name: 'react-app',
  exposes: {
    './Module': './src/remote-entry.ts',
    './web-components': './src/bootstrap.tsx'
  },
};
```
this basically expose the bootrsape as web-components.

in the react's bootstrap.tsx, notice it requires an element with root id:
```
import { StrictMode } from 'react';
import * as ReactDOM from 'react-dom/client';

import App from './app/app';

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);
root.render(
  <StrictMode>
    <App />
  </StrictMode>
);
```
you can change this query to whatever you want as long as it exists in the shell app.

3. add the shell's module-federation.manifest.json
in apps/root/src/assets/module-federation.manifest.json, add an entry for react-app (has to include remoteEntry.js at the end):
```
{
  "login": "http://localhost:4201",
  "dashboard": "http://localhost:4202",
  "app-one": "http://localhost:4203",
  "app-two": "http://localhost:4204",
  "react-app": "http://localhost:4205/remoteEntry.js"
}
```

4. create a wrapper componet for react app. i put the id="root" on the template:
```
import { AfterContentInit, Component } from '@angular/core';
import { loadRemoteModule } from '@nx/angular/mf';

@Component({
  template: '<div id="root"></div>',
})
export class WrapperComponent implements AfterContentInit {
  ngAfterContentInit(): void {
    loadRemoteModule('react-app', './web-components')
      .then(() => console.debug('react-app loaded'))
      .catch((err: any) => console.error(`error loading react-app:`, err)); 
  }
}
```

and I also add this route to app.routes.ts:
```
  {
    path: 'react-app',
    component: WrapperComponent
  },
```

now if you serve up the host and go to http://localhost:4200/react-app, it should load the react app.

**Comment by xiongemi** [comment]
i got it working by omit `react-app` in the command: `nx serve root --devRemotes=app-one,app-two,dashboard,login`.

**Comment by PabloAznarez** [comment]
ok , thanx @xiongemi :).

Anyway, I think the cli should be improved to do this automatically regardless of the framework the host uses.
