### ISSUE TITLE
Buildable library should point TS paths to dist rather than src

### ISSUE THREAD

**Issue by deser** [nrwl/nx#19238]
### Current Behavior

Whenever you generate buildable library it adds to tsconfig.base.json path to `src` rather than to built `dist`. 

### Expected Behavior

Path in tsconfig.base should be targeted to dist folder rather than to src. 

### Steps to Reproduce

1. nx g @nx/react:library aka
2. open tsconfig.base.json
3. Watch added path: `"aka": ["libs/aka/src/index.ts"],`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.16.0
   OS     : darwin-arm64
   npm    : 8.11.0
   
   nx (global)        : 16.5.0
   nx                 : 16.8.1
   @nx/js             : 16.8.1
   @nx/jest           : 16.8.1
   @nx/linter         : 16.8.1
   @nx/workspace      : 16.8.1
   @nx/devkit         : 16.8.1
   @nx/eslint-plugin  : 16.8.1
   @nx/node           : 16.8.1
   @nx/react          : 16.8.1
   @nx/rollup         : 16.8.1
   @nrwl/tao          : 16.8.1
   @nx/vite           : 16.8.1
   @nx/web            : 16.8.1
   @nx/webpack        : 16.8.1
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   nx-stylelint : 14.0.2
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Build executors that support `buildLibsFromSource` will generate a tsconfig that remaps things to point to `dist` to support this. For example, see the docs for angular incremental builds here:
- https://nx.dev/recipes/angular/setup-incremental-builds-angular
- https://nx.dev/concepts/more-concepts/incremental-builds
