### ISSUE TITLE
When  create nx project to react native and creat lib, the component inside doesnt call correctly

### ISSUE THREAD

**Issue by santilp95** [nrwl/nx#19248]
### Current Behavior

When  create nx project to react native and creat lib, the component inside doesnt call correctly i thin that is tsconfig call corrextlyu because said "None of these files exist:"

### Expected Behavior

The component is call correctly

### Steps to Reproduce

1. `npx create-nx-workspace dav-native --preset=react-native --appName=super-app`
2. `nx g @nx/react-native:lib your-lib-name`
3. `nx g @nx/react-native:component your-component-name --project=your-lib-name --export`
4. call custom component

### Nx Report

```shell
None of these files exist:
  * ../../davivienda-biometric/src/index.ts(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * ../../davivienda-biometric/src/index.ts/index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
```

### Package Manager Version

npm 9.6.7

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
i suspect it might be fixed from https://github.com/nrwl/nx/pull/19432. could you try with @nx/react-native 16.10? closing this issue for now.
