### ISSUE TITLE
Why must the root folder name of the project generated by the nx code generator be in the form of kebab case, and can it be customized by the developer

### ISSUE THREAD

**Issue by projectcss** [nrwl/nx#19253]
### Current Behavior

npx nx g @nx/react:library layoutComponent --directory=libs/common-modules/layoutComponent  creates a new library named layout-component in the libs/common-modules/layout-component folder

### Expected Behavior

npx nx g @nx/react:library layoutComponent --directory=libs/common-modules/layoutComponent  creates a new library named layoutComponent in the libs/common-modules/layoutComponent folder

### Steps to Reproduce

1.
npx nx g @nx/react:library layoutComponent --directory=libs/common-modules/layoutComponent

### Nx Report

```shell
npx nx g @nx/react:library layoutComponent --directory=libs/common-modules/layoutComponent
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mpsanchis** [comment]
+1. I haven't checked the generator's code yet, but I'd expect an error if syntax is not allowed, or at least a warning.
