### ISSUE TITLE
Environment variable support for React Native apps

### ISSUE THREAD

**Issue by BuckyMaler** [nrwl/nx#19268]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Support for setting environment variables in React Native apps.

## Motivation

It would simplify and standardize setting environment variables in React Native apps.

## Suggested Implementation

A couple of ways it could work from a user's perspective:

1. The same as React apps https://nx.dev/recipes/tips-n-tricks/define-environment-variables#setting-environment-variables
2. Setting an `envFile` executor option (similar to `nx:run-commands`)

The implementation could lean on [`react-native-config`](https://github.com/luggit/react-native-config/tree/bb3d8133612f3d3df9f7cc019f5d4da8ec61d689#different-environments) for loading environment variables from `.env` files.

**Comment by xiongemi** [comment]
I removed the library react-native-config because some developers want to have the flexibility to choose their own library.

**Comment by xiongemi** [comment]
i will close for now.

**Comment by BuckyMaler** [comment]
@xiongemi Why was this closed? It seems like a reasonable feature request. Does Nx provide environment variable support for React Native that I'm not aware of?
