### ISSUE TITLE
cannot reslove node:process React-native metro-resolver.js 

### ISSUE THREAD

**Issue by RavikanthOB** [nrwl/nx#19269]
### Current Behavior

Im using Axios in React native project under nx repo .Im facing bellow issue 

Metro has encountered an error: Cannot resolve node:process: /Users/Learn/learn-app/node_modules/@nx/react-native/plugins/metro-resolver.js (30:15)

  28 |             return resolvedPath;
  29 |         }
> 30 |         throw new Error(`Cannot resolve ${chalk.bold(realModuleName)}`);
     |               ^
  31 |     };
  32 | }
  33 | exports.getResolveRequest = getResolveRequest;

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_drain
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
0x0

### Expected Behavior

Need a document or steps to use external lib like got ,axios etc 

### Steps to Reproduce

1.Create a Nx react-navtive porject 
2. Add install axios 
3. Create instanse of axios 
4. Call any method 

### Nx Report

```shell
error: Error: Cannot resolve url
    at  /Users/Learn/learn-app/node_modules/@nx/react-native/plugins/metro-resolver.js:30:15
    at Object.resolve ( /Users/Learn/learn-app/node_modules/metro-resolver/src/resolve.js:47:12)
    at ModuleResolver.resolveDependency (  /Users/Learn/learn-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:79:31)
    at DependencyGraph.resolveDependency ( /Users/Learn/learn-app/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
    at Object.resolve ( /Users/Learn/learn-app/node_modules/metro/src/lib/transformHelpers.js:169:21)
    at Graph._resolveDependencies ( /Users/Learn/learn-app/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
    at Graph._processModule ( /Users/Learn/learn-app/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
    at async Graph._addDependency ( /Users/Learn/learn-app/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
    at async Promise.all (index 1)
    at async Graph._processModule ( /Users/Learn/learn-app/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
 ERROR  [Error: InternalError Metro has encountered an error: Cannot resolve url:  /Users/Learn/learn-app/node_modules/@nx/react-native/plugins/metro-resolver.js (30:15)
  28 |             return resolvedPath;
  29 |         }
> 30 |         throw new Error(`Cannot resolve ${chalk.bold(realModuleName)}`);
     |               ^
  31 |     };
  32 | }
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
What's `nx report` say?

**Comment by airowe** [comment]
For what it's worth, I'm seeing the same issue when trying to import from an internal lib package in a monorepo setup that was working prior to this upgrade. @AgentEnder, here's the output of my `nx report`:

```
Node   : 18.16.1
   OS     : darwin-arm64
   npm    : 9.5.1

   nx                 : 16.8.1
   @nx/js             : 16.8.1
   @nx/jest           : 16.8.1
   @nx/linter         : 16.8.1
   @nx/workspace      : 16.8.1
   @nx/cypress        : 16.8.1
   @nx/detox          : 16.8.1
   @nx/devkit         : 16.8.1
   @nx/eslint-plugin  : 16.8.1
   @nx/react          : 16.8.1
   @nx/react-native   : 16.8.1
   @nrwl/tao          : 16.8.1
   @nx/web            : 16.8.1
   @nx/webpack        : 16.8.1
   typescript         : 5.2.2
```

**Comment by alexbalda** [comment]
Facing the same issue here. Blocking me from upgrading RN deps. Is this being looked into, please?

**Comment by xiongemi** [comment]
are you using axios or a related library? from the error, i think it complains about the url module, which is a node module. since react native is client app, maybe just change axios to fetch?

or it is related to this issue? https://github.com/nrwl/nx/issues/19120

**Comment by xiongemi** [comment]
closing out this issue for now.
