### ISSUE TITLE
Importing SVG as ReactComponent with vite

### ISSUE THREAD

**Issue by unrealsolver** [nrwl/nx#19282]
### Current Behavior

svg does not export `ReactComponent`, only `default` which is just a path. Attempting import ReactComponent would lead to `SyntaxError: ambiguous inderect export ReactComponent` error.

### Expected Behavior

According with documentation: https://nx.dev/recipes/react/adding-assets-react#adding-svgs
```
import { ReactComponent as Logo } from './logo.svg';
```
should work with no errors (with vite)

### Steps to Reproduce

1. `nx generate g @nx/react:app app` with vite and ts
2.  `import { ReactComponent as Logo } from './logo.svg';` (any svg would work)
3. run `serve` target and open the app

### Nx Report

```shell
Node   : 16.15.1
   OS     : linux-x64
   yarn   : 3.6.0

   nx                 : 16.8.1
   @nx/js             : 16.8.1
   @nx/linter         : 16.8.1
   @nx/workspace      : 16.8.1
   @nx/cypress        : 16.8.1
   @nx/eslint-plugin  : 16.8.1
   @nx/react          : 16.8.1
   @nx/storybook      : 16.8.1
   @nx/vite           : 16.8.1
   @nx/web            : 16.8.1
   typescript         : 5.1.6
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This is an output for
```js
import * as A from './image.svg'
console.log(A)
```
```
Object { default: "/src/app/image.svg", … }
​
default: "/src/app/image.svg"
​
Symbol(Symbol.toStringTag): "Module"
app.tsx:11:10
```

`vite-plugin-svgr` can import svg as react, but seem it's not configured by default.

**Comment by unrealsolver** [comment]
Additionally, this is being ignored by Storybook, however it should imports the main app config.

**Comment by dobrynin** [comment]
I'm also running into this.

**Comment by ivan-palatov** [comment]
Same issue here, any workarounds? This is major blocker for us migrating to monorepo setup

**Comment by ivan-palatov** [comment]
Found out whats causing the issue, at least for me (and a workaround for everyone).

I had vite-plugin-svgr@4.0.0 installed in the monorepo, which is probably used under the hood of the nx/vite plugin.

The solution for me was to add `svgr` to plugins in `vite.config.ts`:

```typescript
import svgr from "vite-plugin-svgr";

export default defineConfig({
  // ...
  plugins: [
    svgr(),
    // ... other plugins
  ]
  // ... rest of config
})
```

**AND**, also instead of
```typescript
import {ReactComponent as MySvg} from './my_svg.svg';
```
I use
```typescript
import MySvg from './my_svg.svg?react'; // this is new in vite-plugin-svgr v4.0.0
```

I didn't have time to test if removing vite-plugin-svgr from project (or from vite config) would fix the issue entirely. Or potentially just manualy installing it at version 3.x might also fix the issue.

**Comment by martino2197** [comment]
Same problem, go back to version 3.3.0. to be able to solve it

**Comment by PatrickMunsey** [comment]
> Found out whats causing the issue, at least for me (and a workaround for everyone).
> 
> I had `vite-plugin-svgr@4.0.0` installed in the monorepo, which is probably used under the hood in the `nx/vite` plugin.
> 
> The solution for me was to add `svgr` to plugins in `vite.config.ts`:
> 
> ```ts
> import svgr from "vite-plugin-svgr";
> 
> export default defineConfig({
>   // ...
>   plugins: [
>     svgr(),
>     // ... other plugins
>   ]
>   // ... rest of config
> })
> ```
> 
> **AND**, also instead of
> 
> ```ts
> import {ReactComponent as MySvg} from './my_svg.svg';
> ```
> 
> I use
> 
> ```ts
> import MySvg from './my_svg.svg?react'; // this is new in vite-plugin-svgr v4.0.0
> ```
> 
> I didn't have time to test if removing vite-plugin-svgr from project (or from vite config) would fix the issue entirely. Or potentially just manualy installing it at version 3.x might also fix the issue.

Have you or anyone else been able to find a way to import an svg into a vite react app from a sharred asset library in the monorepo using an alias. For example:

```ts
import {AiviaGroupLogo} from '@workspace/ui-assets'
```

Importing png and svg images and using them in img components already works. e.g.


```ts
// index.ts file in the library
export { default as AiviaGroupLogo } from './lib/logos/aivia-group-logo.png';
```


```ts
// in the react application
import { AiviaGroupLogo, AiviaGroupLogoNoText } from '@aiviagroup/ui-assets';

...

<img src={AiviaGroupLogo} />
```

**Comment by irontitan76** [comment]
@PatrickMunsey I ran into a very similar, if not exact, problem earlier.

**Problem:**

1. I'm developing components with storybook in a fairly new repo. I added an SVG to a file using the new SVGR import syntax with `?react`, and I got the error: `Failed to fetch dynamically imported module: `.
2. When trying to import the file directly without the `?react` transform, I get the error `Failed to execute 'createElement' on 'Document': The tag name provided`, which makes perfect sense.
3. I added `vite-plugin-svgr` at 4.0.0 (latest) and added the plugin explicitly to the storybook configuration, but that did not resolve the problem. 

**Solution:**

1. Downgrade `vite-plugin-svgr` to 3.3.0 (it was 4.0.0) instead of using the new import syntax that `svgr` introduced.
2. Add the plugin explicitly to the `plugin` property of `vite.config.ts` for each relevant project.
3. Add the plugin to the `viteFinal` property in storybook's configuration, if applicable. I'm using a [single Storybook instance](https://nx.dev/recipes/storybook/one-storybook-with-composition) for the entire repo.
4. Update import declarations to follow this convention below:
  a. `import Logo from '@scope/assets/logo.svg?react'` -> `import { ReactComponent as Logo } from '@scope/assets/logo.svg';`
  b. `import Logo from '@scope/assets/logo.svg?url'` -> `import logo from '@scope/assets/logo.svg';`.

**Comment by ivan-palatov** [comment]
@PatrickMunsey I have the same setup and everything works for me just fine using vite-plugin-svgr@4.0.0. Do you have nxViteTsPaths() plugin AFTER svgr? There might be some issues with plugins order. Heres my vite.config.ts
```typescript
export default defineConfig({
  cacheDir: "../../node_modules/.vite/core",
  plugins: [
    svgr(),
    dts({
      entryRoot: "src",
      tsConfigFilePath: path.join(__dirname, "tsconfig.lib.json"),
      skipDiagnostics: false,
    }),
    react(),
    cssInjectedByJs(),
    nxViteTsPaths(),
  ],
  worker: {
    plugins: [nxViteTsPaths()],
    format: "es",
  },
  build: {
    lib: {
      entry: "src/index.ts",
      formats: ["es"],
    },
  // ... rest of config
```

**Comment by PatrickMunsey** [comment]
I'm still having issues importing a raw svg file into the application as a react icon however I found I can easily export icons from my own asset library if they are formatted like below. It could just be an issue of the other svg I'm trying to use having unsupported elements such as mesh gradient which throws an error when trying to export using svgr. 

```
// icon:arrow-down | Ant Design Icons https://ant.design/components/icon/ | Ant Design
import * as React from "react";

function IconArrowDown(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      viewBox="0 0 1024 1024"
      fill="currentColor"
      height="1em"
      width="1em"
      {...props}
    >
      <path d="M862 465.3h-81c-4.6 0-9 2-12.1 5.5L550 723.1V160c0-4.4-3.6-8-8-8h-60c-4.4 0-8 3.6-8 8v563.1L255.1 470.8c-3-3.5-7.4-5.5-12.1-5.5h-81c-6.8 0-10.5 8.1-6 13.2L487.9 861a31.96 31.96 0 0048.3 0L868 478.5c4.5-5.2.8-13.2-6-13.2z" />
    </svg>
  );
}

export default IconArrowDown;

```


For now I'm able to export images, .svg and icons (if their formatted as above) from an asset library and bring them into my applicaiton. I think I'll have to make do with that for now and do some more research on how I can structure things to tighten it up later. I'm still assuming importing an .svg as an image and a react icon from the same file is achievable. Perhaps I will just have to have an svg export and an icon varient for each image I want to manipulate as a react compoent.

**Comment by matt-gold** [comment]
I was able to to use vite-plugin-svgr@4.1.0. Make sure to add `"vite-plugin-svgr/client"` to the tsconfig.app.json `types` array after installing. Then the import syntax is `import Logo from '../assets/logo.svg?react';`

**Comment by sallf** [comment]
For anyone who wants to globally update to the new syntax, the regex below might help. 

From `import { ReactComponent as Blog } from '@shared-images/icons/blog.svg` to `import Blog from '@shared-images/icons/blog.svg?react`

Find: `import\s+\{\s*ReactComponent\s+as\s+(\w+)\s*\}\s+from\s+['"]([^'"]+\.svg)['"]`
Replace: `import $1 from '$2?react'`

This worked for me in VS Code's global find and replace. Just be sure to click the `.*` button in the search box so that you're using regex.

**Comment by lukomwro** [comment]
If you want to use `vite-plugin-svgr@4` and import `svg` files as `ReactComponent` without `?react` suffix just override `vite.config.ts` file like that:

```js
export default defineConfig({
  // ...
  plugins: [
    // ...
    svgr({
      svgrOptions: { exportType: 'named', ref: true, svgo: false, titleProp: true },
      include: '**/*.svg',
    }),
    // ...
  ],
  // ...
});
```

Cheers 🍻

**Comment by jovanavukicevicdev** [comment]
> I was able to to use vite-plugin-svgr@4.1.0. Make sure to add the vite plugin in vite.config.ts and to add `"vite-plugin-svgr/client"` to the tsconfig.app.json `types` array after installing. Then the import syntax is `import Logo from '../assets/logo.svg?react';`

Is no one here worried about adding  `"vite-plugin-svgr/client"` to the tsconfig.app.json `types` array, and overwriting the defaults, if types were not declared before this at all?

**Comment by janathedev** [comment]
> I was able to to use vite-plugin-svgr@4.1.0. Make sure to add the vite plugin in vite.config.ts and to add `"vite-plugin-svgr/client"` to the tsconfig.app.json `types` array after installing. Then the import syntax is `import Logo from '../assets/logo.svg?react';`

Is no one here worried about declaring the types array in tsconfig.json and adding "vite-plugin-svgr/client" to it, effectively overwriting the defaults? https://www.typescriptlang.org/tsconfig#types

**Comment by russellpeiris** [comment]
It's 2024 and still the issue exists.

**Comment by Anj-interactivated** [comment]
had to follow this to make it work https://vitejs.dev/guide/features.html#client-types

**Comment by rrain0** [comment]
@lukomwro
> If you want to use vite-plugin-svgr@4 and import svg files as ReactComponent without ?react suffix just override vite.config.ts file like that:
> 
> export default defineConfig({
>   // ...
>   plugins: [
>     // ...
>     svgr({
>       svgrOptions: { exportType: 'named', ref: true, svgo: false, titleProp: true },
>       include: '**/*.svg',
>     }),
>     // ...
>   ],
>   // ...
> });

I've also added type declaration from react to vite-env.d.ts:
```ts
declare module '*.svg' {
  import * as React from 'react';
  
  export const ReactComponent: React.FunctionComponent<React.SVGProps<
    SVGSVGElement
  > & { title?: string }>;
  
  const src: string;
  export default src;
}
```

**Comment by praizjosh** [comment]
> If you want to use `vite-plugin-svgr@4` and import `svg` files as `ReactComponent` without `?react` suffix just override `vite.config.ts` file like that:
> 
> ```js
> export default defineConfig({
>   // ...
>   plugins: [
>     // ...
>     svgr({
>       svgrOptions: { exportType: 'named', ref: true, svgo: false, titleProp: true },
>       include: '**/*.svg',
>     }),
>     // ...
>   ],
>   // ...
> });
> ```
> 
> Cheers 🍻

I also encountered a similar issue using `vite-plugin-svgr@4` to import `svg` files as `ReactComponent` without the `?react` suffix in my project. I slightly modified your solution to get it to work for me.

Under svgrOptions, instead of `exportType: 'named'` I used `exportType: 'named'` and it did the trick.

Just make sure your imported svg file name is the same as the component e.g

`import Logo from "./logo.svg";` ==> `<Logo />`

**Comment by ceduth** [comment]
works great! thanks

**Comment by zuhno** [comment]
@rrain0 Following your advice, there's an issue where importing files like this:
```
import whatever from "assets/img/whatever.svg";
```
doesn't return the src path. Have you managed to resolve this issue as well?
I am inquiring because the project involves passing the aforementioned src as Props to a styled-components component, hence my question.

**Comment by WouterrV** [comment]
> If you want to use `vite-plugin-svgr@4` and import `svg` files as `ReactComponent` without `?react` suffix just override `vite.config.ts` file like that:
> 
> ```js
> export default defineConfig({
>   // ...
>   plugins: [
>     // ...
>     svgr({
>       svgrOptions: { exportType: 'named', ref: true, svgo: false, titleProp: true },
>       include: '**/*.svg',
>     }),
>     // ...
>   ],
>   // ...
> });
> ```
> 
> Cheers 🍻

Works for me, took me a minute to figure out that `exportType: 'named' ` means imports have to happen like
`import { ReactComponents as MySvgFile } from './mySvgFile.svg'`, which is not in the docs of `vite-plugin-svgr`.

**Comment by GicaGashy** [comment]
> If you want to use `vite-plugin-svgr@4` and import `svg` files as `ReactComponent` without `?react` suffix just override `vite.config.ts` file like that:
> 
> ```js
> export default defineConfig({
>   // ...
>   plugins: [
>     // ...
>     svgr({
>       svgrOptions: { exportType: 'named', ref: true, svgo: false, titleProp: true },
>       include: '**/*.svg',
>     }),
>     // ...
>   ],
>   // ...
> });
> ```
> 
> Cheers 🍻

Thank you mate, after 4 hours this did the trick!

**Comment by oyv1cent** [comment]
> @rrain0 Following your advice, there's an issue where importing files like this:
> 
> ```
> import whatever from "assets/img/whatever.svg";
> ```
> 
> doesn't return the src path. Have you managed to resolve this issue as well? I am inquiring because the project involves passing the aforementioned src as Props to a styled-components component, hence my question.

You can configure the exclude field to specify parts that do not need to be converted to React Component.

```
export default defineConfig({
  // ...
  plugins: [
    // ...
    svgr({
      svgrOptions: { exportType: 'named', ref: true, svgo: false, titleProp: true },
      include: '**/*.svg',
      exclude: ['src/assets/svg/**/*.svg']
    }),
    // ...
  ],
  // ...
});
```

**Comment by lolero** [comment]
> > If you want to use `vite-plugin-svgr@4` and import `svg` files as `ReactComponent` without `?react` suffix just override `vite.config.ts` file like that:
> > ```js
> > export default defineConfig({
> >   // ...
> >   plugins: [
> >     // ...
> >     svgr({
> >       svgrOptions: { exportType: 'named', ref: true, svgo: false, titleProp: true },
> >       include: '**/*.svg',
> >     }),
> >     // ...
> >   ],
> >   // ...
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Cheers 🍻
> 
> Thank you mate, after 4 hours this did the trick!

You saved me!

I've been looking for a solution to this for days and couldn't find documentation for the `svgrOptions`.
After reading your solution I tried a few things and it turns out that I only need `exportType: 'named`` for my app to work with v5.

Cheers!

**Comment by jaysoo** [comment]
Thanks all who chimed in, especially @oyv1cent with the config example.

I opened a PR to document this setup here: https://github.com/nrwl/nx/pull/27551

We don't want to have SVGR by default as not everyone uses it, and we're trying to keep our Vite setup as lean as possible.
