### ISSUE TITLE
feat(schematics): allow 'prefix' when creating a lib

### ISSUE THREAD

**Issue by wvanderdeijl** [nrwl/nx#193]
It would be nice if `--prefix` would be supported when generating a new library with `ng generate lib hello --prefix hello`. Currently we have instructions to add the `prefix` manually in the apps section of the .angular-cli.json. This allows us to have unique prefixes for all libraries.

**Comment by ball6847** [comment]
When I create a lib and then create component with `--prefix` 

```
ng g lib foo-layout
ng g component layout --app=foo-layout --prefix=foo
```

but when i run `ng lint` it keep saying 

```
The selector of the component "LayoutComponent" should have prefix "app"
```

I tried editing `.angular-cli.json` to manually set the prefix but got no luck.

It would be nice if `ng g lib` supports `--prefix`

**Comment by wvanderdeijl** [comment]
The trick to making this work is to add the prefix to the generated apps section in .angular-cli.json and also adding the prefix to two tslint rules in tslint.json that have the list of allowed prefixes. Hopefully I can find the time to create a PR to add these steps to the nx schematics

**Comment by vsavkin** [comment]
It has been implemented in Nx 6. Pass `--prefix` when creating a library, and it will be set in the tslint.json file of that library.

**Comment by sutin1234** [comment]
we can disabled prefix at angular.json
