### ISSUE TITLE
nx generate service doesn't account for the current directory

### ISSUE THREAD

**Issue by robertIsaac** [nrwl/nx#19308]
### Current Behavior

it generate Angular Service file always at the root of the project

### Expected Behavior

to generate it in the directory that the command is executed from

### GitHub Repo

https://github.com/robertIsaac/nx-ng-nest

### Steps to Reproduce

```
cd apps\ng\src\app
mkdir services
cd services
nx g s foo
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : win32-x64
   npm    : 9.6.7

   nx                 : 16.8.1
   @nx/js             : 16.8.1
   @nx/jest           : 16.8.1
   @nx/linter         : 16.8.1
   @nx/workspace      : 16.8.1
   @nx/angular        : 16.8.1
   @nx/cypress        : 16.8.1
   @nx/devkit         : 16.8.1
   @nx/eslint-plugin  : 16.8.1
   @nx/nest           : 16.8.1
   @nx/node           : 16.8.1
   @nrwl/tao          : 16.8.1
   @nx/webpack        : 16.8.1
   nx-cloud           : 16.4.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @nguniversal/builders       : 16.2.0
   @nguniversal/express-engine : 16.2.0
```

### Failure Logs

```shell
PS C:\Users\rober\WebstormProjects\nx-ng-nest\apps\ng\src\app\services> nx g s foo
√ Which generator would you like to use? · @schematics/angular:service

>  NX  Generating @schematics/angular:service

CREATE apps/ng/src/app/foo.service.spec.ts
CREATE apps/ng/src/app/foo.service.ts
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

1. it works correctly for component
2. it doesn't work even from the nx webstorm plugin

**Comment by pkirchniawy** [comment]
@AgentEnder I would like to contribute to this issue. Would it be possible?

**Comment by pkirchniawy** [comment]
I did some investigation on this issue. So it seems that there are 2 problems, as why it does not create the files in the expected folder:

1) The underlying schematic is coming from the Angular Team, and the path parameter is optional. Hence, if it's not passed to the executor, it will take the project root (see https://github.com/angular/angular-cli/blob/main/packages/schematics/angular/utility/workspace.ts#L121) As for now, it seems, that the path parameter is not passed into the executor. That could be fixed.

2) But, even if the path would be passed to the Angular Schematic, there is an open Issue on pnpm causing the return value of the function `getPath()` (https://github.com/nrwl/nx/blob/6704483dfd24867e8e7eeb3fa6eaeef02d1a8233/packages/nx/src/utils/path.ts#L32) to return the wrong path. That is because pnpm does not set the INIT_CWD environment variable correct, see https://github.com/pnpm/pnpm/issues/7042. That causes the `getPath()` function to return the path to the folder containing the package.json, which is wrong. That issue does not exist when invoking the generator via npm/npx. So it's a pnpm-only issue here.

I will try to provide a pull request for point 1), but with point 2) we have to wait for pnpm to fix the open issue.

**Comment by robertIsaac** [comment]
> I did some investigation on this issue. So it seems that there are 2 problems, as why the files are not created in the expected folder:
> 
> 1. The underlying schematic is coming from the Angular Team, and the path parameter is optional. Hence, if it's not passed to the executor, it will take the project root (see https://github.com/angular/angular-cli/blob/main/packages/schematics/angular/utility/workspace.ts#L121) As for now, it seems, that the path parameter is not passed into the executor. That could be fixed.
> 2. But, even if the path would be passed to the Angular Schematic, there is an open Issue on pnpm causing the return value of the function `getCwd()` (https://github.com/nrwl/nx/blob/6704483dfd24867e8e7eeb3fa6eaeef02d1a8233/packages/nx/src/utils/path.ts#L32
>    ) to return the wrong path. That is because pnpm does not set the INIT_CWD environment variable correct, see [INIT_CWD env variable should be set to path of where `pnpm` was invoked pnpm/pnpm#7042](https://github.com/pnpm/pnpm/issues/7042). That causes the `getCwd()` function to return the path to the folder containing the package.json, which is wrong. That issue does not exist when invoking the generator via npm/npx. So it's a pnpm-only issue here.
> 
> I will try to provide a pull request for point 1), but with point 2) we have to wait for pnpm to fix the open issue.

question regarding point 2
if I'm installing using pnpm but will invoke using npx, will this fix the problem?

**Comment by pkirchniawy** [comment]
> > I did some investigation on this issue. So it seems that there are 2 problems, as why the files are not created in the expected folder:
> > 
> > 1. The underlying schematic is coming from the Angular Team, and the path parameter is optional. Hence, if it's not passed to the executor, it will take the project root (see https://github.com/angular/angular-cli/blob/main/packages/schematics/angular/utility/workspace.ts#L121) As for now, it seems, that the path parameter is not passed into the executor. That could be fixed.
> > 2. But, even if the path would be passed to the Angular Schematic, there is an open Issue on pnpm causing the return value of the function `getCwd()` (https://github.com/nrwl/nx/blob/6704483dfd24867e8e7eeb3fa6eaeef02d1a8233/packages/nx/src/utils/path.ts#L32
> >    
> >    ) to return the wrong path. That is because pnpm does not set the INIT_CWD environment variable correct, see [INIT_CWD env variable should be set to path of where `pnpm` was invoked pnpm/pnpm#7042](https://github.com/pnpm/pnpm/issues/7042). That causes the `getCwd()` function to return the path to the folder containing the package.json, which is wrong. That issue does not exist when invoking the generator via npm/npx. So it's a pnpm-only issue here.
> > 
> > I will try to provide a pull request for point 1), but with point 2) we have to wait for pnpm to fix the open issue.
> 
> question regarding point 2 if I'm installing using pnpm but will invoke using npx, will this fix the problem?

Unfortunately no, as the current dir is not passed through as param to the Angular Schematic, even though it has the correct value if invoked using npx. So point 1) needs to be fixed in order to make npx work.

**Comment by robertIsaac** [comment]
> > > I did some investigation on this issue. So it seems that there are 2 problems, as why the files are not created in the expected folder:
> > > 
> > > 1. The underlying schematic is coming from the Angular Team, and the path parameter is optional. Hence, if it's not passed to the executor, it will take the project root (see https://github.com/angular/angular-cli/blob/main/packages/schematics/angular/utility/workspace.ts#L121) As for now, it seems, that the path parameter is not passed into the executor. That could be fixed.
> > > 2. But, even if the path would be passed to the Angular Schematic, there is an open Issue on pnpm causing the return value of the function `getCwd()` (https://github.com/nrwl/nx/blob/6704483dfd24867e8e7eeb3fa6eaeef02d1a8233/packages/nx/src/utils/path.ts#L32
> > >    
> > >    ) to return the wrong path. That is because pnpm does not set the INIT_CWD environment variable correct, see [INIT_CWD env variable should be set to path of where `pnpm` was invoked pnpm/pnpm#7042](https://github.com/pnpm/pnpm/issues/7042). That causes the `getCwd()` function to return the path to the folder containing the package.json, which is wrong. That issue does not exist when invoking the generator via npm/npx. So it's a pnpm-only issue here.
> > > 
> > > I will try to provide a pull request for point 1), but with point 2) we have to wait for pnpm to fix the open issue.
> > 
> > 
> > question regarding point 2 if I'm installing using pnpm but will invoke using npx, will this fix the problem?
> 
> Unfortunately no, as the current dir is not passed through as param to the Angular Schematic, even though it has the correct value if invoked using npx. So point 1) needs to be fixed in order to make npx work.

I meant after your fix

**Comment by pkirchniawy** [comment]
> I meant after your fix

Yes, then it should 😄
