### ISSUE TITLE
@nx/dependency-checks ignoring devDependencies

### ISSUE THREAD

**Issue by vsamofal** [nrwl/nx#19307]
### Current Behavior

When you run `npx nx affected:lint` and you have a dependency in a devDependencies in a package json, lint reporting an error, but it actually shouldn't and it works fine with peerDeps, but not with devDeps

### Expected Behavior

Lint shouldn't fail if dependency is in devDeps (e.g. faker library used only in tests)

### Steps to Reproduce

1. create a lib
2. configure nx-dep check rule
3. add some dependency to package.json dev section
4. run lint, see that nx rule doesn't see this dep 

### Nx Report

```shell
✔  nx run test-utils:lint  [remote cache]
    ✔  nx run exceptions:lint  [remote cache]
    ✔  nx run string-utils:lint  [remote cache]
    ✔  nx run typeorm:lint  [remote cache]
    ✔  nx run server-http-client:lint  [remote cache]
    ✔  nx run auth:lint  [remote cache]
    ✔  nx run config:lint  [remote cache]
    ✔  nx run swagger-utils:lint  [remote cache]
    ✔  nx run i18n:lint  [remote cache]
    ✔  nx run crypto:lint  [remote cache]
    ✔  nx run platform-client:lint  [remote cache]
    ✔  nx run logger:lint  [remote cache]
    ✔  nx run typeorm-service:lint  [remote cache]
    ✔  nx run health-check:lint  [remote cache]
    ✔  nx run bootstrap:lint  [remote cache]
    ✔  nx run common-types:lint  [remote cache]
    ✔  nx run async-storage:lint  [remote cache]
    ✔  nx run platform:lint  [remote cache]
    ✔  nx run resource-plugin:lint  [remote cache]

    ✖  nx run redis:lint
       Linting "redis"...
       
       /Users/vsamofal/projects/collaboration-framework/saas-buildkit/libs/redis/package.json
         19:3  error  The "redis" project uses the following packages, but they are missing from "dependencies":
           - @softkit/config  @nx/dependency-checks
       
       ✖ 1 problem (1 error, 0 warnings)
         1 error and 0 warnings potentially fixable with the `--fix` option.
       
       Lint errors found in the listed files.
       
       

    ✖  nx run validation:lint
       Linting "validation"...
       
       /Users/vsamofal/projects/collaboration-framework/saas-buildkit/libs/validation/package.json
         11:3  error  The "validation" project uses the following packages, but they are missing from "dependencies":
           - @faker-js/faker  @nx/dependency-checks
       
       ✖ 1 problem (1 error, 0 warnings)
         1 error and 0 warnings potentially fixable with the `--fix` option.
       
       Lint errors found in the listed files.
       
       

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target lint for 21 projects (4s)
 
    ✔    19/21 succeeded [19 read from cache]
 
    ✖    2/21 targets failed, including the following:
         - nx run redis:lint
         - nx run validation:lint
 
   View structured, searchable error logs at https://nx.app/runs/1BUNAF5j89

[22:15:23] [cost 4.534s] npx nx affected:lint                                                                      

[22:33:15] [~/projects/collaboration-framework/saas-buildkit] git(feature/redis_library) 🔥 ❱❱❱ npx nx affected:lint
[22:34:56] [~/projects/collaboration-framework/saas-buildkit] git(feature/redis_library) 🔥 ❱❱❱ nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 20.5.1
   OS     : darwin-arm64
   yarn   : 3.6.3
   
   nx                 : 16.8.1
   @nx/js             : 16.8.1
   @nx/jest           : 16.8.1
   @nx/linter         : 16.8.1
   @nx/workspace      : 16.8.1
   @nx/devkit         : 16.8.1
   @nx/eslint-plugin  : 16.8.1
   @nx/nest           : 16.8.1
   @nx/node           : 16.8.1
   @nx/plugin         : 16.8.1
   @nrwl/tao          : 16.8.1
   @nx/webpack        : 16.8.1
   nx-cloud           : 16.4.0
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @jscutlery/semver : 3.1.0
   ngx-deploy-npm    : 7.0.1
   ---------------------------------------
   Local workspace plugins:
         @softkit/resource-plugin
```

### Package Manager Version

3.6.3

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by MathurAditya724** [comment]
Having the same issue in the latest version also

```sh
33: 3  error  The "ui" project uses the following packages, but they are missing from "peerDependencies":
  - rollup-plugin-preserve-directives
  - @nx/react  @nx/dependency-checks
```

```sh
Node   : 19.7.0
OS     : darwin-x64
pnpm   : 8.8.0

nx                 : 16.9.1
@nx/js             : 16.9.1
@nx/linter         : 16.9.1
@nx/workspace      : 16.9.1
@nx/cypress        : 16.9.1
@nx/devkit         : 16.9.1
@nx/eslint-plugin  : 16.9.1
@nx/next           : 16.9.1
@nx/react          : 16.9.1
@nx/rollup         : 16.9.1
@nx/storybook      : 16.9.1
@nrwl/tao          : 16.9.1
@nx/vite           : 16.9.1
@nx/web            : 16.9.1
typescript         : 5.2.2
---------------------------------------
Community plugins:
@jscutlery/semver : 3.1.0
ngx-deploy-npm    : 7.0.1
```

Here is my repo - [https://github.com/rhinobase/raftyui](https://github.com/rhinobase/raftyui)
For the timing I have disabled the eslint rule in my `.eslintrc.json`
```jsonc
"overrides": [
    {
      "files": "package.json",
      "rules": {
        "@nx/dependency-checks": [
          "error",
          {
            "checkMissingDependencies": false
          }
        ]
      }
    },
    // Other overrides
    // ...
]
```

**Comment by meeroslav** [comment]
This is not an error but by design.

The purpose of this rule is to ensure your publishable library has all the necessary dependencies specified so that they are installed in the target repo.

The `devDependencies` are ignored on the install so you would end up in a potentially broken state.

If the dependencies listed under `devDependencies` are in fact dev dependencies you can use `ignoredFiles` property of the rule to ignore files that point to these dependencies. 

If the dependencies listed under `devDependencies` are used in the final output files, you should move them to `dependencies` or `peerDependencies`.

**Comment by vsamofal** [comment]
I will check ignoredFiles, thanks

**Comment by vsamofal** [comment]
@meeroslav 
![image](https://github.com/nrwl/nx/assets/27850115/0b58f72a-b78a-4950-b0d7-ee976e485adb)

I tried various options, but none of them actually works, Do you have any hint there?

**Comment by MathurAditya724** [comment]
This is in my `.eslintrc.json` file, under overrides

```json
{
  "files": ["*.json"],
  "parser": "jsonc-eslint-parser",
  "rules": {
    "@nx/dependency-checks": [
      "error",
      {
        "ignoredFiles": ["libs/ui/rollup.config.js"]
      }
    ]
  }
},
```

Seems to work correctly as per the [docs](https://nx.dev/nx-api/eslint-plugin/documents/dependency-checks). The problem bit be because you have to add the path of your file starting from the root of your project.

**Comment by vsamofal** [comment]
@MathurAditya724 thanks, but I don't see a full path in docs 
![image](https://github.com/nrwl/nx/assets/27850115/b531a1a2-bd92-4da8-9a57-1abca25c47ad)

https://nx.dev/nx-api/eslint-plugin/documents/dependency-checks

**Comment by MathurAditya724** [comment]
Yes, Initially I tried it with relative path like `"ignoredFiles": ["rollup.config.js"]`, but it failed. I guess it's because we are running the command from the root level, I am not sure.

**Comment by meeroslav** [comment]
@vsamofal I suggest adding the `src/__tests__` and `__tests__` as exclusion folders for production named input in the `nx.json`. That way you don't have to explicitly ignore it in the `.eslintrc.json`.

The `app.module.ts` should not be ignored. Ignoring that one is likely a mistake.

**Comment by vsamofal** [comment]
@meeroslav this app.module.ts is inside the __tests__, 

this app is for library tests, so not valid for the build. but thank you for pointing it 

Your suggestion about name inputs works like a charm! 

will leave a screenshot here for reference 
![image](https://github.com/nrwl/nx/assets/27850115/647253f8-f25c-401d-a83b-b07ac33aa0d3)
