### ISSUE TITLE
docs: createPackageJson, createLockFile no longer exported by @nx/devkit

### ISSUE THREAD

**Issue by firxworx** [nrwl/nx#19310]
### Documentation issue

Docs provide a recipe that has a custom executor:

```
import { createPackageJson, createLockFile } from '@nx/devkit';
```

However `@nx/devkit` does not export either of `createPackageJson`, `createLockFile` in current version.

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/recipes/ci/ci-deployment

### Additional context or description

I want to get Astro 3 with SSR working with Nx + Docker. Nothing in the community supports this yet.

To build my docker image with only the Astro app and only the Astro dependencies I found the doc to build a custom executor and create a package.json and lockfile. However looks like the docs led me down a false solution path. It feels like the instructions and recipes that could perhaps use some corresponding tests to ensure they stay accurate.

In any case is this not supported? I'm not even sure where to look now. 

In my Astro app's project.json I have build and serve targets that work OK for now with `astro build --config apps/op-ssr/astro.config.mjs` (I know this will **not** work with imported libs which is a key reason to use Nx and is a next step for me...).

Either way docs are out of sync vs. latest and at the moment I'm not sure how to integrate anything new with Nx if it won't create package.json any more.

**Comment by vdhpieter** [comment]
@firxworx both of them are now exported from `@nx/js`. I do get some build errors when using them on the latest version but maybe this helps you!
