### ISSUE TITLE
`npx nx g @nx/js:lib` doesn't use `libs` by-default anymore

### ISSUE THREAD

**Issue by Firfi** [nrwl/nx#19317]
### Current Behavior

`npx nx g @nx/js:lib` doesn't use `libs` by-default anymore but puts the library right into the project root

### Expected Behavior

according to defaults https://nx.dev/concepts/more-concepts/applications-and-libraries, `libs/` is used

### GitHub Repo

https://github.com/Firfi/nx-libs-default-repro

### Steps to Reproduce

1. `npx create-nx-workspace@latest`

<img width="571" alt="Screenshot 2023-09-25 at 11 18 04 AM" src="https://github.com/nrwl/nx/assets/947595/49d6717e-2260-4194-ac1a-5dfa26fcd7ef">

2. in the directory, `npx nx g @nx/js:lib  producer`

<img width="567" alt="Screenshot 2023-09-25 at 11 18 12 AM" src="https://github.com/nrwl/nx/assets/947595/dc6f885e-ca23-41e7-85be-16e5af614b04">

3. ls

<img width="424" alt="Screenshot 2023-09-25 at 11 18 18 AM" src="https://github.com/nrwl/nx/assets/947595/b162830b-9307-40af-a12d-9ab13d393854">

### Nx Report

```shell
npx nx report
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 20.6.0
   OS     : darwin-arm64
   npm    : 9.6.6

   nx                 : 16.9.0
   @nx/js             : 16.9.0
   @nx/jest           : 16.9.0
   @nx/linter         : 16.9.0
   @nx/workspace      : 16.9.0
   @nx/devkit         : 16.9.0
   @nx/eslint-plugin  : 16.9.0
   @nrwl/tao          : 16.9.0
   typescript         : 5.1.6

```
```


### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by AgentEnder** [comment]
This is intentional when using as-provided paths. You can use `derived` or update how you are passing the `--directory` flag to accommodate this. We are working on docs updates.
