### ISSUE TITLE
Seeing error "Static imports of lazy-loaded libraries are forbidden." when lazy loading is only occurring in tests

### ISSUE THREAD

**Issue by kaifresh** [nrwl/nx#19311]
### Current Behavior

In a Next JS app based on `@nx/next` I am receiving the error `Static imports of lazy-loaded libraries are forbidden.` from eslint, which as a dependency of the standard `build` command, is blocking deployment of my app. 

The instance in which dynamic import is being used is in testing, specifically to mock my database using the [TestContainers](https://testcontainers.com/) library. In my app code this library is only statically imported. 

This leaves me with some options, none of which is that appealing:
* Warn instead of error on `@nx/enforce-module-boundaries`
* Find another way to mock the database in a more convoluted manner (unless you guys are aware of a way to do this cleanly)
* Do a `jest` only mock of the database

### Expected Behavior

When i statically import a library in app code but dynamically import it in tests for mocking purposes, I want to be able to exclude test files from the analysis of mixed static & dynamic imports. 

### Steps to Reproduce

1. Statically import a library in your app code
2. Dynamically import the same library in test code

### Nx Report

```shell
Node   : 16.17.1
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx (global)        : 16.7.4
   nx                 : 16.8.1
   @nx/js             : 16.8.1
   @nx/jest           : 16.8.1
   @nx/linter         : 16.8.1
   @nx/workspace      : 16.8.1
   @nx/cypress        : 16.8.1
   @nx/devkit         : 16.8.1
   @nx/esbuild        : 16.8.1
   @nx/eslint-plugin  : 16.8.1
   @nx/next           : 16.8.1
   @nx/node           : 16.8.1
   @nx/react          : 16.8.1
   @nrwl/tao          : 16.8.1
   @nx/web            : 16.8.1
   nx-cloud           : 16.4.0
   typescript         : 5.2.2
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Not a solution, but as a workaround you can use //nx-ignore when dynamic importing in the tests and Nx shouldn't pick up the dynamic dependency causing the lint error.

**Comment by kaifresh** [comment]
Thanks @AgentEnder I will give that a go.

**Comment by kaifresh** [comment]
I'm also hoping there is some kind of configuration option, such as being able to specify a set of files/glob that would be excluded from the static/dynamic check. I'd also be happy to implement this for the project if this is an issue that occurs for others too.

**Comment by meeroslav** [comment]
We do not provide such options as, generally, this is a graph inconsistency. We suggest doing same type of import in production files as you do in your tests (static-static, dynamic-dynamic).

If that is too much work for you you can use `// nx-ignore` as @AgentEnder recommended

**Comment by kaifresh** [comment]
Alright thanks @meeroslav I'll follow that approach
