### ISSUE TITLE
Need official version management support

### ISSUE THREAD

**Issue by kunyan** [nrwl/nx#19319]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

According from https://nx.dev/recipes/adopting-nx/lerna-and-nx#version-management-publishing

There are no official way to release new version for nx workspace.
I think version management for mono repo is the most important part

What's we need ?

1. Bump version for packages in `sync` or `independent` mode.
2. Publish to npm registry/github registry if needed. or set "private: true" to skip
3. Create git tag for each release
4. Create GitHub/GitLab release
5. Changelog auto generation
6. CI support

There are some features could be inherited by [semantic release](https://github.com/semantic-release/semantic-release)

## Alternate Implementations

3rd party plugins for version management
https://github.com/jscutlery/semver
https://github.com/TheUnderScorer/nx-semantic-release

**Comment by AgentEnder** [comment]
Working on it ✏️ , see: https://github.com/nrwl/nx/pull/19110
