### ISSUE TITLE
vite:preview-server and web:file-server not allowing to set the baseHref value

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#19323]
### Current Behavior

I've tried configuring the [@nx/vite:preview-server](https://nx.dev/nx-api/vite/executors/preview-server#nxvitepreviewserver)
With the configuration:
```ts
    "preview": {
      "executor": "@nx/vite:preview-server",
      "defaultConfiguration": "production",
      "options": {
        "buildTarget": "app:build",
        "port": 4200
      }
    },
```

I get this error:
```ts
GET http://localhost:4201/app/lifecycle/assets/config/env.js net::ERR_ABORTED 404 (Not Found)
Refused to execute script from 'http://localhost:4201/app/lifecycle/assets/config/env.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
GET http://localhost:4201/app/lifecycle/main.77e00ef97361d24f.js net::ERR_ABORTED 404 (Not Found)
```
Then I've tried configuring the [@nx/web:file-server](https://nx.dev/nx-api/web/executors/file-server#nxwebfileserver)
```ts
    "serve-static": {
      "executor": "@nx/web:file-server",
      "options": {
        "buildTarget": "orchestrator:build:production",
        "port": 4200,
        "proxyUrl": "http://localhost:4200?",
        "watch": false,
        "parallel": true
      }
    },
```
I get this error:
```ts
GET http://localhost:4200/app/lifecycle/assets/config/env.js net::ERR_ABORTED 404 (Not Found)
GET http://localhost:4200/app/lifecycle/main.0314434fd75ef8b1.js net::ERR_ABORTED 404 (Not Found)
```

### Expected Behavior

The server, together with its files should be served properly.

### Steps to Reproduce

1. With the same configuration run the `nx serve-static your_app` or `nx preview your_app`
2. Open the provided url http://localhost:4200
3. Observe an empty screen

### Nx Report

```shell
Node   : 18.15.0
   OS     : linux-x64
   yarn   : 3.6.3
   
   nx                 : 16.7.4
   @nx/js             : 16.7.4
   @nx/jest           : 16.7.4
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.7.4
   @nx/cypress        : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nx/react          : 16.7.4
   @nx/vite           : 16.7.4
   @nx/web            : 16.7.4
   @nx/webpack        : 16.7.4
   typescript         : 5.1.6
```

### Package Manager Version

yarn: 3.6.3

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

My application has the baseHref and deployUrl properties set, and neither of these solutions allows setting those values so that the assets can get adequately loaded.

**Comment by nemonemi** [comment]
My application has the `baseHref` and `deployUrl` properties set, and neither of these solutions allows setting those values so that the assets can get adequately loaded.

**Comment by xiongemi** [comment]
i could not replicate this issue for vite, I tried to add baseHref to my react app build target like:
```
"build": {
      "executor": "@nx/vite:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "outputPath": "dist/apps/web",
        "baseHref": "/test"
      },

```

when i run with default serve and preview target, it seems fine. it serves up with baseHref added at http://localhost:4201/test. this is my preview target:

```
    "preview": {
      "executor": "@nx/vite:preview-server",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "web:build",
        "port": 4201
      },
```

i could replicate this with [@nx/web:file-server](https://nx.dev/nx-api/web/executors/file-server#nxwebfileserver). currently, serve-static target does not support baseHref options. mostly because it is using https://www.npmjs.com/package/http-server underneath, which does not support baseHref. It is meant to be a simple static server.

what does your build target look like?
