### ISSUE TITLE
docs(homepage): home page link to plugins registry broken

### ISSUE THREAD

**Issue by AdditionAddict** [nrwl/nx#19320]
### Documentation issue

Clicking "Plugins registry" from the homepage nx.dev leads to 404 https://nx.dev/extending-nx/registry

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[Home page.](https://nx.dev)

### Additional context or description

Provide any additional details here as needed.

**Comment by AgentEnder** [comment]
Hey 👋, I think this is just from you having a stale cache for nx.dev. Can you try hitting cmd+shift+r and seeing if it works? We changed that URL earlier.

**Comment by AdditionAddict** [comment]
@AgentEnder you're right 😅
