### ISSUE TITLE
nx.dev packages cannot see

### ISSUE THREAD

**Issue by yeukfei02** [nrwl/nx#19321]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/packages

### Additional context or description

when I click into this link, I cannot see the nx packages and documentation.

**Comment by yeukfei02** [comment]
looks like cmd + shift + r
then I can see, but it is strange.

**Comment by AgentEnder** [comment]
Ah, seems like your cache may have been stale.
