### ISSUE TITLE
Show Generator Output in Docs

### ISSUE THREAD

**Issue by koliveira15** [nrwl/nx#19341]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Include modified files list for each generator and permutation 

<img width="682" alt="image" src="https://github.com/nrwl/nx/assets/35852680/e245a12d-a76c-4ad9-879e-a333db602657">

## Motivation
Insight into exactly what files are modified, deleted, or created so I know what Im getting without actually running the command with dryRun flag

## Suggested Implementation
Modify the build docs script to read the e2e tests output for each plugin & generator so that the output is added under the "Usage" section in the docs

**Comment by sharky98** [comment]
Hello,

I was looking at the docs trying to find some info regarding the difference between a `@nx/node` library and a `@nx/js` library. I was about to propose something similar to this (having a typical output example). Also I may want to add two other wishes:

1. Document for each generators and executors their executor and generator dependencies.
    - `@nx/node:library` execute `@nx/js:library`
    - `@nx/js:library` execute `@nx/js:init`
2. Split the options between the "own" options and those from the dependencies the modified options, the extended options and the ignored options.
    - `@nx/node:library` only
        - `babelJest`
        - `rootDir`
        - `standaloneConfig`
    - `@nx/node:library` changed allowed values
        - `unitTestRunner`
    - `@nx/node:library` modified name of options, but for same purpose from `@nx/js:library`
        - `simpleModuleName` (node) => `simpleName` (js)
    - `@nx/js:library` not found in `@nx/node:library`
        - `bundler`
        - `config`
        - `includeBabelRc`
        - `minimal`
        - `rootProject`
        - `skipPackageJson`

I have however absolutely no idea how this could be done in the simplest way. Just giving an idea out there! 😊

**Comment by FrozenPandaz** [comment]
I don't think having our docs being a snapshot of what is generated is a good way to understand what the generators do.

It is better for our docs to describe what the generator does, when and how they are intended to be used. Seeing the changes the generator will produce is better done via the `--dryRun` flag rather than looking it up in the docs.
