### ISSUE TITLE
Add cacheability option to targets (take two)

### ISSUE THREAD

**Issue by fxposter** [nrwl/nx#19356]
I'd like to resurrect #17443. It was cancelled due to lack of convincing reasons to have the ability to specify particular targets as cacheable instead of only maintaining the global cacheable task list.

I want to present 2 reasons for that.
1. We plan to use nx in our CI pipeline and some of the targets will be programmatically added to some or all targets by a plugin, but it is not possible to mark them cacheable by the plugin and instead users need to understand what exactly the plugin does and add all/some targets that are created by plugin and if plugin changes - they would need to adjust the list, which is not convenient.
2. Sometimes I want to restructure targets for a particular project. Let's consider I have a `build` and `test` targets and `test` dependsOn `build`. Both of targets are in `cacheableOperations` on the workspace level. Now I'd like to `test` target, cause I have multiple disjoint sets of tests and can easily run them all in parallel. So I split `test` to `test:unit`+`test:integration`+`test:e2e` in this particular project and make a dummy `test` target that depends on them all. By doing that I don't need to manually manage target dependencies and can make the task graph solve the "running stuff in parallel" problem for me. Or, for example, I can split `build` to `build:js`+`build:css`+`build:fonts`, etc. The problem here lies in the fact that those targets are highly project-specific, but I cannot make them cacheable in any way other than polluting the global workspace `cacheableOperations` list with an aggregation of a lot of project-specific tasks.

Given the fact that the solution was proposed in previous issue and the solution seems very simple, doesn't require support over time and gives users additional capabilities of leaving config, that is related to the project, inside the project itself (where it belong) - I would really like to see this feature to be implemented.

cc @meeroslav

**Comment by AgentEnder** [comment]
We are working on this now, but at first it will only be specifiable from `targetDefaults`. There are portions of the nx cloud tasks runner that rely on `cacheableOperations`, after that is patched up we will remove some of the guardrails that require it be inside targetDefaults.

**Comment by fxposter** [comment]
Do you know how much time will it take, maybe?

**Comment by AgentEnder** [comment]
No eta

**Comment by LanderBeeuwsaert** [comment]
Question, would this also solve/fix this? => https://github.com/nrwl/nx/issues/18984

**Comment by fxposter** [comment]
If I understood correctly https://github.com/nrwl/nx/pull/19672/files basically does what I asked for, right?

**Comment by AgentEnder** [comment]
Yeah, this should be solved in v17.
