### ISSUE TITLE
Cypress tests using angular application servered using esbuild is not working

### ISSUE THREAD

**Issue by gmfun** [nrwl/nx#19351]
### Current Behavior

When a try to run cypress e2e or component test using dev server as angular application using `"executor": "@angular-devkit/build-angular:browser-esbuild",`. the tests fails and 

It throws 404 error on visit to `/`

On changing executor back to non esbuild one makes it work

### Expected Behavior

e2e should work for both esbuild application as well

### Steps to Reproduce

1. Create an angular application with cypress e2e tests
2. Change applications project.json to "executor": "@angular-devkit/build-angular:browser-esbuild", for build
3. Run e2e test
4. 404 error is thrown

### Nx Report

```shell
Node   : 20.7.0
   OS     : darwin-arm64
   npm    : 10.1.0

   nx (global)        : 16.9.0
   nx                 : 16.9.1
   @nx/js             : 16.9.1
   @nx/jest           : 16.9.1
   @nx/linter         : 16.9.1
   @nx/workspace      : 16.9.1
   @nx/angular        : 16.9.1
   @nx/cypress        : 16.9.1
   @nx/devkit         : 16.9.1
   @nx/eslint-plugin  : 16.9.1
   @nrwl/tao          : 16.9.1
   @nx/web            : 16.9.1
   @nx/webpack        : 16.9.1
   typescript         : 5.1.6
```

### Failure Logs

```shell
ui
    1) "before each" hook for "should display welcome message"
  0 passing (269ms)
  1 failing
  1) ui
       "before each" hook for "should display welcome message":
     CypressError: `cy.visit()` failed trying to load:
/
We failed looking for this file at the path:
/x/apps/ui-e2e/
The internal Cypress web server responded with:
  > 404: Not Found
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
hey @gmfun! This should have been solved in the latest version of Nx. Could you update your workspace and retry with latest?
