### ISSUE TITLE
Target Descriptions

### ISSUE THREAD

**Issue by ethanjdiamond** [nrwl/nx#19355]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

An optional "description" field for target definitions that is a human readable description of the target. This would then be surfaced in `nx graph`, `nx show [project]` and the nx plugin for VSCode.

## Motivation

As monorepos grow large, you tend to get a large variety of targets that need to be run to accomplish different tasks. It's not always obvious from context what a target does, or how to use it. For example, a target might require an extra argument that's expected to be used like `nx run project:install -- otherpackage`, but there's nowhere great to quickly capture that information for other developers who are unfamiliar with your project. It'd be great to see at a glance, particularly in the nx VS plugin, a list of a projects targets and what they do.

## Suggested Implementation

A target definition in a project.json file would include a field for "description" that is free-text. The ProjectConfiguration for project nodes would pick up that string and store it as part of the target definition. Dev tools would then present that field if present.

## Alternate Implementations
I'm not sure if there's a particularly good alternate option worth considering that achieves the goal.

**Comment by alberturria** [comment]
I see it's been a while already, but I'd love to have this feature too. (And I'm also willing to help there! 🙂)
Is there any new regarding this?

**Comment by FrozenPandaz** [comment]
This feature is now available: You can specify the description for your project under `metadata`:

project.json
```
{
  metadata: {
    description: 'This is the marketing app'
  }
}
```

![image](https://github.com/user-attachments/assets/23377363-ee3f-4bc5-85a1-50e8d201e5b3)

I'll get this documented.
