### ISSUE TITLE
packages page

### ISSUE THREAD

**Issue by aarifkhamdi** [nrwl/nx#19369]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/packages

### Additional context or description

The packages article link on main page (https://nx.dev) doesn't work. Direct access to the https://nx.dev/packages works

**Comment by AgentEnder** [comment]
Which link are you referring to? A cmd+f for `packages` on that page doesn't find a link. Maybe you have a cached version of the page, can you try refreshing it?

**Comment by aarifkhamdi** [comment]
> Which link are you referring to? A cmd+f for `packages` on that page doesn't find a link. Maybe you have a cached version of the page, can you try refreshing it?

I checked it with two browsers before reporting. Now it disappeared 👀
