### ISSUE TITLE
Nest Plugin: Add migration to replace '@nestjs/common' by '@nestjs/axios' for 'HttpModule' imports

### ISSUE THREAD

**Issue by JonasBernard** [nrwl/nx#19379]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
I'm relatively new to nx. I don't know if this is something possible to do by plugin migrations.

After using nx migrate, imports of the "HttpModule" failed:
```
'"@nestjs/common"' has no exported member named 'HttpModule'. Did you mean 'HttpCode'?
```

A quick google search revealed, that the module moved inside nest so I can replace
```
import { HttpModule } from '@nestjs/common';
```
by
```
import { HttpModule } from '@nestjs/axios';
```
and everything is fine.

Maybe someone can implement a migration for that.

## Motivation
That's what migrations are made for, at least as far as I understand them.

## Suggested Implementation
Don't know.

**Comment by JonasBernard** [comment]
Referenc: 
https://github.com/nestjs/nest/issues/9385#issuecomment-1079452560

**Comment by FrozenPandaz** [comment]
This issue is outdated. Even NestJS does not mention that deprecation anymore. It's a bit late for us to be adding the migration.
