### ISSUE TITLE
When creating new projects with `--preset=npm` we no longer get automatic nested apps or libs inside `/packages/` 

### ISSUE THREAD

**Issue by fsgreco** [nrwl/nx#19377]
### Current Behavior

I think this could be a bug, cannot tell if it's related to `Nx` or `@nx/react`.
Here are the minimum passages to reproduce the effect:

1. `npx create-nx-workspace@latest myproject --preset=npm`
2. `npm install @nx/react -W` 
3. `npx nx g @nx/react:app frontend --routing --style styled-components --bundler vite --e2eTestRunner none` (this will create a tsconfig.base.json at the root of the project).
4. `npx nx g @nx/react:lib ui-demo --importPath=@myorg/ui-demo`

As a result you will get this project structure: 
```
myproject/
├── frontend
├── ui-demo
└── etc...      
```

### Expected Behavior

Couple of versions ago if I created a project using  `--preset=npm` I will then get all my apps or libs automatically inside a `/packages/` folder (since it creates a project with a `package.json` property `"workspaces": ["packages/*" ]`, so following the same steps above the expected behaviour should be this: 
```
My-Nx-Project/
├── packages/
│   ├── frontend
│   └── ui-demo
└── etc...      
```

### Steps to Reproduce

already provided them above 👍🏽 

### Nx Report

```shell
Node   : 18.13.0
   OS     : darwin-x64
   npm    : 8.19.3

   nx                 : 16.9.1
   @nx/js             : 16.9.1
   @nx/linter         : 16.9.1
   @nx/workspace      : 16.9.1
   @nx/devkit         : 16.9.1
   @nx/eslint-plugin  : 16.9.1
   @nx/react          : 16.9.1
   @nrwl/tao          : 16.9.1
   @nx/vite           : 16.9.1
   @nx/web            : 16.9.1
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

PS: I know for a fact that this was not the expected behaviour because I was following the same exact steps for another issue I opened a month ago ( https://github.com/nrwl/nx/issues/18492#issuecomment-1670919230 ) and it worked as I described above.

**Comment by AgentEnder** [comment]
The default behavior has changed since then, and the behavior going forward is that you should pass the full path to where you want a project to be created in the `--directory` argument for the given generator. This is expected. We are going this route to reduce a bit of magic that was hard to work around in previous versions when you had valid reasons to want a project outside of the normal folder.

**Comment by fsgreco** [comment]
Thanks for the response, I guess the `--directory` argument it's fine. May I suggest to change the documentation though? It's a bit confusing at the moment since according to the `package-based` page it should create the `packages/` folder:  https://nx.dev/getting-started/tutorials/package-based-repo-tutorial

**Comment by AgentEnder** [comment]
Yeah, the change is quite recent and docs review is still in progress.
