### ISSUE TITLE
Angular generator for Signals migration

### ISSUE THREAD

**Issue by EelcoLos** [nrwl/nx#19380]
## Description
A generator for migrating angular observables migration to Signals.

## Motivation
The Angular team themselves made a blog to change zone detection: https://www.angulararchitects.io/en/blog/angular-signals/. Here, they explained to use Angular Signals as a path towards the new detection method.

Therefore, support for migrating to Signals would be amazing. As done with the `nx generate @angular/core:standalone-migration` standalone migration, it could be divided into some steps. For example:
* HTML Analysis for Async Pipe Observables: One key feature of this generator could be the ability to analyze HTML sections of Angular components that use the async pipe to render Observables. The `[existingTitles]="existingTitles$ | async"` observable type should be changed to `[existingTitles]="existingTitles()"`. 
* Called items via `.subscribe()`: As I'm understanding Signals, the `.subscribe()` is forcing actions which are synchronous. As Signals are primarily synchronous, it should be encouraged to use signals over using `.subscribe()`.

## Suggested Implementation
A multi-stage generator as the aforementioned `nx generate @angular/core:standalone-migration`. This way the migration can be incremental.

## Alternate Implementations
When Signals are fully implemented a forced nx migration for the package `nx/angular`. This seems more forced than the generator, where people can slowly migrate sections to signals

**Comment by Coly010** [comment]
Hi @EelcoLos!

Thank you for the suggestion!

Unfortunately, this is not something we are prepared to do. There are many use-cases and patterns in the Angular world that use Observables and correctly identifying the right user-code to switch from Observables is difficult to impossible. It's also not guaranteed to replicate the same behaviour and therefore becomes a very high risk migration to run.

If you're interested in doing this yourself, you could create your own Nx Plugin that you publish that contains the generator.

You can learn more about working with the Nx Devkit here: https://nx.dev/extending-nx/intro/getting-started#create-a-local-plugin

Thanks again for the suggestion!
