### ISSUE TITLE
Unable to customize the webpack configuration when the webpack config and the module federation config are both written in TypeScript (React integrated monorepo)

### ISSUE THREAD

**Issue by nikitalepikhin** [nrwl/nx#19396]
### Current Behavior

I have generated two module federation host apps using the `@nx/react - host` generator. I have used the following configuration (I will paste it as a command for brevity): `nx g @nx/react:host --name=my-app --directory=apps/my-app --e2eTestRunner=none --minimal=true --pascalCaseFiles=true --projectNameAndRootFormat=as-provided --unitTestRunner=none`. I have also selected the `typescriptConfiguration` checkbox.

The issue I am experiencing is that I am unable to add a custom webpack configuration extension function to my webpack.config.ts: 

```
import { Configuration } from 'webpack';

export default composePlugins(
  withNx(),
  withReact(),
  withModuleFederation(config),
  (config: Configuration) => config // this function breaks the app upon launch
);
```

Launching the app results in a TS error: `error TS7006: Parameter 'config' implicitly has an 'any' type`.

I have created two apps inside the linked repo. The `javascript-host` app has both the webpack config and the module federation config written in javascript. The `typescript-host` app has both files written in typescript.

**I have managed to isolate the issue and found that whenever both the webpack configuration and the module configuration are written in TypeScript, this issue occurs.**

I suspected that the issue is somehow related to the compilation of the webpack.config.ts with ts-node before launching, however this turned out to be a wrong assumption. The reason for that is because commenting out all module federation related lines inside the webpack.config.ts does not help. On the other hand, commenting out those lines and converting the module federation config into a javascript file solves the issue.

### Expected Behavior

I should be able to add a custom webpack configuration extension function and have both the webpack config and the module federation config files written in typescript.

### GitHub Repo

https://github.com/nikitalepikhin/nx-webpack-config-ts-error

### Steps to Reproduce

1. Open the provided [repo](https://github.com/nikitalepikhin/nx-webpack-config-ts-error).
2. Check out the `main` branch and run `npm install`.
3. You can start both apps in the `apps` directory by running 
    - `npx nx run javascript-host:serve:development`
    - `npx nx run typescript-host:serve:development`
4. Now check out the `error-state` branch.
5. Try running the typescript-host app `npx nx run typescript-host:serve:development`.
6. The app will fail with a TS error: `error TS7006: Parameter 'config' implicitly has an 'any' type`.
7. Now you can check out the `error-v2-state` branch where all rows related to the module federation config inside the webpack.config.ts of the typescript-host app have been commented out. Launching the app now will also result in the same error.
8. Finally, you can check out the `workaround-state` branch where the module federation config has been converted to a javascript file. Launching the app now works without any issues.

### Nx Report

```shell
Node   : 20.8.0
   OS     : win32-x64
   npm    : 10.1.0

   nx                 : 16.9.1
   @nx/js             : 16.9.1
   @nx/jest           : 16.9.1
   @nx/linter         : 16.9.1
   @nx/workspace      : 16.9.1
   @nx/devkit         : 16.9.1
   @nx/eslint-plugin  : 16.9.1
   @nx/react          : 16.9.1
   @nrwl/tao          : 16.9.1
   @nx/web            : 16.9.1
   @nx/webpack        : 16.9.1
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

The issue persists on both macOS and Windows.

**Comment by AgentEnder** [comment]
This should be fixed in the next release, can you try in v17 or the first beta that is released? Betas and RCs should start soon.

**Comment by nikitalepikhin** [comment]
Ok, I will once the beta is available.
