### ISSUE TITLE
"projectRoot is not defined" happens when trying to add Cypress to a single migrated Angular App

### ISSUE THREAD

**Issue by distante** [nrwl/nx#19390]
### Current Behavior

- calling `npx nx g @nx/cypress:configuration app-e2e --project=app` fails with the error `projectRoot is not defined`

### Expected Behavior

The running should identify that no more than one app exists and the projectRoot is `.`

### Steps to Reproduce

1. Migrate an empty angular app to nx
2. run `npx nx g @nx/cypress:configuration app-e2e --project=app`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.18.0
   OS     : darwin-arm64
   npm    : 8.19.2

   nx                 : 16.9.1
   @nx/js             : 16.9.1
   @nx/jest           : 16.9.1
   @nx/linter         : 16.9.1
   @nx/workspace      : 16.9.1
   @nx/angular        : 16.9.1
   @nx/cypress        : 16.9.1
   @nx/devkit         : 16.2.2
   @nx/eslint-plugin  : 16.9.1
   @nrwl/tao          : 16.9.1
   @nx/webpack        : 16.9.1
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @briebug/jest-schematic  : 3.1.0
   @compodoc/compodoc       : 1.1.21
   @ionic/angular           : 7.1.0
   @ionic/angular-toolkit   : 9.0.0
   @nxext/capacitor         : 16.3.0
   @storybook/angular       : 6.5.16
   @testing-library/angular : 11.0.4
   ngx-spec                 : 2.1.6
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/devkit@16.2.2
     - @nrwl/devkit@16.2.2

   To fix this, run `nx migrate nx@16.9.1`
```

### Failure Logs

```shell
❯ npx nx g @nx/cypress:configuration app-e2e --project=app

>  NX  Generating @nx/cypress:configuration

✔ Which Cypress bundler do you want to use? · vite
Error in node_modules/@nx/cypress/src/generators/configuration/files/v9/cypress.json:

 >  NX   ejs:9

       7|   "pluginsFile": false,
       8|   "video": true,
    >> 9|   "videosFolder": "<%= offsetFromRoot %>dist/cypress/<%= projectRoot %>/videos",
       10|   "screenshotsFolder": "<%= offsetFromRoot %>dist/cypress/<%= projectRoot %>/screenshots",
       11|   "chromeWebSecurity": false
       12| }

   projectRoot is not defined
   Pass --verbose to see the stacktrace.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I have migrated an angular app to nx, which means, there is just one app that lives at the root of the folder.

If I manually provide the variable as `--projectRoot=.` it works as expected

**Comment by mandarini** [comment]
@distante thanks for filing an issue!

So, what is the name of your project? Is it `app`?

I mean, here's what I did:

1. `ng new my-ng-app`
2. `cd my-ng-app`
3. `npx nx@latest init`
4. Take note, now, that your project's name is `my-ng-app`, not `app`.
5. `npx nx g @nx/cypress:configuration app-e2e --project=my-ng-app`
6. Works

If I do `npx nx g @nx/cypress:configuration app-e2e --project=app` it will throw the error it threw for you, too, because there's no project named `app`.
