### ISSUE TITLE
nextjs project's hot reloading is malfunctioning

### ISSUE THREAD

**Issue by jaketakula** [nrwl/nx#19399]
### 1. Create a new nextjs project `helloworld` wih the below script:
```bash
nvm use 18
npm install -g pnpm

pnpx create-nx-workspace@16.9.1 wkspace --workspaceType=integrated \
--preset=apps --nxCloud=false -y

pnpx nx@16.9.1 g @nx/next:app  helloworld --style=@emotion/styled --appDir=true --directory=apps \
--e2eTestRunner=playwright --swc=true
```

### 2. Serve the helloworld with hot reloading:
```bash
pnpx nx@16.9.1 run cloud-ui:serve --configuration=development
```

### 2. go to localhost:4200 and you will see the error:

<img width="1125" alt="image" src="https://github.com/nrwl/nx/assets/143328617/cd81afa4-2acf-40c1-8bcb-66b584e2a25c">

### Expected Behavior

the page shoudl successfully initially loaded and further hot-loaded with any code changes in
`apps/cloud-ui/app/page.tsx`.

### 1. Create a new nextjs project `helloworld` wih the below script:
```bash
npx create-nx-workspace@16.9.1 wkspace --workspaceType=integrated \
--preset=apps --nxCloud=false -y

npx nx@16.9.1 g @nx/next:app  helloworld --style=@emotion/styled --appDir=true --directory=apps \
--e2eTestRunner=playwright --swc=true
```

### 2. Serve the helloworld with hot reloading:
```bash
npx nx@16.9.1 run cloud-ui:serve --configuration=development
```

### 2. go to localhost:4200 and you will see the error:

<img width="1125" alt="image" src="https://github.com/nrwl/nx/assets/143328617/cd81afa4-2acf-40c1-8bcb-66b584e2a25c">

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.18.0
   OS     : darwin-x64
   pnpm   : 8.8.0
   
   nx (global)        : 16.8.1
   nx                 : 16.9.1
   @nx/js             : 16.9.1
   @nrwl/js           : 16.7.4
   @nx/jest           : 16.7.4
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.9.1
   @nrwl/workspace    : 16.7.4
   @nx/devkit         : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nx/nest           : 16.7.4
   @nx/next           : 16.7.4
   @nx/node           : 16.7.4
   @nx/playwright     : 16.7.4
   @nx/react          : 16.7.4
   @nrwl/tao          : 16.7.4
   @nx/web            : 16.7.4
   typescript         : 5.1.6
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/js@16.7.4
     - @nx/jest@16.7.4
     - @nrwl/jest@16.7.4
     - @nx/linter@16.7.4
     - @nrwl/linter@16.7.4
     - @nrwl/workspace@16.7.4
     - @nx/devkit@16.7.4
     - @nrwl/devkit@16.7.4
     - @nx/eslint-plugin@16.7.4
     - @nrwl/eslint-plugin-nx@16.7.4
     - @nx/nest@16.7.4
     - @nrwl/nest@16.7.4
     - @nx/next@16.7.4
     - @nrwl/next@16.7.4
     - @nx/node@16.7.4
     - @nrwl/node@16.7.4
     - @nx/playwright@16.7.4
     - @nx/react@16.7.4
     - @nrwl/react@16.7.4
     - @nrwl/tao@16.7.4
     - @nx/web@16.7.4
     - @nrwl/web@16.7.4
   
   To fix this, run `nx migrate nx@16.9.1`
```

### Failure Logs

Executing task: pnpm exec nx run cloud-ui:serve 

> nx run cloud-ui:serve:development

- ready started server on 0.0.0.0:4200, url: http://localhost:4200
- event compiled client and server successfully in 1904 ms (311 modules)
- wait compiling...
- event compiled client and server successfully in 1295 ms (311 modules)
- wait compiling /page (client and server)...
- warn ../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
Attempted import error: 'createContext' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js
./app/page.tsx
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
Attempted import error: 'createContext' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js
./app/page.tsx
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-react.esm.js
Attempted import error: 'useRef' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-react.esm.js
../../node_modules/.pnpm/@emotion+styled@11.11.0_@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/styled/dist/emotion-styled.esm.js
./app/page.tsx
../../node_modules/.pnpm/@emotion+use-insertion-effect-with-fallbacks@1.0.1_react@18.2.0/node_modules/@emotion/use-insertion-effect-with-fallbacks/dist/emotion-use-insertion-effect-with-fallbacks.esm.js
Attempted import error: 'useLayoutEffect' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+use-insertion-effect-with-fallbacks@1.0.1_react@18.2.0/node_modules/@emotion/use-insertion-effect-with-fallbacks/dist/emotion-use-insertion-effect-with-fallbacks.esm.js
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js
./app/page.tsx
- error ../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js (14:41) @ React
- error createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component
    at eval (webpack-internal:///(sc_server)/../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js:34:92)
    at (sc_server)/../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js (/Users/jakzha/Documents/takula-nita/apps/cloud-ui/.next/server/app/page.js:1636:1)
    at __webpack_require__ (/Users/jakzha/Documents/takula-nita/apps/cloud-ui/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js:8:95)
    at (sc_server)/../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js (/Users/jakzha/Documents/takula-nita/apps/cloud-ui/.next/server/app/page.js:1647:1)
    at __webpack_require__ (/Users/jakzha/Documents/takula-nita/apps/cloud-ui/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./app/layout.tsx:6:88)
    at (sc_server)/./app/layout.tsx (/Users/jakzha/Documents/takula-nita/apps/cloud-ui/.next/server/app/page.js:1559:1)
    at Function.__webpack_require__ (/Users/jakzha/Documents/takula-nita/apps/cloud-ui/.next/server/webpack-runtime.js:33:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  name: 'TypeError',
  digest: undefined
}
null
- warn ../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
Attempted import error: 'createContext' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js
./app/page.tsx
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
Attempted import error: 'createContext' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js
./app/page.tsx
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-react.esm.js
Attempted import error: 'useRef' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-react.esm.js
../../node_modules/.pnpm/@emotion+styled@11.11.0_@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/styled/dist/emotion-styled.esm.js
./app/page.tsx
../../node_modules/.pnpm/@emotion+use-insertion-effect-with-fallbacks@1.0.1_react@18.2.0/node_modules/@emotion/use-insertion-effect-with-fallbacks/dist/emotion-use-insertion-effect-with-fallbacks.esm.js
Attempted import error: 'useLayoutEffect' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+use-insertion-effect-with-fallbacks@1.0.1_react@18.2.0/node_modules/@emotion/use-insertion-effect-with-fallbacks/dist/emotion-use-insertion-effect-with-fallbacks.esm.js
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js
./app/page.tsx
- wait compiling /_error (client and server)...
- warn ../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
Attempted import error: 'createContext' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js
./app/page.tsx
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
Attempted import error: 'createContext' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js
./app/page.tsx
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-react.esm.js
Attempted import error: 'useRef' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-react.esm.js
../../node_modules/.pnpm/@emotion+styled@11.11.0_@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/styled/dist/emotion-styled.esm.js
./app/page.tsx
../../node_modules/.pnpm/@emotion+use-insertion-effect-with-fallbacks@1.0.1_react@18.2.0/node_modules/@emotion/use-insertion-effect-with-fallbacks/dist/emotion-use-insertion-effect-with-fallbacks.esm.js
Attempted import error: 'useLayoutEffect' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+use-insertion-effect-with-fallbacks@1.0.1_react@18.2.0/node_modules/@emotion/use-insertion-effect-with-fallbacks/dist/emotion-use-insertion-effect-with-fallbacks.esm.js
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js
./app/page.tsx

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I manually fix the issue by adding `use client`.
the server error gone but hot-reloading not working correctly.
(I mean the broswer is becoming unresponsive after any code changes).

**Comment by jaketakula** [comment]
Executing task: pnpm exec nx run cloud-ui:serve 


> nx run cloud-ui:serve:development

- ready started server on 0.0.0.0:4200, url: http://localhost:4200
- event compiled client and server successfully in 1904 ms (311 modules)
- wait compiling...
- event compiled client and server successfully in 1295 ms (311 modules)
- wait compiling /page (client and server)...
- warn ../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
Attempted import error: 'createContext' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js
./app/page.tsx
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
Attempted import error: 'createContext' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js
./app/page.tsx
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-react.esm.js
Attempted import error: 'useRef' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-react.esm.js
../../node_modules/.pnpm/@emotion+styled@11.11.0_@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/styled/dist/emotion-styled.esm.js
./app/page.tsx
../../node_modules/.pnpm/@emotion+use-insertion-effect-with-fallbacks@1.0.1_react@18.2.0/node_modules/@emotion/use-insertion-effect-with-fallbacks/dist/emotion-use-insertion-effect-with-fallbacks.esm.js
Attempted import error: 'useLayoutEffect' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+use-insertion-effect-with-fallbacks@1.0.1_react@18.2.0/node_modules/@emotion/use-insertion-effect-with-fallbacks/dist/emotion-use-insertion-effect-with-fallbacks.esm.js
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js
./app/page.tsx
- error ../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js (14:41) @ React
- error createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component
    at eval (webpack-internal:///(sc_server)/../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js:34:92)
    at (sc_server)/../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js (/Users/jakzha/Documents/takula-nita/apps/cloud-ui/.next/server/app/page.js:1636:1)
    at __webpack_require__ (/Users/jakzha/Documents/takula-nita/apps/cloud-ui/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js:8:95)
    at (sc_server)/../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js (/Users/jakzha/Documents/takula-nita/apps/cloud-ui/.next/server/app/page.js:1647:1)
    at __webpack_require__ (/Users/jakzha/Documents/takula-nita/apps/cloud-ui/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./app/layout.tsx:6:88)
    at (sc_server)/./app/layout.tsx (/Users/jakzha/Documents/takula-nita/apps/cloud-ui/.next/server/app/page.js:1559:1)
    at Function.__webpack_require__ (/Users/jakzha/Documents/takula-nita/apps/cloud-ui/.next/server/webpack-runtime.js:33:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  name: 'TypeError',
  digest: undefined
}
null
- warn ../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
Attempted import error: 'createContext' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js
./app/page.tsx
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
Attempted import error: 'createContext' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js
./app/page.tsx
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-react.esm.js
Attempted import error: 'useRef' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-react.esm.js
../../node_modules/.pnpm/@emotion+styled@11.11.0_@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/styled/dist/emotion-styled.esm.js
./app/page.tsx
../../node_modules/.pnpm/@emotion+use-insertion-effect-with-fallbacks@1.0.1_react@18.2.0/node_modules/@emotion/use-insertion-effect-with-fallbacks/dist/emotion-use-insertion-effect-with-fallbacks.esm.js
Attempted import error: 'useLayoutEffect' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+use-insertion-effect-with-fallbacks@1.0.1_react@18.2.0/node_modules/@emotion/use-insertion-effect-with-fallbacks/dist/emotion-use-insertion-effect-with-fallbacks.esm.js
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js
./app/page.tsx
- wait compiling /_error (client and server)...
- warn ../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
Attempted import error: 'createContext' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js
./app/page.tsx
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
Attempted import error: 'createContext' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-6bdfffb2.esm.js
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js
./app/page.tsx
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-react.esm.js
Attempted import error: 'useRef' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/dist/emotion-react.esm.js
../../node_modules/.pnpm/@emotion+styled@11.11.0_@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/styled/dist/emotion-styled.esm.js
./app/page.tsx
../../node_modules/.pnpm/@emotion+use-insertion-effect-with-fallbacks@1.0.1_react@18.2.0/node_modules/@emotion/use-insertion-effect-with-fallbacks/dist/emotion-use-insertion-effect-with-fallbacks.esm.js
Attempted import error: 'useLayoutEffect' is not exported from 'react' (imported as 'React').
Import trace for requested module:
../../node_modules/.pnpm/@emotion+use-insertion-effect-with-fallbacks@1.0.1_react@18.2.0/node_modules/@emotion/use-insertion-effect-with-fallbacks/dist/emotion-use-insertion-effect-with-fallbacks.esm.js
../../node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.14_react@18.2.0/node_modules/@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js
./app/page.tsx

**Comment by diegovilar** [comment]
Tested in 16.8, 16.9 and 16.10. The problem seems to happen on all 3 releases whenever you use any of the CSS-in-JS libraries available in the generator.

@emotion/styled and styl don't work at all (compilation errors), while styled-components and styl break hot-reloading.

Funny thing: if you modify a page, it will not only not autorefresh but will also hang the browser if you manually refresh the page. Meanwhile, if you open another tab it will load the page correctly with the modified content.

Using css, scss or less work as expected. Maybe the problem has something to do with the fact that [CSS-in-JS libraries which require runtime JavaScript are not currently supported in Server Components](https://nextjs.org/docs/app/building-your-application/styling/css-in-js)?

**Comment by diegovilar** [comment]
You're putting 'use client' on top of page.tsx? CSS-in-JS libs that need a client runtime are not supported in server components yet, if I'm not mistaken. 'use client' will break hot reloading if used in a next page. Move your client component to another file and importe it in your page. Should work.

**Comment by ndcunningham** [comment]
@jaketakula what @diegovilar is correct: https://nextjs.org/docs/app/building-your-application/styling/css-in-js

Closing as this is not a Nx issue
