### ISSUE TITLE
dotenv file for each task and configuration must be read before determining whether a cache hit has occurred.

### ISSUE THREAD

**Issue by Chanki-Min** [nrwl/nx#19392]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

NX is comparing the results of hashing different variables to cache each operation. One of these is the dotenv environment variable file, represented by .env.

[NX documentation says that it reads the dotenv file for each task and configuration](https://nx.dev/recipes/tips-n-tricks/define-environment-variables#setting-environment-variables), and in fact it reads the dotenv file just before the task execution and passes it to the child process that will execute the task ([nx source permalink](https://github.com/nrwl/nx/blob/e29e9f90b6c5cf2a5b686327d68de15b873c7c4c/packages/nx/src/tasks-runner/forked-process-task-runner.ts#L235)). So when the task executes, the dotenv file is read and passed as expected.

However, in the current implementation, task execution (including reading the dotenv file) occurs after the process of comparing the task hash to the local remote cache, specifically computing the task hash. Therefore, the dotenv file is not being considered at all in the process of determining the task hash to determine whether a cache hit has occurred.

## Motivation

Because of this, even though the dotenv file is being used in the task and is being put into the named input in nx.json, it's not being considered for cache, so the correct cache is not being configured.

For example, if you create an environment variable file like the one below and use with named input configuration
```
// file path : /apps/myApp/.env.production
NEXT_PUBLIC_API_KEY=someSecretKey123
```
``` json
// file path : /apps/myApp/project.json
{
  "name": "myApp",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/myApp",
  "projectType": "application",
  "targets": {
    "build": {
      "executor": "@nx/next:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "inputs": ["production", "^production", {"env": "NEXT_PUBLIC_API_KEY"}]
      "options": {
        "outputPath": "dist/apps/myApp",
      },
      "configurations": {
        "development": {
          "outputPath": "apps/affiliate"
        },
        "production": {}
      }
    },
}
```

and run the command like this
```
pnpm exec nx run myApp:build --congifuration=production
```

The first run (while the cache is cold) will build without cache.

If you then modify the environment variables like below and run the same comment, it will cached
```
// file path : /apps/myApp/.env.production
NEXT_PUBLIC_API_KEY=someSecretKey456
```

The cache is being hit when it shouldn't be because, as explained above, the task hasher is not reading the dotenv file, but only hashing the current process.env.

## Suggested Implementation

This behavior can be corrected by changing the function call that gets the environment variables in the [hashEnv function](https://github.com/nrwl/nx/blob/e29e9f90b6c5cf2a5b686327d68de15b873c7c4c/packages/nx/src/hasher/task-hasher.ts#L775).

Make hashEnv to get the appropriate dotenv based on the current task and configuration ([like this code](https://github.com/nrwl/nx/blob/e29e9f90b6c5cf2a5b686327d68de15b873c7c4c/packages/nx/src/tasks-runner/forked-process-task-runner.ts#L235)), and hashEnv to use that env object.

However, I don't understand all parts of NX (especially the daemon server part). As currently implemented, [the getEnv function](https://github.com/nrwl/nx/blob/master/packages/nx/src/hasher/set-hash-env.ts#L17) of hashEnv is using the environment variable injected by the daemon server if the daemon server is running, **and I'd like to hear if it's possible to completely ignore the daemon server and implement it as above.**

## Alternate Implementations

This can also be solved by hashing the env file rather than the env by putting the env file as a fileset named input, such as .env.production.

However, in the current NX implementation, .gitignored files are not read by the task hasher, even if specified in the project settings, and this is difficult to use because in most cases organizations .gitignore the .env.* pattern to prevent each developer from accidentally uploading environment variables to external storage.

**Comment by Chanki-Min** [comment]
Seems like i cant add labels to this issue, this should be type:core maybe?

**Comment by doong-jo** [comment]
@FrozenPandaz 
Hello, I would appreciate hearing your thoughts on the proposal above.

**Comment by jbadeau** [comment]
This is quite a blocker for us as we get invalid cache hits and then the wrong code in artifacts.

**Comment by FrozenPandaz** [comment]
This makes sense those env variables should be taken into account for the hashing.
cc @Cammisuli 

As a workaround for now, you could add those files as inputs instead. You add a `!*.env` to `.nxignore` so that Nx will un-ignore it.

I'll take a look at this :thinking:

**Comment by Chanki-Min** [comment]
Thank you for your reply (and fix!) 🥰

This will make us to use build cache work as expected!
