### ISSUE TITLE
Reusable vs app-specific libs

### ISSUE THREAD

**Issue by MichaelWarneke** [nrwl/nx#194]
Would it make sense to have the app-specific libs scaffold under libs in the specific app folder and only the reusable libs in the lib folder? 
Just referring to the new article from @vsavkin in the [blog]([https://blog.nrwl.io/12-things-to-help-large-organizations-do-angular-right-f261a798ad6b) where it says:
NX can
Create app-specific libs and extract reusable libs

I like the the approach but for it is not clear how to scaffold this in a good way.

**Comment by Yonet** [comment]
@MichaelWarneke you can check out this repo for reference: https://github.com/nrwl/nx-workshop-project
