### ISSUE TITLE
React, MFE - application with devRemotes failed to start

### ISSUE THREAD

**Issue by vadimka123** [nrwl/nx#19407]
### Current Behavior

After update from 16.8.1 to 16.9.1 (also checked on new just created project) during serve processes (main application and application from devRemotes option) get killed and I'm getting "This site can’t be reached" as result in browser
Without devRemotes all good 
With verbose option I'm sometimes getting 
```
RpcExitError: Process 9013 exited [SIGTERM]
Issues checking service aborted - probably out of memory. Check the `memoryLimit` option in the ForkTsCheckerWebpackPlugin configuration.
If increasing the memory doesn't solve the issue, it's most probably a bug in the TypeScript.
```
Event with simple, created from scratch project

### Expected Behavior

Application must work with devRemotes option

### Steps to Reproduce

1. npx create-nx-workspace@latest
2. npx nx g @nrwl/react:host host --remotes=cart,blog,shop
3. nx serve host --open --devRemotes=cart --verbose

### Nx Report

```shell
Node   : 18.12.1
OS     : darwin-x64
npm    : 8.19.2

nx                 : 16.9.1
@nx/js             : 16.9.1
@nx/jest           : 16.9.1
@nx/linter         : 16.9.1
@nx/workspace      : 16.9.1
@nx/cypress        : 16.9.1
@nx/devkit         : 16.9.1
@nx/eslint-plugin  : 16.9.1
@nx/react          : 16.9.1
@nrwl/tao          : 16.9.1
@nx/web            : 16.9.1
@nx/webpack        : 16.9.1
nx-cloud           : 16.4.0
typescript         : 5.1.6
```

### Failure Logs

```shell
RpcExitError: Process 9013 exited [SIGTERM]
Issues checking service aborted - probably out of memory. Check the `memoryLimit` option in the ForkTsCheckerWebpackPlugin configuration.
If increasing the memory doesn't solve the issue, it's most probably a bug in the TypeScript.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by patrykluba** [comment]
I had the same problem. Increase memoryLimit helps me by put code in package.json:
`"fork-ts-checker": {
    "typescript": {
      "memoryLimit": 8000
    }
  }`

**Comment by vadimka123** [comment]
@patrykluba, It's abnormal after simple update version of nx 
And this happened with very simple example so it's very abnormal

**Comment by vadimka123** [comment]
After increasing memoryLimit no any errors, but the same behaviour
