### ISSUE TITLE
nx mono repo add to build effort

### ISSUE THREAD

**Issue by mhamri** [nrwl/nx#19404]
### Current Behavior

I'm questioning how Nx build works, and I've created a small reproduction to demonstrate that nx build doesn't reduce build effort; instead, it increases the time, memory usage, and complexity.

In summary:

I've created one app and four packages. Each app depends on the others for building. However, it's challenging to determine whether they are using each other's build results or building independently. To clarify this, I've added a plugin to prove that having Nx packages is equivalent to having a giant monolith app.

### Expected Behavior

build once, use multiple times (currently transpiled/transformed/built `rollup` package 5 times, 1 time correct and 4 times wrong), each build result helps to decrease build effort and memory usage. 

some commands like `nx serve` shouldn't load the whole usage tree into the memory to load the whole nx project 

should be able to run `nx build --watch --configuration=development` for performance increase

### GitHub Repo

https://github.com/mhamri/Bundling-Issues-in-Nx

### Steps to Reproduce

1- build the repo,
2- check each of the dist result, they should build on top of each other

### Nx Report

```shell
Enumerating objects: 112, done.
Counting objects: 100% (112/112), done.
Delta compression using up to 8 threads
Compressing objects: 100% (97/97), done.
Writing objects: 100% (112/112), 291.45 KiB | 7.88 MiB/s, done.
Total 112 (delta 22), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (22/22), done.
To https://github.com/mhamri/Bundling-Issues-in-Nx.git
 * [new branch]      main -> main
branch 'main' set up to track 'origin/main'.
PS C:\repo\toDelete\ngrx-nx-workshop\test-lib-connection\dist\apps\is-angular> nx report
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 16.20.0
   OS     : win32-x64
   npm    : 8.19.4

   nx (global)        : 16.9.1
   nx                 : 16.9.1
   @nx/js             : 16.9.1
   @nx/jest           : 16.9.1
   @nx/linter         : 16.9.1
   @nx/workspace      : 16.9.1
   @nx/angular        : 16.9.1
   @nx/esbuild        : 16.9.1
   @nx/eslint-plugin  : 16.9.1
   @nx/rollup         : 16.9.1
   @nx/vite           : 16.9.1
   typescript         : 5.1.6
```

### Package Manager Version

8.8.0

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Buildable libraries aren't always a slam dunk for performance, and there are a few reasons that the angular builder doesn't consume libraries from dist by default. Regardless, there is a docs article that describes how to enable them, that should get you where you want to be: https://nx.dev/recipes/angular/setup-incremental-builds-angular#setup-incremental-builds-for-angular-applications

**Comment by mhamri** [comment]
@AgentEnder did you see the repo? the issue isn't about angular. none of the lib builds with nx use each other output

I tried with vite, esbuild, tsc and rollup. 
this issue is about what is the point of having separate build in nx when each and every build using it's own? 

instead of building once, we build the same function 5 times and why closing the issue without confirming your understanding about the issue?
