### ISSUE TITLE
 Failed to create a workspace

### ISSUE THREAD

**Issue by kumail-talverse** [nrwl/nx#19415]
### Current Behavior

![image](https://github.com/nrwl/nx/assets/125370937/5ba9a576-a950-449f-8920-d113707f417a)

### Expected Behavior

workspace should be creeated

### Steps to Reproduce

1. Followed simple step, integrated opted for nestjs

### Nx Report

```shell
nx isn't installed
```

### Package Manager Version

npm 9.6.7, yarn 1.22.19

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

worked fine after downgraded to version 15.9.7

**Comment by parikshitsharma717** [comment]
though this is a bug but there's a workaround for it. create your workspace with preset flag.

`npx create-nx-workspace --preset=nest`

**Comment by kumail-talverse** [comment]
@parikshitsharma717 oh thanks, right now I have started with nx v15.9.7.
