### ISSUE TITLE
Transform Angular CLI 7 project to workspace fails on ng add @nrwl/schematics

### ISSUE THREAD

**Issue by JGhignatti** [nrwl/nx#1941]
## Expected Behavior

Able to `ng add @nrwl/schematics` on an Angular project created with Angular CLI 7.3.9.

## Current Behavior

Throwing error when running `ng add @nrwl/schematics`. It moves my app inside a new created folder called `apps`, but doesn't create `libs` folder and `nx.json` file.

## Failure Information (for bugs)

<img width="481" alt="Screen Shot 2019-10-11 at 13 27 58" src="https://user-images.githubusercontent.com/27514735/66668287-3f399d00-ec2b-11e9-90ad-0264940b91c9.png">

### Steps to Reproduce

1. Run `ng new my-app` on Angular CLI 7.3.9.
2. Select Yes for routing and SCSS for styling.
3. Run `ng add @nrwl/schematics`.
4. Check error.

### Context

According to this article [here](https://medium.com/@jason.s.awbrey/angular-console-adding-nrwl-schematics-to-an-existing-project-1368ba1eb925) I tried to make `ng add` use npm, runned again, but same error.
Tried with another Angular CLI created app I have, one that was created on Angular 6 and upgraded to Angular 7, but got
`ENOENT: no such file or directory, open 'apps/tsq-web/tsconfig.app.json'` this time.

"@angular/core": "~7.2.0",
After adding @nrwl/schematics it add to package.json "@nrwl/schematics": "^8.6.0"

After running `ng g @nrwl/schematics:application my-test-app` I get `Cannot find nx.json`.

**Comment by JGhignatti** [comment]
Hi, @jdpearce thanks for checking this.
I've found this PR couple days after I posted this issue, it seems that it could fix my problem.
Thing is, would it be possible for me to checkout to the fix branch and run `ng add @nrwl/schematics`, but running the fix?

**Comment by vsavkin** [comment]
Looking into the PR. Hope to merge it soon.
