### ISSUE TITLE
Build fails only on CI and without any reason reported

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#19433]
### Current Behavior

When building a project locally, it passes without a problem (even with the cache cleared).
However, when running it on Gitlab, it fails without any reason as to why.

```
ERROR: Job failed: command terminated with exit code 1
```
We are applying the `--verbose` and ` --output-style=stream` to our build command, but still, no error output except that it has failed.

### Expected Behavior

The build should either pass or fail with a useful error message.

### Steps to Reproduce

Unfortunately, it is currently impossible to provide a reproduction.

We do have an app that is running on Webpack, and libraries that run on Vite.

### Nx Report

```shell
Node   : 18.15.0
   OS     : linux-x64
   yarn   : 3.6.3
   
   nx                 : 16.7.4
   @nx/js             : 16.7.4
   @nx/jest           : 16.7.4
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.7.4
   @nx/cypress        : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nx/react          : 16.7.4
   @nx/vite           : 16.7.4
   @nx/web            : 16.7.4
   @nx/webpack        : 16.7.4
   typescript         : 5.1.6
```
Same with 
```shell
  Node   : 18.15.0
   OS     : linux-x64
   yarn   : 3.6.3
   
   nx                 : 16.9.1
   @nx/js             : 16.9.1
   @nx/jest           : 16.9.1
   @nx/linter         : 16.9.1
   @nx/workspace      : 16.9.1
   @nx/cypress        : 16.9.1
   @nx/devkit         : 16.9.1
   @nx/eslint-plugin  : 16.9.1
   @nx/react          : 16.9.1
   @nrwl/tao          : 16.9.1
   @nx/vite           : 16.9.1
   @nx/web            : 16.9.1
   @nx/webpack        : 16.9.1
   typescript         : 5.1.6
```

### Failure Logs

```shell
ERROR: Job failed: command terminated with exit code 1
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Can you check your CI usage statistics to see if the processes may be getting killed due to running out of memory or similar?

**Comment by nemonemi** [comment]
@AgentEnder, At the moment, that is not easily possible.
We've resolved our issue by switching from the Yarn PnP to node-modules.
