### ISSUE TITLE
Storybook Intereaction tests failing to run

### ISSUE THREAD

**Issue by louisjrdev** [nrwl/nx#19436]
### Current Behavior

When running `nx run componentlibrary:test-storybook` the test suite failed to run with error:
`TypeError: this._resolver.getGlobalPaths is not a function`

See screenshot of error from console:
![image](https://github.com/nrwl/nx/assets/17555062/742dc90e-0785-45a7-99e8-f8467e459540)

### Expected Behavior

Storybook tests should run without error.

### GitHub Repo

https://github.com/louisjrdev/nxstorybooktestbug

### Steps to Reproduce

1. `npm install` to install dependencies
2. Run `nx run componentlibrary:storybook`
3. Wait for that to finish building
4. Run `nx run componentlibrary:test-storybook`
5. See error in the console

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.15.0
   OS     : win32-x64
   npm    : 9.8.1
   
   nx (global)        : 16.9.1
   nx                 : 16.9.1
   @nx/js             : 16.9.1
   @nx/jest           : 16.9.1
   @nx/linter         : 16.9.1
   @nx/workspace      : 16.9.1
   @nx/angular        : 16.9.1
   @nx/cypress        : 16.9.1
   @nx/devkit         : 16.9.1
   @nx/eslint-plugin  : 16.9.1
   @nx/storybook      : 16.9.1
   @nrwl/tao          : 16.9.1
   @nx/web            : 16.9.1
   @nx/webpack        : 16.9.1
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @storybook/angular : 7.4.6
```

### Failure Logs

```shell
nx run componentlibrary:test-storybook

 FAIL   browser: chromium  componentlibrary/src/lib/testcomponent/testcomponent.component.stories.ts
  ● Test suite failed to run
    TypeError: this._resolver.getGlobalPaths is not a function
      at Runtime._execModule (node_modules/jest-runtime/build/index.js:1392:40)
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.819 s
Ran all test suites.
Warning: run-commands command "test-storybook -c componentlibrary/.storybook --url=http://localhost:4400" exited with non-zero status code

 ———————————————————————————————————————

 >  NX   Ran target test-storybook for project componentlibrary (3s)

    ×    1/1 failed
    √    0/1 succeeded [0 read from cache]
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

This issue was initially only happening in our production repo on CI builds and not locally, but was able to reproduce the issue locally in a new repo and workspace.

**Comment by mandarini** [comment]
@louisjrdev yes to be honest I could not reproduce. I will try to get hold of a person on the team who has a windows machine, maybe they can repro. Sorry about that!

**Comment by kfern** [comment]
Same here on Linux  >  NX   Report complete - copy this into the issue template

   Node   : 18.18.0
   OS     : linux-x64
   npm    : 9.8.1
   
   nx (global)        : 16.10.0
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/next           : 16.10.0
   @nx/playwright     : 16.10.0
   @nx/react          : 16.10.0
   @nx/storybook      : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/vite           : 16.10.0
   @nx/web            : 16.10.0
   typescript         : 5.1.6

**Comment by mandarini** [comment]
Thanks @kfern for reporting this! I am pretty sure this is an issue with test-runner, so thanks for creating an issue there!

**Comment by meeroslav** [comment]
FYI, the problem is with `npm` handling dependencies, not storybook or nx:
https://github.com/storybookjs/test-runner/issues/366#issuecomment-1801762421

**Comment by mandarini** [comment]
I will be closing this now, but feel free to reopen if you verify that it's an issue with Nx (which it seems that it is not)!
