### ISSUE TITLE
projects are being affected when they shouldn't be

### ISSUE THREAD

**Issue by theorlovsky** [nrwl/nx#19445]
### Current Behavior

According to `targetDefaults` in `nx.json`, a project should not be built when, for example, I only change a spec file. But my repro repository shows that it's not the case. On a larger scale (in a real-world repo) it means that by changing just one line in some `*.stories.ts` file I'm triggering A LOT of `lint`, `test` and `build` jobs, which costs us quite some time.

Is it a problem or am I simply missing something?

### Expected Behavior

Generally speaking, I expect `affected` to work as expected 😅
Or, in our case, changing one line in a `*.stories.ts` file should only trigger 1 `lint` job and 1 `build-storybook` job.

### GitHub Repo

https://github.com/theorlovsky/nx-bug-repro

### Steps to Reproduce

1. clone the repo
2. run `npm run show-affected:build`, which will show builds that are affected by the last commit

You can check the commits to see that the only changes made by me is adding the script and adding the comment to the spec file, so it's pretty much a pristine repo that I got after running the `npx create-nx-workspace@latest` command

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.18.0
   OS     : darwin-arm64
   npm    : 10.1.0
   
   nx                 : 16.9.1
   @nx/js             : 16.9.1
   @nx/jest           : 16.9.1
   @nx/linter         : 16.9.1
   @nx/workspace      : 16.9.1
   @nx/angular        : 16.9.1
   @nx/cypress        : 16.9.1
   @nx/devkit         : 16.9.1
   @nx/eslint-plugin  : 16.9.1
   @nrwl/tao          : 16.9.1
   @nx/webpack        : 16.9.1
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by theorlovsky** [comment]
I even tried changing `nx.json` to this:
```json
"targetDefaults": {
    "build": {
      "inputs": ["{projectRoot}/**/*.html"]
    }
}
```
But it didn't change anything, build is this affected, even tho I haven't touched any html file. So it seems to me as if these settings were completely ignored

**Comment by AgentEnder** [comment]
Inputs + outputs affect **_hashing_**, which is separate from affected. Affected isn't aware of which target is being ran, but you should get cache hits when running a target that may be affected but's inputs haven't changed. This is expected behavior.
