### ISSUE TITLE
Switching to @nx/dependency-checks causes `Couldn't find tsconfig.json. tsconfig-paths will be skipped`

### ISSUE THREAD

**Issue by avi-trackunit** [nrwl/nx#19456]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/nx-api/eslint-plugin/documents/dependency-checks

### Additional context or description

I've been working on removing `updateBuildableProjectDepsInPackageJson` and `buildableProjectDepsInPackageJsonType` from my project.json files as they are deprecated and replace them with `@nx/dependency-checks` rule.
I've been going through [this documentation](https://nx.dev/nx-api/eslint-plugin/documents/dependency-checks) but I'm get errors when running the lint script in my project.

```
Linting "my-lib"...
Couldn't find tsconfig.json. tsconfig-paths will be skipped
Error: You have attempted to use a lint rule which requires the full TypeScript type-checker to be available, but you do not have `parserOptions.project` configured to point at your project tsconfig.json files in the relevant TypeScript file "overrides" block of your project ESLint config `libs/@my-lib/.eslintrc.json`

Please see https://nx.dev/guides/eslint for full guidance on how to resolve this issue.
```

I've also made sure to add a parserOptions.project to my `eslint.json` and verified that the path to the `tsconfig.json` is correct (it worked fine before) and added a path to my `package.json` in the `lintFilePatterns` in my `project.json`, yet I still get the error above.

eslint.json
```
{
...
  "overrides": [
    {
      "files": ["*.json"],
      "parser": "jsonc-eslint-parser",
      "rules": {
        "@nx/dependency-checks": "error"
      }
    },
    {
      "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],
      "parserOptions": {
        "project": ["libs/@my-lib/tsconfig.*?.json"]
      },
      "rules": {}
    }
  ]
}
```

project.json
```
{
  ...
  targets: {
    ...
    "lint": {
      "executor": "@nx/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": [
          "libs/my-lib/**/*.ts",
          "libs/my-lib/package.json"
        ]
      }
    }
  }
}
```

**Comment by AgentEnder** [comment]
Hey, some fixes for this have been landed recently. I don't think they've been released yet, but could you check again in v17 when it is out?
