### ISSUE TITLE
[Request] add support for passing output path to @nrwl/node via CLI

### ISSUE THREAD

**Issue by jbjhjm** [nrwl/nx#1945]
## Expected Behavior

Angular's own builder features a [outputPath CLI parameter](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/server/schema.json#L64) which can be used to override the output directory temporarily. 

## Current Behavior

@nrwl/node is missing this feature. For automated build chain - though it's not required - it would be a great and tidy to let the build script set it externally.

Maybe you could add it? Thanks. :)

**Comment by jaysoo** [comment]
@jbjhjm Hey, the option is already (secretly) supported. You can pass `--outputPath=./tmp` to the build command.

We'll update the docs to reflect this. Thanks for reporting!

![Screen Shot 2019-10-17 at 9 57 39 AM](https://user-images.githubusercontent.com/53559/67015496-9e346180-f0c4-11e9-9602-a93ae2a4e459.png)
