### ISSUE TITLE
add ability to specify ignoredFiles wildcard for nx/dependency-checks rules 

### ISSUE THREAD

**Issue by vsamofal** [nrwl/nx#19461]
## Description

I want to be able to exclude directories from nx/dependency-check, so I don't need to choose each file and can for example exclude fully tests folder

## Motivation

It's convenient 

## Suggested Implementation

the same way as other patterns 

## Alternate Implementations

all good

**Comment by meeroslav** [comment]
The field `ignoredFiles` already accepts glob patterns so you could use something like `tests/**/*`.
