### ISSUE TITLE
Storybook generator creates stories for stories in Typescript project

### ISSUE THREAD

**Issue by davezuch** [nrwl/nx#19472]
### Current Behavior

Running `npx nx generate @nrwl/react:stories` is creating `<component>.stories.stories.tsx` files for some components.

### Expected Behavior

Stories should only be created for component files, not their story files.

This issue was reported in #10286 and marked as fixed in #10570, but the fix contains some complicated hueristics that won't always be valid, when it could just make sure the filename doesn't already end with `.stories.ts` or `.stories.tsx`.

### GitHub Repo

https://github.com/nrwl/nx-examples

### Steps to Reproduce

Instructions assume `npm`.

1. First install `@nx/storybook`:
    ```
    npm i -D @nx/storybook
    ```
2. Generate stories for the `cart-cart-page` project:
    ```
    npx nx generate @nrwl/react:stories --project=cart-cart-page
    ```
3. It should generate a `libs/cart/cart-page/src/lib/cart-cart-page/cart-cart-page.stories.tsx` file.
4. Modify that file with these changes:
    ```diff
    -import type { Meta, StoryObj } from '@storybook/react';
    +import * as Storybook from '@storybook/react';
    ```
    ```diff
    -const meta: Meta<typeof CartCartPage> = {
    +const meta: Storybook.Meta<typeof CartCartPage> = {
    ```
    ```diff
    -type Story = StoryObj<typeof CartCartPage>;
    +type Story = Storybook.StoryObj<typeof CartCartPage>;
    ```
    ```diff
     export const Primary = {
    -  args: {},
    +  args: {
    +    children: <span/>
    +  },
     };
    ```
5. Dry-run the story generation again:
    ```
    npx nx generate @nrwl/react:stories --project=cart-cart-page --dry-run
    ```
6. You'll see a `libs/cart/cart-page/src/lib/cart-cart-page/cart-cart-page.stories.stories.tsx` file would be generated.
7. Notice if named imports are used, or if there's no JSX declared in the module, no incorrect story will be generated, but with at least those two conditions present, they will.

### Nx Report

```shell
Node   : 18.17.1
   OS     : darwin-arm64
   yarn   : 1.22.19

   nx                 : 16.10.0-beta.2
   @nx/js             : 16.10.0-beta.2
   @nx/jest           : 16.10.0-beta.2
   @nx/linter         : 16.10.0-beta.2
   @nx/workspace      : 16.10.0-beta.2
   @nx/angular        : 16.10.0-beta.2
   @nx/cypress        : 16.10.0-beta.2
   @nx/devkit         : 16.10.0-beta.2
   @nx/eslint-plugin  : 16.10.0-beta.2
   @nx/react          : 16.10.0-beta.2
   @nx/storybook      : 16.10.0
   @nrwl/tao          : 16.10.0-beta.2
   @nx/web            : 16.10.0-beta.2
   @nx/webpack        : 16.10.0-beta.2
   nx-cloud           : 16.4.0
   typescript         : 5.1.3
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 16.0.0
   @ngrx/effects         : 16.0.0
   @ngrx/entity          : 16.0.0
   @ngrx/router-store    : 16.0.0
   @ngrx/store           : 16.0.0
   @ngrx/store-devtools  : 16.0.0
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/storybook@16.10.0
     - @nrwl/storybook@16.10.0

   To fix this, run `nx migrate nx@16.10.0`
```

### Package Manager Version

npm 9.6.7

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Hi @davezuch ! Thanks for the bug report! 

You can solve your issue at the moment using the `ignorePaths` flag: https://nx.dev/nx-api/react/generators/storybook-configuration#ignore-certain-paths-when-generating-stories

However, I understand what you mean. Our generators can not always account for all use cases, unfortunately. We decided that relying on just the file name (ignoring all paths that end in `.stories.*` would be assuming maybe too much, hence the heuristics you are describing.

We could add a default value to the `ignorePaths` field to ignore `.stories.*` files, I will consider this, thanks! I will also look into the generator logic, since it could be outdated!
