### ISSUE TITLE
@nx/jest:jest cannot be properly called from code

### ISSUE THREAD

**Issue by blairmcalpine** [nrwl/nx#19482]
### Current Behavior

I am trying to create a wrapper around the `@nx/jest:jest` executor, in which I want to maintain 100% of the executor's behaviour while just running some timing functions before and after. To do this, I call @nx/jest:jest executor's implementation from code.

When doing this, I see type errors when attempting to parse the `jest.config.ts` file for whichever test I attempt to run.

Is there maybe more steps that I should run before calling the `@nx/jest:jest` executor from code within my wrapper?

### Expected Behavior

That calling `@nx/jest:jest` via code in a wrapper executor behaves the same as calling `@nx/jest:jest` via `project.json`.

### GitHub Repo

https://github.com/blairmcalpine/NxMinimalRepro

### Steps to Reproduce

1. run `yarn`
2. run `npx nx test cart`, you will see an error regarding parsing the `jest.config.ts` file for `apps/cart`.
3. Perform the following change at `apps/cart/project.json:96` to revert the executor back to the default @nx version:
```diff
       "outputs": ["{options.outputFile}"]
     },
     "test": {
-      "executor": "@nx-example/jest:jest",
+      "executor": "@nx/jest:jest",
       "options": {
         "jestConfig": "apps/cart/jest.config.ts",
         "passWithNoTests": true
```
4. Run `npx nx test cart`, and the tests will pass.

### Nx Report

```shell
Node   : 16.20.2
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx                 : 16.10.0-beta.2
   @nx/js             : 16.10.0-beta.2
   @nx/jest           : 16.10.0-beta.2
   @nx/linter         : 16.10.0-beta.2
   @nx/workspace      : 16.10.0-beta.2
   @nx/angular        : 16.10.0-beta.2
   @nx/cypress        : 16.10.0-beta.2
   @nx/devkit         : 16.10.0-beta.2
   @nx/eslint-plugin  : 16.10.0-beta.2
   @nx/react          : 16.10.0-beta.2
   @nrwl/tao          : 16.10.0-beta.2
   @nx/web            : 16.10.0-beta.2
   @nx/webpack        : 16.10.0-beta.2
   nx-cloud           : 16.4.0
   typescript         : 5.1.3
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 16.0.0
   @ngrx/effects         : 16.0.0
   @ngrx/entity          : 16.0.0
   @ngrx/router-store    : 16.0.0
   @ngrx/store           : 16.0.0
   @ngrx/store-devtools  : 16.0.0
```

### Failure Logs

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

> nx run cart:test

>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Jest: Failed to parse the TypeScript config file /Users/blairmcalpine/Desktop/nx-examples/apps/cart/jest.config.ts

     TSError: ⨯ Unable to compile TypeScript:
   jest.config.ts:4:23 - error TS7006: Parameter 'args' implicitly has an 'any' type.
   
   4 const createConfig = (args) => ({
                           ~~~~
   
   Pass --verbose to see the stacktrace.


 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target test for project cart (931ms)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
When running a local plugin, Nx registers a transpiler to load TS in memory (in your case, this is ts-node). When running a plugin thats already compiled, the transpilers not registered yet. This could result in some edge cases as demonstrated above, but there's not a great solution path out of it. You'll need to fix the TS errors its reporting, or compile your plugin and point to dist most likely.

I know thats not optimal, but a real fix for this is less feasible than one may think at first.

**Comment by blairmcalpine** [comment]
For anyone else coming across this issue, it can be fixed by changing your jest config files to JS instead of TS. This isn't ideal of course but works as a fix nonetheless.
