### ISSUE TITLE
Error: "coverage.provider: c8" is not supported anymore. Use "coverage.provider: v8" instead

### ISSUE THREAD

**Issue by floratmin** [nrwl/nx#19486]
### Current Behavior

When updating vitest to version `0.34.0` and up with nx version `16.10.0` i get the following error:

```
Error: "coverage.provider: c8" is not supported anymore. Use "coverage.provider: v8" instead
```

### Expected Behavior

Tests should pass

### GitHub Repo

Easily reprocudable when setting up test workspace.

### Steps to Reproduce

1. `pnpm dlx create-nx-workspace reproduce --packageManager=pnpm --workspaceType=integrated --preset=ts`
2. `nx g @nx/js:lib testlib --directory util --bundler vite --importPath @studynaut/util-testlib --unitTestRunner vitest --projectNameAndRootFormat derived`
3. `nx run util-testlib:test` => runs fine
4. change version of vitest to `0.34.0` in `package.json` and run `pnpm i`
5. `nx run util-teslib:test` => throws error

### Nx Report

```shell
Node   : 20.7.0
   OS     : linux-x64
   pnpm   : 8.8.0
   
   nx (global)        : 16.9.1
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nrwl/tao          : 16.9.1
   @nx/vite           : 16.10.0
   typescript         : 5.1.6
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/tao@16.9.1
   
   To fix this, run `nx migrate nx@16.10.0`
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by floratmin** [comment]
I could resolve this issue with uninstalling the package `@vitest/coverage-c8`.

**Comment by sharky98** [comment]
I don't think this should be closed. I am using Nx 17.0.1 and according to #18114 #17886, `@vitest/coverage-v8` should be the default. However, generator that uses `vitest` as the unit test runner (such as @nx/js and @nx/react) always try to install `@vitest/coverage-c8` instead.

**Comment by sharky98** [comment]
I have added this to `nx.json`.
```json
"generators": {
  "@nx/vite": {
    "vitest": {
      "coverageProvider": "v8"
    }
  }
}
```

`package.json` already have this:
```json
"@vitest/coverage-v8": "^0.34.6",
```

And running the `@nx/js:library` still install c8.
```shell
> nx g @nx/js:library --name "nx-js" --directory "sandbox/libs/nx-js"

>  NX  Generating @nx/js:library

CREATE sandbox/libs/nx-js/tsconfig.json
CREATE sandbox/libs/nx-js/src/index.ts
CREATE sandbox/libs/nx-js/src/lib/nx-js.spec.ts
CREATE sandbox/libs/nx-js/src/lib/nx-js.ts
CREATE sandbox/libs/nx-js/tsconfig.lib.json
CREATE sandbox/libs/nx-js/project.json
CREATE sandbox/libs/nx-js/.eslintrc.json
CREATE sandbox/libs/nx-js/vite.config.ts
CREATE sandbox/libs/nx-js/tsconfig.spec.json
UPDATE package.json
UPDATE tsconfig.base.json
 WARN  deprecated @vitest/coverage-c8@0.32.4: v8 coverage is moved to @vitest/coverage-v8 package
Packages: +6
++++++
Progress: resolved 1343, reused 1282, downloaded 0, added 6, done

devDependencies:
+ @vitest/coverage-c8 0.32.4 (0.33.0 is available) deprecated

Done in 17.4s
```

```
 >  NX   Report complete - copy this into the issue template

   Node   : 20.8.1
   OS     : win32-x64
   pnpm   : 8.9.2

   nx (global)        : 17.0.1
   nx                 : 17.0.1
   @nx/js             : 17.0.1
   @nx/eslint         : 17.0.1
   @nx/workspace      : 17.0.1
   @nx/cypress        : 17.0.1
   @nx/esbuild        : 17.0.1
   @nx/eslint-plugin  : 17.0.1
   @nx/react          : 17.0.1
   @nrwl/tao          : 17.0.1
   @nx/vite           : 17.0.1
   typescript         : 5.2.2
```

**Comment by Lonli-Lokli** [comment]
With my current workspace I did not have the new coverage package and tests with coverage enabled parameter were running forever
