### ISSUE TITLE
Outdated $schema URL in schema.json for Nx Plugin

### ISSUE THREAD

**Issue by NicoPowers** [nrwl/nx#19489]
### Current Behavior

Hi,

I am using the `nx g @nx/plugin:generator <name>` to create a plugin, and the `schema.json` file references an outdated URL for the `"$schema"` definition:
`"$schema": "http://json-schema.org/schema"`

This leads to the following warning:
```
Unable to load schema from 'http://json-schema.org/schema': Not Found. The requested location could not be found.
<!DOCTYPE html><html lang="en"><head><meta name="viewport" content="width=device-width"/><meta charSet="utf-8"/><title>404: This page could not be found</title><meta name="next-head-count" content="3".(768)
```

That link, http://json-schema.org/schema, is no longer hosted, so perhaps a specific draft / version needs to be referenced.

### Expected Behavior

No warning for `"$schema": "http://json-schema.org/schema"`; it should point to a valid URL or file that exists.

### Steps to Reproduce

1. Perform `nx g @nx/plugin:generator my-plugin`
2. Navigate to src/generators/schema.json
3. Observe defintion `"$schema": "http://json-schema.org/schema"`

### Nx Report

```shell
Node   : 20.8.0
   OS     : linux-x64
   npm    : 10.1.0
   
   nx (global)        : 16.9.1
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/plugin         : 16.10.0
   @nrwl/tao          : 16.10.0
   nx-cloud           : 16.4.0
   typescript         : 5.1.6
   ---------------------------------------
   Local workspace plugins:
         my-plugin
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by clemenscodes** [comment]
Solving this for now by manually setting ` "$schema": "http://json-schema.org/draft-07/schema#"` in all the `schema.json` files.
