### ISSUE TITLE
Use Cypress for API testing

### ISSUE THREAD

**Issue by jogelin** [nrwl/nx#1949]
## Expected Behavior

I would like to add to my Nx workspace a Cypress app used to test only APIs. It is not related to any UI app.

## Current Behavior

It seems impossible to have only a simple cypress app no linked to a frontend app.

I generate a new frontend app to be able to get the e2e app. Then I deleted the `angular.json`  configurations related to the frontend app.

## Failure Information (for bugs)

After removing the `angular.json` configurations related to an UI app, it seems to work but when I tried to use the `affected:apps` scripts, I got `Cannot read property 'name' of undefined`

After some investigations, I see within the scripts that by default, an e2e app get an implicit dependency to a frontend app by just removing the prefix `-e2e`...so it fails because the frontend app doesn't exists.

**Comment by jogelin** [comment]
My Solution is to rename my app and don't use `-e2e` at the end.

Strange that the name of a project as an impact on the way it is managed...

**Comment by jaysoo** [comment]
@jogelin You're right, the `-e2e` name currently has special meaning in Nx. We'll look into improving this experience.

For now, you can also specify an `implicitDependencies` entry in your `nx.json` file, which should contain the name of the app(s) that being tested by Cypress.

Does that help?

**Comment by jogelin** [comment]
@jaysoo thx for the reply. However, I am creating a Cypress e2e because I want to test an external API, out of my monorepo !

**Comment by FrozenPandaz** [comment]
This is related to https://github.com/nrwl/nx/issues/1182

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by hadrien-toma** [comment]
On my side I have nearly the same need: I would like to test the Swagger page generated by a `@nrwl/nest` back-end app.

**Comment by hadrien-toma** [comment]
I am still very interested in this feature 😇

**Comment by krcourville** [comment]
similar to @hadrien-toma , I am looking to independently generate some cypress-based e2e tests for api's.  For the moment, I will try generating using the nrwl/node:application generator to generate an empty app and see if I can get it working from there by referencing what is created by an angular app generator.
