### ISSUE TITLE
Creating MFE 

### ISSUE THREAD

**Issue by assetkad** [nrwl/nx#19496]
### Current Behavior

when i write something like this:
npx nx g @nrwl/angular:app dashboard --mfe --mfeType=host --port=4200 --routing=true --style=scss --inlineTemplate=true --inlineStyle=true
it shows in console:
'mfe' is not found in schema

### Expected Behavior

after wrote i expect that it'll create host application

### Steps to Reproduce

1. npx create-nx-workspace mfe-demo
2. npm i -D @nrwl/angular
3. npx nx g @nrwl/angular:app dashboard --mfe --mfeType=host --port=4200 --routing=true --style=scss --inlineTemplate=true --inlineStyle=true

### Nx Report

```shell
NX  Generating @nrwl/angular:application
 Which E2E test runner would you like to use? · none
 NX   'mfe' is not found in schema
```

### Failure Logs

```shell
>  NX   'mfe' is not found in schema
```

### Package Manager Version

npm 9.7.1

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
The `mfe` option was removed quite some time ago from the `application` generator after being deprecated for a while: https://github.com/nrwl/nx/pull/9821. The error you're getting is correctly telling you that you're providing an option that doesn't exist. I'm unsure of the Nx version you're using (the `nx report` was not provided) but it's most likely a version after that change occurred.

If you want to generate a Module Federation Host application, please use the dedicated [`@nx/angular:host` generator](https://nx.dev/nx-api/angular/generators/host) instead.
