### ISSUE TITLE
x-electron not working

### ISSUE THREAD

**Issue by dgesteves** [nrwl/nx#19490]
### Current Behavior

I am currently creating a new frontend architecture for my company where I want to have a next.js (or simple react) app and an Electron app, I already tried the nx-electron plugin but it is not working. Can someone help me to set up this workspace?
My company is waiting for this reply can I have someone help me with this issue, please? 

### Expected Behavior

Be able to generate an electron app on my workspace.

### GitHub Repo

https://github.com/bennymeg/nx-electron#readme

### Steps to Reproduce

I tried the NX electron app and was not successful either. I just added the electron builder scripts into the package json for the app. The app is within an integrated repo, but I put everything necessary for electron builder inside of the app folder. 

Also of note, I could absolutely not get relative paths working with electron builder.

### Nx Report

```shell
N/A
```

### Failure Logs

```shell
N/A
```

### Package Manager Version

NPM v9.8.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Hey 👋, nx-electron is a community plugin. If you are having issues with it, you should ask on their repo.
