### ISSUE TITLE
React Module Federation: Unable to handle individual MFE retrieval failures in the host MFE

### ISSUE THREAD

**Issue by elliottdaviess** [nrwl/nx#19491]
### Current Behavior

If I generate a host and a remote with Nx React plugin and start the host without starting the remote, the host fails to render entirely. It doesn't matter if the lazy-loaded remote is within an ErrorBoundary. 

I'm a little confused by the double remoteEntry requests per remote MFE too - 

the sequence seems to be, e.g;

http://[localhost:2003/remoteEntry.js](http://localhost:2003/remoteEntry.js) when the host is mounted, then;

http://[localhost:2003/src_remote-entry_ts.js](http://localhost:2003/src_remote-entry_ts.js) when the remote is mounted. 

I can handle the latter with something like;

```
export const remotes: Remote[] = [
  {
    navLink: {
      text: 'test',
      path: '/test-mfe',
    },
    lazy: lazy(() =>
      import('test-mfe/Module').catch((error) => {
        console.error('Loading failed', error);
        return { default: () => <div>Error loading module</div> };
      })
    ),
  },
];
```
but I'm not able to handle the failed request for the remoteEntry.js file (the first call).

### Expected Behavior

For the host to continue functioning, and the ability to .catch() the lazy load error and substitute the module with an error component

### Steps to Reproduce

npx create-nx-workspace --preset=react
npx nx generate @nx/react:host host --remotes=remote

(serve host)

### Nx Report

```shell
Node   : 18.16.0
   OS     : darwin-arm64
   pnpm   : 7.31.0-0
   
   nx (global)             : 16.5.0
   nx                      : 16.9.0
   @nx/js                  : 16.9.0
   @nx/jest                : 16.9.0
   @nx/linter              : 16.9.0
   @nx/workspace           : 16.9.0
   @nrwl/workspace         : 16.5.5
   @nx/devkit              : 16.5.5
   @nx/eslint-plugin       : 16.9.0
   @nrwl/eslint-plugin-nx  : 16.9.1
   @nx/nest                : 16.9.0
   @nx/node                : 16.9.0
   @nx/react               : 16.9.0
   @nrwl/tao               : 16.5.5
   @nx/web                 : 16.9.0
   @nx/webpack             : 16.9.0
   typescript              : 5.1.6
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/workspace@16.5.5
     - @nx/devkit@16.5.5
     - @nrwl/devkit@16.5.5
     - @nrwl/eslint-plugin-nx@16.9.1
     - @nrwl/tao@16.5.5
   
   To fix this, run `nx migrate nx@16.9.1`
```

### Failure Logs

```shell
GET http://localhost:2003/remoteEntry.js net::ERR_CONNECTION_REFUSED
```

### Package Manager Version

pnpm

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
@elliottdaviess i can not replicate this issue. do you still have this issue if you disable the cache or run in incognito mode?

**Comment by ndcunningham** [comment]
@elliottdaviess I am not sure if that would be the correct way to handle remotes being unavailable.
The problem is that for offline remotes imported _statically_ the error happens outside of React so you would not be able to catch it.
You can test this by adding logs to your `bootstrap.tsx` file. It should not be called at all because webpack is loading the modules upfront.

In order to handle the remotes being unavailable when you would have to load via a promise or script tag.

**Comment by elliottdaviess** [comment]
Just FYI for anyone who comes across this issue in future, Nick has kindly added React dynamic module federation support to Nx with https://github.com/nrwl/nx/pull/20024 - thanks!
