### ISSUE TITLE
Fix: Twitter to X logo

### ISSUE THREAD

**Issue by Ayushpanditmoto** [nrwl/nx#19514]
![Screenshot_1](https://github.com/nrwl/nx/assets/31253617/3d5f6ff7-3f75-4ab5-95eb-6945980a0ae5)
Assign me this task

**Comment by ParthMakode** [comment]
is this done?

**Comment by AgentEnder** [comment]
Not currently - the issue will be closed by whatever PR fixes it.

**Comment by mandarini** [comment]
@Ayushpanditmoto would you like to work on this? You can pick the new logo from here: https://simpleicons.org/

**Comment by Ayushpanditmoto** [comment]
@mandarini  yeah sure i want to work on this issues

**Comment by Ayushpanditmoto** [comment]
@mandarini  i would like to assign this task to Sushmita

**Comment by Ayushpanditmoto** [comment]
@mandarini  can you check the pr i think she has done the changes

**Comment by tsopeh** [comment]
The official [X (Twitter) account](https://twitter.com/NXdevtools) is gone 😕. What's going on?

<details>
  <summary>Screenshot</summary>
  
![image](https://github.com/nrwl/nx/assets/37545996/5c32cdba-7b09-4f70-b775-e2e3c1bf76a5)
  
</details>

**Comment by mandarini** [comment]
Closing this PR since the logo has been fixed.

@tsopeh it was done accidentally. we're working on putting it back
