### ISSUE TITLE
NX 16.10 - Unable to load tsconfig-paths, workspace libraries may be inaccessible.

### ISSUE THREAD

**Issue by rzzo** [nrwl/nx#19518]
### Current Behavior

Just updated to latest  16.10.0 from 16.6.0. Now when running server I get "Unable to load tsconfig-paths, workspace libraries may be inaccessible."

### Expected Behavior

I expect no errors or warnings, and to have NX able to access all workspaces.

### Steps to Reproduce

1. Update to latest from 16.6.0
2. Serve the project

### Nx Report

```shell
Node   : 18.16.0
   OS     : darwin-arm64
   npm    : 9.5.1

   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/angular        : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/web            : 16.10.0
   @nx/webpack        : 16.10.0
   typescript         : 5.1.6
```

### Failure Logs

```shell
nx run crimson:serve

> nx run crimson:serve:development

⠋ Generating browser application bundles (phase: setup)...>  NX  Unable to load tsconfig-paths, workspace libraries may be inaccessible.
  - To fix this, install tsconfig-paths with npm/yarn/pnpm
✔ Browser application bundle generation complete.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I have installed tsconfig-paths, and I have also tried installing the webpack version. I am using webpack.config for env vars.

**Comment by rzzo** [comment]
One other thing to note I also had this warning:
"Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed"
  
  Installing those 2 did fix this from showing

**Comment by MohZaibAli** [comment]
Facing same issue.
![image](https://github.com/nrwl/nx/assets/68590303/9db21836-ff96-49da-acf6-719105703123)

**Comment by minijusl** [comment]
On CI this error/warning resulted in task execution failure, while locally it was only the error and execution continued further.
Had to do revert to @nx/* v16.9.0 for now to avoid this behaviour.

**Comment by AgentEnder** [comment]
Hey, this should be fixed in the v17 betas. I'm going to close this out. If you still experience the issue with v17 or its latest beta, feel free to open a new issue so it can be rechecked.

**Comment by rbirkgit** [comment]
I still get these warnings with 17.0 (official release)

```
Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed
```

**Comment by AgentEnder** [comment]
Do you have @swc-node/register or @swc/core installed? If not, that's expected when reading configuration files written with typescript.

**Comment by rbirkgit** [comment]
I am confused. I didn't get the warnings with 16.9. Didn't change anything else.

**Comment by AgentEnder** [comment]
In between 16.9 and 17 there were some updates with how typescript config files are read in
