### ISSUE TITLE
How to pass [target-name] or [configuration-name] to .env files correctly.

### ISSUE THREAD

**Issue by fasani-tx** [nrwl/nx#19522]
### Documentation issue
- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/recipes/tips-n-tricks/define-environment-variables

### Additional context or description

It is not clear to me where to inject [target-name] or [configuration-name] during development mode.

More specific details here (if needed):
https://github.com/nrwl/nx/discussions/19497

**Comment by AgentEnder** [comment]
`[target-name]` and `[configuration-name]` are placeholders for where Nx is looking. e.g.

If you run `nx run my-app:build`, and its default configuration is production, `.env.build`, `.env.production`, and `.env.build.production` should be loaded
