### ISSUE TITLE
Build broke

### ISSUE THREAD

**Issue by nata-atoshvili** [nrwl/nx#19528]
### Current Behavior

TypeError: tasksRunner(...).subscribe is not a function

### Expected Behavior

Building goes well

### Steps to Reproduce

1.
nx build

### Nx Report

```shell

  Node : 18.17.1
  OS   : darwin arm64
  yarn : 1.22.19

  nx : 13.1.4
  @nrwl/angular : Not Found
  @nrwl/cli : 13.1.4
  @nrwl/cypress : 13.1.4
  @nrwl/devkit : 13.1.4
  @nrwl/eslint-plugin-nx : 13.1.4
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.4
  @nrwl/linter : 13.1.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : 16.4.0
  @nrwl/react : 13.1.4
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.4
  @nrwl/web : 13.1.4
  @nrwl/workspace : 13.1.4
  @nrwl/storybook : 13.1.4
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by nata-atoshvili** [comment]
nx report
  Node : 18.17.1
  OS   : darwin arm64
  yarn : 1.22.19

  nx : 13.1.4
  @nrwl/angular : Not Found
  @nrwl/cli : 13.1.4
  @nrwl/cypress : 13.1.4
  @nrwl/devkit : 13.1.4
  @nrwl/eslint-plugin-nx : 13.1.4
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.4
  @nrwl/linter : 13.1.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : 16.4.0
  @nrwl/react : 13.1.4
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.4
  @nrwl/web : 13.1.4
  @nrwl/workspace : 13.1.4
  @nrwl/storybook : 13.1.4
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by FrozenPandaz** [comment]
Sorry, there's not enough information to help you here. Could you please try with the latest version of Nx?
