### ISSUE TITLE
External dependencies missing in projectGraph on Windows

### ISSUE THREAD

**Issue by JonWallsten** [nrwl/nx#19520]
### Current Behavior

I'm currently investigating why module federation is broken in nx >= 16.8.1, https://github.com/nrwl/nx/issues/19121.
The root cause is that `externalModules` are missing in the `projectGraph`, so host/remote cannot share dependencies.

After a lot of digging it seems like the reason is that the `WorkspaceContext` is missing `externalModules`.
In nx@16.2.2 the external modules are added to the project graph by calling `buildNpmPackageNodes`.
In nx@16.8.1 something called `getNxWorkspaceFilesFromContext` is used instead. It's using a `WorkspaceContext` to retrieve the `externalModules`, but it's always empty.

Since `WorkspaceContext` is created by a binary I'm not sure if I can investigate this further.
But since this is only an issue on Windows and this is a native module I guess that it's not that far fetched that it could be the source of the issue. 

```
projectGraph {
  nodes: {
    remote: { name: 'remote', type: 'app', data: [Object] },
    host: { name: 'host', type: 'app', data: [Object] }
  },
  externalNodes: {},
  dependencies: { remote: [], host: [] },
  version: '6.0'
}
```

### Expected Behavior

WorkspaceContext should add npm dependencies as `externalModules` so it can be added to the `projectGraph`

### GitHub Repo

https://github.com/JonWallsten/nx-repro/tree/dynamic

### Steps to Reproduce

1. npm i
2. npm run build

### Nx Report

```shell
Node   : 18.14.1
   OS     : win32-x64
   npm    : 9.3.1

   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/angular        : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/web            : 16.10.0
   @nx/webpack        : 16.10.0
   typescript         : 5.1.6
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by mrehman7095** [comment]
can explicitly sharing dependencies such as 

`shared: (libraryName, config) => {
    if (libraryName.startsWith('@angular/animations')) {
      return {
        ...config,
        requiredVersion: '16.2.10',
        singleton: true,
        strictVersion: true,
      };
    }
    if (libraryName.startsWith('@angular/cdk')) {
      return {
        ...config,
        requiredVersion: '16.2.9',
        singleton: true,
        strictVersion: true,
      };
    }
---------
`
can this be work around for this issue on nx 17 ?

**Comment by JonWallsten** [comment]
@AgentEnder Is there anything I can do to help with this?

**Comment by JonWallsten** [comment]
Just updated to nx@17.x.x and this is still an issue.

**Comment by JonWallsten** [comment]
Finally figured out how to use `--inspect-brk` on the child process that creates the graph. So now I at least have a chance to figure this out:
![image](https://github.com/nrwl/nx/assets/5993909/072e07ee-84c9-40bf-a3a4-60e43d30e681)
I'm trying to find out why the `externalNodes` is always empty. I think that's the key. Any help appreciated.

**Comment by JonWallsten** [comment]
Okey, I finally found the issue! 🥳
I tried to find all the places where `externalNodes` are affected somehow. And found this `getNodes` function in `npm-parser.ts` (we're using npm). 
It takes `data: NpmLockFile` as input. But I'm not using a lock-file.
So added `package-lock=true` to the `.npmrc` and built again, but it still didn't work.
I remember seeing `.gitignore` somewhere when I debugged.
So I removed `package-lock.json` from `.gitignore` and finally it worked.

But since I now have to push the `package-lock.json` to our repo, because it's no longer in the `.gitignore` file I can't get the build to work in Gitlab, because the lock file was prepared on windows.

I get this error: 
`Error: Cannot find module '@nx/nx-linux-x64-gnu'`

So I guess we have two issue here:
1. It should work without a `package-lock.json`
2. `package-lock.json` should not be ignored when building the graph
But if 1 is fixed, two is not necessary to fix.

@AgentEnder

**Comment by Cammisuli** [comment]
on the CI, can you try running `find node_modules -name "*.node" | grep -E "(@nx|@nrwl)"` and making sure that the linux binary shows up there?

For example, on my computer running the command on the nx repo, i get this result:
```
node_modules/.pnpm/@nrwl+nx-darwin-arm64@15.8.0/node_modules/@nrwl/nx-darwin-arm64/nx.darwin-arm64.node
node_modules/.pnpm/@nx+nx-darwin-arm64@17.1.1/node_modules/@nx/nx-darwin-arm64/nx.darwin-arm64.node
```

**Comment by Cammisuli** [comment]
Are the optional dependencies listed in the package-lock.json file? The fact that you can't find rollup's native binary either is suspicious of the package-lock. All the optional dependencies should be listed in the package-lock. For example this is how the nx ones look:
```
    "node_modules/@nx/nx-darwin-arm64": {
      "version": "17.2.2",
      "resolved": "http://localhost:4876/@nx%2fnx-darwin-arm64/-/nx-darwin-arm64-17.2.2.tgz",
      "integrity": "sha512-8dPPmX8KQT/HtizaDmz/+TIAytAwuC0Mvx/UqhiFNL5l0o5HnK+AfNEe2GWk9kfZjg22nmMfBIBDIxl6odNVBQ==",
      "cpu": [
        "arm64"
      ],
      "dev": true,
      "optional": true,
      "os": [
        "darwin"
      ],
      "engines": {
        "node": ">= 10"
      }
    },
    "node_modules/@nx/nx-darwin-x64": {
      "version": "17.2.2",
      "resolved": "http://localhost:4876/@nx%2fnx-darwin-x64/-/nx-darwin-x64-17.2.2.tgz",
      "integrity": "sha512-hJaqyF+wAdFznXv2WQ+qTkCX5+Dr4cCtA9M67/Rln70bUkiQ0upQAacI0BUrHLZOKAS6OKW2V37V1xgCLk+NHw==",
      "cpu": [
        "x64"
      ],
      "dev": true,
      "optional": true,
      "os": [
        "darwin"
      ],
      "engines": {
        "node": ">= 10"
      }
    },
    "node_modules/@nx/nx-freebsd-x64": {
      "version": "17.2.2",
      "resolved": "http://localhost:4876/@nx%2fnx-freebsd-x64/-/nx-freebsd-x64-17.2.2.tgz",
      "integrity": "sha512-CxbtqfL33MHqaEXKNjgrZCf9Sot13KmZvkbET/DOQGJVX6yD1kKV8yTN9KfoeUwf1UorCCyTy5NdyFKq0nkIOQ==",
      "cpu": [
        "x64"
      ],
      "dev": true,
      "optional": true,
      "os": [
        "freebsd"
      ],
      "engines": {
        "node": ">= 10"
      }
    },
    "node_modules/@nx/nx-linux-arm-gnueabihf": {
      "version": "17.2.2",
      "resolved": "http://localhost:4876/@nx%2fnx-linux-arm-gnueabihf/-/nx-linux-arm-gnueabihf-17.2.2.tgz",
      "integrity": "sha512-r5kAqC3c6kIXUfDK27zQ3LsZO/tsDzmiNilxc00DmUIzLPBLt3qlXbctD5jxE80xVkgNSCEZtSFIgTpYdymnAQ==",
      "cpu": [
        "arm"
      ],
      "dev": true,
      "optional": true,
      "os": [
        "linux"
      ],
      "engines": {
        "node": ">= 10"
      }
    },
    "node_modules/@nx/nx-linux-arm64-gnu": {
      "version": "17.2.2",
      "resolved": "http://localhost:4876/@nx%2fnx-linux-arm64-gnu/-/nx-linux-arm64-gnu-17.2.2.tgz",
      "integrity": "sha512-EowQSciBfUg82jwHruFhCnY6/raWoo8FsGPaTNaKPcXtckYCi1hj9XUgHpeG06Z5lgPvO/1pFIUSSkIc3vefQA==",
      "cpu": [
        "arm64"
      ],
      "dev": true,
      "optional": true,
      "os": [
        "linux"
      ],
      "engines": {
        "node": ">= 10"
      }
    },
    "node_modules/@nx/nx-linux-arm64-musl": {
      "version": "17.2.2",
      "resolved": "http://localhost:4876/@nx%2fnx-linux-arm64-musl/-/nx-linux-arm64-musl-17.2.2.tgz",
      "integrity": "sha512-MQgXf5u12EyCINLiuntjOE5sR2Vp4CjHMrXt8aT8ZRURUc6PBkubDjslVhVJ7Xmot38i5Fh/ngrdXzFrQETAUw==",
      "cpu": [
        "arm64"
      ],
      "dev": true,
      "optional": true,
      "os": [
        "linux"
      ],
      "engines": {
        "node": ">= 10"
      }
    },
    "node_modules/@nx/nx-linux-x64-gnu": {
      "version": "17.2.2",
      "resolved": "http://localhost:4876/@nx%2fnx-linux-x64-gnu/-/nx-linux-x64-gnu-17.2.2.tgz",
      "integrity": "sha512-qPB42G0xLlwbpC40r8RxgS+xsKoURpkBmcwhXSo+5iBnfOvW2qk4ox+0h+l+mTT8RB30H/7XNEEXergu2Px1Zw==",
      "cpu": [
        "x64"
      ],
      "dev": true,
      "optional": true,
      "os": [
        "linux"
      ],
      "engines": {
        "node": ">= 10"
      }
    },
    "node_modules/@nx/nx-linux-x64-musl": {
      "version": "17.2.2",
      "resolved": "http://localhost:4876/@nx%2fnx-linux-x64-musl/-/nx-linux-x64-musl-17.2.2.tgz",
      "integrity": "sha512-AnD7rtxyU6LIF0ewCO0gmvrQuJPSPZPXAzrUn95YP+nh357bfweOPV6uyHYn/Nqax1f3FPFe7Ervo48TAzunug==",
      "cpu": [
        "x64"
      ],
      "dev": true,
      "optional": true,
      "os": [
        "linux"
      ],
      "engines": {
        "node": ">= 10"
      }
    },
    "node_modules/@nx/nx-win32-arm64-msvc": {
      "version": "17.2.2",
      "resolved": "http://localhost:4876/@nx%2fnx-win32-arm64-msvc/-/nx-win32-arm64-msvc-17.2.2.tgz",
      "integrity": "sha512-xNvdlfGnTBx6FygCR+AenduVWATh4HtaNibFM7ELdsTM4posYFYk7jpNXf5dFtSANJ+Is2vWAEqjWx1Th0/ZjQ==",
      "cpu": [
        "arm64"
      ],
      "dev": true,
      "optional": true,
      "os": [
        "win32"
      ],
      "engines": {
        "node": ">= 10"
      }
    },
    "node_modules/@nx/nx-win32-x64-msvc": {
      "version": "17.2.2",
      "resolved": "http://localhost:4876/@nx%2fnx-win32-x64-msvc/-/nx-win32-x64-msvc-17.2.2.tgz",
      "integrity": "sha512-2pULDtVSGJUYiFKFJTASaOVpSF9AkjOvVgkRTV92Cx2ykT/9wwg7EfY/WZmLxfAkYFjiQyD9s4Wq06yp/rgd4w==",
      "cpu": [
        "x64"
      ],
      "dev": true,
      "optional": true,
      "os": [
        "win32"
      ],
      "engines": {
        "node": ">= 10"
      }
    },
```

Other package's optional native binaries should be around the same area too.

Did you try deleting node_modules + the package-lock and doing `npm i` again? Did you try updating your npm version?

**Comment by sagarbasavaraj** [comment]
I am having the same problem with npm but it worked with yarn package manager as we have yarn.lock file.

**Comment by gabynevada** [comment]
I switched our package manager to bun and having the same issue as it uses the bun/lockb file.

**Comment by matheo** [comment]
I'm using `pnpm` and I added `pnpm-lock.yaml` to `.nxignore` to prevent `nx format` issues but then my dep-graph was messed up without external dependencies :thinking:
