### ISSUE TITLE
Regression(cli@16.9/17) - executor no longer forwards args

### ISSUE THREAD

**Issue by raphael22** [nrwl/nx#19535]
### Current Behavior

nx/executor no longer forwards args.

@nx/16.8.0
```nx build -- --c=development``` -> ```nx run cart:build-app:development```
@nx/16.9.0 or @nx/16.10.0
```nx build -- --c=development``` -> ```nx run cart:build-app:production```

### Expected Behavior

nx/executor should forwards args

### GitHub Repo

https://github.com/raphael22/nx-examples-forwardsArgs-bug

### Steps to Reproduce

1. git clone https://github.com/raphael22/nx-examples-forwardsArgs-bug
2. git checkout nx/16.9.0 or nx/16.10.0
3. npm install
4. nx build -- --c=development
5. ```nx run cart:build-app:production``` is logged :/
6. git checkout nx/16.8.0
7. npm install
8.  nx build -- --c=development
9. ```nx run cart:build-app:development``` is logged :)

### Nx Report

```shell
 Node   : 18.17.0
 OS     : linux-x64
 npm    : 10.0.0

 nx (global)        : 16.6.0
 nx                 : 16.8.0
 @nx/js             : 16.8.0
 @nx/jest           : 16.8.0
 @nx/linter         : 16.8.0
 @nx/workspace      : 16.8.0
 @nx/angular        : 16.8.0
 @nx/cypress        : 16.8.0
 @nx/devkit         : 16.8.0
 @nx/eslint-plugin  : 16.8.0
 @nx/react          : 16.8.0
 @nrwl/tao          : 16.8.0
 @nx/web            : 16.8.0
 @nx/webpack        : 16.8.0
 nx-cloud           : 16.4.0
 typescript         : 5.1.3
 ---------------------------------------
 Community plugins:
 @ngrx/component-store : 16.0.0
 @ngrx/effects         : 16.0.0
 @ngrx/entity          : 16.0.0
 @ngrx/router-store    : 16.0.0
 @ngrx/store           : 16.0.0
 @ngrx/store-devtools  : 16.0.0
```

### Package Manager Version

10.0.0

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by raphael22** [comment]
reproduce with 17.1.1 :/

**Comment by AgentEnder** [comment]
Hey there - anything after `--` is treated as an arg for the underlying executor and not parsed by Nx. Sorry its taken so long to hear back on this.
