### ISSUE TITLE
Calling "affected" via nodejs ? (an api is available instead of a cli?)

### ISSUE THREAD

**Issue by iangregsondev** [nrwl/nx#1954]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

I have checked the docs and I don't think i missed it ? I am trying to use the affected commands but via nodejs for easy parsing. I basically want to get what applications have changed so I am able to send this to an external api.

It would be nice if this was possible via nodejs rather than using the cli ?

Otherwise, I would need to pipe the results to a file and then parse the file.

I was wondering if the above is available, if not, is there a possibility to output the info as a json, for easy parsing.

Actually, if the api is available then I could also control the output to a file in the format of my choosing.

All I need to do is get a list of affected applications and then I can use this / these values for a 3rd party integration that I am trying to work with.

Any ideas ?

Thanks in advance

**Comment by ZachJW34** [comment]
It is currently possible to get affected apps/libs via node. It looks like there was a more robust API in version 7 seen [here](https://github.com/nrwl/nx/blob/33d34233b5af9190b49cc10d62a73da177fade32/packages/schematics/src/command-line/shared.ts#L320), but we can get by using the `getAffectedMetadata` and `parseFiles` from [here](https://github.com/nrwl/nx/blob/master/packages/workspace/src/command-line/shared.ts).

Here is an example script:
```
const { getAffectedMetadata, parseFiles } = require('@nrwl/workspace/src/command-line/shared');
const { files } = parseFiles({ base: 'HEAD~1', head: 'HEAD' })
const affected = getAffectedMetadata(files);
console.log(affected);
```
Parsing the `angular.json` can be used to find what builders and commands need to be run to accomplish what you need.

**Comment by jaysoo** [comment]
We don't currently support a programmatic interface, but what @ZachJW34 outlined will work for the upcoming 8.7.0 release.

Otherwise if you're on an older 8.x release you can use the following.

```
const { getAffectedProjects, parseFiles } = require('@nrwl/workspace/src/command-line/shared');
const { files } = parseFiles({ base: 'HEAD~1', head: 'HEAD' })
const affected = getAffectedProjects(files);
console.log(affected);
```
Replace `HEAD` and `HEAD~1` with the actual base and head you're comparing.

**Comment by jaysoo** [comment]
Closing this issue since there are examples provided that should be sufficient.

**Comment by vitorcamachoo** [comment]
Hi,
How can I get the affected apps on the latest version (11.X) ?

**Comment by mac2000** [comment]
For anyone landing here, it seems that at moment it is possible with something like:

```js
const { createProjectGraph, ProjectType } = require('@nrwl/workspace/src/core/project-graph')
const { filterAffected } = require('@nrwl/workspace/src/core/affected-project-graph')
const { parseFiles } = require('@nrwl/workspace/src/command-line/shared')
const { calculateFileChanges } = require('@nrwl/workspace/src/core/file-utils')

const args = {base: 'master'} // {base: 'HEAD~1', head: 'HEAD'}
const affectedGraph = filterAffected(createProjectGraph(), calculateFileChanges(parseFiles(args).files)).nodes
const affectedApps = Object.keys(affectedGraph).filter(k => affectedGraph[k].type === ProjectType.app)
console.log(affectedApps) // ['app1', 'app2', ..., 'appN']
```

which will give you an array of affected applications, code is taken from [affected.ts](https://github.com/nrwl/nx/blob/master/packages/workspace/src/command-line/affected.ts#L21)

**Comment by DzmVasileusky** [comment]
@mac2000 not working in nx 15.*
I wonder if there is a reliable nx API
