### ISSUE TITLE
nx build doesn't use previous build steps

### ISSUE THREAD

**Issue by mhamri** [nrwl/nx#19559]
### Current Behavior

I'm reopening #19404 since I believe unfortunately @AgentEnder didn't spend time and closed the issue without understanding the main problem (Irony of his username)

the issue is the build results, not angular (against @AgentEnder  understanding) 

builds are not using previous build step result. having a rollup next to vite next to esbuild means nothing in nx mono repo. main question is

- what exactly nx is caching if each of the build steps are not using the previous build result?

because if it's not for the sake of caching and build-once-use-many, using npm's workspace would be more wise.

I have created a repository that shows when the target build is a vite project or rollup project or an esbuild project. previous build step isn't used in the next build step.

to be clear that "the issue isn't about angular" I've removed the angular application from the repository!

### Expected Behavior

build once, use multiple times. each build step should use previous build result. helps to decrease build effort and memory usage.

### GitHub Repo

https://github.com/mhamri/Bundling-Issues-in-Nx

### Steps to Reproduce

1. create an empty nx project
2. create a rollup project using @nx/js 
3. add a plugin to rollup project to replace text during the build
> in rollup project we have \_\_IsRollup\_\_ and 
![image](https://github.com/nrwl/nx/assets/8991783/4c6da246-315e-4ea3-a082-133f18a51c22)

>we set a plugin to replace the text 
![image](https://github.com/nrwl/nx/assets/8991783/f3c60667-9ebd-49f3-952f-cd7364e1845c)

4. create a vite Project using @nx/js
5. add a plugin to vite project to replace text during the build

> in vite project we use rollup() 
![image](https://github.com/nrwl/nx/assets/8991783/770d7484-1859-4d7b-b276-be91285d9b96)

> configure the vite plugin to replace __IsVite__
![image](https://github.com/nrwl/nx/assets/8991783/bf93e34f-203f-4bab-8207-645c5a28679a)

6. repeat the same thing with different type of project (in repo I created esbuild too)
7. build vite project 
8. visit the dist folder and see if all the text in both project is replaced or not 
![image](https://github.com/nrwl/nx/assets/8991783/de345b30-b154-4d8b-9a15-a75aa346f240)

__by here you can stop, you already saw that build is broken but if you want to test more__

9. add a nodejs project with @nx/node
10. call viteToRollup()
![image](https://github.com/nrwl/nx/assets/8991783/e6387ae3-5514-4871-baab-7ae3bd20dc4a)

12. see output 
![image](https://github.com/nrwl/nx/assets/8991783/360f2e16-3267-4a31-96cd-196eec4072f8)

### Nx Report

```shell
Enumerating objects: 112, done.
Counting objects: 100% (112/112), done.
Delta compression using up to 8 threads
Compressing objects: 100% (97/97), done.
Writing objects: 100% (112/112), 291.45 KiB | 7.88 MiB/s, done.
Total 112 (delta 22), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (22/22), done.
To https://github.com/mhamri/Bundling-Issues-in-Nx.git
 * [new branch]      main -> main
branch 'main' set up to track 'origin/main'.
PS C:\repo\toDelete\ngrx-nx-workshop\test-lib-connection\dist\apps\is-angular> nx report
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 16.20.0
   OS     : win32-x64
   npm    : 8.19.4

   nx (global)        : 16.9.1
   nx                 : 16.9.1
   @nx/js             : 16.9.1
   @nx/jest           : 16.9.1
   @nx/linter         : 16.9.1
   @nx/workspace      : 16.9.1
   @nx/angular        : 16.9.1
   @nx/esbuild        : 16.9.1
   @nx/eslint-plugin  : 16.9.1
   @nx/rollup         : 16.9.1
   @nx/vite           : 16.9.1
   typescript         : 5.1.6
```

### Package Manager Version

pnpm 8.9.0

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Hey @mhamri, sorry if I was not clear before. The tutorial I linked may have been geared towards angular, but the concepts it goes over **_are_** related to what you are seeing. Most of our bundler executors default to building the library code from source, for a variety of reasons which other people would be more versed to explain.

Regardless, if you do not wish for the bundler to build the library from source, and would rather it build from dist which can make sense in some use cases, most of our executors accept an option `buildLibsFromSource`. This is what I was referring to as the angular tutorial covers it.

See:
- https://nx.dev/nx-api/vite/executors/build#buildlibsfromsource
- https://nx.dev/nx-api/webpack/executors/webpack#buildlibsfromsource
- https://nx.dev/nx-api/next/executors/build#buildlibsfromsource

It doesn't look like those options are currently supported for esbuild and rollup, if you need to consume libraries from dist and a parent project is using either of those you should open a feature request to support it. Either way, the consuming app in your repo does use vite, which supports the option, so passing it should resolve the issue you are describing.

**Comment by mhamri** [comment]
@AgentEnder is it possible to not close the issue until we have a clear resolution? 

I've tried what you've suggested and it didn't work 

1- added another vite project with `@nx/js`
2- added the plugin to replace the text `__IsVite2__` in the second project
![image](https://github.com/nrwl/nx/assets/8991783/035becdf-f631-4849-95d8-401148e135af)

3- use the first vite project inside the second project 
![image](https://github.com/nrwl/nx/assets/8991783/d363d3d0-22c6-4daa-99e4-6374f5efc82a)
4- set build from source in both vite project to false 
>vite 
![image](https://github.com/nrwl/nx/assets/8991783/e983bcb8-67a2-45b3-b33f-3a23622fcd87)

>vite 2 
![image](https://github.com/nrwl/nx/assets/8991783/f50986a7-1291-484b-87b0-c3e59ab3f59d)

5- make build files and as you can see, previous build steps isn't used 
![image](https://github.com/nrwl/nx/assets/8991783/73d86407-f06f-49c5-978b-417d13bf6649)

6- tried it with node. changed the node app to use vite2
![image](https://github.com/nrwl/nx/assets/8991783/7976c663-b763-4576-8d97-4af840a168d9)

7- serve the node and only for the first level lib the plugin is applied
![image](https://github.com/nrwl/nx/assets/8991783/c76ef8d7-328a-47bb-b1ac-54ab03eb631f)

8- build node app and for both lib the build is didn't applied
![image](https://github.com/nrwl/nx/assets/8991783/fc99ce0b-9173-4cb2-9369-f7f547d09e4a)

![image](https://github.com/nrwl/nx/assets/8991783/614c4a59-fcc5-4a12-be7b-f61b0f316e65)

**Comment by mhamri** [comment]
@AgentEnder still I'm waiting for your response
