### ISSUE TITLE
@nx/react-native:start omitts metro's bundling progress bar

### ISSUE THREAD

**Issue by meckanism** [nrwl/nx#19556]
### Current Behavior

The  @nx/react-native:start executor is omitting metro's bundling progress bar. We can still _sometimes_ see the bundling progress through the simulator but this seems to be inconsistent. Given how much time this loading usually takes on large react-native projects, not seeing this progress bar on the console makes it look like nothing is happening.

![Screenshot 2023-10-11 at 09 39 25](https://github.com/nrwl/nx/assets/1633430/dc56e98d-f2ca-4f2a-8410-60177cd3b7b3)

### Expected Behavior

@nx/react-native:start executor should display metro's bundling progress bar.
I ran metro directly from node_modules through `node_modules/.bin/react-native start` or even from `node_modules/react-native/cli.js start`

![screen](https://github.com/nrwl/nx/assets/1633430/c2df6005-b223-4d61-9512-44fcf42d1899)

### Steps to Reproduce

1. run the @nx/react-native:start executor.
2. run an application that attaches to metro.
3. notice the metro bundling progress bar does not show up.

### Nx Report

```shell
Node   : 19.7.0
   OS     : darwin-x64
   npm    : 9.5.0

   nx (global)        : 16.8.1
   nx                 : 16.8.1
   @nx/js             : 16.8.1
   @nx/jest           : 16.8.1
   @nx/linter         : 16.8.1
   @nx/workspace      : 16.8.1
   @nx/detox          : 16.8.1
   @nx/devkit         : 16.8.1
   @nx/eslint-plugin  : 16.8.1
   @nx/react          : 16.8.1
   @nx/react-native   : 16.8.1
   @nrwl/tao          : 16.8.1
   @nx/web            : 16.8.1
   nx-cloud           : 16.0.5
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I do not have the time to do a repro (sorry), however, a quick hack directly on node_modules made me possibly find the source of the problem. It seems to have been introduced in this commit 699a20ca03236676a7923cc96e4766b7cedbe519

More specifically changes to the startAsync function when forking react-native/cli.js:

Changing `stdio: ['inherit', 'pipe', 'pipe', 'ipc'],` to `stdio: ['inherit', 'inherit', 'pipe', 'ipc']` on

https://github.com/nrwl/nx/commit/699a20ca03236676a7923cc96e4766b7cedbe519#diff-f530edcbb658f98c4df1448d9ca54b3a46b24206113c8016986f677e930e649cR78-R86

And removing `childProcess.stdout.on('data', ....` on

https://github.com/nrwl/nx/commit/699a20ca03236676a7923cc96e4766b7cedbe519#diff-f530edcbb658f98c4df1448d9ca54b3a46b24206113c8016986f677e930e649cR89-R94

metro output goes back to normal, showing the bundling progress bar.

It's safe to assume that run-ios and run-android that also run metro will have the same problem.

**Comment by xiongemi** [comment]
I can not simply change the stdout to inherit because I am currently listening to the output and i need to resolve the promise wraps around it as soon as the start command launches successfully:
```
    childProcess.stdout.on('data', (data) => {
      process.stdout.write(data);
      if (data.toString().includes('reload the app')) {
        resolve(childProcess);
      }
    });
```
i do not know a better way of solving this.
i am closing this issue for now.

**Comment by meckanism** [comment]
@xiongemi Thanks for trying.

**Comment by xiongemi** [comment]
it should be fixed in nx 18
