### ISSUE TITLE
nx-cloud v16.5.1 fails with "Cannot use 'in' operator to search for ..."

### ISSUE THREAD

**Issue by minijusl** [nrwl/nx#19554]
### Current Behavior

Using Nx Cloud (self-hosted enterprise version) and tonight got an nx-cloud (client) update that fails with following errors.
Nx Cloud deployed using Helm chart (https://github.com/nrwl/nx-cloud-helm) v0.11.5, images tag `2308.22.7.patch2`.

```
+ npx nx-cloud start-agent

/tmp/node_modules/nx-cloud/bin/nx-cloud.js:40
        if (command in lightClient.commands) {
                    ^

TypeError: Cannot use 'in' operator to search for 'start-agent' in undefined
    at /tmp/node_modules/nx-cloud/bin/nx-cloud.js:40:21
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/node_modules/nx-cloud/bin/nx-cloud.js:6:58)
```

```
+ npx nx-cloud record -- nx format:check
/tmp/node_modules/nx-cloud/bin/nx-cloud.js:40
        if (command in lightClient.commands) {
                    ^

TypeError: Cannot use 'in' operator to search for 'record' in undefined
    at /tmp/node_modules/nx-cloud/bin/nx-cloud.js:40:21
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/node_modules/nx-cloud/bin/nx-cloud.js:6:58)
```

### Expected Behavior

It should not fail.

### Steps to Reproduce

1. Update repo with latest nx-cloud version v16.5.1
2. Run any `nx-cloud` command.

### Nx Report

```shell

 >  NX   Report complete - copy this into the issue template

   Node   : 18.18.0
   OS     : darwin-arm64
   npm    : 10.2.0
   
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/angular        : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/nest           : 16.10.0
   @nx/node           : 16.10.0
   @nx/plugin         : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/web            : 16.10.0
   @nx/webpack        : 16.10.0
   nx-cloud           : 16.5.1
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @ngrx/effects        : 16.3.0
   @ngrx/entity         : 16.3.0
   @ngrx/eslint-plugin  : 16.3.0
   @ngrx/router-store   : 16.3.0
   @ngrx/schematics     : 16.3.0
   @ngrx/store          : 16.3.0
   @ngrx/store-devtools : 16.3.0
   ---------------------------------------
   Local workspace plugins:
```

### Operating System

- [X] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by StalkAltan** [comment]
Hi @minijusl,

This is our bad, there is a partial implementation of an unreleased-to-enterprise feature in your images.

There are two things you can do here:
1) Downgrade your `nx-cloud` package to `16.4.0`, or
2) Add `useLightClient: false` to your nx.json under your `accessToken`.

We will cut a patch to this image to remove the in progress work, and it will be available in the next official enterprise release. Sorry for the inconvenience.

**Comment by minijusl** [comment]
I have upgraded Nx Cloud to `2308.22.7.patch3` and now `nx-cloud@16.5.2` provides are warning message (which I guess could be removed by setting `useLightClient: false`.

```
[WARNING] Nx Cloud was unable to fetch or verify its bundle from the instance hosted at:  ___redacted___
[WARNING] Nx Cloud will continue to function as expected, but your installation should be updated
[WARNING] soon for the best experience.
[WARNING] 
[WARNING] If you are an Nx Enterprise customer, please reach out to your assigned Developer Productivity Engineer.
[WARNING] 
[WARNING] If you are NOT an Nx Enterprise customer but are seeing this message, please reach out to cloud-support@nrwl.io.
[WARNING] 
[WARNING] To prevent this check on startup, set `useLightClient: false` in your task runner options found in `nx.json`.
```

However, the CI run itself fails with errors that are not there with `nx-cloud@16.4.0`:
```
>  NX   Unable to complete a run.

Main job terminated with an error: "Run group 'PR-30930_7' is completed"

Error: Main job terminated with an error: "Run group 'PR-30930_7' is completed"
   at DistributedExecutionApi.<anonymous> (/tmp/node_modules/nx-cloud/lib/core/runners/distributed-execution/distributed-execution.api.js:1:3683)
   at Generator.next (<anonymous>)
   at _0x594443 (/tmp/node_modules/nx-cloud/lib/core/runners/distributed-execution/distributed-execution.api.js:1:1647)
   at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

p.s. what is `lightClient`? There is no documentation yet on nx.dev about this option.

**Comment by StalkAltan** [comment]
Hi @minijusl 

The “run group completed” error is normally related to not selecting “re-run all jobs” on your pipeline. Please get in touch with your internal contact if this keeps happening and it will be easier for us to take a look.

The light client is a version of the task runner that is tightly coupled to a specific enterprise image to provide the best possible compatibility. It allows us to iterate and make sure the API and task runner are always correctly in sync. It’s mostly an implementation detail.
