### ISSUE TITLE
Nx Cloud Runners Constantly Getting SIGTERM Cancellation

### ISSUE THREAD

**Issue by JackLazenbyZigzag** [nrwl/nx#19558]
### Current Behavior

We have three Nx Cloud Runners in our CI/CD setup in Azure Pipelines. Since upgrading to the latest version of Nx (16, regardless of sub version), our runners are consistently failing when doing larger builds with Agent exited with the error: Agent was terminated via SIGTERM.

We do not host our own agents, they are the Microsoft provided ones. 

Our Nx commands, as far as I'm aware (following checks with Nx directly) are best practice and this issue has only started occuring since upgrading to the latest version of Nx from version 14 (where we had no issues). 

Here are the Nx packages we are using.

```
"@nx/cypress": "16.10.0",
        "@nx/eslint-plugin": "16.10.0",
        "@nx/jest": "16.10.0",
        "@nx/linter": "16.10.0",
        "@nx/nest": "16.10.0",
        "@nx/node": "16.10.0",
        "@nx/webpack": "^16.10",
        "@nx/workspace": "16.10.0",
        "@nxext/capacitor": "16.7.0",
        "@nxext/ionic-angular": "16.2.0",
"nx": "16.9.1",
        "nx-cloud": "16.4.0",

"optionalDependencies": {
        "@nx/nx-darwin-arm64": "16.5.1",
        "@nx/nx-darwin-x64": "16.5.1",
        "@nx/nx-linux-x64-gnu": "16.5.1",
        "@nx/nx-win32-x64-msvc": "16.5.1"
    }
```

### Expected Behavior

The Nx Runners should not be shut down by SIGTERM.

### Steps to Reproduce

1.

### Nx Report

```shell
Report complete - copy this into the issue template

   Node   : 18.17.1
   OS     : darwin-arm64
   npm    : 9.6.7
   
   nx                 : 16.10.0
   @nx/js             : 16.9.1
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/angular        : 16.9.1
   @nx/cypress        : 16.10.0
   @nx/devkit         : 16.9.1
   @nx/eslint-plugin  : 16.10.0
   @nx/nest           : 16.10.0
   @nx/node           : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/web            : 16.9.1
   @nx/webpack        : 16.10.0
   nx-cloud           : 16.5.1
   typescript         : 4.8.2
   ---------------------------------------
   Community plugins:
   @ionic/angular         : 6.7.5
   @ionic/angular-toolkit : 10.0.0
   @ngneat/spectator      : 14.0.0
   @ngrx/effects          : 15.4.0
   @ngrx/eslint-plugin    : 15.4.0
   @ngrx/router-store     : 15.4.0
   @ngrx/schematics       : 15.4.0
   @ngrx/store            : 15.4.0
   @ngrx/store-devtools   : 15.4.0
   @nxext/capacitor       : 16.7.0
   @nxext/ionic-angular   : 16.2.0
   ng-mocks               : 14.11.0
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/js@16.9.1
     - @nrwl/js@16.9.1
     - @nx/angular@16.9.1
     - @nx/devkit@16.9.1
     - @nrwl/devkit@16.9.1
     - @nx/web@16.9.1
     - @nrwl/web@16.9.1
   
   To fix this, run `nx migrate nx@16.10.0`
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by MartinKPal** [comment]
Same for us. It is really a pain.
@JackLazenbyZigzag some time passed. Did you find a way to deal with this?

**Comment by JackLazenbyZigzag** [comment]
Hi @MartinKPal! Unfortunately not, no. We still get it but it's been a lot more intermittent for us over the last month. It really does depend on what agent Azure assigns to us but recently we've not suffered too much.

We did start to move over to Github Actions  from Azure Pipelines as we didn't have the same issues there but now that it doesn't happen as much for us we popped a pin in that.

If you or anyone else finds a permanent fix for this I'd love to know about it!

**Comment by FrozenPandaz** [comment]
Is this issue still happening?

**Comment by MartinKPal** [comment]
Hi Jason,
Not anymore.


Martin Kollár

PALDESK | Core Services  Product Owner / Team Lead



________________________________
From: Jason Jean ***@***.***>
Sent: Wednesday, May 15, 2024 11:34 PM
To: nrwl/nx ***@***.***>
Cc: Kollar Martin ***@***.***>; Mention ***@***.***>
Subject: [EXT]:Re: [nrwl/nx] Nx Cloud Runners Constantly Getting SIGTERM Cancellation (Issue #19558)


Is this issue still happening?
