### ISSUE TITLE
Assets drop into build root when importing from non-module SCSS in an @nx/react app

### ISSUE THREAD

**Issue by sergiy-pereverziev-quarks-tech** [nrwl/nx#19595]
### Current Behavior

I'm trying to migrate from a customized CRA to a `@nx/react` webpack-based monorepo, and my current goal is placing static assets referred as `url`s from SCSS into a subfolder inside build folder. Maybe I didn't find the proper config option for `project.json` in the documentation (which frankly is pretty basic for `@nx/react`), but currently I'm using `assetModuleFilename` on a `config.output`.

Seems like it works well with the `module.scss` files, but doesn't work when importing plain `.scss`, and I've killed quite a bunch of time trying to figure out the difference between the two rulesets. So if I refer an asset like `url("../assets/image.png")` from SCSS, it will or will not admire `assetModuleFilename`, depending on whether or not the file is a `.module.scss` or a simple `.scss`. Assets from plain `.scss` files will go directly into build root, no matter what. See https://github.com/sergiy-pereverziev-quarks-tech/nx-react-asset-paths-bug/commit/5904c88d7d662fbae0c2897b3b9bb4c501651959 to compare the additions

<img width="1428" alt="image" src="https://github.com/nrwl/nx/assets/127740656/6369c4b3-1263-453c-818b-872aeb2b852a">

### Expected Behavior

Whereever in CSS/SCSS I reference a static file, I'd expect it to have a pathname that I pass in `config.output.assetModuleFilename`.

### GitHub Repo

https://github.com/sergiy-pereverziev-quarks-tech/nx-react-asset-paths-bug

### Steps to Reproduce

1. Create a new Nx React workspace, doesn't matter, standalone or integrated
2. Generate a React app with a Webpack 5 bundler:
```
nx g @nx/react:app
```
4. Set a non-standard `assetModuleFilename` on the Webpack config:
```
config.output.assetModuleFilename = 'media/[name].[hash][ext]';
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.13.2
   OS     : darwin-arm64
   npm    : 8.1.2
   
   nx (global)        : 16.5.1
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/react          : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/web            : 16.10.0
   @nx/webpack        : 16.10.0
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by sergiy-pereverziev-quarks-tech** [comment]
After some time of struggle, I actually found out that it might be related to https://github.com/nrwl/nx/issues/18095, using PostcssCliResources to handle assets

**Comment by RomainoSoko** [comment]
@sergiy-pereverziev-quarks-tech is there a way to bypass this or is it still waiting for a bugfix ?

**Comment by sergiy-pereverziev-quarks-tech** [comment]
@RomainoSoko it's still open, but while we are waiting, I came up with this hack:

```typescript
import { PostcssCliResources } from '@nx/webpack/src/utils/webpack/plugins/postcss-cli-resources';

// Find a loader that matches .scss|.css and includes index file, and then replace the plugin like this:

loader.options.plugins = [
  options.plugins[0],
  PostcssCliResources({
    deployUrl: '/',
    resourcesOutputPath: 'static/media',
    filename: '[name].[hash:20].[ext]',
    loader,
  }),
  options.plugins[2],
];
```
