### ISSUE TITLE
The Nx CLI could not find or load the native binary for your supported platform (linux-arm64).

### ISSUE THREAD

**Issue by vmashnitskaya** [nrwl/nx#19604]
### Current Behavior

I just migrated using nx migrate from 16.0 to 16.5.3

I am running my application in a docker environment.

Now I get the following error when I try to run it :
`The Nx CLI could not find or load the native binary for your supported platform (linux-arm64).`

I have seen the documentation that was provided to deal with such an issue. But there are several issues with it:
1. Our team does not use `npm i` on a regular basis, but rather `npm ci`  both locally and on CI to ensure version consistency. Moreover, we have different OS in a team and it means that team members will not be able to run the same package versions locally using `npm ci`.
2. Although I can use `npm i` in docker, it will be an incorrect approach for me because I will not be able to run the same versions in CI.

How can I achieve the dependencies consistency in such case?

### Expected Behavior

The applicaton is run correctly on all platforms with the same package versions.

### Steps to Reproduce

1.

### Nx Report

```shell
Node   : 18.18.0
   OS     : darwin-arm64
   npm    : 9.8.1

   nx                 : 16.5.3
   @nx/js             : 16.5.3
   @nx/jest           : 16.5.3
   @nx/linter         : 16.5.3
   @nx/workspace      : 16.5.3
   @nx/cypress        : 16.5.3
   @nx/devkit         : 16.5.3
   @nrwl/devkit       : 15.9.7
   @nx/eslint-plugin  : 16.5.3
   @nx/nest           : 16.5.3
   @nx/next           : 16.5.3
   @nx/node           : 16.5.3
   @nx/react          : 16.5.3
   @nx/rollup         : 16.5.3
   @nrwl/tao          : 16.5.3
   @nx/web            : 16.5.3
   @nx/webpack        : 16.5.3
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @jscutlery/semver : 2.30.1
```

### Failure Logs

```shell
NX   Missing Platform Dependency
The Nx CLI could not find or load the native binary for your supported platform (linux-arm64).
This likely means that optional dependencies were not installed correctly, or your system is missing some system dependencies.
```

### Operating System

- [X] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Hey @vmashnitskaya - Can you follow the steps here and see if it helps? https://nx.dev/recipes/troubleshooting/troubleshoot-nx-install-issues

**Comment by vmashnitskaya** [comment]
It helped, thank you
