### ISSUE TITLE
nx release weird behavior

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#19616]
### Current Behavior

I have a project with multiple packages, a shared `core` lib,  and `pkg1` and `pkg2` which depends on core, all packages are in v1.0.0...

Executing `nx release version 2.0.0 -p core` updates the version in `core/package.json` file but not upgrade the core dependency inside `pkg1/package.json` and `pkg2/package.json` json files

Executing `nx release version 2.0.0 -p core, pkg1, pkg2` do the job but also increase the versions for pkg1 and pkg2

### Expected Behavior

My expectations after run `nx release version 2.0.0 -p core` are this:

core/package.json:
```
{
    "name": "core",
    "version": "2.0.0", // version is updated
    ...
}
```

pk1/package.json:
```
{
    "name": "pkg1",
    "version": "1.0.0",  // Keep original version or increase to 1.0.1
    "dependencies": {
        "core": "2.0.0", // Update core dep to new version
        ....
    }
    ...
}
```

pk2/package.json:
```
{
    "name": "pkg2",
    "version": "1.0.0",  // Keep original version or increase to 1.0.1
    "dependencies": {
        "core": "2.0.0",  // Update core dep to new version
        ....
    }
    ...
}
```

### GitHub Repo

https://github.com/gperdomor/nx-tools

### Steps to Reproduce

Clone the repo and just run `nx release version 7.0.0 -p core`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.8.0
   OS     : darwin-x64
   npm    : 10.2.0
   
   nx (global)        : 16.10.0
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/plugin         : 16.10.0
   @nrwl/tao          : 16.10.0
   nx-cloud           : 16.5.2
   typescript         : 5.1.6
   ---------------------------------------
   Local workspace plugins:
         @nx-tools/nx-graphql-codegen
         @nx-tools/nx-container
         @nx-tools/nx-prisma
```

### Failure Logs

```shell
❯ nx release version 7.0.0 -p core

 >  NX   Your filter "core" matched the following projects:

   - core


 >  NX   Running release version for project: core

core 🔍 Reading data for package "@nx-tools/core" from packages/core/package.json
core 📄 Resolved the current version as 6.0.0-alpha.1 from packages/core/package.json
core ✍️  New version 7.0.0 written to packages/core/package.json

UPDATE packages/core/package.json

    "name": "@nx-tools/core",
-   "version": "6.0.0-alpha.1",
+   "version": "7.0.0",
    "type": "commonjs",
```

### Package Manager Version

npm

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JamesHenry** [comment]
@gperdomor you are brave to use an undocumented feature 🙂

**Comment by JamesHenry** [comment]
The documentation is being worked on, as well as a load of new feature that will make nx release much more well rounded for different use cases.

Initially it was built to work for the Nx repo’s own processes and conventions

**Comment by JamesHenry** [comment]
I will keep this open until we add support for independent releases, which will land some time in the next couple of weeks

**Comment by gperdomor** [comment]
@JamesHenry LOL, I was just trying 🤣... Thanks for working on this anyways

**Comment by JamesHenry** [comment]
@gperdomor haha yeah it’s good we want people to be excited to use it and find any rough edges! I’ll keep you updated on here and please keep giving us your feedback as the feature stabilizes over the coming weeks

**Comment by JamesHenry** [comment]
Hi @gperdomor, just linking to the independent releases documentation for posterity: https://nx.dev/recipes/nx-release/release-projects-independently#release-projects-independently

If you have any problems please open a new issue with the latest
