### ISSUE TITLE
Can I have different targetDefaults for different tags ?

### ISSUE THREAD

**Issue by AbdealiLoKo** [nrwl/nx#19612]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Today I can use `targetDefaults` in nx.json to provide defaults for all projects.
Having some way to have different defaults for different "types" of projects would be awesome.
Specifically I am keep to have different defaults for my python, js, rust projects

## Motivation

I recently got introduced to tags in nx - and have started using it a fair bit to organize the types of projects and so on.
I currently have a `lang:py`, `lang:js` and `framework:flask`, framework:ng` kind of tags.
For python and non-JS languages I use run-commands all the time. So having different defaults for different languages would be very useful

## Suggested Implementation

A project can have multiple tags - so, it can be a bit confusing to know which set of defaults would be applicable to which project.
Maybe there can be warnings in those times ?

## Alternate Implementations

Not sure

**Comment by AgentEnder** [comment]
Target defaults are indexed by 2 keys: 
- target name
- executor name

I believe executor name should hit your use case.
