### ISSUE TITLE
NX   Daemon process terminated and closed the connection

### ISSUE THREAD

**Issue by sunils1607** [nrwl/nx#19615]
### Current Behavior

Is any idea about how to resolved  (NX   Daemon process terminated and closed the connection error). i have tried lot . reset, restore, clear cache, reinstall, migrate, etc. and i have mallualy start the daemon. daemon was started but while run the nx serve command again got the same error. its dosen't work for me. it was totally blocking

 >  NX   Daemon process terminated and closed the connection

   Please rerun the command, which will restart the daemon.
   If you get this error again, check for any errors in the daemon process logs found in: D:\Partnersoft\Dev\Workspace\Thronex\MicroFrontend-NX-Monorepo\thronex\node_modules\.cache\nx\d\daemon.log

Daemon.log

[NX Daemon Server] - 2023-10-14T08:59:49.121Z - Started listening on: \\.\pipe\nx\C:\Users\sunil\AppData\Local\Temp\d4b9ff6fc420976aea65\d.sock
[NX Daemon Server] - 2023-10-14T08:59:49.126Z - [WATCHER]: Subscribed to changes within: d:\Partnersoft\Dev\Workspace\Thronex\MicroFrontend-NX-Monorepo\thronex (native)
[NX Daemon Server] - 2023-10-14T08:59:49.138Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-10-14T08:59:49.142Z - Closed a connection. Number of open connections: 0
[NX Daemon Server] - 2023-10-14T08:59:49.143Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-10-14T08:59:49.146Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-10-14T08:59:49.242Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-10-14T08:59:49.244Z - [REQUEST]: 
[NX Daemon Server] - 2023-10-14T08:59:49.244Z - [REQUEST]: 
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }', packages\nx\src\native\plugins\js\ts_import_locators.rs:450:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[NX Daemon Server] - 2023-10-14T09:00:11.943Z - Started listening on: \\.\pipe\nx\C:\Users\sunil\AppData\Local\Temp\d4b9ff6fc420976aea65\d.sock
[NX Daemon Server] - 2023-10-14T09:00:11.945Z - [WATCHER]: Subscribed to changes within: D:\Partnersoft\Dev\Workspace\Thronex\MicroFrontend-NX-Monorepo\thronex (native)
[NX Daemon Server] - 2023-10-14T09:00:11.954Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-10-14T09:00:11.958Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-10-14T09:00:11.960Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-10-14T09:00:12.023Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-10-14T09:00:12.023Z - [REQUEST]: 
[NX Daemon Server] - 2023-10-14T09:00:12.023Z - [REQUEST]: 
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }', packages\nx\src\native\plugins\js\ts_import_locators.rs:450:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[NX Daemon Server] - 2023-10-14T09:01:59.435Z - Started listening on: \\.\pipe\nx\C:\Users\sunil\AppData\Local\Temp\d4b9ff6fc420976aea65\d.sock
[NX Daemon Server] - 2023-10-14T09:01:59.447Z - [WATCHER]: Subscribed to changes within: D:\Partnersoft\Dev\Workspace\Thronex\MicroFrontend-NX-Monorepo\thronex (native)
[NX Daemon Server] - 2023-10-14T09:01:59.449Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-10-14T09:01:59.450Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-10-14T09:01:59.453Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-10-14T09:01:59.510Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-10-14T09:01:59.510Z - [REQUEST]: 
[NX Daemon Server] - 2023-10-14T09:01:59.510Z - [REQUEST]: 
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }', packages\nx\src\native\plugins\js\ts_import_locators.rs:450:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[NX Daemon Server] - 2023-10-14T09:18:48.103Z - Started listening on: \\.\pipe\nx\C:\Users\sunil\AppData\Local\Temp\d4b9ff6fc420976aea65\d.sock
[NX Daemon Server] - 2023-10-14T09:18:48.105Z - [WATCHER]: Subscribed to changes within: D:\Partnersoft\Dev\Workspace\Thronex\MicroFrontend-NX-Monorepo\thronex (native)
[NX Daemon Server] - 2023-10-14T09:18:48.112Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-10-14T09:18:48.114Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-10-14T09:18:48.116Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-10-14T09:18:48.120Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-10-14T09:18:48.188Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-10-14T09:18:48.188Z - [REQUEST]: 
[NX Daemon Server] - 2023-10-14T09:18:48.188Z - [REQUEST]: 
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }', packages\nx\src\native\plugins\js\ts_import_locators.rs:450:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

NX version :16.10.0

### Expected Behavior
Run or Serve the host or remote application

NX version :16.10.0

### Steps to Reproduce

While running the project we got the error (NX   Daemon process terminated and closed the connection error).

NX version :16.10.0

### Nx Report

```shell
Not able to generate. while running the nx report also getting some error (NX   Daemon process terminated and closed the connection error).
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by ggagosh** [comment]
I also have this kind of problem after upgrading to the latest version, but it appears only during Github ci

<img width="1076" alt="image" src="https://github.com/nrwl/nx/assets/1367931/cfd89601-63dd-4631-8f47-e320ba405c3e">

I can't reproduce it on my local machine, I also tried to reproduce it with the same OS: Ubuntu 22.04.3 and Node: v18.18.0 and this blocks me from updating the new version.

**Comment by Den-dp** [comment]
In my case it was caused by strange special characters in JS file

Example:
```
> cat PieSerie.js
// ï¿½

> Format-Hex PieSerie.js

           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   2F 2F 20 EF BF BD 0A                             // ï¿½.
```
Such causes an error here:
https://github.com/nrwl/nx/blob/d293d340093c6a8d1a219732553341b2e0010bb9/packages/nx/src/native/plugins/js/ts_import_locators.rs#L446-L450

**Comment by Cammisuli** [comment]
This is interesting.. How are these characters being added to these files? 

The best thing we can do is handle the error better, but if the files arent in utf-8 then we can't do much otherwise.

**Comment by nocnokneo** [comment]
I'm getting the same error and, like @ggagosh , only inside my container. Thanks to the logging improvement in #19809  I can see that the problematic file is `/home/tbj/git/cyto/env/share/terminfo/x/xterm.js`. Why is Nx scanning compiled binary files in the terminfo database?

**Comment by Cammisuli** [comment]
@nocnokneo Nx will build the project graph based on the root of the repo (where the nx.json file is). If these files arent part of gitingnore, add them to `.nxignore`. 

There's additional handling for js and ts files where we find imports to build out the dependencies. Because this particular file is a .js one, Nx will try to build out the dependency tree.
