### ISSUE TITLE
generate a new plugin with @nx/plugin fails

### ISSUE THREAD

**Issue by auberryberry** [nrwl/nx#19619]
### Current Behavior

Tried to run
`pnpm nx g @nx/plugin:plugin workspace-extensions`
got 

`
In Nx 18, generating projects will no longer derive the name and root.
Please provide the exact project name and root in the future.
Example: nx g @nx/plugin:plugin workspace-extensions --directory workspace-extensions

 >  NX   Cannot parse .prettierignore: InvalidSymbol in JSON at 1:1

   > 1 | # Add files here to ignore them from prettier formatting
       | ^
     2 | /dist
     3 | /coverage

   Pass --verbose to see the stacktrace.
`

### Expected Behavior

Expected it to work.....

### Steps to Reproduce

1.
Literally, just did a new 16.10 workspace, and tried to gen a new plugin

### Nx Report

```shell
Node   : 18.18.2
   OS     : linux-x64
   pnpm   : 8.7.4

   nx             : 16.10.0
   @nx/js         : 16.10.0
   @nx/jest       : 16.10.0
   @nx/linter     : 16.10.0
   @nx/workspace  : 16.10.0
   @nx/devkit     : 16.10.0
   @nx/plugin     : 16.10.0
   @nrwl/tao      : 16.10.0
   nx-cloud       : 16.5.2
   typescript     : 5.2.2
```

### Failure Logs

```shell
>  NX   Cannot parse .prettierignore: InvalidSymbol in JSON at 1:1

   > 1 | # Add files here to ignore them from prettier formatting
       | ^
     2 | /dist
     3 | /coverage


Error: Cannot parse .prettierignore: InvalidSymbol in JSON at 1:1
> 1 | # Add files here to ignore them from prettier formatting
    | ^
  2 | /dist
  3 | /coverage

    at readJson (/home/aubrey/development/sused/monorepo-sused/node_modules/.pnpm/nx@16.10.0/node_modules/nx/src/generators/utils/json.js:20:15)
    at readAndCombineAllProjectConfigurations (/home/aubrey/development/sused/monorepo-sused/node_modules/.pnpm/nx@16.10.0/node_modules/nx/src/generators/utils/project-configuration.js:152:53)
    at readProjectConfiguration (/home/aubrey/development/sused/monorepo-sused/node_modules/.pnpm/nx@16.10.0/node_modules/nx/src/generators/utils/project-configuration.js:95:25)
    at addLint (/home/aubrey/development/sused/monorepo-sused/node_modules/.pnpm/@nx+js@16.10.0_@types+node@20.5.7_nx@16.10.0_typescript@5.2.2/node_modules/@nx/js/src/generators/library/library.js:151:72)
    at libraryGeneratorInternal (/home/aubrey/development/sused/monorepo-sused/node_modules/.pnpm/@nx+js@16.10.0_@types+node@20.5.7_nx@16.10.0_typescript@5.2.2/node_modules/@nx/js/src/generators/library/library.js:53:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async libraryGenerator (/home/aubrey/development/sused/monorepo-sused/node_modules/.pnpm/@nx+js@16.10.0_@types+node@20.5.7_nx@16.10.0_typescript@5.2.2/node_modules/@nx/js/src/generators/library/library.js:16:12)
    at async pluginGeneratorInternal (/home/aubrey/development/sused/monorepo-sused/node_modules/.pnpm/@nx+plugin@16.10.0_@types+node@20.5.7_nx@16.10.0_typescript@5.2.2/node_modules/@nx/plugin/src/generators/plugin/plugin.js:63:16)
    at async /home/aubrey/development/sused/monorepo-sused/node_modules/.pnpm/nx@16.10.0/node_modules/nx/src/command-line/generate/generate.js:249:26
    at async handleErrors (/home/aubrey/development/sused/monorepo-sused/node_modules/.pnpm/nx@16.10.0/node_modules/nx/src/utils/params.js:9:16)
```

### Package Manager Version

8.7.4

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

WSL2
at a guess, .prettierignore isn't JSON ;)
I dragged my ass away from mission impossible to get on with writing a plugin....and this....I'm going to eat some ice-cream to make it better, so basically you folks made me eat ice-cream....sad face.

**Comment by AgentEnder** [comment]
What does your npm workspaces configuration look like?

**Comment by yukimotochern** [comment]
This will happen after convert to flag eslint config
```
yukimoto@MacStudio: ~/playground
$ pnpm dlx create-nx-workspace@latest                                                                                                             [2:06:19]
../Library/pnpm/store/v3/tmp/dlx-69134   |  +67 +++++++
../Library/pnpm/store/v3/tmp/dlx-69134   | Progress: resolved 67, reused 67, downloaded 0, added 67, done

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Where would you like to create your workspace? · org
✔ Which stack do you want to use? · node
✔ What framework should be used? · none
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · org
✔ Would you like to generate a Dockerfile? [https://docs.docker.com/] · No
✔ Enable distributed caching to make your CI faster · No

 >  NX   Creating your v16.10.0 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "pnpm install" several times. Please wait.

✔ Installing dependencies with pnpm
✔ Successfully created the workspace: org.

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


 >  NX   Nx CLI is not installed globally.

   This means that you might have to use "yarn nx" or "npx nx" to execute commands in the workspace.
   Run "yarn global add nx" or "npm install -g nx" to be able to execute command directly.


yukimoto@MacStudio: ~/playground
$ cd org                                                                                                                                          [2:06:57]

yukimoto@MacStudio: ~/playground/org main
$ pnpm nx g @nx/linter:convert-to-flat-config                                                                                                     [2:07:00]

>  NX  Generating @nx/linter:convert-to-flat-config

DELETE .eslintrc.json
DELETE .eslintignore
CREATE eslint.config.js
UPDATE package.json
DELETE apps/org/.eslintrc.json
CREATE apps/org/eslint.config.js
DELETE apps/org-e2e/.eslintrc.json
CREATE apps/org-e2e/eslint.config.js

yukimoto@MacStudio: ~/playground/org main ⚡
$ pnpm add -D @nx/plugin                                                                                                                          [2:07:05]
 WARN  deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
Packages: +2
++
Progress: resolved 632, reused 602, downloaded 0, added 2, done

devDependencies:
+ @nx/plugin 16.10.0

 WARN  Issues with peer dependencies found
.
└─┬ @nx/esbuild 16.10.0
  ├── ✕ unmet peer esbuild@~0.19.2: found 0.17.17
  └─┬ @nrwl/esbuild 16.10.0
    └─┬ @nx/esbuild 16.10.0
      └── ✕ unmet peer esbuild@~0.19.2: found 0.17.17

Done in 2.7s

yukimoto@MacStudio: ~/playground/org main ⚡
$ pnpm exec nx generate @nx/plugin:plugin --name=test-plugin --verbose                                                                            [2:07:18]

>  NX  Generating @nx/plugin:plugin


 >  NX   Unexpected token } in JSON at position 365


SyntaxError: Unexpected token } in JSON at position 365
    at JSON.parse (<anonymous>)
    at hasOverride (/Users/yukimoto/playground/org/node_modules/.pnpm/@nx+linter@16.10.0_@types+node@18.7.1_eslint@8.46.0_nx@16.10.0/node_modules/@nx/linter/src/generators/utils/flat-config/ast-utils.js:66:31)
    at lintConfigHasOverride (/Users/yukimoto/playground/org/node_modules/.pnpm/@nx+linter@16.10.0_@types+node@18.7.1_eslint@8.46.0_nx@16.10.0/node_modules/@nx/linter/src/generators/utils/eslint-file.js:161:44)
    at updateRootEslintConfig (/Users/yukimoto/playground/org/node_modules/.pnpm/@nx+plugin@16.10.0_@types+node@18.7.1_eslint@8.46.0_nx@16.10.0_ts-node@10.9.1_typescript@5.1.6/node_modules/@nx/plugin/src/generators/lint-checks/generator.js:144:54)
    at pluginLintCheckGenerator (/Users/yukimoto/playground/org/node_modules/.pnpm/@nx+plugin@16.10.0_@types+node@18.7.1_eslint@8.46.0_nx@16.10.0_ts-node@10.9.1_typescript@5.1.6/node_modules/@nx/plugin/src/generators/lint-checks/generator.js:14:9)
    at pluginGeneratorInternal (/Users/yukimoto/playground/org/node_modules/.pnpm/@nx+plugin@16.10.0_@types+node@18.7.1_eslint@8.46.0_nx@16.10.0_ts-node@10.9.1_typescript@5.1.6/node_modules/@nx/plugin/src/generators/plugin/plugin.js:99:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/yukimoto/playground/org/node_modules/.pnpm/nx@16.10.0/node_modules/nx/src/command-line/generate/generate.js:249:26
    at async handleErrors (/Users/yukimoto/playground/org/node_modules/.pnpm/nx@16.10.0/node_modules/nx/src/utils/params.js:9:16)
    at async Object.handler (/Users/yukimoto/playground/org/node_modules/.pnpm/nx@16.10.0/node_modules/nx/src/command-line/generate/command-object.js:14:22)
FAIL: 1
```

**Comment by auberryberry** [comment]
> What does your npm workspaces configuration look like?

pnpm monorepo, no npm in sight.  Promise there is no science ;)
`
packages:
  - "packages/*"
  - "apps/*"
  - "!**/test/**"
`

**Comment by AgentEnder** [comment]
> Similar problem happens after converting to flat eslint config @AgentEnder
> 
> ```
> yukimoto@MacStudio: ~/playground
> $ pnpm dlx create-nx-workspace@latest                                                                                                             [2:06:19]
> ../Library/pnpm/store/v3/tmp/dlx-69134   |  +67 +++++++
> ../Library/pnpm/store/v3/tmp/dlx-69134   | Progress: resolved 67, reused 67, downloaded 0, added 67, done
> 
>  >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]
> 
> ✔ Where would you like to create your workspace? · org
> ✔ Which stack do you want to use? · node
> ✔ What framework should be used? · none
> ✔ Integrated monorepo, or standalone project? · integrated
> ✔ Application name · org
> ✔ Would you like to generate a Dockerfile? [https://docs.docker.com/] · No
> ✔ Enable distributed caching to make your CI faster · No
> 
>  >  NX   Creating your v16.10.0 workspace.
> 
>    To make sure the command works reliably in all environments, and that the preset is applied correctly,
>    Nx will run "pnpm install" several times. Please wait.
> 
> ✔ Installing dependencies with pnpm
> ✔ Successfully created the workspace: org.
> 
>  ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
> 
> 
>  >  NX   Nx CLI is not installed globally.
> 
>    This means that you might have to use "yarn nx" or "npx nx" to execute commands in the workspace.
>    Run "yarn global add nx" or "npm install -g nx" to be able to execute command directly.
> 
> 
> yukimoto@MacStudio: ~/playground
> $ cd org                                                                                                                                          [2:06:57]
> 
> yukimoto@MacStudio: ~/playground/org main
> $ pnpm nx g @nx/linter:convert-to-flat-config                                                                                                     [2:07:00]
> 
> >  NX  Generating @nx/linter:convert-to-flat-config
> 
> DELETE .eslintrc.json
> DELETE .eslintignore
> CREATE eslint.config.js
> UPDATE package.json
> DELETE apps/org/.eslintrc.json
> CREATE apps/org/eslint.config.js
> DELETE apps/org-e2e/.eslintrc.json
> CREATE apps/org-e2e/eslint.config.js
> 
> yukimoto@MacStudio: ~/playground/org main ⚡
> $ pnpm add -D @nx/plugin                                                                                                                          [2:07:05]
>  WARN  deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
> Packages: +2
> ++
> Progress: resolved 632, reused 602, downloaded 0, added 2, done
> 
> devDependencies:
> + @nx/plugin 16.10.0
> 
>  WARN  Issues with peer dependencies found
> .
> └─┬ @nx/esbuild 16.10.0
>   ├── ✕ unmet peer esbuild@~0.19.2: found 0.17.17
>   └─┬ @nrwl/esbuild 16.10.0
>     └─┬ @nx/esbuild 16.10.0
>       └── ✕ unmet peer esbuild@~0.19.2: found 0.17.17
> 
> Done in 2.7s
> 
> yukimoto@MacStudio: ~/playground/org main ⚡
> $ pnpm exec nx generate @nx/plugin:plugin --name=test-plugin --verbose                                                                            [2:07:18]
> 
> >  NX  Generating @nx/plugin:plugin
> 
> 
>  >  NX   Unexpected token } in JSON at position 365
> 
> 
> SyntaxError: Unexpected token } in JSON at position 365
>     at JSON.parse (<anonymous>)
>     at hasOverride (/Users/yukimoto/playground/org/node_modules/.pnpm/@nx+linter@16.10.0_@types+node@18.7.1_eslint@8.46.0_nx@16.10.0/node_modules/@nx/linter/src/generators/utils/flat-config/ast-utils.js:66:31)
>     at lintConfigHasOverride (/Users/yukimoto/playground/org/node_modules/.pnpm/@nx+linter@16.10.0_@types+node@18.7.1_eslint@8.46.0_nx@16.10.0/node_modules/@nx/linter/src/generators/utils/eslint-file.js:161:44)
>     at updateRootEslintConfig (/Users/yukimoto/playground/org/node_modules/.pnpm/@nx+plugin@16.10.0_@types+node@18.7.1_eslint@8.46.0_nx@16.10.0_ts-node@10.9.1_typescript@5.1.6/node_modules/@nx/plugin/src/generators/lint-checks/generator.js:144:54)
>     at pluginLintCheckGenerator (/Users/yukimoto/playground/org/node_modules/.pnpm/@nx+plugin@16.10.0_@types+node@18.7.1_eslint@8.46.0_nx@16.10.0_ts-node@10.9.1_typescript@5.1.6/node_modules/@nx/plugin/src/generators/lint-checks/generator.js:14:9)
>     at pluginGeneratorInternal (/Users/yukimoto/playground/org/node_modules/.pnpm/@nx+plugin@16.10.0_@types+node@18.7.1_eslint@8.46.0_nx@16.10.0_ts-node@10.9.1_typescript@5.1.6/node_modules/@nx/plugin/src/generators/plugin/plugin.js:99:39)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async /Users/yukimoto/playground/org/node_modules/.pnpm/nx@16.10.0/node_modules/nx/src/command-line/generate/generate.js:249:26
>     at async handleErrors (/Users/yukimoto/playground/org/node_modules/.pnpm/nx@16.10.0/node_modules/nx/src/utils/params.js:9:16)
>     at async Object.handler (/Users/yukimoto/playground/org/node_modules/.pnpm/nx@16.10.0/node_modules/nx/src/command-line/generate/command-object.js:14:22)
> FAIL: 1
> ```

@yukimotochern  This is a different issue, can you open a new ticket tracking that?

**Comment by AgentEnder** [comment]
> > What does your npm workspaces configuration look like?
> 
> pnpm monorepo, no npm in sight. Promise there is no science ;) ` packages:
> 
> * "packages/*"
> * "apps/*"
> * "!**/test/**"
>   `

Can you post a reproduction repo for me to check out? The following steps work fine for me:

```shell
> npx -y create-nx-workspace@latest my-workspace --no-nxCloud --preset apps
> npm i --save-dev @nx/plugin
> nx g plugin my-plugin
```
