### ISSUE TITLE
404 on "getting-started"

### ISSUE THREAD

**Issue by artiphishle** [nrwl/nx#19620]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/getting-started/what-is-nx

### Additional context or description

404 on mentioned url on
- latest Android 13
- latest Github app from playstore

(only this issue, reproducible on my device. no network changes or similar)

**Comment by scha-ch** [comment]
it's the link to the 30-min video introduction

**Comment by mandarini** [comment]
Hi there @artiphishle ! Thanks for this bug report! The page you are looking for is maybe this? https://nx.dev/getting-started/intro

May I ask where was that link posted? It will help me determine whether we need to add a redirect rule for it or not!

**Comment by artiphishle** [comment]
@mandarini Hi, sorry for the delay, just sorting my inbox now.

It was here:
https://nx.dev/getting-started/intro

The link on top towards the Youtube video wasn't working on Android, now tested on desktop and it works.
If you can make sure it also works on Android 13, this can be closed.

Thanks.

**Comment by mandarini** [comment]
Thank you!!! Verified and it seems to be working! THanks!
