### ISSUE TITLE
Explicit lazy load of modules present in libs not working for component level lazy loading

### ISSUE THREAD

**Issue by siddharthpal** [nrwl/nx#1963]
# Prerequisites
Nx Version : 7.8.0
```
"dependencies": {
    "@angular/animations": "^7.0.0",
    "@angular/common": "^7.0.0",
    "@angular/compiler": "^7.0.0",
    "@angular/core": "^7.0.0",
    "@angular/forms": "^7.0.0",
    "@angular/platform-browser": "^7.0.0",
    "@angular/platform-browser-dynamic": "^7.0.0",
    "@angular/router": "^7.0.0",
    "core-js": "^2.5.4",
    "rxjs": "6.3.3",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "ts-jest": "24.0.0",
    "jest-preset-angular": "7.0.0",
    "@nrwl/builders": "7.8.0",
    "jest": "24.1.0",
    "@types/jest": "24.0.9",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "^7.0.0",
    "@angular-devkit/build-angular": "~0.13.0",
    "codelyzer": "~4.5.0",
    "cypress": "3.1.0",
    "@types/jquery": "3.3.6",
    "@angular/cli": "7.3.1",
    "@nrwl/schematics": "7.8.0",
    "@types/node": "~8.9.4",
    "dotenv": "6.2.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "3.2.2",
    "prettier": "1.15.2"
  }
```
- [ X] I am running the latest version

## Expected Behavior
I am trying to lazy load a module that is present inside libs. I have already added the libs path in my tsconfig.app.json as suggested in #909 . I see that we can not build explicitly lazy modules in aot mode as said [here](https://github.com/angular/angular-cli/issues/6373). Is that true? I am trying to lazy load at the component level but not route level. 
```
  "include": [
    "**/*.ts",
    "../../../libs/lazy/src/index.ts"
  ]
```

## Current Behavior
For AOT builds I am seeing the below issue 
`
ERROR in ./$$_lazy_route_resource lazy namespace object
Module not found: Error: Can't resolve '/Users/palsiddh/Documents/bitbucket/lazy-load/libs/lazy/src/lib/lazy-element/lazy-element.module.ngfactory.js' in '/Users/palsiddh/Documents/bitbucket/lazy-load/apps/lazy-load/$$_lazy_route_resource
`

and for non-AOT builds, I see the below one
`
ERROR in /Users/palsiddh/Documents/bitbucket/lazy-load/libs/lazy/src/lib/lazy-element/lazy-element.module.ts
Module build failed (from /Users/palsiddh/Documents/bitbucket/lazy-load/node_modules/@ngtools/webpack/src/index.js):
Error: /Users/palsiddh/Documents/bitbucket/lazy-load/libs/lazy/src/lib/lazy-element/lazy-element.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/Users/palsiddh/Documents/bitbucket/lazy-load/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:752:23)
    at plugin.done.then (/Users/palsiddh/Documents/bitbucket/lazy-load/node_modules/@ngtools/webpack/src/loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`
### Steps to Reproduce

1. Create Nx(7.0.0) app with angular as ecosystem
2. Create a library 
3. Add a module in the library created
4. Create a component inside the library
5. Add the module created in library as a lazyModule in angular json for the default app created as below
`
             "lazyModules": [
              "libs/lazy/src/lib/lazy-element/lazy-element.module"
            ],
`
6. Run build with `--configuration=production --aot --optimization --buildOptimizer --output-hashing none` for AOT build

Sample [repo](https://github.com/siddharthpal/lazy-load) for issue repro.

**Comment by FrozenPandaz** [comment]
I know this issue is for Nx 7 but I don't think a fix for this will happen.

This is deprecated as of Angular 9. Starting with Angular 8 you should be able to use the `import()` syntax. 

Closing as this behavior is deprecated.
