### ISSUE TITLE
Unable to resolve @nx/web:file-server when adopting nx in existing angular project

### ISSUE THREAD

**Issue by Clindbergh** [nrwl/nx#19655]
### Current Behavior

When running `nx serve app` with `@nx/web:file-server` as executor the execution fails.

### Expected Behavior

Serving the angular app works as expected.

### GitHub Repo

https://github.com/Clindbergh/nx_sample_app/blob/0dda0dff86943ae0edc9cd555c51297df9dc3682/project.json#L50

### Steps to Reproduce

1. Generate a new angular template based on the [tutorial](https://nx.dev/getting-started/tutorials/angular-standalone-tutorial)
2. Replace the executor with ` file-server ` according to https://twitter.com/victorsavkin/status/1356968136784965635?ref_src=twsrc%5Etfw (via https://stackoverflow.com/a/68715756)

### Nx Report

```shell
> myngapp@0.0.0 test
> nx report


 >  NX   Report complete - copy this into the issue template

   Node   : 18.14.1
   OS     : darwin-arm64
   npm    : 9.3.1
   
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/angular        : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/playwright     : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/webpack        : 16.10.0
   typescript         : 5.1.6
```

### Failure Logs

```shell
> app@0.0.0 nx-serve
> nx serve app


 >  NX   Unable to resolve @nx/web:file-server.

   Cannot find module '@nx/web/package.json'
   Require stack:
   - /Users/primary/repos/intemp/gitlab/intemp/hub/hub-frontend/node_modules/nx/src/utils/package-json.js
   - /Users/primary/repos/intemp/gitlab/intemp/hub/hub-frontend/node_modules/nx/src/utils/package-manager.js
   - /Users/primary/repos/intemp/gitlab/intemp/hub/hub-frontend/node_modules/nx/bin/init-local.js
   - /Users/primary/repos/intemp/gitlab/intemp/hub/hub-frontend/node_modules/nx/bin/nx.js
```

### Operating System

- [X] macOS
- [x] Linux
- [x] Windows
- [x] Other (Please specify)

### Additional Information

I am new to nx and was hoping to be able to speed up compilation with nx. Our project is not neatly structured into dozens of smaller projects, so module federation and incremental builds do not (yet - perhaps as a secondary measure) apply. I was hoping that the cache would increase build times to serve the files.

Unfortunately the [nrwl/nx-incremental-large-repo repo](https://github.com/nrwl/nx-incremental-large-repo) seems to be outdated and does not show how to speed up these build times.

Please advise how nx helps for these medium-sized, existing projects that have no clear boundaries defined yet. The documentation mostly assumes familiarity with large, well-structured code bases. I hope to granularly get to know and use more and more features of nx, while experiencing an immediate benefit of switching to nx.

**Comment by AgentEnder** [comment]
Hey @Clindbergh - to use an executor the package containing it needs to be installed. In this case, you'd need to install `@nx/web`.

RE: Incremental builds + speed ups for smaller existing repositories - The tutorial you linked goes into some detail about slowly starting to modularize your app some more. Nx's caching takes place at the target level, so there's not a huge speedup that you'll see for serve  or build of a singular project. Nx provides a good framework for how you can modularize things though, and you can start seeing some speedups immediately by caching your builds when only a test is updated or things like that.
