### ISSUE TITLE
In module federation with React and SSR, remote modules are not working properly

### ISSUE THREAD

**Issue by thanhiro** [nrwl/nx#19677]
### Current Behavior

When using React-specific instructions from [https://nx.dev/recipes/react/module-federation-with-ssr](url) and running `store` host, remote `checkout` is not rendered in SSR. Instead, first remote, `product` is shown in it's place, before it gets replaced by CSRed `checkout`.

### Expected Behavior

Remote `checkout` should be rendered in SSR.

### Steps to Reproduce

1. Create worksplace with nx@next
2. `nx g @nx/angular:host store --ssr --remotes=product,checkout`
3. `nx serve store`
4. Open http://localhost:4200/checkout

### Nx Report

```shell
Node   : 18.18.0
   OS     : darwin-arm64
   pnpm   : 8.8.0

   nx                 : 17.0.0-beta.8
   @nx/js             : 17.0.0-beta.8
   @nx/jest           : 17.0.0-beta.8
   @nx/eslint         : 17.0.0-beta.8
   @nx/workspace      : 17.0.0-beta.8
   @nx/cypress        : 17.0.0-beta.8
   @nx/devkit         : 17.0.0-beta.8
   @nx/eslint-plugin  : 17.0.0-beta.8
   @nx/react          : 17.0.0-beta.8
   @nrwl/tao          : 17.0.0-beta.8
   @nx/web            : 17.0.0-beta.8
   @nx/webpack        : 17.0.0-beta.8
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by thanhiro** [comment]
Also if you choose default (CSS )when generating remotes, CSS modules in remotes are failing in SSR when you try to use them inside remote component.

**Comment by xiongemi** [comment]
this possibly be fixed in PR https://github.com/nrwl/nx/pull/19565
could you try again with the latest nx (v17)?

**Comment by thanhiro** [comment]
Unfortunately, it's not working with 17.0.2 either. Migrated my workspace and then, to be surem, recreated host and remotes. Still same behaviour, wrong (the first in list) federated module gets rendered.

**Comment by xiongemi** [comment]
hey @thanhiro, in the all your tsconfig.server.json, under all the remotes and host, do you have these types `"@nx/react/typings/cssmodule.d.ts"`and `"@nx/react/typings/image.d.ts"`:
```
  "compilerOptions": {
...
    "types": [
      "node",
      "@nx/react/typings/cssmodule.d.ts",
      "@nx/react/typings/image.d.ts"
    ]
  },
```

this should fix your css error?
what kind of error message you got when you try to serve up the app?

**Comment by thanhiro** [comment]
Yes, those types are defined. But when I even try to import a CSS module in federated SSR, there's this error:

> ReferenceError: document is not defined
> while loading "./Module" from 19
>     at findStylesheet (node-federation-loader-checkout.vm:234:36)
>     at node-federation-loader-checkout.vm:251:17
>     at new Promise (<anonymous>)
>     at loadStylesheet (node-federation-loader-checkout.vm:248:20)
>     at Object.__webpack_require__.f.miniCss (node-federation-loader-checkout.vm:264:58)
>     at node-federation-loader-checkout.vm:113:40
>     at Array.reduce (<anonymous>)
>     at Function.__webpack_require__.e (node-federation-loader-checkout.vm:112:67)
>     at Object../Module (node-federation-loader-checkout.vm:10:30)
>     at Object.get (node-federation-loader-checkout.vm:17:23)

**Comment by xiongemi** [comment]
@thanhiro i tried latest nx with ssr example out of the box, it seems fine. do you have a repo for this error?

**Comment by thanhiro** [comment]
Yet again I recreated everything, with 17.0.3, and like documentation suggests.  And the behaviour is exactly the same.
1. When opening checkout page, it actually SSRs product module, not checkout module.
2. If trying to use CSS module classes in code, SSR rendering fails with aforementioned error. (CSR works there as well)

My repo here: https://github.com/thanhiro/nx-example/

**Comment by xiongemi** [comment]
@thanhiro i checkout your repo. when i ran `npx nx serve store`, i can open the `http://localhost:4200/checkout` and it does open the ckecout page.

<img width="1071" alt="Screenshot 2023-11-06 at 1 32 01 PM" src="https://github.com/nrwl/nx/assets/16211801/7d8dba5c-3175-431c-a510-440f41fd2f5a">

also, i saw you changed the background of product page, which runs fine:
<img width="1040" alt="Screenshot 2023-11-06 at 1 33 11 PM" src="https://github.com/nrwl/nx/assets/16211801/16d9460b-2181-4706-85eb-84303d3fc3d4">

**Comment by thanhiro** [comment]
Are you  sure they are properly server-side rendered? CSR is working for me, and if JavaScript is enabled, pages are replaced by proper version by client-side React. But SSRing is failing.

**Comment by thanhiro** [comment]
<img width="643" alt="image" src="https://github.com/nrwl/nx/assets/233608/96901d0b-4a00-4edf-8327-923498800945">
I see that when JS is disabled. Also in /checkout route, as it tries to execute product module.

**Comment by xiongemi** [comment]
i see. i am able to replicate it now. i think this issue is related to https://github.com/webpack-contrib/mini-css-extract-plugin/issues/90. the nx webpack config uses plugin mini-css-extract-plugin under the hood.

**Comment by thanhiro** [comment]
Hi, please note that CSS bug is actually not the original topic why I filed this issue, just something I noted as an additional problem when generating SSR + MF applications as instructed. 

Upgraded to 17.1.2 and the original problem still persist and wrong module gets rendered in server, so problem lies in how federated modules are resolved server side.
