### ISSUE TITLE
Consuming lit lib in angular app throws scss error

### ISSUE THREAD

**Issue by ChellappanRajan** [nrwl/nx#19688]
### Current Behavior

I am creating a Lit library in an NX repository and attempting to consume that library in an Angular application. However, I have encountered the following error:

![image](https://github.com/nrwl/nx/assets/22997191/edb0c8a1-cd66-4c45-9a1c-811bd3b026a7)

I managed to fix the error related to the TypeScript module declaration by adding a type declaration file:
Error: libs/my-lib/src/lib/my-button.ts:3:20 - error TS2307: Cannot find module './button.scss' or its corresponding type declarations.

However, I am unable to resolve the following error related to a SCSS file:

```
./libs/my-lib/src/lib/button.scss:1:0 - Error: Module parse failed: Unexpected token (1:0)
File was processed with these loaders:
 * ./node_modules/resolve-url-loader/index.js
 * ./node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
> .test {
|   color: red;
| }
```
Any help would be greatly appreciated. Please help

### Expected Behavior

Angular app should work without any build error

### Nx Report

```shell
./libs/my-lib/src/lib/button.scss:1:0 - Error: Module parse failed: Unexpected token (1:0)
File was processed with these loaders:
 * ./node_modules/resolve-url-loader/index.js
 * ./node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
> .test {
|   color: red;
| }
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by ChellappanRajan** [comment]
> Thanks for reporting this!
> 
> Please provide a repo where the issue can be reproduced or, at the very least, detailed reproduction steps so we can troubleshoot it.

Thank you for your request. Please give me some time, and I will ensure to upload the necessary information within a day. Thank you for your patience.

**Comment by sandrooco** [comment]
@ChellappanRajan Were you able to resolve this? I'm facing the same issue.
