### ISSUE TITLE
Expo + Storybook doesn't generate storybook component controls

### ISSUE THREAD

**Issue by PrimulaX** [nrwl/nx#19682]
### Current Behavior

When I'm trying to have automatically generated controls based on component types it doesn't generate them.

### Expected Behavior

Storybook should automatically generate story controls based on it types.

### GitHub Repo

https://github.com/PrimulaX/nx_expo_storybook

### Steps to Reproduce

1. Generate Nx workspace with expo preset
2. Add storybook configuration
3. create a story of a component
4. check controls

### Nx Report

```shell
Node   : 18.16.0
   OS     : darwin-arm64
   npm    : 9.5.1
   
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/detox          : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/expo           : 16.10.0
   @nx/react          : 16.10.0
   @nx/react-native   : 16.10.0
   @nx/storybook      : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/web            : 16.10.0
   @nx/webpack        : 16.10.0
   typescript         : 5.1.6
```

### Package Manager Version

npm - 9.5.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Hi there @PrimulaX ! Thanks for filing an issue.

I don't see any props [declared on your components](https://github.com/PrimulaX/nx_expo_storybook/blob/master/apps/strbook/src/storybook/%20components/Switch/Switch.tsx). You are importing the `SwitchProps` as I see, but our generator cannot pick these up. It only picks up props that are directly declared in your code. Check out my PR here:
https://github.com/PrimulaX/nx_expo_storybook/pull/1

Hope this helps! Please let me know if you have any questions, and thanks again! :D

**Comment by PrimulaX** [comment]
That's not about props, it's about controls generation based on component types.
AnywayI have fixed that issue by installing `@storybook/react` as a separate package, basically now I have `@storybook/react` and `@nx/storybook` at the same time.

**Comment by PrimulaX** [comment]
I guess it still needs to be fixed.

**Comment by mandarini** [comment]
Hm ok then I misunderstood. Sorry about that. So, you mean that in the Storybook UI you don't see the controls tab?

**Comment by mandarini** [comment]
Ok. I think maybe this issue is related, too: https://github.com/nrwl/nx/issues/17960

Have you tried this in a pure storybook app? I mean, outside Nx? Could be a third-party issue.

**Comment by PrimulaX** [comment]
No, I don't think so, I guess its storybook versions are mismatched, react native storybook doesn't work with newer versions of the storybook and addons, and Nx uses newer versions.

**Comment by xiongemi** [comment]
this issue relies on @storybook/react-native package. this needs wait for this package to be updated.

**Comment by guillempuche** [comment]
Maybe now is the moment https://storybook.js.org/blog/react-native-storybook-7/

> RN Storybook to core Storybook 7.6, enhances code re-use between @storybook/react and @storybook/react-native, and builds the foundations for more frequent and streamlined future releases.

**Comment by xiongemi** [comment]
i change the storybook for expo to use react-native-web. so you can use @storybook/react instead.
