### ISSUE TITLE
E2E test setup with verdaccio

### ISSUE THREAD

**Issue by gitLinda** [nrwl/nx#19683]
### Current Behavior

When adding plugin e2e tests with the e2eProjectGenerator, a _start-local-registry.ts_ is generated.
When I run the e2e target of my-plugin-e2e, which executes the _start-local-registry.ts_ script, I get the following error:

`
Jest: Got error running globalSetup - C:\Users\lkrue\develop\temp\jose\tools\scripts\start-local-registry.ts, reason: spawnSync C:\Users\lkrue\develop\temp\jose\node_modules\.pnpm\nx@16.10.0_@swc-node+register@1.6.8_@swc+core@1.3.93\node_modules\nx\bin\nx.js UNKNOWN
`

I checked the path in the node modules, and it's there. Also the `const nx = require.resolve('nx')` line is fine. The error happens when executing
`
execFileSync(
    nx,
    ['run-many', '--targets', 'publish', '--ver', '1.0.0', '--tag', 'e2e'],
    { env: process.env, stdio: 'inherit' }
  );
`

It seems to be a windows problem. Since it is running fine on Mac.

### Expected Behavior

The e2e tests can be executed

### Steps to Reproduce

1. Generate a new plugin
2. Generate a e2e app for the plugin
3. Run the e2e target of the e2e app

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.14.0
   OS     : win32-x64
   pnpm   : 8.7.6

   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nrwl/js           : 15.9.2
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nrwl/workspace    : 15.9.2
   @nx/devkit         : 16.10.0
   @nrwl/devkit       : 15.9.2
   @nx/eslint-plugin  : 16.10.0
   @nx/plugin         : 16.10.0
   @nrwl/tao          : 15.9.2
   @nrwl/web          : 15.9.2
   typescript         : 5.1.6
   ---------------------------------------
   Local workspace plugins:
         @myorg/my-plugin
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/js@15.9.2
     - @nrwl/workspace@15.9.2
     - @nrwl/devkit@15.9.2
     - @nrwl/tao@15.9.2
     - @nrwl/web@15.9.2

   To fix this, run `nx migrate nx@16.10.0`
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by khalilou88** [comment]
Same error on windows: https://github.com/khalilou88/jnxplus/actions/runs/6727510978/job/18285417595
