### ISSUE TITLE
@nx/react-native:pod-install cannot be run with bundler

### ISSUE THREAD

**Issue by ste7en** [nrwl/nx#19698]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
I propose the addition of a feature to the project that would allow users to run the Cocoapods `pod install` command via Bundler, using the syntax `bundle exec pod install` as opposed to the current implementation which requires running `pod install` directly. This implementation would encapsulate the Cocoapods environment within a Bundler context, which can provide a more consistent and controlled environment for dependency management.

## Motivation
Running `pod install` via Bundler using `bundle exec pod install` can offer a number of advantages over running `pod install` directly. These advantages include:
1. **Dependency Isolation:** Bundler provides a consistent environment for projects by tracking and installing the exact gems and versions that are needed.
2. **Avoiding Version Conflicts:** Bundler prevents environment pollution by ensuring that the gems you need are present in the development, staging, and production stages.

## Suggested Implementation
1. Introduce a new configuration option within the project settings to allow users to specify their preference for running `pod install` via Bundler.
2. Update the relevant scripts and documentation to check for this configuration option and run `pod install` commands via `bundle exec` where specified.

## Alternate Implementations
N/A

**Comment by migueldaipre** [comment]
Could we add support for the new architecture?

`RCT_NEW_ARCH_ENABLED=1 bundle exec pod install`

https://reactnative.dev/docs/the-new-architecture/pillars-fabric-components#ios-1

Without this, it is not possible to enable the new architecture on iOS with nx.
