### ISSUE TITLE
NX@16.10.0

### ISSUE THREAD

**Issue by CodeNameNinja** [nrwl/nx#19692]
### Current Behavior

I am getting a Socket Connection Timeout, on images that have NX installed.

30.13 error https://registry.yarnpkg.com/@nrwl/nx-linux-x64-gnu/-/nx-linux-x64-gnu-15.8.9.tgz: Socket connection timeout

```Dockerfile

FROM node:20.2-alpine3.17

WORKDIR /app

COPY package.json yarn.lock ./

COPY libs libs

COPY apps/api/auth apps/api/auth

RUN yarn install

RUN yarn workspace @channel360/core build

RUN yarn workspace auth build

WORKDIR /app/apps/api/auth

CMD ["node", "dist/index.js"]
```

Version in package.json
 `"nx": "16.10.0",`
 I have tried to go to older versions, such as `15.8.9` and I am still getting the same issue
 

### Expected Behavior

For the docker image to finish building

### Steps to Reproduce

1. build a docker image with a package.json with nx@16.10.0 installed

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.16.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx              : 15.8.9
   @nrwl/cli       : 15.8.9
   @nrwl/tao       : 15.8.9
   @nrwl/nx-cloud  : 16.5.2
   typescript      : 5.2.2
   ---------------------------------------
   Community plugins:
   nx-cloud : 16.5.2
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Sorry, there's not enough information to help you here. Is it possible this was a networking issue that was intermittent?
