### ISSUE TITLE
nrwl not respecting the cypress --env argument through command line

### ISSUE THREAD

**Issue by prudhvidandamudi** [nrwl/nx#1970]
I was not able to understand if I am doing something wrong or it's a Bug.

I wanted to set my env variable defined in the cypress.json file through the command line. According to the cypress docs, they give 5 different styles to do that. But nrwl is not respecting the cypress 
--env option (**https://docs.cypress.io/guides/guides/environment-variables.html#Option-3-CYPRESS**)

My **cypress.json** File
```
{
  "defaultCommandTimeout": 8000,
  "viewportWidth": 1440,
  "viewportHeight": 900,
  "env": {
    "ENVIRONMENT": "Stagging"
  },
  "fileServerFolder": ".",
  "fixturesFolder": "./src/fixtures",
  "integrationFolder": "./src/integration",
  "pluginsFile": "./src/plugins/index",
  "supportFile": "./src/support/index.ts",
  "video": true,
  "videosFolder": "../../../dist/cypress/apps/web/e2e/videos",
  "screenshotsFolder": "../../../dist/cypress/apps/web/e2e/screenshots",
  "chromeWebSecurity": false
}
```
I am using this command `ng e2e --env environment=Dev --watch --headless`
**it's giving me 'Unknown option: '--env'**

![image](https://user-images.githubusercontent.com/46937269/67107051-b1653100-f199-11e9-8c0b-daf3f77e850b.png)

I also tried using `cypress open --env environment=Dev` instead of the ng CLI command, the problem here is according to the framework .nodemodules is sitting in projects root folder 'projectname\node_modules' , whereas my cypress framework is sitting in 'projectname\apps\admin-web\ui-e2e' so, when I am trying to execute `cypress open --env environment=Dev'` a sample cypress framework and cypress.json file is getting created in the root folder ('projectname\cypress.json') and executing cypress example integration tests, instead of my project tests

StackOverflow question
https://stackoverflow.com/questions/58440173/how-to-set-environment-variables-in-cypress-json-file-through-command-line-ang

I was not able to figure this out. Can anyone help me with it, Thank you

**Comment by asafbenm** [comment]
@prudhvidandamudi  i notice that the issue is closed.
can you share the solution for this issue... it's happens to me also.

thanks

**Comment by rovshenn** [comment]
Same problem here, no way to pass @vsavkin is there any way to have this. I am on the latest nrwl nx 8 version at the moment 8.12.10 and I am still getting the above error

**Comment by srbagg** [comment]
I'm on v9.2.4 and still getting same error. Can anyone share the solution?

**Comment by egdraper** [comment]
I had the same issue, searched all over the interwebs and found this something that might work. Not sure if this helps in every `env` situation. But, in mine, I was trying to set the baseUrl in the environment variables using 
```
ng e2e --env baseUrl=https://myEnvironemnt.myApp.com
```
Which gave me that same error above. I finally saw someone get rid of the `--env` and just do it this way.

```
ng e2e --baseUrl https://myEnvironemnt.myApp.com
```
This seemed to work for this one case at least.

**Comment by AskMarvinV** [comment]
Can this be re-open? it should allow the env to pass custom variable eg. ` --env mock_env `

**Comment by panraj01** [comment]
> Can this be re-open? it should allow the env to pass custom variable eg. `--env mock_env`

If your env in cypress.json is something like this:

"env": {
        "TAGS": "not @ignore",
        "build": ""
    },
to pass on a custom build (in the case above) from command line using nx try:
nx <target> <projectName> --env.build PR-122 --watch

#target is set in workspace.json
#env is set in cypress.json and is of type object 
#watch is to run in watch mode, can be removed if you dont want to see the browser.

**Comment by hadrien-toma** [comment]
@panraj01, I get 

```

**Comment by hadrien-toma** [comment]
@panraj01, on my side:

```
$> cat apps/my-app-e2e/cypress.json                    
{
        "env": {
                "myEnv": ""
        },
        "fileServerFolder": ".",
        "fixturesFolder": "./src/fixtures",
        "integrationFolder": "./src/integration",
        "modifyObstructiveCode": false,
        "pluginsFile": "./src/plugins/index",
        "supportFile": "./src/support/index.ts",
        "video": true,
        "videosFolder": "../../dist/cypress/apps/my-app-e2e/videos",
        "screenshotsFolder": "../../dist/cypress/apps/my-app-e2e/screenshots",
        "chromeWebSecurity": false
}
```

And:

```
$> yarn run nx e2e --project=my-app-e2e --env.myEnv foo
yarn run v1.21.1
$ nx e2e --project=bashopin-e2e --env.myEnv foo

> ng run bashopin-e2e:e2e --env=[object Object] 
Unknown option: '--env'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Context:

```
$> yarn run nx version
yarn run v1.21.1
$ nx version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.6
Node: 13.14.0
OS: linux x64

Angular: 10.0.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.6
@angular-devkit/build-angular      0.1000.6
@angular-devkit/build-ng-packagr   0.1000.6
@angular-devkit/build-optimizer    0.1000.6
@angular-devkit/build-webpack      0.1000.6
@angular-devkit/core               10.0.6
@angular-devkit/schematics         10.0.6
@angular/cdk                       10.1.3
@angular/cli                       10.0.6
@angular/material                  10.1.3
@ngtools/webpack                   10.0.6
@schematics/angular                10.0.6
@schematics/update                 0.1000.6
ng-packagr                         10.0.4
rxjs                               6.5.5
typescript                         3.9.7
webpack                            4.43.0
    
Done in 1.02s.
```

**Comment by egdraper** [comment]
I am still having this issue, I have everything related cypress, angular, nwrl, and typescript updated to the most recent version and still Nada!

So I dived into the @nwrls code and found where the error is coming from at least. Everything in their code seems to be correct but there is this weird bug that is causing the CLI to error even though the code itself will handle the --env parameter. 

Inside the schema.json file in (@ `../node_modules/@nrwl/cypress/src/builders/cypress`) is where the cli parameters are defined. `env` is clearly one of the options, because it is listed there like so...
```
...
    "env": {
      "type": "object",
      "description": "A key-value Pair of environment variables to pass to Cypress runner"
    }
...,
```

But I noticed that when I would type `ng e2e --help` the `--env` is not listed among the cli options. Yet I could see it in the schema.json file. 

So I modified the `"type": "object"` to `"type": "string"` and voila it showed up in the "ng e2e --help". and the "Unknown Option" disappeared, But since we are not passing in a string, it fails sometime later while trying to be parsed (I am guessing). 

For some reason `"type": "object"` is causing this issue when "type" is set to "object". Not sure yet why, but it is clearly the culprit for the above-mentioned error "Unknown Option: --env"

**Comment by panraj01** [comment]
> @panraj01, on my side:
> 
> ```
> $> cat apps/my-app-e2e/cypress.json                    
> {
>         "env": {
>                 "myEnv": ""
>         },
>         "fileServerFolder": ".",
>         "fixturesFolder": "./src/fixtures",
>         "integrationFolder": "./src/integration",
>         "modifyObstructiveCode": false,
>         "pluginsFile": "./src/plugins/index",
>         "supportFile": "./src/support/index.ts",
>         "video": true,
>         "videosFolder": "../../dist/cypress/apps/my-app-e2e/videos",
>         "screenshotsFolder": "../../dist/cypress/apps/my-app-e2e/screenshots",
>         "chromeWebSecurity": false
> }
> ```
> 
> And:
> 
> ```
> $> yarn run nx e2e --project=my-app-e2e --env.myEnv foo
> yarn run v1.21.1
> $ nx e2e --project=my-app-e2e --env.myEnv foo
> 
> > ng run my-app-e2e:e2e --env=[object Object] 
> Unknown option: '--env'
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```
> 
> Context:
> 
> ```
> $> yarn run nx version
> yarn run v1.21.1
> $ nx version
> 
>      _                      _                 ____ _     ___
>     / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
>    / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
>   / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
>  /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
>                 |___/
>     
> 
> Angular CLI: 10.0.6
> Node: 13.14.0
> OS: linux x64
> 
> Angular: 10.0.11
> ... animations, common, compiler, compiler-cli, core, forms
> ... language-service, platform-browser, platform-browser-dynamic
> ... router
> Ivy Workspace: Yes
> 
> Package                            Version
> ------------------------------------------------------------
> @angular-devkit/architect          0.1000.6
> @angular-devkit/build-angular      0.1000.6
> @angular-devkit/build-ng-packagr   0.1000.6
> @angular-devkit/build-optimizer    0.1000.6
> @angular-devkit/build-webpack      0.1000.6
> @angular-devkit/core               10.0.6
> @angular-devkit/schematics         10.0.6
> @angular/cdk                       10.1.3
> @angular/cli                       10.0.6
> @angular/material                  10.1.3
> @ngtools/webpack                   10.0.6
> @schematics/angular                10.0.6
> @schematics/update                 0.1000.6
> ng-packagr                         10.0.4
> rxjs                               6.5.5
> typescript                         3.9.7
> webpack                            4.43.0
>     
> Done in 1.02s.
> ```
> 
> 😢

Sorry i was away from work, i just checked this - WHAT in freaking world they changed in 20 days- this no longer works for me. How about you ?  These guys are so poor in documentation, their update break stuff and they dont even know or care.

**Comment by wmedali** [comment]
I am also having the same issue, no answer found on the web :/ 
my cypress.json 
```json
{
    "fileServerFolder": ".",
    "fixturesFolder": "./src/fixtures",
    "integrationFolder": "./src/integration",
    "modifyObstructiveCode": false,
    "pluginsFile": "./src/plugins/index",
    "supportFile": "./src/support/index.ts",
    "videosFolder": "../../dist/cypress/apps/extranet-e2e/videos",
    "screenshotsFolder": "../../dist/cypress/apps/extranet-e2e/screenshots",
    "chromeWebSecurity": false,
    "viewportHeight": 800,
    "viewportWidth": 1280,
    "reporter": "../../node_modules/cypress-multi-reporters",
    "reporterOptions": {
        "reporterEnabled": "mochawesome, mocha-junit-reporter",
        "mochaJunitReporterReporterOptions": {
            "mochaFile": "../../dist/cypress/apps/extranet-e2e/reports/junit/results-[hash].xml"
        },
        "mochawesomeReporterOptions": {
            "reportDir": "../../dist/cypress/apps/extranet-e2e/reports",
            "overwrite": false,
            "html": false
        }
    },
    "downloadsFolder": "../../dist/cypress/apps/extranet-e2e/downloads"
}
```

and : 

```
$@alee-mac front-end % nr e2e                     

> edenred@0.0.0 e2e /Users/alee/Desktop/repos/front-end
> rm -rf dist/cypress && ng e2e extranet-e2e --headless --baseUrl=http://localhost:4200 --env grepTags=visual


> nx run extranet-e2e:e2e --headless --baseUrl=http://localhost:4200 --env=grepTags=visual 
Property 'env' does not match the schema. 'grepTags=visual' should be a 'object'.
```
Context : 
```
$ front-end % nr e2e                     

> edenred@0.0.0 e2e /Users/alee/Desktop/repos/front-end
> rm -rf dist/cypress && ng e2e extranet-e2e --headless --baseUrl=http://localhost:4200 --env grepTags=visual
alee@alee-mac front-end % nx version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.0
Node: 14.16.1
Package Manager: npm 6.14.12
OS: darwin arm64

Angular: 12.2.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, google-maps, language-service, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.2.0
@angular-devkit/core            12.2.0
@angular-devkit/schematics      12.1.4
@schematics/angular             12.1.4
ng-packagr                      12.1.2
rxjs                            7.3.0
typescript                      4.3.5
```

**Comment by Yohandah** [comment]
I'm also facing this issue; I'm trying to pass --env TAGS='@e2e-test' and it says `Property 'env' does not match the schema. 'TAGS=@e2e-test' should be a 'object'.` @meeroslav

**Comment by wmedali** [comment]
@Yohandah

You can do it this way : 
`--env.TAGS=@e2e-tests`
It seems to work.

**Comment by JohnnyDevNull** [comment]
Push... i came across this too. The error still exists. Someone should extend the docs...
