### ISSUE TITLE
Unable to load webpack.config.js on nx@17.0.0-rc

### ISSUE THREAD

**Issue by vcardins** [nrwl/nx#19716]
### Current Behavior

When I try to run any nx task, I get the error:

Unable to load `/<path_to_app>/webpack.config.js/<path_to_app>/apps/<app>/tsconfig.app.json: ENOTDIR: not a directory, stat '/<path_to_app>/webpack.config.js/<path_to_app>/apps/<app>/tsconfig.app.json'`

It used to work properly on `16.10.0`

### Expected Behavior

nx should perform any task correctly

### Steps to Reproduce

1. Migrate to nx 17 RC `nx migrate nx@17.0.0-rc.0  `
2. Run 'nx serve <app>'
3. The error is thrown

### Nx Report

```shell
NX   Report complete - copy this into the issue template

   Node   : 20.8.0
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx                 : 17.0.0-rc.0
   @nx/js             : 17.0.0-rc.0
   @nx/jest           : 17.0.0-rc.0
   @nx/linter         : 16.10.0
   @nx/eslint         : 17.0.0-rc.0
   @nrwl/linter       : 17.0.0-rc.0
   @nx/workspace      : 17.0.0-rc.0
   @nx/devkit         : 17.0.0-rc.0
   @nx/eslint-plugin  : 17.0.0-rc.0
   @nx/playwright     : 16.10.0
   @nx/react          : 17.0.0-rc.0
   @nrwl/tao          : 16.10.0
   @nx/web            : 17.0.0-rc.0
   @nx/webpack        : 16.10.0
   nx-cloud           : 16.4.0
   typescript         : 5.2.2
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/linter@16.10.0
     - @nx/playwright@16.10.0
     - @nrwl/tao@16.10.0
     - @nx/webpack@16.10.0
     - @nrwl/webpack@16.10.0
   
   To fix this, run `nx migrate nx@17.0.0-rc.0`
```

### Package Manager Version

node: v18.14.0 - npm: 9.3.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
@vcardins I tried it with latest RC and I could not reproduce. Can you please link your repository? It would be super helpful for me.

Steps I followed:

1. `npx create-nx-workspace@latest`, chose `React`, `Integrated`, `Webpack`
2. `nx serve` the React app
3. `nx migrate next` and run migrations etc
4. `nx serve` the React app, still works

**Comment by vcardins** [comment]
Thanks! What's the your node version?

**Comment by vcardins** [comment]
I haven't had the chance to create a repo yet but I noticed it happens if I have a custom `webpack.config`. 
this is the verbose message:
```
Error: Unable to load /<path_to_app>/webpack.config.js/<path_to_app>/apps/<app>/tsconfig.app.json: ENOTDIR: not a directory, stat '/<path_to_app>/webpack.config.js/<path_to_app>/apps/<app>/tsconfig.app.json'    at registerTsConfigPaths (/<path>/node_modules/nx/src/plugins/js/utils/register.js:115:19)
    at registerTsProject (/<path>/node_modules/nx/src/plugins/js/utils/register.js:15:9)
    at resolveCustomWebpackConfig (/Users/<path>/node_modules/@nx/webpack/src/utils/webpack/custom-webpack.js:6:64)
    at devServerExecutor (/<path>/node_modules/@nx/webpack/src/executors/dev-server/dev-server.impl.js:29:77)
    at devServerExecutor.next (<anonymous>)
    at getLastValueFromAsyncIterableIterator (/<path>/node_modules/nx/src/utils/async-iterator.js:13:27)
    at iteratorToProcessStatusCode (/<path>/node_modules/nx/src/command-line/run/run.js:41:94)
    at /<path>/node_modules/nx/src/command-line/run/run.js:154:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleErrors (/<path>/node_modules/nx/src/utils/params.js:9:16)
    ```
    I continue investigating

**Comment by mandarini** [comment]
My node version is `v18.18.0`. When you get a chance to create a super simple sample repo let me know and we'll solve this! :D

**Comment by vcardins** [comment]
@mandarini I realized that `nx migrate latest` doesn't update `@nrwl/webpack`, once I did that manually the issue was gone. Sorry for the confusion, all good now.
