### ISSUE TITLE
NX   Missing Platform Dependency

### ISSUE THREAD

**Issue by lzoubek** [nrwl/nx#19718]
### Current Behavior

I am not able to start fresh nx project using `npx create-nx-workspace@latest`

```
 >  NX   Missing Platform Dependency

   The Nx CLI could not find or load the native binary for your supported platform (linux-x64).
   This likely means that optional dependencies were not installed correctly, or your system is missing some system dependencies.
   For more information please see https://nx.dev/recipes/troubleshooting/troubleshoot-nx-install-issues


npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
npm WARN config `--include=optional` to include them.
npm WARN config
npm WARN config     Default value does install optional deps unless otherwise omitted.
/tmp/tmp-79656-w30KUtABmyJF/error.log (END)
```

### Expected Behavior

nx workspace is created

### Steps to Reproduce

1.

### Nx Report

```shell
no workspace => no report
```

### Package Manager Version

9.6.7

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Node v18.17.1
arch linux

**Comment by FrozenPandaz** [comment]
Have you consulted this guide to troubleshoot the error?

https://nx.dev/recipes/troubleshooting/troubleshoot-nx-install-issues

**Comment by lzoubek** [comment]
I did (previously several times). Now I tried again and it really helped.

For my case it was enough to put following content into my `.npmrc`
```
include=optional
```
I still think, this is more workaround than solution, because it has to be in global `.npmrc`
