### ISSUE TITLE
Error Creating Nextjs remote app with Angular as the host.

### ISSUE THREAD

**Issue by Alsmith141510** [nrwl/nx#19722]
### Current Behavior

I am learning Microfront end using Nx the sample given at this URL 

[](https://nx.dev/recipes/angular/dynamic-module-federation-with-angular#advanced-angular-micro-frontends-with-dynamic-module-federation)

I have the host app created using Angular and a remote app using Angular.  The above example works fine. I am trying to add a new app for creating Blog to this workspace and host app using nextjs. I am running into  issues below.

` npx nx g @nx/next:remote --name=blog --host=dashboard--dry-run`

>  NX  Generating @nx/next:remote

√ Which stylesheet format would you like to use? · scss
Could not find remote definitions at apps/home/src/remotes.d.ts. Did you generate this project with "@nx/react:host"?

### Expected Behavior

IT should create a nextjs remote app 

### Steps to Reproduce

1. Follow the step int he URL

[](https://nx.dev/recipes/angular/dynamic-module-federation-with-angular#advanced-angular-micro-frontends-with-dynamic-module-federation)

### Nx Report

```shell
no report generated
```

### Package Manager Version

 9.8.1

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

N/A

**Comment by Alsmith141510** [comment]
https://nx.dev/recipes/angular/dynamic-module-federation-with-angular#advanced-angular-micro-frontends-with-dynamic-module-federation

The URL did not show up above. I was trying the example in this URl.

**Comment by xiongemi** [comment]
unfortunately, this command would not if trying to create nextjs remote with an angular host. it currently only supports angular remote with angular host and react remote with react host.
to create a nextjs remote, you have to run the command without --host, then manually wire up the module federation. (see blog https://www.angulararchitects.io/en/blog/multi-framework-and-version-micro-frontends-with-module-federation-the-good-the-bad-the-ugly/).

1. run command `npx nx g @nx/next:remote --name=blog`

2. then in the nextjs app, add bootstrap to expose in the module-federation.config.js
in my module-federation.config.js, it will become:

```
module.exports = {
  name: 'react-app',
  exposes: {
    './Module': './src/remote-entry.ts',
    './web-components': './src/bootstrap.tsx'
  },
};
```

3. add to the angular host's module-federation.manifest.json
in angular host's module-federation.manifest.json, add an entry for nextjs remote (has to include remoteEntry.js at the end):
```
{
  "blog": "http://localhost:{your next js port}/remoteEntry.js"
}
```

4. create a wrapper component for nextjs app. i put the id="root" on the template:

```
import { AfterContentInit, Component } from '@angular/core';
import { loadRemoteModule } from '@nx/angular/mf';

@Component({
  template: '<div id="root"></div>',
})
export class WrapperComponent implements AfterContentInit {
  ngAfterContentInit(): void {
    loadRemoteModule('blog', './web-components')
      .then(() => console.debug('nextjs app loaded'))
      .catch((err: any) => console.error(`error loading nextjs app:`, err)); 
  }
}
```

and I also add this route to app.routes.ts:
```
  {
    path: 'blog,
    component: WrapperComponent
  },
```
now if you serve up the host and go to http://localhost:4200/blog, it should load the nextjs app.

**Comment by Alsmith141510** [comment]
Thanks for the update. localhost works fine but loading the next.js module from the angular host app gives me the error below.

core.mjs:10592 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'endsWith')
TypeError: Cannot read properties of undefined (reading 'endsWith')
    at nx-angular-mf.mjs:40:20
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:22:1)
    at asyncToGenerator.js:27:1
    at new ZoneAwarePromise (zone.js:1411:21)
    at asyncToGenerator.js:19:1
    at loadRemoteContainer (nx-angular-mf.mjs:28:35)
    at nx-angular-mf.mjs:18:17
    at Generator.next (<anonymous>)
    at resolvePromise (zone.js:1193:31)
    at resolvePromise (zone.js:1147:17)
    at zone.js:1260:17
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:10735:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:10735:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (core.mjs:11048:33)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:173:47) 

I have the routes in the angular host app as
// import { NxWelcomeComponent } from './nx-welcome.component';
import { Route } from '@angular/router';
import { loadRemoteModule } from '@nx/angular/mf';
import { HomeComponent } from './home/home.component';
export const appRoutes: Route[] = [
{
  path: 'aiblog',
  loadChildren: () =>
      loadRemoteModule('aiblog', './Module').then(
          (m) => m.RemoteEntryModule
       ),
},
{path:'',
redirectTo: '/home', pathMatch: 'full',
},
{path: 'home',
component: HomeComponent},
{
 path: 'login',
 loadChildren: () =>
     loadRemoteModule('login', './Module').then(
         (m) => m.RemoteEntryModule
      ),
},
];

**Comment by ndcunningham** [comment]
We do not currently have support or documentation for this stack, or mixing frameworks.

**Comment by ndcunningham** [comment]
For this stack, we do not currently have support or documentation.
You are free to fill out a feature request but I would not consider this a bug.

**Comment by xiongemi** [comment]
@Alsmith141510 do you have a repo for this error?

**Comment by Alsmith141510** [comment]
Yes

**Comment by xiongemi** [comment]
@Alsmith141510 what is the link to your rep?
