### ISSUE TITLE
Electron support

### ISSUE THREAD

**Issue by bennymeg** [nrwl/nx#1975]
Hi, 
I would like to contribute Electron schematic to Nx .

Before I start, I want to make sure you have not started to work on something like that and to ask your permission to start working on it.

I went through the majority of the code (which is pretty cool, I most say) and I believe I can implement the schematic with ease based on your other schematics.

Benny.

**Comment by vsavkin** [comment]
That's awesome. We aren't working on the electron support. So it would be great if you did it.

We are trying to contain the growth of the nrwl/nx repo for a few reasons: it's hard for us to guarantee the ease of upgrade if the number of packages keeps growing, and it makes the repo harder to manage. That's why we are encourage folks create Nx plugins in separate repos. We will still help you put it together, and will list it on the Nx readme and on nx.dev. What do you think?

**Comment by bennymeg** [comment]
That's great,
I will start working on it soon and I will keep you updated when it will be done.
I will try to keep the development style and guideline as close as possible so people that are familiar with nx code could understand it quickly and in case you would like to include it in the future.

do you have a preferred prefix for the package? I am thinking using something similar to Angular's ngx- prefix. how about nx-electron?

**Comment by bennymeg** [comment]
Hi, 
quick update,

I have implemented schematics for electron applications in a package named [Nx Electron](https://github.com/bennymeg/nx-electron).
I would love to hear everybody's opinions.

Benny.

**Comment by vsavkin** [comment]
@bennymeg that's great. I'll definitely check it out.

**Comment by FrozenPandaz** [comment]
Wow this is great!

Awesome job @bennymeg!

I have a branch with it working here :)

https://github.com/FrozenPandaz/nx-examples/tree/electron

Very very excited to see where this goes!

**Comment by skorunka** [comment]
This is something I'm eager for! Great job.

**Comment by megagru** [comment]
Hi. Are there any release plans?

**Comment by bennymeg** [comment]
Yes, next month.

**Comment by vsavkin** [comment]
Hey folks. Just wanted to let you know that Nx 8.12 will come with some tooling to make it easier to create and test Nx plugins. It should be out next week.

**Comment by bennymeg** [comment]
Sound great! I will check it out once it will be published.

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by bennymeg** [comment]
It took a little bit more then expected, but I am happy to say that [nx-electron](https://github.com/bennymeg/nx-electron) **v9.0.0** is out! 🎉

We have great adoption, and after 10k downloads, it's _safe_ to say the project is _stable_. 😊

- [(NPM) Download Page](https://www.npmjs.com/package/nx-electron)

**Comment by AsuScholar** [comment]
OMG!!! Just in time for a project that I am working on. This is GREAT! Will check it out

**Comment by s4m0r4m4** [comment]
I've been using nx-electron and contributing to it a bit, I'd say this issue can be closed.
