### ISSUE TITLE
vite:build copies package.json to outputPath

### ISSUE THREAD

**Issue by vergilfromadyen** [nrwl/nx#19758]
### Current Behavior

Current behavior defined here:
https://github.com/nrwl/nx/blob/master/packages/vite/src/executors/build/build.impl.ts#L103-L121

When `generatePackageJson` is set to `false`, `vite:build` insists that the output dir should still have a package.json. 

This is not desirable in cases where the outputPath is `{projectRoot}/dist` because this would mean that the `{projectRoot}/package.json` will match `{projectRoot}/dist/package.json` which makes `npm install` break with workspaces due to the conflicting names.

### Expected Behavior

No package.json is generated in the `dist` folder

### Steps to Reproduce

1. Create the following config:
```json
"buildLib": {
    "executor": "@nx/vite:build",
    "dependsOn": ["^build", "^buildLib"],
    "outputs": ["{options.outputPath}"],
    "options": {
        "outputPath": "{projectRoot}/dist",
        "skipTypeCheck": true,
        "force": false,
        "generatePackageJson": false,
    }
}
```
2. Run the `buildLib` task for a project

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.12.0
   OS     : darwin-arm64
   npm    : 8.19.1

   nx                 : 16.5.5
   @nx/js             : 16.5.5
   @nx/linter         : 16.5.5
   @nx/workspace      : 16.5.5
   @nx/devkit         : 16.5.5
   @nx/eslint-plugin  : 16.5.5
   @nrwl/tao          : 16.5.5
   @nx/vite           : 16.5.5
   @nx/webpack        : 16.3.2
   typescript         : 4.9.5
```

### Operating System

- [x] macOS
- [x] Linux
- [x] Windows
- [x] Other (Please specify)

**Comment by jsmecham** [comment]
This is causing problems for my usage, as well. Jest complains about multiple of the same version of packages.

**Comment by jsmecham** [comment]
> @jsmecham I'm currently working around this with a custom executor that wraps around Vite.

Awesome, thank you!
