### ISSUE TITLE
Support Karma for nx

### ISSUE THREAD

**Issue by fkolar** [nrwl/nx#19770]
## Description
There are allot of problem with Jest and when working with Firebase, thre are even more issues. and it cant be realy used to gether. 

Why do you even dropped support? 

## Motivation
Described above

## Suggested Implementation
It can be either schematics or just provide us with guide (manual steps) to remove JEST and add KARMA back

**Comment by fkolar** [comment]
OK I think I foudn [this](https://github.com/nrwl/nx/issues/1405)

**Comment by jaysoo** [comment]
Hey @fkolar , sorry to hear that you are running into issues with Jest and Firebase. We don't plan to add Karma support back in our generators. It is too slow for more projects, and the usage isn't as high as Jest, and even Vitest is surpassing Karma.

You can always install Karma manually.

```
npm install karma --save-dev
npm install karma-jasmine karma-chrome-launcher jasmine-core --save-dev
```

And then configure your project to use it. For example,

```json5
// apps/demo/project.josn
{
  "name: "demo",
  // ...
  "targets": {
    "test": {
      "command": "karma start",
      "options": { "cwd": "apps/demo" }
    },
    // ...
  }
}
```

So when you run `nx test demo`, it will run `karma start` from the project folder. You will need to add a Karma config file, etc. I recommend reading their docs: https://karma-runner.github.io/6.4/intro/installation.html.

Hope that helps.

**Comment by fkolar** [comment]
Thanks for the update. I use jest for any other project for in this case I forced to move to karma as JEST+Firebase JS API does not like each other. there is no fix on the horizon..
