### ISSUE TITLE
nx 17 regression: @nx/esbuild:esbuild with thirdParty: false and generatePackageJson: true doesn't populate dependencies in package.json

### ISSUE THREAD

**Issue by atsjo** [nrwl/nx#19773]
### Current Behavior

@nx/esbuild:esbuild with thirdParty: false and generatePackageJson: true doesn't populate dependencies in package.json for nx 17.0.x (tried 17.0.0 and 17.0.1).

It works fine with 16.10.0. The bundling done by esbuild is correct however, it doesn't bundle thirdParty packages, but fails to add those to package.json with nx 17. I used the same package manager (pnpm 8.9.2) when using both nx 16 and 17...

### Expected Behavior

@nx/esbuild:esbuild with thirdParty: false and generatePackageJson: true populates dependencies in package.json, as with nx 16.10.0

### Steps to Reproduce

1. use esbuild to bundle js project with thirdParty: false and generatePackageJson: true with external dependencies
2. observer that dependencies in package.json is not populated

### Nx Report

```shell
Node   : 20.8.1
   OS     : win32-x64
   pnpm   : 8.9.2

   nx                 : 17.0.1
   @nx/js             : 17.0.1
   @nx/jest           : 17.0.1
   @nx/linter         : 17.0.1
   @nx/eslint         : 17.0.1
   @nx/workspace      : 17.0.1
   @nx/angular        : 17.0.1
   @nx/cypress        : 17.0.1
   @nx/devkit         : 17.0.1
   @nx/esbuild        : 17.0.1
   @nx/eslint-plugin  : 17.0.1
   @nrwl/tao          : 17.0.1
   @nx/web            : 17.0.1
   @nx/webpack        : 17.0.1
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   angular-calendar : 0.31.0
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by maielo** [comment]
+1

**Comment by mattfysh** [comment]
this is the branch that needs to be run in order to add external deps to the generated package.json:
https://github.com/nrwl/nx/blob/ac038e353c32b96655aa8c6145d6d0666361fe76/packages/js/src/utils/package-json/update-package-json.ts#L63-L85

however I can't seem to find how to trigger it from the esbuild executor

**Comment by mattfysh** [comment]
this PR looks like it removed the feature? https://github.com/nrwl/nx/pull/19543

**Comment by atsjo** [comment]
I suspected this was removed as part of https://github.com/nrwl/nx/pull/19543, however the executor is not mentioned in the pull request. This is not used for building libraries (as also mentioned in the property description).

generatePackageJson:
"Generates a `package.json` and pruned lock file with the project's `node_module` dependencies populated for installing in a container. If a `package.json` exists in the project's directory, it will be reused with dependencies populated."

So I assume this is a mistake, I use it for bundling firebase functions, and had to roll back to 16.10.0...

**Comment by mattfysh** [comment]
I'd like to believe it's a mistake, but it looks like the esbuild test has been purposely removed in that PR. I can't seem to get a response on Slack either, nor can I find any info on why it was removed beyond the reference to the new linting rule that doesn't seem relevant to our build workflows. @jaysoo can you please ack this issue? Cheers

**Comment by mattfysh** [comment]
Cc @isaacplmann @meeroslav @Coly010 @JamesHenry @FrozenPandaz @ndcunningham @xiongemi

**Comment by jaysoo** [comment]
@mattfysh I need some clarifications, is this esbuild target for apps or libs? Because in Nx 16 we deprecated `package.json` generation for libs, and removed them in Nx 17. The current way to handle dependencies is through the lint rule (https://nx.dev/nx-api/eslint-plugin/documents/dependency-checks#dependency-checks-rule).

**Comment by mattfysh** [comment]
@jaysoo this is for apps, see earlier comments about docker and firebase workflows

**Comment by atsjo** [comment]
https://nx.dev/nx-api/esbuild/executors/esbuild#generatepackagejson

This property is still in your docs, and there has been no mention of this going await. The property deprecated and now removed is "updateBuildableProjectDepsInPackageJson"....

I use esbuild for bundling and then deploying to firebase functions (which is more or less the same as for @mattfysh , it's deployed to a docker image at google)

**Comment by jaysoo** [comment]
Yes, it should continue to be supported. We'll take a look.

**Comment by aovens-quantifi** [comment]
Thanks for picking this up @jaysoo, I'm also blocked on this

**Comment by bensijons** [comment]
I'm having the same issue with generatePackageJson: true, on version 17.1.2. The generated package.json is always empty.
