### ISSUE TITLE
Nx 17: Lerna packages dir cannot be used for generator dir

### ISSUE THREAD

**Issue by jerkovicl** [nrwl/nx#19795]
### Current Behavior

After upgrade to nx v17.0.1 angular library generator works with 'derived' option and not with 'as-provided' option, everything worked on v16.10

### Expected Behavior

I want to generate angular library with 'as-provided' option

### Steps to Reproduce

1.
![image](https://github.com/nrwl/nx/assets/5444153/42fc4dc1-1faa-4bac-a468-7011c528fa51)

### Nx Report

```shell
nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.18.0
   OS     : win32-x64
   npm    : 9.8.1

   nx (global)        : 17.0.1
   nx                 : 17.0.1
   @nx/js             : 17.0.1
   @nx/jest           : 17.0.1
   @nx/linter         : 17.0.1
   @nx/eslint         : 17.0.1
   @nx/workspace      : 17.0.1
   @nx/angular        : 17.0.1
   @nx/cypress        : 17.0.1
   @nx/devkit         : 17.0.1
   @nx/eslint-plugin  : 17.0.1
   @nx/plugin         : 17.0.1
   @nx/storybook      : 17.0.1
   @nrwl/tao          : 17.0.1
   @nx/web            : 17.0.1
   @nx/webpack        : 17.0.1
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc : 1.1.22
   @storybook/angular : 7.5.1
   ngx-build-plus     : 16.0.0
   ---------------------------------------
   Local workspace plugins:
         @fiyu/lib-toolkit
```

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Hi there @jerkovicl ! Thanks for filing an issue! Unfortunately I could not reproduce. Here's my output:
```
npx nx generate @nx/angular:library --name=katerina --buildable=true --directory=libs/katerina --publishable=true --importPath=@katerina/katerina --projectNameAndRootFormat=as-provided

>  NX  Generating @nx/angular:library

CREATE libs/katerina/project.json
CREATE libs/katerina/README.md
CREATE libs/katerina/ng-package.json
CREATE libs/katerina/package.json
CREATE libs/katerina/tsconfig.json
CREATE libs/katerina/tsconfig.lib.json
CREATE libs/katerina/tsconfig.lib.prod.json
CREATE libs/katerina/src/index.ts
CREATE libs/katerina/src/lib/katerina.module.ts
CREATE libs/katerina/jest.config.ts
CREATE libs/katerina/src/test-setup.ts
CREATE libs/katerina/tsconfig.spec.json
CREATE libs/katerina/.eslintrc.json
UPDATE tsconfig.base.json
```

Can you please provide a simple reproduction repository and the exact command that failed for you?

**Comment by jerkovicl** [comment]
@mandarini i run the same command as you ` nx g @nx/angular:library --name=jankec --buildable=true --publishable=true --importPath=@nas/jankec  --directory=libs/jankec  --projectNameAndRootFormat=as-provided --dry-run`

![image](https://github.com/nrwl/nx/assets/5444153/082db70f-fb46-4f0f-9fa2-d07f8d8ec9ee)

Working on creating repro

**Comment by jerkovicl** [comment]
@mandarini i have sent you a zip with repro on discord

**Comment by mandarini** [comment]
@jerkovicl I need to install them, because if I don't install the dependencies I will not be able to run the command.. :/

**Comment by jerkovicl** [comment]
@mandarini ok i understand, i thought you will run the command with npx as you did before

**Comment by mandarini** [comment]
Here's the actual issue: https://github.com/mandarini/nx-lerna-17-bug

**Comment by JamesHenry** [comment]
Thanks for the clear report @jerkovicl - we've diagnosed the issue on the nx core side and a fix will go up later today.

Please be aware that if you are using Nx 17 with lerna, you will still be pulling in nx 16 as well (because that's what lerna 7 depends on). If you're not seeing any issues then that's great, but something to be aware of.

We will be releasing lerna v8 soon which will depend on nx 17, it should be an easy migration

**Comment by jerkovicl** [comment]
@JamesHenry that's good news!
Yeah i didn't see any issues regarding publishing and versioning my libs so far.
