### ISSUE TITLE
17.0.1 stopped stating up module federation remotes

### ISSUE THREAD

**Issue by rbirkgit** [nrwl/nx#19812]
### Current Behavior

I updated from Nx 16.9.1 to 17.0.1. Before update we started our app with `nx serve myapp` and all module federaion remotes automatically started.

After migration to 17.0.1 remotes are no longer started. The console shows this:

```
 NX  Starting module federation dev-server for myapp with 0 remotes
```

### Expected Behavior

To work as with 16.9.1. I cannot see any breaking changes in the changelog.

### Steps to Reproduce

1.
nx serve

### Nx Report

```shell
Node   : 18.14.0
   OS     : win32-x64
   yarn   : 3.2.4

   nx                 : 17.0.1
   @nx/js             : 17.0.1
   @nx/jest           : 17.0.1
   @nx/linter         : 17.0.1
   @nx/eslint         : 17.0.1
   @nx/workspace      : 17.0.1
   @nx/angular        : 17.0.1
   @nx/cypress        : 17.0.1
   @nx/devkit         : 17.0.1
   @nx/eslint-plugin  : 17.0.1
   @nrwl/tao          : 17.0.1
   @nx/web            : 17.0.1
   @nx/webpack        : 17.0.1
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   ng-mocks : 14.11.0
```

### Package Manager Version

yarn 3.2.4

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Your `module-federation.config.ts` should be similar to this

```ts
import { ModuleFederationConfig } from '@nx/webpack';

const config: ModuleFederationConfig = {
  name: 'host',
  remotes: ['remote'], // <--- Add your remote here
};

export default config;
```
You need to add your remote name inside of your host in order for it to start the remote when your serve the host.
Can you try this and let me know if that worked?

**Comment by rbirkgit** [comment]
That made a difference. Strange it worked with 16.9 without the entries.

One difference still seems that now with nx serve it says starting up two remotes, but it doesn't start them in separate ports etc unless I also add `--devRemotes xxx`  With 16.9 we didn't need to.

**Comment by rbirkgit** [comment]
The Nx 17 release notes says `Enhancements to Module Federation Support` but I cannot find what that is. May be related.

**Comment by ndcunningham** [comment]
> That made a difference. Strange it worked with 16.9 without the entries.
> 
> One difference still seems that now with nx serve it says starting up two remotes, but it doesn't start them in separate ports etc unless I also add `--devRemotes xxx` With 16.9 we didn't need to.

If you list your remote inside of your host `module-federation.config.ts` they should be started statically on separate ports.
For example:
- host: http://localhost:4200
- remote1: http://localhost:4201
- remote2: http://localhost:4202

`--devRemotes` watches for file changes and updates the UI with the changes.

**Comment by ArgV04** [comment]
> ### Current Behavior
> I updated from Nx 16.9.1 to 17.0.1. Before update we started our app with `nx serve myapp` and all module federaion remotes automatically started.
> 
> After migration to 17.0.1 remotes are no longer started. The console shows this:
> 
> ```
>  NX  Starting module federation dev-server for myapp with 0 remotes
> ```
> 
> ### Expected Behavior
> To work as with 16.9.1. I cannot see any breaking changes in the changelog.
> 
> ### GitHub Repo
> _No response_
> 
> ### Steps to Reproduce
> 
> nx serve
> 
> ### Nx Report
> ```shell
> Node   : 18.14.0
>    OS     : win32-x64
>    yarn   : 3.2.4
> 
>    nx                 : 17.0.1
>    @nx/js             : 17.0.1
>    @nx/jest           : 17.0.1
>    @nx/linter         : 17.0.1
>    @nx/eslint         : 17.0.1
>    @nx/workspace      : 17.0.1
>    @nx/angular        : 17.0.1
>    @nx/cypress        : 17.0.1
>    @nx/devkit         : 17.0.1
>    @nx/eslint-plugin  : 17.0.1
>    @nrwl/tao          : 17.0.1
>    @nx/web            : 17.0.1
>    @nx/webpack        : 17.0.1
>    typescript         : 4.9.5
>    ---------------------------------------
>    Community plugins:
>    ng-mocks : 14.11.0
> ```
> 
> ### Failure Logs
> _No response_
> 
> ### Package Manager Version
> yarn 3.2.4
> 
> ### Operating System
> * [x]  macOS
> * [ ]  Linux
> * []  Windows
> * [ ]  Other (Please specify)
> 
> ### Additional Information
> _No response_

This issues still happen, when remotes are configured dynamically with manifest file. now with Nx 17 the remotes are not detected anymore and not served too.

**Comment by Coly010** [comment]
Fixed by this: https://github.com/nrwl/nx/pull/19894
