### ISSUE TITLE
Why is cypress builder copyFiles option deprecated?

### ISSUE THREAD

**Issue by remkoboschker** [nrwl/nx#1982]
Why is the cypress builder copyfiles option deprecated? And what would be an alternative for copying for instance .feature files to the output directory?

**Comment by vsavkin** [comment]
We switched to using webpack for bundling cypress specs. So all static assets imported into a spec will be resolved and bundled in by webpack.

**Comment by remkoboschker** [comment]
So how do I bundle the feature files for running them through the cypress-cucumber-preprocessor?

**Comment by remkoboschker** [comment]
After updating to the latest workspace I noticed the new index.js in de cypres plugins dir. I modified the code to include to cypress-cucumber-preprocessor loader in the webpack config following the config found here https://github.com/TheBrainFamily/cypress-cucumber-webpack-typescript-example/blob/master/cypress/webpack.config.js and I'm off to the races.
```
const { getWebpackConfig } = require('@nrwl/cypress/plugins/preprocessor');
const wp = require('@cypress/webpack-preprocessor');

module.exports = function(on, config) {
  const wpConfig = getWebpackConfig(config);
  wpConfig.node = { fs: 'empty', child_process: 'empty', readline: 'empty' };
  wpConfig.module.rules.push({
    test: /\.feature$/,
    exclude: [/node_modules/],
    use: [
      {
        loader: 'cypress-cucumber-preprocessor/loader'
      }
    ]
  });
  on('file:preprocessor', wp({ webpackOptions: wpConfig }));
};
```
