### ISSUE TITLE
workspace schematic path bug on windows

### ISSUE THREAD

**Issue by bennymeg** [nrwl/nx#1983]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

workspace schematic should work on windows

## Current Behavior

When creating a new workspace schematic and openning it on the console it fails (even without running it) due to incurrect path (probebly due to spaces in the path).

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create new angular + nestjs project with `npm init nx-workspace`
2. create new workspace schematic with angular console: generate > `@nrwl\workspace - workspace schematics`

### Context

Angular CLI: 8.3.3
Node: 10.15.3
OS: win32 x64
Angular: 8.2.11
Nx: 8.6.0

### Failure Logs

> Executing task: C:\Program Files\nodejs\npm.cmd run workspace-schematic -- test --dry-run --no-interactive

> C:\Program\ : The term 'C:\Program\' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:4
> + & {C:\Program\ Files\nodejs\npm.cmd run workspace-schematic -- test --d ...
> +    ~~~~~~~~~~~
> + CategoryInfo          : ObjectNotFound: (C:\Program\:String) [], CommandNotFoundException
> + FullyQualifiedErrorId : CommandNotFoundException

## Other

Probebly the problem is related to the fact the `Program Files` has space in it.

**Comment by vsavkin** [comment]
What command are you running in the terminal?

**Comment by bennymeg** [comment]
I am using Nrwl Angular Console to execute the schematic.

I believe that the command it's executing is:
`C:\Program Files\nodejs\npm.cmd run workspace-schematic -- test --dry-run --no-interactive`

**Comment by Greg5ki** [comment]
Getting the same behaviour.
`Executing task: c:\Code - Apps\berrystreetapps\node_modules\.bin\ng.cmd build referrals --sourceMap=false --statsJson <

c:\Code\ : The term 'c:\Code\' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At line:1 char:4
+ & {c:\Code\ -\ Apps\berrystreetapps\node_modules\.bin\ng.cmd build re ...
+    ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (c:\Code\:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

**Comment by Greg5ki** [comment]
Removed spaces from path and it works fine.

**Comment by edufranzoni** [comment]
I also have similar problems, because my user name (windows profile folder) has space. and i use @latest version.

when I run the 'npx create-nx-workspace myWorkspace' command, I get the error:

"
npm ERR! code ENOLOCAL
npm ERR! Could not install from "Franzoni \ AppData \ Roaming \ npm-cache \ _npx \ 9340" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR! C: \ Users \ Eduardo Franzoni \ AppData \ Roaming \ npm-cache \ _logs \ 2019-12-22T18_40_00_653Z-debug.log

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by FrozenPandaz** [comment]
Hi, this issue is very old and there's not enough information to act on it. If you are still experiencing this issue, please open a new issue with more steps to reproduce.
