### ISSUE TITLE
create-nx-workspace can create a workspace with missing jsdom dependency

### ISSUE THREAD

**Issue by igilham** [nrwl/nx#19853]
### Current Behavior

Creating a new standalone workspace sets up Vite with the `jsdom` environment but does not install `jsdom`, so it fails to run the sample test.

### Expected Behavior

Either don't use `jsdom` in the environment environment (the user did not ask for it) or install it so the out-of-box experience is not broken.

### Steps to Reproduce

```shell
npm i -g nx
npx create-nx-workspace workspace
> None
> Standalone
> Typescript? Yes or No
> Enable distributed caching? No

cd example
nx test example
MISSING DEP  Can not find dependency 'jsdom'
```

### Nx Report

```shell
NX   Report complete - copy this into the issue template

   Node   : 18.12.1
   OS     : darwin-arm64
   npm    : 9.6.1

   nx (global)        : 17.0.1
   nx                 : 17.0.1
   @nx/js             : 17.0.1
   @nx/linter         : 17.0.1
   @nx/eslint         : 17.0.1
   @nx/workspace      : 17.0.1
   @nx/devkit         : 17.0.1
   @nx/eslint-plugin  : 17.0.1
   @nrwl/tao          : 17.0.1
   @nx/vite           : 17.0.1
   typescript         : 5.1.6
```

### Failure Logs

```shell
MISSING DEP  Can not find dependency 'jsdom'
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

[Shared on discord](https://discord.com/channels/1143497901675401286/1166719292839034960).

**Comment by ndcunningham** [comment]
Hi, thanks for reporting this is an error on our end. 
You should see a fix in the next release.
