### ISSUE TITLE
[NestJs] Error while generating module with @nx/nest:module

### ISSUE THREAD

**Issue by dhutaryan** [nrwl/nx#19865]
### Current Behavior

Hello, when I try to generate nestjs module I get the error below

```
npx nx g @nx/nest:module core

Option "project" is deprecated: Provide The `directory` option instead and use the `as-provided` format. the project will be determined from the directory provided. it will be removed in nx v18.

 >  NX   createProjectRootMappingsFromProjectConfigurations is not a function
```

### Expected Behavior

Generate nestjs module

### Steps to Reproduce

1. Init  nx workspace with React as preset
2. Add NestJs project `nx g @nx/nest:application`
3. Run command `npx nx g @nx/nest:module core`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.17.0
   OS     : darwin-x64
   yarn   : 1.22.10
   
   nx                 : 16.8.1
   @nx/js             : 17.0.2
   @nx/jest           : 17.0.2
   @nx/linter         : 17.0.2
   @nx/workspace      : 17.0.2
   @nx/cypress        : 17.0.2
   @nx/devkit         : 17.0.2
   @nx/eslint-plugin  : 17.0.2
   @nx/nest           : 17.0.2
   @nx/node           : 17.0.2
   @nx/react          : 17.0.2
   @nrwl/tao          : 16.8.1
   @nx/vite           : 17.0.2
   @nx/web            : 17.0.2
   @nx/webpack        : 17.0.2
   nx-cloud           : 16.5.2
   typescript         : 5.1.6
```

### Package Manager Version

yarn

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

First, I had nx version 16.8.1. Than I updated it and got the same issue.

**Comment by oluizcarvalho** [comment]
I had the same with the CLI for Angular

![image](https://github.com/nrwl/nx/assets/51300546/245397ef-b451-4853-9ace-9c2558d8a94e)

**Comment by MCantu-PieFi** [comment]
I was able to resolve this by upgrading my nx package to: `"nx": "17.1.1"`

**Comment by junxiaotan** [comment]
https://nx.dev/nx-api/nest#nest-generators
I referred to this place and through some parameter debugging, I found that it can be used temporarily in this way

**Comment by thathurtabit** [comment]
I've just been seeing this, but had to make sure my `@nx/plugin` was the same version as the main `nx` package - haven't run into this problem since I've matched them up (`16.10.0` in my case)

**Comment by FrozenPandaz** [comment]
Yes, please align the version of `nx` with the other `@nx/*` packages.
