### ISSUE TITLE
@nx/express plugin not generating package.json

### ISSUE THREAD

**Issue by udaya-reddy** [nrwl/nx#19896]
### Current Behavior

![image](https://github.com/nrwl/nx/assets/67152550/7edef7d9-10b9-424e-898f-dec5d2321e1b)

### Expected Behavior

package.json is also expected. Tried with version 17.0.2 and 16.10.0 of @nx/express.

### Steps to Reproduce

1. install @nx/express@latest or @nx/express@16.10.0 
2. npx nx g @nx/express:application 
the above output is getting generated.

### Nx Report

```shell
not sure where this is.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Thanks for reporting.
As a workaround and probably the intended way moving forward is to use `@nx/node`

So in your scenario it would be `@nx/node:app --framework=express`

**Comment by udaya-reddy** [comment]
Tried. that too. it does not generate package.json. even if I did a npm init and created one. npm install does not generate package-lock.json 
and whey I try to run  nx run app:serve
> nx run test1-service:serve:development

node:fs:600
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'package-lock.json'
