### ISSUE TITLE
NX Cannot find module '@nx/nx-darwin-x64' on Mac M1 chip

### ISSUE THREAD

**Issue by sazx85** [nrwl/nx#19892]
### Current Behavior

Got error during commit.
NX Cannot find module '@nx/nx-darwin-x64' on Mac M1 chip

Started after update from nx 15.9.4

### Expected Behavior

Commit should work

### Steps to Reproduce

1. Deleted node modules
2. Cleared npm cache
3. Deleted package-lock.json
4. npm i
5. Try to do commit

### Nx Report

```shell
Report complete - copy this into the issue template

   Node   : 18.18.2
   OS     : darwin-arm64
   npm    : 9.8.1
   
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/angular        : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/nest           : 16.10.0
   @nx/node           : 16.10.0
   @nx/storybook      : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/webpack        : 16.10.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @ionic/angular     : 6.7.2
   @storybook/angular : 7.5.1
```

### Failure Logs

```shell
husky > pre-commit (node v18.18.2)
Creating/updating nx project graph...
 >  NX   Cannot find module '@nx/nx-darwin-x64'
   Require stack:
 node_modules/nx/src/native/index.js
 node_modules/nx/src/utils/workspace-context.js
 node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js
 node_modules/nx/src/config/workspaces.js
 node_modules/nx/src/utils/nx-plugin.js
 node_modules/nx/src/project-graph/build-project-graph.js
 node_modules/nx/src/project-graph/project-graph.js
husky > pre-commit hook failed (add --no-verify to bypass)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by expcapitaldev** [comment]
root reason inside 
`node_modules/nx/src/native/index.js`, 
`const { platform, arch } = process`
macos M2 chip

`node -p 'process.arch'` -> arm64 but inside NX `node_modules/nx/src/native/index.js` we can see platform: darwin, arch: x64 not arm64

**Comment by expcapitaldev** [comment]
also https://nx.dev/recipes/troubleshooting/troubleshoot-nx-install-issues#supported-native-module-platforms

`Supported native module platforms
We publish modules for the following platforms:

macOS 11+ (arm64, x64)
Windows (arm64, x64)
We use the msvc target, so as long as Microsoft supports your Windows version, it should work on it
Linux (arm64, x64)
We use gnu ang musl targets, which are used by the most popular Linux distributions
FreeBSD (x64)
If you're running a machine that isn't part of the list above, then Nx does not support it at this time. [Please open an issue on GitHub](https://github.com/nrwl/nx/issues/new/choose) if you feel Nx should support that platform and we will assess what can be done, please make sure to include your platform and architecture in the issue.`

**Comment by expcapitaldev** [comment]
issue found in case which not related to NX, I think issue not actual and should be closed
