### ISSUE TITLE
Add libs to Package-based project

### ISSUE THREAD

**Issue by quanghd0102** [nrwl/nx#19895]
Hi, i'm newbie with nx. I created Package-based project with nx  and added some packages. After that, I want to create library with @nx/react and use it inside my packages but it always show error "Cannot find module".
How can I do this case?

**Comment by fsgreco** [comment]
Hi @quanghd0102, you should first install the plugin inside your package-based monorepo, install it globally: `npm install @nx/react -W`.  
Afterwards you can create your lib or app, like this: 
```bash
npx nx g @nx/react:app frontend --directory packages/frontend --routing 
```

**beware** you should at least use `--directory packages/frontend` option and it will prompt you with the choice of how to call the project and where to place it. If you don't specify `--directory` it will create the folder at the root of the project (I already opened a bug about this here: https://github.com/nrwl/nx/issues/21001  )

**Comment by FrozenPandaz** [comment]
Thank you for answer the question @fsgreco. Marking this as answered.
