### ISSUE TITLE
Instructions for installing through pnpm are missing

### ISSUE THREAD

**Issue by MathurAditya724** [nrwl/nx#19918]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

All the overview pages of API's cards, like react, next, nuxt, express, etc. 

### Additional context or description

- [ ] The layout is not the same for all these pages, some are in tabs, and others are in a single box or multiple boxes.
- [ ] Instructions for installing using pnpm is missing

**Comment by MathurAditya724** [comment]
Sorry to disturb you @AgentEnder, but can you tell if there is any update on this?

**Comment by AgentEnder** [comment]
Just looks like its waiting for review, thanks for the contribution 🎉
