### ISSUE TITLE
Unable to access shared libs from cypress shared lib

### ISSUE THREAD

**Issue by rpanigra18** [nrwl/nx#19912]
### Current Behavior

Before NX upgrade, I was able to access app shared libs from Cypress shared lib (both in lib folder)

Post NX upgrade, mid of 2023, I can reference my shared libs with each other however I am unable to refer to a shared lib in Cypress shared lib - all under libs folder. 

### Expected Behavior

Cypress shared lib should be able to access NX shared libs that have my core modules.

### Steps to Reproduce

 I am unable to control my app by referencing my shared libs in my Cypress shared lib. It used to work prior to NX upgrade.

I had opened an issue but went on a long break and issue was closed. I have provided more details on this one, @barbados-clemens thanks for your response on the last issue, please respond when you get time. The important aspect here is, I am referencing my shared lib in test shared lib (all under libs folder)

### Nx Report

```shell
Node   : 21.1.0
   OS     : win32 x64
   yarn   : 1.22.19
   Hasher : Native

   nx                 : 16.2.1
   @nx/js             : 16.2.1
   @nx/jest           : 16.2.1
   @nx/linter         : 16.2.1
   @nx/workspace      : 16.2.1
   @nx/cypress        : 16.2.1
   @nx/devkit         : 16.2.1
   @nx/eslint-plugin  : 16.2.1
   @nx/react          : 16.2.1
   @nrwl/tao          : 16.2.1
   @nx/web            : 16.2.1
   @nx/webpack        : 16.2.1
   @nrwl/webpack      : 17.0.2
   nx-cloud           : 16.0.5
   typescript         : 5.2.2
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/webpack@17.0.2

   To fix this, run `nx migrate nx@17.0.2`
```

### Package Manager Version

npm

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Please provide a minimal reproduction or, at the very least, clear reproduction steps that lead to creating a workspace where the issue can be reproduced.
