### ISSUE TITLE
jest config globals ts-jest set in preset

### ISSUE THREAD

**Issue by remkoboschker** [nrwl/nx#1993]
I would like to set the ts-jest options and two PR's have worked on this. It works if I put the config in the project root. But I cannot put it in the jest config in the root of the workspace that is imported in the preset property of the jest config in the project root.

**Comment by jdpearce** [comment]
Hi @remkoboschker, I've just had a PR merged into Jest which addresses this. I'm not sure what their release cycle is, but I expect it to be fixed in the next release! 🤞

cf. https://github.com/facebook/jest/pull/9027

**Comment by remkoboschker** [comment]
@jdpearce thanks. Will test.
