### ISSUE TITLE
nx affected:lint calls wrong git diff command

### ISSUE THREAD

**Issue by kroeder** [nrwl/nx#1994]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Running ```nx affected:lint "C:/plattform/solution-manager/package.json"``` should work

## Current Behavior

Running ```nx affected:lint "C:/plattform/solution-manager/package.json"``` throws an error 

```
Error: Command failed: git diff --name-only --relative C:/plattform/solution-manager/package.json undefined
fatal: undefined: no such path in the working tree.
```

Originally I found this error by running husky / lint-staged
```
    "husky": {
        "hooks": {
            "pre-commit": "lint-staged"
        }
    },
    "lint-staged": {
        "*": [
            "npm run affected:lint --parallel --fix", // <---- this breaks
            "npm run format:write",
            "git add"
        ]
    },
```

## Failure Information (for bugs)

I debugged `nx.js` with arguments `affected:lint "C:/plattform/solution-manager/package.json"` and ran into this line:

*@nrwl/workspace/src/command-line/shared.js:85*
![image](https://user-images.githubusercontent.com/5478899/67566327-ca388e00-f727-11e9-8586-886fcbd48923.png)

The `options` object looks like this: 
```
{
  "_": [
    "affected:lint",
    "C:/plattform/solution-manager/package.json"
  ],
  "help": false,
  "version": false,
  "quiet": false,
  "parallel": false,
  "only-failed": false,
  "onlyFailed": false,
  "maxParallel": 3,
  "exclude": [],
  "$0": "node_modules\\@nrwl\\cli\\bin\\nx.js",
  "target": "lint"
}
```

The first thing I noticed is:
```
    else if (options._.length >= 2) {
        return {
            files: getFilesFromShash(options._[1], options._[2])
        };
    }
``` 
isn't correct. If `options._.length === 2` then `options._[2]` is undefined (which causes the error)
Also, `options._[0]` is the command itself and not a file but the command expects 2 file names

```
function getFilesFromShash(sha1, sha2) {
    return parseGitOutput(`git diff --name-only --relative ${sha1} ${sha2}`);
}
```

I also noticed that every destructed object is undefined
```
function parseFiles(options) {
    const { files, uncommitted, untracked, base, head } = options;
```

### Steps to Reproduce

It's a private repo. If necessary I can try to reproduce it by configuring a new project similar to my existing one

### Context

```
  @nrwl/angular : 8.7.0
  @nrwl/cli : 8.7.0
  @nrwl/cypress : 8.7.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.7.0
  @nrwl/linter : 8.7.0
  @nrwl/nest : 8.7.0
  @nrwl/next : Not Found
  @nrwl/node : 8.7.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.7.0
  @nrwl/web : Not Found
  @nrwl/workspace : 8.7.0
  typescript : 3.5.3
```

I can contribute a fix if this is a bug and not a misconfiguration on my side. I just don't know what exactly causes this. 

*Additionally* 
This command succeeds like 70%~ of the time. 30%~ of the time it prevents me from committing (without --no-verify)

**Comment by FrozenPandaz** [comment]
I believe the option you are looking for is the following:

https://nx.dev/web/api/workspace/npmscripts/affected#files

```bash
affected:lint --files="C:/plattform/solution-manager/package.json"
```

Please reopen this issue if that does not work for you.

**Comment by kroeder** [comment]
I believe my description was misleading. I don't want to run this manually (using --files)

My original issue is
```
    "lint-staged": {
        "*": [
            "npm run affected:lint --parallel --fix",
            "npm run format:write",
            "git add"
        ]
    },
``` doesn't work.

That is because `npm run affected:lint` does fail because it tries to run 
```
Error: Command failed: git diff --name-only --relative C:/plattform/solution-manager/package.json undefined
fatal: undefined: no such path in the working tree.
``` 
internally.

I could reproduce this by executing this command 
```
nx affected:lint "C:/plattform/solution-manager/package.json"
```

**Comment by kroeder** [comment]
@FrozenPandaz I can't re-open issues. Can you take a look at my response, please?
https://github.com/nrwl/nx/issues/1994#issuecomment-549370746

**Comment by Lonli-Lokli** [comment]
@FrozenPandaz @kroeder Is this issue still active

**Comment by alexandrzavalii** [comment]
Yes it is.
I am not able to run eslint against staged files in lint-staged.
