### ISSUE TITLE
Generator Paths: Nx 16.8 / Nx 17.0 / projectNameAndRootFormat + nameAndDirectoryFormat

### ISSUE THREAD

**Issue by ctjhoa** [nrwl/nx#19946]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

I use Nx since v14/v15 and so many of my projects rely on `derived` generation paths.

In [Nx 16.8](https://blog.nrwl.io/nx-16-8-release-e38e3bb503b5#b353) blog post, it was advertise as "add this line to your `nx.json`" using `projectNameAndRootFormat` 
```json
  "workspaceLayout": {
    "projectNameAndRootFormat": "derived",
    "appsDir": "apps",
    "libsDir": "libs"
  },
```

Then **one month later**, in [Nx 17.0](https://blog.nrwl.io/nx-17-0-has-landed-1dad19176ff3#c31a) blog post, it was advertise as "we’ve added a new `--nameAndDirectoryFormat` option"

Those new generator paths were very poorly brought to the Nx community because in one month we were given 2 completely different information and **none of them are actually reliable**.

After some issue digging during my Nx project migration to v17.0, I stumbled upon [this issue](https://github.com/nrwl/nx/issues/19525#issuecomment-1763929841) explaining that `projectNameAndRootFormat` is now an option per generator and no longer project wide.

So what about the `nameAndDirectoryFormat`? So it seems to be only available for [nest generator](https://nx.dev/nx-api/nest/generators/interface#nameanddirectoryformat) at the time of writing.

Why a single generator has a different option for it? ¯\_(ツ)_/¯
Others seem to still rely on [projectNameAndRootFormat](https://nx.dev/nx-api/js/generators/library#projectnameandrootformat)
![2023-10-31-155928_1725x342_scrot](https://github.com/nrwl/nx/assets/1716173/ac62cc28-7640-4bd2-82e1-776bb251e19c)

Worst, the only correct documentation is [this one](https://nx.dev/deprecated/workspace-layout#workspace-layout-and-projectnameandrootformat) but has been categorized in "Deprecated".

I know documentation is hard but come on, Nx is suppose to automate migration and IMO this was a perfect case for a migration patch.

### Is there a specific documentation page you are reporting?

- https://blog.nrwl.io/nx-16-8-release-e38e3bb503b5#b353
- https://blog.nrwl.io/nx-17-0-has-landed-1dad19176ff3#c31a
- https://nx.dev/nx-api/nest/generators/interface#nameanddirectoryformat
- https://nx.dev/deprecated/workspace-layout#workspace-layout-and-projectnameandrootformat (**mark as deprecated where it's not**)
- https://github.com/nrwl/nx/issues/19525#issuecomment-1763929841

### Additional context or description

After tests and from my current understanding, the right way to structure your project with new generator path is to use [this deprecated documentation](https://nx.dev/deprecated/workspace-layout#workspace-layout-and-projectnameandrootformat)
```json
  "workspaceLayout": {
    "appsDir": "apps",
    "libsDir": "libs"
  },
  "generators": {
    "@nx/node": {
      "application": {
        "projectNameAndRootFormat": "derived"
      },
      "library": {
        "projectNameAndRootFormat": "derived"
      }
    },
    "@nx/react": {
      "application": {
        "projectNameAndRootFormat": "derived"
      },
      "library": {
        "projectNameAndRootFormat": "derived"
      }
    }
  }
```
except `nest` which has a different option `nameAndDirectoryFormat`

**Comment by ctjhoa** [comment]
Addendum:
`nx g component --help` show `nameAndDirectoryFormat` as an option so. Are we suppose to add both?
![2023-10-31-152825_1916x626_scrot](https://github.com/nrwl/nx/assets/1716173/32d5b305-4e9b-421f-899d-27ec5db1dac2)

**Comment by ctjhoa** [comment]
Documentation updated since https://github.com/nrwl/nx/pull/19861
https://nx.dev/deprecated/as-provided-vs-derived

but still deprecated

**Comment by isaacplmann** [comment]
I agree with a lot of what you're saying.

- We did change our mind between 16.8.0 and 17.0.0.  I'm sorry for the confusion that caused.
- We have two different flags because `--projectNameAndRootFormat` is for project generators (i.e. [library](https://nx.dev/nx-api/nest/generators/library)) and `--nameAndDirectoryFormat` is for every other generator (i.e. [pipe](https://nx.dev/nx-api/nest/generators/pipe)).  Is this distinction not clear enough in the [new docs](https://nx.dev/deprecated/as-provided-vs-derived)?
- The documentation is in the deprecated section because the `derived` way of calculating names/paths is deprecated and won't be available in Nx 18.

If you want to stick to the derived method in Nx 17, you'll either need to answer the prompt every time or specify defaults for every generator that you use:

```
  "workspaceLayout": {
    "appsDir": "apps",
    "libsDir": "libs"
  },
  "generators": {
    "@nx/nest": {
      "application": {
        "projectNameAndRootFormat": "derived"
      },
      "library": {
        "projectNameAndRootFormat": "derived"
      },
      "pipe": {
        "nameAndDirectoryFormat": "derived"
      }
    },
    "@nx/react": {
      "application": {
        "projectNameAndRootFormat": "derived"
      },
      "library": {
        "projectNameAndRootFormat": "derived"
      },
      "component": {
        "nameAndDirectoryFormat": "derived"
      }
    }
  }
```
