### ISSUE TITLE
The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by Lightw3ight** [nrwl/nx#19969]
### Current Behavior

My repo was running NX 15 and Angular 15

I recently updated NX to v17 using the `interactive` command so I could upgrade independently of  Angular as I cannot upgrade Angular yet because of release cycles

I am now trying to upgrade Angular to v16 using `nx migrate` on angular core, cli and cdk and that seemed to work fine

However now I am unable to build any libraries without getting the error
`The "path" argument must be of type string. Received undefined`

I have even tried creating a new library in my monorepo to see if something wasn't upgraded properly in my existing libraries but I get the same issue trying to build that too

### Expected Behavior

Builds should run as usual

### Steps to Reproduce

1. Migrate repo to use NX 17 using `nx migrate latest --interactive` and opting to not migrate angular libs
2. Run `nx migrate @angular/core@latest`
3. Run `nx migrate --run-migrations`
4. Run `nx migrate @angular/cli@latest`
5. Run `nx migrate --run-migrations`
6. Run `nx migrate @angular/cdk@latest`
7. Run `nx migrate --run-migrations`
8. Try to build any library

### Nx Report

```shell
Node   : 16.20.0
   OS     : win32-x64
   npm    : 8.19.4

   nx (global)        : 17.0.2
   nx                 : 17.0.2
   @nx/js             : 17.0.2
   @nx/jest           : 17.0.2
   @nx/linter         : 17.0.2
   @nx/eslint         : 17.0.2
   @nx/workspace      : 17.0.2
   @nx/angular        : 17.0.2
   @nx/cypress        : 17.0.2
   @nx/devkit         : 17.0.2
   @nx/eslint-plugin  : 17.0.2
   @nx/plugin         : 17.0.2
   @nrwl/tao          : 17.0.2
   @nx/web            : 17.0.2
   @nx/webpack        : 17.0.2
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   @auth0/auth0-angular           : 1.9.0
   @infragistics/igniteui-angular : 15.1.26
   @ngrx/component-store          : 16.3.0
   @ngrx/effects                  : 16.3.0
   @ngrx/entity                   : 16.3.0
   @ngrx/store                    : 16.3.0
   @ngrx/store-devtools           : 16.3.0
   devextreme-angular             : 22.2.6
   ng2-charts                     : 3.0.8
   nx-stylelint                   : 13.5.3
   ---------------------------------------
   Local workspace plugins:
         @vista/workspace-extensions
```

### Failure Logs

```shell
Building Angular Package

------------------------------------------------------------------------------
Building entry point '@company/aspect-app-config'
------------------------------------------------------------------------------
✖ Compiling with Angular sources in Ivy partial compilation mode.

 >  NX   The "path" argument must be of type string. Received undefined


TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at Object.dirname (node:path:654:5)
    at C:\projects\company-front-end\node_modules\@nx\angular\src\executors\package\ng-packagr-adjustments\ng-package\entry-point\compile-ngc.transform.js:52:30
    at C:\projects\company-front-end\node_modules\ng-packagr\lib\graph\transform.js:7:35
    at C:\projects\company-front-end\node_modules\rxjs\dist\cjs\internal\operators\switchMap.js:17:35
    at OperatorSubscriber._this._next (C:\projects\company-front-end\node_modules\rxjs\dist\cjs\internal\operators\OperatorSubscriber.js:33:21)
    at OperatorSubscriber.Subscriber.next (C:\projects\company-front-end\node_modules\rxjs\dist\cjs\internal\Subscriber.js:51:18)
    at C:\projects\company-front-end\node_modules\rxjs\dist\cjs\internal\operators\switchMap.js:17:192
    at OperatorSubscriber._this._next (C:\projects\company-front-end\node_modules\rxjs\dist\cjs\internal\operators\OperatorSubscriber.js:33:21)

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target build for project aspect-app-config and 1 task it depends on failed

   Failed tasks:

   - aspect-app-config:build:production

   Hint: run the command with --verbose for more details.

   View structured, searchable error logs at https://nx.app/runs/xyz
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Lightw3ight** [comment]
So it turns out I hadnt updated `ng-packagr` to the latest version, updating that fixed the issue
On a side note, this probably wouldn't have happened if there was a "update angular" kind of command that could independently update angular in a repo that has already had nx updated. If such a thing exists, please let me know :)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Migrating individual `@angular/*` packages manually is not recommended. Doing so can result in what you experienced, forgetting to update some packages which lead to issues. When you opt-out of optional package updates (e.g. run `nx migrate latest --interactive` and skip angular updates), you need to run the migrate command using the `--from` option. This is explained in the docs https://nx.dev/recipes/tips-n-tricks/advanced-update#updating-dependencies-that-are-behind-the-versions-nx-manages.

That's the correct way to update packages that were skipped in previous migrations. There's no Angular-specific command to update because Nx is not an Angular-only CLI, but rather a general-purpose CLI. As explained above, you can still update Angular following the instructions contained in the linked docs.

I'm going to close this since the proper process to migrate the packages was not followed. If you find an issue following that process, please feel free to create a new issue providing the details.
