### ISSUE TITLE
Playwright with Cucumber Setup Option

### ISSUE THREAD

**Issue by barrymichaeldoyle** [nrwl/nx#19970]
## Description
Now that we have `playwright` support, it would be great if it was possible to incorporate BDD using features files with `@cucumber/cucumber`.

## Motivation
Some companies I've worked with like to make use of `feature` files to ensure their business logic can be tested.

## Suggested Implementation
It would be great if we have an option during the playwright setup to include support for `cucumber`.

## Alternate Implementations
Right now I have to manually set that up, but my main problem with it is I've spent 2 days trying to get this right and I can't get it to work in my nx repo, I'm not sure what to do so I'm sure others might be running into this problem too.

Here's a copy paste from my issues I was facing that I posted on the NX Discord server:

I've successfully managed to get Playwright working with NX thanks to the new official nx playwright plugin. But I'm having a lot of issues trying to setup cucumber.

I keep getting this error:

> You're calling functions (e.g. "Given") on an instance of Cucumber that isn't running.
>          This means you have an invalid installation, mostly likely due to:
>          
> Cucumber being installed globally
> A project structure where your support code is depending on a different instance of Cucumber
>      Either way, you'll need to address this in order for Cucumber to work.
>      See https://github.com/cucumber/cucumber-js/blob/main/docs/installation.md#invalid-installations

I have the feeling it is my issue with the the project structure. Not sure if I need to add a cucumber.json file and if so do I do it at the root level or at the app level?

**Comment by rphmee-lo** [comment]
I've also run into this issue trying to setup NX + Playwright + Cucumber. I found the [playwright-bdd](https://vitalets.github.io/playwright-bdd/#/getting-started) package which seems to allow this to work. I only have it running in a toy project at the moment so I don't know if it'll run into issues down the line, but here's the basic setup I used in a project that tests a frontend and backend together:

apps/react-monorepo-e2e/project.json
```
{
  "name": "react-monorepo-e2e",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "projectType": "application",
  "sourceRoot": "apps/react-monorepo-e2e/src",
  "targets": {
    "serve-all": {
      "executor": "nx:run-commands",
      "options": {
        "commands": [
          {
            "command": "nx run next-api:serve"
          },
          {
            "command": "nx run react-monorepo:serve"
          }
        ],
        "parallel": true,
        "readyWhen": "Application is running"
      }
    },
    "e2e": {
      "executor": "@nx/playwright:playwright",
      "outputs": ["{workspaceRoot}/dist/.playwright/apps/react-monorepo-e2e"],
      "options": {
        "config": "apps/react-monorepo-e2e/playwright.config.js"
      }
    },
    "lint": {
      "executor": "@nx/eslint:lint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["apps/react-monorepo-e2e/**/*.{js,ts}"]
      }
    }
  },
  "implicitDependencies": ["react-monorepo"]
}
```

apps/react-monorepo-e2e/playwright.config.js
```
import { defineConfig } from '@playwright/test';
import { nxE2EPreset } from '@nx/playwright/preset';
import { defineBddConfig } from 'playwright-bdd';
import { workspaceRoot } from '@nx/devkit';

// For CI, you may want to set BASE_URL to the deployed application.
const baseURL = process.env['BASE_URL'] || 'http://localhost:4200';

const testDir = defineBddConfig({
  paths: ['./src/features/*.feature'],
  require: ['./src/steps/*.ts'],
});

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();

/**
 * See https://playwright.dev/docs/test-configuration.
//  */
export default defineConfig({
  ...nxE2EPreset(__filename, { testDir }),
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    headless: false, //true
    viewport: { width: 1920, height: 1080 }, //1280x720
    launchOptions: {
      slowMo: 1000,
    },
    video: 'on',
    screenshot: 'only-on-failure',
    baseURL,
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },
  /* Run your local dev server before starting the tests */
  webServer: {
    command: 'npx nx run react-monorepo-e2e:serve-all',
    url: 'http://localhost:4200',
    reuseExistingServer: !process.env.CI,
    cwd: workspaceRoot,
  },
  testDir,
});
```

apps/react-monorepo-e2e/features/sample.feature
```
Feature: Playwright site

    Scenario: Check running app
        Given I open url "http://localhost:4200/"
        Then I see "Welcome Hello API"
```

apps/react-monorepo-e2e/steps/sample.steps/ts
```
import { expect } from '@playwright/test';
import { createBdd } from 'playwright-bdd';

const { Given, When, Then } = createBdd();

Given('I open url {string}', async ({ page }, url) => {
  await page.goto(url);
});

When('I click link {string}', async ({ page }, name) => {
  await page.getByRole('link', { name }).click();
});

Then('I see in title {string}', async ({ page }, keyword) => {
  await expect(page).toHaveTitle(new RegExp(keyword));
});

Then('I see {string}', async ({ page }, keyword) => {
  await expect(page.getByText(new RegExp(keyword))).toBeVisible();
});

```

root/package.json
```
{
  ...
  "scripts": {
      "test-e2e": "cd ./apps/react-monorepo-e2e && npx bddgen && nx run react-monorepo-e2e:e2e"
   },
  ...
}
```

**Comment by vitalets** [comment]
@rphmee-lo thanks for sharing your solution.
You can also run `bddgen` as a dependency of `e2e` target, I've added [some docs](https://vitalets.github.io/playwright-bdd/#/recipes?id=usage-with-nx) on that.

**Comment by gnuechtel** [comment]
Recently, nx-cucumber has been submited by myself to Nx (see PR #20381).
It is using the Cucumber API for JavaScript as test runner (from `@cucumber/cucumber`).
Version 1.0.0 is coming soon. Besides small changes, it is feature-complete.
Still waiting for feedback from Nx.

You can try it here: https://www.npmjs.com/package/@gnuechtel/nx-cucumber
The [quickstart](https://www.npmjs.com/package/@gnuechtel/nx-cucumber#quick-start) works out of the box for playwright. Just try it out and please give me feedback!

BTW: bdd-playwright is also a great tool. It uses Playwright Test instead of Cucumber. Some people say, the developer experience is greater, but Cucumber also has its advantages. However, for the next major version of nx-cucumber I want to write a generator for [bdd-playwright and others](https://gitlab.com/gnuechtel/open-source/-/issues/13). Since it is an open source project, of course everybody is invited to contribute.

**Comment by phramusca** [comment]
I also faced the issue, and for info, it was really due to the fact that I had a @cucumber/cumber installed also globally ... as stated on the error message
Check :
npm list -g @cucumber/cucumber
(you can also check `npm list -g cucumber`)

and remove:
npm uninstall -g @cucumber/cucumber

**Comment by FrozenPandaz** [comment]
@gnuechtel Thank you for working on a plugin for the community! I'm going to mark this issue as closed. Please use https://www.npmjs.com/package/@gnuechtel/nx-cucumber :tada:
