### ISSUE TITLE
`disk` as fallback version resolver in `nx release version`

### ISSUE THREAD

**Issue by guysenpai** [nrwl/nx#19971]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Whether `registry` or `git-tag` version resolver failed, fallback to `disk` version resolver instead throw error

## Motivation

For the first release or publish, `registry` and `git-tag` will throw an error because there is no existing tag and package in the registry

## Suggested Implementation

 For `registry` version resolver

```ts
try {
  // Must be non-blocking async to allow spinner to render
  currentVersion = await new Promise<string>((resolve, reject) => {
    exec(`npm view ${packageName} version --registry=${registry} --tag=${tag}`, (error, stdout, stderr) => {
      if (error) {
        return reject(error);
      }
      if (stderr) {
        return reject(stderr);
      }
      return resolve(stdout.trim());
    });
  });
} catch (error) {
  currentVersion = currentVersionFromDisk;
}
```

for `git-tag` version resolver

```ts
if (!latestMatchingGitTag) {
  currentVersion = currentVersionFromDisk;
}
```

**Comment by JamesHenry** [comment]
Hmm I'm not sure about this one... I may be want you want that _one time_, but the rest of the time I think using `disk` when you've said you don't want that would be undesired behaviour.

I think this might be one of those cases where it is just on the user to get their very first release into the registry and then the registry or git-tag resolvers can take it from there.

E.g. You could just start with `disk` in your first commit, and then change it to registry or git-tag in a follow up right?

I feel like falling back to `disk` when that's not desired is more of a downside than not accommodating this one case, but I won't close this yet in case you have further ideas in this area or have any thoughts on what I've just said
