### ISSUE TITLE
NX 17 does not update package.json with internal buildable dependency versions during build

### ISSUE THREAD

**Issue by mta-trackunit** [nrwl/nx#19989]
### Current Behavior

NX 16 did update package.json on build using updateBuildableProjectDepsInPackageJson, so dist folder of the lib would have updated dependencies.

NX 17 does not update internal dependency versions on build so using the new lint the versions ends up with x: "*" 
updateBuildableProjectDepsInPackageJson has been removed but I cannot find any details on how it is supposed to work, how do i end up with a build with the right versions of dependencies and not "*".

I also tried checkout nx repo and build nx.js - it also does not update dependencies however its using "file://path_to_lib"

### Expected Behavior

It should work as in NX 16 so a build ends up with the package.json that can be published to npm.

### Steps to Reproduce

1. If I follow this guide --> https://nx.dev/getting-started/tutorials/integrated-repo-tutorial 
   _(also setup the lint to --fix the versions)_ 
    once you are done its package.json should look like this: 
    ```
    {
      "name": "@myorg/is-odd",
      "version": "1.2.3",
      "dependencies": {
        "tslib": "^2.3.0",
        "@myorg/is-even": "*"
      },
      "type": "commonjs",
      "main": "./src/index.js",
      "typings": "./src/index.d.ts"
    }
    ```
2. RUN
```
nx run is-odd:build          
```
3. Check the output in dist/libs/is-odd/package.json
```
{
  "name": "@myorg/is-odd",
  "version": "0.0.1",
  "dependencies": {
    "tslib": "^2.3.0",
    "@myorg/is-even": "*"
  },
  "type": "commonjs",
  "main": "./src/index.js",
  "typings": "./src/index.d.ts"
}

```

### Nx Report

```shell
cat dist/libs/is-odd/package.json

{
  "name": "@myorg/is-odd",
  "version": "0.0.1",
  "dependencies": {
    "tslib": "^2.3.0",
    "@myorg/is-even": "*"
  },
  "type": "commonjs",
  "main": "./src/index.js",
  "typings": "./src/index.d.ts"
}
```

### Package Manager Version

Node v18.17.0 yarn 1.22.19

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
To get some clarifications:

1. You set the version in `package.json` of each lib (committed to git).
2. When you run `nx lint <proj> --fix` it is setting version as `*` but you expect it to read the version from source `package.json` of dependencies.

**Comment by mta-trackunit** [comment]
Thanks for the quick response! 

Yes to both question 1 and 2 :) 

**useWorkspaceLibraryVersionsFromSource** could make sense for me - We use @jscutlery/semver, so if it means it will get the version directly from the library so we can have something like this:

**package.json in src**
```
{
  "name": "@myorg/is-even",
  "version": "1.2.3",
  "dependencies": {
    "tslib": "^2.3.0"
  },
  "type": "commonjs",
  "main": "./src/index.js",
  "typings": "./src/index.d.ts"
}
and 
{
  "name": "@myorg/is-odd",
  "version": "0.0.1",
  "dependencies": {
    "tslib": "^2.3.0",
    "@myorg/is-even": "*"
  },
  "type": "commonjs",
  "main": "./src/index.js",
  "typings": "./src/index.d.ts"
}
```

**package.json in DIST**
```
{
  "name": "@myorg/is-even",
  "version": "1.2.3",
  "dependencies": {
    "tslib": "^2.3.0"
  },
  "type": "commonjs",
  "main": "./src/index.js",
  "typings": "./src/index.d.ts"
}
and 
{
  "name": "@myorg/is-odd",
  "version": "0.0.1",
  "dependencies": {
    "tslib": "^2.3.0",
    "@myorg/is-even": "1.2.3"
  },
  "type": "commonjs",
  "main": "./src/index.js",
  "typings": "./src/index.d.ts"
}
```

However we have 580 libs/apps projects so having to run a **lint --fix** every build just to bump internal versions really is not ideal and should not be needed as its part of the repo so could be don during the build instead....
 
What is the reasoning for removing the ```updateBuildableProjectDepsInPackageJson``` during the build of rollup,webpack,esbuild and tsc executors? could we add that back - then it would work as I would expect - and be cheeper to maintain... 

I can also see nx repo does it differently with file:../<path> --> https://github.com/nrwl/nx/blob/master/packages/js/package.json

Maybe that is something the lint tool should also support ? 
What is then setting the right version in NX repo during build? (I cannot see that working for the NX repo either, it is still the file:../<path> efter running the build)

**Comment by jaysoo** [comment]
Unfortunately, the `updateBuildableProjectDepsInPackageJson` was hard to support because the use cases were too different. Users were not able to control `dependencies` vs `peerDependencies` for example, and many users just turned the option off. I'm glad it did work well for your team though.

I think a custom workspace script to update the `package.json` in dist is what I would recommend, as we have no plans to add `updateBuildableProjectDepsInPackageJson` back as a feature. Even better, `nx release` is supposed to solve the exact problem that you are describing. We're currently in the middle of stablelizing the `release` feature, which we're using in Nx itself.

**Comment by mta-trackunit** [comment]
Will the new nx release feature support running different versions pr library - or will it only support single versioning ? 
What is the ETA for the ```nx release``` ?

**Comment by mta-trackunit** [comment]
could you add an option to the linter for putting in the path to the lib using file://../path 
I see this is what you have in nx own repo - and it would be better to support then * 
maybe useWorkspaceLibraryPathInDependencies

**Comment by jaysoo** [comment]
> Will the new nx release feature support running different versions pr library - or will it only support single versioning ?

There will be different strategies, definitely don't have to use single version policy. 

> What is the ETA for the nx release ?

We're already using an experimental version of the feature in the Nx monorepo, but the stable version (with docs) is slated for January 2024 I believe.

> could you add an option to the linter for putting in the path to the lib using file://../path

Yes, I can take a look at this and adding an option to control it if needed.

**Comment by jaysoo** [comment]
I opened this PR to add `useLocalPathsForWorkspaceDependencies ` option. https://github.com/nrwl/nx/pull/20157

You can also set this manually in your `package.json` before the PR lands. The rest of your concerns we'll need to wait until `nx release` is out I think. In the meantime I imagine you can write a script to update versions from `file:...` to the release version prior to publishing -- we used to do this in Nx monorepo prior to `nx release`.

**Comment by ianldgs** [comment]
@jaysoo any chance we'll be able to do at some point:
- `nx affected --target=nx-release-version --specifier-source=conventional-commits`
- `nx affected --target=nx-release-publish`

?

by reading the `nx release` code, I see a way to do it right now, but it involves programatically calling:
-  `nx show --affected --json`
-  `@nx/js:release-version` generator
-  `{ releasePublish } from "nx/src/command-line/release`

**Comment by osuritz-grammarly** [comment]
> This will be improved with `nx release` in the future, but for now I suggest updating the source `package.json` by hand. Maybe we can add an option to the lint rule, e.g. `useWorkspaceLibraryVersionsFromSource`, that can handle (2) in the meantime.

Hey Jay,
Is that still planned for `nx release`? I just tried it and while it did update my version in `devDependencies`, in did not update the version listed in `peerDependencies`. Is that on purpose? Should I open an issue on that?

**Comment by dhdaines** [comment]
just another vote as someone who used this feature and for whom it worked just fine (the `dependencies` versus `peerDependencies` seems like a bit of a post hoc justification because nx will loudly refuse to package projects with `dependencies` these days!)

**Comment by jaysoo** [comment]
The original issue is addressed by both `useLocalPathsForWorkspaceDependencies` lint option and Nx Release, so I'm closing this issue.

Here is an example of using `file:` with Nx Release: https://github.com/jaysoo/packaging-test

As for `peerDependencies`, it isn't support right now but we will look into it. There are some special handling for cases like using version range in `peerDependencies` that don't exist with `dependencies` and `optionalDependencies`. I encourage you to open up a [new discussion](https://github.com/nrwl/nx/discussions/new?category=general) and we can track the feature that way.
