### ISSUE TITLE
Unable to find any apps in `.angular-cli.json`

### ISSUE THREAD

**Issue by SanderElias** [nrwl/nx#200]
new project, freshly generated with create-nx-workspace

started with:
`ng new "projectName" "--directory" "foldername" "--npm-prefix" "AS" --collection=@nrwl/schematics`
After that I did:
`yarn add @angular/cli prettier` 
to update the cli and prettier (prettier gave some issues too, but that is another issue, that is addressed already)
Now on: `ng g app seed-demo``
I get:
![image](https://user-images.githubusercontent.com/1249083/34834140-84061fa2-f6f1-11e7-8c36-8146c1961da1.png)

**Comment by SanderElias** [comment]
Just tried on a totally different system, the same issue!

**Comment by Yonet** [comment]
Hey @SanderElias. Nx still depends on our angular-cli fix. Victor has a pull request to angular-cli waiting to be merged in.

**Comment by cristianmartinez** [comment]
Hi @Yonet, can you provide the issue link, please?

**Comment by noelmace** [comment]
See https://github.com/angular/angular-cli/pull/7777#issuecomment-383296091
