### ISSUE TITLE
17.0.2 stopped stating up module federation remote when configured dynamically via manifest file

### ISSUE THREAD

**Issue by ArgV04** [nrwl/nx#20000]
### Current Behavior

I updated from Nx 17.0.2. Before update we started our app with nx serve shell and all module federation remotes automatically started. The were provided via manifest file.

After migration to 17.0.1 remotes are no longer started. The console shows this:

```
NX  Starting module federation dev-server for myapp with 0 remotes
```

Relates to this issue too, I think: https://github.com/nrwl/nx/issues/19812#issue-1958128798

This issue I think can be found here:

**@nx/webpack/src/utils/module-federation/get-remotes-for-host.js** ... new file introduced in Nx 17

There is a method called: **extractRemoteProjectsFromConfig**

```
const remotes = [];
....
if (
        Object.keys(parsedManifest).every(
          (key) =>
            typeof key === 'string' && typeof parsedManifest[key] === 'string'
        )
      ) {
        remotes.push(...Object.keys(parsedManifest));
      }
```

As a result we are now having an array element in the remotes array object pushed.

Later in the main method there: **getRemotes** .. you are doing something like this :)

```
remotes.forEach((r) => collectRemoteProjects(r, collectedRemotes, context));
```

The **collectRemoteProjects** now get an array as first parameter **r** and trying to resolve the remote name in its method

```
const remoteProject = context.projectGraph.nodes[remote]?.data;
```

But the remote is not some kind of string. It's the array of key names itself from the manifest file and returning **undefined**! 

Bähmm :)

Please fix :)

### Expected Behavior

Serving host should automatically work like in Nx 16.x

### Steps to Reproduce

1. nx serve shell-app (created with --dynamic)

### Nx Report

```shell
Node   : 18.14.0
   OS     : win32-x64
   yarn   : 3.2.4

   nx                 : 17.0.2
   @nx/js             : 17.0.2
   @nx/jest           : 17.0.2
   @nx/linter         : 17.0.2
   @nx/eslint         : 17.0.2
   @nx/workspace      : 17.0.2
   @nx/angular        : 17.0.2
   @nx/cypress        : 17.0.2
   @nx/devkit         : 17.0.2
   @nx/eslint-plugin  : 17.0.2
   @nrwl/tao          : 17.0.2
   @nx/web            : 17.0.2
   @nx/webpack        : 17.0.2
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   ng-mocks : 14.11.0
```

### Package Manager Version

npm 9.8.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
It's been fixed by this: https://github.com/nrwl/nx/pull/19894
