### ISSUE TITLE
"types" field not added to package.json output with tsc executor

### ISSUE THREAD

**Issue by ajwootto** [nrwl/nx#20003]
### Current Behavior

When building a commonjs package with `@nx/js:tsc` using `module: node16`, the package.json output of the package lacks a "types" field. This causes Typescript to not be able to find the type definitions when that package is required by other packages. A valid output should include the "types" field.

### Expected Behavior

"types" field should be included in the package.json output

In case this is intended behaviour, it disagrees with the official recommendation of Typescript docs
https://www.typescriptlang.org/docs/handbook/modules/reference.html#packagejson-main-and-types

### GitHub Repo

https://github.com/DevCycleHQ/js-sdks/pull/588/commits/94aa808c7762064d7aa2cffd43ea5f107edf30b5

### Steps to Reproduce

1. check out the repo at that commit
2. yarn
3. yarn nx build js-cloud-server-sdk

Build fails because it can't find the types declarations of the `server-request` dependency, because Nx isn't adding the "types" field to it.

Adding the types field manually to the source package.json fixes the problem.

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin-arm64
   yarn   : 3.6.0

   nx                 : 16.7.4
   lerna              : 5.6.2
   @nx/js             : 16.7.4
   @nx/jest           : 16.7.4
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.7.4
   @nx/cypress        : 16.7.4
   @nx/detox          : 16.7.4
   @nx/devkit         : 16.7.4
   @nx/esbuild        : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nx/next           : 16.7.4
   @nx/node           : 16.7.4
   @nx/react          : 16.7.4
   @nx/react-native   : 16.7.4
   @nrwl/rollup       : 16.7.4
   @nx/web            : 16.7.4
   @nx/webpack        : 16.7.4
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @altack/nx-bundlefy : 0.16.0
```
```


### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by ajwootto** [comment]
this also appears to be a problem in the rollup executor, and probably others I haven't tested

**Comment by cainlevy** [comment]
I was surprised to discover that this appears to be intentional:

https://github.com/nrwl/nx/blob/75234ae1b5685cfb084ff553922c287d2b8e32bb/packages/js/src/executors/tsc/tsc.impl.ts#L120-L122
