### ISSUE TITLE
NX utils: readProjectFileMapCache not a function

### ISSUE THREAD

**Issue by Dinuda** [nrwl/nx#20007]
### Current Behavior

Error: 

```
TypeError: (0 , nx_deps_cache_1.readProjectFileMapCache) is not a function
    at updatePackageJson 
```

Tried reinstalling packages, and updating the version. The same error still appears. This is an issue with a build config deps or updating a renamed function in all the relevant entities. 
![Screenshot 2023-11-02 at 22 33 00](https://github.com/nrwl/nx/assets/63149008/e4946b99-974d-414f-a506-c9e7b3130367)

### Expected Behavior

For nx to build workspace tooling configuration properly. 

### Steps to Reproduce

1. Install workspace plugin tool
2. Npm install
3. Try to build

### Nx Report

```shell
Node   : 16.14.2
   OS     : darwin-arm64
   npm    : 8.5.0
   
   nx (global)        : 16.10.0
   nx                 : 17.0.2
   @nx/js             : 16.5.5
   @nx/jest           : 16.5.5
   @nx/linter         : 16.5.5
   @nx/workspace      : 16.5.5
   @nx/devkit         : 16.5.5
   @nx/eslint-plugin  : 16.5.5
   @nx/node           : 16.5.5
   @nx/plugin         : 16.5.5
   @nrwl/tao          : 16.5.5
   nx-cloud           : 16.5.2
   typescript         : 5.2.2
   ---------------------------------------
   Local workspace plugins:
         @nx-workspaces-serverless-lambda-angular/workspace-plugin
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/js@16.5.5
     - @nrwl/js@16.5.5
     - @nx/jest@16.5.5
     - @nrwl/jest@16.5.5
     - @nx/linter@16.5.5
     - @nrwl/linter@16.5.5
     - @nx/workspace@16.5.5
     - @nrwl/workspace@16.5.5
     - @nx/devkit@16.5.5
     - @nrwl/devkit@16.5.5
     - @nx/eslint-plugin@16.5.5
     - @nrwl/eslint-plugin-nx@16.5.5
     - @nx/node@16.5.5
     - @nrwl/node@16.5.5
     - @nx/plugin@16.5.5
     - @nrwl/nx-plugin@16.5.5
     - @nrwl/tao@16.5.5
```

### Failure Logs

```shell
TypeError: (0 , nx_deps_cache_1.readProjectFileMapCache) is not a function
    at updatePackageJson
```

### Package Manager Version

8.5.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Found a fix:

Rename deprecated function to new. 

readProjectFileMapCache -> readFileMapCache

**Comment by AgentEnder** [comment]
Hey @Dinuda, it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

**Comment by Dinuda** [comment]
Hi @AgentEnder all good now. Cheers!
