### ISSUE TITLE
Support building multiple module formats with `tsc`

### ISSUE THREAD

**Issue by ajwootto** [nrwl/nx#20010]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Executors such as `tsc` should be able to output a module in `ESM` or `Commonjs` according to executor settings in project.json. Similar to the `rollup` executor, it should support a `formats` field that also allows "hybrid" packages to be produced by specifying both ESM and commonjs.

## Motivation

Currently the only way to make a "hybrid" package with Nx is using the `Rollup` executor, but it is often the case that a library author doesn't want to bundle the files together when distributing the library. One current reason for "why" is that bundlers remove `"use client"` directives needed to distribute React client component libraries:
https://github.com/nrwl/nx/issues/19714

Another is that bundling should be the responsibility of the consumer of a library, it doesn't really make sense to "pre-bundle" files that only really need to be bundled if they are going into an application bundle, in which case another bundler is already going to be in use.

Also as noted in the TS docs, type checking of source files is only applied using one of the two module systems, and using a 3rd party bundler like Rollup to generate two kinds of output means that only one of them is being type checked.
https://www.typescriptlang.org/docs/handbook/modules/guides/choosing-compiler-options.html#notes-on-dual-emit-solutions
Using `tsc` for both kinds of output would allow the build to fail if either of those kinds of output is invalid.

## Suggested Implementation

End-user option could look the same as the `rollup` one, with `formats` allowing multiple formats to be listed.
Under the hood, I'd imagine it would run `tsc` twice while overriding the "module" setting for one of the builds, and then properly structure the `package.json` output to be a hybrid package.

**Comment by potouridisio** [comment]
@ajwootto Excuse me, is there a workaround when using `rollup` bundler for a `next` library?

**Comment by ajwootto** [comment]
@potouridisio not sure, but I filed a separate issue for it 

https://github.com/nrwl/nx/issues/19714

**Comment by ajwootto** [comment]
not stale

**Comment by JamesHenry** [comment]
Sorry for the delay on a concrete response here @ajwootto!

As you have likely seen, our new plugins focus on getting out of the way of your tools, such as `tsc`, for greater transparency and integration. We are therefore not looking to add further complexity to our historical executors which wrap your tools in an opaque way.

For your case, I would personally (i.e. not a universal Nx Team thing) recommend looking at https://github.com/isaacs/tshy - I used it to great effect on the rxjs repo not too long ago.

You can wire it up as an Nx target via an npm script or using the `nx:run-commands` executor to invoke the `tshy` CLI.

**Comment by JamesHenry** [comment]
Sure, the best place to start is this video and doc https://nx.dev/concepts/inferred-tasks linked from https://nx.dev/concepts/nx-plugins
