### ISSUE TITLE
Rollup executor with multiple formats does not output ESM types, does not specify "type": "module"

### ISSUE THREAD

**Issue by ajwootto** [nrwl/nx#20011]
### Current Behavior

When configuring rollup executor to output both esm and cjs formats, it appears that the package.json output lacks a `"type": "module"` field, and that also the generated output files do not contain a type declaration file corresponding to the "esm" version of the bundle.

### Expected Behavior

There should be a generated types output for the `esm` file.

My understanding is that the package.json file should also specify `"type": "module"` in order to indicate that it can be imported as ESM.

### GitHub Repo

https://github.com/DevCycleHQ/js-sdks/pull/588/commits/ae4581f65be604fc4676cb29e7d103e4e3975339

### Steps to Reproduce

1. clone the repo
2. yarn
3. yarn nx build react
4. Inspect dist/ output

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin-arm64
   yarn   : 3.6.0

   nx                 : 16.7.4
   lerna              : 5.6.2
   @nx/js             : 16.7.4
   @nx/jest           : 16.7.4
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.7.4
   @nx/cypress        : 16.7.4
   @nx/detox          : 16.7.4
   @nx/devkit         : 16.7.4
   @nx/esbuild        : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nx/next           : 16.7.4
   @nx/node           : 16.7.4
   @nx/react          : 16.7.4
   @nx/react-native   : 16.7.4
   @nrwl/rollup       : 16.7.4
   @nx/web            : 16.7.4
   @nx/webpack        : 16.7.4
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @altack/nx-bundlefy : 0.16.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by igorkamyshev** [comment]
I believe it's better to fix it instead of automatically marking as stale and closing.

**Comment by ajwootto** [comment]
not stale

**Comment by Coly010** [comment]
After some investigation into this I can confirm there is no issue here.

The output that is produced employs a "Dual-mode Strategy", such that the library is supported in both ESM and CJS environments.

The `module` field is set and points to the ESM file, while the `main` field is set and points to the CJS file. Dependent on the consumer's environment, either `main` or `module` will be accessed correctly.
