### ISSUE TITLE
Is there option to rename generated app and all files that depend on it?

### ISSUE THREAD

**Issue by NakedFool** [nrwl/nx#2001]
- [y] I am running the latest version
- [y] I checked the documentation and found no answer
- [y ] I checked to make sure that this issue has not already been filed
- [y] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

I would like to know that is there option in nx workspace that previously generated app can be renamed? So i don't have to go manually into all files that depend upon that app.

**Comment by FrozenPandaz** [comment]
There is not but I could see this being useful. Would someone from the community be interested in tackling this?

I think the user would do:

```bash
ng generate @nrwl/workspace:rename-project project-name-1 project-name-2
```

**Comment by NakedFool** [comment]
Yes, that would be cool feature!

Looking forward for more people activating in this! :)

**Comment by asherccohen** [comment]
I also suggest a remove command if possible.

**Comment by jdpearce** [comment]
Wow...I've only just seen that I was assigned to this, sorry!

@NakedFool - Hopefully the new `mv` schematic in 8.12 should fulfil this requirement, so I'm going to close this issue as a result.

`nx g @nrwl/angular:mv --project my-project --destination my-renamed-project`

See the [blog](https://blog.nrwl.io/nx-8-12-distributed-caching-improved-dependency-detection-better-support-for-buildable-libraries-6f7cec17b83f) for more.

@asherccohen - We are going to work on a similar `rm`/`remove` schematic for the next release (by "we" I mean me here)

**Comment by gioragutt** [comment]
@jdpearce hey man, just dropping by to ask if there's anything similar for other app/library types?

F.E if I used `nx g @nrwl/node:lib my-lib` and I would like to rename `my-lib` to `their-lib`? 😅

**Comment by jdpearce** [comment]
@gioragutt The `@nrwl/angular:mv` schematic actually depends on a very generic `@nrwl/workspace:mv` schematic, so you can just use that one instead - e.g. `nx g @nrwl/workspace:mv --project my-lib --destination their-lib`

**Comment by FacePalmDev** [comment]
Weird thing happened when I tried this. It's not too much of an issue but I'm wondering if this happens to anyone else. When I ran the command:

```nx g @nrwl/nest:mv --project my-project --destination my-renamed-project```

The console printed out a load of: 
CREATE newProject/xxxx
DELETE oldProject/xxxx

However the old project wasn't actually deleted or removed, all files are still there?
