### ISSUE TITLE
NX computed hash used for cache is different on every run when no changes are introduced  - v2

### ISSUE THREAD

**Issue by alvaro450** [nrwl/nx#20012]
### Current Behavior

Consistent cache misses for one of our monorepo libraries.

### Expected Behavior

When there are no changes on the given library and there is already an entry in cache, it should get the task's output from cache instead of executing the task process again.

### Steps to Reproduce

1.

### Nx Report

```shell
Node   : 18.16.0
   OS     : darwin-arm64
   npm    : 9.5.1
   
   nx                 : 17.0.2
   @nx/js             : 17.0.2
   @nx/jest           : 17.0.2
   @nx/linter         : 17.0.2
   @nx/eslint         : 17.0.2
   @nx/workspace      : 17.0.1
   @nx/angular        : 17.0.2
   @nx/cypress        : 17.0.2
   @nx/devkit         : 17.0.2
   @nx/eslint-plugin  : 17.0.2
   @nx/plugin         : 17.0.2
   @nx/storybook      : 17.0.2
   @nrwl/tao          : 17.0.2
   @nx/web            : 17.0.2
   @nx/webpack        : 17.0.2
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   @storybook/angular : 6.5.15
   apollo-angular     : 4.2.1
   ---------------------------------------
```

### Package Manager Version

npm 9.5.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Same details as the previously opened issue https://github.com/nrwl/nx/issues/19275.

The fix that was done on file [`packages/nx/src/project-graph/utils/retrieve-workspace-files.ts`](https://github.com/nrwl/nx/pull/19806/files) where sorting was added `fileData = fileData.concat(globalFiles).sort();` does not properly sort the files given that the argument passed to the sort fn is an object and not a string.

Passing a predicate `(a, b) => a.file.localeCompare(b.file)` to the sorting function, correctly sorts the files by fileName. 
``` typescript
fileData = fileData.concat(globalFiles).sort((a, b) => a.file.localeCompare(b.file));
```

**Comment by Cammisuli** [comment]
oh no, sorry about that! Let me fix that properly 😓

**Comment by alvaro450** [comment]
> oh no, sorry about that! Let me fix that properly 😓 I got too used to sorting in Rust 😅 

Thank you for the prompt response and resolution!
