### ISSUE TITLE
Integrated monorepo. Linter will fail if a publishable libs depends on another lib of the same repo.

### ISSUE THREAD

**Issue by chabb** [nrwl/nx#20029]
### Current Behavior

I'm not sure if it's a real issue, or if it's more of a documentation issue

Let's suppose you have an integrated repo of publishable typescript libs. One of the lib depends on all the other libs.
```
/libs
>main
>libA
>libB
>libC
```

Everything works fine if I try to build the main lib. But the lint task will fail, because the `package.json` of the `main` lib  has no dependencies to the other libs. What's the right way to fix it ? Should nx or the developers update the package.json file of the publishable library ?

If the libs are not publishable, the lint task will pass ( as there is no package.json )

### Expected Behavior

If I look at the tutorial [here](https://nx.dev/getting-started/tutorials/integrated-repo-tutorial), there is no information on this topic: It would be great to have a few lines and an example on this topic.

### Steps to Reproduce

1. Create an integrated repo
2. Create a few publishable libs (a, b, c)
3. Make one of the lib import something from another lib
4. Run the lint task

### Nx Report

```shell
The lint task will fail
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by ajwootto** [comment]
Currently I think the only place this is documented is in the lint rule itself:
https://nx.dev/nx-api/eslint-plugin/documents/dependency-checks

I haven't been able to find any place in the main docs site where its mentioned or how package interdependencies for publishable packages should be managed now.

You can run the lint task with `--fix` to have the rule automatically add the missing dependencies for you.

**Comment by chabb** [comment]
Thanks @ajwootto. That makes sense, after all, if your lib is publishable, your are the one who is responsible for specifying its dependencies.
