### ISSUE TITLE
dependency-checks lint rule ignores `devDependencies`

### ISSUE THREAD

**Issue by ajwootto** [nrwl/nx#20021]
### Current Behavior

When using the `dependency-checks` lint rule, any dependency which is listed already in "devDependencies" is treated as "missing" from the package.json by the lint rule , and it bugs you to add it.

The only way to resolve the error is to either move it to "dependencies" or separately add it to the linter's ignore list.

Running the linter with `--fix` also adds a duplicate entry for that dependency to the `dependencies` 

### Expected Behavior

The lint rule should understand that when a dependency is already listed in devDependencies, it isn't "missing" and in fact a decision has been made that it's a dev-only dependency.

Ideally, Nx would be more sophisticated at figuring out the different between a dev-only dependency or a runtime-required one by understanding which files are test files and which ones aren't, but in lieu of that I think the linter should still allow devDependencies to resolve this error without having to list it again in the linter's ignore settings.

### Steps to Reproduce

1. Create a package which imports a package in a test file
2. add that package to the devDependencies of the parent package
3. run the lint rule on the parent package
4. get an error about a missing dependency

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin-arm64
   yarn   : 3.6.0

   nx                 : 16.10.0
   lerna              : 5.6.2
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/detox          : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/esbuild        : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/next           : 16.10.0
   @nx/node           : 16.10.0
   @nx/react          : 16.10.0
   @nx/react-native   : 16.10.0
   @nrwl/rollup       : 16.10.0
   @nx/web            : 16.10.0
   @nx/webpack        : 16.10.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @altack/nx-bundlefy : 0.16.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by MathurAditya724** [comment]
This might help you - #19307

**Comment by ajwootto** [comment]
@MathurAditya724 thanks for the link, that's very helpful!

I tried going with the `namedInputs` approach to specify not to include the test files in "production" input, but I believe my lint tasks are configured to use the "default" named input.

Does that mean that following the approach in that issue means configuring the linter to ignore test files in general? Or is there some other piece of configuration that is missing here? It doesn't seem like just configuring the namedInputs is enough, because I still get a linting error.

cc @meeroslav if you're able to lend a hand
