### ISSUE TITLE
@nx/enforce-module-boundaries lint rule ignores "external"

### ISSUE THREAD

**Issue by ajwootto** [nrwl/nx#20033]
### Current Behavior

When importing a package that is going to be inlined due to the use of the `external` setting, the lint rule for enforce-module-boundaries complains that it can't be required in this buildable package because it is non-buildable.

This isn't true, because the non-buildable package is being embedded in the buildable one. 

### Expected Behavior

The lint rule should only enforce this in the case where "external" setting doesn't lead to the imported package being inlined. Otherwise it is linting against a setup that works perfectly fine in the actual build system.

### Steps to Reproduce

1. Create a buildable and non-buildable lib
2. import the non-buildable lib into buildable one
3. Set the 'external' setting of the buildable lib to an empty array (which implies that all workspace packages are to be inlined)
4. Run build
5. it works
6. run lint
7. it fails

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin-arm64
   yarn   : 3.6.0

   nx                 : 16.10.0
   lerna              : 5.6.2
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/detox          : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/esbuild        : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/next           : 16.10.0
   @nx/node           : 16.10.0
   @nx/react          : 16.10.0
   @nx/react-native   : 16.10.0
   @nrwl/rollup       : 16.10.0
   @nx/web            : 16.10.0
   @nx/webpack        : 16.10.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @altack/nx-bundlefy : 0.16.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by meeroslav** [comment]
Hi,

The linter rule is agnostic of the builder you are using so it cannot tell whether you marked that library as external or not (you might have several targets where one marks it as external and one as inlined).

You can switch this check off by setting `enforceBuildableLibDependency` to `false` in your eslint config.
https://nx.dev/nx-api/eslint-plugin/documents/enforce-module-boundaries#options

**Comment by ajwootto** [comment]
Hi @meeroslav . Turning off that enforcement entirely does not seem like a good solution. How can the linter be used in conjunction with the concept of "external", which is present in most Nx build executors and is a pretty critical feature for sharing code between published libs?

Does the linter need some additional option that lets you separately list the "internal" packages, or can it just be updated to understand "external" automatically?

**Comment by ajwootto** [comment]
@meeroslav thanks for the reply

 as far as I understand it though, the point of that check for buildable depending on non-buildable is to prevent a buildable lib that is going to be published somewhere from depending on code that isn't buildable and thus couldn't be separately built and published for use by that parent dependency. However, that check isn't relevant in a situation where the buildable lib is bundling the code of that non-buildable lib in its own source code. In that scenario the non-buildable lib is effectively "
 part" of the outer lib 
 
 It feels like there's a mismatch in expectations here between what should be represented on the Nx project graph vs. what the builders that have "external" option would need to have represented. I understand the point about the linting rule not being specific to builds, but I'm just thinking along the lines of how an "internal" package potentially deserves to be a first-class concept represented in the project graph in order for the other parts of Nx to understand it correctly.
