### ISSUE TITLE
Jest pattern matching doesn't allow selecting file from the list

### ISSUE THREAD

**Issue by kopach** [nrwl/nx#20056]
### Current Behavior

Currently, when using pattern matching with Jest - developer has to know exact file patter beforehand. I'ts not possible to select file from the list of available files. When running Jest outside of NX project, this functionality is available.

### Expected Behavior

When using pattern matching in Jest - it should be possible to additionally be able to select file from list by using arrows on keyboard

### Steps to Reproduce

1. run tests with Jest runner in **watch** mode
2. on tests complete type `p` to go into patter matching mode
3. start typing
4. file list isn't available

### Nx Report

```shell
Node : 18.17.0
   OS   : darwin arm64
   pnpm : 8.6.11
   
   nx                      : 15.9.7
   @nrwl/js                : 15.9.7
   @nrwl/jest              : 15.9.7
   @nrwl/linter            : 15.9.7
   @nrwl/workspace         : 15.9.7
   @nrwl/cli               : 15.9.7
   @nrwl/devkit            : 15.9.7
   @nrwl/eslint-plugin-nx  : 15.9.7
   @nrwl/next              : 15.9.7
   @nrwl/node              : 15.9.7
   @nrwl/react             : 15.9.7
   @nrwl/rollup            : 15.9.7
   @nrwl/tao               : 15.9.7
   @nrwl/web               : 15.9.7
   @nrwl/webpack           : 15.9.7
   typescript              : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I have found solution for this already. 
Add `jest-watch-typeahead` to the project and add this to `jest.preset.js`
```js
  watchPlugins: ['jest-watch-typeahead/filename', 'jest-watch-typeahead/testname'],
```

Wold be great to have this added to jest generator.

Also, I'm willing to contribute and update this myself if you help me to understand where to start. Thanks

**Comment by FrozenPandaz** [comment]
I think we'll keep our `jest` preset light but users can add this plugin to their `jest.preset.js` files.
