### ISSUE TITLE
Missing peerDependencies when built my TS project

### ISSUE THREAD

**Issue by shaunxu** [nrwl/nx#20054]
### Current Behavior

I had created 3 libraries named `app`, `is-even` and `is-odd` created from the document in nx website. In the source code of `app` I imported functions defined in `is-even` and `is-odd`. I also install a thrid-party package `lodash` and used in `app`.

After built my project through `nx run-many --target=build`, I found in the `dist` folder, there is no `peerDependencies` section in `package.json` in `app` folder.

### Expected Behavior

`nx run-many --target=build` should be able to detect which packages I imported from the source code and add them into `peerDependencies`.

### GitHub Repo

https://github.com/shaunxu/myorg

### Steps to Reproduce

1. `npx create-nx-workspace@latest myorg --preset=ts`
2. `npx nx generate @nx/js:library is-even --directory=libs/is-even --publishable --importPath=@myorg/is-even`
3. `npx nx generate @nx/js:library is-odd --directory=libs/is-odd --publishable --importPath=@myorg/is-odd`
4. `npx nx generate @nx/js:library app --directory=libs/app --publishable --importPath=@myorg/app`
5. `npm install lodash`
6. Replace the content of `libs/app/src/lib/app.ts` as below

```js
import { isEven } from "@myorg/is-even";
import { isOdd } from "@myorg/is-odd";
import * as _ from "lodash";

export function app(): string {
  console.log(isEven());
  console.log(isOdd());
  console.log(_.VERSION);
  return 'app';
}

```

7. `npx nx run-many --target=build --skip-nx-cache`
8. Open file `dist/libs/app/package.json` you will see there is no `peerDependencies` section. What I want is

```json
{
  "peerDependencies": {
    "is-even": "^1.0.0",
    "is-odd": "^1.0.0",
    "lodash": "^4.17.21"
  }
}
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 21.0.0
   OS     : darwin-arm64
   npm    : 10.2.0

   nx                 : 17.0.3
   @nx/js             : 17.0.3
   @nx/linter         : 17.0.3
   @nx/eslint         : 17.0.3
   @nx/workspace      : 17.0.3
   @nx/devkit         : 17.0.3
   @nx/eslint-plugin  : 17.0.3
   @nrwl/tao          : 17.0.3
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

It worked fine for `nx v16` in many of my projects but not for `nx v17`.

**Comment by bjsawyer** [comment]
Is there a timeline for the fix for this @FrozenPandaz? I am forced to stay on Angular v14 for the time-being and until this is resolved we have to manually handle add every internal lib to each project's `peerDependencies`.

**Comment by FrozenPandaz** [comment]
Sorry, that functionality has been moved into the `@nx/dependency-checks` lint rule.

It will warn you that there are missing dependencies for a given publishable project:

```
~/p/t/test (main|✚4) $ npx nx lint main

> nx run main:lint

> eslint .


/home/jason/projects/triage/test/libs/main/package.json
  4:3  error  The "main" project uses the following packages, but they are missing from "dependencies":
    - @jason/is-even
    - @jason/is-odd
    - lodash  @nx/dependency-checks

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

Warning: command "eslint ." exited with non-zero status code
—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target lint for project main (988ms)

   ✖  1/1 failed
   ✔  0/1 succeeded [0 read from cache]

~/p/t/test (main|✚4) [1]$ npx nx lint main --fix

> nx run main:lint --fix

> eslint . --fix
```

`--fix` will also add the dependency for you into the `package.json`. You can move the dependency to `peerDependencies` and the rule will still be satisfied. This also helps you keep versions in sync. Read more here: https://nx.dev/nx-api/eslint-plugin/documents/dependency-checks
