### ISSUE TITLE
Daemon ignores custom cache directory

### ISSUE THREAD

**Issue by twittwer** [nrwl/nx#20059]
### Current Behavior

The daemon seems to ignore the custom cache directory.

```
        new file:   .nx/cache/d/daemon.log
        new file:   .nx/cache/d/server-process.json
        new file:   .nx/cache/file-map.json
        new file:   .nx/cache/lockfile.hash
        new file:   .nx/cache/parsed-lock-file.json
        new file:   .nx/cache/project-graph.json
```

### Expected Behavior

All nx process respect the `cacheDirectory` config in the `nx.json`.

### GitHub Repo

https://github.com/twittwer/repro-custom-cache-directory

### Steps to Reproduce

1. run `npm install`
2. run `npm start` (`nx serve app`)
3. see created files in default instead of custom cache directory via `git status`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : win32-x64
   npm    : 9.5.1
   
   nx                 : 17.0.3
   @nx/js             : 17.0.3
   @nx/jest           : 17.0.3
   @nx/linter         : 17.0.3
   @nx/eslint         : 17.0.3
   @nx/workspace      : 17.0.3
   @nx/angular        : 17.0.3
   @nx/cypress        : 17.0.3
   @nx/devkit         : 17.0.3
   @nx/eslint-plugin  : 17.0.3
   @nrwl/tao          : 17.0.3
   @nx/web            : 17.0.3
   @nx/webpack        : 17.0.3
   typescript         : 5.1.6
```
```


### Failure Logs

_No response_

### Package Manager Version

npm

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by AgentEnder** [comment]
These files don't get moved with `cacheDirectory` on purpose, for a few various reasons. Listed below:

- Sometimes cache directory is moved to a network drive or other place that is used by multiple clones of the workspace. In these cases, the daemon and project graph files **_can not_** be shared and shouldn't be moved.
- Idiomatically these files aren't part of the user facing cache. Think of it almost more as temp storage for Nx.

If you want to move these files for whatever reason, you can use the NX_PROJECT_GRAPH_CACHE_DIRECTORY env variable to set a location.
