### ISSUE TITLE
Module federation using js is broken

### ISSUE THREAD

**Issue by Remcoman** [nrwl/nx#20066]
### Current Behavior

Creating a module federated React host or remote seems to be broken

### Expected Behavior

Module federation should work when specifying the `--js` option
Or it should be documented that module federation does not work with JS 

### GitHub Repo

https://github.com/Remcoman/nx-mf-issues

### Steps to Reproduce

1. Run `npx nx generate @nx/react:host --js`
2. See that the generator creates a React module federation app with a combination of js and ts files
3. Try to run the app `npx nx serve {app_name}`
4. Error occurs: `bootstrap is missing`

### Nx Report

```shell
Node   : 16.20.1
   OS     : darwin-x64
   npm    : 8.19.4
   
   nx                 : 17.0.3
   @nx/js             : 17.0.3
   @nx/jest           : 17.0.3
   @nx/linter         : 17.0.3
   @nx/eslint         : 17.0.3
   @nx/workspace      : 17.0.3
   @nx/cypress        : 17.0.3
   @nx/devkit         : 17.0.3
   @nx/eslint-plugin  : 17.0.3
   @nx/react          : 17.0.3
   @nrwl/tao          : 17.0.3
   @nx/web            : 17.0.3
   @nx/webpack        : 17.0.3
   typescript         : 5.1.6
```

### Failure Logs

```shell
ERROR in ./src/main.ts 3:0-21
Module not found: Error: Can't resolve './bootstrap' in '/Users/remco/Documents/projects/nx-mf-issues/apps/jshost/src'

webpack compiled with 1 error (6bb5ab24128f1ca8)
ERROR in ./apps/jshost/src/app/app.tsx:3:23
TS7016: Could not find a declaration file for module './nx-welcome'. '/Users/remco/Documents/projects/nx-mf-issues/apps/jshost/src/app/nx-welcome.js' implicitly has an 'any' type.
    1 | import * as React from 'react';
    2 |
  > 3 | import NxWelcome from './nx-welcome';
      |                       ^^^^^^^^^^^^^^
    4 |
    5 | import { Link, Route, Routes } from 'react-router-dom';
    6 |

ERROR in ./apps/jshost/src/main.ts:1:8
TS2307: Cannot find module './bootstrap' or its corresponding type declarations.
  > 1 | import('./bootstrap');
      |        ^^^^^^^^^^^^^
    2 |

Found 2 errors in 1885 ms.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by rishabkoul** [comment]
yes even i am facing this issue this works fine with type script

**Comment by xiongemi** [comment]
there is an issue with host creating using --js flag, quick fix:
- change main.js to bootstrap.js
- change main.ts to main.js
- remove src/app/app.tsx
- change build target's options -> main to main.js

**Comment by xiongemi** [comment]
there is a pr for this issue: https://github.com/nrwl/nx/pull/20119
