### ISSUE TITLE
dependency-check lint rule should separate options for "including an unused package" vs. ignoring it

### ISSUE THREAD

**Issue by ajwootto** [nrwl/nx#20070]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Add a separate list of packages that should be allowed to be included in the package.json even if the lint rule considers them "unused", so that it bypasses the "obsoleteDependencies" check for that package but does not skip the other checks.

## Motivation

Currently when a package is missing from the package.json the lint rule will complain.
It also complains if a package is listed which it considers "unused" and thus should not be listed.

In both cases, if the lint rule is wrong, the only solution to get lint to pass is to add that dependency to "ignoredDependencies".
However, doing so means that there's no way to tell what the intent of the "ignore" is. Are you ignoring it because you don't want to include it? Or ignoring it because you need to include it and the lint rule won't let you.
Since these are basically opposites, I think it makes more sense to have a second list of dependencies which are explicitly "included" even if the lint rule thinks they shouldn't be. That would help work around issues like this
https://github.com/nrwl/nx/issues/20068
without having to add it to the same list as the dependencies that are being purposefully excluded from the package.json

## Suggested Implementation

Another option like `implicitIncludedDependencies` or something that lists a set of packages that skip the `obsoleteDependencies` check for whether the package is actually using the dependency.

**Comment by meeroslav** [comment]
Thank you for this proposal. It makes sense and would bring a positive improvement.

We can perhaps have two possible property types of `ignoredDependencies`:

- The existing flat array of strings
- The object with the following structure:
```
{
  "missing": string[],
  "unused": string[],
  "mismatch": string[]
}
```

We'll get to this as soon as possible.

**Comment by ajwootto** [comment]
That sounds good :) . It would be great if the package that is having its "unused status" ignored could still be checked for correct version matching against the root package.json version

**Comment by ajwootto** [comment]
@meeroslav while these changes are being made I also think you should consider again the role that "externals" play in the linting rule's ability to provide safety.
See my comment here
https://github.com/nrwl/nx/issues/20019#issuecomment-1836348326

That issue with closed with the justification that the linting rule can't infer things related to your build settings, but isn't that what the rule is doing already in the case of non-buildable libs that are required in an application? In that case, the linting rule knows that the code in that lib is part of the main application and thus any dependencies used in there need to be listed.

How is a buildable lib that includes another lib as part of its build any different than that?
