### ISSUE TITLE
@nrwl/nx-plugin vs @nx/nx-plugin

### ISSUE THREAD

**Issue by Mojo1** [nrwl/nx#20085]
### Current Behavior

@nx/nx-plugin version stuck at 16.0.0-beta.1
@nrwl/nx-plugin at version 17.0.3

shouldn't it be the other way around? Anway expected @nx/nx-plugin to be up to date version

### Expected Behavior

expected to use package @nx/nx-plugin 

### Steps to Reproduce

1...

### Nx Report

```shell
..
```

### Failure Logs

```shell
..
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
The new package is [@nx/plugin](https://www.npmjs.com/package/@nx/plugin). We took the opportunity to not repeat `nx` twice.

The migration should've changed this automatically.

Related Guide: https://nx.dev/recipes/other/rescope#rename
