### ISSUE TITLE
Slack link in readme has expired

### ISSUE THREAD

**Issue by joshamos** [nrwl/nx#2008]
## Expected Behavior

Clicking the Slack button allows me to join Slack.

## Current Behavior

Says the link is expired.

## Failure Information (for bugs)

![image](https://user-images.githubusercontent.com/131831/67812792-1d2d8f00-faf4-11e9-9d61-120cf93afe5f.png)

### Steps to Reproduce

Click this in the readme:

![image](https://user-images.githubusercontent.com/131831/67812814-2a4a7e00-faf4-11e9-8d32-34643ab2eb23.png)

**Comment by FrozenPandaz** [comment]
@Doginal

Can you please update the link in the Nx repo with an invite link that does not expire?

**Comment by eLarocque** [comment]
The link seems to have expired again

**Comment by Doginal** [comment]
@eLarocque - The link is working on my end. 

https://bit.ly/2ZApcSo is the correct link
