### ISSUE TITLE
E2e test performance

### ISSUE THREAD

**Issue by sroettering** [nrwl/nx#2009]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Current Behavior

Running e2e tests with cypress and typescript has become painfully slow after upgrading from 8.4.4 to 8.5.0 and still on 8.6.0. Before updating our tests took around 15 minutes on CI and now they take around 50 minutes.
I think most of the time is spent on type checking:
```
Starting type checking service...
Using 1 worker with 2048MB memory limit
```

Was type checking just added now and does it have to be so slow?

**Comment by FrozenPandaz** [comment]
The compilation has changed a bit for our cypress support. However, type checking was always enabled.

@bcabanes Can you please look into this issue?

**Comment by bcabanes** [comment]
Hi @sroettering!
Do you use the `supportFile` entry in the Cypress json configuration file?

@FrozenPandaz We did not merge this PR removing the type checking with _tslint_ [here](https://github.com/nrwl/nx/pull/1920). This PR is fixing the issue that a lot of type when a `supportFile` is used for Cypress.

**Comment by sroettering** [comment]
@bcabanes Yes I am using the supportFile option. I have several custom commands to make testing of certain scenarios easier and more readable.
So right now cypress is pretty much unusable for me as I can't wait an hour for a build pipeline  to pass :/
