### ISSUE TITLE
nx reset is not clearing angular cache

### ISSUE THREAD

**Issue by rbirkgit** [nrwl/nx#20093]
### Current Behavior

I do `nx reset` and it's not clearing Angualr cache.

Normally I do `ng cache clean` but that is no longer working in our Nx repo.

### Expected Behavior

That nx reset also clears angular cache or provide a way to do it.

### Steps to Reproduce

1. nx reset

### Nx Report

```shell
Node   : 18.14.0
   OS     : win32-x64
   yarn   : 3.2.4

   nx                 : 17.0.3
   @nx/js             : 17.0.3
   @nx/jest           : 17.0.3
   @nx/linter         : 17.0.3
   @nx/eslint         : 17.0.3
   @nx/workspace      : 17.0.3
   @nx/angular        : 17.0.3
   @nx/cypress        : 17.0.3
   @nx/devkit         : 17.0.3
   @nx/eslint-plugin  : 17.0.3
   @nrwl/tao          : 17.0.3
   @nx/web            : 17.0.3
   @nx/webpack        : 17.0.3
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   ng-mocks : 14.11.0
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
`nx reset` is not responsible for the Angular cache. Nx will only clear cache directories related to Nx.

@Coly010 could you provide the best way to clear the Angular cache in an Nx workspace? There's an error when running `ng cache clean`

```
~/p/t/p/react-test $ ng cache clean
Error: This command is not available when running the Angular CLI outside a workspace.
```

**Comment by Coly010** [comment]
A workaround for now would be to delete the `.angular/` directory.
