### ISSUE TITLE
Deploying to Azure link/page is not working (broken link)

### ISSUE THREAD

**Issue by luisphdsolutions** [nrwl/nx#20095]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.

### Additional context or description

Provide any additional details here as needed.

**Comment by FrozenPandaz** [comment]
Sorry, please fill out the issue template. We need more information to address this issue.
