### ISSUE TITLE
Add an option for "nx release changelog" to include merge commits messages only

### ISSUE THREAD

**Issue by MichalToldy** [nrwl/nx#20114]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Add a new option to the command `nx release changelog` to include merge commits messages only

## Motivation

As we don't use the option "squash commits" for merging, the changelog is polluted with feature branch commits. To have it more polished we would like to see only merge (conventional style) commits in the log.

**Comment by JamesHenry** [comment]
@MichalToldy please can you point me at an example of an existing tool that does this just so I have a full example?
