### ISSUE TITLE
nestjs and nextjs proxy configuration not working

### ISSUE THREAD

**Issue by AkshayCloudAnalogy** [nrwl/nx#2011]
## Expected Behavior

Communication between nextjs and nestjs app should work.

## Current Behavior

Currently it is throwing error when i try to call nestjs api from nextjs index page.

## Failure Information (for bugs)

Error is:
GET http://localhost:4200/api 404 (Not Found)

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a empty project with `nx create-nx-workspace@latest next-nest`
2. Add in dependencies with `yarn add --dev @nrwl/next @nrwl/nest`
3. Create nextjs project with `nx g @nrwl/next:app next-app`
4. Create nestjs project and create proxy with `nx g @nrwl/nest:app nest-app --frontendProject=next-app`
5. Run both app with `nx serve nest-app` and `nx serve next-app`
6. Update `/pages/inde.tsx` to this:
```jsx
import React, { useEffect } from 'react';
export const Index = () => {
  useEffect(() => {
    fetch('/api')
      .then(r => r.json())
      .then(res => console.log);
  }, []);
  return <div>Next App</div>;
};
export default Index;
```

### Context

Even `proxy.config.json` file is created in next-app it is still not able to connect properly.
However i have found solution with express server but there is no details available how i can use `server.js` inside nextjs project and serve it.
- next-app is running on port `4200`
- nest-app is running on port `3333`
- Successful response from api when opened `http://localhost:3333/api` that is
```json
{
"message": "Welcome to nest-app!"
}
```

### Failure Logs

Error in console is:
GET http://localhost:4200/api 404 (Not Found)

## Other

Here is the git repo url for the project:
https://github.com/AkshayCloudAnalogy/next-nest.git

**Comment by FrozenPandaz** [comment]
The next app does not support proxies yet but it's generated.

@vsavkin Can proxy support be added to Next apps?

**Comment by dacarley** [comment]
Any update on this issue?

**Comment by jdpearce** [comment]
@dacarley - not yet, sorry. We're considering it, but have to find time to investigate and implement.

Next.js support is something I'm personally looking at in detail this year though, so expect this issue to get some attention sooner rather than later.
