### ISSUE TITLE
load environment variables from configuration name will cover vite modes

### ISSUE THREAD

**Issue by AttackXiaoJinJin** [nrwl/nx#20111]
### Current Behavior

nx version：https://github.com/nrwl/nx/releases/tag/16.5.0-beta.1

project.json：
```
 "build": {
      ...
      "defaultConfiguration": "production",
      "configurations": {
        "development": {
          "mode": "development"
        },
        "production": {
          "mode": "production"
        }
      }
    },
```

package.json：
```
 "build:my-project:staging": "nx build web-hub --mode staging",
```
 before nx 16.5.0-beta.1，I use the command `build:my-project:staging`，vite will use the `.env.staging` file to load environment variables：

https://vitejs.dev/guide/env-and-mode.html#modes

![image](https://github.com/nrwl/nx/assets/26433572/d8a313f0-45cb-4129-93ad-11bf3e4c6465)

BUT，after `16.5.0-beta.1`，especially in：https://github.com/nrwl/nx/pull/17335

![image](https://github.com/nrwl/nx/assets/26433572/7eb5d15b-c03a-4763-a811-abfec708049d)

the vite modes is OUT OF WORK

and the document doesn't mention this： https://nx.dev/core-features/plugin-features/use-task-executors#use-executor-configurations

![image](https://github.com/nrwl/nx/assets/26433572/fd32f66d-fa3c-454e-b1de-730444811770)

### Expected Behavior

I hope you can add some EXPLAIN in docs，and the best is let vite modes cover nx configurations！！

### Steps to Reproduce

see above

### Nx Report

```shell
see above
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
@AttackXiaoJinJin thanks for filing an issue! Can you please try this out with the latest version of Nx and let me know if you're still facing the same issue? We did a number of refactors to the vite executors, and your issue may have gone away.

In the meantime, can you please also provide a minimal reproduction repository? This will help me a lot in narrowing down and solving your issue!

**Comment by mandarini** [comment]
Here is my reproduction repository, different modes are getting applied, with the caveat that I removed `defaultConfiguration`:

https://github.com/mandarini/vite-nx-modes

**Comment by mandarini** [comment]
Ok, I investigated more and you are correct. Even if I remove the default modes, the `configuration` will get applied, due to the linked PR.

We will fix this.

**Comment by mandarini** [comment]
In the meantime, your workaround would be to have 

```
 "build": {
      ...
      "defaultConfiguration": "production",
      "configurations": {
        "development": {
          "mode": "development"
        },
        "production": {
          "mode": "production"
        },
        "staging": {
          "mode": "staging"
        }
      }
    },
```

an extra `staging` configuration

**Comment by AttackXiaoJinJin** [comment]
@mandarini thank you for the fix ! !
