### ISSUE TITLE
Nx migrates to mocking performance.mark for angular unnecesarily

### ISSUE THREAD

**Issue by yharaskrik** [nrwl/nx#20127]
### Current Behavior

As of the v17 beta migrations Nx adds

```
/**
 * Angular uses performance.mark() which is not supported by jsdom. Stub it out to avoid errors.
 */
global.performance.mark = jest.fn();
```

To the test setup files for jest. 

### Expected Behavior

As of the linked PR (include din v17) that is not needed anymore as usages are now guarded.

### GitHub Repo

https://github.com/angular/angular/pull/52505

### Steps to Reproduce

1.

### Nx Report

```shell
v1 - beta
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This has already been fixed by https://github.com/nrwl/nx/pull/20120 and it will be released in the stable version. Angular released that change after we had addressed the issue on our side, but luckily we don't need to do that anymore.
