### ISSUE TITLE
Generators no longer run with `NX Cannot use import statement outside a module` error

### ISSUE THREAD

**Issue by joelkesler** [nrwl/nx#20141]
### Current Behavior

 ```
 npx nx g my-generator --name=hello

>  NX  Generating my-plugin:my-generator


 >  NX   Cannot use import statement outside a module
```

### Expected Behavior

The generator should run and generate what it expected

### Steps to Reproduce

1. try and run a previously working generator. 

The generator lives in a workspace plugin inside the `tools` folder:
```
./tools/workspace-plugin/src/generators
```

### Nx Report

```shell
   Node   : 18.16.0
   OS     : darwin-x64
   npm    : 9.5.1
   
   nx (global)        : 17.0.2
   nx                 : 17.0.2
   @nx/js             : 17.0.2
   @nx/jest           : 17.0.2
   @nx/linter         : 17.0.2
   @nx/eslint         : 17.0.2
   @nx/workspace      : 17.0.2
   @nx/angular        : 17.0.2
   @nx/cypress        : 17.0.2
   @nx/devkit         : 17.0.2
   @nx/eslint-plugin  : 17.0.2
   @nx/plugin         : 17.0.2
   @nx/storybook      : 17.0.2
   @nrwl/tao          : 17.0.2
   @nx/web            : 17.0.2
   @nx/webpack        : 17.0.2
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @ngneat/spectator  : 14.0.0
   @rx-angular/state  : 1.7.0
   @storybook/angular : 7.5.2
   angular-calendar   : 0.31.0
   ng2-charts         : 4.1.1
   ---------------------------------------
   Local workspace plugins:
         @galaxy/workspace-plugin
         my-plugin
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Generators seems to break often on nx updates.

The ways to use them also changes quite quickly. Most tutorials are well out of date after a year or two. For example, the commands in this helpful article don't work anymore due to breaking changes: https://blog.nrwl.io/using-nx-workspace-generators-to-scaffold-new-blog-posts-8c8162cf857b

**Comment by skrtheboss** [comment]
Maybe related to #19475

**Comment by mhelm306** [comment]
I have a similar issue with using any generator from the @nx/plugin package fails to build due to an improper import in the schema.d.ts for several generators.
 they import `ProjectNameAndRootFormat` from `'@nx/devkit/src/generators/project-name-directory-utils'` which is a file that no longer exists, instead of from ` '@nx/devkit/src/generators/project-name-and-root-utils'`. I can't use any generators or executers from that package until it's fixed.
