### ISSUE TITLE
Update Redux Starter Kit to 1.0

### ISSUE THREAD

**Issue by markerikson** [nrwl/nx#2014]
I see that Nx has already [updated Redux Starter Kit to v0.8.0](https://github.com/nrwl/nx/blob/3a191dd30c6bd9971b1dd35cb1cccf3e432c8f17/packages/react/src/utils/versions.ts#L19), including [dealing with the breaking change in the migration](https://github.com/nrwl/nx/blob/c63e93ea6cd2248b00418a3ad9b2041129d703be/packages/react/src/migrations/update-8-7-0/update-8-7-0.ts).

We just released [Redux Starter Kit 1.0](https://github.com/reduxjs/redux-starter-kit/releases/tag/v1.0.0), and I'd like to see Nx updated to use that.  (also, FYI, I'm actually going to put out 1.0.1 in the next day or two.)

**Comment by FrozenPandaz** [comment]
Congratulations on the 1.0!

Thank you so much for letting us know. We will be sure to update soon!

**Comment by FrozenPandaz** [comment]
This was fixed with https://github.com/nrwl/nx/pull/2089 :tada:

**Comment by markerikson** [comment]
Great, thanks!
