### ISSUE TITLE
--skipNxCache does not update the cache

### ISSUE THREAD

**Issue by marcvangend** [nrwl/nx#20176]
### Current Behavior

When running a target with the `--skipNxCache` option, the existing cache is not updated. As a result, `--skipNxCache` cannot be used to solve incorrect cache situations.

Situation: While running `nx run-many -t lint` I noticed that somehow my cache had gotten out of sync. A changed project, which I knew contained a linting error, was reported as succeeded and read from cache. Next I ran `nx run-many -t lint --skipNxCache` and indeed, the project was linted and reported as failed. I expected that this would have updated the cache. However, when running `nx run-many -t lint` again (without solving the issue), the project was once more reported as succeeded.

### Expected Behavior

When using the `--skipNxCache` option, I expect NX to **not read** from cache, but to still **write** to cache. 

Alternatively, I would at least expect the `--skipNxCache` option to invalidate the cache for that operation.

### Steps to Reproduce

1. Run `nx reset` so there is no cache
2. Run a target with the `--skipNxCache` option, eg. `nx run-many -t lint`
3. Run the same target without `--skipNxCache` - I expect things to be cached now

### Nx Report

```shell
Node   : 20.4.0
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx                 : 17.0.3
   @nx/js             : 17.0.3
   @nx/linter         : 17.0.3
   @nx/eslint         : 17.0.3
   @nx/workspace      : 17.0.3
   @nx/cypress        : 17.0.3
   @nx/devkit         : 17.0.3
   @nx/eslint-plugin  : 17.0.3
   @nx/playwright     : 17.0.3
   @nx/react          : 17.0.3
   @nx/rollup         : 17.0.3
   @nrwl/tao          : 17.0.3
   @nx/vite           : 17.0.3
   @nx/web            : 17.0.3
   typescript         : 5.1.6
```

### Package Manager Version

1.22.19

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
This is the expected behavior. `--skipNxCache` skips both reading and writing from the cache. If you want to invalidate the cache, `nx reset` is the way to go.
