### ISSUE TITLE
Enabling gzip and brotli compression in Angular esbuild

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [nrwl/nx#20180]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Is there possibility to add configuration in angular for some plugins like brotli/gzip compression?

## Motivation
It would be nice to have ability to configure that in nx to build complete statically served optimized web site - brotli/gzip compression would help in that

**Comment by Coly010** [comment]
Hi @AdaskoTheBeAsT 

This isn't something that is done at build time. 

gzip/brotli compression should be enabled in your hosting service / server, as it needs to send the correct headers to the browser on file request for the browser to correctly decompress the files. 

https://docs.nginx.com/nginx/admin-guide/web-server/compression/
https://vercel.com/docs/edge-network/compression

**Comment by AdaskoTheBeAsT** [comment]
@Coly010  please consider situation when there is popular site - compressing assets on every request can add overhead as it is described in first article "However, since compression happens at runtime it can also add considerable processing overhead which can negatively affect performance."

Both nginx gzip module and brotli module allows to serve precompressed files as it is described here:
https://nginx.org/en/docs/http/ngx_http_gzip_static_module.html 
https://github.com/google/ngx_brotli#brotli_static 

in case of webpack it is simple modification of webpack.config.js

```js
const { merge } = require('webpack-merge');
const CompressionPlugin = require('compression-webpack-plugin');
const zlib = require('zlib');

module.exports = (config, context) => {
  return merge(config, {
    plugins: [
      new CompressionPlugin({
        algorithm: 'gzip',
        deleteOriginalAssets: false,
        test: /\.(js|css|html|svg|ttf)$/,
        threshold: 1024,
        minRatio: 0.8,
        compressionOptions: {
          level: 9,
        },
      }),
      new CompressionPlugin({
        filename: '[path][base].br',
        algorithm: 'brotliCompress',
        deleteOriginalAssets: false,
        test: /\.(js|css|html|svg|ttf)$/,
        threshold: 1024,
        minRatio: 0.8,
        compressionOptions: {
          params: {
            [zlib.constants.BROTLI_PARAM_QUALITY]: 11,
          },
        },
      }),
    ],
  });
};
```

**Comment by dlq84** [comment]
That's more a general ability to specify custom esbuild plugins, and that's something I really would like too. The angular devkit does support: https://github.com/angular/angular-cli/blob/a556f6cdf3adfa8a475a9e0358c1c34c12b9c527/packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts#L36
