### ISSUE TITLE
Stop sorting tsconfig.base.json paths, order is important

### ISSUE THREAD

**Issue by SimoneGianni** [nrwl/nx#20190]
### Current Behavior

Nx format:write sorts the tsconfig.base.json paths, this is done on purpose see #5945

### Expected Behavior

It should absolutely not touch it, because the order *IS* significant, see (unanswered) #6072 , #6472 , and a few others.

### Steps to Reproduce

1. Create a TS integrated mono repo
2. Add something to the tsconfig.base.json paths, either manually or by creating packages
3. Sort them out in the order your application needs
4. Commit, or otherwise execute format:write
5. See that it sorted it out

### Nx Report

```shell
Node   : 18.12.1
   OS     : linux-x64
   npm    : 8.19.2
   
   nx                 : 16.7.4
   @nx/js             : 16.6.0
   @nx/jest           : 16.7.4
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.7.4
   @nx/devkit         : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nrwl/tao          : 16.7.4
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @jscutlery/semver : 3.1.0
   ---------------------------------------
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The original PR #5945 should be reverted, while it avoids a minor nuissance of a merge conflicts, it breaks applications because the order of paths in the tsconfig file is significant and cannot simply be string-sorted by default. 

At least offer an opt-out option for those who knows how to use a tsconfig file and how to solve a git conflict.

**Comment by Cammisuli** [comment]
@SimoneGianni can you give an example (other than the two issues that you linked) of where the order matters?

**Comment by FrozenPandaz** [comment]
Closing this issue as it hasn't been updated with more information in a while since it was requested. If you continue experiencing this issue, please open a new issue with updated information.
