### ISSUE TITLE
Export @nx/js:tsc executor to be used programatically

### ISSUE THREAD

**Issue by amit-wolfus-lmnd** [nrwl/nx#20208]
- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Export tsc executor from `@nx/js` package so it can be used by custom executors

## Motivation
Creating a build executor that internally uses `tsc` with pre-configured options, this is currently not possible since the executor is not exported from the module.

## Suggested Implementation
export the runExector function like it is exported for other executors (`@nx/webpack` for example)

**Comment by woppa684** [comment]
You can just 

```ts
import { tscExecutor } from '@nx/js/src/executors/tsc/tsc.impl';
```

right?
