### ISSUE TITLE
Nx errors when run in a workspace generated by the Angular CLI

### ISSUE THREAD

**Issue by jdpearce** [nrwl/nx#2021]
## Expected Behavior

Some kind of output which indicates that Nx is aware it can't be used in the current workspace. Possibly even a message which tells the user how to upgrade the current workspace to an Nx workspace?

At the very least, _not_ an error.

## Current Behavior

```bash
▶ nx
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '<cut for brevity>/node_modules/@nrwl/cli/bin/nx.js'
```

### Steps to Reproduce

Run `nx` in a workspace generated by the Angular CLI.

e.g. 

`ng generate new-workspace --create-application=false`
`cd new-workspace`
`nx`

This is far too easily done if you're playing with Angular CLI and Nx workspaces side by side :)

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.
