### ISSUE TITLE
Add missing parameter to documentation of the Generate Command

### ISSUE THREAD

**Issue by jackmorizo** [nrwl/nx#20221]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/nx-api/nx/documents/generate

### Additional context or description

**TLDR:** Add the `quiet` option to the documentation-page 

**Explanation**
I am developing custom generators and executors for the CI/CD pipelines in the company I am working in.
When I use the generate command e.g.: `npx nx generate @my/plugin:my-generator ...` I have noticed that nx ix always printing:
`>  NX  Generating @my/plugin:my-generator` 

Now this is not a big deal when you use generators not in an automated way and if you don't want to process the outputs your generators. However if you want to utilize your generator in your pipelines then it might be useful to pass in the `--quiet` option e.g.: 
`npx nx generate --quiet @my/plugin:my-generator ...`. This makes it easier to use the outputs of your generators in your pipelines.

**Here is the Issue:**
Unfortunately you have to dig through the source code in order to know that this option exists because it is not in the [documentation](https://nx.dev/nx-api/nx/documents/generate#options). I have wasted several hours searching through the docs and even tried out other over-engineered solutions until I looked through the source-code where I found this (which solved my issue): https://github.com/nrwl/nx/blob/059b061bfeeee5bb98c5ea80e3085a0971f306a1/packages/nx/src/command-line/generate/generate.ts#L330C36-L330C36

**Comment by AgentEnder** [comment]
Sounds good, can you open a PR adding it?
