### ISSUE TITLE
Nx ignoring root level scripts listed in `dependsOn`

### ISSUE THREAD

**Issue by drew-y** [nrwl/nx#20229]
### Current Behavior

nx is ignoring root level scripts specified in a project's target. No errors are reported, other dependencies are run. Just not the root level script

Given root `package.json`:
```
  "scripts": {
    "nx-prepare": "npm install"
  },
  "nx": {
    "includedScripts": [
      "nx-prepare"
    ],
    "targets": {
      "nx-prepare": {
        "inputs": [
          "{projectRoot}/package.json",
          "{projectRoot}/package-lock.json",
          "{projectRoot}/yarn.lock"
        ]
      }
    }
  },
```

Root level `nx.json`:
```
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "npmScope": "services",
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": ["nx-prepare", "build", "lint", "test"]
      }
    }
  },
  "targetDefaults": {
    "build": {
      "dependsOn": ["^nx-prepare", "^build"],
      "inputs": ["production", "^production"]
    },
    "lint": {
      "inputs": ["default", "{workspaceRoot}/.eslintrc.json"]
    },
    "test": {
      "inputs": ["default", "^production", "{workspaceRoot}/jest.preset.js"],
      "dependsOn": ["^build"]
    }
  },
  "namedInputs": {
    "default": ["{projectRoot}/**/*", "sharedGlobals"],
    "production": [
      "default",
      "!{projectRoot}/**/?(*.)+(spec|test).[jt]s?(x)?(.snap)",
      "!{projectRoot}/tsconfig.spec.json",
      "!{projectRoot}/jest.config.[jt]s",
      "!{projectRoot}/.eslintrc.json"
    ],
    "sharedGlobals": []
  },
  "defaultProject": "api"
}
```

And the `project.json` for a project called workspace:
```
{
  "name": "workspace",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/workspace/src",
  "projectType": "application",
  "implicitDependencies": ["integrations"],
  "targets": {
    "build": {
      "executor": "nx:run-commands",
      "options": {
        "cwd": "apps/workspace",
        "commands": [{ "command": "bash build.bash", "forwardAllArgs": false }]
      }
    },

    "deploy": {
      "executor": "nx:run-commands",
      "dependsOn": ["synth"],
      "options": {
        "cwd": "apps/workspace",
        "commands": ["cdk deploy --require-approval never --output cdk.out"]
      }
    },

    "lint": {
      "executor": "@nrwl/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["apps/workspace/**/*.ts"]
      }
    },

    "synth": {
      "executor": "nx:run-commands",
      "dependsOn": ["build"],
      "options": {
        "cwd": "apps/workspace",
        "commands": ["cdk synth --output cdk.out"]
      }
    },

    "test": {
      "executor": "@nrwl/jest:jest",
      "outputs": ["{workspaceRoot}/coverage/{projectRoot}"],
      "options": {
        "jestConfig": "apps/workspace/jest.config.ts",
        "passWithNoTests": true,
        "codeCoverage": true
      }
    }
  },
  "tags": []
}
```

I can successfully run the script using `yarn nx nx-prepare`.

### Expected Behavior

I'd expect `yarn nx build workspace --skip-nx-cache --verbose` to run the `nx-prepare` script. But it does not (with or without the cache and verbose flags).

### GitHub Repo

https://github.com/drew-y/nx-root-script-issue

### Steps to Reproduce

I was able to reproduce on a forked instance of nx example

1. `git clone git@github.com:drew-y/nx-root-script-issue.git `
1. `yarn`
2. `yarn nx build cart`

Expected `npm install` to run, does not happen.

Tested using nx `v17` as used by nx example, and using nx `v15.9` used in our project.

### Nx Report

```shell
Node   : 18.18.2
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx                 : 17.1.0-rc.0
   @nx/js             : 17.1.0-rc.0
   @nx/jest           : 17.1.0-rc.0
   @nx/linter         : 17.1.0-rc.0
   @nx/eslint         : 17.1.0-rc.0
   @nx/workspace      : 17.1.0-rc.0
   @nx/angular        : 17.1.0-rc.0
   @nx/cypress        : 17.1.0-rc.0
   @nx/devkit         : 17.1.0-rc.0
   @nx/eslint-plugin  : 17.1.0-rc.0
   @nx/react          : 17.1.0-rc.0
   @nrwl/tao          : 17.1.0-rc.0
   @nx/web            : 17.1.0-rc.0
   @nx/webpack        : 17.1.0-rc.0
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 16.0.0
   @ngrx/effects         : 16.0.0
   @ngrx/entity          : 16.0.0
   @ngrx/router-store    : 16.0.0
   @ngrx/store           : 16.0.0
   @ngrx/store-devtools  : 16.0.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I see that this was reportedly fixed [here](https://github.com/nrwl/nx/issues/14386). But I have been unable to get it to work. Maybe it broke again? Or I might be doing something wrong. Any help would be appreciated. Thanks!

**Comment by AgentEnder** [comment]
The `^` symbol in `dependsOn` strings refers to all instances of that target, on the given project's dependencies. Its highly likely that your projects dont have a dependency on the root project, thus its not being ran.

You can either add an implicit dependency to your projects that points to the root project, or point specifically to the root project when putting it in dependsOn, like so:

```
dependsOn: [{
  target: 'nx-prepare',
  project: 'nx-example'
}]
```

**Comment by drew-y** [comment]
Hey @AgentEnder. Thanks for the response. I definitely did not have a dependency on the root project. I was able to get this working by adding the root project, `nx-example`, to the implicit dependencies with `^nx-prepare` in the `dependsOn`. 

FWIW, the `{ target: 'nx-prepare', project: 'nx-example' }` syntax didn't seem to work, regardless of my implicit dependencies.

In hindsight, this makes perfect sense. Would it be worth adding this information to the [root level scripts recipe](https://nx.dev/recipes/running-tasks/root-level-scripts#configuring-a-rootlevel-target)?

Thanks again for the help!
