### ISSUE TITLE
nx migrate latest breaks package.json/npm install for v17.1.x

### ISSUE THREAD

**Issue by dloetzke** [nrwl/nx#20233]
### Current Behavior

In a new NX standalone repository, `nx migrate latest` (also goes for 17.1.0 and 17.1.1) seems to work, but the then following `npm install` fails when updating from v16.10.0 as well as v17.0.3.

### Expected Behavior

`nx migrate latest` updates NX to the latest version without `npm install` failing to install the new versions.

### GitHub Repo

https://github.com/dloetzke/nx1703to1712/pull/1

### Steps to Reproduce

1. Create NX v17.0.3 standalone repository.
2. `npm install` works fine.
3. Run `nx migrate latest` to migrate to NX v17.1.2.
4. `npm install` no longer works.

### Nx Report

```shell
   Node   : 18.18.2
   OS     : win32-x64
   npm    : 9.8.1

   nx (global)        : 17.0.3
   nx                 : 17.0.3
   @nx/js             : 17.0.3
   @nx/jest           : 17.0.3
   @nx/linter         : 17.0.3
   @nx/eslint         : 17.0.3
   @nx/workspace      : 17.0.3
   @nx/angular        : 17.0.3
   @nx/cypress        : 17.0.3
   @nx/devkit         : 17.0.3
   @nx/eslint-plugin  : 17.0.3
   @nrwl/tao          : 17.0.3
   @nx/web            : 17.0.3
   @nx/webpack        : 17.0.3
   typescript         : 5.1.6
```

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

The [linked repository](https://github.com/dloetzke/nx1703to1712) contains a main branch with a freshly setup NX v17.0.3 standalone repository as well as the branch `17-1-2` which is the main branch after running `nx migrate latest`. The PR into main shows `npm install` failing in a simple GitHub workflow, which also occurs locally under Windows 10.
Creating a new NX v17.1.2 standalone repository works fine, regardless of this problem.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This is a resolution issue with NPM. This problem doesn't occur with Yarn or PNPM. To workaround the issue, please run `npm install --legacy-peer-deps`.
