### ISSUE TITLE
Local dev server with many remotes produces MaxListenersExceededWarning

### ISSUE THREAD

**Issue by minijus** [nrwl/nx#20230]
### Current Behavior

Running local dev server with Angular MF and many remotes produces warnings (MaxListenersExceededWarning):
![image](https://github.com/nrwl/nx/assets/3633549/253e0926-424e-40f3-8d52-60a277a5461c)

### Expected Behavior

Handle static remotes serving with single listener. Instead of creating listener for each remote it should have one listener for all of them.
https://github.com/nrwl/nx/blob/master/packages/angular/src/builders/module-federation-dev-server/module-federation-dev-server.impl.ts#L86-L87

### Steps to Reproduce

1. Launch dev server for Angular application with many remotes (in our case 11)

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.9.0
   OS     : darwin-arm64
   npm    : 10.2.3
   
   nx                 : 17.1.2
   @nx/js             : 17.1.2
   @nx/jest           : 17.1.2
   @nx/linter         : 17.1.2
   @nx/eslint         : 17.1.2
   @nx/workspace      : 17.1.2
   @nx/angular        : 17.1.2
   @nx/cypress        : 17.1.2
   @nx/devkit         : 17.1.2
   @nx/eslint-plugin  : 17.1.2
   @nx/nest           : 17.1.2
   @nx/node           : 17.1.2
   @nx/plugin         : 17.1.2
   @nrwl/tao          : 17.1.2
   @nx/web            : 17.1.2
   @nx/webpack        : 17.1.2
   nx-cloud           : 16.4.0
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @ngrx/effects        : 16.3.0
   @ngrx/entity         : 16.3.0
   @ngrx/eslint-plugin  : 16.3.0
   @ngrx/router-store   : 16.3.0
   @ngrx/schematics     : 16.3.0
   @ngrx/store          : 16.3.0
   @ngrx/store-devtools : 16.3.0
   ---------------------------------------
   Local workspace plugins:
   	 @company/workspace-plugin
   	 @company-tools/nx-plugin
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
This should be fixed by https://github.com/nrwl/nx/pull/20006 which hasn't been released yet.

@minijus I'll see if we can get a release done soon containing this.
