### ISSUE TITLE
Cannot deploy nestjs backend to serveless computing solution like AWS lambda or firebase functions

### ISSUE THREAD

**Issue by some1awesome** [nrwl/nx#20255]
### Current Behavior

After upgrading to nx 17.1.2 we can no longer deploy our project to AWS lambda or google firebase functions.  

When uploading to firebase functions the firebase cli can't seem to find the firebase functions we are trying to upload.

When uploading to AWS the library is uploaded properly but when we try to hit the endpoint through api gateway we get an error saying it cannot find main.handler.

### Expected Behavior

Projects should be able to be uploaded to firebase function and AWS lambda and still work properly once uploaded. 

### GitHub Repo

https://github.com/some1awesome/nestjs-upgrade-serverless-issue

### Steps to Reproduce

1. Run nx build

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.9.0
   OS     : darwin-arm64
   npm    : 10.1.0
   
   nx                 : 17.1.2
   @nx/js             : 17.1.2
   @nx/jest           : 17.1.2
   @nx/linter         : 17.1.2
   @nx/eslint         : 17.1.2
   @nx/workspace      : 17.1.2
   @nx/devkit         : 17.1.2
   @nx/eslint-plugin  : 17.1.2
   @nx/nest           : 17.1.2
   @nx/node           : 17.1.2
   @nrwl/tao          : 17.1.2
   @nx/webpack        : 17.1.2
   typescript         : 5.2.2
```

### Failure Logs

```shell
When uploading to firebase functions:
The following functions are found in your project but do not exist in your local source code:
        testApi(us-central1)

When trying to hit aws lambda:
"Runtime.HandlerNotFound: dist/apps/tools-server/main.handler is undefined or not exported",
        "    at UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1122:15)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

We have isolated the problem to be due to the latest upgrade of @nx/webpack, if we run `nx migrate @nx/webpack --to="@nx/webpack@16.10.0"` it begins to work properly again.  

It seems to be due to the absence of the following lines of code:

`var __webpack_export_target__ = exports;
for(var i in __webpack_exports__) __webpack_export_target__[i] = __webpack_exports__[i];
if(__webpack_exports__.__esModule) Object.defineProperty(__webpack_export_target__, "__esModule", { value: true });
/******/ })()`

If after running the build those lines are added in then we can upload and run the server properly, but the original build does not include those lines.

If you want to fully test it you will need a blaze plan firebase account.  Then you can change the firebase.json to point at that account and try uploading the testApi. To do so run the following:

1) npm run build:functions
2) firebase deploy --only functions:testApi

**Comment by mahmok-lego** [comment]
I am also experiencing the same issue

**Comment by joain946** [comment]
I also have the same issue. It works with "17.1.0-beta.4" but not with "17.1.1".

**Comment by JumBay** [comment]
Same with 17.1.3

**Comment by iwt-DennisVeitinger** [comment]
We were able to resolve this issue by adding the following to our webpack.config.ts:
`    output: {
      libraryTarget: 'commonjs2',
    },`
