### ISSUE TITLE
publish latest @nrwl/builders to NPM registry

### ISSUE THREAD

**Issue by DmitryEfimenko** [nrwl/nx#2025]
## Expected Behavior

NPM registry should have latest version of @nrwl/builders available.

## Current Behavior

* NPM registry shows version 7.8.7 as latest.
* NPM registry versions tab shows that version 8.0.2 is also available

## Failure Information (for bugs)

I'm assuming that 8.0.2 is not the latest version because I've tried using it, but it throws an error:
> Cannot find module '..\node_modules\@nrwl\builders\src\builders.json'

Looking deeper at it, the `src` folder isn't there under `node_modules\@nrwl\builders`.
I assume this should be fixed in the actual latest version.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. add a react app to your workspace
2. in the angular.json file make sure to use builder: `@nrwl/builders:web-build` for this app
3. run `npm run build -- myreactapp`

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context

Please provide any relevant information about your setup:

    "@nrwl/angular": "^8.6.0",
    "@nrwl/builders": "^8.0.2",
    "@nrwl/cypress": "8.6.0",
    "@nrwl/jest": "8.6.0",
    "@nrwl/react": "^8.6.0",
    "@nrwl/web": "8.6.0",
    "@nrwl/workspace": "^8.6.0",

**Comment by brandonroberts** [comment]
The last version of `@nrwl/builders` is `7.8.7`. Starting with 8.x of Nx, the packages were renamed. See the migration guide for more info: https://nx.dev/angular/guides/nx7-to-nx8

**Comment by DmitryEfimenko** [comment]
I see. Thanks for the reply. Perhaps it'd be beneficial to update the README.md of @nrwl/builders to include this information on the top (and publish it to npm). There are quite a few outdated articles flowing around with incorrect information.
