### ISSUE TITLE
Best way of updating NX in repo with multiple active branches

### ISSUE THREAD

**Issue by michelcve** [nrwl/nx#2026]
What is the best way to update NX in a repo with multiple active branches?

Should nx update be run on each active branch, or should a seperate branch be created and merged for that (but how about config changes for individual libraries? wouldn't be nice to have to do those manually?).

**Comment by mehrad-rafigh** [comment]
Hi @michelcve
This really depends. Do your branches have a merge-base? If so, update nx und that merge-base and rebase your other branches on the merge-base.

**Comment by michelcve** [comment]
Hi @mehrad-rafigh (and others tuning in ;-))

I'm not sure what you mean with 'do your branches have a merge-base', but basically our (simplified) situation is like this:

```
develop
  |--- Feature branch 1
  |--- Feature branch 2
  |     |--- Subitem branch 1
  |     \--- Subitem branch 2
  |--- Feature branch 3
  \--- Feature branch 4
```

My concern is that if I update NX on develop, the libraries that were added in e.g. Feature branch 1 or Subitem branch 2, are not 'converted' by NX, which would pose a problem when merging.

The alternative is that I update NX seperately on all branches, which would make sure all libraries are converted. Then I can merge develop back to all branches, and I should be okay.


I hope this clarifies my question a bit more.

**Comment by brandonroberts** [comment]
@michelcve Ideally, you would land the updates to Nx in master, and then merge/rebase the other branches on top of those changes. This is outside the scope of Nx though

**Comment by michelcve** [comment]
@brandonroberts But what if NX changes how a library looks (e.g., modifies some tsconfig.json in all libraries). How would you correct this for branches that have a bunch of new libraries already?

The merge/rebase wouldn't be sufficient, and manually fixing the tsconfig's in all running branches that have new libraries doesn't seam feasable.

Is there a command I can run that could 'fix' these issues?

Also could you elaborate on why is this outside the scope of Nx? As Nx is promoting monorepo structures, I would expect a well documented upgrade path.
