### ISSUE TITLE
NX is broken local

### ISSUE THREAD

**Issue by itronmya** [nrwl/nx#20268]
### Current Behavior

I could not able to run NX locally

![image](https://github.com/nrwl/nx/assets/144651641/61d240dd-ddde-482f-89c7-4310d2847568)

NX workspace version: 16.5.1
Node: 16.6.0
Npm: 8.11.0

### Expected Behavior

NX should work

### Steps to Reproduce

1. Post upgrade npm, nx fails to execute

### Nx Report

```shell
NX is not available
```

### Failure Logs

11659 timing build:run:install:node_modules/@parcel/watcher Completed in 44019ms
11660 timing build:run:install Completed in 44020ms
11661 info run @nestjs/core@9.3.11 postinstall node_modules/@nestjs/core opencollective || exit 0
11662 info run @openapitools/openapi-generator-cli@2.7.0 postinstall node_modules/@openapitools/openapi-generator-cli opencollective || exit 0
11663 info run es5-ext@0.10.62 postinstall node_modules/es5-ext  node -e "try{require('./_postinstall')}catch(e){}" || exit 0
11664 info run esbuild@0.17.19 postinstall node_modules/esbuild node install.js
11665 info run nx@16.5.3 postinstall node_modules/nx node ./bin/post-install
11666 info run nx@16.5.1 postinstall node_modules/@angular-eslint/builder/node_modules/nx node ./bin/post-install
11667 info run nx@15.9.3 postinstall node_modules/@nrwl/cli/node_modules/nx node ./bin/compute-project-graph
11668 info run es5-ext@0.10.62 postinstall { code: 0, signal: null }
11669 timing build:run:postinstall:node_modules/es5-ext Completed in 3658ms
11670 info run @nestjs/core@9.3.11 postinstall { code: 0, signal: null }
11671 timing build:run:postinstall:node_modules/@nestjs/core Completed in 3712ms
11672 info run @openapitools/openapi-generator-cli@2.7.0 postinstall { code: 0, signal: null }
11673 timing build:run:postinstall:node_modules/@openapitools/openapi-generator-cli Completed in 4464ms
11674 info run esbuild@0.17.19 postinstall { code: 0, signal: null }
11675 timing build:run:postinstall:node_modules/esbuild Completed in 4614ms
11676 info run nx@16.5.1 postinstall { code: 0, signal: null }
11677 timing build:run:postinstall:node_modules/@angular-eslint/builder/node_modules/nx Completed in 3999ms
11678 info run nx@15.9.3 postinstall { code: 0, signal: null }
11679 timing build:run:postinstall:node_modules/@nrwl/cli/node_modules/nx Completed in 3113ms
11680 info run nx@16.5.3 postinstall { code: 1, signal: null }
11681 timing reify:rollback:createSparse Completed in 24828ms
11682 timing reify:rollback:retireShallow Completed in 0ms
11683 timing command:i Completed in 398576ms
11684 verbose stack Error: command failed
11684 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:63:27)
11684 verbose stack     at ChildProcess.emit (node:events:527:28)
11684 verbose stack     at maybeClose (node:internal/child_process:1092:16)
11684 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
11685 verbose pkgid nx@16.5.3
11686 verbose cwd C:\Yasar\Repos\OO.UI
11687 verbose Windows_NT 10.0.22621
11688 verbose node v16.16.0
11689 verbose npm  v8.11.0
11690 error code 1
11691 error path C:\Yasar\Repos\OO.UI\node_modules\nx
11692 error command failed
11693 error command C:\WINDOWS\system32\cmd.exe /d /s /c node ./bin/post-install
11694 error >  NX   Missing Platform Dependency
11694 error
11694 error    The Nx CLI could not find or load the native binary for your supported platform (win32-ia32).
11694 error    This likely means that optional dependencies were not installed correctly, or your system is missing some system dependencies.
11694 error    For more information please see https://nx.dev/recipes/ci/troubleshoot-nx-install-issues
11695 verbose exit 1
11696 timing npm Completed in 398799ms
11697 verbose unfinished npm timer reify 1700117086298
11698 verbose unfinished npm timer reify:build 1700117406555
11699 verbose unfinished npm timer build 1700117406563
11700 verbose unfinished npm timer build:deps 1700117406564
11701 verbose unfinished npm timer build:run:postinstall 1700117453797
11702 verbose unfinished npm timer build:run:postinstall:node_modules/nx 1700117453907
11703 verbose code 1

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by bridzius** [comment]
Based on platform support - https://nx.dev/recipes/troubleshooting/troubleshoot-nx-install-issues#supported-native-module-platforms (link in error message) - NX doesn't support 32bit (`win32-ia32`) Windows installs.

**Comment by itronmya** [comment]
Yeah, Figure it out. Thanks
