### ISSUE TITLE
Linting Issue in New Next.js Standalone Projects Created with create-nx-workspace

### ISSUE THREAD

**Issue by jared-christensen** [nrwl/nx#20279]
### Current Behavior

When creating a new Next.js standalone project using `create-nx-workspace`, the linting setup appears to be incorrect. Immediately after project creation, attempting to run linting results in failure.

### Expected Behavior

Linting should run correctly without errors immediately after project creation.

### GitHub Repo

https://github.com/jared-christensen/nx-lint-issue

### Steps to Reproduce

1.`npx create-nx-workspace`
  - Where would you like to create your workspace? › **nx-example** 
  - Which stack do you want to use? … **React**
  - What framework would you like to use? **Next.js**
  - Integrated monorepo, or standalone project? **Standalone**
  - Would you like to use the App Router (recommended)? **Yes**
  - Test runner to use for end to end (E2E) tests **Playwright**
  - Default stylesheet format **CSS**
  - Enable distributed caching to make your CI faster **No**

10. `npx nx run nx-example:lint` 

11. See linting errors

### Nx Report

```shell
Node   : 20.9.0
OS     : darwin-arm64
npm    : 10.1.0

nx (global)        : 17.0.2
nx                 : 17.1.2
@nx/js             : 17.1.2
@nx/jest           : 17.1.2
@nx/linter         : 17.1.2
@nx/eslint         : 17.1.2
@nx/workspace      : 17.1.2
@nx/devkit         : 17.1.2
@nx/eslint-plugin  : 17.1.2
@nx/next           : 17.1.2
@nx/playwright     : 17.1.2
@nx/react          : 17.1.2
@nrwl/tao          : 17.1.2
@nx/web            : 17.1.2
typescript         : 5.2.2
```

### Failure Logs

```shell
*  Executing task: npx nx run nx-example:lint 

> nx run nx-example:lint

Linting "nx-example"...

 >  NX   All files matching the following patterns are ignored:

   - './src/**/*.{ts,tsx,js,jsx}'
   
   Please check your '.eslintignore' file.
   Pass --verbose to see the stacktrace.
```

### Package Manager Version

npm -v 10.1.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I've managed to resolve the linting issues in my project. The key was adjusting the lintFilePatterns in project.json and modifying the ignorePatterns in eslintrc.json.

The changes I made are as follows:

Eslintrc.json:
Original: `"ignorePatterns": ["**/*", ".next/**/*"]`
Updated: `"ignorePatterns": ["!**/*", ".next/**/*"]`

Project.json:
Original: `"lintFilePatterns": ["./src/**/*.{ts,tsx,js,jsx}"]`
Updated: `"lintFilePatterns": ["./app/**/*.{ts,tsx,js,jsx}"]`

I've also created a pull request on my example repository to clearly demonstrate the changes that worked for me. You can view the detailed modifications here: [PR on nx-lint-issue](https://github.com/jared-christensen/nx-lint-issue/pull/1/files).

**Comment by brandoncroberts** [comment]
can confirm this issue exists also on v 17.1.3

**Comment by viraxslot** [comment]
Same issue for me. This fix helped `"ignorePatterns": ["!**/*", ".next/**/*"]`, thanks a lot!

**Comment by ndcunningham** [comment]
This should be fixed in the latest version. 
If not you can reopen this issue.
