### ISSUE TITLE
How can I add publicPath to assets (both js and html) while bundling?

### ISSUE THREAD

**Issue by navyaagarwal23** [nrwl/nx#2027]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

PublicPath should be prepended to assets in HTML file and JS files.

## Current Behavior

Public path does not come into play

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Added key publicPath in webpack config
2. Added key publicPath in workspace.json
3. Supplied output-public-path parameter in CLI

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context

Please provide any relevant information about your setup:

- version of Nx used (_Please run `nx report` at the root of your workspace and copy the results here if you are using Nx 8.6.1 or greater_)
- 3rd-party libraries and their versions
- and most importantly - a use-case that fails

**A minimal reproduction scenario allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

Please include any relevant log snippets or files here.

## Other

Any other relevant information that will help us help you.

**Comment by brandonroberts** [comment]
@navyaagarwal23 can you provide a repo that reproduces this issue with the latest version of Nx?

**Comment by ZachJW34** [comment]
This is a known limitation of the angular cli (see [#6666](https://github.com/angular/angular-cli/issues/6666) and [#9347](https://github.com/angular/angular-cli/issues/9347)).
Url's will respect the `base-href` that you can set via the workspace/angular json so you might be able to use that to your benefit.

**Comment by rarmatei** [comment]
as there hasn't been a lot of activity around this, and a lot of updates to Nx and the Angular CLI went in since, could you please try again with the latest version of Nx and create a new issue with some repro steps if this is a problem? Thanks!
