### ISSUE TITLE
nx format:write ignores --files argument

### ISSUE THREAD

**Issue by Markus-Ende** [nrwl/nx#20272]
### Current Behavior

`nx format:write --files=/path/to/nx-examples/README.md` formats other files

### Expected Behavior

Should only format the given fil(s)

### GitHub Repo

https://github.com/nrwl/nx-examples

### Steps to Reproduce

Tested in nx example repo:
1. Change something in a repo file (e.g. add a tab to a property in jest.preset.js)
2. Save without formatting
3. Run `nx format:write --files=/path/to/nx-examples/README.md` (or with some other file(s)

### Nx Report

```shell
Node   : 18.16.0
   OS     : linux-x64
   yarn   : 1.22.19

   nx                 : 17.1.0-rc.0
   @nx/js             : 17.1.0-rc.0
   @nx/jest           : 17.1.0-rc.0
   @nx/linter         : 17.1.0-rc.0
   @nx/eslint         : 17.1.0-rc.0
   @nx/workspace      : 17.1.0-rc.0
   @nx/angular        : 17.1.0-rc.0
   @nx/cypress        : 17.1.0-rc.0
   @nx/devkit         : 17.1.0-rc.0
   @nx/eslint-plugin  : 17.1.0-rc.0
   @nx/react          : 17.1.0-rc.0
   @nrwl/tao          : 17.1.0-rc.0
   @nx/web            : 17.1.0-rc.0
   @nx/webpack        : 17.1.0-rc.0
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 16.0.0
   @ngrx/effects         : 16.0.0
   @ngrx/entity          : 16.0.0
   @ngrx/router-store    : 16.0.0
   @ngrx/store           : 16.0.0
   @ngrx/store-devtools  : 16.0.0
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

WSL2

**Comment by dmitry-stepanenko** [comment]
Here's the PR that causes this regression https://github.com/nrwl/nx/pull/18670

The problem only occurs with absolute paths, when absolute path is provided here https://github.com/nrwl/nx/blob/b51bd04746e71f622990e532d7c966418c7ecc7a/packages/nx/src/command-line/format/format.ts#L101 `ignore` package throws an error `RangeError: path should be a `path.relative()`d string, but got ...` and in the catch block we are returning a mask for all files `['.']` https://github.com/nrwl/nx/blob/b51bd04746e71f622990e532d7c966418c7ecc7a/packages/nx/src/command-line/format/format.ts#L111

**Comment by AgentEnder** [comment]
@dmitry-stepanenko nice detective work - do you want to open a PR?

**Comment by dmitry-stepanenko** [comment]
@AgentEnder will do!
