### ISSUE TITLE
Remove requiring --directory when using the CLI

### ISSUE THREAD

**Issue by pm20390** [nrwl/nx#20288]
- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
When using CLI commands such as `nx g @nrwl/angular:component` it is frustrating for developers to have to provide the path of the directory the component should be created in. The previous behavior in older Nx versions that would create it in whatever directory you are working in was much more straightforward. A configuration to set the behavior or to automatically set the directory as the current path would be ideal.

## Motivation
Having to type the directory of a path you're already CD'd into is frustrating.

## Suggested Implementation
A configuration in nx.json like "setDirAsCurrentPath" could work.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

The Nx generators are meant to respect the current working directory with the [new way of generating projects and artifacts](https://nx.dev/deprecated/as-provided-vs-derived) (`as-provided` format).

We need more information to know what could be wrong in your workspace. Could you please run `nx report` in your workspace and share the outputs with us?
