### ISSUE TITLE
Cannot run Angular library migration in Nx workspace

### ISSUE THREAD

**Issue by bradley-carestia-jbh** [nrwl/nx#20282]
### Current Behavior

We have an internal Angular library with migration scripts for use with `ng update`. The scripts work fine in a standard Angular workspace.

When run though `nx migrate` however, the arguments to the script are always undefined. Just like in this StackOverflow post https://stackoverflow.com/questions/76860116/tree-is-undefined-angular-update-schematics-in-a-nx-workspace. Running with FORCE_NG_UPDATE=true results in "Error: This command is not available when running the Angular CLI outside a workspace."

To be clear; the `migrations.json` file is generated and appears to run without errors, it just doesn't actually do anything do to the undefined argument.

As not everyone using this library is using Nx, we can't make an Nx generator instead; and it seems awkward to maintain both an Angular and Nx version of the migration script. The consuming project is currently on Nx 16.3.1.

### Expected Behavior

The library's migration script to run correctly in Nx workspaces.

### Steps to Reproduce

1. Create Angular library migration with standard structure, ie:
```
export function version4(_options: any): Rule {
  return (host: Tree, context: SchematicContext) => {
    const version = `4.0.0`;
    context.logger.info(`Applying migration for lib to version ${version}`);
    ...
    return host;
  };
```
2. Run in Nx workspace with `nx migrate`. Notice not even the log statement works (though a standard console.log does, its definitely calling the function)

### Nx Report

```shell
Node   : 16.20.1
   OS     : darwin arm64
   yarn   : 1.22.19
   Hasher : Node
   
   nx                 : 16.3.1
   @nx/js             : 16.3.2
   @nrwl/js           : 16.3.1
   @nx/jest           : 16.3.1
   @nrwl/jest         : 16.3.2
   @nx/linter         : 16.3.1
   @nrwl/linter       : 16.3.2
   @nx/workspace      : 16.3.1
   @nx/angular        : 16.3.1
   @nx/cypress        : 16.3.1
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.1
   @nx/plugin         : 16.3.2
   @nrwl/tao          : 13.1.3
   @nx/web            : 16.3.1
   @nx/webpack        : 16.3.1
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @custom/rollout              : 4.0.0
   @ngrx/component              : 16.0.1
   @ngrx/component-store        : 16.0.1
   @ngrx/eslint-plugin          : 16.0.1
   ---------------------------------------
   Local workspace plugins:
         @custom/opex-nx
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/js@16.3.2
     - @nrwl/jest@16.3.2
     - @nrwl/linter@16.3.2
     - @nx/devkit@16.3.2
     - @nrwl/devkit@16.3.2
     - @nx/plugin@16.3.2
     - @nrwl/nx-plugin@16.3.2
     - @nrwl/tao@13.1.3
   
   To fix this, run `nx migrate nx@16.3.2`
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Hey @bradley-carestia-jbh !

I know it's been a while and this is still sitting.

Would you be able to check if this is still happening in the latest version of Nx?

**Comment by bradley-carestia-jbh** [comment]
Good timing; we're about to do another upgrade cycle @Coly010 . I should be able to test it again in the near future.

**Comment by bradley-carestia-jbh** [comment]
@Coly010 

Just ran my latest migration in version 19, and the issue is still present. My migration starts with:
```
export function version8(_options: any): Rule {
  return (host: Tree, context: SchematicContext) => {
    const version = `8.0.0`;
    context.logger.info(`Applying migration for library to version ${version}`);
```

While the output is just:
```
Running the following migrations:
- library: migration-v8.0.0 (Updates from v7 to v8)
---------------------------------------------------------

Running migration library: migration-v8.0.0
Ran migration-v8.0.0 from library
  Updates from v7 to v8

No changes were made
```

Notice the logging statement is not present.

**Comment by Coly010** [comment]
@bradley-carestia-jbh I'm going to need a reproduction repo, minimal if possible, because I can't reproduce this behaviour.

You can see my repo here: https://github.com/Coly010/nx-ng-migration-repro.git

The root migrations.json points to the angular schematic migration and i can see it logging correctly:
<img width="727" alt="image" src="https://github.com/user-attachments/assets/d5991e02-1608-47ff-b2df-a507f8b36482">


If you clone my repro, make sure to
1. install
2. build

You may need to change the package.json to remove the `devDependencies.'@ng-mig/acme'` for the first install so that you can subsequently build the package.

**Comment by GuillaumeNury** [comment]
Hi @Coly010, I have the same problem.
Nx call the migration script differently if it is a Nx script or an `@angular/cli` script. The logic works most of the time, but not always.

The `@angular/cli`migration will be run correctly only if it contains some of the strings [checked here](https://github.com/nrwl/nx/blob/d9fed4b832bf01d1b9a44ae9e486a5e5cd2d2253/packages/nx/src/command-line/migrate/migrate.ts#L1729-L1738).

In your reproduction repo, your schematic is called (ie `version4` function is called), but not the `(host, context) => {}` function.

This is because the compiled file of the schematic does not include `require('@angular-devkit/schematics')`.

**Comment by Coly010** [comment]
The`(host, context)` must be called in my reproduction, as the log is being output. That log is within the `(host, context)` block: https://github.com/Coly010/nx-ng-migration-repro/blob/main/acme/src/migrations/testing.ts#L7

**Comment by GuillaumeNury** [comment]
I cannot see the log:

![image](https://github.com/user-attachments/assets/d9994a6c-7d29-4c56-9b54-7b67a7afbdae)

(I just added a "version4 called" log above `(host, context)`)

**Comment by GuillaumeNury** [comment]
@Coly010 if this can help, I just

- cloned your repro repo
- `npm i`
- `nx build acme`
- `nx migrate --run-migrations`

Here is the `nx report`:

```
Node           : 20.11.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.2.4

nx                 : 19.6.1
@nx/js             : 19.6.1
@nx/jest           : 19.6.1
@nx/linter         : 19.6.1
@nx/eslint         : 19.6.1
@nx/workspace      : 19.6.1
@nx/angular        : 19.6.1
@nx/devkit         : 19.6.1
@nx/eslint-plugin  : 19.6.1
@nx/plugin         : 19.6.1
@nrwl/tao          : 19.6.1
@nx/web            : 19.6.1
@nx/webpack        : 19.6.1
typescript         : 5.5.4
---------------------------------------
Community plugins:
@ng-mig/acme : 0.0.2
```

**Comment by GuillaumeNury** [comment]
@Coly010 here is a repro, with a second schematic: https://github.com/Coly010/nx-ng-migration-repro/compare/main...GuillaumeNury:nx-ng-migration-repro:repro

![image](https://github.com/user-attachments/assets/a7ddf0b5-c145-4b23-9a77-c26b1f5f4a14)

**Comment by Coly010** [comment]
Interesting, with your change in place, i'm reproducing the issue

**Comment by Coly010** [comment]
Ok, I was able to fix it easily enough from a workaround:

ensure `"cli": "ng"` is set in your package's `migrations.json` file:
```
{
  "schematics": {
    "testing": {
      "cli": "ng",
      "version": "0.0.2",
      "description": "Migration for v0.0.2",
      "factory": "./src/migrations/testing"
    }
}
```

@GuillaumeNury I've pushed an update to the PR (https://github.com/Coly010/nx-ng-migration-repro/pull/2/files) that I created from your change comparison, and here is the result from run-migrations
<img width="601" alt="image" src="https://github.com/user-attachments/assets/fbddf49d-5b72-41f2-96b2-e00dbea8901e">

**Comment by Coly010** [comment]
@bradley-carestia-jbh Can you confirm if setting `cli: ng` resolves your issue?

**Comment by bradley-carestia-jbh** [comment]
I'll give it a try!

**Comment by GuillaumeNury** [comment]
@Coly010 it does not work on my machine 🤔
What version of Nx are you using?

If you look at `isAngularMigration` in [migrate.ts](https://github.com/nrwl/nx/blob/master/packages/nx/src/command-line/migrate/migrate.ts#L1706-L1766) file, it does not use `cli === "ng"`.

Since #16259, `cli` is not really used anymore. You can see in the test files of this PR that `var angular_devkit_core1 = require("@angular-devkit/core");` was added. But when you compile an Angular CLI schematics, this line is not always there.

**Comment by Coly010** [comment]
@GuillaumeNury in fact, in that file, CLI _is_ the default check: https://github.com/nrwl/nx/blob/2c0a50c0d8f45f65c9a91e1426fc2e66a29af3bb/packages/nx/src/command-line/migrate/migrate.ts#L1765


`return entry.cli ? entry.cli !== 'nx' : useAngularDevkitToRunMigration;`

If the CLI property exists on the package’s migrations.json file, then return true if it does not equal ‘nx’.

If the CLI property does not exist on the package’s migrations.json, use the other methods to try find if it’s an angular migration.

**Comment by Coly010** [comment]
> This property is not an "official" one : the cli property is not in the [collection-schema.json](https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/schematics/collection-schema.json)

Yep, which is why we had planned to remove it, but given the fallback logic was flawed, I think it makes sense to keep it for another while to let people have the change to migrate
