### ISSUE TITLE
NX cli commands not working

### ISSUE THREAD

**Issue by itronmya** [nrwl/nx#20280]
### Current Behavior

npx create-nx-workspace@16.5.1, It created the workspace.

But when i try serving application, it fails
nx serve shell          

 >  NX   Missing Platform Dependency

   The Nx CLI could not find or load the native binary for your supported platform (win32-x64).
   This likely means that optional dependencies were not installed correctly, or your system is missing some system dependencies.
   For more information please see https://nx.dev/recipes/ci/troubleshoot-nx-install-issues

Tried optional dependency as well but no clue of why it is failing to serve.

### Expected Behavior

Nx should serve application.

### Steps to Reproduce

1. Create nx workspace
2. nx serve <app-name>

### Nx Report

```shell
Report complete - copy this into the issue template

   Node   : 16.16.0
   OS     : win32-x64
   npm    : 8.11.0

   nx (global)        : 16.5.3
   nx                 : 16.5.3
   @nx/js             : 16.5.3
   @nx/jest           : 16.5.3
   @nx/linter         : 16.5.3
   @nx/workspace      : 16.5.3
   @nx/angular        : 16.5.3
   @nx/cypress        : 16.5.3
   @nx/devkit         : 16.5.3
   @nx/eslint-plugin  : 16.5.3
   @nrwl/tao          : 16.5.3
   @nx/web            : 16.5.3
   @nx/webpack        : 16.5.3
   typescript         : 5.1.6
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Did you follow the steps from the guide linked in the error messaging? In particular regarding running `npm i` after removing the both the node modules and lock file is important if you hit this issue.

https://nx.dev/recipes/ci/troubleshoot-nx-install-issues

**Comment by itronmya** [comment]
Quick question here,
When i run application with scripts in package.json. 'npm  run start', it works
but when i deliberately run 'nx run shell' not working.
Any idea?
![image](https://github.com/nrwl/nx/assets/144651641/e0b42ba9-1ea7-4a9b-8a55-6c15baa44a82)

**Comment by itronmya** [comment]
After updating global version it helps
