### ISSUE TITLE
Cannot create a integrated workspace for Nest Js project

### ISSUE THREAD

**Issue by saboorajat** [nrwl/nx#20302]
### Current Behavior

While creating a workspace with `npx create-nx-workspace gen2-monorepo` but it fails to create a full workspace and throws the below error.

![image](https://github.com/nrwl/nx/assets/105360370/b65e637f-4ade-4d66-8ba3-2d27d65aab9b)

### Expected Behavior

Would be creating a nx workspace with nest js project named api inside app directory.

### Steps to Reproduce

1. npx create-nx-workspace gen2-monorepo

### Nx Report

```shell
Node   : 20.5.1
   OS     : win32-x64
   npm    : 9.8.0
   
   nx (global)    : 17.1.2
   nx             : 17.1.2
   @nx/js         : 17.1.2
   @nx/workspace  : 17.1.2
   @nx/devkit     : 17.1.2
   @nrwl/tao      : 17.1.2
```

### Failure Logs

```shell
added 508 packages, and audited 509 packages in 27s

48 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

>  NX  Generating @nx/workspace:preset

Fetching @nx/nest...
Fetching prettier...

 >  NX   generateFiles: No files found in "/Users/RAJATS~1/AppData/Local/Temp/tmp-3560-FpXHFl4yQeJF/node_modules/@nx/nest/src/generators/application/files". Are you sure you specified the correct path?

   Pass --verbose to see the stacktrace.


 >  NX   Workspace creation failed, see above.

   Pass --verbose to see the stacktrace.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

tsconfig.base.json files are missing when we don't opt for framework.
![image](https://github.com/nrwl/nx/assets/105360370/d71ade28-b559-417d-8d1a-633fc5dc84f8)

**Comment by alifhs** [comment]
I'm also facing the same issue.

**Comment by alifhs** [comment]
Error log:
>  NX   generateFiles: No files found in "/Users/alifh/AppData/Local/Temp/tmp-24804-m4QgknRab0wD/node_modules/.pnpm/@nx+nest@17.1.2_@types+node@20.9.2_nx@17.1.2_typescript@5.2.2/node_modules/@nx/nest/src/generators/application/files". Are you sure you specified the correct path?

**Comment by LeoKun1231** [comment]
report

**Comment by Azuky** [comment]
Possibly related to #18677

**Comment by jkazimierczak** [comment]
I faced the same issue when using `pnpm` (`pnpx`). I looked at #18677 as suggested above, but unfortunately installing both on `C:` and other-letter partitions resulted in the same error. 

Switching to `npx` for setting up the workspace resolved the issue. Then you can remove npm `node_modules` and install dependencies with `pnpm i`.

**Comment by FrozenPandaz** [comment]
Is this still an issue on the latest version of Nx?
