### ISSUE TITLE
@nx/enforce-module-boundaries wants relative import to main lib in secondary entrypoint, but build fails

### ISSUE THREAD

**Issue by flensrocker** [nrwl/nx#20310]
### Current Behavior

I have an Angular library with some code in the main entrypoint (e.g. a service).
I want to import this service into a component, which is located in a secondary entrypoint.

When I do this, the linter errors because of the rule `@nx/enforce-module-boundaries` with the message (the build is fine):

```
.../my-lib/ui/src/lib/ui.component.ts
  2:1  error  Projects should use relative imports to import from other files within the same project. Use "./path/to/file" instead of import from "@secondary-entry-module-boundaries/my-lib"  @nx/enforce-module-boundaries
```

When I fix this the build errors:

```
Building Angular Package

------------------------------------------------------------------------------
Building entry point '@secondary-entry-module-boundaries/my-lib'
------------------------------------------------------------------------------
Copying assets
Writing package manifest
Built @secondary-entry-module-boundaries/my-lib

------------------------------------------------------------------------------
Building entry point '@secondary-entry-module-boundaries/my-lib/ui'
------------------------------------------------------------------------------

 >  NX   my-lib/src/lib/my-lib.service.ts:1:1 - error TS6059: File .../my-lib/src/lib/my-lib.service.ngtypecheck.ts' is not under 'rootDir' '...\my-lib\ui\src'. 'rootDir' is expected to contain all source files.


   1 import { Injectable } from '@angular/core';

   my-lib/ui/src/lib/ui.component.ts:2:30 - error TS6059: File '.../my-lib/src/lib/my-lib.service.ts' is not under 'rootDir' '...\my-lib\ui\src'. 'rootDir' is expected to contain all source files.

   2 import { MyLibService } from '../../../src/lib/my-lib.service';
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   Pass --verbose to see the stacktrace.
```

### Expected Behavior

I would expect the linter to not show an error.

### GitHub Repo

https://github.com/flensrocker/nx-issue-secondary-entry-module-boundaries

### Steps to Reproduce

```
npx nx build my-lib
npx nx lint my-lib
npx nx lint my-lib --fix
npx nx build my-lib
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.18.0
   OS     : win32-x64
   npm    : 10.2.1

   nx                 : 17.1.2
   @nx/js             : 17.1.2
   @nx/jest           : 17.1.2
   @nx/linter         : 17.1.2
   @nx/eslint         : 17.1.2
   @nx/workspace      : 17.1.2
   @nx/angular        : 17.1.2
   @nx/cypress        : 17.1.2
   @nx/devkit         : 17.1.2
   @nx/eslint-plugin  : 17.1.2
   @nrwl/tao          : 17.1.2
   @nx/web            : 17.1.2
   @nx/webpack        : 17.1.2
   typescript         : 5.2.2
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

What is the "correct" way to make this work?
If I have a library with secondary entrypoints, should they not be able to import from the main library?
Or should I only have secondary entrypoints and nothing inside the main library? Non-relative imports between secondary entrypoints does work and throws no error on linting/building.

**Comment by flensrocker** [comment]
I don't really want to disable the linting rule. When I start to let my team do this, it will get worse, because everyone has to understand, when you are allowed to disable a rule and when not. So noone is allowed to disable linting rules. Eceptions are handled by configuration, such as "let unused variables start with an underscore".

I can accept, that the main library cannot import something from a secondary entrypoint, because they are built after the main lib. And it is understandable, that the "first" entrypoint can not depend on the "second" entrypoint.

**Comment by JelleBruisten** [comment]
I agree it should be fixed, but not being able to build might be a bigger problem for your team. I would disable for now, later when fixed remove the disabling of it.

**Comment by flensrocker** [comment]
At the moment I live with the linter error and keep it buildable. 😎

**Comment by meeroslav** [comment]
Thank you for reporting this @flensrocker, we will look into it as soon as possible.
