### ISSUE TITLE
Create a github action to manage .nx cache like Nx Cloud does

### ISSUE THREAD

**Issue by AllanOricil** [nrwl/nx#20327]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Need a solution for this [issue](https://nx.dev/recipes/troubleshooting/unknown-local-cache) when building in Github Actions

## Motivation

I don't want to use Nx Cloud for speed up my builds

## Suggested Implementation

Create a Github Action that can safely cache and restore .nx cache while avoiding all [issues](https://nx.dev/recipes/troubleshooting/unknown-local-cache) described here

Each task would create its own cache and then updated when a non cache hit happened. Github actions does not allow updating the cache with the same key, so you would need to use a workaround like this [one](https://github.com/azu/github-actions-overwrite-cache-example).

You could also enable devs to pass a list of trusted machines ids when using self hosted runners. This way we could easily share cache between runners we control, and avoid the following error:

<img width="979" alt="image" src="https://github.com/nrwl/nx/assets/55927613/6afd8372-ba29-484c-bdb1-d01d2bd5af1d">

Or it would be good if there was an env variable to bypass this protection.

**Comment by StalkAltan** [comment]
Hi, there are no plans to do this at this time. You can set `NX_REJECT_UNKNOWN_LOCAL_CACHE=0` to ignore this error.

**Comment by WolfspiritM** [comment]
Same issue here. We used to cache with github actions but builds start failing now. We're going to use NX_REJECT_UNKNOWN_LOCAL_CACHE now but docs discourage using that.
