### ISSUE TITLE
Cached Nx project fails builds?

### ISSUE THREAD

**Issue by zackarydev** [nrwl/nx#20323]
### Current Behavior

running: `yarn nx run myApp:myTarget`

```
nx run myApp:myTarget
       Could not find 'nx' module in this workspace. Error: [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.
       
       If you are leveraging \`readCachedProjectGraph()\` directly then you will need to refactor your usage to first ensure that
       the ProjectGraph is created by calling \`await createProjectGraphAsync()\` somewhere before attempting to read the data.
       
       If you encounter this error as part of running standard \`nx\` commands then please open an issue on https://github.com/nrwl/nx
           at readCachedProjectGraph (node_modules/nx/src/project-graph/project-graph.js:30:15)
           at run (node_modules/nx/src/command-line/run/run.js:179:69)
           at /node_modules/nx/bin/run-executor.js:60:48
           at Generator.next (<anonymous>)
           at /node_modules/nx/node_modules/tslib/tslib.js:167:75
           at new Promise (<anonymous>)
```

### Expected Behavior

Command to run my target for my app

### Steps to Reproduce

1.  Not sure.

### Nx Report

```shell
Node   : 19.9.0
   OS     : darwin-x64
   yarn   : 1.22.19
   
   nx                 : 16.5.2
   @nx/js             : 16.5.2
   @nx/jest           : 16.5.2
   @nx/linter         : 16.5.2
   @nx/workspace      : 16.5.2
   @nx/cypress        : 16.5.2
   @nx/devkit         : 16.5.2
   @nx/eslint-plugin  : 16.5.2
   @nx/node           : 16.5.2
   @nx/react          : 16.5.2
   @nx/storybook      : 16.5.2
   @nrwl/tao          : 16.5.2
   @nx/web            : 16.5.2
   @nx/webpack        : 16.5.2
   typescript         : 5.1.3
```

### Package Manager Version

   yarn   : 1.22.19

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Tried to upgrade to 17 yesterday on a different branch. Removed node modules, dist, tmp. 

Getting this error today, rest of the team and CI no issues.

**Comment by zackarydev** [comment]
I tried adding `cacheDirectory` but that doesn't solve the issue.

**Comment by zackarydev** [comment]
Might be fixed with `yarn nx reset`

**Comment by AgentEnder** [comment]
Its possible you hit some errors due to the default cache directory changing in version 17, and swapping back to branches that aren't updated yet. Once you are fully on v17 you shouldn't experience these issues.

If `nx reset` doesn't fix this, feel free to write back or open a new issue and we can take a closer look.
