### ISSUE TITLE
pathRewrite does not work for @nx/vite:dev-server

### ISSUE THREAD

**Issue by simonbergstrom** [nrwl/nx#20339]
### Current Behavior

It seems like the pathRewrite property in the proxyConfig is not respected when adding a proxyConfig in my new vite config which previously worked when using webpack. 

Example proxy config: 
```
{
  "/api-with-rewrite": {
    "target": "http://localhost:5003",
    "pathRewrite": { "^/api-with-rewrite": "" },
    "secure": false,
    "changeOrigin": true
  },
  "/test-api": {
    "target": "http://localhost:7005",
    "secure": false,
    "changeOrigin": true
  }
}
```

### Expected Behavior

I want my request to my dev-server to remove /api-with-rewrite from path before reaching http://localhost:5003

### Steps to Reproduce

1. Create vite project
2. Add proxyConfig
3. Try requesting the app and the see if it lands on the proxied api.

### Nx Report

```shell
--
```

### Operating System

- [X] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by BrowserA11y** [comment]
According to [docs](https://vitejs.dev/config/server-options#server-proxy) it is 'rewrite', not 'pathRewrite'. The change worked for me.
