### ISSUE TITLE
@nx/devkit `writeJsonFile` always appends a new line

### ISSUE THREAD

**Issue by alfaproject** [nrwl/nx#20335]
### Current Behavior

`writeJsonFile` from @nx/devkit always appends a new line because it calls the `serializeJson` function which always appends a new line, so the `appendNewLine` effectively doesn't work as intended (it either adds 1 new line or 2 if true)

### Expected Behavior

`writeJsonFile` respects the `appendNewLine` option

**Comment by MaxKless** [comment]
Thanks for the report!
Just tested this out and it looks like it was fixed with https://github.com/nrwl/nx/pull/23440
