### ISSUE TITLE
nx dep-graph, listen EACCES: permission denied error

### ISSUE THREAD

**Issue by jakobgn** [nrwl/nx#2033]
- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

After creating a clean workspace I should be able to run nx dep-graph without errors

## Current Behavior

After creating a clean workspace (windows10 OS) I get an error

## Failure Information (for bugs)

nx dep-graph

>  NX   NOTE  Dep graph started at http://localhost:4211

events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 127.0.0.1:4211
    at Server.setupListenHandle [as _listen2] (net.js:1211:19)
    at listenInCluster (net.js:1276:12)
    at doListen (net.js:1415:7)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
Emitted 'error' event at:
    at emitErrorNT (net.js:1255:8)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 4211
}

## Solution
Increase port number to 5 digit in dep-graph.js ( https://github.com/nodejs/help/issues/1159#issuecomment-373272198)

    app.listen(42111, '127.0.0.1');
    output_1.output.note({
        title: 'Dep graph started at http://localhost:42111'
    });
    opn('http://localhost:42111', {
        wait: false
    });

**Comment by rarmatei** [comment]
hi 👋 there hasn't been any activity on this for a while, and a lot of improvements have been made to Nx in the meantime - so I'll close it for now. Can you please update to the latest version of Nx and create a new issue if you're still experiencing this? Thanks!!
