### ISSUE TITLE
Bug in Nx Cloud app "compare tasks" page

### ISSUE THREAD

**Issue by richard-ling** [nrwl/nx#20348]
### Current Behavior

On the Nx Cloud Compare Tasks page, tasks are listed as "cache miss", even when they are displayed as "remote cache hit" on the Task Details and Run Details pages.

Run Details page:
![image](https://github.com/nrwl/nx/assets/50315238/a1ed0e90-2319-4608-b5b2-f2dc25eb1592)
Task Details page:
![image](https://github.com/nrwl/nx/assets/50315238/2d818cea-5873-40e6-a7c0-fee712fed7a2)
Compare Tasks page:
![image](https://github.com/nrwl/nx/assets/50315238/67eb80fe-c5a8-4ae4-95e5-1ba5468c1d66)

If we load a URL into the right hand side, the loaded task will also be shown as a "cache miss", even when it is not.

### Expected Behavior

Cache status should be consistent

### GitHub Repo

Nx Cloud app

### Steps to Reproduce

1.  Load a task URL into the Nx Cloud app page.
2. Choose a task which is a remote cache hit
3. Open the compare tasks page

### Nx Report

```shell
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : darwin x64
   yarn : 1.22.19
   
   nx : 15.2.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.2.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.0
   @nrwl/js : 15.2.0
   @nrwl/linter : 15.2.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.2.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.2.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.2.0
   @nrwl/web : 14.6.5
   @nrwl/webpack : 15.2.0
   @nrwl/workspace : 15.2.0
   typescript : 4.3.5
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by nixallover** [comment]
@richard-ling thank you for reporting this issue, this has been fixed and will be released in the next week. Sorry I wasn't able to get back to you sooner, I appreciate your patience!

**Comment by richard-ling** [comment]
Thanks @nixallover !
