### ISSUE TITLE
Migrating to latest: Unable to determine 'tsconfig.json' file in workspace config.

### ISSUE THREAD

**Issue by Hypenate** [nrwl/nx#20357]
### Current Behavior

When running `pnpm exec nx migrate --run-migrations` the migration fails:
 >  NX   Failed to run migration-v17 from @angular/cdk. This workspace is NOT up to date!
 >  NX   Tsconfig cannot not be read: /NA

While we see a lot of orange lines:
> Skipping migration for project smc-host-cypress. Unable to determine 'tsconfig.json' file in workspace config.

### Expected Behavior

The migration should pass, because the file is present:
![image](https://github.com/nrwl/nx/assets/7478681/86df5f0e-2353-47ed-84c4-91ed43457bb6)

### Steps to Reproduce

1. Migrate to the latest version? :) 

### Nx Report

```shell
Skipping migration for project xxx. Unable to determine 'tsconfig.json' file in workspace config.
```

### Package Manager Version

pnpm 8.10.2

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AdditionAddict** [comment]
duplicate https://github.com/nrwl/nx/issues/20172
