### ISSUE TITLE
Cannot ignore root directories

### ISSUE THREAD

**Issue by itsRems** [nrwl/nx#20358]
### Current Behavior

Considering the following structure:

```sh
├─ v1/
│ ├─ packages
│ │├─ pkg-a 
│ │└─ pkg-b
└ packages/
   └─ pkg-c
```

I would like to set my `.nxignore` to:
```
./packages
```
in order to ignore the root `packages` directory, but NOT the packages in the `v1/packages` directory.

However, nx fails to respect my ignore when using the `./` prefix, and therefore includes all packages when running commands.

### Expected Behavior

This works fine in nx `16.1.4`, where only the root `./packages` directory is ignored, but hasn't worked any time we've tried to update nx since. 17.1.3 still has the issue

### Steps to Reproduce

try to ignore any root directory

### Nx Report

```shell
Node   : 18.17.1
   OS     : darwin-arm64
   yarn   : 4.0.1
   
   nx          : 17.1.3
   @nrwl/tao   : 17.1.3
   typescript  : 5.2.2
```

### Package Manager Version

yarn 4.0.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Cammisuli** [comment]
can you try using `packages/`?

**Comment by itsRems** [comment]
@Cammisuli `/packages` ignores `v1/packages`

**Comment by Cammisuli** [comment]
oh no, thats not right then. Let me take a closer look

**Comment by Cammisuli** [comment]
After #20500 is released, you can use `/packages` in the root `.nxignore` properly. Sorry about that!

**Comment by itsRems** [comment]
@Cammisuli thanks ! 🙌
