### ISSUE TITLE
Storybook Missing Docs Addon

### ISSUE THREAD

**Issue by elson-currentcorp** [nrwl/nx#20361]
### Current Behavior

Storybook configuration generated via NX is missing the docs addon. 

It has the essentials addon, which should come with 8 addons but the docs one is missing:

![image](https://github.com/nrwl/nx/assets/148154522/b5a320d4-05c4-434f-bb4d-23527f260982)

### Expected Behavior

The docs addon should be available because it is apart of the essentials addon, but it is the only one that is missing.

![image](https://github.com/nrwl/nx/assets/148154522/b1284a2c-777e-4daf-a106-28ed328eb877)

### GitHub Repo

https://github.com/elson-currentcorp/nx-storybook-bug

### Steps to Reproduce

```
$ npx create-nx-workspace@latest
org
React
None
Integrated Monorepo
org
Vite
Cypress
styled-components
yes

$ nx  g @nx/react:lib component-library
$ npm install -D @nx/storybook
$ nx g @nx/react:storybook-configuration component-library
$ nx run component-library:storybook
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.9.0
   OS     : win32-x64
   npm    : 10.1.0

   nx (global)        : 17.1.2
   nx                 : 17.1.3
   @nx/js             : 17.1.3
   @nx/linter         : 17.1.3
   @nx/eslint         : 17.1.3
   @nx/workspace      : 17.1.3
   @nx/cypress        : 17.1.3
   @nx/devkit         : 17.1.3
   @nx/eslint-plugin  : 17.1.3
   @nx/react          : 17.1.3
   @nx/storybook      : 17.1.3
   @nrwl/tao          : 17.1.3
   @nx/vite           : 17.1.3
   @nx/web            : 17.1.3
   typescript         : 5.2.2
```

### Package Manager Version

10.1.0

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Hi there @elson-currentcorp ! Thanks for filing an issue! We don't control the contents of `@storybook/addon-essentials`. As the Storybook documentation notes, https://storybook.js.org/docs/essentials, docs is part of essentials. If it does not show up in your project, then maybe it's an issue with the `@storybook/addon-essentials` addon. You can try opening an issue there and see what's going on? https://github.com/storybookjs/storybook/issues

What behaviour are you experiencing, which indicates that something is wrong?

**Comment by mandarini** [comment]
I'll be closing this issue since it's third party! Let me know if you have any more issues please!
