### ISSUE TITLE
NX 17 - To use Distributed Task Execution, your default task runner configuration must    use the "nx-cloud" task runner.

### ISSUE THREAD

**Issue by asgerjensen** [nrwl/nx#20369]
### Current Behavior

After doing `nx migrate 17.1.3 ` from 16.x  and running migrations, CI platform fails to run DTEs. 
After migration, nx.json no longer contains the `taskRunnerOptions` section, and docs seem to indicate its no longer necessary.

Locally we dont use nx-cloud, but for CI we do. With NX16 this worked fine, by just unsetting the access token in nx.json and at CI time provide it as environment variable `NX_CLOUD_ACCESS_TOKEN`

I'm using github actions, and nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.14.0. Agent initialization works (ie it runs whats listed as install commands), but individual agents fail to do anything complaining that nx-cloud is not my default task runner.

### Expected Behavior

Since documentation for nx cloud config (https://nx.dev/nx-cloud/reference/config)  shows that nx17 does not need taskRunnerOptions to be set, the error message should not indicate that i should set it.

Also, it should actually not fail to run.

### Steps to Reproduce

1. create CI script for github actions using DTE
2. run it

### Nx Report

```shell
NX   Report complete - copy this into the issue template

   Node   : 18.18.2
   OS     : linux-x64
   npm    : 9.8.1
   
   nx                 : 17.1.3
   @nx/js             : 17.1.3
   @nx/jest           : 17.1.3
   @nx/linter         : 17.1.3
   @nx/eslint         : 17.1.3
   @nx/workspace      : 17.1.3
   @nx/angular        : 17.1.3
   @nx/cypress        : 17.1.3
   @nx/devkit         : 17.1.3
   @nx/eslint-plugin  : 17.1.3
   @nx/plugin         : 17.1.3
   @nx/storybook      : 17.1.3
   @nrwl/tao          : 17.1.3
   @nx/web            : 17.1.3
   @nx/webpack        : 17.1.3
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @currents/nx       : 0.2.1
   @ngneat/spectator  : 10.0.1
   @storybook/angular : 7.5.3
   ng-mocks           : 14.12.1
   ---------------------------------------
```

### Failure Logs

```shell
Run npx nx-cloud start-agent
  npx nx-cloud start-agent
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    NX_CLOUD_DISTRIBUTED_EXECUTION: true
    NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 3
    NX_BRANCH: [2](https://github.com/ORG/REPO/actions/runs/6958272621/job/18932964877#step:17:2)5[4](https://github.com/ORG/REPO/actions/runs/6958272621/job/18932964877#step:17:4)
    NX_CLOUD_ACCESS_TOKEN: ***
    NX_CLOUD_AUTH_TOKEN: 
    NPM_TOKEN: 
    VOLTA_HOME: /opt/hostedtoolcache/volta/1.1.1/x[6](https://github.com/ORG/REPO/actions/runs/6958272621/job/18932964877#step:17:6)4
    NX_AGENT_NAME: 2

 >  NX   Starting an agent for running Nx tasks


 >  NX   Invalid Task Runner Configuration

   To use Distributed Task Execution, your default task runner configuration must
   use the "nx-cloud" task runner.
   
   This can be adjusted in "nx.json".
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by asgerjensen** [comment]
Uhm..... sorry for newbie question, but did i miss a comment or failed to do something ?

**Comment by AgentEnder** [comment]
Sorry, we fixed thus with a pr on the nx Cloud repo and it closed the issue.
