### ISSUE TITLE
Output on Windows shows strange characters and is hard to read

### ISSUE THREAD

**Issue by nbolton** [nrwl/nx#20365]
### Current Behavior

`nx hello`:
```
> nx run foobar:hello
> foobar@1.2.3 hello
> echo
←[0K
 ←[2m←[32m————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————←[39m←[22m←[0K
←[0K
 ←[32m>←[39m ←[0m←[7m←[1m←[32m NX ←[39m←[22m←[27m←[0m  ←[32mSuccessfully ran target clean for project synergy←[39m←[2m (8s)←[22m←[0K
 ←[0K
←[0J←[?25h←[?25h
```

### Expected Behavior

`nx hello`:
```
> nx run foobar:hello
> foobar@1.2.3 hello
> echo
0K
```

### Workaround

Don't use root-level script, and type the `nx` command directly.

### Steps to Reproduce

1. Add a script to `package.json` which simply runs `echo`
2. Run using Nx root-level scripts
3. Run the script, e.g. `nx hello`

### Nx Report

```shell
> nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.17.0
   OS     : win32-x64
   npm    : 9.6.7
   
   nx (global)        : 17.1.2
   nx                 : 17.0.2
   @nx/js             : 17.1.2
   @nx/jest           : 17.1.2
   @nx/linter         : 17.0.2
   @nx/eslint         : 17.0.2
   @nx/workspace      : 17.0.2
   @nx/devkit         : 17.1.2
   @nx/esbuild        : 17.0.2
   @nx/eslint-plugin  : 17.0.2
   @nx/node           : 17.0.2
   @nx/playwright     : 17.0.2
   @nx/plugin         : 17.1.2
   @nx/react          : 17.0.2
   @nrwl/tao          : 17.0.2
   @nx/vite           : 17.0.2
   @nx/web            : 17.0.2
   typescript         : 5.1.6
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/js@17.1.2
     - @nrwl/js@17.1.2
     - @nx/jest@17.1.2
     - @nrwl/jest@17.1.2
     - @nx/devkit@17.1.2
     - @nrwl/devkit@17.1.2
     - @nx/plugin@17.1.2
     - @nrwl/nx-plugin@17.1.2

   To fix this, run `nx migrate nx@17.1.2`
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
What terminal is this in? It seems like the terminal is not recognizing ANSI color sequences.

**Comment by nbolton** [comment]
> What terminal is this in? It seems like the terminal is not recognizing ANSI color sequences.

It's in PowerShell 7 in VS Code. I also tested with regular Windows command prompt in VS Code. I haven't tested with stock PowerShell or outside of VS Code (which I plan to do). I also plan to test on a fresh VM install of Windows to see if I can repro it there too. 

Sometimes it actually intermittently understands the ANSI color sequences, but mostly it doesn't.

**Comment by david-morris** [comment]
I'm confused as to why this was ignored and closed.

It's generally useful to be able to turn off ansi sequences, such as when piping commands or posting output to github in a CI pipeline.

Maybe it makes sense to reopen this issue?
