### ISSUE TITLE
`format` can only use `prettier`

### ISSUE THREAD

**Issue by dannygreg** [nrwl/nx#20370]
### Current Behavior

The `format` target is currently the only one which is hard-coded to use a given tool. You are unable to override it in any way.

Although `prettier` is a great choice for JS/TS projects, we have several projects that are written in other languages. We have had to create a `format2` target and standardise on using that (for `nx affected` to work as expected), even for projects which are using `prettier`!

### Expected Behavior

The `format` target should not be special cased in any way, and a `project.json` should be able to define whatever executer it would like.

### Steps to Reproduce

1. Create an `nx` repo
2. Add a project using a language other than JS/TS (e.g. Python)
3. Create a `format` target using a tool of your choice (e.g. `black`)
4. Run `nx format`

### Nx Report

```shell
Node   : 16.15.1
   OS     : darwin-arm64
   npm    : 8.11.0

   nx (global)    : 17.0.2
   nx             : 17.0.2
   @nx/workspace  : 17.1.3
   @nx/devkit     : 16.10.0
   @nrwl/tao      : 17.0.2
   typescript     : 4.3.2
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/workspace@17.1.3
     - @nrwl/workspace@17.1.3
     - @nx/devkit@16.10.0
     - @nrwl/devkit@16.10.0

   To fix this, run `nx migrate nx@17.1.3`
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
`format` as a CLI command is a bit of legacy in that it is one of the first commands that Nx added. We are currently in the process of reconsidering what this should look like, while also providing the same functionality that we currently do out of the box.

My recommendation for multi-language workspaces today would be to add targets named `format` to projects that `nx format` isn't suitable for, and include `nx run-many -t format` in your CI scripts.

I'm going to close out this issue as its not a bug and we are actively considering the future of the format command. It can only use prettier, but also doesn't have much value over running prettier directly. At the end of the day, Nx isn't a formatter and we want to allow more user choice in this area and also remove some of the special cases within our codebase.

**Comment by dannygreg** [comment]
I think you're misunderstanding the bug report: it is impossible to create a format target. Nx will ignore it and use prettier instead.

**Comment by AgentEnder** [comment]
Yeah, `nx format` being a command will prevent `nx format` from ever running a target for the time being. Like I said, we are evaluating that. `nx run-many -t format`, `nx affected -t format`, or `nx run projectName:format` would be the way to invoke the targets

**Comment by dannygreg** [comment]
Oh I see, I glossed over what you were saying there. Mb!

I'd definitely be in the camp for removing any JS-specific features or implementations 😃
