### ISSUE TITLE
Any examples for nx release ?

### ISSUE THREAD

**Issue by kunyan** [nrwl/nx#20383]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

I can't find any examples in nx docs.

by default, there are no way to use `nx release`. it will throw a error

```
 NX   Release group "__default__" matches no projects. Please ensure all release groups match at least one project:

   The relevant config is defined here: nx.json
```

I added following codes into `nx.json`

```
"release": {
    "projectsRelationship": "independent"
  },
```

The nx release version is works. but it only apply to libs.

What if I want to release a project in `apps` directory ?
There are no package.json in apps

is that still possible to do ?

What I'm expected is we could release any type (apps or libs) projects
It could release the projects version by conversational commits or specific version name
The versions of projects are used for Github or Gitlab CI workflow. it could trigger a new webapps release pipeline

Enter the URL or documentation section here.

### Additional context or description

Provide any additional details here as needed.

**Comment by AgentEnder** [comment]
`nx release` documentation is in process and the command is still experimental while we work on ironing out what we want the final APIs to look like. Documentation will be part of the move out of experimental.
