### ISSUE TITLE
Add alias to apps/libes

### ISSUE THREAD

**Issue by eladhaim** [nrwl/nx#20380]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Adding the ability to run any nx command with the app/lib alias

## Motivation

Sometimes apps/libs has large names, by adding short alias all commands can be shorthand significantly.

**Comment by AgentEnder** [comment]
I'd recommend just renaming the project to have the shorter name that you'd like, Nx names don't have anything special behind them so if you want them to be shorter you should rename them.

**Comment by eladhaim** [comment]
The name represent service/lib name. aliases can help us create "shortcuts" for some operations, I can prepare a PR por this, is it something you can consider incorporate?
