### ISSUE TITLE
Yarn v1 and Project graph issue: Source project does not exist

### ISSUE THREAD

**Issue by Exelord** [nrwl/nx#20389]
### Current Behavior

If I have a package json like this:
```json
{
  "dependencies": {
    "my-package": "^1.0.0"
  },
  "resolutions": {
    "my-package": "Exelord/my-package"
  }
}
```

and I install using yarn v1, I am getting a lock file entry like this:

```
my-package@Exelord/my-package, my-package@^1.0.0
  version "1.0.0
  ...
```

This is causing issues when running any nx command:

```
Source project does not exits: npm:my-project@https://codeload.github.com/exelord/my-project/tar.gz/xxxxxxxx
```

I debugged the scenarios and this is happening only with yarn v1. However, if my dependency specifies "1.0.0" instead of "^1.0.0" then it works as the yarn.lock entry has following order:

```
my-package@1.0.0, my-package@Exelord/my-package
  version "1.0.0
  ...
```

I noticed that the issue is happening only if the entry has `my-package@^1.0.0` at the end. In other package managers this is not happening as they resolve it with `my-package@Exelord/my-package` only.

To clarify this issue was introduced after 16.4.0 as it is blocking us from upgrade.

### Expected Behavior

Support following yarn.lock entry:

```
my-package@Exelord/my-package, my-package@^1.0.0
  version "1.0.0
  ...
```

### Steps to Reproduce

1.

### Nx Report

```shell
Not possible to run the command.

Yarn 1.22.19
Node 20.9.0
NX 17.1.3
```

### Package Manager Version

Yarn 1.22.19

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by meeroslav** [comment]
Thank you for opening this issue.

We will look into this issue as soon as possible. In the meantime try to use package alias instead of package resolution:

```json
{
  "dependencies": {
    "my-package": "npm:@exelord/my-package@^1.0.0"
  }
}
```

**Comment by Exelord** [comment]
Thanks @meeroslav! We hope we can move forward with the upgrade soon.

This is just an example for reproduction. In reality there is just a resolution for a sub-dependency, no dependency strictly defined.
