### ISSUE TITLE
Error during lib creation - parent module

### ISSUE THREAD

**Issue by DefunctExodus** [nrwl/nx#204]
It appears that during a lib generation well having specified parentModule it fails

 ```
ng generate lib login --routing --lazy --parentModule=apps/myapp/src/app.module.ts
Error: Cannot read property 'toString' of null
Cannot read property 'toString' of null

```

this is fresh install of angular cli & nrwl

**Comment by cbuller** [comment]
I also have the same problem with: 
ng g lib common --module=apps/common/common.module.ts --routing

**Comment by vsavkin** [comment]
It's caused by an incorrect `parentModule` path. 

We should provide a better error message.

**Comment by sdurnov** [comment]
yep, people forget to add "app" folder before app.module.ts in path

**Comment by vsavkin** [comment]
The issue has been fixed in Nx 6.
