### ISSUE TITLE
undefined is created under apps when using create-nx-workspace with react-native preset

### ISSUE THREAD

**Issue by kanafghan** [nrwl/nx#20414]
### Current Behavior

Running `npx create-nx-workspace <workspace-name> --preset=react-native` creates an Nx workspace with the name of the app set to "undefined"

### Expected Behavior

Normally, the name of the app is set to "mobile" if none is provided. Otherwise, the user should be prompted for a name if none is provided.

### Steps to Reproduce

1. Run `npx create-nx-workspace nx-rn-app --preset=react-native`
2. Open the `nx-rn-app` workspace and notice the "undefined" app in the `apps` folder

### Nx Report

```shell
Node   : 16.20.2
   OS     : darwin-arm64
   npm    : 8.19.4
   
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/detox          : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/react          : 16.10.0
   @nx/react-native   : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/web            : 16.10.0
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by elGusto** [comment]
Also happens with `--preset=expo`

**Comment by FrozenPandaz** [comment]
Is this still occuring on the latest version of Nx?

**Comment by xiongemi** [comment]
it should be fixed in pr https://github.com/nrwl/nx/pull/22761
