### ISSUE TITLE
Intermittent 'setImmediate is not defined' Error with npx jest in NX Next.js Project

### ISSUE THREAD

**Issue by yamada-wacul** [nrwl/nx#20425]
### Current Behavior

In my NX-based Next.js project, running `npx jest` occasionally results in a `ReferenceError: setImmediate is not defined`.
This error does not consistently occur; sometimes all tests pass without any issue, and other times, the error appears across all tests.

### Expected Behavior

 expect that running npx jest should consistently execute tests without encountering the `setImmediate is not defined` error. The behavior should be stable and predictable, with no intermittent errors.

### Steps to Reproduce

1. Create a Next.js project within an NX workspace.
2. Write some tests using Jest.
3. Run the tests using npx jest.
4. Notice that occasionally, the tests fail with a ReferenceError: setImmediate is not defined, while at other times, the same tests pass without any errors.

### Nx Report

```shell
$ nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 20.9.0
   OS     : linux-x64
   npm    : 10.1.0
   
   nx                 : 17.1.3
   @nx/js             : 17.1.3
   @nx/jest           : 17.1.3
   @nx/linter         : 17.1.3
   @nx/eslint         : 17.1.3
   @nx/workspace      : 17.1.3
   @nx/devkit         : 17.1.3
   @nx/eslint-plugin  : 17.1.3
   @nx/next           : 17.1.3
   @nx/playwright     : 17.1.3
   @nx/react          : 17.1.3
   @nrwl/tao          : 17.1.3
   @nx/web            : 17.1.3
   typescript         : 5.3.2
```

### Failure Logs

A sample of the test result when it fails:

```shell
 FAIL   foo  lib/opensearch.spec.ts
  ● Test suite failed to run

    ReferenceError: setImmediate is not defined

      4 |
      5 | // Create a client with SSL/TLS enabled.
    > 6 | import { Client } from '@opensearch-project/opensearch';
        | ^
      7 | import { defaultProvider } from '@aws-sdk/credential-provider-node'; // V3 SDK.
      8 | import { AwsSigv4Signer } from '@opensearch-project/opensearch/aws';
      9 |

      at Object.<anonymous> (node_modules/@opensearch-project/opensearch/lib/Helpers.js:38:30)
      at Object.<anonymous> (node_modules/@opensearch-project/opensearch/index.js:38:17)
      at Object.require (lib/opensearch.ts:6:1)
      at Object.require (lib/opensearch.spec.ts:1:1)
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Hi, so if I understand correctly, you are running jest through the CLI and not via Nx?

**Comment by yamada-wacul** [comment]
@ndcunningham 
Hello,

After further investigation, I found that setting `maxWorkers: 1` in the `jest.config.ts` file seems to prevent the error from occurring. This change suggests that the issue might be related to the way Nx handles parallel processing in Jest.

However, this workaround is not ideal as it significantly slows down our test execution time. I suspect there might be an underlying issue with Nx's Jest integration or the configuration.

---

Additionally, I would like to provide some background information that might be relevant to this issue. Next.js project includes server actions and server components, which are inherently dependent on Node.js environment. This aspect of project complicates the Jest `testEnvironment` configuration as we need to accommodate both `jsdom` (for client-side) and `node` (for server-side) environments.

The challenge arises because these two environments need to coexist within the same Nx workspace and Jest configuration. It's not straightforward to separate them completely due to the intertwined nature of server and client components in Next.js. This complexity might be contributing to the intermittent `ReferenceError: setImmediate is not defined` we are experiencing.

I hope this additional context helps in understanding the complexity of our setup and could provide insights into a more nuanced solution.
