### ISSUE TITLE
Nx Playbook tutorial -Nx Workspaces (by Nrwl)- out of date

### ISSUE THREAD

**Issue by songlineboy** [nrwl/nx#20423]
### Documentation issue

 The basic Nx Playbook tutorial seems to be out of date with current version 17 of nx - so no much use to new user starting there.

- [ ] Reporting a tutorial bug

Nx Workspaces (by Nrwl)

https://nxplaybook.com/courses/

### Additional context or description

If you try to follow the course using v.17.1.3 you will see the cli responses don't match the tutorial options, so folder structure cannot be followed etc.

**Comment by juristr** [comment]
@songlineboy Hey! Yeah I'm sorry we're aware of that and are already planning to update them. Meanwhile here's some good places to get started:

- All links to getting started tutorials, articles, examples: https://nx.dev/getting-started/intro#learn-nx
- [Tutorials](https://nx.dev/getting-started/tutorials) (including videos)
- [Youtube channel](https://www.youtube.com/@nxdevtools) which has lots of educational content
- [Nx Community discord](https://go.nx.dev/community)
