### ISSUE TITLE
What does "-W" meaning in `npm install`？

### ISSUE THREAD

**Issue by yeongjet** [nrwl/nx#20427]
From [nx doc](https://nx.dev/getting-started/tutorials/package-based-repo-tutorial#create-a-new-workspace) 
<img width="738" alt="image" src="https://github.com/nrwl/nx/assets/7941297/4d4f6787-7989-45dc-8905-f6860a868f77">

but there is no "-W" argument in [npm doc](https://docs.npmjs.com/cli/v10/commands/npm-install).

**Comment by AgentEnder** [comment]
`-W` tells npm/yarn/pnpm to install the package into the root workspace when using workspaces, I'm not sure why it isn't documented on the npm site.
