### ISSUE TITLE
Update NX from v15 to v17 - Error with mini-css-extract-plugin

### ISSUE THREAD

**Issue by schatteleyn** [nrwl/nx#20428]
### Current Behavior

Hello everyone,
I'm trying to update the NX' version we're using on our project, and after a lot of battles, I'm arrived to a point I'm not sure what to do anymore.
This is a React 20 app running on Ubuntu.

After running my nx run serve, everything runs fine until bundle time, when I then have those long errors: 
[https://pastebin.com/B61HSdXu](https://pastebin.com/B61HSdXu
)

Seems like something is going wrong in the HotReload code of the Mini CSS Extract Plugin that is called inside NX.

Here are some of my code:

webpack.config.json:
https://pastebin.com/GQeKNHjz

nx.json
https://pastebin.com/KQFRs649

package.json
I had to add the mini css extract plugin directly in here earlier in the update process, I don't know if it could be causing some troubles.

https://pastebin.com/geTMxmvk

I hope this is enough details, 

### Expected Behavior

I need my app to finish the bundle step and launch

### Steps to Reproduce

1.

### Nx Report

```shell
➜  npx nx report
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 19.8.1
   OS     : linux-x64
   npm    : 9.5.1
   
   nx                 : 17.0.3
   @nx/js             : 17.0.3
   @nx/jest           : 17.0.3
   @nx/linter         : 17.0.3
   @nx/eslint         : 17.0.3
   @nx/workspace      : 17.0.3
   @nx/devkit         : 17.0.3
   @nx/eslint-plugin  : 17.0.3
   @nx/react          : 17.0.3
   @nrwl/tao          : 17.0.3
   @nx/web            : 17.0.3
   @nx/webpack        : 17.0.3
   typescript         : 4.4.4
   ---------------------------------------
   Community plugins:
   @gb-nx/cli : 3.3.0
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Are you still having issues with the `mini-css-extract-plugin` on the latest version of Nx?
