### ISSUE TITLE
Next.js: Broken styles when using styled-components

### ISSUE THREAD

**Issue by zynchro** [nrwl/nx#2042]
# Prerequisites
- [x] [...prerequisites]
- [x] Scoured StackOverflow

## Expected vs Current Behavior

Simply put; 
SASS = styling works beautifully.
styled-components = styling broken on initial page load, but applies on HMR.

### Steps to Reproduce

1. Install via `npx create-nx-workspace@latest sass --preset=next`
Selecting SASS for styling
![image](https://user-images.githubusercontent.com/6055731/68525459-b67c5280-02f7-11ea-8c69-5130dfc12d6e.png)
(note: styled-components unavailable here)

2. Remove the scss default
![image](https://user-images.githubusercontent.com/6055731/68525561-09a2d500-02f9-11ea-9df7-4049b11a0cfe.png)

3. Add another app, selecting styled-components
![image](https://user-images.githubusercontent.com/6055731/68525571-25a67680-02f9-11ea-85f2-6ca17cdcc1e1.png)

4.  Serve and check the apps

| nx serve styled-components | nx serve sass |
| - | - |
| ![image](https://user-images.githubusercontent.com/6055731/68525625-9b124700-02f9-11ea-8584-caa88089c22a.png) | ![image](https://user-images.githubusercontent.com/6055731/68525600-5e465000-02f9-11ea-9169-63feb4430e51.png) |

### Context

- nx report
```bash
  @nrwl/angular : Not Found
  @nrwl/cli : 8.7.0
  @nrwl/cypress : 8.7.0
  @nrwl/eslint-plugin-nx : 8.7.0
  @nrwl/express : Not Found
  @nrwl/jest : 8.7.0
  @nrwl/linter : 8.7.0
  @nrwl/nest : Not Found
  @nrwl/next : 8.7.0
  @nrwl/node : Not Found
  @nrwl/react : 8.7.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.7.0
  @nrwl/web : 8.7.0
  @nrwl/workspace : 8.7.0
  typescript : 3.4.5
```

- environment
```bash
node: v12.12.0
npm: 6.11.3
```

- 3rd-party libraries: none

- use case that failed: check above reproduction steps ☝️ 

- repro: https://github.com/zynchro/nx-issue-repro-styled-components

### Failure Logs

![image](https://user-images.githubusercontent.com/6055731/68525744-de20ea00-02fa-11ea-94a8-16588ac88c89.png)

**Comment by enjdusan** [comment]
I have the exact same problem, but with Next.js. Styles from styled components are missing after initial load, but they are applied after HMR.

**Comment by david0723** [comment]
I found a solution here https://spectrum.chat/next-js/general/quick-question-about-styled-components-ssr~7fb88ab0-037d-49e4-acac-ad52ef347de8

**Comment by enjdusan** [comment]
My issue was that server and client had a different classNames. I found a solution here:
https://github.com/zeit/next.js/issues/7423

**Comment by jaysoo** [comment]
It's possible if you override the document class and provide the babel plugins. 

See example here: https://github.com/jaysoo/react-ssr-example/tree/master/apps/next-app

Going to close this issue since there is a solution, but we might look at enhancing the generated code when `styled-components` is chosen. Cheers!

**Comment by zenVentzi** [comment]
Am I supposed to see styled-components as an option because I don't.![image](https://user-images.githubusercontent.com/11378653/74594294-3a538280-503d-11ea-9877-4f78be6656df.png)
