### ISSUE TITLE
Nx + Module federation + Angular gives error NG0912 when using gridstack 

### ISSUE THREAD

**Issue by ringo-anva** [nrwl/nx#20430]
### Current Behavior

Switching between different pages is given us the following warnings:

NG0912: Component ID generation collision detected. Components 'GridstackItemComponent' and 'GridstackItemComponent' with selector 'gridstack-item' generated the same component ID. To fix this, you can change the selector of one of those components or add an extra host attribute to force a different ID. Find more at https://angular.io/errors/NG0912

### Expected Behavior

No warning (for us this warning cause errors in production)

### GitHub Repo

https://github.com/ringo-anva/gridstack

### Steps to Reproduce

1. checkout main at repo https://github.com/ringo-anva/gridstack
2. npm install
3. npm run start
4. open devtools console
5. click on menu option 'remote 1'
6. click on menu optioni 'remote 2'

Now warnings should appear.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.17.0
   OS     : darwin-arm64
   npm    : 9.6.7
   
   nx                 : 17.1.2
   @nx/js             : 17.1.2
   @nx/jest           : 17.1.2
   @nx/linter         : 17.1.2
   @nx/eslint         : 17.1.2
   @nx/workspace      : 17.1.2
   @nx/angular        : 17.1.2
   @nx/cypress        : 17.1.2
   @nx/devkit         : 17.1.2
   @nx/eslint-plugin  : 17.1.2
   @nrwl/tao          : 17.1.2
   @nx/web            : 17.1.2
   @nx/webpack        : 17.1.2
   typescript         : 5.2.2
```

### Failure Logs

```shell
NG0912: Component ID generation collision detected. Components 'GridstackItemComponent' and 'GridstackItemComponent' with selector 'gridstack-item' generated the same component ID. To fix this, you can change the selector of one of those components or add an extra host attribute to force a different ID. Find more at https://angular.io/errors/NG0912
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jrab** [comment]
are you doing an esbuild? i think with Angular 17 they move away from webpack and start using esbuild to build the app. module federation was very dependent on webpack pre v17. i imagine the tooling will need to be updated. See more here:

https://www.angulararchitects.io/en/blog/micro-frontends-with-modern-angular-part-1-standalone-and-esbuild/

but for sure this needs to be updated on the nx side

**Comment by ringo-anva** [comment]
@jrab we are using webpack, hope Nx will have a solution for this. Cheers for your answer.

**Comment by ringo-anva** [comment]
@leosvelperez this solved our issue! Thank you.
