### ISSUE TITLE
depicting the sub-modules within library in deps-graph to yield usefull dep-graph of affected modules

### ISSUE THREAD

**Issue by sameerinfodb** [nrwl/nx#2044]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [Y] I am running the latest version
- [Y] I checked the documentation and found no answer
- [ Y] I checked to make sure that this issue has not already been filed
- [ Y] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Should be able to see the Sub Module within the Library in dep-graph.

## Current Behavior

I'm only able to see the dep-graph at lib and app level. Sub-modules within the library are not displayed .

### Context

My Monorepo structure is as follows

+ todo-app 
   + Core-Lib
   + Features-lib
     + User-mgmt- Module
     + role-mgmt - Module

when we run npm run dep-graph then the graph only shows the deps b/w todo-app -> Core-Lib & todo-app->Features-lib , but does not show the user-mgmt-module and role-mgmt-module under features-lib.

We were looking for this feature because when we change the sub-module and run dep-graph command then we want see all the affected library due to change in the sub-module a library.

Is there any way to get the affected deps-graph after considering sub-modules. Please suggest.

**Comment by jdpearce** [comment]
Hi @sameerinfodb - thanks for raising an issue. This isn't how we would recommend you organise your monorepo. Typically `User-mgmt` and `role-mgmt` would be completely separate libraries (e.g. `ng g @nrwl/angular:lib user-mgmt`). This would meant that we could track the dependencies. Tracking the dependencies of modules within each library is beyond the current scope of Nx.

I'd recommend you read through our book "Enterprise Angular Monorepo Patterns" for more information (see the [Nrwl Connect](https://connect.nrwl.io/app/books/enterprise-angular-monorepo-patterns) site).

**Comment by sameerinfodb** [comment]
Thanks for the inputs.
This means dependencies are tracked at library level not at module level in dep-graph. please confirm.

**Comment by jdpearce** [comment]
@sameerinfodb Yes, I believe that's true. I'm not sure how we _could_ track dependencies at the module level. That would require knowledge of how each library is compiled.

**Comment by webmandman** [comment]
I am just starting to use Nx and my initial thought was to create a UI lib with multiple components in it, and I foresee the components list growing over time. I noticed dep-graph doesn't not show  you which component was updated. 

So it would be nice if when you generate a component or module for a specific lib, you add this information to nx.json. Then you could observe where specifically the component was affected and display it under the "UI" lib. I'd say the specific component the lib would both be highlighted red in the graph. 

Any chance this could be added Nx? or extended via a community plugin?
