### ISSUE TITLE
Process exited with code 0

### ISSUE THREAD

**Issue by fliitor** [nrwl/nx#20446]
### Current Behavior

For now I use 16.5.3 and I just try 17 (with migrate command + check all files + commit before change)
Now I just rollback everything

```
git reset --hard HEAD
rm node_modules
pnpm i
npx nx reset
npx nx run app:task
```

but it stop with

` NX  Process exited with code 0, waiting for changes to restart...`

I try many things, impossible to have my code working...

NB: Now I've `Starting compilation in watch mode..` but I havn't that before
I don't understand what I don't rollback...

NB2: Build works as expected, and I can launch manually my generated code

If anyone have an idea, I'm out of ideas :/

### Expected Behavior

It should launch like before

### Steps to Reproduce

1. Update to 17
2. pnpm nx migrate
3. Rollback everythings

### Nx Report

```shell
Node   : 18.17.0
   OS     : win32-x64
   pnpm   : 8.6.10

   nx                 : 16.5.3
   @nx/js             : 16.5.3
   @nx/jest           : 16.5.3
   @nx/linter         : 16.5.3
   @nx/workspace      : 16.5.3
   @nx/cypress        : 16.5.3
   @nx/devkit         : 16.5.3
   @nx/esbuild        : 16.5.3
   @nx/eslint-plugin  : 16.5.3
   @nx/next           : 16.5.3
   @nx/node           : 16.5.3
   @nx/react          : 16.5.3
   @nrwl/tao          : 16.5.3
   @nx/web            : 16.5.3
   @nx/webpack        : 16.5.3
   typescript         : 5.2.2
```

### Failure Logs

```shell
Starting compilation in watch mode...


Found 0 errors. Watching for file changes.
Debugger listening on ws://localhost:9229/b535b896-b620-4378-9d08-99a37fec6fca
Debugger listening on ws://localhost:9229/b535b896-b620-4378-9d08-99a37fec6fca
For help, see: https://nodejs.org/en/docs/inspector

Debugger attached.

Waiting for the debugger to disconnect...


>  NX  Process exited with code 0, waiting for changes to restart...
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
There's been many fixes in the node executor since this issue was opened. Can you try again, and it's not working with the latest 17 or 18 Nx versions, can you open a new issue with a reproduction?

A reproduction speeds up the triage process.
