### ISSUE TITLE
Custom targets running in loops

### ISSUE THREAD

**Issue by andii1997** [nrwl/nx#20443]
### Current Behavior

I added some custom npm scripts in my packages and if I run affected projects on that target, the script starts a loop until an error occurs. In my example repo below I added a script which runs `npm version patch` and it increases 15-20 version numbers until it fails. In another project I have a similar issue with npm publish which runs twice (because the second publish failes).

### Expected Behavior

The script should only run once.

### GitHub Repo

https://gitlab.com/andii1997/nx-loop/

### Steps to Reproduce

In my demo project:
1. Run `npm run version:affected` in the project root

Project setup:
1. Created project using `npx create-nx-workspace`
2. Added package using `npx nx generate @nx/js:lib mylib`
3. Add script into packages `package.json`
4. Add script to root `package.json` with `nx affected -t [TARGET]`
5. Run that npm script or skip step 4 and run command directly

### Nx Report

```shell
Node   : 20.9.0
OS     : win32-x64
npm    : 9.8.0

nx                 : 17.1.3
@nx/js             : 17.1.3
@nx/linter         : 17.1.3
@nx/eslint         : 17.1.3
@nx/workspace      : 17.1.3
@nx/devkit         : 17.1.3
@nx/eslint-plugin  : 17.1.3
@nrwl/tao          : 17.1.3
typescript         : 5.2.2
```

### Failure Logs

```shell
>  NX   Running target version for project mylib
    ×  nx run mylib:version
       > mylib@0.0.98 versioning tasks...
> npm version patch
    ⠴    nx run mylib:version

> version
> npm version patch


> version
> npm version patch


> version
> npm version patch


> version
> npm version patch


> version
> npm version patch


> version
> npm version patch


> version
> npm version patch


> version
> npm version patch


> version
> npm version patch


> version
> npm version patch


> version
> npm version patch


> version
> npm version patch


> version
> npm version patch


> version
> npm version patch


> version
> npm version patch


> version
> npm version patch


> version
> npm version patch

The command "npm" is either misspelled or could not be found.
       npm ERR! code 1
npm ERR! path C:\Users\[USERNAME]\Documents\Dev\nx-loop\mylib
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm version patch
```

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

It happends on my local Windows 10 machine and also in the Gitlab CI within an node:20-alpine docker

**Comment by AgentEnder** [comment]
When you run `npm version`, it executes the version script beforehand. As such, you get a loop.

`npm run version` -> `npm version` -> `npm run version` ad infinitum

Nx is just running `npm run version`. You can validate this by renaming the script to anything other than version.

I'm going to close this out since its not an issue coming from Nx.
