### ISSUE TITLE
Support passing a list of test files to the Jest executor

### ISSUE THREAD

**Issue by cmparsons** [nrwl/nx#20462]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Similar to the existing `testFile` option, adding an option to the Jest executor that supports passing a list of tests files to run.

## Motivation

The [`@nx/vite:test` plugin seems to support this behavior already with `testFiles`](https://nx.dev/nx-api/vite/executors/test#testfiles), and it seems `testFiles` has replaced `testFile`, so this feature could bridge the functionality between the two test runners. 

At Netlify, we use the `circleci tests run` command to split tests for parallelization and to utilize [CircleCI's rerun failed tests feature](https://circleci.com/docs/rerun-failed-tests/). CircleCI's CLI will pass tests as a space-delimited list of files, so ideally we could easily hook into this behavior with a command like:
```bash
npx jest --listTests | circleci tests run --command="xargs npx nx run-many -t test --testFiles" --split-by=timings
```

## Suggested Implementation

Add a new option called `testFiles` to the Jest executor that is either a string with the expectation that it's a space-delimited list of file names or to match the vitest plugin, an array of strings (I'm not sure how `nx` would parse this from the CLI).

**Comment by leosvelperez** [comment]
hey @cmparsons! Thanks for the suggestion!

I'll look into adding support for this to the `@nx/jest:jest` executor. Please note that if you're using inferred tasks for Jest, you can already do this:

```
nx test <project> path/to/spec/file1 path/to/spec/file2
nx test <project> path/to/folder/containing/spec/files
```

The tasks inferred by the `@nx/jest` plugin run the Jest CLI directly `jest` from the project root as cwd. So, you're able to use anything the Jest CLI supports.
