### ISSUE TITLE
PandaCSS support

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#20479]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Like to tailwind integration, would be nice to have a PandaCSS generator config 

## Motivation
Be able to use PandaCSS

## Suggested Implementation
I already setup my repo and only fount one issue related to `panda codegen` and the `...createGlobPatternsForDependencies(__dirname)` call inside panda.config.ts, for now I commented that line

**Comment by AgentEnder** [comment]
We don't use panda css internally, nor have clients that are using it. I think this would be a good niche for a community plugin to fill, and once panda is more stable (currently on a 0.x release) and sees more adoption we may consider first party support.
