### ISSUE TITLE
Cant generate standalone files for next.js 13.4.1

### ISSUE THREAD

**Issue by aaronissac** [nrwl/nx#20486]
### Current Behavior

when using "nx build image-editor" and setting next.config.js to :

`const nextConfig = {
  nx: {
    // Set this to true if you would like to to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: false
  },

  compiler: {
    // For other options, see https://styled-components.com/docs/tooling#babel-plugin
    styledComponents: true
  },
  output: "standalone"
};
`
No standalone files are generated, and no server.js is genrated.

ive also tried  

` experimental: {
    outputFileTracingRoot: path.join(__dirname, "../../")
  },`

This is related to this bug: https://github.com/nrwl/nx/issues/9017
According to this issue, its supposed to be fixed but the problem persists.

### Expected Behavior

Genrate server.js and related standalone files.

### Steps to Reproduce

1.Create a repo with multiple next.js 13 projects.
2.build stand alone files.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.9.0
   OS     : darwin-arm64
   npm    : 10.1.0
   
   nx (global)        : 17.1.2
   nx                 : 17.1.1
   @nx/js             : 17.1.1
   @nx/jest           : 17.1.1
   @nx/linter         : 17.1.1
   @nx/eslint         : 17.1.1
   @nx/workspace      : 17.1.1
   @nx/devkit         : 17.1.1
   @nx/eslint-plugin  : 17.1.1
   @nx/next           : 17.1.1
   @nx/react          : 17.1.1
   @nrwl/tao          : 17.1.1
   @nx/web            : 17.1.1
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-container : 5.1.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Hey, can you create a sample repo illustrating the problem?
Is your problem similar to this: https://github.com/nrwl/nx/issues/18150 ?
