### ISSUE TITLE
`package.json`'s `name` field is having weird `source` text

### ISSUE THREAD

**Issue by iKrishnaSahu** [nrwl/nx#20496]
### Current Behavior

package.json's name field is having source text with workspace name

For example, if I use workspace name as `test-nx17ws` while creating new nx 17 workspace, then name field in `package.json` is set to `@test-nx17ws/source` which was not the case in previous version

Is this something new?

### Expected Behavior

Not sure. By why this change?

### Steps to Reproduce

1. `npx create-nx-workspace@17.1.3`
2. Use workspace name as `test-nx17ws` or anything
3. Once the command is successful, go to `package.json` and check name field

### Nx Report

```shell
C:\Projects\projects\workspaces2\5.12\test-nx17ws>nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.18.2
   OS     : win32-x64
   npm    : 8.19.3

   nx             : 17.1.3
   @nx/js         : 17.1.3
   @nx/workspace  : 17.1.3
   @nx/devkit     : 17.1.3
   @nrwl/tao      : 17.1.3
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
The root package.json isn't generally published, and we changed how we read the npm scope to be reading the root package.json name.

The `/source` isn't important, it could be `/anything`, but the scope used for your packages will be whatever the scope defined there is.
