### ISSUE TITLE
building multiple apps and deploying it as one.

### ISSUE THREAD

**Issue by a5hik** [nrwl/nx#205]
Question: How to run multiple apps together..

App1
App2
I need both App1 and App2 to work independently (can be built and deployed)
I know this is possible with nx.

But,
.. I have a super app that loads both App1 and App2.
Can routes operate this way between apps and the store?

Is this model doable with nx?

**Comment by wvanderdeijl** [comment]
Could you use an approach to create Lib1 and Lib2 with all the current code. Then create App1 that only consumes Lib1, an App2 that only consumes Lib2 and a SuperApp that consumes both libs?

**Comment by a5hik** [comment]
Yes I was doing exactly the same.. the shared ui code is moved to libs as
lazy loaded routes and I’m referring it from the specific app as well from
super app. Thus works perfect.
