### ISSUE TITLE
yarn lint disrespecting prettier config

### ISSUE THREAD

**Issue by vincaslt** [nrwl/nx#2051]
## Description

I'm trying to change prettier config for my projects:

```
{
  "useTabs": false,
  "printWidth": 100,
  "tabWidth": 2,
  "singleQuote": true,
  "semi": false,
  "trailingComma": "none"
}
```

Running `yarn lint` produces errors like: `6:24  error  Missing semicolon  semi`
I have also tried adding [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) and [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) to disable any rules that may be conflicting, but I still get this error. I have checked, and I have no semi rule declared explicitly in my configs, rules have not been changed after generating the config initially.

## Expected Behavior

No eslint errors on rules prettier takes care of.

## Current Behavior

Eslint "semi" conflicts with prettiers "semi" rules.

### Context

Please provide any relevant information about your setup:

- nx/report:
```
  @nrwl/angular : Not Found
  @nrwl/cli : 8.7.1
  @nrwl/cypress : 8.7.1
  @nrwl/eslint-plugin-nx : 8.7.1
  @nrwl/express : Not Found
  @nrwl/jest : 8.7.1
  @nrwl/linter : 8.7.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 8.7.1
  @nrwl/react : 8.7.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.7.1
  @nrwl/web : 8.7.1
  @nrwl/workspace : 8.7.1
  typescript : 3.6.4
```

- relevant package versions:
```
    "eslint": "^6.1.0",
    "eslint-config-prettier": "^6.5.0",
    "eslint-plugin-import": "2.18.2",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-prettier": "^3.1.1",
    "eslint-plugin-react": "7.16.0",
    "eslint-plugin-react-hooks": "2.1.2",
    "prettier": "1.18.2",
```

**A minimal reproduction scenario allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

**Comment by vincaslt** [comment]
Here is the example repo you where you can reproduce the issue: https://github.com/vincaslt/example-eslint-nx-error

This is generated by literally just:
1. `npx create-nx-workspace myworkspace` -> `react`
2. Add `"semi": false` to `.prettierrc`

Issue can be seen by running: `yarn lint`. Code has no semicolons as per prettier's formatting, but linter doesn't care.

**Comment by stramel** [comment]
I'm getting this as well. Same setup

**Comment by stramel** [comment]
@brandonroberts Would you prefer to unblock this that I throw together an entire repository that runs into this issue?

**Comment by brandonroberts** [comment]
@stramel I think the repro by @vincaslt is enough unless you have more information about the issue. Thanks

**Comment by iangregsondev** [comment]
I am also getting this, run npm run lint

I added the following to my eslint file until its resolved

```
    "semi": ["error", "never"],
```

To confirm my prettierrc is 

```
{
  "singleQuote": false,
  "semi": false,
  "printWidth": 132
}

```

and my eslint extends etc

```
  "plugins": ["@typescript-eslint", "@nrwl/nx", "jest"],
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier/@typescript-eslint",
    "prettier"
  ],
```

it states that the prettier should come last - which it does.

**Comment by Cammisuli** [comment]
This looks like it's related to the builder we use to do the linting.
https://github.com/angular-eslint/angular-eslint/blob/cf88cc15e21d0f8ff208ece008cec6dcfefffdba/packages/builder/src/index.ts#L199-L206

They have `semi` set to always error when running the CLI engine.

**Comment by zishe** [comment]
Same behaviour. `nx format:write` doesn't do anything too.

**Comment by stramel** [comment]
@vsavkin After updating my `@nrwl` deps to `8.11.0` I still had to manually force `"@angular-eslint/builder"` to `v0.0.1-alpha.18`
