### ISSUE TITLE
Cannot use expo's  webpack from expo/webpack-config or custom webpack for expo-web project in NX

### ISSUE THREAD

**Issue by arishZype** [nrwl/nx#20521]
### Current Behavior

I have 2 projects integrated in NX. One is a bare react-native project and another is an expo-web project which uses react-native-web under the hood.

Now, when I was running the expo-web project seperately, expo handled the webpack code on its own but it gave a command as below 
> npx expo customize webpack.config.js

which gives a customizable webpack file, where I could do any other operations like optimization with bundle chunks or tree shaking or minifying or any other webpack functionality.

After integrating with nx, my customizeable webpack of expo was no longer used as nx handles it on its own.

Now that is fine but working with this flow creates a bundle size of 7 mb which is huge as I cannot do any bundle size reducing configurations which were available without nx. This huge bundle size makes the website slow and reduces the performance.

There is a page on nx documentation to ```Configure webpack on your Nx workspace```, but it is not valid for expo-web projects as webpack of expo-web is handled internally from expo and not from nx. 

### Expected Behavior

Either It should let me use my expo customizeable build, or provide a way in which I can add those configurations in nx's webpack.

### GitHub Repo

https://github.com/arishZype/NXExpoWebDemo.git

### Steps to Reproduce

Step 1: Create NX Workspace
> npx create-nx-workspace my-project --preset=react-native --appName=mobile

Step 2: Install Expo
> npm i --save-dev @nx/expo

Step 3: Create Expo-web Project
> nx g @nx/expo:app my-project-web

Step 4: Run Web
> npx nx start my-project-web
> If you get ```[Bug]: Cannot read properties of undefined (reading 'addHelper') ```, update all babel dependencies and reinstall dependencies and run again

Step 5: Build it using the command
> npx nx export my-web-project --platform=web

Step 6: The bundle generated is a single file and not chunks. To try to make it into chunks, run the customize command in apps/my-web-project dir as below

> npx expo customize webpack.config.js

Step 7: Add a simple console in this config file and run it.

Step 8: You'll observe that although a new custom webpack.config.js file is created, it still is not getting used.

Step 9: Thus the code for optimization, tree shaking, minifying, bundle analyzing, etc cannot be written in the webpack.

### Nx Report

```shell
   Node   : 18.8.0
    OS     : darwin-x64
   npm    : 8.19.1
   
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/detox          : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/expo           : 16.4.0
   @nx/react          : 16.10.0
   @nx/react-native   : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/web            : 16.4.0
   @nx/webpack        : 16.4.0
   nx-cloud           : 16.5.2
   typescript         : 5.1.3
```

### Operating System

- [X] macOS

**Comment by SwapnilkRespo** [comment]
i'm facing the same issue

**Comment by Pratish149** [comment]
I am also facing similar issue. Any solutions ??

**Comment by fahimalizain** [comment]
Facing the same issue now.

**Comment by aykutyilmaz37** [comment]
same problem

**Comment by aykutyilmaz37** [comment]
There is no problem when I use expo with a single project. However, when I add more than one project, @expo/webpack-config gives an error and does not run the project completely.

**Comment by malaganator3000** [comment]
> There is no problem when I use expo with a single project. However, when I add more than one project, @expo/webpack-config gives an error and does not run the project completely.

I'm experiencing the same issue. When working with expo on a single project, everything runs smoothly. However, when trying to add more than one project, I encounter errors with @expo/webpack-config that prevent the project from running fully. Any solutions or suggestions for managing multiple projects efficiently?

**Comment by xposionn** [comment]
> There is no problem when I use expo with a single project. However, when I add more than one project, @expo/webpack-config gives an error and does not run the project completely.

Same issue, I have an expo and nestjs and I'm facing the same issue,
I have tried to start with nestjs and then add expo and vise versa, both tried give the same error

**Comment by aykutyilmaz37** [comment]
I solved this problem for now as follows.
I disabled webpack.config.js. and I removed it from tsconfig.json file.
The project is configured with the metro.config.js file and start. I'm not sure it's the right solution.

**Comment by xposionn** [comment]
> I solved this problem for now as follows.
> 
> I disabled webpack.config.js. and I removed it from tsconfig.json file.
> 
> The project is configured with the metro.config.js file and start. I'm not sure it's the right solution.

How did you disabled the webpack.config.ts?

**Comment by aykutyilmaz37** [comment]
> > I solved this problem for now as follows.
> > I disabled webpack.config.js. and I removed it from tsconfig.json file.
> > The project is configured with the metro.config.js file and start. I'm not sure it's the right solution.
> 
> How did you disabled the webpack.config.ts?

I just deleted webpack.config.js. I will look at the configuration settings later

**Comment by xiongemi** [comment]
according to expo docs https://docs.expo.dev/router/migrate/from-expo-webpack/: "@expo/webpack-config is deprecated and not receiving any new feature updates."

so it is better to use metro as bundler. please delete the webpack.config.js.

i am going to close this issue for now.
