### ISSUE TITLE
Angular monorepo with module federation, relative remotes are not loaded

### ISSUE THREAD

**Issue by miguelchico** [nrwl/nx#20545]
### Current Behavior

Using Nx 17.1.3:

I've followed the documentation to create an angular application to use module federation.
I've created one host application and two remotes (remote1 and remote2) and everything works fine on development.

The content of my webpack.prod.config.ts file is something like:

```ts

....
remotes: [
 ['remote1', '/remote1Path'],
 ['remote2', '/remote2Path']
]
....

```

When I build the application using `nx build host --configuration=production` the application is built and I can see all the resources in the dist folder.
After that, I'm starting an Nginx server (on port 9000) to serve the dist folder.

When I load the host application in the browser with http://localhost:9000 the application is not loading correctly.

I can see a request for http://localhost:9000/remote1 that I've configured to return the remoteEntry.mjs file in the dist folder and after that I can see request trying to load the chunks of the remote1 application but they are like: http://localhost:9000/xxxxxx.js (where xxxxx is just a valid chunk for the app)

If I just change the webpack.prod.config.ts file is something like:

```ts

....
remotes: [
 ['remote1', 'http://localhost:9000/remote1Path'],
 ['remote2', 'http://localhost:9000/remote2Path']
]
....

```

Everything works fine, I don't need to do anything special to load the remoteEntry.mjs because it is loaded correctly and chunks for all remotes are loaded.

Same application but using Nx version 16.10.0 works fine with relative definitions for remotes

### Expected Behavior

Using a relative path for remotes should work without any issue

### Steps to Reproduce

1. Create a nx monorepo
2. Add host and remotes application
3. Configure relative url for remotes
4. Build app
5. Serve application with nginx (for example) from dist folder
6. Load the app

### Nx Report

```shell
NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : darwin-x64
   npm    : 10.2.3
   
   nx                 : 17.1.3
   @nx/js             : 17.1.3
   @nx/jest           : 17.1.3
   @nx/linter         : 17.1.3
   @nx/eslint         : 17.1.3
   @nx/workspace      : 17.1.3
   @nx/angular        : 17.1.3
   @nx/cypress        : 17.1.3
   @nx/devkit         : 17.1.3
   @nx/eslint-plugin  : 17.1.3
   @nrwl/tao          : 17.1.3
   @nx/web            : 17.1.3
   @nx/webpack        : 17.1.3
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @koliveira15/nx-sonarqube : 3.4.0
   @ngrx/component-store     : 17.0.1
   @ngrx/effects             : 17.0.1
   @ngrx/entity              : 17.0.1
   @ngrx/router-store        : 17.0.1
   @ngrx/schematics          : 17.0.1
   @ngrx/store               : 17.0.1
   @ngrx/store-devtools      : 17.0.1
   angular-auth-oidc-client  : 16.0.1
   ngrx-immer                : 2.1.1
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Spookyfan** [comment]
Had the same issue while updating to NX and Angular 17
Appending `remoteEntry.mjs` to your remotes fixed the problem for me, if you require relative paths.
```
....
remotes: [
 ['remote1', '/remote1Path/remoteEntry.mjs'],
 ['remote2', '/remote2Path/remoteEntry.mjs']
]
....
```
