### ISSUE TITLE
Add option to only read from a remote cache

### ISSUE THREAD

**Issue by jovdb** [nrwl/nx#20543]
## Description
I would like:
- locally: read from remote cache (if local cache miss), but **don't write** WIP code to remote cache
- CI: read and write to the remote cache, so only CI will add pushed code to the remote cache

## Motivation
During development and running local scripts:
- Prevent polluting the remote cache with caches of WIP code that is not useful for other users/CI
- Faster to store in local cache than uploading to remote cache
- Less costs when only using remote buckets for public available commits

## Alternate Implementations
I don't think these options can help me:
`--skip-nx-cache`: No cache is used
`--no-cloud`: Only local cache is used, so when checking out a branch, we cannot use the remote cache

**Comment by StalkAltan** [comment]
You can achieve this by committing a `read-only` access token to your `nx.json` (https://nx.dev/ci/recipes/security/access-tokens)

You can find some more info about how we suggest configuring your Nx Cloud workspace here: https://nx.dev/ci/concepts/cache-security

**Comment by jovdb** [comment]
Probably important to mention:
I don't use NX Cloud, I use a custom remote cache (Google Clould Storage Bucket)
I assume the access token solution is only for NX Cloud
