### ISSUE TITLE
Setting "watch": false for next custom-server does not work

### ISSUE THREAD

**Issue by stomvi** [nrwl/nx#20550]
### Current Behavior

Setting "watch": false in `development` config of the `build-custom-server` target does not work.  Tried to print the options and it shows `options.watch` is still `true`.

### Expected Behavior

`custom-server` build behavior should follow project.json config. 

### Steps to Reproduce

1. npx create-nx-workspace --preset=next --name=test --appName=www
2. npx nx g @nx/next:custom-server --projectName=www
3. Edit the `build-custom-server` section of file: test/apps/www/project.json
4. Add "watch": false to `build-custom-server.configurations.development`
5. Start the server by `npx nx serve www`

### Nx Report

```shell
Node   : 20.9.0
OS     : linux-x64
npm    : 10.1.0

nx                 : 17.1.3
@nx/js             : 17.1.3
@nx/jest           : 17.1.3
@nx/linter         : 17.1.3
@nx/eslint         : 17.1.3
@nx/workspace      : 17.1.3
@nx/cypress        : 17.1.3
@nx/devkit         : 17.1.3
@nx/esbuild        : 17.1.3
@nx/eslint-plugin  : 17.1.3
@nx/next           : 17.1.3
@nx/node           : 17.1.3
@nx/react          : 17.1.3
@nrwl/tao          : 17.1.3
@nx/web            : 17.1.3
typescript         : 5.2.2
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Next.js does fast refresh by default. The custom server-generated uses `next()` which is Next.js' server.
There is no way to turn this off and it is working and encouraged by the Vercel team.
https://github.com/vercel/next.js/issues/1109#issuecomment-279582855
