### ISSUE TITLE
Integrated Workspace Generation missing directories

### ISSUE THREAD

**Issue by cjkoral** [nrwl/nx#20569]
### Current Behavior

from this link https://nx.dev/getting-started/tutorials/integrated-repo-tutorial#getting-started-with-integrated-repos

i should be able to run this command

`npx create-nx-workspace@latest myorg --preset=ts`

and it should create the directory structure

```myorg/
├── packages/
├── tools/
├── nx.json
├── package.json
├── README.md
└── tsconfig.base.json
```

however when i run this the `packages` and `tools` directory are not present. 

### Expected Behavior

this command

`npx create-nx-workspace@latest myorg --preset=ts`

builds the following directory structure

```myorg/
├── packages/
├── tools/
├── nx.json
├── package.json
├── README.md
└── tsconfig.base.json
```

### Steps to Reproduce

1. Run `npx create-nx-workspace@latest myorg --preset=ts`
2. view file structure

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 19.6.0
   OS     : darwin-arm64
   npm    : 9.4.0

   nx (global)    : 17.1.3
   nx             : 17.1.3
   @nx/js         : 17.1.3
   @nx/workspace  : 17.1.3
   @nx/devkit     : 17.1.3
   @nrwl/tao      : 17.1.3
   typescript     : 5.2.2
```

### Failure Logs

```shell
none
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Not clear if it is a CLI bug or Docs bug.

**Comment by FrozenPandaz** [comment]
The above page does not mention that directory structure anymore.
