### ISSUE TITLE
Update Rescope Packages page

### ISSUE THREAD

**Issue by acostajake** [nrwl/nx#20573]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [X] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.
The [Compatability Matrix](https://nx.dev/nx-api/workspace/documents/nx-nodejs-typescript-version-matrix) indicates some versions of Nx work with some versions of Node. There is some confusion here because the order of supported node versions is unexpected.
Nx 15.9.5 supports Node 16
Nx 16 -> 16.4.0 requires Node 18
Nx 16.4.1 supports Node 16 again

### Additional context or description
[Rescoping](https://nx.dev/recipes/other/rescope) was a big enough change that it warranted a special page to separate it from other migration docs that bump plugin versions.
Rescoping while using Node <18 crashes because of a package dependency yarnpkg/parsers that was [pinned to support Node 16 in the Nx 15.95 release](https://github.com/nrwl/nx/releases/tag/15.9.5) but bumped with the Nx 16 release.
The package was later [pinned in Nx 16.4.1](https://github.com/nrwl/nx/pull/17860) to avoid dropping support for Node 16.

Provide any additional details here as needed.
**Suggestion**: If developers are on Node <18, and Nx <16 and want to rescope to NX >16, this should be called out on the rescoping page.

**Comment by isaacplmann** [comment]
We aren't going to dedicate resources to update documentation for a version of Node (16) that is no longer in LTS and a version of Nx (16) that is at the very end of the LTS cycle.
