### ISSUE TITLE
unable to find tsconfig.base.json or tsconfig.json

### ISSUE THREAD

**Issue by CGQAQ** [nrwl/nx#20574]
### Current Behavior
```
D:\Code\Personal\2b\web>nx g @nx/next:app core --verbose   

 >  NX   Unable to resolve @nx/next:app.

   unable to find tsconfig.base.json or tsconfig.json

Error: Unable to resolve @nx/next:app.
unable to find tsconfig.base.json or tsconfig.json
    at getGeneratorInformation (D:\Code\Personal\2b\.nx\installation\node_modules\nx\src\command-line\generate\generator-utils.js:39:15)
    at D:\Code\Personal\2b\.nx\installation\node_modules\nx\src\command-line\generate\generate.js:218:248
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleErrors (D:\Code\Personal\2b\.nx\installation\node_modules\nx\src\utils\params.js:9:16)
```
### Expected Behavior

create successfully

### Steps to Reproduce

1. nx g @nx/next:app core --verbose

### Nx Report

```shell
Node   : 20.9.0
OS     : win32-x64
npm    : 10.1.0

nx (global)  : 17.1.3
nx           : 17.1.3
@nrwl/tao    : 17.1.3
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Oh, also, it would be super helpful if you could provide a minimum reproduction repository!

**Comment by CGQAQ** [comment]
repro repo: https://github.com/CGQAQ/nx-20574-repro

**Comment by mandarini** [comment]
@CGQAQ hmm I do not see a `package.json` file in your project...

**Comment by mandarini** [comment]
So, I have some updated info @CGQAQ after talking with @AgentEnder who knows more about this setup! :)

First, you can, indeed, run generators from plugins listed in your `nx.json` installation section without a `package.json` present in your repo root. However, none of our first-party generators are written with this in mind, including `@nx/next` which you're trying to use.

Second, you don't seem to have the `@nx/next` plugin installed inside the `nx.json[installation]` block, so its not installed there.

Third, JavaScript based projects don't really benefit from `.nx` install, so maybe you should consider scaffolding your repo in another way, maybe using `create-nx-workspace`: https://nx.dev/getting-started/installation

Let me know if these things help!

**Comment by CGQAQ** [comment]
The thing is I have a project that is NOT pure js, it's half Rust half js, so first thing I did is look up docs, and found [installing-nx-into-an-existing-repository](https://nx.dev/getting-started/installation#installing-nx-into-an-existing-repository), then I search 'nextjs nx' and found [this](https://nx.dev/nx-api/next/documents/overview), and I don't want package.json in my root, so I skipped the first step and directly ran `nx g @nx/next:lib my-new-lib`, after doing these:

1. `npm init -y`
2. `npm install --save-dev @nx/next`
3. `nx g @nx/next:app my-new-app` 

it works now, so I guess I should close the issue, thanks

**Comment by CGQAQ** [comment]
> However, none of our first-party generators are written with this in mind, including @nx/next which you're trying to use.

@mandarini The thing I still not quite get is that if none of your generators support this, why you generate in this way by default in this [command](https://nx.dev/getting-started/installation#installing-nx-into-an-existing-repository), it's very confusing.

**Comment by CodeMedic42** [comment]
I am going to jump in here as well as I am running into what appears to be the same error message. However I am getting it when trying to run a command for a third party generator. I am trying to run the following command and get the following error dump.

```
nx g @jscutlery/semver:install --verbose
```

```
 >  NX   Unable to resolve @jscutlery/semver:install.

   unable to find tsconfig.base.json or tsconfig.json

Error: Unable to resolve @jscutlery/semver:install.
unable to find tsconfig.base.json or tsconfig.json
    at Workspaces.readGenerator (/Users/me/source/project/node_modules/.pnpm/nx@15.9.7/node_modules/nx/src/config/workspaces.js:151:19)
    at Object.<anonymous> (/Users/me/source/project/node_modules/.pnpm/nx@15.9.7/node_modules/nx/src/command-line/generate.js:229:209)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/me/source/project/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I honestly have no idea what to even do with this message. I am hoping someone might have an idea of where I can start poking around in to try and find a solution.

**Comment by AgentEnder** [comment]
Hey @CGQAQ, there's a few things to break down here:

- The error is confusing, its something that changed because when we try to resolve plugins if it fails then we look for local plugins, which requires the tsconfigs. This should be updated.

- The `.nx` setup is intended mainly for repos that don't use generators to get things up and running. The only way it gets generated when running `nx init`, is if you pick to initialize nx inside a folder that doesn't have a package.json in it. This typically matches the assumption that you won't be running generators which would add a package.json there.

I hope this clears things up. I'll work on cleaning the error message up, but lets keep the issue closed since you were able to correct the configuration in your repo and we can work on clearing docs up as time goes on.
