### ISSUE TITLE
print-affected always prints everything without affected information

### ISSUE THREAD

**Issue by pascalruscher** [nrwl/nx#2057]
## Expected Behavior

For my CI process I need an overview of only affected apps and libs in my repository with information like name, root, type. I used `nx print-affected` for this case. I expected to get only the affected apps/libs or at least an information about the modification in the graph. Maybe I am just missing some options to get what I want?

## Current Behavior

I get all my apps and libs printed instead of only modified/affected ones.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `npx create-nx-workspace@latest nx-demo`
2. ? What to create in the new workspace empty             [an empty workspace]
3. ? CLI to power the Nx workspace       Angular CLI  [Extensible CLI for Angular applications. Recommended for Angular projects.]
4. `cd nx-demo`
5. `npm install --save-dev @nrwl/angular`
6. `nx g @nrwl/angular:lib functions`
7. `nx g @nrwl/angular:application dummy`
8. commit everything
9. modify something in apps/dummy for example app.component.ts
10. `nx print-affected`

``` JSON
{ 
   "tasks":[ 

   ],
   "dependencyGraph":{ 
      "projects":{ 
         "dummy-e2e":{ 
            "name":"dummy-e2e",
            "root":"apps/dummy-e2e",
            "type":"e2e",
            "tags":[  ],
            "architect":{  },
            "files":[  ],
            "implicitDependencies":[  ],
            "fileMTimes":{  }
         },
         "functions":{ 
            "name":"functions",
            "root":"libs/functions",
            "type":"lib",
            "tags":[  ],
            "architect":{  },
            "files":[  ],
            "implicitDependencies":[  ],
            "fileMTimes":{  }
         },
         "dummy":{ 
            "name":"dummy",
            "root":"apps/dummy",
            "type":"app",
            "tags":[  ],
            "architect":{  },
            "files":[  ],
            "implicitDependencies":[  ],
            "fileMTimes":{  }
         }
      },
      "dependencies":{ 
         "dummy-e2e":[ 
            { 
               "projectName":"dummy",
               "type":"implicit"
            }
         ],
         "functions":[ 

         ],
         "dummy":[ 

         ]
      },
      "roots":[ 
         "dummy-e2e",
         "functions"
      ]
   }
}
```
As you can see I get the dummy projects (which I modified) and the functions lib which I didn't touch.

### Context

`nx report`

```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 8.7.1
  @nrwl/cli : 8.7.1
  @nrwl/cypress : 8.7.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.7.1
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.7.1
  @nrwl/web : Not Found
  @nrwl/workspace : 8.7.1
  typescript : 3.4.5
```

When I run `nx affected:apps` I get:
```
>  NX   NOTE  Affected criteria defaulted to --base=master --head=HEAD


>  NX  Affected apps:

  - dummy
```
and `nx affected:libs`:
`>  NX   NOTE  Affected criteria defaulted to --base=master --head=HEAD`

and `nx affected:dep-graph --file=deps.json`:
```
{
  "deps": {
    "dummy-e2e": [
      {
        "projectName": "dummy",
        "type": "implicit"
      }
    ],
    "functions": [],
    "dummy": []
  },
  "affectedProjects": [
    "dummy",
    "dummy-e2e"
  ],
  "criticalPath": [
    "dummy",
    "dummy-e2e"
  ]
}
```
Which is correct.

**Comment by isaacplmann** [comment]
If you give `nx print-affected` a target, it will list out the correct tasks in the `tasks` array.

`nx print-affected --target=lint`

I'm not sure what the intended behavior is, but this should get the information you want.

**Comment by pascalruscher** [comment]
Well I would have to read out the projects from the tasks array and find the projects in the dependency graph because I need the information from there. And as print-affected is named I expect to get all affected projects listed there.

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by martaGalveSwipejobs** [comment]
Is there a solution or alternative to this command to find the name of affected projects?

**Comment by pauleustice** [comment]
> Is there a solution or alternative to this command to find the name of affected projects?

I'm not 100% what the original author needed, but I _think_ it's just a list of affected apps. If that's the case, you can use

`nx print-affected --select=projects` which outputs a CSV, e.g. `app1, app2`. That means it can easily be converted to an array if needed in whichever script consumes it.
