### ISSUE TITLE
nx run  Command failed

### ISSUE THREAD

**Issue by rnyschyi** [nrwl/nx#20579]
### Current Behavior

I'm trying to run `nx run vos-local:serve:development`, and receive message 

>  NX   Command failed: %windir%\System32\REG.exe QUERY HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography /v MachineGuid

![image](https://github.com/nrwl/nx/assets/12164294/50883d39-fad1-4a46-ad5c-8b2fcab6ff5a)

### Expected Behavior

project should start

### Steps to Reproduce

1. go to project directory
2. run  nx run vos-local:serve:development

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 21.2.0
   OS     : win32-x64
   npm    : 10.2.3

   nx (global)        : 17.0.3
   nx                 : 17.0.3
   @nx/js             : 17.0.3
   @nx/jest           : 17.0.3
   @nx/linter         : 17.0.3
   @nx/eslint         : 17.0.3
   @nx/workspace      : 17.0.3
   @nx/angular        : 17.0.3
   @nx/cypress        : 17.0.3
   @nx/devkit         : 17.0.3
   @nx/eslint-plugin  : 17.0.3
   @nrwl/tao          : 17.0.3
   @nx/web            : 17.0.3
   @nx/webpack        : 17.0.3
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @ngrx/component       : 16.0.0
   @ngrx/component-store : 16.0.0
```

### Package Manager Version

npm 10.2.3

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Can you run with `--verbose` or `NX_VERBOSE_LOGGING=true` and grab a stack trace?

**Comment by rnyschyi** [comment]
> I'm trying to run `nx run vos-local:serve:development`, and receive message
> 
> >


`> @vos/source@0.0.0 vos-local-dev
> nx run vos-local:serve:development  --verbose

[NX CLOUD] Verifying current cloud bundle
[NX CLOUD] A local bundle currently exists:  {
  version: '2312.20.5.hotfix1',
  fullPath: 'C:\\Users\\nro\\WebStorm Projects\\VOS.TransportOrders\\src\\client\\.nx\\cache\\cloud\\2312.20.5.hotfix1'
}
[NX CLOUD] Last verification was more than 30 minutes ago, verifying bundle is still valid
[NX CLOUD] Currently installed bundle is invalid, downloading version 2401.03.1  from  https://cloud.nx.app/nx-cloud/static/client-bundle
[NX CLOUD] Done:  C:\Users\nro\WebStorm Projects\VOS.TransportOrders\src\client\.nx\cache\cloud\2401.03.1
ERROR: Registry editing has been disabled by your administrator.

 >  NX   Command failed: %windir%\System32\REG.exe QUERY HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography /v MachineGuid

   ERROR: Registry editing has been disabled by your administrator.


Error: Command failed: %windir%\System32\REG.exe QUERY HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography /v MachineGuid
ERROR: Registry editing has been disabled by your administrator.

    at genericNodeError (node:internal/errors:956:15)
    at wrappedFn (node:internal/errors:510:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at l (C:\Users\nro\WebStorm Projects\VOS.TransportOrders\src\client\.nx\cache\cloud\2401.03.1\index.js:3:394)
    at Jr (C:\Users\nro\WebStorm Projects\VOS.TransportOrders\src\client\.nx\cache\cloud\2401.03.1\index.js:7:2861)
    at XC (C:\Users\nro\WebStorm Projects\VOS.TransportOrders\src\client\.nx\cache\cloud\2401.03.1\index.js:27:12818)
    at Di (C:\Users\nro\WebStorm Projects\VOS.TransportOrders\src\client\.nx\cache\cloud\2401.03.1\index.js:27:15457)
    at Object.U0 (C:\Users\nro\WebStorm Projects\VOS.TransportOrders\src\client\.nx\cache\cloud\2401.03.1\index.js:30:7059)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Process finished with exit code 1
`

**Comment by aklokov** [comment]
is there any solution for this issue?
