### ISSUE TITLE
How to update dependencies to newest version

### ISSUE THREAD

**Issue by puschie286** [nrwl/nx#20570]
### Documentation issue

The [documentation](https://nx.dev/core-features/automate-updating-dependencies) only shows how to update nx itself but not how to update dependencies (like angular or any other package). This question has been asked several times, but none of the answers are suitable for all situations

If you try to update a single dependency (like @angular/core) nx migrate will create an broken package.json with only some dependency updated and others not - this will cause the suggested next step of "npm install" to fail. if you update the next dependency (that is mentioned in npm install fail), it get updated in package.json (partly again) but override the migration.json. So you have to manually take care of the migration.json and merge them. (Mentioned [here](https://github.com/nrwl/nx/issues/17100#issuecomment-1555643177))

The whole process is very error prone and can easy lead to missing migrations. This should at least be mentioned in the updating dependencies documentation.

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?
[Dependency Updating](https://nx.dev/core-features/automate-updating-dependencies)

### Additional context or description

Would be great if this could be automated by two changes:
- merge migrations.json files
- use the dependency tree to repeat 'nx migrate {package}' untill all dependencies are updated

**Comment by Tom4U** [comment]
As dependencies might be quite complex, depending on the project itself, I don't know if it would be a good idea to automatically update all dependencies.

For me, I've found a simple solution on Bash (or Git Bash if using Windows) where I could better control what will be updated next.

For instance, I've had to update all storybook packages (_@storybook/*_), so I've used the following command:
`npm outdated | awk '{print $1}' | grep storybook | xargs -I % sh -c 'nx migrate %@latest'`

That way you will have more control over the packages being updated.
