### ISSUE TITLE
Dev Server Configuration

### ISSUE THREAD

**Issue by ecnaidar** [nrwl/nx#2061]
In our case specific development environment setup causes issue with exposing dev server.
Solution for webpack dev server outlined here https://github.com/webpack/webpack-dev-server/issues/147

Solvable by providing "disableHostCheck: true" to webpack config which is currently impossible pass through

**Comment by xtiancapil** [comment]
You can define a custom webpack config and change the `webpackConfig` property in the `architect.build` sectino of your workspace.json to use thecustom one.

Here's a sample. In my sample I'm referencing the client, but you could probably change it to get the devServer:
```
const getBabelWebpackConfig = require('@nrwl/react/plugins/babel');
const devServerClient = require.resolve('webpack-dev-server/client');

module.exports = (config, context) => {        
    const cfg = getBabelWebpackConfig(config);

    cfg.entry.main = [        
        devServerClient + '?http://0.0.0.0:4200',
        context.buildOptions.main
    ];
    cfg.devServer.public = "http://localhost:4200";
    cfg.devServer.allowedHosts = ['localhost'];
    cfg.devServer.disableHostCheck = true;
    cfg.devServer.host = 'localhost';    

    return cfg;
};
```

**Comment by ecnaidar** [comment]
Well, that looks quite complicated but workable. 
Will look into that, thanks.

**Comment by elkeis-on-work** [comment]
try this also
```
"serve": {
                    "executor": "@nrwl/web:dev-server",
                    "options": {
                        ...
                        "allowedHosts": "host.docker.internal,localhost"
                    },
                    ...
                }
```

**Comment by zakhenry** [comment]
Thanks @elkeis-on-work  - this is now an array though

```json
      "options": {
        "allowedHosts": ["localhost", "host.docker.internal"]
      },
```
