### ISSUE TITLE
Quick way of converting workspace.json to angular.json for use with angular console ?

### ISSUE THREAD

**Issue by iangregsondev** [nrwl/nx#2062]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Is there a way to convert a workspace.json to angular.json ?

I created an application using the nx cli rather than choosing angular cli but this has an issue that angular console cannot work with the project.

I would like to know how difficult it is to convert a workspace.json to an angular.json

Anybody know is there is some work planned to rebrand the angular console ?

Like NX Console and works with both angular.json and workspace.json ?

Thanks in advance

**Comment by jdpearce** [comment]
Hi @iangregsondev - the workspace file (angular/workspace.json) should have the same format regardless of which CLI you choose, which means you may be able to get away with just renaming it. There are other dependencies installed though - e.g. Angular CLI for a start.

If you have a question about the Angular Console roadmap, you may want try looking in their repo where you can raise a separate issue if need be : https://github.com/nrwl/angular-console

**Comment by iangregsondev** [comment]
ok - i will give it a try - thanks.

**Comment by beeman** [comment]
For future reference, I had the same question as I was looking to use `ng add` in my workspace built with the `nx` cli. 

When running the command I got this error:

```
$ ng add @nguniversal/express-engine --clientProject web
The add command requires to be run in an Angular project, but a project definition could not be found.
```

Luckily, we don't have to change a whole lot to our project to fix this. Making a symlink makes it work:

```
$ ln -s workspace.json angular.json
$ ng add @nguniversal/express-engine --clientProject web
Skipping installation: Package already installed
CREATE apps/web/src/main.server.ts (298 bytes)
CREATE apps/web/src/app/app.server.module.ts (318 bytes)
CREATE apps/web/tsconfig.server.json (330 bytes)
CREATE apps/web/server.ts (2003 bytes)
UPDATE package.json (5759 bytes)
UPDATE angular.json (20794 bytes)
UPDATE apps/web/src/main.ts (431 bytes)
UPDATE apps/web/src/app/app.module.ts (786 bytes)
✔ Packages installed successfully.
```

**Comment by YonathanB** [comment]
> For future reference, I had the same question as I was looking to use `ng add` in my workspace built with the `nx` cli.
> 
> When running the command I got this error:
> 
> ```
> $ ng add @nguniversal/express-engine --clientProject web
> The add command requires to be run in an Angular project, but a project definition could not be found.
> ```
> 
> Luckily, we don't have to change a whole lot to our project to fix this. Making a symlink makes it work:
> 
> ```
> $ ln -s workspace.json angular.json
> $ ng add @nguniversal/express-engine --clientProject web
> Skipping installation: Package already installed
> CREATE apps/web/src/main.server.ts (298 bytes)
> CREATE apps/web/src/app/app.server.module.ts (318 bytes)
> CREATE apps/web/tsconfig.server.json (330 bytes)
> CREATE apps/web/server.ts (2003 bytes)
> UPDATE package.json (5759 bytes)
> UPDATE angular.json (20794 bytes)
> UPDATE apps/web/src/main.ts (431 bytes)
> UPDATE apps/web/src/app/app.module.ts (786 bytes)
> ✔ Packages installed successfully.
> ```
> 
> Then, when running the server, I got this:
> 
> ```
> $ ng run web:server
> Cannot determine versions of "@angular/cli".
> ```
> 
> Which is fixed by running:
> 
> ```
> yarn add -D @angular/cli
> ```
> 
> After that, it works:
> 
> ```
> $ ng run web:server
> Hash: 071cc358edfc4d66a3cd
> Time: 10163ms
> Built at: 05/10/2020 6:20:14 PM
>       Asset      Size  Chunks                          Chunk Names
>     main.js  9.93 MiB    main  [emitted]        [big]  main
> main.js.map  10.5 MiB    main  [emitted] [dev]         main
> Entrypoint main [big] = main.js main.js.map
> chunk {main} main.js, main.js.map (main) 8.9 MiB [entry] [rendered]
> ```
> 
> _Until..._
> 
> ![image](https://user-images.githubusercontent.com/36491/81514503-167aa280-92f5-11ea-969d-154d3dbfd2d8.png)
> 
> Running this command failed:
> 
> ```
> $ nx g @nrwl/angular:lib dev --directory web --style scss
> Cannot read property 'schematics' of undefined
> ```
> 
> So removing the symlink:
> 
> ```
> $ rm angular.json
> ```
> 
> And that fixes it:
> 
> ```
> $ nx g @nrwl/angular:lib dev --directory web --style scss
> CREATE libs/web/dev/README.md (138 bytes)
> CREATE libs/web/dev/tsconfig.lib.json (411 bytes)
> CREATE libs/web/dev/tslint.json (260 bytes)
> CREATE libs/web/dev/src/index.ts (37 bytes)
> CREATE libs/web/dev/src/lib/web-dev.module.ts (160 bytes)
> CREATE libs/web/dev/src/lib/web-dev.module.spec.ts (343 bytes)
> CREATE libs/web/dev/tsconfig.json (126 bytes)
> CREATE libs/web/dev/jest.config.js (358 bytes)
> CREATE libs/web/dev/tsconfig.spec.json (236 bytes)
> CREATE libs/web/dev/src/test-setup.ts (29 bytes)
> UPDATE workspace.json (21852 bytes)
> UPDATE nx.json (1260 bytes)
> UPDATE tsconfig.json (1548 bytes)
> ```

Don't understand?!!
Does it mean that after removing the symlink the nx command isn't known anymore?

I tried to rename the file to angular.json and it doesn't work...
I don't think this discussion should be closed

**Comment by beeman** [comment]
> > For future reference, I had the same question as I was looking to use `ng add` in my workspace built with the `nx` cli.
> > When running the command I got this error:
> > ```
> > $ ng add @nguniversal/express-engine --clientProject web
> > The add command requires to be run in an Angular project, but a project definition could not be found.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Luckily, we don't have to change a whole lot to our project to fix this. Making a symlink makes it work:
> > ```
> > $ ln -s workspace.json angular.json
> > $ ng add @nguniversal/express-engine --clientProject web
> > Skipping installation: Package already installed
> > CREATE apps/web/src/main.server.ts (298 bytes)
> > CREATE apps/web/src/app/app.server.module.ts (318 bytes)
> > CREATE apps/web/tsconfig.server.json (330 bytes)
> > CREATE apps/web/server.ts (2003 bytes)
> > UPDATE package.json (5759 bytes)
> > UPDATE angular.json (20794 bytes)
> > UPDATE apps/web/src/main.ts (431 bytes)
> > UPDATE apps/web/src/app/app.module.ts (786 bytes)
> > ✔ Packages installed successfully.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then, when running the server, I got this:
> > ```
> > $ ng run web:server
> > Cannot determine versions of "@angular/cli".
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Which is fixed by running:
> > ```
> > yarn add -D @angular/cli
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After that, it works:
> > ```
> > $ ng run web:server
> > Hash: 071cc358edfc4d66a3cd
> > Time: 10163ms
> > Built at: 05/10/2020 6:20:14 PM
> >       Asset      Size  Chunks                          Chunk Names
> >     main.js  9.93 MiB    main  [emitted]        [big]  main
> > main.js.map  10.5 MiB    main  [emitted] [dev]         main
> > Entrypoint main [big] = main.js main.js.map
> > chunk {main} main.js, main.js.map (main) 8.9 MiB [entry] [rendered]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > _Until..._
> > ![image](https://user-images.githubusercontent.com/36491/81514503-167aa280-92f5-11ea-969d-154d3dbfd2d8.png)
> > Running this command failed:
> > ```
> > $ nx g @nrwl/angular:lib dev --directory web --style scss
> > Cannot read property 'schematics' of undefined
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So removing the symlink:
> > ```
> > $ rm angular.json
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And that fixes it:
> > ```
> > $ nx g @nrwl/angular:lib dev --directory web --style scss
> > CREATE libs/web/dev/README.md (138 bytes)
> > CREATE libs/web/dev/tsconfig.lib.json (411 bytes)
> > CREATE libs/web/dev/tslint.json (260 bytes)
> > CREATE libs/web/dev/src/index.ts (37 bytes)
> > CREATE libs/web/dev/src/lib/web-dev.module.ts (160 bytes)
> > CREATE libs/web/dev/src/lib/web-dev.module.spec.ts (343 bytes)
> > CREATE libs/web/dev/tsconfig.json (126 bytes)
> > CREATE libs/web/dev/jest.config.js (358 bytes)
> > CREATE libs/web/dev/tsconfig.spec.json (236 bytes)
> > CREATE libs/web/dev/src/test-setup.ts (29 bytes)
> > UPDATE workspace.json (21852 bytes)
> > UPDATE nx.json (1260 bytes)
> > UPDATE tsconfig.json (1548 bytes)
> > ```
> 
> Don't understand?!! Does it mean that after removing the symlink the nx command isn't known anymore?
> 
> I tried to rename the file to angular.json and it doesn't work... I don't think this discussion should be closed

The format of workspace.json completely changed so I don't think it works anymore.
