### ISSUE TITLE
_Core tutorial_ has no navigation entry

### ISSUE THREAD

**Issue by Clindbergh** [nrwl/nx#20636]
### Documentation issue

The Core Tutorial can be reached through the search, but no navigation entry seems to exist.

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [X] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[Core tutorial](https://nx.dev/core-tutorial#core-tutorial) (and subpages)

### Additional context or description

I thought about making a PR, but I am unsure how the documentation works, given that there is actually a menu entry in [docs/generated/manifests/menus.json](https://github.com/nrwl/nx/blob/master/docs/generated/manifests/menus.json) for this tutorial.

**Comment by isaacplmann** [comment]
The tutorial was removed
