### ISSUE TITLE
format:check does not correctly interpret .gitignore

### ISSUE THREAD

**Issue by Fuco1** [nrwl/nx#20632]
### Current Behavior

Files which are ignored by git are still processed by `nx format:check`.

The problem is that if the `.gitignore` contains a line `.expo`, this means any directory `.expo` nested anywhere in the tree should be ignored.  So:

```
/.expo
/apps/myapp/.expo
/tools/something/.expo
```

should all be excluded from the check.  If I want to ignore only top-level files, `.gitignore` allows this by adding a leading `/` that matches the "root" directory.

### Expected Behavior

All the files ignored by git are also ignored by nx.

### Steps to Reproduce

1.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : linux-x64
   pnpm   : 8.11.0

   nx (global)        : 17.1.3
   nx                 : 17.1.3
   @nx/js             : 17.1.3
   @nx/jest           : 17.1.3
   @nx/eslint         : 17.1.3
   @nx/workspace      : 17.1.3
   @nx/detox          : 17.1.3
   @nx/eslint-plugin  : 17.1.3
   @nx/expo           : 17.1.3
   typescript         : 5.2.2
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AZN1244** [comment]
:)

**Comment by MaxKless** [comment]
Hey! Thanks for the report @Fuco1 :) 
I just tried this locally and both a file at the root and a nested file were properly ignored by prettier. Can you try again and confirm that this still happens to you on the latest version of nx?

**Comment by MaxKless** [comment]
Glad to hear it, I'll close this for now :)
