### ISSUE TITLE
Next.js app  created without adding React dependency

### ISSUE THREAD

**Issue by stramel** [nrwl/nx#2064]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

I would expect all necessary dependencies to be installed through the generator

## Current Behavior

`react` and `react-dom` are both missing from the `package.json` and thus preventing the app from being served.

![image](https://user-images.githubusercontent.com/855184/68952667-dabbb180-0785-11ea-8181-249e73b81d4e.png)
![image](https://user-images.githubusercontent.com/855184/68952680-e14a2900-0785-11ea-883d-e9da5191c0d7.png)

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create an empty NX workspace `yarn create nx-workspace`
2. Install the Next.js generator `yarn add -D @nrwl/next`
3. Generate a Next.js app by running `nx g @nrwl/next:app test`
4. Attempt to serve the app `yarn start test`

### Additional Notes

I also ran `nx g @nrwl/react:lib foobar` and also did not get `react` or `react-dom` added to my `package.json`. However, running `nx g @nrwl/react:app foobar` does properly add the dependencies.

**Comment by vsavkin** [comment]
Could you try it with Nx 8.8.3? I just gave it a try, and it worked.

**Comment by stramel** [comment]
Seems to be working with the latest version.
