### ISSUE TITLE
[REQ] Display host with port using nx serve <app>

### ISSUE THREAD

**Issue by stramel** [nrwl/nx#2065]
It would be great to have a link to the host that the app is launched on. It was not intuitive to figure out what port my Next.js app was launched on without reading into the documentation. Next.js is normally 3000 and through NX it launches on 4200.

CRA does a nice job of this by both launching the tab and displaying a message like so:

![image](https://user-images.githubusercontent.com/855184/68955783-62a4ba00-078c-11ea-9661-b85fb385a30e.png)

**Comment by mbriggs** [comment]
Good idea :)

**Comment by stramel** [comment]
Seems to be showing `Ready on http://localhost:4200` for me now
