### ISSUE TITLE
404 for "Read more" link from Invite new member dialog

### ISSUE THREAD

**Issue by PowerSupply** [nrwl/nx#20667]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Clicking "Read more" link under "Require Social OAuth Sign-In" in the Invite new member dialog leads to 404.

### Additional context or description
<img width="539" alt="image" src="https://github.com/nrwl/nx/assets/622851/e338df80-244e-44e5-8c8a-f1d6cb68208f">

404 for link leading to: https://nx.dev/ci/account/users?utm_source=nx-cloud

**Comment by barbados-clemens** [comment]
Hi @PowerSupply, sorry about that. this is the page that's supposed to be redirected to.
https://nx.dev/ci/recipes/security/google-auth
but there is also a broken image link, this is the contents of that image
![image](https://github.com/nrwl/nx/assets/23272162/9a82cc91-0f77-41e5-9b20-0bf50dab6eae)

broke image link fix for Nx docs are here: https://github.com/nrwl/nx/issues/20667
and I've submitted a PR to fix the link on the nx cloud side.

thanks for reporting this to us!
