### ISSUE TITLE
17.2.0 @nx/webpack:webpack executor throws isolatedConfig on simple build with node target

### ISSUE THREAD

**Issue by botre** [nrwl/nx#20671]
### Current Behavior

Given the following simple build target:

```
    "build": {
      "executor": "@nx/webpack:webpack",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/apps/backend",
        "main": "apps/backend/src/main.ts",
        "tsConfig": "apps/backend/tsconfig.app.json",
        "target": "node",
        "compiler": "tsc"
      }
    },
```

I encountered the following error:

```
> nx run backend:build

{
  outputPath: 'dist/apps/backend',
  main: 'apps/backend/src/main.ts',
  tsConfig: 'apps/backend/tsconfig.app.json',
  target: 'node',
  compiler: 'tsc',
  deleteOutputPath: true,
  outputFileName: 'main.js',
  isolatedConfig: true,
  buildLibsFromSource: true,
  root: '/Users/bjorn/Development/lab-box/mobvious-platform',
  projectRoot: 'apps/backend',
  sourceRoot: 'apps/backend/src',
  webpackConfig: '',
  fileReplacements: [],
  optimization: { scripts: undefined, styles: undefined }
}

 >  NX   Using "isolatedConfig" without a "webpackConfig" is not supported.

   Pass --verbose to see the stacktrace.


 —————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for project backend (328ms)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

### Expected Behavior

It should not throw.

### Steps to Reproduce

Create simple target using webpack, targetting node.

Run the target.

```
    "build": {
      "executor": "@nx/webpack:webpack",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/apps/backend",
        "main": "apps/backend/src/main.ts",
        "tsConfig": "apps/backend/tsconfig.app.json",
        "target": "node",
        "compiler": "tsc"
      }
    },
```

### Nx Report

```shell
Node   : 18.18.0
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx                 : 17.2.0
   @nx/js             : 17.2.0
   @nx/jest           : 17.2.0
   @nx/linter         : 17.2.0
   @nx/eslint         : 17.2.0
   @nx/workspace      : 17.2.0
   @nx/cypress        : 17.2.0
   @nx/detox          : 17.2.0
   @nx/devkit         : 17.2.0
   @nx/eslint-plugin  : 17.2.0
   @nx/expo           : 17.2.0
   @nx/nest           : 17.2.0
   @nx/node           : 17.2.0
   @nx/react          : 17.2.0
   @nrwl/tao          : 17.2.0
   @nx/web            : 17.2.0
   @nx/webpack        : 17.2.0
   typescript         : 5.2.2
```

### Failure Logs

```shell
See above.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by TriPSs** [comment]
I think they forgot to add a migration somewhere, adding `"webpackConfig": "<directory of your project>/webpack.config.js"` with the following config fixes this:

```js
const { composePlugins, withNx } = require('@nx/webpack')

// Nx plugins for webpack.
module.exports = composePlugins(withNx(), (config) => {
  // Update the webpack config as needed here.
  // e.g. `config.plugins.push(new MyPlugin())`
  return config
})
```

**Comment by jaysoo** [comment]
There was a migration back in 15.6 for this. We'll add it again for 17.2.x just in case it wasn't done.

**Comment by redplane** [comment]
> I think they forgot to add a migration somewhere, adding `"webpackConfig": "<directory of your project>/webpack.config.js"` with the following config fixes this:
> 
> ```js
> const { composePlugins, withNx } = require('@nx/webpack')
> 
> // Nx plugins for webpack.
> module.exports = composePlugins(withNx(), (config) => {
>   // Update the webpack config as needed here.
>   // e.g. `config.plugins.push(new MyPlugin())`
>   return config
> })
> ```

You are right.
I had the same issue and my fix was:
- Go to the <project folder>
- Create a file named: `webpack.config.js`
- Open file `<project folder>/project.json`
- Add `"webpackConfig": "apps/apis/webpack.config.js"` into `targets.build`

More information can be seen at: https://nx.dev/recipes/webpack/webpack-config-setup

**Comment by 0xRapid** [comment]
Happened to me in Windows. I think the solution is not to have to create something, but to make a migration that solves it

**Comment by jaysoo** [comment]
The migration will basically create the file mentioned above. We removed support for webpack builds that don't specify a webpack config file.

**Comment by TriPSs** [comment]
@jaysoo there is still "partial" support as when you put it off it will still fallback, [even though that is broken](https://github.com/nrwl/nx/pull/20678#issuecomment-1848411971).

**Comment by jaysoo** [comment]
We're moving away from that, and it'll be gone by Nx 18 (around June 2024). But yes it is supposed to still work.

**Comment by jaysoo** [comment]
Released in 17.2.1

**Comment by MichaelKaaden** [comment]
In my case, the  "executor" was already "@nx/webpack:webpack". Since the migration expects it to be "@nrwl/webpack:webpack" instead, it didn't run.

**Comment by jacqueslareau** [comment]
Upgraded to nx@17.2.1 from nx@17.2.0 and no migration detected.

**Comment by jaysoo** [comment]
We're cutting a new patch with `@nx` scope as well. For migrations, you can manually pass `--from=nx@<ver>` if you don't see the migration. Perhaps due to the versions installed, Nx did not pick up new migrations.

**Comment by luisfelipediaz** [comment]
I tried with `--from=nx@<ver>` but it doesn't work, keeps throwing the error:

`Using "isolatedConfig" without a "webpackConfig" is not supported.`

**Comment by KeithGillette** [comment]
Neither `17.2.3` nor `17.2.4` picked up the migration, with or without `--from=nx@15.6` (which caused other problems), perhaps because our `project.json` had no `targets.build.isolatedConfig` property at all. Adding it and setting it to `false` per @TriPSs removed the `Using "isolatedConfig" without a "webpackConfig" is not supported.` error on serve but showed the deprecation warning, so I decided to move on and just manually added in the base `webpack.config.js` and pointed `targets.build.options.webpackConfig` to it, per [Configure webpack on your Nx workspace](https://nx.dev/recipes/webpack/webpack-config-setup#configure-webpack-on-your-nx-workspace), as suggested by @TriPSs and @redplane, which prevented the error and deprecation warning (but the latter only if the `isolatedConfig` property did not exist at all in `project.json`—the warning persists if `isolatedConfig: true`).

**Comment by Lorenz-A-Mueller** [comment]
Thanks so much for the helpful answers!
Just to clarify (because I just stumbled over that), both the `isoldatedConfig` and  `webpackConfig` properties go into `targets.build.options`

**Comment by TriPSs** [comment]
@Lorenz-A-Mueller yes.
