### ISSUE TITLE
Cannot find module 'nx/src/devkit-exports' while run npx nx g @nrwl/angular:component

### ISSUE THREAD

**Issue by karocksjoelee** [nrwl/nx#20679]
### Current Behavior

while running : 
`npx nx g @nrwl/angular:component tab-bar-header --dir=shared/components --project=web-app`

will return error of : 

 >  NX   Cannot find module 'nx/src/devkit-exports'

### Expected Behavior

Generated component to my directory

### Steps to Reproduce

1.npx nx g @nrwl/angular:component tab-bar-header --dir=shared/components --project=web-app

### Nx Report

```shell
nx : 14.5.4
   @nrwl/angular : 17.2.0
   @nrwl/cypress : 14.5.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.4
   @nrwl/eslint-plugin-nx : 14.5.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.4
   @nrwl/js : 14.5.4
   @nrwl/linter : 14.5.4
   @nrwl/nest : 14.5.4
   @nrwl/next : Not Found
   @nrwl/node : 14.5.4
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 17.2.0
   @nrwl/workspace : 14.5.4
   typescript : 5.2.2
   ---------------------------------------
   Community plugins:
         @ionic/angular: 7.5.8
         ng-zorro-antd: 14.0.0
```

### Failure Logs

```shell
Require stack:
   - /Users/joeleem1max/Works/nx-posup/node_modules/@nx/devkit/index.js
   - /Users/joeleem1max/Works/nx-posup/node_modules/@nx/angular/src/generators/component/component.js
   - /Users/joeleem1max/Works/nx-posup/node_modules/nx/src/config/workspaces.js
   - /Users/joeleem1max/Works/nx-posup/node_modules/nx/src/command-line/generate.js
   - /Users/joeleem1max/Works/nx-posup/node_modules/nx/src/command-line/nx-commands.js
   - /Users/joeleem1max/Works/nx-posup/node_modules/nx/bin/init-local.js
   - /Users/joeleem1max/Works/nx-posup/node_modules/nx/bin/nx.js
   Pass --verbose to see the stacktrace.
```
```


### Package Manager Version

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Most of the packages in your report are using 14.5.4, except for `@nrwl/angular` and `@nrwl/web` which are on 17.2.0. That's not correct. You must have all the Nx packages aligned on the version.

I'm unsure how you ended up with those versions. You might have manually updated those two packages to the latest version. Please set their versions to 14.5.4 to match the rest of the packages. If you need/want to update your versions, make sure to use the `nx migrate` command and migrate one major version at a time until you get to the desired version.

**Comment by mrahulreddy** [comment]
Hello Nx team, @leosvelperez 

![nx-devkit-windows-error](https://github.com/nrwl/nx/assets/14847799/1cb75810-0af8-4db2-8c14-12729c1162a5)

I'm facing above problem on my Windows computer where I see an error message that says, 
`Cannot find module 'nx/src/devkit-exports.` 

The people using Mac computers, with the same Node version 16.20.2 as mine, don't have this issue. 
I tried fixing it by deleting the 'node_modules' folder, 'package-lock' file, and reinstalling using the "npm i" command, but I'm still getting the same error.

**Comment by leosvelperez** [comment]
@mrahulreddy which version of Nx do you have installed globally? If it's older than 14.9.0 and older than your workspace's Nx version, please update your global installation to a recent version.

**Comment by mrahulreddy** [comment]
After running `nx migrate latest`, the Nx version is now `"nx": "17.2.8"`. I executed the migrations using `nx migrate --run-migrations` but encountered the same error when running `npm run storybook`. @leosvelperez
