### ISSUE TITLE
After migration from nx 16 to nx 17 the goal "npx nx run-many --target=lint --all" fails because of Configuration for rule "@nx/enforce-module-boundaries" is invalid:

### ISSUE THREAD

**Issue by heike2718** [nrwl/nx#20676]
### Current Behavior

Today I migrated my nx workspace including angular to the new major version, i.e. from 16 to 17. The migration run successfully. The application can be built an is running without unexpected errors. Thanks for the nice migration tooling!

Nevertheless, the linting fails:

With version 16 

```
npx nx run-many --target=lint --all
```

run without any error.

With version 17 all of the libs and the app fail the linting.

Error Message:

```
Configuration for rule "@nx/enforce-module-boundaries" is invalid:
          x run Value {"sourceTag":"type:api","onlyDependOnLibWithTags":["type:model","type:data"]} should NOT have additional properties.
          	Value {"sourceTag":"type:api","onlyDependOnLibWithTags":["type:model","type:data"]} should NOT have additional properties.
          7/27 fValue {"sourceTag":"type:api","onlyDependOnLibWithTags":["type:model","type:data"]} should match exactly one schema in oneOf.
```

The .eslintrc.json was not effected by migration. 

Migration added the aditional dev-dependency "@nx/eslint": "17.2.0" to package.json

Since the error message complains about the configuration for rule "@nx/enforce-module-boundaries" I think, there are changes in the nx/eslint package that are not matched by the migration. 

I would appreciate to get an example of a .eslintrc.json file that passes the linting.

My .eslintrc.json that passed the config check with nx 16 is attached.
[.eslintrc.json](https://github.com/nrwl/nx/files/13623254/eslintrc.json)

It looks as if there are breaking changes effecting the lint-configuration that are not documented

### Expected Behavior

Need an .eslintrc.json that passes the configuration check.

### GitHub Repo

https://github.com/heike2718/mathe-jung-alt

### Steps to Reproduce

Hints: I left 2 branches in order to reproduce the braking behaviour of eslint:

1. checkout branch https://github.com/heike2718/mathe-jung-alt/tree/angular-16-version-of-frontend
2.  cd to frontend/mja-ws
3. run npm install
4. run npx nx run-many --target=lint --all

There should not be any linting errors

5. checkout branch https://github.com/heike2718/mathe-jung-alt/tree/bump-to-angular-17
6. cd to frontend/mja-ws
7. lint fails completely with an error message about the configuration of the rule.

### Nx Report

```shell
Node   : 18.14.0
   OS     : linux-x64
   npm    : 9.3.1
   
   nx                 : 17.2.0
   @nx/js             : 17.2.0
   @nx/jest           : 17.2.0
   @nx/linter         : 17.2.0
   @nx/eslint         : 17.2.0
   @nx/workspace      : 17.2.0
   @nx/angular        : 17.2.0
   @nx/cypress        : 17.2.0
   @nx/devkit         : 17.2.0
   @nx/eslint-plugin  : 17.2.0
   @nrwl/tao          : 17.2.0
   @nx/web            : 17.2.0
   @nx/webpack        : 17.2.0
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @ngrx/effects        : 17.0.1
   @ngrx/eslint-plugin  : 17.0.1
   @ngrx/router-store   : 17.0.1
   @ngrx/store          : 17.0.1
   @ngrx/store-devtools : 17.0.1
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by heike2718** [comment]
Sorry: in the Steps to reproduce I forgot these steps after checking out the branch https://github.com/heike2718/mathe-jung-alt/tree/bump-to-angular-17

6.1. rm -rf node_modules
6.2. npm install

Yes: I did cleanup and install the version 16 depencencies completely after switching to the other branch. I only forgot to document these steps here.

**Comment by meeroslav** [comment]
In v 17 we introduced a more stricter check for rule’s schema. It could happen that your existing config was not valid. I’ll check as soon as possible.

**Comment by meeroslav** [comment]
Your configuration is in fact invalid. The old version was tolerating that, but v17 is strict about it. 

You have a several property name mismatches e.g. using `onlyDependsOnLibsWithTags` or `onlyDependOnLibWithTags` instead of `onlyDependOnLibsWithTags`.  Or the provided value is not array but a string.

Your rule wasn't working as expected, though, since those properties would not match expected names.

Once you fix those issues you will actually get a bunch of valid issues like 
![Screenshot 2023-12-11 at 18 02 30](https://github.com/nrwl/nx/assets/881612/640029c7-b9d1-49ea-a6b3-9f7a5faf3804)

Also, the recommended `@typescript-eslint` rule set, which got bumped, is a bit more strict, so expect several of the errors from there (which you can disable if you so wish).

![Screenshot 2023-12-11 at 18 03 49](https://github.com/nrwl/nx/assets/881612/5f16198e-2983-4a71-a9f4-ab40cbd0f6d2)

**Comment by meeroslav** [comment]
Just to clarify it's:

`only Depend (singular) On Libs (plural) With Tags (plural)`

**Comment by heike2718** [comment]
Thank you very much. That was very helpful.
