### ISSUE TITLE
@angular/pwa upgrade is missing in v17

### ISSUE THREAD

**Issue by cre8** [nrwl/nx#20686]
### Current Behavior

#18736 added the pwa library to the migration files for at least v16. But after upgrading to v17, the pwa is still at v16

### Expected Behavior

That the pwa library will be updated too as other angular libs like material

### Steps to Reproduce

- Create a angular application with the PWA dependency on version 16
- Migrate to 17

### Nx Report

```shell
Node   : 18.17.0
   OS     : win32-x64
   npm    : 9.6.7

   nx                 : 17.2.0
   @nx/js             : 17.2.0
   @nx/jest           : 17.2.0
   @nx/linter         : 17.2.0
   @nx/eslint         : 17.2.0
   @nx/workspace      : 17.2.0
   @nx/angular        : 17.2.0
   @nx/cypress        : 17.2.0
   @nx/detox          : 17.2.0
   @nx/devkit         : 17.2.0
   @nx/esbuild        : 17.2.0
   @nx/eslint-plugin  : 17.2.0
   @nx/react          : 17.2.0
   @nrwl/tao          : 17.2.0
   @nx/web            : 17.2.0
   @nx/webpack        : 17.2.0
   typescript         : 5.2.2
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
@cre8 thanks for bringing this to our attention. I created a PR that will fix it for anyone doing the migration again, and it's also ensuring future migrations will contain it (I updated a helper script we use to help us scaffold the migrations).

If you already updated, please bump the `@angular/pwa` package version.
