### ISSUE TITLE
Support TypeScript declarations with @nx/esbuild:esbuild

### ISSUE THREAD

**Issue by castleadmin** [nrwl/nx#20688]
- [X ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
esbuild doesn't support the creation of declaration files (*.d.ts) and probably never will (see https://github.com/evanw/esbuild/issues/95).
Since declaration files are essential for published libraries,
it would be great if `@nx/esbuild:esbuild` would provide an option to output them.

## Motivation
Declaration files (*.d.ts) are essential for published libraries.

## Suggested Implementation
The commonly accepted workaround is to run a tsc build before the esbuild build that only outputs the declaration files.
This additional build step could be provided as a `@nx/esbuild:esbuild` option.

## Alternate Implementations
Implement the additional build step in the `@nx/js:library` generator for publishable libraries.

**Comment by jaysoo** [comment]
@castleadmin Hey, thanks for expressing interest on this, do you have any suggestions on how you'd want to do this?

**Comment by castleadmin** [comment]
Hi @jaysoo, for the suggested case I would do the following

- Introduce a new boolean valued `--declaration` option
- If `--declaration`  or the tsconfig option [declaration](https://www.typescriptlang.org/tsconfig#declaration) is true,
  then the TypeScript compiler will be used before the esbuild build call to generate the declarations
- The TypeScript compiler could be called via the command line or the @nx/js:tsc executor
- The same `tsconfig` options should be used for the esbuild and declarations build with one exception
  - The declaration build will always set the [emitDeclarationOnly](https://www.typescriptlang.org/tsconfig#emitDeclarationOnly) tsconfig option

**Comment by castleadmin** [comment]
@jaysoo What do you think about the new feature? Should I start implementing a concrete solution?

**Comment by GideonMax** [comment]
Hello, what are the plans on implementing this, and are there any workarounds I can do to achieve this behavior?

**Comment by GideonMax** [comment]
When can we expect this feature?

**Comment by castleadmin** [comment]
I should be able to implement the feature within the next 2 weeks.

**Comment by ChristopherPHolder** [comment]
What is missing to complete this feature? It seems the MR is open and ready for review. 

I am happy to contribute if there is anything needed to complete the feature 👍

**Comment by ThePlenkov** [comment]
Here is the way I have fixed it:
```

    "dts": {
      "executor": "@nx/js:tsc",
      "outputs": [
        "{options.outputPath}"
      ],
      "options": {
        "outputPath": "dist/packages/prosemirror-markdown-es",
        "main": "packages/prosemirror-markdown-es/src/index.ts",
        "tsConfig": "packages/prosemirror-markdown-es/tsconfig.dts.json",
        "clean": true
      }
    },
    "build": {
      "executor": "@nx/esbuild:esbuild",
      "outputs": [
        "{options.outputPath}"
      ],
      "options": {
        "outputPath": "dist/packages/prosemirror-markdown-es",
        "main": "packages/prosemirror-markdown-es/src/index.ts",
        "tsConfig": "packages/prosemirror-markdown-es/tsconfig.lib.json",
        "assets": [
          "packages/prosemirror-markdown-es/*.md",
        ],
        "generatePackageJson": true,
        "format": [
          "cjs"
        ],
        "deleteOutputPath": false
      },
      "dependsOn": [
        "dts"
      ]
    },
```

so I create first dts with clean:true and then build esbuild with  "deleteOutputPath": false. I know it's ugly but it works =)

**Comment by danielsharvey** [comment]
This has been done in #21084. I have experienced and issue with referencing buildable libraries - see https://github.com/nrwl/nx/issues/26376.

**Comment by MaxKless** [comment]
Hello! Looks like this has been resolved in https://github.com/nrwl/nx/pull/21084 so I will close this issue. 
Please create new issues or comment on the one linked above if you're running into problems with this feature.
