### ISSUE TITLE
Migrating to 17.2.0 prevents remotes starting on separate ports

### ISSUE THREAD

**Issue by ahernd2** [nrwl/nx#20687]
### Current Behavior

After migrating to version 17.0.2 we noticed that our shell application no longer starts remotes on separate ports. Instead all remotes seem to be served on the same port with different paths needed, is this intentional?

```typescript
module.exports = {
  name: 'thunder',
  remotes: ['landing', 'overview'] // <- Both start on port 4201
};
```

### Expected Behavior

Remotes usually started on separate ports making it easy to map them in our proxy.conf.js file for angular.

For example in this configuration, the overview remote usually starts on port 4217 because that is what its serve-static configuration is set to

```json
 "serve-static": {
      "executor": "@nx/web:file-server",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "overview:build",
        "port": 4217,
        "proxyUrl": "http://localhost:4217?"
      },
      "configurations": {
        "development": {
          "buildTarget": "overview:build:development"
        },
        "production": {
          "buildTarget": "overview:build:production"
        }
      }
    },
```

### Steps to Reproduce

1.

### Nx Report

```shell
Node   : 18.18.0
   OS     : linux-x64
   pnpm   : 7.33.4
   
   nx                 : 17.2.0
   @nx/js             : 17.2.0
   @nx/jest           : 17.2.0
   @nx/linter         : 17.2.0
   @nx/eslint         : 17.2.0
   @nx/workspace      : 17.2.0
   @nx/angular        : 17.2.0
   @nx/cypress        : 17.2.0
   @nx/devkit         : 17.2.0
   @nx/esbuild        : 17.2.0
   @nx/eslint-plugin  : 17.2.0
   @nx/express        : 17.2.0
   @nx/node           : 17.2.0
   @nx/playwright     : 17.2.0
   @nx/plugin         : 17.2.0
   @nx/storybook      : 17.2.0
   @nrwl/tao          : 17.2.0
   @nx/web            : 17.2.0
   @nx/webpack        : 17.2.0
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @ngneat/transloco    : 4.3.0
   @ngrx/effects        : 17.0.1
   @ngrx/router-store   : 17.0.1
   @ngrx/store          : 17.0.1
   @ngrx/store-devtools : 17.0.1
   @storybook/angular   : 7.5.3
   ngx-build-plus       : 13.0.1
   ngx-toastr           : 16.2.0
   ---------------------------------------
   Local workspace plugins:
         workspace-plugin
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ahernd2** [comment]
Im guessing this related to this change https://github.com/nrwl/nx/pull/20006. So I guess thats just how it works now?

**Comment by Coly010** [comment]
You’re correct, this was an intentional change. 

You can always use `—skipRemotes=“*”` to opt out of having the host spin up a single file server for all the remotes and manually serve them statically so they are on the port you expect.

we may look into some kind of “forced port” behaviour where you can attempt to specify which port to serve the single file server on, to allow for hard coded values like your proxy to find it.

**Comment by rbirkgit** [comment]
We have an issue with this change. We can change our proxy file to use the same port for all remotes, but then we cannot start any of our remotes in dev mode which uses specific ports.

How can you get the proxy working with both static and devmode remotes? are we expected to have to manually edit the proxy file every time we start our host depending on if we start a remote in static or dev mode?

**Comment by rbirkgit** [comment]
Created new bug about this as this one is closed: https://github.com/nrwl/nx/issues/20974
