### ISSUE TITLE
Running a freshly created React Native app using XCode fails (but works fine using npx nx run-ios mobile)

### ISSUE THREAD

**Issue by quickseries** [nrwl/nx#20680]
### Current Behavior

# Issue 1

When you create a new react native app using the instructions here: https://nx.dev/recipes/react/react-native fails to build using XCode, spitting out this error:

```bash
Node found at: /Users/XXXXX/.nvm/versions/node/v18.17.0/bin/node
error No Metro config found in /Users/XXXXXX/dev/spacemates.
```

Note that it works perfectly fine when running `npx nx run-ios mobile`.

# Issue 2

Moving the `metro.config.js` file from `/apps/XXXX` to the root of the project allows XCode to run the project perfectly, but then the app has a compilation error in metro:

```bash
[Nx] Failed to locate tsconfig}
Error: Cannot resolve ./src/main
    at /Users/XXXXXXX/dev/spacemates/node_modules/@nx/react-native/plugins/metro-resolver.js:30:15
    at Object.resolve (/Users/XXXXXXX/dev/spacemates/node_modules/metro-resolver/src/resolve.js:47:12)
    at ModuleResolver.resolveDependency (/Users/XXXXXXX/dev/spacemates/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:79:31)
    at DependencyGraph.resolveDependency (/Users/XXXXXXX/dev/spacemates/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
    at /Users/XXXXXXX/dev/spacemates/node_modules/metro/src/lib/transformHelpers.js:169:21
    at Server._resolveRelativePath (/Users/XXXXXXX/dev/spacemates/node_modules/metro/src/Server.js:1045:12)
    at async Server.requestProcessor [as _processBundleRequest] (/Users/XXXXXXX/dev/spacemates/node_modules/metro/src/Server.js:449:37)
    at async Server._processRequest (/Users/XXXXXXX/dev/spacemates/node_modules/metro/src/Server.js:383:7)
```

### Expected Behavior

A freshly created react native should run in XCode without any issues.

### Steps to Reproduce

# Issue 1

1. Run `npx create-nx-workspace happynrwl --preset=react-native --appName=mobile`
2. Run `cd mobile`
3. Run `npx nx run-ios mobile`
4. Kill the running process after it has successfully loaded the app in the simulator
5. Launch `mobile.xcworkspace` in XCode
6. Click the play button in the nav bar (start the active scheme)
7. It will fail as it cannot find the metro.config.js file.

# Issue 2

1. After running the above steps
2. Move `app/XXXX/metrol.config.js` to the root of the project
3. Click the play button in the nav bar (start the active scheme) in XCode
4. The app builds successfully
5. Notice that the javascript cannot compile as it is looking for main

### Nx Report

```shell
Node   : 18.17.0
   OS     : darwin-arm64
   npm    : 9.8.1
   
   nx (global)        : 17.1.3
   nx                 : 17.2.0
   @nx/js             : 17.2.0
   @nx/jest           : 17.2.0
   @nx/linter         : 17.2.0
   @nx/eslint         : 17.2.0
   @nx/workspace      : 17.2.0
   @nx/detox          : 17.2.0
   @nx/devkit         : 17.2.0
   @nx/eslint-plugin  : 17.2.0
   @nx/react          : 17.2.0
   @nx/react-native   : 17.2.0
   @nrwl/tao          : 17.2.0
   @nx/web            : 17.2.0
   typescript         : 5.2.2
```

### Package Manager Version

npm    : 9.8.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
i think you have to just run `nx start mobile` in a separate terminal.

this happens because in the repo, there are 2 node_modules folder:
- 1 at workspace root
- 1 at project root

when the terminal running launchCommand, it runs form workspace root rather than project root.
