### ISSUE TITLE
`nx print-affected --select projects` return all projects when deleting a project

### ISSUE THREAD

**Issue by orlevii** [nrwl/nx#20691]
### Current Behavior

When running `nx print-affected --select projects` (or `nx show projects --affected`)
the output returns **all** the projects in the repository when deleting a project.

I tried to ask as a discussions, but no replies.
https://github.com/nrwl/nx/discussions/20548

(Tested on Linux and MacOS)

### Expected Behavior

No project should be returned.

### GitHub Repo

https://github.com/orlevii/nx-examples

### Steps to Reproduce

I forked the `nx-examples` repository and deleted a project from the `apps` directory.

1. Clone & install dependencies (https://github.com/orlevii/nx-examples)
2. `git checkout delete_app`
3. Run `npx nx print-affected --select projects`
4. See that it outputs all the projects in the repository

You can see the changes of this branch here:
https://github.com/nrwl/nx-examples/compare/master...orlevii:nx-examples:delete_app

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.9.0
   OS     : linux-x64
   yarn   : 1.22.19
   
   nx                 : 17.2.0-beta.15
   @nx/js             : 17.2.0-beta.15
   @nx/jest           : 17.2.0-beta.15
   @nx/linter         : 17.2.0-beta.15
   @nx/eslint         : 17.2.0-beta.15
   @nx/workspace      : 17.2.0-beta.15
   @nx/angular        : 17.2.0-beta.15
   @nx/cypress        : 17.2.0-beta.15
   @nx/devkit         : 17.2.0-beta.15
   @nx/eslint-plugin  : 17.2.0-beta.15
   @nx/react          : 17.2.0-beta.15
   @nrwl/tao          : 17.2.0-beta.15
   @nx/web            : 17.2.0-beta.15
   @nx/webpack        : 17.2.0-beta.15
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 17.0.1
   @ngrx/effects         : 17.0.1
   @ngrx/entity          : 17.0.1
   @ngrx/router-store    : 17.0.1
   @ngrx/store           : 17.0.1
   @ngrx/store-devtools  : 17.0.1
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This issue has huge impact on CI time when deprecating projects, it basically requires to build & test the entire monorepo every time there's a change like that.

**Comment by AgentEnder** [comment]
Hey 👋 - when deleting projects Nx has no way of knowing what projects depended on it prior to the deletion. To do this, Nx would need to persist changes to the graph over time, and the size of that data would get out of hand quickly.

If we were to remove this logic, it would be possible that projects which should be affected were missed and that's much more dangerous than having the longer CI times. 

I'm going to go ahead and close this out. Let me know if you have further questions.
