### ISSUE TITLE
Feature: Generate forms

### ISSUE THREAD

**Issue by tiaguinho** [nrwl/nx#207]
I was thinking if it's possible to use schematics to generate forms.
The idea is to type something like ```ng generate form app --module=apps/<appname>/src/app/app.module.ts --schema=category.json --reactive```

Inside the category.json we can describe the interface like this:

```json
{
    "id": "string",
    "name": "string",
    "slug": "string"
}
```

NX will generate a component with boilerplate form based on the describe inside the .json file.

**Comment by matthewharwood** [comment]
I think a future iteration of semantics will allow you  to write your own.  In the meantime,
You should look at formly https://alligator.io/angular/formly/

**Comment by vsavkin** [comment]
I thought about it quite a bit and came to a conclusion that it is hard to provide a generic schematic for forms because they tend to be app-specific. You can, however, create your own schematic generating forms. Formly is a good option as well.

Closing this issue.
