### ISSUE TITLE
Base html tag cannot be disabled

### ISSUE THREAD

**Issue by xYouLL** [nrwl/nx#20700]
### Current Behavior

Every time an app gets built a <base /> html tag is appended in the head tag (`<base href="/" />`). This behavior cannot be prevented. As of #5079, even trying to pass `{ "type": ["string", "null"] }` to the baseHref parameter it doesn't work.
This is how I configured my `project.json` file:
```
"options": {
   "outputPath": "dist/apps/inventory",
   "baseHref": { "type": ["string", "null"] }
},
```

### Expected Behavior

<base /> tag should be removed passing a null to the json schema.

### Steps to Reproduce

1. Create an application (react in my case).
2. Specify the `baseHref` parameter on the build target to be either `null` or `{ "type": ["string", "null"] }`
3. Build the application.

### Nx Report

```shell
Node   : 20.3.0
   OS     : win32-x64
   npm    : 9.6.6

   nx                 : 17.2.0
   @nx/js             : 17.2.0
   @nx/linter         : 17.2.0
   @nx/eslint         : 17.2.0
   @nx/workspace      : 17.2.0
   @nx/devkit         : 17.2.0
   @nx/eslint-plugin  : 17.2.0
   @nx/react          : 17.2.0
   @nrwl/tao          : 17.2.0
   @nx/vite           : 17.2.0
   @nx/web            : 17.2.0
   typescript         : 5.2.2
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
You can delete the `baseHref` entry from your options. You also need to remove the `<base>` element from your source `index.html` file.

**Comment by xYouLL** [comment]
> You can delete the `baseHref` entry from your options. You also need to remove the `<base>` element from your source `index.html` file.

Isn't there a way to prevent the bundler to append the `<base>` element? I don't want to remove it manually for each index.html I generate.
Also, reading from the source code, I noticed that for vite only the `base` parameter works. There's no way to modify the baseHref.

**Comment by jaysoo** [comment]
If we remove the `<base>` tag when `baseHref` is undefined it will be a behavior change. We can probably update the generated `index.html` to exclude this tag since it'll be set by `baseHref` anyway,

**Comment by xYouLL** [comment]
> We can probably update the generated `index.html` to exclude this tag since it'll be set by `baseHref` anyway,

It would be useful in my opinion. Having the freedom to choose whether to have the base tag or not it is useful in some cases.

**Comment by xYouLL** [comment]
Wouldn't be enough to add an ejs conditional check to the index template? I wanted to create a pull request for it but I'm having problems while setting up the environment.

**Comment by jaysoo** [comment]
We can remove it without an option. If baseHref is not set, or set to `/`, the `<base>` tag isn't necessary. If it's set to something else, then the Nx webpack plugin will it to the generated `index.html`. In either case, it doesn't need to be in the source `index.html` file.
