### ISSUE TITLE
Using react with nrwl nx, confirmation of library use (smart vs dumb)?

### ISSUE THREAD

**Issue by iangregsondev** [nrwl/nx#2071]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

I would like some confirmation of what we should be using libraries for when using react with nrwl. Libraries are usually used for features - which we could assume is a page - right ?

So all pages are added to libraries as features ?

So these would be smart components.

THe problem I am having now is that the UI Library (mentioned in the book) is supposed to be used for DUMB components that store no state and only pass in props.

What happens if I need to have a smart component that is shared amongst the application ?

So putting this in UI library - seems kind of wrong, according to the nrwl book.

Under features, also feels kine of wrong because features === pages.

Am I missing something ? 

So where do smart components go if they are not features ?

Or should the libs/features be split furhter into 

libs/features/pages
libs/features/components

I did check example repos that i could find but none of them when into great detail.

Would love some feedback

Thanks

**Comment by iangregsondev** [comment]
The other thing that could be possible is to split the feature up like so

(this first example, have a user FEATURE, which can hold more than 1 page and more than 1 smart component)

```
/libs
   /user
      /pages
          /user-registration
          /user-management
      /components
         /register-profile
        /magement-list
```

or

(this second example, have a user-registration FEATURE, which can hold ONLY 1 page and more than 1 smart component)

```
/libs
   /user-registration
      /page
          /regsitration
      /components
         /register-profile
        /register-list
```

I am still finding it quite difficult to understand the best way of doing this..

Having read the monorepo book by nrwl, which is really angular specific and also now the nrwl react book but it stops short of giving guidance on the above

Anybody else using react ?

**Comment by iangregsondev** [comment]
OK I have come up with the following..

```
  /libs/frontend/feature/accounts # feature "accounts" for frontend
    /src
        /lib
           /components
             /account-picker # Contains all files css (if used) and tsx file
            / account-table # Contains all files css (if used) and tsx file
           ....... etc (could be quite a file) - only specific to accounts
         /pages
              /account-list .  # Empty shell contains components from above (and shared places)
             /account-detail  # Empty shell contains components from above (and shared places) 
   /libs/frontend/[some-other-feature]
    .... continues

  /libs/frontend/ui
    /src
      /lib
       /components
         /button
         /spinner

  /libs/api/accounts # where the "api" endpoints for account are etc
   .... continues

```

would love some feedback...

To summarise, the frontend feature as created by NX, each feature can contain multiple components separated by a component directory, each component in this directory has its "own" directory.

features i prefixed with the app name i.e. frontend or api 

The frontend feature also contains (at the same level as components), a pages (this could be called views ) directory which is basically just a shell that assembles all "specific" components that it needs from the components in the same feature and also any "presentational" ONLY components that can be found under the UI directory 

The only thing I am not sure about (currently anyway :-) ) - the components directory under the feature/accounts would have both SMART components and some PRESENTATIONAL components - these are being shared inside the same directory.

**Comment by jaysoo** [comment]
@iangregsondev Hey, sorry I didn't see this issue until now.

In general I think you can group your features and ui libraries under the same domain.

For example:

```
libs/
  accounts/
    api/                                # API code for accounts domain
    feature/                         # "Smart" components for accounts
    ui/                                  # Presentational components for accounts
  shared/
    ui/                                  # Presentational components used by other libs/apps
```

Or you if you like to separate backend vs frontend:

```
libs/
  backend/
    accounts/
  frontend/
    accounts/
      feature/
      ui/
    shared/
      ui/
```

Again, sorry for the delayed reply. Hope this helps!
