### ISSUE TITLE
Cannot set Absolute paths or Aliases in a react library. 

### ISSUE THREAD

**Issue by maximus-lynn** [nrwl/nx#20711]
### Current Behavior

I've got two applications which are going to share one react library code. I've copied over my project to this library that uses absolute paths. 

I am told that the paths are not found in my IDE. 

I've now changed the tsconfig file inside the library to the below:

```
    "baseUrl": ".",
    "paths": {
      "core/*": ["src/lib/core/*"]
    },
    // OR
    "baseUrl": "src/lib/*",
```

Both of these do not work. I get the same error:
```
Cannot find module 'core/authentication/hooks/use-auth' or its corresponding type declarations.
```

### Expected Behavior

Expected behavior would be to have absolute paths in the library project so I do not need to go through my whole project to convert over to relative paths. 

### Steps to Reproduce

1.

### Nx Report

```shell
Run nx generate @nx/angular:library mylibrary

Try to create a aliase or absolute paths.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
Hi @maximus-lynn,

Are you using `compilerOptions.paths` in your library's tsconfig file? Because Nx uses the `tsconfig.base.json` or `tsconfig.json` at the root of your workspace to alias workspace libs already, it is not possible to set aliases for individual projects.

**Comment by ajitzero** [comment]
I'm facing the same issue, using Nx v14 (Angular v14). I'll try to reproduce this in a fresh project with v17 later tonight, because I am sure this used to work in the angular-nest preset earlier (6-8 months ago).
