### ISSUE TITLE
Support Vitest v1

### ISSUE THREAD

**Issue by birkskyum** [nrwl/nx#20722]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

The nx/vite package has a peer dependency on [Vitest < 1](https://github.com/nrwl/nx/blob/332b0120df97fc05e52e4156b01df0208fbb925e/packages/vite/package.json#L41) . It would be great to use the stable release instead.

## Motivation

Vitest v1 does come with a range of improvements. https://github.com/vitest-dev/vitest/releases/tag/v1.0.0

**Comment by mandarini** [comment]
We'll be working on it soon

**Comment by ComradeCow** [comment]
> We'll be working on it soon

Will this be coming as a part of 17.2? The `@nx/vite@17.2` versions currently have invalid peer dependencies. `vitest@0.34` requires `vite@4`, but `@nx/vite` requires `vite@5`. We get nastygrams from npm when installing.  We could use `--legacy-peer-deps` to bypass, but the errors have hosed up some of our upgrade scripts / processes.

**Comment by mandarini** [comment]
It is not part of 17.2 too. I can try and make a push for it to go into a version next week maybe.
