### ISSUE TITLE
Nx MUST outline breaking changes in release notes

### ISSUE THREAD

**Issue by deser** [nrwl/nx#20729]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?
Release page doesn't describe breaking changes: https://github.com/nrwl/nx/releases 

### Additional context or description
In the newest shiny 17.2.0 release there were breaking changes (at least for webpack executor):
https://github.com/nrwl/nx/compare/17.1.3...17.2.0#diff-8f9d5a32deaa7e0d6d4a8f5acfb7e61be0b20de8a85e74b3e2aec10043a34addL311

Changing these defaults broke my app.

### Expected behavior
Nx should add detailed descriptions on any breaking change within release.

**Comment by jaysoo** [comment]
There are some regression that are being patched for Webpack. There aren't breaking changes in 17.2.0, do you have other issues you ran into?

**Comment by deser** [comment]
I disagree. Any removal of default value for webpack executor is a breaking change, because you don't know, maybe people are building their specific business logic in very uncommon ways.

**Comment by barrymichaeldoyle** [comment]
Yeah unfortunately updating to 17.2.0 broke my builds in my module federated react apps. I've been disciplined in incrementally updating every minor version change to avoid being blindsided by breaking changes but that didn't prevent this.

**Comment by jaysoo** [comment]
The `isolatedConfig` default is the changed behavior, if there are other problems they are likely bugs that should be patched.

**Comment by AgentEnder** [comment]
I'm going to close this issue out. We do our best to highlight breaking changes, but sometimes regressions slip through. Please stick to 1 problem per github issue so that they can be effectively tracked and managed.

As @jaysoo mentioned there were some regressions in 17.2.0, we are actively working on tracking them down.
