### ISSUE TITLE
Going from 16 to 17 totally wrecked `generate lib`

### ISSUE THREAD

**Issue by prewk** [nrwl/nx#20724]
### Current Behavior

Up until `16.7.4`, using `nx g lib foo/bar` created a lib in `libs/foo/bar` with the name `foo-bar`, and the TS alias `@myPrefix/foo/bar`.

On `17.1.2` (and above), using `nx g lib foo/bar` starts a guide that asks me which library generator I want to use. That's okay, I can be more specific.

`nx g @nx/angular:library foo/bar` starts a guide that asks me how I want to create the project name. That's okay, I can default `projectNameAndRootFormat` to `derived` in `nx.json`.

After that, it creates

* A lib in `libs/foo/bar` - correct
* Wrong selector prefixes (Okay, I can set this also in `nx.json`)
* The `tsconfig.base.json`'s alias becomes `foo/bar`?! (I can't set this in `nx.json` because it'll make the alias the same for all generated libs)

I've been searching around and I can't find where/why this change happened? How can I remedy it?

### Expected Behavior

I expect it to either work like before or give me configurable options to automatically set the TS alias correct.

### Steps to Reproduce

`nx g lib` (See "Current behavior")

### Nx Report

```shell
Node   : 18.17.1
   OS     : darwin-arm64
   yarn   : 1.22.19

   nx                 : 17.1.2
   @nx/js             : 17.1.2
   @nx/jest           : 17.1.2
   @nx/linter         : 17.1.2
   @nx/eslint         : 17.1.2
   @nx/workspace      : 17.1.2
   @nx/angular        : 17.1.2
   @nx/cypress        : 17.1.2
   @nx/devkit         : 17.1.2
   @nx/eslint-plugin  : 17.1.2
   @nx/plugin         : 17.1.2
   @nx/storybook      : 17.1.2
   @nrwl/tao          : 17.1.2
   @nx/web            : 17.1.2
   @nx/webpack        : 17.1.2
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @ngneat/spectator        : 14.0.0
   @ngrx/component          : 16.2.0
   @ngrx/component-store    : 16.2.0
   @ngrx/effects            : 16.2.0
   @ngrx/entity             : 16.2.0
   @ngrx/router-store       : 16.2.0
   @ngrx/schematics         : 16.2.0
   @ngrx/store              : 16.2.0
   @ngrx/store-devtools     : 16.2.0
   @storybook/angular       : 7.5.3
   @testing-library/angular : 14.2.0
   ---------------------------------------
   Local workspace plugins:
   	 @mon/workspace-plugin
```
```


### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I'm sure there are good reasons for this change, but it seems basic features disappeared?

**Comment by jaysoo** [comment]
Hi @prewk I think your tsconfig issue is because we no longer use `npmScope` in `nx.json`. The only way to set scope is to change your root `package.json` to include a scope in the name. 

For example, if your workspace root `package.json` has this:

```json5
{ 
  "name": "@acme/source"
  //...
}
```

Then Nx will use `@acme` as the scope.

**Comment by prewk** [comment]
Wow thank you, I've totally missed this! Btw, it seems the right name is `@acme/root`.

Can I configure which generator `nx g lib` uses also?
