### ISSUE TITLE
No ./tmp folder

### ISSUE THREAD

**Issue by birkskyum** [nrwl/nx#20725]
### Documentation issue

- [ ] Reporting a typo
- [X] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.

https://github.com/nrwl/nx/blob/8caebc5280d0c4cdfa68171bf112b5b8509601d4/CONTRIBUTING.md?plain=1#L80

### Additional context or description

I tried to follow this CONTRIBUTION.md guide, but there is no ./tmp folder created:

```md
## Publishing to a local registry

To test if your changes will actually work once the changes are published,
it can be useful to publish to a local registry.

Check out [this video for a live walkthrough](https://youtu.be/Tx257WpNsxc) or follow the instructions below:

- Run `pnpm local-registry` in Terminal 1 (keep it running)
- Run `npm adduser --registry http://localhost:4873` in Terminal 2 (real credentials are not required, you just need to
  be logged in. You can use test/test/test@test.io.)
- Run `pnpm nx-release 18.0.0 --local` in Terminal 2 - you can choose any nonexistent version number here, but it's recommended to use the next major
- Run `cd ./tmp` in Terminal 2
- Run `npx create-nx-workspace@18.0.0` in Terminal 2

If you have problems publishing, make sure you use Node 18 and NPM 8.
```

**Comment by xYouLL** [comment]
I ran into this issue too on macOs.
I fixed it by running again the commands listed in the documentation.
If still it's not working, try to re-install all the dependencies and try again.

**Comment by AgentEnder** [comment]
Its possible that tmp directory may not be present. In any case, its not relevant for the rest of the guide. The main point is to navigate outside of the nx workspace and create a new workspace using the published version.

**Comment by FrozenPandaz** [comment]
Closing this issue as the question has been answered.
