### ISSUE TITLE
Updating from 15.6 to 17.2 (and possibly earlier) causes `Class private methods are not enabled` errors when using `transformIgnorePatterns`

### ISSUE THREAD

**Issue by mikehhhhhhh** [nrwl/nx#20723]
### Current Behavior

On a project that has unbuilt dependencies, and thus entries in jest `transformIgnorePatterns`, when running nx test on any project after migrating from nx 15.6 to 17.2, I get the following error:

```/Users/me/code/project/node_modules/jest-runner/build/index.js: Class private methods are not enabled. Please add `@babel/plugin-proposal-private-methods```

### Expected Behavior

Tests should continue to work

### Steps to Reproduce

1. Create project in 15.6 that depends on unbuilt TS npm modules. 
2. Update to 17.2
3. Run tests

### Nx Report

```shell
Node   : 18.16.1
   OS     : darwin-arm64
   pnpm   : 7.29.3
   
   nx (global)        : 17.2.1
   nx                 : 17.2.1
   @nx/js             : 17.2.1
   @nx/jest           : 17.2.1
   @nx/eslint         : 17.2.1
   @nx/workspace      : 17.2.1
   @nx/cypress        : 17.2.1
   @nx/devkit         : 17.2.1
   @nx/eslint-plugin  : 17.2.1
   @nx/nest           : 17.2.1
   @nx/node           : 17.2.1
   @nx/plugin         : 17.2.1
   @nx/react          : 17.2.1
   @nx/webpack        : 17.2.1
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @jscutlery/semver      : 2.30.0
   @nx-tools/nx-container : 4.0.3
```

### Failure Logs

```shell
Test Suites: 0 of 11 total
Tests:       0 total
Snapshots:   0 total
Time:        1.884 s
Ran all test suites.

 >  NX   /Users/me/code/project/node_modules/jest-runner/build/index.js: Class private methods are not enabled. Please add `@babel/plugin-proposal-private-methods` to your configuration.

     71 |       : this.#createParallelTestRun(tests, watcher);
     72 |   }
   > 73 |   async #createInBandTestRun(tests, watcher) {
        |   ^
     74 |     process.env.JEST_WORKER_ID = '1';
     75 |     const mutex = (0, _pLimit().default)(1);
     76 |     return tests.reduce(
   Pass --verbose to see the stacktrace.


 ———————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target test for project parent (3s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I believe this is the same issue as #15356 

Removing `transformIgnorePatterns` is not an option for me, as we depend on some unbuilt ts modules.

Adding `jest-runner` to the `transformIgnorePatterns` solves the issue. Perhaps this should be added to the jest preset or at least documented somewhere? 

Creating this issue mostly for future searchers to find a solution, as the error messages send you on a wild goose chase trying to add babel modules that does not resolve the issue.

**Comment by jaysoo** [comment]
@mikehhhhhhh Can you provide a small repro for this issue? It looks like `jest-runner` is being transpiled, which should not happen.

**Comment by jaysoo** [comment]
Perhaps `node_modules` is not being ignored?
