### ISSUE TITLE
@nx/dependency-checks incorrectly caches dependencies from first seen package.json for the entire run

### ISSUE THREAD

**Issue by ComradeCow** [nrwl/nx#20727]
### Current Behavior

We use `lint-staged` to enforce lint rules with a pre-commit hook. To speed that up, we're invoking `eslint` directly on the files that are changed (instead of invoking the lint target on affected projects).

If we have a commit with multiple `package.json` files, the lint rule assumes ALL packages use the dependencies of the first package.  This means when it scans the second, third `package.json` file, it believes there are dependencies missing from those projects, even if the `package.json` files are correct.  

The auto-fixer will end up adding duplicated dependencies to subsequent the `package.json` files (adding dependencies when it was already specified in the `package.json`)

We currently work around this issue by committing the `package.json` files one at a time.

### Expected Behavior

The rule should work across multiple package.json files in a single eslint run.

The rule should emit the same errors regardless of the order the files are specified in.

The auto-fixer should not add 

### GitHub Repo

https://github.com/ComradeCow/nx-deps-lint-error

### Steps to Reproduce

0. Clone the sample repo - run `npm install`

1. Run `npx eslint packages/project1/package.json packages/project2/package.json` 
    The lint rule fails complaining pad-right is missing from project2

2. Run `npx eslint packages/project1/package.json` 
    No errors

3. Run `npx eslint packages/project2/package.json`
    No errors

4. Run `npx eslint packages/project2/package.json packages/project1/package.json`
    The lint rule fails, but pad-left is missing from project1

5. Run `npx eslint packages/project2/package.json packages/project1/package.json --fix`
    `pad-left` will be added to project1's package.json a second time.

### Nx Report

```shell
❯ nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 20.6.1
   OS     : linux-x64
   npm    : 10.2.4
   
   nx (global)        : 17.1.1
   nx                 : 17.2.1
   @nx/js             : 17.2.1
   @nx/workspace      : 17.2.1
   @nx/devkit         : 17.2.1
   @nx/eslint-plugin  : 17.2.1
   @nrwl/tao          : 17.2.1
   typescript         : 5.3.3
```

### Package Manager Version

10.1.0

### Operating System

- [X] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by meeroslav** [comment]
Interesting find. Thank you for reporting this.
