### ISSUE TITLE
ESLint Configuration Issue: Missing 'parserOptions.project' for TypeScript 'deprecation/deprecation' Rule after upgrading to 17.2.x

### ISSUE THREAD

**Issue by yuchuan1** [nrwl/nx#20731]
### Current Behavior

After running ```pnpm nx migrate latest```, ```ppnpm install --no-frozen-lockfile``` and ```pnpm exec nx migrate --run-migrations```, my original working eslint for one of my libs stopped working.
Here is the error message

nx run ui:lint
Linting "ui"...

Error: You have attempted to use the lint rule deprecation/deprecation which requires the full TypeScript type-checker to be available, but you do not have `parserOptions.project` configured to point at your project tsconfig.json files in the relevant TypeScript file "overrides" block of your project ESLint config `libs/ui/.eslintrc.json`

Please see https://nx.dev/guides/eslint for full guidance on how to resolve this issue.

### Expected Behavior

The lint should run without error

### Steps to Reproduce

1. run ```pnpm nx lint ui```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : darwin-arm64
   pnpm   : 8.12.0

   nx                 : 17.2.3
   @nx/js             : 17.2.3
   @nx/jest           : 17.2.3
   @nx/eslint         : 17.2.3
   @nx/workspace      : 17.2.3
   @nx/angular        : 17.2.3
   @nx/cypress        : 17.2.3
   @nx/esbuild        : 17.2.3
   @nx/eslint-plugin  : 17.2.3
   @nx/nest           : 17.2.3
   @nx/node           : 17.2.3
   @nx/storybook      : 17.2.3
   @nx/web            : 17.2.3
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc       : 1.1.23
   @ngneat/spectator        : 15.0.1
   @ngneat/tailwind         : 7.0.3
   @ngrx/component-store    : 17.0.1
   @ngrx/effects            : 17.0.1
   @ngrx/entity             : 17.0.1
   @ngrx/eslint-plugin      : 17.0.1
   @ngrx/router-store       : 17.0.1
   @ngrx/schematics         : 17.0.1
   @ngrx/store              : 17.0.1
   @ngrx/store-devtools     : 17.0.1
   @ngx-matomo/router       : 4.1.2
   @ngx-matomo/tracker      : 4.1.2
   @storybook/angular       : 7.6.4
   @testing-library/angular : 15.1.0
   eslint-plugin-ngrx       : 2.1.4
   ng-mocks                 : 14.12.1
   ngrx-immer               : 2.1.1
   ngx-extended-pdf-viewer  : 19.0.0-alpha.6
   ngx-spec                 : 2.1.6
   ngx-toastr               : 18.0.0
   nx-stylelint             : 17.1.0
```

### Failure Logs

```shell
nx run ui:lint


Linting "ui"...

Error: You have attempted to use the lint rule deprecation/deprecation which requires the full TypeScript type-checker to be available, but you do not have `parserOptions.project` configured to point at your project tsconfig.json files in the relevant TypeScript file "overrides" block of your project ESLint config `libs/ui/.eslintrc.json`

Please see https://nx.dev/guides/eslint for full guidance on how to resolve this issue.


 ————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target lint for project ui (8s)

    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]

 ELIFECYCLE  Command failed with exit code 1.
```

### Package Manager Version

pnpm   : 8.12.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

.eslintrc.json for ui lib
```
{
  "extends": ["../../.eslintrc.json"],
  "ignorePatterns": ["!**/*"],
  "overrides": [
    {
      "files": ["*.ts", "src/**/*.ts"],
      "extends": [
        "plugin:@angular-eslint/recommended",
        "plugin:@angular-eslint/template/process-inline-templates",
        "plugin:sonarjs/recommended",
        "plugin:tailwindcss/recommended",
        "plugin:security/recommended",
        "plugin:compat/recommended",
        "plugin:@nx/angular",
        "plugin:deprecation/recommended",
        "prettier"
      ],
      "parserOptions": {
        "project": [
          "libs/ui/tsconfig.*?.json",
          "libs/ui/.storybook/tsconfig.json"
        ]
      },
      "rules": {
        "@typescript-eslint/no-explicit-any": "off",
        "@typescript-eslint/no-unused-vars": "off",
        "import/export": "off",
        "import/no-unresolved": "off",
        "security/detect-object-injection": "off",
        "@angular-eslint/directive-selector": [
          "error",
          {
            "type": "attribute",
            "prefix": "holmes",
            "style": "camelCase"
          }
        ],
        "@angular-eslint/component-selector": [
          "error",
          {
            "type": "element",
            "prefix": "holmes",
            "style": "kebab-case"
          }
        ],
        "array-plural/array-plural": [
          2,
          {
            "allows": [
              "actual",
              "arr",
              "array",
              "axis",
              "columnDef",
              "dataset",
              "expected",
              "g",
              "layout",
              "list",
              "model",
              "range",
              "result",
              "sort",
              "temp"
            ]
          }
        ]
      }
    },
    {
      "files": ["*.spec.ts"],
      "extends": [
        "plugin:testing-library/angular",
        "plugin:jest-formatting/recommended",
        "plugin:jest/recommended"
      ],
      "rules": {
        "sonarjs/no-duplicate-string": "off",
        "import/no-unresolved": "off",
        "@typescript-eslint/no-non-null-assertion": "off",
        "non-null-expression": "off",
        "@typescript-eslint/no-unused-vars": "off",
        "@typescript-eslint/no-empty-function": "off",
        "array-plural/array-plural": [
          2,
          {
            "allows": [
              "actual",
              "arr",
              "array",
              "axis",
              "columnDef",
              "dataset",
              "expected",
              "g",
              "layout",
              "list",
              "model",
              "range",
              "result",
              "sort",
              "temp"
            ]
          }
        ]
      }
    },
    {
      "files": ["*.stories.ts"],
      "extends": ["plugin:storybook/recommended"],
      "rules": {
        "sonarjs/no-duplicate-string": "off",
        "import/no-unresolved": "off"
      }
    },
    {
      "files": ["*.html"],
      "extends": ["plugin:@nx/angular-template"],
      "rules": {}
    }
  ]
}
```

**Comment by ViktorPontinen** [comment]
Getting same issue here as well. Impossible to debug why, if it's an issue with eslint or the config. Here's my `.eslintrc.json` located in the library.

```
{
  "extends": ["plugin:@nrwl/nx/react", "@custom/eslint-config-custom", "../../../../.eslintrc.json"],
  "ignorePatterns": ["!**/*"],
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],
      "parserOptions": {
        "project": ["libs/shared/util/cache-buster/tsconfig.*?.json"]
      },
      "rules": {}
    },
    {
      "files": ["*.ts", "*.tsx"],
      "rules": {}
    },
    {
      "files": ["*.js", "*.jsx"],
      "rules": {}
    }
  ]
}

```

When running `nx lint shared-util-cache-buster` getting error:
```
Linting "shared-util-cache-buster"...

Error: You have attempted to use the lint rule @typescript-eslint/naming-convention which requires the full TypeScript type-checker to be available, but you do not have `parserOptions.project` configured to point at your project tsconfig.json files in the relevant TypeScript file "overrides" block of your project ESLint config `libs/shared/util/cache-buster/.eslintrc.json`

Please see https://nx.dev/guides/eslint for full guidance on how to resolve this issue.
```

**Comment by ViktorPontinen** [comment]
Adding further debugging information.

After adding back `"lintFilePatterns": ["libs/shared/util/cache-buster/**/*.{ts,tsx,js,jsx}"]` in `lint` target in `project.json` it seems to work again. So it's something related to the removal of `lintFilePatters` that was made in migration of this PR https://github.com/nrwl/nx/pull/20313 , which was released to `v17.2.0`. Will dig deeper into the changes to see if anything was missed.

Working and not working lint targets for reference:
Working:
```
    "lint": {
      "executor": "@nx/eslint:lint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["libs/shared/util/cache-buster/**/*.{ts,tsx,js,jsx}"]
      }
    },
```

Not working:
```
    "lint": {
      "executor": "@nx/eslint:lint",
      "outputs": ["{options.outputFile}"]
    },
```

**Comment by yuchuan1** [comment]
It worked after adding back lintFilePatterns.
Thanks @ViktorPontinen

**Comment by ViktorPontinen** [comment]
> It worked after adding back lintFilePatterns. Thanks @ViktorPontinen

Np. It's a temporary workaround tho, ideally it should work without adding it I guess.

Couldn't find anything in https://github.com/nrwl/nx/pull/20313 that would break this but I probably don't have the right insights to figure it out.

**Comment by meeroslav** [comment]
Hi @yuchuan1 and @ViktorPontinen,

Thank you for reporting this. The latest version changes `lintFilePatterns` from e.g. `path/to/your/project/**/*.{fileExtensionList}` to `{projectRoot}` where `projectRoot=path/to/your/project`.

The main difference is that before you were only linting specific files e. g. `ts,tsx,js,jsx` in Viktor's case while now the linter will lint all the files for which there are rules defined in the config files.

If you have something like:
```
{
      "files": "*.json",
      "parser": "jsonc-eslint-parser",
      "rules": {}
}
```

it would now lint the JSON files as well. There is somewhere a misconfiguration on your end where non-TS files are being linted with Typescript-eslint rules.

## Time consuming fix

Running lint task with `--format=json` would list all the files that are now being linted. You will probably spot some file extensions that were not in the original `lintFilePattern`. You can either remove all the `overrides` that point to that extension or investigate why the TS rules apply to them.

Calling `eslint --print-config path/to/my/project/random.json` would, for example, show us all the rules applied to linting JSON files. You can do the same for `html` files or anything else you suspect of being linted, and it shouldn't. 

The error is likely in your base root eslint config or in one of the other extends (e.g. `@custom/eslint-config-custom` in Viktor's case).

This is the path that I propose to take, as long as you can reserve time for it.

## Quick fix

You can always reset the lintFilePattern back to it's original state:

```
// original

    "lint": {
      "executor": "@nx/eslint:lint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["libs/shared/util/cache-buster/**/*.{ts,tsx,js,jsx}"]
      }
    },

// after migration

    "lint": {
      "executor": "@nx/eslint:lint",
      "outputs": ["{options.outputFile}"],
    },

// fixed

    "lint": {
      "executor": "@nx/eslint:lint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["{projectRoot}/**/*.{ts,tsx,js,jsx}"]
      }
    },
```

**Comment by ViktorPontinen** [comment]
@meeroslav Thanks for the clarification. If I understand correctly the issue stems from ts rules being applied to json files?

In my case, the `@custom/eslint-config-custom` just extends `["airbnb", "airbnb-typescript"]`(with disabling of some rules), no overrides or rules for json files added there. 
In root .eslintrc.json I have `"extends": ["plugin:prettier/recommended", "plugin:jest/recommended"],`. Besides those we have not added any overrides or rules to json files. 

I have also deducted that the `plugin:prettier/recommended` and `plugin:jest/recommended` as not being the issue because everything works as expected(event without `lintFilePatterns`) if I remove `@custom/eslint-config-custom` from project eslint config. So if initial question is correct it would point to `airbnb` or `airbnb-typescript` having improper file targeting somewhere.

**Comment by meeroslav** [comment]
> If I understand correctly the issue stems from ts rules being applied to json files?

That's my guess. In any case, the ts rules are being applied to files that are not in this array `["*.ts", "*.tsx", "*.js", "*.jsx"]` since for those you have parser defined.

I'm suspecting on https://github.com/iamturns/eslint-config-airbnb-typescript. If you look at this line https://github.com/iamturns/eslint-config-airbnb-typescript/blob/master/lib/shared.js#L31 you will notice that it sets those rules without restricting them to a specific file set, meaning it would be applied on any file and one of those requires ts parser.

**Comment by ViktorPontinen** [comment]
> > If I understand correctly the issue stems from ts rules being applied to json files?
> 
> That's my guess. In any case, the ts rules are being applied to files that are not in this array `["*.ts", "*.tsx", "*.js", "*.jsx"]` since for those you have parser defined.
> 
> I'm suspecting on https://github.com/iamturns/eslint-config-airbnb-typescript. If you look at this line https://github.com/iamturns/eslint-config-airbnb-typescript/blob/master/lib/shared.js#L31 you will notice that it sets those rules without restricting them to a specific file set, meaning it would be applied on any file and one of those requires ts parser.

Yep, made the same conclusion. Thanks for the input. I guess OP also has some rule that created this issue.

**Comment by meeroslav** [comment]
One potentially quick solution would be to move that extends inside the override:

This applies `@custom/eslint-config-custom` including the airbnb-typescript on everthing
```json
{
  "extends": ["plugin:@nrwl/nx/react", "@custom/eslint-config-custom", "../../../../.eslintrc.json"],
  "ignorePatterns": ["!**/*"],
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],
      "parserOptions": {
        "project": ["libs/shared/util/cache-buster/tsconfig.*?.json"]
      },
      "rules": {}
    },
    {
      "files": ["*.ts", "*.tsx"],
      "rules": {}
    },
    {
      "files": ["*.js", "*.jsx"],
      "rules": {}
    }
  ]
}
```

This one keeps it bound to JS/TS files only:
This applies `@custom/eslint-config-custom` including the airbnb-typescript on everthing
```json
{
  "extends": ["plugin:@nrwl/nx/react", "../../../../.eslintrc.json"],
  "ignorePatterns": ["!**/*"],
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],
     "extends": ["@custom/eslint-config-custom"],
      "parserOptions": {
        "project": ["libs/shared/util/cache-buster/tsconfig.*?.json"]
      },
      "rules": {}
    },
    {
      "files": ["*.ts", "*.tsx"],
      "rules": {}
    },
    {
      "files": ["*.js", "*.jsx"],
      "rules": {}
    }
  ]
}
```

**Comment by meeroslav** [comment]
@yuchuan1, please let me know if the writeup above also solves your problem.
In the worst case, reverting `lintFilePatterns` brings you back to the previous safe state.

I will close this issue, but in case something other pops up we can reopen it.
