### ISSUE TITLE
After migrating from NX 17.2.1 to 17.2.3 Angular App can't be build

### ISSUE THREAD

**Issue by phihochzwei** [nrwl/nx#20732]
### Current Behavior

I just migrated via nx migrate latest from 17.2.1 to 17.2.3. After migration, the build process fails and no bundle files are generated. The are no errors, even when running with --verbose. The bundle files are simply not generated and therefore the build fails

After reverting to NX 17.2.1 via Revert Commit everything works fine

### Expected Behavior

Expected behavior would be, that the application is building as usual :) 

### Steps to Reproduce

1. nx migrate latest
2. npm install
3. nx build

Our project is an angular application with ssr. 

### Nx Report

```shell
not available
```

### Package Manager Version

rpm 10.2.3

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [X] Other (Please specify)

### Additional Information

Error occurs on my local OSX machine as well as on our gitlab CI pipeline

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Unfortunately, I can't reproduce the issue with the provided information. Please note the provided information is too generic and doesn't allow us to get to the state your application is in. When a repo with a reproduction is not provided, it's important the reproduction steps are as detailed as possible. This increases the likelihood that we can reproduce the issue you're having and we can help.

Key information is missing in the description of the issue:

- how the workspace should be created (specific options that lead to your setup before migrating)
- output of `nx report`

Please provide those details and anything you might think is relevant so we can reproduce the issue. If possible, it would be even better to provide a reproduction.

**Comment by phihochzwei** [comment]
I can provide the output of nx report tomorrow. However, the specific options that led to our workspace are shrouded in the past, since we are working on/in it for now a little bit more than 2 years.

**Comment by phihochzwei** [comment]
@leosvelperez What ever the problem was, it is solved in 17.2.4 

I migrated from 17.2.1 to 17.2.4 and all works as expected. However, if you use "nx migrate latest" you still get 17.2.3, I had to address the latest version manually
