### ISSUE TITLE
After migrating from Nx 17.0.2 to 17.2.3 Node App cannot be built with webpack

### ISSUE THREAD

**Issue by dtslvr** [nrwl/nx#20735]
### Current Behavior

After running `yarn nx migrate latest` and applying the migrations, I'm not able to build the backend (Node / webpack) anymore.

### Expected Behavior

The backend builds successfully as before with Nx `17.0.2`.

### Steps to Reproduce

1. yarn nx migrate latest
2. yarn install
3. yarn nx migrate --run-migrations
4. yarn nx run backend:build

### Nx Report

```shell
   Node   : 18.19.0
   OS     : darwin-arm64
   yarn   : 1.22.21
   
   nx                 : 17.2.3
   @nx/js             : 17.2.3
   @nx/jest           : 17.2.3
   @nx/linter         : 17.2.3
   @nx/eslint         : 17.2.3
   @nx/workspace      : 17.2.3
   @nx/angular        : 17.2.3
   @nx/cypress        : 17.2.3
   @nx/devkit         : 17.2.3
   @nx/eslint-plugin  : 17.2.3
   @nx/express        : 17.2.3
   @nx/node           : 17.2.3
   @nx/storybook      : 17.2.3
   @nrwl/tao          : 17.2.3
   @nx/web            : 17.2.3
   @nx/webpack        : 17.2.3
   typescript         : 5.2.2
```

### Failure Logs

```shell
ERROR in main
Module not found: Error: Can't resolve './src' in '/Development/my-application'
resolve './src' in '/Development/my-application'
  using description file: /Development/my-application/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Development/my-application/package.json (relative path: ./src)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Development/my-application/src doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Development/my-application/src.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /Development/my-application/src.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /Development/my-application/src.wasm doesn't exist
      as directory
        /Development/my-application/src doesn't exist

webpack 5.89.0 compiled with 1 error and 1 warning in 66 ms
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

For `yarn nx migrate latest` I still get `17.2.3` instead of `17.2.4`.

**Comment by Hypenate** [comment]
We had the same issues, we downgraded the the `nx/webpack` packageback to version 17.0.3
`"@nx/webpack": "17.0.3"`

**Comment by mandarini** [comment]
@dtslvr can you please share a simple reproduction repository? thanks for filing an issue!

Here is my repo: https://github.com/mandarini/webpack-nx-migrate

I could not reproduce. My apps build successfully before and after migrating...

**Comment by fabar-fast4** [comment]
I have the same issue and I just found the solution !
I think a migration is missing in the last NX version.

To fix your build, override the following code in `webpack.config.js`

```javascript
// Nx plugins for webpack.
module.exports = composePlugins(
  withNx({
    target: 'node',
  }),
  (config) => {
    // Update the webpack config as needed here.
    // e.g. `config.plugins.push(new MyPlugin())`
    return config
  }
)
````

**Comment by NathanLaing** [comment]
> I have the same issue and I just found the solution ! I think a migration is missing in the last NX version.
> 
> To fix your build, override the following code in `webpack.config.js`
> 
> ```js
> const { composePlugins, withNx } = require('@nx/webpack')
> 
> // Nx plugins for webpack.
> module.exports = composePlugins(
>   withNx({
>     target: 'node',
>   }),
>   (config) => {
>     // Update the webpack config as needed here.
>     // e.g. `config.plugins.push(new MyPlugin())`
>     return config
>   }
> )
> ```

Was having the issue outlined here. This fix worked for me.
