### ISSUE TITLE
After migration from 17.1.3 to 17.2.4 component tests started failing due to incorrect webpack configuration

### ISSUE THREAD

**Issue by yzhylin** [nrwl/nx#20743]
### Current Behavior

After running `component-test` target for a remote microfronted `nx run application:component-test` we started observing the following output:

DevTools listening on ws://127.0.0.1:56124/devtools/browser/88bbfaeb-0acc-47b9-b026-d8de908ef771
[webpack-dev-server] Project is running at:
[webpack-dev-server] Loopback: http://127.0.0.1:8080/
[webpack-dev-server] Content not from webpack is served from 'workspace\apps\application\public' directory

Remove output folder workspace\apps\application\cypress\reports\html

ERROR in   HookWebpackError: ENOENT: no such file or directory, scandir
  
  - HookWebpackError.js:48 makeWebpackError
    [workspace]/[webpack]/lib/HookWebpackErr    or.js:48:9
  - Compilation.js:3068 
    [workspace]/[webpack]/lib/Compilation.js    :3068:12
  - Compilation.js:481 fn
    [workspace]/[webpack]/lib/Compilation.js    :481:17
    
    ....

  - -- inner error --
  - Error: ENOENT: no such file or directory, scandir

ERROR in Conflict: Multiple assets emit different content to the same filename index.html
webpack compiled with 2 errors (246588d18d80c2bb)

Here is a chunk from the project config:

```
    "component-test": {
      "executor": "@nx/cypress:cypress",
      "options": {
        "cypressConfig": "apps/application/cypress.config.ts",
        "testingType": "component",
        "devServerTarget": "application:build",
        "skipServe": true
      }
    },

"build": {
      "executor": "@nx/webpack:webpack",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "compiler": "babel",
        "outputPath": "dist/apps/application",
        "index": "apps/application/src/index.html",
        "baseHref": "/",
        "main": "apps/application/src/main.ts",
        "tsConfig": "apps/application/tsconfig.app.json",
        "assets": [
          "apps/application/src/favicon.ico",
          "apps/application/src/assets"
        ],
        "scripts": [],
        "webpackConfig": "apps/application/webpack.config.js"
      },
      "configurations": {
        "development": {
          "extractLicenses": false,
          "optimization": false,
          "sourceMap": true,
          "vendorChunk": true
        },
        "production": {
          "fileReplacements": [
            {
              "replace": "apps/application/src/environments/environment.ts",
              "with": "apps/application/src/environments/environment.prod.ts"
            }
          ],
          "optimization": true,
          "outputHashing": "all",
          "sourceMap": false,
          "namedChunks": false,
          "extractLicenses": true,
          "vendorChunk": false,
          "webpackConfig": "apps/application/webpack.config.prod.js"
        }
      }
    },

```

### Expected Behavior

Component test target should work or migration steps has to be correct

### Steps to Reproduce

1. npx nx migrage 17.2.4
2. follow the instructions
3. npx nx run appliation:component-test

### Nx Report

```shell
Node   : 18.18.2
   OS     : win32-x64
   npm    : 9.8.1
   
   nx                 : 17.2.4
   @nx/js             : 17.2.4
   @nx/jest           : 17.2.4
   @nx/linter         : 17.2.4
   @nx/eslint         : 17.2.4
   @nx/workspace      : 17.2.4
   @nx/cypress        : 17.2.4
   @nx/devkit         : 17.2.4
   @nx/eslint-plugin  : 17.2.4
   @nx/plugin         : 17.2.4
   @nx/react          : 17.2.4
   @nx/storybook      : 17.2.4
   @nrwl/tao          : 17.2.4
   @nx/web            : 17.2.4
   @nx/webpack        : 17.2.4
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @nxkit/style-dictionary : 3.0.2
   ---------------------------------------
   Local workspace plugins:
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Hi there @yzhylin ! Thanks for filing an issue! Can you please share a reproduction repository? This will really help us with understanding what's wrong and resolving the issue quicker! Thank you!!

**Comment by yzhylin** [comment]
Here it is https://github.com/yzhylin/broken-component-test
