### ISSUE TITLE
@nx/storybook, lack of support for storybook 8

### ISSUE THREAD

**Issue by sebpalluel** [nrwl/nx#20745]
### Current Behavior

When launching my project with the latest version of storybook (^8.0.0-alpha.3) I get this error:
```
Storybook 6 is no longer maintained, and not supported in Nx. 
       Please upgrade to Storybook 7.
   
       Here is a guide on how to upgrade:
       https://nx.dev/nx-api/storybook/generators/migrate-7
```

### Expected Behavior

Storybook just announced the support for RSC in storybook with Nextjs: https://storybook.js.org/blog/storybook-react-server-components/
It would be really useful to avoid this error that is not related to storybook 8 itself.

### GitHub Repo

https://github.com/sebpalluel/storybook-rsc-demo-nx

### Steps to Reproduce

1. `pnpm i`
2. `pnpm storybook` (the storybook targeting the app in the root folder is working normally)
3. `pnpm exec nx run nextjs:storybook` (the storybook targeting the app in nextjs folder is failing)

### Nx Report

```shell
>  NX   Running global Nx CLI with PNPM may have issues.

   Prefer to use "pnpm" (https://pnpm.io/cli/exec) to execute commands in this workspace.
    TIP  create a shortcut such as: alias pnx="pnpm nx --"
   


 >  NX   Report complete - copy this into the issue template

   Node   : 20.1.0
   OS     : darwin-arm64
   pnpm   : 8.11.0
   
   nx                 : 17.2.3
   @nx/js             : 17.2.4
   @nx/jest           : 17.2.4
   @nx/eslint         : 17.2.4
   @nx/cypress        : 17.2.3
   @nx/eslint-plugin  : 17.2.4
   @nx/next           : 17.2.4
   @nx/react          : 17.2.4
   @nx/storybook      : 17.2.3
   typescript         : 5.3.3
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/js@17.2.4
     - @nx/jest@17.2.4
     - @nx/eslint@17.2.4
     - @nx/eslint-plugin@17.2.4
     - @nrwl/eslint-plugin-nx@17.2.4
     - @nx/next@17.2.4
     - @nx/react@17.2.4
   
   To fix this, run `nx migrate nx@17.2.4`
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This repo is a fork of the original demo for RSC: https://github.com/shilman/storybook-rsc-demo

**Comment by mandarini** [comment]
Oooops! Will fix it asap (not today tho :P )
