### ISSUE TITLE
Angular-standalone workspace creation with pnpm fails

### ISSUE THREAD

**Issue by gergelyszerovay** [nrwl/nx#20753]
### Current Behavior

I run `pnpm dlx create-nx-workspace@latest nx17app --preset=angular-standalone --packageManager=pnpm` on Widows 10, then select esbuild/scss/no SSR/no e2e/no distributed cache. I get the following error:

```
Packages: +67
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 67, reused 67, downloaded 0, added 67, done

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

√ Which bundler would you like to use? · esbuild
√ Default stylesheet format · scss
√ Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? · No
√ Test runner to use for end to end (E2E) tests · none
√ Enable distributed caching to make your CI faster · No

 >  NX   Creating your v17.2.3 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "pnpm install" several times. Please wait.

✔ Installing dependencies with pnpm
✖ Creating your workspace in nx17app

 >  NX   Failed to create a workspace.

   Error: 'dules' is not recognized as an internal or external command,
operable program or batch file.
```

### Expected Behavior

The workspace should be created

### Steps to Reproduce

1. `pnpm dlx create-nx-workspace@latest nx17app --preset=angular-standalone --packageManager=pnpm`
2. select esbuild/scss/no SSR/no e2e/no distributed cache

### Nx Report

```shell
-
```

### Package Manager Version

pnpm 8.12.0

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
I tested this and it's not Angular specific. The workspace appears to be created correctly, but CNW always errors out with:

```
   Error: '\node_modules' is not recognized as an internal or external command,
operable program or batch file.
```

Or a variation of that error.

**Comment by pjoe** [comment]
FWIW: looks like windows specific, works for me on Linux (WSL)
