### ISSUE TITLE
Suppression of Vite CJS warning doesn't work

### ISSUE THREAD

**Issue by ms-tng** [nrwl/nx#20769]
### Current Behavior

The `@nx/vite:build` and `@nx/vite:dev-server` executors print this warning:
```
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
```
That is although the warning should have been suppressed by https://github.com/nrwl/nx/pull/20719.

### Expected Behavior

There should be no warning.

### Steps to Reproduce

Run the `@nx/vite:build` or `@nx/vite:dev-server` executor

### Nx Report

```shell
   Node   : 20.5.0
   OS     : win32-x64
   pnpm   : 8.9.0

   nx (global)        : 17.2.4
   nx                 : 17.2.4
   @nx/js             : 17.2.4
   @nx/eslint         : 17.2.4
   @nx/workspace      : 17.2.4
   @nx/devkit         : 17.2.4
   @nx/eslint-plugin  : 17.2.4
   @nx/react          : 17.2.4
   @nrwl/tao          : 17.2.4
   @nx/vite           : 17.2.4
   typescript         : 5.3.3
```

### Package Manager Version

pnpm 8.9.0

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

This happens because Vite already prints the warning when it is `require`d, which happens before the `VITE_CJS_IGNORE_WARNING` environment variable is set here: https://github.com/nrwl/nx/blob/80a987ee7dc72509b0d750b0ce094b17c00df005/packages/vite/src/executors/build/build.impl.ts#L34

**Comment by mandarini** [comment]
@Lonli-Lokli we're planning to do that, yes
