### ISSUE TITLE
Remote module federation report error (SyntaxError: Cannot use 'import.meta' outside a module)

### ISSUE THREAD

**Issue by erankhoo** [nrwl/nx#20761]
### Current Behavior

I am trying to consume module federation from the CDNm through module federation plugin. I tried to render it on server side but got this error

<img width="1505" alt="image" src="https://github.com/nrwl/nx/assets/151596962/117e8f9e-ccaf-459e-bfd9-5f1c0cd0d820">

### Expected Behavior

I expect it can render on server side

### Steps to Reproduce

See Above

### Nx Report

```shell
Node   : 21.2.0
   OS     : darwin-arm64
   npm    : 10.2.3
   
   nx (global)        : 17.1.3
   nx                 : 17.2.3
   @nx/js             : 17.2.3
   @nx/jest           : 17.2.3
   @nx/linter         : 17.2.3
   @nx/eslint         : 17.2.3
   @nx/workspace      : 17.2.3
   @nx/cypress        : 17.2.3
   @nx/devkit         : 17.2.3
   @nx/eslint-plugin  : 17.2.3
   @nx/react          : 17.2.3
   @nrwl/tao          : 17.2.3
   @nx/web            : 17.2.3
   @nx/webpack        : 17.2.4
   typescript         : 5.2.2
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/webpack@17.2.4
     - @nrwl/webpack@17.2.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
If you can provide a repo that reproduces this error that would be great.

As this is React workspace, it doesn't quite fall under the known issue regarding this error on Angular.
You can also try updating your `module-federation.config.js` file to add `libraryType: 'var'`, which _should_ resolve the issue.

**Comment by erankhoo** [comment]
hello @Coly010 thank you for your quick response!

https://github.com/kea0811/demo-nx

here is the repo that i replicate the error.

clone that project and run 'nx serve shell myremote'

**Comment by erankhoo** [comment]
Hey @Coly010 , I manage to resolved the issue above by changing the library to commonjs-module. But it causes another error says document is not defined when accessing it from findStylesheet function. Has anyone met the same problem?

it seems like it can’t access the document when it runs on vm.

**Comment by erankhoo** [comment]
hello @Coly010 , I had test without the scss/css bundling (not import in module). it works, so it seems like it is the styling that is blocking the build. is there a way i can load the styling at CSR?

Does anyone met the same problem?

**Comment by p-dtamburus** [comment]
Same problem here with angular 17...
![image](https://github.com/nrwl/nx/assets/151773829/b007e0d6-2437-4caf-97b6-23b96924bc24)

**Comment by ndcunningham** [comment]
@erankhoo sorry for the lateness but did you ever find a working solution?

I tried your repo and I think as @Coly010 mentioned you might need to use `type: 'var'` on both your remote and your host.

I tried to load your remote via a `promise` but It seems that your amazon remote blocks `localhost` so I could not fetch it from the app.

> Access to script at 'https://demo-nx.s3.ap-southeast-1.amazonaws.com/web/browser/remoteEntry.js' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
