### ISSUE TITLE
@nx/eslint: `eslintConfig` config option not working

### ISSUE THREAD

**Issue by knoefel** [nrwl/nx#20777]
### Current Behavior

After initialising a new nx nextjs workspace and migrating to eslint flat config i get the following error after setting the `eslintConfig` prop in the lint section of project.json.

> TypeError: Key "rules": Key "@typescript-eslint/no-array-constructor": Could not find plugin "@typescript-eslint".

This only happens when i explicitly link a eslint.config.js file via `eslintConfig` and don't use the root eslint configuration.

### Expected Behavior

Its possible to run the lint task after upgrading to flat config

### GitHub Repo

https://github.com/knoefel/nx-eslint-flat-config

### Steps to Reproduce

1. create new nx workspace
2. run `nx generate @nx/eslint:convert-to-flat-config`
3. update the app config for the lint target by setting a `esLintConfig` property:
```js
    "lint": {
      "executor": "@nx/eslint:lint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "eslintConfig": "apps/lint/eslint.config.js"
      }
    }
```
4. run `nx lint lint`

### Nx Report

```shell
Node   : 20.10.0
   OS     : darwin-arm64
   npm    : 10.2.4
   
   nx (global)        : 17.1.1
   nx                 : 17.2.4
   @nx/js             : 17.2.4
   @nx/jest           : 17.2.4
   @nx/linter         : 17.2.4
   @nx/eslint         : 17.2.4
   @nx/workspace      : 17.2.4
   @nx/devkit         : 17.2.4
   @nx/eslint-plugin  : 17.2.4
   @nx/next           : 17.2.4
   @nx/playwright     : 17.2.4
   @nx/react          : 17.2.4
   @nrwl/tao          : 17.2.4
   @nx/web            : 17.2.4
   typescript         : 5.2.2
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by meeroslav** [comment]
Thank you @knoefel for reporting this.

The fix is on the way.
