### ISSUE TITLE
Inputs not respected when running effected with specific target

### ISSUE THREAD

**Issue by rluvaton** [nrwl/nx#20776]
### Current Behavior

I have the following config similar to the docs:
```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "targetDefaults": {
    "build": {
      "cache": true,
      "inputs": ["{projectRoot}/src/index.ts"]
    },
	// ....
  },
 // ...
}
```
> Similar to [Docs](https://nx.dev/recipes/running-tasks/customizing-inputs#exclude-files-from-invalidating-cache)

running `npx nx affected:build --base=main` when changed `{projectRoot}/src/index.test.ts` (not `index.test.ts`) still find affected project

### Expected Behavior

Should not find any projects

### GitHub Repo

https://github.com/rluvaton/nx-bug-20776

### Steps to Reproduce

Changes made to be able to reproduce https://github.com/rluvaton/nx-bug-20776/commit/85d38baf0eef43fe9aa98a74a210ea769deadc27

1. Change `apps/nx-named-input/src/index.test.ts`
2. Run `npx nx affected:build --base=main`
3. see that `nx-named-input` project is still executed
4. Cry

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.18.0
   OS     : darwin-arm64
   npm    : 9.8.1
   
   nx                 : 17.2.4
   @nx/js             : 17.2.4
   @nx/jest           : 17.2.4
   @nx/linter         : 17.2.4
   @nx/eslint         : 17.2.4
   @nx/workspace      : 17.2.4
   @nx/devkit         : 17.2.4
   @nx/esbuild        : 17.2.4
   @nx/eslint-plugin  : 17.2.4
   @nx/node           : 17.2.4
   @nrwl/tao          : 17.2.4
   typescript         : 5.2.2
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
This is expected behavior. Affected is not aware of the target being ran, but the duplicates should be cached locally or on CI with the help of Nx Cloud. I'm going to close this out as there are other issues tracking the request for target aware affected.
