### ISSUE TITLE
Improve Azure Pipelines documentation

### ISSUE THREAD

**Issue by lydemann** [nrwl/nx#20787]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.

https://nx.dev/ci/recipes/set-up/monorepo-ci-azure

### Additional context or description

Provide any additional details here as needed.

I recently made a [blog post](https://christianlydemann.com/how-to-set-up-a-ci-pipeline-with-azure-pipelines-and-nx/) where I shared how to set up a complete CI pipeline with Azure Pipelines and Nx including how to release it to Firebase hosting.

The current Azure Pipeline documentation is missing some key points:
- Caching of the packages
- How to package and publish the build artifact
- How to tag the build artifact (so release pipelines can subscribe to packages of a certain tag)

**Comment by isaacplmann** [comment]
None of our other CI workflows handle publishing or archiving. I'm going to close this, unless there is a compelling reason why Azure needs this more than other CI providers.
