### ISSUE TITLE
@nx/cypress@16.10.0 auto-selects incorrect tsconfig.json file

### ISSUE THREAD

**Issue by bjsawyer** [nrwl/nx#20802]
### Current Behavior

When an app/lib has `tsconfig.json` files in both `{project root}/tsconfig.json` and `{project root}/cypress/tsconfig.json`, the `{project root}/tsconfig.json` is automatically used when running component tests.

### Expected Behavior

`{project root}/cypress/tsconfig.json` should be automatically used for component tests.

### GitHub Repo

https://github.com/bjsawyer/cypress-bug-repro/tree/main

### Steps to Reproduce

1. Clone repo
2. `npm i`
3. `npx nx run-many --target=build --all=true`
4. `npx nx component-test cypress-bug-repro`
5. Test passes, but it **shouldn't**

The test should fail because the component it's testing displays dummy text [exported from the ](https://github.com/bjsawyer/cypress-bug-repro/blob/main/apps/cypress-bug-repro/src/app/app.component.ts#L2)`@cypress-bug-repro/utils` lib, but the `apps/cypress-bug-repro/cypress/tsconfig.json` file overwrites the `"paths"` object [to be empty](https://github.com/bjsawyer/cypress-bug-repro/blob/main/apps/cypress-bug-repro/cypress/tsconfig.json#L9). This proves that the `apps/cypress-bug-repro/tsconfig.json` file is used instead, whereas Cypress should use `apps/cypress-bug-repro/cypress/tsconfig.json`.

### Nx Report

```shell
Node   : 18.18.2
OS     : darwin-arm64
npm    : 9.8.1

nx                 : 16.10.0
@nx/js             : 16.10.0
@nx/jest           : 16.10.0
@nx/linter         : 16.10.0
@nx/workspace      : 16.10.0
@nx/angular        : 16.10.0
@nx/cypress        : 16.10.0
@nx/devkit         : 16.10.0
@nx/eslint-plugin  : 16.10.0
@nrwl/tao          : 16.10.0
@nx/webpack        : 16.10.0
typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This causes issues when we need to do Cypress-specific configuration in the `tsconfig`.

**Comment by bjsawyer** [comment]
Let me know if any additional info is needed or if there's anything I can do to help with this one.

**Comment by mandarini** [comment]
Hi there @bjsawyer ! Thanks for filing an issue! I am not sure what is wrong here, but can you please retry with the latest version? There has been a great number of big changes between 16.10 and 17.2 which could be reflected here!
