### ISSUE TITLE
Connection refused when creating React Express app out-of-the-box

### ISSUE THREAD

**Issue by jpreecedev** [nrwl/nx#2080]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

## Expected Behavior

When creating a new React Express app out of the box, when loading the browser, an API request to `/api` should return a greeting

## Current Behavior

The request fails with the following error

```
[HPM] Error occurred while trying to proxy request /api from localhost:4200 to http://localhost:3333 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /api from localhost:4200 to http://localhost:3333 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

## Failure Information (for bugs)

Connection refused

### Steps to Reproduce

Use `npx create-nx-workspace@latest` to create a React Express app (I used CSS for styles)
Run `yarn start`
Hit the browser (localhost:4200)
Notice the error in the terminal both in the browser and in bash

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context

Using latest everything, Macbook Pro 2019 top specs, Catalina.

**Comment by mbriggs** [comment]
Thank you for the bug report, we'll look into it :)

**Comment by jaysoo** [comment]
Hi @jpreecedev, you need to serve both api and client apps.

```
yarn serve api
yarn serve demo
```

We don't start both with `nx serve` or `yarn start` currently, but we can do that in a future release.

Let me know if this workaround fixes your issue.

**Comment by jpreecedev** [comment]
Thanks, works fine.  For me it was `yarn start api` rather than `yarn serve api`.  A nice feature would be to get the CLI to output some basic instructions on what commands to run.

Appreciate the help!
