### ISSUE TITLE
Found default #other-links style and id in template 

### ISSUE THREAD

**Issue by KhizerRehan** [nrwl/nx#20807]
### Default Template has unncessary ID "#other-links"

While generating default template found unnecessary style/id being added different under following 
 - <framework>/generators/application/files

Not sure if it is added INTENTIONAL? if it is than this issue can be closes otherwise a small PR can be added as a good contribution :)

<img width="1115" alt="default-id" src="https://github.com/nrwl/nx/assets/17727069/6a5e4b8a-10f5-4ce3-af2f-26277878c426">

Provide any additional details here as needed.

**Comment by AgentEnder** [comment]
I don't think its hurting anything, and its not wrong to be there, so I'm inclined to say that its not worth chaning. That file is afterall going to be deleted immediately 85%+ of the time.
