### ISSUE TITLE
@nx/vite serve target does not pull the mode option from the specified buildTarget after Nx v17.2.x.

### ISSUE THREAD

**Issue by viniciusbsneto** [nrwl/nx#20816]
### Current Behavior

@nx/vite `serve` target does not pull the `mode` option from the specified `buildTarget` after Nx v17.2.x.

![image](https://github.com/nrwl/nx/assets/17788722/111d979c-c806-487b-9af8-a6b54a761e46)

### Expected Behavior

@nx/vite `serve` target pulls the `mode` option from the specified `buildTarget`.

### GitHub Repo

https://github.com/viniciusbsneto/nx-vite-serve-mode-issue

### Steps to Reproduce

1. Run `nx serve:my-app:sandbox`.
1. Verify that `{ command: 'serve', mode: 'development' }` is console logged instead of `{ command: 'serve', mode: 'sandbox' }`.

### Nx Report

```shell
Node   : 18.17.0
   OS     : linux-x64
   npm    : 9.6.7

   nx (global)        : v17.2.5
   nx                 : v17.2.5
   @nx/js             : v17.2.5
   @nx/linter         : v17.2.5
   @nx/eslint         : v17.2.5
   @nx/workspace      : v17.2.5
   @nx/cypress        : v17.2.5
   @nx/devkit         : v17.2.5
   @nx/eslint-plugin  : v17.2.5
   @nx/react          : v17.2.5
   @nrwl/tao          : v17.2.5
   @nx/vite           : v17.2.5
   @nx/web            : v17.2.5
   typescript         : 5.2.2
```

### Failure Logs

```shell
viniciusbsneto in my-organization on  main ❯ nx run my-app:serve:sandbox

> nx run my-app:serve:sandbox

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
{ command: 'serve', mode: 'development' }
{ command: 'serve', mode: 'development' }
  ➜  Local:   http://localhost:4200/
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I did a quick investigation and I believe the issue could have been introduced by PR #20708.

`mode` used to be passed as `extraArgs` in both places as you can see in the diff screenshot. Now it's only being passed as `otherOptions`. I think it should be passed as `serverOptions` as well or `serverOptions` only. I say that because a workaround I've found is to setup `mode` in a configuration for the `serve` target directly. If we look at the executor code, the `serve` target `mode` is returned by `getViteServerOptions` and passed to the `mergeConfig` `server` object instead of the outter object.
![image](https://github.com/nrwl/nx/assets/17788722/2eda573e-8a61-47a0-9616-130d3bd07b6e)

If my suspicion turns out to be true and I can get some help to understand which options should really be Vite extra args, I'd be willing to submit a PR.

**Comment by mandarini** [comment]
@viniciusbsneto thanks for submitting this issue, I'll look into it. In the meantime, can you take a look here and see if it's related to your issue?
https://nx.dev/recipes/react/use-environment-variables-in-react#environment-variable-conflict-between-nx-and-vite

**Comment by viniciusbsneto** [comment]
> @viniciusbsneto thanks for submitting this issue, I'll look into it. In the meantime, can you take a look here and see if it's related to your issue? https://nx.dev/recipes/react/use-environment-variables-in-react#environment-variable-conflict-between-nx-and-vite

Sure! It looks like I'm in line with the configurations setup recommend by Nx:
```
"configurations": {
  "development": {
    "mode": "development"
  },
  "production": {
    "mode": "production"
  },
  "staging": {
    "mode": "staging"
  },
  "my-other-mode": {
    "mode": "my-other-mode"
  }
}
```
![image](https://github.com/nrwl/nx/assets/17788722/e598b3aa-f446-4ee8-b0ba-983ad337cc1d)
![image](https://github.com/nrwl/nx/assets/17788722/5c7b9ac8-9de6-4014-9555-1abcf0682d38)

> `mode` was added to `serve` target configurations as a workaround.

**Comment by mandarini** [comment]
Ok, found the issue. It was not the `extraArgs`. It's that I'm not reading the mode from here: https://github.com/nrwl/nx/blob/master/packages/vite/src/executors/dev-server/dev-server.impl.ts#L31, from `buildTargetOptions`. I fixed that now! :)

**Comment by viniciusbsneto** [comment]
> Ok, found the issue. It was not the `extraArgs`. It's that I'm not reading the mode from here: https://github.com/nrwl/nx/blob/master/packages/vite/src/executors/dev-server/dev-server.impl.ts#L31, from `buildTargetOptions`. I fixed that now! :)

Nice! That was my second guess since Vite tells us that `mode` is indeed from `SharedOptions` and not `ServerOptions`. But I wasn't sure where it was coming from. So the workaround worked because `mode` comes from `otherOptions` (returned by `getServerExtraArgs(options)`) when set in the `serve` target. But since `buildTarget` wasn't being passed to `getServerExtraArgs` besides the `serve` target `options`, it wasn't able to read its `mode`. It makes total sense!

Thanks, @mandarini! I wish I had been able to submit that fix but at least I've learned a lot! Is there any source material other than the official docs you'd recommend to get deeper into Vite? I'd like to be more active contributing to this executor.

**Comment by mandarini** [comment]
@viniciusbsneto thanks! Not really, and we'll be moving away from executors soon, this is why we're trying to keep the logic in them at minimum. It's best to configure your project at the `vite.config.ts` level rather than the executor options!

**Comment by viniciusbsneto** [comment]
> @viniciusbsneto thanks! Not really, and we'll be moving away from executors soon, this is why we're trying to keep the logic in them at minimum. It's best to configure your project at the `vite.config.ts` level rather than the executor options! To keep as close to the original/native vite experience as possible!

> and we'll be moving away from executors soon
Good to know! Then I won't be spending too much energy on that. Thanks!
