### ISSUE TITLE
@nx/nuxt not found in npm

### ISSUE THREAD

**Issue by rahulswaminathan** [nrwl/nx#20814]
### Current Behavior

I'm trying to create a NuxtJS Nx workspace using `npx create-nx-workspace@latest`. After selecting VueJS as the stack and Nuxt as the framework, Nx is unable to fetch `@nx/nuxt` package from npm.

### Expected Behavior

Successfully create a NuxtJS Nx integrated monorepo.

### Steps to Reproduce

1. `npx create-nx-workspace@latest`
2. Where would you like to create your workspace? · `mynuxtmonorepo`
3. Which stack do you want to use? · `vue`
4. Integrated monorepo, or standalone project? · `integrated`
5. Application name · `mynuxtmonorepo`
6. What framework would you like to use? · `nuxt`
7. Test runner to use for end to end (E2E) tests · `cypress`
8. Default stylesheet format · `scss`
9. Enable distributed caching to make your CI faster · `No`
10. Open the log file and you should see the failure logs mentioned under **Failure Logs** below

### Nx Report

```shell
npx nx report    

 >  NX   Could not find Nx modules in this workspace.

   Have you run npm/yarn install?


Note: I am unable to to get the nx report from mynuxtmonorepo as it depends on @nx/nuxt. As npm install is unable to find the dependency, it gives the above error.
```

### Failure Logs

```shell
>  NX   Command failed: npm install


npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nx%2fnuxt - Not found
npm ERR! 404 
npm ERR! 404  '@nx/nuxt@v17.2.5' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

### Package Manager Version

10.2.4

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

1. `npx create-nx-workspace@latest --preset=nuxt` gives the same result.
2. Searching for `@nx/nuxt` in [npmjs.com](url) does not return anything. 
<img width="318" alt="image" src="https://github.com/nrwl/nx/assets/11411435/788e92ea-671c-43a0-9bb6-2184ce7711db">

3. [https://registry.npmjs.org/@nx%2fnuxt](url) returns `{"error":"Not found"}`

**Comment by anton-liam** [comment]
same issue.

Why not release the @nx/nuxt package and say nuxt is supported?

**Comment by jaysoo** [comment]
Hi, sorry the Nuxt option was not supposed to be in the release. Nx 17.2.6 fixes this issue, and we'll work on a proper release for `@nx/nuxt` soon.

**Comment by DanielUsupov** [comment]
@jaysoo Do we have an issue link for @nx/nuxt release progress?
