### ISSUE TITLE
Renaming/Moving NextJS library with `@nx/workspace:move` doesn't work for the server import path

### ISSUE THREAD

**Issue by michalvadak** [nrwl/nx#20821]
### Current Behavior

When renaming/moving NextJS library with `@nx/workspace:move` only `@org/library-1` import path is changed. 

The `@org/library-1/server` stays the same.

### Expected Behavior

When renaming/moving NextJS library with `@nx/workspace:move` both import paths `@org/library-1` and `@org/library-1/server` should be changed.

### Steps to Reproduce

1. Generate NextJS library `nx g @nx/next:library library-1 --directory=libs/library-1`
2. Rename it `nx g move --projectName library-1 --newProjectName library-2 --destination libs/library-2`

### Nx Report

```shell
Node   : 20.10.0
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx (global)        : 17.2.3
   nx                 : 17.2.3
   @nx/js             : 17.2.3
   @nx/jest           : 17.2.3
   @nx/linter         : 17.2.3
   @nx/eslint         : 17.2.3
   @nx/workspace      : 17.2.3
   @nx/devkit         : 17.2.3
   @nx/eslint-plugin  : 17.2.3
   @nx/next           : 17.2.3
   @nx/playwright     : 17.2.3
   @nx/react          : 17.2.3
   @nrwl/tao          : 17.2.3
   @nx/web            : 17.2.3
   typescript         : 5.2.2
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by alexandr2110pro** [comment]
Hey Nx Team! Pretty annoying thing. Can you give us ETA on the fix?
