### ISSUE TITLE
How to handle image assets in React Library

### ISSUE THREAD

**Issue by stramel** [nrwl/nx#2084]
I have scaffolded a React Library and a Next.js app using the generators. I am wanting to use a svg asset directly in a component but I'm unsure how to import/reference it. In CRA, I was able to do something like `import { ReactComponent as MySVG } from 'path/to/my/file.svg'`

**Comment by AdamVig** [comment]
Duplicate of #1931.

**Comment by stramel** [comment]
Hmmm... This is related but normally a React application has webpack config. I don't know how that would work with the library since the library has to be able to work in each application's webpack config.

**Comment by AdamVig** [comment]
With the approach used in #1964, SVG files would be converted into JavaScript/TypeScript files that export standard React components. This is a mental shift: the SVG files would no longer be "assets" in the normal sense, but would instead be part of the application just like any other React components.

The library would only be exporting JavaScript/TypeScript files, so applications consuming the library would not have to have any special Webpack configurations.

**Comment by stramel** [comment]
Alright, so in this setup the application wouldn't be handling the SVG files directly anymore, correct?

**Comment by AdamVig** [comment]
Correct, at least based on #1964 and [the SVGR docs](https://www.smooth-code.com/open-source/svgr/docs/getting-started/).

**Comment by stramel** [comment]
Thank you for the explanation. I will close this in hopes that #1964 gets merged soon.

**Comment by stramel** [comment]
@AdamVig #1964 was merged and released but appears to only target apps.

I am wanting to have a library called `@stramel/icons` which would export all the React Component versions of my SVGs.

**Comment by AdamVig** [comment]
@stramel Sorry, I thought that PR would make it possible to embed SVGs in React libraries. I need that functionality as well.

**Comment by stramel** [comment]
@AdamVig I'm wondering if the react lib just needs the custom type since the app handles the bundling?

**Comment by stramel** [comment]
Appears that works. I re-created the react lib for it which added the correct typing to the tsconfig. I'm still unable to get the app to work with the svg files but that should be under #1931. Closing again.

My new `tsconfig.json` looks like:

```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "jsx": "react",
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "types": ["node", "jest"]
  },
  "files": [
    "../../node_modules/@nrwl/react/typings/cssmodule.d.ts",
    "../../node_modules/@nrwl/react/typings/image.d.ts"
  ],
  "include": ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx"]
}
```

**Comment by sophiestix** [comment]
In our case we would like to handle png files in React components in a React library that gets published with the `--publishable` flag. Right now we get an error from rollup: `Error: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)`.

What would be the best approach?
- is it enough to just install and --save-dev a rollup-plugin
- create our own rollup config with plugins (maybe even webpack)?
- or any hints?

**Comment by jaysoo** [comment]
@sophiestix Hi 👋 we currently don't have the same asset handling available for publishable libraries. I suggest either using an external CSS file to handle images, or alternatively we are working on better asset handling in a future release (soon).

**Comment by sophiestix** [comment]
Thank you @jaysoo for the quick response! 🤗

**Comment by jbojcic1** [comment]
@stramel did you mange to do this? If yes how?

> I am wanting to have a library called `@stramel/icons` which would export all the React Component versions of my SVGs.

**Comment by trumbitta** [comment]
> @sophiestix Hi 👋 we currently don't have the same asset handling available for publishable libraries. I suggest either using an external CSS file to handle images, or alternatively we are working on better asset handling in a future release (soon).

Oh noes! Any news about it?

**Comment by stramel** [comment]
> @stramel did you mange to do this? If yes how?
> 
> > I am wanting to have a library called `@stramel/icons` which would export all the React Component versions of my SVGs.

Yep, I sure did!

my `repo/libs/icons/src/index.ts` contains one of these lines for each icon.

`export { ReactComponent as Activity } from './lib/icn_activity.svg'`

I can then just import using `import { Activity } from '@stramel/icons'`

**Comment by trumbitta** [comment]
FYI I got it to work with a custom rollup config:

```
/* eslint-disable @typescript-eslint/no-var-requires */
module.exports = (config) => {
  const svgr = require('@svgr/rollup').default;
  const url = require('@rollup/plugin-url');

  console.dir(config, { depth: null });

  return {
    ...config,
    plugins: [
      ...config.plugins,
      url(),
      svgr({
        svgo: false,
        ref: true,
        titleProp: true,
      }),
    ],
  };
};
```

I really hope nx will add this in the near future as this is the second custom config I'm having for adding SVGR support (the first one is a custom webpack config for StoryBook).

**Comment by imcvakt** [comment]
@trumbitta I'm currently trying to create a publishable lib with react and @fluentui/react, but I'm facing issues with theirs svgs as well.

Can you explain-me or provide more details with that approach you have done?

**Comment by Bielik20** [comment]
I see issue is closed but I feel like it side tracked to handling icons/SVGs. Still title is "How to handle **image** assets in **React Library**" and this is exactly what I have problem with.

When doing stuff like that:
```ts
import image from './sample-image.jpg';
```

Doesn't matter the size, this image gets bundled inline to library dist code (works fine for app bundler). I get why this happens - we do not know what configuration will be used to bundle final app. Still I have to ask is there a better way? Library could inform that in order to use it one needs to use some assets bundling plugins etc.

If there is no other way, perhaps we could at least update docs: https://nx.dev/latest/react/guides/adding-assets-react to inform about different behaviour with libs.

**Comment by cyrus-za** [comment]
I feel like this issue should be opened again until [this](https://github.com/nrwl/nx/issues/2084#issuecomment-589716850) comment from @jaysoo changes. 

Just like @trumbitta I too had to create a custom config to handle svgs for both rollup and storybook. I also had to do it for jest. See #4850 and #2859

**Comment by dommyboy** [comment]
please reopen this issue.. this is insane!

**Comment by dommyboy** [comment]
@trumbitta you are a legend

**Comment by owen26** [comment]
This thread should be reopened as it's handling a totally different scenario that bundling SVG in NX libs (NOT apps)

**Comment by zeilsell-user1** [comment]
It's been over a year and this is still closed? How do I handle image assets in a react library?

**Comment by Shaglock** [comment]
> It's been over a year and this is still closed? How do I handle image assets in a react library?

I think it was recently fixed

https://github.com/nrwl/nx/pull/12226

https://github.com/nrwl/nx/issues/6761
