### ISSUE TITLE
Vite - baseHref and deployUrl config not being applied

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#20848]
### Current Behavior

I have an application that needs to be served from a specific URL. That means that its resources should also be served from there as well.

With Webpack, I was able to set the `baseHref` and `deployUrl` to control that behavior, but now, with Vite, those properties have no effect. Using the `base` property has no effect either.

### Expected Behavior

One should be able to configure the base path of the application with Vite through `project.json` configuration.

### Steps to Reproduce

1.

### Nx Report

```shell
Node   : 20.10.0
   OS     : linux-x64
   npm    : 10.2.3
   
   nx                 : 17.2.4
   @nx/js             : 17.2.4
   @nx/linter         : 17.2.4
   @nx/eslint         : 17.2.4
   @nx/workspace      : 17.2.4
   @nx/cypress        : 17.2.4
   @nx/devkit         : 17.2.4
   @nx/eslint-plugin  : 17.2.4
   @nx/react          : 17.2.4
   @nrwl/tao          : 17.2.4
   @nx/vite           : 17.2.4
   @nx/web            : 17.2.4
   typescript         : 5.2.2
```

### Package Manager Version

npm 

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Hi there @nemonemi ! Can you please retry with latest version of Nx? It should be fixed. Also, can you please try setting these in your `vite.config.ts`? We're trying to move away from `project.json` and towards configuring tools directly in their config files! Thank you!

**Comment by nemonemi** [comment]
Hi @mandarini ,
thanks for the awesomely quick response!
Sure, would you mind pointing me to the documentation where I could find how to properly configure my vite.config.ts with this use case?

**Comment by nemonemi** [comment]
After exploring the API I found that there is a `base` property on the `defineConfig` of the `vite.config.ts` which, when set, serves the application and its resources from the `base` path.
Still, it would be nice if you could link documentation with this use case here, for future reference.
Thanks!

**Comment by mandarini** [comment]
Here: https://vitejs.dev/config/

It's the configuration for vite! :)
