### ISSUE TITLE
Static images are incorrectly linked using web export

### ISSUE THREAD

**Issue by nwesthoff** [nrwl/nx#20876]
### Current Behavior

I've added an image using `expo-image` and a static `require('../images/broken-image.png')` import. During development this looks fine, however when exporting for web and using `npx serve` (as is recommended by Expo), images are incorrectly resolved.

| development | web export |
| --- | --- | 
| ![image](https://github.com/nrwl/nx/assets/7780722/9cfd36c9-b71d-4d3d-9981-53664a103551) | ![image](https://github.com/nrwl/nx/assets/7780722/21e8bf44-289e-4d42-999e-f4406e1fa818)  | 

### Expected Behavior

For static imports to work consistently across platforms on expo SDK49 and nx 17.2.6. Currently neither iOS or Android suffer the same issue.

### GitHub Repo

https://github.com/nwesthoff/nx-metro-expo-require-image

### Steps to Reproduce

1. run `nx export expo-app`
2. `cd apps/expo-app/dist`
3. `npx serve -p 4000`
4. open [localhost:4000](http://localhost:4000)

### Nx Report

```shell
Node   : 18.18.2
   OS     : darwin-arm64
   npm    : 9.8.1
   
   nx (global)        : 17.2.6
   nx                 : 17.2.6
   @nx/js             : 17.2.6
   @nx/jest           : 17.2.6
   @nx/linter         : 17.2.6
   @nx/eslint         : 17.2.6
   @nx/workspace      : 17.2.6
   @nx/detox          : 17.2.6
   @nx/devkit         : 17.2.6
   @nx/eslint-plugin  : 17.2.6
   @nx/expo           : 17.2.6
   @nx/react          : 17.2.6
   @nrwl/tao          : 17.2.6
   @nx/web            : 17.2.6
   @nx/webpack        : 17.2.6
   typescript         : 5.2.2
```

### Failure Logs

```shell
GET http://localhost:4000/1 404 (Not Found)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Using hermes engine and metro bundler for web and ios

**Comment by xiongemi** [comment]
i update nx to latest and it seems to work?
i submit a pr to your repo: https://github.com/nwesthoff/nx-metro-expo-require-image/pull/1

i run `nx export expo-app` then at dist/apps/expo-app, i run `npx http-server ./`, it seems to work?
