### ISSUE TITLE
nx:run-commands serve does not exit successfully

### ISSUE THREAD

**Issue by rodentskie** [nrwl/nx#20875]
### Description

I use `go` in my own project.
Then in my `serve`:

```
"serve": {
      "executor": "nx:run-commands",
      "options": {
        "cwd": "src/api",
        "command": "gow run main.go"
      }
    },
```

I did use `gow` to have a live-reload every after save. Works fine as I have a graceful shutdown implemented.
But with I exit the program with `Ctrl+C`, it does not gracefully shutdowns the application.

Here is the full `project.json`.

```
{
  "name": "api",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "projectType": "application",
  "sourceRoot": "src/api",
  "targets": {
    "build": {
      "executor": "nx:run-commands",
      "options": {
        "cwd": "src/api",
        "command": "go build -o ../../dist/packages/api ./main.go"
      }
    },
    "serve": {
      "executor": "nx:run-commands",
      "options": {
        "cwd": "src/api",
        "command": "gow run main.go"
      }
    },
    "test": {
      "executor": "nx:run-commands",
      "options": {
        "cwd": "src/api",
        "command": "go test"
      }
    },
    "e2e": {
      "executor": "nx:run-commands",
      "options": {
        "cwd": "src/api",
        "command": "go test"
      }
    }
  },
  "tags": []
}

```

### Expected Behavior

Serve

```
➜ nx serve api

> nx run api:serve

[gow] unable to read terminal state: inappropriate ioctl for device
Server listening on port 8080
^C
```

Build

```
➜ nx build api

> nx run api:build


 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target build for project api (445ms)
 
```

Serve should also output
```
 NX   Successfully ran target build for project api (445ms)
```
After terminating the program.

### GitHub Repo

[Link](https://github.com/nrwl/nx-recipes/tree/main/go)

### Steps to Reproduce

1. Clone the repo
2. cd go/
3. npm ci
4. nx serve api
5. Hit ctrl+c; no successful exit message
6. If you run build; end with success.

### Nx Report

```shell
nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.19.0
   OS     : linux-x64
   pnpm   : 8.12.1
   
   nx (global)    : 17.2.6
   nx             : 17.2.6
   @nx/workspace  : 17.2.6
   @nrwl/devkit   : 17.2.6
   typescript     : 5.3.3
```

### Package Manager Version

pnpm --version 8.12.1

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by rodentskie** [comment]
Might be related to [#13766](https://github.com/nrwl/nx/issues/13766)

**Comment by AgentEnder** [comment]
When you hit ctrl+c or otherwise send a signal to the process to exit, Nx doesn't print more information because it has been killed. There's also not a real benefit to the run end messaging in this case, as there's not info to provide regarding things like cloud output links as long lived tasks aren't cached.

I'm going to close this out as its unlikely for this to change, and it doesn't seem like there are negative impacts that would affect users.
