### ISSUE TITLE
Nx does not minify bundles

### ISSUE THREAD

**Issue by AkshayCloudAnalogy** [nrwl/nx#2087]
## Expected Behavior

`nx build` should create minified files for react app or react publishable library.

## Current Behavior

`nx build` is not creating minified files for react app or react publishable library even if optimization is set to true in workspace.json

### Steps to Reproduce

1. Create a new empty nx workspace using `npx create-nx-worspace@latest test-workspace`.
2. Add react using `yarn add @nrwl/react`
3. Create a react app using `nx g @nrwl/react:app test-app`
4. Create a publishable library using `nx g lib test-lib --publishable`
5. Run build using `nx build`

All the files are created but none of them is minified however on `nx build test-lib` it shows Bundle size, Minified Size and GZipped size but no minified file is created at all.

Please let me know if i am doing anything wrong. Also i think documentation  of deployment and optimization should be improved.

**Comment by AdamVig** [comment]
Try using the `--prod` flag, for example:
```shell
nx build --prod
```

**Comment by mbriggs** [comment]
@AdamVig is correct, --prod should give you minified build artifacts. If it doesn't, feel free to reopen this issue :)

**Comment by AkshayCloudAnalogy** [comment]
@AdamVig @mbriggs 
It is working with the app but not for publishable react library using `nx g lib test-lib --publishable` as there is no production script for that in workspace.json

**Comment by andyjessop** [comment]
`@nrwl/js` also doesn't have the `--prod` flag. Is there a different recommended way of minifying libraries generated with `@nrwl/js:library`?
