### ISSUE TITLE
NodeJs breakpoints stop working after migrating from v17.1.3 to v17.2.5 on Windows

### ISSUE THREAD

**Issue by valtersantosmatosmanulife** [nrwl/nx#20880]
### Current Behavior

Unsure why, but the VSCODE breakpoints stop working after migrating from v17.1.3 to v17.2.5 on Windows
We can see that the breakpoints remain unbound on VSCODE
`launch.json`
    {
      "command": "npm run start:all",
      "name": "Debug All",
      "request": "launch",
      "type": "node-terminal"
    },

### Expected Behavior

Breakpoints should work as before

### Steps to Reproduce

1.  Simple use the following in the lunch.json:
    {
      "command": "npm run start:all",
      "name": "Debug All",
      "request": "launch",
      "type": "node-terminal"
    },
2. Make a NodeJs app in Windows 
3. Try to make a breakpoint

### Nx Report

```shell
(working version, it stops working if we bump nx to 2.5)

   Node   : 20.10.0
   OS     : win32-x64
   npm    : 10.2.5

   nx                 : v17.1.3
   @nx/js             : 17.1.3
   @nx/jest           : 17.1.3
   @nx/linter         : 17.1.3
   @nx/eslint         : 17.1.3
   @nx/workspace      : 17.1.3
   @nx/devkit         : v17.2.5
   @nx/eslint-plugin  : 17.1.3
   @nx/nest           : 17.1.3
   @nx/node           : 17.1.3
   @nx/playwright     : 17.1.3
   @nx/react          : 17.1.3
   @nrwl/tao          : v17.2.5
   @nx/web            : 17.1.3
   @nx/webpack        : 17.1.3
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   nx-stylelint : 17.0.1
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/js@17.1.3
     - @nrwl/js@17.1.3
     - @nx/jest@17.1.3
     - @nrwl/jest@17.1.3
     - @nx/linter@17.1.3
     - @nx/eslint@17.1.3
     - @nx/workspace@17.1.3
     - @nrwl/workspace@17.1.3
     - @nx/eslint-plugin@17.1.3
     - @nrwl/eslint-plugin-nx@17.1.3
     - @nx/nest@17.1.3
     - @nrwl/nest@17.1.3
     - @nx/node@17.1.3
     - @nrwl/node@17.1.3
     - @nx/playwright@17.1.3
     - @nx/react@17.1.3
     - @nrwl/react@17.1.3
     - @nx/web@17.1.3
     - @nrwl/web@17.1.3
     - @nx/webpack@17.1.3
     - @nrwl/webpack@17.1.3
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by mitdc-cd-dylan** [comment]
met same issue, any one can help on this?

**Comment by mandarini** [comment]
possibly related? https://github.com/nrwl/nx/issues/15159

**Comment by tagplus5** [comment]
https://github.com/nrwl/nx/issues/14708

**Comment by valtersantosmatosmanulife** [comment]
Workaround in: [14708 comment](https://github.com/nrwl/nx/issues/14708#issuecomment-1858838470)
