### ISSUE TITLE
nx affected:build is not building any libs using github actions.

### ISSUE THREAD

**Issue by yatendra121** [nrwl/nx#20884]
### Current Behavior

nx affected is not tracking changes of libs for building/publishing using github actions.

### Expected Behavior

nx affected has to track changes of libs using github actions.

### Steps to Reproduce

name: Publish Package

on:
  push:
    tags:
      - v*

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18.x]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      - name: Pnpm Install
        run: pnpm install

      - name: Unit Test
        run: pnpm affected:test --base=origin/main

      - name: App Test
        run: pnpm app:test --base=origin/main

      - name: Build
        run: pnpm affected:build --base=origin/main

      - run: pnpm affected:publish --base=origin/main
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NODE_OPTIONS: '--max-old-space-size=6144'

### Nx Report

```shell
Below is log of running script on CI. 
 > qnx@0.0.8 affected:publish /home/runner/work/qnx/qnx
 > npx nx affected --target=publish --exclude='app,my-lib' "-t" "--base=origin/main"

 >  NX   No explicit --head argument provided, but found environment variable NX_HEAD so using its value as the affected head: 95c64516d7e96cfacf0f37fb6cacbdaa4ae148d7

 >  NX   No projects with targets publish,  for 0 projects were run 

 >  NX   Successfully ran targets publish,  for 0 projects
```

### Package Manager Version

pnpm - latest

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
It sounds like `NX_HEAD` is being set somewhere, where is it being set? Generally changing the base makes sense but HEAD should be left alone.

**Comment by yatendra121** [comment]
@AgentEnder Based on your response, I have added these codes. So it is working now.

- name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

And removed manually tags (like base). then final codes is.

name: Publish Package

on:
  push:
    tags:
      - v*

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18.x]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      - name: Pnpm Install
        run: pnpm install

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - name: Unit Test
        run: pnpm affected:test

      - name: App Test
        run: pnpm app:test

      - name: Build
        run: pnpm affected:build

      - run: pnpm affected:publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NODE_OPTIONS: '--max-old-space-size=6144'

**Comment by yatendra121** [comment]
So i am closing it.
