### ISSUE TITLE
`nx run projectA:build --watch` gets stuck watching its dependency projectB

### ISSUE THREAD

**Issue by Kim716** [nrwl/nx#20886]
### Current Behavior

When using the --watch flag with projectA:build, it starts watching its dependency projectB, but then gets stuck at that point.

This issue is same with this closed issue: https://github.com/nrwl/nx/issues/18480
and is similar with this closed issue: https://github.com/nrwl/nx/issues/9406

### Expected Behavior

Using the --watch flag with projectA:build should watch and build both projectB and projectA simultaneously.

### GitHub Repo

https://github.com/Kim716/nx-watch-issue-demo/tree/main

### Steps to Reproduce

1. Having two projects, where projectA depends on projectB.
2. In the nx.json file, the below code should be set:
```
"targetDependencies": {
    "build": [
      {
        "target": "build",
        "projects": "dependencies"
      }
    ]
  },
```
3. Execute `nx run projectA:build --watch`
4. Observe that the watch process gets stuck on projectB.

### Nx Report

```shell
Node : 16.15.0
   OS   : darwin arm64
   npm  : 8.5.5
   
   nx : 14.1.9
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.9
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.9
   @nrwl/eslint-plugin-nx : 14.1.9
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.9
   @nrwl/js : 14.4.2
   @nrwl/linter : 14.1.9
   @nrwl/nest : Not Found
   @nrwl/next : 14.1.9
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.4.2
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 12.1.1
   @nrwl/web : 14.1.9
   @nrwl/workspace : 14.1.9
   typescript : 4.9.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Kim716** [comment]
Our team is still facing challenges with this issue, so I reopened a new one because I'm not sure how to reopen the original issue at https://github.com/nrwl/nx/issues/18480.

**Comment by mandarini** [comment]
Hi there @Kim716 ! Can you please retry with our latest version? Nx 14 was released almost 2 years ago, and a lot of things have been changed (and fixed) since then.

Do you have any trouble updating to the latest version?

**Comment by Kim716** [comment]
Hi @mandarini! Thanks for your response. Our team has decided to update to the latest version because the issue has been resolved in the latest release. If we encounter any difficulties during the update, we will attempt to find a solution. If we are unable to find one, we will seek your guidance. 🙏 Thanks!

**Comment by mandarini** [comment]
Thank you, that's great to hear! sure uf you encounter any trouble just let us know! I'll be closing this issue now!
