### ISSUE TITLE
Build issues on angular library with scss and inline style

### ISSUE THREAD

**Issue by LcsGa** [nrwl/nx#20898]
### Current Behavior

I have a components library in angular v17 in which every components use inline style with scss.
Every components are a secondary entry point.
In my components I may be using global mixins at the root level.
For each component ng-packagr has an `inlineStyleLanguage` and a `lib#styleIncludePaths` options that has to be passed in order to work as I expect.

### Expected Behavior

Every scss rules should be working within my components once they are packaged and downloaded through npm.
I already posted an issue on angular about it and received answers stating that this is due to @nx/angular:package that doesn't support it. You can find more informations about it [here](https://github.com/angular/angular-cli/issues/26712#issuecomment-1866145485)

### GitHub Repo

https://github.com/LcsGa/angular-sass-issue-26712-nx

### Steps to Reproduce

1. Build the components library
2. Either run the demo where it already throws errors or publish it on npm and use it within another project where scss features (here a mixins for media query) won't work

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.18.2
   OS     : win32-x64
   npm    : 10.2.0
   
   nx                 : 17.1.3
   @nx/js             : 17.1.3
   @nx/jest           : 17.1.3
   @nx/linter         : 17.1.3
   @nx/eslint         : 17.1.3
   @nx/workspace      : 17.1.3
   @nx/angular        : 17.1.3
   @nx/cypress        : 17.1.3
   @nx/devkit         : 17.1.3
   @nx/eslint-plugin  : 17.1.3
   @nx/playwright     : 17.1.3
   @nrwl/tao          : 17.1.3
   @nx/web            : 17.1.3
   @nx/webpack        : 17.1.3
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   ngxtension : 1.6.2
```

### Package Manager Version

npm@10.2.0

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

You can find another issue I first opened on angular as I thought it was related to it => https://github.com/angular/angular-cli/issues/26712

**Comment by santoshyadavdev** [comment]
Just for info this change is not backward compatible our libs is on Angular 13.2 and we are trying to upgrade to Nx 17.2

**Comment by LcsGa** [comment]
Hi! Just to add some precisions, here is an example of the issue I face:
- I have a `_responsive.scss` partial file, with responsive mixins within it
![image](https://github.com/nrwl/nx/assets/58547290/4661406c-5333-42ea-8903-26fab65f81aa)
- In secondary entry points (eg. icon) sometimes I wanna `@use` this partial file to `@include` some of my mixins within the inline style of my component
![image](https://github.com/nrwl/nx/assets/58547290/46714029-70bc-4893-9516-17b894829ad8)
- To do so, the root `ng-package.json` of my lib has the options 
```json
"inlineStyleLanguage": "scss",
"assets": ["./assets", "./styles"],
```
Every secondary entry points that needs the `responsive` partial has this option within its own `ng-package.json` 
```json
"lib": {
  "styleIncludePaths": ["../styles"]
}
```
- my `tsconfig.base.json` registers each SEP within the `paths` array (but not the lib itself)
```json
  "paths": {
    "@kw/components/icon": ["libs/components/icon/src/index.ts"],
  }
```

=> When I serve my demo app, using the lib errors like this are thrown:
![image](https://github.com/nrwl/nx/assets/58547290/d9531781-8ba5-412e-8f2d-87dcddfded35)

**Comment by leosvelperez** [comment]
hey @santoshyadavdev!

> Just for info this change is not backward compatible our libs is on Angular 13.2 and we are trying to upgrade to Nx 17.2

Please note Nx 17 is not compatible with Angular v13, so that change is not expected to work with that version of Angular. You can check Angular and Nx compatibility at https://nx.dev/nx-api/angular/documents/angular-nx-version-matrix#nx-and-angular-version-compatibility-matrix.

**Comment by santoshyadavdev** [comment]
@leosvelperez thanks for sharing this, I thought Nx and version Angular version does not matter, but anyways the `~` support in scss is dropped, anyways to bring it back, or do we have any other option?

**Comment by leosvelperez** [comment]
The latest version of Nx supports the LTS versions of Angular. Angular v13 has been out of the LTS support for a bit now.

`ng-packagr` itself dropped the support for that ([in Angular v15](https://github.com/ng-packagr/ng-packagr/commit/b1ebee34c7c89cb3d91cb49c74b9c013e84da125#diff-924be34791b3ffddb16d1a303f5e9e0f1d3b59596dbf7a777bf1d02287138dfb)) because it was a non-standard resolution. Since the current lowest version in LTS is Angular v15, that means no LTS version of Angular supports it, and therefore, Nx doesn't either. It was part of our adjustments code only because `ng-packagr` had it.

**Comment by santoshyadavdev** [comment]
Thanks @leosvelperez, yeah we know, somehow we are in weird situation we have Nx 17 and Angular 13, we will move to angular executors for our publishable libs for time being and use the nx executor after Angular 15, where we can remove `~`
