### ISSUE TITLE
Code scaffolding to generate services etc on folder libs

### ISSUE THREAD

**Issue by jeffkenz89** [nrwl/nx#209]
ng generate service component-name --app=myapp/service 
will generate on app folder  but how to generate service on libs folder?

ng generate service component-name --app=libs/name/service(failed)

**Comment by jimdubbs** [comment]
as far as the CLI is concerned, libs are "apps". pass the name of your lib to the --app argument.

**Comment by jeffkenz89** [comment]
it's not on apps folder but lib folder @jimdubbs 
![image](https://user-images.githubusercontent.com/21219550/35182224-1b476e62-fe03-11e7-988b-6483be27ba18.png)

**Comment by vsavkin** [comment]
Given this:
```
apps/
  myapp
libs/
  mylib
```

You can generate a service like this: 
```
ng generate service service-name --app=mylib
```
