### ISSUE TITLE
Output format for eslint is not respected

### ISSUE THREAD

**Issue by atifsyedali** [nrwl/nx#2091]
Specifying output format (e.g. "json") is not respected. Not sure why this line exists:

https://github.com/nrwl/nx/blob/f28d94162d56c1fbf50ef689953fcb30bd95bb9d/packages/linter/src/builders/lint/lint.impl.ts#L15

**Comment by zodiac1214** [comment]
is there a way to pass eslint/tslint arguments in nx? something like `nx lint mylib1 -- --fix --format=json --outputFile=some.file`

**Comment by rarmatei** [comment]
`outputFile` and `format` are now supported in Nx: https://nx.dev/angular/cli/lint

please update to latest and try again! I'll close this for now.
