### ISSUE TITLE
@nx/aws-lambda deprecation?

### ISSUE THREAD

**Issue by DanielKucal** [nrwl/nx#20913]
### Current Behavior

I think there's some mistake going on here:
Package [@nrwl/aws-lambda](https://www.npmjs.com/package/@nrwl/aws-lambda) is deprecated in favor of @nx/aws-lambda
<img width="803" alt="image" src="https://github.com/nrwl/nx/assets/8938562/40da9a59-4a88-48d2-b4fb-e7f0ac9a47d8">
But package [@nx/aws-lambda](https://www.npmjs.com/package/@nx/aws-lambda) is even more deprecated:
<img width="1015" alt="image" src="https://github.com/nrwl/nx/assets/8938562/7dedc2b3-cec8-45fd-a17d-34d3e1e76e27">

While both are updated 2-3 days ago.

### Expected Behavior

I think the intent is to deprecate @nrwl/aws-lambda in favor of @nx/aws-lambda, so it should be marked properly as @nx/aws-lambda is now.

### Steps to Reproduce

1. `npm i -D @nx/aws-lambda`

### Nx Report

```shell
% nx report

 >  NX   Running global Nx CLI with PNPM may have issues.

   Prefer to use "pnpm" (https://pnpm.io/cli/exec) to execute commands in this workspace.
    TIP  create a shortcut such as: alias pnx="pnpm nx --"
   


 >  NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : darwin-arm64
   pnpm   : 8.12.0
   
   nx                 : 17.1.3
   @nx/js             : 17.1.3
   @nx/jest           : 17.1.3
   @nx/eslint         : 17.1.3
   @nx/workspace      : 17.1.3
   @nx/angular        : 17.1.3
   @nx/devkit         : 17.1.3
   @nx/esbuild        : 17.1.3
   @nx/eslint-plugin  : 17.1.3
   @nx/node           : 17.1.3
   @nx/playwright     : 17.1.3
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @nrwl/aws-lambda : 17.2.2
   @nx-bun/nx       : 1.2.0
```

### Failure Logs

```shell
% npm i -D @nx/aws-lambda    
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/aws-lambda@17.2.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by DanielKucal** [comment]
Additionally, @nx/aws-lambda has a dependency on @nrwl/aws-lambda

```
 % pnpm add -D @nx/aws-lambda --force
 WARN  using --force I sure hope you know what you are doing
 WARN  deprecated @nx/aws-lambda@17.2.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @nrwl/aws-lambda@17.2.3

This error happened while installing the dependencies of @nx/aws-lambda@17.2.3

The latest release of @nrwl/aws-lambda is "17.2.2".

Other releases are:
  * next: 16.7.0-beta.1

If you need the full list of all 33 published versions run "$ pnpm view @nrwl/aws-lambda versions".
Progress: resolved 1593, reused 1534, downloaded 0, added 0

```

**Comment by iababio** [comment]
**Same issue here**:
npx create-nx-workspace@latest my-functions --preset=@nx/aws-lambda 

Node v18.17.1

***Error log***:
 >  NX   Command failed: npm install

   Pass --verbose to see the stacktrace.


npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/aws-lambda@17.2.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in: /Users/ababio/.npm/_logs/2023-12-25T20_27_46_821Z-debug-0.log

**Comment by jaysoo** [comment]
This is fixed now. Note that the package `@nx/aws-lambda` will no longer be supported moving forward. It is just a collection of generators so you could easily replace it with your own plugin.

The code is under the `17.2.3` tag: https://github.com/nrwl/nx-labs/tree/17.2.3/packages/aws-lambda
