### ISSUE TITLE
Nx Storybook interaction tests documentation page link broken

### ISSUE THREAD

**Issue by sashafirsov** [nrwl/nx#20924]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/nx-api/storybook/generators/configuration

### Additional context or description

The link [Nx Storybook interaction tests documentation page](https://nx.dev/packages/storybook/documents/interaction-tests) is broken. Perhaps should point to one of
* https://nx.dev/recipes/storybook/storybook-interaction-tests
* https://blog.nrwl.io/storybook-interaction-tests-in-nx-135fdaabc944

**Comment by FrozenPandaz** [comment]
This seems to have been fixed. The link directly navigates to https://nx.dev/recipes/storybook/storybook-interaction-tests#setup-storybook-interaction-tests
