### ISSUE TITLE
Option to exclude platform specific external dependencies in task input

### ISSUE THREAD

**Issue by jhecking** [nrwl/nx#20929]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

When configuring the input for a task execution, I would like to _exclude_ certain external dependencies. I.e. instead of including only specific external dependencies using the `{ "externalDependencies": [...] }` setting, I would like to include _all_ external dependencies except one or more explicitly listed dependencies.

## Motivation

We are using Mocha to run unit tests for some of our apps/libraries. Since there is no built-in nx executor for Mocha, nx includes _all_ external dependencies as input for these tasks by default. We are generally ok with that, but there are a few dependencies in our project graph which have platform specific packages. Which of these platform specific packages gets installed depends on where the tests are running. That causes minor differences in the project graph as calculated by nx, which will cause cache misses when using the nx remote cache. In particular, the following list of packages is causing such caching problems in our case:
* `@nx/nx-darwin-arm64` (ironically, these packages include the native implementations of the hashing routines used by nx)
* `@nx/nx-darwin-x64`
* `@nx/nx-freebsd-x64`
* `@nx/nx-linux-arm-gnueabihf`
* `@nx/nx-linux-arm64-gnu`
* `@nx/nx-linux-arm64-musl`
* `@nx/nx-linux-x64-gnu`
* `@nx/nx-linux-x64-musl`
* `@nx/nx-win32-arm64-msvc`
* `@nx/nx-win32-x64-msvc`
* `fsevents` (only gets installed on macOS/darwin)
* `@msgpackr-extract/msgpackr-extract-darwin-arm64`
* `@msgpackr-extract/msgpackr-extract-darwin-x64`
* `@msgpackr-extract/msgpackr-extract-linux-arm`
* `@msgpackr-extract/msgpackr-extract-linux-arm64`
* `@msgpackr-extract/msgpackr-extract-linux-x64`
* `@msgpackr-extract/msgpackr-extract-win32-x64`

Rather than explicitly listing all of the dependencies in the task input (a long list, which might frequently change), it would be better if we could just list these few packages as exceptions to exclude when hashing the external dependencies of a task.

## Suggested Implementation

One option would be to update the `externalDependencies` input to accept either a list of dependencies to include or a list of dependencies to exclude, i.e.

```
export interface ExternalDependenciesInput {
  externalDependencies: {
    include?: Array<string>,
    exclude?: Array<string>
  }
}
```

The existing definition of `externalDependencies: Array<string>` can be mapped to `externalDependencies: { include: Array<string> }` to remain backwards compatible.

Then the Rush hash planner needs to be updated to be able to handle these new config option: https://github.com/nrwl/nx/blob/cbb26cb3683570a245ea53fa84da0907f3072ee3/packages/nx/src/native/tasks/hash_planner.rs#L153-L169

## Alternate Implementations

There are likely various other ways our problem could be solved. Some that come to mind:
* An official nx executor for Mocha that can intelligently determine the right external dependencies. (I assume the jest executor does this but did not check.)
* When comparing the detailed project graph generated on two different machines with different platform specific packages installed (local & CI), I noticed that the only difference in the entries for these packages is whether the package version is included in the name, e.g. `fsevents` package is installed on my local (macOS) machine:
  ```
    "npm:fsevents": {
      "type": "npm",
      "name": "npm:fsevents",
      "data": {
        "version": "2.3.2",
        "packageName": "fsevents",
        "hash": "sha512-xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA=="
      }
    },
  ```
  But same package is _not_ installed in the CI env (on Linux):
  ```
    "npm:fsevents@2.3.2": {
      "type": "npm",
      "name": "npm:fsevents@2.3.2",
      "data": {
        "version": "2.3.2",
        "packageName": "fsevents",
        "hash": "sha512-xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA=="
      }
    },
  ```
  The difference between `npm:fsevents` and `npm:fsevents@2.3.2` seems to be what's causing the cache miss. So maybe for the purpose of calculating the hash the version number part in the name could be ignored?

**Comment by de-don** [comment]
Looking for the same feature, to exclude some libraries from test dependencies for example.

I am suggesting next config:

```
        {
          "externalDependencies": ["!prettier", "!@types/uuid"]
        },

**Comment by miluoshi** [comment]
And supporting `*`-patterns would be helpful as well:
```json
{ "externalDependencies": ["*eslint*", "@typescript-eslint/*"] }
```
