### ISSUE TITLE
NX test passes even when i broke test on purpose

### ISSUE THREAD

**Issue by swierzbicki** [nrwl/nx#20927]
### Current Behavior

Command `nx test`

`app.component.spec.ts` passes even when i broke test on purpose. 

Probably there is an issue with caching. It happens on a new project initilized by NX cli. 

I'm using Jest + Spectator. Maybe this is the reason?

### Expected Behavior

Tests should not use cache when i change files. 

### GitHub Repo

`git@github.com:swierzbicki/nx-jest-spectator.git`

Edit: another repro https://github.com/jaysoo/issue-20927

### Steps to Reproduce

1. Run `nx test` 
2. In `app.component.spec.ts.` change line 23 from `Welcome nx-jest-spectator` to `Welcome nx-jest-spectator 2`
3. Then run `nx test` agaian
4. Test still passes 🟢 

### Nx Report

```shell
Node   : 18.19.0
   OS     : darwin-arm64
   pnpm   : 8.12.1
   
   nx                 : v17.2.5
   @nx/js             : v17.2.5
   @nx/jest           : v17.2.5
   @nx/linter         : v17.2.5
   @nx/eslint         : v17.2.5
   @nx/workspace      : v17.2.5
   @nx/angular        : v17.2.5
   @nx/cypress        : v17.2.5
   @nx/devkit         : v17.2.5
   @nx/eslint-plugin  : v17.2.5
   @nx/playwright     : v17.2.5
   @nrwl/tao          : v17.2.5
   @nx/web            : v17.2.5
   @nx/webpack        : v17.2.5
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @ngneat/spectator : 16.0.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by swierzbicki** [comment]
@jaysoo I hope that bug is reproducible. If not - please let me know. 
Do you know how long this could take? I mean... fixing the issue. It is a first time when i report a bug in Nx :)

**Comment by jaysoo** [comment]
As noted in #20934 , it's not testing specifically, as building is also running into the same issue.

**Comment by jaysoo** [comment]
This issue seems to be affecting root/standalone projects. i.e. when `src` is at the root, instead of something like `apps/myapp/src`

Version `17.2.0-beta.1` is fine and `17.2.0-beta.2` is the first to introduce the regression.

**Comment by swierzbicki** [comment]
@jaysoo For now i just disable the cache `"cache": false` for all tasks. If it's fixed i will enable cache :)
