### ISSUE TITLE
nx/enforce-module-boundaries does not throw an error when using unsupported tags in source project

### ISSUE THREAD

**Issue by mcofko** [nrwl/nx#20922]
### Current Behavior

Hey,

I started using latest version of Nx couple of days ago, and after the initial setup, I took a look into @nx/eslint-plugin library, specifically into @nx/enforce-module-boundaries. After following the guides on the official [Nx.dev website](https://nx.dev/nx-api/eslint-plugin/documents/enforce-module-boundaries) I sadly come to realization that this particular rule doesn't work in my monorepo. I don't get any errors reported in CLI, neither in VS Code.

Monorope currently contains 25+ projects stored inside `packages` folder. I added the following property into all project's `package.json` files:
`"nx": {"tags": ["scope:slot"]},`, with the exception of two projects which contain the following tag value `"tags":["scope:test"]`.

That's how the **root** .eslintrc.js looks like, which lives inside `./packages/myProject-base/configs/`:
```
module.exports = {
	root: true,
	env: {
		browser: true,
		commonjs: true,
		es2021: true,
	},
	extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended', 'prettier', 'plugin:prettier/recommended'],
	plugins: ['@nx/eslint-plugin', 'typescript', '@typescript-eslint', '@nx'],
	globals: {
		Atomics: 'readonly',
		SharedArrayBuffer: 'readonly',
	},
	parser: '@typescript-eslint/parser',
	parserOptions: {
		sourceType: 'module',
		ecmaVersion: '12',
	},
	overrides: [
		{
			files: ['*.ts', '*.js'],
			plugins: ['@nx', '@nx/eslint-plugin'],
			rules: {
				'@nx/enforce-module-boundaries': [
					'error',
					{
						allow: [],
						// update depConstraints based on your tags
						depConstraints: [
							{
								sourceTag: 'scope:core',
								onlyDependOnLibsWithTags: ['scope:core'],
							},
							{
								sourceTag: 'scope:test',
								onlyDependOnLibsWithTags: ['scope:core', 'scope:test'],
							}
						]
					}
				],
			}
		},
	],
};
```
The above config is used in the source project through a simple `require`:
```
const eslintConfig = require('../../node_modules/@my-org/myProject-base/configs/.eslintrc.js');
module.exports = eslintConfig;
```

The source package.json and the linter rule are looking like this:
```
"nx": {
      "tags": ["scope:core"]
  },
  "scripts": {
    "linter": "eslint src test --ext ts"
  },
  "author": "",
  "devDependencies": {
    "@my-org/myProject-base": "*",
    "@my-org/sprite-forge-animation": "*"
  },
  "peerDependencies": {
    "@my-org/myProject-assets": "*",
    "@my-org/myProject-display": "*",
    "@my-org/myProject-easing": "*",
    "@my-org/myProject-pixi": "*",
    "@my-org/myProject-utils": "*",
    "eventemitter3": "4",
    "howler": "2",
    "reflect-metadata": "0"
  },
  "dependencies": {},
``` 

 

### Expected Behavior

As I mentioned above, I changed the **tag** values for "@my-org/myProject-assets" & "@my-org/myProject-display": to **scope:test**, and for this reason I would expect to see CLI failing and warning/errors shown in VS Code.

Am I missing something? Is **tsconfig.json** requiring any other particular settings?
Currently it looks like the  nx/enforce-module-boundaries rule is completely ignored, while all other non-nx linter rules are still working as expected.

### Steps to Reproduce

/

### Nx Report

```shell
Node   : 18.18.2
   OS     : win32-x64
   npm    : 9.8.1

   nx                 : 17.2.6
   lerna              : 8.0.1
   @nx/js             : 17.2.6
   @nx/workspace      : 17.2.6
   @nx/devkit         : 17.2.6
   @nx/eslint-plugin  : 17.2.6
   @nrwl/tao          : 17.2.6
   typescript         : 5.3.2
```

### Failure Logs

```shell
No failure logs to share, as the linter isn't reporting any issues.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by mcofko** [comment]
Adding some additional data, hope this will help figuring out the issue. 
After some trails&erros, I noticed that by adding `nx: {}` to the root **workspace package.json** of my packaged based monorepo, I did start receiving linter errors, but now it's logging errors per each "local" dependency I'm using in my target project.

![image](https://github.com/nrwl/nx/assets/5575435/3f608c85-8fd9-46de-b2dd-3f5637e78f4c)

At least this shows that linter configuration is being picked up, and is configured the "right way" (no spelling mistakes, or usage of incorrect properties).
The project **tags** are also being correctly picked up by **graph** visualizer:

![image](https://github.com/nrwl/nx/assets/5575435/f2ea716d-8db4-4aac-859f-58a572b2b711)

As soon as I remove `nx: {}` from the root **workspace package.json**, and run a **lint** command on one of the projects I receive successful passes again. 

Any ideas what could be going on here? Any suggestion how could I further debug the issue?

**Comment by mcofko** [comment]
Was finally able to resolve the above mentioned issue. For the above linter flag to work as expected it's **required** having a tsconfig.json || tsconfig.base.json file in workspace root, otherwise the linter rule with no be applied correctly -> `target-project-locator.js -> getRootTsConfig()`.

The way how our monorepo is used is to basically contain only libraries. Apps (in our case those are diff types of games) are still used as single repos. Inside the monorepo we have a lib called @myorg/base -> which also contains all the **base configs** (eslint, tsconfig, prettier, babel,...) where then each library "imports" the base configs and extends on it if required. The apps (single repos) are then importing @myorg/base to be able to also extend from base configs.

@JamesHenry  would it be possible to have a fallback lookup into the source project tsconfig if it is not found in the root workspace? Potentially making modifications inside `target-proejct-locator.js -> getRootTsConfig()`?

**Comment by mcofko** [comment]
Hi @meeroslav 

I'm bit tight with time, will try to present the case with the below folder/file tree structure, hopefully this will help:

.
└── RootFolder/
    ├── packages/
    │   ├── configs/
    │   │   └── tsconfigCore.json
    │   ├── display/
    │   │   ├── tsconfig.json  -> extends tsconfigCore.json
    │   │   └── package.json
    │   └── assets/
    │       ├── tsconfig.json  -> extends tsconfigCore.json
    │       └── package.json
    ├── package.json
    ├── package-lock.json
    └── nx.json

At this point for "nx/enforce-module-boundaries" linter rule to work it is required having a **tsconfig.json** on the root level.
A potential solution would be to have a fallback lookup into the **target project** tsconfig.json if it is not found in the root workspace folder.

**Comment by meeroslav** [comment]
Is there a reason why you don't want to have `tsconfig.json` in the root?

Since all `nx` commands run from the root, it's expected the main configurations (tsconfig, jest config, eslintrc... to be there). Omitting this would also block your IDE from running those commands natively.
