### ISSUE TITLE
Package.json files are included as projects when not using npm workspaces/lerna/pnpm

### ISSUE THREAD

**Issue by dschnare** [nrwl/nx#20925]
### Current Behavior

We are in the midst of adopting NX for our monorepo. Our mono repo has several standalone packages with package.json files AND project.json files.

```
packages/
  my-lib/
    package.json -- name "@scope/my-lib"
    project.json -- name "my-lib"
  ...
```

When I use the NX CLI to inspect the graph I notice that "@scop/my-lib" and "my-lib" are in the graph. We are trying to slowly transition over to an integrated monorepo, so we started by transitioning over all targets to project.json in each package.

Interestingly, this automatic package.json inclusion is only occurring for two of our packages, one is an app and the other is a library. I've inspected the package.json for these packages and compared against all of our other packages and there is nothing out of the usual, the same goes with the project.json files; all looks as it should.

Additionally, when we attempt to run `npx nx run my-lib:build` for example, some times it succeeds, other times it reports the failure that "my-lib" cannot be found. If we run it again (or sometimes a few times) then NX eventually finds it.

### Expected Behavior

I would expect to only see "my-lib" in the graph and all its dependencies. We are not using NPM workspaces, Learn, or PNPM. We'd expect only the project.json files to be used to name the projects and to define the targets.

### Steps to Reproduce

1. Create an empty workspace with a "packages" folder
```
mkdir test-workspace
mkdir test-workspace/packages
cd test-workspace
npm init --yes
npm i -D nx@17.2.7
```

2. Create the "nx.json" file in the workspace root
```
{
  "extends": "nx/presets/npm.json",
  "affected": {
    "defaultBase": "master"
  },
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {}
    }
  }
}
```

2. Add two standalone packages to the "packages" folder
```
mkdir packages/my-lib
mkdir packages/my-other-lib

cd packages/my-lib
npm init --yes --scope=@my-org
echo "exports.hello = 'hello'" > index.js

cd ../my-other-lib
npm init --yes --scope=@my-org
npm install ../my-lib
echo "exports.message = require('@scope/my-lib').hello + ' world'" > index.js

cd ../../
```

3. Create `packages/my-lib/project.json`
```
{
  "name": "my-lib",
  "projectType": "library",
  "root": "packages/my-lib/",
  "sourceRoot": "packages/my-lib"
}
```

4. Create `packages/my-other-lib/project.json`
```
{
  "name": "my-other-lib",
  "projectType": "library",
  "root": "packages/my-other-lib/",
  "sourceRoot": "packages/my-other-lib"
}
```

5. Install NX globally
```
npm i -g nx@17.2.7
```

6. Now run `npx nx graph`. See that @my-org/my-lib, @my-org/my-other-lib, my-lib and my-other-lib are all listed as projects.

### Nx Report

```shell
Node   : 18.17.1
OS     : darwin-arm64
npm    : 9.6.7
   
nx         : 17.2.7
@nrwl/tao  : 17.2.7
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I did discover that the cause of this issue was due to the trailing "/" on "project.json#root". Deleting the trailing "/" in all project.json files resolves the issue (only one project is correctly listed).

Having a trailing "/" on "project.json#sourceRoot" does not cause this issue.

**Comment by FrozenPandaz** [comment]
This was resolved. Please open a new issue if you experience this with the latest versions of Nx.
