### ISSUE TITLE
Resume builder error

### ISSUE THREAD

**Issue by Usha19082002** [nrwl/nx#20923]
### Current Behavior

Could not find ".modules.yaml" at "C:\Resume Project\resume Rx\Reactive-Resume-main/node_modules/.modules.yaml"

   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.

### Expected Behavior

'pnpm' is not recognized as an internal or external command,
operable program or batch file.

### GitHub Repo

https://github.com/Usha19082002/resumebuilder

### Steps to Reproduce

1.
'pnpm' is not recognized as an internal or external command,
operable program or batch file.

### Nx Report

```shell
Could not find ".modules.yaml" at "C:\Resume Project\resume Rx\Reactive-Resume-main/node_modules/.modules.yaml"


   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
```

### Failure Logs

```shell
Could not find ".modules.yaml" at "C:\Resume Project\resume Rx\Reactive-Resume-main/node_modules/.modules.yaml"


   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
Can you provide more information? The repo you linked is not using Nx nor pnpm.

1. Are you using pnpm or another package manager?
2. Can you link to a repo or a branch that shows your Nx setup?
