### ISSUE TITLE
centos7 angular build --configuration xxx : path in file replacements does not exist

### ISSUE THREAD

**Issue by sailengsi** [nrwl/nx#20935]
### Current Behavior

![image](https://github.com/nrwl/nx/assets/20767778/03e026ab-039d-42d4-919d-9172cfaf4f4a)

### Expected Behavior

![image](https://github.com/nrwl/nx/assets/20767778/03e026ab-039d-42d4-919d-9172cfaf4f4a)

### Steps to Reproduce

0， create angular project, v17.0.4
1，vim apps/xxxx/project.json
2，targets.build.configurations.production add:
"fileReplacements": [
            {
              "replace": "apps/xxx/src/environments/environment.ts",
              "with": "apps/xxxx/src/environments/environment.prod.ts"
            }
],
3，`centos7` nx build errors
4，local mac is ok

### Nx Report

```shell
![image](https://github.com/nrwl/nx/assets/20767778/03e026ab-039d-42d4-919d-9172cfaf4f4a)
```

### Failure Logs

```shell
![image](https://github.com/nrwl/nx/assets/20767778/03e026ab-039d-42d4-919d-9172cfaf4f4a)
```

### Package Manager Version

pnpm 8.1.1

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by sailengsi** [comment]
When will it be repaired? Currently, it can only be replicated on Linux Centos. I can't use environment variables now
👀

**Comment by Coly010** [comment]
@sailengsi can you retry this with the latest version of Nx (19.6.1)
