### ISSUE TITLE
NX build passes even when i broke files on purpose 

### ISSUE THREAD

**Issue by swierzbicki** [nrwl/nx#20934]
### Current Behavior

Command `nx build`

Build passes even when i broke the app.component.ts file 

Probably there is an issue with caching. It happens on a new project initilized by NX cli.

### Expected Behavior

Build should not use cache when i change files.

### GitHub Repo

git@github.com:swierzbicki/nx-jest-spectator.git

### Steps to Reproduce

1. Run `nx build`
2. Break `app.component.ts`. 
3. Run `nx build` again
4. Build still passes 🟢  

### Nx Report

```shell
Node   : 18.19.0
   OS     : darwin-arm64
   pnpm   : 8.12.1
   
   nx                 : v17.2.5
   @nx/js             : v17.2.5
   @nx/jest           : v17.2.5
   @nx/linter         : v17.2.5
   @nx/eslint         : v17.2.5
   @nx/workspace      : v17.2.5
   @nx/angular        : v17.2.5
   @nx/cypress        : v17.2.5
   @nx/devkit         : v17.2.5
   @nx/eslint-plugin  : v17.2.5
   @nx/playwright     : v17.2.5
   @nrwl/tao          : v17.2.5
   @nx/web            : v17.2.5
   @nx/webpack        : v17.2.5
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @ngneat/spectator : 16.0.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by swierzbicki** [comment]
I think this issue is related with cache itself for all "steps". Previously i reported an issue for tests:
https://github.com/nrwl/nx/issues/20927

But now i discover it happens also for `nx build`.

**Comment by jaysoo** [comment]
@swierzbicki we'll investigate it, do you mind closing this issue or #20927 so we can keep the discussion in one place? It looks like it's not testing or building specifically.

**Comment by swierzbicki** [comment]
@jaysoo Ok :)
