### ISSUE TITLE
 'updateBuildableProjectDepsInPackageJson' is not found in schema

### ISSUE THREAD

**Issue by shanieMoonlight** [nrwl/nx#20947]
### Current Behavior

I recently upgraded Nx to version 17 using the cli.
After doing so none of my apps or libs would build. I keep getting the error  NX   "'updateBuildableProjectDepsInPackageJson' is not found in schema".
I noticed that during the migration to v17 ("updateBuildableProjectDepsInPackageJson": true) added to all of the project.json files.

If I remove this everything builds just fine. 
If I build a new mono-repo  and create some libraries none of the project.json's have the updateBuildableProjectDepsInPackageJson field,  but they do have  "@nx/dependency-checks": "error" in the .eslintrc.json which I've read is a replacement for updateBuildableProjectDepsInPackageJson.

Should I just remove all references to updateBuildableProjectDepsInPackageJson and add "@nx/dependency-checks": "error" in the migrated project?

### Expected Behavior

I expected all libraries and app to build as usual

### Steps to Reproduce

1. Create a library.
2. Add  "updateBuildableProjectDepsInPackageJson": true in the targets.build.options of project.json.
3. Reference the library in an app and try to build the app.

### Nx Report

```shell
*  Executing task: npx nx run deps-test:build 


   ×    1/2 dependent project tasks failed (see below)
   √    1/2 dependent project tasks succeeded [1 read from cache]

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 


> nx run lib1:build:production


 >  NX   'updateBuildableProjectDepsInPackageJson' is not found in schema



 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Ran target build for project deps-test and 2 task(s) they depend on (254ms)

    ×    1/2 failed
    √    1/2 succeeded [1 read from cache]
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by alexanderPastornicky** [comment]
same

**Comment by benjaminbarbe10** [comment]
Hello, I have the same problem as you.

**Comment by JDelladecimas** [comment]
Same here.

**Comment by MGREMY** [comment]
Same

**Comment by lazybobcat** [comment]
In order to solve this issue, follow the documentation https://nx.dev/nx-api/eslint-plugin/documents/dependency-checks to enable dependency checks:

- add the override and rule options to `.eslintrc.json`
- you *may* need to add your project `package.json` in the `lintFilePatterns` if they're excluded
- lint your project and check that the project's `package.json` file is appropriately updated 
- finally, remove the `updateBuildableProjectDepsInPackageJson` configurations and try to build the project

I hope this helps, that solved this issue for me.

**Comment by SerkanSipahi** [comment]
@lazybobcat thanks, this works for me.

**Comment by shanieMoonlight** [comment]
Thanks @lazybobcat. 

@meeroslav I thought I did send you the full report. 
it was just the same line for each lib _NX   'updateBuildableProjectDepsInPackageJson' is not found in schema_

Is there a way to get more detailed info?

**Comment by meeroslav** [comment]
This is what that report looks like (notice the first line):

![Screenshot 2024-01-18 at 22 00 52](https://github.com/nrwl/nx/assets/881612/345064db-ba85-448c-839e-57e3f3c2fdb3)

**Comment by shanieMoonlight** [comment]
I see,  _nx report_ is a command. I didn't know about it.
I'll add that next time.
