### ISSUE TITLE
.nxignore is not used in any non-root directory with a .gitignore

### ISSUE THREAD

**Issue by thislooksfun** [nrwl/nx#20945]
### Current Behavior

If you have a top-level .nxignore file it will not apply to any directory which contains a .gitignore file.

### Expected Behavior

The .nxignore file should apply globally, and should override all .gitignore files, regardless of file structure.

### GitHub Repo

https://github.com/thislooksfun/nx-caching-ignore-bugs

### Steps to Reproduce

1. Take any nx project, new or existing
2. Add a .nxignore file to the root of the project with some rule(s) in it
3. Add an empty .gitignore file anywhere inside one of the nx targets
4. Run a cacheable nx command (with the daemon enabled) against the target with the .gitignore
5. Change a file ignored by the rule from step 2
6. Run the cacheable nx command again
7. The command will execute again, even though it should be a cache hit

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.18.2
   OS     : darwin-x64
   npm    : 9.8.1
   
   nx             : 17.2.7
   lerna          : 6.6.2
   @nx/workspace  : 17.2.7
   @nx/devkit     : 17.2.7
   @nrwl/tao      : 17.2.7
   typescript     : 5.2.2
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This is caused by a couple problems coming together due to the way the nxignore is added to the ignore filter:

https://github.com/nrwl/nx/blob/8a8dbb381ea6ce50d3a5e8ba605bde56dbb22dc2/packages/nx/src/native/watch/watch_config.rs#L37-L43

#### Problem 1:

Due to a bug in the way the `ignore-files` crate currently works internally, calling `add_file` to add more ignore rules to a given path does not apply those rules to any of its children. This means that any rules added to the root of the project by the `.nxignore` file do not propagate down into any subdirectories containing their own .gitignore files. This issue will be fixed by https://github.com/watchexec/watchexec/pull/746.

#### Problem 2:

`ignore-files` assumes that all given ignore rules are hierarchical, with the closest (i.e. deepest) rules taking precedence. This means that even after https://github.com/watchexec/watchexec/pull/746 fixes problem 1 above, the .nxignore file will still not take precedence over the .gitignore tree. In order to make that work as expected, I think fixing that will require implementing some custom priority logic in the watch filterer.

Specifically, I suggest having a separate Filter instance for the `.nxignore` that is checked first. If matching against it returns `Match::None`, then it should fall back to the hierarchical `.gitignore` matcher.

**Comment by Cammisuli** [comment]
thanks @thislooksfun for your investigation and work so far on this! I understand the problem and will do some refactoring to apply your suggestion (and also update the watch-exec library)
