### ISSUE TITLE
Allow absolute path for target outputs 

### ISSUE THREAD

**Issue by khalilou88** [nrwl/nx#20961]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Outputs are relative to the workspaceRoot. But Maven `install phase` create a jar in the local Maven repo outside of the workspace directory by default. And we want the Nx cache to restore this artifact.
Putting the maven local repo inside the workspace solve this problem but we like a solution more generic.

## Motivation

To make Nx more suitable for another language/framework

## Suggested Implementation

Allow absolute path for target outputs

**Comment by AgentEnder** [comment]
The outputs path changing invalidates the cache, so absolute paths would not really work. Imagine something like `/usr/{user}/...`, {user} is different on each dev's machine, thus different project configuration hash

Relative paths are nice, because they should be the same across machines. What would you want to change here?

**Comment by khalilou88** [comment]
Thanks @AgentEnder 

Based on your explanation, I want the outputs to accept an object type with two properties:
```
{
absolutePart: string; 
relativePart: string; 
}
```
AbsolutePart depends on the machine and should be ignored by Nx.
During the graph calculation with graph V2 (inside `CreateNodes` function), we will fill these two properties because they are dynamics.

Example :
```
{
absolutePart: '{options.localRepo}',
relativePart: '{options.outputDirLocalRepo}',
}
```
After `nx show project spring-boot-lib` command the result will be something like this:

```
"options":{
...other options,
"localRepo":"C:\\Users\\khalil\\.m2\\repository",
"outputDirLocalRepo":"\\com\\example\\spring-boot-lib\\0.0.0"
}
```

The `outputDirLocalRepo` change if we change `groupId`, `projectName` (`artifactId` in maven) and `projectVersion`.


@jbadeau @ToppScorer Do you have something to correct or add ?
