### ISSUE TITLE
17.2 broke our MFE remotes with all remotes on same port

### ISSUE THREAD

**Issue by rbirkgit** [nrwl/nx#20974]
### Current Behavior

With 17.2 all remotes now start on the same port when in static mode, but on different ports when in dev mode. This breaks our env and we can no longer update to 17.2 or higher.

### Expected Behavior

We expect a revert of this feature of having all remotes on same port, or an easy way to go back to how it was with 17.1.

### Steps to Reproduce

Have a repo with MFE remotes and update to 17.2

### Nx Report

```shell
Node   : 18.14.0
   OS     : win32-x64
   yarn   : 4.0.1

   nx                 : v17.2.5
   @nx/js             : v17.2.5
   @nx/jest           : v17.2.5
   @nx/linter         : v17.2.5
   @nx/eslint         : v17.2.5
   @nx/workspace      : v17.2.5
   @nx/angular        : v17.2.5
   @nx/cypress        : v17.2.5
   @nx/devkit         : v17.2.5
   @nx/eslint-plugin  : v17.2.5
   @nrwl/tao          : v17.2.5
   @nx/web            : v17.2.5
   @nx/webpack        : v17.2.5
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   ng-mocks : 14.11.0
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

In our hosts proxy config file we have this but cannot figure out how to support different port numbers/path depending on static or dev mode and why we need the static ports remain on different ports, i.e. same as in dev mode.
```
  "/myhost/plugin/billing": {
    "target": "https://localhost.mycompany.com:4203",
    "secure": false,
    "logLevel": "debug",
    "pathRewrite": {
      "^/myhost/plugin/billing": ""
    }
  }
```

**Comment by glp** [comment]
This also happens with react mf

**Comment by smasala** [comment]
@rbirkgit in the `project.json` of the `host` application add the name of the remotes again
```
"serve": {
      "executor": "@nx/react:module-federation-dev-server",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "host-app:build",
        "hmr": true,
        "port": 4200,
        "devRemotes": ["remote-app-name"] // same as in host-app/module-federation.config.ts
      },
```

This then forces the correct port to be pulled as defined in the `remote-app` serve section -> https://github.com/nrwl/nx/blob/11e139c7ec42d77dee96af9bf3afd71bc7f717a2/packages/react/src/executors/module-federation-dev-server/module-federation-dev-server.impl.ts#L277

@leosvelperez is this intentional (did the jump from 16.4.2)?

**Comment by glp** [comment]
This also does not work for projects with dynamic module federation, as the app has no way of knowing if the remote is served via static or devRemote, making it impossible to load the remoteEntry file.

**Comment by kevinriemens** [comment]
This isssue is still present in 19.0.0

**Comment by rbirkgit** [comment]
With 18.2.4+ the old behavior magically came back, with each remote on separate ports. I should have mentioned it. 

Now I am scared trying 19.0 if it's back all on the same port?

**Comment by Coly010** [comment]
Closed as fixed, thanks for raising the issue!
