### ISSUE TITLE
Docs: typo in "Getting Started" command

### ISSUE THREAD

**Issue by yohancourbe** [nrwl/nx#2097]
https://nx.dev/angular/getting-started/getting-started#creating-an-application

the command says

`ng g @nrwl/angular:application myapp`

which I think should be

`nx g @nrwl/angular:application myapp`

**Comment by brandonroberts** [comment]
For a primarily Angular workspace, using the `ng` command is recommended.

**Comment by yohancourbe** [comment]
@brandonroberts ng command will want an angular.json file to work, but if you create a workspace a chose nx-cli there won't be any, and the docs doesn't say you have to chose angular-cli. As a total newbie with NX, I found it confusing.
