### ISSUE TITLE
feat(devkit): extend `ProjectConfiguration` with additional metadata

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#20970]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

`getProjects` or `createProjectGraphAsync` provide contents of `project.json`. 

While building tools (generators/executors/other) it might happen very often that we need to access `package.json` to obtain more info about particular project or even additional configs. 

ATM to obtain this metadata one needs to do additional IO calls to fetch these data + implement caching on its own to reduce IO impact hit.

It would be very helpful if nx api could fetch `package.json` metadata if present with optional config to fetch additional files as well if specified.

## Motivation

Context provided in Description paragraph.

In our particular scenario the use case is to migrate away from lerna to nx / mix of various tech in a monorepo that needs to co-exists.

https://github.com/microsoft/fluentui/pull/30178 

## Suggested Implementation

```ts
import * as devkit from '@nx/devkit';

const projects = devkit.getProjects(devkit.tree);

expect(project['hello-world'].packageJSON.toEqual({name:'@proj/hello-world',dependencies:{},devDependencies:{},bin:{...}})

// ===


const graph = await devkit.createProjectGraphAsync(); 

expect(graph.nodes['hello-world'].data.packageJSON).toEqual({name:'@proj/hello-world',dependencies:{},devDependencies:{},bin:{...}});
```

## Alternate Implementations

optionally one could provide additional files to be fetched if necessary:

```ts
import * as devkit from '@nx/devkit';

const projects = devkit.getProjects(devkit.tree,{metadata:['.eslintrc.json']});

expect(project['hello-world'].packageJSON.toEqual({name:'@proj/hello-world',dependencies:{},devDependencies:{},bin:{...}})
expect(project['hello-world'].metadata.toEqual({'.eslintrc.json':{...}})

// ===


const graph = await devkit.createProjectGraphAsync(); 
expct(graph.nodes['hello-world'].data.packageJSON).toEqual({name:'@proj/hello-world',dependencies:{},devDependencies:{},bin:{...}});
expct(graph.nodes['hello-world'].data.metadata).toEqual({'.eslintrc.json':{...}})
```

```

**Comment by AgentEnder** [comment]
I don't think we would want to go in this direction. There are two separate concerns here:

- `readProjectConfiguration`, `getProjects`, and other methods used in generators
- `ProjectConfiguration` as present in the project graph node's data field.

I'm going to close this issue out, but there is some more explanation for each of these concerns below. Feel free to reach out if this does not feel adequate, and we can discuss more.

### Generators

For the first usage, I'd recommend reading in whichever file you need information from on the tree. In general, we are trying to slim down the generator utils such that using `readProjectConfiguration` and `updateProjectConfiguration` is as easy to use as possible, with the least magic going on, and the least possibility of files getting updated with information that should not be present.

e.g. You wouldn't want a packageJSON field to accidentally end up in `project.json`.

If you need extra info its not hard to get, and its not extra IO calls as we would just be doing them under the hood if we were to update the methods. Also consider that all projects may not have eslintrc's or package.json files, and we would then be doing unnecessaries work in most repos.

My recommendation would something as simple as this in the generator you are working on:

```typescript
const projects = getProjects(tree)
for (const [projectName, project] of projects.entries()) {
  const packageJsonPath = joinPathFragments(project.root, 'package.json');
  const packageJson = tree.exists(packageJsonPath) ? readJson(tree, packageJsonPath) : null;
  // ... do stuff with package json
}
```

### Project Graph

In the case of project graph nodes, we aren't likely to move forward with this either. The format there is largely tailored to what Nx needs to know to operate, hash, and run tasks etc. In this case, my recommendation would be to load the files as needed for the project which you are looking at.

Additionally, we wouldn't parameterize the metadata files to load as the shape of the graph is stable. It isn't recomputed or transformed each time you call the function to create the graph. Its incrementally recomputed based on file changes, and we would want to avoid extra work as things go on.
