### ISSUE TITLE
Unable to build normally using `@nx/js:swc`

### ISSUE THREAD

**Issue by aosnow** [nrwl/nx#20985]
### Current Behavior

![image](https://github.com/nrwl/nx/assets/3865017/76854e8a-2684-4ec0-ada7-7853233fe3cc)

As shown in the figure, when using `@nx/js:swc` for building, a serious issue occurs here. The strategy of `tmp${swcrcPath}` causes the next step of `writeJsonFile > mkdirSync` to fail, as shown in the following figure, because tmpSwcrcPath does not seem like a valid path for a rule.

![image](https://github.com/nrwl/nx/assets/3865017/7154dc67-3139-4643-bdd0-c129be970453)

### Expected Behavior

I hope to be able to use `@nx/js:swc` for building normally.

### Steps to Reproduce

1. Create any `@nx/js:lib` project.
2. Set `@nx/js:swc` as the bundler.
3. Run `nx run xxx:build`.

### Nx Report

```shell
Debugger listening on ws://127.0.0.1:58694/3dbd2da0-cc87-4889-a7a1-e457e5815e9e
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

> nx run util:build

Debugger listening on ws://127.0.0.1:58713/4d9315b5-141c-4f1c-8d8d-ec5831f7c720
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

 >  NX   ENOENT: no such file or directory, mkdir 'tmpE:\netease-lab\typedoc-plugins\libs\util'
                                                                                               
   Pass --verbose to see the stacktrace.                                                       
                                                                                               
Waiting for the debugger to disconnect...                                                      

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Ran target build for project util (4m)

    ×    1/1 failed
    √    0/1 succeeded [0 read from cache]

Waiting for the debugger to disconnect...
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
This should be fixed by #21801
