### ISSUE TITLE
Generated package.json is not having any dependencies

### ISSUE THREAD

**Issue by nanthakumaran-s** [nrwl/nx#20981]
### Current Behavior

I'm using nx version `16.10.0`. In the nx.json, `generatePackageJson` is enabled. After all these the generated package.json haven't coming with any dependency. 

`dist/apps/courses-service`
```json
{
  "name": "courses-service",
  "version": "0.0.1",
  "main": "main.js"
}
```

`nx.json`
```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build", "lint", "test", "e2e"]
      }
    }
  },
  "workspaceLayout": {
    "projectNameAndRootFormat": "as-provided"
  },
  "targetDefaults": {
    "build": {
      "executor": "@nx/webpack:webpack",
      "options": {
        "generatePackageJson": true
      },
      "dependsOn": ["^build"],
      "inputs": ["production", "^production"]
    },
    "test": {
      "inputs": ["default", "^production", "{workspaceRoot}/jest.preset.js"]
    },
    "lint": {
      "inputs": [
        "default",
        "{workspaceRoot}/.eslintrc.json",
        "{workspaceRoot}/.eslintignore",
        "{workspaceRoot}/eslint.config.js"
      ]
    }
  },
  "namedInputs": {
    "default": ["{projectRoot}/**/*", "sharedGlobals"],
    "production": [
      "default",
      "!{projectRoot}/**/?(*.)+(spec|test).[jt]s?(x)?(.snap)",
      "!{projectRoot}/tsconfig.spec.json",
      "!{projectRoot}/jest.config.[jt]s",
      "!{projectRoot}/src/test-setup.[jt]s",
      "!{projectRoot}/test-setup.[jt]s",
      "!{projectRoot}/.eslintrc.json",
      "!{projectRoot}/eslint.config.js"
    ],
    "sharedGlobals": []
  }
}

```

### Expected Behavior

The generated package.json should contain the dependencies for that particular app

### Steps to Reproduce

1. 

### Nx Report

```shell
$ nx report
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 21.5.0
   OS     : darwin-arm64
   npm    : 10.2.4
   
   nx (global)        : 16.8.1
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/express        : 16.10.0
   @nx/node           : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/vite           : 16.10.0
   @nx/webpack        : 16.10.0
   typescript         : 5.1.6
```

### Package Manager Version

10.2.4

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by grz-gajda** [comment]
Similar to https://github.com/nrwl/nx/issues/19226.

**Comment by mithileshchellappan** [comment]
Reverting to `16.6.01` helped me solve this issue

**Comment by nanthakumaran-s** [comment]
> Similar to #19226.

Thanks @grz-gajda . Found the fix from this issue

**Comment by nanthakumaran-s** [comment]
> Reverting to `16.6.0` helped me solve this issue with `generatePackageJson: true` in `nx.json`

Thanks @mithileshchellappan . Migrating to 16.6.0 worked for me

**Comment by ikushlianski** [comment]
When generating an `@nx/nest` application I don't see `package.json` anywhere, only `project.json`. Is it supposed to be like that?

**Comment by mithileshchellappan** [comment]
@ikushlianski If you have `generatePackageJson` enabled in `nx.json` nx will generate package.json for your services, which is used when building and independent service

**Comment by ikushlianski** [comment]
> @ikushlianski If you have `generatePackageJson` enabled in `nx.json` nx will generate package.json for your services, which is used when building and independent service

Thanks, I'd expect package.json to be created when I generate a Nest app with NX. But it seems NX has a different philosophy which does not imply that you'd need package.json unless you build your app for external use.
