### ISSUE TITLE
Changes in executors not affect projects

### ISSUE THREAD

**Issue by de-don** [nrwl/nx#20980]
### Current Behavior

I have a plugin with executors `@mono/executors` (project name `executors`, and one executor `@mono/executors:lint-translates`.

I noticed that the changes in this plugin do not affect the applications that use it.

For example, if I take the following steps, then at the last stage the result will be taken from the cache, although it is no longer relevant.
1) Run `nx run my-project:lint-translates`
2) Do some changes in source code of @org/executors
3) Again, run `nx run my-project:lint-translates` (it will return result instanly, from cache).

### Expected Behavior

Changes in plugin should invalidate cache for project:target that uses this executor, or there should be a way to configure that.

### Steps to Reproduce

1. Create simple nx repo.
2. Create plugin with 1 executor
3. Create library
4. Use this executor for some target in this library.
5. Run this target for this lib.
6. Made some changes in executor
7. Run this target for this lib again

### Nx Report

```shell
 >  NX   Report complete - copy this into the issue template

   Node   : 18.18.2
   OS     : darwin-arm64
   npm    : 9.8.1
   
   nx                 : 16.5.5
   @nx/js             : 16.5.5
   @nx/jest           : 16.5.5
   @nx/linter         : 16.5.5
   @nx/workspace      : 16.5.5
   @nx/angular        : 16.5.5
   @nx/cypress        : 16.5.5
   @nx/devkit         : 16.5.5
   @nx/eslint-plugin  : 16.5.5
   @nx/plugin         : 16.5.5
   @nx/storybook      : 16.5.5
   @nrwl/tao          : 16.5.5
   @nx/webpack        : 16.5.5
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc : 1.1.19
   @storybook/angular : 7.6.6
   nx-stylelint       : 16.0.1
   ---------------------------------------
   Local workspace plugins:
         @mono/generators
         @mono/executors
         @mono/shared
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by de-don** [comment]
Even when I changed version in `pachage.json` in `@org/executors` plugin, cache still valid.

**Comment by AgentEnder** [comment]
Yes, this is a known limitation. The projects that use the executor do not depend on the project containing the executor definition. You can manually include an implicit dependency to represent this relationship. We do not currently plan on adding the edge to the graph automatically as it can cause issues when multiple local plugins are present in the repository.
