### ISSUE TITLE
Impossible to pass extra args to vite cli

### ISSUE THREAD

**Issue by e-kulikov** [nrwl/nx#20997]
### Current Behavior

Any extra args passed into `options` object of `@nx/vite:build` executor are ignored

### Expected Behavior

Extra arguments override values defined in `vite.config`

### Steps to Reproduce

1. Generate `nx g @nx/js:lib --bundler vite`
2. Be sure there is no `watch` option in the build target of `vite.config` file
3. Add an extra target `dev` in `project.json` of the library with the following options:
```json
{
// ...
"targets": {
  "dev": {
    "executor": "@nx/vite:build",
    "options": {
      // ...
      "watch": true // or any other valid vite options
    }
  }
}
}
```
4. Run "dev" target of the project
5. See extra options are not applied

### Nx Report

```shell
Node   : 20.10.0
OS     : win32-x64
pnpm   : 8.13.1

nx                 : 17.2.8
@nx/js             : 17.2.8
@nx/linter         : 17.2.8
@nx/eslint         : 17.2.8
@nx/workspace      : 17.2.8
@nx/devkit         : 17.2.8
@nx/eslint-plugin  : 17.2.8
@nrwl/tao          : 17.2.8
@nx/vite           : 17.2.8
@nx/vue            : 17.2.8
@nx/web            : 17.2.8
nx-cloud           : 16.5.2
typescript         : 5.3.3
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

If I understood the idea correctly, there should not be negation `!` [in this condition](https://github.com/nrwl/nx/blob/e31c179c02f9aa2a767ed75be32be6bf53d69fda/packages/vite/src/executors/build/build.impl.ts#L202).

**Comment by mandarini** [comment]
Hi there @e-kulikov ! Thanks for filing an issue! You can pass the extra args inside your `vite.config.ts` file, instead. We are moving towards relying mostly on the config files of each tool instead of `project.json` targets! So can you try this instead and let me know?

**Comment by e-kulikov** [comment]
Hello!
Thanks for suggestion. I found out, that my particular case (I need "watch" mode for development) I can solve with "configurations" options. As I understood, nx but not vite will be watching changes, that is even better.

But in my mind, nx should be a middleware between a tool (vite, esbuild, eslint, etc) and end user, helping with usage, but not limiting any features (I might be probably wrong with this assumption). Most of the tools allow users to rewrite some options defined in the config through cli flags. And it seems instead of relying on config files, [checks like this](https://github.com/nrwl/nx/blob/e31c179c02f9aa2a767ed75be32be6bf53d69fda/packages/vite/src/executors/build/build.impl.ts#L202) limits and forces nx users to use end tool config files only, instead of providing them flexibility.

And now I realize it has been done intentionally, so it's not a bug issue and it's probably better close PR I made.

**Comment by mandarini** [comment]
In any case, I created this PR: https://github.com/nrwl/nx/pull/21042, which looks like it will help in this case.

**Comment by Wurielle** [comment]
> Hi @e-kulikov ! We will be removing executors and `project.json` files and configuration options quite soon, so we are sort of forcing users to use the Vite configuration options.
> 
> This
> 
> ```
>     if (!schema.properties[key]) {
>       extraArgs[key] = options[key];
>     }
> ```
> 
> means that right now we do allow ALL of the Vite CLi options to be forwarded to Nx. All those that are NOT in the `schema.json` are `extraArgs`. All those that are in schema.json are taken into account already, since they are not extra.
> 
> Please let me know of any concerns you may have, or if something does not work in your use case.

Hey there, I've been trying to pass an arg to my `vite` command as well as there doesn't seem to be a way to do it just with the Vite config file. 

I'm currently fighting with circular dependencies and I need to debug this with the `vite --debug hmr` command. 
Here's the link to the Vite documentation for this: https://vitejs.dev/guide/troubleshooting.html#a-full-reload-happens-instead-of-hmr

I haven't found a way to pass args from my current version of nx(@17.2.6) from the doc either so that might be an edge case worth considering if we're being pushed to use our build tool's config file.
