### ISSUE TITLE
@nx/remix - vitest keywords not found, pnpm triggers ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL for 'serve' target

### ISSUE THREAD

**Issue by binaryartifex** [nrwl/nx#21002]
### Current Behavior

in newly generated nx monorepo with a single remix app, the file at tests/routes/_index.spec.tsx triggers a typescript error saying it cannot find name 'test'. furthermore, when attempting to run the 'serve' target with pnpm, which default generates to `pnpm exec remix-serve build/index.js`, it triggeres an `ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL Command "remix-serve" not found` error.

### Expected Behavior

the types included in the tsconfig.spec.ts should be respected in the test example file and i shouldn't have to swap out pnpm for npx (which works as a fill in replacement) to get the serve target to work.

### Steps to Reproduce

1. pnpm dlx create-nx-workspace --packageManager="pnpm"
2. pnpm add -D @nx/remix
3. generate a remix app (id also point out it fails to perform dry runs)
4. check typescript error that generates in tests file
5. run build target, then attempt to run serve target.

### Nx Report

```shell
Node   : 20.9.0
   OS     : win32-x64
   pnpm   : 8.14.0

   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/react          : 17.2.8
   @nx/remix          : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/vite           : 17.2.8
   @nx/web            : 17.2.8
   typescript         : 5.3.3
```

### Failure Logs

```shell
💿  remix dev
 info  building...
 info  built (733ms)
'remix-serve' is not recognized as an internal or external command,
operable program or batch file.
undefined
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "remix-serve" not found
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Error: connect ECONNREFUSED 127.0.0.1:4200
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4200
}
Node.js v20.9.0
```

### Package Manager Version

pnpm - 8.14.0

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by JoepKockelkorn** [comment]
I'm running into the vitest keyword problems as well. Seems like the tsconfig setup is not correct. The tsconfig that is resolved is not the `tsconfig.spec.json` due to the files/include configuration pointing to all typescript files in the `tsconfig.json`. When generating an app with the Angular/React plugins this is however correctly setup, so we could check there what is the proper setup.
