### ISSUE TITLE
Nx complains that <p>...</p> is JSX

### ISSUE THREAD

**Issue by JESii** [nrwl/nx#21015]
### Current Behavior

I converted a simple "Hello world" CRA app to Nx to try it out.
`yarn build` works just fine and I can deploy the app to aws/s3
But now I'm getting errors when trying to run the app locally with `yarn start`
Why does it think that `<p>...</p>` is JSX?
![CleanShot 2024-01-04 at 16 58 40@2x](https://github.com/nrwl/nx/assets/486/d5a337de-e121-45cf-a180-df128671989f)

### Expected Behavior

Should start locally without complaints.

### GitHub Repo

https://github.com/JESii/hello-aws

### Steps to Reproduce

1. Install the repo
2. run `yarn build`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.12.1
   OS     : darwin-x64
   yarn   : 1.22.19

   nx (global)        : 17.2.8
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/react          : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/vite           : 17.2.8
   @nx/web            : 17.2.8
   typescript         : 5.2.2
```

### Failure Logs

```shell
None
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

1. I originally created a CRA just for testing some AWS code -- everything worked just fine: I built the app, ran it locally, deployed it to was, and all worked fine.
2. When I upgraded it to Nx (with npx nx init), it builds just fine, deployed just fine, but won't start in local mode

**Comment by ndcunningham** [comment]
I mean the syntax that you have is 100% JSX inside of a `.js` file. 
The error is correct and I do not believe this is a bug.

For your `build` command did you run `npx nx build` your cache might be stale.

Running `npx nx build --skip-nx-cache` should also higlight the issue.
