### ISSUE TITLE
Provide release* functions in Node.js API from non-src/ export?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [nrwl/nx#21029]
## Description

Moving https://github.com/typescript-eslint/typescript-eslint/pull/8194/files#r1443409404 here: can functions like `releaseChangelog`, `releasePublish`, and `releaseVersion` be exported from a more official-looking module specifier than `nx/src/command-line/release`? 

## Motivation

In that PR @JamesHenry had to use this import style:

```ts
import {
  releaseChangelog,
  releasePublish,
  releaseVersion,
} from 'nx/src/command-line/release';
```

Importing from `src/` like that feels off. Source code exports not made available from the root or another more formally indicated path imply we're taking a dependency on an internal thing we shouldn't.

## Suggested Implementation

I don't know much about how the `nx` family of packages is set up right now, so my first instinct is the smallest change:

```ts
import {
  releaseChangelog,
  releasePublish,
  releaseVersion,
} from 'nx';
```

## Alternate Implementations

...but if the root `nx` package isn't meant to export these things, maybe a different package, or failing that, formal sub-path?

```ts
import { /* ... */ } from '@nx/releases';
```

```ts
import { /* ... */ } from 'nx/releases';
```

**Comment by Hotell** [comment]
+ 1 for api import

```
import { /* ... */ } from '@nx/releases';
// or
import { /* ... */ } from 'nx/releases';
```
