### ISSUE TITLE
@nx/js registerTsProject ignores given tsconfig in favour of tsconfig.base when using swc build executor

### ISSUE THREAD

**Issue by ramik91** [nrwl/nx#21039]
### Current Behavior

When I register a generator or executor of my local Nx plugin using
```javascript
const { workspaceRoot } = require('nx/src/utils/workspace-root');
const { registerTsProject } = require('nx/src/plugins/js/utils/register');

registerTsProject(workspaceRoot, 'tsconfig.json');

module.exports = require('./generator.ts');
```

And there is a `tsconfig.base.json` present in my workspace root folder.
Then the compiler options defined in the given `tsconfig.json` are silently overridden with `tsconfg.base.json`.

This has been introduced in https://github.com/nrwl/nx/commit/9a919a0383bcf54053606a74fcd2ccacc2064ae1

### Expected Behavior

The complier options passed to `registerTsProject` function should not be overridden silently.

In case the override is really a desired/expected behaviour it should be documented properly and there should be a warning in the stout as well.

### GitHub Repo

https://github.com/ramik91/nx

### Steps to Reproduce

1. Create a workspace with `tsconfig.json` extending `tsconfig.base.json`, both present in the workspace root
2. Enable default import syntax in `tsconfig.json` file using `esModuleInterop` and `allowSyntheticDefaultImports` compiler options
3. Create a local Nx plugin
4. Crate a generator in the local Nx plugin
5. Implement the generator logic using TypeScript and default import syntax eg `import path from 'path'` and calling a method of the default import eg `path.join()`
6. Register the generator using `registerTsProject` as described above in the **Current Behaviour** section
7. Run the generator

The generator execution will fail with `Cannot read properties of undefined (reading "join")`

### Nx Report

```shell
Node   : 18.17.1
   OS     : darwin-x64
   yarn   : 1.22.19

   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/node           : 17.2.8
   @nx/plugin         : 17.2.8
   @nx/react          : 17.2.8
   @nx/rollup         : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   typescript         : 4.9.5
   ---------------------------------------
   Local workspace plugins:
   	 @jake/playwright-plugin-nx
   	 @jake/js-plugin-storybook
   	 @jake/js-plugin-nx
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

https://stackoverflow.com/questions/77765596/custom-nx-plugins-does-not-support-default-imports

**Comment by danielsharvey** [comment]
+1 

I've been affected by this. The behaviour was unexpected and the cause troublesome to track down.
