### ISSUE TITLE
Recent change to not allow relative import of non-project files has broken existing functionality

### ISSUE THREAD

**Issue by rathpc** [nrwl/nx#21035]
### Current Behavior

When referencing non-project global configuration type files, you now run into module boundary errors as a result of this issue https://github.com/nrwl/nx/pull/20563 being merged. There is no way to ignore this, so you either need to monkey patch this functionality back out or downgrade to a version before this. Additionally, if you try to move any and all global/root level configurations or scripts you might have (_we have several things we were centralizing to avoid copy and pasting config all over the place including storybook, cypress and webpack partial configs as well as various scripts and more_) into a new project instead, this still does not fix the issue because things like a partial storybook config cannot come from an aliased local project and Nx even has documentation providing what we had been doing as an example of this https://nx.dev/recipes/storybook/custom-builder-configs#projectspecific-configuration as well as a direct comment mentioning the same thing on another issue https://github.com/nrwl/nx/issues/19657#issuecomment-1767830770.

This change either needs to be reverted and addressed some other way, or give us a way to ignore that condition completely.

### Expected Behavior

We should still be able to import a centralized/root/global config (or really any other file) into a project file as a relative or absolute path and not hit a module boundary error. One specific case would be importing something like a root preview.ts file for storybook or a shared module-federation.config.ts file for webpack, or even a centralized cypress base config for component testing.

### Steps to Reproduce

1. On the latest version of Nx, configure the module boundary plugin, create a new library project and add a storybook configuration to it.
2. Create a root `.storybook` folder with a shared preview.ts file that exports something you might need to import in your local projects main.ts file.
3. Import that file in your main.ts file using a relative import.
4. Lint the project
5. You get an eslint error from the module boundary plugin.
6. Then you try to remedy this issue with the following steps.
7. Remove the relative import and move that root config into another project you might have which has an alias already set up for it in the tsconfig.
8. Import the config now using that aliased project import name.
9. Lint the project - no eslint error this time
10. Run storybook dev
11. Now you get a compilation error because the config is parsed before ts compilation happens.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.17.1
   OS     : darwin-arm64
   yarn   : 1.22.19

   nx (global)        : 17.1.1
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/express        : 17.2.8
   @nx/node           : 17.2.8
   @nx/plugin         : 17.2.8
   @nx/react          : 17.2.8
   @nx/storybook      : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   typescript         : 5.3.3
```

### Package Manager Version

yarn v1.22.19

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

These are the new lines creating this issue https://github.com/nrwl/nx/pull/20563/files#diff-b2ed99abed3583be93552042fff6a0365d3d611e4dfff38e223b9993b0e23d44R352-R357

@meeroslav tagging you as this was your change

**Comment by meeroslav** [comment]
Hi,

Thank you for raising this. I still believe no project should relatively import non-workspace files and that those partial configs should be part of the shared project or a `root` project.

The implemented functionality in the linter rule will not change, but you can disable the errors by adding the following comment on the line before:
```
// eslint-disable-next-line @nx/enforce-module-boundaries
```

@mandarini do you have an example where these shared partial configs are included in the root project and/or why sharing them from a library would not work?

**Comment by mandarini** [comment]
@rathpc can you please try to import the root file this this: `@scope/.storybook/preview.ts` and let us know if it works?

**Comment by rathpc** [comment]
Yes, this does not work due to the "pre-ts-compilation" state of the preview file, it errors with the infamous "Cannot find module" error. Specifically for storybook (at least what I've found so far) - it has to be relative to work

**Comment by rathpc** [comment]
I should specify, importing with `@scope/.storybook/preview.ts` works but only for linting, it causes the cannot find module error when running storybook

**Comment by rathpc** [comment]
will do, thank you. I will see if this potentially impacts any other part of our workflow in the meantime

**Comment by rathpc** [comment]
I've just discovered that cypress component testing also suffers from this problem. I ended up needing to put the lint ignore in many places. Even moving that to a scoped project at the root did not fix the issue.

**Comment by mandarini** [comment]
@barbados-clemens @meeroslav let's look into this a bit more offline

**Comment by rathpc** [comment]
@mandarini was anything further discovered offline on this issue?
