### ISSUE TITLE
`nx release`: support `projects` configuration filtering with similar patterns as `run-many`

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#21078]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Currently implemented filtering by project names In an huge monorepo with various release groups needs, is not sufficient as it's very hard to be able to declaratively define `projects` within `groups` and maintain that list in sync.

Thus one needs to always go [the imperative path](https://github.com/microsoft/fluentui/pull/30251/files#diff-24b89bf80b17b53078c9914190997ccec0106c336c087bc91e7f0f50be4d1dacR143-R168) to create another abstraction over an abstraction.

Task orchestration filtering logic is already implemented in `run-many`, it would be very useful to have similar filtering capabilities in nx release `projects` filtering.

## Suggested Implementation

```json
{
"release": {
    "groups": {
       "foo": {"projects":["tag:foo", "tag:platform:web"]}
    }
  }
}
```

**Comment by JamesHenry** [comment]
@Hotell do you have a reproduction for this not working? The config resolution logic already leverages the same utilities used by run-many, and when I personally tried leverage tags on a workspace just now it worked fine

**Comment by Hotell** [comment]
@JamesHenry whoops, I understood from examples that only project names or project names globs are available, haven't looked at implementation :D 

I try it out and it works ! closing and cheers !
