### ISSUE TITLE
extractLicenses causes error for Node.js builder

### ISSUE THREAD

**Issue by boyanio** [nrwl/nx#2107]
## Current Behavior

I have an express.js application using the latest (8.8.2) Nx with `@nrwl/node:build`. When in production I set `extractLicenses` to `true`, I get the following error:

```
An unhandled exception occurred: license-webpack-plugin: Please specify a regular expression as the pattern property on the plugin options.
```

## Expected Behavior

I don't get an error

**Comment by brandonroberts** [comment]
This has already been fixed by https://github.com/nrwl/nx/pull/2098 and will go out with the next release
