### ISSUE TITLE
affected:build --parallel fails in Angular Ivy first build

### ISSUE THREAD

**Issue by vadjs** [nrwl/nx#2108]
## Expected Behavior

`nx affected:build --parallel` in Angular project with Ivy enabled should have success result when building first time.

## Current Behavior

Build fails with error: `ERROR in Tried to overwrite /home/master/work/vtbf/node_modules/@angular/core/core.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.`

## Failure Information (for bugs)

When you run `nx affected:build --parallel` in Angular project first time, it starts compiling all packages (like `Compiling @angular/animations : es2015 as esm2015`).
Because NX runs several builds simultaneously, compiling process has conflicts and fails.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `ng g @nrwl/angular:application one`
2. `ng g @nrwl/angular:application two`
3. `ng update @angular/cli @angular/core --next` - Ivy turned on by default in Angular 9
4. `nx affected:build --all --parallel`

### Context

Please provide any relevant information about your setup:

- version of Nx used:
```
  @nrwl/angular : 8.8.2
  @nrwl/cli : 8.8.2
  @nrwl/cypress : 8.8.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.8.2
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.8.2
  @nrwl/web : Not Found
  @nrwl/workspace : 8.8.2
  typescript : 3.6.4
```
- 3rd-party libraries and their versions:
Angular 9.0.0-rc.3
- and most importantly - a use-case that fails
Everytime when it's first run of Angular app.

### Failure Logs

```
Compiling @angular/core : es2015 as esm2015
Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
ERROR in Tried to overwrite /home/master/work/test/bug/node_modules/@angular/core/core.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.
```

**Comment by FrozenPandaz** [comment]
Thank you for filing this issue.

The Angular team is aware of this issue:

https://github.com/angular/angular/issues/32431

We are planning to use a workaround for the time being.

```
"postinstall": "ngcc",
```

Unfortunately, it takes quite some time.

**Comment by Carniatto** [comment]
Any updates on this?

**Comment by vsavkin** [comment]
Closing this issue because the workaround is in place
