### ISSUE TITLE
Component-testing with angular and vite

### ISSUE THREAD

**Issue by mimse** [nrwl/nx#21089]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
I´m missing the option for using vite as the bundler with component testing

<img width="946" alt="image" src="https://github.com/nrwl/nx/assets/1250254/274e88ce-3998-4085-87f3-ff3e00b9fac1">

## Motivation
Would like to use vite for all of our bundling

**Comment by leosvelperez** [comment]
Thanks for the request!

While the current Cypress CT + Angular can use a build target with esbuild, it's true that it still uses webpack to build/serve the component for testing. This is something that's not supported by Cypress itself. As you can see in your shared screenshot, the `defineConfig` function from the `cypress` package doesn't allow you to pass `angular` with `vite`.

Please request this feature on the Cypress repository.
