### ISSUE TITLE
Better user experience when migrating from @nrwl/workspace@15 to @nx/workspace@16

### ISSUE THREAD

**Issue by davimiku** [nrwl/nx#21093]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
When migrating an Angular Nx repo from v15 to v16, I came across the [rescope documentation](https://nx.dev/recipes/other/rescope) for `@nrwl -> @nx`.

1. From an Angular Nx repo on v15
2. Run `nx migrate @nx/workspace@16.10.0`

However, no migrations are generated. The full output of that command is:

```sh
$ ./node_modules/.bin/nx migrate @nx/workspace@16.10.0
Fetching meta data about packages.
It may take a few minutes.

 >  NX   The migrate command has run successfully.

   - package.json has been updated.
   - There are no migrations to run, so migrations.json has not been created.


 >  NX   Next steps:

   - Make sure package.json changes make sense and then run 'npm install',
   - To learn more go to https://nx.dev/core-features/automate-updating-dependencies
```

(note that the package.json changes reported was just formatting)

After much confusion, I realized that although the scope is now `@nx`, I'm still supposed to run the migrations with the **old** `@nrwl` scope. Running `nx migrate @nrwl/workspace@16.10.0` proceeded with the migrations. The fact that the command ran successfully but produced nothing was confusing.

## Motivation
It would be nice to make it either "Just Work" to migrate to the `@nx` scope, or add a message/warning saying that you still have to use the old `@nrwl` scope for migrating.

## Suggested Implementation

There are a few things that could improve the user experience:

The migration to `@nx/workspace@16` from `@nrwl/workspace@15` could transparently include the migrations that you would have gotten by migrating to `@nrwl/workspace@16`.

Additionally, the [rescope documentation](https://nx.dev/recipes/other/rescope) says:

> For existing repos, run nx migrate as you normally would. When migrating to version 16 or higher, the package names will be automatically updated for you.

In hindsight, I get what it was trying to say, but when I was first doing the migration my interpretation "as you normally would" means "run nx migrate to the package you want to go to" where "the package I wanted to go to" was `@nx/workspace@16`. I think it's a little ambiguous and could be clarified a bit more.

## Alternate Implementations

The migration to `@nx/workspace@16` from `@nrwl/workspace@15` could include an error/warning message saying that you need to migrate to `@nrwl/workspace@16` first, which itself will include a migration that updates the scope name for you.

**Comment by FrozenPandaz** [comment]
I'm glad you figured it out. This migration is pretty old now. I don't think we'll update it at this point.

Hopefully others are able to figure it out as well.
