### ISSUE TITLE
nx/rspack 17.2.3 broken at npm

### ISSUE THREAD

**Issue by valorkin** [nrwl/nx#21091]
### Current Behavior

will not install because it depends on `"@nrwl/rspack": "17.2.3"` which is not on npm
this blocks rpsack related generates cuz they run `npm i -D @nx/rspack@*`

### Expected Behavior

should just work? :)

### Steps to Reproduce

1.  `npm i -D @nx/rspack@*` or  `npm i -D @nx/rspack@17.2.3`

### Nx Report

```shell
----
```

### Package Manager Version

npm 10

### Operating System

- [X] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Package has been published!
