### ISSUE TITLE
ts(2307) for importing Vue files from other nx libraries

### ISSUE THREAD

**Issue by DDuunk** [nrwl/nx#21109]
### Current Behavior

Cannot find module '@vue-ts-test/ui-components' or its corresponding type declarations. ts(2307)

### Expected Behavior

no error

### GitHub Repo

https://github.com/DDuunk/vue-ts-test

### Steps to Reproduce

1. Create a integrated monorepo using vue
2. pnx g @nx/vue:lib ui-components --directory=libs/ui/components --style=scss
3. pnx g @nx/vue:lib ui-layouts --directory=libs/ui/layouts --style=scss
4. Create a vue3 file in ui-component, lets call it `component-a`
5. Create a vue3 file in ui-layouts, lets call it `layout-a`
6. Import `component-a` in `layout-a`

### Nx Report

```shell
Node   : 18.18.0
   OS     : darwin-arm64
   npm    : 9.8.1
   
   nx (global)        : 16.2.2
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/vite           : 17.2.8
   @nx/vue            : 17.2.8
   @nx/web            : 17.2.8
   typescript         : 5.2.2
```

### Package Manager Version

pnpm 8.9.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by TimVervers** [comment]
Having the same problem! I can reproduce this issue using Mac with Webstorm and also Windows with VS Code. It seems to only giving errors when importing into Vue libraries, not the Apps.

**Comment by DaanIhomer** [comment]
I also have this issue! Comfirmed on Windows with webstorm

**Comment by mandarini** [comment]
Hi there @DDuunk ! I know of this error, and I'm looking into it. However, this is not preventing you from serving the app or building the app and seeing the correct result, right?
I mean, the typescript error pops up for me in vscode, but I can still build/serve successfully. Is this the case for you too?

**Comment by DDuunk** [comment]
@mandarini yes building and serving the app works as expected for me. Good to know this issue is known already. Please let me know if I can provide assistance!

**Comment by DaanIhomer** [comment]
Sure you can serve. But this issues gives an enormously cluttered error list in any IDE, not to mention missing intellisense like behaviors or control-clicking through to the source etc.

**Comment by mandarini** [comment]
I see @DaanIhomer ! I'll try to fix this! Thanks!

**Comment by mandarini** [comment]
@DaanIhomer @DDuunk 

you can remove 

```
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    },
```

from your `tsconfig.lib.json` and the warning will go away. I pushed a PR to fix this.

**Comment by mandarini** [comment]
Related: https://github.com/nrwl/nx/issues/21203

**Comment by DDuunk** [comment]
> @DaanIhomer @DDuunk
> 
> you can remove
> 
> ```
>     "baseUrl": ".",
>     "paths": {
>       "@/*": ["./src/*"]
>     },
> ```
> 
> from your `tsconfig.lib.json` and the warning will go away. I pushed a [PR](https://github.com/nrwl/nx/pull/21297) to fix this.
> 
> Here's a PR to your repo, as well @DDuunk [DDuunk/vue-ts-test#1](https://github.com/DDuunk/vue-ts-test/pull/1)

Thanks @mandarini this indeed fixes it! I'm curious, why does this fix it?

**Comment by mandarini** [comment]
I guess the `paths` in that file conflicts with the `paths` in `tsconfig.base.json`, and it messes up the result!

**Comment by DaanIhomer** [comment]
This works! My IDE is clean again! thank you :)
