### ISSUE TITLE
--reason-affected flag

### ISSUE THREAD

**Issue by robert-king** [nrwl/nx#21106]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
nx show projects --affected --exclude='tag:no-ci' --reason-affected

note the extra --reason-affected  flag

output would look like this:

nx show projects --affected --exclude='tag:no-ci' --reason-affected
frontend    reason=lib[common,..,+1],file[logo.png]
backend    reason=lib[common]
common    reason=file[consts.ts]
other-lib    reason=file[main.ts,...,+5]

in my CI/CD i noticed some apps were affected but i wasn't sure what was affecting them. This would help me quickly understand at least one reason why they were included.

## Suggested Implementation
a concise reason is given of the first change found that contributed towards the rolling hash. --verbose could allow larger reason

## Alternate Implementations
happy for suggestions, i only spent a few seconds thinking about this. I'd also need some pointers of how to implement.

**Comment by AgentEnder** [comment]
There's some spikes we've done around this that we may move forward with. With this being pretty integrated in core it would likely be an internal developer championing the PR.

**Comment by TheSpyder** [comment]
Could this "reason affected" also be used to show why a task runs when I think it should be cached? I find that _really_ hard to figure out.
