### ISSUE TITLE
Automatic dependency detection not working anymore

### ISSUE THREAD

**Issue by eugeniosegala** [nrwl/nx#21110]
### Current Behavior

I have create a new integrated mono-repo following the [NX tutorial](https://nx.dev/getting-started/tutorials/integrated-repo-tutorial).

Something I noticed is that the [automatic dependency detection](https://nx.dev/core-tutorial/05-auto-detect-dependencies) is not working anymore.

Even after adding:

```
"pluginsConfig": {
  "@nx/js:tsc": {
    "analyzeSourceFiles": true
  }
}
```

Every time I build a package using the `@nx/js:tsc` executor, the `package.json` inside the `dist` folder does not contain the dependencies included within my package.

In previous versions of NX (i.e: v16), this feature was working.

I have create a sample repo [here](https://github.com/eugeniosegala/nx-17-auto-dep-detection-bug/blob/main/libs/is-even/src/lib/is-even.ts#L4).

### Expected Behavior

The `package.json` of the built package should contain its dependencies, including `loadash`.

Additional notes: even the internal packages `is-even`/`is-odd` do not appear within the package.json.

### GitHub Repo

https://github.com/eugeniosegala/nx-17-auto-dep-detection-bug

### Steps to Reproduce

1. Create a new integrated mono-repo following the [documentation](https://nx.dev/getting-started/tutorials/integrated-repo-tutorial).
2. Add `lodash` to the main `package.json` and use it inside the `is-even` package
3. Build the `is-even` package and check `package.json` inside `dist`

Or check this sample repo on [GitHub](https://github.com/eugeniosegala/nx-17-auto-dep-detection-bug/blob/main/libs/is-even/src/lib/is-even.ts#L4).

### Nx Report

```shell
Node   : 18.13.0
OS     : darwin-x64
npm    : 9.2.0
   
nx                 : 17.2.8
@nx/js             : 17.2.8
@nx/jest           : 17.2.8
@nx/linter         : 17.2.8
@nx/eslint         : 17.2.8
@nx/workspace      : 17.2.8
@nx/devkit         : 17.2.8
@nx/eslint-plugin  : 17.2.8
@nrwl/tao          : 17.2.8
typescript         : 5.2.2
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by schoubeydeloitte** [comment]
Hello, is there any update on this issue?

**Comment by shubhuchoubey** [comment]
Hello, is there any update on this?

**Comment by AgentEnder** [comment]
@nx/js:tsc doesn't update package json to contain libraries automatically any more, rather you should use the lint rule to ensure that the package.json stays up to date. See: https://nx.dev/nx-api/eslint-plugin/documents/dependency-checks
