### ISSUE TITLE
how to use native-federation in NX?

### ISSUE THREAD

**Issue by ksrae** [nrwl/nx#21127]
I have used module-federation in my project which is build in Angular 13 with NX.
I am trying to update Angular to 17 and change module-federation to native-federation.

It worked without NX. however, I have no idea how to set native-federation on NX.

I couldn't find any document for it.

when I tried `ng g @angular-architects/native-federation:init` then I got an error: "Error: This command is not available when running the Angular CLI outside a workspace".

is there any CLI command? or how to fix project.json?

**Comment by AgentEnder** [comment]
`nx g @angular-architects/native-federation:init` should be used, instead of `ng g`

**Comment by Coly010** [comment]
As @AgentEnder stated, you should ensure you're using `nx` to run generators in an Nx Workspace. 

I'm going to close this issue as the fix has been provided. If you have further issues, tag me in your comment and I'll revisit it!
