### ISSUE TITLE
After upgrading to nx 17 cache directory setting seems ignored and produces a .nx directory at project root

### ISSUE THREAD

**Issue by blackholegalaxy** [nrwl/nx#21120]
### Current Behavior

We have a NX project to handle various library development. Repo is public and mentionned below.

Project was using NX 16 and angular 16 ecosystem. Recently we ran `nx migrate latest` to move to nx 17. After the migration a `.nx` directory appeared and had to be gitignored.

Previous config:
```json
"tasksRunnerOptions": {
    "default": {
      "runner": "nx-cloud",
      "options": {
        "cacheDirectory": ".nxcache",
        "cacheableOperations": [
          "build",
          "lint",
          "test",
          "bundle-scss"
        ]
      }
    }
  },
```

New config after `nx migrate latest`:
```json
"cacheDirectory": ".nxcache"
```

Plus `cache:true` on each cacheable operation.

Despite this a .nx directory was immediately created. Containing a sub `cache` directory with files map and project graph.

### Expected Behavior

We expect to have NX 17 not overriding our cacheDirectory settings.

### GitHub Repo

https://github.com/exalif/angular-libs

### Steps to Reproduce

1. create a NX project at version 16 using for example angular preset
2. Add cacheable operations and add a custom cache config containing a cacheDirectory different than `.nx`:

```json
"tasksRunnerOptions": {
    "default": {
      "options": {
        "cacheDirectory": ".nxcache",
        "cacheableOperations": [
          "build",
          "lint",
          "test"
        ]
      }
    }
  },
```

3. `nx migrate latest` to update to NX 17
4. See a .nx directory is created at root

### Nx Report

```shell
BEFORE:
>  NX   Report complete - copy this into the issue template

   Node   : 18.12.0
   OS     : win32-x64
   yarn   : 3.5.1

   nx (global)        : 16.10.0
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/angular        : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/webpack        : 16.10.0
   nx-cloud           : 16.4.0
   typescript         : 5.1.6

AFTER:
>  NX   Report complete - copy this into the issue template

   Node   : 18.12.0
   OS     : win32-x64
   yarn   : 4.0.2

   nx (global)        : 17.2.8
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/angular        : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   typescript         : 5.2.2
```

### Operating System

- [X] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Please note we tried on staying on yarn 3.5.1 with the same results.

**Comment by AgentEnder** [comment]
The cache directory is still used, but there are certain files that are not controlled via it. These are files that are almost more of a temp storage for Nx itself, rather than cache artifacts. They can be controlled via NX_PROJECT_GRAPH_CACHE_DIRECTORY. See: https://nx.dev/reference/environment-variables#environment-variables

**Comment by dhmw** [comment]
Hi @AgentEnder I don't think using an env var which is not also exposed in nx.json is a proper solution for this. I have just updated to the latest nx and I am seeing the `.nx` directory created even after only running `yarn` in my repository. I really would rather avoid having to now set env vars in _every environment_ which builds this repository. Somehow earlier versions of nx were able to keep it's files in one place, so I'm not sure why this would have changed?

You've stated in another thread on this topic that

> Idiomatically these files aren't part of the user facing cache. Think of it almost more as temp storage for Nx.

So why not put them in some `/tmp/path-hash` location and not inside my repository where its making a mess?


Regards,
Doug
