### ISSUE TITLE
@nrwl/storybook peer dependency version fix

### ISSUE THREAD

**Issue by philipjbrowning** [nrwl/nx#2113]
The dependency versions for babel-loader and @babel/core have the wrong name and version number combination:

## Expected Behavior

- @nrwl/storybook@8.8.3 requires a peer of @babel/core@^7.5.4
- @nrwl/storybook@8.8.3 requires a peer of babel-loader@^8.0.6

- @storybook/web -> @storybook/core ???

## Current Behavior

```
npm WARN @nrwl/storybook@8.8.3 requires a peer of @storybook/web@^5.2.5 but none is installed. You must install peer dependencies yourself.
npm WARN @nrwl/storybook@8.8.3 requires a peer of babel-loader@^7.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN @nrwl/storybook@8.8.3 requires a peer of @babel/core@^8.0.6 but none is installed. You must install peer dependencies yourself.
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install the latest of @nrwl/storybook@8.8.3
2. Look at the warnings

### Context

Please provide any relevant information about your setup:

- version of Nx used is 8.8.3

**Comment by vsavkin** [comment]
Fixed here: https://github.com/nrwl/nx/pull/2128
