### ISSUE TITLE
Additional cypress configuration option overrides

### ISSUE THREAD

**Issue by matt-sneed** [nrwl/nx#21132]
It would be nice if you could configure a cypress executor with additional configuration options such as turning on video recording. 

## Description
Add an executor option similar to the ```env``` option, to pass in configurations from our executors. A use case that would be beneficial for this, is the ability to turn on / off video recording in different executors. Currently the only valid way of doing that is to provide multiple configuration files or pass it in as a command line statement like:

```
CYPRESS_VIDEO=true nx e2e project-name
```

## Motivation
Allowing additional customizations in our executors would allow us to define separate executor configurations for different developer or CI/CD scenarios

## Suggested Implementation
add an additional schema option for ```config```
```
    "config": {
      "type": "object",
      "description": "A key-value Pair of config values to pass to Cypress runner."
    },
```

additionally, in the executor you would simply add an additional section to add those config values to the Cypress.run / Cypress.open
```
 if (opts.config) {
    options.config = {
      ...options.config,
      ...opts.config,
    };
  }
```

**Comment by AgentEnder** [comment]
I think the recommended path here would be to create multiple configuration files, we are unlikely to add extra functionality via the executor options as we are currently trying to stick more towards letting the tool work as it normally would to remove a bit of the magic that confuses developers when onboarding to Nx.
