### ISSUE TITLE
nx affected:libs , affected:apps etc. dont work anymore

### ISSUE THREAD

**Issue by montella1507** [nrwl/nx#21134]
### Current Behavior

When i run anything like 

"nx affected:libs"

i am getting error 

Cannot find configuration for task projectname:affected:libs

Strange is, it does not work on macOS, node v20.9.0

but it works on circleci.

### Expected Behavior

It should have printed affected libs / apps

### Steps to Reproduce

Creeate respotiroy with lib and app

### Nx Report

```shell
Node   : 20.9.0
   OS     : darwin-arm64
   npm    : 10.1.0
   
   nx                 : 17.1.1
   @nx/js             : 17.1.1
   @nx/jest           : 17.1.1
   @nx/linter         : 17.1.1
   @nx/eslint         : 17.1.1
   @nx/workspace      : 17.1.1
   @nx/angular        : 17.1.1
   @nx/cypress        : 17.1.1
   @nx/devkit         : 17.1.1
   @nx/eslint-plugin  : 17.1.1
   @nrwl/tao          : 17.1.1
   @nx/web            : 17.1.1
   @nx/webpack        : 17.1.1
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.12.1
   @ngneat/transloco                : 4.3.0
   @ngrx/component                  : 17.0.0-rc.0
   @ngrx/component-store            : 17.0.0-rc.0
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
`affected:apps` and `affected:libs` were removed for nx 17. You can use `nx show projects --affected` to achieve similar results.
