### ISSUE TITLE
nx affected does not work correctly when package.json is changed

### ISSUE THREAD

**Issue by jneves92** [nrwl/nx#21130]
### Current Behavior

First change package.json versions and then run command nx affected -t lint --files=package.json .
Result: NX   Successfully ran target lint for 0 projects (4ms)

### Expected Behavior

First change package.json versions and then run command nx affected -t lint --files=package.json .
Result: NX   Successfully ran target lint for 130 projects.

This is the expected behavior because I have many projects depends on package.json

### Steps to Reproduce

1. Change package.json versions
2. run command nx affected -t lint --files=package.json

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.9.0
   OS     : darwin-arm64
   npm    : 10.1.0
   
   nx (global)        : 17.2.8
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/angular        : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/storybook      : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @storybook/angular : 7.6.8
   angular-calendar   : 0.31.0
   devextreme-angular : 23.1.6
   ngx-build-plus     : 17.0.0
   ngx-spinner        : 16.0.2
   ngx-toastr         : 18.0.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Did you run `npm i` after making the changes to `package.json`? The `package-lock.json` will trigger all of the projects being affected.
