### ISSUE TITLE
unexpected cache hit after changes in a standalone project

### ISSUE THREAD

**Issue by chihab** [nrwl/nx#21144]
### Current Behavior

* nx build
* update a file inside src folder of the standalone app
* nx build (cache hit, ouptut read from the cache)

### Expected Behavior

* nx build
* update a file inside src folder of the standalone app
* nx build (cache miss)

### Steps to Reproduce

npx create-nx-workspace@latest
Choose Angular or React
Choose Standalone

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : darwin-arm64
   npm    : 10.2.3
   
   nx (global)        : 17.1.3
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/react          : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/vite           : 17.2.8
   @nx/web            : 17.2.8
   typescript         : 5.2.2
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

- Cache hit works as expected on intergrated monorepo
- If I replace projectRoot with workspaceRoot in named inputs, the cache works as expected for the standalone project
- Update: The issue is not reproducible on 17.0.0

**Comment by PeterMK85** [comment]
Facing the same after, updating `"17.0.2",` to `"17.2.8"` experiencing unexpected cache hits, particularly on tasks with externalDependencies declarations.

Example task:
```        
"generate-api-types-schema": {
            "executor": "api-schema-generator",
            "options": {
                "contractsFiles": [
                    "node_modules/@xxx/yyy/reference/api.spec.json",
                ],
                "outDir": "src/generated",
                "cwd": "packages/schemas"
            },
            "inputs": [
                {
                    "externalDependencies": [
                        "@xxx/yyy",
                        "swagger-typescript-api",
                        "openapi-zod-client"
                    ]
                },
                "{workspaceRoot}/packages/_plugins/api-schema-generator/executor.ts",
                "{workspaceRoot}/packages/_plugins/api-schema-generator/template.hbs"
            ],
            "outputs": ["{projectRoot}/src/generated/**/*"]
        },
 ```
 
 Before the update worked fine, after the update on `@xxx/yyy`, still a cache hit

**Comment by chihab** [comment]
The issue is not reproducible on 17.0.0

**Comment by Pho3niX90** [comment]
same issue experienced: 
    "@nx/angular": "17.2.8",
    "@nx/workspace": "17.2.8",

**Comment by ecool** [comment]
New project created to test this also has cache hitting when it shouldn't.

**Comment by Cammisuli** [comment]
this was fixed in  https://github.com/nrwl/nx/pull/20979 - which should be coming out very soon. (in 17.3.0)

Sorry for the delay on this!
