### ISSUE TITLE
Bun as package manager

### ISSUE THREAD

**Issue by ffMathy** [nrwl/nx#21154]
- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description, Motivation, Suggested implementation

Before you close this, please hear me out. 

In #11049, it was mentioned that making NX support for Bun as a package manager would require changes to the core. 

That's true, but since Bun's lock file is identical to Yarn's (it's a binary file), it wouldn't require many changes, and most likely wouldn't lead to a lot of trouble and bugs.

In fact, a guy named Jordan Hall even made a patch to support it: https://gist.github.com/Jordan-Hall/e910402a31b4a1e5a0b78324d6595618

I feel like the Bun related issues are closed way too fast. Yes, I know there's a discussion available, but is that being tracked or monitored? I feel like locking an issue keeps us from counting the amount of up votes on it. 

Here, I'm not advocating towards full Bun support in NX. However, just support for the package manager part. 

I also feel like the impact is huge. I already tested the performance boost of Bun compared to even pnpm. And it's very, very real. So for such a huge win with such an easy change (as highlighted in the patch), what's not to like? 

If you decide to lock this, at least please post a proper reasoning around your thoughts, and perhaps give the community a chance to provide a counter argument to that reasoning. 

Bun is not just hype it seems. I get different vibes than when Yarn came out. The places where I've tried using it, the difference was night and day, and the Node team doesn't seem to be responding at all to Bun's competition.

**Comment by AgentEnder** [comment]
We can leave an issue open for now for Bun, its just not a priority at this moment so support it automatically. You should still be able to use bun for installing packages, and just use the `--skip-install` flags for generators and set NX_MIGRATE_SKIP_INSTALL when migrating, as then Nx shouldn't ever be running a package manager install.

For now, I'm closing this out in favor of https://github.com/nrwl/nx/issues/21075, which will track bun support.
