### ISSUE TITLE
Unnecessary installation of React-specific packages when generating nx workspace with nest preset

### ISSUE THREAD

**Issue by mihailgolban** [nrwl/nx#21152]
### Current Behavior

When generating a new project with the Nest preset using the command `npx create-nx-workspace my-workspace --preset=nest`, unnecessary packages related to React monorepo are being installed. The packages in question are:
```json
 "@pmmmwh/react-refresh-webpack-plugin": "^0.5.7",
 "@svgr/webpack": "^8.0.1",
 "react-refresh": "^0.10.0",
```

These packages are not required for NestJS projects and are more relevant to React setups.
React-specific packages mentioned above are installed, even though they are not needed for NestJS monorepo projects.

### Expected Behavior

Only the necessary packages for NestJS monorepo should be installed, excluding the unnecessary React-related packages.

### Steps to Reproduce

1. Run `npx create-nx-workspace my-workspace --preset=nest`
2. Check the installed packages in the generated package.json

### Nx Report

```shell
Node   : 20.11.0
   OS     : linux-x64
   pnpm   : 8.14.1
   
   nx                 : 17.3.0-beta.2
   @nx/js             : 17.3.0-beta.2
   @nx/jest           : 17.3.0-beta.2
   @nx/linter         : 17.3.0-beta.2
   @nx/eslint         : 17.3.0-beta.2
   @nx/workspace      : 17.3.0-beta.2
   @nx/angular        : 17.3.0-beta.2
   @nx/cypress        : 17.3.0-beta.2
   @nx/devkit         : 17.3.0-beta.2
   @nx/esbuild        : 17.3.0-beta.2
   @nx/eslint-plugin  : 17.3.0-beta.2
   @nx/next           : 17.3.0-beta.2
   @nx/playwright     : 17.3.0-beta.2
   @nx/react          : 17.3.0-beta.2
   @nx/storybook      : 17.3.0-beta.2
   @nrwl/tao          : 17.3.0-beta.2
   @nx/web            : 17.3.0-beta.2
   @nx/webpack        : 17.3.0-beta.2
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @monodon/rust      : 1.3.2
   @ngrx/effects      : 17.0.1
   @ngrx/router-store : 17.0.1
   @ngrx/store        : 17.0.1
   ---------------------------------------
   Local workspace plugins:
         @nx/linter
         @nrwl/storybook
         @nrwl/workspace
         @nrwl/angular
         @nrwl/cypress
         @nrwl/esbuild
         @nrwl/webpack
         @nx/workspace-plugin
         @nrwl/react
         @nx/react-native
         @nrwl/jest
         @nrwl/next
         @nx/playwright
         @nrwl/web
         @nrwl/js
         @nx/storybook
         @nx/workspace
         @nx/angular
         @nx/cypress
         @nx/esbuild
         @nx/express
         @nx/webpack
         @nx/eslint
         @nx/plugin
         @nx/rollup
         @nx/detox
         @nx/react
         @nx/remix
         @nx/expo
         @nx/jest
         @nx/nest
         @nx/next
         @nx/node
         @nx/nuxt
         @nx/vite
         @nx/vue
         @nx/web
         @nx/js
         nx
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by benjaminhera** [comment]
I thought I was going crazy, I regenerated my whole workspace like 3 times and found the same bug.

I guess the `url-loader` package is related to `webpack` and in turn to Nest right?

**Comment by mihailgolban** [comment]
Hi @benjaminhera,

It's worth noting that this problem seems to affect users who are using `Node` projects as well, not just `NestJS`.

Regarding your question about the `url-loader` package, it is not specifically required for `NestJS`, and its inclusion might be related to the unintended installation issue. 
I recommend manually removing the React-specific packages from the `package.json` file after generating the workspace until the issue is resolved.

**Comment by benjaminhera** [comment]
Thanks for looking into and fixing this issue @mihailgolban!

I'm going to try to remove the `url-loader` package, if I encounter any dependency issue I will let you know.
