### ISSUE TITLE
unable to run e2e tests for a specific browser using the `@nx/playwright:playwright` executor

### ISSUE THREAD

**Issue by quirin-buechner-mdctec** [nrwl/nx#21151]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

The `@nx/playwright:playwright` executor has a `browser` option but when using it, I got an error:
```
nx e2e cb-legacy-e2e --browser=chromium
```
```
Error: Cannot use --browser option when configuration file defines projects. Specify browserName in the projects instead.
    at new FullConfigInternal (C:\Users\QuirinBuechner\Projekte\mdctec-mono-repo\node_modules\.pnpm\playwright@1.40.1\node_modules\playwright\lib\common\config.js:57:63)
    at ConfigLoader._loadConfig (C:\Users\QuirinBuechner\Projekte\mdctec-mono-repo\node_modules\.pnpm\playwright@1.40.1\node_modules\playwright\lib\common\configLoader.js:114:24)
    at ConfigLoader.loadConfigFile (C:\Users\QuirinBuechner\Projekte\mdctec-mono-repo\node_modules\.pnpm\playwright@1.40.1\node_modules\playwright\lib\common\configLoader.js:95:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runTests (C:\Users\QuirinBuechner\Projekte\mdctec-mono-repo\node_modules\.pnpm\playwright@1.40.1\node_modules\playwright\lib\cli.js:118:36)
    at t.<anonymous> (C:\Users\QuirinBuechner\Projekte\mdctec-mono-repo\node_modules\.pnpm\playwright@1.40.1\node_modules\playwright\lib\cli.js:40:7)
```

Assuming the following `playwright.config.ts`:
```typescript
import { defineConfig, devices } from '@playwright/test'
import { nxE2EPreset } from '@nx/playwright/preset'

export default defineConfig({
    ...nxE2EPreset(__filename, { testDir: './src/playwright/tests' }),
    /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
    use: {
        baseURL:'http://localhost:4200',
        /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
        trace: 'on-first-retry',
    },
    projects: [
        {
            name: 'chrome',
            use: {
                ...devices['Desktop Chrome'],
                channel: 'chrome',
            }, // or 'chrome-beta'
        },
        {
            name: 'edge',
            use: {
                ...devices['Desktop Edge'],
                channel: 'msedge',
            },
        },
        {
            name: 'firefox',
            use: {
                ...devices['Desktop Firefox'],
            },
        },
    ],
})

```
## Motivation
It would be great if there is a CLI option to limit local test execution to only one browser in order to decrease test execution time.
I have configured playwright to run my tests on multiple browsers. During CI this is not a big deal as I dont care that much about time but, when running tests locally, especially with watchMode on, IMHO it is more important to get test results fast, and it would be 'enough' to run tests only for one browser.

## Suggested Implementation
Playwright has a `--project` CLI parameter (see https://playwright.dev/docs/test-projects#run-projects) that would allow to run tests using a single browser configuration as defined in the `projects` section of the config file, but I was not able to pass a value via the nx CLI. The nx playwright executor would have to correctly run playwright with an extra `--project` parameter

**Comment by quirin-buechner-mdctec** [comment]
There is already a discussion related to the `--project` Parameter in the playwright repo: 
[https://github.com/microsoft/playwright/issues/23840#issuecomment-1601333396](url)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

You should run:

```
nx e2e cb-legacy-e2e -- --project=chromium
```

Note the extra `--` in front of the `--project=chromium`. The Nx CLI has a `--project` argument that gets parsed and stripped from the command run. If you need to provide it to the underlying task, you need to "tell" the Nx CLI not to parse it. That's what the extra `--` does. It's a separator telling the Nx CLI that anything that comes behind it is for the task being run. That's needed for any option whose name matches that of an Nx CLI option. For any other option that doesn't match, we don't need to provide that separator.
