### ISSUE TITLE
Possibility of using middleware with the executeDevServerBuilder.

### ISSUE THREAD

**Issue by BenSawary** [nrwl/nx#21175]
I'd like to use the executeDevServerBuilder programmatically like angular's builder. In the current implementation there is no way to pass a middleware to the builder.

Under the hood the nx builder delegates to the angular builder. Therefore it should be possible to add an optional middleware parameter to the nx builder.

A alternative would be to use the angular builder directly but without the nx features :(

- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

**Comment by leosvelperez** [comment]
This was added in https://github.com/nrwl/nx/pull/21048 and released in Nx v17.3.0.

**Comment by BenSawary** [comment]
Hi @leosvelperez,

thank you very much for the dev-server extension. However, with this implementation there is no way to pass parameters to the middleware like in the plugin specification.


Can you provide this option with the next release?
