### ISSUE TITLE
Unable to load Angular remote inside React Host application

### ISSUE THREAD

**Issue by sonikasharma1403** [nrwl/nx#21174]
### Current Behavior

Unable to load Angular remote inside React Host application

### Expected Behavior

`loadRemoteModule` should be able to load react and angular remotes

### Steps to Reproduce

1. Create a react host
2. Create a angular remote
3. use `loadRemoteModule` from `@nx/react/mf` to load the remote application

### Nx Report

```shell
Node   : 18.16.0
   OS     : darwin-x64
   npm    : 9.5.1
   
   nx (global)        : 16.10.0
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/react          : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   typescript         : 5.2.2
```

### Operating System

- [ X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by sonikasharma1403** [comment]
I was able to get it up and running by these 2 approaches.

Approach 1:
<img width="776" alt="image" src="https://github.com/nrwl/nx/assets/86649832/2f1842eb-5be0-4da7-83c6-95a915af2324">
had to include a similar change in the angular, `withModuleFederation` function
Final change: <img width="776" alt="image" src="https://github.com/nrwl/nx/assets/86649832/6a504c92-1f0b-42c6-96de-3d0db57c9fb0">

Approach 2: 
<img width="621" alt="image" src="https://github.com/nrwl/nx/assets/86649832/1a516249-b15b-488f-993f-36c5c3fff0f1">
instead of fetching the file and adding it to the head tag, can we use the angular apporach ie.
`function loadModule(url: string) {
  return import(/* webpackIgnore:true */ url);
}
`

Approach 2 works for both react and angular remote, and we need not do the `library: { type: var,  name: test}` related change

**Comment by sonikasharma1403** [comment]
@AgentEnder, @Coly010 - could you please recommend a way to get this up and running?

**Comment by Coly010** [comment]
This is not a feature we support, nor intend to support as it will lead to Micro Frontend Anarchy.
https://www.thoughtworks.com/en-gb/radar/techniques/micro-frontend-anarchy

You could potentially look at using a web components: https://www.angulararchitects.io/en/blog/multi-framework-and-version-micro-frontends-with-module-federation-your-4-steps-guide/

**Comment by sonikasharma1403** [comment]
@Coly010 - 
Angular architects support this based on type, for react - it is possible to use the script approach, and for angular it is possible to use the module approach. It can also be explicitly specified if needed. 

If type is module - then it does the `function loadModule(url: string) { return import(/* webpackIgnore:true */ url); }` and if type is script it uses the `script loading and window scope`. 

This is the same function used in the link shared by you above. 

https://github.com/angular-architects/module-federation-plugin/blob/main/libs/mf-runtime/src/lib/loader/dynamic-federation.ts#L80

Can we have similar support and leave the decision of `type` to the application?

**Comment by sonikasharma1403** [comment]
@Coly010 , @AgentEnder  - can we have a similar support?

**Comment by Coly010** [comment]
You should be able to use the `angular-architects` module federation plugin if you need this support right away.

I cannot guarantee we'll add this support, as mentioned it leads into Micro Frontend Anarchy, which we want to avoid. 

However, I will bring it up internally as a discussion point.

**Comment by hardikpatel043** [comment]
For me the use case is to load Angular module dynamically in angular app only. Once angular module is loaded, i want to extract component from it and load in html template. Here angular component is having several input and outputs. So i can't use lazy loading of federated module.

Yes, I can do it using standalone component. But due to some reason, I cant move from angular module to standalone component.

Is there any way to achieve this using nx module federation ?

@Coly010
