### ISSUE TITLE
Nx integrated workspace with Vue project keeps throwing "Cannot find module" even 

### ISSUE THREAD

**Issue by MrJean** [nrwl/nx#21203]
### Current Behavior

A freshly created Nx integrated workspace with a Vue project (using Vite) keeps throwing "Cannot find module" error in the IDE even when the paths have been added to tsconfig.app.json - in addition to already having the path in resolve - alias in vite.config.ts.

Adding this to tsconfig.app.json even results in "Cannot find module" errors on the shared library imports.

### Expected Behavior

The paths configured in tsconfig.app.json should be correctly interpreted by the IDE and not throw a "Cannot find module" error.

### Steps to Reproduce

`$ npx create-nx-workspace@latest`

✔ Where would you like to create your workspace? · nxintegratedvue
✔ Which stack do you want to use? · vue
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · nxintegratedvue
✔ Test runner to use for end to end (E2E) tests · cypress
✔ Default stylesheet format · scss
✔ Enable distributed caching to make your CI faster · No

`$ cd nxintegratedvue`

`$ npx nx generate @nx/vue:library --name=components --unitTestRunner=vitest --bundler=vite --directory=libs/components --component=true --importPath=@lib/components --projectNameAndRootFormat=as-provided --no-interactive`

`$ npx nx generate @nx/js:library --name=shared-assets --unitTestRunner=vitest --directory=libs/shared-assets --importPath=@lib/shared-assets --projectNameAndRootFormat=as-provided --no-interactive`

Go to App.vue and add the following import: `import { Components } from '@lib/components';`

Also add the component to the `<template>` of App.vue: `<Components />`

$ npx nx run nxintegratedvue:serve

Confirm the `Components`-component is present and the application starts.

Again in App.vue comment out the default NxWelcome import and replace it with an import that contains an alias (@):

```
// import NxWelcome from './NxWelcome.vue';
import NxWelcome from '@/app/NxWelcome.vue';
```

This will result in the codebase being not able to resolve the NxWelcome path.
Now in `vite.config.ts` add the following:

```
  resolve: {
    alias: [
      {
        find: '@',
        replacement: fileURLToPath(new URL('./src', import.meta.url))
      }
    ]
  },
```

The component will be resolved correctly, but the IDE will present a "Cannot find module" error.
Now add the following to the `compilerOptions` in `tsconfig.app.json`:

```
    "paths": {
      "@/*": [
        "./src/*"
      ],
    }
```

The "Cannot find module" will still occur and after restarting the IDE the "Cannot find module" error is also present on import from the shared `Components`-component.

### Nx Report

```shell
Node   : 20.9.0
   OS     : darwin-arm64
   npm    : 10.1.0
   
   nx (global)        : 17.2.8
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/vite           : 17.2.8
   @nx/vue            : 17.2.8
   @nx/web            : 17.2.8
   typescript         : 5.2.2
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Hi there @MrJean 

Can you please remove 

```
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    },
```

from your `tsconfig.lib.json`?
This will make the warning go away. 

I pushed a [PR](https://github.com/nrwl/nx/pull/21297) to fix this.

**Comment by LHBruneton-C2C** [comment]
Hello !
Thanks @mandarini for your answer.
It helped me in a different context, which could be fixed too:
- in a Vue Standalone Nx workspace
- when generating a new module with Nx generator (and using this module as an internal dependency)
- serving works fine
- building fails with a "Cannot find module" error
- the lines you pointed out are the culprit in `tsconfig.lib.json`
