### ISSUE TITLE
[Next] Error: Could not find a production build

### ISSUE THREAD

**Issue by stomvi** [nrwl/nx#21215]
### Current Behavior

Clean install @nx/next with @nx/next:custom-server, `npx nx run xxx:serve:production` will fail:
Error: Could not find a production build

Only `npx nx run xxx:serve-custom-server:production` works.

### Expected Behavior

`npx nx run xxx:serve:production` should also work.

### Steps to Reproduce

npx create-nx-workspace test --preset=next --appName=www --nextAppDir=true --nxCloud=false --style=scss --e2eTestRunner=cypress
cd test
npx nx g @nx/next:custom-server --project=www --compiler=swc
npx nx run www:build:production
npx nx run www:serve:production

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : darwin-arm64
   npm    : 10.2.3

   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/next           : 17.2.8
   @nx/react          : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   typescript         : 5.2.2
```

### Failure Logs

```shell
Error: Could not find a production build in the '.../new1/apps/www/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at NextNodeServer.getBuildId (.../new1/node_modules/next/src/server/next-server.ts:461:15)
    at new Server (.../new1/node_modules/next/src/server/base-server.ts:403:25)
    at new NextNodeServer (.../new1/node_modules/next/src/server/next-server.ts:216:5)
    at NextServer.createServer (.../new1/node_modules/next/src/server/next.ts:167:20)
    at .../new1/node_modules/next/src/server/next.ts:206:23
    at NextServer.prepare (.../new1/node_modules/next/src/server/next.ts:144:20)
```

### Package Manager Version

10.2.3

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Hi, thanks for giving the reproduction steps.

A workaround would be to update your custom server `apps/www/server/main.ts` to point to your artifacts.
In your case it would be inside `dist/` so something like this should work.

```ts
import { workspaceRoot } from 'nx/src/devkit-exports';
//....
const dev = process.env.NODE_ENV === 'development';
const dir = dev ? path.join(__dirname, '..') : path.join(workspaceRoot, 'dist', 'apps', 'www');

//...
```

While you wait for a patch release.
