### ISSUE TITLE
nx serve does not bind to ip address

### ISSUE THREAD

**Issue by naishe** [nrwl/nx#2123]
Hey guys,

I am developing a React webapp using Nx. I require this app to test on phone. But I cannot access it over wi-fi using the ip address. Is there a way to ensure nx binds to `0.0.0.0` instead of `localhost` so that I can access it using http://192.168.0.102:4200 ?

This is how `netstat` looks like

```
tcp4       0      0  192.168.0.102.63776    104.21.212.16.https    ESTABLISHED
tcp4       0      0  localhost.4200         localhost.63645        ESTABLISHED
tcp4       0      0  localhost.63645        localhost.4200         ESTABLISHED
```

**Comment by Cammisuli** [comment]
Can you try running this command, and let me know how it goes?
```
yarn nx serve --host=0.0.0.0
```

**Comment by vsavkin** [comment]
Unfortunately because of this this won't work: https://github.com/nrwl/nx/blob/master/packages/web/src/builders/dev-server/dev-server.impl.ts#L80

We should remove it. 

@naishe I think the only way for now is to update your `/etc/hosts` to remap localhost to `0.0.0.0`. 

You can also write a postinstall script that will update the node moduels and will replace:

```
        hostname:
          serveOptions.host === '0.0.0.0' ? 'localhost' : serveOptions.host,
```

with

```
        hostname:
          serveOptions.host === '0.0.0.0' ? '0.0.0.0' : serveOptions.host,
```

**Comment by FrozenPandaz** [comment]
Fixed by #2129

**Comment by koshpendi** [comment]
still can not rich it over wi-fi using the ip address.

**Comment by quangv** [comment]
i had to do...

`yarn nx serve --host 0.0.0.0 --publicHost dev.local`

(i mapped dev.local to the ip address of my dev box on my dev machine in `/etc/hosts`, prolly would work with ip address.)

**Comment by quolpr** [comment]
For npm users: `npm run nx serve -- --host=0.0.0.0`

**Comment by piotros** [comment]
`--host=0.0.0.0` works for me also.

By default fresh nx workspace has `nx serve` as a starting script so that should be enough for most of npm users:
`npm start -- --host=0.0.0.0`

**Comment by Serhii-the-Dev** [comment]
None of the suggestions are working anymore (at least with `next` v12), you need to specify the `hostname` attribute either via a command line:
```
yarn start app --hostname 0.0.0.0
```
or via a `serve` target options:
```
"serve": {
  "executor": "@nrwl/next:server",
  "options": {
    "buildTarget": "app:build",
    "port": 3000,
    "hostname": "0.0.0.0",
    "dev": true
  },
  "configurations": {
    ...
  }
}
```

**Comment by achantz** [comment]
> None of the suggestions are working anymore (at least with `nx` v13 and `next` v12), you need to specify the `hostname` [attribute ](https://nx.dev/next/server#hostname) either via a command line:
> 
> ```
> yarn start app --hostname 0.0.0.0
> ```
> 
> or via a `serve` target options:
> 
> ```
> "serve": {
>   "executor": "@nrwl/next:server",
>   "options": {
>     "buildTarget": "app:build",
>     "port": 3000,
>     "hostname": "0.0.0.0",
>     "dev": true
>   },
>   "configurations": {
>     ...
>   }
> }
> ```
Small correction:
"hostname": "0.0.0.0" should be "host": "0.0.0.0" to be picked up by the npm start command.

Hope this helps.
