### ISSUE TITLE
Tailwind breaks style imports in remix based nx standalone app

### ISSUE THREAD

**Issue by ArthurFoucher** [nrwl/nx#21234]
### Current Behavior

I'm struggling to create a NX workspace for a Remix app with Tailwind support.
Specifically, creating a bare bones react standalone workspace, adding a remix app via the plugin and adding tailwind support makes the app crash when importing css files.

### Expected Behavior

I expect the app to start properly, load css files and support tailwind styling.

### GitHub Repo

https://github.com/ArthurFoucher/nx-remix-tailwind-error-repro

### Steps to Reproduce

1. Run this
```sh
# Create a nx monorepo with
# - react standalone
# - CSS
npx create-nx-workspace acme --e2eTestRunner=none --nxCloud=skip --workspaceType=standalone  --preset=react-standalone --appName=acme --bundler=vite --style=css

cd acme
# Add nx-wrapped remix
npm install --save-dev @nx/remix

# Create a remix app
npx nx g @nx/remix:app myapp --unitTestRunner=vitest --e2eTestRunner=none
npx nx build myapp
```

2. Add a css file at `myapp/app/styles.css`, with any content, such as
```
* {
  background-color: aliceblue;
}
```
3. Use it in the root Remix app file:
```ts

import styles from './styles.css';

export const links: LinksFunction = () => [{ href: styles, rel: 'stylesheet' }];
```

4. Add tailwind to the app
```sh
# Setup tailwind in the remix app
npx nx g @nx/react:setup-tailwind --project=myapp
```

5. Serve the application
```sh
npx nx serve myapp
```

### Nx Report

```shell
Node   : 18.17.1
   OS     : darwin-arm64
   npm    : 9.6.7
   
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/react          : 17.2.8
   @nx/remix          : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/vite           : 17.2.8
   @nx/web            : 17.2.8
   typescript         : 5.2.2
```

### Failure Logs

```shell
> nx run myapp:serve

 💿  remix dev
 info  building...
✘ [ERROR] require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and 'path/to/projects/acme/myapp/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension. [plugin css-file]
    app/root.tsx:21:19:
      21 │ import styles from './styles.css';
         ╵                    ~~~~~~~~~~~~~~
  This error came from the "onLoad" callback registered here:
    ../node_modules/@remix-run/dev/dist/compiler/plugins/cssImports.js:77:12:
      77 │       build.onLoad({
         ╵             ~~~~~~
    at setup (path/to/projects/acme/node_modules/@remix-run/dev/dist/compiler/plugins/cssImports.js:77:13)
    at handlePlugins (path/to/projects/acme/node_modules/@remix-run/dev/node_modules/esbuild/lib/main.js:1279:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
It looks like you used the wrong generator when adding tailwind.

Note you have used `npx nx g @nx/react:setup-tailwind --project=myapp`. 

This sets up Tailwind specifically for a React project, and not a Remix project. There are some key differences between how things are generated for both types of projects.

When generating the Tailwind setup for Remix, we generate TS ESM-based config for Tailwind, and we do not generate a `postcss.config.js` file.

If you use 
`npx nx g @nx/remix:setup-tailwind --project-myapp` you should not run into any difficulties.

I have a sample repo here which followed your reproduction steps but I used `@nx/remix:setup-tailwind` instead:
https://github.com/Coly010/nx-remix-tailwind-sample

**Comment by ArthurFoucher** [comment]
Thanks, I appreciate the help !
A suggestion I can give is to make it more prominent in the docs, I didn't see a mention of this package when I was looking at it, I may not be the only one 🙂
