### ISSUE TITLE
GLOBAL_NX_VERSION

### ISSUE THREAD

**Issue by thienhoanguit** [nrwl/nx#21270]
### Current Behavior

Run command
`nx report`

Output:

> C:\Users\HHT8HC\AppData\Roaming\npm\node_modules\nx\bin\nx.js:128
>     globalThis.GLOBAL_NX_VERSION ??= GLOBAL_NX_VERSION;
>                                  ^^^
> 
> SyntaxError: Unexpected token '??='
> ←[90m    at wrapSafe (internal/modules/cjs/loader.js:1001:16)←[39m
> ←[90m    at Module._compile (internal/modules/cjs/loader.js:1049:27)←[39m
> ←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)←[39m
> ←[90m    at Module.load (internal/modules/cjs/loader.js:950:32)←[39m
> ←[90m    at Function.Module._load (internal/modules/cjs/loader.js:790:14)←[39m
> ←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m
> ←[90m    at internal/main/run_main_module.js:17:47←[39m

`node -v`
> v14.17.3

`ng version`
> Angular CLI: 10.2.4
> Node: 14.17.3
> OS: win32 x64
> 
> Angular:
> ...
> Ivy Workspace:
> 
> Package                      Version
> ------------------------------------------------------
> @angular-devkit/architect    0.1002.4 (cli-only)
> @angular-devkit/core         10.2.4 (cli-only)
> @angular-devkit/schematics   10.2.4 (cli-only)
> @schematics/angular          10.2.4 (cli-only)
> @schematics/update           0.1002.4 (cli-only)

### Expected Behavior

report work normal

### Steps to Reproduce

1. Open cmd
2. type `nx report` and enter
3. view result

### Nx Report

```shell
C:\Users\HHT8HC\AppData\Roaming\npm\node_modules\nx\bin\nx.js:128
    globalThis.GLOBAL_NX_VERSION ??= GLOBAL_NX_VERSION;
                                 ^^^

SyntaxError: Unexpected token '??='
←[90m    at wrapSafe (internal/modules/cjs/loader.js:1001:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1049:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:950:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:790:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m
```

### Package Manager Version

npm --version 6.14.13

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by NgDaddy** [comment]
Hi,

According to the [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment#browser_compatibility), Logical nullish assignment is available for Node.js 15.0.0.

@thienhoanguit what is your NX version installed in the project?

**Comment by AgentEnder** [comment]
You need to update Node JS. Nx currently supports node 18.x and 20.x versions. See: https://nx.dev/getting-started/intro#nx-nodejs-and-typescript-compatibility-matrix

**Comment by airowe** [comment]
@AgentEnder I'm still seeing this on CircleCI when trying to kick off an Android build.

```
 Node   : 18.16.1
   OS     : darwin-arm64
   npm    : 9.5.1

   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/detox          : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/react          : 17.2.8
   @nx/react-native   : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   typescript         : 5.2.2
```

**Comment by AgentEnder** [comment]
The **_only_** way for this to happen is if you have an outdated node installation, you'll need to update that on your CI pipeline
