### ISSUE TITLE
【cacheDirectory】 Custom Location

### ISSUE THREAD

**Issue by jieLi086** [nrwl/nx#21296]
###  cacheDirectory can dynamic directories be supported ？ 

for example

"cacheDirectory": "$HOME/nx/cache/"   ->  /（user root）/nx/cache/

or

variables can be passed ：   "cacheDirectory": "$path/nx/cache/"   ...

**Comment by AgentEnder** [comment]
The cache storage can be controlled via environment variables, which is what I'd recommend for this. https://nx.dev/reference/environment-variables#environment-variables
