### ISSUE TITLE
Failed to create workspace

### ISSUE THREAD

**Issue by wardbell** [nrwl/nx#213]
Did a clean installation of NX and CLI, per instructions on web site:
```
npm install -g @nrwl/schematics 
npm install -g @angular/cli
```
Versions are
```
@angular/cli@1.6.5
@nrwl/schematics@0.6.13
```
I run `create-nx-workspace demo` and it fails with
```
Creating a sandbox with the CLI and Nx Schematics...
[fsevents] Success: "/private/var/folders/zt/gn3lrvp9609gz_qgcc6c17mr0000gn/T/tmp-87824yujjV3jYkT1Y/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
Cached binary found at /Users/Ward/.npm/node-sass/4.7.2/darwin-x64-57_binding.node
Binary found at /private/var/folders/zt/gn3lrvp9609gz_qgcc6c17mr0000gn/T/tmp-87824yujjV3jYkT1Y/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine
added 1009 packages in 24.565s
ng new "ngrx-data" --collection=@nrwl/schematics
module.js:540
    throw err;
    ^

Error: Cannot find module '@angular-devkit/core'
```
No directory created. No obvious traces of activity left behind on disk.

Running node v.8.9.4 and npm v.5.6.0 on Mac OS High Sierra

**Comment by hubbergit** [comment]
Same problem here as well:

- Node 8.9.3
- NPM 5.6.0
- Angular CLI 1.6.5 (<= I think this is the problem)
- Windows 10

**Comment by DefunctExodus** [comment]
Same problem here

- Node 8.4.0
- Yarn 1.3.2
- Angular CLI 1.6.3
- Fedora 27

**Comment by DickSmith** [comment]
I had the same issue, seems to be related to stuff discussed here https://github.com/angular/angular-cli/issues/9194.

I found the following workaround, though:
```
npm un -g @angular-devkit/core @angular-devkit/schematics @schematics/angular @nrwl/schematics @angular/cli
npm i -g @angular-devkit/core
npm i -g @angular-devkit/schematics
npm i -g @schematics/angular
npm i -g @nrwl/schematics
npm i -g @angular/cli
```
Once finished your global tree should look something like this:
```
~$ npm -g ls --depth=0
~/.nvm/versions/node/v8.9.1/lib
├── @angular-devkit/core@0.0.28
├── @angular-devkit/schematics@0.0.51
├── @angular/cli@1.6.5
├── @nrwl/schematics@0.6.13
├── @schematics/angular@0.1.16
└── npm@5.6.0
```

After that I ran:
```
ng new "PROJECT_NAME" --collection=@nrwl/schematics # same as what create-nx-workspace does, but I still had issues when running create-nx-workspace
```
And the project was successfully created.

You will then need to `cd` into the created project and run:
```
npm i @angular-devkit/core
```
To be able to generate apps, libs, components, etc.

__Environment:__
* Mac OS X Sierra 10.12.6 (16G1036)
* Node 8.9.1
* NPM 5.6.0

__Notes:__
I also discovered that installing them all inline as:
```
npm i -g @angular-devkit/core @angular-devkit/schematics @schematics/angular @nrwl/schematics @angular/cli
```
results in:
```~$ npm -g ls --depth=0
~/.nvm/versions/node/v8.9.1/lib
├── @angular/cli@1.6.5
├── @nrwl/schematics@0.6.13
└── npm@5.6.0
```
which will still result in the same errors. Which is why I suggest just uninstalling them all and then reinstalling one-by-one in that order.

**Comment by russoturisto** [comment]
I was successfully able to generate a new project with the workaround.  Thank you! :)

**Comment by vsavkin** [comment]
The CLI removed the dependency on `@angular-devkit/core`. I released a new version of Nx that has fixed it.

FYI: the only package you need to to be able to run `create-nx-workspace` is `@nrwl/schematics`. You don't need to install anything else globally.

**Comment by dixonsatit** [comment]
ng new workspace --col @nrwl/schematics
