### ISSUE TITLE
Module not found: Can't resolve '@sentry/utils' when using NextJS (app router) + Nx + pnpm

### ISSUE THREAD

**Issue by seanparmelee** [nrwl/nx#21329]
### Current Behavior

When running `nx build nextjs-app`, the build fails with

```
Failed to compile.

./app/api/hello/route.ts
Module not found: Can't resolve '@sentry/utils'
https://nextjs.org/docs/messages/module-not-found
./app/layout.tsx
Module not found: Can't resolve '@sentry/utils'
https://nextjs.org/docs/messages/module-not-found
./app/page.tsx
Module not found: Can't resolve '@sentry/utils'
https://nextjs.org/docs/messages/module-not-found
> Build failed because of webpack errors
Error occurred while trying to run the build command
```

### Expected Behavior

`nx build nextjs-app` succeeds

### GitHub Repo

https://github.com/seanparmelee/sentry-nextjs-nx-issue

### Steps to Reproduce

1. Clone the reproduction repo
2. Run `pnpm install`
3. Run `nx build nextjs-app`

### Nx Report

```shell
Node   : 20.10.0
   OS     : darwin-arm64
   pnpm   : 8.13.1

   nx (global)    : 17.2.8
   nx             : 17.2.8
   @nx/eslint     : 17.2.8
   @nx/workspace  : 17.2.8
   @nx/next       : 17.2.8
   @nrwl/tao      : 17.2.8
   typescript     : 5.2.2
```

### Failure Logs

```shell
> nx run nextjs-app:build:production

   ▲ Next.js 14.1.0
   Creating an optimized production build ...
Failed to compile.

./app/api/hello/route.ts
Module not found: Can't resolve '@sentry/utils'
https://nextjs.org/docs/messages/module-not-found
./app/layout.tsx
Module not found: Can't resolve '@sentry/utils'
https://nextjs.org/docs/messages/module-not-found
./app/page.tsx
Module not found: Can't resolve '@sentry/utils'
https://nextjs.org/docs/messages/module-not-found
> Build failed because of webpack errors
Error occurred while trying to run the build command
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

When I was creating this reproduction, I tried to take away a few more variables, but I couldn't reproduce the issue if I:

* replaced pnpm w/ npm
* used only the NextJS pages router (the issue still reproduces if both the pages and app routers are used)
* took Nx out of the equation

So it seems like it's something with the combination of these 🤷

As a workaround, we just added `@sentry/utils` as a dependency to the app, but it would be nice to not to have to do that since we're not explicitly using that dependency.

I also reported this in the [Sentry repo](https://github.com/getsentry/sentry-javascript/issues/10306), but it sounds like this issue may be caused by something Nx is doing.

**Comment by RicardoUU** [comment]
I've encountered the same issue. Using `pnpm nx xxx xxx` to run commands doesn't cause any problems.🤔

**Comment by seanparmelee** [comment]
I wish I would've saw your comment earlier @RicardoUU!
I've since removed my global install of Nx and can no longer reproduce this issue. Interestingly enough, if I reinstall `17.2.8` globally (which is apparently the version I had installed at the time), I still can't reproduce it anymore 🤷
