### ISSUE TITLE
React, Node Nx Mono repo build and run issue

### ISSUE THREAD

**Issue by Abirami-Manisa** [nrwl/nx#21326]
### Current Behavior

Currently, I have a monorepo, which is built using Node API stack , with express framework, with Dockerfile generated.
There is another application and library created using ReactTS. 
When I try to build the node application, the build is obtained with the apps and libs in the same folder.
But for the React application, the apps and libs are generated in a different folder in dist.

### Expected Behavior

I need the application to be built in a similar way as in Node Application and also the Dockerfile for the React application as well

### Steps to Reproduce

1.npx create-nx-workspace@latest with the stack as Node API, framework as express, and Dockerfile generated
2. Generate ReactTS applications
3. Generate libraries for React and Node

### Nx Report

```shell
The build works when provided nx preview. But I need to run them from dist folder
```

### Package Manager Version

nx version :v17.2.8, npm :10.2.3

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
What executor are you using to build the applications?

**Comment by Abirami-Manisa** [comment]
> What executor are you using to build the applications?

I'm using Vite to build the applications for React
