### ISSUE TITLE
releasePublish uses process.exit making it unsuitable for programmatic use

### ISSUE THREAD

**Issue by jeffora** [nrwl/nx#21321]
### Current Behavior

When using `releasePublish` programmatically via `import { releasePublish } from 'nx/release;`, successful invocations will result in the method calling `process.exit(0)`, while errors call `process.exit(1)`. This makes this unsuitable for programmatic consumption, as it is not possible to `try/catch` errors, or perform additional tasks after successfully running.

E.g., the following code does not work (does not print the logged line):

```ts
import { releasePublish } from 'nx/release';

await releasePublish({ projects: ['my-project'] });
console.log('Publishing successful');
```

### Expected Behavior

To support programmatic consumption, the method `releasePublish` should throw errors or return results. A CLI wrapper could easily convert these into `process.exit` commands but allow programmatic consumers to perform their own error handling and clean up tasks.

### Steps to Reproduce

1.
```ts
import { releasePublish } from 'nx/release';

await releasePublish({ projects: ['my-project'] });
console.log('Publishing successful');
```

### Nx Report

```shell
NA
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JamesHenry** [comment]
Thanks @jeffora, this has already been addressed in https://github.com/nrwl/nx/pull/21338 and is available in the 17.3 RC

**Comment by jeffora** [comment]
Thanks @JamesHenry that's great. I'll take a look at the RC and revert our workaround

**Comment by JamesHenry** [comment]
Cool, thanks @jeffora - please note there was a regression this introduced for the CLI usage, fixed here: https://github.com/nrwl/nx/pull/21388
