### ISSUE TITLE
List possible interpolated values in nx.json more clearly

### ISSUE THREAD

**Issue by ryanbas21** [nrwl/nx#21339]
### Documentation issue

- [x] Documentation improvement

nx.json related docs

[Enter the URL or documentation section here.](https://nx.dev/reference/nx-json#nxjson)

### Additional context or description

It would be nice to have a more clearly listed set of values that we can use in nx.json to programatically set up some of the nx workspace. For example, there are things like

`version`, `workspaceRoot`, `projectRoot`

From looking at this page, this is all I can tell that is accepted. 

There is a small block here

```
When defining any options or configurations inside of a target default, you may use the {workspaceRoot} and {projectRoot} tokens. This is useful for defining things like the outputPath or tsconfig for many build targets.
```

But I'm not sure if this means that is the entirety of the api. It could. For example if `projectDirectory` was an option, i could customize my generators to use an output path that is something like

```
${workspaceRoot}/${projectDirectory}/${projectName}/dist
```

But i don't think this is an option. would just be nice if there was the complete list laid out and if it grew it would be easy to update / see whats new in this api.

**Comment by AgentEnder** [comment]
For targets the only valid interpolations are {projectRoot}, {workspaceRoot}, and {projectName}. The `{version}` token and some others may be usable inside `nx release`, but would not make sense for target options as the tasks runner isn't aware of the versions of your package to be able to make the substitution

**Comment by isaacplmann** [comment]
The available options are listed here: https://nx.dev/recipes/running-tasks/configure-outputs#output-files

There are still only those 3 possible interpolated values.  If that list grows, we'll make a table.
