### ISSUE TITLE
Nx skips linting tasks when eslint plugins are updated

### ISSUE THREAD

**Issue by alfaproject** [nrwl/nx#21347]
### Current Behavior

When an eslint plugin (or even eslint itself) is updated, let's say @typescript-eslint as an example Nx does not run linting tasks for all the projects and it's leaving my colleagues wondering why totally unrelated files to their PRs sometimes expose linting issues not related to the files they updated.

Am I doing something wrong or is there a way to signal Nx to force linting when some node modules update?

### Expected Behavior

If eslint or any eslint plugin is updated like @typescript-eslint then Nx runs linting tasks again for the whole project

### 1. Create any Nx workspace
```
% npx create-nx-workspace --pm yarn
Need to install the following packages:
create-nx-workspace@17.2.8
Ok to proceed? (y) y

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Where would you like to create your workspace? · nx17
✔ Which stack do you want to use? · node
✔ What framework should be used? · express
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · nx17
✔ Would you like to generate a Dockerfile? [https://docs.docker.com/] · No
✔ Enable distributed caching to make your CI faster · No

 >  NX   Creating your v17.2.8 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "yarn install" several times. Please wait.

✔ Installing dependencies with yarn
...
✔ Successfully created the workspace: nx17.
```

### 2. Run linting for the whole project
```
% cd nx17
% yarn nx run-many -t lint
yarn run v1.22.19
$ /Users/alfa/the-mill/nx17/node_modules/.bin/nx run-many -t lint

    ✔  nx run nx17:lint (3s)
    ✔  nx run nx17-e2e:lint (3s)

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target lint for 2 projects (3s)

✨  Done in 7.42s.
```

### 3. Update eslint (or any eslint plugin) to another version
```
% yarn add --dev eslint@8.56.0
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 5 new dependencies.
info Direct dependencies
└─ eslint@8.56.0
info All dependencies
├─ @eslint/eslintrc@2.1.4
├─ @eslint/js@8.56.0
├─ @humanwhocodes/config-array@0.11.14
├─ @ungap/structured-clone@1.2.0
└─ eslint@8.56.0
✨  Done in 3.75s.
```

### 4. Run linting again for the whole project
```
% yarn nx run-many -t lint
yarn run v1.22.19
$ /Users/alfa/the-mill/nx17/node_modules/.bin/nx run-many -t lint

    ✔  nx run nx17:lint  [existing outputs match the cache, left as is]
    ✔  nx run nx17-e2e:lint  [existing outputs match the cache, left as is]

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target lint for 2 projects (217ms)

   Nx read the output from the cache instead of running the command for 2 out of 2 tasks.

✨  Done in 0.99s.
```

### Nx Report

```shell
% yarn nx report
yarn run v1.22.19
$ /Users/alfa/the-mill/nx17/node_modules/.bin/nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : darwin-x64
   yarn   : 1.22.19

   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/esbuild        : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/node           : 17.2.8
   @nrwl/tao          : 17.2.8
   typescript         : 5.2.2

✨  Done in 1.05s.
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
The inputs to the lint task can be configured with ` { externalDependencies: ['my-eslint-plugin'] } ` to add these packages to the cache / affected calculations

**Comment by alfaproject** [comment]
The documentation for that seems to imply that overrides the default NPM dependencies that Nx discovers from the project graph with the ones we set in `externalDependencies` but I don't want to remove the project graph dependencies either

**Comment by meeroslav** [comment]
You are correct, @alfaproject; this should have been affecting the graph.

The graph incorrectly skips a connection between `eslint` and `@nx/eslint` because `eslint` is set as a peer dependency.

The `@typescript-eslint` or any other ESLint plugins would unfortunately not work in the classic ESLint config since they are resolved dynamically in the runtime, and Nx cannot know which are being used. This is solved in the new Flat Config where the previous implicit magic imports are now replaced by explicit imports in the config itself.

**Comment by meeroslav** [comment]
After looking into this a bit more, the yarn sadly does not track peer dependencies so lock file parsing cannot detect this dependency. 

Please note that this works correctly in pnpm and npm. I will add the support for yarn modern, but v1 is, unfortunately, hopeless.

**Comment by alfaproject** [comment]
Is there a way to use @AgentEnder suggestion but without overriding the graph and instead just let it know about these implicit external dependencies? Migrating to the new eslint flat config isn't an option right now, I just don't have the capacity

**Comment by meeroslav** [comment]
@alfaproject, I totally understand. Switching to the flat config is a big step.

Unfortunately, using `externalDependencies` does not work with `@nx/eslint:lint` executor, but you can use `eslint` directly.
We will announce a cool new feature in a few days that makes this switch significantly easier.

**Comment by meeroslav** [comment]
You can change your `lint` targets to something like this:

```jsonc
    "lint": {},
```

And then use `nx.json`'s `targetDefaults`:
```jsonc
{
  ...
  "targetDefaults": {
    ...
    "lint": {
      "inputs": [
        "default",
        "{workspaceRoot}/.eslintrc.json",
        "{workspaceRoot}/tools/eslint-rules/**/*",
        { externalDependencies: ["eslint", "@typescript-eslint/eslint-plugin", ...] }
      ],
      "command": "eslint .",
      "options": {
        "cwd": "{projectRoot}"
      },
      "cache": true
    },
  }
}
```

This means that each lint target will read from the target defaults and would apply `eslint .` on the root of the project while respecting the external dependencies listed when calculating the hash for caching.

**Comment by alfaproject** [comment]
@meeroslav we actually use target defaults already:
```json
  "targetDefaults": {
    ...
    "lint": {
      "cache": true,
      "executor": "@nx/eslint:lint",
      "inputs": ["default", "{workspaceRoot}/.eslintrc.json"],
      "outputs": ["{options.outputFile}"]
    },
```

However, I was under the impression that adding `{ externalDependencies: [...] }` to the inputs overrides the graph and it doesn't just add those dependencies to the already existing graph. Like for example if I have some other dependency in a project that gets updated, let's say '@slack/web' or whatever, then I'd like the lint to also re-run for the projects using that dependency
