### ISSUE TITLE
.nxignore documentation lacks details

### ISSUE THREAD

**Issue by ItamarGronich** [nrwl/nx#21345]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [X] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

The `.nxignore` reference page: https://nx.dev/reference/nxignore

### Additional context or description

The `.nxignore` reference page says that files or folders specified in the `.nxignore` files are _completely_ ignored by Nx which is not true.
They are ignored from affected calculations, however they are included in nx cache calculation.

**Comment by AgentEnder** [comment]
I don't think they should be considered. I'll take a look and see whats going on.

**Comment by AgentEnder** [comment]
I was able to validate that adding files to .nxignore prevents Nx from finding the project and omits the file from the hash. If you are not seeing that behavior feel free to open a bug report for more troubleshooting.
