### ISSUE TITLE
@nrwl/angular:library runs a NodePackageInstallTask when unnecessary

### ISSUE THREAD

**Issue by jdpearce** [nrwl/nx#2137]
## Expected Behavior

It should be possible to generate a library without running the npm install task. e.g. by passing `--skip-install` or `--skip-package-json` options.

## Current Behavior

`ng g lib <library>` will *always* run a NodePackageInstallTask

This is down to the `addUnitTestRunner` rule:

https://github.com/nrwl/nx/blob/ac33f049b24f2246140d10e733828bc58947340c/packages/angular/src/schematics/library/library.ts#L445

Perhaps this rule could be updated to pay attention to those flags?

**Comment by semtos** [comment]
+1

**Comment by brandonroberts** [comment]
I tried this with the latest release and it no longer runs install tasks unless `--publishable` is provided.
