### ISSUE TITLE
Angular 17 production bundle built with nx build cannot be served with Node

### ISSUE THREAD

**Issue by he1dj** [nrwl/nx#21373]
### Current Behavior

Nx v.17.2.8, Node v.20.10.0

_nx build -> node dist/project/server/server.mjs_
**Output**: absolutely nothing
![image](https://github.com/nrwl/nx/assets/84002636/4281d51d-4f90-400b-bbbc-311fe9a9d464)

_ng new -> ng build -> node dist/project/server/server.mjs_
**Output**: properly running Express server for serving an SSR application.
![image](https://github.com/nrwl/nx/assets/84002636/23656c1e-0600-4498-9996-ddd5cf47c7cc)

Even in a completely new nx  Angular standalone workspace, Node cannot serve dist/project/server/server.mjs. Same result on Windows 11 and Ubuntu 23.10.

### Expected Behavior

I expect my SSR application to easily run via Node.

### Steps to Reproduce

1. npx create-nx-workspace
2. project name
3. Angular 
4. Standalone
5. esbuild
6. SCSS
7. Enable SSR
8. Cypress
9. Enable distibuted caching
10. nx build
11. node dist/project/server/server.mjs

### Nx Report

```shell
PS C:\Users\sakta\Documents\Dev\Projects\blog\iliveindubai> nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : win32-x64
   npm    : 10.4.0
   
   nx (global)        : 17.2.6
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/angular        : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/playwright     : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   typescript         : 5.2.2
```

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This was fixed by https://github.com/nrwl/nx/pull/21157, which was released in v17.3.0. Please, make sure to migrate to the latest version or if you can't migrate right now, add a `run()` at the end of the generated `server.ts` file.
