### ISSUE TITLE
NX semantics install  leads to build errors which are super harsh for developers to debug 

### ISSUE THREAD

**Issue by montella1507** [nrwl/nx#21377]
### Current Behavior

When you generate something with NX semantics which leads to packages update, it can easily lead to packages conflicts, after that a developer can get super-missleaing errors.

One example:

ENVIRONMENT
Node 20.9.0  LTS 
Nx Version v17.2.8
All packages up-to-date (angular 17.1.0 etc)

Generate library:
`nx g @nx/angular:library --name=analytics --buildable=true --directory=libs/shared --changeDetection=OnPush --displayBlock=true --importPath=@cue/analytics --prefix=cue --projectNameAndRootFormat=derived --skipModule=true --skipTests=true --style=scss --unitTestRunner=none`

IT will for no-reason update package.json and it tries to install packages.
```
    "@swc-node/register": "~1.6.7",
    "@swc/core": "~1.3.85",
 "jsonc-eslint-parser": "^2.1.0",
```

It will throws error during installation of packages - not compatible with LTS of node js:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@es-joy/jsdoccomment@0.36.1',
npm WARN EBADENGINE   required: { node: '^14 || ^16 || ^17 || ^18 || ^19' },
npm WARN EBADENGINE   current: { node: 'v20.9.0', npm: '10.1.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.18.4',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm WARN EBADENGINE   current: { node: 'v20.9.0', npm: '10.1.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'eslint-plugin-jsdoc@39.6.2',
npm WARN EBADENGINE   required: { node: '^14 || ^16 || ^17 || ^18 || ^19' },
npm WARN EBADENGINE   current: { node: 'v20.9.0', npm: '10.1.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.18.4',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm WARN EBADENGINE   current: { node: 'v20.9.0', npm: '10.1.0' }
npm WARN EBADENGINE }
```

Now, when trying to build:
```
✘ [ERROR] Angular compilation initialization failed. [plugin angular-compiler]

  Error: Cannot resolve type entity i11.IconsModule to symbol
      at reflectTypeEntityToDeclaration (file:///Users/marianbencat/WebstormProjects/touchONE-assist/node_modules/@angular/compiler-cli/bundles/chunk-3WRR7A6G.js:544:11)
      at extraReferenceFromTypeQuery (file:///Users/marianbencat/WebstormProjects/touchONE-assist/node_modules/@angular/compiler-cli/bundles/chunk-GM44CTB7.js:1456:26)
      at file:///Users/marianbencat/WebstormProjects/touchONE-assist/node_modules/@angular/compiler-cli/bundles/chunk-GM44CTB7.js:1451:12
      at Array.map (<anonymous>)
      at extractReferencesFromType (file:///Users/marianbencat/WebstormProjects/touchONE-assist/node_modules/@angular/compiler-cli/bundles/chunk-GM44CTB7.js:1447:23)
      at DtsMetadataReader.getNgModuleMetadata (file:///Users/marianbencat/WebstormProjects/touchONE-assist/node_modules/@angular/compiler-cli/bundles/chunk-GM44CTB7.js:1651:16)
      at CompoundMetadataReader.getNgModuleMetadata (file:///Users/marianbencat/WebstormProjects/touchONE-assist/node_modules/@angular/compiler-cli/bundles/chunk-GM44CTB7.js:1602:27)
      at StandaloneComponentScopeReader.getScopeForComponent (file:///Users/marianbencat/WebstormProjects/touchONE-assist/node_modules/@angular/compiler-cli/bundles/chunk-YFIBJR5K.js:2449:48)
      at CompoundComponentScopeReader.getScopeForComponent (file:///Users/marianbencat/WebstormProjects/touchONE-assist/node_modules/@angular/compiler-cli/bundles/chunk-GM44CTB7.js:2819:27)
      at ComponentDecoratorHandler.resolve (file:///Users/marianbencat/WebstormProjects/touchONE-assist/node_modules/@angular/compiler-cli/bundles/chunk-GM44CTB7.js:6994:36)
```

Because it has somehow broken packages / cache / seomthing in node modules:

Why ? Why should have schematic added additional packages, when not migrating to newer version of schematics / packages etc?

It should have only generated code,  not update packages in package.json

Especially if it is not compatible with LTS version of node.js

### Expected Behavior

Several possible solutions:
A) do not update packages, at least when they are not compatible with LTS of node.js
B) add option to skip install (it is not  in NX console either)
C) Atleast warn user about the the possible problems

This behavior leads in not required difficulties.

### Steps to Reproduce

 Explained in description.

### Nx Report

```shell
Node   : 20.9.0
   OS     : darwin-arm64
   npm    : 10.1.0
   
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/angular        : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   nx-cloud           : 16.5.2
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome    : 0.14.1
   @ng-bootstrap/ng-bootstrap          : 16.0.0
   @ngneat/transloco                   : 4.3.0
   @ngrx/component-store               : 17.1.0
   @ngrx/effects                       : 17.1.0
   @ngrx/entity                        : 17.1.0
   @ngrx/router-store                  : 17.1.0
   @ngrx/store                         : 17.1.0
   @ngrx/store-devtools                : 17.1.0
   @progress/kendo-angular-barcodes    : 14.3.0
   @progress/kendo-angular-buttons     : 14.3.0
   @progress/kendo-angular-dateinputs  : 14.3.0
   @progress/kendo-angular-dialog      : 14.3.0
   @progress/kendo-angular-dropdowns   : 14.3.0
   @progress/kendo-angular-editor      : 14.3.0
   @progress/kendo-angular-inputs      : 14.3.0
   @progress/kendo-angular-intl        : 14.3.0
   @progress/kendo-angular-l10n        : 14.3.0
   @progress/kendo-angular-label       : 14.3.0
   @progress/kendo-angular-layout      : 14.3.0
   @progress/kendo-angular-listview    : 14.3.0
   @progress/kendo-angular-menu        : 14.3.0
   @progress/kendo-angular-pager       : 14.3.0
   @progress/kendo-angular-popup       : 14.3.0
   @progress/kendo-angular-progressbar : 14.3.0
   @progress/kendo-angular-ripple      : 14.3.0
   @progress/kendo-angular-scrollview  : 14.3.0
   @progress/kendo-angular-toolbar     : 14.3.0
   @progress/kendo-angular-tooltip     : 14.3.0
   @progress/kendo-angular-treeview    : 14.3.0
   @rx-angular/cdk                     : 1.0.0
   @rx-angular/state                   : 1.7.0
   @rx-angular/template                : 1.1.0
   angular-calendar                    : 0.31.0
```

### Package Manager Version

10.1.0

### Operating System

- [X] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

The `@nx/angular:library` generator already provides an option to skip installing packages the plugin deems necessary: `skipPackageJson`. So, you could have run:

```
nx g @nx/angular:library analytics --buildable --directory=libs/shared --changeDetection=OnPush --displayBlock --importPath=@cue/analytics --prefix=cue --projectNameAndRootFormat=derived --skipModule --skipTests --style=scss --unitTestRunner=none --skipPackageJson
```

Additionally, the generator doesn't install any of those packages warning about using an unsupported engine, nor does any of the installed packages by the generator depend on them. So, that seems like a pretty specific issue of your setup that probably surfaces because of npm re-resolving deps when the packages were installed.

> Also, as unsolicited advise, please note that using `--projectNameAndRootFormat=derived` is deprecated, and in Nx v19, the `as-provided` format will be the way to generate projects and artifacts. We strongly recommend to start using the new format.

I'm closing this since there's already a way to skip installing dependencies. As advised, if you want to do so, please run the generator providing the `--skipPackageJson` flag.

**Comment by montella1507** [comment]
1) npm i      = no changes to package.json and package-lock.json
2) nx g @nx/angular:library --name=security --buildable=true --directory=shared --projectNameAndRootFormat=derived
updating package.json

<img width="1086" alt="image" src="https://github.com/nrwl/nx/assets/10418323/d92b99d0-f17f-4904-b6cb-804cd1a4ebf2">

It adds these two lines:

`    
"@swc-node/register": "~1.6.7",
 "@swc/core": "~1.3.85",
`

and then, it breaks build.

<img width="1416" alt="image" src="https://github.com/nrwl/nx/assets/10418323/0ee395f1-b70c-48ea-9651-8a622942e77c">

**Comment by leosvelperez** [comment]
You still ran the generator without providing the `--skipPackageJson` option. As I mentioned in my previous comment, if you want to skip making changes to your installed deps, you must run the generator with that flag (e.g. `nx g @nx/angular:lib my-lib --skipPackageJson ...`).

Either way, I'm glad you've resolved the issue now.

**Comment by montella1507** [comment]
Yes. Nx extension for webstorm does not Have this option, that Is why.
