### ISSUE TITLE
Module federation dev server assumes that the build target is the target that should be built for static remotes.

### ISSUE THREAD

**Issue by statop** [nrwl/nx#21394]
### Current Behavior

Module federation dev server assumes that the build target is the target that should be built for static remotes.

### Expected Behavior

Module federation dev server does not assume that the build target is the target that should be built for static remotes.

### Steps to Reproduce

1. Try to run module federation dev server with a static remote where the build target is not the correct target

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.17.1
   OS     : darwin-arm64
   pnpm   : 8.14.3

   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/angular        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/node           : 17.2.8
   @nx/plugin         : 17.2.8
   @nx/react          : 17.2.8
   @nx/rollup         : 17.2.8
   @nx/storybook      : 17.2.8
   @nx/vite           : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @openadp/tools-plugin : 24.5.0
   @storybook/angular    : 7.6.10
   ---------------------------------------
   Local workspace plugins:
   	 @openadp/tools-plugin
```

### Package Manager Version

pnpm  8.14.3

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

In the old module federation dev server, serve-static was used to serve static remotes. This allowed remotes to use something other than build for the webpack build. This no longer works.

For example sometimes I have webpack as a secondary target. And the main build target is tsc. TSC uses the webpack output as an asset that gets coppied into the output folder.

**Comment by Coly010** [comment]
Related: https://github.com/nrwl/nx/pull/19694

**Comment by csutorasr** [comment]
The ticket is might related, too. https://github.com/nrwl/nx/issues/19693 Please check if it is a dupe.
