### ISSUE TITLE
8.9.0 breaks DataPersistence again

### ISSUE THREAD

**Issue by jasedwards** [nrwl/nx#2140]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Calling datapersistence.fetch should not return invalid action error

## Current Behavior

datapersistence.fetch is return the invalid action error from a couple months ago when the rxjs version mismatch was identified.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.
Upgraded from 8.6.0 to 8.9.0.  Run dataPersistence.fetch.  I would love to provide a repo but as with most errors I see there is way different behavior for somebody like me who has been using nx since version 1 and generating a workspace from scratch.  I just don't know how to repo something like that.  I generated a new repo and don't get the error even though I have the exact same versions in my larger existing one.

Here is the specific error message when running the fetch. 

logger.service.ts:90 Effect "SplitManagerManagerEffects.searchSplitManager$" dispatched an invalid action: {"_isScalar":false,"source":{"_isScalar":false,"source":{"_isScalar":false,"source":{"_isScalar":false},"operator":{"resultSelector":{"_isScalar":false,"source":{"_isScalar":false,"source":{"_isScalar":false,"source":{"_isScalar":true,"value":{"url":"StarsOne/RMIS/STARS.Claim.mvc/Metadata/ManagerTotalItemCount","body":null,"reportProgress":false,"withCredentials":false,"responseType":"json","method":"GET","headers":{"normalizedNames":{},"lazyUpdate":null,"headers":{}},"params":{"updates":null,"cloneFrom":null,"encoder":{},"map":{}},"urlWithParams":"StarsOne/RMIS/STARS.Claim.mvc/Metadata/ManagerTotalItemCount?viewId=32&SessionMode=ReadOnly"}},"operator":{"concurrent":1}},"operator":{}},"operator":{}}}},"operator":{}},"operator":{}}

Here is the code.  fetchEntity returns an observable.

```
 return this.fetchEntity({
        domainName: SplitManagerManagerConstants.DomainName,
        packageName: SplitManagerManagerConstants.PackageName,

        sortInfo: state[SplitManagerManagerFeatureKey].Config.SortInfo,
        filter: state[SplitManagerManagerFeatureKey].Filter.Value,
        viewId: viewId,
        activePage: 1, // state[SplitManagerManagerFeatureKey].Config.ActivePage,
        includeTotalCount: true
      }).pipe(map(def => new fromSplitManagerManagerActions.Searched(def)));
```

### Context

Please provide any relevant information about your setup:
results of nx report:
```

  @nrwl/angular : 8.9.0
  @nrwl/cli : 8.9.0
  @nrwl/cypress : 8.9.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.9.0
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.9.0
  @nrwl/web : Not Found
  @nrwl/workspace : 8.9.0
  typescript : 3.5.3
```

here is version info:
```
Angular CLI: 8.3.3                                                
Node: 10.16.2                                                     
OS: win32 x64                                                     
Angular: 8.2.14                                                   
... animations, common, compiler, compiler-cli, core, forms       
... language-service, platform-browser, platform-browser-dynamic  
... router                                                        
                                                                  
Package                            Version                        
------------------------------------------------------------      
@angular-devkit/architect          0.803.3                        
@angular-devkit/build-angular      0.803.19                       
@angular-devkit/build-ng-packagr   0.803.19                       
@angular-devkit/build-optimizer    0.803.19                       
@angular-devkit/build-webpack      0.803.19                       
@angular-devkit/core               8.3.3                          
@angular-devkit/schematics         8.3.3                          
@angular/cdk                       8.2.3                          
@angular/cli                       8.3.3                          
@angular/material                  8.2.3                          
@ngtools/json-schema               1.1.0                          
@ngtools/webpack                   8.3.19                         
@schematics/angular                8.3.3                          
@schematics/clearsight             0.0.1                          
@schematics/update                 0.803.3                        
ng-packagr                         4.7.1                          
rxjs                               6.4.0                          
typescript                         3.5.3                          
webpack                            4.39.2                         
```

It does not list it here but I have also tried with NGRX versions 8.3.0 and 8.5.0

I was able to get around this by downgrading to version 8.8.3

**Comment by FrozenPandaz** [comment]
I was not able to repro this:

https://github.com/FrozenPandaz/nx-examples/tree/fetch-test

(I believe I have the same `ng v` and `nx report` output)

A repro would help us debug this issue.

**Comment by jasedwards** [comment]
@FrozenPandaz  I will try to find time this weekend to get a repo going.  My repo is very large with a lot of 3rd party libs.  will starting adding them to see if i can narrow it down

**Comment by jasedwards** [comment]
@FrozenPandaz  Ok, I need to do some more sanity checks this weekend but I noticed my versions of @angular-devkit/... were a version behind what you're using now.  I would not think that should matter since they are dev dependencies but perhaps?  They referenced rxjs 6.3 where as I am using 6.4.  I will run more checks over the weekend and comment.

**Comment by jasedwards** [comment]
updating angular-devkit fixed it.  I see that is imported all over polyfill so I can only guess that the different versions of rxjs used in devkit was the issue. I will make sure to keep my version of that in sync with yours in the future.  thanks.
