### ISSUE TITLE
NX' exported generator functions to accept inherited template folder

### ISSUE THREAD

**Issue by EelcoLos** [nrwl/nx#21456]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
When calling an exported generator function from NX (in this particular case the `ngrxFeatureStoreGenerator`) should use the template of the newly created generator.

```ts
import { ngrxFeatureStoreGenerator } from '@nx/angular/generators';
import { Tree } from '@nx/devkit';

export async function dmNgrxFeatureGenerator(tree: Tree) {
	await ngrxFeatureStoreGenerator(tree, {
		name: 'test',
		minimal: false,
		parent: 'libs/test/src/lib.routes.ts',
		facade: true,
		directory: ''
	});
}

export default dmNgrxFeatureGenerator;
```

The exported function should allow to have the templates of the calling function to be called, or the methods of the generator itself to be exposed

## Motivation
As stated by @ZackDeRose in the last webinar, people should have to copy all the files of NX to be tweaking some parameters they'd like. In that webinar, he referred to the discord thread: https://discord.com/channels/1143497901675401286/1194667985349115986 . 
I tried implementing it, like shown above. The templates of my own folder were not used.
Extending the functions in this way would make it open for extention, while the generator itself remains closed for modification

## Suggested Implementation
An additional property (maybe even part of the schema too, so this can even be used without even building a custom generator).

## Alternate Implementations
Expose the methods used in the generators, so we can extend the generator ourselves.

**Comment by AgentEnder** [comment]
I don't think we'd be open to allowing providing a fully custom template, as there may be places where after we generate the template we modify the contents or expect the contents to fulfill a certain criteria. If the user provided a template that didn't meet that criteria, the generator would crash when it hit a bad assumption.

Rather, I'd recommend calling the generator and letting it do its thing, and then calling `generateFiles` to override files with your custom templates and removing files that you don't wish with `tree.delete`. It would look something like this:

```typescript
import { ngrxFeatureStoreGenerator } from '@nx/angular/generators';
import { Tree, generateFiles, joinPathFragments } from '@nx/devkit';

export async function dmNgrxFeatureGenerator(tree: Tree, options) {
	await ngrxFeatureStoreGenerator(tree, {
		name: 'test',
		minimal: false,
		parent: 'libs/test/src/lib.routes.ts',
		facade: true,
		directory: ''
	});
    generateFiles(tree, joinPathFragments(__dirname, 'files'), options)
}

export default dmNgrxFeatureGenerator;
```
