### ISSUE TITLE
Add Expo 50 support

### ISSUE THREAD

**Issue by sem4phor** [nrwl/nx#21469]
## Description

Expo 50 was released recently with react-native 0.73. It has a lot of cool features and bugfixes.

## Motivation

As mentioned expo 50 + RN 0.73 have a lot of features which would be beneficial to everyone using expo/react-native :) 

## Suggested Implementation

Update peer dependencies and adjust withNxMetro config if needed.

**Comment by xiongemi** [comment]
got a pr https://github.com/nrwl/nx/pull/20896

**Comment by gerarts** [comment]
Any info on in which `@nx` version this will be released? Do we have to wait for `v18.0.0`?

**Comment by xiongemi** [comment]
it is a part of nx 18
