### ISSUE TITLE
nx serve no longer working when launched from script

### ISSUE THREAD

**Issue by cvlmtg** [nrwl/nx#21478]
### Current Behavior

We have an npm monorepo which was configured with `npx nx@latest init`. When we serve our app, we run a script that generates some configs, copies some files etc and then launches `nx serve <appName>`. It always worked fine until we upgraded from nx 17.2.8 to nx 17.3.1. Now the serve command no longer works when launched from our script, but it works if I run it manually from the shell. The strange thing is that in the serve output has appeared a `^D` key, so it seems it's stopping itself...

Here is an example (foobar.js is a test script that includes just the spawn code we use to run nx)

```bash
 (develop) ~/d/books cat foobar.js
#!/usr/bin/env node

import { spawn } from 'node:child_process';

const cmd  = spawn('npx', [ 'nx', 'serve', '@books/web' ]);

process.stdin.pipe(cmd.stdin);
cmd.stdout.pipe(process.stdout);
cmd.stderr.pipe(process.stderr);

 (develop) ~/d/books ./foobar.js

> nx run @books/web:serve

^D
> @books/web@0.0.0 serve
> vite
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
  VITE v5.0.12  ready in 324 ms
  ➜  Local:   http://localhost:8999/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help



 >  NX   Successfully ran target serve for project @books/web

 (develop) ~/d/books npx nx serve @books/web

> nx run @books/web:serve


> @books/web@0.0.0 serve
> vite

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

  VITE v5.0.12  ready in 262 ms

  ➜  Local:   http://localhost:8999/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
```

As you can see above, when nx is run from the script, there's a `^D` in the output, which does not appear when I run it directly from the shell.

### Expected Behavior

The serve command should work even when run from another script.

### Steps to Reproduce

to reproduce the problem you can use the following JS script:

```javascript
#!/usr/bin/env node

import { spawn } from 'node:child_process';

const cmd  = spawn('npx', [ 'nx', 'serve', APP_NAME ]);

process.stdin.pipe(cmd.stdin);
cmd.stdout.pipe(process.stdout);
cmd.stderr.pipe(process.stderr);
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : darwin-arm64
   npm    : 10.2.3

   nx             : 17.3.1
   @nx/js         : 17.3.1
   @nx/linter     : 17.3.1
   @nx/eslint     : 17.3.1
   @nx/workspace  : 17.3.1
   @nx/cypress    : 17.3.1
   @nx/devkit     : 17.3.1
   @nx/react      : 17.3.1
   @nx/storybook  : 17.3.1
   @nrwl/tao      : 17.3.1
   @nx/vite       : 17.3.1
   @nx/web        : 17.3.1
   typescript     : 5.3.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
This should be fixed by #21496, which is queued up for the next release. I'm going to close this out as the fix has already been merged.
