### ISSUE TITLE
Error: Failed to convert JavaScript value `Object {"base":"dist/apps/appname","browser":""}` into rust type `String`

### ISSUE THREAD

**Issue by maltehol** [nrwl/nx#21480]
### Current Behavior

After running the migration [convert-to-application-executor](https://nx.dev/nx-api/angular/generators/convert-to-application-executor) our project.json file was updated:
from
```
   "outputPath": "dist/apps/appname",
``` 
to: 
```
  "outputPath": {
       "base": "dist/apps/appname"
  },
```

But when triggering nx build, the NX deamon crashes:
> [NX Daemon Server] - 2024-02-01T09:56:05.340Z - Handled REQUEST_PROJECT_GRAPH. Handling time: 2789. Response time: 6.
node_modules\nx\src\hasher\native-task-hasher-impl.js:32
        const plans = this.planner.getPlansReference(tasks.map((t) => t.id), taskGraph);
                                   ^
>
>Error: Failed to convert JavaScript value `Object {"base":"dist/apps/appname","browser":""}` into rust type `String`
    at NativeTaskHasherImpl.hashTasks (node_modules\nx\src\hasher\native-task-hasher-impl.js:32:36)
    at InProcessTaskHasher.hashTasks (node_modules\nx\src\hasher\task-hasher.js:53:50)
    at handleHashTasks (node_modules\nx\src\daemon\server\handle-hash-tasks.js:20:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleResult (node_modules\nx\src\daemon\server\server.js:110:16)
    at async handleMessage (node_modules\nx\src\daemon\server\server.js:84:9)
    at async node_modules\nx\src\daemon\server\server.js:45:9 {
  code: 'StringExpected'
}

### Expected Behavior

The NX deamon should not crash.

### Steps to Reproduce

1. run `nx g @nx/angular:convert-to-application-executor`
2. try to build an app with `nx run appname:build`

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 20.11.0
   OS     : win32-x64
   npm    : 10.2.4

   nx                 : 17.3.1
   @nx/js             : 17.3.1
   @nx/jest           : 17.3.1
   @nx/linter         : 17.3.1
   @nx/eslint         : 17.3.1
   @nx/workspace      : 17.3.1
   @nx/angular        : 17.3.1
   @nx/cypress        : 17.3.1
   @nx/devkit         : 17.3.1
   @nx/eslint-plugin  : 17.3.1
   @nx/playwright     : 17.3.1
   @nrwl/tao          : 17.3.1
   @nx/web            : 17.3.1
   @nx/webpack        : 17.3.1
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   @ngneat/transloco           : 6.0.4
   @ngrx/component-store       : 17.1.0
   @ngrx/data                  : 17.1.0
   @ngrx/effects               : 17.1.0
   @ngrx/entity                : 17.1.0
   @ngrx/router-store          : 17.1.0
   @ngrx/schematics            : 17.1.0
   @ngrx/store                 : 17.1.0
   @ngrx/store-devtools        : 17.1.0
   @nx-aws-plugin/nx-aws-cache : 3.2.0
   @storybook/angular          : 7.6.9
```

### Failure Logs

```shell
[NX Daemon Server] - 2024-02-01T09:56:05.340Z - Handled REQUEST_PROJECT_GRAPH. Handling time: 2789. Response time: 6.
node_modules\nx\src\hasher\native-task-hasher-impl.js:32
        const plans = this.planner.getPlansReference(tasks.map((t) => t.id), taskGraph);
                                   ^

Error: Failed to convert JavaScript value `Object {"base":"dist/apps/appname","browser":""}` into rust type `String`
    at NativeTaskHasherImpl.hashTasks (node_modules\nx\src\hasher\native-task-hasher-impl.js:32:36)
    at InProcessTaskHasher.hashTasks (node_modules\nx\src\hasher\task-hasher.js:53:50)
    at handleHashTasks (node_modules\nx\src\daemon\server\handle-hash-tasks.js:20:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleResult (node_modules\nx\src\daemon\server\server.js:110:16)
    at async handleMessage (node_modules\nx\src\daemon\server\server.js:84:9)
    at async node_modules\nx\src\daemon\server\server.js:45:9 {
  code: 'StringExpected'
}
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
You likely are using the `options.outputPath` somewhere to define the outputs of that project, and that doesn't support an object reference. You'll need specify the output path in the outputs directly.

**Comment by maltehol** [comment]
Hi. Your documentations for @nx/angular:application says different:

> outputPath
Required
oneOf [object, string]
>
>Specify the output path relative to workspace root. *Note: the [object ](https://nx.dev/nx-api/angular/executors/application?ref=root/properties/outputPath/oneOf/0)notation is only supported in Angular versions >= 17.1.0.*

https://nx.dev/nx-api/angular/executors/application

Also, it was the generator that did these changes. I switched to browser-esbuild which indeed expect a string so it's now working for me.

**Comment by AgentEnder** [comment]
Hi, yes I was referring to the outputs array for your target referencing options output path. It's fine for the option to be an object, but things inside outputs shouldn't be

**Comment by robinpellegrims** [comment]
I have the same issue after using the convert-to-application-executor on nx 17.3.1 and angular 17.1, so I don't think this issue should be closed. It's an issue in the generator, no?

**Comment by jaysoo** [comment]
I've provided the fix here in case anyone runs into it. It's not something we can support in Nx.

https://github.com/nrwl/nx/discussions/26746#discussioncomment-9905468
