### ISSUE TITLE
GET http://localhost:4202/remoteEntry.mjs net::ERR_CONNECTION_REFUSED 

### ISSUE THREAD

**Issue by bensalemahmed** [nrwl/nx#21494]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.

### Additional context or description

Provide any additional details here as needed.

**Comment by AgentEnder** [comment]
Closing this out as well, reasoning in the other issue.
