### ISSUE TITLE
Expo CLI is not responding

### ISSUE THREAD

**Issue by remi2257** [nrwl/nx#21501]
### Current Behavior

I created a new Nx workspace an Expo app, and I realised the CLI is not responding anymore.
It complicates things when you want to use your keyboard to launch the app, reload it, ...

I have to basically spam a key (or hold it) to have a response from my terminal

### Expected Behavior

A responding CLI. 

### Steps to Reproduce

1. Create a Nx workspace with the expo preset `npx create-nx-workspace --preset=expo`
2. Start the CLI with the "serve" command
3. Use your keyboard in the terminal (for example, use "a" to open the app)

### Nx Report

```shell
Node   : 20.10.0
   OS     : linux-x64
   yarn   : 4.1.0
   
   nx                 : 17.3.1
   @nx/js             : 17.3.1
   @nx/jest           : 17.3.1
   @nx/linter         : 17.3.1
   @nx/eslint         : 17.3.1
   @nx/workspace      : 17.3.1
   @nx/detox          : 17.3.1
   @nx/devkit         : 17.3.1
   @nx/eslint-plugin  : 17.3.1
   @nx/expo           : 17.3.1
   @nx/next           : 17.3.1
   @nx/react          : 17.3.1
   @nrwl/tao          : 17.3.1
   @nx/web            : 17.3.1
   @nx/webpack        : 17.3.1
   typescript         : 5.3.3
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

- It is working has expected on my repo with Nx 16.6.0
- **the "start" executor from expo has 2 dependencies in the field "dependsOn". If you delete them, it works as expected**
- the CLI doesn't work in VsCode neither in a "standard" terminal

**Comment by xiongemi** [comment]
@remi2557 it should be fixed in the next version.
you can just run `nx start` for now.

**Comment by xiongemi** [comment]
it should be fixed in nx 18

**Comment by frantisekhanzlikbl** [comment]
> it should be fixed in nx 18. closing this issue for now

Hi, may I ask in what version? I'm currently on 18.0.4 and it's unfortunately no better. :-/

It might be worth noting that I'm not using expo, but a custom inquirer prompts, but the behaviour is exactly as described by the OP. Anything that requires input is non-responsive unless I hold (or spam) the key. I'd love to at least work around this somehow, but it appears that there's no `nx start` command now.
