### ISSUE TITLE
Set Up Application Proxies Fail - NX   Cannot find module 'nx/src/plugins/package-json-workspaces'

### ISSUE THREAD

**Issue by Leo-Wangyc** [nrwl/nx#21516]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

[Enter the URL or documentation section here.](https://nx.dev/recipes/node/application-proxies#set-up-application-proxies)

### Additional context or description

I started a new react + next project and chose the nest.js as the backend service. Then I try to connect them through setting up application proxies. Here are the commands in the docs:
```bash
nx g @nx/node:app <node-app> --frontendProject my-react-app
nx g @nx/nest:app <nest-app> --frontendProject my-react-app
nx g @nx/express:app <express-app> --frontendProject my-react-app
```
I ran 'nx g @nx/nest:app <nest-app> --frontendProject my-react-app' this command. But it throw an error 

>  NX   Cannot find module 'nx/src/plugins/package-json-workspaces'

I'm not sure which step I did is wrong. Thanks.
Node version is v21.1.0. 

![image](https://github.com/nrwl/nx/assets/46594055/9f65f60e-6a9a-461c-9263-82b0e0019d65)

**Comment by Leo-Wangyc** [comment]
By the way, Node version is v21.1.0. Thanks!

**Comment by greeedy-b** [comment]
I have this error too.
In start, react-native metro server

**Comment by aholthagerty** [comment]
Well this is frustrating.  I am getting this same error and have no clue what to do about it.

using `npx nx g @nx/node:application <app name> --dry-run`

**Comment by aholthagerty** [comment]
Was able to fix it locally for me by editing `node_modules/@nx/jest/src/plugins/plugin.js` line 12 to be: 

`const package_json_workspaces_1 = require("nx/plugins/package-json-workspaces");`



definitely a hacky solution, though.

**Comment by airowe** [comment]
Still happening

**Comment by aholthagerty** [comment]
going to comment here to keep this issue from auto-closing.
