### ISSUE TITLE
Cannot stop (Ctrl + C) nx serve command after upgrade from 17.2.8 -> 17.3.1

### ISSUE THREAD

**Issue by SnakeSVx** [nrwl/nx#21523]
### Current Behavior

CTRL + C does not do anything, seems to be ignored

### Expected Behavior

CTRL + C stopping the running process

### Steps to Reproduce

1. run nx serve app-name

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.19.0
   OS     : linux-x64
   npm    : 10.2.5
   
   nx (global)        : 17.3.1
   nx                 : 17.3.1
   @nx/js             : 17.3.1
   @nx/jest           : 17.3.1
   @nx/linter         : 17.3.1
   @nx/eslint         : 17.3.1
   @nx/workspace      : 17.3.1
   @nx/angular        : 17.3.1
   @nx/cypress        : 17.3.1
   @nx/devkit         : 17.3.1
   @nx/eslint-plugin  : 17.3.1
   @nx/node           : 17.3.1
   @nx/storybook      : 17.3.1
   @nrwl/tao          : 17.3.1
   @nx/vite           : 17.3.1
   @nx/web            : 17.3.1
   @nx/webpack        : 17.3.1
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc               : 1.1.23
   @fortawesome/angular-fontawesome : 0.14.1
   @ngneat/spectator                : 16.0.0
   @storybook/angular               : 7.6.12
   @twittwer/compodoc               : 1.12.0
   ng-mocks                         : 14.12.1
   ngx-extended-pdf-viewer          : 18.1.14
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Build, serve, test, linting config in project.json

Other command's do not seem to be affected.

```
"targets": {
    "build": {
      "executor": "@nx/angular:webpack-browser",
      "outputs": ["{options.outputPath}"],
      "options": {
        "buildLibsFromSource": false,
        "outputPath": "dist/apps/docs",
        "index": "apps/docs/src/index.html",
        "main": "apps/docs/src/main.ts",
        "polyfills": "apps/docs/src/polyfills.ts",
        "tsConfig": "apps/docs/tsconfig.app.json",
        "inlineStyleLanguage": "scss",
        "assets": [
          "apps/docs/src/favicon.ico",
          "apps/docs/src/assets",
          ...
        ],
        "styles": ["apps/docs/src/styles.scss"],
        "scripts": []
      },
      "configurations": {
        "production": {
          "budgets": [
            {
              "type": "initial",
              "maximumWarning": "500kb",
              "maximumError": "2mb"
            },
            {
              "type": "anyComponentStyle",
              "maximumWarning": "2kb",
              "maximumError": "4kb"
            }
          ],
          "fileReplacements": [
            {
              "replace": "apps/docs/src/environments/environment.ts",
              "with": "apps/docs/src/environments/environment.prod.ts"
            }
          ],
          "outputHashing": "all"
        },
        "development": {
          "buildOptimizer": false,
          "optimization": false,
          "vendorChunk": true,
          "extractLicenses": false,
          "sourceMap": true,
          "namedChunks": true
        }
      },
      "defaultConfiguration": "production"
    },
    "serve": {
      "executor": "@nx/angular:dev-server",
      "options": {
        "buildLibsFromSource": false
      },
      "configurations": {
        "production": {
          "buildTarget": "docs:build:production"
        },
        "development": {
          "buildTarget": "docs:build:development"
        }
      },
      "defaultConfiguration": "development"
    },
    "extract-i18n": {
      "executor": "@angular-devkit/build-angular:extract-i18n",
      "options": {
        "buildTarget": "docs:build"
      }
    },
    "lint": {
      "executor": "@nx/eslint:lint"
    },
    "test": {
      "executor": "@nx/jest:jest",
      "outputs": ["{workspaceRoot}/coverage/apps/docs"],
      "options": {
        "jestConfig": "apps/docs/jest.config.ts"
      }
    },
```

**Comment by AgentEnder** [comment]
I attempted to reproduce this issue in both a fresh react and angular workspace, and in either case the serve command was killed on ctrl + c

Can you provide some more thorough reproduction steps or a repository which illustrates the behavior?

**Comment by SnakeSVx** [comment]
Will take a look if I can make a small reproduction project. For now we reverted back to 17.2.8 after testing if 18.x fixed the issue or not.

**Comment by SnakeSVx** [comment]
Closing this issue. Problem is caused by an external library, apparently affecting nx.

**Comment by ryandegruyter** [comment]
@SnakeSVx We got the same issue when upgrading from 17.2.8 to 18.0.1.
Which external dependency was causing the problem in your case if I may ask?

**Comment by AgentEnder** [comment]
We are going to reopen this as we've had a few reports of similar issues and haven't been able to pin down how and why this would be happening.

**Comment by ryandegruyter** [comment]
Thank you, in our case we don't have that dependency and it seems to occur with any nx command that keeps a process running.

**Comment by SnakeSVx** [comment]
I tried some more things out and it seems the dependency itself is not the issue, but "using" as a runner seems to be.

This config means it all seems to work: 


```
"tasksRunnerOptions": {
    "minio": {
      "runner": "nx-remotecache-minio",
      "options": {
        "other-config-options": ""
        "cacheableOperations": ["build", "lint", "test", "e2e", "build-storybook", "compodoc"]
      }
    },
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build", "lint", "test", "e2e", "build-storybook", "compodoc"]
      }
    }
  },
```

With this it seems to hang on serve: 

```
"tasksRunnerOptions": {
    "default": {
      "runner": "nx-remotecache-minio",
      "options": {
        "other-config-options": ""
        "cacheableOperations": ["build", "lint", "test", "e2e", "build-storybook", "compodoc"]
      }
    },
    "local": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build", "lint", "test", "e2e", "build-storybook", "compodoc"]
      }
    }
  },
```

**Comment by woodrunner** [comment]
> I tried some more things out and it seems the dependency itself is not the issue, but "using" as a runner seems to be.
> 
> With the default config it all seems to work:
> 
> ```
> "tasksRunnerOptions": {
>     "default": {
>       "runner": "nx/tasks-runners/default",
>       "options": {
>         "cacheableOperations": ["build", "lint", "test", "e2e", "build-storybook", "compodoc"]
>       }
>     }
>   },
> ```
> 
> With the custom runner config it seems to hang on serve:
> 
> ```
> "tasksRunnerOptions": {
>     "default": {
>       "runner": "nx-remotecache-minio",
>       "options": {
>         "other-config-options": ""
>         "cacheableOperations": ["build", "lint", "test", "e2e", "build-storybook", "compodoc"]
>       }
>     }
>   },
> ```

Nice finding.. I don't think it is specific related to the nx-remotecache-minio plugin, since we have a another runner (@pellegrims/nx-remotecache-s3) and we have the same issue.  With the default runner we're able to kill the serve.

**Comment by NiklasPor** [comment]
> > I tried some more things out and it seems the dependency itself is not the issue, but "using" as a runner seems to be.
> > 
> > With the default config it all seems to work:
> > 
> > ```
> > "tasksRunnerOptions": {
> >     "default": {
> >       "runner": "nx/tasks-runners/default",
> >       "options": {
> >         "cacheableOperations": ["build", "lint", "test", "e2e", "build-storybook", "compodoc"]
> >       }
> >     }
> >   },
> > ```
> > 
> > With the custom runner config it seems to hang on serve:
> > 
> > ```
> > "tasksRunnerOptions": {
> >     "default": {
> >       "runner": "nx-remotecache-minio",
> >       "options": {
> >         "other-config-options": ""
> >         "cacheableOperations": ["build", "lint", "test", "e2e", "build-storybook", "compodoc"]
> >       }
> >     }
> >   },
> > ```
> 
> Nice finding.. I don't think it is specific related to the nx-remotecache-minio plugin, since we have a another runner (@pellegrims/nx-remotecache-s3) and we have the same issue.  With the default runner we're able to kill the serve.


Hey that runner is also based on `nx-remotecache-custom` so it might only occur with runners based on the packages. I'll bump dependencies and debug tomorrow, it obviously worked in past nx versions.
