### ISSUE TITLE
Existing prettierignore cause failure when migrating from angular cli to nx workspace

### ISSUE THREAD

**Issue by LukeHowellDev** [nrwl/nx#2155]
## Expected Behavior

When running `ng add @nrwl/workspace` with an existing `.prettierignore`, the file should be modified and migration not fail.

## Current Behavior

If `.prettierignore` exists in the project before `ng add @nrwl/workspace`, the migration will fail with the following error

```
ERROR! .prettierignore already exists.
The Schematic workflow failed. See above.
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `ng new my-app`
1. `cd my-app`
1. `touch .prettierignore`
1. `ng add @nrwl/workspace`
1. Observe output
```
Installing packages for tooling via npm.
Installed packages for tooling via npm.
    Renamed karma.conf.js -> apps/my-app/karma.conf.js
    Renamed tsconfig.app.json -> apps/my-app/tsconfig.app.json
    Renamed tsconfig.spec.json -> apps/my-app/tsconfig.spec.json
    Renamed src -> apps/my-app/src
    Renamed e2e -> apps/my-app-e2e
ERROR! .prettierignore already exists.
The Schematic workflow failed. See above.
```

### Context

Please provide any relevant information about your setup:

- Angular CLI version: 8.3.20
- Angular version: 8.2.14

_I was also able to reproduce this with older versions_

**Comment by FrozenPandaz** [comment]
Would somebody from the community like to take a look into this issue?

**Comment by PetrosA** [comment]
Same issue here!

**Comment by mehrad-rafigh** [comment]
@LukeHowellDev @FrozenPandaz @PetrosA I opened a PR fixing the issue. The only problem is, that I cannot get the test to pass

**Comment by jdpearce** [comment]
I think there's been a miscommunication somewhere here. There is already a PR that fixed this. There is no issue with the `.prettierrc` file (that we know of).

Thanks for the PR @mehrad-rafigh but I think it's addressing a problem that no longer exists. I'm going to close that and this issue due to it being already fixed by https://github.com/nrwl/nx/pull/3329
