### ISSUE TITLE
docs: automate updating dependencies page is missing 

### ISSUE THREAD

**Issue by vltansky** [nrwl/nx#21583]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[https://nx.dev/core-features/automate-updating-dependencies](https://nx.dev/core-features/automate-updating-dependencies)

### Additional context or description

missing page. It's the first result in google by searching "nx update". 

Provide any additional details here as needed.

**Comment by SnakeSVx** [comment]
The url seems to have changed to https://nx.dev/features/automate-updating-dependencies

**Comment by isaacplmann** [comment]
This one is resolved.
