### ISSUE TITLE
options not inherited for inferred test targets (@nx/jest/plugin) in nx 18

### ISSUE THREAD

**Issue by atsjo** [nrwl/nx#21587]
### Current Behavior

Adding "passWithNoTests": true to options in @nx/jest/plugin declaration has no effect, neither has the the options in targetDefaults for @nx/jest:jest

### Expected Behavior

options are inherited for the inferred test targets

### Steps to Reproduce

1. add below to plugins array in nx.json
```
    {
      "plugin": "@nx/jest/plugin",
      "options": {
        "targetName": "newtest",
        "passWithNoTests": true,
        "options": {
          "passWithNoTests": true
        }
      }
    }
```
2. run target for project with no tests

### Nx Report

```shell
Node   : 20.11.0
   OS     : win32-x64
   pnpm   : 8.15.1
   
   nx                 : 18.0.0
   @nx/js             : 18.0.0
   @nx/jest           : 18.0.0
   @nx/linter         : 18.0.0
   @nx/eslint         : 18.0.0
   @nx/workspace      : 18.0.0
   @nx/angular        : 18.0.0
   @nx/cypress        : 18.0.0
   @nx/devkit         : 18.0.0
   @nx/esbuild        : 18.0.0
   @nx/eslint-plugin  : 18.0.0
   @nrwl/tao          : 18.0.0
   @nx/web            : 18.0.0
   @nx/webpack        : 18.0.0
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   angular-calendar : 0.31.0
```

### Failure Logs

```shell
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In C:\Users\atles\source\repos\teve-no\task4s\libs\shared-all
  4 files checked.
  testMatch: **/?(*.)+(spec|test).[jt]s?(x) - 0 matches
  testPathIgnorePatterns: \\node_modules\\ - 4 matches
  testRegex:  - 0 matches
Pattern:  - 0 matches
Warning: run-commands command "jest" exited with non-zero status code
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Hi there!

Thanks for raising this issue. 

The correct place to supply the CLI option is currently in `targetDefaults`. However, because we do not use the `@nx/jest:jest` executor with the `@nx/jest/plugin` (instead directly calling `jest` CLI), you need to set it up a little bit differently.

```json
"targetDefaults": {
  "newtest": {
     "args": ["--passWithNoTests"]
  }
}
```

Where `newtest` is the name given to the `test` target:
```json
   {
      "plugin": "@nx/jest/plugin",
      "options": {
        "targetName": "newtest",
  }
```

**Comment by atsjo** [comment]
Thanx, this worked! just had to wrap args in options:

```
    "test": {
      "options": {
        "args": ["--passWithNoTests"]
      }
    }
```

**Comment by atsjo** [comment]
I have now removed all lint and test targets from my project.json files, nice:-)

closing, since this is just a docs issue...
