### ISSUE TITLE
@nx/dependency-checks should not fail on local libraries

### ISSUE THREAD

**Issue by k3nsei** [nrwl/nx#21595]
### Current Behavior

In my project `Library A` is depending on local `Library B`. I have `peerDependencies` like shown below and getting linting errors. Btw. I don't want to use version number for security reasons as our project scope isn't published to npm, that why we are using local path (which is valid package.json).

```json
{
  "peerDependencies": {
    "@angular/common": "^17.1.2",
    "@angular/core": "^17.1.2",
    "@my-app/lib-b": "../../dist/libs/lib-b"
  }
}
```

I'm getting eslint error like that

`9:3  error  The version specifier does not contain the installed version of "@my-app/lib-b" package: 0.0.1      @nx/dependency-checks`

### Expected Behavior

When using local library as `peerDependencies` it's version should be ignored when there is local path is specified or give possibility to configure to ignore version mismatch for given libraries (currently it could be set to ignore all).

### Steps to Reproduce

1. Create project with 2 libraries
2. One library should be depending on the other
3. Add second library to dependentcies list into first library `package.json` using local path to dist.
4. Run `nx run-many --target lint --all`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.11.0
   OS     : win32-x64
   npm    : 10.4.0

   nx                 : 18.0.1
   @nx/js             : 18.0.1
   @nx/jest           : 18.0.1
   @nx/linter         : 18.0.1
   @nx/eslint         : 18.0.1
   @nx/workspace      : 18.0.1
   @nx/angular        : 18.0.1
   @nx/cypress        : 18.0.1
   @nx/devkit         : 18.0.1
   @nx/eslint-plugin  : 18.0.1
   @nx/storybook      : 18.0.1
   @nrwl/tao          : 18.0.1
   @nx/web            : 18.0.1
   @nx/webpack        : 18.0.1
   typescript         : 5.3.3
```

### Package Manager Version

npm@10.4.0

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
I believe this is because we are expecting file refs to have the `file:` protocol at the beginning (e.g. `file:../my-lib`)

**Comment by MarkJungeblut** [comment]
We also need support on this topic. 
At the moment it's not possible for us to release our packages because internal buildable libs are automatically added to the package.json with "*" as version. 

We have many peer dependencies to handle which are automatically updated by renovate so that we cannot add them manually everytime to our package.json. 

We are not talking about one lib, we provide 10+ libs.

It would be good to get a possible fix soon. 
`"updateBuildableProjectDepsInPackageJson": true` was working perfectly for us.

**Comment by k3nsei** [comment]
Yes adding prefix `file:` helped
