### ISSUE TITLE
Add component testing to @nx/playwright plugin 

### ISSUE THREAD

**Issue by bsunderhus** [nrwl/nx#21594]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Playwright provides a [component testing library](https://playwright.dev/docs/test-components) (although still experimental), would be nice to have a playwright plugin similar to [@nx/cypres](https://nx.dev/nx-api/react/generators/component-cypress-spec)

## Motivation

As there's an equivalent for cypress which is already supported by nx [@nx/cypres](https://nx.dev/nx-api/react/generators/component-cypress-spec), I imagine it would be desirable to have it also for playwright

## Suggested Implementation

Exactly as the one for cypress, but for playwright.

**Comment by Hotell** [comment]
After more detailed look on nx playwright code it looks like component testing with standard is almost 1:1 besides few details:
- import api used for pw config needs to be imported from different package https://github.com/microsoft/fluentui-contrib/pull/102/files#diff-2c33cdc0d64beece4ba687216e89ff575cb2b4c724c94560078497850ecedc44L1
- small tweaks are present config itself
- CLI invoked is different  https://github.com/microsoft/fluentui-contrib/pull/102/files#diff-ae669bfdda3f4230495b09429957d3d30544949a8c13b6c272a7394f84d3bd92R117

https://github.com/microsoft/fluentui-contrib/pull/102
