### ISSUE TITLE
Get different results when run nx/jest from different folder

### ISSUE THREAD

**Issue by yzhe554** [nrwl/nx#21591]
### Current Behavior

`nx test <target>` from root fails but when it's run from the library(target), it passes.
The project is migrated from lage following https://nx.dev/recipes/adopting-nx/adding-to-monorepo
NX 17 and 18 are both tested, same issue can be found.
Tried with lage/yarn workspace command to run test from root, no issues.

### Expected Behavior

`nx test <target>` should give the same results from any folder in the repo.

### Steps to Reproduce

1.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.15.0
   OS     : linux-x64
   yarn   : 1.22.21
   
   nx            : 17.3.2
   lerna         : 6.1.0
   @nrwl/devkit  : 15.3.3
   @nrwl/tao     : 17.3.2
   typescript    : 5.0.4
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/devkit@15.3.3
   
   To fix this, run `nx migrate nx@17.3.2`
```

### Operating System

- [ ] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Hi there @yzhe554 ! Thank you so much for filing this issue! It would be super helpful if you could provide a simple reproduction repository!

**Comment by yzhe554** [comment]
Hi @mandarini , it's tricky to provide a reproduction repo, because it's found from company's project and this only happens to one lib of 45 libs.

**Comment by mandarini** [comment]
Ah I see @yzhe554 ! Then this makes me think that maybe it's not an issue with Nx in itself, since it works for 44 libs and only fails in one. What does the lib that causes the issue look like? What stack is it using? Does it have any special configuration? What does the jest config look like?

**Comment by yzhe554** [comment]
Hey @mandarini , I would still consider this is a NX side issue or a NX specific config.
1. jest.config are exactly the same
2. `nx run <target>` passes if I run from any lib, it doesn't have to be inside the failed one. It only fails if I run it from root.
3. `yarn lage run test --scope <target>` or `yarn workspace <target> jest` works.

> What stack is it using?
It's nodejs, azure-functions, msw, jest.

> Does it have any special configuration? What does the jest config look like?
This is the jest.config.js in side the lib, and I didn't have a jest.config.js from root(I tried if I duplicate one from root, same tests fail).
```
module.exports = {
  testEnvironment: 'node',
  resetMocks: true,
  workerIdleMemoryLimit: '400M',
  testPathIgnorePatterns: ['dist', '__generated__'],
  modulePathIgnorePatterns: ['dist'],
  setupFilesAfterEnv: ['./setupTests.ts'],
  coverageReporters: ['lcov'],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx,js,jsx}',
    '!**/__fixtures__/**',
    '!**/__generated__/**',
    '!**/__testHelpers__/**',
    '!src/index.ts',
    '!**/graphql/**',
  ],
  transform: {
    '^.+\\.(t|j)sx?$': '@swc/jest',
  },
};
```
