### ISSUE TITLE
Add format json as an output option to nx show projects

### ISSUE THREAD

**Issue by andersbea** [nrwl/nx#21602]
- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Allow the option to print out the result from 
```
npx nx show projects --affected --type app
``` 
or more generally
```
npx nx show projects
```
as a json list.

## Motivation

When setting up flows for a CICD pipeline in Github Actions, I separate the publishing of apps that have been affected into their own jobs using matrix strategies. Currently I have to handle this outside of the command, which adds unnecessary complexity in my action. 

## Suggested Implementation

Add the command flag `--output` or `-o` (shorthand) with the parameters `json` or `yaml` as options. Without the flags the code can default to the current method, which prints the project per line. 

My current implementation simply takes the output and puts it into a json array. In the following example I also output into a GITHUB_OUTPUT to be used in the matrix:
```
apps=$(npx nx show projects --base=origin/main --affected --type app)
json_array="[]"
for app in $apps; do
  json_array=$(echo $json_array | jq --arg app "$app" '. + [$app]')
done
echo "apps=$json_array" >> "$GITHUB_OUTPUT"
```

## Alternate Implementations

The flag could also be simpler such as `--json`. 
However the method i suggested above is based upon the kubernetes method for outputting details when using the CLI, such as 
```
kubectl get pods -o yaml
```

**Comment by AgentEnder** [comment]
`--json` is already a valid flag for show projects
