### ISSUE TITLE
Double-compilation of SCSS files  when using nx cache

### ISSUE THREAD

**Issue by asgerjensen** [nrwl/nx#21613]
### Current Behavior

I sometimes see build failures like this
```
Warning: ▲ [WARNING] Comments in CSS use "/* ... */" instead of "//" [js-comment-in-css]

    /home/runner/work/xxx/xxx/apps/xxx/src/app/account/account-shared/account-link-tile/account-link-tile/account-link-tile.component.scss:2:18:
      2 │ /******/ (() => { // webpackBootstrap
        ╵                   ~~

Warning: ▲ [WARNING] Comments in CSS use "/* ... */" instead of "//" [js-comment-in-css]

    /home/runner/work/xxx/xxx/libs/components/src/lib/material/product-tile/product-tile/product-tile.component.scss:15:10:
      15 │ /******/  // startup
         ╵           ~~
```
Most often when no changes have been made in that lib, or any of its dependencies, and mostly when building for app-shell.

The reason i figure it might be related to nx-cache, is because, the way to fix it, is to randomly touch some scss file, in that lib, and push it, forcing a recompile of the lib.

### Expected Behavior

Build to not be flacky.

### Steps to Reproduce

1. unclear. I cant repo it trivially. 
2. mostly interested in whether it /could/ be nx-cache related or if i'm barking up the wrong tree

### Nx Report

```shell
Node   : 18.17.0
   OS     : darwin-x64
   npm    : 9.6.7
   
   nx                 : 17.1.3
   @nx/js             : 17.1.3
   @nx/jest           : 17.1.3
   @nx/linter         : 17.1.3
   @nx/eslint         : 17.1.3
   @nrwl/linter       : 16.7.4
   @nx/workspace      : 17.1.3
   @nx/angular        : 17.1.3
   @nx/cypress        : 17.1.3
   @nx/devkit         : 17.1.3
   @nx/eslint-plugin  : 17.1.3
   @nrwl/tao          : 17.1.3
   @nx/web            : 17.1.3
   @nx/webpack        : 17.1.3
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @perpendicular/plugins-nx : 17.0.5
   ng-mocks                  : 14.12.1
   ---------------------------------------
```

### Failure Logs

```shell
Warning: ▲ [WARNING] Comments in CSS use "/* ... */" instead of "//" [js-comment-in-css]

    /home/runner/work/xxx-frontend/xxx-frontend/apps/xxx/src/app/account/account-shared/account-link-tile/account-link-tile/account-link-tile.component.scss:2:18:
      2 │ /******/ (() => { // webpackBootstrap
        ╵                   ~~



Warning: ▲ [WARNING] Comments in CSS use "/* ... */" instead of "//" [js-comment-in-css]

    /home/runner/work/xxx-frontend/xxx-frontend/apps/xxx/src/app/account/account-shared/account-link-tile/account-link-tile/account-link-tile.component.scss:15:10:
      15 │ /******/  // startup
         ╵           ~~



Warning: ▲ [WARNING] Comments in CSS use "/* ... */" instead of "//" [js-comment-in-css]

    /home/runner/work/xxx-frontend/xxx-frontend/apps/xxx/src/app/account/account-shared/account-link-tile/account-link-tile/account-link-tile.component.scss:16:10:
      16 │ /******/  // Load entry module and return exports
         ╵           ~~



Warning: ▲ [WARNING] Comments in CSS use "/* ... */" instead of "//" [js-comment-in-css]

    /home/runner/work/xxx-frontend/xxx-frontend/apps/xxx/src/app/account/account-shared/account-link-tile/account-link-tile/account-link-tile.component.scss:17:10:
      17 │ /******/  // This entry module doesn't tell about it's top-level d...
         ╵           ~~

```
```


### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by ahernd2** [comment]
I think there is something wrong with caching since version 17+. I've noticed over the past two weeks when we change code in libraries that are in our project, the cache is not invalidated for that library, so when our gitlab deployment comes along and builds the app, our projects seem to end up with an older version of the changed library. 

Currently our workaround is to manually delete the cache, which is not ideal.

This is also a very hard one to recreate

**Comment by andreas-becker** [comment]
I did add "overrides" for ajv and ajv-keywords in my package.json and then the same error occured.

**Comment by hoeni** [comment]
Maybe this helps to isolate the issue:
I'm *not* using Nx, just plain Angular (and came here via Google search). However, we see Angular builds failing in our GitLab CI with exactly that error randomly on about every 30-40th build since about 1–2 years and surely long before NG17.
Since it tends to be more often when the build server is stressed, I suppose a race condition in the build process itself.

**Comment by jaysoo** [comment]
It looks like it isn't a problem in Nx itself but perhaps in Angular v17. You can also pass `--skip-nx-cache` to force the build again.

If there is a problem with Nx, please open a new issue with a repro so we can debug it properly. Thanks!
