### ISSUE TITLE
Federated modules don't work going from nx 17 to nx 18

### ISSUE THREAD

**Issue by Aubrey-Russell** [nrwl/nx#21632]
### Current Behavior

Upgrading to NX 18 from 17 breaks all federated module stuff 

![image](https://github.com/nrwl/nx/assets/157523547/3b57f1ae-a063-4ded-8f0a-ba989a64952e)

### Expected Behavior

Remote federated modules should work as expected when migrating from nx 17 to nx 18

### Steps to Reproduce

1. Create an NX remote federated module project in nx 17
2. Create a react shell host application
3. Create a react remote federated module
4. Reference a dynamic federated module using the module exports in module-federation.config.js
5. Launch the shell
6. Observe Shell finding remote Entry and launching on a server and port
7. run mx migrate --latest
8. pnpm install
9. nx serve shell
10. Observe errors saying cannot find remoteEntry

Instead of the shell, running on localhost:4200, referencing federated module remote entry on, say, localhost:9007 like on nx 17 as is configured in remote app project.json, now bizarrely its looking on localhost:4201/remoteEntry.js

NX never launches anything on localhost:4201; there's nothing there and I never configured it to run anything on localhost:4201 so it makes sense why remote entry cannot be found

### Nx Report

```shell
Node   : 21.1.0
   OS     : win32-x64
   pnpm   : 8.14.2

   nx                 : 18.0.1
   @nx/js             : 18.0.1
   @nx/jest           : 18.0.1
   @nx/linter         : 18.0.1
   @nx/eslint         : 18.0.1
   @nx/workspace      : 18.0.1
   @nx/cypress        : 18.0.1
   @nx/devkit         : 18.0.1
   @nx/eslint-plugin  : 18.0.1
   @nx/react          : 18.0.1
   @nrwl/tao          : 18.0.1
   @nx/web            : 18.0.1
   @nx/webpack        : 18.0.1
   typescript         : 5.3.3
```

### Failure Logs

```shell
Failed to load resource: net::ERR_CONNECTION_REFUSED
remoteEntry.js:1 
        
        
        Failed to load resource: net::ERR_CONNECTION_REFUSED
remoteEntry.js:1 
        
        
        Failed to load resource: net::ERR_CONNECTION_REFUSED
remoteEntry.js:1
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by ptakpatryk** [comment]
I couldn't reproduce it on the `macOS`. Everything works fine after migrating.
What I can suggest tho is running `nx reset` before and after migration. I found caching sometimes a pain when changing configurations etc.

Additionally, you could take a look at the shell's `webpack.config.prod.ts` and see what the path is configured to each of the remotes as this is what controls where the host will be looking for the remotes.
![image](https://github.com/nrwl/nx/assets/42934159/da3ff86b-369e-4313-96df-b0b2f2551cc8)

Sorry if I teach you how to suck eggs here, but trying to be helpful 😄

**Comment by Aubrey-Russell** [comment]
@ptakpatryk Thanks very much for your response here this is helpful, I will try nx reset as well and see if that fixes it, if not I will attempt to replicate and strip down the project as an example. The remotes thing you mentioned here is interesting too. In nx 17 I didn't have to specify these remotes in a development configuration in the webpack config on localhost. Of course for production and stuff I have to refer to where the federated module is hosted, but using the module-federation.config.js was sufficient previously:

module.exports = {
    name: 'shell',
    remotes: ['app1', 'app2', 'app3'],
};

In nx 17 what would happen is it seemed like nx would look at my app project.json, start the project on the port specified, then dynamically reference localhost:port and point to that as long as i had it specified in the module-federation.config. Did the logic change under the hood here to where it operates differently when ingesting remotes and now it requires you to specify the localhost remote as well?

**Comment by Aubrey-Russell** [comment]
@ptakpatryk It looks like now I must specify --devRemotes when starting shell. Previously it seemed like NX would automatically determine which --devRemotes to use

**Comment by isunilmekala** [comment]
Even after specifying `--devRemotes` its failing to load those remote hosts as in development mode.

**Comment by rbirkgit** [comment]
Can this be related to this issue? https://github.com/nrwl/nx/issues/20974

We cannot update to Nx 7.3+ since now we are forced to have all static remoted starting up on the same port. But that doesn't work as they use different ports in devRemote mode. Is there a solution to this? or we will not be able to update top any newer Nx?

**Comment by leosvelperez** [comment]
The original issue reported in this thread should have been addressed by https://github.com/nrwl/nx/pull/21709, which was released in Nx 18.0.4. There was an issue with the remapping done to the remote URL when the project had a single remote (when serving static remotes).

> It looks like now I must specify --devRemotes when starting shell. Previously it seemed like NX would automatically determine which --devRemotes to use

You need to specify which remotes you want to serve in development mode. Those specified with the `--devRemotes` flag will be watched, rebuilt, and live-reloaded on changes. The rest of the remotes will be built once and served with a static server for a faster startup.

> Can this be related to this issue? #20974

That's a different issue, and you can continue the conversation over that thread.

@Aubrey-Russell could you please try again with the latest version and see if the issue is solved for you?

**Comment by Aubrey-Russell** [comment]
@leosvelperez thanks for your message, I will try the latest version today and see if that works

**Comment by Aubrey-Russell** [comment]
@leosvelperez Weirdly enough it completely fails to launch now. Running with verbose doesn't give me any more information

\node_modules\.pnpm\@nx+react@18.0.4_@swc-node+register@1.8.0_@swc+core@1.4.1_@types+node@20.11.17_nx@18.0.4_typescript@5.3.3\node_modules\@nx\react\src\executors\module-federation-dev-server\module-federation-dev-server.impl.js:111
                throw new Error(`Remote failed to start. See above for errors.`);
                ^

Error: Remote failed to start. See above for errors.
    at ChildProcess.<anonymous> (node_modules\.pnpm\@nx+react@18.0.4_@swc-node+register@1.8.0_@swc+core@1.4.1_@types+node@20.11.17_nx@18.0.4_typescript@5.3.3\node_modules\@nx\react\src\executors\module-federation-dev-server\module-federation-dev-server.impl.js:111:23)
    at ChildProcess.emit (node:events:515:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

Node.js v21.1.0

Report 

   Node   : 21.1.0
   OS     : win32-x64
   pnpm   : 8.15.2

   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/jest           : 18.0.4
   @nx/linter         : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/workspace      : 18.0.4
   @nx/cypress        : 18.0.4
   @nx/devkit         : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nx/react          : 18.0.4
   @nrwl/tao          : 18.0.4
   @nx/web            : 18.0.4
   @nx/webpack        : 18.0.4
   typescript         : 5.3.3

**Comment by Aubrey-Russell** [comment]
Ill see if I can create a separate repo that replicates this issue that I can share

**Comment by Aubrey-Russell** [comment]
if I specify devRemotes then there's no error or problem at all which is odd. Remote start has no issues.

**Comment by leosvelperez** [comment]
That's definitely not expected. Something else might be going on. Please provide a reproduction so we can troubleshoot it.

**Comment by isunilmekala** [comment]
Don't know how much this is correct but with below change I am able to run the remote app in development mode

![image](https://github.com/nrwl/nx/assets/83385574/77649b47-3ad5-46fb-9dea-26c503c93738)
