### ISSUE TITLE
@nx/esbuild:esbuild does not include assets in watch or build

### ISSUE THREAD

**Issue by paustint** [nrwl/nx#21654]
### Current Behavior

Started a brand new node project from scratch with express. When I build the application, the assets directory is not copied into the dist folder. And when serving the application, all the assets return 404 since the assets directory is ignored.

:star: **EDIT** 

I think the string version of the configuration may be broken, I looked at the docs for the "[configuration playground](https://nx.dev/nx-api/esbuild/executors/esbuild#options-playground)" and trie the object format and the assets were handled correctly.

```diff
"assets": [
-"apps/nx-test/src/assets", // THIS DOES NOT WORK WITH ESBUILD
+  { // THIS DOES WORK
+    "glob": "**/*",
+    "input": "apps/nx-test/src/assets",
+    "output": "apps/nx-test/src/assets",
+    "ignore": [".gitkeep"]
+  }
],
```

### Expected Behavior

assets are copied over just like they are in all other scenarios.

### GitHub Repo

https://github.com/paustint/nx-bug-report-1

### Steps to Reproduce

In provided repo:
run `npm run build` and notice assets are not copied over.
run `npm run start` and notice `curl http://localhost:3000/assets/test.json` does not return file that should be returned.

If you want to try from scratch like I did to create above repo:

```shell
npx create-nx-workspace@latest

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Where would you like to create your workspace? · nx-test
✔ Which stack do you want to use? · node
✔ What framework should be used? · express
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · nx-test
✔ Would you like to generate a Dockerfile? [https://docs.docker.com/] · Yes
✔ Set up CI with caching, distribution and test deflaking · github

 >  NX   Creating your v18.0.2 workspace.

✔ Installing dependencies with npm
✔ Successfully created the workspace: nx-test.
✔ CI workflow with Nx Cloud has been generated successfully
✔ CI workflow has been generated successfully
```

### Nx Report

```shell
npx nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin-arm64
   npm    : 7.6.3

   nx                 : 18.0.2
   @nx/js             : 18.0.2
   @nx/jest           : 18.0.2
   @nx/linter         : 18.0.2
   @nx/eslint         : 18.0.2
   @nx/workspace      : 18.0.2
   @nx/devkit         : 18.0.2
   @nx/esbuild        : 18.0.2
   @nx/eslint-plugin  : 18.0.2
   @nx/node           : 18.0.2
   @nrwl/tao          : 18.0.2
   typescript         : 5.3.3
```

### Failure Logs

```shell
N/A
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I first encountered this on my existing project, and created a new project from scratch to see what I might be doing wrong.... but the default configuration out of the box is broken.

**Comment by lazybobcat** [comment]
I have the same issue and can't find out why. It was working two weeks ago but now it isn't.  I'm sorry I don't have any more information but I can't figure out what change could have affected this.

```
npx nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 20.9.0
   OS     : linux-x64
   npm    : 10.1.0

   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/linter         : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/workspace      : 18.0.4
   @nx/devkit         : 18.0.4
   @nx/esbuild        : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nrwl/tao          : 18.0.4
   @nx/vite           : 18.0.4
   @nx/web            : 18.0.4
   typescript         : 5.3.3
```

**Comment by Christop406** [comment]
Thanks for the workaround here, I am also seeing this issue but switching to the glob object fixed it for now 👍🏻

**Comment by ronnetzer** [comment]
I'm also experiencing this issue with latest nx (19.3.1), also glob pattern isn't working for `md` files

**Comment by cereum** [comment]
any updates on this?

**Comment by gi** [comment]
You can change the string from `"apps/nx-test/src/assets"` to `"apps/nx-test/src/assets/**/*"`. This fixed it for me without using the object syntax:

In `project.json`, `targets.build.options`:
```json
"assets": ["apps/server/src/assets/**/*"],
```

The assets are copied to the `dist/apps/{app-name]/src/assets` directory.

**Comment by ndcunningham** [comment]
Hey thanks for reporting, if you are using the single string the expected item should be a file.

If it is a folder it needs to be a glob. So to fix your issue you need to add `*` or `**/*` if necessary.
