### ISSUE TITLE
NX > 17.2.8 Crashes when running nx serve on Windows from directories with a space in their name

### ISSUE THREAD

**Issue by johnmeshulam** [nrwl/nx#21653]
### Current Behavior

When upgrading to NX > 17.2.8, projects which previously worked fine on windows crash when being served. This only occurs when the rootDir of the project has a space in its name. In this case - I ran the program from a folder called "My Folder".

I have experienced this behavior on both nx/next applications and nx/express applications.

### Expected Behavior

NX serve works as before without evaluating spaces in folder names as terminators.

### Steps to Reproduce

1. Create an project on Windows, make sure to include a space in the project rootDir name.
2. From the rootDir of the project, run `npx nx serve`
3. NX should crash instantly before serving the application.

### Nx Report

```shell
Node   : 18.19.0
   OS     : win32-x64
   npm    : 10.4.0

   nx                 : 18.0.2
   @nx/js             : 18.0.2
   @nx/jest           : 18.0.2
   @nx/linter         : 18.0.2
   @nx/eslint         : 18.0.2
   @nx/workspace      : 18.0.2
   @nx/devkit         : 18.0.2
   @nx/eslint-plugin  : 18.0.2
   @nx/express        : 18.0.2
   @nx/next           : 18.0.2
   @nx/node           : 18.0.2
   @nx/react          : 18.0.2
   @nrwl/tao          : 18.0.2
   @nx/web            : 18.0.2
   @nx/webpack        : 18.0.2
   typescript         : 5.3.3
```

### Failure Logs

```shell
Error: Cannot find module 'D:\My'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

I have tried creating a new project from scratch as well as reinstall Node and node_modules, nothing seemed to fix this issue. It only occurs on `nx serve`.

**Comment by johnmeshulam** [comment]
Closing this as it worked as expected on a different machine.

**Comment by byjokese** [comment]
@johnmeshulam im getting same, problem, reproduced it one 3 machines, but I do also have others that dont.

Did you get it working on the reported machine?

**Comment by nostromoJohn** [comment]
> @johnmeshulam im getting same, problem, reproduced it one 3 machines, but I do also have others that dont.
> 
> 
> 
> Did you get it working on the reported machine?

I didn't. Made a new folder without spaces.

**Comment by johnmeshulam** [comment]
> @johnmeshulam im getting same, problem, reproduced it one 3 machines, but I do also have others that dont.
> 
> 
> 
> Did you get it working on the reported machine?

I didn't end up solving it, made a new folder without spaces and it worked fine. I can re-open the issue if needed

**Comment by byjokese** [comment]
Not that easy I really need that name for internal stuff. Will investigate on my side then.
