### ISSUE TITLE
Webpack regression in v18 due to PR 20988

### ISSUE THREAD

**Issue by ryanhaugh** [nrwl/nx#21656]
### Current Behavior

https://github.com/nrwl/nx/pull/20988 introduced a Webpack regression in Nx v18 where parentheses aren't handled correctly in url.

20988 copies the fix done in the angular-cli repository: https://github.com/angular/angular-cli/pull/23691, but that fix introduced a regression that caused parentheses in url not to be handled correctly. https://github.com/angular/angular-cli/pull/23774 fixed this issue, and this fix should be implemented in this repo as well.

### Expected Behavior

Parentheses in url are handled correctly

### Steps to Reproduce

1. Add a test similar to the one [here](https://github.com/angular/angular-cli/pull/23774/files#diff-c4e4a0497e7b7e74e3ac70fc5d6751f307967fdbb575c7e43ad3332278d81fdbR710)

### Nx Report

```shell
Node   : 20.11.0
   OS     : darwin-arm64
   npm    : 10.2.4
   
   nx                 : 18.0.2
   @nx/js             : 18.0.2
   @nx/jest           : 18.0.2
   @nx/linter         : 18.0.2
   @nx/eslint         : 18.0.2
   @nx/workspace      : 18.0.2
   @nx/cypress        : 18.0.2
   @nx/devkit         : 18.0.2
   @nx/eslint-plugin  : 18.0.2
   @nx/plugin         : 18.0.2
   @nx/react          : 18.0.2
   @nx/rollup         : 18.0.2
   @nx/storybook      : 18.0.2
   @nrwl/tao          : 18.0.2
   @nx/web            : 18.0.2
   @nx/webpack        : 18.0.2
   typescript         : 5.3.3
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Fixed in: https://github.com/nrwl/nx/pull/21884
