### ISSUE TITLE
Root level targets cannot run with a specific configuration unless specifying the project name

### ISSUE THREAD

**Issue by JakeDern** [nrwl/nx#21657]
### Current Behavior

I have a project with root level nx targets defined in a root level `project.json` next to my root level `package.json`. See here:

```json
{
  "name": "HybridRelease",
  "$schema": "node_modules/nx/schemas/project-schema.json",
  "targets": {
    "get-configurations": {
      "executor": "nx:run-commands",
      "options": {
        "command": "echo {args.foo}"
      },
      "defaultConfiguration": "test",
      "configurations": {
        "prod": {
          "args": "--foo=bar"
        },
        "test": {
          "args": "--foo=bing"
        }
      }
    }
  }
}
```

Depending on which syntax I use to run this target it may or may not fail to execute. For example `nx get-configurations` runs just fine, but `nx get-configurations:test` fails to run. Here's the full matrix that I tried: 

<img width="627" alt="image" src="https://github.com/nrwl/nx/assets/33842784/504ab64e-e7eb-44fa-9937-0640d62505b5">

### Expected Behavior

I would expect the target to run in any of the following syntaxes:

* `nx target:configuration`
* `nx target`
* `nx project:target:configuration`

### GitHub Repo

Unfortunately I cannot provide the source repo

### Steps to Reproduce

1. Configure a root level nx target in `project.json` with more than one configuration.
2. Also configure a default configuration.
3. Attempt to execute the target via the following methods:
 `nx target:configuration`
 `nx target`
 `nx project:target:configuration`
4. Observe that the first method fails, but the second and third work

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.19.0
   OS     : linux-x64
   npm    : 10.2.3

   nx (global)        : 18.0.1
   nx                 : 18.0.1
   @nx/js             : 18.0.1
   @nx/jest           : 18.0.1
   @nx/linter         : 18.0.1
   @nx/eslint         : 18.0.1
   @nx/workspace      : 18.0.1
   @nx/devkit         : 18.0.1
   @nx/eslint-plugin  : 18.0.1
   @nx/plugin         : 18.0.1
   @nrwl/tao          : 18.0.1
   typescript         : 5.3.3
   ---------------------------------------
   Local workspace plugins:
         hybrid-build
```

### Failure Logs

```shell
>  NX   Cannot find configuration for task HybridRelease:get-configurations:test

Error: Cannot find configuration for task HybridRelease:get-configurations:test
    at ProcessTasks.createTask (/home/jakedern/repos/HybridRelease/node_modules/nx/src/tasks-runner/create-task-graph.js:156:19)
    at ProcessTasks.processTasks (/home/jakedern/repos/HybridRelease/node_modules/nx/src/tasks-runner/create-task-graph.js:23:39)
    at createTaskGraph (/home/jakedern/repos/HybridRelease/node_modules/nx/src/tasks-runner/create-task-graph.js:195:21)
    at createTaskGraphAndValidateCycles (/home/jakedern/repos/HybridRelease/node_modules/nx/src/tasks-runner/run-command.js:62:63)
    at /home/jakedern/repos/HybridRelease/node_modules/nx/src/tasks-runner/run-command.js:86:27
    at handleErrors (/home/jakedern/repos/HybridRelease/node_modules/nx/src/utils/params.js:9:22)
    at runCommand (/home/jakedern/repos/HybridRelease/node_modules/nx/src/tasks-runner/run-command.js:83:52)
    at Object.runOne (/home/jakedern/repos/HybridRelease/node_modules/nx/src/command-line/run/run-one.js:50:59)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Package Manager Version

Npm 10.2.3

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
`nx build` is a simplification of "infix" target notation (e.g. `nx build project`) where project is left to the default value which is determined by your cwd.

{proj:target:configuration} syntax is an alternate, used **_only_** for `nx run ...`.

For infix notation, you can set configuration by passing a flag (e.g. `nx build --configuration production`)
