### ISSUE TITLE
@nx/react-native:sync-deps Not Working (NX 18+)

### ISSUE THREAD

**Issue by enchorb** [nrwl/nx#21655]
### Current Behavior

All dependencies from root package.json are copied into mobile app specific package.json

### Expected Behavior

Prior to Nx 18 only the dependencies used by the app where added/ 

### Steps to Reproduce

1. Run sync-deps on Nx 18

### Nx Report

```shell
Node   : 18.16.1
   OS     : darwin-arm64
   yarn   : 4.0.1
   
   nx (global)        : 18.0.2
   nx                 : 18.0.2
   @nx/js             : 18.0.2
   @nx/jest           : 18.0.2
   @nx/linter         : 18.0.2
   @nx/eslint         : 18.0.2
   @nx/workspace      : 18.0.2
   @nx/cypress        : 18.0.2
   @nx/detox          : 18.0.2
   @nx/devkit         : 18.0.2
   @nx/eslint-plugin  : 18.0.2
   @nx/express        : 18.0.2
   @nx/next           : 18.0.2
   @nx/node           : 18.0.2
   @nx/plugin         : 18.0.2
   @nx/react          : 18.0.2
   @nx/react-native   : 18.0.2
   @nx/storybook      : 18.0.2
   @nrwl/tao          : 18.0.2
   @nx/vite           : 18.0.2
   @nx/web            : 18.0.2
   @nx/webpack        : 18.0.2
   typescript         : 5.3.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
it was actually intended. there was an issue someone opened where there is a package needed to be used by ios, but is not referenced in the code, so it did not get added when doing `pod install`. so i changed it to include all the dependencies.

**Comment by enchorb** [comment]
We now have the issue where we have 2 different Nx react native apps and they are bundling unused dependencies. One of them is erroring because it depends on a library that requires changes to and android/ file which the other does not have.

**Comment by guillempuche** [comment]
For my excluding https://nx.dev/nx-api/react-native/executors/sync-deps doesn't work.

@nx/react-native v18.0.4

```json
"sync-deps": {
      "executor": "@nx/expo:sync-deps",
      "options": {
        "exclude": [
          "metro",
          "metro-resolver"
        ]
      }
},
```

**Comment by whoisdominic** [comment]
We are experiencing the same behavior using @nx/expo:sync-deps on version 18.0.4. All of our dependencies from the project including dev dependencies are being added

**Comment by whoisdominic** [comment]
> it was actually intended. there was an issue someone opened where there is a package needed to be used by ios, but is not referenced in the code, so it did not get added when doing `pod install`. so i changed it to include all the dependencies.

Wouldn't placing the dependency inside manually be a better solution than dumping every dependency in the application??

**Comment by guillempuche** [comment]
> Excluding https://nx.dev/nx-api/react-native/executors/sync-deps doesn't work.
> 
> The new Expo Router v3 requires to not use `metro` and `metro-resolver` in the package.json https://docs.expo.dev/router/installation/#update-resolutions
> 
> @nx/react-native v18.0.4
> 
> ```json
> "sync-deps": {
>       "executor": "@nx/expo:sync-deps",
>       "options": {
>         "exclude": [
>           "metro",
>           "metro-resolver"
>         ]
>       }
> },
> ```

@xiongemi, the PR doesn't solve that problem I pointed
