### ISSUE TITLE
The @nx/js:swc executor doesn't check the version of @swc/cli

### ISSUE THREAD

**Issue by torfmaster** [nrwl/nx#21662]
### Current Behavior

The executor assumes a specific version of the swc cli (i.e. 0.1.62). However, it does not validate this version. As in version 0.3 swc introduced the strip leading path [option](https://swc.rs/docs/usage/cli#--strip-leading-paths) with a default behavior which differs from the 0.2 versions artifacts produced by a swc compiler >=0.3.0 are unusable.

### Expected Behavior

swc accepts only compatible versions of @swc/cli.

### Steps to Reproduce

1. create a fresh nx project
2. create a node library inside with swc as its compiler
3. build library
4. upgrade swc

### Nx Report

```shell
Node   : 18.14.1
   OS     : linux-x64
   pnpm   : 8.15.1
   
   nx                 : 18.0.2
   @nx/js             : 18.0.2
   @nx/jest           : 18.0.2
   @nx/linter         : 18.0.2
   @nx/eslint         : 18.0.2
   @nx/workspace      : 18.0.2
   @nx/devkit         : 18.0.2
   @nx/eslint-plugin  : 18.0.2
   @nrwl/tao          : 18.0.2
   typescript         : 5.3.3
```

### Failure Logs

```shell
Before upgrade

$ find dist
dist
dist/mylib
dist/mylib/package.json
dist/mylib/README.md
dist/mylib/src
dist/mylib/src/index.d.ts
dist/mylib/src/index.js.map
dist/mylib/src/lib
dist/mylib/src/lib/mylib.js
dist/mylib/src/lib/mylib.d.ts
dist/mylib/src/lib/mylib.js.map
dist/mylib/src/index.js
```

after upgrade

```
$ find dist
dist
dist/mylib
dist/mylib/package.json
dist/mylib/mylib
dist/mylib/mylib/src
dist/mylib/mylib/src/index.js.map
dist/mylib/mylib/src/lib
dist/mylib/mylib/src/lib/mylib.js
dist/mylib/mylib/src/lib/mylib.js.map
dist/mylib/mylib/src/index.js
dist/mylib/README.md
dist/mylib/src
dist/mylib/src/index.d.ts
dist/mylib/src/lib
dist/mylib/src/lib/mylib.d.ts
```

### Package Manager Version

pnpm 8.15.1

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

# Possible Resolutions

## Check swc version

In `packages/js/src/utils/swc/compile-swc.ts` check the version and fail if it doesn't match (with a speaking error message). This at least helps to find the issue.

## Add required flags

In the same file add the required flag and upgrade the version in `versions.ts` to a version higher than >=0.3.0 (unfortunately swc rejects unknown parameters so keeping the version is no option).

## Do not use swc/cli

swc/cli has no type safe interface (command line interface). Otherwise the errors on upgrade could have been detected. Use swc directly and make it somehow an optional dependency of nx.

If there is an option that doesn't require very deep knowledge I'm willing to implement one of the solutions. However, currently I do not know which one to pick.

**Comment by jaysoo** [comment]
This has been fixed here [701c513fd7ccbc52a6ee3c0aed3cbf342007e5f9](https://github.com/nrwl/nx/pull/22856)
