### ISSUE TITLE
"Error: project undefined not found" for new React Library on NX18

### ISSUE THREAD

**Issue by WonderPanda** [nrwl/nx#21675]
### Current Behavior

We just recently updated our monorepo to NX 18. 

The main application in our codebase is Vite + React.

When attempting to add a new React Library to our codebase using the @nx/react:library generator the application will no longer serve the moment a component from that library is imported. We get the following error logs from the NX daemon

`Error: project undefined not found`

### Expected Behavior

Adding a new React Library and consuming components from it in a Vite application should work correctly

### Steps to Reproduce

1. Generate a new React library using the following `pnpm exec nx generate @nx/react:library --name=test-lib --unitTestRunner=vitest --directory=libs/frontend/test-lib --compiler=swc --component=false --importPath=@test/test-lib --projectNameAndRootFormat=as-provided --style=none --no-interactive`
2. Attempt to import a component from that library into React Vite application and observe that it will no longer serve

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.8.1
   OS     : linux-x64
   pnpm   : 8.12.1

   nx                 : 18.0.1
   @nx/js             : 18.0.1
   @nx/jest           : 18.0.1
   @nx/linter         : 18.0.1
   @nx/eslint         : 18.0.1
   @nx/workspace      : 18.0.1
   @nx/cypress        : 18.0.1
   @nx/devkit         : 18.0.1
   @nx/esbuild        : 18.0.1
   @nx/eslint-plugin  : 18.0.1
   @nx/nest           : 18.0.1
   @nx/node           : 18.0.1
   @nx/playwright     : 18.0.1
   @nx/react          : 18.0.1
   @nx/storybook      : 18.0.1
   @nrwl/tao          : 18.0.1
   @nx/vite           : 18.0.1
   @nx/web            : 18.0.1
   @nx/webpack        : 18.0.1
   typescript         : 5.3.3
```

### Failure Logs

```shell
Error: project undefined not found
    at NativeTaskHasherImpl.hashTasks (/home/jesse/code/work/eluve/eluve-nx/node_modules/.pnpm/nx@18.0.1_@swc-node+register@1.6.8_@swc+core@1.3.95/node_modules/nx/src/hasher/native-task-hasher-impl.js:33:36)
    at InProcessTaskHasher.hashTasks (/home/jesse/code/work/eluve/eluve-nx/node_modules/.pnpm/nx@18.0.1_@swc-node+register@1.6.8_@swc+core@1.3.95/node_modules/nx/src/hasher/task-hasher.js:53:50)
    at handleHashTasks (/home/jesse/code/work/eluve/eluve-nx/node_modules/.pnpm/nx@18.0.1_@swc-node+register@1.6.8_@swc+core@1.3.95/node_modules/nx/src/daemon/server/handle-hash-tasks.js:20:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleResult (/home/jesse/code/work/eluve/eluve-nx/node_modules/.pnpm/nx@18.0.1_@swc-node+register@1.6.8_@swc+core@1.3.95/node_modules/nx/src/daemon/server/server.js:110:16)
    at async handleMessage (/home/jesse/code/work/eluve/eluve-nx/node_modules/.pnpm/nx@18.0.1_@swc-node+register@1.6.8_@swc+core@1.3.95/node_modules/nx/src/daemon/server/server.js:84:9)
    at async /home/jesse/code/work/eluve/eluve-nx/node_modules/.pnpm/nx@18.0.1_@swc-node+register@1.6.8_@swc+core@1.3.95/node_modules/nx/src/daemon/server/server.js:45:9 {
  code: 'GenericFailure'
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by PaulMest** [comment]
It appears that when running the generator command on Linux, there are modifications to `nx.json` that cause a build failure. When running this same command on macOS, there are no modifications to `nx.json` and the new lib works just fine.

<img width="928" alt="image" src="https://github.com/nrwl/nx/assets/1721104/887c42bf-eedf-4f9a-8465-82956e5e4342">

Once I remove those changes from `nx.json`, the build works again.

**Comment by AgentEnder** [comment]
The modifications to nx.json are being skipped because of an env var we put in `.env` during migrate. That should be distributed to other team members machines.

This'll still be investigated.

**Comment by stephenwade** [comment]
Making sure every team member sets an env var should not be the only way to opt out of this or any Nx behavior. Please add a setting in `nx.json` to disable Project Crystal.

**Comment by ksjogo** [comment]
> > I am trying to convert our exisiting nx monorepo to crystal and also have this issue. The task graph seems fine, but when running an auto-generated command I now get that issue.
> 
> Have you tried adding this to your .env?
> 
> ```
> # Nx 18 enables using plugins to infer targets by default
> # This is disabled for existing workspaces to maintain compatibility
> # For more info, see: https://nx.dev/concepts/inferred-tasks
> NX_ADD_PLUGINS=false
> ```

I actually want to opposite.
I want to migrate to crystal from an existing project.
Did add the plugins etc.
But now when running tasks I get this.

Is there some migration guide?

**Comment by HybridFox** [comment]
I am getting exactly the same error trying to build a next application:

```#15 1.746
#15 1.746 > web_main@0.1.0 nx
#15 1.746 > nx run frontend:build:production --verbose
#15 1.746
#15 7.093
#15 7.093  >  NX   project undefined not found
#15 7.093
#15 7.093
#15 7.093 Error: project undefined not found
#15 7.093     at NativeTaskHasherImpl.hashTasks (/app/node_modules/nx/src/hasher/native-task-hasher-impl.js:33:36)
#15 7.093     at InProcessTaskHasher.hashTasks (/app/node_modules/nx/src/hasher/task-hasher.js:53:50)
#15 7.093     at hashTasksThatDoNotDependOnOutputsOfOtherTasks (/app/node_modules/nx/src/hasher/hash-task.js:25:33)
#15 7.093     at async invokeTasksRunner (/app/node_modules/nx/src/tasks-runner/run-command.js:126:5)
#15 7.093     at async /app/node_modules/nx/src/tasks-runner/run-command.js:89:24
#15 7.093     at async handleErrors (/app/node_modules/nx/src/utils/params.js:9:16)
#15 7.093     at async runCommand (/app/node_modules/nx/src/tasks-runner/run-command.js:83:20)
#15 7.093     at async Object.runOne (/app/node_modules/nx/src/command-line/run/run-one.js:50:24)```

**Comment by kristofvranckx** [comment]
I had this same issue when migrating an existing project to project crystal. In my case, the issue was a `package.json` that was missing a name field.

I would recommand having a look at the ouput of the project graph by running `nx graph --file=output.json` and see if there is a project where name is `undefined`.

**Comment by wootencl** [comment]
Seeing this issue on my end as well. Only in CI though. Removing the `plugins` from `nx.json` and making sure the explicit `test` and `lint` `targets` were in the project's `project.json` remedied the issue. No luck finding a project/`package.json` without a name to which the issue can be attributed. Looking to opt in to Project Crystal as well but blocked until this is resolved.

**Comment by wootencl** [comment]
After some further sleuthing locally with `act` was able to determine the issue was related to a `package.json` brought in from other Github action logic. Many thanks @kristofvranckx.
