### ISSUE TITLE
NX 18 workspace creation seems to be broken

### ISSUE THREAD

**Issue by vadjs** [nrwl/nx#21682]
### Current Behavior

I've tried to reproduce some issues using NX 18 but encountered the new one, seems more serious.
When i've tried to go through standard workspace creation flow, I've got a completely broken workspace as a result.
No NX commands works fine, even `nx report`

### Expected Behavior

Flow should work.

### Steps to Reproduce

npx create-nx-workspace@latest

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Where would you like to create your workspace? · test-nx-18
✔ Which stack do you want to use? · react
✔ What framework would you like to use? · none
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · dummy
✔ Which bundler would you like to use? · webpack
✔ Test runner to use for end to end (E2E) tests · playwright
✔ Default stylesheet format · scss
✔ Do you want Nx Cloud to make your CI fast? · github

 >  NX   Creating your v18.0.2 workspace.

✔ Installing dependencies with npm
✔ Successfully created the workspace: test-nx-18.
✖ Setting up Nx Cloud

 >  NX   Failed to setup Nx Cloud

   Error:
 >  NX   Cannot convert object to primitive value

### Nx Report

```shell
Impossible to get it. Even `nx reset` doesn't help.

nx report

 >  NX   Cannot convert object to primitive value


   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
```
```


### Failure Logs

_No response_

### Package Manager Version

node v20.11.0, npm 10.4.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by Aubrey-Russell** [comment]
try this which seems to work-> pnpm install create-nx-workspace

pnpm create-nx-workspace --latest

**Comment by AgentEnder** [comment]
Can you upload one of these workspaces to github so we can investigate?

**Comment by vadjs** [comment]
@AgentEnder There is a resulting code: https://github.com/vadjs/nx-18-bug

@Aubrey-Russell I suppose NX should work properly with NPM as well.

**Comment by vadjs** [comment]
@AgentEnder problem is still there(NX 18.0.4).
