### ISSUE TITLE
nx run rust panic in older versions of Windows

### ISSUE THREAD

**Issue by gbtb** [nrwl/nx#21700]
### Current Behavior

When running arbitrary nx run command (e.g. `nx run webpack-dev`) on older versions of Windows 10 (as well as Windows Server 2016) we receive a Rust panic. 

Digging around for a bit, it looks like that a reason for this is the usage of portable-pty dependency, specifically [this code](https://github.com/wez/wezterm/blob/4f123a461bffdd8ac2e21c0697d02c5c992abd29/pty/src/win/psuedocon.rs#L51) 

### Expected Behavior

Ideally, I would expect nx to run on any release of Windows 7/10 or Windows Server 2016+, because I don't think that modern terminal support is a hard requirement for a Node JS CLI tool. 
To the very least, it would be nice to have this requirement mentioned in the docs or readme.

### Steps to Reproduce

1. Install and initialize nx in any node js app on Windows 10 older than 2018 release.
2. Try to run any package.json script with nx - `npx nx run script`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.11.0
   OS     : win32-x64
   npm    : 10.4.0

   nx          : 17.3.2
   @nrwl/tao   : 17.3.2
   typescript  : 4.6.4
```

### Failure Logs

```shell
> nx run asp.net:webpack-dev

thread '<unnamed>' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crat
8.1\src\win\psuedocon.rs:47:63:
this system does not support conpty.  Windows 10 October 2018 or newer is required
doConsole" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information
I tried a couple of things to fix this issue:
1. Installing Microsoft Terminal as a separate package through choco - failed with a similar error about unsupported version
2. While looking into psuedocon.rs I've noticed that it tries to load conpty.dll as well, so I tried to add conpty.dll from https://github.com/wez/wezterm/blob/4f123a461bffdd8ac2e21c0697d02c5c992abd29/assets/windows/conhost/README.md to node_modules\@nx\nx-win32-x64-msvc. This also didn't help to resolve the issue.
3. Bisecting different nx versions, I found that v16 is the last major versions that works in outdated Windows versions

_No response_

**Comment by jebriggs** [comment]
We're experiencing the same problem when trying to upgrade nx right after installing creating a new workspace with create-nx-workspace using version 18.0.4, but I believe the same problem occurred with 17.3.1, will have to check. Last successful update was 17.2.8. 

Windows machines are all managed so we can't upgrade Windows.  We've just cross over from evaluation to committing to use nx for our monorepo, so this is a blocker.
Node 18.18.0
NPM: 9.8.1
windows server 2016

thread '<unnamed' panicked at c:\users\runneradmin\.cargo\git\checkouts\ etc. psuedocon.rs:47:63
this system does nto support cnpty. Windows 10 October 2018 or newer is required: SymbolNotFound {symbol:"CreatePseudoConsole"}
note:run with `RUST_BACKTRACE=1 evnironment varia ble to display a backtrace.

**Comment by Cammisuli** [comment]
Sorry about that! I'll create a fix for this asap.

**Comment by Cammisuli** [comment]
as a temporary workaround, setting the env var `NX_NATIVE_COMMAND_RUNNER=false` should allow Nx to work the same way before.

**Comment by gbtb** [comment]
> Sorry about that! I'll create a fix for this asap. If you all don't mind, can you open a node repl, and type in `os.release()`, and give me the value?
> 
> I'd like to see how the version shows up for Windows Server vs Windows Desktop, etc

Here's how version string looks like for Windows Server 2016 - '10.0.14393'. For Windows Server 2019 it's '10.0.17763'. I'll add examples of desktop version strings on Monday.


> as a temporary workaround, setting the env var `NX_NATIVE_COMMAND_RUNNER=false` should allow Nx to work the same way before.

Thanks for a workaround, it indeed does work!

**Comment by jebriggs** [comment]
Thanks!  The workaround also works for me.  The version I get from winver is:

Microsoft Windows Server
Version 1607 (OS Build 143.6614)

and this is also for Windows Server 2016

**Comment by gbtb** [comment]
Couple more examples of os.release from desktop windows machines:
10.0.19045 - rust-based version works well
10.0.16299 - rust-based version doesn't work

**Comment by Cammisuli** [comment]
Ok, thanks everyone. I'll figure something out based on these versions.
