### ISSUE TITLE
nx release does not include the correct files

### ISSUE THREAD

**Issue by davidsilva2841** [nrwl/nx#21718]
### Current Behavior

When running nx release, the package created does not include the correct files

Partial output from `nx release --first-release --projects=lib1 --verbose`
```
📦  @nx-app/lib1@0.0.6
=== Tarball Contents ===

156B  .babelrc                
331B  .eslintrc.json          
166B  README.md               
200B  package.json            
179B  project.json            
28B   src/index.ts            
76B   src/lib/lib1.module.scss
240B  src/lib/lib1.spec.tsx   
270B  src/lib/lib1.tsx        
402B  tsconfig.json           
494B  tsconfig.lib.json       
503B  tsconfig.spec.json      
1.7kB vite.config.ts    
```

Created package.json that's deployed (notice the file paths aren't included in the tarball)
```
{
  "name": "@nx-app/lib1",
  "version": "0.0.3",
  "main": "./index.js",
  "types": "./index.d.ts",
  "exports": {
    ".": {
      "import": "./index.mjs",
      "require": "./index.js"
    }
  }
}
```

### Expected Behavior

The correct files should be included in the tarball

### Steps to Reproduce

```
npx create-nx-workspace@latest --preset=react-standalone --bundler=vite --pm yarn
nx g @nx/react:library lib1 --unitTestRunner=vitest --bundler=vite --importPath=@nx-app/lib1 --directory=libs/lib1
nx release --first-release --projects=lib1 --verbose
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : darwin-arm64
   yarn   : 4.1.0
   
   nx                 : 18.0.2
   @nx/js             : 18.0.2
   @nx/linter         : 18.0.2
   @nx/eslint         : 18.0.2
   @nx/workspace      : 18.0.2
   @nx/devkit         : 18.0.2
   @nx/eslint-plugin  : 18.0.2
   @nx/react          : 18.0.2
   @nrwl/tao          : 18.0.2
   @nx/vite           : 18.0.2
   @nx/web            : 18.0.2
   typescript         : 5.3.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JamesHenry** [comment]
@davidsilva2841 I'm sorry for the delay in getting back to you here.

It looks like you have not built your project before releasing it, so you only have your source TypeScript files to work with.

The most powerful way to orchestrate things how you want it is using a release script and then leverage the programmatic API for nx release: https://nx.dev/features/manage-releases#using-the-programmatic-api-for-nx-release

That way you can invoke an ```execSync(`npx nx run-many -t build`)``` or equivalent whenever makes the most sense for your workflow (and possibly move files around etc)

Hope that helps for now!
