### ISSUE TITLE
No dependency graph detection inside .astro files

### ISSUE THREAD

**Issue by airtonix** [nrwl/nx#21733]
### Current Behavior

1. have a nx monorepo with a single `package.json` and many `project.json`
2. within this monorepo, have an astro app
3. this astro should only contain `pages/*.astro` files, where it imports react components from the rest of the monorepo
4. within this monorepo, also have a nextjs app (to demonstrate what is expected)
5. this nextjs app should import the same composable react components in `app/*.tsx` (or `pages/*.tsx` it doesn't matter which) from the rest of the monorepo
6. run `nx graph`
7. tick show all

✅ the nextjs app shows all the monorepo dependencies detected from the `pages/*.tsx` files.
🛑 the astro app shows no monorepo dependencies for the the `pages/*.astro` files.

### Expected Behavior

✅ the nextjs app should show all the monorepo dependencies detected from the `pages/*.tsx` files.
✅ the astro app should show all monorepo dependencies detected for the the `pages/*.astro` files.

`nx affected --target=build` should also include the astro project if i modify the card component.

### GitHub Repo

https://github.com/airtonix/nx-no-astro-dependencie-bug

### Steps to Reproduce

```
git clone https://github.com/airtonix/nx-no-astro-dependencie-bug
cd nx-no-astro-dependencie-bug
npm i
npx nx graph
```

### Nx Report

```shell
x npx nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : linux-x64
   npm    : 10.2.3
   
   nx                 : 18.0.3
   @nx/js             : 18.0.3
   @nx/jest           : 18.0.3
   @nx/linter         : 18.0.3
   @nx/eslint         : 18.0.3
   @nx/workspace      : 18.0.3
   @nx/devkit         : 18.0.3
   @nx/eslint-plugin  : 18.0.3
   @nx/next           : 18.0.3
   @nx/react          : 18.0.3
   @nrwl/tao          : 18.0.3
   @nx/web            : 18.0.3
   @nx/webpack        : 18.0.3
   typescript         : 5.3.3
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

overview: 

![image](https://github.com/nrwl/nx/assets/61225/1bd5b321-5fab-4de3-9a46-43d43d6dd884)

`npx nx graph`

![image](https://github.com/nrwl/nx/assets/61225/42b6f118-761a-46bc-91e7-cfb4afe3358a)

`npx nx run web-with-astro:serve`

![image](https://github.com/nrwl/nx/assets/61225/d36653a8-e74e-440d-a4c3-8a8db0ede06b)

![image](https://github.com/nrwl/nx/assets/61225/d11c1f4d-bda5-46f1-aad3-522e95441f21)

`npx nx run web-with-nextjs:dev`

![image](https://github.com/nrwl/nx/assets/61225/72522494-270a-4a9e-a292-9a8d9c13e8b8)

![image](https://github.com/nrwl/nx/assets/61225/3d6d6d48-d287-410b-ae4a-63a765354608)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This is expected. Nx performs static analysis for JS/TS and `.vue` files out-of-the-box. Astro files have a custom syntax and require to be processed by the Astro compiler. As with many other technologies, a community plugin can provide this functionality. A custom plugin is required to [extend the project graph](https://nx.dev/extending-nx/recipes/project-graph-plugins) and create the necessary nodes and dependencies.

I'm going to close this since it's working as expected, and there are currently no plans to provide first-party support for Astro.

**Comment by airtonix** [comment]
@leosvelperez ok then, perhaps a good actionable solution is to update the documentation under the getting started with NX and astro so this is called out?

**Comment by airtonix** [comment]
ok the answer is actually to use https://github.com/nxtensions/nxtensions/tree/main/packages/astro as a plugin in your `nx.json`: 

`nx.json`
```
{
  ...
  plugins: [
    '@nxtensions/astro'
  ]
  ...
}
```
