### ISSUE TITLE
Error: 'les' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by esthrim** [nrwl/nx#21742]
### Current Behavior

When I run this command on windows command prompt : 
`npx create-nx-workspace --pm pnpm`

it's giving me this error : 
` NX   Failed to create a workspace.

   Error: 'les' is not recognized as an internal or external command,
operable program or batch file.

I try also the second time now the error is : 

` NX   Failed to create a workspace.

   Error: 'odules' is not recognized as an internal or external command,
operable program or batch file.`

I'm using pnpm version 8.15.1, nodejs version 20.11.0 and windows 11 without wsl

maybe there is something broken command or text in the windows environment ?
![Screenshot 2024-02-09 135210](https://github.com/nrwl/nx/assets/2139726/0e803e31-a612-4dd8-950d-50daf75ac6cb)

### Expected Behavior

it suppose to generate the workspace successfully

### Steps to Reproduce

1.
`npx create-nx-workspace --pm pnpm`

### Nx Report

```shell
>  NX   Failed to create a workspace.

   Error: 'les' is not recognized as an internal or external command,
operable program or batch file.
```

### Failure Logs

```shell
>  NX   Failed to create a workspace.

   Error: 'les' is not recognized as an internal or external command,
operable program or batch file.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by esthrim** [comment]
![image](https://github.com/nrwl/nx/assets/2139726/ebf15206-3865-4d52-8a78-cd1a392574b1)

**Comment by joelpelaez** [comment]
I have the same issue, I tried using create-nx-workspace with react preset and create a empty monorepo and add @nx/react and @nx/workspace after that, but is the same issue.

Using the command `npx nx g @nx/workspace:preset --name=main3 --preset=react-monorepo --e2eTestRunner=none --bundler=vite`

This only happens with pnpm.

I checked if some packages that @nx/react installs are present before execute the generator the command is executed successfully.

If them are not preset outputs something like that:

```
C:\Users\user\source\repos\nx\tmp\org1>_modules;C:\Users\user\source\repos\nx\tmp\org1\node_modules\.pnpm\node_modules;C:\Users\user\source\repos\nx\tmp\org1\node_modules\.pnpm\nx@19.0.0-canary.1\node_modules\nx\bin\node_modules;C:\Users\user\source\repos\nx\tmp\org1\node_modules\.pnpm\nx@19.0.0-canary.1\node_modules\nx\node_modules;C:\Users\user\source\repos\nx\tmp\org1\node_modules\.pnpm\nx@19.0.0-canary.1\node_modules;C:\Users\user\source\repos\nx\tmp\org1\node_modules\.pnpm\node_modules"
"_modules" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
```

The package @swc-node/register is also involved in this issue, If this package is removed and react preset is executed throws this log:

```
C:\Users\user\source\repos\nx\tmp\org1>C:\Users\user\source\repos\nx\tmp\org1\node_modules\.bin\\node.exe" (
"C:\Users\user\source\repos\nx\tmp\org1\node_modules\.bin\\node.exe" (" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

C:\Users\user\source\repos\nx\tmp\org1>"C:\Users\user\source\repos\nx\tmp\org1\node_modules\.bin\\node.exe"  "C:\Users\user\source\repos\nx\tmp\org1\node_modules\.bin\\..\nx\bin\nx.js" "g" "@nx/workspace:preset" "--name=main3" "--preset=react-monorepo" "--e2eTestRunner=none" "--bundler=vite"
""C:\Users\user\source\repos\nx\tmp\org1\node_modules\.bin\\node.exe"" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

C:\Users\user\source\repos\nx\tmp\org1>node  "C:\Users\user\source\repos\nx\tmp\org1\node_modules\.bin\\..\nx\bin\nx.js" "g" "@nx/workspace:preset" "--name=main3" "--preset=react-monorepo" "--e2eTestRunner=none" "--bundler=vite"
```

and retries to execute the command again.

But if the command is executed directly using node:

```
node  "C:\Users\user\source\repos\nx\tmp\org1\node_modules\.bin\\..\nx\bin\nx.js" "g" "@nx/workspace:preset" "--name=main3" "--preset=react-monorepo" "--e2eTestRunner=none" "--bundler=vite"
```

The error doesn't happen.

I tried to check the cmd.exe calls and intercept them using COMSPEC environment variable but I cannot get information about the caller. cmd.exe can be called directly or some part of pnpm process is executed by cmd.exe

This sees similar to this issue https://github.com/pnpm/pnpm/issues/7181 . But I cannot confirm if pnpm is the real curprit.

**Comment by BensEye** [comment]
![image](https://github.com/nrwl/nx/assets/165655152/11777dbb-4246-45f4-aafa-909c41ac9c34)

Similar issue here.
Attempted to install with `npx create-nx-workspace@latest --preset=next --pm pnpm`.
