### ISSUE TITLE
Targets with `dependsOn` cant be cancelled with `Crtl+C`

### ISSUE THREAD

**Issue by jerkovicl** [nrwl/nx#21744]
### Current Behavior

If the target has `dependsOn` defined then it cant be cancelled with `Ctrl+C`, if you remove `dependsOn` from `project.json` then it works

### Expected Behavior

Target with `dependsOn` can be cancelled
This worked on nx `v18.0.2`

### GitHub Repo

https://github.com/jerkovicl/nx-examples/tree/bug/angular-ts-dependson-target

### Steps to Reproduce

1. `nx run products:serve`
2. try to cancel `serve` target with `Ctrl+C`

### Nx Report

```shell
Node   : 20.11.0
   OS     : win32-x64
   npm    : 10.2.4

   nx (global)        : 18.0.3
   nx                 : 18.0.3
   @nx/js             : 18.0.3
   @nx/jest           : 18.0.3
   @nx/linter         : 18.0.3
   @nx/eslint         : 18.0.3
   @nx/workspace      : 18.0.3
   @nx/angular        : 18.0.3
   @nx/cypress        : 18.0.3
   @nx/devkit         : 18.0.3
   @nx/eslint-plugin  : 18.0.3
   @nx/react          : 18.0.3
   @nrwl/tao          : 18.0.3
   @nx/web            : 18.0.3
   @nx/webpack        : 18.0.3
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 17.1.0
   @ngrx/effects         : 17.1.0
   @ngrx/entity          : 17.1.0
   @ngrx/router-store    : 17.1.0
   @ngrx/store           : 17.1.0
   @ngrx/store-devtools  : 17.1.0
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by jerkovicl** [comment]
Tested with 18.0.4, but still an issue

**Comment by jerkovicl** [comment]
Using `NX_NATIVE_COMMAND_RUNNER=false` as a workaround fixes the issue

**Comment by t-lechner** [comment]
We got the same issue on Windows and nx@18.0.5 - it was working with nx@17.2.3 
Was able to reproduce with a minimal setup

1) npx create-nx-workspace@latest / npx create-nx-workspace@17.2.3
2) nx g lib debug-lib
3) update the project.json
```json
{
  "name": "debug-lib",
  "$schema": "../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "myapp/src",
  "projectType": "library",
  "targets": {
    "build": {
      "command": "echo Build",
      "dependsOn": ["prebuild"]
    },
    "prebuild": {
      "command": "echo Prebuild"
    }
  },
  "tags": []
}
```


4) nx run debug-lib:build

with @latest it cannot be canceld
with @17.2.3 it works

Thanks @jerkovicl your workaround works for us as well :)

> Using `NX_NATIVE_COMMAND_RUNNER=false` as a workaround fixes the issue


I think the following issues are related to the same problem:

- https://github.com/nrwl/nx/issues/22094
- https://github.com/nrwl/nx/issues/21978
- https://github.com/nrwl/nx/issues/21965

Cheers Thomas
