### ISSUE TITLE
Storybook plugin is crashing when using SWC

### ISSUE THREAD

**Issue by ItayAssouline** [nrwl/nx#21767]
### Current Behavior

When using SWC compiler in a react app (Webpack), the @nx/react/plugins/storybook is looking for babel config (and if there's one it throws other errors like `cannot create nodes...`). 
tried editing the configs (adding useSWC / storybook-addon-swc), but seems like the storybook plugin itself requires babel (because if I remove it, the errors go away and storybook boots up, but I get no support for NX imports) 

### Expected Behavior

react storybook plugin should not crash when project is natively with SWC 

### Steps to Reproduce

1. create an NX integrated monorepo
2. generate a react app, with Webpack bundler, SWC compiler, no e2e test runner, globalCSS enabled, pascalCaseFiles enabled and the rest as defaults)
3. add storybook configuration with the @nx/react:storybook-configuration (on defaults)
4. run storybook for this project

### Nx Report

```shell
Node   : 21.6.1
   OS     : win32-x64
   pnpm   : 8.15.1

   nx (global)        : 18.0.3
   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/jest           : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/workspace      : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nx/react          : 18.0.4
   @nx/storybook      : 18.0.4
   @nx/web            : 18.0.4
   @nx/webpack        : 18.0.4
   typescript         : 5.3.3
```

### Package Manager Version

pnpm

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Not sure if it's a bug or a yet-to-be-implemented feature,
but for the time being im using only the NX generators and getting errors so feels like a bug

**Comment by R-J-dev** [comment]
As far as I know Storybook 7 loads babel by default and storybook-addon-swc overwrites that loader with a swc loader. So If you have removed the babelrc, I guess you run into this error as well that is described here: https://github.com/Karibash/storybook-addon-swc/issues/52.

**Comment by Coly010** [comment]
Can we confirm if this is still an issue? I was unable to reproduce this on `nx@18.2.4`
