### ISSUE TITLE
Cannot Import './plugin' Subpath from @nx/vite Due to "exports" Field Restriction

### ISSUE THREAD

**Issue by zackmoun** [nrwl/nx#21764]
### Current Behavior

Attempting to import or require a subpath (./plugin) from @nx/vite results in an error indicating that the package subpath './plugin' is not defined by "exports" in /node_modules/@nx/vite/package.json.

### Expected Behavior

A clear explanation of how to correctly extend or interact with @nx/vite using the intended plugin mechanism, or an update to the package's exports field to allow such imports if they are meant to be supported.

### Steps to Reproduce

1. Install @nx/vite version 17.1.2 in an Nx workspace.
2. Try to import or require the ./plugin subpath in any module, e.g., require('@nx/vite/plugin') or import '@nx/vite/plugin'.
3. Observe the error: Package subpath './plugin' is not defined by "exports" in /node_modules/@nx/vite/package.json.

### Nx Report

```shell
The console outputs the error: NX Package subpath './plugin' is not defined by "exports" in /.../node_modules/@nx/vite/package.json.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
The plugin export was not ready until Nx 18, where it is already marked as exposed.

**Comment by zackmoun** [comment]
@AgentEnder Thanks for let me know :)
