### ISSUE TITLE
Support web in @nx/expo

### ISSUE THREAD

**Issue by guillempuche** [nrwl/nx#21774]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Currently `project.json` supports iOS and Android:

```json
"run-ios": {
      "executor": "@nx/expo:run",
      "dependsOn": [
        "ensure-symlink",
        "sync-deps"
      ],
      "options": {
        "platform": "ios"
      }
},
```
It should also support `web` and update docs https://nx.dev/nx-api/expo/executors

## Motivation

Expo is becoming a universal framework: native and web. Thanks to Expo 50 https://expo.dev/changelog/2024/01-18-sdk-50 and Expo Router https://docs.expo.dev/router/introduction/.

> Expo Router is a file-based router for React Native and web applications.

**Comment by xiongemi** [comment]
does you project.json has serve target, like:

```
    "serve": {
      "executor": "@nx/expo:serve",
      "options": {
        "port": 8081
      }
    },
```

if not, you can add this target and run `nx serve <your app>`.
also, you can run `nx start <your app> --web` to run the app on web.

**Comment by guillempuche** [comment]
Good, it's opening https://github.com/guillempuche/nx-expo-next-tamagui/blob/main/apps/expo/project.json the web on my browser now.

It's not rendering it, but I suppose an issue in my code.
