### ISSUE TITLE
Adding a package.json to a lib will prevent NX looking for .npmrc files in the root.

### ISSUE THREAD

**Issue by grumpyoldman-io** [nrwl/nx#21798]
### Current Behavior

When running a `release publish` to a private Github package repository NX is unable to add the correct authentication token via `.npmrc` from the repo's root `.npmrc` when that lib (in a subfolder like `./libs/my-test-lib`) has a package.json.

### Expected Behavior

When running a `release publish` and my libs contain a `package.json` but no `.npmrc` (as it is in the root of the repo) it should use the roots' `.npmrc` file for publishing

### GitHub Repo

https://github.com/nrwl/nx-examples

### Steps to Reproduce

Since this involves private settings I sadly can't create a repo that produces this but these are the steps:

1. create empty multi package node repo with NX
1. create publishable library (example name: `@my-test-scope/my-test-lib`)
1. add `.npmrc` to the root with something like (make sure this is not present in your home folder, as that is respected):
    ```
    @my-test-scope:registry=https://npm.pkg.github.com
    //npm.pkg.github.com/:_authToken=${MY_AUTH_TOKEN}
    ``` 
1. run `nx release publish`

You should be confronted with auth issues.

as soon as you add a copy of your `.npmrc` to your lib folder, it will work

### Nx Report

```shell
Node   : 20.10.0
OS     : darwin-arm64
yarn   : 1.22.21

nx                 : 18.0.3
@nx/js             : 18.0.3
@nx/jest           : 18.0.3
@nx/linter         : 18.0.3
@nx/eslint         : 18.0.3
@nx/workspace      : 18.0.3
@nx/devkit         : 18.0.3
@nx/eslint-plugin  : 18.0.3
@nx/node           : 18.0.3
@nrwl/tao          : 18.0.3
typescript         : 5.3.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I've debugged the issue after I found this comment:

https://github.com/nrwl/nx/pull/16652/files#diff-5436947051cc756ff8c6940d47a4d78f54570bbaaa5947ab6c007639d5bdfd17R119-R120

**Comment by zelladays** [comment]
Having the same issue here. Any updates on this?

**Comment by keenanzucker-tipalti** [comment]
Running into the same problems unfortunately as above... 😢

**Comment by ruairidhflint** [comment]
^ Same. Any update much appreciated.

**Comment by AnastasiaGridchina** [comment]
Experiencing the same problem. Hopefully, it will be resolved soon

**Comment by JamesHenry** [comment]
Hi Folks, I believe this is a limitation on the npm side, ultimately `nx release publish` is running `npm publish` behind the scenes, and I don't think it is respecting any kind of inheritance up multiple levels like that.

Please could one of the people on this thread try publishing their setup using `npm publish` directly in on of their project directories to confirm?

**Comment by JamesHenry** [comment]
This is the PR that is addressing this issue: https://github.com/nrwl/nx/pull/22304

**Comment by grumpyoldman-io** [comment]
@JamesHenry Thanks for picking this up. I wouldn't mind adding something like a flag or config to opt in to this behavior, and seeing the comments and solutions mentioned in this thread I think a lot of people have made "worse" workarounds. I do hope that the config will exist on the package level, not the root. Something along the lines of "useNpmrcFromRoot" (terrible naming, but just to make a point) would make it possible to reuse it, if it was possible to extend or compose the root file that would be a cherry on top for me.

**Comment by grumpyoldman-io** [comment]
> why would you put properties in a root config that don’t apply in the majority of circumstances?

My thought process was based on the notion of making this behavior explicit, and opt-in per package so you can cherry pick when to apply this as to my knowledge npmrc has no way of extending / overriding. Your following point though:

> That is how almost all other tools work, always taking the root config into account and then overriding with project level config where necessary.

Makes a lot of sense to me, and if the override per project also allows you to change root settings this would work perfectly for all cases I can come up with. I was just not aware that this would be a possibility for .npmrc. A lot of the other tools in the repo have explicit "extends" or "import base" like syntax though.

**Comment by JamesHenry** [comment]
Yes I agree, I think npm config files are lacking explicit mechanisms for inheritance.

One nuance here is if publishing from dist, the .npmrc at the project level needs to be copied to that location as part of the build step…

There isn’t really much we can do to automate this I don’t think but we can document it in @fahslaj PR

**Comment by grumpyoldman-io** [comment]
AFAIK npm is not very strict about what it contains, just thinking out loud, perhaps introducing a custom setting (either in .npmrc or in nx.json) to do some "just in time" .npmrc creation/removal could potentially work?

To me this _might **just**_ fall within the scope of monorepo tooling, but having a comment in the docs telling people to manually create the .npmrc per package will also do the trick with a whole lot less logic.

**Comment by JamesHenry** [comment]
Ok update on this folks, we are going to have a call with the npm team next week on this to make sure we implement the solution that will work best/most intuitively for you all. 

We still have some open questions about how npm CLI is intended to work in certain scenarios (e.g. it seems that sadly I was wrong about project level .npmrc files being respected if you run the command from the workspace root pointing at the project directory) and this will be our chance to address all of them before closing this issue.

I'll keep you posted!

**Comment by ccreusat** [comment]
Hello guys,

If you are using `pnpm` like me and waiting for a solution between nx/npm , you can only have one `.npmrc` at root level and use `pnpm publish -r` instead of `nx release publish`.

You can still prepare the release but skip publish for now `nx release --skip-publish`

Hope this helps some of you while we wait for this to be resolved!

**Comment by fahslaj** [comment]
Hey everyone! This has been fixed with this PR - https://github.com/nrwl/nx/pull/22304

Now, `nx release` will use the root `.npmrc` when publishing. This includes support for scoped registries and auth within `.npmrc`. If you need to override the registry at the project-level (instead of by npm scope), then you can set the `registry` and `tag` options in project configuration. See this doc for details - https://nx.dev/recipes/nx-release/configure-custom-registries
