### ISSUE TITLE
problem with gitignore

### ISSUE THREAD

**Issue by wendal2841** [nrwl/nx#21816]
### Current Behavior

in new versions of nx there are projects in the apps folder, if you add the folder to git ignore then nx does not see the projects, how to disable this

### Expected Behavior

if you add a folder with projects to gitignore then nx sees the projects

### Steps to Reproduce

1. add apps folder to gitignore
2. run nx lint ****

### Nx Report

```shell
/nx run ****:lint

 >  NX   Cannot find project '****'


Process finished with exit code 1
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
This is intended behavior - for nx to consider a project it cannot be excluded from your git repo. If you want to force this, you could add a negative pattern inside .nxignore to unignore the project.
