### ISSUE TITLE
Change default libs/ apps/ folder layout

### ISSUE THREAD

**Issue by josuerios** [nrwl/nx#2182]
I'm opening this issue as a feature request.

## Expected Behavior

I want the ability to create and maintain a different folder layout. Right now by default, created apps and libs are being hosted inside `apps/` and `libs/` folder respectively. I have a small Nx workspace where I want to keep both types inside a `packages/` folder. Right now I'm creating them with the default behavior, moving them manually and updating the path references where needed and everything works like a charm. I think it will be cool to have this as a built-in feature. I've reviewed the code and identified which changes are needed and willing to make a PR.

**Comment by vsavkin** [comment]
I think we could introduce two variables `apps-root` and `libs-root` (which could both be set to `packages`). We do references `apps` and `libs` in schematics creating apps and libs, but I don't believe we hardcode those in many other places. 

If you want to submit a PR, we will help you.

**Comment by Lonli-Lokli** [comment]
I think its a great idea for angular apps, CLI supports any folder location, personally I prefer to have libs for shared functionality (like it's Angular common) and modules or packages per each microfrontend, to distinguish lib and module.

**Comment by bekos** [comment]
This is already supported in `nx.json` by using for example:
```
"workspaceLayout": {
  "appsDir": "projects",
  "libsDir": "packages"
}
```

**Comment by Bulletninja** [comment]
is it possible to use an array for appsDir?

i'd love to do something like
```
"workspaceLayout": {
  "appsDir": ["core-use-case1/clients/**", "core-use-case2/clients/**"], 
  "libsDir": "utils"
}
```
