### ISSUE TITLE
Writing custom Task runner using esm modules and/or typescript.

### ISSUE THREAD

**Issue by khludenevav** [nrwl/nx#21834]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
I'm using custom tasks runner in order to customize cache. And it works fine, but I see 2 issues
1) it only supports cjs modules. Because uses `require` import.
<img width="399" alt="image" src="https://github.com/nrwl/nx/assets/41898629/133a9137-c86d-4a3f-a26a-16505299f220">

2) I don't want to publish my plugin for my perspective it should be local. Could Nx support executor written on TS?

How I currently reference plugin in nx.json
```
"tasksRunnerOptions": {
    "default": {
      "runner": "./libs/nx-task-runner",
      "options": {
        "captureStderr": true
      }
    }
  },
```
libs/nx-task-runner/package.json content:
```
...
  "main": "lib/index.js",
...
```

## Motivation
Publishing task runner package is additional step and slows down the process of making any changes in it.

## Suggested Implementation
Probably somehow using ts-node will help to launch code from ts package.

## Alternate Implementations
¯\\_(ツ)_/¯

**Comment by AgentEnder** [comment]
ESM support for plugins is tracked here: #15682, no ETA on that. We could look into typescript for the tasks runner though, could be interesting.

**Comment by work933k** [comment]
Temporary solution, add a script to your package.json to compile it from TS to JS and commit:
```
"scripts": {
    "build:custom-runner": "tsc tools/task-runners/custom-runner/index.ts",
```

**Comment by cainrus** [comment]
@khludenevav you can register runtime ts transpiler(ts-node or swc) via index.js like

```
require('ts-node').register({ /* options */ });

module.exports = require('./src/index.ts');
```

**Comment by AgentEnder** [comment]
Given custom tasks runners are deprecated and slated for removal I'm going to close this out. The other linked issue will continue to track general esm support for other plugin facets
