### ISSUE TITLE
Feature request: generate @nrwl/react:lib without stylesheets

### ISSUE THREAD

**Issue by elliottsj** [nrwl/nx#2184]
## Expected Behavior

Able to `nx g @nrwl/react:lib <name>` without selecting a stylesheet option.

## Current Behavior

Currently, the [`style` option is required](https://github.com/nrwl/nx/blob/88920ac381f25d76b0b2dda244084536337db590/packages/react/src/schematics/library/schema.json#L31).

### Context

Often React libraries do not need to use styles, for example a library exporting a collection of Hooks.

```
@nrwl/workspace@8.9.0
@nrwl/react@8.9.0
```

**Comment by FrozenPandaz** [comment]
This is a good point. Not all react libraries need to be a component.

1. We can add an option: `component`. This can be passed as `--no-component` which should not generate a component code
2. The `style` option (for both `lib` and `component`) can have a `none` option which will not generate styles in the component (if `--no-component is NOT passed) and set the default for the library to generate components without styles by default.

**Comment by jaysoo** [comment]
I'll add this to the next round of features.
