### ISSUE TITLE
Problem with release option `"createRelease": "github"`

### ISSUE THREAD

**Issue by NeekoDev** [nrwl/nx#21845]
### Current Behavior

The command `npx nx release --skip-publish` throw an NX error : `A GitHub API Error occurred when creating/updating the release` when I use `"createRelease": "github"` in `nx.json

The `nx.json` : 

```json
{
    "extends": "nx/presets/npm.json",
    "$schema": "./node_modules/nx/schemas/nx-schema.json",
    "affected": {
        "defaultBase": "master"
    },
    "release": {
        "projects": [
            "packages/*"
        ],
        "git": {
            "commitMessage": "chore(release): v{version}",
            "commit": true,
            "tag": true
        },
        "changelog": {
            "projectChangelogs": {
                "file": false,
                "createRelease": "github"
            }
        }
    }
}
```

### Expected Behavior

When I execute `npx nx release --skip-publish`, I want to create Github Tag (as it is done without worries when I don't use `"createRelease": "github"`) and Github Release of the tag.

### Nx Report

```shell
Node   : 18.18.2
   OS     : win32-x64
   pnpm   : 8.15.1
   
   nx             : 18.0.4
   @nx/js         : 18.0.4
   @nx/workspace  : 18.0.4
   @nx/devkit     : 18.0.4
   @nrwl/tao      : 18.0.4
   typescript     : 5.3.3
```

### Failure Logs

```shell
>  NX   A GitHub API Error occurred when creating/updating the release

   GitHub Error: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/releases/releases#create-a-release"}
   ---
   Request Data:
   Repo: NeekoDev/nx-pkg-ci
   Token: null
   Body: {"tag_name":"v0.1.2","name":"v0.1.2","body":"## 0.1.2 (2024-02-16)\n\nThis was a version bump only for @neekodev/pkg-core to align it with other projects, there were no code changes.","prerelease":false}
```

### Package Manager Version

pnpm 8.15.1

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by JamesHenry** [comment]
@NeekoDev are you setting a GITHUB_TOKEN or GH_TOKEN environment variable? As you can see in the output the token is currently coming through as null so it suggests that you do not have one of those environment variables populated

**Comment by cskiwi** [comment]
> @NeekoDev are you setting a GITHUB_TOKEN or GH_TOKEN environment variable? As you can see in the output the token is currently coming through as null so it suggests that you do not have one of those environment variables populated

Yep adding that to the tasks env values did it for me, might be useful for in the docs ;)

**Comment by recallwei** [comment]
I think this should be added into documentation.

<img width="1919" alt="image" src="https://github.com/nrwl/nx/assets/62941121/33ffee55-9d89-4ce9-9907-5d95b5d1032f">

After add `GITHUB_TOKEN` to `.env.local`, it works.
