### ISSUE TITLE
Add `assets` param to vite executor options

### ISSUE THREAD

**Issue by nguyentvan7** [nrwl/nx#21856]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Similar to `webpack` build executor (https://nx.dev/nx-api/webpack/executors/webpack#assets), it would be nice for the `vite` build executor (https://nx.dev/nx-api/vite/executors/build) to contain an `assets` property in the options that would statically copy files from libraries to our build/dev server for us.

## Motivation

This would help those transitioning from `webpack` to `vite` seamlessly, and also unifies the behavior across the 2 executors. As of now, those who need static asset copying will have to use a vite plugin, such as https://www.npmjs.com/package/vite-plugin-static-copy

## Suggested Implementation

Same as `webpack`, add an `assets` param that will do the static copying for us

**Comment by AgentEnder** [comment]
We are moving to support tools by limiting the work performed by our executors. In this case, I'd recommend using a vite plugin to handle the static assets copy.
