### ISSUE TITLE
Add native module support for loong64

### ISSUE THREAD

**Issue by wxpppp** [nrwl/nx#21860]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

When I depend on nx on the loongarch linux platform, I encountered the error "Error: Unsupported architecture on Linux: loong64", I want to know if the @nx/nx-linux-loong64-gnu module is supported or how to build the executable file "nx.linux-loong64-gnu.node".
## Motivation

The LoongArch architecture (LoongArch) is an Instruction Set Architecture (ISA) that has a RISC style.
More and more people are starting to deploy services on LoongArch and use it as a production environment, and the basic software also mostly supports the LoongArch architecture.

**Comment by yzewei** [comment]
Looking forward to the addition of a new architecture. @tmc

**Comment by FrozenPandaz** [comment]
Loong64 and other architectures we currently do not have native binaries will be supported when we ship a WASM distribution https://github.com/nrwl/nx/pull/22870.
