### ISSUE TITLE
Incorrect NX Version in doc

### ISSUE THREAD

**Issue by shrezaaa** [nrwl/nx#21867]
I would like to extend my gratitude for creating such a powerful library. I have been using it for my project, and it has been very helpful. 

However, I have a concern regarding the compatibility of the library with Angular. According to the documentation, version 18.1.0 is compatible with Angular 17.2, but I could not find this version on the npmjs site. The latest version available on the site is v18.0.4. I would appreciate it if you could provide more information about the availability of version 18.1.0. When can we expect it to be officially released? 

I believe many users like me would benefit from an official announcement regarding the availability of the latest version. Any information you can provide would be much appreciated.

Thank you for your time and assistance.

[https://nx.dev/nx-api/angular/documents/angular-nx-version-matrix](url)
[https://www.npmjs.com/package/nx?activeTab=versions](url)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

The 18.1.0 is indeed not released just yet, but it should be released soon. That's the version that will contain the support for Angular 17.2.0 as indicated in the linked docs. It was a mistake to publish it before the version was released. You can keep an eye on the [Releases page](https://github.com/nrwl/nx/releases) to know when it's published.

**Comment by FrozenPandaz** [comment]
Nx `18.1.0` has been released and the [page](https://nx.dev/nx-api/angular/documents/angular-nx-version-matrix#nx-and-angular-version-compatibility-matrix) is correct now.
