### ISSUE TITLE
Nx 18: create-nx-workspace for Nextjs doesn't install @nx/react 

### ISSUE THREAD

**Issue by Balance8** [nrwl/nx#21877]
### Current Behavior

✔ Which stack do you want to use? · react
✔ What framework would you like to use? · nextjs
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · nx-kira
✔ Would you like to use the App Router (recommended)? · Yes
✔ Would you like to use the src/ directory? · No
✔ Test runner to use for end to end (E2E) tests · playwright
✔ Default stylesheet format · CSS

Installs nextjs

### Expected Behavior

✔ Which stack do you want to use? · react
✔ What framework would you like to use? · nextjs
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · nx-kira
✔ Would you like to use the App Router (recommended)? · Yes
✔ Would you like to use the src/ directory? · No
✔ Test runner to use for end to end (E2E) tests · playwright
✔ Default stylesheet format · CSS

installs next js + nx/react

### Steps to Reproduce

1. npx create-nx-workspace@latest --pm pnpm
2. pick nextjs

### Nx Report

```shell
Node   : 16.18.0
   OS     : darwin-arm64
   pnpm   : 8.15.1
   
   nx (global)        : 17.2.8
   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/jest           : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/workspace      : 18.0.4
   @nx/devkit         : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nx/next           : 18.0.4
   @nx/playwright     : 18.0.4
   @nx/react          : 18.0.4
   @nrwl/tao          : 17.2.8
   typescript         : 5.3.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Hey! I am closing this as it is working as expected. If you need functionality from `@nx/react` you can install it manually.
