### ISSUE TITLE
[NX:18.0.4] Package error occurred when execute "nx run" script

### ISSUE THREAD

**Issue by ChoSeoHwan** [nrwl/nx#21878]
### Current Behavior

Below error occurred when execute "nx run" script.

```shell
Error: Your application tried to access chalk, but it isn\'t declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: chalk
Required by: C:\Projects\NX-BUG~1\YARN~1\UNPLUG~1\NX-VIR~2\NODE_M~1\nx\src\utils\

Require stack:
- C:\Projects\NX-BUG~1\YARN~1\UNPLUG~1\NX-VIR~2\NODE_M~1\nx\src\utils\logger.js
- C:\Projects\NX-BUG~1\YARN~1\UNPLUG~1\NX-VIR~2\NODE_M~1\nx\src\utils\params.js
- C:\Projects\NX-BUG~1\YARN~1\UNPLUG~1\NX-VIR~2\NODE_M~1\nx\src\command-line\run\run.js
# ...
```

### Expected Behavior

run executor normally

### GitHub Repo

https://github.com/ChoSeoHwan/nx-bug-report-0

### Steps to Reproduce

1. clone reproduce project

`git clone https://github.com/ChoSeoHwan/nx-bug-report-0.git`

2. preparation step

`yarn install`

3. reproduce error case

`yarn nx run reproduce:build`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.11.0
   OS     : win32-x64
   yarn   : 4.1.0

   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   typescript         : 5.3.3
```

### Package Manager Version

yarn 4.1.0

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

- node : 20.11.0
- nx : 18.0.4
- yarn : 4.1.0

**Comment by meeroslav** [comment]
Sadly, I could not reproduce this. Running the install works just fine and the build does not require `chalk`. Can you try to remove clone it on a fresh folder and try again?

Try cleaning up your local yarn cache, as it might be corrupted.

**Comment by necm1** [comment]
I'm facing the same issue using.

```bash
> nx run api:serve:development

(node:55464) [MODULE_NOT_FOUND] Error: Your application tried to access express, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
(Use `node --trace-warnings ...` to show where the warning was created)
^C%
```

Happened after migrating from yarn classic to yarn 4 using pnp.

**Comment by meeroslav** [comment]
@necm1 despite the similarities, you have a completely different issue. It seems that `express` that is needed by your serve is not explicitly accessible to `api`. This happens when either `express` is missing in the root package.json or the generated `package.json` for your app is missing it.

Please open a new issue and provide also the following information:
- your root package.json dependencies
- the generated package.json from your `dist/apps/api` after running `nx build api`
