### ISSUE TITLE
Static Module Federation skipRemotes option is not working

### ISSUE THREAD

**Issue by ArgV04** [nrwl/nx#21880]
### Current Behavior

I have created one shell and several static remotes.

In the shell all remotes are added in the remotes config section. But when I want to start the shell by skipping some remotes I get error where he is still trying to load the skipped remotes 

**remoteEntry.mjs** --> **_remoteEntry.mjs net::ERR_CONNECTION_REFUSED_** 

**_nx serve host --skipRemotes=remote-one_**

While serving flow gets started I see log messages about skipping remotes but not able to run my app regarding the error above.

On dynamic federation this is working but not for static configured remotes. Any explanations or solutions? Thanks in advance 🙂

<img width="638" alt="image" src="https://github.com/nrwl/nx/assets/30262768/07a5a881-6bd2-428c-84fc-e1e1b2b54916">

### Expected Behavior

Skipped remotes should be fully considered.

### Steps to Reproduce

Followed current Nx static module federation article/documentation

### Nx Report

```shell
Node   : 18.18.2
   OS     : darwin-arm64
   npm    : 9.8.1
   
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/angular        : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   typescript         : 5.2.2
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Hi @ArgV04 !

You've misunderstood the intention of `skipRemotes`. Perhaps we need better documentation clarifying the usage of this option.
https://nx.dev/ci/features/split-e2e-tasks

The only thing that `skipRemotes` does is to prevent the named remotes provided to that option from being `served` automatically.

It does not remove them from the `remotes:[]` definition in the app's `module-federation.config.js` file.

This is useful for when you have a remote that does not live in the same repo as the `host` application.

**Comment by ArgV04** [comment]
So there is no way to skip serving remotes in same repo while serving shell?
