### ISSUE TITLE
bug: @nrwl/react - missing @babel/preset-react and react when running build on react publishable library

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#2188]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

`nx build ui-button` should build react library

## Current Behavior

Build fails. 

![image](https://user-images.githubusercontent.com/1223799/70813841-79a9ec80-1dca-11ea-8576-adfa536cf162.png)

when I explicitly install `yarn add -D @babel/preset-react`. Build starts working.

Although it will still fail because of missing `react`

![image](https://user-images.githubusercontent.com/1223799/70813923-a6f69a80-1dca-11ea-9af8-5372c9430fb8.png)

On needs to manually install dependencies:

```
yarn add react react-dom @types/react @types/react-dom
```

After these manual steps build will work.

I expected that those dependencies would be added when running `react:lib` for first time (at least the `@babel/react-preset`

## Failure Information (for bugs)

- see above

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. npx create-nx-workspace@latest my-workspace
2. choose empty workspace
3. yarn add -D @nrwl/react
4. yarn nx g @nrwl/react:lib ui-button --publishable

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context

Please provide any relevant information about your setup:

- version of Nx used:
```
  @nrwl/angular : Not Found
  @nrwl/cli : 8.9.0
  @nrwl/cypress : 8.9.0
  @nrwl/eslint-plugin-nx : 8.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 8.9.0
  @nrwl/linter : 8.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 8.9.0
  @nrwl/react : 8.9.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.9.0
  @nrwl/web : 8.9.0
  @nrwl/workspace : 8.9.0
  typescript : 3.5.3
```
- 3rd-party libraries and their versions
- and most importantly - a use-case that fails

**A minimal reproduction scenario allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by jaysoo** [comment]
The issue is that the lib schematic never added the react dependencies, only the app schematic does that. We should do that into both for consistency.

**Comment by Hotell** [comment]
Sounds good. 👌
