### ISSUE TITLE
node: support  creating libraries and publishable libraries

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#2189]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

To officially support `@nx g @nrwl/node:lib my-node-utils --publishable`

We can already generate node library via schematic, although it's not documented (inherited from `@nrwl/workspace` I assume):

![image](https://user-images.githubusercontent.com/1223799/70816986-e1633600-1dd0-11ea-86ef-a3920b1de5b6.png)
![image](https://user-images.githubusercontent.com/1223799/70816940-ca244880-1dd0-11ea-8940-11fc40c54932.png)

## Current Behavior

Currently I can generate node library via `@nx g @nrwl/node:lib my-node-utils`,
which is missing `build` builder. I can add it on my own ofc, but it would be much better to add `--publishable` functionality.

- version of Nx used (_Please run `nx report` at the root of your workspace and copy the results here if you are using Nx 8.6.1 or greater_): `8.9.0`
- 3rd-party libraries and their versions
- and most importantly - a use-case that fails

**Comment by tommck** [comment]
We should be able to build pure script publishable libraries too.. should be in the "@nrwl/workspace" library schematics too
