### ISSUE TITLE
`nx release` support for per-project registry configuration

### ISSUE THREAD

**Issue by jaknas** [nrwl/nx#21907]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Lerna currently supports per-project publish configuration using `publishConfig`. I'm using it to change registry for some of the monorepo packages. 

As far as I know, registry is right now only possible to be specified per monorepo, and the project-level configuration is ignored.

## Motivation

It should help to migrate projects off Lerna to use `nx release`, and in general support for this kind of configuration would be welcome.

## Suggested Implementation

Support `publishConfig` key in `package.json` or `project.json`

## Alternate Implementations

Documentation how to achieve it with programatic API

**Comment by JamesHenry** [comment]
Hi @jaknas, I'm sorry for the delay in you receiving a response on this one.

Work was done last month to solidify how we execute publishing and respect all the various configuration options of npm.

This PR https://github.com/nrwl/nx/pull/22304 shows that `publishConfig` will be respected when present so I'm going to close this one.
