### ISSUE TITLE
CLM Vulnerability for ejs package in @nx/webpack, @nx/jest and @nx/lint coming through @nx/devkit

### ISSUE THREAD

**Issue by Kathuria** [nrwl/nx#21910]
### Current Behavior

While using nx for setting up webpack, jest and lint - it installs packages @nx/webpack, @nx/jest and @nx/lint. As we build this in pipeline, these packages giving CLM Vulnerability for packages indirectly dependent on "ejs". As per the scan, ejs should be removed.

### Expected Behavior

Expecting nx packages to be ejs independent. Currently mentioned packages depends upon @nx/devkit which further having dependency on ejs.
Solution can be removing ejs all together by removing as external dependency or replacing with alternative package.

### Steps to Reproduce

1. Install the packages required for webpack, jest or lint.
2. Scan the packages for vulnerability

### Nx Report

```shell
NA
```

### Package Manager Version

18.0.4

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
EJS is used when running generators, and is not a valid avenue of attack for this type of vulnerability. You can safely mark it as not relevant. No EJS code makes it into any code being published from an Nx repo.
