### ISSUE TITLE
[@nx/webpack] Use recent source-map-loader without deprecated `abab` dependency

### ISSUE THREAD

**Issue by swcm-mnestler** [nrwl/nx#21933]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
`@nx/webpack` 18.x currently depends on `"source-map-loader": "^3.0.0"` which in turn brings in the deprecated `abab` package.
The breaking changes `4.0.0` and `5.0.0` of `source-map-loader` only dropped support for Node versions < 14.15 and < 18.12, respectively. Replacing these should therefore be straightforward.

## Motivation
The `abab` package is deprecated:
```
npm WARN deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
```
Bumping the dependency would resolve this warning.

## Suggested Implementation
Use `source-map-loader` `^5.0.0`.

## Alternate Implementations
Use `source-map-loader` `^4.0.0` if support for older node versions is still required.

**Comment by danazkari** [comment]
This warning is actually breaking a use case:

<img width="735" alt="image" src="https://github.com/nrwl/nx/assets/349542/91aa1b9f-5686-4640-b437-464e55402d02">

<img width="558" alt="image" src="https://github.com/nrwl/nx/assets/349542/e9cbb1be-3909-4150-954f-13a03ef2ab9e">

That's as far as it goes when trying to create an app with `next` as the preset. Would the fix be as suggested by @swcm-mnestler?

**Comment by Coly010** [comment]
@danazkari I note you're using `Node 16.17.1`.

The fix suggested by @swcm-mnestler would not fix your issue.
You need to update to Node 18 or Node 20.

**Comment by danazkari** [comment]
> @danazkari I note you're using `Node 16.17.1`.
> 
> The fix suggested by @swcm-mnestler would not fix your issue.
> You need to update to Node 18 or Node 20.

Initially since for a project at my job we're stuck there... But I've tested it already with the newest versions and the issues persist.

I've even gone as far as setting up a nix flake just to have the cleanest nodejs and run the same experiment and still get the same results.

**Comment by danazkari** [comment]
> @danazkari I note you're using `Node 16.17.1`.
> 
> The fix suggested by @swcm-mnestler would not fix your issue.
> You need to update to Node 18 or Node 20.

Here's the issue I've opened about this

https://github.com/nrwl/nx/issues/22760
