### ISSUE TITLE
Nx18 is garbage, it's too difficult to use

### ISSUE THREAD

**Issue by aosnow** [nrwl/nx#21944]
### Current Behavior

Nx18 is garbage, it's too difficult to use

### Expected Behavior

Restore to the old recommended configuration

### Steps to Reproduce

1. Nx18 is garbage, it's too difficult to use

### Nx Report

```shell
Nx18 is garbage, it's too difficult to use
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Hi there 😊 

Thanks for the issue. I'm going to close this out as there's not anything constructive present.

Feel free to open a new, less heated, issue that contains specific changes you'd like to see in a more constructive manner.

As a reminder, we are all people working hard on making Nx the best it can possibly be, and deserve the same respect you would treat any other colleague with.
