### ISSUE TITLE
Environment variables are not loaded into EXPO

### ISSUE THREAD

**Issue by DDuunk** [nrwl/nx#21942]
### Current Behavior

Environment variables from the `.env` file in `src/apps/app` are not loaded into EXPO

### Expected Behavior

Environment variables from the `.env` file in `src/apps/app` are loaded into EXPO

### GitHub Repo

https://github.com/DDuunk/expo-test

### Steps to Reproduce

1. Run `nx run app:run-ios`
2. You'll not see the environment variables being logged in your terminal

### Nx Report

```shell
Node   : 18.18.0
   OS     : darwin-arm64
   npm    : 9.8.1

   nx (global)        : 17.2.8
   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/jest           : 18.0.4
   @nx/linter         : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/workspace      : 18.0.4
   @nx/detox          : 18.0.4
   @nx/devkit         : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nx/expo           : 18.0.4
   @nx/react          : 18.0.4
   @nrwl/tao          : 18.0.4
   @nx/web            : 18.0.4
   @nx/webpack        : 18.0.4
   typescript         : 5.3.3
```

### Package Manager Version

npm 10.2.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The answer provided here https://github.com/nrwl/nx-labs/issues/116#issuecomment-1298852766 does offer a solution

**Comment by xiongemi** [comment]
it does load. i think it is doing something strange with stringify.

change the line to `console.log('process.env', process.env);` and you should be able to see your env variables.

**Comment by DDuunk** [comment]
@xiongemi I just changed the line as suggested and my output results in:

```
LOG  process.env {"NODE_ENV": "development"}
``` 

None of the environment variables defined in `apps/app/.env` showed up.

**Comment by xiongemi** [comment]
@DDuunk
my mistake. it only shows the complete the env in web view. run `nx start <your app> --web` and you will see complete env.
![Screenshot 2024-02-23 at 6 04 53 PM](https://github.com/nrwl/nx/assets/16211801/a6f7c664-6e5f-4b2a-89ed-91b123b8507e)

however, for ios, you can log it directly: `console.log('process.env', process.env['EXPO_PUBLIC_MY_CUSTOM_VARIABLE']);`. it will show the value. 
<img width="480" alt="Screenshot 2024-02-23 at 6 06 00 PM" src="https://github.com/nrwl/nx/assets/16211801/8301d925-5877-496d-bc91-1d4aab105666">

by logging process.env does not show all the env variables.

**Comment by DDuunk** [comment]
Check, by using `EXPO_PUBLIC_` prefixed variables I got the result I wanted. Weird that process.env does not show all variables en non prefixed variables don't show up at all.
