### ISSUE TITLE
webpack WriteIndexHtmlPlugin does not respect inject: false

### ISSUE THREAD

**Issue by Janim007** [nrwl/nx#21949]
### Current Behavior

nx@17.2.8
in project.json i have: 
```json
{
  "target": 
   "build": {
     "options": {
         "styles": [{ "input": "...", "bundleName": "...", "inject": false}, ..]
   }
 }
}
```
However, when I build the project, the generated HTML includes the CSS files mentioned in the styles field above, even though inject was set to `false`.

### Expected Behavior

The expected behavior is for the HTML page not to include the styles marked with `inject: false`, leaving it up to the developer to inject them as necessary.

### Steps to Reproduce

1. create style sheets
2. add `input` `bundleName` and `inject:false` in project.json under build options.
3. build the app
4. check the generated html file (it should not include the style files that marked as `injected:false`

### Nx Report

```shell
Node   : 18.19.1
   OS     : darwin-arm64
   yarn   : 3.2.3
   
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/express        : 17.2.8
   @nx/node           : 17.2.8
   @nx/playwright     : 18.0.4
   @nx/react          : 17.2.8
   @nx/rollup         : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   nx-cloud           : 18.0.0
   typescript         : 4.9.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Hi! Could you please provide a repo with a minimal reproduction so that I can investigate this further?

**Comment by Coly010** [comment]
Closed by: https://github.com/nrwl/nx/pull/23444
