### ISSUE TITLE
Running a nx:run-commands task configuration using shorthand notation causes infinite loop

### ISSUE THREAD

**Issue by dschnare** [nrwl/nx#21958]
### Current Behavior

Running some tasks with a configuration using the shorthand notation `nx run project:task:configname` causes an infinite loop like.

```
nx run project:task:configname
nx run project:"task:configname"
nx run project:task:configname
nx run project:"task:configname"
...
```

However, when using the longhand notation `nx run project:task --configuration configname` the task's configuration only runs once.

```
nx run project:task:configname
```

Some remedies we've found...
1. Just rename the configuration from "staging" to "staging2" (not suitable however)
2. Use the longhand notation to execute a tasks' configuration; npx nx run project:task --configuration configname
3. Randomly the shorthand notation won't go into a loop, most times it does

### Expected Behavior

The shorthand or longhand notation used to run a tasks' configuration should only run the task once.

### Steps to Reproduce

1. Create a simple project with a task that uses the nx:run-commands executor
2. Add two configurations for the task; "beta" and "staging"
3. Run the configuration using both the shorthand and longhand notations
4. Watch the loop occur randomly.

Example
```json
{
  "name": "my-proj",
  "projectType": "application",
  "root": "packages/my-proj",
  "sourceRoot": "packages/my-proj/src",
  "targets": {
    "deploy": {
      "executor": "nx:run-commands",
      "options": {
        "cwd": "packages/my-proj",
        "commands": ["CI=true ./scripts/deploy --env=alpha"]
      },
      "configurations": {
        "beta": {
          "commands": ["CI=true ./scripts/deploy --env=beta"]
        },
        "staging": {
          "commands": ["CI=true ./scripts/deploy --env=staging"]
        }
      }
    }
  }
}
```

### Nx Report

```shell
Node   : 18.19.0
   OS     : darwin-arm64
   npm    : 9.6.7
   
   nx          : 17.2.8
   @nrwl/tao   : 17.2.8
   typescript  : 5.3.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
I was unable to reproduce this with the project.json you supplied, only changing the contents of the commands. Can you provide the contents of ./scripts/deploy? If you change the command does it solve your problem?

**Comment by dschnare** [comment]
I tried commenting out the entire script file contents so it’s just a no op and it still occurs.

I can repro locally as well as just using the command “echo hi”.

I’ve recently updated to Nx 17.2.8 from 16.x.

**Comment by AgentEnder** [comment]
Interesting. When I try to repro it I don't see the behavior. Can you post a reproduction on github for me to check?

**Comment by dschnare** [comment]
Hey @AgentEnder we discovered the issue. Man do we feel dumb. Our current setup we have package.json files and project.json files for each of our local standalone packages. We had a recent change that removed the `"nx": { "includedScripts": [] }` from our package.json files. So we had a clash of task names.

Our package.json file had script like "deploy:staging" and then we had targets in our project.json file like "deploy" with a configuration "staging". So adding `"nx": { "includedScripts": [] }` to our package.json file resolved our issue.
