### ISSUE TITLE
Next.js just sits there and says "compiling" but never finished, new next app - no changes

### ISSUE THREAD

**Issue by iangregsondev** [nrwl/nx#2196]
- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

To be able to use npm run start and the applications launches and works.

## Current Behavior

After doing the following

```
 npx --ignore-existing create-nx-workspace next-test2
```

all files are created but running the npm run start fails... it just sits there saying "compiling"

See here, shows exactly whats going on.

![image](https://user-images.githubusercontent.com/2370364/70850243-81c86180-1e88-11ea-813c-77353cd60b8a.png)

Absolutely no changes made, just run the create-nx-workspace . and npn runs tart ...

I am using Node v12.0.0

**Comment by AryanJ-NYC** [comment]
Two lines down it reads `[ ready ] compiled successfully`. That is the next server.

Upon running this, do you have a Next.js app running at `http://localhost:4200`?

**Comment by asherccohen** [comment]
Check your scss for image import with url...the compiler silently fails without warnings. It happened to me and took me weeks to figure out.

**Comment by iangregsondev** [comment]
Sorry my bad, its working now. I didn't notice any output stating it was listening on port 4200 like other nx apps.

**Comment by elliottsj** [comment]
This will be addressed in https://github.com/nrwl/nx/pull/2173/files#diff-3ae94fa96db6d0580a313332735007e9R49

**Comment by asherccohen** [comment]
Ok, if anyone gets stuck here, I have another scenario that can lead to this problem.
Next.js does not import images (or urls in css) out-of-the-box. It requires a specific plugin next/images and configuration in next.config.js.

Just look up docs for this.
