### ISSUE TITLE
Can't initialize routing in Angular app using preset

### ISSUE THREAD

**Issue by tommck** [nrwl/nx#2197]
I ran these 2 commands:
1) `npx create-nx-workspace@latest` and chose Angular and Scss..
2) `ng generate @nrwl/angular:library lazy-lib --lazy --parentModule=apps/nx-app/src/app/app.module.ts --routing --style=scss --tags=views`

I received no errors about routing, but no lazy/routing stuff was set up.
The angular app that was created does not have routing at all, so I would expect an error

## Expected Behavior

Minimally, I would expect an error to be reported that the routing/lazy flags cannot be honored.
Optimally, I would like it to add routing configuration (or be given a way to do that with the schematics in create-nx-workspace)

## Current Behavior

It silently fails and I don't have lazy loading or routing set up

**Comment by brandonroberts** [comment]
Currently the presets do not include routing. As an alternative run:

```
npx create-nx-workspace@latest --preset=empty // Choose the Angular CLI
ng add @nrwl/angular
ng g nx-app // Choose routing when prompted
ng generate @nrwl/angular:library lazy-lib --lazy --parentModule=apps/nx-app/src/app/app.module.ts --routing --style=scss --tags=views
```

We can look at adding a warning to the generate command for a library if the routing configuration is not found.

**Comment by tommck** [comment]
Yeah, I figured out a way to get around it once I figured out that there was a problem, but it was unexpected for it to silently fail

**Comment by tommck** [comment]
I would argue that silent failure is a **bug**, though

**Comment by leon** [comment]
@tommck what was your solution?, i'm struggling with the same thing.

**Comment by brandonroberts** [comment]
Just to follow-up here, I'm working on an feature to add interactive mode to `create-nx-workspace`, so if you use `--interactive=true` it will show you the prompts from the underlying schematics.

https://github.com/nrwl/nx/pull/2258

**Comment by tommck** [comment]
@leon In my app, it was demo code I was newly creating, so I just recreated the app with routing in it.

But, in another app, I just manually added the routing lines myself (it's pretty much a one-liner)

**Comment by vsavkin** [comment]
Fixed here: https://github.com/nrwl/nx/pull/2258

It's going to be release in 8.12 next week. Simply pass `--interactive=true` when creating a workspace and you will be able to select all the options.

Thank you!
