### ISSUE TITLE
NX 18.0.4 - React application generation doesn't generate any targets in project.json

### ISSUE THREAD

**Issue by tibiiorcdw** [nrwl/nx#21971]
### Current Behavior

When generating a new React application with NX 18.0.4 the resulting app doesn't have any targets in the project.json file.

### Expected Behavior

Targets are populated in project.json for React application.

### Steps to Reproduce

The following command was used to generate a new React application:

nx g @nx/react:application --directory=apps/demo2 --style=css

>  NX  Generating @nx/react:application

√ What name would you like to use for the application? · demo2
√ Would you like to add React Router to this application? (y/N) · true
√ Which E2E test runner would you like to use? · cypress
√ What should be the project name and where should it be generated? · demo2 @ apps/demo2
CREATE apps/demo2/src/app/app.spec.tsx
CREATE apps/demo2/src/assets/.gitkeep
CREATE apps/demo2/src/favicon.ico
CREATE apps/demo2/src/index.html
CREATE apps/demo2/src/main.tsx
CREATE apps/demo2/tsconfig.app.json
CREATE apps/demo2/webpack.config.js
CREATE apps/demo2/.babelrc
CREATE apps/demo2/src/app/nx-welcome.tsx
CREATE apps/demo2/src/app/app.module.css
CREATE apps/demo2/src/app/app.tsx
CREATE apps/demo2/src/styles.css
CREATE apps/demo2/tsconfig.json
CREATE apps/demo2/project.json
CREATE apps/demo2/.eslintrc.json
CREATE apps/demo2-e2e/project.json
CREATE apps/demo2-e2e/src/e2e/app.cy.ts
CREATE apps/demo2-e2e/src/support/app.po.ts
CREATE apps/demo2-e2e/src/support/e2e.ts
CREATE apps/demo2-e2e/src/fixtures/example.json
CREATE apps/demo2-e2e/src/support/commands.ts
CREATE apps/demo2-e2e/cypress.config.ts
CREATE apps/demo2-e2e/tsconfig.json
CREATE apps/demo2-e2e/.eslintrc.json
CREATE apps/demo2/jest.config.ts
CREATE apps/demo2/tsconfig.spec.json
UPDATE package.json

added 3 packages, and audited 1371 packages in 12s

247 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

 >  NX   👀 View Details of demo2

   Run "nx show project demo2 --web" to view details about this project.

The project.json looks like this:

{
  "name": "demo2",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/demo2/src",
  "projectType": "application",
  "targets": {},
  "tags": []
}

### Nx Report

```shell
Node   : 18.13.0
   OS     : win32-x64
   npm    : 8.19.3

   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/jest           : 18.0.4
   @nx/linter         : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/workspace      : 18.0.4
   @nx/cypress        : 18.0.4
   @nx/devkit         : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nx/react          : 18.0.4
   @nrwl/tao          : 18.0.4
   @nx/web            : 18.0.4
   @nx/webpack        : 18.0.4
   typescript         : 5.3.3
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

If this is by design, can we still have the targets generated?

**Comment by mandarini** [comment]
Hi there @tibiiorcdw ! This is indeed the expected behaviour, you can read our docs here about Inferred Tasks: https://nx.dev/concepts/inferred-tasks

If you want targets to be created, you can use the `NX_ADD_PLUGINS=false` env variable, but for new workspaces this is not the recommended way.

Please let us know if you have any questions!

**Comment by tibiiorcdw** [comment]
We current heavily customize the build and serve tasks in project.json. While I read the inferred tasks link, I am not sure how I would migrate that to this new model. If you have any documentation or examples of how this could be done it would be very beneficial.
