### ISSUE TITLE
@nrwl/storybook generates e2e tests in `apps/` folder instead of `libs/`

### ISSUE THREAD

**Issue by InSuperposition** [nrwl/nx#2198]
## Expected Behavior

When adding `storybook` along with the option to configure `cypress` e2e tests, `nx g @nrwl/react:library:storybook-configuration my-lib` generates e2e tests under the `apps` folder

## Current Behavior

Since my-libs is a library`nx g @nrwl/react:library:storybook-configuration my-lib` generates e2e tests under the `libs` folder

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `npx create-nx-workspace@latest`
2. `nx generate @nrwl/react:library my-lib`
3. `nx g @nrwl/react:library:storybook-configuration my-lib`

### Context

Please provide any relevant information about your setup:

```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : Not Found
  @nrwl/cli : 8.9.0
  @nrwl/cypress : 8.9.0
  @nrwl/eslint-plugin-nx : 8.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 8.9.0
  @nrwl/linter : 8.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 8.9.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.9.0
  @nrwl/web : 8.9.0
  @nrwl/workspace : 8.9.0
  typescript : 3.5.3
```

**A minimal reproduction scenario allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs
Example output for `my-lib` library

```
? Configure a cypress e2e app to run against the storybook instance? Yes
CREATE libs/my-lib/.storybook/tsconfig.json (180 bytes)
CREATE libs/my-lib/.storybook/addons.js (37 bytes)
CREATE libs/my-lib/.storybook/config.js (214 bytes)
CREATE libs/my-lib/.storybook/webpack.config.js (549 bytes)
CREATE apps/my-lib-e2e/tslint.json (42 bytes)
CREATE apps/my-lib-e2e/cypress.json (458 bytes)
CREATE apps/my-lib-e2e/tsconfig.e2e.json (152 bytes)
CREATE apps/my-lib-e2e/tsconfig.json (126 bytes)
CREATE apps/my-lib-e2e/src/fixtures/example.json (80 bytes)
CREATE apps/my-lib-e2e/src/plugins/index.js (811 bytes)
CREATE apps/my-lib-e2e/src/support/commands.ts (1068 bytes)
CREATE apps/my-lib-e2e/src/support/index.ts (599 bytes)
UPDATE package.json (1755 bytes)
UPDATE libs/my-lib/tsconfig.lib.json (248 bytes)
UPDATE workspace.json (5578 bytes)
UPDATE nx.json (378 bytes)
```

## Other

All files are updated wirth `apps/` in path instead of `libs/`

```
UPDATE package.json (1755 bytes)
UPDATE libs/components/tsconfig.lib.json (248 bytes)
UPDATE workspace.json (5578 bytes)
UPDATE nx.json (378 bytes)
```

**Comment by vsavkin** [comment]
In Nx, anything that is executable is an app. Libraries are simply packages of reusable code. Since e2e tests are executable, they are applications and placed in the apps folder. I.e., this is by design.
