### ISSUE TITLE
@nx/cypress, supportfile not correctly set

### ISSUE THREAD

**Issue by Squixx** [nrwl/nx#21992]
### Current Behavior

when running e2e projects on 18.0.5 that dont explicitly include any config other as `nxE2EStorybookPreset(__dirname),`  the project will error with

```
Your project does not contain a default supportFile. We expect a file matching cypress/support/e2e.{js,jsx,ts,tsx} to exist.

If a support file is not necessary for your project, set supportFile to false.

https://on.cypress.io/support-file-missing-or-invalid
```

This was working fine on 18.0.4, so it seem to me there is some error in `nxE2EPreset`

### Expected Behavior

supportfile value correctly set to:

`    const candidate = join(dir, basePath, 'support', f);` 

if the e2e.ts file exists

### Steps to Reproduce

1.

### Nx Report

```shell
nx report

 NX   Report complete - copy this into the issue template

Node   : 20.10.0
OS     : linux-x64
pnpm   : 8.15.4

nx (global)        : 18.0.1
nx                 : 18.0.5
@nx/js             : 18.0.5
@nx/jest           : 18.0.5
@nx/eslint         : 18.0.5
@nx/workspace      : 18.0.5
@nx/angular        : 18.0.5
@nx/cypress        : 18.0.5
@nx/devkit         : 18.0.5
@nx/eslint-plugin  : 18.0.5
@nx/express        : 18.0.5
@nx/node           : 18.0.5
@nx/plugin         : 18.0.5
@nx/rollup         : 18.0.5
@nx/storybook      : 18.0.5
@nx/web            : 18.0.5
@nx/webpack        : 18.0.5
typescript         : 5.3.3
---------------------------------------
Community plugins:
@compodoc/compodoc       : 1.1.23
@ionic/angular           : 7.7.3
@ionic/angular-toolkit   : 11.0.1
@ngrx/effects            : 17.1.1
@ngrx/router-store       : 17.1.1
@ngrx/store              : 17.1.1
@ngrx/store-devtools     : 17.1.1
@nx-dotnet/core          : 2.2.0
@nxext/capacitor         : 17.0.1
@nxext/ionic-angular     : 17.0.1
@storybook/angular       : 7.6.17
angular-auth-oidc-client : 17.0.0
ng-mocks                 : 14.12.1
ng2-charts               : 5.0.4
ngx-toastr               : 18.0.0
---------------------------------------
Local workspace plugins:
         @vf/generators
```

### Failure Logs

```shell
Your project does not contain a default supportFile. We expect a file matching cypress/support/e2e.{js,jsx,ts,tsx} to exist.

If a support file is not necessary for your project, set supportFile to false.

https://on.cypress.io/support-file-missing-or-invalid
```

### Package Manager Version

pnpm@8.15.4

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

It does work correctly when manually set

**Comment by ryandegruyter** [comment]
Same issue here

**Comment by ugrave** [comment]
Seems that the new calulcated supportFile contains now the dir name of the cpyress configuration.
Before it was only `supportFile = '${basePath}/support/e2e.{ts,js}'`. Now it is `${dirname(pathToConfig)}/${basePath}/support/${f}`.

**Comment by ugrave** [comment]
As a workaround i set it explicitly to the right path after setting the nxPreset
```typescript
export default defineConfig({
  e2e: {
    ...nxE2EPreset(__dirname),
    supportFile: 'src/support/e2e.ts',
  },
});
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Can someone provide a reproduction so we can troubleshoot this? If not, at least some detailed reproduction steps (how to create the workspace and any other generation and changes to get to the state where the issue can be reproduced).

**Comment by ugrave** [comment]
I try to create a reproducible with:

```shell
$ npx create-nx-workspace@latest

 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

√ Where would you like to create your workspace? · bug
√ Which stack do you want to use? · angular
√ Integrated monorepo, or standalone project? · integrated
√ Application name · myapp
√ Which bundler would you like to use? · webpack
√ Default stylesheet format · scss
√ Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? · No
√ Test runner to use for end to end (E2E) tests · cypress
√ Do you want Nx Cloud to make your CI fast? · skip

 NX   Creating your v18.0.6 workspace.
```

Then i checked the new generated `cypress.config.ts` and i saw that this config uses `__filename` in the nxPreset and not `__dirname` as i did..

If i run `nx e2e myapp` with the `__filename` in the config its working. But if i change it to `__dirname`  im also getting the error:
```
Your project does not contain a default supportFile. We expect a file matching cypress/support/e2e.{js,jsx,ts,tsx} to exist.

If a support file is not necessary for your project, set supportFile to false.

https://on.cypress.io/support-file-missing-or-invalid
```

If i'm also no change it to `__filename` in my project:
```
export default defineConfig({
  e2e: {
    ...nxE2EPreset(__filename)
  },
});
```
the error away. Seems that `nxE2EPreset(__dirname)` does not work anylonger. Only if you use `nxE2EPreset(__filename)`

So to reproduce create a new workspace and change in cypress.config.ts `nxE2EPreset(__filename)` with `nxE2EPreset(__dirname)`.

**Comment by ugrave** [comment]
I had a look in the code and i found that the nxBaseConfig is normalizing the given  path:
https://github.com/nrwl/nx/blob/49861e30b7ce1cc422823b131eafde6e8fe6e6f7/packages/cypress/plugins/cypress-preset.ts#L46-L47

But for the supportFile it will not normalize:
https://github.com/nrwl/nx/blob/49861e30b7ce1cc422823b131eafde6e8fe6e6f7/packages/cypress/plugins/cypress-preset.ts#L105

**Comment by leosvelperez** [comment]
@ugrave thanks for the info and the investigation! I'll push a fix soon.
