### ISSUE TITLE
@nrwl/storybook: Peer Dependency @storybook/web does not exist on NPM

### ISSUE THREAD

**Issue by frederikdekegel** [nrwl/nx#2203]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Peer Dependencies listed @storybook/web can be installed from npm

## Current Behavior

Failure: The libray @storybook/web does not exist on npm.... judging that the version number is exactly the same as react, maybe copy - paste mistake?

## Failure Information (for bugs)
npm WARN @nrwl/storybook@8.9.0 requires a peer of @storybook/react@^5.2.5 but none is installed. You must install peer dependencies yourself.
**_npm WARN @nrwl/storybook@8.9.0 requires a peer of @storybook/web@^5.2.5 but none is installed. You must install peer dependencies yourself._**
npm WARN @nrwl/storybook@8.9.0 requires a peer of @storybook/addon-knobs@^5.2.5 but none is installed. You must install peer dependencies yourself.
npm WARN @nrwl/storybook@8.9.0 requires a peer of @babel/core@^7.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN @storybook/angular@5.2.8 requires a peer of autoprefixer@^8.1.0 but none is installed. You must install peer dependencies yourself.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. npm install --save-dev @storybook/web

### Context

Please provide any relevant information about your setup:

  @nrwl/angular : 8.9.0
  @nrwl/cli : 8.9.0
  @nrwl/cypress : 8.9.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.9.0
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.9.0
  @nrwl/web : Not Found
  @nrwl/workspace : 8.9.0
  typescript : 3.5.3

### Failure Logs

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@storybook%2fweb - Not found
npm ERR! 404
npm ERR! 404  '@storybook/web@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

## Other
/

**Comment by FrozenPandaz** [comment]
Thank you for reporting this!

I opened a PR to resolve this.
