### ISSUE TITLE
'ng cache clean' returns error

### ISSUE THREAD

**Issue by rbirkgit** [nrwl/nx#22046]
### Current Behavior

```
D:\Git>ng cache clean

 NX   Cannot find project 'clean'
```

### Expected Behavior

To be able to clear the Angular cache. Doing `nx reset` doesn't clear the Angular cache either.

### Steps to Reproduce

1. Type `ng cache clean`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 18.19.0
OS     : win32-x64
yarn   : 4.0.1

nx                 : 18.0.5
@nx/js             : 18.0.5
@nx/jest           : 18.0.5
@nx/linter         : 18.0.5
@nx/eslint         : 18.0.5
@nx/workspace      : 18.0.5
@nx/angular        : 18.0.5
@nx/cypress        : 18.0.5
@nx/devkit         : 18.0.5
@nx/eslint-plugin  : 18.0.5
@nrwl/tao          : 18.0.5
@nx/web            : 18.0.5
@nx/webpack        : 18.0.5
typescript         : 5.1.6
---------------------------------------
Community plugins:
ng-mocks : 14.12.1
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting!

I saw you had already reported this in the past, and a solution was provided: https://github.com/nrwl/nx/issues/20093#issuecomment-1805936096. To reiterate, `nx reset` is an Nx command responsible for clearing the Nx local cache, not the Angular CLI cache. You can delete the Angular CLI cache manually or even add a simple script to your `package.json`.

I'm pushing a change to handle this and provide the relevant feedback when running `nx cache ...` in Angular workspaces.
