### ISSUE TITLE
React application not running in IE11

### ISSUE THREAD

**Issue by alfonsobravi** [nrwl/nx#2209]
## Expected Behavior

The App to load polyfills and run in IE11, possibly in both development and prod mode.

## Current Behavior

**Dev mode:** IE11 raises syntax errors (related to ES6 arrow functions) and stops
**Prod mode:** blank screen, scripts are loaded but nothing seems to be evaluated, judging from performance timeline. 

#### Dev mode scenario

1. `npx --ignore-existing create-nx-workspace nx-ie11-test --preset=react`
2. `npm serve`  (or yarn, for what is worth)

Scripts are loaded and evaluated:

![timeline](https://i.imgur.com/9wlfVc9.png)

But the resulting outcome is a syntax error pointing to the first evaluated function presenting ES6 arrow notation:

![console](https://i.imgur.com/G5lfKJu.png)
![bundle](https://i.imgur.com/klBUOs6.png)

I've tried to tackle the issue from a few different angles:
- "downgrading" the `target` parameter value to `"es5"` in `tsconfig.json`;
- adding a `"browserslist"` section in `package.json` and make sure IE11 is explicitly listed;
- addding `react-app-polyfill` and cleaning `node-modules/.cache` before rebuilding as suggested [here](https://medium.com/@matwankarmalay/create-react-app-ie11-script1002-syntax-error-how-to-get-rid-of-it-d70000c53ddf);

Same result 🤕

#### Build mode scenario

1. `npx --ignore-existing create-nx-workspace nx-ie11-test --preset=react`
2. `npm build`  (or yarn, for what is worth)

Rendered page is empty and console is clean:
 
![Imgur](https://i.imgur.com/9otneIZ.png)

This time scripts are loaded but not evaluated, from what I can see.:

![Imgur](https://i.imgur.com/r4xH7Ub.png)
![Imgur](https://i.imgur.com/wAzSFE5.png)

Any suggestions?

**Comment by vsh13** [comment]
i have encountered  the same issue. Was able to get around it by putting a **.babelrc** inside my _frontend f_older wit this
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "entry",
        "forceAllTransforms": true,
        "corejs": "3.0.0",
        "targets": {
          "ie": "11"
        }
      }
    ]
  ]
}

I guess **nx** has a bug with Babel config.  @alfonsobravi  @vsavkin.

**Comment by alfonsobravi** [comment]
Thanks for the hint @vsh13, it definitely did the job for me. I still think it should be addressed or, at least, documented.

**Comment by alfonsobravi** [comment]
Definitely a Babel configuration issue which should be addressed or documented.
This `.babelrc` in the root folder is now doing the job:
````
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "useBuiltIns": "entry",
                "forceAllTransforms": true,
                "corejs": "3.0.0",
                "targets": {
                    "browsers": "last 1 version",
                    "ie": "11"
                }
            }
        ],
        "@babel/preset-react"
    ],
    "plugins": [
        "@babel/plugin-transform-runtime"
    ]
}
````
But it requires manual installation of `@babel/plugin-transform-runtime` and its configuration, alongside the inclusion of `@babel/preset-react` in the presets section.

**Comment by krizic** [comment]
@alfonsobravi still not making it work in my case :/

**Comment by alfonsobravi** [comment]
@krizic what kind of error are you getting? Please bear in mind the suggested addition of  the above described `.babelrc` does not replace the need for you to include all necessary polyfills, should any of your libraries or apps need anything more specific than what's in `core-js/stable` that **nx** includes by default.
My "usual" configuration (providing support for React, Redux, Sagas & Immer) looks something like:
```
import 'core-js/stable';
import 'core-js/fn/array/find-index';
import 'core-js/fn/array/for-each';
import 'core-js/fn/array/from';
import 'core-js/fn/object/values';
import 'regenerator-runtime/runtime';
```

**Comment by alfonsobravi** [comment]
@krizic Everything seems to have taken a step back for me as well :(
While I can run almost every bit of my monorepo in dev/debug mode (with the exception of Immer), production build is back to producing a white page with JS code pretty much ignored.
Same code, moved into a standalone CRA project, builds just fine (Immer included).

**Comment by alfonsobravi** [comment]
Please refer to last commit on master branch for the aforementioned repository.
As of v 8.11.0 of nx, both apps are now working across all browsers when using `yarn start {pkgName}` or `yarn build {pkgName} --prod`.
Omitting the `--prod` flag still triggers the white page issue. 
While I guess it's good enough for me to move forward, it still feels a tad weird and symptomatic of a fragile combination of way too many uncontrolled moving parts...

**Comment by krizic** [comment]
Using 8.11.2 and still have arrow functions left in VENDOR bundle. MAIN bundle seems ok. Am I doing something wrong?

**Comment by krizic** [comment]
added  "@babel/plugin-transform-arrow-functions", "@babel/plugin-transform-template-literals" to babel plugins, however now I ended up with a white-page no errors issue

**Comment by alfonsobravi** [comment]
I managed to getReact, Redux, Sagas, Immer, Axios working just fine on IE11 after swapping schematics generated polyfills with:
```
import 'react-app-polyfill/stable';
import 'react-app-polyfill/ie11';
```
They are wrappers for `core-js` nothing more (stable is actually just like the default polyfills) with some extra smartness attached.
Not sure how actively maintained they are in order to be considered a long term solution for the issue... I guess the other option is to extract the logic and bake it into the schematics. @vsavkin ?

**Comment by footyapps27** [comment]
Facing the same issue in IE11.
@vsavkin Any plans on fixing this?

I am using Nx 9.1.2

**Comment by vsavkin** [comment]
@footyapps27 will talk to @jaysoo, who is in charge of our react story.

**Comment by jaysoo** [comment]
Taking a look at this for the next release.

**Comment by jaysoo** [comment]
For anyone running into this problem, you can edit your `.browserslistrc` file and remove `not IE 9-11` from it. This will make the production build work with IE11.

Since we do differential loading now I think we can support IE11 in the nomodules bundle. I'll get this change into the next release.

**Comment by jaysoo** [comment]
BTW, we won't support development mode in IE11 since we target only evergreen browsers for development.

**Comment by footyapps27** [comment]
@jaysoo Updating the`.browserslistrc` did not help.

When the `optimization` is `true`, the console is printing an error.
```
Expected Identifier
```

When `optimization` is `false`, there is no error on the console.

Do you have any leads as to how to support react projects in IE 11?

My current `.browserslistrc` looks like

```
> 0.5%
last 2 versions
Firefox ESR
```

Using the latest version of `nx`:

```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : Not Found
  @nrwl/cli : 9.2.2
  @nrwl/cypress : 9.2.2
  @nrwl/eslint-plugin-nx : 9.2.2
  @nrwl/express : Not Found
  @nrwl/jest : 9.2.2
  @nrwl/linter : 9.2.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 9.2.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.2
  @nrwl/web : 9.2.2
  @nrwl/workspace : 9.2.2
  typescript : 3.8.3
```

**Comment by footyapps27** [comment]
@alfonsobravi @krizic Were you guys able to make it work on IE?

**Comment by footyapps27** [comment]
@jaysoo Any luck running the apps in IE11?

**Comment by samratshaw** [comment]
@vsavkin Please help to confirm if react apps are able to build in IE 11.

**Comment by jaysoo** [comment]
@samratshaw Hmm, that's strange. That query should include IE11. I'll have to take a look at it more closely.

**Comment by mlakmal** [comment]
@jaysoo i just tried react app through nx cli. and modified browserslist to below to allow IE 9-11

when i run npm run build xyz --prod command it is not generating differential loading script bundles.
```
> 0.5%
last 2 versions
Firefox ESR
not dead
IE 9-11
#not IE 9-10 # For IE 9-11 support, remove 'not'.

```

i am not sure if nx react supports es5 vs es2015 separate bundles on build, coming from angular support i was wondering if this is supported for react apps through nx?

**Comment by mlakmal** [comment]
> @jaysoo i just tried react app through nx cli. and modified browserslist to below to allow IE 9-11
> 
> when i run "npm run build xyz --prod" command it is not generating differential loading script bundles.
> 
> ```
> > 0.5%
> last 2 versions
> Firefox ESR
> not dead
> IE 9-11
> #not IE 9-10 # For IE 9-11 support, remove 'not'.
> ```
> 
> i am not sure if nx react supports es5 vs es2015 separate bundles on build, coming from angular support i was wondering if this is supported for react apps through nx?

never mind "npm run build --prod" command was not passing the --prod to underline command. it was resolved with usign nx build --prod

**Comment by countravioli** [comment]
@mlakmal If you are calling your nx command through npm run and want to pass args through the syntax is `npm run build -- --prod` Here is some info on passing args to your npm run commands https://github.com/npm/npm/pull/5518

+1 for being affected by this as well.

**Comment by countravioli** [comment]
I got my application running in IE11 after much googling and trial and error. I came across something that sounded similar. I think the problem is not everyone publishes their modules in NPM as es5 modules.

By default babel-loader is configured to exclude everything in node_modules. [This article](https://developer.epages.com/blog/coding/how-to-transpile-node-modules-with-babel-and-webpack-in-a-monorepo/) shared the tool `are-you-es5` with me. 

I was able to solve this in nx by replacing the webpackConfig path in workspace.json with a custom one that extends the default one by nx. It replaces the exclude rule for babel-loader with a regex provided by are-your-es5.

1. Modify workspace.json
project -> [YOUR_PROJECT] -> architect -> build -> options -> webpackConfig
```
            "webpackConfig": "./webpack.config.js",

```
2. `npm install are-you-es5`

3. create `webpack.config.js` at project root
```
const { execSync } = require('child_process');
const path = require('path');
const getWebpackConfig = require('@nrwl/react/plugins/webpack');

module.exports = (config) => {
  config = getWebpackConfig(config);

  // IE 11 Loading issues
  // certain required node_modules need to be transpiled as they are not distributed with an es5 build
  // This utility identifies those and creates a regex we can pass to babel-loader
  const bin = path.join(__dirname, '/node_modules/.bin/are-you-es5');
  const out = execSync(`node '${bin}' check . -r | tail -n 1`)

  const regexStr = out.toString().trim();
  const regex = new RegExp(regexStr);
  config.module.rules[0].exclude = regex;
  
  return config;
};
```

I obviously don't think this is a good long term solution, but I think it provides a good workaround. Also I hope it provides some clarity on how to properly resolve the issue for the more enlightened.

**Comment by zak-c-lmk** [comment]
+1 on this issue. Are there any plans for a fix?

**Comment by conioX** [comment]
+1 blank on ie

**Comment by rubennaatje** [comment]
My .browserslistrc
```# This file is used by:
# 1. autoprefixer to adjust CSS to support the below specified browsers
# 2. babel preset-env to adjust included polyfills
#
# For additional information regarding the format and rule options, please see:
# https://github.com/browserslist/browserslist#queries
#
# For IE 9-11 support, please remove 'not' from the last line of the file and adjust as needed

> 0.5%
last 2 versions
Firefox ESR
IE 9-11
dead
```

Then ``yarn nx build frontend --prod`` and it works in internet explorer for me. Without any weird workarounds I guess. Maybe annoying if you're actively trying to fix a bug specific for internet explorer but eh. Not like anyone (hopefully) actively develops in internet explorer.

**Comment by puku0x** [comment]
I found buildable libraries using `async/await` showed `regeneratorRuntime is not defined` error too.

**Comment by varoot** [comment]
>   const bin = path.join(__dirname, '/node_modules/.bin/are-you-es5');
>   const out = execSync(`node '${bin}' check . -r | tail -n 1`)
> 
>   const regexStr = out.toString().trim();
>   const regex = new RegExp(regexStr);
>   config.module.rules[0].exclude = regex;

Correct me if I'm wrong but I think there's a bug here. `are-you-es5` returns RegEx string with starting and ending "/" so we need to strip these out before passing to `new RegExp`

```js
const regexStr = out.toString().trim();
const regex = new RegExp(regexStr.substring(1, regexStr.length - 1));
```

Also this script is not Windows compatible, for Windows compatible script, we can use:

```js
const { execSync } = require('child_process');
const path = require('path');
const getWebpackConfig = require('@nrwl/react/plugins/webpack');

module.exports = (config) => {
  config = getWebpackConfig(config);

  // IE 11 Loading issues
  // certain required node_modules need to be transpiled as they are not distributed with an es5 build
  // This utility identifies those and creates a regex we can pass to babel-loader
  const bin = path.join(__dirname, 'node_modules', '.bin', 'are-you-es5');
  const out = execSync(`"${bin}" check . -r`);

  const regexStr = out.toString().trim().split('\n').pop().trim();

  // Remove "/" from the start and end
  const regex = new RegExp(regexStr.substring(1, regexStr.length - 1));

  config.module.rules[0].exclude = regex;

  return config;
};
```

**Comment by ramHruday** [comment]
Tried All of the solutions, updating browserlistrc, the webpack.config fix (the command ran gave me a error),  updated to latest nx tool..
All gave me Blank screen..
Is there any other way?

**Comment by ramHruday** [comment]
Along with updating browserlistrc,( webpack.config fix explained was throwing errors), updated nx tool

and my app started rendering when i updated babel.config.json
```

{
  "babelrcRoots": [
    "*"
  ],
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "entry",
        "forceAllTransforms": true,
        "corejs": "3.0.0",
        "targets": {
          "browsers": "last 1 version",
          "ie": "11"
        }
      }
    ],
    "@babel/preset-react",
    "@nrwl/web/babel"
  ],
  "plugins": [
    "@babel/plugin-transform-runtime",
    "@babel/plugin-transform-arrow-functions",
    "graphql-tag"
  ]
}

```

I guess our plugins are determined by what kind of react we used...We used React es6 arrow functions and graphql tag from apollo..
Although stills some console erros and css errors are there..My app rendered..

**Comment by sushruth** [comment]
This seems to be a problem still after updating to nx 10

**Comment by ramHruday** [comment]
Upgrading 10 doesnt work..
- [ ] Try Updating ur babel...
- [ ] check error on IE..
- [ ] Find out what kindoff ES6 feature in that script error needs
- [ ] to be es5'ed.
- [ ] Find the babel plugin for that and update babel config.json

**Comment by sushruth** [comment]
@ramHruday Upgrading to nx 10 acually broke my projects on IE11. It would probably help to add documentation on what all IE11 configs were removed as per the announcement blog post, and how we can customize and enable them in our projects if we needed.

Sure, there are workarounds for this but my request is to have a consistent set of rules we can follow for IE11 support.

**Comment by ADobrianskiy** [comment]
I can also confirm that after migration from v9 to v10 IE stopped working at all. The reason is that the output bundle with --prod tag missing `nomodule` files and tags inside HTML. I agree with @sushruth that it would be nice to have a straightforward way how to handle an IE browser using NX.

**Comment by fetters5** [comment]
We have the same issue b/c we use the query-string package, on latest versions of nx 9 and 10, we cannot get the query-string package to transpile to es5

**Comment by sushruth** [comment]
I debugged this for a while today. I think the issue lies in the logic of `isDifferentialLoadingNeeded()` from 

https://github.com/nrwl/nx/blob/d1f740e264e55a56edc8bd15daa5cbe40651d1f3/packages/web/src/utils/third-party/utils/build-browser-features.ts#L33-L39

I think the more appropriate way to calculate if ES5 support is needed is - 
```js
!this._es6TargetOrLater || this.isEs5SupportNeeded();
```

After doing this change locally, and then doing the following, -

1. Set `"optimization": true` in the configuration being built in `workspace.json` file
2. Use `ie 11` in `browserslist` file within the app

I was able to make a production build and have it work in IE.

I am going to submit a PR for this.

**Comment by vaunus** [comment]
@sushruth I can confirm on my side that your fix from the PR above is causing `*.es5.js` artefacts to be generated in the build. Without your fix and on NX `10.2.0` I am not seeing these files there at all, only the `*.esm.js` files are present.

On an unrelated note, I was still seeing arrow functions in my `vendor.*.es5.js` file until the `query-string` package was removed.

**Comment by sushruth** [comment]
@vaunus another thing I had to do was add "es6" to "lib" in my tsconfig. But even then node_modules files are not being compiled down essentially because the babel config in @nrwl/web package excludes transpiring anything from node_modules.

**Comment by vaunus** [comment]
@sushruth Thanks, yeah I am aware of that. I already modified the excludes option as suggested above using a custom webpack config that inherits from `@nrwl/web` and using the regex output of `npx are-you-es5 check . -r`. Even with this in place there were still arrow functions in my vendor bundle. In the end it was just easier to remove `query-string` 🙂

**Comment by sushruth** [comment]
@vaunus that may be better in multiple ways. `core-js` should polyfill stuff like URLSearchParams and URL class. Making that switch could be good.

**Comment by imekedaprahs** [comment]
I want to share that this issue haunted me for at least two weeks.
@countravioli, gave me the biggest hint by sharing information about the module: are-you-es5

I was not able to use his code snippets in their entirety, but using this module I was able to zero in on the offender and exclude them from my code base.
Thank you very much!

**Comment by nikparo** [comment]
I was pulling my hair out over why the `are-you-es5` regex wasn't working for me. Turns out the package, `color-convert` in my case, was installed as `../../node_modules/@nrwl/web/node_modules/color-convert/`. The regex matched already on `/node_modules/@nrwl/`, and the package was therefore excluded and not transpiled. The trick is to add '@nrwl' to the exclusion part of the regex: 
```js
config.module.rules[0].exclude = new RegExp('[\\/]node_modules[\\/](?!(@nrwl|color-convert)[\\/])');
```
---
If this still doesn't do the trick for you, I recommend setting `config.optimization.moduleIds = 'named';` before inspecting your bundle.

**Comment by kunjee17** [comment]
Has anyone made it working with latest dev. This really deal breaker when we are trying to move towards monorepo and nx dev. It would be great if someone can share the solution if they have made it working. 

For me it is not working at all. Even after trying most of the above solutions. Prod version just go blank on me in IE. While things are good for Chrome and other latest browser.

**Comment by kirjai** [comment]
I just had an attempt at narrowing down the issue, and as far as I can tell, IE 11 support works fine *with the simplest use case*.
[Here's a repo](https://github.com/kirjai/nx-react-ie11), where I can successfully run `yarn nx serve --prod`, open it in IE 11 (running in a VM, mind you), and see the UI working as expected. This is using latest version of Nx (`11.5.2`), and a fresh workspace. All it takes is adding `IE 11` to `.browserslist` *for the simplest use case*.

Can someone who's still experiencing this issue on latest Nx help narrow down what breaks IE 11 support for you specifically? A repro repo would be helpful. Repros that have been posted in this thread earlier are a few major versions behind by now, unfortunately. Without it, i'm afraid there's nothing actionable for us here at the moment

**Comment by kunjee17** [comment]
I was able to debug the issue I was facing. I did tried above solutions. For me my test cases was leaking into prod build. And then it was unable to convert to es5. After commenting couple of test cases I manage to cut down async code from prod build. 

Personally `minified = false` do help debug javascript files. I still unable to find out why test cases are leaking into prod build but still manage to debug it.

**Comment by Nick-Lucas** [comment]
Hi @kirjai 

I have opened a PR purely for diff purposes against your repo: https://github.com/kirjai/nx-react-ie11/pull/1 

The only changes I've made are those necessary to get this running on IE11 in a Parallels Windows 10 VM on my Mac.

On `yarn serve` IE11 gives a white screen with a syntax error, caused by an arrow function which survived transpilation:

![image](https://user-images.githubusercontent.com/8896153/128825169-c87579fa-f1f9-43a5-87c0-43dbe4c4628e.png)
![image](https://user-images.githubusercontent.com/8896153/128825227-d1911d34-4e46-462e-ba9d-8c3637613033.png)

Below are my nx report, yarn.lock, IE11 version. Note my own project is on the latest Nx versions as it was bootstrapped last week, and has the same issues.

```
  Node : 14.17.4
  OS   : darwin x64
  yarn : 1.21.1
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.5.2
  @nrwl/cypress : 11.5.2
  @nrwl/devkit : 11.5.2
  @nrwl/eslint-plugin-nx : 11.5.2
  @nrwl/express : Not Found
  @nrwl/jest : 11.5.2
  @nrwl/linter : 11.5.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.5.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.5.2
  @nrwl/web : 11.5.2
  @nrwl/workspace : 11.5.2
  @nrwl/storybook : 11.5.2
  @nrwl/gatsby : Not Found
  typescript : 4.0.7
[yarn.lock.txt](https://github.com/nrwl/nx/files/6959744/yarn.lock.txt)

```

![image](https://user-images.githubusercontent.com/8896153/128824895-dbcfda8c-95dd-4c45-8486-cbfb9e55afdf.png)

**Comment by vmashnitskaya** [comment]
Hello, I am facing the same issue with blank screen in IE11.
Steps to reproduce:
1. Create nx app with npx create-nx-workspace@latest.
2. Update .browserslistrc accordingly.
3. Update to webpack 5 via npx nx g @nrwl/web:webpack5.
I have noticed that after the 2d step, the app is running in IE11 ok, but after migration it does not and shows empty screen. 

Maybe someone faced the same issue?

**Comment by vmashnitskaya** [comment]
> Hello, I am facing the same issue with blank screen in IE11.
> Steps to reproduce:
> 
> 1. Create nx app with npx create-nx-workspace@latest.
> 2. Update .browserslistrc accordingly.
> 3. Update to webpack 5 via npx nx g @nrwl/web:webpack5.
>    I have noticed that after the 2d step, the app is running in IE11 ok, but after migration it does not and shows empty screen.
> 
> Maybe someone faced the same issue?

UPD: solved by adding to custom webpack config target: ['web', 'es5']

**Comment by sevakraynov** [comment]
Hi, i get some problems with transpilling to `es5` in ie11.

Steps for reproduce:
1. Run `npx create-nx-workspace@latest`, create app from react preset;
2. Change target in `tsconfig.base.json`: `target: "es5"`;

<details>
	<summary>tsconfig.base.json</summary>

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es5",
    "module": "esnext",
    "lib": ["es2017", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {}
  },
  "exclude": ["node_modules", "tmp"]
}
```

</details>

3. Add support IE11 in `.browserslist`

<details>
	<summary>.browserslist</summary>

```browserslist
last 1 Chrome version
last 1 Firefox version
last 2 Edge major versions
last 2 Safari major version
last 2 iOS major versions
Firefox ESR
IE 11
```

</details>

4. Install `react-app-polyfill` and add them in `polyfill.ts`
<details>
	<summary>polyfill.ts</summary>

```ts
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';
import 'core-js/stable';
import 'regenerator-runtime/runtime';
```

</details>

5. Change App functional component to class component.
<details>
	<summary>app.tsx</summary>

```tsx
import { Component } from 'react';
import styles from './app.module.scss';

export class App extends Component {
  render(): JSX.Element {
    return <div className={styles.app}>{"react-ie11"}</div>;
  }
}

export default App;

```

</details>

6. Run serve command in production configuration `npx nx serve ie11-app --configuration=production`;
7. Open IE11, get this error.
<details>
	<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/23610614/136045695-45c82cc5-cc02-4832-ac0d-f1cd028b7a24.png)
![image](https://user-images.githubusercontent.com/23610614/136045774-f1ec4f42-53d8-4fb9-af1c-f1a384e2bd14.png)

```js
}},UXeq:function(e,t,n){"use strict";n.r(t);var r=n("r0ML"),o=n("+Q0i"),a=n("mAQP"),i=n.n(a),s=n("wO/c"),l=class extends r.Component{render(){return Object(s.jsxDEV)("div",{className:i.a.app,children:"react-ie11"},void 0,!1,
```

</details>

<details>
	<summary>.babelrc</summary>

```json
{
  "presets": [
    [
      "@nrwl/react/babel",
      {
        "runtime": "automatic"
      }
    ]
  ],
  "plugins": []
}
```

</details>



`class extends` not transpiled to function. How to fix this?
