### ISSUE TITLE
NX build get stuck

### ISSUE THREAD

**Issue by MoeedthePessimist** [nrwl/nx#22094]
### Current Behavior

When running `nx build app-name` the process get stuck at  `nx run etesal:build:production` and the process doesn't comes to a completion. I don't even get an error message or any success message. 

![image](https://github.com/nrwl/nx/assets/63580699/8d08aecc-2983-47ff-8793-2219eecac4b0)

### Expected Behavior

It should either show an error message in case of any build errors or show success message if there aren't any build errors.

### GitHub Repo

https://github.com/devaxl/etesal.git

### Steps to Reproduce

1. Run `yarn install` to install the dependencies.
2. Run `nx build app-name` to build the application.

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.17.0
   OS     : win32-x64
   yarn   : 1.22.19
   
   nx (global)        : 16.6.0
   nx                 : 16.8.1
   @nx/js             : 16.8.1
   @nx/jest           : 16.8.1
   @nx/linter         : 16.8.1
   @nx/workspace      : 16.8.1
   @nx/devkit         : 16.8.1
   @nx/eslint-plugin  : 16.8.1
   @nx/express        : 16.9.1
   @nx/node           : 16.9.1
   @nx/react          : 16.8.1
   @nrwl/tao          : 16.8.1
   @nx/vite           : 16.8.1
   @nx/web            : 16.8.1
   @nx/webpack        : 16.8.1
   nx-cloud           : 16.4.0
   @nrwl/nx-cloud     : 18.0.0
   typescript         : 5.1.6
```

### Failure Logs

```shell
There are no failure logs
```

### Package Manager Version

yarn v1.22.19

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Bishop19** [comment]
I'm facing the same issue but with node@20.9.0 nx@7.1.2 and docker. If I run ```nx build webapp``` outside the container (but with the same software versions) it works.

**Comment by MoeedthePessimist** [comment]
@Bishop19 Same. Even tho it is working perfectly fine in the development mode but when building the react application it gets stuck. 

Although the node js application is building completely fine. It's kind of frustrating since there is no error message either and the logs aren't visible to see what's causing this issue.
