### ISSUE TITLE
crash storybook build when sourceMap = true

### ISSUE THREAD

**Issue by Areen3** [nrwl/nx#22115]
### Current Behavior

building project ex :nx storybook comp
crash build, 
becasue in project.json sourceMap is true (in section storybook)

### Expected Behavior

when you set soruceMap on true do not crash run storybook
"options": {
        "port": 4400,
        "sourceMap": true, <-------------------------------- if false works ok
        "configDir": "libs/str/.storybook",
        "browserTarget": "comp:build-storybook",
        "compodoc": true,
        "compodocArgs": ["-e", "json", "-d", "libs/str"]
      },

### Steps to Reproduce

1. set sourceMap: true in storybook section
2 build project for ex. nx storybook comp

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 18.18.2
OS     : win32-x64
npm    : 9.8.1

nx (global)        : 18.0.6
nx                 : 18.0.6
@nx/js             : 18.0.6
@nx/jest           : 18.0.6
@nx/linter         : 18.0.6
@nx/eslint         : 18.0.6
@nx/workspace      : 18.0.6
@nx/angular        : 18.0.6
@nx/cypress        : 18.0.6
@nx/devkit         : 18.0.6
@nx/eslint-plugin  : 18.0.6
@nx/storybook      : 18.0.6
@nrwl/tao          : 18.0.6
@nx/web            : 18.0.6
@nx/webpack        : 18.0.6
typescript         : 5.3.3
---------------------------------------
Community plugins:
@compodoc/compodoc : 1.1.23
@storybook/angular : 7.6.17
```

### Failure Logs

```shell
E:\temp\to-check-something\storybook\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\javascript\JavascriptModulesPlugin.js:164
                        throw new TypeError(
                              ^

TypeError: The 'compilation' argument must be an instance of Compilation
    at JavascriptModulesPlugin.getCompilationHooks (E:\temp\to-check-something\storybook\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\javascript\JavascriptModulesPlugin.js:164:10)
    at SourceMapDevToolModuleOptionsPlugin.apply (E:\temp\to-check-something\storybook\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\SourceMapDevToolModuleOptionsPlugin.js:54:27)
    at E:\temp\to-check-something\storybook\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\SourceMapDevToolPlugin.js:184:53
    at Hook.eval [as call] (eval at create (E:\temp\to-check-something\storybook\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:256:1)
    at Hook.CALL_DELEGATE [as _call] (E:\temp\to-check-something\storybook\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (E:\temp\to-check-something\storybook\node_modules\webpack\lib\Compiler.js:1139:26)
    at E:\temp\to-check-something\storybook\node_modules\webpack\lib\Compiler.js:1183:29
    at _next0 (eval at create (E:\temp\to-check-something\storybook\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:41:1)
    at eval (eval at create (E:\temp\to-check-something\storybook\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:55:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.18.2
Waiting for the debugger to disconnect...
```

### Package Manager Version

npm

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Areen3** [comment]
This sourceMap is nessesery to build storybook with debug information
soruceMap is avaliable in schema angular and I can debug komponents code
In nx i cant't debug (except browser debug)

I try add sourceMap as 
nx storybook comp --sourceMap
in main.js storybook 
but nothing wokrs. 
It is important that debug test what we write. 

Maybe there is a place somewhere else where I can set this switch to enable debugging?

**Comment by Areen3** [comment]
ok actual state is:
I add sourceMap to project.json configuration
![image](https://github.com/nrwl/nx/assets/34617740/2f888ed3-dc77-461e-9a3b-f00405c6aa42)
I comment this code in webpack
![image](https://github.com/nrwl/nx/assets/34617740/3d750143-73c2-46ec-9799-1d6cc32c9b37)
this is in file JavascriptModulesPlugin.js
my wersion, of webpack: "webpack": "^5.88.2",

and I can set breakpoint in components and debug code componts

I think, that, NX sending wrong configuration to web packa, but these are my guesses

**Comment by Coly010** [comment]
Hey! It would be great if you could provide a repo with a minimal reproduction of this issue so i can investigate further 🙂

**Comment by Areen3** [comment]
hi
https://github.com/Areen3/storybook-test
run command: nx storybook comp
and you shud have this error:
![image](https://github.com/nrwl/nx/assets/34617740/87c4df1e-0d03-4342-addc-cbbf68888636)

**Comment by Areen3** [comment]
ok, today I make another env

**Comment by Areen3** [comment]
@Coly010 

this repo https://github.com/Areen3/storybook-test is not working, I checked it

You can make some investigation :)
