### ISSUE TITLE
Install nx failed with v18.1.0

### ISSUE THREAD

**Issue by waitingsong** [nrwl/nx#22129]
### Current Behavior

no error with v18.0.6
got error with v18.1.0
linux: 
```
Error: Cannot find module '@nx/nx-linux-x64-gnu'
```

window11:
```
Error: Cannot find module '@nx/nx-win32-x64-msvc'

```

### Expected Behavior

installation succeed

### Steps to Reproduce

1.

### Nx Report

```shell
none
```

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Yes, sorry, 18.1.0 was published accidentally! Please do not use!!!! Sorry about that!!!

**Comment by srn271** [comment]
I have an almost identical problem with **Nx 18.0.6** on our CI:

> Error: Cannot find module '@nx/nx-linux-x64-musl'

The local installation (Windows) works fine.
Any suggestions? Or should i open a new issues?
