### ISSUE TITLE
`@babel/runtime` is missing when creating Expo project with Nx & PNPM

### ISSUE THREAD

**Issue by kopach** [nrwl/nx#22122]
### Current Behavior

When creating project with NX & PNPM - it won't work due to missing dependency

### Expected Behavior

no errors should be thrown on app start, `@babel/runtime` should be present explicitly in package.json

### Steps to Reproduce

1. ` npx create-nx-workspace@latest --preset=expo --appName=your-app-name`
2. start the app
3. error is thrown `Error: Cannot resolve @babel/runtime/helpers/interopRequireDefault`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 18.17.0
OS     : darwin-arm64
pnpm   : 8.6.12

nx                 : 18.0.6
@nx/js             : 18.0.6
@nx/jest           : 18.0.6
@nx/linter         : 18.0.6
@nx/eslint         : 18.0.6
@nx/workspace      : 18.0.6
@nx/detox          : 18.0.6
@nx/devkit         : 18.0.6
@nx/eslint-plugin  : 18.0.6
@nx/expo           : 18.0.6
@nx/react          : 18.0.6
@nrwl/tao          : 18.0.6
@nx/web            : 18.0.6
@nx/webpack        : 18.0.6
typescript         : 5.3.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
i think it is fixed in a part of pr https://github.com/nrwl/nx/pull/22759/files
