### ISSUE TITLE
docs: Extend/Change the rollup configuration used to build libs

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#2212]
There is a nice official cookbook about how to extend webpack for building apps https://connect.nrwl.io/app/cookbook/4CjE7wgoOyYU3ri08GCAr7

Can you provide similar for rollup/libs ?

thx !

**Comment by srdjanRakic** [comment]
Any news on this?

**Comment by srdjanRakic** [comment]
Is there any way I can extend the rollup config and add image plugin? @Cammisuli 

<img width="944" alt="Screen Shot 2020-02-23 at 16 45 45" src="https://user-images.githubusercontent.com/16154503/75115095-fde6de80-565b-11ea-85df-05f0016ef3bf.png">

**Comment by Cammisuli** [comment]
@srdjanRakic if you're using react (which uses the web builder), you can provide a `rollup.config.js` path in the `build` architect of your `paywall-previews` project.
https://nx.dev/web/api/web/builders/package#rollupconfig

the config should look something similar to this:
```
module.exports = (config) => {
   // do your config 
}
```

And for reference, the code:
https://github.com/nrwl/nx/blob/49168c10e334bc6566e37f3de4312d33272e81f2/packages/web/src/builders/package/package.impl.ts#L134-L136

**Comment by hsw107** [comment]
Just updating the link here from @Cammisuli's comment, https://nx.dev/react/plugins/web/builders/package#rollupconfig

**Comment by timbakkum** [comment]
Any way to use webpack to build a react component lib? We are already using webpack for storybook in this lib and is also consumed by apps that use webpack to build. Rather frustrating and a lot of extra work to create a custom rollup config that does the same as and is compatible with our webpack configs!

**Comment by asherccohen** [comment]
> Any way to use webpack to build a react component lib? We are already using webpack for storybook in this lib and is also consumed by apps that use webpack to build. Rather frustrating and a lot of extra work to create a custom rollup config that does the same as and is compatible with our webpack configs!

Same here, why we're forced to use rollup for libs (web:package builder) when there is a a webpack compatible builder (web:build)?

**Comment by asherccohen** [comment]
[Followup]

A nice to have would be to include javascriptEnabled flag and modifyVars for LESS compilation in rollup postcss configuration;

```
            postcss({
                inject: true,
                extract: options.extractCss,
                autoModules: true,
                plugins: [autoprefixer],
                        use: [
          [
            'less',
            {
              javascriptEnabled: true,
              // modifyVars: {
              //   'primary-color': '#1DA57A',
              //   'link-color': '#1DA57A',
              //   'border-radius-base': '2px',
              // },
            },
          ],
        ],
            }),
```

**Comment by wolfhoundjesse** [comment]
> Any way to use webpack to build a react component lib? 
Have you tried changing the executor in your workspace.json to `@nrwl/web:build`?

**Comment by alexworker23** [comment]
For those who are looking for a way to extend rollup config - here is my solution, which helped me to add `svgr` plugin:
1. Create `rollup.config.js` inside root folder.
2. Create the config extending the already existing one from nx
```
const nrwlConfig = require('@nrwl/react/plugins/bundle-rollup');
const svgr = require('@svgr/rollup').default;

module.exports = (config) => {
  nrwlConfig(config);
  return {
    ...config,
    plugins: [...config.plugins, svgr()]
  };
}
```
3. Attach the config to the project you want to build it with (in workspace.json) :
```
"projects":
   "ui-project-name": {
   ...
      "targets": {
      ...
         "build": {
         ...
            "rollupConfig": "rollup.config.js",
         }
       }
   }
```

**Comment by subhranshudas** [comment]
i tried below but this does not work. the strings are not replaced.

```
const nrwlConfig = require('@nrwl/react/plugins/bundle-rollup');
const replace = require('@rollup/plugin-replace').default;

module.exports = (config) => {
  const nxConfig = nrwlConfig(config);

  return {
    ...nxConfig,
    plugins: [
      ...nxConfig.plugins,
      replace({
        '../../assets/frownface.png': './lib/assets/frownface.png',
      })
    ]
  };
}
```

**Comment by Azbesciak** [comment]
What with @nrwl/angular:package executor? is there any way that I can use custom rollup or webpack config addition or substitution, _without_ own custom executor?
