### ISSUE TITLE
`@nx/vite:test` ignoring `passWithNoTests` after migrating to 18.1.0

### ISSUE THREAD

**Issue by Lonli-Lokli** [nrwl/nx#22139]
### Current Behavior

Failure with vitest when no tests are found in the project

### Expected Behavior

No failures

### Steps to Reproduce

1) Add js lib with vite & vitest
2) add passWithNoTests: truee to test target in project.json
3) remove all tests
4) run npx nx run project:test

### Nx Report

```shell
Nx 18.1
Node 18.18.2
npm 9.8.1
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by JoepKockelkorn** [comment]
I've stumbled upon this as well. Workaround for me was to apply the setting in the vite.config.ts under `test`, but I expected there to be a migration which there was not.

**Comment by Lonli-Lokli** [comment]
I should also add that this option was not officially supported https://nx.dev/nx-api/vite/executors/test

**Comment by Coly010** [comment]
`passWithNoTests` is an option that you must set in your `vite.config.ts` or `vitest.config.ts`

From the `vitest` docs: https://vitest.dev/config/#passwithnotests
