### ISSUE TITLE
Integrated monorepo tutorial not accurate

### ISSUE THREAD

**Issue by PauloMadro** [nrwl/nx#22133]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/getting-started/tutorials/integrated-repo-tutorial

### Additional context or description

It states that after running 
`npx create-nx-workspace@latest myorg --preset=ts`
I would get a specific folder structure. But it's not what I got. I didn't get the packages or tools folders created. Also whenever I add a new app or library those get to the root folder, and according the documentation they should get to a subfolder.

**Comment by isaacplmann** [comment]
This tutorial has been removed in favor of the [React Monorepo tutorial](https://nx.dev/getting-started/tutorials/react-monorepo-tutorial)
