### ISSUE TITLE
docs: is there any way how to copy files when building libs/apps via glob

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#2213]
taken from comment: https://github.com/nrwl/nx/pull/1907#issuecomment-551991878

**Comment by Cammisuli** [comment]
More often than not, building apps would usually have an `asset` property. For example, building apps would usually have an `asset` property you can specify in the `workspace.json` or `angular.json`. 
You can read more here: https://nx.dev/react/api/web/builders/build#assets

With libs, there usually isn't an asset property you can specify when building those.

**Comment by leon** [comment]
Yes there is.
It's available via the angular app config.

```json
// the key is within: projects.myapp.architect.options
"assets": [
              "apps/app/src/favicon.ico",
              "apps/app/src/robots.txt",
              "apps/app/src/manifest.webmanifest",
              {
                "glob": "**/*",
                "input": "libs/shared/ui-theme/assets",
                "output": "./assets"
              }
            ],
```

This will copy all files from the assets folder of ui-theme into assets

so libs/shared/ui-theme/assets/img/logo.png will become the same as apps/app/assets/img/logo.png

**Comment by sameerinfodb** [comment]
@leon 
How about Style sheets, can we store style sheet as well in the shared folder then copy it to assets folder at the time of build.

**Comment by Hotell** [comment]
> @leon
> How about Style sheets, can we store style sheet as well in the shared folder then copy it to assets folder at the time of build.

That can be done in similar way via `<target>.options.styles` https://nx.dev/react/api/web/builders/build#styles

demo: https://github.com/nrwl/nx-examples/blob/master/angular.json#L38-L41

**Comment by Hotell** [comment]
> More often than not, building apps would usually have an `asset` property. For example, building apps would usually have an `asset` property you can specify in the `workspace.json` or `angular.json`.
> You can read more here: https://nx.dev/react/api/web/builders/build#assets
> 
> With libs, there usually isn't an asset property you can specify when building those.

this answer is enough, thx @Cammisuli , Closing

**Comment by n0mer** [comment]
@leon , your sample would copy robots.txt to ./dist/assets/robots.txt

But according to https://www.robotstxt.org  , this file should be in project root.

**Comment by pawaniu** [comment]
Hi,

The `init()` function present in `lib/core/Context.js` finding files present in `"sources", "builders", "transforms"` folders which is one level up in the source code. But when we are bundling this package into node application using Nx/Webpack,  then in main.js i.e. the final bundle file, there is no parent directory preset with these mentioned names.  Which gives error while initializing. Can we have some const of all the files present in these folders instead of directly referring to fileSystem to avoid this error?
