### ISSUE TITLE
Nx trying to access local files on mac

### ISSUE THREAD

**Issue by PauloMadro** [nrwl/nx#22134]
### Current Behavior

I'm using this guide https://nx.dev/nx-api/vite/generators/configuration to migrate a webpack project to vite.
After I ran the command, it started requesting access to my mac folders like photos or downloads. I denied everything because it's weird. Is that expected? And then it won't run the serve command
<img width="1045" alt="Screenshot 2024-03-04 at 10 56 56 AM" src="https://github.com/nrwl/nx/assets/134521706/74d9b72d-a92e-4424-9430-913c56b1b4ac">

### Expected Behavior

It should not request access to .Trash or any other personal folder

### Steps to Reproduce

1.
NA

### Nx Report

```shell
Same error as above, cant access .Trash so it won't let me create nx report
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information
Yes, I tried nx reset but the error persists. The only way to make it work is reverting the branch to before the migration. Update: Even if I just create a new vite project it starts failing, no migration needed. I created a new app in my monorepo with this command `npx nx g @nx/react:app pinata-vite --bundler=vite` the error is the same

**Comment by Coly010** [comment]
Thank you for bringing this issue to our attention! I want to assure you that I will take a look as soon as I can. Your patience and understanding in this matter is greatly appreciated.

**Comment by Coly010** [comment]
Hi, I was not able to reproduce this. Could you provide a reproduction?
