### ISSUE TITLE
Azure Devops with NX Agents does not work

### ISSUE THREAD

**Issue by edolic** [nrwl/nx#22159]
### Current Behavior

With the provided example pipeline in the Documentation https://nx.dev/ci/recipes/set-up/monorepo-ci-azure the setup is not working.

The pipeline it self has also a small issue

Corrected:
```
- bash: |
          LAST_SHA=$(az pipelines build list --branch $(Build.SourceBranchName) --definition-ids $(System.DefinitionId) --result succeeded --top 1 --query "[0].triggerInfo.\"ci.sourceSha\"")
          if [ -z "$LAST_SHA" ]
          then
            echo "Last successful commit not found. Using fallback 'HEAD~1': $BASE_SHA"
          else
            echo "Last successful commit SHA: $LAST_SHA"
            echo "##vso[task.setvariable variable=BASE_SHA]$LAST_SHA"
          fi
        displayName: 'Get last successful commit SHA'
        condition: ne(variables['Build.Reason'], 'PullRequest')
        env:
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
```

### Expected Behavior

Build is working based on NX agents integration / usage.

I assume the default workflow used is wrong: Error Message
```

Error: Command failed: git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin pull/51962/head
fatal: couldn't find remote ref pull/51962/head
```

The branch name doesn't exist. Azure Devops has not default pull request branch naming.

### Steps to Reproduce

1. Nx Monorepo hosted in azure
2. Use the pipeline from documentation: https://nx.dev/ci/recipes/set-up/monorepo-ci-azure => fixe the pipelien to make it run
3. Error will be thrown: 
![image](https://github.com/nrwl/nx/assets/2466617/ff58b116-cf8f-43e8-bce2-872252f75f78)

### Nx Report

```shell
>  NX   Unable to complete a run.

   CI execution '274308' failed. Reason: One or more workflows failed. Visit https://nx.dev/ci/recipes/troubleshooting/ci-execution-failed#one-or-more-workflows-failed for more information.
   Error: CI execution '274308' failed. Reason: One or more workflows failed. Visit https://nx.dev/ci/recipes/troubleshooting/ci-execution-failed#one-or-more-workflows-failed for more information.
```

### Failure Logs

```shell
Starting logs...
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
fatal: couldn't find remote ref pull/51962/head
node:child_process:965
    throw err;
    ^

Error: Command failed: git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin pull/51962/head
fatal: couldn't find remote ref pull/51962/head

    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at Object.<anonymous> (/tmp/3272864555:28:37)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  status: 128,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(48) [Uint8Array] [
      102,  97, 116,  97, 108,  58,  32,  99, 111,
      117, 108, 100, 110,  39, 116,  32, 102, 105,
      110, 100,  32, 114, 101, 109, 111, 116, 101,
       32, 114, 101, 102,  32, 112, 117, 108, 108,
       47,  53,  49,  57,  54,  50,  47, 104, 101,
       97, 100,  10
    ]
  ],
  pid: 62,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(48) [Uint8Array] [
    102,  97, 116,  97, 108,  58,  32,  99, 111,
    117, 108, 100, 110,  39, 116,  32, 102, 105,
    110, 100,  32, 114, 101, 109, 111, 116, 101,
     32, 114, 101, 102,  32, 112, 117, 108, 108,
     47,  53,  49,  57,  54,  50,  47, 104, 101,
     97, 100,  10
  ]
}

Node.js v20.9.0
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jdpearce** [comment]
Hi @edolic - are you using Azure Git?

Unfortunately our ADO pipeline only works if you're hosting this on GitHub (since Azure Git doesn't even support PR triggers).

The other problem with Azure Git is that the launch templates we currently provide will not work and you'll have to write your own (not least because Azure Git doesn't use the same refs as GitHub)

We are looking to document this in the near future. Sorry you've had to discover this yourself.

**Comment by edolic** [comment]
Yes, I'm using Azure Git.

Hm I was looking already in the existing template, some tweaking here, could solve the issue: https://github.com/nrwl/nx-cloud-workflows/blob/main/workflow-steps/checkout/main.ts

As it's already supports other vendors besides Github. 

If I change the branch name from number to the real branch name it works till the last line

```
// Checkout the branch or PR
  const checkoutRef = isPR ? 'FETCH_HEAD' : `origin/${nxBranch}`;
  execSync(`git checkout --progress --force -B ${nxBranch} ${checkoutRef}`);
```
it should be as well FETCH_HEAD, but isPR is false in this case, as it's not a number :)

I will try to create a custom checkout template and use the existing workflow

**Comment by jdpearce** [comment]
@edolic If you want to share the updated template, that would be super helpful for other folks on Azure Git. 

If you were to create a PR to update that template to support Azure Git as well as the other providers, that would be even better!

**Comment by edolic** [comment]
I was trying first by adding my custom launch-template in .nx/workflows/agents.yaml as described in the [documentation](https://nx.dev/ci/reference/launch-templates), but this file is not picked up.

**Comment by edolic** [comment]
This was solved by: https://github.com/nrwl/nx-cloud-workflows/pull/34
