### ISSUE TITLE
'The "path" argument must be of type string or...' if using @nx/js:swc and @nx/webpack:webpack (with generatePackageJson)

### ISSUE THREAD

**Issue by stixx200** [nrwl/nx#22160]
### Current Behavior

The method `getSwcrcPath` (in `get-swcrc-path.ts`) returns an object which isn't expected by `compiler-helper-dependency.ts`.
The jsExecutors object expect to return a string in `getConfigPath`.

If this object is passed to `getHelperDependency`->`readJsonFile`, the following exception gets thrown:
`HookWebpackError: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Object`

### Expected Behavior

No error :)

### GitHub Repo

https://github.com/stixx200/nx-js-swc-webpack-generatepackagejson-repro

### Steps to Reproduce

1. Use a library with `@nx/js:swc` executor
2. Use an application with `@nx/webpack:webpack` executor with activated `generatePackageJson`
3. build the application

With the repro repository:
- `cd org`
- `npx nx build fooapp`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.11.1
OS     : win32-x64
npm    : 10.2.4

nx                 : 18.1.0
@nx/js             : 18.1.0
@nx/jest           : 18.1.0
@nx/linter         : 18.1.0
@nx/eslint         : 18.1.0
@nx/workspace      : 18.1.0
@nx/devkit         : 18.1.0
@nx/esbuild        : 18.1.0
@nx/eslint-plugin  : 18.1.0
@nx/node           : 18.1.0
@nrwl/tao          : 18.1.0
@nx/web            : 18.1.0
@nx/webpack        : 18.1.0
typescript         : 5.3.3
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

This patch solves the issue. I don't know if this is the correct way:

```
diff --git a/packages/js/src/utils/compiler-helper-dependency.ts b/packages/js/src/utils/compiler-helper-dependency.ts
index 85f685096f..226d4d6c88 100644
--- a/packages/js/src/utils/compiler-helper-dependency.ts
+++ b/packages/js/src/utils/compiler-helper-dependency.ts
@@ -16,7 +16,21 @@ export enum HelperDependency {
   swc = 'npm:@swc/helpers',
 }
 
-const jsExecutors = {
+enum JsExecutors {
+  tsc = '@nx/js:tsc',
+  swc = '@nx/js:swc',
+}
+
+type ExecutorHelper = {
+  helperDependency: HelperDependency;
+  getConfigPath: (
+    options: ExecutorOptions,
+    contextRoot: string,
+    projectRoot: string
+  ) => string;
+};
+
+const jsExecutors: Record<JsExecutors, ExecutorHelper> = {
   '@nx/js:tsc': {
     helperDependency: HelperDependency.tsc,
     getConfigPath: (options: ExecutorOptions, contextRoot: string, _: string) =>
@@ -28,7 +42,7 @@ const jsExecutors = {
       options: SwcExecutorOptions,
       contextRoot: string,
       projectRoot: string
-    ) => getSwcrcPath(options, contextRoot, projectRoot),
+    ) => getSwcrcPath(options, contextRoot, projectRoot).swcrcPath,
   } as const,
 } as const;
```

**Comment by Kolahzary** [comment]
This issue is blocking us from upgrading to the latest version of NX

**Comment by bddy** [comment]
> This issue is blocking us from upgrading to the latest version of NX

We were in the same situation and ended up using [patch-package](https://www.npmjs.com/package/patch-package). Here's the patch:

```
diff --git a/node_modules/@nx/js/src/utils/compiler-helper-dependency.js b/node_modules/@nx/js/src/utils/compiler-helper-dependency.js
index da45e37..3f3b6d1 100644
--- a/node_modules/@nx/js/src/utils/compiler-helper-dependency.js
+++ b/node_modules/@nx/js/src/utils/compiler-helper-dependency.js
@@ -17,7 +17,7 @@ const jsExecutors = {
     },
     '@nx/js:swc': {
         helperDependency: HelperDependency.swc,
-        getConfigPath: (options, contextRoot, projectRoot) => (0, get_swcrc_path_1.getSwcrcPath)(options, contextRoot, projectRoot),
+        getConfigPath: (options, contextRoot, projectRoot) => (0, get_swcrc_path_1.getSwcrcPath)(options, contextRoot, projectRoot).swcrcPath,
     },
 };
 /**

```

**Comment by jorgeramirezamora** [comment]
Same here, this happens when upgrading from Nx `17.3.2` to `18.3.5`

**Comment by P4sca1** [comment]
The issue still exists with nx version 19.2.0-beta.7. The patch mentioned above seems to work fine.

**Comment by jorgeramirezamora** [comment]
> Same here, this happens when upgrading from Nx `17.3.2` to `18.3.5`

By the way, I skipped this error by removing the `generatePackageJson` flag (In case you do not need to generate the package.json for the given project).
