### ISSUE TITLE
nx exiting with code 0 in CI without executing target

### ISSUE THREAD

**Issue by jimdubbs** [nrwl/nx#2219]
## Expected Behavior
when executing nx affected --target=build in AWS CodeBuild using the --files argument i would expect the affected apps to be build. here is the command I am executing:
npm run affected -- --target=build --files=libs/svc-service-lane-ng-ui/src/lib/accept-quote-line-dialog/accept-quote-line-dialog.component.ts --prod

## Current Behavior
When I run this locally, it executes as I would expect. When I execute this via AWS CodeBuild the child process executing the command exits with code 0 immediately, with nothing in the stderr or stdout.

## Failure Information (for bugs)
I've verified the path to the files passed to the --files argument is accurate. Even if they were not, I woudl expect some sort of output from the nx execution, but there is nothing in either stderr or stdout.

### Context

Please provide any relevant information about your setup:

Running version 8.5 of NX.

**Comment by vsavkin** [comment]
When happens when you run locally and in CI? 

```
npm run affected:apps -- --files=libs/svc-service-lane-ng-ui/src/lib/accept-quote-line-dialog/accept-quote-line-dialog.component.ts 
npm run affected:libs -- --files=libs/svc-service-lane-ng-ui/src/lib/accept-quote-line-dialog/accept-quote-line-dialog.component.ts 
```

**Comment by jimdubbs** [comment]
when running both those commands locally it behaves as I would expect. in CI it does not work in the same manner as stated above.

possibly worth noting that my CI process is calling a javascript file ("node ci.js") as I am doing a few things prior to trying to execute the affected build. I did try explicitly setting the build command in CI to "npm run affected:apps -- --files=libs/svc-service-lane-ng-ui/src/lib/accept-quote-line-dialog/accept-quote-line-dialog.component.ts" as well though, but returned the same result.

**Comment by jimdubbs** [comment]
running "nx build" in CI also automatically exits with code 0 with nothing in the stderr or stdout.

**Comment by jimdubbs** [comment]
@vsavkin Any suggestions on where to start figuring this one out? I know you're quite busy so I dont mind figuring it out..just need a little direction!

**Comment by vsavkin** [comment]
@jimdubbs really sorry for the late reply. 

`nx build` simply delegates to the angular cli. It doesn't do much apart from that.

Do you see the same result when running `ng build ...`?

**Comment by jimdubbs** [comment]
@vsavkin running ng build works as expected.

**Comment by kklimczak** [comment]
@vsavkin I ran `nx g @nrwl/web:application app` today and I noticed the same bahavior (exit 0 without any information in console. 
My stack:
```
nx: 8.2.0
node: 10.16.0
npm: 6.9.0
os: Ubuntu 19.10
```

**Comment by vsavkin** [comment]
@kklimczak could you step through the nx script to see why it exists. This is the script is invoked when you run nx build: `node_modules/@nrwl/cli/lib/init-local.js`

**Comment by jimdubbs** [comment]
in trying to figure out whats happening, if I import the affected.js directly from node_modules and use that everything works correctly.

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by imaustink** [comment]
We are seeing this same issue in our CodeBuild jobs when running `nx affected:build --base=origin/master --head=HEAD`, `nx affected:test --base=origin/master --head=HEAD`, and even `nx print-affected`. All of these exit 0 printing nothing more than `Done in 0.08s.`.

I have discovered a workaround. If I disable local caching for a build, nx behaves as expected. Obviously this is less than desirable so we'd love to get this solved soon.

I am happy to contribute a PR to resolve this, but I need a little direction here as I am completely baffled by this behavior.

**Comment by vsavkin** [comment]
@imaustink quick question. 

- When you run print-affected, there is nothing being displayed? 
- If you disable caching for a build, what happens to print-affected?

**Comment by vsavkin** [comment]
Folks. I need more information about the issue. @imaustink could you help by answering the questions above?

**Comment by jcvalerio** [comment]
We are facing the same issue using AWS Amplify console

we release a new version only if the test and e2e test passed successfully, but the script fails and the AWS Amplify console just got an exit code 0

`amplify.yml`

```yml


test:
  phases:
    preTest:
      commands:
        - nvm use $VERSION_NODE_12

    test:
      commands:
        - echo "Run unit and e2e tests based on Nx dep-graph"
        - ./run-dep-graph.sh
        - exitCode=$?
        - if [ ${exitCode} -ne 0 ]; then exit 1; fi

        - echo "Publish new version"
        - if [ "${AWS_BRANCH}" = "master" ]; then npx semantic-release; fi

    postTest:
      commands:
        - echo "Generate Mochawesome reports"
        - ./generate-reports.sh

```

`run-dep-graph.sh`

```sh
#!/usr/bin/env bash
set -Eeuxo pipefail

REVISION=origin/${AWS_BRANCH}~1
AWS_BRANCH=master

npm run affected:test -- --base=${REVISION} --head=${AWS_BRANCH} --parallel
exitCode=$?
if [ ${exitCode} -ne 0 ]; then exit 1; fi

exit 0;

```

As you can see in the image below one of our test fails and it is notifies as *INFO* instead of an *ERROR*
```
[INFO]: > nx run utils:test
```

In the image below you can see the AWS Amplify Console log for each statement and the exit code was 0

![image](https://user-images.githubusercontent.com/2169894/90281653-2f31b180-de2a-11ea-8096-13467477f3b7.png)
This is a failing test

![image](https://user-images.githubusercontent.com/2169894/90277349-9fd4d000-de22-11ea-9d37-744c7acf1238.png)
This is a failing e2e

If we run the same script locally it break the bash execution and exit with a error code 1

![image](https://user-images.githubusercontent.com/2169894/90283617-c51b0b80-de2d-11ea-9828-d750660b598a.png)


The expected behavior for this bash script on any environment CI or local with a failing test

```sh
REVISION=origin/${AWS_BRANCH}~1
AWS_BRANCH=master
npx nx affected:test --base=${REVISION} --head=${AWS_BRANCH} --parallel 
exitCode=$?
echo "exitCode = $?"
if [ ${exitCode} -ne 0 ]; then exit 1; fi
exit 0;
```

the affected completes with an exit code different than 0
then the `exitCode=$?` get that value and continues the script execution

Currently it just fails and break the execution, so we are unable to add custom handling

**Comment by imaustink** [comment]
> @imaustink quick question.
> 
> * When you run print-affected, there is nothing being displayed?
Correct
> * If you disable caching for a build, what happens to print-affected?
With caching disabled, `print-affected` (and seemingly all other NX commands) works as expected, meaning it prints out a JSON object of the projects, libs, and dependencies that changed.

**Comment by vsavkin** [comment]
Thank you folks.

This is the place were we exit with status code 1: https://github.com/nrwl/nx/blob/master/packages/workspace/src/tasks-runner/run-command.ts#L84

Because you see the failures printed out, I expect the hasFailure function to return "true".

You can verify it that it's called by adding a console.log statement there in a postinstall script:

```
fs.writeFileSync("node_modules/@nrwl/workspace/src/tasks-runner/run-command.js"",
fs.readFileSync("node_modules/@nrwl/workspace/src/tasks-runner/run-command.js").toString().replace("process.exit(1);", "console.log('exit1!!!!');process.exit(1);")
```

Let me know if you see `exit1!!!` printed out. And please try either latest 9x or latest 10x.

**Comment by imaustink** [comment]
@vsavkin the problem is that the nx CLI is exiting with a code 0 without seemingly doing anything. It is not exiting with code 1. Looks like @jcvalerio was also seeing it exit with code 0 in CI, but when he ran it locally when he got a code 1. I believe that is unrelated to this issue.

**Comment by jcvalerio** [comment]
Exactly @imaustink !!

@vsavkin, I tried to describe what happens locally and on the CI, and the results are totally different.

**Comment by vsavkin** [comment]
I know that the behavior is different. The CI output in the screenshot is printed right before the line I highlighted.  So I image the printResults is called, but process.exit(1) is either not called, or it is called and some other process wraps your command and ignore status code 1. So I'm curious which one is it.

**Comment by Rafcin** [comment]
> We are facing the same issue using AWS Amplify console
> 
> we release a new version only if the test and e2e test passed successfully, but the script fails and the AWS Amplify console just got an exit code 0
> 
> `amplify.yml`
> 
> ```yaml
> test:
>   phases:
>     preTest:
>       commands:
>         - nvm use $VERSION_NODE_12
> 
>     test:
>       commands:
>         - echo "Run unit and e2e tests based on Nx dep-graph"
>         - ./run-dep-graph.sh
>         - exitCode=$?
>         - if [ ${exitCode} -ne 0 ]; then exit 1; fi
> 
>         - echo "Publish new version"
>         - if [ "${AWS_BRANCH}" = "master" ]; then npx semantic-release; fi
> 
>     postTest:
>       commands:
>         - echo "Generate Mochawesome reports"
>         - ./generate-reports.sh
> ```
> 
> `run-dep-graph.sh`
> 
> ```shell
> #!/usr/bin/env bash
> set -Eeuxo pipefail
> 
> REVISION=origin/${AWS_BRANCH}~1
> AWS_BRANCH=master
> 
> npm run affected:test -- --base=${REVISION} --head=${AWS_BRANCH} --parallel
> exitCode=$?
> if [ ${exitCode} -ne 0 ]; then exit 1; fi
> 
> exit 0;
> ```
> 
> As you can see in the image below one of our test fails and it is notifies as _INFO_ instead of an _ERROR_
> 
> ```
> [INFO]: > nx run utils:test
> ```
> 
> In the image below you can see the AWS Amplify Console log for each statement and the exit code was 0
> 
> ![image](https://user-images.githubusercontent.com/2169894/90281653-2f31b180-de2a-11ea-8096-13467477f3b7.png) This is a failing test
> 
> ![image](https://user-images.githubusercontent.com/2169894/90277349-9fd4d000-de22-11ea-9d37-744c7acf1238.png) This is a failing e2e
> 
> If we run the same script locally it break the bash execution and exit with a error code 1
> 
> ![image](https://user-images.githubusercontent.com/2169894/90283617-c51b0b80-de2d-11ea-9828-d750660b598a.png)
> 
> The expected behavior for this bash script on any environment CI or local with a failing test
> 
> ```shell
> REVISION=origin/${AWS_BRANCH}~1
> AWS_BRANCH=master
> npx nx affected:test --base=${REVISION} --head=${AWS_BRANCH} --parallel 
> exitCode=$?
> echo "exitCode = $?"
> if [ ${exitCode} -ne 0 ]; then exit 1; fi
> exit 0;
> ```
> 
> the affected completes with an exit code different than 0 then the `exitCode=$?` get that value and continues the script execution
> 
> Currently it just fails and break the execution, so we are unable to add custom handling

@jcvalerio Sorry, did you manage to deploy a NX repo to Amplify? How did you manage that? I can't get it to deploy without it shitting the bed on the deployment step.

**Comment by jcvalerio** [comment]
> 
> @jcvalerio Sorry, did you manage to deploy a NX repo to Amplify? How did you manage that? I can't get it to deploy without it shitting the bed on the deployment step.

Hi! @Rafcin !!

👉  Currently, using  `@aws-amplify/cli` = 5.1.0 and `@nrwl/cli` = 2.5.8 the issue is gone.

When that issue appeared the workaround applied was:

Verify into the bash file if the exit code was different than zero, then, force the exit in the bash file.

```bash
#!/usr/bin/env bash
set -Eeuxo pipefail


  npm run affected:test -- --base=${REVISION} --head=${AWS_COMMIT_ID} --parallel
  exitCode=$?
  if [ ${exitCode} -ne 0 ]; then exit 1; fi


  npm run affected:e2e -- --base=${REVISION} --head=${AWS_COMMIT_ID} --headless --parallel ${CYPRESS_RECORD_KEY}
  exitCode=$?
  if [ ${exitCode} -ne 0 ]; then exit 1; fi

```

Let me know if this help you or which are the versions you are using.
Regards

**Comment by Rafcin** [comment]
> 
> > 
> > @jcvalerio Sorry, did you manage to deploy a NX repo to Amplify? How did you manage that? I can't get it to deploy without it shitting the bed on the deployment step.
> 
> Hi! @Rafcin !!
> 
> 👉  Currently, using  `@aws-amplify/cli` = 5.1.0 and `@nrwl/cli` = 2.5.8 the issue is gone.
> 
> When that issue appeared the workaround applied was:
> 
> Verify into the bash file if the exit code was different than zero, then, force the exit in the bash file.
> 
> ```bash
> #!/usr/bin/env bash
> set -Eeuxo pipefail
> 
> 
>   npm run affected:test -- --base=${REVISION} --head=${AWS_COMMIT_ID} --parallel
>   exitCode=$?
>   if [ ${exitCode} -ne 0 ]; then exit 1; fi
> 
> 
>   npm run affected:e2e -- --base=${REVISION} --head=${AWS_COMMIT_ID} --headless --parallel ${CYPRESS_RECORD_KEY}
>   exitCode=$?
>   if [ ${exitCode} -ne 0 ]; then exit 1; fi
> 
> ```
> 
> Let me know if this help you or which are the versions you are using.
> Regards

@jcvalerio Thanks for the info! I'm actually more confused on how you've been able to deploy the app at all. I'm using Next12 and NX for my app, and I can't even deploy.

The Amplify team say it's an artifact issue, although they have no solution at the moment. 

How were you able to deploy to Amplify without running into build issues? Amplify always runs the build command even if you run NX build and also Serverless doesn't want to play nice with NX.

Your the only person I've heard of using NX and successfully deploying to Amplify so I'm extremely curious!!!

**Comment by jcvalerio** [comment]
> 
> @jcvalerio Thanks for the info! I'm actually more confused on how you've been able to deploy the app at all. I'm using Next12 and NX for my app, and I can't even deploy.
> 
> The Amplify team say it's an artifact issue, although they have no solution at the moment.
> 
> How were you able to deploy to Amplify without running into build issues? Amplify always runs the build command even if you run NX build and also Serverless doesn't want to play nice with NX.
> 
> Your the only person I've heard of using NX and successfully deploying to Amplify so I'm extremely curious!!!

Ok,

Sometimes the Amplify Console failed with no reason( at least clear for us 😄  ).
We faced artifact issues issues, like 

- the size of the directory is more than X mb check [Amplify console build successful but fails to move to deploy](https://github.com/aws-amplify/amplify-console/issues/41)
- the number of files are bigger than X


So try using a single directory that you know has only one file for example, just to see the build completes successfully.

```yml
frontend:
  artifacts:
    baseDirectory: dist/apps/cloud
    files:
      - '**/*'

  cache:
    paths:
      - dist/apps/cloud/**/*

test:

  artifacts:
    baseDirectory: dist/cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*'

```

If that works, so you can dig more if you build is bigger than the limits or by the number of files.
Sometimes, people didn't use the base directory and AWS Amplify console tries to store node_modules and that fires the issue.


Let me know if that helps or we can explore other options.

👍

**Comment by Rafcin** [comment]
@jcvalerio 

I heard about the size issues but it's nothing I ever encountered. My original issues when deploying where Sentry and the rust compiler caused issues, but now the Amplify staff say npx serverless terminates without reason and later they said it was an artifacts issue.

I've tried everything from copying the .next folder into the package, I have pkg jsons in the apps to trick the build settings into using SSR and all that fun stuff.

Based on that path Im guessing your using a different framework right?

**Comment by jcvalerio** [comment]
@Rafcin 

Yes, we deploy a backend with amplify/cli, other things with serverless framework and the front-end is a React SPA

If you want share the amplify.yml  by email and I will take a look.

**Comment by Rafcin** [comment]
@jcvalerio I'd really appreciate that! I'll send you an invite, it might be easier + one of the issues I opened.
https://github.com/aws-amplify/amplify-console/issues/2377

**Comment by msabramo** [comment]
I am running into this same issue. My builds work fine on my Mac laptop, but when I try to run them on a Ubuntu 20.04.02 Linux VM for CI, the build command does nothing and exits with a 0 and no output:

```
$ npx nx build backdrop
$ echo $?
0
```

I've added some `console.log` statements to `node_modules/@nrwl/workspace/src/command-line/run-one.js` and it seems to not get past this line in the `runOne` function:

```js
const projectGraph = yield project_graph_1.createProjectGraphAsync();
```

In more detail, here's the modified code I have:

```js
        yield connect_to_nx_cloud_1.connectToNxCloudUsingScan(nxArgs.scan);
            console.log('*** About to call project_graph_1.createProjectGraphAsync()');
        const projectGraph = yield project_graph_1.createProjectGraphAsync();
            console.log('*** project_graph_1.createProjectGraphAsync() returned projectGraph = ', projectGraph);
        const { projects, projectsMap } = getProjects(projectGraph, opts.project);
```

and the output with this code:

```
$ npx nx build backdrop
*** About to call project_graph_1.createProjectGraphAsync()
```

Digging in further, if I update `node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js` as follows:

```js
function createProjectGraphAsync(projectGraphVersion = '5.0') {
    return tslib_1.__awaiter(this, void 0, void 0, function* () {
        /**
         * Using the daemon is currently an undocumented, opt-in feature while we build out its capabilities.
         * If the environment variable is not set to true, fallback to using the existing in-process logic.
         */
console.log('*** I am in createProjectGraphAsync - 1');
        if (process.env.NX_DAEMON !== 'true') {
console.log('*** I am in createProjectGraphAsync - 2');
            return projectGraphAdapter('5.0', projectGraphVersion, yield build_project_graph_1.buildProjectGraph());
        }
console.log('*** I am in createProjectGraphAsync - 3');
        const daemonClient = require('./daemon/client/client');
console.log('*** I am in createProjectGraphAsync - 4');
        if (!(yield daemonClient.isServerAvailable())) {
console.log('*** I am in createProjectGraphAsync - 5');
            yield daemonClient.startInBackground();
        }
console.log('*** I am in createProjectGraphAsync - 6');
        return projectGraphAdapter('5.0', projectGraphVersion, daemonClient.getProjectGraphFromServer());
    });
}
```

then I get this output:

```
jenkins@or1010051147177:/apps/slave/workspace/lied-ml_sail-ui_ethos-k8s-deploy$ npx nx build backdrop
*** About to call project_graph_1.createProjectGraphAsync()
*** I am in createProjectGraphAsync - 1
*** I am in createProjectGraphAsync - 2
```

so that suggests that the problem occurs while executing this line:

```
return projectGraphAdapter('5.0', projectGraphVersion, yield build_project_graph_1.buildProjectGraph());
```

Even more specifically, I can break the code down a bit to figure out whether the problem is in `buildProjectGraph` or `projectGraphAdapter`:

```js
        if (process.env.NX_DAEMON !== 'true') {
console.log('*** I am in createProjectGraphAsync - 2');
                const projectGraphForDebugging = yield build_project_graph_1.buildProjectGraph();
console.log('*** I am in createProjectGraphAsync - 2.5 - projectGraphForDebugging = ', projectGraphForDebugging);
            return projectGraphAdapter('5.0', projectGraphVersion, yield build_project_graph_1.buildProjectGraph());
        }
```

and the result is:

```
$ npx nx build backdrop
*** About to call project_graph_1.createProjectGraphAsync()
*** I am in createProjectGraphAsync - 1
*** I am in createProjectGraphAsync - 2
```

so I think the problem is when calling `build_project_graph_1.buildProjectGraph()`.

**Comment by msabramo** [comment]
I also get similar output with `npx nx dep-graph`:

```
jenkins@or1010051147177:/apps/slave/workspace/lied-ml_sail-ui_ethos-k8s-deploy$ npx nx dep-graph
*** I am in createProjectGraphAsync - 1
*** I am in createProjectGraphAsync - 2
```

**Comment by msabramo** [comment]
If I set `export NX_DAEMON=true`, then it seems to get past this point:

```
$ npx nx build backdrop
*** About to call project_graph_1.createProjectGraphAsync()
*** I am in createProjectGraphAsync - 1
*** I am in createProjectGraphAsync - 3
*** I am in createProjectGraphAsync - 4
*** I am in createProjectGraphAsync - 6
```

but then gets stuck?

**Comment by msabramo** [comment]
I also tried `nx reset` and that didn't seem to help.

```
$ npx nx reset

>  NX   NOTE  Resetting the Nx workspace cache and stopping the Nx Daemon.

  This might take a few minutes.


>  NX  Daemon Server - Stopped


>  NX   SUCCESS  Successful reset the Nx workspace.

$ npx nx build backdrop
*** About to call project_graph_1.createProjectGraphAsync()
*** I am in createProjectGraphAsync - 1
*** I am in createProjectGraphAsync - 2
$ echo $?
0
```
