### ISSUE TITLE
Does the command "nx show projects" return a list separated by new line by default?

### ISSUE THREAD

**Issue by vcardins** [nrwl/nx#22219]
### Current Behavior

Maybe it's by design, but when I run the command `npx nx show projects --affected --type=app --base=$NX_BASE --head=$NX_HEAD` it returns a list of apps separated by new line "\n", however, I wished it was separated by comma. 

Current output:
app1
app2
app3

### Expected Behavior

As the expected behaviour, I'd like to (either by default), pass a parameter which sets the separation character.

As a workaround, I'm doing `$(npx nx show projects --affected --type=app --base=$NX_BASE --head=$NX_HEAD | tr '\n' ',' | sed 's/,$//')`

which outputs: app1,app2,app3

### Steps to Reproduce

1. Run the command `npx nx show projects --affected --type=app --base=$NX_BASE --head=$NX_HEAD`
2. Notice the output is separated by new line

### Nx Report

```shell
Node   : 20.11.1
OS     : darwin-arm64
yarn   : 1.22.19

nx                 : 18.0.6
@nx/js             : 18.0.6
@nx/jest           : 18.0.6
@nx/linter         : 18.0.6
@nx/eslint         : 18.0.6
@nx/workspace      : 18.0.6
@nx/devkit         : 18.0.6
@nx/eslint-plugin  : 18.0.6
@nx/playwright     : 18.0.6
@nx/react          : 18.0.6
@nrwl/tao          : 18.0.6
@nx/web            : 18.0.6
@nx/webpack        : 18.0.6
typescript         : 5.3.3
```

### Package Manager Version

1.22.1

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Would you like to add a `--sep` option for `nx show` which would be used in that case? It would have no effect when printing `json` or using the `--web` option.

**Comment by vcardins** [comment]
@FrozenPandaz Not sure I understand you. Do you mean something like
`npx nx show projects --affected --type=app --sep ","` it didn't work

**Comment by FrozenPandaz** [comment]
Sorry, I was unclear.

There currently is no way to change the separator used. However, if you would like to add the feature, it would be a `--sep` flag. A PR would be welcome :+1:
