### ISSUE TITLE
cache miss because of npmDependencies on nx reset

### ISSUE THREAD

**Issue by robertIsaac** [nrwl/nx#22248]
### Current Behavior

nx lint has negative cache miss if the npm changed
it seems nx cache add the new dependencies incorrectly in the cache if the Daemon Server is running and you must reset it everytime you change branch or dependency

### Expected Behavior

nx to have deterministic behavior, same source should always give cache hit

### Steps to Reproduce

1. in any existing repo run `npm i jsonc-eslint-parser` and use that parser in your eslint configuration
2. run `nx lint`
3. run `nx reset`
4. run `nx lint`

### Nx Report

```shell
Node   : 20.11.0
   OS     : win32-x64
   npm    : 10.4.0
   
   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/jest           : 18.0.4
   @nx/linter         : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/workspace      : 18.0.4
   @nx/angular        : 18.0.4
   @nx/cypress        : 18.0.4
   @nx/devkit         : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nx/nest           : 18.0.4
   @nx/node           : 18.0.4
   @nrwl/tao          : 18.0.4
   @nx/web            : 18.0.4
   @nx/webpack        : 18.0.4
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   ng-mocks : 14.12.1
```

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

![image](https://github.com/nrwl/nx/assets/14242054/549a945f-130a-4d5a-b68f-38f5765a1a56)

**Comment by MaxKless** [comment]
Hey! Thanks for the report.
I haven't been able to get to this issue yet but it's on my list and I'll try to reproduce & fix it ASAP :)

**Comment by robertIsaac** [comment]
this has been fixed by https://github.com/nrwl/nx/pull/28024
