### ISSUE TITLE
x-prompt multiselect should select hovered option on enter if no selection is made

### ISSUE THREAD

**Issue by man-trackunit** [nrwl/nx#22257]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
x-prompt multiselect should select the currently hovered option when pressing enter if no selection is made. Maybe optional.

## Motivation
9/10 times when I click through a prompt with multiselect, especially if placed next to simple selects, I end up not selecting anything and have to start over when faced with a multiselect.

## Suggested Implementation
Select the currently hovered option on enter if no selection is made.

**Comment by FrozenPandaz** [comment]
This would make it very difficult to not select anything... Is it perhaps unclear that what you are hovering is not selected? Any suggestions on how we can make it more clear?

**Comment by man-trackunit** [comment]
Good point with not being able to proceed without making a selection. I guess the first item could be a default `none` option but I see how that complicates things (although I'd still like it).

I guess having the greyed out checkmark look more like an actual checkbox would be helpful too. 🤔
![CleanShot 2024-03-18 at 08 07 34@2x](https://github.com/nrwl/nx/assets/79450095/3473ff2b-91b9-4d81-9f02-5fd065b0d67e)
![Artboard](https://github.com/nrwl/nx/assets/79450095/dc9388f7-f371-4493-a14c-9c75faa431c4)

**Comment by AgentEnder** [comment]
If you'd like to contribute the change, you can also change the indicators for the multiselects. Enquirer's typings unfortunately don't allow for the props as needed so you'll have to cast. The selects would look something like this:

```typescript
const { value } = await prompt</*...*/>({
      type: 'multiselect',
      name: 'value ',
      message: '...',
      choices: [
		// ...
      ],
      footer: 'Press <space> to select, <return> to submit.',
      indicator(state, choice) {
        return choice.enabled ? chalk.green('☑') : chalk.dim('☐');
      },
    } as any);
```

**Comment by man-trackunit** [comment]
Alright, thanks for the update. I'll give it a shot on next non-crunch day 👌
