### ISSUE TITLE
module federation ssr devRemotes cause port in used error

### ISSUE THREAD

**Issue by recover758126** [nrwl/nx#22256]
### Current Behavior

When I seve the host pass the args --devRemotes will cause address in use.  Then my server cannot bootstrap.
![CleanShot 2024-03-11 at 17 37 50](https://github.com/nrwl/nx/assets/30303767/f7181ae1-174e-4adb-a06b-62ff389bb237)

### Expected Behavior

This bug should be fixed.

### Steps to Reproduce

 Just follow the document for react.
 https://nx.dev/recipes/react/module-federation-with-ssr#setup-module-federation-with-ssr-for-angular-and-react

### Nx Report

```shell
Node   : 16.13.1
OS     : darwin-arm64
npm    : 8.1.2

nx                 : 18.0.8
@nx/js             : 18.0.8
@nx/jest           : 18.0.8
@nx/linter         : 18.0.8
@nx/eslint         : 18.0.8
@nx/workspace      : 18.0.8
@nx/cypress        : 18.0.8
@nx/devkit         : 18.0.8
@nx/eslint-plugin  : 18.0.8
@nx/react          : 18.0.8
@nrwl/tao          : 18.0.8
@nx/web            : 18.0.8
@nx/webpack        : 18.0.8
typescript         : 5.3.3
```

### Package Manager Version

npm 8.1.2

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
We identified the issue and are discussing about how we should address it.
For now i'll assign this to @Coly010 to take a look.

**Comment by Coly010** [comment]
Fixed by https://github.com/nrwl/nx/pull/27411 and https://github.com/nrwl/nx/pull/27345
