### ISSUE TITLE
404 (Not Found) error for any page

### ISSUE THREAD

**Issue by IgorSelin** [nrwl/nx#22271]
### Current Behavior

1. Navigate to any page(not root page '/')
2. Check this error
3. Although the pages load normally and this error does not affect the functionality in any way, there is still this error

### Expected Behavior

1. Navigate to any page(not root page '/')
2. There is no 404 (Not Found) error 

### Steps to Reproduce

1. Navigate to any page(not root page '/')
2. Check this error
3. Although the pages load normally and this error does not affect the functionality in any way, there is still this error
<img width="813" alt="Screenshot 2024-03-26 at 3 59 45 PM" src="https://github.com/nrwl/nx/assets/67583045/6cadf3cd-199e-4bcd-b5bf-0663b71c0461">

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 21.7.0
   OS     : darwin-x64
   npm    : 10.5.0
   
   nx                 : 17.3.0
   @nx/js             : 17.3.0
   @nx/jest           : 17.3.0
   @nx/linter         : 17.3.0
   @nx/eslint         : 17.3.0
   @nx/workspace      : 17.3.0
   @nx/devkit         : 17.3.0
   @nx/eslint-plugin  : 17.3.0
   @nx/react          : 17.3.0
   @nrwl/tao          : 17.3.0
   @nx/web            : 17.3.0
   @nx/webpack        : 17.3.0
   typescript         : 5.3.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

My webpack.config.js:

`const { composePlugins, withNx } = require('@nx/webpack');
const { withReact } = require('@nx/react');
const { withModuleFederation } = require('@nx/react/module-federation');
const baseConfig = require('./module-federation.config');
const coreLibraries = new Set(['react', 'react-dom', 'react-router-dom']);
const config = {
  ...baseConfig,
  shared: (libraryName, defaultConfig) => {
    if (coreLibraries.has(libraryName)) {
      return {
        ...defaultConfig,
        requiredVersion: '>=0.0.1',
        strictVersion: false,
        eager: true,
      };
    }
    // Returning false means the library is not shared.
    return false;
  },
};

// Nx plugins for webpack to build config object from Nx options and context.
module.exports = composePlugins(
  withNx({ sourceMap: false }),
  withReact(),
  withModuleFederation(config)
);
`

**Comment by jaysoo** [comment]
@IgorSelin I'm not able to repro in 17.3.0, do you have a repo you can link to?

Also, check with the latest 18.1.3 version.

**Comment by IgorSelin** [comment]
@jaysoo we can check this issue on deployed project. Everything is okay locally. But yeah, I'll check it with the latest verion

**Comment by jaysoo** [comment]
@IgorSelin The deployment isn't controlled by Nx, and it's up to you to configure deep-links correctly.

For example, if you use `.htaccess` then you can do something like

```
<ifModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule (.*) /index.html [QSA,L]
</ifModule>
```

Or with nginx:

```
server {
      listen 80;
      listen [::]:80;
      server_name localhost;

      location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html =404;
      }
}
```

**Comment by jaysoo** [comment]
Closing this as it isn't an Nx issue.
