### ISSUE TITLE
@nx/cypress:cypress returns exit code 0 on cancelled tests

### ISSUE THREAD

**Issue by jesse-humi** [nrwl/nx#22289]
### Current Behavior

When using [Cypress' Run Cancellation setting](https://docs.cypress.io/guides/cloud/smart-orchestration/run-cancellation), a failed e2e test will cancel all other tests running in parallel to avoid wasting time and resources. The matrix that contains the failed test will return a non-zero exit code from Nx as expected. However, all of the parallel runs that have been cancelled as well, return a success exit code despite Cypress returning non-zero.

Matrix containing failed test ✅ 
![image](https://github.com/nrwl/nx/assets/104863080/583bf33c-3ad4-41cd-acc9-572505cd0813)

Matrix skipped as a result of the failing test ❌ 
![image](https://github.com/nrwl/nx/assets/104863080/ddeda467-a651-4f8e-8995-62dab8f8ea92)

### Expected Behavior

When Cypress returns a non-zero exit code, Nx should also return a non-zero exit code

### GitHub Repo

[Cypress' Run Cancellation setting](https://docs.cypress.io/guides/cloud/smart-orchestration/run-cancellation) is a premium feature and therefore can't be made into a reproduceable repo

### Steps to Reproduce

1. Create a repo that uses @nx/cypress:cypress to run at least two e2e tests
2. Connect your repo to [Cypress Cloud](https://docs.cypress.io/guides/cloud/getting-started) and enable the [Run Cancellation setting](https://docs.cypress.io/guides/cloud/smart-orchestration/run-cancellation)
3. Enable [parallelization](https://docs.cypress.io/guides/cloud/smart-orchestration/parallelization#Turning-on-parallelization) to split the e2e test suite
4. Have 1 test fail while the rest pass
5. Observe the return code from Nx

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.11.1
   OS     : linux-x64
   yarn   : 3.5.0
   
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/angular        : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/storybook      : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   @auth0/auth0-angular : 2.2.1
   @compodoc/compodoc   : 1.1.19
   @cypress/schematic   : 2.5.1
   @storybook/angular   : 7.6.10
   angular-calendar     : 0.31.0
   rxjs                 : 6.6.7
   ---------------------------------------
   Local workspace plugins:
   	 merge-translations
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this and apologies for the delayed response!

Have you updated your Nx version since you reported this? Just to make sure the reported information is still accurate and the issue still occurs.

If that's the case, could you please provide a repo where the issue can be reproduced? It'll be better if it uses a recent Nx version. I'll set the Cypress `projectId` in the config and use the appropriate key of my test account, so don't worry about that part.
