### ISSUE TITLE
Bun.js Support

### ISSUE THREAD

**Issue by laynef** [nrwl/nx#22283]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

- Please support Bun.js as a package manager and fix the NX platform runner

## Motivation

- Bun.js runs x17 faster than pnpm and x37 than yarn and npm

## Problem

- Fix  NX   Missing Platform Dependency

<img width="1082" alt="Screenshot 2024-03-12 at 10 18 50 AM" src="https://github.com/nrwl/nx/assets/14255968/91161ce7-562a-4336-8773-4274866da238">

## Solution

<img width="1016" alt="Screenshot 2024-03-19 at 6 24 12 PM" src="https://github.com/nrwl/nx/assets/14255968/713fa548-a81f-4a78-9873-7f3f959e709e">

<img width="1060" alt="Screenshot 2024-03-19 at 6 23 55 PM" src="https://github.com/nrwl/nx/assets/14255968/9c07e2c7-9c48-4083-92cf-5066c18e0522">

**Comment by laynef** [comment]
I added this PR: https://github.com/nrwl/nx/pull/22345

Please take a look.

**Comment by laynef** [comment]
Please merge.

PR: https://github.com/nrwl/nx/pull/22402

**Comment by LeOndaz** [comment]
Bump, urgent

**Comment by Jordan-Hall** [comment]
#22602
