### ISSUE TITLE
NPM 5.0 required even if using yarn?

### ISSUE THREAD

**Issue by maxime1992** [nrwl/nx#223]
From the getting started guide: https://nrwl.io/nx/guide-getting-started

```
npm install -g @nrwl/schematics

or

yarn global add @nrwl/schematics

This makes the create-nx-workspace binary available at the terminal. So from anywhere on your local machine you can run the following to create a new Nx workspace:

create-nx-workspace myworkspace
```

When I run `create-nx-workspace myworkspace` I end up with:
> To create a workspace you must have NPM >= 5.0.0 installed.

But I don't care about npm as I'm using yarn.

**Comment by vsavkin** [comment]
Pass the --yarn flag (`create-nx-workspace myworkspace --yarn`), and everything should work without npm.
