### ISSUE TITLE
nx-agens link doesn't work

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#22307]
### Documentation issue
![image](https://github.com/nrwl/nx/assets/77624664/797ea422-03d3-453a-8ded-e89a165a3573)

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?
https://nx.dev/ci/features/nx-agents

### Additional context or description

From the home page, this link leads to 404
![image](https://github.com/nrwl/nx/assets/77624664/5337fc11-ab9c-45e0-a543-597bbbce6c21)

**Comment by StalkAltan** [comment]
Thanks for reporting, this was fixed in #22314
