### ISSUE TITLE
HMR initializing and executing, but not painting in browser

### ISSUE THREAD

**Issue by imadeyourday** [nrwl/nx#22300]
### Current Behavior

When HMR is enabled in my serve command and also enabled via my webpack config, it initializes in the console for the browser, it picks up when a change occurs after save, and it attempts to hot update (even stating that it HAS updated module and that the app is up to date), but it NEVER paints the change without a hard refresh.

### Expected Behavior

I would expect hmr to paint the change in the browser.

### GitHub Repo

Repo is private - can curate/share file contents at request

### Steps to Reproduce

**1. Serve & load the application in a browser**

**2. HMR initializes and the app is rendered.**
![hmr-pre-change](https://github.com/nrwl/nx/assets/13092425/9a3a679d-10ad-48b9-9b2c-10fbb9f76272)

**3. A change is made, the console detects the change (from the correct file), the console attempts an update then states that the browser IS updated, but the browser is never painted with the change.**
![hmr-post-change](https://github.com/nrwl/nx/assets/13092425/24ecfaa5-5763-4aaf-b342-2f3e9e794bf8)

**NOTE:** the chunkloaderror is clearly a potential source for the issue, but i haven't been able to find documentation or to trace that back to the root cause of the issue. That error also does not occur every time hmr gets triggered (typically only the first time after the page has been served), but the app NEVER re-paints.

Here is a copy of that error for copy pasta purposes:

```VM13:1  [HMR] Update failed: ChunkLoadError: Loading hot update chunk polyfills failed.
(missing: http://localhost:4200/polyfills.a8d843f133afff7c.hot-update.mjs)
    at http://localhost:4200/polyfills.17d3a0dd8748db5d.js:72328:25
    at nrWrapper (<anonymous>:1:29329)
    at new Promise (<anonymous>)
    at new r (<anonymous>:1:8666)
    at loadUpdateChunk (http://localhost:4200/polyfills.17d3a0dd8748db5d.js:72323:19)
    at http://localhost:4200/polyfills.17d3a0dd8748db5d.js:72783:28
    at Array.forEach (<anonymous>)
    at __webpack_require__.hmrC.jsonp (http://localhost:4200/polyfills.17d3a0dd8748db5d.js:72778:21)
    at http://localhost:4200/polyfills.17d3a0dd8748db5d.js:71864:46
    at Array.reduce (<anonymous>)
```

### Nx Report

```shell
Node   : 18.13.0
OS     : win32-x64
pnpm   : 7.26.2

nx                 : 18.0.8
@nx/js             : 18.0.8
@nx/jest           : 18.0.8
@nx/eslint         : 18.0.8
@nx/workspace      : 18.0.8
@nx/cypress        : 18.0.8
@nx/devkit         : 18.0.8
@nx/eslint-plugin  : 18.0.8
@nx/node           : 18.0.8
@nx/plugin         : 18.0.8
@nx/react          : 18.0.8
@nx/rollup         : 18.0.8
@nrwl/tao          : 18.0.8
@nx/vite           : 18.0.8
@nx/web            : 18.0.8
@nx/webpack        : 18.0.8
typescript         : 4.8.4
---------------------------------------
Local workspace plugins:
         @coxauto-ui/custom-executors
```

### Package Manager Version

pnpm 7.26.2

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

**Config for serve command my application project.json**
```"serve": {
      "executor": "@nx/react:module-federation-dev-server",
      "options": {
        "buildTarget": "cxm:build",
        "devRemotes": ["customer", "communications", "tenant-admin"],
        "hmr": true,
        "liveReload": false,
        "port": 4200,
        "parallel": 4
      },
      "configurations": {
        "development": {
          "buildTarget": "cxm:build:development"
        },
        "production": {
          "buildTarget": "cxm:build:production",
          "hmr": false
        }
      }
    },
```

**Webpack config:**
```const { composePlugins, withNx } = require("@nx/webpack");
const { withReact } = require("@nx/react");
const { merge } = require("webpack-merge");
// Module Federation Enablement
const withModuleFederation = require("@nx/react/module-federation");
const moduleFederationConfig = require("./module-federation.config");
const {
  setSharedLibrariesForModuleFederation
} = require("../../module-federation.config");

module.exports = composePlugins(
  withNx(),
  withReact(),
  withModuleFederation(
    setSharedLibrariesForModuleFederation(moduleFederationConfig)
  ),
  (config, context) => {
    return merge(config, {
      node: { global: true },
      devServer: {
        hot: true
      },
      resolve: {
        extensions: [".tsx", ".ts", ".js"],
        fallback: {
          stream: require.resolve("stream-browserify"),
          http: require.resolve("stream-http"),
          https: require.resolve("https-browserify"),
          zlib: require.resolve("browserify-zlib")
        },
        mainFields: ["browser", "module", "main"]
      },
      watchOptions: {
        ignored: "**/node_modules/",
        aggregateTimeout: 600,
        poll: 1000
      }
    });
  }
);
```

**Comment by Coly010** [comment]
Hi @imadeyourday !

Sorry for the time it's taken to get back to you on this.

I've found a workaround that you can implement right now, and I have a fix planned for Nx itself.

in the `webpack.config` for your HOST application, and _only_ your host, if you add

```js
(config) => {
    if(config.mode === 'development') {
    config.optimization ??= {};
    config.optimization.runtimeChunk = 'single';
    return config;
    }
  }
```
to `composePlugins()`

This should fix HMR for you.

you also should not need to manually set `devServer: { hot: true }` as this will be set by `withReact()`.

**Comment by imadeyourday** [comment]
This worked. Thanks so much!
