### ISSUE TITLE
Nx 18.0.6 cache doesn't trigger build on files changed under .gitignore

### ISSUE THREAD

**Issue by rbirkgit** [nrwl/nx#22301]
### Current Behavior

Modifying a file in my src/assets/docs folder is not causing a new build. Cache is being used, even though I have changes. This because it has a .gitignore. The files in this folder are generated.

Modifying other fiiles in my src/assets folder does cause a new build.

### Expected Behavior

Expect a new build to happen for .gitignored files that changed

### Steps to Reproduce

Add a folder to .gitIgnore. Modify a file in that folder. A new build will use cache.

### Nx Report

```shell
Node   : 18.19.0
OS     : win32-x64
yarn   : 4.0.1

nx                 : 18.0.6
@nx/js             : 18.0.6
@nx/jest           : 18.0.6
@nx/linter         : 18.0.6
@nx/eslint         : 18.0.6
@nx/workspace      : 18.0.6
@nx/angular        : 18.0.6
@nx/cypress        : 18.0.6
@nx/devkit         : 18.0.6
@nx/eslint-plugin  : 18.0.6
@nrwl/tao          : 18.0.6
@nx/web            : 18.0.6
@nx/webpack        : 18.0.6
typescript         : 5.1.6
---------------------------------------
Community plugins:
ng-mocks : 14.12.1
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Nx.json
```
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build"],
      "inputs": ["production", "^production"],
      "cache": true
    },
```

.gitignore
```
/apps/cloud-ui/src/assets/docs/*
```

**Comment by FrozenPandaz** [comment]
By default, Nx does not hash files that are gitignored by default.

If you would like Nx to hash gitignored files, un-ignore it from Nx in `.nxignore`:

```
!/apps/cloud-ui/src/assets/docs/*
```

**Comment by rbirkgit** [comment]
I will try that. Sounds simple enough. Thanks!
