### ISSUE TITLE
Best place for storing images for libs ? 

### ISSUE THREAD

**Issue by iangregsondev** [nrwl/nx#2230]
- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

Hi,

I have created a react app with multiple libs - its based off a angular.json workspace. Under apps there is a assets folder - what should this be used for ? I thought this was for standard fonts and any global - added to main / app.tsx

Where are the images for each library supposed to be stored ? 

Should I create an assets folder under each lib ?

If these are created in each lib, should i be extending and adding paths to the libs for app under angular .json i.e

```
            "assets": [
              "apps/web/src/favicon.ico",
              "apps/web/src/assets",
              "../../libs/etc... // Kind of seems wrong too 
            ],
```

from the lib, I can't get access to the app/assets folder, i could place a tsconfig PATH on there but it seems kind of wrong that a lib is calling back into an app

I really love some feedback - what others are doing, whats the best place for storing images (or assets) that are specific to a library

The mono repo book doesn't go into it, unless I am missing something

**Comment by FrozenPandaz** [comment]
Good question.

The [nx-examples repo](https://github.com/nrwl/nx-examples/blob/master/angular.json#L164) has an example of storing shared assets in a lib. You can have app specific assets in the app assets folder such as maybe a specific logo or favicon just for that app. If assets are shared between different apps, you can create a lib with no typescript or anything and put them there. Unfortunately, you have to duplicate the assets config for each app which uses them but at least there is 1 copy. 

Also note that nx won't find this dependency on it's own so we can add an [`implicitDependency`](https://github.com/nrwl/nx-examples/blob/master/nx.json#L20) to make Nx aware that those apps  should be rebuilt when those assets change.

Hope that helps! :)

**Comment by iangregsondev** [comment]
Great stuff, thanks for the info with regards to implicitDependency

**Comment by barryajones** [comment]
Here's the updated link for the nx-examples repo https://github.com/nrwl/nx-examples/blob/master/workspace.json#L49-L59
