### ISSUE TITLE
@nrwl/workspace run-commands throws "should have required property 'class'

### ISSUE THREAD

**Issue by iangregsondev** [nrwl/nx#2232]
- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Should run commands

## Current Behavior

Added 

```
        "compodoc": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "commands": [
              {
                "command": "npx compodoc -p apps/my-app/tsconfig.app.json"
              }
            ]
          }
        },
```

as per https://connect.nrwl.io/app/cookbook/1BarpEG6zfxCv4evBvJSWi

But running this outputs

```
Schema validation failed with the following errors:
  Data path ".builders['run-commands']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['run-commands']" should have required property 'class'.
```

my package json

```
  "dependencies": {
    "@nrwl/workspace": "^8.9.0",
```

**Comment by FrozenPandaz** [comment]
Hi @iangregsondev 

What version of the Angular CLI are you on?

`@nrwl/workspace@^8.0.0` requires `@angular/cli@8.0.0`

**Comment by iangregsondev** [comment]
thanks @FrozenPandaz , yep I have a workspace of 7.x and cli of 7.x

Updated and it seems to work

Thanks
