### ISSUE TITLE
Add documentation how to create a custom inferred tasks plugin

### ISSUE THREAD

**Issue by TNAJanssen** [nrwl/nx#22325]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [X] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

n/a

### Additional context or description

I want to create a custom tsc check plugin using inferred tasks, but there is no documentation on how to do this.

**Comment by TNAJanssen** [comment]
When following this documentation:
https://nx.dev/extending-nx/recipes/project-graph-plugins

I get the following error:
 Inner Error: Error: Jest: Failed to parse the TypeScript config file libs/xxx/jest.config.ts
  TSError: ⨯ Unable to compile TypeScript:
libs/xxx/jest.config.ts(11,7): error TS2451: Cannot redeclare block-scoped variable '_default'.

While i didn't add anything:
import { CreateNodes, CreateNodesContext, readJsonFile } from '@nx/devkit';
import { dirname } from 'path';

export const createNodes: CreateNodes = [
  '**/project.json',
  (projectConfigurationFile: string, opts, context: CreateNodesContext) => {
    const projectConfiguration = readJsonFile(projectConfigurationFile);
    const root = dirname(projectConfigurationFile);

    return {
      projects: {
        [root]: projectConfiguration,
      },
    };
  },
];

**Comment by epliXs** [comment]
I have encoutered same error, and i am not certain if this has to do with me making making a mistake in piecing together information in guides or there is an issue with jest plugin.

Here is barebones reproduction repo: https://github.com/epliXs/nx-plugin-debug

The error is intermittent, the most consitent way of reproducing it is:
* `npx nx reset`
* `npx nx run foobar-a:echo`

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Could you please expand on what piece of extra information you feel is needed or would like to see in the https://nx.dev/extending-nx/recipes/project-graph-plugins recipe? We recently [added some extra information](https://github.com/nrwl/nx/pull/22748) to that page.

The error reported is unrelated to the plugin you've created. It's an error thrown from the `@nx/jest/plugin`, and that's a separate issue. Please let's keep this issue focused on the documentation improvements you think are needed. If the issue's purpose was actually to get help on how to address that error, we can update the description and focus on that instead. Otherwise, feel free to create a separate issue for the Jest plugin error.

**Comment by a88zach** [comment]
I'm getting this exact same error when I add a custom plugin.  
- Without the custom plugin registered in nx.json, the jest plugin works as expected
- With the custom plugin registered and the jest plugin removed, the custom plugin works as expected
- With both the custom plugin registered and the jest plugin registered, this error is throw for every project
```
The "@nx/jest/plugin" plugin threw an error while creating nodes from libs/weight-algorithm/jest.config.ts:
    Error: Jest: Failed to parse the TypeScript config file /Users/zachtindall/Documents/repos/client_wastewizer_com/libs/weight-algorithm/jest.config.ts
      TSError: ⨯ Unable to compile TypeScript:
    libs/weight-algorithm/jest.config.ts(11,7): error TS2451: Cannot redeclare block-scoped variable '_default'.
    
        at readConfigFileAndSetRootDir (/Users/zachtindall/Documents/repos/client_wastewizer_com/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:116:13)
        at async readInitialOptions (/Users/zachtindall/Documents/repos/client_wastewizer_com/node_modules/jest-config/build/index.js:403:13)
        at async readConfig (/Users/zachtindall/Documents/repos/client_wastewizer_com/node_modules/jest-config/build/index.js:147:48)
        at async buildJestTargets (/Users/zachtindall/Documents/repos/client_wastewizer_com/node_modules/@nx/jest/src/plugins/plugin.js:78:20)
        at async Array.exports.createNodes (/Users/zachtindall/Documents/repos/client_wastewizer_com/node_modules/@nx/jest/src/plugins/plugin.js:60:32)
        at async /Users/zachtindall/Documents/repos/client_wastewizer_com/node_modules/nx/src/project-graph/plugins/utils.js:49:27
        at async Promise.all (index 35)
        at async runCreateNodesInParallel (/Users/zachtindall/Documents/repos/client_wastewizer_com/node_modules/nx/src/project-graph/plugins/utils.js:66:5)
        at async Promise.all (index 3)
        at async processFilesAndCreateAndSerializeProjectGraph (/Users/zachtindall/Documents/repos/client_wastewizer_com/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:148:43)
```

Although this seems to be a problem with the jest plugin, the error only occurs when another custom plugin is registered in nx.json

I'm working on a repo to reproduce the issue, but have had no luck reproducing this issue yet on a fresh repo.  It's only occurring on my repo that was started with version 14 and has been consistently updated with each nx release

**Comment by a88zach** [comment]
@leosvelperez here is a a repo that demonstrates the error.  The steps to reproduce are laid out in the README.md

https://github.com/a88zach/crystal-bug

**Comment by a88zach** [comment]
Created https://github.com/nrwl/nx/issues/26245 for the issue with the jest plugin
