### ISSUE TITLE
Running nx commands yields Vite CJS API deprecation warning

### ISSUE THREAD

**Issue by kylebjordahl** [nrwl/nx#22336]
### Current Behavior

When running common `nx` commands (including `nx report`) with the vite plugin installed, a deprecation warning is emitted

### Expected Behavior

No extra deprecation warnings are emitted 

### Steps to Reproduce

1.

### Nx Report

```shell
➜  workspace: nx report
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

 NX   Report complete - copy this into the issue template

Node   : 20.11.1
OS     : linux-arm64
npm    : 10.2.4

nx                 : 18.0.7
@nx/js             : 18.0.7
@nx/jest           : 18.0.7
@nx/linter         : 18.0.7
@nx/eslint         : 18.0.7
@nx/workspace      : 18.0.7
@nx/cypress        : 18.0.7
@nx/devkit         : 18.0.7
@nx/eslint-plugin  : 18.0.7
@nx/plugin         : 18.0.7
@nx/react          : 18.0.7
@nx/remix          : 18.0.7
@nx/storybook      : 18.0.7
@nrwl/tao          : 18.0.7
@nx/vite           : 18.0.7
@nx/web            : 18.0.7
typescript         : 5.3.3
---------------------------------------
Community plugins:
@nxlv/python : 18.0.0
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [X] Other (Please specify)

### Additional Information

Running in an Ubuntu-based devcontainer on Apple Silicon

**Comment by Coly010** [comment]
NODE_ENV issue is a separate issue being tracked here: https://github.com/nrwl/nx/issues/22347

The deprecation warning can be removed by adding `"type": "module"` to the package.json of your project that uses `vite.config.ts`
