### ISSUE TITLE
`generateFiles` from @nx/devkit overwrites project.json template file

### ISSUE THREAD

**Issue by scottyschup** [nrwl/nx#22337]
### Current Behavior

I am creating a custom library generator that has all of my teams config files pre-configured as we need them. In my generator, I have a `project.json__tmpl__` file in my template files directory. However when I run the generator, the resulting `project.json` looks nothing like my template. It seems that `generateFiles` is overwriting my template version at some point in the process.

### Expected Behavior

`generateFiles` should not create a `project.json` if there is already one present after interpolating template files.

### Steps to Reproduce

1. Create a simple Nx generator.
2. Add `project.json__tmpl__` to the template files directory with some custom content that is different from a standard generated `project.json` file.
3. Run the generator.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : darwin-arm64
   pnpm   : 8.14.1
   
   nx (global)        : 18.0.3
   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/jest           : 18.0.4
   @nx/linter         : 18.0.4
   @nx/workspace      : 18.0.4
   @nx/cypress        : 18.0.4
   @nx/devkit         : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nx/plugin         : 18.0.4
   @nx/react          : 18.0.4
   @nx/storybook      : 18.0.4
   @nx/vite           : 18.0.4
   @nx/web            : 18.0.4
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   nx-stylelint : 17.1.4
   ---------------------------------------
   Local workspace plugins:
     @consumer-frontend/tools
```

### Package Manager Version

pnpm v8.14.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
What does the resulting `project.json` file look like? Could you create a minimal repo so we can easily reproduce the issue please?

**Comment by scottyschup** [comment]
Actually it looks like something else was happening as I can't reproduce the error in my own project anymore 🤦
