### ISSUE TITLE
@nx/workspace:remove >18.0.8 fails with `The "path" argument must be of type string. Received null`

### ISSUE THREAD

**Issue by matt-fff** [nrwl/nx#22346]
### Current Behavior

This appears to be a regression. Remove works in `@nx/workspace@18.0.8`, but consistently fails in `@nx/workspace@18.1.0` and above.

This series of commands succeeds:
```
npx -y create-nx-workspace@18.0.8 nx-rm-pass --preset=@monodon/rust
cd nx-rm-pass
npm install
npx nx g @monodon/rust:binary myapp
npx nx g rm myapp
```

The same commands with a version > 18.0.8 fails:
```
npx -y create-nx-workspace@18.1.0 nx-rm-fail --preset=@monodon/rust
cd nx-rm-fail
npm install
npx nx g @monodon/rust:binary myapp
npx nx g rm myapp
```

https://github.com/nrwl/nx/assets/8656127/49e84489-fb97-47ad-b34a-0d7041fde0a8

### Expected Behavior

Running `npx nx g rm myapp` under `@nx/workspace@18.1.*` should remove `myapp` from the workspace the same way that `@nx/workspace@18.0.8` does.

https://github.com/nrwl/nx/assets/8656127/d1cc23ce-56bc-4c92-b885-b10e9c5d2191

### GitHub Repo

https://github.com/matt-fff/nx-rm-fail

### Steps to Reproduce

You can use the commands in the "current behavior" section, but I know those are for Rust. Let's reproduce with a React monorepo to show that the issue is more widespread.

1. Create a new workspace at version 18.1.0 or above. You can use defaults for all the prompts
```
npx create-nx-workspace@18.1.1 react-monorepo --preset=react-monorepo
```

2. cd into the project
```
cd react-monorepo
```

3. Try to delete one of the default apps.
```
npx nx g rm react-monorepo-e2e
```

Output:
```
 NX  Generating @nx/workspace:remove
 NX   The "path" argument must be of type string. Received null

Pass --verbose to see the stacktrace.
```

4. (Optional) You can try adding a new project and remove that, so we know it's not specific to default projects.
```
npx nx g @nx/react:app inventory

npx nx g rm inventory-e2e
```

Output:
```
 NX  Generating @nx/workspace:remove
 NX   The "path" argument must be of type string. Received null

Pass --verbose to see the stacktrace.
```

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.10.0
OS     : linux-x64
npm    : 10.2.3

nx                 : 18.1.1
@nx/js             : 18.1.1
@nx/linter         : 18.1.1
@nx/eslint         : 18.1.1
@nx/workspace      : 18.1.1
@nx/cypress        : 18.1.1
@nx/devkit         : 18.1.1
@nx/eslint-plugin  : 18.1.1
@nx/react          : 18.1.1
@nrwl/tao          : 18.1.1
@nx/vite           : 18.1.1
@nx/web            : 18.1.1
typescript         : 5.3.3
```

### Failure Logs

```shell
$ npx nx g rm inventory-e2e --verbose

 NX  Generating @nx/workspace:remove


 NX   The "path" argument must be of type string. Received null


TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at validateString (node:internal/validators:162:11)
    at join (node:path:1175:7)
    at FsTree.normalize (/home/matt/Workspaces/scratch/react-monorepo/node_modules/nx/src/generators/tree.js:225:64)
    at FsTree.exists (/home/matt/Workspaces/scratch/react-monorepo/node_modules/nx/src/generators/tree.js:94:25)
    at updateJestConfig (/home/matt/Workspaces/scratch/react-monorepo/node_modules/@nx/workspace/src/generators/remove/lib/update-jest-config.js:41:15)
    at removeGenerator (/home/matt/Workspaces/scratch/react-monorepo/node_modules/@nx/workspace/src/generators/remove/remove.js:17:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/matt/Workspaces/scratch/react-monorepo/node_modules/nx/src/command-line/generate/generate.js:241:26
    at async handleErrors (/home/matt/Workspaces/scratch/react-monorepo/node_modules/nx/src/utils/params.js:9:16)
    at async Object.handler (/home/matt/Workspaces/scratch/react-monorepo/node_modules/nx/src/command-line/generate/command-object.js:13:22)
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by yrue** [comment]
I am experiencing the same issue at the same step.

Environment:
Operating System: macOS 14.4.1 (23E224)
Node.js Version: v20.8.0
@nx/workspace Version: 18.2.4

**Comment by mohamad-hesari** [comment]
I have experienced the same issue at the same step.

I changed this file in node_modules and the problem was solved.
node_modules/@nx/workspace/src/generators/remove/lib/update-jest-config.js:41:15
`if (!tree.exists(rootConfigPath) ||` to `if (!rootConfigPath || !tree.exists(rootConfigPath) ||`

**Comment by yrue** [comment]
Thank you, @mohamad-hesari, it works!

**Comment by MaxKless** [comment]
Hey thanks for providing the workaround @mohamad-hesari and thanks for the report @matt-fff :) 
It looks like this was the exact solution and has been fixed in https://github.com/nrwl/nx/pull/23328
