### ISSUE TITLE
Cannot find eslint or jest when running inferred targets for 18.1.1 (and 18.1.2)

### ISSUE THREAD

**Issue by atsjo** [nrwl/nx#22343]
### Current Behavior

cannot run inferred targets for eslint or jest, since eslint or jest command cannot be resolved.
fails with 'eslint' or 'jest' is not recognized as an internal or external command, operable program or batch file.

### Expected Behavior

can run inferred targets for eslint or jest as in 18.0.8

### Steps to Reproduce

1. update working 18.0.8 repo using eslint or jest inferred targets to 18.1.1
2. run eslint or jest for inferred target on any project

### Nx Report

```shell
Node   : 20.11.1
OS     : win32-x64
pnpm   : 8.15.4

nx                 : 18.1.1
@nx/js             : 18.1.1
@nx/jest           : 18.1.1
@nx/linter         : 18.1.1
@nx/workspace      : 18.1.1
@nx/angular        : 18.1.1
@nx/devkit         : 18.1.1
@nx/esbuild        : 18.1.1
@nx/eslint-plugin  : 18.1.1
@nrwl/tao          : 18.1.1
@nx/web            : 18.1.1
@nx/webpack        : 18.1.1
typescript         : 5.3.3
---------------------------------------
Community plugins:
angular-calendar : 0.31.0
```

### Failure Logs

```shell
nx run shared-all:lint

'eslint' is not recognized as an internal or external command, operable program or batch file.

OR

nx run shared-all:test

'jest' is not recognized as an internal or external command, operable program or batch file.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by MobliMic** [comment]
I'm having the same issue. Tried downgrading nx to 18.0.8 and now its running the targets just fine.

Started a brand new project today. Installed nx globally and was seeing this issue. I then ran the same targets using `npx nx lint [application]` and that seemed to run just fine. 

## nx report (not working)

```
Node   : 20.11.1
OS     : win32-x64
npm    : 10.2.4

nx (global)        : 18.1.1
nx                 : 18.1.1
@nx/js             : 18.1.1
@nx/jest           : 18.1.1
@nx/linter         : 18.1.1
@nx/eslint         : 18.1.1
@nx/workspace      : 18.1.1
@nx/devkit         : 18.1.1
@nx/eslint-plugin  : 18.1.1
@nx/next           : 18.1.1
@nx/playwright     : 18.1.1
@nx/react          : 18.1.1
@nrwl/tao          : 18.1.1
@nx/web            : 18.1.1
@nx/webpack        : 18.1.1
typescript         : 5.3.3
```


## nx report (working)
```
Node   : 20.11.1
OS     : win32-x64
npm    : 10.2.4

nx (global)        : 18.0.8
nx                 : 18.0.8
@nx/js             : 18.0.8
@nx/jest           : 18.0.8
@nx/linter         : 18.0.8
@nx/eslint         : 18.0.8
@nx/workspace      : 18.0.8
@nx/devkit         : 18.0.8
@nx/eslint-plugin  : 18.0.8
@nx/next           : 18.0.8
@nx/playwright     : 18.0.8
@nx/react          : 18.0.8
@nrwl/tao          : 18.0.8
@nx/web            : 18.0.8
@nx/webpack        : 18.0.8
typescript         : 5.3.3
```

Im still having issues with build, but that is relating to next and tailwind and believe that to be a configuration issue i need to resolve on my part but I've not changed anything from the default configuration using `npx create-nx-workspace` so thought was worth mentioning incase it is somehow tangentially related. (see image)

![image](https://github.com/nrwl/nx/assets/4713282/4e6f7d38-a3cb-4249-82ec-a58aa29a856f)

**Comment by atsjo** [comment]
18.1.2 does not fix this...

**Comment by atsjo** [comment]
tried setting env variable NX_RUN_COMMANDS_DIRECTLY=false. This didn't fix it, but got another error message:
```
nx run shared-all:lint

^[[6;1R
```
and then the command just hangs.... (can break it via ctrl-c)

**Comment by FrozenPandaz** [comment]
Closed by https://github.com/nrwl/nx/pull/22382
