### ISSUE TITLE
@nx/vite  `nx build` ignores "modes"

### ISSUE THREAD

**Issue by dan-cooke** [nrwl/nx#22347]
### Current Behavior

As per the vite docs you can specify a `.env.production` file which will take precedence when you run `vite build`

https://vitejs.dev/guide/env-and-mode.html#modes

However this does not work when going through `nx` at all

### Expected Behavior

running `nx build ui` should be no different than running `vite build` from inside the ui directory

### Steps to Reproduce

1. Create a new vite monorepo
2. Create 2 env files inside a ui application directory

.env
```
VITE_FOO=BAR
```

.env.production
```
VITE_FOO=BAZ
```

3. Inside the main.tsx insert `console.log(imports.meta.env.VITE_FOO)`
4. Run `nx build`

Observe the built js inside dist/apps/ui grep for the string `BAR`

### Expected result
You should see the string `BAZ` not `BAR` as we are running in production mode

### Proof that its nx
If you simply `cd apps/ui && npx vite build` you can see `BAZ` in the built output clearly

### Nx Report

```shell
Node   : 20.9.0
OS     : linux-x64
yarn   : 1.22.21

nx (global)        : 18.0.8
nx                 : 18.0.6
@nx/js             : 18.0.6
@nx/jest           : 18.0.6
@nx/linter         : 18.0.6
@nx/eslint         : 18.0.6
@nx/workspace      : 18.0.6
@nx/cypress        : 18.0.6
@nx/devkit         : 18.0.6
@nx/esbuild        : 18.0.6
@nx/eslint-plugin  : 18.0.6
@nx/nest           : 18.0.8
@nx/node           : 18.0.6
@nx/react          : 18.0.6
@nrwl/tao          : 18.0.6
@nx/vite           : 18.0.6
@nx/web            : 18.0.6
@nx/webpack        : 18.0.6
typescript         : 5.3.3
---------------------------------------
Community plugins:
@nx-extend/shadcn-ui : 1.0.1
---------------------------------------
The following packages should match the installed version of nx
  - @nx/nest@18.0.8
  - @nrwl/nest@18.0.8

To fix this, run `nx migrate nx@18.0.8`
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by TNAJanssen** [comment]
Same issue here

**Comment by Coly010** [comment]
Thank you for bringing this issue to our attention! I want to assure you that I will take a look as soon as I can. Your patience and understanding in this matter is greatly appreciated.

**Comment by r3gisrc** [comment]
Same Here, for what i investigated:
It looks that multiple task/configuration .env file are only processed by webpack executor:
At /node_modules/@nx/webpack/node_modules/nx/src/tasks-runner/task-env>.loadDotEnvFilesForTask

So i end up with this workaround in my vite config:

```
const configurationFile = path.join(__dirname, `../.env.${process.env.NODE_ENV}`)
if (fs.existsSync(configurationFile)) DotEnv.config({path: configurationFile})
```

**Comment by puopg** [comment]
I can confirm the same behavior. My `.env.local` file loads great, but I was really hoping I could just define a `.env.production.local` or something similar to build with the production build NVAR's so that I don't have to manually comment in and out the production values in my `.env.local`

**Comment by Coly010** [comment]
Fixed by: https://github.com/nrwl/nx/pull/28663
