### ISSUE TITLE
I cannot get hot reload working with storybook and it's killing me!

### ISSUE THREAD

**Issue by TheDevelolper** [nrwl/nx#22352]
### Current Behavior

Storybook hot reload doesn't work in a react vite environment. There doesn't seem to be an obvious way to get this working? I can't find any docs on this either. Perhaps I'm not looking hard enough but they seem very hidden away.

--watch flag for storybook now fails. They broke it but then they decided to remove it completely as they prefer to use storybook dev server with `sb dev`. 

I can't seem to get the command to work in nx. So every time I make a storybook change I need to rebuild the whole thing to see if it works which is killing my workflow.

### Expected Behavior

It would be great if there was a way we could either use sb dev in Nx or provide a workaround where the --watch flag uses sb dev?

### Steps to Reproduce

1. Make a Nx project
2. Add Storybook
3. Add a component 
4. Alter the component

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.11.1
OS     : linux-x64
yarn   : 1.22.22

nx                 : 18.1.1
@nx/js             : 18.1.1
@nx/linter         : 18.1.1
@nx/eslint         : 18.1.1
@nx/workspace      : 18.1.1
@nx/cypress        : 18.1.1
@nx/devkit         : 18.1.1
@nx/eslint-plugin  : 18.1.1
@nx/playwright     : 18.1.1
@nx/react          : 18.1.1
@nx/storybook      : 18.1.1
@nrwl/tao          : 18.1.1
@nx/vite           : 18.1.1
@nx/web            : 18.1.1
typescript         : 5.3.3
---------------------------------------
Community plugins:
@nx-dotnet/core : 2.2.0
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by TheDevelolper** [comment]
To answer my own question, I found that existing issues answered this somewhat already but the problem in my case was that I did not have a storybook configuration in my project.json for the nx project in my case it was a ui-components project which was part of a larger monorepo. 

So the configuration is at the project level in a file called project,json needed to have storybook section added like so: 

``` javascript
{
  "name": "ui-components",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "libraries/ui-components/src",
  "projectType": "library",
  "tags": [],
  "// targets": "to see all targets run: nx show project ui-components --web",
  "targets": {
    "storybook": {
      "executor": "@nx/storybook:storybook",
      "options": {
        "port": 4300,
        "host": "0.0.0.0",
        "configDir": "libraries/ui-components/.storybook"
      },
      "configurations": {
        "ci": {
          "quiet": true
        }
      }
    }
  }
}
```

incidentally I also had to modify the viteConfigPath in my ./storybook/main.ts file but that was another issue.

**Comment by TheDevelolper** [comment]
I closed this issue too quicky, it's not actually resolved. I will keep trying myself and I will update my comments.

**Comment by Coly010** [comment]
Hey @TheDevelolper 

Can you provide me with more accurate and detailed reproduction steps please? 
I need to know if `Make an Nx project` means adding a new project to an existing Nx workspace or if it was setup via `create-nx-workspace`.

I also need to know what generators or options were used.

**Comment by TheDevelolper** [comment]
Sorry I left this open. The problem was caused by WSL mounted drives. They prevent file change notifications so nothing reloads!
