### ISSUE TITLE
Incorrect generation of eslint.config.js for angular library

### ISSUE THREAD

**Issue by ivibe** [nrwl/nx#22350]
### Current Behavior

After generating angular library the content of eslint.config.js is next:
```javascript
const FlatCompat = require('@eslint/eslintrc');
const js = require('@eslint/js');
const baseConfig = require('../../eslint.config.js');

const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
});

module.exports = [...baseConfig];
```

### Expected Behavior

```javascript
const { FlatCompat } = require('@eslint/eslintrc');
...
```

### Steps to Reproduce

1. `npx nx generate @nx/angular:library --name=another-lib --directory=libs/another-lib --projectNameAndRootFormat=as-provided --no-interactive`
2. `nx run another-lib:lint`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.10.0
OS     : linux-x64
npm    : 10.5.0

nx (global)        : 18.1.1
nx                 : 18.1.1
@nx/js             : 18.1.1
@nx/jest           : 18.1.1
@nx/linter         : 18.1.1
@nx/eslint         : 18.1.1
@nx/workspace      : 18.1.1
@nx/angular        : 18.1.1
@nx/cypress        : 18.1.1
@nx/devkit         : 18.1.1
@nx/eslint-plugin  : 18.1.1
@nx/nest           : 18.1.1
@nx/node           : 18.1.1
@nrwl/tao          : 18.1.1
@nx/web            : 18.1.1
@nx/webpack        : 18.1.1
typescript         : 5.3.3
```

### Failure Logs

```shell
Linting "another-lib"...

 NX   FlatCompat is not a constructor

Pass --verbose to see the stacktrace.


———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target lint for project another-lib (619ms)

   ✖  1/1 failed
   ✔  0/1 succeeded [0 read from cache]
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

eslint.config.js with same error is created when generating angular application.

When transitioning to new flat system (`nx g @nx/eslint:convert-to-flat-config`), the `FlatCompat ` is imported correctly in newly generated eslint.config.js files.

**Comment by tadamczak** [comment]
There is one more issue regarding generating new libraries and eslint.config.js.

We have some custom rules added in nx.json, for example prefix for component selectors. In normal esling.config.js after migration it is added to module.exports like 

```
module.exports = [
  ...baseConfig,
  ...compat
    .config({ extends: ['plugin:@nx/angular', 'plugin:@angular-eslint/template/process-inline-templates'] })
    .map((config) => ({
      ...config,
      files: ['**/*.ts'],
      rules: {
        '@angular-eslint/component-selector': [
          'error',
          {
            type: 'element',
            prefix: 'custom-selector',
            style: 'kebab-case',
          },
        ],
      },
    })),
  ...compat.config({ extends: ['plugin:@nx/angular-template'] }).map((config) => ({
    ...config,
    files: ['**/*.html'],
    rules: {},
  })),
];
```
However when generating new library it looks like this
```
module.exports = [...baseConfig];
```

PS. I also noticed that after generating library it generates file jest.config.ts on the root of the project with
```
import { getJestProjects } from '@nx/jest';

export default {
  projects: getJestProjects(),
};
```
Is this file required somehow or is it another bug?

Thanks for your help!

**Comment by kfalicov** [comment]
I'm also experiencing this under identical conditions and outcomes- It'd be great to get this patched

**Comment by GeorgeKnap** [comment]
Confirmed happening on currently latest NX 19.1.1
easily reproducible by running generator to convert workspace to inferred targets (project crystal). after this happens no generators works anymore due to `TypeError: FlatCompat is not a constructor`
