### ISSUE TITLE
Only one angular application is built when run-many with --watch flag in nx18.1.1

### ISSUE THREAD

**Issue by ivibe** [nrwl/nx#22351]
### Current Behavior

When launching `run-many --targets=build --parallel=4 --watch` command only one angular application is built and watched for changes

### Expected Behavior

All angular applications must be built and watched

### Steps to Reproduce

1. `npx create-nx-workspace@latest wsp`

| Prompt | Response |
| -------- | ----------- |
| Which stack do you want to use? | Angular |
| Integrated monorepo, or standalone project? | Integrated Monorepo |
| Application name | main |
| Which bundler would you like to use? | esbuild |
| Default stylesheet format | SASS(.scss) |
| Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? | No |
| Test runner to use for end to end (E2E) tests | Cypress |
| Set up CI with caching, distribution and test deflaking | Skip for now |
| Would you like remote caching to make your build faster? | Skip for now |

2. `npx nx generate @nx/angular:application --name=admin --directory=apps/admin --projectNameAndRootFormat=as-provided --no-interactive`
3. `npx nx generate @nx/angular:application --name=user --directory=apps/user --projectNameAndRootFormat=as-provided --no-interactive`
4. `nx run-many --targets=build --configuration=development --parallel=4 --watch`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.10.0
OS     : linux-x64
npm    : 10.5.0

nx (global)        : 18.1.1
nx                 : 18.1.1
@nx/js             : 18.1.1
@nx/jest           : 18.1.1
@nx/linter         : 18.1.1
@nx/eslint         : 18.1.1
@nx/workspace      : 18.1.1
@nx/angular        : 18.1.1
@nx/cypress        : 18.1.1
@nx/devkit         : 18.1.1
@nx/eslint-plugin  : 18.1.1
@nrwl/tao          : 18.1.1
@nx/web            : 18.1.1
@nx/webpack        : 18.1.1
typescript         : 5.3.3
```

### Failure Logs

```shell
NX   Running target build for 3 projects:

- admin
- main
- user

With additional flags:
  --watch=true

—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

> nx run admin:build:development --watch


> nx run main:build:development --watch


                                       > nx run user:build:development --watch

⠙ Building...
Initial chunk files | Names         |  Raw size
main.js             | main          |   1.15 MB | 
polyfills.js        | polyfills     |  83.60 kB | 
styles.css          | styles        | 107 bytes | 

                    | Initial total |   1.23 MB
Output location: /home/wsp/dist/apps/admin

Application bundle generation complete. [1.731 seconds]
Watch mode enabled. Watching for file changes...
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Without `--watch` flag everything works correctly.

With `--watch` flag even output in terminal is clunky
![terminal-output](https://github.com/nrwl/nx/assets/20191286/824bec52-d533-43b6-b320-db11b5410476)

**Comment by FrozenPandaz** [comment]
This was fixed by #22341 which was released in `18.1.2`
