### ISSUE TITLE
swc exclude config may not a array

### ISSUE THREAD

**Issue by hongxuWei** [nrwl/nx#22360]
### Current Behavior

if not configed "exclude" will get a error
```text
TypeError: Cannot read properties of undefined (reading 'concat')
    at generateTmpSwcrc (/Users/hongxu/repos/smallfish/node_modules/@nrwl/js/src/utils/swc/inline.js:7:41)
```

### Expected Behavior

give a default value for swc exclude if nx must need it

### Steps to Reproduce

-

### Nx Report

```shell
-
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by hongxuWei** [comment]
https://github.com/nrwl/nx/pull/21904

**Comment by hongxuWei** [comment]
@FrozenPandaz

**Comment by jaysoo** [comment]
PR is merged https://github.com/nrwl/nx/pull/21904

Thanks
