### ISSUE TITLE
Add a showConfig flag on the CLI to show the rendered nx config for a project

### ISSUE THREAD

**Issue by joshlartz** [nrwl/nx#22372]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Similar to other tools in the ecosystem like tsc and jest, it would be helpful if nx also had a `--showConfig` flag to output the rendered config from nx.json, project.json, and inference for a given project.

## Motivation

 With the hierarchical nature of the config files, it takes a bit of mental overhead to figure out what the final config values for a target in a project might be. It helps with troubleshooting as well when things are not inferred correctly. 

## Suggested Implementation

This functionality is already happening internally when the project graph is made, so this would be a CLI argument that outputs that config. The `nx show` command feels like the best place for this. I would expect project to be a required parameter. 

## Alternate Implementations

You could also mirror the common `--showConfig` flag, but I'm not sure which command makes sense to hang that off of.

**Comment by FrozenPandaz** [comment]
It seems you've already found `nx show`. The command is `nx show project <Project Name>`. This will show it in `json` form by default. Though, i'd recommend passing `--web` to open up a web view to show it.

Does that command work for you? The web view includes information about which plugin created each property in the final configuration of a projecft.

**Comment by joshlartz** [comment]
It does! I've used `nx show projects` and `--affected` a ton of times, including the graph, but somehow missed this version of project without the "s". Thank you!
