### ISSUE TITLE
Nx create workspace (React Standalone App) is not working in Windows while using --pm=yarn

### ISSUE THREAD

**Issue by siddharthOtr** [nrwl/nx#22383]
##### I am creating this in D drive of my computer (in C drive its working properly)
```npx create-nx-workspace@latest myreactapp --preset=react-standalone --packageManager=yarn```
#### This command results into the following : 
1.  Which bundler would you like to use? => Vite
2. Test runner to use for end to end (E2E) tests => None
3. Default stylesheet format => SASS
4. Do you want Nx Cloud to make your CI fast? => Skip for now

- [x] Installing dependencies with yarn
- [ ] Creating your workspace in myreactapp ( not completed )   

### Steps to Reproduce

1. Go to any drive of your computer (Other than C Drive).
2. open terminal and select node version
```nvm use 18```
3. run the command
```npx create-nx-workspace@latest myreactapp --preset=react-standalone --packageManager=yarn```
4. It will result into Error.

### Nx Report

```shell
NX   Failed to create a workspace.

Error: error Command failed with exit code 1.
```

### Failure Logs

```shell
There is no logs created for this, I have tried to access error logs but it's not creating any error logs.
```

### Package Manager Version

yarn - 1.22.19 

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

1. when creating workspace using older version (eg. 16) instead of @latest then it's working properly. 
2. While using package manager as npm its working properly.

**Comment by MaxKless** [comment]
Hey! Thanks for the report. I just wanted to let you know that I've been able to reproduce this and am digging into what could be the root cause... it seems like something is going wrong during the preinstall step.

**Comment by siddharthOtr** [comment]
Hi @MaxKless,
Thanks for the update. Is there any fix or workaround available for this issue?
