### ISSUE TITLE
Nx release "invalid package name" of buildable lib

### ISSUE THREAD

**Issue by cspritchard** [nrwl/nx#22380]
### Current Behavior

We are working on doing our first release of an Angular app from our monorepo, and are trying to do independent project releases. Our nx.json is as follows:
```
"release": {
    "projectsRelationship": "independent",
    "changelog": {
      "projectChangelogs": true
    },
    "projects": ["source-tank-desktop"]
  }
```

When running the command `nx release --first-release --dry-run --projects=source-tank-desktop` we get this error:
 >  NX   Invalid package name "@ejg-wgs/types/common" of package "@ejg-wgs/types/common@0.0.1": name can only contain URL-friendly characters.

Renaming the package and its references to be `@ejg-wgs/types-common` resolves the issue and allows the release command to run. But, we are unsure why this is necessary as all other libs do not have this issue. For example, this project also depends on the lib `@ejg-wgs/types/source-tank` yet no error is generated for that name during release. 

These are implicit dependencies outlined in the apps project.json like so:
```
  "targets": {
    "build": {
      "options": {
        "allowedCommonJsDependencies": [
          "@ejg-wgs/types/common",
          "@ejg-wgs/types/source-tank",
          "@codewithdan/observable-store"
        ],
      },
    },
```

### Expected Behavior

Identical buildable libs, with same naming pattern only different names, should either cause no error or both throw same error instead of one and not the other.

### Steps to Reproduce

1. Create workspace with single angular app
2. Create two libs with name @my-org/group/lib-one & @my-org/group/lib-two
3. Configure libs as implicit dependencies of app in project.json
4. Configure independent project releases for app
5. Run nx release and get invalid package name error

### Nx Report

```shell
Node   : 18.18.0
   OS     : darwin-arm64
   npm    : 9.8.1
   
   nx (global)        : 18.0.3
   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/jest           : 18.0.4
   @nx/linter         : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/workspace      : 18.0.4
   @nx/angular        : 18.0.4
   @nx/cypress        : 18.0.4
   @nx/devkit         : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nrwl/tao          : 18.0.4
   @nx/web            : 18.0.4
   @nx/webpack        : 18.0.4
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.14.1
   ng-mocks                         : 14.12.1
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by kevindice** [comment]
Hi @cspritchard - Package names can only have one slash in them.
