### ISSUE TITLE
18.1.0 breaks forwardAllArgs argument

### ISSUE THREAD

**Issue by rejas** [nrwl/nx#22385]
### Current Behavior

I have this executor:
```
"typecheck": {
  "executor": "nx:run-commands",
  "options": {
    "commands": ["tsc -p tsconfig.lib.json --noEmit"],
    "cwd": "libs/services",
    "forwardAllArgs": false
  }
},
```

With 18.1.0 I get for when doing `nx run services:typecheck`

```
error TS5023: Unknown compiler option '--forwardAllArgs'.
Warning: command "tsc -p tsconfig.lib.json --noEmit --forwardAllArgs false" exited with non-zero status code


 NX   Ran target typecheck for project services (416ms)

   ✖  1/1 failed
   ✔  0/1 succeeded [0 read from cache]

```

### Expected Behavior

With 18.0.8 I get no error:

```
> nx run services:typecheck

 NX   Successfully ran target typecheck for project services (2s)

Process finished with exit code 0
```

### Steps to Reproduce

1. Update to nx 18.1
2. Run typecheck executor

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 18.19.0
OS     : darwin-arm64
pnpm   : 8.15.5

nx (global)        : 18.1.2
nx                 : 18.1.2
@nx/js             : 18.1.2
@nx/jest           : 18.1.2
@nx/eslint         : 18.1.2
@nx/workspace      : 18.1.2
@nx/devkit         : 18.1.2
@nx/eslint-plugin  : 18.1.2
@nx/next           : 18.1.2
@nx/playwright     : 18.1.2
@nx/react          : 18.1.2
@nx/storybook      : 18.1.2
@nx/vite           : 18.1.2
typescript         : 5.3.3
---------------------------------------
Community plugins:
nx-stylelint : 17.1.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by francescocaveglia** [comment]
this syntax works:
```
"typecheck": {
  "executor": "nx:run-commands",
  "options": {
    "commands": [
      {
        "command": "tsc -p tsconfig.lib.json --noEmit",
        "forwardAllArgs": false
      }
    ],
    "cwd": "libs/services"
  }
},

**Comment by rejas** [comment]
Thanks, this works indeed. Any idea/reason why the syntax changed with 18.1?

**Comment by javascriptkitty** [comment]
I'm still getting an error even though all the checks pass
<img width="669" alt="Screenshot 2024-03-19 at 11 07 33 PM" src="https://github.com/nrwl/nx/assets/39271295/d030b495-18dc-4bd0-962a-fdbb22095b4a">

**Comment by FrozenPandaz** [comment]
We didn't change the syntax but I the handling of which options are forwarded to the command has changed. We will be fixing the change in behavior.

**Comment by xiongemi** [comment]
forwardAllArgs is an option under options.commands as shown in https://nx.dev/nx-api/nx/executors/run-commands. as mentioned above, it is not directly under options.
there was a change where any unknown options will be passed to the underlying command.

closing this issue for now.

**Comment by xiongemi** [comment]
i think it is related to https://github.com/nrwl/nx/issues/22025. currently there is no top level forwardAllArgs
