### ISSUE TITLE
npm run format causes tslint error: max-line-length

### ISSUE THREAD

**Issue by dereklin** [nrwl/nx#224]
This is related to https://github.com/nrwl/nx/issues/187.  But I am reporting a new/specific issue.  Hopefully it's just a prettier config issue.

Here is my repo: https://github.com/dereklin/nx-demo-jest/tree/format-problem

It's the format-problem branch.

I have code that looks like this:

```
    this.dummy.type1.dummyPropertyFunction
      = this.dummy.type2.dummyPropertyFunction
      = this.dummy.type3.dummyPropertyFunction
      = this.dummy.type4.dummyPropertyFunction
      = this.dummy.type5.dummyPropertyFunction
      = this.dummy.type6.dummyPropertyFunction
      = this.dummy.type7.dummyPropertyFunction
      = this.dummy.type8.dummyPropertyFunction
      = () => {
        return 'dummy';
      };
```
After npm run format, this code is turned into this:

```
    this.dummy.type1.dummyPropertyFunction = this.dummy.type2.dummyPropertyFunction = this.dummy.type3.dummyPropertyFunction = this.dummy.type4.dummyPropertyFunction = this.dummy.type5.dummyPropertyFunction = this.dummy.type6.dummyPropertyFunction = this.dummy.type7.dummyPropertyFunction = this.dummy.type8.dummyPropertyFunction = () => {
      return 'dummy';
    };
```

This causes the max-line-length tslint error.

I would expect the format to leave the original.  In fact, it should turn the resulting code into the original if I had wrote the resulting code by hand.

**Comment by vsavkin** [comment]
It looks like an issue with prettier. So I would file it here: https://github.com/prettier/prettier.

In general, you should not have max-line-length  in your tslint.json. If upgrade your version of Nx and run nx-migrate, it should remove max-line-length. If something went wrong and it didn't happen, you can remove it yourself.

**Comment by dereklin** [comment]
@vsavkin I don't think nx should change the tslint.json rules automatically.  Better to leave tslint.json alone to give total control to team/developers.

Regarding this particular issue, I have filed it here: https://github.com/prettier/prettier/issues/3819
It doesn't seem like an easy thing to fix.  Right now, I am using 
```
// prettier-ignore
```
https://prettier.io/docs/en/ignore.html
