### ISSUE TITLE
Nx release to use changesets as the versioning source

### ISSUE THREAD

**Issue by osuritz-grammarly** [nrwl/nx#22401]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Nx should support [changesets](https://github.com/changesets/changesets) as the source of semantic versioning information used to infer the next version number of a package when invoking `nx release [version]`.
While [conventional commits](https://www.conventionalcommits.org/en/) ships as an option today, it appears the implementors of `nx release` have purposely kept the door open to alternative ways of determining version numbers. Changesets is a fairly largely use option that depends on files being added to a repo's `.changesets` directory to determine the next version number.
It is similar, in spirit, to conventional commits but is divorced from the underlying source repository commit message format to do its job.

## Motivation
Using [conventional commits](https://www.conventionalcommits.org/en/) as the source of versioning requires a big change in engineering culture for larger teams and may not be feasible.
Using changesets brings another option to the table for teams that are already using changesets today —outside of Nx— as their versioning/changelog management system.

## Suggested Implementation
To enable conventional commits, users update `nx.json` with the following section:
```json
{
  "release": {
    "version": {
      "conventionalCommits": true
    }
  }
}
```

Configuring the use of changesets would look something like:
```json
{
  "release": {
    "version": {
      "changesets": true
    }
  }
}
```

When configured as such, `nx release` would invoke [the changesets CLI](https://github.com/changesets/changesets?tab=readme-ov-file#integrating-with-ci) or API calls such as `applyReleasePlan(...)` or `getReleasePlan(...)`

## Alternate Implementations
🤷

**Comment by FrozenPandaz** [comment]
We are actually working on a file-based way to version packages.

@fahslaj would you like to give a sneak peek of what you are working on?

**Comment by fahslaj** [comment]
Hi @osuritz-grammarly, you're right that we've left the door open to other ways to determine versions! I'm happy to say that we're currently working on a feature that allows you to use Nx Release to accomplish what you've described above - detached from commit history and conventional commits standards. It's currently still in development, but I will follow up with more information once it's available :)

**Comment by osuritz-grammarly** [comment]
Sweet! ❤️ 

Out of curiosity, @fahslaj  do you have a rough ETA for this feature? Nothing to hold you to, but more a ballpark so we can determine next steps for us internally, if any.

**Comment by tkajtoch** [comment]
FYI This seems to be the feature mentioned above: https://github.com/nrwl/nx/pull/23190

**Comment by JakeGinnivan** [comment]
This is quite cool, one of the remaining features of changesets is the GitHub action: https://github.com/changesets/action

This opens a pull request containing the results of the version command, and when that PR is merged, it will run the publish command instead of opening/updating the PR.

It would be good to either support adding this feature, or allowing changesets to be integrated somehow (as suggested above).

**Comment by thdk** [comment]
In case anyone is looking for the docs for Nx version plans: https://nx.dev/recipes/nx-release/file-based-versioning-version-plans

**Comment by JamesHenry** [comment]
That's absolutely right @thdk, thank you.

Nx release natively provides a file based versioning system which will be very familiar to anyone who has used the library changesets before. We even use the same frontmatter YAML powered markdown format as them (unlike Beachball, for example, which uses JSON for its files).

Nx release comes with the advantages that it is built in and developed alongside the rest of Nx and can be combined with our other versioning strategies across different release groups within the same monorepo.

As noted above, please find the documentation for file based versioning (what we call "version plans") here:

 https://nx.dev/recipes/nx-release/file-based-versioning-version-plans
