### ISSUE TITLE
Nextjs nx x app directory does not use tsconfig base so libs not imported

### ISSUE THREAD

**Issue by CharlieGreenman** [nrwl/nx#22425]
### Current Behavior

barrel files error out in nextjs app 

### Expected Behavior

barrel files should work e.g. "extends": "../../tsconfig.base.json", should be included in tsconfig.json for app which it currently isn't

### Steps to Reproduce

1. create new nextjs repo
2. create new lib
3. create new component
import component in app

### Nx Report

```shell
NA
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Could you please provide a repo where we can reproduce the issue please? When I tried to reproduce it, the imports were working as expected.

**Comment by CharlieGreenman** [comment]
This is for the apps folder. Will get around to sooner than later
