### ISSUE TITLE
Nx run-many support process

### ISSUE THREAD

**Issue by LiangNex** [nrwl/nx#22427]
## Description

Nx run-many is useful for a monorepo project to execute build commands cross multiple pkgs; But it sucks when each build command costs about 30 ~ 40 seconds. 

It would be amazing if there is a progress bar for the whole build process.

## Motivation

Currently our devs constantly complain about this thing, they want a progress feat so that they can have an ETA about how long they should wait for the whole process.

Not something like this without any progress info.
```shell
 >  NX   Running target build for project @abc/oasis
 
    →    Executing 1/1 remaining tasks...
 
    ⠇    nx run @abc/oasis
```

## Suggested Implementation

Anything, a counter will also help; e.g. progress: [3/17]
A progress bar is prefered :P

## Alternate Implementations

N/A

**Comment by FrozenPandaz** [comment]
Perhaps the language here is not clear but Nx actually already shows the same information as the "Progress" you are looking for.

![image](https://github.com/nrwl/nx/assets/8104246/28da30b7-bc6f-4751-8d60-40f4feacd178)

> Executing 7/52 remaining tasks

As the `run-many` command runs, the 52 remaining tasks will countdown to 0. It started at 119, the total amount of tasks being executed by the command. 7 of those 52 remaining tasks are running right now in parallel. The 7 are listed below.

> 67 / 67 succeeded

The bottom is how many tasks have been completed. Which will count up to 119.

With your example, we would say something like... 67 / 119.

---

All I'm saying is the progress is basically a countdown from 119 to 0 which is at 52 tasks remaining in the screenshot. The bigger the number, the more time is left. As the number approaches 0, the closer the command is to being complete. While the number of total tasks being run is not explicitly printed, an indicator of how much work is left to do is indeed displayed.

Now that I explained it, does it make more sense? What would you change about the output to better indicate progress?

**Comment by FrozenPandaz** [comment]
There hasn't been a response here for a while so I'm going to close this.
