### ISSUE TITLE
[@nx/react] `@nx/react/tailwindcss` is not configured in `package.json` as an access point

### ISSUE THREAD

**Issue by sharky98** [nrwl/nx#22420]
### Current Behavior

Configuring Tailwind using TypeScript (`tailwind.config.ts`) and using `import { createGlobPatternsForDependencies } from "@nx/react/tailwind";` under stricter/newer configuration is giving an error: `Cannot find module '@nx/react/tailwind' or its corresponding type declarations.ts(2307)`.

This is my `tsconfig.base.json`.

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "Node16",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "verbatimModuleSyntax": true,
    "target": "ES2022",
    "module": "Node16",
    "lib": ["ES2023", "DOM"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {}
  },
  "exclude": ["node_modules", "tmp"]
}
```

### Expected Behavior

No error.

### Steps to Reproduce

1. Use stricter/newer TypeScript configuration.
2. Convert the defaut Tailwind configuration to TypeScript, using import statement.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.11.1
OS     : linux-x64
pnpm   : 8.15.5

nx (global)        : 18.1.2
nx                 : 18.1.2
@nx/js             : 18.1.2
@nx/eslint         : 18.1.2
@nx/workspace      : 18.1.2
@nx/cypress        : 18.1.2
@nx/devkit         : 18.1.2
@nx/eslint-plugin  : 18.1.2
@nx/plugin         : 18.1.2
@nx/react          : 18.1.2
@nrwl/tao          : 18.1.2
@nx/vite           : 18.1.2
@nx/web            : 18.1.2
typescript         : 5.4.2
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I am pretty certain that the issues comes from the fact that `package.json` does not configure `@nx/react/tailwind` to be a valid export endpoint.

https://github.com/nrwl/nx/blob/b7ffb257a25821666f9dfd0cda49761231814ed0/packages/react/package.json#L19-L20

Adding the `exports` configuration to `package.json` should correct the issue. At least, it does when "monkey-patching" the `package.json` in my node_modules directory.

```json
{
  "exports": {
    ".": {
      "types": "./index.d.ts",
      "default": "./index.js"
    },
    "./tailwind": {
      "types": "./tailwind.d.ts",
      "default": "./tailwind.js"
    }
  },
  "main": "./index.js",
  "types": "./index.d.ts"
}
```

**Comment by jaysoo** [comment]
@sharky98 The problem is that Node16 resolution requires file extensions to be specified when importing `@nx/react/tailwind`, so your import should be `@nx/react/tailwind.js` which will be matched to the types in `tailwind.d.ts`. Adding the `exports` entry works as well, but it's a breaking change on our end so we cannot do that easily.

My suggestion is to use `moduleResolution: 'bundler'` instead, which makes the file extensions optional.


```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "Bundler",
    "module": "ES2022",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "verbatimModuleSyntax": true,
    "target": "ES2022",
    "lib": ["ES2023", "DOM"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {}
  },
  "exclude": ["node_modules", "tmp"]
}
```
