### ISSUE TITLE
SWC runtime errors with Nx generators

### ISSUE THREAD

**Issue by kwickramasekara** [nrwl/nx#22435]
### Current Behavior

After migrating our monorepo from Nx 16 to 18, we noticed runtime errors when executing generator scripts. Rolling back SWC to versions that were used in Nx v16 worked.

Error:
![image](https://github.com/nrwl/nx/assets/6528584/1cab4f9d-a4bf-40b1-9736-1e84ccf277e8)

### Expected Behavior

Should not produce errors when executing generator scripts

### Steps to Reproduce

1. Install latest Nx
2. Create a generator that uses devkit
3. Run generator script

### Nx Report

```shell
Node   : 18.15.0
OS     : darwin-arm64
npm    : 9.5.0

nx                 : 18.0.7
@nx/js             : 18.0.7
@nx/jest           : 18.0.7
@nx/linter         : 18.0.7
@nx/eslint         : 18.0.7
@nx/workspace      : 18.0.7
@nx/devkit         : 18.0.7
@nx/eslint-plugin  : 18.0.7
@nx/plugin         : 18.0.7
@nrwl/tao          : 18.0.7
typescript         : 5.4.2
---------------------------------------
Local workspace plugins:
REDACTED
```

### Package Manager Version

9.5.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Issue exists with:
```
"@swc-node/register": "^1.9.0",
"@swc/cli": "^0.3.10",
"@swc/core": "^1.4.5",
```

Rolled back to the following to avoid errors:
```
"@swc-node/register": "^1.4.2",
"@swc/cli": "^0.1.62",
"@swc/core": "^1.3.51"
```

**Comment by FrozenPandaz** [comment]
Could you provide a repro we can take a look at to help us resolve your issue?
