### ISSUE TITLE
options with create-nx-workspace to execute it silently.

### ISSUE THREAD

**Issue by sameerinfodb** [nrwl/nx#2244]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

**npx create-nx-workspace@latest poss-web --preset empty --type=angular**

Should provision the new workspace without expecting user to select whether it should use
type as it is already provided.

[ ] Nx           [Extensible CLI for JavaScript and TypeScript applications]
[ ]Angular CLI  [Extensible CLI for Angular applications. Recommended for Angular projects.]

## Current Behavior

What is the current behavior?

It is not considering the type and prompting the user to select the workspace-type.

version of Nx used 8.9.0
version of Angular CLI used 8.3.14

**Comment by FrozenPandaz** [comment]
I believe this is the command you are looking for:

```
npx create-nx-workspace poss-web --preset=empty --cli=angular
```

The proper option is called "cli"
