### ISSUE TITLE
@nx/dependency-checks documentation should include package-lock.json is required to correctly pull in dependencies 

### ISSUE THREAD

**Issue by L-NiNo** [nrwl/nx#22442]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?
@nx/dependency-checks

Enter the URL or documentation section here.
https://nx.dev/nx-api/eslint-plugin/documents/dependency-checks 

### Additional context or description
I spent many hours migrating angular lib monoreop trying to get the dependency check added in the migration. I followed the documentation and I could see it working but was not seeing the 3rd party libs imported into the lib. Stumbled upon https://github.com/nrwl/nx/issues/20881 and saw that the rule pulls from the package-lock. (which was deleted during the upgrade process to prevent locking issues). If this was in the documentation, I would have save time, frustration, and effort to know that this would have needed to be there for this process to work correctly.  

Provide any additional details here as needed.

**Comment by FrozenPandaz** [comment]
Sure, we can mention that. PRs are welcome for this.
