### ISSUE TITLE
Nx lint is not using the full configuration as eslint do

### ISSUE THREAD

**Issue by elvince** [nrwl/nx#22458]
### Current Behavior

If I run eslint apps/xx/src/. or nx lint xx I should have the same ouput which is not the case.

Eslint command is properly using the eslint import plugin to manage absolute path import defined in the tsconfig.
While nx lint command is not

### Expected Behavior

Same output whatever command is used.

### Steps to Reproduce

1. Create a monorepo react
2. Setup a project with absolute path setup
3. add in project eslint setup :
```
 settings: {
    'import/resolver': {
      typescript: {
        extensions: ['.js', '.jsx', '.ts', '.tsx', '.svg', '.png'],
        project: ['./apps/*/tsconfig.json'],
      },
      node: {
        extensions: ['.js', '.jsx', '.ts', '.tsx', '.svg', '.png'],
        project: ['./apps/*/tsconfig.json'],
      },
    },
  },
```
4. launch the 2 different command

### Nx Report

```shell
Node   : 20.9.0
OS     : win32-x64
npm    : 10.1.0

nx                 : 18.0.8
@nx/js             : 18.0.8
@nx/linter         : 18.0.8
@nx/eslint         : 18.0.8
@nx/workspace      : 18.0.8
@nx/cypress        : 18.0.8
@nx/devkit         : 18.0.8
@nx/eslint-plugin  : 18.0.8
@nx/react          : 18.0.8
@nrwl/tao          : 18.0.8
@nx/vite           : 18.0.8
@nx/web            : 18.0.8
typescript         : 5.3.3
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Please provide a repo where the issue can be reproduced to help us troubleshoot the problem more quickly.
