### ISSUE TITLE
Unable to run load nextjs jest config outside of `nx run`

### ISSUE THREAD

**Issue by karlismelderis-mckinsey** [nrwl/nx#22450]
### Current Behavior

seems that this [PR](https://github.com/nrwl/nx/pull/22026) broke simple script:
```bash
pnpx knip --config ./knip.js
```

with latest changes code fails here - https://github.com/nrwl/nx/blob/master/packages/next/plugins/with-nx.ts#L144
because none of these ENV variables are there

Also running jest tests outside of nx (e.g. IntelliJ) is not possible now

everything fails with same error:
```
  TypeError: Cannot read properties of undefined (reading 'data')
    at readConfigFileAndSetRootDir (/.../node_modules/.pnpm/jest-config@29.7.0_@types+node@20.11.30_ts-node@10.9.2/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:116:13)
```

maybe `with-nx.ts` need to add `'phase-test' === phase` [here](https://github.com/nrwl/nx/blob/master/packages/next/plugins/with-nx.ts#L120) but I'm not familiar enough with NextJS plugin

### Expected Behavior

I don't need to run every single script within `nx run ...`

### Steps to Reproduce

try to run knip of jest outside of nx

### Nx Report

```shell
TypeError: Cannot read properties of undefined (reading 'data')
    at readConfigFileAndSetRootDir (/.../node_modules/.pnpm/jest-config@29.7.0_@types+node@20.11.30_ts-node@10.9.2/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:116:13)
```
```


### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by karlismelderis-mckinsey** [comment]
@jaysoo would you be able to check this bug?

**Comment by karlismelderis-mckinsey** [comment]
@FrozenPandaz and @ndcunningham how soon will you be able to pick this up?

if you're overloaded I can try to investigate internals of nx and come up with a proposal PR

**Comment by ndcunningham** [comment]
@karlismelderis-mckinsey feel free to pick this up if you can

**Comment by johndalvik** [comment]
@karlismelderis-mckinsey @ndcunningham 

Any update on this?

I have to provide additional code to fix the behaviour, which is not not very clean and straightforward.

```ts
process.env['NX_TASK_TARGET_PROJECT'] = 'app';
process.env['NX_TASK_TARGET_TARGET'] = 'test';
process.env['NX_TASK_TARGET_CONFIGURATION'] = 'development';
```

**Comment by ndcunningham** [comment]
I don't think I see an issue with including `TASK_TARGET_TARGET` env var as we did before. 
We probably should've just added the graph creation instead of replacing it.
