### ISSUE TITLE
Documentation detail

### ISSUE THREAD

**Issue by yvesguilherme** [nrwl/nx#22453]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [X] Documentation improvement
- [X] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/showcase/example-repos/mfe#nx-microfrontend-example

### Additional context or description

Hi guys! I think, for this example, the documentation needs to be more detailed, because when users look at the repository, there are a lot of features and functionalities... Some parts of the Nx documentation are a bit bad, because there is no additional information...

But congratulations on your work! I appreciate it :)

Hugs!...

**Comment by FrozenPandaz** [comment]
Sure, we could add more detail to that page. What would you like to see there?

**Comment by isaacplmann** [comment]
Closing.  Feel free to reopen if you have a specific suggestion.
