### ISSUE TITLE
What Could be the Issue with Integrating a Custom Executor for the 'serve' Operation?

### ISSUE THREAD

**Issue by jon9090** [nrwl/nx#22451]
I aim to incorporate my custom executor into the `serve` operation.

Therefore, I've designed an executor blueprint, with the main function structured as follows:

```typescript
import { ServeExecutorSchema } from './schema';
import { externalSchematic } from '@angular-devkit/schematics';

export default async function runExecutor(options: ServeExecutorSchema) {
  // Implement custom functionality here..
  // The remainder remains unchanged.
  return externalSchematic('@angular-devkit/build-angular', 'dev-server', {
    ...options,
  });
  // console.log('Executor ran for Serve', options);
  // return {
  //   success: true,
  // };
}
```

In the project.json/angular.json file:

```json
"serve": {
      "executor": "@app/angular:serve",
      "configurations": {...}
```

Executing the schematics with: `nx serve app`.

Encountered:

```
yarn nx serve app
yarn run v1.22.19
$ app/node_modules/.bin/nx serve app

> nx run app:serve:development
 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target serve for project app failed

   Failed tasks:

   - app:serve:development

   Hint: run the command with --verbose for more details.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

What could be the issue here?

**Comment by FrozenPandaz** [comment]
I think you may be mixing ideas here.

`externalSchematic` calls an Angular CLI schematic. It is intended to be used within other Angular CLI schematics.

An Nx executor is used to run operations on a project, not generate code like schematics are used for.

I'm not sure what you are trying to achieve but you may want to read these few guides. I don't think there's much more we can do to help you resolve this issue.

 https://nx.dev/extending-nx/tutorials/create-plugin
 https://nx.dev/extending-nx/recipes/local-executors
https://nx.dev/extending-nx/recipes/local-generators
