### ISSUE TITLE
Missing Platform Dependency - darwin-arm64

### ISSUE THREAD

**Issue by Taldorr** [nrwl/nx#22472]
### Current Behavior

When using the "NX Console" Extension in VSCode, projects are not found MOST OF THE TIME.

Over the last couple of hours, I created different new nx workspaces (with `npx create-nx-workspace`). In all but 1 of those workpaces, projects would not be displayed in the VSCode extension, even when `npx nx show projects` would display them correctly every time.

In the single occurrence, when the projects did show up and I tried to fire a command via the UI of the extension, I got this error:

NX   Missing Platform Dependency

The Nx CLI could not find or load the native binary for your supported platform (darwin-arm64).
This likely means that optional dependencies were not installed correctly, or your system is missing some system dependencies.
For more information please see https://nx.dev/recipes/troubleshooting/troubleshoot-nx-install-issues

The same command put into the terminal manually will work as expected.

### Expected Behavior

The NX Console should display the projects of a workspace and execute commands without errors

### GitHub Repo

https://github.com/nrwl/nx-examples

### Steps to Reproduce

1. create a new nx workspace with `npx create-nx-workspace` (or clone the nx-examplex repo)
2. open the NX Console extension of VSCode
3. No projects are displayed or commands cannot be executed

### Nx Report

```shell
Node   : 20.10.0
OS     : darwin-x64
yarn   : 1.22.17

nx (global)        : 18.1.2
nx                 : 18.1.0-beta.10
@nx/js             : 18.1.0-beta.10
@nx/jest           : 18.1.0-beta.10
@nx/linter         : 18.1.0-beta.10
@nx/eslint         : 18.1.0-beta.10
@nx/workspace      : 18.1.0-beta.10
@nx/angular        : 18.1.0-beta.10
@nx/cypress        : 18.1.0-beta.10
@nx/devkit         : 18.1.0-beta.10
@nx/eslint-plugin  : 18.1.0-beta.10
@nx/react          : 18.1.0-beta.10
@nrwl/tao          : 18.1.0-beta.10
@nx/web            : 18.1.0-beta.10
@nx/webpack        : 18.1.0-beta.10
typescript         : 5.3.3
---------------------------------------
Community plugins:
@ngrx/component-store : 17.0.1
@ngrx/effects         : 17.0.1
@ngrx/entity          : 17.0.1
@ngrx/router-store    : 17.0.1
@ngrx/store           : 17.0.1
@ngrx/store-devtools  : 17.0.1
```

### Failure Logs

```shell
*  Executing task: yarn nx run cart:lint 

yarn run v1.22.17
$ nx run cart:lint

 NX   Missing Platform Dependency

The Nx CLI could not find or load the native binary for your supported platform (darwin-arm64).
This likely means that optional dependencies were not installed correctly, or your system is missing some system dependencies.
For more information please see https://nx.dev/recipes/troubleshooting/troubleshoot-nx-install-issues

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 *  The terminal process "/bin/zsh '-l', '-c', 'yarn nx run cart:lint'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.
```

### Package Manager Version

yarn --version = 1.22.17

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Taldorr** [comment]
Edit: I used a Macbook M1 and just realized, that with `nx report` the OS is displayed as "darwin-x64".
Shouldn't it be "dawin-arm"? Is it possible the wrong OS is detected?

**Comment by Taldorr** [comment]
I found a workaround for this problem:

1. I uninstalled the current version for VSCode and installed 1.86.2
2. I uninstalled the current version for Nx Console and installed 18.10.1
3. I used nvm to change my node version from 20.10.0 to 18
4. Lastly, I manually installed `npm i @nx/nx-darwin-arm64 --force`

I'm still wondering, why the error suddenly occurred and I think not all of the steps above are actually required to get the workaround running

**Comment by MaxKless** [comment]
Great that you found this workaround. 
Usually the problem is much simpler and is because you installed node for the wrong architecture originally. 
Maybe you installed it via homebrew? Or just the wrong installer. 
Reinstalling node is usually the solution. Also refer to the [troubleshooting guide here](https://nx.dev/recipes/nx-console/console-troubleshooting). I'll update it to fit your scenario better.
