### ISSUE TITLE
CSS broken because of media="print" (when generating new project and adding simple CSS rule)

### ISSUE THREAD

**Issue by loxy** [nrwl/nx#22479]
### Current Behavior

When I create a new project (with latest version) like this (see used settings)

```sh
npx create-nx-workspace@latest css-print-bug  

NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Which stack do you want to use? · angular
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · css-print-bug
✔ Which bundler would you like to use? · esbuild
✔ Default stylesheet format · scss
✔ Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? · No
✔ Test runner to use for end to end (E2E) tests · none
✔ Set up CI with caching, distribution and test deflaking · skip
✔ Would you like remote caching to make your build faster? · skip

 NX   Creating your v18.1.2 workspace.

✔ Installing dependencies with npm
✔ Successfully created the workspace: css-print-bug.
```

And adding just a simple CSS rule in main SCSS file (`{projectRoot}/src/styles.scss`)
```scss
div {
  color: red;
}
```

the compiled `index.html` is referencing the stylesheet with a `media="print"` on it:

```html
<link rel="stylesheet" href="styles-B4PBPOF5.css" media="print" onload="this.media='all'">
<noscript><link rel="stylesheet" href="styles-B4PBPOF5.css"></noscript>
```
 
When running the app the CSS is not applied! (unless you print the web page)

### Expected Behavior

In compiled `index.html` the link tag is applied correctly without `medie="print"`

### GitHub Repo

https://github.com/loxy/css-print-bug

### Steps to Reproduce

1. build project
2. examine compiled `index.html`

### Nx Report

```shell
Node   : 18.12.1
OS     : darwin-arm64
npm    : 8.19.2

nx                 : 18.1.2
@nx/js             : 18.1.2
@nx/jest           : 18.1.2
@nx/linter         : 18.1.2
@nx/eslint         : 18.1.2
@nx/workspace      : 18.1.2
@nx/angular        : 18.1.2
@nx/devkit         : 18.1.2
@nx/eslint-plugin  : 18.1.2
@nrwl/tao          : 18.1.2
@nx/web            : 18.1.2
@nx/webpack        : 18.1.2
typescript         : 5.3.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I have found a similar issue in Angular Universal repo. See: https://github.com/angular/universal/issues/3128
It is already fixed and SSR is mentioned. My issue is without SSR but using new esbuild.

**Comment by loxy** [comment]
See also: https://github.com/angular/angular-cli/issues/20864

**Comment by Coly010** [comment]
I can't reproduce this issue, even on the repo you provided.

`media=print` is not an issue here. The `onload` function resets the targetted media for the stylesheet.

I cannot see an issue here from the Nx side of things. This involves angular and how it compiles the files. If you encounter another issue with it, it would be worth raising the issue on their repo.
