### ISSUE TITLE
npx create-nx-workspace test, installs schematics from v7

### ISSUE THREAD

**Issue by iangregsondev** [nrwl/nx#2248]
- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Performing a 

```
npx create-nx-workspace test
```

should install the latest (including schematics) from v8 (currently).

## Current Behavior

This still installs v7.x...

I saw an issue for it a while ago and it said it was fixed but the problem is still happening as far as i can see

**Comment by iangregsondev** [comment]
This means that doing something simple like this

```
ng add @nrwl/react
```

fails with errors, you need to first update the schematics before continuing.

**Comment by mehrad-rafigh** [comment]
Hi @iangregsondev 
have you tried the `--ignore-existing` flag, e.g. `npx --ignore-existing create-nx-workspace test`.
Can you please try this and let us know?

**Comment by iangregsondev** [comment]
Damb :-) ! Yes - it appears I have the schematics installed globally - so doing your command above, works great.

I presume the correct course of action here,is to remove the schematics globally ?

**Comment by mehrad-rafigh** [comment]
Good to hear it works :) 
I would recommend not to install it globally, expect the `@nrwl/cli` package if you want to run `nx` without prefixing it with `npx`. 
Please close the issue as well, if your problem is resolved

**Comment by iangregsondev** [comment]
Great thanks!
