### ISSUE TITLE
`npx nx@latest init` does not migrate from CRA to Vite

### ISSUE THREAD

**Issue by Lonli-Lokli** [nrwl/nx#22520]
### Current Behavior

Executed `npx nx@latest init` on non-edjected CRA (5.0.1), got questions re what commands are cacheable, re: cloud and that's all.

nx.json created but it still uses react-scripts and webpack

### Expected Behavior

Vite introduced

### Steps to Reproduce

--

### Nx Report

```shell
lateest nx added
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Lonli-Lokli** [comment]
from what I see in source code, it is expecting vite to be specified
https://github.com/nrwl/nx/blob/master/packages/nx/src/command-line/init/implementation/react/index.ts#L93

While docs saying that Vite will be enabled by default https://nx.dev/recipes/react/migration-cra

**Comment by Lonli-Lokli** [comment]
Also seems like v2 of init missing this CRA migration functionality

**Comment by leosvelperez** [comment]
Thanks for reporting this!

The automated CRA to Vite migration when running `nx init` was intentionally removed. The `nx init` command is now only concerned about adding Nx to the repo. It won't automatically do extra things like converting from CRA to Vite. It's easy enough to do so manually. There are some online resources you can read to do this:

https://www.freecodecamp.org/news/how-to-migrate-from-create-react-app-to-vite/
https://dev.to/henriquejensen/migrating-from-create-react-app-to-vite-a-quick-and-easy-guide-5e72
https://www.robinwieruch.de/vite-create-react-app/

The https://nx.dev/recipes/react/migration-cra document was outdated and no longer valid. We deleted it, and trying to access it will redirect you to the standard way of migrating any repo to Nx (running `npx nx@latest init`).
