### ISSUE TITLE
Project with `dependsOn` property with `serve-static` targets never runs

### ISSUE THREAD

**Issue by artuska** [nrwl/nx#22524]
### Current Behavior

I have an A app which depends on few microfrontends B and C apps `serve-static` target, so in my A app in `serve` target config I do:

```
"targets": {
    "serve": {
      "options": {
        "port": 4200
      },
      "dependsOn": [
        {
          "projects": "B",
          "target": "serve-static"
        },
        {
          "projects": "C",
          "target": "serve-static"
        }
      ]
    }
  },
```

After B and C `serve-static` command my A app does not run `serve` command, because `serve-static` commands just blocks my A app `serve` target.

### Expected Behavior

All `dependsOn` project targets should run in parallel and not block the main task. 

### Steps to Reproduce

1.

### Nx Report

```shell
Node   : 20.11.1
OS     : win32-x64
npm    : 10.2.4

nx (global)        : 18.1.3
nx                 : 18.1.3
@nx/js             : 18.1.3
@nx/linter         : 18.1.3
@nx/eslint         : 18.1.3
@nx/workspace      : 18.1.3
@nx/cypress        : 18.1.3
@nx/devkit         : 18.1.3
@nx/eslint-plugin  : 18.1.3
@nx/playwright     : 18.1.3
@nx/react          : 18.1.3
@nrwl/tao          : 18.1.3
@nx/vite           : 18.1.3
@nx/web            : 18.1.3
typescript         : 5.4.3
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
This is not how `dependsOn` works. Tasks which are depended upon must complete successfully. And `serve-static` does not complete since the server stays running.

We have a module federation executor which handles running the remote dev servers though.

Read the guide here:
https://nx.dev/concepts/module-federation/faster-builds-with-module-federation
