### ISSUE TITLE
Ability to query why the cache isn't being used

### ISSUE THREAD

**Issue by brianwestphal** [nrwl/nx#22530]
## Description
Debugging cache misses is a pain.  It seems like nx should be able to say why cache isn't being used for a particular target / project combination.

## Motivation
I want my builds to go as fast as possible and don't want to spend time debugging my build configuration.

## Suggested Implementation
Add a "--list-cache-miss-reasons" flag or similar

**Comment by FrozenPandaz** [comment]
This is a feature of Nx Cloud which is documented here>

https://nx.dev/recipes/troubleshooting/troubleshoot-cache-misses#troubleshoot-cache-misses

**Comment by brianwestphal** [comment]
@FrozenPandaz thanks. But I'm not using nx-cloud. I'm using nx entirely locally. So I believe this would still be helpful.
