### ISSUE TITLE
Next doesn't export static pages since version 18

### ISSUE THREAD

**Issue by Code-Divine** [nrwl/nx#22534]
### Current Behavior

Since updating to latest nx and next.js when trying to export a static site, the static pages under pages/ folder are not exported. I am using Next 14 and nx 18. The build succeeds without problem and I can even see this line  ✓ Generating static pages (10/10)  but the static pages are not in the folder. I see another .next folder with them in it, but not sure what that is. 

My next.config.js

`
//@ts-check

// eslint-disable-next-line @typescript-eslint/no-var-requires
const { withNx } = require('@nx/next/plugins/with-nx')

/**
 * @type {import('@nx/next/plugins/with-nx').WithNxOptions}
 **/
const nextConfig = {
  output: 'export',
  nx: {
    // Set this to true if you would like to to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: false
  },
  typescript: {
    // !! WARN !!
    // Dangerously allow production builds to successfully complete even if
    // your project has type errors.
    // !! WARN !!
    ignoreBuildErrors: true
  }
}

module.exports = withNx(nextConfig)
` 

My build target in project.json
`"build": {
      "executor": "@nx/next:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "outputPath": "dist/apps/landing"
      },
      "configurations": {
        "development": {
          "outputPath": "apps/landing"
        },
        "production": {}
      }
    },`

### Expected Behavior

The static pages should appear

### Steps to Reproduce

1.

### Nx Report

```shell
No failed build
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by rosshettel** [comment]
I too am running into this issue

**Comment by rosshettel** [comment]
@Code-Divine on a hunch I tried setting `distDir` to `out` in next.config.js - and that works as a workaround. Must be some bug in the `withNx` plugin that's composed that leaves that unset

**Comment by Code-Divine** [comment]
yeah, that was the problem. Previously next exported by default in directory named "exported" and now since next 14 and the changes how export is done it defaulted to that hidden directory. All you have to do is set distDir to "out" or "exported" in my case
