### ISSUE TITLE
nx serve fails when using options.headers

### ISSUE THREAD

**Issue by daannoltes** [nrwl/nx#22537]
### Current Behavior

After migrating from v18.0.2 to v18.1.3, when running `nx run bugreport:serve:development` with [headers](https://nx.dev/nx-api/angular/executors/dev-server#headers) we get the following error:

```
 NX   Cannot convert undefined or null to object
```

### Expected Behavior

 `nx run bugreport:serve:development` works with headers, as it did in v18.0.2

### Steps to Reproduce

1. Create a new Angular workspace ( Named ours `bugreport` )
2. `nx run bugreport:serve:development`
3. `** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **`
4. Add headers to `targets.serve.options`
```
        "serve": {
            "executor": "@nx/angular:dev-server",
            "configurations": {
                "production": {
                    "buildTarget": "bugreport:build:production"
                },
                "development": {
                    "buildTarget": "bugreport:build:development"
                }
            },
            "defaultConfiguration": "development",
            "options": {
                "headers": {
                    "content-security-policy": "default-src 'self';" // Our actual policy removed for security purposes
                }
            }
        },
```
5. `nx run bugreport:serve:development`
4. `NX   Cannot convert undefined or null to object`
6. Downgrade to Nx v18.0.2
7. `nx run bugreport:serve:development`
8.  `** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **`

### Nx Report

```shell
nx                 : 18.1.3
@nx/js             : 18.1.3
@nx/jest           : 18.1.3
@nx/linter         : 18.1.3
@nx/eslint         : 18.1.3
@nx/workspace      : 18.1.3
@nx/angular        : 18.1.3
@nx/cypress        : 18.1.3
@nx/devkit         : 18.1.3
@nx/eslint-plugin  : 18.1.3
@nrwl/tao          : 18.1.3
@nx/web            : 18.1.3
@nx/webpack        : 18.1.3
nx-cloud           : 18.0.0
typescript         : 5.3.3
```

### Package Manager Version

npm v9.6.5

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
I cannot reproduce this on macos with latest:

```
 NX   Report complete - copy this into the issue template

Node   : 20.11.0
OS     : darwin-arm64
npm    : 10.4.0

nx (global)        : 18.0.4
nx                 : 18.2.2
@nx/js             : 18.2.2
@nx/jest           : 18.2.2
@nx/linter         : 18.2.2
@nx/eslint         : 18.2.2
@nx/workspace      : 18.2.2
@nx/angular        : 18.2.2
@nx/devkit         : 18.2.2
@nx/eslint-plugin  : 18.2.2
@nrwl/tao          : 18.2.2
@nx/web            : 18.2.2
@nx/webpack        : 18.2.2
typescript         : 5.4.3
```

Can you try again with latest version of Nx? It could be a windows-only issue if it still exists on latest Nx.

**Comment by daannoltes** [comment]
@Coly010 Can confirm! After migrating to 18.2.2 the headers option works again.
Thanks for looking into it!
