### ISSUE TITLE
Possible improvement in "Enforce Module Boundaries" documentation

### ISSUE THREAD

**Issue by alperkay** [nrwl/nx#22538]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/features/enforce-module-boundaries

### Additional context or description

Assuming we have the following folder structure, all modules under the `apps/` folder have `"projectType": "application"` defined in their `project.json` file, whereas all modules under the `libs/` folder have `"projectType": "library"` defined in their `project.json` file. 

By looking at the documentation, we initially had the wrong assumption that we also have to define `tags` field in the `project.json` file of each app under the `/apps/` folder. But that was giving unexpected results (for instance still outputting the eslint error when both apps are tagged as "scope:external" and trying to import from each other. 

After some investigation in the source code, we found out that you don't need to define tags for packages which are `"projectType": "application"` and importing between such packages are by default always forbidden by the `"@nx/enforce-module-boundaries"` rule regardless.

I think it would be helpful if it's mentioned in the documentation. Something along the lines of "Importing between modules which have `"projectType": "application"` defined in their `project.json` file are always forbidden by the `"@nx/enforce-module-boundaries"` rule and there is no need or use to define "tags" for them. Tags are explicitly used for modules which have `"projectType": "library"` defined in their `project.json` .

```
apps/
  app-1/
    package.json
    project.json
  app-2/
    package.json
    project.json
libs/
  lib-1/
    package.json
    project.json
  lib-2/
    package.json
    project.json
```

**Comment by isaacplmann** [comment]
Applications are generated without an `index.ts` public API file and without a path alias in the tsconfig file.  That's what makes them not be able to be imported.  It isn't the enforce module boundaries rule.
