### ISSUE TITLE
It looks like all of libraries dependencies have not been built yet

### ISSUE THREAD

**Issue by jsleigh97** [nrwl/nx#22540]
### Current Behavior

Hey I need some help! Just recently switched angular app to nx monorepo and it will run perfectly on my local. However when I try to build my shared library it is failing due to error in first screenshot. I have tried multiple things and the nx.json file specifies that dependencies must be built first. If someone could help on this would be very much appreciated! Thanks!
![image](https://github.com/nrwl/nx/assets/156810491/bb8804ba-70db-4e93-a8d9-90b1b8caa28a)
![image](https://github.com/nrwl/nx/assets/156810491/b80732c4-03fa-44d4-88bc-2bec183183eb)

### Expected Behavior

The shared library should build successfully as the env 

### Steps to Reproduce

1. run npx nx build shared --configuration=development --verbose

### Nx Report

```shell
NX   Running target build for project shared and 1 task it depends on:

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

> nx run env:build:development  [existing outputs match the cache, left as is]

Building Angular Package

------------------------------------------------------------------------------
Building entry point 'env'
------------------------------------------------------------------------------
- Compiling with Angular sources in Ivy full compilation mode.
✔ Compiling with Angular sources in Ivy full compilation mode.
- Generating FESM2020
✔ Generating FESM2020
- Generating FESM2015
✔ Generating FESM2015
- Copying assets
✔ Copying assets
- Writing package manifest
✔ Writing package manifest
✔ Built env

------------------------------------------------------------------------------
Built Angular Package
 - from: C:\Lighthouse\lighthouse-web\libs\env
 - to:   C:\Lighthouse\lighthouse-web\dist\env
------------------------------------------------------------------------------

Build at: 2024-03-27T15:28:29.228Z - Time: 10639ms


> nx run shared:build:development

It looks like all of shared's dependencies have not been built yet:
- env

You might be missing a "targetDefaults" configuration in your root nx.json (https://nx.dev/reference/project-configuration#target-defaults),
or "dependsOn" configured in shared's project.json (https://nx.dev/reference/project-configuration#dependson)

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Running target build for project shared and 1 task it depends on failed

Failed tasks:

- shared:build:development

Hint: run the command with --verbose for more details.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Sorry, we will need more information before starting to understand why the library is not built. Can you provide a repo where the issue can be reproduced please?

**Comment by jsleigh97** [comment]
> Sorry, we will need more information before starting to understand why the library is not built. Can you provide a repo where the issue can be reproduced please?

I have sent you an email regarding giving access to repo.

**Comment by FrozenPandaz** [comment]
Sorry, I don't see the e-mail. Could you provide a minimal reproduction of the issue you're facing in a public repo please? We don't have enough information here to debug the issue.
