### ISSUE TITLE
Webpack's "interpolateEnvironmentVariablesToIndex" defaults to NODE_ENV=development

### ISSUE THREAD

**Issue by vergilfromadyen** [nrwl/nx#22563]
### Current Behavior

I'm investigating an issue where my build sometimes runs in development mode by default. In the course of my investigation I found a possible bug.

The "getClientEnvironment" function defaults to `NODE_ENV=development` [in this file](https://github.com/nrwl/nx/blob/71a0b0dce7d1dcd1b7b39e59e315093055b26b14/packages/webpack/src/utils/webpack/interpolate-env-variables-to-index.ts#L28).

This looks to be at odds with the executor [as defined here](https://github.com/nrwl/nx/blob/b051bbf600a24cccd283d2699ca225687489d1b2/packages/webpack/src/executors/webpack/webpack.impl.ts#L102-L103).

Is this on purpose?

### Expected Behavior

The default mode should be consistent

**Comment by jaysoo** [comment]
@vergilfromadyen There shouldn't be a conflict there as the executor sets `NODE_ENV` first, which is read in by the interpolate function. 

Note that `nx serve` will be in `development`, and `build` will be `production`. You can override that by using `NODE_ENV=staging nx serve`

Can you link a repro

**Comment by stefanlivens** [comment]
Oh wow, i have the same issue, but then with vite! And only on our CI agents.
I have a console.log(prcess.env.NODE_ENV) in my vite config, and locally it is 'prodcution' but on my  CI it is 'production' if i run "vite build", but 'development' if i run "nx build"

**Comment by vergilfromadyen** [comment]
> Oh wow, i have the same issue, but then with vite! And only on our CI agents. I have a console.log(prcess.env.NODE_ENV) in my vite config, and locally it is 'prodcution' but on my CI it is 'production' if i run "vite build", but 'development' if i run "nx build"

@stefanlivens I forgot to update the issue but Vite assumes NODE_ENV=development by default, potentially [here](https://github.com/vitejs/vite/blob/01af308dfd271df604a3fc9e9b3a9fcc2063e5d8/packages/vite/src/node/config.ts#L460). I haven't looked too far in the source code to figure out why this isn't the same as locally.
