### ISSUE TITLE
[Crystal][Nest] Wrong inferred test target in Nest E2E apps

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#22568]
### Context:
In nest e2e applications, a `e2e` target is explicitly defined and a `test` target is inferred as we can see in the next image
<img width="1381" alt="Screenshot 2024-03-28 at 3 04 44 PM" src="https://github.com/nrwl/nx/assets/371939/6bed05d6-8f4a-4be9-a3f3-c1ef5bedda8a">

Both are basically the same...

In my personal use case I execute `lint`, `test` and `build` in a DTE jobs inside my CI, and I execute `e2e` tests as part of other jobs, basically because e2e needs more preparations like browsers downloads for `cypress/playwright` or even DB services and other stuff.

### Problem:
Running `npx nx affected --base=$NX_BASE --head=$NX_HEAD -t lint,test,build --parallel=2` will execute test target of and Nest e2e application

### Expected Behavior

Nest e2e apps should not have a `test` target, so running something like this `npx nx affected --base=$NX_BASE --head=$NX_HEAD -t lint,test,build --parallel=2` should not execute any `test` job from an e2e app...

### Steps to Reproduce

1. Just create a new workspace with a new nest app, for example `demo-app` with a proper e2e project
2. Run `npx nx run-many --all -t lint,test,build --parallel=2`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.12.0
OS     : darwin-x64
npm    : 10.5.0

nx (global)        : 18.1.3
nx                 : 18.1.3
@nx/js             : 18.1.3
@nx/jest           : 18.1.3
@nx/linter         : 18.1.3
@nx/eslint         : 18.1.3
@nx/workspace      : 18.1.3
@nx/devkit         : 18.1.3
@nx/eslint-plugin  : 18.1.3
@nx/nest           : 18.1.3
@nx/next           : 18.1.3
@nx/node           : 18.1.3
@nx/playwright     : 18.1.3
@nx/react          : 18.1.3
@nrwl/tao          : 18.1.3
@nx/vite           : 18.1.3
@nx/web            : 18.1.3
@nx/webpack        : 18.1.3
typescript         : 5.3.3
---------------------------------------
Community plugins:
@nx-tools/nx-container : 5.2.0
```

### Package Manager Version

nom 10.5.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

On the other hand, for NextJS and React E2E applications using playwright, the targets presents are `e2e` and `e2e-ci`, so to maintain consistency we should have also e2e-ci for nest e2e apps?   

### Workaround

For now to fix my current issue, I updated my project.json to
```
{
  "name": "nest-app-e2e",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "implicitDependencies": ["nest-app"],
  "projectType": "application",
  "targets": {
    "test": {
      "executor": "nx:noop",
      "cache": true
    },
    "e2e": {
      "executor": "@nx/jest:jest",
      "outputs": ["{workspaceRoot}/coverage/{e2eProjectRoot}"],
      "options": {
        "jestConfig": "apps/nest-app-e2e/jest.config.ts",
        "passWithNoTests": true
      }
    }
  }
}
```

**Comment by gperdomor** [comment]
Related to https://github.com/nrwl/nx/discussions/22183

**Comment by ndcunningham** [comment]
Hey! Thanks for reporting this,

This should be fixed as of: https://github.com/nrwl/nx/pull/22987
