### ISSUE TITLE
Commabnd "nx format:check all" does not check ALL, but only uncommited? 

### ISSUE THREAD

**Issue by montella1507** [nrwl/nx#22578]
### Documentation issue

- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?
https://nx.dev/nx-api/nx/documents/format-check

### Additional context or description
Documentation says that command

nx format:check all

Should "Format all projects" however. It does nothing.  

To be precise i think it formats / checks ALL projects but only uncommited / touched files....

1)  prettier --check . 
Checks and show warning for 1800 files  

2) nx format:check all
 Checks nothing (only edited files)

3) IDE Prettier autoreformat on save works to

**Comment by JelleBruisten** [comment]
You need to pass options like this:

`nx format:check --all`

**Comment by montella1507** [comment]
Ah. Thanks.
