### ISSUE TITLE
tsconfig.app.ts and tsconfig.spec.ts cannot find type definition file

### ISSUE THREAD

**Issue by karolis-96** [nrwl/nx#22583]
### Current Behavior

<img width="463" alt="image" src="https://github.com/nrwl/nx/assets/163000830/d7d694d1-b1f6-4430-869a-da23b3d3d187">

As seen in screenshot I get message that cannot find type definition file for '@nx/react/...'

I've found similar issues in the pass, but nothing helped

### Expected Behavior

No error message

### Steps to Reproduce

1. Create new project `npx create-nx-workspace@latest react-monorepo --preset=react-monorepo` 
2. Use rspack instead of webpack
3. These files should be marked by IDE once setup is complete

### Nx Report

```shell
Node   : 21.2.0
OS     : win32-x64
yarn   : 1.22.19

nx (global)        : 18.1.3
nx                 : 18.2.1
@nx/js             : 18.2.1
@nx/jest           : 18.2.1
@nx/linter         : 18.2.1
@nx/eslint         : 18.2.1
@nx/workspace      : 18.2.1
@nx/devkit         : 18.2.1
@nx/eslint-plugin  : 18.2.1
@nx/react          : 18.2.1
@nrwl/tao          : 18.2.1
@nx/web            : 18.2.1
typescript         : 5.4.3
---------------------------------------
Community plugins:
@nx/rspack : 18.0.6
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Are there any errors when you run the `build` or `serve` command?

**Comment by karolis-96** [comment]
Closing this one, because not relevant to us anymore. 

It was probably IDE message, no errors when we `build` or `serve`
