### ISSUE TITLE
conflict with semicolons between prettier and typescript/javascript eslint confg

### ISSUE THREAD

**Issue by arrocke** [nrwl/nx#22599]
### Current Behavior

Using `plugin:@nx/javascript` or `plugin:@nx/typescript` in my eslint configuration along with prettier configured to remove semicolons results an @typescript-eslint/no-extra-semi error on the following code
```js
function test() {
  ;[1,2].forEach(console.log)
}
```

### Expected Behavior

This rule is disabled by default when extending the prettier eslint config because prettier inserts semicolons in places where this rule errors if they are present. In this case, prettier is being overprotective in inserting the semicolon, but we can't change prettier behavior.

### Steps to Reproduce

1. Set up a project with the default eslint config for javascript or typescript.
2. Configure prettier to remove semicolons.
3. Add the following code. Prettier will always insert a semicolon before this line
```
function test() {
  ;[1,2].forEach(console.log)
}
```
4. Try to lint the project

### Nx Report

```shell
Node   : 18.18.2
OS     : darwin-x64
npm    : 9.8.1

nx (global)        : 17.1.2
nx                 : 18.2.1
@nx/js             : 18.2.1
@nx/jest           : 18.2.1
@nx/linter         : 18.2.1
@nx/eslint         : 18.2.1
@nx/workspace      : 18.2.1
@nx/cypress        : 18.2.1
@nx/devkit         : 18.2.1
@nx/eslint-plugin  : 18.2.1
@nx/node           : 18.2.1
@nx/playwright     : 18.2.1
@nx/rollup         : 18.2.1
@nx/storybook      : 18.2.1
@nrwl/tao          : 18.2.1
@nx/vite           : 18.2.1
@nx/vue            : 18.2.1
@nx/web            : 18.2.1
@nx/webpack        : 18.2.1
typescript         : 5.0.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I think [this line](https://github.com/nrwl/nx/blob/master/packages/eslint-plugin/src/configs/typescript.ts#L44) in the typescript config (and the corresponding line in the javascript config) should be conditionally set based on `isPrettierAvailable`. If `isPrettierAvailable` is true, the the `@typescript-eslint/no-extra-semi` rule should be turned off.

I'm happy to open a PR to fix this. For now, we can override this ourselves in our config

**Comment by veniodev** [comment]
Having the same issue after the new version upgrade:
```shell
Node   : 20.14.0
OS     : win32-x64
npm    : 10.7.0

nx (global)        : 19.1.1
nx                 : 19.1.1
@nx/js             : 19.1.1
@nx/jest           : 19.1.1
@nx/linter         : 19.1.1
@nx/eslint         : 19.1.1
@nx/workspace      : 19.1.1
@nx/angular        : 19.1.1
@nx/cypress        : 19.1.1
@nx/devkit         : 19.1.1
@nx/eslint-plugin  : 19.1.1
@nrwl/tao          : 19.1.1
@nx/web            : 19.1.1
@nx/webpack        : 19.1.1
nx-cloud           : 19.0.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
---------------------------------------
Community plugins:
@ngrx/component-store                : 17.0.1
@ngrx/effects                        : 17.0.1
@ngrx/entity                         : 17.0.1
@ngrx/router-store                   : 17.0.1
@ngrx/schematics                     : 17.0.1
@ngrx/store                          : 17.0.1
@ngrx/store-devtools                 : 17.0.1
```

@arrocke until this fix, what would be the workaround?

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Since Nx 19.1.0, the `javascript` and `typescript` shared configs in the `@nx/eslint-plugin` package no longer configure the `@typescript-eslint/no-extra-semi` or `no-extra-semi` rules (https://github.com/nrwl/nx/commit/be6453cfbd7b422c4aaeefa13d0febb5c8d7327f). A migration was provided to extract the configuration for those rules to the user ESLint configuration to avoid breaking changes and let the users decide what to do with them. New workspaces won't have those rules configured. You can see the rationale for this change at https://github.com/nrwl/nx/pull/26011.

I'm closing this since those rules are no longer configured in the `@nx/eslint-plugin` package. Once you update to Nx 19.1.0 or later, you'll be in control of those rules and can easily prevent these conflicts with Prettier.
