### ISSUE TITLE
The file "" is outside of the configured rootDir'.'"

### ISSUE THREAD

**Issue by jsleigh97** [nrwl/nx#22607]
### Current Behavior

Hi everyone, I have switched a normal angular app to an nx monorepo and have came across an issue when building one of the libraries. I have attached the dep graph to see which libraries are pointing to each other. The shared library was added to be the global point where all the libraries can point to. I have moved files from allocate-web to shared and when I run nx run allocate-web:build:development --verbose I get the error in the second screenshot. Can anyone help me with this? Happy to give access to repo to look at the code deeper. 
![image](https://github.com/nrwl/nx/assets/156810491/657c0cdf-488d-4c05-9a66-c9a6922a5c40)
![image](https://github.com/nrwl/nx/assets/156810491/0aa865e9-e719-4b10-9a84-f12d79492953)

### Expected Behavior

The libraries should build with no issues. I can run it locally with no issues but when I try to build it is causing this error. This would be an issue when trying to deploy to test or production environment.

### Steps to Reproduce

1. I had to add a console.log in the directory 'node_modules/nx/src/utils/params.js
![image](https://github.com/nrwl/nx/assets/156810491/5eada1c1-037e-4fac-849e-8e54c7c1e300)
2. run in terminal - 'nx run allocate-web:build:development --verbose

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 16.14.2
OS     : win32-x64
npm    : 8.5.0

nx (global)    : 18.1.2
nx             : 18.1.2
@nx/js         : 18.1.2
@nx/jest       : 18.1.2
@nx/linter     : 18.1.2
@nx/eslint     : 18.1.2
@nx/workspace  : 18.1.2
@nx/angular    : 18.1.2
@nx/devkit     : 18.1.2
@nrwl/tao      : 18.1.2
@nx/web        : 18.1.2
@nx/webpack    : 18.1.2
typescript     : 4.9.5
---------------------------------------
Community plugins:
@ngrx/effects        : 15.4.0
@ngrx/eslint-plugin  : 15.4.0
@ngrx/router-store   : 15.4.0
@ngrx/store          : 15.4.0
@ngrx/store-devtools : 15.4.0
ngrx-immer           : 2.0.1
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by lemonCMS** [comment]
I am running into the same / similar problem with our angular application

i ran `nx migrate latest`  for me this triggered only minor updates on angular 17.2 -> 17.3 and nx 18.0 -> 18.2

But also the typescript package was updated from `5.3.3` -> `5.4.3`

With typescript 5.4.3 i got the message 
` File '....' is not under 'rootDir' '...\libs\shared\src'. 'rootDir' is expected to contain all source files`

When i install typescript 5.3.3 the error is gone and I'm able to build the application


```
 NX   Report complete - copy this into the issue template

Node   : 18.16.0
OS     : win32-x64
npm    : 9.5.1

nx                 : 18.2.1
@nx/js             : 18.2.1
@nx/jest           : 18.2.1
@nx/linter         : 18.2.1
@nx/eslint         : 18.2.1
@nx/workspace      : 18.2.1
@nx/angular        : 18.2.1
@nx/cypress        : 18.2.1
@nx/devkit         : 18.2.1
@nx/eslint-plugin  : 18.2.1
@nx/storybook      : 18.2.1
@nrwl/tao          : 18.2.1
@nx/web            : 18.2.1
@nx/webpack        : 18.2.1
typescript         : 5.4.3
---------------------------------------
Community plugins:
@compodoc/compodoc       : 1.1.21
@nebular/theme           : 13.0.0
@ngrx/component-store    : 17.1.1
@ngrx/effects            : 17.1.1
@ngrx/store              : 17.1.1
@ngrx/store-devtools     : 17.1.1
@storybook/angular       : 7.5.1
angular-auth-oidc-client : 17.0.0
ng-mocks                 : 14.11.0
```

**Comment by veniodev** [comment]
@lemonCMS I can confirm the same issue has happened to me and downgrading the typescript version resolved it.

```shell

Node   : 16.19.1
OS     : win32-x64
npm    : 8.19.3

nx (global)        : 18.0.4
nx                 : 18.2.2
@nx/js             : 18.2.2
@nx/jest           : 18.2.2
@nx/linter         : 18.2.2
@nx/eslint         : 18.2.2
@nx/workspace      : 18.2.2
@nx/angular        : 18.2.2
@nx/cypress        : 18.2.2
@nx/devkit         : 18.2.2
@nx/eslint-plugin  : 18.2.2
@nrwl/tao          : 18.2.2
@nx/web            : 18.2.2
@nx/webpack        : 18.2.2
nx-cloud           : 18.0.0
typescript         : 5.3.3
---------------------------------------
Community plugins:
@ngrx/component-store                : 17.0.1
@ngrx/effects                        : 17.0.1
@ngrx/entity                         : 17.0.1
@ngrx/router-store                   : 17.0.1
@ngrx/schematics                     : 17.0.1
@ngrx/store                          : 17.0.1
@ngrx/store-devtools                 : 17.0.1

```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Could you provide a reproduction so we can troubleshoot it?
