### ISSUE TITLE
[Rollup] Update rollup version to 4

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#22604]
### Current Behavior

Nx is using rollup v2.79.1 even when the latest version is 4.13.2

### Expected Behavior

Nx should use latest version of rollup

### Steps to Reproduce

1. Create a new Nx workspace
2. Install @nx/rollup package
3. Run `npx rollup --version` to see the installed rollup version

### Nx Report

```shell
nx report                               

 NX   Report complete - copy this into the issue template

Node   : 20.12.0
OS     : darwin-x64
npm    : 10.5.0

nx (global)        : 18.2.1
nx                 : 18.2.1
@nx/js             : 18.2.1
@nx/jest           : 18.2.1
@nx/linter         : 18.2.1
@nx/eslint         : 18.2.1
@nx/workspace      : 18.2.1
@nx/devkit         : 18.2.1
@nx/eslint-plugin  : 18.2.1
@nx/rollup         : 18.2.1
@nrwl/tao          : 18.2.1
typescript         : 5.4.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
The main changes that may affect us are to the plugin API. Need to check the plugin support for v3 and v4, if they are compatible then we can upgrade.

**Comment by jaysoo** [comment]
The PR is opened, but we should hold off on merging it until we're ready for Nx 19 release (later in April). Although there doesn't appear to be any breaking changes for our default setup, workspaces could have their own Rollup plugins that are not compatible with v4.

**Comment by gperdomor** [comment]
@jaysoo wow that was fast ❤️ ... Thank you...
