### ISSUE TITLE
Mocks are applied partially when testing on windows

### ISSUE THREAD

**Issue by nkv843** [nrwl/nx#22617]
### Current Behavior

Mock a function inside donor lib during testing dependent lib.

If this function is used in both donor and dependent libs, it will be mock only for dependent and original inside donor lib.

So, due to this behavior, tests in attached repo are failing

### Expected Behavior

If we mock any function inside another module, it must be represented as a mocked function everywhere else

tests in attached repo should not fail

### GitHub Repo

https://github.com/nkv843/nx-mock-within-module-issue

### Steps to Reproduce

0. use windows machine
1. clone repo https://github.com/nkv843/nx-mock-within-module-issue 
2. npm i 
3. npm run test

### Nx Report

```shell
Node   : 18.19.1
OS     : win32-x64
npm    : 10.2.4

nx (global)        : 16.10.0
nx                 : 18.2.1
@nx/js             : 18.2.1
@nx/jest           : 18.2.1
@nx/linter         : 18.2.1
@nx/eslint         : 18.2.1
@nx/workspace      : 18.2.1
@nx/devkit         : 18.2.1
@nx/eslint-plugin  : 18.2.1
@nx/react          : 18.2.1
@nrwl/tao          : 18.2.1
@nx/web            : 18.2.1
@nx/webpack        : 18.2.1
typescript         : 5.4.3
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

reproducible only on windows machines

**Comment by vadimb** [comment]
Hi, sorry to bother but @leosvelperez have you had a chance to look at the example repo? Is there something we need to to help to locate the issue? 

I see there was a similar issue reported https://github.com/nrwl/nx/issues/10029.

I work with @nkv843 and our colleagues that use Win are having a pain now bc of this. Any help/hints appreciated.

**Comment by nkv843** [comment]
Hi! 
Any updates on this so far @FrozenPandaz? 
Maybe you need more inputs from my side?

**Comment by dorin-js** [comment]
Same issue, any solution or at least workaround so far?

**Comment by leosvelperez** [comment]
Hey all! Thanks for reporting this, and apologies for the delay.

I'll try to set up a Windows VM to investigate this and I'll post here any updates. Could you confirm if this is a Windows-only issue?

**Comment by vadimb** [comment]
Hi, we see it only on Windows - Linux and macOS behave as expected. Let me know please if you need more info or explanations we are more then happy to share.

**Comment by nkv843** [comment]
Great job! Thanks a lot @FrozenPandaz 
I think this is also the solution for #10029 and maybe https://github.com/nrwl/nx-react-native/issues/35
