### ISSUE TITLE
Error on local build Expo EAS with Yarn 4.1.1

### ISSUE THREAD

**Issue by guillempuche** [nrwl/nx#22631]
### Current Behavior

Run EAS build with Nx EAS Pre Install script with Yarn 4.1 throws an error.

### Expected Behavior

Build locally the app on my Android emulator.

### Steps to Reproduce

1. Files
// `apps/xiroi-expo/project.json`
```json
...
               "build-dev-android": {
			"executor": "@nx/expo:build",
			"options": {
				"platform": "android",
				"profile": "development",
				"local": true,
				"clearCache": false
			}
		},
...
```

// `tools/scripts/eas-build-pre-install.mjs`
```js
/*
 * This script is used to patch the '@nx/expo' package to work with EAS Build.
 * It is run as the eas-build-pre-install script in the 'package.json' of expo app.
 * It is executed as 'node tools/scripts/eas-build-pre-install.mjs <workspace root> <project root>'
 * It will copy the dependencies and devDependencies from the workspace package.json to project's package.json.
 * This is needed because EAS Build does the install in project's directory and not workspace's directory.
 */
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const [workspaceRoot, projectRoot] = process.argv.slice(2);
if (!workspaceRoot) {
  throw new Error('Missing workspace root');
}
if (!projectRoot) {
  throw new Error('Missing project root');
}
try {
  const workspacePackage = JSON.parse(
    readFileSync(join(workspaceRoot, 'package.json')).toString()
  );
  const projectPackage = JSON.parse(
    readFileSync(join(projectRoot, 'package.json')).toString()
  );
  projectPackage.dependencies = workspacePackage.dependencies;
  projectPackage.devDependencies = workspacePackage.devDependencies;
  writeFileSync(
    join(projectRoot, 'package.json'),
    JSON.stringify(projectPackage, null, 2)
  );
} catch (e) {
  console.error('Error reading package.json file', e);
}
```
2. `yarn exec nx run xiroi-expo:build-dev-android`
3. I process with interactive dialog
4. Get error

### Nx Report

```shell
Node   : 20.11.0
OS     : darwin-arm64
yarn   : 4.1.1

nx                : 18.2.2
@nx/js            : 18.2.2
@nx/jest          : 18.2.2
@nx/linter        : 18.2.2
@nx/eslint        : 18.2.2
@nx/workspace     : 18.2.2
@nx/cypress       : 18.2.2
@nx/devkit        : 18.2.2
@nx/expo          : 18.2.2
@nx/next          : 18.2.2
@nx/react         : 18.2.2
@nx/react-native  : 18.2.2
@nx/storybook     : 18.2.2
@nrwl/tao         : 18.2.2
@nx/vite          : 18.2.2
@nx/web           : 18.2.2
@nx/webpack       : 18.2.2
typescript        : 5.4.3
```

### Failure Logs

```shell
✔ Using remote Android credentials (Expo server)
✔ Using Keystore from configuration: Build Credentials sKIJ_f5Qy3 (default)
✔ Compressed project files 2s (4.2 MB)
ANDROID_NDK_HOME environment variable was not specified, continuing build without NDK
[SETUP_WORKINGDIR] Preparing workingdir /var/folders/ys/spt316fs5sxck01gjy40s1rc0000gn/T/eas-build-local-nodejs/5e53c180-8067-49e4-baa6-dc79011017dd
[START_BUILD] Starting build
  "job": {
    "type": "managed",
    "platform": "android",
    "projectRootDirectory": "apps/xiroi-expo",
    "projectArchive": {
      "type": "PATH",
      "path": "/var/folders/ys/spt316fs5sxck01gjy40s1rc0000gn/T/eas-cli-nodejs/6fdcab7d-0cc4-4940-ba1c-9c301f7e0376.tar.gz"
    },
    "builderEnvironment": {},
    "cache": {
      "disabled": false,
      "paths": [],
      "clear": false
    },
    "updates": {},
    "developmentClient": true,
    "buildType": "apk",
    "username": "xiroi",
    "experimental": {},
    "mode": "build",
    "triggeredBy": "EAS_CLI"
  }
[PRE_INSTALL_HOOK] Script 'eas-build-pre-install' is present in package.json, running it...
[PRE_INSTALL_HOOK] Internal Error: ENOENT: no such file or directory, stat '/private/var/folders/ys/spt316fs5sxck01gjy40s1rc0000gn/T/eas-build-local-nodejs/5e53c180-8067-49e4-baa6-dc79011017dd/build/.yarn/releases/yarn-4.1.1.cjs'
[PRE_INSTALL_HOOK] Error: ENOENT: no such file or directory, stat '/private/var/folders/ys/spt316fs5sxck01gjy40s1rc0000gn/T/eas-build-local-nodejs/5e53c180-8067-49e4-baa6-dc79011017dd/build/.yarn/releases/yarn-4.1.1.cjs'
[PRE_INSTALL_HOOK] 
Error: yarn run eas-build-pre-install exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/guillem/.npm/_npx/df16f1aa38b72159/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:633:26)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:518:28)
    at Pipe.<anonymous> (node:net:337:12)
    ...
    at spawnAsync (/Users/guillem/.npm/_npx/df16f1aa38b72159/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawn (/Users/guillem/.npm/_npx/df16f1aa38b72159/node_modules/@expo/turtle-spawn/dist/index.js:16:47)
    at runHookIfPresent (/Users/guillem/.npm/_npx/df16f1aa38b72159/node_modules/@expo/build-tools/dist/utils/hooks.js:34:42)
    at async /Users/guillem/.npm/_npx/df16f1aa38b72159/node_modules/@expo/build-tools/dist/common/setup.js:48:9
    at async BuildContext.runBuildPhase (/Users/guillem/.npm/_npx/df16f1aa38b72159/node_modules/@expo/build-tools/dist/context.js:98:28)
    at async setupAsync (/Users/guillem/.npm/_npx/df16f1aa38b72159/node_modules/@expo/build-tools/dist/common/setup.js:47:5)
    at async buildAsync (/Users/guillem/.npm/_npx/df16f1aa38b72159/node_modules/@expo/build-tools/dist/builders/android.js:38:5)
    at async runBuilderWithHooksAsync (/Users/guillem/.npm/_npx/df16f1aa38b72159/node_modules/@expo/build-tools/dist/builders/common.js:12:13)
    at async Object.androidBuilder (/Users/guillem/.npm/_npx/df16f1aa38b72159/node_modules/@expo/build-tools/dist/builders/android.js:24:16)
    at async buildAndroidAsync (/Users/guillem/.npm/_npx/df16f1aa38b72159/node_modules/eas-cli-local-build-plugin/dist/android.js:66:12)

Build failed
Unknown error. See logs of the Pre-install hook build phase for more information.
npx exited with non-zero code: 1
    Error: build command failed.

 NX   1



———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target build-dev-android for project xiroi-expo (11s)

   ✖  1/1 failed
   ✔  0/1 succeeded [0 read from cache]
```

### Package Manager Version

yarn 4.1.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The `package.json` has Yarn configured, check it below. You can also do it running `yarn set version berry`.

```json
...
  "engines": {
    "node": ">=20"
  },
  "packageManager": "yarn@4.1.1"
...
```

// `.yarnrc.yml`

```yaml
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.1.1.cjs
```
  
Other version of packages:
  - `expo` 50.0.14
  - `eas-cli` 7.6.2

I read https://docs.expo.dev/build-reference/npm-cache-with-yarn/, but I don't know what to do. According to ChatGTP:
> The Expo guide script focuses on optimizing package installation by leveraging EAS's npm cache. In contrast, your script focuses on dependency management within a monorepo setup, ensuring that project dependencies are correctly set up for the build.

**Comment by guillempuche** [comment]
I haven't check yet the post install script from Nx example `tools/scritps/eas-build-post-install.mjs`.

```js
/**
 * This script is used to patch the '@nx/expo' package to work with EAS Build.
 * It is run as a eas-build-post-install script in the 'package.json' of expo app.
 * It is executed as 'node tools/scripts/eas-build-post-install.mjs <workspace root> <project root>'
 * It will create a symlink from the project's node_modules to the workspace's node_modules.
 */

import { existsSync, symlink } from 'node:fs'
import { join } from 'node:path'

const [workspaceRoot, projectRoot] = process.argv.slice(2)

if (existsSync(join(workspaceRoot, 'node_modules'))) {
	console.log('Symlink already exists')
	process.exit(0)
}

symlink(
	join(projectRoot, 'node_modules'),
	join(workspaceRoot, 'node_modules'),
	'dir',
	err => {
		if (err) console.log(err)
		else {
			console.log('Symlink created')
		}
	},
)
```

**Comment by xiongemi** [comment]
i tried to build with eas locally. here are what did:
- install expo-dev-client at workspace root
- then i ran into an issue "eas-cli-local-build-plugin: not found". it turns out i have to downgrade eas-cli version to 6 (https://github.com/expo/eas-cli/issues/2000)

**Comment by guillempuche** [comment]
@xiongemi, do you have a solution?

**Comment by guillempuche** [comment]
React Native 0.74 https://reactnative.dev/blog/2024/04/22/release-0.74 has Yarn 3 as the default package manager for new projects. Not npm.

It's a good moment to handle EAS build in Expo with Yarn v4. 😉

**Comment by guillempuche** [comment]
Expo team is recommending to use build development. A screenshot from one of its team members.

<img width="637" alt="imatge" src="https://github.com/nrwl/nx/assets/3519924/14bb174d-ec77-4847-91d1-3ed593089275">

**Comment by xiongemi** [comment]
i submit a pr https://github.com/nrwl/nx/pull/26992 fixing this, i think the easiest work around would just copy the lock file form workspace root to project root, then it seems local build would work for me.

**Comment by xiongemi** [comment]
the quickest workaround would just be:
- go the app and run `npm run eas-build-pre-install` then delete this script from the package.json's scripts.
now when you run the local build, it should work with yarn 4
i am working on a pr to do a proper fix for this

**Comment by xiongemi** [comment]
another fix would be in package.json, add your app and library to workspaces, something like:
```
  "workspaces": [
    "apps/*",
    "libs/*"
  ],
```

**Comment by guillempuche** [comment]
It didn't work.

**Comment by xiongemi** [comment]
> It didn't work.

what error are you getting?

**Comment by vaagnavanesyan** [comment]
@guillempuche same here. I've used Nx + Expo for a year, and it was a year of struggling with bugs and errors. Now I've ended up with plain Yarn 4 Workspaces and kept Nx only as a task runner and graph builder (to determine what is affected).

Nx may be good for library-oriented monorepos, but I found it inappropriate for application-centric monorepos with web, API, or mobile apps. It's sad that I wasted a year to figure that out because the official docs describe a lot of plugins and executors, which are nothing more than built-in workarounds for Nx-based problems like path resolving.

When using Nx, you get caught in vendor lock-in, which is probably not what you'd want.

It's sad that Nx is the most mentioned tool for monorepos, but in reality, you end up struggling with a bunch of errors. It's definitely not what a production-ready tool should be.

For additional context, I used Nx in a monorepo with TS libraries, web and mobile applications, and a NestJS backend. Now I've switched to Yarn Workspaces, migrated the web project to Vite, and everything works like a charm. Most importantly, it all works predictably.

**Comment by alifa20** [comment]
This PR: https://github.com/nrwl/nx/pull/26992 which is closing this issue, has broken yarn v4 for me. EAS does not seem to work anymore. 

This workaround used to work for me with NX 19.6.4,  but he PR seems to break EAS and I no longer can build with EAS anymore. Any suggestions how to fix this?

> the quickest workaround would be: go the app and run `npm run eas-build-pre-install` then delete this script from the package.json's scripts. now when you run the local build, it should work with yarn 4 i am working on a pr to do a proper fix for this
