### ISSUE TITLE
React HMR doesn't work for inference based application

### ISSUE THREAD

**Issue by unknownconstant** [nrwl/nx#22658]
### Current Behavior

I started a new NX project which defaulted to using inference plugins. When editing the react tsx files I noticed HMR wasn't working, the page was reloading in its entirety when saving, rather than just updating the relevant component.

When going to investigate and troubleshoot, I noticed that the project.json for the application was basically empty other than a comment suggesting I use some web UI to look at project tasks. I've put so much time into troubleshooting nx's quirks before that when faced with another non-functional project straight from the generator my heart sank that I was going to be stuck with a headache for another couple of days.

Fortunately, I have a working project.json that I've been able to copy. When running from that and removing references to the inference plugin everything works as it should. I've tried the new way of doing things with an open mind, but it didn't give me a production-ready experience so I'm steering well clear of the inference stuff.

### Expected Behavior

HMR should work for new react applications when using the new inference plugins. It should be easier to choose whether the new inference thing should be used, or the more stable project.json

### Steps to Reproduce

1. Create a new react project using inference
2. No HMR

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 21.7.1
OS     : darwin-x64
npm    : 10.5.0

nx (global)        : 17.0.2
nx                 : 18.2.1
@nx/js             : 18.2.1
@nx/jest           : 18.2.1
@nx/linter         : 18.2.1
@nx/eslint         : 18.2.1
@nx/workspace      : 18.2.1
@nx/devkit         : 18.2.1
@nx/esbuild        : 18.2.1
@nx/eslint-plugin  : 18.2.1
@nx/node           : 18.2.1
@nx/react          : 18.2.1
@nx/rollup         : 18.2.1
@nrwl/tao          : 18.2.1
@nx/web            : 18.2.1
@nx/webpack        : 18.2.1
typescript         : 5.4.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
If you are using Project Crystal (inferred targets) then, the webpack config you provide should contain details about `hmr`, which should be enabled by default if you are using `webpack-dev-server` v4+. 

The Webpack plugin uses the `webpack-cli` which contains `webpack-dev-server` v5+
When you make changes to your source running the `serve` command you should see something like
```shell
main.4bf405a2a5343c78.hot-update.js
```
Inside of your log.

Can you provide a small repro?
