### ISSUE TITLE
@nx/react/plugins/storybook trying to add our custom plugins

### ISSUE THREAD

**Issue by rexkenley** [nrwl/nx#22661]
### Current Behavior

After upgrading our nx@18.2.1 repo storybook to version 8, I am getting this error

![image](https://github.com/nrwl/nx/assets/10548251/c9543859-30f6-430e-a1f7-832b967ce311)

### Expected Behavior

Generate storybook site.

### Steps to Reproduce

1. npx storybook@latest upgrade 
2. Answer yes to every prompt

### Nx Report

```shell
Node   : 20.11.1
OS     : win32-x64
npm    : 10.2.4
 
nx                 : 18.2.1
@nx/js             : 18.2.1
@nx/jest           : 18.2.1
@nx/linter         : 18.2.1
@nx/eslint         : 18.2.1
@nx/workspace      : 18.2.1
@nx/cypress        : 18.2.1
@nx/devkit         : 18.2.1
@nx/eslint-plugin  : 18.2.1
@nx/playwright     : 18.2.1
@nx/react          : 18.2.1
@nx/rollup         : 18.2.1
@nx/storybook      : 18.2.2
@nrwl/tao          : 18.2.1
@nx/web            : 18.2.1
@nx/webpack        : 18.2.1
typescript         : 5.4.3
---------------------------------------
Community plugins:
<redacted>
---------------------------------------
Local workspace plugins:
<redacted>
---------------------------------------
The following packages should match the installed version of nx
  - @nx/storybook@18.2.2
  - @nrwl/storybook@18.2.2

<redacted>
└─┬ @nx/storybook@18.2.2
  └── @nrwl/storybook@18.2.2
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Could you provide a repo where we can reproduce this issue please?

**Comment by rexkenley** [comment]
It would be difficult to provide a repo. But I was able to work around it by deleting the nx .cache folder every time it happens. 

Could that be a clue?
