### ISSUE TITLE
@nrwl/workspace - nx workspace-schematic my-schematic --help doesn't invoke help on custom schematic

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#2267]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

```
nx workspace-schematic my-schematic --help
```

Should print out to terminal help based on custom schematic schema

## Current Behavior

- I've developed custom nx schematic (generated via `nx g @nrwl/workspace:workspace-schematic my-schematic` 
- when I wanna get help (by printing out supported schematic schema options) by executing `nx workspace-schematic my-schematic --help`, instead of getting proper help I'm getting output of `nx workspace-schematic --help`
![image](https://user-images.githubusercontent.com/1223799/71783778-dbd1c800-2feb-11ea-98ec-e87f8f89fb7b.png)

### Context

```
 @nrwl/angular : Not Found
  @nrwl/cli : 8.9.0
  @nrwl/cypress : 8.9.0
  @nrwl/eslint-plugin-nx : 8.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 8.9.0
  @nrwl/linter : 8.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 8.9.0
  @nrwl/react : 8.9.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.9.0
  @nrwl/web : 8.9.0
  @nrwl/workspace : 8.9.0
  typescript : 3.7.3
```

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.
