### ISSUE TITLE
Unable to import css file from global files

### ISSUE THREAD

**Issue by karolis-96** [nrwl/nx#22691]
### Current Behavior

Trying to declare `theme.css` inside `root/global/theme/theme.css` (global is library) and use it in app as `import '@Theme/theme.css`

project.json (inside `root/global/theme`)
```
{
  "name": "theme",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "global/theme",
  "projectType": "library",
  "tags": []
}
```

tsconfig.base.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": ["es2020", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@Theme": ["global/theme"]
    }
  },
  "exclude": ["node_modules", "tmp"]
}
```

In `root/apps/admin`App.tsx` trying to import as `import '@Theme/theme.css`

### Expected Behavior

theme.css file is loaded

### Steps to Reproduce

1. Run `npx create-nx-workspace@latest react-monorepo --preset=react-monorepo --packageManager=yarn`
2. Use vite for react
3. Add library `nx g @nx/react:library theme --directory=global/theme --bundler=none`
4. Add `theme.css` file inside `global/theme` and remove unnecessary files
5. Update `project.json` and `tsconfig.base.json` files to correspond with correct path
6. Try to import theme.css inside application folder

### Nx Report

```shell
Node   : 21.2.0
OS     : win32-x64
yarn   : 1.22.19

nx (global)        : 18.1.3
nx                 : 18.2.2
@nx/js             : 18.2.2
@nx/linter         : 18.2.2
@nx/eslint         : 18.2.2
@nx/workspace      : 18.2.2
@nx/devkit         : 18.2.2
@nx/eslint-plugin  : 18.2.2
@nx/react          : 18.2.2
@nrwl/tao          : 18.2.2
@nx/vite           : 18.2.2
@nx/web            : 18.2.2
typescript         : 5.4.4
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Can you provide a repo which we can look at to reproduce your issue?

Which CSS library are you using?

The tsconfig paths are also for typescript code, not the styles so those are not relevant.

**Comment by karolis-96** [comment]
thanks for reply. Sure here is the [link](https://github.com/karolis-666/monorepo-nx) of repo

currently just testing out with plain css. Note: this repro repository also tries to import `.jpeg` file which also fails, you can comment that part out, I am not sure for now is vite configuration is missing something ir it's nx related
