### ISSUE TITLE
Cannot build nx/js libraries with sibling library reference

### ISSUE THREAD

**Issue by rexkenley** [nrwl/nx#22697]
### Current Behavior

When I try to build a library that references a sibling library it errors out with little details
![image](https://github.com/nrwl/nx/assets/10548251/aa5fb7bc-1818-418f-8d87-57863c2bb462)
![image](https://github.com/nrwl/nx/assets/10548251/c1260a98-a5fb-4bfb-91f0-cc3bccd85a1a)

### Expected Behavior

Build the library

*When I remove the reference it works
![image](https://github.com/nrwl/nx/assets/10548251/c9a5562a-9e43-44f0-b95d-f0f666e44f4d)

### Steps to Reproduce

1. Reference a function in another library
2. Build library

### Nx Report

```shell
Node   : 20.11.1
OS     : win32-x64
npm    : 10.2.4
 
nx                 : 18.2.2
@nx/js             : 18.2.2
@nx/jest           : 18.2.2
@nx/linter         : 18.2.2
@nx/eslint         : 18.2.2
@nx/workspace      : 18.2.2
@nx/cypress        : 18.2.2
@nx/devkit         : 18.2.2
@nx/eslint-plugin  : 18.2.2
@nx/playwright     : 18.2.2
@nx/react          : 18.2.2
@nx/rollup         : 18.2.2
@nx/storybook      : 18.2.2
@nrwl/tao          : 18.2.2
@nx/web            : 18.2.2
@nx/webpack        : 18.2.2
typescript         : 5.4.4
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
@rexkenley Is the referenced library also buildable? For JS libs/packages, all dependencies must be buildable as well. If the dependencies are not buildable you can run `nx g @nx/js:setup-build` generator to add the target.

**Comment by jaysoo** [comment]
I'm going to close this, as I see that you are using `@nx/rollup:rollup`, and consuming other buildable libraries is working. Consuming non-buildable libraries does not work, and is intentional.

If you have an use-case to use non-buildable libraries please open a [discussion](https://github.com/nrwl/nx/discussions) as it is a feature/enhancement.
