### ISSUE TITLE
Cannot build nx/js libraries with sibling library reference

### ISSUE THREAD

**Issue by rexkenley** [nrwl/nx#22706]
### Current Behavior

When I try to build a library (buildable & publishable) that references a sibling library (buildable & publishable) it errors out with little details
![image](https://github.com/nrwl/nx/assets/10548251/e4a08fc4-8035-4265-9a05-e5b9bc3c22d1)
![image](https://github.com/nrwl/nx/assets/10548251/ebbe6942-b8ed-4a6c-b138-946a871d7bf3)

### Expected Behavior

Build the library

*When I remove the reference it works
![image](https://github.com/nrwl/nx/assets/10548251/efd043e9-f63e-4e1c-abc0-dce0aac738c2)

### Steps to Reproduce

1. Reference a function in another buildable/publishable library
2. Build library

### Nx Report

```shell
Node   : 20.11.1
OS     : win32-x64
npm    : 10.2.4
 
nx                 : 18.2.2
@nx/js             : 18.2.2
@nx/jest           : 18.2.2
@nx/linter         : 18.2.2
@nx/eslint         : 18.2.2
@nx/workspace      : 18.2.2
@nx/cypress        : 18.2.2
@nx/devkit         : 18.2.2
@nx/eslint-plugin  : 18.2.2
@nx/playwright     : 18.2.2
@nx/react          : 18.2.2
@nx/rollup         : 18.2.2
@nx/storybook      : 18.2.2
@nrwl/tao          : 18.2.2
@nx/web            : 18.2.2
@nx/webpack        : 18.2.2
typescript         : 5.4.4
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

https://github.com/nrwl/nx/issues/22697 is the original issue that was closed. I don't know why since the answer is not applicable. I am not asking for a new feature.

**Comment by jaysoo** [comment]
@rexkenley We need a repro to debug this. From what I can tell, you are importing `ui` into `util`. When you build `util`, it must also build dependencies (i.e. `ui`). If `ui` is not buildable, then building `util` will fail.

Can you try running `nx build ui` and see what error is coming from that?

**Comment by jaysoo** [comment]
There is an error building dependencies, perhaps it's confusing since it's not printed. I have a PR to fix that https://github.com/nrwl/nx/pull/22707

**Comment by rexkenley** [comment]
@jaysoo, utils only references models. ui is another library not being referenced by utils.
![image](https://github.com/nrwl/nx/assets/10548251/cf364c0d-f555-4843-89f1-66f4cecab2f9)

models build is successful
![image](https://github.com/nrwl/nx/assets/10548251/3f6448d6-aafe-4fd0-bc1a-b4ab0bd4670f)

**Comment by jaysoo** [comment]
We'll patch the error printing, but in the meantime you can edit `node_modules/@nx/rollup/src/executors/rollup/rollup.impl.js` and `console.log` the error to see: https://github.com/nrwl/nx/blob/master/packages/rollup/src/executors/rollup/rollup.impl.ts#L140-L144

**Comment by rexkenley** [comment]
Thanks @jaysoo, I will try that and let you know.

**Comment by rexkenley** [comment]
@jaysoo This is the error output
![image](https://github.com/nrwl/nx/assets/10548251/19bc35a7-6c57-4e98-b586-d7ef5049cec7)

**Comment by jaysoo** [comment]
@rexkenley It looks like you may have a type error. Do you see any diagnostic info higher up?

**Comment by rexkenley** [comment]
@jaysoo, no that screenshot is everything.

Is there a way to make it display more diagnostic?

**Comment by rexkenley** [comment]
@jaysoo, your clue helped me solve the issue. I did not include a d.ts file which finally showed the files with the wrong types. After excluding those files, I was finally able to execute a successful build.

Thanks!
