### ISSUE TITLE
Project Crystal and vite build input configuration does not work as expected

### ISSUE THREAD

**Issue by conmute** [nrwl/nx#22714]
### Current Behavior

On changed vite.config.ts:build.rollupOptions with custom input i have an error about dependencies without any more details

 NX   Failed to create dependencies. See above for errors
 
 error is comming from:
 
 ```
     at buildProjectGraphUsingContext (/Users/ross/.ghq/github.com/DelveNetwork/inputscribe/node_modules/.pnpm/nx@18.2.1_@swc-node+register@1.9.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/build-project-graph.js:138:15)
```

Note: running `npx vite build` in `<root>apps/appname` folder works but then it works outside of nx capabilities

### Expected Behavior

I should run `nx build appname` and should see the build command from `nx show appname --web`. 

### Steps to Reproduce

1. Setup any vite project where w can have empty target
2. Modify vite.config.ts to have custom input with `build.rollupOptions.input.name = 'page/different.html'` page and create the `<root>/apps/appname/pages/different.html` for it accordingly
3. Rename `<root>/apps/appname/index.html` entry to `index.html.bak`
4. Run `nx build appname --verbose` or `nx show appname --web --verbose`

You will see that it fails to get dependencies, yet I expected to work with rollupOptions.input that I had provided

### Nx Report

```shell
After `nx reset` was able to run `nx report` the output:


> nx report

 NX   Report complete - copy this into the issue template

Node   : 20.12.0
OS     : darwin-x64
pnpm   : 8.15.6

nx                 : 18.2.1
@nx/js             : 18.2.1
@nx/linter         : 18.2.1
@nx/eslint         : 18.2.1
@nx/workspace      : 18.2.1
@nx/cypress        : 18.2.1
@nx/devkit         : 18.2.1
@nx/eslint-plugin  : 18.2.1
@nx/playwright     : 18.2.1
@nx/react          : 18.2.1
@nrwl/tao          : 18.2.1
@nx/vite           : 18.2.1
@nx/web            : 18.2.1
typescript         : 5.2.2
```
```


### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by nzacca** [comment]
This might be related to: https://github.com/nrwl/nx/blob/master/packages/vite/src/plugins/plugin.ts#L258

Nx is looking for an `inputs` property to determine whether or not the project is buildable. The actual property is `input` (as the OP has it): https://rollupjs.org/configuration-options/#input

Might be able to workaround the issue by adding a fake property:

```js
  rollupOptions: {
    input: { /* normal config */ },
    /* @ts-ignore */
    inputs: {} // fake one to force Nx to recognize the build
  } 
```

**Comment by JonScottLee** [comment]
I am also having this issue, in a brand new Nx project. As soon as I generate a ui library by running `npx nx g lib any-lib-name-here`, all subsequent Nx calls fail (generating apps, libs, looking at dep graph, etc), with the same error original poster notes.

**Comment by JonScottLee** [comment]
> I am also having this issue, in a brand new Nx project. As soon as I generate a ui library by running `npx nx g lib any-lib-name-here`, all subsequent Nx calls fail (generating apps, libs, looking at dep graph, etc), with the same error original poster notes.

Reverting back to Nx version 18.2.1 fixes the issue for me.

**Comment by JoshuaCWebDeveloper** [comment]
I've had this error happen twice in the past week with two separate newly created nx workspaces.

The first time was with a single project workspace using webpack, and I resolved the issue by re-running `npm install`.

The second time was with a multi-project workspace using vite, and I resolved the issue by checking out the head of my git branch erasing all modifications to all files (including changes to `package.json` and `package-lock.json`), re-running the nx command (which then worked), and then immediately restoring all of the modifications (using a temp branch), upon which the nx command would still work.

Very weird. My only guess is that there must be some sort of cache somewhere that is getting out of sync with the working directory.

**Comment by JoshuaCWebDeveloper** [comment]
> I've had this error happen twice in the past week with two separate newly created nx workspaces.
> 
> The first time was with a single project workspace using webpack, and I resolved the issue by re-running `npm install`.
> 
> The second time was with a multi-project workspace using vite, and I resolved the issue by checking out the head of my git branch erasing all modifications to all files (including changes to `package.json` and `package-lock.json`), re-running the nx command (which then worked), and then immediately restoring all of the modifications (using a temp branch), upon which the nx command would still work.
> 
> Very weird. My only guess is that there must be some sort of cache somewhere that is getting out of sync with the working directory.

Just had it happen again. This time neither of the above two methods worked. However, deleting my `.nx` directory solved the issue.
