### ISSUE TITLE
Add ability to set memoryLimit of ForkTsCheckerWebpackPlugin

### ISSUE THREAD

**Issue by jbojcic1** [nrwl/nx#2272]
Currently there is no way to set the memory limit for the ForkTsCheckerWebpackPlugin. Only number of workers can be set.

This can be a problem if you have limited resources in the CI/CD tool.

The only way to go around this currently is too extend webpack config and modify default by creating new instance of ForkTsCheckerWebpackPlugin, but that doesn't seem like an ideal solution.

**Comment by Cammisuli** [comment]
Hi @jbojcic1 what package are you using that you're running into issues with `ForkTsCheckerWebpackPlugin`?

**Comment by jbojcic1** [comment]
@Cammisuli I am using React but, if I am not missing something, the code that configures that is in the web package https://github.com/nrwl/nx/blob/0b520b9639829738226eb36875c6d96738f0e061/packages/web/src/utils/config.ts#L75

**Comment by jbojcic1** [comment]
If you think that's something that could/should be added, I'd be happy to help.

**Comment by Cammisuli** [comment]
@jbojcic1 you're correct, the react package uses the `@nrwl/web` package. An option could definitely be added to set the memory of the type checker (similar to what we have with `maxWorkers` option). 

You're more than welcome to help if you'd like. Just let me know if you have any questions!
