### ISSUE TITLE
Angular 17 with :application executor runs into blocking console issues

### ISSUE THREAD

**Issue by ErickRodrCodes** [nrwl/nx#22731]
### Current Behavior

Environment: Windows 10 Enterprise 22H2

In random cases, when serving Angular 17 with the application executioner, it tends to block the terminal with some incomplete characters:

![image](https://github.com/nrwl/nx/assets/1978642/1a54ab47-7e3a-40d8-ae65-83c3d08ec8ce)

while this happens the task runner is in a lethargic state:

![image](https://github.com/nrwl/nx/assets/1978642/979e01d7-876f-4f1d-9c94-8d0aca16bab4)

Only after pressing CTRL + C, the terminal unfreezes, and you can input a serving command as R, Q or H

Note that sometimes it works, and in this case, I had to kill it:

![image](https://github.com/nrwl/nx/assets/1978642/ddd5c774-d570-4065-92a2-a4327ad2683a)

and the worst-case scenario is I have to kill every single node process if CTRL+C doesn't work with
```
Get-Process -Name node | Stop-Process
```

I suspect the issue is located with chalk, other coloring library, or simply the spinner prevents to run something when rendering on the terminal. I even ensured it takes `FORCE_COLOR=0` to prevent any color rendering. Reason I'm suspecting of it is for the similar output I get on build on CI:

![image](https://github.com/nrwl/nx/assets/1978642/a63c3c98-5f54-4933-9de5-4278a37d6edf)

### Expected Behavior

It just should serve. It started to happen after migrating to Angular 17 and set up the executor as `@angular-devkit/build-angular:application`

### Steps to Reproduce

1. unfortunately it is totally random and I can reproduce it every single time. However, it is quite frequent if you have `@angular-devkit/build-angular:application` on the codebase. just run in powershell `nx serve your-angular-app` and sporadically will show up a blocking set of strings.

### Nx Report

```shell
Report complete - copy this into the issue template

Node : 18.18.2

OS : win32-x64

npm : 9.8.1

nx (global) : 18.1.2
nx : 18.1.2
@nx/js : 18.1.2
@nx/jest : 18.1.2
@nx/linter : 18.1.2
@nx/eslint 18.1.2
@nx/workspace 18.1.2
@nx/angular : 18.1.2
@nx/devkit : 18.1.2
@nx/esbuild : 18.1.2
@nx/eslint-plugin : 18.1.2
@nx/express 18.1.2
@nx/node : 18.1.2
@nrwl/tao : 18.1.2
@nx/web : 18.1.2
@nx/webpack : 18.1.2
typescript : 5.3.3

Community plugins:
@testing-library/angular : 13.0.1

angular-auth-oidc-client : 16.0.1
ng-mocks : 14.12.1
```

### Failure Logs

```shell
it block the terminal, so no logs are really visible
```

### Package Manager Version

npm 9.8.1

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

as a preventive measure I tried to run `cross-env FORCE_COLOR=0 CI=true` to ensure coloring won't happen, however something is triggering some strange character that blocks the terminal to continue.

**Comment by ErickRodrCodes** [comment]
It seems that setting on the executer options the option `verbose` to `false` fixes the issue. it won't show the building spinner, and it seems it might work. however you can't command vite to reload, open or quite the application.

**Comment by ErickRodrCodes** [comment]
Additional: the ANSI Escape sequence has something to do here:

https://en.wikipedia.org/wiki/Escape_sequence

The ^[[8; escape sequence is only supported by some terminals. If you are using a terminal that does not support it, the concealed text will be displayed normally. The ^[[8; escape sequence can be used to conceal any type of text, including text that is already colored. The ^[[8; escape sequence can be combined with other ANSI escape sequences to create more complex effects. For example, you could use the ^[[8; escape sequence to conceal text that is also blinking or underlined.

**Comment by pkelleter** [comment]
@ErickRodrCodes would you be so nice to elaborate on how/where exactly to put verbose to false in the config? :)

**Comment by ErickRodrCodes** [comment]
> same issue here. upgrading node from 16 to 20 improved the issue from happening almost-always to decently-often - but it still persists in general.
> 
> @ErickRodrCodes would you be so nice to elaborate on how/where exactly to put verbose to false in the config? :)

Sure thing.

In your project. json browse build -> options, then set an option called "verbose" to be false. that should be enough.

**Comment by MaxKless** [comment]
Hey thanks for the report! This is a known issue and tracked in https://github.com/nrwl/nx/issues/22358.
As a workaround, setting `NX_NATIVE_COMMAND_RUNNER=false` in your `.env` file should work.
I'll close this as a duplicate :)

**Comment by ErickRodrCodes** [comment]
for those using `cross-env` it work fine for me as well without .env:

```json
"start":"cross-env NX_NATIVE_COMMAND_RUNNER=FALSE nx serve <app>"
```
