### ISSUE TITLE
Unable to use absolute imports of folders inside any app with nx monorepo

### ISSUE THREAD

**Issue by rishavpandey43** [nrwl/nx#22730]
### Current Behavior

I have several folders like helper, component, api, and modules inside my app, and I want to use absolute import like `import { consoleLog } from 'helper';` instead of relative imports.

Now, this is not possible even though configured tsconfig.app.json inside the app.

This is the config I added - 

```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    ...
    "baseUrl": "./src",
    "paths": {
      "helpers/*": ["helpers/*"]
    }
  },
  ...
}
```

I used `vite-tsconfig-paths` inside `apps/main-app/vite.config.ts` like below and was able to use absolute paths inside the application - 

```
import { nxViteTsPaths } from '@nx/vite/plugins/nx-tsconfig-paths.plugin';
import viteTsconfigPaths from 'vite-tsconfig-paths';

...
plugins: [react(), nxViteTsPaths(), viteTsconfigPaths()],
...
```

But, with this configuration, I'm unable to use another library/package.

Like, when using `import { UiLib } from '@my-org/ui-lib';` inside app, I'm getting following error - 

`Cannot find module '@my-org/ui-lib' or its corresponding type declarations.`

### Expected Behavior

Absolute imports should work inside internal applications/packages too, and it should not affect the overall NX setup.

### GitHub Repo

https://github.com/rishavpandey43/nx-monorepo-test

### Steps to Reproduce

1. Start the application in any environment, and open the `apps/main-app/src/app/app.tsx` file.'
2. On the first line, you'll get this error prompted in the editor or in CLI too if you start the vite server 

### Nx Report

```shell
Node   : 20.10.0
OS     : darwin-arm64
npm    : 10.2.3

nx (global)        : 17.2.8
nx                 : 18.2.3
@nx/js             : 18.2.3
@nx/linter         : 18.2.3
@nx/eslint         : 18.2.3
@nx/workspace      : 18.2.3
@nx/devkit         : 18.2.3
@nx/eslint-plugin  : 18.2.3
@nx/react          : 18.2.3
@nx/rollup         : 18.2.3
@nrwl/tao          : 18.2.3
@nx/vite           : 18.2.3
@nx/web            : 18.2.3
typescript         : 5.4.4
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
@nx/rollup/plugin
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
tsconfig paths overwrite each other, they don't extend. Since thats how the lib imports work as setup by default, this isn't something we support.

**Comment by alex-gale** [comment]
Is there a way to overcome this at all? We like using absolute imports within individual projects (`import { Home } from 'components/Home'`) as opposed to messy relative imports (`import { Home } from '../../../../../../../../../../components/Home'`) but can't work out how to get this or something similar to work

**Comment by AgentEnder** [comment]
Extracting pieces out to libraries and importing from the library should give much nicer import paths, on top of the graph / caching benefits

**Comment by alex-gale** [comment]
Definitely, that's the end goal. Just trying to work out the best way to import a few existing projects without having to change too much

**Comment by AgentEnder** [comment]
You can set the apps tsconfig with paths, you'll just have to add an entry there for any libs you want to use too

**Comment by rishavpandey43** [comment]
Hi Everyone, 

I got the solution for this, and I believe it needs to be done in the above case.

When I got the issue in one of my internal apps of mono-repo, I updated its `apps/pay-platform/tsconfig.app.json` to this - 

```
"baseUrl": ".",
"paths": {
  "@skuad/fe-core": ["../../packages/fe-core/src/index.ts"],
  "@skuad/fe-utils": ["../../packages/fe-utils/src/index.ts"],
  "@skuad/sk-ui": ["../../packages/sk-ui/src/index.ts"],
  "@skuad/ui-components": ["../../packages/ui-components/src/index.ts"],
  "@pay/*": ["./src/*"]
}
```

Here, we're first re-defining all the other packages, and libraries again relative to the internal app and then also defining absolute imports within the apps.

With this above setup, I'm able to use both app-level absolute imports and other packages within the mono-repo
