### ISSUE TITLE
Path intelliSense stop working suddenly for no reason

### ISSUE THREAD

**Issue by anteqkois** [nrwl/nx#22733]
### Current Behavior

My intellisense starts importing from root level like:
'libs/shared/src/lib...',

### Expected Behavior

Import using TS path like bfore:
'@linkerry/shared',

### Steps to Reproduce

1. No steps

### Nx Report

```shell
Node   : 20.11.1
   OS     : darwin-arm64
   pnpm   : 8.10.5

   nx (global)        : 16.5.0
   nx                 : 16.5.0
   @nx/js             : 16.5.4
   @nx/jest           : 16.5.0
   @nx/linter         : 16.5.0
   @nx/workspace      : 16.5.0
   @nx/cypress        : 16.5.4
   @nx/devkit         : 17.2.8
   @nx/esbuild        : 16.5.4
   @nx/eslint-plugin  : 16.5.0
   @nx/nest           : 16.5.0
   @nx/next           : 17.2.7
   @nx/node           : 16.5.0
   @nx/react          : 16.5.4
   @nrwl/tao          : 16.5.0
   @nx/webpack        : 16.5.0
   typescript         : 5.1.6
   ---------------------------------------
   Local workspace plugins:
   	 @linkerry/...
   	 @linkerry/...
   	 @linkerry/...
   	 @linkerry/...
   	 ...
   	 @linkerry/...
   ---------------------------------------
```

### Package Manager Version

pnpm 8.10.5

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I tried to change typescript.preferences.importModuleSpecifier and also for JS but it don't work, I checked all options. I have properly configured ts config in root dir with path. This imports working for almost year

**Comment by rosslavery** [comment]
We also started encountering this recently.

Our repo is configured with `"typescript.preferences.importModuleSpecifier": "project-relative"`.

But lately -- hard to pinpoint when -- our imports are now using root-absolute paths, even with the above configuration.

This is not only for org-scoped libraries in the OP, but also for apps importing files from within itself, it will still make the path `apps/xxx/src/yyy.ts`, despite trying to import from a file inside `apps/xxx`
