### ISSUE TITLE
Missing Platform Dependency

### ISSUE THREAD

**Issue by Anik-the-dev** [nrwl/nx#22740]
### Current Behavior

I am using WSL(Ubuntu Linux-x64) where i installed node, npm and nx.
when I write: **nx setup** for a existing cloned project, it shows error.
"**The Nx CLI could not find or load the native binary for your supported platform (linux-x64).
This likely means that optional dependencies were not installed correctly, or your system is missing some system dependencies.**"

I tried every possible way, still facing this error.

### Expected Behavior

Expected: nx will setup correctly.

### Steps to Reproduce

1. nx setup in WSL ( In short)
**In Details:**
1.I update the  packages (sudo apt update)
2.Add fresh nodejs(curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -)
3.Install nodejs in WSL ( sudo apt-get install -y nodejs)
4.Install nx in locally(npm install nx)
5. when run: nx setup
Output: Missing dependency error

### Nx Report

```shell
Missing Platform Dependency

The Nx CLI could not find or load the native binary for your supported platform (linux-x64).
This likely means that optional dependencies were not installed correctly, or your system is missing some system dependencies.
For more information please see https://nx.dev/recipes/troubleshooting/troubleshoot-nx-install-issues
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Did you follow the troubleshooting steps linked in https://nx.dev/recipes/troubleshooting/troubleshoot-nx-install-issues?

Npm has a bug that sometimes keeps platform specific deps from being in the package lock, in which cases deleting and reinstalling packages is sometimes necessary.
