### ISSUE TITLE
nx release publish - custom registry - sonartype nexus - npm view 404 not handled 

### ISSUE THREAD

**Issue by RobbyRabbitman** [nrwl/nx#22766]
### Current Behavior

`nx release publish` fails due to `npm view` for the first release. 

The executor https://github.com/nrwl/nx/blob/master/packages/js/src/executors/release-publish/release-publish.impl.ts ignores `404` in combination with `no such package available` or `not found`, but it does not ignore the error for a custom registry of type https://www.sonatype.com/products/sonatype-nexus-repository, which we are using at our company, because the error log does not contain `no such package available` or `not found`. 

`npm view does-not-exist versions dist-tags --json` for `https://www.npmjs.com/` has `not found` in the error, while `npm view does-not-exist versions dist-tags --json` for _sonartype nexus_ does not contain `no such package available` or `not found`

While reading through the source code of the executor, you can set the flag `--first-release` in order to skip the `npm view` part, which is a workaround for now.

### Expected Behavior

Don't fail on the first release for custom registries of type https://www.sonatype.com/products/sonatype-nexus-repository

### Steps to Reproduce

1. `.npmrc`  in the root of the repository with custom sonartype nexus registry 
2. Not released yet
3. nx release publish

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.11.1
OS     : linux-x64
pnpm   : 8.15.4

nx                 : 18.2.3
@nx/js             : 18.2.3
@nx/linter         : 18.2.3
@nx/eslint         : 18.2.3
@nx/workspace      : 18.2.3
@nx/angular        : 18.2.3
@nx/cypress        : 18.2.3
@nx/devkit         : 18.2.3
@nrwl/devkit       : 18.0.4
@nx/eslint-plugin  : 18.2.3
@nx/storybook      : 18.2.3
@nrwl/tao          : 18.2.3
@nx/vite           : 18.2.3
@nx/web            : 18.2.3
@nx/webpack        : 18.2.3
typescript         : 5.4.4
---------------------------------------
Registered Plugins:
@nx/storybook/plugin
@nx/vite/plugin
@nx/eslint/plugin
---------------------------------------
Community plugins:
@compodoc/compodoc : 1.1.23
@storybook/angular : 7.6.17
ng-mocks           : 14.12.1
nx-stylelint       : 17.1.4
---------------------------------------
The following packages should match the installed version of nx
  - @nrwl/devkit@18.0.4

To fix this, run `nx migrate nx@18.2.3`

Finishing: Report
```

### Failure Logs

```shell
// nx release publish

Something unexpected went wrong when checking for existing dist-tags.
 Error: Command failed: npm view my-package versions dist-tags --json --"<company-registry>"
npm ERR! code E404
npm ERR! 404 my-package - GET <company-registry>/my-package
npm ERR! 404 
npm ERR! 404  'my-package' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

// npm view sonartype nexus

npm view my-package versions dist-tags --json --"<company-registry>"
npm ERR! code E404
npm ERR! 404 my-package - <company-registry>/my-package
npm ERR! 404 
npm ERR! 404  'my-package' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
{
  "error": {
    "code": "E404",
    "summary": "my-package - GET <company-registry>/my-package",
    "detail": "\n 'my-package' is not in this registry.\n\nNote that you can also install from a\ntarball, folder, http url, or git url."
  }
}

// npm view https://registry.npmjs.org/does-not-exist

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/does-not-exist - Not found
npm ERR! 404 
npm ERR! 404  'does-not-exist@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
{
  "error": {
    "code": "E404",
    "summary": "Not Found - GET https://registry.npmjs.org/does-not-exist - Not found",
    "detail": "\n 'does-not-exist@*' is not in this registry.\n\nNote that you can also install from a\ntarball, folder, http url, or git url."
  }
}
```

### Package Manager Version

8.15.4

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by thdk** [comment]
This should have been fixed with following PR: https://github.com/nrwl/nx/pull/20995

https://github.com/nrwl/nx/pull/20995/files#diff-1c2ebfe42e321fc6f4a8c99988807e45610b304f4685123906741b0260fc5472R183-R192

However, the same change still needs to be applied here:

https://github.com/nrwl/nx/pull/20995/files#diff-1c2ebfe42e321fc6f4a8c99988807e45610b304f4685123906741b0260fc5472R143-R151
