### ISSUE TITLE
The projects flag on run-many command do not accept space as mentioned on the docs 

### ISSUE THREAD

**Issue by alexanmtz** [nrwl/nx#22765]
### Current Behavior

When you run the command `nx run-many --projects='project1 project2'`, it targets 0 projects, and when it runs  `nx run-many --projects='project1,project2'` it will affect the two projects.

### Expected Behavior

As specified on the docs https://nx.dev/nx-api/nx/documents/run-many#projects

The projects flag for run-many should accept space separate projects as mentioned here: 
**Projects to run. (comma/space delimited project names and/or patterns)**

So when you run  `nx run-many --projects='project1 project2'` it needs to run 'project1' and 'project2'

### Steps to Reproduce

1. Make sure you have multiple projects
2. Run `nx run-many --projects='project1 project2'` 
3. The scope of the command will affect 0 projects

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.17.1
   OS     : win32-x64
   yarn   : 1.22.19
   
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/node           : 17.2.8
   @nx/plugin         : 17.2.8
   @nx/react          : 17.2.8
   @nx/rollup         : 17.2.8
   @nx/storybook      : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @theunderscorer/nx-semantic-release : 2.6.2
   ---------------------------------------
   Local workspace plugins:
         @nx/test
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Hey @alexanmtz. For the space delimiter to work they can't be wrapped in quotes. Try `nx show projects -p foo bar` to see both.
