### ISSUE TITLE
Nx creating React-Next.JS standalone app doesn't run

### ISSUE THREAD

**Issue by austinlukaschewski** [nrwl/nx#22774]
### Current Behavior

Generated a new project using `npx create-nx-workspace@latest --pm pnpm` command. After picking React / NextJS / standalone ... etc. Once project is built, running `pnpm start` or `nx serve` results in errors and the app not starting.

This is the error after running nx serve <app name> --verbose:
`Failed to process project graph.
  The "@nx/jest/plugin" plugin threw an error while creating nodes from apps/back-nine-bullies-web/jest.config.ts:
    ● Validation Error:
    
      Module @nx/react/plugins/jest in the transform option was not found.
             <rootDir> is: <root>/<workspace name>/apps/<NextJS app name>
    
      Configuration Documentation:
      https://jestjs.io/docs/configuration`

### Expected Behavior

Ability to run the app after a clean project build using `pnpm start` or `nx serve`

### Steps to Reproduce

1. `npx create-nx-workspace@latest --pm pnpm`
2. Select React
3. Select NextJS
4. Select standalone
5. Finish project set up & navigate to that project
6. Run `pnpm start` or `nx serve <app name>`

### Nx Report

```shell
NX   Failed to process project graph.

Pass --verbose to see the stacktraces.

(Output from running `nx report --verbose`)
```

### Package Manager Version

8.14.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by austinlukaschewski** [comment]
This was a mistake on my end, not a bug. Sorry.

**Comment by hafizhuseynov** [comment]
@austinlukaschewski  I'm getting same error, how did you solved it?

**Comment by austinlukaschewski** [comment]
in the jest config you have to comment out the transform property, not sure what it has changed too but I didnt need it so I was able to comment it out. I also realized that `nx serve` wasn't working and seemed to have changed to `nx start`.

@hafizhuseynov I hope this helps.
