### ISSUE TITLE
workspace dependencies are installed in top-level

### ISSUE THREAD

**Issue by its-dibo** [nrwl/nx#22789]
### Current Behavior

when creating a new app with `@nx/angular:application my-app`, the dependencies are added in the top-level dir.
it should be added to each workspace separately

in addition, no package.json is created inside the newly created workspace at all

### Expected Behavior

the file apps/my-app/package.json should be created, and the dependencies are added to it instead of the top-level one

### Steps to Reproduce

1. create a monorepo
2. add "apps/**/*" to the rook package's `workspaces[]`
3. run `@nx/angular:application my-app --directory apps/my-app`

### Nx Report

```shell
Node   : 20.10.0
OS     : linux-x64
yarn   : 1.22.22

nx (global)    : 18.2.4
nx             : 18.2.4
@nx/js         : 18.2.4
@nx/jest       : 18.2.3
@nx/linter     : 18.2.3
@nx/eslint     : 18.2.3
@nx/workspace  : 18.2.4
@nx/angular    : 18.2.4
@nx/cypress    : 18.2.4
@nx/devkit     : 18.2.4
@nrwl/tao      : 18.2.4
@nx/web        : 18.2.4
@nx/webpack    : 18.2.4
typescript     : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/cypress/plugin
---------------------------------------
The following packages should match the installed version of nx
  - @nx/jest@18.2.3
  - @nrwl/jest@18.2.3
  - @nx/linter@18.2.3
  - @nx/eslint@18.2.3
```

### Package Manager Version

yarn

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Hey 👋.

This is expected behavior, Nx generators currently setup projects according to single version principle and without npm workspaces in mind. Its on our internal roadmap to make them play nicer when workspaces have already been configured though.

For more on single version principle, see: https://nx.dev/concepts/more-concepts/dependency-management#single-version-policy
