### ISSUE TITLE
`nx release` generates tag with an non-interpolated `{version}` when there are no changes

### ISSUE THREAD

**Issue by yjaaidi** [nrwl/nx#22798]
### Current Behavior

Given a group with the following configuration:

```json
"my-group": {
  "projects": [
    "a",
    "b"
  ],
  "projectsRelationship": "fixed",
  "releaseTagPattern": "my-group-{version}"
}
```

and given there are no changes on `a` & `b`.

Running `nx release` will tag the commit with `my-group-{version}` without interpolating the `{version}`.

_Also, looking at the source code below, it seems that a similar problem could happen and pollute the commit message with fixed groups that don't have any changes_
https://github.com/nrwl/nx/blob/a627ce84b1420b20e6d48fd7f98a5e08b1a13a86/packages/nx/src/command-line/release/utils/shared.ts#L201-L203

### Expected Behavior

It should not tag.

There should be a precondition before this: https://github.com/nrwl/nx/blob/a627ce84b1420b20e6d48fd7f98a5e08b1a13a86/packages/nx/src/command-line/release/utils/shared.ts#L249-L253

### Steps to Reproduce

Cf. example above.

### Nx Report

```shell
Node   : 21.7.2
OS     : darwin-arm64
yarn   : 3.5.1

nx                 : 18.2.4
@nx/js             : 18.2.4
@nx/jest           : 18.2.4
@nx/linter         : 18.2.4
@nx/eslint         : 18.2.4
@nx/workspace      : 18.2.4
@nx/angular        : 18.2.4
@nx/cypress        : 18.2.4
@nx/devkit         : 18.2.4
@nrwl/devkit       : 18.1.0-beta.2
@nx/eslint-plugin  : 18.2.4
@nx/node           : 18.2.4
@nx/plugin         : 18.2.4
@nx/rollup         : 18.2.4
@nrwl/tao          : 18.1.0-beta.2
@nx/vite           : 18.2.4
@nx/web            : 18.2.4
@nx/webpack        : 18.2.4
typescript         : 5.4.4
---------------------------------------
Registered Plugins:
@nx/vite/plugin
---------------------------------------
Community plugins:
@analogjs/vite-plugin-angular : 1.1.2
@monodon/rust                 : 1.4.0
---------------------------------------
The following packages should match the installed version of nx
  - @nrwl/devkit@18.1.0-beta.2
  - @nrwl/tao@18.1.0-beta.2

To fix this, run `nx migrate nx@18.2.4`
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by stefanlivens** [comment]
Ah, this explains the 'v{version}' tags we have. We tought it was a user-/environment- issue! Thanks for clearing that up!
