### ISSUE TITLE
Add a command to remove an app from the workspace.

### ISSUE THREAD

**Issue by asherccohen** [nrwl/nx#2279]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [ x] I checked the documentation (nx.dev) and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Be able to run a command like nx remove @nrwl/react:application myapp to completely remove an application/library from the workspace.

## Current Behavior

No documented way to remove an app/lib from the wrokspace.

### Context

Please provide any relevant information about your setup:

- version of Nx used: 8.9.0

**Comment by asherccohen** [comment]
The move command has been introduced to help refactoring a workspace.

nx g @nrwl/workspace:move --projectName my-feature-lib --destination shared/my-feature-lib

Does this help in regards to removing a project from it?

**Comment by FrozenPandaz** [comment]
The remove schematic has now been added! :tada: Please give it a try!

```
ng g @nrwl/workspace:remove project-name
```

**Comment by bostondevin** [comment]
How do you specify the workspace name and the application or library name? What does project-name mean? I tried this and it keeps giving me this error whether i'm in the workspace directory or not:

"The generate command requires to be run in an Angular project, but a project definition could not be found."

**Comment by bostondevin** [comment]
NVM - this is how you do it: **nx g @nrwl/workspace:remove my-feature-lib**

**Comment by sky107** [comment]
Dont forget to remove its dependent applications first
