### ISSUE TITLE
Nx Graph - Generate the png image from command line

### ISSUE THREAD

**Issue by mauriziovitale** [nrwl/nx#22799]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?
I would like to know if there is any way to generate the Nx graph image from command line i.e. 
nx graph --image

Enter the URL or documentation section here.
https://nx.dev/features/explore-graph
### Additional context or description

Provide any additional details here as needed.

**Comment by AgentEnder** [comment]
On the CLI you can use `--file` to output html or json, there is not currently a way to output a static image though.

**Comment by zackarydev** [comment]
Could we add this as a feature eventually though? It would be extremely helpful to have an image of affected libraries / apps and to upload this in PRs.

**Comment by mauriziovitale** [comment]
> On the CLI you can use `--file` to output html or json, there is not currently a way to output a static image though.

Thanks this was my plan B :)
