### ISSUE TITLE
Path somehow broke in Webstorm. Probably my fault.

### ISSUE THREAD

**Issue by mcblum** [nrwl/nx#228]
So I came in to work today and the paths defined are now not being recognized. We use `@frontend` as an alias for `libs` and everything is lit up with errors. The app is working fine, it's just Webstorm that is no longer respecting it.

Any ideas what that might be? This is certainly not a bug, just a specific issue that others may come across. I've verified that my `tsconfig.json` is named correctly and the paths are in there. The only thing that's changed about this project is that I renamed the parent folder a few days ago, but I updated all aliases and such.

Thanks in advance!

**Comment by vsavkin** [comment]
>> it's just Webstorm that is no longer respecting it.

What do you mean by this?

**Comment by mcblum** [comment]
@vsavkin sorry man - forgot to close this. I'm not sure what exactly happened but the old uninstall and reinstall everything worked.
