### ISSUE TITLE
Add external $ref resolution to allow modular schemas for generators/executors

### ISSUE THREAD

**Issue by charlesanim** [nrwl/nx#22808]
Both #9206  (this) and #9208 remain good ideas. Is there any interest in re-opening or other consideration of this idea?

_Originally posted by @danielsharvey in https://github.com/nrwl/nx/issues/9206#issuecomment-1399518688_

Was there a resolution on both issues mentioned here? I'm facing the same issue and hoping to leverage module schemas for my generators.

**Comment by AgentEnder** [comment]
We are currently tracking support for this / similar features here: https://github.com/nrwl/nx/issues/10890

**Comment by charlesanim** [comment]
Ah gotcha. Any idea the ETA for such a feature to land?
