### ISSUE TITLE
Problem with targetDefaults / configurations and @nx/jest/plugin in nx.json

### ISSUE THREAD

**Issue by killmenot** [nrwl/nx#22817]
### Current Behavior

Hi,

Got a problem when added configurations for targetDefaults for test task when @nx/jest/plugin is used.

### Case 1
```
Branch: main
```

Running default configuration (OK)
```
> nx run nx-test:test

> jest --passWithNoTests true

No tests found, exiting with code 0

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Successfully ran target test for project nx-test (2s)
 ```

Running ci configuration (Failed)
```
> nx run nx-test:test:ci

> jest --passWithNoTests true --ci true --codeCoverage true

● Unrecognized CLI Parameter:

  Unrecognized option "codeCoverage".

  CLI Options Documentation:
  https://jestjs.io/docs/cli

Warning: command "jest --passWithNoTests true --ci true --codeCoverage true" exited with non-zero status code
```

### Case 2
```
Branch: test
```

if I remove `@nx/jest/plugin` plugin from nx.json, configure "targetDefaults" and update "project.json"

Running default configuration (OK)
```
➜  nx-test git:(temporary) ✗ nx run nx-test:test

> nx run nx-test:test

No tests found, exiting with code 0

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Successfully ran target test for project nx-test (2s)
 ```

Running ci configuration (OK)
```
➜  nx-test git:(temporary) ✗ nx run nx-test:test:ci

> nx run nx-test:test:ci

No tests found, exiting with code 0

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Successfully ran target test for project nx-test (1s)
 ```

### Expected Behavior

`nx run nx-test:test:ci` in Case1 should work

### GitHub Repo

https://github.com/killmenot/nx-test

### Steps to Reproduce

```
nx run nx-test:test
nx run nx-test:test:ci
```

### Nx Report

```shell
Node   : 18.19.0
OS     : darwin-x64
npm    : 10.2.3

nx (global)        : 18.2.4
nx                 : 18.2.4
@nx/js             : 18.2.4
@nx/jest           : 18.2.4
@nx/linter         : 18.2.4
@nx/eslint         : 18.2.4
@nx/workspace      : 18.2.4
@nx/devkit         : 18.2.4
@nx/eslint-plugin  : 18.2.4
@nx/nest           : 18.2.4
@nx/node           : 18.2.4
@nrwl/tao          : 18.2.4
@nx/web            : 18.2.4
@nx/webpack        : 18.2.4
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by killmenot** [comment]
NOTE:

For Case1 the following will work but in this case it means targetDefaults and @nx/jest/plugin configures jest cli options directly
```
"configurations": {
   "ci": {
      "ci": true,
      "coverage": true
   }
}
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

The issue is that `codeCoverage` is not an option known to the Jest CLI. The correct option is `coverage`.

In "Case 1", you're using the inferred task by the `@nx/jest/plugin`. Inferred tasks run the underlying tool directly, in this case, the Jest CLI. You can see the valid options for the Jest CLI: here https://jestjs.io/docs/cli.

In the "Case 2", you're using the `@nx/jest:jest` executor. The executor does accept an option called `codeCoverage` and that's why it works with it. You can see the accepted executor options here: https://nx.dev/nx-api/jest/executors/jest#options.

Please update the target defaults for the `test` target to provide the `coverage` option when using inferred tasks instead of the `codeCoverage` option.
