### ISSUE TITLE
@nx/js lib generator tests do not work when importing another lib

### ISSUE THREAD

**Issue by skwny** [nrwl/nx#22833]
### Current Behavior

When attempting to run tests on a library, the tests will fail due to the use of `import`. The error I receive is:
```
    SyntaxError: Cannot use import statement outside a module

    > 1 | import { InjectionToken } from '@angular/core'
        | ^

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (../client-types/src/index.ts:1:1)
      at Object.<anonymous> (src/lib/test.ts:1:1)
```

I've tried various configuration settings but have been unsuccessful, and beginning to wonder if I am overthinking it or configured the generator wrong to begin with. Please advise.

### Expected Behavior

Generated Typescript libraries successfully work with imports.

### Steps to Reproduce

1. Generate a new Typescript library via @nx/js and select `jest` as the `unitTestRunner`.
2. Write some code that uses an import statement.
3. Create a test for that code.
4. Run the test and observe the error `SyntaxError: Cannot use import statement outside a module`

### Nx Report

```shell
Node   : 20.12.2
OS     : darwin-arm64
npm    : 10.5.0

nx                 : 18.2.4
@nx/js             : 18.2.4
@nx/jest           : 18.2.4
@nx/linter         : 18.2.4
@nx/eslint         : 18.2.4
@nx/workspace      : 18.2.4
@nx/angular        : 18.2.4
@nx/cypress        : 18.2.4
@nx/devkit         : 18.2.4
@nx/esbuild        : 18.2.4
@nx/eslint-plugin  : 18.2.4
@nx/node           : 18.2.4
@nrwl/tao          : 18.2.4
@nx/web            : 18.2.4
@nx/webpack        : 18.2.4
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
---------------------------------------
Community plugins:
ng-zorro-antd : 17.3.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by MaxKless** [comment]
Hey! Thanks for the report. I wonder what's going on here... Can you specify why you're importing from angular in an `@nx/js` lib instead of `@nx/angular`? 

I tried reproducing this but for me a normal js lib with jest can run tests as expected
<img width="1308" alt="image" src="https://github.com/user-attachments/assets/a3f96b42-46cc-4449-91d2-1488289a550d">

Please provide a minimal reproduction so I can have a look into what's going wrong for you.
