### ISSUE TITLE
Project Crystal flaky CI behavior (regression)

### ISSUE THREAD

**Issue by Bielik20** [nrwl/nx#22876]
### Current Behavior

After updating from "18.0.6" to "18.3.1" targets inferred using plugin are inconsistent. When running `npx nx show project web-e2e --web` locally I always get correct targets, meaning:
* `e2e-ci`
* `e2e-ci--xxx` etc.

Where `e2e-ci` depends on `e2e-ci--xxx`.

When running on GitHub Actions with DTE I _sometimes_ get correct behavior and _sometimes_ only the `e2e-ci` is run.

The inconsistencies have nothing to do with actual code. It differs "from rerun to rerun".

### Expected Behavior

Targets inferred using plugin should always stay consistent.

### Steps to Reproduce

1. Create repo with playwright
2. Setup CI/CD on GitHub Actions with DTE
3. Run `affected -t e2e-ci` on GH Actions

_Some_ runs will not include `e2e-ci-xxx`

### Nx Report

```shell
Node   : 20.11.1
OS     : darwin-arm64
npm    : 10.2.4

nx                 : 18.3.1
@nx/js             : 18.3.1
@nx/jest           : 18.3.1
@nx/linter         : 18.3.1
@nx/eslint         : 18.3.1
@nx/workspace      : 18.3.1
@nx/devkit         : 18.3.1
@nx/eslint-plugin  : 18.3.1
@nx/next           : 18.3.1
@nx/node           : 18.3.1
@nx/playwright     : 18.3.1
@nx/plugin         : 18.3.1
@nx/react          : 18.3.1
@nrwl/tao          : 18.3.1
@nx/web            : 18.3.1
@nx/webpack        : 18.3.1
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@xyz/tools/src/plugins/playwright
---------------------------------------
Community plugins:
@ns3/nx-core       : 5.2.0
@ns3/nx-npm        : 5.2.0
@ns3/nx-serverless : 5.2.0
---------------------------------------
Local workspace plugins:
	 @xyz/workspace-plugin
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

We are using our own playwright plugin to infer tasks, but it works pretty much the same as a regular one. Just adjusted for our workflow.

**Comment by FrozenPandaz** [comment]
Hm, you mentioned you are using your own playwright plugin to infer tasks. Could you see if the same issue occurs when using the `@nx/playwright/plugin`? What exactly are you seeing for the configuration of `e2e-ci` in the cases where it is not picking up other tasks?

**Comment by Bielik20** [comment]
It is not that simple to test it with `@nx/playwright/plugin`. In our `playwright.config.ts` we are referencing some Nx environment variables that are unavailable when `@nx/playwright/plugin` runs, and since it is using `playwright.config.ts` to get data for configuration it crashes.

As for the second part, I cannot really see a configuration while in CI run (or maybe I can?). All I see is that in the "tab" with `npx nx affected -t e2e-ci` I only see parent task `e2e-ci` and none of the sharded tasks.

I have a link from the run:
```
---------------------------------------------------
| Current URL: https://cloud.nx.app/runs/1sNSW9Klnc
| OrganizationId: 620505a08ba9c40005211866
| Plan: PRO
| WorkspaceId: 62050738a0e506672a3452f0
---------------------------------------------------
```

There is a target `web-e2e:e2e-ci`. It should have around 10 tests it depends on `web-e2e:e2e-ci--foo-bar` etc. But those are not present. I want to be perfectly clear here, when running show project locally etc. it works fine. Even on CI it works most of the time. This is the particular run when I first seen them missing.

**Comment by leosvelperez** [comment]
hey @Bielik20!

You could run `nx show project web-e2e` on CI (in a step prior to running your e2e tasks) to see the final merged project configuration. You can also add extra logging to your plugin implementation to see if your plugin is always returning all the expected targets, but these aren't shown on Nx Cloud.

That said, we need to somehow discard whether the issue might be caused by the custom plugin implementation or if it's an issue from Nx. I'm unsure if you can, but if possible, it would be good to check the custom plugin implementation. I understand that locally always works as expected, but again, hard to know from our side if something in the plugin could be causing it. We haven't seen such an issue with the `@nx/playwright/plugin` (we use it internally in a few projects).

**Comment by Bielik20** [comment]
Hmm, yeah I understand. Sorry I am not responding more often there is a lot of work.
I can confirm that issue still happens sometimes.

As for implementations I think I could share it. It is not particularly complicated nor long. It is based on your implementation and looks like that:

```ts
import {
  CreateDependencies,
  CreateNodes,
  CreateNodesContext,
  detectPackageManager,
  joinPathFragments,
  ProjectConfiguration,
  readJsonFile,
  TargetConfiguration,
  writeJsonFile,
} from '@nrwl/devkit';
import { calculateHashForCreateNodes } from '@nx/devkit/src/utils/calculate-hash-for-create-nodes';
import { existsSync } from 'fs';
import { globSync } from 'glob';
import { dirname } from 'node:path';
import { getLockFileName } from 'nx/src/plugins/js/lock-file/lock-file';
import { projectGraphCacheDirectory } from 'nx/src/utils/cache-directory';
import { join } from 'path';

type PlaywrightTargets = Pick<ProjectConfiguration, 'targets' | 'metadata'>;

const cachePath = join(projectGraphCacheDirectory, 'playwright.hash');
const targetsCache = existsSync(cachePath) ? readTargetsCache() : {};
const calculatedTargets: Record<string, PlaywrightTargets> = {};

function readTargetsCache(): Record<string, PlaywrightTargets> {
  return readJsonFile(cachePath);
}

function writeTargetsToCache(targets: Record<string, PlaywrightTargets>) {
  writeJsonFile(cachePath, targets);
}

export const createDependencies: CreateDependencies = () => {
  writeTargetsToCache(calculatedTargets);
  return [];
};

export const createNodes: CreateNodes = [
  '**/?(*-)web-e2e/project.json',
  (projectConfigurationFile: string, opts, context: CreateNodesContext) => {
    const projectRoot = dirname(projectConfigurationFile);
    const e2eCiTargetDefaults = getE2eCiTargetDefaults(context);
    const e2eTargetDefaults = getE2eTargetDefaults(context);
    if (!e2eCiTargetDefaults || !e2eTargetDefaults) {
      return {};
    }

    const hash = calculateHashForCreateNodes(projectRoot, {}, context, [
      getLockFileName(detectPackageManager(context.workspaceRoot)),
    ]);
    const { targets, metadata } =
      targetsCache[hash] ?? buildPlaywrightTargets(projectRoot, e2eCiTargetDefaults, e2eTargetDefaults);

    calculatedTargets[hash] = { targets, metadata };

    return {
      projects: {
        [projectRoot]: {
          root: projectRoot,
          targets,
          metadata,
        },
      },
    };
  },
];

function buildPlaywrightTargets(
  projectRoot: string,
  e2eCiTargetDefaults: TargetConfiguration<any>,
  e2eTargetDefaults: TargetConfiguration<any>,
): PlaywrightTargets {
  const tests = findTests(projectRoot);
  const e2eCiTargets = tests.reduce(
    (acc, test) => {
      const configuration: TargetConfiguration = {
        ...e2eCiTargetDefaults,
        dependsOn: ['^deploy'],
        command: `playwright install chromium && playwright test ${test.file}`,
        options: {
          cwd: projectRoot,
        },
        metadata: {
          technologies: ['playwright'],
          description: `Runs Playwright Tests in ${test.file} in CI`,
        },
      };

      return {
        ...acc,
        [test.name]: configuration,
      };
    },
    {} as Record<string, TargetConfiguration>,
  );
  const e2eCiTargetsNames = Object.keys(e2eCiTargets);
  const e2eCiMainTarget: TargetConfiguration = {
    ...e2eCiTargetDefaults,
    executor: 'nx:noop',
    metadata: {
      technologies: ['playwright'],
      description: 'Runs Playwright Tests in CI',
    },
    dependsOn: e2eCiTargetsNames,
  };
  const e2eMainTarget: TargetConfiguration = {
    ...e2eTargetDefaults,
    command: `playwright install chromium && playwright test`,
    options: {
      cwd: projectRoot,
    },
    metadata: {
      technologies: ['playwright'],
      description: 'Runs Playwright Tests',
    },
  };

  const targets: ProjectConfiguration['targets'] = {
    e2e: e2eMainTarget,
    ['e2e-ci']: e2eCiMainTarget,
    ...e2eCiTargets,
  };
  const metadata: ProjectConfiguration['metadata'] = {
    targetGroups: { 'E2E (CI)': ['e2e-ci', ...e2eCiTargetsNames] },
  };

  return {
    targets,
    metadata,
  };
}

function findTests(projectRoot: string) {
  const pattern = '**/*.spec.ts';
  const files = globSync(pattern, {
    cwd: joinPathFragments(projectRoot, 'tests'),
    dot: true,
    follow: true,
    nodir: true,
  });
  return files.map((file) => ({
    file,
    name: 'e2e-ci--' + file.replaceAll('/', '-').replaceAll('.spec.ts', ''),
  }));
}

function getE2eCiTargetDefaults(context: CreateNodesContext): TargetConfiguration | undefined {
  return context.nxJsonConfiguration.targetDefaults['e2e-ci'];
}

function getE2eTargetDefaults(context: CreateNodesContext): TargetConfiguration | undefined {
  return context.nxJsonConfiguration.targetDefaults['e2e'];
}
```

Where would you recommend adding print? I remember from docs that logging insides of a plugin are not very helpful. I recall I needed to run it without daemon to see the logs properly. I am not sure how useful it will be in CI/CD environment.

**Comment by leosvelperez** [comment]
Yeah, to see the logs from plugins, you could either run in CI with `NX_DAEMON=false` or you could expose the `.nx/cache/d/daemon.log` file as an artifact in your CI/CD provider so you can download and inspect it later.

Based on your plugin implementation, the only things that I can imagine could cause such behavior (if not caused by Nx or Nx Cloud) are:

- the globbing for test files doesn't return anything
- a poisoned cache that's hit in such cases

Therefore, I'd suggest to log a few things:

- are the targets retrieved from cache?
  - is `targetsCache[hash]` defined?
- is `files` inside `findTests` empty?
- log `targets` before returning in the `createNodes` tuple function

Make sure to add any relevant context to those logs (e.g. `configFilePath`) so it's easier to correlate them. Plugins and matching files are processed in parallel.

Please share with us the relevant logs when you hit the issue.

**Comment by Bielik20** [comment]
still working on it (fighting the stale bot)
