### ISSUE TITLE
Project graph contains no external dependencies when using pnpm lockfile v9

### ISSUE THREAD

**Issue by ms-tng** [nrwl/nx#22874]
### Current Behavior

When using pnpm v9 with the new `lockfileVersion: '9.0'`, the logic for creating the Nx project graph does not find any external dependencies.

### Expected Behavior

The Nx project graph should include external dependencies even when using pnpm lockfile v9.

### Steps to Reproduce

To reproduce, run the following code:
```js
import { createProjectGraphAsync } from '@nx/devkit';
import { writeFile } from 'fs/promises';

await writeFile('project-graph.json', JSON.stringify(await createProjectGraphAsync(), null, 2));
```

Open `project-graph.json` and observe that `"dependencies"` lists no external dependencies, i.e. where `"target": "npm:..."`.

### Nx Report

```shell
Node   : 20.5.0
OS     : win32-x64
pnpm   : 9.0.2

nx (global)        : 18.3.1
nx                 : 18.3.1
@nx/js             : 18.3.1
@nx/jest           : 18.3.1
@nx/eslint         : 18.3.1
@nx/workspace      : 18.3.1
@nx/devkit         : 18.3.1
@nx/eslint-plugin  : 18.3.1
@nx/express        : 18.3.1
@nx/node           : 18.3.1
@nx/playwright     : 18.3.1
@nx/plugin         : 18.3.1
@nx/react          : 18.3.1
@nx/rollup         : 18.3.1
@nx/storybook      : 18.3.1
@nrwl/tao          : 18.3.1
@nx/vite           : 18.3.1
@nx/web            : 18.3.1
typescript         : 5.4.5
```

### Package Manager Version

```shell
pnpm   : 9.0.2
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by marviobezerra** [comment]
+1

**Comment by gperdomor** [comment]
+1

**Comment by AgentEnder** [comment]
Nx doesn't support pnpm 9 yet. Support for that is currently being tracked in https://github.com/nrwl/nx/issues/22850. I'm going to close this as a duplicate.
