### ISSUE TITLE
[Nx Plugin] Vitest support for nx plugins generators

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#22882]
### Current Behavior

Hi folks...

It's well known that, at least for now, nx plugins needs to be CommonJS only, but those plugins can rely on other publishable packages from the same workspace.

Those publishable libraries, needs to be CommonJS too, but for library generators we have the option to use Vite as bundler and Vitest as unit test runner...

Considering this, would be great to have an option to use Vitest as test runner for plugins, in that way we can remove jest dependencies...

### Expected Behavior

Provide also Vitest as test runner in plugin generator

### Steps to Reproduce

N/A

### Nx Report

```shell
N/A
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I created also a discussion for this https://github.com/nrwl/nx/discussions/22834

**Comment by gperdomor** [comment]
.

**Comment by gperdomor** [comment]
Not stale

**Comment by SirMishaa** [comment]
Up ?
