### ISSUE TITLE
[Next.js] [Cypress] Support specifying a custom baseUrl

### ISSUE THREAD

**Issue by elliottsj** [nrwl/nx#2289]
## Expected Behavior

Able to specify a custom `baseUrl` when running Cypress tests against a Next.js application. For example, I use a reverse proxy to serve my app on `https://app.example.com`, which forwards traffic to `http://localhost:3001`. I want my Cypress tests to connect to `https://app.example.com`.

## Current Behavior

When using `devServerTarget` with `@nrwl/cypress`, the Cypress process always opens `http://localhost:${options.port}`. `baseUrl` can be passed as an option, but `devServerTarget` cannot be used simultaneously. See https://github.com/nrwl/nx/issues/1614

### Context

Please provide any relevant information about your setup:

```
  @nrwl/angular : Not Found
  @nrwl/cli : 8.11.0
  @nrwl/cypress : 8.11.0
  @nrwl/eslint-plugin-nx : 8.11.0
  @nrwl/express : Not Found
  @nrwl/jest : 8.11.0
  @nrwl/linter : 8.11.0
  @nrwl/nest : Not Found
  @nrwl/next : 8.11.0
  @nrwl/node : Not Found
  @nrwl/react : 8.11.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.11.0
  @nrwl/web : 8.11.0
  @nrwl/workspace : 8.11.0
  typescript : 3.5.3
```

**Comment by vsavkin** [comment]
Closed here: https://github.com/nrwl/nx/pull/2287
