### ISSUE TITLE
Unable to override NODE_ENV during custom Configuration

### ISSUE THREAD

**Issue by techaks** [nrwl/nx#2291]
I am trying to set  NODE_ENV=STAGING

**Comment by Cammisuli** [comment]
Hi @techaks thanks for filing an issue! Can you give a little bit more info? What kind of project are you building (node, angular, react)? What steps did you try to set the environment variable?

**Comment by vsavkin** [comment]
@techak could you provide more info?

**Comment by jaysoo** [comment]
Going to close this as there hasn't been any updates. We do support `NODE_ENV` in our `@nrwl/web:build` builder -- it will basically be replaced by what `NODE_ENV` evaluates to at build time. And for Node apps it will always use `process.env.NODE_ENV`.

**Comment by zyf0330** [comment]
> Going to close this as there hasn't been any updates. We do support `NODE_ENV` in our `@nrwl/web:build` builder -- it will basically be replaced by what `NODE_ENV` evaluates to at build time. And for Node apps it will always use `process.env.NODE_ENV`.

Hello, I use node apps, but `process.env.NODE_ENV` always is `development`, and it is replaced to literal after build by webpack.
