### ISSUE TITLE
npm run affected:* broken when workspace is not in root folder of repo

### ISSUE THREAD

**Issue by dflor003** [nrwl/nx#2292]
## Expected Behavior

I can run affected commands such as `npm run affected:lint` even if my NX workspace is NOT at the root of the git repo.

## Current Behavior

Running `npm run affected:lint` fails with errors when your NX project is in a subdirectory in your git repo instead of off the root. Here's how my folder structure looks:

```
/my-repo
  - package.json # This package.json is for something unrelated
  ... # Other folders omitted for brevity
  /app # This is a self-contained angular project that uses NX
    - package.json
    - nx.json
    - angular.json
    /apps
      ... # Omitted for brevity
    /libs
      ... # Omitted for brevity
```

## Failure Information (for bugs)

I did some digging and it seems like the failure may be in [`file-utils.ts`](https://github.com/nrwl/nx/blob/9c50569c55090d5ec7d16d97ac9a829de5aea9b1/packages/workspace/src/core/file-utils.ts#L75-L77). To get the diff for a file, it shells out to `git show`, but the file path that gets passed is relative to the `nx.json` directory, NOT the git repository root. 

Here's a concrete example:

If you make a change to `/app/package.json`, it will run `git show master:package.json`. 
However, it seems like it would need to run `git show master:app/package.json` to get the correct behavior.

### Steps to Reproduce

1. Create a git repo with a `package.json` at the root with some arbitrary packages
2. Create a sub folder called `app` at the root of the repo
3. Create a new nx workspace inside the `/app` folder
4. Check everything in and push it up to the remote
5. Make a change to the `/app/package.json` file
6. Run `npm run affected:lint` in the `/app` folder

### Context

```bash
$ npx nx report
Root path is C:\Projects\my-repo\app

>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 8.11.0
  @nrwl/cli : 8.11.0
  @nrwl/cypress : 8.11.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.11.0
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.11.0
  @nrwl/web : Not Found
  @nrwl/workspace : 8.11.0
  typescript : 3.5.3
```

### Failure Logs

Here's the error I was getting. Note that `@types/knockout` is a package defined in the root `package.json`:

```
Error: Invalid project name is detected: "@types/knockout"
    at addAffectedNodes (C:\Projects\my-repo\app\node_modules\@nrwl\workspace\src\core\affected-project-graph\affected-project-graph.js:44:15)
    at ctx.touchedProjects.forEach.p (C:\Projects\my-repo\app\node_modules\@nrwl\workspace\src\core\affected-project-graph\affected-project-graph.js:34:9)
    at Array.forEach (<anonymous>)
    at filterAffectedProjects (C:\Projects\my-repo\app\node_modules\@nrwl\workspace\src\core\affected-project-graph\affected-project-graph.js:33:25)
    at Object.filterAffected (C:\Projects\my-repo\app\node_modules\@nrwl\workspace\src\core\affected-project-graph\affected-project-graph.js:22:12)
    at Object.affected (C:\Projects\my-repo\app\node_modules\@nrwl\workspace\src\command-line\affected.js:20:36)
    at Object.exports.commandsObject.yargs.usage.command.command.command.command.command.command.command.command.command.command.command.command.args [as handler] (C:\Projects\my-repo\ap
p\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:70:138)
    at Object.runCommand (C:\Projects\my-repo\app\node_modules\@nrwl\workspace\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\Projects\my-repo\app\node_modules\@nrwl\workspace\node_modules\yargs\yargs.js:1022:30)
    at Object.get [as argv] (C:\Projects\my-repo\app\node_modules\@nrwl\workspace\node_modules\yargs\yargs.js:965:21)
```

**Comment by RichardMisiak** [comment]
I'm seeing the same issue
In our case we have a repo that looks like 
```
api/
  ...
web/
  app/
    package.json
    nx.json
    ...
...
```

Running `affected` from the `app` folder prints:
```
fatal: Path 'web/app/package.json' exists, but not 'package.json'.
Did you mean 'master:Web/closest-friend/package.json' aka 'master:./package.json'?
fatal: Path 'web/app/angular.json' exists, but not 'angular.json'.
Did you mean 'master:Web/app/angular.json' aka 'master:./angular.json'?
fatal: Path 'web/app/package.json' exists, but not 'package.json'.
Did you mean 'web/app/package.json' aka 'master:./package.json'?
```

Present in 8.10.0 and 8.11.0

**Comment by RichardMisiak** [comment]
I'm seeing the same issue
In our case we have a repo that looks like 
```
api/
  ...
web/
  app/
    package.json
    nx.json
    ...
...
```

Running `affected` from the `app` folder prints:
```
fatal: Path 'web/app/package.json' exists, but not 'package.json'.
Did you mean 'master:web/app/package.json' aka 'master:./package.json'?
fatal: Path 'web/app/angular.json' exists, but not 'angular.json'.
Did you mean 'master:web/app/angular.json' aka 'master:./angular.json'?
fatal: Path 'web/app/package.json' exists, but not 'package.json'.
Did you mean 'web/app/package.json' aka 'master:./package.json'?
```

Present in 8.10.0 and 8.11.0

**Comment by mehrad-rafigh** [comment]
This ticket seems to be a duplicate! The same has been reported [here](https://github.com/nrwl/nx/issues/2274)

**Comment by RichardMisiak** [comment]
@mehrad-rafigh I don't think is it, the linked ticket concerns an error occurring for any runs of `nx affected` but this is about a different error that only happens when the nx workspace is not in the repository root
The linked ticket appears to have been fixed in ` 8.11.0` but this issues is still present

**Comment by dflor003** [comment]
Yeah, this is a bug specifically with the way that `git show` is being used to get the diff of a file specifically when the nx workspace is in a sub folder off of the root.

**Comment by jsaguet** [comment]
Hello, 
We are facing the same issue in my company with a project which is not at the root of the git repo.
This makes our build time quite long because we need to run tests and lint for every library in the CI.

There is no problem though when the commands are run from the folder where the package.json is. (on our local machines)

Have someone found a workaround by any chance?
Thank you

**Comment by dflor003** [comment]
No workaround that I'm aware of. Hoping that I've provided enough detail on my synopsis of the issue in the bug report so that one of the contributors can fix it.

**Comment by jlerasmus** [comment]
We are experiencing the same issue.  Our repo folder structure is basically the same as mentioned here: [https://github.com/nrwl/nx/issues/2292#issuecomment-572463139](url)

**Comment by AndrewTaftPlusone** [comment]
We are also experiencing the same issue in v9.0.1.  Our folder structure is a little deeper but it has the same basic problem.
