### ISSUE TITLE
`nx release` fails when publishing packages that have a `prepublishOnly` step that produces console output

### ISSUE THREAD

**Issue by gutentag2012** [nrwl/nx#22925]
### Current Behavior

When running the `nx release` command for packages that have a `prepublishOnly` script that e.g. builds the package, the command fails since it cannot parse the console output as a JSON

### Expected Behavior

It should be possible to publish packages that have a `prepublishOnly` script attached

### Steps to Reproduce

Since this step involves actually publishing to npm, you need to create your own package on npm for this.

1. Create a npm library that is publishable
2. Add the `"prepublishOnly": "echo 'This is only a test'"`
3. Run the `nx release` command
4. Selecte `yes` when it asks to publish the package

### Nx Report

```shell
Node   : 18.20.2
   OS     : win32-x64
   pnpm   : 8.15.6

   nx             : 18.0.2
   @nx/js         : 18.0.2
   @nx/workspace  : 18.0.2
   @nx/devkit     : 18.0.2
   @nrwl/tao      : 18.0.2
   typescript     : 5.4.3
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

I already have a local patch for this and would be willing to open a PR for this.

The issue is [here](https://github.com/nrwl/nx/blob/master/packages/js/src/executors/release-publish/release-publish.impl.ts#L101), there the output of the publish command is parsed without stripping it of previous output.

**Comment by AgentEnder** [comment]
I'm sure a PR would be appreciated 🤗, I've assigned JamesHenry to the issue as he would be the most likely eventual reviewer.

**Comment by gutentag2012** [comment]
I just opened the PR so a review would be very much appreciated :D
PR: #23112
