### ISSUE TITLE
Having files with [ and ] in the name makes format check fail

### ISSUE THREAD

**Issue by wamasimba** [nrwl/nx#22937]
### Current Behavior

When I create files with [ and ] in the name, the format check fails, as it can't find the file. It seems that the filename is passed to a globber, perhaps of the OS, and the executed command fails with `ELIFECYCLE  Command failed with exit code 1.`.

### Expected Behavior

These filenames should be passed in a way that prevents interpretation of the characters in the filename.

### Steps to Reproduce

1. Add file with [] in the name, e.g. permissions[none].json
2. run `nx format:check --base=origin/master --head=HEAD`
-> Result is `ELIFECYCLE  Command failed with exit code 1.`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.9.0
   OS     : win32-x64
   pnpm   : 8.14.2
   
   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/jest           : 18.0.4
   @nx/linter         : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/workspace      : 18.0.4
   @nx/angular        : 18.0.4
   @nx/cypress        : 18.0.4
   @nx/devkit         : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nx/node           : 18.0.4
   @nx/plugin         : 18.0.4
   @nx/storybook      : 18.0.4
   @nrwl/tao          : 18.0.4
   @nx/web            : 18.0.4
   @nx/webpack        : 18.0.4
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc   : 1.1.23
   @ngrx/effects        : 17.1.0
   @ngrx/router-store   : 17.1.0
   @ngrx/store          : 17.1.0
   @ngrx/store-devtools : 17.1.0
   @storybook/angular   : 7.6.14
   @twittwer/compodoc   : 1.12.0
   ng-mocks             : 14.12.1
   nx-stylelint         : 17.1.3
```

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
I can't reproduce this on either platform, can you upload a reproduction repository to help test?
