### ISSUE TITLE
Could not find module "@nrwl/storybook"

### ISSUE THREAD

**Issue by tommyc38** [nrwl/nx#2293]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x ] I checked the documentation (nx.dev) and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior
running the command: `ng g @nrwl/angular:storybook-configuration --name=shared` should generate my project stroybook folder  

Please describe the behavior you are expecting
It should create a project directory in my lib (e.g. shared)

## Current Behavior
instead I get an error that it can't find module "@nrwl/storybook" from my root workspace
What is the current behavior?

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  run: `ng g @nrwl/angular:storybook-configuration --name=shared`
2. go through list of questions answering Y/n
3. receive error: could not find module "@nrwl/storybook" from <workspace-root>

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context

Please provide any relevant information about your setup:

-  @nrwl/angular : 8.11.0
  @nrwl/cli : 8.11.0
  @nrwl/cypress : 8.11.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.11.0
  @nrwl/linter : 8.11.0
  @nrwl/nest : 8.11.0
  @nrwl/next : Not Found
  @nrwl/node : 8.11.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.11.0
  @nrwl/web : Not Found
  @nrwl/workspace : 8.11.0
  typescript : 3.5.3

- 3rd-party libraries and their versions
- and most importantly - a use-case that fails

**A minimal reproduction scenario allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

Please include any relevant log snippets or files here.

## Other

Any other relevant information that will help us help you.

**Comment by tommyc38** [comment]
I ran: `npm -D install @nrwl/storybook` and that seemed to work.  You may want to add this step to your documentation.  The issue I have now appears to be #2121.  All of my components are broken out into modules within the lib.  I am assuming many others are also doing this as well.

**Comment by tommyc38** [comment]
I get the note below when running `nx g @nrwl/angular:storybook-configuration project-name`.  Is this accurate because its not part of your documentation.  Moreover, I go through the three questions and then run into an error (e.g. no declarations array in the @NgModule decorator in libs/shared/src/lib/shared.module.ts) which relates to #2121.  

Storybook functionality seems unusable.


<img width="568" alt="Screen Shot 2020-01-13 at 1 02 25 PM" src="https://user-images.githubusercontent.com/10190567/72287848-04b61680-3605-11ea-8670-53a0b227254f.png">

**Comment by FrozenPandaz** [comment]
The docs are here:

https://github.com/nrwl/nx/blob/master/docs/angular/guides/modernize-storybook.md

Would someone like to contribute a line, in the beginning, to instruct how to install storybook?

**Comment by tommyc38** [comment]
@FrozenPandaz, I got it working and will make a pull request with updated guide info.
