### ISSUE TITLE
React generator Always bundles with Vite event when you tell it not too

### ISSUE THREAD

**Issue by ZNackasha** [nrwl/nx#22959]
### Current Behavior

running the following command will still generate a vite.config.ts file

```
yarn nx g @nx/react:lib library-name --directory=library-dir --importPath=@benzinga/lib-import-path --compiler=swc --bundler=none
```

### Expected Behavior

dont generate a vite config 

### Steps to Reproduce

1. run `yarn nx g @nx/react:lib library-name --directory=library-dir --importPath=@benzinga/lib-import-path --compiler=swc --bundler=none`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 18.18.0
OS     : win32-x64
yarn   : 1.22.19

nx                 : 18.3.3
@nx/js             : 18.3.3
@nx/jest           : 18.3.3
@nx/linter         : 18.3.3
@nx/eslint         : 18.3.3
@nx/workspace      : 18.3.3
@nx/cypress        : 18.3.3
@nx/devkit         : 18.3.3
@nx/esbuild        : 18.3.3
@nx/eslint-plugin  : 18.3.3
@nx/next           : 18.3.3
@nx/node           : 18.3.3
@nx/react          : 18.3.3
@nx/react-native   : 18.3.3
@nrwl/tao          : 18.3.3
@nx/vite           : 18.3.3
@nx/web            : 18.3.3
@nx/webpack        : 18.3.3
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/jest/plugin
@nx/vite/plugin
@nx/cypress/plugin
@nx/next/plugin
@nx/react-native/plugin

Done in 10.95s.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
I don't see `vite.config.ts` file being generated. It is possible that you are using Vitest, and thus the config file is used just for testing. In the latter case, you'll see that the config file has `test` property on it.

Here's an example repo that you can try yourself: https://github.com/jaysoo/issue22959
