### ISSUE TITLE
Build fails for a new next(v14.0) project

### ISSUE THREAD

**Issue by rabira-hierpa** [nrwl/nx#22952]
### Current Behavior

Hello I created an `nx` project and added a `Next.js v14.0` app  and tried to build the project with the following build option under `project.json`

```json
"build": {
      "executor": "@nx/next:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "outputPath": "dist/apps/frontend",
        "buildTarget": "frontend:build",
        "postcssConfig": "apps/frontend/postcss.config.js",
        "tsConfig": "apps/frontend/tsconfig.json"
      },
      "configurations": {
        "development": {
          "outputPath": "dist/apps/dev/frontend"
        },
        "production": {
          "outputPath": "dist/apps/frontend",
          "buildTarget": "frontend:build:production"
        }
      }
    },
```

Then I tried to build the project with the following command 

```bash 
> nx run frontend:build:production


> Build error occurred
RangeError: Maximum call stack size exceeded
    at readPackageScope (node:internal/modules/cjs/loader:377:26)
    at trySelf (node:internal/modules/cjs/loader:506:40)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1025:24)
    at /XX/playground/next-nx/node_modules/next/dist/server/require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at mod.require (/XX/playground/next-nx/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:130:18)
    at getNxContext (XX/playground/next-nx/node_modules/@nx/next/plugins/with-nx.js:24:50)
    at getNxContext (XX/playground/next-nx/node_modules/@nx/next/plugins/with-nx.js:44:16)
Build process exited due to code 1  

 NX   Ran target build for project frontend (2s)

   ✖  1/1 failed
   ✔  0/1 succeeded [0 read from cache]

```

### Expected Behavior

Should build the next project and produce the output on to the `ouputPath` directory specifed in under `build` option in `project.json`

### GitHub Repo

https://github.com/rabira-hierpa/next-nx

### Steps to Reproduce

1. Clone the repo at https://github.com/rabira-hierpa/next-nx
2. Install the dependencies using `pnpm` 
3. Run the build command nx run frontend:build:production
4. Observe the output for the command

### Nx Report

```shell
Nx report

Node   : 20.12.2
OS     : darwin-arm64
npm    : 10.5.0

nx (global)        : 18.3.3
nx                 : 18.3.3
@nx/js             : 18.3.3
@nx/jest           : 18.3.3
@nx/linter         : 18.3.3
@nx/eslint         : 18.3.3
@nx/workspace      : 18.3.3
@nx/cypress        : 18.3.3
@nx/devkit         : 18.3.3
@nx/eslint-plugin  : 18.3.3
@nx/next           : 18.3.3
@nx/react          : 18.3.3
@nrwl/tao          : 18.3.3
@nx/web            : 18.3.3
@nx/webpack        : 18.3.3
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/next/plugin
@nx/cypress/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

### Package Manager Version (pnpm)

10.5.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Hey @rabira-hierpa :) 

Did you manually edit the `project.json` here at all?

It don't think you should have `buildTarget` in your options.

**Comment by rabira-hierpa** [comment]
Hey @Coly010 
Yes I did add some of the options on `project.json`  manually and `buildTarget` is required.

```bash

> nx run frontend:serve


 NX   Required property 'buildTarget' is missing

```

**Comment by ndcunningham** [comment]
`serve` requires a `buildTarget` because you need to build the app first before serving it.
However your `project.json` has some invalid configurations like `buildTarget`, `tsConfig` for `build`.

These are not options which we generate when you create a new app. 

I **removed** them from your code and tried to build again and it's working.
