### ISSUE TITLE
Docs: add explanation and example strategies around affected and lock files

### ISSUE THREAD

**Issue by blordpluto** [nrwl/nx#22960]
### Documentation issue

- [x] Documentation improvement

@meeroslav This was promised last year, still hoping to see it soon. 😄 See:

https://github.com/nrwl/nx/issues/15116#issuecomment-1620019479

In general, the relationship of the dependency graph to lockfiles feels underdocumented across the entire project. This is a major topic and deserves a bit more IMO. Thanks!

**Comment by miluoshi** [comment]
This should have not been closed. See the linked comment above.
