### ISSUE TITLE
Can't use Tailwindcss in Nx Next project

### ISSUE THREAD

**Issue by juuyan** [nrwl/nx#2298]
I am using 8.9.0 nx.

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior
It should work.

## Current Behavior
```
[ error ] ./styles/main.css
Error: Didn't get a result from child compiler
```

### Steps to Reproduce
1. `npx create-nx-workspace@latest my-org`
2. `yarn add --dev @nrwl/next`
3. `nx g @nrwl/next:application my-project`
4. `yarn add tailwindcss autoprefixer postcss-loader @zeit/next-css`
5. `cd apps/my-project`
6. create
```
postcss.config.js
module.exports = {
  plugins: [
    require('tailwindcss'),
    require('autoprefixer')
  ]
};
```
7. create
```
next.config.js
const withCSS = require('@zeit/next-css');
module.exports = withCSS({});
```
8. create
```
styles/main.css
@tailwind base;
@tailwind components;
@tailwind utilities;
```
9. create a default _app.js in pages
10. add `import '../styles/main.css'` in _app.js
11. run serve
12. see the error in terminal

Compared with in a normal Next project, is there any extra efforts I need to do to make it work?

**Comment by juuyan** [comment]
I have solved the problem by myself.
Basically my issues come from the misunderstanding of how nx works.

Here is how I added tailwind in next.js project
1. install `tailwind` and `autoprefixer` in the workspace
2. create `tailwind.config.js` and `tailwind.css`. 
3. import `tailwind.css` at `_app.tsx`
4. create
```
next.config.js
const path = require('path');

module.exports = {
  webpack: config => {
    config.module.rules.push({
      test: /\.css$/,
      use: [
        {
          loader: 'postcss-loader',
          options: {
            ident: 'postcss',
            plugins: [
              require('tailwindcss')(
                path.resolve(__dirname, 'tailwind.config.js') // the absolute path of your tailwind.config.js
              ),
              require('autoprefixer')
            ]
          }
        }
      ],
      // the absolute path of the folder contains tailwind.css
      // I reuse tailwind.css across projects and libs so I put it in the workspace root
      // Maybe I should create a lib for it.
      include: path.resolve('./global') 
    });

    return config;
  }
};
```

It is similar if you wanna integrate Tailwind with lib's storybook or in projects of other framework. Just find the way to push rules to webpack config.

Hope it helps.

**Comment by naillizard** [comment]
I found that even without extending the webpack through next.config.js by simply creating the postcss.config.js or json it works, but by default it will try to locate the tailwind.config.js file at the root of the project not the app, of course you can override that in postcss.config.js file.

However, tailwindcss ships with purge by default, and I found that purge is not working for some reason.

apps
- webapp
-- postcss.config.js
tailwind.config.js

tailwind.config.js
```js
module.exports = {
  purge: [
    './apps/webapp/layouts/**/*.{js,ts,jsx,tsx}',
    './apps/webapp/pages/**/*.{js,ts,jsx,tsx}',
  ]
}
```

postcss.config.js
```js
module.exports = {
  plugins: [
    'tailwindcss',
    'postcss-flexbugs-fixes',
    [
      'postcss-preset-env',
      {
        autoprefixer: {
          flexbox: 'no-2009',
        },
        stage: 3,
        features: {
          'custom-properties': false,
        },
      },
    ],
  ],
};
```

**Comment by kuccello** [comment]
Here is the approach I use:
https://kuccello.medium.com/nx-react-tailwind-css-made-simple-7ab71d39e678

**Comment by erkobridee** [comment]
@naillizard about the tailwind optimization output using purge, I also had the same issue here, and I solve it following the [tailwindcss documentation to manually set it to enable](https://tailwindcss.com/docs/optimizing-for-production#enabling-manually)

so, having the `NODE_ENV=production`, it set to true in my case

```
module.exports = {
  purge: {
    enabled: process.env.NODE_ENV === 'production',
    content: [
      './apps/webapp/layouts/**/*.{js,ts,jsx,tsx}',
      './apps/webapp/pages/**/*.{js,ts,jsx,tsx}',
    ]
  }
}
```

**Comment by naillizard** [comment]
oh awesome, thanks!
