### ISSUE TITLE
Modify the Project Graph - Is this up to date with Project Crystal?

### ISSUE THREAD

**Issue by caioquirino** [nrwl/nx#22996]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/extending-nx/recipes/project-graph-plugins

### Additional context or description

Hi awesome @nrwl team! I am trying to write plugins to be used within the same nx monorepo.
The structure is like:
```
<monorepo root>
/apps/<app>
/libs/<lib>
/plugins/<plugin>
```

So, after creating the plugin and its executors, I am trying to, based on the presence of a file, add a specific target to the project's task graph. I am following that documentation, but it looks different than when I look at the [Vite plugin](https://github.com/nrwl/nx/tree/master/packages/vite) for example. Should this page be updated to adhere to Project Crystal way?

Thanks!

**Comment by AgentEnder** [comment]
The page has been updated for crystal. Do you have any specific questions or noted discrepancies?
