### ISSUE TITLE
Infrastructure as Code for Enterprise applications

### ISSUE THREAD

**Issue by MitkoTschimev** [nrwl/nx#2300]
Hello everyone,

I would like to know what you think about my idea. Let's start at the beginning. I played with a lot of tools for IaC (Infrastructure as Code) inside angular. In the end, it doesn't matter which tool you are using at the moment. Every time it ends up that you are really restricted. Every one of us knows how complex the infrastructure on enterprise-level looks like. You have to consider more things than just deploying my app to a server / serverless function / CDN somewhere.

I use NX since really early stages and just love it and I would like to fill this gap. But I need a bit of help from you.
So my idea is to use [terraform](https://www.terraform.io/) for handling this. Why terraform? 
In my opinion, it is a nice solution to have a clean understandable code for your infrastructure. It supports a mass of [providers](https://www.terraform.io/docs/providers/index.html) (which will help us to support almost everyone here, azure, aws, google cloud, ...). You can provide the code inside the project. Not hidden somewhere in cached directories. Easy extendable for use cases like VPC's, ...
You could even create modules (libs) which can have dependencies with each other. Tooling for [dependency graphs](https://www.terraform.io/docs/commands/graph.html) is already existing too.
So we can find a lot of similarities.

I already started inside a clone from this repository. But before I dive in deeper. What do you think?
Would you like to have this kind of tooling?

Another one could be [Pulumi](https://www.pulumi.com/), but it has not so many provider support but still, the big players and you can write the IaC in typescript/javascript.

**Comment by MitkoTschimev** [comment]
Just for your information. I started it as my own project now. Not anymore as part of this codebase. The progress is going forward. Please feel free and take a look ;)

https://github.com/Dev-Thought/ng-deploy-universal

Currently, nx angular workspaces are supported and you should give it a try ;)

**Comment by MitkoTschimev** [comment]
Does the new nx plugin system support ng-add too?

My plugin is working currently for nx with ng, nx native and angular cli. I like the new plugin system but afraid to lose the ability to support all 3 of them.

**Comment by wesleygrimes** [comment]
Yes it should. We have an approved plugin that uses ng add today. It’s the karma to jest one.

**Comment by MitkoTschimev** [comment]
Hmm ok just to be sure I was describing everything right.
It event can support native angular cli with ng-add or just the ng-add schematic as a link?

https://github.com/Dev-Thought/ng-deploy-it/issues/32

**Comment by wesleygrimes** [comment]
Correct

**Comment by MitkoTschimev** [comment]
This functionality is provided by Nx DeployIt.


https://github.com/Dev-Thought/nx-plugins/tree/master/libs/nx-deploy-it

Issue can be closed
