### ISSUE TITLE
Default --preset=expo workspace .toHaveTextContent in App.spec.tsx contains a TypeScript error

### ISSUE THREAD

**Issue by danharten-sovtech** [nrwl/nx#23027]
### Current Behavior

Currently, `.toHaveTextContent` greets the developer with: `Property 'toHaveTextContent' does not exist on type 'JestMatchers<ReactTestInstance>'.`

### Expected Behavior

No TypeScript error. 

To fix this, update tsconfig.spec.json `types` to include the appropriate types, like so: `"types": ["jest", "node", "@testing-library/jest-native"]`

This way, the expo preset can be presented error free.

### Steps to Reproduce

1. run `npx create-nx-workspace@latest --preset=expo --appName=your-app-name`
2. Navigate to app/App.spec.tsx
3. See typescript error

### Nx Report

```shell
Node   : 20.9.0
OS     : darwin-arm64
npm    : 10.1.0

nx (global)        : 18.3.2
nx                 : 18.3.4
@nx/js             : 18.3.4
@nx/jest           : 18.3.4
@nx/linter         : 18.3.4
@nx/eslint         : 18.3.4
@nx/workspace      : 18.3.4
@nx/detox          : 18.3.4
@nx/devkit         : 18.3.4
@nx/eslint-plugin  : 18.3.4
@nx/expo           : 18.3.4
@nx/react          : 18.3.4
@nrwl/tao          : 18.3.4
@nx/web            : 18.3.4
@nx/webpack        : 18.3.4
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/expo/plugin
@nx/eslint/plugin
@nx/jest/plugin
@nx/detox/plugin
```

### Package Manager Version

1.22.19

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
or you can fix it by adding the setup file:
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "module": "commonjs",
    "types": ["jest", "node"]
  },
  "files": ["./test-setup.ts"],
  "include": [
    "jest.config.ts",
    "src/**/*.test.ts",
    "src/**/*.spec.ts",
    "src/**/*.test.tsx",
    "src/**/*.spec.tsx",
    "src/**/*.test.js",
    "src/**/*.spec.js",
    "src/**/*.test.jsx",
    "src/**/*.spec.jsx",
    "src/**/*.d.ts"
  ]
}
```

I will do a proper fix.

**Comment by danharten-sovtech** [comment]
Thank you @xiongemi! Really appreciate it.
