### ISSUE TITLE
Cannot install Nx

### ISSUE THREAD

**Issue by Vorakor** [nrwl/nx#2303]
## Expected Behavior

I expect that when I enter the command `npm init nx-workspace project-name-here` the command will create a folder, put a package.json in it and create a blank nx workspace.

I am on a Windows 10 machine, and I've used Nx before, I don't understand why it isn't working.

## Current Behavior

It errors out, so I tried starting off with an Angular workspace and adding the nx to it, and that failed as well.

## Failure Information (for bugs)

npm init nx-workspace vorakor-samples-workspace
Error: EPERM: operation not permitted, mkdir 'C:\Users\<username>'
TypeError: Cannot read property 'loaded' of undefined
    at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:98:27)
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:216:3)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:77:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:225:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:263:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:83:7
    at Array.forEach (<anonymous>)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:82:13
    at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:173:20)
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:98

TypeError: Cannot read property 'loaded' of undefined
    at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:98:27)
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:216:3)
    at process.emit (events.js:198:13)
    at process._fatalException (internal/bootstrap/node.js:496:27)
Install for create-nx-workspace@latest failed with code 7
PS C:\Users\<username>\Development> npm config edit      
PS C:\Users\<username>\Development> npm init nx-workspace vorakor-samples-workspace
Error: EPERM: operation not permitted, mkdir 'C:\Users\<username>'
TypeError: Cannot read property 'loaded' of undefined
    at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:98:27)
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:216:3)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:77:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:225:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:263:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:83:7
    at Array.forEach (<anonymous>)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:82:13
    at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:173:20)
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:98
                          ^

TypeError: Cannot read property 'loaded' of undefined
    at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:98:27)
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:216:3)
    at process.emit (events.js:198:13)
    at process._fatalException (internal/bootstrap/node.js:496:27)
Install for create-nx-workspace@latest failed with code 7
PS C:\Users\<username>\Development> npm init nx-workspace vorakor-samples-workspace
Error: EPERM: operation not permitted, mkdir 'C:\Users\<username>'
TypeError: Cannot read property 'loaded' of undefined
    at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:98:27)
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:216:3)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:77:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:225:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:263:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:83:7
    at Array.forEach (<anonymous>)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:82:13
    at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:173:20)
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:98
                          ^
    at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:98:27)
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:216:3)
    at process.emit (events.js:198:13)
    at process._fatalException (internal/bootstrap/node.js:496:27)
Install for create-nx-workspace@latest failed with code 7
PS C:\Users\<username>\Development> whoami
376l\<username>
PS C:\Users\<username>\Development> npm config edit
PS C:\Users\<username>\Development> ng new vorakor-samples-workspace --create-application=false
CREATE vorakor-samples-workspace/angular.json (135 bytes)
CREATE vorakor-samples-workspace/package.json (1261 bytes)
CREATE vorakor-samples-workspace/README.md (1041 bytes)
CREATE vorakor-samples-workspace/tsconfig.json (543 bytes)
CREATE vorakor-samples-workspace/tslint.json (1761 bytes)
CREATE vorakor-samples-workspace/.editorconfig (246 bytes)
CREATE vorakor-samples-workspace/.gitignore (631 bytes)
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

> core-js@2.6.11 postinstall C:\Users\<username>\Development\vorakor-samples-workspace\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

> @angular/cli@8.3.22 postinstall C:\Users\<username>\Development\vorakor-samples-workspace\node_modules\@angular\cli
> node ./bin/postinstall/script.js

npm WARN karma-jasmine-html-reporter@1.5.1 requires a peer of jasmine-core@>=3.5 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 697 packages from 851 contributors and audited 8170 packages in 21.884s
found 0 vulnerabilities

warning: LF will be replaced by CRLF in .editorconfig.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in .gitignore.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in README.md.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in angular.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in package.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in tsconfig.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in tslint.json.
The file will have its original line endings in your working directory
    Successfully initialized git.
PS C:\Users\<username>\Development> cd .\vorakor-samples-workspace\
PS C:\Users\<username>\Development\vorakor-samples-workspace> ls

    Directory: C:\Users\<username>\Development\vorakor-samples-workspace

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        1/11/2020     22:05                node_modules
-a----        1/11/2020     22:04            246 .editorconfig
-a----        1/11/2020     22:04            135 angular.json
-a----        1/11/2020     22:05         239584 package-lock.json
-a----        1/11/2020     22:04           1261 package.json
-a----        1/11/2020     22:04           1041 README.md
-a----        1/11/2020     22:04            543 tsconfig.json
-a----        1/11/2020     22:04           1761 tslint.json

PS C:\Users\<username>\Development\vorakor-samples-workspace> npm init nx-workspace
npm ERR! code ENOLOCAL

npm ERR! A complete log of this run can be found in:
Install for create-nx-workspace@latest failed with code 1
PS C:\Users\<username>\Development\vorakor-samples-workspace> ng add @nrwl/workspace
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Cannot read property 'replace' of undefined
PS C:\Users\<username>\Development\vorakor-samples-workspace> ng add @nrwl/workspace
Skipping installation: Package already installed
Cannot read property 'replace' of undefined
PS C:\Users\<username>\Development\vorakor-samples-workspace> ng add @nrwl/workspace
Installing packages for tooling via npm.
Installed packages for tooling via npm.
An unhandled exception occurred: Cannot find module 'typescript'
See "C:\Users\<username>\AppData\Local\Temp\ng-3rJ4Ja\angular-errors.log" for further details.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Changed directory to be outside of existing projects but still in desired folder where I want to create a new folder to contain workspace.
2. Entered command.
3. Upon failing multiple times, I used `ng new project-workspace-name-here --create-application=false` to create a new blank Angular workspace.
4. Upon creation of new workspace, changed directories into the workspace.
5. Attempted to run `npm init nx-workspace` again.
6. Upon failure again, attempted to run `ng add @nrwl/workspace`
7. Upon yet another failure, submitted ticket.

### Context

Using latest version of Nx, NPM version 6.9.0, node version 10.16.3, Windows 10 OS, Visual Studio Code.

**Comment by dylanesque** [comment]
Having the same problem, latest nx, NPM v6.13.4, Node v12.14.0, LLatest Angular CLI. Windows 10. I installed the latest version of TS, did not change.

**Comment by ruslanguns** [comment]
Any news ?

**Comment by nickinnon** [comment]
I ran into this issue on Windows 10 building an empty workspace/nx-cli.

I noticed the dir I was building in had a node_modules directory and package.json file. After removing those, my build completed as expected.

YMMV

**Comment by curiouscod3** [comment]
same issue ; I used the latest nx

>   npm: '6.14.4',
>   node: '10.15.3',

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by bsultonov** [comment]
Try to place your _npm-cache_ folder to another path by running 
`npm config set cache C:\tmp\nodejs\npm-cache --global`

**Comment by vsavkin** [comment]
Do you have the same issue when using `npx create-nx-workspace@latest`?

**Comment by dauth-dev** [comment]
replacing the npm-cache solved it for me. Thanks!

**Comment by FrozenPandaz** [comment]
Going to close this issue as it is quite old. If you still encounter this issue, please open a new issue with updated details.

**Comment by nhhockeyplayer** [comment]
well this is now new

with all the latest flanking issues plaguing angular@12

I created a nrwl/nx lib named shared-assets

and I manually fabricated its install to my node_modules dir during build
and its been running fine for months

somehow code snuck in thats seeking a package.json in my monorepo INSIDE the libs dir for this library

when the monorepo is standard for only 1 package.json at root dir

I give grace for nxtend and capacitor schematic as its still in dev

package.json
`    "@energy/shared-assets": "file:libs/shared-assets/src",`

here is my build error

workspace.json
```
        "shared-assets": {
            "projectType": "library",
            "root": "libs/shared-assets",
            "sourceRoot": "libs/shared-assets/src",
            "prefix": "energy",
            "architect": {
                "lint": {
                    "builder": "@angular-devkit/build-angular:tslint",
                    "options": {
                        "tsConfig": [
                            "libs/shared-assets/tsconfig.lib.json",
                            "libs/shared-assets/tsconfig.spec.json"
                        ],
                        "exclude": [
                            "**/node_modules/**",
                            "!libs/shared-assets/**/*"
                        ]
                    }
                },
                "test": {
                    "builder": "@nrwl/jest:jest",
                    "options": {
                        "jestConfig": "libs/shared-assets/jest.config.js",
                        "passWithNoTests": true
                    }
                }
            },
            "schematics": {
                "@schematics/angular:component": {
                    "style": "scss"
                }
            }
        },
```

cli
`
meanstack02@admin energy % ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.1.2
Node: 12.22.1
OS: darwin x64

Angular: <error>
... animations, cdk, common, compiler, compiler-cli, core
... flex-layout, forms, language-service, material
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.2 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            11.1.2 (cli-only)
@angular-devkit/schematics      11.1.2 (cli-only)
@angular/cli                    11.1.2 (cli-only)
@schematics/angular             11.1.2 (cli-only)
@schematics/update              0.1101.2 (cli-only)
rxjs                            6.6.7
typescript                      4.2.3 (cli-only)
`

**Comment by nhhockeyplayer** [comment]
or something is going a run under the hood

**Comment by nhhockeyplayer** [comment]
I try to build it individually with nx build shared-assets

this is what comes

```
meanstack02@admin energy % nx build shared-assets
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '@nrwl/workspace/src/utilities/perf-logging'
Require stack:
- /Users/meanstack02/node_modules/@nrwl/cli/lib/init-local.js
- /Users/meanstack02/node_modules/@nrwl/cli/bin/nx.js
- /Users/meanstack02/.config/yarn/global/node_modules/@nrwl/cli/bin/nx.js
- /Users/meanstack02/.config/yarn/global/node_modules/nx/bin/nx.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/Users/meanstack02/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.initLocal (/Users/meanstack02/node_modules/@nrwl/cli/lib/init-local.js:17:5)
    at Object.<anonymous> (/Users/meanstack02/node_modules/@nrwl/cli/bin/nx.js:43:18)
    at Module._compile (/Users/meanstack02/.config/yarn/global/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/meanstack02/node_modules/@nrwl/cli/lib/init-local.js',
    '/Users/meanstack02/node_modules/@nrwl/cli/bin/nx.js',
    '/Users/meanstack02/.config/yarn/global/node_modules/@nrwl/cli/bin/nx.js',
    '/Users/meanstack02/.config/yarn/global/node_modules/nx/bin/nx.js'
  ]
}
```
