### ISSUE TITLE
React Tutorial Step 4 sample code missing import

### ISSUE THREAD

**Issue by dArignac** [nrwl/nx#2304]
## Expected Behavior

The tutorial application runs and shows no errors after updating the code with provided source code of step 4 (https://nx.dev/react/tutorial/04-connect-to-api)

## Current Behavior

The application runs, but provides an error:
```
ERROR in /home/alex/nx-test/apps/todos/src/app/app.tsx(17,3):
TS2304: Cannot find name 'useEffect'.
```

This leads to not being able to answer the question at the end of tutorial step 4 correctly.

The import line should be adjusted to `import React, { useEffect, useState } from 'react';` and should be included in the provided code on the tutorial page.

### Steps to Reproduce

1. Follow the React tutorial along until and including step 4

**Comment by FrozenPandaz** [comment]
The docs are here.

Would someone like to contribute a fix?

**Comment by dArignac** [comment]
Sure, will create a PR asap.
