### ISSUE TITLE
Nest tests not working correctly with cross module import

### ISSUE THREAD

**Issue by wojtek1150** [nrwl/nx#2306]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency) - **not sure, this is configuration issue for me, errors in @rwml module**

## Expected Behavior

Imports should work correctly

## Current Behavior

When some library is used in tested component tests are failed with message:

```
apps/<app_name>/src/...spec.ts
  ● Test suite failed to run

    Configuration error:

    Could not locate module @<workspace_name>/shared/<lib_name> mapped as:
    ../../libs/shared/<lib_name>/src/index.ts.

    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/@<workspace_name>\/shared\/<lib_name>/": "../../libs/shared/<lib_name>/src/index.ts"
      },
      "resolver": .../node_modules/@nrwl/jest/plugins/resolver.js
    }


      at createNoMappedModuleFoundError (../../node_modules/jest-resolve/build/index.js:501:17)
      at Object.<anonymous> (src/...service.ts:213:25)
``` 

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create an empty workspace and add angular with jest as a test runner (or angular workspace)
2. Create an application
3. Create a library
4. Use library service in application service
5. Write a test for this service (you have to import that service here)
6. Try to run the test

With mocking the service (so no import from another lib) it will work of course, but situation 2:

1. Create an empty workspace and add angular with jest as a test runner (or angular workspace)
2. Create an application
4. Create a library helper with statics methods
5. Use some function from lib in application service (static method, so no provider)
5. Write a test for this service (you have to import that service here)
6. Try to run a test

And more complex:

1. Create an empty workspace and add angular with jest as a test runner (or angular workspace)
2. Create an application
3. Create a library (A)
4. Create a library helper (B) with statics methods
5. Use helper in lib (A) service
4. Use library service (A) in application service
5. Write a test for this service (you have to import that service here)
6. Try to run a test

### Context

Please provide any relevant information about your setup:

```
    "@angular/xxxx": "^8.2"
    "@angular-devkit/build-angular": "^0.803.22",
    "@angular-devkit/build-ng-packagr": "~0.801.1",
    "@angular/cli": "^8.3.22",
    "@angular/compiler-cli": "^8.0.2",
    "@nrwl/jest": "^8.10.1",
    "@nrwl/workspace": "8.4.3",
    "jest": "^24.9.0",
    "jest-preset-angular": "^7.0.0",
```

**A minimal reproduction scenario allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

**Comment by FrozenPandaz** [comment]
Please provide a repo exhibiting the issue to help us debug the issue.

**Comment by helgetan** [comment]
in my config i have something like this maybe this helps.
   moduleNameMapper: {
        '^@workspace-name/(.*)$': "<rootDir>/libs/$1/src/index.ts"
    }
jest can't import tsconfig paths variables correctly 
-> check this issue https://github.com/kulshekhar/ts-jest/issues/414

**Comment by Cammisuli** [comment]
It looks like `ts-jest` has support to automap the tsconfig paths to jest's `moduleNameMapper`:
https://kulshekhar.github.io/ts-jest/user/config/#jest-config-with-helper

```
// jest.config.js
const { pathsToModuleNameMapper } = require('ts-jest/utils');
// In the following statement, replace `./tsconfig` with the path to your `tsconfig` file
// which contains the path mapping (ie the `compilerOptions.paths` option):
const { compilerOptions } = require('./tsconfig');

module.exports = {
  // [..]
  // prefix is important, make sure to add it for Nx
  moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, { prefix: '<rootDir>/' } )
};
```

We could possibly add it by default in the jest config that's generated.

**Comment by maxime1992** [comment]
I just encountered this issue. 

Reading the comment from @Cammisuli:

> The resolver we have for jest (@nrwl/jest/plugins/resolver) should be able to resolve files based on the tsconfig already

I tried removing everything within `moduleNameMapper` and it just worked :)

**Comment by Cammisuli** [comment]
Is there still an issue with this, even with the comments above?

**Comment by rhyek** [comment]
I am currently experiencing this. Tried the above example code and it does not help:
```
   moduleNameMapper: {
        '^@somethingsomething/(.*)$': "<rootDir>/libs/$1/src/index.ts"
   }
```

**Comment by Cammisuli** [comment]
@rhyek we have a Jest resolver that should know how to find your lib projects. This does not work properly if you use the `moduleNameMapper`. Can you try to remove that property and see if it works?

**Comment by rhyek** [comment]
@Cammisuli by default that property isn't present in the configuration file. I only added it to see if it helped with the error. Again, the import that's failing is in my global setup file. I have not tested in an actual test file.

**Comment by Cammisuli** [comment]
Can you provide a repo that shows the error? I don't think I understand because I can't reproduce it 😞

**Comment by Durisvk** [comment]
Hey, in case someone's still experiencing this issue, here's how I've managed to solve it:

Add the following snippet into `jest.config.js` under each project (requires quite a lot of manual work...):
```js
const preset = require('@nrwl/jest/preset');

module.exports = {
  ...preset.default,
  // Your previous config goes here - I'm pasting my own here:
  displayName: 'ui-components',
  preset: '../../jest.preset.js',
  transform: {
    '^.+\\.[tj]sx?$': 'babel-jest',
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  coverageDirectory: '../../coverage/libs/ui-components',
}
```

I've figured out the solution based on this comment: https://github.com/nrwl/nx/issues/10100#issuecomment-1161718570

The error started to occur after upgrading from NX 13.1 to 15.1
Maybe this solution should be added to a migration script cause I definitely didn't know this is necessary all of a sudden...
