### ISSUE TITLE
Support typescript 3.7.4 and optional chaining for React

### ISSUE THREAD

**Issue by KrzysztofCzaplejewicz** [nrwl/nx#2311]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

## Expected Behavior

Will @nrwl/react support typescript 3.7.4 and optional chaining?

**Comment by puku0x** [comment]
It seems we need to add Babel plugins in `webpack.config.js` https://github.com/nrwl/nx/issues/1931#issuecomment-571398087 to use Optional Chaining because Nx currently uses `@babel/preset-env@7.5.5`.
https://github.com/nrwl/nx/blob/master/packages/web/package.json#L45

**Comment by Hotell** [comment]
easiest solution would be to bump to latest babel [7.8 and babel-preset which supports those features by default](https://babeljs.io/blog/2020/01/11/7.8.0#ecmascript-2020-default-support-10811-https-githubcom-babel-babel-pull-10811-10817-https-githubcom-babel-babel-pull-10817-10819-https-githubcom-babel-babel-pull-10819-10843-https-githubcom-babel-babel-pull-10843)

**Comment by jaysoo** [comment]
The bump to 7.8.0 will be in the next version. PR is here https://github.com/nrwl/nx/pull/2346
