### ISSUE TITLE
ReferenceError: jest is not defined on a newly created project

### ISSUE THREAD

**Issue by psousa50** [nrwl/nx#23148]
### Current Behavior

I created a project with the following configurations:

✔ Which stack do you want to use? · react
✔ What framework would you like to use? · none
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · test-nx
✔ Which bundler would you like to use? · vite
✔ Test runner to use for end to end (E2E) tests · none
✔ Default stylesheet format · tailwind
✔ Do you want Nx Cloud to make your CI fast? · skip

When I add a line that uses jest to a test, for instance:

```javascript
  it('should have a greeting as the title', () => {
    const m = jest.fn();
    const { getByText } = render(<App />);
    expect(getByText(/Welcome test-nx/gi)).toBeTruthy();
  });
```

I get this error when I run the tests:

```bash
ReferenceError: jest is not defined
```

### Expected Behavior

The test should run successfully

### GitHub Repo

https://github.com/nrwl/nx-examples

### Steps to Reproduce

1. Add the following code at line 12 of the file `app.spec.tsx` inside the `inventory` app: 

```javascript
const m = jest.fn();
```

2. Run the tests:

```bash
nx test inventory 
```

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 18.18.2
OS     : darwin-x64
npm    : 10.2.5

nx (global)        : 18.3.4
nx                 : 18.0.5
@nx/js             : 18.0.5
@nx/linter         : 18.0.5
@nx/eslint         : 18.0.5
@nx/workspace      : 18.0.5
@nx/cypress        : 18.0.5
@nx/devkit         : 18.0.5
@nx/eslint-plugin  : 18.0.5
@nx/react          : 18.0.5
@nrwl/tao          : 18.0.5
@nx/vite           : 18.0.5
@nx/web            : 18.0.5
typescript         : 5.2.2
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I've tried a few things to solve the problem like running `nx add @nx/jest`, and creating a `jest.config.js` file. Nothing worked. Maybe I'm missing something here, but I was expecting Nx to work with Jest out of the box

**Comment by psousa50** [comment]
I probably should be using vitest...

**Comment by AgentEnder** [comment]
I'm a bit confused, you linked the nx-examples repo which contains 2 apps (cart and products). The file you mentioned modifying doesn't exist within it. Are you looking at a different branch?

For what its worth, I do believe that generating a new workspace using vite would setup vitest rather than jest by default. So `jest` would not be defined. 

If you'd like to use jest, you'd need to do the `nx add @nx/jest` and have your jest config as mentioned, and ensure that the jest config is in your project's root.

**Comment by psousa50** [comment]
Hi @AgentEnder ,

thank you for your response. I think I've read somewhere that Nx was configured to use Jest by default, so I expected it to work on a newly created project. I know I tried to add later the `@nx/jest` plugin, but it also didn't work.

Anyway, I've decided to use Vitest now and everything is working fine
