### ISSUE TITLE
`nx serve` builds, starts server, tells me its hosted and ready, then just exits

### ISSUE THREAD

**Issue by asgerjensen** [nrwl/nx#23160]
### Current Behavior

`nx serve` on 

```  "executor": "@angular-devkit/build-angular:dev-server",```
stopped working for my project.

I builds everything, starts the server, then just exits to the command prompt (stopping the server in the process)

ie
```
...
account-login.component-T2RFKWNK.js                      | account-login-component                      | 490 bytes | 
cms-landing-page.component-YXTFTGJM.js                   | cms-landing-page-component                   | 467 bytes | 
marketingspot-preview-report.component-PY534WAD.js       | marketingspot-preview-report-component       | 353 bytes | 
marketingspot-preview-search-score.component-SL47OTTN.js | marketingspot-preview-search-score-component | 339 bytes | 

Application bundle generation complete. [12.007 seconds]
Watch mode enabled. Watching for file changes...
  ➜  Local:   https://localhost:4200/
  ➜  press h + enter to show help

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target serve for project XXXX


asger@S-L92NW3MYXM XXXX-frontend % 
```

### Expected Behavior

after `nx serve` it should not exit, and should leave server up, ready to take requests.

### Steps to Reproduce

Unclear. 
It happened to two people on our team at various  times.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.20.2
   OS     : darwin-arm64
   npm    : 10.5.0
   
   nx                 : 17.3.2
   @nx/js             : 17.3.2
   @nx/jest           : 17.3.2
   @nx/linter         : 17.3.2
   @nx/eslint         : 17.3.2
   @nx/workspace      : 17.3.2
   @nx/angular        : 17.3.2
   @nx/cypress        : 17.3.2
   @nx/devkit         : 17.3.2
   @nx/eslint-plugin  : 17.3.2
   @nrwl/tao          : 17.3.2
   @nx/web            : 17.3.2
   @nx/webpack        : 17.3.2
   typescript         : 5.3.3
```

### Failure Logs

```shell
Unclear
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

have nx-cloud enabled
have tried --skip-nx-cache
have tried deleting .angular .nx and node-modules
have tried clean checkout
have tried --verbose, no info is given.

**Comment by asgerjensen** [comment]
Update: on a whim, i removed the cloudAccessToken from my nx.json, and that solved the issue...

i wonder what motivated this change in behavior, as i've had that token set for months

**Comment by Coly010** [comment]
Hey :) Could you try migrating to Nx 18 (`npx nx migrate latest && npx nx migrate --run-migrations`) and then place your cloudAccessToken back in your nx.json and see if you still encounter the issue?

**Comment by asgerjensen** [comment]
sure, will do and report back

**Comment by asgerjensen** [comment]
Upgrading nx as mentioned, solved the issue. 
 
While it may then be academic, i still dont get if this was a problem on my end, or with nxcloud.
 
Anywys, solution seems to be to upgrade or disable nxclouds readonly token.

**Comment by AgentEnder** [comment]
Closing this out as fixed in latest
