### ISSUE TITLE
create-nx-workspace strips version from preset option

### ISSUE THREAD

**Issue by zachlewton** [nrwl/nx#23174]
### Current Behavior

right now `npx create-nx-workspace my-workspace --preset=@org/package@1.1.1` does not respect the version and defaults to latest

### Expected Behavior

this command would respect the version passed to it

### Steps to Reproduce

This is just an example that mirrors my situation:
(have go installed locally)
1. run `npx create-nx-workspace go-workspace --preset=@nx-go/nx-go@2.7.0`
2. `cd go-workspace`
3. run `nx report `

you will see it installed the latest nx-go rather than the version you specified 
https://github.com/nx-go/nx-go/releases

### Nx Report

```shell
Node   : 18.18.2
OS     : darwin-arm64
npm    : 9.8.1

nx             : 18.3.4
@nx/workspace  : 18.3.4
@nx/devkit     : 18.3.4
@nrwl/tao      : 18.3.4
---------------------------------------
Registered Plugins:
@nx-go/nx-go
---------------------------------------
Community plugins:
@nx-go/nx-go : 3.0.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
i submit a pr https://github.com/nrwl/nx/issues/23174 to install the specified version for 3rd party lpreset. however, for @nx-go/nx-go@2.7.0, it does not have preset generator for this version. i think the preset generator for @nx-go/nx-go is added for 3.0.0

**Comment by zachlewton** [comment]
yeah sorry i was just using that as an example but probably should have picked one with valid generator . didnt realize that was the case , my bad!
