### ISSUE TITLE
@swc/core peer dependency warnings on fresh Nx 18.3.4 setup for angular/esbuild (windows)

### ISSUE THREAD

**Issue by ErickRodrCodes** [nrwl/nx#23176]
### Current Behavior

It could be annoying, but not critical. While you install a package you end up with this:

![image](https://github.com/nrwl/nx/assets/1978642/f8739d5b-2165-49ae-b8b9-c012cabfbb70)

### Expected Behavior

it should not run warnings on any npm install

Solution is quite simple: change the dependency to be **@swc/core@^1.4.13**

after that warnings are gone:

![image](https://github.com/nrwl/nx/assets/1978642/f3a42909-a174-4dfd-8b5d-5504f60774f5)

### Steps to Reproduce

1. npx create-nx-workspace@latest
2. setup an Angular monorepo with esbuild, and playwright
3. enter in your workspace, remove node_modules, run `npm i`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.10.0
OS     : win32-x64
npm    : 10.2.3

nx (global)        : 18.0.4
nx                 : 18.3.4
@nx/js             : 18.3.4
@nx/jest           : 18.3.4
@nx/linter         : 18.3.4
@nx/eslint         : 18.3.4
@nx/workspace      : 18.3.4
@nx/angular        : 18.3.4
@nx/devkit         : 18.3.4
@nx/eslint-plugin  : 18.3.4
@nx/playwright     : 18.3.4
@nrwl/tao          : 18.3.4
@nx/web            : 18.3.4
@nx/webpack        : 18.3.4
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/eslint/plugin
```

### Package Manager Version

npm 10.2.3

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Thank you for bringing this issue to our attention! I want to assure you that I will take a look as soon as I can. Your patience and understanding in this matter is greatly appreciated.

**Comment by Coly010** [comment]
Fixed in latest 🙂 
<img width="985" alt="image" src="https://github.com/nrwl/nx/assets/12140467/1d463095-cbba-41e2-abb1-bb9c667b524c">
