### ISSUE TITLE
Supported Nx versions

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#23220]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

No.

### Additional context or description

As plugins maintainers we need to update our plugins to work with newer Nx versions... Now that Nx 19 is released i want to now which version of Nx will be actively maintained, would be great to include in the docs which versions are supported, abandoned or in maintenance mode... With that information plugins maintainers can take decisions about remove support for older versions of nx if is needed

**Comment by FrozenPandaz** [comment]
We will support the last year of major versions with security and core functionality patches.

In May 2023, we were working on Nx 16, so the current supported versions as of May 2024 are:

* Nx 19
* Nx 18
* Nx 17
* Nx 16

Generally, it would be the current version + 2 prior versions. Nx 18 was a special version without breaking changes so right now it's at 4 versions. 

We will follow up with an official docs page.

**Comment by jaysoo** [comment]
@gperdomor https://nx.dev/reference/releases
