### ISSUE TITLE
Nx without ngrx? Using Apollo.

### ISSUE THREAD

**Issue by jeremyputeaux** [nrwl/nx#233]
I have this app I made that uses Apollo.
Since I need to make another app I thought of Nx and installed everything.

But now I discover that Apollo and ngrx are not working well together.
Since I have to use Apollo and I don't really need ngrx (even if I really like effects and the simplicity of store), **I'm wondering if there is a way to use Nx without ngrx?**

**Comment by jeremyputeaux** [comment]
Actually @kamilkisiela just released https://github.com/apollographql/apollo-angular/tree/1.0-ngrx/packages/apollo-angular-cache-ngrx and so far, so good.
Let's close this one.

**Comment by val-samonte** [comment]
@jeremyputeaux starting apollo 2, you can actually use apollo all the way and skip using ngrx. https://github.com/apollographql/apollo-link-state

**Comment by akshath4u** [comment]
Hi, I am using apollo angular with ngrx and using ngrx effects for graphql queries. is this the right approach?

**Comment by vsavkin** [comment]
If you want to use Nx only for of its implementation of workspace/monorepo, you can create a new project and then remove the following dependencies from package.json:

```
"@nrwl/nx"
"@ngrx/effects"
"@ngrx/router-store"
"@ngrx/store"
"@ngrx/store-devtools"
```

We were talking about having an NgRx-less version of Nx, but decided to delay it until later.
