### ISSUE TITLE
Nx+Vitest ignores root vitest.config.ts

### ISSUE THREAD

**Issue by Lonli-Lokli** [nrwl/nx#23303]
### Current Behavior

Any settings specified in root vitest.config.ts are ignored

### Expected Behavior

Settings from root vitest.config.ts should be applied

### Steps to Reproduce

1) Create any Nx + Vitest repo
2) Remove existing test
3) Add root vitest.config.ts with 
```ts
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    passWithNotTests: true
  }
})
```
4. Run npx nx proj:test

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 18.18.2
OS     : win32-x64
npm    : 9.8.1

nx                 : 19.0.2
@nx/js             : 19.0.2
@nx/linter         : 19.0.2
@nx/eslint         : 19.0.2
@nx/workspace      : 19.0.2
@nx/devkit         : 19.0.2
@nx/eslint-plugin  : 19.0.2
@nx/react          : 19.0.2
@nrwl/tao          : 19.0.2
@nx/vite           : 19.0.2
@nx/web            : 19.0.2
typescript         : 5.4.5
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Hey, can you provide a repro so we can investigate, this is working as expected on my end.

**Comment by Lonli-Lokli** [comment]
@ndcunningham Here is it https://github.com/Lonli-Lokli/issues-nrwl-nx-23303

**Comment by Lonli-Lokli** [comment]
It's not stale!
@AgentEnder

**Comment by Lonli-Lokli** [comment]
It's active but ignored

**Comment by Lonli-Lokli** [comment]
@ndcunningham could you reproduce the issue?

**Comment by Lonli-Lokli** [comment]
Not stale

**Comment by Lonli-Lokli** [comment]
Reproduction provided, not stalw

**Comment by Coly010** [comment]
I don't see the issue?

If I run `npx vitest` in `apps/nx-vitest`, it fails on no test files found. Vitest itself is not finding your root config file.

If you look at the `test` target for your app (via `nx show project nx-vitest`) you'll see the cwd is set to `apps/nx-vitest`.

What you _can_ do is run `nx test` which will pick up your root `vitest.workspace.ts` file, which in turn finds your root `vitest.config.ts` file.

Everything here is working as expected.

**Comment by Lonli-Lokli** [comment]
@Coly010 That's actually a continuation of my previous issue https://github.com/nrwl/nx/issues/22139#issuecomment-2031864054

What I want is to have an ability to setup something global for tests, and to allow Nx+Vitest pick up this workspace file, which does not happen. 

What I do not want is to specify passWithNoTst or any global options like coverage reporters in each {project}/vitest.config.ts

**Comment by Coly010** [comment]
In that case it would be better to create a feature request over on the discussions: https://github.com/nrwl/nx/discussions/new?category=feature-requests
