### ISSUE TITLE
Distributed task execution only works for cacheable targets

### ISSUE THREAD

**Issue by shahraship** [nrwl/nx#23308]
### Current Behavior

monorepo> nx serve shell --verbose
[NX CLOUD] Verifying current cloud bundle
[NX CLOUD] A local bundle currently exists:  {
  version: '2405.02.15.hotfix3',
  fullPath: '/Users/dev/Developer/monorepo/.nx/cache/cloud/2405.02.15.hotfix3'
}
[NX CLOUD] Last verification was within the past 30 minutes, will not verify this time
[NX CLOUD] Done:  /Users/dev/Developer/monorepo/.nx/cache/cloud/2405.02.15.hotfix3

 NX   Distributed task execution only works for cacheable targets

Target 'shell:serve' cannot be executed.
To be able to replay the output of the target, distributed task execution only supports cacheable targets.
You can verify that 'serve' is part of the list of cacheable targets in the 'nx.json' file.
You can invoke this command without distribution by doing "NX_CLOUD_DISTRIBUTED_EXECUTION=false nx ...".

### Expected Behavior

Be able to serve apps locally.

### Steps to Reproduce

This seems very specific to my local environment. I tried re-cloning the repo and re-installing NX as well.

### Nx Report

```shell
monorepo> nx report

 NX   Report complete - copy this into the issue template

Node   : 20.11.1
OS     : darwin-arm64
npm    : 10.2.4

nx (global)        : 18.1.2
nx                 : 18.1.2
@nx/js             : 18.1.2
@nx/jest           : 18.1.2
@nx/linter         : 18.1.2
@nx/eslint         : 18.1.2
@nx/workspace      : 18.1.2
@nx/angular        : 18.1.2
@nx/cypress        : 18.1.2
@nx/devkit         : 18.1.2
@nx/eslint-plugin  : 18.1.2
@nx/express        : 18.1.2
@nx/node           : 18.1.2
@nx/plugin         : 18.1.2
@nx/react          : 18.1.2
@nx/storybook      : 18.1.2
@nrwl/tao          : 18.1.2
@nx/web            : 18.1.2
@nx/webpack        : 18.1.2
typescript         : 5.3.3
---------------------------------------
Community plugins:
@compodoc/compodoc : 1.1.23
@storybook/angular : 7.6.17
@twittwer/compodoc : 1.12.0
apollo-angular     : 4.1.1
ng-mocks           : 14.12.1
ngx-pendo          : 1.14.3
nx-stylelint       : 17.0.1
---------------------------------------
Local workspace plugins:
         @myorg/generators
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by StalkAltan** [comment]
Hi, you probably ran `npx nx-cloud start-ci-run` locally. This should have prompted you with a warning that it isn't needed locally. This is because running the command puts a marker file on your machine that tells all future commands to run with DTE enabled, as you are currently experiencing.

To remove this, you can run `npx nx-cloud cleanup`.
