### ISSUE TITLE
TypeError in nx:run-commands with `env` option

### ISSUE THREAD

**Issue by romainwg** [nrwl/nx#23325]
### Current Behavior

When executing a custom nx run-command target in nx.json to run a script, specifying environment variables using the "env" option, the command fails with a TypeError: Cannot convert undefined or null to object. This occurs despite following the official documentation for passing environment variables to commands.

For example:

`npx nx run default-hmi:docker-build-test`

```json
"docker-build-test": {
    "executor": "nx:run-commands",
    "options": {
      "command": "./scripts/docker-manager.sh build",
      "cwd": ".",
      "env": { "FOO": "BAR" }
    }
  }
```

### Expected Behavior

The expected behavior is that the environment variable specified in the "env" option of the nx:run-commands executor should be correctly passed to the command being executed, allowing for successful execution of the script with the provided environment variables. No TypeErrors should occur when using documented features as expected.

The documentation indicates that you can use env or envFile; in fact, envFile works just as well as envFile.
See: <https://nx.dev/nx-api/nx/executors/run-commands#env>

`env` is set as object on the json schema:
<https://github.com/nrwl/nx/blob/53693fdd1cb6c3becbfe47ef6ad393d0e20ecc3c/packages/nx/src/executors/run-commands/schema.json#L128>

### GitHub Repo

There is no problem on nx 19.0.0-beta (nx-examples):
<https://github.com/romainwg/nx-examples-env-issue/commit/4b1d05af916e6605616a6ff721ddd50b20cc6e97>

But does not work on nx 18.1.3:
<https://github.com/romainwg/nx-examples-env-issue/commit/c45334ab075ba974ce9fadbd83c6403dac135eda>

### Steps to Reproduce

1. Define a custom target in `nx.json` using `nx:run-commands` that executes a shell script and uses the `env` option to specify environment variables.
2. Run the custom target using the Nx CLI command `npx nx run <project>:<target>`.
3. Observe the `TypeError: Cannot convert undefined or null to object` error being thrown during execution.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 21.6.2
OS     : linux-x64
npm    : 10.2.4

nx                 : 18.1.3
@nx/js             : 18.1.3
@nx/jest           : 18.1.3
@nx/linter         : 18.1.3
@nx/eslint         : 18.1.3
@nx/workspace      : 18.1.3
@nx/cypress        : 18.1.3
@nx/devkit         : 18.1.3
@nx/eslint-plugin  : 18.1.3
@nx/node           : 18.1.3
@nx/plugin         : 18.1.3
@nx/react          : 18.1.3
@nx/storybook      : 18.1.3
@nrwl/tao          : 18.1.3
@nx/vite           : 18.1.3
@nx/web            : 18.1.3
typescript         : 5.3.3
---------------------------------------
Community plugins:
@webpro/nx-tsc : 0.0.1
---------------------------------------
Local workspace plugins:
         @hmi/plugin-check-unpinned-dependencies
         @hmi/plugin-check-envs-sync
```

### Failure Logs

```shell
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    (Additional stack trace information corresponding to the error encountered)
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
it is fixed in pr https://github.com/nrwl/nx/pull/22426 which is available after 18.2
