### ISSUE TITLE
Feature request: implement workspace builder with TypeScript

### ISSUE THREAD

**Issue by elliottsj** [nrwl/nx#2336]
## Expected Behavior

Able to write a workspace builder in TypeScript.

## Current Behavior

It's only possible to implement a workspace builder in plain JavaScript.

### Context

I've watched the [Nx Playbook lecture on custom builders](https://nxplaybook.com/courses/701247/lectures/12570377), which is a great resource. However I've noticed that we can only write the builder in plain JS currently. I'd love if these can be written in TypeScript.

**Comment by FrozenPandaz** [comment]
Closing in favor of https://github.com/nrwl/nx/issues/2211
