### ISSUE TITLE
allow eslint cache

### ISSUE THREAD

**Issue by zodiac1214** [nrwl/nx#2337]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

## Expected Behavior

eslint cache could be enabled

## Current Behavior

no way to enable eslint cache

## Other

Allow eslint --cache in configuration/cli

**Comment by jaysoo** [comment]
Good idea!

**Comment by rarmatei** [comment]
I can have a look at this 👍

**Comment by rarmatei** [comment]
This requires a change to `@angular-eslint/builder` package: https://github.com/angular-eslint/angular-eslint/pull/35

**Comment by Hotell** [comment]
or nx It might make sense to build/maintain  own nx version builder for eslint as we discussed with @jaysoo

**Comment by zodiac1214** [comment]
One thing i also want to point out is that `nx affected:lint` does not make sense at all right now. Lint should only happen to files that are changed. Not projects that has dependencies on.

**Comment by rarmatei** [comment]
@zodiac1214 I agree, linting won't break on a file when only its dependencies have changed. Hopefully eslint caching will land in `9.1`

**Comment by zodiac1214** [comment]
I haven't checked this for a long time. It looks like we have it released! i just tried that. it reduce lint time from 40s to 10s in one of my project. @rarmatei close this ticket now
