### ISSUE TITLE
[Feature Request] affected:apps --exclude

### ISSUE THREAD

**Issue by dereklin** [nrwl/nx#234]
Sometimes we might have apps we never want to build; for example, we don't want to build an angular-playground app.  So it will be nice to have the --exclude flag as a filter.

**Comment by vsavkin** [comment]
Fixed here:https://github.com/nrwl/nx/commit/7c330163bdcb0ca4b699995813abd90394bcc6b8

**Comment by arvindnama** [comment]
does exclude work with `--with-deps` ?

I am trying to run 

`nx test --with-deps --project=app-name --exclude=lib2,lib3`

but I don't see it working .. 
I am on v12.0.6
