### ISSUE TITLE
Svgs crash the app

### ISSUE THREAD

**Issue by evgenyshenets91** [nrwl/nx#23468]
### Current Behavior

After upgrading from 18nx to 19 in React project I have this issue: 
Failed to execute 'createElement' on 'Document': The tag name provided ('http://localhost:4200/fintiba-logo.939a27c492f3b4a984045f1df5584f2b.svg') is not a valid name.

I checked if replace it with `import { ReactComponent as Logo } from './logo.svg';` it works, But I don't want to change it everywhere.

### Expected Behavior

After upgrading to latest NX version expect imports work as before.

### Steps to Reproduce

1. migrate from nx 18 to 19. 
2. used import in 18nx as import Logo from '../../../assets/svg/fintiba-logo.svg';

### Nx Report

```shell
Node   : 20.3.1
OS     : darwin-arm64
npm    : 9.6.7

nx                 : 19.0.4
@nx/js             : 19.0.4
@nx/jest           : 19.0.4
@nx/linter         : 19.0.4
@nx/eslint         : 19.0.4
@nx/workspace      : 19.0.4
@nx/cypress        : 19.0.4
@nx/devkit         : 19.0.4
@nx/eslint-plugin  : 19.0.4
@nx/expo           : 19.0.4
@nx/node           : 19.0.4
@nx/react          : 19.0.4
@nrwl/tao          : 19.0.4
@nx/web            : 19.0.4
@nx/webpack        : 19.0.4
typescript         : 5.3.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Can you show your webpack config?
