### ISSUE TITLE
(react) TS2591: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.

### ISSUE THREAD

**Issue by czaplej** [nrwl/nx#2355]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Failure Information (for bugs)
I'm getting  this error: TS2591: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.

I had types "node" in tsconfig intalled package etc.

**Comment by jaysoo** [comment]
Do you have a repo we can check? Make sure your `typeRoots` includes the same folder that `@types/node` is installed in.

**Comment by KrzysztofCzaplejewicz** [comment]
@jaysoo project was generated by CLI so main tsconfig has 
![image](https://user-images.githubusercontent.com/29889157/72899166-bb14ac80-3d25-11ea-939d-ed9bcc33be0d.png)
where is project structure is: 
![image](https://user-images.githubusercontent.com/29889157/72899232-d7b0e480-3d25-11ea-9f1f-024968182ffd.png)
and in apps folder there is web (react app)

**Comment by jaysoo** [comment]
@czaplej Sorry for the late reply. It might have been a bad config in a previous version. Can you try updating to the latest Nx 9 release?

```nx migrate @nrwl/workspace@9.1.0```

I just checked it require is working. I tested by using it for `styled-components`:

```
// eslint-disable-next-line @typescript-eslint/no-var-requires
const styled = require('styled-components').default;
```

Lastly, can you double-check your `tsconfig.json` in your apps and libs? They should include this compiler option:

```
{
  ...
  "compilerOptions": {
    ...
    "types": ["node", "jest"]
  }
}
```

**Comment by jaysoo** [comment]
Closing this for now, but feel free to re-open if you continue to have issues.

**Comment by yeomann** [comment]
![image](https://user-images.githubusercontent.com/5970751/104828078-2f692980-586e-11eb-99e4-e0e5b4589a9c.png)

This is a fresh project and getting this error

**Comment by codeninja** [comment]
Hey just in case anyone needs to solve this in the future:

Make sure you update the `tsconfig.lib.json` as well as the `tsconfig.json` inside the lib.

The `tsconfig.lib.json` in my project had an empty `"types":[]` which was overwriting the `tsconfig.json`'s types declaration!
