### ISSUE TITLE
(react) Can't install own version of rxjs

### ISSUE THREAD

**Issue by czaplej** [nrwl/nx#2357]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Failure Information (for bugs)

I put rxjs in version 6.5.4 in package.json but still i have error about "Type source is not assignable to type source "

Is it possible to install own version of rxjs or @nrwl/react depended on it

**Comment by jaysoo** [comment]
It should be possible. We'll look into it.

**Comment by BigAB** [comment]
I've discovered a possibly related issue:

## Reproduction Steps

1. create new nx react workspace
2. install `rxjs@next` (currently 7.0.0-beta.0)
3. use a v7 feature such as `lastValueFrom`

```jsx
import React, { useEffect, useState } from 'react';
import { of, lastValueFrom } from 'rxjs';
import { delay } from 'rxjs/operators';
import './app.css';

const stuff$ = of([
  {
    id: 1,
    name: 'My baseball',
  },
  {
    id: 2,
    name: 'My glove',
  },
  {
    id: 3,
    name: 'My bat',
  },
]).pipe(delay(3000));

export const App = () => {
  const [stuff = [], setStuff] = useState();

  useEffect(() => {
    console.log(lastValueFrom);
    (async () => {
      const val = await lastValueFrom(stuff$);
      setStuff(val);
    })();
  }, []);

  return (
    <div className="app">
      <ul>
        {stuff.map(({ id, name }) => (
          <li key={id}>{name}</li>
        ))}
      </ul>
    </div>
  );
};

export default App;
``` 

## Result 
The code will fail at run time, with `lastValueFrom` being `undefined`.

The exact same code will work on a fresh Create-React-App installation.

**Comment by BigAB** [comment]
the **2b** solution from https://github.com/nrwl/nx/issues/2458 does solve my issue above
