### ISSUE TITLE
[Feature Request]  Add support to restrict workers and memory in dev server

### ISSUE THREAD

**Issue by raheelriax** [nrwl/nx#2366]
## Expected Behaviour

` Nx serve <app-name> --maxWorkers=1 --memoryLimit=1028 `
command should allow restricting workers and memory limit.

## Current Behaviour
passed arguments doesn't have any effect

### Steps to Reproduce

Just start any dev server for your application node or react application and try to pass the above arguments to restrict

1. maxWorkers
2. MemoryLimit

### Context

I am using Nx to develop full stack applications (React + Apollo) I've multiple applications and libraries inside my mono repository. During development process a developer needs to run at-least 2 parallel instances of dev servers. One for the Frontend (React) and the other one for the Node JS (Apollo). These dev server instances often takes too much of the system' ram that other task's get compromised.
We need to have some kind of options to restrict the memory & service workers we allocate to dev server instances for effective memory usage.

*Output of nx report*

 @nrwl/angular : Not Found
  @nrwl/cli : 8.11.2
  @nrwl/cypress : 8.11.2
  @nrwl/eslint-plugin-nx : 8.11.2
  @nrwl/express : 8.11.2
  @nrwl/jest : 8.11.2
  @nrwl/linter : 8.11.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 8.11.2
  @nrwl/react : 8.11.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.11.2
  @nrwl/web : 8.11.2
  @nrwl/workspace : 8.11.2
  typescript : 3.5.3

.

**Comment by raheelriax** [comment]
Thanks a lot ☺️

**Comment by youngchon** [comment]
Does the fix affect  `nx run` too?
