### ISSUE TITLE
Nest e2e 

### ISSUE THREAD

**Issue by SOHELAHMED7** [nrwl/nx#2368]
Kind: feature/docs request

In Angular we can create entirely new and separate app to e2e test it using Cypress.

Similarly, kindly add feature and/or docs to do same with API made using NestJS

NestJS [recommends](https://docs.nestjs.com/fundamentals/testing#end-to-end-testing) [supertest](https://github.com/visionmedia/supertest), however [Cypress](https://www.cypress.io/blog/2017/11/07/add-gui-to-your-e2e-api-tests/) can also be used.

**Comment by vsavkin** [comment]
I believe this is a duplicate: https://github.com/nrwl/nx/issues/1098
