### ISSUE TITLE
[Q] watching files

### ISSUE THREAD

**Issue by KrzysztofCzaplejewicz** [nrwl/nx#2369]
## Other

I can't find information about watching files changes. How it works? If i have few libraries and i make changes, would it rebuild whole solution or only depended libs? If not, It would be great feature to create. Now i have ~15 libs and make small changes and it's take a bit too long in my opinion. I have kinda good laptop 32gb RAM, i7 and 512 gb SSD disc. No circular dependency in project.

**Comment by filippomuscolino** [comment]
@czaplej how did you managed this?
