### ISSUE TITLE
[feature] Nest library schematic

### ISSUE THREAD

**Issue by Sikora00** [nrwl/nx#2378]
It would be great to have a schematic like @nrwl/angular-library also for nest.

**Comment by Sikora00** [comment]
@vsavkin Could you assign this issue to me?

**Comment by Sikora00** [comment]
I sent a pull request, but I'm wondering if it would be better not to use @nestjs/schematics:library and copy its functionality to @nrwl/nest:library.

**Comment by juristr** [comment]
@Sikora00 Hey, thanks a lot for your PR. We’ll be looking into it as soon as we can and give you feedback :) Just give us a bit of buffer as we’re currently streamlining our latest release & then we’ll continue with new features :)
