### ISSUE TITLE
[Discussion] Who is using Nx in production?

### ISSUE THREAD

**Issue by vsavkin** [nrwl/nx#2379]
Nx has been growing fast (5x in 2019). A lot of companies use Nx today, some of them are listed here: https://nx.dev

If you are using Nx, and you don't mind sharing this fact with the world, please post your company name with a link in the comment below. We appreciate it a lot.

**Comment by BuckyMaler** [comment]
The development group I'm a part of at [National Oilwell Varco](https://www.nov.com/) has been using Nx for almost a year. We're loving it! Earlier this month we updated to version 8, and are excited about Storybook and the recent caching work. I work on a front-end tooling and infrastructure team with @ZachJW34. We've contributed a few times to the Nx project and look forward to contributing more. Thank you team Nrwl for all your hard work! 👍

**Comment by Sikora00** [comment]
At @valueadd-poland Nx is an important part of our tech stack for over a year and we use it with joy. We deployed a lot of software to production with support from tools from nrwl. We are looking forward to taking advantage of the latest nx features like support for the story book and we are waiting for new, awesome tools in the feature.

**Comment by wickstargazer** [comment]
Hi we are using nx in production, our site is [FlowAccount.com](https://flowaccount.com)
Its been some good few months we are dwelling into Nx worskspace. Its a pretty seamless development experience!

And we have wrote our own schematic to work with Nx as well ... its an implementation of serverless node typescript, using nx/angular-cli to generate/serve offline and deploy to aws cloud. 

[@flowaccount/nx-serverless](https://www.npmjs.com/package/@flowaccount/nx-serverless)

The fun part of it is being to work on a full-stack app within one workspace. I have also added tree-shaking for the node_modules and its working well.

We are also adding enhancements and features to it, to help integrate our development workflow and CI/CD pipeline :)

Thankz for a great open-source product!

**Comment by tashoecraft** [comment]
At icims we use Nx to power our Attract product line of career sites: https://www.icims.com/talent-acquisition-software/career-site-solutions/. We power the sites of some of the largest companies, Pepsico, Fedex, Johnson & Johnson, Mcdonalds. Nx serves primarily the searching and applying for jobs portion, applicant data management applications, internal apps, etc. 

It's been very helpful in reusing code quickly without having to deploy to a hosted npm, version tag, and redeploy when changes come down the line. 

Very excited about the future of NX as we pull more applications into the repo.

**Comment by alfaproject** [comment]
We've recently started a company (actually, been almost a year, dayum...) to make a casino platform. I'm pretty sure we are the first ones in the world to have made a 100% serverless casino platform and it would have been very difficult without `nx`, so thank you guys for this amazing tool. I'm just sad I didn't time to contribute to open source projects this past year, because you know... busy.

We are called The Mill Adventure, https://www.themill.io/

**Comment by LayZeeDK** [comment]
Systemate A/S
https://www.systemate.dk/

**Comment by Carniatto** [comment]
We are very glad to use it at Riaktr for most of our apps and services. It's has been a ride change for us.
https://www.riaktr.com/

**Comment by dsebastien** [comment]
For Didowi, our upcoming product, we're using Nx as the glue between all the parts of the overall system.

We combine Nx, Angular, NestJS and Kubernetes (also during development) among other things :)

Really glad so far!

**Comment by klaascuvelier** [comment]
We're using it as well at Showpad:
https://www.showpad.com

**Comment by klauvi** [comment]
Sensa
https://sensa.is/

**Comment by yannickglt** [comment]
We use it at Elium https://elium.io

**Comment by stefan-karlsson** [comment]
We use it at MatHem https://mathem.se

**Comment by pf1gura** [comment]
We love it at [Placester](https://placester.com). We started using it about half a year ago as a replacement for `lerna`. The transition was smooth and it enabled us to do so much great stuff without worrying about initial setup. It just works!

**Comment by lithqube** [comment]
I'm really happy that I introduce NX to Zertificon Solutions GmbH - zertificon.com ☺️

**Comment by hotpixelgroup** [comment]
We use it at [Hot Pixel Group](http://www.hotpixelgroup.com). You guys are doing great work!

**Comment by osc707** [comment]
We do at my department @ Adobe. I was hired to architect our AdTech DSP (originally in PHP & angularJS) to Angular (Nx, Ngrx). We have built a few stand alone features over the last 18 months. The last 6 months we are finally doing a platform rebuild with a configuration driven Angular UI leveraging dynamic component generation. [Adobe AdCloud](https://www.tubemogul.com/)

**Comment by demisx** [comment]
## ❤️
@ DimasList.org - https://dimaslist.org

**Comment by dhondiramjawade** [comment]
We are using Nx for our Enterprise Application. It's great tool with well defined architecture for large scale applications with many useful feature like storybook, dependency graph and many more. Looking forward to hear from you guys about Bazel official support.

**Comment by ball6847** [comment]
At [7peaks software](https://7peakssoftware.com/), We develop many enterprise software for our clients in Thailand. We started using NX for almost 2 years now (since nx v0.7) and we still love it. 
We always happy to recommend NX to Angular Community in Thailand.

Thanks for creating NX.

**Comment by tonmanna** [comment]
We have just begun looking into NX at [ITOPPLUS](url=http://www.itopplus.com). Before we try it on production, we have a lot of questions on how NX can solve our issues. After researching and meeting people that know NX well. After our research, we have no doubts anymore. We're ready to adopt NX on our next production project.

**Comment by antoinepairet** [comment]
[Medispring](https://app.medispring.be/) is an EHR from Belgium used by more than 1200 doctors everyday

**Comment by oschlegel** [comment]
We are one of several teams working for [MyPorsche](https://connect-portal.porsche.com/) and we are using nx to maintain our frontend code

**Comment by dopsonbr** [comment]
We use it at [HomeDepot](https://www.homedepot.com/). It is used for a couple of critical internal apps and not the public e-commerce site. I am hoping to do a full write up about our stack and the migration of a massive 1.7x AngularJs app, when I get some free time.

**Comment by dsln** [comment]
We use it at [SOTI Inc. ](https://www.soti.net/)  in Ontario as part of our shared component library across our suite of products.

**Comment by vmasek** [comment]
We at [FlowUp](https://flowup.cz/en/tech-stack) are using Nx in production alongside with Ionic, Angular and GraphQL to develop multiple "news" related applications and websites (with universal SSR) as part of the news platform for (unnamed) digital network

**Comment by matthewjh** [comment]
We are very happily using it at Tradeweb in our UI monorepo.

https://www.tradeweb.com/

**Comment by charsleysa** [comment]
Kintal Apps Ltd has been using nrwl nx for about 1.5 years for the main product MyMahi https://mymahi.co.nz

**Comment by rexebin** [comment]
Encial Group Ltd. We have been using Nx for our trading and management system since begining.

**Comment by jerryorta-dev** [comment]
Spout is using it for a music app that is angular front-end inside of electron and firebase.

**Comment by yharaskrik** [comment]
trellis.org is! We have been using Nx for quite a while now! We love it so much a few of us (@Doginal) in the company have contributed to the repo itself and have started a community run Slack workspace for Nx users called [@nrwl/community](https://join.slack.com/t/nrwlcommunity/shared_invite/enQtNzU5MTE4OTQwOTk0LTgxY2E0ZWYzMWE0YzA5ZDA2MWM1NDVhNmI2ZWMyYmZhNWJiODk3MjkxZjY3MzU5ZjRmM2NmNWU1OTgyZmE4Mzc)! We just requested access to the Nx Cloud and are so excited about everything Nx is doing. I couldn't imagine building our company without it, I personally will be using Nx for any project I ever work on.

**Comment by dogmatico** [comment]
We have consolidated some client web applications, 7 at the moment, into a Nx mono-repo at http://bmat.com.

We are happy with the result: having to not manage artifacts and source synchronization has been very satisfying. The only issue, minor because we are a small team, is with commits updating `angular.json` and `nx.json`: I think that modularizing those files can be a really big win and prevent merge conflicts.

**Comment by atifsyedali** [comment]
We have been using Nx for ourselves and for another client on a fairly large project. 

Though, we have had to add custom builders, for example, to: (a) a node/web builder to generate a package.json from the dependency graph for each app in the dist folder, (b) a web builder that ports over create-react-app configurations and modifies it for SSR+client, (c) enable distributed caching on redis. We are managing these changes in our own mono-repo that uses Nx to build Nx builders: https://github.com/apployees/apployees-nx

**Comment by myspivey** [comment]
[Shutterstock](https://www.shutterstock.com) is in the process of integrating this to manage our e-commerce code.

**Comment by annsk** [comment]
We use it in our system. 

IC COMPLEX
https://iccomplex.eu

**Comment by LukeHowellDev** [comment]
[Suzy](https://suzy.com/) recently migrated our [Crowdtap](https://crowdtap.com/) application to an NX workspace. It is still just the one application in the workspace as a first step. We recently added our first library and are working on plans to refactor the application into appropriate libraries. Alongside that, we will be pulling in and refactoring our other frontend applications. We are really looking forward to being able to take full advantage of the tooling provided with NX.

**Comment by lukasholzer** [comment]
We @Dynatrace https://www.dynatrace.com/ are heavily depending on you folks! 

You are doing amazing work and help us to focus on our business use cases!

**Comment by alexanderPastornicky** [comment]
[Solar Turbines](https://www.solarturbines.com/) - A Caterpillar Company. Thanks guys!

**Comment by hoang-innomizetech** [comment]
We are an offshoring/outsourcing company based in Vietnam. We have been using this tool for at least 3 projects. The current project we are working on is a big cloud-based SaaS product with Angular, NestJS, Serverless, AWS services.

InnomizeTech https://www.innomizetech.com/

**Comment by GaramNick** [comment]
We at [Oper Credits](https://www.opercredits.com/) have recently transferred our apps to Nx.

Thank you for your hard work & dedication!

**Comment by EvtK** [comment]
We are using it at [Achmea](www.achmea.nl), the largest insurance company in the Netherlands. I'm a front-end lead developer, working for one the labels of Achmea: [CentraalBeheer](www.centraalbeheer.nl). At CentraalBeheer, we use NX in our mono repo for all our client-side (and Sitecore) front-end development.

**Comment by bellindj** [comment]
We use it at [84.51°](https://www.8451.com/) on our largest Angular application. NX helped us scale from 1 to 6 teams with 30 active contributors. We also have an NX repo for our Design System (which has a React lib, Angular lib, StencilJS lib, React app and Angular app all under one NX repo!).

**Comment by josecolella** [comment]
We use it at Dynatrace for our Digital business applications. NX has helped us reduce the complexity of sharing higher level libraries between different applications, and making the developer workflow easier with all teams working from the same repository while leveraging modularity, and a libs first approach

**Comment by lukasholzer** [comment]
> We @Dynatrace https://www.dynatrace.com/ are heavily depending on you folks!
> 
> You are doing amazing work and help us to focus on our business use cases!

@josecolella  :D

**Comment by Adrael** [comment]
We @betclicgroup are also relying on you. Thanks!
[https://betclic.com](https://betclic.com)

**Comment by rafa-as** [comment]
We at @carnovo https://carnovo.com/es use it and we are very grateful for your great work.

Thanks!

**Comment by plambhsa** [comment]
We're using it for a couple applications at MotivHealth! It's been great!

**Comment by kylecordes** [comment]
We use Nx to manage a big pile of example apps for our Angular training:

https://angularbootcamp.com/

... and also for various complex projects for our customers at:

https://oasisdigital.com/

**Comment by rinckd** [comment]
We use it at Daupler for a variety of apps. Monorepos for the win! [https://daupler.com](https://daupler.com)

**Comment by JustinHoldstock** [comment]
We're currently migrating away from micro-frontends over at [Vendasta](https://www.vendasta.com/) in favour of a monorepo.  Our first few projects are internal apps, and our [new Frontend Framework](https://galaxy.vendasta.com/)

**Comment by Niaro** [comment]
We use it at https://www.bridgerpay.com/. Tons of thanks for this awesomeness!

**Comment by aloulouamine** [comment]
We use it at https://nordnet.com.

**Comment by oscarlagatta** [comment]
GOV.UK

**Comment by tytusplanck** [comment]
I recently wrote an article on my [organization's](8451.com) journey of using Nx:

 https://medium.com/@tytusplanck/scaling-our-largest-angular-platform-with-nx-8aa70ee3619f

**Comment by ricardo-mello** [comment]
We use at TOTVS Hospitality.
https://produtos.totvs.com/produto/totvs-hospitalidade/pdv/

I also wrote an article a few months ago about how we're using monorepo for 1 year (now are 2 years):
https://medium.com/@ricardo.mello/um-ano-de-monorepo-o-que-aprendemos-e-porque-você-deveria-usá-lo-d3130280bd7d

**Comment by ricardo-mello** [comment]
We use at TOTVS Hospitality.
https://produtos.totvs.com/produto/totvs-hospitalidade/pdv/

I also wrote an article (in Portuguese) a few months ago about how we're using monorepo for 1 year (now are 2 years):
https://medium.com/@ricardo.mello/um-ano-de-monorepo-o-que-aprendemos-e-porque-você-deveria-usá-lo-d3130280bd7d 

And other about Nx itself: https://medium.com/@ricardo.mello/desenvolva-aplicações-full-stack-com-angular-cli-e-nx-2f8dce62975f

**Comment by un33k** [comment]
@vsavkin I have my own consulting company and I deployed NX for a few clients.  The current one is for an enterprise application ( health/insurance)  with 200 active developer (angular) and manages 1/10th of all Americans, which is 35 million people. 

I've just enabled nx cloud for this project, and slowly bumping up the budget cap, as I examine the time saved.

Thank you

**Comment by jschaufele** [comment]
Moving to an opinionated framework is a big step - there can be many value drivers too - My biggest concern is the fact it was originally built for angular, I know it  has scaffolding for other frameworks but most of the people on this feed are using it with angular too - I will be using NextJs - I currently use yarn workspaces but can't find how you pull in existent applications ,  would appreciate insight to these concerns

**Comment by evanfuture** [comment]
We're live at last:

Dungeon Mastery https://dungeonmastery.app

**Comment by un33k** [comment]
@jschaufele - This issue is probably not the best place to address your concern.  But if you had a question on stackoverflow, then perhaps others could provide their experiences with NX, so you can draw your own conclusion.

**Comment by pegaltier** [comment]
I converted my two previous companies:
- https://www.solocal.com/
- https://www.moviplus.ch/

I also used it to generate my Scully boilerplate for my consulting business:
- https://angular-enterprise.com/

**Comment by gullitmiranda** [comment]
yube.com.br

**Comment by derbenoo** [comment]
### Using Nx in production with over 1000 libs and apps :rocket: 

We've been using Nx for almost 2 years and we are pretty much all-in at this point. Our entire monorepo evolves around Nx and by now, it would be impossible to keep building our complex SaaS web-application without full-stack TypeScript, the affected graph and library encapsulation. 

Thanks @vsavkin and the team for building such an awesome open-source project :heart: 

If you want to see what is possible with Nx, you can check out:
[https://tapeapp.com](https://tapeapp.com)


Greetings from the Tape team!

**Comment by Koslun** [comment]
We've been using it in production for over a year with our Angular app along with a Cypress project we've got working but not put into active use yet.

Considerations to start using it for our Node.js server as well.

Company: normative.io
Our app: app.normative.io

**Comment by shashankvivek** [comment]
When I worked with Schlumberger, our team opted for Nx. It has been really a good experience  We used it for DELFI portal
