### ISSUE TITLE
npm install fails during create-nx-workspace 

### ISSUE THREAD

**Issue by olakara** [nrwl/nx#238]
I have the following installed on my PC:
Angular CLI: 1.6.2
Node: 8.6.0
OS: win32 x64
npm: 5.3.0

I installed schematics through the command: `npm install -g @nrwl/schematics` and completed successfully. Next, I ran: `create-nx-workspace my` which didn't complete and threw the following error:

`Error: Command failed: npm install --silent
    at checkExecSyncError (child_process.js:592:13)
    at Object.execSync (child_process.js:632:13)`

Here is the screenshot:
![untitled](https://user-images.githubusercontent.com/570905/35479304-57083df4-040d-11e8-8c24-92e25fae0ff9.png)

the command keeps throwing error at `child_process.js`. I am not able to see the partially created workspace to manually try the npm install command as well. Any solution to this issue? Anybody else facing this?

**Comment by sandangel** [comment]
take > 10minutes on macos too

I'm using nx/schematics 0.6.19

**Comment by jeffkenz89** [comment]
try use yarn

**Comment by dereklin** [comment]
This happens to me when I am behind proxy.  use --yarn shows this error:
```
error ".angular_cli165.tgz": Tarball is not in network and can not be located in cache ...
```
Need to figure out how to properly set the proxy for this...

**Comment by vsavkin** [comment]
The issue has been fixed here: https://github.com/nrwl/nx/commit/cc3f51f85b21548f12c7363d95925f7f39bdae01
