### ISSUE TITLE
(react)[BUG] --sourceMap=false not working

### ISSUE THREAD

**Issue by czaplej** [nrwl/nx#2385]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Failure Information (for bugs)

nx build --sourceMap=false should not create .map files

### Failure Logs

Please include any relevant log snippets or files here.
![image](https://user-images.githubusercontent.com/29889157/73163992-5379ab00-40f1-11ea-9cdb-504702bde2eb.png)

## Other

--sourcemaps=false also not working (I found this in some angular issues)

**Comment by FrozenPandaz** [comment]
Hi, can you please provide a repo showing the issue?

What projects do you have setup? I see the `sourceMap` issue for the react build.

**Comment by felixknox** [comment]
Hi NX team

I am having the same issue with a PROD build
Repo to replicate issue here https://github.com/felixknox/nx-testing

Running:
`nx build test-build --prod --sourceMap`
Results in above error from @czaplej 

Also running:
`nx build test-build --prod`
Produces no sourcemaps, which I would expect to be the default behaviour.
