### ISSUE TITLE
'ng serve api' serves old file version

### ISSUE THREAD

**Issue by ArtemSkok** [nrwl/nx#2387]
## Expected Behavior

The 'ng serve' command should run actual version of the code and watch for changes.

## Current Behavior

The 'ng serve' command does not serve the actual version of the code. It executes some files from cache instead. The 

### Steps to Reproduce

1. Generate nx project.
2. Add nest application.
3. Run 'ng serve [project_name]' on generated with nx schematix nestjs appliacation.
4. Send request to some route of nestjs application (for example you will get '111' string as respose).
4. Make changes to some controller in nestjs application (change the string beeing send as response to '222').
5. Send request to some route of nestjs application.
result: you still get '111' while you won't change the name of the route.

### Context
  @nrwl/angular : 8.11.2
  @nrwl/cli : 8.11.2
  @nrwl/cypress : 8.11.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.11.2
  @nrwl/linter : 8.11.2
  @nrwl/nest : 8.11.2
  @nrwl/next : Not Found
  @nrwl/node : 8.11.2
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.11.2
  @nrwl/web : Not Found
  @nrwl/workspace : 8.11.2
  typescript : 3.4.5

**Comment by FrozenPandaz** [comment]
Sorry, I cannot reproduce this issue. The response changes accordingly for me. Can you please provide a repo showcasing the issue to help us debug this issue?

**Comment by FrozenPandaz** [comment]
Sorry, I was not able to reproduce this issue and a repro has not been provided in 2 months. If you continue to experience this issue, please create a new issue and provide a repro.
