### ISSUE TITLE
Bug with nx lib creation in converted project

### ISSUE THREAD

**Issue by xeax** [nrwl/nx#241]
OS: Win

Angular 4 project was converted to Nx Workspace with:
```
npm install --save-dev @nrwl/schematics
ng generate workspace backoffice --collection=@nrwl/schematics
```

lib added with command:
`ng generate lib fake-db --nomodule`

resulting libs/fake-db/index.ts containing:
`export {FakeDb} from './apps\backoffice\src/fake-db';`
Single `\` is error here.

May be good solution is to use only "/" in all paths.

PS: And I don't understand such folder structure for new library.
Why ./apps/backoffice/src instead of ./src?

**Comment by xeax** [comment]
Using new library class and running:
`ng serve --app=backoffice`
fails with this error:
ERROR in F:/mc/apps/backoffice/src/app/app.component.ts (3,24): Cannot find module '@backoffice/fake-db'.
even if I change libs/fake-db/index.ts to:
`export {FakeDb} from './apps/backoffice/src/fake-db';`

May be problem in apps/backoffice/src/tsconfig.app.json containing option:
`{  ... , "compilerOptions": { ... , "baseUrl": "", ...  }, ... }`

I have not find such option in nx-example apps configs and any apps created in Nx Workspaces created with create-nx-workspace command.

removing it allow normal app serving and prod-building. May be it is a second bug?

**Comment by phl3x0r** [comment]
See [#250](https://github.com/nrwl/nx/issues/250)

**Comment by vsavkin** [comment]
It should be fixed once we switch to the Angular CLI 1.7.

**Comment by vsavkin** [comment]
@xeax could you try it with Nx 0.8?

**Comment by xeax** [comment]
On
```
@angular/cli 1.4.10
@nrwl/schematics 0.8.0
```

My results:
```
F:\test>npm install --save-dev @nrwl/schematics
+ @nrwl/schematics@0.8.0
added 117 packages in 32.831s

F:\test>ng generate workspace backoffice --collection=@nrwl/schematics
  create test.js (1033 bytes)
  update package.json (3139 bytes)
  update .angular-cli.json (1697 bytes)
  update protractor.conf.js (889 bytes)

F:\test>ng generate lib fake-db --nomodule
Error: context.addTask is not a function
context.addTask is not a function
```

**Comment by vsavkin** [comment]
Yup. You need to upgrade the CLI to 1.7+

**Comment by xeax** [comment]
On
```
@angular/cli 1.7.3
@nrwl/schematics 0.8.0
```

lib added with command:
ng generate lib fake-db --nomodule

resulting libs/fake-db/index.ts containing:
`export { FakeDb } from './src/fake-db';`

Now it is correct path without any errors. Thank you!

Tomorrow I'll try to check "Cannot find module" error.

**Comment by vsavkin** [comment]
Closing this as the issue has been resolved by the CLI team.
