### ISSUE TITLE
Application reload when changing library

### ISSUE THREAD

**Issue by gcollin** [nrwl/nx#2414]
Hello all,

I'm trying to see if nrwl nx would be a good fit for our future angular project in my organization. And I'm struggling to find a way to manage libs and apps reload.
It's more a question than a bug I believe, but I would appreciate to know how to achieve this. The documentation doesn't seem to provide an answer.

## Initial steps
I have created a workspace with an application and a library. The application is importing the library, and a nx dep-graph shows this dependency very well.
I run the application using "ng serve" application".
Whenever I change a file in the application code, it gets recompiled and reloaded in the browser automatically, and that's a great way to develop.

## Expected Behavior
When I change a file in the library while the application is running (with ng serve), I expect that the application is recompiled and reloaded as well. Hence I'm as fast developping a library than developping an application.

## Current Behavior
Currently, nothing happens on the application side. To see the effect of the change in the library, I have to restart "ng serve" and face a full compilation again.

### Context

Please provide any relevant information about your setup:
  @nrwl/angular : 8.11.2
  @nrwl/cli : 8.11.2
  @nrwl/cypress : 8.11.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.11.2
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.11.2
  @nrwl/web : Not Found
  @nrwl/workspace : 8.11.2
  typescript : 3.5.3

### Question
Any other way to achieve this auto-recompile / auto-reload of an application when you change a library using nx ?

**Comment by gcollin** [comment]
I fact it just works.
You run the application with ng serve application, and it reloads whenever you make a change to the imported library.
I don't understand why I didn't see this behavior before. Closing the ticket

**Comment by harshit-kishor2** [comment]
i have also same problem plz help how can i get rid of this problem. I'm unable to autoreload

**Comment by nhhockeyplayer** [comment]
same problem here
livereload bogging down development severely
UI libs templates changes html scss
