### ISSUE TITLE
Publish release notes in github

### ISSUE THREAD

**Issue by jogelin** [nrwl/nx#242]
For multiple reason, it could be could to publish the release and the release notes in github. Is it planified ?

**Comment by skydever** [comment]
the [CHANGELOG.md](https://github.com/nrwl/nx/blob/master/CHANGELOG.md) is very useful

**Comment by jogelin** [comment]
Thanks @skydever, I agree with you :)

My point is to use the release management of github which will publish this CHANGELOG.md content in the same time to this page : https://github.com/nrwl/nx/releases 

Some external tools (like [sibbell.com](https://sibbell.com)) are using this page and here, you feel that there are not releases...

**Comment by vsavkin** [comment]
We changed our process to push releases to GitHub. 

Now you should be able to either use https://github.com/nrwl/nx/releases or CHANGELOG.md.
