### ISSUE TITLE
Missing details for release 8.12.1

### ISSUE THREAD

**Issue by minijus** [nrwl/nx#2420]
## Other

There are new versions published to npm (8.12.1). However, there is no new tag for that version in github, there is no new release as well and there is no changelog update.

It would be great to have some details and visibility before pulling these changes in.

```
    We analyzed your package.json, there are some packages to update:
    
      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @nrwl/angular                      8.12.0 -> 8.12.1         ng update @nrwl/angular
      @nrwl/jest                         8.12.0 -> 8.12.1         ng update @nrwl/jest
      @nrwl/workspace                    8.12.0 -> 8.12.1         ng update @nrwl/workspace
```

Similar release happened before for 8.7.1 #2050 . It would be great to have release/publish process reviewed.

**Comment by mehrad-rafigh** [comment]
Details for 8.12.2 are missing as well. @vsavkin can you please update the github releases?

**Comment by vsavkin** [comment]
Sorry folks. Updated the released.
