### ISSUE TITLE
React: Deploy React Apps To Subfolders

### ISSUE THREAD

**Issue by osanzharevskyy** [nrwl/nx#2423]
## Expected Behavior

Regarding [this doc](https://create-react-app.dev/docs/deployment/), if you set homepage in package.json, URL should prepend it to resources:

<script src="http://foo.bar/subfolder/runtime.js" type="module"></script>
<script src="http://foo.bar/subfolder/polyfills.js" type="module"></script>
<script src="http://foo.bar/subfolder/styles.js" type="module"></script>
<script src="http://foo.bar/subfolder/vendor.js" type="module"></script>
<script src="http://foo.bar/subfolder/main.js" type="module"></script>

## Current Behavior

Resource URLs remains the same:

<script src="runtime.js" type="module"></script>
<script src="polyfills.js" type="module"></script>
<script src="styles.js" type="module"></script>
<script src="vendor.js" type="module"></script>
<script src="main.js" type="module"></script>

### Steps to Reproduce

1. add "homepage": "http://foo.bar/subfolder" entry to package.json
2. run yarn build
3. observe source code for index.html

### Context

  @nrwl/angular : Not Found
  @nrwl/cli : 8.7.0
  @nrwl/cypress : 8.7.0
  @nrwl/eslint-plugin-nx : 8.7.0
  @nrwl/express : 8.7.0
  @nrwl/jest : 8.7.0
  @nrwl/linter : 8.7.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 8.7.0
  @nrwl/react : 8.7.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.7.0
  @nrwl/web : 8.7.0
  @nrwl/workspace : 8.7.0
  typescript : 3.4.5

## Other

Solution with .env files also doesn't work, in generated file, it looks like this - <link rel="icon" type="image/x-icon" href="%PUBLIC_URL%/favicon.ico" />
The same behavior, if you set baseUrl in index.html. After building, it resets to default "/".

**Comment by osanzharevskyy** [comment]
Closing issue. Sorry, everything is configurable via workspace.json file.

**Comment by jarppe** [comment]
How this can be configured? I read https://nx.dev/web/api/web/builders/dev-server but did not see anything. I tried blindly setting "baseUrl", "baseHref", "base", but nothing seems to work.

**Comment by osanzharevskyy** [comment]
Well, I've created staging build:

"build:staging": "nx build --configuration=staging"

in workspace.json:

"fileReplacements": [
{
    "replace": "apps/discovery2.0/src/environments/environment.ts",
    "with": "apps/discovery2.0/src/environments/environment.staging.ts"
}],
"deployUrl": "/subfolder",
"baseHref": "/subfolder"

environment.staging.ts:

export const environment = {
    ...productionEnvironment,
    production: false,
    baseHref: '/subfolder', // <-- this one is used for links in your code
};

also you need to configure .htaccess or WebConfig:

.htaccess:
Options -MultiViews
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.html [QSA,L]

WebConfig:
<rule name="rule 1t" stopProcessing="true">
	<match url="^"  />
	<action type="Rewrite" url="/index.html"  appendQueryString="true" />
</rule>

Hope it help.

**Comment by csumudu** [comment]
Thanks @osanzharevskyy this solved my problem
