### ISSUE TITLE
Deploying to Heroku exceeds quota and fails to start application

### ISSUE THREAD

**Issue by asherccohen** [nrwl/nx#2425]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
-  [x ] I am running the latest version
- [ x] I checked the documentation (nx.dev) and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

"nx serve myApp --prod" should only execute the application and not build it unless no build folder is found.

## Current Behavior

"nx serve myApp --prod" builds a new app everytime, this exceeds standard heroku quota and fails to start the application with a procfile as the app should be ready within 60secs.

### Context

Please provide any relevant information about your setup:

-   @nrwl/angular : Not Found
  @nrwl/cli : 8.11.1
  @nrwl/cypress : 8.11.1
  @nrwl/eslint-plugin-nx : 8.11.1
  @nrwl/express : 8.11.1
  @nrwl/jest : 8.11.1
  @nrwl/linter : 8.11.1
  @nrwl/nest : Not Found
  @nrwl/next : 8.11.1
  @nrwl/node : 8.11.1
  @nrwl/react : 8.11.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.11.1
  @nrwl/web : 8.11.1
  @nrwl/workspace : 8.11.1
  typescript : 3.5.3
- 3rd-party libraries and their versions
- and most importantly - a use-case that fails

**Comment by PizzapunkDev** [comment]
It's generally a bad idea to use the built-in Webpack Dev Server that Angular uses to actually host your application - it's not built or designed for a production use case. Your pipeline should be building and pushing the compiled artifacts to Heroku, and an appropriate server for that platform serving it as static content.

**Comment by asherccohen** [comment]
I understand. That was my initial thought but how do I start the app in Heroku?I can't find suggestions to serve applications as static.
Every tutorial points in the direction of a build && start script in package.json. Am I missing something obvious here?
Also this problem happens with Now.sh but their team explained they are working on a solution.

**Comment by jdpearce** [comment]
Hi, @asherccohen! As @PizzapunkDev mentioned, we wouldn't recommend that you use the dev server to serve an Angular application (I believe it does display errors when you run it in production mode)

Serving the app in Heroku is somewhat beyond the scope of what we can help with on here, _however_ what you could do is use something like [serve](https://www.npmjs.com/package/serve) or simply write your own `server.js` as a simple express app, e.g.

```js
const path = require('path');
const express = require('express');
const app = express();

// Serve static files
app.use(express.static(path.join(__dirname, '/dist/my-app')));

// Send all requests to index.html
app.get('/*', function(req, res) {
    res.sendFile(path.join(__dirname, '/dist/my-app/index.html'));
});

// default Heroku port
app.listen(process.env.PORT || 5000);
```

Your `Procfile` would then contain `web: node server.js`

**Comment by asherccohen** [comment]
Ok so it is a known problem and not something I missed. Good to know 🤣.
Very well I'll follow that path.
Thanks for the awesome suggestion!much appreciated.

**Comment by asherccohen** [comment]
Hi @jdpearce and @PizzapunkDev I'm still having troubles with this. I know it's off topic here but serving the exported application on heroku with 'serve' package shows a 404 page.
Any suggestions?
I think the main troube here is the fact that each app doesn't have a package.json and I can't find documentation about deploying in these cases.
When you say that express can be used do you mean I should write a custom next js server -> nx build myApp or (export?) and then use procfile to run the server?
Thanks in advance.
