### ISSUE TITLE
yarn install @next using wrong version

### ISSUE THREAD

**Issue by Jordan-Hall** [nrwl/nx#2426]
Npm install of the @next package is behind the current release version. Can we always keep this build ahead or at least on the current release version

**Comment by vsavkin** [comment]
We talked about it internally, and, unfortunately, we cannot guarantee it. 

Based on https://docs.npmjs.com/cli/dist-tag, the next tag is used to identify the upcoming version. In our case it has to correspond to a beta or an RC release. We were thinking about having a nightly release folks can depend on, but even that strategy won't guarantee it.

Sorry, but I'm going to close this issue.
