### ISSUE TITLE
Build output caching does not work for `@nrwl/next:build` followed by `@nrwl/next:dev-server`

### ISSUE THREAD

**Issue by elliottsj** [nrwl/nx#2429]
## Expected Behavior

Running the `@nrwl/next:build` command should cache build outputs, so that `@nrwl/next:dev-server` does not need to build the app again.

## Current Behavior

```shell
yarn nx run myapp:build:production
# observe: myapp is compiled

yarn nx run myapp:serve:production
# observe: myapp is compiled *again*
```

### Steps to Reproduce

https://github.com/Yolk-HQ/nx-caching-issue-2429

### Context

Please provide any relevant information about your setup:

```
  @nrwl/angular : Not Found
  @nrwl/cli : 8.12.2
  @nrwl/cypress : 8.12.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.12.2
  @nrwl/linter : 8.12.2
  @nrwl/nest : Not Found
  @nrwl/next : 8.12.2
  @nrwl/node : Not Found
  @nrwl/react : 8.12.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.12.2
  @nrwl/web : 8.12.2
  @nrwl/workspace : 8.12.2
  typescript : 3.5.3
```

**Comment by dai4** [comment]
+1 on this. This affects serving the app in production too, when you would have already built the code in a ci/cd pipeline and essentially makes it impossible to efficiently Dockerize the setup

**Comment by vsavkin** [comment]
Please take a look at "The Problem with Building from Source": https://blog.nrwl.io/distributed-caching-in-nx-164edfbc68e0

Basically, webpack rebuilds everything from source. From webpack's point view, serving or building with the watch flag always reads source. You could, of course, change what `myapp:serve:production` means to simply serve the dist folder with say http-server. That would work.

There are several ways to mitigate this problem (e.g., using buildable libraries). All of them involve tradeoffs. We are working on simplifying using biddable libraries making some setups more pragmatic. We will publish something about it in the next month or so.

**Comment by dai4** [comment]
@vsavkin Would you be able to point us to an example where you would modify the serve:production to correctly just run the built next.js app?

**Comment by smakhtin** [comment]
+1 here. Can you provide us with a workaround solution, otherwise it's not understandable how to do production builds.

**Comment by minutuslausus** [comment]
actually this affects angular apps as well. Based on the info that it is caused because of webpack watch flag I would say every single type of project is affected by this (react, next, angular etc)

**Comment by minutuslausus** [comment]
> +1 here. Can you provide us with a workaround solution? Otherwise, it's not understandable how to do production builds.

this issue should not affect builds. The problem here is that on every serve command your code get compiled.

**Comment by vsavkin** [comment]
Hi folks! This example shows a "workaround": https://github.com/nrwl/nx-incremental-large-repo. Basically, you can only cache files written to disk. The example shows how to build libraries (write files to disk), and webpack (for linking and chunking). The example uses Angular but there is really nothing Angular-specific about it.

This isn't ideal because relinking everything takes time, and isn't really needed for development.

My plan is to for very large apps only use webpack for prod builds and have a simple dev server that can load compiled libs, concat them, and serve them. Google does it this way (just with closure instead of webpack). 

Does it make sense?

**Comment by vsavkin** [comment]
Closing this issue. 

Making this a better-supported use case is one of the priorities for H2 2020.
