### ISSUE TITLE
Can't make the migration from CLI to run

### ISSUE THREAD

**Issue by abnersouza** [nrwl/nx#243]
Hi guys,

First time using the nx, i have a project using angular latest 5.2.2 and cli 1.6.5, using SCSS.

I follow the guide on how to migrate from CLI to Nx, but for some reason the scss is looking for the wrong place now and I cant run the application anymore.

![screen shot 2018-01-30 at 11 10 02](https://user-images.githubusercontent.com/3270632/35568089-c066a9a0-05ae-11e8-9c85-0c32e2fbc5c3.png)

You can see from the pic that is trying to find the font-awesome and others inside the ./apps/host/node_modules I think maybe is because of the root.

am I missing something here?

Thanks a lot

**Comment by abnersouza** [comment]
I found the solution, basically the path from the styles/scripts need to go up 3 directories. Here the issue solved.

![screen shot 2018-01-30 at 12 21 12](https://user-images.githubusercontent.com/3270632/35571117-5eddbdd6-05b8-11e8-9a63-71c884d41ea8.png)

**Comment by phl3x0r** [comment]
That's because the paths are relative to the location of the tsconfig.app.json file that you are using.

**Comment by vsavkin** [comment]
Thank you for submitting the issue. This is a known limitation (see here: https://github.com/nrwl/nx/issues/132.), which we need to address. Currently you have to update the paths manually.
