### ISSUE TITLE
[eslint] Cannot produce lint report file using builder

### ISSUE THREAD

**Issue by mrmeku** [nrwl/nx#2435]
There are two steps necessary to fixing this issue.

1) Allow consumers to specify a format using the `--format` flag.
Currently, `@nrwl/linter` intentionally removes the `format` flag when running under `eslint`. Presumably, because the format enum for `eslint` is different for `tslint`. We should stop doing this behavior.

https://github.com/nrwl/nx/blob/b220a17c477f8b3738fc4c538d0b457748de3a01/packages/linter/src/builders/lint/lint.impl.ts#L14

As soon as users can specify an output format, then they could at least pipe STDOUT to a file on disk to produce a report (after removing the other things NX logs, but at least its doable).

2) Add an additional flag to specify an output file location.
This would require an upstream PR to `@angular-eslint` since currently that builder has no configuration option for an output file: https://github.com/angular-eslint/angular-eslint/blob/master/packages/builder/src/schema.json

The way @angular-eslint is currently written, it produces one report per file linted. This strategy could be kept to produce a directory of lint results rather than an individual file, or the upstream change could merge all the individual reports and then write to a file. Depends on what API we feel is best. I personally feel the individual file API is better since I assume most consumers who produce reports will need to merge all individual reports for each individual project's lint job at some point during their CI run

**Comment by bekos** [comment]
@rarmatei i see that both `format` and `outputFile` are supported. shall we close this or is anything else missing? 🤔

**Comment by rarmatei** [comment]
Yes, this should be fixed now 👍 thanks for checking!!
