### ISSUE TITLE
[eslint] Failed to load plugin '@typescript-eslint'

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#2439]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

run `nx lint some-eslint-app ` without errors

## Current Behavior

running `nx lint some-eslint-app` throws: Failed to load plugin '@typescript-eslint' declared in '--config » ../../.eslintrc': Cannot find module '@typescript-eslint/eslint-plugin'

## Failure Information (for bugs)

Some dependencies are not installed when create an application with eslint...

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Just create a new empty workspace or with react-express preset
2. Create a new app with eslint linter (if workspace is empty)
3. Lint that app with `nx lint name-of-the-app`

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context

Please provide any relevant information about your setup:

```
  @nrwl/angular : Not Found
  @nrwl/cli : 8.12.2
  @nrwl/cypress : Not Found
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.12.2
  @nrwl/linter : 8.12.2
  @nrwl/nest : 8.12.2
  @nrwl/next : Not Found
  @nrwl/node : 8.12.2
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.12.2
  @nrwl/web : Not Found
  @nrwl/workspace : 8.12.2
  typescript : 3.5.3
```

**Comment by gperdomor** [comment]
also in 9.0.0 RC1

**Comment by calvinkcox** [comment]
This is also an issue with 9.0.0's (official) release.
It appears to be a problem with the way peer dependencies are being handled.

Manually installing all required peer dependencies appears to resolve:
`yarn add --dev @typescript-eslint/eslint-plugin @babel/core@^7.0.0-0 @nrwl/workspace @nrwl/eslint-plugin-nx @nrwl/nx prettier-eslint eslint-config-prettier eslint-plugin-prettier prettier @typescript-eslint/parser `

Note: I'm not resolving angular peer dependencies required as part of @nx/web so you'll still be getting some warnings.

**Comment by gperdomor** [comment]
In my case I only install `@typescript-eslint/parser @typescript-eslint/eslint-plugin @nrwl/eslint-plugin-nx eslint-config-prettier`

**Comment by jaysoo** [comment]
We made an optimization so package.json updates are only performed as needed, however we made a small logical error for 9.0.0 and the 8.12.x releases.

This has since been patched here: https://github.com/nrwl/nx/pull/2481

If you try 9.0.1 or 8.12.5 this issue should be fixed.
