### ISSUE TITLE
[Feature Request] NuxtJS support

### ISSUE THREAD

**Issue by SOHELAHMED7** [nrwl/nx#2440]
[This comment](https://github.com/nrwl/nx/issues/1541#issuecomment-582508201) by Victor encouraged me to create this issue to track and discuss [NuxtJS](https://nuxtjs.org/) support.

Also solving https://github.com/nrwl/nx/issues/1541 will help to solve part of this issue

**Comment by Jordan-Hall** [comment]
@SOHELAHMED7  I've back on normal internet now and speeding things up.  I'll take a look at NuxtJS and see if i can do both together.  @vsavkin Builder coming on ok. But should this be a community PR or should it come into the main project

**Comment by vsavkin** [comment]
Hey folks. Nx has been pluggable for a while, and we recently landed the `create-nx-plugin` command, which I think is perfect for things like the NuxtJS support. 

I think it's better to develop it in a separate repo, but we are happy to help if you encounter any major issues.

**Comment by SOHELAHMED7** [comment]
Thanks @vsavkin 

I am very much interested to learn `create-nx-plugin` and use it to extend Nx. 

Request to provide docs and and example for `create-nx-plugin`

**Comment by jpsc** [comment]
@SOHELAHMED7 @Jordan-Hall Did you happen to start this plugin somewhere? I would like to help also :)

**Comment by SOHELAHMED7** [comment]
@jpsc I have not started

**Comment by wallopthecat** [comment]
This would be awesome as someone moving from Lerna to nx now - anything I can do to help?

**Comment by dzcpy** [comment]
Still waiting. Hopefully it will be supported soon. Nuxt is quite a nice framework, IMO its more convinient and out-of-the-box usable than Next

**Comment by jpsc** [comment]
It's already available as a plugin. https://github.com/ZachJW34/nx-plus/tree/master/libs/nuxt
