### ISSUE TITLE
[Feature Request] nx edject

### ISSUE THREAD

**Issue by Lonli-Lokli** [nrwl/nx#2447]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Ability to completely edject nx from repository

## Current Behavior

Do not exists

### Context
I would like to have an ability to completely remove Nx from project

**Comment by vsavkin** [comment]
Sorry, given that Nx is an open system built out of plugins, this is not possible. Closing this issue.
