### ISSUE TITLE
ngrx - useDataPersistence flag only works for creators does not work for older syntax

### ISSUE THREAD

**Issue by gkamperis** [nrwl/nx#2448]
## Expected Behavior
I'd expect to not have DataPersistence even when using the older sysntax of ngrx for effects

## Current Behavior
Only works when "creators" is selected as the ngrx implementation

## Failure Information (for bugs)
N/A

### Steps to Reproduce

run the command for ngrx with --useDataPersistence=false
ng g @nrwl/angular:ngrx my-lib --module=XXXX --useDataPersistence=false

### Context

@nrwl/XXXX@8.12.0

## Other

[see older syntax template](https://github.com/nrwl/nx/blob/master/packages/angular/src/schematics/ngrx/files/__directory__/__fileName__.effects.ts__tmpl__
)
it does not use checks like this

`<% if (useDataPersistence) { %> `

as the 
[creator template](https://github.com/nrwl/nx/blob/master/packages/angular/src/schematics/ngrx/creator-files/__directory__/__fileName__.effects.ts__tmpl__
) does

**Comment by brandonroberts** [comment]
@gkamperis is there a reason you aren't using the new creators syntax instead? Would you like to submit a PR for the older syntax?

**Comment by gkamperis** [comment]
@brandonroberts a few reasons... 

We have existing code that uses the older syntax (of the time). Generating a new feature with different syntax would introduce inconsistency in approach in the codebase.

Also completely as a personal preference and I still find the older syntax a lot clearer.

Not very different for effects really but I *really* don't like the new action creators.

I am probably alone in the group that never thought I had boilerplate. And I am probably alone in the group who doesn't like the new syntax. :) 

I prefer the Nx approach with the enum for the action type etc etc. Spelling out exactly what I have in classes etc etc. 

I can also do more with classes, like decorate them... 

I was kind of relieved when I saw the old syntax is still the default. Which is another reason to not use the new one :)

Final reason... @ngrx still supports it!

RE the PR, I'll give it a go. 
Amending the templates is easy not sure what testing will be required so might need help there.

**Comment by brandonroberts** [comment]
@gkamperis thanks for the explanation. Feel free to reach out if you need additional help on the PR.
