### ISSUE TITLE
[Feature]: Ability to bump packages version and update changelog automatically

### ISSUE THREAD

**Issue by gauravsoni119** [nrwl/nx#2457]
## Expected Behavior

Provide schematics to bump up the package version and update the changelog of the packages. This feature is provided by [lerna](https://github.com/lerna/lerna/tree/master/commands/version#lernaversion) and [rushjs](https://rushjs.io/pages/maintainer/publishing/). I am not able to find this on [nx.dev](https://nx.dev/web) documentation.

With the help of this, there is no need to update the package version manually which means one should only focus on code not updating the version and changelog.

## Current Behavior

We need to manually bump up the package version and update the changelog.

## Other

If you guys have some other recommendations for this, it would be also helpful.

**Comment by alexanderPastornicky** [comment]
standard-version

**Comment by Mani2693** [comment]
This feature will be very useful , we need to bump in version and generate change log which is possible in lerna

**Comment by KyleBastien** [comment]
Bumping this thread so it doesn't go stale, this is defiently a needed feature of Nx!

**Comment by KyleBastien** [comment]
Bumping this thread so it doesn't go stale, this is defiently a needed feature of Nx!

**Comment by edbzn** [comment]
@KyleBastien we created a community plugin for that [@jscutlery/semver](https://github.com/jscutlery/semver)

**Comment by KyleBastien** [comment]
@edbzn I think that's close to what I'm thinking, but I wish it was a little less opinionated, similar to Lerna's [`version`](https://github.com/lerna/lerna/tree/main/commands/version#readme) command. i.e. It's very coinvent to not follow convention commits sometimes, or to just be able to pass in `lerna version bump`, etc.

Even it was _just_ the ability to do `nx major | minor | patch | premajor | preminor | prepatch | prerelease`, that would be enough IMO.

**Comment by edbzn** [comment]
@KyleBastien it would be a great addition to the plugin, can you create an issue for that?

**Comment by virus2016** [comment]
This is the only reason why we haven't moved over to NX. Would be amazing to use with semantic release

**Comment by zgover** [comment]
Any update on this?

**Comment by ddhawal** [comment]
Is there any documentation or videos around this on how version bump-up would work? I checked - https://github.com/jscutlery/semver/issues/464,  and found there is no mention of a version in any package.json or product.json and it would get bumped up like Lerna depending upon dependency update.

**Comment by pachiraDIG** [comment]
+bump

**Comment by catsass19** [comment]
bump

**Comment by brossetti1** [comment]
bump

**Comment by unagigd** [comment]
bump

**Comment by Lms24** [comment]
This would be great to have, so... bump

**Comment by andreapigatto** [comment]
I think one main feature a Monorepo needs to have is automatic versioning, publishing packages, etc.. all the lerna commands basically.. was curious about nx and its hype due to the fact that lerna is slowly dying.. but at the end in 2022 seems lerna or lerna + nx to boost performance is still the way to go

**Comment by Lms24** [comment]
Agreed, to me, this seems like an essential feature for a monorepo manager. We were very excited to ditch lerna for nx in one of our new monorepos but we had to [add lerna back](https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/53) just to get a simple version bump possibilty

**Comment by bertyhell** [comment]
I also made a package that does exactly this. It might be used as inspiration to implement the built in feature in nx: https://www.npmjs.com/package/bump-package-versions
