### ISSUE TITLE
create-nx-plugin causes error Cannot find project 'plugin-name-e2e' in 'apps/plugin-name-e2e'

### ISSUE THREAD

**Issue by wickstargazer** [nrwl/nx#2464]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

workspace-lint should work without errors.

## Current Behavior

What is the current behavior?

```
>  NX   ERROR  The angular.json file is out of sync

  - Cannot find project 'plugin-name-e2e' in 'apps/plugin-name-e2e'
```

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

1. run create-nx-plugin on a workspace.
2. run workspace-lint

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context

Please provide any relevant information about your setup:

```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 8.12.0
  @nrwl/cli : 8.12.0
  @nrwl/cypress : 8.12.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.12.0
  @nrwl/linter : 8.12.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 8.12.0
  @nrwl/react : Not Found
  @nrwl/schematics : 8.8.3
  @nrwl/tao : 8.12.0
  @nrwl/web : 8.12.0
  @nrwl/workspace : 8.12.0
  typescript : 3.5.3
```

**A minimal reproduction scenario allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

```
>  NX   ERROR  The angular.json file is out of sync

  - Cannot find project 'aws-cdk-e2e' in 'apps/aws-cdk-e2e'
```

## Other

Any other relevant information that will help us help you.

**Comment by Cammisuli** [comment]
Hi @wickstargazer, I just tried with the latest version of nx, and I wasn't able to reproduce this. Can you try with the latest?

Also, for an FYI `create-nx-plugin` will create a new nx workspace. Are you trying to add the nx-plugin to an existing workspace (angular or nx)?

**Comment by wickstargazer** [comment]
i am trying to add it to the current workspace, oh yes i actually did the `ng g @nrwl/plugins` route

sorry, i had the mix-ups
i am upgrading the workspace atm, will try with the new version

**Comment by wickstargazer** [comment]
@Cammisuli 
I am still getting the same error with `workspace-lint`, this time i started from a brand new project. I will be moving the lib to the workspace and publishing it soon ... lets take a look then?

**Comment by Cammisuli** [comment]
Sure. In the meantime, can you provide me with the exact steps you used? Did you execute `ng g @nrwl/nx-plugin`? Or something else?

**Comment by wickstargazer** [comment]
Sure,
I just executed `ng g @nrwl/nx-plugin:plugin-name` .. Thats about it, then run workspace-lint
then it complains about the e2e project not being found/matched according to the error msg i posted.

**Comment by Cammisuli** [comment]
I can't reproduce the errors. Here's the output for me:
```sh
test-workspace on  master [!?] is 📦 v0.0.0 took 1m 3s 658ms 
 [I] ➜ yarn nx g @nrwl/nx-plugin:plugin myplugin
yarn run v1.19.2
$ nx g @nrwl/nx-plugin:plugin myplugin
CREATE libs/myplugin/tslint.json (48 bytes)
CREATE libs/myplugin/README.md (170 bytes)
CREATE libs/myplugin/tsconfig.json (123 bytes)
CREATE libs/myplugin/tsconfig.lib.json (249 bytes)
CREATE libs/myplugin/src/index.ts (0 bytes)
CREATE libs/myplugin/tsconfig.spec.json (273 bytes)
CREATE libs/myplugin/jest.config.js (240 bytes)
CREATE libs/myplugin/package.json (159 bytes)
CREATE libs/myplugin/builders.json (285 bytes)
CREATE libs/myplugin/collection.json (334 bytes)
CREATE libs/myplugin/src/builders/myplugin/builder.spec.ts (1486 bytes)
CREATE libs/myplugin/src/builders/myplugin/builder.ts (508 bytes)
CREATE libs/myplugin/src/builders/myplugin/schema.d.ts (113 bytes)
CREATE libs/myplugin/src/builders/myplugin/schema.json (221 bytes)
CREATE libs/myplugin/src/schematics/myplugin/schema.d.ts (100 bytes)
CREATE libs/myplugin/src/schematics/myplugin/schema.json (621 bytes)
CREATE libs/myplugin/src/schematics/myplugin/schematic.spec.ts (790 bytes)
CREATE libs/myplugin/src/schematics/myplugin/schematic.ts (2166 bytes)
CREATE libs/myplugin/src/schematics/myplugin/files/src/index.ts.template (38 bytes)
CREATE apps/myplugin-e2e/tsconfig.json (123 bytes)
CREATE apps/myplugin-e2e/tests/myplugin.test.ts (1488 bytes)
CREATE apps/myplugin-e2e/tsconfig.spec.json (199 bytes)
CREATE apps/myplugin-e2e/jest.config.js (136 bytes)
UPDATE tsconfig.json (799 bytes)
UPDATE angular.json (10502 bytes)
UPDATE nx.json (702 bytes)
✨  Done in 2.68s.
test-workspace on  master [!?] is 📦 v0.0.0 
 [I] ➜ yarn nx workspace-lint
yarn run v1.19.2
$ nx workspace-lint
✨  Done in 0.83s.
```

**Comment by wickstargazer** [comment]
OK! i found the error :)
**OS : Windows**
when generating the test, the `e2e` section in config is updated with the following `sourceRoot`

```
 "sourceRoot": "apps\\plugin-name-e2e/src",
```
it should be 

```
 "sourceRoot": "apps/plugin-name-e2e/src",
```

Thats about it... Thankz for the confirmation tha things works! @Cammisuli

**Comment by dbartholomae** [comment]
Can confirm the problem. I dug a bit into the code of the generator, and based on my understanding using a package like [slack](https://github.com/sindresorhus/slash) in one of the following lines should fix the problem:
https://github.com/nrwl/nx/blob/master/packages/nx-plugin/src/schematics/e2e-project/e2e.ts#L60
https://github.com/nrwl/nx/blob/master/packages/nx-plugin/src/schematics/e2e-project/e2e.ts#L127

I'm not sure though which position would be better - depends on how this would be used. The same problem might also exist in other templates.
I would be willing to provide a PR, but would need some guidance along these topics first.

**Comment by Cammisuli** [comment]
Hi @dbartholomae, you're right where this could appear in other schematics. I think some refactoring needs to be done so that all packages use the same implementation of getting the project name.

**Comment by hgschwibbe** [comment]
Same problem here. I reproduced it by creating a storybook configuration without e2e:

`$ ng g @nrwl/angular:storybook-configuration libraryXyz`
✔ Configure a cypress e2e app to run against the storybook instance? (Y/n) · false
✔ Automatically generate *.stories.ts files for components declared in this project? (Y/n) · true
✔ Automatically generate *.spec.ts files in the cypress e2e app generated by the cypress-configure generator? (Y/n) · false

Then run:
`$ ng g @nrwl/angular:stories --name=libraryXyz`

``
Error: Cannot find project 'theme-e2e'
    at Object.getProjectConfig (/home/hgsch/sourcecode/pbv-frontends/node_modules/@nrwl/workspace/src/utils/ast-utils.js:448:15)
    at /home/hgsch/sourcecode/pbv-frontends/node_modules/@nrwl/angular/src/schematics/component-cypress-spec/component-cypress-spec.js:19:60
    at MergeMapSubscriber.project (/home/hgsch/sourcecode/pbv-frontends/node_modules/@angular-devkit/schematics/src/rules/call.js:75:24)
    at MergeMapSubscriber._tryNext (/home/hgsch/sourcecode/pbv-frontends/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/home/hgsch/sourcecode/pbv-frontends/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/home/hgsch/sourcecode/pbv-frontends/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/home/hgsch/sourcecode/pbv-frontends/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)
    at Observable._trySubscribe (/home/hgsch/sourcecode/pbv-frontends/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/home/hgsch/sourcecode/pbv-frontends/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Observable.js:30:22)
    at MergeMapOperator.call (/home/hgsch/sourcecode/pbv-frontends/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:37:23)
Cannot find project 'theme-e2e'
``
