### ISSUE TITLE
yarn create nx-workspace fails in 9.0.0

### ISSUE THREAD

**Issue by x87** [nrwl/nx#2465]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Nx creates a new workspace

## Current Behavior

Nx fails as it can't detect the version of Node

## Failure Information (for bugs)

```bash
$ yarn create nx-workspace
yarn create v1.15.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "create-nx-workspace > @nrwl/workspace@9.0.0" has unmet peer dependency "prettier@^1.18.2".
[4/4] 🔨  Building fresh packages...
success Installed "create-nx-workspace@9.0.0" with binaries:
      - create-nx-workspace
? Workspace name (e.g., org name)     nx-test
? What to create in the new workspace angular           [a workspace with a single Angular application]
? Application name                    nx-test
? Default stylesheet format           SASS(.scss)  [ http://sass-lang.com   ]
Creating a sandbox with Nx...
new nx-test --preset="angular" --appName="nx-test" --style="scss" --interactive=false --collection=@nrwl/workspace
Node.js version undefined detected.
The Angular CLI requires a minimum Node.js version of either v10.13 or v12.0.

Please update your Node.js version or visit https://nodejs.org/ for additional instructions.
(node:6081) UnhandledPromiseRejectionWarning: Error: Command failed: "/var/folders/tl/vdskkggx6f53nd7n6ytj9ztr0000gp/T/tmp-6081Jqj0tQeIpaQX/node_modules/.bin/ng" new nx-test --preset="angular" --appName="nx-test" --style="scss" --interactive=false --collection=@nrwl/workspace
    at checkExecSyncError (child_process.js:639:11)
    at Object.execSync (child_process.js:676:15)
    at createApp (/Users/xxxxx/.config/yarn/global/node_modules/create-nx-workspace/bin/create-nx-workspace.js:342:21)
    at determineCli.then.cli (/Users/xxxxx/.config/yarn/global/node_modules/create-nx-workspace/bin/create-nx-workspace.js:76:21)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:6081) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6081) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 86.25s.

$ node -v
v11.15.0
```
### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create a new folder and cd into it
2. run `yarn create nx-workspace`
3. observe the error in the console (see the log above)

### Context

Please provide any relevant information about your setup:

- yarn 1.15.2
- node 11.15.0

### Failure Logs

see above

## Other
same happens with `npm init nx-workspace`

**Comment by FrozenPandaz** [comment]
Sorry, the error message is vague but Node 11 is not supported by the Angular CLI.

> The Angular CLI requires a minimum Node.js version of either v10.13 or v12.0.

https://github.com/angular/angular-cli/blob/3c771d1b56f369cd5385b911023e4a134b2a1da8/packages/angular/cli/bin/ng#L18

Please use Node ~10.13 or Node ~12.0
