### ISSUE TITLE
Initial workspace conversion corrupts binary files during file renames

### ISSUE THREAD

**Issue by armstrjare** [nrwl/nx#2469]
## Expected Behavior

Initial workspace conversion from standard angular-cli workspace reorganises binary files without modification.

## Current Behavior

Binary files are modified during filesystem reorganisation

## Failure Information (for bugs)

I think this is due to converting the file `Buffer` to String during copying files.  

https://github.com/nrwl/nx/blob/f232a438d3ed5a10235d278b0f0e4573c19d14dc/packages/workspace/src/schematics/init/init.ts#L331

https://github.com/nrwl/nx/blob/f232a438d3ed5a10235d278b0f0e4573c19d14dc/packages/workspace/src/utils/ast-utils.ts#L773

https://github.com/nrwl/nx/blob/f232a438d3ed5a10235d278b0f0e4573c19d14dc/packages/workspace/src/utils/ast-utils.ts#L800

### Steps to Reproduce

1. Create existing angular-cli workspace
2. Add binary files in assets directory
3. Run NX migration.
4. Observe binary image files are corrupted.

### Context
```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 8.12.4
  @nrwl/cli : 8.12.4
  @nrwl/cypress : 8.12.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.12.4
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.12.4
  @nrwl/web : Not Found
  @nrwl/workspace : 8.12.4
  typescript : 3.7.5
```
```
Angular CLI: 9.0.1
Node: 12.0.0
OS: darwin x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.23
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        8.3.23
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               8.3.23
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
```

**Comment by amtb** [comment]
Happens with 8.12.9 as well.

**Comment by Pablodotnet** [comment]
This is still happening :C
