### ISSUE TITLE
Question  on Effect with DataPersistence to listen to multiple actions 

### ISSUE THREAD

**Issue by joelmuskwe** [nrwl/nx#2470]
# Prerequisites
- [*] I am running the latest version
- [*] I checked the documentation (nx.dev) and found no answer
- [*] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Question  on effects  on  how an effect with DataPersistence can  be triggered  from multiple actions.  

## Current Behavior
**On Code Below  it's  only  working  for one action**
  getUserInfo$ = createEffect(
    () =>
  this.dataPersistence.fetch(
    AuthActions.loginSuccess || AuthActions.getUserDetails,
    {
      run: (
        action:
          | ReturnType<typeof AuthActions.getUserDetails>
          | ReturnType<typeof AuthActions.loginSuccess>,
        state: fromAuth.AuthPartialState
      ) => {
        // Your custom service 'load' logic goes here. For now just return a success action...
        return this.service
          .getUserDetails()
          .pipe(
            map((user: UserEntity) =>
              AuthActions.getUserDetailsSuccess({ user })
            )
          );
      },

      onError: (
        action: ReturnType<typeof AuthActions.getUserDetails>,
        error
      ) => {
        console.error('Error', error);
        return AuthActions.getUserDetailsFailure({ error });
      }
    }
  )
  );

**I   ended up removing persistencess  for it to work like below**
  getUserDetails$ = createEffect((): any =>
    this.actions$.pipe(
      ofType(AuthActions.loginSuccess, AuthActions.getUserDetails),
      mergeMap(() =>
        this.service.getUserDetails().pipe(
          map((user: UserEntity) =>
            AuthActions.getUserDetailsSuccess({ user })
          ),
          catchError(error => of(AuthActions.getUserDetailsFailure({ error })))
        )
      )
    )
  );

**Comment by brandonroberts** [comment]
Hey @joelmuskwe. Use the `fetch` pipeable operator from `@nrwl/angular` which is the counterpart to using the DataPersistence service.

```ts
getUserDetails$ = createEffect((): any =>
  this.actions$.pipe(
    ofType(AuthActions.loginSuccess, AuthActions.getUserDetails),
    fetch({
      run: action => {
        // Your custom service 'load' logic goes here. For now just return a success action...
        return someAction();
      },
  
      onError: (action, error) => {
        console.error('Error', error);
        return someErrorAction();
      }
    }))
  );

```
