### ISSUE TITLE
affected command has different output on azure devops hosted build agents (linux vs windows)

### ISSUE THREAD

**Issue by elvirdolic** [nrwl/nx#2472]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x ] I checked the documentation (nx.dev) and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

`yarn affected:build --base=origin/master --head=HEAD --aot --parallel --maxParallel=1`

project 1

Please describe the behavior you are expecting

## Current Behavior

running this command on Azure Devops linux build agent ("ubuntu-latest") should produce the same output then running on Windows Image but it doesn't. On Linux all project are affected if this one particular app was changed. On Windows it's the correct behavior.

`yarn affected:build --base=origin/master --head=HEAD --aot --parallel --maxParallel=1`

project 1
project 2
project 3

## Failure Information (for bugs)

Linux

```
Starting: yarn affected:build
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.163.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
(node:5189) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:5189) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:5189) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:5189) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:5189) Warning: Use Cipheriv for counter mode of aes-256-ctr
Script contents:
(node:5189) Warning: Use Cipheriv for counter mode of aes-256-ctr
yarn affected:build --base=origin/master --head=HEAD --aot --parallel --maxParallel=1
========================== Starting Command Output ===========================
(node:5189) Warning: Use Cipheriv for counter mode of aes-256-ctr
/bin/bash --noprofile --norc /home/vsts/work/_temp/c067de7d-cafa-4374-b2b7-60f55940a2b9.sh
yarn run v1.21.1
$ nx affected:build --base=origin/master --head=HEAD --aot --parallel --maxParallel=1

>  NX  Running target build for projects:

- project1
- project2
- project x

```
Windows

```
Starting: yarn affected:build
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.163.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
yarn affected:build --base=origin/master --head=HEAD --aot --parallel --maxParallel=1
========================== Starting Command Output ===========================
"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "d:\a\_temp\dc4e1fee-88aa-45fd-94e2-94ffee4e5549.cmd""
yarn run v1.21.1
$ nx affected:build --base=origin/master --head=HEAD --aot --parallel --maxParallel=1

>  NX  Running target build for projects:

- project1
```

### Steps to Reproduce
Just switching agent in build pipeline and the affected command prints different results

### Failure Logs

Please include any relevant log snippets or files here.

## Other

Any other relevant information that will help us help you.

**Comment by vsavkin** [comment]
@elvirdolic thank you for submitting the issue. It's hard to troubleshoot without having a repro. The affected logic relies on using git to see what files changed and then matching them against the projects. 

Could you run print-affected command on both agents to compare the results? 

I'm curious about the edges in the dep graph.

**Comment by SebasG22** [comment]
Hey folks, 
@vsavkin, Thanks for your quickly response.
I'm experimenting the same issue with a private repository in `CIRCLE CI`.
On my machine the print affected gets a different output (RIGHT OUTPUT) than over `circle ci`.
** My Machine ** Ubuntu 18.04
![image](https://user-images.githubusercontent.com/17608169/75300754-e1d37080-5806-11ea-8b2c-82988c6a0e82.png)
** Circle CI **
![image](https://user-images.githubusercontent.com/17608169/75300815-0d565b00-5807-11ea-874a-742c298b4b2e.png)


My circle CI config is using the `print affected` in the same way that this example repo https://github.com/nrwl/nx-azure-build using `calculate-commands.js`

It's a wired bug, and for now only happens to that branch.

**Comment by SebasG22** [comment]
Hey folks,
After digging a lot into the problem I found the root cause of the issue so please be sure that you are running the same version of **git** in both environments and use the `base` pointing to the origin.

**Wrong way**
```js
const baseSha = isMaster ? 'origin/master~1' : 'master';
$ nx print-affected --base=${baseSha} --head=${head} --target=${target}
```

**Good Way**
```js
const baseSha = isMaster ? 'origin/master~1' : 'origin/master';
$ nx print-affected --base=${baseSha} --head=${head} --target=${target}
```
**Note**: If you have any issues with git and `baseSHA` make sure you have a reference for `origin`.
Just make a `git fetch origin master `.

Hope this solve the problem @elvirdolic.

**Comment by elvirdolic** [comment]
@SebasG22 this is not the same issue.
[linux.txt](https://github.com/nrwl/nx/files/4257709/linux.txt)
[windows.txt](https://github.com/nrwl/nx/files/4257711/windows.txt)



@vsavkin attached is the output on linux vs windows. I just changed agent-pool setting.

**Comment by vsavkin** [comment]
@elvirdolic  From what I can see, the number of nodes is the same but the windows version is missing edges some edges. You can look at the dependencies section of the two json documents to figure out what is different. Once you know what edges are missing, you can try to investigate why they aren't there in the windows version.

**Comment by elvirdolic** [comment]
@vsavkin in the windows version

there is only one entry for

 "target": "paldesk" => this is the project/app which is affected

in the linux version there are way more entries like this.

**Comment by vsavkin** [comment]
@elvirdolic the edges are created by analyzing esm imports. You can examine those to see if there is anything unusual about them. You can then look at your global `tsconfig.json` to see if path mappings for those imports are set up correctly.

With a repro I can look at, I cannot troubleshoot it further. Could you provide a github repo with a repro?

**Comment by elvirdolic** [comment]
@vsavkin thank you for your support. I have found the issue. There is an import in one of the shared libs from this app. The question is then why on linux this is done right and on Windows it's not :)

**Comment by manandkumaar** [comment]
Thanks @elvirdolic for reporting this issue. 

Hi @vsavkin, 

I am also facing this issue after upgrading from 8.12.11 to 9.2.3. This issue is happening only at azure pipeline with linux hosted agents and the same works fine in my local (windows 10). 

**Expected Behavior**
nx affected:build --base=remotes/origin/master --exclude=${excludePublishableWidgets} --prod --parallel

project 1

**Screenshots:**

![image](https://user-images.githubusercontent.com/2328960/82792038-637d7d80-9e8c-11ea-86b2-2ce124f3f5e7.png)

**Current Behavior**
running this command on Azure Devops linux build agent ("ubuntu-latest") should produce the same output then running on Windows Image but it doesn't. On Linux all project are affected if this one particular app was changed. On Windows it's the correct behavior.

nx affected:build --base=remotes/origin/master --exclude=${excludePublishableWidgets} --prod --parallel

project 1
project 2
project 3

**Screenshots:**

![image](https://user-images.githubusercontent.com/2328960/82791593-ab4fd500-9e8b-11ea-8d1f-2a1eec27bd26.png)

**Comment by elvirdolic** [comment]
@manandkumaar I have found the issue by running nx print-affected --base=origin/master --head=HEAD --target=build on the linux agent. 
* search then for one project where you know it shouldn't be rebuild because it`'s not affected
* find all projects entries where "target": "my-project" is listed and check the project if you have some imports in this lib/app 

The linux output  was right one. The window output was wrong in my case.

**Comment by philipjfulcher** [comment]
@elvirdolic I'm circling back to some of these issues related to differences between Windows/Linux/Mac OS and I think they're resolved in our latest version of Nx 9 and 10. Are you able to update your repo to 9.6 or 10.1 to see if that resolves the issue?

**Comment by elvirdolic** [comment]
@philipjfulcher I don't have any problem with this anymore. We are already on latext nx version and we can' reproduce it anymore
