### ISSUE TITLE
ng g defaults in angular.json ignored on migration to 9.0

### ISSUE THREAD

**Issue by goelinsights** [nrwl/nx#2475]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

## Expected Behavior

ng g c utilizes the defaults in angular.json that worked prior to migrating to nx workspace 9/ Angular 9

## Current Behavior

What is the current behavior?
component generated ignores the configuration file defaults.  In my case, (see configuration below), 
component generation has a css file, isn't flat, and doesn't add changeDetection.OnPush

### Steps to Reproduce

angular.json
```
 "defaultProject": "my-project",
  "schematics": {
    "@nrwl/schematics:component": {
      "styleext": "scss",
      "spec": true,
      "flat": true,
      "changeDetection": "OnPush"
    },
```
`ng g c my-component-name`

### Context

Please provide any relevant information about your setup:

Report complete - copy this into the issue template

  @nrwl/angular : 9.0.0
  @nrwl/cli : 9.0.0
  @nrwl/cypress : 9.0.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : 9.0.0
  @nrwl/jest : 9.0.0
  @nrwl/linter : 9.0.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.0.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.0.0
  @nrwl/web : Not Found
  @nrwl/workspace : 9.0.0
  typescript : 3.7.5

**A minimal reproduction scenario allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

Fails silently

## Other

Happy to investigate more, but where is the configuration file pulled from?

**Comment by xmlking** [comment]
Angular cli 9.0.2 deprecated  `styleext`,  `spec` should be replaced with `style`,  `skipTests ` by Nx as well...
