### ISSUE TITLE
[Bug] Angular builder cannot find built dependent libs

### ISSUE THREAD

**Issue by gund** [nrwl/nx#2479]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Builder `@nrwl/angular:package` should be able to locate built dependent libraries in custom locations (not in `dist/libs/<lib-name>`) if library output path was changed in it's `ng-package.json`'s `dest` property.

## Current Behavior

Right now builder `@nrwl/angular:package` has hardcoded path to resolve all dependent libs from path that looks like `dist/libs/<lib-name>`:

https://github.com/nrwl/nx/blob/f232a438d3ed5a10235d278b0f0e4573c19d14dc/packages/angular/src/builders/package/package.impl.ts#L55-L60

## Failure Information (for bugs)

When building a library via `@nrwl/angular:package` builder that has another library as dependency that is also built with `@nrwl/angular:package` and it's output path was modified then build fails with:

```
Some of the library button's dependencies have not been built yet. Please build these libraries before:
- utils

Try: nx run-many --target build --projects button,...
```

### Steps to Reproduce

1. Create empty NX workspace
2. Generate a publishable angular library called `lib1`
3. Generate a publishable angular library called `lib2`
4. Import NgModule from `lib1` into `lib2`
5. Modify `ng-package.json` file of `lib1` to change `dest` property to other location (`./dist`) instead of default `../../dist/libs/lib1`
6. Run `ng build lib1` to build dependency first
6. Run `ng build lib2` and watch it fails even when we built it's dependency `lib1`

### Context

```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 9.0.0
  @nrwl/cli : 9.0.0
  @nrwl/cypress : 9.0.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.0.0
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.0.0
  @nrwl/web : Not Found
  @nrwl/workspace : 9.0.0
  typescript : 3.7.5
```

**Comment by gund** [comment]
I'm sorry - I actually looked at the code of `node` builder =)

In the angular builder the path is hardcoded to `dist/<lib-root>/package.json`:

https://github.com/nrwl/nx/blob/f232a438d3ed5a10235d278b0f0e4573c19d14dc/packages/angular/src/builders/package/package.impl.ts#L55-L60

This is a problem because we can still modify the destination path in the `ng-package.json` `dest` property.
And once it's changed from default the builder will never be able to find built libraries.

So angular builder should resolve package.json by looking at `ng-package.json` `dest` property that is located in `angular.json` `project` option of the `build` target.

The steps should be:

1. Locate ng-package.json first from `angular.json`:
```jsonc
"architect": {
  "build": {
    "builder": "@nrwl/angular:package",
    "options": {
      "tsConfig": "libs/utils/tsconfig.lib.json",
      "project": "libs/utils/ng-package.json" // <-- Locate ng-package.json first
    }
  },
}
```
2. Read `ng-package.json`'s `dest` property to find destination path:
```jsonc
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "./dist", // <-- Read this prop
  "lib": {
    "entryFile": "src/index.ts"
  }
}
```

Now we can use that path to find `package.json` of built dependency.

Please let me know if this is enough - I might work on PR for this change =)

**Comment by florianehmke** [comment]
Are there any workarounds for this?

**Comment by gund** [comment]
@florianehmke my workaround for now is keeping the output path as default and then after build executing script to copy assets back to where I needed them.

**Comment by SURBHU** [comment]
Hi Author, 
I am also facing same issue while building lib packages when upgraded to Angular 9. Please let me have the solution for it.

**Comment by juristr** [comment]
The problem here is that the `angular.json` libs' `outputs` property needs to be always in sync with what is in the `ng-package.json` as of now. We don't sync them manually, but that needs to be done by the user in case they're being changed.

Basically right now a lib config might look like this:

```
"core-publib1": {
    "projectType": "library",
    ...
    "architect": {
        "build": {
            "builder": "@nrwl/angular:package",
            "options": {
                "tsConfig": "libs/core/publib1/tsconfig.lib.json",
                "project": "libs/core/publib1/ng-package.json"
            },
        }
}
```

By default everything works out of the box. If someone changes the `dest` inside the `ng-package.json`, the output path Nx infers would be out of sync with what is being used by ng-packagr and thus leads to unexpected behaviours. To fix that, add the `outputs` property to the config in `angular.json`, like:

```
"core-publib1": {
    "projectType": "library",
    ...
    "architect": {
        "build": {
            "builder": "@nrwl/angular:package",
            "outputs": ["dist/libs/core/publib__1"], <<<<<<<<<<<< needs to be in sync with ng-package.json
            "options": {
                "tsConfig": "libs/core/publib1/tsconfig.lib.json",
                "project": "libs/core/publib1/ng-package.json"
            },
        }
}
```
