### ISSUE TITLE
[Feature Request / Question] More robust polyglot support

### ISSUE THREAD

**Issue by J-Swift** [nrwl/nx#2482]
Hey nrwl team, I continue to love what yall are doing! Thanks for being awesome!

I know you are probably focused on the JS ecosystem in terms of full stack support, but I know I've heard you talk in the past about true polyglot monorepo support within the `nx` toolchain. I haven't been able to track down any info online or within this repo on your official plans for, e.g., dotnet as a backend. I assume a lot of that is ideally leveraging bazel and so that has to come first, but I was just hoping you could share any specifics on your plans / thoughts around supporting backends that aren't JS-based. Selfishly I care about dotnet core but I think it probably has a lot of overlap in other ecosystems as well.

Thanks again!

**Comment by FrozenPandaz** [comment]
Implementing Bazel will definitely help with this. What are people most interested in seeing?

**Comment by J-Swift** [comment]
My vote is on dotnet (core) and I suspect there are a lot of angular shops that run dotnet on their backend.

I'd also love rails but I'm not sure there would be enough interest/Bazel support for that

**Comment by tomdavidson** [comment]
We have Rust modules and end up with Python on our data side - no matter how much we try to do with NodeJS.

**Comment by exequiel09** [comment]
I also use Python side by side with Angular

**Comment by keberox** [comment]
Python

**Comment by mrlubos** [comment]
Hey, Python here as well! Any updates on this request?

**Comment by mrlubos** [comment]
No

**Comment by leonardochaia** [comment]
I remember reading there was a Go implementation being worked on..

I'm interested in .NET Core as well

**Comment by mrlubos** [comment]
Sigh

**Comment by dasco144** [comment]
Would be great if we could move our dotnet/angular projects into a single nx repo

**Comment by mrlubos** [comment]
Bump

**Comment by mrlubos** [comment]
Bump

**Comment by sgammon** [comment]
bump from JVM land 😄

**Comment by AgentEnder** [comment]
Just as an update, we support multiple languages via custom plugins. There are currently several community plugins (including my own, from before I joined nrwl that I still maintain) for various languages. Off the top of my head, there are plugins to add support for: 
- dotnet cli
- java / spring
- python
- go

I can't speak much for the plugins other than https://github.com/nx-dotnet/nx-dotnet, but nx-dotnet supports _most_ of the functionality of Nx without getting in the way of developers who would rather use built in tooling in visual studio during development.

What kind of additional support for these plugins would people like to see?

**Comment by mrlubos** [comment]
Thanks @AgentEnder! I didn't know about the Python plugin and it seems it should suffice for my needs. That being said, if there was a native support for other languages directly in Nx, that would be preferred!

**Comment by AgentEnder** [comment]
Talking about "native" support in Nx gets a little blurry. "native" Nx is really just @nrwl/tao, @nrwl/workspace and @nrwl/devkit. All of the other Nrwl packages are themselves plugins just like a community plugin would be. Some things we do handle on the native side are things like dependency graph analysis for typescript files, but that capability has been exposed to plugins now (nx-dotnet as an example supports this).

Other things that people associate with Nx's core may be things like module boundaries, but thats not straightforward in other languages as things like dotnet core do not have the same concept of a linter that we have in JS land. That being said, plugin developers can definitely add support for this its just a bit messier. For example, in nx-dotnet we have a prebuild msbuild task that checks this. It could feasibly be done as a Roslyn analyzer as well. But eslint and the built in eslint rules don't apply in these kinds of projects.

This kind of thing is definitely close to my heart, the benefits Nx brings to javascript based repos are huge and if they can be shared they should be. 

Is there some additional capability that you would like to see exposed to plugins to aid in polyglot support?

**Comment by mrlubos** [comment]
Thank you for the additional context @AgentEnder! I am all good for now with the Python support, thank you!

**Comment by thurahtetaung** [comment]
The python community plugin is archived and no longer maintained by the original maintainer. If anyone know of an alternative way to get python apps (not django or flask, generic python) to work in an NX workspace, please let me know.

**Comment by Johanneslueke** [comment]
Why did you close the issue? The fact that the python plugin is being archived makes this discussion even more important!

Not just for python but for the other community driven plugins.

Could you explain your reasoning. Just linking to the issue left me with more questions then answers.
