### ISSUE TITLE
pascalCaseFiles option bug

### ISSUE THREAD

**Issue by epikhighs** [nrwl/nx#2488]
## Expected Behavior

I was expecting pascalCaseFiles option to actually drop hyphenation in file name creation and possibly even in the project name

https://nx.dev/web/api/react/schematics/library#pascalcasefiles

## Current Behavior

nx g @nrwl/react:lib heroStat --pascalCaseFiles=true --dryRun 
CREATE libs/hero-stat/.eslintrc (7019 bytes)
CREATE libs/hero-stat/README.md (172 bytes)
CREATE libs/hero-stat/tsconfig.json (405 bytes)
CREATE libs/hero-stat/tsconfig.lib.json (224 bytes)
CREATE libs/hero-stat/src/index.ts (33 bytes)
CREATE libs/hero-stat/tsconfig.spec.json (273 bytes)
CREATE libs/hero-stat/jest.config.js (244 bytes)
**CREATE libs/hero-stat/src/lib/hero-stat.css (0 bytes)
CREATE libs/hero-stat/src/lib/hero-stat.spec.tsx (285 bytes)**
CREATE libs/hero-stat/src/lib/hero-stat.tsx (286 bytes)
UPDATE tsconfig.json (777 bytes)
UPDATE workspace.json (10274 bytes)
UPDATE nx.json (732 bytes)

notice how the project name and file names are hero-stat  instead of the heroStat that was passed in

### Context

Please provide any relevant information about your setup:

using nx v9.0

**Comment by jaysoo** [comment]
The `pascalCaseFiles` option need to be pass down to the component schematic.

https://github.com/nrwl/nx/blob/ed0f0f8/packages/react/src/schematics/library/library.ts#L82-L91

We can patch it next release. Thank for reporting!
