### ISSUE TITLE
affected commands ignore new targets (cached in nxdeps.json)

### ISSUE THREAD

**Issue by studds** [nrwl/nx#2489]
## Expected Behavior

Adding a new target "bullseye" and running `nx affected --target bullseye` should run the "bullseye" target.

## Current Behavior

Targets are "cached" in nxdeps.json, and the new target is ignored.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

1. Run `nx affected:build`
2. Add a new target "bullseye" to workspace.json
3. Run `nx affected --target bullseye"`

### Context

Please provide any relevant information about your setup:

@nrwl/angular : Not Found
  @nrwl/cli : 9.0.0
  @nrwl/cypress : Not Found
  @nrwl/eslint-plugin-nx : 9.0.0
  @nrwl/express : Not Found
  @nrwl/jest : 9.0.0
  @nrwl/linter : 9.0.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.0.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.0.0
  @nrwl/web : Not Found
  @nrwl/workspace : 9.0.0
  typescript : 3.7.5

**Comment by vsavkin** [comment]
Thank you for submitting the issue!

It has been fixed in Nx 9.0.2 and Nx 8.12.7.
