### ISSUE TITLE
NextJs styled-components starter error: Cannot find name NxLogo

### ISSUE THREAD

**Issue by luisfilipegoncalves** [nrwl/nx#2494]
## Expected Behavior

Next.js sample app with styled components should load correctly. 

## Current Behavior

Next.js sample app with styled components does not load correctly. 

```
ERROR in ****/xpto/apps/frontend/pages/index.tsx(147,10):
147:10 Cannot find name 'NxLogo'.
    145 |     <StyledApp>
    146 |       <header className="flex">
  > 147 |         <NxLogo alt="" width="75" height="50" />
        |          ^
    148 |         <h1>
    149 |           Welcome to frontend! [{environment.production ? 'PROD' : 'DEV'}]
    150 |         </h1>
```

![image](https://user-images.githubusercontent.com/2605696/74604276-29922380-50b4-11ea-88d6-2d67364513fc.png)

### Steps to Reproduce

```
npx --ignore-existing create-nx-workspace xpto
```
Select:
 - an empty workspace
 - Nx Cli

```
cd xpto
npm install --save-dev @nrwl/next
nx g @nrwl/next:app frontend
```
Select: 
- styled-components

```
nx serve frontend
```

 
### Context
Nx report:
  @nrwl/angular : Not Found
  @nrwl/cli : 9.0.0
  @nrwl/cypress : 9.0.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.0.0
  @nrwl/linter : 9.0.0
  @nrwl/nest : Not Found
  @nrwl/next : 9.0.0
  @nrwl/node : Not Found
  @nrwl/react : 9.0.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.0.0
  @nrwl/web : 9.0.0
  @nrwl/workspace : 9.0.0
  typescript : 3.7.5

## Other

Adding these imports to apps/frontend/pages/index.tsx solves the issue.

```
import { ReactComponent as NxLogo } from '../assets/nx-logo-white.svg';
import { environment } from '../environments/environment';
```

![image](https://user-images.githubusercontent.com/2605696/74604355-29465800-50b5-11ea-9b0f-c8e81c5f8155.png)

Seems that the issue is in the template file: 

https://github.com/nrwl/nx/blob/c4ea49c3c672056d627743064fb3d02ce4f60bd1/packages/next/src/schematics/application/files/pages/__fileName__.tsx__tmpl__#L11

**Comment by jaysoo** [comment]
Ah yes, there is an import missing. We'll patch this up.

**Comment by jdpearce** [comment]
Sorry, my fault. I saw this at the weekend and haven't had time to fix it yet. 😔
