### ISSUE TITLE
Creating a new Angular 9 project from an empty workspace gives errors

### ISSUE THREAD

**Issue by reinvanleirsberghe** [nrwl/nx#2500]
# Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior
Install and run Angular 9 application after creating an empty workspace.

## Current Behavior
App is not running due to errors

## Failure Information (for bugs)
<img width="857" alt="Screenshot 2020-02-17 at 16 44 59" src="https://user-images.githubusercontent.com/4301574/74668130-dea40900-51a4-11ea-82cb-78b131e44267.png">

### Steps to Reproduce
Create a new **empty** workspace.
Use Angular CLI.
Add a new angular 9 application:

```
npm install --save-dev @nrwl/angular
ng g @nrwl/angular:application nxAngular
```

Run Angular 9 application
`ng serve nx-angular`

**Comment by vsavkin** [comment]
@reinvanleirsberghe  Thank you for submitting the issue. Could you provide a link with a repro?

**Comment by reinvanleirsberghe** [comment]
Can you be more specific what you need :)

**Comment by vsavkin** [comment]
@reinvanleirsberghe sorry, I meant a link to a github repository with an empty workspace you created.

**Comment by brandonroberts** [comment]
I ran through the repro steps with latest release and didn't receive this error. If you're still having issues, please re-open this one. Thanks
