### ISSUE TITLE
Add documentation on filtering projects by tag in `nx show projects`

### ISSUE THREAD

**Issue by terrymun** [nrwl/nx#25062]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/nx-api/nx/documents/show#projects

### Additional context or description

I had a need recently where I want to retrieve an array of projects that are filtered by a specific tag due to some business requirements. There does not seem to be any documentation related to this, and it was only [asking on the Discord forum](https://discord.com/channels/1143497901675401286/1242094364302508052/1242094364302508052) where somebody pointed me in the right direction:

```bash
# Get all projects with the tag "scope:util"
nx show projects -p tag:scope:util

# Get all projects with the tag "scope:util" or "type:ui"
nx show projects -p tag:scope:util tag:type:ui # With space delimiter
nx show projects -p tag:scope:util,tag:type:ui # With comma delimiter
```

**Comment by Hotell** [comment]
yeah the `-p` flag supports the same capabilities as within `run-many` commands.

there are some inconsistencies though that needs unification, see https://github.com/nrwl/nx/discussions/26901#discussioncomment-10157758
