### ISSUE TITLE
Any plans to support loading Apps of other frameworks?

### ISSUE THREAD

**Issue by a5hik** [nrwl/nx#251]
Hi Is there any plans to support or is it feasible today to mix Apps of other frameworks (React, Vue) as part of this platform?

I have an Enterprise UI platform composed of several Angular Apps, and there are quite a few Apps that uses React, Vue etc.. Is there a way to bring those in to the platform?

**Comment by jeffbcross** [comment]
As of right now, we don't have plans for first-class support for other frameworks, though this is something that has come up before. Folks could certainly bring different apps into the same repository, but would need to wire up separate build steps for non-Angular packages. And we're generally limited by Angular CLI in how flexible we can be with how projects are built.

Do you have ideas on specific things you'd like to see Nx do?

**Comment by a5hik** [comment]
I would like to see nx support the other apps at build and deploy level(not necessarily to support the CLI commands) and loading lazy routes of other frameworks as well. 
Component interaction is the next thing (may be this the frameworks itself needs to support)..

**Comment by vsavkin** [comment]
These are really good use case. Unfortunately, until the CLI becomes more flexible, we won't be able to implement them in Nx. Having said that, you can override the `npm run build` script to implement the use cases yourself.

Closing this because there are no plans to support this in the near future.

**Comment by mcblum** [comment]
@a5hik @vsavkin at the moment the best way I've found to do this is to use our own build scripts that go through build --> test --> e2e --> deploy but in different sections. It looks for Angular apps in angular.json and then all other types of apps are defined in a separate config. Each config for the separate type of app specifies what it's supposed to do to build. It's not the most elegant, but it's working for Angular + React.
