### ISSUE TITLE
Skip build on failure

### ISSUE THREAD

**Issue by hoang-innomizetech** [nrwl/nx#2514]
hi everyone, 

I am trying to figure out whether we have an option that we can stop/skill build on any project? 

For example, when I run this command `nx affected:build --prod --exclude cicd --all` I want to stop if there is an error occur.

**Comment by vsavkin** [comment]
Sorry. Could you be a bit more specific? Why are you excluding CICD above?

**Comment by hoang-innomizetech** [comment]
@vsavkin Sorry for the unclear issue. We are excluding the CICD project because we don't want to build it, we don't want to deploy or build that app per commit. 

The purpose of the skip build on failure option is to reduce the time that our CI pipeline runs, we actually don't want to continue building others if there a project cannot be built. I know that the affected:build command runs multiple builds at a time (parallel), is that possible to terminate others if a project failed?
