### ISSUE TITLE
[BUG] React app not compiles in angular-nest workspace

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#2523]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

React apps compiles successfully in a workspace with angular-nest preset

## Current Behavior

React apps not compiles

## Failure Information (for bugs)

```
Entrypoint main = runtime.js runtime.js.map vendor.js vendor.js.map main.js main.js.map
Entrypoint polyfills = runtime.js runtime.js.map polyfills.js polyfills.js.map
Entrypoint styles = runtime.js runtime.js.map styles.js styles.js.map
chunk {main} main.js, main.js.map (main) 350 KiB ={runtime}= ={vendor}= [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 566 KiB ={runtime}= [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 0 bytes ={main}= ={polyfills}= ={styles}= ={vendor}= [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 336 KiB ={runtime}= [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 1.16 MiB ={main}= ={runtime}= [initial] [rendered] split chunk (cache group: vendor) (name: vendor)

ERROR in ./styles.scss (/Users/gperdomor/Downloads/platform/node_modules/@nrwl/web/src/utils/third-party/cli-files/plugins/raw-css-loader.js!/Users/gperdomor/Downloads/platform/node_modules/postcss-loader/src??embedded!/Users/gperdomor/Downloads/platform/node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-3!./styles.scss)
Module build failed (from /Users/gperdomor/Downloads/platform/node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'includePaths'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/Users/gperdomor/Downloads/platform/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:85:11)
    at Object.loader (/Users/gperdomor/Downloads/platform/node_modules/sass-loader/dist/index.js:36:28)

ERROR in ./app/app.scss (/Users/gperdomor/Downloads/platform/node_modules/postcss-loader/src??embedded!/Users/gperdomor/Downloads/platform/node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-2-2!./app/app.scss)
Module build failed (from /Users/gperdomor/Downloads/platform/node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'includePaths'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/Users/gperdomor/Downloads/platform/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:85:11)
    at Object.loader (/Users/gperdomor/Downloads/platform/node_modules/sass-loader/dist/index.js:36:28)
ℹ ｢wdm｣: Failed to compile.
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a workspace with angular-nest preset
2. Run `nom i --save-dev @nrwl/react`
3. Create a react application
4. Run `nx serve your-react-app`

### Context

NX  Report complete - copy this into the issue template

  @nrwl/angular : 9.0.2
  @nrwl/cli : 9.0.2
  @nrwl/cypress : 9.0.2
  @nrwl/eslint-plugin-nx : 9.0.2
  @nrwl/express : Not Found
  @nrwl/jest : 9.0.2
  @nrwl/linter : 9.0.2
  @nrwl/nest : 9.0.2
  @nrwl/next : Not Found
  @nrwl/node : 9.0.2
  @nrwl/react : 9.0.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.0.2
  @nrwl/web : 9.0.2
  @nrwl/workspace : 9.0.2
  typescript : 3.7.5

**Comment by jaysoo** [comment]
This was due to a mismatch between sass-loader used by react and angular apps. This has been fixed as of 9.3.
