### ISSUE TITLE
Error migrating from 8.11.1

### ISSUE THREAD

**Issue by Sidewinder1138** [nrwl/nx#2528]
I attempted to run `nx migrate @nrwl/workspace`, on my existing 8.11.1 workspace. I get this error:

`Command failed: npm install @nrwl/workspace@@nrwl/workspace --prefix=/var/folders/zq/_f7nkq1n1cn55xp28hsrpt280000gp/T/tmp-753684xEd2ExAgLT1`

I am concerned by the `@nrwl/workspace@@nrwl/workspace` part in there, seems really odd, why is that repeating? Is that some kind of odd npm syntax I'm not aware of?

I tried what the tool suggests, which is to dev install the latest CLI and then try again, but I have the same problem. I'm pretty stumped. Any help greatly appreciated.

**System:**
MacOS 10.15.2 (Catalina)
Node v12.13.1
NPM v6.13.7

**nx report:**
```
  @nrwl/angular : 8.11.1
  @nrwl/cli : 8.11.1
  @nrwl/cypress : 8.11.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.11.1
  @nrwl/linter : 8.11.1
  @nrwl/nest : 8.11.1
  @nrwl/next : Not Found
  @nrwl/node : 8.11.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.11.1
  @nrwl/web : Not Found
  @nrwl/workspace : 8.11.1
  typescript : 3.5.3
```

**Comment by vsavkin** [comment]
could you try: 

```
yarn add @nrwl/workspace@8.12.8
```

And then

```
nx migrate @nrwl/workspace@8.12.8 --from="@nrwl/workspace@8.11.1"
```

**Comment by Sidewinder1138** [comment]
I tried and still got a similar error:

`The migrate command failed. Try the following to migrate your workspace:
> npm install --save-dev @nrwl/workspace@latest
> nx migrate @nrwl/workspace@@nrwl/workspace@8.12.8 --from="@nrwl/workspace@8.12.8"
This will use the newest version of the migrate functionality, which might have your issue resolved.
----------------------------------------------------------------------------------------------------
Command failed: npm install @nrwl/workspace@@nrwl/workspace@8.12.8 --prefix=/tmp/tmp-91017FKWhXVyFbW6
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@nrwl/workspace@8.12.8" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chris/.npm/_logs/2020-02-27T07_15_37_469Z-debug.log

/home/chris/work/nova/nova/node_modules/@nrwl/workspace/node_modules/yargs/yargs.js:1109
      else throw err
           ^

Error: Command failed: ./node_modules/.bin/tao migrate @nrwl/workspace@8.12.8 --from=@nrwl/workspace@8.11.1
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at Object.handler (/home/chris/work/nova/nova/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:76:21)
    at Object.runCommand (/home/chris/work/nova/nova/node_modules/@nrwl/workspace/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/chris/work/nova/nova/node_modules/@nrwl/workspace/node_modules/yargs/yargs.js:1022:30)
    at Object.get [as argv] (/home/chris/work/nova/nova/node_modules/@nrwl/workspace/node_modules/yargs/yargs.js:965:21)
    at Object.initLocal (/home/chris/work/nova/nova/node_modules/@nrwl/cli/lib/init-local.js:20:79)
    at Object.<anonymous> (/home/chris/work/nova/nova/node_modules/@nrwl/cli/bin/nx.js:12:18)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 9101,
  stdout: null,
  stderr: null
`

**Comment by Sidewinder1138** [comment]
I'm trying to at least come up with a workaround so I'm no blocked. I'm considering creating a brand new workspace at the latest version, and then somehow manually migrating in my project code... as awful as that may be (maybe not so bad? never tried it...). Can anyone think of a less drastic workaround? :)

**Comment by Tre665** [comment]
@Sidewinder1138 I had a similar problem some time ago. My problem was, that I hadn‘t installed the tao package before the upgrade. What worked for me was to install it as a dev dependency and then rerun the migrate process again.

**Comment by Sidewinder1138** [comment]
Thanks @Tre665 , I tried that but still got the same errors.

**Comment by yaroslavya** [comment]
Is there any update on this? @Sidewinder1138, did you manage to find a workaround?

**Comment by rlmcneary2** [comment]
In case anyone gets here via search looking for an answer I've been able to migrate from 8.11.1 by upgrading two packages:

```bash
yarn upgrade @nrwl/cli@^9.0.0 @nrwl/workspace@^9.0.0
```

It appears that the `cli` package (or a dependency) was generating malformed npm commands which failed. Error messages suggest upgrading `workspace` but I found that I needed to do `cli` as well.

**Comment by FrozenPandaz** [comment]
Is anybody still encountering this issue? If so, please provide a repro if possible.

Also check out this issue for more things to try when migrating Nx: https://github.com/nrwl/nx/issues/4333
