### ISSUE TITLE
Buildable Angular libs should be generated with Ivy disabled

### ISSUE THREAD

**Issue by brandonroberts** [nrwl/nx#2529]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Please describe the behavior you are expecting

No warning is displayed when compiling a buildable library

## Current Behavior

What is the current behavior?

A warning that Ivy should not be enabled when compiling a buildable library is displayed 

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

1. npx create-nx-workspace@latest myossorg --preset=empty --cli=angular
2. ng add @nrwl/angular
3. ng g lib ng-lib --publishable
4. ng build ng-lib
5. Note the ivy warning

### Context

Please provide any relevant information about your setup:

- version of Nx used (_Please run `nx report` at the root of your workspace and copy the results here if you are using Nx 8.6.1 or greater_)
- 3rd-party libraries and their versions
- and most importantly - a use-case that fails

Nx 9.0.2

**A minimal reproduction scenario allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

Please include any relevant log snippets or files here.

## Other

Any other relevant information that will help us help you.

**Comment by juristr** [comment]
Running it with the `--prod` flag already solves the issue:

```
ng build ng-lib --prod
```

That uses the `tsconfig.lib.prod.json` which has Ivy disabled. Would you want to make production builds the default?

**Comment by alexanderPastornicky** [comment]
`ng build lib --prod` throws exception

An unhandled exception occurred: Configuration 'production' is not set in the workspace.

**Comment by juristr** [comment]
Oh, thanks for the heads up. We'll look into this

**Comment by brandonroberts** [comment]
This issue has been fixed
