### ISSUE TITLE
ng generate command doesn't create the routing files

### ISSUE THREAD

**Issue by olakara** [nrwl/nx#253]
I am trying to create an app or module with routing.. but when I issue `ng g app myapp --routing` or try to create a module with routing like `ng generate lib admin --routing` I don't see the routing module files created. 

I am currently running latest nx tools and here is my ng -v command:

![ng](https://user-images.githubusercontent.com/570905/35753970-217e60b0-087b-11e8-8377-bed01cc3f1aa.png)

**Comment by vsavkin** [comment]
Nx generates router configuration inline. So `ng g app myapp --routing` should result in something like this:

```
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';
import { BrowserModule } from '@angular/platform-browser';
import { NxModule } from '@nrwl/nx';
import { RouterModule } from '@angular/router';

@NgModule({
  imports: [BrowserModule, NxModule.forRoot(), RouterModule.forRoot([], { initialNavigation: 'enabled' })],
  declarations: [AppComponent],
  bootstrap: [AppComponent]
})
export class AppModule {}
``` 

I think that the CLI generating the router configuration in a separate file is unfortunate. Your components and providers (e.g., guards and resolvers) are configured in the module file. It makes sense to have the routes configured there as well.

**Comment by vorant94** [comment]
@vsavkin Is there some way to configure Nx to do as Angular CLI itself?
