### ISSUE TITLE
Is Ivy default view engine in action with nx 9.0.2

### ISSUE THREAD

**Issue by sameerinfodb** [nrwl/nx#2534]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [ X] I checked the documentation (nx.dev) and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

As we are using Angular 9.0.0 in Nx 9.0.2, Need to know if Ivy Rendering engine is set as default. Were can we find this setting in Nx 9.0.2.

### Context

Please provide any relevant information about your setup:
  @nrwl/angular : 9.0.2
  @nrwl/cli : 9.0.2
  @nrwl/cypress : 9.0.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.0.2
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.0.2
  @nrwl/web : Not Found
  @nrwl/workspace : 9.0.2
  typescript : 3.7.5

**Comment by yharaskrik** [comment]
Ivy view engine is determined by Angular itself not by Nx. If you are using angular v9+ then yes Ivy is turned on my default but you can turn it off in by setting theses option in your tsconfig

```
"angularCompilerOptions": {
    "enableIvy": false
  }
```

as seen here under [Opting out of Ivy](https://angular.io/guide/ivy)

**Comment by juristr** [comment]
Thx Jay for answering. Closing the issue. If there are any further issues or questions, feel free to create a new one 🙂
