### ISSUE TITLE
React & Angular - Add CSS Modules for Stylus, SCSS/SASS, LESS

### ISSUE THREAD

**Issue by TheAifam5** [nrwl/nx#2539]
# Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Support for CSS Modules, not only for React but also for Angular.

## Current Behavior

NX currently only support `.module.css` but does not `.module.styl`, `.module.scss`, `.module.less`, `.module.sass`.

## Other

I see on WebPack page that LESS has currently some problems with CSS Modules, but looks like the thread is solved?. I made a simple `webpack.config.js` for LESS, as a workaround for now, nothing fancy but does the job:
```
const _ = require('lodash');
const getConfig = require('@nrwl/react/plugins/webpack');
const cssModuleRegex = /\.module\.less$/;

module.exports = config => {
  config = getConfig(config);

  config.module.rules.forEach((rule, idx) => {
    // Find rule tests for CSS.
    // Then make sure it excludes .module.css files.
    if (rule.test.test('foo.less')) {
      rule.exclude = rule.exclude
        ? Array.isArray(rule.exclude)
          ? [...rule.exclude, cssModuleRegex]
          : [rule.exclude, cssModuleRegex]
        : cssModuleRegex;
    }
  });

  const globalRule = config.module.rules.find(r => r.test.test('test.less'));
  const lessRule = {
    ..._.cloneDeep(globalRule.oneOf.find(r => r.test.test('test.less'))),
    test: /\.module\.less$/
  };
  delete lessRule.exclude;
  // just add between 'style-loader' and 'postcss-loader'
  lessRule.use.splice(
    1,
    0,
    { loader: 'css-modules-typescript-loader' },
    { loader: 'css-loader', options: { modules: true, importLoaders: 1 } }
  );
  globalRule.oneOf.unshift(lessRule);
  delete globalRule.exclude;

  return config;
};
```

**Comment by FrozenPandaz** [comment]
Nx uses the Angular CLI builders to build Angular apps. CSS Modules are not supported by default in the Angular CLI.

You can, however, use this custom builder to modify the webpack config:

https://www.npmjs.com/package/@angular-builders/custom-webpack

**Comment by FrozenPandaz** [comment]
I don't know if we will add this feature so I'm going to close for now. Please post if you are able to get css modules with angular working with the custom-webpack builder.
