### ISSUE TITLE
Disable format dist folder

### ISSUE THREAD

**Issue by pacocom** [nrwl/nx#2541]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites
No prerequisites.

- [X ] I am running the latest version
- [ X] I checked the documentation (nx.dev) and found no answer
- [ X] I checked to make sure that this issue has not already been filed
- [ X] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

![image](https://user-images.githubusercontent.com/7735329/75140723-c75aa380-56ef-11ea-83c9-e4c3435b4766.png)

![image](https://user-images.githubusercontent.com/7735329/75140415-28ce4280-56ef-11ea-8158-6046f6e59612.png)

## Expected Behavior
Does not format **dist** folder.

![image](https://user-images.githubusercontent.com/7735329/75140259-cf661380-56ee-11ea-89fd-61aae04a2bfe.png)

## Current Behavior
Now **dist** folder is formatted.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

1. ng build
2. npm run format

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context

Please provide any relevant information about your setup:

- version of Nx used (_Please run `nx report` at the root of your workspace and copy the results here if you are using Nx 8.6.1 or greater_)
- 3rd-party libraries and their versions
- and most importantly - a use-case that fails

**A minimal reproduction scenario allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

Please include any relevant log snippets or files here.

## Other

Any other relevant information that will help us help you.

**Comment by vsavkin** [comment]
@pacocom could you provide a link to a github repo with a repro?

**Comment by FrozenPandaz** [comment]
This should be fixed by #2493.
