### ISSUE TITLE
Nx do not use work space configurations

### ISSUE THREAD

**Issue by bennymeg** [nrwl/nx#2552]
- [ x ] I am running the latest version
- [ x ] I checked the documentation (nx.dev) and found no answer
- [ x ] I checked to make sure that this issue has not already been filed
- [ x ] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior
Nx should use the configuration the are defined in `[angular/worspace].json` file:
`projects/[name]/architect/build/configurations/[productions (i.e.)]`

## Current Behavior
Nx only uses the default configuration even if other configuration is used (i.e. production).

### Steps to Reproduce

1. npm init nx-workspace (i.e. express-react)
2. add to the react app the following lines:
```js
import { environment } from './environments/environment';

console.log('production:', environment.production);
```
3. build a project twice: in development mode and in production mode. Both of the invocations should print false (due to the fact that fileReplacment object from the production configuration did not been used, the same behavior happen to all the fields in the configuration). 

### Context
- versions of Nx used: 8.9.0, 9.0.3
- 3rd-party libraries and their versions: none
- I'm using angular console to build / serve the projects

## Other

I've done some testings, it seems the the `configuration` field in the Webpack `config` variable is always empty.

In build.impl.ts > run(): `let config = getNodeWebpackConfig(options);`
```js
config = {
  option: {
    ...
  },
  configuration: {} // <- empty
}
```

**Comment by juristr** [comment]
Hi @bennymeg.

I just gave this a try, adding the code you mentioned into the react app's `main.tsx` as well as in the express app's `main.ts` file.

When running in dev mode, it correctly prints `false`, when running in `production` mode, it correctly prints `true`.

For the react app I tried both

```
$ nx build --prod
```

and then serving it with `http-server` from dist. Also `nx serve --configuration=production` works.

Also, removing the fileReplacement option in the `workspace.json` of the react project's production configuration results in the correct behavior: now in dev & prod I get `false` being printed out.

Can you provide more details or a reproduction repository?

**Comment by bennymeg** [comment]
You are right, I think I found the issue.

It seems the the issue is related to `angular console`, selecting a configuration only affects the option that are visible in the UI but not in the command it self.

I.e.: when I select the production configuration it invokes `ng build name --extractLicenses --optimization` and omits the `--prod` parameter which cause what I describe above. If I invoke `ng build name --extractLicenses --optimization --prod` manually it works as expected.
I hope this is still the right place for that issue.
