### ISSUE TITLE
[Feature Request] (react) gzip production build

### ISSUE THREAD

**Issue by czaplej** [nrwl/nx#2557]
I haven't find in source code that  react production builds has gziped files. If it will be possible, that would be great. (I could do this if it doesn't hide the problems you already know about)

rollup has a plugin:
[https://github.com/kryops/rollup-plugin-gzip](https://github.com/kryops/rollup-plugin-gzip)

webpack has a plugin: 
[https://webpack.js.org/loaders/gzip-loader/](https://webpack.js.org/loaders/gzip-loader/)

**Comment by ankitr-nalkv** [comment]
A similar feature for Angular would be great as well
