### ISSUE TITLE
How to read affected apps into an array variable in shell script?

### ISSUE THREAD

**Issue by dereklin** [nrwl/nx#2558]
I used to be able to read the affected apps into a variable in shell script like this:

```
apps=$(./node_modules/.bin/nx affected:apps --base="$(git merge-base "${remoteMaster}" HEAD)" --head=HEAD)
```

With the new version, the affected:apps is printing nicely formatted text in the console, but my apps variable is blank.

What is the new way of reading the affected apps into an array variable?

**Comment by juristr** [comment]
Hi, you should be able to pass the `--plain` flag. This would give you a space separated list of apps.

Feel free to reopen the issue if this doesn't help. 🙂
