### ISSUE TITLE
Missing docs for angular-cli version logic. [.angular_cli165.tgz] [.angular_cli.tgz]

### ISSUE THREAD

**Issue by ph55** [nrwl/nx#256]
After creating new workspace, angular cli added to dev dependencies as following:
```
"devDependencies": {
  "@angular/cli": "file:.angular_cli165.tgz",
  ...
```
And file `.angular_cli165.tgz` added to root directory.

So I assume that:
* Current NX version depends on this specific angular-cli version.
* Updating angular-cli to latest version is discouraged since it could break NX functionality.

Some info about this in docs (free course) would be helpful.

**Comment by AustinMatherne** [comment]
It's in the [FAQ](https://github.com/nrwl/nx/wiki/FAQ). Something in the docs would be helpful though.

**Comment by ph55** [comment]
@AustinMatherne thanks. FAQ is enough I guess. Hope this issue will help to find info as well.
