### ISSUE TITLE
@nrwl/jest schema.json defines a --coverage option that does not seem to affect coverage output

### ISSUE THREAD

**Issue by dotDeeka** [nrwl/nx#2564]
## Expected Behavior
The schema.json for the jest builder defines an option called `--coverage` https://github.com/nrwl/nx/blob/master/packages/jest/src/builders/jest/schema.json#L110
```
"coverage": {
      "description": "Indicates that test coverage information should be collected and reported in the output. This option is also aliased by --collectCoverage. (https://jestjs.io/docs/en/cli#coverage)",
      "type": "boolean"
    }
```
I would expect running `npx nx test <app-name> --coverage=false` would not generate coverage output, and `npx nx test <app-name> --coverage=true` would generate coverage output.

## Current Behavior
The `--coverage` flag seems to be ignored when passed on the command line, and whatever is in the jest.confg file for coverage settings is used

### Steps to Reproduce
I have created a minimal repo to reproduce the issue https://github.com/dotDeeka/nx-coverage-repro

1. clone the git repo
2. npm install
3. run npx nx test example-app --coverage=true
The coverage reporter is set to text in the jest config, but there is no coverage report printed to the terminal

## Other

I have done a bit of preliminary investigation and I discovered that there is another, similar option `--codeCoverage` and setting this to true or false works as expected. Looking at the implementation (https://github.com/nrwl/nx/blob/master/packages/jest/src/builders/jest/jest.impl.ts) it appears that the --coverage option isn't actually passed to jest at all, unless I'm reading it wrong, or `--coverage` is meant for something else and I'm misunderstanding.

**Comment by dotDeeka** [comment]
Could this be fixed with something as simple as changing this line (https://github.com/nrwl/nx/blob/master/packages/jest/src/builders/jest/jest.impl.ts#L95) to
```
coverage: options.codeCoverage ?? options.coverage,
```

**Comment by vsavkin** [comment]
It's a bug. The `codeCoverage` option is used to indicate the coverage. I'd delete the coverage option and leave only `codeCoverage`. Would you like to submit a PR?

**Comment by dotDeeka** [comment]
Sure, I would be glad to
