### ISSUE TITLE
How to resolve "Circular dependency" in NRWL

### ISSUE THREAD

**Issue by kswaroop** [nrwl/nx#2570]
I am getting the below LINT error

"Circular dependency between "A(lib)" and "B(lib)" detected (nx-enforce-module-boundaries) tslint error"
Most of the issues are coming when a Service from one Library is used(imported) in another lib.

Can you please help how to resolve this issue

**Comment by czaplej** [comment]
U can't doing something like:
`
//LIB A
import libB from 'LIB_B'

//LIB B
import libA from 'LIB_A'
`

**Comment by kswaroop** [comment]
Thanks, Yeah I am using in the same way, I have created a service 'LIBC_XYZ which has the methods and I am using in other libraries, but still getting an error

**Comment by kswaroop** [comment]
Thanks, Yeah I am using in the same way, I have created a service 'LIBC_XYZ which has the methods and I am using in other libraries, but still getting an error

**Comment by FrozenPandaz** [comment]
If you use `nx dep-graph` you should be able to see the circular dependency.

What @czaplej mentioned about creating a 3rd library works a lot of the time.

I wrote an initial doc in the wiki on resolving circular dependencies:

https://github.com/nrwl/nx/wiki/Resolving-Circular-Dependencies

Let me know if it helps.

**Comment by kkuriata** [comment]
Anyway, something happened that NX started posting linter errors? I didn't change anything in my project, "only" updated from 8 to 9 and linter started throwing errors (same `nx-enforce-module-boundaries` settings)

**Comment by czaplej** [comment]
I have similar errors that @kkuriata said. I have use 9.0.4 version of nx

**Comment by cngarkar** [comment]
I think @kkuriata is right. I'm also seeing the circular dependency issues after upgrading to 9.

**Comment by kswaroop** [comment]
> Thanks, Yeah I am using in the same way, I have created a service 'LIB_XYZ which has the methods and I am using in other libraries, but still getting an error

I have manually updated the code by removing which has a circular dependency, It works fine now, Actually, all libraries are interrelated, so if one has dependency most of the other related are also failing

**Comment by snebjorn** [comment]
I getting false positives of `nx-enforce-module-boundaries`

I have this graph

![image](https://user-images.githubusercontent.com/1266245/76663309-e034d700-6580-11ea-8772-839c4f4c9f01.png)

Where each of the akita-ng-libraries have akita as a `peerDependency`

I also have a demo app which uses all of the above (remember peerDependencies) which causes the graph to look like this

![image](https://user-images.githubusercontent.com/1266245/76663511-79fc8400-6581-11ea-93db-9722eed08ecb.png)

and now I'm getting spammed with false `nx-enforce-module-boundaries`

> Circular dependency between "akita-ng-entity-service" and "akita" detected
> Circular dependency between "akita-ng-forms-manager" and "akita" detected
> etc

please advice

**Comment by snebjorn** [comment]
Nevermind, I missed the arrow going from akita to the app :/

Now I'm not getting any `nx-enforce-module-boundaries` 

![image](https://user-images.githubusercontent.com/1266245/76663861-c09eae00-6582-11ea-8022-53ba38e8e761.png)

**Comment by dsebastien** [comment]
I'm facing difficulties understanding how to best structure my NX workspace in apps and libs to optimize build times and benefit from caching, considering an Angular + NGRX app.

As the starting point, I had one "web" app, composed of many major "features", each with its own (lazy-loaded) Angular module. Those modules were loaded lazily through the router, but also eagerly when a dependent Angular module needed it (e.g., if module X needs module Y, it has it in its imports).

As part of my current refactoring, I've extracted most of those features in separate libraries: one per major feature of the app, which I load lazily when needed.

Now, after fixing compilation issues, I remain with circular dependencies. My question is: what is your experience with splitting inter-dependent lazy-loaded Angular modules and what would be your recommendation?

Do you recommend splitting each feature in multiple libs (e.g., feature-x-core, feature-x-store, feature-x-dumb-components, feature-x-smart-components, ...)?

I've given this some thought and I don't see a clear path forward. For instance, if I consider the NGRX selectors of feature-x, then I can see that those rely on state types and selectors from feature-y.

One idea that I still have is extracting some parts (e.g., reducers & selectors) of the store for each feature and putting those in a shared "core" lib, but I'd still remain with the Angular module imports. Or should I just ignore the lint error in that case?

In our case I feel like keeping all of those features in the same NX lib is detrimental as it represents > 80% of the whole app.

**Comment by xmlking** [comment]
Hi difficult to find why I have circular dependency! don't see any dependency from `core` -> `webapp`  in the code 
https://github.com/xmlking/yeti

![image](https://user-images.githubusercontent.com/627951/77711427-3b59c700-6f8e-11ea-99ad-6fe918a0eabb.png)

**Comment by snebjorn** [comment]
@xmlking 
![image](https://user-images.githubusercontent.com/1266245/77731620-882bb500-7003-11ea-94f0-7ea9cab9482f.png)

**Comment by FrozenPandaz** [comment]
>  something happened that NX started posting linter errors? I didn't change anything in my project, "only" updated from 8 to 9 and linter started throwing circular dep errors

Yes, Nx is able to resolve more dependencies in 9 than before in 8. As a result, a dependency could have been resolved that now causes a circular dependency. These are valid dependencies.

For example,

Relative dependencies are now a resolved dependency even though they are not recommended.

```ts
import { } from '../../libs/libA/src'; // Is now a dependency
```

**Comment by FrozenPandaz** [comment]
I'm going to close this issue as I've started a guide.

https://github.com/nrwl/nx/wiki/Resolving-Circular-Dependencies

Please open a new issue if that guide does not cover a method for resolving circular dependencies so we can add it.

**Comment by Abdallah-khalil** [comment]
@FrozenPandaz 
I'm currently having a situation where i'm using the environment.ts file from my app into more than one library and those libraries are used in this app . which was going fine with angular 8 , but now it's showing a circular dep error . Is there a way to get a round that ?

**Comment by kkuriata** [comment]
@Abdallah-khalil You should move your environment files into some common library that will be imported by all the apps you need. You can then use fileReplacements in angular.json/workspace.json to replace specific environment for chosen build. Unfortunately when you want to use fileReplacements with default dev build (`ng serve`), then you need to point the configuration: `ng serve --configuration=serve` (@FrozenPandaz not sure if it is a bug or it is inteded).

For example, when I have two projects: `project1` and `project2`. And one lib `core`.

```
libs/core
  /environments
    /project1
      environment.serve.ts
      environment.prod.ts
    /project2
      environment.serve.ts
      environment.prod.ts
  environment.ts // this one will be replaced by any from above
```
Then I use `angular.json` to set file replacements inside `serve` configuration to have it by default when I develop new features. Unfortunately in this case it is not enough as I mentioned. Even when I specify file replacement for both projects, it won't work without `--configuration=serve` flag. Because `serve` is default `ng serve` configuration, I think it is a bug, but not sure.

**Comment by lookapanda** [comment]
There's also the issue when using something like `typeorm`. Database entities naturally can have circular dependencies where one entity has a OneToMany relation to another entity which itself has a ManyToOne relation to the prior entity. This causes a circular dependency which then causes errors. :/ Is there any way to solve this?

**Comment by cngarkar** [comment]
I updated the nx workspace recently, and I'm no longer seeing the circular dep errors. Can someone from nx team confirm if this is fixed or still a known issue?

**Comment by charlex** [comment]
@Ponjimon That's a very good point, and one that is keeping me (wrongly or rightly) from having multiple modules for my TypeORM entities.

**Comment by adamm-monek** [comment]
Another possible scenario, which I have encountered, is when using NgRX Router Store, like in https://blog.nrwl.io/using-ngrx-4-to-manage-state-in-angular-applications-64e7a1f84b7b

E.g. 
2 libs, a UI lib and a store lib.
you set up effects in the store lib to respond to navigation to a component in the UI lib.
a component in the UI lib calls the store facade to retrieve some data that it needs.

Thus a circular dependency.
In Victor's post the components which are the subject of navigation are in the same app as the effects, etc, as it is a simple example.

**Comment by then3rdman** [comment]
> Another possible scenario, which I have encountered, is when using NgRX Router Store, like in https://blog.nrwl.io/using-ngrx-4-to-manage-state-in-angular-applications-64e7a1f84b7b
> 
> E.g.
> 2 libs, a UI lib and a store lib.
> you set up effects in the store lib to respond to navigation to a component in the UI lib.
> a component in the UI lib calls the store facade to retrieve some data that it needs.
> 
> Thus a circular dependency.
> In Victor's post the components which are the subject of navigation are in the same app as the effects, etc, as it is a simple example.

I have run into this exact situation! Slightly less complex however.

I am using a lib that container my auth store, its being used in the login feature lib. I want to use the navigated helper to generate a cookie when the login component is loaded however this is a direct circular dependancy. 

I see no way around this.... that is if i am going to the navigated helper.....

**Comment by nhhockeyplayer** [comment]
so it sounds like some of these circular dependencies are just saying 

HE... he is using some stuff from HER
and
HER is using some stuff from HE 

but as long as it executes fine there should be no problem

unless these circular dependencies are warning of an infinite loop?

I think the definition of circular dependency needs to be revisited

maybe these are just BIDIRECTIONAL ASSOCIATIONS which may be harmless

and a REAL circular dependency means INFINITE LOOP imminent

any thoughts ?

can someone elaborate simply confirming somethings I noted here ?

**Comment by skopekreep** [comment]
Adding to what @ghost said, it seems that a circular dependency is unavoidable when using the navigation operator in an effect, if the component that the operator references is not in the same module (or lib) as the effect.

In my case, the component communicates exclusively with a facade in a data access lib to get its data. But after switching my effect to use the router as the source of truth as recommended in the article previously cited, the effect in the the data access lib references back to the component in the ui lib.  Guaranteed circular dependency.  Splitting apart data access libs from ui libs isn't an anti-pattern, but perhaps there is some nuance I'm not appreciating.

Any insights or best practices are welcome.  Thanks.

**Comment by nhhockeyplayer** [comment]
So would you hire a plumber to come into your home
and leave the pipes hemorrhaging and dripping leaking?
No one is talking to the core on this

It's bad enough we got asynchronous and overlap with race conditions and dead locks and I have had to trouble shoot those native database table ones from transaction demarcation + refCounts from high end multi protocol api servers used by the navy and fortune 500's... whose architect later sold and made his few million to those who dont 'really' know whats left lurking under the hood. I'd love to see some node.js atomic transactions and have not yet. Just de-coupled grouped dispatches.

what Im seeing here with grouped modules and lib sharing is we can ONLY make a bland abstraction at the top via a small finite # of groups

everything underneath still ends up being shared in an eventual tangle unless ... maybe large horizontal columns/groups/subgroups
and large scale codebase growth does not distribute in favor even after grouping
are we dealing with an eventual quagmire?

Maybe victor can elaborate?

But the guy who made his millions knew and bailed... he was the #1 code implementer & architect

**Comment by JonesHong** [comment]
It work for me.

Same issue!!
![image](https://user-images.githubusercontent.com/22835128/194715628-07028f50-f707-4841-b9e7-f5645dcd261c.png)
```sh
nx dep-graph
```
![image](https://user-images.githubusercontent.com/22835128/194715705-589a7c49-affd-4c74-a8a2-bb055f12d749.png)

But if I add `"depndsOn":[]`
![image](https://user-images.githubusercontent.com/22835128/194715753-bfb9b182-50a4-4070-a5f7-e38125d25ce8.png)
It works
![image](https://user-images.githubusercontent.com/22835128/194715774-95e7d0ec-7cc8-48d9-9c96-0f17f1f1026d.png)

The graph is the sme.

It look like same problem at [#9085](https://github.com/nrwl/nx/issues/9085)
Good luck guys

**Comment by JonesHong** [comment]
I also try to move out the depends part.
Make Graph simple
![image](https://user-images.githubusercontent.com/22835128/194717005-04d2793c-3819-4be1-8c08-3e0dc2d74be0.png)

I build the ngrx-like store management with Angular and Nest.
File structor like this: 
![image](https://user-images.githubusercontent.com/22835128/194717131-05b8f632-3ea3-415b-ab5f-0c9de96f2366.png)
backend depends on  `@nestjs/common`
![image](https://user-images.githubusercontent.com/22835128/194717172-d138fcb4-f5fa-4e34-ad08-6f21be23f1b1.png)
frontend depends on `@angular/core`
![image](https://user-images.githubusercontent.com/22835128/194717202-eef01dd1-bd1b-4a65-abf4-46de8ed64689.png)

Becuse of those depends, Nx will become circular.
So I just move out those part for their own scope.
![image](https://user-images.githubusercontent.com/22835128/194717315-958f66f4-adea-4ebd-b77c-53f6d5537591.png)
backend
![image](https://user-images.githubusercontent.com/22835128/194717549-5e64d1b0-d1b4-4788-bedb-7eb247500887.png)
![image](https://user-images.githubusercontent.com/22835128/194717626-40af34dc-ea79-42d1-8259-2507e7a28df9.png)
frontend
![image](https://user-images.githubusercontent.com/22835128/194717562-a9ebe768-81ec-42bf-88e7-01d46750c583.png)
![image](https://user-images.githubusercontent.com/22835128/194717686-21818a5f-d123-4b84-9d15-86c1afb20494.png)

**Comment by JonesHong** [comment]
I had try this too, but not work.
![image](https://user-images.githubusercontent.com/22835128/194719276-666b0938-0d25-4999-a844-1d9857e735b2.png)
![image](https://user-images.githubusercontent.com/22835128/194719301-7953008b-0fe8-4bfa-8ebd-20a5c18f7049.png)

**Comment by jmeinlschmidt** [comment]
I was receiving false positive circular dep. error. Solution for me was to run `nx reset`. I think this suggestion might take part in the wiki as well https://github.com/nrwl/nx/wiki/Resolving-Circular-Dependencies, any opinion @FrozenPandaz?
