### ISSUE TITLE
[BUG] Nx NextJS Runtime config variables are "undefined" while running production build

### ISSUE THREAD

**Issue by suwigyarathore** [nrwl/nx#2572]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

In NextJs apps that is bootstrapped via NX NextJs schematics based on instructions specified [here](https://blog.nrwl.io/nx-now-supports-next-js-84ae3d0b2aed), the
**_publicRuntimeConfig_** variables specified in **_next.config.js_** should be available in **_getInitialProps_** during runtime both in production and dev mode as specified in orignal nextjs documentation [here](https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration).

Similar project bootstrapped via [create-next-app](https://nextjs.org/blog/create-next-app) works perfectly where **_publicRuntimeConfig_** variables specified in **_next.config.js_** are. available in **_getInitialProps_** during runtime both in production and dev mode.

## Current Behavior

Nextjs app that is created via Nx Nextjs schematics gives **_undefined_**   for **_publicRuntimeConfig_**  accessed in **_getInitialProps_** during runtime of production build but in development mode it works perfectly

**next.config.js**
`module.exports = {
  serverRuntimeConfig: {
    // Will only be available on the server side
    mySecret: 'secret',
    secondSecret: process.env.SECOND_SECRET // Pass through env variables
  },
  publicRuntimeConfig: {
    // Will be available on both server and client
    staticFolder: '/static'
  }
};`

**getInitialProps**
`
import getConfig from 'next/config';
const { publicRuntimeConfig } = getConfig();
...
Index.getInitialProps = async ctx => {
  console.log('I am here');
  console.log(publicRuntimeConfig.staticFolder); // Undefined when running prod build
  return {};
};`

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. clone [repo](https://github.com/suwigyarathore/nextjs-nx-runtime-config.git)
2. Change directory to code directory
3. run `npm install`
4. run `npm start tuskdesk`
5. Open [http://localhost:4200/](http://localhost:4200/) in your browser
6. You will see run time config variables consoled in terminal like below
![image](https://user-images.githubusercontent.com/20533539/75457975-6d6f0d80-597d-11ea-8f60-f2c095846b1c.png)
7. Now run `npm run build tuskdesk` to create a production build
8. Run a custom command `npm run start-prod:nextjs` In short it copies dist file to root and run next app (There could be a better way, I am not sure)
9.  Open [http://localhost:3000](http://localhost:3000) in browser 
10. You will see as contrast to previous output variables are consoled as **undefined** like below
![image](https://user-images.githubusercontent.com/20533539/75459857-005d7700-5981-11ea-9417-12dbc40d323b.png)

### Context

 **NX  Report**

`  @nrwl/angular : Not Found
  @nrwl/cli : 9.0.4
  @nrwl/cypress : 9.0.4
  @nrwl/eslint-plugin-nx : 9.0.4
  @nrwl/express : Not Found
  @nrwl/jest : 9.0.4
  @nrwl/linter : 9.0.4
  @nrwl/nest : Not Found
  @nrwl/next : 9.0.4
  @nrwl/node : Not Found
  @nrwl/react : 9.0.4
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.0.4
  @nrwl/web : 9.0.4
  @nrwl/workspace : 9.0.4
  typescript : 3.7.5`

## Other

As I tried to reproduce the issue in bare bone NextJs setup but it works perfectly there. To reproduce follow below steps

1. Clone [repo](https://github.com/suwigyarathore/nextjs-runtime-config)
2. Change directory to code directory
3. run `npm install`
4. For **_Dev Mode_** run `npm run dev` 
5. Go to [http://localhost:3000](http://localhost:3000) and you will see runtime variables in terminal like below 
![image](https://user-images.githubusercontent.com/20533539/75460749-22a3c480-5982-11ea-812b-55e9142f4374.png)
6. For **_Prod Mode_** run `npm run build` and `npm run start`
7. Go to [http://localhost:3000](http://localhost:3000) and you will see runtime variables in terminal like below 
![image](https://user-images.githubusercontent.com/20533539/75461407-0c4a3880-5983-11ea-8ba2-32b68dd27b56.png)

**Comment by suwigyarathore** [comment]
The issue is resolved. I was missing coping of **next.config.js** also while moving **dist** output to root.

**_Instead of this_**
`"start-prod:nextjs": "rm -rf .next && mv dist/apps/tuskdesk .next && node ./node_modules/.bin/next start"`

**_Do this_**
`"start-prod:nextjs": "rm -rf .next && mv dist/apps/tuskdesk .next && cp apps/tuskdesk/next.config.js next.config.js && node ./node_modules/.bin/next start"`

**_Suggestion_**
When **next.config.js** was missing while running the next start command, a descriptive error message could be helpful. Instead, it was using the default next.config with empty fields

**Comment by chasevida** [comment]
Ok, this was a total pain due to it kinda just failing silently. Took me a while to realise it was `NX` and not something wrong with the underlying `next/config` and build cycle. Thank you @suwigyarathore .

**Comment by chronark** [comment]
Just ran into this as well and spent a few hours trying to find the issue. Thanks @suwigyarathore
