### ISSUE TITLE
next.js build error on new workspace: can't find `node-sass`

### ISSUE THREAD

**Issue by rarmatei** [nrwl/nx#2574]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

## Expected Behavior

It should build/serve succesfully.

## Current Behavior

There's an error:

```
./pages/index.scss
Error: Cannot find module 'node-sass'
Require stack:
- ......./test2/node_modules/sass-loader/lib/loader.js
- ......./test2/node_modules/loader-runner/lib/loadLoader.js
- ......./test2/node_modules/loader-runner/lib/LoaderRunner.js
- ......./test2/node_modules/webpack/lib/NormalModule.js
- ......./test2/node_modules/webpack/lib/NormalModuleFactory.js
- ......./test2/node_modules/webpack/lib/Compiler.js
- ......./test2/node_modules/webpack/lib/webpack.js
- ......./test2/node_modules/next/dist/build/compiler.js
- ......./test2/node_modules/next/dist/build/index.js
- ......./test2/node_modules/@nrwl/next/src/builders/build/build.impl.js
- ......./test2/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- ......./test2/node_modules/@angular-devkit/architect/node/index.js
- ......./test2/node_modules/@nrwl/tao/src/commands/run.js
- ......./test2/node_modules/@nrwl/tao/index.js
- ......./test2/node_modules/@nrwl/cli/lib/init-local.js
- ......./test2/node_modules/@nrwl/cli/bin/nx.js
- /Users/raresmatei/.npm-global/lib/node_modules/@nrwl/cli/lib/init-global.js
- /Users/raresmatei/.npm-global/lib/node_modules/@nrwl/cli/bin/nx.js
```

### Steps to Reproduce

```bash
npx create-nx-workspace@latest repro-workspace ---> select next.js app
cd test1
nx build
```

`node-sass` doesn't exist under `node_modules`
If I do `yarn add node-sass` it works again.

### Context

Please provide any relevant information about your setup:

  @nrwl/angular : Not Found
  @nrwl/cli : 9.0.4
  @nrwl/cypress : 9.0.4
  @nrwl/eslint-plugin-nx : 9.0.4
  @nrwl/express : Not Found
  @nrwl/jest : 9.0.4
  @nrwl/linter : 9.0.4
  @nrwl/nest : Not Found
  @nrwl/next : 9.0.4
  @nrwl/node : Not Found
  @nrwl/react : 9.0.4
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.0.4
  @nrwl/web : 9.0.4
  @nrwl/workspace : 9.0.4
  typescript : 3.7.5

**Comment by EfstathiadisD** [comment]
This is an issue. Maybe `node-sass` wasn't added as a dependency when, you select `sass`style??  I can confirm it :)

**Comment by rarmatei** [comment]
> This is an issue. Maybe `node-sass` wasn't added as a dependency when, you select `sass`style?? I can confirm it :)

Thanks for confirming! I'm planning to have a look at this early next week!
