### ISSUE TITLE
[@nrwl/linter] Can we add different output formats for stdout and --outputFile?

### ISSUE THREAD

**Issue by jdpearce** [nrwl/nx#2575]
Currently if you provide a format (e.g. `checkstyle`) in the `lint` target options, this will define how the output is piped to stdout *and* how it is written to the `outputFile` if provided. This may not be the appropriate thing to do as any format other than `stylish` will be almost unreadable when we run `nx lint` at the command line.

**Comment by NotSoImportant** [comment]
fixed with https://github.com/nrwl/nx/pull/4755
