### ISSUE TITLE
Can not add postcss-normalize postcss plugin

### ISSUE THREAD

**Issue by mladen107** [nrwl/nx#2578]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

I expect that I can easily add postcss plugins using postcss.config.js

## Current Behavior

postcss.config.js is not picked up by postcss-loader since there is plugins section in loader rule created by postcssPluginCreator. This prevents postcss-loader to pick up config file. If postcss.config.js is complicate to support I suggesting including postcss-normalize plugin by default as create-react-app does.

**Comment by FrozenPandaz** [comment]
For now, you can modify your webpackConfig to include the plugin:

https://connect.nrwl.io/app/cookbook/4CjE7wgoOyYU3ri08GCAr7

If you have a working custom config, please share here so others can use it as well! 😄

@jaysoo would it make sense to add this to the default config?

Does this plugin include `normalize.css` by itself or will it noop if `normalize.css` is not imported by the user?

**Comment by ZachJW34** [comment]
Our company has accomplishes modifying Angular's webpack config to tweak some postcss plugins. One way is using `patch-package` and targeting `node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/styles.js`, but with access to the webpack config like @FrozenPandaz linked, you can do something similar to this:

```

**Comment by jaysoo** [comment]
Adding `postcss-normalize` is a good idea. The experience is a lot better if users didn't need to modify configuration too much.

We should make sure the generated stylesheet has `@import-normalize`. This wouldn't affect users using styled-components or emotion.
