### ISSUE TITLE
Do not add jest and cypress when unitTestRunner and e2eTestRunner are set to none

### ISSUE THREAD

**Issue by pandaniell** [nrwl/nx#2587]
After setting up a basic workspace https://nx.dev/react/fundamentals/build-full-stack-applications I would like to get rid of testing since I am not interested in it and I didn't get a prompt if I wanted to add it or not, is this possible?

It seems like even when doing `yarn nx g @nrwl/react:application --name web --unitTestRunner none --e2eTestRunner none`, testing dependencies are installed and jest files are generated in the root of the project

**Comment by vsavkin** [comment]
It's a bug. The project is set up without Jest and Cypress, but global files are still added.

**Comment by nikitad-lohika-tix** [comment]
@vsavkin also, why `@nrwl/angular` has the dependency on `@nrwl/cypress`, what if I do not want to use cypress for e2e? Currently I get it anyway. I think it is better to eliminate this dependency if possible

**Comment by pandaniell** [comment]
Thank you for looking into this, once the changes have been pushed, would you be able to comment the steps to completely remove it from an existing workspace?
