### ISSUE TITLE
Feature - NgRx Data library schematics

### ISSUE THREAD

**Issue by yharaskrik** [nrwl/nx#2589]
Would it be of interest to the Nx team if I were to work on some schematics to generate NgRx Data Entities and their corresponding services and functions?

My proposal would be to have a schematic that allows you to pass in an entity name and have the schematic generate you:

1. Data Service
2. entity metadata
3. Optionally any of the entity functions
4. Optionally Plural names
5. optinionally add the entity to the appEntityMetadata
6. Generate the entity itself or use a preexisting with import path flag

**Comment by vsavkin** [comment]
@brandonroberts what do you think?

**Comment by yharaskrik** [comment]
I just looked and realized that there are schematics in the NgRx platform repo for data already (albeit only for an entity with `id` and a service). So it may not may a ton of sense to reimplement that for Nx.

**Comment by brandonroberts** [comment]
@yharaskrik I agree that the schematics we have in the platform cover those things already.

**Comment by yharaskrik** [comment]
@brandonroberts From what I can tell they only support a basic entity with an id property, but I would like to provide functionality for the above list in my original comment, some might be a bit difficult but I think I will try and provide some of it and make a PR to @ngrx/platform instead of @nrwl/nx

**Comment by brandonroberts** [comment]
Sounds good. Just open an issue first and tag me.
