### ISSUE TITLE
Yarn audit fails after upgrading to 19.0.6

### ISSUE THREAD

**Issue by cpaul-mo** [nrwl/nx#25890]
### Current Behavior

| Critical    |  Deserialization Code Execution in js-yaml |
| :-------- | :------- |
| Package  | js-yaml     |
| Dependency of | lerna   |
| Path    | lerna > @lerna/create > nx > js-yam    |
| More info    | https://www.npmjs.com/advisories/1091002    |

### Expected Behavior

No issues with Yarn audit.

### Steps to Reproduce

1. `yarn audit`

### Nx Report

```shell
Node   : 21.7.1
OS     : darwin-arm64
yarn   : 1.22.19

nx          : 19.0.6
lerna       : 8.1.3
@nx/devkit  : 19.0.6
@nrwl/tao   : 19.0.6
typescript  : 3.9.10
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
So.. good news is.. I believe this to be a false positive on their part.

Our `js-yaml` dependency is an aliased dependency to `@zkochan/js-yaml`: https://github.com/nrwl/nx/blob/37f02f7e6b301975977dc2f7bdcb0fb4c2609317/packages/nx/package.json#L55

It has been that way for a while.. so I suspect the auditors have somehow changed their behavior to not take into account aliases.

However, that said. I don't think we actually need to alias it? So we should be able to fix the issue.

@meeroslav can you take a look please?

**Comment by haxxxton** [comment]
can confirm this is a false positive. `dependabot` also flags this pretty harshly, as its detecting `0.0.7` as the js-yaml version.

<img width="538" alt="image" src="https://github.com/nrwl/nx/assets/743105/b5d7c6d6-edd2-4949-9a0e-96733ea1872a">

I was able to solve this temporarily with an override in my package.json (im using npm)

```json
{
  "overrides": {
    "js-yaml": "4.1.0"
  }
}
```

**Comment by meeroslav** [comment]
Thank you for reporting this issue. It has been resolved with https://github.com/nrwl/nx/pull/25999
