### ISSUE TITLE
nx g @nrwl/angular:move reporting error

### ISSUE THREAD

**Issue by sameerinfodb** [nrwl/nx#2590]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Should move the library from lib/cm-cm-feature-shell to shared/my-feature-lib

## Current Behavior

reporting error  "Unexpected token s in JSON at position 38"

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. npx create-nx-workspace@latest cmpoc
2. nx g @nrwl/angular:lib  cm-feature-shell --directory=cm --unit-test-runner=karma --tags="scope:test,type:feature" --style="scss"
3. nx g @nrwl/angular:move --project "cm-cm-feature-shell"  shared/my-feature-lib

**Comment by jsaguet** [comment]
Are you running your commands on a Windows environment?
I encountered the same issue on Windows and opened a PR to fix it (#2588)

**Comment by sameerinfodb** [comment]
> Are you running your commands on a Windows environment?
> I encountered the same issue on Windows and opened a PR to fix it (#2588)

Yes, This is command is executed in Windows Environment.
