### ISSUE TITLE
Maybe flutter too? O:)

### ISSUE THREAD

**Issue by MikeProcudin** [nrwl/nx#2595]
omg, this dev tool is so amazin.

Guys, how do you think in the near future will it be possible to incorporate flutter into this system?

Many thanks.

**Comment by vsavkin** [comment]
@MikeProcudin I personally like Dart and Flutter, but unfortunately we don't have enough cycles to work on it in the near future. If you are interested in developing it, we will help out. We have decent support for plugin development now.

**Comment by MikeProcudin** [comment]
@vsavkin, I am busy with getting a better life.
Unfortunately, I am not in silicon valley 💃

**Comment by tinesoft** [comment]
For @MikeProcudin, @vsavkin  and others interested,

I released `nx-flutter` plugin that add flutter capabilities to your Nw workspace!
👉🏾 https://github.com/tinesoft/nxrocks/tree/master/packages/nx-flutter
👉🏾 https://github.com/nrwl/nx/pull/4434

Enjoy
