### ISSUE TITLE
When using Bun, 'nx migrate --run-migrations' adds a package-lock.json and does not respect bun.lockb

### ISSUE THREAD

**Issue by benpsnyder** [nrwl/nx#25987]
### Current Behavior

Run `nx migrate next` or `nx migrate latest` then `nx migrate --run-migrations` and you will see `package-lock.json` get created

### Expected Behavior

I expected it to respect my bun.lockb and not throw `error parsing lockfile: Lockfile is missing data`

### GitHub Repo

https://github.com/benpsnyder/nx-bun-testing

### Steps to Reproduce

Use https://github.com/benpsnyder/nx-bun-testing to reproduce

### Nx Report

```shell
Node   : 22.1.0
OS     : darwin-arm64
bun    : 1.1.9

nx (global)    : 19.1.0-beta.1
nx             : 19.1.0-beta.3
@nx/js         : 19.1.0-beta.3
@nx/linter     : 19.1.0-beta.3
@nx/eslint     : 19.1.0-beta.3
@nx/workspace  : 19.1.0-beta.3
@nx/devkit     : 19.1.0-beta.3
@nrwl/tao      : 19.1.0-beta.3
typescript     : 5.4.5
```

### Failure Logs

```shell
error parsing lockfile: Lockfile is missing data
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by benpsnyder** [comment]
Tagging in @Jordan-Hall

**Comment by Jordan-Hall** [comment]
@FrozenPandaz @jaysoo   this isn't a bug in bun. When it creates the tmp folder it running on NX version 19.0.7 even if you use nx migrate canary. Maybe this is something deeper than Bun or is this as expected

**Comment by Jordan-Hall** [comment]
@benpsnyder this should kinda be resolved now with the official release

**Comment by benpsnyder** [comment]
@Jordan-Hall I agree; it is resolved. We should never face this issue again, even if #25991 doesn't close ... but I would rather see it close.

**Comment by Jordan-Hall** [comment]
@jaysoo it's resolved hut I think the Underlying issue should start being fix
