### ISSUE TITLE
NX generator display too many cmd windows in windows os

### ISSUE THREAD

**Issue by ChoSeoHwan** [nrwl/nx#25993]
### Current Behavior

Nx generator display too many cmd windows like below video.

https://github.com/nrwl/nx/assets/20502624/258bb007-9d08-4329-b413-5107a51c6b2b

Our project has over 50 packages.
It seems that the nx daemon displays a cmd window when creating a graph.

### Additional 1

This issue also occurred when running `yarn nx report`.

### Additional 2

Nx generator on Mac is too slow compared to version 18.
Probably, it is the same cause.

### Expected Behavior

Runs the generator faster without showing the cmd window.

### Steps to Reproduce

1. `yarn nx g @nx/js:library` in monorepo project

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.12.2
OS     : win32-x64
yarn   : 4.2.2

nx             : 19.0.7
@nx/js         : 19.0.7
@nx/jest       : 19.0.7
@nx/eslint     : 19.0.7
@nx/workspace  : 19.0.7
@nx/devkit     : 19.0.7
@nx/esbuild    : 19.0.7
@nx/nest       : 19.0.7
@nx/node       : 19.0.7
@nx/plugin     : 19.0.7
@nx/webpack    : 19.0.7
nx-cloud       : 19.0.0
typescript     : 5.4.5
---------------------------------------
Community plugins:
@jscutlery/semver : 5.2.2
---------------------------------------
Local workspace plugins:
         @notification-service/nx
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

This problem makes work almost impossible.
It seems that the issue needs to be resolved quickly.

**Comment by akopachov** [comment]
Experiencing the same issue on Windows 11.
Had to set up devcontainer to continue working.

**Comment by ChoSeoHwan** [comment]
Any changes on this issue?
We can't upgrade nx version because of this issue

**Comment by ValentinGurkov** [comment]
In the newer releases, its a bit better, it opens only once `cmd` window. On `19.05` no windows are opened though and I prefer if it can remain that way. So we are still using the older version in our projects

**Comment by MaxKless** [comment]
Hi! Sorry you're running into this, we recently made some changes to how plugins are loaded and their code executed and this probably snuck in. 
Please retry on the latest nx `19.5` and confirm that this still issue still exists.
