### ISSUE TITLE
Issue when creating backend app in node for a NX monorepo

### ISSUE THREAD

**Issue by ZBOT3000** [nrwl/nx#26004]
### Current Behavior

Node app not being created in NX. When I try nx reset, problem still persists

### Expected Behavior

For a node backend app to be generated

### Steps to Reproduce

1. nx g @nrwl/node:app backend

### Nx Report

```shell
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
```

### Failure Logs

```shell
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Hi, can you please provide a repo we can pull down to reproduce the issue? It would help us identify the cause and fix the issue.
