### ISSUE TITLE
Not able to enable ivy on Storybook

### ISSUE THREAD

**Issue by maxigimenez** [nrwl/nx#2601]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Support ivy on storybook.

## Current Behavior

Ivy is not enabled for storybook projects.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Clone this repository `https://github.com/maxigimenez/nx-angular-storybook`
2. Run `npm install`
3. Run `npx ng run my-lib:storybook`
4. Inspect angular element and run `$0.__ngContext__` in the browser console, will return `undefined` but when ivy is enable it returns more information.

### Context

Please provide any relevant information about your setup:

- Using latests angular
- Tried with latests storybook and also with `next` branch of storybok

Use the repository mentioned above to fully reproduce the issue.

## Other
I forked storybook and run their `angular-cli` project with the latest version of angular and work as expected.

**Comment by nikbabchenko** [comment]
By the way, how to compile in prod mode storybook?

**Comment by gund** [comment]
Bumping so it's not closed.

**Comment by Stonepaw** [comment]
Bump!

I discovered this unexpected issue when trying to storybook a component that was binding css variables, an ivy only feature. Is there a workaround or possible fix for this issue?

**Comment by juristr** [comment]
@Stonepaw I'm working on a fix. For now you can try to remove the `create-ivy-entry-points` from the `postinstall` script in the package.json. Remove and re-install the node_modules and then storybook should run in Ivy mode
