### ISSUE TITLE
NX React 10kb inline limit customizable?

### ISSUE THREAD

**Issue by matthew-plusprogramming** [nrwl/nx#26044]
### Current Behavior

Hi, I was curious is the 10kb limit for inlining assets customizable in react. I would assume there would be a way to customize this, although I'm having trouble finding it. The file in which the limit is defined is here:
https://github.com/nrwl/nx/blob/af463c4833723e7bd8829f07baec8bf5d3a50649/packages/react/plugins/bundle-rollup.ts

### Expected Behavior

I would expect to be able to change this limit.

### Steps to Reproduce

1. N/A

### Nx Report

```shell
N/A
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by MilanKovacic** [comment]
Are you using @nx/react, and which bundler?
