### ISSUE TITLE
Angular - Compat matrix

### ISSUE THREAD

**Issue by PieterjanDeClippel** [nrwl/nx#26079]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

- [nx.dev](https://nx.dev/nx-api/angular/documents/angular-nx-version-matrix)
- [Github](https://github.com/nrwl/nx/blob/af463c4833723e7bd8829f07baec8bf5d3a50649/docs/shared/packages/angular/angular-nx-version-matrix.md?plain=1#L17)

### Additional context or description

- [StackOverflow](https://stackoverflow.com/questions/78525195/can-we-use-angular-18-on-nx-18-2-0/78526494?noredirect=1#comment138450309_78526494)

**Comment by FrozenPandaz** [comment]
This was fixed with https://github.com/nrwl/nx/pull/23905.
