### ISSUE TITLE
Can't open nx console generator ui since upgrade @nx/angular to 19.1 and angular 18

### ISSUE THREAD

**Issue by guysenpai** [nrwl/nx#26088]
### Current Behavior

The nx console generator ui does not open since `@nx/angular` 19.1.0 and angular 18 deps are installed.
Note: It works when using `nx generate` command

### Expected Behavior

The nx console generator ui does open

### GitHub Repo

https://github.com/guysenpai/nx-console-bug

### Steps to Reproduce

1. clone the repo
2. install deps
3. try to generate using nx console

### Nx Report

```shell
Node   : 20.12.2
OS     : linux-x64
pnpm   : 8.15.7

nx                 : 19.1.0
@nx/js             : 19.1.0
@nx/jest           : 19.1.0
@nx/linter         : 19.1.0
@nx/eslint         : 19.1.0
@nx/workspace      : 19.1.0
@nx/angular        : 19.1.0
@nx/devkit         : 19.1.0
@nx/eslint-plugin  : 19.1.0
@nrwl/tao          : 19.1.0
@nx/web            : 19.1.0
@nx/webpack        : 19.1.0
typescript         : 5.4.5
```

### Failure Logs

```shell
[Nxls] - 2024-05-26T10:27:03.708Z - Unable to get Nx info: TypeError [ERR_INVALID_ARG_TYPE]: The "paths[2]" argument must be of type string. Received undefined
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

A comment about the issue I opened in nx-console repo
https://github.com/nrwl/nx-console/issues/2148#issuecomment-2131213019

**Comment by jamesynz** [comment]
Yeap it didn't work for me either with a new nx installation with Nx. It will not work even if you downgrade the Nx Console version. 

`Node   : 20.13.1
OS     : darwin-x64
npm    : 10.5.2

nx (global)        : 19.1.0
nx                 : 19.1.0
@nx/js             : 19.1.0
@nx/jest           : 19.1.0
@nx/linter         : 19.1.0
@nx/eslint         : 19.1.0
@nx/workspace      : 19.1.0
@nx/angular        : 19.1.0
@nx/cypress        : 19.1.0
@nx/devkit         : 19.1.0
@nx/eslint-plugin  : 19.1.0
@nrwl/tao          : 19.1.0
@nx/web            : 19.1.0
@nx/webpack        : 19.1.0
typescript         : 5.4.5`

It worked when i created another workspace with a downgraded version of Nx 
> npx create-nx-workspace@19.0.4 

Node   : 20.13.1
OS     : darwin-x64
npm    : 10.5.2

nx (global)        : 19.1.0
nx                 : 19.0.4
@nx/js             : 19.0.4
@nx/jest           : 19.0.4
@nx/linter         : 19.0.4
@nx/eslint         : 19.0.4
@nx/workspace      : 19.0.4
@nx/angular        : 19.0.4
@nx/devkit         : 19.0.4
@nx/esbuild        : 19.0.4
@nx/eslint-plugin  : 19.0.4
@nx/playwright     : 19.0.4
@nrwl/tao          : 19.0.4
@nx/web            : 19.0.4
@nx/webpack        : 19.0.4
typescript         : 5.4.4

**Comment by leosvelperez** [comment]
This is an issue in Nx Console that we're taking a look. Please follow https://github.com/nrwl/nx-console/issues/2148 for updates.
