### ISSUE TITLE
Running `ng generate app` fails with silent error

### ISSUE THREAD

**Issue by WouterSpaak** [nrwl/nx#261]
Hello,

Running `ng generate app foo-dev --prefix foo --style scss` fails with a silent error:

![error-nx-g-app](https://user-images.githubusercontent.com/2631869/35923657-230b4d90-0c21-11e8-8f9a-1be1789f2f92.png)

I'm getting this error on Powershell in Windows 10, as well as bash on the Windows Subsystem for Linux. Error has also been reproduced by a colleague working on a brand new MacBook Pro.

My angular versions:

```
Angular CLI: 1.6.5
Node: 8.8.1
OS: win32 x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cdk: 5.2.0
@angular/cli: 1.6.5
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.2.0
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.7.1
webpack: 3.10.0
```

And Nrwl Schematics at `@nrwl/schematics@0.7.3`.

Other generative commands (`component`, `pipe`, `service` etc.) seem unaffected. Running `ng generate app foo` without any options also fails.

**Comment by WouterSpaak** [comment]
I've pinpointed the error down to typescript 2.7.*. Apparently there has been a change in the typescript API that causes this command to fail silently; everything works as expected when I install TS 2.6.2.

I'll take a look at what the cause of this API change is, and file a PR where I either fix the problem (hopefully) or pin the TS dependency to 2.6.

**Comment by vsavkin** [comment]
Since a particular version of Angular (and  the CLI) works with a particular version of TypeScript, Nx is pinned to one version of TypeScript as well. We use TS 2.6.2 when we generate a new workspace.

In general, I recommend you to let Nx upgrade Angular, CLI, RxJS, NgRx, or TypeScript. One of the advantages of using Nx is that we makes sure the lib combination we ship works well together.

Closing this issue.

**Comment by jdk339** [comment]
`npm install typescript@2.6.2` gets rid of the silent 'Error:' error, but I get another error right after running `ng generate app my-app-name --routing`

```
Cannot find module '@angular-devkit/schematics'
Error: Cannot find module '@angular-devkit/schematics'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/user/workspace/node_modules/@nrwl/schematics/src/collection/app/index.js:11:20)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by jdk339** [comment]
I figured it out. I had to downgrade `@nrwl/schematics` from `0.7.4` (I upgraded trying to fix the problem above) back to what I had before (`0.3.0`). Really wish the documentation had documentation on how to update `@nrwl/schematics`, because changing/upgrading the version through npm does not seem to work...

**Comment by literalpie** [comment]
@jdk339 you can run `npm run update` with the latest version of nrwl, or `npm run nx-migrate` if you have an older version. 

Install the new version of nrwl/schematics first, then run the appropriate command. This will do everything needed to make everything work with the latest version of nrwl

**Comment by jdk339** [comment]
@literalpie Thanks, but if I do `npm install @nrwl/schematics@latest` it still doesn't give me the migration script in my `package.json` to migrate my project
