### ISSUE TITLE
Can not upgrade to TypeScript 3.8.3

### ISSUE THREAD

**Issue by daniellwdb** [nrwl/nx#2610]
After trying to upgrade to TypeScript 3.8.3 and using top level await, the following error appears:
```
Module parse failed: Cannot use keyword 'await' outside an async function
File was processed with these loaders:
  * ./node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
```
I'm not sure what to do at this point, I tried upgrading ts-loader to `"ts-loader": "typestrong/ts-loader",` which gave me a different error
```
ERROR in ./apps/api/src/main.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: Cannot find module './dist'
``` 
and change the main tsconfig (in the root of the workspace)
```json
"target": "es2017",
"module": "esnext",
"lib": ["es2017", "dom"],
```

**Comment by vsavkin** [comment]
Sorry, we currently do not officially support TypeScript 3.8+.

It usually takes a few months for all the tools we rely on to start supporting latest version of TypeScript. Once it happens, we will bump up the version. We will also update your workspace automatically once this happens.

**Comment by joain946** [comment]
I have the same issue. I would like to use "top level await" together with Node.js 14 and AWS Lambda.
Any idea on when this will be resolved?

My error:
Module parse failed: Cannot use keyword 'await' outside an async function (8:0)
File was processed with these loaders:
 * ./node_modules/@nrwl/node/node_modules/ts-loader/index.js

**Comment by BetterLuke** [comment]
Same issue, please

**Comment by vinerich** [comment]
Any news on this?
