### ISSUE TITLE
@AgentEnder Your fix broke `skipRemotes` entirely. It finds matching projects based on the `projectGraph`. If the projects are in a different repository and are not running (which is my use-case and is also other's use-case as well I'm sure), it won't be able to find them. Then `remotesToSkip` ends up being empty causing an error when you start the project.

### ISSUE THREAD

**Issue by zamodev** [nrwl/nx#26121]
Hello, I'm trying to communicate my host application with another project that is outside this workspace, I have used skipRemotes but as @Michael-Ziluck comments it only works for projects that are in the same workspace, otherwise when I do it with one that This is on the outside I get an error that does not allow me to launch the project

**Comment by FrozenPandaz** [comment]
Could you please open a new issue using the issue template? It will help us take a look. From this issue, I'm not sure which change you're referring to.
