### ISSUE TITLE
e2e runner for Cypress does not allow parallel execution

### ISSUE THREAD

**Issue by brentatkins** [nrwl/nx#26135]
### Current Behavior

Cypress supports parallel test execution, however this is not possible with using the nx e2e target. The parallel option passed as an additional option is not forward to the Cypress command.

When executing command: 
```
nx e2e sample-e2e -- --parallel --ci-build-id abc123 --record --key xyz987
```

the resulting Cypress command does not include the `parallel` option

```
cypress run --ci-build-id abc123 --record --key xyz987
```

This ultimately produces an error by Cypress:
```
You passed the --ci-build-id flag but did not provide either a --group or --parallel flag.
```

This seems to be a change introduced in `18.2.3`. In prior versions, the parallel option is passed to Cypress as expected.

### Expected Behavior

All arguments should be passed to the Cypress command, including the `parallel` option

### Steps to Reproduce

1. Create an e2e project using Cypress
2. Set a value for projectId in the cypress.config.ts
3. Run this command: nx e2e sample-e2e -- --parallel --ci-build-id abc123 --record --key xyz987 (replace sample-e2e with the name of your e2e project)
4. 💥 Cypress fails to run due to the missing `parallel` flag

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 22.0.0
OS     : darwin-arm64
npm    : 10.5.1

nx                 : 19.1.0
@nx/js             : 19.1.0
@nx/jest           : 19.1.0
@nx/linter         : 19.1.0
@nx/eslint         : 19.1.0
@nx/workspace      : 19.1.0
@nx/angular        : 19.1.0
@nx/cypress        : 19.1.0
@nx/devkit         : 19.1.0
@nx/eslint-plugin  : 19.1.0
@nrwl/tao          : 19.1.0
@nx/web            : 19.1.0
@nx/webpack        : 19.1.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
```

### Failure Logs

```shell
❯ npx nx e2e sample-e2e -- --parallel --ci-build-id 12331223 --record --key 9999

> nx run sample-e2e:e2e --parallel --ci-build-id 12331223 --record --key 9999

> cypress run --ci-build-id 12331223 --record --key 9999


DevTools listening on ws://127.0.0.1:53159/devtools/browser/bdd5686e-e123-41b4-84f5-5c20ac8aa115
2024-05-27 20:42:35.502 Cypress[16346:95237720] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
Reusing the server already running on http://localhost:4200
You passed the --ci-build-id flag but did not provide either a --group or --parallel flag.

The --ci-build-id flag you passed was: 12331223

The --ci-build-id flag is used to either group or parallelize multiple runs together.

https://on.cypress.io/incorrect-ci-build-id-usage
Warning: command "cypress run --ci-build-id 12331223 --record --key 9999" exited with non-zero status code
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

As mentioned earlier, this is an issue introduced in version `18.2.3`. I tested version `18.2.2` and it works as expected.

I have also tried setting the target option in the project.json (see below), however this does not work either.

```
"e2e": {
  "options": {
    "parallel": false,
  }
}
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

In most cases, using the syntax you used is fine, but the `parallel` option is a bit special because both the Nx CLI and the `nx:run-commands` executor accept a `--parallel` option. Because of that, the following happens:

```bash
# --parallel is parsed and used by the Nx CLI
# --ci-build-id, --record and --key are unknown to the Nx CLI and the nx:run-commands executor, so they are forwarded
nx e2e sample-e2e --parallel --ci-build-id abc123 --record --key xyz987

# --parallel is parsed and used by the nx:run-commands executor
# --ci-build-id, --record and --key are unknown to the nx:run-commands executor, so they are forwarded
nx e2e sample-e2e -- --parallel --ci-build-id abc123 --record --key xyz987
```

The Nx CLI and the `nx:run-commands` executor can't assume whether `--parallel` was meant to be forwarded in such cases.

Similarly, when providing it in the target configuration as an option, you're effectively providing an option for a target that uses the `nx:run-commands` executor, and therefore, the option is for that executor. Only the unknown options and the options provided with the `--args` option are forwarded to the underlying command.

For these special cases, you must use the `--args` option of the `nx:run-commands` executor:

```bash
# set everything you want to forward to the underlying command
nx e2e sample-e2e --args="--parallel --ci-build-id abc123 --record --key xyz987"

# set only the option that conflicts with the Nx CLI and/or the nx:run-commands executor
nx e2e sample-e2e --args="--parallel" --ci-build-id abc123 --record --key xyz987
```

You can read the following docs for more information: https://nx.dev/recipes/running-tasks/pass-args-to-commands.
