### ISSUE TITLE
Documentation page referenced from a chat with your AI not found

### ISSUE THREAD

**Issue by roiros** [nrwl/nx#26149]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/executors/overview 

### Additional context or description

Asked on your [AI agent](https://nx.dev/ai-chat)
How are executers and nx agents related?

**Comment by FrozenPandaz** [comment]
Hm, I asked the AI again today and got all links that do exist. If you see it again, please open a new issue.

Sources
[Nx Agents](https://nx.dev/reference/glossary#nx-agents)
[Use Task Executors](https://nx.dev/core-features/plugin-features/use-task-executors#use-task-executors)
[Nx Cloud Efficiently Orchestrates Agents](https://nx.dev/concepts/more-concepts/illustrated-dte#nx-cloud-efficiently-orchestrates-agents)
