### ISSUE TITLE
Basic creation of a workspace fails

### ISSUE THREAD

**Issue by maartentibau** [nrwl/nx#2617]
Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

I'm trying to create an empty or Angular workspace with the latest version of Nx

## Current Behavior

After selecting which type of workspace I want, first tried with Empty then with Angular but both result in the same error.
 
## Failure Information (for bugs)

Creating of the workspace fails

### Steps to Reproduce

`npx create-nx-workspace@latest my-workspace` OR `npm init nx-workspace@latest my-workspace`

Select `Empty` or `Angular` using `Angular CLI`

Then suddenly this error pops up, because the whole setup of the workspace completes.
A question I have with this is how I could avoid using Yarn and force only to use NPM during the install, is that possible?

### Failure Logs

```
npx: installed 180 in 191.272s
? What to create in the new workspace empty             [an empty workspace]
? CLI to power the Nx workspace       Angular CLI  [Extensible CLI for Angular applications. Recommended for Angular projects.]
Creating a sandbox with Nx...
warning @angular/cli > universal-analytics > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
error @angular-devkit/core@9.0.5: The engine "yarn" is incompatible with this module. Expected version ">= 1.13.0".
error Found incompatible module
(node:21270) UnhandledPromiseRejectionWarning: Error: Command failed: yarn install --silent
    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at createSandbox (/Users/maarten/.npm/_npx/20559/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:317:21)
    at determineCli.then.cli (/Users/maarten/.npm/_npx/20559/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:75:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:21270) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21270) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Other

**Comment by maartentibau** [comment]
OK, it seems this was an issue at my end.

I removed Yarn completely from my laptop and now it works. 🙂

**Comment by fetters5** [comment]
I had the same issue yesterday and also had to uninstall a really old version of yarn I forgot I had.
