### ISSUE TITLE
[nx/vite] [19.1.0] Vitest runs in watch mode by default? (or should we add a coverage target?)

### ISSUE THREAD

**Issue by connorjs** [nrwl/nx#26223]
### Current Behavior

After upgrading to 19.1.0, my test script now runs in watch mode.

### Expected Behavior

I expect my test script to only run in watch mode if told to do so.

---

Alternatively, I expect the inferred plugin to provide some CI-mode target separate from test. I am more than eager to learn about latest Vitest recommendations but let me share a bit more about the flow I have used for a few years now.

- There are two test modes
  1. Fast red-green cycle for development (watch mode or using IDE)
  2. Verify build (run with coverage)
- CI runs the coverage, but I should be able to verify almost everything CI runs locally.
  - I have seen others recommend coverage not needed for standard red-green/watch loops and tests run faster without coverage collection
- Specifically, I have a `ci-build` npm run script that executes `nx test`. This now hangs b/c it enters watch mode.

Thus, I’m open to two targets here if needed. (My original expectation would be to just add watch if needed: `nx test my-project -- --watch`.)

Note: Using `cross-env` with `CI=true` fixes this for me, but removes the nice output on local CLI.

Additionally, watch mode vs. no watch mode messes with caching it seems. (When opening the report, I thought it was fixed after upgrading `nx` globally but that was only b/c of a cache hit on the `nx test my-project -- --run` execution. After cleaning cache, it continued to hang with watch.)

### Steps to Reproduce

1. Create repo with `@nx/vite` 
2. Ensure you have unit tests in a project
3. Run `test` target on a project

_I can create sample repo if needed, but I assume there’s existing example repos with which to test._

### Nx Report

```shell
Node   : 20.11.0
OS     : darwin-arm64
npm    : 10.2.4

nx (global)    : 19.1.0
nx             : 19.1.0
@nx/js         : 19.1.0
@nx/linter     : 19.1.0
@nx/eslint     : 19.1.0
@nx/workspace  : 19.1.0
@nx/devkit     : 19.1.0
@nrwl/tao      : 19.1.0
@nx/vite       : 19.1.0
typescript     : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/js/src/plugins/typescript/plugin.js
@nx/vite/plugin
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

It seems we added support for manually passing watch in <https://github.com/nrwl/nx/pull/23298>. This used `watch: false` as default.

Then, it seems we removed the new `watch: false` in <https://github.com/nrwl/nx/pull/25975>.

Thus, I’ll tag @Coly010 and @jaysoo to chime in with their recommendations here. As mentioned in expected behavior, I’m happy to learn other recommendations.

For the time being, I have added `cross-env CI=true` into my local npm run script which fixes test running locally, but removes the nice Nx output.

**Comment by terrymun** [comment]
We experienced the same issue here, and only found out because we run unit tests (with vitest) in our pre-push hooks, and these checks were stalling after the upgrade.

Our current stop-gap solution to this is to not use the vite plugin to create inferred tasks for unit testing, but instead define the `test` task for every project that needs to be unit tested. It's a bit verbose but since we don't have a lot of projects/packages, this worked out fine.

Still looking forward to using the inferred test task again once watch mode is disabled by default, so we can keep our multitude of `project.json` files DRY.

**Comment by Coly010** [comment]
Hi! I'm sorry for the inconvenience that this change introduced to your workflows.

When we were inferring the target, we had been setting `{watch: false}` to replicate the `vitest run` behaviour. 
However, the goal is that the plugin should only run `vitest` and allow the config file and overrides such as `nx run myproj:test --watch=false` to function as expected.

Therefore we decided to closely align with the recommendations from `vitest` itself which uses watch by default. There is an ongoing discussion around this on the Vitest GitHub Repo: https://github.com/vitest-dev/vitest/discussions/540

A workaround that can be done is to add `watch: false` to your `vite.config.ts`'s `test` object, or to your `vitest.config.ts`'s `test` object.

Another workaround is to create a `test` target in the affected `project.json` files which would simply be:

```
"test": {
  "options": {
    "watch": false
  }
}
```

**Comment by connorjs** [comment]
Thank you @Coly010! I confirmed that my expected workflow is restored by adding `watch: false` under `test` field in vite(st) config. I am still able to run in watch with the `--watch/-w` flag on CLI.

```
nx test my-project -- -w
```

Thank you for sharing Vitest discussion, too.

I defer to y’all as contributors for closing this with workaround or converting to "Pending Vitest discussion" or whatever. Cheers!

**Comment by connorjs** [comment]
Well, one more thought. What’s the best way to find out Nx user thoughts on the "dual target" state I mentioned? Copying what I posted on Vitest discussion.

> Traditionally, I have had `test` command that defaults to watch (nice to use `npm t` on CLI) and skips coverage. I then have a `coverage` command that runs and collects coverage. CI builds use `coverage`, not `test`.

Is there desire for `@nx/vite` inferred tasks to have two targets? One that is `cache: false` for watching and one that is `cache: true` for running? The run one defaults to adding `--coverage` as well.

The name (`coverage` for CI instead of `test`) may not be industry standard (I don’t know what others use), but I do think having two targets could save some undifferentiated work in Vitest Nx monorepos. (Especially, if we solve the coverage combining in the monorepo, which I have hacked together myself with nyc cli. This aspect relates to Vitest monorepo support, too.)

**Comment by jaysoo** [comment]
> Is there desire for @nx/vite inferred tasks to have two targets? One that is cache: false for watching and one that is cache: true for running? The run one defaults to adding --coverage as well.

Cacheability shouldn't matter since `--watch` mode will not complete, and thus cannot be cached. We will make a change to the generated config to set `watch: false` so things work better with Nx out of the box. Users can still pass `--watch` to override this option.

I think having a separate CI target may be too specific to certain use cases. User can run `nx affected -t test --coverage` for example in CI. If it's very common that this is the CI use-case , then maybe it's worth inferring a separate target.

**Comment by FrozenPandaz** [comment]
This was fixed with https://github.com/nrwl/nx/pull/26267.
