### ISSUE TITLE
Nx migrate to v19 issues

### ISSUE THREAD

**Issue by ArielGueta** [nrwl/nx#26224]
### Current Behavior

Running `nx migrate --run-migrations` after `nx migrate latest` to v19 causes the following issues:

- Many warning of "Skipping migration for project settings. Unable to determine 'tsconfig.json' file in workspace config."
-  Failed to run migration-v18 from @angular/cdk. This workspace is NOT up to date!
-  error TS5083: Cannot read file '/tools/tsconfig.base.json'.

When I also try to run npm start after this I get this weird error:

> Invalid self-closing element in index HTML file: '<path
            d="M360.608 150.369L466.871 256.632L352.938 370.566C299.044 424.46 299.044 511.84

### Expected Behavior

To work

### Steps to Reproduce

1.

### Nx Report

```shell
Node   : 20.11.1
OS     : darwin-arm64
npm    : 10.2.4

nx                 : 19.1.0
@nx/js             : 19.1.0
@nx/jest           : 19.1.0
@nx/linter         : 19.1.0
@nx/eslint         : 19.1.0
@nx/workspace      : 19.1.0
@nx/angular        : 19.1.0
@nx/devkit         : 19.1.0
@nx/eslint-plugin  : 19.1.0
@nx/playwright     : 19.1.0
@nx/plugin         : 19.1.0
@nrwl/tao          : 19.1.0
@nx/vite           : 19.1.0
@nx/web            : 19.1.0
@nx/webpack        : 19.1.0
typescript         : 5.4.5
---------------------------------------
Community plugins:
@auth0/auth0-angular : 2.2.3
---------------------------------------
Local workspace plugins:
         @app/workspace-plugin
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by nedim1511** [comment]
@ArielGueta I managed to solve _Invalid self-closing element in index HTML file:_ by closing it manually. So, instead of:
<path /> try to use <path></path>

For the second error I think you might need to check if that path exists and if it does, set it like here: https://stackoverflow.com/a/66088074

**Comment by ArielGueta** [comment]
`<path />` is valid:

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/path

**Comment by ArielGueta** [comment]
Removing the migration of angular/cdk solves the issues
