### ISSUE TITLE
Installing @progress/kendo-angular-intl Causes Generate in NX Console to Stop Working.

### ISSUE THREAD

**Issue by vdiaz1130** [nrwl/nx#2624]
Installing @progress/kendo-angular-intl in an NX Angular project causes the Generate button in the VS Code NX Console to stop working.

To reproduce:
npx create-nx-workspace@latest myws
select Angular
give it a name
select SASS
cd into the project
open in VS Code
click the Generate button in the NX Console - note it works
npm i --save @progress/kendo-angular-intl
click the Generate button in the NX Console - note it no longer works
In VS Code, Select help >> Toggle Developer Tools
click the Generate button in the NX Console - note the errors in the developer tools
npm uninstall --save @progress/kendo-angular-intl
click the Generate button in the NX Console - note it works again

**Comment by ctaleck** [comment]
This issue was submitted on the original repository as https://github.com/nrwl/nx-console/issues/923

**Comment by ctaleck** [comment]
If someone tests PR #971, it may fix this issue.
