### ISSUE TITLE
Memory issues building multiple Angular apps with NX on bitbucket pipelines

### ISSUE THREAD

**Issue by mattiLeBlanc** [nrwl/nx#26256]
### Current Behavior

I have many build failures with my mono repo building 3 Angular apps in parallel.
I had to set parallel to 1 worker only to make sure I am not running out of memory.
In bitbucket I am using size 2 already to get 8gb of memory.

Is there any memory optimisation possible or do I have to resort to dedicated runners or just building my angular apps in line?

<img width="1436" alt="image" src="https://github.com/nrwl/nx/assets/5285035/2c2bc596-6e29-4df0-ae6d-f9e14c93cfd7">

Related issue: https://github.com/nrwl/nx/issues/14343

### Expected Behavior

Build multiple apps in parallel?

### Steps to Reproduce

1. build around 3 apps at the same time with Nx affected

### Nx Report

```shell
i dont have one
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [X] Other (Please specify)

### Additional Information

Running on bitbucket pipelines with 2x memory

**Comment by MaxSassen** [comment]
try adding the following into your steps:

size: 2x #doubling memory size

**Comment by Coly010** [comment]
Hi! I'm sorry to hear you're encountering a problem building your apps in parallel.

This isn't directly related to Nx itself. Nx creates a node process per build when running in parallel. 
The combination of these three processes, plus the parent process could be reaching the Node memory allocation on your CI machine.

You can look into:
1. increasing the Node Memory Allocation for your CI runner (https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-megabytes)
2. Increasing the amount of RAM assigned to your CI Runners
3. Use Nx Cloud (https://nx.app/) which can allow you to automatically distribute tasks across different agents in parallel (https://nx.dev/ci/features/distribute-task-execution)
