### ISSUE TITLE
tslib not found in node server production build

### ISSUE THREAD

**Issue by vincaslt** [nrwl/nx#2625]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

I build a production build of my node app, which is generated from `@nrwl/node`, calling `nx build api --prod`. I copy the generated files onto my server (or just another directory) and start it with `node main.js`.

## Current Behavior

The error I get when starting is: 

```
> node main.js
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'tslib'
Require stack:
- C:\Users\vinca\Desktop\main.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:690:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:852:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:74:18)[39m
    at Object.<anonymous> (C:\Users\vinca\Desktop\main.js:91:18)
    at __webpack_require__ (C:\Users\vinca\Desktop\main.js:20:30)
    at Object.<anonymous> (C:\Users\vinca\Desktop\main.js:1086:17)
    at __webpack_require__ (C:\Users\vinca\Desktop\main.js:20:30)
    at Object.<anonymous> (C:\Users\vinca\Desktop\main.js:1076:18)
    at __webpack_require__ (C:\Users\vinca\Desktop\main.js:20:30) {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [ [32m'C:\\Users\\vinca\\Desktop\\main.js'[39m ]
}
```

**Comment by vincaslt** [comment]
I've a sense this is because api build does not include vendors. Is there a configuration option I'm missing?

**Comment by vincaslt** [comment]
I added this flag in production build config: `"externalDependencies": "none"`

**Comment by agrinko** [comment]
@vincaslt , thank you, it helped! I would never guess it...

**Comment by hertzg** [comment]
For people who are trying out `nx` you probably have set `"importHelpers": true` (default config) in your `tsconfig.base.json` which will use `tslib` package when there's a need to emit helpers in generated code.

There are reasons when such behavior is Preferred but if you want to opt out of it you could set that flag to `false`. 

### References

* https://www.typescriptlang.org/docs/handbook/compiler-options.html
* https://www.npmjs.com/package/tslib

**Comment by vanduc1102** [comment]
should we add the `tslib` to generated packageJson be default ?

**Comment by brentkirkland** [comment]
If you come across a similar situation try adding `"generatePackageJson": true` to your production configuration in build

```
"configurations": {
            "production": {
              "optimization": true,
              "extractLicenses": true,
              "generatePackageJson": true,
              "inspect": false,
              "fileReplacements": [
                {
                  "replace": "apps/log-listener/src/environments/environment.ts",
                  "with": "apps/log-listener/src/environments/environment.prod.ts"
                }
              ]
            }
          }
```

**Comment by Kalanamith** [comment]
This issue still exists

**Comment by ankuragrwl** [comment]
I did the following and it worked for me:

In the nestjs App's project.json file, configure generatePackageJson : true inside the build configuration section.

Then add  RUN npm --prefix api-gateway --omit=dev -f install to the Dockerfile
