### ISSUE TITLE
Adding Nx plugin @angular-architects/ddd to nx list

### ISSUE THREAD

**Issue by manfredsteyer** [nrwl/nx#2626]
According to your docs, I'd like to propose adding the Nx Plugin [@angular-architects/ddd](https://www.npmjs.com/package/@angular-architects/ddd) to ``nx list``.

**Comment by wesleygrimes** [comment]
Sounds good! Woul you be able to submit a PR and add to the community/approved-plugins.json file?

**Comment by wesleygrimes** [comment]
Use #2597 as an example. We have updated the docs on the submission process but haven’t deployed new version to website yet.

**Comment by wesleygrimes** [comment]
@manfredsteyer we will go ahead and create the PR to get your plugin added. Thanks!
