### ISSUE TITLE
"An error occured while creating pruned lockfile"

### ISSUE THREAD

**Issue by pct-cclausen** [nrwl/nx#26296]
### Current Behavior

It told me to create a ticket here.

Situation: I have a node app that gets auto-reloaded when I change a file.
Only in this situation does the error show up, on the first startup everything is fine.
It stills works because "To prevent the build from breaking we are returning the root lock file."

See failure logs & additional information.

### Expected Behavior

No error messages

### Steps to Reproduce

No idea, I hope the data I provided may help anyway.

### Nx Report

```shell
Node   : 20.12.0
OS     : linux-x64
npm    : 10.5.0

nx                 : 18.2.4
@nx/js             : 18.2.4
@nx/jest           : 18.2.4
@nx/linter         : 18.2.4
@nx/eslint         : 18.2.4
@nx/workspace      : 18.2.4
@nx/angular        : 18.2.4
@nx/cypress        : 18.2.4
@nx/devkit         : 18.2.4
@nx/esbuild        : 18.2.4
@nx/eslint-plugin  : 18.2.4
@nx/node           : 18.2.4
@nx/plugin         : 18.2.4
@nrwl/tao          : 18.2.4
@nx/web            : 18.2.4
@nx/webpack        : 18.2.4
typescript         : 5.3.3
---------------------------------------
Community plugins:
@ionic/angular       : 7.8.6
@ngneat/spectator    : 15.0.1
@nxext/ionic-angular : 18.0.4
@rx-angular/cdk      : 17.0.1
ng-mocks             : 14.12.2
---------------------------------------
Local workspace plugins:
         @<redacted>/<redacted>
```

### Failure Logs

```shell
NX   An error occured while creating pruned lockfile

Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
To prevent the build from breaking we are returning the root lock file.
If you run `npm install --package-lock-only` in your output folder it will regenerate the correct pruned lockfile.

Original error: Target project does not exist: npm:pg-types@2.2.0


Error: Target project does not exist: npm:pg-types@2.2.0
    at validateCommonDependencyRules (/workspace/node_modules/nx/src/project-graph/project-graph-builder.js:326:15)
    at validateDependency (/workspace/node_modules/nx/src/project-graph/project-graph-builder.js:313:5)
    at ProjectGraphBuilder.addDependency (/workspace/node_modules/nx/src/project-graph/project-graph-builder.js:190:9)
    at ProjectGraphBuilder.addStaticDependency (/workspace/node_modules/nx/src/project-graph/project-graph-builder.js:89:14)
    at /workspace/node_modules/nx/src/plugins/js/lock-file/project-graph-pruning.js:81:17
    at Array.forEach (<anonymous>)
    at traverseNode (/workspace/node_modules/nx/src/plugins/js/lock-file/project-graph-pruning.js:78:36)
    at /workspace/node_modules/nx/src/plugins/js/lock-file/project-graph-pruning.js:80:9
    at Array.forEach (<anonymous>)
    at traverseNode (/workspace/node_modules/nx/src/plugins/js/lock-file/project-graph-pruning.js:78:36)
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I put this log line right before the error is thrown in the validateCommonDependencyRules function.

````
    if (!projects[d.target] &&
        !externalNodes[d.target] &&
        !('sourceFile' in d && d.sourceFile)) {

            console.log(d, externalNodes, projects, fileMap);

        throw new Error(`Target project does not exist: ${d.target}`);
    }
````
It printed this:

````

{
  source: 'npm:pg',
  target: 'npm:pg-types@2.2.0',
  type: 'static',
  sourceFile: undefined
} {
  // I removed all but this node here, because the other ones are clearly unrelated

  'npm:pg-types': {
    type: 'npm',
    name: 'npm:pg-types',
    data: {
      version: '2.2.0',
      packageName: 'pg-types',
      hash: '12834163013231816562'
    }
  },
  
  }
} {} { projectFileMap: {}, nonProjectFiles: [] }


````

What seems off here is that it makes a lookup for pg-types in externalNodes in the code like this: `externalNodes[d.target]`
and then cannot find pg-types, because the key under which it is located is "npm:pg-types", but it searches for "npm:pg-types:2.2.0", so with the version included. It is the right version, but the key in externalNodes does not include that version.

What might be relevant here is a result of `npm ls pg-types` in my workspace:

````
 npm ls pg-types
@<redacted>/source@ /workspace
├─┬ @types/pg@8.11.6
│ └── pg-types@4.0.2
└─┬ pg@8.11.5
  └── pg-types@2.2.0
````

For some reason the @types package uses a different version of pg-types than pg.
Maybe this duplication causes the version to pop up in the key?

If I get rid of @types/pg in my workspace the error goes away and instead it shows it for some other package "split2", which I cannot remove as easily. That package also has multiple versions in npm ls.

**Comment by FrozenPandaz** [comment]
We've made some fixes to this area recently. Could you retry with the latest version of Nx please?

**Comment by pct-cclausen** [comment]
That will take a while, I just upgraded NX and this was the highest version that worked with some of the plugins we use.

I will see what I can do.
