### ISSUE TITLE
@nrwl/storybook:configuration - adds unecessary dependencies to package.json

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#2630]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

When creating storybook for React library, only react specific libraries should be added during SB init

`nx g @nrwl/react:storybook-configuration remove-foo`

adds following deps only:

```json
{
"@storybook/react": "5.3.9",
"@storybook/addon-knobs": "5.3.9",
"babel-loader": "8.0.6",
"@babel/core": "7.8.3",
}
```

## Current Behavior

Both angular and react libs are added

![image](https://user-images.githubusercontent.com/1223799/76245042-7d1f0980-623b-11ea-8434-816f8bebcb07.png)

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `nx g @nrwl/react:lib hello`
2. `nx g @nrwl/react:storybook-configuration hello`

### Context

```
@nrwl/angular : Not Found
  @nrwl/cli : 9.0.4
  @nrwl/cypress : 9.0.4
  @nrwl/eslint-plugin-nx : 9.0.4
  @nrwl/express : Not Found
  @nrwl/jest : 9.0.4
  @nrwl/linter : 9.0.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.0.4
  @nrwl/react : 9.0.4
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.0.4
  @nrwl/web : 9.0.4
  @nrwl/workspace : 9.0.4
  typescript : 3.7.5
```

**Comment by FrozenPandaz** [comment]
This should have been fixed with https://github.com/nrwl/nx/pull/2886! :tada:
