### ISSUE TITLE
Jest TypeScript Resolver Incorrectly Resolves TSConfig

### ISSUE THREAD

**Issue by victormoukhortov** [nrwl/nx#26337]
### Current Behavior

Jest resolver makes rigid assumptions about TSConfig structure which leads to incomplete resolution of TS config when diverging from NX's default structure.

### Expected Behavior

https://github.com/nrwl/nx/blob/master/packages/jest/plugins/resolver.ts#L18 `getCompilerSetup` should completely resolve the TS config, including arbitrary levels of `extends`, the same way TypeScript itself does. The issue can be fixed by monkey-patching

```TypeScript
JSON.parse(execSync(`npx tsc --showConfig`, { stdio: 'pipe', cwd: path_1.dirname(filename) }).toString());
```

instead of `ts.parseJsonConfigFileContent` and adjusting surrounding code. Unfortunately I don't see that TypeScript directly provides an ESM API equivalent to `--showConfig`. I'm sure a more graceful approach than `npx` is possible.

This fix allows `tsconfig.spec.json` to extend a lib/apps `tsconfig.json` without missing options from `tsconfig.base.json`, and generally allows more flexibility in TS config structure.

### Steps to Reproduce

1. Create an empty project with TypeScript and Jest
2. Remove `tsconfig.json` and extend `tsconfig.lib.json` in `tsconfig.spec.json`
3. Observe failures to resolve other modules in the project

### Nx Report

```shell
Node   : 18.14.1
OS     : darwin-arm64
yarn   : 3.6.1

nx (global)        : 17.1.2
nx                 : 18.3.3
@nx/js             : 18.3.3
@nx/jest           : 18.3.3
@nx/linter         : 18.3.3
@nx/eslint         : 18.3.3
@nx/workspace      : 18.3.3
@nx/cypress        : 18.3.3
@nx/devkit         : 18.3.3
@nx/eslint-plugin  : 18.3.3
@nx/next           : 18.3.3
@nx/plugin         : 18.3.3
@nx/react          : 18.3.3
@nx/storybook      : 18.3.3
@nrwl/tao          : 18.3.3
@nx/vite           : 18.3.3
@nx/web            : 18.3.3
@nx/webpack        : 18.3.3
nx-cloud           : 18.0.1
typescript         : 5.1.6
---------------------------------------
Community plugins:
@jscutlery/semver      : 3.4.1
@nx-tools/nx-container : 5.1.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

The `ts.parseJsonConfigFileContent` parses the configuration recursively and resolves all the `extends`. We need to understand better what your setup is and what specific failures or configuration differences you're seeing. Could you please provide a repo with the setup you're referring to, in which the resolver doesn't work as expected?
