### ISSUE TITLE
package name is not inferred from scope without project.json file

### ISSUE THREAD

**Issue by ixahmedxi** [nrwl/nx#26347]
### Current Behavior

I have my root package.json name to be `orbitkit` and every package in the workspace has the `@orbitkit` scope name so for example, `@orbitkit/utils`.

Whenever I try to run a comman like `nx build utils` it throws out an error saying the project does not exist, works if i do `nx build @orbitkit/utils`.

However, the moment I create a `project.json` file in the package, even if it's empty, I can do `nx build utils`.

### Expected Behavior

I expect the naming of the packages without the scope to be realised by nx without needing to create empty project.json files.

### GitHub Repo

https://github.com/ixahmedxi/orbitkit/tree/nx

### Steps to Reproduce

1. Clone the repo
2. Run `bun install`
3. Run `bun nx build utils`, observe the error
4. Add an empty `project.json` file to `packages/utils`
5. Run `bun nx build utils`, observe that it now behaves as expected.

### Nx Report

```shell
Node   : 20.12.2
OS     : linux-x64
bun    : 1.1.10

nx          : 19.1.2
@nrwl/tao   : 19.1.2
typescript  : 5.4.5
```

### Package Manager Version

bun 1.1.10

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JamesHenry** [comment]
We only use one name as the source of truth for a project.

- In the case of a only package.json file being present there is name in there explicitly, so we use that.
- If you were to set the `name` field in project.json to that same value we would use that and not allow anything else either.

Finally, if a project.json is present, that is the ultimate source of truth, and the behavior you are seeing is that we don't force you to write a name in the project.json file and instead infer it from its location on disk if you don't.

I agree that this combination, where there is a package.json with a name, and a project.json without a name, is currently confusing.

**Comment by AgentEnder** [comment]
Hey - just providing an update here. In `package.json` you can rename the project under the `nx` key. The current behavior where the name changes by adding an empty json file is confusing, we should fall back on the package.json instead.

The linked PR corrects that behavior. We can't safely remove the scope from your project names without a configuration field telling us the new name as it introduces footguns around name collisions.
