### ISSUE TITLE
@nrwl/jest: plugins/resolver doesn't work when using plain jest cli

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#2635]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

one should be still able to run test suite directly via `yarn jest` (so whole codebase can be tested) - yes I know in ideal world this won't be needed 
- this is a must for migration purposes ( going from yarn workspaces/lerna monorepo  to nx)

## Expected Behavior

tweak behaviour `@nrwl/jest/plugins/resolver` so it will still work if `tsconfig.spec.json` is not present within root - for migration purposes

## Current Behavior

Console overflow with 
`...Cannot locate a tsconfig.spec.json. Please create one at /Users/hotell/Projects/devel/productboardlabs/multioss/tsconfig.spec.json`
for every test ( we have 1k+ tests, which basically kills the console)

### Context

```
  @nrwl/angular : Not Found
  @nrwl/cli : 9.0.4
  @nrwl/cypress : 9.0.4
  @nrwl/eslint-plugin-nx : 9.0.4
  @nrwl/express : Not Found
  @nrwl/jest : 9.0.4
  @nrwl/linter : 9.0.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.0.4
  @nrwl/react : 9.0.4
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.0.4
  @nrwl/web : 9.0.4
  @nrwl/workspace : 9.0.4
  typescript : 3.7.5
```

**Comment by Cammisuli** [comment]
This is kinda related to running Jest within VsCode. I'll take care of this.

**Comment by orzarchi** [comment]
any updates on this? @Cammisuli

**Comment by Cammisuli** [comment]
@orzarchi https://github.com/nrwl/nx/pull/3766
