### ISSUE TITLE
 NX   Unsupported payload sent to daemon server: {"type":"GLOB","globs":["**/{vite,vitest}.config.{js,ts,mjs,mts,cjs,cts}"]}

### ISSUE THREAD

**Issue by beeman** [nrwl/nx#26366]
### Current Behavior

I try to create a js lib in my repo and get the message above

### Expected Behavior

I expect to be able to create a js lib

### GitHub Repo

https://github.com/pubkeyapp/verify-solana-wallet/tree/main

### Steps to Reproduce

1. clone the repo above, check out the initial commit (4ea213a)
2. run `pnpm install`
3. run `nx g @nx/js:lib --name verify-solana-wallet --unit-test-runner vitest --bundler vite --directory packages/verify-solana-wallet --project-name-and-root-format as-provided --publishable --import-path verify-solana-wallet  --verbose`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.9.0
OS     : darwin-arm64
pnpm   : 9.0.5

nx                 : 19.2.0-beta.7
@nx/js             : 19.2.0-beta.7
@nx/linter         : 19.2.0-beta.7
@nx/eslint         : 19.2.0-beta.7
@nx/workspace      : 19.2.0-beta.7
@nx/devkit         : 19.2.0-beta.7
@nx/eslint-plugin  : 19.2.0-beta.7
@nrwl/tao          : 19.2.0-beta.7
@nx/vite           : 19.2.0-beta.7
@nx/web            : 19.2.0-beta.7
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
```

### Failure Logs

```shell
$ nx g @nx/js:lib --name verify-solana-wallet --unit-test-runner vitest --bundler vite --directory packages/verify-solana-wallet --
project-name-and-root-format as-provided --publishable --import-path verify-solana-wallet  --verbose

 NX  Generating @nx/js:library

Fetching @nx/eslint...
Packages: +412
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 421, reused 412, downloaded 0, added 412, done

devDependencies:
+ @nx/eslint 19.2.0-beta.7

Done in 7.7s
Fetching @nx/vite...
Packages: +420
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 466, reused 420, downloaded 0, added 420, done

devDependencies:
+ @nx/vite 19.2.0-beta.7

Done in 6.1s

 NX   Unsupported payload sent to daemon server: {"type":"GLOB","globs":["**/{vite,vitest}.config.{js,ts,mjs,mts,cjs,cts}"]}


Error: Unsupported payload sent to daemon server: {"type":"GLOB","globs":["**/{vite,vitest}.config.{js,ts,mjs,mts,cjs,cts}"]}
    at handleMessage (/Users/beeman/dev/github/pubkeyapp/verify-solana-wallet/node_modules/.pnpm/nx@19.1.2/node_modules/nx/src/daemon/server/server.js:102:104)
    at /Users/beeman/dev/github/pubkeyapp/verify-solana-wallet/node_modules/.pnpm/nx@19.1.2/node_modules/nx/src/daemon/server/server.js:45:15
    at Socket.<anonymous> (/Users/beeman/dev/github/pubkeyapp/verify-solana-wallet/node_modules/.pnpm/nx@19.1.2/node_modules/nx/src/utils/consume-messages-from-socket.js:13:17)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:349:9)
    at Readable.push (node:internal/streams/readable:286:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Package Manager Version

pnpm 9.0.5

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Using the latest beta to work around another issue - as per [this suggestion](https://github.com/nrwl/nx/issues/22247#issuecomment-2140001244).

When I run the above command with the DAEMON disabled it works (`NX_DAEMON=false`) as suggested in one of the other issues I faced over the last months.

**Comment by AgentEnder** [comment]
Hey @beeman - Can  you confirm that the issue continues if you run `nx reset` first, and if so, the contents of `node_modules/nx/src/daemon/server/server.js`?

**Comment by elanizi43998** [comment]
Hey @AgentEnder, It still gives me the same error as @beeman even after `nx reset`.
This is my server.js content in the attached file:
[dameon server.pdf](https://github.com/user-attachments/files/15747591/dameon.server.pdf)

**Comment by elanizi43998** [comment]
I've found a workaround, I had to migrate from `19.2.2` to `18.0.3`, after that i deleted `node_modules`, then installed dependencies and it worked.
I know It's not an ideal solution, but It will help If you don't want to be stuck!

**Comment by AgentEnder** [comment]
In 19.2 and higher GLOB is a valid message for the daemon to handle, looking at your attacher daemon server code it's not what should be present in 19.2 though. 

I think running nx reset, followed by rm -rf node modules and reinstalling may fix it

**Comment by karolisKTri** [comment]
> In 19.2 and higher GLOB is a valid message for the daemon to handle, looking at your attacher daemon server code it's not what should be present in 19.2 though.
> 
> I think running nx reset, followed by rm -rf node modules and reinstalling may fix it

Same problem here. Setting up new application. nx reset + deleting node_modules didn't help.

**Comment by lppedd** [comment]
Bumping to avoid stale status.
