### ISSUE TITLE
Schematic "jest-project" not found in collection "@schematics/angular"

### ISSUE THREAD

**Issue by manolof** [nrwl/nx#2639]
## Expected Behavior

When I follow the cookbook on how to migrate from Karma to Jest on an app, and run my `ng generate jest-project --project <project_name>` command, I expect for no errors and for the necessary files to be created/updated.

## Current Behavior

When I run `ng generate jest-project --project <project_name>` I get the following error:

`An unhandled exception occurred: Schematic "jest-project" not found in collection "@schematics/angular".`

If I run `ng generate @nrwl/jest:jest-project --project <project_name>` then I receive error: `Expected apps/<project_name>/tsconfig.json to exist. Please create one.`

In order to move on with my work, I checked in the file `node_modules/@nrwl/jest/src/schematics/jest-project/jest-project.js` and renamed the occurrences of `tsconfig.json` to `tsconfig.app.json`.

### Steps to Reproduce

On a project that has an app with Karma as test runner:
1. Follow the steps 1 to 4 as in https://connect.nrwl.io/app/cookbook/6dr9s4zrcKDzwedZladnWW

### Context

```
  @nrwl/angular : 9.0.4
  @nrwl/cli : 9.0.4
  @nrwl/cypress : 9.0.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.0.4
  @nrwl/linter : 9.0.4
  @nrwl/nest : 9.0.4
  @nrwl/next : Not Found
  @nrwl/node : 9.0.4
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.0.4
  @nrwl/web : Not Found
  @nrwl/workspace : 9.0.4
  typescript : 3.7.5
```

In my angular.json, I have tried with either `cli.defaultCollection: @nrwl/schematics` and without `cli` property.

**Comment by JoA-MoS** [comment]
I also ran into the same issue and used the same steps to resolve. Is this something you are looking for PR to fix? 

Is there a time where it should look for tsconfig.json vs tsconfig.app.json?  Should it look fo a tsconfig.app.json if it doesn't find it then look for a tsconfig.json if it doesn't find either then it errors?

**Comment by FrozenPandaz** [comment]
`jest-project` belongs to `@nrwl/angular` so `@schematics/angular` should indeed not have it. If your `defaultCollection` in `angular.json` is not `@nrwl/angular` you can still invoke `jest-project` by using the verbose form of generate: `ng generate @nrwl/angular:jest-project`. You can also choose to set your `defaultCollection` to `@nrwl/angular`. This should be done automatically in an Nx workspace.

I'm going to close this issue as I think the context in this issue is likely outdated so please open a new issue if the issue persists.

**Comment by topratiksharma** [comment]
on running this we get the below issue..

nx generate @nrwl/angular:jest-project --project <project-Name>
Schematic "jest-project" not found in collection "@nrwl/angular"
