### ISSUE TITLE
feat: handle nx-enforce-module-boundaries depConstraints on external file

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#2640]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Use an external file to configure nx-enforce-module-boundaries rule on eslint and tslint to avoid duplication

## Current Behavior

The configuration is handled in `.eslintrc` and `tslint.json`, if you use both linters, you need to duplicate the config

**Comment by vsavkin** [comment]
Given that the Angular CLI is supposed to switch to eslint in the future, most likely we won't do it, but I'll keep the issue here to track it.

**Comment by stijnvn** [comment]
Currently, the `@nrwl/angular:library` schematic generates a library configured with tslint and `@nrwl/workspace:library` generates one configured with eslint by default. In our workspace this introduced the eslint dependency and it is confusing that the nx-enforce-module-boundaries rule was out of sync. Would it be an option to have the same default linter for every library schematic?
