### ISSUE TITLE
Build target of nestjs project not easy to configure

### ISSUE THREAD

**Issue by spotlesscoder** [nrwl/nx#26405]
### Current Behavior

Created a new monorepo with create-nx-workspace
Created nestjs app with @nx/nest

It creates a project.json with no explicitly defined "build" target
I want to add a prebuild step to execute a script that generates static assets before starting the nestjs project build

I have no place I can quickly get the default build target json code for to just add a `dependsOn` property

### Expected Behavior

There should be some way to easily insert the default build target code (maybe through a cli command and/or nx console vscode plufgin)

### Steps to Reproduce

see above

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.2.0
OS     : linux-x64
npm    : 9.6.6

nx (global)        : 19.2.0
nx                 : 19.2.0
@nx/js             : 19.2.0
@nx/jest           : 19.2.0
@nx/linter         : 19.2.0
@nx/eslint         : 19.2.0
@nx/workspace      : 19.2.0
@nx/devkit         : 19.2.0
@nx/eslint-plugin  : 19.2.0
@nx/nest           : 19.2.0
@nx/next           : 19.2.0
@nx/node           : 19.2.0
@nx/playwright     : 19.2.0
@nx/react          : 19.2.0
@nrwl/tao          : 19.2.0
@nx/web            : 19.2.0
@nx/webpack        : 19.2.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/next/plugin
@nx/playwright/plugin
@nx/eslint/plugin
@nx/jest/plugin
@nx/webpack/plugin
```

### Package Manager Version

npm 9.6.6

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Hello @spotlesscoder 👋 

You can add a partial configuration here to specify only depends on. You don't need to specify the full inferred configuration. e.g., if you wanted to add a codegen step it may look like:

```
{
  "targets": {
    "build": {
      "dependsOn": ["codegen"]
    },
    "codegen": {
      "command": "...."
    }
  }
}
```

**Comment by spotlesscoder** [comment]
Thanks :) 
I think this fact should be made more obvious in the documentation
