### ISSUE TITLE
Generated package.json file missing dependencies since 19.1.2

### ISSUE THREAD

**Issue by PodStuart** [nrwl/nx#26410]
### Current Behavior

Versions 19.1.2 and 19.2.0 appear to have introduced some regression whereby the generated package.json file is missing some dependencies.

### Expected Behavior

Generated package.json file is not missing dependencies.

### Steps to Reproduce

Really quite difficult to create a minimal reproduction since this is happening in a monorepo with 20 apps and dozens of dependencies.

### Nx Report

```shell
Node   : 20.14.0
OS     : darwin-arm64
npm    : 10.7.0

nx                 : 19.2.0
@nx/js             : 19.2.0
@nx/jest           : 19.2.0
@nx/linter         : 19.2.0
@nx/eslint         : 19.2.0
@nx/workspace      : 19.2.0
@nx/cypress        : 19.2.0
@nx/devkit         : 19.2.0
@nx/eslint-plugin  : 19.2.0
@nx/nest           : 19.2.0
@nx/next           : 19.2.0
@nx/node           : 19.2.0
@nx/react          : 19.2.0
@nx/storybook      : 19.2.0
@nrwl/tao          : 19.2.0
@nx/web            : 19.2.0
@nx/webpack        : 19.2.0
typescript         : 5.4.3
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
---------------------------------------
Community plugins:
@nx-go/nx-go                 : 3.1.0
@trumbitta/nx-plugin-openapi : 1.12.1
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Configuration from one of our build targets.

`    "build": {
      "executor": "@nx/webpack:webpack",
      "outputs": ["{options.outputPath}"],
      "options": {
        "target": "node",
        "compiler": "tsc",
        "outputPath": "dist/apps/commercial/destination/site-admin-api",
        "main": "apps/commercial/destination/site-admin-api/src/main.ts",
        "tsConfig": "apps/commercial/destination/site-admin-api/tsconfig.app.json",
        "tsPlugins": ["@nestjs/swagger/plugin"],
        "webpackConfig": "apps/commercial/destination/site-admin-api/webpack.config.js",
        "generatePackageJson": true
      },`

**Comment by Nick-Lucas** [comment]
Also seeing this here on 19.2.0 after upgrading from 19.0.0

tRPC is missing from our API, which is weird since it's imported in many places and never conditionally - also sort of the most important dependency for our API!

**Comment by FrozenPandaz** [comment]
@Nick-Lucas could you see what version of `@trpc/server` you are using? 

I think this repo showcases the same @trpc/server depenency missing but I'm not sure.

@meeroslav can you take a look please?

**Comment by Nick-Lucas** [comment]
> @Nick-Lucas could you see what version of `@trpc/server` you are using?
> 
> I think this repo showcases the same @trpc/server depenency missing but I'm not sure.
> 
> @meeroslav can you take a look please?

`11.0.0-rc.382`

Now I think of it here's a diff of everything which changed between 19.0.0 and 19.2.0

![image](https://github.com/nrwl/nx/assets/8896153/7d57c299-6873-47fc-bf01-c3af70b3eb0c)

the react and react-query stuff also appears to have been correctly there originally since we use the @trpc/react-query package for some TS type imports in the API and it would all get dragged in if Nx isn't filtering `import type {} from` out.
