### ISSUE TITLE
[QUESTION] @nrwl/jest no public API

### ISSUE THREAD

**Issue by klaascuvelier** [nrwl/nx#2642]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- ~I am running the latest version~
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

_n/a_

## Current Behavior

It's not possible to create a builder that extends the current `@nrwl/jest` implementation because no code is exported through the main package file.
### Context

I was wondering if there's a specific reason the `@nrwl/jest` package has no public api that can be used to create a custom builder that extends the existing implementation.

The builders from `@angular/devkit` are available, e.g.:
```
import { executeBrowserBuilder } from '@angular-devkit/build-angular';
```

In our NX monorepo we have a lib (tslint rules) that needs to be transpiled to JS (not through Jest transpilation) before we run the Jest scripts. So I wanted to create a custom builder that first transpires the source files and and then runs the default Jest builder. 
I was not able to do so because it's not possible to get to the `run` method from the `@nrwl/jest` builder.

**Comment by vsavkin** [comment]
I think we should export the builder.

**Comment by klaascuvelier** [comment]
Thanks for answering @vsavkin.

I was looking into making an MR for this but have a couple of questions.
- This seems like an improvement that could be done on earlier versions of NX. What's the process for that. Do I just create multiple MRs with targets to earlier versions?
- Do I do only do this for the Jest builder, or do I do this for more builders (~express~, ~nest~, next, node, ..)
- Is there a convention for exports naming, do I just export `run` from the jest builder, or should it be renamed?
