### ISSUE TITLE
NodeJs app unable to use a node library with a imported JSON

### ISSUE THREAD

**Issue by frzyc** [nrwl/nx#26431]
### Current Behavior

Importing a lib from a NodeJs app seem to unable to access the JSON file imported from a lib. 
This lib works in other apps, like vite/react apps.

### Expected Behavior

Importing a lib that imports a JSON file should work from a NodeJs App.

### GitHub Repo

https://github.com/frzyc/nx_import_lib_json

### Steps to Reproduce

1. Run `npx create-nx-workspace@latest` to create a new NX repo using Integrated monorepo, with a NodeJs app
2. Create a shared node library called utils: `npx nx generate @nx/node:library --name=utils --directory=libs/utils --projectNameAndRootFormat=as-provided --unitTestRunner=none --no-interactive`
3. Modify utils to import from a JSON file:
```Typescript
import * as data from "./data.json"
export function utils() {
  return data;
}
```
4. Add `"resolveJsonModule": true` to `libs/utils/tsconfig.json` in `compilerOptions`
5. Modify `apps/nx_import_lib_json/src/main.ts` to include the `utils` function:
```Typescript
import { utils } from "@nx-import-lib-json/utils"
console.log(utils());
```
6. Add `"resolveJsonModule": true` to `apps/nx_import_lib_json/tsconfig.json` in `compilerOptions`
7. Run the app using `nx serve nx_import_lib_json`

### Nx Report

```shell
Node   : 20.10.0
OS     : win32-x64
npm    : 10.2.3

nx                 : 19.2.0
@nx/js             : 19.2.0
@nx/jest           : 19.2.0
@nx/linter         : 19.2.0
@nx/eslint         : 19.2.0
@nx/workspace      : 19.2.0
@nx/devkit         : 19.2.0
@nx/esbuild        : 19.2.0
@nx/eslint-plugin  : 19.2.0
@nx/node           : 19.2.0
@nrwl/tao          : 19.2.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/jest/plugin
```

### Failure Logs

```shell
Error: Cannot find module './data.json'
Require stack:
- F:\Project\nx_import_lib_json\dist\apps\nx_import_lib_json\libs\utils\src\lib\utils.js
- F:\Project\nx_import_lib_json\dist\apps\nx_import_lib_json\libs\utils\src\index.js
- F:\Project\nx_import_lib_json\dist\apps\nx_import_lib_json\apps\nx_import_lib_json\src\main.js
- F:\Project\nx_import_lib_json\dist\apps\nx_import_lib_json\main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Function.Module._resolveFilename (F:\Project\nx_import_lib_json\tmp\nx_import_lib_json\main-with-require-overrides.js:41:36)
    at Function.Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.Module._load (F:\Project\nx_import_lib_json\node_modules\@nx\js\src\executors\node\node-with-require-overrides.js:18:31)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (F:\Project\nx_import_lib_json\libs\utils\src\lib\utils.ts:1:23)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Hey, I see the problem is you have to set `bundle: false` for your node app.

We should generate this by default so it works out of the box. Should you need to get something working immediately you could make that change or wait for the patch to go out.

**Comment by ndcunningham** [comment]
You need to turn bundling on inside of your node app's project.json 
`bundle: true`
