### ISSUE TITLE
Splitting nx.json and angular.json per project

### ISSUE THREAD

**Issue by eliasdarruda** [nrwl/nx#2643]
Hey! 

It would be very cool if we could have a tool to split configuration files like angular.json or nx.json per app/lib
Currently we are working in the same repo with a lot of different projects and a lot of people, we always end up having to solve conflicts on these files.

Angular CLI does not support splitting angular.json by default, so we could put a angular-project.ts inside each lib or app and then run a script to concatenate every entry into angular.json

The same idea would work for nx.json, or maybe on nx.json just a flag to search in the directories for a nx.json file or something.

Is there anyone with a similar solution to share?

**Comment by dogmatico** [comment]
Solving this, even with JSON pointers to external files, will be a great quality of life improvement. Conflicts arising in those files when multiple branches create libraries and projects require, unless I'm doing it wrong and there is a better way, require meticulous work to solve and a bit of understanding of the structure of angular/nx.json.

**Comment by vsavkin** [comment]
I'm with you folks! We work with a lot of clients with 10k angular/workspace json files. So definitely something we are thinking about.

**Comment by eliasdarruda** [comment]
I made a package to solve this problem, it comes with the cost of having to run a command before every serve and build action to merge the files.
However I don't see any way out of this behaviour for angular.json file.

This plugin solves the conflict and complexity problem for "nx.json", "angular.json" and "tsconfig.json" files.

It would be nice if we could see in the future a flag to at least do it automatically on nx.json file

The package:
https://github.com/eliasdarruda/nx-config-splitter

**Comment by jsaguet** [comment]
How about alphabetically ordering projects in nx.json, angular.json, tsconfig.json to reduce conflicts ?
Like suggested in #2607, it would help to automatically resolve conflicts if modified lines are not the same.
Maybe it is not adapted to very large projects but it could help for smaller ones

**Comment by BenjaminDobler** [comment]
I wrote an extension for visual studio code to help me deal with large angular.json files.
The extension allows you to right click on a project on visual studio code and only open this part of the angular.json in a "virtual" editor. You can edit the partial and save your changes back to the angular.json.
It is basically like each project has it's own angular.json but it's all virtually.
Here is the link: https://marketplace.visualstudio.com/items?itemName=richapps.ng-config
If there is interest this could maybe also be integrated into nx console!?

**Comment by kylecordes** [comment]
We have a project with a 20,000+ line angular.json file; we gave up maintaining this by hand or with schematics, and instead regenerate it frequently based on clues our ad hoc generator gets from the contents of the projects.

So… +1.

**Comment by americoneto1** [comment]
@vsavkin is there any plan on NX roadmap to solve this issue?

@eliasdarruda schematics changes the content of these files (angular.json, nx.json, etc). I would like to know if your solution also changes the content of base files.

**Comment by eliasdarruda** [comment]
> @vsavkin is there any plan on NX roadmap to solve this issue?
> 
> @eliasdarruda schematics changes the content of these files (angular.json, nx.json, etc). I would like to know if your solution also changes the content of base files.

Base files will stay frozen from the point you copied your original angular.json file to a .base file, it proved to be a good solution for our team, after implementing it we never had to solve conflicts of these files again

**Comment by bubblegumsoldier** [comment]
> We have a project with a 20,000+ line angular.json file; we gave up maintaining this by hand or with schematics, and instead regenerate it frequently based on clues our ad hoc generator gets from the contents of the projects.
> 
> So… +1.

Which ad hoc generator do you use? Is it a proprietary one or open source?

 

> > @vsavkin is there any plan on NX roadmap to solve this issue?
> > @eliasdarruda schematics changes the content of these files (angular.json, nx.json, etc). I would like to know if your solution also changes the content of base files.
> 
> @americoneto1 Base files will stay frozen from the point you copied your original angular.json file to a .base file, it proved to be a good solution for our team, after implementing it we never had to solve conflicts of these files again

I really like your project but I am a bit scared about building a companies platform on a one-person repository dependency at the core of project structure. Are there any plans on how you are going to maintain the project considering angular updates, etc? Or do you know about any other alternatives?

**Comment by bubblegumsoldier** [comment]
> I'm with you folks! We work with a lot of clients with 10k angular/workspace json files. So definitely something we are thinking about.

Are there specific plans, tickets or similar currently open?

**Comment by jimbarrett33** [comment]
Very interested in a built-in NX solution for this. In general, different teams work on different apps in the monorepo with different build configurations but use common libraries under /libs. So even if there was just a single "libs.angular.json" with all the libs and an "app-<name>.angular.json" for each app that would help a lot. The lib entries in angular.json are fairly standard format and changes would be much easier to merge without all the apps embedded in the same angular.json.

**Comment by labeled** [comment]
+1 for this feature. We've just begun with nx console and have noticed merge conflicts when multiple developers create libs/apps in different branches. I know JSON doesn't like the trailing comma in it but that would help resolve merge conflicts. That or adding a new lib / project to the beginning instead of the end of the projects property.

**Comment by labeled** [comment]
+1

**Comment by areknow** [comment]
Agreed that a built in NX solution would be great! We are scaling fast and are feeling the conflict pains in our angular.json file and other root files. Thanks!

**Comment by josecolella** [comment]
Definitely agree that as best practices dictate to generate libs and modularize features into libs, this problem will only get worse.

**Comment by kylecordes** [comment]
@bubblegumsoldier 

> Which ad hoc generator do you use? Is it a proprietary one or open source?

Just a couple hundred lines of TypeScript we wrote, full of assumptions of the specific shape of the projects in our workspace. So proprietary... but not useful to anyone's else workspace anyway.

**Comment by cfrim** [comment]
What is the progress on this issue?

**Comment by PetarKirov** [comment]
> We have a project with a 20,000+ line angular.json

This must be cruel joke... does anyone consider this even remotely workable!? My personal tolerance for manually maintained json files is 300 LoC. I can't believe that a project which claims to offer workflow benefits for medium to large projects hasn't addressed this since day 1!

**Comment by nephi5** [comment]
I have recently migrate our angular app to nx workspace. It has been so far a never ending mind blowing experience. :exploding_head:  Creating libraries and apps like there is no tomorrow :smile: . It would be really great to have this feature. :+1:

**Comment by kumaravnish** [comment]
+1

**Comment by jimbarrett33** [comment]
Adding comment so the bot doesn't close this. That I'm still very interested in this feature. Not sure of the point of having bots automatically closing issues.

**Comment by americoneto1** [comment]
+1

**Comment by samartomar** [comment]
need utility to put files.

**Comment by ramyhhh** [comment]
+1

**Comment by markhus-aurelius** [comment]
Also finding this painful to manage at work. Would love if the nx team could try to address it 👍

**Comment by willyou** [comment]
+1

**Comment by mehrad-meraji** [comment]
+1

**Comment by svanda-navisys** [comment]
Right, I'd like to at least ask how people solve this issue in practise, we have a monorepo with merely 3 apps, but as people add libs in different branches, there are *always* merge conflicts happening in all of: `workspace.json`, `tsconfig.base.json`, `jest.config.js` and `nx.json`. Most of them can be solved by "accepting both changes", but sometimes the braces are wrong and we have to manually fix the layout. I can't imagine having to do this when we have as little as 100 libs. It almost feels like a NX monorepo is meant to be maintained by a single developer at a time.

Maybe there are some workflows around this? Like only creating new libs/apps in the base branch an then working on them later in feature branches, when the changes in common files are commited? I don't know, maybe I'm missing something obvious, but this issue alone is a BIG hurdle for *rapid developlement*.

**Comment by labeled** [comment]
We've implemented an auto formatting of json files in alphabetical order
which has helped drastically reduce the merge conflicts. Check out prettier
it can do it.

**Comment by AgentEnder** [comment]
@svanda-navisys As labeled says, auto-formatting these files in alphabetical order (via prettier, a workspace schematic, or so on) does help quite a bit. As you proposed, workflows where you create all libs / apps in trunk and then develop on them in the feature branches can help as well.

The linked PR is not ready yet, but is something I am actively working on. It will solve this issue for 2/4 of the files (nx.json and workspace/angular.json). The other 2 are a bit simpler to solve conflicts with in most cases.

**Comment by josecolella** [comment]
@svanda-navisys With the project I work with, we ended up adding a git hook for sorting the nx.json and angular.json

```sh
sort-json ./angular.json ./nx.json ./tsconfig.base.json
```
