### ISSUE TITLE
19.1.1 targetDefaults change of behavior

### ISSUE THREAD

**Issue by kirjai** [nrwl/nx#26436]
### Current Behavior

The behavior of targetDefaults has changed between version 19.1.0 and 19.1.1?

Having targetDefaults defined for both the target name, as well as the executor - ignores the targetDefaults defined by target name (or the one that's defined first, perhaps).

### Expected Behavior

targetDefaults for both target name and executor should be merged, as was the behavior before 19.1.1

Unless that's the new intended behavior and the fact that it used to work previously was a bug

### GitHub Repo

https://github.com/kirjai/glowing-carnival

### Steps to Reproduce

1. go to the "repro" commit in the repo (efe7e7328474425312f901a4748b20a3d0a90499)
this commit is on version 19.1.0.
2. run `npx nx test my-app`
You should see two logs - "Hello My Target", and "Hello Test"

^ above steps outline the expected behavior

3. Check out the latest commit, that is on version 19.1.1
4. after re-installing dependencies, running same command - `npx nx test my-app`
5. You will see only one log - "Hello Test". indicating that the "dependsOn" defined in `targetDefaults.test` is now (incorrectly?) ignored

### Nx Report

```shell
Node   : 18.20.2
OS     : darwin-arm64
npm    : 10.5.0

nx                 : 19.1.1
@nx/js             : 19.1.1
@nx/jest           : 19.1.1
@nx/linter         : 19.1.1
@nx/eslint         : 19.1.1
@nx/workspace      : 19.1.1
@nx/devkit         : 19.1.1
@nx/eslint-plugin  : 19.1.1
@nx/next           : 19.1.1
@nx/playwright     : 19.1.1
@nx/react          : 19.1.1
@nrwl/tao          : 19.1.1
@nx/web            : 19.1.1
@nx/webpack        : 19.1.1
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/next/plugin
@nx/playwright/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Suspected PR:
https://github.com/nrwl/nx/pull/26033

with love to the whole Nx team 🖤

**Comment by FrozenPandaz** [comment]
This is the new intended behavior. If you relied on this incorrect behavior, I think the best way to resolve it would be to add the `dependsOn` to the executor `targetDefaults`. I believe that would solve your issue.
