### ISSUE TITLE
Module Federation host build failing due to remote error

### ISSUE THREAD

**Issue by bouncehead13** [nrwl/nx#26474]
### Current Behavior

I was upgrading my Module Federation app from Nx 15 to Nx 19 (I know big jump). The migration was going smoothly until I started testing the production builds. I noticed the host app (`shell`) is not working.

What I narrowed it down to is the shell now has a dynamic link to `app1`. This can also been seen in the Nx Graph.
<img width="142" alt="Screenshot 2024-06-08 at 9 02 51 PM" src="https://github.com/nrwl/nx/assets/4275875/75930141-0c00-4d22-b480-8779dd78d81a">

This dynamic link is caused by the new approach to use tsconfig `paths` over the older `remotes.d.ts` approach.
```
"paths": {
  "app1/Module": ["apps/app1/src/remote-entry.ts"]
}

// vs remotes.d.ts
declare module 'app1/Module';
```

In fact, commenting out the tsconfig `paths` and commenting in the contents of `remotes.d.ts` removes the dynamic link and allows the host (`shell`) to build successfully.

In the reproducible GIT Repo provided, I forced an error with a wrong variable name `console.log(faill)` which triggers the behavior described above.

### Expected Behavior

Host should be able to build independently of its remotes given Module Federation doesn't have any explicit link between them.

### GitHub Repo

https://github.com/bouncehead13/nx-build-failure

### Steps to Reproduce

1. Clone the repo and install packages
2. Run `npx nx run shell:build`
3. Notice how it errors because of an error in `app1`

### Nx Report

```shell
Node   : 18.19.0
OS     : darwin-arm64
npm    : 10.2.3

nx                 : 19.2.2
@nx/js             : 19.2.2
@nx/jest           : 19.2.2
@nx/linter         : 19.2.2
@nx/eslint         : 19.2.2
@nx/workspace      : 19.2.2
@nx/devkit         : 19.2.2
@nx/eslint-plugin  : 19.2.2
@nx/react          : 19.2.2
@nrwl/tao          : 19.2.2
@nx/web            : 19.2.2
@nx/webpack        : 19.2.2
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

### Failure Logs

```shell
> nx run shell:build:production

Entrypoint main = main.84be68696647cccd.js
Entrypoint styles = styles.5f4524c1fa820eae.css styles.0cde17e5fe195ca1.js
chunk (runtime: main, styles) 41.a2dff550eae61628.js 6.95 KiB [rendered]
chunk (runtime: main, styles) 144.9e5bebabe50d80ae.js (id hint: vendors) 134 KiB [rendered] reused as split chunk (cache group: defaultVendors)
chunk (runtime: main) 42 bytes
chunk (runtime: main) 785.9d7285bc75864b68.js 60.6 KiB (javascript) 84 bytes (consume-shared) [rendered]
chunk (runtime: main) main.84be68696647cccd.js (main) 98 bytes (javascript) 126 bytes (share-init) 20.8 KiB (runtime) [entry] [rendered]
chunk (runtime: styles) styles.5f4524c1fa820eae.css, styles.0cde17e5fe195ca1.js (styles) 50 bytes (javascript) 80 bytes (css/mini-extract) 126 bytes (share-init) 18.9 KiB (runtime) [entry] [rendered]
chunk (runtime: main, styles) 913.8ba3bde4aed38d66.js (id hint: vendors) 228 KiB [rendered] reused as split chunk (cache group: defaultVendors)
chunk (runtime: main) 6 bytes (remote) 6 bytes (share-init)
chunk (runtime: main, styles) 42 bytes reused as split chunk (cache group: default)

ERROR in ./apps/app1/src/app/app.tsx:8:15
TS2552: Cannot find name 'faill'. Did you mean 'fail'?
     6 | export function App() {
     7 |   const fail = 'hello';
  >  8 |   console.log(faill);
       |               ^^^^^
     9 |
    10 |   return (
    11 |     <div>

webpack compiled with 1 error (c70372bdd06d32fb)

———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target build for project shell (5s)

   ✖  1/1 failed
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I'm not sure how to proceed forward using the new approach so my workaround is manually maintaining the `remotes.d.ts` file. However, I would like to not do that and use the scaffolding Nx provides. I am not sure if I am missing something or a defect in how the bundlers are compiling the code.

**Comment by ndcunningham** [comment]
This is intended. 
If you want your shell to be built standalone you would have to change your remote declaration:
```js
  remotes: ['app1'],
  ```
To use something like [promise-based remotes](https://webpack.js.org/concepts/module-federation/) where the remote is only known at run-time.

Change back to use `remote.d.ts` just removes the type safety that was added. 
So instead of getting the error at build time, you would get it at run time.

When you generate a host you can pass the `--dynamic` flag for this to be set up. However, since the remote deployment can be customized we leave that implementation up to you.

```
npx nx generate @nx/react:host host \
--dynamic true \
--remotes myremote
```

**Comment by bouncehead13** [comment]
Thank for getting back to me @ndcunningham! Maybe I didn't explain well our use-case and the problem Nx introduced.

So this is a monorepo and we could have different teams owning different portions of the site, but all known during build time. Say Team A manages the host/shell application while Team B manages a singular remote `app1`. However, the individual team should be able to deploy separately. Meaning as Team A makes updates to the Shell and deploys, Team B could be "breaking" their code but a week out from deploying. Still Team A can go live with their modifications.

You're suggesting in this case, rather than having Shell know about App1 during build time (aka the remote entry file), make it known during run time with dynamic imports.

So it's a conciseness design and not a bundler defect that all remotes are "built" when the Shell/Host gets built? Seems like an anti-pattern of MFE.

**Comment by Coly010** [comment]
@bouncehead13 Not necessarily an anti pattern.

MFE is just a general term used for a technique that involves loading certain portions of the frontend application remotely.
It could be iframes for example.

What we have learned over the years of supporting MFE architectures boils down to two main use cases:

1. Faster builds
2. Independent Deployability

We optimized what we generate out of the box for faster builds, as that was the overwhelming majority of why people were reaching for MFE.

If your use case is Independent Deployability then you can still achieve it along with type safety.

1. Make sure there are no implicitDependencies in your host’s project.json file.
2. Add `// nx-ignore-next-line` above the imports in your host for the remotes (this will remove any edge created in the project graph between the two projects)

With that being said, we would still recommend that if you redeploy your host/shell application, that you _should_ redeploy all your remote applications. 

Your shell may have bumped a version of a package that your already-deployed remotes also used, and now that package can no longer be shared. This holds true also for workspace libraries, wherein you could break singletons. I.e if you rely on a singleton source for application state shared across remotes, then you could introduce a runtime-only breaking change. 

Whereas redeploying everything when shell is changed helps prevent these potential issues at runtime.

We would also recommend for general development practice that your applications should always be in a deployable state (even if it’s an old state, this could mean feature branches for individual remotes, or using a feature flag setup) when working with MFEs.

This also helps ease the deployment burden by knowing that you _can_ always deploy everything without breaking production.

For example, if a security vulnerability was found in a package that all your host and remotes use, and you need to release a hot fix immediately to patch that vulnerability, it’s a simple case of adding the patch and redeploying everything.
