### ISSUE TITLE
`nx release`: fails when executed outside the workspace root directory

### ISSUE THREAD

**Issue by Badisi** [nrwl/nx#26492]
### Current Behavior

Consider:
- the following project structure:
```
.
├── projects
│  └── package-a
│     └── ...
├── ...
```
- the following `nx.json` configuration:
```json
"release": {
    "projectsRelationship": "independent",
    "version": {
        "conventionalCommits": true
    },
    "changelog": {
        "projectChangelogs": {
            "createRelease": "github"
        }
    }
}
```

----

#### Issue
<br/>

Running `nx release -p=package-a` from within `projects/package-a/` folder, will trigger the following issue:
```bash
...

NX   Updating npm lock file
Updating package-lock.json with the following command:
npm install --package-lock-only

NX   Staging changed files with git
Staging files in git with the following command:
git add projects/package-a/package.json package-lock.json

NX   fatal: pathspec 'projects/package-a/package.json' did not match any files
```

> NB: why am I running the command from there ? It's because I have a generic Github workflow that takes a working directory and executes different pipeline commands from there (ie. lint, test, build, release) and expects each commands to be in the **package.json** of each package.

----

#### Solution
<br/>

The issue relies in `gitAdd()`:
https://github.com/nrwl/nx/blob/9280c9a8d9637b9c11fbc4d0f47fff2f6141f54c/packages/nx/src/command-line/release/utils/git.ts#L219
called here:
https://github.com/nrwl/nx/blob/9280c9a8d9637b9c11fbc4d0f47fff2f6141f54c/packages/nx/src/command-line/release/version.ts#L311

Because the paths given to `git` (through the `commandArgs`) are always relatives to the workspace root directory, the `execCommand` should always be executed from there:
```ts
return execCommand('git', commandArgs, { cwd: WORKSPACE_ROOT_DIR ); 
```

> NB: using `../../` in place of WORKSPACE_ROOT_DIR worked in my case, but I will let you figure out how to get the actual value in a generic way from that part of your code.

### Expected Behavior

The command `nx release` should work anywhere.

### Steps to Reproduce

None

### Nx Report

```shell
Node   : 18.18.2
OS     : darwin-x64
npm    : 10.8.0

nx (global)    : 19.0.4
nx             : 19.2.0
@nx/js         : 19.2.0
@nx/workspace  : 19.2.0
@nx/devkit     : 19.2.0
@nrwl/tao      : 19.2.0
typescript     : 4.7.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JamesHenry** [comment]
Thanks @Badisi I'll get this fixed up now.

FYI I highly recommend leveraging https://www.npmjs.com/package/patch-package for such things in future, will give you a much cleaner and less manual way to patch things

**Comment by Badisi** [comment]
Yeah, I tend to be a bit old-school sometimes... 😅

Thanks for the reactivity !
