### ISSUE TITLE
Unexpected token when creating workspace on existing app

### ISSUE THREAD

**Issue by chilli-andrew** [nrwl/nx#265]
I am getting the following error:

c:\dev\myproject\src\AngularSpa>ng generate workspace mycurrentapp --collection=@nrwl/schematics
Error: Unexpected token ﻿ in JSON at position 0
Unexpected token ﻿ in JSON at position 0

My setup is as follows:
Windows 10
ng version 1.6.8

I have installed npm install --save-dev @nrwl/schematics and updated my local version of ng to 1.6.8.

Any help/suggestions would be appreciated as the error message doesn't give much away.  I have also tested my .angular-cli.json, tsconfig.json, package.json to confirm that the json in those files will parse.

**Comment by chilli-andrew** [comment]
It appears that the migration partially works as my project files are moved to the new workspace but the .angular-cli.json has not been updated.

**Comment by Shmow** [comment]
I'm also running into this problem. Although my error reads:
Error: Unexpected token **?** in JSON at position 0
Unexpected token **?** in JSON at position 0

Upgraded from angular-cli 1.2.7 to 1.70 (because 1.2.7 does not have schematics at all)
npm -v = 5.6.0
node -v = v8.9.4
Windows Server 2012 R2

Since angular-cli does not provide a whole lot of logging it's tough to see where the problem is. Maybe plain old file encoding?

**Comment by vsavkin** [comment]
Could you provide a github repo with a repro?

**Comment by chilli-andrew** [comment]
I won't be able to supply a repo for you although I did manage to get around the issue by doing the necessary changes manually.

**Comment by Shmow** [comment]
@chilli-andrew Mind telling me what those changes were?

**Comment by chilli-andrew** [comment]
@Shmow. If your files weren't copied across to the new apps/yourproject folder you will need to do this manually. What I did next was to create a new nx workspace in a different directory using create-nx-workspace and then generated an app. I used this app to compare .angular-cli.json and copy the relevant changes e.g. to the "apps" node (you may want to create an app and a lib so you can see how this  affects the "apps" node). I then checked out the packages.json to get any missing angular packages. The tsconfig.json and tsspec.config.json files also need updating and the tsconfig.app.json in your yourproject/app/src directory will also need to be adjusted.  Basically your application should follow the structure of the nx workspace you have created.
