### ISSUE TITLE
nx graph --affected --file=graph.json not working correctly

### ISSUE THREAD

**Issue by Suldenkov** [nrwl/nx#26501]
### Current Behavior

After upgrade to 19.1.1 from 17.0.2. In comand nx graph --affected --file=graph.json fields disappeared affectedProjects and now it’s not clear how to find out which projects are affected.

### Expected Behavior

It is possible to identify affected projects

### Steps to Reproduce

nx graph --affected --file=graph.json 

### Nx Report

```shell
nx                 : 19.1.1
@nx/js             : 19.1.1
@nx/jest           : 19.1.1
@nx/linter         : 19.1.1
@nx/eslint         : 19.1.1
@nx/workspace      : 19.1.1
@nx/angular        : 19.1.1
@nx/cypress        : 19.1.1
@nx/devkit         : 19.1.1
@nx/eslint-plugin  : 19.1.1
@nrwl/tao          : 19.1.1
@nx/web            : 19.1.1
@nx/webpack        : 19.1.1
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by sovcharenko** [comment]
`affected` seem to be broken:

```
yarn --silent nx show projects --json --affected --withTarget=lint --base=0626ea8669414acab7b1e7be191066e0b7251881 --head 3acbd6024c094dccb7eb8a69bbe67f181022735b
```
reports everything while there is not a single change between `base` and `head`

**Comment by FrozenPandaz** [comment]
`nx graph --affected --file=graph.json` has deprecated long ago in version `16.1.0` and was warning since then. This information can now be retrieved by appending `--graph` to your `nx affected` command. 

https://nx.dev/deprecated/affected-graph

> affected seem to be broken:

> yarn --silent nx show projects --json --affected --withTarget=lint --base=0626ea8669414acab7b1e7be191066e0b7251881 --head 3acbd6024c094dccb7eb8a69bbe67f181022735b
> reports everything while there is not a single change between base and head

This seems like a different issue, please open a new issue. Also, please check if there really are no changes between those diffs. The command you can use is:
```
git diff --name-only --no-renames --relative "${base}" "${head}"
```

**Comment by Suldenkov** [comment]
Can you tell me exactly how to use it nx affected with --graph? When I use nx affected, I need to select --target but I don't need it. I just want to build a graph of affected projects.

**Comment by Suldenkov** [comment]
I just saw in the documentation a recommendation to use nx graph --affected instead of affected:graph but you said she was deprecated. Can you tell me if this is an error in the documentation or if I misunderstood something?

Message in documentation: `Deprecated: Use nx graph --affected, or nx affected --graph instead depending on which best suits your use case. The affected:graph command was removed in Nx 19.`
