### ISSUE TITLE
NPE on task runner

### ISSUE THREAD

**Issue by gkamperis** [nrwl/nx#26506]
### Current Behavior

I am hitting this bug throwing a NPE with a MFE setup and buildable libs

This line accesses `targetConfiguration` with no truthy check
https://github.com/nrwl/nx/blob/8351cb11f30d14fc508320da3107a138c92fb289/packages/nx/src/tasks-runner/utils.ts#L204

however next line 
https://github.com/nrwl/nx/blob/8351cb11f30d14fc508320da3107a138c92fb289/packages/nx/src/tasks-runner/utils.ts#L205
shows this can be possibly undefined

and even further down

https://github.com/nrwl/nx/blob/8351cb11f30d14fc508320da3107a138c92fb289/packages/nx/src/tasks-runner/utils.ts#L209C2-L209C38

### Expected Behavior

To not throw

### Steps to Reproduce

Set up MFE with dev remotes and buildable libs.
Try building the remote on its own

### Nx Report

```shell
N/A
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by gkamperis** [comment]
is this not as easy as adding a `?.` ?

**Comment by xiongemi** [comment]
it is fixed in pr https://github.com/nrwl/nx/pull/26721
