### ISSUE TITLE
nx/expo not showing QR

### ISSUE THREAD

**Issue by monojitwithu** [nrwl/nx#26529]
### Current Behavior

Not showing qr and other sideloading option after metro starts

### Expected Behavior

Should show QR and other side loading option 

### Steps to Reproduce

1.Create any expo app with nx
nx start app

### Nx Report

```shell
added 986 packages, and audited 987 packages in 1m

129 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

 NX  Generating @nx/workspace:preset

Fetching prettier...
Fetching @nx/detox...

 NX   Cannot find configuration for 'App name'

Pass --verbose to see the stacktrace.


 NX   Workspace creation failed, see above.

Pass --verbose to see the stacktrace.


npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
i submit a pr to fix this on windows: https://github.com/nrwl/nx/pull/26493
the workaround for now would be add to your project.json's targets:
```
"targets": {
  "start": {
      "executor": "@nx/expo:start"
  }
}
```

**Comment by monojitwithu** [comment]
Now Start command is working fine.
But still QR issue is not fixed.
Expo TUI is not showing.
Should show this 
<img width="320" alt="image" src="https://github.com/nrwl/nx/assets/84927543/f1adce8b-6df9-41ca-9b42-dff250600e81">

But getting this only 
<img width="296" alt="image" src="https://github.com/nrwl/nx/assets/84927543/cc564746-18c8-4605-bc17-4e24fd53bf29">

Please let me know if you have a fix for this

**Comment by xiongemi** [comment]
i tried on windows, now it shows the qr code.

<img width="770" alt="Screenshot 2024-06-23 150032" src="https://github.com/nrwl/nx/assets/16211801/e4fea23b-54c2-4e48-97f7-67c016f06383">


i submitted pr https://github.com/nrwl/nx/pull/26493 to fix this.

could you try the latest version of nx or add
```
"targets": {
  "start": {
      "executor": "@nx/expo:start"
  }
}
```

**Comment by xiongemi** [comment]
i tried on windows, it shows the qr code now:

**Comment by xiongemi** [comment]
> @xiongemi Now Start command is working fine. @FrozenPandaz But still QR issue is not fixed. Expo TUI is not showing. Should show this <img alt="image" width="320" src="https://private-user-images.githubusercontent.com/84927543/339985923-f1adce8b-6df9-41ca-9b42-dff250600e81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NDM0NjgsIm5iZiI6MTcyMzg0MzE2OCwicGF0aCI6Ii84NDkyNzU0My8zMzk5ODU5MjMtZjFhZGNlOGItNmRmOS00MWNhLTliNDItZGZmMjUwNjAwZTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDIxMTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczOGY5N2E3NWU0ODc0ODMzNjA4YmFlNjljN2ZkZmM4NzY2M2I5NjczYmYzMWJhMGY0ZDQzMGM2MGJjZTI4NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tz51zB2mQVmviaBSpVMl4mBbz8ZYLsdyl7naEtN3Ync">
> 
> But getting this only <img alt="image" width="296" src="https://private-user-images.githubusercontent.com/84927543/339986071-cc564746-18c8-4605-bc17-4e24fd53bf29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NDM0NjgsIm5iZiI6MTcyMzg0MzE2OCwicGF0aCI6Ii84NDkyNzU0My8zMzk5ODYwNzEtY2M1NjQ3NDYtMThjOC00NjA1LWJjMTctNGUyNGZkNTNiZjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDIxMTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3ZDY2ZmFiMDk4YjA2N2JiYjcwZWE1ZDAyZjlmZWIxMDQ1MmVmYzQ0NGMzZmY5MzNlNDk3YTg3Mjc4MGNkNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J-g2hkFNZDgfSN1Lku3XfKCJ-th2xFRmtT1K-KLU75I">
> 
> Please let me know if you have a fix for this

set NX_NATIVE_COMMAND_RUNNER=false in your env file and run the command again to see if that would fix the issue?
