### ISSUE TITLE
nx migrate throws when called without args

### ISSUE THREAD

**Issue by snebjorn** [nrwl/nx#2653]
## Expected Behavior

Exceptions shouldn't propagate all the way out, but instead gracefully fail with a human readable error message.

**Example**

```shell
PS C:\Repos\nx-test> nx migrate
Provide the correct package name and version. E.g., @nrwl/workspace@9.0.0.

PS C:\Repos\nx-test>
```

## Current Behavior

Currently exceptions propagate all the way out, causing this scary looking error message. It looks like something horrible went wrong. But really it's just saying that it was called incorrectly, which is a common scenario.

```shell
PowerShell 7.0.0
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Repos\nx-test> nx migrate
Provide the correct package name and version. E.g., @nrwl/workspace@9.0.0.
C:\Repos\nx-test\node_modules\yargs\yargs.js:1109
      else throw err
           ^

Error: Command failed: .\node_modules\.bin\tao migrate 
    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at Object.exports.commandsObject.yargs.usage.command.command.command.command.command.command.command.command.command.command.command.command.command.command.command.alias.command.command.command [as handler] (C:\Repos\nx-test\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:76:21)
    at Object.runCommand (C:\Repos\nx-test\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\Repos\nx-test\node_modules\yargs\yargs.js:1022:30)
    at Object.get [as argv] (C:\Repos\nx-test\node_modules\yargs\yargs.js:965:21)
    at Object.initLocal (C:\Repos\nx-test\node_modules\@nrwl\cli\lib\init-local.js:20:79)
    at Object.<anonymous> (C:\Repos\nx-test\node_modules\@nrwl\cli\bin\nx.js:12:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10
```

### Steps to Reproduce

1. nx migrate
2. observe thrown exception

Run on this repo https://github.com/snebjorn/nx-test

### Context

```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 9.1.0
  @nrwl/cli : 9.1.0
  @nrwl/cypress : 9.1.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.1.0
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.1.0
  @nrwl/web : Not Found
  @nrwl/workspace : 9.1.0
  typescript : 3.7.5
```

**Comment by FrozenPandaz** [comment]
The reason you see this error is that `nx migrate` requires a version at the moment.

See the [examples on this page](https://nx.dev/react/nx-commands/migrate).

What would you expect as the default version if none is passed?

```
nx migrate // ===

nx migrate latest // ? This would be latest from npm
nx migrate@^currentVersion // ? This would be the highest version in the same major version
nx migrate@~currentVersion // ? This would be the highest version in the same minor version
```

**Comment by snebjorn** [comment]
The issue was just that the exception bubbled all the way out.

It should gracefully exit after printing the error message it gave.
> Provide the correct package name and version. E.g., @nrwl/workspace@9.0.0.

**Comment by snebjorn** [comment]
I updated the issue to be more clear.
It really just boils down to "Exceptions shouldn't propagate all the way out,"

If "more info needed" then please let me know what is unclear.

I believe the solution is to put a `try-catch` around the argument parser.

**Comment by zayenz** [comment]
This issue tripped me up today, I thought that my nx install was broken as it showed a stack-trace from a simple command invocation. I agree with the suggestion by @snebjorn.
