### ISSUE TITLE
`@nx/esbuild` produces invalid sourcemaps if `\n` is used inside of string template

### ISSUE THREAD

**Issue by Akxe** [nrwl/nx#26548]
### Current Behavior

```javascript
function progressCallback(progress) {
	res.write(JSON.stringify(progress) + `\n\n`);
}

progressCallback('test');
```

When build this code produces:

```javascript
let progressCallback2 = function(progress) {
  res.write(`${JSON.stringify(progress)}

`);
```

The main difference is that the resulting code uses actual newlines and not `\n`.

The problem is that the sourcemap created does think that there are no newlines and, therefor, everything bellow that line is broken.

### Expected Behavior

From what I can tell, the problem does not occur in ESBuild playground. I therefore reported the error here, as I do not know what process is used to generate the sourcemaps.

### GitHub Repo

https://esbuild.github.io/try/#dAAwLjE5LjIALS1zb3VyY2VtYXAAZnVuY3Rpb24gcHJvZ3Jlc3NDYWxsYmFjayhwcm9ncmVzcykgewoJcmVzLndyaXRlKEpTT04uc3RyaW5naWZ5KHByb2dyZXNzKSArIGBcblxuYCk7Cn0KCnByb2dyZXNzQ2FsbGJhY2soJ3Rlc3QnKQ

### Steps to Reproduce

1. Use `executor` `"@nx/esbuild:esbuild"`
2. Use code provided in ESBuild demo
3. Replace 

### Nx Report

```shell
Node   : 20.14.0
OS     : win32-x64
npm    : 10.7.0

nx (global)        : 19.2.2
nx                 : 19.1.0
@nx/js             : 19.1.0
@nx/jest           : 19.1.0
@nx/linter         : 19.1.0
@nx/eslint         : 19.1.0
@nx/workspace      : 19.1.0
@nx/angular        : 19.1.0
@nx/devkit         : 19.1.0
@nx/esbuild        : 19.1.0
@nx/eslint-plugin  : 19.1.0
@nx/node           : 19.1.0
@nrwl/tao          : 19.1.0
@nx/web            : 19.1.0
@nx/webpack        : 19.1.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
---------------------------------------
Community plugins:
@rx-angular/template : 18.0.0
```

### Failure Logs

```shell
./dist/apps/server/main.js
  Your source map refers to generated column 1 on line 6846, but the source only contains 0 column(s) on that line.
  Check that you are using the correct source map.
```

### Package Manager Version

npm: 10.7.0

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

I was able to fix the sourcemap by replacing the template string with this: `res.write(JSON.stringify(progress) + '\n\n')`

**Comment by Coly010** [comment]
Hey @Akxe !

Could you try this again with the latest version of Nx?

**Comment by Coly010** [comment]
Unfortunately, this is not an Nx issue. It's intended behaviour by `esbuild`: 
https://github.com/evanw/esbuild/issues/545
https://github.com/evanw/esbuild/issues/307#issuecomment-667486093
