### ISSUE TITLE
`Updated <lib> to null` when the changelog is generated with `nx release`

### ISSUE THREAD

**Issue by gispada** [nrwl/nx#26564]
### Current Behavior

In an independent projects setup with conventional-commits versioning, when
- `mylib2` consumes `mylib`
- changes only affect `mylib2`
- `nx release` is run

then in the changelog of `mylib2` the following lines appear:

```
+ ### 🧱 Updated Dependencies
+
+ - Updated mylib to null
```

### Expected Behavior

If `mylib` version is not updated it should not appear in the changelog of `mylib2`, even if the latter is dependent on the former.

### GitHub Repo

https://github.com/gispada/nx-changelog-issue-repro

### Steps to Reproduce

The repro is already configured with the appropriate git history to trigger the issue. There are 1 `feat` and 1 `fix` commit for `mylib2` since the last tag.

1. Clone the repo and install dependencies
2. Be sure to also fetch tags
3. Run `npx nx release --dry-run`

### Nx Report

```shell
Node   : 20.10.0
OS     : darwin-x64
npm    : 10.2.3

nx                 : 19.3.0
@nx/js             : 19.3.0
@nx/jest           : 19.3.0
@nx/linter         : 19.3.0
@nx/eslint         : 19.3.0
@nx/workspace      : 19.3.0
@nx/devkit         : 19.3.0
@nx/eslint-plugin  : 19.3.0
@nx/react          : 19.3.0
@nx/rollup         : 19.3.0
@nrwl/tao          : 19.3.0
@nx/web            : 19.3.0
@nx/webpack        : 19.3.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/rollup/plugin
@nx/eslint/plugin
@nx/jest/plugin
@nx/webpack/plugin
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JamesHenry** [comment]
Sorry about this @gispada, this is addressed by #26671
