### ISSUE TITLE
#21428 removed `devDependencies` from package.json

### ISSUE THREAD

**Issue by TriPSs** [nrwl/nx#26577]
Why? Why is this not made optional (or at-least make this behavior opt in?), as a lib maintainer we add dev dependencies so that 
1. the package is available when we are developing 
2. we can import the package.json and copy it over if needed to the devDependencies of the users project
3. we can use a tool like ncu to easy update set packages that are added to the users project
4. we are then not forcing certain versions to our end users

Can we make this behavior opt-in or opt-out?

**Comment by TriPSs** [comment]
#21428, made this ticket with the reference in issue function, sorry that it's not following the format.

**Comment by FrozenPandaz** [comment]
What are you running where you are seeing the issue? Can you provide a reproduction please to help us reproduce the issue?

**Comment by TriPSs** [comment]
[Here is the commit](https://github.com/TriPSs/nx-extend/pull/286/commits/7e4a5d406e30679855859573324d8408edea2176) that changes the implementation we had. These packages where build and released with `devDependencies` so when running the `<package>:init` we could read it from there.

We can keep dependencies inside the package.json up to date with tools like [ncu](https://www.npmjs.com/package/npm-check-updates), now it will become a manual stap, which will be forgotten.

**Comment by TriPSs** [comment]
I did add more info?

**Comment by TriPSs** [comment]
Again, I did add more info.

**Comment by TriPSs** [comment]
Once again, I did add more info @FrozenPandaz

**Comment by TriPSs** [comment]
@jaysoo @FrozenPandaz

**Comment by TriPSs** [comment]
:/

**Comment by TriPSs** [comment]
:/

**Comment by TriPSs** [comment]
Bump again

**Comment by TriPSs** [comment]
Bump again

**Comment by TriPSs** [comment]
Once again, not stale @FrozenPandaz
