### ISSUE TITLE
unable to generate @nrwl/nest:lib

### ISSUE THREAD

**Issue by killbox-code** [nrwl/nx#2657]
- [X] I am running the latest version
- [X] I checked the documentation (nx.dev) and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Expecting the command `ng g @nrwl/nest:lib --directory=sensei --tags=server,lib --controller --service api` to generate a NestJS library named `api` in the `libs/sensei` directory

## Current Behavior

The command `ng g @nrwl/nest:lib --directory=sensei --tags=server,lib --controller --service api` does not do anything. It doesn't return the prompt either so it surely tries to do something but no output or project changes are observed and the prompt will not be returned until CTRL+C is used.

### Steps to Reproduce

1. in a NX (v 7.8.7) repo, issue the command to add a NestJS lib

### Context

NX Report Output:

```
  @nrwl/angular : 9.1.1
  @nrwl/cli : 9.1.1
  @nrwl/cypress : 9.1.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : 9.1.1
  @nrwl/jest : 9.1.1
  @nrwl/linter : 9.1.1
  @nrwl/nest : 9.1.1
  @nrwl/next : Not Found
  @nrwl/node : 9.1.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.1.1
  @nrwl/web : 9.1.1
  @nrwl/workspace : 9.1.1
  typescript : 3.7.5
```

**Comment by FrozenPandaz** [comment]
For me, it did take quite a while (26 seconds) but it does complete successfully.

Can you please provide a repo so that we can clone it to debug the issue?

**Comment by killbox-code** [comment]
@FrozenPandaz - you're right. Approx. the same completion time for me, I was not being patient enough. Thanks, Sir - hope all is well.
