### ISSUE TITLE
Vite Config TypeError on `defineConfig` regarding `cacheDir` with test config

### ISSUE THREAD

**Issue by barrymichaeldoyle** [nrwl/nx#26579]
### Current Behavior

I get a type error if I specific a `cacheDir` in my test config:

```
export default defineConfig({
  test: {
    cacheDir: '../../../node_modules/.vitest/libs/shared/utils',
    ...
  },
  ...
})
```

> Object literal may only specify known properties, and 'cacheDir' does not exist in type 'InlineConfig'.

What does work is this:

```
export default defineConfig({
  test: {
    cache: { dir: '../../../node_modules/.vitest/libs/shared/utils' },
    ...
  },
  ...
})
```

But when I do that and run the tests I get the following deprecation warning:

>  Vitest  "cache.dir" is deprecated, use Vite's "cacheDir" instead if you want to change the cache director. Note caches will be written to "cacheDir/vitest"

### Expected Behavior

Should not get type errors when using `test.cacheDir`. It's worth noting that everything works fine if I `@ts-ignore`. The tests run successfully and I do not get the deprecation warning mentioned above.

### Steps to Reproduce

1. Set a `test.cacheDir` key in the `defineConfgi` in a `vite.config.ts` file.
2. Get sad because you see type error.
3. Get around it with an ugly `@ts-ignore` or `@ts-expect-error`.

### Nx Report

```shell
Node   : 20.12.0
OS     : linux-arm64
bun    : 1.1.12

nx                 : 19.3.0
@nx/js             : 19.3.0
@nx/jest           : 19.3.0
@nx/linter         : 19.3.0
@nx/eslint         : 19.3.0
@nx/workspace      : 19.3.0
@nx/cypress        : 19.3.0
@nx/devkit         : 19.3.0
@nx/eslint-plugin  : 19.3.0
@nx/playwright     : 19.3.0
@nx/react          : 19.3.0
@nx/storybook      : 19.3.0
@nrwl/tao          : 19.3.0
@nx/vite           : 19.3.0
@nx/web            : 19.3.0
@nx/webpack        : 19.3.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/vite/plugin
```

### Failure Logs

```shell
No overload matches this call.
  The last overload gave the following error.
    Object literal may only specify known properties, and 'cacheDir' does not exist in type 'InlineConfig'.ts(2769)
index.d.ts(3181, 18): The last overload is declared here.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Hey :) I think you've misunderstood where the `cacheDir` property is supposed to go. 

`cacheDir` _does not_ exist in the `test` object. You need to use the `cacheDir` at vite's object level.

```ts
defineConfig({
   cacheDir: "", // <---- Use it here!!
   test: {
       cacheDir: "" // <----- Not here!!
   }
})
```

**Comment by Lonli-Lokli** [comment]
@Coly010 Ntw Nx now adds this cache dir to test too, as part of object, see https://github.com/Lonli-Lokli/issues-nrwl-nx-23303/blob/master/apps/nx-vitest/vite.config.ts#L37 (that's Nx sample for another issue https://github.com/nrwl/nx/issues/23303)

This property is deprecated, see https://github.com/vitest-dev/vitest/pull/5229

**Comment by Coly010** [comment]
Yep, we can do some cleanup.
