### ISSUE TITLE
NX release is not correctly bumping dependant projects when using conventional commits

### ISSUE THREAD

**Issue by Warrper** [nrwl/nx#26592]
### Current Behavior

I have a monorepo with a project graph that has a similar structure to this:
![image](https://github.com/nrwl/nx/assets/17754468/0e72bc01-d66c-45ee-9638-690f7e3d7702)

When using nx release if I create a commit that changes @wp-test/test-package-a, currently we get the following console output:

```bash
 NX   Running release version for project: @wp-test/test-package-c

@wp-test/test-package-c 🔍 Reading data for package "@wp-test/test-package-c" from packages/folder-b/folder-c/package-c/package.json
@wp-test/test-package-c 📄 Resolved the current version as 1.1.0 from git tag "@wp-test/test-package-c@1.1.0".
@wp-test/test-package-c 🚫 No changes were detected using git history and the conventional commits standard.
@wp-test/test-package-c 🚫 Skipping versioning "@wp-test/test-package-c" as no changes were detected.

 NX   Running release version for project: @wp-test/test-package-d

@wp-test/test-package-d 🔍 Reading data for package "@wp-test/test-package-d" from packages/folder-b/folder-c/package-d/package.json
@wp-test/test-package-d 📄 Resolved the current version as 1.1.0 from git tag "@wp-test/test-package-d@1.1.0".
@wp-test/test-package-d 🚫 No changes were detected using git history and the conventional commits standard.
@wp-test/test-package-d 🚫 Skipping versioning "@wp-test/test-package-d" as no changes were detected.

 NX   Running release version for project: @wp-test/test-package-a

@wp-test/test-package-a 🔍 Reading data for package "@wp-test/test-package-a" from packages/folder-a/package-a/package.json
@wp-test/test-package-a 📄 Resolved the current version as 1.1.0 from git tag "@wp-test/test-package-a@1.1.0".
@wp-test/test-package-a 📄 Resolved the specifier as "patch" using git history and the conventional commits standard.
@wp-test/test-package-a ✍️  New version 1.1.1 written to packages/folder-a/package-a/package.json

 NX   Running release version for project: @wp-test/test-package-b

@wp-test/test-package-b 🔍 Reading data for package "@wp-test/test-package-b" from packages/folder-b/package-b/package.json
@wp-test/test-package-b 📄 Resolved the current version as 1.1.0 from git tag "@wp-test/test-package-b@1.1.0".
@wp-test/test-package-b 🚫 No changes were detected using git history and the conventional commits standard.
@wp-test/test-package-b 🚫 Skipping versioning "@wp-test/test-package-b" as no changes were detected.
```

In this scenario the only package that gets updated is package-a, despite the fact that I have version.generatorOptions.updateDependents = 'auto'

### Expected Behavior

I would expect that all packages that depend on package-a would also get updated as part of this release.

### Steps to Reproduce

1. Create a monorepo with a dependency structure matching this graph:
![image](https://github.com/nrwl/nx/assets/17754468/0e72bc01-d66c-45ee-9638-690f7e3d7702)
2. use nx release with the following release config:
```json
{
    "projects": [
      "packages/**/*"
    ],
    "projectsRelationship": "independent",
    "changelog": {
      "automaticFromRef": true,
      "projectChangelogs": {
        "file": false,
        "createRelease": "github"
      }
    },
    "version": {
      "conventionalCommits": true,
      "generatorOptions": {
        "updateDependents": "auto",
        "fallbackCurrentVersionResolver": "disk"
      }
    }
  }
```

3. create a nx-release.ts with code that looks like this:
```ts
    const versionOutput = await releaseVersion({
      dryRun: false,
      verbose: true,
      gitCommit: false,
      gitTag: true,
    });

    const releaseOutput = await releasePublish({
      dryRun: false,
      verbose: true,
      outputStyle: 'stream',
    });

    console.log('versionOutput', JSON.stringify(versionOutput, null, 4));
    console.log('releaseOutput', releaseOutput);
```

The important part here is that gitCommit is false.

4. Run your initial release and see that everything bumps fine.
5. Run another release with only a change to package-a and observe that only package a updates rather than package a and its dependencies

### Nx Report

```shell
Node   : 20.11.0
OS     : darwin-arm64
yarn   : 1.22.21

nx             : 18.3.5
@nx/js         : 18.3.5
@nx/workspace  : 18.3.5
@nx/devkit     : 18.3.5
@nrwl/tao      : 18.3.5
typescript     : 5.3.3
```

### Package Manager Version

yarn 1.22.21

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

After digging around the code I belive the issue lies here:
https://github.com/nrwl/nx/blob/95a6e6864de76cfa6396b2fc2d2b8911e237864f/packages/js/src/generators/release-version/release-version.ts#L377

Because we are passing gitCommit false to version (we manage versions entierly using tags) when it looks through your commits for 'relevent' commits https://github.com/nrwl/nx/blob/95a6e6864de76cfa6396b2fc2d2b8911e237864f/packages/nx/src/command-line/release/utils/shared.ts#L309 it will only return commits for package-a (as that's the only package that actually has a commited change).

version.generatorOptions.updateDependents = 'auto' that it would also update package-a's dependent packages rather than just the package itself.

The commit to package-a is 'relevent' to b,c and d because they depend on package-a

**Comment by rcolwell-cb** [comment]
Seems like same behavior as this. @JamesHenry @FrozenPandaz 
https://github.com/nrwl/nx/issues/26041

**Comment by JamesHenry** [comment]
This was answered on #26041, in this case it is down to the old version of Nx being used
