### ISSUE TITLE
lint task not being inferred by Nx 19.3

### ISSUE THREAD

**Issue by mschneider-lise** [nrwl/nx#26598]
### Current Behavior

Running `npx nx lint {project}` is failing with "Cannot find configuration for task {project}:lint".

I created two new Nx workspaces containing a react app using `create-nx-workspace` to compare Nx versions 19.3 and 19.2.3. It seems like Nx is not inferring the lint task when using 19.3.

Here are lists of the inferred targets taken from the IntelliJ plugin:

Nx 19.3
![image](https://github.com/nrwl/nx/assets/98520062/efe32102-25df-4f9d-9097-2b94f00ebb4f)

Nx 19.2.3
![image](https://github.com/nrwl/nx/assets/98520062/130261cf-c04c-4a31-bfaa-84008f570f23)

### Expected Behavior

Running `npx nx lint {project}` should correctly run lint for the project.

### Steps to Reproduce

1. Create a new Nx (react) project using `npx create-nx-workspace@19.3`
2. Run `npx nx lint {project}`

### Nx Report

```shell
Node   : 20.10.0
OS     : win32-x64
npm    : 8.8.0

nx                 : 19.3.0
@nx/js             : 19.3.0
@nx/jest           : 19.3.0
@nx/linter         : 19.3.0
@nx/eslint         : 19.3.0
@nx/workspace      : 19.3.0
@nx/devkit         : 19.3.0
@nx/eslint-plugin  : 19.3.0
@nx/react          : 19.3.0
@nrwl/tao          : 19.3.0
@nx/vite           : 19.3.0
@nx/web            : 19.3.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

It's working in our build server (linux), so maybe this problem is limitted to windows.

**Comment by atsjo** [comment]
same for me... it worked after upgrading to 19.3, but disappeared after doing a nx reset... also using windows....

**Comment by cmcnicholas** [comment]
Experiencing the same issue, local nx cache had a mixture of lint tasks available for my projects (but there should be one available for each project). Deleted the nx cache and forced it to refresh workspace and the lint commands are gone from all projects now (at least consistent). This happened after upgrading to latest NX.

**Comment by ardabeyazoglu** [comment]
Same happened to me today. After struggling with multiple methods, only adding lint target to apps/libs individually made it work. However, this should not be necessary like it was before 19.3

**Comment by atsjo** [comment]
still same with 19.4...

**Comment by atsjo** [comment]
seems fixed via https://github.com/nrwl/nx/pull/26638

**Comment by Ccry11** [comment]
If the problem persists after the update, try to run `nx reset`
