### ISSUE TITLE
let nrwl schematics extend from angular schematics

### ISSUE THREAD

**Issue by wvanderdeijl** [nrwl/nx#266]
just wanted to let you know that angular devkit merged a PR to allow a schematics collection to extend from another collection: https://github.com/angular/devkit/pull/398

Might be useful to use this nrwl/nx to prevent duplication from all the angular schematics you're not really touching

would be wonderful for us if nrwl/nx extends from angular schematics, so we can make our own collection that extends from nrwl/nx to make some minor tweaks and add some of our own generators

**Comment by Nxt3** [comment]
Doesn't nrwl already do this?

https://github.com/nrwl/nx/blob/master/packages/schematics/src/collection.json

They are extending multiple things from Angular's collections.

**Comment by wvanderdeijl** [comment]
The current NX code lists all angular cli generators and for each generator specifies it extends from the one from angular. This requires NX to list all angular generators and will break if angular adds a new generator as that new one won't be in the NX collection.
With the new devkit PR you can set the `extends` property at the schematics collection level so there is no need to list all the individual angular generators anymore. The NX schematics collection would than extends from the default angular collection and automatically pick up on new generators added to the default angular collection

**Comment by vsavkin** [comment]
Fixed here https://github.com/nrwl/nx/pull/307
