### ISSUE TITLE
npx create-nx-workspace@latest (v19.3.0) fails for a vue monorepo

### ISSUE THREAD

**Issue by ghost23** [nrwl/nx#26605]
### Current Behavior

I am on a Windows 11 machine, running powershell.
I type `npx create-nx-workspace@latest --verbose` and answer the questions like this:
```
√ Where would you like to create your workspace? · demo
√ Which stack do you want to use? · vue
√ What framework would you like to use? · none
√ Integrated monorepo, or standalone project? · integrated
√ Application name · Sandbox
√ Test runner to use for end to end (E2E) tests · playwright
√ Default stylesheet format · scss
√ Do you want Nx Cloud to make your CI fast? · skip
```

Then it successfully installs the npm dependencies but fails at creating my workspace:

```
✔ Installing dependencies with npm
✖ Creating your workspace in nebf6-ui-monorepo

 NX   Failed to create a workspace.

Exit code: 1
Log file: C:\Users\<myuser>\AppData\Local\Temp\tmp-26616-xNwdu6g17RlE\error.log
```

In  the log file it says:

```
added 404 packages, and audited 405 packages in 31s

45 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

 NX  Generating @nx/workspace:preset

Fetching prettier...

 NX   Cannot find configuration for 'Sandbox'

Pass --verbose to see the stacktrace.


 NX   Workspace creation failed, see above.


Error: Workspace creation failed, see above.
    at ChildProcess.<anonymous> (C:\Users\<myuser>\AppData\Local\Temp\tmp-26616-xNwdu6g17RlE\node_modules\@nx\workspace\src\generators\new\generate-preset.js:38:24)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

### Expected Behavior

My Vue Workspace should be correctly generated

### Steps to Reproduce

See description above

### Nx Report

```shell
I do this in the unfinished project folder:

npx nx report

 NX   Report complete - copy this into the issue template

Node   : 20.14.0
OS     : win32-x64
npm    : 10.7.0

nx              : 19.3.0
@nx/js          : 19.3.0
@nx/linter      : 19.3.0
@nx/eslint      : 19.3.0
@nx/workspace   : 19.3.0
@nx/devkit      : 19.3.0
@nx/playwright  : 19.3.0
@nrwl/tao       : 19.3.0
@nx/vite        : 19.3.0
@nx/vue         : 19.3.0
@nx/web         : 19.3.0
typescript      : 5.4.5
```

### Failure Logs

```shell
see in the description
```

### Package Manager Version

npm v10.7.0

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by ghost23** [comment]
Additonal info: I switched to node v21.7.3 and npm 10.5.0, same result.
Also node v22.3.0 and npm 10.8.1 fails in the same manner.

**Comment by ghost23** [comment]
Ahh, now I tried using the same name for workspace and application name and then it works. But that is awkward?! Why ask for these two names in the first place if they have to be same anyway?

**Comment by Coly010** [comment]
Hey @ghost23 !

No there was an issue here.

The first name that the prompt asks for is the workspace name, useful for when you have multiple projects in the workspace. The second is the application name in particular that is set up immediately.

There was an issue with the second step here which didn't parse PascalCased names correctly.

**Comment by ghost23** [comment]
Ah, I see. Thank you for the explanation
