### ISSUE TITLE
Next.js + Project Crystal fails to execute the dependencies of a target in the right order under certain circumstances

### ISSUE THREAD

**Issue by julianobrasil** [nrwl/nx#26613]
### Current Behavior

In a Next.js application, inside the `next.config.js` file we have a function to load the content of a certain file, let's call it `dyn-var.js`:

```js
const importVars = async () => {
  // @ts-ignore
  return require('./dyn-var.js');
};

module.exports = async (/** @type {string} */ phase) => {
  const { a } = await importVars();
  console.log({ a });
  return composePlugins(...plugins)(nextConfig)(phase);
};
```

 That file is created during the build time, in a target that is a dependency of the `build` target:

```json
  "targets": {
    "build": {
      "dependsOn": ["random-dependency"]
    },
    "random-dependency": {
      "executor": "nx:run-commands",
      "options": {
        "cwd": "apps/next-app",
        "command": "echo 'export const myVar = 2;' > dyn-var.js"
      }
    }
  }
```

 The issue is that `nx` fails to build the Next.js project because that file is missing.

Interestingly, the same setup works if, instead of leaving the executor to be selected by the Nx's  inference system, I force the usage of the `@nx/next:build` executor. 

### Expected Behavior

I'd expect to be able to add files dynamically to the Next.js project, during the build time. Those files would be added by a dependency Nx target before the Next.js app build starts, as it works if I force the usage of the `@nx/next:build` executor.

### GitHub Repo

https://github.com/julianobrasil-experimental/nx-next-issue

### Steps to Reproduce

1. `yarn` to install the dependencies
2. `yarn nx run app-next:build --verbose`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.10.0
OS     : darwin-arm64
yarn   : 1.22.19

nx                 : 19.3.0
@nx/js             : 19.3.0
@nx/jest           : 19.3.0
@nx/linter         : 19.3.0
@nx/eslint         : 19.3.0
@nx/workspace      : 19.3.0
@nx/devkit         : 19.3.0
@nx/eslint-plugin  : 19.3.0
@nx/next           : 19.3.0
@nx/react          : 19.3.0
@nrwl/tao          : 19.3.0
@nx/web            : 19.3.0
@nx/webpack        : 19.3.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/next/plugin
@nx/jest/plugin
@nx/eslint/plugin
```

### Failure Logs

```shell
NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  AggregateCreateNodesError: An error occurred while processing files for the @nx/next/plugin plugin.
    - apps/next-app/next.config.js: Cannot find module './dyn-var.js'
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Hey,

Thanks for reporting this issue. 
The reason this is happening is that during the graph creation for inferred targets, the _vars_ you are referencing is not available so it fails. 
Internally, Nx also needs to consider this the usual solution is to check `global.NX_GRAPH_CREATION` and skip anything that would be unavailable (like async values/dependencies etc...) 

This is expected. However, in your case you have a few solutions:

1. Wrap using a `try-catch`, something like:
```
module.exports = async (/** @type {string} */ phase) => {
  try {
    const { a } = await importVars();
    console.log({ a });
  } catch(e) {
    console.error(e);
  }
  return composePlugins(...plugins)(nextConfig)(phase);
};
```

2. Skip using `NX_GRAPH_CREATION`
```js
  if(!global.NX_GRAPH_CREATION) {
  const { a } = await importVars();
  console.log({ a});
  } 
  ```
3. Run the dependency task outside of Nx
- Like using a npm script to run before running nx command

### Note
I saw that you are using **export** inside a `.js` shouldn't it be `module.exports`

**Comment by julianobrasil** [comment]
Thanks for the quick help, @ndcunningham. I was doing something similar, but instead of `global.NX_GRAPH_CREATION`, I was checking `process.env.NEXT_DEPLOYMENT_ID` (build) and `process.env.__NEXT_PROCESSED_ENV` (serve), which I wasn't comfortable with.

Yeah, I wrote a random thing inside that file (it would run anyway because of the previous failure 😄)
