### ISSUE TITLE
Overriding executor in nx.json works differently from overriding other fields

### ISSUE THREAD

**Issue by longngng** [nrwl/nx#26611]
### Current Behavior

Overriding executor for a target inferred from plugin works differently from overriding other fields

### Expected Behavior

Overriding executor for a target inferred from plugin works the same way as overriding other fields

### GitHub Repo

https://github.com/longngng/nx-plugin-override-example

### Steps to Reproduce

1. Clone the repo
2. Run nx show project nx-plugin-override-example-code --json. Take note of the configs for "build" target
3. In nx.json, add the following config for build target
```
  "targetDefaults": {
    "build": {
      "executor": "nx:noop"
    }
  },
```
4. Run nx show project nx-plugin-override-example-code --json. Take note of the configs for "build" target
5. Replace the config for build in nx.json with
```
  "targetDefaults": {
    "build": {
      "cache": false
    }
  },
```
6. Run nx show project nx-plugin-override-example-code --json. Take note of the configs for "build" target
7. Replace the config for build in nx.json with
```
  "targetDefaults": {
    "build": {
      "inputs": ["input1234"]
    }
  },
```
6. Run nx show project nx-plugin-override-example-code --json. Take note of the configs for "build" target

You can repeat this for different fields. Observe that in the first scenario, the config for build is not overridden. Meanwhile in other cases, the configs are merged or overridden.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.9.0
OS     : linux-x64
npm    : 10.1.0

nx                 : 19.3.0
@nx/js             : 19.3.0
@nx/linter         : 19.3.0
@nx/eslint         : 19.3.0
@nx/workspace      : 19.3.0
@nx/devkit         : 19.3.0
@nx/eslint-plugin  : 19.3.0
@nx/react          : 19.3.0
@nrwl/tao          : 19.3.0
@nx/vite           : 19.3.0
@nx/web            : 19.3.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
This is expected, changing the executor via target defaults away from what is already defined isn't supported. Target defaults are only merged if the target and defaults are considered compatible. If two targets have different executors, they are not compatible.
