### ISSUE TITLE
`nx release publish`: 402 Payment Required error with scoped packages

### ISSUE THREAD

**Issue by Badisi** [nrwl/nx#26632]
### Current Behavior

When trying to publish a scoped npm package for the first time, this results in the following error:

```sh
$ nx release publish --first-release
```
```sh
> nx run @hug/ngx-overlay:nx-release-publish

Skipped npm view because --first-release was set
npm publish error:
402 Payment Required - PUT https://registry.npmjs.org/@hug%2fngx-overlay - You must sign up for private packages
npm publish stdout:
{
  "error": {
    "code": "E402",
    "summary": "402 Payment Required - PUT https://registry.npmjs.org/@hug%2fngx-overlay - You must sign up for private packages",
    "detail": ""
  }
}
```

The issue is that scoped npm packages can also be public and needs to be published with public access:
```sh
npm publish --access public
```

### Expected Behavior

Scoped npm packages should be published without issues

### Steps to Reproduce

Run `nx release publish --first-release` with a scoped npm package.

### Nx Report

```shell
Node   : 18.18.2
OS     : darwin-x64
npm    : 10.8.0

nx (global)    : 19.0.4
nx             : 19.2.0
@nx/js         : 19.2.0
@nx/workspace  : 19.2.0
@nx/devkit     : 19.2.0
@nrwl/tao      : 19.2.0
typescript     : 4.7.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JamesHenry** [comment]
Hi @Badisi, you just need to set:

```json
  "publishConfig": {
     "access": "public"
   }
```

In your relevant package.json

**Comment by Badisi** [comment]
I should have thought of that one 🤦‍♂️

That, indeed, did the trick. Thanks!
