### ISSUE TITLE
NX built in environment variables are not available to process in nx19

### ISSUE THREAD

**Issue by pmosconi** [nrwl/nx#26658]
### Current Behavior

Variables such as NX_TASK_TARGET_PROJECT are not made available to running process even if docs still say so: https://nx.dev/reference/environment-variables

### Expected Behavior

The variables stated in the docs should be made available even if they don't start with NX_PUBLIC_

### Steps to Reproduce

console.log(process.env);

### Nx Report

```shell
Node   : 20.9.0
OS     : linux-x64
yarn   : 1.22.22

nx                 : 19.3.1
@nx/js             : 19.3.1
@nx/jest           : 19.3.1
@nx/linter         : 19.3.1
@nx/eslint         : 19.3.1
@nx/workspace      : 19.3.1
@nx/cypress        : 19.3.1
@nx/devkit         : 19.3.1
@nx/eslint-plugin  : 19.3.1
@nx/express        : 19.3.1
@nx/nest           : 19.3.1
@nx/node           : 19.3.1
@nx/react          : 19.3.1
@nrwl/tao          : 19.3.1
@nx/web            : 19.3.1
@nx/webpack        : 19.3.1
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/webpack/plugin
```

### Failure Logs

```shell
N/A
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by MaxKless** [comment]
Can you be more specific as to what process you want to use these variables in? Is it an nx plugin? Is it the nx process itself? Is it a third-party tool being spawned by nx? 
It's very possible that we're not correctly passing env variables down to some tool but we need more info from you to track it down.

**Comment by pmosconi** [comment]
Hi @MaxKless ,
thanks for your enquiry.
I've been using the NX_TASK_TARGET_PROJECT var in frontend apps to choose among different configuration sets, such as the API urls.

For example, we have a monorepo containing 4 frontend react apps and 2 api nest apps. 
3 frontends consume the first API, while the fourth uses the second one.

The following code snippet does all the magic:

```
import axios from 'axios';

const API_SERVERS = {
  'admin-portal': 'NX_PUBLIC_ADMIN_API_URL',
  portal: 'NX_PUBLIC_API_URL',
};
const env = process.env;
const apiServer = API_SERVERS[env?.NX_TASK_TARGET_PROJECT];
const baseURL = env[apiServer] || env?.NX_PUBLIC_API_URL;

export const axiosInstance = axios.create({ baseURL });
// ...

```
The application called admin-portal consumes NX_PUBLIC_ADMIN_API_URL
The other applications (one being called portal) consume NX_PUBLIC_API_URL

In .env file there are no moving parts and it can be used to start any or all of them at the same time without changes.
It is also good for build and deploy.

Hope this clarifies the point.

**Comment by MaxKless** [comment]
Is this a problem in the built app or when serving it locally? Which executor are you using to build/serve the app?

**Comment by pmosconi** [comment]
The executor is webpack.
Issue exists both locally and in production: for the latter, I searched NX_ in deployed minimized files and just found the NX_PUBLIC variables that are defined in .env.

Minimal reproduction can be cloned from https://github.com/pmosconi/nx-env-test

**Comment by MaxKless** [comment]
Since Nx 19, we only bundle environment variables that start with `NX_PUBLIC` for security reasons. Read more in the blog post here https://nx.dev/blog/nx-19-release#breaking-change-updating-bundled-environment-variables-to

The `NX_` environment variables are set for the _running_ process, like a serve executor that is spawned by nx. 

You can still include the environment variables in your build, because at _build_ time, webpack has access to the Nx environment variables. So you can write a webpack config that uses those env vars and modifies the build with them.

**Comment by pmosconi** [comment]
I had read the breaking change notice and found it quite confusing, especially because the built in variables there were available before now are no more: IMO you should at least explain this better.

You also mention that is possible to pass the variable in webpack config: where can I find an example?

Thanks

**Comment by MaxKless** [comment]
What did you find confusing exactly? It mentioned that we offer no migration for this, no?
The security reason is exactly that `NX_` variables might contain sensitive data like access tokens or internal things like apis or project structure. So those need to be excluded from a bundle. 

Check out https://webpack.js.org/plugins/environment-plugin/ to include environment vars in your webpack build.

**Comment by MaxKless** [comment]
i think you're misunderstanding it a little bit. They are available to the running process. But they're not automatically bundled.

**Comment by pmosconi** [comment]
Yes, I got it now. Maybe it could be made clearer for others too.
