### ISSUE TITLE
What is the correct way to use angular esbuild

### ISSUE THREAD

**Issue by muhamedkarajic** [nrwl/nx#26669]
### Current Behavior

Before I had the old nx setup without esbuild. The repo is around 170 libraries, some of them are internal, we have all kinds of other libraries.

Old setup:
```json
"build": {
  "executor": "@angular-devkit/build-angular:browser",
"serve": {
  "executor": "@nx/angular:dev-server",
```
Total build:
Without .nx and .angular: 178,564ms or 2.9min
With .nx and .angular: 65,487ms or 1.09min

Inside core library
Adding console log in constructor of core library 20sec
Removing the previous change in constructor 17sec

Inside higher order library:
Adding variable 12sec
Removing change of added variable 7sec
Added console.log: 12sec
Removed console log: 6.5sec

I'm totally confused which approach is the right one. I see the default nx setup is the following:
```json
"build": {
  "executor": "@angular-devkit/build-angular:application",
"serve": {
  "executor": "@angular-devkit/build-angular:dev-server",
```
Total build:
Without .nx and .angular: 28,000ms or 0,47min
With .nx and .angular: 29,000ms or 0,5min (basically no difference)

Inside core library
Adding console log in constructor of core library 20sec
Removing the previous change in constructor 12sec

Inside higher order library:
Adding console log inside higher order library 9sec
After a few edits it takes around 3seconds for futher edits
Added public variable: 4sec
Removing public variable: 3 sec

Following the nx documentation in order to use the esbuild I have to make it
```json
"build": {
  "executor": "@nx/angular:browser-esbuild",
"serve": {
  "executor": "@nx/angular:dev-server",
```

Total build:
Without .nx and .angular: 29,000ms or 0,50min
With .nx and .angular: 37,000ms or 0,65min (might havebeen a fluke)

Inside core library
Adding console log in constructor of core library 26sec
Removing the previous change in constructor 16sec
Adding one more console log: 3sec
Adding public variable: 18sec

Inside higher order library:
Adding console log inside higher order library 12sec
After a few edits it takes around 3seconds for futher edits
Adding public variable: 6sec
 

### Expected Behavior

I would expect the best possible setup to be by default, however I'm not sure if thats the case. 
Also I'm totally confused whats the difference of those last two cause they are almost identical in performance.

Another thing is the second option requires me for our internal libraries to use .js everywhere. Why is that?

### Steps to Reproduce

Everything explained above.

### Nx Report

```shell
No need for any repo.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Similar numbers are also on Windows.

**Comment by muhamedkarajic** [comment]
> Are you trying to find out the correct setup to use for your angular applications?
Under the Nx repo, yes.

> Are you trying to find out how to switch from webpack-based builds to esbuild-based builds?
I think we have to convert out internal libraries differently to support the esbuild but I don't know what we have to do. Can you help me with that as well? Cause right now to make it compile I have to add `.js` and `/index.js` to each import.

Are you trying to get a resolution to errors you are seeing regarding your libraries?
I do not undersatnd the question. Sorry.

Are you trying to suggest that there is a performance differential between Nx's builders and Angular's builders?
Not really, I was just confused whats the difference. To me it seems there is no difference but what makes you have your own and have different names? Is yours somehow better in some specific cases, cause I am testing it with around 30 interconnected libs and see no difference.

**Comment by muhamedkarajic** [comment]
@Coly010 I added URL of the library example, which is a library which gets build by typegen (C# -> Typescript) and than its installed by us in frontend.

**Comment by muhamedkarajic** [comment]
I believe what the issue is after now reconsidering everything said that its about the fact that .ts is loaded as a default but it has to be stated that its /index, however I think also in some cases index.ts is missing so I have provide index.js. Now after checking it generates index.d.ts but not index.ts.

**Comment by muhamedkarajic** [comment]
@Coly010 any update from your side?

**Comment by Coly010** [comment]
You should generate the `.ts` files, and your libraries should point to them as the entrypoint in your tsconfig.base.json's `compilerOptions.paths` property.

**Comment by muhamedkarajic** [comment]
> You should generate the `.ts` files, and your libraries should point to them as the entrypoint in your tsconfig.base.json's `compilerOptions.paths` property.

It wont work with the .d.ts.? Okay.
