### ISSUE TITLE
Nx CLI commmands hang forever when import from `node:test` package is used

### ISSUE THREAD

**Issue by wdcryer** [nrwl/nx#26683]
### Current Behavior

When I run an Nx command, like `nx report` or `nx run-many -t build` there is no output in the terminal. It hangs forever. Oddly, I tracked the issue down to a line of code I added on my branch:

```js
import { describe, it } from 'node:test';
```

When I remove that line and reset Nx, the CLI starts working properly again. If I add the line back, the CLI hangs again. This issue happens both on my Mac M2 and in CI (Drone) which runs in Linux. 

This is the content of `.nx/workspace-data/d/daemon.log`:
```
[NX Daemon Server] - 2024-06-25T19:09:54.545Z - Started listening on: /var/folders/s4/ftswryd92hldf_c1y5yv1z480000gp/T/a8110bf1a788564e40fe/d.sock
[NX Daemon Server] - 2024-06-25T19:09:54.547Z - [WATCHER]: Subscribed to changes within: /Users/bcryer/Documents/GitHub/core-components/master (native)
[NX Daemon Server] - 2024-06-25T19:09:54.549Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2024-06-25T19:09:54.550Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2024-06-25T19:09:54.550Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2024-06-25T19:09:54.551Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2024-06-25T19:09:55.153Z - [REQUEST]: Updated workspace context based on watched changes, recomputing project graph...
[NX Daemon Server] - 2024-06-25T19:09:55.153Z - [REQUEST]: 
[NX Daemon Server] - 2024-06-25T19:09:55.154Z - [REQUEST]: 
```

I tried adding several environment variables suggested by @barbados-clemens [in the Discord channel](https://discord.com/channels/1143497901675401286/1255169241997512734), such as `NX_VERBOSE_LOGGING=true`, `NX_DAEMON=false`, and `NX_NATIVE_LOGGING="nx"`, but no combination produced any additional logging in the terminal or in `daemon.log`.

### Expected Behavior

Nx CLI commands should not hang forever.

### GitHub Repo

https://github.com/wdcryer/nx-cli-hangs-forever

### Steps to Reproduce

1. Use Node 20. Version managers like NVM or FNM can be used to install the correct version.
2. Run `corepack enable` to install the correct pnpm version.
3. Run `pnpm install`.
4. Run `pnpm nx report` or `pnpm build`.
5. Observe that the command hangs indefinitely.
6. Delete the code in `apps/docs/src/__tests__/some.test.mjs`.
7. Run `pnpm nx report` or `pnpm build`.
8. Observe that the command works as expected.

### Nx Report

```shell
Node   : 20.12.2
OS     : darwin-arm64
pnpm   : 9.1.4

nx             : 19.3.0
@nx/js         : 19.3.0
@nx/workspace  : 19.3.0
@nx/devkit     : 19.3.0
@nrwl/tao      : 19.3.0
typescript     : 4.9.5
```

### Failure Logs

Nothing is logged.

### Package Manager Version

pnpm 9.1.4

### Operating System

- [X] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This reproduction was created by taking a private repository and whittling it down about as much as possible. The private repo has all of the important fields in `package.json` and `nx.json` filled out, as well as many apps and packages.

**Comment by AgentEnder** [comment]
I can't seem to reproduce this, but I wasn't able to reuse the provided lockfile as it contained links to an internal artifactory. Are you still experiencing the issue? Our reports look completely identical but I wouldn't rule out some underlying package change.
