### ISSUE TITLE
.babelrc inside libs

### ISSUE THREAD

**Issue by conioX** [nrwl/nx#2668]
is it possible to add  .babelrc inside libs? i already try to create .babelrc inside libs and add                         "webpackConfig": "@nrwl/react/plugins/webpack" inside libs but not works at all !!

i need add .babelrc because antd use babel-plugin-import to import style

**Comment by jon301** [comment]
Hi

Same problem for me :( Basically I'm trying to create a component library with EmotionJS and I need to add `@emotion/babel-preset-css-prop` to my [babel config presets](https://emotion.sh/docs/css-prop#babel-preset) to be able to use the `css` prop in my react components.

I've tried to update the `babelConfig` property path of my library in `workspace.json` to make it point to this file:

```
module.exports = function (config) {
  const babelConfig = require('@nrwl/react/plugins/bundle-babel')(config);
  babelConfig.presets.push('@emotion/babel-preset-css-prop');
  return babelConfig;
};
```

When I build the library with `nx run mylib:build`, the custom babel config is correctly read (I've put a `console.log` inside), but it does not seem to work :(

![image](https://user-images.githubusercontent.com/122108/82119640-7a331e80-9780-11ea-9089-ad83a491ea56.png)

I've also tried with a custom webpack config (https://github.com/nrwl/nx/issues/1721#issuecomment-521652145 from @jaysoo ) but with no success, as I presume libs read `rollupConfig` and not `webpackConfig`

**Comment by jaysoo** [comment]
As of Nx 9.4 we generate all apps and libs with their own `.babelrc` files. Each project can customize their babel setup, or you can use the root `babel.config.json` file for shared presets and plugins.

When you run the migration for 9.4 you will have all of these files generated for you: `nx migrate @nrwl/workspace@9.4`.

**Comment by Hotell** [comment]
absolutely amazing @jaysoo thx for this!

**Comment by vpalam-om** [comment]
I have the same issue, but `"jsx": "preserve"` didn't work. If I use `css` prop inside my component library and use the component inside nextjs application, the `css` prop ends up containing `You have tried to stringify object...`.
.babelrc for my lib (it was generated automatically during migration to v9.5, I added emotion preset manually):
`{
  "presets": ["@nrwl/react/babel", "@emotion/babel-preset-css-prop"],
  "plugins": []
}`

.babelrc for next application:
`{
  "presets": ["next/babel", "@emotion/babel-preset-css-prop"],
  "plugins": []
}`

Sorry for posting my question in closed issue, but it seems to be very relevant to my problem.

**Comment by codewaseem** [comment]
@vpalam-om I'm facing the same issue. Did you find any solution for this?
