### ISSUE TITLE
nx graph --affected not contain info about affected projects

### ISSUE THREAD

**Issue by Suldenkov** [nrwl/nx#26686]
### Current Behavior

between comands nx graph --affected --file=f.json and nx graph --file=s.json there's no difference.

### Expected Behavior

The documentation says that the flag `affected` Highlight affected projects.

### Steps to Reproduce

1. nx graph --affected --file=f.json
2. nx graph -file=s.json
3. diff f.json s.json

### Nx Report

```shell
nx                 : 19.1.1
@nx/js             : 19.1.1
@nx/jest           : 19.1.1
@nx/linter         : 19.1.1
@nx/eslint         : 19.1.1
@nx/workspace      : 19.1.1
@nx/angular        : 19.1.1
@nx/cypress        : 19.1.1
@nx/devkit         : 19.1.1
@nx/eslint-plugin  : 19.1.1
@nrwl/tao          : 19.1.1
@nx/web            : 19.1.1
@nx/webpack        : 19.1.1
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

If this command is deprecated, can you suggest another way to get an affected project so that it works on versions 12 and 19

**Comment by AgentEnder** [comment]
The best way to just get the list of affected projects in Nx 19 would be `nx show projects --affected`. I believe that should work in v17+

**Comment by Suldenkov** [comment]
> The best way to just get the list of affected projects in Nx 19 would be `nx show projects --affected`. I believe that should work in v17+

I understand that this team is the best option. However, I need to use one way to get the affected project in projects with 19 and then at least with version 13. I wanted to know if this is possible or if all other methods have been disabled since version 19

**Comment by AgentEnder** [comment]
There's not a common command for this use case.
