### ISSUE TITLE
No cached ProjectGraph is available

### ISSUE THREAD

**Issue by AliAzh1991** [nrwl/nx#26695]
### Current Behavior

Hello,

Actually when migrating to NX version 17.3.0, we are facing this error when trying to launch nx:run-commands on the project : 

Could not find 'nx' module in this workspace. Error: [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.
 
If you are leveraging \`readCachedProjectGraph()\` directly then you will need to refactor your usage to first ensure that
the ProjectGraph is created by calling \`await createProjectGraphAsync()\` somewhere before attempting to read the data.

The issue was already raised by another ticket but without any solution (https://github.com/nrwl/nx/issues/10730).

Can you please help us resolve that issue ? 

Thanks.

### Expected Behavior

The issue must be corrected.

### Steps to Reproduce

Execute nx:run-commands on a project using Angular 17.1.2

### Nx Report

```shell
Could not find 'nx' module in this workspace. Error: [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.
 
If you are leveraging \`readCachedProjectGraph()\` directly then you will need to refactor your usage to first ensure that
the ProjectGraph is created by calling \`await createProjectGraphAsync()\` somewhere before attempting to read the data.
```

### Package Manager Version

Yarn : 1.22.19

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by dhaq** [comment]
Same problem

**Comment by alecf** [comment]
seeing on migration from 19.1 to 19.3 and 19.4 (due to dependabot cadence, we never tried 19.2)

**Comment by rosslavery** [comment]
Same here, and can confirm that 19.1.2 works, 19.2.3 does not.

Deleting nx cache doesn't help.

**Comment by AliAzh1991** [comment]
Hello @AgentEnder,

Please find attached the package.json and also bellow the result of the nx report : 

![image](https://github.com/user-attachments/assets/e24c85ca-e5c9-4fc3-bcd9-67078178e969)

Thanks for your help.
[package.json](https://github.com/user-attachments/files/16190419/package.json)

**Comment by AgentEnder** [comment]
Can you try upgrading to the latest Nx 18 or 19 release? This isn't something I can reproduce on 17.3.0 myself. Alternatively, uploading a repository that I can clone to see the issue would also help.
