### ISSUE TITLE
dev-server executor expects certain options, but error message does not give away how to solve

### ISSUE THREAD

**Issue by fhaag** [nrwl/nx#26714]
### Current Behavior

In my `project.json` file, I have a `testserve` target that uses the `@nx/angular:dev-server` executor:
```json
"testserve": {
	"executor": "@nx/angular:dev-server",
	"configurations": {
		"development": {
			"buildTarget": "myProject:build:development"
		}
	},
	"defaultConfiguration": "development"
},
```
`build` is another target in the same `project.json` file. When invoking `nx run testserve`, this works flawlessly.

However, once I replace `myProject:build:development` with another target in the same file, say `myProject:testoutput`:
```json
"testoutput": {
	"command": "echo 'TEST'"
}
```
`nx run testserve` will result in the following error:
> TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string. Received undefined

I suspect only a subset of targets with certain options are eligible to be used here, but unfortunately, the error message does not give away what exactly is required (nor does the [executor's documentation page](https://nx.dev/nx-api/angular/executors/dev-server)).

### Expected Behavior

After my modification of the build target, the expected outcome of invoking `nx run testserve` is that it will output the text `TEST`, and maybe repeat to do so whenever the live reload of `dev-server` strikes.

Alternatively, I'd expect the exact requirements for targets eligible to be used as a `buildTarget` in the `@nx/angular:dev-server` executor options to be outlined on the [documentation page for the `dev-server` executor](https://nx.dev/nx-api/angular/executors/dev-server).

### GitHub Repo

https://github.com/fhaag/angular-cli-bug-repro/tree/buildtarget-nx-issue

### Steps to Reproduce

1. Create a simple project with `ng new repro-app` and `nx init`.
2. Add a simple test target in the `project.json` file, e.g.:
```json
"testoutput": {
	"command": "echo 'TEST'"
}
```
3. Duplicate the `serve` target, rename the copy to `testserve`, change it to use `@nx/angular:dev-server` as its executor and use the newly inserted target from step 2 as the `buildTarget`.
4. Run `nx run testserve` and watch the error message.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 18.17.0
OS     : win32-x64
npm    : 8.9.0

nx (global)    : 19.3.1
nx             : 19.0.8
@nx/js         : 19.0.8
@nx/linter     : 19.0.8
@nx/eslint     : 19.0.8
@nx/workspace  : 19.0.8
@nx/angular    : 19.0.8
@nx/devkit     : 19.0.8
@nrwl/tao      : 19.0.8
@nx/web        : 19.0.8
@nx/webpack    : 19.0.8
typescript     : 4.9.5
```

### Failure Logs

```shell
NX   The "paths[1]" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:167:9)
    at readTsconfig (C:\...\NX\targets\github\repro\node_modules\@angular-devkit\build-angular\src\utils\read-tsconfig.js:44:51)
    at configureI18nBuild (C:\...\NX\targets\github\repro\node_modules\@angular-devkit\build-angular\src\utils\i18n-options.js:125:61)
    at generateI18nBrowserWebpackConfigFromContext (C:\...\NX\targets\github\repro\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:67:80)
    at setup (C:\...\NX\targets\github\repro\node_modules\@angular-devkit\build-angular\src\builders\dev-server\index.js:141:126)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

I had at first assumed this to be an Angular-CLI - specific error and reported it there: https://github.com/angular/angular-cli/issues/27935
However, it was suggested there that this should be reported to the NX project instead.

https://github.com/nrwl/nx/pull/21998 sounds a bit similar (reporting the same error message), but it appears to describe a situation where the target is not used ("Expected Behavior: This error gets bypassed, since the server does not try to resolve the path in the dev environment."), unlike my case, where I very much expect the path to the target (if that is what is meant here?) to be resolved.

**Comment by Coly010** [comment]
I don't want this to degrade into a situation where Angular and ourselves are passing the responsibility back and forth.

However, this _is_ a limitation from the Angular Devkit and is caused by malformed configuration on your part.

The `@nx/angular:dev-server` is an executor which adds some additional options on top of the `@angular-devkit/build-angular:dev-server` builder. But it passes through the options and invokes the Angular builder.

The Angular builder expects `buildTarget` to match the schema from the `@angular-devkit/build-angular:*` builders. The `buildTarget` you're passing does not.

Essentially, you're not using the executor/builder as it should be.

There's no issue here, either on the Nx side, or the Angular side.
