### ISSUE TITLE
generateLockfile option breaks serving application in nx 19.3.2

### ISSUE THREAD

**Issue by jaqua** [nrwl/nx#26716]
### Current Behavior

I've update NX from 19.2.3 to the latest (19.3.2) version. My applications are using the option `generateLockfile`.

In the latest version I do get the error:

    npx nx run project-api:serve

    > nx run project-api:serve:development

    > nx run project-api:build

    > webpack-cli build --generateLockfile=true --node-env=production

    [webpack-cli] Error: Unknown option '--generateLockfile=true'
    [webpack-cli] Run 'webpack --help' to see available commands and options
    Warning: command "webpack-cli build --generateLockfile=true --node-env=production" exited with non-zero status code

Version 19.3.0 is working, 19.3.2 is failing.

### Expected Behavior

Should work as it did in 19.2.3

### Steps to Reproduce

npx nx migrate latest
npm install
npx nx run project-api:serve

### Nx Report

```shell
Node   : 18.18.0
OS     : darwin-arm64
npm    : 9.8.1

nx                 : 19.3.2
@nx/js             : 19.3.2
@nx/jest           : 19.3.2
@nx/linter         : 19.3.2
@nx/eslint         : 19.3.2
@nx/workspace      : 19.3.2
@nx/cypress        : 19.3.2
@nx/detox          : 19.3.2
@nx/devkit         : 19.3.2
@nx/eslint-plugin  : 19.3.2
@nx/expo           : 19.3.2
@nx/nest           : 19.3.2
@nx/next           : 19.3.2
@nx/node           : 19.3.2
@nx/react          : 19.3.2
@nx/react-native   : 19.3.2
@nx/storybook      : 19.3.2
@nrwl/tao          : 19.3.2
@nx/web            : 19.3.2
@nx/webpack        : 19.3.2
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/next/plugin
@nx/react-native/plugin
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin
@nx/cypress/plugin
@nx/storybook/plugin
@nx/expo/plugin
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Did you migrate to using inferred targets manually?
Can you provide a small repro?

If you are using inferred targets `generateLockfile` is not a valid argument for `webpack-cli` This needs to be set inside of the `NxWebpackAppPlugin` found inside your webpack config.
