### ISSUE TITLE
targetDefaults are ignored

### ISSUE THREAD

**Issue by RobbyRabbitman** [nrwl/nx#26742]
### Current Behavior

It does not matter what i put in `@nx/vite:build` in the`targetDefaults`, `@nx/vite` added this property though when adding this package.

nx.json targetDefaults
```json
"@nx/vite:build": {
      "cache": true,
      "dependsOn": ["^build"],
      "inputs": ["default", "^default", "viteGlobals", "^viteGlobals"]
},
```
inferred build target in project (copied from vscode extension, which displays project targets)
```json
"inputs": ["default","^default",{"externalDependencies":["vite"]}]
```

project.json
```json
{
  "name": "web-util",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "targets": {
    "test": {
      "command": "wtr --config=wtr.config.mjs",
      "options": {
        "cwd": "{projectRoot}"
      }
    },
    "stylelint": {}
  },
  "tags": ["scope:web", "type:util"]
}

```

### Expected Behavior

The build target should include the viteGlobals named input.

### Steps to Reproduce

1. add @nx/vite
2. modify @nx/vite:build
3. have a project which uses vite

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.11.1
OS     : darwin-arm64
pnpm   : 8.12.1

nx (global)        : 19.2.3
nx                 : 19.0.3
@nx/js             : 19.0.3
@nx/eslint         : 19.0.3
@nx/workspace      : 19.0.3
@nx/angular        : 19.0.3
@nx/devkit         : 19.0.3
@nx/eslint-plugin  : 19.0.3
@nx/gradle         : 19.0.3
@nx/storybook      : 19.0.3
@nx/vite           : 19.0.3
@nx/web            : 19.0.3
typescript         : 5.4.4
---------------------------------------
Registered Plugins:
@nx/storybook/plugin
@nx/vite/plugin
@nx/eslint/plugin
@nx/gradle
---------------------------------------
Community plugins:
@compodoc/compodoc : 1.1.25
@storybook/angular : 7.6.19
ng-mocks           : 14.13.0
nx-stylelint       : 17.1.5
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
The target default for @nx/vite:build only applies to targets which use the @nx/vite:build executor. Inferred targets typically do not use an executor, and likely are running via nx:run-commands. You should be able to modify them via target defaults based on the target name rather than the executor.

**Comment by RobbyRabbitman** [comment]
Ahhhh, yes! Thats the trick! When using plugins to infer targets, you have to delete the target defaults generated by the vite init generator, since there are no targets which is going to use it anyways...
