### ISSUE TITLE
[FEAT] run-many --tags=tag1,tag2

### ISSUE THREAD

**Issue by snebjorn** [nrwl/nx#2675]
Would be nice if we could use tags with the `nx run-many` command.

Example
```shell
> nx run-many --target=build --tags=core,demo-app
```

**Comment by snebjorn** [comment]
Not sure what to do here. Should I keep this alive until it's implemented or?

**Comment by vsavkin** [comment]
Sorry. The issue was marked by mistake. I removed the label.

**Comment by ericwooley** [comment]
To add on to this, another related feature that would be really nice is the ability to check if something is affected by tag.

EG
```bash
# print affected by tag, one line per service
SERVICES_TO_DEPLOY=$(nx print-affected --target=build --select=tasks.target.project | awk 'gsub(/, /, "\n")')


# if there are more than one line output by 
if [[ $(echo $SERVICES_TO_DEPLOY | wc -l) -gt 0 ]] echo "run build command for services"
```

**Comment by mattposch** [comment]
Yes, Yes, Yes, we need this!! We need to group multiple apps/libs to larger applications and it would be soo nice to be able to run them with a single tag!

**Comment by hassankhan** [comment]
Hi all, just dropping in to share my 0.02c, its seems like the `tags` aren't useful for much right now, adding support for them to the `run-many` command would drastically improve my workflow.

**Comment by ndrsg** [comment]
this feature would be absolutely great!!

**Comment by rabraghib** [comment]
+1

**Comment by marcus-sa** [comment]
Still wondering why this haven't been implemented yet 😅

**Comment by bintoll** [comment]
Agree, it will be quite useful for me also! Right now I have to list all projects as excluded in different tasks manually, grouping projects by tag will simplify this process a lot and make it much more scalable.

**Comment by MitkoTschimev** [comment]
We just came across the same requirement. We tag based on business domains on a higher level. In the pipeline related to the business domain I just want to lint all those projects and this would be very helpful

**Comment by sylvainar** [comment]
That would be great indeed, nice to see there is a PR open for that!
