### ISSUE TITLE
nestjs app is served with `--node-env=production`

### ISSUE THREAD

**Issue by docentYT** [nrwl/nx#26761]
### Current Behavior

When running `nx serve nestjsapp,` webpack builds it in a production mode.

### Expected Behavior

It should be served with `--node-env=development`.

### Steps to Reproduce

See #22880 

### Nx Report

```shell
Node   : 20.12.1
OS     : win32-x64
npm    : 10.5.0

nx (global)        : 19.1.1
nx                 : 19.3.2
@nx/js             : 19.3.2
@nx/jest           : 19.3.2
@nx/linter         : 19.3.2
@nx/eslint         : 19.3.2
@nx/workspace      : 19.3.2
@nx/angular        : 19.3.2
@nx/devkit         : 19.3.2
@nx/eslint-plugin  : 19.3.2
@nx/nest           : 19.3.2
@nx/node           : 19.3.2
@nx/playwright     : 19.3.2
@nrwl/tao          : 19.3.2
@nx/web            : 19.3.2
@nx/webpack        : 19.3.2
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/eslint/plugin
@nx/webpack/plugin
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by morgnism** [comment]
Having the same issue. The docs state that running `nx serve my-nest-app` runs build target in watch mode, but this isn't the case.

**Comment by cdoky** [comment]
![image](https://github.com/user-attachments/assets/861ac35e-5c39-4e9e-b8f4-dbd3754d1fee)
+1，have any solutions?

**Comment by morgnism** [comment]
Correcting my comment from earlier, I found that winning the server target DID run the server in watch mode, but it uses the production build target first and restarts the build on subsequent file changes.

This isn't a huge problem, but it can make it harder to decipher errors when you miss a provider.

**Comment by cdoky** [comment]
Can someone fix it?

**Comment by cdoky** [comment]
https://github.com/nrwl/nx/blob/dc821abd5249bb2769c58e3d9f466bd67bb516fa/packages/webpack/src/plugins/plugin.ts#L160-L180

The plugin defines `--node-env=production` , can anyone improve it?

**Comment by cdoky** [comment]
If you add a build task in project.json, you can perform breakpoint debugging, but hotreload will fail.
```json
"targets": {
"build": {
            "executor": "@nx/webpack:webpack",
            "options": {
                "outputPath": "dist/apps/api",
                "webpackConfig": "apps/api/webpack.config.js"
            }
        },
"serve":...
```

**Comment by SeanLatimer** [comment]
It appears to be forcefully passing `production` [here](https://github.com/nrwl/nx/blob/7d0d834e425488c77a7f9f6360ca51f2f87cdda7/packages/webpack/src/plugins/plugin.ts#L162).

I changed around some of the targets in `project.json` and it appears to work ok other than `build` is always run with `NODE_ENV=production`. `serve` does override to `development` which can be confirmed by throwing `console.log(process.env.NODE_ENV)` in `webpack.config.js`.

```json
{
  "name": "server",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/server/src",
  "projectType": "application",
  "tags": [],
  "targets": {
    "build": {
      "executor": "@nx/webpack:webpack",
      "defaultConfiguration": "production",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/apps/server",
        "webpackConfig": "apps/server/webpack.config.js"
      }
    },
    "serve": {
      "executor": "@nx/js:node",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "server:build",
        "runBuildTargetDependencies": false
      },
      "configurations": {
        "development": {},
        "production": {}
      }
    }
  }
}
```

```js
// webpack.config.js
const { NxAppWebpackPlugin } = require('@nx/webpack/app-plugin');
const { join } = require('path');

console.log(process.env.NODE_ENV);
module.exports = {
  output: {
    path: join(__dirname, '../../dist/apps/server'),
  },
  stats: 'errors-only',
  plugins: [
    new NxAppWebpackPlugin({
      target: 'node',
      compiler: 'tsc',
      main: './src/main.ts',
      tsConfig: './tsconfig.app.json',
      assets: ['./src/assets'],
      optimization: false,
      outputHashing: 'none',
      generatePackageJson: process.env.NODE_ENV === 'production',
      sourceMap: process.env.NODE_ENV === 'development',
    }),
  ],
};
```

**Comment by cdoky** [comment]
haha, the solution is here： https://github.com/nrwl/nx/issues/21517#issuecomment-2242902642

**Comment by morgnism** [comment]
@cdoky This solution works up to the point of hot reload failing, as you mentioned earlier. Have you figured out a workaround for this?

**Comment by cdoky** [comment]
> @cdoky This solution works up to the point of hot reload failing, as you mentioned earlier. Have you figured out a workaround for this?

if hot reload failed, you can fixed it by `nx reset`

**Comment by cdoky** [comment]
@morgnism you can use this solution: https://github.com/nrwl/nx/issues/21517#issuecomment-2242902642, if you hot reload failed, you can fixed it by `nx reset`

**Comment by rsaenen** [comment]
I'm facing this issue with slow "hot reloading" (10x slower than before). You can try to edit this [file](https://github.com/nrwl/nx/blob/7d0d834e425488c77a7f9f6360ca51f2f87cdda7/packages/webpack/src/plugins/plugin.ts#L162) in your node_modules (then run `nx reset`) and you will see that it's still slow to reload after a file change.  

I guess there's an issue with the webpack configuration, webpack won't hot reloading because on each file change, it will build with production mode your app.  

IMO it should run a webpack-cli watch with dev mode and not rebuild the app. 

My webpack configuration that enable debug : 
```javascript
const { NxAppWebpackPlugin } = require('@nx/webpack/app-plugin');
const { join } = require('path');

module.exports = {
  output: {
    path: join(__dirname, '../../dist/apps/<your-app>'),
  },
  plugins: [
    new NxAppWebpackPlugin({
      target: 'node',
      compiler: 'tsc',
      main: './src/main.ts',
      tsConfig: './tsconfig.app.json',
      assets: ['./src/assets'],
      optimization: false,
      outputHashing: 'none',
      sourceMap: process.env.ENV !== 'production',
    }),
  ],
};
```

**Comment by slyk** [comment]
> If you add a build task in project.json, you can perform breakpoint debugging, but hotreload will fail.
> 
> "targets": {
> "build": {
>             "executor": "@nx/webpack:webpack",
>             "options": {
>                 "outputPath": "dist/apps/api",
>                 "webpackConfig": "apps/api/webpack.config.js"
>             }
>         },
> "serve":...

added this to my app project.json and breakpoints start to work. THANK you my friend!!

All newcomers that will try to nestjs with NX now will not have breakpoints until they google that issue? that is very bad for such platform :(

**Comment by cdoky** [comment]
@slyk 
The solution is here： https://github.com/nrwl/nx/issues/21517#issuecomment-2242902642. 
Reset you project.json,
Just modify the webpack.config.js

**Comment by SinPP** [comment]
This is not fixing the mentioned problem.

The dev mode should not try to EVER build any production libs. It makes the nx system completely unusable for small projects. I have one dependent library and a simple file change takes around 3 minutes before the dev server starts up again. The only reason is that it tries to build dependent libraries, which it should NEVER ever do in development mode. Even starting the nestjs service in production mode is flawed.

Any input from the nx team? When is a fix to be expected?

**Comment by rsaenen** [comment]
To enhance DX, you can use nest-cli for dev purposes like local serve.  

1. Create `nest-cli.json`
```json
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "apps/<project-1>/src",
  "monorepo": true,
  "root": "apps/<project-1>",
  "compilerOptions": {
    "tsConfigPath": "apps/<project-1>/tsconfig.nest.json"
  },
  "projects": {
    "<project-1>": {
      "type": "application",
      "root": "apps/<project-1>",
      "entryFile": "main",
      "sourceRoot": "apps/<project-1>/src",
      "compilerOptions": {
        "tsConfigPath": "apps/<project-1>/tsconfig.nest.json"
      }
    },
    "<project-2>": {
      "type": "application",
      "root": "apps/<project-2>",
      "entryFile": "main",
      "sourceRoot": "apps/<project-2>/src",
      "compilerOptions": {
        "tsConfigPath": "apps/<project-2>/tsconfig.nest.json"
      }
    }
  }
}
```

2. Create `apps/<project-1>/tsconfig.nest.json`
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/apps/<project-1>",
    "module": "commonjs",
    "types": ["node"],
    "emitDecoratorMetadata": true,
    "target": "es2021"
  },
  "exclude": ["jest.config.ts", "src/**/*.spec.ts", "src/**/*.test.ts"],
  "include": ["src/**/*.ts"]
}
```

3. Update `apps/<project-1>/project.json` to add a target
```json
{
  "name": "<project-1>",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/<project-1>/src",
  "projectType": "application",
  "tags": [],
  "targets": {
    ...
    "local": {
      "executor": "nx:run-commands",
      "options": {
        "command": "nest start <project-1> --debug --watch --preserveWatchOutput"
      }
    }
  }
}
```

4. Update `package.json` scripts
```json
  "scripts": {
    "dev": "nx run-many --all --target=local --output-style=stream-without-prefixes --verbose --parallel=<your number of projects>", 
```
(be aware that .env.local ou .env will be loaded)

5. If you have projects without nestjs (like react, vue...), add a target local
```json
 "local": {
      "executor": "nx:run-commands",
      "options": {
        "command": "nx serve <other-project>"
      }
    },
```

6. You can run `npm run dev` with faster reload and debug

**Comment by Shoke7** [comment]
This worked for me, but still I do not like the solution. I Nx should try to fix this as soon as possible. @kamilmysliwiec

My project.json
```
{
  "name": "my-project",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/my-project/src",
  "projectType": "application",
  "tags": [],
  "targets": {
    "redis": {
      "executor": "nx:run-commands",
      "options": {
        "command": "pnpm run docker:redis"
      }
    },
    "serve": {
      "executor": "@nx/js:node",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "my-project:build"
      },
      "configurations": {
        "development": {
          "buildTarget": "my-project:build:development",
          "waitUntilTargets": ["redis"]
        },
        "production": {
          "buildTarget": "my-project:build:production"
        }
      }
    },
    "build": {
      "executor": "nx:run-commands",
      "options": {
        "command": "webpack-cli build",
        "args": ["--node-env=development"]
      },
      "configurations": {
        "production": {
          "args": ["--node-env=production"]
        }
      }
    }
  }
}

```

My WebPack:
```
const { NxAppWebpackPlugin } = require('@nx/webpack/app-plugin');
const { join } = require('path');

const isProd = process.env.NODE_ENV === 'production';

module.exports = {
  output: {
    path: join(__dirname, '../../dist/apps/my-project'),
    filename: 'main.js',
  },
  plugins: [
    new NxAppWebpackPlugin({
      target: 'node',
      compiler: 'tsc',
      main: './src/main.ts',
      tsConfig: './tsconfig.app.json',
      optimization: isProd ? true : false,
      outputHashing: isProd ? 'all' : 'none',
      generatePackageJson: true,
      watch: isProd ? false : true,
    }),
  ],
};
```

**Comment by ndcunningham** [comment]
Hi, thanks for filling out this issue.

Yes, this is an actual issue the problem only occurs for the nest plugin which will be updated to ensure that your application can be built and served in dev mode.
