### ISSUE TITLE
[Nest]: Upgrade to NestJS 7

### ISSUE THREAD

**Issue by johannesschobel** [nrwl/nx#2680]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior
I would like to see an upgrade to nestjs 7. The latest version was published last weekend. See here: https://trilon.io/blog/announcing-nestjs-7-whats-new

**Comment by telco2011** [comment]
+1

**Comment by aahmyu** [comment]
Hello, any eta on this?

**Comment by josecolella** [comment]
Any way we can contribute to this?

**Comment by WonderPanda** [comment]
Just to be clear, are you looking for an upgrade that will help you automatically implement necessary changes from the Migration Guide for v6 -> v7? It's pretty easy to upgrade the NestJS dependencies in an NX monorepo just do `yarn upgrade-interactive --latest` and check off all the Nest related packages and you're pretty much good to go.

You'll need to follow the [migration guide](https://docs.nestjs.com/migration-guide) if there were any breaking changes that would impact your code.

I agree that the default NX NestJS scaffolding should be updated to target 7.x but its definitely not a blocker at the moment

**Comment by demisx** [comment]
What's the proper way to upgrade Nx to the latest stable NestJs v7 via npm? We aren't using yarn.

**Comment by johannesschobel** [comment]
I just updated all dependencies manually and did a `npm install`... Worked like a charm

**Comment by juristr** [comment]
FYI, there's an open PR for this #2921

**Comment by wrslatz** [comment]
#2921 has been merged. Should this be closed?

**Comment by johannesschobel** [comment]
Thanks a lot.. closed :)
