### ISSUE TITLE
Lazy loaded components from a library does not affect app

### ISSUE THREAD

**Issue by elgurinn** [nrwl/nx#2681]
This is more of a question/discussion whether this should be the expected behavior or not.

When lazy loading components in Angular 9 from a library the app which is loading the component does not show up as affected if the component has been changed only the library. 

Is it necessary to import the module containing the component for the app to be affected?

## Expected Behavior

App is affected by changing a component in a library which is lazy loaded in the app.

## Current Behavior

App is not affected when changing a component in a library when the component is lazy loaded in the app.

**Comment by rkalita** [comment]
Hi, i faced with the same problem and it also relates to lazy loaded modules, that we're using in libraries.
Here is an example of architecture:

![image](https://user-images.githubusercontent.com/7390722/77152502-aefd5f00-6aca-11ea-8fb8-02b312a350b0.png)

where {role}-shell and data-access - libraries

If i'm making any changes in files, that placed inside shared folder - nx:affected isn't see any changes. I was trying to use **implicitDependencies** in nx.json, but this feature works only for files, we can't write a path to folder there

**Comment by FrozenPandaz** [comment]
Can you please provide a repo with the issue so we can investigate?

If you are using a `loadChildren` or `import()`, the connection should be made.

**Comment by elgurinn** [comment]
I am lazy loading components **not** modules in another feature library.

When I run `nx dep-graph`:
![nxdepgraph](https://user-images.githubusercontent.com/20297705/77180005-380f9880-6ac1-11ea-8b3e-8f6a95028edc.png)

If I make changes to a component in the library, it only show that the library is affected:
![nxaffecteddepgraph](https://user-images.githubusercontent.com/20297705/77180042-4362c400-6ac1-11ea-87c2-7b55e6bcd263.png)


```typescript
// feature-xxx.component.ts
import('@xxx/xxx/xxx/ui/visualization').then(c => {
      this.dynamicContainer.clear();
      this.dynamicCompRef = this.dynamicContainer.createComponent(
        this.cfr.resolveComponentFactory(c[this.componentToLoad])
      );
```

There is no reference to the UI library **module** in the feature library in which it is used. Therefore it does not show up as a dependency. I was just wondering if there is a way to specify that there is a dependency.

**Comment by elgurinn** [comment]
Solved it by using setting implicit dependencies in the nx.json for the app.

```JSON
{
"app": {
      "tags": ["type:app"],
      "implicitDependencies": ["xxx-xxx-xxx-xxx"]
    },

}
```
