### ISSUE TITLE
nx release publish fails when package does not have latest tag

### ISSUE THREAD

**Issue by ColinRhodes** [nrwl/nx#26828]
### Current Behavior

`nx release publish` fails when the package does not have the `latest` tag. This is because `npm view {package-name}` returns empty output when there is no `latest` tag.

I am using versions that are fixed to the same value across all packages, so when I add a new lib to test locally, I don't want to set the `latest` tag, since that would impact all of my packages. Instead, I want to publish a prerelease for all packages.

### Expected Behavior

I'd expect subsequent calls to `npx nx release publish` to successfully publish additional versions of the package.

### Steps to Reproduce

1. NodeJS nx project, with version tags initialized
2. Add new NodeJS publishable library
3. `npx nx release version prerelease --preid=alpha --git-tag=true && npx nx release publish` -- works as expected
4. `npx nx release version prerelease --preid=alpha --git-tag=true && npx nx release publish` -- error below

```
Something unexpected went wrong when checking for existing dist-tags.
   SyntaxError: Unexpected end of JSON input
      at JSON.parse (<anonymous>)
      at runExecutor (/home/runner/work/roadmunk/roadmunk/node_modules/@nx/js/src/executors/release-publish/release-publish.impl.js:75:37)
```

### Nx Report

```shell
Node   : 18.19.1
OS     : linux-x64
npm    : 10.2.4

nx (global)        : 19.3.2
nx                 : 19.3.2
@nx/js             : 19.3.2
@nx/jest           : 19.3.2
@nx/linter         : 19.3.2
@nx/eslint         : 19.3.2
@nx/workspace      : 19.3.2
@nx/cypress        : 19.3.2
@nx/devkit         : 19.3.2
@nx/esbuild        : 19.3.2
@nx/eslint-plugin  : 19.3.2
@nx/express        : 19.3.2
@nx/nest           : 19.3.2
@nx/next           : 19.3.2
@nx/node           : 19.3.2
@nx/react          : 19.3.2
@nx/storybook      : 19.3.2
@nrwl/tao          : 19.3.2
@nx/vite           : 19.3.2
@nx/web            : 19.3.2
@nx/webpack        : 19.3.2
typescript         : 5.4.3
---------------------------------------
Community plugins:
nx-stylelint : 17.1.4
```

### Failure Logs

```shell
Something unexpected went wrong when checking for existing dist-tags.
   SyntaxError: Unexpected end of JSON input
      at JSON.parse (<anonymous>)
      at runExecutor (/home/runner/work/roadmunk/roadmunk/node_modules/@nx/js/src/executors/release-publish/release-publish.impl.js:75:37)
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ColinRhodes** [comment]
Using `nx release publish --first-release` bypasses this error (along with some safety checks), but it seems like a feasible workaround.  

AFAIK using `--first-release` here shouldn't be required because the tags have been initialized, and the publish error is on the 2nd publish, not the 1st one.

**Comment by JamesHenry** [comment]
@ColinRhodes I wasn't able to reproduce with the latest nx. FYI your current instructions don't show you providing a custom dist tag to publish, which would mean you _are_ publishing to latest, so I can't actually be sure what you tried when encountering the issue.

I recommend bumping to the latest nx first, and it's possible the issue has already been addressed. If you are still having the issue, please feel free to reopen with some updated steps to reproduce.

Many thanks!
