### ISSUE TITLE
unused boolean function from storybook knob

### ISSUE THREAD

**Issue by fritzschoff** [nrwl/nx#2682]
Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

use the boolean function in the example file

## Current Behavior

you use the text function twice and the number function once.

## Failure Information (for bugs)

[doc for storybook](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)
On this page at the **Example Files** section you import the boolean function, but you are not using it, as far as I can see it.

### Context

Please provide any relevant information about your setup:

see the [docs](https://nx.dev/angular/guides/modernize-storybook-angular#how-to-use-storybook-in-an-nx-repo)

**Comment by juristr** [comment]
@fritzschoff is this just a docs change?

Basically you mean this `boolean` import in the [storybook Nx docs](https://nx.dev/angular/plugins/storybook/overview#how-to-use-storybook-in-an-nx-repo)

![image](https://user-images.githubusercontent.com/542458/87984777-c7ae6d80-cada-11ea-8815-ac110e57d469.png)

**Comment by fritzschoff** [comment]
Yes this is a doc update request
