### ISSUE TITLE
[plugin] @nx/js generators with `tsc` as bundler install unnecessary SWC packages

### ISSUE THREAD

**Issue by wsuwt** [nrwl/nx#26835]
### Current Behavior

Generating a nx plugin or new library with tsc compiler install `@swc-node/register`, `@swc/cli` and `@swc/core` packages.

### Expected Behavior

Generating a nx plugin or new library with tsc compiler DOES NOT install `@swc-node/register`, `@swc/cli` and `@swc/core` packages.

### Steps to Reproduce

1.  Create a new nx project
2. Run `npx nx g @nx/js:lib my-lib` command
 

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 22.4.0
OS     : darwin-arm64
npm    : 10.8.1

nx                 : 19.4.0
@nx/js             : 19.4.0
@nx/linter         : 19.4.0
@nx/eslint         : 19.4.0
@nx/workspace      : 19.4.0
@nx/devkit         : 19.4.0
@nx/eslint-plugin  : 19.4.0
@nrwl/tao          : 19.4.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
```

### Package Manager Version

10.8.1

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Duplicate issue found https://github.com/nrwl/nx/issues/17871 but it was close by bot.

**Comment by AgentEnder** [comment]
Nx uses @swc-node/register to run plugin code in the local workspace without a transpilation / build step. If this is not something you plan to utilize they can be removed.
