### ISSUE TITLE
`build` command doesn't run the actual script after upgrading to `19.4.0`

### ISSUE THREAD

**Issue by ecoms-ye** [nrwl/nx#26833]
### Current Behavior

Hello, when I tried to build a vite subpackage with `pnpm nx build PACKAGE_NAME`,
the vite script not actually running after upgrading nx from `19.3.1` to `19.4.0`.

```sh
# vite script not actually running (after upgrading to `19.4.0`)
$ pnpm nx build PACKAGE_NAME

> nx run PACKAGE_NAME:build


——————————————————————————————————————————————————————————————————

 NX   Successfully ran target build for project PACKAGE_NAME (229ms)
```

### Expected Behavior

It can be solved by rolling back nx to `19.3.2`.

```sh
# vite is executed (after rolling back to `19.3.2`)
$ pnpm nx build PACKAGE_NAME
# [Dependent script outputs]
> nx run PACKAGE_NAME:generate-type  [local cache]


> PACKAGE_NAME@0.1.0 generate-type /PATH/packages/PACKAGE_NAME
> tsc --project tsconfig.declaration.json


> nx run PACKAGE_NAME:build  [local cache]

# [Vite's outputs]
dist/PACKAGE_NAME.css      16.82 kB │ gzip:  4.52 kB
✓ built in 1.93s

——————————————————————————————————————————————————————————————————

 NX   Successfully ran target build for project PACKAGE_NAME and 1 task it depends on (64ms)

Nx read the output from the cache instead of running the command for 2 out of 2 tasks.
```

### Steps to Reproduce

Sorry it's a unstandard private project without any `@nx/*` plugins.
May I create a reproduce-able repo later after work?

### Nx Report

```shell
$ pnpm nx report

 NX   Report complete - copy this into the issue template

Node   : 20.15.0
OS     : linux-x64
pnpm   : 9.4.0

nx          : 19.4.0
@nrwl/tao   : 19.4.0
typescript  : 5.5.3
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

- the `build` script is in `package.json`, not in `project.json`
- only `nx` package is installed (no `@nx/*` plugins)

**Comment by AgentEnder** [comment]
Hey @ecoms-ye - can you attach a minimum reproduction?
