### ISSUE TITLE
nx serve angular project fails with v19.4.0

### ISSUE THREAD

**Issue by Jonnytoshen** [nrwl/nx#26832]
### Current Behavior

I got an error when trying to serve an Angular project:
```sh
> nx run prospect:serve:development


 NX   Cannot find module '@angular/build/package.json'

Require stack:
- /path-to-workspace/node_modules/nx/src/utils/package-json.js
- /path-to-workspace/node_modules/nx/src/utils/print-help.js
- /path-to-workspace/node_modules/nx/src/command-line/run/run.js
- /path-to-workspace/node_modules/nx/bin/run-executor.js
Pass --verbose to see the stacktrace.


—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Running target serve for project prospect failed

Failed tasks:

- prospect:serve:development

Hint: run the command with --verbose for more details.
```

### Expected Behavior

No errors are thrown and the application is served correctly.

### Steps to Reproduce

1. Run `npx create-nx-workspace@latest --pm yarn` command to create a Angular monorepo workspace.
2. Run `nx serve` command to serve the Angular app. 

### Nx Report

```shell
Node   : 20.15.0
OS     : darwin-x64
yarn   : 4.3.1

nx (global)        : 19.1.1
nx                 : 19.4.0
@nx/js             : 19.4.0
@nx/jest           : 19.4.0
@nx/linter         : 19.4.0
@nx/eslint         : 19.4.0
@nx/workspace      : 19.4.0
@nx/angular        : 19.4.0
@nx/devkit         : 19.4.0
@nx/eslint-plugin  : 19.4.0
@nx/playwright     : 19.4.0
@nrwl/tao          : 19.4.0
@nx/web            : 19.4.0
@nx/webpack        : 19.4.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/eslint/plugin
```

### Package Manager Version

yarn@4.3.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Fafnur** [comment]
Problem installing dependencies. 

A temporary solution is to run the command:
```bash
npm install --foreground-scripts
```

Can be used until a fix is ​​released.

**Comment by jsprw** [comment]
Just installing `@angular/build` worked for me. Would be great if NX allowed us to replace the dependency `@angular-devkit/build-angular:application` with  `@angular/build` (which has 40 less dependencies than devkit) for their `@nx/angular` builder.

**Comment by ciriousjoker** [comment]
The solution provided by @jsprw seems to work, the `--foreground-scripts` didn't. Not sure why installing the dependency manually is necessary though. In my case, I'm running mac os locally (devkit is installed and the referenced package.json file also exists), but linux on ci and it complains that `NX   Unable to resolve @angular-devkit/build-angular:application.`

**Comment by leosvelperez** [comment]
This issue was fixed by https://github.com/nrwl/nx/pull/26979, and the change should be released soon. Please keep an eye on the releases to update and get the fix.
