### ISSUE TITLE
[react-native] `--no*` striped away when being passed to the actual command

### ISSUE THREAD

**Issue by matinzd** [nrwl/nx#26836]
### Current Behavior

--no is getting striped when being forwarded to the main command

<img width="897" alt="Screenshot 2024-07-05 at 13 21 09" src="https://github.com/nrwl/nx/assets/24797481/d69e2ee6-fc5a-4a5c-b394-11779f31c5ee">

### Expected Behavior

--no should not be striped when passing to the main command.

### Steps to Reproduce

1. Initiate a project with React Native CLI

1. Run `nx run-android my-app --no-packager`

1. Error will happen:

```
➜  ✗ nx android my-app --no-packager

> nx run my-app:android --no-packager

Starting JS server...
error: unknown option '--packager'
(Did you mean --no-packager?)

 NX   1
```

`--no-packager` is an option from React Native CLI: https://github.com/react-native-community/cli/blob/main/packages/cli-platform-android/README.md#run-android

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.10.0
OS     : darwin-arm64
npm    : 10.2.3

nx                 : 18.3.4
@nx/js             : 18.3.4
@nx/jest           : 18.3.4
@nx/linter         : 18.3.4
@nx/eslint         : 18.3.4
@nx/workspace      : 18.3.4
@nx/cypress        : 18.3.4
@nx/detox          : 18.3.4
@nx/devkit         : 18.3.4
@nx/eslint-plugin  : 18.3.4
@nx/expo           : 18.3.4
@nx/next           : 18.3.4
@nx/react          : 18.3.4
@nx/react-native   : 18.3.4
@nrwl/tao          : 18.3.4
@nx/web            : 18.3.4
@nx/webpack        : 18.3.4
typescript         : 5.3.3
---------------------------------------
Registered Plugins:
@nx/react-native/plugin
@nx/eslint/plugin
@nx/webpack/plugin
@nx/detox/plugin
@nx/next/plugin
@nx/cypress/plugin
@nx/jest/plugin
@nx/expo/plugin
```

### Package Manager Version

Node v20.10.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
what does your android target look like?
- if you use executor `@nx/react-native:run-android`, it will pass `no-packager` as default, you don't need to pass it down
- if you use plugin, in nx.json, you got something like:
```
"plugins": ["@nx/react-native/plugin"],
```
you can run the command `nx run-android <you app> --no-packager`. it will not parse --no-packager.
