### ISSUE TITLE
NX react with Webpack v19 lost proxyConfig option in serve mode

### ISSUE THREAD

**Issue by ipassynk** [nrwl/nx#26848]
### Current Behavior

proxyConfig is gone from serve options

### Expected Behavior

To have proxyConfig to point to separate file proxy config file. 

### Steps to Reproduce

nx generate @nrwl/react:app my-react-app 
got to apps/my-react-app 
try to add proxyConfig like that and see that nx fails

{
  "name": "grand-central",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/my-app/src",
  "projectType": "application",
  "tags": [],
  "// targets": "to see all targets run: nx show project my-app --web",
  "targets": {
    "serve": {
        "proxyConfig": "/apps/my-app/proxy.conf.json"
      }
    }
  }
}

### Nx Report

```shell
Node   : 16.20.1
OS     : darwin-x64
npm    : 8.19.4

nx (global)        : 19.4.0
nx                 : 19.4.0
@nx/js             : 19.4.0
@nx/jest           : 19.4.0
@nx/linter         : 19.4.0
@nx/eslint         : 19.4.0
@nx/workspace      : 19.4.0
@nx/devkit         : 19.4.0
@nx/eslint-plugin  : 19.4.0
@nx/react          : 19.4.0
@nrwl/tao          : 19.4.0
@nx/web            : 19.4.0
@nx/webpack        : 19.4.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I am sure that it worked before for NX React Webpack projects (may be v 16)

**Comment by ErickRodrCodes** [comment]
hypothetically speaking, my question is if it is needed for you a non LTS version of node such as 16. Did you tried running it with Node 20 which is the active LTS?

**Comment by ipassynk** [comment]
@ErickRodrCodes It is not related to node version at all. ProxyConfig is missing in the schema.

**Comment by jkyoutsey** [comment]
The same thing is happening in my Angular repo that I just upgraded to Angular 18.0.7. My app is DOA without being able to proxy requests. What's the workaround or plan for a fix?

**Comment by ndcunningham** [comment]
You need to define your `proxy` inside of your webpack config https://webpack.js.org/configuration/dev-server/#devserverproxy

Your project is not using an executor so you would not need to define it that way.

**Comment by ipassynk** [comment]
@ndcunningham Yes proxy config inside webpack gives [some ](https://webpack.js.org/configuration/dev-server/#devserverproxy) simple proxy capabilities but having proxy file separated from webpack much more flexible AND NX previous had this option and now it is gone. I don't think it is right idea to close this issue.
