### ISSUE TITLE
Module Federation is serving all the remote apps when the host app is served, and they are all in the same workspace.

### ISSUE THREAD

**Issue by DavesCP** [nrwl/nx#26843]
### Current Behavior

I created my project where I have several apps within the same workspace. 

I am using module federation to connect these microapps. However, the problem I'm facing is that when I start the host application, it starts all the remote applications that are configured in my module-federation.manifest.json instead of starting only the host, even though I haven't configured any application to be started with the devRemotes tag.

![image](https://github.com/nrwl/nx/assets/76002941/a3787567-923f-4091-8f0f-53549a24b9ae)

### Expected Behavior

I expected that when I started the host application, only it would be started, and not all applications at once. After all, I will have many microapps within the same workspace.

### Steps to Reproduce

1.Create a workspace 
2. Create a host app with module federation 
3. Create some remotes apps with module federation and configure file module-federation.manifest.json
4. Serve the host app

### Nx Report

```shell
Executing task: npx nx run host-app:serve 


> nx run host-app:serve:development

 NX  Starting module federation dev-server for host-app with 13 remotes
> nx run beneficios-app:build:development
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
This is working as expected. The other remotes are being served statically. 

This ensures full functionality, without clogging up machine resources.
It is mentioned here: https://nx.dev/concepts/module-federation/faster-builds-with-module-federation#architectural-overview

The idea is that you serve the host, and the remotes it depends on are also served, to ensure full functionality of the application. they are served via `http-server` to reduce the resource usage on your machine. this means if you make changes to those remotes, the changes will not be reflected.

The `--devRemotes` option is used to serve one or more remote applications with `webpack-dev-server` to allow for full HMR and live reloading, but it is more resource intensive.
