### ISSUE TITLE
VSCode error when using TS path mappings with wildcards

### ISSUE THREAD

**Issue by Tallyb** [nrwl/nx#26868]
### Current Behavior

this is the same as https://github.com/nrwl/nx/issues/11671 which marked as resolve with no resolution. 

### Expected Behavior

error should not be shown. Error occurs when there is a tsconfig path`"xxx/*": ['xxx/yyy/*"] `

### Steps to Reproduce

1.
define a path as above

### Nx Report

```shell
nx                 : 19.3.2
@nx/js             : 19.3.2
@nx/jest           : 19.3.2
@nx/linter         : 19.3.2
@nx/eslint         : 19.3.2
@nx/workspace      : 19.3.2
@nx/angular        : 19.3.2
@nx/cypress        : 19.3.2
@nx/devkit         : 19.3.2
@nx/eslint-plugin  : 19.3.2
@nx/plugin         : 19.3.2
@nx/storybook      : 19.3.2
@nrwl/tao          : 19.3.2
@nx/web            : 19.3.2
@nx/webpack        : 19.3.2
typescript         : 5.4.5
---------------------------------------
Community plugins:
@ngrx/signals        : 17.2.0
@rx-angular/cdk      : 17.1.0
@rx-angular/template : 17.2.0
@storybook/angular   : 8.1.6
ng-mocks             : 14.13.0
ngxtension           : 3.4.0
nx-stylelint         : 17.1.5
---------------------------------------
Local workspace plugins:
	 generators
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Could you please provide a repo where we can reproduce the issue to help us debug and fix the issue?

**Comment by leosvelperez** [comment]
@Tallyb thanks for providing a repro! We'll take a look.

**Comment by leosvelperez** [comment]
Closing this one in favor of https://github.com/nrwl/nx-console/issues/2222 as this is an Nx Console issue.
