### ISSUE TITLE
Failed to set bitbucket-pipelines for generating CI workflow

### ISSUE THREAD

**Issue by MansurIsakov** [nrwl/nx#26875]
### Current Behavior

Returns error:

_Generating CI workflow
Failed to generate CI workflow
Error:
NX Generating @nx/workspace:ci-workflow
NX Property 'ci' does not match the schema. 'bitbucket' should be one of github, circ
leci, azure, bitbucket-pipelines, gitlab._

### Expected Behavior

Returns success message and creates CI workflow for bitbucket pipelines

### Steps to Reproduce

1. Create new NX Angular project by running command `npx create-nx-workspace@18 payme-fallbacks --preset=angular-monorepo`
2. Proceed till the last step of choosing CI workflow
3. Pick Bitbucket Pipelines from the list
![IMAGE 2024-07-10 16:15:33](https://github.com/nrwl/nx/assets/72330622/c93e8f0f-5fb6-463d-89c6-5674cc0dd683)
![IMAGE 2024-07-10 16:15:34](https://github.com/nrwl/nx/assets/72330622/7801d49d-1fd5-4b52-955f-c2c58167a3d3)

### Nx Report

```shell
I couldnt create project, so im leaving it empty
```

### Package Manager Version

npm 10.2.4

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
This was fixed with https://github.com/nrwl/nx/pull/26890
