### ISSUE TITLE
Please deprecate @nrwl/nx

### ISSUE THREAD

**Issue by snebjorn** [nrwl/nx#2688]
## Expected Behavior

[@nrwl/nx](https://www.npmjs.com/package/@nrwl/nx) is no longer used/maintained and should be marked as [deprecated](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions#deprecating-an-entire-package).
The deprecation message should point to [@nrwl/workspace](https://www.npmjs.com/package/@nrwl/workspace)

## Current Behavior

@nrwl/nx looks like a valid package.

**Comment by FrozenPandaz** [comment]
@vsavkin 

Should we publish an `8.0.0` and deprecate it?

**Comment by snebjorn** [comment]
This is still an issue

**Comment by vsavkin** [comment]
Sorry. The issue was marked by mistake. I removed the label.

**Comment by vsavkin** [comment]
Deprecated it. Closing the issue.

**Comment by romanblanco** [comment]
@vsavkin The documentation still refers to the deprecated package: https://nx.dev/angular/cli/overview#installing-the-cli
