### ISSUE TITLE
PNPM 9.5 Overrides problem on the auto generate package json for @nx/webpack:webpack

### ISSUE THREAD

**Issue by ZanchiStefano** [nrwl/nx#26884]
### Current Behavior

During the migration from NX 19.0.8 to 19.4.2 and PNPM 8.15.7 to 9.5 we encountered the following problem.

Using PNPM 9.5 with the `@nx/webpack:webpack` and the flag `generatePackageJson` set to true, the generation of the package.json and the pnpm-lock.yaml are incorrect because of the overrides present in the lock but not in the package.

Because of that, when we try to generate the build for production with the following command `pnpm i --prod --frozen-lockfile` we obtain:

> ERR_PNPM_LOCKFILE_CONFIG_MISMATCH Cannot proceed with the frozen installation. The current "overrides" configuration doesn't match the value found in the lockfile

This problem appears even with a fresh installation.

### Expected Behavior

The correct behaviour is that the package.json and the pnpm-lock.yaml are aligned and the command `pnpm i --prod --frozen-lockfile` will work just fine.

### GitHub Repo

https://github.com/ZanchiStefano/nx-pnpm-error

### Steps to Reproduce

With the repo linked:
1. Clone the repo and install all the dependency
2. Execute the command `pnpm exec nx run nx-pnpm-error:build:production`
3. Look in the `dist` folder generated inside the folder `apps/nx-pnpm-error`

You can see there the anomaly of the package and pnpm lock.

### Nx Report

```shell
Node   : 20.15.1
OS     : win32-x64
pnpm   : 9.5.0

nx                 : 19.4.2
@nx/js             : 19.4.2
@nx/jest           : 19.4.2
@nx/linter         : 19.4.2
@nx/eslint         : 19.4.2
@nx/workspace      : 19.4.2
@nx/devkit         : 19.4.2
@nx/eslint-plugin  : 19.4.2
@nx/nest           : 19.4.2
@nx/node           : 19.4.2
@nrwl/tao          : 19.4.2
@nx/web            : 19.4.2
@nx/webpack        : 19.4.2
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

### Package Manager Version

9.5.0

### Operating System

- [ ] macOS
- [x] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by tiagovtristao** [comment]
We are also bumping into this problem, so just using `pnpm install` for now.
