### ISSUE TITLE
Could not connect to the debugger when using the default port (0)

### ISSUE THREAD

**Issue by eranshmil** [nrwl/nx#2690]
## Expected Behavior

Recently, I upgraded our project from Angular 8.x to 9.x, Nest 6.x to 7.x and Nx 8.x to 9.x. Since then the debugger could not connect to the process.

![image](https://user-images.githubusercontent.com/9721664/77099256-51123e00-6a1c-11ea-95dc-b47138a839c8.png)

## Current Behavior

After the upgrade and migration, only `passWithNoTests` been added to the `angular.json` and there were no changes to `nx.json` and any of the `tsconfigs`.
It is not working even without the changes to the files and only using the upgraded dependencies.

I am running the project from the terminal using `ng serve` and I tried reopening `VScode`, removing/reinstalling `node_modules` and also debugging using the Chrome's `dedicated Node DevTools for Node.js`.

When adding `port` to the options in `angular.json` it works without any problem.
So it is probably related to #2510.

### Steps to Reproduce

You can find my repro [here](https://github.com/eranshmil/repro-nx-nest-debug). In `master` branch you can find the files before the upgrade, and in `nx9` branch the upgraded version.

Or just run the following steps:

1. Create a new workspace using the latest v8:

   ```sh
   npx create-nx-workspace@8.12.9 repro-nx-nest-debug
   ```

1. Upgrade nx:

   ```sh
   yarn update
   ```

1. Add a breakpoint and run the api:

   ```sh
   yarn start api
   ```

1. Try to attach to the process using the options `Debug: Attach to Node process` from the `Command Palette...`.

### Context

- I'm using VSCode 1.43.1 and Node.js 12.8.1

<details>
<summary>nx report</summary>

```sh
  @nrwl/angular : 9.1.2
  @nrwl/cli : 9.1.2
  @nrwl/cypress : 9.1.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.1.2
  @nrwl/linter : 9.1.2
  @nrwl/nest : 9.1.2
  @nrwl/next : Not Found
  @nrwl/node : 9.1.2
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.1.2
  @nrwl/web : Not Found
  @nrwl/workspace : 9.1.2
  typescript : 3.7.5
```

</details>

<details>
<summary>Relevant packages</summary>

```sh
  @angular-devkit/build-angular@0.900.6
  @angular/cli@9.0.6
  @angular/common@9.0.7
  @angular/compiler@9.0.7
  @angular/compiler-cli@9.0.7
  @angular/core@9.0.7
  @nestjs/common@7.0.3
  @nestjs/core@7.0.3
  @nestjs/jwt@7.0.0
  @nestjs/passport@7.0.0
  @nestjs/platform-express@7.0.3
  @nestjs/platform-socket.io@7.0.3
  @nestjs/schematics@7.0.0
  @nestjs/serve-static@2.1.0
  @nestjs/swagger@4.4.0
  @nestjs/testing@7.0.3
  @nestjs/typeorm@7.0.0
  @nestjs/websockets@7.0.3
  core-js@3.6.4
  ts-node@8.6.2
  tslib@1.11.1
```

</details>

<details>
<summary>Relevant project configuration in angular.json</summary>

```json
  "server": {
    "root": "apps/server",
    "sourceRoot": "apps/server/src",
    "projectType": "application",
    "prefix": "server",
    "schematics": {},
    "architect": {
      "build": {
        "builder": "@nrwl/node:build",
        "options": {
          "outputPath": "dist/apps/server",
          "main": "apps/server/src/main.ts",
          "tsConfig": "apps/server/tsconfig.app.json",
          "assets": ["apps/server/src/assets"]
        },
        "configurations": {
          "production": {
            "optimization": true,
            "extractLicenses": true,
            "inspect": false,
            "fileReplacements": [
              {
                "replace": "apps/server/src/environments/environment.ts",
                "with": "apps/server/src/environments/environment.prod.ts"
              }
            ]
          }
        }
      },
      "serve": {
        "builder": "@nrwl/node:execute",
        "options": {
          "buildTarget": "server:build"
        }
      },
      "lint": {
        "builder": "@angular-devkit/build-angular:tslint",
        "options": {
          "tsConfig": [
            "apps/server/tsconfig.app.json",
            "apps/server/tsconfig.spec.json"
          ],
          "exclude": ["**/node_modules/**", "!apps/server/**"]
        }
      },
      "test": {
        "builder": "@nrwl/jest:jest",
        "options": {
          "jestConfig": "apps/server/jest.config.js",
          "maxWorkers": 3,
          "tsConfig": "apps/server/tsconfig.spec.json",
          "passWithNoTests": true
        }
      }
    }
  }
```

</details>

**Comment by FrozenPandaz** [comment]
VSCode does not support port 0 yet (https://github.com/microsoft/vscode/issues/52373)

@Cammisuli Do you think it makes sense to revert the change to the default port because vscode doesn't support it?

**Comment by Cammisuli** [comment]
@FrozenPandaz this is hard to balance; if we revert the change, then we will lose the dev experience of watching and reloading.

**Comment by eranshmil** [comment]
Maybe you should revert this change and add a section about it in the documentation and let the user choose whether to set the port in the options to 0 or not.

**Comment by fsystemdevelopment** [comment]
For anyone having the same issue, fast solution add port to angular.json in section see attached 
![port](https://user-images.githubusercontent.com/24252788/79213664-d802dc80-7e49-11ea-9860-ec9e32b091bf.PNG)

**Comment by Cammisuli** [comment]
@fsystemdevelopment provides the solution for this. 

Also VSCode now provides the JavaScript debugging terminal where it’ll start debugging node scripts as soon as the command is executed. 

I’m gonna close this for now because the solution was provided. We can reopen if needed 🙂

**Comment by snaerth** [comment]
I have the exact same config but still not being able to run the attach process
```
Error processing attach: Error: Could not connect to debug target at http://localhost:7777: Promise was canceled
at e (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:1:103397)
```

The launch config
![image](https://user-images.githubusercontent.com/8678089/101208497-2f202080-366a-11eb-8669-07f2b7fdd92e.png)

The workspace config
![image](https://user-images.githubusercontent.com/8678089/101208576-47903b00-366a-11eb-96e8-f29735f01cc1.png)

Any idea what I might be missing?

**Comment by micaelmbagira** [comment]
@Cammisuli Do you have an example (`launch.json`) config that works with the new VSCode debugger and `"port": 0`?
