### ISSUE TITLE
core:runCommands: explicit `--parallel` argument doesn't override env variable `NX_PARALLEL`

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#26903]
### Current Behavior

inline CLI arguments won't override global env variables.

`NX_PARALLEL=8 yarn nx run-many -t e2e --parallel=1`

will result in running `e2e` target in parallel process ( which in case of cypress will fail )

there is a bug within implementation: https://github.com/nrwl/nx/blob/2c4c2ae8ca525b973df97b4d8721709b481ad027/packages/nx/src/utils/command-line-utils.ts#L180-L196

### Expected Behavior

CLI arguments should override ENV `NX_` variables. 

> **NOTE:** haven't checked all source but I think it would be good to have this behaviour consistent for all ENV variables vs inline provided arguments 

### GitHub Repo

- https://github.com/microsoft/fluentui/pull/31949
- commit as a workaround https://github.com/microsoft/fluentui/pull/31949/commits/7e077d9cebf1fcae0167f36e1be3dadf1cfbcbb9

### Steps to Reproduce

1. clone the PR branch
2. `NX_PARALLEL=8 yarn nx run-many -t e2e --parallel=1`

### Nx Report

```shell
Node   : 20.15.0
OS     : darwin-arm64
yarn   : 1.23.34

nx                 : 19.3.2
@nx/js             : 19.3.2
@nx/jest           : 19.3.2
@nx/linter         : 19.3.2
@nx/eslint         : 19.3.2
@nx/workspace      : 19.3.2
@nx/devkit         : 19.3.2
@nx/eslint-plugin  : 19.3.2
@nx/node           : 19.3.2
@nx/plugin         : 19.3.2
@nrwl/tao          : 19.3.2
typescript         : 5.0.4
---------------------------------------
Local workspace plugins:
         @fluentui/workspace-plugin
```

### Package Manager Version

yarn v1

### Operating System

- [X] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Hey Martin 👋 

Looking in to this now, I think what you are saying makes sense. Shouldn't be a terribly hard changeset.

Thanks.

**Comment by Hotell** [comment]
awesome , thx for quick fix @AgentEnder  🤝
