### ISSUE TITLE
The Nx CLI could not find or load the native binary for your supported platform (win32-x64)

### ISSUE THREAD

**Issue by muhammaduxair** [nrwl/nx#26937]
### Current Behavior

I want to create a fresh nx workspace with preset of an Angular app but facing this issue:
![image](https://github.com/user-attachments/assets/0e6153d3-ba3d-4b53-a25d-e80db7f4564b)

### Expected Behavior

No error message when creating new nx workspace in Windows (win32-x64)

### Steps to Reproduce

1. run command `npx create-nx-workspace@latest standalone-org --preset=angular-standalone`

### Nx Report

```shell
-
```

### Failure Logs

```shell
NX   Missing Platform Dependency

The Nx CLI could not find or load the native binary for your supported platform (win32-x64).
This likely means that optional dependencies were not installed correctly, or your system is missing some system dependencies.
For more information please see https://nx.dev/troubleshooting/troubleshoot-nx-install-issues
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by chriscurnow** [comment]
Something is going on here. See #26930

**Comment by MaxKless** [comment]
Hey thanks for the report! 
Did you go through the Nx Install troubleshooting guide? 
Issues like this are often related to nvm or node installation issues. 

https://nx.dev/troubleshooting/troubleshoot-nx-install-issues

Please let me know if you've gone through the steps in here and are still facing issues.

**Comment by chriscurnow** [comment]
@MaxKless Please see my comments in #26930.

I don't understand the troubleshooting guide.

Does it mean the whole initial installation, eg npx create-nx-workspace...?

In my case, that would be quite onerous. I have already gone through the whole installation process and that seemed to work. It is only when I issue an nx command I get the error message.

I did eventually find a pretty simple workaround that might help you trace the problem. See my comment here: https://github.com/nrwl/nx/issues/26930#issuecomment-2227275804.

It is strange that this has just started happening. Over the years, I have created several angular mono repos for different clients, and this has never been a problem.

**Comment by muhammaduxair** [comment]
@MaxKless when I went through the troubleshooting guide, I found a solution that worked for me: [Microsoft Visual C++ Redistributable](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).

Thanks ❤️
