### ISSUE TITLE
nx cypress debuggin

### ISSUE THREAD

**Issue by rovshenn** [nrwl/nx#2693]
- [] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

setting debugging on the cli should enable debugging messages on cypress
cli: set DEBUG=cypress:*

debugging messages using debugger plugin by cyprerss with proper namespace

## Current Behavior

setting debugging on the cli does not cause cypress to show debugging messages
cli: set DEBUG=cypress:*

no debugging messages 

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create a brand new app with cypress e2e tests
2. set DEBUG=cypress:* and run ng run rn-e2e:e2e --headless (this command is taken directly from nx -> e2e -> run)
3. no cypress logs

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context

nx --version 8.12.10
Cypress package version: 4.0.2
Cypress binary version: 4.0.2
node -v v12.16.1
yarn -v 1.19.1

**A minimal reproduction scenario allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

Please include any relevant log snippets or files here.

## Other

Any other relevant information that will help us help you.

**Comment by rovshenn** [comment]
@vsavkin could you please take a look? the debugging was working when we used pure cypress

**Comment by FrozenPandaz** [comment]
How are you setting the environment variable?

When I run the command as follows:

```
DEBUG=cypress:* yarn e2e products-e2e
```

I am able to see debug information:
![image](https://user-images.githubusercontent.com/8104246/77200559-2ded9a00-6ac1-11ea-90fe-640808826632.png)

**Comment by rovshenn** [comment]
This command did it, thank you very much @FrozenPandaz . I was just not passing the debug flag the right way!
