### ISSUE TITLE
Remix recipe does not have `development` task

### ISSUE THREAD

**Issue by 13ogrammer** [nrwl/nx#26943]
### Current Behavior

The README in the Remix application created using Remix Recipe (@nx/remix) mentions the command `npx nx dev myapp` to run the app in development environment. However, the `project.json` file in the remix app does not have `dev` task in the `targets`. Hence, when running the command it throws the following error:
`cannot find configuration for task myapp:dev`

### Expected Behavior

I expect the `npx nx dev myapp` command to run the remix application in a development environment with hot reloading.

### Steps to Reproduce

1. Follow the instructions on https://nx.dev/nx-api/remix to setup a remix application.
2. run `npx nx dev myapp` in the terminal

### Nx Report

```shell
Node   : 18.19.0
OS     : darwin-arm64
yarn   : 1.22.21

nx (global)        : 19.4.3
nx                 : 19.1.1
@nx/js             : 19.1.1
@nx/jest           : 19.1.1
@nx/linter         : 19.1.1
@nx/eslint         : 19.1.1
@nx/workspace      : 19.1.1
@nx/cypress        : 19.1.1
@nx/devkit         : 19.1.1
@nx/eslint-plugin  : 19.1.1
@nx/playwright     : 19.1.1
@nx/react          : 19.1.1
@nx/remix          : 19.1.1
@nx/storybook      : 19.1.1
@nrwl/tao          : 19.1.1
@nx/vite           : 19.1.1
@nx/web            : 19.1.1
@nx/webpack        : 19.1.1
typescript         : 5.4.2
```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Try again with latest Nx (19.5.0 at time of writing). Dev target is inferred by the `@nx/remix/plugin`. 

I verified it just now and have updated the docs to reflect it
