### ISSUE TITLE
Production build (shell app) does not build remotes apps via host app build

### ISSUE THREAD

**Issue by pawelofieldly** [nrwl/nx#26944]
### Current Behavior

I have migrated nx 18 -> 19 and I noticed that remotes apps are not built up. My project is created by module federation config. Previously it was enough to run nx run shellapp:build to build the shell project and remote apps at once time. Now I have to run remote:build separately for each remote. I've tried it by create new empty workspace project and setup MF from scratch as it's described in documentation. It also fails. Is it bug or a feature ?

### Expected Behavior

Build remote apps together with shell app

### Steps to Reproduce

1. Create empty folder
2. setup project as in documentation: `nx g @nx/angular:host shell --directory=apps/angular/with-remotes/shell --remotes=remote1,remote2` https://nx.dev/recipes/module-federation/create-a-host
3. nx run shell:build

I've also added  ` "implicitDependencies": ["remote1", "remote2"],`  it ends up succeeded but remotes apps are still not built up as in nx18

### Nx Report

```shell
Node   : 20.15.0
OS     : darwin-arm64
npm    : 10.7.0

nx                 : 19.4.3
@nx/js             : 19.4.3
@nx/jest           : 19.4.3
@nx/linter         : 19.4.3
@nx/eslint         : 19.4.3
@nx/workspace      : 19.4.3
@nx/angular        : 19.4.3
@nx/devkit         : 19.4.3
@nx/eslint-plugin  : 19.4.3
@nrwl/tao          : 19.4.3
@nx/web            : 19.4.3
@nx/webpack        : 19.4.3
typescript         : 5.4.5
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
The `implicitDependencies` are required to inform Nx to build other projects first.

If that is missing, then Nx will not know to build the remotes.

It is intentionally not added when generating hosts with remotes to support independent deployability of remote applications

**Comment by pawelofieldly** [comment]
@Coly010 I've added implicit dependencies (as I mention :)) and it doesn't work as well. I've added it to the shell project.json

**Comment by Coly010** [comment]
@pawelofieldly Ah yes, in that case your `nx.json` is missing the following in `targetDefaults`

```json
"build": {
   "dependsOn": ["^build"]
}
```

**Comment by pawelofieldly** [comment]
@Coly010 Thanks, it seems that my project builds up properly now :)

**Comment by EnochGao** [comment]
Has the issue been fixed? Why do I still have this problem？
#27448

**Comment by EnochGao** [comment]
@Coly010
