### ISSUE TITLE
@nx/playwright ignoring --project argument

### ISSUE THREAD

**Issue by MillerSvt** [nrwl/nx#26965]
### Current Behavior

`nx e2e app --project=chromium`
Runs all tests, ignoring the --project parameter

### Expected Behavior

Runs only tests in the chromium project

### GitHub Repo

https://github.com/nrwl/nx/issues/26965#issuecomment-2258177471

### Steps to Reproduce

1. Create angular application with playwright as e2e test runner
2. Create e2e test
3. Add some projects for different browsers in playwright.config.ts
4. Run `nx e2e app --project=some-project`

### Nx Report

```shell
nx report

 NX   Report complete - copy this into the issue template

Node   : 20.12.2
OS     : darwin-arm64
npm    : 10.5.0

nx              : 18.3.5
@nx/js          : 18.3.5
@nx/jest        : 18.3.5
@nx/linter      : 18.3.5
@nx/eslint      : 18.3.5
@nx/workspace   : 18.3.5
@nx/angular     : 18.3.5
@nx/devkit      : 18.3.5
@nx/playwright  : 18.3.5
@nrwl/tao       : 18.3.5
@nx/web         : 18.3.5
@nx/webpack     : 18.3.5
typescript      : 5.4.5
---------------------------------------
Community plugins:
@jsverse/transloco         : 7.4.2
@ngrx/effects              : 17.0.1
@ngrx/entity               : 17.0.1
@ngrx/store                : 17.0.1
@ngrx/store-devtools       : 17.0.1
@taiga-ui/cdk              : 3.84.0
@taiga-ui/core             : 3.84.0
@taiga-ui/proprietary-core : 3.84.0
```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Hey, can you retry this with the latest of Nx (19.5)?

If it still doesn't work, could you provide a repo with a minimal reproduction, it would be super helpful.

**Comment by MillerSvt** [comment]
Repo: https://github.com/MillerSvt/nx-playwright-bug-repro
Command: `nx e2e app-e2e --project=chromium`
Result:
```
  3 failed
    [chromium] › example.spec.ts:3:5 › has title ───────────────────────────────────────────────────
    [firefox] › example.spec.ts:3:5 › has title ────────────────────────────────────────────────────
    [webkit] › example.spec.ts:3:5 › has title ─────────────────────────────────────────────────────
```

**Comment by MillerSvt** [comment]
Could you fix it for version 18 as well?

**Comment by MillerSvt** [comment]
@Coly010 what?

**Comment by Coly010** [comment]
Yeah, this one is kind of a "special case" because Nx CLI has an `arg` called `project` also.
