### ISSUE TITLE
 NX doesnt install on my Macbook

### ISSUE THREAD

**Issue by freezepro** [nrwl/nx#26996]
### Current Behavior

I was trying to install NX via several commands via NPM, I am always getting following issue

node_modules/@nx/js/node_modules/nx/src/native/native-bindings.js:244
npm ERR!     throw loadError
npm ERR!     ^
npm ERR! 
npm ERR! Error: Cannot find module '@nx/nx-darwin-arm64'
npm ERR! Require stack:...
 Require stack:
npm ERR! - /Users/.../project/node_modules/@nx/js/node_modules/nx/src/native/index.js
npm ERR! - Users/.../project/node_modules/@nx/js/node_modules/nx/src/hasher/node-task-hasher-impl.js
npm ERR! -Users/.../project//node_modules/@nx/js/node_modules/nx/src/hasher/task-hasher.js
---

1) I've removed packages lock json and node_modules folder and tried again , 
2) tried to clean via npm cache clean --force 
3) when I am trying to run npm uninstall nx , getting same error as above. 

my device is Apple M1 Pro 
my Nodejs says I am on arm64

### Expected Behavior

Has to install 

### Steps to Reproduce

1.

### Nx Report

```shell
as it installed I think I have nothing for that
```

### Package Manager Version

NPM 20.12.2

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Have you gone through this guide? https://nx.dev/troubleshooting/troubleshoot-nx-install-issues#troubleshoot-nx-installations

Also, do you have any flags that disable installing optional dependencies?
