### ISSUE TITLE
`nx report` yield "Cannot convert undefined or null to object" error after upgrading from 14.8.6 to 15.0.0

### ISSUE THREAD

**Issue by trend-min-wang** [nrwl/nx#26999]
### Current Behavior

`nx serve` and `nx report` will yield "Cannot convert undefined or null to object" error `

### Expected Behavior

`nx serve` command should start the application

### GitHub Repo

https://github.com/trend-min-wang/nx-example.git

### Steps to Reproduce

1. `git clone https://github.com/trend-min-wang/nx-example.git`
2. `cd nx-example`
3. `npm i`
4. `npm start`

### Nx Report

```shell
>  NX   Cannot convert undefined or null to object

   
   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
```

### Failure Logs

```shell
>  NX   Cannot convert undefined or null to object

   
   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
```

### Package Manager Version

10.7.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
If you updated to 15.0.13 then the repo works. We recommend updating to the latest minor of the major version. Or at least the latest patch for the major+minor version.
