### ISSUE TITLE
Nx updates my Next version after creating a new application

### ISSUE THREAD

**Issue by YuriyDyachkov** [nrwl/nx#27004]
I have a large project on Next and I want to divide it into several projects and collect everything into a monorepository using Nx.

1. I first initiated my project with the command `npx nx@latest init --integrated`. 
2. Then I made a monorepository from the project using the `nx g convert-to-monorepo` command. I had to work with the configs, but I was able to launch the project. 
3. Next, I wanted to create another application in my monorepository and move some of the code there. I use the `nx g @nx/next:application` command to create another application and Nx updates all my dependencies, upgrading the Next version to 14+, but I don't want to do that at this stage and my application breaks. 

How can I get around this?
Am I doing something wrong?

**Comment by MilanKovacic** [comment]
When you use generators for the first time, or migrate to new versions of nx, it runs the migrations as specified here: https://github.com/nrwl/nx/blob/master/packages/next/migrations.json

Sometimes, these migrations involve updating related packages to achieve compatibility with infrastructure.
I recommend first upgrading your application, and then splitting it.
