### ISSUE TITLE
Tailwind does not work in new workspace with React, No React Framework, Rspack, Tailwind setup

### ISSUE THREAD

**Issue by sirajc** [nrwl/nx#27028]
### Current Behavior

Create a new Nx workspace, Select React, No React Framework, Rspack, Tailwind
Tailwind setup does not work

Create a new Nx workspace, Select React, No React Framework, Webpack, Tailwind
Tailwind setup works

Going through manual setup as mentioned in nx.dev didn't helped either.

### Expected Behavior

Tailwind should work with Rspack &  React

### Steps to Reproduce

Create a new Nx workspace, Select React, No React Framework, Rspack, Tailwind
Tailwind setup does not work

### Nx Report

```shell
Node   : 18.16.0
OS     : darwin-arm64
npm    : 9.5.1

nx (global)        : 19.5.1
nx                 : 19.5.1
@nx/js             : 19.5.1
@nx/jest           : 19.5.1
@nx/linter         : 19.5.1
@nx/eslint         : 19.5.1
@nx/workspace      : 19.5.1
@nx/cypress        : 19.5.1
@nx/devkit         : 19.5.1
@nx/eslint-plugin  : 19.5.1
@nx/playwright     : 19.5.1
@nx/react          : 19.5.1
@nrwl/tao          : 19.5.1
@nx/web            : 19.5.1
typescript         : 5.5.3
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/playwright/plugin
@nx/jest/plugin
---------------------------------------
Community plugins:
@nx/rspack : 19.2.0
```

### Failure Logs

```shell
No Logs or error
```

### Package Manager Version

npm 9.5.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Tailwind docs suggest `postcss-loader` in configuration for `rspack` which is missing in `@nx/rspack` + `@nx/react` combo

https://tailwindcss.com/docs/guides/rspack

**Comment by semanticist21** [comment]
rspack.config.js should be like this!

module.exports = composePlugins(withNx(), withReact(), (config) => {
  return {
    ...config,
    module: {
      rules: [
        ...config.module.rules,
        {
          test: /\.css$/,
          use: ['postcss-loader'],
          type: 'css',
        },
      ],
    },
  };
});
