### ISSUE TITLE
Incorrect exit code when karma tests fail in CI

### ISSUE THREAD

**Issue by stevesouth** [nrwl/nx#27041]
### Current Behavior

I am trying to set up nx in our CI pipeline, but i'm struggling with incorrect exit codes when tests fail.

Strangely it works locally on my mac, but in CI which is the following environment, the test command is returning a 0 exit code.

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

node -v
v20.13.0

pnpm nx --version
Nx Version:
- Local: v19.5.1
- Global: Not found

"test": "karma start  --browsers ChromeHeadlessNoSandbox",

### Expected Behavior

exit code is 1 and the job fails

### Steps to Reproduce

I will see if I can reproduce with the example repo, but in the meantime any guidance for where I should be debugging would be great.

### Nx Report

```shell
Node   : 20.13.0
OS     : linux-x64
npm    : 8.19.4

nx          : 19.5.1
@nrwl/tao   : 19.5.1
typescript  : 4.9.3
```

### Failure Logs

Chrome Headless 120.0.6099.224 (Linux x86_64): Executed 1095 of 1095 (2 FAILED) (17.366 secs / 14.958 secs)
TOTAL: 2 FAILED, 1093 SUCCESS
npm ERR! Lifecycle script `test` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @caplin/core@0.6.0 
npm ERR!   at location: /builds/front-end/mono/caplin/core 
 NX   Successfully ran target test for project @caplin/core
Test command exit code: 0

### Package Manager Version

pnpm -v 8.15.9

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I have confirmed that in run-exector, the exit code is 0 when returned. I haven't tracked down where that is coming from yet.

process.on('message', async (message) => {
    try {
        const statusCode = await (0, run_1.run)(process.cwd(), process.env.NX_WORKSPACE_ROOT, message.targetDescription, message.overrides, message.isVerbose, message.taskGraph);
        console.log("********", statusCode, "********");
        process.exit(statusCode);
    }
    catch (e) {
        console.error(e);
        process.exit(1);
    }
});

**Comment by FrozenPandaz** [comment]
Could you please provide a repo with exactly how you are hooking `karma` up to Nx please?
