### ISSUE TITLE
Babel config files cannot override babel-loader options

### ISSUE THREAD

**Issue by emilio-martinez** [nrwl/nx#2709]
## Expected Behavior

To be able to add a babel config file to a project, e.g., `babel.config.js`, `.babelrc.js`, etc., and have that effectively be able to override Babel options, including those set in the `babel-loader` options themselves.

## Current Behavior

Options already set within the `babel-loader` options cannot be overridden by a babel config added to a project. This seems to be because `babel-loader` reads the babel config and then applies the loader options on top of that, in that order, making it impossible to override existing plugins.

For example, if I didn't want `@babel/plugin-proposal-class-properties` to have the `loose` option set to `true`, I have no option but to override via adding a webpack config.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Add a `.babelrs.js` file to a project, i.e., `apps/my-app/.babelrc.js`
2. Try to override `@babel/plugin-proposal-class-properties` or another plugin declared within the `babel-loader` options currently. 
3. Upon running the dev server or build, notice the `babel-loader` options will persist,regardless of the plugin config set in `.babelrs.js`.

### Context

Please provide any relevant information about your setup:

```
  @nrwl/angular : Not Found
  @nrwl/cli : 9.1.2
  @nrwl/cypress : 9.1.2
  @nrwl/eslint-plugin-nx : 9.1.2
  @nrwl/express : 9.1.2
  @nrwl/jest : 9.1.2
  @nrwl/linter : 9.1.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.1.2
  @nrwl/react : 9.1.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.1.2
  @nrwl/web : 9.1.2
  @nrwl/workspace : 9.1.2
  typescript : 3.7.5
```

## Suggestion on how to solve?

I'd suggest not setting options within `babel-loader` unless they're loader-only options rather than Babel options. Instead, the config can be set via babel config files, as it would normally would on any project using Babel (including [Babel itself](https://github.com/babel/babel)!).

#### Pros

* Babel options would be fully configurable without having to jump through hoops. For example, #2119.
* This would follow similar patters Nx already uses such as Jest configs.
* Babel config can still be maintained by Nx via migrations.

#### Cons

* Applying differential loading options to babel would have to change. That `esm` param that Nx uses internally for the webpack config would have to be passed to babel in some other way.

**Comment by jaysoo** [comment]
This is now fixed because we expose `.babelrc` and `babel.config.json` for the monorepo setup. You can customize it as you see fit. :)
