### ISSUE TITLE
generatePackageJson omits dependencies with package aliases

### ISSUE THREAD

**Issue by stephenwade** [nrwl/nx#27098]
### Current Behavior

When I use the @nx/webpack:webpack executor with the `generatePackageJson` option, the resulting package.json file doesn't include any dependencies that are defined with [package aliases](https://github.com/npm/rfcs/blob/main/implemented/0001-package-aliases.md).

Here's an example of a package.json file with a package alias:

```json
{
  "dependencies": {
    "lodash": "3.10.1",
    "lodash-4": "npm:lodash@4.17.21"
  }
}
```

I have reproduced this issue with PNPM v8 and NPM. The repro repository uses NPM.

### Expected Behavior

I expect the generated package.json file to include all the dependencies used in the project, including those with package aliases.

### GitHub Repo

https://github.com/stephenwade/nx-issue-repro-scaling-carnival

### Steps to Reproduce

1. Look at package.json and app/src/main.ts. They use dependencies "lodash" and "lodash-4".
1. Run `npm ci`
1. Run `npx nx build`
1. Look at dist/app/package.json. It only has the dependency "lodash".

### Nx Report

```shell
Node   : 20.15.1
OS     : darwin-arm64
npm    : 10.8.2

nx             : 19.4.0
@nx/js         : 19.4.0
@nx/workspace  : 19.4.0
@nx/devkit     : 19.4.0
@nrwl/tao      : 19.4.0
@nx/webpack    : 19.4.0
typescript     : 5.4.5
```

### Failure Logs

No error messages are reported. It just produces an incorrect result.

### Package Manager Version

npm 10.8.2

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by phihochzwei** [comment]
Have you checked if this is something similar to https://github.com/nrwl/nx/issues/26604 ?

**Comment by stephenwade** [comment]
It isn't similar. I believe that issue happens because TypeORM doesn't have a direct dependency on mssql, so Nx can't infer that mssql belongs in the generated package.json file.

In this issue, the app code explicitly uses the dependency with a package alias, but that dependency still isn't added to the generated package.json file.

**Comment by stephenwade** [comment]
@leosvelperez Can the fix be merged, please?
