### ISSUE TITLE
nx/expo not showing QR on Windows

### ISSUE THREAD

**Issue by bjornraats** [nrwl/nx#27108]
### Current Behavior

Nx/Expo is not showing qr and other sideloading options after metro starts

### Expected Behavior

Nx/Expo should show QR and other side loading options

### Steps to Reproduce

1. Create a new expo app with latest nx version (nx 19.5.3 / expo 51.0.8) -> 
npx create-nx-workspace@latest --preset=expo --appName=test-expo-app

2. Start the new expo app -> nx start test-expo-app

### Nx Report

```shell
Node   : 20.13.1
OS     : win32-x64
npm    : 10.5.2

nx                 : 19.5.3
@nx/js             : 19.5.3
@nx/jest           : 19.5.3
@nx/linter         : 19.5.3
@nx/eslint         : 19.5.3
@nx/workspace      : 19.5.3
@nx/detox          : 19.5.3
@nx/devkit         : 19.5.3
@nx/eslint-plugin  : 19.5.3
@nx/expo           : 19.5.3
@nx/react          : 19.5.3
@nrwl/tao          : 19.5.3
@nx/web            : 19.5.3
@nx/webpack        : 19.5.3
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/expo/plugin
@nx/eslint/plugin
@nx/jest/plugin
@nx/detox/plugin
```

### Failure Logs

```shell
$ pnx start test-expo-app

> nx run test-expo-app:start

Packager is ready at http://localhost:19000
Starting project at C:\ihomer\repos\expo-test-app\app\apps\test-expo-app
Using src/app as the root directory for Expo Router.
Starting Metro Bundler
Waiting on http://localhost:19000
Logs for your project will appear below.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Also tried with Nx version 19.4.0 (which has said to have fixed this behavior according to https://github.com/nrwl/nx/issues/26529) and Expo 50.0.19 but still the same behavior...

**Comment by bjornraats** [comment]
@xiongemi any thoughts on this? :)

**Comment by xiongemi** [comment]
@bjornraats my guess would be set `NX_NATIVE_COMMAND_RUNNER=false` in your env file and run the command again to see if that would fix the issue?

**Comment by xiongemi** [comment]
i just tried it, when with executor, it works fine on my windows 11 machine:
```
"targets": {
  "start": {
      "executor": "@nx/expo:start"
  }
}
```

**Comment by xiongemi** [comment]
closing this issue for now
