### ISSUE TITLE
Unusable performance when accessing nx-dev landing page via Remote Desktop

### ISSUE THREAD

**Issue by Den-dp** [nrwl/nx#27114]
### Current Behavior

Remote desktop users (a popular use case for enterprise companies) experience significant lag and slow performance when accessing nx.dev landing page, which features an animated background.
This issue affects the overall user experience, causing delays in page interaction.

### Expected Behavior

Take into account `window.matchMedia('(prefers-reduced-motion: reduce)').matches` setting (which is `true` for Remote Desktop) while deciding to animate the background

### Steps to Reproduce

1. open nx.dev via windows RDP/windows365/etc

### Nx Report

```shell
n/a
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Den-dp** [comment]
Hey, is it already deployed?

Animations and blur on https://nx.dev are still enabled for the RDP use case

**Comment by isaacplmann** [comment]
It was deployed.  It looks like new code was added that ignores reduced-motion preference again.  Thanks for mentioning it

**Comment by isaacplmann** [comment]
I have a PR up that hopefully fixes it again.  I'd appreciate you taking a look at the preview to make sure it actually works for you.  I'm testing my work by setting `prefers-reduced-motion` to true in the Chrome devtools and looking for any animation on the page, but that won't necessarily catch any performance issues.

https://nx-dev-git-nx-dev-reduced-motion-nrwl.vercel.app/

**Comment by Den-dp** [comment]
@isaacplmann just checked and it works great, thanks! 🚀
