### ISSUE TITLE
nx process exited with code 9 (after upgrade to 18.3.2 from 16.3.2)

### ISSUE THREAD

**Issue by merlinstardust** [nrwl/nx#27119]
### Current Behavior

I get `process exited with code 9` and `--debug and --debug-brk are invalid` whenever I try to run my backend API. My frontend command has no issues.

### Expected Behavior

My backend API should run without error

### Steps to Reproduce

1.

### Nx Report

```shell
Node   : 20.16.0
OS     : linux-x64
npm    : 10.8.1

nx                 : 18.3.5
@nx/js             : 18.3.5
@nx/jest           : 18.3.5
@nx/linter         : 18.3.5
@nx/eslint         : 18.3.5
@nx/workspace      : 18.3.5
@nx/cypress        : 18.3.5
@nx/devkit         : 18.3.5
@nx/eslint-plugin  : 18.3.5
@nx/nest           : 18.3.5
@nx/node           : 18.3.5
@nx/plugin         : 18.3.5
@nx/react          : 18.3.5
@nx/storybook      : 18.3.5
@nrwl/tao          : 18.3.5
@nx/vite           : 18.3.5
@nx/web            : 18.3.5
@nx/webpack        : 18.3.5
typescript         : 5.4.5
```

### Failure Logs

```shell
Option "isolatedConfig" is deprecated: Automatic configuration of Webpack is deprecated in favor of an explicit 'webpack.config.js' file. This option will be removed in Nx 19. See https://nx.dev/recipes/webpack/webpack-config-setup.
Option "isolatedConfig" is deprecated: Automatic configuration of Webpack is deprecated in favor of an explicit 'webpack.config.js' file. This option will be removed in Nx 19. See https://nx.dev/recipes/webpack/webpack-config-setup.
asset main.js 764 KiB [emitted] [big] (name: main)
asset assets/starting-blocks.svg 9.16 KiB [emitted] [from: src/assets/starting-blocks.svg] [copied]
asset assets/.gitkeep 0 bytes [emitted] [from: src/assets/.gitkeep] [copied]
  
webpack 5.86.0 compiled successfully (7b7da86dede50db5)
/root/.nvm/versions/node/v20.16.0/bin/node: [DEP0062]: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` and `node --inspect-brk` instead.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

I'm using WSL. I encountered the same issue with node 18 and node 20. I was on 16.3.2 and upgraded to 16.10, then 17.3.2, then 18.3.2.

Regarding a reproduction, unfortunately, I can't seem to create one with the example repo and I can't link to it since it's a private repo.

At the very least, I'm hoping for more info on what exit code 9 means or how to get more info for debugging. I already tried running `npx nx run --verbose api:serve` but the output only added lines about the assets folder, which wasn't helpful

**Comment by ndcunningham** [comment]
Can you show your `project.json` the project you are running the serve command?
