### ISSUE TITLE
 NX   Failed to process project graph. Pass --verbose to see the stacktraces. ( Windows 10) 

### ISSUE THREAD

**Issue by Alemdie** [nrwl/nx#27154]
### Current Behavior

already done everything but this encounter same error when doing the 

npm run dev

unable to proceed. Encounter  NX   Failed to process project graph. Pass --verbose to see the stacktraces. problem.
![zz](https://github.com/user-attachments/assets/062d8657-77a8-4f50-a7d1-36b5d5309533)

### Expected Behavior

to start running the dev environment

### Steps to Reproduce

1.

### Nx Report

```shell
NA
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Could you please provide the logs after running with `--verbose`?

**Comment by nsmith7989** [comment]
Potentially related to #27213
