### ISSUE TITLE
--memoryLimit is ignored?

### ISSUE THREAD

**Issue by lookapanda** [nrwl/nx#2716]
## Expected Behavior

`--memoryLimit` flag should limit the memory used during building an app

## Current Behavior

`--memoryLimit` flag seems to do nothing and it defaults to 2048MB

## Failure Information (for bugs)

See below

### Steps to Reproduce

1. Build with flags `--maxWorkers=1 --memoryLimit=512`
2. Output says it used 2048MB

### Context

Ref #2581 #2305 

### Failure Logs

```
$ yarn build gql-service-users
yarn run v1.22.4
$ nx build --maxWorkers=1 --memoryLimit=512 gql-service-users
> nx run gql-service-users:build --maxWorkers=1 --memoryLimit=512
Starting type checking service...
Using 1 worker with 2048MB memory limit
```

**Comment by FrozenPandaz** [comment]
What version of Nx are you using?

This feature was introduced in [9.1.0](https://github.com/nrwl/nx/releases/tag/9.1.0)

```bash
> nx build cart --memoryLimit 512
> ng run cart:build --memoryLimit=512 
Starting type checking service...
Using 8 workers with 512MB memory limit
```

This is the result from https://github.com/nrwl/nx-examples.

**Comment by lookapanda** [comment]
The latest version. The problem is, that `@nrwl/node` is not using that option. In fact, it's inconsistent accross all packages. Some seem to use it, some don't.

See https://github.com/nrwl/nx/blob/master/packages/node/src/utils/config.ts#L68
