### ISSUE TITLE
Updating to 19.5.3 breaks e2e parallelism

### ISSUE THREAD

**Issue by Mrblackey** [nrwl/nx#27168]
### Current Behavior

After updading to v19.5.3, e2e tests run only sequentially.

### Expected Behavior

Parallel behaviour should not change when updating nx version.

### GitHub Repo

https://github.com/nrwl/nx-examples

### Steps to Reproduce

1. `nx migrate latest`
2. `yarn`
3. `nx run-many -t e2e --parallel=3`
4. e2e targets are running sequentially.

### Nx Report

```shell
Node   : 22.4.1
OS     : win32-x64
yarn   : 1.22.22

nx                 : 19.5.3
@nx/js             : 19.5.3
@nx/jest           : 19.5.3
@nx/linter         : 19.5.3
@nx/eslint         : 19.5.3
@nx/workspace      : 19.5.3
@nx/angular        : 19.5.3
@nx/cypress        : 19.5.3
@nx/devkit         : 19.5.3
@nx/eslint-plugin  : 19.5.3
@nx/react          : 19.5.3
@nrwl/tao          : 19.5.3
@nx/web            : 19.5.3
@nx/webpack        : 19.5.3
typescript         : 5.5.3
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/cypress/plugin
@nx/jest/plugin
---------------------------------------
Community plugins:
@ngrx/component-store : 18.0.1
@ngrx/effects         : 18.0.1
@ngrx/entity          : 18.0.1
@ngrx/operators       : 18.0.1
@ngrx/router-store    : 18.0.1
@ngrx/store           : 18.0.1
@ngrx/store-devtools  : 18.0.1
```

### Failure Logs

```shell
$ npx nx run-many -t e2e --parallel=3

 NX   Running target e2e for 2 projects

   →  Executing 1/2 remaining tasks...

   ⠼  nx run products-e2e:e2e
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by MaxKless** [comment]
Hey @Mrblackey! This is expected behavior since https://github.com/nrwl/nx/pull/26820. We want to make sure `e2e` targets generated by our plugins don't run in parallel because they often end up consuming more resources than they should and it's better to run them sequentially, especially in CI.

You can change this behaviour by setting the `parallelism` flag in `project.json` or in `nx.json#targetDefaults`.
Check out the blog post here for more info: https://nx.dev/blog/nx-19-5-adds-stackblitz-new-features-and-more#new-individual-targets-can-now-opt-out-of-parallelism

**Comment by Mrblackey** [comment]
> Hey @Mrblackey! This is expected behavior since #26820. We want to make sure `e2e` targets generated by our plugins don't run in parallel because they often end up consuming more resources than they should and it's better to run them sequentially, especially in CI.
> 
> You can change this behaviour by setting the `parallelism` flag in `project.json` or in `nx.json#targetDefaults`. Check out the blog post here for more info: https://nx.dev/blog/nx-19-5-adds-stackblitz-new-features-and-more#new-individual-targets-can-now-opt-out-of-parallelism

Awesome! Adding `"parallelism": true` did solve the issue, but I'm getting a warning `Property parallelism is not allowed.`. Why is that?

**Comment by MaxKless** [comment]
I think that's an issue with Nx Console. It should be fixed once https://github.com/nrwl/nx-console/pull/2221 is merged
