### ISSUE TITLE
nx release: add support for access option when publishing to npm

### ISSUE THREAD

**Issue by DuncanMcPherson** [nrwl/nx#27165]
### Current Behavior

Currently, if you don't want to pay to publish private packages, or you want to publish a public package with a scope (i.e. @nx), the `nx release` command fails with a `402 Payment Required` message.

### Expected Behavior

I'd expect there to be a flag that I can pass to change the access level to public. An alternative is having the default behavior be public when publishing to npm.

### GitHub Repo

https://github.com/duncanmcpherson/nx-tools.git

### Steps to Reproduce

1. run `nx release --projects nx-publish-npm`
2. note error message states `402`

### Nx Report

```shell
Node   : 22.4.1
OS     : win32-x64
npm    : 10.8.1

nx (global)        : 19.5.1
nx                 : 19.5.1
@nx/js             : 19.5.1
@nx/jest           : 19.5.1
@nx/linter         : 19.5.1
@nx/eslint         : 19.5.1
@nx/workspace      : 19.5.1
@nx/angular        : 19.5.1
@nx/cypress        : 19.5.1
@nx/devkit         : 19.5.1
@nx/eslint-plugin  : 19.5.1
@nx/plugin         : 19.5.1
@nrwl/tao          : 19.5.1
@nx/web            : 19.5.1
@nx/webpack        : 19.5.1
typescript         : 5.5.3
---------------------------------------
Registered Plugins:
@nxextensions/firebase-cypress
@nx/eslint/plugin
---------------------------------------
Local workspace plugins:
         @nxextensions/firebase-cypress
```

### Failure Logs

```shell
NX   Running target nx-release-publish for project nx-publish-npm:

- nx-publish-npm

With additional flags:
  --firstRelease=true

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

> nx run nx-publish-npm:nx-release-publish

npm publish error:
402 Payment Required - PUT https://registry.npmjs.org/@nxextensions%2fnx-publish-npm - You must sign up for private packages

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 NX   Running target nx-release-publish for project nx-publish-npm failed

Failed tasks:

- nx-publish-npm:nx-release-publish
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by JamesHenry** [comment]
HI @DuncanMcPherson, this is related to how npm handles things when dealing with scoped packages, we won't deviate from their default as that would be unintuitive and confusing.

They provide the `publishConfig` option in your package.json to be able to control this behaviour (again purely npm related, not nx)

You can set:

```sh
"publishConfig": {
    "access": "public"
  }
```

I don't think we need an extra flag in nx release, and it would come with the risk that it would be applied to more packages than desired given the nature of publishing multiple packages together in a monorepo

**Comment by JamesHenry** [comment]
FYI @DuncanMcPherson I did decide to add the extra flag to `nx release publish` here #27765, npm doesn't document the package.json option well enough
