### ISSUE TITLE
@nx/rspack:dev-server executor is missing some @nx/webpack:dev-server options

### ISSUE THREAD

**Issue by jorgeramirezamora** [nrwl/nx#27191]
### Current Behavior

The `@nx/rspack:dev-server` executor only supports `buildTarget`, `mode` and `port` options.

https://nx.dev/nx-api/rspack/executors/dev-server#nxrspackdevserver

### Expected Behavior

The `@nx/rspack:dev-server` executor should also support custom `allowedHosts`, `host`, `proxyConfig` and `ssl` options, as `@nx/webpack:dev-server` does.

https://rspack.dev/config/dev-server

### Steps to Reproduce

1. Have a project with `webpack` configured that has a `serve` target that implements `allowedHosts`, `host`, `proxyConfig` and `ssl`.

```
{
   ...
    "serve": {
      "executor": "@nx/webpack:dev-server",
      "options": {
        "allowedHosts": "my-app.local",
        "buildTarget": "my-app:build",
        "hmr": true,
        "host": "0.0.0.0",
        "proxyConfig": "packages/my-app/proxy.conf.json",
        "ssl": true
      },
      "configurations": {
        "development": {
          "buildTarget": "my-app:build:development"
        },
        "production": {
          "buildTarget": "my-app:build:production",
          "hmr": false
        }
      }
    }
    ...
}
```

2. Migrate to `rspack` using `nx g @nx/rspack:configuration`
3. Notice how the `@nx/rspack:dev-server` executor now only has the `build-target` option.
```
{
    ...
    "serve": {
      "executor": "@nx/rspack:dev-server",
      "options": {
        "buildTarget": "my-app:build:development"
      },
      "configurations": {
        "development": {},
        "production": {
          "buildTarget": "my-app:build:production"
        }
      }
    }
    ...
}
```

### Nx Report

```shell
Node   : 20.16.0
OS     : darwin-arm64
npm    : 10.8.1

nx                 : 19.5.1
@nx/js             : 19.5.1
@nx/jest           : 19.5.1
@nx/linter         : 19.5.1
@nx/eslint         : 19.5.1
@nx/workspace      : 19.5.1
@nx/cypress        : 19.5.1
@nx/devkit         : 19.5.1
@nx/eslint-plugin  : 19.5.1
@nx/nest           : 19.5.1
@nx/node           : 19.5.1
@nx/react          : 19.5.1
@nx/storybook      : 19.5.1
@nrwl/tao          : 19.5.1
@nx/vite           : 19.5.1
@nx/web            : 19.5.1
@nx/webpack        : 19.5.1
typescript         : 5.5.3
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
---------------------------------------
Community plugins:
@nx/rspack : 19.2.0
```

### Package Manager Version

NPM 10.8.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
The `@nx/rspack` executors require an `rspack.config` file to be present. You can configure these options in the `rspack.config` file directly. 

The `@nx/rspack` executors will not be updated to include these options as they can be found in the config file. This is in line with our new approach to configuration. See [Inferred Tasks](https://nx.dev/concepts/inferred-tasks#inferred-tasks-project-crystal) for more details.
