### ISSUE TITLE
removing old cache entries not working

### ISSUE THREAD

**Issue by SFU253** [nrwl/nx#27206]
### Current Behavior

I noticed the local cache growing bigger and investigated a little to figure out what is happening.
From what i understand after executing a task, nx randomly starts cleaning up old cache entries that are older than one week.
\
But that step fails with `ENOENT: no such file or directory` for the cache directory on my machine. I traced it down to https://github.com/nrwl/nx/blob/c400ea3002eba058d4e4ca02b3b5144ace306f15/packages/nx/src/tasks-runner/cache.ts#L37
which seems to have unnecessary `"` quotes here ``` `"${this.cachePath}"` ```. 
After removing those, the entries older than one week were removed from the local cache as expected.

### Expected Behavior

Entries older than one week are removed from the local cache when the cleanup is running. 

### Steps to Reproduce

1. Use any existing nx repo with local cache entries older then one week (or reduce the time limit to whatever fits to invalidate some cache entries)
2. Set `shouldSpawnProcess` to `true` to eliminate the randomness
https://github.com/nrwl/nx/blob/c400ea3002eba058d4e4ca02b3b5144ace306f15/packages/nx/src/tasks-runner/cache.ts#L34-L41
3. run any nx task
4. Observe that no entries in the local cache are removed

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.11.1
   OS     : darwin-arm64
   npm    : 10.2.4
   
   nx                 : 17.3.1
   @nx/js             : 17.3.1
   @nx/jest           : 17.3.1
   @nx/linter         : 17.3.1
   @nx/eslint         : 17.3.1
   @nx/workspace      : 17.3.1
   @nx/angular        : 17.3.1
   @nx/cypress        : 17.3.1
   @nx/devkit         : 17.3.1
   @nx/eslint-plugin  : 17.3.1
   @nrwl/tao          : 17.3.1
   @nx/web            : 17.3.1
   @nx/webpack        : 17.3.1
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   @ngneat/aim    : 2.0.0
   @taiga-ui/cdk  : 3.64.0
   @taiga-ui/core : 3.64.0
```

### Failure Logs

```shell
Error: ENOENT: no such file or directory, scandir '"PATH_TO_PROJECT/.nx/cache"/terminalOutputs'
    at readdirSync (node:fs:1438:3)
    at terminalOutputs (PATH_TO_PROJECT/node_modules/nx/src/tasks-runner/remove-old-cache-records.js:12:37)
    at Object.<anonymous> (PATH_TO_PROJECT/node_modules/nx/src/tasks-runner/remove-old-cache-records.js:8:11)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '"PATH_TO_PROJECT/.nx/cache"/terminalOutputs'
}
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I gathered the error by logging it here
https://github.com/nrwl/nx/blob/c400ea3002eba058d4e4ca02b3b5144ace306f15/packages/nx/src/tasks-runner/remove-old-cache-records.ts#L13-L19

**Comment by AgentEnder** [comment]
Awesome issue report, thanks @SFU253 - you've done a lot of the work already, would you be interested in putting the PR up for this?
