### ISSUE TITLE
nx commands: --plain is invalid for commands other than nx affected:(libs|apps)

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#2720]
## Current Behavior

Commands other than `nx affected:apps` and `nx affected:libs` have a `--plain` option which does nothing.

## Expected Behavior

Commands other than `nx affected:apps` and `nx affected:libs` do not have a `--plain` option.

<details><summary>Original Description</summary>
# nx commands: --plain doesn't work

# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

there is no difference between `--plain`  and no `--plain`

## Current Behavior

![image](https://user-images.githubusercontent.com/1223799/77542467-800a3300-6ea6-11ea-93a4-850f8201854e.png)

### Context
```
 @nrwl/angular : Not Found
  @nrwl/cli : 9.1.2
  @nrwl/cypress : 9.1.2
  @nrwl/eslint-plugin-nx : 9.1.2
  @nrwl/express : Not Found
  @nrwl/jest : 9.1.2
  @nrwl/linter : 9.1.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.1.2
  @nrwl/react : 9.1.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.1.2
  @nrwl/web : 9.1.2
  @nrwl/workspace : 9.1.2
  typescript : 3.8.3
```
</details>

**Comment by FrozenPandaz** [comment]
Sorry for the confusion, `--plain` is only for text output commands (`nx affected:libs` and `nx affected:apps`).

We should remove the option from other commands.

**Comment by Hotell** [comment]
awesome, thx @FrozenPandaz !
