### ISSUE TITLE
Playwright Executor: Unable to specify list of projects

### ISSUE THREAD

**Issue by nmcivor501** [nrwl/nx#27211]
### Current Behavior

When Specifying a list of projects in a project's `project.json` and trying to run the `@nx/playwright:playwright` executor, the projects are not recognized by `nx` as valid, despite being read in somewhat correctly. 

### Expected Behavior

- Read in the *list* of projects from both the `project` array inside `project.json`
- Read in a subset of projects specified in the CLI. e.g. `npx nx e2e project1 -- --project=chromium --project=firefox --project=webkit` (or any other syntax) 

### Steps to Reproduce

1. Define all your projects (chromium, firefox, webkit in this case) inside `project1/playwright.config.ts`
2. Set a list of projects inside the `project` array in `project.json` for "project1":
```
{
  "name": "project1",
    "e2e": {
      "executor": "@nx/playwright:playwright",
      "outputs": ["{workspaceRoot}/dist/.playwright/project1"],
      "options": {
        "config": "project1/playwright.config.ts",
        "project": [
          "chromium",
          "firefox",
          "webkit",
        ],
      },
    },
  },
  "tags": []
}

```
3. Run the target for that project: `$ nx npx e2e project1`
 - See the "failure logs" section for the Error message
 
 AND/OR
 
 1. Try to pass all the projects defined in your `playwright.config.ts` as commandline arguments (using the syntax suggested [here](https://github.com/nrwl/nx/issues/21151#issuecomment-2117591478) best I can tell: `$ npx nx e2e project1 -- --project=chromium --project=firefox --project=webkit`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.20.3
   OS     : darwin-arm64
   npm    : 10.8.2

   nx                 : 17.0.0
   @nx/js             : 17.0.0
   @nx/jest           : 17.0.0
   @nx/linter         : 17.0.0
   @nx/eslint         : 17.0.0
   @nx/workspace      : 17.0.0
   @nx/cypress        : 17.0.0
   @nx/devkit         : 17.0.0
   @nx/eslint-plugin  : 17.0.0
   @nx/playwright     : 17.0.0
   @nx/plugin         : 17.0.0
   @nx/react          : 17.0.0
   @nx/rollup         : 17.0.0
   @nrwl/tao          : 17.0.0
   @nx/web            : 17.0.0
   @nx/webpack        : 17.0.0
   typescript         : 5.0.4
   ---------------------------------------
   Local workspace plugins:
         @local-plugin/plugin1
```

### Failure Logs

```shell
$ npx nx e2e project1

> nx run project1:e2e

 >  NX   Ensuring Playwright is installed.
   use --skipInstall to skip installation.
Error: Project(s) "chromium,firefox,webkit" not found. Available projects: "setup", "teardown", "chromium", "firefox", "webkit"
Error: Project(s) "chromium,firefox,webkit" not found. Available projects: "setup", "teardown", "chromium", "firefox", "webkit"
    at filterProjects (.../node_modules/playwright/lib/runner/projectUtils.js:67:11)
    at writeLastRunInfo (.../node_modules/playwright/lib/runner/runner.js:144:54)
    at Runner.runAllTests (.../node_modules/playwright/lib/runner/runner.js:82:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runTests (.../node_modules/playwright/lib/program.js:207:85)
    at t.<anonymous> (.../node_modules/playwright/lib/program.js:54:7)
```

### Package Manager Version

$ yarn --version1.22.22

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This particular issue was fixed by https://github.com/nrwl/nx/pull/20850 and released in Nx v17.0.4. So, to address the issue, I recommend that you update them to version 17.3.1 or later. Another change in 17.0.4 removed the default projects from the `nxE2EPreset` exported by `@nx/playwright/preset`. Due to an oversight, that version didn't include a migration to configure the default projects in the projects `playwright.config.ts` files. The migration was provided in Nx 17.3.1.

I'm closing this since the issue was already addressed in a later version.
