### ISSUE TITLE
Nx Reset and other commands that require project graph fail when daemon experiences an error

### ISSUE THREAD

**Issue by DuncanMcPherson** [nrwl/nx#27220]
### Current Behavior

Currently, if I write a plugin (and leave it in a state where the graph can't process) or manually create a project.json file, the daemon hangs and leaves it's process running. The process that the daemon runs on seems to create a lock on it's log file. Running `nx daemon --stop` or `nx reset` seem to have no effect on that lock.

### Expected Behavior

running `nx daemon --stop` or `nx reset` should force close the affected daemon process.

### GitHub Repo

https://github.com/nrwl/nx-examples

### Steps to Reproduce

1. Run `nx graph`
2. hit `ctrl + c`
3. run `nx reset` (should fail to reset)
4. run `nx graph` (should fail due to EPERM: on daemon.log)

### Nx Report

```shell
Node   : 20.11.1
OS     : win32-x64
npm    : 10.8.2

nx (global)        : 19.5.1
nx                 : 19.5.3
@nx/js             : 19.5.3
@nx/jest           : 19.5.3
@nx/linter         : 19.5.3
@nx/eslint         : 19.5.3
@nx/workspace      : 19.5.3
@nx/cypress        : 19.5.3
@nx/devkit         : 19.5.3
@nx/eslint-plugin  : 19.5.3
@nx/plugin         : 19.5.3
@nrwl/tao          : 19.5.3
@nx/web            : 19.5.3
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
---------------------------------------
Local workspace plugins:
         @nxextensions/firebase-cypress
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by MaxKless** [comment]
Hello! Thanks for the report :) This is an issue with plugin isolation. Please update to the latest patch `19.5.7` where this is fixed. 
If you run into any other issues, please let me know :)
