### ISSUE TITLE
add support for typescript-eslint@8

### ISSUE THREAD

**Issue by robertIsaac** [nrwl/nx#27241]
### Current Behavior

when I run `npm i @typescript-eslint/eslint-plugin@latest @typescript-eslint/parser@latest @typescript-eslint/utils@latest` it throw
```
npm error Could not resolve dependency:
npm error peer @typescript-eslint/parser@"^6.13.2 || ^7.0.0" from @nx/eslint-plugin@19.5.3
npm error node_modules/@nx/eslint-plugin
npm error   dev @nx/eslint-plugin@"19.5.3" from the root project
npm error   @nx/eslint-plugin@"19.5.3" from @nrwl/eslint-plugin-nx@19.5.3
npm error   node_modules/@nrwl/eslint-plugin-nx
npm error     @nrwl/eslint-plugin-nx@"19.5.3" from @nx/eslint-plugin@19.5.
```
even if I used `-f`, the next time I do `npm i` or `npm ci` it will fail

### Expected Behavior

npm i to execute normally
new projects to come with `typescript-eslint` version 8

### Steps to Reproduce

1. in any nx project run `npm i @typescript-eslint/eslint-plugin@latest @typescript-eslint/parser@latest @typescript-eslint/utils@latest`

### Nx Report

```shell
Node   : 20.14.0
OS     : win32-x64
npm    : 10.8.2

nx                 : 19.5.3
@nx/js             : 19.5.3
@nx/jest           : 19.5.3
@nx/linter         : 19.5.3
@nx/eslint         : 19.5.3
@nx/workspace      : 19.5.3
@nx/angular        : 19.5.3
@nx/devkit         : 19.5.3
@nx/eslint-plugin  : 19.5.3
@nrwl/tao          : 19.5.3
@nx/web            : 19.5.3
@nx/webpack        : 19.5.3
typescript         : 5.5.4
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

nx should produce new projects using the flat configuration as well

I'm welling to help with a PR, but I think this needs a broader discussions about how exactly should it look
there are many breaking changes especially with flat configuration and I'm not sure what is expected
if you want me to start something and to figure it out overtime I don't mind it and I can start working on it this week but I don't want to open a PR that might not be accepted

**Comment by JamesHenry** [comment]
I appreciate the enthusiasm @robertIsaac, I only cut the release for typescript-eslint v8 a couple of hours ago. Please have a little patience, I will work on this very soon

**Comment by JamesHenry** [comment]
This should land in Nx 19.7 by the end of the month, you can follow along with https://github.com/nrwl/nx/issues/27451 which I have created to avoid the multiple duplicates we currently have open.

The WIP PR is getting very close, so stay tuned. It's not easy because of a large differences in ESLint v9 support across ESLint plugins that Nx sets up for you.
