### ISSUE TITLE
Expo fonts unuable to load: [TypeError: Cannot read property 'uri' of null]

### ISSUE THREAD

**Issue by sc-mitton** [nrwl/nx#27243]
### Current Behavior

I have tried to add custom fonts through expo-fonts and the app is unable to load them from the assets folder. 

### Expected Behavior

The fonts should load and the fontsLoaded variable should be true and the fontError variable should be null. Additionally, the custom fonts should be dislaying.

### GitHub Repo

https://github.com/sc-mitton/example

### Steps to Reproduce

1. npx create-nx-workspace example --packageManager pnpm
   > react
   > expo
   > mobile
   > skip
   > skip
2. cd example
3. pnpm i
4. nx run mobile:install expo-font
5. nx run mobile:install @react-native/assets-registry
6. Add expo-font to app.json plugins
       [
        "expo-font",
        {
          "fonts": [
            "./assets/fonts/SourceSans3Bold.ttf",
            "./assets/fonts/SourceSans3Medium.ttf",
            "./assets/fonts/SourceSans3Regular.ttf",
            "./assets/fonts/SourceSans3SemiBold.ttf"
          ]
        }
      ]
7. nx run mobile:prebuild
8. nx run mobile:ios-run

### Nx Report

```shell
Node           : 20.14.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.2.0

nx (global)        : 19.2.2
nx                 : 19.5.4
@nx/js             : 19.5.4
@nx/jest           : 19.5.4
@nx/eslint         : 19.5.4
@nx/workspace      : 19.5.4
@nx/detox          : 19.5.4
@nx/eslint-plugin  : 19.5.4
@nx/expo           : 19.5.4
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/expo/plugin
@nx/eslint/plugin
@nx/jest/plugin
@nx/detox/plugin
```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Logs for the font variables:

 LOG  fontError: null
 LOG  fontsLoaded: false
 LOG  fontError: [TypeError: Cannot read property 'uri' of null]
 LOG  fontsLoaded: false

**Comment by sc-mitton** [comment]
The fonts work fine in a normal app, so I believe the issue has something to do with how nx is working.

**Comment by sc-mitton** [comment]
Using bun instead of pnpm fixed the problem

**Comment by sc-mitton** [comment]
Using bun instead of pnpm fixed the problem

**Comment by LouisLec** [comment]
I had the same error message, (expo 51 and pnpm), I found in my `pnpm-lock.yaml` several versions of metro installed (79 and 80). 79 was installed as a peer dependency of `@react-native-clipboard/clipboard` I think, so I replaced it with `expo-clipboard` and now it's working.

Loading assets seems to require the adequate metro/expo combo...
