### ISSUE TITLE
unable to install vitest 2 with @nx/vite

### ISSUE THREAD

**Issue by pavel-shermayster-sage** [nrwl/nx#27259]
### Current Behavior

vitest 2 is not listed as peer dependency in @nx/vite packange.json

### Expected Behavior

vitest should be listed in peer dependency

### Steps to Reproduce

1. create project with @nx/vite and vitest 2 
2. `npm i` will fail

### Nx Report

```shell
no report
```

### Operating System

- [X] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by connorjs** [comment]
Vitest 2 migration guide for reference: <https://vitest.dev/guide/migration.html>

Assuming `@nx/vite` does not any deprecated options (copied below), then I think all migration work lies on users, which means that `@nx/vite` can add the peer dependency seamlessly.

Any concerns about just adding the peer dependency?

---

> **Deprecated Options Removed**
>
> Some deprecated options were removed:
> 
> * `vitest typecheck` command - use `vitest --typecheck` instead
> * `VITEST_JUNIT_CLASSNAME` and `VITEST_JUNIT_SUITE_NAME` env variables (use reporter options instead)
> * check for `c8` coverage (use coverage-v8 instead)
> * export of `SnapshotEnvironment` from `vitest` - import it from `vitest/snapshot` instead
`SpyInstance` is removed in favor of `MockInstance`

**Comment by connorjs** [comment]
I threw together a PR that adds the peer dependency. Hopefully this suffices, but let me know here (or on PR) if more testing is needed.
