### ISSUE TITLE
core: `dependsOn` local project overrides regression (introduced between nx 19.4 - 19.5)

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#27258]
### Current Behavior

`dependsOn` overrides no longer work

following configuration worked with nx 19.3:

<img width="952" alt="image" src="https://github.com/user-attachments/assets/044589a6-95cc-4048-9d69-e1317c087f13">

with nx 19.5 it doesn't work anymore:

![image](https://github.com/user-attachments/assets/d64b2ddd-0b0f-4815-8192-0d379a9b3524)

### Expected Behavior

`dependsOn` overrides should work as before (merge of inferred target with manually specified bug) 

**Workaround:**

 if full target definition is manually provided it works as before

![image](https://github.com/user-attachments/assets/d39af56d-d246-4e85-97c8-73965dac83e1)

### GitHub Repo

https://github.com/microsoft/fluentui/pull/32136

### Steps to Reproduce

1. see failing pipeline

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.15.0
OS             : darwin-arm64
Native Target  : aarch64-macos
yarn           : 1.23.34

nx                 : 19.5.4
@nx/js             : 19.5.4
@nx/jest           : 19.5.4
@nx/linter         : 19.5.4
@nx/eslint         : 19.5.4
@nx/workspace      : 19.5.4
@nx/devkit         : 19.5.4
@nx/eslint-plugin  : 19.5.4
@nx/node           : 19.5.4
@nx/plugin         : 19.5.4
@nrwl/tao          : 19.5.4
typescript         : 5.0.4
---------------------------------------
Local workspace plugins:
         @fluentui/workspace-plugin
```

### Package Manager Version

yarn v1

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
@Hotell Can you provide more detail as to what I can clone and try to run from that PR that exhibits the problem? I tried to repro in a fresh run and did not see an issue.

**Comment by Hotell** [comment]
1. this is the PR I linked in issue description - https://github.com/microsoft/fluentui/pull/32136 - please check it out
2. all the test-perf are failing because targets are not executed as before ( nx 19.3 ) https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=355023&view=logs&j=4a446d69-1b32-5c30-7305-e0c1f94959f8
3. local repro:
   - `yarn install` 
   - `yarn nx reset`
   - `yarn nx run `yarn nx run perf-test:test-perf` -> nothing will be run. **this is the reported bug**
     - perf-test app overrides `bundle` target to not run dependency `build` targets ( global nx config ), but it won't run anything, so `test-perf` wont have any assets ready to be run agains perf test 
     - <img width="878" alt="image" src="https://github.com/user-attachments/assets/df5cfc86-029f-47fb-a269-bf23b6004f29">

lemme know if you need anything else. ty

**Comment by AgentEnder** [comment]
Ok, got a minimal repro locally. Thanks for the info @Hotell 👋

**Comment by Hotell** [comment]
This team rocks! Thx a ton folks for quick fix. 🍻
