### ISSUE TITLE
Module Federation with SSR & React runs into Module Not Found

### ISSUE THREAD

**Issue by jc1993** [nrwl/nx#27250]
### Current Behavior

Hello! 👋 
From following the exact steps here - https://nx.dev/recipes/react/module-federation-with-ssr
I am getting the following error below when going to localhost:4200/product (full page load, not SPA).  The page loads via CSR, but SSR seems to fail behind the scenes with a 500 error.  Can't quite tell what I'm doing wrong:

`Error: Cannot find module 'product@http://localhost:4201/server/remoteEntry.js'
Require stack:
- /Users/.../workspace/sample-project/dist/apps/store/server/server.js
while loading "./Module" from 23
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Function.Module._load (node:internal/modules/cjs/loader:983:27)
    at Function.Module._load (/Users/.../workspace/sample-project/node_modules/@nx/js/src/executors/node/node-with-require-overrides.js:18:31)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/.../workspace/sample-project/dist/apps/store/server/webpack:/store/external commonjs-module "product@http:/localhost:4201/server/remoteEntry.js":1:1)
    at __webpack_require__ (/Users/.../workspace/sample-project/dist/apps/store/server/webpack:/store/webpack/bootstrap:22:1)
    at handleFunction (/Users/.../workspace/sample-project/dist/apps/store/server/webpack:/store/node_modules/@module-federation/webpack-bundler-runtime/dist/index.cjs.js:69:1)
    at /Users/.../workspace/sample-project/dist/apps/store/server/webpack:/store/node_modules/@module-federation/webpack-bundler-runtime/dist/index.cjs.js:118:1
    at Array.forEach (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/.../workspace/sample-project/dist/apps/store/server/server.js'
  ]
}`

This is what I inputted to the workspace creator
`✔ Where would you like to create your workspace? · ...
✔ Which stack do you want to use? · react
✔ What framework would you like to use? · none
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · ...
✔ Which bundler would you like to use? · webpack
✔ Test runner to use for end to end (E2E) tests · playwright
✔ Default stylesheet format · styled-components
✔ Which CI provider would you like to use? · skip
✔ Would you like remote caching to make your build faster? · yes
✔ Will you be using GitHub as your git hosting provider? · Yes`

### Expected Behavior

The module should be resolvable and SSR should reflect that

### Steps to Reproduce

Exact steps detailed here - https://nx.dev/recipes/react/module-federation-with-ssr

### Nx Report

```shell
Node           : 21.7.3
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.5.0

nx                 : 19.5.4
@nx/js             : 19.5.4
@nx/jest           : 19.5.4
@nx/linter         : 19.5.4
@nx/eslint         : 19.5.4
@nx/workspace      : 19.5.4
@nx/cypress        : 19.5.4
@nx/devkit         : 19.5.4
@nx/eslint-plugin  : 19.5.4
@nx/playwright     : 19.5.4
@nx/react          : 19.5.4
@nrwl/tao          : 19.5.4
@nx/web            : 19.5.4
@nx/webpack        : 19.5.4
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/playwright/plugin
@nx/jest/plugin
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Hey @jc1993 !

This is a new but known issue. I'm in contact with the Module Federation team to help determine what exactly is incorrect and how we can go about resolving it. 

I'll update when I know more.

**Comment by Coly010** [comment]
PR on our side: https://github.com/nrwl/nx/pull/27492
PR on the module-federation side: https://github.com/module-federation/core/pull/2860
