### ISSUE TITLE
Cannot find project '$NX_PROJECT_NAME'

### ISSUE THREAD

**Issue by artuska** [nrwl/nx#27287]
### Current Behavior

Windows:

```
nx watch --all -- npx nx build \$NX_PROJECT_NAME
```

Nothing in documentation works on Windows — https://nx.dev/recipes/running-tasks/workspace-watching

### Expected Behavior

$NX_PROJECT_NAME becomes a project name

### Steps to Reproduce

1. just use any on the Workspace Watching commands

### Nx Report

```shell
Node           : 20.11.1
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.2.4

nx (global)        : 19.5.6
nx                 : 19.5.6
lerna              : 8.1.7
@nx/js             : 19.5.6
@nx/linter         : 19.5.6
@nx/eslint         : 19.5.6
@nx/workspace      : 19.5.6
@nx/cypress        : 19.5.6
@nx/devkit         : 19.5.6
@nx/eslint-plugin  : 19.5.6
@nx/playwright     : 19.5.6
@nx/react          : 19.5.6
@nrwl/tao          : 19.5.6
@nx/vite           : 19.5.6
@nx/web            : 19.5.6
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
@nx/playwright/plugin
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
We'll update the documentation to provide guidance on Windows.

In the meantime, the command you're looking for on Windows looks like this:

```sh
nx watch --all -- npx nx build %NX_PROJECT_NAME%
```
