### ISSUE TITLE
React reverse proxy configuration is not working and throwing errors on start

### ISSUE THREAD

**Issue by ryanmccormick** [nrwl/nx#27321]
### Current Behavior

When trying to configure a reverse proxy I get an error that describes proxyConfig as an Unknown option:
```bash
> nx-broken-proxy-demo@0.0.0 start
> nx run demo-frontend:serve


> nx run demo-frontend:serve

> webpack-cli serve --proxyConfig=packages/demo-frontend/proxy.conf.json --node-env=development

[webpack-cli] Error: Unknown option '--proxyConfig=packages/demo-frontend/proxy.conf.json'
[webpack-cli] Run 'webpack --help' to see available commands and options
Warning: command "webpack-cli serve --proxyConfig=packages/demo-frontend/proxy.conf.json --node-env=development" exited with non-zero status code
```

### Expected Behavior

I expect the serve target to run and reverse proxy my requests to my backend service.

### GitHub Repo

https://github.com/ryanmccormick/nx-broken-proxy-demo

### Steps to Reproduce

1. Generate a new workspace 
2. Add a frontend project
3. Add a backend project using the steps described in [Set Up Application Proxies](https://nx.dev/recipes/node/application-proxies#set-up-application-proxies)
4. Find out that the proxy.conf.json file is not created
5. Manually add a proxy config file `proxy.conf.json` at the root of your frontend project:
```json
{
  "/api": {
    "target": "http://localhost:3000",
    "secure": "false"
  }
}
```
6. Add the proxyConfig to your frontend project's `project.json` file:
```json
{
"...otherproperties":"",
"targets": {
    "serve": {
      "options": {
        "proxyConfig": "packages/demo-frontend/proxy.conf.json"
      }
    }
  }
}
```

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.16.0
OS             : linux-x64
Native Target  : x86_64-linux
npm            : 10.8.1

nx (global)        : 19.5.6
nx                 : 19.5.6
@nx/js             : 19.5.6
@nx/jest           : 19.5.6
@nx/linter         : 19.5.6
@nx/eslint         : 19.5.6
@nx/workspace      : 19.5.6
@nx/devkit         : 19.5.6
@nx/eslint-plugin  : 19.5.6
@nx/nest           : 19.5.6
@nx/node           : 19.5.6
@nx/react          : 19.5.6
@nx/rollup         : 19.5.6
@nrwl/tao          : 19.5.6
@nx/web            : 19.5.6
@nx/webpack        : 19.5.6
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin
@nx/rollup/plugin
```

### Failure Logs

```shell
> nx-broken-proxy-demo@0.0.0 start
> nx run demo-frontend:serve


> nx run demo-frontend:serve

> webpack-cli serve --proxyConfig=packages/demo-frontend/proxy.conf.json --node-env=development

[webpack-cli] Error: Unknown option '--proxyConfig=packages/demo-frontend/proxy.conf.json'
[webpack-cli] Run 'webpack --help' to see available commands and options
Warning: command "webpack-cli serve --proxyConfig=packages/demo-frontend/proxy.conf.json --node-env=development" exited with non-zero status code
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
The `proxyConfig` option is something specific to the legacy setup using the [`@nx/webpack:webpack` executor](https://nx.dev/nx-api/webpack/executors/webpack#nxwebpackwebpack).

You should use the proxy feature from Webpack itself: https://webpack.js.org/configuration/dev-server/#devserverproxy

See example: https://github.com/jaysoo/issue-27321
---
I'll update the generator and docs to reflect the new setup as well.
