### ISSUE TITLE
Build Failing for React App with one JS Library

### ISSUE THREAD

**Issue by daninus14** [nrwl/nx#27339]
### Current Behavior

I can run the app by doing `nx serve myapp` however, when building `nx build myapp` it fails with the following error:

```
Could not resolve entry module "libs/mylib/src/index.ts".
```

I recently migrated from Nx 16.x to latest. Unclear if this is the reason though, since I just added another app and library in the same mono repo workspace just to test it with the same results. Unless the base workspace config files did not migrate properly.

This error **only** happens when the library in question is using **javascript** and `.jsx` files. If a typescript only library is generated, everything works.

### Expected Behavior

For the build to succeed.

### Steps to Reproduce

1. Create React Mono Repo with an app
2. Add Library
3. Import component from library to the app
4. Build project

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.2.0
OS             : darwin-x64
Native Target  : x86_64-macos
yarn           : 4.4.0

nx (global)        : 19.3.0
nx                 : 19.5.6
@nx/js             : 19.5.6
@nx/jest           : 19.5.6
@nx/linter         : 19.5.6
@nx/eslint         : 19.5.6
@nx/workspace      : 19.5.6
@nx/cypress        : 19.5.6
@nx/devkit         : 19.5.6
@nx/eslint-plugin  : 19.5.6
@nx/playwright     : 19.5.6
@nx/react          : 19.5.6
@nrwl/tao          : 19.5.6
@nx/vite           : 19.5.6
@nx/web            : 19.5.6
typescript         : 5.5.4
```

### Failure Logs

```shell
nx build scratch

   ✖  1/1 dependent project tasks failed (see below)

———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


> nx run Explore:build:production

vite v5.3.5 building for production...
✓ 0 modules transformed.
x Build failed in 1.08s

 NX   Could not resolve entry module "libs/explore/src/index.ts".

Pass --verbose to see the stacktrace.


———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target build for project scratch and 1 task(s) they depend on (12s)

   ✖  1/1 failed
   ✔  0/1 succeeded [0 read from cache]
```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
It should work as demonstrated here: https://github.com/jaysoo/27339

I would double-check your tsconfig for the library to ensure that `.jsx` files are included. If you can provide a repro for this that would help in us debugging.

**Comment by daninus14** [comment]
@jaysoo Thanks for replying!

I figured out the issue by generating another app, confirming it would build after importing, and comparing the tsconfig files as you suggested.

In the `tsconfig.app.json` file, VS Code always shows errors because it says the object is missing the following properties:

```javascript
    "declaration": true,
    "composite": true
```

I had added them based on the vscode suggestions.

That's what caused the project to break. Once I removed it, it built without erros, however, VSCode is complaining that the file has erros.

I think it's weird that VS Code is basically showing an error and "fixing" it breaks the build but not the serving of the app.

Do you have any insights on this? Is this is a problem with nx that could be fixed or is it all vs code related?
