### ISSUE TITLE
NX Remix (Vite) Plugin creates vitest.config.ts instead of vite.config.ts

### ISSUE THREAD

**Issue by kosiakMD** [nrwl/nx#27330]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

[Remix with Nx](https://nx.dev/recipes/react/remix)

### Additional context or description

In the documentation mentioned above there is list of created files, and there says that Remix plugin should create `vite.config.ts`.
But it doesn't.
Instead of this file, it creates `vitest.config.ts`, but there is no mention of it in this documentation.

There is no documentation on how to create `vite.config.ts` manually and how to bind it with NX Remix runners.

**Comment by kosiakMD** [comment]
@isaacplmann can you help me please?
last point I posted was `There is no documentation on how to create vite.config.ts manually and how to bind it with NX Remix runners.`
so I still can't find in documentation how to add vite.config.ts for Remix app created by NX
Thanks

**Comment by isaacplmann** [comment]
You should be able to just make a `vite.config.ts` file and `@nx/vite` will infer build tasks from it
