### ISSUE TITLE
esbuild version conflict in NX Angular project when running in production mode

### ISSUE THREAD

**Issue by joh-klein** [nrwl/nx#27333]
### Current Behavior

There seems to be a version conflict issue with esbuild while trying to run the project in a production environment. When I try to execute `NODE_ENV=production npm ci` in a Docker container, I get `Error: Expected "0.23.0" but got "0.21.5"`, referring to esbuild.

### Expected Behavior

The project should run successfully after executing `NODE_ENV=production npm ci`.

### GitHub Repo

https://github.com/joh-klein/nx-examples

### Steps to Reproduce

1. Create a new NX workspace using `npx create-nx-workspace@latest test1`.
1. Generate a new buildable Angular library using `npx nx generate @nrwl/angular:lib --buildable`.
1. Try to install the prod dependencies using `NODE_ENV=production npm ci`.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.16.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.8.1

nx                 : 19.5.7
@nx/js             : 19.5.7
@nx/jest           : 19.5.7
@nx/linter         : 19.5.7
@nx/eslint         : 19.5.7
@nx/workspace      : 19.5.7
@nx/angular        : 19.5.7
@nx/cypress        : 19.5.7
@nx/devkit         : 19.5.7
@nx/eslint-plugin  : 19.5.7
@nx/react          : 19.5.7
@nrwl/tao          : 19.5.7
@nx/web            : 19.5.7
@nx/webpack        : 19.5.7
typescript         : 5.5.3
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/cypress/plugin
@nx/jest/plugin
---------------------------------------
Community plugins:
@ngrx/component-store : 18.0.2
@ngrx/effects         : 18.0.2
@ngrx/entity          : 18.0.2
@ngrx/operators       : 18.0.2
@ngrx/router-store    : 18.0.2
@ngrx/store           : 18.0.2
@ngrx/store-devtools  : 18.0.2
```

### Failure Logs

```shell
npm error code 1
npm error path /Users/[redacted]/nx-examples/node_modules/ng-packagr/node_modules/esbuild
npm error command failed
npm error command sh -c node install.js
npm error /Users/[redacted]/nx-examples/node_modules/ng-packagr/node_modules/esbuild/install.js:134
npm error     throw new Error(`Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)}`);
npm error           ^
npm error
npm error Error: Expected "0.23.0" but got "0.21.5"
npm error     at validateBinaryVersion (/Users/[redacted]/nx-examples/node_modules/ng-packagr/node_modules/esbuild/install.js:134:11)
npm error     at /Users/[redacted]/nx-examples/node_modules/ng-packagr/node_modules/esbuild/install.js:284:5
npm error
npm error Node.js v20.16.0
npm error A complete log of this run can be found in: /Users/[redacted]/.npm/_logs/2024-08-08T09_48_55_180Z-debug-0.log
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

A temporary workaround is to add this override to the package.json

```
  "overrides": {
    "ng-packagr": {
      "esbuild": "0.21.5"
    }
  }
  ```

**Comment by joh-klein** [comment]
Well, the problem only occurs in an nx wokspace! (I tried it with an angular only repository) Because `@nx/angular` is in `dependencies` and has the required peerDependency `@angular-devkit/build-angular` which itself has the optional peerDependency `ng-packagr`. And when I only want to install the prod dependencies the npm "magic" happens …

**Comment by leosvelperez** [comment]
Do you need `@nx/angular` as a production dependency? Are you using any of the runtime helpers from it? If not, you can move it to `devDependencies`.

**Comment by joh-klein** [comment]
I never thought to move it to devDependecies since it is the nx default to put it into dependencies. I just tried that solution and it works!

Maybe it would be a good idea to put it into devDependencies by default? Or split `@nx/angular` into two packages for dev and prod dependencies?

**Comment by leosvelperez** [comment]
I'm glad it worked.

I agree we should consider generating projects with it in `devDependencies`. The `@nx/angular` runtime helpers are a small subset of what the plugin offers and are not used by everyone. We'll look into doing so.

Moving the runtime helpers out of `@nx/angular` is something we've long discussed but we haven't yet decided to do so.

**Comment by joh-klein** [comment]
Thank you for your help!

**Comment by joh-klein** [comment]
Sorry, I should probably leave this open, right?
