### ISSUE TITLE
Wrong project graph when using target defaults

### ISSUE THREAD

**Issue by Elyahou** [nrwl/nx#27346]
### Current Behavior

I noticed that with last NX versions, the tasks graphs in circleCI was wrong, it included some circular dependencies that were not existing in the monorepo. This issue is present only when running without Daemon (like in CI or with NX_DAEMON=false).

Here a repository that reproduce this issue: https://github.com/Elyahou/project-graph-bug

```
$ npx nx build lib1 --verbose

> nx run lib1:prepare

> echo prepare lib1


> nx run lib3:prepare

> echo prepare lib3

prepare lib3

> nx run lib2:prepare

> echo prepare lib2

prepare lib2
prepare lib1

> nx run lib3:build

> echo build lib3

build lib3

> nx run lib2:build

> echo build lib2

build lib2

> nx run lib1:build

> echo build lib1

build lib1
```

```
$ NX_DAEMON=false npx nx build lib1 --verbose

> nx run lib1:prepare

> echo prepare lib1

prepare lib1

> nx run lib3:build

> echo build lib3

build lib3

> nx run lib2:build

> echo build lib2

build lib2

> nx run lib1:build

> echo build lib1

build lib1
```

With `NX_DAEMON=false` only lib1 run prepare task...

### Expected Behavior

The graph should be correct with `NX_DAEMON=false`

### GitHub Repo

https://github.com/Elyahou/project-graph-bug

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 22.2.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.8.1

nx                 : 19.5.7
@nx/js             : 19.5.7
@nx/linter         : 19.5.7
@nx/eslint         : 19.5.7
@nx/workspace      : 19.5.7
@nx/devkit         : 19.5.7
@nx/eslint-plugin  : 19.5.7
@nrwl/tao          : 19.5.7
typescript         : 5.5.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by bridzius** [comment]
We are experiencing this as well (was just in the middle of creating a repro for this - https://github.com/bridzius/mutable-nx)

Traced this down to https://github.com/nrwl/nx/blob/master/packages/nx/src/project-graph/utils/project-configuration-utils.ts#L791, which assigns a ref of the `targetDefault` and then mutates it for subsequent assignments. Changing it to use `JSON.parse(JSON.stringify(` seems to alleviate the issue, though is probably not the solution.

**Comment by Elyahou** [comment]
@bridzius Exact, I just open [a Pull Request](https://github.com/nrwl/nx/pull/27348) to fix it
