### ISSUE TITLE
@nx/expo:export outputDir vs output-dir

### ISSUE THREAD

**Issue by ChrisSargent** [nrwl/nx#27369]
### Current Behavior

Docs here: https://nx.dev/nx-api/expo/executors/export#outputdir, say:

> Relative to workspace root, the directory to export the static files to. Default: dist

We are using the @nx/expo plugin

1. Without using `outputDir` the build is output relative to the `projectRoot`, not `workspaceRoot`
2. Adding `outputDir` results in an error, `unknown or unexpected option: --outputDir`
3. Need to use `output-dir` as the option

### Expected Behavior

As per the docs:

> `outputDir` - Relative to workspace root, the directory to export the static files to. Default: dist

### Steps to Reproduce

1. Create an Nx expo project
2. Try running an export
3. Try adding a `outputDir` option

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 18.20.4
OS             : darwin-arm64
Native Target  : aarch64-macos
yarn           : 4.4.0

nx                 : 19.5.6
@nx/js             : 19.5.6
@nx/jest           : 19.5.6
@nx/linter         : 19.5.6
@nx/eslint         : 19.5.6
@nx/workspace      : 19.5.6
@nx/devkit         : 19.5.6
@nx/eslint-plugin  : 19.5.6
@nx/expo           : 19.5.6
@nx/node           : 19.5.6
@nx/playwright     : 19.5.6
@nx/react          : 19.5.6
@nrwl/tao          : 19.5.6
@nx/web            : 19.5.6
@nx/webpack        : 19.5.6
typescript         : 5.3.3
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/expo/plugin
```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

our task config:

```json
    "export": {
      "dependsOn": ["prebuild"],
      "inputs": ["production", "^production", "configForNx"],
      "outputs": ["{options.output-dir}"],
      "options": {
        "platform": "web",
        "output-dir": "dist/{projectRoot}"
      }
    },
```

**Comment by ChrisSargent** [comment]
Actually, even this doesn't work, it still outputs to the `projectRoot/dist` folder, even when updated to `"output-dir": "{workspaceRoot}/dist/{projectRoot}"

**Comment by xiongemi** [comment]
this is not a defect. there are 2 ways to export

if in your project.json, you got an export target like:
```
  "targets": {
    "export": {
      "executor": "@nx/expo:export",
      "outputDir": "dist/{projectRoot}"
    }
  }
```

this export output directory will be relative to workspace root.

however, if you don't have the export target defined, it will be equivalent to using the expo cli https://docs.expo.dev/more/expo-cli/#exporting

so you run export command: `nx export <your app> --output-dir dist`, this is just using the expo cli command: `expo export --output-dir dist`, this dist is relative to your project path.

**Comment by ChrisSargent** [comment]
I think the difference is we're using the expo plugin - so in our project.json we're not specifying `"executor": "@nx/expo:export",`, i.e. we're using the "inferred tasks" way but trying to make that task depend on another task.

(if we do add the executor explicitly, it does work as expected)

Is it possible to continue using the inferred tasks whilst also defining a `dependsOn` field?
