### ISSUE TITLE
Failed nx run mobile:build-android Command

### ISSUE THREAD

**Issue by hosseint79** [nrwl/nx#27367]
### Current Behavior

when I try to run this command `npx nx run mobile:build-android `
I get error

### Expected Behavior

Successfully APK file created

### Steps to Reproduce

1. create new app
2. add 
"build-android": {
  "executor": "@nx/react-native:build-android",
  "outputs": [
    "{projectRoot}/build/outputs/bundle",
    "{projectRoot}/build/outputs/apk"
  ],
  "options": {
    "mode": "release"
  }
}
3. npx nx run mobile:build-android,

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 22.5.1
OS     : darwin-arm64
npm    : 10.8.2

nx                 : 19.4.1
@nx/js             : 19.4.1
@nx/jest           : 19.4.1
@nx/linter         : 19.4.1
@nx/eslint         : 19.4.1
@nx/workspace      : 19.4.1
@nx/devkit         : 19.4.1
@nx/eslint-plugin  : 19.4.1
@nx/next           : 19.4.1
@nx/playwright     : 19.4.1
@nx/react          : 19.4.1
@nx/react-native   : 19.4.1
@nrwl/tao          : 19.4.1
@nx/web            : 19.4.1
@nx/webpack        : 19.4.1
typescript         : 5.0.4
---------------------------------------
Registered Plugins:
@nx/next/plugin
@nx/jest/plugin
@nx/eslint/plugin
@nx/react-native/plugin
@nx/webpack/plugin
@nx/playwright/plugin
```

### Failure Logs

```shell
> Task :app:createBundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:createBundleReleaseJsAndAssets'.
> Couldn't determine Hermesc location. Please set `react.hermesCommand` to the path of the hermesc binary file. node_modules/react-native/sdks/hermesc/%OS-BIN%/hermesc
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by alexmyshchyshyn** [comment]
@hosseint79 How did you solve it? Could you please help me with that?

**Comment by hosseint79** [comment]
Certainly! I’d be happy to help

1: My app was located at:
`/apps/mobile`

2: I opened the build.gradle file located at:
`/apps/mobile/android/app/build.gradle`

3: I uncommented the hermesCommand line and replaced it with:
`hermesCommand = "../../node_modules/react-native/sdks/hermesc/%OS-BIN%/hermesc"`

If your app isn't in /apps, you might need to adjust the hermesCommand path

**Comment by alexmyshchyshyn** [comment]
Thanks a lot @hosseint79. Found it some time ago too 🥇

**Comment by akshgods** [comment]
getting this error:

error: unknown option '--signing-config'

**Comment by xiongemi** [comment]
to solve this issue, need to set hermesCommand in your file <your app>/android/app/build.gradle:
change the line `// hermesCommand = "$rootDir/my-custom-hermesc/bin/hermesc"`
to something like `hermesCommand = "../../node_modules/react-native/sdks/hermesc/%OS-BIN%/hermesc"`
depends on your app's directory offset from root, if your project root is `apps/<app name>`, the line is `hermesCommand = "../../node_modules/react-native/sdks/hermesc/%OS-BIN%/hermesc"`; if the project root is just `<app name>`, then the line is `hermesCommand = "../node_modules/react-native/sdks/hermesc/%OS-BIN%/hermesc"`
