### ISSUE TITLE
 NX   Missing Platform Dependency

### ISSUE THREAD

**Issue by dpanda-caisoft** [nrwl/nx#27396]
### Current Behavior

node version is 20.12
npm version is 10.5.0
nx serve home command gives error.

 NX   Missing Platform Dependency

The Nx CLI could not find or load the native binary for your supported platform (darwin-arm64).
This likely means that optional dependencies were not installed correctly, or your system is missing some system dependencies.
For more information please see 

<img width="1564" alt="Screenshot 2024-08-13 at 10 58 44" src="https://github.com/user-attachments/assets/ffd0dc9a-da05-4861-b2d6-a379a4e2f966">
 https://nx.dev/troubleshooting/troubleshoot-nx-install-issues

### Expected Behavior

it was working before , it used to run 

### GitHub Repo

private repo

### Steps to Reproduce

command nx serve home

### Nx Report

```shell
NX   Missing Platform Dependency

The Nx CLI could not find or load the native binary for your supported platform (darwin-arm64).
This likely means that optional dependencies were not installed correctly, or your system is missing some system dependencies.
For more information please see https://nx.dev/troubleshooting/troubleshoot-nx-install-issues
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Could you try with the `latest` version of nx please?

**Comment by dpanda-caisoft** [comment]
Hi @FrozenPandaz  ,Thanks for for your help . It worked .

**Comment by FrozenPandaz** [comment]
You're welcome!
