### ISSUE TITLE
nx report shows @nx and @nrwl together

### ISSUE THREAD

**Issue by mhp-borisbojic** [nrwl/nx#27398]
### Current Behavior

When doing an `nx report`, it wells me that e.g. `@nrwl/workspace` should match my installed version of NX, which is odd:

1. I don't have specified `@nrwl/workspace` in my package.json
2. According to the NX docs, `@nrwl/workspace` was renamed to `@nx/workspace` anyway

### Expected Behavior

Don't see any reference or report in regards to `@nrwl`

### Steps to Reproduce

1. Use yarn 4.x (berry)
2. Remove yarn.lock and node_modules
3. Yarn install
4. NX report

### Nx Report

```shell
Node   : 20.15.0
OS     : darwin-arm64
yarn   : 4.4.0

nx (global)        : 19.3.2
nx                 : 19.4.4
@nx/js             : 19.4.4
@nx/jest           : 19.4.4
@nx/linter         : 19.4.4
@nx/eslint         : 19.4.4
@nx/workspace      : 19.4.4
@nrwl/workspace    : 19.3.0
@nx/angular        : 19.4.4
@nx/devkit         : 19.4.4
@nrwl/devkit       : 19.3.0
@nx/eslint-plugin  : 19.4.4
@nx/nest           : 19.4.4
@nx/node           : 19.4.4
@nx/playwright     : 19.4.4
@nrwl/tao          : 19.3.0
@nx/web            : 19.4.4
@nx/webpack        : 19.4.4
typescript         : 5.5.4
---------------------------------------
Community plugins:
@auth0/auth0-angular       : 2.2.3
@ng-bootstrap/ng-bootstrap : 17.0.0
@ngxs/store                : 18.1.1
@nx-extend/terraform       : 6.0.5
ng-mocks                   : 14.13.0
nx-stylelint               : 17.1.5
---------------------------------------
The following packages should match the installed version of nx
  - @nrwl/workspace@19.3.0
  - @nrwl/devkit@19.3.0
  - @nrwl/tao@19.3.0

To fix this, run `nx migrate nx@19.4.4`
```

### Package Manager Version

yarn 4.0.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Those packages are installed as dependencies of their `@nx/` counterparts so that we maintain the NPM stats. They should not be misaligned so the warning is informing you of something you should still resolve. I believe another issue mentioned that `@nx-extend/terraform` is causing the misalignment. Please reach out to them at https://github.com/TriPSs/nx-extend and see if they can resolve the issue.
