### ISSUE TITLE
metro web builds cache key collision 

### ISSUE THREAD

**Issue by leggomuhgreggo** [nrwl/nx#27392]
### Current Behavior

After upgrading to Expo SDK 51, and adpting expo web projects from webpack to metro web, we noticed that sometimes one project's build would have environment variables from a different project in the monorepo.

The issue was intermittent and only happened in pipelines with multiple web builds.

We determined that — if the `metro.config.js` file is **identical** between two or more projects — then **it uses the same cache key**. And when multiple projects are being built — after the first project is completed — subsequent projects will resolve the first project's compiled/cached app config (etc) from metro cache — because they have the same cache-key.

> [!NOTE]
> This is also true for `start` commands, and (presumably) other build related commands. 

_EDIT: updated to improve clarity_

### Expected Behavior

The builds should be isolated and config from one build should not leak into subsequent builds. 

### GitHub Repo

https://github.com/leggomuhgreggo/metro-web-cache-issue-2024-08-09

### Steps to Reproduce

Follow instructions in README.

### Nx Report

```shell
Node           : 18.20.2
OS             : darwin-arm64
Native Target  : aarch64-macos
yarn           : 1.22.22

nx                 : 19.5.6
@nx/js             : 19.5.6
@nx/jest           : 19.5.6
@nx/linter         : 19.5.6
@nx/eslint         : 19.5.6
@nx/workspace      : 19.5.6
@nx/cypress        : 19.5.6
@nx/detox          : 19.5.6
@nx/devkit         : 19.5.6
@nx/esbuild        : 19.5.6
@nx/eslint-plugin  : 19.5.6
@nx/expo           : 19.5.6
@nx/nest           : 19.5.6
@nx/node           : 19.5.6
@nx/playwright     : 19.5.6
@nx/plugin         : 19.5.6
@nx/react          : 19.5.6
@nx/storybook      : 19.5.6
@nrwl/tao          : 19.5.6
@nx/vite           : 19.5.6
@nx/web            : 19.5.6
@nx/webpack        : 19.5.6
typescript         : 5.5.3
---------------------------------------
Community plugins:
@nx-go/nx-go           : 2.7.0
@nx-tools/nx-container : 5.1.0
@nxkit/playwright      : 3.0.2
@nxrs/cargo            : 0.3.4
---------------------------------------
Local workspace plugins:
         @workspace/sg-codepipeline-plugin
         @workspace/sg-codedeploy-plugin
         @workspace/sg-typeorm-plugin
         @workspace/sg-rover-plugin
         @workspace/sg-expo-plugin
         @workspace/repo
         @workspace/sg-vite-plugin
         @sg-monorepo/workspace-plugin
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I've also opened up an issue on the expo repo here:
https://github.com/expo/expo/issues/30930

**Comment by xiongemi** [comment]
the other thing you can do is in project.json, add targets:
```
  "targets": {
    "export": {
      "options": {
        "args": ["--clear"]
      }
    }
  }
```

so it will always clear the expo cache when you can export command.

**Comment by leggomuhgreggo** [comment]
>this seems to be something to do with expo cache. the easist way to fix is just run the command with --clear flag to clear the expo cache when export. for example:

Yes, this is in line with our findings:

>_We determined that if the metro.config.js file is identical between two projects, then **it uses the same cache key**. And when multiple projects are built, later projects will used the cached app config of the first project to be cached._

I think it'd be useful to add something to the metro.config.js — maybe part of the `withNxMetro` function — to distinguish the configs, just to avoid this issue

You can see an example of what Im talking about [here](https://github.com/leggomuhgreggo/metro-web-cache-issue-2024-08-09/commit/cad28e485f611cfdc0e6ec752aa98315a3a14c91)

**Comment by xiongemi** [comment]
> Thanks for taking a look at this!
> 
> > this seems to be something to do with expo cache. the easist way to fix is just run the command with --clear flag to clear the expo cache when export. for example:
> 
> Yes, this is in line with our findings here:
> 
> > _We determined that — if the `metro.config.js` file is **identical** between two or more projects — then **it uses the same cache key**. And when multiple projects are being built — after the first project is completed — subsequent projects will resolve the first project's compiled/cached app config (etc) from metro cache — because they have the same cache-key._
> 
> _EDIT: updated to improve clarity_
> 
> I think it'd be useful to add something to the `metro.config.js` — maybe part of the `withNxMetro` function — to distinguish the configs — so that when they're hashed, the corresponding cache-key is differentiated.
> 
> You can see an example of what Im talking about [here](https://github.com/leggomuhgreggo/metro-web-cache-issue-2024-08-09/commit/cad28e485f611cfdc0e6ec752aa98315a3a14c91), which leverages the [`cacheVersion` option](https://metrobundler.dev/docs/configuration/#cacheversion)
> 
> <img alt="image" width="500" src="https://private-user-images.githubusercontent.com/2213636/361726302-d68f976f-f787-40d1-b6ea-7b706cff1673.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NzIwMjYsIm5iZiI6MTcyNDg3MTcyNiwicGF0aCI6Ii8yMjEzNjM2LzM2MTcyNjMwMi1kNjhmOTc2Zi1mNzg3LTQwZDEtYjZlYS03YjcwNmNmZjE2NzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMTkwMjA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWNjM2E1ODg3MGE4YjAzZmY5MGNhMDc3MDhkY2YyN2MwNjMwNTY3ZmNkNDNjMmQxZjRlMTA1ZWRkNmQzMTI4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CXhszdZFUJmS3euGr41IgRRojBTRkiKfAxwO3hUu8fU">

this solves the metro cache key between 2 different apps. however, when I change the .env file or app.config.js, it does not refresh the output.

**Comment by leggomuhgreggo** [comment]
>however, when I change the .env file or app.config.js, it does not refresh the output.

Nice find! Just confirmed on my end too.

Oddly passing `--clear` for one of the projects, seems to bust the cache for all projects.

I'm guessing the expo app config is being compiled separately from other app files — because changes to `App.tsx` make it into the build, where changes to `app.config.js` do not.

(I tried looking at the expo/metro source code to see how that was working, but no luck, so far)

I can imagine why they might want to cache it separately, but yeah would seem like an oversight that modifying the app config file wouldn't break its cache. 🤷 

I think the "sticky app config cache" issues cloud probably be considered separately from the "cross-project cache contagion" issue. If its agreeable to y'all, I'd vote in favor of shipping the `cacheVersion` fix and following up on the remaining items.
