### ISSUE TITLE
DataPersistence access to store on router navigation

### ISSUE THREAD

**Issue by Affiction** [nrwl/nx#2741]
Doc: [Data Fetching On Router Navigation](https://nx.dev/angular/guides/misc-data-persistence#data-fetching-on-router-navigation "Data Fetching On Router Navigation")

```javascript
    this.s.navigation(TodoComponent, {
        // Via second parameter we can access to the store
        run: (a: ActivatedRouteSnapshot, state: TodosState) => {
            return ...
      }));
    },
```

- [*] I am running the latest version
- [*] I checked the documentation (nx.dev) and found no answer
- [*] I checked to make sure that this issue has not already been filed
- [*] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

When we navigate to "TodoComponent" we should access to the store via the second parameter.

## Current Behavior

When we navigate to "TodoComponent" second parameter return **undefined**.

### Steps to Reproduce

I created a small [repo](https://github.com/Affiction/navigate-data-persistence). 
When we navigate to AppComponent we [log](https://github.com/Affiction/navigate-data-persistence/blob/8552fe7c3e65e365e0057532df4055952e493fe3/apps/navigate-data-persistence/src/app/%2Bstate/users.effects.ts#L20-L21). For methods **fetch** everything is fine.

1. install dependencies;
2. npm run start;
3. check devtools console;

## Other

On the first look [here](https://github.com/nrwl/nx/blob/6516176b65f8efae6ea9f60f65fd45a4bdf30aad/packages/angular/src/runtime/nx/data-persistence.ts#L416) and [here](https://github.com/nrwl/nx/blob/6516176b65f8efae6ea9f60f65fd45a4bdf30aad/packages/angular/src/runtime/nx/data-persistence.ts#L114-L117) was provide store and everything should works as expected.

**Comment by FrozenPandaz** [comment]
You are correct, that is the right solution. When using the operators you should provide the store by using `withLatestFrom`. We will update our docs to use the operators.

**Comment by marcellobarile** [comment]
what is the actual solution, sorry? I'm a bit lost. Thanks.

**Comment by Affiction** [comment]
> what is the actual solution, sorry? I'm a bit lost. Thanks.

```javascript
    this.s.navigation(TodoComponent, {
        // Via second parameter we can access to the store
        run: (a: ActivatedRouteSnapshot, state: TodosState) => {
           return of(a).pipe(
              withLatestFrom('TODO: add another stream with data here'),
              tap(([activatedRouteSnapshot, withLatestFromData]) => {
                console.log(activatedRouteSnapshot);
                console.log(withLatestFromData);
              })
      }));
    },
```
