### ISSUE TITLE
Dependency Conflict with @nxkit/style-dictionary@5.0.0 and style-dictionary@4.x

### ISSUE THREAD

**Issue by codebysandeep** [nrwl/nx#27416]
### Current Behavior

When attempting to use `@nxkit/style-dictionary@5.0.0` with `style-dictionary@4.0.1`, the Nx monorepo project encounters a dependency conflict. The peer dependency specified in `@nxkit/style-dictionary@5.0.0` requires `style-dictionary@^3.7.1`, which is incompatible with `style-dictionary@^4.0.1`.

**Environment:**

- Nx Version: 19.5.6
- @nxkit/style-dictionary Version: 5.0.0
- style-dictionary Version: 4.0.1
- Node Version: Latest (as used in the official Node Docker image node:latest)
- Package Manager: npm (used in CI pipeline with GitLab)

**Styledictionary version 4 details**
https://styledictionary.com/version-4/migration/

### Expected Behavior

The packages should install without conflicts, allowing the use of `style-dictionary@4.x` with `@nxkit/style-dictionary@5.0.0`.

### Steps to Reproduce

**Steps to Reproduce:**

- Set up an Nx monorepo project.
- Install `@nxkit/style-dictionary@5.0.0` and `style-dictionary@4.0.1` in the devDependencies.
- Attempt to run npm install.

### Nx Report

```shell
Node           : 22.6.0
OS             : darwin-x64
Native Target  : x86_64-macos
npm            : 10.8.2

nx (global)    : 19.3.0
nx             : 19.5.6
@nx/js         : 19.5.6
@nx/workspace  : 19.5.6
@nx/devkit     : 19.5.6
@nrwl/tao      : 19.5.6
typescript     : 5.5.4
---------------------------------------
Community plugins:
@nxkit/style-dictionary : 5.0.0
```

### Failure Logs

```shell
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error 
npm error While resolving: @nxkit/style-dictionary@5.0.0
npm error Found: style-dictionary@4.0.1
npm error node_modules/style-dictionary
npm error   dev style-dictionary@"^4.0.1" from the root project
npm error 
npm error Could not resolve dependency:
npm error peer style-dictionary@"^3.7.1" from @nxkit/style-dictionary@5.0.0
npm error node_modules/@nxkit/style-dictionary
npm error   dev @nxkit/style-dictionary@"^5.0.0" from the root project
npm error 
npm error Conflicting peer dependency: style-dictionary@3.9.2
npm error node_modules/style-dictionary
npm error   peer style-dictionary@"^3.7.1" from @nxkit/style-dictionary@5.0.0
npm error   node_modules/@nxkit/style-dictionary
```

### Package Manager Version

10.8.2

### Operating System

- [X] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

The issue occurs during the CI pipeline execution in a GitLab environment.

**Suggested Resolution:**
Consider updating the `@nxkit/style-dictionary` package to support `style-dictionary@4.x` or provide guidance on how to resolve this conflict without downgrading style-dictionary.

**Comment by Coly010** [comment]
Hey @codebysandeep !

`NxKit` is not owned or maintained by us or this repo. You should open this issue on their repo: https://github.com/nxkit/nxkit
