### ISSUE TITLE
Build with generating a `package.json` is missing a GitHub package

### ISSUE THREAD

**Issue by daniel-schwartz-k** [nrwl/nx#27423]
### Current Behavior

I am building my app with `--generatePackageJson` but the generated `package.json`  is missing the [uWebSockets.js GitHub package](https://github.com/uNetworking/uWebSockets.js)  which I import and use in the app.

Note: happens with `@nx/esbuild:esbuild` and `@nx/webpack:webpack` executors.

### Expected Behavior

Expecting to build the app with `--generatePackageJson` and having the the generated `package.json` include the uWebSockets.js GitHub package.

### Simple GitHub Repo

https://github.com/daniel-schwartz-k/nx-issue-uweb

### Steps to Reproduce

1. Init a simple NX 19 project
    ```sh
    npx create-nx-workspace@19.5.7
    ```
3. Select Node project
4. Select Monorepo project
5. Select Koa
6. Install [uWebSockets.js GitHub package](https://github.com/uNetworking/uWebSockets.js),
    ```sh
    npm i "uWebSockets.js"@"github:uNetworking/uWebSockets.js#v20.47.0"
    ```
7. Use `uWebSockets` in the app

    ```ts
    import { App, SSLApp } from 'uWebSockets.js'
    console.log("Using in the app:",  App({}), SSLApp({}));
    ```
8. Build the app and generate the package json:
    ```sh
    npx nx run org:build --generatePackageJson --skip-nx-cache
    ```

9. Observe missing `uWebSockets.js` is missing from the generated `/dist/apps/package.json`
    ```json
    {
      "name": "org",
      "version": "0.0.1",
      "dependencies": {
        "koa": "2.14.2"
      },
      "main": "./main.js",
      "type": "commonjs"
    }
    ```

### Nx Report

```shell
Node           : 20.15.0
OS             : linux-x64
Native Target  : x86_64-linux
npm            : 10.7.0

nx                 : 19.5.7
@nx/js             : 19.5.7
@nx/jest           : 19.5.7
@nx/linter         : 19.5.7
@nx/eslint         : 19.5.7
@nx/workspace      : 19.5.7
@nx/devkit         : 19.5.7
@nx/esbuild        : 19.5.7
@nx/eslint-plugin  : 19.5.7
@nx/node           : 19.5.7
@nrwl/tao          : 19.5.7
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/jest/plugin
```

### Operating System

- [ ] macOS
- [X] Linux - Using WSL2 (Windows Sub System for Linux).
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
Looks like lockfile parsing is not accounting for the right version when installing from git remote. We'll fix it.
