### ISSUE TITLE
Compiler option for react library generator not adding SWC plugin import when specified

### ISSUE THREAD

**Issue by pongells** [nrwl/nx#27433]
### Current Behavior

When generating a library with SWC compiler, the option is ignored if the test runner is vitest.

This happens because of https://github.com/nrwl/nx/blob/master/packages/react/src/generators/library/library.ts#L176

### Expected Behavior

`import react from "@vitejs/plugin-react-swc";`

should be added to `vite.config.ts` instead of 

`import react from "@vitejs/plugin-react";`

### Steps to Reproduce

1.`nx g @nx/react:library --verbose --name swclib --bundler none --linter none --unit-test-runner vitest --compiler swc`
2. in `vite.config.ts` the import is `import react from "@vitejs/plugin-react";` instead of `import react from "@vitejs/plugin-react-swc";`

### Nx Report

```shell
Node           : 20.11.0
OS             : darwin-arm64
Native Target  : aarch64-macos
yarn           : 4.4.0

nx                 : 19.5.7
@nx/js             : 19.5.7
@nx/jest           : 19.5.7
@nx/linter         : 19.5.7
@nx/eslint         : 19.5.7
@nx/workspace      : 19.5.7
@nx/devkit         : 19.5.7
@nx/eslint-plugin  : 19.5.7
@nx/playwright     : 19.5.7
@nx/plugin         : 19.5.7
@nx/react          : 19.5.7
@nx/rollup         : 19.5.7
@nrwl/tao          : 19.5.7
@nx/vite           : 19.5.7
@nx/web            : 19.5.7
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
-------------------
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by NgDaddy** [comment]
Hi, I've pushed a small fix for it. I am not 100% sure this is how it should get fixed but I feel it this way

**Comment by ndcunningham** [comment]
Closing as this has been fixed
