### ISSUE TITLE
@nx/webpack doesn't add an inferred build task for all the documented webpack config file types

### ISSUE THREAD

**Issue by glitch452** [nrwl/nx#27438]
### Current Behavior

When adding a `webpack.config.cts` or `webpack.config.mts` file to the root of a project, there is no inferred `build` task. The other webpack config file names in the [documentation](https://nx.dev/nx-api/webpack#how-nxwebpack-infers-tasks) are working normally. 

### Expected Behavior

When adding a `webpack.config.cts` or `webpack.config.mts` file to the root of a project, there should be an inferred `build` task. All of the [documented](https://nx.dev/nx-api/webpack#how-nxwebpack-infers-tasks) configuration file names should work to create an inferred `build` task. 

### Steps to Reproduce

1. Install @nx/webpack
2. Add the @nx/webpack/plugin to the workspace plugins list
3. Create a webpack config file at the root of a project in the workspace with one of the broken file names
4. Run `nx show project <projectName> --json | jq .targets.build`, which returns null since the build task is not being inferred

### Nx Report

```shell
Node           : 20.15.1
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.8.2

nx (global)        : 19.5.3
nx                 : 19.5.7
@nx/js             : 19.5.7
@nx/jest           : 19.5.7
@nx/linter         : 19.5.7
@nx/eslint         : 19.5.7
@nx/workspace      : 19.5.7
@nx/cypress        : 19.5.7
@nx/devkit         : 19.5.7
@nx/eslint-plugin  : 19.5.7
@nx/nest           : 19.5.7
@nx/next           : 19.5.7
@nx/node           : 19.5.7
@nx/react          : 19.5.7
@nx/storybook      : 19.5.7
@nrwl/tao          : 19.5.7
@nx/vite           : 19.5.7
@nx/web            : 19.5.7
@nx/webpack        : 19.5.7
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/next/plugin
@nxlv/python
@nx/cypress/plugin
@nx/eslint/plugin
@nx/storybook/plugin
@nx/webpack/plugin
---------------------------------------
Community plugins:
@nxlv/python : 19.0.2
```

### Package Manager Version

npm v10.8.2

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by glitch452** [comment]
Looks like it's this line: https://github.com/nrwl/nx/blob/f7eab14f6b782b10f28c9d41551fc9bb1855babb/packages/webpack/src/plugins/plugin.ts#L56

**Comment by jaysoo** [comment]
Hi @glitch452 

The problem here is that Webpack CLI itself will not load `mts` and `cts` files. I'll update the docs to match what the plugin actually supports.

You can use `webpack.config.ts`, and just make sure your `package.json` has the right type if you to use CJS vs ESM format.
