### ISSUE TITLE
The 'implicitDependencies' option in mf does not work.

### ISSUE THREAD

**Issue by EnochGao** [nrwl/nx#27448]
### Current Behavior

The 'implicitDependencies' option in mf does not work.
![image](https://github.com/user-attachments/assets/baa6b069-8e2a-4dd7-957e-716136179e54)
![image](https://github.com/user-attachments/assets/1acddb3e-7b8e-4339-9892-48984db52cc2)

### Expected Behavior

work fine

### GitHub Repo

https://github.com/EnochGao/nx-test/tree/mf

### Steps to Reproduce

npx nx build host check the dist folder

### Nx Report

```shell
Node           : 20.14.0
OS             : linux-x64
Native Target  : x86_64-linux
npm            : 10.7.0

nx                 : 19.5.7
@nx/js             : 19.5.7
@nx/jest           : 19.5.7
@nx/linter         : 19.5.7
@nx/eslint         : 19.5.7
@nx/workspace      : 19.5.7
@nx/angular        : 19.5.7
@nx/devkit         : 19.5.7
@nx/eslint-plugin  : 19.5.7
@nrwl/tao          : 19.5.7
@nx/web            : 19.5.7
@nx/webpack        : 19.5.7
typescript         : 5.5.3
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
As a workaround for now, add `dependsOn["^build"]` to the `targetDefaults.@nx/angular:webpack-browser` entry

**Comment by EnochGao** [comment]
@Coly010 I upgraded to version 19.16.1, but it doesn't seem to be working

**Comment by Coly010** [comment]
@EnochGao Can you give any additional information at all? It's very difficult to help solve issues when comments are vague

**Comment by EnochGao** [comment]
> @EnochGao Can you give any additional information at all? It's very difficult to help solve issues when comments are vague

Thank you for your reply. I upgraded the current [branch](https://github.com/EnochGao/nx-test/tree/mf) and ran npx nx build host. The child project was not built.

**Comment by EnochGao** [comment]
Upgrading to version 19.7.0-beta.1 also does not take effect

**Comment by EnochGao** [comment]
@leosvelperez

**Comment by EnochGao** [comment]
@Coly010
