### ISSUE TITLE
Create new workspaces with ESLint v9 and typescript-eslint v8

### ISSUE THREAD

**Issue by JamesHenry** [nrwl/nx#27451]
### Current Behavior

New workspaces are created with ESLint v8 (and its eslintrc config format), and typescript-eslint v7, which is now the previous major version.

### Expected Behavior

New workspaces are created with ESLint v9 (and its default flat config format) and typescript-eslint v8.

Existing workspaces should not be forcibly migrated, but they have access to the conversion generator if they choose to use it.

### Steps to Reproduce

`npx create-nx-workspace` with any stack.

### Nx Report

```shell
All
```

### Operating System

- [X] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

This issue was created to be able to close duplicates and focus attention and discussion in one place.

**Comment by AlexanderShabalinMaersk** [comment]
is there any news about this?

**Comment by cmcnicholas** [comment]
Hi guys, what's the situation with this? I can't find any external documentation but this looks to be merged, how would one go about migrating v8 to v9 in an existing nx repo?

**Comment by robertIsaac** [comment]
> Hi guys, what's the situation with this? I can't find any external documentation but this looks to be merged, how would one go about migrating v8 to v9 in an existing nx repo?

it's part of nx 19.8, which in beta now

**Comment by kbrilla** [comment]
this PR silently added `plugin:@angular-eslint/template/accessibility` which is not mentioned anywhere and makes Christmas Tree out of old projects when switched to flat config manually. New way of configuring eslint should not add/remove any rules compared to existing config.

**Comment by kbrilla** [comment]
I also found out that new 

> > Hi, @JamesHenry , thx for this PR, I have but one problem after migrating to new configuration. This PR silently added `plugin:@angular-eslint/template/accessibility` which is not mentioned anywhere and makes Christmas Tree out of old projects when switched to flat config manually. New way of configuring eslint should not add/remove any rules compared to existing config.
> 
> I like your expression of "makes Christmas Tree"
> 
> as a workaround you can turn off the rules here is the full list https://github.com/angular-eslint/angular-eslint/blob/159658fcd5174728533877ff36dc091644a44944/packages/angular-eslint/src/configs/template-accessibility.ts#L4 so to turn them off you do
> 
> ```
>       '@angular-eslint/template/alt-text': 'off',
>       '@angular-eslint/template/click-events-have-key-events': 'off',
>       '@angular-eslint/template/elements-content': 'off',
>       '@angular-eslint/template/interactive-supports-focus': 'off',
>       '@angular-eslint/template/label-has-associated-control': 'off',
>       '@angular-eslint/template/mouse-events-have-key-events': 'off',
>       '@angular-eslint/template/no-autofocus': 'off',
>       '@angular-eslint/template/no-distracting-elements': 'off',
>       '@angular-eslint/template/role-has-required-aria': 'off',
>       '@angular-eslint/template/table-scope': 'off',
>       '@angular-eslint/template/valid-aria': 'off',
> ```
> 
> or even better turn off the ones doing the noise in the project
> 
> me personally I'm not strongly with or against adding it, but I think there should be an option to optout for example to have `flat-configs/angular-template-no-accessibility` but the default to be `flat-configs/angular-template`

"makes Christmas Tree" means that it start to light up just like Christmas lights on Christmas tree, never though that it might be just a local saying. 

On subject though: yeah, I have nothing against adding accessibility rules to config - I was just confused and tries to figure out where those rules comes from. Maybe adding that to description of changes, would save me from some digging. As for workaround, I already fixed most issues, but thanks anyway :)

**Comment by CyanoFresh** [comment]
why don't anyone say about missing support by eslint-plugin-import for eslint@9? Workspace is created, react app generated, but I can't run `npm i` anymore

**Comment by pumano** [comment]
@CyanoFresh today they (eslint-plugin-import) released support version 2.31

**Comment by pumano** [comment]
@JamesHenry eslint 9 has --quiet param, that not run warn rules. When I pass that param via:

`nx run-many --exclude=lib1,lib2 --target=lint --quiet` 

that param not passed to eslint, just filter warnings instead for eslint 9 should not run rules with warnings totally.

**Comment by CyanoFresh** [comment]
@pumano thanks, now it's working fine

**Comment by JamesHenry** [comment]
Hi Folks, please open fresh issues with full context and steps to reproduce. The work represented by this issue has been completed and so the issue has been closed. Whilst we always try our best on every effort we ship, it doesn't mean that the work is guaranteed to be perfect, and any remaining imperfections are what we will work on addressing as soon as possible and as soon as we have clear steps on how to reproduce them. It is not possible to keep track of comments on closed issues, and they are overwhelming likely to not provide steps to reproduce, unlike a fresh issue.

Many thanks!
