### ISSUE TITLE
nx couldnt run storybook task when tsconfigPaths function imported from vite-tsconfig-paths

### ISSUE THREAD

**Issue by AndrewMakarevich** [nrwl/nx#27473]
### Current Behavior

I have a storybook config within my packages folder: 
```ts
import type {StorybookConfig} from '@storybook/web-components-vite';
import {mergeConfig} from 'vite';
import {nxViteTsPaths} from '@nx/vite/plugins/nx-tsconfig-paths.plugin';
import tsconfigPaths from 'vite-tsconfig-paths';

const config: StorybookConfig = {
  stories: ['*.stories.@(js|jsx|ts|tsx|mdx)'],
  framework: {
    name: '@storybook/web-components-vite',
    options: {},
  },
  addons: ['@storybook/addon-essentials'],

  viteFinal: async (config) =>
    mergeConfig(config, {
      plugins: [nxViteTsPaths({}), tsconfigPaths()],
    }),
};

export default config;
```
When i tried to run "nx run --verbose {NAME_OF_THE_PACKAGE}:storybook" next error appears:

An error occurred while processing files for the @nx/storybook/plugin plugin.
    - packages/{NAME_OF_THE_PACKAGE}/.storybook/main.ts: Cannot access 'exports' before initialization
      ReferenceError: Cannot access 'exports' before initialization

As soon as I delete the tsconfigPaths import from the stroybook main.ts everything start working as expected.

### Expected Behavior

nx run --verbose {NAME_OF_THE_PACKAGE}:storybook command should execute as expected even with imported tsconfigPaths

### Steps to Reproduce

1.

### Nx Report

```shell
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  An error occurred while processing files for the @nx/storybook/plugin plugin.
    - packages/{NAME_OF_THE_PACKAGE}/.storybook/main.ts: exports is not defined in ES module scope
      ReferenceError: exports is not defined in ES module scope
```

### Package Manager Version

9.7.0

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Hey @AndrewMakarevich !

You've configured the storybook/main.ts file incorrectly. The `nxViteTsPaths()` plugin already provides the functionality of `vite-tsconfig-paths` including additional patches for it to work within an Nx workspace. You only need the `nxViteTsPaths` plugin, not both, as also indicated by it's removal from your config resulting in it working as expected.

**Comment by AndrewMakarevich** [comment]
Hi, @Coly010, thanks for your answer! The problem there was is that if I would remove that tsconfigPaths, storybook wouldn't see paths, which're declared within tsconfig.json file, but as soon as I added tsconfigPaths, it worked as expected (but it only runs if I run storybook through pnpm, not from nx cli)
