### ISSUE TITLE
Error updating from 18.3.5 to 19.6.0

### ISSUE THREAD

**Issue by Code-Divine** [nrwl/nx#27485]
### Current Behavior

When I ran npx nx migrate --run-migrations I am getting this error

`Running migration @nx/cypress: update-19-6-0-update-ci-webserver-for-vite

 NX   Failed to run update-19-6-0-update-ci-webserver-for-vite from @nx/cypress. This workspace is NOT up to date!

 NX   matchingPluginRegistrations is not iterable

Pass --verbose to see the stacktrace.

Command failed: npx nx _migrate --run-migrations

 NX   Command failed: npx nx migrate --run-migrations`
 
 Not sure what it means or what is broken. I googled the errors but nothing comes up. When I migrate to 19.5.7 the error did not exist.

### Expected Behavior

It should migrate without any issue

### Steps to Reproduce

1.

### Nx Report

```shell
Node           : 20.11.0
OS             : darwin-x64
Native Target  : x86_64-macos
npm            : 10.8.2

nx                 : 19.6.0
@nx/js             : 19.6.0
@nx/jest           : 19.6.0
@nx/linter         : 19.6.0
@nx/eslint         : 19.6.0
@nx/workspace      : 19.6.0
@nx/cypress        : 19.6.0
@nx/devkit         : 19.6.0
@nx/eslint-plugin  : 19.6.0
@nx/express        : 19.6.0
@nx/next           : 19.6.0
@nx/node           : 19.6.0
@nx/plugin         : 19.6.0
@nx/react          : 19.6.0
@nrwl/tao          : 19.6.0
@nx/web            : 19.6.0
@nx/webpack        : 19.6.0
typescript         : 5.5.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
This is fixed here https://github.com/nrwl/nx/pull/27471

**Comment by jaysoo** [comment]
Related to #https://github.com/nrwl/nx/issues/27470
