### ISSUE TITLE
Web builder should create a build for legacy browsers only when required

### ISSUE THREAD

**Issue by jbojcic1** [nrwl/nx#2749]
## Expected Behavior

Web builder should be doing build for legacy es5 browsers only if it's actually required for the project based on the targetted browsers. Angular build is doing it based on the browser list https://github.com/angular/angular-cli/blob/d0ede149187fee45646aad5a7e55e1d268ac5bfe/packages/angular_devkit/build_angular/src/utils/build-browser-features.ts

## Current Behavior

Currently web builder does the build for legacy browsers if optimization is on which basically means every prod build.

### Steps to Reproduce

Just create a react project for example and configure browserlist file to only support last chrome version and then run prod build for that project and notice how unnecessary es5 bundles have been created.

**Comment by jbojcic1** [comment]
I noticed that there is a similar functionality in nx https://github.com/nrwl/nx/blob/master/packages/web/src/utils/third-party/utils/build-browser-features.ts
and it's used for building common part of webpack config, so I guess it can also be used to check if legacy build should be triggered at all

**Comment by jbojcic1** [comment]
Since I couldn't wait for this I created my own builder which just extends the default web builder and uses BuildBrowserFeatures to determine if legacy build can be skipped. Repo: https://github.com/jbojcic1/nx-builders

If it seems like a valid approach let me know and I can do the pr to apply it on the web build too.

**Comment by brianmarco** [comment]
Would love to have this feature as well. As it stands now we're paying for additional compute time with each pipeline execution to produce the legacy builds that we don't actually need.  Turning off `optimization` in the build prevents the legacy builds from happening, but then we lose all the other benefits of the `optimization` option (e.g. hashes for cache busting). Thanks for putting this forward @jbojcic1 .

I also really like the idea of leveraging browserslist to determine if the legacy build is required. Though I guess one could argue for something more explicit, like a specific configuration option.

**Comment by ShayDavidson** [comment]
@vsavkin any idea when such thing can be implemented for React?

**Comment by jbojcic1** [comment]
@ShayDavidson it's already done in the new version of nx. Not sure why they didn't mark it as done though.

**Comment by ShayDavidson** [comment]
Thanks @jbojcic1! I still can't get it to work though. Should i just `optimization: false` in the `workspace.json` settings for my build step?

**Comment by ShayDavidson** [comment]
Okay I understand what's going on. I'm using the `package` builder instead. Is that supported there?

**Comment by jbojcic1** [comment]
Not sure about package builder. I've never used it. Try looking here https://github.com/nrwl/nx/blob/master/packages/web/src/builders/package/package.impl.ts

**Comment by ShayDavidson** [comment]
Apparently it was a completely different issue. I had to change the `useBuiltIns` in the `.babelrc` of the package to false.
