### ISSUE TITLE
Generate docs for component libraries

### ISSUE THREAD

**Issue by Yonet** [nrwl/nx#275]
Option to auto generate docs from dumb component libraries to increase the discoverability of the shared modules. You can see a generated doc example here: http://ui.sportngin.com/

**Comment by tyler-morrison** [comment]
My team was able to do this pretty easily using [Compodoc](https://github.com/compodoc/compodoc).

Compodoc reads your entire Angular app without actually compiling the source. Just create a new `tsconfig.json` at the root level of your project and be sure to use the following...

```json
{
...
"include": [
    "apps/**/*.ts",
    "libs/**/*.ts"
]
...
}
```

Then you can run `compodoc -p ./tsconfig.compodoc.json` and easily create living docs related to your Nx workspace.

**Comment by vogloblinsky** [comment]
I have added a special paragraph in the documentation about this use-case : https://compodoc.github.io/website/guides/tips-and-tricks.html#documentation-of-several-apps-in-a-monorepository

**Comment by FadiNouh1** [comment]
using alias paths in the application seems this is not working 
example :

in app.module.ts

`import { productModule } from "@eshop/product"`

in tsconfig.compdoc.ts: 
```typescript
"paths": {
    "@eshop/product" : ["libs/product/src/index.ts"]
}
```

I get the error : 
```<rejected> { Error: File not found: C:/git-projects/online-shop/frontend/apps/eshop/src/app/@eshop/product/product.module.ts
```

**Comment by vogloblinsky** [comment]
@FadiNouh1 Compodoc doesn't support that right now, sorry..

**Comment by nayfin** [comment]
@vogloblinsky it seems the nx demo you point to in the compodoc docs has changed and no longer includes compodoc.

**Comment by liquidautumn** [comment]
It seems Compodoc yet to implement notion of NX application and library. Is there any effort in this direction? I'd like to contribute, but don't know if I should start it by myself or join somebody to help.

**Comment by FrozenPandaz** [comment]
Closing this issue as we now have storybook support and also there is a plugin for compodoc. :tada:

**Comment by nayfin** [comment]
@FrozenPandaz I can't find the compodoc plugin, do you have a link you could add?

**Comment by FrozenPandaz** [comment]
Here's a link to the community plugin:

https://github.com/twittwer/nx-tools/tree/master/libs/compodoc#readme

There's also a full list of community plugins that you can find here!

https://nx.dev/nx-community

**Comment by diegovincent** [comment]
@FrozenPandaz excuse me if this is a stupid question, how can I add this plugin on a v8 workspace?

**Comment by curiouscod3** [comment]
> Here's a link to the community plugin:
> 
> https://github.com/twittwer/nx-tools/tree/master/libs/compodoc#readme
> 
> There's also a full list of community plugins that you can find here!
> 
> https://nx.dev/nx-community

I got this error with Angular 10 and @nrwl 10.
```javascript
node_modules/viz.js/viz.js:33 Invalid asm.js: Function definition doesn't match use
```

**Comment by rhutchison** [comment]
> > Here's a link to the community plugin:
> > https://github.com/twittwer/nx-tools/tree/master/libs/compodoc#readme
> > There's also a full list of community plugins that you can find here!
> > https://nx.dev/nx-community
> 
> I got this error with Angular 10 and @nrwl 10.
> 
> ```js
> node_modules/viz.js/viz.js:33 Invalid asm.js: Function definition doesn't match use
> ```

I think this is an issue with the viz library.  if you don't need html view, you can use `nx run <project>:compodoc:json`

**Comment by sir-captainmorgan21** [comment]
@FrozenPandaz thoughts on building this into the angular builder as an optional config to run compodoc prior to running storybook? Using compodoc is a requirement to get auto documentation with storybook and angular. I'd assume its used pretty frequently.
