### ISSUE TITLE
Missing typescript checks when using inferred tasks (project Crystal) and vite

### ISSUE THREAD

**Issue by vtregner-cen29414** [nrwl/nx#27501]
### Current Behavior

When new monorepo with react application and vite bundler is generated, build task doesn't include Typescript checks. Build is successful even if contains typescript errrors.

### Expected Behavior

Build of application with Typescript errors should fail.

### Steps to Reproduce

1.
Generate repo using npx create-nx-workspace

and with these parameters:

√ Where would you like to create your workspace? · org
√ Which stack do you want to use? · react
√ What framework would you like to use? · none
√ Integrated monorepo, or standalone project? · integrated
√ Application name · org
√ Which bundler would you like to use? · vite
√ Test runner to use for end to end (E2E) tests · none
√ Default stylesheet format · scss
√ Which CI provider would you like to use? · skip
√ Would you like remote caching to make your build faster? · skip

2.
Type some code with typescript error, for example add this line to app.tsx:

const shouldShowError: string = 5;

3.
Build application

nx run org:build

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.10.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 8.9.0

nx                 : 19.6.0
@nx/js             : 19.6.0
@nx/jest           : 19.6.0
@nx/linter         : 19.6.0
@nx/eslint         : 19.6.0
@nx/workspace      : 19.6.0
@nx/devkit         : 19.6.0
@nx/eslint-plugin  : 19.6.0
@nx/react          : 19.6.0
@nrwl/tao          : 19.6.0
@nx/vite           : 19.6.0
@nx/web            : 19.6.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Issue where missing typescript checks was solved in past (prior projet Crystal)
https://github.com/nrwl/nx/issues/13954

The Vite discussion points out that TS checks are not part of the Vite build process:
https://github.com/vitejs/vite/discussions/12870
https://vitejs.dev/guide/features.html#transpile-only

**Comment by Coly010** [comment]
@vtregner-cen29414 As you've mentioned yourself, TS Checks are not part of the `vite` build. 

Project Crystal's intention is to use the underlying tooling more correctly.

I'll add a typecheck target that gets inferred by the vite plugin, but it'll be a separate target. 
You could also do this yourself by adding the following to your targetDefaults in nx.json:

```
"targetDefaults": {
   "typecheck": {
       "cache": true,
        "inputs": ["^production", "production"].
       "command": "tsc --noEmit",
    }
}
```

Then in the `project.json` of any projects you want to ensure typechecking is performed on, add the following:

```
"targets": {
   "typecheck": {},
   "build": {
       "dependsOn": ["typecheck"]
   }
}
```

Even if we infer the `typecheck` target, you'll need to add a dependsOn to the build target if you want it to run before `app:build`

**Comment by cwagner22** [comment]
@Coly010 The inferred typecheck PR doesn't load any tsconfig file.
https://github.com/nrwl/nx/commit/ceff54177b563b2912c48a72fc9b345f4aab62ee#diff-e21b84bc7a86a657a55ca6be0f7f8dbe1c2a3ff3475357e0de168fc775c987bbR215

The command `tsc --noEmit` doesn't do anything if we are using tsconfig.lib.json

**Comment by Coly010** [comment]
Good catch
