### ISSUE TITLE
Vitest Failures after updating to `19.5.4` when using `@nx/vite:test` executor

### ISSUE THREAD

**Issue by illmerlukas** [nrwl/nx#27500]
### Current Behavior

After upgrading our project from version `18.x` to `19.6.0`, our tests have started failing since version `19.5.4`. The failure appears to be related to this change: https://github.com/nrwl/nx/pull/27118. This issue specifically affects projects set up with `@nx/vite:test` when using a `vite.config.ts` for both testing and the app. To resolve this, we would need to either create a separate vitest configuration file and remove the vue plugin or conditionally include the vue plugin.

Vite.config.ts

```js
/// <reference types='vitest' />
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import { nxViteTsPaths } from '@nx/vite/plugins/nx-tsconfig-paths.plugin';

export default defineConfig({
  root: __dirname,
  cacheDir: '../../node_modules/.vite/apps/nx-vitest-issue',

  server: {
    port: 4200,
    host: 'localhost',
  },

  preview: {
    port: 4300,
    host: 'localhost',
  },

  plugins: [vue(), nxViteTsPaths()],

  // Uncomment this if you are using workers.
  // worker: {
  //  plugins: [ nxViteTsPaths() ],
  // },

  build: {
    outDir: '../../dist/apps/nx-vitest-issue',
    emptyOutDir: true,
    reportCompressedSize: true,
    commonjsOptions: {
      transformMixedEsModules: true,
    },
  },

  test: {
    watch: false,
    globals: true,
    environment: 'jsdom',
    include: ['src/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],

    reporters: ['default'],
    coverage: {
      reportsDirectory: '../../coverage/apps/nx-vitest-issue',
      provider: 'v8',
    },
  },
});
```

### Expected Behavior

Tests should ideally pass without requiring additional configuration when using the `@nx/vite:test` executor. However, I'm uncertain about what the best approach would be and would appreciate any guidance.

### GitHub Repo

https://github.com/illmerlukas/nx-vitest-issue

### Steps to Reproduce

1. clone repo
2. install dependencies -> `npm i`
3. run failing tests -> `npx nx test nx-vitest-issue`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.16.0
OS             : linux-x64
Native Target  : x86_64-linux
npm            : 10.8.1

nx                 : 19.6.0
@nx/js             : 19.6.0
@nx/linter         : 19.6.0
@nx/eslint         : 19.6.0
@nx/workspace      : 19.6.0
@nx/devkit         : 19.6.0
@nx/eslint-plugin  : 19.6.0
@nrwl/tao          : 19.6.0
@nx/vite           : 19.6.0
@nx/vue            : 19.6.0
@nx/web            : 19.6.0
typescript         : 5.5.4
```

### Failure Logs

```shell
FAIL  src/app/App.spec.ts [ src/app/App.spec.ts ]
SyntaxError: At least one <template> or <script> is required in a single file component.
 ❯ Object.parse$2 [as parse] ../../node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:1920:7
 ❯ createDescriptor ../../node_modules/@vitejs/plugin-vue/dist/index.cjs:86:43
 ❯ transformMain ../../node_modules/@vitejs/plugin-vue/dist/index.cjs:2331:34
 ❯ TransformPluginContext.transform ../../node_modules/@vitejs/plugin-vue/dist/index.cjs:2881:16
 ❯ PluginContainer.transform ../../node_modules/vite/dist/node/chunks/dep-Cy9twKMn.js:48989:19
 ❯ loadAndTransform ../../node_modules/vite/dist/node/chunks/dep-Cy9twKMn.js:51810:27
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
@illmerlukas Thanks for reporting the issue. It seems like a regression was introduced here: https://github.com/nrwl/nx/pull/27118.

The problem is that plugins are loaded twice--once by Nx, and once by Vitest. By using `vue()` twice, the error occurs. The fix for both this regression and the original issue is to point Vitest to the correct config file and let Vitest load the plugins.
