### ISSUE TITLE
Could not find any generators named "mv" on v19.6.1

### ISSUE THREAD

**Issue by alexandr2110pro** [nrwl/nx#27529]
### Current Behavior

```
➜ nx g move --project=foo --destination=new/path/foo          

 NX   Could not find any generators named "move"
```

### Expected Behavior

It should figure out that it should use `@nx/workspace:move` automatically, as it used to do before.

### Steps to Reproduce

1. Create a workspace with Nx v19.6.1
2. Create a lib
3. Try to move the lib with `nx g mv`

### Nx Report

```shell
Node           : 20.16.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.7.1

nx                 : 19.6.1
@nx/js             : 19.6.1
@nx/jest           : 19.6.1
@nx/linter         : 19.6.1
@nx/eslint         : 19.6.1
@nx/workspace      : 19.6.1
@nx/devkit         : 19.6.1
@nx/eslint-plugin  : 19.6.1
@nx/rollup         : 19.6.1
@nrwl/tao          : 19.6.1
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/rollup/plugin
@nx/eslint/plugin
@nx/jest/plugin
```
```


### Failure Logs

_No response_

### Package Manager Version

9.7.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Can it be because of the pnpm v9?

**Comment by paweltwardziak** [comment]
@alexandr2110pro I am checking if I am gonna face the same issue with npm manager. If so, I will try to fix it.

**Comment by paweltwardziak** [comment]
Hmmm @alexandr2110pro I cannot reproduce the issue. My setup is: 

`$ nx report

 NX   Report complete - copy this into the issue template

Node           : 20.12.1
OS             : win32-x64
Native Target  : x86_64-windows
pnpm           : 9.7.1

nx                 : 19.6.1
@nx/js             : 19.6.1
@nx/jest           : 19.6.1
@nx/eslint         : 19.6.1
@nx/workspace      : 19.6.1
@nx/angular        : 19.6.1
@nx/devkit         : 19.6.1
@nx/eslint-plugin  : 19.6.1
@nx/playwright     : 19.6.1
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/eslint/plugin
---------------------------------------
Community plugins:
@ngrx/eslint-plugin : 18.0.2
@ngrx/signals       : 18.0.2
@ngrx/store         : 18.0.2
`

**Comment by paweltwardziak** [comment]
Maybe this is releted to your OS?

**Comment by paweltwardziak** [comment]
Have you tries to clean-up the repo? `nx reset` or just remove `.nx` folder

**Comment by FrozenPandaz** [comment]
Could you please provide a repo where this occurs? This is working fine here in the `nx` repo.

**Comment by alexandr2110pro** [comment]
Hey there. It turned out the `@nx/workspace` package wasn't installed. I don't know why—I think I've used Nx generators only to create a monorepo and all the libraries in it. I believe previously, when you did it like that, it used to install the workspace package.

The problem went away when I installed it.

**Comment by alexandr2110pro** [comment]
What is more interesting, that `nx report` printed the `@nx/workspace` but it wasn't in the package.json
