### ISSUE TITLE
Unit tests run in non-ivy mode

### ISSUE THREAD

**Issue by artaommahe** [nrwl/nx#2752]
## Expected Behavior

Jest unit tests run in ivy mode

## Current Behavior

Unit tests run in non-ivy mode

### Steps to Reproduce

1. add this to component's OnInit
```ts
import { ɵivyEnabled as ivyEnabled } from '@angular/core';

  public ngOnInit(): void {
    console.log('> ivyEnabled', ivyEnabled);
  }
```
2. run component's test and see `false` in console

It returns `true` in browser.

### Context

```
  @nrwl/angular : 9.1.4
  @nrwl/cli : 9.1.4
  @nrwl/cypress : 9.1.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.1.4
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.1.4
  @nrwl/web : Not Found
  @nrwl/workspace : 9.1.4
  typescript : 3.7.5
```

## Other

Running component's tests in non-ivy mode many stuff that are built with ivy support will not work and we have contradictions how component behave in browser and in tests.
E.x. regular task - unsubscribing on destroy via custom operator/decorator, like this library https://github.com/ngneat/until-destroy/. Currently it fails in tests on start
```ts
    TypeError: Cannot read property 'onDestroy' of undefined
```
because is looking for ivy-related properties on component for proper work and has not found them.

**Comment by elgurinn** [comment]
Please take a look here: [Cannot test @Injectable() services with Jest](https://github.com/ngneat/until-destroy/issues/54)

Do you have this postinstall command:

`ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points`

if so try changing it to just `ngcc` and try again.

**Comment by brandonroberts** [comment]
Closing as resolved

**Comment by krokofant** [comment]
@brandonroberts How is this solved? The default behavior seems broken, the workaround isn't a fix. 😕
