### ISSUE TITLE
[QUESTION] npm run workspace-schematic just for output generation?

### ISSUE THREAD

**Issue by philly-vanilly** [nrwl/nx#2754]
Is it possible to use this or another command to compile (ts to js) custom schematics and copy files to /dist/ without producing an error?

I just found when you do `npm run workspace-schematic .` it basically generates the output that I would need to use an extra package.json script for, for free, but with the drawback of producing an error (because . is not a valid schematic).

I need a compiled output for publishing my custom workspace schematics on npm. Running `tsc -p tools/tsconfig.tools.json` is not enough as I need to additionally copy collection.json or package.json.

publishing directly from the tools/schematics folder is also possible, but then I need another tsconfig for compiling in place and to cleanup the JS afterwards

**Comment by brandonroberts** [comment]
As a workaround, you can run `npm run nx workspace-schematics --list-schematics` to compile the schematics into the dist folder without an error

**Comment by FrozenPandaz** [comment]
If you are trying to publish your schematics on npm, I recommend looking into if Nx plugins can help.

See if this guide helps you:
https://nx.dev/angular/guides/nx-plugin

**Comment by JoepKockelkorn** [comment]
> As a workaround, you can run `npm run nx workspace-schematics --list-schematics` to compile the schematics into the dist folder without an error

FYI, it's `npm run nx workspace-schematic --list-schematics` as in single form 'workspace-schematic'
