### ISSUE TITLE
NX Cloud agent: dotnet is not installed - setup-dotnet action is ignored

### ISSUE THREAD

**Issue by roldengarm** [nrwl/nx#27558]
### Current Behavior

My repo depends on .NET as we're using nx-dotnet.
I'm starting a ci-run on 8 linux-medium-js and then have below two actions
```
 - uses: actions/setup-dotnet@v4
    with:
      dotnet-version: '8.0.100'
  - run: npm ci
```
Then, npm ci fails, as dotnet is not installed on the runner:
```
nx g @nx-dotnet/core:restore
27   
28   /bin/sh: 1: dotnet: not found
```

### Expected Behavior

It installs dotnet on the agent before running npm ci

### Steps to Reproduce

1. add https://www.nx-dotnet.com/core to a repo
2. enable nx cloud
3. try to run `npm ci`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.16.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.8.1

nx                 : 19.5.7
@nx/js             : 19.5.7
@nx/jest           : 19.5.7
@nx/linter         : 19.5.7
@nx/eslint         : 19.5.7
@nx/workspace      : 19.5.7
@nx/angular        : 19.5.7
@nx/cypress        : 19.5.7
@nx/devkit         : 19.5.3
@nx/eslint-plugin  : 19.5.7
@nrwl/tao          : 19.5.7
@nx/web            : 19.5.7
@nx/webpack        : 19.5.7
nx-cloud           : 19.0.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx-dotnet/core
@nx/cypress/plugin
---------------------------------------
Community plugins:
@fortawesome/angular-fontawesome : 0.15.0
@jsverse/transloco               : 7.4.3
@nx-dotnet/core                  : 2.4.3
ng2-charts                       : 6.0.1
---------------------------------------
The following packages should match the installed version of nx
  - @nx/devkit@19.5.3
  - @nrwl/devkit@19.5.3

To fix this, run `nx migrate nx@19.5.7`
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information
I guess another workflow action has to be added to [this repo](https://github.com/nrwl/nx-cloud-workflows)?
Or alternatively, can we customise the docker image used for the runner?

**Comment by EelcoLos** [comment]
can concur, this happens to me as well: https://github.com/EelcoLos/nx-tinkering/actions/runs/10520973969/job/29150814666

**Comment by EelcoLos** [comment]
if we look at https://github.com/nx-dotnet/nx-dotnet/blob/master/.github/workflows/pr.yml & https://github.com/nx-dotnet/nx-dotnet/blob/master/.github/workflows/main.yml, we can see which workflows are used there and are possible now. Still, the question remains

**Comment by FrozenPandaz** [comment]
Correct! You'll need to define your own custom launch templates to use dotnet in Nx Agents.
