### ISSUE TITLE
--max_old_space_size=8192 is not considered after upgrade to 9.1.4

### ISSUE THREAD

**Issue by elvirdolic** [nrwl/nx#2755]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior
Building the app is not running into: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

## Current Behavior
After update to  "@nrwl/workspace": "9.1.4" build is failing

## Failure Information (for bugs)

Before update:

```
package.json
"ng": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng",

nx affected:build --base=origin/master --head=HEAD --aot

>  NX  Running target build for projects:

  - projectX

  With flags:
    --aot=true


———————————————————————————————————————————————

$ node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build projectX --aot=true

```

After update:

where taskRunners are used

```
nx affected:build --base=origin/master --head=HEAD --aot 

>  NX  Running target build for projects:

  - projectX

 
  With flags:
    --aot=true

———————————————————————————————————————————————

> ng run projectX:build --aot=true 

```

for me it seems that --max_old_space_size=8192 is not forwarded to node process? Is there any way to set this?

**Comment by FrozenPandaz** [comment]
Sorry, this is a difference with the new task-runner.

You can now pass the `--max_old_space_size` directly into Nx via the following:
```
node --max_old_space_size=8192 node_modules/@nrwl/cli/bin/nx.js affected:build --all --configuration production
```

Please let me know if this works since it is hard to reproduce the issue without a repo.

**Comment by elvirdolic** [comment]
@FrozenPandaz looks good with adding it directly into nx.

**Comment by manandkumaar** [comment]
@FrozenPandaz This issue is getting reproduced in latest version 9.2.3 and 9.2.4.

Even i tried with empty nx angular project, it is still getting reproduced.

`"affected:build": "node --max_old_space_size=8192 node_modules/@nrwl/cli/bin/nx.js affected:build",` 

![image](https://user-images.githubusercontent.com/2328960/81848712-299aa600-9573-11ea-8934-3f4b11b936a0.png)

Please suggest.
