### ISSUE TITLE
yarn global command samples: 'yarn global' commands have been removed in 2.x

### ISSUE THREAD

**Issue by neillindberg** [nrwl/nx#27588]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?
[
Enter the URL or documentation section here.
](https://nx.dev/recipes/installation/update-global-installation)

### Additional context or description

Using the `yarn global` commands throughout this page w/ yarn 2.x yields:
Usage Error: The 'yarn global' commands have been removed in 2.x - consider using 'yarn dlx' or a third-party plugin instead

I should note that I've yet to find the proper command so just reporting.

**Comment by paweltwardziak** [comment]
Hi @neillindberg I've just raised a PR with the docs update
