### ISSUE TITLE
nx release command on Gitlab CI

### ISSUE THREAD

**Issue by jasus** [nrwl/nx#27595]
### Current Behavior
I have a NX projects with some libs I want to publish in the gitlab package registry.

I run this command in my Gitlab CI pipeline

`npx nx release --skip-publish`

but I notice that the tags are not created in the gitlab project, when it even appears in the terminal

```
UPDATE libs/xxxxxx/package.json

    "name": "@XXXXXXX/xxxxxx",
-   "version": "0.1.3",
+   "version": "0.1.4",
    "description": "TEST",


 NX   Staging changed files with git


 NX   Generating an entry in libs/xxxxxx/CHANGELOG.md for @XXXXXXX/xxxxxx/v0.1.4


UPDATE libs/xxxxxx/CHANGELOG.md

+ ## 0.1.4 (2024-08-22)
+
+
+ ### 🩹 Fixes
+
+ - code
+
+
  ## 0.1.3 (2024-08-22)




 NX   Staging changed files with git


 NX   Committing changes with git


 NX   Tagging commit with git


 NX   Skipped publishing packages.
```

I checked that in local works and create the tags locally, but I want to automate in my gitlab ci pipeline.

I checked the video in the official page and seems in Github is working
@JamesHenry 
https://nx.dev/blog/versioning-and-releasing-packages-in-a-monorepo

Should this also work on Gitlab or is there something I'm missing?

I suppose in this messages is applying this in the gitlab runner but,

```
NX   Committing changes with git


NX   Tagging commit with git
```

Should I run a manual git push or something?

I don't know if this is correct

Thank you in advance

### Expected Behavior

Tags should be created in GITLAB

### Steps to Reproduce

1.
`nx.json`

```
"release": {
    "projects":["libs/*"],
    "projectsRelationship": "independent",
    "releaseTagPattern": "@XXXXX/{projectName}/v{version}",
    "changelog": {
      "projectChangelogs": true
    },
    "git": {
      "commit": true,
      "tag": true
    },
    "version": {
      "conventionalCommits": true
    }
  },
  "targetDefaults": {
    "nx-release-publish": {
      "dependsOn": ["build"],
      "options": {
        "packageRoot": "dist/libs/{projectName}"
      }
    }
  },
```

### Nx Report

```shell
Node           : 18.16.1
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 9.5.1

nx                 : 19.6.1
@nx/js             : 19.6.1
@nx/jest           : 19.6.1
@nx/linter         : 19.6.1
@nx/eslint         : 19.6.1
@nx/workspace      : 19.6.1
@nx/devkit         : 19.6.1
@nx/eslint-plugin  : 19.6.1
@nx/react          : 19.6.1
@nx/rollup         : 19.6.1
@nrwl/tao          : 19.6.1
@nx/vite           : 19.6.1
@nx/web            : 19.6.1
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
@nx/jest/plugin
@nx/rollup/plugin
```

### Package Manager Version

9.5.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JamesHenry** [comment]
@jasus Yes, right now the only time we create an automated push is when the user opts in to GitHub Release creation (where we POST their changelog markdown to the GitHub API to create entries like these: https://github.com/nrwl/nx/releases)

So right now you will need to add a git push command yourself for GitLab. I recommend the following args:

```sh
git push --follow-tags --no-verify --atomic
```

It looks like GitLab has its own concept of "releases", similar to GitHub, would you like to work with me to enable creating them as part of Nx release? https://docs.gitlab.com/ee/user/project/releases/

The main thing I will need from you is to test things out on your GitLab instance.

**Comment by JamesHenry** [comment]
@jasus I hope you will be wiling to help test things, but I've realized we have an already upvoted issue for GitLab releases support, so please join me on that issue: https://github.com/nrwl/nx/issues/22985

This one is resolved by you adding the push command in your pipeline, per the above

**Comment by jasus** [comment]
> @jasus I hope you will be wiling to help test things, but I've realized we have an already upvoted issue for GitLab releases support, so please join me on that issue: #22985
> 
> This one is resolved by you adding the push command in your pipeline, per the above

Perfect, I would be glad to help on this.

Thanks for your help, we keep in contact
