### ISSUE TITLE
React dynamic module federation

### ISSUE THREAD

**Issue by VanTigranyan** [nrwl/nx#27592]
### Current Behavior

Trying to setup Dynamic module federation with React host and remote. The latest version of @nx/react/mf provides necessary functions to load and define remotes from a json manifest and then load the module with the loadRemoteModule function. But whenever I try to load a react remote in the host app I get an error about import.meta. If I set library type to var in module federation config then I get another error stating that a federated module cannot contain multiple files (not sure what that means).
![CleanShot 2024-08-22 at 20 23 06@2x](https://github.com/user-attachments/assets/e9ca523c-2636-4877-a242-ab4a9547b5de)
![CleanShot 2024-08-22 at 20 55 04@2x](https://github.com/user-attachments/assets/8f9a1b80-44d7-4f91-988d-c13072d68e3c)

### Expected Behavior

There is a nice and proper setup for dynamic module federation to work with React apps but the functionality basically doesn't work with NX's default setup (these applications are freshly generated by NX, nothing custom). There is no documentation to support us with how to setup everything with React as the main framework and there are the issues that I described above. I would appreciate any help here. Maybe I am doing something wrong, or maybe there is a real issue. Thanks in advance.

### GitHub Repo

https://github.com/VanTigranyan/nx-react-dynamic-mf

### Steps to Reproduce

1. Clone the repo
2. do npm install and run nx serve react-shell --devRemotes=mfe-login
3. Observe the error in the browser console by opening localhost:4200

### Nx Report

```shell
 NX   Report complete - copy this into the issue template

Node           : 18.19.1
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 9.9.3

nx                 : 19.6.2
@nx/js             : 19.6.2
@nx/jest           : 19.6.2
@nx/linter         : 19.6.2
@nx/eslint         : 19.6.2
@nx/workspace      : 19.6.2
@nx/devkit         : 19.6.2
@nx/eslint-plugin  : 19.6.2
@nx/react          : 19.6.2
@nrwl/tao          : 19.6.2
@nx/web            : 19.6.2
@nx/webpack        : 19.6.2
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/jest/plugin
---------------------------------------
Community plugins:
@nx/rspack : 19.5.0
```

### Failure Logs

```shell
Logs from browser console.

Uncaught SyntaxError: Cannot use 'import.meta' outside a module (at remoteEntry.js:7973:29)Understand this error
20:22:59.315 watchConsoleLogs.8258a5d6.js:6 Failed to initialize remote secondaryMFE TypeError: Cannot read properties of undefined (reading 'init')
    at Object.init (dynamic-federation.js:45:1)
    at loadRemoteContainer (dynamic-federation.js:75:1)
    at async loadRemoteModule (dynamic-federation.js:28:1)
console.<computed> @ watchConsoleLogs.8258a5d6.js:6
init @ dynamic-federation.js:48
loadRemoteContainer @ dynamic-federation.js:75
await in loadRemoteContainer
loadRemoteModule @ dynamic-federation.js:28
(anonymous) @ app.tsx:20
Qj @ react-dom.production.min.js:243
Hk @ react-dom.production.min.js:285
(anonymous) @ react-dom.production.min.js:281
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
Show 8 more frames
Show lessUnderstand this error
20:22:59.322 dynamic-federation.js:42 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'get')
    at Object.get (dynamic-federation.js:42:1)
    at loadRemoteModule (dynamic-federation.js:29:1)
```

### Package Manager Version

9.9.3

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by VanTigranyan** [comment]
I think to fix this, react remotes should generate remoteEntry.mjs instead of remoteEntry.js, otherwise the browser basically doesn't recognize remoteEntry as a module, hence import.meta is not available in that js file.

**Comment by VanTigranyan** [comment]
I want to add that when I load a react remote app supported by the same NX setup in my angular shell app, it works without any issues.

**Comment by VanTigranyan** [comment]
@Coly010 Hi. Maybe you have some context?

**Comment by Coly010** [comment]
I think it does just boil down to the ESM issue. I would have bet that we did generate .mjs remotes for React, but it seems not. I’ll have a look

**Comment by VanTigranyan** [comment]
@Coly010 Thank you very much. I'll wait for your update.

**Comment by VanTigranyan** [comment]
Just FYI: I did dig into MF plugin config and seems like it is set to output a module, but the fileName is set to remoteEntry.js. Taking into account that webpack bundles react and doesn't output ESM, I think this is where the conflict resides. CommonJS react bundles try to execute an ESM module. Obviously this doesn't work.

**Comment by Coly010** [comment]
Interestingly, I wasn't able to reproduce this on a new workspace I just created.

I'll take a look at your repo now, but let me know if this one works for you: https://github.com/Coly010/nx-react-dyn-fed-demo

**Comment by Coly010** [comment]
@VanTigranyan Found the problem, you didn't have `loadRemoteModule` wrapped in `React.lazy`. Unfortunately, this is a requirement currently due to how the scopes are initialized with MF.

I created a PR to show this: https://github.com/VanTigranyan/nx-react-dynamic-mf/pull/1

**Comment by VanTigranyan** [comment]
@Coly010 OMG. I am so stupid. How could I forget that. I understand how that works for components. But what if I want to get a shared library from my react remote?

**Comment by Coly010** [comment]
@VanTigranyan Like this: https://github.com/VanTigranyan/nx-react-dynamic-mf/pull/2 :)

<img width="727" alt="image" src="https://github.com/user-attachments/assets/822a44d2-81cd-41b2-9e9b-6da732c56d9d">
<img width="570" alt="image" src="https://github.com/user-attachments/assets/09bd5df2-6fde-4bc3-aa25-5763e3015d0e">
<img width="71" alt="image" src="https://github.com/user-attachments/assets/fb629d03-fd73-4779-b139-c5adc0b5812e">

**Comment by VanTigranyan** [comment]
@Coly010 I can confirm that even with React.lazy() I can import only components. So we are blocked if we want to import other things, such as shared libraries. And even if I export a dumb component with the library, I pretty much have to count the component so that React.lazy() works a loads the lib. How do we solve this problem?

**Comment by VanTigranyan** [comment]
@Coly010 I tried your solution. It's great. The problem is I wanted to expose another module (shared state) from the MFE itself, without creating another MFE just for sharing a library. But I guess I can work with this for now. Thanks a lot for looking into this so quickly and for great suggestions. I am at least unblocked right now.

**Comment by VanTigranyan** [comment]
One more question I have is whether @module-federation/enhanced is used for Angular Module federation as well?

**Comment by Coly010** [comment]
You can follow the pattern that i created with the new MFE and just apply it to an existing MFE. the `@nx/react:federate-module` generator allows you to specify and existing remote and it'll add a new export to it that can be consumed via `loadRemoteModule`.

Yes `@module-federation/enhanced` is also being used for Angular

**Comment by VanTigranyan** [comment]
@Coly010 Sorry for bothering so much. I just want to get answers to all problems that we have so that I can start to work on building the actual application. Is it possible to load a dynamic remote into another dynamic remote? Let's say we have menu that we want to share and setup it as an MFE. then I want to load this menu dynamically in another dynamic remote (let's say dashboard) and that remote gets dynamically loaded into the shell. Right now I cannot get it to work.

**Comment by Coly010** [comment]
@VanTigranyan Theoretically yes it should. I'd be interesting in seeing the error you're facing with it

**Comment by VanTigranyan** [comment]
Oh, it's the same error with import.meta not being available.
For the context, we have a huge Angular application, that we are trying to decouple into smaller React-based MFEs. So I added MF setup to Angular to act as a shell, then created a react app as a remote. I managed to dynamically load the remote and render it. I managed to solve the routing, navigation and state-sharing problems. The only thing that remains for me to solve is loading another react-remote in the first one I mentioned. After experimenting today I found out that when I set the definitions in the shell, even if I use loadRemoteModule in a remote, it still sees the definitions and can load another remote. But this works only if the host is react. I tried to set definitions in Angular shell using both react/mf and angular/mf libs, so that each app type gets the definitions but that didn't help either. I found that when I share @nx/react in Angular and when I do it in a react shell, the output is not the same, hence, I guess, Even when I share @nx/react from Angular, the react remote loads it's own instance of this library, meaning the 'singletion' param doesn't work in multi-stack MF setup.

**Comment by VanTigranyan** [comment]
@Coly010 I ended up using @module-federation/enhanced with rspack on react and angular now just consumes these remotes using loadRemote(). It worked flawlessly. I was able to solve all problems I had. I used its plugin instead of NX' one. Thank you so much for pointing me to it. I would struggle for days if not that suggestion. So all problems are solved. Thank you very much again.
