### ISSUE TITLE
Question: how to use Tailwinds CSS with Nx?

### ISSUE THREAD

**Issue by mcblum** [nrwl/nx#276]
Thanks for all of your work on Nx. I'm trying to incorporate Tailwinds into our Nx monorepo. There are a lot of instructions out there that would work great if the project was a single project, but I don't understand enough about how apps are actually built / assembled when within a workspace.

Could anyone provide a bit of guidance as to how I can modify the webpack config of each app individually? Or is there a better way to do this?

**Comment by vsavkin** [comment]
Nx is a CLI project. So the only modification allowed are the ones allowed by the CLI. I'd read through the CLI docs to see what options are available

What do you need to modify to make it work?

**Comment by mcblum** [comment]
@vsavkin you're on top of these issues today :)

Looks like the most common way is to eject the project. Does that cause any issues? Here's an SO issue that goes over the basics.

https://stackoverflow.com/questions/47381149/angular-4-tailwindcss-setup

I think a lot of my lack of understanding of how this works comes from not being able to visualize how to set different config options for the different apps within the Nx Workspace.

**Comment by vsavkin** [comment]
In CLI 1.x you have to inject to be able to change the webpack configuration of any of your apps. Nx  uses CLI 1.x.

>> Does that cause any issues? H
After ejecting `ng generate` will continue to work, but `ng build`, `ng test`, and `ng serve` won't.  The npm scripts will be rewritten to invoke webpack directly.

We are currently working on making Nx run on top of CLI 6, which allows you to customize your build step. Once it's released, you won't have to eject to be able to incorporate Tailwinds.

**Comment by vdiaz1130** [comment]
Has anyone been successful in implementing Tailwind with NX Angular project? Can anyoe direct me to steps, suggestions or sample repo?
Thanks!

**Comment by vdiaz1130** [comment]
I was able to get it to work following the instructions here:
https://github.com/tehpsalmist/ng-tailwindcss

**Comment by dsebastien** [comment]
For those interested, I’ve written an article explaining how to integrate Tailwind with Nx, Angular and Storybook over here:  https://medium.com/@dSebastien/adding-tailwind-support-to-a-nrwl-nx-workspace-with-angular-and-storybook-bf890ea882e

**Comment by derHodrig** [comment]
@dsebastien i followed your guide and end up with true
```
true is not a PostCSS plugin
```

I followed your guide right before the point Adding Tailwind support to Nx’s Storybook build.
Hm are there any breaking changes?

**Comment by dsebastien** [comment]
@derHodrig Indeed, the last PostCSS major version has broken plugins, I've had the same kind of error messages when trying to use PostCSS-import..

**Comment by derHodrig** [comment]
> For those interested, I’ve written an article explaining how to integrate Tailwind with Nx, Angular and Storybook over here: https://medium.com/@dSebastien/adding-tailwind-support-to-a-nrwl-nx-workspace-with-angular-and-storybook-bf890ea882e

behind a paywall :(

**Comment by JoA-MoS** [comment]
@derHodrig - open the link incognito

**Comment by derHodrig** [comment]
@JoA-MoS oh this is a great tipp. thanks.

**Comment by gilles-bertrand** [comment]
Hi nothing snce to work now, this is the error I receive
**'customWebpackConfig' is not found in schema**

**Comment by METACEO** [comment]
Hey @gilles-bertrand, I had a similar issue when coming from an older Angular app - I still had a `customWebpackConfig` object in my `@angular-builders/custom-webpack:dev-server` options and I was getting your issue until I removed it. Have you tried [the custom webpack dev server](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack#custom-webpack-dev-server) options similar to the example `angular.json` snippet?

**Comment by pixelsailor** [comment]
As @METACEO mentioned, removing the `customWebpackConfig` object resolved the problem for me. Thanks for this.
