### ISSUE TITLE
Show library typing/runtime dependencies differently in dependency graph

### ISSUE THREAD

**Issue by spaceribs** [nrwl/nx#2760]
## Expected Behavior

When importing just the type information from a library using Typescript >3.8:
```
import type { MyInterface } from '@project/my-models';
```
The `affected:dep-graph` should indicate it is a type dependency rather than a runtime dependency, or optionally filter type dependencies.

## Current Behavior

Libraries which are depended on for just type information are shown with the same dependency arrow-line as those libraries which provide runtime services.

### Steps to Reproduce

1. Create an app
2. Create a library
3. Create a interface model in the library and export it.
4. Import the interface via `import type` into the app.
5. Run `affected:dep-graph` command.
6. Library is shown as a hard dependency for the app.

### Context

```
  @nrwl/angular : 9.1.4
  @nrwl/cli : 9.1.4
  @nrwl/cypress : 9.1.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.1.4
  @nrwl/linter : 9.1.4
  @nrwl/nest : 9.1.4
  @nrwl/next : Not Found
  @nrwl/node : 9.1.4
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.1.4
  @nrwl/web : 9.1.4
  @nrwl/workspace : 9.1.4
  typescript : 3.8.3
```

**Comment by spaceribs** [comment]
As an additional aside to this, there are also other dependency types, such as Sass imports, which would be great to differentiate.

**Comment by spaceribs** [comment]
any word from the team on this?

**Comment by vsavkin** [comment]
Sorry. The issue was marked by mistake. I removed the label.

**Comment by MaximSagan** [comment]
This would be nice to have.

Does anyone have any thoughts on whether `affected:build` would be able to safely skip re-builds of apps that are only "type-affected" (so long as there are no type errors)?

**Comment by spaceribs** [comment]
Unstale

**Comment by MaximSagan** [comment]
Unstale

I might see if I can take this one

**Comment by spaceribs** [comment]
thank you so much @philipjfulcher!

**Comment by johannesf95** [comment]
@vsavkin is there a reason why this feature has been reverted?

**Comment by spaceribs** [comment]
Yeah, i'm a bit confused myself, did this not mean to be released?

**Comment by philipjfulcher** [comment]
@spaceribs - I reached out to Victor about this:

> The issue wasn’t the dep graph showing but adding types to core indicating types of edges and changing the logic in getUpdatedProjectGraph.
getUpdatedProjectGraph stopped working for the example I had (so there was a bug there). I also I don’t think we should have the DependencyType type. The choices we have right now were JS oriented.
So we can restore the viz part of it without making any core changes.

Does that make sense? I think you can re-raise a PR with the viz changes, but skip the core changes that were made previously. If you need help, applying the changes to just the viz, let me know and I can help.
