### ISSUE TITLE
Playwright project generated with Remix use the wrong start command

### ISSUE THREAD

**Issue by Anthony-Jhoiro** [nrwl/nx#27628]
### Current Behavior

The playwright config `webServer.command` is based on the path given in the CLI argument. 
Example: `yarn nx g app dashboard/dashboard` (with playwright) will use `yarn nx dev dashboard/dashboard` as the `webServer.command` command

### Expected Behavior

The command should be based on the project name so the command would be `yarn nx dev dashboard`.

### GitHub Repo

https://github.com/Anthony-Jhoiro/nx-reproductible-case-remix-playwright-generation

### Steps to Reproduce

1. create nx workspace with `npx create-nx-workspace --packageManager yarn`
2. add remix dependency `yarn nx add @nx/remix`
3. generate project in a subfolder with playwright as e2e test runner `yarn nx g app dashboard/dashboard`
4. look into `dashboard/dashboard-e2e/playwright.config.ts`

### Nx Report

```shell
➜ nx report

 NX   Report complete - copy this into the issue template

Node   : 22.7.0
OS     : darwin-arm64
yarn   : 1.22.22

nx                 : 19.0.1
@nx/js             : 19.0.1
@nx/linter         : 19.0.1
@nx/eslint         : 19.0.1
@nx/workspace      : 19.0.1
@nx/devkit         : 19.0.1
@nx/eslint-plugin  : 19.0.1
@nx/playwright     : 19.0.1
@nx/react          : 19.0.1
@nx/remix          : 19.0.1
@nrwl/tao          : 19.0.1
@nx/vite           : 19.0.1
@nx/web            : 19.0.1
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/remix/plugin
@nx/vite/plugin
@nx/eslint/plugin
@nx/playwright/plugin
@nx/react
```

### Failure Logs

```shell
> nx run dashboard-e2e:e2e

> playwright test

error Command failed with exit code 1.

Error: Process from config.webServer was not able to start. Exit code: 1
```

### Package Manager Version

yarn 1.22.22

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Hi @Anthony-Jhoiro This has been fixed in a more recent version of Nx. I tested this with 19.7 and it works fine
