### ISSUE TITLE
Jest Paths to Modules failing when running tests

### ISSUE THREAD

**Issue by tcoz** [nrwl/nx#2764]
I have an NX workspace up and running, haven't had any trouble with it in some time. However recently I created a new app, and have some paths configured in it in ts.config.app.json (I have no choice but to use these paths):

```
paths: { 
       "core/*": ["apps/myapp/myapp-ui/src/app/core/*"],
      "shared/*": ["apps/,myapp/myapp-ui/src/app/shared/*"],
      "templates/*": ["apps/myapp/myapp-ui/src/app/templates/*"],
}

or 

paths: { 
       "^core/(.*)": ["apps/myapp/myapp-ui/src/app/core/1$"],
      ...
}
```

etc.  (and many other options tried).

It works fines, runs as expected, etc, until I try to test it (using Jest). Then it's all "modules not found". 

I have tried configuring modulePaths, moduleNameMapper, etc. etc. in the jest.config that lives in the root of the app, which looks like this:

workspace
-- apps
----someapps
------myapp
------jest.config.js

Nothing works, the modules are never found. I originally suspected that the rootDir is not doing what I'd expect it to be doing, but by "breaking" the jest resolver, it traces out the rootDir in the console (it actually tells you, rootDir = etc/etc), so I know it's correct.

Any wisdom on this one would be greatly appreciated. I'm at a total brick wall here and I need to get these tests running. If I put the app in a vanilla angular 8 project, everything works fine. 

Thanks in advance. I have looked elsewhere in the issues here, but there doesn't seem, to be any basic guidance insofar as, "this is how it resolves the rootDir, which means this is how you need to configure it."

**Comment by tcoz** [comment]
I manged to find a way to get the root directory tracing out. It's correct. As far as I can see the module entries I'm using are correct (and I've tried many, many different formats, but the basic straightforward one indicated by jest docs is the one I've been told should work). It doesn't. I'm rapidly moving to having to remove the path entries from the app and reconfiguring all the imports (which would be hundreds of them). I'm seriously hoping to avoid having to find where to add "../../.." hundreds of times.

**Comment by ahnpnl** [comment]
If you are having issues with tsconfig path and moduleNameMapper perhaps you can check this https://github.com/kulshekhar/ts-jest/blob/master/TROUBLESHOOTING.md

**Comment by Cammisuli** [comment]
Hey folks, we have a special resolver that we use for Jest to find apps and libs in your workspace. Can you please make sure that the root jest.config.js has something like the following?
```typescript
module.exports = {
  testMatch: ['**/+(*.)+(spec|test).+(ts|js)?(x)'],
  transform: {
    '^.+\\.(ts|js|html)$': 'ts-jest'
  },
  resolver: '@nrwl/jest/plugins/resolver',
  moduleFileExtensions: ['ts', 'js', 'html'],
  coverageReporters: ['html']
};
```

The most important piece being the `resolver` property.

**Comment by Cammisuli** [comment]
I'm going to close this issue as there hasn't been a response in quite some time (after my last comment). If the issue still persists, a new one can be opened. Thank you!

**Comment by lidanh** [comment]
> I know it is an old issue, yet I can't get it to work. I have added the prop you said, but it still can not resolve the paths.
> 
> Is there anything else to be tried?
> 
> I'm trying to set up `globalSetup` and `globalTeardown` scripts since I want to create and seed the test databse. However, for the specified scripts, the resolver does not seem to work. I have tried harcoding the `moduleNameMapper` but still no results. However, the unit tests which also have alias imports, work.

Same here :( 

jest.config.e2e.js:
```js
module.exports = {
  displayName: 'nothing-to-prod-e2e',
  preset: '../../../jest.preset.js',
  globals: {
    'ts-jest': {
      tsconfig: '<rootDir>/../tsconfig.spec.json',
    },
  },
  testMatch: ['**/*.e2e-spec.ts'],
  testEnvironment: 'node',
  transform: {
    '^.+\\.[tj]s$': 'ts-jest',
  },
  moduleFileExtensions: ['ts', 'js', 'html'],
  coverageDirectory: '../../../coverage/apps/nothing-to-prod-e2e',
  globalSetup: "./globalSetup.ts",
  globalTeardown: "./globalTeardown.ts",
};
```

Tried to add the `resolver` or `moduleNameMapper` but it still doesn't work:

```
Cannot find module '@lidan/infra/e2e-test-utils'
```

**Comment by anthonyma94** [comment]
@mikededo I'm running into the same issue, did you find a solution to it?

**Comment by mikededo** [comment]
Sort of. It is a bit tricky to explain, but I share with you the repository in which I am working and how I solved it. 

In [this file](https://github.com/hubbl-app/hubbl/blob/develop/apps/api/src/test/e2e-setup.ts) I set up everything, what would be in the `globalSetup`. All the tests are inside [this file](https://github.com/hubbl-app/hubbl/blob/develop/apps/api/src/test/index.spec.ts) and all are imported from the corresponding files. You can also check my [`project.json`](https://github.com/hubbl-app/hubbl/blob/develop/apps/api/project.json) file in which I have a special command named `test-e2e` that specifically runs these tests.

**Comment by anthonyma94** [comment]
Awesome, thank you for sharing.

I did some research after my comment yesterday, turns out Jest doesn't use ts-node or tsc when using globalSetup, which is why the paths aren't loading. I was able to get it working by progamatically starting the services in my globalSetup file:

```ts
/** These steps are needed as globalSetup doesn't start tsc. */
// Manually load ts-node and tsconfig
require("ts-node").register({
    transpileOnly: true,
});
// Manually load envs
require("dotenv").config({ path: "./apps/api/.env" });
process.env.DB_NAME = "test_db";
process.env.MONGO_URL = "";

// Manually map paths
const { compilerOptions } = require("../../../../tsconfig.base.json");
const tsConfigPaths = require("tsconfig-paths");

tsConfigPaths.register({
    baseUrl: "./",
    paths: compilerOptions.paths,
});
```
Hopefully this helps!
