### ISSUE TITLE
Angular lib schematics started creating tsconfig.libs.prod.json files

### ISSUE THREAD

**Issue by LMFinney** [nrwl/nx#2765]
## Expected Behavior

When I create a lib, the files created for the lib should include `tsconfig.json`, `tsconfig.lib.json`, and `tsconfig.spec.json`, but not other tsconfig files.

## Current Behavior

Starting somewhere after nx 9, it also creates `tsconfig.lib.prod.json`. I don't think it's a critical problem, but I'd like to understand what's ahppening, and if we're supposed to have the file.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. With nx v9.1.4, create a workspace with `npx create-nx-workspace@latest repro-workspace`. I created mine with Angular and Nest, but I don't know if that's important.
2. Add a library with the command `ng g @nrwl/angular:lib ui`

https://github.com/LMFinney/nx-prod/ shows the two commits and the resulting file.

### Context

Please provide any relevant information about your setup:

  @nrwl/angular : 9.1.4
  @nrwl/cli : 9.1.4
  @nrwl/cypress : 9.1.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.1.4
  @nrwl/linter : 9.1.4
  @nrwl/nest : 9.1.4
  @nrwl/next : Not Found
  @nrwl/node : 9.1.4
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.1.4
  @nrwl/web : Not Found
  @nrwl/workspace : 9.1.4
  typescript : 3.7.5

**Comment by FrozenPandaz** [comment]
@brandonroberts

Correct me if I'm wrong but I believe this file is only necessary if the library is publishable. This file is used to publish libraries that are still compiled for view engine as that is still the recommended way to publish libraries for compatibility. If the library is not publishable, we should remove this file right?

**Comment by brandonroberts** [comment]
Yes, that's correct. I believe that file was introduced in Angular v9 through the upstream library schematic.
