### ISSUE TITLE
Cypress fails to close

### ISSUE THREAD

**Issue by Capocaccia** [nrwl/nx#27658]
### Current Behavior

  When Cypress is run in "watch mode", the UI appears. When you try to exit this process via the command line, Cypress does not close and the UI stays in place.

### Expected Behavior

When Cypress is run in "watch mode", the UI appears. When you try to exit this process via the command line, the UI closes and the Cypress process is exited appropriately.

### GitHub Repo

https://github.com/Capocaccia/nxCypress

### Steps to Reproduce

1. Clone the repo attached
2. Execute the following command `npx nx open-cypress cypressExample-e2e`
3. Wait for the Cypress UI to appear
4. In the terminal where the command from step 2 was executed, press Control+C to exit the process
5. Note how the Cypress UI remains present.

### Nx Report

```shell
Node           : 20.16.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.8.1

nx                 : 19.6.3
@nx/js             : 19.6.3
@nx/jest           : 19.6.3
@nx/linter         : 19.6.3
@nx/eslint         : 19.6.3
@nx/workspace      : 19.6.3
@nx/cypress        : 19.6.3
@nx/devkit         : 19.6.3
@nx/eslint-plugin  : 19.6.3
@nx/react          : 19.6.3
@nrwl/tao          : 19.6.3
@nx/web            : 19.6.3
@nx/webpack        : 19.6.3
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/cypress/plugin
@nx/jest/plugin
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Screen recording of issue is attached

https://github.com/user-attachments/assets/92f52831-1cd4-49f9-a934-8e4e7e91da4d

**Comment by Coly010** [comment]
@Capocaccia In the directory containing your `cypress.config` file, can you run:

`npx cypress open`

then try to close it as you have been, with `Ctrl + C` and let me know if the UI closes?

In the command you have run, all we've done is open a new process that runs `cypress open`, so behaviour should controlled by cypress itself rather than us. I'm curious to see if cypress ui is closing as you'd expect when you invoke cypress directly.

This would indicate that we're not sending an event through correctly to the child process.

**Comment by Capocaccia** [comment]
@Coly010 When I followed the instructions in your message the Cypress UI did close correctly. See attached screen recording.

https://github.com/user-attachments/assets/5fe33ef0-b35d-42cb-8f53-51a0c2fda532

**Comment by Capocaccia** [comment]
Interesting! Thats really helpful to know. Definitely gives me a direction to go in and therefore I will close this issue for now.
