### ISSUE TITLE
[Feature Request] Don't kill entire process tree in @nrwl/node:execute

### ISSUE THREAD

**Issue by pcafstockf** [nrwl/nx#2766]
Would it be of interest to the Nx team if I were to submit a PR allowing for a configuration option instructing @nrwl/node:execute **not** to kill the entire subProcess tree?

## Expected Behavior

Our app contains code to **cleanly** shutdown any child processes that it launches.  We need @nrwl/node:execute to send SIGTERM **only** to our app (pid), which will then manage the shutdown of it's own child processes (if any).

## Current Behavior

Currently @nrwl/node:execute attempts to SIGTERM all processes itself, which causes us no end of grief (it actually prevents restart when we are developing with nx serve).

### Context

  @nrwl/node : 9.1.4

## Other

I'm new to nx, but it looks like the option could be added to NodeExecuteBuilderOptions.  I'd need to do a little research on the specifics of tree-kill.

**Comment by FrozenPandaz** [comment]
Sorry, it's hard to understand the issue without a repo to look at.

For clarification, is the ask to _only_ send SIGTERM to the process that `@nrwl/node:execute` starts rather than the whole process tree and for the node application to handle it's own child processes?

**Comment by pcafstockf** [comment]
> For clarification, is the ask to _only_ send SIGTERM to the process that `@nrwl/node:execute` starts rather than the whole process tree and for the node application to handle it's own child processes?

Yes.
