### ISSUE TITLE
[Question] NX for non-js apps

### ISSUE THREAD

**Issue by brunobertechini** [nrwl/nx#2767]
[Question]
Can we use nrwl/nx and add applications for dotnetcore/java even if we don't have any plugin? Just for the sake of having everything in the same monorepo?

Looking for best practices/guidance.

Bruno

**Comment by brunobertechini** [comment]
The issue im facing is: I would like increase the usage of  nrwl/nx for my company and I was looking for a way to create an "empty project" where I can add source code from PHP, dotnet core, docker etc

One goal/monorepo only.

**Comment by santino83** [comment]
Maybe you could write schematics to preconfiugre folders to handle a php/java/dotnet project inside your monorepo... eg, you could have apps/libs and a new backend, with inside java/dotnet/php etc... then, those languages has their own package manager and ways to create and handle monorepos, you should add your own commands to npm or schematics. By hand, you could do it today by create a folder with a new maven pom project, than you could add some scripts to package.json to run java commands against the pom. Is it useful? Personally, I don't like mixing together frontend and backend projects as this layers can be highly decoupling by api contracts

**Comment by brunobertechini** [comment]
Hi @santino83 I will try to find documentation about that. Thanks!

**Comment by Chris2011** [comment]
Hey @brunobertechini I'm also interested in this concept, did you already find smth? My use case is that I have some Apache NetBeans maven plugins, that I would like to collect in a monorepo and also some Vue based UIs for the GUI of the plugins to have them in the same repo.

**Comment by AMorgaut** [comment]
Also interested for our project which has a several PHP backends

**Comment by MKashifSarbazi** [comment]
Does nx support php laravel?

**Comment by lordjoo** [comment]
Does any one find any solution ?

**Comment by prodkt** [comment]
This really is only for JS Frameworks? No PHP?
