### ISSUE TITLE
Make it easier to run jest tests for single file with vs code

### ISSUE THREAD

**Issue by leon** [nrwl/nx#2768]
## Expected Behavior
Allow me to go into .spec.ts file and press "Run Jest for Current File"

Please describe the behavior you are expecting

## Current Behavior
In vs code we can pass in the current file that should be tested.
but I always need to pass in the lib or else jest will run all my tests before the debugger stopping on my file.

This makes it very hard to get started with debugging your libs.

## Proposal
we could add a helper method to nx, that will return the lib / app name for the current file.
that way we could pass this in as the lib name in launch.json.

or we could add a test-file command which would do this for us.

# Wallaby
I'm also using wallaby, and you have the same problem there, where you first need to specify which lib directory you want to run.

## Going forward
If we can discuss what the best solution would be. I will be happy to implement it.

**Comment by barbados-clemens** [comment]
If you're wanting to just click a button and run a single file using a vscode extension is the best way to go. this is the one we recommend https://marketplace.visualstudio.com/items?itemName=firsttris.vscode-jest-runner

you can also just use the jest cli to run a single file as we try to keep that compatibility for reasons like this.

**Comment by igor-q-bio** [comment]
@leon Do you know if this still an issue with the Wallaby?
