### ISSUE TITLE
Change detection working in one app and not working in other app using same component

### ISSUE THREAD

**Issue by NavneetVaid** [nrwl/nx#27694]
### Current Behavior

Hi, I have Nx Mono repo architecture, i have two components which are present inside libs. I have two apps referring to the same components. In one app all works fine and in the other app the change detection of angular is not working properly for both components. I have to manually trigger click or any other event to make change detection work. What might be the issue ?

### Expected Behavior

It should work in same way for both apps

### Steps to Reproduce

1.

### Nx Report

```shell
N.A
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
There isn't enough info in this issue. I'm assuming it's an Angular app, and may not be an Nx issue.

If you still have a problem, please open a new issue with a repro that we can check. Thanks.
