### ISSUE TITLE
NX Command Fails with "Compiling Terminating" When Running nx run-many --target=serve

### ISSUE THREAD

**Issue by Sami-80** [nrwl/nx#27690]
### Current Behavior

![image (8)](https://github.com/user-attachments/assets/2a250e6c-295e-454c-8053-e7d72b1850f8)

When executing the command nx run-many --target=serve, the process terminates with no error. The same project runs normally when using Node.js and Angular directly, indicating that the issue may be specific to NX.

### Expected Behavior

The command nx run-many --target=serve should execute successfully and start the development server for the project without errors.

### Steps to Reproduce

1 .Open a terminal or command prompt.
2 .Navigate to the root directory of your NX workspace.
3 .Run the command: nx run-many --target=serve.
4. Observe no error message and termination of the process.

### Nx Report

```shell
Node : 18.17.0
   OS   : win32 x64
   npm  : 9.6.7

   nx : 15.0.2
   @nrwl/angular : 15.0.2
   @nrwl/cypress : 15.0.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.2
   @nrwl/expo : Not Found
   @nrwl/express : 15.0.2
   @nrwl/jest : 15.0.2
   @nrwl/js : 15.0.2
   @nrwl/linter : 15.0.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.0.2
   @nrwl/nx-cloud : 19.0.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.2
   @nrwl/web : Not Found
   @nrwl/webpack : 15.0.2
   @nrwl/workspace : 15.0.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @syncfusion/ej2-angular-richtexteditor: 19.4.56
         ng-zorro-antd: 14.3.0
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by maksof-osama** [comment]
Just remove runner from nx.json file

  "tasksRunnerOptions": {
    "default": {
      "options": {
        "cacheableOperations": ["build", "lint", "test", "e2e"],
      }
    }
  },

**Comment by jaysoo** [comment]
Closing this as it shouldn't be an issue in the latest version, and v15 is not in LTS.
