### ISSUE TITLE
Adding Storybook Configuration does not install @storybook/core

### ISSUE THREAD

**Issue by ChazUK** [nrwl/nx#2770]
- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Adding Storybook to an Angular UI Library should install all relevant libraries.

## Current Behavior

Trying to follow documentation which appears to be out of date or missing steps https://nx.dev/angular/plugins_storybook/overview. After installing `@nrwl/angular` and `@nrwl/storybook` and running the setup commands, `@storybook/core` is not added to package.json.

## Failure Information (for bugs)

```
An unhandled exception occurred: Cannot find module '@storybook/core/dist/server/build-dev'
See "/private/var/folders/05/x3k8qmdn1476r6yvkmchxnw40qmf92/T/ng-iFJ1jL/angular-errors.log" for further details.
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `npx create-nx-workspace@latest workspace` Created an empty workspace
2. `cd workspace`
3. `npm install --save-dev @nrwl/angular`
4. `ng g @nrwl/angular:lib ui`
5. `ng g @nrwl/angular:application dummy-app` _(have to install dummy app to be able to use angular-cli even tho I've created an angular library)_
6. `ng g component skip-link --project=ui --export` Creating first component
7. `npm install --save-dev @nrwl/storybook`
8. `ng g @nrwl/angular:storybook-configuration ui` or `ng g @nrwl/storybook:configuration --name=ui --configureCypress --uiFramework=@storybook/angular` Which of these should be used?
9. `ng run ui:storybook`
10. Error occurs

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context

```
  "dependencies": {
    "@angular/animations": "9.0.0",
    "@angular/common": "9.0.0",
    "@angular/compiler": "9.0.0",
    "@angular/core": "9.0.0",
    "@angular/forms": "9.0.0",
    "@angular/platform-browser": "9.0.0",
    "@angular/platform-browser-dynamic": "9.0.0",
    "@angular/router": "9.0.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.0",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.900.1",
    "@angular/cli": "9.0.1",
    "@angular/compiler-cli": "9.0.0",
    "@angular/language-service": "9.0.0",
    "@babel/core": "7.8.3",
    "@nrwl/angular": "^9.1.4",
    "@nrwl/cypress": "9.1.4",
    "@nrwl/jest": "9.1.4",
    "@nrwl/storybook": "*",
    "@nrwl/workspace": "9.1.4",
    "@storybook/addon-knobs": "5.3.9",
    "@storybook/angular": "5.3.9",
    "@storybook/react": "5.3.9",
    "@types/jest": "24.9.1",
    "@types/node": "~8.9.4",
    "babel-loader": "8.0.6",
    "codelyzer": "~5.0.1",
    "cypress": "^4.1.0",
    "dotenv": "6.2.0",
    "eslint": "6.8.0",
    "jest-preset-angular": "8.0.0",
    "jest": "24.9.0",
    "prettier": "1.19.1",
    "ts-jest": "24.0.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.0.0",
    "typescript": "~3.7.4"
  }
```

**Comment by FrozenPandaz** [comment]
Your steps are correct. There was a bug before so either try again with the latest version or maybe you need to do an npm install after step 8? In step 8, the command that should be used is `ng g @nrwl/angular:storybook-configuration ui`

**Comment by ChazUK** [comment]
Followed the same steps and Storybook launches, but I'm getting this error when opening it in the browser on first run. But not on second run so 👍, Thank you for the quick response.

```
Error: ENOENT: no such file or directory, stat '/Users/uut1/repos/europe-core/node_modules/@storybook/core/dist/public/iframe.html/runtime~main.9e110037fd5c6d10ab04.bundle.js'
Error: ENOENT: no such file or directory, stat '/Users/uut1/repos/europe-core/node_modules/@storybook/core/dist/public/iframe.html/vendors~main.9e110037fd5c6d10ab04.bundle.js'
Error: ENOENT: no such file or directory, stat '/Users/uut1/repos/europe-core/node_modules/@storybook/core/dist/public/iframe.html/main.9e110037fd5c6d10ab04.bundle.js'
```

**Comment by ChazUK** [comment]
This is my updated `package.json`
```
  "dependencies": {
    "@angular/animations": "9.1.0",
    "@angular/common": "9.1.0",
    "@angular/compiler": "9.1.0",
    "@angular/core": "9.1.0",
    "@angular/forms": "9.1.0",
    "@angular/platform-browser-dynamic": "9.1.0",
    "@angular/platform-browser": "9.1.0",
    "@angular/router": "9.1.0",
    "@nrwl/angular": "9.2.1",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.4",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.901.0",
    "@angular/cli": "9.1.0",
    "@angular/compiler-cli": "9.1.0",
    "@angular/language-service": "9.1.0",
    "@babel/core": "7.8.3",
    "@nrwl/cypress": "9.2.1",
    "@nrwl/jest": "9.2.1",
    "@nrwl/storybook": "^9.2.1",
    "@nrwl/workspace": "9.2.1",
    "@storybook/addon-knobs": "5.3.9",
    "@storybook/angular": "5.3.9",
    "@storybook/react": "5.3.9",
    "@types/jest": "25.1.4",
    "@types/node": "~8.9.4",
    "babel-loader": "8.0.6",
    "codelyzer": "~5.0.1",
    "cypress": "^4.1.0",
    "dotenv": "6.2.0",
    "eslint": "6.8.0",
    "jest-preset-angular": "8.1.2",
    "jest": "25.2.3",
    "prettier": "1.19.1",
    "ts-jest": "25.2.1",
    "ts-node": "~7.0.0",
    "tslint": "~6.0.0",
    "typescript": "~3.8.3"
  }
```
