### ISSUE TITLE
nx release plan:check did not return a non-zero exit code when version plan file does not exist

### ISSUE THREAD

**Issue by wood3n** [nrwl/nx#27739]
### Current Behavior

run `nx release plan:check` in github actions, it prints `No touched projects found based on changed files` but no exit ci.

### Expected Behavior

I want that it will automatically exit from ci when version plan was not found after run `nx release plan:check`.

### GitHub Repo

https://github.com/wood3n/fe-kit

### Steps to Reproduce

just see this actions step: https://github.com/wood3n/fe-kit/actions/runs/10682748546/job/29609306239#step:6:2

### Nx Report

```shell
Node           : 20.17.0
OS             : ubuntu-22.04
pnpm           : 8.15.9

nx             : 19.6.2
@nx/js         : 19.6.2
@nx/workspace  : 19.6.2
@nx/devkit     : 19.6.2
@nrwl/tao      : 19.6.2
typescript     : 5.5.4
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by wood3n** [comment]
> @wood3n What you have linked to is a success case - you do not have any relevant changes which require a version plan. Therefore the command is appropriately exiting with code zero.
> 
> Could it be that this is more a question of how to find the relevant changes for a particular run?
> 
> Right now I see you are not setting `--base` and `--head` (or `NX_BASE` and `NX_HEAD`) which is likely why you are not seeing what you expect.
> 
> First things first, please can you clarify what relevant changes you were expecting to see?

**Comment by wood3n** [comment]
@JamesHenry thanks for your reply. 

I just see this description in official document:

<img width="993" alt="image" src="https://github.com/user-attachments/assets/313ad609-c121-42e6-b8de-f94c81901bb5">

So I want to use `nx release plan:check` to check whether it should run next command such as `npx nx release` in github actions.

**Comment by JamesHenry** [comment]
@wood3n It's fair that we don't call out the CI specific concerns there, I'll update the docs.

It works the same way as it does for `nx affected`, if you are familiar with that. You need to inform Nx about the range you care about for changes.

You can add our action to your workflow before you run your nx commands:

```yaml
      - uses: nrwl/nx-set-shas@v4
```

This will set NX_BASE and NX_HEAD for you in your workflow.

If you still see unexpected behaviour after that feel free to open an issue

**Comment by JamesHenry** [comment]
https://github.com/nrwl/nx/pull/27784
