### ISSUE TITLE
Documentation Error: Recipes > Module Federation >  Create A Host

### ISSUE THREAD

**Issue by davidsilva2841** [nrwl/nx#27746]
### Documentation issue

- [ ] Reporting a typo
- [x ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/recipes/module-federation/create-a-host

### Additional context or description
Followed the steps in the documentation here and they do not work

**Comment by Coly010** [comment]
@davidsilva2841 Can you provide any more information at all?

What part of it didnt work?
Which command?
Did you run it in an Nx workspace?
What version were you using?
What error message did you see?
