### ISSUE TITLE
workspace/command-line: dep-graph renders weird dependency tree

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#2778]
## Expected Behavior

properly resolve dep graph

## Current Behavior

`workspace-tools` isn't used anywhere - it's default nx `./tools` folder registered within `workspace.json` se we are be able to leverage nx for running pipeline for `./tools` as well (schematics/scripts/builders).

- Am I missing something within configs ? 
- How is the dep graph being  build under the hood? (would be easier to know to be able to debug this)

![image](https://user-images.githubusercontent.com/1223799/78059151-ad188300-7389-11ea-81bd-2a4d1560f007.png)

**workspace.json:**

```json
 "projects": {
    "workspace-tools": {
      "root": "tools",
      "sourceRoot": "tools",
      "projectType": "library",
      "schematics": {},
      "architect": {
        "lint": {
          "builder": "@nrwl/linter:lint",
          "options": {
            "linter": "eslint",
            "config": "tools/.eslintrc",
            "fix": true,
            "tsConfig": ["tools/tsconfig.tools.json"],
            "exclude": ["**/node_modules/**"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "tools/jest.config.js",
            "tsConfig": "tools/tsconfig.spec.json",
            "passWithNoTests": true
          }
        }
      }
    },
}
```

**nx.json:**

```json
{
"npmScope": "my-project",
  "implicitDependencies": {
    "workspace.json": "*",
    "package.json": {
      "dependencies": "*",
      "devDependencies": "*"
    },
    "tsconfig.json": "*",
    "tslint.json": "*",
    "nx.json": "*"
  },
  "projects": {
    "workspace-tools": {
      "tags": []
    },
  }
}
```

**.eslintrc.js:**
```js
rules: {
    '@nrwl/nx/enforce-module-boundaries': [
      'error',
       {
        allow: [
          // "old" codebase within src/js/libs - it's mapped within tsconfig.json "paths"
          'libs/**',
          // "old" codebase within apps/ui/ - ui needs be moved to proper package within lib
          'apps/ui/**',
          // "old packages, without nx support"
          '@my-project/ui/**',
          '@my-project/globals',
        ],
        depConstraints: [
          // Projects without any tags cannot depend on any other projects.
          // Following allows projects without any tags to be able to depend on any other project.
          {
            sourceTag: '*',
            onlyDependOnLibsWithTags: ['*'],
          },
       ]
}]
}
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `yarn nx dep-graph`

### Context

```
 @nrwl/angular : Not Found
  @nrwl/cli : 9.1.2
  @nrwl/cypress : 9.1.2
  @nrwl/eslint-plugin-nx : 9.1.2
  @nrwl/express : Not Found
  @nrwl/jest : 9.1.2
  @nrwl/linter : 9.1.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.1.2
  @nrwl/react : 9.1.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.1.2
  @nrwl/web : 9.1.2
  @nrwl/workspace : 9.1.2
  typescript : 3.8.3
```

**Comment by FrozenPandaz** [comment]
Sorry, it's difficult to know why `dep-graph` is showing this without a repo to clone. Please provide a repo so I can help debug the reason why those dependencies are drawn.

**Comment by Hotell** [comment]
> Sorry, it's difficult to know why `dep-graph` is showing this without a repo to clone. Please provide a repo so I can help debug the reason why those dependencies are drawn.

yeah I'd love to, but it's whole product code, where is a tons of obsolete code with various circular dependencies -> that's what I'm migrating to nx gradually. So it's under NDA, I don't think I can reproduce it manually (5k+ files)

**Comment by Hotell** [comment]
one thing I found out is that `dep-graph` is having problems if project uses scoped packages under same namespace which are not registered within `workspace.json`

for instance:

```
// @my-proj/foo is not registered within workspace.json
import {foo} from '@my-proj/foo'
// @my-proj/nx is registered within workspace.json
import {nxFoo} from '@my-proj/nx'
```

when I migrated/registered `@my-proj/foo` within `workspace.json`, it resolved dep graph for that package.

That's why I was asking how is the resolution being done (high overview), so I could solve it on my own and share those findings here.

**Comment by juristr** [comment]
Hey @Hotell 👋 . Surprisingly I had the exact same issue yesterday also embedding the tools folder as `workspace-tools` in the `angular.json`.

Talked to Jason and I think we found it. Jason has a PR (#2789) that might fix it. Gonna test it now on my workspace.

In general, thanks a lot for all ur detailed issues/feature requests you provide here. Awesome job :)

**Comment by Hotell** [comment]
you're the best folks! ❤️hope I will have more time to contribute more soon - in terms of PR etc. 🙌keep rockin
