### ISSUE TITLE
Nx Vite build not cached out of the box

### ISSUE THREAD

**Issue by Shuunen** [nrwl/nx#27785]
### Current Behavior

The default `outputs` of the build target generated by Nx Vite is not cached.

The build works, if I run the build target a second time, nx says it read the cache successfully

But if I `rm dist -rf` and run the build again, my project previous build does not appears in `dist`.

After investigation I found out the issue was **slash & backslash in outputs path** and probably only related to Windows environements.

### Expected Behavior

The vite project should be cached correctly out of the box.

### Steps to Reproduce

1. On Windows (I think it's the old story between windows & unix path handling) generate a nx monorepo
2. Generate a vite library or app, here for the example let's say `libs/ui`
3. By default we can see that the `outputs` contain `{workspaceRoot}\dist\libs\ui` (see screenshot attached)
4. Run `nx build ui`, it works and generate as expected a build in `{workspaceRoot}\dist\libs\ui`
5. Run again and see that Nx says is re-used the previously cached build
6. Delete dist folder `rm dist -rf` and run `nx build ui` again
7. The expected build in `{workspaceRoot}\dist\libs\ui` is not there
8. Edit the `libs/ui/project.json` and customise build target by adding `"build": { "outputs": [ "{workspaceRoot}/dist/libs/ui"  ]  },` **note here that the only thing that change is that we are now using slashes instead of backslashes**
9. Build, delete dist and build again, now `{workspaceRoot}\dist\libs\ui` exists, the cache is now working as expected

![2024-09-05 11_44_39-ui Details - monorepo - Visual Studio Code](https://github.com/user-attachments/assets/7b818946-e664-4d58-8fae-ffde36f15668)

### Nx Report

```shell
Node           : 20.14.0
OS             : win32-x64
Native Target  : x86_64-windows
pnpm           : 8.15.9

nx (global)        : 19.6.1
nx                 : 19.6.1
@nx/js             : 19.6.1
@nx/eslint         : 19.6.1
@nx/workspace      : 19.6.1
@nx/eslint-plugin  : 19.6.1
@nx/nest           : 19.6.1
@nx/node           : 19.6.1
@nx/react          : 19.6.1
@nx/storybook      : 19.6.1
@nx/vite           : 19.6.1
@nx/web            : 19.6.1
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/vite/plugin
@nx/storybook/plugin
---------------------------------------
Community plugins:
@nx-tools/nx-container : 6.0.2
@nx/rspack             : 19.5.0
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Can you try this again on latest version of nx (20)?
