### ISSUE TITLE
Unable to generate code coverage report

### ISSUE THREAD

**Issue by chr1soscl** [nrwl/nx#2783]
Hello,
Recently we are experiencing an issue with the code coverage report, it is coming out empty, it is showing all the classes but the percentages are empty, these are my dev dependencies:
```
"@angular-devkit/build-angular": "^0.803.23",
    "@angular/cli": "8.0.0",
    "@angular/compiler-cli": "^8.0.0",
    "@angular/language-service": "^8.0.0",
    "@nrwl/jest": "8.1.0",
    "@nrwl/workspace": "8.1.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/jest": "24.0.9",
    "@types/node": "~8.9.4",
    "codelyzer": "~5.0.1",
    "dotenv": "6.2.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "jest": "24.1.0",
    "jest-junit": "7.0.0",
    "jest-preset-angular": "^7.1.1",
    "jest-zone-patch": "0.0.10",
    "prettier": "1.16.4",
    "protractor": "~5.4.0",
    "ts-jest": "24.0.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.4.5"
```
and this is my jest configuration:
```
module.exports = {
  testMatch: ['**/+(*.)+(spec|test).+(ts|js)?(x)'],
  transform: {
    '^.+\\.(ts|js|html)$': 'ts-jest'
  },
  resolver: '@nrwl/jest/plugins/resolver',
  moduleFileExtensions: ['ts', 'js', 'html'],
  collectCoverage: true,
  coverageReporters: ['html','json','text','cobertura','lcov'],
  reporters: [ 'default', 'jest-junit' ]  
};

```
![CodeCoverage](https://user-images.githubusercontent.com/43754109/78155062-fd83f500-740a-11ea-9410-7d858cc90ec4.PNG)

**Comment by FrozenPandaz** [comment]
Hi, is it possible for you to provide a repo with a minimal replication of the issue?

I tested this on https://github.com/nrwl/nx-examples by running `nx test cart --code-coverage` and had a proper coverage report generated. Is it possible that adding some of the other code coverage reporters corrupted the html coverage? Are the other coverage reports generated properly?

**Comment by ahnpnl** [comment]
Hi guys, for this issue pls follow this https://www.instagram.com/p/B-poAHiHH5Q/?igshid=13hjw2rw5awxw

**Comment by ahnpnl** [comment]
Hi guys for this issue pls follow this https://github.com/facebook/jest/issues/5739

**Comment by FrozenPandaz** [comment]
https://github.com/facebook/jest/issues/5739 is now closed and we don't have a repro in over a month so I'm going to close this issue. If you continue to run into this the issue please open a new issue with a repo exhibiting the behavior.
