### ISSUE TITLE
[Angular] [Module Federation] nx-angular-mf duplicated in vendor.js and library module

### ISSUE THREAD

**Issue by pcurrivan** [nrwl/nx#27842]
### Current Behavior

After upgrading an Nx MF Angular app to Nx 19.6.6, Angular 18, etc., I see this error when calling `loadRemoteModule`:

`TypeError: Cannot read properties of undefined (reading 'endsWith')`

Looking in the dev tools, it looks like the `nx-module-mf.mjs` module is included twice: in vendor.js as well as in the chunk for the Angular library project that uses the loadRemoteModule function.

In my app, I call `setRemoteDefinitions` before Angular bootstrap, and then I call `loadRemoteModule` after bootstrap (dynamic plugin system).

It seems like `remoteUrlDefinitions` is correctly populated before bootstrap, but then the library chunk loads after bootstrap and resets `remoteUrlDefinitions` to `{}`.  So when I call `loadRemoteModule`, `remoteUrl` ends up undefined, causing the error.

### Expected Behavior

`nx-module-mf.mjs` shouldn't be duplicated at runtime and `loadRemoteModule` should find the remote definitions set before bootstrap with `setRemoteDefinitions`

### Steps to Reproduce

1. Create an MFE host and remote
2. call `setRemoteDefinitions` in main.ts before bootstrap
3. create a library that uses `loadRemoteModule`
4. call `loadRemoteModule` via the library after bootstrap

### Nx Report

```shell
Node: 20.16.0
npm: 10.8.1

nx: 19.6.6
typescript: 5.5.4

Community Plugins:
ngx-build-plus: 18.0.0
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by hakalb** [comment]
I tried the fix but I don't think the main issue is solved. Now there's just another console error.
![image](https://github.com/user-attachments/assets/9337767a-7a06-4d90-8163-a1a092ce74b3)

Still there must be duplicate instances.

A workaround is to make sure `setRemoteDefinitions` (or `setRemoteUrlResolver`) is located in the same project as `loadRemoteModule` to end up in the same bundle file.

Looks like it's also possible to add `@nx/angular/mf` to `additionalShared` in `module-federation.config.js` for the host application.

**Comment by pcurrivan** [comment]
I can confirm I now get the same error as @hakalb on Nx 19.8.0.  However, I have not been able to work around the issue with an additionalShared entry.  @hakalb could you share the exact additionalShared entry that worked for you?  I tried the following entry (also tried without eager):

```
{
      libraryName: '@nx/angular/mf',
      sharedConfig: { singleton: true, eager: true },
}
```

This resulted in this error:

```
loadShareSync failed! The function should not be called unless you set "eager:true". If you do not set it, and encounter this issue, you can check whether an async boundary is implemented.

The original error message is as follows: 

index.cjs.js:1426 Uncaught Error: 
        The loadShareSync function was unable to load @nx/angular/mf. The @nx/angular/mf could not be found in <frontend app name>.
        Possible reasons for failure: 

        1. The @nx/angular/mf share was registered with the 'get' attribute, but loadShare was not used beforehand.

        2. The @nx/angular/mf share was not registered with the 'lib' attribute.
``` 

Restricting my use of @nx/angular/mf to only one Nx project is not really an acceptable workaround for my project.

@Coly010 Want me to make a new ticket or can this one be reopened?

**Comment by hakalb** [comment]
I tried this to get it to work before I restricted the usage to only the host application.

Nx version 19.7.4.

```ts
// module-federation.config.ts

import type { ModuleFederationConfig } from '@nx/webpack';

const config: ModuleFederationConfig = {
  name: 'app-host',
  remotes: [],
  additionalShared: [
    {
      libraryName: '@nx/angular/mf',
      sharedConfig: {}. // also worked with your settings
    }
  ]
};

export default config;
```

```ts
// webpack.config.ts

import { withModuleFederation } from '@nx/angular/module-federation';

import moduleFederationConfig from './module-federation.config';

export default withModuleFederation(moduleFederationConfig, { dts: false });
```

I invoke the function just before application bootstrap.

```ts
// bootstrap.ts (not all code)

const bootstrap = () => {
  return setupApplication(appRoutes).then(({ providers, remoteDefs }) => {
    setRemoteDefinitions(remoteDefs);
    return bootstrapApplication(AppComponent, { providers });
  });
};

composeAsync(swUnregisterDeprecatedApps, bootstrap)().catch((error) => {
  bootstrapApplication(FailoverComponent);
});
```

**Comment by pcurrivan** [comment]
@Coly010 
My reproduction steps were not quite correct.  You also need a lazy-loaded feature module to reproduce the issue.  I've created a new reproduction repo: https://github.com/pcurrivan/nx-dyn-mf

Here are the new steps to reproduce:

- Clone the repo 
- `npm install`
- `npx serve host`
- Open browser and see error: 'Error: Call setRemoteDefinitions or setRemoteUrlResolver to allow Dynamic Federation to find the remote apps correctly.'

**Comment by Ginetti** [comment]
I'm facing exactly the same issue.

Using the loadRemoteModule from the app works fine, but when it's called from a lazy-loaded feature library, the error mentioned by @pcurrivan appears.

I tried upgrading nx to the latest version, but it didn't resolve the issue.

**Nx Report**

```
Node           : 20.18.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.9.0

nx                 : 20.0.9
@nx/js             : 20.0.9
@nx/jest           : 20.0.9
@nx/eslint         : 20.0.9
@nx/workspace      : 20.0.9
@nx/angular        : 20.0.9
@nx/devkit         : 20.0.9
@nx/eslint-plugin  : 20.0.9
@nx/plugin         : 20.0.9
@nx/web            : 20.0.9
@nx/webpack        : 20.0.9
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
```

@Coly010 is it possible to reopen the issue ?

**Comment by Erbenos** [comment]
I am facing the same issue.

```
{
      libraryName: '@nx/angular/mf',
      sharedConfig: { singleton: true, eager: true },
}
```

To the federation config of the host whose loadRemoteModule fails with 

```
 Error: Call setRemoteDefinitions or setRemoteUrlResolver to allow Dynamic Federation to find the remote apps correctly.
```

Works around it.

NX Report:

```
miroslavfoltyn$ npx nx report

 NX   Report complete - copy this into the issue template

Node           : 22.1.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.7.0

nx                 : 20.0.7
@nx/js             : 20.0.7
@nx/jest           : 20.0.7
@nx/eslint         : 20.0.7
@nx/workspace      : 20.0.7
@nx/angular        : 20.0.7
@nx/cypress        : 20.0.7
@nx/devkit         : 20.0.7
@nx/eslint-plugin  : 20.0.7
@nx/nest           : 20.0.7
@nx/node           : 20.0.7
@nx/plugin         : 20.0.7
@nx/storybook      : 20.0.7
@nx/web            : 20.0.7
@nx/webpack        : 20.0.7
typescript         : 5.5.4
---------------------------------------
<omitting community and local plugins>
```
