### ISSUE TITLE
Azure DevOps Pipeline failing because of cloud integration

### ISSUE THREAD

**Issue by DavidVollmers** [nrwl/nx#27848]
### Current Behavior

So for some reason running nx build ... fails in Azure DevOps Pipelines with the following error message:
`Nx Cloud: Workspace is disabled`

While locally it just puts out a warning:
`This Nx Cloud organization has been disabled due to exceeding the FREE plan.`

This is the worse kind of paywall behavior I can imagine. Thank you for interrupting development work in pipelines but not locally. I will never ever even think about paying money for a solution which acts this violently.

The solution to this obviously is to disable the cloud integration completely :)

### Expected Behavior

.

### Steps to Reproduce

1. Use NX
2. Run out of free credits
3. Hate NX Cloud integration

### Nx Report

```shell
.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by StalkAltan** [comment]
Hi! Sorry that the error comes as a surprise!

Nx Cloud warns organization admins via email at 50, 75, 90, and 100% thresholds of usage limits that exceeding the limits will result in disablement. We're always interested in making sure your usage allowances more obvious, and are open to suggestions on how this could have been surfaced better.

**Comment by DavidVollmers** [comment]
But this does not explain why running nx still works locally but not in a pipeline. Why is there a warning locally but an error in the pipeline?

**Comment by KotaHarmon** [comment]
We don't get any errors from NX, but we do get a warning locally and in our build pipeline that says:

`Nx Cloud: Workspace is disabled`

Nothing about running out of a threshold on our end. Would be great to receive a better error message than:

`##[error]Error: Npm failed with return code: 1`

The only thing we can determine is blocking us is NX Cloud and we setup an account and connected our VCS, but our pipeline is still failing and only outputting that stupid error code 1 message.

Most likely we will be removing nx from all projects if this is going to be a persisting issue.

**Comment by DavidVollmers** [comment]
@KotaHarmon You don't need to remove nx from your project. Just remove the cloud integration (remove the access token from the `nx.json` file.

This behavior is clearly intended to push people into paying for the cloud integration (paywall), which is a really deconstructive thing to do!

**Comment by KotaHarmon** [comment]
Yup, we did that and got it working. We also made use of the following cli commands:
`--skip-nx-cache NX_NO_CLOUD=true`

Appreciate the follow-up @DavidVollmers!
