### ISSUE TITLE
Vitest won't resolve Path aliases in nx 19.7.2, 19.7.1, 19.7.0 and 19.6.6

### ISSUE THREAD

**Issue by jahusa02** [nrwl/nx#27852]
### Current Behavior

Vitest will fail with 

`Error: Failed to load url @test/other-things/things-things.controller (resolved id: @test/other-things/things-things.controller) in /workspace/vitest/apps/vitest-test/src/things/stuff/bla.mapper.spec.ts. Does the file exist?
 ❯ loadAndTransform ../../node_modules/.pnpm/vite@5.4.3_@types+node@18.16.20/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:51847:17`
 
 in 19.6.5 it will run fine tho. Please help because that will halt us from updating.

### Expected Behavior

Should resolve Path aliases

### GitHub Repo

https://github.com/jahusa02/nx-19.7.0-vitest

### Steps to Reproduce

1. run `nx test vitest-test`

### Nx Report

```shell
Node           : 20.16.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.10.0

nx (global)        : 19.7.0
nx                 : 19.7.0
@nx/js             : 19.7.0
@nx/jest           : 19.7.0
@nx/eslint         : 19.7.0
@nx/workspace      : 19.7.0
@nx/esbuild        : 19.7.0
@nx/eslint-plugin  : 19.7.0
@nx/node           : 19.7.0
@nrwl/tao          : 19.7.0
@nx/vite           : 19.7.0
@nx/web            : 19.7.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/vite/plugin
```

### Failure Logs

```shell
Error: Failed to load url @test/other-things/things-things.controller (resolved id: @test/other-things/things-things.controller) in /workspace/vitest/apps/vitest-test/src/things/stuff/bla.mapper.spec.ts. Does the file exist?
 ❯ loadAndTransform ../../node_modules/.pnpm/vite@5.4.3_@types+node@18.16.20/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:51847:17
```

### Package Manager Version

pnpm@9.10.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by egonm12** [comment]
I have the same problem and suspect it might be related to this change, but I don't have the time to confirm this atm: https://github.com/nrwl/nx/pull/27774

**Comment by 0xd0a** [comment]
@egonm12 Yes, you are correct. 

The culprit is 
https://github.com/nrwl/nx/blob/7c79f2aa19f867552c446189598f3d0581641ded/packages/vite/plugins/nx-tsconfig-paths.plugin.ts#L255

If the file name consists of several segments separated with dots the "parse" will erroneously  consider it an extension.

For example
```ts
import { a } from "./app.controller";
```
*controller* is obviously not an extension.

So #27774 has to be reconsidered.

**Comment by roshcagra** [comment]
Hi! I'm running into this too while attempting to upgrade to 19.8.2 :(

Is there a known workaround or should I wait for a fix before upgrading?
