### ISSUE TITLE
serve-static target should not be created without e2e config

### ISSUE THREAD

**Issue by DariusPa** [nrwl/nx#27854]
### Current Behavior

1. Generate new application without e2e config: `nx g @nx/angular:application app123 --directory apps --bundler=esbuild --ssr=false --projectNameAndRootFormat=derived`
2. Generated app **GENERATES** serve-static target under project.json even though I haven't passed e2eTestRunner flag

### Expected Behavior

1. Generate new application without e2e config: `nx g @nx/angular:application app123 --directory apps --bundler=esbuild --ssr=false --projectNameAndRootFormat=derived`
2. Newly created app **SHOULD NOT** generate serve-static target under project.json if e2eTestRunner flag is not passed

### Steps to Reproduce

1. nx g @nx/angular:application app123 --directory apps --bundler=esbuild --ssr=false --projectNameAndRootFormat=derived

### Nx Report

```shell
Node           : 18.17.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.1.0

nx (global)        : 17.0.3
nx                 : 19.6.4
@nx/js             : 19.6.4
@nx/jest           : 19.6.4
@nx/linter         : 19.6.4
@nx/eslint         : 19.6.4
@nx/workspace      : 19.6.4
@nx/angular        : 19.6.4
@nx/cypress        : 19.6.4
@nx/devkit         : 19.6.4
@nx/eslint-plugin  : 19.6.4
@nx/nest           : 19.6.4
@nx/node           : 19.6.4
@nx/playwright     : 19.6.4
@nx/plugin         : 19.6.4
@nrwl/tao          : 19.6.4
@nx/vite           : 19.6.4
@nx/web            : 19.6.4
@nx/webpack        : 19.6.4
typescript         : 5.5.4
---------------------------------------
Community plugins:
@ngneat/transloco        : 6.0.4
@ngrx/component-store    : 18.0.2
@ngrx/effects            : 18.0.2
@ngrx/entity             : 18.0.2
@ngrx/eslint-plugin      : 18.0.2
@ngrx/operators          : 18.0.2
@ngrx/router-store       : 18.0.2
@ngrx/schematics         : 18.0.2
@ngrx/signals            : 18.0.2
@ngrx/store              : 18.0.2
@ngrx/store-devtools     : 18.0.2
angular-auth-oidc-client : 18.0.1
apollo-angular           : 7.1.2
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The code that needs to be moved: https://github.com/nrwl/nx/blob/320d9f223f79fd5ec6ef5b8cf657dad72b09bd26/packages/angular/src/generators/application/lib/add-e2e.ts#L31

Pull request opened: https://github.com/nrwl/nx/pull/27853

**Comment by Coly010** [comment]
The serve static target is useful for other scenarios:
 - Previewing a production version of your application locally
 - Module Federation features
 
 It is not constrained to just `e2e`. 
 
 I'll make a slight change to how and where it is set up to reflect this.
