### ISSUE TITLE
storybookConfigurationGenerator appending to nx.json ad nauseam

### ISSUE THREAD

**Issue by matthew-williamson** [nrwl/nx#27866]
### Current Behavior

When using the `storybookConfigurationGenerator` from `@nx/react`, my workspace's `nx.json` file gets an additional `tasksRunnerOptions.default.options.cacheableOperations` `build-storybook` value _every single time_, meaning it eventually looks like

```
{
  "tasksRunnerOptions": {
    "default": {
      "options": {
        "cacheableOperations": ["build-storybook", "build-storybook", "build-storybook", ...]
      }
    }
  }
}

```

### Expected Behavior

It should not be doing that, if the generator or update of the tree or files or whatever is causing it sees the value in the nx.json array, it shouldn't add a new one.

### Steps to Reproduce

1. Run the `storybookConfigurationGenerator`

### Nx Report

```shell
N/A
```

### Package Manager Version

yarn 3.1.1

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
@matthew-williamson Can you please provide the Nx version you're using by running `nx report` because this should have been fixed already: https://github.com/nrwl/nx/blob/590c7ae905cfc98ceb4a2778b58a550375466f1b/packages/storybook/src/generators/configuration/lib/util-functions.ts#L639

**Comment by matthew-williamson** [comment]
@Coly010 ah, I see. Totally possible:

![image](https://github.com/user-attachments/assets/9f0cbe7f-6a29-4740-ac93-ba80e03eb86e)

**Comment by Coly010** [comment]
Interestingly, you’re on a version that fix exists for.

I see you have a local workspace plugin, are you invoking storybookConfigurationGenerator from this plugin?

**Comment by jrschifa** [comment]
I think this PR is the culprit that broke the comparison. https://github.com/nrwl/nx/commit/05e7602a2cae019f33ca3b0cccd2ca2f477c984f#diff-2cc24f7df8a70ad01ff5f9e420bd92c04b86adda2ee5005bce9aa5a165ab0147L137-L145 

Simply missing a `!` in front of the check

**Comment by Coly010** [comment]
@jrschifa Ah! good spot. I'll get it resolved
