### ISSUE TITLE
react-router-dom version is overwritten in package.json when generating new React application

### ISSUE THREAD

**Issue by chefinDan** [nrwl/nx#27881]
### Current Behavior

I need to use v5 of react-router-dom due a dependency on Okta-React. I have "^5.0.0" specified in my package.json, but when I use the React generator and specify route generation NX automatically uses v6 of react-router-dom and updates my package.json. This then breaks all other apps that use features from v5 of react-router not found in v6. 

### Expected Behavior

I expect the React generator to add routing using the current version specified by my app.
If that is not possible, then provide a way for me to override the version used by NX when generating a React app.

### Steps to Reproduce

1. Generate a React app and add routing.
2. Change the version of react-router in package.json to "^5.0.0" and reinstall dependencies.
3. Generate another React app with routing
4. Notice that the version of react-router has changed in package.json 

### Nx Report

```shell
Node           : 20.11.1
OS             : darwin-x64
Native Target  : x86_64-macos
npm            : 10.8.2

nx                 : 19.6.3
@nx/js             : 19.6.3
@nx/jest           : 19.6.3
@nx/linter         : 19.6.3
@nx/eslint         : 19.6.3
@nx/workspace      : 19.6.3
@nx/devkit         : 19.6.3
@nx/eslint-plugin  : 19.6.3
@nx/react          : 19.6.3
@nrwl/tao          : 19.6.3
@nx/vite           : 19.6.3
@nx/web            : 19.6.3
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Hey,

If you do not want to update the dependencies you can pass `skipPackageJson` when you are generating your react project.
Additionally, this might result in your project not running as expected.

Closing.
