### ISSUE TITLE
Affected: The table of options is not formatted properly

### ISSUE THREAD

**Issue by anthony-b-dev** [nrwl/nx#27893]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://github.com/nrwl/nx/blob/master/docs/generated/packages/nx/documents/affected.md

### Additional context or description

The table of options is not formatted properly

**Comment by pawel-twardziak** [comment]
Hi, I am facing the same. In general, the docs is going nuts - there must be a syntax or formatting issue in the source.

**Comment by pawel-twardziak** [comment]
I can try to fix it. It is annoying, using the docs right now 😄

**Comment by jaysoo** [comment]
@pawel-twardziak We greatly appreciate community PRs if you're still up for the task.

**Comment by pawtwa** [comment]
@jaysoo great, thenks for the response! I am still up for it, will do.

**Comment by pawel-twardziak** [comment]
@jaysoo great, thanks for the response! I am still up for it, will do.

**Comment by pawel-twardziak** [comment]
@jaysoo I am not it, doing the job :)

**Comment by pawel-twardziak** [comment]
@jaysoo @isaacplmann PR's just been raised

**Comment by pawel-twardziak** [comment]
I reckon the issue comes from this command `nx documentation --no-dte` - it breakes the files

**Comment by pawel-twardziak** [comment]
![obraz](https://github.com/user-attachments/assets/d2071501-f8c4-4ecb-8941-cc0049a4e026)

**Comment by pawel-twardziak** [comment]
https://github.com/rust-lang/rust/issues/105723
