### ISSUE TITLE
Mitration from nx 17.3.2 to 18.3.5 breaks compilation (input production env NX_MF_DEV_SERVER_STATIC_REMOTES)

### ISSUE THREAD

**Issue by ekiliqua** [nrwl/nx#27899]
### Current Behavior

The compilation broke after the update using "nx migrate --run-migrations".

### Expected Behavior

It should compile.

### Steps to Reproduce

I'm not sure if the error actually originates from version 17, as I am migrating step by step from version 15. It's a monorepository with Angular applications. I believe I have pinpointed the problem, but I'm not sure if I need to configure something else or if I should simply remove the configuration that is added in a specific step of the migration.

In any case, it's possible that this migration step is causing the same issue for other users.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.9.0
OS     : darwin-arm64
npm    : 10.1.0

nx                 : 18.3.5
@nx/js             : 18.3.5
@nx/jest           : 18.3.5
@nx/linter         : 18.3.5
@nx/eslint         : 18.3.5
@nx/workspace      : 18.3.5
@nx/angular        : 18.3.5
@nx/cypress        : 18.3.5
@nx/devkit         : 18.3.5
@nx/eslint-plugin  : 18.3.5
@nrwl/tao          : 18.3.5
@nx/web            : 18.3.5
@nx/webpack        : 18.3.5
typescript         : 5.4.5
```

### Failure Logs

```shell
> nx serve customer-area --open --devRemotes="consola-monitorizacion"


> nx run customer-area:serve:development --open --devRemotes=consola-monitorizacion


 NX  Starting module federation dev-server for customer-area with 8 remotes


 NX  Building 7 static remotes...

/Users/xxxxxx/Documents/repos/xxxxxx-frontend-xxxxxx/node_modules/@nx/angular/src/executors/module-federation-dev-server/lib/build-static-remotes.js:49
                throw new Error(`Remote failed to start. A complete log can be found in: ${remoteBuildLogFile}`);
                ^

Error: Remote failed to start. A complete log can be found in: /Users/xxxxxxx/Documents/repos/xxxxxx-frontend-xxxxxx/.nx/cache/2024-09-12T18_41_05_920Z-build.log
    at ChildProcess.<anonymous> (/Users/xxxxxxx/Documents/repos/xxxxxx-frontend-xxxxxx/node_modules/@nx/angular/src/executors/module-federation-dev-server/lib/build-static-remotes.js:49:23)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

Node.js v20.9.0

========================================

And this is the content of the log file:

/Users/xxxxxxx/Documents/repos/xxxxxx-frontend-xxxxxx/node_modules/nx/src/hasher/native-task-hasher-impl.js:32
        const plans = this.planner.getPlansReference(tasks.map((t) => t.id), taskGraph);
                                   ^

Error: "production" is an invalid fileset.
All filesets have to start with either {workspaceRoot} or {projectRoot}.
For instance: "!{projectRoot}/**/*.spec.ts" or "{workspaceRoot}/package.json".
If "production" is a named input, make sure it is defined in nx.json.

    at NativeTaskHasherImpl.hashTasks (/Users/xxxxxxx/Documents/repos/xxxxxx-frontend-xxxxxx/node_modules/nx/src/hasher/native-task-hasher-impl.js:32:36)
    at InProcessTaskHasher.hashTasks (/Users/xxxxxxx/Documents/repos/xxxxxx-frontend-xxxxxx/node_modules/nx/src/hasher/task-hasher.js:53:50)
    at handleHashTasks (/Users/xxxxxxx/Documents/repos/xxxxxx-frontend-xxxxxx/node_modules/nx/src/daemon/server/handle-hash-tasks.js:30:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleResult (/Users/xxxxxxx/Documents/repos/xxxxxx-frontend-xxxxxx/node_modules/nx/src/daemon/server/server.js:107:16)
    at async handleMessage (/Users/xxxxxxx/Documents/repos/xxxxxx-frontend-xxxxxx/node_modules/nx/src/daemon/server/server.js:81:9)
    at async /Users/xxxxxxx/Documents/repos/xxxxxx-frontend-xxxxxx/node_modules/nx/src/daemon/server/server.js:45:9 {
  code: 'GenericFailure'
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

First of all, I apologize for my level of English; it’s not my native language.

I'm not sure if the error actually originates from version 17, as I am migrating step by step from version 15. It's a monorepository with Angular applications. I believe I have pinpointed the problem, but I'm not sure if I need to configure something else or if I should simply remove the configuration that is added in a specific step of the migration.

![image](https://github.com/user-attachments/assets/9c19843a-412d-4346-adcb-bd357c403440)

If I remove that configuration from the nx.json file, everything works correctly.

I think that configuration is added in one of these two migrations after running the command "nx migrate --run-migrations":

[...]

    {
      "cli": "nx",
      "version": "18.0.0-beta.0",
      "description": "Add NX_MF_DEV_SERVER_STATIC_REMOTES to inputs for task hashing when '@nx/angular:webpack-browser' is used for Module Federation.",
      "factory": "./src/migrations/update-18-0-0/add-mf-env-var-to-target-defaults",
      "package": "@nx/angular",
      "name": "add-module-federation-env-var-to-target-defaults"
    }

[...]

    {
      "cli": "nx",
      "version": "18.1.1-beta.0",
      "description": "Ensure targetDefaults inputs for task hashing when '@nx/angular:webpack-browser' is used are correct for Module Federation.",
      "factory": "./src/migrations/update-18-1-1/fix-target-defaults-inputs",
      "package": "@nx/angular",
      "name": "fix-target-defaults-for-webpack-browser"
    },

[...]

I think it’s related to this: https://github.com/nrwl/nx/issues/21390

Thank you

**Comment by Coly010** [comment]
This seems like it may be a caching issue or a stale `Nx Graph`, such that your removal of 

```
{
  "env": "NX_MF_DEV_SERVER_STATIC_REMOTES"
}
```

is invalidating the stale graph and allowing for a rebuild, as `{env: string}` is a valid input.

The other thing to check is whether "production" is in your `namedInputs` in the `nx.json`.

**Comment by ekiliqua** [comment]
Thank you for your response.

After reporting the issue, I continued testing and investigating. It seems that the error is caused because there is no configuration for "namedInputs". Shouldn't this be added automatically during the migration? If I remove these two lines, everything works perfectly:

![image](https://github.com/user-attachments/assets/0f1c4e65-ea44-4bcc-8083-a5849ce513ff)


And if we don't want to remove those two lines, we need to configure the namedInputs. I took these from a new project generated with nx@19. Shouldn't this be added automatically during the migration?:

![image](https://github.com/user-attachments/assets/6c79545d-be02-4900-8ca7-5256943f05e8)


Once I fixed that, I encountered a problem related to routing. The static servers for the applications that I haven't specified in "devRemotes" are not loading correctly. I've been reviewing the configuration of all the nx files, but I can't find the issue. I've seen related posts, but I can't seem to solve it... With a freshly generated project, routing works correctly, but after migrating the old project, it doesn't.

When I try to access any application, the same one always loads, regardless of which one I try to access. However, if I access an application specified in --devRemotes, that one works correctly...


Any ideas?

Thanks

**Comment by Coly010** [comment]
There is an issue with the migration but it is not that it needs to add those namedInputs, rather it should only add them if they exist.

Can you open a new issue for the remotes issue, with the version of Nx, and as much information as possible, including errors in the terminal and browser
