### ISSUE TITLE
Nx does not recomputes project graph afer changes in node_modules

### ISSUE THREAD

**Issue by Exelord** [nrwl/nx#27943]
### Current Behavior

When switching to a branch with yarn.lock changes, NX does not recomputes the graph automatically. After running `yarn install` I need to manually `nx reset` in order to get a correct graph and use remote cache.

### Expected Behavior

When switching to a branch with yarn.lock changes, NX does recomputes the graph automatically and it is watching for any change in node_modules.

### Steps to Reproduce

1. Switch to a different branch with changes in dependencies
2. Try to get targets from remote cache [no cache]
3. install dependencies and try again [ no cache ]
4. run `nx reset`
5. Try again running from cache [ remote cache found ]

### Nx Report

```shell
NX 19.7.2
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
Do you have a repro that you can link to for us to debug?

**Comment by julianobrasil** [comment]
It happens to me all the time. I basically got used to `yarn nx reset` whenever I switched branches.
