### ISSUE TITLE
Can't upgrade Nx to 19.7.3

### ISSUE THREAD

**Issue by k4wo** [nrwl/nx#27959]
### Current Behavior

I'm not able to upgrade Nx to 19.7.3.

1. First issue related is to a proxy file:
```
Running migration @nx/webpack: update-19-6-3-proxy-config

 NX   Failed to run update-19-6-3-proxy-config from @nx/webpack. This workspace is NOT up to date!


 NX   Cannot find {workspaceRoot}/proxy.json
```
If I remove manually `proxyConfig` field from my `project.json` migration succeed but I'm not able to run the project.

2. Below is message from logs:
```
[ Module Federation Manifest Plugin ]: Manifest will use absolute path resolution via its host at runtime, reason: publicPath='auto'

 NX   [ Module Federation Manifest Plugin ]: no files found for remoteEntry chunk
```

### Expected Behavior

1. First issue should ended up with better worded message. 
2. App is running

### Steps to Reproduce

1.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 21.5.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.2.4

nx                 : 19.7.3
@nx/js             : 19.7.3
@nx/jest           : 19.7.3
@nx/linter         : 19.7.3
@nx/eslint         : 19.7.3
@nx/workspace      : 19.7.3
@nx/cypress        : 19.7.3
@nx/devkit         : 19.7.3
@nx/esbuild        : 19.7.3
@nx/eslint-plugin  : 19.7.3
@nx/express        : 19.7.3
@nx/node           : 19.7.3
@nx/react          : 19.7.3
@nx/storybook      : 19.7.3
@nrwl/tao          : 19.7.3
@nx/web            : 19.7.3
@nx/webpack        : 19.7.3
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/storybook/plugin
```

### Operating System

- [X] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Webpack, static module federation with react, 3 remotes and host. I'm able to upgrade to 19.6.0 (from 19.0.0)

**Comment by belaczek** [comment]
This might be related to https://github.com/nrwl/nx/issues/28042. Does the failing remote have any dashes "-" in its name?

**Comment by Coly010** [comment]
Should be resolved with: Fixed by: https://github.com/nrwl/nx/pull/28401
