### ISSUE TITLE
 Dependency injection compatibility or how to share code between client/backend

### ISSUE THREAD

**Issue by soyuka** [nrwl/nx#2796]
Original issue: https://github.com/nestjs/nest/issues/4487

## Explanation details

Let's say we have a full-stack application, using Angular and Nest. Side note, the repository is setup with https://nx.dev. Now, the project needs a Logger, you set up a new library `ng g @nrwl/workspace:lib logger` and start working on sending your logs to Loggly via http:

<details>
<summary>Logger implementation</summary>

```typescript
import { Observable } from 'rxjs';

export interface LogglyConfiguration {
  token: string;
  enabled: boolean;
  tags: string[];
  silent?: boolean;
}

export abstract class Logger {
  private url: string;

  constructor(
    private http: ??? (see below),
    private configuration: LogglyConfiguration
  ) {
    this.url = `https://logs-01.loggly.com/inputs/${
      configuration.token
    }/tag/${configuration.tags.join(',')}/`;
  }

  error(error: Error) {
    this.log(error.message, { stack: error.stack });
  }

  log(message: string, payload: any) {
    if (!this.configuration.silent) {
      console.error('Sending following log to loggly: ', message, payload);
    }

    if (!this.configuration.enabled) {
      return;
    }

    this.http.post(this.url, { message, payload }).subscribe({
      error: error => console.log('Error logging in loggly:', error)
    });
  }
}
``` 

</details>

Now comes the interesting part, first the HttpImplementation in angular you'd have `HttpClient` from `@angular/common/http`, in Nest `HttpService` from `@nest/common`. I had to type something like:

```typescript
    Partial<{
      post: (url: string, data: any) => Observable<any>;
    }>
```
But there's probably something better to do here.

About injection I first thought naively that both `Injectable` implementations would work together and added:

```typescript
import {Injectable as NestInjectable} from "@nest/common"
import {Injectable} from "@angular/common"

@NestInjectable()
@Injectable()
class Logger {}
``` 

This fails building with errors like:

```console
WARNING in /home/soyuka/work/deviseur/node_modules/@nestjs/common/utils/load-package.util.js 8:39-59
Critical dependency: the request of a dependency is an expression

ERROR in /home/soyuka/work/deviseur/node_modules/@nestjs/common/cache/cache.providers.js
Module not found: Error: Can't resolve 'cache-manager' in '/home/soyuka/work/deviseur/node_modules/@nestjs/common/cache'
```

Let's see what we can do with the `LogglyConfiguration` interface. Note that apparently we can't import interfaces from other packages as nest logs:

```console
WARNING in ./apps/api/src/app/logger.ts 14:190-209
"export 'LogglyConfiguration' was not found in '@scope/logger'
```

Also, when using Angular you'd typically use a token to inject the configuration for example:
```typescript
    {
      provide: LOGGLY_CONFIG,
      useValue: () =>
        ({
          token: environment.loggly.token,
          enabled: environment.loggly.enabled,
          tags: environment.loggly.tags
        } as LogglyConfiguration)
    }
```

Where `LOGGLY_CONFIG` is a token (useful for typings):
```typescript
export const LOGGLY_CONFIG = new InjectionToken<LogglyConfiguration>(
  'loggly.configuration'
);
```

In Nest, the recommandation is to use a string, but this looses the advantages of strict typing with the token. 

Today I have to use two different implementations in the Nest project and in the Angular project [see this gist](https://gist.github.com/soyuka/8d3711c6cdc8c5b748f392ae24d5459c).

### Solution

Ideally both injection annotation (Angular's and Nest's) should be compatible and declaring a shared service could be easier then this. Do you think that this would be possible or are they limitation that would interfere that I'm not aware of? Could we introduce tools to ease this process in nx? What are your thoughts on the subject?

By the way, thanks to the nrwl team to provide such an amazing tool.

**Comment by FrozenPandaz** [comment]
I do agree with @kamilmysliwiec 's that these two frameworks do not share a dependency injection system so it's not really expected to work. I think having an `abstract class` and having thin implementations as you have is a good way to approach it.

_In theory_, it might be possible that both decorators could be applied to the class. However, there is still the issue that the tokens that you are trying to inject are different. Not only is it different for the LOGGLY_CONFIGURATION but it is also different for the Http class. Theoretically, that could be fixed as well?

**Comment by soyuka** [comment]
Indeed, actually I've improved the code, a token as a string will also work with angular and simplifies things a bit: https://gist.github.com/soyuka/8d3711c6cdc8c5b748f392ae24d5459c.

I've thought about sharing both decorators but it doesn't work and I had a weird exception telling me that they probably don't like each others :p. I also thought about having a decorator that implements both but it's too difficult and there will be too many edge cases. Finally, I would also recommend the kind of implementation I have done here. 

Do you think that this deserves a documentation of some kind? I'd enjoy contributing this if you think that this would help others. If not, feel free to close this issue. Thanks for your answer.

**Comment by brandonroberts** [comment]
I think sharing interfaces/types/APIs across libs is documented, but this issue can be used as reference for others.
