### ISSUE TITLE
Page refresh issue - nx

### ISSUE THREAD

**Issue by a5hik** [nrwl/nx#280]
Does nx has any built in mechanism to support losing state when refreshing page? What is the real purpose of data persistence api and its underlying api? Does it solves the above issue? If not what is the recommendation. I see the ngrx sample uses index dB? If then do we have samples with nx?

**Comment by Yonet** [comment]
@a5hik nx does not have a built in mechanism for saving data on refreshed page. DataPersistence is a helper function to persist server state while the session is active. You can read more about it here:
https://nrwl.io/nx/guide-data-persistence and here: https://blog.nrwl.io/using-ngrx-4-to-manage-state-in-angular-applications-64e7a1f84b7b
