### ISSUE TITLE
Cypress - add reporters options

### ISSUE THREAD

**Issue by maiis** [nrwl/nx#2800]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

We would like to pass `reporter` and `reporterOptions` to Cypress

## Current Behavior

These options are not supported, checked on https://nx.dev/angular/cli/e2e#cypress-options

### Steps to Reproduce

`nx e2e myapp-e2e --reporter junit --reporter-options 'mochaFile=reports/results-[hash].xml,toConsole=true'`

### Context

```
  @nrwl/angular : 9.1.2
  @nrwl/cli : 9.1.2
  @nrwl/cypress : 9.1.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.1.2
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.1.2
  @nrwl/web : Not Found
  @nrwl/workspace : 9.1.2
  typescript : 3.7.5
```

**Comment by eliperelman** [comment]
As a workaround, you can also specify these as [environment variables that Cypress recognizes](https://docs.cypress.io/guides/references/configuration.html#Environment-Variables):

```sh
CYPRESS_REPORTER=junit CYPRESS_REPORTER_OPTIONS="mochaFile=reports/results-[hash].xml,toConsole=true" nx e2e myapp-e2e
```

**Comment by ShaneK** [comment]
Is there a reason you closed this? A workaround is a hack, not a solution. I would still like the reporter option to be added.

**Comment by mehrad-rafigh** [comment]
@maiis I think @ShaneK is right. You should reopen this issue and I will open a PR for this. The reporter and reporterOptions flags should work out of the box without any hacks.

**Comment by maiis** [comment]
👍🏻 I initially closed it because I wasn’t gonna have time to make a PR in the end, and I’m not using Cypress anymore. You’re right I reopen it, can be useful for others 👌🏻

**Comment by mehrad-rafigh** [comment]
@maiis Thank you! I will open a PR today!

**Comment by simonstadlinger** [comment]
@mehrad-rafigh Thank you for your fix, it did everything it needed to do!
I still have one little inconvenience. The two options "reporter" and "reporter-option" are not recognized when specified in the cypress.json. Have I configured something wrong? If not, I would be glad if that is made possible.

**Comment by mehrad-rafigh** [comment]
Hi @simonstadlinger 
Happy to hear it fixed your problem :)
Actually, if you provide the reporter options through the cypress.json file, those options should be picked up by cypress.
I will investigate this and provide some feedback

**Comment by milanPandya** [comment]
Hi @mehrad-rafigh , do you have any update on your investigation of reporter options through cypress.json file not getting picked up? Even I am facing similar issue if reporter is present in cypress.json file.

**Comment by cgilmeanu** [comment]
> Hi @simonstadlinger
> Happy to hear it fixed your problem :)
> Actually, if you provide the reporter options through the cypress.json file, those options should be picked up by cypress.
> I will investigate this and provide some feedback

Hi! I have the same problem and this is due to the fact the if the `reporter` and `reporterOptions` are missing from the angular.json file, then, internally, the cypress executor is sets the `options.reporter` to "something" - could be undefined - but still, because of this the cypress.json reporter is ignored.

I've created a draft PR for this if you can check it out here: https://github.com/nrwl/nx/pull/7089

**Comment by mxxlrfu** [comment]
> Hi @mehrad-rafigh , do you have any update on your investigation of reporter options through cypress.json file not getting picked up? Even I am facing similar issue if reporter is present in cypress.json file.
> 
> The correct location of cypress-multi-reporter is C:\work\dir-name\node_modules\cypress-multi-reporters
> 
> Update: Turns out it is a Cypress issue and not an nx one. [cypress-io/cypress#6406](https://github.com/cypress-io/cypress/issues/6406)
> 
> ![image](https://user-images.githubusercontent.com/334839/128720555-c2c8f9dc-4588-48c5-b1ad-c624b7ca7132.png)

Hmm is there another open issue for this ? What you can actually do is passing the relative path to `cypress-multi-reporters` as the `reporter` as in:

```
{
  "reporter": "../../node_modules/cypress-multi-reporters"
}
```

This is a workaround that works with `mochawesome` but no guarantee it's gonna work in your case...
