### ISSUE TITLE
Webpack Module Federation: Remote build fails with dashes in remote module name

### ISSUE THREAD

**Issue by belaczek** [nrwl/nx#28042]
### Current Behavior

After upgrading to NX 19.8.0, or any other version with updated module federation, builds of all federated remotes with dash in its name started to fail. 

Example federation config:
```typescript
const config: ModuleFederationConfig = {
  name: 'acme-remote',

  library: { type: 'var', name: 'acme_remote' },

  exposes: {
    './Module': './src/remote-entry.ts',
  },
  shared,
};
```
**Seems like the `library` property is being ignored**. And changing the name property is not possible without renaming the whole project, which is not feasible in our case.

### Expected Behavior

Build of federated remotes would pass the same way as before the upgrade.

### GitHub Repo

https://github.com/belaczek/nx-federation-repro

### Steps to Reproduce

1. Clone https://github.com/belaczek/nx-federation-repro
2. `pnpm install`
3. `pnpm nx build acme-remote`

### Nx Report

```shell
Node           : 20.12.1
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.10.0

nx                 : 19.8.0
@nx/js             : 19.8.0
@nx/jest           : 19.8.0
@nx/linter         : 19.8.0
@nx/eslint         : 19.8.0
@nx/workspace      : 19.8.0
@nx/devkit         : 19.8.0
@nx/eslint-plugin  : 19.8.0
@nx/react          : 19.8.0
@nrwl/tao          : 19.8.0
@nx/web            : 19.8.0
@nx/webpack        : 19.8.0
typescript         : 5.5.4
```

### Failure Logs

```shell
> nx run acme-remote:build:production

[ Module Federation Manifest Plugin ]: Manifest will use absolute path resolution via its host at runtime, reason: publicPath='auto'

 NX   [ Module Federation Manifest Plugin ]: no files found for remoteEntry chunk

Pass --verbose to see the stacktrace.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by k4wo** [comment]
I have the same issue. This is happening from 19.6.3 version

**Comment by k4wo** [comment]
20.0.0 is still affected

**Comment by Coly010** [comment]
Fixed by: https://github.com/nrwl/nx/pull/28401
