### ISSUE TITLE
Name collision between app and lib while using the nx cli

### ISSUE THREAD

**Issue by vajahath** [nrwl/nx#2809]
#### Env
- [x] I am running the latest version
```
"@nrwl/cli": "^9.2.1",
"@nrwl/workspace": "^9.2.1",
```
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Issue
I've converted my existing angular app **(with name `xxxx`)** to Nx via the following command as suggested in the doc (and it was working fine).
```sh
ng add @nrwl/workspace
```
Then I created a shared lib with **the same name** via:
```
nx g @nrwl/workspace:lib xxxx
```
Even though there are no folder collisions, configurations in the `angular.json` got **overwrite** without any warnings. 

## Expected Behavior

If there is such a name collision, it should fail after providing a good warning.

## Current Behavior

The config files got overwrite without any notice. So my existing projects may not work.

#### nx report
$ nx report
```sh
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 9.2.2
  @nrwl/cli : 9.2.2
  @nrwl/cypress : 9.2.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.2.2
  @nrwl/linter : 9.2.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.2.2
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.2
  @nrwl/web : Not Found
  @nrwl/workspace : 9.2.2
  typescript : 3.7.5

Done in 0.48s.
```

**Comment by FrozenPandaz** [comment]
Fixed by #2997
