### ISSUE TITLE
pnpm support for nx cli ?

### ISSUE THREAD

**Issue by iangregsondev** [nrwl/nx#2812]
Hi,

there was some work done to support pnpm (alternative to yarn and pm) package manager - I am referring to this pull request https://github.com/nrwl/nx/pull/1253

The changes seem to specifically deal with "ng" - angular cli.

This doesn't fix the same when using the nx cli ?

Thanks in advane

**Comment by jaysoo** [comment]
Hey @iangregsondev, we should have `pnpm` support even without Angular CLI.

We detect for `pnpm` by executing `pnpm --version`. https://github.com/nrwl/nx/blob/6706a05/packages/create-nx-workspace/bin/shared.ts#L35-L37

However, if you have `yarn` installed, that will take precedence. 

Hope that helps, feel free to re-open if you run into any issues.
