### ISSUE TITLE
19.8.1 leaves dangling child processes on Windows

### ISSUE THREAD

**Issue by CreativeTechGuy** [nrwl/nx#28207]
### Current Behavior

When pressing ctrl+c on windows to kill a NX command (eg: a dev server), it leaves all of the sub-processes (node, esbuild, vite, etc) running.

### Expected Behavior

When pressing ctrl+c on windows to kill a NX command (eg: a dev server), it should kill all of the processes which were created.

### Steps to Reproduce

1. Run a NX command which uses the `nx:run-commands` executor
2. Kill the command in the terminal with ctrl+c
3. Check Windows Task Manager to see that the process that was started is still running (this is easiest to see if the first process starts a server on a port since the second run will now fail since that port is still in-use)

### Nx Report

```shell
Node           : 20.17.0
OS             : win32-x64
Native Target  : x86_64-windows
pnpm           : 9.11.0

nx                 : 19.8.1
@nx/js             : 19.8.1
@nx/jest           : 19.8.1
@nx/linter         : 19.8.1
@nx/eslint         : 19.8.1
@nx/workspace      : 19.8.1
@nx/devkit         : 19.8.1
@nx/esbuild        : 19.8.1
@nx/eslint-plugin  : 19.8.1
@nx/plugin         : 19.8.1
@nrwl/tao          : 19.8.1
@nx/vite           : 19.8.1
typescript         : 5.6.2
```

### Failure Logs

```shell
N/A
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

This is the commit which broke it: https://github.com/nrwl/nx/pull/28073

This is the NodeJS reference for why it's broken: https://github.com/nodejs/node/issues/29837#issuecomment-538438824

**Comment by BitBuf** [comment]
Issue still present on 19.8.2.

**Comment by MaxKless** [comment]
There is some nuance to this. The sub-processes you see are probably the plugin workers. Nx spawns them when calculating the project graph and their lifecycle is tied to the parent process. By default, this parent process is the nx daemon. So as long as the daemon is running, the plugin workers will be running. 

This is independent from the individual task execution and is expected behavior. 

It's very possible that there is still an issue stemming from `windowsHide: true`. Can you set the `NX_DAEMON` env variable to false and recheck the behaviour? Now, all child processes should be stopped once task execution stops. 

Is there a difference between tasks that end by themselves (like `build`, usually) and tasks that you kill manually (like `serve` in your example)?

**Comment by CreativeTechGuy** [comment]
@MaxKless Thanks for the reply!

`NX_DAEMON=false` didn't make a difference unfortunately.

And yes it's only with tasks the user kills. A `build` type task won't have the same issue since the process ends and isn't killed.

I've confirmed that by doing a find/replace in all of the nx & @nx packages for `windowsHide: true` -> `windowsHide: false` that it fixes the issue. That was the only fix I was able to find.

**Comment by MaxKless** [comment]
yeah I can repro this and am working on a fix. I don't want to replace all instances of `windowsHide: true` since that will result in popups everywhere again. It might be okay to set it to false for executor invocations, though. I'm investigating.

**Comment by lppedd** [comment]
Anyone know in which version this issue was introduced?

**Comment by MaxKless** [comment]
If you wait just a couple of hours, you should be fine to update to `20.0.2`

**Comment by CreativeTechGuy** [comment]
@lppedd 19.8.0 doesn't have the issue, it was introduced in 19.8.1. And it seems like it's been fixed in 20.0.2! (Thanks @MaxKless)

**Comment by CreativeTechGuy** [comment]
Looks like the PR to fix this is #28496 (just tagging to link the two).

**Comment by lppedd** [comment]
Thanks @MaxKless! @CreativeTechGuy do you see prompt windows popping up as a side effect?

**Comment by CreativeTechGuy** [comment]
@lppedd The fixed version hasn't been released yet so I cannot test it. But when making the patch locally, yes a windows command prompt window will flash for a second and then close. Doesn't really bother me.

**Comment by MaxKless** [comment]
[20.0.2](https://github.com/nrwl/nx/releases/tag/20.0.2) is out! So please try this new version and confirm that it's fixed.
I'll also release a new Nx Console version that fixes even more dangling process errors. 

Please let me know if you run into any windows popups after the update, I didn't locally, but it might still happen. We will have to take care of those manually. Thank you :)

**Comment by lppedd** [comment]
@MaxKless upgraded to 20.0.2 and it behaves as expected for me. No popups currently, I'll keep you posted.

**Comment by mklueh** [comment]
I don't think this is entirely fixed yet. I have constant CMD popups still, and Node.exe processes running in the background while using `20.1.1`

**Comment by MaxKless** [comment]
Node.exe processes running in the background are entirely normal, there's the daemon and plugin workers and the language server if using Nx Console.
Regarding the popups, that sucks. Could you create a new issue with more details?
If you can create a minimal repro using the same plugins you're using in your repository where you're seeing this, that's the easiest way to help us fix this! Just @ me in it and I'll look into it :)

**Comment by mklueh** [comment]
@MaxKless I know they are normal, but sometimes it feels like things are stuck in the background and taking up 1GB+ memory still. But I can't tell for sure if this is Nx related.

Regarding popups, I got one step further now.

It seems ,CMD is used through Windows Terminal, and then the Windows Terminal stays open without and CMD tab in it.

After adjusting the CMD settings from Automatic to

![Image](https://github.com/user-attachments/assets/ce9f563f-dc90-45f9-93f3-86e015888e26)

the popups at least close afterwards and won't stay open.

I try to create something reproducible, but maybe the entire issue is just related to Windows itself.
