### ISSUE TITLE
Expo: copyPackageJsonAndLock returns undefined instead of cleanup function in corner cases

### ISSUE THREAD

**Issue by dearlordylord** [nrwl/nx#28208]
### Current Behavior

copyPackageJsonAndLock returns undefined https://github.com/nrwl/nx/blob/8fa7065cf14df6a90896442f90659b00baa1b5b9/packages/expo/src/executors/build/build.impl.ts#L126 when it's ran with pnpm + workspace

### Expected Behavior

it should always return a cleanup function, according to its "docs" (code comment) 

if there's nothing to cleanup, then a noop function should be returned

this is the behaviour that another part of your code https://github.com/nrwl/nx/blob/8fa7065cf14df6a90896442f90659b00baa1b5b9/packages/expo/src/executors/build/build.impl.ts#L43 expects, and fails with a non-descriptive error "resetLocalFunction is not a function"

### Steps to Reproduce

run a build e.g. `npx nx build-eas` with pnpm + workspaces set up

### Nx Report

```shell
no need
```

### Failure Logs

```shell
no need
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by moAlobaidi** [comment]
have you found a work around for this?

**Comment by dearlordylord** [comment]
> have you found a work around for this?

until https://github.com/nrwl/nx/pull/28209 is merged, you can edit the library code manually or be applying a patch during your build process
