### ISSUE TITLE
Last line of inquirer output/console output gets cut off

### ISSUE THREAD

**Issue by CatchABus** [nrwl/nx#28219]
### Current Behavior

I'm not sure why but in current version of nx I see an old bug that was supposedly taken care of in 17.3.0.
That is #13540 

### Expected Behavior

NX command runner should not clip cli output.

### Steps to Reproduce

See #13540 

### Nx Report

```shell
Node           : 21.2.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.2.3

nx             : 19.8.2
@nx/js         : 19.8.2
@nx/workspace  : 19.8.2
@nx/devkit     : 19.8.2
@nrwl/tao      : 19.8.2
typescript     : 5.6.2
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
i tried the repo in https://github.com/nrwl/nx/issues/23230, i am able to see the last line. i suspect this issue was fixed in version 20.0.7.
