### ISSUE TITLE
Linter reports circular dependency when running on linux but not on windows

### ISSUE THREAD

**Issue by beatlang** [nrwl/nx#2824]
## Expected Behavior

Linter should behave the same on Windows and Linux.

## Current Behavior

Linter reports `ERROR: /registration.component.ts:5:1 - Circular dependency between "x" and "y" detected` only on Linux. 

## Failure Information (for bugs)

On windows the linter runs successfully. Dep-graph shows no circular dependency. 

### Steps to Reproduce

- Create a project with several libraries and an app, set tags and dependency constraints
- Add a absolute reference from a library to an app component that consumes the same library. In my case `import { ISettingsEntity } from 'app/operation/settings-entity';`
- Run lint (affected or not) on linux. 

The circular reference is found on linux, but not on windows.

### Context

The problem occurred when updating from @nrwl/workspace@8.12.10  to @nrwl/workspace@9.2.2. It works on 8.12.10 and breaks on 9.0.0.

### Failure Logs

ERROR: /registration.component.ts:5:1 - Circular dependency between "x" and "y" detected

## Other

Any other relevant information that will help us help you.

**Comment by lookapanda** [comment]
Same issue here running on Ubuntu inside WSL 2. It reports a circular dependency, but there is none.

**Comment by philipjfulcher** [comment]
Since there's a difference between Linux and Windows, this may be related to #2955. Next release should have a fix for that issue, so I'll check back on this to see if it solves it.

**Comment by philipjfulcher** [comment]
@beatlang @Ponjimon  I'm circling back to some of these issues related to differences between Windows/Linux/Mac OS and I think they're resolved in our latest version of Nx 9 and 10. Are you able to update your repo to 9.6 or 10.1 to see if that resolves the issue?

**Comment by philipjfulcher** [comment]
This should be fixed in the latest version of 9.x and 10.x of Nx. Please open another bug if you see it again after upgrading to the latest version.
