### ISSUE TITLE
Give affected commands the ability to understand code ownership in Github

### ISSUE THREAD

**Issue by tytusplanck** [nrwl/nx#2825]
## Expected Behavior

I would love if Nx could help us determine what teams are required to view a PR in Github. This would help large enterprises determine what team's need to actually review a PR based on what code was changed/affected.

## Current Behavior

We currently manage this for 6 enterprise teams in an Nx (all Angular) monorepo using `CODEOWNERS` file. This can be cumbersome to manage and also determine whether or not a shared library is really valuable for some teams to review. Ideally, we would like to leverage Nx to help us determine who the right people are to review a given PR.

It may be possible to derive this today given Nx's tooling but, I haven't found any good resources/solutions online. It's also possible that an Nx plugin that hooks into Github would work rather than adding it to the framework itself. I'm curious what the Nrwl team thinks of this problem and if you all feel Nx could help us solve it.

### Context

We have 6 enterprise teams working in an Angular Nx monorepo (38 contributors last month). We are currently on (Angular 8 and Nx 8) but are in the process of upgrading this week (4/6/2020). Our monorepo has 9 apps bringing together over 40 libs into one platform to a user.

**Comment by elvirdolic** [comment]
It would be nice if it could be used by other non github repos as well which don’t have codeowners
