### ISSUE TITLE
storybook has broken migration - monorepo unusable

### ISSUE THREAD

**Issue by nhhockeyplayer** [nrwl/nx#28279]
### Current Behavior

SUBJECT: storybook has broken migration - monorepo unusable

performed nx migrate latest

storybook has tripped up alot

monorepo is in unusable state cannot build anything

nx reset fails to remedy

help appreciated...

the migration process continues to fail at every attempt to get storybook@latest which seems simple... it fails

### Expected Behavior

migration should have worked around this but its really spun out

### GitHub Repo

https://github.com/nhhockeyplayer/meanstacknh

### Steps to Reproduce

nx migrate latest

then run migrations

fails when it attempts to get storybook@latest

### Nx Report

meanstack02@admin meanstacknh % nx report

 NX   Report complete - copy this into the issue template

Node           : 22.4.1
OS             : darwin-x64
Native Target  : x86_64-macos
yarn           : 1.22.22

nx (global)        : 19.4.3
nx                 : 19.8.3
@nx/js             : 19.8.3
@nx/jest           : 19.8.3
@nx/linter         : 19.8.3
@nx/eslint         : 19.8.3
@nx/workspace      : 19.8.3
@nx/angular        : 19.8.3
@nx/cypress        : 19.8.3
@nx/devkit         : 19.8.3
@nrwl/devkit       : 13.10.6
@nx/eslint-plugin  : 19.8.3
@nx/express        : 19.8.3
@nx/nest           : 19.8.3
@nx/node           : 19.8.3
@nx/storybook      : 19.8.3
@nrwl/tao          : 19.8.3
@nx/web            : 19.8.3
@nx/webpack        : 19.8.3
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
@nx/storybook/plugin
---------------------------------------
Community plugins:
@compodoc/compodoc                    : 1.1.25
@fortawesome/angular-fontawesome      : 0.15.0
@ionic/angular                        : 6.7.5
@jsverse/transloco                    : 7.5.0
@ngrx/component                       : 18.0.2
@ngrx/component-store                 : 18.0.2
@ngrx/effects                         : 18.0.2
@ngrx/entity                          : 18.0.2
@ngrx/operators                       : 18.0.2
@ngrx/router-store                    : 18.0.2
@ngrx/schematics                      : 18.0.2
@ngrx/store                           : 18.0.2
@ngrx/store-devtools                  : 18.0.2
@nxtend/capacitor                     : 13.0.0
@nxtend/ionic-angular                 : 13.1.0
@storybook/angular                    : 8.3.4
angular-builder-custom-terser-options : 1.0.1
apollo-angular                        : 7.2.0
---------------------------------------
The following packages should match the installed version of nx
  - @nrwl/devkit@13.10.6

To fix this, run `nx migrate nx@19.8.3`
---------------------------------------
⚠️ Unable to construct project graph.
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the @nx/storybook/plugin plugin.
    - .storybook/main.js: Cannot read properties of undefined (reading 'name')
      TypeError: Cannot read properties of undefined (reading 'name')
          at getStorybookFramework (/Users/meanstack02/meanstacknh/node_modules/@nx/storybook/src/plugins/plugin.js:180:66)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
          at async buildStorybookTargets (/Users/meanstack02/meanstacknh/node_modules/@nx/storybook/src/plugins/plugin.js:66:32)
          at async exports.createNodes (/Users/meanstack02/meanstacknh/node_modules/@nx/storybook/src/plugins/plugin.js:51:32)
          at async /Users/meanstack02/meanstacknh/node_modules/nx/src/project-graph/plugins/utils.js:47:27
          at async Promise.all (index 0)
          at async createNodesFromFiles (/Users/meanstack02/meanstacknh/node_modules/nx/src/project-graph/plugins/utils.js:45:5)
          at async LoadedNxPlugin.createNodes.<computed> (/Users/meanstack02/meanstacknh/node_modules/nx/src/project-graph/plugins/internal-api.js:44:28)
          at async createNodes (/Users/meanstack02/meanstacknh/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:69:36)
          at async consumeMessage (/Users/meanstack02/meanstacknh/node_modules/nx/src/project-graph/plugins/isolation/messaging.js:38:26)

### Failure Logs

```
meanstack02@admin meanstacknh % NX_CLOUD_DISTRIBUTED_EXECUTION=false nx build shared-feature-chat --verbose

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the @nx/storybook/plugin plugin.
    - .storybook/main.js: Cannot read properties of undefined (reading 'name')
      TypeError: Cannot read properties of undefined (reading 'name')
          at getStorybookFramework (/Users/meanstack02/meanstacknh/node_modules/@nx/storybook/src/plugins/plugin.js:180:66)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
          at async buildStorybookTargets (/Users/meanstack02/meanstacknh/node_modules/@nx/storybook/src/plugins/plugin.js:66:32)
          at async exports.createNodes (/Users/meanstack02/meanstacknh/node_modules/@nx/storybook/src/plugins/plugin.js:51:32)
          at async /Users/meanstack02/meanstacknh/node_modules/nx/src/project-graph/plugins/utils.js:47:27
          at async Promise.all (index 0)
          at async createNodesFromFiles (/Users/meanstack02/meanstacknh/node_modules/nx/src/project-graph/plugins/utils.js:45:5)
          at async LoadedNxPlugin.createNodes.<computed> (/Users/meanstack02/meanstacknh/node_modules/nx/src/project-graph/plugins/internal-api.js:44:28)
          at async createNodes (/Users/meanstack02/meanstacknh/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:69:36)
          at async consumeMessage (/Users/meanstack02/meanstacknh/node_modules/nx/src/project-graph/plugins/isolation/messaging.js:38:26)

```

### Package Manager Version

meanstack02@admin meanstacknh % yarn --version 1.22.22

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

thanks for assist

**Comment by nhhockeyplayer** [comment]
okay I deleted root .storybook folder

I recreated a separate nx project that uses storybook for latest nx and copied those files over beneath each project to sync

manually updated my local project storybook files

migration upgraded storybook to latest did my best to clean that up where needed

what got my build working was to edit the nx.json
not being updated duringmiugration

deleted storybook plugin

```
added this to nx.json
    "build-storybook": {
      "cache": true,
      "inputs": [
        "default",
        "^production",
        "{projectRoot}/.storybook/**/*",
        "{projectRoot}/tsconfig.storybook.json"
      ]
    }
```

alot of manually shaking and hands on hope I goit it right migration runs thru but nothing needed to migrate for latest

build is working now

fingers crossed

storybook stories fail to compile

if I rerun last migrations script... will it fail on storybook? well results follow...

failed not impressed with storybook integration


```
meanstack02@admin meanstacknh % yarn nx migrate --run-migrations                                           
yarn run v1.22.22
$ /Users/meanstack02/meanstacknh/node_modules/.bin/nx migrate --run-migrations

 NX   Running 'yarn' to make sure necessary packages are installed

[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ node ./decorate-angular-cli.js

 NX   Decoration of the Angular CLI is deprecated and will be removed in a future version

Please replace usage of "ng <command>" in any scripts, particularly for CI, with "nx <command>"


 NX   Angular CLI has been decorated to enable computation caching.

$ husky install
husky - Git hooks installed
$ /Users/meanstack02/meanstacknh/node_modules/.bin/nx migrate --run-migrations
$ /Users/meanstack02/meanstacknh/node_modules/.bin/nx _migrate --run-migrations

 NX   Running migrations from 'migrations.json'

Running the following migrations:
- @nx/storybook: update-19-6-0-add-nx-packages (Update workspace to use Storybook v8)
---------------------------------------------------------

Running migration @nx/storybook: update-19-6-0-add-nx-packages

 NX   Migrating Storybook to v8

🚀 This migration will update your Storybook configuration to v8.
It will call the @nx/storybook:migrate-8 generator for you.
You can read more about the migration and how this generator works here:
https://nx.dev/nx-api/storybook/generators/migrate-8


 NX   Calling sb upgrade

ℹ️ Nx will call the Storybook CLI to upgrade your @storybook/* packages to the latest version.
📖 You can read more about the Storybook upgrade command here: https://storybook.js.org/docs/react/configure/upgrading

error Command "storybook@latest" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 NX   Migration failed

🚨 The Storybook CLI failed to upgrade your @storybook/* packages to the latest version.
Please try running the sb upgrade command manually:
yarn storybook@latest upgrade

Error: Command failed: yarn storybook@latest upgrade --yes
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:889:11)
    at execSync (node:child_process:961:15)
    at callUpgrade (/Users/meanstack02/meanstacknh/node_modules/@nx/storybook/src/generators/migrate-8/calling-storybook-cli.js:18:38)
    at migrate8Generator (/Users/meanstack02/meanstacknh/node_modules/@nx/storybook/src/generators/migrate-8/migrate-8.js:26:49)
    at changeStorybookTargets (/Users/meanstack02/meanstacknh/node_modules/@nx/storybook/src/migrations/update-19-6-0/update-sb-8.js:29:36)
    at runNxMigration (/Users/meanstack02/meanstacknh/node_modules/nx/src/command-line/migrate/migrate.js:1036:11)
    at executeMigrations (/Users/meanstack02/meanstacknh/node_modules/nx/src/command-line/migrate/migrate.js:921:39)
    at runMigrations (/Users/meanstack02/meanstacknh/node_modules/nx/src/command-line/migrate/migrate.js:1009:43) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 90899,
  stdout: null,
  stderr: null
}

 NX   ⚙️ Calling sb automigrate

ℹ️  Nx will call the Storybook CLI to automigrate the Storybook configuration of all your projects that use Storybook.
📖 You can read more about the Storybook automigrate command here: https://storybook.js.org/docs/react/configure/upgrading#automigrate-script


 NX   Calling sb automigrate for admin

Command:
yarn storybook@latest automigrate --config-dir apps/admin/.storybook

error Command "storybook@latest" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 NX   Migration failed

🚨 The Storybook CLI failed to automigrate the Storybook configuration of your project.
The error was: Error: Command failed: yarn storybook@latest automigrate --config-dir apps/admin/.storybook  --yes
Please try running the sb automigrate command manually:
yarn storybook@latest automigrate --config-dir apps/admin/.storybook


 NX   Calling sb automigrate for @nhhockeyplayer/shared-root-ui-widget

Command:
yarn storybook@latest automigrate --config-dir libs/shared/root/ui-widget/.storybook

error Command "storybook@latest" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 NX   Migration failed

🚨 The Storybook CLI failed to automigrate the Storybook configuration of your project.
The error was: Error: Command failed: yarn storybook@latest automigrate --config-dir libs/shared/root/ui-widget/.storybook  --yes
Please try running the sb automigrate command manually:
yarn storybook@latest automigrate --config-dir libs/shared/root/ui-widget/.storybook


 NX   Storybook configuration migrated.

☑️ The automigrate command was successful.
The following projects were migrated successfully:


 NX   Failed migrations.

There were some projects that were not migrated successfully.
⚠️ The following projects were not migrated successfully:
  - admin
  - @nhhockeyplayer/shared-root-ui-widget
You can run the following commands to migrate them manually:
- yarn storybook@latest automigrate --config-dir apps/admin/.storybook
- yarn storybook@latest automigrate --config-dir libs/shared/root/ui-widget/.storybook


 NX   Migration complete!

🎉 Your Storybook configuration has been migrated to Storybook ^8.0.0!
📖 You can see a summary of the tasks that were performed in the storybook-migration-summary.md file in the root of your workspace.

Ran update-19-6-0-add-nx-packages from @nx/storybook
  Update workspace to use Storybook v8

Changes:
  UPDATE storybook-migration-summary.md

---------------------------------------------------------

 NX   Successfully finished running migrations from 'migrations.json'. This workspace is up to date!

✨  Done in 12.83s.
meanstack02@admin meanstacknh % yarn storybook@latest automigrate --config-dir apps/admin/.storybook
yarn run v1.22.22
error Command "storybook@latest" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
meanstack02@admin meanstacknh % yarn storybook@latest automigrate --config-dir libs/shared/root/ui-widget/.storybook
yarn run v1.22.22
error Command "storybook@latest" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
meanstack02@admin meanstacknh % 

```

**Comment by nhhockeyplayer** [comment]
I got my monorepo to buikld now

any suggestions how to cleanup storybook migration are appreciated

thankns

**Comment by nhhockeyplayer** [comment]
I got my monorepo to build now

**Comment by kuriangrge** [comment]
how did you fix this?
