### ISSUE TITLE
docs: provide version of nx + plugins for docs on nx.dev

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#2828]
## Expected Behavior

this is a feature request. My workflow with nx is to go directly to github repo as I don't know what's the current deployed version of `nx.dev`. I'm all good with that, but in general other devs might be not (DX...)

It would be nice to display version of nx for particular docs.

great example how to do this is angular.io

![image](https://user-images.githubusercontent.com/1223799/78706470-6c7fb300-790f-11ea-8ea0-d8224addb841.png)

- first step could be just displaying deployed version
- in future having docs functionality line angular.io would be top notch

**Comment by bcabanes** [comment]
Hi @Hotell!
Thank you for proposing this feature, we have it in our plan, but don't have ETA yet.

**Comment by Hotell** [comment]
already implemented, so can be closed 
![image](https://user-images.githubusercontent.com/1223799/97019329-7c2fb380-1550-11eb-92b2-92893d8f711e.png)

great job folks!
