### ISSUE TITLE
Angular with module federation does not apply localization on serve, modifies routes on ssr serve

### ISSUE THREAD

**Issue by LorinRenodeyn2PO** [nrwl/nx#28282]
### Current Behavior

- running `pnpm nx serve <projectname> --configuration=nl` works but does not apply any of the localizations and does not set the correct base href as configured
- running `pnpm nx serve-ssr <projectname> --configuration="nl` sets the basehref correctly and applies localizations but also modifies the routes in the app to include the basehref, which should not be the case

Admittedly, I am new to nx. But at this point i've spent hours trying to figure out what's wrong and can't figure out what's the problem. Found other issues from past years on the angular localization, but those seem to have been resolved to work correctly using a similar setup to what i'm running.

### Expected Behavior

- running `pnpm nx serve <projectname> --configuration=nl` should serve up a localized version of the website with the correct basehref set
- running `pnpm nx serve-ssr <projectname> --configuration="nl` should not modify the routes in the site, leaving off the basehref

### Steps to Reproduce

1. create a workspace with an Angular 18+ app using module federation
2. set up the app for SSR using the nx recipe that configures "@nx/angular:module-federation-dev-server" for "serve" target and "@nx/angular:module-federation-dev-ssr" for "serve-ssr target"
3. enable angular i18n on the app, creating translation files for at least 1 extra language beyond base

Relevant parts of the project.json file in the app's folder:

```JSON
{
	"i18n": {
		"sourceLocale": "en",
		"baseHref": "/en",
		"locales": {
			"nl": {
				"baseHref": "/nl/",
				"translation": "apps/public-facing/my-project/public/locales/messages.nl.xlf"
			},
			"fr": {
				"baseHref": "/fr/",
				"translation": "apps/public-facing/my-project/public/locales/messages.fr.xlf"
			}
		}
	},
	"targets": {
		"build": {
			"executor": "@nx/angular:webpack-browser",
			"configurations": {
				"en": {
					"localize": ["en"]
				},
				"nl": {
					"localize": ["nl"]
				},
				"fr": {
					"localize": ["fr"]
				},
				"production": {
					"localize": true,
					"budgets": [
						{
							"type": "initial",
							"maximumWarning": "500kb",
							"maximumError": "1mb"
						},
						{
							"type": "anyComponentStyle",
							"maximumWarning": "2kb",
							"maximumError": "4kb"
						}
					],
					"outputHashing": "all",
					"customWebpackConfig": {
						"path": "apps/public-facing/my-project/webpack.prod.config.ts"
					}
				},
				"development": {
					"buildOptimizer": false,
					"optimization": false,
					"vendorChunk": true,
					"extractLicenses": false,
					"sourceMap": true,
					"namedChunks": true
				}
			},
			"defaultConfiguration": "production"
		},
		"serve": {
			"executor": "@nx/angular:module-federation-dev-server",
			"options": {
				"port": 3333,
				"publicHost": "http://localhost:3333"
			},
			"configurations": {
				"production": {
					"buildTarget": "my-project:build:production"
				},
				"development": {
					"buildTarget": "my-project:build:development"
				},
				"en": {
					"buildTarget": "my-project:build:development,en"
				},
				"nl": {
					"buildTarget": "my-project:build:development,nl"
				},
				"fr": {
					"buildTarget": "my-project:build:development,fr"
				}
			},
			"defaultConfiguration": "development"
		},
		"extract-i18n": {
			"executor": "@angular-devkit/build-angular:extract-i18n",
			"options": {
				"format": "xlf2",
				"outputPath": "apps/public-facing/my-project/public/locales",
				"buildTarget": "my-project:build"
			}
		},
		"server": {
			"dependsOn": ["build"],
			"executor": "@nx/angular:webpack-server",
			"options": {
				"outputPath": "dist/apps/public-facing/my-project/server",
				"main": "apps/public-facing/my-project/server.ts",
				"tsConfig": "apps/public-facing/my-project/tsconfig.server.json",
				"inlineStyleLanguage": "scss",
				"customWebpackConfig": {
					"path": "apps/public-facing/my-project/webpack.server.config.ts"
				}
			},
			"configurations": {
				"production": {
					"outputHashing": "media"
				},
				"development": {
					"buildOptimizer": false,
					"optimization": false,
					"sourceMap": true,
					"extractLicenses": false,
					"vendorChunk": true
				},
				"en": {
					"localize": ["en"]
				},
				"nl": {
					"localize": ["nl"]
				},
				"fr": {
					"localize": ["fr"]
				}
			},
			"defaultConfiguration": "production"
		},
		"serve-ssr": {
			"executor": "@nx/angular:module-federation-dev-ssr",
			"configurations": {
				"development": {
					"browserTarget": "my-project:build:development",
					"serverTarget": "my-project:server:development"
				},
				"production": {
					"browserTarget": "my-project:build:production",
					"serverTarget": "my-project:server:production"
				},
				"en": {
					"browserTarget": "my-project:build:development,en",
					"serverTarget": "my-project:server:development,en"
				},
				"nl": {
					"browserTarget": "my-project:build:development,nl",
					"serverTarget": "my-project:server:development,nl"
				},
				"fr": {
					"browserTarget": "my-project:build:development,fr",
					"serverTarget": "my-project:server:development,fr"
				}
			},
			"defaultConfiguration": "development"
		},
	}
}
```

location of the translate files: 
![Image](https://github.com/user-attachments/assets/44820946-0f11-48bb-95e6-9ba052e75af4)

### Nx Report

 NX   Report complete - copy this into the issue template

Node   : 20.16.0
OS     : darwin-arm64
pnpm   : 9.12.0

nx                 : 19.3.0
@nx/js             : 19.5.6
@nx/jest           : 19.3.0
@nx/linter         : 19.3.0
@nx/eslint         : 19.3.0
@nx/workspace      : 19.3.0
@nx/angular        : 19.3.0
@nx/cypress        : 19.3.0
@nx/devkit         : 19.3.0
@nx/eslint-plugin  : 19.3.0
@nx/storybook      : 19.5.6
@nrwl/tao          : 19.3.0
@nx/web            : 19.5.6
@nx/webpack        : 19.3.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
@nx/storybook/plugin
---------------------------------------
Community plugins:
@ngrx/component      : 18.0.2
@ngrx/effects        : 18.0.2
@ngrx/entity         : 18.0.2
@ngrx/router-store   : 18.0.2
@ngrx/signals        : 18.0.2
@ngrx/store          : 18.0.2
@ngrx/store-devtools : 18.0.2
@storybook/angular   : 8.3.0
---------------------------------------
The following packages should match the installed version of nx
  - @nx/js@19.5.6
  - @nrwl/js@19.5.6
  - @nx/storybook@19.5.6
  - @nrwl/storybook@19.5.6
  - @nx/web@19.5.6
  - @nrwl/web@19.5.6

To fix this, run `nx migrate nx@19.5.6`

### Package Manager Version

pnpm 9.12.0

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

After seeing the message from the `nx report` command, I tried running `pnpm nx migrate nx@latest`. 

However that broke even more: There was at first an error about trying to run static remotes on port `-Infinity` (the remotes list is empty). Tried to solve this by  setting a `"staticRemotesPort": 3333` in the options for `serve-ssr`. After that, the process would start but get stuck right after generating bundles and before serving up the app without any error messages. It just hangs and never completes.

**Comment by Coly010** [comment]
Part of the issue here is the following config for your serve target:

```json
"en": {
  "buildTarget": "my-project:build:development,en"
},
"nl": {
  "buildTarget": "my-project:build:development,nl"
},
"fr": {
  "buildTarget": "my-project:build:development,fr"
}
```

This is trying to make use of a feature that does not exist in Nx, combining multiple configurations.

As such, your translation configurations are not going to be picked up and used correctly.
There is a chance that part of it is working as we call through to the angular builders which would support this syntax but Nx alone does not and therefore there can be a compat issue.

I'm not going to be able to debug this any further without an actual repository that i can pull and try this out on

**Comment by LorinRenodeyn2PO** [comment]
@Coly010 We came to the same conclusion, sorry for not commenting with our own feedback. Removing the `development,` part of the configuration made the translations show up. Leaving out the `development` bit and only leaving the localization does makes it unclear which config is actually being used (presumably the one set as default?).

But given that the NX builders are communicated to being "drop-in replacements" for the Angular ones, this behavior is very confusing when the [Angular docs have examples](https://angular.dev/guide/i18n/merge#build-for-french-example) that use the multiple configuration syntax.

**Comment by Coly010** [comment]
The Nx builders _are_. The Nx CLI is not a 1:1 to Angular CLI, and that's where the difference comes, but it tends to only be impactful when using Angular's built-in i18n solution. 

Sorry for any frustration here, but this is a design that will not change on our end. 

Glad you were able to get it working :)

**Comment by LorinRenodeyn2PO** [comment]
Adding some notes about Angular's i18n to the docs for the various builders (both esbuild/vite and webpack ones) or an easily findable how-to might save some people a lot of time and headache :)
