### ISSUE TITLE
Can't build the React Native app with use_frameworks enabled: normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-cxxreact' from project 'Pods')

### ISSUE THREAD

**Issue by PrimulaX** [nrwl/nx#28293]
### Current Behavior

I'm trying to build the app to run in the simulator on ios with `use_frameworks` enabled but getting this error: `react-native/ReactCommon/cxxreact/Instance.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-cxxreact' from project 'Pods')`

It works without `use_framworks`, it's interesting because I tried it with React Native CLI and it works but when I'm trying to use Nx it fails

### Expected Behavior

Should be able to build app with `use_frameworks` enabled.

### GitHub Repo

https://github.com/PrimulaX/nx_rn_repro_use_frameworks

### Steps to Reproduce

1. create Nx workspace with React Native: `npx create-nx-workspace happynrwl \
--preset=react-native \
--appName=mobile`
2. Enable `use_frameworks` in`Podfile`: `use_frameworks! :linkage => :static`
3. Run `pod install`
4. Run the application using: `npx nx run-ios mobile`

### Nx Report

Node           : 20.17.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.8.2

nx                 : 19.8.3
@nx/js             : 19.8.3
@nx/jest           : 19.8.3
@nx/linter         : 19.8.3
@nx/eslint         : 19.8.3
@nx/workspace      : 19.8.3
@nx/devkit         : 19.8.3
@nx/eslint-plugin  : 19.8.3
@nx/react          : 19.8.3
@nx/react-native   : 19.8.3
@nrwl/tao          : 19.8.3
@nx/web            : 19.8.3
@nx/webpack        : 19.8.3
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/react-native/plugin
@nx/eslint/plugin
@nx/webpack/plugin

### Failure Logs

The following build commands failed:
        CompileC /Users/primulax/Library/Developer/Xcode/DerivedData/Mobile-hgwwqwvapfygyxguxbtszdvttqxu/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-cxxreact.build/Objects-normal/arm64/Instance.o /Users/primulax/Desktop/happynrwl/node_modules/react-native/ReactCommon/cxxreact/Instance.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-cxxreact' from project 'Pods')
        Building workspace Mobile with scheme Mobile and configuration Debug
(2 failures)

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by PrimulaX** [comment]
It looks like Nx is doing something internally which breaks the `use_frameworks` usage

**Comment by xiongemi** [comment]
i just checkout your repo and run the command, it seems fine for me:

```
➜  nx_rn_repro_use_frameworks git:(master) ✗ npx nx run-ios mobile

> nx run mobile:run-ios

> react-native run-ios

info Found Xcode workspace "Mobile.xcworkspace"
info No booted devices or simulators found. Launching first available simulator...
info Launching iPhone 15 (iOS 17.5)
info Building (using "xcodebuild -workspace Mobile.xcworkspace -configuration Debug -scheme Mobile -destination id=307B8015-10F8-4972-85CA-46CA503C7CDE")
success Successfully built the app
2024-10-24 16:12:00.825 xcodebuild[46298:93019049]  DVTPlugInQuery: Requested but did not find extension point with identifier 'Xcode.InterfaceBuilderBuildSupport.PlatformDefinition'. This is programmer error; code should only request extension points that are defined by itself or its dependencies.
info Installing "/Users/emily/Library/Developer/Xcode/DerivedData/Mobile-eekpycoxaeunfnbeyfbdtaiyiqrr/Build/Products/Debug-iphonesimulator/Mobile.app
info Launching "org.reactjs.native.example.Mobile"
success Successfully launched the app

——————————————————————————————————————————————————————————————————————————————————————————————

 NX   Successfully ran target run-ios for project mobile (2m)
```

I run `nx pod-install mobile` at your workspace root to do pod install.
i also run `nx build-ios mobile` and it also works for me.

**Comment by PrimulaX** [comment]
Hey @xiongemi, thanks for the answer.

For me, every dependency is this way inside `Podfile.lock`: `boost (from `../node_modules/react-native/third-party-podspecs/boost.podspec`)`

Looks like the import path is different, how can this happen?

**Comment by xiongemi** [comment]
i think you run `pod install` at ios folder root. could you try to run `nx pod-install mobile` at workspace root?

**Comment by PrimulaX** [comment]
@xiongemi I did try your command

**Comment by xiongemi** [comment]
i pushed up a pr to your repo: https://github.com/PrimulaX/nx_rn_repro_use_frameworks/pull/1/files
I am able to run `npx nx run-ios mobile` after I run `nx pod-install mobile`

**Comment by PrimulaX** [comment]
@xiongemi Thanks, I'll check it out

**Comment by PrimulaX** [comment]
In the end, I could not solve this issue so I did eject from NX.
