### ISSUE TITLE
[RSPACK] reactRefresh is not disabled even after setting it to false

### ISSUE THREAD

**Issue by ReinGomezWP** [nrwl/nx#28297]
### Current Behavior

Using Rspack as builder in a React application
- configured the reactRefresh to turn off for all `tsx` files
- Deployed in the dev environment / ran preview-server in `development` mode
- Still see the reactRefresh errors
![Image](https://github.com/user-attachments/assets/f6259475-5977-483e-9c15-b08e4945cfed)

The config:
````
const getConfig = () => {
  return composePlugins(withNx(), withReact(), (config) => {
    // CSS and SASS
    config.experiments = { css: true };
    config.module = {
      ...config.module,
      rules: [
        ...config.module.rules,
        {
          test: /\.s[ac]ss$/i,
          use: [
            {
              loader: 'postcss-loader',
            },
          ],
          type: 'css/auto',
          exclude: '/node_modules/',
        },
        {
          test: /\.tsx$/,
          loader: 'builtin:swc-loader',
          exclude: /node_modules/,
          options: {
            jsc: {
              parser: {
                syntax: 'typescript',
                tsx: true,
              },
              transform: {
                react: {
                  runtime: 'automatic',
                  development: false,  // <---- TURNED OFF REFRESH
                  refresh: false,  // <---- TURNED OFF REFRESH
                },
              },
              externalHelpers: true,
            },
          },
          type: 'javascript/auto',
        },
        {
          test: /\.svg$/i,
          issuer: /\.[jt]sx?$/,
          use: ['@svgr/webpack'],
        },
        {
          test: /\.(woff|woff2|eot|ttf|otf|)$/,
          type: 'asset/resource',
          generator: {
            filename: 'fonts/[name]-[hash][ext][query]',
          },
        },
      ],
      parser: {
        ...config.module.parser,
        'css/auto': {
          namedExports: false,
        },
      },
      generator: {
        ...config.module.generator,
        'css/auto': {
          localIdentName: '[local]__[id]',
          exportsConvention: 'camel-case',
        },
      },
    };

    return config;
  });
};

module.exports = getConfig();
````

### Expected Behavior

It should work the same as in `production` mode where the refresh flag is turned off

### Steps to Reproduce

1. Make an rspack react app
2. Set the react refresh to false in config
3. Build and run in preview-server using the mode `development`

### Nx Report

Report complete - copy this into the issue template

Node           : 19.5.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 9.3.1

nx                 : 19.8.3
@nx/js             : 19.8.3
@nx/jest           : 19.8.3
@nx/linter         : 19.8.3
@nx/eslint         : 19.2.3
@nx/workspace      : 19.8.3
@nx/cypress        : 19.2.3
@nx/devkit         : 19.8.3
@nx/eslint-plugin  : 19.8.3
@nx/playwright     : 19.8.3
@nx/react          : 19.8.3
@nx/storybook      : 19.2.3
@nrwl/tao          : 19.8.3
@nx/vite           : 19.8.3
@nx/web            : 19.8.3
@nx/webpack        : 19.8.3
nx-cloud           : 19.1.0
typescript         : 5.5.4
---------------------------------------
Community plugins:
@nx/rspack : 19.8.0
---------------------------------------

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Hi @ReinGomezWP !

You would also need to modify the plugins if your intention is override what happens when you run with `mode = development` as we use this to add the ReactRefreshPlugin: https://github.com/nrwl/nx/blob/master/packages/rspack/src/utils/with-react.ts#L31

This is how the Rspack Docs recommend adding the plugin: https://rspack.dev/guide/tech/react#fast-refresh

This is a non-issue for Nx, so I'm going to close this.

**Comment by ReinGomezWP** [comment]
Thank you so  much for the comment!
