### ISSUE TITLE
Где пример для Kleiber?

### ISSUE THREAD

**Issue by kas-elvirov** [nrwl/nx#28298]
Я не понимаю язык выше, поэтому все удалил, пишу на русском

Я скачал исходники клайбера - ssh://git@НАШ_ДОМЕН:ПОРТ/kleiber/kleiber_front_main.git
Настроил npm, получил доступы и ноут. Кстати СберБук

И у меня есть задача PCAT-1640. И я застрял на пункте оборачивания проекта в монорепу. Подскажи пожалуйста что я делаю не так. Дублируйте пожалуйста сообщение в СберЧат

**Comment by Bullfrog1234** [comment]
Translated for others:

> I don't understand the language above, so I deleted everything, I write in Russian
> 
> I downloaded the Kleiber source code - ssh://git@OUR_DOMAIN:PORT/kleiber/kleiber_front_main.git
> I set up npm, got access and a laptop. By the way, SberBuk
> 
> And I have a PCAT-1640 task. And I got stuck at the point of turning the project into monorep. Please tell me what I'm doing wrong. Please duplicate the message in SberChat
