### ISSUE TITLE
build cache issue with ".nx" project cache

### ISSUE THREAD

**Issue by nhhockeyplayer** [nrwl/nx#28319]
### Current Behavior

build cache issue with ".nx" project cache

build fails when there is no .nx cache

### Expected Behavior

build should work seamlessly with no interruptions

### Steps to Reproduce

perform the following within your monorepo:

```
rm -rf .nx 
nx run-many --all --target=build --parallel
```

produces following erroneous output

```
 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktraces.
```

### Nx Report

nx report

 NX   Report complete - copy this into the issue template

Node           : 22.4.1
OS             : darwin-x64
Native Target  : x86_64-macos
yarn           : 1.22.22

nx (global)        : 19.8.4
nx                 : 19.8.4
@nx/js             : 19.8.4
@nx/jest           : 19.8.4
@nx/linter         : 19.8.4
@nx/eslint         : 19.8.4
@nx/workspace      : 19.8.4
@nx/angular        : 19.8.4
@nx/cypress        : 19.8.4
@nx/devkit         : 19.8.4
@nx/eslint-plugin  : 19.8.4
@nx/node           : 19.8.4
@nrwl/tao          : 19.8.4
@nx/web            : 19.8.4
@nx/webpack        : 19.8.4
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
---------------------------------------
Community plugins:
@nxext/capacitor     : 19.1.0
@nxext/ionic-angular : 19.1.0

### Failure Logs

```
 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktraces.
```

### Package Manager Version

yarn 1.22.22

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
I could not reproduce this. Try either the latest 20.0.2 version or the latest 19.8.6 patch version.

If you still have an issue, can you open a new issue with a repro link? Thanks!
