### ISSUE TITLE
@nx/js/plugins/jest/local-registry - listenAddress other than 'localhost' - startLocalRegistry does not resolve promise

### ISSUE THREAD

**Issue by RobbyRabbitman** [nrwl/nx#28314]
### Current Behavior

`startLocalRegistry` of `@nx/js/plugins/jest/local-registry` does not resolve when the host is different than `localhost`.

### Expected Behavior

I expect `--listenAddress='0.0.0.0'` of `@nx/js:verdaccio` to work with `startLocalRegistry` of `@nx/js/plugins/jest/local-registry`

### Steps to Reproduce

```json5
// project.json targets
{
  "executor": "@nx/js:verdaccio",
  "options": {
    "port": 4321,
    "listenAddress": "0.0.0.0",
    "clear": true,
    "config": "{projectRoot}/src/local-registry.yml",
    "storage": ".local-registry"
  }
}
```
`startLocalRegistry` has output:
```sh
Cleared local registry storage folder /Users/rob/Desktop/hdi-components/.local-registry
warn --- http address - http://0.0.0.0:4321/ - verdaccio/5.32.2
```
```json5
// project.json targets
{
  "executor": "@nx/js:verdaccio",
  "options": {
    "port": 4321,
    "clear": true,
    "config": "{projectRoot}/src/local-registry.yml",
    "storage": ".local-registry"
  }
}
```
`startLocalRegistry` has output:
```sh
Cleared local registry storage folder /Users/rob/Desktop/hdi-components/.local-registry
warn --- http address - http://localhost:4321/ - verdaccio/5.32.2
```

The `startLocalRegistry` promise does not resolve because the predicate never matches https://github.com/nrwl/nx/blob/c2af06e0a12529a5c3d1a09024ccc1fabf4e5604/packages/js/src/plugins/jest/start-local-registry.ts#L40-L71

I don't have a deep understanding of `@nx/js:verdaccio` and `verdaccio` itself but i guess the executor expects the log level at least to be on `warn` in order to parse the `registry` url of the following log statement: `warn --- http address - {url} - verdaccio/5.32.2`

A workaround for my project is a pnpm patch for now:
```ts
if (data.toString().includes('http address')) {
  const port = data.toString().match(/http:\/\/(?<host>[^:/]+)(:(?<port>\d+))?/)?.groups?.port;
```
In general I wonder whether its a good idea to hardcode `localhost` as the host - maybe it should also be parsed from the log statement aswell.

I also tried to use the listen property in the `verdaccio` config and omit the `port` arg in the `@nx/js:verdaccio` executor but its required - I guess it makes sense that it is required because it uses the port for the npm config shenanigans.
```yml
# verdaccio config
listen:
  - 0.0.0.0:4321 # no effect
```

 A alternative (which I haven't tested) may be to not use the `@nx/js:verdaccio` but `verdaccio`s cli itself and hard code the registry in the global `.npmrc` to a specific value e.g. `http://localhost:4321`. This may be fine for lots of use cases - for mine at least it would be.

### Nx Report

Node           : 20.15.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.11.0

nx                 : 19.6.4
@nx/js             : 19.6.4
@nx/linter         : 19.6.4
@nx/eslint         : 19.6.4
@nx/workspace      : 19.6.4
@nx/angular        : 19.6.4
@nx/cypress        : 19.6.4
@nx/devkit         : 19.6.4
@nx/eslint-plugin  : 19.6.4
@nx/storybook      : 19.6.4
@nrwl/tao          : 19.6.4
@nx/vite           : 19.6.4
@nx/web            : 19.6.4
@nx/webpack        : 19.6.4
typescript         : 5.4.4
---------------------------------------
Registered Plugins:
@hdi-components/tools-tsc-plugin
@hdi-components/tools-web-test-runner-plugin
@hdi-components/tools-storybook-test-plugin
@hdi-components/tools-stylelint-plugin
@nx/eslint/plugin
@nx/vite/plugin
@nx/storybook/plugin
---------------------------------------
Community plugins:
@compodoc/compodoc : 1.1.25
@storybook/angular : 8.3.5
ng-mocks           : 14.13.1
---------------------------------------
Local workspace plugins:
         @hdi-components/tools-playwright
         @hdi-components/tools-storybook
         @hdi-components/tools-publish
         @hdi-components/tools-release
         @hdi-components/tools-docker
         @hdi-components/tools-pack

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by hakalb** [comment]
Upvoting this as it's blocker for me when running plugins e2e where the plugin is used in a Docker build.

The plugin is deployed to the local registry but Docker can not pull it unless Verdaccio is listening on `0.0.0.0`.   
As you mentioned `startLocalRegistry` is hard coded to `localhost` only, which breaks the listener logic.

It's also not possible to define `listen` in Verdaccio config since `port` is required, which always adds `--listen` argument.

**Comment by RobbyRabbitman** [comment]
I have exactly your usecase. I'm running it in a Docker container and trying to access it from within the container. Im no docker/network expert but somehow localhost works but 127.0.0.1 is not - however on my Mac I can access it via 127.0.0.1 - stackoverflow says vardaccio needs to listen on all adresses, therefore the 0.0.0.0 but I wonder why it works on my host machine without the 0.0.0.0 - anybody here that can explain that?

**Comment by hakalb** [comment]
> I have exactly your usecase. I'm running it in a Docker container and trying to access it from within the container. Im no docker/network expert but somehow localhost works but 127.0.0.1 is not - however on my Mac I can access it via 127.0.0.1 - stackoverflow says vardaccio needs to listen on all adresses, therefore the 0.0.0.0 but I wonder why it works on my host machine without the 0.0.0.0 - anybody here that can explain that?

The key is to make the container look outside to the host since `localhost` on the container is not the same as your Mac.
To do that you need to use `.npmrc`,  `.yarnrc` or `.yarnrc.yml` depending on your package manager.

Hopefully these steps will make it work for you as well.

I replaced `startLocalRegistry` with a fixed version using the regular expression you provided
```ts
import { execSync, fork } from 'child_process';

type Options = {
  localRegistryTarget: string;
  storage: string;
  verbose?: boolean;
  clearStorage?: boolean;
};

export function localRegistry({
  localRegistryTarget,
  storage,
  verbose,
  clearStorage
}: Options) {
  if (!localRegistryTarget) {
    throw new Error(`localRegistryTarget is required`);
  }
  return new Promise((resolve, reject) => {
    const childProcess = fork(
      require.resolve('nx'),
      [
        ...`run ${localRegistryTarget} --location none --clear ${clearStorage ?? true}`.split(
          ' '
        ),
        ...(storage ? [`--storage`, storage] : [])
      ],
      { stdio: 'pipe' }
    );

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const listener = (data: any) => {
      if (verbose) {
        process.stdout.write(data);
      }
      const dataStr = String(data);

      // Fixed support for custom host
      const match = dataStr.match(/http:\/\/(?<host>[^:/]+)(:(?<port>\d+))?/);

      if (match) {
        const { host, port } = match.groups;
        console.log(`Local registry started on host '${host}' port '${port}'`);
        const registry = `http://${host}:${port}`;
        process.env.npm_config_registry = registry;

        execSync(
          `npm config set //${host}:${port}/:_authToken "secretVerdaccioToken"`,
          {
            windowsHide: true
          }
        );

        // yarnv1
        process.env.YARN_REGISTRY = registry;

        // yarnv2
        process.env.YARN_NPM_REGISTRY_SERVER = registry;
        process.env.YARN_UNSAFE_HTTP_WHITELIST = host;
        console.log('Set npm and yarn config registry to ' + registry);

        resolve(() => {
          childProcess.kill();
          execSync(`npm config delete //${host}:${port}/:_authToken`, {
            windowsHide: true
          });
        });
        childProcess?.stdout?.off('data', listener);
      }
    };

    childProcess?.stdout?.on('data', listener);

    childProcess?.stderr?.on('data', (data) => {
      process.stderr.write(data);
    });

    childProcess.on('error', (err) => {
      console.log('local registry error', err);
      reject(err);
    });

    childProcess.on('exit', (code) => {
      console.log('local registry exit', code);
      if (code !== 0) {
        reject(code);
      } else {
        resolve(() => {
          // noop
        });
      }
    });
  });
}

```

Then prepare 

- [ ] 

- [ ] one of the rc files

```yml
# .npmrc for npm/pnpm

registry=http://host.docker.internal:4873
//host.docker.internal:4873/:_authToken=secretVerdaccioToken
```

```yml
# .yarnrc for yarn classic

registry "http://host.docker.internal:4873"
//host.docker.internal:4873/:_authToken "secretVerdaccioToken"
```

```yml
# .yarnrc.yml for yarn berry

# only if you want to use node_modules
nodeLinker: node-modules

npmRegistryServer: "http://host.docker.internal:4873"
npmAuthToken: "secretVerdaccioToken"

unsafeHttpWhitelist:
- host.docker.internal
```

In your `Dockerfile` you have to copy the rc file before installing modules

```Dockerfile
# example code for npm

COPY package.json .npmrc ./

RUN npm install

COPY . .

RUN npx nx build my-app --no-cloud
```
