### ISSUE TITLE
RSpack shared libs is not working on default export using mjs

### ISSUE THREAD

**Issue by jmvtrinidad** [nrwl/nx#28326]
### Current Behavior

Installed package which is shared and using mjs unable to properly use default export

### Expected Behavior

should work the same way as webpack with module federation

### GitHub Repo

https://github.com/web-infra-dev/rspack/issues/8043

### Steps to Reproduce

1. Repro is on this issue https://github.com/web-infra-dev/rspack/issues/8043

### Nx Report

 NX   Report complete - copy this into the issue template

Node           : 22.4.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.12.0

nx (global)        : 19.8.0
nx                 : 20.0.0
@nx/js             : 19.8.3
@nx/jest           : 19.8.3
@nx/eslint         : 19.8.3
@nx/eslint-plugin  : 19.8.3
@nx/react          : 19.8.3
@nx/rspack         : 19.8.0
@nrwl/tao          : 19.8.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
---------------------------------------
The following packages should match the installed version of nx
  - @nx/js@19.8.3
  - @nx/jest@19.8.3
  - @nx/eslint@19.8.3
  - @nx/eslint-plugin@19.8.3
  - @nrwl/eslint-plugin-nx@19.8.3
  - @nx/react@19.8.3
  - @nx/rspack@19.8.0
  - @nrwl/tao@19.8.0

To fix this, run `nx migrate nx@20.0.0`

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
This is an issue in rspack and webpack: https://github.com/module-federation/core/issues/2995#issuecomment-2395609645

I would follow the comment linked for more information on a resolution to this
