### ISSUE TITLE
schematics/lint: migrate to non-deprecated eslint config format

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#2833]
all schematics generate/builders consume `.eslintrc` which is [*deprecated*](https://eslint.org/docs/user-guide/configuring#configuration-file-formats) according to official eslint docs.
![image](https://user-images.githubusercontent.com/1223799/78758560-9c19d400-797e-11ea-80c8-b4610507b4b2.png)

It would be nice to use non deprecated stuff.

- migration to `.eslintrc.json` looks like good start (non dynamic unlike .js configs) - migrations script should be easy to do as well

**Comment by JamesHenry** [comment]
This is resolved in https://github.com/nrwl/nx/pull/3763

**Comment by Hotell** [comment]
I'd prefer conditionally future tense, as nothing is resolved by a draft heh ✌️
