### ISSUE TITLE
`nx run` infix syntax not working with configurations

### ISSUE THREAD

**Issue by akwodkiewicz** [nrwl/nx#28335]
### Current Behavior

Given a target with configurations defined in `project.json` it is not possible to run a task with a specific configuration when using the infix syntax.

See "Steps to Reproduce" for the minimal reproduction.

- `nx run foobar:migration:run` works fine ✔ 

  ``` 
  > nx run foobar:migration:run 
  
  > echo running migrations
  
  running migrations
  
   NX   Successfully ran target migration for project foobar (38ms)
  ```
  
- `nx migration foobar` works fine ✔ 

  ```
  > nx run foobar:migration:run
  
  > echo running migrations
  
  running migrations
  
   NX   Successfully ran target migration for project foobar (40ms)
  ```
  
- `nx migration:run foobar` does not work 🐛 :x:

  ```
  NX   Cannot find configuration for task foobar:migration:run
  
  Pass --verbose to see the stacktrace.
  ```
  

### Expected Behavior

`nx migration:run foobar` as well as `nx migration:generate foobar` work in the same way as `nx run foobar:migration:run` and `nx run foobar:migration:generate`.

### Steps to Reproduce

Use this `project.json`:

```json
{
  "name": "foobar",
  "targets": {
    "migration": {
      "executor": "nx:run-commands",
      "defaultConfiguration": "run",
      "configurations": {
        "run": {
          "commands": ["echo running migrations"]
        },
        "generate": {
          "commands": ["echo generating migrations"]
        }
      }
    }
  }
}
```

### Nx Report

```
Node           : 18.20.4
OS             : darwin-arm64
Native Target  : aarch64-macos
yarn           : 1.22.22

nx (global)  : 19.6.4
nx           : 20.0.0
```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The same issue exists on both `19.6.4` and `20.0.0`.

**Comment by akwodkiewicz** [comment]
It looks as if this should be possible by replacing `<target>` with `<target>[:configuration]` in the `command`:


https://github.com/nrwl/nx/blob/1924bc30b6c5a46a526931162e5ceaa16b5689f7/packages/nx/src/command-line/run/command-object.ts#L32-L37

just like it's done in the regular `nx run` `CommandModule`:

https://github.com/nrwl/nx/blob/1924bc30b6c5a46a526931162e5ceaa16b5689f7/packages/nx/src/command-line/run/command-object.ts#L9-L10

I expect this magic is handled by `yargs`.

**Comment by akwodkiewicz** [comment]
Actually it won't work like I suggested above, because in my suggested infix version you can't have an optional thing in the middle.

But this would work, just tested locally:

```ts
    command: '$0 <targetWithOptionalConfig> [project] [_..]',
    describe: 'Run a target for a project.',
    handler: async (args) => {
        const [_, target, configuration] = /(.*?):(.*)/.exec(args.targetWithOptionalConfig);
        args.target = target;
        args.configuration = configuration;
        args.targetWithOptionalConfig = undefined;
```

The `?` in the regex makes the first group _lazy_, so multiple occurrences of `:` will be part of the 2nd group, for example: `a:b:c:d` => `a`, `b:c:d`

**Comment by jaysoo** [comment]
Hi @akwodkiewicz 👋 , thanks for taking the time to report this. 

At this point we're not looking to extend the syntax for how to run Nx targets. Note that you can pass `--configuration` when using the `nx <target> <project>` format. So, rather than running what you are suggesting:

```
nx migration:run foobar
```

You can use:

```
nx migration foobar --configuration=run
```

I'm going to close this issue, but if you have additional use-cases that aren't addressed then please open a new one, or open a discussion for a feature request. Thanks!
