### ISSUE TITLE
create-nx-workspace command not working though i change the updated version of angular and nrwl schematics, node and npm to the latest til now it's not working 

### ISSUE THREAD

**Issue by jeykarlokes** [nrwl/nx#2834]
[
![Screenshot from 2020-04-08 15-01-53](https://user-images.githubusercontent.com/26407094/78768743-fa0fe100-79a9-11ea-8c22-625ac6b6424f.png)
](url

kindly help me to sort out this issue when i tried using 
create-nx-workspace sample

shows command not found.
![Screenshot from 2020-04-08 15-04-47](https://user-images.githubusercontent.com/26407094/78768976-4eb35c00-79aa-11ea-903d-84fc22a5a0aa.png)

**Comment by FrozenPandaz** [comment]
It seems like you didn't install `create-nx-workspace` globally.

Can you please run `npx create-nx-workspace@latest sample` instead so that it pulls it from npm and runs it?

**Comment by jeykarlokes** [comment]
Thanks for replying frozen pandas  and that works well..
