### ISSUE TITLE
Verdaccio doesn't clean npm config

### ISSUE THREAD

**Issue by zoran995** [nrwl/nx#28353]
### Current Behavior

nx verdaccio sets npm config but doesn't clean it up

### Expected Behavior

nx should clean the npm config after user kills the process

### Steps to Reproduce

1. run verdaccio local-registry
2. check that the npm config is updated
3. kill the process
4. check that the npm config is not cleaned

### Nx Report

 NX   Report complete - copy this into the issue template

Node           : 20.9.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.1.0

nx                 : 19.6.4
@nx/js             : 19.6.4
@nx/jest           : 19.6.4
@nx/linter         : 19.6.4
@nx/eslint         : 19.6.4
@nx/workspace      : 19.6.4
@nx/cypress        : 19.6.4
@nx/devkit         : 19.6.4
@nx/eslint-plugin  : 19.6.4
@nx/react          : 19.6.4
@nx/rollup         : 19.6.4
@nx/storybook      : 19.6.4
@nrwl/tao          : 19.6.4
@nx/web            : 19.6.4
@nx/webpack        : 19.6.4
typescript         : 5.6.2

---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin
@nx/jest/plugin
@nx/rollup/plugin
@nx/storybook/plugin

### Package Manager Version

10.1.0

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by alancpazetto** [comment]
Hi everyone! 

I'm getting this error too in last versions of NX.

Investigating I found the problem, I will open a PR with bugfix.

Can anyone assign this issue to me?
