### ISSUE TITLE
Generated library has eslint.config.js for wrong version of ESLint

### ISSUE THREAD

**Issue by e-oz** [nrwl/nx#28359]
### Current Behavior

We use ESLint 8 because of [this issue](https://github.com/cartant/eslint-plugin-rxjs-angular/issues/23).
Nx 20 generates incorrect config, example:
```ts
const nx = require('@nx/eslint-plugin');
const baseConfig = require('../../../eslint.config.js');

module.exports = [
  ...baseConfig,
  ...nx.configs['flat/angular'],
  ...nx.configs['flat/angular-template'],
  {
    files: ['**/*.ts'],
    rules: {
      '@angular-eslint/directive-selector': [
        'error',
        {
          type: 'attribute',
          prefix: 'cr',
          style: 'camelCase',
        },
      ],
      '@angular-eslint/component-selector': [
        'error',
        {
          type: 'element',
          prefix: 'cr',
          style: 'kebab-case',
        },
      ],
    },
  },
  {
    files: ['**/*.html'],
    // Override or add rules here
    rules: {},
  },
];
```
After that Nx can not run any command, and fails with
```
 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
```

### Expected Behavior

Please check ESLint version and generate a correct config.
Example of correct config:
```
const { FlatCompat } = require('@eslint/eslintrc');
const js = require('@eslint/js');
const baseConfig = require('../../../eslint.config.js');

const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
});

module.exports = [
  ...baseConfig,
  ...compat
    .config({
      extends: [
        'plugin:@nx/angular',
        'plugin:@angular-eslint/template/process-inline-templates',
      ],
    })
    .map((config) => ({
      ...config,
      files: ['**/*.ts'],
      rules: {
        ...config.rules,
        '@angular-eslint/directive-selector': [
          'error',
          {
            type: 'attribute',
            prefix: 'cr',
            style: 'camelCase',
          },
        ],
        '@angular-eslint/component-selector': [
          'error',
          {
            type: 'element',
            prefix: 'cr',
            style: 'kebab-case',
          },
        ],
      },
      languageOptions: {
        parserOptions: {
          project: ['libs/shared/delivery-address/tsconfig.*?.json'],
        },
      },
    })),
  ...compat
    .config({ extends: ['plugin:@nx/angular-template'] })
    .map((config) => ({
      ...config,
      files: ['**/*.html'],
      rules: {
        ...config.rules,
      },
    })),
];
```

### Steps to Reproduce

1. Create Angular workspace with ESLint 8
2. run `nx g @nx/angular:library`

### Nx Report

 NX   Report complete - copy this into the issue template

Node           : 22.9.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.8.3

nx                 : 20.0.0
@nx/js             : 20.0.0
@nx/jest           : 20.0.0
@nx/eslint         : 20.0.0
@nx/workspace      : 20.0.0
@nx/angular        : 20.0.0
@nx/devkit         : 20.0.0
@nx/eslint-plugin  : 20.0.0
@nx/playwright     : 20.0.0
@nx/vite           : 20.0.0
@nx/web            : 20.0.0
@nx/webpack        : 20.0.0
typescript         : 5.6.2
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/eslint/plugin
---------------------------------------

### Failure Logs

⚠️ Unable to construct project graph.
  Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  An error occurred while processing files for the @nx/eslint/plugin plugin.
- libs/shared/copy-to-clipboard/eslint.config.js: Cannot find module 'angular-eslint'
Require stack:
  - /Users/oz/repos/project/workspace-name/node_modules/@nx/eslint-plugin/src/flat-configs/angular.js
- /Users/oz/repos/project/workspace-name/node_modules/@nx/eslint-plugin/src/index.js
- /Users/oz/repos/project/workspace-name/libs/shared/copy-to-clipboard/eslint.config.js
Error: Cannot find module 'angular-eslint'
Require stack:
  - /Users/oz/repos/project/workspace-name/node_modules/@nx/eslint-plugin/src/flat-configs/angular.js
- /Users/oz/repos/project/workspace-name/node_modules/@nx/eslint-plugin/src/index.js
- /Users/oz/repos/project/workspace-name/libs/shared/copy-to-clipboard/eslint.config.js
at Module._resolveFilename (node:internal/modules/cjs/loader:1248:15)
at Module._load (node:internal/modules/cjs/loader:1074:27)
at TracingChannel.traceSync (node:diagnostics_channel:315:14)
at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
at Module.require (node:internal/modules/cjs/loader:1339:12)
at require (node:internal/modules/helpers:135:16)
at Object.<anonymous> (/Users/oz/repos/project/workspace-name/node_modules/@nx/eslint-plugin/src/flat-configs/angular.js:4:50)
  at Module._compile (node:internal/modules/cjs/loader:1546:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
  at Module.load (node:internal/modules/cjs/loader:1317:32)

### Package Manager Version

npm 10.8.3

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by e-oz** [comment]
Related: https://github.com/nrwl/nx/issues/28388

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Could you provide a repro?

I tried to reproduce the issue by creating an Nx v19.5.0 workspace (which comes with ESLint v8), migrating it to the latest Nx version, and then generating a lib, but I couldn't. It does generate a newer configuration like the one you shared, but that's compatible with ESLint 8.57.x. The error you're getting is due to a missing `angular-eslint` package, which the `@nx/js:library` generator installs.

FWIW, this is the repo I created when trying to reproduce the issue: https://github.com/leosvelperez/28359-nx-angular-eslint-flat-config. I might be missing some important detail to reproduce the issue. Please take a look and let me know.

**Comment by e-oz** [comment]
Nice, and I still manually fixing every generated eslint config...
