### ISSUE TITLE
Cannot migrate to NX 20.0.0

### ISSUE THREAD

**Issue by phihochzwei** [nrwl/nx#28352]
### Current Behavior

When trying to migrate from 19.8.3 we receive the following message

`Fetching meta data about packages.
It may take a few minutes.
Fetching nx@20.0.0
Fetching @nrwl/tao@20.0.0
Unable to fetch migrations for @nrwl/tao@20.0.0: Command failed: npm install @nrwl/tao@20.0.0
npm error code ETARGET
npm error notarget No matching version found for @nrwl/tao@20.0.0.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.

npm error A complete log of this run can be found in: /Users/XXX/.npm/_logs/2024-10-08T05_24_08_689Z-debug-0.log

 NX   The migrate command failed.

 NX   Cannot read properties of undefined (reading 'schematics')`

### Expected Behavior

Navigation runs smoothly :) 

### Steps to Reproduce

1. nx migrate latest

### Nx Report

 NX   Report complete - copy this into the issue template

Node           : 22.2.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.7.0

nx                 : 19.8.3
@nx/js             : 19.8.3
@nx/jest           : 19.8.3
@nx/linter         : 19.8.3
@nx/eslint         : 19.8.3
@nx/workspace      : 19.8.3
@nx/angular        : 19.8.3
@nx/cypress        : 19.8.3
@nx/devkit         : 19.8.3
@nx/eslint-plugin  : 19.8.3
@nx/nest           : 19.8.3
@nx/node           : 19.8.3
@nx/plugin         : 19.8.3
@nx/storybook      : 19.8.3
@nrwl/tao          : 19.8.3
@nx/web            : 19.8.3
@nx/webpack        : 19.8.3
typescript         : 5.5.3
---------------------------------------
Registered Plugins:
@nx/storybook/plugin
---------------------------------------
Community plugins:
@ngrx/component      : 18.0.2
@ngrx/effects        : 18.0.2
@ngrx/entity         : 18.0.2
@ngrx/router-store   : 18.0.2
@ngrx/schematics     : 18.0.2
@ngrx/store          : 18.0.2
@ngrx/store-devtools : 18.0.2
@storybook/angular   : 8.2.9
ng-mocks             : 14.13.0
ng2-charts           : 6.0.1
---------------------------------------

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jeoffreybakker** [comment]
I had the same with `@nrwl/js` library and found out it has been renamed to `@nx/js`. After updating `@nrwl/js` to `@nx/js` in my package.json I was able to upgrade.

**Comment by phihochzwei** [comment]
Thanks mate. That solved it.

**Comment by phihochzwei** [comment]
Well, not yet :) 

`npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/@nx%2ftao - Not found
npm error 404
npm error 404  '@nx/tao@20.0.0' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
`

**Comment by jeoffreybakker** [comment]
Well looking on https://www.npmjs.com/package/@nrwl/tao it states it has been merged with nx. So maybe you don't need this package at all, but I'm not sure as information is a bit scarce.
