### ISSUE TITLE
serve with devRemoted replaces hyphens with underscores

### ISSUE THREAD

**Issue by altodd-cintra** [nrwl/nx#28354]
### Current Behavior

`nx serve app-shell --devRemotes=onboarding-documents`

results in

> Cannot find remote "onboarding_documents". Check that the remote name is correct in your module federation config file.

Note the hyphen in the project name has been replaced with an underscore

### Expected Behavior

app is served

### Steps to Reproduce

1.

### Nx Report

 NX   Report complete - copy this into the issue template

Node           : 20.13.1
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.5.2

nx (global)        : 20.0.0
nx                 : 20.0.0
@nx/js             : 20.0.0
@nx/jest           : 20.0.0
@nx/eslint         : 20.0.0
@nx/workspace      : 20.0.0
@nx/angular        : 20.0.0
@nx/cypress        : 20.0.0
@nx/devkit         : 20.0.0
@nx/eslint-plugin  : 20.0.0
@nx/web            : 20.0.0
@nx/webpack        : 20.0.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Intentional and will be better supported by: https://github.com/nrwl/nx/pull/28401
