### ISSUE TITLE
workspace schematics: create/move file to projects sibling directory

### ISSUE THREAD

**Issue by sroettering** [nrwl/nx#2836]
- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

I want to generate some sql files containing test data using schematics. However, my repository is set up such that the nx project is a sibling of the server (java) project where the sql files belong.
I did not get schematics to create a file outside of the nx project directory which I guess is a built-in security feature.
Is there another way I could solve that problem? By changing some rootDir value for example?

**Comment by jdpearce** [comment]
Probably the simplest way to do this would be to copy them out of the Nx workspace after the schematic has run its course (i.e. create a `package.json` script something like `nx workspace-schematic my-schematic && cp mysqlfiles/* ../myotherdir`)

If you want to go *really* overboard though, you could register a `TaskExecutor`, e.g.

```ts
export default function(options: SchematicOptions): Rule {
  return chain([
    (tree: Tree, _context: SchematicContext): Tree => {
      tree.create('newfile.txt', 'This is a new file');
      return tree;
    },
    (_host: Tree, context: SchematicContext) => {
      const engineHost = (context.engine.workflow as any)._engineHost;
      engineHost.registerTaskExecutor(createCopyTask());
      context.addTask(new RunCopyTask());
    }
  ]);
}

interface CopyTaskOptions {}

class RunCopyTask implements TaskConfigurationGenerator<CopyTaskOptions> {
  constructor() {}

  toConfiguration(): TaskConfiguration<CopyTaskOptions> {
    return {
      name: 'RunCopy',
      options: {}
    };
  }
}

function createCopyTask(): TaskExecutorFactory<CopyTaskOptions> {
  return {
    name: 'RunCopy',
    create: () => {
      return Promise.resolve<TaskExecutor<CopyTaskOptions>>(
        (_options: CopyTaskOptions, context: SchematicContext) => {
          return new Observable(obs => {
            spawn('cp', ['newfile.txt', '..']).on('close', (code: number) => {
              if (code === 0) {
                context.logger.info('Copied.');
                obs.next();
                obs.complete();
              } else {
                const message = `Copy failed, see above.`;
                obs.error(new Error(message));
              }
            });
          });
        }
      );
    }
  };
}
```

Personally, I'd recommend the package script. 😆

**Comment by sroettering** [comment]
Thanks, I was hoping for a different answer, but will go with the package.json solution for now.
