### ISSUE TITLE
MFE schematic broken version 20 cannot generate hosts or remotes

### ISSUE THREAD

**Issue by nhhockeyplayer** [nrwl/nx#28370]
### Current Behavior

MFE schematic broken version 20 cannot generate hosts or remotes

nx-console is not working

### Expected Behavior

should be able to model hosts and remotes at high velocity

### Steps to Reproduce

try and create host

nx-console UI eventually quite trapped in nx-reset error

### Nx Report

nx report

 NX   Report complete - copy this into the issue template

Node           : 22.4.1
OS             : darwin-x64
Native Target  : x86_64-macos
yarn           : 1.22.22

nx (global)        : 20.0.0
nx                 : 20.0.0
@nx/js             : 20.0.0
@nx/jest           : 20.0.0
@nx/eslint         : 20.0.0
@nx/workspace      : 20.0.0
@nx/angular        : 20.0.0
@nx/cypress        : 20.0.0
@nx/devkit         : 20.0.0
@nx/eslint-plugin  : 20.0.0
@nx/node           : 20.0.0
@nx/storybook      : 20.0.0
@nx/web            : 20.0.0
@nx/webpack        : 20.0.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
---------------------------------------
Community plugins:
@ionic/angular        : 8.3.2
@ngrx/component       : 18.0.2
@ngrx/component-store : 18.0.2
@ngrx/effects         : 18.0.2
@ngrx/entity          : 18.0.2
@ngrx/operators       : 18.0.2
@ngrx/router-store    : 18.0.2
@ngrx/schematics      : 18.0.2
@ngrx/store           : 18.0.2
@ngrx/store-devtools  : 18.0.2
@nxext/capacitor      : 19.1.2
@nxext/ionic-angular  : 19.1.2

### Failure Logs

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:host --directory=apps/host --name=host --backendProject=bff --no-interactive --dry-run

 NX  Generating @nx/angular:host

 NX   NOTE: This generator does not support --dry-run. If you are running this in Nx Console, it should execute fine once you hit the "Generate" button.

Pass --verbose to see the stacktrace.

### Package Manager Version

yarn 1.22.22

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Is there any way you could record a video of this occurring? 

Also, are you using VSCode or an IntelliJ IDE?

**Comment by nhhockeyplayer** [comment]
JETBRAINS WEBSTORM latest

this issue https://github.com/nrwl/nx/issues/28388
 should be prioritized as IMMEDIATE patch and fix it immediately
it covers alot of what other users are reporting in their issues failing locally as of recent

closing this ticket as duplicate

hopefully they will patch and get this one first https://github.com/nrwl/nx/issues/28388
 to fix everything under the hood

**Comment by nhhockeyplayer** [comment]
> Is there any way you could record a video of this occurring?
> 
> Also, are you using VSCode or an IntelliJ IDE?

Hi Colin

This might help... I cant be the only person stuck on this release and migration.

Can I grant you access to my repo and you can take a peek at it?

https://github.com/nhhockeyplayer/meanstacknh

My repo is really stuck in the nx-reset trap... nx-console refuses to render
maybe you can pin point something?
