### ISSUE TITLE
Environment variable `NX_WORKSPACE_DATA_CACHE_DIRECTORY` is not used

### ISSUE THREAD

**Issue by MrChocolatine** [nrwl/nx#28389]
### Current Behavior

Custom workspace data directory is not respected.

### Expected Behavior

Custom workspace data directory respected.

### Steps to Reproduce

In your [page about environment variables](https://nx.dev/reference/environment-variables), you mention `NX_WORKSPACE_DATA_CACHE_DIRECTORY`:

![Image](https://github.com/user-attachments/assets/a6b4d05f-7901-41a0-aef5-9771fb4a80a5)

However, in your codebase this variable is not used at all.

Instead, the variable `NX_WORKSPACE_DATA_DIRECTORY` is used (with a fallback to `NX_PROJECT_GRAPH_CACHE_DIRECTORY`, which I believe was used for NX version 17)

_From: https://github.com/nrwl/nx/blob/20.0.0/packages/nx/src/utils/cache-directory.ts#L85-L92_
![Image](https://github.com/user-attachments/assets/f42f228d-fd43-4bcd-9205-1657a6c54e8d)

### Nx Report

n/a

### Failure Logs

None

### Package Manager Version

Yarn v1.22.22

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I use git-worktrees heavily in my daily work, I have several of them.
I already have `NX_CACHE_DIRECTORY` configured to share NX data between my git worktrees, for better performances.

Following your documentation, I used to have `NX_WORKSPACE_DATA_CACHE_DIRECTORY` configured the same way, but it appears not being used at all, resulting in poor performances.

Now I have `NX_WORKSPACE_DATA_DIRECTORY` configured instead of `NX_WORKSPACE_DATA_CACHE_DIRECTORY`.

---

To add to that, when I am inside of one of my worktree, I still have `.nx/workspace-data` built and filled with data, even if `NX_WORKSPACE_DATA_DIRECTORY` is set to point at my main worktree. (where I also have `.nx/workspace-data`)

Is that expected?

**Comment by jaysoo** [comment]
@isaacplmann The docs should be updated with `NX_WORKSPACE_DATA_DIRECTORY ` instead of `NX_WORKSPACE_DATA_CACHE_DIRECTORY`.

**Comment by isaacplmann** [comment]
@MrChocolatine I tried this out and if I set the `NX_WORKSPACE_DATA_DIRECTORY` in a `.env` file it correctly puts the workspace data in the directory I specified.  I did run `nx reset` to make sure that the daemon restarts and uses the new value.  Setting the env variable only on the command line won't work because the daemon runs on a background process.

**Comment by MrChocolatine** [comment]
@isaacplmann thanks for your reply.

I have `NX_WORKSPACE_DATA_DIRECTORY` set in my `.zshenv` file, I am not setting it when running commands in my terminal.

**Comment by isaacplmann** [comment]
Nx doesn't read the `.zshenv` file.  Setting a variable there is the equivalent of setting the var in the terminal.  Here is the full list of env files it will read:
https://nx.dev/recipes/tips-n-tricks/define-environment-variables

**Comment by MrChocolatine** [comment]
> Nx doesn't read the `.zshenv` file. Setting a variable there is the equivalent of setting the var in the terminal. Here is the full list of env files it will read: https://nx.dev/recipes/tips-n-tricks/define-environment-variables

This is rather confusing.
`zshenv` is a system file, variables declared in there are loaded and available in shells.

**Comment by isaacplmann** [comment]
Correct.  That's why the environment variable is loaded as if you prefixed your terminal commands with it.  But the daemon process is not triggered directly by the terminal and it doesn't know about the `.zshenv` file.

You're experiencing the same situation as if you prefixed every Nx command with `NX_WORKSPACE_DATA_DIRECTORY=some/path`.

**Comment by MrChocolatine** [comment]
> Correct. That's why the environment variable is loaded as if you prefixed your terminal commands with it. But the daemon process is not triggered directly by the terminal and it doesn't know about the `.zshenv` file.
> 
> You're experiencing the same situation as if you prefixed every Nx command with `NX_WORKSPACE_DATA_DIRECTORY=some/path`.

I see, thank you very much for this @isaacplmann :-) .

**Comment by MrChocolatine** [comment]
This is weird, I just tried using an `.env` file instead of my `.zshenv` and it really did not give any good result, all the contrary.

My git-worktrees setup is as follow:

```
- Folder `work`
  |_ Folder `master` (the main worktree)
  |_ Folder `feature-1`
  |_ ...and so on...
```

Initially, as explained above, I had this in my `.zshenv` file:

```bash
export NX_CACHE_DIRECTORY="$HOME/ <long path> /work/master/.nx/cache"
export NX_WORKSPACE_DATA_DIRECTORY="$HOME/ <long path> /work/master/.nx/workspace-data"
```

Overall things were fine. Running `yarn` from one of the worktree was reusing NX from the `master` folder.

Following your advice, I removed `NX_CACHE_DIRECTORY` and `NX_WORKSPACE_DATA_DIRECTORY` from my `.zshenv` and declared them in an `.env` file:

```
NX_CACHE_DIRECTORY="/Users/ <long path> /work/master/.nx/cache"
NX_WORKSPACE_DATA_DIRECTORY="/Users/ <long path> /work/master/.nx/workspace-data"
```

Result when running `yarn` in one of the worktree: cache and workspace data from the `master` folder are not reused. Folders `.nx/cache/` and `.nx/workspace-data/` recreated in my worktree.

I tried several times, while moving the `.env` file:
- `/Users/ <long path> /work/feature-1/.env`
- `/Users/ <long path> /work/master/.env`
- `/Users/ <long path> /work/.env`
- `$HOME/.env`

Same result, cache and workspace data from `master` not reused.

What am I missing?
