### ISSUE TITLE
Global preview-head.html for Storybook

### ISSUE THREAD

**Issue by twittwer** [nrwl/nx#2838]
## Expected Behavior

If I add a `preview-head.html` in the root `.storybook` directory, to add custom styles (like Angular Material Icons) to Storybook, I would expect them to be applied to all storybook instances in the workspace.

## Current Behavior

I have to add the same `preview-head.html` in the `.storybook` directory of all libs.

**Comment by mandarini** [comment]
Hi @twittwer . It's in our plans to address this issue with a schematic, possibly, along with other extra config files for Storybook. I'll keep this issue updated.

**Comment by huv1k** [comment]
This is a feature request, I think stale bot should ignore these.

**Comment by kpaxton** [comment]
Is there a ticket to have a lib's preview.js inherit from the root? Also to modify the preview.js to represent what is suggested now by Storybook? Or should it be included in this?
```
export const parameters = {
...
};

export const decorators = [
...
];
```

**Comment by wizardnet972** [comment]
@twittwer for now, you can use this solution: (for global use. at `.storybook` folder in the root)
```
module.exports = {
  stories: ...,
  addons: ...,
  previewHead: (head) => `
    ${head}
    <style>
       * {border: 1px solid red;}
    </style>
  ` 
  ....
```

**Comment by mandarini** [comment]
Hi there! I am closing this, since the solution provided by @wizardnet972 is perfectly valid. Since `previewHead` option exists in `main.js` config, you can add your global preview-head HTML in the root `.storybook/main.js`.

[Documentation on how to configure previewHead/preview-head here](https://storybook.js.org/docs/react/addons/writing-presets#previewmanager-templates).

**Comment by alexciesielski** [comment]
Unfortunately I am getting a type error when using `previewHead` inside `main.ts`.

- `@nrwl/storybook: 14.5.8`
- `@storybook/angular: 6.5.9`

![image](https://user-images.githubusercontent.com/17651898/186384750-2644ed80-53f1-4fc8-88e6-f24c4f69c95a.png)

**Comment by mandarini** [comment]
Hi there @alexciesielski ! This is an issue with Storybook, not with Nx. I am looking into fixing it, however, together with the Storybook team! :)
