### ISSUE TITLE
Nx cache may infinitely recurse

### ISSUE THREAD

**Issue by sepruko** [nrwl/nx#28393]
### Current Behavior

The task cache does not ignore the cache directory. This may cause Nx to get stuck creating an infinitely recursive directory structure (which is a pain to remove).

### Expected Behavior

The task cache always ignores the configured cache directory, irrespective of the task's outputs.

### GitHub Repo

https://github.com/sepruko/nx-cache-recurse

### Steps to Reproduce

1. Create an Nx workspace, whose root contains a project.
2. Create a target for the root project with `cache` as `true` and `outputs` as `["{projectRoot}/**/*"]`.
3. Attempt to run the target with `nx run <project-name>:<target-name>`.
4. The command will not exit, meanwhile Nx is creating a recursive directory tree in the cache.

### Nx Report

Node           : 20.18.0
OS             : win32-x64
Native Target  : x86_64-windows
pnpm           : 9.12.1

nx          : 20.0.0
@nx/js      : 20.0.0
@nx/devkit  : 20.0.0
@nx/plugin  : 20.0.0
@nx/vite    : 20.0.0
typescript  : 5.6.2

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
this happens because in `cache.rs`'s put function throw an error `**Error: File name too long (os error 63)**`
