### ISSUE TITLE
"fork-ts-checker-webpack-plugin" plugin is not working on Rspack applications

### ISSUE THREAD

**Issue by ReinGomezWP** [nrwl/nx#28391]
### Current Behavior

I've been trying to use the [fork-ts-checker-webpack-plugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin) as it should be supported by RSpack according to the [documentation](https://rspack.dev/guide/compatibility/plugin)

I am getting the error below:
![Image](https://github.com/user-attachments/assets/cf4da873-5d46-456d-ae47-ba94e1389dcc)

### Expected Behavior

The plugin should work

### Steps to Reproduce

1. Create an Rspack application
2. Set the following configuration
````
import { composePlugins, withNx, withReact } from '@nx/rspack';
import ForkTsCheckerWebpackPlugin from 'fork-ts-checker-webpack-plugin';

const getConfig = () => {
  return composePlugins(withNx(), withReact(), (config) => {
    // Plugins
    config.plugins = [
      ...config.plugins,
      ...[
        new ForkTsCheckerWebpackPlugin({
          typescript: {
            configFile: './apps/main-app/tsconfig.app.json',
          },
        }),
      ],
    ];

    return config;
  });
};
````

### Nx Report

Node           : 19.5.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.5.0

nx                 : 19.8.3
@nx/js             : 19.8.3
@nx/jest           : 19.8.3
@nx/linter         : 19.8.3
@nx/eslint         : 19.2.3
@nx/workspace      : 19.8.3
@nx/cypress        : 19.2.3
@nx/devkit         : 19.8.3
@nx/eslint-plugin  : 19.8.3
@nx/playwright     : 19.8.3
@nx/react          : 19.8.3
@nx/storybook      : 19.2.3
@nrwl/tao          : 19.8.3
@nx/vite           : 19.8.3
@nx/web            : 19.8.3
@nx/webpack        : 19.8.3
nx-cloud           : 19.1.0
typescript         : 5.5.4
---------------------------------------
Community plugins:
@nx/rspack : 19.8.0
---------------------------------------

### Operating System

- [x] macOS
- [x] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by ReinGomezWP** [comment]
Same error happens for `dotenv-webpack`, another supported plugin
![Image](https://github.com/user-attachments/assets/eef86b46-5e8b-4c06-8f61-9b613efd9871)

**Comment by ndcunningham** [comment]
Hi, thanks for opening an issue

That error would suggests that something is going wrong with the way you are importing or using the `ForkTsCheckerWebpackPlugin`.

To fix this you need to use `require` instead of `import` for your plugin
