### ISSUE TITLE
schematics problem with new angular devkit: Cannot find module '@schematics/angular/strings'

### ISSUE THREAD

**Issue by yuriyp** [nrwl/nx#284]
There are two files which depend on "@schematics/angular/strings"
packages/schematics/src/collection/application/index.ts
packages/schematics/src/collection/app/index.ts

while commit "refactor(@angular-devkit/core): expose string utils as a scoped names…" at angular/devkit removed packages/schematics/angular/strings.ts
https://github.com/angular/devkit/commit/0776a4eddf05cab79b6e118cef4758c1cf04f1ec#diff-2c20d1bd414640ddaa31aa6902fbecb6

It looks that now it is part of @angular-devkit/core: devkit/packages/angular_devkit/core/src/utils/strings.ts

So, nx schematics does not work with new version of angular devkit

**Comment by jwuliger** [comment]
Oh man, I just spent over an hour trying to figure this error out. Thanks, @yuriyp for your insight. now I need to find a workaround.

I can report the same problem. My Env:

```
Angular CLI: 1.6.5 (NX Version)
Node: 8.9.4
OS: win32 x64
Angular: 5.2.6
```

**Comment by ThomasBurleson** [comment]
Please retry with CLI 1.7.2 and Nx v0.8.0. Will reopen if you confirm the issue still exists with those recent versions.
