### ISSUE TITLE
`.prettierrc`/`prettierrc.js` issues when adding `"plugins": ["prettier-plugin-tailwindcss"]`

### ISSUE THREAD

**Issue by willdspd** [nrwl/nx#28422]
### Current Behavior

I'm attempting to add `prettier-plugin-tailwindcss` to my NX monorepo. I found [this](https://github.com/nrwl/nx/issues/17271) Github issue which suggests converting `.prettierrc` to `prettierrc.js` and adding `plugins: ["prettier-plugin-tailwindcss"]`. This didn't work for me, and when digging a bit deeper I found the following:

- When placing `"plugins": ["prettier-plugin-tailwindcss"]` in `.prettierrc`, Prettier stops working completely in my repo
- When converting `.prettierrc` to `prettierrc.js`, Prettier works, but settings aren’t applied (e.g. `singleQuote: true`)
- When placing `plugins: ["prettier-plugin-tailwindcss"]` in `prettierrc.js`, it seems to have no effect, just like `singleQuote: true`

"nx": "16.1.0"
"@nx/next": "16.1.0"
"@nx/eslint-plugin": "16.1.0"
"@nx/js": "16.1.0"
"@nx/linter": "16.1.0"
"@nx/react": "16.1.0"
"@nx/web": "16.1.0"
"@nx/workspace": "16.1.0"
"prettier": "^2.8.4"
"prettier-plugin-tailwindcss": "^0.5.12"
"tailwindcss": "^3.4.1"
"eslint-config-prettier": "8.1.0"

### Expected Behavior

Na

### Steps to Reproduce

Na

### Nx Report

Na

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by khalilou88** [comment]
You are using version 2 of prettier. The plugin array is for version 3

**Comment by willdspd** [comment]
That's worked! And I didn't even have to convert .prettierrc to prettierrc.js. Thanks @khalilou88
