### ISSUE TITLE
npm install fails after fresh install with "create-nx-workspace" with Next preset

### ISSUE THREAD

**Issue by aggiustino** [nrwl/nx#28423]
### Current Behavior

`npm install` doesn't work after a fresh install with Next preset.

Error thrown:
```
npm warn ERESOLVE overriding peer dependency
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: eslint-config-next@14.2.3
npm error Found: eslint@9.12.0
npm error node_modules/eslint
npm error   peer eslint@"^8.56.0" from @typescript-eslint/parser@7.2.0
npm error   node_modules/eslint-config-next/node_modules/@typescript-eslint/parser
npm error     @typescript-eslint/parser@"^5.4.2 || ^6.0.0 || 7.0.0 - 7.2.0" from eslint-config-next@14.2.3
npm error     node_modules/eslint-config-next
npm error       dev eslint-config-next@"14.2.3" from the root project
npm error
npm error Could not resolve dependency:
npm error peer eslint@"^7.23.0 || ^8.0.0" from eslint-config-next@14.2.3
npm error node_modules/eslint-config-next
npm error   dev eslint-config-next@"14.2.3" from the root project
npm error
npm error Conflicting peer dependency: eslint@8.57.1
npm error node_modules/eslint
npm error   peer eslint@"^7.23.0 || ^8.0.0" from eslint-config-next@14.2.3
npm error   node_modules/eslint-config-next
npm error     dev eslint-config-next@"14.2.3" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

### Expected Behavior

Running npm install should work as well as installing additional repos.

### Steps to Reproduce

Using npm:
- Create new repo via `npx create-nx-workspace@latest --preset next` and leave select all default values.
- Run `npm install` from newly create directory.

### Nx Report
```
Node           : 20.17.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.8.2

nx (global)        : 20.0.0
nx                 : 20.0.0
@nx/js             : 20.0.0
@nx/jest           : 20.0.0
@nx/eslint         : 20.0.0
@nx/workspace      : 20.0.0
@nx/devkit         : 20.0.0
@nx/eslint-plugin  : 20.0.0
@nx/next           : 20.0.0
@nx/playwright     : 20.0.0
@nx/react          : 20.0.0
@nx/vite           : 20.0.0
@nx/web            : 20.0.0
@nx/webpack        : 20.0.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/next/plugin
@nx/playwright/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

### Package Manager Version

npm 10.8.2

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ziacik-resco** [comment]
This is getting ridiculous. Were any tests run against release 20? Or any release, actually?

**Comment by laszlo-ratesic** [comment]
I was able to install packages with `--legacy-peer-deps` but ran into issues when trying to use shadcn/ui CLI so I needed something that would work without the flag. 

I ended up changing my package.json's devDependencies and overrides to this
```
"devDependencies": {
    // other dependencies...
    "@typescript-eslint/eslint-plugin": "^7.2.0",
    "@typescript-eslint/parser": "^7.2.0",
    "eslint": "8.56.0",
    "eslint-config-next": "14.2.3",
  },
  "overrides": {
    "eslint": "8.56.0",
    "@typescript-eslint/eslint-plugin": {
      "eslint": "8.56.0"
    },
    "@typescript-eslint/parser": {
      "eslint": "8.56.0"
    }
  }
```

Then I ran `npm clean cache --force` and then `npm install` and it worked like a charm for me.

**Comment by aggiustino** [comment]
Yes, running `npm I --legacy-peer-deps` or adding dependencies to `overrides` fixes it, but it's far from ideal.

**Comment by nickmanks** [comment]
revert to using `npx create-nx-workspace@19.6` if you want to avoid the dramas for now

**Comment by jaysoo** [comment]
Unfortunately, this is partly out of our hands right now as `eslint-config-next` v14 has not updated their peer dependency to support ESLint v9. We chose to migrate over to ESLint v9 from v8 since the latter reached EOL on October 5th, 2024.

For now, you will need `npm i --force` or `npm i --legacy-peer-deps` until Next.js updates their package, which looks like it won't happen until Next.js v15. I encourage you to open an issue on https://github.com/vercel/next.js/issues for it to be available in Next.js v14.

The only thing Nx users could do is to use the latest Next.js RC, e.g. `15.0.0-rc.1`. We don't want to install RC versions by default.

**Comment by jaysoo** [comment]
The other option is to remove `eslint-config-next`, but you'll also need to remove Next.js specific rules from your `eslint.config.js` files.


```
module.exports = [
  // Remove these if you remove eslint-plugin-next
  // ...fixupConfigRules(compat.extends('next')),
  // ...fixupConfigRules(compat.extends('next/core-web-vitals')),
  //
  ...baseConfig,
  ...nx.configs['flat/react-typescript'],
  { ignores: ['.next/**/*'] },
];
```

**Comment by jaysoo** [comment]
Closing this as there isn't anything we can do on our end except to wait until the ecosystem catches up to the fact that ESLint v8 is no longer supported, and that only ESLint flat configs are supported.

See more on the announcement of ESLint v8 EOL: https://eslint.org/blog/2024/09/eslint-v8-eol-version-support/

**Comment by dreglad** [comment]
@jaysoo ESLint 9 is now [supported in Next.js 15](https://nextjs.org/blog/next-15#eslint-9-support), which is the current stable release. I believe the Nx Next.js profile should be updated to reflect this version bump.

**Comment by nemonemi** [comment]
I am not using Next.js and I am experiencing the same issue.
