### ISSUE TITLE
Nx/webpack generating separate map file when setting is inline-source-map

### ISSUE THREAD

**Issue by rexkenley** [nrwl/nx#28436]
### Current Behavior

We upgraded our webpack config to use the Nx webpack. However, we noticed that it generates a separate map file instead of generating a single file.

The details are found here.
https://github.com/nrwl/nx/discussions/28416

### Expected Behavior

Generate a single file

### Steps to Reproduce

The details are found here.
https://github.com/nrwl/nx/discussions/28416

### Nx Report

Node           : 20.11.1
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.2.4

nx                 : 19.8.0
@nx/js             : 19.8.0
@nx/jest           : 19.8.0
@nx/linter         : 19.8.0
@nx/eslint         : 19.8.0
@nx/workspace      : 19.8.0
@nx/cypress        : 19.8.0
@nx/devkit         : 19.8.0
@nx/eslint-plugin  : 19.8.0
@nx/playwright     : 19.8.0
@nx/react          : 19.8.0
@nx/rollup         : 19.8.0
@nx/storybook      : 19.8.0
@nrwl/tao          : 19.8.0
@nx/vite           : 19.8.0
@nx/web            : 19.8.0
@nx/webpack        : 19.8.0
typescript         : 5.6.2
---------------------------------------
Registered Plugins:
@hcltech/powerplatform-solution/plugin
@hcltech/powerplatform-pcf/plugin
@hcltech/powerplatform-web-resource/plugin/nuget
@hcltech/powerplatform-web-resource/plugin/webpack
@nx/webpack/plugin
@nx/eslint/plugin
@nx/playwright/plugin
@nx/jest/plugin
@nx/rollup/plugin
@nx/storybook/plugin
@nx/vite/plugin
---------------------------------------
Community plugins:
@hcltech/powerplatform-catalog      : 3.1.0
@hcltech/powerplatform-dataverse    : 2.8.0
@hcltech/powerplatform-init         : 3.0.0
@hcltech/powerplatform-pac          : 4.1.0
@hcltech/powerplatform-pcf          : 5.0.0
@hcltech/powerplatform-react        : 1.0.1
@hcltech/powerplatform-solution     : 4.0.1
@hcltech/powerplatform-web-resource : 5.0.0

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by rexkenley** [comment]
Here is the problematic code
https://github.com/nrwl/nx/blob/42da5421afdd21700486fbb1e26d22e8f36bc199/packages/webpack/src/plugins/nx-webpack-plugin/lib/apply-base-config.ts#L88C1-L93C15

**Comment by ndcunningham** [comment]
I answered in the discussion which was linked #https://github.com/nrwl/nx/discussions/28416. We can also wait for #28508 if you would like to set a different `sourceMap` that is not `hidden`.
However, to answer your issue you can find it inside of the discussion!

If that does not work feel free to re-open with some details on the failure.
