### ISSUE TITLE
Javascript --js command giving error on Express Generate

### ISSUE THREAD

**Issue by iwarner** [nrwl/nx#2843]
Reading this guide
https://nx.dev/react/guides/js-and-ts is states

`simply pass --js to all generate commands`

Running

`nx generate @nrwl/express:application communications --js`

brings up error

`Could not match option 'js' to the @nrwl/express:application schema.`

I am on MacOSX Mojave
Node v12.14.1

Latest NX - just installed

Thanks

**Comment by davidrhoderick** [comment]
I'm just trying nx and I'm getting this same error.

**Comment by ramiel** [comment]
Any news on this?

**Comment by shreyansh-zazz** [comment]
Any news? I am trying to create a node application with `js`, not `ts`. Why it is so hard, I am also getting the same error.

**Comment by ilkka** [comment]
If you look at the [options schema for the express application generator](https://github.com/nrwl/nx/blob/7cbf4ffd88a9bc543407dd18c1ebbad194375e7e/packages/express/src/schematics/application/schema.d.ts), you will notice that it does not, in fact, support the `--js` option. Caught me off guard as well. The docs are definitely overselling it :)

**Comment by shreyansh-zazz** [comment]
@ilkka I spend my whole day digging into so many things like debugging, js/ts, etc., none of them worked according to the documentation.

**Comment by AlonMiz** [comment]
+1

**Comment by bekos** [comment]
Closing as this has already been fixed via #3683.
