### ISSUE TITLE
NX Lint broken on scaffolded NX 20 repo  (Integrated monorepo with Angular app)

### ISSUE THREAD

**Issue by GeorgeKnap** [nrwl/nx#28440]
### Current Behavior

1. scaffold NX20 integrated workspace with Angular app
2.  run nx lint for your app

throws error 
```
> nx run demo:lint

Linting "demo"...
 NX   Cannot read properties of undefined (reading 'at')
Occurred while linting C:\development\nx20\apps\demo\src\app\app.component.html:1
Rule: "@typescript-eslint/ban-ts-comment"
Pass --verbose to see the stacktrace.
```

### Expected Behavior

expecting lint works

### Steps to Reproduce

1.

### Nx Report

 NX   Report complete - copy this into the issue template

Node           : 20.11.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.2.4

nx (global)        : 20.0.0
nx                 : 20.0.0
@nx/js             : 20.0.0
@nx/jest           : 20.0.0
@nx/eslint         : 20.0.0
@nx/workspace      : 20.0.0
@nx/angular        : 20.0.0
@nx/cypress        : 20.0.0
@nx/devkit         : 20.0.0
@nx/eslint-plugin  : 20.0.0
@nx/web            : 20.0.0
@nx/webpack        : 20.0.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin

### Package Manager Version

npm 10.2.4

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

could be related to https://github.com/typescript-eslint/typescript-eslint/issues/8075

**Comment by leosvelperez** [comment]
This was fixed by https://github.com/nrwl/nx/pull/28381 and the fix will be released soon.
