### ISSUE TITLE
How to pass multipe args in workspace:run-commands

### ISSUE THREAD

**Issue by Uter1007** [nrwl/nx#2846]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ X ] I am running the latest version
- [ ] I checked the documentation (nx.dev) and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

When running nx affected --target=deploy --args="--DOCKER_USER=testuser --DOCKER_PASS=testpw" two paramters get parsed and added to args object.

## Current Behavior

Only the first parameter get parsed -> the string got terminated by a space.

**Comment by Ponjimon** [comment]
I just upgraded to Nx 11 and this definitely used to work in Nx 10.2.0:

```
$ yarn run nx run graphql:dummy --args="--foo=bar --baz=buz"
yarn run v1.22.5                                                                                                                                                                                                           
$ nx run graphql:dummy '--args=--foo=bar --baz=buz'                                                                                                                                                                        

> nx run graphql:dummy --args=--foo=bar --baz=buz 
Dummy graphql --foo=bar --baz=buz
Done in 0.60s.
```

As opposed to Nx 11.0.4:

```
$ yarn run nx run graphql:dummy --args="--foo=bar --baz=buz"
yarn run v1.22.5                                                                                                                                                                                                           
$ nx run graphql:dummy '--args=--foo=bar --baz=buz'                                                                                                                                                                        

> nx run graphql:dummy --args="--foo=bar --baz=buz" 
Invalid args: "--foo=bar --baz=buz"
error Command failed with exit code 1.
```

I cannot upgrade to Nx 11 and have to revert to Nx 10 beacuse of this because our pipeline is relying on multiple arguments working. There is also no reason why only one argument should be working, this clearly is a bug.

**Comment by bekos** [comment]
@Ponjimon can you try to execute ` yarn run nx run graphql:dummy --foo=bar --baz=buz`? Will this work?

**Comment by Ponjimon** [comment]
@bekos Yes, this does indeed work, I will change our pipeline using that format then :) 

I'd suggest adding / changing the [documentation](https://nx.dev/latest/angular/plugins/workspace/executors/run-commands) though: 
![image](https://user-images.githubusercontent.com/770632/102218495-52ef2c00-3ede-11eb-8e56-16a7a3362aa0.png)

**Comment by bekos** [comment]
@Ponjimon np :) Yes, I also think that we should just start deprecating the `--args` usage. What you reported is actually a bug though, if we want to be backwards compatible! I will look into that :)

**Comment by danimbrogno** [comment]
Just noticed that args with hyphens in them which worked in nx 8 no longer seem to work in nx 11.

e.g.

Only slot is successfully passed here
`yarn expo build:android -t app-bundle --release-channel {args.slot} --keystore-path {args.android-keystore} --keystore-alias {args.android-keystore-alias} --skip-workflow-check --no-wait --no-publish`

All arguments are passed here
`yarn expo build:android -t app-bundle --release-channel {args.slot} --keystore-path {args.androidKeystore} --keystore-alias {args.androidKeystoreAlias} --skip-workflow-check --no-wait --no-publish`

**Comment by nwitte-rocketloans** [comment]
This is a breaking change that broke my CI pipeline. Unsure of what the purpose of this change even is. Why would it convert kebab-case to camelCase with no option to override it?

**Comment by bekos** [comment]
@nwitte-rocketloans how exactly you are using this command? this change shouldn't be a breaking change.

**Comment by nwitte-rocketloans** [comment]
Keep in mind, we are using these types of arguments throughout our commands in workspace.json, so this could take a while to comb through. Here is an example:

`        "build-docker": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "command": "docker build .",
            "file": "path/to/Dockerfile",
            "tag": "image-tag:latest",
            "cache-from": "image-tag:latest"
          }
        },`
        
        Since cache-from contains a hyphen, it turns from --cache-from to --cacheFrom. WHY?

**Comment by bekos** [comment]
@nwitte-rocketloans and how do you run it? can you show the command you invoke it?

**Comment by nwitte-rocketloans** [comment]
> @nwitte-rocketloans and how do you run it? can you show the command you invoke it?

`nx build-docker app-name`

or 

`nx run app-name:build-docker`
