### ISSUE TITLE
New react app with rspack ignore styles.css

### ISSUE THREAD

**Issue by Wykks** [nrwl/nx#28465]
### Current Behavior

When I create a new react app with rspack, it generate a styles.css file with a comment saying "You can add global styles to this file". But this file is completely ignored. 
Not too surprising given that the rspack executor (https://nx.dev/nx-api/rspack/executors/rspack) doesn't support the styles option.

### Expected Behavior

Either the file should not be generated or the rspack executor should support global style file.

### Steps to Reproduce

1. In any 20.0.1 workspace: `npx nx g @nx/react:app my-app --bundler=rspack --style=css`
2. add this to the styles.css file
```
body {
  background-color: red !important;
}
```
3. `npx nx serve my-app`
4. Notice that the styles is ignored

### Nx Report

Node           : 20.18.0
OS             : linux-x64
Native Target  : x86_64-linux
npm            : 10.8.2

nx (global)        : 20.0.1
nx                 : 20.0.1
@nx/js             : 20.0.1
@nx/eslint         : 20.0.1
@nx/workspace      : 20.0.1
@nx/devkit         : 20.0.1
@nx/eslint-plugin  : 20.0.1
@nx/react          : 20.0.1
@nx/rspack         : 20.0.1
@nx/vite           : 20.0.1
@nx/web            : 20.0.1
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Hey, thanks for reporting this issue. 

A small workaround until this is addressed is to add your global style file inside your main entrypoint for example (`main.tsx`)
