### ISSUE TITLE
HMR not working for rspack/webpack MFE with exposes in config

### ISSUE THREAD

**Issue by jmvtrinidad** [nrwl/nx#28467]
### Current Behavior

HMR is not working on host but working on remote

### Expected Behavior

HMR should work with host as well, this is the fix provided
https://github.com/module-federation/module-federation-examples/issues/358#issuecomment-844455904

### Steps to Reproduce

1. create a new host app then add a exposes component using module.federation-config.ts

### Nx Report

 NX   Report complete - copy this into the issue template

Node           : 22.4.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.12.1

nx (global)        : 19.8.4
nx                 : 19.8.4
@nx/js             : 19.8.4
@nx/jest           : 19.8.4
@nx/linter         : 19.8.4
@nx/eslint         : 19.8.4
@nx/workspace      : 19.8.4
@nx/devkit         : 19.8.4
@nx/eslint-plugin  : 19.8.4
@nx/plugin         : 19.8.4
@nx/react          : 19.8.4
@nx/storybook      : 19.8.4
@nrwl/tao          : 19.8.4
@nx/vite           : 19.8.4
@nx/web            : 19.8.4
@nx/webpack        : 19.8.4
nx-cloud           : 19.1.0
typescript         : 5.5.2
---------------------------------------
Community plugins:
@koliveira15/nx-sonarqube : 3.5.1
@nx-tools/nx-container    : 5.0.3
@nx/rspack                : 19.8.0
---------------------------------------
Local workspace plugins:
         fe-tools

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Hi @jmvtrinidad !

Can you provide a better reproduction? Preferably a repo containing it with instructions on how to reproduce the error from there.
I'm having trouble understanding the setup that has caused this issue.

A host (e.g. `hostA`) generally doesn't expose a component, however, if the project is both a host and a remote, then it must be consumed by another host (e.g. `shell`).
Therefore, to get HMR you would need to run `nx serve shell --devRemotes=hostA`
