### ISSUE TITLE
Circle CI does not build nest-js application

### ISSUE THREAD

**Issue by Uter1007** [nrwl/nx#2847]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [ ] I checked the documentation (nx.dev) and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior
npm run build -- --configuration production will run on CircleCI without any troubles.
Build process 

## Current Behavior

node --max-old-space-size=2048 ./node_modules/.bin/ng "build" "crm-sync" "--configuration=production"

Starting type checking service...
Using 34 workers with 2048MB memory limit
events.js:287
throw er; // Unhandled 'error' event
^

Error: write EPIPE
at process.target._send (internal/child_process.js:806:20)
at process.target.send (internal/child_process.js:677:19)
at run (/home/circleci/repo/node_modules/@nrwl/node/node_modules/fork-ts-checker-webpack-plugin/lib/service.js:26:21)
at process.<anonymous> (/home/circleci/repo/node_modules/@nrwl/node/node_modules/fork-ts-checker-webpack-plugin/lib/service.js:38:5)
at process.emit (events.js:310:20)
at emit (internal/child_process.js:876:12)
at processTicksAndRejections (internal/process/task_queues.js:85:21)
Emitted 'error' event on process instance at:
at internal/child_process.js:810:39
at processTicksAndRejections (internal/process/task_queues.js:79:11) {
errno: 'EPIPE',
code: 'EPIPE',
syscall: 'write'
}

### Steps to Reproduce

1. Create multiple Nestjs Projects
2. use circleci example config but instead of yarn use npm
3. wait for troubles in circleci

**Comment by Uter1007** [comment]
Just saw that there was another ticket already: https://github.com/nrwl/nx/issues/1899

**Comment by jaysoo** [comment]
@Uter1007 

> Using 34 workers with 2048MB memory limit

This looks pretty problematic. This is defaulted to `# CPUs - 2` so I'm guessing you have 36 cores?

Can you try passing `--maxWorkers=8` or something more sane? 

We'll need to look into better defaults for # workers.

**Comment by Uter1007** [comment]
will try out. in the last hours I did not find any problems since using ngcc as a pre-step. Will trace and analyze more in the next couple of days.

**Comment by lukasholzer** [comment]
@Uter1007 as @jaysoo pointed out you have to specify the `maxWorkers` for the build target in the `angular.json` or `nx.json` file. Otherwise, you will create a worker thread overhead that crashes the process. This has to be done everywhere where you use the `@nrwl/node:build`.

Maybe @vsavkin would it make sense to provide a more sensible default number for the `maxWorkers`, that is not bound to the CPUs? Because it will generate a thread overhead If you have more CPUs.

**Comment by jaysoo** [comment]
Also tagging @Cammisuli. I think we've discussed `maxWorkers` with @vsavkin before? Better to tune it down a bit.

**Comment by Uter1007** [comment]
maxworkers setting in the build step looks good so far on my CircleCI setting.

**Comment by webberwang** [comment]
I kept getting this error on NX `"Nx could not find process's output"`, took hours to debug with this cryptic error message. Then the message `Using 34 workers with 2048MB memory limit` led me here.

Adding this here so the error message could link to this thread here.

**Comment by Burgov** [comment]
Thanks guys! Reducing the maxWorkers seems to do the trick! For me, the issue was even more obscure - with nx, the build command would simply yield no output, but exit with code 0. without nx (so ng build), the command would stall for 10 minutes and then be killed by circleci.
