### ISSUE TITLE
Cannot create Angular remote project with - (Hyphen) in it

### ISSUE THREAD

**Issue by its-ratikant** [nrwl/nx#28481]
### Current Behavior

Cannot create remote with - (Hyphen) with it; e.g. my-mfe

![Image](https://github.com/user-attachments/assets/6fe9e718-deba-4809-982b-77cab6fe2952)

### Expected Behavior

This is very basic project naming convention, we should never restrict user to create a remote project with a hyphen in it - though it is allowing to create a host project with a hyphen in it..

### Steps to Reproduce

1. create workspace
2. create angular host project
3. create angular remote project with a hyphen in it, e.g. user-management

### Nx Report

Node           : 20.18.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.8.2

nx (global)        : 20.0.0
nx                 : 20.0.1
@nx/js             : 20.0.1
@nx/jest           : 20.0.1
@nx/eslint         : 20.0.1
@nx/workspace      : 20.0.1
@nx/angular        : 20.0.1
@nx/devkit         : 20.0.1
@nx/eslint-plugin  : 20.0.1
@nx/web            : 20.0.1
@nx/webpack        : 20.0.1
typescript         : 5.5.4

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Discussion here: https://github.com/nrwl/nx/discussions/28494

Unfortunately this is a restriction from Module Federation and therefore it'll continue to operate in the manner as above
