### ISSUE TITLE
React workspace.json extractCss property not working

### ISSUE THREAD

**Issue by FatihHyusein** [nrwl/nx#2848]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I am running the latest version
- [ x] I checked the documentation (nx.dev) and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

If extractCss: true is set in workspace.json the built project should have styles.css instead of styles.js

Please describe the behavior you are expecting

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create nx react project
2. in workspace.json set extractCss to true
3. build the project
4. The output style is js file instead of css (nxdeps.json also shows extractCss :true)

**Comment by bekos** [comment]
Seems like this is working on the latest version.
![image](https://user-images.githubusercontent.com/551595/99818376-d07d8180-2b56-11eb-9358-d293426d423c.png)

Feel free to reopen if this is still an issue!

**Comment by kerituni12** [comment]
If you include style.css in styles project.json it work , but if direct import in js code without include project.json it's js file

![](https://gcdnb.pbrd.co/images/OLB4ltzzXAnW.png?o=1)
