### ISSUE TITLE
HMR is extremely slow when using module-federation/enhanced with rspack

### ISSUE THREAD

**Issue by ReinGomezWP** [nrwl/nx#28485]
### Current Behavior

Updated to the latest version of workspace and converted our rspack application into a host application.
However the HMR started getting really slow. The host application has no remotes whatsoever.
It used to take less than a 1sec for HMR to reflect the changes, but now it takes close to 10sec

### Expected Behavior

HMR should be the same as it was when it was a standalone rspack application since the host application has no remotes.

### Steps to Reproduce

1. Create an rspack application
2. Add the module-federation configurations
3. Run in dev-server and modify application to trigger HMR

### Nx Report

Node           : 19.5.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.5.0

nx                 : 20.0.1
@nx/js             : 20.0.1
@nx/jest           : 20.0.1
@nx/eslint         : 19.2.3
@nx/workspace      : 20.0.1
@nx/cypress        : 19.2.3
@nx/devkit         : 20.0.1
@nx/eslint-plugin  : 20.0.1
@nx/playwright     : 20.0.1
@nx/react          : 20.0.1
@nx/rspack         : 20.0.1
@nx/storybook      : 19.2.3
@nx/vite           : 20.0.1
@nx/web            : 20.0.1
@nx/webpack        : 20.0.1
nx-cloud           : 19.1.0
typescript         : 5.5.4
---------------------------------------
The following packages should match the installed version of nx
  - @nx/eslint@19.2.3
  - @nx/cypress@19.2.3
  - @nrwl/cypress@19.2.3
  - @nx/storybook@19.2.3
  - @nrwl/storybook@19.2.3

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
I can't reproduce this, can you provide a repo with a minimal reproduction of the slowness so that I can investigate further?
