### ISSUE TITLE
nx reset always required

### ISSUE THREAD

**Issue by agnusdei1207** [nrwl/nx#28480]
### Current Behavior

![Image](https://github.com/user-attachments/assets/265c8e45-f959-4890-b1b8-12c64a36f498)
Here's the translation of your message into English:

Every time I restart the NX server, it keeps asking me to reset. This is very inconvenient. My development time has doubled. There are many significant issues with each update, and I am seriously considering not using NX anymore.

If you need any further assistance, feel free to ask!

### Expected Behavior

![Image](https://github.com/user-attachments/assets/265c8e45-f959-4890-b1b8-12c64a36f498)
Here's the translation of your message into English:

Every time I restart the NX server, it keeps asking me to reset. This is very inconvenient. My development time has doubled. There are many significant issues with each update, and I am seriously considering not using NX anymore.

If you need any further assistance, feel free to ask!

### Steps to Reproduce

1.

### Nx Report

![Image](https://github.com/user-attachments/assets/265c8e45-f959-4890-b1b8-12c64a36f498)
Here's the translation of your message into English:

Every time I restart the NX server, it keeps asking me to reset. This is very inconvenient. My development time has doubled. There are many significant issues with each update, and I am seriously considering not using NX anymore.

If you need any further assistance, feel free to ask!

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by andrey59412678** [comment]
same here, it's been like this for a few days. every time I kill a serving app I need to `nx reset` before I can `serve` it again. also happens with pretty much every other nx command I do, not only serving. generators too.

```
Node   : 20.12.1
OS     : linux-x64
pnpm   : 8.15.7

nx                 : 19.5.3
@nx/js             : 19.5.3
@nx/jest           : 19.5.3
@nx/linter         : 19.5.3
@nx/eslint         : 19.5.3
@nrwl/linter       : 16.9.1
@nx/workspace      : 19.5.3
@nx/cypress        : 19.5.3
@nx/devkit         : 19.5.3
@nx/esbuild        : 19.5.3
@nx/eslint-plugin  : 19.5.3
@nx/next           : 19.5.3
@nx/node           : 19.5.3
@nx/plugin         : 19.5.3
@nx/react          : 19.5.3
@nx/storybook      : 19.5.3
@nrwl/tao          : 19.5.3
@nx/vite           : 19.5.3
@nx/web            : 19.5.3
@nx/webpack        : 19.5.3
nx-cloud           : 19.0.0
typescript         : 5.5.4
```

**Comment by GaryB432** [comment]
me too.  also leaving terminals open

```
Node           : 20.17.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.8.2

nx                 : 20.0.1
@nx/js             : 20.0.1
@nx/eslint         : 20.0.1
@nx/workspace      : 20.0.1
@nx/devkit         : 20.0.1
@nx/eslint-plugin  : 20.0.1
@nx/vite           : 20.0.1
@nx/web            : 20.0.1
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
```

**Comment by julianobrasil** [comment]
It's been one or two versions since Nx began to require `nx reset` quite often.

I even had to build a script to be used in our GH workflows to automatically reset it when the error message says so. The number of failures that we have team-wide is annoying.

**Comment by jaysoo** [comment]
Does anyone have a repro that we can use to debug the issue?
