### ISSUE TITLE
Question: framework agnostic library

### ISSUE THREAD

**Issue by edbzn** [nrwl/nx#2850]
Hi guys, 

When creating a publishable library with Nx that **not** aims to target Angular we must remove all the boilerplate needed for running this environment:

- `angularCompilerOptions` in ts-config files,
- Test setup file that imports `'jest-preset-angular'`,
- `NgModule` created by default,
- Spec file using the `TestBed` module.

I imagine it's due to the history of Nx that was mainly targeting Angular at its early stages. It could be useful to have a new `generate lib` option to create a framework agnostic library, by this I mean a TypeScript only library. What do you think? 

However thanks for your work, I really appreciate working with Nx.

**Comment by brandonroberts** [comment]
You have a couple of options here:

Use the `@nrwl/workspace:library` schematic to generate a barebones TypeScript library
https://nx.dev/angular/plugins_workspace_schematics/library

Use the `nx-plugin` schematic to do the same, but integrations schematics, and builders, that are independent of the Angular framework also.
https://nx.dev/angular/plugins_nx-plugin/overview
