### ISSUE TITLE
Passing --project option to @nx/playwright:playwright invalidates all other NX args.

### ISSUE THREAD

**Issue by bridzius** [nrwl/nx#28543]
### Current Behavior

Passing `-- --project` as suggested in https://github.com/nrwl/nx/issues/21151#issuecomment-2117591478 will choose the correct Playwright 'project', but will also forcefully ignore any other NX arguments that preceeded it.

Command such as:
`npx nx run appl:e2e --test-files=apps/appl/playwright/e2e --skip-install -- --project=chromium`

Translates to:
`nx run appl:e2e --project=chromium`

### Expected Behavior

Command such as:
`npx nx run appl:e2e --test-files=apps/appl/playwright/e2e --skip-install -- --project=chromium`

Should translate to to:
`nx run appl:e2e --test-files=apps/appl/playwright/e2e --skip-install --project=chromium`

### GitHub Repo

https://github.com/bridzius/pw-repro

### Steps to Reproduce

1. `npm ci`
2. `npx nx run frontend-e2e:e2e --test-files=bing.spec.ts --skip-install -- --project=chromium`

Will run 2 tests (google/bing) on 'chromium'.

### Nx Report

Node           : 20.16.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.8.1

nx                 : 20.0.3
@nx/js             : 20.0.3
@nx/eslint         : 20.0.3
@nx/workspace      : 20.0.3
@nx/devkit         : 20.0.3
@nx/eslint-plugin  : 20.0.3
@nx/playwright     : 20.0.3
@nx/vite           : 20.0.3
@nx/web            : 20.0.3
@nx/webpack        : 20.0.3
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/vite/plugin
@nx/eslint/plugin

### Package Manager Version

npm@10.8.1

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
i think there are a couple of things you can do that you don't need additional options in playwright schema:
1. you can run the command like `npx nx run frontend-e2e:e2e -- --project=chromium --test-files=bing.spec.ts --skip-install` with all the options after `--`.
2. you can also use inferred targets(https://nx.dev/concepts/inferred-tasks) for playwright. you can delete "targets" in your project.json. then you run `npx nx run frontend-e2e:e2e`, you will just use `playwright` command directly under the hood. you can just run `npx nx run frontend-e2e:e2e -- bing.spec.ts --project=chromium`.

**Comment by bridzius** [comment]
Thanks for the answer, passing directly into the executor does indeed solve this specific usecase.
Though both options still have drawbacks:
1. Drops all control of the `nx` wrapper still, so things like `--skip-nx-cache`(not used here, but just an example) will no longer work, since all the commands are passed directly into the executor.
2. Changes the test run command structure entirely, since neither `--test-files`, nor `--skip-install` are standard `playwright` options.

It seems a bigger refactoring is on our hands.
