### ISSUE TITLE
Generate angular remote app failed with name that has hyphen charactor

### ISSUE THREAD

**Issue by blogic-toplx** [nrwl/nx#28558]
### Current Behavior

When i try to generate new angular remote app with name 'sale-reports' that includes '-', the terminal return an issue:
```
NX   Invalid remote name: sale-report. Remote project names must:
- Start with a letter, dollar sign ($) or underscore (_)
- Followed by any valid character (letters, digits, underscores, or dollar signs)
The regular expression used is ^[a-zA-Z_$][a-zA-Z_$0-9]*$.
```

As i checked in the documentation, the regex pattern for name of remote app is: ^[a-zA-Z][^:]*$.
![Image](https://github.com/user-attachments/assets/0ac3e8ae-68e6-484d-9ebe-0b7c307cd1cb)
And this is valid for my name - 'sale-reports'.

Is this new updated rule for remote name or any mismatch here?

Note:
Node version: v20.18.0
Nx Version: v20.0.3

### Expected Behavior

We can generate new angular remote app with name that has hyphen.

### Steps to Reproduce

1. Create new workspace: npx create-nx-workspace@latest blogic-view --preset=apps
2. Generate new host app: nx g @nx/angular:host src/apps/dashboard --dynamic
3. Generate new remote app: nx g @nx/angular:remote src/apps/sale-reports --host=dashboard

### Nx Report

 NX   Report complete - copy this into the issue template

Node           : 20.18.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.8.2

nx (global)        : 20.0.3
nx                 : 20.0.3
@nx/js             : 20.0.3
@nx/jest           : 20.0.3
@nx/eslint         : 20.0.3
@nx/workspace      : 20.0.3
@nx/angular        : 20.0.3
@nx/devkit         : 20.0.3
@nx/eslint-plugin  : 20.0.3
@nx/playwright     : 20.0.3
@nx/vite           : 20.0.3
@nx/web            : 20.0.3
@nx/webpack        : 20.0.3
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/eslint/plugin

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by xichtop** [comment]
After reading the source, i saw this commit made the rule for the remote name: https://github.com/nrwl/nx/commit/1badac82c977b6950a6be9bfe6f727300caa2bd3#diff-c54f4e1195e9cb19426f4f0185acfe9ee9fdc17372a366e0658549cbc4a2072fR458.
I think the doc haven't been updated after the change.

**Comment by barrymichaeldoyle** [comment]
> After reading the source, i saw this commit made the rule for the remote name: [1badac8#diff-c54f4e1195e9cb19426f4f0185acfe9ee9fdc17372a366e0658549cbc4a2072fR458](https://github.com/nrwl/nx/commit/1badac82c977b6950a6be9bfe6f727300caa2bd3#diff-c54f4e1195e9cb19426f4f0185acfe9ee9fdc17372a366e0658549cbc4a2072fR458). I think the doc haven't been updated after the change.

Ah yes, that's the PR that's blocking us from upgrading to v20 🙁

**Comment by Coly010** [comment]
@blogic-toplx The error is correct. There is a mismatch in the generator's schema, I'll push a PR to fix that now. 
However, this is expected and will be enforced going forward. You can learn more about the reasoning behind this here: https://github.com/nrwl/nx/discussions/28494

Note, existing remotes using `-` should continue to work fine.
