### ISSUE TITLE
Defaulting SVGR to enabled with the withNx plugin creates dev & prod svg mismatch with Next 19 and turbopack

### ISSUE THREAD

**Issue by lourd** [nrwl/nx#28551]
### Current Behavior

Next.js 15 was published as stable today, which includes turbopack also being considered stable for the dev server.

When using turbopack with the dev server, via the `--turbo` option, any SVGs that were imported now have a different runtime representation than before. Now, they're imported as `StaticImageData` objects, e.g.:

```ts
interface StaticImageData {
    src: string;
    height: number;
    width: number;
    blurDataURL?: string;
    blurWidth?: number;
    blurHeight?: number;
}
```

but during the prod build a default import of an svg file is just a string, the static path of the file in the build output.

It's possible to enable SVGR for turbopack (see https://github.com/vercel/turborepo/issues/4832#issuecomment-1751407444), but that takes additional configuration, and it also has different semantics (not requiring the query parameter on the import string).

It's particularly confusing because if you leave out the `nx` block entirely, SVGR is still enabled. You have to explicitly set `nx.svgr` to `false` to not go through that processing.

### Expected Behavior

I would not expect the `withNx` plugin to handle anything other than monorepo integration, setting up paths as needed, etc. 

### Steps to Reproduce

1. Generate an Nx repo and an Next.js app
2. Import an svg file in the Nx app and log the import.
3. Run the dev server for the Next.js app. See the log output is an object with various properties, including `src`.
4. Build the Next.js app. See that the log output for the svg file is now just a string.

### Nx Report

Node           : 20.12.1
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.7.0
nx                 : 20.0.3
@nx/js             : 20.0.3
@nx/jest           : 20.0.3
@nx/eslint         : 20.0.3
@nx/workspace      : 20.0.3
@nx/devkit         : 20.0.3
@nx/esbuild        : 20.0.3
@nx/eslint-plugin  : 20.0.3
@nx/next           : 20.0.3
@nx/node           : 20.0.3
@nx/playwright     : 20.0.3
@nx/react          : 20.0.3
@nx/vite           : 20.0.3
@nx/web            : 20.0.3
@nx/webpack        : 20.0.3
typescript         : 5.5.4

Registered Plugins:
@nx/next/plugin
@nx/playwright/plugin
@nx/eslint/plugin
@nx/jest/plugin

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Hey, thanks for filling out this issue.

We default the SVGR option for Next.js apps to `false` so when you create a Next.js app this is shouldn't happen.
Looking back, we could've done a better job at this option as removing it also enables it when you use `withNx` plugin. 

Currently, this is option deprecated and will be removed in Nx 21. The workaround is to leave the svgr option `false` to include the loader from within Nx's `withNx` plugin. https://github.com/nrwl/nx/pull/28705
