### ISSUE TITLE
Nx uses env variable specified in .env.local instead of using given value when building in pipeline

### ISSUE THREAD

**Issue by jvskriubakken** [nrwl/nx#28569]
### Current Behavior

Hi

I have several react apps and corresponding dotnet webapps. They are setup in the same way. I'm passing environment variable NX_PUBLIC_BUILD_NUMBER into every app in the Azure pipeline build like this (excerpt from yaml file):
```      
      - script: yarn nx affected --base=$(BASE_SHA) --target=build --configuration=production --parallel=3
        displayName: "Build apps"
        env:
          NX_PUBLIC_BUILD_NUMBER: $(Build.BuildNumber)
```

Every react app project has file .env.local on root that contains:
```
NX_PUBLIC_BUILD_NUMBER=local-debug
```

When running the applications locally every app get the value "local-debug" from the following execution:
```
process.env["NX_PUBLIC_BUILD_NUMBER"]
```

When running the applications on the their servers, every app gets the actual build number as the value (instead of "local-debug"). However, one application still has the value "local-debug" when running on it' server. When I search for "NX_PUBLIC_BUILD_NUMBER" in the generated js-file I find "local-debug". 

How can this happen? Anyone experienced this? I have compared project.json and tsconfig.json and other files between the apps working as expected and the one that doesn't, without finding any differences (other than that they reside in different paths - as expected). Hoping for some guidance on what could be causing it. Thanks!

### Expected Behavior

That nx passes given environment variable to every affected react app equally.

### Steps to Reproduce

N/A.

### Nx Report

Node           : 18.20.2
OS             : darwin-arm64
Native Target  : aarch64-macos
yarn           : 1.22.19

nx (global)        : 19.8.6
nx                 : 19.8.6
@nx/js             : 19.8.6
@nx/jest           : 19.8.6
@nx/linter         : 19.8.6
@nx/eslint         : 19.8.6
@nx/workspace      : 19.8.6
@nx/cypress        : 19.8.6
@nx/devkit         : 19.8.6
@nx/eslint-plugin  : 19.8.6
@nx/plugin         : 19.8.6
@nx/react          : 19.8.6
@nx/storybook      : 19.8.6
@nrwl/tao          : 19.8.6
@nx/vite           : 19.8.6
@nx/web            : 19.8.6
@nx/webpack        : 19.8.6
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/cypress/plugin
@nx/jest/plugin
@nx-dotnet/core
@nx/storybook/plugin
---------------------------------------
Community plugins:
@nx-dotnet/core : 2.4.5
---------------------------------------
Local workspace plugins:
         @airmont/nx-plugins

### Package Manager Version

yarn 1.22.19

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by sacru2red** [comment]
Is this related to this issue? #28576

**Comment by xiongemi** [comment]
i am not sure whether it is related to https://github.com/nrwl/nx/issues/28576. what does your log say? does it say `Nx read the output from the cache instead of running the command`?
i submitted a pr https://github.com/nrwl/nx/pull/28741 to add .env, .local.env, .env.local files at workspace root to be cache. so any changes to these files will invalidate cache. when you changed these files and run affected command again, it should not read from cache.

**Comment by xiongemi** [comment]
there are a couple of things you can do right now:
- you can manually add `{projectRoot}/.env.local` or `{workspaceRoot}/.env.local` to your build target inputs, like:
```
  "targets": {
    "build": {
      "inputs": ["{projectRoot}/.env.local"]
    }
  }
```
this will ensure not to read from cache when `.env.local` file got changed

- maybe change the command something like?
```
NX_PUBLIC_BUILD_NUMBER=$(Build.BuildNumber) yarn nx affected --base=$(BASE_SHA) --target=build --configuration=production --parallel=3
```
