### ISSUE TITLE
NX cache ignores environment variable value changes

### ISSUE THREAD

**Issue by sacru2red** [nrwl/nx#28576]
### Current Behavior

duplicated #4662

but It's not resolved bug

restart nx with "--skip-nx-cache" after changing env file
(If you have multiple dependsOns like me, it may take several minutes.)

### Expected Behavior

NX detect chaging env or .env file

### Steps to Reproduce

1. nx run someapp
2. change root's .env file
3. nx run someapp

### Nx Report

Node           : 20.17.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.8.3

nx             : 20.0.2
@nx/js         : 20.0.2
@nx/jest       : 20.0.2
@nx/eslint     : 20.0.2
@nx/workspace  : 20.0.2
@nx/devkit     : 20.0.2
@nx/next       : 20.0.2
@nx/react      : 20.0.2
@nx/web        : 20.0.2
@nx/webpack    : 20.0.2
typescript     : 5.5.4
---------------------------------------
Registered Plugins:
@nx/jest/plugin
@nx/next/plugin

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by sacru2red** [comment]
@jaysoo  After changing .env, the changes are not propagated to Apps.

**Comment by xiongemi** [comment]
i also tried it locally, i could not replicate it as well. i just use https://github.com/nrwl/nx-examples as the react app to test with:

- I created `.env` at workspace root
- I also need to change the react app's webpack.config.js to pass down the process.env to react app:
```
const { composePlugins, withNx } = require('@nx/webpack');
const { withReact } = require('@nx/react');
const { EnvironmentPlugin } = require('webpack');

// Nx plugins for webpack.
module.exports = composePlugins(
  withNx(),
  withReact(),
  (config, { options, context }) => {
    // Update the webpack config as needed here.
    // e.g. config.plugins.push(new MyPlugin())
    // For more information on webpack config and Nx see:
    // https://nx.dev/packages/webpack/documents/webpack-config-setup
    config.plugins.push(new EnvironmentPlugin({ ...process.env }));
    return config;
  }
);
```
if I use vite as bundler, in vite.config.ts, I also need to add a line
```
  define: {
    'process.env': JSON.stringify(process.env),
  },
```

- I added a line to manually console.log the process.env inside the react app. everytime I change the .env file, I kill the server and serve up again, I am able to see the updated value from `.env`.

**Comment by xiongemi** [comment]
i think you can manually add `{projectRoot}/.env` or `{workspaceRoot}/.env` or the path to your .env file to your target inputs, something like:
```
  "targets": {
    "build": {
      "inputs": ["{projectRoot}/.env"]
    }
  }
``
this will ensure not to read from cache when `.env` file got changed

**Comment by xiongemi** [comment]
i am going to close my pr and this ticket as well.
it makes more sense to pick exactly the environment variables that the task depends on and specify those as inputs instead. The .env might have variables for many different tasks and it doesn't always make sense to bust the cache for every single task.
