### ISSUE TITLE
Cypress fails with "Uncaught ReferenceError: require is not defined" after installing @nrwl/cypress preprocessor hook

### ISSUE THREAD

**Issue by rslemos** [nrwl/nx#2857]
Consider an angular application (`ng new app`) with default cypress dev-installed (`yarn add cypress --dev`) and cypress-visual-regression (`yarn add cypress-visual-regression --dev`).

##### A word about *cypress-visual-regression*

This plugin is installed in two steps:

in `cypress/plugins/index.js`:
```
const getCompareSnapshotsPlugin = require('cypress-visual-regression/dist/plugin');
module.exports = (on, config) => {
   getCompareSnapshotsPlugin(on);
 }
```

in `cypress/support/commands.js` (in turn imported from `cypress/support/index.js`):
```
const compareSnapshotCommand = require('cypress-visual-regression/dist/command');
compareSnapshotCommand();
```
Simple, eh?

##### The simplest `@nrwl/cypress` preprocessor

After `yarn add @nrwl/cypress @nrwl/workspace --dev`, in `cypress/plugins/index.js`:
```
[...]
const { preprocessTypescript } = require('@nrwl/cypress/plugins/preprocessor');

module.exports = (on, config) => {
  getCompareSnapshotsPlugin(on);

  // Preprocess Typescript
  config.env.tsConfig = config.fileServerFolder + "/cypress/tsconfig.json";
  on('file:preprocessor', preprocessTypescript(config));
}
```

And the new `cypress/tsconfig.json`:
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "allowJs": true
  }
}
```

## Expected Behavior

I expect everything would still work (`yarn cypress run --headless`) after installing `@nrwl/cypress` preprocessor, even the old ".js" specs (or new ".ts" for that matter).

## Current Behavior

But.... cypress chokes when it is processing `cypress/support/index.js`.

The only output I get is:
```
Uncaught ReferenceError: require is not defined
```

The mentioned `require` is the one in `cypress/support/commands.ts`:
```
const compareSnapshotCommand = require('cypress-visual-regression/dist/command');
```
(once commented out, cypress continue to execute the specs, to fail later, due to missing `compareSnapshot` command, which is expected).

### Context

>  NX  Report complete

  @nrwl/angular : Not Found
  @nrwl/cli : 9.2.2
  @nrwl/cypress : 9.2.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : Not Found
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.2
  @nrwl/web : Not Found
  @nrwl/workspace : 9.2.2
  typescript : 3.8.3

3rd party libraries
  cypress: 3.4.0
  cypress-visual-regression: 1.2.0

```
Angular CLI: 9.1.1
Node: 10.19.0
OS: linux x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
```

**Comment by Cammisuli** [comment]
I'm going to investigate using the built in TypeScript preprocessor that's included in Cypress now.

**Comment by kbradl16** [comment]
I'm getting this error with cypress-cucumber-preprocessor as well.

**Comment by laurentsd** [comment]
My fix was to not call on('file:preprocessor', preprocessTypescript(config));
I don't understand why Nx still generates this code even in its latest version...

**Comment by brunano21** [comment]
What version of NX are you currently using?

**Comment by laurentsd** [comment]
Nx 11.6.3

**Comment by brunano21** [comment]
@laurentsd  how are you customizing webpack in that case? I need to hook cypress-cucumber-preprocessor.

**Comment by laurentsd** [comment]
I am not customizing webpack, I don't need to.
