### ISSUE TITLE
updating .eslintrc doesn't invalidate the cache

### ISSUE THREAD

**Issue by snebjorn** [nrwl/nx#2858]
## Expected Behavior

Updating linting rules/config should invalidate linting cache.

## Current Behavior

When running eslint it'll show the cached output even though .eslintrc (workspace root) was changed.

```bash
❯ nx lint akita

> nx run akita:lint 

>  NX   NOTE  Cached Output:

Linting "akita"...
```
### Steps to Reproduce

I'm not sure when the cache kicks in, but once it does you can reproduce this.

1. nx lint stuff
2. watch cache kick in
3. add a new rule to the rules section in the root .eslintrc
4. nx lint stuff
5. observe the previous cached and now invalid response

### Context

```bash
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 9.2.2
  @nrwl/cli : 9.2.2
  @nrwl/cypress : 9.2.2
  @nrwl/eslint-plugin-nx : 9.2.2
  @nrwl/express : 9.2.2
  @nrwl/jest : 9.2.2
  @nrwl/linter : 9.2.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.2.2
  @nrwl/react : 9.2.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.2
  @nrwl/web : 9.2.2
  @nrwl/workspace : 9.2.2
  typescript : 3.8.3
```

"eslint": "6.8.0",
"@typescript-eslint/eslint-plugin": "2.28.0",
"@typescript-eslint/parser": "2.28.0",

**Comment by jaysoo** [comment]
Hi @snebjorn, the `.eslintrc` file isn't currently being considered in cache calculations.

Can you try adding a `runtimeCacheInputs` entry to your `nx.json`?

```
"tasksRunnerOptions": {
    "default": {
      "options": {
        "cacheableOperations": ["build", "lint", "test"]
        "runtimeCacheInputs": ["echo .eslintrc"]
      }
    }
  }
```

This will `echo` out the content of the file so it will be considered in cache invalidation.

@FrozenPandaz Looks like it might be time to make the root file list extendable? https://github.com/nrwl/nx/blob/a06c256/packages/workspace/src/core/file-utils.ts#L198

**Comment by snebjorn** [comment]
adding `"runtimeCacheInputs": ["echo .eslintrc"]` doesn't help.

After adding it I ran linting until it gave me the cached output, then I changed a rule from "off" to "warn" and ran linting again `nx lint <project>` but I still got the cached output

**Comment by rarmatei** [comment]
> adding `"runtimeCacheInputs": ["echo .eslintrc"]` doesn't help.
> 
> After adding it I ran linting until it gave me the cached output, then I changed a rule from "off" to "warn" and ran linting again `nx lint <project>` but I still got the cached output
> 
> yes, I did remember to save the file :)

Can you please try `cat .eslintrc` instead of `echo` ? Echo will print out the file name, but we want to print out the contents, so it invalidates the cache when they change (as Jack mentioned)

**Comment by snebjorn** [comment]
Strange it doesn't recognize `cat` but `cat` works fine in the terminal. I'm on windows.

```bash
❯ nx lint akita
'cat' is not recognized as an internal or external command,
operable program or batch file.
(node:6184) UnhandledPromiseRejectionWarning: Error: Nx failed to execute runtimeCacheInputs defined in nx.json failed:
Command failed: cat .eslintrc
'cat' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by rarmatei** [comment]
if you're on windows, maybe try `type .eslintrc` ? 

https://superuser.com/questions/434870/what-is-the-windows-equivalent-of-the-unix-command-cat

**Comment by snebjorn** [comment]
okay type seem to do the job.

But if I use CTRL+Z and then save to alter the file it doesn't invalidate the cache. If I manually type what the result of CTRL+Z would have been then the cache is invalidated.
I don't even know how that's possible :/

**Comment by rarmatei** [comment]
apologies I'm not completely sure what you mean by using CTRL+Z to alter the file - are you undoing your changes?

The Nx cache stores multiple hashes. 

1. So let's say your `.eslintrc` file contains "some-string"
2. You invoke linting
3. The cache mechanism will call `type .eslintrc`, see that its output is "some-string" and will create a hash from that, and store it `node_modules/.cache` along with the output of your command
3. You invoke linting again, but because nothing has changed, it will just pull in the results from the cache, so it should be instant
4. You then change the contents of `.eslintrc` to "other-string"
5. Steps 2 and 3 will be repeated, it will run the full linter, cache the new contents of `.eslintrc`
6. You now change the contents of `.eslintrc` **back to** "some-string" and run linting
7. This time, even though you just changed `.eslintrc`, because you changed it back to a version it had already cached (in step 3), it will just pull those results instantly - so it won't run the full caching again

Does it make sense? 🤔

**Comment by snebjorn** [comment]
Thanks for the explanation, the multiple caches explains quite a bit.

I'm not able to reproduce my CTRL+Z problem. I'm calling an error 40 on that one :)

**Comment by Hotell** [comment]
also make sure to use `--skip-nx-cache` or manually remove nx cache folder from `node_modules` when you're troubleshooting

**Comment by snebjorn** [comment]
This is still an issue.

If caching files in the root folder isn't something you'll do, then close this issue.

**Comment by vsavkin** [comment]
Sorry. The issue was marked by mistake. I removed the label.

**Comment by IshIvan** [comment]
Hi! Add your `.eslintrc` to `nx.json`
```
"implicitDependencies": {
        ".eslintrc": "*",
}
```
