### ISSUE TITLE
Switch to Inkeep Search

### ISSUE THREAD

**Issue by ntotten** [nrwl/nx#28585]
### Documentation issue

One thing that I find difficult with using NX is that the search is really bad. Algolia docs search fails to give me the results I am looking for way too often. We (zuplo.com) have switched to [Inkeep](https://inkeep.com/) for our search and love it. IMO it would be super helpful for nx.dev to be searchable with inkeep.

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.

### Additional context or description

Provide any additional details here as needed.

**Comment by isaacplmann** [comment]
We have updated some of the search settings.  We don't plan to use Inkeep, but hopefully search is working better for you.
