### ISSUE TITLE
NODE_ENV=development in production (vite:build)

### ISSUE THREAD

**Issue by ViktorPontinen** [nrwl/nx#28584]
### Current Behavior

Running: `nx build some-app` produces:

`NODE_ENV = development`

### Expected Behavior

Running: `nx build some-app` produces:

`NODE_ENV = production`

### Steps to Reproduce

Our build target:
```
    "build": {
      "executor": "@nx/vite:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "skipTypeCheck": true,
        "outputPath": "dist/apps/some-name",
        "emptyOutDir": true
      },
      "configurations": {
        "development": {
          "mode": "development",
          "watch": true
        },
        "production": {
          "mode": "production"
        }
      }
    },
```

### Nx Report
```
Node           : 20.18.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.8.2

nx (global)        : 20.0.3
nx                 : 20.0.3
@nx/js             : 20.0.3
@nx/jest           : 20.0.3
@nx/eslint         : 20.0.3
@nx/workspace      : 20.0.3
@nx/cypress        : 20.0.3
@nx/detox          : 20.0.3
@nx/devkit         : 20.0.3
@nx/eslint-plugin  : 20.0.3
@nx/next           : 20.0.3
@nx/playwright     : 20.0.3
@nx/plugin         : 20.0.3
@nx/react          : 20.0.3
@nx/react-native   : 20.0.3
@nx/remix          : 20.0.3
@nx/storybook      : 20.0.3
@nx/vite           : 20.0.3
@nx/web            : 20.0.3
@nx/webpack        : 20.0.3
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
---------------------------------------
Community plugins:
@jscutlery/semver : 5.3.1
---------------------------------------
Local workspace plugins:
	 @org/custom-plugin
```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Seems like this one might the culprit? https://github.com/nrwl/nx/pull/28444

🚨 🚨 🚨 **We updated from NX 19.7.3 to 20.0.3 today and started noticing dev tooling and other dev mode only things showing up in our production environment** 🚨 🚨 🚨 

Temporary fix is to add `NODE_ENV=production` in `.env` file. Will we await info on if this is a NX bug or something on our side.

**Comment by lucavb** [comment]
We are also facing the same issue and are aiming for the same solution. As far as we can tell this change caused it 

https://github.com/nrwl/nx/pull/28252/files

It is no longer considering whether Nx was set to production but Rspack directly just looks for `NODE_ENV` and completely disregards to what Nx was set to.

**Comment by KonstantinKai** [comment]
same problem

**Comment by jsmecham** [comment]
We are also experiencing this issue. Where previously `nx build` would result in `NODE_ENV=production` builds, it has now reverted to `development`.
