### ISSUE TITLE
CLI update?

### ISSUE THREAD

**Issue by abnersouza** [nrwl/nx#286]
I recently migrated my project to use Nx. I was with the latest version of the Angular CLI 1.7.0, but I know that nx uses a gzip with it's own cli version. After the migration it set on my package.json the cli from the zip and also kept my in the dev dependencies, but I removed mine. I decided to keep Nx even tough In my project the only nx command that is working is the one to create libs, all the other ones (create app, create lib with routing and so on) none are working, tested outside my project some are working some are not.

First is should i remove my cli dependency? 
Any plans to update the CLI gzip? or How can I do it?

**Comment by tommyc38** [comment]
I removed my my cli by accident from within an existing Nx workspace and have no idea what the protocol to upgrade/update the CLI or Nx is supposed to be.  Please advise.

**Comment by kylecordes** [comment]
There is a PR underway right now that updates to CLI 1.7.1, getting rid of the local fork version:

https://github.com/nrwl/nx/pull/289

I suspect most likely once that ships, there will be instructions on how to upgrade from the old set up to the new set up.

**Comment by RicardoVaranda** [comment]
@kylecordes Seems like it's been forked! Any information on the upgrade procedure would be greatly appreciated :)

**Comment by kylecordes** [comment]
@RicardoVaranda It's merged, which is great. I am not "living on the edge" of unpublished Nx-in-progress... but if I had to guess, I'd guess that when you upgrade your Nx dependencies to the upcoming versions, you'll also change the CLI dependency to 1.7.1+, and discard the old custom CLI tgz.  Real upgrade info will have to come from the Nx team, this is just a guess at the bare minimum.

**Comment by Yonet** [comment]
@abnersouza @kylecordes @RicardoVaranda @tommyc38 latest version of nx 0.8.0 is using angular-cli 1.7.1. Thank you for your patience. Closing this issue.

**Comment by maartentibau** [comment]
Any chance the CLI version could be bumped up to v1.7.3 going through the change log I think it should be a small one.
