### ISSUE TITLE
nxViteTsPaths not resolving file imports with "." in filename

### ISSUE THREAD

**Issue by cnorthfield** [nrwl/nx#28615]
### Current Behavior

When `nxViteTsPaths` is used in a vite config file, and the project contains file imports with a dot (.) separator, compilation fails due to a failure in resolving the path.

The following example of importing `foo.enum.ts` fails:
```typescript
import { EnumFoo } from "@foo/foo.enum";
```

The following example of importing `foo.enum.ts` passes:
```typescript
import { EnumFoo } from "@foo/foo.enum.ts";
```

However, the first example is a valid import so it should not fail.

### Expected Behavior

We should expect typescript alias paths to be resolved correctly.

### GitHub Repo

https://github.com/cnorthfield/nx-vite-path-bug

### Steps to Reproduce

1. Clone the repository
2. Run the following command to install the dependencies:

```bash
npm install
```

3. Run the following command to run the tests:

```bash
nx test
```

The error is thrown when running the tests. The error message is:

```
Error: Failed to resolve import "@enums/foo.enum" from "src/app/app.tsx". Does the file exist?
```

### Nx Report

```bash
 NX   Report complete - copy this into the issue template

Node           : 20.12.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.5.0

nx (global)        : 20.0.1
nx                 : 20.0.5
@nx/js             : 20.0.5
@nx/eslint         : 20.0.5
@nx/workspace      : 20.0.5
@nx/devkit         : 20.0.5
@nx/eslint-plugin  : 20.0.5
@nx/react          : 20.0.5
@nx/vite           : 20.0.5
@nx/web            : 20.0.5
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
```

### Package Manager Version

10.5.0

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I believe a recent fix for https://github.com/nrwl/nx/issues/22868 may have introduced this.

When resolving paths, only the extensions set in the plugin should be considered i.e. defaults:
```typescript
['.ts', '.tsx', '.js', '.jsx', '.json', '.mjs', '.cjs']
```

**Comment by huv1k** [comment]
We are facing the same issue, we have imports like:
```tsx 
import Settings from '@acme/settings.module'
import Component from '@acme/component.react'
```
this stoped working after https://github.com/nrwl/nx/pull/27774

**Comment by abrcdf1023** [comment]
Any workaround here?
