### ISSUE TITLE
"nx add [package]" insert the package in wrong place in package.json

### ISSUE THREAD

**Issue by Amit775** [nrwl/nx#28625]
### Current Behavior

"nx add [package]" append the package to the end of the dependencies list
"nx add [package]" also add the package in both dependencies and devDependencies

### Expected Behavior

"nx add [package]" should insert the package alphabetically and keep the dependencies list sorted
"nx add [package]" should insert the package only in dependecies list

### Steps to Reproduce

1. npx create-nx-workspace reproduce --preset=angular
2. cd reproduce
3. nx add @ngrx/signals (happens with several packages that I tryied)

### Nx Report

 NX   Report complete - copy this into the issue template

Node           : 18.20.3
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.4.0

nx (global)        : 20.0.5
nx                 : 20.0.5
@nx/js             : 20.0.5
@nx/jest           : 20.0.5
@nx/eslint         : 20.0.5
@nx/workspace      : 20.0.5
@nx/angular        : 20.0.5
@nx/devkit         : 20.0.5
@nx/eslint-plugin  : 20.0.5
@nx/playwright     : 20.0.5
@nx/vite           : 20.0.5
@nx/web            : 20.0.5
@nx/webpack        : 20.0.5
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/eslint/plugin
---------------------------------------
Community plugins:
@ngrx/signals : 18.1.0

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

{
  "name": "@reproduce/source",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~18.2.0",
    "@angular/common": "~18.2.0",
    "@angular/compiler": "~18.2.0",
    "@angular/core": "~18.2.0",
    "@angular/forms": "~18.2.0",
    "@angular/platform-browser": "~18.2.0",
    "@angular/platform-browser-dynamic": "~18.2.0",
    "@angular/router": "~18.2.0",
    "rxjs": "~7.8.0",
    "zone.js": "~0.14.3",
    "@ngrx/signals": "^18.1.0"    <-----------------------------------------------------
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~18.2.0",
    "@angular-devkit/core": "~18.2.0",
    "@angular-devkit/schematics": "~18.2.0",
    "@angular/cli": "~18.2.0",
    "@angular/compiler-cli": "~18.2.0",
    "@angular/language-service": "~18.2.0",
    "@eslint/js": "^9.8.0",
    "@ngrx/signals": "^18.1.0",   <------------------------------------
    "@nx/angular": "20.0.5",
    "@nx/devkit": "20.0.5",
    "@nx/eslint": "20.0.5",
    "@nx/eslint-plugin": "20.0.5",
    "@nx/jest": "20.0.5",
    "@nx/js": "20.0.5",
    "@nx/playwright": "20.0.5",
    "@nx/web": "20.0.5",
    "@nx/workspace": "20.0.5",
    "@playwright/test": "^1.36.0",
    "@schematics/angular": "~18.2.0",
    "@swc-node/register": "~1.9.1",
    "@swc/core": "~1.5.7",
    "@swc/helpers": "~0.5.11",
    "@types/jest": "^29.5.12",
    "@types/node": "18.16.9",
    "@typescript-eslint/utils": "^8.0.0",
    "angular-eslint": "^18.3.0",
    "eslint": "^9.8.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-playwright": "^1.6.2",
    "jest": "^29.7.0",
    "jest-environment-jsdom": "^29.7.0",
    "jest-preset-angular": "~14.1.0",
    "nx": "20.0.5",
    "prettier": "^2.6.2",
    "ts-jest": "^29.1.0",
    "ts-node": "10.9.1",
    "tslib": "^2.3.0",
    "typescript": "~5.5.2",
    "typescript-eslint": "^8.0.0"
  },
  "nx": {
    "includedScripts": []
  }
}

**Comment by Amit775** [comment]
https://github.com/nrwl/nx/blob/1218502c8444a8d493c7e5006b35d077021d237e/packages/nx/src/command-line/add/add.ts#L56

maybe it's inteded?    
why it use addDev by default?

**Comment by jaysoo** [comment]
Hi @Amit775, the `nx add` add command is not meant to install any package. It's intended to install Nx plugins (e.g. `@nx/angular`, `@nx/vite`, etc.).

This is why it is always a dev dependency, since Nx plugins are not required for production. I would use your package manager for these cases, e.g. npm, yarn, pnpm, or bun.
