### ISSUE TITLE
storybookConfigurationGenerator of @nx/angular adding react dependencies in package.json

### ISSUE THREAD

**Issue by thutinavaneethreddy** [nrwl/nx#28633]
### Current Behavior

When I run storybookConfigurationGenerator for an angular project using the command : `nx g @nx/angular:storybook-configuration --project=test`, it is adding react and react-dom dependencies in package.json

### Expected Behavior

When I run storybookConfigurationGenerator using the command : `nx g @nx/angular:storybook-configuration --project=test`, it should not react and react-dom dependencies in package.json

### Steps to Reproduce

1. In an nx workspace that has angular library, generate the storybook config for the library using : 

`nx g @nx/angular:storybook-configuration --project=<project-name>
`
2. Open package.json, it will add react and react-dom packages, which are not needed to run the storybook or angular libray.

### Nx Report

Node   : 20.18.0
OS     : darwin-x64
npm    : 10.8.2

nx (global)        : 18.2.0
nx                 : 18.2.0
@nx/js             : 18.2.0
@nx/jest           : 18.2.0
@nx/linter         : 18.2.0
@nx/eslint         : 18.2.0
@nx/workspace      : 18.2.0
@nx/angular        : 18.2.0
@nx/cypress        : 18.2.0
@nx/devkit         : 18.2.0
@nx/eslint-plugin  : 18.2.0
@nx/express        : 18.2.0
@nx/nest           : 18.2.0
@nx/node           : 18.2.0
@nx/plugin         : 18.2.0
@nx/storybook      : 18.2.0
@nrwl/tao          : 18.2.0
@nx/web            : 18.2.0
@nx/webpack        : 18.2.0
typescript         : 5.4.2
---------------------------------------
Community plugins:
@koliveira15/nx-sonarqube    : 4.0.0
@ngneat/spectator            : 17.1.0
@ngrx/effects                : 17.0.1
@ngrx/router-store           : 17.0.1
@ngrx/schematics             : 17.0.1
@ngrx/store                  : 17.0.1
@ngrx/store-devtools         : 17.0.1
@storybook/angular           : 8.2.8
apollo-angular               : 7.0.2
ngx-build-plus               : 17.0.0
ngx-daterangepicker-material : 6.0.0

### Operating System

- [x] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
this is not a bug. this is because "Starting in 7.0, react and react-dom are now required peer dependencies of Storybook when using addon-docs" (https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-peer-dependencies-required)
