### ISSUE TITLE
nx affected: is executed against untracked files by default

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#2864]
## Expected Behavior

- `affected` commands are not executed on `untracked` by default
- `affected:apps/affected:libs` properly works with `--untracked`,`--uncommited`

## Current Behavior

**workspace.json**
```json
{
"pb-e2e": {
      "root": "cypress",
      "sourceRoot": "cypress",
      "projectType": "application",
      "architect": {      
        "lint": {
          "builder": "@nrwl/linter:lint",
          "options": {
            "linter": "eslint",
            "config": ".eslintrc",
            "tsConfig": ["cypress/tsconfig.json"],
            "exclude": ["**/node_modules/**", "!cypress/**"]
          }
        }
      }
    }
}
```

**git status**
![image](https://user-images.githubusercontent.com/1223799/79433583-9602a380-7fcd-11ea-90e0-3bd48c9fddb7.png)

**nx affected issues:**

```sh
yarn nx affected:lint
```

will run `pb-e2e` 
![image](https://user-images.githubusercontent.com/1223799/79434129-3789f500-7fce-11ea-8894-a475ac960776.png)

```sh
yarn nx affected:lint --untracked=false
```

has the same issue

**ISSUE no 2:**

On the other hand `affected:libs`,`affected:apps` don't work with cli flags

```sh
yarn nx affected:apps
```
![image](https://user-images.githubusercontent.com/1223799/79434273-6acc8400-7fce-11ea-9dd1-d7b325e7e108.png)

```sh
yarn nx affected:apps --untracked
```

provides the same output

### Context

```
 @nrwl/angular : Not Found
  @nrwl/cli : 9.2.2
  @nrwl/cypress : 9.2.2
  @nrwl/eslint-plugin-nx : 9.2.2
  @nrwl/express : Not Found
  @nrwl/jest : 9.2.2
  @nrwl/linter : 9.2.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.2.2
  @nrwl/react : 9.2.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.2
  @nrwl/web : 9.2.2
  @nrwl/workspace : 9.2.2
  typescript : 3.8.3
```

**Comment by vsavkin** [comment]
When I try it, "yarn nx affected:lint" handles untracked files.

You can see what gets invoked at:
```
node_modules/@nrwl/workspace/src/command-line/shared.js
```

Could you check what path it takes? It should invoke `getUntrackedFiles` which you can tap to see what it returns
