### ISSUE TITLE
Error: The externalDependency 'webpack-cli' for 'server:build' could not be found

### ISSUE THREAD

**Issue by mreouven** [nrwl/nx#28653]
### Current Behavior

NX started to fail when I try to serve or build my NestJS app. It gives this error if Itry to do so:
Error: The externalDependency 'webpack-cli' for 'server:build' could not be found.

This was happening to my existing project. But I also tried it on a fresh NX install and it behaved the same way.

### Expected Behavior

I expect a server to build and/or serve my NestJS app as normal.

### GitHub Repo

No response

### Steps to Reproduce

1.
You install a fresh and clear nx workspace with NestJS project in it.
`npx create-nx-workspace@latest`

### Nx Report

 NX   Report complete - copy this into the issue template

Node           : 20.18.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.12.2

nx (global)        : 20.0.2
nx                 : 20.0.6
@nx/js             : 20.0.6
@nx/jest           : 20.0.6
@nx/eslint         : 20.0.6
@nx/workspace      : 20.0.6
@nx/eslint-plugin  : 20.0.6
@nx/nest           : 20.0.6
@nx/node           : 20.0.6
@nx/web            : 20.0.6
@nx/webpack        : 20.0.6
typescript         : 5.6.3
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin

### Failure Logs

[NX Daemon Server] - 2024-10-27T19:33:21.559Z - Started listening on: /var/folders/mj/lww8gths3qg6y2b3wj3_wv1m0000gn/T/27d3b91aec48e45b1e35/d.sock
[NX Daemon Server] - 2024-10-27T19:33:21.560Z - [WATCHER]: Subscribed to changes within:  (native)
[NX Daemon Server] - 2024-10-27T19:33:21.562Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2024-10-27T19:33:21.562Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2024-10-27T19:33:21.563Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2024-10-27T19:33:21.563Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2024-10-27T19:33:21.622Z - [WATCHER]: Processing file changes in outputs
[NX Daemon Server] - 2024-10-27T19:33:22.223Z - [REQUEST]: Updated workspace context based on watched changes, recomputing project graph...
[NX Daemon Server] - 2024-10-27T19:33:22.223Z - [REQUEST]: 
[NX Daemon Server] - 2024-10-27T19:33:22.223Z - [REQUEST]: 
[NX Daemon Server] - 2024-10-27T19:33:22.233Z - Time taken for 'loadNxPlugins' 658.537375ms
[NX Daemon Server] - 2024-10-27T19:33:22.233Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2024-10-27T19:33:22.233Z - Established a connection. Number of open connections: 3
[NX Daemon Server] - 2024-10-27T19:33:22.234Z - Closed a connection. Number of open connections: 2
[NX Daemon Server] - 2024-10-27T19:33:22.234Z - Established a connection. Number of open connections: 3
[NX Daemon Server] - 2024-10-27T19:33:22.235Z - [REQUEST]: Responding to the client. handleHashGlob
[NX Daemon Server] - 2024-10-27T19:33:22.235Z - Done responding to the client handleHashGlob
[NX Daemon Server] - 2024-10-27T19:33:22.235Z - Handled HASH_GLOB. Handling time: 0. Response time: 1.
[NX Daemon Server] - 2024-10-27T19:33:22.235Z - Established a connection. Number of open connections: 4
[NX Daemon Server] - 2024-10-27T19:33:22.235Z - Closed a connection. Number of open connections: 3
[NX Daemon Server] - 2024-10-27T19:33:22.235Z - Established a connection. Number of open connections: 4
[NX Daemon Server] - 2024-10-27T19:33:22.236Z - [REQUEST]: Responding to the client. handleGlob
[NX Daemon Server] - 2024-10-27T19:33:22.236Z - Done responding to the client handleGlob
[NX Daemon Server] - 2024-10-27T19:33:22.236Z - Handled GLOB. Handling time: 1. Response time: 0.
[NX Daemon Server] - 2024-10-27T19:33:22.236Z - Established a connection. Number of open connections: 5
[NX Daemon Server] - 2024-10-27T19:33:22.236Z - Closed a connection. Number of open connections: 4
[NX Daemon Server] - 2024-10-27T19:33:22.236Z - [REQUEST]: Responding to the client. handleHashGlob
[NX Daemon Server] - 2024-10-27T19:33:22.236Z - Done responding to the client handleHashGlob
[NX Daemon Server] - 2024-10-27T19:33:22.236Z - Handled HASH_GLOB. Handling time: 0. Response time: 0.
[NX Daemon Server] - 2024-10-27T19:33:22.237Z - [REQUEST]: Responding to the client. handleHashGlob
[NX Daemon Server] - 2024-10-27T19:33:22.237Z - Done responding to the client handleHashGlob
[NX Daemon Server] - 2024-10-27T19:33:22.237Z - Handled HASH_GLOB. Handling time: 0. Response time: 0.
[NX Daemon Server] - 2024-10-27T19:33:22.304Z - [REQUEST]: Responding to the client. handleHashGlob
[NX Daemon Server] - 2024-10-27T19:33:22.304Z - Done responding to the client handleHashGlob
[NX Daemon Server] - 2024-10-27T19:33:22.304Z - Handled HASH_GLOB. Handling time: 1. Response time: 0.
[NX Daemon Server] - 2024-10-27T19:33:22.304Z - [REQUEST]: Responding to the client. handleHashGlob
[NX Daemon Server] - 2024-10-27T19:33:22.304Z - Done responding to the client handleHashGlob
[NX Daemon Server] - 2024-10-27T19:33:22.304Z - Handled HASH_GLOB. Handling time: 0. Response time: 0.
[NX Daemon Server] - 2024-10-27T19:33:22.306Z - [REQUEST]: Responding to the client. handleHashGlob
[NX Daemon Server] - 2024-10-27T19:33:22.306Z - Done responding to the client handleHashGlob
[NX Daemon Server] - 2024-10-27T19:33:22.306Z - Handled HASH_GLOB. Handling time: 0. Response time: 0.
[NX Daemon Server] - 2024-10-27T19:33:22.307Z - [REQUEST]: Responding to the client. handleHashGlob
[NX Daemon Server] - 2024-10-27T19:33:22.307Z - Done responding to the client handleHashGlob
[NX Daemon Server] - 2024-10-27T19:33:22.307Z - Handled HASH_GLOB. Handling time: 1. Response time: 0.
[NX Daemon Server] - 2024-10-27T19:33:22.309Z - [REQUEST]: Responding to the client. handleHashGlob
[NX Daemon Server] - 2024-10-27T19:33:22.309Z - Done responding to the client handleHashGlob
[NX Daemon Server] - 2024-10-27T19:33:22.309Z - Handled HASH_GLOB. Handling time: 0. Response time: 0.
[NX Daemon Server] - 2024-10-27T19:33:22.545Z - [REQUEST]: Responding to the client. handleHashGlob
[NX Daemon Server] - 2024-10-27T19:33:22.545Z - Done responding to the client handleHashGlob
[NX Daemon Server] - 2024-10-27T19:33:22.545Z - Handled HASH_GLOB. Handling time: 1. Response time: 0.
[NX Daemon Server] - 2024-10-27T19:33:22.549Z - [REQUEST]: Responding to the client. handleHashGlob
[NX Daemon Server] - 2024-10-27T19:33:22.549Z - Done responding to the client handleHashGlob
[NX Daemon Server] - 2024-10-27T19:33:22.549Z - Handled HASH_GLOB. Handling time: 0. Response time: 0.
[NX Daemon Server] - 2024-10-27T19:33:23.030Z - Time taken for 'build-project-configs' 796.3743749999999ms
[NX Daemon Server] - 2024-10-27T19:33:23.179Z - [SYNC]: collect registered sync generators
[NX Daemon Server] - 2024-10-27T19:33:23.179Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2024-10-27T19:33:23.179Z - Time taken for 'total for creating and serializing project graph' 1615.556083ms
[NX Daemon Server] - 2024-10-27T19:33:23.180Z - Done responding to the client project-graph
[NX Daemon Server] - 2024-10-27T19:33:23.180Z - Handled REQUEST_PROJECT_GRAPH. Handling time: 1616. Response time: 1.
/node_modules/.pnpm/nx@20.0.6_@swc-node+register@1.10.9_@swc+core@1.7.40_@swc+helpers@0.5.13__@swc+types@0.1.13_t_yfhvfmjec33wurs27rewo4dhoi/node_modules/nx/src/hasher/native-task-hasher-impl.js:32
        const plans = this.planner.getPlansReference(tasks.map((t) => t.id), taskGraph);
                                   ^

Error: The externalDependency 'webpack-cli' for 'infinity-market-server:build' could not be found
    at NativeTaskHasherImpl.hashTasks (/node_modules/.pnpm/nx@20.0.6_@swc-node+register@1.10.9_@swc+core@1.7.40_@swc+helpers@0.5.13__@swc+types@0.1.13_t_yfhvfmjec33wurs27rewo4dhoi/node_modules/nx/src/hasher/native-task-hasher-impl.js:32:36)
    at InProcessTaskHasher.hashTasks (/node_modules/.pnpm/nx@20.0.6_@swc-node+register@1.10.9_@swc+core@1.7.40_@swc+helpers@0.5.13__@swc+types@0.1.13_t_yfhvfmjec33wurs27rewo4dhoi/node_modules/nx/src/hasher/task-hasher.js:41:46)
    at handleHashTasks (/node_modules/.pnpm/nx@20.0.6_@swc-node+register@1.10.9_@swc+core@1.7.40_@swc+helpers@0.5.13__@swc+types@0.1.13_t_yfhvfmjec33wurs27rewo4dhoi/node_modules/nx/src/daemon/server/handle-hash-tasks.js:30:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleResult (/node_modules/.pnpm/nx@20.0.6_@swc-node+register@1.10.9_@swc+core@1.7.40_@swc+helpers@0.5.13__@swc+types@0.1.13_t_yfhvfmjec33wurs27rewo4dhoi/node_modules/nx/src/daemon/server/server.js:172:16)
    at async handleMessage (/node_modules/.pnpm/nx@20.0.6_@swc-node+register@1.10.9_@swc+core@1.7.40_@swc+helpers@0.5.13__@swc+types@0.1.13_t_yfhvfmjec33wurs27rewo4dhoi/node_modules/nx/src/daemon/server/server.js:110:9)
    at async /node_modules/.pnpm/nx@20.0.6_@swc-node+register@1.10.9_@swc+core@1.7.40_@swc+helpers@0.5.13__@swc+types@0.1.13_t_yfhvfmjec33wurs27rewo4dhoi/node_modules/nx/src/daemon/server/server.js:72:9 {
  code: 'GenericFailure'
}

Node.js v20.18.0

### Package Manager Version

npm

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Hey, thanks for reporting this issue.
I tried creating a new project using inferred targets and without and they both are working as expected

Can you show your `project.json` and `nx.json` config files? 
Or you can create a small repo and share the details on this thread for us to investigate?

**Comment by mreouven** [comment]
After investigating I found that the problem occurred when I set package-lock or phnom lock in gitignore
