### ISSUE TITLE
How to add storybook support to an older nx version ?

### ISSUE THREAD

**Issue by roger-gl** [nrwl/nx#2866]
I'm currently using 8.7.1 and I want to add storybook support to my project. It seems as if that started with 8.8 ? But just running  npx nx migrate 8.8 didn't work. So the question is how can I upgrade to a version that supports it, or even better add a storybook config to the current 8.7.1 ?

**Comment by roger-gl** [comment]
I upgraded manually by changing each version related to nx from 8.7.1 to 8.8.1. After that the storybook stuff worked (except that nx run didn't work). One final question since I want to reduce the impact to the production code as much as possible. Cann  "@nrwl/angular" be also a dev dependency ?

**Comment by FrozenPandaz** [comment]
`@nrwl/angular` is only needed at runtime if you are using the `DataPersistance` class or operators.

**Comment by FrozenPandaz** [comment]
Closing as I think this question is answered. You can reopen if the answer is unclear.
