### ISSUE TITLE
Problem with tests in a starter template

### ISSUE THREAD

**Issue by Faithfinder** [nrwl/nx#2869]
## Expected Behavior

I run `npx create-nx-workspace` (with options "Angular" and "CSS") and it creates a functional starter project

## Current Behavior

The project immediately has a problem in `app.component.spec.ts` - `"Error: Failed: "Zone is needed for the async() test helper but could not be found. Please make sure that your environment includes zone.js/dist/zone.js"`

### Context
  @nrwl/angular : 9.2.2
  @nrwl/cli : 9.2.2
  @nrwl/cypress : 9.2.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.2.2
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.2
  @nrwl/web : Not Found
  @nrwl/workspace : 9.2.2
  typescript : 3.8.3

**Comment by brandonroberts** [comment]
I tried this with the latest version of Nx, and it ran the tests correctly. If you're still having issues after upgrading, reopen this issue. Thanks
