### ISSUE TITLE
nx build does not replace environment file in any variation

### ISSUE THREAD

**Issue by naishe** [nrwl/nx#2870]
I have the following configuration in my `workspace.json` for my NodeJS project:

```JSON
"configurations": {
            "production": {
              "optimization": true,
              "extractLicenses": true,
              "inspect": false,
              "fileReplacements": [
                {
                  "replace": "apps/api/src/environments/environment.ts",
                  "with": "apps/api/src/environments/environment.prod.ts"
                }
              ]
            },
            "test": {
              "optimization": true,
              "extractLicenses": true,
              "inspect": false,
              "fileReplacements": [
                {
                  "replace": "apps/api/src/environments/environment.ts",
                  "with": "apps/api/src/environments/environment.test.ts"
                }
              ]
            }
          }
        },
```
The environment files sit in the same hierarchy:
<img width="217" alt="The environment files sit in the same hierarchy" src="https://user-images.githubusercontent.com/845424/79641224-ca37b900-81b3-11ea-818d-5fe7dc6f3f61.png">

I am unable to find which command will pick up the `test` configuration. I have tried multiple things it did not work:

```bash
nx build api --test # does not work
NODE_ENV=test nx build api # does not work
NODE_ENV=test nx build api --test # does not work
nx build api -c=test # does not work
nx build api -c test # does not work
nx build api --prod # works for prod env file
```

## Expected Behavior
I should be able to choose between different environment files during the build.

## Current Behavior
`fileReplacement` does not seem to work for NodeJS project for anything other than `prod`.

### Steps to Reproduce
In your workspace with one server side project, say api, do the the following:
1. Add a new file `environment.test.ts` on the same pattern as the existing `environment.prod.ts`
2. In the `workspace.json` under the `"api" > "architect" > "buiid"  > "configurations"` block, add a new configuration for the "test" environment that looks like the existing "production" configuration, except it has `"fileReplacements"` array that looks like this:  
```JSON
               {
                  "replace": "apps/api/src/environments/environment.ts",
                  "with": "apps/api/src/environments/environment.test.ts"
                }
```
Now try to do a build that picks up and replaces  environment.ts with environment.test.ts during the build. It does not seem to be possible. 

The commands I tried above did not help me. Here is my nx version.

```
nx --version
8.9.0
```

**Comment by naishe** [comment]
Raised this question on StackOverflow: https://stackoverflow.com/questions/61294196/nwrl-nx-environment-files-is-not-replaced-for-nodejs-project-for-non-local-non

**Comment by naishe** [comment]
Any ideas? @jaysoo @rarmatei 

Sorry for bothering you guys, I am feeling like I am stuck at a dead end.

**Comment by rarmatei** [comment]
can you please try `nx build api --configuration=test` ?

If not, can you please create an example repo showing this problem?

**Comment by naishe** [comment]
Thanks, will do it right away!

**Comment by naishe** [comment]
Apologies. The `--configuration` worked. For some reason when I tried `--configuration` yesterday following the documentation (it was documented under Angular project), it worked for the React project but it did not _seem_ to work for NodeJS. It is totally my fault.

Thanks for the suggestion.
