### ISSUE TITLE
@nx/next:application generator potential typo?

### ISSUE THREAD

**Issue by Huink7** [nrwl/nx#28703]
### Current Behavior

Because of Nx20 we recently switched nx workspace presets (because next:application is not ready for preset:ts) which lead to diffing what is created for us and what is not. I noticed this line
https://github.com/nrwl/nx/blame/63b745e8c3cd7f00b91397abca6121da34b0b388/packages/next/src/generators/application/lib/create-application-files.ts#L132 

and wanted to verify what the intent was. I assume that its not trying to spread in the updateJson() function from nx/devkit, so its possible that the `d` in updatedJson was missed?

### Expected Behavior

I assume its missing out on some of the original JSON from the tsconfig by not spreading in updatedJson properly.

### Steps to Reproduce

1.

### Nx Report

N/A

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Hey, thanks for reporting this issue. It is incorrect and will be addressed!
