### ISSUE TITLE
Workspace Creation Fails Due to License Field Warning with Yarn

### ISSUE THREAD

**Issue by profitsky** [nrwl/nx#28710]
### Current Behavior

Error: warning ../../../../package.json: No license field
error Command failed with exit code 1

### Expected Behavior

The Nx workspace should be successfully created without errors.

### Steps to Reproduce

1. Run npx create-nx-workspace --pm yarn.
2. Choose:
-Directory for workspace: vvvv
-Stack: none
-Prettier: No
-CI provider: GitHub
3. Nx begins creating the workspace but fails with an error.

### Nx Report

>  NX  Report complete - copy this into the issue template

  Node : x.x.x
  OS   : Your Operating System Info
  yarn : x.x.x

  nx : x.x.x
  @nrwl/angular : Not Found
  @nrwl/cypress : Not Found
  @nrwl/detox : Not Found
  @nrwl/devkit : x.x.x
  @nrwl/eslint-plugin-nx : x.x.x
  @nrwl/express : Not Found
  @nrwl/jest : Not Found
  @nrwl/js : x.x.x
  @nrwl/linter : x.x.x
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : x.x.x
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/react-native : Not Found
  @nrwl/rollup : x.x.x
  @nrwl/storybook : Not Found
  @nrwl/web : Not Found
  @nrwl/workspace : x.x.x
  typescript : x.x.x

### Package Manager Version

yarn: 1.22.19

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

This issue appears to be related to a warning about the missing license field in package.json. Ensuring the workspace creation process handles this warning or providing guidance on how to avoid this error would be helpful.

Thank you for looking into this!

**Comment by abebelagua** [comment]
I have the same issue, @profitsky you managed to fix the error

**Comment by profitsky** [comment]
> I have the same issue, [@profitsky](https://github.com/profitsky) you managed to fix the error

unfortunately no
