### ISSUE TITLE
Cannot run jest tests with `--maxWorkers=50%` option via @nrwl/jest:jest builder

### ISSUE THREAD

**Issue by wrslatz** [nrwl/nx#2871]
The `@nrwl/jest` builder should support both number and string inputs for `maxWorkers` config option. Passing `--maxWorkers=50%` to `ng test` or `nx affected:test` fails with schema validation, but the [Jest CLI Options documentation](https://jestjs.io/docs/en/cli#--maxworkersnumstring) specify that both a number and string are acceptable arguments.

## Expected Behavior

Both `ng test -- --maxWorkers=50%` and `nx affected:test -- --maxWorkers=50%` run tests and do not throw schema validation errors.

## Current Behavior
Both `ng test -- --maxWorkers=50%` and `nx affected:test -- --maxWorkers=50%` result in the following error:
```
Cannot parse arguments. See below for the reasons.
    Argument --maxWorkers could not be parsed using value "50%".Valid type(s) is: number
```

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce
1. `npx create-nx-workspace@latest`
2. Choose a workspace that has tests out of the gate (I chose Angular)
3. Run any test using `"builder": "@nrwl/jest:jest"` and pass `-- --maxWorkers=50%` flag to the command.

### Context

The schema that is now out of date
https://github.com/nrwl/nx/blob/54d06f0fc95e60e55cad23dd28ba665f1592fdc6/packages/jest/src/builders/jest/schema.json#L56-L59

The original PR that implemented this functionality
https://github.com/nrwl/nx/pull/757

The latest jest docs for this functionality
https://jestjs.io/docs/en/cli#--maxworkersnumstring

Minimal reproduction repo
https://github.com/wrslatz/nx-playground/tree/e836200fe7484c6ac022066d13d534f5eb95808b

**Comment by FrozenPandaz** [comment]
Thanks for reporting this!

Looks like the type of the option needs to be `number | string`

This would be a good first issue.

**Comment by wrslatz** [comment]
I'd be happy to submit a PR for review!

**Comment by wrslatz** [comment]
I've submitted #3025 to close this issue. Would appreciate a review whenever it's convenient!
