### ISSUE TITLE
[BUG]: NX 20 creates DEV React bundles - integrating them in other apps causes errors (Uncaught TypeError: xyz.jsxDEV is not a function)

### ISSUE THREAD

**Issue by andrastoth-ws** [nrwl/nx#28721]
### Current Behavior

After upgrading a monorepo with React projects in it to `20.0.x` we have seen DEV bundles created instead of production ones. The error became visible when we used a UI package generated by `nx20` and included elsewhere. We encountered this error:

`Uncaught TypeError: xyz.jsxDEV is not a function`

After digging for the reasons we have figured out that since we upgraded our `production` build creates minified DEV bundles. Reverting back to `19.8.8.` solved the issue.

### Expected Behavior

A production build is executed resulting in a bundle without `jsxDEV` references.

### GitHub Repo

https://github.com/andrastoth-ws/nx20-react-production-bug-repro

### Steps to Reproduce

1. Create a new monorepo project with a React project in, it using `"nx": "20.0.6"`
2. Change the `project.json` file of the freshly generated React app to this:
```json
{
  "name": "nx-20-jsxdev-repro",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/nx-20-jsxdev-repro/src",
  "projectType": "application",
  "tags": [],
  "// targets": "to see all targets run: nx show project nx-20-jsxdev-repro --web",
  "targets": {
    "build": {
      "executor": "@nx/vite:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "outputPath": "dist/apps/nx-20-jsxdev-repro"
      },
      "configurations": {
        "development": {
          "mode": "development"
        },
        "production": {
          "mode": "production"
        }
      }
    }
  }
}
```

3. Run `nx run nx-20-jsxdev-repro:build:production` to create a production bundle
4. Check for `jsxDEV` references in the generated files

Alternatively, you can use the bug repro project, run a `production` build as it is, then downgrade version to `19.8.8` and compare the two outputs.

### Nx Report

 NX   Report complete - copy this into the issue template

Node           : 20.16.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.8.1

nx                 : 20.0.6
@nx/js             : 20.0.6
@nx/jest           : 20.0.6
@nx/eslint         : 20.0.6
@nx/workspace      : 20.0.6
@nx/devkit         : 20.0.6
@nx/eslint-plugin  : 20.0.6
@nx/react          : 20.0.6
@nx/vite           : 20.0.6
@nx/web            : 20.0.6
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
@nx/jest/plugin

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Fixed by: https://github.com/nrwl/nx/pull/28663
