### ISSUE TITLE
[Feature Request] Using environment variables with accessToken (distributed caching)

### ISSUE THREAD

**Issue by kkuriata** [nrwl/nx#2873]
I'm trying to use cloud distributed caching in my project. It works fine, but there is an issue with `accessToken` which is placed inside `nx.json`. As it is a JSON, I can't set dynamic key using ENV - one for CI and one (read-only) for local use. Unfortunately I checked the [DC](https://nx.dev/angular/guides_ci/distributed-builds) and [CLI](https://nx.dev/angular/cli/affected) docs and there is no alternative way (parameter) to set `accessToken`.

I know I can do a workaround - using `fileReplacements` in `workspace.json`/`angular.json`. But having a copy of this file and specifying `--configuration` flag just for one token is not the best approach.

## Expected Behavior

To be able to use ENV to set `accessToken` dynamically.

## Current Behavior

No such possibility.

### Context

```
Angular CLI: 9.1.0
Node: 12.14.1
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
```

### Other

Maybe I'm missing something, because why would you give a possibility of creating multiple access tokens, but no possibility to use more than one?

**Comment by arjunyel** [comment]
You could update the nx.json via a script https://medium.com/@ferie/how-to-pass-environment-variables-at-building-time-in-an-angular-application-using-env-files-4ae1a80383c

**Comment by FrozenPandaz** [comment]
The environment variable to set the Nx Cloud access token is `NX_CLOUD_AUTH_TOKEN=(your-token-here)`.

If you sign into https://nx.app and go to your workspace, you can click the `Workspace Options` button on the top right:

![image](https://user-images.githubusercontent.com/8104246/80834339-859e1b80-8bbe-11ea-853f-272708f4cb01.png)

There, there is documentation for different ways to setup your access token:

![image](https://user-images.githubusercontent.com/8104246/80834410-a9f9f800-8bbe-11ea-8f02-706ced60ae9b.png)

**Comment by kkuriata** [comment]
@FrozenPandaz Thanks for pointing a solution for that. But how can I use `dotenv` with that? I have multiple projects and I would prefer setting `.env` file locally instead of real user/system environments. I have found some alternative, but I'm already using `dotenv` with some worker scritps inside project, but not sure how to inject the variables isnide `nx`.

**Comment by cyrus-za** [comment]
+1. This issue should be reopened as it's not been answered properly
