### ISSUE TITLE
Imports of lazy loaded modules are forbidden

### ISSUE THREAD

**Issue by classifieds-dev** [nrwl/nx#2876]
Hello,

I have an app and several libraries. To make things simple lets say my main application is "app" and one of my libs is "blog". The blog module /lib is lazy loaded into the app via route "blog". However, the blog module also requires some settings such as; the blog endpoint url. The blog endpoint url is stored inside the app environments json file. The blog module has an exported token for those settings. However, when I attempt to import the blog lib inside the app.module file there is a tslint rule violation saying this shouldn't be done because the blog module is being lazy loaded in a route as well. Has anyone else ran into this issue and if so what patterns are available that wouldn't require placing the configuration for libs within libs directory themselves. I would like to keep everything organized inside the single environment file in the app. Below is an example of what I'm talking about.

```javascript
export const environment = {
  production: false,
  mediaSettings: {
    ...
  },
  chatSettings: {
     ...
  },
  blogSettings: {
     ...
  },
};
```

In this case where media, chat, and blog are each independent libs with models and tokens for their settings.

```javascript
const routes = [
  ...
  { path: 'blogs', loadChildren: () => import('@wsname/blogs').then(m => m.BlogsModule) },
];

@NgModule({
  ...
  providers: [
    { provide: CHAT_SETTINGS, useValue: new ChatSettings(environment.chatSettings) },
    { provide: MEDIA_SETTINGS, useValue: new MediaSettings(environment.mediaSettings) },
    // This is what I want to do but get a tslint rule violation in the import due to blog also being lazy loaded.
    { provide: BLOG_SETTINGS, useValue: new BlogSettings(environment.blogSettings) },
  ]
})
export class AppModule {}
```

**Comment by FrozenPandaz** [comment]
Importing from paths that are meant to be lazy loading negates some of the effect of bundling (depending on what the target ES version is).

Thus, it is recommended to make a separate library for those types of tokens or data such as `@wsname/blogs/token` and for the feature to be loaded from `@wsname/blogs/feature` for example.
