### ISSUE TITLE
React / rspack - File replacement do not work with @nx/rspack:rspack

### ISSUE THREAD

**Issue by seb-mynotary** [nrwl/nx#28779]
### Current Behavior

Attribute fileReplacement in project.json is ignored. 

### Expected Behavior

Attribute fileReplacement in project.json should not be ignored and files should be replaced.

### GitHub Repo

https://github.com/seb-mynotary/nx-rspack

### Steps to Reproduce

1. `git clone https://github.com/seb-mynotary/nx-rspack.git`
2. `nx run demo:serve:production `
3. Inspect the generated html

### Nx Report

Node           : 20.10.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.4.0

nx (global)        : 20.0.6
nx                 : 20.0.8
@nx/js             : 20.0.8
@nx/eslint         : 20.0.8
@nx/workspace      : 20.0.8
@nx/eslint-plugin  : 20.0.8
@nx/react          : 20.0.8
@nx/rspack         : 20.0.8
@nx/vite           : 20.0.8
@nx/web            : 20.0.8
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin

### Package Manager Version

pnpm 9.4.0

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by seb-mynotary** [comment]
@Coly010 I was able to make it work by using this setup :

```
 {
              "replace": "./env",
              "with": "./env.production"
            }
```
I dunno if it helps

**Comment by Coly010** [comment]
Fixed by: https://github.com/nrwl/nx/pull/28825
