### ISSUE TITLE
Remote cache on S3 not working with Powerpack

### ISSUE THREAD

**Issue by wewelll** [nrwl/nx#28776]
### Current Behavior

I have followed the documentation to setup remote caching on s3: 

- I activated my license with `nx activate-powerpack XXXX` 
- I have installed the package `@nx/powerpack-s3-cache` and as I use AWS SSO, I added this to my `nx.json`: 

```json
 "s3": {
    "ssoProfile": "my-sso-profile",
    "region": "my-region",
    "bucket": "my-bucket"
  },
```

At this point my config looks correct, but when I run an NX task, there is no cache step happening, and I see no error. It is as if NX wasn't aware of the remote cache configuration. 

I've tried many things, for instance:
- `nx reset`
- adding `NX_DB_CACHE=true` (undocumented btw)

Also my workspace is not connected to NX Cloud, I'm assuming it's not necessary to make S3 caching work. 

Am I missing something to make remote caching work on S3 ?

### Expected Behavior

NX should use the remote cache on S3

### Steps to Reproduce

1. Activate Powerpack
2. Add powerpack S3 configuration for remote caching
3. Caching does not work

### Nx Report

Node           : 20.18.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.12.3

nx                 : 20.0.5
@nx/js             : 20.0.5
@nx/jest           : 20.0.5
@nx/eslint         : 20.0.5
@nx/workspace      : 20.0.5
@nx/devkit         : 20.0.5
@nx/esbuild        : 20.0.5
@nx/eslint-plugin  : 20.0.5
@nx/node           : 20.0.5
@nx/plugin         : 20.0.5
@nx/react          : 20.0.5
@nx/vite           : 20.0.5
@nx/web            : 20.0.5
@nx/webpack        : 20.0.5
typescript         : 5.6.3

---------------------------------------
Nx Powerpack
Licensed to Spiko for 5 users in 1 workspace until 10/21/2025

@nx/powerpack-s3-cache  : 1.0.9

---------------------------------------
Community plugins:
@nx-tools/nx-container : 6.1.0
---------------------------------------
Local workspace plugins:
	 @spiko/nx-plugin

### Package Manager Version

PNPM

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Cammisuli** [comment]
Are you seeing remote cache hits on CI? If you're running this locally you won't see any results.

Also make sure that `useLegacyCache` is false or removed in the nx.json if it exists there.

**Comment by wewelll** [comment]
`useLegacyCache` is set to `false`

**Comment by Cammisuli** [comment]
is the powerpack license checked into the repo under `./.nx/powerpack/license.ini`?

**Comment by tidusjar** [comment]
It states here: https://nx.dev/nx-enterprise/activate-powerpack#2-register-the-license-key

If this is an OSS application use env vars, otherwise if it's closed source you could commit the license key.

I also have `.nx` in my `.gitignore`, but will add in an exception for the license file

**Comment by wewelll** [comment]
Ok thanks, it works by adding the license to the repo 👍
