### ISSUE TITLE
Error occurring in effects

### ISSUE THREAD

**Issue by joelmuskwe** [nrwl/nx#2880]
- [X] I am running the latest version
- [X] I checked the documentation (nx.dev) and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Generating effects with or without data persistance using the createEffect() without throwing error in scaffolded files.

## Current Behavior
Throwing error: `Type 'Observable<any>' is not assignable to type 'Observable<Action> | ((...args: any[]) => Observable<Action>)'.`

## Failure Information (for bugs)
`Type 'Observable<any>' is not assignable to type 'Observable<Action> | ((...args: any[]) => Observable<Action>)'.
  Type 'Observable<any>' is not assignable to type 'Observable<Action>'.
    The types of 'source.operator.call' are incompatible between these types.
      Type '(subscriber: import("/Users/joelmuskwe/Projects/1_work/lab/demo-suite/node_modules/@nrwl/angular/node_modules/rxjs/internal/Subscriber").Subscriber<any>, source: any) => import("/Users/joelmuskwe/Projects/1_work/lab/demo-suite/node_modules/@nrwl/angular/node_modules/rxjs/internal/types").TeardownLogic' is not assignable to type '(subscriber: import("/Users/joelmuskwe/Projects/1_work/lab/demo-suite/node_modules/rxjs/internal/Subscriber").Subscriber<any>, source: any) => import("/Users/joelmuskwe/Projects/1_work/lab/demo-suite/node_modules/rxjs/internal/types").TeardownLogic'.
        Types of parameters 'subscriber' and 'subscriber' are incompatible.
          Type 'import("/Users/joelmuskwe/Projects/1_work/lab/demo-suite/node_modules/rxjs/internal/Subscriber").Subscriber<any>' is not assignable to type 'import("/Users/joelmuskwe/Projects/1_work/lab/demo-suite/node_modules/@nrwl/angular/node_modules/rxjs/internal/Subscriber").Subscriber<any>'.
            Property 'isStopped' is protected but type 'Subscriber<T>' is not a class derived from 'Subscriber<T>'.ts(2322)
effect_creator.d.ts(40, 198): The expected type comes from the return type of this signature.`

### Steps to Reproduce

1. yarn create nx-workspace demo-web
2. ng add @nrwl/angular
3. ng generate @nrwl/angular:application --name=demo-web --style=scss --routing --tags=scope:shared,type:app,platform:web
4. ng generate @nrwl/angular:ngrx --name=DemoState --module=apps/demo-web/src/app/app.module.ts --root --useDataPersistence
5. Imported `import { NxModule } from '@nrwl/angular';` in app.module.ts and added 
    NxModule.forRoot() in the imports section.
6. ng generate @nrwl/workspace:workspace-schematic --name=feature

**(feature schematic: index.ts)**
```ts
import { chain, externalSchematic, Rule } from '@angular-devkit/schematics';
import * as path from 'path';

export default function(schema: any): Rule {
  return chain([
    externalSchematic('@nrwl/angular', 'lib', {
      name: !schema.name.includes('-feature-shell')
        ? `${schema.name}-feature-shell`
        : schema.name,
      directory:
        schema.directory +
        `/${
          schema.name.includes('-feature-shell')
            ? schema.name.replace('-feature-shell', '')
            : schema.name
        }`,
      prefix: schema.prefix,
      simpleModuleName: true,
      style: schema.style,
      routing: schema.routing,
      lazy: schema.lazy,
      parentModule: schema.parentModule,
      unitTestRunner: schema.unitTestRunner,
      tags: schema.tags
    }),
    externalSchematic('@nrwl/angular', 'library', {
      name: `${
        schema.name.includes('data-access-')
          ? schema.name.replace('data-access-', '')
          : schema.name
      }-data-access`,
      directory:
        schema.directory +
        `/${
          schema.name.includes('data-access-')
            ? schema.name.replace('data-access-', '')
            : schema.name
        }`,
      unitTestRunner: schema.unitTestRunner,
      prefix: schema.prefix,
      style: schema.style,
      tags: 'scope:shared,type:data-access',
      simpleModuleName: true
    }),
    externalSchematic('@nrwl/angular', 'ngrx', {
      name: schema.name,
      root: false,
      module: path.join(
        'libs',
        schema.directory,
        schema.name,
        `${schema.name}-data-access`,
        `src`,
        `lib`,
        `${schema.name}-data-access.module.ts`
      ),
      facade: true,
      syntax: 'creators',
      useDataPersistence: true
    }),
    externalSchematic('@schematics/angular', 'service', {
      name: schema.name,
      project: `${schema.directory.replace(/\//g, '-')}-${schema.name.replace(
        /\//g,
        '-'
      )}-${schema.name.replace(/\//g, '-')}-data-access`
    })
  ]);
}
```

**(feature schematic: schema.json)**
```json
{
  "$schema": "http://json-schema.org/schema",
  "id": "feature",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Library name",
      "$default": {
        "$source": "argv",
        "index": 0
      },
      "x-prompt": "What name would you like to use for the feature library?"
    },
    "directory": {
      "type": "string",
      "description": "A directory where the feature is placed",
      "x-prompt": {
        "message": "Where would you like to put the feature library?",
        "type": "list",
        "items": [
          {
            "value": "dmx",
            "label": "Demo Web"
          }
        ]
      }
    },
    "prefix": {
      "type": "string",
      "format": "html-selector",
      "description": "The prefix to apply to generated selectors.",
      "default": "demo",
      "alias": "p",
      "x-prompt": "What prefix would you like to use for the feature library?"
    },
    "style": {
      "description": "The file extension to be used for style files.",
      "type": "string",
      "default": "scss",
      "x-prompt": {
        "message": "Which stylesheet format would you like to use?",
        "type": "list",
        "items": [
          {
            "value": "css",
            "label": "CSS"
          },
          {
            "value": "scss",
            "label": "SASS(.scss)  [ http://sass-lang.com   ]"
          },
          {
            "value": "styl",
            "label": "Stylus(.styl)[ http://stylus-lang.com ]"
          },
          {
            "value": "less",
            "label": "LESS         [ http://lesscss.org     ]"
          }
        ]
      }
    },
    "routing": {
      "type": "boolean",
      "default": true,
      "description": "Add router configuration. See lazy for more information.",
      "x-prompt": {
        "message": "Would you like to enable Routing?",
        "type": "list",
        "items": [
          {
            "value": true,
            "label": "True"
          },
          {
            "value": false,
            "label": "False"
          }
        ]
      }
    },
    "lazy": {
      "type": "boolean",
      "default": true,
      "description": "Add RouterModule.forChild when set to true, and a simple array of routes when set to false.",
      "x-prompt": {
        "message": "Would you like to enable Lazy Loading?",
        "type": "list",
        "items": [
          {
            "value": true,
            "label": "True"
          },
          {
            "value": false,
            "label": "False"
          }
        ]
      }
    },
    "parentModule": {
      "type": "string",
      "description": "Update the router configuration of the parent module using loadChildren or children, depending on what `lazy` is set to.",
      "x-prompt": "Specify path too parent moodule you would like to update router configuration",
      "default": "apps/demo-web/src/app/app.module.ts"
    },
    "tags": {
      "type": "string",
      "description": "Add tags to the library (used for linting)",
      "default": "scope:shared,type:feature"
    },
    "unitTestRunner": {
      "type": "string",
      "enum": ["karma", "jest", "none"],
      "description": "Test runner to use for unit tests",
      "default": "jest"
    }
  },
  "required": ["name", "directory"]
}
```
7. yarn workspace-schematic feature
Entered name as auth and left all defaults as is.

8. Opened auth.effects.ts in `/libs/dmx/auth/auth-data-acces/src/lib/+state/auth.effects.ts` an got error above.

### Context

  @nrwl/angular : 9.2.3
  @nrwl/cli : 9.2.3
  @nrwl/cypress : 9.2.3
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.2.3
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.3
  @nrwl/web : Not Found
  @nrwl/workspace : 9.2.3
  typescript : 3.8.3

[Demo Repo](https://github.com/joelmuskwe/nx-demo-suite)

**Comment by brandonroberts** [comment]
I would recommend using the data persistence operators for `fetch`, `navigate`, etc if you're using the new creators syntax with NgRx to get better type support.  This should be the default now for schematics.

**Comment by brandonroberts** [comment]
The docs have been updated to reflect this also. https://nx.dev/angular/guides/misc-data-persistence
