### ISSUE TITLE
Adding NX to existing NestJS project guide

### ISSUE THREAD

**Issue by ChristianBell1995** [nrwl/nx#28807]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Adding nx to an existing NestJS project
I have an existing NestJS project with ~5 applications and ~30-40 libs which are used across these applications. I was wondering if anyone has any experience adding nx to an existing project? 

I followed the guide here:
- https://nx.dev/recipes/adopting-nx/adding-to-existing-project
Which worked in as far as it cached the yarn commands when prefaced with `nx` however during the migration nx only identified one node in the dependency graph (the project as a whole) so any change to a file anywhere in the project will invalidate the cache. 

Using this library https://nx.dev/nx-api/nest I can create nest libs or applications which will show up in the dependency graph but can't see anywhere in the docs where you can run commands to add existing modules to the nx project.

Would be great if anyone has experience doing this so I know if it would be possible + how much time it would take! Thanks

**Comment by jasonbdt** [comment]
To generate NestJS Modules, Services etc. you have to use Generators that are provided by the @nx/nest Plugin.

Modules
`nx g @nx/nest:module apps/your-app/src/app/your-module`

Services
`nx g @nx/nest:service apps/your-app/src/app/your-service`

Did you mean this or do you need help migrating your existing Nest Project into nx workspace?

**Comment by ndcunningham** [comment]
Hi, thanks for filling out an issue.

I think you might be referring to https://nx.dev/getting-started/intro#try-nx-yourself to add nx to an existing project.
