### ISSUE TITLE
Nx prints "Nx is executing your tasks [...]" instead of printing the tasks' stdout in CI

### ISSUE THREAD

**Issue by floydnant** [nrwl/nx#28811]
### Current Behavior

When the repo is connected to nx cloud and the nx VSC Integration is installed in the repo, Nx prints "Nx is executing your tasks and will print a summary upon completion." instead of printing the tasks's stdout in GitHub Actions.

This results in poor UX as you have to click through several links to get to your CI's output, in the worst case even be blocked by a login form. I want to simply look at my workflow's output when a test fails and don't want to have to be redirected to another site (which doesn't even have a darkmode btw).

And this is especially unfortunate as GitHub usually annotates PR diffs with things like linter warnings and such, but you're taking away GitHub's ability to do so because the output is gatekept through nx.

### Expected Behavior

I was expecting at least a setting that lets me disable this behaviour and get back my precious stdout, but I was unable to find one.

Or the output is just printed as usual, like any other occasion where nx runs stuff w/o cloud hu-ha.

### Steps to Reproduce

1. Create GitHub repo w/ an nx workspace
2. Setup nx cloud and install nx's VSC integration on the repo
3. Add a workflow that produces output we want to see
4. Here it breaks, the output is replaced by a message saying "Nx is executing your tasks and will print a summary upon completion."

### Nx Report

No need for a report, this issue is conceptual.

### Operating System

- [ ] Linux
- [ ] Windows
- [ ] macOS
- [ ] Other (Please specify)

**Comment by StalkAltan** [comment]
You can disable this on your workspace settings: https://nx.dev/blog/improved-ci-log-with-nx-cloud#revert-to-the-old-behavior

**Comment by andersonba** [comment]
@StalkAltan Is it possible to disable this behavior for a single command execution? For example, I would like the full log when running the deploy target for the apps.
