### ISSUE TITLE
[question] clearing/pruning NX Cache

### ISSUE THREAD

**Issue by EvtK** [nrwl/nx#2883]
This is no issue, but a question. We are using the cache created in node_modules/.cache/NX in our CI environment. We distribute the NX cache between our agents. The size of the cache enlarges fast :). 

Is there a way to clear this cache, if possible by a certain depth?

I have searched the examples for distributed NX and the source code, but did not find this option. But maybe I have overlooked it :).

**Comment by Hotell** [comment]
> Is there a way to clear this cache
- you can move it outside node modules and `rm -rf` on it (ofc that can be done within node_modules)
![image](https://user-images.githubusercontent.com/1223799/79865754-f6ce1980-83db-11ea-9234-9344b0de9bdc.png)

> if possible by a certain depth
- I don't think so (@jaysoo  pls correct me if I'm wrong)

**Comment by FrozenPandaz** [comment]
[Nx Cloud](nx.app) is the best solution for distributing the cache for CI and local development as it stores the cache on a remote server.

Not sure what would classify as the depth of the cache. I think if you were caching this in CI, you would likely want to do it per PR... so that it clears.

Hopefully, that answers the question.

**Comment by hadrien-toma** [comment]
"The best solution" is always relative to a point of view. For me the best solution has to be open source for instance. So having a way to clear the cache locally, specifying for instance "only the cache of Cypress" would be useful.

**Comment by chrisui** [comment]
Would be really great to see a way to prune a local cache during a run so that we can avoid the explosion of caching artifacts containing old entries. Effectively would be nice to have a LRU implementation to control the disk cache size otherwise it will grow to infinity and the only way you can avoid that is to completely nuke the cache which is unfortunate.

**Comment by mathpaquette** [comment]
any updates?

**Comment by jonhamm** [comment]
> [Nx Cloud](nx.app) is the best solution for distributing the cache for CI and local development as it stores the cache on a remote server.
> 
> Not sure what would classify as the depth of the cache. I think if you were caching this in CI, you would likely want to do it per PR... so that it clears.
> 
> Hopefully, that answers the question.

I have setup NxCloud in or build pipeline and it works fine
Developers can draw from that cache too but they cannot write to NxCloud0

_BUT_ as a developer I use a lot of git worktrees for different branches and I want to share caching among these branches, so I have setup a `NX_CACHE_DIRECTORY=~/.nxcache` - so this does not clear.

Nx does not seem to cleanup this cache ?? Should it not be pruned to have only 14 days old artefacts ??
If this is not doable a command `nx prune-cache --days=14` or similar would be much appreciated.

**Comment by ianldgs** [comment]
My current solution:
`find $NX_CACHE_DIRECTORY -maxdepth 1 -mtime +7 -exec rm -rf '{}' \;`

**Comment by SethDavenport** [comment]
I'm persisting the .nx cache to my github actions cache. Yes, I could use cloud, but I would have to go through a big internal vendor approval process, get budget, etc. I'll probably do it eventually but for now a pattern where

* main runs saves .nx-cache to github action's cache, using the current commit sha as the cache ID
* PRs load the version of the github cache from the github sha matching `NX_BASE`

It's working pretty great so far. However I have noticed that the cache does grow monotonically over time. So yeah I will probably adjust my github actions workflow to have `main` nuke it every few days.

**Comment by ianldgs** [comment]
yeah, when I'm updating something on ci/build that requires re-building a lot of times the cache on gitlab can take longer to download than to actually compile everything.
we definitely need a nicer way to clean up stale cache. cleaning up for x days ago doesn't work for when you invalidate cache multiple times with new chages.

**Comment by SethDavenport** [comment]
Ended up doing this:

```bash
#! /usr/bin/env bash
set -e

# This script accepts as an argument a number of megabytes. It will then
# delete files in the current folder, oldest first, until the overall size
# of the folder's contents is beneath that number of megabytes.
#
# We use this for pruning caches in CI.

maxSizeKB=$(($1*1024)) # in MB

# Sort files by modification time, oldest first
taskHashes=($(ls -tr .nx-cache | grep -v -E "(\.commit|^d|^terminalOutputs|nxdeps.json)$"))

# Calculate current total size
totalSize=0
for hash in "${taskHashes[@]}"; do
  totalSize=$((totalSize + $(du -sk ".nx-cache/$hash" | cut -f 1)))
  totalSize=$((totalSize + $(du -sk ".nx-cache/$hash.commit" | cut -f 1)))
  totalSize=$((totalSize + $(du -sk ".nx-cache/terminalOutputs/$hash" | cut -f 1)))
done

echo "Starting total size: $totalSize, requested max size: $maxSizeKB KB"

# Delete oldest files until the total size is below the threshold
i=0
while [ "$totalSize" -gt "$maxSizeKB" ]; do
  hash=${taskHashes[$i]}
  totalSize=$((totalSize - $(du -sk ".nx-cache/$hash" | cut -f 1)))
  totalSize=$((totalSize - $(du -sk ".nx-cache/$hash.commit" | cut -f 1)))
  totalSize=$((totalSize - $(du -sk ".nx-cache/terminalOutputs/$hash" | cut -f 1)))

  echo "Deleting files associated with hash $hash; totalSize is now $totalSize"
  rm -rf ".nx-cache/$hash"
  rm -rf ".nx-cache/$hash.commit"
  rm -rf ".nx-cache/terminalOutputs/$hash"
  i=$i+1
done

echo "Finished total size: $totalSize"
```
