### ISSUE TITLE
[Bug] NPM registry is not read from .npmrc when using NX Release API

### ISSUE THREAD

**Issue by roman-supy-io** [nrwl/nx#28843]
### Current Behavior

I'm using NX release programmatic approach with a custom registry
The issue is when running the custom release script, the custom registry is not resolved/read from the `.npmrc`.

**System:**
- MacOS Sequoia 15.0.1
- Macbook M1 Pro
- NPM - 10.8.2
- Node - 22.0.6

Code:
`.npmrc`:
```sh
registry=https://registry.npmjs.org/
@company:registry=https://custom.registry/
//custom.registry/:always-auth=true
//custom.registry/:_auth=<redacted>
```

`release.ts`:
```ts
import { releasePublish } from 'nx/release';
...
await releasePublish({
    dryRun: options.dryRun,
    verbose: options.verbose,
    firstRelease: options.firstRelease,
    registry: options.registry, // if not passed, returns 403 and tries to publish to https://registry.npmjs.org instead of https://custom.registry
    tag: options.preid ?? 'latest',
  });
```

Worth noting that ALL packages within the workspace are under `@company/***` npm scope (`name` property in `package.json`)

### Expected Behavior

Release can read the existing `.npmrc` and publish to the target registry without specifying `--registry` flag manually

### Steps to Reproduce

1. Generate a new NX workspace
2. Add one or two projects with --importPath @company/***
3. Use custom registry/verdaccio and configure the `.npmrc` respectively
4. Build and bump the package in the output folder (e.g. `dist/libs/...`)
5. Run the release-publish step as in code example above

### Nx Report

Node           : 22.6.0
OS             : darwin-x64
Native Target  : x86_64-macos
npm            : 10.8.2

nx (global)        : 20.0.0
nx                 : 20.0.6
@nx/js             : 20.0.6
@nx/jest           : 20.0.6
@nx/eslint         : 20.0.6
@nx/workspace      : 20.0.6
@nx/devkit         : 20.0.6
@nx/eslint-plugin  : 20.0.6
@nx/nest           : 20.0.6
@nx/node           : 20.0.6
@nx/plugin         : 20.0.6
nx-cloud           : 19.1.0
typescript         : 5.5.4

### Failure Logs

> nx run commitlint-config:nx-release-publish

Debugger attached.
npm publish error:
This command requires you to be logged in to https://registry.npmjs.org/
You need to authorize this machine using `npm adduser`
Waiting for the debugger to disconnect...

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JamesHenry** [comment]
@roman-supy-io I cannot reproduce, please modify this repo to provide a reproduction:

https://github.com/JamesHenry/issue-28843

In its current state (created based on the information provided) both `nx release publish` and `releasePublish()` match each other and seem to be behaving as expected by selecting `https://custom.registry/` as the registry to target (which can only have come from the workspace `.npmrc` file):

![Image](https://github.com/user-attachments/assets/b7844933-eac2-46e1-ab43-940defae749d)

![Image](https://github.com/user-attachments/assets/75441b87-20e2-4c6c-93ea-99c21cee4933)
