### ISSUE TITLE
node:build doing type check before file replacement

### ISSUE THREAD

**Issue by arjunyel** [nrwl/nx#2887]
## Expected Behavior

Building a node app with --configuration=production should work even if theres a type issue in enviroment.ts since that build should be using enviroment.prod.ts.

## Current Behavior

Building a node app in our CI (using --configuration=production) is failing because theres an (expected) typescript error in enviroment.ts, however in the angular.json fileReplacements the build config should be using enviroment.prod.ts. Therefore an error in enviroment.ts shouldn't break the build because that file shouldn't be used. This works correctly when building an Angular app.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. npx create-nx-workspace@latest
2. Use the Angular + nestjs template and name the app todo
3. `npx nx build todo --configuration=production` works
4. In `apps/todo/src/environments/environment.ts` add `import {} from './test';` to the top. Importing a file that doesnt exist is a TS error.
5. `npx nx build todo --configuration=production` still works however
6. `npx nx build api --configuration=production` works
7. In `apps/api/src/environments/environment.ts` add `import {} from './test';` to the top
8. `npx nx build todo --configuration=production` the build now fails

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context

Please provide any relevant information about your setup:

```
@nrwl/angular : 9.2.3
@nrwl/cli : 9.2.3
@nrwl/cypress : 9.2.3
@nrwl/eslint-plugin-nx : Not Found
@nrwl/express : Not Found
@nrwl/jest : 9.2.3
@nrwl/linter : 9.2.3
@nrwl/nest : 9.2.3
@nrwl/next : Not Found
@nrwl/node : 9.2.3
@nrwl/react : Not Found
@nrwl/schematics : Not Found
@nrwl/tao : 9.2.3
@nrwl/web : Not Found
@nrwl/workspace : 9.2.3
typescript : 3.8.3
```

### Failure Logs

```
npx nx build api --configuration=production

> ng run api:build:production 
Starting type checking service...
Using 14 workers with 2048MB memory limit
Hash: 15583b0ec94f30a2afdd
Built at: 04/21/2020 8:30:44 PM
Entrypoint main = main.js main.js.map
chunk    {0} main.js, main.js.map (main) 2.32 KiB [entry] [rendered]

ERROR in /Users/test/work/todo/apps/api/src/environments/environment.ts
ERROR in /Users/test/work/todo/apps/api/src/environments/environment.ts(1,16):
TS2307: Cannot find module './test'.
```

**Comment by FrozenPandaz** [comment]
In the `tsconfig.app.json` you can change `include` to:

```
  "include": ["src/main.ts"]
```

This is a good first issue. I think we can not write a migration to change this for existing applications because it would be a breaking change to change `**/*.ts` to `src/main.ts` and it's not entirely necessary since those apps will still work without making the change.

**Comment by Hotell** [comment]
if it's an expected error I suggest to use `@ts-ignore` or `@ts-expect-error` pragma to that particular line and leave builder  implementation as is.
