### ISSUE TITLE
Invalid character check for generator

### ISSUE THREAD

**Issue by PepijnSenders** [nrwl/nx#2888]
## Expected Behavior

For NX to throw an error when using invalid characters.

## Current Behavior

<img width="768" alt="Screen Shot 2020-04-21 at 9 56 36 PM" src="https://user-images.githubusercontent.com/2052659/79932265-1b95b180-841b-11ea-8b95-ae30188dc331.png">

**Comment by FrozenPandaz** [comment]
This was fixed with #3396 Starting with `@` and other non-alphabetical characters is no longer valid.
