### ISSUE TITLE
How add to @nrwl/storybook fonts or assets?

### ISSUE THREAD

**Issue by victorward** [nrwl/nx#2895]
How add to library with @nrwl/storybook fonts or assets?

## Expected Behavior

The `file-loader` inside `webpack.config` should load files with fonts or property `assets` for `@nrwl/storybook:storybook` should be added

## Current Behavior

Configuration for @nrwl/storybook doesn't allows me to provide any assets property, also when I provide file-loader inside webpack.config it just omit it..

### Context

Webpack file-loader: 

```javascript
    {
      test: /\.(woff|woff2)$/,
      use: [
        {
          loader: 'file-loader',
          options: {
            outputPath: (url, resourcePath, context) => {
              console.log('url', url);
              console.log('resourcePath', resourcePath);
              console.log('context', context);
              // Anything printed; in 'Sources -> webpack' is also missed
              return `assets/${url}`;
            },
          }
        }
      ],
      include: path.resolve(__dirname, '../src/assets/')
    }
```

Font use inside scss file:
```javascript
@font-face {
  font-family: 'FontName';
  // src: url('^assets/fonts/FontName.woff2') format('woff2'), url('^assets/fonts/FontName.woff') format('woff'); // <-- The same
  src: url('/assets/fonts/FontName.woff2') format('woff2'), url('/assets/fonts/FontName.woff') format('woff');
  font-weight: $font-weight-regular;
}
```

 NX  Report
> @nrwl/angular : 9.0.2
  @nrwl/cli : 9.0.2
  @nrwl/cypress : 9.0.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.0.2
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.0.2
  @nrwl/web : Not Found
  @nrwl/workspace : 9.0.2
  typescript : 3.7.5

angular.json

```javascript
"storybook": {
          "builder": "@nrwl/storybook:storybook",
          "options": {
            "uiFramework": "@storybook/angular",
            "port": 4400,
            "config": {
              "configFolder": "libs/shared/library-name/.storybook"
            }
          },
          "configurations": {
            "ci": {
              "quiet": true
            }
          }
        },
```

**Comment by twittwer** [comment]
I don't know if I get you right. If the problem is the definition of required assets you can have a look at the `preview-head.html` - https://storybook.js.org/docs/configurations/add-custom-head-tags/

**Comment by victorward** [comment]
Thanks for response. 
`Unfortunately it's doesn't work either.`
Basically what I want to achieve is to load fonts and than declare them using @font-face.
But I don't know how to do it, as described in issue webpack loader seems to not work

**Comment by Chartieer** [comment]
This works

```json
"storybook": {
          "builder": "@nrwl/storybook:storybook",
          "options": {
            "uiFramework": "@storybook/react",
            "port": 4400,
            "staticDir": ["public"],
            "config": {
              "configFolder": "libs/*_ya-lib_*/.storybook"
            }
          },…
```

**Comment by antoniojps** [comment]
@Chartieer The [staticDir](https://nx.dev/latest/react/storybook/executors/storybook#staticdir) worked with the path related to the workspace directory, here's my settings:

```
"storybook": {
  "executor": "@nrwl/storybook:storybook",
  "options": {
    "uiFramework": "@storybook/react",
    "port": 4400,
    "staticDir": ["libs/ytrank-components/public"],
    "config": { "configFolder": "libs/ytrank-components/.storybook" }
  },
  "configurations": { "ci": { "quiet": true } }
}
```

**Comment by always-maap** [comment]
This also worked for me. all fonts and assets in `.storybook` to share between all storybook apps
```
"storybook": {
  "executor": "@nrwl/storybook:storybook",
  "options": {
    "uiFramework": "@storybook/react",
    "port": 4400,
    "config": { "configFolder": "libs/admin-ui/.storybook" },
    "staticDir": [".storybook/public"]
  },
  "configurations": { "ci": { "quiet": true } }
},
```

**Comment by frontr-uk** [comment]
@Chartieer you are a star!
