### ISSUE TITLE
Build failures do not include errors messages when running on CI

### ISSUE THREAD

**Issue by paustint** [nrwl/nx#28979]
### Current Behavior

When a task runs in CI, the actual error messages are no longer printed out and I am forced to go look to nx cloud to see the error messages.

The same command locally shows the errors above the pretty table

![Image](https://github.com/user-attachments/assets/78f53d24-542f-4bcc-8307-c6f33a1b1045)

### Expected Behavior

As stated in the documentation, errors should always be shown regardless of the environment by default.

### Steps to Reproduce

1. run tasks on CI that fail (e.g. build command)
2. notice output on CI does not show error messages

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.14.0
OS             : darwin-arm64
Native Target  : aarch64-macos
yarn           : 1.22.22

nx                 : 20.1.2
@nx/js             : 20.1.2
@nx/jest           : 20.1.2
@nx/eslint         : 20.1.2
@nx/workspace      : 20.1.2
@nx/devkit         : 20.1.2
@nx/esbuild        : 20.1.2
@nx/eslint-plugin  : 20.1.2
@nx/node           : 20.1.2
@nx/playwright     : 20.1.2
@nx/react          : 20.1.2
@nx/vite           : 20.1.2
@nx/web            : 20.1.2
@nx/webpack        : 20.1.2
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
```

### Failure Logs

```shell
I only where there were failure logs.... we only get a pretty summary table without any detail
```

### Package Manager Version

yarn 1.22.22

### Operating System

- [x] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by StalkAltan** [comment]
Hi @paustint, you can disable this on your workspace settings: https://nx.dev/blog/improved-ci-log-with-nx-cloud#revert-to-the-old-behavior.

**Comment by paustint** [comment]
OK.... I really don't like that settings in nx cloud leak into external tools (bitbucket in my case)
I can see where settings in nx cloud control nx cloud output, but odd that it controls all ci environments - I don't want to have to go to nx cloud to see what test caused a failure.
