### ISSUE TITLE
Can't generate modules with ng g module...

### ISSUE THREAD

**Issue by Yonet** [nrwl/nx#29]
In newly generated ngrx app ng g module doesn't work. ng g component/service/... works fine.

ng generate ngrx app —module=apps/debug/src/app/app.module.ts —root 
ng g module apps/debug/src/myFeatureModule

**Comment by jschwarty** [comment]
I am not able to get any of the angular/schematics to run in a Nx Workspace. It seems like there is only one schematics collection available and that is the nx one.

**Comment by jschwarty** [comment]
I got some answers on this. Will make a PR for it.
