### ISSUE TITLE
The @nrwl/storybook custom webpack configuration loaders don't load files without direct file use 

### ISSUE THREAD

**Issue by victorward** [nrwl/nx#2901]
The` @nrwl/storybook` custom webpack configuration loaders don't load files without direct file use in` .ts` file

## Expected Behavior

After defining any loader like this:
```javascript
  config.module.rules.push({
    test: /\.scss$/,
    use: ['style-loader', 'css-loader', 'sass-loader'],
    include: path.resolve(__dirname, '../src/assets/scss'),
  });
```
or like this: 
```javascript
  config.module.rules.push({
    test: /\.svg$/,
    loader: 'file-loader',
    options: {
      outputPath: 'assets/icons',
    },
    include: path.resolve(__dirname, '../src/assets/icons'),
  });
```
I except that webpack will load all files which meet the pattern

## Current Behavior

Webpack will not load any file if it will be not used inside some component code. For example, if you add reference inside `@Component` declaration to `styleUrls: ['./XYZ.component.scss']` it will work fine, but without use, it just omits these files.

It makes sense for reducing the final bundle file size, but it will also force me to add an inline import to `config.js` to load some global styles. The real problem starts when I need to load a lot of SVG icons using HTML SVG tag:
```html
<svg><use [attr.href]="'assets/icons/' + spriteManifest + '#icon-' + name"></use></svg>
// OR
<svg><use [attr.href]="'../../assets/icons/' + spriteManifest + '#icon-' + name"></use></svg>
```
These ways of loading don't work. Adding aliases to webpack configuration do not work either.

Maybe there exists some way of adding `assets` array for a storybook library inside `angular.json` (like for angular apps)?
### Context

> @nrwl/angular : 9.2.2
  @nrwl/cli : 9.2.2
  @nrwl/cypress : 9.2.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.2.2
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.2
  @nrwl/web : Not Found
  @nrwl/workspace : 9.2.2
  typescript : 3.8.3

**Comment by victorward** [comment]
Some time ago I found a workaround:
You need to define _asstets_ in `angular.json` for your `"defaultProject"` build configuration.  For me, this is strange and not obvious that I need to define this configuration inside default angular project when I created a library which is independent of this application

**Comment by juristr** [comment]
@victorward I think this open PR https://github.com/nrwl/nx/pull/2926 could fix the issue for you, right?

**Comment by victorward** [comment]
> @victorward I think this open PR #2926 could fix the issue for you, right?

yes, it can resolve, I will check after merging

**Comment by juristr** [comment]
@victorward awesome thx. I'm closing this for now then. Thanks again for your feedback
