### ISSUE TITLE
React / rspack - HMR constantly fail

### ISSUE THREAD

**Issue by seb-mynotary** [nrwl/nx#29041]
### Current Behavior

HMR do not work after file modification

### Expected Behavior

Hmr shouldn't throw error after modification

### Steps to Reproduce

1. `git clone https://github.com/seb-mynotary/nx-rspack.git`
2. `nx run demo:serve`
3. update main.tsx
4. look at the console to see the error

### Nx Report

```shell
Node           : 20.10.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.4.0

nx (global)        : 20.0.6
nx                 : 20.1.2
@nx/js             : 20.1.2
@nx/eslint         : 20.1.2
@nx/workspace      : 20.1.2
@nx/eslint-plugin  : 20.1.2
@nx/react          : 20.1.2
@nx/rspack         : 20.1.2
@nx/vite           : 20.1.2
@nx/web            : 20.1.2
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
```

### Failure Logs

```shell

```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Fixed by #28825
