### ISSUE TITLE
bug: @nrlw/workspace:move - implicit dependencies tokens are not renamed

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#2906]
## Expected Behavior

update `implicitDependencies` token references, when executing `move` schematic

## Current Behavior

when running `move` schematic, nx.json `implicitDependencies` are not updated (if moved lib is referenced there)

**nx.json**

```jsonc
{
"projects": {
    "one": {
      "tags": [],
      // 🚨THIS WONT BE RENAMED
      "implicitDependencies": ["two"]
    },
    "two": {
      "tags": []
    }
  }
}
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. npx create-nx-workspace@latest repro-workspace
2. nx g @nrwl/workspace:lib one
3. nx g @nrwl/workspace:lib two
4. update nx.json -> 
```
    "one": {
      "tags": [],
       "implicitDependencies": ["two"]
    },
```
5.  nx g @nrwl/workspace:move --projectName=two --destination=nested/two
6. check nx.json
```
    "one": {
      "tags": [],
      // 🚨THIS SHOULD BE nested-two
       "implicitDependencies": ["two"]
    },
```

### Context

```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : Not Found
  @nrwl/cli : 9.2.2
  @nrwl/cypress : 9.2.2
  @nrwl/eslint-plugin-nx : 9.2.2
  @nrwl/express : Not Found
  @nrwl/jest : 9.2.2
  @nrwl/linter : 9.2.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.2.2
  @nrwl/react : 9.2.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.2
  @nrwl/web : 9.2.2
  @nrwl/workspace : 9.2.2
  typescript : 3.8.3
```

**Comment by FrozenPandaz** [comment]
Good point, this may be easy enough for the community to tackle.
