### ISSUE TITLE
Weird Behavior in NestJS Generators

### ISSUE THREAD

**Issue by bzp2010** [nrwl/nx#29076]
### Current Behavior

The NestJS generator is used in a way that doesn't match the documentation and is very different from previous releases.

According to my #28910 (Additional Information), and another reporter's checks (https://github.com/nrwl/nx/issues/28910#issuecomment-2473716712), this does exist.

@pawel-twardziak also proves (https://github.com/nrwl/nx/issues/28910#issuecomment-2484269010) that these generators are not quite normal, at least, it doesn't match the documentation. It also doesn't work as well as the previous implementation in Nx 19. As mentioned there, I'd better create a new issue to keep track.

In detail: #28910
---

I would kindly ask you to indicate the correct way to use the nestjs generator, as it is very different from the way I used it during nx 16-19.
I know we've switched to the default as-provided, but it also looks like the nestjs generator doesn't support directory but uses path instead.

I've read https://nx.dev/deprecated/as-provided-vs-derived#generate-paths-and-names-asprovided, but it doesn't look like that's what actually works, which I don't understand.

For example, when I try to generate code for a project in the root directory, I use the --path option and the files are generated in the wrong path.
```
➜  my-workspace git:(main) ✗ nx g @nx/nest:guard --name auth --path apps/my-workspace/src/app

 NX  Generating @nx/nest:guard

CREATE apps/my-workspace/src/apps/my-workspace/src/app/app.guard.spec.ts
CREATE apps/my-workspace/src/apps/my-workspace/src/app/app.guard.ts
```
It is duplicated in the `apps/my-workspace/src` section and I have to move it manually which I think might be wrong, it should be able to work correctly, in the past I used `--directory` to deal with the problem directly, but now it seems that it no longer exists.

I saw that section included in `--path` and maybe it was the cause of the error, so I went into that folder and generated it again.

```
➜  my-workspace git:(main) ✗ cd apps/my-workspace/src 
➜  src git:(main) ✗ nx g @nx/nest:guard --name auth --path app                      

 NX  Generating @nx/nest:guard

CREATE apps/my-workspace/src/app/app.guard.spec.ts
CREATE apps/my-workspace/src/app/app.guard.ts
```

Now, the generated path is correct, but again, I noticed that the generated file names `app.guard.ts` and classes `AppGuard` in them do not follow the input value `auth`, but appear to be automatically inferred from the path `app`. It's not just guard, but other nestjs code generators have similar problems, such as controllers and filters.

If I want to make sure the filename is correct, I have to make sure that the last part of the path in `--path` is the filename prefix I want. Just like:
```
nx g @nx/nest:guard --name auth --path app/auth
nx g @nx/nest:guard --name auth --path auth
```

But unfortunately the two methods above fall back into the cycle of problems about paths mentioned above.

```
➜  src git:(main) ✗ nx g @nx/nest:guard --name auth --path app/auth

 NX  Generating @nx/nest:guard

CREATE apps/my-workspace/src/app/app/auth/auth.guard.spec.ts
CREATE apps/my-workspace/src/app/app/auth/auth.guard.ts

➜  src git:(main) ✗ nx g @nx/nest:guard --name auth --path auth    

 NX  Generating @nx/nest:guard

CREATE apps/my-workspace/src/auth/auth.guard.spec.ts
CREATE apps/my-workspace/src/auth/auth.guard.ts
```

It looks like I have to enter the `app` directory to generate the file at `auth/auth.guard.ts`.

This breaks the intuition of the previous generator's use of `--directory`, and `--path` forces me to infer where I should be generating files and return the up-level directory in that location.

Also, I don't want to place the generated files inside a directory, well, at least not every time, e.g. I want to generate `auth.guard.ts` instead of `auth/auth.guard.ts`, which, if memory serves me correctly, was the behavior when I used --directory before.

### Expected Behavior

It is desirable that these generators continue to support the `--directory` option that was supported in Nx19 and earlier, which is the most intuitive to use. The current `--path` option is extremely unintuitive.

```
nx --version

Nx Version:
- Local: v19.3.0
- Global: v20.1.0
```

Back then, I used commands like:

```
nx g @nx/nest:guard --name auth --directory apps/[hidden]/src/app/config

 NX  Generating @nx/nest:guard

? Where should the guard be generated? … 
▸ As provided: apps/[hidden]/src/app/config/auth.ts
  Derived:     apps/[hidden]/src/apps/[hidden]/src/app/config/auth.ts
```

Of course, I'm using the As-provided pattern, so it generates:

```
CREATE apps/[hidden]/src/app/config/auth.guard.spec.ts
CREATE apps/[hidden]/src/app/config/auth.guard.ts
```

No misplaced paths, no duplicate paths, no weird nested folders, everything is fine.
This is exactly what I expected, nothing that forces me to have to guess and infer paths, and the generated files are not nested by their folder prefixes. The files are generated in exactly the folder I specify, which is fairly intuitive.

### Steps to Reproduce

1. Using the nestjs generator in Nx20, try to generate a Guard (including, but not limited to, a Guard, which behaves like a Controller or Service).
2. As I mentioned above, the Nx 19 is very intuitive and easy to use, of course, it works fine.

### Nx Report

```shell
Node           : 20.13.1
OS             : linux-x64
Native Target  : x86_64-linux
npm            : 10.5.2

nx (global)        : 20.1.0
nx                 : 20.1.0
@nx/js             : 20.1.0
@nx/jest           : 20.1.0
@nx/eslint         : 20.1.0
@nx/workspace      : 20.1.0
@nx/eslint-plugin  : 20.1.0
@nx/nest           : 20.1.0
@nx/node           : 20.1.0
@nx/web            : 20.1.0
@nx/webpack        : 20.1.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

### Failure Logs

```shell

```

### Package Manager Version

pnpm 9.14.1

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

This issue is derived from another issue #28910. I've transferred as much of the relevant background and errors as I can here, and if not here, there may be more information there. If information is still missing, I will add it.

**Comment by pawel-twardziak** [comment]
thanks @bzp2010 for following up and reporting that issue. Will work on it, something should get clarified within ~1 week.

**Comment by pawel-twardziak** [comment]
thanks @bzp2010 for following up and reporting that issue. Will work on it, something should get clarified within ~1 week.

**Comment by pawel-twardziak** [comment]
there is a bug on Github :D it doubles comments 😆

**Comment by ndcunningham** [comment]
Hi, You are correct.
When we transitioned to use `--path` instead of `--project` it created this issue.

It will be fixed stay tuned for the PR, thanks for reporting!

**Comment by bzp2010** [comment]
I have started using Nx 20.1.4 and now these generators are working fine. I've noticed that `name` is no longer used and instead `path` is used to infer the file name and class name prefix, which I used on Nx 19.

Anyway, it works fine now.
