### ISSUE TITLE
Question - Excluding dependencies between libs

### ISSUE THREAD

**Issue by danzrou** [nrwl/nx#2917]
- I have a lib which includes cypress utilities for tests.
- I have an additional UI lib which uses storybook.
  - In the stories, I use a module from the tests library

When Nx analyses the dependencies, it sets the tests library as dependency for the UI library.
However, its used only in the stories which are excluded from the library's build.

Is there a way to explicitly ignore the stories in the dependency construction?

**Comment by brandonroberts** [comment]
Add an `.nxignore` file at the root of your workspace, and include your matches to be excluded from the dependency resolution.
