### ISSUE TITLE
Discrepancy Between Rollup Config dist Output Path and package.json dist Usage in Nx 20.2.0-beta.6

### ISSUE THREAD

**Issue by ashkanhosseini** [nrwl/nx#29195]
### Current Behavior

In Nx, when generating a new package using `@nx/react` with Rollup as the bundler, there is a discrepancy between the `dist` folder location defined in the generated `rollup.config.js` and the `dist` folder referenced in `package.json`.

- The `rollup.config.js` places the build output in the root-level `dist` folder (`outputPath: 'dist/packages/package-1'`).
- However, the `package.json` at the package level points to `dist` in the package folder (`"main": "./dist/index.js"`), which causes inconsistency in the build output location.

This discrepancy leads to confusion and can break build and publish processes.

### Expected Behavior

The generated `rollup.config.js` and the `package.json` should be consistent in terms of the `dist` folder location.

- The `rollup.config.js` should place the build output in the same `dist` folder path as specified in the `package.json`.
- For example, if the `package.json` references `"main": "./dist/index.js"` inside the package folder, the `rollup.config.js` should also output to that same folder (`packages/package-1/dist`), or vice versa.
- Alternatively, the `dist` folder should be configurable and automatically aligned in both configurations (e.g., through a common setting in `nx.json` or `project.json`).

It's also worth mentioning that baseUrl is missing from this setup but I've added it to tsconfigconfig.base.json

### GitHub Repo

https://github.com/ashkanhosseini/nx-next-release/pull/2/files

### Steps to Reproduce

You can check [this repo ](https://github.com/ashkanhosseini/nx-next-release/pull/2/files) to reproduce the bug, make sure to checkout `rollup-config-discrepancy-with-package-json` branch

Here are the steps I took to reproduce:
1. generate package-1 using `npx nx g @nx/react:library packages/package-1 --bundler=rollup --publishable --importPath=@myorg/package-1 --verbose`
2. generate package-1 using `npx nx g @nx/react:library packages/package-2 --bundler=rollup --publishable --importPath=@myorg/package-2 --verbose`
3. rename all the generated rollup.config.js files to *.cjs and the same for the eslint.config.js files. Refer to [this](https://github.com/nrwl/nx/issues/29193) bug report for more info
4. import package-1 in `packages/package-2/src/lib/package-2.tsx` to add a dependency
5. update dependencies of the package-2 to add dependency to package-1 as `"@myorg/package-1": "workspace:*"`
6. `run npx nx sync`
7. try to build package-2 by running `npx nx build package-2 --verbose` and you will see the following error: ```
[!] (plugin rpt2) RollupError: [plugin rpt2] src/lib/package-2.tsx:1:26 - error TS2307: Cannot find module '@myorg/package-1' or its corresponding type declarations.

1 import { Package1 } from '@myorg/package-1';
                           ~~~~~~~~~~~~~~~~~~

src/index.ts

    at getRollupError (/Users/ashkanhosseini/projects/nx-next-release/node_modules/rollup/dist/shared/parseAst.js:285:41)
    at Object.error (/Users/ashkanhosseini/projects/nx-next-release/node_modules/rollup/dist/shared/parseAst.js:281:42)
    at Object.error (/Users/ashkanhosseini/projects/nx-next-release/node_modules/rollup/dist/shared/rollup.js:902:32)
    at RollupContext.error (/Users/ashkanhosseini/projects/nx-next-release/node_modules/rollup-plugin-typescript2/src/context.ts:35:17)
    at /Users/ashkanhosseini/projects/nx-next-release/node_modules/rollup-plugin-typescript2/src/diagnostics.ts:70:17
    at Array.forEach (<anonymous>)
    at printDiagnostics (/Users/ashkanhosseini/projects/nx-next-release/node_modules/rollup-plugin-typescript2/src/diagnostics.ts:42:14)
    at typecheckFile (/Users/ashkanhosseini/projects/nx-next-release/node_modules/rollup-plugin-typescript2/src/index.ts:67:3)
    at Object.<anonymous> (/Users/ashkanhosseini/projects/nx-next-release/node_modules/rollup-plugin-typescript2/src/index.ts:269:5)
    at Generator.next (<anonymous>)
    at /Users/ashkanhosseini/projects/nx-next-release/node_modules/rollup-plugin-typescript2/node_modules/tslib/tslib.es6.mjs:121:69
    at new Promise (<anonymous>)
    at __awaiter (/Users/ashkanhosseini/projects/nx-next-release/node_modules/rollup-plugin-typescript2/node_modules/tslib/tslib.es6.mjs:117:10)
    at Object.transform (/Users/ashkanhosseini/projects/nx-next-release/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:28099:20)
    at /Users/ashkanhosseini/projects/nx-next-release/node_modules/rollup/dist/shared/rollup.js:1087:40


Warning: command "rollup -c rollup.config.cjs" exited with non-zero status code
—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Running target build for project package-2 and 1 task it depends on failed

Failed tasks:

- package-2:build

Hint: run the command with --verbose for more details.
```


### Nx Report

```shell
npx nx report

 NX   Report complete - copy this into the issue template

Node           : 22.11.0
OS             : darwin-arm64
Native Target  : aarch64-macos
yarn           : 1.22.22

nx                 : 20.2.0-beta.6
@nx/js             : 20.2.0-beta.6
@nx/jest           : 20.2.0-beta.6
@nx/eslint         : 20.2.0-beta.6
@nx/workspace      : 20.2.0-beta.6
@nx/devkit         : 20.2.0-beta.6
@nx/eslint-plugin  : 20.2.0-beta.6
@nx/react          : 20.2.0-beta.6
@nx/rollup         : 20.2.0-beta.6
@nx/web            : 20.2.0-beta.6
typescript         : 5.6.3
---------------------------------------
Registered Plugins:
@nx/js/typescript
@nx/eslint/plugin
@nx/rollup/plugin
@nx/jest/plugin
```

### Failure Logs

```shell

```

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by leosvelperez** [comment]
This was fixed by https://github.com/nrwl/nx/pull/29196.
