### ISSUE TITLE
@nx/angular@20.1.4 not supporting Angular 19

### ISSUE THREAD

**Issue by BenRacicot** [nrwl/nx#29216]
### Current Behavior

Looks like Nx is supporting Angular 19 in other packages but not `@nx/angular@20.1.4`?

npm error Could not resolve dependency:
npm error peer @angular-devkit/build-angular@">= 16.0.0 < 19.0.0" from @nx/angular@20.1.4
npm error node_modules/@nx/angular
npm error   @nx/angular@"^20.1.4" from the root project

Is this support coming?

### Expected Behavior

Latest Nx versions support current Angular releases.

### Steps to Reproduce

1.

### Nx Report

```shell
npm i
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: recruitler@1.0.0
npm error Found: @angular-devkit/build-angular@19.0.3
npm error node_modules/@angular-devkit/build-angular
npm error   dev @angular-devkit/build-angular@"19.0.3" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @angular-devkit/build-angular@">= 16.0.0 < 19.0.0" from @nx/angular@20.1.4
npm error node_modules/@nx/angular
npm error   @nx/angular@"^20.1.4" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/home/.npm/_logs/2024-12-05T13_10_32_672Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/home/.npm/_logs/2024-12-05T13_10_32_672Z-debug-0.log
```

### Failure Logs

```shell

```

### Package Manager Version

npm 10.8.3

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Angular 19 is not yet supported (https://nx.dev/nx-api/angular/documents/angular-nx-version-matrix#nx-and-angular-version-compatibility-matrix). It will be supported in Nx v20.2.0.

**Comment by guoliang** [comment]
@leosvelperez 
Hi, I'm new to NX and have a question. When version 20.2.0 is released, how can I upgrade an existing Angular 18 project to Angular 19?
