### ISSUE TITLE
@nrwl/react:app/lib and @nrwl/express:app/lib should fail if name isn't supplied

### ISSUE THREAD

**Issue by jdpearce** [nrwl/nx#2924]
From here: https://github.com/nrwl/nx/issues/333#issuecomment-619063256

Both `nx g @nrwl/express:app/lib` and `nx g @nrwl/react:app/lib` create files in the root of `/apps`/`/libs` if the user does not provide an application name.

These schematics should fail with an error if the name is empty.

This should be a matter of either validating the options/schema before running any of the following rules, or possibly just adding a regex which will fail if the input is empty (note that libs starting with numbers would also be invalid, so something like `^[a-zA-Z]{1}.*$` might suffice.

**Comment by cristianmartinez** [comment]
Is someone working on this? @jdpearce can I take it?
