### ISSUE TITLE
Extending from @nestjs/schematics fails @nrwl/nest init & other schematics

### ISSUE THREAD

**Issue by juristr** [nrwl/nx#2925]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Adding `@nrwl/nest` and then executing `@nrwl/nest:init` (or any other schematic) should just work.

## Current Behavior

Currently an error is thrown that `@nestjs/schematics` has to be installed first

![image](https://user-images.githubusercontent.com/542458/80376786-9c7cff00-889a-11ea-9aa1-73e5c77510b3.png)

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a new empty workspace
2. `yarn add @nrwl/nest`
3. `yarn nx g @nrwl/nest:init`

### Context

This has been introduced by #2756

**Comment by Cammisuli** [comment]
Fixed with #2999
