### ISSUE TITLE
Nx  can not perform "child_process"

### ISSUE THREAD

**Issue by offwork** [nrwl/nx#293]
<img width="918" alt="screen shot 2018-02-27 at 01 50 12" src="https://user-images.githubusercontent.com/10039583/36700966-890ed99a-1b62-11e8-8c61-3930f7c8b8a4.png">

Nx not completing the installation after creating the project. It's probably due to the changes that came with the new version of [Nodejs](https://github.com/nodejs/node/blob/319cd443a93baa70cc8c04808602c45bf79d4bf9/lib/child_process.js#L602).

**Comment by thelgevold** [comment]
Which version of node/OS are you using?

**Comment by offwork** [comment]
node v9.6.1 / macOS 10.13.3

**Comment by dereklin** [comment]
Same issue for me:

Node 8.9.4
Windows Subsystem for Linux

Works fine on Windows Dos Prompt

**Comment by thelgevold** [comment]
Can you retry with the latest version of nx (0.8.0) and @angular/cli@1.7.1?

**Comment by offwork** [comment]
The problem I'm experiencing exactly is this:

1. `create-nx-workspace support-ticket-suite --directory=ticket-system --npm-scope=suite`
     `child_process.js:614
    throw err;`

2.  `create-nx-workspace support-ticket-suite`
      everything is okay!

I use Yarn for package management. global prefix is as follows:
<img width="702" alt="kerem-terminal" src="https://user-images.githubusercontent.com/10039583/37051085-9cfe9a92-2186-11e8-866f-5b8ace71788a.png">

**Comment by ball6847** [comment]
I can confirm this.

As we can see here https://github.com/nrwl/nx/blob/eb42a4e34fb23a5a268ce9326695bf209b0f450a/packages/schematics/bin/create-nx-workspace.ts#L60

`create-nx-workspace` pass all additional arguments to `ng new` command including `--directory` which is a valid option for `ng new` command 

But later `create-nx-workspace` execute yarn and npm inside `projectName` which can be problematic if `projectName` and `--directory` flag are not the same value.

https://github.com/nrwl/nx/blob/eb42a4e34fb23a5a268ce9326695bf209b0f450a/packages/schematics/bin/create-nx-workspace.ts#L69

IMO, it would be great if `create-nx-workspace` acknowledge the --directory options and provide the correct value for cwd in next command.

**Comment by vsavkin** [comment]
This issue has been fixed here: da9310e9dbb4eb3294200ca72bfa70b14faec2c2
