### ISSUE TITLE
Nx React and Content Security Policy (CSP)

### ISSUE THREAD

**Issue by sasha-3ap** [nrwl/nx#2932]
Nx build generates code that requires use of 'unsafe-inline' for style-src  CSP directive. 
Is there a solution in Nx to avoid adding 'unsafe-inline' to CSP? (nonce, hash, ...)

## Expected Behavior
Solution/Option/Flag/Configuration at build time to avoid use of 'unsafe-inline' CSP directive. 

For example Material UI [supports](https://material-ui.com/styles/advanced/#how-does-one-implement-csp) nonce through use of meta tag. Solution is good because on every application (page) request new nonce can be generated and used.

Webpack supports nonce with `__webpack_nonce__` configuration but in this case static value for nonce is used which is not as good as previous example. 

## Current Behavior
Inline styles require use of 'unsafe-inline' CSP directive. 

### Context
- latest Nx with react

**Comment by sushruth** [comment]
@sasha-3ap were you able to address your CSP needs in some way?

**Comment by sasha-3ap** [comment]
> @sasha-3ap were you able to address your CSP needs in some way?

Unfortunately I found no solution in Nx for this.

I ended up solving this on nginx used to serve frontend (material ui). Solution was to generate nonce and inject header `<meta property="csp-nonce" content={nonce} />`. This is then used by [material-ui out of the box](https://material-ui.com/styles/advanced/#content-security-policy-csp).
