### ISSUE TITLE
Don't override libs in tsconfig of libraries

### ISSUE THREAD

**Issue by mperktold** [nrwl/nx#2937]
## Expected Behavior

When changing the libs of the global tsconfig.json of my workspace, this should affect all apps and libraries except those where I intentionally override the property in the local tsconfig.json.

## Current Behavior

When generating a library using `nx g lib some-lib`, the generated local tsconfig inside some-lib overrides the libs property. When changing the libs of the global tsconfig, some-lib is not affected since it overrides this property, and because it does so automatically, this is easy to miss.

## Other

The big picture is that IDEs such as Visual Studio Code use the global tsconfig, while ng cli tools such as use the local one.

So when upgrading the global tsconfig.json to say ES2018, VS Code lets me use ES2018 APIs inside some-lib without complaining, but e.g. ˋng lintˋ is missing the typings of the new APIs, and gives misleading warnings as a consequence.

To avoid this scenario, I suggest not to override the libs property in local tsconfig files. One can always manually override it when needed.
Also, I assume that when using Nx, one probably wants to use the same libs across the whole workspace, so there is little need to override it in libraries.

**Comment by squelix** [comment]
I have the same issue :/

**Comment by FrozenPandaz** [comment]
Hi, thanks for reporting this.

We can certainly add an option to skip it for workspaces that can use the root `tsconfig.json` for this. 

> one probably wants to use the same libs across the whole workspace

I don't believe this is true. `libs` allow you to bring in things like `dom` typings which should not be brought in when building NodeJS applications and vice versa. Limiting these `libs` to the set that matches the environment the code runs in prevents many issues where say `window` is used in a NodeJS app. We can figure out a way to skip parts of the `tsconfig.json` when generating the lib.

**Comment by mperktold** [comment]
> I don't believe this is true. libs allow you to bring in things like dom typings which should not be brought in when building NodeJS applications and vice versa.

That makes sense.

A workspace option would be great! 👍 

Thanks
