### ISSUE TITLE
Initiate routing upon pessimisticUpdate success

### ISSUE THREAD

**Issue by FallenRiteMonk** [nrwl/nx#294]
Hy,

what would be the best way to initiate a redirect upon successfully finishing a HTTP request?

My scenario is the following:
I have a lib that handles the authentication, which has a guard that checks login-state/permissions upon routing. If a user is now not logged in, a popup for authentication is shown.
What I want to achieve is that once the user successfully logged in I close the popup and want to redirect the page to where it was routing to that activated the guard. 

I am able to pass the wanted URL to the pessimisticUpdate effect. My question is only how would i no go about doing the navigation itself? would I dispatch a new NAVIGATION action or would I just import the router and navigate to where I want to?

**Comment by pkamdem** [comment]
@FallenRiteMonk Have you thought about using url to persist state?

1. Redirect to the auth route if a user is not logged (Persist requested page in url)
2. One login is complete, redirect to the previously requested page

============

Redirect to myapp/authroute?redirectpage=myredirected-page-persisted
Redirect to myapp/myredirected-page-persisted after login

**Comment by thelgevold** [comment]
Hi.
Closing since this isn't directly related to Nx. I recommend reposting on stackoverflow though.
