### ISSUE TITLE
remix ignores project vite.config.ts if target override in project.json

### ISSUE THREAD

**Issue by Evanion** [nrwl/nx#29402]
### Current Behavior

This is an odd issue.
if you have a page with a loader in a remix project, with the new singleFetch feature. the response differs if you change the `outputPath` in `project.json`

project.json:
```json
{
  "name": "reprod",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/reprod",
  "projectType": "application",
  "tags": [],
  "// targets": "to see all targets run: nx show project reprod --web",
  "targets": {
    "build": {
      "executor": "@nx/remix:build",
      "options": {
        "outputPath": "dist/apps/reprod",
        "generatePackageJson": true
      }
    }
  }
}
```

when running in dev mode, you get a response of:
```ts
{
  foo: "foo"
}
```
but if you run `nx build reprod` and then run `npm start` in the output, the response is different
```ts
{
  type: "DataWithResponseInit",
  data: {
    foo: "foo"
  },
  init: {
    headers: {
      "x-foo": "bar"
    }
  }
}
```

If you remove the build target from `project.json` it works as expected when you run `nx start reprod`.
It seems as though when you override the `build` target, vite no longer reads the projects `vite.config.ts` file, and instead uses some standard config, I noticed this since `nx build reprod` complains that I should enable feature flags that ARE enabled.

I have gone over the documentation for the build executor, but it doesn't have any missing configs.
https://nx.dev/nx-api/remix/executors/build

### Expected Behavior

I expect to be able to change the output target without it breaking the config.

### GitHub Repo

https://github.com/Evanion/remix-singleFetch-reprod

### Steps to Reproduce

1. Generate a new nx workspace (20.2.2) `npx create-nx-workspace@latest reprod-repo`
2. Add latest  `nx add @nx/remix`
3. Create a new remix app `nx g @nx/remix:app reprod`
4. Update `project.json` for `reprod` app, and add a new `outputPath`
```json
{
  "name": "reprod",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/reprod",
  "projectType": "application",
  "tags": [],
  "// targets": "to see all targets run: nx show project reprod --web",
  "targets": {
    "build": {
      "executor": "@nx/remix:build",
      "options": {
        "outputPath": "dist/apps/reprod",
        "generatePackageJson": true
      }
    }
  }
}
```
5. Add a loader to the index route, that returns a data object wrapped in a `data` function. (linked repo is at this stage)
6. run `nx dev reprod`
7. run `nx build reprod`
8. start prod version `cd dist/apps/reprod && npm start`

### Nx Report

```shell
Node           : 20.12.2
OS             : win32-x64
Native Target  : x86_64-windows
pnpm           : 9.12.1

nx (global)        : 20.0.0
nx                 : 20.2.2
@nx/js             : 20.2.2
@nx/jest           : 20.2.2
@nx/eslint         : 20.2.2
@nx/workspace      : 20.2.2
@nx/devkit         : 20.2.2
@nx/eslint-plugin  : 20.2.2
@nx/playwright     : 20.2.2
@nx/react          : 20.2.2
@nx/remix          : 20.2.2
@nx/vite           : 20.2.2
@nx/web            : 20.2.2
typescript         : 5.6.3
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
@nx/playwright/plugin
@nx/jest/plugin
@nx/remix/plugin
```

### Failure Logs

```shell

```

### Package Manager Version

pnpm 9.12.1

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
@Evanion It seems like you are trying to mix Inferred Task usage and Executor usage.

If you look in your Nx.json and see a `plugins` section containing `@nx/remix/plugin`, then there's no need to use `executor` in a build target in your `project.json`.

Instead, you should change your `vite.config.ts` file to update the output option within the `remix()` plugin itself, as explained here in the remix docs: https://remix.run/docs/en/main/file-conventions/vite-config

**Comment by Evanion** [comment]
@Coly010 That gives me a different output, the `dist/apps/reprod` folder contains a server and client folder. How do I start the app?
