### ISSUE TITLE
@nrwl/node and @nrwl/nest not cleaning up tmp directory

### ISSUE THREAD

**Issue by clonardo** [nrwl/nx#2940]
- [ X ] I am running the latest version
- [ X ] I checked the documentation (nx.dev) and found no answer
- [ X ] I checked to make sure that this issue has not already been filed
- [ X ] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

When running a node or nest.js app using `nx build` or `nx serve` (both of which invoke `@nrwl/node:build`, per the generated workspace.json), a `/tmp` directory is created. The directory is not cleaned up after build, or when the `nx serve` process exits.

## Current Behavior

A `/tmp` directory with a number of empty folders underneath (`apps`/`{projectName}`) is left over if running `nx build`. If running `nx serve`, after stopping that process, 

## Failure Information (for bugs)

`tmp` directory should not be left over after `build` or `serve` complete

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Init a new workspace: `npx create-nx-workspace@latest` (initialize as empty)
2. cd into the create workspace, run `yarn` to install dependencies
3. Add Nest or Node dependencies: `yarn add -D @nrwl/nest` or `yarn add -D @nrwl/node`
4. Add a Nest or Node app: `nx g @nrwl/nest:application myapp` or `nx g @nrwl/node:application myapp`
5. Run `nx serve` or `nx build`. If running `nx serve`, once the app comes up, press Ctrl + C to exit.
6. Observe the leftover `tmp` directory in the project root, as well as subdirectories as described above.

### Context

Please provide any relevant information about your setup:

- nx report output: 
```
  @nrwl/angular : Not Found
  @nrwl/cli : 9.2.3
  @nrwl/cypress : Not Found
  @nrwl/eslint-plugin-nx : 9.2.3
  @nrwl/express : Not Found
  @nrwl/jest : 9.2.3
  @nrwl/linter : 9.2.3
  @nrwl/nest : 9.2.3
  @nrwl/next : Not Found
  @nrwl/node : 9.2.3
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.3
  @nrwl/web : Not Found
  @nrwl/workspace : 9.2.3
  typescript : 3.8.3
```
- Windows 10 Pro x64
- Node.js 12.16.1 x64

### Failure Logs

N/A

**Comment by FrozenPandaz** [comment]
This has been fixed with https://github.com/nrwl/nx/commit/3bdcc0b0125c941eb0b4b5a77a6f5a8a8a3d11be in v9.3.0.
