### ISSUE TITLE
pnpm not working with nx - more explained inside

### ISSUE THREAD

**Issue by iangregsondev** [nrwl/nx#2944]
Hi,

I am trying to use pnpm with nx. I have brand new project. I did a pnpm install

and it created the following .bin under node_modules (notice the missing nx)

![image](https://user-images.githubusercontent.com/2370364/80754333-23e2a080-8b2f-11ea-8a8b-0a7c599cd290.png)

if you look further down there is a .pnpm directory which contains it

![image](https://user-images.githubusercontent.com/2370364/80754418-496faa00-8b2f-11ea-8d0a-075a9a79f81d.png)

executing NX from a nx repo that has been installed with NPM and NOT pnpm - gives the following - so it works

```
➜  deleteme2 git:(master) npm run nx

> deleteme2@0.0.0 nx /Users/ian/Development/Personal/typescript/deleteme2
> nx

Nx - Extensible Dev Tools for Monorepos.
```

But on the pnpm one

```
➜  instant-accounts git:(feature/initial-setup) ✗ npm run nx

> instant-accounts-ws@0.0.0 nx /Users/ian/Development/Personal/typescript/instant-accounts
> nx

sh: nx: command not found
```

Anybody managed to get a good workflow working with pnpm and nx ?

**Comment by FrozenPandaz** [comment]
Thank you for reporting and investigating the issue!

I see, so the issue is that `@nrwl/cli` is brought in by `@nrwl/workspace` which `npm` brings in to `.bin` but `pnpm` does not. To fix, `@nrwl/cli` should be a direct dependency. We wanted to avoid that to avoid so many dependencies when possible :thinking:.

cc @vsavkin

**Comment by smasala** [comment]
For the record (if migrating to `pnpm`), also require `"nx": "nx"` in your `package.json` under `scripts`

**Comment by npwork** [comment]
`pnpm nx`
simply returns empty line and it's not in .bin

<img width="472" alt="Screen Shot 2022-04-17 at 2 52 22 PM" src="https://user-images.githubusercontent.com/1792720/163713202-9dc128f9-c3cd-402f-bb66-137c687ffb09.png">


<img width="360" alt="Screen Shot 2022-04-17 at 2 52 59 PM" src="https://user-images.githubusercontent.com/1792720/163713224-abcce8ca-f37f-49fb-a8e5-1d9e9740de94.png">

**Comment by smitroshin** [comment]
System info:
```
WSL Ubuntu 20.04.4 LTS
```
Packages:
```
nx: v14.1.4
pnpm: v7.0.1
```

I installed nx globally using `pnpm add -g nx`.
And it works using just `nx` command, but I receive warning:

![image](https://user-images.githubusercontent.com/20210690/167802870-8165f9d9-2d5b-4bb5-abb7-a0232d946a59.png)

After, I tried two ways: `pnpm nx` and `pnpm exec nx`.

Outside nx workspace:

![image](https://user-images.githubusercontent.com/20210690/167801990-6ef49a17-9b47-4fb0-afb5-d7d4ac861be9.png)

Inside nx workspace:

![image](https://user-images.githubusercontent.com/20210690/167803600-198fd771-e630-490f-8573-8870ce4efc4f.png)

So, inside the project from some reason these commands just returns new line.
I think I need to mention that nx is listed in project devDependecies.

After removing nx from project devDependecies, nx started to execute command twice and continue to return warning even if I use `pnpm exec`.

![image](https://user-images.githubusercontent.com/20210690/167807826-ceb5a1eb-2234-4bc1-bc7e-f4dea63ad557.png)

**Comment by JoshuaEN** [comment]
The "bin" field is no longer specified in the `@nrwl/cli` package ( #9394 ).

"bin" is still specified in the `nx` package:https://github.com/nrwl/nx/blob/ba592f8a99778e5fadef39526419b1b326de2df8/packages/nx/package.json#L25

Thus adding [`nx`](https://www.npmjs.com/package/nx) (note: not `@nrwl/nx`) as a direct dev dependency causes `pnpm` to correctly add `nx` to `.bin`, and thus should resolve the `nx` not found error.

**Comment by electroheadfx** [comment]
I have the same issue, "nx": "./bin/nx.js" are there, what is the advice to run pnpm with NX, locally (no work) or globally (with the warning) ?

**Comment by alexgorbatchev** [comment]
There are still issues with pnpm. Simply following NX tutorial and generating a new project then running `pnpm i`, nothing works in VSCode. The NX Console extension doesn't work and VSCode doesn't pick up on any types or modules. Removing `node_modules` and running `npm i` fixes all issues.
