### ISSUE TITLE
@nrwl/angular :app and :lib schematics should support eslint

### ISSUE THREAD

**Issue by beeman** [nrwl/nx#2950]
## Expected Behavior

It would be great if we could create Angular apps and libs with eslint preconfigured.

## Current Behavior

Currently the option `--linter` is there, but it only allows selecting `tslint` which is deprecated.

## Other

I'm happy to give a shot at a PR that adds this, I just want to make sure if this is desired and if there are things I need to keep in mind while adding the functionality.

**Comment by brandonroberts** [comment]
Closing as a duplicate of #1699. We'll track progress there
