### ISSUE TITLE
Question - Running Storybook non dev build

### ISSUE THREAD

**Issue by danzrou** [nrwl/nx#2952]
Is there a schematic to build storybook for non dev (in order to deploy it)?
Thanks!

**Comment by twittwer** [comment]
The storybook schematics adds two new targets to your project `storybook` and `build-storybook`.  
So you can simply run `ng run <project>:build-storybook` instread of `ng run <project>:storybook` and you'll get a static build of your storybook in the `dist/storybook/<project>` directory.

Does this answer your question?

**Comment by danzrou** [comment]
Ye totally, that what I was looking for. Couldn't find that in documentation.
Thanks

**Comment by twittwer** [comment]
https://nx.dev/angular/plugins/storybook/builders/build
