### ISSUE TITLE
Blazor support

### ISSUE THREAD

**Issue by felixknox** [nrwl/nx#2954]
Hi team NX, thanks for a great and solid product.

I was wondering if you have done any considerations regarding support for [Blazor](https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor)?

**Comment by FacePalmDev** [comment]
I'd like to see this too

**Comment by krokofant** [comment]
This seems more related to a plugin such as https://github.com/nx-dotnet/nx-dotnet
