### ISSUE TITLE
Error in circular dependency detection ?

### ISSUE THREAD

**Issue by admir86** [nrwl/nx#2980]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

External packages with names that starts like an library name in the nx workspace should not be treated like the this lib.

## Current Behavior

I have four libs in my monorepo: common, desktop, concept and basiskomponenten.
In this monorepo I'm consuming a library "@inova/desktop-api-service" (from a private npm registry). Since I updated from @nrwl/workspace@8.12.11 to the latest I have lint errors where I'm importing objects from "@inova/desktop-api-service".

## Failure Information (for bugs)

![image](https://user-images.githubusercontent.com/36576424/81496087-40ac7000-92b5-11ea-89b2-62166a2f2900.png)

```
ERROR: C:/.../InovaFrontend/libs/common/src/lib/app-context/culture-context/culture-context.service.ts[10, 1]: Circular dependency between "common" and "desktop" detected
```
nx.json:
![image](https://user-images.githubusercontent.com/36576424/81496129-8ff2a080-92b5-11ea-9f46-fc9ca85f04cd.png)

lint.json:
![image](https://user-images.githubusercontent.com/36576424/81497520-52931080-92bf-11ea-9da2-feacda27dee8.png)

tsconfig.json:
![image](https://user-images.githubusercontent.com/36576424/81497631-fb417000-92bf-11ea-9ab8-bd1c2f1d24e9.png)

### Context

Please provide any relevant information about your setup:

```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 9.2.4
  @nrwl/cli : 9.2.4
  @nrwl/cypress : 9.2.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.2.4
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.4
  @nrwl/web : Not Found
  @nrwl/workspace : 9.2.4
  typescript : 3.8.3
```

**Comment by Hotell** [comment]
you need to allow those "private" packages under same scope within you lint configuration

```js
{
   '@nrwl/nx/enforce-module-boundaries': [
      'error',
       {
        allow: [
          // "our public/private packages github/npm"
          '@inova/desktop-api-service',
        ],
     }]
}
```

**Comment by admir86** [comment]
> you need to allow those "private" packages under same scope within you lint configuration
that don't resolve all of the errors.
anyway I think it would be only a workaround. why should external dependencies be treated in the nx-enforce-module-boundaries?

@FrozenPandaz 
maybe it's a problem of [this](https://github.com/nrwl/nx/issues/2570#issuecomment-605028582) new feature

**Comment by admir86** [comment]
just run `yarn nx run workspace:test` on my fork. the failing test will show the issue.

**Comment by admir86** [comment]
@FrozenPandaz is the unit test as repro not sufficient? do you need something more?
or can you remove the "blocked: repro needed" label? :)

**Comment by FrozenPandaz** [comment]
Thanks for the unit test case, that was super for fixing the issue.
