### ISSUE TITLE
The @nrwl/workspace:remove schematic should ignore node_modules, et al

### ISSUE THREAD

**Issue by beeman** [nrwl/nx#2981]
## Expected Behavior

The command `nx g @nrwl/workspace:remove <project>` takes a few seconds.

## Current Behavior

Currently it takes a few minutes (on my localhost)

```
$ time nx g @nrwl/workspace:remove web-package-list --dry-run
DELETE libs/web/package-list
UPDATE workspace.json (24570 bytes)
UPDATE nx.json (1403 bytes)
UPDATE tsconfig.json (1777 bytes)

NOTE: The "dryRun" flag means no changes were made.
nx g @nrwl/workspace:remove web-package-list --dry-run  320.71s user 106.77s system 112% cpu 6:20.70 total
```

## Other

I've added some debugging info in my node_modules and nailed it down to [this piece of code](https://github.com/nrwl/nx/blob/c00f996beaf64da0375e5cffe1107e6a1773a099/packages/workspace/src/schematics/remove/lib/check-dependencies.ts#L33-L39).

After adding this console log, you'll see that it will actually visit all contents of the `node_modules.  We probably want to filter out anything that's listed in .gitignore.

```javascript
tree.visit(file => {
  console.log('visit', file)
  files.push({... })
})
```

When I monkey-patch that snippet I get the expected results:

```
$ nx g @nrwl/workspace:remove web-package-list --dry-run  2.18s user 0.41s system 105% cpu 2.450 total
```

My monkey-patch is this:

```javascript
tree.getDir('/apps').visit(file => {
  ...
});
tree.getDir('/libs').visit(file => {
  ...
});
```

I'd be happy to submit a PR that fixes it, however I could not find how to filter the `tree: Tree` that we visit in this `checkDependencies` method. Very open for suggestions :)

**Comment by FrozenPandaz** [comment]
Yes! Thank you for investigating!

Check out this example to ignore `gitignore`'d files:
https://github.com/nrwl/nx/blob/b55a1a96dd74fc1ecc209eb4f42959933102bd75/packages/react/src/migrations/update-8-3-0/update-8-3-0.ts#L106

PRs welcome!

**Comment by beeman** [comment]
@FrozenPandaz I just submitted a PR. I went for a slightly different approach as filtering inside the `visit()` callback would be too late. That will still traverse the complete `node_modules`.

I talked to the maintainers of the Angular CLI and they confirmed that this is currently how a `tree: Tree` works, and showed work around similar to this.
