### ISSUE TITLE
Create @nrwl/web:lib with --js flag?

### ISSUE THREAD

**Issue by hsw107** [nrwl/nx#2985]
## Expected Behavior

I would think that running
`nx g @nrwl/web:lib myLib --js` would be able to run and generate a web library in js instead of ts.

Documentation says:

> TypeScript is a great choice for many teams, but not for everyone. If you want to use Nx with JavaScript, simply pass --js to **all generate commands**

(Emphasis mine)
[Source](https://nx.dev/react/guides/js-and-ts)

I am currently only using react and flow as type checker, and want to opt-out of typescript, even for web libraries.

## Current Behavior

What is the current behavior?
It outputs `Could not match option 'js' to the @nrwl/web:library schema.`

**Comment by shreyansh-zazz** [comment]
@BigAB How come this is a feature? In the documentation, it is clearly mentioned that in order to create anything in `js` instead of `ts` use the flag `--js` at the end. Why it's not working already?

**Comment by BigAB** [comment]
@shreyansh-zazz  🤷‍♂️ Perhaps it was an overly optimistic documentation?

I wasn't involved in the feature when it was added, but near as I can tell this flag is only handled in the `@nrwl/react` package.  I am currently investigating the effort to extend this to `@nrwl/web` or beyond.

**Comment by shreyansh-zazz** [comment]
> 🤷‍♂️ Perhaps it was an overly optimistic documentation?

Well, in that case, there are several overly optimistic statements present in the documentation. Perhaps we can put a little effort in removing them? 

PS: I wasted my whole day trying different things as mentioned in docs, which in reality didn't work.

**Comment by hsw107** [comment]
@shreyansh-zazz If you feel so strongly I'm sure you'd be welcomed to create a PR with clearer documentation. Like all software there will be bugs and gaps in features as well as in the documentation.

I agree the documentation was somewhat unclear, but I can see how this got missed and I'm glad they're taking a look at it now.

**Comment by briermay** [comment]
you claim to have fixed this, but its not fixed.
