### ISSUE TITLE
@nrwl/workspace:move schematics yields error: 'This should never happen.' 🤪

### ISSUE THREAD

**Issue by beeman** [nrwl/nx#2986]
## Expected Behavior

The command below either executes as expected, or yields a proper error message that it can't do what I ask it to. 

```
$ nx g @nrwl/workspace:move --projectName web-layout --destination web/layout/console
```

## Current Behavior

It fails, telling me that that should never happen. This message makes me feel both special and clumsy ;)

```
$ nx g @nrwl/workspace:move --projectName web-layout --destination web/layout/console
This should never happen. Path: "/libs/web/layout".
```

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

1. `yarn create nx-workspace my-app`
1. `cd my-app`
2. `yarn add -D @nrwl/angular`
3. `nx g @nrwl/angular:lib layout --directory web`
4. `nx g @nrwl/workspace:move --projectName web-layout --destination web/layout/console`

## Other

The workaround is to do the move in 2 steps:

```
$ nx g @nrwl/workspace:move --projectName web-layout --destination web/layout-console
$ nx g @nrwl/workspace:move --projectName web-layout-console --destination web/layout/console
```

**Comment by beeman** [comment]
Probably related https://github.com/angular/angular-cli/issues/16527

**Comment by FrozenPandaz** [comment]
This is reproducible on https://github.com/nrwl/nx-examples with the following command:

```
ng g @nrwl/workspace:move cart/cart-page/cart-page --projectName cart-cart-page
```

**Comment by george43g** [comment]
I tried to move a library down below its own path and got this error. A clearer error message would have been great.

I tried 'testing' -> 'testing/util' - it failed. 

Instead, this worked:
'testing' -> 'temp-testing', and then
'temp-testing' -> 'testing/util'

**Comment by llwt** [comment]
Ran into this as well when trying to write unit tests for our custom move / delete schematics that wrap the default. I wasn't able to find a work around (in our tests) but seems related to angular/angular-cli#16527 as @beeman called out.

> It seems to happen if those files were created by a previous rule and the move is done by copy and deletion.

For us it's running the `lib` schematic, then attempting to run the `move` schematic right after in a single test.

**Comment by beeman** [comment]
I think it would be great if this could be addressed at some point. Not urgent, be definitely a nice addition :)
