### ISSUE TITLE
TS2305 issue

### ISSUE THREAD

**Issue by Alakazam03** [nrwl/nx#2989]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [y] I am running the latest version
- [y] I checked the documentation (nx.dev) and found no answer
- [y] I checked to make sure that this issue has not already been filed
- [y] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

The file should be exported properly

## Current Behavior

Starting type checking service...
Using 2 workers with 2048MB memory limit
Hash: b6d9493833e894f1c73f
Built at: 12/05/2020 00:56:32
Entrypoint main = main.js main.js.map
chunk {main} main.js, main.js.map (main) 19 KiB [entry] [rendered]

WARNING in ./apps/backend/src/app/routes/offers.ts 23:31-37
"export 'offers' was not found in '../logic'

ERROR in /Users/alakazam/Documents/projects/nodejs/main-backend/apps/backend/src/app/routes/offers.ts
ERROR in /Users/alakazam/Documents/projects/nodejs/main-backend/apps/backend/src/app/routes/offers.ts(3,10):
TS2305: Module '"../../../../../../../../../../../Users/alakazam/Documents/projects/nodejs/main-backend/apps/backend/src/app/logic"' has no exported member 'offers'.

## Other
I have added new files to my apps. I am writing  express project using typescript. But the newly added files are being recognised.

Please help @texel @peterblazejewicz @beeman

**Comment by FrozenPandaz** [comment]
Sorry, we cannot do anything to help debug your issue without a repo.

Please provide a repo for us to look at.

**Comment by beeman** [comment]
@FrozenPandaz this one and #2984 can be closed, we fixed his issue in Slack.

**Comment by FrozenPandaz** [comment]
Awesome! Thank you!

**Comment by Blackhex** [comment]
Where was the problem, please?

**Comment by kenptr** [comment]
I'm having similar issue (I believe). What was the problem and how did you solve it?
