### ISSUE TITLE
feature: parse typescript for webpackConfig file in @nrwl/node:build

### ISSUE THREAD

**Issue by george43g** [nrwl/nx#2990]
## Expected Behavior

Hi, this isn't really a bug but I thought it might be an easy fix so might be worth lodging an issue.
This is regarding the `@nrwl/node:build` builder for nx.
There is a configuration option, for `@nrwl/node:build`, that is `webpackConfig`.
It works by loading a js file, and passing two parameters to the exported function, `config` and `context`. 
You're meant to take the config object and return it with updated values.

Working with the config object would be much easier with type information. For this to be possible, it should also be possible to write the module in Typescript.

So the feature request is to add a typescript loader to the node builder so it's able to process typescript `webpackConfig` files.

With webpack's own webpack.config.js/ts, this already works. It's already possible to configure webpack to use a loader (documented feature) to read a `webpack.config.ts` file. It would be great if we could do this with Nx too.

## Current Behavior

It will load files with either file extension, but treat the source code as JS. If it encounters TS, it will crash.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. set your `webpackConfig` json key in `angular.json` to point to a TS file
2. write a ts file with a function as the export object
3. attempt to build project `nx build custom-webpack-project`

**Comment by george43g** [comment]
I should add one more thing. There may be a case where you need to await a promise before you can return the new config. It would also be useful if the consuming code could await the loaded function rather than just trying to read the new config.

I believe the await keyword can be used on a value regardless of wether it is a promise. So if a value (return value in this case) *might* be a promise, awaiting it woudl yield the result, and if it was a sync function then awaiting it would make no difference.

I also found one last bug with the run-commands builder - let me know if I should post either of these as separate issues.
With the run-commands builder, it is possible to specify a dotEnv file. If the file contains comments on the same line, such as,
`myVar="test" #this is a test var`, the value passed into the env variable includes the comment. For example, the above would yield the following:
```echo $myVar
"test" #this is a test var```

**Comment by tonivj5** [comment]
Could be reopened this issue?
