### ISSUE TITLE
library does not have fileReplacements options

### ISSUE THREAD

**Issue by naishe** [nrwl/nx#2991]
I am splitting my application into two different services. This requires me to factor out the data access code in a separate library. Unfortunately, I do not see a `fileReplacement` option in `workspace.json` for the library.

I need to have different settings likes query logging on or off, caching in memory or Redis, and discovery services based on the environment. I was hoping that I will configure various env settings under `libs/data/src/environments` and switch to appropriate env during the build.

Can someone help me how to achieve this?

**Comment by FrozenPandaz** [comment]
Unfortunately, the `fileReplacement` has to be done in the app config. But you can pass files from the `lib` there as follows:

```

                {
                  "replace": "libs/environment/src/environments/environment.ts",
                  "with": "libs/environment/src/environments/environment.prod.ts"
                }
```

**Comment by VanTigranyan** [comment]
@FrozenPandaz is it possible to create a simple library like this and make it buildable, as all my libs are buildable and I cannot import these files to any of them if it is not buildable one.
