### ISSUE TITLE
eslint version check fails to recognize latest release (v7)

### ISSUE THREAD

**Issue by benediktvaldez** [nrwl/nx#3001]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

I would expect to be able to upgrade to the latest version of `eslint`, in this case `v7.0.0`. Especially considering the message I get from NX is that eslint must be version 6.1 or higher.

## Current Behavior

When I upgraded `eslint`, I got a message for each package saying that `ESLint must be version 6.1 or higher.`.

## Failure Information (for bugs)

When running `yarn lint` I get the following output.

```
$ nx workspace-lint && nx lint

Linting "repro-app"...
ESLint must be version 6.1 or higher.
```

### Steps to Reproduce

I've created a repo with a fresh workspace reproducing the problem at [benediktvaldez/eslint-v7-0-0-repro-workspace](https://github.com/benediktvaldez/eslint-v7-0-0-repro-workspace) (initial commit is original workspace, second commit has upgraded eslint)

1. create new workspace with an app that uses eslint, for example next.js
2. `yarn lint` works fine out of the box
```
$ nx workspace-lint && nx lint

Linting "repro-app"...

All files pass linting.
```
3. upgrade `eslint` dependency to `v7.0.0`
5. `yarn lint` results in error
```
$ nx workspace-lint && nx lint

Linting "repro-app"...
ESLint must be version 6.1 or higher.
```

### Context

nx report output
```
@nrwl/angular : Not Found
@nrwl/cli : 9.2.4
@nrwl/cypress : 9.2.4
@nrwl/eslint-plugin-nx : 9.2.4
@nrwl/express : 9.2.4
@nrwl/jest : 9.2.4
@nrwl/linter : 9.2.4
@nrwl/nest : Not Found
@nrwl/next : 9.2.4
@nrwl/node : 9.2.4
@nrwl/react : 9.2.4
@nrwl/schematics : Not Found
@nrwl/tao : 9.2.4
@nrwl/web : 9.2.4
@nrwl/workspace : 9.2.4
typescript : 3.9.2
```

3rd party
```
eslint: 7.0.0
```

## Other

I believe I have found the problem in the code base, and I've created a PR with the change I believe is needed #3002.

I believe the problem is here: https://github.com/nrwl/nx/blob/b55a1a96dd74fc1ecc209eb4f42959933102bd75/packages/linter/src/builders/lint/lint.impl.ts#L35-L40

If I'm reading this correctly this problem will disappear again when we get to `>v7.1.0` but re-emerge every time we get a major release that has a minor version below 1.

I tried changing these lines locally in my `node_modules` folder to the following, notice the only difference is that we only compare the minor version number when the major version is 6. This resulted in successfully running the lint script.

```typescript
if (
  !version ||
  version.length < 2 ||
  Number(version[0]) < 6 ||
  (Number(version[0]) === 6 && Number(version[1]) < 1)
) {
```

**Comment by IAMtheIAM** [comment]
Good catch. Foretuntely, eslint 7.1.0 is out now so you can just increment versions to avoid this until it's fixed

**Comment by benediktvaldez** [comment]
> Good catch. Foretuntely, eslint 7.1.0 is out now so you can just increment versions to avoid this until it's fixed

Yeah it's less urgent now since 7.1.0 is out. I already have a PR to fix this so it will most likely be merged before v8 comes out 😊
