### ISSUE TITLE
@nrwl/storybook: migrate to new storybook configuration - >=5.3

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#3003]
# This is a feature request

**things to be done:**
- update storybook schematics
- provide migrations from old to new sb config

## Expected Behavior

Use new storybook configuration (post v5.3) when running schematics
-> https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#to-mainjs-configuration

as the currently used is "soft-deprecated"

![image](https://user-images.githubusercontent.com/1223799/81838839-00642080-9547-11ea-94aa-834c20f28bfb.png)

## Current Behavior

schematics are using pre 5.3 configuration

### Context

```
  @nrwl/angular : Not Found
  @nrwl/cli : 9.2.4
  @nrwl/cypress : 9.2.4
  @nrwl/eslint-plugin-nx : 9.2.4
  @nrwl/express : Not Found
  @nrwl/jest : 9.2.4
  @nrwl/linter : 9.2.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.2.4
  @nrwl/react : 9.2.4
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.4
  @nrwl/web : 9.2.4
  @nrwl/workspace : 9.2.4
  typescript : 3.8.3
```

**Comment by TimNuman** [comment]
Agreed, the new storybook main.js setup is much cleaner and easier.

My new main main.js file (./storybook in the repo root)

```
module.exports = {
  stories: ['../src/**/*.stories.tsx'],
  addons: ['@storybook/addon-knobs'],
};

```

My new main.js file in the project that uses storybook:

```
const main = require('../../../../.storybook/main');
module.exports = main;
```

Should be a small change?
How would I got about making a PR? :)

**Comment by sl-benjamindupuy** [comment]
Agreed too, new storybook configuration is much better and change should be done before current config become depreciated...

**Comment by mandarini** [comment]
Hi @Hotell ! We are working on the Storybook 6 upgrade at the moment! I think this will solve this issue! :) [This](https://github.com/nrwl/nx/pull/3434) is still a draft pull request!
