### ISSUE TITLE
Jest builder is missing "--coverage" and "--no-coverage" options.

### ISSUE THREAD

**Issue by zbream** [nrwl/nx#3005]
## Expected Behavior

Working in an NX Workspace using Angular and Jest, I cannot use the [vscode-jest](https://github.com/jest-community/vscode-jest) extension to run and debug unit tests. 

It looks like this was possible in the past ([comment](https://github.com/nrwl/nx/issues/1190#issuecomment-475654455), [pull request](https://github.com/nrwl/nx/pull/1118)), however this no longer works.

## Current Behavior

A recent change removed support for the **--coverage** argument:

https://github.com/nrwl/nx/pull/2569

However, the extension will automatically pass in **--coverage** or **--no-coverage** depending on configuration, it looks like we don't have control over that. The NX Jest builder should support these arguments.

## Failure Information (for bugs)

After configuring the extension to use **ng test**, the following error is reported in the output console:

![image](https://user-images.githubusercontent.com/16364440/81855554-807d8c80-952d-11ea-9a06-bf1874cd93b0.png)

### Steps to Reproduce

1. Create a new NX repo using Jest as the unit test runner.
2. Configure VSCode according to [this comment](https://github.com/nrwl/nx/issues/1190#issuecomment-475654455).
3. Check the Output console for Jest extension.

### Context

```
  @nrwl/angular : 9.1.4
  @nrwl/cli : 9.1.4
  @nrwl/cypress : 9.1.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.1.4
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.1.4
  @nrwl/web : Not Found
  @nrwl/workspace : 9.1.4
  typescript : 3.7.5
```

[`vscode-jest`](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest): 3.2.0

## Other

Is there a reason that the Jest NX builder has its own API over Jest? Would it be possible for it to pass along any config options to the underlying CLI? I'm not overly familiar with builders, this might not be possible.

**Comment by FrozenPandaz** [comment]
Thank you for tracking the issue down :+1:.
