### ISSUE TITLE
Unable to create Nx workspace

### ISSUE THREAD

**Issue by howlofthesun** [nrwl/nx#3006]
- [ x] I am running the latest version
- [ x] I checked the documentation (nx.dev) and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

```
npx create-nx-workspace@latest nx-test 
```
should create a new workspace.
 
## Current Behavior
```sh
[user nx-test]$ npx create-nx-workspace@latest nx-test -v
npx: installed 198 in 6.529s
? What to create in the new workspace empty             [an empty workspace]
? CLI to power the Nx workspace       Nx           [Extensible CLI for JavaScript and TypeScript applications]
Creating a sandbox with Nx...
➤ YN0000: ┌ Resolution step
➤ YN0060: │ root-workspace-0b6124@workspace:. provides prettier@npm:1.18.2 with version 1.18.2 which doesn't satisfy ^1.19.1 requested by @nrwl/workspace@npm:9.2.4
➤ YN0000: └ Completed in 1.57s
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0.43s
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0.34s
➤ YN0000: Done with warnings in 2.35s
new nx-test "-v" --preset="empty" --interactive=false --collection=@nrwl/workspace
/bin/sh: /tmp/tmp-99937QQ0p3obQ5ca/node_modules/.bin/tao: No such file or directory
(node:9993) UnhandledPromiseRejectionWarning: Error: Command failed: "/tmp/tmp-99937QQ0p3obQ5ca/node_modules/.bin/tao" new nx-test "-v" --preset="empty" --interactive=false --collection=@nrwl/workspace
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at createApp (/home/user/.npm/_npx/9993/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:343:21)
    at /home/user/.npm/_npx/9993/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:76:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:9993) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9993) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Other

Ive uninstalled and reinstalled nx cli.

**Comment by FrozenPandaz** [comment]
Hm sorry, I am not able to replicate the issue.

Is there any more info that you can provide such as your OS and `npm` version?

**Comment by st-clair-clarke** [comment]
@FrozenPandaz @howlofthesun  I don't understand why these issues cannot be replicated by @FrozenPandaz. I get the same error when I attempted I use the same command above. I was wondering why there should be an error at the first attempt at using nx.

The command that actually works for me is:

`npx create-nx-workspace nx-test `

I reported an issue 2 days ago that @FrozenPandaz  could not replicate either - yet the problem is also present on Windows x64 and Mac. Hmm....

**Comment by overlineink** [comment]
Reviving the same error! 👎
cc: @Froze
```json
[error] Error: Could not find module "@nrwl/workspace" from ".../x-workspace".
    at Object.resolve (/home/x/node_modules/@angular-devkit/core/node/resolve.js:154:11)
    at NodeModulesEngineHost._resolvePackageJson (/home/x/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:28:21)
    at NodeModulesEngineHost._resolveCollectionPath (/home/x/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:69:40)
    at NodeModulesEngineHost.createCollectionDescription (/home/x/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:115:27)
    at SchematicEngine._createCollectionDescription (/home/x/node_modules/@angular-devkit/schematics/src/engine/engine.js:147:40)
    at SchematicEngine.createCollection (/home/x/node_modules/@angular-devkit/schematics/src/engine/engine.js:140:43)
    at NewCommand.getCollection (/home/x/node_modules/@angular/cli/models/schematic-command.js:128:35)
    at NewCommand.initialize (/home/x/node_modules/@angular/cli/models/schematic-command.js:44:37)
    at async NewCommand.validateAndRun (/home/x/node_modules/@angular/cli/models/command.js:124:9)
    at async Object.runCommand (/home/x/node_modules/@angular/cli/models/command-runner.js:186:24)
```

**Comment by iromashko** [comment]
I got same error. Manjaro 20.0, npm: 6.14.5,  node 14.2.0
![2020-05-15-204431_1920x1080_scrot](https://user-images.githubusercontent.com/3991384/82108305-4f23dd00-9736-11ea-9461-39f8e21319d9.png)

**Comment by howlofthesun** [comment]
Sure. sorry for the delay.
OS: `Centos7` 
Node: `v12.16.1`
NPM: `6.14.5`

**Comment by Qarun-Qadir-Bissoondial** [comment]
Can confirm that I get this same error that I briefly mentioned [here](https://github.com/nrwl/nx/issues/3128). I'm running Pop!_OS 18.04 LTS

**Comment by AshkanHovold** [comment]
I got the same issue.
OS: Ubuntu 20.04
npm 6.14.5
node v12.13.0

**Comment by vsavkin** [comment]
@AshkanHovold @howlofthesun @iromashko could you try it again with `npx  create-nx-workspace@9.5.1`. 

It looks like the CLI wasn't able to find the collection. Not sure why this happened. We, however, changed the create-nx-workspace command to point to the collection using an absolute path. If you try 9.5.1, we can see if it still fails.

**Comment by vsavkin** [comment]
Closing this issue

**Comment by bostondevin** [comment]
I get this error using Mac OS Mohave - it doesn't happen with Catalina:

Devins-Air:GitHub bostondevin$ npx create-nx-workspace@latest
? Workspace name (e.g., org name)     mgx-studio
? What to create in the new workspace react-express     [a workspace with a full stack application (React + Express)]
? Application name                    MGX Studio
? Default stylesheet format           styled-components [ https://styled-components.com            ]
? Use Nx Cloud? (It's free and doesn't require registration.) Yes [Faster builds, run details, Github integration. Learn more at https://
nx.app]
Creating a sandbox with Nx...
error Couldn't find package "@nrwl/workspace" on the "npm" registry.
node:child_process:636
    err = new Error(msg);
          ^

Error: Command failed: yarn install --silent
    at checkExecSyncError (node:child_process:636:11)
    at Object.execSync (node:child_process:672:15)
    at createSandbox (/Users/bostondevin/.npm/_npx/505743838affa773/node_modules/create-nx-workspace/bin/create-nx-workspace.js:386:21)
    at /Users/bostondevin/.npm/_npx/505743838affa773/node_modules/create-nx-workspace/bin/create-nx-workspace.js:91:44
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 31242,
  stdout: null,
  stderr: null
}
npm ERR! code 1
npm ERR! path /Users/bostondevin/Documents/GitHub
npm ERR! command failed
npm ERR! command sh -c create-nx-workspace

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bostondevin/.npm/_logs/2020-11-07T13_28_52_262Z-debug.log
