### ISSUE TITLE
Prevent or warn when plugins have mixed dependencies

### ISSUE THREAD

**Issue by sharebear** [nrwl/nx#3012]
## Expected Behavior

Some mechanism to prevent mixing plugin versions when a new version of nx is released

## Current Behavior

Unknowingly installing a plugin of the wrong version causes cryptic error message. Today I installed the angular plugin in a workspace I created last week, this caused the version numbers to be incorrect (existing plugins are 9.2.4 the newly installed plugin is 9.3.0).

## Failure Information (for bugs)

```
 nx generate @nrwl/angular:application --name=loan-frontend --style=CSS --backendProject=loan-api --e2eTestRunner=none --prefix=loan --routing --skipTests --unitTestRunner=none --no-interactive --dry-run
workspace_1.setDefaultCollection is not a function
```

### Steps to Reproduce

1. `npx create-nx-workspace@9.2.4 oldworkspace` # simulate "old" workspace
2. `cd oldworkspace`
3. `npm install --save-dev @nrwl/angular` # copy-paste from documentation
4. `nx generate @nrwl/angular:application`

## Other

To some extent I understand that this is user error (unless this should have been treated as a breaking API change), but not _very_ easy to spot if you're not watching the diffs in package.json closely. Could some part of the infrastructure catch a version mismatch before running further code?

**Comment by sharebear** [comment]
FYI `nx migrate @nrwl/workspace` did resolve the problem, but I still feel the situation could have been handled better by the tooling.

**Comment by PaddingtonTheBear** [comment]
> FYI `nx migrate @nrwl/workspace` did resolve the problem, but I still feel the situation could have been handled better by the tooling.

Appreciate you posting this and posting the "workaround" to manually migrate. I'm not sure how I wound up in this situation where I had mismatched versions, just started getting the cryptic ```workspace_1.setDefaultCollection is not a function``` error when trying to add new applications.
