### ISSUE TITLE
Optionally disable "noImportsOfLazyLoadedLibraries" in tslint

### ISSUE THREAD

**Issue by leon-marzahn** [nrwl/nx#3014]
## Expected Behavior

It should be possible to disable the "noImportsOfLazyLoadedLibraries" check. In some cases it is intended to import a lazy loaded library (For example if you import it in another lazy loaded library).

## Current Behavior

When you import a lazy loaded library via the es6 import, linting fails.

**Comment by JamesHenry** [comment]
Hi @leon-marzahn please allow me to apologise that you didn't receive an explicit acknowledgement on this before now.

You have written "tslint" in the title, but "noImportsOfLazyLoadedLibraries" is a string used within the _eslint_ plugin, please could you clarify which one you mean?

**Comment by leon-marzahn** [comment]
Hi @JamesHenry, thanks for responding. I began having the issue after upgrading to ivy. I "fixed" the issue by setting "nx-enforce-module-boundaries" to allow my lazy loaded modules to be imported. I assumed it was related to tslint, but maybe it is related to eslint.

**Comment by JamesHenry** [comment]
@leon-marzahn Ok, please could you provide a minimal reproduction of the issue?

**Comment by leon-marzahn** [comment]
@JamesHenry Ok, i could provide a reprodution, but why? It's some rule eslint/tslint that prevents lazy-loaded modules from being imported directly (Outside of angular routing). And as far as i can tell, i couldn't reproduce it easily, as only linting fails. Everything else is fine.

**Comment by JamesHenry** [comment]
@leon-marzahn If you can provide a repo with some instructions on how to encounter the lint failure with a comment on how you are suggesting it should change, then that is naturally going to be the fastest and most efficient way to a resolution.

Right now there is no clear evidence of what you are observing or the change in behaviour you are suggesting and without that it's hard to proceed.

If for some reason you are unable to provide a repo, a serious of screenshots with detailed notes around relevant commands and configuration files would still be a great improvement

**Comment by leon-marzahn** [comment]
@JamesHenry So apparently, it has been fixed somewhere between May 2020 and now. I thought making this issue might help fixing the bug, but apparently the better approach was to wait almost a full year and it's fixed :)

**Comment by JamesHenry** [comment]
Thank you for confirming @leon-marzahn and sorry again for the long gap between responses!
