### ISSUE TITLE
Next Js: Update to Next 9.4

### ISSUE THREAD

**Issue by asherccohen** [nrwl/nx#3020]
- [x ] I am running the latest version
- [x ] I checked the documentation (nx.dev) and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Next js should be at version 9.4 which introduces some cool default features (fast refresh for example), making entry barrier for new starters even easier.  For reference https://nextjs.org/blog/next-9-4

## Current Behavior

Next js is currently at 9.3.3.

**Comment by benediktvaldez** [comment]
I actually just updated it manually in my package.json. Are there changes required within nx to achieve this, except of course for new generated apps?

**Comment by conioX** [comment]
any news about this because its still 9.3.3 guys
