### ISSUE TITLE
paths in the root "tsconfig" or the "tsconfig.app" files aren't being resolved

### ISSUE THREAD

**Issue by AlaaElrifaie** [nrwl/nx#3026]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [✓] I am running the latest version
- [✓] I checked the documentation (nx.dev) and found no answer
- [✓] I checked to make sure that this issue has not already been filed
- [✓] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

When I add entries to the "paths" block in "tsconfig.json" within the root of my Nx workspace they should be resolved and I should be able to use them in my Angular project.
```
"paths": {
      "@fuse": ["@fuse/"],
      "@app/*": ["app/*"],
      "@environments/*": ["environments/*"]
    }
```

## Current Behavior

Path's do not get resolved as when using them inside a vanilla Angular CLI project.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Add a custom path to "paths" inside tsconfig.json inside an Nx repo.
2. Try to use the new custom path inside an Angular application for imports.

Thanks in advance.

**Comment by mattarau** [comment]
Hey @AlaaElrifaie, I'm having the same problem right now, but you've closed the issue without any explanation on that. Did you have luck fixing it?
