### ISSUE TITLE
 @nrwl/react:storybook dependency bug

### ISSUE THREAD

**Issue by epikhighs** [nrwl/nx#3030]
## Expected Behavior

when running `nx g @nrwl/react:storybook-configuration foo--js`   the following packages should not be installed unless necessary

    "@storybook/angular": "5.3.9",
    "@angular/forms": "*"

## Current Behavior

when running `nx g @nrwl/react:storybook-configuration foo--js`   the following packages are installed to package.json, but my project does not need these packages.

    "@storybook/angular": "5.3.9",
    "@angular/forms": "*"

using nx 9.2.4

**Comment by FrozenPandaz** [comment]
This was fixed in `v9.3.0` please retry with the latest version and reopen if this is still an issue.
