### ISSUE TITLE
NX affected - runs against all libraries with any tsconfig.json change

### ISSUE THREAD

**Issue by tanepiper** [nrwl/nx#3031]
## Expected Behavior

When running `nx affected:libs` commands that it should pick up only libraries that have changed, should be able to ignore non-library changes

## Current Behavior

When running `nx affected:libs` commands pick up external changes such as 'tsconfig.json' - specifically adding a new library with no dependence on other library in my code running affected still runs all libraries.

### Steps to Reproduce

1. From master of mono-repo create new branch
2. Run generate command (`nx g @nrwl/node:lib --name=newlib`
3. Run `nx affected:test`

Instead of just testing the new library, it's tests all libraries.

Example can be seen here in this PR: https://github.com/tanepiper/rxjs-primitives/pull/32

```
  NX  Running target lint for projects:

  - rxjs-array
  - rxjs-boolean
  - rxjs-utility
  - rxjs-string
  - rxjs-number
```

However it should only run for `rxjs-boolean` and `rxjs-array`, but as array was a newly added library in the tsconfig it runs all

**Comment by Hotell** [comment]
can you give us your `nx.json` please ?

It's probably caused by having `tsconfig.json` in implicitDependencies

![image](https://user-images.githubusercontent.com/1223799/82303205-edc07000-99ba-11ea-84b6-6bbd4f7480c5.png)

**Comment by tanepiper** [comment]
Ahh, would explain things:

```
{
  "npmScope": "tinynodes",
  "implicitDependencies": {
    "workspace.json": "*",
    "package.json": {
      "dependencies": "*",
      "devDependencies": "*"
    },
    "tsconfig.json": "*",
    "tslint.json": "*",
    "nx.json": "*"
  },
  "tasksRunnerOptions": {
    "default": {
      "runner": "@nrwl/workspace/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build", "lint", "test", "e2e"]
      }
    }
  },
  "projects": {
    "rxjs-string": {
      "tags": []
    },
    "rxjs-number": {
      "tags": []
    },
    "rxjs-boolean": {
      "tags": []
    },
    "rxjs-utility": {
      "tags": []
    },
    "rxjs-array": {
      "tags": []
    }
  }
}
```
