### ISSUE TITLE
Disable format on new app creation.

### ISSUE THREAD

**Issue by ph55** [nrwl/nx#305]
After migrating project to 'nx' and adding new app to workspace - format runs on newly created app and old converted project as well.

Any way to disable format ?
Removing 'postGenerate' line from 'default' doesn't have effect.

![image](https://user-images.githubusercontent.com/1386622/36977852-475ddf36-208b-11e8-9783-45d63bf4027a.png)

**Comment by ph55** [comment]
Never mind https://github.com/nrwl/nx/issues/187

**Comment by exequiel09** [comment]
Why close this? I also needed to disable auto-formatting not only when generating apps but also libs. Previous versions allows disabling the auto-formatting during generation.

**Comment by exequiel09** [comment]
@vsavkin is there any way to disable auto-formatting during generation? Thanks :)
