### ISSUE TITLE
create-nx-workspace fails when choosing a preset with Angular CLI

### ISSUE THREAD

**Issue by beeman** [nrwl/nx#3059]
## Expected Behavior

`create-nx-workspace` should not fail when choosing a preset with Angular CLI.

## Current Behavior

`create-nx-workspace` fails when choosing a preset with Angular CLI.

### Steps to Reproduce

1. Run `yarn create nx-workspace my-app --preset empty --cli angular`

### Context

Angular CLI does not understand the `--preset` parameter.

### Failure Logs

```
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "create-nx-workspace > @nrwl/workspace@9.3.0" has unmet peer dependency "prettier@^2.0.4".
[4/4] 🔨  Building fresh packages...

success Installed "create-nx-workspace@9.3.0" with binaries:
      - create-nx-workspace
[#########################################################################################################################] 195/195Creating a sandbox with Nx...
warning @angular/cli > universal-analytics > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
new my-app "empty" "angular" --preset="empty" --interactive=false --collection=@nrwl/workspace
Unknown option: 'empty'
Unknown option: 'angular'
(node:66660) UnhandledPromiseRejectionWarning: Error: Command failed: "/var/folders/rr/n45jfj7130x1vdvcv4dywpvc0000gn/T/tmp-66660AWAygwLIGEdQ/node_modules/.bin/ng" new my-app "empty" "angular" --preset="empty" --interactive=false --collection=@nrwl/workspace
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at createApp (/Users/beeman/.config/yarn/global/node_modules/create-nx-workspace/bin/create-nx-workspace.js:343:21)
    at /Users/beeman/.config/yarn/global/node_modules/create-nx-workspace/bin/create-nx-workspace.js:76:21
(node:66660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:66660) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 23.27s.
```

## Other

For shits and giggles I include a visual representation of the issue 🤓

![nx-preset-issue](https://user-images.githubusercontent.com/36491/82733351-dcd46f00-9cd8-11ea-91dc-49a66fd0c045.gif)

**Comment by FrozenPandaz** [comment]
For some reason, those args have to have equals between them. I think this is inconsistent with the rest of the commands. Would somebody from the community be interested in investigating a fix?

**Comment by beeman** [comment]
@FrozenPandaz I'm already looking at fixing it :)

**Comment by FrozenPandaz** [comment]
Thank you @beeman!

**Comment by beeman** [comment]
@FrozenPandaz just submitted my PR.

>  those args have to have equals between them

From looking at the code and the actual issue, we were passing in too much parameters for the Angular CLI.

```
new my-app "empty" "angular" --preset="empty" --interactive=false --collection=@nrwl/workspace
Unknown option: 'empty'
Unknown option: 'angular'
```

Both the words `empty` and `angular` that can see in this part of the error are obsolete. The `empty` is a leftover from the `--preset` arg, but that gets passed in. The `angular` is a leftover from the `--cli` parameter, and this is something we don't use when delegating to Angular CLI as it has no notion of alternative CLI's.

I hope this makes it a bit clear, happy to elaborate further if needed :)
