### ISSUE TITLE
nx.dev unreachable

### ISSUE THREAD

**Issue by jschank** [nrwl/nx#3066]
None of the presets apply.
I simply cannot load any content from https://nx.dev, and I don't know how else to tell you.

I get a message, in Chrome, that says this:

This site can’t be reachednx.dev’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

I would love to access all of the wonderful content on nx.dev

**Comment by FrozenPandaz** [comment]
Hi, I'm able to reach the site now. Are you still having issues?

**Comment by jschank** [comment]
Nope - it still doesn't work. 
Is there an ip address I can try - it looks like DNS can't find it

**Comment by jschank** [comment]
My router uses these DNS Server settings.
71.252.0.12
68.237.161.12

I tried using 8.8.8.8, and it didn't help

**Comment by FrozenPandaz** [comment]
Sorry, I am able to resolve nx.dev using 8.8.8.8 as well :confused::

![image](https://user-images.githubusercontent.com/8104246/82764614-1d69e080-9dde-11ea-9b68-148b96b00a29.png)

**Comment by jschank** [comment]
ok... and when I try to use the ip address directly and go to https://151.101.1.195
I get a firebase site not found error.

When I try https://151.101.65.195
I get
Your connection is not private
Attackers might be trying to steal your information from 151.101.65.195 (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID

Again - it seems to think firebase is involved

**Comment by jschank** [comment]
Ok. So I'm a complete idiot. A long time ago, in a galaxy far away, I set up my resolver to route all dev domains to localhost. (so I could use dev as a development url) 

This article helped me figure out how I did it, in that previous life.
https://superuser.com/questions/1374892/dev-domains-dont-resolve

I'm going to close this because I wasted enough of your time.
