### ISSUE TITLE
Bazel support is not working

### ISSUE THREAD

**Issue by fbaba-nibtravel** [nrwl/nx#3067]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation (nx.dev) and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Based on https://blog.nrwl.io/introduction-to-nrwl-bazel-schematics-c391911a5e9f, running the command `npx create-nx-workspace monorepo-test --bazel` should create the nx workspace with bazel support

## Current Behavior

Running the described command `npx create-nx-workspace monorepo-test --bazel` it throws an exception `Unknown option: '--bazel'`

## Failure Information (for bugs)

``` sh
fernandobaba@Fernandos-MacBook-Pro Personal % npx create-nx-workspace monorepo-test --bazel      
npx: installed 198 in 11.368s
? What to create in the new workspace angular           [a workspace with a single Angular application]
? Application name                    public
? Default stylesheet format           SASS(.scss)  [ http://sass-lang.com   ]
Creating a sandbox with Nx...
warning @angular/cli > universal-analytics > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
new monorepo-test "--bazel" --preset="angular" --appName="public" --style="scss" --interactive=false --collection=@nrwl/workspace
Unknown option: '--bazel'
(node:29214) UnhandledPromiseRejectionWarning: Error: Command failed: "/var/folders/m3/gq94g_3x557f8md6h4mngtt40000gn/T/tmp-29214Ns1ndxIVFH3S/node_modules/.bin/ng" new monorepo-test "--bazel" --preset="angular" --appName="public" --style="scss" --interactive=false --collection=@nrwl/workspace
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at createApp (/Users/fernandobaba/.npm/_npx/29214/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:343:21)
    at /Users/fernandobaba/.npm/_npx/29214/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:76:21
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:29214) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:29214) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install Bazel https://docs.bazel.build/versions/master/install.html 
2. run `npm install -g @bazel/ibazel ` 
3. run `npm install -g @nrwl/schematics`
4. run `npx create-nx-workspace monorepo-test --bazel`

### Context

I've been trying to test the monorepo structure with Bazel support based on https://blog.nrwl.io/introduction-to-nrwl-bazel-schematics-c391911a5e9f 

```
/usr/local/lib
├── @angular/cli@9.1.4
├── @aws-amplify/cli@4.19.0
├── @bazel/ibazel@0.13.1
├── @mobiscroll/cli@1.5.2
├── @nestjs/cli@6.12.9
├── @nrwl/bazel@7.8.7
├── @nrwl/cli@9.3.0
├── @nrwl/nx@7.8.7
├── @nrwl/schematics@8.12.11
├── UNMET PEER DEPENDENCY @schematics/angular@0.7.1
├── @vue/cli@4.3.1
├── aws-cdk@1.38.0
├── commander@2.20.0
├── cypress@4.6.0
├── expo-cli@2.20.0
├── gatsby-cli@2.8.3
├── gulp@4.0.2
├── http-server@0.11.1
├── ionic@5.2.1
├── ios-sim@8.0.1
├── UNMET PEER DEPENDENCY jasmine-marbles@0.6.0
├── lint-staged@10.2.2
├── native-run@0.2.7
├── nightwatch@1.3.4
├── npm@6.14.5
├── npm-check@5.9.2
├── prettier@2.0.5
├── rimraf@2.6.3
├── UNMET PEER DEPENDENCY rxjs@^6.4.0
├── rxjs-tslint@0.1.8
├── tslint@5.20.1
├── typescript@3.6.4
├── web-push@3.3.5
├── webpack@4.41.5
├── webpack-cli@3.3.10
└── yarn@1.21.1

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.4
Node: 12.14.1
OS: darwin x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.901.4
@angular-devkit/core         9.1.4
@angular-devkit/schematics   9.1.4
@schematics/angular          9.1.4
@schematics/update           0.901.4
rxjs                         6.5.4
```

**Comment by FrozenPandaz** [comment]
Hello,

Thank you for your interest in using Bazel with Nx! :smile:. 

Unfortunately, this [blog post](https://blog.nrwl.io/introduction-to-nrwl-bazel-schematics-c391911a5e9f) is outdated and the behavior outlined in the blog post has been deprecated. Sorry for the confusion. I will see about editing the above blog post.

There is currently, no recommended way to integrate Bazel and Nx. We have been exploring new avenues to integrate Bazel with Nx. There is no ETA for when this work will be done.
