### ISSUE TITLE
builder @nrwl/node:package `deleteOutputPath` flag stopped working

### ISSUE THREAD

**Issue by BioPhoton** [nrwl/nx#3068]
THANKS for all the great stuff you ship! <3 <3 <3 

# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Please describe the behavior you are expecting

## Current Behavior

What is the current behavior?

## Failure Information (for bugs)
Since my last update, the `deleteOutputPath` flag stopped working. 

### Steps to Reproduce
I use it to run a separate build process for schematics and builder with a separate tsconfig file and copy the bundles in the folder without deleting the normal build

```json   
"schematics": {
          "builder": "@nrwl/node:package",
          "options": {
            "deleteOutputPath": false,
            "outputPath": "dist/libs/mylib",
            "tsConfig": "libs/mylib/tsconfig.schematics.json",
            "packageJson": "libs/mylib/package.json",
            "main": "libs/mylib/src/index.ts",
            "assets": ["libs/mylib/collection.json"]
          }
        }
```

**Update**
While setting up the reproduction and I realized the option is not present in the schema.json.
Maybe it got removed?

**Comment by FrozenPandaz** [comment]
I'm pretty sure and don't see any history of us having this flag.

Would somebody in the community be interested in adding this flag?

**Comment by BioPhoton** [comment]
Ok. I checked and agree! Was on an "experimental" state on this machine...
Will see if i can contribute 😉!

**Comment by edbzn** [comment]
Hi, I'm willing to add this option. I'm wondering if this should be added to the base [`BuildBuilderOptions`](https://github.com/nrwl/nx/blob/b6ad3b7eaa4c9af55267faf25dd563672f7390ce/packages/web/src/utils/types.ts#L16) for any build target or just the Node one [`BuildNodeBuilderOptions`](https://github.com/nrwl/nx/blob/master/packages/node/src/builders/build/build.impl.ts#L23). What do you think @FrozenPandaz ?
