### ISSUE TITLE
Code coverage paths are broken

### ISSUE THREAD

**Issue by schmkr** [nrwl/nx#3070]
✅ _[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

_I am not 100% this is a bug in `@nrwl/jest`, `jest-preset-angular`, `jest` or one of Jest's dependencies that are responsible for generating the code coverage. I already asked in the [#support-channel on Slack](https://nrwlcommunity.slack.com/archives/CMFKWPU6Q/p1589352981092000), but nobody answered._ 

## Expected Behavior

When running tests with `collectCoverage` enabled, I expect the generated html output to be working.

## Current Behavior

When tests have run, the code coverage overview of a lib or app looks okay, but clicking on a link for a component from that overview, e.g. `lib/awesome-button` to check the button component's coverage, already shows some paths are not resolved correctly, since the next page loses styling. Checking the developer tools, you'll see the base.css file and other assets cannot be found. From that page, clicking on the link to a .ts file, results in a broken link.
 
## Failure Information (for bugs)

First some screenshots:

1. Overview still looks good
![Overview still looks good](https://user-images.githubusercontent.com/612280/82804157-15fc1300-9e82-11ea-8051-0ecded6f0c0f.png)

2. One level deeper, assets cannot be resolved
![One level deeper, assets cannot be resolved](https://user-images.githubusercontent.com/612280/82804259-3fb53a00-9e82-11ea-84d2-c97cd97c4c95.png)

Link to the `awesome-button.component.ts` is broken and results in a 404

The page in screenshot number 2 has its links to the stylesheets defined as:

```
<link rel="stylesheet" href="../../prettify.css" />
<link rel="stylesheet" href="../../base.css" />
```
If they are set to:

```
<link rel="stylesheet" href="../prettify.css" />
<link rel="stylesheet" href="../base.css" />
```

It renders correctly.

The same goes for the links to the coverage page of a component (in this case): On the page in screenshot number 2, it links to `lib/awesome-button.component.ts.html` but it should link to `lib/awesome-button/awesome-button.component.ts.html`.

### Steps to Reproduce

1. `npx create-nx-workspace@latest`
1. `ng generate @nrwl/angular:library --name=ui-components --directory=shared`
1. `ng generate @schematics/angular:component --name=awesome-button --project=shared-ui-components`
1.  add `collectCoverage: true` to `jest.config.js` in the root of the project
1. `nx run-many --all --target test`
1. `npx serve coverage`
1. click to libs -> shared -> ui-components -> lib/awesome-button -> awesome-button.component.ts

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context

Please provide any relevant information about your setup:

```
nx report
  @nrwl/angular : 9.0.2
  @nrwl/cli : 9.0.2
  @nrwl/cypress : 9.0.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.0.2
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.0.2
  @nrwl/web : Not Found
  @nrwl/workspace : 9.0.2
  typescript : 3.7.5
```

```
npm ls --depth=0 | grep jest
├── @nrwl/jest@9.0.2
├── @types/jest@24.0.9
├── jest@24.1.0
├── jest-preset-angular@8.0.0
├── ts-jest@24.0.0
```

### Failure Logs

There aren't any logs for this, but here is the directory layout of `coverage/libs/shared/ui-components`:

```
coverage/libs/shared/ui-components
├── base.css
├── block-navigation.js
├── index.html
├── lib
│   ├── awesome-button
│   │   ├── awesome-button.component.html.html
│   │   ├── awesome-button.component.ts.html
│   │   └── index.html
│   ├── index.html
│   └── shared-ui-components.module.ts.html
├── prettify.css
├── prettify.js
├── sort-arrow-sprite.png
└── sorter.js
```

## Other

I've tried using the `lcovonly` coverage reporter and use `genhtml` to generate a html report from the generated coverage files, but that too seemed to result in similar path errors.

**Comment by FrozenPandaz** [comment]
Sorry I'm not too familiar with the `serve` package but the issue is the URL doesn't have a trailing slash:

http://localhost:5000/libs/products/home-page/lib/home-page/ using `npx serve` works. Perhaps there is an option for including trailing slashes in their directory pages?

On the bright side, would you be open to using the `http-server` package instead? It works properly with this:

```
npx http-server coverage
```

![image](https://user-images.githubusercontent.com/8104246/82839180-83b53880-9e9c-11ea-82ed-c4d015bcddfe.png)

**Comment by schmkr** [comment]
Thanks @FrozenPandaz, using `npx http-server` does indeed result in a fully working experience. I believe I have tried that in the past with similar results.
