### ISSUE TITLE
Issue with nx serve api on windows

### ISSUE THREAD

**Issue by ti0** [nrwl/nx#3072]
## Expected Behavior

I am building a project with NX cli. It has an angualr frontend, a nestjs backend, and a shared types library. I started the project on Ubuntu but now switched to Windows. It worked perfectly when I was running on ubuntu. Both the frontend and api are using the shared types library.

When I run `nx serve frontend` it works fine and launches the server

When I run `nx serve api` on ubuntu, it starts the server fine.

## Current Behavior

When I run `nx serve api` on windows, it is doing something strange where it adds a `../` to the types library and this breaks the build. A sample error:

```
ERROR in ./apps/api/src/app/modules/test/test.controller.ts
Module not found: Error: Can't resolve '../E:\Workspace\xunity\libs\types\src\lib\test\test.dto' in 'E:\Workspace\xunity\apps\api\src\app\modules\test'
```
This same error appears for all references to the types library in the api, I have only provided one error for brevity, but it is the same error repeated with different file names.

## Failure Information (for bugs)

I don't understand why it is prepending the `../` if it is resolving the full path on windows. This seems to be the reason the build is breaking. But for some reason, the frontend app, which also references the same types from the library is building fine. It is only breaking when building the api.

### Steps to Reproduce

Apart from creating a workspace first on Linux, with frontend, api, and types library, and then trying to run on Windows, not sure if there is a way to reproduce this (or if it will reproduce in a brand new project, or if this issue is just specific to my build/project).

### Context

Please provide any relevant information about your setup:

- Latest NX on Windows 10
- Angular + NestJS

### Failure Logs

```
ERROR in ./apps/api/src/app/modules/test/test.controller.ts
Module not found: Error: Can't resolve '../E:\Workspace\xunity\libs\types\src\lib\test\test.dto' in 'E:\Workspace\xunity\apps\api\src\app\modules\test'
```
This same error appears for all references to the types library in the api, I have only provided one error for brevity, but it is the same error repeated with different file names.

**Comment by FrozenPandaz** [comment]
Hi, would you be able to help us help you by providing a repo that we can pull down and see the issue?

**Comment by Cammisuli** [comment]
Hi @ti0 were you able to provide a reproduction? If not we’re gonna have to close this issue 😕
