### ISSUE TITLE
nx build and serve fails to fetch libraries for node apps

### ISSUE THREAD

**Issue by YonatanKra** [nrwl/nx#3074]
## Expected Behavior

I expect to run `nx build my-app` and it will build my app with the dependency libraries.

## Current Behavior

Trying to build the app results in an error:
![image](https://user-images.githubusercontent.com/6459899/82833173-f8509d00-9ec5-11ea-960b-50c431e06f2e.png)

## Failure Information (for bugs)

It started happening suddenly. I get the above error for every library I'm trying to import into my nodejs apps.

### Steps to Reproduce

1. Setup a new empty workspace
2. Install the @nrwl/node
3. Create a new library
4. Create a new app
5. Import the library from the app
6. Try to build or serve the app (e.g. `nx build myApp` or `nx serve myApp`).

I've uploaded the demo repository here: https://github.com/YonatanKra/nx_issue

It's a new workspace - with an untouched lib and an almost untouched app (just changed it to import the lib).
After you clone, yarn or npm install and then try to build the app `reports-api`.

### Context

This has happened both on my Mac as well as on a Windows 10 Laptop.

Please provide any relevant information about your setup:

- version of Nx used (_Please run `nx report` at the root of your workspace and copy the results here if you are using Nx 8.6.1 or greater_)
@nrwl/angular : Not Found
  @nrwl/cli : 9.3.0
  @nrwl/cypress : Not Found
  @nrwl/eslint-plugin-nx : 9.3.0
  @nrwl/express : Not Found
  @nrwl/jest : 9.3.0
  @nrwl/linter : 9.3.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.3.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.3.0
  @nrwl/web : Not Found
  @nrwl/workspace : 9.3.0
  typescript : 3.8.3

**Comment by Cammisuli** [comment]
There's a couple things you can try here:
When doing a build, you can run the following command:
`nx build reports-api --with-deps`

Now it's a bit weird when you do the serve, because there's no serve command for a library, so the `--with-deps` doesn't really work. 

So what you can do instead is this:
Add a new configuration to your build target, with the `buildLibsFromSource` property set to true:
```
"build": {
          "builder": "@nrwl/node:build",
          "options": {
            "outputPath": "dist/apps/reports-api",
            "main": "apps/reports-api/src/main.ts",
            "tsConfig": "apps/reports-api/tsconfig.app.json",
            "assets": ["apps/reports-api/src/assets"]
          },
          "configurations": {
            /// ... production is here as well
            "dev": {
              "buildLibsFromSource": true
            }
          }
```

Then in your `serve` command, change buildTarget from `"buildTarget": "reports-api:build"` to `"buildTarget": "reports-api:build:dev"`. That should then read the source files of dependant libraries and serve everything nicely. 😄 

Let us know if that works out for you 😃

**Comment by YonatanKra** [comment]
Thanks @Cammisuli !
The trick with the `--withDeps` worked for `build` (I forgot to mention that, although I'd mentioned that on slack). It does not work for `serve`.

I'm trying to serve a nodejs app. Is this not possible? Should I do `build --watch` for a nodejs app?

**Comment by Cammisuli** [comment]
@YonatanKra did you try the second solution I provided? You can set flags for specific configurations, and having `buildLibsFromSource` should help your case.

**Comment by YonatanKra** [comment]
@Cammisuli 
Using `buildLibsFromSource` works for the `build` - but not for the `serve`.
The serve still throws the same errors.

**Comment by YonatanKra** [comment]
@Cammisuli - I got it working!
Your solution works - it's just that I forgot to add the custom webpack config inside the file.
Thanks a lot!
