### ISSUE TITLE
Upgrading from AngularJs

### ISSUE THREAD

**Issue by piernik** [nrwl/nx#308]
It's a question...

I have very big project written in `angularJs`. It's a CRM system.
I think it's time to upgrade to `Angular`.
I read Your article: https://blog.nrwl.io/using-nrwl-nx-to-upgrade-you-angularjs-applications-to-angular-f5b8adf188aa
I think that `downgrade` strategy is better for me, but I have no idea how to do it :).

I installed nx workspace and installed `downgradeModule`.
Where should I put my old app files?

In `main.ts` is `import 'app';` but... old app is just javascript file without modules:/
Here is my old `index.html` file (in short):

```
    <link rel="stylesheet" ng-href="/{{app.theme}}.2.6.0.14.css">
    <script src="libs.2.6.0.14.js"></script>
    <script src="scripts.2.6.0.14.js"></script>
    <script src="templates.2.6.0.14.js"></script>
```

I'm stucked.

Maybe You have a sample project for that?

**Comment by ThomasBurleson** [comment]
@piernik - we will work on improving some documentation for this.

**Comment by piernik** [comment]
Great ! When can I expect it? This week or rather this month?
Need to plan my week ;)

**Comment by piernik** [comment]
I found Victors article: https://vsavkin.com/migrating-angular-1-applications-to-angular-2-in-5-simple-steps-40621800a25b

It assumes that `AngularJs` code looks like this: 
```
import * as angular from 'angular'
import 'angular-route'

import {MessagesModule} from './messages';
import {MenuModule} from './menu';
import {SettingsModule} from './menu';

export const Ng1AppModule = angular.module('Ng1AppModule', ['ngRoute', SettingsModule.name, MessagesModule.name, MenuModule.name]);
```
But in reality code looks like this:
```
(function () {
    angular
        .module('app', [
            'app.core',
            'app.common',
            'ncy-angular-breadcrumb',
            'ngAnimate',
            'ngMessages',
            'ngSanitize',
//...
        ])
    ;
})();
```

Is it possible to upgrade from "standard" code not `typescriptish`?

**Comment by BeaveArony** [comment]
Copy your angularjs app to the assets folder.
This workshop project is really useful:
https://github.com/nrwl/tuskdeskjs-angular-upgrade
Go through the commits to follow the steps.

**Comment by madbonez** [comment]
What can i do with separate templates when im upgrading ng1 app? All your examples, that im found, uses inline templates string. require() wont work becouse rollup work, i dont now how. Templates cache is horrible manual rewrite work. Copy and paste html to inline field not handly for support - couse app is big and i cant just rewrite it all. Do  you have any "rigth way"? Maybe i can inject my own build script that is use nodejs usual require html files as string past it in some temp folder then manually call ng-packagr with rigth templates (inlined)
