### ISSUE TITLE
How to remove cypress from nx workspace

### ISSUE THREAD

**Issue by Alex-Zubov** [nrwl/nx#3084]
I want to use codeceptjs instead of cyppress. I've remove all  cypress-related files but in package-lock.json  
"@nrwl/angular": {
      "version": "9.2.4",
      "resolved": "https://registry.npmjs.org/@nrwl/angular/-/angular-9.2.4.tgz",
      "integrity": "sha512-ySaT9hDCEMxdYPQLzOwxYaV94iUsVqUvtEsRXig7PPwCiAojX3bjL04bC0l2RUptQsLfXScow1QA6IM4jyB7cA==",
      "requires": {
        "@angular-devkit/schematics": "~9.1.0",
        "@nrwl/cypress": "9.2.4",
        "@nrwl/jest": "9.2.4",
        "@schematics/angular": "~9.1.0",
        "jasmine-marbles": "~0.6.0"
      }
    },
=============
"@nrwl/cypress": "9.2.4" in reqiuered dependencies. I use azure pipeline and  downloading additional dependencies  impact to running time.

Is there way to remove @nrwl/cypress dependency from  @nrwl/angular?

**Comment by krokofant** [comment]
If you just want to prohibit the downloading of the binaries, which are quite large, you can set the environment variable `CYPRESS_INSTALL_BINARY` to `0`.

**Comment by FrozenPandaz** [comment]
`@nrwl/cypress` doesn't bring in `cypress` so you don't have to be concerned about removing that one.

You can set a default for the application schematics to use "none" for e2e test runner:

workspace.json (at the bottom)
```
  "schematics": {
    "@nrwl/angular:application": {
      "unitTestRunner": "jest",
      "e2eTestRunner": "none"
    },
```
