### ISSUE TITLE
nx format (npm. run format:check|write) not behaving as expected

### ISSUE THREAD

**Issue by tcoz** [nrwl/nx#3090]
I have a repo,  I'm looking at the master branch. I branch it, and want to run code formatting on that branch. There are no commits; the whole point is to format the branch, commit the changes, put out a PR, then commit them to master. 

What I want to do:

- run formatting on a specific project. This project and no other, regardless of commits, staging, etc. I don't want affected computations etc. I just want it to run on a target project in a straightforward way. 

There doesn't appear to be any way to do that. There is an "exclude" option, which I guess would mean I would have to exclude everything except the one project I want to format. I guess a complementary "include" option would be great.

That aside, on to the part that seems to now be working as expected:

When I try using any of the options to control the scope of formatting, I always get this message, and then it just appears to run off and do whatever it wants (by all appearances, format the entire branch in a not-so-easy-to-predict way):

fatal: ambiguous argument 'apps-and-libs': unknown revision or path not in the working tree.

Again, this is true if I use any of the options, for example "head". 

The problem: I want to format the code in a target project. If I have to live with "all apps and libs", that'd not be ideal but I could make it work. However I always get this error if I run any option and the options to control how the formatting behaves do not appear to work. The docs are not very enlightening here. I suspect this is just something I don't know about how the nx/cli commands work with GIT, but as for now I'm at a bit of a loss. By all appearances the format command just doesn't seem to work as documented without errors.

**Comment by FrozenPandaz** [comment]
Hi,

So for the first part, I see you want a `--project` option where you can specify which project you want to format without any affected calculations. Is that right?

For the second part, the commands limit the scoping of the formatting properly for me. Can you post the exact command that you are running?

**Comment by bekos** [comment]
@tcoz You can now use the `--projects` options. I hope this solves your issue, if not feel free to open a new one.
