### ISSUE TITLE
nx build --with-deps is a no-op on deps

### ISSUE THREAD

**Issue by cdaringe** [nrwl/nx#3097]
## Current Behavior

`nx build --with-deps` just executes `build`, as though `--with-deps` wasn't present

## Expected Behavior

`--with-deps` to propagate to build targets

## Steps to Reproduce

- enter a nx project
- `npx nx build --with-deps`
- observe no deps built

### Failure Logs

n/a

### Environment

```

>  NX  Report complete - copy this into the issue template

  @nrwl/angular : Not Found
  @nrwl/cli : 9.3.0
  @nrwl/cypress : 9.3.0
  @nrwl/eslint-plugin-nx : 9.2.4
  @nrwl/express : Not Found
  @nrwl/jest : 9.2.4
  @nrwl/linter : 9.2.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.2.4
  @nrwl/react : 9.3.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.3.0
  @nrwl/web : 9.3.0
  @nrwl/workspace : 9.3.0
  typescript : 3.9.3

```

**Comment by FrozenPandaz** [comment]
Hi,

Please provide a repo exhibiting the issue so that we have more information about the issue.

**Comment by cdaringe** [comment]
@FrozenPandaz, i'm happy to build a repro. to make sure the repro sufficiently demonstrates the issue, perhaps you can help me out by clarifying what doesn't make sense in the description? if i send a new git url--we'll still need to be aligned on the above description (which is that `--with-deps` doesn't ensure all dependents are built for a project with a plain-jane call to `nx build`)

**Comment by cdaringe** [comment]
@FrozenPandaz reproduction: https://github.com/cdaringe/nxtester/tree/demo/build-with-deps-fail

**Comment by jorgekleeen** [comment]
Same problem here +1

**Comment by llwt** [comment]
@FrozenPandaz Any thoughts on this one?

**Comment by vsavkin** [comment]
Hi folks! I believe this issue has been fixed. Could you try Nx 10?
