### ISSUE TITLE
Storybook Configuration (with NX)

### ISSUE THREAD

**Issue by kevinjeong-accenture** [nrwl/nx#3107]
![image](https://user-images.githubusercontent.com/60707986/83668759-15583080-a596-11ea-8948-8ca1311036a6.png)

![image](https://user-images.githubusercontent.com/60707986/83669143-afb87400-a596-11ea-9192-f52e1d8a15b1.png)

The context for routes with the regex is picking up more files than it should. Even though we added strict grammar to only pick up story files, it retrieves spec files as well. We believe this is due to the fact that it is going into other tsconfig files or doing something strange.

**Comment by juristr** [comment]
@kevinjeong-accenture Hi, could you provide us with some repro steps that detail what exactly is wrong? Ideally providing us a GitHub repo with the wrong behavior 🙏.

Also, could you verify this issue still persists with our latest `v10.1.0`?

**Comment by mandarini** [comment]
Hi there @kevinjeong-accenture ! Do you have any update on this? Did you try it out with the latest version of Nx?
