### ISSUE TITLE
Webpack 5 / Module Federation

### ISSUE THREAD

**Issue by StevenLangbroek** [nrwl/nx#3116]
## Description

Webpack 5 has a new feature called Module Federation (I'm sure it's caught some folks' attention by now), allowing you to at runtime import parts of bundles from other applications. I could see this slotting into `nx` quite neatly, for example by allowing the `exposes` property of the plugin to be set in `nx.json`:

```json
{
  "projects": {
    "chrome": {
      "exposes": {
        "AppContainer": "src/App.tsx"
      },
      "tags": []
    },
    "chrome-e2e": {
      "tags": [],
      "implicitDependencies": ["chrome"]
    },
    "settings": {
      "tags": [],
      "exposes": {
        "Settings": "src/Settings.tsx"
      }
    }
  }
}
```

I tried looking for an existing issue but couldn't find any, so thought it would be worth bringing up. Would love to hear what you think about Module Federation in general, and what it could mean for NX. Thanks <3

Some links:
- [Documentation](https://webpack.js.org/concepts/module-federation/)
- [Demo](https://github.com/mizx/mfe-webpack-demo)

**Comment by Vynlar** [comment]
Just wanted to leave my two cents on this topic:

My current project demands that we are able to independently deploy + load each individual page of our SPA. As far as I can tell, Nx lets you build each app independently but that does not allow me to build each page independently. I can simply use module federation in a typical monorepo but Nx's tools around tracking "affected" modules is incredibly nice. I would love to be able to take advantage of both module federation (for independently deployability/runtime composition) alongside the great developer experience that Nx is known for.

Does anyone have a sense of how difficult it would be to accomplish this?

**Comment by smasala** [comment]
Agree with @Vynlar. This would be a huge game changer in terms of creating isolated buildable and deployable apps which can then be part of a single and larger SPA.

**Comment by jandvik-tbc** [comment]
> Just wanted to leave my two cents on this topic:
> 
> My current project demands that we are able to independently deploy + load each individual page of our SPA. As far as I can tell, Nx lets you build each app independently but that does not allow me to build each page independently. I can simply use module federation in a typical monorepo but Nx's tools around tracking "affected" modules is incredibly nice. I would love to be able to take advantage of both module federation (for independently deployability/runtime composition) alongside the great developer experience that Nx is known for.
> 
> Does anyone have a sense of how difficult it would be to accomplish this?

I have the same requirement. Unless a plugin or other solution to this becomes available in the next few, I'll have to move forward without using Nx 😢. We will be building one central Micro FE component library that will be used by multiple sites, all of which will also have to be Micro FE, using the component library. Webpack 5 Module Federation + Nx would be perfect for this.

**Comment by ashinga48** [comment]
+1 for any pointers to develop this.

**Comment by luke-siedle** [comment]
As far as I know, Webpack 5 is not yet supported in nx.dev, although Next 10 has support for it.  Any news on when Webpack 5 support might land?

**Comment by jeffgaynorspok** [comment]
I'll mirror the importance of these requests. We are looking to move our frontend to leverage NX + Single SPA + Webpack 5 Module Federation for micro-frontends. Any additional support for custom webpack configs per application and to easily export into separate NPM packages if needed would be spectacular.

**Comment by MaurizioCasciano** [comment]
This link explains how to use Module Federation in a NX Monorepo
[Angular Architects](https://www.angulararchitects.io/aktuelles/using-module-federation-with-monorepos-and-angular/)

**Comment by jeffgaynorspok** [comment]
> This link explains how to use Module Federation in a NX Monorepo
> [Angular Architects](https://www.angulararchitects.io/aktuelles/using-module-federation-with-monorepos-and-angular/)

@MaurizioCasciano Thanks for the link. I'll read through this thoroughly to see if I can make it work with React, as we don't use Angular.

**Comment by MitkoTschimev** [comment]
@jeffgaynorspok Had you luck with a working setup?

**Comment by jeffgaynorspok** [comment]
> @jeffgaynorspok Had you luck with a working setup?

@MitkoTschimev I have a work-in-progress setup that functions with NX, Single SPA, and React Applications with Webpack 4.42.0 (currently shipped with NX). I got too many errors with Webpack 5. I will attempt again with Webpack 5 once I have a clean setup.

**Comment by MitkoTschimev** [comment]
Same happened for me. I will wait till nx supports webpack 5 with Next and react.

**Comment by ebrehault** [comment]
For anyone interested, here is a working of nx+angular+webpack 5 module federation https://github.com/ebrehault/micro-frontend-with-nx

**Comment by MitkoTschimev** [comment]
Yes but that's just the case for angular I guess

**Comment by mohammedzamakhan** [comment]
It would be great to use module federation in Nx when you have the workspace build with Vue/React instead of Angular, right now module federation can be used in Nx with only Angular.

**Comment by vanuj** [comment]
We have started a multi repo project using Webpack 5 and planning to leverages advantages of Nx.
Any idea by when Webpack 5 (module federation) support would be there in Nx ?

**Comment by mohammedzamakhan** [comment]
@FrozenPandaz can you remove the stale tag from this issue?

**Comment by smasala** [comment]
Not a plugin but is able to recognise the applications and place the webpack configurations correctly within the NX Monorepo: https://github.com/angular-architects/module-federation-plugin

**Comment by mohammedzamakhan** [comment]
@smasala we all know about this plug-in, which only works for angular applications in NX, not React or Vue apps

**Comment by elenasch** [comment]
We too are building React apps with webpack 5 and Module Federation plugin. Would love to be able to use Nx, but right now not having the webpack 5 support for React apps is a blocker

**Comment by aGoncharuks** [comment]
Would be good to know if Webpack 5/Module federation support is on the roadmap this year.

**Comment by georgewilde** [comment]
Just wanted to add to the weight of people looking for this functionality. I currently have multiple repos each with a single-spa react application using Webpack 5. I'm currently unable to take advantage of Nx to bring these repos together into a single repo because of the lack of support for Webpack 5. I'd really like to see this functionality added and if there's anything I can do to help with that, just let me know.

It would be helpful to know if this support is on the Nx roadmap to help plan future architecture decisions.

**Comment by firxworx** [comment]
Just setup nx for the first time... And discovered no webpack 5... Blocker for me too re NextJS projects.

**Comment by vitorcamachoo** [comment]
Any new about webpack 5 integration?

**Comment by crates** [comment]
@firxworx / @vitorcamachoo / @agoncharuks / @georgewilde / @elenasch / @vanuj:

Webpack 5 is on the Nx roadmap, slated for release with version 13 in October of this year.

**Comment by willgm** [comment]
AngularCLI v12 released a production ready version of Webpack 5 support, so I believe it should be easier to build up from and give support for Module Federation to all the flavors.

**Comment by bwcgn** [comment]
It seems to have been released already? https://nx.dev/latest/react/guides/webpack-5#webpack-5-migration
Anyone has tried it?

**Comment by willgm** [comment]
Nx does seams to support Webpack 5 / Module Federation, but at least for now looks like it just for Angular:
https://nx.dev/latest/react/angular/setup-mfe#nrwlangularsetup-mfe

I would like to know if this support will come to React and Next apps as well.

**Comment by wootencl** [comment]
This was fairly helpful to me for getting things working: https://github.com/Pkearney2021/nx-module-federation-webpack5

I'd still advocate a turn key solution though as Angular has on offer.

**Comment by crates** [comment]
This is standard in the latest version of Nx. Time to close this issue!

**Comment by StevenLangbroek** [comment]
@crates did you read the discussion? is there any writing as to plans for React / other framework support?

**Comment by crates** [comment]
@StevenLangbroek - I've read most of what's here and also played around a bit with the plugin provided by Nx for module federation with Angular. The bulk of the work here is done, although admittedly there aren't yet schematics for spinning up new React components ready to be exported as module federation guests. Still, I'd content that Nx fully supports this at the current time. Adding schematics for React is a pretty small task and (arguably) separate from the issue of broader support for the protocol itself. Moreover, enabling components to be imported as guests via mod fed is done; all you need to do is bundle them like you would normally and add them to your webpack config as remote imports.
