### ISSUE TITLE
Only populate dependencies related to the entry file when build lib.

### ISSUE THREAD

**Issue by Stupidism** [nrwl/nx#3117]
## Current Behavior

build web:package is populating npm dependencies of all the files inside `src`

## Expected Behavior

only populate  npm dependencies of those files who is imported by the entry file

## Steps to Reproduce

1. Create a lib with storybook integrated

2. use some other npm dependency, which is not used by the lib source code, like `styled-component` to write a story.

3. run build command. you will see unexpected dependency like this

![image](https://user-images.githubusercontent.com/5801015/83851677-4e82d300-a745-11ea-9e0e-0ce120313dc8.png)

![image](https://user-images.githubusercontent.com/5801015/83851922-9d306d00-a745-11ea-8902-8eacd3327d0f.png)

### Environment

```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : Not Found
  @nrwl/cli : 9.3.0
  @nrwl/cypress : 9.3.0
  @nrwl/eslint-plugin-nx : 9.3.0
  @nrwl/express : Not Found
  @nrwl/jest : 9.3.0
  @nrwl/linter : 9.3.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 9.3.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.3.0
  @nrwl/web : 9.3.0
  @nrwl/workspace : 9.3.0
  typescript : 3.8.3
```

**Comment by Stupidism** [comment]
It seems I only need to add stories in the exclude field in tsconfig.json

**Comment by FrozenPandaz** [comment]
This might be hard to solve programmatically. Does anybody have a suggestion for how to do this explicitly? Maybe like an 
 `"excludeDependencies"` option for the builder to not add to dependencies?

**Comment by Stupidism** [comment]
> It seems I only need to add stories in the exclude field in tsconfig.json

It's solved already. Not automatically, but manually add path match in exclude field in tsconfig.json
