### ISSUE TITLE
How to config React frontend application completely dev-server proxy?

### ISSUE THREAD

**Issue by doudounannan** [nrwl/nx#3119]
## Current Behavior

I only have an React frontend application completely, backend API is separated from my frontend application, I hope forwarding interface fetching to backend API such as: forward */api* to *http://domain3.domain2.com/path/api*, but I can't find any solution to solve this?

## Expected Behavior

forwarding interface fetching to backend API

## Steps to Reproduce

[github's project address](https://github.com/doudounannan/nx-demo)

```bash
$ yarn start nx-demo
```

**Comment by FrozenPandaz** [comment]
This is already available. :)

In your project's `serve` configuration you can add:

```
            "proxyConfig": "apps/app1/proxy.conf.json"
```

And such file looks like the following:

```
{
  "/api": {
    "target": "http://localhost:3333",
    "secure": false
  }
}
```

**Comment by raviSussol** [comment]
Hi, how to set proxy config for a production build react app? For a dev environment (serving) config works but for a production build - not working.

I've set proxy config something like below:
```
"build": {
      "executor": "@nrwl/web:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "proxyConfig": "apps/frontend/proxy.config.json",
        "outputPath": "dist/apps/frontend",
        "index": "apps/frontend/src/index.html",
        "baseHref": "/",
        ...
      }
    }
```
and in dev:
```
"serve": {
      "executor": "@nrwl/web:dev-server",
      "options": {
        "buildTarget": "frontend:build",
        "proxyConfig": "apps/frontend/proxy.config.json",
        "hmr": true
      }
   }
```

**Comment by gitsome** [comment]
As @raviSussol shows above, ensure to put the "proxyConfig" in the json located in this path and json section: `client project` > `project.json` > `serve` > `options`.

**Comment by raviSussol** [comment]
@gitsome I think that only works for a dev environment (i.e. while serving). For a production build it doesn't work (or not working). Is that settings working for you in a production build?

**Comment by LorenzoVianello** [comment]
@raviSussol I've your same problem.
I've added proxyConfig even inside build options, but proxy cannot be set :/
In dev-only works perfectly,  but i'm now stuck with build

**Comment by pjw9963** [comment]
Does anyone have a work around for this? Kinda important for my builds to use the production api url
