### ISSUE TITLE
Schematic error generating lazy library

### ISSUE THREAD

**Issue by ThomasBurleson** [nrwl/nx#312]
On the nrwl.io site - using Angular CLI 1.7.2 and @nrwl/schematics 0.8.0 - using the following command:

```console
ng generate lib team --routing --lazy --parentModule=apps/nrwl.io/src/app/app.module.ts
```

Adds the following *incorrect* entry into `app/app.module.ts`:

```js
{ path: 'team', loadChildren: '@undefined/team#TeamModule' }
```

the entry should be `@nrwlio/team#TeamModule`.

May be releated to #303

**Comment by FrozenPandaz** [comment]
This does not affect new projects. We default the value of `npmScope` now but we could add a migration to solve this problem for older projects.

**Comment by vsavkin** [comment]
As @FrozenPandaz pointed out the issue is with a missing npmScope. We added a check to throw an exception if npmScope is not defined, so this should no longer be a problem.
