### ISSUE TITLE
Cannot convert Angular CLI workspace to Nx Workspace if Angular CLI workspace was created with --create-application=false

### ISSUE THREAD

**Issue by Qarun-Qadir-Bissoondial** [nrwl/nx#3128]
## Current Behavior
An Angular workspace initially created with `ng new workspace_name --create-application=false` and later has applications and libraries added to it fails to be converted to an Nx Workspace when running `ng add @nrwl/workspace` as per [Transitioning to Nx](https://nx.dev/angular/migration/migration-angular#using-ng-add).

Additionally, under trying to create a new nx workspace manually as per [here](https://nx.dev/angular/migration/migration-angular#transitioning-manually), the following errors were produced: 

```
npm init nx-workspace @ngx-abstractions --preset=angular
npx: installed 198 in 12.351s
? Application name                    forms-test
? Default stylesheet format           CSS
Creating a sandbox with Nx...
added 401 packages from 239 contributors and audited 401 packages in 8.74s

23 packages are looking for funding
  run `npm fund` for details

found 4 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
new @ngx-abstractions --preset="angular" --appName="forms-test" --style="css" --interactive=false --collection=@nrwl/workspace
An unhandled exception occurred: Collection "@nrwl/workspace" cannot be resolved.
See "/tmp/ng-hbZxav/angular-errors.log" for further details.
(node:17049) UnhandledPromiseRejectionWarning: Error: Command failed: "/tmp/tmp-17049nHkeVwOf9goV/node_modules/.bin/ng" new @ngx-abstractions --preset="angular" --appName="forms-test" --style="css" --interactive=false --collection=@nrwl/workspace
    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:647:15)
    at createApp (/home/qarunqb/.npm/_npx/17001/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:343:21)
    at /home/qarunqb/.npm/_npx/17001/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:76:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:17049) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:17049) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Others have pointed out that the solution to my problem creating a new Nx workspace from scratch was to install Nrwl Workspace globally, but it did not help in my case.

## Expected Behavior
An Angular workspace initially created with `ng new workspace_name --create-application=false` and then later has applications and libraries added to it is expected to be converted to an Nx Workspace.

## Steps to Reproduce
**Step that works**:

1. `ng new appName`
2. `cd appName`
3. `ng add @nrwl/workspace`

**Step that doesn't work (application):**:
1. `ng new workspace_name --create-application=false`
2. `cd workspace_name`
3. `ng generate application app1`
4. `ng add @nrwl/workspace`.

Step 4 produces the following output:

```
Skipping installation: Package already installed
    Renamed projects/app1/tsconfig.app.json -> apps/app1/tsconfig.app.json
    Renamed projects/app1/karma.conf.js -> apps/app1/karma.conf.js
    Renamed projects/app1/tsconfig.spec.json -> apps/app1/tsconfig.spec.json
    Renamed projects/app1/src -> apps/app1/projects/app1/src
    Path: e2e does not exist
```

**Step that doesn't work (library):**

1. `ng new workspace_name --create-application=false`
2. `cd workspace_name`
3. `ng generate library test`
4. `ng add @nrwl/workspace`

Step 4 produces the following output:
```
Skipping installation: Package already installed
    Renamed projects/test/tsconfig.lib.json -> apps/test/tsconfig.lib.json
    Renamed projects/test/karma.conf.js -> apps/test/karma.conf.js
    Renamed projects/test/tsconfig.spec.json -> apps/test/tsconfig.spec.json
    Renamed projects/test/src -> apps/test/projects/test/src
    No e2e project was migrated because there was none declared in angular.json
Cannot set property 'outDir' of undefined

```

### Environment
```
Angular CLI: 9.1.7
Node: 13.13.0
OS: linux x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.7
@angular-devkit/build-angular      0.901.7
@angular-devkit/build-ng-packagr   0.901.7
@angular-devkit/build-optimizer    0.901.7
@angular-devkit/build-webpack      0.901.7
@angular-devkit/core               9.1.7
@angular-devkit/schematics         9.1.7
@angular/cli                       9.1.7
@ngtools/webpack                   9.1.7
@schematics/angular                9.1.7
@schematics/update                 0.901.7
ng-packagr                         9.1.5
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
@nrwl/angular                      9.3.0
@nrwl/workspace                    9.3.0
```

The above problem description means that the only way I can create an Nx workspace is to create an Angular CLI project with an application by default, transition that to an Nx workspace and, if I want to add existing applications and libraries, I have to create apps and libs with the same name in the Nx workspace and then manually transfer them over.

It means I'm not able to:
 - Migrate any Angular CLI project containing applications and libs as long as the workspace started off with `--create-application=false`
 - Start a new Nx workspace from scratch and then add applications and libs.

**Comment by Qarun-Qadir-Bissoondial** [comment]
I've made some progress in understanding why the `Path: e2e does not exist`. The following was done on an Angular Workspace containing both an application and a library. 

It seems as though Nx is looking for an `e2e` key under the `architect` section of each project in `angular.json`. A library is not generated with this and thus, the error is thrown.

I've manually added in `e2e` under the `architect` section of my library project definition of my angular.json as follows (I've left it empty just to see what happens):

```
 "e2e": {
          "builder": "",
          "options": {
            "protractorConfig": "",
            "devServerTarget": ""
          },
          "configurations": {
            "production": {
              "devServerTarget": ""
            }
          }
        },
```

The following error resulted when running `ng add @nrwl/workspace`:

```
Skipping installation: Package already installed
    Make sure the forms.architect.e2e.options.protractorConfig is valid or the forms project is removed from angular.json.
    An e2e project was specified but  could not be found.
    Your workspace could not be converted into an Nx Workspace because of the above error.
An e2e project was specified but  could not be found.
```

This means that Nx is searching for an `e2e` project. What puzzles me is when this library is removed and only the application remains (this has proper e2e config in the package.json), the `Path: e2e does not exist` error was still generated. (Note, I ran `ng e2e` for the default protractor test that comes with a new application in an Angular Workspace and the test passed with no problems.)

**Comment by Qarun-Qadir-Bissoondial** [comment]
Even stranger, when I have the correct `e2e` config for an application in my `angular.json`, Nx complains about not finding it, but if i delete it from angular.json, then the migration into an Nx workspace works successfully and `nx.json` has `undefined-e2e` as the e2e for the application. 

I guess I managed to get my workspace converted to an Nx workspace but the issue of Nx throwing an `e2e` path error even when the path is correct, that issue still remains so I'm still leaving this issue open in hopes that someone sees it. Hopefully I'm not the only one with this error.

**Comment by brandonroberts** [comment]
Fixed in https://github.com/nrwl/nx/pull/4043

**Comment by ArkasDev** [comment]
@Qarun-Qadir-Bissoondial I have the same error.
