### ISSUE TITLE
【last reply not resolve the problem】How to config React frontend application completely dev-server proxy?

### ISSUE THREAD

**Issue by doudounannan** [nrwl/nx#3133]
I can't reopen the last same issue closed by @FrozenPandaz , his reply can't resolve the issue
## Current Behavior

I only have an React frontend application completely, backend API is separated from my frontend application, I hope forwarding interface fetching to backend API such as: I fetch *giphy* API *https://api.giphy.com/v1/gifs/search?api_key=dc6zaTOxFJmzC&q=cat*
(libs/gifs/src/lib/gifs.tsx line 15). In my project's serve configuration has added

```config
"proxyConfig": "apps/nx-demo/proxy.conf.json"
```
forward */v1/gifs* to *https://api.giphy.com* (apps/nx-demo/proxy.conf.json) 

```config
{
  "/v1/gifs": {
    "target": "https://api.giphy.com",
    "secure": false
  }
}
```

console log

```bash
[HPM] Error occurred while trying to proxy request /v1/gifs/search?api_key=dc6zaTOxFJmzC&q=cat from localhost:4200 to https://api.giphy.com (ENOTFOUND) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

but it doesn't work, why?

## Expected Behavior

forwarding interface fetching to backend API

## Steps to Reproduce

[github's project address](https://github.com/doudounannan/nx-demo)

```bash
$ yarn start nx-demo
```

**Comment by FrozenPandaz** [comment]
You have to change the origin of the header.

```
{
  "/v1/gifs": {
    "target": "https://api.giphy.com",
    "secure": false,
    "changeOrigin": true
  }
}
```

You can read more about it here:
https://webpack.js.org/configuration/dev-server/#devserverproxy
