### ISSUE TITLE
Cleanup way of mocking fetch when generating a new react-express preset

### ISSUE THREAD

**Issue by sketchnotes** [nrwl/nx#3137]
## Current Behavior
When the projects are generated from an empty presets, e.g. @nrwl/react:app (frontend) and @nrwl/express:app (backend) `fetch` can be used in the code without issue, nevertheless it generates an error during the test. There's also no link to `note-fetch` nowhere in the project.

In the case of using a `react-express` preset, there's no such issue and the link to `note-fetch` can be found in `yarn.lock`

## Expected Behavior
 - broken test

## Steps to Reproduce
1. Clone the repo: https://github.com/sketchnotes/issue-nx-fetch
2. install packages
3. run: nx test

### Failure Logs
![Screenshot from 2020-06-08 23-02-30](https://user-images.githubusercontent.com/60486879/84075067-2bbe1c00-a9dc-11ea-8e65-0cc55d374bc2.png)
```
...
console.error
    The above error occurred in one of your React components:
        in Unknown
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

      at logCapturedError (../../node_modules/react-dom/cjs/react-dom.development.js:21843:13)
      at logError (../../node_modules/react-dom/cjs/react-dom.development.js:21880:5)
      at update.callback (../../node_modules/react-dom/cjs/react-dom.development.js:23232:5)
      at callCallback (../../node_modules/react-dom/cjs/react-dom.development.js:13829:12)
      at commitUpdateEffects (../../node_modules/react-dom/cjs/react-dom.development.js:13867:7)
      at commitUpdateQueue (../../node_modules/react-dom/cjs/react-dom.development.js:13855:3)
      at commitLifeCycles (../../node_modules/react-dom/cjs/react-dom.development.js:22160:11)

  console.error
    Error: Uncaught [ReferenceError: fetch is not defined]
...
```
### Environment

  @nrwl/angular : Not Found
  @nrwl/cli : 9.3.0
  @nrwl/cypress : 9.3.0
  @nrwl/eslint-plugin-nx : 9.3.0
  @nrwl/express : 9.3.0
  @nrwl/jest : 9.3.0
  @nrwl/linter : 9.3.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.3.0
  @nrwl/react : 9.3.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.3.0
  @nrwl/web : 9.3.0
  @nrwl/workspace : 9.3.0
  typescript : 3.8.3

**Comment by FrozenPandaz** [comment]
So `--preset react-express` is close to but not exactly identical to generating a react app and express app with the --frontendProject flag. We also add these few lines to the test file for that preset.

```
  afterEach(() => {
    delete global['fetch'];
    cleanup();
  });

  it('should render successfully', async () => {
    global['fetch'] = jest.fn().mockResolvedValueOnce({
      json: () => ({
        message: 'my message'
      })
    });
```

Now... that is definitely not a clean way of mocking fetch and I'm going to edit this issue to find and implement a better way of making those tests pass..
