### ISSUE TITLE
Generate i18n configuration along with app generation

### ISSUE THREAD

**Issue by KyleBastien** [nrwl/nx#3138]
## Description
Similar to picking which type of styles (i.e. CSS, styled-components, etc.) you want to be generated along with your app, I think it would make sense to generate an i18n configuration along with that app.

## Motivation
I believe this would be beneficial because i18n and localization are basic necessities of almost any enterprise application. Since Nx is trying to target an audience where you can build like Google, Microsoft, etc., I think having the ability to have an i18n configuration out of the box with a generated app is a necessity.

I think this is possible to do today if you write your own serve builder, and schematic, but I think this should really come out of the box with any generated Nx app.

## Suggested Implementaion
I would imagine that when generating an app you would get an option between a few popular i18n libraries (i.e. react-i18next, Angular i18n, etc.) and then your app would be generated with the appropriate i18n configuration file, and an empty i18n strings file.

Your app would also automatically be configured with a proxy which listened for the appropriate `/locales/add` request, so that any keys that haven't been previously saved to the i18n strings file, will automatically be saved.

## Alternate Implementations
I could also imagine this being a plugin which you could apply after the app is generated which adds i18n to your application. I think the problem with this today is that is requires building your own serve builder which starts up the Express server which can listen for `/locales/add`. Ideally I would think users would want to stick with the @nrwl/web:dev-server builder, instead of a wrapper.

**Comment by s4m0r4m4** [comment]
I wouldn't label this as only scope: react, it would be nice to support angular here too, espeically with their i18n built-in capabilities.
