### ISSUE TITLE
Convert cli project error

### ISSUE THREAD

**Issue by FallenRiteMonk** [nrwl/nx#314]
Converting an existing cli project leads to a lint error.
```error TS5058: The specified path does not exist: '<OLD_PROJECT_PATH>/tsconfig.e2e.json'.```

The '.angular-cli.json' file contains the following entries under 'lint':

```js
{
     "project": "<NEW_PROJECT_PATH>/src/tsconfig.app.json",
      "exclude": "**/node_modules/**"
},
{
      "project": "./tsconfig.spec.json",
      "exclude": "**/node_modules/**"
},
{
      "project": "<OLD_PROJECT_PATH>/tsconfig.e2e.json",
      "exclude": "**/node_modules/**"
}
```
but should contain:
```js
{
     "project": "<NEW_PROJECT_PATH>/src/tsconfig.app.json",
      "exclude": "**/node_modules/**"
},
{
      "project": "./tsconfig.spec.json",
      "exclude": "**/node_modules/**"
},
{
      "project": "<NEW_PROJECT_PATH>/e2e/tsconfig.e2e.json",
      "exclude": "**/node_modules/**"
}
```

**Comment by FallenRiteMonk** [comment]
I further noticed that the app is missing the 'NxModule.forRoot()' import.

**Comment by ThomasBurleson** [comment]
@FallenRiteMonk - are you using @nrwl/schematics 0.8.0 with Angular CLI 1.7.x ?

**Comment by FallenRiteMonk** [comment]
Jep ```"@nrwl/schematics": "^0.8.0"``` and ```"@angular/cli": "^1.7.0"```.
This is what ```ng g workspace``` command added for me.

**Comment by FrozenPandaz** [comment]
I can take this
