### ISSUE TITLE
build by '@nrwl/node:package' does not exclude node_modules

### ISSUE THREAD

**Issue by Aniket-Engg** [nrwl/nx#3142]
I am getting this issue while trying to build a node lib

## Current Behavior
on running `nx build <lib_name>`, it shows: `Maximum call stack size exceeded`.

If I remove `node_modules` folder inside lib, it works fine.

## Expected Behavior
It should run build command without any issue.

## Steps to Reproduce
My configuration:
```
"build": {
          "builder": "@nrwl/node:package",
          "options": {
            "outputPath": "libs/<lib_name>/dist",
            "tsConfig": "libs/<lib_name>/tsconfig.lib.json",
            "packageJson": "libs/<lib_name>package.json",
            "main": "libs/<lib_name>/src/index.ts",
            "updateBuildableProjectDepsInPackageJson": false,
            "exclude": ["**/node_modules/**"],
            "assets": ["libs/<lib_name>/*.md"]
          }
        }

```
Run `nx build <lib_name>`

### Environment
```
% nx report

>  NX  Report complete - copy this into the issue template

  @nrwl/angular : Not Found
  @nrwl/cli : 9.2.4
  @nrwl/cypress : Not Found
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.3.0
  @nrwl/linter : 9.3.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.3.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.4
  @nrwl/web : Not Found
  @nrwl/workspace : 9.2.4
  typescript : 3.8.3
```

Let me know if any more details are required.

**Comment by Aniket-Engg** [comment]
Has it been resolved?

**Comment by Cammisuli** [comment]
oh sorry about that! Can you provide a reproduction repo? 

But from what I see from the description is that you have node_modules inside a lib folder. So you have at least two node_modules folder in your workspace? If that's the case, why?

**Comment by Aniket-Engg** [comment]
There can be a possibility that we have a dep in root package.json and that is not included in lib's package.json.

`node_modules` inside lib folder is required to test if package has all the required dependency as it is published individually as an NPM module.

**Comment by Cammisuli** [comment]
Fair enough. Can you provide a reproduction and I can see what's up?

**Comment by Aniket-Engg** [comment]
I will be difficult to provide a repo, still I will check at my end. 

Basically the issue was that it was also processing node_modules files while running the build of lib and subsequently resulting in the `Maximum call stack size exceeded.` error.
