### ISSUE TITLE
@storybook/docs doesn't work

### ISSUE THREAD

**Issue by sl-benjamindupuy** [nrwl/nx#3147]
Hi !

I use the storybook with NX and it works well overall by cons I can not use the docs addon https://github.com/storybookjs/storybook/tree/master/addons/docs/angular
No error but it shows me "no docs" in the corresponding tab.
Exactly the same worries as https://github.com/storybookjs/storybook/issues/9103
The new configuration could solve the problem but nx does not support it at the moment...

Thanks

**Comment by juristr** [comment]
Related PR: https://github.com/nrwl/nx/pull/2882
