### ISSUE TITLE
How to  only configure to  build field deployUrl in production environment?

### ISSUE THREAD

**Issue by doudounannan** [nrwl/nx#3148]
How to  only configure to  build field deployUrl in production environment?

## Current Behavior
can't find where to configure

## Expected Behavior

eg: 
deployUrl: /blog
in non-production environment
index.html includes <script src="main.[hash].esm.js" type="module">
in production environment
index.html includes <script src="/blog/main.[hash].esm.js" type="module">

## Steps to Reproduce

[my github's repo](https://github.com/doudounannan/nx-demo)

**Comment by FrozenPandaz** [comment]
You would want to add it to this set of configuration here:

https://github.com/doudounannan/nx-demo/blob/master/workspace.json#L27

Read more about the Workspace Configuration here: https://nx.dev/react/workspace/configuration#targets
