### ISSUE TITLE
bundle js inject to index.html  type="text/JavaScript" instead of  type="module"

### ISSUE THREAD

**Issue by doudounannan** [nrwl/nx#3149]
How to bundle js inject to index.html  type="text/JavaScript" instead of  type="module"?

## Current Behavior
can't find where to configure

## Expected Behavior

eg: 
index.html includes <script src="main.[hash].esm.js" type="text/javascript"> not <script src="main.[hash].esm.js" type="module">

## Steps to Reproduce

[my github's repo](https://github.com/doudounannan/nx-demo)

**Comment by FrozenPandaz** [comment]
Setting `type="text/javascript"` is not recommended per the HTML5 spec. https://html.spec.whatwg.org/dev/scripting.html#attr-script-type

In production bundles, there are 2 tags.. 1 for es5 and 1 for esm:

```
<script src="main.06b33e9a637ea86fbc12.esm.js" type="module">
</script><script src="main.7b168a6aa1a58566fc20.es5.js" nomodule defer></script>
```
Allowing users on modern browsers to download less code :tada: 

Is there a particular reason why you need the attribute to be there?

**Comment by doudounannan** [comment]
@FrozenPandaz `yarn build <app's name> --prod`, there aren't 2 tags, only 1 for esm, like below
```html
<script src="runtime.a38b665096a19e60b337.js" type="module"></script><script src="polyfills.043045065551225889db.esm.js" type="module"></script><script src="main.9262a9a76c2de513fe32.esm.js" type="module"></script>
```

**Comment by BigAB** [comment]
Depending on the browser support specified in the `.browserslistrc`file, if you don't support any browsers that can't load ESModules (with the `type="module"` attribute), we only build the module versions.

Maybe you need to adjust the `.browserslistrc` file to include support for older on non-compliant browsers?
([more info on that](https://github.com/browserslist/browserslist))
