### ISSUE TITLE
Cache mechanist isn't working in case the project folder is different from libs

### ISSUE THREAD

**Issue by mauriziovitale** [nrwl/nx#3151]
## Current Behavior
Not able to cache the build of libs in case the folder isn't called `libs` 

## Expected Behavior
It should be possible to cache the libs even with a custom name for the project folder. 
https://github.com/angular/angular-cli/blob/master/packages/angular/cli/lib/config/schema.json#L19
Nx should be able to handle a custom lib name by checking the property `newProjectRoot` and should not be hardcoded
https://github.com/nrwl/nx/blob/master/packages/workspace/src/utils/project-type.ts#L10

## Steps to Reproduce
Generate a workspace
Generate a lib
Change the libs folder into lib (sync the angular.json)
Try to build a library
The cache folder under node_modules does not contain the bundle

### Environment

 @nrwl/angular : 9.3.0
  @nrwl/cli : 9.3.0
  @nrwl/cypress : 9.3.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.3.0
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.3.0
  @nrwl/web : Not Found
  @nrwl/workspace : 9.3.0
  typescript : 3.8.3

**Comment by FrozenPandaz** [comment]
Hi, can you please provide a repo that exhibits the issue?

We use Nx to build Nx actually so we don't have a `libs` directory... and caching works..

**Comment by vsavkin** [comment]
I'm sorry, but I'm going to close this issue. If you are able to repro it with the latest Nx 10 or Nx 9, please reopen it with the repro.
