### ISSUE TITLE
how to create a custom workspace schematic to generate a react app 

### ISSUE THREAD

**Issue by doudounannan** [nrwl/nx#3157]
In the document section [Workspace Schematics](https://nx.dev/react/workspace/schematics/workspace-schematics) only tell how to custom a lib in `@nrwl/workspace` collection. 

I want to custom a react app schematic instead of @nrwl/react.My react app's directory structure like blow:

```txt
├── browserslist
├── jest.config.js
├── proxy.conf.json
├── src
|  ├── App.tsx
|  ├── assets
|  |  └── images
|  ├── components
|  ├── environments
|  |  ├── environment.prod.ts
|  |  └── environment.ts
|  ├── favicon.ico
|  ├── index.html
|  ├── main.tsx
|  ├── pages
|  ├── polyfills.ts
|  ├── routers
|  |  ├── config.ts
|  ├── store.ts
|  ├── styles.scss
├── tsconfig.app.json
├── tsconfig.json
└── tsconfig.spec.json
```

I have several solutions:
1. modify @nrwl/react
2. create a new collection like @nrwl/react

Or other exist solution?

**Comment by FrozenPandaz** [comment]
You can do anything you want with a **Workspace Schematic**!

In the `index.ts` that is generated, you'll notice the following line:

```ts
    externalSchematic('@nrwl/workspace', 'lib', {
      name: schema.name,
    }),
```

In the docs it also mentions that this function executes any schematic from an installed package
> The externalSchematic function allows you to call schematics provided from by an installed npm package.

You can change the above line to the following:
```ts
    externalSchematic('@nrwl/react', 'app', {
      name: schema.name,
    }),
```

And now it will create a react app!

**Comment by rexebin** [comment]
I have written an article sharing my experience in creating schematics for React, if interested, [here](https://rexebin.medium.com/create-a-master-detail-crud-workspace-schematic-for-a-react-nrwl-nx-project-2c3d7979088b).
