### ISSUE TITLE
Provide DataPersistence service in app.module.ts

### ISSUE THREAD

**Issue by BioPhoton** [nrwl/nx#316]
**Problem:**
After initializing the ngrx setup the `DataPersistence` service is not provided by the providers in app.module.ts but the `AppEffects` service is.

If I run my project I get an error because `DataPersistence` is used but nit provided. 

```
zone.js:672 Unhandled Promise rejection: StaticInjectorError[DataPersistence]: 
  StaticInjectorError[DataPersistence]: 
    NullInjectorError: No provider for DataPersistence! ;
```

**Solution:**
After initializing the ngrx setup also add `DataPersistence` service to providers

**Comment by ThomasBurleson** [comment]
@BioPhoton - plz show the code samples before and after.

**Comment by BioPhoton** [comment]
Before:

```typescript
@NgModule({
  imports: [
    BrowserModule,
    RouterModule.forRoot(),
    StoreModule.forRoot(
      { app: appReducer },
      {
        initialState: { app: appInitialState },
        metaReducers: !environment.production ? [storeFreeze] : []
      }
    ),
    EffectsModule.forRoot([AppEffects]),
    !environment.production ? StoreDevtoolsModule.instrument() : [],
    StoreRouterConnectingModule
  ],
  declarations: [
    AppComponent,
  ],
  providers: [AppEffects],
  bootstrap: [AppComponent]
})
```

After:

```typescript
@NgModule({
  imports: [
    BrowserModule,
    RouterModule.forRoot(),
    StoreModule.forRoot(
      { app: appReducer },
      {
        initialState: { app: appInitialState },
        metaReducers: !environment.production ? [storeFreeze] : []
      }
    ),
    EffectsModule.forRoot([AppEffects]),
    !environment.production ? StoreDevtoolsModule.instrument() : [],
    StoreRouterConnectingModule
  ],
  declarations: [
    AppComponent,
  ],
  // I provided DataPersistence here
  providers: [AppEffects, DataPersistence],
  bootstrap: [AppComponent]
})
```

**Comment by FrozenPandaz** [comment]
@BioPhoton 
Just looking for some more information here. Was this workspace created with `create-nx-workspace` or converted from a `ng new` workspace? This is probably a bug with the latter method.

**Comment by ngfelixl** [comment]
Can reproduce this with `npm init nx-workspace name` and adding **ngrx** via *@nrwl/schematics* in angular-console. At first I used the empty root store, afterwards I added an ngrx-feature store. @BioPhoton's solution working.

- @nrwl/nx: 7.8.0
- @nrwl/builders: 7.8.0
- @nrwl/schematics: 7.8.0

**Comment by paxforce** [comment]
@FrozenPandaz I created a brand new nx-workspace a few weeks ago and I got the same thing as @BioPhoton - I too had to add the DataPersistence service to the app.module providers manually.
