### ISSUE TITLE
TS Warning, VS Code: Cannot write file because it would overwrite input file

### ISSUE THREAD

**Issue by BigAB** [nrwl/nx#3169]
## Current Behavior
When I create a new workspace + app with `--preset=react` and open a Typescript file, the following warning appears in the "Problems" tab of VSCode
```
Cannot write file '~/my-workspace/apps/my-app/jest.config.js' because it would overwrite input file
```
<img width="950" alt="screen-shot" src="https://user-images.githubusercontent.com/76821/84548510-00307f80-acc3-11ea-8e6e-85c0a6316553.png">

## Expected Behavior
I would expect there to be no "Problems" after generating a workspace + app

## Steps to Reproduce

1. `npx create-nx-workspace`, select `React`, any style, name application anything
2. open the file at `apps/your-appname/src/app/app.tsx` with VS Code
3. look at the "Problems" tab on the integrated terminal

### Environment
```
@nrwl/angular : Not Found
  @nrwl/cli : 9.4.0
  @nrwl/cypress : 9.4.0
  @nrwl/eslint-plugin-nx : 9.4.0
  @nrwl/express : Not Found
  @nrwl/jest : 9.4.0
  @nrwl/linter : 9.4.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 9.4.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.4.0
  @nrwl/web : 9.4.0
  @nrwl/workspace : 9.4.0
  typescript : 3.8.3
```

**Comment by BigAB** [comment]
Adding `"exclude": ["./jest.config.js"]` to the `tsconfig.json` seems to fix it, not sure if that's the right way to go, but it works

**Comment by timbakkum** [comment]
Same happens for TypeScript libs with allowJS true. Even though there is a `outDir` property in `tsconfig.lib.json` that points away from where the input files are, VSCode is still giving me problems.

**Comment by joshribakoff** [comment]
Any reason to not change `include` to only have the `src` directory in scope? Normally only the project's source would be type checked in my experience

**Comment by BigAB** [comment]
Should be fixed now in Nx 10
