### ISSUE TITLE
unbound breakpoint

### ISSUE THREAD

**Issue by wxyer** [nrwl/nx#3173]
my launch.json code below:
  {
      "type": "chrome",
      "request": "launch",
      "name": "Debug emer",
      "url": "http://localhost:4200",
      "webRoot": "${workspaceFolder}",
      "sourceMaps": true,
      "trace": true,
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Debug api",
      "sourceMaps": true,
      "trace": true,
      "port": 7777,
    }
## Description

when debug,front end lanuched success and back end attached success,but the breakpoint is gray and not stopped, when pointer hover,has a tip unbound breakpoint, i don't kown where is wrong ,can anyone help me?

**Comment by dbvcode** [comment]
@wxyer did you find a solution?

**Comment by ahmetesen** [comment]
any solutions for that?
