### ISSUE TITLE
decorate-angular-cli.js requires @nrwl/workspace to be a dependency rather than a devDependency

### ISSUE THREAD

**Issue by dsebastien** [nrwl/nx#3179]
## Current Behavior
The script requires @nrwl/workspace, but that package doesn't get installed when using a script such as `npm ci --only=production --no-optional --no-audit`. I'm using this to build the production Dockerfile of our project, but it now fails because @nrwl/workspace is a devDependency.

## Expected Behavior
The decorate-angular-cli.js script should also work when using `npm ci --only=production`

## Error log

```
> didowi@0.0.0 setup:prod /app
> npm ci --only=production --no-optional --no-audit

npm WARN prepare removing existing node_modules/ before installation

> leveldown@5.4.1 install /app/node_modules/leveldown
> node-gyp-build


> level@6.0.0 postinstall /app/node_modules/level
> opencollective-postinstall || exit 0


> core-js@3.6.5 postinstall /app/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> @nestjs/core@7.1.3 postinstall /app/node_modules/@nestjs/core
> opencollective || exit 0

                           Thanks for installing nest 
                 Please consider donating to our open collective
                        to help us maintain this package.
                                         
                           Number of contributors: 457
                              Number of backers: 382
                              Annual budget: $41,235
                             Current balance: $4,596
                                         
             Become a partner: https://opencollective.com/nest/donate
                                         

> didowi@0.0.0 postinstall /app
> node ./decorate-angular-cli.js

internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '@nrwl/workspace'
Require stack:
- /app/decorate-angular-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/decorate-angular-cli.js:28:20)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/decorate-angular-cli.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! didowi@0.0.0 postinstall: `node ./decorate-angular-cli.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the didowi@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-06-15T10_31_30_851Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! didowi@0.0.0 setup:prod: `npm ci --only=production --no-optional --no-audit`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the didowi@0.0.0 setup:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-06-15T10_31_30_944Z-debug.log

```

**Comment by mfechner** [comment]
I see the same problem.
It seems that the new @nrwl/nx version requires typescript and @nrwl/workspace as run dependency.

**Comment by hallowatcher** [comment]
I just stumbled upon this in my GitLab CI build.

Is it right to add typescript and @nrwl/workspace to the prod dependencies then?
![image](https://user-images.githubusercontent.com/6265839/85375864-34176a80-b537-11ea-9437-fa11cd5b2450.png)

**Comment by mehrad-rafigh** [comment]
Interesting! We have @nrwl/workspace as a devDependency and our migration to v10 worked just fine

**Comment by jared-christensen** [comment]
So what is the fix?

**Comment by maxisam** [comment]
ah.... I still have this issue with v12.9.0

**Comment by ohabash** [comment]
did anyone decide on a solution.

>Error: Cannot find module '/tmp/build_7b475095/decorate-angular-cli.js'

![Screen Shot 2021-10-12 at 3 26 39 PM](https://user-images.githubusercontent.com/15847500/137024333-5cdfb9b4-808d-4d82-932e-579e229f3ee9.png)


```  Node : 14.16.0
  OS   : darwin x64
  npm  : 6.14.11
  
  nx : Not Found
  @nrwl/angular : 12.10.0
  @nrwl/cli : 12.10.0
  @nrwl/cypress : 12.10.0
  @nrwl/devkit : 12.10.0
  @nrwl/eslint-plugin-nx : 12.10.0
  @nrwl/express : 12.10.0
  @nrwl/jest : 12.10.0
  @nrwl/linter : 12.10.0
  @nrwl/nest : 12.10.0
  @nrwl/next : Not Found
  @nrwl/node : 12.10.0
  @nrwl/nx-cloud : 12.3.13
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.10.0
  @nrwl/storybook : 12.10.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5```

**Comment by spoilerdo** [comment]
My whole project is not building anymore because of this, pls give me a fix

**Comment by brunsten** [comment]
Same issue here... Any updates?

**Comment by spoilerdo** [comment]
For me the decorate-angular-cli.js file was magically removed. So when I added it back into my project it worked again

**Comment by rujorgensen** [comment]
I'm having this issue now, when running `npm ci --only=production`, what was the fix 🙂? This silence in here is so odd 🤨.

**Comment by wesleyyoung** [comment]
@rujorgensen try adding this to your post install and changing your ci build to `NOYARNPOSTINSTALL=1 npm ci --only=production`

test -n "$NOYARNPOSTINSTALL" || node ./decorate-angular-cli.js && test -n "$NOYARNPOSTINSTALL" || ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points

**Comment by rujorgensen** [comment]
@wesleyyoung Hi, thanks for your suggestion, I get some errors though (first something about not finding `ng`, which probably has something to do with the mod. to the `decorate-angular` step of the postinstall, then I tried to revert the postinstall script back, but then got `#11 66.08 sh: ngcc: not found` and a lot of other stuff) 🙂. As I've already spent a lot of time dealing with this, I'm not going to be investigating further--just hoped for a quick fix 😊. Again thanks a lot for helping out 👍.

**Comment by balteo** [comment]
Any fix or workaround ? I am facing the same issue...

**Comment by casalete** [comment]
Why is this closed? @vsavkin

**Comment by CharlieGreenman** [comment]
I had this issue... make sure you `nx` installed in your `devDependencies`. I removed nx when the cli told me that nrwl/workspace is now used in place of nx during nx migrate. Once i added nx to my devDependencies, this error went away
