### ISSUE TITLE
Global config option for affected base.

### ISSUE THREAD

**Issue by benmonro** [nrwl/nx#3180]
## Description
We are changing our default branch to be named `main` and we're looking for a way to globally configure our repo to use that in conjunction with `affected` commands.

## Motivation

to be able to globally configure the base branch for affected commands.

## Suggested Implementation

In workspace.json perhaps?

**Comment by brandonroberts** [comment]
PR landing soon to support this https://github.com/nrwl/nx/pull/3217

**Comment by vsavkin** [comment]
This has landed in Nx 9.5.
