### ISSUE TITLE
next.js custom server errors with default settings

### ISSUE THREAD

**Issue by cdaringe** [nrwl/nx#3190]
## Current Behavior

```
// workspace.json
"serve": {
  "builder": "@nrwl/next:server",
  "options": {
    ...
    "dev": true,
    "customServerPath": "server.ts"
  },
```

yields:

```
/path/to/app/server.ts:1
import { createServer } from "http";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

Which suggests to me that `.ts` is not supported. However, the documentation does not detail what really is accepted as a value to the field (e.g. i learned string values are relative filenames from the target projectDirname). I could do a .js file, but that won't work gracefully with my other typescript code.

https://nextjs.org/docs/advanced-features/custom-server I now see suggests that the server is _not_ part of the webpack process.

## Expected Behavior

`.ts` entrypoint to work.  Perhaps babeled & loaded?

## Steps to Reproduce

- create a new next.js nx project using @nrwl/next
- add a `.ts` file to the customServer options
- serve

### Failure Logs

- see above

### Environment

n/a

**Comment by mandarini** [comment]
Hi there @cdaringe ! Thanks for filing an issue. Could this possibly be a request for an enhancement, rather than a bug?

**Comment by cdaringe** [comment]
Ya, definitely an enhancement
