### ISSUE TITLE
Font size on https://nx.dev/ is too small

### ISSUE THREAD

**Issue by sohonisaurabh** [nrwl/nx#3194]
## Description
For a regular user like me, I feel it difficult to read through the content on https://nx.dev/ site. There is some problem with the font family and font size that it is just not readable enough.
Current font is `Montserrat` with font size of 12px

## Motivation
If a normal user can't read it, very tough for users with impaired vision to stay on the website for even 5 seconds. Please help!

## Suggested Implementaion
For `Montserrat` font family, 14px seems readable enough for content.

## Alternate Implementations
Default to Helvetica with 12px.

**Comment by bcabanes** [comment]
The font has been changed and bumped a little bit!
Thank you for the feedback!
