### ISSUE TITLE
next.js recipe disjoint customServer provisions between build & serve

### ISSUE THREAD

**Issue by cdaringe** [nrwl/nx#3199]
## Current Behavior

- `serve` supports a `customServer`, but `build` is missing such provisions. that is, though i have a custom server, the build distribution ignores it, meaning my built artifact is not runnable after build, but is runnable in dev using serve.

similarly, `next.config.js` & `public` assets are missing in dist, which are common next.js required artifacts

this is related, but independent of #3190

## Expected Behavior

- customServer and associated provisions make it into dist. this could feasibly be a webpack::target::node execution on `customServer` placed into `dist/apps/<appname>/server.js` as an optimized bundle.

## Steps to Reproduce

- observe nx src for next.js serve vs build builder impls

### Failure Logs

n/a

### Environment

n/a

**Comment by cdaringe** [comment]
i've thought on this some. given that we are TS-first-class, and next demands custom servers as JS, it probably makes sense to have have the next builders allow for a customServer _dependency_ option if TS support is desired. then, an implicit dependency maps `my-next-app` => `my-next-app-custom-server`, and the builder ensures that custom server lib assets are bundled and inserted as `my-next-app/server.js`

**Comment by cdaringe** [comment]
scram, stalebot

**Comment by cdaringe** [comment]
scram stalebot

**Comment by vasuneet** [comment]
any update on this ? Our production build is having issue to run the custom server

**Comment by cdaringe** [comment]
My last comment is dated and is not recommended. As it turns out, you can tell next JS programmatically where the contents of the pages live. So what we ended up doing was just creating a brand new application, then that application _is_ our server. We never run next directly, we only run our server. That server imports the next JS app handler, configures it, and specifically points it to our next JS application files. So essentially we have two apps, and the server app points to the next JS app, and it all works fine. And this is made possible only by the fact that there is a `dir: ...` flag supported by next. On the phone, so sorry if that didn't make perfect sense. Having the server as an app and having the nextJS nrwl as an app I ended up being a clean solution, I'll be at it comes with a little bit of indirection, as at the end of the day, they both ultimately end up being run as the same process.

**Comment by vasuneet** [comment]
Hey. I am reiterating my issue. I have following artifacts :
nextJSapproot
  ---contents related to nextjs app
  --- server.js (this is my custom server)

which is working fine with nx:server <nextapp>

but after creating production build I am running 
yarn start
and it is picking default server not the custom one.

What provision over here I need to do to make it work.

**Comment by kirjai** [comment]
#5765 was merged recently, which potentially makes custom prod server available as a feature, i believe?

have you tried setting the `customServerPath` option in the production configuration in your `workspace.json`? 

<img width="429" alt="Screenshot 2021-06-11 at 14 07 35" src="https://user-images.githubusercontent.com/9858620/121690962-24d65780-cacf-11eb-834e-143377ea900e.png">

that should allow you to run `nx serve <name of your next app> --prod` and nx should use the provided custom server for that.

could you give that a try to see if that works for what you're trying to do?

**Comment by nsmith7989** [comment]
@kirjai I don't think #5765 fixes this issue for build. 

The custom server never ends up compiled into the `dist` directory. 

Also if you look at the dist's package.json of each app, `start` is still `"start": "next start"` not `"start": "node customServer.js"`

We're run into this problem too, ended up adding a separate target to each of our nextjs apps that does @nrwl/node:build, then use @nrwl/workspace:run-commands to combine those two together.  

```
"build": {
          "executor": "@nrwl/workspace:run-commands",
          "options": {
            "commands": [
              "yarn nx run booking-res-lite:build-next:production",
              "yarn nx run booking-res-lite:build-server:production"
            ]
          }
        },
        "build-next": {
          "executor": "@nrwl/next:build",
          "outputs": ["{options.outputPath}"],
          "options": {
            "root": "apps/booking/res-lite",
            "outputPath": "dist/apps/booking-res-lite"
          },
          "configurations": {
            "production": {}
          }
        },
        "build-server": {
          "executor": "@nrwl/node:build",
          "outputs": ["{options.outputPath}"],
          "options": {
            "outputPath": "dist/apps/booking-res-lite",
            "main": "apps/booking/res-lite/server.ts",
            "tsConfig": "apps/booking/res-lite/tsconfig.server.json"
          },
          "configurations": {
            "production": {
              "optimization": true,
              "extractLicenses": true,
              "inspect": false
            }
          }
        },
```

**Comment by jcze91** [comment]
Any progress on this issue ? :/

**Comment by jaysoo** [comment]
Sorry for the lack of updates.  We need to rethink the custom server implementation.

As pointed out, it is only running the dev server through the custom server. We may need a migration to move it from  `@nrwl/next:server` to `@nrwl/next:build` since it is a build concern.

We'll have something soon, so stay tuned.

**Comment by gnoyixiang** [comment]
not stale?
