### ISSUE TITLE
Library secondary entry points

### ISSUE THREAD

**Issue by klemenoslaj** [nrwl/nx#3208]
## Description

I am not sure if this would be possible, but it could have a great potential of building publishable libraries within Nx workspaces.

I am wondering if it would be possible to get introduce secondary entries to publishable libraries, similar like [`ng-packagr` is doing](https://github.com/ng-packagr/ng-packagr/blob/master/docs/secondary-entrypoints.md), but with the detached build from the main library?

Right now `ng-packagr` builds the whole library including all the entry points. This defeats the purpose of Nx. So my suggestion or rather question is, if would be possible to build only the entry point changed and use the rest from cache?
I am aware this would probably have to be implemented in Nx completely without reusing much of `ng-packagr` functionality, but in my eyes this could be well worth it.

## Example

Library structure:

- `@myOrg/library`
- `@myOrg/library/first-entry`
- `@myOrg/library/second-entry`

Change detected in `@myOrg/library/first-entry`:
- Nx only builds `first-entry` and leaves the rest as is

Currently:
- Nx triggers `ng-packagr` which builds whole library with both entry points

## Solution

Speculating enormously here, but maybe we could use non-publishable libraries instead of `ng-packagr` entry points to get the result?

**Comment by klemenoslaj** [comment]
> If we missed this issue please reply to keep it active.

Yes. Still think it could be a very good addition to Nx.

**Comment by lazarljubenovic** [comment]
Also interested in this. Is it on the road-map? An obvious workaround is to have two libraries with paths `@scope/foo` and `@scope/foo/bar` to imitate this behavior as far as the consumers of the two libraries are concerned, but obviously this fails short as soon as you want the libraries to be publishable (maybe even buildable depending on the setup).

**Comment by olofens** [comment]
Hey guys, I'm using ng-packagr secondary entry points in my Nx monorepo. Here's what I did: https://olofens.medium.com/secondary-entry-points-in-an-angular-nx-library-8d01a80634cc

I realize though that it doesn't help with detached build.

**Comment by jhesgodi** [comment]
I would really like to hear about how this can be achieved.

**Comment by BhaskaranR** [comment]
hello - Is this still in the pipeline? I need multiple entry points for react library that could be lazy loaded

**Comment by maxime1992** [comment]
@olofens thank you **so much** for your write up. I've read countless docs and articles without being able to figure out how to properly break down 1 lib into multiple exports so that the whole lib wouldn't be included if we import only part of it.

It was tremendously helpful :pray:

**Comment by BeSpunky** [comment]
Did anyone find a way to enable computation caching on secondary endpoints? Any workaround?
Seems like the current decision must be between:
a. A single publishable library with multiple entrypoints - No caching
b. Multiple publishable libraries with a single entrypoint each - With caching

**Comment by rcuddy** [comment]
I'm using a setup similar to @olofens above, with a ui libary using ng-packagr. It "just worked" when I migrated the project into NX but agree there are holes this creates in the nx experience. Both computation caching and dependency graphs suffer from this as these "sub libraries" are effectively invisible to NX but this multiple entry points pattern is the "correct" one that should be used when building complex publishable libraries (in angular. I have no idea how our react friends work in this context!)

Could we evolve some hybrid model perhaps where each of the entry points exist as first class NX libraries that are used normally within the monorepo as actual independent buildable libraries themselves;  but then some new publish process is created that bundles them together into a single "export" library during that export libraries build step? This almost sounds like it starts to touch onto some of the issues people are trying to work around in https://github.com/nrwl/nx/issues/1765 in publishing libraries with dependencies that aren't exposed as buildable libs. Those workarounds would get the code bundled up, but I'm not sure if the import paths would still work right for consumers of this library?

**Comment by BeSpunky** [comment]
I actually tried something similar last week, where I created a lib for every entrypoint, then created the main (publishable) lib with the same structure as before, but only including imports and exports. Something like this:
```
libs/
|-- main-library
     |-- entrypoint-1 (imports from libs/entrypoint-1 + exports)
     |-- entrypoint-2 (imports from libs/entrypoint-2 + exports)
|-- entrypoint-1 (actual code)
|-- entrypoint-2 (actual code)
```
This builds successfully and computational caching works. However, and I should've guessed it, the `dist/main-library` folder only contains maps and definition files. The actual code is not there which makes the folder useless.

Maybe there's some webpack config to force the code to be copied from the compiled libs and not just referenced, but my webpack knowledge is not there yet. Furthermore, as @rcuddy mentioned, this may quickly lead to chaos in the codebase.

Conclusion, the NX team should find a way to seamlessly integrate computational caching for secondary entrypoints. This is VITAL for a publishable library. Any other solution is probably going to involve hacking or unmaintainable configuration...

**Comment by liverant** [comment]
Does someone have a solution? (that is not Angular specific)
I opened a new issue as this one was closed: https://github.com/nrwl/nx/issues/8606
