### ISSUE TITLE
Can 'deployUrl' or other build option support to assign according to environment such as NODE_ENV === 'production' or 'development'

### ISSUE THREAD

**Issue by doudounannan** [nrwl/nx#3209]
## Description

There are two environment stage & production in our project. Option 'deployUrl' is '' or not exist when local development, it's supposed to '/A/' in stage environment, but it's supposed to 'https://cdn.xx/A/' in production environment.

So I hope option 'deployUrl' or other build can from .env or process.

**Comment by nzacca** [comment]
Wondering, would it be possible to do something similar to the `outputs` interpolation in the `workspace.json`?

```json
...
"app1": {
  "build": {
    "options": {
      "deployUrl": "{env.MY_FIRST_APP}"
    }
  },
},
"app2": {
  "build": {
    "options": {
      "deployUrl": "{env.MY_SECOND_APP}"
    }
  },
}
...
```

Our use case is we have a different deploy url _per app per environment_ so we're looking for the ability to set this on the CD pipeline.

**Comment by Anenth** [comment]
@meoufun @nzacca Where you guy able to find a solution for this?

**Comment by nzacca** [comment]
@Anenth I ended up creating a helper script that is called on our pipeline to assemble the nx build script with the appropriate deploy url. A static map is used to map between each app and the deploy url.
