### ISSUE TITLE
How to reference environment variables into index.html in Nx

### ISSUE THREAD

**Issue by doudounannan** [nrwl/nx#3210]
## Description

Like in `create-react-app`,access the environment variables starting with REACT_APP_ in the public/index.html，like below:

In Nx, how to access the environment variables from .env or process?

```html
<title>%REACT_APP_WEBSITE_NAME%</title>
```

**Comment by Stupidism** [comment]
Any plan to support this feature? It's quite annoying that I can't even use different favicon.ico in test and prod environments.

**Comment by vaunus** [comment]
We've also just come up against this issue and have struggled to find a decent solution. We essentially want environment variable replacement at static build time within the `index.html` of a React app. Injecting scripts isn't an option as we are using NewRelic and they specifically say not to do this as it will cause issues.

We came across `HtmlWebpackPlugin` which does environment variable replacement, but it seems this plugin does a lot more as well so it ends up causing issues when used with NX. Perhaps an implementation of `HtmlReplaceWebpackPlugin` to replace something like `<%= ENV_VAR %>` would do the trick?

**Comment by timbakkum** [comment]
We need to swap assets at build time loaded by our index.html. We just hardcode the default file path and then replace the default source at that path at build time using the `assets` and/or `fileReplacements` option in our different build configurations. 

It's not ideal, but works for our current use cases, so maybe this can be of help. I wish it was more straightforward like how create react app manages this.

**Comment by jkrehm** [comment]
I'm also running into this issue. Disappointed to see it closed automatically without a resolution. 😞

**Comment by tar-aldev** [comment]
Having the same issue needed it to setup rollback and react.

**Comment by christian452** [comment]
Running into this issue as well. This is causing nasty workarounds. Any plans to support?

**Comment by JoshHubi** [comment]
I too am running into this issue. Are there still no plans to support this?

**Comment by ADobrianskiy** [comment]
Any news?

**Comment by halafi** [comment]
I don't think this issue should be closed

**Comment by wilkinsonjack1993** [comment]
For those running webpack 5, the above solution doesn't seem to work - I have opened a bug ticket for it here: https://github.com/nrwl/nx/issues/6941
