### ISSUE TITLE
.babelrc not picked up from @nrwl/express project

### ISSUE THREAD

**Issue by adams-family** [nrwl/nx#3212]
##  Current Behavior
`.babelrc` file seems to be ignored (no matter where is it placed)

## Expected Behavior
`.babelrc` file should be used when placed in the root of the workspace or inside of an app

## Steps to Reproduce

1) Create a new workspace
```
npm init nx-workspace nxworkspace
```
  Project: empty
  CLI: Angular
  NX cloud cache: No

2) Create an express project:
```
cd nxworkspace
npm i @nrwl/express --save-dev
ng g @nrwl/express:application express
```

3) Create a .babelrc file with a syntax error in the root folder of the workspace
```
echo "xxx" > .babelrc
```

4) Start serving express
```
nx serve express
```

In my opinion I should get an error here that informs me that webpack has attempted to process my .babelrc file.

### Environment
```
  @nrwl/angular : 9.4.5
  @nrwl/cli : 9.4.5
  @nrwl/cypress : 9.4.5
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : 9.4.5
  @nrwl/jest : 9.4.5
  @nrwl/linter : 9.4.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.4.5
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.4.5
  @nrwl/web : Not Found
  @nrwl/workspace : 9.4.5
  typescript : 3.8.3
```

**Comment by jaysoo** [comment]
Express apps are not going through babel at this moment (unlike web/react apps). We may be able to add support in the futur

**Comment by adams-family** [comment]
@jaysoo Thanks. Is there any kind of compilation of Express apps in nrwl? As I am using `.ts` files in my project, but the build bundle is called `main.js`.
