### ISSUE TITLE
nx 9.4.x doesn't use browser entry point properly

### ISSUE THREAD

**Issue by gsong** [nrwl/nx#3213]
## Current Behavior

nx 9.4.5 builds React library with node modules, instead of browser modules.

## Expected Behavior

As nx 9.3.0 did, build the lib with browser modules.

## Steps to Reproduce

I've done the exact same thing with both nx 9.4.5 and 9.3.0.

1. `npx create-nx-workspace` with React
1. `nx g @nrwl/react:lib mylib --js --publishable`
1. Install `uuid` and make the appropriate code change

### nx 9.4.5

1. Clone https://github.com/gsong/nx-rollup-problem
1. `npm i`
1. `npx nx build mylib`
1. Notice the following errors:

   ```text
   'crypto' is imported by node_modules/uuid/dist/esm-node/rng.js, but could not be resolved – treating it as an external dependency
   'crypto' is imported by node_modules/uuid/dist/esm-node/md5.js, but could not be resolved – treating it as an external dependency
   'crypto' is imported by node_modules/uuid/dist/esm-node/sha1.js, but could not be resolved – treating it as an external dependency
   ```

If you look at the `dist/libs/mylib/mylib.esm.js`, you'll notice that indeed the module is trying to import `crypto`:

```js
import crypto from "crypto";
```

### nx 9.3.0

1. Clone https://github.com/gsong/nx-rollup-problem/tree/nx-9.3
1. `npm i`
1. `npx nx build mylib`

Success! `dist/libs/mylib/mylib.esm.js` imports from `uuid` instead:

```js
import { v4 } from "uuid";
```

### Environment

<details>
<summary>nx 9.4.5</summary>
<pre>
@nrwl/angular : Not Found
@nrwl/cli : 9.4.5
@nrwl/cypress : 9.4.5
@nrwl/eslint-plugin-nx : 9.4.5
@nrwl/express : Not Found
@nrwl/jest : 9.4.5
@nrwl/linter : 9.4.5
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/react : 9.4.5
@nrwl/schematics : Not Found
@nrwl/tao : 9.4.5
@nrwl/web : 9.4.5
@nrwl/workspace : 9.4.5
typescript : 3.8.3
</pre>
</details>

<details>
<summary>nx 9.3.0</summary>
<pre>
@nrwl/angular : Not Found
@nrwl/cli : 9.3.0
@nrwl/cypress : 9.3.0
@nrwl/eslint-plugin-nx : 9.3.0
@nrwl/express : Not Found
@nrwl/jest : 9.3.0
@nrwl/linter : 9.3.0
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/react : 9.3.0
@nrwl/schematics : Not Found
@nrwl/tao : 9.3.0
@nrwl/web : 9.3.0
@nrwl/workspace : 9.3.0
typescript : 3.8.3
</pre>
</details>

**Comment by hsw107** [comment]
This is still reproducible as of 10.0.6, and as early at 9.4.0.

**Comment by Blackhex** [comment]
Any workaround for this, please?

**Comment by hsw107** [comment]
@vsavkin Looks like this was removed from any milestones. Do you know if there's any plans to fix this or have a workaround? We haven't been able to upgrade Nx since 9.4.0 was released.

**Comment by beeman** [comment]
I'm seeing the same, I would love to know how to get this fixed!

I kinda assumed this would work for React as it does work for Angular in an Nx Workspace, but sadly it doesn't.

**Comment by ZackDeRose** [comment]
Unable to reproduce this issue in 11.5 - we believe it to be resolved.

We are no longer supporting legacy versions older than 1 prior.

Please reopen if you believe this is still a valid issue!

**Comment by beeman** [comment]
@ZackDeRose I had this with the latest and greatest, I'll create a repro.

**Comment by ZackDeRose** [comment]
Appreciate it @beeman!
