### ISSUE TITLE
Nx 8 -> 9 : can not kill (ctrl + c) affected:build/test/e2e process

### ISSUE THREAD

**Issue by SaifJerbi** [nrwl/nx#3218]
After upgrading to nx 9, i can no longer kill the different process launched with `affected` until they are finished. i'm used to run `yarn affected:test/build` in my local dev environement after local merge or git changes and when there are some fails, i'm used to kill the running process with `ctrl + c` to fix different fails.
The problem is that the console is stopped for few moments and comes back with logs. It behave like it was running in separate thread but trace in the same console

## Current Behavior
I can no longer kill a process running with `affected`

## Expected Behavior
I think this is a regression because i didn't face this problem before migrating

## Steps to Reproduce
run : `yarn affected:test` or `build`
try to kill the process with : `ctrl + c` when the first affected module start testing/building

### Environment
Issue reproduced in Mac OS catalina and Rhel 7
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 9.4.5
  @nrwl/cli : 9.4.5
  @nrwl/cypress : 9.4.5
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : 9.4.5
  @nrwl/jest : 9.4.5
  @nrwl/linter : 9.4.5
  @nrwl/nest : 9.4.5
  @nrwl/next : Not Found
  @nrwl/node : 9.4.5
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.4.5
  @nrwl/web : Not Found
  @nrwl/workspace : 9.4.5
  typescript : 3.8.3

**Comment by vsavkin** [comment]
@SaifJerbi Thanks for submitting the issue. 

I cannot repro it. Could you provide a github repo with a repro? Could you also try Nx 9.5.1, in case something has been fixed in 9.5.1?
