### ISSUE TITLE
`ng lint --exclude` not working in 9.4.3+

### ISSUE THREAD

**Issue by pburkindine** [nrwl/nx#3219]
## Current Behavior

The exclude in `ng lint --exclude "**/{*.spec,*.stub,*.mock,mocks}.ts"` e.g. does not work after updating to nx 9.4.3; errors are found in spec files (we lint our spec files with a different tslint.json)

## Expected Behavior
`--exclude` should be respected

## Steps to Reproduce

https://github.com/pburkindine/nx-ng-lint-exclude/tree/master/apps/ng-lint-exclude-nx

Run the `lint-files` package.json script

**Comment by pburkindine** [comment]
It may be relevant to add, in our actual repo I was able to fix the problem by rolling back @schematics/angular from 9.1.9 to 9.1.7

In the test repo, a clean nx install, @schematics/angular is not specified so is set at 9.1.9

**Comment by vsavkin** [comment]
Thanks for submitting the issue. 

Exclude is also used to exclude Nx projects, so the flag gets filtered out before it reaches the builder.  This fix is to add `--`, as follows:

```
ng lint -- --exclude "**/{*.spec,*.stub,*.mock,mocks}.ts"
```

I'm going to close this issue.
