### ISSUE TITLE
add --no-eslintrc option to nx lint schema

### ISSUE THREAD

**Issue by epikhighs** [nrwl/nx#3220]
## Description

add `--no-eslintrc` option to nx lint.  https://eslint.org/docs/user-guide/configuring#using-configuration-files-1

Currently, it throws an error b/c it is not part of the schema.
```
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(eslintrc).
```
## Motivation

It allows for custom custom eslint rules to be applied while opting out of the cascading eslintrc feature.  By default, if eslintrc file(s) exists in the directory structure, then those configs are merged together and merged with the config passed through the `--config` flag.  By using the `--no-eslintrc`, one could apply a custom eslint config that does not get merged with other eslintrc files.

## Suggested Implementaion

Schema should support this eslint flag and pass this option through to eslint when specified.

**Comment by JamesHenry** [comment]
Hi @epikhighs please allow me to apologise that you did not receive an explicit acknowledgement on this before now.

I have now added this capability in #4832

**Comment by epikhighs** [comment]
Nice.  Thank you @JamesHenry.
