### ISSUE TITLE
Version 8.12.10 source on npm does not match what is in https://github.com/nrwl/nx/releases/tag/8.12.10

### ISSUE THREAD

**Issue by rickj33** [nrwl/nx#3228]
## Current Behavior
The source file jest.impl.ts from npm install still has the astTransformers defined as 
```
  astTransformers: [
       'jest-preset-angular/InlineHtmlStripStylesTransformer'
      ]
```
it does not include the addition of the build folder in the path. This causes the test in angular to fail due to the fact it cannot find the file.

## Expected Behavior
I would expect the source from the package match what is in the source form https://github.com/nrwl/nx/releases/tag/8.12.10
The   jest.impl.ts file from this tag defines the astTransformers as 
```
  astTransformers: [
        'jest-preset-angular/build/InlineFilesTransformer',
        'jest-preset-angular/build/StripStylesTransformer'
      ]
```

## Steps to Reproduce
run npm i @nrwl/jest@8.12.11 --save-dev
download the source from https://github.com/nrwl/nx/releases/tag/8.12.10
compare the jest.impl file.

**Comment by vsavkin** [comment]
Thanks for submitting the issue. We had the tagging screwed up, so the associated source is incorrect. Unfortunately I'm not able to update/remove the assets, so I added a comment in the release notes pointing to the right source.
