### ISSUE TITLE
$workspaceRoot not created on `update`

### ISSUE THREAD

**Issue by emilio-martinez** [nrwl/nx#323]
When creating a new project with Nx, an entry for `$workspaceRoot` is created in the `.angular-cli.json`:

```js
{
  ...
  "apps": [
    ...
    {
      "name": "$workspaceRoot",
      "root": ".",
      "appRoot": ""
    }
  ]
  ...
}
```

However, this app entry is not created on `update`, and there is no migration for it. See https://github.com/nrwl/nx/search?utf8=%E2%9C%93&q=workspaceRoot.

To be candid, not sure what it's used for, but thought it would be more helpful to report it than not.

**Comment by bcabanes** [comment]
Hi!

Closing old issue.
