### ISSUE TITLE
Is it possible to bundle all node_modules into a single .js file for a @nrwl/express app?

### ISSUE THREAD

**Issue by adams-family** [nrwl/nx#3235]
## Description

I have a workspace with a `@nrwl/express` and a `@nrwl/angular` app.

When I build the express application with:

```
ng build backend
```

I get a single `main.js` file where my entire express application lives. However, this file does not include node_modules and therefore when deploying to production I still need to run `npm install` and install dependencies.

It seems reasonable to bundle everything with `webpack` (including `node_modules`) into a single .js file because that way it can be always deployed to production in a second without worrying about installing the right versions of node_modules during go-live.

Is it possible to achieve it?

**Comment by jadengis** [comment]
@adams-family it really depends on the type of dependencies you have. Some npm packages for node.js have native components (C++ compile binaries), for example the `sharp` image processing library. These cannot be packed by a module bundler, and so those dependencies will always need to be installed before use.

However, if you don't use any libraries with native dependencies, you can add the `externalDependencies: "none"` argument to the builder for your express app in `workspace.json`. This will make webpack attempt to bundle all the source, including node_modules.

**Comment by adams-family** [comment]
@jadengis This is a very good answer! I completely forgot about compiled binaries, my suggestion doesn't really make sense for a real worls application then. I'm closing this question.
