### ISSUE TITLE
Cypress supports Typescript natively, does that mean anything?

### ISSUE THREAD

**Issue by markgoho** [nrwl/nx#3236]
https://docs.cypress.io/guides/references/changelog.html#4-4-0

Does this relieve any burden on Nx to do anything special to get Cypress to read the `spec.ts` files?

**Comment by juristr** [comment]
Hey @markgoho. Yeah it should. Now that TS is natively supported, we should be able to drop the preprocessor. If you're interested you can follow this related issue #3037 :)
