### ISSUE TITLE
`makeSureNoAppIsSelected` is not added to `karma.conf.js` on `update`

### ISSUE THREAD

**Issue by emilio-martinez** [nrwl/nx#324]
When creating a new project with Nx, the following snipped is near the top of the `karma.conf.js` file:

```js
const { makeSureNoAppIsSelected } = require('@nrwl/schematics/src/utils/cli-config-utils');
// Nx only supports running unit tests for all apps and libs.
makeSureNoAppIsSelected();
```

However, this is not created on `update`, and there is no migration for it. See https://github.com/nrwl/nx/search?utf8=%E2%9C%93&q=makeSureNoAppIsSelected.

**Comment by Yonet** [comment]
You can find the replication of the issue here: https://github.com/nrwl/nx-examples/blob/master/karma.conf.js

**Comment by FrozenPandaz** [comment]
I can take this
