### ISSUE TITLE
Linting on E2E app does not catch errors

### ISSUE THREAD

**Issue by aderito7** [nrwl/nx#3249]
## Current Behavior

When running **lint** against an e2e application it does not fail when there are errors in the application

## Expected Behavior

I have yet to see this work although I hope I'm just missing some configuration

## Steps to Reproduce

- Run `npx create-nx-workspace@latest`
- Select an angular project in the setup process
- move to the _app.spec.ts_ file and introduce a linting issue
- `ng run <APP>-e2e:lint` or even use Nx Console
- Notice how this will always pass linting

Same issue happens for _products_e2e_ and _carts_e2e_

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

```
  @nrwl/angular : 9.4.5
  @nrwl/cli : 9.4.5
  @nrwl/cypress : 9.4.5
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.4.5
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.4.5
  @nrwl/web : Not Found
  @nrwl/workspace : 9.4.5
```

**Comment by vsavkin** [comment]
Unfortunately, I'm not able to repro it. Could you provide a repository with a repro?

**Comment by aderito7** [comment]
Hi @vsavkin so I've just tested again and made sure to follow the original steps and I still get the same issues.
This time I just also made sure to make use of the nx command as well `npx nx lint <APP>`

Here is a repo: https://github.com/aderito7/ng-e2e-test

**Comment by geromegrignon** [comment]
I can't reproduce the bug either.
I cloned your repo and running `ng run ng-test-e2e:lint`, the errors are correctly displayed : 

![image](https://user-images.githubusercontent.com/32737308/90514770-e77c9400-e161-11ea-8953-da84ebaca0c5.png)

While removing the unused expression, the linter pass as intended : 

![image](https://user-images.githubusercontent.com/32737308/90514958-3296a700-e162-11ea-8ed6-63c4c7bb4a3a.png)

**Comment by aderito7** [comment]
Okay, thank you all for assisting. It's a bit of a weird one for me, but I'll close this issue as I notice that this is not a broad issue.
