### ISSUE TITLE
`makeSureNoAppIsSelected` is inaccurate for `ng test -a app-name`

### ISSUE THREAD

**Issue by emilio-martinez** [nrwl/nx#325]
`makeSureNoAppIsSelected()` correctly verifies passed arguments as long as they're formulated as `-a=app-name` or `--app=app-name`. However, arguments are missed if they're formulated without the equal sign after the argument key, i.e., `-a app-name` or `--app app-name`.

That syntax, both with and without the equals sign after the argument key, is valid, as shown in Angular CLI's ["Multiple Apps integration" story](https://github.com/angular/angular-cli/wiki/stories-multiple-apps).

See reference below to where the equal sign is being explicitly sought out as part of the argument.

https://github.com/nrwl/nx/blob/be6bfd31ecbb16588902796d40b2d0d6716cac7f/packages/schematics/src/utils/cli-config-utils.ts#L25-L43

**Comment by FrozenPandaz** [comment]
I can take this

**Comment by FrozenPandaz** [comment]
This should no longer be an issue as of `0.10.0`.
