### ISSUE TITLE
[Question]: List of all available commands

### ISSUE THREAD

**Issue by johannesschobel** [nrwl/nx#3250]
Dear Nrwl Team,

i recently stumbled upon the issue to rename a library. I did this by manually `search / replace` commands because i was not aware that there is an easy to use command.

In this issue described here ( https://github.com/nrwl/nx/issues/2001 ) @jdpearce posted a command to move a project / app from `src` to `dest`.

Are those commands documented somewhere? Because i was not able to find any documentation on this command or any other (maybe similar) commands.

Thanks a lot!

**Comment by jdpearce** [comment]
Hi @johannesschobel, it seems those schematics aren't indexed by our search tool! Sorry about this.

You can find documentation on our plugins here : https://nx.dev/angular/plugins/overview

The specific `move` schematic that you want is documented here : https://nx.dev/angular/plugins/workspace/schematics/move

You can also use `nx list` to show the available plugins and then schematics in each plugin.

**Comment by johannesschobel** [comment]
Dear @jdpearce ,
thanks for the response. 

This may, however, be a bit cumbersome, because i would need to check all `nx list [package]` in order to search for a respective command / schematic (if it exists, though ;) ).

All the best and thanks for helping

**Comment by juristr** [comment]
@johannesschobel Highly recommend the [NxConsole VSCode extension](https://nx.dev/angular/cli/console)

**Comment by johannesschobel** [comment]
Yeah I know this plugin, and I use it regularly.. However I did not stumble across these commands.. maybe I did miss them.. nevermind 🤔
