### ISSUE TITLE
Support for webdriverio

### ISSUE THREAD

**Issue by maikdiepenbroek** [nrwl/nx#3256]
## Description
Next to the great cypress support i would like to add a e2e stack using webdriverio/jasmine|mocha/cucumber. It would be great if that has out of the box support for generating such a project. 

## Motivation
To give users the choice of using a different e2e stack than cypress.

## Suggested Implementation
Be able to generate an e2e app with webdriver io default settings and the ability to run it via an nx command.

## Alternate Implementations
Via a custom plugin

I'm more than happy to help implement this, if someone can point me in the right direction.

ps. In the default template there's a typo in `Alternate Implementations`

**Comment by christian-bromann** [comment]
@maikdiepenbroek thanks for raising the issue. I totally agree with you that people should have an alternative to Cypress and I am a bit confused why such feature requests are rejected as stale.

While I am a bit busy with bunch of other things I can take a look to see what needs to be done to add a Cypress alternative for this repository. If anyone from the maintainer teams things it is a bad idea please let me know.

Therefore I would also appreciate if we could re-open this one. Thanks!

**Comment by Roozenboom** [comment]
For anyone looking at WebdriverIO support in NX, I created an NX plugin to do exactly that, please have a look at https://nx.dev/community#plugin-directory and search for WebdriverIO or go directly to https://github.com/Roozenboom/rbnx/tree/main/packages/webdriverio

**Comment by maikdiepenbroek** [comment]
@Roozenboom Great, thanks so much for your effort. Since i changed projects i no longer had the need for it and in my previous project we didn't need it after all. So i didn't implement it myself.
