### ISSUE TITLE
Invalid file path reference in stack trace on NODE app with nx serve

### ISSUE THREAD

**Issue by shlomiassaf** [nrwl/nx#3258]
## Current Behavior

Stack trace errors (NODE APP, `nx serve`) are referencing incorrect files

## Expected Behavior

Stack trace should reference the right path to allow VS CODE to open the file on click.

## Steps to Reproduce
On a NODE project, run the app and throw somewhere, you will get a stack trace printed in the console.
The paths for `ts` files are mapped incorrectly due to webpack mapping errors.

```
Error: 123
    at ServerInitializationModule.configure (/Users/shlomiassaf/Desktop/Code/sg/sg-node/dist/applications/public-api/webpack:/applications/public-api/src/app/server/init/init.module.ts:44:11)
    at MiddlewareModule.loadConfiguration (/Users/shlomiassaf/Desktop/Code/sg/sg-node/node_modules/@nestjs/core/middleware/middleware-module.js:47:24)
    at loadMiddlewareConfiguration (/Users/shlomiassaf/Desktop/Code/sg/sg-node/node_modules/@nestjs/core/middleware/middleware-module.js:37:24)
    at Array.map (<anonymous>)
...
```

Instead of `/Users/shlomiassaf/Desktop/Code/sg/sg-node/dist/applications/public-api/webpack:/applications/public-api/src/app/server/init/init.module.ts`

It should be `/Users/shlomiassaf/Desktop/Code/sg/sg-node/applications/public-api/src/app/server/init/init.module.ts`

It has an effect on the development process, very hard to jump into areas.
Not the end of the world, but would be nice to have this sorted out.

Thanks!

**Comment by DetachHead** [comment]
This is a bigger issue than not being able to easily navigate between files in the stack trace. It also stops breakpoints from working. I think this should be reopened

**Comment by DetachHead** [comment]
This is actually a bigger issue than not being able to click the files in the stack trace because it also stops breakpoints from working. I think this issue should be reopened

**Comment by elisiskind** [comment]
I agree this should be reopened - this is a serious problem and I am not aware of any workarounds.

**Comment by hardikbeladiya** [comment]
Same here. I am working on the Project in which we don't have the clue from where the Error is coming, so I guess this is very important Issue.

**Comment by markabrahams** [comment]
I love using Nx - thanks very much to the @nrwl team for their great work here.  This issue was the one immediately obvious poor developer experience I noticed when I first started using Nx - amongst a whole bunch of really great experience!  As such, a fix for this would be the most exciting and productive improvement to Nx for me.
