### ISSUE TITLE
Invalid TS Path mapping

### ISSUE THREAD

**Issue by shlomiassaf** [nrwl/nx#3259]
## Current Behavior

Some TS path mapping expressions supported by TS are not supported by `tsconfig-paths-webpack-plugin` resulting
in webpack unable to resolve the modules using the plugin

The issue is ofcourse in more complex scenarios, in simple scenarios it works great.

> Notice that the issue is most likely coming from [tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths) but it's hard to tell because `tsconfig-paths-webpack-plugin` is using it under the hood and I didn't debug it

## Expected Behavior

TS mappings valid in TS should work in webpack as well.

## Steps to Reproduce

Consider the following mappings

```
      "@sg/nest/auth": ["packages/nest/auth/src/index.ts"],
      "@sg/nest/auth/*": ["packages/nest/auth/*"],
```

If you were to consolidate them:

```
      "@sg/nest/auth*": [
        "packages/nest/auth*",
        "packages/nest/auth/src/index.ts"
      ],
```

It will not work...
Running build or server will pass type checking but will throw on runtime.

----

I understand this is not a direct error of the library but perhaps it can be workaround using custom alias or something or you guys approaching the 3rd party for a fix... I don't know where the error is.

It took me some time to pinpoint this because the implementation is hidden within nx and this is why I opened it here because developers will find it hard to understand the origin of the error.

**Comment by samcraigdev** [comment]
Doing something similar with library specific path aliases instead of using `../` navigation for publishable libraries, but hitting a wall with runtime / typing output as the imports are not being converted.

**Comment by samcraigdev** [comment]
Before a fix / improvement to config overrides exists, here's a patch that is currently working for our development / CI builds:

```diff
--- a/node_modules/@nrwl/web/src/builders/package/package.impl.js
+++ b/node_modules/@nrwl/web/src/builders/package/package.impl.js
@@ -24,6 +24,7 @@ const delete_output_dir_1 = require("../../utils/delete-output-dir");
 const resolve = require('@rollup/plugin-node-resolve');
 const commonjs = require('@rollup/plugin-commonjs');
 const typescript = require('rollup-plugin-typescript2');
+const ttypescript = require('ttypescript');
 const image = require('@rollup/plugin-image');
 const copy = require('rollup-plugin-copy');
 exports.default = architect_1.createBuilder(run);
@@ -97,6 +98,7 @@ function createRollupOptions(options, dependencies, context, packageJson, source
             typescript({
                 check: true,
                 tsconfig: options.tsConfig,
+                typescript: ttypescript,
                 tsconfigOverride: {
                     compilerOptions: {
                         rootDir: options.entryRoot,
@@ -104,6 +106,10 @@ function createRollupOptions(options, dependencies, context, packageJson, source
                         declaration: true,
                         paths: compilerOptionPaths,
                         target: config.format === 'esm' ? 'esnext' : 'es5',
+                        plugins: [
+                            { transform: "@zerollup/ts-transform-paths" },
+                            { transform: "@zerollup/ts-transform-paths", afterDeclarations: true },
+					    ],
                     },
                 },
             }),
```

**Comment by samcraigdev** [comment]
The only issue w/ the above is that it's also converting import references to other library references, looking into overriding the `compilerOptionPaths` that is being passed to `rollup-plugin-typescript2` now.

**Comment by samcraigdev** [comment]
Looks like `@zerollup/ts-transform-paths` just introduced an exclusion rule for any external dependencies. So, for the above patch to work correctly for your libraries, all you have to do is add the local library as a dependency in the `package.json` of the library you're importing from.
