### ISSUE TITLE
nx react feedback

### ISSUE THREAD

**Issue by nickbullock** [nrwl/nx#3269]
Hello,
## Description

I used `nrwl/nx` with angular a lot and I really love it, thanks for your great work. And I want to use it in my next project with react.  
But since there are not so many react nx users I want to share some feedback.  
I just created fresh workspace and react application using nx.

### Component generation
And the first thing I tried to do is to create component using webstorm angular plugin (as I ususally do, because it is really improves my dx and speed) and I found out that there is no such possibility. Angular plugin doesn't work for react project because it looks for `angular.json` and `@angular/cli`. Also there is no vscode/webstorm `nx` plugin and it hurts.

Ok, we still can use cmd to generate a component, so I type `ng g c Filter` and get two prompts!

The first one is `What is the name of the project for this component? `, but `workspace.json` already  have `"defaultProject": "app"`, why should I answer this?

The second one is `Should this component be exported in the project?` - I think if you generate a component for library it should not be exported by default, but of course you can use `--export`. Also I think nx should automatically check the type of the project specified and don't ask for it if this project is application, because the next message is a little embarassing (`The "--export" option should not be used with applications and will do nothing.`)

React users still always name components using pascal casing and it is turned off by default now. But this can be achieved by adding "pascalCaseFiles": true to the schematics section of `workspace.json` so it is ok.

`--directory` option is confusing as well. Even if you type `nx g c list --directory <HereIsMyProjectPath>` nx still asks about what project do you want to use.

So now I must use something like ` nx g c list --project=app --export=false`.

The profit of `ng` cli is when you type `ng g c list` and it is just creates a component. Without any delays and prompts.

**Comment by vsavkin** [comment]
@nickbullock thank you very much for your feedback. @jaysoo for you info.

**Comment by nickbullock** [comment]
@vsavkin @jaysoo UPD
We continue to use `nrwl/nx` in our new project and I will update this post from time to time, if you interested.
So it was my bad and I found that both of this prompts can be skipped with the following `workspace.json` configuration:
```
    "@nrwl/react": {
      "component": {
        "style": "styled-components",
        "pascalCaseFiles": true,
        "project": "shop-admin",
        "export": false
      }
    },
```
and then I'm able to use `nx g c List` and it works like a charm.

But there are still two confusing things:
1)`directory` option. 
How do we usually create a component with `ng`: 
- CTRL-C relative path to the folder where we want to create this component in webstorm/vscode(for example `apps/<my-project-name>/src/app/views/main/components`)
- type `ng g c (CTRL+V here)/List`

and it creates `apps/<my-project-name>/src/views/main/components/list`


`nx` behaves different:
- CTRL-C relative path to the folder where we want to create this component in webstorm/vscode(for example `apps/<my-project-name>/src/app/views/main/components`)
- type `nx g c List --directory (CTRL+V here)`

and it creates ` apps/<my-project-name>/src/apps/<my-project-name>/src/app/list/List.tsx` which is totally I don't want it to be.
2) Barrel files.
React world use barrel files widely.
So we really need something like option `--barrel` turned on by default.
What does it mean:
when generating a component additionally create `index.ts` file for it.
So after generation 
`nx g c List`
we can import it like
`import { List } from 'apps/<my-project-name>/src/views/main/components/List'`
instead of
`import { List } from 'apps/<my-project-name>/src/views/main/components/list/List'`

**Comment by Hotell** [comment]
interesting points of view/suggestions. very nice @nickbullock !

Following 2 statements are vague to some extent and not backed by any data (that's what one gets with less opinionated ecosystems hehe) - I added comments how I see those from my experience to "enrich" feedback to nrwl team. 

> React users still always name components using pascal casing 

Are they? I've been writing production react applications in large teams for 3+ years and I never used PascalCased as it introduces various issues.

> React world use barrel files widely

Using barrels for everything (private API's) mitigates proper tree shaking most of the times and ads another "churn" by having index.ts. Also from internal library standpoint it doesn't matter if you use barrel or not, what matters is "clean" api exported to consumers of your library within monorepo.
- With that said, I agree that a config option should be provided by react schematic plugin (maybe across all schematics that makes sense - node/next/express/react)

**Comment by nickbullock** [comment]
@Hotell 
I described my personal feelings and thoughts using `nx/react` for the new enterprise project started from the ground and of course your experience can be different.

I believe about 90% of small and mid-sized teams (all of silicon valley and LA startups, right?) use CRA as architecture boilerplate. CRA is much more popular than `nrwl/nx` in the react community and It uses pascal casing. So it is the main reason to use pascal casing by default - just to not confuse people. But, anyway, there is an option provided for it.

I agree about barrel files. Maybe we just need one more option.
