### ISSUE TITLE
How to build an nx application in multi-stage docker build 

### ISSUE THREAD

**Issue by moattarwork** [nrwl/nx#327]
I'm building a docker image from my nx project and in my Dockerfile the following line 

`RUN npm run build -- --app=dealmgmtapp --prod --build-optimizer`

throw exception complaining on Typescript module

> Cannot find module 'typescript' from '/'
> Error: Cannot find module 'typescript' from '/'
>     at Function.module.exports [as sync] (/app/node_modules/resolve/lib/sync.js:40:15)
>     at resolveProjectModule (/app/node_modules/@angular/cli/utilities/require-project-module.js:6:20)
>     at Object.requireProjectModule (/app/node_modules/@angular/cli/utilities/require-project-module.js:11:20)
>     at Object.readTsconfig (/app/node_modules/@angular/cli/utilities/read-tsconfig.js:6:48)
>     at new NgCliWebpackConfig (/app/node_modules/@angular/cli/models/webpack-config.js:19:42)
>     at Class.run (/app/node_modules/@angular/cli/tasks/build.js:31:31)
>     at Class.run (/app/node_modules/@angular/cli/commands/build.js:250:40)
>     at resolve (/app/node_modules/@angular/cli/ember-cli/lib/models/command.js:261:20)
>     at new Promise (<anonymous>)
>     at Class.validateAndRun (/app/node_modules/@angular/cli/ember-cli/lib/models/command.js:240:12)
>     at Promise.resolve.then.then (/app/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:140:24)
>     at <anonymous>
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! mezz-dealmgmt-web@0.0.0 build: `ng build "--app=dealmgmtapp" "--prod" "--build-optimizer"`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the mezz-dealmgmt-web@0.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2018-03-13T09_56_51_603Z-debug.log

How we I can solve the issue.

**Comment by bboehm86** [comment]
Works fine for me... What does your Dockerfile look like?

**Comment by xmlking** [comment]
works for me , here  is how I am using 
https://github.com/xmlking/nx-starter-kit/blob/master/.docker/prod.dockerfile#L19

**Comment by moattarwork** [comment]
You right. Thanks for the tip. It works for me now. I had couple of issues related to upgrading to the last tooling for Angular CLI too. BTW thankx.

**Comment by jeffbcross** [comment]
Going to close this issue to keep our issues tidy, but good discussion!

**Comment by Buttars** [comment]
Is there an updated method for this? The nx-starter-kit uses their own custom image now that I would like to avoid unless someone convinces me otherwise.
