### ISSUE TITLE
[Nx 8] Update Angular to latest 8.x

### ISSUE THREAD

**Issue by L2jLiga** [nrwl/nx#3273]
Latest 8.x version (currently 8.12.11) depends on angular cli 8.3.23 same time latest Angular CLI version is 8.3.28

## Description
Is it possible to release Nx 8.x with newer version of CLI?

**Comment by brandonroberts** [comment]
We won't be releasing another Nx 8.x version to bump the Angular CLI. You should be able to bump the patch fixes manually without issue.

**Comment by L2jLiga** [comment]
Angular CLI version is pinned in Nx and I can not update patch and don't duplicate dependencies 😓 

I mean If I will have latest 8.x Nx and latest Ng CLI 8.x installed in project then I will have Ng CLI 8.3.23 (transitive from Nx) and 8.3.28 (direct from package.json)
