### ISSUE TITLE
Using custom builder with workspace.json breaks the nx command

### ISSUE THREAD

**Issue by gszzzzzz** [nrwl/nx#3281]
## Current Behavior

When using `@angular-builders/custom-webpack` with `workspace.json` setup, providing `builder` option with `@angular-builders/custom-webpack` breaks the `nx ...` commands.

## Expected Behavior

Nx command should produces same results, no matter which builder I use.

## Steps to Reproduce

1. Create new Nx environment that uses `workspace.json`.
2. Install `@nrwl/angular` with `@angular-builders/custom-webpack` as dev-dependency.
3. Add new angular application with `nx generate ...`.
4. Update `workspace.json` files as below:
```
...
"architect": {
    "build": {
         "builder": "@angular-builders/custom-webpack:browser",
         ...
    }
}
...
```
5. Save and run `nx build` command.

In above steps, if you change `serve.builder` field, instead of `build.builder`, it will break `nx serve` command.

### Failure Logs

Using `nx build` command:
```
> nx run test-app:build 
Cannot determine versions of "@angular/cli".
This likely means your local installation is broken. Please reinstall your packages.
```

Using `nx serve` command:
```
> nx run test-app:serve 
Cannot determine versions of "@angular/cli".
This likely means your local installation is broken. Please reinstall your packages.
```

Additionally, using `ng serve` (or `ng build`) command:
```
> ng serve
The serve command requires to be run in an Angular project, but a project definition could not be found.
```

### Environment

```
@nrwl/angular : 9.5.1
@nrwl/cli : 9.5.1
@nrwl/cypress : 9.5.1
@nrwl/eslint-plugin-nx : 9.5.1
@nrwl/express : Not Found
@nrwl/jest : 9.5.1
@nrwl/linter : 9.5.1
@nrwl/nest : 9.5.1
@nrwl/next : Not Found
@nrwl/node : 9.5.1
@nrwl/react : Not Found
@nrwl/schematics : Not Found
@nrwl/tao : 9.5.1
@nrwl/web : Not Found
@nrwl/workspace : 9.5.1
typescript : 3.8.3
```

**Comment by vsavkin** [comment]
It looks like you have two copies of @angular-devkit/build-angular in your node_modules. One is likely to be inside @angular-builders/custom-webpack. Remove the inner version to only keep the one at the root (see here how to do it: https://github.com/nrwl/nx/issues/2458) 

Running `> ng serve` won't work in your workpace because there is no Angular CLI.

**Comment by gszzzzzz** [comment]
You were right - my `package.json` has both `@angular-builders/custom-webpack` and `@angular-devkit/build-angular`, and turns out `@angular-builders/custom-webpack` has its own `build-angular` package installed.

Removing `@angular-devkit/build-angular` solved my issue, though I think this might be a common issue among the people who uses both Angular with `custom-webpack` builder. Is there any way for Nrwl to solve this automatically? (e.g., check if there are any duplicated builders everytime user adds dev-dependency, and purge one of them.)

**Comment by luqezman** [comment]
@gszzzzzz any solutions found?

**Comment by brandonroberts** [comment]
Closing as resolved

**Comment by Splaktar** [comment]
I'm using
```json
    "@angular-builders/custom-webpack": "^11.0.0",
    "@angular-devkit/build-angular": "0.1102.1",
```
In the same project with Nx 11.3.x and not seeing problems, so it looks like Nx was indeed fixed to not break in this configuration.
