### ISSUE TITLE
Provide types for JSON output of `--graph`

### ISSUE THREAD

**Issue by maxime1992** [nrwl/nx#3283]
## Description
The commands which generate a graph do not have a type that can be imported so that consumers can know the type of the data. The data is created in this function: https://github.com/nrwl/nx/blob/8cf69c4b9abb2194ee2bbe374b6db97a8dce857b/packages/nx/src/command-line/graph/graph.ts#L1164

## Motivation

Nx is great and the CLI may be enough in some cases.

But when setting up a monorepo some people/company may need to have custom scripts running and thanks to NX we can get a JSON object which represents what has been affected.

On our side we need this and we ended up typing what we needed from the output.

I think it may be quite nice to have that exported by NX so that we can safely consume the JSON output of nx affected commands **even we we update NX version**. 

## Revisions

This issue was originally created for `print-affected` which has been deprecated. I have revised it for the newer commands.

**Comment by maxime1992** [comment]
Bump

**Comment by maxime1992** [comment]
:see_no_evil:

**Comment by maxime1992** [comment]
up

**Comment by maxime1992** [comment]
Up

**Comment by maxime1992** [comment]
Just checked. Still the case.

**Comment by maxime1992** [comment]
Hello bot

**Comment by FrozenPandaz** [comment]
Hey all, I've rewritten this issue to be about the commands which have succeeded `print-affected` but it is still valid. I don't think this is a big change to make and I think someone from the community would be able to make it.

**Comment by paweltwardziak** [comment]
Hi @maxime1992  and @FrozenPandaz I've just raised a PR with the type exposed

**Comment by paweltwardziak** [comment]
Sure thing @FrozenPandaz, thanks
