### ISSUE TITLE
ng add @nrwl/workspace (or schematics) inside existing angular project generate wrong paths in tsconfig.app.json

### ISSUE THREAD

**Issue by billyjov** [nrwl/nx#3285]
## Current Behavior

**tsconfig.app.json**  inside `apps/appname`
```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "types": [
      "node"
    ]
  },
  "files": [
    "main.ts",
    "polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
```

## Expected Behavior

```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "types": [
      "node"
    ]
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts" <-- add src folder
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
```

## Steps to Reproduce

- Take an existing Angular CLI project 
- run the command `ng add @nrwl/schematics` inside the root directory (from git bash)
- After installation take a look at `apps/appname/tsconfig.app.json` file. 

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

- OS: Windows 10
- Angular CLI version: 9.1.0

**Comment by brandonroberts** [comment]
Do you mean `ng add @nrwl/workspace`? `@nrwl/schematics` should no longer be used with version 8 and later.

**Comment by billyjov** [comment]
@brandonroberts Yes!. I also tried with `ng add @nwrl/workspace` and got the same issue.

**Comment by brandonroberts** [comment]
I tried to reproduce this using the following commands:

```sh
npx @angular/cli@9.1.0 new ng3285
cd ng3285
ng add @nrwl/workspace@latest
```

After running those commands, I looked at the `apps/ng3285/tsconfig.app.json` and it looks correct to me.

```ts
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "types": []
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
```

Is there some more specific reproduction instructions you can provide?

**Comment by billyjov** [comment]
I tried it with a new installed app and it's works. But inside our existing app with have the issue.. I'll take a closer look at this and try to find out what is going wrong.

**Comment by brandonroberts** [comment]
Thanks @billyjov. Feel free to reopen this issue if you're still having problems
