### ISSUE TITLE
Path error with nx g @nrwl/angular:lib ui

### ISSUE THREAD

**Issue by matthiasunt** [nrwl/nx#3286]
## Current Behavior
When I run `nx g @nrwl/angular:lib ui` in my freshly created nx workspace and select SASS for stylesheets I'm getting the following error:
`Path "/libs/ui/src/lib/ui.service.spec.ts" does not exist.`

## Expected Behavior
The ui lib gets created as expected.

## Steps to Reproduce
I created a new nx Angular workspace with `npx create-nx-workspace@latest`, selected the Angular preset, SASS and ran `nx g @nrwl/angular:lib ui`.

### Failure Logs
`Path "/libs/ui/src/lib/ui.service.spec.ts" does not exist.`

### Environment
```
  @nrwl/angular : 9.5.1
  @nrwl/cli : 9.5.1
  @nrwl/cypress : 9.5.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.5.1
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.5.1
  @nrwl/web : Not Found
  @nrwl/workspace : 9.5.1
  typescript : 3.8.3
```

**Comment by johnrbaur** [comment]
This appears to be an issue if you have the following configuration in angular.json:

```
"schematics": {
  "@schematics/angular:service": {
    "skipTests": true
  }
}
```

The code behind the @nrwl/angular schematic first calls the @schematics/angular schematic (which generates service files). Then it attempts to delete the service file, without checking if it exists. 

I set the above config to "false", and the library generated correctly.
