### ISSUE TITLE
Cannot find tsconfig.base.json when generating a new app

### ISSUE THREAD

**Issue by matthiasunt** [nrwl/nx#3288]
## Current Behavior
When I run `nx g @nrwl/angular:app app` in my freshly created nx workspace and select SASS for stylesheets I'm getting the following error:
`Cannot find base TypeScript configuration file 'tsconfig.base.json`

## Expected Behavior
The app gets created as expected.

## Steps to Reproduce
`npx create-nx-workspace@latest` with the Angular preset
`nx g @nrwl/angular:app app` with SASS and routing

### Failure Logs
`Cannot find base TypeScript configuration file 'tsconfig.base.json'.`

### Environment
Globally:
```
@angular/cli@9.1.10
@nrwl/cli@9.5.1
```

`nx report` in my project:
```
  @nrwl/angular : 9.5.1
  @nrwl/cli : 9.5.1
  @nrwl/cypress : 9.5.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.5.1
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.5.1
  @nrwl/web : Not Found
  @nrwl/workspace : 9.5.1
  typescript : 3.8.3
```

**Comment by Cammisuli** [comment]
Hi @matthiasunt, do you happen to have the Angular CLI installed globally?

**Comment by matthiasunt** [comment]
> Hi @matthiasunt, do you happen to have the Angular CLI installed globally?

Hi, yes. `@angular/cli@9.1.10`

**Comment by Cammisuli** [comment]
Hmm.. I'm not able to reproduce it locally. I do know that the tsconfig.base.json and all those changes are happening in v10 of Nx and Angular. 

I suspect that something got updated somewhere behind the scenes. This might also be related to the issue you created in #3286.

Do you happen to have Nx installed globally as well?

**Comment by matthiasunt** [comment]
> Hmm.. I'm not able to reproduce it locally. I do know that the tsconfig.base.json and all those changes are happening in v10 of Nx and Angular.
> 
> I suspect that something got updated somewhere behind the scenes. This might also be related to the issue you created in #3286.
> 
> Do you happen to have Nx installed globally as well?

Thanks for the hint. Yes, `@nrwl/cli@9.5.1`.

**Comment by FrozenPandaz** [comment]
Can you please provide the version of `@schematics/angular` that you have or provide a repo to pull down?

The `tsconfig.base.json` is something for v10 which we are working on but should not be required for `9.x`.

**Comment by matthiasunt** [comment]
> Can you please provide the version of `@schematics/angular` that you have or provide a repo to pull down?
> 
> The `tsconfig.base.json` is something for v10 which we are working on but should not be required for `9.x`.

I just downgraded `@schematics/angular` from 10.x to `^9.1.2` and it worked, thanks.

**Comment by zernolo** [comment]
I get the same problem on Angular 10, I'm using a workspace with 4 projects, I'm trying to add a new project

ng generate application xxxx
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
Cannot find base TypeScript configuration file 'tsconfig.base.json'. 

Dependencies I use:
    "@angular/animations": "~10.0.8",
    "@angular/cdk": "^10.1.2",
    "@angular/common": "~10.0.8",
    "@angular/compiler": "~10.0.8",
    "@angular/core": "~10.0.8",

**Comment by florian-kittel** [comment]
I faced the same problem after migrating. There is properly a migration missing where tsconfig.base.json was introduced. So what I simply did is, generating a new app and copy over

- tsconfig.json
- tsconfig.app.json
- tsconfig.base.json
- tsconfig.spec.json

If you have set paths to e.g. internal libs, that paths are now located in tsconfig.base.json.

 ```
// Example of tsconfig.base.json with custom paths
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "@mycompany/my-ui-lib": [
        "dist/my-ui-lib/my-ui-lib",
        "dist/my-ui-lib"
      ],
      "@mycompany/my-direct-included-lib": [
        "projects/my-direct-included-lib/src/index",
        "projects/my-direct-included-lib/src"
      ]
    }
  }
}
```
