### ISSUE TITLE
Lazy loaded modules. Allow exports for services, models etc. [suggestion]

### ISSUE THREAD

**Issue by ph55** [nrwl/nx#329]
Lazy loaded modules could easily have services and models that might be used in other modules.
Services usually used as singletons and accessible from any part of application.
Models or interfaces used for types also across whole application.

Structurally it is still more correct to put these files in module IMO. And export it  from barrel.
Need easy way to allow these files to be exported.

* Maybe adding endings of files that would be allowed for export from lazy-loaded modules.
![image](https://user-images.githubusercontent.com/1386622/37342685-fb2a0e48-26cd-11e8-8cf0-88069a777e94.png)
So the files like `notification.model.ts`, `notification-model.ts`,  `notification.service.ts` would be allowed for export.

* Or maybe allow some folders within lazy-loaded modules. So all files in this folder would be allowed for export.
![image](https://user-images.githubusercontent.com/1386622/37343117-37f1a77c-26cf-11e8-9e5b-d9ac0d5878bb.png)

**Comment by kylecordes** [comment]
The difficulty here is that if you refer to anything concrete in the lazy module, then some of your lazy loaded code won't actually be lazy loaded.  It will be loaded as part of the main module.

Long (**decades**) predating Angular and TypeScript, the solution to this is very well understood though.

Consider an application with main module A, lazy loaded module B.

The difficulty, the thing to avoid, is that if code inside A refers to (depends on) code inside B, at compile time, then module B is no longer really lazy loaded. Parts of it will end up eagerly loaded, compiled into A.

To avoid such a problematic dependency, instead introduce a new module/library/etc. C.  This code will define whatever types, classes etc. are necessary to interact with B. The dependencies are then:

A --> C <-- B

(There is an important caveat with TypeScript. With TypeScript, the types are used only at compile time, not at run time. So there are cases where it is possible to refer to a type, such as an interface, inside a lazy module, without causing the code and that lazy module to be eagerly loaded. Unfortunately as I write this I am not perfectly clear on the rules around this, and recommend caution when relying on it.)

**Comment by ph55** [comment]
Got it. Thanks for detailed explanation.
