### ISSUE TITLE
Support `yarn nx run-many --target=format` for running the formatter on specific projects

### ISSUE THREAD

**Issue by zakhenry** [nrwl/nx#3303]
## Description

I want to be able to run `yarn nx run-many --target=format --projects=a,b,c` to format the projects that I have passed, in the same way that I do for building, linting & testing

## Motivation

I have a pipeline strategy that involves precomputing which nx projects are affected (with `nx print-affected`), and subsequent stages don't do a full git clone (for performance reasons). For build/test/lint I do `nx run-many` with the affected projects, but I can't do that with format, so I resort to cloning the full repo in that step.

## Suggested Implementation

The same as the other run-many targets?

## Alternate Implementations

none, as consistency is the goal here

**Comment by bekos** [comment]
@zakhenry thx for the suggestion 👍 
atm it makes more sense to me to add it as an option to the existing command. I am also thinking to make it work along side `all` option. So 
- `nx format --projects=a,b,c` will format **only the affected** files _inside a,b,c projects_, while
- `nx format --projects=a,b,c --all` will format **all** files _inside a,b,c projects_.

Will this work for you?
