### ISSUE TITLE
Jest: async Angular test

### ISSUE THREAD

**Issue by myin142** [nrwl/nx#3309]
## Current Behavior
Tests on components that use async code (like Promise or Observables) do not get resolved using normal `fixture.detectChanges()` or other similar ways.

## Expected Behavior
I expect that async code gets resolved using `fixture.detectChanges()` or something similar.

## Steps to Reproduce
Create a new angular workspace and add this field to the `AppComponent` typescript file.
```typescript
test = Promise.resolve('Test');
```
Add this part anywhere in the `AppComponent` html file where it will be shown.
```typescript
{{test | async}}
```
And add this new test for `AppComponent`
```typescript
it('should show test', () => {
  const fixture = TestBed.createComponent(AppComponent);
  fixture.detectChanges();
  expect(fixture.nativeElement.textContent).toContain('Test');
});
```
Running `nx test <project-name>` results in a test failure where the expected string `Test` was not found.

### Other Information
Creating a normal angular project where I setup `jest` with `jest-preset-angular` and exactly the same changes, results in a passing test.

There is a way to pass the test by moving the `fixture.detectChanges()` inside the `async()` function and adding another one just before the test:

```typescript
let fixture;

beforeEach(async(() => {
    TestBed.configureTestingModule({
        imports: [RouterTestingModule],
        declarations: [AppComponent],
    }).compileComponents();

    fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
}));

it('should show test', () => {
    fixture.detectChanges();
    expect(fixture.nativeElement.textContent).toContain('Test');
});
```

### Environment

  @nrwl/angular : 9.5.1
  @nrwl/cli : 9.5.1
  @nrwl/cypress : 9.5.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.5.1
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.5.1
  @nrwl/web : Not Found
  @nrwl/workspace : 9.5.1
  typescript : 3.8.3

**Comment by brandonroberts** [comment]
Thanks @myin142, but this is not an Nx issue. A generated test for a component is more of a placeholder for you to update when you start adding functionality.

**Comment by myin142** [comment]
So when the exact same jest test works on a normal angular project but not in Nx, it has nothing to do with Nx? Everything is configured correctly?
