### ISSUE TITLE
@nrwl/linter: builder execution is almost 2 times slower than raw eslint

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#3310]
## Current Behavior
nrwl linter builder is almost 2 times (sometimes even more) slower in comparison with raw eslint execution

demonstration on project that contains 2 files only:

**nrwl linter**
![image](https://user-images.githubusercontent.com/1223799/87180155-4687f700-c2e0-11ea-8330-f99b108fd4b2.png)

**eslint**
![image](https://user-images.githubusercontent.com/1223799/87180168-4daf0500-c2e0-11ea-8692-188f38d2758b.png)

## Expected Behavior

Execute linting with same speed like raw eslint

### Environment
```
  @nrwl/angular : Not Found
  @nrwl/cli : 9.5.1
  @nrwl/cypress : 9.5.1
  @nrwl/eslint-plugin-nx : 9.5.1
  @nrwl/express : Not Found
  @nrwl/jest : 9.5.1
  @nrwl/linter : 9.5.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.5.1
  @nrwl/react : 9.5.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.5.1
  @nrwl/web : 9.5.1
  @nrwl/workspace : 9.5.1
  typescript : 3.8.3
```

**Comment by jdpearce** [comment]
Thanks for raising this, @Hotell - that's an exceptionally long time for two files! Are you able to share the repo?

There may always be a slight overhead in using the builder because we load the files slightly differently to the way eslint does it, but what you have there does seem excessive. 🤔

**Comment by Hotell** [comment]
> Are you able to share the repo?

Unfortunately no...

---

## measurements

I did additional measurements this morning on different library. those time deltas are much smaller, so maybe it was my system overloaded or something (up time was 42 days previously - I rebooted this morning)

**Files linted:** 7

**3 types of execution:**

**1. raw eslint**

`TIMING=1 yarn eslint --ext .ts,.tsx,.js libs/analytics`

**measurement:**

> ⏱ 28.64s

```
Rule                                          | Time (ms) | Relative
:---------------------------------------------|----------:|--------:
@typescript-eslint/no-misused-promises        |   172.145 |    27.0%
@nrwl/nx/enforce-module-boundaries            |   154.725 |    24.2%
etc/deprecation                               |    84.871 |    13.3%
jsdoc/require-hyphen-before-param-description |    37.029 |     5.8%
jsdoc/check-alignment                         |    28.955 |     4.5%
import/no-duplicates                          |    20.665 |     3.2%
tsdoc/syntax                                  |    17.874 |     2.8%
jsdoc/check-indentation                       |    16.725 |     2.6%
@typescript-eslint/no-unused-vars             |     6.990 |     1.1%
react/prefer-es6-class                        |     6.845 |     1.1%
✨  Done in 28.64s.
```

**2. run-command builder**

`TIMING=1 yarn nx run analytics:lint-manual --skip-nx-cache`

**architect:**
```json
"lint-manual": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "command": "eslint --ext=.ts,.tsx,.js libs/analytics"
          }
        }
```

**measurement:**

> ⏱ 41.79s

```
Rule                                          | Time (ms) | Relative
:---------------------------------------------|----------:|--------:
@nrwl/nx/enforce-module-boundaries            |   188.481 |    28.0%
@typescript-eslint/no-misused-promises        |   170.529 |    25.3%
etc/deprecation                               |    80.029 |    11.9%
jsdoc/require-hyphen-before-param-description |    33.656 |     5.0%
jsdoc/check-alignment                         |    28.095 |     4.2%
import/no-duplicates                          |    20.434 |     3.0%
tsdoc/syntax                                  |    18.123 |     2.7%
jsdoc/check-indentation                       |    15.655 |     2.3%
react/prefer-es6-class                        |    10.229 |     1.5%
@typescript-eslint/no-unused-vars             |     7.209 |     1.1%
✨  Done in 41.79s.
```

**3. lint builder** 

`TIMING=1 yarn nx run analytics:lint --skip-nx-cache`

**architect:**
```json
"lint": {
          "builder": "@nrwl/linter:lint",
          "options": {
            "linter": "eslint",
            "tsConfig": [
              "libs/analytics/tsconfig.lib.json",
              "libs/analytics/tsconfig.spec.json"
            ],
            "exclude": ["**/node_modules/**", "!libs/analytics/**/*"]
          }
        }
```

**measurement:**

> ⏱ 33.53s

```
Rule                                          | Time (ms) | Relative
:---------------------------------------------|----------:|--------:
@nrwl/nx/enforce-module-boundaries            |   193.577 |    30.3%
@typescript-eslint/no-misused-promises        |   169.615 |    26.6%
etc/deprecation                               |    78.180 |    12.2%
jsdoc/check-alignment                         |    26.005 |     4.1%
jsdoc/require-hyphen-before-param-description |    22.307 |     3.5%
tsdoc/syntax                                  |    16.091 |     2.5%
jsdoc/check-indentation                       |    16.072 |     2.5%
import/no-duplicates                          |    12.716 |     2.0%
@typescript-eslint/no-unused-vars             |    11.469 |     1.8%
react/prefer-es6-class                        |     6.509 |     1.0%
✨  Done in 33.53s.
```

## observations

- `@nrwl/workspace:run-commands` is the slowest even though just executing underlying raw binary. I think this should be investigated a bit more as I'd expect similar number to raw binary execution (eslint)
- `@nrwl/nx/enforce-module-boundaries` is the main slow down of linting process ( I'd investigate this further and add some perf tweaks to that package. Maybe just TS bump to 3.9 will improve the situation on it's own)
- I'd would be great to reduce that delta between native vs lint builder to less than 5 second ( I assume the number will increase with adding more files)

Lemme know if you need anything more from my side.

**Comment by jdpearce** [comment]
@Hotell Thanks for that. Interesting results.

I don't think the `@nrwl/nx/enforce-module-boundaries` rule has been updated much since it was written so it may not have been massively optimised (if that's possible). This probably bears some further investigation.

If you have any suggestions, or even want to raise a PR...? 😁

**Comment by vsavkin** [comment]
I ran into `@nrwl/nx/enforce-module-boundaries` being slow the other day. I think there are two parts that contribute to it: 
- Circular dep check is written very naively. We should probably use dynamic programming to avoid walking the same paths over and over again.
- TypeScript resolution can be slow. We should experiment with bypassing it for some imports.

**Comment by Hotell** [comment]
I've some more data :)

We've migrated big legacy chunk of codebase to nx, wich has 10k + circular dependencies... with `@nrwl/nx/enforce-module-boundaries` turned on, linting for an app that used some of those parts got stuck indefinitely. Turning this plugin off completely for obsolete parts "fixed" the problem.

It would be great to have more performant implementation going forward.

TY folks

**Comment by JamesHenry** [comment]
This will be addressed in https://github.com/nrwl/nx/pull/3763, where the new builder is a very thin wrapper around ESLint's new (v7+) `ESLint` class

**Comment by Hotell** [comment]
thin wrapper sounds about right. looking forward 👌

**Comment by JamesHenry** [comment]
@Hotell have you had chance to try out the new `eslint` builder in `v10.3.0`?

**Comment by Hotell** [comment]
> @Hotell have you had chance to try out the new `eslint` builder in `v10.3.0`?

- not yet, we have own perf improvements in place. the biggest issue is nx module boundaries rule anyways
- we plan to migrate to 10.3 in 2 weeks, so I'll get back to you with some data

thanks @JamesHenry !

**Comment by 4kochi** [comment]
I would also try to use the new eslint builder. Is there a migration for updating an existing project / lib from tslint to eslint. Or is this a manual step I have to do?

**Comment by JamesHenry** [comment]
@4kochi specifically here we are referring to using the new eslint builder in Nx vs the old eslint builder in Nx - tslint is not involved.

There is a larger effort I am working on around tslint -> eslint migration within Nx workspaces but that is not yet available and is a manual process for now.

**Comment by JamesHenry** [comment]
@Hotell Happy New Year, mate!

I am going to close this one because the `@nrwl/linter:eslint` builder has been around for a few months now and does not have the same issue as originally reported around being much slower than a direct eslint CLI invocation.

**Comment by Hotell** [comment]
@JamesHenry  Happy New Year to you as well buddy! 🍻

Sure thing.

regarding performance I replied within different thread/issue https://github.com/nrwl/nx/issues/2784#issuecomment-751228719
