### ISSUE TITLE
Anuglar update to v 10

### ISSUE THREAD

**Issue by Akxe** [nrwl/nx#3315]
## Description

From: https://update.angular.io/#9.0:10.0l3

> Angular now recommends the use of a `tsconfig.base.json` to help organize the various typings contexts (shared, unit tests, end to end tests, application, etc). `ng update` will migrate you automatically.

None of the angular `tsconfig` files were found. How should I properly upgrade them? I am hesitant to touch them as it is something pretty complicated when combined with NRWL.

**Comment by brandonroberts** [comment]
This will be handled for you with the Nx 10 upgrade migrations. If you want to try it out, use `ng update @nrwl/workspace@next`

**Comment by Akxe** [comment]
@brandonroberts Should I revert upgrading manually then?

**Comment by brandonroberts** [comment]
Yes

**Comment by brandonroberts** [comment]
Try upgrading using the latest beta, and see if that works. If it doesn't, file an issue and we'll look into fixing it

**Comment by Akxe** [comment]
@brandonroberts Angular material did not upgrade... Other than that, pretty smooth
