### ISSUE TITLE
new NPM dependencies appear as a project in print-affected

### ISSUE THREAD

**Issue by zakhenry** [nrwl/nx#3317]
## Current Behavior

When running `nx print-affected`, in the `projects` section, there is an entry `npm:husky`, which is unexpected as it is not an NX library or app.

## Expected Behavior

Only NX projects should be present in the projects field. Unknown if regression.

## Steps to Reproduce

Repro PR: https://github.com/nrwl/nx-examples/pull/108
Steps to repro
1. Run `yarn add --dev husky`
2. Run `nx print-affected | more` and see 

```
➜ yarn nx print-affected | more 
yarn run v1.22.4
$ nx print-affected

>  NX   NOTE  Affected criteria defaulted to --base=master --head=HEAD

{
  "tasks": [],
  "projects": [
    "npm:husky", <--------- Huh?
    "products-e2e",
    "products",
    "cart",

```

### Environment

```
➜ yarn nx report
yarn run v1.22.4
$ nx report

>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 9.5.0-rc.0
  @nrwl/cli : 9.5.0-rc.0
  @nrwl/cypress : 9.5.0-rc.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.5.0-rc.0
  @nrwl/linter : 9.5.0-rc.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 9.5.0-rc.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.5.0-rc.0
  @nrwl/web : 9.5.0-rc.0
  @nrwl/workspace : 9.5.0-rc.0
  typescript : 3.8.3

✨  Done in 0.64s.

```

Update: On further investigation I can see that this is the case for any new npm dependency. It is possible then that this is by design, though it is indeed confusing. 

Ideally (to avoid breaking changes) the `print-affected` output would have the following keys added: `libs`, `apps`, `e2e`, `npm`, providing the list of each scope of project.

**Comment by Hotell** [comment]
> Ideally (to avoid breaking changes) the print-affected output would have the following keys added...

Hmm why would you need that? `npm:` prefix is self explanatory IMO

**Comment by zakhenry** [comment]
It is more self explanatory now there is that prefix I admit (I had previously been running nx@9.2.3 which was not prefixed.

I think the confusing bit is that npm packages are very different to nx libraries/apps - I cannot pass them to any of the (standard) run-many commands, which was my initial intent.

Now there is a prefix I can filter the list of what I pass to `run-many`, but I still think this isn't really the cleanest way of separating what is logically a separate concept

**Comment by FrozenPandaz** [comment]
It is by design.

However, there's a separate property in `print-affected` output for `tasks` which I recommend that you use instead. This is a list of `tasks` that can be run. This will also automatically filter the projects for ones that support the `target` that you supply.
