### ISSUE TITLE
Problem with decorators

### ISSUE THREAD

**Issue by ericgoe** [nrwl/nx#3322]
## Current Behavior
I have a nx workspace. This workspace contains of two projects a backend (nest.js) and a web-frontend (next.js) and a shared library. This library handles the http requests. In the library, I store as well the shared interfaces/DTO's like the following:

```
import { ApiProperty } from '@nestjs/swagger'

export class AccessTokenResponseDto {
    @ApiProperty({
        example: 'xxxxx.xxxxx.xxxxx',
    })
    public token!: string
}

```
As you can see I use the decorator `@ApiProperty` from the `@nestjs/swagger` package. This line is causing the bug.
Using the library on the backend side is fine but importing it on frontend side breaks the website and I receive the following error:

`SyntaxError: {PROJECT}/libs/rest-client/src/dto/auth/access-token-response.dto.ts: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (4:5):`

After some research I changed my `.babelrc.json` to `babel.config.json`. It looks like this change fixed the error above but a new one appeared.

`{PROJECT}/node_modules/@nestjs/common/cache/cache.providers.js
Module not found: Can't resolve 'cache-manager' in '{PROJECT}/node_modules/@nestjs/common/cache'`

I also tried multiple times to reach somebody in slack but I looks like this is a more non-trival issue.

## Expected Behavior
I expect that this works without compilation errors.

## Steps to Reproduce
1. Create a simple nx workspace
2. Add a next.js project and a library.
3. In this library use the @nestjs/swagger decorators
4. Import this library in the next.js project

### Failure Logs
contents of babel.config.json:
```
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "useBuiltIns": "usage",
                "corejs": 3
            }
        ],
        "next/babel"],
    "plugins": [
        ["@babel/plugin-proposal-decorators", { "legacy": true }],
        ["@babel/plugin-proposal-class-properties", { "loose": true }]
    ]
}
```

### Environment
```
>  NX  Report

  @nrwl/angular : Not Found
  @nrwl/cli : 9.4.5
  @nrwl/cypress : 9.4.5
  @nrwl/eslint-plugin-nx : 9.4.5
  @nrwl/express : Not Found
  @nrwl/jest : 9.4.5
  @nrwl/linter : 9.4.5
  @nrwl/nest : 9.4.5
  @nrwl/next : 9.4.5
  @nrwl/node : 9.4.5
  @nrwl/react : 9.4.5
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.4.5
  @nrwl/web : 9.4.5
  @nrwl/workspace : 9.4.5
  typescript : 3.8.3
```

I maybe should add that I have not that much experience in webpack, babel and bundling so far, but I understand it's purpose.

**Comment by pradeeprajr93** [comment]
Facing similar kind of issue with having "Angular" as front-end and "Nest" as back-end due to swagger decorators in interface.

**Comment by pradeeprajr93** [comment]
@FrozenPandaz can you please check this?

**Comment by ericgoe** [comment]
I did a bit of investigation.
To summarize it: Decorators are working, but using them is causing the error. Is there a way to remove decorators?

If you get this error 

`
{PROJECT}/node_modules/@nestjs/common/cache/cache.providers.js Module not found: Can't resolve 'cache-manager' in '{PROJECT}/node_modules/@nestjs/common/cache'
`

then your decorators are working. There has been a misconception. The problem which I and probably @pradeeprajr93 have is that we're using the library on the frontend. The library uses decorators which are importing packages from the backend. (In general decorators are functions. [How do decorators work.](https://www.telerik.com/blogs/decorators-in-javascript)). I do not want to include these packages in the frontend bundle anyway.

So my second thought was to disable decorators when serving/building the frontend. I've tried several packages f.e. 

- [babel-plugin-undecorate](https://www.npmjs.com/package/babel-plugin-undecorate)
- [babel-plugin-remove-decorator](https://www.npmjs.com/package/babel-plugin-remove-decorator)
- [babel-plugin-remove-decorators](https://www.npmjs.com/package/babel-plugin-remove-decorators)

Unfortunately none of them worked. Is there a way to disable/remove decorators ?

**Comment by METACEO** [comment]
So, I don't know how I feel about this, but it is all using mechanisms provided to us. I'll try my best to break it down.

With the below setup, I can import `my-object.ts` from a library in both my Nest project and my Angular project. Nest compiles with the Swagger decorator, and my Angular app compiles after having the Swagger decorator replaced with an empty one. Unfortunately you'd have to do this with all of the decorators that are not cross-compatible. This should also go the other way around, using Angular decorators but replacing them with empty decorators for Nest compiles.

Would anyone have any alternative approaches?.. something feels off about this (maybe the scalability?..) but it is again using mechanisms given to us out-of-the-box - no hacks.

**libs/api-interfaces/src/lib/my-object.ts**
```typescript
import { ApiProperty } from './decorators-nest';

export class MyObject {
  @ApiProperty()
  objectId: string;
}
```

**libs/api-interfaces/src/lib/decorators-nest.ts**
```typescript
export { ApiProperty } from '@nestjs/swagger';
```

**libs/api-interfaces/src/lib/decorators-angular.ts**
```typescript
import "reflect-metadata";

export function ApiProperty(): PropertyDecorator {
  return function () {
  }
}
```

**angular.json**
```
{
  "projects": {
    "my-frontend-angular-app": {
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "configurations": {
            "default": {
              "fileReplacements": [
                // REPLACE THE NEST DECORATOR WITH ANGULAR FRIENDLY
                {
                  "replace": "libs/api-interfaces/src/lib/decorators-nest.ts",
                  "with": "libs/api-interfaces/src/lib/decorators-angular.ts"
                }
              ]
            },
            "production": {
              "fileReplacements": [
                {
                  "replace": "apps/my-frontend-angular-app/src/environments/environment.ts",
                  "with": "apps/my-frontend-angular-app/src/environments/environment.prod.ts"
                },
                // REPLACE THE NEST DECORATOR WITH ANGULAR FRIENDLY
                {
                  "replace": "libs/api-interfaces/src/lib/decorators-nest.ts",
                  "with": "libs/api-interfaces/src/lib/decorators-angular.ts"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            // SPECIFY THE DEFAULT DEFINITION
            "browserTarget": "my-frontend-angular-app:build:default"
          },
          "configurations": {
            "production": {
              "browserTarget": "my-frontend-angular-app:build:production"
            }
          }
        }
      }
    }
  }
}
```

**Comment by pradeeprajr93** [comment]
@METACEO 
Thanks for the workaround. I wish it would work, unfortunately it didn't work for me.
It will be way more helpful if you share a stackblitz project (or similar) with your workaround. 

Thanks

**Comment by METACEO** [comment]
Hey @pradeeprajr93, sorry to hear, I don't know if I can prove this out via stackblitz but I should be able to throw together a quick repo with Nest+Swagger and Angular and the above configurations.

**Comment by METACEO** [comment]
@pradeeprajr93 @ericgoe I've used the strategy I mentioned above (with more validation examples, too) within this example repo: https://github.com/METACEO/nx-demo-swagger-decorators
- It's (cold start) deployed here: https://nx-demo-swagger-decorators.herokuapp.com/
- The commit with the above mentioned strategy is here: https://github.com/METACEO/nx-demo-swagger-decorators/commit/e6ee152272037151cbdadd515e7cda3887498638

**Comment by Meriemi-git** [comment]
Hi everyone !
Can we expect a fix for this ? 
I use a lib shared between my backend and my frontend with models and the Nestjs mongoose plugin with decorators.
It will be very appreciated.

**Comment by charlex** [comment]
Note I have encountered this myself, and would like to figure out a workaround.

I posted this on an existing [SO post](https://stackoverflow.com/questions/54332378/now-sh-build-breaking-due-to-support-for-the-experimental-syntax-decorators-le/65502903#65502903)

**Comment by ZackDeRose** [comment]
There are two issues that I see being brought up here:

1. Decorators playing nice across-frameworks/build environments (babel vs. tsc). We've recently added `@babel/plugin-proposal-decorators` to support [now legacy] decorator implementations going forward for our react babel builds. This should allow for sharing these legacy decorators from shared libs to apps of any lib/framework!

2. The specific example given:
```ts
export class AccessTokenResponseDto {
    @ApiProperty({
        example: 'xxxxx.xxxxx.xxxxx',
    })
    public token!: string
}
```
Exports backend-specific code that you likely do not want in your frontend bundles anyway. In general, `interface`s and `type`s in Typescript offer a good alternative to `class` (as they are transpiled away) for sharing the "shape" of your DTOs across the backend/frontend divide. Perhaps this `class` that lived in a nest-specific lib could implement an `interface` that lived in a `@nrwl/workspace` lib - as a way of keeping your backend and frontend in sync, while still benefitting from the decorators here?

I'll be closing this ticket now as we believe the decorator issue this brought up we believe to be resolved now! Please feel free to reopen if you feel this is not the case!
