### ISSUE TITLE
core: add option to dep-graph that prevents opening browser automatically

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#3324]
## Description
currently when we run `nx dep-graph`, server is bumped up and automatically opens new browser tab, which might be anoyoing for some users.

## Motivation
It would be nice to opt our for advanced users/users familiar with the cli functionality to be able to turn off auto browser tab spawn.

## Suggested Implementation

- open default browser
`nx dep-graph`

- won't open browser
`nx dep-graph --browser=none`

- open particular browser
`nx dep-graph --browser=firefox`

**Comment by philipjfulcher** [comment]
This sounds good, but I think we should follow the convention for `--open` on the `start` command:
https://nx.dev/angular/cli/serve#serve

So the option would be `--open` or `-o`. `dep-graph` would default to not opening the browser and only do so if `--open` or `-o` was provided.

**Comment by Hotell** [comment]
Sure thing @philipjfulcher ! I was trying to mirror similar behavior to create react app which uses open node package with that proposed API (which does what I described for free). I understand it's more helpful to mirror Angular CLI flags for easier migration, although as I understand it correctly nx will not follow Angular CLI /releases parity starting this year according to docs. Pls lemme know if that's old info. Cheers
