### ISSUE TITLE
nrwl/angular -> ngrx dependencies

### ISSUE THREAD

**Issue by VladBozhinovski** [nrwl/nx#3326]
I have an 1 year old generated angular 9 / nx workspace with nrwl/angular package. I want to remove all ngrx dependencies since I'm not using them in the project.

My packages: 
 - @nrwl/angular : 9.3.0
 - @agular/core: 9.1.9

When I remove ngrx dependencies and try to run the project I have issue due to @nrwl/angular has missing dependencies :
 - @ngrx/effects
 - @ngrx/router-store
 - @ngrx/store

Is it possible to have nrwl/angular project without ngrx dependencies?

**Comment by brandonroberts** [comment]
@VladBozhinovski Yes. The `@nrwl/angular` package itself does not depend on the NgRx libraries, so if you aren't using it anywhere, you can remove the dependencies. The dependencies are added when you generate something with the `ngrx` schematic.

**Comment by VladBozhinovski** [comment]
Yes but the thing is I'm getting this when I remove those dependencies

![image](https://user-images.githubusercontent.com/8876745/87323936-b5a75a80-c52f-11ea-8fbd-1fadece788f7.png)

**Comment by brandonroberts** [comment]
If you can provide a reproduction of this issue, we'll take a look

**Comment by VladBozhinovski** [comment]
> If you can provide a reproduction of this issue, we'll take a look

I have hard time reproducing it in Stackblitz. I guess there is no support for NX workspace in stackblitz..

**Comment by brandonroberts** [comment]
Use `npx create-nx-workspace@latest nx3326 --preset=angular --appName=myapp` to create an app. Add the changes to reproduce the issue, create a repo on GitHub and push it up there.

**Comment by mpstv** [comment]
Hi everyone. I have the same issue.

I reproduced it in this [repository.](https://github.com/mpstv/nx3326)

This error occurs after I added import `NxModule` in `app.module.ts`:

```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { NxModule } from '@nrwl/angular';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule, NxModule.forRoot()],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule { }
```
Now after running `ng build`, error will be displayed:
```
ERROR in The target entry-point "@nrwl/angular" has missing dependencies:
 - @ngrx/effects
 - @ngrx/router-store
 - @ngrx/store
```
Why is this happening?

**Comment by brandonroberts** [comment]
I see. The `NxModule.forRoot()` adds the `DataPersistence` service in its providers, which depends on those packages. You don't need the NxModule in that case. Remove the NxModule, and there won't be any dependencies on NgRx.
