### ISSUE TITLE
@nrwl/web:package builder ignores assets

### ISSUE THREAD

**Issue by Ledzz** [nrwl/nx#3328]
## Current Behavior
I have assets section in my project.build.options section:
```
"assets": [{
	"glob": "",
	"input": "libs/mylib/README.md",
	"output": "."
}]
```

this code was autogenerated (I've changed input property). And when I build mylib, the file not copying.

## Expected Behavior
Files copied as stated in assets section.

### Environment
I think this is because of fast-glob release v3.0.0, there is a bullet that says they allow `Only forward-slashes in glob expression.`
https://github.com/mrmlnc/fast-glob/releases/tag/3.0.0

If I go to this line and replace double backward slashes with forward it works fine.
https://github.com/nrwl/nx/blob/master/packages/web/src/builders/package/package.impl.ts#L286

Here's docs of fast-glob:
https://github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows

**Comment by bekos** [comment]
hi @Ledzz :) Can you please elaborate on this issue? Usually the way to write these globs is like this:
```
{
  "glob": "README.md",
  "input": "libs/mylib",
  "output": "."
}
```

Can you try it and let me know if this works for you?

**Comment by Ledzz** [comment]
@bekos yeah, I've tried it, not working too :(

**Comment by bekos** [comment]
@Ledzz using the latest Nx, after generating `mylib` , adding the above snippet into the `assets` of the application and building the application, I'm able to see the README.me file copied inside `dist/apps/myapp` 🤔 Maybe I missed something, can you share a reproduction repository so I can check?

**Comment by Ledzz** [comment]
@bekos I've tried to update `@nrwl/workspace` and it seems to be working know, very strange:/ I'll try on empty repo later

**Comment by bekos** [comment]
@Ledzz I am going to close as it seems to be working also on new projects, but feel free to reopen if you have a reproduction scenario.

**Comment by Ledzz** [comment]
@bekos sry for th delay, here's the repro: https://github.com/Ledzz/nx-assets-repro
I'm using windows 10.
`git clone`, `npm i`, `npm run build:mylib`. File theming.styl is missing in dist folder, but it is specified in workspace.json.

**Comment by Ledzz** [comment]
@bekos should I open a new issue or we could reopen this?
