### ISSUE TITLE
React app not minified. Huge file size.

### ISSUE THREAD

**Issue by muhajirdev** [nrwl/nx#3334]
## Current Behavior

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/12745166/87383013-9574ab80-c5c2-11ea-9879-a41015fec17b.png">

## Expected Behavior

I expect the production code to be minified

## Steps to Reproduce

build the application. Upload it somewhere. see it in web.dev/measure.

### Environment

```

>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 9.5.0-rc.0
  @nrwl/cli : 9.5.0-rc.0
  @nrwl/cypress : 9.5.0-rc.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.5.0-rc.0
  @nrwl/linter : 9.5.0-rc.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 9.5.0-rc.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.5.0-rc.0
  @nrwl/web : 9.5.0-rc.0
  @nrwl/workspace : 9.5.0-rc.0
  typescript : 3.8.3
```

**Comment by puku0x** [comment]
It seems `--prod` option was not provided when you built the app.

```
nx build <project> --prod
```
https://nx.dev/react/cli/build

**Comment by muhajirdev** [comment]
thanks @puku0x . I should have read more the docs deeper
