### ISSUE TITLE
List option --skip-nx-cache in --help output for each command

### ISSUE THREAD

**Issue by darkowic** [nrwl/nx#3338]
## Description

Add option `--no-cache` or similar to force running a command without cache. Or add a simple command to clear the existing cache.

## Motivation

Commands are failing sometimes. For some reason nx is caching also failed command...
```
[darkowic@pop-os] ~/projects/github/nx-examples (react-workbox-issues)
$ yarn build react-example --prod
yarn run v1.22.4
$ nx build react-example --prod

> ng run react-example:build:production 

>  NX   NOTE  Cached Output:

LOADING CUSTOM WEBPACK CONFIG!
Starting type checking service...
Using 2 workers with 2048MB memory limit
Hash: 10507e40f490d48bcd8e
Built at: 07/14/2020 6:33:00 PM
Entrypoint main = runtime.2884de51619a2cb9d571.js main.626f07979a12c0addef9.esm.js
Entrypoint polyfills = runtime.2884de51619a2cb9d571.js polyfills.f1dfc981609339866b63.esm.js
chunk    {0} runtime.2884de51619a2cb9d571.js (runtime) 0 bytes ={1}= ={2}= [entry] [rendered]
chunk    {1} main.626f07979a12c0addef9.esm.js (main) 243 KiB ={0}= [initial] [rendered]
chunk    {2} polyfills.f1dfc981609339866b63.esm.js (polyfills) 239 KiB ={0}= [initial] [rendered]
Segmentation fault (core dumped)
error Command failed with exit code 139.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Suggested Implementation

In description

**Comment by darkowic** [comment]
I found in[ another issue](https://github.com/nrwl/nx/issues/2956) that there is `--skip-nx-cache` flag and I found documentation here - https://nx.dev/react/workspace/computation-caching#skipping-cache

But either `nx --help` or `yarn build react-example --prod --help` doesn't mention it. It would be really helpful to add it.

**Comment by rajeshpal53** [comment]
For skip nx cache output add in command 
--skip-nx-cache

**Comment by zygimantas** [comment]
Is there an environment variable for skipping cache?

**Comment by PayBas** [comment]
> Is there an environment variable for skipping cache?

@zygimantas  Since Nx 13.4.0 you can use `NX_SKIP_NX_CACHE`.
https://github.com/nrwl/nx/blob/13.4.0/packages/workspace/src/command-line/utils.ts#L190
Haven't tried it yet though.
