### ISSUE TITLE
@nrwl/web: index.html is not tracked by webpack in production build

### ISSUE THREAD

**Issue by darkowic** [nrwl/nx#3339]
## Current Behavior

In general, the issue is related to service worker usage with [workbox-webpack-plugin](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin).
In development mode (with `isScriptOptimizeOn=false`) `index.html` is tracked by webpack (with IndexHtmlWebpackPlugin) and injected correctly to service worker by the workbox plugin. But in production mode:
```js
  if (!isScriptOptimizeOn) {
    const {
      deployUrl,
      subresourceIntegrity,
      scripts = [],
      styles = [],
      index,
      baseHref,
    } = options;

    config.plugins.push(
      new IndexHtmlWebpackPlugin({
        input: resolve(wco.root, index),
        output: basename(index),
        baseHref,
        entrypoints: generateEntryPoints({ scripts, styles }),
        deployUrl: deployUrl,
        sri: subresourceIntegrity,
        noModuleEntrypoints: ['polyfills-es5'],
      })
    );
  }
```
whole `IndexHtmlWebpackPlugin` usage is skipped and the `index.html` is not tracked. Therefore automatic index.html revision tracking for the service worker is not possible.

Related to https://github.com/nrwl/nx/issues/3337

## Expected Behavior

`index.html` is tracked by webpack and exists in application chunks.

## Steps to Reproduce

Reproduced in https://github.com/darkowic/nx-examples/pull/1

Steps:
1. Install dependencies `yarn`
2. Apply the patch to generate one production build `yarn patch-package`
3. Build prod `yarn build react-example --prod`
4. Serve the app `npx http-server dist/apps/react-example/`
5. Open the application.
6. Go offline and refresh the page - the application should work in offline mode - it doesn't because there is no `index.html`

### Environment

```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 9.5.0-rc.0
  @nrwl/cli : 9.5.0-rc.0
  @nrwl/cypress : 9.5.0-rc.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.5.0-rc.0
  @nrwl/linter : 9.5.0-rc.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 9.5.0-rc.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.5.0-rc.0
  @nrwl/web : 9.5.0-rc.0
  @nrwl/workspace : 9.5.0-rc.0
  typescript : 3.8.3
```

**Comment by route2Dev** [comment]
Adding the service-worker configuration also causes multiple hashed files of the same chunk (main, polyfills, runtime) to appear in the `dist/apps/react-example` folder when running `nx build react-example --prod`.

I added the relevant service-worker code to a brand new `Nx` workspace and saw the same results. It is disappointing because I was hoping to use a Nx mono-repo for a PWA client project with a node backend.

### Environment
  ```
  nx : Not Found  
@nrwl/angular : Not Found  
  @nrwl/cli : 10.0.7  
  @nrwl/cypress : 10.0.7
  @nrwl/eslint-plugin-nx : 10.0.7
  @nrwl/express : Not Found
  @nrwl/jest : 10.0.7
  @nrwl/linter : 10.0.7
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 10.0.7
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.7
  @nrwl/web : 10.0.7
  @nrwl/workspace : 10.0.7
  typescript : 3.9.7
```

**Comment by darkowic** [comment]
Probably still existing. Didn't have the time recently to take a look

**Comment by darkowic** [comment]
> Probably still existing. Didn't have the time recently to take a look

Keep it. I will someday fix it :D

**Comment by rudfoss** [comment]
Hi, I just ran in to the same issue. Any news on this?
