### ISSUE TITLE
best way to include a possibly out-of-band application

### ISSUE THREAD

**Issue by rhyek** [nrwl/nx#3346]
## Description
What is the best way to include a project in my nx workspace that is a node application that will not need `serve`, `build`, `test`, etc commands? For example, I want to include an application that is basically a sql migration manager/runner and its commands would just be `migrate`, something like `create-migration`, and perhaps `rollback`, and I also want `nx affected:apps` to include it when for example I add a new sql migration file.

I would not mind (and would actually perhaps prefer) to run those specific commands from within the app's folder and not necessarily from my workspace's root.

**Comment by Doginal** [comment]
Hey @rhyek, 

This is a perfect question for the slack community! come join us here: [@nrwl/community](https://bit.ly/2ZApcSo)

**Comment by brandonroberts** [comment]
Thanks @Doginal
