### ISSUE TITLE
nx build runs 'type checking' twice

### ISSUE THREAD

**Issue by borisd** [nrwl/nx#3349]
## Current Behavior
Running ```nx build``` runs type checking twice

## Expected Behavior
Should run only once or even better: offer option to disable with flag

## Steps to Reproduce
New nx project and call ```nx buld <app> --prod```

### Environment
  @nrwl/angular : Not Found
  @nrwl/cli : 9.4.5
  @nrwl/cypress : 9.4.5
  @nrwl/eslint-plugin-nx : 9.4.5
  @nrwl/express : Not Found
  @nrwl/jest : 9.4.5
  @nrwl/linter : 9.4.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 9.4.5
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.4.5
  @nrwl/web : 9.4.5
  @nrwl/workspace : 9.4.5
  typescript : 3.8.3

**Comment by Ledzz** [comment]
Nx builds two times: with es5 and esm for differential loading, that's why you see type checking message two times

**Comment by borisd** [comment]
Do you know if there a way to disable the type checking for a build?

**Comment by Ledzz** [comment]
No :(

**Comment by bekos** [comment]
@borisd indeed, the type checking happens once per build, so this is not so as bug as a feature request to be able to disable type checking 😃 tbh though, I am not so sure that it has any value, because in this case, why use typescript in the first place? 🤔 

Can you please elaborate on the motivation behind it? Is it only for performance reasons?

**Comment by borisd** [comment]
We are using the same code to build a number of similar sites (just different .env). Since moving to NX from plain TS project the build time went up 5x (multiplied for each site). 

Would be nice to be able to run TS check once and have build ignore this step on same build with different env.

**Comment by bekos** [comment]
@borisd It would be weird if such slow build times are caused only by the type checker 😕 I will open an issue so we can investigate it deeper, but for now I will try to send a PR to avoid the type checking for the legacy builds. I hope this is a first good step 😃
