### ISSUE TITLE
move schematic fails when package name does not reflect folder heirarchy

### ISSUE THREAD

**Issue by cdaringe** [nrwl/nx#3354]
## Current Behavior

```ts
externalSchematic("@nrwl/workspace", "move", {
  projectName: schema.projectName, // scopey-my-favorite-lib
  destination: schema.destination, // libs/scopey/something/else, doesn't matter
});
```

crashes with `TypeError: Cannot read property 'map' of undefined`.

### Root cause

This logic assumes 100% parity between package-name and folder structure, which is not always the case.

- a reference to the current folder path is obtained via the `from` key/value pair: https://github.com/nrwl/nx/blob/67dda10d55c24d537bd2751bfa0d61c54b47c240/packages/workspace/src/schematics/move/lib/update-imports.ts#L31-L33
- the folder path is used as a lookup into `tsconfig.json`: https://github.com/nrwl/nx/blob/67dda10d55c24d537bd2751bfa0d61c54b47c240/packages/workspace/src/schematics/move/lib/update-imports.ts#L67-L69
    - ^ this is flawed. as defined in `nx.json`, my package name is not _strictly_ a function of my folder name. if often is, but we have cases where it is not. in this example, my package name is `@project/scopey-my-favorite-lib`, not ` @project/scopey/my/favorite/lib`, thus this script cannot locate the key in `compilerSettings.paths`.

consequently, the lookup fails and results in an uncaught expectation.

## Expected Behavior

- package names should reference definitions `nx.json`, versus assuming a filepath can be converted to a package-name by flipping `-` chars to `/` chars.

## Steps to Reproduce

- add a lib
- rename that lib in nx.json to use `-`s instead of `/`s
- update tsconfig.json to use `-`s instead of `/`s in the path mappings
- run the move schematic
- observe the `file/styles/package/name` lookup fail

### Failure Logs

n/a

### Environment

n/a

**Comment by jdpearce** [comment]
Hi, @cdaringe - thanks for raising a detailed issue! There's a PR in the works to address this already - #3318
