### ISSUE TITLE
My Libs need to access the environments variables inside the Apps

### ISSUE THREAD

**Issue by dulcetti** [nrwl/nx#3355]
Hi guys. My repository has three projects on the `apps` folder. Each project has a self environment file. I have a service folder on the `libs` folder with some services. These services need to use the environment variables of each project in your methods. Bellow, I will show the code...

## Code
Env file on `lp` project:
```
API_URL = https://URL/
AUTHORIZATION = CODE
ORIGIN_CODE = CODE
```

Env file on `modal` project:
```
API_URL = https://ANOTHER_URL/
AUTHORIZATION = ANOTHER_CODE
ORIGIN_CODE = ANOTHER_CODE
```

An example of service:
```typescript
export const fetchData = async (params: IData) => {
  try {
    const url = `${API_URL}path/`;
    const data = (await axios.post(url, params)).data;

    return data;
  } catch (err) {
    throw err;
  }
}
```

The problem is, all projects will have to use the services, so, I need to pass on services the env variables. How can I do this?

I try this:
```typescript
export const fetchData = async (env: IEnvironments, params: IData) => {
  try {
    const url = `${env.API_URL}path/`;
    let data = (await axios.post(url, params)).data;
  } catch (err) {
    throw err;
  }
}
```

The problem is, I need to pass the env variable in all methods calls. It's ok? The NX has a better choice?

Regards.

**Comment by danielfyhr** [comment]
Here's one way to do it. In my opinion your libraries should not be aware of environments. In the code below the "fetchData" is created somewhere in the application lp, and shared within lp. All usages in lp will point to this one function which in turn uses the library.

It is not really a question of NX here, but more of programming practices.

```typescript
// in fetch-data library
export const createDataFetcher = (env: IEnvironments) => async (params: IData) => {
    const url = `${env.API_URL}path/`;
    const data = (await axios.post(url, params)).data;
    return data;
};

// export somewhere in lp, usable in lp:
export const fetchData = createDataFetcher({ API_URL: process.env.API_URL });

// somewhere else in lp
const fetchDataAndDoSomething = async () => {
  const params: IData = { message: 'hello' };
  const data = await fetchData(params); // using the fetchData created above
  // do something with data...
  return data;
};

// export somewhere in modal, usable in modal:
// export const fetchData = createDataFetcher({ API_URL: process.env.API_URL });
```

**Comment by dulcetti** [comment]
@danielfyhr hey, thanks to your answer. It's a good example, I will try here in the project. My questions were if the NX has a another type to execute my example, but your answer refreshes my mind, thanks.

**Comment by dulcetti** [comment]
Hey @danielfyhr, a question. I put the files .env.production and .env.development on lp folder, and run ok. But on build get always the production config.

I saw an example of environments like Angular configuration:
```
apps/
  lp/
    src/
      environments/
        environment.ts
        environment.prod.ts
```

But don't work. Does this last example work on NX React?

Regards.

**Comment by dulcetti** [comment]
When a try to run `NODE_ENV=development nx build lp -c development` nx gets the production environment =/

**Comment by dulcetti** [comment]
Forget my last message, I resolved the question :)
