### ISSUE TITLE
IE 9 infinite looping

### ISSUE THREAD

**Issue by bhupatikrish** [nrwl/nx#336]
**Steps:**
Create a new app using the following steps.
1) create-nx-workspace nx-sample
2) cd nx-sample
3) ng g app sample-app --routing --style scss
4) Update \nx-sample\apps\sample-app\src\polyfills.ts as below.
5) ng build
6) Publish nx-sample\dist\apps\sample-app to web server.
7) Access the app in IE 9.

**Issue:** 
The app goes into infinite loop by appending the current route. For the steps above, /# to the url.
For example if there is /route1 defined and if we navigate to it then /route1/route1 .... appended in the url and it ties to load in a infinite loop.

**Console error**: 
TypeError: Object doesn't support property or method 'apply' 

**polyfills.ts**
-----------

/***************************************************************************************************
 * BROWSER POLYFILLS
 */

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following for the Reflect API. */
import 'core-js/es6/reflect';

/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
import 'core-js/es7/reflect';

/**
 * Required to support Web Animations `@angular/platform-browser/animations`.
 * Needed for: All but Chrome, Firefox and Opera. http://caniuse.com/#feat=web-animation
 **/
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.

/***************************************************************************************************
 * Zone JS is required by Angular itself.
 */
import 'zone.js/dist/zone'; // Included with Angular CLI.

/***************************************************************************************************
 * APPLICATION IMPORTS
 */

/**
 * Date, currency, decimal and percent pipes.
 * Needed for: All but Chrome, Firefox, Edge, IE11 and Safari 10
 */
// import 'intl';  // Run `npm install --save intl`.
/**
 * Need to import at least one locale-data with intl.
 */
// import 'intl/locale-data/jsonp/en';

**Comment by bhupatikrish** [comment]
Looks like its an open issue with angular-cli.
https://github.com/angular/angular-cli/issues/6110

**Comment by Yonet** [comment]
@bhupatikrish thank you for the update. I am closing the issue.
