### ISSUE TITLE
[@nrwl/react] Using publishable libraries ignores CSS in built applications

### ISSUE THREAD

**Issue by ratoi-crysty** [nrwl/nx#3378]
## Current Behavior

When using components inside a @nrwl/react:app from a publishable @nrwl/react:lib, the css from the library doesn't end in the build.  

## Expected Behavior

The CSS from the publishable library components should also be present in the app build

## Steps to Reproduce

Create a workspace for react: `npx create-nx-workspace@latest react-library-css-issue`
Add a publishable react library: `nx g @nrwl/react:lib publishable-foo --publishable`
Add some styling for the "publishable-foo" component 
Use the component from the library inside the application
Build the application (currently it requires to also built the library first, so the command used was: `yarn affected:build`). So for the example repository, the library should be built first and then the application.
Check the result. 

Here's a repo demonstrating this: https://github.com/ratoi-crysty/react-library-css-issue

Please note that his is reproducible only on the built version. When you use the dev version (`yarn start`), the application behaves as expected.

**Comment by montogeek** [comment]
@ratoi-crysty Did you found a solution for this?

**Comment by ratoi-crysty** [comment]
I did find some workarounds, but not a proper solution. I found 2 solutions, both it downsides:

1) Include the build .css. But this means that the library needs to be compiled before the applcation
2) If it's possible, inside the library, do not import the scss files inside each component, but instead create a main scss file that imports all them (or with a hierarchy), and inside the application include the main scss.

As I said, both of them come with some downsides. 
Hope it helps!

**Comment by montogeek** [comment]
@ratoi-crysty Thanks!
I found another solution, it is to add `extractCSS: false` to `workspace.json` configuration, but unfortunately it doesn't work.

I know it works because I changed in the Nx source code.

**Comment by wilkinsonjack1993** [comment]
I am also getting this issue. My design system has React files that import `.scss` files. I then build these in order to publish them to npm using the following command in my workspace.json:
```
        "build": {
          "builder": "@nrwl/web:package",
          "options": {
            "outputPath": "dist/libs/design-system",
            "tsConfig": "libs/design-system/tsconfig.lib.json",
            "project": "libs/design-system/package.json",
            "entryFile": "libs/design-system/src/index.ts",
            "external": ["react", "react-dom", "react-router"],
            "babelConfig": "@nrwl/react/plugins/bundle-babel",
            "rollupConfig": "@nrwl/react/plugins/bundle-rollup",
          }
        },
```
This creates .esm.css, .esm.js, .umd.js, .umd.css files but what I really want is a way to get the css and js to bundle together so that when I import a component from this published package, I get the styles included in that component. Any ideas how I could do this?

**Comment by Tatamethues** [comment]
I'm not sure I'm facing the same issue. I uses postcss in library. It did not get compiled either.

**Comment by ratoi-crysty** [comment]
After further investigating this issue, I think the issue (and therefore the solution) is not as straight forward as I initially thought. 

There are a two things to have in mind here:
- First, I think it's ok that the S?CSS is extracted, bundled, and the import removed, as in this case, it will make the library more easily usable, as it will not require a bundler with the capabilities to extract S?CSS (ex. webpack)
- Second, the issue itself is the discrepancy between the DEV and BUILD versions (for the application). As the dev seems to use the source files directly while the build version uses the built version of the library

While, sadly, I do not have a good understanding of the build/dev scripts to be able to make PR for it. I think the proper solution will be to also use the source files inside the BUILD script, as this will remove the differences between them (even if for some reason it will be configurable). As I see no reason why the BUILD script from the application should use the built version of the library, if the DEV script can properly run with the source files of the library.

If someone has some information why the current BUILD script behaves this way, please give more details on it, maybe it will help us understand how to fix/get around it. 
Thanks!

**Comment by ratoi-crysty** [comment]
This issues seems to be fixed. I could not reproduce it anymore.

**Comment by cforsyth68** [comment]
Have we fixed this bug in NX yet?

It seems to me that the resulting index.js file that gets compiled and output into the /dist/libs/ folder needs to have an import './index.css' in it and then the styles from the index.css get included and built with the project that consumes the library. Or am I missing something?

**Comment by datumgeek** [comment]
@cforsyth68 - have a look at this:
https://nx.dev/packages/web/executors/rollup#extractcss

if you are using `@nrwl/rollup:rollup` for your build, and you change the `extractCss` options property to false, the css will be inline inside the `index.js`

NOTE: case has to be exact (not `extractCSS`) - use `extractCss`

**Comment by cforsyth68** [comment]
> @cforsyth68 - have a look at this: https://nx.dev/packages/web/executors/rollup#extractcss
> 
> if you are using `@nrwl/rollup:rollup` for your build, and you change the `extractCss` options property to false, the css will be inline inside the `index.js`
> 
> NOTE: case has to be exact (not `extractCSS`) - use `extractCss`

Thanks. I figured it out. Learning never stops 😀
