### ISSUE TITLE
Jest unit tests fails when executed from mount directory

### ISSUE THREAD

**Issue by Spandana-01** [nrwl/nx#3388]
### Project structure

**C:\Project1**
  |-- apps
  |-- libs
    &emsp;&emsp;|- - library1
    &emsp;&emsp;&emsp;&emsp; |- - src
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp; |- - lib\component1
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; | - - .ts
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; | - - spec.ts
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp; |- - index.ts
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp; |- - test-setup.ts
    &emsp;&emsp;&emsp;&emsp; |- - jest.config.js
    &emsp;&emsp;&emsp;&emsp; |- - tsconfig.json
    &emsp;&emsp;&emsp;&emsp; |- - tsconfig.lib.json
    &emsp;&emsp;&emsp;&emsp; |- - tsconfig.lib.prod.json
    &emsp;&emsp;&emsp;&emsp; |- - tsconfig.spec.json
    &emsp;&emsp;&emsp;&emsp; |- - tslint.json
    &emsp;&emsp;|- - library2
    &emsp;&emsp;&emsp;&emsp; |- - src
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp; |- - lib\component2
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; | - - .ts
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; | - - spec.ts
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp; |- - index.ts
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp; |- - test-setup.ts
    &emsp;&emsp;&emsp;&emsp; |- - jest.config.js
    &emsp;&emsp;&emsp;&emsp; |- - tsconfig.json
    &emsp;&emsp;&emsp;&emsp; |- - tsconfig.lib.json
    &emsp;&emsp;&emsp;&emsp; |- - tsconfig.lib.prod.json
    &emsp;&emsp;&emsp;&emsp; |- - tsconfig.spec.json
    &emsp;&emsp;&emsp;&emsp; |- - tslint.json
  |-- angular.json
  |-- jest.config.json
  |-- nx.json
  |-- package.json
  |-- tsconfig.json
  |-- tsconfig.spec.json
  |-- tslint.json

### Current Behavior

Unit tests are failing when run from **mount directory**.
 All the test cases are failing with following error.
```

â—? Test suite failed to run
TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
[91merror[0m[90m TS5009: [0mCannot find the common subdirectory path for the input files.

```

> **_(Note: When run from C:\Project1 unit tests are successfully run)_**

### Expected Behavior

Unit test should pass irrespective of mount or normal directory

### Steps to reproduce

-  Mount C\Project1  
`subst X: C:\Project1`

- Execute test cases
`ng test --coverage`

### Environment

"@nrwl/angular": "9.0.3",
 "@nrwl/cypress": "9.0.3",
 "@nrwl/jest": "9.0.3",
 "@nrwl/workspace": "9.0.3",
 "@types/jest": "24.0.9",
    "jest": "24.1.0",
    "jest-preset-angular": "^8.1.3",
    "ts-jest": "24.0.0",

- jest.config.json
```
module.exports = {
  testMatch: ['**/+(*.)+(spec|test).+(ts|js)?(x)'],
  transform: {
    '^.+\\.(ts|js|html)$': 'ts-jest'
  },
  resolver: '@nrwl/jest/plugins/resolver',
  moduleFileExtensions: ['ts', 'js', 'html'],
  coverageReporters: ['html', 'lcov']
};
```
- test configuration for each library in angular.json
```
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "libs/library1/jest.config.js",
            "tsConfig": "libs/library1/tsconfig.spec.json",
            "passWithNoTests": true,
            "codeCoverage": true,
            "collectCoverage": true,
            "codeCoverageExclude": ["**/index.ts"],
            "setupFile": "libs/library1/src/test-setup.ts"
          }
        }
```

- nx.json
```
{
  "npmScope": "dp-gre",
  "implicitDependencies": {
    "angular.json": "*",
    "package.json": {
      "dependencies": "*",
      "devDependencies": "*"
    },
    "tsconfig.json": "*",
    "tslint.json": "*",
    "nx.json": "*"
  },
"projects": {
    "library1": {
      "tags": []
    },
    "library2": {
      "tags": []
    },
}
}
```

**Comment by Cammisuli** [comment]
This might take me some time to set up as I don't have Windows readily available for me :(

**Comment by zoechi** [comment]
I think they should be linked facebook/jest#10429
