### ISSUE TITLE
e2e execution error

### ISSUE THREAD

**Issue by FallenRiteMonk** [nrwl/nx#339]
Using version 0.9.0 when i try to run ```ng e2e --app admin``` I get the following error: ```Please provide the app name using --app or -a.```. It only works if I run the following command: ```ng e2e --app=admin```
(Equal sign required)

This is strange because ```ng serve --app admin``` works just fine

**Comment by jschwarty** [comment]
Was able to reproduce. Looks like this message is coming from Nx code here: https://github.com/nrwl/nx/blob/fcec9dc1c0468514b4a8f05f1c83bc59c6f14778/packages/schematics/src/utils/cli-config-utils.ts#L22

TODO: Need to update [`findAppArg`](https://github.com/nrwl/nx/blob/fcec9dc1c0468514b4a8f05f1c83bc59c6f14778/packages/schematics/src/utils/cli-config-utils.ts#L36) to support no equals

**Comment by FrozenPandaz** [comment]
I can take this

**Comment by FrozenPandaz** [comment]
This should be fixed as of `0.10.0`. Let me know if there are any issues with this.
