### ISSUE TITLE
Introduce Playwright as option for E2E testing

### ISSUE THREAD

**Issue by Lonli-Lokli** [nrwl/nx#3390]
## Description
Support for Playwright developed by Microsoft (https://github.com/microsoft/playwright) as option for e2e testing

## Motivation
Current option (cypress) has limitations in API + only chrome based, while Playwright supports chrome, Firefox and webkit

## Suggested Implementation
Existing integration with Jest, already used by Nx - see https://github.com/playwright-community/jest-playwright

**Comment by FrozenPandaz** [comment]
Looks like a great tool! For what it's worth, cypress also now includes support for Firefox and Edge :tada:.

We don't have any plans on adding support for more e2e tools. This sounds like an awesome plugin for someone to maintain though! Would anybody like to work on this?

**Comment by Bielik20** [comment]
@FrozenPandaz Would you accept a PR to make current Jest builder more "extendable"? I made a plugin by merging some parts of your jest and cypress executors. I would like to avoid copying code so I would like to extract some parts of jest executor to separate functions so that I could use them.

**Comment by Sam-Lin-MillersLab** [comment]
it's ashamed. playwright supports WebKit and multiple tabs. Cypress is good but playwright has some advantages for different use cases. I think it might be time to rethink the decision.

**Comment by StephenStrickland** [comment]
Playwright support would be incredible, probably the main thing holding me back from Nx.

**Comment by rickvandermeij-aanzee** [comment]
@FrozenPandaz Maybe you can reconsider the option to support playwright instead of cypress. Cypress is not completely free, whereas you need subscriptions to get the full benefit of cypress. Playwright is completely free, which will suit better at nrwl/nx

**Comment by Sam-Lin-MillersLab** [comment]
@rickvandermeij-aanzee I think free or not free is not the key. The key is Cypress just doesn't meet the requirement for enterprise usage. 50% of our users use Apple devices. Apple device consumers are more willing to pay for certain type of goods. It is the fact that enterprises have to support Safari. I honestly can't believe Cypress didn't start with webkit support in mind.

**Comment by herodriguez7** [comment]
Hi all,

Sorry to resurrect an old issue but I'm really just trying to figure out if this is, or is not, possible? Does nx support integration and usage of Playwright for the e2e tests project?

Also, if it does, is it strictly for playwright-jest? As opposed to using Playwright's recommended test runner, Playwright Test?

Thank you for any insights you can shed; am new to all of this.

**Comment by rickvandermeij-aanzee** [comment]
@herodriguez7 we use playwright in our NX monorepo, it just doesnt come standard out of the box, but everything is working fine, even the affected

**Comment by prewk** [comment]
Yeah and you can just add it and pretend nx doesn't exist if you want. You don't need the integration.

**Comment by humbienri** [comment]
Thanks @rickvandermeij-aanzee! Did you have to write up your own generators and executors to then be able to leverage some of the "affected" scripts/commands?

**Comment by rickvandermeij-aanzee** [comment]
we use a mockserver to connect as our service, so we can easily manage responses.

i cannot dump all of the code (yet) but below should create the affected for any e2e.
set your app as an implicitDependency to target e2e as affected

we do not have written any own generators for now, but maybe thats something what we will add, when it will become too much metadata to set up for.

in our e2e project:
```
"e2e": {
	"executor": "@nrwl/workspace:run-commands",
	"options": {
		"command": "START_SERVER_AND_TEST_INSECURE=1 start-server-and-test 'nx serve app --configuration=mock' 'https://localhost:4202/' 'APP=apps/app-e2e npx cucumber-js --config cucumber.base.js'"
	},
	"configurations": {
		"no-serve": {
			"command": "APP=apps/app-e2e npx cucumber-js --config cucumber.base.js"
		}
	}
},
```

in our package.json
`"affected:e2e": "start-server-and-test 'nx serve mockserver' 'http://localhost:3999/mocking' 'nx affected:e2e --base=$npm_config_base'",`

**Comment by rickvandermeij-aanzee** [comment]
If anyone wants to play with a starterkit containing playwright: https://github.com/rickvandermey/angular-starterkit/tree/develop checkout the develop branch, Will add Visual Regression tests with playwright and storybook as well in the future

**Comment by rockse** [comment]
We have released an NX plugin for playwright https://github.com/marksandspencer/nx-plugins/tree/main/packages/nx-playwright using native playwright runner

We have a team that supports it too. So feel free to raise an issue or pr : )

**Comment by Camo30** [comment]
@FrozenPandaz I think this issue should still be open. Are there any plans to integrate playwright more closely?
