### ISSUE TITLE
Performance Issues with Boundaries Lint Checks

### ISSUE THREAD

**Issue by vsavkin** [nrwl/nx#3393]
When moving a very large repo from Nx 8 to Nx 9, we noticed a significant slowdown in running the boundaries lint checks. From what I can tell, these are the issues:

1. The circular dependencies check can be very flow in large projects. This is because we traverse the same graph over and over again. Instead of doing this, we can use dynamic programming and cache traversed sub-paths. The number of total traversals should become O(EdgesInProjectGraph).
2. If a circular dependency is found we don't print the path. We just say somehow A and B depend on each other. We should print the path.
3. TypeScript module resolution is slower than the one we used before. We need to find out how much slower and if it is significant, figure out a way to speed it up. Maybe run the first resolution first, maybe cache the resolved paths etc.
4. Both ESLint and TSLint should become faster.

**Comment by Hotell** [comment]
related: #3310
