### ISSUE TITLE
Reload of app not working out of the box when changing a lib

### ISSUE THREAD

**Issue by masaanli** [nrwl/nx#3394]
## Current Behavior

When using a library in an app and then change the library the app will not reload automatically.

## Expected Behavior

I was expecting that the app will reload because it depends on the library.
(the only way I achieved this was by adding this to by app:
```
"implicitDependencies": ["button"]
```
Then when I change the button component it will reload my app.

I cannot imagine this is a manual step? Because it's not a global file or something, it can automatically detect that button was imported from that library right? Seems like implicitDependencies is the wrong place?

### Environment

  @nrwl/angular : 9.1.2
  @nrwl/cli : 9.1.2
  @nrwl/cypress : 9.1.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.1.2
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.1.2
  @nrwl/web : Not Found
  @nrwl/workspace : 9.1.2
  typescript : 3.7.5

**Comment by shinjucommunications** [comment]
Tried a restart of nx serve?

**Comment by FrozenPandaz** [comment]
Hm, a lot of details are missing and not using the latest version of Nx.

Can you please try the latest version of Nx and see if the issue is still reproducible? If so, please provide a repro so we can take a look.
