### ISSUE TITLE
Build Storybook only for affected libs

### ISSUE THREAD

**Issue by iceteabottle** [nrwl/nx#3397]
## Description
I'm currently working on a big nx based project. We plan a lot of apps so for us building only affected apps is really important feature. Our CI builds always affected apps. It would be great if we could build storybook only if the used library is really affected. Now we have build it always.

## Motivation
As described above: It would be great if we could save the build time and storybook could be build only when the used lib is affected.

## Suggested Implementation
I imagine it should be possible to use the same logic that is used for identifying affected apps.

## Alternate Implementations
...

What do you think?
Thanks!

**Comment by FrozenPandaz** [comment]
I believe the command you are looking for is the following:

```
nx affected --target build-storybook
```

Does that suit your needs?

**Comment by iceteabottle** [comment]
Ah! Perfect, thanks!
