### ISSUE TITLE
Changes to location and structure of nxdeps.json file

### ISSUE THREAD

**Issue by capJavert** [nrwl/nx#3404]
## Description
We are using the NX for managing monorepos at our company for few months now. With nx we use Docker based deployment. Because of that we created some custom scripts to make sure our Docker images remain as small and performant as they can be for each of our applications (they vary between React, Express, Nest and other).

One of the issues we had with NX is because of the root `package.json` principle. Our docker images would always include all the combined node_modules from root `package.json`. Because of that we created custom script that would at build time analyse `nxdeps.json` file and create separate package.json (for each of our apps) that could be used to create Docker images and include only required packages for each app respectively.

We did all of this during 9.x era of NX library. Recently we also upgraded NX to 10.x along with our other depdendencies. What we noticed that for some reason we would no longer get `dist/nxdeps.json` file after build or any other action like `dep-graph` or during development. Which was strange. After some research we noticed that this [feat(core): redesign workspace file hashing](https://github.com/nrwl/nx/commit/67dda10d55c24d537bd2751bfa0d61c54b47c240#diff-e41e2a43730009e7f6efea0b50dbee46R13) changed how `nxdeps.json` file is generated and also altered:
- JSON structure
- location of the file (new location is `node_modules/.cache/nx/nxdeps.json`

We get it that major version can introduce breaking changes (which is fine) but we also think that this should have been noted in release notes.

By looking at other issues we can see that in few places there is a recommendation to use `nxdeps.json` to analyse dependencies for use cases like ours. For example
- https://github.com/nrwl/nx/issues/1972
 It would be great if you could give some more light on this subject.

We were able to quickly adjust our script to accommodate these changes to `nxdeps.json` location and structure but we were wondering if this is something we can expect in the future and how often?

**Comment by FrozenPandaz** [comment]
Cool script! We do not consider `nxdeps.json` as a public API. I think what you want to achieve can be done more idiomatically with `nx dep-graph --file graph.json`. How does that sound in terms of the command?

I believe it is currently missing `npm` projects though which can be a separate issue.

**Comment by capJavert** [comment]
@FrozenPandaz thanks for your response. graph.js file created with command you mentioned produces json file of the sam format as nxdeps.json (except for missing npm dependencies) - so if nxdeps.json is not public API then graph.json produced with graph command also is not part of public API.

Including npm dependencies into graph command would just produce same results.

I am wondering about future plans for nxdeps.json format - if you have some more info on that?

Any other tips on solving our problem from original comment?

**Comment by capJavert** [comment]
Bump. Any further plans for this?

**Comment by Maks-Yaremenko** [comment]
I'm also wondering how to get deps per project, @capJavert, are you figured out how to do this? Thank you.

**Comment by capJavert** [comment]
Not really, we still have an internal script that manually resolves this with few manual dep hints. 

I think this feature is still very relevant and needed in nx toolset.

**Comment by Maks-Yaremenko** [comment]
totally agree with you.
