### ISSUE TITLE
Support of eslint in Angular 10 ?

### ISSUE THREAD

**Issue by iangregsondev** [nrwl/nx#3408]
Hi,

I just created a new NX app that consists of one angular app. (Angular 10)

I noticed that it is still creating tslint (deprecated), do you know what our options are to install eslint?

Has anybody physically done this yet?

Thanks in advance

**Comment by brandonroberts** [comment]
There is a workaround in https://github.com/nrwl/nx/issues/1699. Closing as a duplicate
