### ISSUE TITLE
run-commands pass current project via environment variable

### ISSUE THREAD

**Issue by mac2000** [nrwl/nx#3412]
## Description

At moment we can add any set of custom commands via `@nrwl/workspace:run-commands` which is awesome, but we can not copy paste them between projects because of need to specify project name, dist path, etc

## Motivation

In my case I wish to have simple step something like

```json
{
  "archive": {
    "builder": "@nrwl/workspace:run-commands",
    "options": {
      "cwd": "dist/apps/demo",
      "command": "zip -q -r demo.zip ."
    }
  }
}
```

## Suggested Implementation

I can see that while starting process we are [fulfilling environment variables for it](https://github.com/nrwl/nx/blob/master/packages/workspace/src/builders/run-commands/run-commands.impl.ts#L155) wondering if there is a way to get something about project we are building right now?

## Alternate Implementations

Alternative might be to build kind of own run-commands analogue on top of current but to me it seems like it will be yet another lib

**Comment by FrozenPandaz** [comment]
Hm, I think writing a workspace-schematic that generates the command with the project name will serve you better than "copy and pasting" between different projects in `workspace.json`.

I think with the ability to interpolate arguments in `nx affected` and `nx run-many` via `nx affected --target echo --command "echo {project.name}"` which needs to be done because those are overrides for multiple projects there isn't a major need to provide it via environment variables to `run-commands`.

**Comment by mac2000** [comment]
Indeed, did not figured out how it can be used in this case, thank you for a point, if someone will read this in future here is how you can have any kind of scripts without making any additional schematics:

**angular.json**

```js
// ...
  "myscript": {
    "builder": "@nrwl/workspace:run-commands",
      "options": {
        "command": "sh tools/scripts/myscript.sh {args.project}"
      }
  }
// ...
```

**myscript.sh**

```bash
#!/bin/sh
set -e

if [ "$1" == "" ]
then
  echo "project name is missing, exiting..."
  exit 0
fi

project=$1
dist=$(cat angular.json | jq -r ".projects.$1.architect.build.options.outputPath")

echo "project: $project" # project: demo
echo "dist: $dist"       # dist: dist/apps/demo
```

usage:

```bash
yarn nx affected --all --target=myscript --args="--project={project.name}"
```
