### ISSUE TITLE
Give an option to "remove" the lib folder inside the src folder of a library.

### ISSUE THREAD

**Issue by kingbreddo** [nrwl/nx#3414]
## Description
At the moment, the source files of a library are placed in the `src/lib` folder.
Personally I don't think that the `lib` folder adds any value to the folder structure.
Because the libraries are already placed inside the `libs` folder, that already indicates that it is a library.
In my view, the `src/lib` folder looks double. It creates an extra folder in the folder structure that you have to open.

Personally I was thinking of adding an option to allow the generation of the lib folder.

I don't know what other NX users think about this.
I like to discuss this with other contributes and maybe convert it to a feature request.

**Comment by Hotell** [comment]
I'd disagree
- having `/lib` and `index.ts` as 2 separate entities, explicitly reflects public API, also make easier automation tasks like generation etc

**Comment by vsavkin** [comment]
I don't feel very strongly about the layout, but I'd prefer not to have an extra option for all the schematics generating libs. It's more code to maintain, more opportunities for bugs. You could, of course, create a workspace schematic that wraps the library schematics and removes the lib folder, or create a separate plugin altogether. 

I'm going to close this one. Thank you!
