### ISSUE TITLE
cannot build publishable & buildable library with sub-entries unless using dist path

### ISSUE THREAD

**Issue by nadavsinai** [nrwl/nx#3417]
## Current Behavior
Unless directing tsconfig path to dist folder, some of my workspace libraries fail to compile
with out of rootDir error.

for example when compiling our lib `sticky-notes` with it's tsconfig.json extending your regular tsconfig.base.json
in which it could find '@algotec/ui-elements-webkit/*' pointing to ["libs/ui-elements/*"]
I get errors like these:

````
libs/sticky-notes/src/sticky-notes.module.ts:24:30 - error TS6059: File 'F:/client-workspace-2/li
bs/ui-elements-webkit/dropdown/index.ts' is not under 'rootDir' 'F:\client-workspace-2\libs\stick
y-notes\src'. 'rootDir' is expected to contain all source files.
````

If I change to extend an alternative tsconfig.lib.json which changes all the paths to dist/libs/<libname> the library can compile, but I have to get the compilation order right.

what's confusing is that I found that *some* libraries that have secondary entry points and relay on libs with secondary entry points do work, I am yet to find an explanation for that.
this issue is probably related to #2794 @juristr I'd love your help debugging this.

## Expected Behavior
Compile buildable & publishable libraries also when they have secondary entry points

## Steps to Reproduce
I did try to create a new workspace only for reproduction of this error and didn't succeed yet.
I will update here and point a link whenever I make it.

### Environment

````
  @nrwl/angular : 10.0.6
  @nrwl/cli : 10.0.6
  @nrwl/cypress : 10.0.6
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.0.6
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.6
  @nrwl/web : Not Found
  @nrwl/workspace : 10.0.6
  typescript : 3.9.7

````

**Comment by juristr** [comment]
hey @nadavsinai...weird 🤔 . Can you provide a sample repo where I could reproduce the build issue?

**Comment by ganeshpms** [comment]
Try ading paths to the sub folders, `dist` path may require you delete the `dist` to build from source , and make sure you keep your `ng-package.json`, and `package.json`  under 'src/lib'
```
      "@scope/library/entry1": ["libs/library/src/lib/entry1/index.ts"],
      "@scope/library/entry2": ["libs/library/src/lib/entry1/index.ts"]
```
instead of
```
 "@scope/library/*": ["dist/library/*" , "libs/library/*"],
```

**Comment by nadavsinai** [comment]
HI @ganeshpms , thanks for your reply. This is not so feasible for us.
For example under ui-elements-webkit (ui components package) we currently have 74 subpackages, moreover putting each sub-package in the global tsconfig is another manual step developers need to do to create a new subpackage - which something we want to encourage not hinder.
I would try this only for testing and report back.
aswell, I am still trying to find the time to create a reproduction repo (same config omitting our code )

**Comment by ganeshpms** [comment]
> HI @ganeshpms , thanks for your reply. This is not so feasible for us.
> For example under ui-elements-webkit (ui components package) we currently have 74 subpackages, moreover putting each sub-package in the global tsconfig is another manual step developers need to do to create a new subpackage - which something we want to encourage not hinder.
> I would try this only for testing and report back.
> aswell, I am still trying to find the time to create a reproduction repo (same config omitting our code )

**Comment by ganeshpms** [comment]
ah, I see your point, we will also hit the same issue soon. I just tried as following after your reply, it works with just two paths.  It works also with another publishable library which has reference to this library.
```
"@scope/library": ["libs/library"],  // <--- Publishable used by @nrwl/angular:package
"@scope/library/*": ["libs/library/src/lib/*"], //<-- Buildable used by @angular-devkit/build-angular:browser and editor (vscode)
```

to make it work, I just made sure the publishable build the components library as following, instead of the default `src/lib/entry1`
```
------------------------------------------------------------------------------
Building entry point '@scope/library/entry1'
------------------------------------------------------------------------------
```

by keeping the `ng-package.json` , `package.json` inside `src/lib`  and `angular.jason`

```
      "root": "libs/library/src/lib",
      .
      "architect": {
        "build": {
          "builder": "@nrwl/angular:package",
          "options": {
            "tsConfig": "libs/library/tsconfig.lib.json",
            "project": "libs/library/src/lib/ng-package.json"
```

**Comment by nadavsinai** [comment]
I did test it with the 74 direct references to the subpackages in the paths object and it did not work.
I must be missing on something here
my library has a root of `/libs/library
and the project (ng-package.json) and tsconfig properties of the builder options look like this :
````
	"tsConfig": "libs/library/tsconfig.lib.json",
	"project": "libs/library/ng-package.json"
````

in addition subpackages exist directly underneath root - not underneath src
eg `libs/library/subpackage` (with it's own package.json and index.ts) 
I don't understand howcome your examples state for library/src/lib (assuming lib is a subpackage name) if src it the location for the main package's code - how will the subpackages code won't be included in the main package in this scenario?

**Comment by nadavsinai** [comment]
I found this was my fault: some of the libraries had another builder - not "@nrwl/angular:package" but our own extended-lib-builder which adds stuff such as assets copying, pre/post build commands and other goodies, but internally it used ng-packager without the special runtime path mapping you're doing in package.imp.js (line 20)
`buildable_libs_utils_1.updatePaths(projectDependencies, parsedTSConfig.options.paths);`

I changed our own builder to use the `run` function from `@nrwl/angular/src/builders/package/package.impl` (pity it isn't exposed from top-level) and now we got the expected behavior

**Comment by imcvakt** [comment]
Hi, I'm facing the same issue but with react project... Can you provide me more info about the workaround? I know it's closed but...

**Comment by HackPoint** [comment]
> Hi, I'm facing the same issue but with react project... Can you provide me more info about the workaround? I know it's closed but...

They care more about making features that no one needs instead of fixing the ones that exists.
@vsavkin can you please help ppl with that?
