### ISSUE TITLE
`nx affected` should take into consideration also previous failed jobs

### ISSUE THREAD

**Issue by sgametrio** [nrwl/nx#3419]
## Current Behavior
Using `nx affected:test --base=$BASE_SHA --head=$HEAD_SHA` in the Gitlab CI/CD could bypass some failing tests.

What is the best practice while using `nx affected` in the CI/CD?

I'm asking because I don't know if there is a _by design_ way which will run also the previous failed tests.

As of now I'm saving the last successful build commit SHA in order to re-test also failed tests but I think this should be pointed out somewhere in the docs (if it's by design), or   

## Expected Behavior
Failed tests from previous runs should be run again until they pass. Maybe with the help of the caching system.

## Steps to Reproduce
The scenario is the following:
1. HEAD is at commit A.
2. We introduce a change (through a commit B) in a file which triggers the re-run of a test T1.
3. The pipeline is triggered through a push and `nx affected:test --base=A --head=B` is run.
4. T1 fails, blocking the pipeline.
5. I update something else in my codebase (commit C), which doesn't modify T1 or its deps.
6. The pipeline runs `nx affected:test --base=B --head=C` but T1, who should fail, is not run because is not affected by the latest diff. Therefore the pipeline pass, giving me the feeling that everything is ok, when T1 instead will still fail if run.

**Comment by FrozenPandaz** [comment]
I think what you are trying to avoid is re-running passed projects during your pipeline?

If so, you'll see pretty much the same results if you use Nx Cloud (or save the cache) to cache the results. The changes in `A => C` will include the full set of projects but projects that already passed during the `A => B` run and were not touched in `B => C` will be cached and not rerun.

Does this help you achieve what you want?

**Comment by sgametrio** [comment]
Yes, I would like to avoid to run them twice, but also let the pipeline fail if a test hasn't been fixed/touched during a push.

Let me be more clear: to achieve that in my GitLab CI/CD I'm using, each time I push:
```
nx affected --target=test --base=$CI_COMMIT_BEFORE_SHA --head=$CI_COMMIT_SHA
```
where `$CI_COMMIT_BEFORE_SHA` is the latest commit prior to the commits introduced with the push. 

Now, Pushing the commit B, let the project P **fail** because of a test T1. In the meantime I push C which doesn't touch project P, therefore the `nx affected` will not run tests for T project, letting the pipeline to pass. This is misleading because the pipeline should fail (and block the subsequent stages for example) since there is still a failing test in my codebase.

This could be easily solved if Gitlab would provide the last successful pipeline commit. So that I can use it instead of the variable $CI_COMMIT_BEFORE_SHA.

I will investigate more the usage of the Nx Cloud and caching system, but I feel like `nx affected:test` should address, or point out somewhere in the doc, this problem.

Don't know if you agree.

**Comment by Wazbat** [comment]
I just wanted to chime in and say that I agree completely. As someone new to nx this took a while to figure out. I really do feel that the docs should be updated your example, stressing the importance of it being the sha of the last succesful build

I'm using google cloud build, so I used the following inside of the `gcloud` builder which runs this bash script
```bash
echo "Fetching curent build's trigger ID"
BUILD_TRIGGER_ID=$(gcloud builds describe ${BUILD_ID} --format="value(buildTriggerId)")
echo "Fetching last succesful build for trigger ID $BUILD_TRIGGER_ID"
LAST_ID=$(gcloud builds list --filter "status='SUCCESS' AND buildTriggerId='${BUILD_TRIGGER_ID}' AND substitutions.BRANCH_NAME='${BRANCH_NAME}'" --format="value(id)" | head -n1)
if [ -z "$LAST_ID" ]; then
    echo "No past builds found, not creating the $TEMPORARY_COMMIT_SHA_FILE file to reflect this"
    exit
fi
echo "Describing Last build: $LAST_ID"
COMMIT_SHA=$(gcloud builds describe $LAST_ID --format="value(substitutions.COMMIT_SHA)")

if [ -z "$COMMIT_SHA" ]; then
    echo "No COMMIT_SHA in last succesful build found. Aborting"
    exit 1
fi

echo "Last succesful build found: $LAST_ID with commit $COMMIT_SHA"
echo "Writing to $TEMPORARY_COMMIT_SHA_FILE"
set -o noclobber
echo $COMMIT_SHA > $TEMPORARY_COMMIT_SHA_FILE
exit
```

It's not pretty but it seems to work ok

**Comment by justinpenguin45** [comment]
I agree that the documentation is not clear enough how to use this in CI/CD env for example Azure Devops. I want to be able to build anything affected since the last successful build (could be multiple commits). Its really not clear how to do this at all
