### ISSUE TITLE
Using ng g component myComponent -a=myModule --export erring out

### ISSUE THREAD

**Issue by CharlieGreenman** [nrwl/nx#342]
When using the above command, I am receiving the following error: 

```
Error: Could not find an NgModule for the new component. Use the skip-import option to skip importing components in NgModule. 
Could not find an NgModule for the new component. Use the skip-import option to skip importing components in NgModule.
```

As a side note, the following is then generated in my libs component
src
--|apps
--|--| libName

Using latest: 
```
"@nrwl/nx": "^0.9.1",
"@nrwl/schematics": "^0.9.1",
```

As well as ran `migrate-nx`

**Comment by CharlieGreenman** [comment]
Had to do with improper addition to .angular-cli.json. All good.

**Comment by sdurnov** [comment]
@CharlieGreenman which kind of improper addition? Having same issue, can't figure out what's wrong..
