### ISSUE TITLE
Cannot run Cypress tests from Webstorm

### ISSUE THREAD

**Issue by BorisZubchenko** [nrwl/nx#3424]
First of all, thank you for resolving [the similar Jest issue](https://github.com/nrwl/nx/issues/2314)! I really like the way I can run tests now. Unfortunately, it has some drawbacks...

## Current Behavior

When I run Cypress tests from Webstorm (with green triangle), the following error occured:
```
  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    apps/cypress-learning-e2e/src/integration/app.spec.ts:4:20 - error TS2304: Cannot find name 'cy'.

    4   beforeEach(() => cy.visit('/'));
                         ~~
    apps/cypress-learning-e2e/src/integration/app.spec.ts:8:5 - error TS2304: Cannot find name 'cy'.

    8     cy.login('my-email@something.com', 'myPassword');
          ~~
``` 
The thing is that Cypress tests perceived as Jest tests so Mocha context is confused with the Jest.

## Expected Behavior

The test should be executed properly.

## Steps to Reproduce

1. Generate a new workspace (Angular+Nest).
2. (Don't know if required) Run any Jest unit test.
3. Run the e2e test (or all of them) from app.spec.ts with IntelliJ IDEA/WebStorm UI (Click on green triangle(s) near the line numbers).

### Environment

```
  @nrwl/angular : 10.0.6
  @nrwl/cli : 10.0.6
  @nrwl/cypress : 10.0.6
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.0.6
  @nrwl/linter : 10.0.6
  @nrwl/nest : 10.0.6
  @nrwl/next : Not Found
  @nrwl/node : 10.0.6
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.6
  @nrwl/web : Not Found
  @nrwl/workspace : 10.0.6
  typescript : 3.9.7
```

**Comment by Cammisuli** [comment]
Hmm, that's interesting! I never even thought about running cypress through WebStorm before!

I'll take a look and see what's up.

**Comment by FrozenPandaz** [comment]
Going to label this as a feature as it wasn't intended to work and we are looking to add this behavior.

**Comment by Areen3** [comment]
Hi 
I spended some time to recognised these problems and here is some clue

I made repo with example how to configure VScode and Webstorm to debug cypress test

https://github.com/Areen3/debug-nx-cypress
there is two banches 
first to debug multi project angular enwirnment
second to debug VSC and Webstorm (using payed plugin)

I hope these examples can be usefull

But I faced one problem:
I cant configure shared library that was used in cypress test, to connect these files, in diferrent way than absolute path to file

![image](https://user-images.githubusercontent.com/34617740/108420172-bb86bc00-7233-11eb-93d8-26e648f40fea.png)
maybe someone know how to configure it properly and change it to relative path

in these examples you have additionaly: 
how to configure cypress to run spec wihtout nx environment
how to debug under VSCode
how co call another nx library from spec file
