### ISSUE TITLE
Ability to make an existing library buildable

### ISSUE THREAD

**Issue by john0tough** [nrwl/nx#3427]
I have a large angular project with many libraries, and four apps, so build the project take a lot of time because libraries are builded every time with each app build.

So I want to know if there is a way to add buildable option to my existing libraries

Many thanks, and sorry for my bad english, I'm not a native speaker... but we do what we can 😄

**Comment by yharaskrik** [comment]
Hey @john0tough I recently made this simple schematic for doing it internally that i published to npm

https://www.npmjs.com/package/@trellisorg/make-buildable

I haven't written tests or used it extensively but feel free to give it a go. Right now it supports node and angular libs but no others.

**Comment by brandonroberts** [comment]
@john0tough we have it on our list to work on official schematics to support this also.

**Comment by john0tough** [comment]
> Hey @john0tough I recently made this simple schematic for doing it internally that i published to npm
> 
> https://www.npmjs.com/package/@trellisorg/make-buildable
> 
> I haven't written tests or used it extensively but feel free to give it a go. Right now it supports node and angular libs but no others.

Thanks, I'll take a look

**Comment by mehrad-rafigh** [comment]
@brandonroberts any news on this? Can we pitch in and write this schematic or even better incorporate @yharaskrik schematic.

**Comment by fasidOnGit** [comment]
+1

**Comment by yharaskrik** [comment]
Recently updated to fix a couple of bugs, remove some hardcoded values and conditionally set some builders based on nx version.

https://www.npmjs.com/package/@trellisorg/make-buildable

**Comment by johannesnormannjensen** [comment]
+1

**Comment by timtos** [comment]
"buildable libraries cannot import non-buildable libraries" +1

**Comment by mehrad-rafigh** [comment]
Maybe we should create a new community plugin for this. I know @yharaskrik has a package, but it is not open source. Any chance you could host the sources on github @yharaskrik?

**Comment by cmbkla** [comment]
I'm here to keep things fresh.

**Comment by mhamri** [comment]
@brandonroberts also is it possible have an easy way to update the buildable library package.json. the central package.json and one version policy is very cool idea, but when we are talking about buildable library, then we end up with over 10 different package.json that need to udpated/version separately and it defeat the purpose of the mono repo somehow.  can I delete the package.json in those buildable library or should keep them?

**Comment by sagiBarkol** [comment]
updates?

**Comment by Yohandah** [comment]
needing this as well !

**Comment by AlexAegis** [comment]
A manual guide would be just as welcome in the meanwhile. I tried adding the build config to the angular.json file and related ng-packagr files but it still complains.

**Comment by B-R-Bender** [comment]
me to

**Comment by shawnmclean** [comment]
I ran into this because I created a publishable/buildable package after I made a normal react lib.

**Comment by kryptus36** [comment]
+1 for a manual guide in interim

**Comment by joeguo911** [comment]
+1

**Comment by wkaskie** [comment]
+1

**Comment by sir-captainmorgan21** [comment]
+1 almost two years later

**Comment by bilalshaikh42** [comment]
+1

**Comment by nekkon** [comment]
+1

**Comment by Isterius** [comment]
🙌

**Comment by B-R-Bender** [comment]
my current workarount is just to use `nx g move` to rename project using some prefix
then create a buildable one with the proper name and move all existing code to it
`nx g remove` prefixed one at the end

**Comment by MakarGlavanar** [comment]
For those who find it annoying to `nx g move` every library, here is another workaround:

1. Create an empty library with the required type [optional, you can use other already created libraries if they match your type]
2. Copy `package.json` from the created library to your existing library with the wrong buildable flags
3. Fix paths in `package.json`
4. Copy the `build` target line from the created library `project.json` and paste it to your existing library `project.json`
5. Repeat steps 2-4 for each library you need to mark `buildable`
6. Delete folder `nx` from `.cache` folder in `node_modules`
7. Restart your IDE

Hope it helps

**Comment by savvyshell** [comment]
+1

**Comment by expelledboy** [comment]
Painful experience..

For a given
- project `the-project`
- library `my-lib`

1. `nx g move my-lib my-lib-zap`
2. `rm -rf libs/my-lib/src`
3. `cp -R libs/my-lib-zap/src libs/my-lib`
5. `find ./{apps,libs} -type f -name "*.ts" -print0 | xargs -0 sed -i 's_@my-lib-zap_my-lib_'`
6. eye ball your diffs, revert, merge etc
7. `nx g remove my-lib-zap`
8. `git add .`
9. `git commit -m "make my-lib buildable"

Had to do this for 14 library today 😭 the whole day wasted

**Comment by cnpallares** [comment]
This worked for me with no problems when I accidentally generate a library as internal (non-buildable).

- Add build target into the lib's project.json
- Add package.json
- Add ng-package.json
- Add tsconfig.lib.prod.json

Hope can help :)

It should be nice to have this as an automatic generator.

Regards I'm really enjoying migrating a stand-alone angular app to NX.

**Comment by kenatwex** [comment]
> This worked for me with no problems when I accidentally generate a library as internal (non-buildable).
> 
> * Add build target into the lib's project.json
> * Add package.json
> * Add ng-package.json
> * Add tsconfig.lib.prod.json
> 
> Hope can help.
> 
> Anyways, should be nice to have this as an automatic generator.
> 
> Regards :)

this is how I do it but it would be nice to have a plugin to convert i inherited a big mound and need to remodel it

**Comment by mtiller** [comment]
Well, I'm relatively new to `nx` so perhaps what I did has some hidden pitfall, but I just took an existing repo that had a non-buildable library (and all files committed) and did a `nx g remove <library>`.  Then I recreated it as a buildable version from the same generator.  Then, I just went back and restored my files.  There were a few files from the generator that I had to manually remove.  But I did this for a couple of packages and it worked fine.  The good thing is that since all files are committed, if you do this on a branch and it doesn't work out, just throw away your changes.

**Comment by beaussan** [comment]
This is now possible with vite, you can run `@nrwl/vite:configuration` on a existing project and it will create a build target using vite

**Comment by Bezmehrabi** [comment]
Hey, Our project has a bunch of libraries, and we need this feature. Any updates on that front?
I'm willing to work on the issue if that's ok.

**Comment by jaysoo** [comment]
Like @beaussan mentioned, you can run the `nx g @nx/vite:configuration`  or `nx g @nrwl/vite:configuration` command to add a build target for existing projects. We can look into providing a more generic tool for JS libs, e.g. `nx g @nx/js:build`, that can support other bundlers like esbuild, rollup, rspack, etc.

**Comment by arturgawlik** [comment]
+1 Need this feature for project that has almost 200 libs to add "build" target :')

**Comment by zestsystem** [comment]
I'm make every library buildable just in case lol

**Comment by expelledboy** [comment]
@jaysoo Thank you :)
