### ISSUE TITLE
0.9.1 migration removes "lazyLoad"

### ISSUE THREAD

**Issue by ph55** [nrwl/nx#343]
When updating from 0.8.0 to 0.9.1 - "lazyLoad" block removed from "nx-enforce-module-boundaries".
I assume it's related to new feature - [support for tagged libs](https://github.com/nrwl/nx/pull/330)

![image](https://user-images.githubusercontent.com/1386622/37658968-7095139c-2c57-11e8-83fa-15b036669552.png)

**Comment by skydever** [comment]
I found out that there is an [autodetection](https://github.com/nrwl/nx/blob/de138bb26cb816b86afe6b8f14abb362cec2a20e/packages/schematics/src/tslint/nxEnforceModuleBoundariesRule.ts#L167) for that now. 

I got it like that: the rule checks lib dependencies, also if a lib is loaded via `loadChildren` into another lib/app. if so, imports from that lazy loaded lib into the lib/app that is lazy loading via `loadChildren` are not allowed. no need to keep track of it *manually* anymore, and it allows you to do both (lazy and not lazy) including the lazy only check if the lib is supposed to be lazy loaded, awesome!

e.g. `my-app` is using `loadChildren` to load `my-lib`. imports within `my-app` from `@myworkspace/my-lib` produce a lint error in that case: `imports of lazy-loaded libraries are forbidden`. `my-app-two` can import `@myworkspace/my-lib` (it does not use `loadChildren` for `my-lib`), even if `my-app` is using `loadChildren`.

**Comment by skydever** [comment]
...but this is still required at the corresponding `tsconfig.app.json` I suppose (e.g. in `my-app` when using `loadChildren`):

```json
"include": [
    "**/*.ts"
    /* add all lazy-loaded libraries here: "../../../libs/my-lib/index.ts" */,
    "../../../libs/my-lib/index.ts"
  ]
```

... maybe a nice additional feature, to show a lint error at the line of `loadChildren` if the typescript setup is missing that in it's include, to get the error *when you type it* ...

**Comment by ph55** [comment]
> I found out that there is an autodetection for that now

I don't think so.

This is **with** module added to "lazyLoad" (correct validation)

![image](https://user-images.githubusercontent.com/1386622/37703042-0687b79c-2cfd-11e8-9c3a-d0e6097d7c51.png)
![image](https://user-images.githubusercontent.com/1386622/37703035-fee58dd4-2cfc-11e8-93fd-d1ee2eaeef31.png)

<hr>
<br>
<br>

This is **without** module in "lazyLoad" (no validation)

![image](https://user-images.githubusercontent.com/1386622/37703097-3bba1df6-2cfd-11e8-8779-a08bedc3e364.png)
![image](https://user-images.githubusercontent.com/1386622/37703087-32867608-2cfd-11e8-9850-8748ea557ad5.png)

**Comment by skydever** [comment]
you are sure that you are on `0.9.1`, maybe a lint cache problem in your ide? see [56788ba](https://github.com/nrwl/nx/commit/56788ba3d1a8220455b03f0c766963ae8179ce81)

**Comment by ph55** [comment]
I see. Both `@nrwl/nx` and `@nrwl/schematics` are 0.9.1
Did reinstall `node_modues`
```
rm -rf node_modules package-lock.json
npm install
```
Now I see circular dependencies warnings (tslint) which tells it's updated.
But, lazy load stopped to work at all.

![image](https://user-images.githubusercontent.com/1386622/37764831-51957890-2dcb-11e8-88ab-fb52eec716bf.png)

![image](https://user-images.githubusercontent.com/1386622/37765033-e0e40778-2dcb-11e8-8c2e-cbea85873e80.png)

**Comment by ph55** [comment]
Closing in favor of https://github.com/nrwl/nx/issues/352
