### ISSUE TITLE
nx run-many ignoring skip-nx-cache option

### ISSUE THREAD

**Issue by smasala** [nrwl/nx#3432]
Nx version @ 8.12.11

## Current Behavior
```
>  NX  Running target test for projects:
  With flags:
    --skip-nx-cache=true
    --skipNxCache=true
```

`Unknown option: '--skip-nx-cache'
Unknown option: '--skipNxCache`

## Steps to Reproduce
`nx run-many --target=test --all --skip-nx-cache`

**Comment by vsavkin** [comment]
The option is not available in 8.12. We only support two major releases: so it's 9x and 10x now.

You can update @nrwl/workspace package to 9.5.1 without updating any other packages. This should not affect any plugins and you should be able to use the option.
