### ISSUE TITLE
aggregate coverage information

### ISSUE THREAD

**Issue by benmonro** [nrwl/nx#3437]
## Description

When using nx with many libs, we often a scenario where we have lib A with component A and lib B with component B.  component A uses component B and there's a test of A, but B shows zero coverage, even though i know it's covered in A.  this is because lib A and lib B each have their own jest runs and each collect covg from their own respective libs.  wondering if there's some way to solve this in nx-land.

## Motivation

to get more comprehensive, accurate coverage reports of the entire monorepo.

## Suggested Implementation

not sure?

**Comment by benmonro** [comment]
@FrozenPandaz or @vsavkin any thoughts or ideas on this?

**Comment by vsavkin** [comment]
We implemented this for a few clients. Basically, you often cannot collect coverage for the whole repo. You might have different applications in the same, hence different coverages. You can also have different modules built by different teams, so they should not affect each other's coverage.  At the same time, as you pointed out, the coverage reports can be too granular. So what we did for some of our clients is we wrote a script that allows you to specify groups of libs that form "systems" and then we aggregated coverage reports. Aggregating reports isn't hard. The only interesting bit is that you need to restore reports for the libs for a particular system.  We used Nx Cloud for that but you could use a custom solution.

**Comment by benmonro** [comment]
@vsavkin thank you.  any way you could elaborate on that or provide an example of how one might create a group of libs as a system? like does it use scope to accomplish this?  I'm concerned the aggregating of coverage reports will not be enough.  In order to capture that a component is covered, it has to be part of the 'collectCoverageFrom' in jest.  so to expand my example, when I run the tests in A, i need it to collect coverage from A AND B, otherwise, even if you aggregate the reports, B will still show as uncovered.

**Comment by Lonli-Lokli** [comment]
We are interested in it too, with monorepo it's also useful to have 'common'  code coverage as an indicator.
Will it be possible to use in community edition?

**Comment by tonivj5** [comment]
Up

**Comment by tonivj5** [comment]
> Up

**Comment by barbados-clemens** [comment]
I can look into this, but unsure when I'll have a chance, feel free for someone else to give it a try!

**Comment by TicTak21** [comment]
I found possible solution [here](https://dev.to/rupeshtiwari/merge-and-publish-code-coverage-for-nx-workspace-in-azure-ci-pipeline-1pk5). Need to test it, but I would like to see something like that out of the box.

**Comment by shutupandshave** [comment]
Up

**Comment by groothuyse** [comment]
We have 'solved' this by creating a dummy "all" application that bundles everything so we can get an aggregate coverage report.

angular.json
```   
"all": {
      "root": "./",
      "sourceRoot": "./",
      "projectType": "application",
      "architect": {
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "apps/all/src/test.ts",
            "polyfills": "apps/all/src/polyfills.ts",
            "tsConfig": "apps/all/tsconfig.spec.json",
            "karmaConfig": "apps/all/karma.conf.js",
            "scripts": [ ],
            "styles": [ ]
          }
        }
      }
    },
```
then in tsconfig.spec.json
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "src/test.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "../../**/*.spec.ts",
    "**/*.d.ts"
  ]
}

```

and in the test.ts
```
// Then we find all the tests from all apps and libs
const context = require.context('../../../', true, /^\.\/(apps|libs)\/.+\.spec\.ts$/);
```

**Comment by NgrNxk** [comment]
Oh, I have given this too much thought and SO searches... Anyways, in the end, for my use case, it was a very simple hack. In the `jest.config.ts` of our primary (frontend) app, I added the following to the `default` properties:

```ts
  projects: getJestProjects().map(
    (val: unknown) => (val as string).replace('<rootDir>', '<rootDir>/../../')
  ),
```
as well as the corresponding import at the top:
```ts
import { getJestProjects } from '@nrwl/jest';
```

Now, whenever I run `nx run frontend:test`, it runs all of the tests from (I think) `workspace.json`'s projects. Which is great, because we only have the app.component inside the app -- everything else is in the *libs* folder. Adding `--codeCoverage` to this run works just fine.

And yes, you could argue that this doesn't work well if you have multiple apps inside -- and your probably right. On the one hand, you can just filter based on some folder (what about tags?). On the other hand: our second app in there is a java project, and this one doesn't use "my" *libs* folder.

**Comment by dan-cooke** [comment]
@NgrNxk this has put me on the right track, 

With your method I can run all the relevant tests ... and they are indeed added to the coverage report - so thanks for that :)

But its still missing something the crucial point I think. 

The coverage report is not detecting that `lib/a` function is tested by `app/api/tests/**` and it is not included in the coverage report.

Any ideas?

**Comment by vojvodics** [comment]
This is possible to do by using vitest and c8 coverage reporter. I created a mini repo with an example: https://github.com/vojvodics/nx-coverage-example

The basic setup is adding this to your vitest config: 
```
coverage: {
  provider: 'c8',
  allowExternal: true,
  all: true,
},
```

This will generate duplicates however, so you'll probably need something to merge all reports. E.g:
```
istanbul-merge --out coverage/coverage-final.json 'coverage/**/coverage-final.json'
```
