### ISSUE TITLE
Running test on grouping folder runs, all children, which leads to multiple runs of them

### ISSUE THREAD

**Issue by KeKs0r** [nrwl/nx#3438]
### Prequestion 
Is it an anti pattern to have "grouping folders" in libs as libraries themselves?
(if so this might mage the rest obsolete)

# Actual Report
Example Scenario (from the docs)
```
apps/
  booking/
  check-in/
libs/
  booking/                 <---- grouping folder
    feature-shell/         <---- library

  check-in/
    feature-shell/

  shared/                  <---- grouping folder
    data-access/           <---- library

    seatmap/               <---- grouping folder
      data-access/         <---- library
      feature-seatmap/     <---- library
```

## Current Behavior
When running `nx test shared` it also runs all tests for its children. Ending up in running all of these:
-  shared
- shared-data-access
- shared-seatmap
- shared-seatmap-data-access
- shared-seatmap-feature-seatmap

This seems kinda logical when running just `nx test shared`.  The problem is when the `feature-seatmap` has a specific jest config (either babel jest or a setup file), which is required for their test. Then it will fail those test cases. Where as when directly running them `nx test shared-seatmap-feature-seatmap` they would pass.
Also in a case when running all tests for affected. When the whole tree is affected:
1.   shared
2.   shared-seatmap
3.  shared-seatmap-feature-seatmap
The tests of 3. would run 3 times. The tests of 2. would run 2 times etc.

## Expected Behavior
I think running tests for a grouping folder should only run the tests in the `src` of that grouping. Alternatively this behaviour should be possible to control via CLI option.

## Steps to Reproduce
I am currently on a mobile, but quite sure it can be reproduced in the example repo by running `nx test shared`

--> No actually not, since the shared folder is not a lib itself. In my case the grouping folders are libs themselves and have some components. 

### Environment
```
  @nrwl/angular : Not Found
  @nrwl/cli : 9.5.1
  @nrwl/cypress : 9.5.1
  @nrwl/eslint-plugin-nx : 9.5.1
  @nrwl/express : 9.2.2
  @nrwl/jest : 9.5.1
  @nrwl/linter : 9.5.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.5.1
  @nrwl/react : 9.5.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.5.1
  @nrwl/web : 9.5.1
  @nrwl/workspace : 9.5.1
  typescript : 3.8.3
```

**Comment by FrozenPandaz** [comment]
Nesting libs within one another is not recommended as configuration files usually define globs for files within them which would not know when to stop traversing downwards. I would recommend moving the `src` under `shared` to a new library and then make `shared` a grouping folder. An alternative solution would be to change the `testRegex` for that library but there are other issues with libs within libs.

Does this solve your issue?

**Comment by KeKs0r** [comment]
Yes I think there are good ways around it. It just wasn't super clear to me that the "grouping" are not libs themselves... Refactored most of my codebase to this and it works fine now.
