### ISSUE TITLE
[Feature Request] Option --ignoreTestFiles cli argument not exposed by the cypress builder

### ISSUE THREAD

**Issue by jacobworrel** [nrwl/nx#3439]
## Description
I would like to be able to ignore test files via the cypress ignoreTestFiles cli argument. Currently, when trying to run `nx e2e my-app-e2e --ignoreTestFiles=path/to/file`, I get the following error:
```
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(ignoreTestFiles).
```

## Motivation
I want to ignore tests that run visual regression tests on applitools while running e2e tests in watch mode. My current workaround is to duplicate the `cypress.json` file with a `ignoreTestFiles` prop and pass that in via the `cypress-config` cli flag.

## Suggested Implementation
The implementation for https://github.com/nrwl/nx/issues/1192 should work for this flag as well.

**Comment by FrozenPandaz** [comment]
That sounds like an important flag for the builder to accept.

As mentioned, this is a relatively simple feature and someone from the community can send a PR! :pray:

**Comment by mehrad-rafigh** [comment]
@FrozenPandaz @jacobworrel I will take a try at this and open a PR
