### ISSUE TITLE
Proxy between different micro apps in same browser window

### ISSUE THREAD

**Issue by msreekm** [nrwl/nx#3440]
## Proxy between different micro apps in same browser window
Let us say we have 3 micro apps (react) and 1st app has a link to the 2nd app and 2nd app is running in differnt port during developmet ,is it possible to test the flow end-to-end app1->app2->app3->app1 seamlessly without switching browsers? This is in a way similar to proxying for api calls running on a. different port

**Comment by henriqueweiand** [comment]
I have practically the same context. I have two apps that must run on the same port, but they are different react apps. Each is in a specific path.

I'm trying some approaches with run-many or nx own proxy, but still without success

**Comment by nhhockeyplayer** [comment]
I wondering why we dont have option of naming the proxy entry point

seems it is always /api
```

{
  "/api": {
    "target": "http://localhost:3333",
    "secure": false
  }
}
```
when we add micro apps dont they receive their own proxy?

the schematic does not alter nor edit the proxy.conf.json

seems the proxy.conf.json is hardwired to just 'api' when it should be managing them?

any clarification would be helpful

**Comment by msreekm** [comment]
@henriqueweiand , I finally figured out a way to switch between 2 apps running on same port. Created a github repo with sample apps - https://github.com/msreekm/nx-nextjs-routing
