### ISSUE TITLE
tsconfig path doesn't update from nx 0.2.2 to latest

### ISSUE THREAD

**Issue by Yonet** [nrwl/nx#345]
Applications created with nx v 0.2.2 has tsconfig path on the root level .angular-cli.json as
```
"tsconfig": "../../../tsconfig.app.json",
```
Updating to the newest version, creates new applications with tsconfig.app.json files, paths defined as:
```
"tsconfig": "tsconfig.app.json",
```
but keeps the applications created with the older versions as is. This is causing a problem when using affected:build. 

You can find the repro here:
When the problem apps/libs created: 
https://github.com/nrwl/nx-examples/blob/7743fac179e56fbc5dab5691855a26178011904b/.angular-cli.json

Latest updated version with affects:build issue: https://github.com/nrwl/nx-examples/tree/01814e5108de44510b78f23461e29878f51f2525

**Comment by FrozenPandaz** [comment]
The result looks correct after upgrading using @nrwl/schematics@0.9.1

https://github.com/FrozenPandaz/nx-examples/tree/migrate-from-0-2-2

**Comment by Yonet** [comment]
@FrozenPandaz it is not correct after you ran. The issue is here:https://github.com/FrozenPandaz/nx-examples/blob/295aefea2d10e6e8529e5cf16163bf52d217754e/.angular-cli.json#L22

**Comment by FrozenPandaz** [comment]
So here's the story:

https://github.com/nrwl/nx-examples/commits/158993378f9b4eb875f767ad82fd0be7ec903211

The 2nd to last commit here: https://github.com/nrwl/nx-examples/commit/46521446ab7a32fdacb460d51565b6f9bfe8dba0

Did the proper migration and noted it in the angular-cli.json

The commit after that (The last commit) Merged in 2 new apps with the old way of doing tsconfigs:https://github.com/nrwl/nx-examples/commit/158993378f9b4eb875f767ad82fd0be7ec903211

This made it appear as though the migration didn't happen for some apps.

Thus, I don't think this is an issue with migrations
