### ISSUE TITLE
Generating react app w/ react router produces invalid code

### ISSUE THREAD

**Issue by joshribakoff** [nrwl/nx#3456]
<img width="706" alt="Screen Shot 2020-08-01 at 3 25 34 PM" src="https://user-images.githubusercontent.com/4021306/89111494-42488880-d40b-11ea-93f8-ab7e83a0041e.png">

Nx 9.5.1

I just checked out https://github.com/rx-store/rx-store and ran the pictured command.

**Comment by bekos** [comment]
@joshribakoff Can you please try with the latest Nx? If it's not solved, please try to provide a repo to test, because I was unable to reproduce the issue locally.

**Comment by joshribakoff** [comment]
Tried it 1x on Nx 10 and it didn't replicate any issue. It was either specific to Nx 9, or it is a race condition, feel free to close either way. It's not blocking me in any way & was just FYI.

**Comment by bekos** [comment]
@joshribakoff great 👍 thx for the feedback, it's always welcome 😃
