### ISSUE TITLE
Is it safe to programmatically remove the base tag?

### ISSUE THREAD

**Issue by shaharkazaz** [nrwl/nx#3458]
## Description

Seems like the `baseHref` is a mandatory property in the build options (no way to remove it).
What's the reason for it? what are the side effects? and is it safe to programmatically remove the base tag?

Thanks!

**Comment by vsavkin** [comment]
I don't believe it's not a mandatory property. If you remove it, it will be defaulted to "/". And you can programmatically remove it as well. Some libraries may depend on it (e.g., the router), but generally you don't have to have it.

**Comment by shaharkazaz** [comment]
@vsavkin thanks for the answer.
By mandatory I mean that I can't pass a value that prevents this tag from being added (the default is `/`), is there any value I can pass to prevent this tag from being added?
