### ISSUE TITLE
Dist folder is not deleted between builds

### ISSUE THREAD

**Issue by shaharkazaz** [nrwl/nx#3466]
## Current Behavior
dist folder is not deleted between builds.

## Expected Behavior
Delete the dist folder between builds.

## Steps to Reproduce
- Create a new nx workspace
- Run the build
- Add a custom file "willPersist"
- Re-run the build, the file is still there.

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment
    "@nrwl/cypress": "10.0.6",
    "@nrwl/eslint-plugin-nx": "10.0.6",
    "@nrwl/jest": "10.0.6",
    "@nrwl/react": "10.0.6",
    "@nrwl/web": "10.0.6",
    "@nrwl/workspace": "10.0.6",

**Comment by jaysoo** [comment]
Hi @shaharkazaz, 

Do you mean to delete the `outputPath` for a single project when building? For example, if I run `nx build my-app` then I'd expect something equivalent to `rm -rf dist/apps/my-app` to execute first.

**Comment by shaharkazaz** [comment]
@jaysoo That's the default behavior when using the angular-cli and that makes sense to me.
