### ISSUE TITLE
@nrwl/schematics@0.9.1 update breaks tslint live inspection in WebStorm

### ISSUE THREAD

**Issue by spiotr12** [nrwl/nx#347]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
After update `@nrwl/schematics` package from 0.8.0 to 0.9.1 I experiencing and issue in WebStrom. when in WebStorm I enable tslint plugin so it shows tslint errors while developing it crushes the IDE (please see this link where I explained what happened [see it here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000329604/comments/360000107584) logs are included there).

I track down different options and in result it turned out that it is this `@nrwl/schematics` rules directory that breaks WebStorm. I did not see this problem in 0.8.0 (I've tried to replicate it back on v 0.8.0). I did also reinstall WebStorm and I've used clean installation. TSLing plugin is included by default in this IDE.

## Expected behavior:
That I can use TSLint plugin in WebStorm. It is definietly a problem on this package on certain version. I can provide logs

## Minimal reproduction of the problem with instructions:
REQUIREMENTS:
IDE: WebStorm; TSLing plugin enabled; In settings, enable Use "safe write" option under Appearance & Behavior -> System Settings
@nrwl/schematics@0.9.1

Generate new ngrx workspace and generate new app
just change any file e.g. app.component.ts file and save it multiple times very quickly until you see following error:
![image](https://user-images.githubusercontent.com/10038964/37687160-c00c5a82-2c9a-11e8-8a83-31875b3a0ed2.png)

Please notice that there will be two files generated by IDE:
![image](https://user-images.githubusercontent.com/10038964/37687196-e26d8dbc-2c9a-11e8-911a-2a9975e28873.png)

In my opinion there is something in schematics that crush tslint and therefore the IDE

## Version of affected browser(s),operating system(s), npm, node and ngrx:
@nrwl/schematics@0.9.1
WebStorm 2017.3.5
tslint plugin 173.4674.32

## Other information:
I suspect that tslint is locking the file while WebStorm is trying to save it. 
Thanks for help

**Comment by spiotr12** [comment]
Same issue happens on @nrwl/schematics@0.9.0 version

**Comment by jeffbcross** [comment]
@spiotr12 could you experiment with commenting out different Nx rules to see which one(s) might be the culprit?

**Comment by spiotr12** [comment]
Sure, I can

**Comment by skydever** [comment]
... seems related to #403 and I guess fixed with #404

**Comment by BertDuyck** [comment]
Having the same issues, but it only happens on windows from my experience.

**Comment by bcabanes** [comment]
Hi!

Closing old issue.
