### ISSUE TITLE
Cypress tests not awaiting page redirects

### ISSUE THREAD

**Issue by ajkratz** [nrwl/nx#3471]
Our application uses an oauth authentication workflow. For nearly all tests a login is required. We have implemented this successfully using cy.request. The oauth workflow includes several page redirects, 302, and 303.
In a native cypress project the test waits for the redirects and the login completes successfully.

When we try to execute the same test inside an nx-angular-mono-repo with nrwl/cypress and with ng e2e test-project, the test fails. In the open runner you can see, that the page redirects are ignored. Instead the post request returns StatusCode 200 at once.

## Current Behavior
cypress test fails, because page redirects are not awaited

## Expected Behavior
cypress test waits for page redirects and completes successfully

## Steps to Reproduce
create new nx-workspace for angular app.
Run test that uses cy-request, which includes page redirects

### Environment
nx mono repo with angular 9
@nrwl/cypress 9.5.1
cypress 4.10.0

**Comment by baxtor** [comment]
Hi everyone,
any updates on this issue ? We've the same issue here when using nrwl-cypress tests in angular 9 application with authentication enabled.

Regards baxtor
