### ISSUE TITLE
Cannot find name 'describe'” when running “ng serve express”

### ISSUE THREAD

**Issue by adams-family** [nrwl/nx#3488]
## Current Behavior
I get the following error when running `ng serve express`  (here express is a @nrwl/express project)

```
TS2593: Cannot find name 'describe'. Do you need to install type definitions for a test runner? 
Try `npm i @types/jest` or `npm i @types/mocha` and then add `jest` or `mocha` to the types
field in your tsconfig.
```

## Expected Behavior
`ng serve express` should work.

## Steps to Reproduce
1. Create a new workspace: `npx create-nx-workspace`
2. Install @nrwl/express: `npm install --save @nrwl/express`
3. Create an express project: `npm run nx generate @nrwl/express:app express`
4. Add `export` before `const server = ` in `main.ts`:

```
import * as express from 'express';

const app = express();

app.get('/api', (req, res) => {
  res.send({ message: 'Welcome to express!' });
});

const port = process.env.port || 3333;
export const server = app.listen(port, () => {
  console.log(`Listening at http://localhost:${port}/api`);
});
server.on('error', console.error);
```

5. Add supertest: `npm i supertest —save`
6. Create a simple `example.test.ts` file:

```
const { server } = require('./server');

describe('TEST: /', () => {
  it('Should work just fine', async () => {
    // all ok
  });
});

export {};
```

7. Run: `ng serve express`

Result: the error above

## Git repo to reproduce

https://github.com/adams-family/nrwl-jest-error-repro

### Environment

`nx report`:

```
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.0.10
  @nrwl/cypress : Not Found
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : 10.0.10
  @nrwl/jest : 10.0.10
  @nrwl/linter : 10.0.10
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.0.10
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.10
  @nrwl/web : Not Found
  @nrwl/workspace : 10.0.10
  typescript : 3.9.7
```

**Comment by vsavkin** [comment]
Hi there!

You need to exclude *.test files as well, or rename the file to *.spec.ts in https://github.com/adams-family/nrwl-jest-error-repro/blob/master/apps/express/tsconfig.app.json

Closing this issue

**Comment by adams-family** [comment]
Hi @vsavkin, agreed, it helps!

One question tough: given a large number of projects that use `*.test.ts` pattern for Jest testing, shouldn't we exclude *.test.ts in `tsconfig.app.json` by default?
