### ISSUE TITLE
[Noob question] How to manually create (a pure webpack) app (w/ Cloudflare Workers)

### ISSUE THREAD

**Issue by JakubKoralewski** [nrwl/nx#3489]
## Description

I've been in the middle of migrating my submodule setup to a Lerna monorepo when I found out about Nx, and decided that Nx is the way to go. I have a next application which easily following [the docs](https://nx.dev/angular/plugins/next/schematics/application) I generated, but I also have multiple  Cloudflare Workers based backends that I want to use and from what I see I need to run the `generate` command or else I lose all the functionality that `nx` provides regarding dependency graphs etc.

My question is: **how can I generate a pure webpack app in Nx?** 

Is modifying the `nx.json` file enough to override the CLI and manually create apps or is the CLI necessary? I'm considering also creating a react app and then removing everything inside the app folder, will that work? I will have to then fix `workspace.json`, but what are the `builder`s...

EDIT: Also I'd like to clarify, these are not *purely webpack* apps, as they are not run with the `webpack` command, but through the Cloudflare Worker CLI `wrangler` tool, which I believe does not modify the output file at all apart from only running `webpack` on it (I may be wrong). Does the use of `wrangler` instead of `webpack` necessitate the use of a custom plugin?

**Comment by JakubKoralewski** [comment]
I've created a simple plugin that pulls from github templates and installs the dependencies from package.json then removes it.: https://github.com/supercuts/nx-cf-workers

But I don't know how to proceed with the build commands, I'm guessing I'm gonna have to use `child_process` and run `wrangler build`, but is that it? I'd appreciate some help.

**Comment by Akhil16** [comment]
Did You manage to manage cloudflare workers in Nx monorepo??
