### ISSUE TITLE
Apps with the same root folder are not properly displayed in the dep-graph

### ISSUE THREAD

**Issue by ferdiemmen** [nrwl/nx#3490]
## Current Behavior

When having 2 applications using the same root folder and source files, the dep-graph will not display the first application's graph. It only shows the graphs for the second application.

<img width="178" alt="Screenshot 2020-08-08 at 11 02 25" src="https://user-images.githubusercontent.com/560816/89706518-be405480-d966-11ea-9b10-c5842324a4cb.png"> 

## Expected Behavior

I expect the graph to show both the first and second application graphs and that the second application has a direct dependency on the first application.

<img width="281" alt="Screenshot 2020-08-08 at 11 02 51" src="https://user-images.githubusercontent.com/560816/89706548-019ac300-d967-11ea-95db-21694b97be1f.png">

## Steps to Reproduce

Create 2 applications using the same root folder. (Additionally add 2 libraries and lazy load them in the first application. To get a better graph.)

## Reproduction

https://github.com/ferdiemmen/repro-nrwl-3490

- Clone repo
- Install dependencies: $ yarn
- Run dep-graph: $ nx dep-graph
- Select products and products2
- Select products-home-page and products-product-detail-page
- Notice that only for products the graph is connecting to products-home-page and products-product-detail-page

Now open node_modules/@nrwl/workspace/src/core/file-graph/file-map.js

- comment out lines #24, #25 and #26 and save
- Run dep-graph: $ nx dep-graph
- Select products and products2
- Select products-home-page and products-product-detail-page

Notice that now for both products and products2 the graphs is connecting to products-home-page and products-product-detail-page

## Possible solution
https://github.com/nrwl/nx/blob/5b6df632cb767e3da5cf8b804b827147d729e129/packages/workspace/src/core/file-graph/file-map.ts#L25%3E#27
```
    ...
    files.forEach((f) => {
            /**
            * Commenting out the statement on the next 3 lines resolves the issue, but this might be here for a  specific reason.
            */
            // if (seen.has(f.file)) {    
            //    return;
            // }

            if (f.file.startsWith(p.root)) {
                fileMap[projectName].push(f);
                seen.add(f.file);
            }
        });
    ...
```

### Environment

  @nrwl/angular : 10.0.6
  @nrwl/cli : 10.0.6
  @nrwl/cypress : 10.0.6
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.0.6
  @nrwl/linter : 10.0.6
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 10.0.6
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.6
  @nrwl/web : 10.0.6
  @nrwl/workspace : 10.0.6
  typescript : 3.9.7

**Comment by philipjfulcher** [comment]
I'm not quite following the reproduction steps, are you able to put together an example repo for the situation you're describing?

**Comment by ferdiemmen** [comment]
Hi Philip,

I added the reproduction repo already see: https://github.com/ferdiemmen/repro-nrwl-3490
- Clone repo
- Install dependencies: $ yarn
- Run dep-graph: $ nx dep-graph
- Select products and products2
- Select products-home-page and products-product-detail-page

Notice that only for products the graph is connecting to products-home-page and products-product-detail-page

Now open `node_modules/@nrwl/workspace/src/core/file-graph/file-map.js`
- comment out lines #24, #25 and #26 and save
- Run dep-graph: $ nx dep-graph
- Select products and products2
- Select products-home-page and products-product-detail-page

Notice that now for both products and products2 the graphs is connecting to products-home-page and products-product-detail-page

If you need more information let me know.

**Comment by philipjfulcher** [comment]
Thank you for the clarification, I completely missed the link to the repo. I'll take a look.

**Comment by FrozenPandaz** [comment]
Thanks for the reproduction!

What is the motivation for this expected behavior? Why is it necessary to describe the same set of files with different projects?

**Comment by ferdiemmen** [comment]
Hi @FrozenPandaz,
The motivation is that we create apps with different routes, libraries and themes (scss). To keep to the DRY principle we use the same base application.

**Comment by FrozenPandaz** [comment]
I'm not sure how you are switching out the themes and routes. Can you keep the base application in a lib and then create multiple applications that use that lib?

**Comment by ferdiemmen** [comment]
@FrozenPandaz I switch out the themes and routes using file replacement. Creating a lib could indeed be a solution although having app specific files like main.ts and index.html feels a bit off putting them in a library. This also prevents us from using the application specific schematics since the files won't be there. For example generating Server Side Rendering which updates the main.ts file.

**Comment by ferdiemmen** [comment]
My issue has been resolved by using file replacements and creating a library for shared functionality. Although the dep-graph still has this limitation, it is not a limitation for the way we currently use dep-graph. Thanks @FrozenPandaz and @philipjfulcher for taking the time to look into this issue.
