### ISSUE TITLE
Unknown option: '--buildLibsFromSource'

### ISSUE THREAD

**Issue by maxime1992** [nrwl/nx#3493]
## Current Behavior

I have been trying to get every lib on our monorepo to be buildable. I'm nearly there and while I intend to use the `--with-deps` flag soon, I wanted to get that first bit merged asap where everything should be ready for next step.

But I get weird errors saying "Module not found: Error: Can't resolve" just like in https://github.com/nrwl/nx/issues/3131

So I found out that I should be using the `--buildLibsFromSource` flag instead of the `--with-deps` for now.

And it works for the NestJs app :+1: BUT as we do generate our `yarn nx run-many` command with something like the following: 
`yarn nx run-many --target=build --prod --projects=${config.affected.apps.join()} --parallel --maxParallel=5 --buildLibsFromSource` I thought it'd be fine to apply that arg on all the projects to build.

BUT, for all the other apps/libs I get 

> Unknown option: '--buildLibsFromSource'

## Expected Behavior

Being able to build anything with the `--buildLibsFromSource` tag

### Environment

```
  @nrwl/angular : 10.0.7
  @nrwl/cli : 10.0.7
  @nrwl/cypress : 10.0.7
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.0.7
  @nrwl/linter : 10.0.7
  @nrwl/nest : 10.0.7
  @nrwl/next : Not Found
  @nrwl/node : 10.0.7
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.7
  @nrwl/web : 10.0.7
  @nrwl/workspace : 10.0.7
  typescript : 3.9.7
```

**Comment by vsavkin** [comment]
We use the builders provided by the Angular team to build Angular applications. Their builder doesn't support `buildLibsFromSource` and there is not much we can do about it. We are considering wrapping their builder though.

For now though, you have several options:
1. You can wrap the default angular builder, add `buildLibsFromSource`, and just ignore the option.
2. You can also replace run-many with something like this:

```
pheudo code

if affected.includes(myAngularApp) 
   ng build myAngularApp

if affected.includes(myNestApp)
  ng build myNestApp --buildLibsFromSource
```

Closing this as it's not actionable right now.
