### ISSUE TITLE
Migration From CRA documentation error with config-overrides.js step

### ISSUE THREAD

**Issue by joshkarges** [nrwl/nx#3495]
## Current Behavior
Following the [Migration From CRA documentation](https://nx.dev/react/migration/migration-cra) still results in an error with the ModuleScopePlugin:
`Module not found: You attempted to import /home/myrepo/myorg/libs/mylib/src/index.ts which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.`

## Expected Behavior

The shared lib is found outside of the src/ directory because the ModuleScopePlugin was adequately filtered out of the `config.resolve.plugins`.

## Steps to Reproduce

1. Migrate a create-react-app to an nx app using the documentation here https://nx.dev/react/migration/migration-cra
2. After using the library in your migrated app, try an `nx build myapp`.

The issue is that the `!(plugin instanceof ModuleScopePlugin)` condition is false when it shouldn't be.  Possibly because react-scripts is using a different version of ModuleScopePlugin.  A more reliable condition would be `!(plugin.constructor.name === 'ModuleScopePlugin')`.

This is just a heads up to change the documentation since I went though a bit of a struggle to find out what was wrong.

### Environment

```
$ node --version
v14.7.0

$ tsc --version
Version 3.5.3

$ nx --version
10.0.10

$ yarn --version
1.22.4

$ create-react-app --version
3.2.0

$ yarn list react-app-rewired
└─ react-app-rewired@2.1.6

$ yarn list react-scripts
└─ react-scripts@3.4.1
```

**Comment by karolisg** [comment]
Thank you very much! I was trying to solve this problem for 4 hours.

**Comment by hicaro** [comment]
I am surprised that neither [cra-to-nx](https://www.npmjs.com/package/cra-to-nx) utility nor the migration documentation have been updated yet. This is still an issue. It took me a while to start doubting the setup since so many people go through it.

@joshkarges, thanks for reporting this!

**Comment by jakub-astrahit** [comment]
It still IS a bug in the documentation! Where can I fix this please?
