### ISSUE TITLE
Lack of "strict: true" causes hidden type errors to go unchecked

### ISSUE THREAD

**Issue by webberwang** [nrwl/nx#3502]
## Current Behavior

During Circle CI builds, `@nrwl/nest` build is triggering error

```
> nx run core:build 
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://err.sh/next.js/no-cache
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

The "path" argument must be of type string. Received null
Error during build
```

## Expected Behavior

`The "path" argument must be of type string. Received null` should not appear

## Steps to Reproduce

Unfortunately I can't reproduce locally, but this might be where the error occurs.

https://github.com/nrwl/nx/blob/7363ef0720a73c24a7a69010b0b0e59d145c7a69/packages/next/src/builders/server/server.impl.ts#L54-L63

`path` is undefined here, but without script mode, we don't catch that 

https://github.com/nrwl/nx/blob/7363ef0720a73c24a7a69010b0b0e59d145c7a69/packages/next/src/utils/types.ts#L39-L48

could actually be undefined

With `strict` mode enabled, we see the ESLint error.

<img width="486" alt="builder_ts_—_codelab__Workspace_" src="https://user-images.githubusercontent.com/26264925/89977299-a8a98400-dc1f-11ea-9f89-b03ff6cc4050.png">

The issue goes much deeper, the project has lots of ESLint error, turning on strict mode becomes a sea of red. But the longer we go without strict mode, the more hidden errors like these will pile up.

### Environment

```
 nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.0.11
  @nrwl/cypress : 10.0.11
  @nrwl/eslint-plugin-nx : 10.0.11
  @nrwl/express : Not Found
  @nrwl/jest : 10.0.11
  @nrwl/linter : 10.0.11
  @nrwl/nest : 10.0.11
  @nrwl/next : 10.0.11
  @nrwl/node : 10.0.11
  @nrwl/react : 10.0.11
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.11
  @nrwl/web : 10.0.11
  @nrwl/workspace : 10.0.11
  typescript : 3.9.7
```

**Comment by stramel** [comment]
@webberwang did you ever resolve this?
