### ISSUE TITLE
Jest Schematic still adds `setupFile` & `tsConfig`

### ISSUE THREAD

**Issue by twittwer** [nrwl/nx#3505]
## Current Behavior

When generating a project with jest it creates the correct `jest.config.js` with `setupFilesAfterEnv` & `tsConfig` but it adds `setupFile` & `tsConfig` to the test architect as well.

https://github.com/nrwl/nx/blob/3b8a10f073/packages/jest/src/schematics/jest-project/lib/update-workspace.ts#L18

## Expected Behavior

Because `setupFile` & `tsConfig` options were removed from all test architects during the migration to Nx10 it seems unintended, that these options are still generated.

## Steps to Reproduce

* Generate Nx Workspace with an Angular app
  `npx create-nx-workspace@latest test-jest --preset="angular" --appName="test-jest"`

* Look at the `projects.test-jest.architect.test.options` in the `angular.json`

```json
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "apps/test-jest/jest.config.js",
            "tsConfig": "apps/test-jest/tsconfig.spec.json", // <-- was removed during Nx10 migration
            "passWithNoTests": true,
            "setupFile": "apps/test-jest/src/test-setup.ts" // <-- was removed during Nx10 migration
          }
        }
```

* The `jest.config.js` contains this information as expected

```js
module.exports = {
  name: 'test-jest',
  preset: '../../jest.config.js',
  setupFilesAfterEnv: ['<rootDir>/src/test-setup.ts'], // <-- `projects.test-jest.architect.test.options.setupFile`
  globals: {
    'ts-jest': {
      tsConfig: '<rootDir>/tsconfig.spec.json', // <-- `projects.test-jest.architect.test.options.tsConfig`
      stringifyContentPathRegex: '\\.(html|svg)$',
      astTransformers: [
        'jest-preset-angular/build/InlineFilesTransformer',
        'jest-preset-angular/build/StripStylesTransformer',
      ],
    },
  },
  coverageDirectory: '../../coverage/apps/test-jest',
  snapshotSerializers: [
    'jest-preset-angular/build/AngularNoNgAttributesSnapshotSerializer.js',
    'jest-preset-angular/build/AngularSnapshotSerializer.js',
    'jest-preset-angular/build/HTMLCommentSerializer.js',
  ],
};
```

### Environment
```
  nx : Not Found
  @nrwl/angular : 10.0.11
  @nrwl/cli : 10.0.11
  @nrwl/cypress : 10.0.11
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.0.11
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.11
  @nrwl/web : Not Found
  @nrwl/workspace : 10.0.11
  typescript : 3.9.7
```

**Comment by Cammisuli** [comment]
Ah, you're absolutely correct! 😅 

I guess it was missed. 

For anyone interested, this line (and a the setup file part) needs to be removed from the jest schematic:
https://github.com/nrwl/nx/blob/e06822da7e2987d480f0b3a579fa41aed01c45c8/packages/jest/src/schematics/jest-project/lib/update-workspace.ts#L13

**Comment by twittwer** [comment]
I could do it but won't get to it until Monday

**Comment by ZachJW34** [comment]
@twittwer I can get to this one if you haven't started working on it. @Cammisuli should another migration be added to remove these options from projects that have been generated since the [last migration](https://github.com/nrwl/nx/commit/12a407f8cbb16b6057cd19bfb26bc5a8fb8c60c8)?

**Comment by twittwer** [comment]
@ZachJW34 I would have started this afternoon, but you can take it - thx 👍

**Comment by Cammisuli** [comment]
Yes, I think a migration should be added again. It'll most likely be the same set up as the original migration (without the jest config modifications 😄 )
