### ISSUE TITLE
vanillia nx angular project does not run tests in VSCode

### ISSUE THREAD

**Issue by d4046949** [nrwl/nx#3507]
## Current Behavior
I've created a standard nx project and then installed Jest extensions for visual studio code. I've then clicked Debug on one of the tests that were created as part of the project. These fail to run.

entering 'nx test' at the command line shows that the test pass. 

## Expected Behavior
I want to be able to debug a test

## Steps to Reproduce
create a new project using the NX CLI
install the Jest extension for VSCode
Attempt to debug the test.
Note that the component creation fails

## Additional information
I've tried following various posts found on the web. Even changed the launch.json to look like this

        {
            "name": "vscode-jest-tests",
            "type": "node",
            "request": "launch",
            "program": "${workspaceFolder}/node_modules/@angular/cli/bin/ng",
            "args": ["test", "--pass-with-no-tests", "--run-in-band", "--no-code-coverage", "--test-file"],
            "cwd": "${fileDirname}",
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "trace": "all"
            }

**Comment by vsavkin** [comment]
@Cammisuli can you reply?

**Comment by Lonli-Lokli** [comment]
You can try this launch.json, just change path to appropriate config files
{
            "type": "node",
            "request": "launch",
            "name": "[E2E] Jest Current File",
            "program": "${workspaceFolder}/node_modules/.bin/jest",
            "args": [
              "--runTestsByPath",
              "${relativeFile}",
              "--c",
              "${workspaceFolder}/apps/cv-e2e/jest.config.e2e.js",
              "--runInBand",
              "--no-cache"
            ],
            "console": "internalConsole",
            "outputCapture": "std",
            "internalConsoleOptions": "openOnSessionStart",
            "disableOptimisticBPs": true,
            "windows": {
              "program": "${workspaceFolder}/node_modules/.bin/jest",
            }
          }

**Comment by Cammisuli** [comment]
By default, Jest extensions run Jest at the root of the workspace. They don't know about the multiple Jest configs in each project, unless you specify it in the settings for the extension. And even then, you can only have one config at a time. 

I'm planning on fixing this so that if you run Jest in the root, it'll know about all the projects. But that's currently a WIP. 

In the meantime since you're using VScode, you can debug tests easily by just running the `nx test <project>` command in a JavaScript Debug Terminal: 
![image](https://user-images.githubusercontent.com/4332460/90184944-eb846c80-dd83-11ea-9dca-c12a9984cd4d.png)

Then add debug points as you normally would.

**Comment by Lonli-Lokli** [comment]
@FrozenPandaz is there any possibility now to have common code coverage calculated?
It's pretty useful to have single code coverage for the monorepo, like a sum of all project and lib reports.

**Comment by Cammisuli** [comment]
@Lonli-Lokli You should be able to just run `jest` in the root of the repo and Jest will run all projects. Hopefully that calculates all coverage reports together.

**Comment by Lonli-Lokli** [comment]
@Cammisuli It cannot find references to customized via _paths_ libraries, I believe due to this in root jest.config.js
`resolver: '@nrwl/jest/plugins/resolver',`
