### ISSUE TITLE
affected:dep-graph fails if files get removed

### ISSUE THREAD

**Issue by juristr** [nrwl/nx#3508]
## Current Behavior

When I run `yarn nx affected:dep-graph --file=dist/dep-graph.json` it fails when a file got removed in the branch.

## Expected Behavior

It shouldn't fail :)

## Steps to Reproduce

Setup commands (mostly)

```
$ npx create-nx-workspace depgraphtests --preset=angular
$ npx nx g @nrwl/angular:lib testlib
$ ng g c testcmp --testlib
$ git add .
$ git commit -am 'initial setup'
```

Create a new branch, remove the generated `testcm` and commit it. In that new branch run

```
$ yarn nx affected:dep-graph --base=master --file=dist/dep-graph.json
```

### Failure Logs

Fails with an error like the following

![image](https://user-images.githubusercontent.com/542458/90064133-9ea08780-dcea-11ea-87e6-4740e8b1efd5.png)

On the other side `yarn nx print-affected` seems to work

### Environment

```
@nrwl/angular : 10.0.11
  @nrwl/cli : 10.0.11
  @nrwl/cypress : 10.0.11
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.0.11
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.11
  @nrwl/web : Not Found
  @nrwl/workspace : 10.0.11
  typescript : 3.9.7
```

**Comment by vsavkin** [comment]
The issue was fixed both in 9x and 10x branches.
