### ISSUE TITLE
Module doesn't exist on jest config file for express application

### ISSUE THREAD

**Issue by zefexdeveloper** [nrwl/nx#3515]
## Current Behavior

I created an empty workspace and everything is working just fine but when I added an express application following the documentation on Express Plugin the `jest.config.js` file is giving me an error saying that `module` doesn't exist.

## Expected Behavior

It shouldn't give me an error on the jest config file.

## Steps to Reproduce

1. `npx create-nx-workspace@latest`

> Workspace name (e.g., org name): myorg
> What to create in the new workspace: empty

2. `yarn add -D @nrwl/express`
3. `nx generate @nrwl/express:application api`

![image](https://user-images.githubusercontent.com/30276092/90144556-55395200-dd55-11ea-87b5-089fd44e95b8.png)

### Environment

Windows 10, Node 12.18.3

**Comment by vsavkin** [comment]
Thank you for submitting the issue.

The linter should only lint files in src.

**Comment by zefexdeveloper** [comment]
@vsavkin What would be the solution for that?

**Comment by bekos** [comment]
@zefexdeveloper seems like the `eslintrc` inside the `api` folder should use `"ignorePatterns": ["/*.*", "!src/**/*"]`, so it will only lint whatever is inside your `src` folder. I will try to prepare a PR, but try it and tell me if that works for you 😃

**Comment by zefexdeveloper** [comment]
@bekos Thank you, I hope it gets merged ❤️

**Comment by Hotell** [comment]
> The linter should only lint files in src.

While it might happen that it should in reality it might be opposite. For instance we're linting all config files per project also when lib uses storybook ( config files are being linted within / nor just configs - storybook helpers/components etc)

I'd say if you introduce this it's a breaking change ( for us it definitely will be)

**Comment by JamesHenry** [comment]
I think this can be closed now. As of `v10.3.0` there is a much more lightweight `eslint` builder and as a user you control what files are included for linting via the `lintFilePatterns` array within the builder options.

**Comment by zefexdeveloper** [comment]
@JamesHenry I don't know how `v10.3.0` would solve that, I just installed and it keep giving me the same error `module is not defined`. Is there something I can do like change some setting or something?

**Comment by JamesHenry** [comment]
Ok fair enough, there is more of a config issue than a builder issue. We have some updates in the works which will more holistically address automatically this which should hopefully land in `v10.4.0`

**Comment by zefexdeveloper** [comment]
@JamesHenry Thank you very much
