### ISSUE TITLE
Export libraries in a publishable library

### ISSUE THREAD

**Issue by AsmisAlan** [nrwl/nx#3527]
Hello! 

I'm currently working on a project that contains a lot of angular libraries and I need export all in a unique publishable library.

## Current Behavior

I tried to add an export for each library in the barrel file of the publishable library and after run the build command the cli throw this error::

> libs/a-lib/src/index.ts:2:15 - error TS6059: File 'libs/b-lib/src/index.ts' is not under 'rootDir' 'libs/a-lib/src'. 'rootDir' is expected to contain all source files.

## Expected Behavior

Export all libraries into just one (publishable) that can be used for other applications outside of the current nx workspace.

## Steps to Reproduce

1. Download the repo [from here](https://github.com/AsmisAlan/nx-lib-publishable)  (I can't share the original code but you can reproduce it in this demo).
1. run ` nx build lib-publishable`

### Environment
OS: Windows 10 Pro

nx report:

  @nrwl/angular : 9.4.4
  @nrwl/cli : 9.5.1
  @nrwl/cypress : 9.4.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.4.4
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.5.1
  @nrwl/web : Not Found
  @nrwl/workspace : 9.4.4
  typescript : 3.8.3

**Comment by Cammisuli** [comment]
It looks like the repro repo you have doesn't have the publishable library there. I'm just wondering, are you publishing a library that uses node or angular?

I've seen some issues with Node related libs because of the change to solution style tsconfigs. This type of issue was fixed by removing the rootDir in the tsconfig.lib.json. You can read more here:
https://github.com/nrwl/nx/issues/3462

**Comment by AsmisAlan** [comment]
@Cammisuli Thank you for your quick response! 

First of all I apologize, reviewing the demo repo I saw that I forgot to push some changes. 

About your recommendation, the tsconfig.lib.json not define a rootDir, this value comes from the tsconfig.json that is located in the root of the project.
I tried to remove this value but nothing change and also I tried to overwrite the tsconfig.lib.json rootDir without success.

**Comment by Cammisuli** [comment]
Hmm, I thought it would have been related to node. It's something we're going to have to investigate then.

**Comment by imcvakt** [comment]
I'm facing the same issue but with react

**Comment by julianpoemp** [comment]
I was facing the "not under rootDir" issue and found out, that one of my libraries was accidentally added to the .gitignore file. After that I removed this line and the rootDir issue was solved.

**Comment by ZackDeRose** [comment]
Wanted to leave some feedback here for folks experiencing frustration around buildable libs.

The OP mentioned wanting to have a single buildable lib, whose purpose was to provide a publishable library for the rest of their workspace.

Unfortunately, by their nature, any buildable lib in your Nx Workspace may only depend on other buildable libs when it comes to importing/exporting from your local Nx Workspace. [The OP's example repro shows the one publishable lib importing from non-buildable libs]

We are looking to include more robust feedback around this limitation (see #5054 && #5160) going forward, but this message may be useful to the OP (@AsmisAlan) or others who encounter this issue or are stuck on prior Nx versions.
