### ISSUE TITLE
npm audit shows vulnerabilities for yargs-parser which is used by @nrwl/workspace

### ISSUE THREAD

**Issue by sandeeppatidar30** [nrwl/nx#3546]
npm audit shows vulnerabilities for yargs-parser which is used by @nrwl/workspace@10.0.12
 yargs-parser having latest version 19.0.1 but @nrwl/workspace uses 10.0.0

## Current Behavior
npm audit shows vulnerabilities for yargs-parser which is used by @nrwl/workspac@10.0.12
it shows found 8 vulnerabilities (4 low, 4 moderate)
## Expected Behavior

It should use latest version of yargs-parser which is 19.0.1

## Steps to Reproduce
Use @nrwl/workspace@10.0.12 and run npm audit it shows 8 vulnerabilities for yargs-parser which is internally used by @nrwl/workspace@10.0.12.

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by vsavkin** [comment]
Closed here: https://github.com/nrwl/nx/pull/3654

Thank you!
