### ISSUE TITLE
discuss: move env-specific store configuration into environment module

### ISSUE THREAD

**Issue by jeffbcross** [nrwl/nx#355]
Example: app.module.ts

```typescript
@NgModule({
  imports: [
     ...
     !environment.production ? StoreDevtoolsModule.instrument() : [],
  ]
})
```

If we, for example, want to add store freeze to this configuration across all apps, I would have to change each app's module manually. If we shifted this responsibility to the environment files themselves, it would keep apps consistent automatically when changing env-specific configuration. I.e.:

default environment.ts

```typescript
export const StoreSetup = [
  StoreDevtoolsModule.instrument()
]
```

default environment.prod.ts

```typescript
export const StoreSetup = [] // No-op
```

default app.module.ts

```typescript
import { StoreSetup } from './environment';

@NgModule({
  imports: [
    ...
    StoreSetup
  ]
})
```

Then as a developer, I can add store freeze to one place (environment.ts) and all apps will take advantage of it.

**Comment by ThomasBurleson** [comment]
@jeffbcross - like this with one exception:

`StoreSetup` ---> `StoreDevToolsSetup`

**Comment by jeffbcross** [comment]
@ThomasBurleson do you see the dev.tools.ts module as doing anything other than returning this object? What value does it add to introduce another module and object for this?

BTW `DevTools.instrumentStore` is not callable in that example (but you're calling it in app.module). What is the intended API?

**Comment by vsavkin** [comment]
Closing this. No immediate plans to implement it.
