### ISSUE TITLE
Cypress Builder: Support for Percy.IO

### ISSUE THREAD

**Issue by rolandoldengarm** [nrwl/nx#3567]
## Description
Percy.io requires that Cypress is wrapped inside a Percy command, see step 4 [here](https://docs.percy.io/docs/cypress). The NRWL Cypress builder does not support this, as it is running Cypress directly [here](https://github.com/nrwl/nx/blob/master/packages/cypress/src/builders/cypress/cypress.impl.ts#L182).

## Motivation
Percy.IO is an amazing tool for visual tests.

## Suggested Implementation
Provide a way to wrap the Cypress execution in another process.

## Alternate Implementations
Have a config flag in the builder "isPercy" which will make sure it's run inside the Percy process.

**Comment by mehrad-rafigh** [comment]
What about the people not using percy? How would this change affect them?

**Comment by mehrad-rafigh** [comment]
We are really interested to use percy. Should I create a PR?

**Comment by MmtBkn** [comment]
We are interested in this feature too. @bcabanes, how can we achieve this? Could we just execute it as bash here, and return the status code?
https://github.com/nrwl/nx/blob/41ad2654266926d53ad008f45b13b5ad7cc697d8/packages/cypress/src/builders/cypress/cypress.impl.ts#L191

**Comment by elvirdolic** [comment]
We are doing this

` "affected:e2e": "percy exec -- nx affected:e2e`

**Comment by smasala** [comment]
Are there any solutions for running percy and nx affected tests in cache mode?

**Comment by ola-jha** [comment]
Has there been any solution to this?

**Comment by cyrus-za** [comment]
Any news on this?

**Comment by konstantinschuette** [comment]
> 



> We are doing this
> 
> ` "affected:e2e": "percy exec -- nx affected:e2e`

This solution doesn't work when you use NX cloud.
Because if the E2E tests are already cached, they will not be executed and Percy will fail.
