### ISSUE TITLE
Option to exclude file pattern while calculating affected projects

### ISSUE THREAD

**Issue by dogancana** [nrwl/nx#3577]
## Description
Affected logic is used in various tasks and some file patterns are not necessary in some of these tasks. An example would be excluding style files while running unit tests.
I'd like to have an option to pass an ignore file pattern for affected command.

## Motivation
This would decrease affected projects, resulting in faster execution times. 

## Suggested Implementation
Could filter out the files according to exclude file pattern, just after calling calculateFileChanges in affected command.

## Alternate Implementations
NA

If the feature request is valid and fits into your planning, I can create a PR

**Comment by webberwang** [comment]
Here is a hack for the time being.

Currently you can specify a comma separated list of files to include using the `files` flag. 

You could glob your project using the excluded files/extensions, then transform that into a list, then pass into files.

**Comment by dogancana** [comment]
Thanks @webberwang. I actually started to plan that. But I realised that I'm building my own 'find affected' logic. That's why I created this suggestion
