### ISSUE TITLE
nx 9 React build hangs forever

### ISSUE THREAD

**Issue by ThatMate** [nrwl/nx#3578]
I have upgraded from nx 8 to 9 as I have mentioned here: https://github.com/nrwl/nx/issues/2946#issuecomment-673669180 

This has been working for `nx serve adm` where `adm` is a react project.

But it hangs forever when I try to do a build. This is blocking us from release.

## Current Behavior

Here is what I see: **(started at Fri Aug 21 15:57:38 IST 2020)**
This build takes 23 minutes for a small project with under 100 TypeScript files.

```
nx build adm --configuration=test

> nx run adm:build:test
Starting type checking service...
Using 6 workers with 2048MB memory limit
Hash: ba74bd0b993c4cc1d0a8
**Built at: 08/21/2020 4:04:06 PM**
Entrypoint main [big] = runtime.365178a7a0f8f038a0f1.js runtime.365178a7a0f8f038a0f1.js.map main.3f6765b8b8417aeefa3f.esm.js main.3f6765b8b8417aeefa3f.esm.js.map
Entrypoint polyfills = runtime.365178a7a0f8f038a0f1.js runtime.365178a7a0f8f038a0f1.js.map polyfills.c5c4fdadab70353ad788.esm.js polyfills.c5c4fdadab70353ad788.esm.js.map
chunk    {0} runtime.365178a7a0f8f038a0f1.js, runtime.365178a7a0f8f038a0f1.js.map (runtime) 0 bytes ={1}= ={2}= [entry] [rendered]
chunk    {1} main.3f6765b8b8417aeefa3f.esm.js, main.3f6765b8b8417aeefa3f.esm.js.map (main) 5.19 MiB ={0}= [initial] [rendered]
chunk    {2} polyfills.c5c4fdadab70353ad788.esm.js, polyfills.c5c4fdadab70353ad788.esm.js.map (polyfills) 239 KiB ={0}= [initial] [rendered]
Starting type checking service...
Using 6 workers with 2048MB memory limit
Hash: 880faff852f16f6d1d68
**Built at: 08/21/2020 4:19:57 PM**
Entrypoint main [big] = runtime.ea86ecefbed611ddfe95.js runtime.ea86ecefbed611ddfe95.js.map main.785e1e2eabb749cd730c.es5.js main.785e1e2eabb749cd730c.es5.js.map
Entrypoint polyfills = runtime.ea86ecefbed611ddfe95.js runtime.ea86ecefbed611ddfe95.js.map polyfills.538942d830539f549034.es5.js polyfills.538942d830539f549034.es5.js.map
chunk    {0} runtime.ea86ecefbed611ddfe95.js, runtime.ea86ecefbed611ddfe95.js.map (runtime) 0 bytes ={1}= ={2}= [entry] [rendered]
chunk    {1} main.785e1e2eabb749cd730c.es5.js, main.785e1e2eabb749cd730c.es5.js.map (main) 5.29 MiB ={0}= [initial] [rendered]
chunk    {2} polyfills.538942d830539f549034.es5.js, polyfills.538942d830539f549034.es5.js.map (polyfills) 388 KiB ={0}= [initial] [rendered]
```

Finishes at **Fri Aug 21 16:21:59 IST 2020**

Other projects are node applications and they get build fairly quickly.

## Expected Behavior

Build should finish with or without error. But it stays unresponsive.

## Steps to Reproduce
Create a monorepo with ReactJS project in nx version 8, Migrate it to nx 9. Try a build. 

### Environment
nx report

>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.0.11
  @nrwl/cypress : 10.0.11
  @nrwl/eslint-plugin-nx : 10.0.11
  @nrwl/express : 10.0.11
  @nrwl/jest : 10.0.11
  @nrwl/linter : 10.0.11
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.0.11
  @nrwl/react : 10.0.11
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.11
  @nrwl/web : 10.0.11
  @nrwl/workspace : 10.0.11
  typescript : 3.9.7

System Info:

  Model Name:	MacBook Pro
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB

**Comment by webberwang** [comment]
What command did you type to migrate?

**Comment by ThatMate** [comment]
Bump: Any idea how to debug this?

**Comment by vsavkin** [comment]
Sorry for the late reply. It's a bit challenging to troubleshoot it without having a repro. 

Are you able to reproduce it in a small repo? What does the test configuration contain and how is different from the default one?

**Comment by LuminalZero** [comment]
I've encountered this a number of times of late. I'm of the belief that it has to do with restoring the node modules.
