### ISSUE TITLE
npx create-nx-workspace fails

### ISSUE THREAD

**Issue by spaceghostu** [nrwl/nx#3584]
## Current Behavior
Does not create workspace after asking questions

## Expected Behavior
Create a nx workspace

## Steps to Reproduce
run "npx create-nx-workspace"

use these values in questions:

? Workspace name                                        example
? What to create in the new workspace      angular          
? Application name                                        example
? Default stylesheet format                           CSS
? Use the free tier of the distributed cache provided by Nx Cloud? (Use arrow keys)
  Yes [Faster command execution, faster CI. Learn more at https://nx.app]
❯ No  [Only use local computation cache]

wait 

then fails

### Failure Logs
❯ npx create-nx-workspace
npx: installed 193 in 30.404s
? Workspace name (e.g., org name)     example
? What to create in the new workspace angular           [a workspace with a single Angular application]
? Application name                    example
? Default stylesheet format           CSS
? Use the free tier of the distributed cache provided by Nx Cloud? No  [Only use local computation cache]
Creating a sandbox with Nx...
added 409 packages from 238 contributors and audited 409 packages in 7.408s

25 packages are looking for funding
  run `npm fund` for details

found 4 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
new example  --preset="angular" --appName="example" --style="css" --interactive=false --collection=@nrwl/workspace
Unknown error: Error: No valid exports main found for '/private/var/folders/_8/y_vc5mbj15l740gvbbdhlh1c0000gn/T/tmp-77457K4hhpc2jvdc8/node_modules/uuid'
(node:77457) UnhandledPromiseRejectionWarning: Error: Command failed: "/var/folders/_8/y_vc5mbj15l740gvbbdhlh1c0000gn/T/tmp-77457K4hhpc2jvdc8/node_modules/.bin/ng" new example  --preset="angular" --appName="example" --style="css" --interactive=false --collection=/var/folders/_8/y_vc5mbj15l740gvbbdhlh1c0000gn/T/tmp-77457K4hhpc2jvdc8/node_modules/@nrwl/workspace/collection.json
    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:647:15)
    at createApp (/Users/calvindurramt/.npm/_npx/77457/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:367:21)
    at /Users/calvindurramt/.npm/_npx/77457/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:85:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:77457) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:77457) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Environment
nx report
Could not find Nx in this workspace.

**Comment by webberwang** [comment]
<img width="651" alt="webber_webbers-mbp____Sites_Codelab" src="https://user-images.githubusercontent.com/26264925/91291105-6c127800-e749-11ea-9e7d-8f42e2553516.png">

**Comment by webberwang** [comment]
```Unknown error: Error: No valid exports main found for '/private/var/folders/_8/y_vc5mbj15l740gvbbdhlh1c0000gn/T/tmp-77457K4hhpc2jvdc8/node_modules/uuid'```

Could be some issue with your cache. Clear your npm or yarn cache then try again

**Comment by jeffkhull** [comment]
I am getting this same error with latest.  Here is my output.  I also tried clearing the cache.


> ➜  nx npx create-nx-workspace@latest
> npx: installed 193 in 5.223s
> ? Workspace name (e.g., org name)     test-nx
> ? What to create in the new workspace react-express     [a workspace with a full stack application (React + Express)]
> ? Application name                    test-nx
> ? Default stylesheet format           emotion           [ https://emotion.sh                       ]
> ? Use the free tier of the distributed cache provided by Nx Cloud? No  [Only use local computation cache]
> Creating a sandbox with Nx...
> [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 0/355
> new test-nx  --preset="react-express" --appName="test-nx" --style="@emotion/styled" --interactive=false --collection=@nrwl/workspace
> ✖ Package install failed, see above.
> The Schematic workflow failed. See above.
> (node:51151) UnhandledPromiseRejectionWarning: Error: Command failed: "/tmp/tmp-511515ZcYIZjkXD3E/node_modules/.bin/tao" new test-nx  --preset="react-express" --appName="test-nx" --style="@emotion/styled" --interactive=false --collection=/tmp/tmp-511515ZcYIZjkXD3E/node_modules/@nrwl/workspace/collection.json
>     at checkExecSyncError (child_process.js:630:11)
>     at Object.execSync (child_process.js:666:15)
>     at createApp (/home/jeff/.npm/_npx/51151/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:367:21)
>     at /home/jeff/.npm/_npx/51151/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:85:25
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:51151) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:51151) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by vsavkin** [comment]
Hi folks. It's hard to troubleshoot it cause the only thing the error message indicates is that your `npm install` failed. There are a lot of reasons for that to happen. 

- You might have a custom npm registry set up (e.g., an artifactory)
- Firewall 
- Npm could be down (this happens a lot more than one might image)
- Your global npm cache is screwed up.

The way I'd go about it:
- Does it work with `yarn create nx-workspace`, something is wrong with global npm modules. If it doesn't, probably an issue with artifactory.

**Comment by shantanu-deshmukh** [comment]
Was having the same issue, clearing yarn cache fixed it for me. 
```cmd
yarn cache clean
npx create-nx-workspace@latest
```
