### ISSUE TITLE
Exclude a file from the webpack watch?  - currently causes a rebuild which I don't want it to

### ISSUE THREAD

**Issue by iangregsondev** [nrwl/nx#3599]
Hi,

Can anyone help ?

I am extending a webpack config to create a json file (version.json) which contains a git hash - which I need for my app.

I do it like so

```
const file = join(__dirname, "/src/config/version.json")

console.log(`Writing version to json : ${file}\n`)
// Excluded rest of code for readability.

module.exports = (config) => {

  return config
}
```

The problem here is that when I first start the app (serve) then I get the app restarting the build process, so it almost finishes and then restarts the build again.

This is because of the version.json file, the file changes so webpack/nx detects this and restarts the build again.

Is there any way to exclude this file or even the directory "__dirname, "/src/config" "?

So webpack will not force another build just because the version.json changes.

My actually webpack config is pretty empty right now

```
module.exports = (config) => {

  return config
}
```

I was wondering if there is some property that I can pass in the angular.json to ignore a file/ directory from the watch list of the webpack ?

Any help really appreciated

Thanks

**Comment by realappie** [comment]
Great question, sad to see this closed without any answer. Seems like a simple problem.
