### ISSUE TITLE
feat(schematics/workspace): translate baseurl-relative paths from AngularCLI to workspace

### ISSUE THREAD

**Issue by jeffbcross** [nrwl/nx#36]
When I generated new components in my Angular CLI app, it would import them as follows in app.module:

```typescript
import { MyComponent } from 'app/my/my.component';
```

AFAIK, the `app/` import works because the `baseUrl` in `<root>/tsconfig.json` is set to "src".

This doesn't work after upgrading to Nx workspace since the directory layout changes, and `baseUrl` changes from `src` to `.`.

It would be nice to fix this automatically. Simplest fix would be to add an `app` entry to paths in the root tsconfig.json, which can point to `apps/original-app`. But this would encourage other libs and apps to import from `app`, which is not recommended. The better solution would be to rewrite all `app/` imports to be relative.

**Comment by vsavkin** [comment]
Has been fixed in the CLI
