### ISSUE TITLE
Weird jest output

### ISSUE THREAD

**Issue by joshribakoff** [nrwl/nx#3603]
## Current Behavior
Expected actual output has random integers unrelated to my test? 

![Screen Shot 2020-08-25 at 8 05 56 AM](https://user-images.githubusercontent.com/4021306/91191685-eee3f600-e6a9-11ea-8f76-f3069da88e74.png)

## Expected Behavior
Match behavior in create-react-app, no random stuff in test output:

![Screen Shot 2020-08-25 at 8 05 13 AM](https://user-images.githubusercontent.com/4021306/91191696-f3a8aa00-e6a9-11ea-80f2-2a995217532c.png)

## Steps to Reproduce
Just write a failing test in our repo: https://github.com/rx-store/rx-store/pull/62/files

### Environment

```
  nx : Not Found
  @nrwl/angular : 10.0.7
  @nrwl/cli : 10.0.7
  @nrwl/cypress : 10.0.7
  @nrwl/eslint-plugin-nx : 10.0.7
  @nrwl/express : Not Found
  @nrwl/jest : 10.0.7
  @nrwl/linter : 10.0.7
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 10.0.7
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.7
  @nrwl/web : 10.0.7
  @nrwl/workspace : 10.0.7
  typescript : 3.9.7
```

**Comment by webberwang** [comment]
Are you referring to the `-3` `+1`? That is the line diff count & is normal behavior

**Comment by joshribakoff** [comment]
Got it, thanks. Wasn’t familiar with seeing that FYI. I wonder if there’s a reason they default it to off
