### ISSUE TITLE
React testing improvements

### ISSUE THREAD

**Issue by joshribakoff** [nrwl/nx#3605]
## Description
I'm normally used to using Enzyme but I noticed Nx used react-testing-library in our project w/ no option to change it within Nx.

I started trying to learn react-testing-library & then [ran into this issue](https://github.com/testing-library/react-testing-library/issues/379) because ~the jest custom matchers are not setup.~ I guess I just need to import this at the top of every test

## Motivation
~Better testing out of the box w/o having to debug the setup~
Some users may want to use Enzyme

## Suggested Implementation
- offer an option for Enzyme?
- flesh out the react-testing-library setup a bit more
  - `yarn add @testing-library/jest-dom --dev `
  - add `import '@testing-library/jest-dom';` to the test because the example on https://testing-library.com/docs/react-testing-library/example-intro produces type error about missing `.toHaveTextContent()` method, and only changing it to this seems to fix it

## Alternate Implementations
~You could omit tests in the react builder? Although that would take away some of the benefits of using Nx in the first place.~

**Comment by karol-majewski** [comment]
To anyone interested: I managed to add types for custom matchers (such as `toHaveTextContent `) by modifying the `tsconfig.spec.json` in the directory I'm testing:

```diff
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "module": "commonjs",
-   "types": ["jest", "node"]
+   "types": ["jest", "node", "testing-library__jest-dom"]
  },
  "include": ["**/*.spec.ts", "**/*.spec.tsx"]
}
```

**Comment by Divlo** [comment]
Thanks, it actually works! @karol-majewski 
The cleaner way in my opinion is instead of `"testing-library__jest-dom"`, it is `"@testing-library/jest-dom"`.

**Comment by nvitaterna** [comment]
> To anyone interested: I managed to add types for custom matchers (such as `toHaveTextContent `) by modifying the `tsconfig.spec.json` in the directory I'm testing:
> 
> ```diff
> {
>   "extends": "./tsconfig.json",
>   "compilerOptions": {
>     "outDir": "../../dist/out-tsc",
>     "module": "commonjs",
> -   "types": ["jest", "node"]
> +   "types": ["jest", "node", "testing-library__jest-dom"]
>   },
>   "include": ["**/*.spec.ts", "**/*.spec.tsx"]
> }
> ```
> 
> With this change, you don't need to import `@testing-library/jest-dom` in every test file.
> 
> (Make sure to install `@types/testing-library__jest-dom` first.)

Where do you import `@testing-library/jest-dom` initially? IIRC it has to be imported *somewhere* but I'm not exactly sure where to put it to make it available for the whole workspace.

**Comment by karol-majewski** [comment]
It needs to be imported in your Jest setup file:


**`apps/<app-name>/jest.config.js`**

```js
module.exports = {
  ...
  /**
   * Enable `@testing-library/jest-dom` matchers.
   *
   * @see https://jestjs.io/docs/configuration#setupfilesafterenv-array
   */
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
};
```

**`apps/<app-name>/jest.setup.ts`**

```js
/**
 * Enable `@testing-library/jest-dom` matchers such as toHaveTextContent or toHaveAttribute.
 */
import '@testing-library/jest-dom';
```

**Comment by Shaglock** [comment]
I had the same issue and in my case in my library folder `libs/<mylib>` I created `jest.setup.ts` with import, same as in [this comment](https://github.com/nrwl/nx/issues/3605#issuecomment-849907534), but I didn't make any type imports, instead, in `tsconfig.spec.json` I added to `include` like this:
```
{
...
  "include": [
    **"./jest.setup.ts",**
    "**/*.spec.ts",
...
  ]
}
``` 
and had no issues.
I wanted to use `jest.preset.js` that NX provides but didn't manage to make it work. I wish I could do this with preset, so that I don't have to create `jest.setup.ts` in every lib/app I have and do the same `include`s in `tsconfig`s everywhere.

**Comment by marcuiulian13** [comment]
To add to the solution suggested by @Shaglock:

1. Create a `setupTests.ts` file in the root of the monorepo with whatever is required for you - testing library, fetch mock, etc.

2. Add the following to `/jest.preset.ts`:
```
setupFilesAfterEnv: ['../../setupTests.ts'],
```

3. Add the following to each app/library's `tsconfig.spec.json`'s `include` array:
```
include: [
    "../../setupTests.ts",
]
```

This will get you the desired result.
