### ISSUE TITLE
Adding tests broke our build

### ISSUE THREAD

**Issue by joshribakoff** [nrwl/nx#3607]
https://github.com/rx-store/rx-store/pull/63 build fails adding tests to upstream lib because the `affected` command doesn't understand that the "core" lib must be built in order to first test the "react" lib which consumes from the "core" lib.

Sorry I didn't use the template, not much time & I think its straightforward. Happy to provide more details, and everything is right there open source.

**Comment by joshribakoff** [comment]
I'd propose it should build the core even w/o `--with-deps` if the core is not already built, instead of error'ing? Or determine when its needed & always build it, without needing a flag? Why would you ever want stale build output?

**Comment by joshribakoff** [comment]
Feel free to close this, it seems `--with-deps` did fix it, but my feedback is that it seems un-intuitive, one alternative (if there's some need for people to have stale deps, maybe for perf or due to some known limitation) would be to default to it being on? Or maybe Nx could provide some more "out of the box" setup for CI checks  [we apparently got ours a bit wrong initially]

**Comment by webberwang** [comment]
The doc does make the distinction https://nx.dev/angular/cli/affected-build

<img width="595" alt="cli__affected_build___Nx_angular_documentation" src="https://user-images.githubusercontent.com/26264925/91289226-ec83a980-e746-11ea-856e-3f6d280ebee9.png">

I think making it opt in / out is more complicated. Reading the docs above, one can deduce that `affected` means direct code change, and `--with-deps` will include dependencies

**Comment by joshribakoff** [comment]
I agree on the making it more complicated being a downside. That’s why I’m not sure why we have the flag at all, and it doesn’t always build deps of affected projects in all cases where it needs to be built (maybe store a hash in the dist, if it’s missing or invalid a rebuild is required?)

Cheers

**Comment by webberwang** [comment]
Did you mean that even with `--with-deps` it doesn't always build required dependencies?

**Comment by joshribakoff** [comment]
Sorry I worded that a bit confusingly. There is 2 points I'm trying to make, I guess.

1) I am not sure why we have `--with-deps` flag, I cannot think of any case where I would not want to build my deps. It also seems like nx could potentially store a manifest of hashes, and use this to detect when building deps is needed, all automatically so no flag would be needed anymore.

2) In our repo at least, we have a small number of libs and a large number of apps. A minor change to a readme or unit test would ideally not cause all affected apps to rebuild (because it does not actually affect them), but that is what Nx did here. It rebuilt every app that used my lib, even though the lib did not materially change, and it also defaulted to not building the necessary dependencies of my lib, which seems counter intuitive.

In my opinion at least, it would be nice for Nx to *always* build the deps (if its necessary to do so because they haven't been built, or the built code is out of date). I would never want to not build the deps if they're out of date or missing. This could be accomplished with hashing & a manifest. It would also allow it potentially figure out if my changes didn't actually touch the production TS code & only files referenced in the "test" tsconfig were changed.

**Comment by webberwang** [comment]
1) `--with-dep` works across different commands, like test etc Taking `--with-dep` out would break all those features. You could just add `--with-dep` to your build script to resolve the issue.

2) you'll need to post your project so we know how it is configured, otherwise we won't have enough information

**Comment by joshribakoff** [comment]
1 - why would you need to ask Nx to run tests for (unchanged) deps? Why not run tests for all the affected packages and build dependencies (as needed)?

2 - see link in my OP to failing PR / our project

This is resolved and is just feedback so feel free to close if you think the current behavior is good

**Comment by webberwang** [comment]
1. A more flexible API can cover more use cases. If we take out the feature, would you agree that some users will have lost a needed capability in their workflow? The current API does cover your needs

2. https://github.com/rx-store/rx-store/runs/1027591351 Appears to me that it broke because the deps were not built

**Comment by joshribakoff** [comment]
1 - Just asking the use case, describing the use case in the docs where it explains `--with-deps` would maybe be good. I also think it could be inverted to `--without-deps`, so that by default Nx does what [in my opinion] most users would expect by default, and does not default to a workflow that is (for lack of a better word) "broken" in some cases, requiring users to figure out why & what to do. IMO it would make Nx that much better for newer users especially!

2 - Yeah I got that. I'm just saying defaulting to not creating the build is a bit counter intutivie

Thanks for the detailed thoughts
