### ISSUE TITLE
Support different eslintrc file formats

### ISSUE THREAD

**Issue by darkowic** [nrwl/nx#3609]
## Description

Currently seems like only `.eslintrc` file is supported for eslint configuration. But eslint allows storing configuration in different more convenient file formats like `.js` - https://eslint.org/docs/user-guide/configuring#configuration-file-formats-1

## Motivation

Js format is easier to write and allows more flexibility.

**Comment by webberwang** [comment]
I agree with this as well. I encountered issue when using TypeScript ESLint Parser, which requires `tsconfigRootDir` to be set. Using `__dirname` was the only way I could resolve the path correctly across IDE's.

**Comment by Hotell** [comment]
> I agree with this as well. I encountered issue when using TypeScript ESLint Parser, which requires `tsconfigRootDir` to be set. Using `__dirname` was the only way I could resolve the path correctly across IDE's.

That can be done in standard json format as well.

---

Using commonjs module for config comes with its own downsides - for example hard to write schematics as AST transforms need to be involved. Static declarative configs are always prefered instead of dynamic.
Also you can always modify it by hand to js config instead of json if you need to do so.

**Comment by piet-v** [comment]
Also needed to be able to set `tsconfigRootDir` to get proper support in WebStorm IDE.

I first swapped `.eslintrc` with `.eslintrc.js` but then I noticed `.eslintrc` gets created every time a library is generated which broke WebStorm support again😓 

Managed to get it working with a different workaround:

step 1: Create `.eslintrc.js` with content:
```
module.exports = {
  parserOptions: {
    tsconfigRootDir: __dirname,
  },
};
```

step 2: Add `"./.eslintrc.js",` to `extends` array in in `.eslintrc`

**Comment by JamesHenry** [comment]
Thanks folks, I am going to close this one for the following reasons:

1. One of Nx's greatest strengths is its ability to migrate users' workspaces when things change in e.g. configuration files, so supporting migrating multiple configuration file formats would put too much strain on Nx maintainers
2. JSON files are _significantly_ easier to statically analyse and migrate, so keeping that as the only format for now makes sense (I am somewhat dreading ESLint's proposed upcoming change to only supporting a new `eslint.config.js` file, but let's not open that can of worms until we have to!)
3. Any user that wants to turn their back on the automated migrations and use a custom, hand-crafted .js, .yml or any other supported configuration file type is free and able to do so already, they are not blocked

Hope that makes sense!
