### ISSUE TITLE
Inject NODE_ENV=production when building app with --prod

### ISSUE THREAD

**Issue by darkowic** [nrwl/nx#3610]
## Description

`NODE_ENV` env variable is used widely in the js environment to mark the production version of a build.

## Motivation

Production build command has to be run with `NODE_ENV=production` to get the best optimization result.

Without `NODE_ENV=production`:
```
$ yarn build wizard --prod
yarn run v1.22.4
$ nx build wizard --prod

> nx run wizard:build:production 
Starting type checking service...
Using 2 workers with 2048MB memory limit
Hash: 49714b4f2c714d253909
Built at: 08/26/2020 8:16:21 AM
Entrypoint main [big] = runtime.4e9d49fabb961c79b027.js vendor.3e61a74c967da0482112.esm.js main.cc6f80f2e5704e40992d.esm.js
chunk    {0} main.cc6f80f2e5704e40992d.esm.js (main) 381 KiB ={1}= ={2}= [initial] [rendered]
chunk    {1} runtime.4e9d49fabb961c79b027.js (runtime) 0 bytes ={0}= ={2}= [entry] [rendered]
chunk    {2} vendor.3e61a74c967da0482112.esm.js (vendor) 2.51 MiB ={0}= ={1}= [initial] [rendered] split chunk (cache group: vendor) (name: vendor)
Done in 31.53s.
```
with `NODE_ENV=production`:
```
$ NODE_ENV=production yarn build wizard --prod --no-cache
yarn run v1.22.4
$ nx build wizard --prod --no-cache

> nx run wizard:build:production --no-cache 
Starting type checking service...
Using 2 workers with 2048MB memory limit
Hash: 3f5664cca70ba6ff5565
Built at: 08/26/2020 8:28:07 AM
Entrypoint main [big] = runtime.4e9d49fabb961c79b027.js vendor.3131a3729f30f53d53a3.esm.js main.b483c90b1446222c378b.esm.js
chunk    {0} main.b483c90b1446222c378b.esm.js (main) 381 KiB ={1}= ={2}= [initial] [rendered]
chunk    {1} runtime.4e9d49fabb961c79b027.js (runtime) 0 bytes ={0}= ={2}= [entry] [rendered]
chunk    {2} vendor.3131a3729f30f53d53a3.esm.js (vendor) 1.7 MiB ={0}= ={1}= [initial] [rendered] split chunk (cache group: vendor) (name: vendor)
Done in 29.07s.
```

Without providing this env variable I get following warning in the browser console:
```
VM29 vendor.3e61a74c967da0482112.esm.js:2 You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
```

## Suggested Implementation

Always inject `NODE_ENV` variable for the build, start process - `development` by default and `production` when optimization or prod version is built.

**Comment by danielfyhr** [comment]
Are you using the node builder here?

Have you tried this setting for production builds?
https://nx.dev/angular/plugins/node/builders/build#optimization
In your workspace.json or angular.json try
  ```
  "configurations": {
            "production": {
              "optimization": true
            }
   }
```
Your warning in the browser suggests "setting mode to production in webpack (https://webpack.js.org/concepts/mode/)" which the above configuration should set as seen in https://github.com/nrwl/nx/blob/dd1527ce0311b30c482daf04095c192e91d07c26/packages/node/src/utils/config.ts#L30

**Comment by darkowic** [comment]
I use `@nrwl/web:build` and yes, I have `optimization` set to `true`.

**Comment by timbakkum** [comment]
We are running into the same issue, but only when using `nx serve our-app --prod`. It seems to create a production build, but when running the code on the dev server, `process.env.NODE_ENV` is still set to `'development'`. 

However, when just running a `nx build our-app --prod` the code under `process.env.NODE_ENV === 'development'` conditionals is properly stripped out. 

We don't see a difference in build sizes when explicitly passing `NODE_ENV=production` to `nx build our-app --prod` or without, which is to be expected because we notice that the `mode: production` is properly set in both cases. As per the webpack documentation, it seems to automatically set the `process.env.NODE_ENV` to `production` during build time: https://webpack.js.org/guides/production/#specify-the-mode

**Comment by darkowic** [comment]
It's still there probably. Need to upgrade to the latest version to confirm...

**Comment by Kunjinkao0** [comment]
Hi @danielfyhr, this page had gone https://nx.dev/angular/plugins/node/builders/build#optimization, is there any best practice of using env variables for the workspace? I just found environment in React but no Angular.

**Comment by puku0x** [comment]
https://github.com/nrwl/nx/pull/5522 might solve this too?

**Comment by danielfyhr** [comment]
@Kunjinkao0 
> Hi @danielfyhr, this page had gone https://nx.dev/angular/plugins/node/builders/build#optimization, is there any best practice of using env variables for the workspace? I just found environment in React but no Angular.

That link should be here now: https://nx.dev/latest/react/web/build#optimization (I was looking at the node builder the first time I posted, but the web builder is the correct one).

I don't know about any best practices for env variables in the workspace, but https://github.com/nrwl/nx/pull/5522 looks interesting for solving the original issue.

**Comment by nhp2907** [comment]
With flat --prod it's okay.
But i also need another env such as "testing" or "staging".
So NODE_ENV should not be replaced
