### ISSUE TITLE
Angular 6 support roadmap

### ISSUE THREAD

**Issue by noelmace** [nrwl/nx#362]
Do you have / What's your plan to support Angular 6 ?

This issue follow [the comment on this issue by @vsavkin ](https://github.com/nrwl/nx/issues/261#issuecomment-366716319).

The main issue I see for now is the dependency to TypeScript 2.6, given that Angular 6 require TS 2.7. This is blocked by ngrx/platform/issues/926 for data persistence, but their is also an issue with schematics (nrwl/nx/issues/261).

**Comment by jeffbcross** [comment]
We'll try to release as close to the final release of Angular v6 as possible, once all dependencies can play together nicely.

**Comment by noelmace** [comment]
@jeffbcross thanks for this efficient response :D If you have the time to give more informations about the current issues on this, I would be happy to help if possible, given that I wanted to try to use angular elements in one of my Nx project. But I could also just wait

**Comment by noelmace** [comment]
Link https://github.com/nrwl/nx/issues/377

**Comment by lexcaraig** [comment]
will this also support the `ng add <package>` command? Thanks!

**Comment by FrozenPandaz** [comment]
@lexcaraig Yes it will! `ng add @nrwl/schematics` is available in the RC right now actually!
