### ISSUE TITLE
create-nx-plugin cant find @nrwl/workspace collection

### ISSUE THREAD

**Issue by stefan-karlsson** [nrwl/nx#3626]
## Current Behavior
`npx create-nx-plugin nx-plugins --pluginName my-plugin` generates the error `Collection "@nrwl/workspace" cannot be resolved.`

## Expected Behavior
Able to run  create-nx-plugin without any errors

## Steps to Reproduce
- `npx create-nx-plugin nx-plugins --pluginName my-plugin`

![image](https://user-images.githubusercontent.com/25538602/91635495-40b5b480-e9f9-11ea-85e3-678ea2fad157.png)

**Comment by neophyt3** [comment]
coincidentally faced same issue yesterday
I have raised a PR which fixes this issue
FYI https://github.com/nrwl/nx/issues/3626

**Comment by Cammisuli** [comment]
Fixed with #3631
