### ISSUE TITLE
Do not use `require(path.join(workspace.dir` type requires - can help some folks already using yarn 2

### ISSUE THREAD

**Issue by sushruth** [nrwl/nx#3637]
## Description

Would be nice to not use requires like `require(path.join(workspace.dir` to allow yarn 2 adoption as well.

## Motivation

mainly yarn 2 compatibility

## Suggested Implementation

Not too different from how it works now.

## Alternate Implementations

NA

**Comment by bekos** [comment]
@sushruth I believe all requires inside the repo are fixed now. There are still some things to be fixed for Yarn 2 support, mainly in the applications we generate, but let's keep track of it in https://github.com/nrwl/nx/issues/2386.
