### ISSUE TITLE
Visualizing Dependency Tree

### ISSUE THREAD

**Issue by vsavkin** [nrwl/nx#364]
# Visualizing Dependency Tree

Nx knows about all libs and apps and how they depend on each other.

This is how you can get the data:

```
const nodes = getProjectNodes(cliConfig);
const deps = readDependencies(cliConfig.project.npmScope, nodes);
```

We should provide a command displaying this graph.

## Commands

`npm run dependency-graph`

Should display a DAG.

* Type of nodes: `app`, `lib`, `global`. Every node in the graph is either an app or app lib. There is one extra node called "global". Every app implicitly depends on the global. Libs cannot depend on global.
* Types of edges: `es6import`, `lazyLoading`, `implicit`. All dependencies on global are "implicit".
* Every node should display the name of the app/lib, including the directory. It should also display the node's tags.
* Every edge should display the relationship type.

`npm run affected:dependency-graph -- SHA1 SHA2`

* Show display the same DAG as above.
* Every affected app's node should be "highlighted".
* Every touched project should be highlighted as well, but in a different way.
* List of touched global files should be displayed as well.

The tool should work on all platforms. Maybe we can utilize http://www.webgraphviz.com? So when the user runs the command we will just generate a file or open webgraphviz in the browser and render the graph?

**Comment by skydever** [comment]
I found [viz.js](https://github.com/mdaines/viz.js/wiki/API) to render a graph nicely, [compodoc](https://github.com/compodoc/compodoc) is using it too, maybe it is useful @electrichead ?

including graphs for apps and libs in compodoc would be cool too, it looks very nice, but for what I figured out they only support 1 app to generate the docs properly (?) - so this issue is a very nice thing, maybe also as an extension for compodoc (as a part for app and lib dependencies)?

**Comment by electrichead** [comment]
It appears that we can approach this in two ways:
1. Command-line only: the idea is to generate an SVG and save to disk. viz.js allows us to do this without requiring graphviz to be installed on the system (making it cross-platform).
2. Output the data as JSON to a folder which contains an index.html file that renders the graph (similar to istanbul and compodoc). Either the tool or the user would have to open this file in the browser.

Approach 2 allows us to be more flexible in what the rendering looks like and allows us to make it interactive in future.

Approach 1 is quicker and allows us to iterate on it based on how users use it.

**Comment by skydever** [comment]
I created a small [stackblitz](https://stackblitz.com/edit/angular-wjx1pq?embed=1&file=app/app.component.ts&hideExplorer=1) that is generating the graph from the `/dist/nxdeps.json` only, that the linter is creating (not covering all use cases though) and thought I could share it, for a quick overview of the workspace (just played around a bit myself, then tried to use the styling from your pr 👍)

maybe creating a vscode extension is something useful, showing a new tab in the ide to view the graph with commands/keybindings to the different affected options, or as links/options in the view ...

**Comment by vsavkin** [comment]
We have added some support for this.

Run `yarn dep-graph --help` to see the available options.

```
Graph dependencies within workspace

Run command using:
  --files        A list of files delimited by commas                     [array]
  --uncommitted  Uncommitted changes
  --untracked    Untracked changes

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
  --file     output file (e.g. --file=.vis/output.json)
```

If you run `yarn dep-graph`, it will open the dep graph in the browser. 

You can also run `yarn affected:dep-graph` to see apps and libs affected by a file change.

@skydever: a vscode extension is a good idea. We are also thinking about having a web version.

I'm closing this issue. Any future work on this should be tracked in other issues.
