### ISSUE TITLE
@nrwl/storybook Set Project/App to take build config

### ISSUE THREAD

**Issue by ChazUK** [nrwl/nx#3655]
I'm running Storybook on an Angular project for a UI library. When running `nx run ui:storybook` the build configuration is taken from the `defaultProject` property in `angular.json`

```
info => Using angular project 'default-app' for configuring Storybook.
```

Is it possible to set build configs for each storybook implementation, or point the builder to a specifically configure app within the monorepo?

**Comment by webberwang** [comment]
Couldn't you modify `workspace.json` `storybook.builder`?

**Comment by ChazUK** [comment]
@webberwang I'm using Angular, so I'm guessing you mean `angular.json` in the root.

my build config is 

```
"storybook": {
  "builder": "@nrwl/storybook:build",
  "options": {
    "uiFramework": "@storybook/angular",
    "outputPath": "dist/libs/ui/dist/storybook",
    "config": {
      "configFolder": "libs/ui/.storybook"
    }
  },
  "configurations": {
    "ci": {
      "quiet": true
    }
  }
},
```

From what I can tell there is no option to select a specific application to use as it's default config https://github.com/nrwl/nx/blob/master/packages/storybook/src/builders/build-storybook/schema.json

**Comment by wontondon** [comment]
Something is off about the way the `workspace.json` generated by nx is used with `@storybook/angular`. I have tracked it down and storybook is looking for a project to load its configuration by looking for a project called `storybook`, then the workspace/angular default, and finally falling back to the first project in the list. https://github.com/storybookjs/storybook/blob/v6.0.28/app/angular/src/server/angular-cli_config.ts#L63

Locally I skipped this logic and when you return null it loads the custom configuration that nx generated. In my env I was getting an error and storybook was working at all before I made these local changes.

**Comment by hiepxanh** [comment]
I belive this issues belong to this https://github.com/storybookjs/storybook/pull/12565

![image](https://user-images.githubusercontent.com/16970990/99362373-ffd98780-28e5-11eb-894c-119803ed5671.png)

currently it's 6.1.0-rc.4

**Comment by hiepxanh** [comment]
BTW PR is https://github.com/storybookjs/storybook/pull/12565

**Comment by hiepxanh** [comment]
It look like not really play nice with NX
https://github.com/storybookjs/storybook/pull/12565/files#diff-06da7c89bd3e3f47d96985acf2534485007ca1bb0225582f43f694a7862a6a70R73-R82
He is trying to use enviroment variable 
![image](https://user-images.githubusercontent.com/16970990/99362764-77a7b200-28e6-11eb-84ac-df60972e03db.png)

What is NX using to define the current project name sir? @vsavkin

**Comment by hiepxanh** [comment]
Awww, found this, creating my own enviroment variable match with that PR and voila 😄 
![image](https://user-images.githubusercontent.com/16970990/99365318-b3904680-28e9-11eb-9d8e-9947a1c3661f.png)

**Comment by bopm** [comment]
@vsavkin any news on this one? I just wasted a good hour on finding this one at all.

**Comment by hiepxanh** [comment]
I created PR but it still delay for a month
