### ISSUE TITLE
Storybook React: Missing class properties transform

### ISSUE THREAD

**Issue by Bielik20** [nrwl/nx#3657]
## Current Behavior

This component
```tsx
import React from 'react';

interface PaymentDropInState {
  clientToken?: string;
}

export class PaymentDropIn extends React.Component<{}, PaymentDropInState> {
  state = { clientToken: undefined };

  render() {
    return <h2>Loading...</h2>;
  }
}
```

Doesn't work with story
```tsx
import React from 'react';
import {PaymentDropIn} from './payment-drop-in';

export default {
  component: PaymentDropIn,
  title: 'PaymentDropIn',
};

export const Default = () => {
  return <PaymentDropIn />;
};
```

Problem relates to 
```tsx
  state = { clientToken: undefined };
```

I am getting "Missing class properties transform" error message.

Changing `.babelrc` of that project (lib) to:
```json
{
  "presets": ["@nrwl/react/babel"],
  "plugins": [
    ["styled-components", { "pure": true, "ssr": true }],
    "@babel/proposal-class-properties"
  ]
}
```
solves the issue.

It is worth noting that this component works ok when run outside of storybook.

## Expected Behavior

I would expect storybook to work properly with class properties.

## Steps to Reproduce

```
yarn add --dev @nrwl/storybook
nx g @nrwl/react:lib project-name
nx g @nrwl/react:storybook-configuration project-name
```

Create above components and run

```
nx run project-name:storybook
```

### Failure Logs

```
ERROR in ./libs/@payment/component/src/lib/payment-drop-in.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/damianbielecki/Projects/_private/braintree-react-express/libs/@payment/component/src/lib/payment-drop-in.tsx: Missing class properties transform.
   8 | 
   9 | export class PaymentDropIn extends React.Component<{}, PaymentDropInState> {
> 10 |   state = { clientToken: undefined };

```

### Environment

Node: `v12.13.1`

```
 nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.1.0
  @nrwl/cypress : 10.1.0
  @nrwl/eslint-plugin-nx : 10.1.0
  @nrwl/express : 10.1.0
  @nrwl/jest : 10.1.0
  @nrwl/linter : 10.1.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.1.0
  @nrwl/react : 10.1.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.1.0
  @nrwl/web : 10.1.0
  @nrwl/workspace : 10.1.0
  typescript : 3.9.7
```

**Comment by mandarini** [comment]
Hi @Bielik20 ! Thanks for filing an issue! 

I could successfully reproduce your issue, so good news there! And indeed the fix you proposed makes it work. Just a small note, however. The plugin is called [`@babel/plugin-proposal-class-properties`](https://babeljs.io/docs/en/babel-plugin-proposal-class-properties) (I guess it was a typo).

So, I changed my library's `.babelrc` file to this:
```
{
  "presets": [
    "@nrwl/react/babel"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties"
  ]
}
```
(I assume the addition of the `styled-components` was specific to your use case)

So, would you like to give it a try and try to fix this, and then create a PR? You can check out [this guide for contributing](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md). Let me know if you would like to do that, or I can take a look! :)

**Comment by Bielik20** [comment]
Hello, yeah that was a typo, but weirdly it works (perhaps it is an alias).

Well I could give it a try but I wonder where should it be fixed? Should generating storybook add that plugin or storybook builder should take that into the account? I am not that familiar with NX source code yet, but shouldn't storybook compilation be the same as the React one? I mean `.babelrc` in the library is also used by the react builder, and it clearly doesn't need that plugin, or am I missing something?

My other idea is that it may be resolved with https://github.com/nrwl/nx/pull/3434 as version 6 of storybook introduces native TypeScript support.

**Comment by mandarini** [comment]
Hi @Bielik20 ! I tried it with the current state of the Nx repo (which has the Storybook v6 support) and it seems to work, as you suggested! :) 

I'll close this issue now, but try it as well and let me know if the issue persists!
