### ISSUE TITLE
NX Config prevents ChakraUI from working?

### ISSUE THREAD

**Issue by JakeGinnivan** [nrwl/nx#3667]
## Current Behavior
After installing ChakraUI using instructions at https://next.chakra-ui.com/docs/getting-started the styles are broken. 

It may be related to #3620, but also maybe not. 

The issue the library theme props do not get transformed into css properties. For example 
<img width="287" alt="image" src="https://user-images.githubusercontent.com/453152/92299228-19c02b00-ef83-11ea-928a-f001b70549e4.png">

## Expected Behavior

I am new to NX, I would expect something which works out of the box with create-react-app and similar to work in NX.

My guess is there is some babel or webpack config which is stopping this from working. 

## Steps to Reproduce

Create a new workspace with a React project. Install Chakra UI, try to use it. The below repo you just need to clone and yarn start.

https://github.com/JakeGinnivan/nx-chakra-issue

I am happy to help debug further, I do not know how to see the effective babel/webpack config when using NX

### Environment

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.1.0
  @nrwl/cypress : 10.1.0
  @nrwl/eslint-plugin-nx : 10.1.0
  @nrwl/express : Not Found
  @nrwl/jest : 10.1.0
  @nrwl/linter : 10.1.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 10.1.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.1.0
  @nrwl/web : 10.1.0
  @nrwl/workspace : 10.1.0
  typescript : 3.9.7

**Comment by JakeGinnivan** [comment]
I tracked down the issue. https://github.com/chakra-ui/chakra-ui/issues/1719#issuecomment-675557345

It looks like because emotion is included by default then adding Chakra caused double ups in emotion. Fixing up my dependencies fixed the issue for me

**Comment by Nightbr** [comment]
Hey, I'm having the same issue, can you explain how you have fixed this? Thanks for your help :ok_hand:

**Comment by Nightbr** [comment]
Perhaps upgrading to emotion 11 #4088 can help this. So far I have upgraded manually but the builder needs the PR to be merged to make it work.

**Comment by JakeGinnivan** [comment]
NX adds an exact version of emotion into your package.json.
You basically need to ensure you don't have multiple versions of the same emotion packages in your lock file.
Other things which may be causing issues is storybook also depending on emotion or something else.

**Comment by Nightbr** [comment]
Yes, I have removed @emotion/* packages and reinstall them and it works now:

```json
    "@emotion/core": "^10.0.0",
    "@emotion/react": "^11.1.1",
    "@emotion/styled": "^11.0.0",
```

Thanks!

**Comment by JakeGinnivan** [comment]
@Nightbr I think you also want to remove `@emotion/core`, it has been removed in v11

**Comment by Nightbr** [comment]
Not yet, If I removed it I will get a build error because of #4088 not already merged. But yeah, I hope I can remove `@emotion/core` completely and use the latest emotion library with nx.

**Comment by Jezfx** [comment]
@JakeGinnivan we're running into the exact same issue. Don't suppose you've got a list of all the packages in your `package.json` file of the working repo? You'd be a live saver 🙏

**Comment by JakeGinnivan** [comment]
It's more about your lock file rather than the package.json
If you are using yarn you can run `yarn dedupe` or a similar command for your package manager
