### ISSUE TITLE
Error when trying to generate new lib

### ISSUE THREAD

**Issue by phsims** [nrwl/nx#367]
I am unable to generate anything new in my work space.  When I try to create a new lib I get the following error
```
Error: Unregistered task "node-package" in schematic "lib".
Unregistered task "node-package" in schematic "lib".
```
generating components results in the following
`Schematic "c" not found in collection "@nrwl/schematics".`

I have tried deleting and reinstalling everything but its not working and I cant find any similar errors when searching google

**Comment by jeffbcross** [comment]
Hi @phsims, can you give some more info about your environment?

 * Nx version
 * Angular CLI version (`ng -v`)
 * Windows, Mac, Linux

**Comment by praveenkumar-r** [comment]
This issue is coming for all generations .. for lib app component generations

-  Nx version **0.9.1**
- Angular CLI version **1.6.0**
- Windows

**Comment by frontr-uk** [comment]
sam here.

**Comment by phsims** [comment]
I think this was due to updates.  Apparently there has been some problem with the CLI and a new Jasmine update after rolling it back I the error went away

**Comment by xmlking** [comment]
```error
ng g component containers/graph --app=graph --dry-run
The "c" alias is already in use by the "--collection" option and cannot be used by the "--change-detection" option. Please use a different alias.
```
ng  v
```
Angular CLI: 1.7.3
Node: 9.10.1
OS: darwin x64
Angular: 6.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cdk: 6.0.0-rc.0
@angular/cli: 1.7.3
@angular/flex-layout: 5.0.0-beta.14
@angular/material-moment-adapter: 6.0.0-rc.0
@angular/material: 6.0.0-rc.0
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.4.8
@angular-devkit/schematics: 0.4.8
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.4.8
@schematics/package-update: 0.3.2
typescript: 2.7.2
webpack: 3.11.0
```

**Comment by Aaltuj** [comment]
@nrwl/nx": "0.11.1"
@nrwl/schematics": "0.11.1"

`> ng -v

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.7.1
Node: 8.9.4
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.1
@angular/tsc-wrapped: 4.4.6
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.4.6
@angular-devkit/schematics: 0.4.6
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.4.6
typescript: 2.6.2
webpack: 3.11.0`

**Comment by Aaltuj** [comment]
create a patch in my script to resolve the failing of the creation
```
function patchSchema() {
  const schemaPath = `${rootRepo}/node_modules/@schematics/angular/component/schema.json`;
  const exist = fs.existsSync(schemaPath);
  if (!exist)
    return;
  const content = fs.readFileSync(schemaPath, 'utf-8');

  const schemaFile = JSON.parse(content);
  schemaFile.properties.changeDetection.alias = 'cd';

  fs.writeFileSync(schemaPath, JSON.stringify(schemaFile));

}
```

**Comment by Riddlegun** [comment]
same issue
```
Angular CLI: 1.6.8
Node: 8.9.1
OS: linux x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 5.2.4
@angular/cli: 1.6.8
@angular/material-moment-adapter: 5.2.4
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.8.1
webpack: 3.10.0
```

**Comment by itache** [comment]
same issue
_                      _                 ____ _     ___
  / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
 / △ \ | '_ \ / _ `| | | | |/ _` | '__|   | |   | |    | |
/ ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
              |___/
   
Angular CLI: 1.6.8
Node: 9.4.0
OS: linux x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 5.2.4
@angular/cli: 1.6.8
@angular/material-moment-adapter: 5.2.4
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
typescript: 2.7.2
webpack: 3.10.0

**Comment by qrrock** [comment]
hi there!,

just try 

```
    yarn add @nrwl/nx@latest @nrwl/schematics@latest --exact
    yarn add @angular/cli@1.7.1
```

fixed issue for me 

finall:

```
    Angular CLI: 1.7.1
    Node: 8.9.4
    OS: linux x64
    Angular: 5.0.0-rc.3
    ... animations, common, compiler, compiler-cli, core, forms
    ... http, language-service, platform-browser
    ... platform-browser-dynamic, router

    @angular/cli: 1.7.1
    @angular-devkit/build-optimizer: 0.3.2
    @angular-devkit/core: 0.3.2
    @angular-devkit/schematics: 0.3.2
    @ngtools/json-schema: 1.2.0
    @ngtools/webpack: 1.10.1
    @schematics/angular: 0.3.2
    @schematics/package-update: 0.3.2
    typescript: 2.5.3
    webpack: 3.11.0
```

**Comment by phsims** [comment]
im on windows, package.json is below
{
  "name": "fusion-workspace",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "format": "prettier --single-quote --print-width 120 --write \"{apps,libs}/**/*.ts\""
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/core": "^0.5.7",
    "@angular/animations": "^5.2.6",
    "@angular/cdk": "^5.2.3",
    "@angular/common": "^5.2.6",
    "@angular/compiler": "^5.2.6",
    "@angular/core": "^5.2.6",
    "@angular/flex-layout": "^5.0.0-beta.14",
    "@angular/forms": "^5.2.6",
    "@angular/http": "^5.2.6",
    "@angular/material": "^5.2.3",
    "@angular/platform-browser": "^5.2.6",
    "@angular/platform-browser-dynamic": "^5.2.6",
    "@angular/router": "^5.2.6",
    "@dharapvj/ngx-signalr": "^3.0.0",
    "@ngrx/effects": "^5.1.0",
    "@ngrx/router-store": "^5.0.1",
    "@ngrx/store": "^5.1.0",
    "@ngrx/store-devtools": "^5.1.0",
    "@ngx-translate/core": "^10.0.1",
    "@ngx-translate/http-loader": "^3.0.1",
    "@nrwl/nx": "^1.0.0",
    "@types/pouchdb": "^6.3.2",
    "angular-oauth2-oidc": "^3.1.4",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.3",
    "hammerjs": "^2.0.8",
    "intl": "^1.2.5",
    "material-design-icons": "^3.0.1",
    "pouchdb": "^6.4.3",
    "rxjs": "^5.5.6",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "github:nrwl/fix-cli-build",
    "@angular/compiler-cli": "^5.2.6",
    "@angular/language-service": "5.2.10",
    "@nrwl/schematics": "^1.0.0",
    "@types/jasmine": "^2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~9.6.5",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~3.1.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.4.1",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^1.0.0",
    "prettier": "1.12.1",
    "protractor": "~5.3.0",
    "ts-node": "~6.0.0",
    "tslint": "~5.9.1",
    "typescript": "^2.4.2"
  }
}

**Comment by vsavkin** [comment]
CLI 1.6 doesn't have the node-package task. It was added in CLI 1.7.

Could you try it with Nx 1.0, which uses CLI 1.7?

**Comment by phsims** [comment]
thanks @vsavkin I have run the needed updates, I can generate libs now however I init.ts and interfaces.ts are not being created, looking at the examples readme I presume its because you are updating however Im also not getting selectors.ts or facade.ts

**Comment by manndave** [comment]
I'm seeing this error running CLI 1.7.1.  I don't know if it's related to this other problem I'm having or not: #455. 

Angular CLI: 1.7.1
Node: 8.9.4
OS: win32 x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

angular/cli: 1.7.1
angular-devkit/build-optimizer: 0.3.2
angular-devkit/core: 0.4.9
angular-devkit/schematics: 0.4.9
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.10.1
schematics/angular: 0.4.6
typescript: 2.6.2
webpack: 3.11.0

**Comment by FrozenPandaz** [comment]
Closing this issue as it seems to be working.

**Comment by dhananjayve** [comment]
Error while generating component
The "c" alias is already in use by the "--collection" option and cannot be used by the "--change-detection" option. Please use a different alias.
Please help me, I have tried changing aliases in node_modules\@schematics\angular\component\schema.json, but does not work

Angular CLI: 1.7.4
Node: 10.15.3
OS: win32 x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.7.4
@angular-devkit/architect: 0.13.7
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 7.3.7
@angular-devkit/schematics: 7.3.7
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 7.3.7
@schematics/package-update: 0.3.2
@schematics/update: 0.13.7
typescript: 2.5.3
webpack: 3.11.0
