### ISSUE TITLE
Cannot connect to remote cache

### ISSUE THREAD

**Issue by hardikpatel043** [nrwl/nx#3676]
I am trying to use nx cloud for my project which is build using nrwl workspace. I have followed instruction given below url to set up nx cloud workspace.

https://nx.app/orgs/workspace-setup

I completed the setup and tried to run 'nx build' command.

## Current Behavior
It gives me an error

>  NX   WARNING  Nx Cloud Problems

  - Cannot connect to remote cache (scope: api, code: ECONNABORTED).

## Expected Behavior
It should update the cache to my remote workspace.

https://nx.app/orgs/5f51ee2faaeff800054debcc/workspaces/5f520b59aaeff800054e06d5/report

## Steps to Reproduce
Here is my repo which I am using.
https://github.com/hardikpatel043/mf-app

I tried different ways to fix like deleting node_modules and did npm install again. I also tried to delete local nx cache.
It worked two-three times after this steps. But now it always gives me an error as above.

nx report

  nx : Not Found
  @nrwl/angular : 10.0.12
  @nrwl/cli : 10.0.12
  @nrwl/cypress : 10.0.12
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.0.12
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.12
  @nrwl/web : Not Found
  @nrwl/workspace : 10.0.12
  typescript : 3.9.7

**Comment by vsavkin** [comment]
Could you try again? We completely rewrote the implementation of the Nx Cloud backend and had a few issues with the new one.

**Comment by hardikpatel043** [comment]
@vsavkin  Its working seamless now. Thank you

**Comment by hckhanh** [comment]
@hardikpatel043 I got this issue again in my product:

```sh
 - Cannot connect to Nx Cloud (scope: api, code: ECONNABORTED). Try invo
king the command with the NX_CLOUD_NO_TIMEOUTS env variable set to 'true'
```

When I go to the nx.app to check my build, it cannot access for a while.
