### ISSUE TITLE
Need to add support for GraphQL (Code First) schema generation using @nrwl/node libraries

### ISSUE THREAD

**Issue by nbaua** [nrwl/nx#3679]
## Description
Trying to achieve the GraphQL code first schema generation using @nrwl/node libraries.
Say for example, we want to segregate all the entities in to separate  library of its own kind so that the same classes can be 
used across the projects and at the same time can be decorated with @ObjectType as well as @Entity decorators for graphql and typeorm to coexist.

However as these libraries will not be compiled into the respective js files per entity (or combined for that matter).

`autoSchemaFile: '/schema.gql',`
The above would result into the following error.
`GraphQLError [Object]: Query root type must be provided.`

as the following 
`import { AuthEntity } from '@nx-ws/shared/data-access';`

is the classes within the library are not treated same as the class, when they are under the same project.
Shouldn't there be a way to compile these entities prior to the other projects and entities be stitched to one `schema.gql` !!!

**Comment by vespertilian** [comment]
@nbaua I am using type graphql with NX. 

I store all my objects in a models library. Then I start my server and point the webstorm graphql tooling to a running graphql endpoint. It will then introspect the served schema and save a generated schema.graphql file in the root of the project which can give you autocomplete for the graphql queries in your editor. This should work for VS Code etc. 


graphql.config file: (which you can point to multiple schema endpoints I belive)
```graphql.config
  "name": "carabiner",
  "schemaPath": "schema.graphql",
  "extensions": {
    "endpoints": {
      "Default GraphQL Endpoint": {
        "url": "http://localhost:7777/api/graphql",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": true
      }
    }
  }
}

```

```schema.graphql
# This file was generated based on ".graphqlconfig". Do not edit manually.

schema {
  query: Query
  mutation: Mutation
}

type EventSubscription {
  email: String!
  eventNameSlug: String!
  success: Boolean!
}
...
```

**Comment by vespertilian** [comment]
Actually, while this works all works for the API when you try to import a decorated type from a lib into an angular app it will throw errors.  😧

So having this in a nx lib 

```ts
import { Field, ObjectType } from 'type-graphql';

@ObjectType()
export class EventSubscription {
  @Field()
  eventNameSlug: string

  @Field()
  email: string

  @Field()
  success: boolean
}
```

Will throw errors if you try to use this type in an Angular app.

**Comment by vespertilian** [comment]
Update:

So I think I got it working.

The `type-graphql` docs have instructions on how to disable the decorators when using the class as a type annotation in Angular. 

[type-graphql-ref](https://typegraphql.com/docs/0.16.0/browser-usage.html)

NX Issue [https://github.com/nrwl/nx/issues/1384](https://github.com/nrwl/nx/issues/1384)

webpack.config.js
```
const webpack = require('webpack')

module.exports = {
  plugins: [
    new webpack.NormalModuleReplacementPlugin(/type-graphql$/, resource => {
      resource.request = resource.request.replace(/type-graphql/, "type-graphql/dist/browser-shim");
    }),
  ]
};
```

Also

tsconfig.app.json
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "types": []
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts",
    "../../node_modules/type-graphql/dist/browser-shim.ts"
  ]
}
```

This is what I am going with for now. Another option I considered was to use [graphql-code-generator](https://github.com/dotansimha/graphql-code-generator) to re-generate just the types from the grapqhl schema.

**Comment by vespertilian** [comment]
Another update:

So while the above does work, I am now thinking that a more optimal approach might be to not import the decorated classes into the frontend apps. 

Instead, I think the best approach might be to use the decorated types for the API only, then follow [this guide](https://blog.nrwl.io/using-apollo-graphql-with-angular-in-an-nx-workspace-9ad0155c1914) to create a frontend data-access lib that re-generates the types from the generated `schema.graphql` file (created from introspecting the API endpoint) and the frontend graphql queries and mutations.

The advantage here is that you get all the API types and the frontend graphql queries and mutations and you don't have to mess around with the custom webpack config.

**Comment by nbaua** [comment]
> Update:
> 
> So I think I got it working.
> 
> The `type-graphql` docs have instructions on how to disable the decorators when using the class as a type annotation in Angular.
> 
> [type-graphql-ref](https://typegraphql.com/docs/0.16.0/browser-usage.html)
> 
> NX Issue #1384
> 
> webpack.config.js
> 
> ```
> const webpack = require('webpack')
> 
> module.exports = {
>   plugins: [
>     new webpack.NormalModuleReplacementPlugin(/type-graphql$/, resource => {
>       resource.request = resource.request.replace(/type-graphql/, "type-graphql/dist/browser-shim");
>     }),
>   ]
> };
> ```
> 
> Also
> 
> tsconfig.app.json
> 
> ```json
> {
>   "extends": "./tsconfig.json",
>   "compilerOptions": {
>     "outDir": "../../dist/out-tsc",
>     "types": []
>   },
>   "files": [
>     "src/main.ts",
>     "src/polyfills.ts",
>     "../../node_modules/type-graphql/dist/browser-shim.ts"
>   ]
> }
> ```
> 
> This is what I am going with for now. Another option I considered was to use [graphql-code-generator](https://github.com/dotansimha/graphql-code-generator) to re-generate just the types from the grapqhl schema.

Hi,
@vespertilian 

 I thought of the generator approach, however that wouldn't be optimal, making difficult to maintain when there is changes in tables/views. Also I want to execute the migrations while my team is working on the project. So we need to have the complete *code-first* support. 

For now we are stuck with the schema first approach as we need to meet the project deadlines. I am sure, it should be possible with some configuration changes and path configurations, somehow now able to figure it out. I am not allowed to talk the project much however planning to host a private repo which will replicate the issue. do let me know if you want to contribute, I will add you.

Thanks for participating on this thread, my apologies, I replied back with a delay, bit occupied with project deliverable.  

N Baua

**Comment by nbaua** [comment]
@vespertilian 

```

import { Field, ObjectType } from '@nestjs/graphql';
import { BaseEntity, Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

@ObjectType()
@Entity('user') //, { schema: 'DB_NAME_HERE' }
export class AuthEntity extends BaseEntity {
  @PrimaryGeneratedColumn({ type: 'int', name: 'id' })
  public id: number;

  @Field({ nullable: true })
  @Column('varchar', { name: 'username', nullable: true, length: 50 })
  public username: string | null;

  @Field({ nullable: true })
  @Column('varchar', { name: 'password', nullable: true, length: 255 })
  public password: string | null;

  @Field({ nullable: true })
  @Column('varchar', { name: 'email', nullable: true, length: 50 })
  public email: string | null;

  @Field({ nullable: true })
  @Column('tinyint', {
    name: 'isActive',
    nullable: true,
    width: 1,
    default: () => "'1'",
  })
  public isActive: boolean | null = false;

  @Column('datetime', {
    name: 'createdAt',
    nullable: true,
    default: () => 'CURRENT_TIMESTAMP',
  })
  public createdAt: Date | null;

  @Column('datetime', { name: 'updatedAt', nullable: true })
  public updatedAt: Date | null;
}

```

This is the way we are using an entity class in both TypeORM as well as GraphQL and works fine with schema first or code first approach in other projects where the project hierarchy is not the NRWL(NX) way. 

I can have the entities coupled this way deep in the server (API) project and can live happy. however I would love to have them loosely coupled as library and be usable in multiple projects.

As you can see with the Auth entity declared as above I can use it as many times as I want without having to change the structure. Hope we can solve this little mystery together. Thanks for your time.

**Comment by vespertilian** [comment]
@nbaua 

Having a library for the @ObjectType classes was almost working for me via the module replacement webpack config, the only issue I had was I could not seem to configure JEST with a similar module inclusion so all my tests started to break, I agree it would be really nice to be able to have this in a library. 

One way, less than ideal I was also thinking of was you could have a models folder and have all the graphql @ObjectTypes implement the classes from the model's folder.

I think we maybe need to create a test repo, to show the type-graphql team (I can ask about the jest config) and nx team we could maybe @ Philip Fulcher who wrote the original NX Graphql article and get his opinion.

**Comment by nbaua** [comment]
@vespertilian ,

Hi, 
Thanks for joining this discussion, I was bit busy this weekend, I would create a repo based on the project I am working on right now, just enough to simulate this issue. Will put the link here as well in a day.

I haven't communicated Philip Fulcher or other developers from the NX team anytime soon, it would be great if you handle this by endorsing this discussion with them. I will definitely take some time out today and push the code in a repository. Please check the thread sometime tomorrow if you can. Thanks again for your valuable time.

--- NBaua

**Comment by nbaua** [comment]
Hi Everyone,

Please feel free to clone the repository listed below to reproduce the issue:

https://github.com/nbaua/nx-gql-code-first-issue

To get the glimpse of the issue,  Just putting the output as I received from the same project.

```

[Nest] 6428   - 09/15/2020, 12:59:35 PM   [InstanceLoader] TypeOrmCoreModule dependencies initialized +13ms
(node:6428) UnhandledPromiseRejectionWarning: Error: No type definitions were found with the specified file name patterns: "./**/*.gql". Please make sure there is at least one file that matches the given patterns.
    at GraphQLTypesLoader.<anonymous> (H:\GitHub Projects\nx-gql-code-first-issue\node_modules\@nestjs\graphql\dist\graphql-types.loader.js:38:23)
    at Generator.next (<anonymous>)
    at fulfilled (H:\GitHub Projects\nx-gql-code-first-issue\node_modules\@nestjs\graphql\node_modules\tslib\tslib.js:111:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6428) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.        

```

I know at first glance, this is just appears as a incorrect path issue for graphql files is being reported here, however before coming to any conclusions just check the repository and this discussion thread as we are trying to solve this real hard.


Once again, the Problem statement

Use a NX library as a provider/helper for all the projects using graphql code first approach and also to support the typeorm as much as possible at the same time. The agenda here is at least my all api projects should rely on the same entities/schema classes. If Angular can use them ---nothing like that, and I guess it should be able to.


Thanks for your time.

N Baua

**Comment by vespertilian** [comment]
@nbaua I am still keen on this. Just a bit slammed currently, I plan to hopefully checkout your repo next week, thanks for creating it. Sorry for the delay.

**Comment by nbaua** [comment]
@vespertilian ,

That's alright, I can understand, we all have some real world projects to work on. Me also kind of tide up with something.
BTW, I tried changing (hard-coding) the compilerOptions - Path of out dir etc,last weekend, however still getting same/similar issue. Once I'll get some handful amount of bandwidth I'll jump on to it. 

Thanks for kicking back on this thread, it makes me feel alive.

-N Baua

**Comment by vespertilian** [comment]
Hey @nbaua 

Oh, how time flys, so I looked at your repo. 

So in my repo, I manually build my schema from the types, and I don't have issues importing them into my API library as that has type-graphql manually setup and it can process the decorators.

I think your issue might be more to do with Nest? Also, I still don't fully understand your error, I am not using nest. It all seemed to build for me. Weird? maybe something has changed? This thread is a little old.  I did get the error `No type definitions were found with the specified file name patterns: "./**/*.gql"`

My app looks like this I can import decorated objects from a library into my api.

```
  const schema = await buildSchema({
    resolvers: [
      TodoResolver,
      EmailResolver,
      ProgramResolver,
      ProgramCategoryResolver,
      SubscribeToProgramResolver,
      EventResolver
    ],
    container: Container,
    dateScalarMode: 'isoDate',
    scalarsMap: [ ]
  })
```

I have issues on the frontend when running my specs if I try to use the class as a type in the frontend, it wants to import the decorates. I was getting an error when building, but I don't seem to be getting that now... not sure if there was an update, I will have to investigate more. I still get errors when I run specs. Maybe it's a jest thing I am looking at swapping back to jasmine anyway as jest seems to be slow for angular.

```
  // angular component
   export class TodoComponent implements OnInit {
      foo: Todo
   }

    TypeError: Reflect.getMetadata is not a function

       5 | export class Todo {
       6 |   @Field(type => ID)
    >  7 |   id: ID_TYPE
         |   ^
       8 | 
       9 |   @Field()
      10 |   body: string

      at Object.findType (../../node_modules/type-graphql/dist/helpers/findType.js:9:35)
      at ../../node_modules/type-graphql/dist/decorators/Field.js:16:53
      at Object.__decorate (../../node_modules/tslib/tslib.js:97:114)
      at Object.<anonymous> (../../libs/models/src/lib/todo.ts:7:3)
      at Object.<anonymous> (../../libs/models/src/index.ts:8:1)
      at Object.<anonymous> (src/app/programs/start-program/start-program.component.ts:7:1)
      at Object.<anonymous> (src/app/programs/start-program/start-program.component.spec.ts:3:1)

```

Currently, I am just keeping all my GraphQL definitions in my API app and exporting the types into a data library and importing them from that library. Not ideal but it is working ok.

**Comment by nbaua** [comment]
Hi @vespertilian, 

_I am just keeping all my GraphQL definitions in my API app and exporting the types into a data library and importing them from that library._

Thought so, that was the only option left now, still a lot of work, also if there is change in the API app, we again have to do manual updates, which I am trying to avoid.

One more thing I would like to ask, can introspection on the gql files via a script (like running a grunt task or something) can help? Just asking in a thin air. I am not a fan of grunt though.

Regards,
N Baua

**Comment by vespertilian** [comment]
@nbaua 

Yeah it's not too much work if you follow [this guide](https://blog.nrwl.io/using-apollo-graphql-with-angular-in-an-nx-workspace-9ad0155c1914)

**Comment by nbaua** [comment]
@vespertilian ,

Haha,
I guess we both are thinkin in the same way, I went through that.
I guess for now we can use this approach, however I am keen to see how the NX team goes with this further.

Regards,
N Baua

**Comment by DaSchTour** [comment]
Is there any chance that there will be the possibility to use the [CLI Plugin](https://docs.nestjs.com/graphql/cli-plugin) together with NX?
I wonder why there is no possibility to add the configuration from the nest-cli.json to nx workspace.json

**Comment by nguyennhattan1398** [comment]
i got the same error, do you have any solution?

**Comment by nguyennhattan1398** [comment]
> Hey @nbaua
> 
> Oh, how time flys, so I looked at your repo.
> 
> So in my repo, I manually build my schema from the types, and I don't have issues importing them into my API library as that has type-graphql manually setup and it can process the decorators.
> 
> I think your issue might be more to do with Nest? Also, I still don't fully understand your error, I am not using nest. It all seemed to build for me. Weird? maybe something has changed? This thread is a little old. I did get the error `No type definitions were found with the specified file name patterns: "./**/*.gql"`
> 
> My app looks like this I can import decorated objects from a library into my api.
> 
> ```
>   const schema = await buildSchema({
>     resolvers: [
>       TodoResolver,
>       EmailResolver,
>       ProgramResolver,
>       ProgramCategoryResolver,
>       SubscribeToProgramResolver,
>       EventResolver
>     ],
>     container: Container,
>     dateScalarMode: 'isoDate',
>     scalarsMap: [ ]
>   })
> ```
> 
> I have issues on the frontend when running my specs if I try to use the class as a type in the frontend, it wants to import the decorates. I was getting an error when building, but I don't seem to be getting that now... not sure if there was an update, I will have to investigate more. I still get errors when I run specs. Maybe it's a jest thing I am looking at swapping back to jasmine anyway as jest seems to be slow for angular.
> 
> ```
>   // angular component
>    export class TodoComponent implements OnInit {
>       foo: Todo
>    }
> 
>     TypeError: Reflect.getMetadata is not a function
> 
>        5 | export class Todo {
>        6 |   @Field(type => ID)
>     >  7 |   id: ID_TYPE
>          |   ^
>        8 | 
>        9 |   @Field()
>       10 |   body: string
> 
>       at Object.findType (../../node_modules/type-graphql/dist/helpers/findType.js:9:35)
>       at ../../node_modules/type-graphql/dist/decorators/Field.js:16:53
>       at Object.__decorate (../../node_modules/tslib/tslib.js:97:114)
>       at Object.<anonymous> (../../libs/models/src/lib/todo.ts:7:3)
>       at Object.<anonymous> (../../libs/models/src/index.ts:8:1)
>       at Object.<anonymous> (src/app/programs/start-program/start-program.component.ts:7:1)
>       at Object.<anonymous> (src/app/programs/start-program/start-program.component.spec.ts:3:1)
> ```
> 
> Currently, I am just keeping all my GraphQL definitions in my API app and exporting the types into a data library and importing them from that library. Not ideal but it is working ok.

i got the same error, do you have any solution?

**Comment by vespertilian** [comment]
@nguyennhattan1398 

So I just use GraphQL code-gen to generate the types for my frontend, from my backend code. So they are separate projects and only linked when I rebuild the type definitions via GraphQL Codegen. 

Would have been nice to just use the classes directly but this works well enough for now. GraphQL Codegen also will generate types for your queries so you probably want it anyway. 

https://github.com/nrwl/nx-apollo-example
