### ISSUE TITLE
Affected builds should take angular.json content into account

### ISSUE THREAD

**Issue by pascalbe-dev** [nrwl/nx#3680]
AFAIK, the current behavior of the nx affected commands is, that it runs targets for all projects, which are affected. Affected means, that the project itself or any project on which it depends (or a dependent project depends) is changed. Furthermore, a project is considered as affected, when the angular.json (or workspace.json) or the package.json changes. 

This is great, but I think there are cases, where a project is considered as affected, although the changes, which occured do not really affect it. E.g., if a new project x was added to the angular.json, which is not at all related to a current project y. In that case, y is considered as affected. The same happens, if there are build target config changes for another project z. Also in that case, project x is considered as affected.

I guess, nx checks the files and if they changed. But in case of the angular.json, it would add some benefit, if nx could determine if a project x is really affected by a change to the angular.json file by analyzing the changes inside the angular.json file.
That would not require building all libs / apps, if someone adds a new library.

Please let me know, if there are technical reasons, why this is not implemented or if I missed something.

**Comment by pascalbe-dev** [comment]
I added this as question / discussion because I guess, I'm not the first one to think about that and there is probably a reason, why this is not implemented.

**Comment by pascalbe-dev** [comment]
@vsavkin @juristr
Any explanation or comment appreciated :)

**Comment by FrozenPandaz** [comment]
This is actually already a feature of nx though it is not enabled by default.

Remove the implicit dependencies for `workspace.json` or `angular.json` and this will magically happen :open_mouth:.

Caveat:

When a project is deleted, we do not have a "previous" state that we can use so at this time, we must assume that everything is affected. Think of this as we're checking that the project that was removed was not depended upon.

**Comment by pascalbe-dev** [comment]
Ah nice, didn't know that. Thanks for clarifying :)
