### ISSUE TITLE
Angular Schemtaics option skipTests block library generation

### ISSUE THREAD

**Issue by GonzoLiGGa** [nrwl/nx#3684]
execute command:
nx g @nrwl/angular:lib maps

## Current Behavior
Error "Path "/libs/maps/src/lib/maps.service.spec.ts" does not exist", library has not beend generated

## Expected Behavior
Library successfully created

## Steps to Reproduce
Version:
@angular-devkit/architect         0.803.23
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              8.3.23
@angular-devkit/schematics        8.3.23
@angular/cdk                      8.2.3
@angular/cdk-experimental         8.2.3
@angular/cli                      10.0.8
@ngtools/webpack                  10.0.8
@schematics/angular               8.3.23
@schematics/update                0.1000.8
rxjs                              6.6.2
typescript                        3.9.7
webpack                           4.39.2

Node 12.16.1
Angular 10.0.11

### Environment
Windows 10

**Comment by GonzoLiGGa** [comment]
I have found that problem is in angular.json configuration
```
  "schematics": {
    "@schematics/angular:component": {
      "changeDetection": "OnPush",
      "skipTests": true,
      "style": "scss"
    },
    "@schematics/angular:directive": {
      "skipTests": true
    },
    "@schematics/angular:pipe": {
      "skipTests": true
    },
    "@schematics/angular:service": {
      "skipTests": true
    }
  }
```
Looks like strange behaviour

**Comment by brandonroberts** [comment]
This has already been fixed in later versions of Nx. For a workaround with older versions, see here https://github.com/nrwl/nx/issues/3286
