### ISSUE TITLE
Add usage informations for Nx and create-nx-workspace

### ISSUE THREAD

**Issue by noelmace** [nrwl/nx#369]
Add an "help" command and/or --help option to the CLI tools in order to centralize documentation on them, like angular-cli.

I already starded to work on it ;)

## create-nx-workspace

add a `--help` option, giving an output like the one we would have with yargs

see https://github.com/nrwl/nx/pull/368

### feature request

`nx help [command` should result in an output looking like the one given by  `ng help [command]`.

### how (need feedback)

To begin with, I added an help.ts file in command-line, with the corresponding case on nx.ts command, which use the exported help function, generating the help message of the corresponding command (`nx help [command]`) or the list of commands, if there isn't any command provided.

Then, I followed a "minimal impact" approach :  make every command file (format.ts, affected.ts, etc ...) export an "help" constant which specify usage, description, sub-commands and options (following an Help interface, exported by shared.ts).

Having each description, list of subcommands and options, in the same file than the manipulation of the corresponding method, would, in my opinion, lead to a better readability than keeping all of them in the file help.ts.

But this "minimal impact" approach will have its limits. For now, I'm only considering the support of `nx help [command]`. Refactoring command-line files from functions to classes, following the [angular-cli "command" model](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/models/command.ts), could lead to a more flexible approach (and a more readable result), making it easier to support --help, -h and "nx command help".

### alternative

We could also : 
- support only `nx help` for the list of commands
- add an `help` sub-command to each command (example : `nx format help`)

**Comment by jeffbcross** [comment]
Seems like a reasonable approach to me! @vsavkin?

**Comment by noelmace** [comment]
Status update, in short :
* stuck a long time on #394 
* because of a misunderstanding on #408
* resolving this (with a refactoring or even by replacing yargs-parser by yargs instead) require to write a lot more unit and e2e tests on command-line
* this use case is not a priority (for me anyway), so, given the amount of work, I'll focus on #225 for now
* but I'll get back to it, mainly because I think more tests on command-line is a really important thing

Bonus : speaking of refactoring, did you thinked about angular-devkit architect ? I'm not familiar with it, but it seams a good solution for the command line.

**Comment by noelmace** [comment]
@mrmeku is addressing this issue in https://github.com/nrwl/nx/compare/help

**Comment by noelmace** [comment]
closed by https://github.com/nrwl/nx/pull/422
