### ISSUE TITLE
RFC: allow next.js configuration participation from builder

### ISSUE THREAD

**Issue by cdaringe** [nrwl/nx#3692]
## Description

When executing NX next.js builders, I want modify the next.js configuration. However, nx gives me no provisions to do so directly. Instead, nx/next simply loads config using next.js builtin functions. To modify my next.js config via a builder, I must mutate my env, e.g. `process.env.TURN_ON_FEATURE`, then sniff for such an env var in my next.config.js, because no programmatic exposure let's me tune the resultant next config programmatically. This amount of indirection is a bit of a code smell.

## Motivation

To allow us to participate in next.js configuration programatically

## Suggested Implementation

To solve this let's add an option to the `NextServeBuilderOptions`. Perhaps the API could be as follows:

`NextServeBuilderOptions["customizeNextConfigFilename"] = string` which maps to a function: `(nextConfig: NextConfig) => NextConfig`

## Alternate Implementations

Rather than allow for a `string` to a file, instead, just allow for a function directly on the `NextServeBuilderOptions`. This would mean that users would need to implement a custom builder to place such a function onto the options. Simpler, but doesn't allow usage out-of-the-box with nrwl/next builder

**Comment by jaysoo** [comment]
@cdaringe Thanks for opening the issue.

Are you able to update `next.config.js` for your app to customize the configuration?

For example, (if you need different config for build phase)

```
const { PHASE_PRODUCTION_BUILD } = require('next/constants');

module.exports = (phase, { defaultConfig }) => {
  if (phase === PHASE_PRODUCTION_BUILD) {
    console.log('PHASE_PRODUCTION_BUILD', defaultConfig);
    return {
      /* prod build options here */
    };
  }

  return {
    /* config options for all other  phases */
  };
};
```

Would that solve your issue? If not, can you explain?

**Comment by jaysoo** [comment]
I have a solution proposed here that should help with this issue.

https://github.com/nrwl/nx/pull/3782#issuecomment-698967729
