### ISSUE TITLE
@nrwl/workspace:move doesn't update .storybook import paths

### ISSUE THREAD

**Issue by webberwang** [nrwl/nx#3707]
## Current Behavior

`.storybook` import paths are not updated

## Expected Behavior
`.storybook/addon.js`
`.storybook/config.js`
`.storybook/webpack.config.js`

should update path

## Steps to Reproduce
Use `@nrwl/workspace:move` on a `@nrwl/react:library` + `@nrwl/react:storybook-configuration`, make sure the directory level is changed when moving

### Environment

nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.1.0
  @nrwl/cypress : 10.1.0
  @nrwl/eslint-plugin-nx : 10.1.0
  @nrwl/express : Not Found
  @nrwl/jest : 10.1.0
  @nrwl/linter : 10.1.0
  @nrwl/nest : 10.1.0
  @nrwl/next : 10.1.0
  @nrwl/node : 10.1.0
  @nrwl/react : 10.1.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.1.0
  @nrwl/web : 10.1.0
  @nrwl/workspace : 10.1.0
  typescript : 3.9.7

**Comment by mandarini** [comment]
Probably related/similar to [#3818](https://github.com/nrwl/nx/issues/3818)
