### ISSUE TITLE
Differential build for @nrwl/node:package

### ISSUE THREAD

**Issue by GrandSchtroumpf** [nrwl/nx#3728]
## Description
It would be nice to have a differential build for `@nrwl/node:package` like angular packagr with : 
- umd
- esm5
- esm2015

## Motivation
Currently when packaging a node library with CommonJS it creates a dependency to `tslib` (the built version requires `tslib`).
I don't think this is a good practice to include `tslib` into the dependencies. If we change the "module" in tsconfig, then there is no dependency on `tslib` but then apps that consume the library ends up with the error `unexpected token "export"`.
Also if the node library is supposed to be run on a browser, then commonjs is not supported.
With differential build the app consuming the library can take the best build for it.

## Suggested Implementation
On `@nrwl/node:package` creates multiple builds.

## Alternate Implementations
A first step could be to get rid of `tslib` in the built version, but I don't know what would be the impacts.

A very minimal step would be to add `tsconfig` in the dependencies of the `package.json` of the built library if it uses "commonjs" module.

**Comment by Qarun-Qadir-Bissoondial** [comment]
I'm having this exact problem. There seems to be a `@nrwl/node:build` builder but I've never used it before and I can't seem to find documentation on it to produce umd, esm5 or esm2015 bundles.

**Comment by nartc** [comment]
I would also love to be able to **NOT** produce commonjs bundles. Mainly because of this: https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77?gi=a9ab1a7d2ec9

**Comment by nartc** [comment]
Is there any update on this? `commonjs` also leads to non tree-shakable libs.
