### ISSUE TITLE
Builder: @nrwl/web schema validation fails when object is given as `styles` option

### ISSUE THREAD

**Issue by armanozak** [nrwl/nx#3730]
## Current Behavior

This (simplified workspace.json) works:

```json
{
  "projects": {
    "demo": {
      "architect": {
        "build": {
          "builder": "@nrwl/web:build",
          "options": {
            "styles": ["apps/demo/src/styles.less"]
          }
        }
      }
    }
  }     
}
```

This one doesn't:

```json
{
  "projects": {
    "demo": {
      "architect": {
        "build": {
          "builder": "@nrwl/web:build",
          "options": {
            "styles": [
              {
                "input": "apps/demo/src/styles.less",
                "inject": false,
                "bundleName": "styles"
              }
            ]
          }
        }
      }
    }
  }     
}
```

The schema validation fails and Nx stops building the project.

The interesting thing is, when I change [schema.json of builder](https://github.com/nrwl/nx/blob/master/packages/web/src/builders/build/schema.json) and make `styles` accept either string or an object as option, it works and creates the bundles as expected. Obviously, the current schema does not reflect the existing feature.

## Expected Behavior

A minified chunk called `styles.css` to be created and added to the bundle.

**I am planning to open a PR and introduce some changes:**

1. Add the following code from [Angular CLI config schema](https://github.com/angular/angular-cli/blob/master/packages/angular/cli/lib/config/schema.json) to [the end of the schema.json](https://github.com/nrwl/nx/blob/master/packages/web/src/builders/build/schema.json#L320)

```json
"extraEntryPoint": {
  "oneOf": [
    {
      "type": "object",
      "properties": {
        "input": {
          "type": "string",
          "description": "The file to include."
        },
        "bundleName": {
          "type": "string",
          "description": "The bundle name for this extra entry point."
        },
        "inject": {
          "type": "boolean",
          "description": "If the bundle will be referenced in the HTML file.",
          "default": true
        }
      },
      "additionalProperties": false,
      "required": [
        "input"
      ]
    },
    {
      "type": "string",
      "description": "The file to include."
    }
  ]
}
```

2. Change [styles schema](https://github.com/nrwl/nx/blob/master/packages/web/src/builders/build/schema.json#L105-L111) to the following:

```json
"styles": {
  "type": "array",
  "description": "External Styles which will be included with the application",
  "items": {
    "$ref": "#/definitions/extraEntryPoint"
  }
},
```

Please let me know if this looks good to you. ☝️

## Steps to Reproduce

- Run `yarn create nx-workspace demo` in terminal.
- Select "react" when "? What to create in the new workspace" is prompted.
- Enter an application name. (e.g. demo)
- Select a style format when "? Default stylesheet format" is prompted. (e.g. LESS)
- Change the workspace.json file as described above.
- Try building the app.

### Failure Logs
```bash
> nx run demo:build:production 
Schema validation failed with the following errors:
  Data path ".styles[0]" should be string.
error Command failed with exit code 1.
```

### Environment
```bash
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.2.0
  @nrwl/cypress : 10.2.0
  @nrwl/eslint-plugin-nx : 10.2.0
  @nrwl/express : Not Found
  @nrwl/jest : 10.2.0
  @nrwl/linter : 10.2.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 10.2.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.2.0
  @nrwl/web : 10.2.0
  @nrwl/workspace : 10.2.0
  typescript : 3.9.7
```

**Comment by Saegusae** [comment]
This is also a blocker for my company's product right now. We're currently utilizing gulp scripts to replicate the intended behavior of generating multiple controlled style chunks.

**Comment by armanozak** [comment]
Hi,

Any news on this issue?

Thanks.

**Comment by bekos** [comment]
@armanozak sorry for the delay. Are you interested in sending a PR or shall I take care of it?

**Comment by armanozak** [comment]
Hi @bekos,

No problem. I'll send a PR.
