### ISSUE TITLE
migration @nrwl/storybook:update-10.0.12 error

### ISSUE THREAD

**Issue by epikhighs** [nrwl/nx#3733]
## Current Behavior

when running migration to nx 10.2.0, the `@nrwl/storybook:update-10.0.12` fails b/c it's looking for a `tsconfig.lib.json` file

```
Could not read apps/ctv/tsconfig.lib.json.
```

but this is unexpected b/c it's looking for a `lib` tsconfig file in the `apps`.  

I took a look at the upgrade source code and in the tests, it's assuming a `tsconfig.lib.json` as well

```
// nx\packages\storybook\src\migrations\update-10-0-12\update-10-0-12.spec.ts
    expect(
      config.projects['home-ui-react'].architect.lint.options.tsConfig
    ).toEqual([
      'libs/home/ui-react/tsconfig.lib.json',
      'libs/home/ui-react/tsconfig.spec.json',
      'libs/home/ui-react/.storybook/tsconfig.json',
    ]);
```

## Expected Behavior

I would expect the migration script to look for a `tsconfig.app.json` file instead of a `tsconfig.lib.json` file in the `/apps` directory

## Steps to Reproduce

i just ran the standard migration command `nx migrate --run-migrations=migrations.json` with the standard migration settings

```
// migrations.json
{
  "migrations": [
    {
      "version": "10.0.12",
      "description": "Add missing storybook config to lint target",
      "factory": "./src/migrations/update-10-0-12/update-10-0-12",
      "package": "@nrwl/storybook",
      "name": "update-10.0.12"
    }

  ]
}
```

### Environment
windows 10 
```
➜  ✗ nx report
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 9.2.4
  @nrwl/cypress : 10.2.0
  @nrwl/eslint-plugin-nx : 10.2.0
  @nrwl/express : Not Found
  @nrwl/jest : 10.2.0
  @nrwl/linter : 10.2.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.2.0
  @nrwl/react : 10.2.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.4
  @nrwl/web : 10.2.0
  @nrwl/workspace : 10.2.0
  typescript : 3.9.7

```

**Comment by juristr** [comment]
@epikhighs hi, thanks for your bug report. Could you share a small GitHub repo that shows the problem? That would help me a ton to see whether my PR fixes your issue before we release it into the wild 😉 

thx a lot 🙇

**Comment by epikhighs** [comment]
@juristr hey do you still need the repo? I noticed the issue was closed and merged already.  Unfortunately, I don't have the time to setup a separate repo and I can't share my private repo (since it's for work).  I would think it's pretty simple to set one up to reproduce.  An nx repo with one react app and trying to update from prior nx version to the lastest.  If it can't be reproduced in that situation, then maybe this issue is specific to my repo :)
