### ISSUE TITLE
How to detect an angular component and module created with nx CLI ?

### ISSUE THREAD

**Issue by E-jarod** [nrwl/nx#3734]
I have used these commands : 
```
nx g @nrwl/angular:lib test
nx g @nrwl/angular:component test --project=test --export
```

That gives : 
`libs/test/src/lib/test.module.ts`
```ts
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TestComponent } from './test/test.component';

@NgModule({
  imports: [CommonModule],
  declarations: [TestComponent],
  exports: [TestComponent],
})
export class TestModule {}
```

`libs/test/src/lib/test/test.component.ts`
```ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'catalogue-ng-ui-test',
  templateUrl: './test.component.html',
  styleUrls: ['./test.component.scss']
})
export class TestComponent implements OnInit {
  constructor() { }

  ngOnInit(): void {
  }
}
```

`libs/test/src/index.ts`
```ts
export * from './lib/test.module';
```

`tsconfig.base.json`
```json
// ...
"@catalogue-ng-ui/test": ["libs/test/src/index.ts"]
// ...
```

But when I want to import `TestComponent` in : 
`libs/shared/util/src/lib/shared-util.module.ts`, `libs/shared/util/src/lib/request.util.ts` or `libs/shared/util/src/lib/ngb-date-moment-adapter.util.ts`
```ts
import { TestComponent } from './../../../../test/src/lib/test/test.component';
// this is working : 'TestComponent' is declared but its value is never read.

// OR

import { TestComponent } from '@repo-name/test';
// 'TestComponent' is declared but its value is never read.ts(6133)
// Module '"../../../../test/src"' has no exported member 'TestComponent'.
```
Or in an app (named `app-ui`) :
`apps/app-ui/src/app/app.module.ts`, `apps/app-ui/src/app/home/home.component.ts` or `apps/app-ui/src/app/home/home.module.ts`
```ts
import { TestComponent } from './../../../../libs/test/src/lib/test/test.component';
// this is working : 'TestComponent' is declared but its value is never read.ts(6133)


import { TestComponent } from '@repo-name/test';
// Cannot find module '@repo-name/test' or its corresponding type declarations.ts(2307)
``` 

I want to import it with the `@repo-name/test` path rather than a `../../../../` relative path.
Or, if possible, the module itself (test.module.ts) in the `app.module.ts` or `home.module.ts`.

I'm on Manjaro i3, with VS Code
```zsh
❯ nx report                                                 

>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : 10.0.7
  @nrwl/cli : 10.0.7
  @nrwl/cypress : 10.0.7
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.0.7
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.7
  @nrwl/web : Not Found
  @nrwl/workspace : 10.0.7
  typescript : 3.9.7
```

**Comment by bekos** [comment]
@E-jarod you can only import from other libraries, only what is exported  from library's public API which is defined in `libs/test/src/index.ts`. You can take a look also [here](https://nx.dev/angular/tutorial/08-create-libs). In this case you export only the module, not the `TestComponent`.  Closing as it is behaving as expected 😃

**Comment by E-jarod** [comment]
@bekos but even if I follow the doc, there is this message : 
![2020-09-15-143027_797x71_scrot](https://user-images.githubusercontent.com/57091681/93210510-0b7ec580-f760-11ea-81f1-eee946d81307.png)

**Comment by bekos** [comment]
@E-jarod sometimes VS code doesn't pick up these changes immediately. Try to reload it and see if it is fixed.

**Comment by E-jarod** [comment]
@bekos No, it is not fixed, I still have the same error message in the path `@repo-name/test`.

**Comment by bekos** [comment]
Can you please create a repository I can checkout and take a look?

**Comment by E-jarod** [comment]
@bekos a public repo ?

**Comment by E-jarod** [comment]
@bekos I have followed the doc, and everything works fine (https://github.com/E-jarod/myorg), but I don't understand why it doesn't work in my project.

**Comment by bekos** [comment]
@E-jarod Not sure I can help with that 😃 What you describe here is a heavily used feature, and would be very surprised if it was broken! Try to debug by replicating the steps in your project and you will probably find it out 🤞

**Comment by E-jarod** [comment]
@bekos okay thanks :+1:
