### ISSUE TITLE
ESLint: Error while loading rule '@nrwl/nx/enforce-module-boundaries': Unexpected token } in JSON at position 1839 Occurred while linting

### ISSUE THREAD

**Issue by jlabaj** [nrwl/nx#3735]
@nrwl/eslint-plugin-nx@10.2.0:
I am getting the following error when linting in VS code:
ESLint: Error while loading rule '@nrwl/nx/enforce-module-boundaries': Unexpected token } in JSON at position 1839 Occurred while linting
package.json:
...
"@nrwl/angular": "^10.2.0",
"@nrwl/eslint-plugin-nx": "^10.1.0",
"@nrwl/workspace": "^10.2.0",
...

**Comment by FrozenPandaz** [comment]
Hi, could you please provide a repo that we could take a look at if possible or the contents of your `package.json`?

**Comment by jlabaj** [comment]
> Hi, could you please provide a repo that we could take a look at if possible or the contents of your `package.json`?

my package.json:
{
  "name": "marmind",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "nx": "nx",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "tsc --noEmit && eslint . --ext js,ts,json --quiet --fix",
    "e2e": "ng e2e",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint": "nx affected:lint",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected": "nx affected",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "update": "ng update @nrwl/workspace",
    "workspace-schematic": "nx workspace-schematic",
    "dep-graph": "nx dep-graph",
    "help": "nx help",
    "postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^10.1.1",
    "@angular/common": "^10.1.1",
    "@angular/compiler": "^10.1.1",
    "@angular/core": "^10.1.1",
    "@angular/forms": "^10.1.1",
    "@angular/material": "^10.2.0",
    "@angular/platform-browser": "^10.1.1",
    "@angular/platform-browser-dynamic": "^10.1.1",
    "@angular/router": "^10.1.1",
    "@ngx-translate/core": "^13.0.0",
    "core-js": "^3.6.5",
    "tslib": "^2.0.0",
    "zone.js": "^0.11.1"
  },
  "devDependencies": {
    "@angular-architects/ddd": "^1.0.5",
    "@angular-devkit/build-angular": "~0.1001.1",
    "@angular-devkit/build-ng-packagr": "~0.1001.1",
    "@angular-eslint/builder": "0.3.0-beta.1",
    "@angular-eslint/eslint-plugin": "0.3.0-beta.1",
    "@angular-eslint/eslint-plugin-template": "0.3.0-beta.1",
    "@angular-eslint/template-parser": "0.3.0-beta.1",
    "@angular/cdk": "^10.2.0",
    "@angular/cli": "^10.1.1",
    "@angular/compiler-cli": "~10.1.1",
    "@angular/language-service": "^10.1.1",
    "@angular/upgrade": "^10.1.1",
    "@ng-select/ng-option-highlight": "0.0.5",
    "@ng-select/ng-select": "^5.0.1",
    "@ngrx/core": "^1.2.0",
    "@ngrx/data": "^10.0.0",
    "@ngrx/effects": "^10.0.0",
    "@ngrx/entity": "^10.0.0",
    "@ngrx/router-store": "^10.0.0",
    "@ngrx/schematics": "^10.0.0",
    "@ngrx/store": "^10.0.0",
    "@ngrx/store-devtools": "^10.0.0",
    "@nrwl/angular": "^10.2.0",
    "@nrwl/eslint-plugin-nx": "^10.1.0",
    "@nrwl/workspace": "^10.2.0",
    "@types/jasmine": "~3.5.14",
    "@types/jasminewd2": "~2.0.3",
    "@types/jquery": "^3.5.1",
    "@types/node": "~14.10.1",
    "@typescript-eslint/eslint-plugin": "^4.1.0",
    "@typescript-eslint/parser": "^4.1.0",
    "codelyzer": "~6.0.0",
    "cypress": "^5.1.0",
    "dotenv": "8.2.0",
    "eslint": "^7.8.1",
    "eslint-config-prettier": "^6.11.0",
    "eslint-import-resolver-typescript": "^2.3.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-sort-imports-es6-autofix": "^0.5.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "moment": "^2.27.0",
    "ng-packagr": "^10.1.0",
    "nx": "^10.2.0",
    "prettier": "^2.1.1",
    "protractor": "~7.0.0",
    "rxjs": "^6.6.3",
    "rxjs-compat": "^6.6.3",
    "ts-node": "~9.0.0",
    "tsickle": "^0.39.1",
    "tslib": "^2.0.0",
    "typescript": "^3.9.7"
  }
}

**Comment by mattietea** [comment]
Did you ever find a solution for this?

**Comment by jlabaj** [comment]
> Did you ever find a solution for this?

I did not fully test it yet but updating the node version probably helped, currently at 14.13.0 but 12.18.4  could also work

**Comment by Saafine** [comment]
I got this error when my angular.json was missing a comma somewhere. Make sure all your .json files are properly formatted.

**Comment by timbakkum** [comment]
I had a similar issue, and the error message didn't lead me anywhere useful. It turned out I had a trailing comma in my workspace.json that wasn't part of the files I was trying to lint. Check every JSON file that might be loaded by Nx during linting. Hope that helps.
