### ISSUE TITLE
Allow wildcard project matching for `nx run-many --projects=core-*`

### ISSUE THREAD

**Issue by webberwang** [nrwl/nx#3736]
## Description

Allow something like `nx run-many --target="lint" --projects="core-*"`

## Motivation

Sometimes you may want to lint a group of libraries under the same namespace or top-level directory.

For larger projects it may get unwieldy to have to specify each library explicitly

## Suggested Implementation

Parse using glob or regex to match projects

**Comment by ALFmachine** [comment]
this would be handy 👍
