### ISSUE TITLE
Storybook tsconfig does not allow jsx and synthetic default imports

### ISSUE THREAD

**Issue by iamandrewluca** [nrwl/nx#3741]
## Current Behavior
When using JSX into a storybook story, TypeScript reports errors

## Expected Behavior

I can use JSX in a story without errors.
This seems to be a regresion.

## Steps to Reproduce

https://github.com/iamandrewluca/test-nx-storybook/commits/main

- generate react workspace with `demo` app
- generate library `demo-lib`
- install nrwl storybook package
- generate storybook for `demo-lib`
- open file `libs/demo-lib/src/lib/demo-lib.stories.tsx`

### Failure Logs

```
/home/aluca/Temp/test-story/libs/demo-lib/src/lib/demo-lib.stories.tsx
Error:(1, 8) TS1259: Module '"/home/aluca/Temp/test-story/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
Error:(2, 39) TS6142: Module './demo-lib' was resolved to '/home/aluca/Temp/test-story/libs/demo-lib/src/lib/demo-lib.tsx', but '--jsx' is not set.
Error:(13, 10) TS17004: Cannot use JSX unless the '--jsx' flag is provided.
Information:File is not included in any tsconfig.json
```

### Environment

```
nx : Not Found
@nrwl/angular : Not Found
@nrwl/cli : 10.2.0
@nrwl/cypress : 10.2.0
@nrwl/eslint-plugin-nx : 10.2.0
@nrwl/express : Not Found
@nrwl/jest : 10.2.0
@nrwl/linter : 10.2.0
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/react : 10.2.0
@nrwl/schematics : Not Found
@nrwl/tao : 10.2.0
@nrwl/web : 10.2.0
@nrwl/workspace : 10.2.0
typescript : 3.9.7
```

### Possible solutions

I investigated and found for now 2 solutions.

- `Fix 1` https://github.com/iamandrewluca/test-nx-storybook/commit/76c8b28d16ae70cc9e84ee2a544e9af1b2dbb20f
- `Fix 2` https://github.com/iamandrewluca/test-nx-storybook/commit/c4665c3404e3b836db7ae69822be7f3480413df5

Have to mention that this happens when I introduce storybook for the first time in the project (at the time of writing this issue)
I have already a project that uses storybook, and `tsconfig.json` looks like in `Fix 2`, even after `nx update`

**History of tsconfig template file**

```
https://github.com/nrwl/nx/commits/master/packages/storybook/src/schematics/configuration/lib-files/.storybook/tsconfig.json
```

was renamed to

```
https://github.com/nrwl/nx/commits/master/packages/storybook/src/schematics/configuration/lib-files/.storybook/tsconfig.json__tmpl__
```

Pull Request that changed this behaviour https://github.com/nrwl/nx/pull/3056

**Comment by mandarini** [comment]
Hi there @iamandrewluca and thanks for filing an issue!

This issue should be fixed in [Nx 10.2.1](https://github.com/nrwl/nx/releases/tag/10.2.1). Check out [this commit here](https://github.com/nrwl/nx/commit/d34c3e6).

Can you try it out with the latest version of Nx (10.2.1) and please let me know if the issue persists!
