### ISSUE TITLE
@types/node typings not working

### ISSUE THREAD

**Issue by Ponjimon** [nrwl/nx#3743]
## Current Behavior
With nx 10, Node typings don't seem to work anymore.
![image](https://user-images.githubusercontent.com/770632/93367255-8de4b380-f84c-11ea-97b1-869a26ef41c3.png)

It's in the tsconfig (see nx-examples repo).

## Expected Behavior
It should support node typings, as it's installed in package.json and correctly added to tsconfig.

## Steps to Reproduce
Download the `nx-examples` repository and just add something that uses `process` or any other Node-typical const / variable / global.

### Environment
From `nx-examples`:

```
  @nrwl/angular : 10.0.6
  @nrwl/cli : 10.0.6
  @nrwl/cypress : 10.0.6
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.0.6
  @nrwl/linter : 10.0.6
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 10.0.6
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.6
  @nrwl/web : 10.0.6
  @nrwl/workspace : 10.0.6
  typescript : 3.9.7
```

If I downgrade to 9.x it works.

**Comment by Ponjimon** [comment]
Okay, so, apparently it's because the `tsconfig.lib.json` includes this:

```json
{
  "types": []
}
```

So the node typings are not included, even though they are in the `tsconfig.json`

**Comment by FrozenPandaz** [comment]
Hi @Ponjimon,

If you generate a `@nrwl/node:lib` then the `tsconfig.lib.json` should have the appropriate types for `node`.

I suspect you might have generated a `@nrwl/workspace` lib which does not have typings for `node` since it is not assumed t hat it will be consumed within `node`.

Where is that file and what kind of `lib` did you generate?

**Comment by Ponjimon** [comment]
All libs were created using `nx generate @nrwl/workspace:lib` and then I did nx migrate to upgrade to Nx 10
