### ISSUE TITLE
Builder from custom plugin is not compiled when used in the app

### ISSUE THREAD

**Issue by vpalam-om** [nrwl/nx#3752]
I want to create a custom builder which would allow me to create Docker containers.
I started with the default builder generate with `nx g @nrwl/nx-plugin:plugin my-plugin--importPath=@my-project/my-path`.
After that I added corresponding option for `my-app` to the `workspace.json`:
`
"deploy": {
  "builder": "./libs/my-plugin:build"
}`
When I run `nx deploy my-app` I receive the error `Cannot find module <path-to-builder>`. My current workaround it to build plugin first and specify the path to the compiled plugin, but I believe this behavior is not obvious.

## Current Behavior
Source code of custom plugin cannot be used, the compiled path has to be specified.

## Expected Behavior
Source code of custom plugin can be used.

## Steps to Reproduce
- Create a React app.
- Create a custom plugin.
- Use builder from custom plugin in the app.

### Failure Logs
```
Cannot find module 'path/to/builder'
Require stack:
- ...\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- ...\node_modules\@angular-devkit\architect\node\index.js
- ...\node_modules\@nrwl\tao\src\commands\run.js
- ...\node_modules\@nrwl\tao\index.js
- ...\node_modules\@nrwl\cli\lib\run-cli.js
```

### Environment
```
PS D:\Projects\molequle> nx report

>  NX  Report complete - copy this into the issue template

  @nrwl/angular : Not Found
  @nrwl/cli : 10.0.6
  @nrwl/cypress : 10.0.6
  @nrwl/eslint-plugin-nx : 10.0.6
  @nrwl/express : Not Found
  @nrwl/jest : 10.0.6
  @nrwl/linter : 10.0.6
  @nrwl/nest : Not Found
  @nrwl/next : 10.0.6
  @nrwl/node : 10.0.6
  @nrwl/react : 10.0.6
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.6
  @nrwl/web : 10.0.6
  @nrwl/workspace : 10.0.6
  typescript : 3.9.7
```

**Comment by Cammisuli** [comment]
I'm changing this from a bug to a feature, as this wasn't the intention of plugins. 

For a workaround, you have to build the project first with the build command. And then do the deploy. You can chain together multiple command with the `@nrwl/workspace:run-commands` builder. https://nx.dev/angular/plugins/workspace/builders/run-commands
