### ISSUE TITLE
upgrade TS version

### ISSUE THREAD

**Issue by sanyashvets** [nrwl/nx#377]
Greetings. Now we have TS version `^2.8.1`, but I cant generate new app with this version. I just getting an empty error and nothing happens
```
alex@alex:~/Documents/tests/test-workspace$ ng g app testy2
Error: 
alex@alex:~/Documents/tests/test-workspace$ 
```
Same situation with `2.7.2` TS version installed. Can you add support of new TS versions, please?

Versions:
```
Angular CLI: 1.7.3
Node: 9.9.0
OS: linux x64
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.7.2 / 2.8.1
webpack: 3.11.0

```

**Comment by jeffbcross** [comment]
We stay aligned with angular/angular TypeScript versions. As of latest stable release, the range is `>=2.4.2 <2.7`: https://github.com/angular/angular/blob/5298b2bda34a8766b28c8425e447f94598b23901/packages/compiler-cli/package.json#L18

Angular v6 will support `>=2.7.2 <2.8`: https://github.com/angular/angular/blob/master/packages/compiler-cli/package.json

Chances are the issue you're seeing isn't related to Nx, but is schematics-related.
