### ISSUE TITLE
Cant create workspace

### ISSUE THREAD

**Issue by hagamitu** [nrwl/nx#3778]
## Current Behavior
When trying to create a new workspace I get an error and the workspace is not created

## Expected Behavior
The workspace will be created

## Steps to Reproduce
just run:
npx create-nx-workspace@latest

### Failure Logs
npx: installed 179 in 11.943s
? Workspace name (e.g., org name)     testnrwl
? What to create in the new workspace angular           [a workspace with a single Angular application]
? Application name                    app
? Default stylesheet format           CSS
? Use Nx Cloud? (It's free and doesn't require registration.) No
Creating a sandbox with Nx...
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 5.97s
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0.6s
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0.36s
➤ YN0000: Done in 6.94s
new testnrwl  --preset="angular" --appName="app" --style="css" --interactive=false --collection=@nrwl/workspace
(node:83113) UnhandledPromiseRejectionWarning: Error: Cannot find module '@nrwl/workspace/collection.json'
Require stack:
- /Users/haimagami-turjeman/.npm/_npx/83113/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.resolve (internal/modules/cjs/helpers.js:83:19)
    at createApp (/Users/haimagami-turjeman/.npm/_npx/83113/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:376:40)
    at /Users/haimagami-turjeman/.npm/_npx/83113/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:91:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:83113) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:83113) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Environment
node 12.6.3
nx cli is not installed globally
was working for me in <10 nx version

**Comment by vsavkin** [comment]
@hagamitu Do you still see the same issue with Nx 10.3.1?
