### ISSUE TITLE
How to add @angular/fire?

### ISSUE THREAD

**Issue by curiouscod3** [nrwl/nx#3779]
I'm stuck in installing 'ng add XXX'
for example, https://github.com/angular/angularfire 

```
The add command requires to be run in an Angular project, but a project definition could not be found.
```

NX recoomends to use NX-CLI  not Angular CLI for working with other frameworks.

Okay..then What should I do to use 'ng add'  Material, Firebase and so on..
Most of top library packages only support "ng add" schematics way recently..
Of course, there are ways to manually install but they started to get rid of manual install documentation because of 'ng add' popularity.

so, NX CLI should support 'nx add'  because there is no angular.cli but workspace.json,

**Comment by troywweber7** [comment]
I have the same question for `@angular/material`. I've also submitted an issue with `@angular/material` to see if there is a way to get support in Nx be creating a generate schematic alias for the `ng add` schematic logic: https://github.com/angular/components/issues/20675

**Comment by samudiogo** [comment]
Hi folks, 
I will take the angular material as an example of how to deal with ng add in NX workspace:

**Add @angular/material using yarn or npm:**

`yarn add @angular/material`

Now, let's take the advantage of `nx list @angular/material`. This fabulous command shows us all possibility of usage of @angular/material:
![image](https://user-images.githubusercontent.com/4693486/103111926-7ded2480-4630-11eb-973d-4dac958d9348.png)
now let's add in our angular project:

`nx g  @angular/material:ng-add`

That's all folks! Simple as that!

**Comment by hadrien-toma** [comment]
Tank you @samudiogo, it works on my side, additionnaly, here is the associated help (of course, it is possible to specify the project):

```
yarn run nx generate @angular/material:ng-add --help
yarn run v1.21.1
$ nx generate @angular/material:ng-add --help

nx generate @angular/material:ng-add [options,...]

Options:
  --project               Name of the project.
  --theme                 The theme to apply (default: indigo-pink)
  --typography            Whether to set up global typography styles.
  --animations            Whether Angular browser animations should be set up. (default: true)
  --dryRun                Runs through and reports activity without writing to disk.
  --skip-nx-cache         Skip the use of Nx cache.
  --help                  Show available options for project target.
  
Done in 1.34s.
```

**Comment by dianjuar** [comment]
@edbzn and I are working to make the builder `ngx-deploy-npm` [compatible with an Nx Workspace](https://github.com/bikecoders/ngx-deploy-npm/pull/40) and we were facing some difficulties with the ng-add.

I follow the instructions that you put here taking as an example `@angular/material` with the same error output.

`npx nx list ngx-deploy-npm`
![image](https://user-images.githubusercontent.com/7026066/107181156-1c3e0b00-698f-11eb-8e29-07e1de3de058.png)

And then `npx nx generate ngx-deploy-npm:ng-add` but an error is triggered bringing almost no information

```
Unable to resolve ngx-deploy-npm:ng-add.
EISDIR: illegal operation on a directory, read
```
![image](https://user-images.githubusercontent.com/7026066/107181241-4263ab00-698f-11eb-8ec5-c3254d27101f.png).

Super strange for me because on an Angular workspace everything was running perfectly. 


# Solution
I found that the problem was on npm and there are [multiple reasons](https://www.xspdf.com/resolution/50628837.html) of why you are getting the error and our case was basically that `nx` was trying to read a file that didn't exists.

The case was that the builder didn't have `schema` property in its `collection.json` 😅. I just added and work perfectly.

![image](https://user-images.githubusercontent.com/7026066/107188820-31ba3180-699d-11eb-84b9-81b0570ae5da.png)

**Comment by dianjuar** [comment]
Don't forget that you can use the parameter `--verbose` to try to get more info

**Comment by ohabash** [comment]
where is `collection.json`?


> @edbzn and I are working to make the builder `ngx-deploy-npm` [compatible with an Nx Workspace](https://github.com/bikecoders/ngx-deploy-npm/pull/40) and we were facing some difficulties with the ng-add.
> 
> I follow the instructions that you put here taking as an example `@angular/material` with the same error output.
> 
> `npx nx list ngx-deploy-npm`
> ![image](https://user-images.githubusercontent.com/7026066/107181156-1c3e0b00-698f-11eb-8e29-07e1de3de058.png)
> 
> And then `npx nx generate ngx-deploy-npm:ng-add` but an error is triggered bringing almost no information
> 
> ```
> Unable to resolve ngx-deploy-npm:ng-add.
> EISDIR: illegal operation on a directory, read
> ```
> 
> ![image](https://user-images.githubusercontent.com/7026066/107181241-4263ab00-698f-11eb-8ec5-c3254d27101f.png).
> 
> Super strange for me because on an Angular workspace everything was running perfectly.
> 
> # Solution
> I found that the problem was on npm and there are [multiple reasons](https://www.xspdf.com/resolution/50628837.html) of why you are getting the error and our case was basically that `nx` was trying to read a file that didn't exists.
> 
> The case was that the builder didn't have `schema` property in its `collection.json` 😅. I just added and work perfectly.
> 
> ![image](https://user-images.githubusercontent.com/7026066/107188820-31ba3180-699d-11eb-84b9-81b0570ae5da.png)

**Comment by Radecom** [comment]
Please, @dianjuar, could you explain more in detail how to add the schema?
Do you mean the schema ng-add-schema.json?
Would you be so kind as to show us an example, please?

**Comment by dianjuar** [comment]
Ok, I will clarify some stuff first to see if we are looking for a solution for the same problem.

I had a problem executing the `ng add`  to an Nx workspace. All the info [here](https://github.com/nrwl/nx/issues/3779#issuecomment-751136586) and [here](https://github.com/nrwl/nx/issues/3779#issuecomment-751484143) helped me out to know what was the way.

Even though, I was experimenting with failures trying to do `ng add` for an **Nx plugin that I was building**. So I put the solution the help person in the future that came across with the same problem as me.

---

The solution consists of adding in the `collection.json` file of the Nx plugin the property `schema` on the section `ng-add`. That property `schema` just points out to a [file](https://github.com/bikecoders/ngx-deploy-npm/blob/master/src/ng-add-schema.json) that it's going to define the options of your plugin's ng-add.

[This is the PR](https://github.com/bikecoders/ngx-deploy-npm/pull/43/files) where I solve that specific problem for my Nx Plugin that was facing failures on the ng-add.

**Comment by zergeborg** [comment]
I keep receiving the following error:
```
Unable to resolve @angular-architects/module-federation:ng-add.
PropertyNameExpected in JSON at position 835
```

When I run the following command:
```
nx g @angular-architects/module-federation:ng-add
```

FYI I already ran:
```
npm add @angular-architects/module-federation
```
and
```
nx list @angular-architects/module-federation
```
Which both worked fine.

So maybe the workaround is not generally applicable to all Angular plugins? Could someone reopen this bug ticket please? Or alternatively I can open a new bug report, although the content would be identical to this one.

Also, I don't think it's reasonable that the whole world would rewrite all their Angular plugins to make them nx compatible. IMO it should be the other way around, nx should work hard to make sure it works with all Angular plugins out of the box.
