### ISSUE TITLE
tsconfig.app.json is skipped and "include" "files" settings are ignored

### ISSUE THREAD

**Issue by asherccohen** [nrwl/nx#3784]
## Current Behavior
In my apps\myApp\tsconfig.app.json i set "files" to include a specific node_modules/baseui/theme.ts file so the ts-loader would take into consideration but this is skipped and I get an error:

`
ERROR in rootDir/node_modules/baseui/theme.ts 1:0
Module parse failed: The keyword 'interface' is reserved (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
`

## Expected Behavior
When I set "files" or "include" in my tsconfig.app.json it should not be ignored.

## Steps to Reproduce
- create a workspace
- create a lib based on https://baseweb.design/
- import the theme type somewhere
- create an app
- import anything that uses the theme type
- yarn start myApp

## Context

- original tsconfig.base.json is untouched so node_modules are excluded:
`
  "exclude": ["node_modules", "tmp"]
`
- paths are set correctly 

Can someone explain to me why the specific tsconfig files are ignored, as this is not the only example I had where setting anything inside them would be taken into consideration for building/serving apps or libs.

**Comment by webberwang** [comment]
What schematic are you running for the lib?

**Comment by asherccohen** [comment]
Tx @webberwang for your question.

I am running it with the "@nrwl/react:lib".

**Comment by ZackDeRose** [comment]
Hi @asherccohen - I've attempted to reproduce this issue in this repo: https://github.com/ZackDeRose/tsconfig-app-skipped-3784

Following the steps left, I don't seem to be able to reproduce the the issue as stated, so I'll be closing this ticket.

Please feel free to reopen with an explanation on where my reproduction attempt was lacking if you feel this is still an issue!
