### ISSUE TITLE
extraGlobals in react rollup config being merged with output instead of output.globals

### ISSUE THREAD

**Issue by benatkin** [nrwl/nx#3789]
## Current Behavior

It has this message: `No name was provided for external module 'react' in output.globals – guessing 'React'`

...despite `react: 'React'` being in [rollup.config.js](https://github.com/nrwl/nx/blob/master/packages/react/plugins/bundle-rollup.ts#L5)

Also upon logging the output the extraGlobals aren't inside `output.globals` but are merged with `output`. This [doesn't appear to match rollup's docs](https://rollupjs.org/guide/en/). Here's the output:

``` js
{
  globals: {},
  format: 'umd',
  file: '/Users/bat/projects/resources/resources/dist/packages/vtv/vtv.umd.js',
  name: 'Vtv',
  react: 'React',
  'react-dom': 'ReactDOM',
  'styled-components': 'styled',
  '@emotion/core': 'emotionCore',
  '@emotion/styled': 'emotionStyled'
}
```

It appears [line 18 in bundle-rollup.ts](https://github.com/nrwl/nx/blob/master/packages/react/plugins/bundle-rollup.ts#L18) should be this:

```
      globals: {...options.output.globals, ...extraGlobals},
```

instead of this:

```
      ...extraGlobals,
```

## Expected Behavior

I think it should look like this:

``` js
{
  globals: {},
  format: 'umd',
  file: '/Users/bat/projects/resources/resources/dist/packages/vtv/vtv.umd.js',
  name: 'Vtv',
  globals: {
    react: 'React',
    'react-dom': 'ReactDOM',
    'styled-components': 'styled',
    '@emotion/core': 'emotionCore',
    '@emotion/styled': 'emotionStyled'
  }
}
```

## Steps to Reproduce

Create a buildable react library and build it. Copy `bundle.rollup.ts` to `bundle.rollup.js` and update the path of bundle.rollup.ts in your library and log the output. Here's mine:

``` js
const rollup = require('rollup')

function getRollupOptions(options) {
  const extraGlobals = {
    react: 'React',
    'react-dom': 'ReactDOM',
    'styled-components': 'styled',
    '@emotion/core': 'emotionCore',
    '@emotion/styled': 'emotionStyled',
  };
  console.log({output: options.output})
  if (Array.isArray(options.output)) {
    options.output.forEach((o) => {
      o.globals = { ...o.globals, ...extraGlobals };
    });
  } else {
    options.output = {
      ...options.output,
      ...extraGlobals,
    };
  }
  console.log({outputAfterChange: options.output})
  return options;
}

module.exports = getRollupOptions;
```

I modified `build.options.rollupConfig` in my library in `workspace.json` to be `packages/vtv/bundle-rollup` and put the file in `packages/vtv/bundle-rollup.js`

### Failure Logs

```
Bundling...
Entry module "packages/vtv/src/index.ts" is using named and default exports together. Consumers of your bundle will have to use `Vtv["default"]` to access the default export, which may not be what you want. Use `output.exports: "named"` to disable this warning
No name was provided for external module 'react' in output.globals – guessing 'React'
No name was provided for external module 'vtv-model' in output.globals – guessing 'vtvModel'
*snip*
Bundle complete.

>  NX   CLOUD  See run details at https://nx.app/runs/SMqrawwLS9b


~/projects/resources/resources work-on-vtv* 34s
❯

~/projects/resources/resources work-on-vtv*
❯ nx build vtv

> nx run vtv:build
{
  output: {
    globals: {},
    format: 'umd',
    file: '/Users/bat/projects/resources/resources/dist/packages/vtv/vtv.umd.js',
    name: 'Vtv'
  }
}
{
  outputAfterChange: {
    globals: {},
    format: 'umd',
    file: '/Users/bat/projects/resources/resources/dist/packages/vtv/vtv.umd.js',
    name: 'Vtv',
    react: 'React',
    'react-dom': 'ReactDOM',
    'styled-components': 'styled',
    '@emotion/core': 'emotionCore',
    '@emotion/styled': 'emotionStyled'
  }
}
```

### Environment

```
>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.2.0
  @nrwl/cypress : 10.2.0
  @nrwl/eslint-plugin-nx : 10.2.0
  @nrwl/express : Not Found
  @nrwl/jest : 10.2.0
  @nrwl/linter : 10.2.0
  @nrwl/nest : Not Found
  @nrwl/next : 10.2.0
  @nrwl/node : 10.2.0
  @nrwl/react : 10.2.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.2.0
  @nrwl/web : 10.2.0
  @nrwl/workspace : 10.2.0
  typescript : 4.0.3
```

**Comment by jliebrand** [comment]
I just stumbled on this as well, while debugging a potentially related problem (my external modules are not being built/bundled in to my buildable lib since 10.x... related?)

Just wondering if anyone is looking at this, since line 18 is clearly wrong

**Comment by tanepiper** [comment]
I have this in a non-react library, [RxJS Ninja](https://github.com/rxjs-ninja/rxjs-ninja)

![image](https://user-images.githubusercontent.com/376930/100011168-a2f03c80-2dd1-11eb-865a-58198489da6c.png)

With RxJS, they put their globals on `rxjs` and `rxjs.operators`, but with the build it puts the `operators` on the global, so I have to do a small shim in place to get it to work correctly with my library. I've tried adding a `rollup.config.js` but no luck

```
<script src="https://unpkg.com/rxjs/bundles/rxjs.umd.min.js"></script>
<script>
    window.operators = rxjs.operators;
</script>
<script src="https://unpkg.com/@rxjs-ninja/rxjs-random@1.1.1/rxjs-random.umd.js"></script>

<script module>
    const { tap } = rxjs.operators;
    const { fromRandom } = RxjsRandom;
    fromRandom(0, 1, 1000).pipe(tap(console.log)).subscribe()
</script>
```

This repo is customised using `@nrwl/node` to create the libraries and `@nrlw/web` babel to compile the UMD and ESM version instead.

On top of that I can't see a way to add back commonjs builds
