### ISSUE TITLE
If NX.json contains not existing project, TSLint crashing entire TypescriptServer

### ISSUE THREAD

**Issue by montella1507** [nrwl/nx#3792]
"@nrwl/angular": "^10.0.4",
Angular CLI: 10.0.3
Node: 12.18.0      
OS: win32 x64      

Angular: 10.0.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.3
@angular-devkit/build-angular      0.1000.3
@angular-devkit/build-ng-packagr   0.1000.3
@angular-devkit/build-optimizer    0.1000.3
@angular-devkit/build-webpack      0.1000.3
@angular-devkit/core               10.0.3
@angular-devkit/schematics         10.0.5
@angular/cdk                       10.0.2
@angular/cli                       10.0.3
@ngtools/webpack                   10.0.3
@schematics/angular                10.0.3
@schematics/update                 0.1000.3
ng-packagr                         5.7.1
rxjs                               6.5.2
typescript                         3.9.7
webpack                            4.43.0

If Nx.json contains project that doesnt exist in Angular.json it crashes via TSLint entire typescript server and it is hard to debug.

**Comment by FrozenPandaz** [comment]
Please provide a repro that we can pull down so that we can investigate the issue. There are checks in place that `nx.json` is in sync with `angular.json`. Are you running `tslint` directly perhaps?
