### ISSUE TITLE
@nrwl/workspace - library cannot be made publishable or at least buildable

### ISSUE THREAD

**Issue by maxime1992** [nrwl/nx#3797]
## Current Behavior

I did encounter this issue earlier today: https://github.com/nrwl/nx/issues/3795

It made me think about the fact that I was probably doing something wrong by having setup some of my shared libs as angular libs (as they were only used in angular projects) but could later on be used by node projects as well.

Therefore, I think I'm going to go ahead and transform those into `@nrwl/workspace - library` instead of a `@nrwl/angular - library`. The only thing that is stopping me right now is that I'd have to make that change on quite a few of them and we use the `--with-deps` flag to build our app so all of our libraries have been made buildable.

Unfortunately, the buildable flag seems to have been made available on all kind of libs **except** for the  `@nrwl/workspace - library`. Is this by design? Is there anything I'm missing? Or is this a bug?

What should I do?

## Expected Behavior

Either being able to import angular libs on a nest app (not the best scenario) or make `@nrwl/workspace - library` buildable?

## Steps to Reproduce

Use nx console and notice that there is no buildable or publishable flag for `@nrwl/workspace - library` but there is one for the others.

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by juristr** [comment]
Hey @maxime1992 👋 

Yeah we probably should do a better job do document / adjust these different libraries (we have lots of them by now 😅 ). `@nrwl/workspace` libraries are useful if you just want some plain TS library. Like if you want to share code between node / react / angular.

You're right. At the moment they're not publishable / buildable and we're currently overhauling that whole publishable/buildable experience in general. 

So the best way at the moment if you want a "neutral" publishable library is to use the `@nrwl/node` package and generate one using the `--publishable --importPath...` flags.

**Comment by juristr** [comment]
> The only thing that is stopping me right now is that I'd have to make that change on quite a few of them and we use the --with-deps flag to build our app so all of our libraries have been made buildable.

Just out of curiosity. Are you using `--with-deps` to have incremental building or for some other reason?

**Comment by maxime1992** [comment]
@juristr thanks for the reply. I guess I'll go with the node builder then.

> Just out of curiosity. Are you using --with-deps + buildable libs to have incremental building or for some other reason?

Yes, for incremental building but I'm thinking of removing it actually. I've noticed that since I've set that up I've lost the ability to run the `affected` command properly :warning: Is this something by design or maybe a bug?

Lint, build and test commands can't run anymore on only just what's needed unless I remove the `--with-deps`.  
Should I raise a bug for that or is it normal :thinking:?

**Comment by juristr** [comment]
@maxime1992 I'll give this a closer look. Will take some time though since I have some higher priority stuff on my plate first. Thx for your patience 🙏

**Comment by maxime1992** [comment]
I believe this should be kept open

**Comment by juristr** [comment]
> Lint, build and test commands can't run anymore on only just what's needed unless I remove the --with-deps. Otherwise it just run those commands on everything.
Should I raise a bug for that or is it normal 🤔?

@maxime1992 a minimal repo to reproduce would definitely be interesting here to see why it wouldn't work anymore.

In your example above: did you try using node libs instead of workspace libs? They can also be made buildable etc, so might be a good fit for sharing logic in your nest app.
