### ISSUE TITLE
RFC: reducing project compile times with improved tooling

### ISSUE THREAD

**Issue by cdaringe** [nrwl/nx#3799]
## Description

Monorepos have a ton of code. Building takes time. These considerations alone are pretty much why so much effort has been placed into working on the build cache in nx! Even with awesome perf tools like the cache, various changes may induce long build/test cycles.

One of the slower steps in JS projects is compiling. Jest compiles, webpack compiles, typescript compiles--pretty much _most_ of our tasks involve some sort of compilation, generally via babel or typescript. These steps are slow. What is _slow?_. It's subjective, but I'm talking generally anything > 1-2 seconds.

Enter https://github.com/swc-project/swc

SWC compiles things comparatively fast. Super fast, even ;)

Consider a world where we just _swap_ TS & Babel with swc

![](https://mk0fictionphilep9xqe.kinstacdn.com/wp-content/uploads/2020/04/indiana-jones-raiders-idol-768x432.jpg)

**Benefits**:

- speed
- consolidation of compiler toolchain (babel + tsc => swc)

**Risks**:

- involves distributing binaries, which can be obnoxious in some environments
- lags behind JS/TS community in features
- nx community is rich w/ configuration and docs around babel & tsc. many NX APIs are first-class to status-quo compilers. implementation could reduce support/attention to status quo toolkit

...and many more. :) This post isn't meant to be complete, just start a dialog

**Comment by FrozenPandaz** [comment]
This is possible if there was a `builder` that ran `swc`. Someone from the community could look into making such a plugin. Distributing binaries and lagging behind the JS/TS community sounds like risk indeed though.

**Comment by JohanHeyvaert** [comment]
No news? I would also like to try **swc**. It's advised by the WallabyJS team here: https://wallabyjs.com/blog/optimizing-typescript.html

**Comment by david-morris** [comment]
Now that swc is supported as default by next.js, it would be great to see this reopened.
