### ISSUE TITLE
Nx hides warning messages when replaying commands from cache

### ISSUE THREAD

**Issue by ashwinGokhale** [nrwl/nx#3800]
## Current Behavior

I have a single Angular app where the size of one of the bundles exceeds the maximumWarning of 250Kb, which I specified in the budgets property in my angular.json file. When I run `nx build my-app --prod` for the first time, there is nothing in the local cache, so I see the entire output, including the warning message that one of the bundles has exceeded 250Kb. However, when I run `nx build my-app --prod` for a second time, it replays the output from the cache, but that output does not contain any warning messages.

## Expected Behavior

I expect the warning messages to be captured and replayed by the Nx cache.

## Steps to Reproduce

1. `git clone https://github.com/nrwl/nx-examples.git`
2. `cd nx-examples`
3. `yarn`
4. Add the following to: `projects.products.architect.build.configurations.production.budgets` in `angular.json`
  4.1. ```
           {
                  "type": "any",
                  "maximumWarning": "1kb"
            }
         ```
5. `yarn nx build --prod`
  5.1. You will see the following output **with** the warnings:
![image](https://user-images.githubusercontent.com/21692499/94059474-5075ae00-fd97-11ea-8901-ff9459fc9a88.png)
6. `yarn nx build --prod`
  6.1. You will see the following output **without** the warnings:
![image](https://user-images.githubusercontent.com/21692499/94059619-87e45a80-fd97-11ea-9d93-eaa76da4bc72.png)


### Failure Logs
<!-- Please include any relevant log snippets or files here. -->

### Environment
<!-- It's important for us to know the context in which you experience this behavior! -->
<!-- Please paste the result of `nx report` below! -->

  nx : Not Found
  @nrwl/angular : 10.1.0  
  @nrwl/cli : 10.1.0  
  @nrwl/cypress : Not Found
  @nrwl/eslint-plugin-nx : 10.1.0
  @nrwl/express : 10.1.0
  @nrwl/jest : 10.1.0
  @nrwl/linter : 10.1.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.1.0
  @nrwl/react : 10.1.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.1.0
  @nrwl/web : 10.1.0
  @nrwl/workspace : 10.1.0
  typescript : 3.9.7

**Comment by vsavkin** [comment]
Thank you for submitting the issue.

By default we only capture stdout, and we don't capture stderr. The reason for that is that stderr can produce a lot of output and it can take a long time to replay it (many seconds). Most of the time, if the command succeeds, all the needed output is in stdout. The warnings in this case are printed into stderr. You can capture stderr by setting NX_TERMINAL_CAPTURE_STDERR env variable to true.

We are thinking about making it more customizable, for now the env variable is the only accordance we provide.

I'm going to close this issue.
