### ISSUE TITLE
Publishable library not build in prod mode when ngrx module is imported

### ISSUE THREAD

**Issue by gmfun** [nrwl/nx#3801]
## Current Behavior

Builidng publishable library in prod mode is throwing error when any module in it contains `StoreModule.forRoot`
```
ERROR: Error during template compile of 'NgTestModule'
  Function calls are not supported in decorators but 'StoreModule' was called.

An unhandled exception occurred: Error during template compile of 'NgTestModule'
  Function calls are not supported in decorators but 'StoreModule' was called.
```

## Expected Behavior

Library should build in prod mode

## Steps to Reproduce

- create a new workspace
- add publishable library lets say `ng-test`
- `ng add @ngrx/store`
- import empty `StoreModule` in `NgTestModule`  in `ng-test` library. `imports: [CommonModule, StoreModule.forRoot({})],`
- `nx build ng-test --prod`

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

```
nx : Not Found
  @nrwl/angular : 10.2.1
  @nrwl/cli : 10.2.1
  @nrwl/cypress : 10.2.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.2.1
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.2.1
  @nrwl/web : Not Found
  @nrwl/workspace : 10.2.1
  typescript : 3.9.7
```

**Comment by brandonroberts** [comment]
Linking this issue for reference to check the `skipTemplateCodgen` flag in the `angularCompilerOptions`. https://github.com/ngrx/platform/issues/2768
