### ISSUE TITLE
Rollup web:package - externals with wildcard

### ISSUE THREAD

**Issue by Bielik20** [nrwl/nx#3809]
## Description

There are libs that export stuff from inner paths. Examples
* rxjs/operators
* lodash/**

That causes them to be bundled with lib as they are not technically externals because this:
https://github.com/nrwl/nx/blob/9153007462212d5f6f2aacdec2c2e49a764ba090/packages/web/src/builders/package/package.impl.ts#L249
checks quality.

## Motivation

Smaller bundle size.

## Suggested Implementation

Naive implementation would look like that:

```js
external: (id) => externalPackages.some(pkg => (id === pkg || id.includes(`${pkg}/`)))
```

## Alternate Implementations

I also entertained a thought of doing it with `rollupConfig` that would simply overwrite `external`. Problem is that I have no access to `externalPackages` created in [here](https://github.com/nrwl/nx/blob/9153007462212d5f6f2aacdec2c2e49a764ba090/packages/web/src/builders/package/package.impl.ts#L236) and I would like to avoid repeating the same job.

As of right now, I am doing [this](https://github.com/Bielik20/ts-libs/blob/5c9a9f27646f40f58787f242db98d9e72f4d554f/tools/src/plugins/react-rollup-plugin.ts#L1-L34) to replace `rollupConfig`.

**Comment by Bielik20** [comment]
I still think this is a valid issue.
Although it can be fixed with custom rollup plugin it is such a common use case this should be handled out of the box.

**Comment by shubhamdeodia** [comment]
This is really an important option to have, please add this feature

**Comment by linbudu599** [comment]
@FrozenPandaz This issue had already been fixed, maybe you can close it now.

**Comment by Bielik20** [comment]
It is true, may work around is no longer necessary.
