### ISSUE TITLE
Prod build has same css in styles.css and main.css

### ISSUE THREAD

**Issue by ajitsonlion** [nrwl/nx#3811]
## Current Behavior

On nx build --prod, the final index.html contains

```
<link rel="stylesheet" href="styles.bd7cbed31af32e1c87b5.css">
<link rel="stylesheet" href="main.bd7cbed31af32e1c87b5.css"></head>

```
Exact came code, since the hash is same, is being added into the head section two times, once in styles.css and then main.css

My workspace.json config has only one entry
`"styles": ["apps/my-app/src/styles.scss"],
`

## Expected Behavior
Only one entry for global css file.

## Steps to Reproduce
I updated to nx 10.2.1 and noticed this two time addition in final build.
When I remove 
`"styles": ["apps/my-app/src/styles.scss"],
`
both the css links are gone.

**Comment by mandarini** [comment]
Hi there @ajitsonlion ! Thanks for filing an issue!

Unfortunately, I could not reproduce your issue using the latest version of Nx. I generated a new workspace with a react app, I added a component, some new css rules, and then I built the app. The resulting `index.html` looks like this:

<img width="648" alt="Screenshot 2020-09-29 at 2 43 29 PM" src="https://user-images.githubusercontent.com/6603745/94554087-3853d200-0262-11eb-9cdb-e8303e931268.png">

Can you provide a repo which reproduces your issue?

**Comment by ri8ika** [comment]
It is not rendered in the file. But it can be seen when you view the page source. And even in normal running app (without building), you can see the main.css

**Comment by ChrisABryant** [comment]
The cause of this issue was found in our project.  The scss files were imported in our code as well as being specified in workspace.json. Removing the import eliminated the redundant main.css.
