### ISSUE TITLE
Improve support for node library/application package management

### ISSUE THREAD

**Issue by gioragutt** [nrwl/nx#3817]
## Description

[Also described in this reddit comment](https://www.reddit.com/r/Angular2/comments/iy3hgx/angular_typescript_vs_nodejs_backend_typescript/g6c786u/?context=3).

Recently I migrated some of my company's code to an NX repo. It consists of:
* several front-end angular projects, more to be migrated in the future.
* a production node microservice, and several other node-based projects.

Bundling and dockerizing a front-end application is a piece of cake - bundle and you're done.
On the other hand, bundling and dockerizing a node app is a pain.

Since an NX repo only has a single `package.json`, you need a different mechanism for bundling your dependencies, an example for such is described [in this issue](https://github.com/nrwl/nx/issues/1777), and in issues linked to it.

In the reddit post, I described a problem I had which made me do an even uglier workaround, to do get a `node_modules` directory in my code, since a library I used (`jaeger-client`) relied to reading an asset from there.

What I ended up doing was save a list of all dependencies that are specific to node libraries and apps (which is still more than you need, but much less than you would get otherwise) and generate a `package.json` using this list.

## Motivation

I think that there should be a more standard way to bundle/build node applications, such that supports `node_modules` cleanly. Running the applications locally could work the same as it does now, but another option to bundle it with a proper node_modules should be available.

## Suggested Implementation

One thing I thought of would be to generate a `package.json` as part of the bundling.
In order to generate the `package.json`, you'd have each node library and application specify its distinct dependencies in a configuration file. It would be just the names of the dependencies, since the versions are specified in the repo-level `package.json`.

In the build process, since dependencies are known, you could collect all the dependencies from all libraries used, and the built application, and combine it into a `package.json`.

This `package.json` is then *easily* used by a Dockerfile that would copy the `package.json`, then `npm install` (or `npm ci` if we can generate a lock file as well), and then copy the `dist` files themselves.

## Alternate Implementations

I can't think of any non-hacky solutions, but it would revolve around libraries specifying their dependencies, and later a more compact `node_modules` is created.

If you could take the actual `node_modules` of the repo, copy it, and curate it to contain only the needed dependencies.

I don't know how the curation process would work, but I also don't know if this would work well with docker layer caching 🤷🏻‍♂️

**Comment by reajuria** [comment]
@gioragutt , It looks like in order to generate package.json you need to include `"packageJson"` property in `workspace.json` file, this is a nestjs api example:

```
{
  "version": 1,
  "projects": {
    "some-api": {
      "root": "apps/some-api",
      "sourceRoot": "apps/some-api/src",
      "projectType": "application",
      "prefix": "some-api",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@nrwl/node:build",
          "options": {
            "outputPath": "dist/apps/some-api",
            "main": "apps/some-api/src/main.ts",
        --> "packageJson": "apps/some-api/package.json", <--
            "tsConfig": "apps/some-api/tsconfig.app.json",
            "assets": ["apps/some-api/src/assets"]
          },
          "configurations": {
            ...
```

Then add a `package.json`:
```
{
  "name": "@org-name/some-api",
  "version": "1.0.1"
}

```

I'm using `nrwl/cli@10.3.1`

Hope it helps 👋🏻

**Comment by gioragutt** [comment]
Hey @reajuria, thanks for the tip!

I'm currently not able to test this, so I'm gonna ask instead. When I use this method, do I have to populate the `package.json` dependencies array(s) myself, or does `nx` handle this?

Because if it doesn't, it'd mean that I'd still have to manage `package.json` dependencies separately for this app.
Also, how would mono-repo level dependencies work?

**Comment by reajuria** [comment]
@gioragutt this is just a workaround to generate `package.json` file with `@nrwl/node:package` builder 😅

`package.json` template will include project dependencies when `nx build some-api` completes (Actually, it may end with an error showing `error TS6059: File '...whole-path-to-a-lib-dependency-file.ts' is not under 'rootDir' 'apps/some-api'. 'rootDir' is expected to contain all source files.`) then it will be placed on `/dist/apps/some-api/package.json` .

Note that I missed to change `"builder": "@nrwl/node:build",` to `"builder": "@nrwl/node:package",` in previous comment.

You can also do a copy of the `build` architect section and name it `package` then you can run `nx package some-api` instead of `nx build some-api` and store somewhere else the generated `/dist/apps/some-api/package.json` to be used with a `Dockerfile`.

Architects section will look like:
```
"architect": {
  "package": {
    "builder": "@nrwl/node:package", <--
    "options": {
      "outputPath": "dist/apps/some-api",
      "main": "apps/some-api/src/main.ts",
      "packageJson": "apps/some-api/package.json", <--
      "tsConfig": "apps/some-api/tsconfig.app.json",
      "assets": ["apps/some-api/src/assets"]
    },
    "configurations": {
      "production": {
        "optimization": true,
        "extractLicenses": true,
        "inspect": false,
        "fileReplacements": [
          {
            "replace": "apps/some-api/src/environments/environment.ts",
            "with": "apps/some-api/src/environments/environment.prod.ts"
          }
        ]
      }
    }
  },
  "build": {
    "builder": "@nrwl/node:build",
    ...
```

mono-repo dependencies will/should be kept the same way in root `package.json` as nx currently does.

This is a example `/dist/apps/some-app/package.json` that I get every time as output:
```
{
  "name": "@org-name/some-api",
  "version": "1.0.1",
  "main": "src/main.js",
  "typings": "src/main.d.ts",
  "dependencies": {
    "typeorm": "^0.2.29",
    "@nestjs/common": "^7.0.0",
    "@nestjs/typeorm": "^7.1.5",
    "lodash": "^4.17.20",
    "rxjs": "~6.5.5",
    "crypto-js": "^4.0.0",
    "ioredis": "^4.19.2",
    "axios": "^0.21.0",
    "jsonwebtoken": "^8.5.1",
    "@nestjs/schedule": "^0.4.1",
    "@nestjs/core": "^7.0.0",
    "cache-manager": "^3.4.0",
    "helmet": "^4.2.0"
  },
  "peerDependencies": {}
}
```

We should be able to do all this without a workaround or having to manually collect dependencies, Maybe `@nrwl/node:package` builder is not intended to be used on applications but it would be great to be able to package them using it

**Comment by reajuria** [comment]
# nrwl/nx packaging nest applications
I've found another workaround to generate a deployable microservice with a single bash script, currently I'm using Google Cloud Build to build container images. I will post what works for my use case but anyone can easily adapt it.

Currently using `@nrwl/cli@10.3.1` installed globally to run scripts

## Add `/apps/some-api/package.json`
You can include `scripts` tag to run scripts inside dist application's folder.
```
{
  "name": "@org-name/some-api",
  "version": "1.0.1",
  "scripts": {
    "cloud-build": "gcloud builds submit --tag gcr.io/...",
    "cloud-deploy": "gcloud run deploy ..."
  },
}
```

## Add `@nrwl/node:package` architect to your project in `workspace.json`
Make a copy of build architect and modify until it looks like:
```
"architect": {
  "package": {
    "builder": "@nrwl/node:package", <-- Change `build` to `package`
    "options": {
      "outputPath": "dist/apps/some-api",
      "main": "apps/some-api/src/main.ts",
      "packageJson": "apps/some-api/package.json", <-- Add the path to a `package.json` inside your nest application
      "tsConfig": "apps/some-api/tsconfig.app.json",
      "assets": ["apps/some-api/src/assets"],
      "srcRootForCompilationRoot": "." <-- Add this line, this will fix TS6059 error during packaging if your application depends on `/libs` folder
    }
  },
  "build": {
    "builder": "@nrwl/node:build",
    ...
```

## Add `/apps/some-api/assets`
Add a folder where you will store files like `Dockerfile` and files that your application may need for execution or containerization... in my case I named `assets`

## Add `/apps/some-api/assets/Dockerfile`
This file can be simple as:
```
FROM node:12

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --only=production

COPY . ./

EXPOSE 8080

CMD [ "node", "main.js" ]
```

## Add scripts for applications
Here you will store the scripts to package or deploy your nest application, anyone with higher understanding on bash scripting can easily do a single script that accepts a parameter for application name and do validations and more, for now we will keep this as an example. You may need to prepend `npx` to nx commands to be able to run or use `package.json` included scripts

### `/scripts/some-api/package.sh`
```
# Cleanup
rm -rf ./dist/apps/some-api

# Generate package.json and remove remaining directories
nx package some-api
rm -rf ./dist/apps/some-api/apps
rm -rf ./dist/apps/some-api/libs

# Build Node/NestJS Application
nx build some-api

# Install node packages to create package-lock.json then cleanup node_modules
cd ./dist/apps/some-api/
npm install
rm -rf ./node_modules
cd ../../..

# Copy Dockerfile or other needed files
cp ./apps/some-api/package/* ./dist/apps/some-api/
```

### `/scripts/some-api/cloud-build.sh`
```
cd ./dist/apps/some-api/
npm run cloud-build
cd ../../..
```

### `/scripts/some-api/cloud-deploy.sh`
```
cd ./dist/apps/some-api/
npm run cloud-deploy
cd ../../..
```

## Run commands from mono-repo directory
`sh ./scripts/some-api/package.sh`
After running it you will get an application folder that has `package.json` and `package-lock.json` that can be included in CI/CD, publish to a package repository or create docker images, is up to everyone needs.

You can manually trigger a build for a container image
`sh ./scripts/some-api/cloud-build.sh`

Then deploy it
`sh ./scripts/some-api/cloud-deploy.sh`


There may be more ways to package and publish applications and there may be ways to trigger builds when applications are affected by changes, if anyone knows please share them 👋🏻

**Comment by steinroe** [comment]
This is what is holding us back to nx. We need to setup cicd for multiple react apps. + libraries and multiple nest services + libraries.
