### ISSUE TITLE
Build Options for Library Project Type

### ISSUE THREAD

**Issue by imben1109** [nrwl/nx#3819]
## Description
There are no build option for library project type including angular or react. 

## Motivation
It can extends nx to include momo repo to develop library for angular or react or any other supported framework.

## Suggested Implementation
Add build option for library project type. just like ng-packagr in angular cli. 

## Alternate Implementations
N/A

**Comment by FrozenPandaz** [comment]
Is this [the flag](https://nx.dev/latest/react/plugins/angular/schematics/library#buildable) you are looking for? It adds a `build` target to the library.

**Comment by imben1109** [comment]
@FrozenPandaz Yes. 

```
nx g @nrwl/react:library test-runbable-lib --buildable=true
```

It works. Should this flag be true as default?
