### ISSUE TITLE
make ngrx optional

### ISSUE THREAD

**Issue by piernik** [nrwl/nx#382]
`ngrx` has a good competitor `nrxs`  https://ngxs.gitbooks.io/ngxs/
`nx` uses `ngrx` by default. 
Maybe giving another param to skip `ngrx` as `package.json` dependency?

**Comment by ThomasBurleson** [comment]
@piernik - what do you mean by *skip* `ngrx` as a package.json dependency?

**Comment by piernik** [comment]
After generating new workspace `package.json` always contains 
```
    "@ngrx/effects": "5.1.0",
    "@ngrx/router-store": "5.0.1",
    "@ngrx/store": "5.1.0",
    "@ngrx/store-devtools": "5.1.0", 
```

**Comment by jeffbcross** [comment]
We've discussed making NgRx optional. Personally I'd like to keep it, since the point of Nx is to be able to provide more value by being more prescriptive (and being able to provide more validation/enforcement because of that).

**Comment by piernik** [comment]
@jeffbcross can I simply delete all ngrx dependencies from package file?

**Comment by ThomasBurleson** [comment]
Sure... If you are not using Ngrx in your code nor using DataPersistence.

**Comment by ThomasBurleson** [comment]
Closing as will-not-change.

**Comment by SamuelMS** [comment]
@ThomasBurleson @jeffbcross I'd ask that we reconsider here, if possible.

I honestly believe the core offering of Nx isn't any particular integration with Ngrx -- I think it's safe to say that many Angular teams at enterprises don't use it -- but rather the scaffolding and control that it provides to developers that need to manage many distinct applications.

Being able to share components and resources across projects, complete with CLI support? That's _massive_ value. Seriously, that's huge. But while that would likely prove a significant time- and cost-saver for our clients, we have no intention to leverage any Ngrx functionality at this point.

I understand that we can use Nx as-is and make do (and simply ignore Ngrx), but it just feels like the message is a bit muddled here if they ship together. Per @FallenRiteMonk's comment, it seems as if Nx is already fairly decoupled from Ngrx as is, so removing it by default doesn't seem like _too_ large a stretch to ask for -- but please let me know if I'm totally off base here.

**Comment by Mathyn** [comment]
Any updates on this? Just like @paddyfink I get the following errors when building my project:

```
ERROR in node_modules/@nrwl/nx/src/data-persistence.d.ts(3,25): error TS2307: Cannot find module '@ngrx/effects'.
node_modules/@nrwl/nx/src/data-persistence.d.ts(4,31): error TS2307: Cannot find module '@ngrx/store'.
```

**Comment by philly-vanilly** [comment]
> Sure... If you are not using Ngrx in your code nor using DataPersistence.

That is not true, the project is not building, I get the same errors as Mathyn. Why don't you just make data-persistence an optional npm module for nx?

I am using NX just for architecture linting (for preventing libs using libs that should not depend on each other); alternatively you could make this function an own npm module. Static, development-only features like this should not be tied together with runtime ones.

If anyone knows how to set up this kind of linting yourself, please let me know.

**Comment by Boosten** [comment]
@Mathyn make sure to remove the NxModule from your AppModule:
![image](https://user-images.githubusercontent.com/3380927/54925438-96398800-4f0e-11e9-8c07-970324c3f60e.png)
