### ISSUE TITLE
simpleModuleName option for NestJs libs

### ISSUE THREAD

**Issue by brevelles** [nrwl/nx#3822]
## Description
When creating a Nestjs lib, if the library is being created inside a directory (using --directory option), the resulting module name includes the folder name.

## Motivation
The simpleModuleName option already exists in @nrwl/angular:library. I believe it should also exist in @nrwl/nest:library

## Suggested Implementation
Same as @nrwl/angular:library (simpleModuleName to keep the module name simple when using --directory)

**Comment by hnxb** [comment]
Hi there, I think there's a mistake here.
The PR is adding `simpleModuleName` for `node`, not `nestjs`.

I couldn't generate a lib with `simpleModuleName` flag using `@nrwl/nest` generator

```bash
nx g @nrwl/nest:lib mylib --directory=api --simpleModuleName
```

```bash
'simpleModuleName' is not found in schema
```

Do we need to reopen this?

**Comment by lahtite** [comment]
@FrozenPandaz, I think this issue should be reopened. Issue [#5153](https://github.com/nrwl/nx/pull/5153) did not solve this. SimpleModuleName option does still not work with @nrwl/nest:library schema.

**Comment by JoseLopez01** [comment]
isn't this working in nest yet?

**Comment by tar-aldev** [comment]
So I assume for now this can only be achieved with
```
nx generate @nrwl/nest:library <library_name> && \
nx generate @nrwl/workspace:move grouping_folder/<library_name> --projectName=<library_name> --no-interactive
```
?
And also manually update workspace.json to change `projects` field?

**Comment by bilalshaikh42** [comment]
Can we reopen this? It would be very useful. Lots of time wasted with manually doing this
