### ISSUE TITLE
How to add git project as app?

### ISSUE THREAD

**Issue by HackPoint** [nrwl/nx#383]
For example I have whole different project and I would like to add it into the workspace.
Link to project I would like to add:
https://github.com/codetok/cdk-admin

What is the best practice to do it?

**Comment by mrmeku** [comment]
If we look here (https://github.com/nrwl/nx/blob/4edc8e6c8b0801a13a5b0722eb20a68fa59eec11/packages/schematics/src/collection.json#L9) we'll see that we have a schematic that you can run to migrate an existing cli project to an nx workspace. You can run the schematic via:

`ng g workspace --collection=@nrwl/schematics`
