### ISSUE TITLE
Extend docs for nx run-many

### ISSUE THREAD

**Issue by tar-aldev** [nrwl/nx#3832]
## Description

When I run `nx run-many` how do I specify ports for each app respectively? I cannot find any mention of this in your documentation.

**Comment by FrozenPandaz** [comment]
This currently does not exist. My recommendation would be to set a different port in `workspace.json` if you want to run them together. Then you can use `run-many` to serve those projects together.

If this does not work for you, please provide your motivation and a suggested implementation.
