### ISSUE TITLE
Using data persistence in effects fetch method providing full store state should provide the partial or feature state

### ISSUE THREAD

**Issue by ak274** [nrwl/nx#3838]
The DataPersistence helper functions return the full store state instead of the partial feature state. 

Similar issue was submitted in the past too:--
https://github.com/nrwl/nx/issues/711

**Current Behavior** 
Here is the reproduction branch if you go to products and orders pages i'm logging the state in effects which are using data persistence utility class it will log the entire state or the app.

**Expected Behavior** 
In  orders effects it should only use the orders partial state and in products it should only provide products state.

**Reproduction Repo**
https://github.com/ak274/nx-issue

![image](https://user-images.githubusercontent.com/16129430/94694315-57ca2800-0352-11eb-8cbc-706726acd98f.png)

**Comment by brandonroberts** [comment]
This is by design. The method doesn't have context of a partial state. If you want a partial state, you need to use a selector in combination with the data persistence operators.

**Comment by naticaceres** [comment]
how would I go if I wanted to combine a selector with a data persistence operator? 
is there somewhere an example or some documentation where I can read about this scenario?

**Comment by robinpellegrims** [comment]
For future reference, here's an example of combining the `fetch` operator with a (feature) state selector:

```typescript
  this.actions$.pipe(
      ofType(MyAction),
      concatLatestFrom(() => this.store$.select(featureStateSelector)),
      fetch({
        run: (action, state) => {
```
