### ISSUE TITLE
Generating an app fails on Mac when in a directory with spaces

### ISSUE THREAD

**Issue by Skubakoob** [nrwl/nx#384]
I followed the instructions to get up and running and generate a workspace - all good. When generating an app however, I kept getting errors of a module not existing.

This was all sat in a folder called "VS Projects"

I moved the workspace to "Projects" and the app was created successfully

Just thought that might help someone who has the same issue on a Mac.. On windows it doesn't seem to be a problem

**Comment by mrmeku** [comment]
Thanks so much for writing a well authored bug report. I was able to reproduce the bug easily. We'll get on fixing this

**Comment by FrozenPandaz** [comment]
This issue should have been fixed for a while now with https://github.com/nrwl/nx/pull/353. Let us know if you are still running into this issue.
