### ISSUE TITLE
Unable to stop tests with nx

### ISSUE THREAD

**Issue by therk** [nrwl/nx#3842]
## Current Behavior
On MacOSX (Catalina 10.15.6), when running npm script "nx run-many --target=test --all" unable to stop test using Ctrl + C

## Expected Behavior
Tests should stop running when SIGNINT is sent from the terminal to the process.

## Steps to Reproduce
Create multiple projects such as frontend in React, frontend e2e, and backend in NodeJS with tests.
Start running the all tests via "nx run-many --target=test --all"

### Environment

>  NX  Report complete - copy this into the issue template

  nx : 10.2.1
  @nrwl/angular : Not Found
  @nrwl/cli : 10.1.0
  @nrwl/cypress : 10.1.0
  @nrwl/eslint-plugin-nx : 10.1.0
  @nrwl/express : 10.1.0
  @nrwl/jest : 10.1.0
  @nrwl/linter : 10.1.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.1.0
  @nrwl/react : 10.1.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.1.0
  @nrwl/web : 10.1.0
  @nrwl/workspace : 10.1.0
  typescript : 3.9.7

**Comment by FrozenPandaz** [comment]
Good catch, I have a fix :)
