### ISSUE TITLE
Option to exclude certain bundles from source map generation

### ISSUE THREAD

**Issue by vaunus** [nrwl/nx#3848]
## Description
Having played with the `@nrwl/web:build` builder's `sourceMap` options and reviewing the NX code, I can see that `SourceMapDevToolPlugin` is used when generating source maps within Webpack. I propose adding a new builder option to allow excluding certain bundles from source map generation which leverages the `exclude` option of this plugin.

## Motivation
In our project we are seeing very slow build times when source maps are generated for our production builds. We would still like these to be generated for our `main` bundle since we send this off to our error reporting tools, but we are less concerned about generating source maps for the `vendor` bundle. I noticed most of the build time goes into generating source maps for the vendor bundle leading to a total build time for just one of our apps of ~10 mins. I have tested excluding source map generation for the vendor bundle by adding an `excludes: ['vendor']` to the `SourceMapDevToolPlugin` and this takes build time down to 1m 30s. 

## Suggested Implementation
My suggestion would be to add a `sourceMap.excludeBundles: [ ]` option to the `@nrwl/web:build` builder options. e.g. 

```
"builder": "@nrwl/web:build",
    "options": {
        ...
        "sourceMap": {
            ...
            "excludeBundles": ["vendor"]
        }
    }
```

After testing this I can see that passing this string array directly into the `SourceMapDevToolPlugin` `exclude` option prevents source maps from being generated for the specified bundles.

## Alternate Implementations
None considered, but it seems giving the developer finer grained control over this would be useful.

**Please let me know your thoughts on this. I am happy to put in a PR with your** 👍🏻

**Comment by jaysoo** [comment]
@vaunus Hey, sorry for the delayed response. I think the problem with explicitly defining bundle names to exclude is that they are defined by Nx so it wouldn't be clear how to configure this option properly.

Nx is supposed to support turning vendor sourcemap on/off through existing options (https://github.com/nrwl/nx/blob/master/packages/web/src/builders/build/schema.json#L68-L71)

There's a bug right now that'll be fixed here https://github.com/nrwl/nx/pull/3902

Once the fix lands, sourcemaps will exclude vendor by default, and you can turn it on by editing your `workspace.json` file.

```
{
  "sourceMap": {
    "scripts": true,
    "vendor": true
  }
  ...
}
```

I hope that helps!

**Comment by vaunus** [comment]
@jaysoo that's excellent thanks!

**Comment by chrismcleod** [comment]
i also discovered today adding the SourceMapDevtools option to disable columns reduces build time by about 95%.
