### ISSUE TITLE
There are several of them but closed - nrwl doesnt respect env configs for cypress

### ISSUE THREAD

**Issue by panraj01** [nrwl/nx#3855]
## Current Behavior
nx custom appName-e2e --env.build 1.1.79 --watch
Schema validation failed with the following errors:
  Data path ".env" should be object.

## Expected Behavior
Should be able to pass the build number which is under the env object in cypress config.

## Steps to Reproduce
Try above. It work seldom and not work most of the time. I dont know the reason for inconsistency, but its adding to the pain and its frustrating.

### Environment
NX version - 9.3.0

**Comment by bekos** [comment]
@panraj01 it's weird that it even runs sometimes on 9.3.0. This is fixed via ee4b278, which is available after 10.2.0. Can you upgrade and try again?

**Comment by bekos** [comment]
@panraj01 Closing as we haven't heard back from you. Feel free to reopen if you have any more details.

**Comment by panraj01** [comment]
Hey @bekos - my sincere apologies, i had some challenges upgrading the version since my lead was in middle of feature (even though its not related). I upgraded NX and eypress env variables are working again. Thanks much. Appreciate you keeping an eye on this one.

**Comment by bekos** [comment]
@panraj01 Glad it works for you now 🎉
