### ISSUE TITLE
Dependency constrains are not announced when loading library lazily

### ISSUE THREAD

**Issue by chernodub** [nrwl/nx#3857]
## Current Behavior
When I'm trying to import Angular library with `loadChildren`, `nx-enforce-module-boundaries` rule doesn't announce any message, while the esm import works just fine
![image](https://user-images.githubusercontent.com/37013688/94985061-313c0500-057d-11eb-8c8a-0ab071402aa3.png)

As you can see, no linting message
![image](https://user-images.githubusercontent.com/37013688/94985072-5466b480-057d-11eb-982c-2d82e52fbad0.png)

## Expected Behavior
When I import lib through `loadChildren` I expect to see the same message as it would be with importing through esm import

## Steps to Reproduce
Repo: https://github.com/chernodub/nx-acht
1. Create lib with `scope` different from `scope:shared` to make sure it doesn't match any constraints
2. Try to import with `loadChildren`

### Environment
```
  "dependencies": {
    "@angular/animations": "^10.0.0",
    "@angular/common": "^10.0.0",
    "@angular/compiler": "^10.0.0",
    "@angular/core": "^10.0.0",
    "@angular/forms": "^10.0.0",
    "@angular/platform-browser": "^10.0.0",
    "@angular/platform-browser-dynamic": "^10.0.0",
    "@angular/router": "^10.0.0",
    "@google-cloud/firestore": "^4.2.0",
    "@nestjs/common": "^7.0.0",
    "@nestjs/core": "^7.0.0",
    "@nestjs/platform-express": "^7.0.0",
    "@nrwl/angular": "10.0.7",
    "reflect-metadata": "^0.1.13",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-ng-packagr": "~0.1000.5",
    "@angular/cli": "~10.0.0",
    "@nrwl/workspace": "10.0.7",
    "@types/node": "~8.9.4",
    "dotenv": "6.2.0",
    "ng-packagr": "^10.0.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.0.0",
    "eslint": "6.8.0",
    "typescript": "~3.9.3",
    "prettier": "2.0.4",
    "@nrwl/nest": "10.0.7",
    "@angular/compiler-cli": "^10.0.0",
    "@angular/language-service": "^10.0.0",
    "@angular-devkit/build-angular": "~0.1000.0",
    "codelyzer": "~5.0.1",
    "jest-preset-angular": "8.1.2",
    "@nrwl/jest": "10.0.7",
    "jest": "25.2.3",
    "@types/jest": "25.1.4",
    "ts-jest": "25.2.1",
    "cypress": "^4.1.0",
    "@nrwl/cypress": "10.0.7",
    "@nrwl/node": "10.0.7",
    "@nestjs/schematics": "^7.0.0",
    "@nestjs/testing": "^7.0.0"
  }
```

**Comment by chernodub** [comment]
Guys, could you help me understand if we could resolve the issue?

**Comment by gkamperis** [comment]
Same for me with the latest...

NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : 10.3.1
  @nrwl/cli : 10.3.1
  @nrwl/cypress : 10.3.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.1
  @nrwl/linter : 10.3.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.1
  @nrwl/web : Not Found
  @nrwl/workspace : 10.3.1
  typescript : 4.0.5
