### ISSUE TITLE
While creating storybook for a Lib ui project_type_1.projectDir is not a function

### ISSUE THREAD

**Issue by nahumzs** [nrwl/nx#3862]
## Current Behavior
[REACT]
I created a library UI running `nx g @nrwl/react:storybook-configuration something` then I tried to add storybook support as how it's indicated on [the documentation](https://nx.dev/latest/react/plugins/storybook/overview) and the [youtube tutorial](https://www.youtube.com/watch?v=sFpqyjT7u4s&ab_channel=Nrwl-NarwhalTechnologiesInc.)

Then I tried to run `nx g @nrwl/react:storybook-configuration project-name` but failed with:

> project_type_1.projectDir is not a function

Not sure what am I missing.

<img width="893" alt="Screen Shot 2020-10-04 at 11 32 19 AM" src="https://user-images.githubusercontent.com/19418590/95024091-d74b4600-0635-11eb-9534-855e6e90a351.png">
<img width="219" alt="Screen Shot 2020-10-04 at 11 32 30 AM" src="https://user-images.githubusercontent.com/19418590/95024092-d87c7300-0635-11eb-8edf-692964f6be13.png">

## Expected Behavior

Its should created storybook in a specific library when running `nx g @nrwl/react:storybook-configuration project-name`

## Steps to Reproduce

This I'm trying this in a fresh and new nrwl project:

```
    "@nrwl/eslint-plugin-nx": "10.2.1",
    "@nrwl/jest": "10.3.0",
    "@nrwl/react": "^10.3.0",
    "@nrwl/storybook": "^10.3.0",
    "@nrwl/workspace": "10.2.1",
``` 

### Environment

```
    "@nrwl/eslint-plugin-nx": "10.2.1",
    "@nrwl/jest": "10.3.0",
    "@nrwl/react": "^10.3.0",
    "@nrwl/storybook": "^10.3.0",
    "@nrwl/workspace": "10.2.1",
```

**Comment by FrozenPandaz** [comment]
Hi @nahumzs,

Your `@nrwl/workspace` version is misaligned with your other `@nrwl/` packages. Can you please update `@nrwl/workspace` to `^10.3.0` and see if the issue is resolved?

**Comment by boisamazing** [comment]
Thanks for @FrozenPandaz 's solution.
For me just run `npm install @nrwl/workspace@latest` to upgrade `@nrwl/workspace` to the latest version, which is currently `^10.3.0`, has solved the problem.

**Comment by nahumzs** [comment]
@FrozenPandaz beautiful indeed that solved the issue, TIL:

All the version for `@nrwl/...` have to run in the same version 🙏
