### ISSUE TITLE
AWS CDK support?

### ISSUE THREAD

**Issue by ynishimura** [nrwl/nx#3864]
Hello there

Love nx, very brilliant.

We're building backend system on AWS.
Then we're using [AWS CDK](https://github.com/aws/aws-cdk). Would you consider a PR adding schematics for AWS CDK? Or is it better to do it as an independent lib?

Cheers

Daniel

**Comment by ValiDraganescu** [comment]
resuscitate this feature please :)

**Comment by timofeysie** [comment]
It looks like there are a few options for doing this already.


[@myin/aws-cdk](https://npm.io/package/@myin/aws-cdk): Working with AWS CDK in Nx workspaces

```txt
nx g @myin/aws-cdk:application <project-name>
nx g @myin/aws-cdk:lambda <project-name>
```

[@flowaccount/nx-plugins]\(https://github.com/flowaccount/nx-plugins): 🔎 Extensible Continous Delivery/Depolyment Tools on top of Nx workspace for seamless deployments with frameworks like Serverless Framework and aws-cdk (Infrastructure as a code)

I don't see and usage info there.  It says there is a [@flowaccount/nx-aws-cdk plugin](https://github.com/flowaccount/nx-plugins/tree/master/libs/nx-aws-cdk).

There might be more.  @ValiDraganescu or anyone want to try those out?  Add any more options you find here as well.

**Comment by yehonadav-feel** [comment]
@codebrew/nx-aws-cdk
