### ISSUE TITLE
Creating library in a nested folder

### ISSUE THREAD

**Issue by roip890** [nrwl/nx#3869]
Hi,

I am trying to create an angular library in a nested folders.
Somehow, if the module is in a path a/b/c/d/lib-name it generated with a name of a-b-c-d-lib-name.
(for example nx g lib lib-name --directory a/b/c/d).
There is an option to create a lib in a nested folder without changing the lib name?

Thanks.

**Comment by juanjofg** [comment]
Have you tried using **--simpleModuleName**?

**Comment by vsavkin** [comment]
Hi there!

simpleModuleName changes the generated module name. If you want to change the lib name itself, you just need to update manually in workspace.json and nx.json after the generation. You can also create a workspace schematic that will generate a lib and will do the rename after.
