### ISSUE TITLE
[Nx-Plugin] Add support for other package managers than Yarn when installing deps for  e2e tests

### ISSUE THREAD

**Issue by tinesoft** [nrwl/nx#3871]
## Description

Currently, running `nx e2e my-project-e2e` fails when installing dependencies if **Yarn is not installed**.
It should instead default to NPM when the later is not found. Or, better yet, it should auto-determine the right package manager, just like it is done when creating the Nx plugin workspace.

## Motivation

Could not run e2e tests if using NPM instead of Yarn
## Suggested Implementation

In https://github.com/nrwl/nx/blob/31304d4d01bb6f0e5a04082ec72e64c78a0e6756/packages/nx-plugin/src/utils/testing-utils/nx-project.ts#L67

Replace the call to `runYarnInstall()` by a `runPackageManagerInstall()` that could look like this:

```
export function runPackageManagerInstall(silent: boolean = true) {
  const packageManager = determinePackageManager(); // see https://github.com/nrwl/nx/blob/31304d4d01bb6f0e5a04082ec72e64c78a0e6756/packages/create-nx-plugin/bin/create-nx-plugin.ts#L202 for reference
  const install = execSync('${packageManager} install', {
    cwd: tmpProjPath(),
    ...(silent ? { stdio: ['ignore', 'ignore', 'ignore'] } : {}),
  });
  return install ? install.toString() : '';
}
```

## Alternate Implementations

I could propose a PR if this request is accepted

**Comment by trumbitta** [comment]
Yes please! I can't for the life of me get Yarn to work with a private npm registry (while npm works just fine) and since I don't use Yarn anyway, this is bugging me big time!

**Comment by trumbitta** [comment]
I found a way: https://dev.to/trumbitta/how-to-make-both-npm-and-yarn-use-private-registries-2n6b

But I still wasted like 3 days on this, and I won't use yarn for anything else than this anyway :)

**Comment by bekos** [comment]
@tinesoft You can send a PR, thx 👍
