### ISSUE TITLE
Type Definition overrides are ignored

### ISSUE THREAD

**Issue by JonasZ95** [nrwl/nx#3886]
## Current Behavior
I tried to use react-table in my nx react project which requires you to override some types If you want to use some plugins:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table
However, those overrides are ignored for some reason and building the project results in errors while linting and dev tools(vscode) work fine with the provided types.

## Expected Behavior
NX respects the type definition overrides and builds fine.

## Steps to Reproduce
https://github.com/JonasZ95/NxTypesFail
Types are defined here: https://github.com/JonasZ95/NxTypesFail/blob/main/libs/tablers/src/types/react-table-config.d.ts

1. Clone the repo
2. yarn install
3. yarn nx build table-test 

### Failure Logs
```
ERROR in /home/jonas/work/table-test/libs/tablers/src/lib/table/table.tsx
ERROR in /home/jonas/work/table-test/libs/tablers/src/lib/table/table.tsx(40,54):
TS2339: Property 'getSortByToggleProps' does not exist on type 'HeaderGroup<D>'.

ERROR in /home/jonas/work/table-test/libs/tablers/src/lib/table/table.tsx
ERROR in /home/jonas/work/table-test/libs/tablers/src/lib/table/table.tsx(44,29):
TS2339: Property 'isSorted' does not exist on type 'HeaderGroup<D>'.

ERROR in /home/jonas/work/table-test/libs/tablers/src/lib/table/table.tsx
ERROR in /home/jonas/work/table-test/libs/tablers/src/lib/table/table.tsx(45,32):
TS2339: Property 'isSortedDesc' does not exist on type 'HeaderGroup<D>'.
```

### Environment
```
NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.3.0
  @nrwl/cypress : 10.3.0
  @nrwl/eslint-plugin-nx : 10.3.0
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.0
  @nrwl/linter : 10.3.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 10.3.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.0
  @nrwl/web : 10.3.0
  @nrwl/workspace : 10.3.0
  typescript : 4.0.3

Done in 1.42s.
```

**Comment by gokberkakdeniz** [comment]
I was trying to augment react-router's DefaultRootState. First I taught that I misconfigured tsconfig. After 2 hours, i found this issue...

**Comment by bekos** [comment]
@JonasZ95 unfortunately when building the  `table-test` application, it's own tsconfig doesn't know about the custom typings defined inside the library folder. You will see that if you add `"../../libs/tablers/src/types/react-table-config.d.ts"`, inside the `files` property or just the `"../../libs/tablers/src/types"` on the `include` array of `apps/table-test/tsconfig.app.json` the build succeeds.

I'm afraid that there is not much we can got on our side to automate this 😞  Closing but feel free to reopen if you have any suggestions.

**Comment by AhmedBHameed** [comment]
@bekos 
You just saved my day.
