### ISSUE TITLE
Different style themes on the same module lib

### ISSUE THREAD

**Issue by stedda** [nrwl/nx#3887]
Hi guys, I would like to address a question regarding the usage of the same module, in different applications, but with different styles.

## Description
I do have a single module/lib of Login, that I would like to entirely reuse it in multiple apps (apps are written in Angular 10). The module is lazy loaded in each application. The only difference at the application level for this module are the angular-material theme configurations. 

What I did so far, was to create a core styles lib, that uses default sass variables, that I would like to override at application level.

Do you guys have encountered this use case? How would you solve it/did you solved it?

Code snippets:

1. In my core lib:
```
libs/core/styles/variables.scss:

@import '~@angular/material/theming';

$default-primary: mat-palette(...) !default;
$default-accent: mat-palette(...) !default;
$default-warn: mat-palette(...) !default;
$theme: mat-light-theme(...) !default;


$primary: mat-color(...) !default;
$secondary: mat-color(...) !default;
$green: mat-color(...) !default;
$yellow: mat-color(...) !default;
$red: mat-color(...) !default;

.......
```

This variables.scss file is imported in my login module located in libs/core/login:
```
loginPageComponent.component.scss

@import "libs/core/styles/variables";
```

In app1, I would like for example to use theme 1, witch would have another _variables.scss file that i can import in styles.scss.
In app2, I would like to use theme 2, witch would have another _variables.scss file and so on.

The constraint here is that I would like to configure the theme at app level, without having to import in each core/shared lib module variables from a specific app.

So far I couldn't override the variables without ```ViewEncapsulation.None``` and ```::ng-deep``` that is deprecated already.

Thanks and looking forward for your answers.

**Comment by guilherme-felipe** [comment]
i have the same problem.
