### ISSUE TITLE
Formatting of jest.config.js

### ISSUE THREAD

**Issue by EvtK** [nrwl/nx#3889]
## Current Behavior
After generating new apps or libs, the jest.config.js is expanded with a new entry. This happens on the same line as the last entry.

`"<rootDir>/apps/myfirstapp","<rootDir>/libs/mynewlib"`

## Expected Behavior
It should be formatted on a newline:
```
"<rootDir>/apps/myfirstapp",
"<rootDir>/libs/mynewlib"
```
and use double quotes might be a preference, but i think normally this would be single quotes.

**Comment by EvtK** [comment]
any progress on this one?

**Comment by Cammisuli** [comment]
Hey @EvtK, sorry about a late response to this!

I tried to a new Nest app in a recent version of Nx, and it looks like the Jest config is being formatted properly.

Files should be formatted using whatever prettier configs are in the workspace. So make sure that `.prettierignore` doesn't have the jest config in there. 

If the config isn't in the ignore file, what kind of library or app are you generating?

**Comment by EvtK** [comment]
Hi there @Cammisuli. We are using NX for our corporate mono repo full of Angular apps. So upon generating a new Angular lib, the jest config for this library is not added on a new line on the jest.config.js.

**Comment by Cammisuli** [comment]
What version of Nx are you using?

**Comment by EvtK** [comment]
@Cammisuli I'm running version:     "@nrwl/workspace": "11.1.5",
