### ISSUE TITLE
Modify the behavior of affected:lint script

### ISSUE THREAD

**Issue by gagle** [nrwl/nx#3890]
Could someone clarify the use case for the `affected:lint` script? What we tipically want to achieve in the CI pipeline is to lint only files that have been changed or added, but with this script all the affected apps/libs will be relinted. By using the cache we avoid relinting but I don't understand the motivation to create the `affected:lint` script the way it is now.

If I change code inside a lib, why do I need to lint also the app that depends on it? I should only relint the lib. The "affected graph" for this specific linting case shouldn't propagate to other libs/apps. If I want to still narrow the linting scope and only relint files that have been added/modified then this is out of the scope of Nx, but the first part is something that Nx could improve.

**Comment by statyan** [comment]
I agree, current implementation of `affected:lint` makes small sense. I understand why it was done so - they created a generic way to detect affected projects and then simply run any passed command against the list. But for lint valid behavior would be to get the list of affected files, not projects. And run lint only for the changed files. Assuming code was linted from the project start we need to run lint only in PR build.
In our project we created a simple script to get the changed files from git and run `tslint` against each of them.

**Comment by GrumpyMeow** [comment]
I also see the same behaviour. Unfortunately i'm unable to change this behaviour using targetDefaults.
