### ISSUE TITLE
nx tests execution significantly slower than direct jest execution

### ISSUE THREAD

**Issue by anton-gorbikov** [nrwl/nx#3892]
## Current Behavior
We have a highly modular application. Currently, our `nx` project contains about 400 projects. At some point in time, we've noticed that CI build time started to grow exponentially. Now if we are talking about entire solution tests run it takes about 1.5 hours. We've started to investigate what can be improved and found that if we are trying to run `jest` tests directly without using `nx` (it requires some reconfiguration, but it's not a huge problem) the time reduces from 1.5 hours to 20-30 minutes.

## Expected Behavior
I would expect that `nx` performance should be at least comparable to raw `jest` performance. I found that `nrwl` already has a similar issue for [lint](https://github.com/nrwl/nx/issues/3310). Probably it's related, but not 100% sure.

## Steps to Reproduce

I've tested this behavior using `nx-examples` repository and can confirm that this is applicable to it.

Running `nx` results in 49s:
```zsh
npm run nx run-many -- --target=test --all
```
<img width="639" alt="image" src="https://user-images.githubusercontent.com/5469718/95578203-2cbf9280-0a3c-11eb-8fcd-8cf57dd1e2ea.png">

Running `jest` directly results 12s:
```zsh
npm run jest -- --ci --noStackTrace --silent --maxWorkers=4
```
<img width="258" alt="image" src="https://user-images.githubusercontent.com/5469718/95578319-61cbe500-0a3c-11eb-8802-321c430ff055.png">

The only change I've made is added `"jest": "jest"` to the scripts section of `package.json`.

### Environment
You can verify this behavior using `nx-example` repository.

**Comment by kenptr** [comment]
For me, `nx run myapp:test` finishes in 1.2 seconds, but `nx run myapp:test --watch` each tests finishes in around 5 seconds.

Remedy for watch was `nx run myapp:test --watch --runInBand` (see https://jestjs.io/docs/troubleshooting#tests-are-extremely-slow-on-docker-andor-continuous-integration-ci-server)

or you could add it to your workspace.json

**Comment by yharaskrik** [comment]
I am also experiencing this. In my repo I am getting a 7s speedup by running jest directly. 17s by running `yarn nx test <lib>` and 10s by running `jest` (in the project directory). 

To note: this is with clearing the jest cache before and these timings are total time of command, not "test time" as reported by jest.

Timings:

**Without Jest Cache**
`jest` - 10.802s
`yarn nx test` - 18.14s

**With Jest Cache**
`jest` - 3.607s
`yarn nx test` - 9.85s

```
 Node : 12.20.1
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 12.0.8
  @nrwl/cli : 12.0.8
  @nrwl/cypress : 12.0.8
  @nrwl/devkit : 12.0.8
  @nrwl/eslint-plugin-nx : 12.0.8
  @nrwl/express : 12.0.8
  @nrwl/jest : 12.0.8
  @nrwl/linter : 12.0.8
  @nrwl/nest : 12.0.8
  @nrwl/next : Not Found
  @nrwl/node : 12.0.8
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.8
  @nrwl/web : 12.0.8
  @nrwl/workspace : 12.0.8
  @nrwl/storybook : 12.0.8
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```
