### ISSUE TITLE
feat(ngrx): should install deps when initializing NgRx

### ISSUE THREAD

**Issue by jeffbcross** [nrwl/nx#39]
I'd set up a fresh workspace, created an application, and then added NgRx to a module:

```
ng generate ngrx app --module=apps/my-app/src/app/app.module.ts --onlyEmptyRoot
```

When I ng served it, I got an error because `@ngrx/store-devtools` had been added to my package.json, but not installed. I'd expect it to be installed automatically.

**Comment by vsavkin** [comment]
Waiting for the CLI to support it. In addition to running `npm install` we also want to run the code formatter.

**Comment by vsavkin** [comment]
We changed our setup to include NgRx dependencies into an empty workspace, so this should not be a problem any more.
