### ISSUE TITLE
@nrwl/angular app schematic shouldn't blindly pick workspace name as a prefix by default. 

### ISSUE THREAD

**Issue by k-paxian** [nrwl/nx#3904]
## Current Behavior

Given you have an empty workspace named like "mycompany.com"
Next you are generating angular app  `nx g @nrwl/angular:app myapp` 
if you'll omit setting `prefix` from command line, it will use workspace name as a prefix
which will lead to generated angular component selector "mycompany.com-root" which is an invalid HTML tag
since it has a DOT in it.

## Expected Behavior

Escape it or filter somehow, do not blindly use the workspace name for the prefix.
You are allowing to create workspace name having dots in it, and then you are allowing me to shoot in my leg. 

## Steps to Reproduce

Given you have an empty workspace named like "mycompany.com"
Next you are generating angular app  `nx g @nrwl/angular:app myapp` 
if you'll omit setting `prefix` from command line, it will use workspace name as a prefix
which will lead to generated angular component selector "mycompany.com-root" which is an invalid HTML tag
since it has a DOT in it.

**Comment by FrozenPandaz** [comment]
Interesting find. That should not be a valid workspace name.

**Comment by FrozenPandaz** [comment]
Fixed with https://github.com/nrwl/nx/pull/3928 :tada:
