### ISSUE TITLE
create library nest using schematic take about 5 mintues 

### ISSUE THREAD

**Issue by Areen3** [nrwl/nx#3905]
## Current Behavior

if it executes the create nestjs command, it takes about 5 minutes
command example:
nx generate @ nrwl / nest: library --name = main --buildable --directory = af / be / common --importPath = @ apr / af / be / common / main --no-interactive

## Expected Behavior

to make the command work like any other scheme, i.e. at normal speed

it was in the previous cli version (I don't know before, because I am
new nx user)

## Steps to Reproduce

hm it practically executes this command like any other cli
I was looking at processes, generally the node is laden
I don't know where I can look to help you

as long as you give directions, I'll try to do it all

### Failure Logs

there is no error

### Environment

windows 10, the newest nx installed globally,

**Comment by sgomanf** [comment]
same issue. linux debian based distro (mx linux), node version 12.20.0, nx version 10.4.4 and running in a bash process outside vscode
