### ISSUE TITLE
root is required with run-many

### ISSUE THREAD

**Issue by GrandSchtroumpf** [nrwl/nx#3907]
## Current Behavior
The "root" field is required with `run-many`
```typescript
"examples": {
  "root": "dummy/path",
  "architect": {
    "serve": {
      "builder": "@nrwl/workspace:run-commands",
      "options": {
        "commands": [
          "ng serve example-1",
          "ng serve example-2 --port 4201"
        ],
        "parallel": true
      }
    }
  }
},
```
If I don't set the "root" field `nx run-many target=serve --project=examples` fails with "cannot read length of undefined".

## Expected Behavior
Either root should not be mandatory or provide a clearer error message.

## Steps to Reproduce
1. Create nx workspace
2. Add json example above in workspace.json and update nx.json
3. run `nx run-many target=serve --project=examples`

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs
```
TypeError: Cannot read property 'length' of undefined
    at ***\node_modules\@nrwl\workspace\src\core\project-graph\operators.js:67:57
    at Array.sort (<anonymous>)
    at Object.getSortedProjectNodes (***\node_modules\@nrwl\workspace\src\core\project-graph\operators.js:55:33)
    at new TargetProjectLocator (***\node_modules\@nrwl\workspace\src\core\target-project-locator.js:15:47)
    at buildExplicitTypeScriptDependencies (***\node_modules\@nrwl\workspace\src\core\project-graph\build-dependencies\explicit-project-dependencies.js:8:34)
    at ***\node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:60:41
    at Array.forEach (<anonymous>)
    at buildProjectGraph (***\node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:60:26)
    at Object.createProjectGraph (***\node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:40:30)
    at Object.<anonymous> (***\node_modules\@nrwl\workspace\src\command-line\run-many.js:17:46)
```

### Environment
```
  nx : Not Found
  @nrwl/angular : 10.3.0
  @nrwl/cli : 10.3.0
  @nrwl/cypress : 10.3.0
  @nrwl/eslint-plugin-nx : 10.3.0
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.0
  @nrwl/linter : 10.3.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.3.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.0
  @nrwl/web : 10.3.0
  @nrwl/workspace : 10.3.0
  typescript : 4.0.3
```

**Comment by vsavkin** [comment]
Hi there!

All targets in Nx have to belong to a project. There are no project-less targets. We discussed this feature several times, but it was never high enough priority. We will examine it again.

**Comment by GrandSchtroumpf** [comment]
I think it's ok not to support "project-less" targets. Then maybe improving the error message would help debugging. Something like : "The keys 'projectType' & 'root' are required".

**Comment by dongyuwei** [comment]
project-less targets will be helpful for global tasks, for example lint(eslint and stylelint), we can config only one lint for all projects in workspace.
