### ISSUE TITLE
Migrating a Yarn workspace from a traditional Angular CLI workspace to an Nx fails

### ISSUE THREAD

**Issue by ahasall** [nrwl/nx#3908]
## Current Behavior

When trying to migrate a Yarn workspace from a traditional Angular CLI workspace to an Nx workspace, it fails with the following error:

```bash
Installing packages for tooling via yarn.
An unhandled exception occurred: error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
Package install failed, see above.
See "/private/var/folders/5s/2g7_c5f120d9t9f280skfw2c0000gn/T/ng-xfBnhp/angular-errors.log" for further details
```

## Expected Behavior

I expect to be able to migrate my traditional Angular CLI workspace to Nx even if I am using Yarn workspaces.

### Generate a new Angular CLI workspace

```bash
ng new my-app --defaults --package-manager=yarn
```

### Make it a Yarn workspace

Add `"workspaces": []` to the `package.json` file.

### Try migrating to an Nx workspace

```bash
ng add @nrwl/workspace
```

**Comment by alfaproject** [comment]
I'm also using yarn workspaces (without Angular) and I'm getting hit by this error. In my case, I was just trying to update:

```shell
# yarn update
yarn run v1.22.5
$ nx migrate latest
$ /Users/alfa/Documents/the-mill/lambda-infra.nosync/node_modules/.bin/tao migrate latest
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest

 ERROR  The migrate command failed. Try the following to migrate your workspace:

> yarn add --dev @nrwl/workspace@latest
> nx migrate @nrwl/workspace@latest --from="@nrwl/workspace@10.4.2"
This will use the newest version of the migrate functionality, which might have your issue resolved.
----------------------------------------------------------------------------------------------------
Command failed: yarn add @nrwl/workspace@latest --prefix=/var/folders/2b/wfy2bq8s1h18f3sd9rdnn9cc0000gn/T/tmp-11171N8lO7iS6qyP2
error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).

error Command failed with exit code 1.
```

**Comment by chihab** [comment]
As a workaround you can create a `.yarnrc ` file in your root yarn workspace and set the flag to `--ignore-workspace-root-check ` to  `true `

**.yarnrc**
--ignore-workspace-root-check true

**Comment by chihab** [comment]
Actually, any `ng add`, not only `@nrwl/workspace`, that tries to update package.json would eventually fail (`yarn ng add @angular/material` for example)

`ng add` CLI command should either handle that (conditionally/always pass -W when yarn workspace detected) or maybe accept an extraArgs option (currently used for registry only apparently).

On the other hand, `yarn ng add @angular/pwa` works fine because `@angular/pwa` is not saved (ng-add: {save: false} in the schematics' package.json) and the thing is that it calls `service-worker` external schematics which does save the dependency without any problem (possible workaround for @nx/workspace?)

**Comment by chihab** [comment]
The `.yarnrc` config above is the one suggested in an Angular CLI related issue: https://github.com/angular/angular-cli/issues/10795

The current issue should probably be closed.

**Comment by philipjfulcher** [comment]
@chihab thanks for your contribution! The .yarnrc looks like the best bet for managing this issue. I'll close this bug, anyone with a similar issue should use the .yarnrc solution above.
