### ISSUE TITLE
nx doesn't do correct node resolution

### ISSUE THREAD

**Issue by mhamri** [nrwl/nx#3909]
https://github.com/angular/angular-cli/issues/3864

it's like Deja Vu, this issue just recently resolved in angular cli, now nx suffer from the same. 

when node_module is in upper folder (mainly because of docker) the nx or any cli which is invoked by npm, should be able to traverse the folders and find the node_modules and use that folder as the node_module.

## Current Behavior

```
/home/app # npm start -- playground

> revaedge@0.0.0 start /home/app
> nx serve "playground"


>  NX   ERROR  Could not find Nx in this workspace.

  To convert an Angular workspace to Nx run: ng add @nrwl/workspace
```

## Expected Behavior

work like any other correct nodejs app. resolve to upper folder

## Steps to Reproduce

move node_module to upper folder and try to run npm start. 

### Environment

can't because nx doesn't work as it should 
```
/home/app # npx nx report

>  NX   ERROR  Could not find Nx in this workspace.

  To convert an Angular workspace to Nx run: ng add @nrwl/workspace
```

**Comment by vsavkin** [comment]
@bekos do you think your work on yarn2 addressed this?

**Comment by bekos** [comment]
Yes, it should. @mhamri from the error message you get, it seems that you are using an older version of Nx. Can you update your **global** packages to _latest_ and try again?

**Comment by mhamri** [comment]
@bekos let me try, I will update in here

**Comment by mhamri** [comment]
@bekos it exits without any error 

![image](https://user-images.githubusercontent.com/8991783/97296679-f1babd00-188b-11eb-8bc0-7e1da0c74cf4.png)


in the picture, i'm in `/home/node/app` where the node_modules is in `/home/node` (I did `ls` and `pwd` to give you an idea about hte structure)

then if I go to app folder and run `npm start` which translate to `nx serve` then it does nothing. 

just note that I don't have node install globally. so meaning the npm is being read from the `/home/node/node_modules`

**Comment by bekos** [comment]
@mhamri seems like it cannot locate the workspace directory, and probably related to https://github.com/nrwl/nx/issues/3484 which is more complicated. I will try to take a stub on this and let you know.
