### ISSUE TITLE
generate command JavaScript override not working

### ISSUE THREAD

**Issue by briermay** [nrwl/nx#3912]
## Current Behavior

nx generate @nrwl/node:app myapp --js
Could not match option 'js' to the @nrwl/node:application schema.

## Expected Behavior

npx generate to create the app with JavaScript instead of TypeScript

Is this a regression? .i.e Did this used to be the behavior at one point? 

No idea first time using this but as per your own documentation:
"If you prefer JavaScript to TypeScript, pass --js to any nx g ... command. Everything else works the same way whether you use JavaScript or TypeScript. Read More" <- also read more link broken

## Steps to Reproduce

simply pass --js to any generate command

**Comment by kevinfaguiar-tc** [comment]
express plugin doesn't has the --js option too :(

**Comment by briermay** [comment]
that's ok I figured out a work around. if you go to the workspace.json file it has 3 references upon creating any new app/library to a .ts file. the main.ts  and the 2 files in the environments folder. if you simply rename the references in the workspace.json file and then rename those to .js it works fine. its a pain but its a usable workaround.

**Comment by vsavkin** [comment]
Every plugin has to support `--js` directly. We have two PRs in progress that make it work for more plugins (e.g., https://github.com/nrwl/nx/pull/3706).

**Comment by ockenden** [comment]
I was looking to use this for my next project, but again `--js` is not working. Seems odd to force people to use ts over JS. I would have assumed `--ts` would have been the smarter option to flag.

Looks like I'll have to find a different solution - maybe I'll get to use this some time in the future when this issue is resolved but sadly it doesn't seem like a priority :(

**Comment by vsavkin** [comment]
I'm going to close this since generating node and express apps supported --js since Nov. The `create-nx-workspace` command doesn't support --js, but i think it's a separate issue from the one reported here. I'm going to discuss with the core team, so hopefully we can land it by April.

Thank you!
