### ISSUE TITLE
skipFormat angular application schematic's option is not passed to formatFiles rule

### ISSUE THREAD

**Issue by artaommahe** [nrwl/nx#3914]
## Current Behavior
Angular application schematic has a `skipFormat` option (https://github.com/nrwl/nx/blob/master/packages/angular/src/schematics/application/schema.json#L88) but it's not passed to the `formatFiles` rule (that accepts such option https://github.com/nrwl/nx/blob/b55a1a96dd74fc1ecc209eb4f42959933102bd75/packages/workspace/src/utils/rules/format-files.ts#L19) so files are always formatted.

## Expected Behavior
`skipFormat` is passed to the `formatFiles` rule

## Steps to Reproduce

- add some formatting mess to e.x. root tslint.json
- run angular application generating command with `--skipFormat=true`
- `tslint.json` is formated

### Environment

```
  nx : Not Found
  @nrwl/angular : 10.2.1
  @nrwl/cli : 10.2.1
  @nrwl/cypress : 10.2.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.2.1
  @nrwl/linter : 10.2.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.2.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.2.1
  @nrwl/web : Not Found
  @nrwl/workspace : 10.2.1
  typescript : 3.9.7
```

**Comment by isaacplmann** [comment]
@sandikbarr is taking a look at this

**Comment by isaacplmann** [comment]
Should not have been closed. It was accidentally linked to an unrelated pr
