### ISSUE TITLE
When space in workspace path, ERROR

### ISSUE THREAD

**Issue by 1cm** [nrwl/nx#3919]
Hello NX
I notice that if i want to create new workspace with npx create-nx-workspace@latest in the folder in my PC on location for example D:\Visual Studio 2008\Projects\nameless error occurs

ERROR! nameless/nx.json already exists.
ERROR! nameless/tsconfig.base.json already exists.
ERROR! nameless/package.json already exists.
ERROR! nameless/README.md already exists.
ERROR! nameless/.editorconfig already exists.
ERROR! nameless/.gitignore already exists.
ERROR! nameless/.prettierignore already exists.
ERROR! nameless/.prettierrc already exists.
ERROR! nameless/angular.json already exists.
ERROR! nameless/decorate-angular-cli.js already exists.
ERROR! nameless/tools/tsconfig.tools.json already exists.
ERROR! nameless/tools/schematics/.gitkeep already exists.
ERROR! nameless/.vscode/extensions.json already exists.
ERROR! nameless/apps/.gitkeep already exists.
ERROR! nameless/libs/.gitkeep already exists.
The Schematic workflow failed. See above.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
(node:11344) UnhandledPromiseRejectionWarning: Error: Command failed: yarn tao new nameless  --preset="angular" --appName="virmani" --style="scss" --linter="tslint" --interactive=false --collection=C:\Users\ADMINI~1\AppData\Local\Temp\1\tmp-113443bk6SGhD4Fru\node_modules\@nrwl\workspace\collection.json --cli=ng --nxWorkspaceRoot=D:\Visual Studio 2008\Projects\nameless
    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:647:15)
    at createApp (C:\Users\Administrator\AppData\Roaming\npm-cache\_npx\11344\node_modules\create-nx-workspace\bin\create-nx-workspace.js:424:21)
    at C:\Users\Administrator\AppData\Roaming\npm-cache\_npx\11344\node_modules\create-nx-workspace\bin\create-nx-workspace.js:92:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11344) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by duard** [comment]
same error here

**Comment by FrozenPandaz** [comment]
Hey @bekos I see you have a commit, please submit a pull request when you are ready :smile:

**Comment by imeakpan** [comment]
How do we get around this error in the meantime? Trying to create an nx workspace.

**Comment by ev45ive** [comment]
Why is it closed? in "@nrwl/cli": "10.4.4" and in create-nx-workspaces, **it's still not fixed.**

**Comment by agalazis** [comment]
@ev45ive  @vsavkin  I think it was closed by accident all the reference to code that fixes are in third party repo that had no pr nor merged back to this repo I guess
