### ISSUE TITLE
support nx cached:*

### ISSUE THREAD

**Issue by zodiac1214** [nrwl/nx#3924]
## Description

similar to `nx affected:apps` `nx affected:libs`, we should also have `nx cached:apps/libs`
## Motivation

in a very large project, even with distributed CI system and `nx run-many`, there are times where you have to test/lint a large number of projects. Let's say you use 10 build agents for 100 affected libs, and there is a typo in one of the lib which failed lint. A rerun would still using 10 build agents even though 99 affected libs will just use cached output. The problem here is that, you are taking/paying unnecessary 9 build agents which you don't have to run. if we have a way to tell whether a project has cached or not, then for people like me who has a limited budget on build agents, i can use nx cached:apps to de-duplicate the list from nx affected:apps. So in above scenario, after i fixed the typo, i don't have to run 9 agents for projects that will not run any lint at all. instead, only the one lib will need to run on one agent. (assuming that lib is not a dependency of any other libs)
## Suggested Implementation

we are creating task object [here](https://github.com/nrwl/nx/blob/master/packages/workspace/src/command-line/print-affected.ts#L18), i suggest that we also call hasher.hashTasks() such that we can check whether a project has cached or not.

**Comment by zodiac1214** [comment]
@atifsyedali

**Comment by DominikB2014** [comment]
I am running into the same issue using GitHub actions for distributed CI. 
I have posted a similar issue https://github.com/nrwl/nx/issues/4709

I believe the issue with `nx cached:apps` would be that the caching is done at a target level not an app level. So nx cached apps may not make the most sense.

Say we have 3 apps, each with a build, test, lint and deploy target. When a pull request is opened we run the build, test, lint on each affected app in CI. Notice deploy has not ran. 

With your approach, nx cached:apps would not capture the fact that only build, test and lint were cached, but deploy was not. Hence if we wanted to run deploy on all apps outputted with nx cached:apps, it would not be possible, we would need nx cached:apps --target=deploy

To add to this, what if build and test have passed for a single app, but lint failed. Does your proposal assume that every target has passed for a single app for it to be considered cached?

Hope that make sense, let me know if there is anything incorrect here, thanks.
