### ISSUE TITLE
nx-plugin can't compile tests when generated from inside a workspace

### ISSUE THREAD

**Issue by TomzBench** [nrwl/nx#3926]
## Current Behavior
When creating a nx-plugin inside of a clean nx-workspace, the nx command to test the nx-plugin will fail.

## Expected Behavior
I expect that a fresh workspace with a new nx-plugin project should have passing tests. And that the test runner when running the test should be able to build the test

## Steps to Reproduce
```bash
npx create-nx-workspace foo
cd foo
yarn -D @nrwl/nx-plugin
nx g @nrwl/nx-plugin:plugin --name=example --directory=plugins --importPath="@tomzbench/nx-plugin-example"
nx run plugins-example:build # <--- Will work fine
nx run plugins-example:test  # < --- Will fail
```

### Failure Logs
Here is a repository that will produce failure: https://github.com/TomzBench/nx-examples/tree/plugin-test-fail

```
FAIL plugins-example libs/plugins/example/src/builders/build/builder.spec.ts
Job name "@nx-example/plugins-example:build" does not exist # <--- It seems to want to use a import path instead of local path
```

### Environment
```
>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : 10.3.1-beta.1
  @nrwl/cli : 10.3.1-beta.1
  @nrwl/cypress : 10.3.1-beta.1
  @nrwl/eslint-plugin-nx : 10.3.1-beta.1
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.1-beta.1
  @nrwl/linter : 10.3.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.3.1
  @nrwl/react : 10.3.1-beta.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.1-beta.1
  @nrwl/web : 10.3.1-beta.1
  @nrwl/workspace : 10.3.1-beta.1
  typescript : 4.0.3
```

(EDIT - e2e tests will to build OK, but the plugin project `:test` target will fail)

**Comment by trumbitta** [comment]
@TomzBench FWIW it works if you don't specify a custom directory (i.e. try omitting `--directory=plugins`

**Comment by trumbitta** [comment]
It also works if you edit the spec file deleting the `plugins` part:

```ts
    const run = await architect.scheduleBuilder('@foo/example:build', options);
```

If think I could put together a PR, but no promises: it depends on how much time the kid decides to concede :D

**Comment by trumbitta** [comment]
No need for a PR, it seems @vsavkin worked around this issue while reforging the world and renaming things (I dig the new names! Way clearer than the old angular-ish ones!).

https://github.com/nrwl/nx/commits/master/packages/nx-plugin/src/schematics

@TomzBench is the workaround enough for you?  
This one: https://github.com/nrwl/nx/issues/3926#issuecomment-735258823

**Comment by TomzBench** [comment]
It not big deal for me personally. It is easy to fix the compile errors after you run the code generator. When using any of the code generators, I first run build:test commands to know i'm starting from a sane place before making changes.  So it is kind of a bad feeling when the generated code doesn't compile. Somebody new to nx might think something is wrong so it's good to keep the con gen stuff compiling.  So that is the reason for posting the issue.
