### ISSUE TITLE
Nx Cloud review: test failed incomplete / truncated

### ISSUE THREAD

**Issue by dbigintonpro** [nrwl/nx#3931]
I am reviewing and testing the Nx Cloud feature and was interested to see how the results are displayed.  I updated my workspace to the latest package versions, then on running `nx run-many --target=build --all --scan` noted a failure.  I am interested to see how this would be presented in Nx Cloud, but the results were of no use. For some reason it seems to have only captured a partial build process and TRUNCATED the results.  The actual test in question wasn't provided.

![image](https://user-images.githubusercontent.com/16273691/96324399-b1d41a00-0fef-11eb-94c4-b0cb8449ef27.png)

Is there anything I need to be doing to resolve this, as I'd like to evaluate the solution and potentially integrate it into our SDLC and CI/CD process in the near future. I could see an immediate benefit to the distributed caching mechanism across our team, and this would certainly, alone be of great benefit to us.

I look forward to hearing your thoughts on the issue I am facing.  Many thanks in advance.

**Comment by vsavkin** [comment]
Currently, we truncate the output of every task (we only send the first 50k characters). This reason why the output is so long is that we capture both stdout and stderr, and stderr creates a lot of output. We have a few solutions in mind, and we will release something fixing the issue shortly.
