### ISSUE TITLE
Jest is slow for angular compared with headless chrome

### ISSUE THREAD

**Issue by vespertilian** [nrwl/nx#3936]
## Jest is slow

So I started to use Jest as it was the default that was set up, and people say good things. However, I noticed some of the first few tests I have created have been much slower than I expected, based on my previous experience. 

To double-check this I loaded up two vanilla angular projects to see if it's NX (does not seem to be) jest is just much slower even in simple angular CLI apps even for the sample specs. Like twice as slow for each test. 

**Is this an issue for anyone else?** 

Also, I am a bit reluctant to move away from Karma, Jasmine and Protractor as Jest and Cypress are not very useful for cross-browser testing. A bit sad to give that up. I like the idea of multiple vendors on the web.

<img width="781" alt="slow-jest" src="https://user-images.githubusercontent.com/441418/96411593-6c545e80-1234-11eb-87da-efd7e1cb6cd4.png">

**Comment by ubergeoff** [comment]
This could be due to a couple of (possible) factors.

As for me, I have always noticed Jest to be much faster when compared to karma.

However, I have (in the past) - setup my tests in a incorrect manner - that made Jest run slower.

1) What OS are you running your tests on.
2) Do you make use of any test Mock classes..?

**Comment by vespertilian** [comment]
@ubergeoff 

Thanks for your response. 

I have MacOS 10.15.7, jest can run fast because it parallelises specs. However, each spec seems to run slower. Yes, I do mock as much as I can for component tests using ng-mocks. 

Here are some sample repo's 
https://github.com/vespertilian/angular-test-app-jest
https://github.com/vespertilian/angular-test-app-jasmine'

These are just Angular CLI projects, but they seem to match my timings from NX which I just used the default Jest setup. 

I added timing outputs to each spec. As you can see lots of the Jest specs are up to twice as slow. The previous image was using wallaby JS. 

<img width="2530" alt="Screen Shot 2020-11-01 at 2 44 30 pm" src="https://user-images.githubusercontent.com/441418/97794738-ccde9500-1c51-11eb-863d-672d56ee89d8.png">

**Comment by tamascsaba** [comment]
I think i would be nice to repoen, because it is a valid problem on bigger test environment
