### ISSUE TITLE
Changes to angular.json/workspace.json should be project scoped

### ISSUE THREAD

**Issue by DominikB2014** [nrwl/nx#3939]
## Description
When we make a change to angular.json, whether that change is the generation of a new app or adding a style to a particular project, nx treats that as all apps being affected. It would be great if we can scope changes to angular.json to a particular app automatically (without manually doing this in nx.json).

## Motivation
Nx treats all apps as being affected when in reality they are not all affected in every case. This increases the time it takes to run a specific target on all affected apps in ci

## Suggested Implementation 
If I make a make a change to a particular project in angular.json, only that project should be affected (along with any dependencies of course). I imagine this can be done by parsing the git diff command on angular.json, determing which lines have changed in angular.json and then determing which project those lines fall under. (Only issue is here is a change in formatting would trigger affected, so maybe parsing the angular.json from the base and head would be a better approach)

**Comment by FrozenPandaz** [comment]
Good news, this is actually already a feature of Nx but it is disabled by default. If you would like to enable this for your workspace, remove the `implicitDependencies` in `nx.json`. Example commit: https://github.com/nrwl/nx-examples/commit/98a8a1688b23a443087e46fb69107f5fbfd282ad#diff-15552e50b1b7c05b05b7ffe08ee47b5ed62b8d2039229c58972a42fd22a7381c

We plan to enable this by default in the near future.

**Comment by DominikB2014** [comment]
Closing this issue, I've been testing this, appears to work perfectly.
