### ISSUE TITLE
[dev issue] e2e tests on Windows doesn't work

### ISSUE THREAD

**Issue by noelmace** [nrwl/nx#394]
**Type**

This is a "contributing" / documentation issue.

**Description**

There is a lot of issues when trying to contribute with Windows. Even if I suppose the support of the dev scripts for Windows isn't a priority, maybe some of you managed to solve this before me, which would permit me to had this informations in CONTRIBUTING.md.

I found some workarounds for build, link and test, but I couldn't find any for e2e.

**Version**
On master (test on: 4edc8e6c8b0801a13a)

**Related issues**
For e2e, there is an issue with jest on Windows : https://github.com/facebook/jest/issues/2381#issuecomment-377824552

I get this issue when I try to test my current development on the nx command-line : https://github.com/nrwl/nx/issues/369 (https://github.com/noelmace/nx/tree/f5dc49b1aad87258b636c8fa74d2550f032f562c/)

**Details**
```
$ ./scripts/e2e.sh command-line

> @nrwl/nx-source@0.9.0 build D:\git\gh\nx
> ./scripts/build.sh

'.' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nrwl/nx-source@0.9.0 build: `./scripts/build.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nrwl/nx-source@0.9.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\N2632888\AppData\Roaming\npm-cache\_logs\2018-04-01T23_29_29_853Z-debug.log
npx: installed 1 in 2.636s
Path must be a string. Received undefined
D:\git\gh\nx\node_modules\ng-packagr\cli\main.js
Building Angular Package
Building entry point '@nrwl/nx'
Cleaning build directory
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc
Bundling to FESM15
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Relocating source maps
Copying staged files
Writing package metadata
Built @nrwl/nx
Building entry point '@nrwl/nx/testing'
Cleaning build directory
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc
Bundling to FESM15
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Relocating source maps
Copying staged files
Writing package metadata
Built @nrwl/nx/testing
Built Angular Package!
- from: D:\git\gh\nx\packages\nx
- to:   D:\git\gh\nx\packages\nx\dist
No tests found
In D:\git\gh\nx
  295 files checked.
  testMatch: **/__tests__/**/*.js?(x),**/?(*.)(spec|test).js?(x) - 45 matches
  testPathIgnorePatterns: \\node_modules\\ - 295 matches
Pattern: "./build/e2e/schematics/command-line.test.js" - 0 matches
```

Even if I try to directly run jest (after building) : 
```
$ ./node_modules/.bin/jest build/e2e/schematics/command-line.test.js
No tests found
In D:\git\gh\nx
  295 files checked.
  testMatch: **/__tests__/**/*.js?(x),**/?(*.)(spec|test).js?(x) - 45 matches
  testPathIgnorePatterns: \\node_modules\\ - 295 matches
Pattern: "build/e2e/schematics/command-line.test.js" - 0 matches
```
Same error with all schematics e2e tests : 
```
$ ./node_modules/.bin/jest build/e2e/schematics/
No tests found
In D:\git\gh\nx
  295 files checked.
  testMatch: **/__tests__/**/*.js?(x),**/?(*.)(spec|test).js?(x) - 45 matches
  testPathIgnorePatterns: \\node_modules\\ - 295 matches
Pattern: "build/e2e/schematics/" - 0 matches
```

Yet, everthing is ok in build/e2e/schematics/*.test.js files.

**Comment by skydever** [comment]
... I am using the [ubuntu](https://www.microsoft.com/en-us/store/p/ubuntu/9nblggh4msv6) app from the microsoft store to run the e2e tests locally under windows, and I also activated Travis on my fork repo of nx to verify changes before creating a PR at the official repo. not exactly what you are looking for I suppose, but it is a workaround ...

**Comment by noelmace** [comment]
@skydever In fact, this is exactly the kind of information I'm looking for;) Support for dev environment on Windows is not important enough to rethink the build process and dependencies. I only created this issue in order to get feedbacks from other contributors. In the mean time, I started to use Docker to run e2e test.

**Comment by noelmace** [comment]
My feedback : if we talk about workarounds, the only good solution is ... to move to Linux ;-) VirtualBox shared folder doesn't support symlink on windows, which make it impossible to use yarn without --no-bin-path, and this project need bin paths. Another solution is to use ssh with rmate (if you use VS Code, like I do) like explained in https://medium.com/@prtdomingo/editing-files-in-your-linux-virtual-machine-made-a-lot-easier-with-remote-vscode-6bb98d0639a4, but you could only edit one file at a time ... so, for now, when I have to work on Windows, I use a VM with everything (including VS Code) in it, which is just horrible. Of course, I set travis on my fork like @skydever, but for some cases it's not enough.

So, to really resolve this issue (I'm not closing it since it's not really resolved, even if it's not important), a solution could be to rewrite all the scripts with node instead of bash, with care for Windows compatibility. For now, I don't have the time for that, especially because I don't really care about Windows ;-) But if someone want to do it, it would be a pleasure to help.

**Comment by noelmace** [comment]
So sorry about that, but as I said, as I'm not a big windows fan, my "workaround" was to use a Linux virtual machine. So, I don't think (even if I'm the one who opened this issue in the first place) I could be of any help on windows support, but I could indeed had a some informations in CONTRIBUTING about "what you should not try to do", like using windows or npm link :slightly_smiling_face: Tell me if you think this could be of any interest.
