### ISSUE TITLE
Not able to run nx serve on nestjs application. Error: Cannot find module

### ISSUE THREAD

**Issue by patryk-zielinski93** [nrwl/nx#3943]
## Current Behavior
I am not able to run nx serve on nestjs application. Command throws:
Error: Cannot find module '@my-app/shared/server/domain'

## Expected Behavior
It should work

## Steps to Reproduce
It is hard to say how to reproduce this issue, because it happens randomly on libs generated with nx. Sometimes removing node_modules, dist directory and running nx serve again helps. Perhaps this is a problem with generating the application because the generated main.js file tries to import the module via an alias, not a file path as in other modules.
```
/* harmony import */ var _my-app_my-app_booking_server_domain__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! @my-app/my-app/booking/server/domain */ "./libs/my-app/booking/server/domain/src/index.ts");
/* harmony import */ var _my-app_shared_server_domain__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! @my-app/shared/server/domain */ "@my-app/shared/server/domain");
```

### Environment
   nx : Not Found
  @nrwl/angular : 10.2.1
  @nrwl/cli : 10.2.1
  @nrwl/cypress : 10.2.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.2.1
  @nrwl/linter : 10.2.1
  @nrwl/nest : 10.2.1
  @nrwl/next : Not Found
  @nrwl/node : 10.2.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.2.1
  @nrwl/web : Not Found
  @nrwl/workspace : 10.2.1
  typescript : 3.9.7

**Comment by patryk-zielinski93** [comment]
After few nx serve reruns and dist directory removals it compiles properly:
```
/* harmony import */ var _my_app_shared_server_domain__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! @my-app/shared/server/domain */ "./libs/shared/server/domain/src/index.ts");
```
Maybe there is some race condition?

**Comment by Cammisuli** [comment]
Hi @patryk-zielinski93 , sorry for taking a while and not replying sooner, but maybe you could try with the latest version of Nx? 

And if possible try and get the repro for us?
