### ISSUE TITLE
nx lint with --quiet not hiding warnings

### ISSUE THREAD

**Issue by mbaird4** [nrwl/nx#3946]
## Current Behavior
When running `nx lint {project} --quiet`, or when adding `quiet: true` to the workspace config for the lint behaviour, I am still seeing all the warnings in the output

## Expected Behavior

when running with `quiet`, warnings should be hidden from the output logs when linting

## Steps to Reproduce

In .eslintrc.json, set up at least one rule that causes a warning (doesn't matter whether basic eslint or typescript-eslint type rule)
in project, write code that violates the warning rule
run `nx lint {project} --quiet`

### Environment

  nx : Not Found
  @nrwl/angular : 10.3.1
  @nrwl/cli : 10.3.1
  @nrwl/cypress : 10.3.1
  @nrwl/eslint-plugin-nx : 10.3.1
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.1
  @nrwl/linter : 10.3.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.3.1
  @nrwl/react : 10.3.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.1
  @nrwl/web : 10.3.1
  @nrwl/workspace : 10.3.1
  typescript : 3.9.7

**Comment by perjerz** [comment]
I have the same behavior.

**Environment**

Angular CLI: 10.1.7
Node: 12.18.0
OS: darwin x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: <error>

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1001.6
@angular-devkit/build-angular      0.1001.7
@angular-devkit/core               10.1.6
@angular-devkit/schematics         10.1.7
@angular/cdk                       10.2.5
@angular/cli                       10.1.7
@angular/material                  10.2.5
@angular/material-moment-adapter   10.2.5
@schematics/angular                10.1.7
@schematics/update                 0.1001.7
rxjs                               6.6.3
typescript                         4.0.3

**package.json**
...
    "@nrwl/angular": "10.3.3",
    "@nrwl/cli": "^10.3.3",
    "@nrwl/cypress": "10.3.3",
    "@nrwl/eslint-plugin-nx": "^10.3.3",
    "@nrwl/express": "10.3.3",
    "@nrwl/jest": "10.3.3",
    "@nrwl/next": "10.3.3",
    "@nrwl/node": "10.3.3",
    "@nrwl/react": "10.3.3",
    "@nrwl/storybook": "10.3.3",
    "@nrwl/web": "10.3.3",
    "@nrwl/workspace": "10.3.3",
...

**Comment by perjerz** [comment]
I think I know why it happen.
We use "@nrwl/linter:eslint" builder from source code version 10.3.3. It does not implement options "quiet"
https://github.com/nrwl/nx/blob/10.3.x/packages/linter/src/builders/eslint/utility/eslint-utils.ts#L20

But in "@nrwl/linter:linter builder that used eslint already implement options "quiet"
https://github.com/nrwl/nx/blob/10.3.x/packages/linter/src/builders/lint/utility/eslint-utils.ts#L67

**Comment by un33k** [comment]
@mbaird4 I have raised an issue with Eslint to have quiet option available via .eslintrc.json.  https://github.com/eslint/eslint/issues/13898

**Comment by arabull** [comment]
Sorry for all the noise. It was all an effort to get my commit message correct. 🤦
