### ISSUE TITLE
Visual Studio Code Auto Attach debugging not working with NestJS

### ISSUE THREAD

**Issue by rhyek** [nrwl/nx#3948]
## Bug Report

Reference: nestjs/nest#5590.

## Current behavior
In a new nx project with nest preset, after setting a breakpoint somewhere and configuring Visual Studio Code's `Debug -> JavaScript -> Auto Attach Filter` with several configurations, the application will not start and the breakpoint will not hit when running `nx serve`. It does not matter wether I enable or disable `Debug -> JavaScript -> Use Preview`.

Different values for the auto attach setting have the following results:
`always`
![image](https://user-images.githubusercontent.com/702922/96661327-07b70380-1309-11eb-914f-2cb534b7215b.png)

`smart`
![image](https://user-images.githubusercontent.com/702922/96661381-23220e80-1309-11eb-822d-51b0c2f78231.png)

`onlyWithFlag`
![image](https://user-images.githubusercontent.com/702922/96661429-45b42780-1309-11eb-8792-e40630b2fc39.png)

`disabled`
![image](https://user-images.githubusercontent.com/702922/96661469-59f82480-1309-11eb-87e9-c5e46a37f7ad.png)

## Expected behavior
The application should start and breakpoints should break processing. This was working up until recently. I am not entirely sure, but I believe up until at least 1 month ago it was working fine.

Having a project with *just* NestJS does work with Visual Studio Code's auto attach debugging.

## Environment

<pre><code>
Nest version: 7.4.4

 
For Tooling issues:
- Node version: 14.13.1
- Platform: Mac

Others:

    "@nrwl/cli": "10.3.1",
    "@nrwl/eslint-plugin-nx": "10.3.1",
    "@nrwl/jest": "10.3.1",
    "@nrwl/nest": "10.3.1",
    "@nrwl/node": "10.3.1",
</code>
</pre>

**Comment by aca-pulco** [comment]
@vsavkin  Please tell me when can I wait for a fix on this bug?

**Comment by florianmrz** [comment]
I'm facing the same issue with @nrwl/node v11.0.2, however, I might've found some additional information.

It possibly has something to do with the inspect argument being passed down to the child process, see this [StackOverflow question](https://stackoverflow.com/questions/50885128/how-can-i-debug-a-child-process-fork-process-from-visual-studio-code/50885129#50885129).

https://github.com/nrwl/nx/blob/075fe9446b16e4e5c8bba78e4cb85888e5e50fe9/packages/node/src/builders/execute/execute.impl.ts#L75-L77


Since the whole `nx serve` process was being debugged, setting the "inspect" option to `false` in `workspace.json` worked for me, as the spawned child process would still be able to break on any breakpoints:

```
# workspace.json        
"serve": {
  "builder": "@nrwl/node:execute",
  "options": {
    "buildTarget": "api:build",
    "inspect": false
  }
},
```

Afterwards, using both the `JavaScript Debug Terminal` as well as the [Auto Attach Feature](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_auto-attach-smart-patterns) with the following patterns worked for me:
```
# VSCode Settings (JSON)
"debug.javascript.autoAttachFilter": "smart",
"debug.javascript.autoAttachSmartPattern": [
  "!**/{node_modules,npm-global,.yarn,.nvm}/**",
  "**/$KNOWN_TOOLS$/**",
  "'**/node_modules/@nrwl/node/**'"
],
```

**Comment by bobbylight** [comment]
Gentle nudge.  I'm seeing this behavior with @nrwl/node 11.5.1.  Auto-attach does not detect and connect a debugger when I run the following in my monorepo:

```bash
nx serve
```

However it _does_ do the right thing when I launch the built app via node directly:

```bash
node --inspect=9229 dist/apps/my-nest-app/main.js
```

**Comment by bobbylight** [comment]
VS Code's auto-attach seems to work for me on Windows if I have the terminal set to cmd.exe, but not when I've set it to Git Bash.  Perhaps this is a clue?  Like many developers, I'd really prefer to use Git Bash whenever possible.

**Comment by jasonkenneth** [comment]
Ditto here running nx in wsl2/ubuntu20.04. We just upgraded our project from nx v9.x to v11.x. Is it the `./decorate-angular-cli.js` causing us issues?

`nx report` results:
  Node : 14.16.1
  OS   : linux x64
  npm  : 6.14.120

  nx : Not Found
  @nrwl/angular : 11.6.3
  @nrwl/cli : 11.6.3
  @nrwl/cypress : 11.6.3
  @nrwl/devkit : 11.6.3
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.6.3
  @nrwl/linter : 11.6.3
  @nrwl/nest : 11.6.3
  @nrwl/next : Not Found
  @nrwl/node : 11.6.3
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.6.3
  @nrwl/web : Not Found
  @nrwl/workspace : 11.6.3
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.0.7

**Comment by ethan-deng** [comment]
Just switch to "command prompt" to run the command will work. "powershell" won't work.
