### ISSUE TITLE
Dependency webpack-subresource-integrity has security issue under version 1.5.1

### ISSUE THREAD

**Issue by InsaLili** [nrwl/nx#3958]
## Current Behavior
Current version `"webpack-subresource-integrity": "1.1.0-rc.6"`

webpack-subresource-integrity reports security issue: Tags are injected with integrity="undefined" on v1.5.0

Ref: https://github.com/waysact/webpack-subresource-integrity/issues/131

This issue is patched in version 1.5.1.

## Expected Behavior
webpack-subresource-integrity version should be >= 1.5.1

**Comment by vsavkin** [comment]
The issue has been fixed here: 1b1ddfa3bb799f7466854faafb5108d674da6e8d
