### ISSUE TITLE
Problem with configuration of next.js projects

### ISSUE THREAD

**Issue by DarekTechTailorCo** [nrwl/nx#3961]
# Bug report
Disabling x-powered-by does not work in projects with next.js

## Describe the bug
After adding `poweredByHeader: false` to `<app>/next.config.js`, 'X-Powered-By' response header changes its value from 'Nest.js' to 'Express' instead of being deleted.

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
A repository has been prepared in which the problem can be reproduced:
https://github.com/DarekTechTailorCo/nxdev-nextjs-config-issue

configuration:
https://github.com/DarekTechTailorCo/nxdev-nextjs-config-issue/blob/master/apps/my-app/next.config.js#L7

Application with the above configuration is launched via `yarn start`.

## Expected behavior
The 'X-Powered-By' response header should stop being sent.

## System information
- OS: [Windows]
- Browser: Chrome 86.0.4240.111 64-bit
- Version of Next.js: 
- Version of Node.js: 12.0.0

$ nx report

>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.3.1
  @nrwl/cypress : 10.3.1
  @nrwl/eslint-plugin-nx : 10.3.1
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.1
  @nrwl/linter : 10.3.1
  @nrwl/nest : Not Found
  @nrwl/next : 10.3.1
  @nrwl/node : Not Found
  @nrwl/react : 10.3.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.1
  @nrwl/web : 10.3.1
  @nrwl/workspace : 10.3.1
  typescript : 4.0.3

**Comment by herbertpimentel** [comment]
@DarekTechTailorCo can u give us a glue about how you made this integration of nextjs and nxdev, I also want use. ?!
