### ISSUE TITLE
Comparison with Rush.js

### ISSUE THREAD

**Issue by alexkreidler** [nrwl/nx#3974]
Rush is a "a scalable monorepo manager for the web" that includes some of the same core features as Nx, with a few differences. See https://github.com/microsoft/rushjs.io-website/issues/76 for details.

It would be great to add a page to the website/documentation that outlines the differences between Nx and Rush.

In fact, it might also be useful to compare with Lerna, just to illustrate how cross-project builds and `nx affected` are different.

**Comment by FrozenPandaz** [comment]
Hi :wave:

Yes, we are aware of Rush.js for a while now and try it out from time to time. :smile:

Regarding https://github.com/microsoft/rushjs.io-website/issues/76...

> I see Rush's top five contributors are on a similar level, while Nx's top two far outstrip the others. This gives me some confidence that Rush is truly maintained, and hearing about Rush in production does the same.

I strongly believe that all of the folks on the Nx team are all incredibly smart. I'm also sure that the folks working on Rush are incredibly smart as well. I am not sure what leads you to believe that the top 2 contributors "far outstrip the others" but for what it's worth, I would like to share that I don't see the same whatsoever. We are all working hard to provide useful tools and improve developer experience. Perhaps you would consider retracting your statement as it might be hurtful to belittle the achievements of others. :pray: 

> I suspect Rush by default is faster on installs due to PNPM, but I'm very curious about the change detection and task running performance.

We are currently looking into supporting PNPM. :wink:

> Nx also takes on somewhat of a larger scope, also trying to manage webpack, jest, and typescript configs with their own presets under the @nrwl npm org. 

We do indeed try to provide an opinionated default experience for tools that we believe are great choices for development and particularly for working with monorepos.

> Personally, my experience as a relatively new Nx user is that I've spent unordinate amounts of time going to the nx monorepo and trying to read through webpack, babel, and jest configs to figure out what's going on. 

I'm sorry that Nx can be confusing. Please join the [community slack](https://bit.ly/2ZApcSo) and ask questions that you have and/or ask questions here on GitHub.

> Rush is built with Rush!

That's so cool! Nx is built with Nx as well!

> In fact, it might also be useful to compare with Lerna, just to illustrate how cross-project builds and nx affected are different.

@vsavkin did just that in this article: https://blog.nrwl.io/why-you-should-switch-from-lerna-to-nx-463bcaf6821.

If you see areas that you think Nx could take inspiration from Rush.js or any other tools, please please share your thoughts!
