### ISSUE TITLE
rely on @schematics/angular for ast-utils and similar

### ISSUE THREAD

**Issue by peterbsmyth** [nrwl/nx#3975]
## Description

```ts
import { InsertChange } from '@schematics/angular/utility/change';
import { addDeclarationToModule } from '@schematics/angular/utility/ast-utils';
```

these are now possible and were not possible when early Schematics users were implementing Schematics. So a migration away from the internal implementation that Nx has would give some more reliability and maintainability of these utils by relying on them directly from @schematics/angular

## Suggested Implementation

There's minor differences in the implementations around the usage that @nrwl/workspace implements. In my review there were some private properties that @nrwl/workspace uses that would not be possible when relying on the @schematics/angular implementation. Those are minor and addressable.

All in all, it's a majority of drop-in replacements.

**Comment by FrozenPandaz** [comment]
I'm open to adopting these utils if they are drop-in replacements or differences can be addressed easily. One issue we have seen that I wonder if it has been addressed is that these utilities depend on the version of `typescript` that is used. If you pass in an `AST` generated by a version of `typescript` that is different from the one used by the utils, it could cause an issue. Has that been addressed? Overall, I'm not too concerned with maintaining these files as they largely have not been touched. Would someone from the community be interested in looking into this?

**Comment by peterbsmith2** [comment]
I think I could have a start at PR soon. Getting hands on a problem is a good way to understand it. So I can keep an eye out for the typescript version issue as well as any others.

**Comment by mehrad-rafigh** [comment]
Hi @peterbsmith2 did you had any chance to look into this?
