### ISSUE TITLE
Root level tsconfig.json is missing resp. gets deleted

### ISSUE THREAD

**Issue by mikezks** [nrwl/nx#3981]
## Current Behavior
- Generating a new workspace with `npx create-nx-workspace myworkspace` leads to a monorepo w/o root level `tsconfig.json`.
- If `tsconfig.json` is added manually, it will be deleted on generating a new app w/ `nx g app mytest`.

## Expected Behavior
Root level `tsconfig.json` needs to be generated and must not be deleted on generating new apps. Otherwise the IDE auto-import behavior is broken.

## Steps to Reproduce
See above.

The following `tsconfig.json` file should be generated automatically:
```
{
  "extends": "./tsconfig.base.json"
}
```

### Environment

  @nrwl/angular : 10.3.1
  @nrwl/cli : 10.3.1
  @nrwl/cypress : 10.3.1
  @nrwl/eslint-plugin-nx : 10.3.1
  @nrwl/jest : 10.3.1
  @nrwl/linter : 10.3.1
  @nrwl/tao : 10.3.1
  @nrwl/workspace : 10.3.1
  typescript : 4.0.5

**Comment by FrozenPandaz** [comment]
This is related to https://github.com/nrwl/nx/issues/3874

**Comment by brandonroberts** [comment]
This works correctly even without the root tsconfig.json, and a tsconfig.base.json in the Nx 11 release with the repro instructions. Closing as resolved

**Comment by mikezks** [comment]
Yes, it works perfectly know, thanks.
