### ISSUE TITLE
nestjs not serve with Nx

### ISSUE THREAD

**Issue by markhot** [nrwl/nx#3991]
1) create new workspace with nest app api.
2) run nx serve api
## Current Behavior

application builded but not run
## Expected Behavior

must be started.
## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by mandarini** [comment]
Hi there @markhot ! Thanks for filing an issue. Can you please give some more details, and possibly a reproducible case, or a sample repository which demonstrates your issue? Unfortunately, I could not reproduce it, as it is.

**Comment by markhot** [comment]
I may repeated:
From all build of workspaces after with nest after run nx serve api, it not
run, only buid.
May be vi need reinstall Nx.
What i must do for it?

вт, 3 нояб. 2020 г. в 16:24, Katerina Skroumpelou <notifications@github.com

**Comment by mandarini** [comment]
Hi @markhot ! Can you please let me know what version of node/npm you are on? Maybe you will need to update node and npm, and then run `npx create-nx-workspace` once more?

**Comment by markhot** [comment]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise>node
--version
v14.13.1

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise>npm --version
6.14.8

чт, 5 нояб. 2020 г. в 19:08, Katerina Skroumpelou <notifications@github.com

**Comment by mandarini** [comment]
Hi @markhot !

Can you try something for me please?

* Uninstall yarn globally: `npm uninstall -g yarn` (you will need admin access)
* Clean npm cache and verify: `npm cache clean --force && npm cache verify`
* Restart
* Reinstall yarn globally `npm install -g yarn`
* Restart terminal
* `npx create-nx-workspace@latest`
* When this command completes, please run `nx report` and post the results here.

And then try to run your app, and let me know if the issue persists.

Thank you! Let me know if this helped!

**Comment by markhot** [comment]
Now it work. I think i worked with nodejs debugger. I work withouy yarn,
with npm.

пт, 6 нояб. 2020 г., 12:26 Katerina Skroumpelou <notifications@github.com>:

**Comment by mandarini** [comment]
That's great! I'll close this issue now, since you got it working! You can reopen it if the issue comes up again! :)
