### ISSUE TITLE
Debugging test is extremly hard with nrwl

### ISSUE THREAD

**Issue by Akxe** [nrwl/nx#3992]
## Description

Debugging tests in nrwl is very hard with VSCode. After 5 months of occasional trying, I still have not been able to create a functioning test luncher for VSCode.

I have created an app with `nx`, added a library and 1 test file: https://github.com/Akxe/nx-multi-workspace-test - for anyone trying the same

This is code to debug `.spec.ts` files
```js
{
	"type": "node",
	"request": "launch",
	"name": "Jest - current file",
	"program": "${workspaceFolder:Groundwork}/node_modules/@angular/cli/bin/ng",
	"cwd": "./",
	"args": [
		"test",
		"--testFile=${fileBasenameNoExtension:Groundwork}",
		"--runInBand",
	],
	"console": "internalConsole",
	"internalConsoleOptions": "neverOpen",
	"disableOptimisticBPs": true,
}
```

It will return a very interesting error
```
C:\Program Files\nodejs\node.exe .\..\..\..\..\Documents\Programming\multi-workspace-test\node_modules\@angular\cli\bin\ng test `--testFile=test.spec --runInBand
Could not read source map for file:///C:/Users/akxe/Documents/Programming/multi-workspace-test/node_modules/typescript/lib/typescript.js: ENOENT: no such file or directory, open 'c:\Users\akxe\Documents\Programming\multi-workspace-test\node_modules\typescript\lib\typescript.js.map'
Process exited with code 1
```

-------
### New parameter for `nx` command
The `nx` command could have a new parameter `--projectFromPath="path"` it would allow `nx` to decide on what project a file belongs to.

Example: (test a specific file)
```nx test --projectFromPath=libs/shared/src/file.spec.ts --testFile=libs/shared/src/file.spec.ts```

The command will deduce that `libs/shared/src/file.spec.ts` is part of the project named `shared`; the command will thus be equivalent to:

```nx test shared --testFile=libs/shared/src/file.spec.ts```

#### VSCode

I am not able to create the whole launch configuration, but this is what would come to my mind:

```js
{
	"type": "node",
	"request": "launch",
	"name": "Jest - current file",
	"program": "${workspaceFolder}/node_modules/@nrwl/cli/bin/nx",
	"cwd": "./",
	"args": [
		"test",
		"--projectFromPath=${relativeFile}",
		"--testFile=${fileBasenameNoExtension}",
		"--runInBand",
	],
	"console": "internalConsole",
	"internalConsoleOptions": "neverOpen",
	"disableOptimisticBPs": true,
}
```

**Comment by FrozenPandaz** [comment]
Hi, we made some changes for this recently. Your repo actually includes them. Can you try using this plugin? 

https://marketplace.visualstudio.com/items?itemName=firsttris.vscode-jest-runner

https://blog.nrwl.io/vs-code-jest-improved-eslint-support-typescript-4-storybook-6-and-more-with-nx-10-3-faf7c12fe556

![image](https://user-images.githubusercontent.com/8104246/97725093-22753f00-1aa4-11eb-952b-8854f7153cbb.png)

**Comment by Akxe** [comment]
I missed it when I was creating the repo...

With this extension, I had to change settings to:
```
"jestrunner.projectPath": "C:\\Users\\akxe\\Documents\\Programming\\rita",
"jestrunner.jestPath": "C:\\Users\\akxe\\Documents\\Programming\\rita\\node_modules\\jest\\bin\\jest.js",
```

To make it work in a multi-folder workspace.
