### ISSUE TITLE
nx v10 cannot resolve url() path references from deep scss folder structures - breaks app or lib build

### ISSUE THREAD

**Issue by gkamperis** [nrwl/nx#3997]
## Current Behavior
With Nx I can create a publishable lib that I also can use straight in an app in the same workspace.

With ng10 and using Sass instead of node-sass the url() paths are not resolved the same way.
They have different resolutions depending on the target that is run.

Effectively, you can:

* only build the app
* or only build a publishable lib with in-lined assets

I cannot achieve both, i.e.: have a buildable app and a correctly built publishable lib.

Initially I thought this was an ng-packgr issue and I raised it there
https://github.com/ng-packagr/ng-packagr/issues/1776

but as you can see from the reply it looks like this is expected.

I also assume that if the lib is shared the way Angular recommends by linking to the dist artefacts then this will not be an issue.
So this means that Nx's way of using the lib straight and being able to publish it is not feasible any more.

## Expected Behavior
I expect to be able achieve both, i.e.: have a buildable app and a correctly built publishable lib.

Up till now with Nx 9 latest and Angular 9 with node-sass I could achieve both.

I recently moved to Nx10 and ng10 migrating away from node-sass

## Steps to Reproduce

Repro repo:
https://github.com/gkamperis/nx-scss-depth-bug

The path reference in this file
https://github.com/gkamperis/nx-scss-depth-bug/blob/master/libs/test-lib/src/lib/test-component/scss/level1/_something.scss
will allow to either build the app with 

`npm run build`

or if you swap the comments build the lib with the correct inlined assets with 

`npm run build-lib`

(To reproduce just comment the proper line out/in)

### Failure Logs
App building error
`npm run build`

```
ERROR in github/test-ws/libs/test-lib/src/lib/test-component/scss/test-component.component.scss
Module Error (from github/test-ws/node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: github\test-ws\level1\_something.scss:6:2: Can't resolve '../assets/account_box-other-24px.svg' in 'github\test-ws\libs\test-lib\src\lib\test-component\scss'
  4 |
  5 |   // this publishes the lib inlining correctly
> 6 |   background-image: url('../../assets/account_box-other-24px.svg');
    |  ^
  7 | }

```

Lib building building warning
`npm run build-lib`

```
------------------------------------------------------------------------------
Building entry point 'test-lib'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
WARNING: postcss-url: github\test-ws\libs\test-lib\src\lib\test-component\scss\test-component.component.scss:2:3: Can't read file 'github\test-ws\libs\test-lib\src\assets\account_box-other-24px.svg', ignoring

```
### Environment
>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : 10.3.1
  @nrwl/cli : 10.3.1
  @nrwl/cypress : 10.3.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.1
  @nrwl/linter : 10.3.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.1
  @nrwl/web : Not Found
  @nrwl/workspace : 10.3.1
  typescript : 4.0.5

**Comment by nhhockeyplayer** [comment]
shouldn't we be avoiding relative paths altogether?

shouldn't the framework support the following scss for and dev but moreso for PRODUCTION?

```
ion-content {
    background: url('assets/vignette-light.png') ;
}
```

would like to hear the workaround or solution this one is blocking

**Comment by nhhockeyplayer** [comment]
standard production angular mandates no relative paths

should be 'assets/logo.png'

i cannot build either

**Comment by brandonroberts** [comment]
Will you confirm this is still an issue with the latest version of Nx?

**Comment by gkamperis** [comment]
@brandonroberts 

confirmed

https://github.com/gkamperis/nx-scss-depth-bug/tree/nx11

**Comment by nhhockeyplayer** [comment]
Hoping to see a fix @brandonroberts 
the world is watching you
: )

**Comment by brandonroberts** [comment]
I got a similar note from @JamesHenry, but it seems like this is not supported anymore according to https://github.com/angular/angular-cli/pull/17537, and what he recommended is removing the `resolve-url-loader` if you're using a custom webpack builder such as `@angular-builders/custom-webpack`

**Comment by gkamperis** [comment]
@brandonroberts I have used the standard nx commands to create the repro. Is Nx using a custom webpack builder?

essentially you cannot have a publishable lib that shares components with a deep scss folder structure with an app in the same repo...

unless... (for anyone stuck)

...you flatten out the scss hierarchy.... this is my workaround atm but it does mot make sense to be constrained like this...

**Comment by gkamperis** [comment]
bump

**Comment by gkamperis** [comment]
bump again to keep this alive... 

@brandonroberts will this be attempted to be resolved? or is this a "won't fix"?

In the latter case some docs about the limitations and workaround would be great.

Thanks

**Comment by brandonroberts** [comment]
This one is still on our radar

**Comment by dsjellz** [comment]
I'm surprised more folks have not run into this. I don't see much in the way of a workaround either? Unfortunately this is going to hold up our entire upgrade process. Hopefully a workaround is found before I'm burned at the stake for moving our org to Nx in the first place.

**Comment by sandikbarr** [comment]
Credit to @JamesHenry on this solution. You can use the custom webpack builder to remove resolve_url_loader to work around this issue. 

I was able to resolve this in @gkamperis in your Nx10 [example repo](https://github.com/gkamperis/nx-scss-depth-bug).
* Install [@angular-builders/custom-webpack](https://www.npmjs.com/package/@angular-builders/custom-webpack)
* In workspace/angular.json config, set the builder:
```
  "build": {
    "builder": "@angular-builders/custom-webpack:browser",
    "options": {
      "customWebpackConfig": {
        "path": "apps/test-app/webpack.config.js"
      },
      ...
```
```
  "serve": {
    "builder": "@angular-builders/custom-webpack:dev-server",
    ...
```
* Add apps/test-app/webpack.config.js:
```
const webpack = require('webpack');

/**
 * @param {webpack.Configuration} config
 * @param {import('@angular-builders/custom-webpack').CustomWebpackBrowserSchema} _options
 * @param {import('@angular-builders/custom-webpack').TargetOptions} _targetOptions
 */
module.exports = (config, _options, _targetOptions) => {
  const sassRule = config.module.rules.filter(
    (r) => r.test.toString() === /\.scss$|\.sass$/.toString()
  );
  if (sassRule && sassRule[0] && Array.isArray(sassRule[0].use)) {
    sassRule[0].use = sassRule[0].use.filter((u) => {
      if (
        typeof u !== 'string' &&
        typeof u !== 'function' &&
        u.loader.includes('resolve-url-loader')
      ) {
        return false;
      }
      return true;
    });
  }

  return config;
};
```

**Comment by gkamperis** [comment]
bump

**Comment by gkamperis** [comment]
bump

**Comment by Coly010** [comment]
@gkamperis Have you tried the solution outlined by @sandikbarr ? https://github.com/nrwl/nx/issues/3997#issuecomment-815014164

The latest version of Nx also allows you to use a custom webpack config without using a third-party builder if you'd prefer to not depend on `custom-webpack-builder`.

If you need any help setting up your `angular.json`/`workspace.json` to use the built-in custom webpack support, please let me know!

**Comment by Coly010** [comment]
This issue has been open for a long time with no follow-up.
There is a solution presented in my previous comment.

If this solution does not solve the issue, feel free to open this issue again.
