### ISSUE TITLE
nx migrate leads to npm update failures

### ISSUE THREAD

**Issue by domeshek** [nrwl/nx#4010]
In order to try out the --importPath library option described in a recent blog post I tried "nx migrate @nrwl/workspace" (because that flag didn't seem to be supported in my current workspace).  That produced a plausible package.json and migrations.json.  It looked like I was moving from angular 10.0.0 to 10.2.1. and nrwl/angular 10.0.1 to 10.3.1 (among other things).

I missed a step and tried running "nx migrate @nrwl/workspace" before "npm install".  When the "nx migrate" failed, I read more carefully and saw my mistake.  I tried "npm install" and it failed with a "Cannot read property 'matches' of undefined".  Googling suggested I could delete my node_modules and package-lock.json.  I tried that (actually just renamed them) and now "npm install" says:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: team@0.0.0
npm ERR! Found: @angular/common@10.2.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"10.2.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^5.2.5" from angular-pell@0.1.0
npm ERR! node_modules/angular-pell
npm ERR!   angular-pell@"^0.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

I just Googled what angular-pell is, but I'm not sure its something my project is actually using.

Should I try the --force or --legacy-peer-deps (and if so, which should I try)?  What symptoms/problems might I expect downstream if I take either of those paths?

Thanks for any guidance.

**Comment by hiepxanh** [comment]
run these report:
`npx nx report`
`node --version`
`yarn --version`
`npm --version`
