### ISSUE TITLE
Colocating the E2E tests with the project they are coupled to

### ISSUE THREAD

**Issue by BigAB** [nrwl/nx#4013]
## Description

I want to propose an idea about changing the schematics and configs so that `e2e` tests are colocated with the project they are coupled to, rather than separate applications.

<img width="228" alt="colocate-e2e" src="https://user-images.githubusercontent.com/76821/97897844-acb7e000-1cfc-11eb-93c0-7d1882bbabef.png">

Perhaps as an `e2e` sibling to `src`? I have done a few manual migrations and it "seems" to work fine.

I understand the philosophy of it being more of an application, but I also think there is a precedent with how our jest tests in the specific project, and it is actually annoying that the e2e test are "somewhere else" in the directory tree rather than near the thing they are testing.

I also find it very much clutters the `apps` folder, as on one client we have a single `app` in the `apps` folder that is actually hard to find mixed in with the hundreds of e2e tests.

There is the idea that E2E tests are not really 1:1 like that, and can test many apps/libs with one suite, and though that may be true our current naming convention really does encourage a coupling anyway, and I think for the rare case you would want to make a cross cutting e2e app, you should have a command that simply generates a cyrpress app that you can name however you want.

I think this would be a good change, I think it's more what people would expect, and I think it helps differentiate `apps`, `libs` and the tools like tests and stories that support those app and libs.

**Comment by vaunus** [comment]
I agree they clutter the `apps` folder as well. It would be good to have the option to colocate them as you've suggested.
