### ISSUE TITLE
@nrwl/workspace:mv not working 100%

### ISSUE THREAD

**Issue by vespertilian** [nrwl/nx#4014]
## Current Behavior

Following the advice in issue #2001 I was moving a library. 
nx g @nrwl/workspace:mv --project my-lib --destination their-lib 

It worked mostly great; it just did not update the jest.config.js file with the new lib directory. It's a quick manual fix, just thought I should note it here. 

## Expected Behavior
It should have updated jest.config.js with the new library location

Thanks for this great project!

**Comment by beeman** [comment]
I was about to open a closely related issue, but I guess it can go in here too.

When running `nx g @nrwl/workspace:remove <name-of-project>`, it won't remove the entry in `jest.config.js`.

**Comment by JoepKockelkorn** [comment]
Just want to point out the actual name of the schematic is `@nrwl/workspace:move` not `@nrwl/workspace:mv`.

**Comment by Cammisuli** [comment]
This should be fixed with #4227
