### ISSUE TITLE
nx build with --deleteOutputPath causes "Unknown option: '--deleteOutputPath'"

### ISSUE THREAD

**Issue by KirillMetrik** [nrwl/nx#4015]
## Current Behavior
running `nx build <project_name> --deleteOutputPath=false` causes the following error from Angular CLI:
Unknown option: '--deleteOutputPath'

I have tried to create a ticket regarding this in Angular Github: https://github.com/angular/angular-cli/issues/19283 . But they told me this is an NX issue.

## Expected Behavior
The build should run.

In version 9 of the whole environment `deleteOutputPath` was `false` by default, so it wasn't needed to build with this parameter. Since Angular 10 `deleteOutputPath` is `true` by default. We need to preserve an output path because we sometimes have an extra step copying some resources to it before the build.

## Steps to Reproduce
The problem can be reproduced on https://github.com/nrwl/nx-examples:

1. clone nx-examples
2. run `npm install`
3. run `nx build cart --deleteOutputPath=false`

### Environment
```
nx : Not Found
  @nrwl/angular : 10.3.1-beta.1
  @nrwl/cli : 10.3.1-beta.1
  @nrwl/cypress : 10.3.1-beta.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.1-beta.1
  @nrwl/linter : 10.3.1-beta.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 10.3.1-beta.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.1-beta.1
  @nrwl/web : 10.3.1-beta.1
  @nrwl/workspace : 10.3.1-beta.1
  typescript : 4.0.3
```

**Comment by KirillMetrik** [comment]
Any reaction to this please? @vsavkin ?

**Comment by FrozenPandaz** [comment]
We do not currently support that option and we always remove the output directory. I think it is a good option to have. Would someone like to add that option?
