### ISSUE TITLE
Adding custom webpack configuration

### ISSUE THREAD

**Issue by topratiksharma** [nrwl/nx#4016]
## Adding custom configuration inside workspace.json

We are generating 3rdPartyLicenes file via `"extractLicenses": true,` under workspace.json.
I am looking to extract and convert 3rdPartyLibrary text file into Json.
I was able to do this by adding custom configuration into angular projects using `@angular-builders/custom-webpack`. We are now migrating it to nx. Is there any specific way of achieving the same inside using Nx.

We are not looking to change the nx default bundling process.

Below code is from `angular.json`

`"customWebpackConfig": {`
       `       "path": "./custom.formattter.js" // This js converts 3rdParty library text file into json file.`
`},`

CC: @ankeshdave

**Comment by topratiksharma** [comment]
Hi Nx Team any update how to do this.

**Comment by FrozenPandaz** [comment]
You can continue using `@angular-builders/custom-webpack` with Nx. Does this solution work for you?

**Comment by topratiksharma** [comment]
I can use it but will it not deviate from NX architecture also I am not looking to change the NX default bundling process.
