### ISSUE TITLE
[feature-request] enable lazy routing and parent module for multi tier applications in ng g app

### ISSUE THREAD

**Issue by lmeijdam** [nrwl/nx#402]
hey guys,

Just starting out using NX and it looks really slick!

I'm currently in a situation where our team is developing an application 'shell/layout' which can load up one or more applications (different teams/projects) depending on the route. At the current implementation, without NX, we use different applications and the 'shell' has a router configuration to lazy load the other application in a 'layout' like set up. The layout contains a header, a footer and a container. In which the container loads up the other applications.

I was wondering if you guys are planning on adding the router + lazy + parentmodule options to the 'ng g app' command. If not, what would you guys suggest instead?

**Comment by noelmace** [comment]
I think what you describe is "lazy loaded lib", as shown in the documentation : 
``ng generate lib mymodule --routing 
    --lazy --parentModule=apps/myapp/src/myapp.module.ts``
See https://nrwl.io/nx/guide-nx-workspace#create-an-angular-module-lib

**Comment by lmeijdam** [comment]
Thanks for your reply!

I thought of that too, and it will suffice for now! how would you set up your structure if there is another 'app' hosted on another server or environment which need to be loaded into your 'main' app? I added a small drawing to simplify (not the best drawing skills).

![example](https://user-images.githubusercontent.com/5443014/38482492-d3bf02fc-3bcf-11e8-88d4-9725a7132087.png)

Thanks anyway!

**Comment by lmeijdam** [comment]
Thanks, will do!
