### ISSUE TITLE
Generating Angular library/app throw "projectConfig.architect.lint.options.tsConfig is not iterable"

### ISSUE THREAD

**Issue by valid13** [nrwl/nx#4022]
## Current Behavior
When i tried to generate a library/application with this configuration from angular.json
"schematics": {
    "@nrwl/angular:application": {
      "style": "scss",
      "tags": "helloworld",
      "linter": "eslint",
      "unitTestRunner": "karma",
      "e2eTestRunner": "protractor",
      "strict": true
    },
    "@nrwl/angular:library": {
      "style": "scss",
      "tags": "helloworld",
      "linter": "eslint",
      "unitTestRunner": "karma",
      "strict": true
    }
  }

with this command
`ng generate library helloworld`

this error is thrown
**projectConfig.architect.lint.options.tsConfig is not iterable**

This behavior only happen when unitTestRunner is Karma and linter is eslint, removing one of them don't create an issue.

It think it comes from this line
https://github.com/nrwl/nx/blob/58e99b0a5b75439c49dd4d40303cfb891a3b82bc/packages/angular/src/schematics/karma-project/karma-project.ts#L106
But i didn't look in depth, tsConfig is not defined in options when linter: 'eslint'

## Expected Behavior
It should generate a library or app with karma runner and eslint linter (eslintrc)
eslint was added recently so i suppose it's a regression.

## Steps to Reproduce

- Add this configuration to angular.json
"schematics": {
    "@nrwl/angular:application": {
      "style": "scss",
      "tags": "helloworld",
      "linter": "eslint",
      "unitTestRunner": "karma",
      "e2eTestRunner": "protractor",
      "strict": true
    },
    "@nrwl/angular:library": {
      "style": "scss",
      "tags": "helloworld",
      "linter": "eslint",
      "unitTestRunner": "karma",
      "strict": true
    }
  }

- Generate a library or an application

### Failure Logs
`projectConfig.architect.lint.options.tsConfig is not iterable`

### Environment
  nx : 10.3.1
  @nrwl/angular : 10.3.1
  @nrwl/cli : 10.3.1
  @nrwl/cypress : 10.3.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.1
  @nrwl/linter : 10.3.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.1
  @nrwl/web : Not Found
  @nrwl/workspace : 10.3.1
  typescript : 3.9.5

**Comment by thMthMnky** [comment]
-Same log message when running: 'nx g lib --name=helloWorld --no-interactive'.
-Schematics: 
```
  "schematics": {
    "@nrwl/react": {
      "application": {
        "style": "css",
        "linter": "eslint",
        "babel": true
      },
      "component": {
        "style": "css"
      },
      "library": {
        "style": "css",
        "linter": "eslint"
      }
    }
  }

```
Seemingly Relevant Subset of devDependencies:
```
"nx": "10.4.4",
"@nrwl/cypress": "10.0.12",
"@nrwl/eslint-plugin-nx": "10.0.12",
"@nrwl/express": "^10.4.4",
"@nrwl/jest": "10.0.12",
"@nrwl/node": "^10.4.4",
"@nrwl/react": "^10.4.4",
"@nrwl/storybook": "^10.4.4",
"@nrwl/web": "^10.4.4",
"@nrwl/workspace": "^10.4.4",
"eslint": "6.8.0",
"eslint-config-prettier": "6.0.0",
"eslint-plugin-cypress": "^2.11.2",
"eslint-plugin-import": "2.21.2",
"eslint-plugin-jsx-a11y": "6.3.1",
"eslint-plugin-react": "7.20.0",
"eslint-plugin-react-hooks": "4.0.4",
"@typescript-eslint/eslint-plugin": "2.19.2",
"@typescript-eslint/parser": "2.19.2",
```

**Comment by mehrad-rafigh** [comment]
This should be fixed with https://github.com/nrwl/nx/issues/4264

**Comment by brandonroberts** [comment]
Closing as resolved
