### ISSUE TITLE
 When generating next.js component with nx schematics, component css files should be modules

### ISSUE THREAD

**Issue by jlcampbell** [nrwl/nx#4030]
## Current Behavior

Component generated using Next schematic in nx creates a css file, not a css module. When you try to use the component, this error shows up:
![Screen Shot 2020-11-05 at 4 35 04 PM](https://user-images.githubusercontent.com/16676808/98299014-fca8d800-1f84-11eb-9d5f-637a2f846272.png)

## Expected Behavior

The [component-name].css file should instead be named [component-name].module.css. The component should be ready to use after it is generated.

## Steps to Reproduce

(cd into nx repo, and next.js app)

`nx g component demoComponent                
? What is the name of the project for this component? demo-app
? Which stylesheet format would you like to use? CSS
CREATE apps/demo-app/components/demo-component/demo-component.css (0 bytes)
CREATE apps/demo-app/components/demo-component/demo-component.spec.tsx (304 bytes)
CREATE apps/demo-app/components/demo-component/demo-component.tsx (305 bytes)`

add this line to index.tsx of Next.js app to import new component: `import {DemoComponent} from '../components/demo-component/demo-component'`

run with 'nx serve'

Open browser window to see error.

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.3.2
  @nrwl/cypress : 10.3.2
  @nrwl/eslint-plugin-nx : 10.3.2
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.2
  @nrwl/linter : 10.3.2
  @nrwl/nest : Not Found
  @nrwl/next : 10.3.2
  @nrwl/node : Not Found
  @nrwl/react : 10.3.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.2
  @nrwl/web : 10.3.2
  @nrwl/workspace : 10.3.2
  typescript : 4.0.5

**Comment by mandarini** [comment]
Hi there @jlcampbell ! Thanks for filing an issue! Do you think that your issue is related to [issue #3803](https://github.com/nrwl/nx/issues/3803)? Should we link these two?

**Comment by mandarini** [comment]
Hey, please take a look here [github.com/nrwl/nx/issues/3803#issuecomment-723162346](https://github.com/nrwl/nx/issues/3803#issuecomment-723162346).

**Comment by kirjai** [comment]
Hey, just checked it out and as per [this comment](https://github.com/nrwl/nx/issues/4030#issuecomment-723162985), this issue seems to have been fixed now

Tested on latest (version `11.1.5` at the time of writing)

Please reopen this issue if you're still experiencing problems!
