### ISSUE TITLE
nx console unable to start multiple projects

### ISSUE THREAD

**Issue by ericsnap** [nrwl/nx#4031]
## Current Behavior

If I want to start/serve multiple _projects_ in the nx console, the second project always complains that the first project/task is already executing like this:
```plaintext
The task 'nx-console: ng serve client (tools)' is already active.
```
In the example above, I first started the `client>serve` task/project.
Then I wanted to start the `api>serve` task/project. 

![Nov-05-2020 17-13-31](https://user-images.githubusercontent.com/16297214/98310477-4647f180-1f8a-11eb-8936-979ad0ca8599.gif)

## Expected Behavior

I would expect to be able to start multiple projects/tasks from within the console sidebar widget.

## Steps to Reproduce

I simply followed the steps from the tutorial to generate the code and structure.
Then:
* refresh projects list to make sure it is all up-to-date
* start the `client>serve` task
* start the `api>serve` task
* error

### Environment

```plaintext
  nx : Not Found
  @nrwl/angular : 10.3.2
  @nrwl/cli : 10.3.2
  @nrwl/cypress : 10.3.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.2
  @nrwl/linter : 10.3.2
  @nrwl/nest : 10.3.2
  @nrwl/next : Not Found
  @nrwl/node : 10.3.2
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.2
  @nrwl/web : Not Found
  @nrwl/workspace : 10.3.2
  typescript : 4.0.5
```
(FWIW, not sure why it is saying `nx: Not Found`, I did run the `nx report` command. And I tried both using the global version and via `yarn run`)

**Comment by mandarini** [comment]
Hi there @ericsnap ! Thanks for filing an issue. I did not look into it in very much detail, but until I do, off the top of my head, have you tried the [`run-many` command](https://nx.dev/latest/angular/cli/run-many)?

**Comment by eliprand** [comment]
@mandarini you want me to read documentation? 😆 
To be clear, I can absolutely run both commands separately in 2 different terminals. My bug report was more about the GUI/Console Projects section. I would have expected it to be able to run any of those tasks, regardless of whether or not another task is already executing (someone could want to run both `serve` and `e2e` at the same time or something like that).
And thanks for pointing that `run-many` command. I definitely will be able to use it.

**Comment by ericsnap** [comment]
@mandarini you want me to read documentation? 😆 
To be clear, I can absolutely run both commands separately in 2 different terminals. My bug report was more about the GUI/Console Projects section. I would have expected it to be able to run any of those tasks, regardless of whether or not another task is already executing (someone could want to run both `serve` and `e2e` at the same time or something like that).
And thanks for pointing that `run-many` command. I definitely will be able to use it.
_(sorry for the double-post if you see it twice - got my browser windows confused and replied with my personal account)_

**Comment by mandarini** [comment]
So, @ericsnap , after a brief discussion with @isaacplmann , we think this should be redirected to [nrwl/nx-console](https://github.com/nrwl/nx-console), it seems to be an nx-console issue!

**Comment by ericsnap** [comment]
@mandarini you are absolutely correct. I am fairly new to Nx and did not realize you had a different repo for console-specific issues. I will repost over there. 
Thanks for the help.
