### ISSUE TITLE
`npm run nx serve` fails after creating empty workspace, adding Angular plugin + creating new app

### ISSUE THREAD

**Issue by zejji** [nrwl/nx#4038]
## Current Behavior
`npm run nx serve` fails after creating empty workspace, adding Angular plugin + creating a new application.

The message `An unhandled exception occurred: Cannot find module 'webpack'` is shown.

(Note that I am starting with an empty workspace rather than with the single Angular application template because I want to customize the options for the new Angular project as shown in the reproduction steps below.)

## Expected Behavior
I expect `npm run nx serve` to start the Angular development server without errors.

## Steps to Reproduce

On Windows 10 with NodeJS LTS 14.15.0:
1. Open a new PowerShell window
2. Run `npx create-nx-workspace nxtest`
3. Choose the 'empty' template and the 'Angular CLI' option for the CLI
4. Move into the new directory with `cd nxtest`
5. Run `npm install -D @nrwl/angular` to install the Angular plugin
6. Create a new Angular app as follows:
```
npm run nx g @nrwl/angular:app -- testapp  --e2e-test-runner=protractor --unit-test-runner=jest --strict --style=scss --routing --linter=eslint --enable-ivy
```
7. Run `npm run nx serve`

### Failure Logs
```
PS C:\Users\<username>\source\repos\nxtest> npm run nx serve

> nxtest@0.0.0 nx
> nx "serve"


> ng run testapp:serve
An unhandled exception occurred: Cannot find module 'webpack'
Require stack:
- C:\Users\<username>\source\repos\nxtest\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
- C:\Users\<username>\source\repos\nxtest\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\Users\<username>\source\repos\nxtest\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
- C:\Users\<username>\source\repos\nxtest\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\Users\<username>\source\repos\nxtest\node_modules\@angular-devkit\architect\node\index.js
- C:\Users\<username>\source\repos\nxtest\node_modules\@angular\cli\models\architect-command.js
- C:\Users\<username>\source\repos\nxtest\node_modules\@angular\cli\commands\run-impl.js
- C:\Users\<username>\source\repos\nxtest\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\<username>\source\repos\nxtest\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\<username>\source\repos\nxtest\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\<username>\source\repos\nxtest\node_modules\@angular\cli\models\command-runner.js
- C:\Users\<username>\source\repos\nxtest\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\<username>\source\repos\nxtest\node_modules\@angular\cli\lib\init.js
- C:\Users\<username>\source\repos\nxtest\node_modules\@nrwl\cli\lib\run-cli.js
See "C:\Users\<USERNAME>~1\AppData\Local\Temp\ng-U7gsfD\angular-errors.log" for further details.
npm ERR! code 1
npm ERR! path C:\Users\<username>\source\repos\nxtest
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "nx "serve""

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<username>\AppData\Local\npm-cache\_logs\2020-11-06T15_10_51_278Z-debug.log
```

### Environment
Windows 10 Pro
Version 10.0.19042 Build 19042
PowerShell version: 5.1.19041.610
NodeJS version: 14.15.0

nx report output:
```
  nx : Not Found
  @nrwl/angular : 10.3.2
  @nrwl/cli : 10.3.2
  @nrwl/cypress : 10.3.2
  @nrwl/eslint-plugin-nx : 10.3.2
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.2
  @nrwl/linter : 10.3.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.2
  @nrwl/web : Not Found
  @nrwl/workspace : 10.3.2
  typescript : 4.0.5
```

**Comment by bekos** [comment]
@zejji I followed your steps but wasn't able to reproduce the error. Can you please provide more info or a repo that we can inspect and see what's going on?

**Comment by zejji** [comment]
@bekos - Thanks for the quick reply.

I've created an example Git repo illustrating the issue - please see attached.

There's a separate Git commit for each of the 3 commands that I ran, and the exact text of each command is included in the commit message.

All you need to do to use the repo is (i) unzip and enter the `nxtest` directory; (ii) run `npm install`; and (iii) run `npm run nx serve`.

[nxtest.zip](https://github.com/nrwl/nx/files/5503143/nxtest.zip)

**Comment by duard** [comment]
I cant create a new project too :

`
npx create-nx-workspace@latest of5
npm install -D @nrwl/angular
nx generate @nrwl/angular:application simples-front
`
![image](https://user-images.githubusercontent.com/36894/99576697-16044800-29b9-11eb-8737-eb821ae4af13.png)

`
➜npx create-nx-workspace@latest of5

? What to create in the new workspace empty             [an empty workspace with a layout that works best for building apps]
? CLI to power the Nx workspace       Nx           [Recommended for all applications (React, Node, etc..)]
? Use Nx Cloud? (It's free and doesn't require registration.) No
Creating a sandbox with Nx...
new of5  --preset="empty" --linter="eslint" --interactive=false --collection=@nrwl/workspace
✔ Packages installed successfully.
    Successfully initialized git.
CREATE of5/nx.json (539 bytes)
CREATE of5/tsconfig.base.json (509 bytes)
CREATE of5/README.md (3239 bytes)
CREATE of5/.editorconfig (245 bytes)
CREATE of5/.gitignore (503 bytes)
CREATE of5/.prettierignore (74 bytes)
CREATE of5/.prettierrc (26 bytes)
CREATE of5/workspace.json (96 bytes)
CREATE of5/package.json (1151 bytes)
CREATE of5/tools/tsconfig.tools.json (223 bytes)
CREATE of5/tools/schematics/.gitkeep (0 bytes)
CREATE of5/.vscode/extensions.json (109 bytes)
CREATE of5/apps/.gitkeep (0 bytes)
CREATE of5/libs/.gitkeep (0 bytes)

~/z-my-dev
➜cd of5

of5 on  master via ⬢ v15.0.1
➜npm install -D @nrwl/angular
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.

added 642 packages, and audited 928 packages in 19s

44 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

of5 on  master [!] via ⬢ v15.0.1
➜nx generate @nrwl/angular:application simples-front
? Which stylesheet format would you like to use? SASS(.scss)  [ http://sass-lang.com   ]
? Would you like to configure routing for this application? Yes
⠋ Installing packages...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: of5@0.0.0
npm ERR! Found: @angular/compiler@10.2.3
npm ERR! node_modules/@angular/compiler
npm ERR!   @angular/compiler@"^10.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@">=2.3.1 <9.0.0 || >8.0.0-beta <9.0.0" from codelyzer@5.0.1
npm ERR! node_modules/codelyzer
npm ERR!   dev codelyzer@"~5.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/duard/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/duard/.npm/_logs/2020-11-18T19_13_15_327Z-debug.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.
`

**Comment by duard** [comment]
this fix the problem 

```
npm i -g npm@6
```
https://github.com/nrwl/nx/issues/4089#issuecomment-728747172

**Comment by bekos** [comment]
@zejji Sorry for the late reply. Indeed, using your zip I got the same error, but after removing package.lock and re-installing everything works as expected. Can you try again with the latest Nx? What is your npm version?

**Comment by zejji** [comment]
@bekos - My npm version is 7.0.3

I've just retried the steps in my original post on this issue and now I get an error even earlier when running `npm install -D @nrwl/angular`:

![image](https://user-images.githubusercontent.com/3524191/100068792-dbbefe80-2e2f-11eb-99ca-2fb8bbd0f80c.png)

**Comment by bekos** [comment]
I see there was a [related issue](https://github.com/npm/cli/issues/2000) that got resolved in 7.0.4. Can you try to upgrade your npm and try again? 🤞

**Comment by zejji** [comment]
@bekos - I've just tried the reproduction steps in my original post using npm 7.0.15, which is the latest version, and get the following errors:

![image](https://user-images.githubusercontent.com/3524191/100758472-721e9180-33e7-11eb-9a4b-7e6dc4b052d8.png)

**Comment by bekos** [comment]
@zejji Can you try the `--legacy-peer-deps` ?

**Comment by zejji** [comment]
@bekos - This time I get a different error :(

`npm install -D --legacy-peer-deps @nrwl/angular` appears to work successfully, but then when I create the Angular app and try to run it, I get the following errors:

![image](https://user-images.githubusercontent.com/3524191/101404038-fe402580-38cd-11eb-9d3b-bca06d7bd5e7.png)

**Comment by zejji** [comment]
@bekos - Do you know if Nx intended to be used with Windows? Virtually nothing works according to the instructions and I was just wondering whether it's only tested with specific platforms.

**Comment by zejji** [comment]
Just adding a link to this related issue: https://github.com/nrwl/nx/issues/4321

It certainly looks as though the setup of an Angular project starting with an empty project needs reviewing by someone familiar with the codebase, as a broken initial setup may create problems in future updates and migrations.

**Comment by duard** [comment]
`duard (~/z-dev-me/simples) on  material-layout [!] is 📦 v0.0.0 node:(v12.18.2) 
🍺 ❯  npm run nx -- g @nrwl/angular:app testes-app --style=scss --routing=false                                                                                                                                             09:09:52 took 7s 

> simples@0.0.0 nx /home/duard/z-dev-me/simples
> nx "g" "@nrwl/angular:app" "testes-app" "--style=scss" "--routing=false"

Unable to resolve @nrwl/angular:app.
Cannot find module '@nrwl/workspace/src/utils/name-utils'
Require stack:
- /home/duard/z-dev-me/simples/node_modules/@nrwl/angular/src/utils/ast-utils.js
- /home/duard/z-dev-me/simples/node_modules/@nrwl/angular/src/schematics/application/application.js
- /home/duard/z-dev-me/simples/node_modules/@nrwl/tao/src/shared/workspace.js
- /home/duard/z-dev-me/simples/node_modules/@nrwl/tao/src/commands/generate.js
- /home/duard/z-dev-me/simples/node_modules/@nrwl/tao/index.js
- /home/duard/z-dev-me/simples/node_modules/@nrwl/cli/lib/init-local.js
- /home/duard/z-dev-me/simples/node_modules/@nrwl/cli/bin/nx.js
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simples@0.0.0 nx: `nx "g" "@nrwl/angular:app" "testes-app" "--style=scss" "--routing=false"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the simples@0.0.0 nx script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/duard/.npm/_logs/2020-12-18T12_09_57_911Z-debug.log
`

**Comment by Frikki** [comment]
Any news? This seems vital to the purpose of Nx!

**Comment by jonstelly** [comment]
I'm getting the same issue.  Following steps like mentioned above (which seem to be a short version of [this](https://nx.dev/latest/angular/migration/overview) migration overview guide).

I'm running this on Ubuntu 20.04 in WSL2.  NPM version is 7.6.2.

After I get the error about missing webpack module, I can `npm i --save-dev webpack` to get webpack installed, then the `nx serve` seems to get a bit further but then errors out with:

```
Cannot read property 'add' of undefined
TypeError: Cannot read property 'add' of undefined
    at /home/me/code/my-framework/node_modules/@ngtools/webpack/src/ivy/plugin.js:164:86
    at Array.forEach (<anonymous>)
    at /home/me/code/my-framework/node_modules/@ngtools/webpack/src/ivy/plugin.js:164:33
    at SyncHook.eval [as call] (eval at create (/home/me/code/my-framework/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (/home/me/code/my-framework/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/home/me/code/my-framework/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:630:30)
    at /home/me/code/my-framework/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/me/code/my-framework/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/home/me/code/my-framework/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/home/me/code/my-framework/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:662:28)
    at /home/me/code/my-framework/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/me/code/my-framework/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at AsyncSeriesHook.lazyCompileHook (/home/me/code/my-framework/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._go (/home/me/code/my-framework/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Watching.js:41:32)
    at /home/me/code/my-framework/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Watching.js:33:9
    at Compiler.readRecords (/home/me/code/my-framework/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:529:11)
```
