### ISSUE TITLE
Can't generate Angular application with ESLint

### ISSUE THREAD

**Issue by devinshoemaker** [nrwl/nx#4060]
## Current Behavior

An Angular application cannot be generated with ESLint.

## Expected Behavior

An Angular application can be generated with `--linter eslint`.

## Steps to Reproduce

```
npx create-nx-workspace my-org
yarn add -D -E @nrwl/angular
nx g @nrwl/angular:app myApp --linter eslint
```

### Failure Logs

`projectConfig.architect.lint.options.tsConfig is not iterable`

### Environment

```
>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : 10.3.2
  @nrwl/cli : 10.3.2
  @nrwl/cypress : 10.3.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.2
  @nrwl/linter : 10.3.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.2
  @nrwl/web : Not Found
  @nrwl/workspace : 10.3.2
  typescript : 4.0.5
```

**Comment by barrymichaeldoyle** [comment]
This is such an annoying issue, how do we work around it?

**Comment by mehrad-rafigh** [comment]
@barrymichaeldoyle @devinshoemaker Have you guys tried nx 11.0.4?
This [PR](https://github.com/nrwl/nx/pull/4264) should have fixed that

**Comment by JamesHenry** [comment]
Closing for now as I believe that the linked PR did address this, please feel free to reopen if not
