### ISSUE TITLE
Unable to create a symlink from the Angular CLI to the Nx CLI v9.7.1

### ISSUE THREAD

**Issue by dzhavat** [nrwl/nx#4073]
## Current Behavior

I just updated an Angular project from `@nrwl/workspace@8.12.11` to `@nrwl/workspace@9.7.1` and as part of the update, a `decorate-angular-cli.js` file was generated. This script is set to runs as part of a `postinstall` script.

When I run it, I get an "Unable to create a symlink from the Angular CLI to the Nx CLI:ENOENT: no such file or directory, open './node_modules/.bin/nx.ps1" error.

The issue looks very similar to #3186. It also goes away if I apply the same fix to the `decorate-angular-cli.js` file. The commit 39963e4 that fixes the problem is tagged with 9.7.0 but the fix is not part of that release. It first appears in the [release of v10.0.0](https://github.com/nrwl/nx/releases/tag/10.0.0).

## Expected Behavior

No errors.

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

Windows Server 2016 Datacenter

**Comment by dzhavat** [comment]
I'm also wondering, if I migrate to v10, will this bug be fixed applied to `decorate-angular-cli.js` file automatically, or should it be added manually?

**Comment by brandonroberts** [comment]
This fix should be updated, but you also have the option to update it manually to resolve the issue. As you mentioned, this issue is not present in more recent versions of Nx
