### ISSUE TITLE
Can't run Cypress tests into Docker container. 

### ISSUE THREAD

**Issue by brunano21** [nrwl/nx#4079]
## Current Behavior
it seems that I cannot run Cypress tests into a Docker container as shown here https://www.cypress.io/blog/2019/05/02/run-cypress-with-a-single-docker-command/.

## Expected Behavior
I would hope to run tests either with the @nrwl/cypress-builder or through `cypress run` through a docker container.
I can also assure the Cypress tests run fine in case of an Angular workspace/app (without @nwrl/nx installed).

### Failure Logs
```
$ docker run -v /home/dc-user/workbench/:/e2e -w /e2e --entrypoint=cypress cypress/included:4.12.1 run --project ./apps/demo-app-e2e/ --config-file cypress.json
The function exported by the plugins file threw an error.

We invoked the function exported by `/e2e/apps/demo-app-e2e/src/plugins/index.js`, but it threw an error.

 Error: Please provide an absolute path to a tsconfig.json as cypressConfig.env.tsConfig
    at preprocessTypescript (/e2e/node_modules/@nrwl/cypress/src/plugins/preprocessor.js:18:15)
    at module.exports (/e2e/apps/demo-app-e2e/src/plugins/index.js:21:27)
    at /root/.cache/Cypress/4.12.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:78:12
    at tryCatcher (/root/.cache/Cypress/4.12.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/root/.cache/Cypress/4.12.1/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at load (/root/.cache/Cypress/4.12.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:75:7)
    at EventEmitter.<anonymous> (/root/.cache/Cypress/4.12.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:231:5)
    at EventEmitter.emit (events.js:210:5)
    at process.<anonymous> (/root/.cache/Cypress/4.12.1/Cypress/resources/app/packages/server/lib/plugins/util.js:19:22)
    at process.emit (events.js:210:5)
    at process.emit (/root/.cache/Cypress/4.12.1/Cypress/resources/app/packages/server/node_modules/source-map-support/source-map-support.js:495:21)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

### Environment
```
  @nrwl/angular : 9.2.4
  @nrwl/cli : 9.2.4
  @nrwl/cypress : 9.2.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.2.4
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.4
  @nrwl/web : Not Found
  @nrwl/workspace : 9.2.4
  typescript : 3.8.3
```

**Comment by shlomiassaf** [comment]
I don't think it's a bug, this one is a feature.

We need a builder that will run cypress in a docker while also supporting watch mode.

The main issue here is snapshot testing with image diffing, those must run on the same OS or it will always render issues.

For example, on my OSX I get an image that is always 5%+ different then any image rendered on ubuntu OS.
This is mainly due to fonts, scroll bars etc.

The only solution is to run the tests on a container similar to the one running in the CI.

Cypress supports a single command line docker testing and I also thing NX should follow that and allow the users to use cypress pre-built dockers, there is one for every version. This will ensure consistency.

NX should run the application locally and also compile the e2e app, then map the compiled output to the docker and run it. In the process, configuring the docker to the localhost application, mapping ports etc.

The process should be complex.

**Comment by shlomiassaf** [comment]
@brunano21 what you experience is and issue with the typescript preprocessor which compiles the e2e app into a single bundle file and it is a plugin which is an integral part of NX so it must have NX run before to "enrich" the configuration with the proper values required for compilation.

I think this part should stay on the local machine, cause otherwise we will need custom container builds for NX as well, to include all the node dependencies needed to build stuff.
This approach will drastically slow the CI process, unless NX will commit to provide "all included" containers for each Cypress pre-defined container.

Instead, I think the compilation should be done on the local machine, mapping a directory directly to the container and updating the local build.

**Comment by brunano21** [comment]
@shlomiassaf thanks for your reply. 
A few points to clarify and few more thoughts:
0) yes, maybe this is not a bug, but a feature.
1) as part of my CIpipeline, I don't want to set up/download/install Cypress into my CI pipeline each time, but rather delegate this to a docker container where Cypress is installed already and ready to go. Cypress comes with docker images for each Cypress version (https://hub.docker.com/r/cypress/included/tags). In this case, I wouldn't be interested to the watch mode feature, but "run once" only.
2) I see the _issue_ stands with the NX preprocessor that runs before Cypress kicks in. As per my understanding, the preprocessor is responsible for transpilling TS spec files into JS ones mainly. However, I also noticed that the preprocessor shouldn't be needed anymore (#3037)
3) Apparently the NX builder doesn't support the breakdown of the cypress task, by running only the e2e build or cypress tests run (more here #1206).
4) as now, I generally build the e2e app into CI and spin up a server for it, then map the cypress specs files into the Docker container where Cypress should be able to run the tests again - but the error reported in the first comment is where I got stuck.

Any suggestion or thought is highly appreciated at this time.

**Comment by shlomiassaf** [comment]
If you build the e2e app, you end up with JS files which at this point you don't need the preprocessor, you can remove it.

Generally, what the preprocessor does is to modify the webpack configuration to support the monorepo environment and delegate to webpack which returns the file compiled, if you have the compiled files you can just skip the preprocessing part.

Also, about watching, the `cypress.json` in the docker container should have a watch preprocessor on the compiled file and locally, each TS change, will compile a new JS file which is mapped to the docker, which watches it... done :)

**Comment by brunano21** [comment]
To add more details, my CI is:
- building the e2e app (`nx build --prod demo-app)
- running docker command as per Cypress docs suggestion: `docker run -v /home/dc-user/workbench/:/e2e -w /e2e --entrypoint=cypress cypress/included:5.5.0 run --project ./apps/demo-app-e2e/ --config-file cypress.json --config baseUrl=http://xx.xx.xx.xx:4200`

The content of apps/demo-app-e2e/src/plugins/index.js is basically empty (commented out everything)
```
// ***********************************************************
// This example plugins/index.js can be used to load plugins
//
// You can change the location of this file or turn off loading
// the plugins file with the 'pluginsFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/plugins-guide
// ***********************************************************

// This function is called when a project is opened or re-opened (e.g. due to
// the project's config changing)

//const { preprocessTypescript } = require('@nrwl/cypress/plugins/preprocessor');

module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config

  // Preprocess Typescript file using Nx helper
  //on('file:preprocessor', preprocessTypescript(config));
};

```

Tests are found by cypress and it tries to run them. However multiple errors are reported and tests are not executed. See below:
```
====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    5.5.0                                                                              │
  │ Browser:    Electron 85 (headless)                                                             │
  │ Specs:      8 found (accordion.component.spec.ts, app.spec.ts, button.component.spec.ts, calen │
  │             dar.component.spec.ts, input-number.component.spec.ts, input.component.spec.ts, ra │
  │             dio-button.component.spec.ts, textarea.component.spec.ts)                          │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  accordion.component.spec.ts                                                     (1 of 8)

Oops...we found an error preparing this test file:

  src/integration/accordion.component.spec.ts

The error was:

Error: Webpack Compilation Error
/e2e/apps/demo-app-e2e/tsconfig.json
[tsl] ERROR
      TS5053: Option 'sourceMap' cannot be specified with option 'inlineSourceMap'.

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.

Oops...we found an error preparing this test file:

  src/support/index.ts
```

**Comment by brunano21** [comment]
With Cypress v 4.12.1 the error is 
```
docker run -v /home/dc-user/workbench/tsconfig.json:/e2e/tsconfig.json -v /home/dc-user/workbench/apps/demo-app-e2e:/e2e/demo-app -w /e2e cypress/included:4.12.1 run --project ./demo-app/ --config baseUrl=http://xx.xx.xx.xx:4200

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    4.12.1                                                                             │
  │ Browser:    Electron 80 (headless)                                                             │
  │ Specs:      8 found (accordion.component.spec.ts, app.spec.ts, button.component.spec.ts, calen │
  │             dar.component.spec.ts, input-number.component.spec.ts, input.component.spec.ts, ra │
  │             dio-button.component.spec.ts, textarea.component.spec.ts)                          │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  accordion.component.spec.ts                                                     (1 of 8)

Oops...we found an error preparing this test file:

  /e2e/demo-app/src/support/index.ts

The error was:

SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (17:0) while parsing /e2e/demo-app/src/support/index.ts while parsing file: /e2e/demo-app/src/support/index.ts


This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```

**Comment by shlomiassaf** [comment]
It looks like you are parsing TS files within the docker.
This means you also need the entire nrwl suite there, cause each SPEC file is bundled with all the cypress goodies there.

This means you either need to add another FS layer to the docker, with all NX stuff or build outside, and pass the bundle or JS files.

Without docker, this happens internally, the files are built into a temp folder hand the file path is passed to cypress.

You need to compile the TS files into JS and provide the JS files to the docker, removing the preprocessor in the docerized version

**Comment by brunano21** [comment]
Uhm @shlomiassaf  As stated already in my first comment, I have another pipeline for a different Angular CLI- based project where NX is not being used. I'm able to run TS spec files into a Docker container (with Cypress 4.12.1) with no issue at all.

**Comment by shlomiassaf** [comment]
I'm not sure 4.12.1 has built in TS support in Cypress, wasn't it in a later version?

Do you have a preprocessor there?

**Comment by shlomiassaf** [comment]
If there is built in TS support, try using the webpack preprocessor direction:

```\const webpackPreprocessor = require('@cypress/webpack-preprocessor')
 
module.exports = (on) => {
  const options = {
    // send in the options from your webpack.config.js, so it works the same
    // as your app's code
    webpackOptions: require('../../webpack.config'),
    watchOptions: {},
  }
 
  on('file:preprocessor', webpackPreprocessor(options))
}
```

https://www.npmjs.com/package/@cypress/webpack-preprocessor

**Comment by brunano21** [comment]
Typescript is supported by Cypress since 4.4.0 (https://docs.cypress.io/guides/references/changelog.html#4-4-0)

**Comment by brunano21** [comment]
> If there is built in TS support, try using the webpack preprocessor directly:
> 
> ```
>  
> module.exports = (on) => {
>   const options = {
>     // send in the options from your webpack.config.js, so it works the same
>     // as your app's code
>     webpackOptions: require('../../webpack.config'),
>     watchOptions: {},
>   }
>  
>   on('file:preprocessor', webpackPreprocessor(options))
> }
> ```
> 
> https://www.npmjs.com/package/@cypress/webpack-preprocessor
> 
> Note that you might not have support for TS path mappings, depending on the implementation

I'd like to avoid any custom configuration or running an npm install into the docker container.

**Comment by shlomiassaf** [comment]
@brunano21 I think that if there is not `typescript` in the project it will not compile

My guess is that your other project has all the node_modules in the docker...

**Comment by brunano21** [comment]
> i

That's what I wanted to avoid :D

**Comment by brunano21** [comment]
> @brunano21 I think that if there is not `typescript` in the project it will not compile
> 
> My guess is that your other project has all the node_modules in the docker...

That's literally what I wanted to avoid. I need to understand what's the configuration/set up problem between my two pipelines: one is using NX, the second no and within the second I'm able to run Cypress tests into a docker container, without mapping node_modules or running npm install: all I do is to map specs files as shown into (this guide)[https://www.cypress.io/blog/2019/05/02/run-cypress-with-a-single-docker-command/]
```
docker run -it -v $PWD:/e2e -w /e2e cypress/included:3.2.
```

**Comment by shlomiassaf** [comment]
Strange, you use `3.2` there, with NO typescript support ?

**Comment by shlomiassaf** [comment]
I've just logged in to the docker container of 4.12.1, it has `ts-node` and `typescript` included

**Comment by brunano21** [comment]
That was just the example you find into the guide I have linked above. I currently using 4.12.1.

**Comment by brunano21** [comment]
Please try to replicate the issue into a docker image by trying to run a Cypress tests of a NX workspace into the docker container itself.

**Comment by shlomiassaf** [comment]
@brunano21 I was able to run in.

You must have typescript installed, globally or in the nearest `node_modules` for it to work. (read here)[https://github.com/cypress-io/cypress-documentation/pull/2710]

You also need to remove the pre processor if you don't want to install the entire NX toolchain.

**HOWEVER**
If you have a monorepo setup, with path mappings, you will not have them defined, and need to do so manually.

This is why, my first suggestion is to compile it on the local computer, create a single bundle for all non spec files, and then compile the spec files and copy it all to the docker, without any need for extra deps.

**Comment by brunano21** [comment]
Could you be more explanatory about =_you will not have them defined, and need to do so manually._?

Also, when you say _compile it on local computer_, what are you referring to? Shouldn't I just copy the TS spec files only into the docker image? Or am I missing something else?

**Comment by shlomiassaf** [comment]
I did confirm, but you can't require them, they are within the Cypress installation.
It also makes sense, they cant force a TS version on you, you must bring it.

What I did was to run the docker with entrypoint bash, mapping all folders as before.
manually install `typescript`
Ran the code.

I got an error message cause it couldn't find a path, which is an internal path mapping I have.
Once this is sorted out it should be ok.

But note that any require to an npm module will have to be installed before running

**Comment by brunano21** [comment]
I found this: https://github.com/cypress-io/cypress-docker-images/issues/319

I guess I'm not the only one facing this issue... :-/

**Comment by shlomiassaf** [comment]
What do they want? Typescript 3 installed? maybe 4? maybe upcoming 5? it's not something Cypress can solve. Each project has a different compile version.

It's not a big deal however, only installing TS is quick.
It's also something you can't avoid when using third party plugins, you have to install them as well.

The only issue I have is the path mappings, Cypress does not provide and input to customise the `ts-node` TS configuration so I can't inject my path mapping configuration.

I used direct references to the module and it worked...

**Comment by shlomiassaf** [comment]
I guess I can setup some ENV variable for the config or register it before but the latter will force me to install ts-node as well

**Comment by shlomiassaf** [comment]
I tried putting this in the `plugin/index.js`

```
process.env.TS_NODE_PROJECT = require('path').join(process.cwd(), 'tsconfig.e2e.json');
require('ts-node/register');
require('tsconfig-paths/register');
```
But it didn't work.
My guess is that cypress override it, using it's own ts-node (https://github.com/cypress-io/cypress/pull/5906/files#diff-8e4b9811a53c9f9ae33ee23813d04c61040f89b600adbff569168bb42ff8158bR188-R189)

> If I put a wrong path in TS_NODE_PROJECT it throws, so it does take it

I think there is TS support but a very limited one, with no possible way I can see to customize the tsconfig, which is a big problem

**Comment by shlomiassaf** [comment]
@brunano21 OK, I figured this out.

It's not complicated as we thought it was.

From the **ROOT** of your work space:

```bash
docker run -it -v $PWD:/workspace -w /workspace --entrypoint=./node_modules/.bin/nx cypress/included:4.12.1 e2e ngrid-dev-app-e2e --dev-server-target --base-url=http://host.docker.internal:4200
```

Basically, the `-v` maps between the folders of the container and the host, it's not a copy, pure hot link.
So we can map it all, including node modules, and just build it on the container.

Note that on special scenarios, when using npm packages which require OS compilation (node GYP) and if the host/container are different (win/linux) you might have issues, I didn't run into any here.

**Comment by brunano21** [comment]
@shlomiassaf many thanks for your time!

This is exactly what I'm doing in my first pipeline, where I have a mono-repo (not using nrwl/nx) which is working fine when running tests into a docker container as you shown.

As said earlier, I have to understand what's wrong when using a nx since I'm facing the issues reported above. 

Many thanks again for taking a look at this.

**Comment by brunano21** [comment]
I got it working as you suggested, but your way is going to compile the app first and execute the tests right after. Is there a way to skip the app build phase, since I have already the app built and reachable to a given URL? 
I think this relates to #1206.

**Comment by brunano21** [comment]
I found this PR #3744 and (this comment)[https://github.com/nrwl/nx/pull/3744#issuecomment-704096584] too which helped with what I was looking for.

The *definitive* command is now 
```
docker run -it -v $PWD:/workspace -w /workspace --entrypoint=./node_modules/.bin/nx cypress/included:4.12.1 e2e demo-app-e2e --devServerTarget= --baseUrl=http://xx.xx.xx.xx:4200
```
Note the empty `devServertTarget` argument and the given `baseUrl` passed down to the Cypress configuration.

**Comment by shlomiassaf** [comment]
Happy to help 
Did you look at my comment? The dev server target is empty

**Comment by brunano21** [comment]
Oh man, I missed that 🤦‍♂️ sorry!
