### ISSUE TITLE
Attempting to build a library: library is a dependency of itself?

### ISSUE THREAD

**Issue by ConnorDY** [nrwl/nx#4081]
## Current Behavior
I'm using NX with Angular and have been struggling for a while to upgrade from Angular 9 to 10.
I ended up starting a new NX workspace from scratch using the latest everything and I've got everything working now except for building my library package.

Previously I used `ng build core --prod` to build, but now I'm getting:
```
Some of the project core's dependencies have not been built yet. Please build these libraries before:
- core

Try: nx run core:build --with-deps
```

So I tried `nx run core:build:production --with-deps` but it seems to think core is a dependency of core and then fails with the exact same error message.

## Expected Behavior
Library project builds successfully as it previously did.

## Steps to Reproduce
1) Create a new NX workspace: `npx create-nx-workspace@latest`
2) Create a new library: `npx nx g @nrwl/angular:lib core`
3) Add build config to `angular.json` under `projects.core.architect`:
 ```json
"build": {
          "builder": "@nrwl/angular:package",
          "options": {
            "tsConfig": "libs/core/tsconfig.lib.json",
            "project": "libs/core/ng-package.json"
          },
          "configurations": {
            "production": {
              "tsConfig": "libs/core/tsconfig.lib.prod.json"
            }
          }
        }
```
4) Attempt to build the library: `nx run core:build:production --with-deps`

### Failure Logs
Relevant log included above.

### Environment
```
nx : Not Found
  @nrwl/angular : 10.3.3
  @nrwl/cli : 10.3.3
  @nrwl/cypress : 10.3.3
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.3
  @nrwl/linter : 10.3.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.3
  @nrwl/web : Not Found
  @nrwl/workspace : 10.3.3
  typescript : 4.0.5
```

**Comment by brandonroberts** [comment]
This issue is resolved in Nx 11

**Comment by ohabash** [comment]
im getting this error also in version 12 of angular // nrwl

> nx run core:build:production 
>Some of the project core's dependencies have not been built yet. Please build these libraries before:
>- shared
>- core

so i tried to build shared but i get the same error? Any ideas?
