### ISSUE TITLE
Mismatch of project names between nx.json and angular.json causes misleading error message

### ISSUE THREAD

**Issue by kylebjordahl** [nrwl/nx#4090]
## Current Behavior
If a project name is different between `nx.json` and `angular.json`, *most* `nx` commands throw a misleading error:

```
>  NX   ERROR  Could not find @nrwl/cli module in this workspace.
```

(so far, it seems that `nx format` is the only command unaffected, FWIW)

### Why would this even happen in the first place?

Manual renaming, human error, etc. In our case, it was the following:
When `@nrwl/angular` creates an e2e project which is nested in a folder, the project name ends up with a `/` in it, which causes a VS Code warning in `angular.json`. While adding some additional configuration to `angular.json`, I saw this warning and manually fixed it.

![Screen Shot 2020-11-14 at 9 50 51 AM](https://user-images.githubusercontent.com/3489222/99153684-e5da4380-265e-11eb-961b-957ddb3cdd66.png)

The e2e project naming is a separate issue, but illustrates how easy it is to make a small "fix" and end up down a rabbit hole.

## Expected Behavior
When the nx cli finds an issue with `angular.json` or `nx.json`, it should throw an error that leads the user to what has actually caused the problem, not a wild goose hunt of reinstalling all node modules, changing node versions, etc 😩

## Steps to Reproduce
 1. Change a project name in `angular.json`
 2. run `nx affected:apps`
 3. see error message
 4. Restore project name in `angular.json`
 5. run `nx affected:apps` 
 6. see successful command output

### Failure Logs
```
>  NX   ERROR  Could not find @nrwl/cli module in this workspace.
```

### Environment
  @nrwl/angular : 9.5.1
  @nrwl/cli : 9.5.1
  @nrwl/cypress : 9.5.1
  @nrwl/eslint-plugin-nx : 9.5.1
  @nrwl/express : Not Found
  @nrwl/jest : 9.5.1
  @nrwl/linter : 9.5.1
  @nrwl/nest : 9.6.0
  @nrwl/next : Not Found
  @nrwl/node : 9.5.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.5.1
  @nrwl/web : Not Found
  @nrwl/workspace : 9.5.1
  typescript : 3.9.7

**Comment by vsavkin** [comment]
Thank you for submitting the issue.

Do you see the same issue when using Nx 9.8 or Nx 10? If yes, could you provide a repo reproducing the issue?

**Comment by kylebjordahl** [comment]
@vsavkin - sorry for the delay, was in the midst of things and lost track of open issues.

I can confirm that using nx `10.4.4` I now see a much improved error message: `angular.json and nx.json are out of sync. The following projects are missing in nx.json: rship/utils-socket-gateway-tester`

Thanks for the great tools, glad to see them getting even better.
