### ISSUE TITLE
Next JS Module federation plugin

### ISSUE THREAD

**Issue by suwigyarathore** [nrwl/nx#4091]
## Description
Next JS Module federation plugin

## Motivation
Could enable micro frontend pattern like https://github.com/nrwl/nx/pull/3913 for Next JS apps in NX workspace
 
## Suggested Implementation
https://gist.github.com/jherr/dd10bc34448590a2661a0c6acbcc7e8a
https://github.com/module-federation/nextjs-mf

**Comment by akshayr20** [comment]
Do we have docs for NX, next js module federation support?
