### ISSUE TITLE
workspace_1.InsertChange is not a constructor 

### ISSUE THREAD

**Issue by rahilkalia1234** [nrwl/nx#4093]
## Current Behavior

throwing error workspace_1.InsertChange is not a constructor  when trying to create library

## Expected Behavior

should create a library

## Steps to Reproduce

trying to create library using npx ng g @nrwl/workspace:library xyz

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by vsavkin** [comment]
Thank you for submitting the issue.

Unfortunately, I'm not able to reproduce it. Could you provide a repository where the provided command would fail?
