### ISSUE TITLE
Upgraded from Nx 10.1 to 10.4: Now getting "Could not find Nx modules in this workspace."

### ISSUE THREAD

**Issue by crates** [nrwl/nx#4097]
## Current Behavior
Since upgrading my Nx from version 10.1 to 10.4 just now, I can no longer start my project. 
It says, "NX   ERROR  Could not find Nx modules in this workspace."
Followed by, "Have you run npm/yarn install?"

## Expected Behavior
I would expect my project to start. It starts fine on the older version.

## Steps to Reproduce
Presumably, this would happen for anyone running a TypeScript React project upgrading to 10.4?

### Environment
Oddly enough, even `nx report` is throwing the same error listed above.

**Comment by crates** [comment]
Just a heads-up: reverting my package.json file DID get things working for me.

So, that means there's an incompatibility with the old and new versions of Nx.

Here's the contents of `nx report` AFTER reverting to the known-good state:
```
  nx : 10.1.0
  @nrwl/angular : 8.12.11
  @nrwl/cli : 10.1.0
  @nrwl/cypress : 10.1.0
  @nrwl/eslint-plugin-nx : 10.1.0
  @nrwl/express : 10.1.0
  @nrwl/jest : 10.1.0
  @nrwl/linter : 10.1.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.1.0
  @nrwl/react : 10.1.0
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 10.1.0
  @nrwl/web : 10.1.0
  @nrwl/workspace : 10.1.0
  typescript : 3.9.7
```

Here are the dependencies from the `package.json` file earlier, when it was broken:
```
{
  "dependencies": {
    "@apollo/client": "^3.1.4",
    "@apollo/react-hoc": "^3.1.5",
    "@apollo/react-hooks": "^3.1.5",
    "@auth0/auth0-spa-js": "^1.12.0",
    "@capacitor/core": "^2.4.0",
    "@hookstate/core": "^3.0.1",
    "@ionic/react": "5.3.2",
    "@ionic/react-router": "5.3.2",
    "apollo-boost": "^0.4.9",
    "apollo-link-context": "^1.0.20",
    "cross-fetch": "^3.0.5",
    "document-register-element": "1.13.1",
    "express": "4.17.1",
    "graphql": "^15.3.0",
    "history": "^4.10.1",
    "ionicons": "5.1.2",
    "lodash": "^4.17.20",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-router-dom": "5.2.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1001.0",
    "@angular/forms": "10.0.12",
    "@babel/core": "7.8.3",
    "@babel/plugin-proposal-decorators": "^7.10.5",
    "@babel/preset-env": "7.9.6",
    "@babel/preset-react": "^7.10.4",
    "@babel/preset-typescript": "^7.10.4",
    "@capacitor/cli": "^2.4.0",
    "@graphql-codegen/cli": "^1.17.8",
    "@graphql-codegen/typescript-operations": "^1.17.8",
    "@graphql-codegen/typescript-react-apollo": "^2.0.6",
    "@nrwl/cypress": "10.1.0",
    "@nrwl/eslint-plugin-nx": "10.1.0",
    "@nrwl/express": "10.1.0",
    "@nrwl/jest": "10.1.0",
    "@nrwl/node": "10.1.0",
    "@nrwl/react": "10.1.0",
    "@nrwl/schematics": "^8.12.11",
    "@nrwl/storybook": "10.1.0",
    "@nrwl/web": "10.1.0",
    "@nrwl/workspace": "10.1.0",
    "@nxtend/ionic-react": "3.1.0",
    "@storybook/addon-knobs": "5.3.9",
    "@storybook/angular": "5.3.9",
    "@storybook/react": "5.3.9",
    "@testing-library/cypress": "7.0.0",
    "@testing-library/jest-dom": "5.11.4",
    "@testing-library/react": "10.4.1",
    "@testing-library/user-event": "12.1.5",
    "@types/express": "4.17.0",
    "@types/jest": "26.0.8",
    "@types/node": "~8.9.4",
    "@types/ramda": "github:types/npm-ramda#dist",
    "@types/react": "16.9.38",
    "@types/react-dom": "16.9.8",
    "@types/react-router-dom": "5.1.5",
    "@typescript-eslint/eslint-plugin": "2.19.2",
    "@typescript-eslint/parser": "2.19.2",
    "babel-jest": "26.2.2",
    "babel-loader": "8.0.6",
    "babel-plugin-transform-inline-environment-variables": "^0.4.3",
    "concurrently": "^5.3.0",
    "cypress": "^4.12.1",
    "cz-conventional-changelog": "^3.3.0",
    "dotenv": "^6.2.0",
    "eslint": "6.8.0",
    "eslint-config-prettier": "6.0.0",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-import": "2.21.2",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-react": "7.20.0",
    "eslint-plugin-react-hooks": "4.0.4",
    "fs": "0.0.1-security",
    "husky": "^4.3.0",
    "jest": "26.2.2",
    "jest-fetch-mock": "^3.0.3",
    "node-fetch": "^2.6.1",
    "nx": "^10.1.0",
    "path": "^0.12.7",
    "prettier": "2.0.4",
    "semantic-release": "^17.1.1",
    "ts-jest": "26.1.4",
    "ts-node": "~7.0.0",
    "tslint": "~6.0.0",
    "typescript": "3.9.7"
  },
}
```

**Comment by crates** [comment]
And, just for good measure, here are the dependencies in the known-good state:
```
  "dependencies": {
    "@apollo/client": "^3.1.4",
    "@apollo/react-hoc": "^3.1.5",
    "@apollo/react-hooks": "^3.1.5",
    "@auth0/auth0-spa-js": "^1.12.0",
    "@capacitor/core": "^2.4.0",
    "@hookstate/core": "^3.0.1",
    "@ionic/react": "5.3.2",
    "@ionic/react-router": "5.3.2",
    "apollo-boost": "^0.4.9",
    "apollo-link-context": "^1.0.20",
    "cross-fetch": "^3.0.5",
    "document-register-element": "1.13.1",
    "express": "4.17.1",
    "graphql": "^15.3.0",
    "history": "^4.10.1",
    "ionicons": "5.1.2",
    "lodash": "^4.17.20",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-router-dom": "5.2.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1001.0",
    "@angular/forms": "10.0.12",
    "@babel/core": "7.8.3",
    "@babel/plugin-proposal-decorators": "^7.10.5",
    "@babel/preset-env": "7.9.6",
    "@babel/preset-react": "^7.10.4",
    "@babel/preset-typescript": "^7.10.4",
    "@capacitor/cli": "^2.4.0",
    "@graphql-codegen/cli": "^1.17.8",
    "@graphql-codegen/typescript-operations": "^1.17.8",
    "@graphql-codegen/typescript-react-apollo": "^2.0.6",
    "@nrwl/cypress": "10.1.0",
    "@nrwl/eslint-plugin-nx": "10.1.0",
    "@nrwl/express": "10.1.0",
    "@nrwl/jest": "10.1.0",
    "@nrwl/node": "10.1.0",
    "@nrwl/react": "10.1.0",
    "@nrwl/schematics": "^8.12.11",
    "@nrwl/storybook": "10.1.0",
    "@nrwl/web": "10.1.0",
    "@nrwl/workspace": "10.1.0",
    "@nxtend/ionic-react": "3.1.0",
    "@storybook/addon-knobs": "5.3.9",
    "@storybook/angular": "5.3.9",
    "@storybook/react": "5.3.9",
    "@testing-library/cypress": "7.0.0",
    "@testing-library/jest-dom": "5.11.4",
    "@testing-library/react": "10.4.1",
    "@testing-library/user-event": "12.1.5",
    "@types/express": "4.17.0",
    "@types/jest": "26.0.8",
    "@types/node": "~8.9.4",
    "@types/ramda": "github:types/npm-ramda#dist",
    "@types/react": "16.9.38",
    "@types/react-dom": "16.9.8",
    "@types/react-router-dom": "5.1.5",
    "@typescript-eslint/eslint-plugin": "2.19.2",
    "@typescript-eslint/parser": "2.19.2",
    "babel-jest": "26.2.2",
    "babel-loader": "8.0.6",
    "babel-plugin-transform-inline-environment-variables": "^0.4.3",
    "concurrently": "^5.3.0",
    "cypress": "^4.12.1",
    "cz-conventional-changelog": "^3.3.0",
    "dotenv": "^6.2.0",
    "eslint": "6.8.0",
    "eslint-config-prettier": "6.0.0",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-import": "2.21.2",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-react": "7.20.0",
    "eslint-plugin-react-hooks": "4.0.4",
    "fs": "0.0.1-security",
    "husky": "^4.3.0",
    "jest": "26.2.2",
    "jest-fetch-mock": "^3.0.3",
    "node-fetch": "^2.6.1",
    "nx": "^10.1.0",
    "path": "^0.12.7",
    "prettier": "2.0.4",
    "semantic-release": "^17.1.1",
    "ts-jest": "26.1.4",
    "ts-node": "~7.0.0",
    "tslint": "~6.0.0",
    "typescript": "3.9.7"
  },
```

**Comment by mandarini** [comment]
Hi there @crates ! 
Thanks for filing an issue!

I am assuming you used [`nx migrate`](https://nx.dev/latest/angular/workspace/update), is this correct?
Please take a look at the [Generate migrations.json](https://nx.dev/latest/angular/workspace/update) paragraph.
`nx migrate` will essentially anazyle your dependencies, and update your `package.json` with all the new versions of the packages that you need to go from one version to the other. So, in order to actually get all these new versions of these new packages you always need to run `yarn` or `npm install` after this analysis.

After installing the "missing modules", you will also need to run `nx migrate --run-migrations=migrations.json` which will take care of changing bits of your code that may need to match the version you are migrating/upgrading to.

So, the error you got is an expected behavior, because, most times (if not all), your `package.json` will have changed and new dependencies will be waiting to be installed, the missing modules that you spotted.

So, can you please try to run `yarn` and then `nx migrate --run-migrations=migrations.json` and let me know if the problem persists?

Let me know if this helps!

**Comment by crates** [comment]
OK. Thanks for getting back to me so quickly, @mandarini!

Unfortunately, following the upgrade path produced the same, undesirable result.

I first ran `nx migrate`, as instructed. Next, I did an `npm install` as you recommended.

Following that, upon trying to run `nx migrate --run-migrations=migrations.json`, I got the same error. =(

**Comment by crates** [comment]
Just wanted to weigh in further to indicate that the same problem doesn't happen (at least, not in the same way) when I tried just now to upgrade to 10.3 instead of going straight to 10.4 from v10.1 all at once. 

Here's what I ran as an alternative:
```
nx migrate @nrwl/workspace@10.3
npm install
nx migrate --run-migrations=migrations.json
```

Unlike the previous errors, this one didn't complain about missing modules. 

I did, however, still encounter an error when running this alternative migration:
```
Running migration @nrwl/workspace:add-cli-dependency
An installation of node_modules has been required. Make sure to run it after the migration
Successfully finished @nrwl/workspace:add-cli-dependency
---------------------------------------------------------
Running migration @nrwl/workspace:update-10-3-0
Successfully finished @nrwl/workspace:update-10-3-0
---------------------------------------------------------
Running migration @nrwl/workspace:add-vscode-extensions
Successfully finished @nrwl/workspace:add-vscode-extensions
---------------------------------------------------------
Running migration @nrwl/workspace:add-buildable-project-deps-in-package-json-type
Successfully finished @nrwl/workspace:add-buildable-project-deps-in-package-json-type
---------------------------------------------------------
Running migration @nrwl/angular:update-9-0-0
Schematic "update-9-0-0" not found in collection "@nrwl/angular".
Command failed: npx tao migrate --run-migrations=migrations.json
```

**Comment by crates** [comment]
Another quick update: I was able to get past the error I posted just above.

Here's what I ran most recently, in order to get past this error:
```
npm i -D @nrwl/cli
npm i -D @nrwl/angular
npx nx migrate --run-migrations=migrations.json
```

That seems to have allowed me to process the migrations file and update my Nx successfully to v10.3...
With the exception, however, of the `@nrwl/cli` and `@nrwl/angular` packages, which are at 10.4 now.

**Comment by crates** [comment]
After going through that migration, it looks like Nx is still working (albeit on v10.1.0 for some reason).

Here's what I see now when I run `nx report`:

```
  nx : 10.1.0
  @nrwl/angular : 10.4.1
  @nrwl/cli : 10.3.0
  @nrwl/cypress : 10.3.0
  @nrwl/eslint-plugin-nx : 10.3.0
  @nrwl/express : 10.3.0
  @nrwl/jest : 10.3.0
  @nrwl/linter : 10.3.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.3.0
  @nrwl/react : 10.3.0
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 10.3.0
  @nrwl/web : 10.3.0
  @nrwl/workspace : 10.3.0
  typescript : 4.0.5
```

**Comment by crates** [comment]
I also wanted to confirm that, following the above upgrade path to v10.3, my project appears to be working fine.

I ran a few commands to validate this, including my unit tests, feature tests in Cypress, and manually checking it.

I will now try updating from v10.3 to v10.4 in case anyone else encounters the same problems I did, down the line.

**Comment by crates** [comment]
OK, so **THIS** time, I got a third error, when trying to upgrade from 10.3 to 10.4:

```
npm i

> my-package@0.0.0-development postinstall /Users/my-user/Code/my-package
> ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points

sh: ngcc: command not found
```

**Comment by crates** [comment]
OK. This has been quite a strange series of errors. I have been able to get past the newest ones now.

So, in order to get `npm install` to work locally in my project after upgrading to 10.4 from 10.3, I needed to run:
`npm i -g @angular/compiler-cli @angular/compiler typescript`

What's really odd about this is, I've never previously had or needed these packages to be installed globally.

I've been running my project on 5 different development workstations so far, and this was never a problem before.

I'm thinking something has changed between versions 10.3 and 10.4 that is germane to the crux of these issues.

Anyways... I'm happy to report, for the sake of anyone else finding their way here, that my upgrade to 10.4 is good now.

After adding these 3 packages globally, I was able to run `nx migrate --run-migrations=migrations.json`.

Here's what I am seeing in my `nx report` now:
```
  nx : 10.1.0
  @nrwl/angular : 10.4.1
  @nrwl/cli : 10.3.0
  @nrwl/cypress : 10.4.1
  @nrwl/eslint-plugin-nx : 10.4.1
  @nrwl/express : 10.4.1
  @nrwl/jest : 10.4.1
  @nrwl/linter : 10.4.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.4.1
  @nrwl/react : 10.4.1
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 10.3.0
  @nrwl/web : 10.4.1
  @nrwl/workspace : 10.4.1
  typescript : 4.0.5
```

**Please do not close this issue without further investigation of the underlying issue.**

While it's true that I have laid out a viable path above for upgrading, the bug still exists here.

In order to keep other folks from getting frustrated (and possibly leaving your ecosystem), we should still continue investigating and working on a resolution, so that other users upgrading from older versions can do so seamlessly, and without jumping through all of the hoops I had to get through in order to get things working again.

**Comment by crates** [comment]
My project starts fine now, and I can run the unit tests without problems. 

However, I can no longer run my `nx workspace-lint && nx lint` command successfully anymore.

The error I'm getting there is that some of my files don't belong to any projects, which was never a problem before.

Also, my `nx e2e` command no longer functions. It now throws the following error, not present in version 10.1:
`Could not find target "e2e" in the vieday-ionic project. Valid targets are: build, serve, lint, test`

I have to say, I'm extremely disappointed with how brittle the Nx ecosystem appears to be at this point.

**Comment by crates** [comment]
I was able to get past the errors where Cypress didn't understand the types for "cy" or "it" or "describe".

I did this by editing my `tsconfig.e2e.json` file to add the following to the "compilerOptions" object:
`    "types": ["cypress", "jest", "@testing-library/cypress", "@types/cypress", "@types/jest"]`

**It's really important to understand that _none_ of this was necessary prior to upgrading to version 10.4 of Nx.**

Somehow, in the process of upgrading to a newer version, I was left with a LOT of manual work to do.

After adding this line, my types are now working for the standard Cypress and Jest methods...

HOWEVER, I'm still not back to a working state. I'm now getting errors for each of my custom Cypress methods:
```
TS2339: Property 'login' does not exist on type 'cy & EventEmitter'.
TS2339: Property 'setFakeProfile' does not exist on type 'cy & EventEmitter'.
TS2339: Property 'mockLogin' does not exist on type 'cy & EventEmitter'.
```

It's BS like this that makes me hate TypeScript. For every five minutes it saves me, I find that later on, somewhere I end up spending five hours trying to solve problems like these.

**Comment by vsavkin** [comment]
Thank you for submitting the issue. 

It's challenging to investigate without having a repro. For instance, it's strange that the migration didn't update all the packages (some of them are 10.4.1, some are not).

It's also puzzling why you would you need to install any global dependencies. Global deps should not be used at all. The only explanation I can think of is that you have some deps missing in your package.json and somehow they got picked up from your global node_modules. 

Are you having the same issue if you run `npx nx migrate`? 

Also, are you able to create a repro? I'm able to create a 10.1 project and migrate it to 10.4.1 in a single without any issues. If we have a repo reproducing all/some of the issues, we could investigate.

**Comment by crates** [comment]
@vsavkin : Have you tried using the dependencies from the broken version above to reproduce the issue?

I'm not sure how else to reproduce this for you. It doesn't mean it isn't a real bug or problem.

And yes, I actually did test using `npx` as well. It didn't change anything in terms of the results.

**Comment by crates** [comment]
This is a bit unrelated to the original issue, but I wanted to add it in case anyone else encounters the same Cypress problem I was having above. It looks like one of the upgrades (either to Cypress, to Nx, or to TypeScript) has changed the way that namespaces work for Cypress. 

Previously (working as of Nx v10.1), I had declared namespaces for my custom Cypress methods like so:
```
  declare namespace Cypress {
    interface Chainable<Subject> {
      login(email: string, password: string): void;
      setFakeProfile(): void;
      mockLogin(): void;
    }
  }
```

For whatever reason, that just decided to stop working entirely now. It just isn't working the way it used to.

After reading around the Internet some similar posts from other users, I have updated this code to read:
```
declare global {
  namespace Cypress {
    interface Chainable<Subject> {
      login(email?: string, password?: string): Promise<any>;
      setFakeProfile(): Promise<any>;
      mockLogin(): Promise<any>;
    }
  }
}
```

I also added the following lines to the top of my `support/commands.ts` file:
```
/// <reference types="cypress" />
/* eslint @typescript-eslint/camelcase: 0, @typescript-eslint/no-unused-vars: 0, @typescript-eslint/no-namespace: 0 */
```

I have absolutely ZERO idea why this worked fine before version 10.4 and suddenly required changes to function again.

Nothing else was changed, except trying to upgrade the Nx package and running an `npm audit fix`.

Thankfully, this fixed my remaining Cypress errors, so now my end to end tests are working again.

Now I need to fix the linting errors, and my project will be upgraded. I can't believe how much work this has been.

**Comment by crates** [comment]
OK. I was able to fix the final issue (around the lint command not working) by adding an `.nxignore` file to my project's root with the couple of files that lived outside the Nx ecosystem (which included a deployment config file, a service account token, and three custom modules). 

I also had to add a couple of `jest.d.ts` files (which I had to add in the first place because, for whatever reason, Jest's methods weren't seen previously by TypeScript - a problem that was perhaps since fixed by the other changes listed earlier in this thread).

It looks like I've made it through all of the headaches associated with upgrading my Nx version to 10.4 ... for now.

I'm praying I don't have to go through all of this again. These kinds of issues are precisely what I was hoping to avoid by using a framework like Nx in the first place! _(sigh)_

**Comment by crates** [comment]
I'm now seeing the same `ngcc` error I was getting earlier, locally, when trying to build to my CI instance.

So, there's some other issue here that needs to be resolved before the build will work on all devices.

This really sucks, guys. I am starting to deeply regret entrusting my project to Nx.

**Comment by crates** [comment]
OK. Looks like those global dependencies were part of the problem - installing them locally to the project fixed this.

No idea why the upgrade script wouldn't have done this for me, though, considering that **_version 10.1 worked fine for me_**.

So, here's the command that fixed the CI build error: `npm i -D @angular/compiler-cli @angular/compiler`

**Comment by vsavkin** [comment]
I'm sorry you are having issues upgrading. 

Unfortunately, issues related to npm installs are hard to troubleshoot unless we have a good repro. Different versions of npm (and I'm not even talking about yarn and pnpm) work differently. Global dependencies can affect what is resolved and from when. If you happened to have something npm linked, same story. Hoisting can drastically how your node_modules are structured..

I tried the versions you provided and the migration process worked fine, so there is very likely something in your env or in your project. For instance, if you create a project with 10.1, you will see both the compiler-cli and compiler packages are present in package.json. I don't know why they are missing in your project. `ngcc` comes from the compiler-cli package. So the compiler-cli package is installed, ngcc will be there. Why is it absent when you run stuff in CI? Maybe node_modules are cached incorrectly, maybe `npm install` failed. 

Things you could do it to narrow it down:

- Create a brand new project using 10.1 and compare package.json files. What is missing in your project etc.. Clearly compiler-cli and compiler are missing. Any other package missing? Do versions match? And once you reconcile that you can try migrating again.
- I often create a docker container to isolate myself from my env and use that to troubleshoot issues. No global modules issues in this case.

**Comment by crates** [comment]
Thanks for bearing with me, @vsavkin - I really appreciate you looking into this with me.

The version I had that was working earlier, on 10.1, did not include the `compiler-cli` or `compiler` packages for whatever reason. They must've somehow been included from downstream dependencies, b/c things were indeed working before without them listed.

If you really want to reproduce this issue, I suppose I could grant you access to my private repo. I have release tags from both before and after the upgrade path. My version 1.11.0 tag is from prior to the upgrade, when I was on Nx 10.1 and things were building okay. If you check out that tag and run the migration from there, I'm guessing you'll see the problem I was having.

Since you've indicated this wasn't an issue when creating a new Nx project on version 10.1, I went back and checked for what version I started this project on, initially. It looks like my original version was 9.2.2 of Nx, and somehow, the upgrade path from that version to 10.1 succeeded, while creating future problems down the line.

That's the best I know how to do. LMK if that's enough.

**Comment by playerx** [comment]
Hi @crates thanks for sharing your experience, because I've the same issue you had when upgrading to 10.4, now I'll follow your instructions 👍

**Comment by Manimozhi** [comment]
PS C:\projecs\nx-examples> npx nx migrate --run-migrations=migrations.json
'yarn' is not recognized as an internal or external command,
operable program or batch file.
C:\projecs\nx-examples\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: yarn tao migrate --run-migrations=migrations.json
...
Successfully finished migration-v11-router-initial-navigation-options
---------------------------------------------------------
Running migration update-10-0-0
    Updating @angular/cli to 10.0.0
Repository is not clean. Update changes will be mixed with pre-existing changes.
Using package manager: 'yarn'
Collecting installed dependencies...
Found 65 dependencies.
Fetching dependency metadata from registry...
  UPDATE package.json (3122 bytes)
| Installing packages (yarn)...

**Comment by JakubPawlak** [comment]
I had the same problem after migration to nx@12.10.0 in CI. Before migration there were no problems neither in docker nor on localhost. After migration localhost was working without issues but the error was shown in docker before linting.

For me the solution was to add @nrwl/cli to dev dependencies:
```
npm i -D @nrwl/cli
```
On localhost I had @nwrl/cli installed locally.
