### ISSUE TITLE
storybook schematics friendliness

### ISSUE THREAD

**Issue by kkoo95** [nrwl/nx#4104]
When adding storybook support to an "ESlinted" project, I identified a boilerplate steps that could be added to the install schematics.  
Sub files `.eslintrc.json` of storybook enabled libraries should also specifically refer to storybook's `tsconfig`:

```json
{
  "extends": "../../.eslintrc.json",
  "ignorePatterns": [
    "!**/*"
  ],
  "rules": {},
  "overrides": [
    {
      "files": ["*.ts", "*.tsx"],
      "parserOptions": { "project": ["./tsconfig.*?.json", "./.storybook/tsconfig.json"] }
    }
  ]
}
```
### Failure Logs
in IntelliJ, I get this ESLint error when opening a `.stories.ts` file

```console
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src\lib\frame\frame.component.stories.ts.
The file must be included in at least one of the projects provided.
```

### Environment
  nx : Not Found
  @nrwl/angular : 10.4.1
  @nrwl/cli : 10.3.2
  @nrwl/cypress : 10.4.1
  @nrwl/eslint-plugin-nx : 10.4.1
  @nrwl/express : Not Found
  @nrwl/jest : 10.4.1
  @nrwl/linter : 10.4.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.2
  @nrwl/web : Not Found
  @nrwl/workspace : 10.4.1
  typescript : 4.0.5

**Comment by iamandrewluca** [comment]
Duplicate #3867

**Comment by mandarini** [comment]
Hi @kkoo95 , thanks for filing an issue!

Please take a look at [this comment here](https://github.com/nrwl/nx/issues/3867#issuecomment-781941968)

I believe it should solve your issue!
