### ISSUE TITLE
Upgrade eslint-plugin-react-hooks to avoid warnings

### ISSUE THREAD

**Issue by therk** [nrwl/nx#4105]
## Current Behavior
Getting warning when running npm install and using eslint@7.12.1:
 WARN eslint-plugin-react-hooks@2.5.1 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.

## Expected Behavior
No warnings

## Steps to Reproduce
run npm install with a node project that depends on eslint@7.12.1

### Environment
  nx : 10.3.3
  @nrwl/angular : Not Found
  @nrwl/cli : 10.4.2
  @nrwl/cypress : 10.4.2
  @nrwl/eslint-plugin-nx : 10.4.2
  @nrwl/express : 10.4.2
  @nrwl/jest : 10.4.2
  @nrwl/linter : 10.4.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.4.2
  @nrwl/react : 10.4.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.4.2
  @nrwl/web : 10.4.2
  @nrwl/workspace : 10.4.2
  typescript : 4.0.5

**Comment by zaunermax** [comment]
This would also fix https://github.com/nrwl/nx/issues/3742

**Comment by ZackDeRose** [comment]
Adding as a note - I've investigated this briefly - while our eslint-plugin-react-hooks dependency has been updated, I'm seeing creating a blank react project does not install eslint itself - resulting in a similar warning message. I'll keep this alive until we can get a fix in for this issue. (Will make sure to mention to @jaysoo at our upcoming Nx react sync).

**Comment by ZackDeRose** [comment]
Looks like since this has been filed, we've updated to the latest version of `eslint-plugin-react-hooks` and are no longer seeing the warning. Will close out the issue accordingly. Thanks for creating this issue @therk !
