### ISSUE TITLE
Better typings for dataPersistence

### ISSUE THREAD

**Issue by rafaelss95** [nrwl/nx#4108]
## Problems
1. `state` on `dataPersistence` callbacks is nullable.

https://github.com/nrwl/nx/blob/8e519cd8e41e6db1036675c2d09843079681c851/packages/angular/src/runtime/nx/data-persistence.ts#L36-L40

https://github.com/nrwl/nx/blob/8e519cd8e41e6db1036675c2d09843079681c851/packages/angular/src/runtime/nx/data-persistence.ts#L75-L76

With strict type enabled, we can't use the state directly without checking its nullability before. Ex:

```ts
readonly test$ = createEffect(() =>
  this.actions$.pipe(
    concatMap(action => of(action).pipe(
      withLatestFrom(this.store$.select(someSelector)),
    ),
    navigation(AComponent, {
      run: (_, state) => {
        state.awesome // Type error as state is nullable
      },
    }),
  ),
);
```

2. Conditional return:

- If it's a non-dispatching effect then it should be `void`;
- If it's a dispatching effect then it could be either `Action` or `Observable<Action>`.

Note that currently I can write something like this:

```ts
readonly test$ = createEffect(() =>
  this.actions$.pipe(
    navigation(AComponent, {
      run: () => {
        someAction(); // missing return intentionally
      },
    }),
  ),
);
```

... without type errors :(. It would be awesome if we conditionally defined the correct type to avoid mistakes like this.

3. In documentation you say:

https://github.com/nrwl/nx/blob/8e519cd8e41e6db1036675c2d09843079681c851/packages/angular/src/runtime/nx/data-persistence.ts#L306-L307

_"[...] and forces the developer to handle errors [...]"_

... however the `onError` is optional. Maybe I just misunderstood the sentence?

4. Change from `any` to `unknown` in `onError`, in order to avoid some typos, while accessing props. Somewhat related to https://github.com/microsoft/TypeScript/issues/26174.

## Suggestions
For the points 1, 3 and 4, I got this idea (not sure if it's the best way, but...):

```diff
export interface FetchOpts<T, A> { 
-  id?(a: A, state?: T): any; 
+  id?(a: A, state: T): unknown;
-  run(a: A, state?: T): Observable<Action> | Action | void; 
+  run(a: A, state: T): Observable<Action> | Action | void;
-  onError?(a: A, e: any): Observable<any> | any; 
+  onError(a: A, e: unknown): unknown;
 } 
```

### Environment
Angular 10
Ngrx 10
NX 10

**Comment by brandonroberts** [comment]
@rafaelss95 better typings would be an improvement. Would you like to put in a PR for this?
