### ISSUE TITLE
Add support for `--create-commits` on nx migrate

### ISSUE THREAD

**Issue by JamesHenry** [nrwl/nx#4111]
## Description

`nx migrate` has some significant advantages over it's closest equivalent, `ng update`, but one nice feature that that tool does have is the `--create-commits` flag which causes it to create a commit after each migration has run successfully.

## Motivation

This can be really useful for larger version jumps and/or on larger monorepos where a lot of files are affected by the migrations.

It's still just as easy to reset back to where you started with, albeit you may have to page through a few more commits 😄

**Comment by RonanCodes** [comment]
Can we reopen this issue.
The --create-commits flag is wonderful when using Angular's ng update command.
As when you are reviewing a PR you can how each migration item affected the code base.

**Comment by JamesHenry** [comment]
Funnily enough, I had to emulate this manually again today, so definitely happy to reopen and I've raised it with Victor

**Comment by JohnnyDevNull** [comment]
I came across this today and would also be happy to have this some time in the future :)
