### ISSUE TITLE
`target` not inheriting correction from tsconfig for buildable/publishable react library

### ISSUE THREAD

**Issue by nmackey** [nrwl/nx#4115]
## Current Behavior
When building my bluidable/publishable react library I get `semantic error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.`  Even though my `tsconfig.base.json` has `"target": "es2015",` set.  My library `tsconfig.lib.json` and `tsconfig.json` do not override this value.

From what I can tell this issue https://github.com/nrwl/nx/issues/3601 & this fix https://github.com/nrwl/nx/pull/3661 seem to be the cause.  It appears that setting target to `undefined` when the format is 'esm' prevents the rollup plugin from inheriting the target correctly. https://github.com/mandarini/nx/blob/master/packages/web/src/builders/package/package.impl.ts#L193

If I change that line of code to something more like:
```
        const compilerOptionsESM = {
            rootDir: options.entryRoot,
            allowJs: false,
            declaration: true,
            paths: compilerOptionPaths
        };
        const compilerOptionsOther = {
            rootDir: options.entryRoot,
            allowJs: false,
            declaration: true,
            paths: compilerOptionPaths,
            target: 'es5',
        };
        const plugins = [
            copy({
                targets: convertCopyAssetsToRollupOptions(options.outputPath, options.assets),
            }),
            image(),
            typescript({
                check: true,
                tsconfig: options.tsConfig,
                tsconfigOverride: {
                    compilerOptions: config.format === 'esm' ? compilerOptionsESM : compilerOptionsOther
                }
            }),
            peerDepsExternal({
                packageJsonPath: options.project,
            }),
            postcss({
                inject: true,
                extract: options.extractCss,
                autoModules: true,
                plugins: [autoprefixer],
            }),
            localResolve(),
            resolve({
                preferBuiltins: true,
                extensions: fileExtensions,
            }),
            plugin_babel_1.getBabelInputPlugin({
                cwd: path_1.join(context.workspaceRoot, sourceRoot),
                rootMode: 'upward',
                babelrc: true,
                extensions: fileExtensions,
                babelHelpers: 'bundled',
                exclude: /node_modules/,
                plugins: [
                    config.format === 'esm'
                        ? undefined
                        : 'babel-plugin-transform-async-to-promises',
                ].filter(Boolean),
            }),
            commonjs(),
            filesize(),
            json(),
        ];
```

the target value gets inherited correctly

## Expected Behavior
Target should be correctly inherited from `tsconfig.base.json`

## Steps to Reproduce
Create a buildable/publishable react library that has ES5+ features and try to build it.

### Failure Logs
using `verbosity: 3` with the rollup typescript plugin the target is not set in the `parsed tsconfig`

with my fix `"target": 2,` (es2015) in the `parsed tsconfig`

**Comment by bcheidemann** [comment]
Hey, I'm having issues with this. Any word on when it will be fixed?

**Comment by ZackDeRose** [comment]
I've attempted a reproduction of this issue here: https://github.com/ZackDeRose/buildable-react-lib-4115

I'm finding with the latest Nx version, I'm unable to reproduce given the reproduction steps. If I'm missing something here please feel free to re-open with an explanation of what from my reproduction is lacking.

Thanks!!

**Comment by jayjnu** [comment]
This happened to me.

# Reproduction step

1. create a publishable core library  with property accessors defined

```
// @workspace/core

class Core {
  get data() {
    return 'hello';
  }
}
```

2.  build it
```
nx run build core
```

3. it would fail with message

```
semantic error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.
Bundle failed: core
```

# Solution

I solved it by setting `target: "es2015"` field to the library's `tsconfig.lib.json`;

```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../../dist/out-tsc",
    "types": ["node"],
    "target": "ES2015"
  },
  "files": [
    "../../../node_modules/@nrwl/react/typings/cssmodule.d.ts",
    "../../../node_modules/@nrwl/react/typings/image.d.ts"
  ],
  "exclude": ["**/*.spec.ts", "**/*.spec.tsx"],
  "include": ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx"]
}
```
Setting target to `tsconfig.json` didn't work.
Maybe it's my shallow understanding of nx project.  I guess each `tsconfig.json` per project seems to exist purely for editor support.

The config used in this line of code is a path to `tsconfig.lib.json`, from which `rollup-plugin-typescript2` runs its own build steps.

https://github.com/nrwl/nx/blob/159bc9986bcf83f30763e3dd0f18cd2905c03965/packages/web/src/builders/package/package.impl.ts#L194

**Comment by bcheidemann** [comment]
@jayjnu 

Could be an issue with the way the overrides are applied:

https://github.com/nrwl/nx/blob/159bc9986bcf83f30763e3dd0f18cd2905c03965/packages/web/src/builders/package/package.impl.ts#201

If tsconfig.lib.json doesn't define target, then it will be passed as an override but may be undefined. In this case. Perhaps this is overriding the value from tsconfig.json with undefined.

**Comment by bcheidemann** [comment]
> I've attempted a reproduction of this issue here: https://github.com/ZackDeRose/buildable-react-lib-4115
> 
> I'm finding with the latest Nx version, I'm unable to reproduce given the reproduction steps. If I'm missing something here please feel free to re-open with an explanation of what from my reproduction is lacking.
> 
> Thanks!!

I am unable to verify if this repo reproduces the issue or not as doing an npm install results in the following error:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/linter@999.9.12.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'buildable-react-lib-4115'
npm ERR! notarget 
```

Could you advise on how you were able to use this repo?

**Comment by bcheidemann** [comment]
@ZackDeRose 

I've submitted a PR replacing all @nrwl/* packages with the @latest version. When running:

```
npx nx build accessor-example
```

I get the error:

```
Error during bundle: Error: /home/ben/Code/buildable-react-lib-4115/libs/accessor-example/src/lib/example-class.ts(6,7): semantic error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.
Bundle failed: accessor-example
```

Based on this I would suggest for @nmackey or @ZackDeRose to reopen the issue.

**Comment by bcheidemann** [comment]
@ZackDeRose

Further to the above comment, removing the following line, as anticipated, results in a successful build:

https://github.com/nrwl/nx/blob/159bc9986bcf83f30763e3dd0f18cd2905c03965/packages/web/src/builders/package/package.impl.ts#L201

**Comment by bcheidemann** [comment]
@ZackDeRose 

I have opened a PR fixing this issue.
