### ISSUE TITLE
--dry-run flag fails for gateway on backend nest app

### ISSUE THREAD

**Issue by nhhockeyplayer** [nrwl/nx#4131]
nx --version
10.4.4

the following command results in files being populated to the project

nx generate @nrwl/nest:gateway user –-dry-run

```

macbookpro portal % nx --version
10.4.4
macbookpro portal % nx generate @nrwl/nest:gateway user –-dry-run
? What Nest project would you like to target? micro-root
CREATE apps/micro-root/src/user/user.gateway.spec.ts (446 bytes)
CREATE apps/micro-root/src/user/user.gateway.ts (238 bytes)
macbookpro portal % 
```

**Comment by mandarini** [comment]
Referencing [the other related issue here](https://github.com/nrwl/nx/issues/4130). These two issues I think are one. Looking into it.

**Comment by bekos** [comment]
@nhhockeyplayer seems like the first dash of `–-dry-run` is not correct 🤔 Anyways, I tried with the latest version of nx and seems to work fine, but feel free to re-open if you have more info. 
![image](https://user-images.githubusercontent.com/551595/110932702-7d615180-8334-11eb-9fbf-dd8010612b6f.png)
