### ISSUE TITLE
node builder does not minify when optimization=true

### ISSUE THREAD

**Issue by takakobem** [nrwl/nx#4141]
## Current Behavior

node builder does not minify with optimization=true due to 
https://github.com/nrwl/nx/blob/master/packages/node/src/utils/node.config.ts#L17-L22

## Expected Behavior

I think it should be minified when optimization=true.

**Comment by vsavkin** [comment]
@Cammisuli do you know why we chose not to minify?

**Comment by Cammisuli** [comment]
Hmm.. not entirely sure. That was done before my time. I don't see any issues with having it minimized now. But honestly, I don't think it really matters as much for Node apps, as much as it does for the we. 

This is easy to add from any one in the community if they'd like. 😄

**Comment by vandriesh** [comment]
@Cammisuli my guess it's not that easy since I couldn't find one

is there a working example or some code I can use for inspiration and adjust workspace.json to:
minimize the code
generate a unique name e.g. `[name.[hash].min.js`
