### ISSUE TITLE
WARNING in Conflict: Multiple assets emit different content to the same filename 3rdpartylicenses.txt

### ISSUE THREAD

**Issue by rakibulalam** [nrwl/nx#4143]
After running this command ` nx run myapp:build:production ` its showing  

> WARNING in Conflict: Multiple assets emit different content to the same filename 3rdpartylicenses.txt

**Comment by mandarini** [comment]
Hi there @rakibulalam ! Thanks for filing an issue!

Unfortunately I could not reproduce your issue. Could you provide some more information, and preferably a repository which I can use to reproduce the problem you are facing? Thank you very much in advance!

**Comment by rakibulalam** [comment]
Hello @mandarini 
Thanks for your reply. 
the warning has happened could be in webpack configuration. Running dev server is ok. when I try to build. It's showing the above issue. I am developing a design system for my current company using nx mono repo facilities. Unfortunately, when i am trying to build the production it's showing the above issue. do you wish to see any configuration for diagnosis the problem. please I can do it for resolving the unwanted issue.

**Comment by mandarini** [comment]
Hi @rakibulalam ,

Yes it would be very helpful if you provided your configuration, your setup, the result of `nx report`, the steps you followed to produce this. Any information that you can give. Also, if you try to reproduce this in a new setup, just to break down the steps and see where they fail..

Thank you!
