### ISSUE TITLE
Cannot build Angular Application with buildable library dependecies and --baseHref (or many other commands)

### ISSUE THREAD

**Issue by labeled** [nrwl/nx#4147]
## Current Behavior
After creating an Angular Application and some buildable libraries I cannot build using some available commands from the build UI in NX Console (or directly from cmd line). I am able to build --withDeps using no other flags but I must use some more. I tried building with aot, baseHref, and buildOptimizer and received the error "Unkown option" for each one.

## Expected Behavior
I expected to be able to build --withDeps and use the flags required to build my Angular Applications. I have not had it work in the past, but that doesn't mean I'm not doing anything wrong.

## Steps to Reproduce
Generate workspace, add application, add buildable library, run nx run project:build --withDeps --baseHref=/Studio/.

I can reproduce this without any code changes in nx-examples. Pull down the repo, npm install, and run this command: `ng build products --with-deps --baseHref=/Studio/`

### Failure Logs
```
> Executing task: ng build products --with-deps --baseHref=/Studio/ <

Unknown option: '--with-deps'
```

### Environment
  nx : Not Found
  @nrwl/angular : 10.3.1
  @nrwl/cli : 10.3.1
  @nrwl/cypress : 10.3.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.1
  @nrwl/linter : 10.3.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : Not Found
  @nrwl/web : Not Found
  @nrwl/workspace : 10.3.1
  typescript : 4.0.5

**Comment by labeled** [comment]
Wait one, I realized that nx-examples doesn't use buildable libraries. I'll update soon.

**Comment by jiayisheji** [comment]
@labeled You can go to `angular.json` to configure baseHref

**Comment by vsavkin** [comment]
@jdpearce had a PR implementing this (https://github.com/nrwl/nx/pull/3989), but decided to delay till after nx 11.

**Comment by fmuscolino** [comment]
@vsavkin Any update on the PR? 

We need to build a project --with-deps with the --base-href and it fails.
The problem is that we can't configure baseHref in angular.json since the baseHref is not fixed (depends on branch name and it's specified in our CI environment)
