### ISSUE TITLE
Running nx ngrx causing error

### ISSUE THREAD

**Issue by CharlieGreenman** [nrwl/nx#415]
Command
```
ng generate ngrx choose-size --module=apps/angular-pixel-illustrator/src/app/components/choose-size/choose-size.module.ts
```
Error: 
```
Error: Path "/__path__/__name@dasherize@if-flat__/__name@dasherize__.actions.ts" does not exist.
Path "/__path__/__name@dasherize@if-flat__/__name@dasherize__.actions.ts" does not exist.
```

Notable mentions
```
"@angular-devkit/core": "^0.5.4",
"@angular-devkit/schematics": "^0.5.5",
"@angular/cli": "1.7.1",
"@nrwl/schematics": "^0.11.1",
"@nrwl/nx": "^0.11.1"
```

I was wondering if anyone else is coming across the same issue ^, and if so, how did they solve it? Thank you.

**Comment by FrozenPandaz** [comment]
Hi @CharlieGreenman we are investigating this but if you could provide repo with the issue would help us greatly.

**Comment by CharlieGreenman** [comment]
I should be able to do that. Will do Saturday night Sunday morning ASAP.
Thank you.

**Comment by CharlieGreenman** [comment]
Providing something in moment.

**Comment by CharlieGreenman** [comment]
I've created a temp repo for this issue: https://github.com/CharlieGreenman/MonoAngularPixel

**Comment by FrozenPandaz** [comment]
Thank you for your reproduction! I was able to reproduce this.

**Comment by FrozenPandaz** [comment]
You should not need to install your own versions of `@angular-devkit/core` and `@angular-devkit/schematics`.

Fixing these dependencies allows you to generate ngrx again. You might have to remove your package-lock.json if you have errors after installing Nx.

I made a PR to your reproduction here: https://github.com/CharlieGreenman/MonoAngularPixel/pull/1

**Comment by CharlieGreenman** [comment]
@FrozenPandaz that did. Obviously we can look into, this particular scenario not affecting ngrx. Going to close, and if we would like to open another ticket for the above, by all means.
