### ISSUE TITLE
@nrwl/workspace:library schematics does not generate "src" with unitTestRunner=none

### ISSUE THREAD

**Issue by nartc** [nrwl/nx#4151]
## Current Behavior

As title said, when `ng generate @nrwl/workspace:library` is executed with the `--unitTestRunner` flag set to `none`, Nx does not generate the `src` directory anymore. With default `unitTestRunner`, the `src` directory (with appropriate files) is generated properly.

## Expected Behavior

This is a regression. `ng generate @nrwl/workspace:library --unitTestRunner=none` should generate the "src" dir with appropriate files.

## Steps to Reproduce

- Run `npx nx/ng generate @nrwl/workspace:library --name=core --directory=api --unitTestRunner=jest --testEnvironment=jsdom`

### Environment

```
  nx : Not Found
  @nrwl/angular : 10.4.4
  @nrwl/cli : 10.4.4
  @nrwl/cypress : 10.4.4
  @nrwl/eslint-plugin-nx : 10.4.4
  @nrwl/express : Not Found
  @nrwl/jest : 10.4.4
  @nrwl/linter : 10.4.4
  @nrwl/nest : 10.4.4
  @nrwl/next : Not Found
  @nrwl/node : 10.4.4
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.4.4
  @nrwl/web : Not Found
  @nrwl/workspace : 10.4.4
  typescript : 4.0.5
```

**Comment by mehrad-rafigh** [comment]
I modified the test of the lib schematics, but the test still passed

**Comment by FrozenPandaz** [comment]
This has been solved :tada: :

![image](https://user-images.githubusercontent.com/8104246/108435417-62109400-7217-11eb-900f-d0282f1cc7af.png)
