### ISSUE TITLE
--verbose option not taken into account for test commands

### ISSUE THREAD

**Issue by timbakkum** [nrwl/nx#4160]
## Current Behavior
using the nx console or by manually using the cli, passing --verbose flag to a test command like `nx run lib:test --verbose` or `nx run lib:test -- --verbose`.

running `jest --verbose` in the lib/app I want to test does correctly apply the flag's functionality. 

## Expected Behavior
I expect the expected behavior of this flag to be active: "Display individual test results with the test suite hierarchy."

## Steps to Reproduce
run a test command using the verbose flag using the nx console or the nx cli

### Environment
```
nx report                                                            

>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.2.1
  @nrwl/cypress : 10.2.1
  @nrwl/eslint-plugin-nx : 10.2.1
  @nrwl/express : Not Found
  @nrwl/jest : 10.2.1
  @nrwl/linter : 10.2.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 10.2.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.2.1
  @nrwl/web : 10.2.1
  @nrwl/workspace : 10.2.1
  typescript : 3.9.7
```

**Comment by paulantoine2** [comment]
It doesn't make any difference for build commands either. Which is annoying because my CI crash after 
`Using 6 workers with 2048MB memory limit` without any error.

**Comment by bopm** [comment]
And yet, it's not working even now. I have a project upgraded to ng 12, which is no longer build after that being stuck in `Generating browser application bundles (phase: building)` and verbose doing nothing for the build. 

cc @vsavkin

**Comment by tariknz** [comment]
Yep nx doesn't pass the arg to the ng cli, if you run `ng run my-app:test --verbose` it works fine.

**Comment by laggingreflex** [comment]
Was this fixed? I'm using a Next.js project/app and it's not working in it either.

**Comment by FacePalmDev** [comment]
Come on, it's 2022. Please fix this

**Comment by peter-coastpay-com** [comment]
this is still an issue, --verbose flag does nothing

**Comment by bopm** [comment]
It's good to see that this project keeps a long line of Angular Core team traditions on how to deal with issues. :trollface:

**Comment by kwiniarski97** [comment]
It might happen that you are not having a `--output-style=stream` added as a flag to your `nx affected ...` script. e.g. 
```
nx affected:build --verbose --output-style=stream --base=HEAD~1
```

**Comment by alexhad** [comment]
running the test with `nx run my-app:test --verbose` works!

**Comment by nicolasagorreca-tc** [comment]
It works for me adding `--output-style=static`
