### ISSUE TITLE
Caching & dependencies between targets

### ISSUE THREAD

**Issue by studds** [nrwl/nx#4162]
## Description

Adding the ability to specify dependencies between targets (and optionally, configurations) and ensuring these targets / configurations have been run before executing the current target.

## Motivation

I've got a workspace with a lot of projects. Each of those projects have "build" and "deploy" targets. When running "deploy", I first have to make sure I've already run "build", otherwise (obviously) I'll deploy the wrong version.

This is on top of dependencies between projects, which I also have.

The ideal is that when I run `nx run my-project:deploy --withDeps` it should first execute `my-project:build`.

An additional wrinkle is that, regardless of the configuration I'm using to deploy, I always want to run the `production` build configuration.

## Suggested Implementation

Ideally in `angular.json`, add a field to each target: `dependsOnTargets`. This is an array of strings formatted `{target}[:{configuration}]`.

Before running any target, nx should first run each target in `dependsOnTargets`. Just as if a target is run directly, the cached result should be used if available.

## Alternate Implementations

Essentially the same as above, but in `nx.json` instead.

**Comment by vsavkin** [comment]
This is the recommended way to do it:

```
        "deploy": {
          "builder": "@nrwl/workspace:run-commands",
          "outputs": ["dist/deploy/mproj"]
          "options": {
            "commands": [
                "nx run myproj:build::production",
                "nx deploy-base myproj"
            ],
            "parallel": false
          }
        }
```

Some things to consider:
* You often want to run tasks in parallel (for perf), so now we need to express that aspect. 
* We want to cache every target, such that we can reuse partial computation. 

Given that composing processes seemed like the easiest way to do it. And Nx already deals with nested Nx invocation to provide good output.

Does it solve your problem?

**Comment by studds** [comment]
Yes it does, thanks! Don't know why I didn't think of that myself!

My two small reservations are that it's somewhat long-winded and that it's not explicit - the dependency is implicit in how the commands are put together. But those reservations together probably don't justify any change.

**Comment by studds** [comment]
Actually, thinking through this a bit further... would this mean that I'd need to have a seperate target for each deploy environment? Eg:

```
        "deploy": {
          "builder": "@nrwl/workspace:run-commands",
          "outputs": ["dist/deploy/mproj"]
          "options": {
            "commands": [
                "nx run myproj:build::production",
                "nx deploy-base myproj"
            ],
            "parallel": false
          }
        },
        "deploy-test": {
          "builder": "@nrwl/workspace:run-commands",
          "outputs": ["dist/deploy/mproj"]
          "options": {
            "commands": [
                "nx run myproj:build::production",
                "nx deploy-base myproj --configuration test"
            ],
            "parallel": false
          }
        },
        "deploy-staging": {
          "builder": "@nrwl/workspace:run-commands",
          "outputs": ["dist/deploy/mproj"]
          "options": {
            "commands": [
                "nx run myproj:build::production",
                "nx deploy-base myproj --configuration staging"
            ],
            "parallel": false
          }
        },
        "deploy-prod": {
          "builder": "@nrwl/workspace:run-commands",
          "outputs": ["dist/deploy/mproj"]
          "options": {
            "commands": [
                "nx run myproj:build::production",
                "nx deploy-base myproj --configuration prod"
            ],
            "parallel": false
          }
        },
```

**Comment by mievoe** [comment]
@studds You can use the [`args` property](https://nx.dev/latest/angular/plugins/workspace/executors/run-commands#properties) to provide some context to your `deploy` target.

**Comment by rgoomar** [comment]
Just adding on that this type of feature would be great to have. I'm running into a similar issue and using the `run-commands` with chained commands feels like a hack and does not work in the desired way I want.

For example, if I have Project X which has a target called `serve` that depends on Project Y and Project Z to be served as well prior to it being run, if I chain them, since it starts a server for each, it doesn't have a graceful "end" to the task since it will end with like `Served on localhost:3000`. The problem here is that since it runs the first Project X serve, it ends up not continuing since the command hasn't technically "finished". 

It would be nice to just have something like Gradle's `dependsOn` or Bazel's `:deps` to explicitly define target dependencies. It also makes it more clear so you don't have to have separate targets and create a "wrapper" target that encompasses those.

**Comment by sweepy84** [comment]
Really need this feature too. Can be easily done with [Turborepo](https://turborepo.org/)
