### ISSUE TITLE
Question - Is there a command to migrate from tslint to eslint?

### ISSUE THREAD

**Issue by danzrou** [nrwl/nx#4170]
## Description
As the Slack link in docs does not work - asking it here.

Thanks!

**Comment by ryancraigmartin** [comment]
Hey @danzrou! You can join the Slack community with this [link.](https://join.slack.com/t/nrwlcommunity/shared_invite/enQtNzMwMTQ2MjY0MDA1LWE4ZDZiYjM5ZjE0MWVjYmVmODM1MDEyZGU5NzA2YTM2MDM2ZDY3Yzg4YWU4MDI4YTcwZTM1ZWRjNzE5M2YzY2Y).
