### ISSUE TITLE
Expandable Env Variables

### ISSUE THREAD

**Issue by lucasmonstro** [nrwl/nx#4172]
## Description
I want to know if is possible use https://github.com/motdotla/dotenv-expand?

## Motivation
I will avoid a lot of dry using this approach.

## Suggested Implementation
https://github.com/motdotla/dotenv-expand

**Comment by alitnk** [comment]
+1
 I would also like to know about this.

**Comment by hassankhan** [comment]
@vsavkin Please consider re-opening this issue; as @lucasmonstro said this would help a lot for DRY. I'd like to be able to set a root `.env` and app-specific `.env` files that use variable expansion to grab variables from the root `.env`.

**Comment by ontoneio** [comment]
Solution that I have found is to use dotenv-cli which supports variable expansion. [Dotenv-cli](https://github.com/entropitor/dotenv-cli)
Like so in your run-commands executor.
"commands": [{
		"command": "dotenv -e ./.env -- bash -c 'command-to-run $EXPANDED_VARIABLE'"
				}],

**Comment by DesertFoxNV** [comment]
Also interested in this as the NestJS Config module allows expansion, it would be nice to see support for expansion in the workspace and app level .env files.

**Comment by noahmayr** [comment]
+1 this would be very useful
