### ISSUE TITLE
[angular:package] updateBuildableProjectDepsInPackageJson includes dependencies only from `.spec.ts` file

### ISSUE THREAD

**Issue by lacolaco** [nrwl/nx#4174]
## Current Behavior

When I build Angular publishable package with Nx, output `package.json` contains some dependencies added by `updateBuildableProjectDepsInPackageJson` feature. But it includes some dependencies which is used only in `.spec.ts`. 

## Expected Behavior

Extract missing dependencies from only library code which is referred from `tsconfig.lib.json`. 

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

```
>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : 10.4.4
  @nrwl/cli : 10.3.3
  @nrwl/cypress : 10.4.4
  @nrwl/eslint-plugin-nx : 10.4.4
  @nrwl/express : Not Found
  @nrwl/jest : 10.4.4
  @nrwl/linter : 10.4.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.4.4
  @nrwl/web : Not Found
  @nrwl/workspace : 10.4.4
  typescript : 4.0.5
```

**Comment by RGunning** [comment]
Running into the same issue as well with storybook stories. They are excluded by the tsconfig.lib.json, but @nrwl/angular:package is adding @storybook as a PeerDependency because of the updateBuildableProjectDepsInPackageJson option

**Comment by pvds** [comment]
I don't see a solution here; running into the same issue.
