### ISSUE TITLE
Next.js nx plugin breaks standard next.js file loading for svgs

### ISSUE THREAD

**Issue by joshbuckley182** [nrwl/nx#4182]
## Current Behavior
When importing css which uses svgs via `url(...)` (in my case https://github.com/lipis/flag-icon-css), those svgs are handled incorrectly. 

This appears to be caused by https://github.com/nrwl/nx/blob/master/packages/next/src/utils/config.ts#L50-L82, which overrides next's normal loading in https://github.com/vercel/next.js/blob/master/packages/next/build/webpack/config/blocks/css/index.ts#L289-L312. 

The nx next.js plugin adds it's own svg handling _after_ my own configuration (from `next.config.js`), making it ugly to work around. 

## Expected Behavior
For these svgs to be handled in the same way as in a non-nx next.js project. 

## Steps to Reproduce
- Create fresh next.js and nx+next.js projects
- Add css, ie `npm i flag-icon-css` (from https://github.com/lipis/flag-icon-css)
- Import css into `pages/_app`, ie `import 'flag-icon-css/css/flag-icon.css'`
- Add `<span className="flag-icon flag-icon-gb"></span>` somewhere in `pages/index`
- Observe that the svg is correctly loaded in the next.js project, but not in the nx+next.js one

### Failure Logs
n/a

### Environment
```
  nx : 10.3.0
  @nrwl/angular : 8.12.11
  @nrwl/cli : 10.2.1
  @nrwl/cypress : 10.2.1
  @nrwl/eslint-plugin-nx : 10.2.1
  @nrwl/express : Not Found
  @nrwl/jest : 10.2.1
  @nrwl/linter : 10.2.1
  @nrwl/nest : Not Found
  @nrwl/next : 10.2.1
  @nrwl/node : Not Found
  @nrwl/react : 10.2.1
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 10.2.1
  @nrwl/web : 10.2.1
  @nrwl/workspace : 10.2.1
  typescript : 3.9.7
```

**Comment by joshbuckley182** [comment]
# Workaround

As the next.js plugin adds webpack rules _after_ those I define in `next.config.js`, I have overridden the `push` method on the `rules` array to intercept and prevent this svg rule from being added. 

``` 
// next.config.js

module.exports = {
  webpack(config) {
    // Prevent nx from adding an svg handler - stick to what is provided by
    // nextjs or that we have defined ourselves.
    config.module.rules.push = (...items) => {
      Array.prototype.push.call(
        config.module.rules,
        ...items.filter((item) => item.test.toString() !== '/\\.svg$/')
      )
    }

    return config
  },
}
```

**Comment by threehams** [comment]
Thank you for the workaround. I spend longer than I'd like to admit trying to figure out why `svg` imports wouldn't work for a brand new setup; having Webpack rules injected _after_ `next.config.js` is completely unexpected.

**Comment by paustint** [comment]
THANK YOU SO MUCH! I wont get the last couple of hours of my life back, but I can now move on!

Appreciate you posting the workaround 🎉
