### ISSUE TITLE
bug(schematics/workspace)Camel case app name creates 2 seperate folders.

### ISSUE THREAD

**Issue by Yonet** [nrwl/nx#42]
schematics @nrwl/schematics:app --name=camelCase
Creates camel-case folder which has src/app/app.module
Also creates  camelCase folder with e2e/, src/assets, src/environments

**Comment by vsavkin** [comment]
Fixed here https://github.com/nrwl/nx/commit/04545116f0282bbbd4bcef08d7ba8b5abb1bf709
