### ISSUE TITLE
Warning: Fell back to using 'fs' to identify file_path as deleted

### ISSUE THREAD

**Issue by rfprod** [nrwl/nx#4201]
## Current Behavior

I renamed a file, and now I have a warning in the terminal that suggests to file a bug report.

## Expected Behavior

No warning in the terminal when removing/renaming workspace files, and running commands after that.

## Steps to Reproduce

Rename a file. For example `apps/some-app-e2e/src/fixtures/example.json` -> `apps/some-app-e2e/src/fixtures/credentials.json`.
Run command `npx nx e2e some-app-e2e`.

### Failure Logs

```bash
ng run zzz-e2e:e2e --watch 
Warning: Fell back to using 'fs' to identify apps/zzz-e2e/src/fixtures/example.json as deleted. Please open an issue at https://github.com/nrwl/nx so we can investigate.
```

### Environment

Cli is installed as a global dependency.

```bash
$ sudo npm list -g --depth=0
[sudo] password for suser: 
/usr/lib
├── @angular/cli@11.0.2
├── @compodoc/compodoc@1.1.11
├── @nestjs/cli@7.5.3
├── @ngxs/cli@2.0.0
├── @nrwl/cli@10.4.4
├── asar@3.0.3
├── clang-format@1.4.0
├── commitizen@4.2.2
├── cz-conventional-changelog@3.3.0
├── firebase-tools@8.16.2
├── madge@3.12.0
├── npm@6.14.9
├── npm-check-updates@10.2.2
├── svgo@1.3.2
├── typescript@4.1.2
└── yarn@1.22.10

```

```
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.3
Node: 14.15.1
OS: linux x64

Angular: 11.0.3
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1001.7
@angular-devkit/build-angular      0.1100.3
@angular-devkit/core               11.0.3
@angular-devkit/schematics         11.0.3
@angular/cdk                       11.0.1
@angular/flex-layout               11.0.0-beta.33
@angular/material                  11.0.1
@angular/material-moment-adapter   11.0.1
@schematics/angular                11.0.3
@schematics/update                 0.1100.3
rxjs                               6.6.3
typescript                         4.0.5
```

```bash
>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : 10.4.4
  @nrwl/cli : 10.4.4
  @nrwl/cypress : 10.4.4
  @nrwl/eslint-plugin-nx : 10.4.4
  @nrwl/express : Not Found
  @nrwl/jest : 10.4.4
  @nrwl/linter : 10.4.4
  @nrwl/nest : 10.4.4
  @nrwl/next : Not Found
  @nrwl/node : 10.4.4
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.4.4
  @nrwl/web : Not Found
  @nrwl/workspace : 10.4.4
  typescript : 4.0.5
```

**Comment by cyrus-za** [comment]
Also running into this after deleting unused files from libs/

**Comment by R4VANG3R** [comment]
Also running into this issue when running a React project with version: 10.3.1

**Comment by s4m0r4m4** [comment]
I ran into this problem as well. To reproduce, I moved a file using drag-n-drop in the VS Code file explorer on the left. Then ran `nx build <my proj>` and received the following two error messages:

- Warning: Fell back to using 'fs' to identify apps/canvas-render-test/src/services/test.service.spec.ts as deleted. Please open an issue at https://github.com/nrwl/nx so we can investigate.
- Warning: Fell back to using 'fs' to identify libs/lib-images/src/lib/interfaces/aim-dimensioned-located-item.interface.ts as deleted. Please open an issue at https://github.com/nrwl/nx so we can investigate. 

Potentially an issue on the VS Code side, since they have also been having issues changing import paths when I do this, related issue here: https://github.com/microsoft/TypeScript/issues/40386

**Comment by crates** [comment]
Just wanted to say, me too. I renamed a library (including everything that referenced it), and everything still broke.

**Comment by crates** [comment]
Looks like the error self-resolved after a successful git commit.

**Comment by miluoshi** [comment]
This warning is really annoying and I honestly don't understand why I get it for deleted files. 

But what I found when searching in nrwl/nx codebase was that it should be removed by v10.2 as [this jsdoc line](https://github.com/nrwl/nx/blob/8e519cd8e41e6db1036675c2d09843079681c851/packages/workspace/src/core/hasher/git-hasher.ts#L123) for a function printing this warning is saying. @vsavkin can it be removed already? Thanks

**Comment by bekos** [comment]
@miluoshi I prepare a PR that is going to resolve the root cause of this warning, be patient 😃

**Comment by miluoshi** [comment]
@bekos awesome, thanks! 🚀

**Comment by mrsshilpad** [comment]
I see this issue everytime I define a new story " Fell back to using 'fs' to identify". What is the concrete solution to it?

**Comment by mrsshilpad** [comment]
Thanks! Yes, it fixed for me too but then I wasn't able to see my component in storybook, so I had to restart everything. How is committing a concrete solution?

**Comment by mrsshilpad** [comment]
I see my stories missing every now and then, guess this is different issue. But annoying.
