### ISSUE TITLE
Angular Prod Building Failing 

### ISSUE THREAD

**Issue by treveshan** [nrwl/nx#4211]
## Current Behavior
When running nx build --prod. Build fails due to missing Modules.

## Expected Behavior
When running nx build --prod. Should create production artifacts in bin/app folder

### Failure Logs
ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/@nestjs/common/cache/cache.providers.js
Module not found: Error: Can't resolve 'cache-manager' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\@nestjs\common\cache'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/fastify-plugin/plugin.js
Module not found: Error: Can't resolve 'console' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\fastify-plugin'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/cookie-signature/index.js
Module not found: Error: Can't resolve 'crypto' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\cookie-signature'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/etag/index.js
Module not found: Error: Can't resolve 'crypto' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\etag'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/destroy/index.js
Module not found: Error: Can't resolve 'fs' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\destroy'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/etag/index.js
Module not found: Error: Can't resolve 'fs' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\etag'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/express/lib/view.js
Module not found: Error: Can't resolve 'fs' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\express\lib'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/fastify-static/index.js
Module not found: Error: Can't resolve 'fs' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\fastify-static'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/fastify-static/lib/dirList.js
Module not found: Error: Can't resolve 'fs' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\fastify-static\lib'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/fastify-swagger/static.js
Module not found: Error: Can't resolve 'fs' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\fastify-swagger'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/fastify-swagger/dynamic.js
Module not found: Error: Can't resolve 'fs' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\fastify-swagger'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/fs.realpath/index.js
Module not found: Error: Can't resolve 'fs' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\fs.realpath'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/fs.realpath/old.js
Module not found: Error: Can't resolve 'fs' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\fs.realpath'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/glob/glob.js
Module not found: Error: Can't resolve 'fs' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\glob'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/glob/sync.js
Module not found: Error: Can't resolve 'fs' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\glob'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/mime/mime.js
Module not found: Error: Can't resolve 'fs' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\mime'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/send/index.js
Module not found: Error: Can't resolve 'fs' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\send'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/express/lib/request.js
Module not found: Error: Can't resolve 'http' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\express\lib'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/express/lib/response.js
Module not found: Error: Can't resolve 'http' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\express\lib'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/express/lib/application.js
Module not found: Error: Can't resolve 'http' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\express\lib'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/express/lib/request.js
Module not found: Error: Can't resolve 'net' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\express\lib'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/destroy/index.js
Module not found: Error: Can't resolve 'stream' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\destroy'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/send/index.js
Module not found: Error: Can't resolve 'stream' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\send'

ERROR in E:/Systems/EasyReports/src/easy-reports/node_modules/body-parser/lib/read.js
Module not found: Error: Can't resolve 'zlib' in 'E:\Systems\EasyReports\src\easy-reports\node_modules\body-parser\lib'

### Environment
  nx : Not Found
  @nrwl/angular : 10.3.1
  @nrwl/cli : 10.3.1
  @nrwl/cypress : 10.3.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.1
  @nrwl/linter : 10.3.1
  @nrwl/nest : 10.3.1
  @nrwl/next : Not Found
  @nrwl/node : 10.3.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.1
  @nrwl/web : Not Found
  @nrwl/workspace : 10.3.1
  typescript : 3.9.7

**Comment by FrozenPandaz** [comment]
It seems like you are importing a library which uses `@nestjs` into your `@angular` application. This will cause an error with the build because the Angular application is built for the web whereas the `@nestjs` was intended for Node.

**Comment by treveshan** [comment]
Thank you. Its seems I had swagger decorators on a few modals causing this issues.
