### ISSUE TITLE
Angular server side rendering failing

### ISSUE THREAD

**Issue by kedevked** [nrwl/nx#4212]
Adding ssr to angular does not render the page.

Steps to reproduce

- create workspace (with angular nest)

- adding ssr with ( ` ng add @nestjs/ng-universal`)

- update the nestjs to render the generated file

Please consider my repo here: https://github.com/kedevked/angular-nest

**Comment by mehrad-rafigh** [comment]
@kedevked you are not using the ssr lib correctly. Please refer to documentation on how to use [ng-universal](https://github.com/nestjs/ng-universal)

**Comment by kedevked** [comment]
Sorry, you were right. There were some module to be imported

**Comment by JizZuS** [comment]
@kedevked How did you manage to get this working? I just can't get past this error while accessing the server via browser:

`Error: ENOENT: no such file or directory, open 'C:\..\repo_root\app.component.html'`

Any help would be very appreciated. Thank you.

**Comment by kedevked** [comment]
Hello @JizZuS, I just published a video [here](https://www.youtube.com/watch?v=eO_4iN1u21g&ab_channel=edkeveked) outlining my steps

**Comment by samosunaz** [comment]
I was struggling with this, but managed to make it work, you can see the instructions here https://samosunaz.hashnode.dev/nestjs-angular-universal-in-an-nx-workspace
