### ISSUE TITLE
Creating multiple back end applications throws error `Path "/apps/X/proxy.conf.json" already exist.`

### ISSUE THREAD

**Issue by davecranwell-vocovo** [nrwl/nx#4215]
## Current Behavior
If I create a React app, then an express app with `--frontendProject=myreactapp`. I see a `proxy.conf.json` created in the React app codebase. 

If I then add a second express app, also with the same `frontendProject`, I get the error
`Path "/apps/myreactapp/proxy.conf.json" already exist.` and the generator appears to bail: no further files are created or changed.

I have to wonder if I'm doing something fundamentally wrong by having 2 APIs, but this can't be that unusual in a microservices environment.

I've tried using `--force` but it still complains. Ideally it shouldn't have to use force though as multiple apis doesn't seem outlandish.

## Expected Behavior
I'd expect the second app to be appended to the object in `proxy.conf.json`.

## Steps to Reproduce
1. Create brand new NX project
2. Add React front end
3. Add Express backend, linked to front end
4. Add second Express backend, linked to front end

### Environment
OSX Catalina
Node 12.16.2
@nrwl/workspace 10.4.4

**Comment by mehrad-rafigh** [comment]
I can reproduce this as well, when I adjust the test. I will take a look at this and open a PR

**Comment by bekos** [comment]
@mehrad-rafigh do you still want to send a PR? 😃

**Comment by mehrad-rafigh** [comment]
@bekos sry I forgot about this. I will finish the PR tonight

**Comment by mehrad-rafigh** [comment]
@bekos I opened a PR. Could you please review it?
