### ISSUE TITLE
Implicit dependencies outside the Angular root

### ISSUE THREAD

**Issue by evtk** [nrwl/nx#4220]
I'm not sure if it's a bug or simply not designed as is, but I can't seem to register implicit dependencies that are living 'outside' of the angular root. 

Repo setup:

/client/angular/ -> contains all Angular code.
/client/tools/ -> contains tooling used by all client platforms (in this case, mock server)

So we have defined some mock yaml files inside this client/tools folder. Some of these mock files are used/loaded inside unit test in Angular. Now if one changes a mock file, it could potentially lead to a failing unit test. So, any change to the mock files should trigger an implicit dependency to rebuild all Angular projects.

I thought I could arrange this with the following configuration in nx.json:

```
  "implicitDependencies": {
    "angular.json": "*",
    "package.json": "*",
    "tslint.json": "*",
    "nx.json": "*",
    "tsconfig.base.json": "*",
    "../tools/mock-server/**/*.*": "*"
},
```
But a change in the mock files will simply not trigger all projects to be 'affected'.

I followed the example in the docs (with the styles glob) and that does trigger a change. Is this not designed like this and am I not allowed to do this?

How can I achieve my goal :). Thanks!

**Comment by FrozenPandaz** [comment]
@bekos can you take a look at this please? I thought this was supported.

If possible, please provide a repo that we can pull down to take to help us investigate the issue.

**Comment by bekos** [comment]
@EvtK Can you please explain a bit more how your structure is? More specifically where your .git folder is and also from which directory you execute your nx commands (I suppose /client/angular, right?).

**Comment by EvtK** [comment]
hi @bekos, sorry for the late response. I guess I have missed your update :)

this is our structure:

```
monorepo root
  - /client/angular 
  - /client/static
  - /client/tools
```

we have a 'VS code client workspace' located under /client/. 

the .git folder is located in the root of mono repo (so not directly under client/angular)

nx commands are indeed executed from client/angular

hope this helps!

**Comment by EvtK** [comment]
@bekos can you check-in? this still seems to be an issue on our side :)

**Comment by 0xR** [comment]
same here for a NodeJS project

**Comment by oschlegel** [comment]
I'm having the same issue, is there already a solution?

**Comment by EvtK** [comment]
@bekos @FrozenPandaz any progress on this?

**Comment by yasinkocak** [comment]
@bekos @FrozenPandaz any progress on this?

**Comment by cyrixmorten** [comment]
Am working on a document describing how we use a small script to create a hash file that can be added as implicit dependency: [Detect file changes outside Nx workspace](https://docs.google.com/document/d/1UuSgdLQWTLdlglSntXZu9oNXWuWh0BJzwLv3Mo-N_NE/edit?usp=sharing)
