### ISSUE TITLE
Can't resolve 'stream' and 'zlib' when build app

### ISSUE THREAD

**Issue by EmilBuszylo** [nrwl/nx#4233]
## Current Behavior
I'm trying to use [@react-pdf/renderer ](https://www.npmjs.com/package/@react-pdf/renderer) in react project based on nx. During build app (or just run dev server), I got errors:
![pdf errors](https://user-images.githubusercontent.com/20420991/101622149-f9d35400-3a16-11eb-8c5e-4071c9d06983.png)

I was trying to resolve the problem by install stream and zlib packages but after that, during build time I get:
![zlib_bindings_error](https://user-images.githubusercontent.com/20420991/101622185-05267f80-3a17-11eb-9ddd-1f46adb29169.png)

## Expected Behavior
Building and running project with installed @react-pdf/renderer package.

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

 ```
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.4.4
  @nrwl/cypress : 10.4.4
  @nrwl/eslint-plugin-nx : 10.4.4
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.1
  @nrwl/linter : 10.3.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.4.4
  @nrwl/react : 10.3.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.4.4
  @nrwl/web : 10.3.1
  @nrwl/workspace : 10.3.1
  typescript : 4.1.2

```

**Comment by FrozenPandaz** [comment]
Hi, please provide a repo that we can pull down to help us investigate the issue.

**Comment by voznik** [comment]
hi @EmilBuszylo 
the problem is that you want to use `typescript@4.1.2`
I had the same error when I was trying to build angular application with latest (11.0.*) Angular & Nx clis AND `"disableTypeScriptVersionCheck": false` parameter
try to install `typescript @4.0.5`

**Comment by knoefel** [comment]
@voznik Thx for your suggestions. I'm exactly in the same situation right now (using nx and  `@react-pdf/renderer`)  I set the typescript version to `typescript@4.0.3`. But the error persists (even after a clean install and removing the `node_modules` folder). Do you have maybe any other ideas?

**Comment by knoefel** [comment]
@EmilBuszylo did the suggestion from @voznik resolved your problem?

**Comment by Abdulrahman-Falyoun** [comment]
Same here
