### ISSUE TITLE
Angular2 conversion tool/schematic for Nrwl NxCloud

### ISSUE THREAD

**Issue by nhhockeyplayer** [nrwl/nx#4237]
## Description

Field observations I see are citing demand for converter migration tool for old angular 2 projects based on .angular cli build config files and intelligently integrating them into the scaffold of apps/servers

## Motivation

Large scale projects in the field citing demand (huge banks with large angular 2 footprints) would like to have their projects immediately converted to this new platform.

## Suggested Implementation

- a schematic
- maybe an outright conversion tool that is smart enough to flag naming of projects and their build semantics & configurations

maybe in initial interrogation of hosts ports domain names etc... to minimize the difficulty

## Alternate Implementations

cli is the way

**Comment by FrozenPandaz** [comment]
Hi, that is quite a few versions you have to upgrade :sweat_smile:.

Good news is.. we have automatic migrations going all the way back to before nx 1.0! (which used Angular 5 If I recall correctly) I would do this incrementally so.. updating to 6 first.. then 7.. all the way until 11. This should work for trivial workspaces but.. there's a lot of room for error for non-trivial workspaces so this might not work.

There are a couple of different strategies that you can try if that is not working:

1. Create a new workspace and copy your code over:

We have a guide on how to migrate existing codebases in general to Nx: https://nx.dev/latest/angular/migration/overview

We even have a guide on how you can preserve your git history when migrating to Nx: https://nx.dev/latest/angular/migration/preserving-git-histories

2. Follow the Angular Update Guide and then add Nx on top.

You can refer to the update guide: https://update.angular.io/?v=2.0-11.0 to move your project from Angular 2 to Angular 11.

After, you can add the latest version of Nx on top of that: https://nx.dev/latest/angular/migration/migration-angular

If you have trouble.. My best advice is to join the community slack and asking for help there. The community is great and very helpful :smile:

**Comment by nhhockeyplayer** [comment]
for me it's actually simpler

large angular 5 project

they want to move to Nx workspace

several apps and servers

what would you recommend

**Comment by nhhockeyplayer** [comment]
also
im trying to get a feel understanding for whats taking place under the hood with these

```
npm run build.ionic.e2ask
npm run prepare.ionic.e2ask
npm run sync.ionic.e2ask
npm run clean.ionic.e2ask
```


can you elaborate? 
as an ionic developer I execute them but dont see anything going on
itd be nice to hear whats happening where and how

**Comment by nhhockeyplayer** [comment]
like how does one do an ionic repair

**Comment by nhhockeyplayer** [comment]
and how one would do a manual elaborate APK build with SSL certs and such from command line
