### ISSUE TITLE
NX workspace configuration files

### ISSUE THREAD

**Issue by pgerhard** [nrwl/nx#4251]
## Description
I use NX workspaces to develop multiple different applications using a variety of different frameworks (vanilla NodeJS, Angular and React). Thus when creating my initial workspace using `npx create-nx-workspace@latest` and when asked `What to create in the new workspace` I configured it to be `empty`. 
This results in a workspace which follows the overall structure mentioned [here](https://nx.dev/latest/angular/workspace/workspace-overview).
If however I create an NX workspace and when asked `What to create in the new workspace` I select `angular` the overall structure is as described [here](https://nx.dev/latest/angular/workspace/configuration). 

In my eyes this leads to two problems

1. It is confusing that when reading the docs there are two contradicting statements (both documents state that files are present in every NX workspace.
2. It may lead some people to conclude that it is not possible to develop a React and Angular application within the same NX workspace

This is why I would suggest no longer generating the `angular.json` and instead use the `workspace.json`, even if the user configures the content of the workspace to be `angular`. This would mean 

* that at a top level all NX workspaces are truly uniform at a root level
* allow the docs to not contradict themselves
* create a JSON schema for the workspace.json which can be used across all of the supported project types

**Comment by Frikki** [comment]
Yes, this is definitely an issue that will also shy organizations away from adapting Nx as part of their tooling.

**Comment by pgerhard** [comment]
Any feedback on this from the NX Team?
