### ISSUE TITLE
Combine Multiple Storybook Outputs into one output

### ISSUE THREAD

**Issue by mehrad-rafigh** [nrwl/nx#4252]
## Description
We are using the storybook without the nrwl integration, but would like to use it.
We have multiple libs that have their own stories. When we build storybook, all stories are combined into one output which then can be served via HTTP Server.
Using the nrwl integration I have not found a way to combine multiple stories into one output.

## Motivation
We could deliver all outputs in one single server, but there are too many clicks involved to see all stories inside the workspace 

## Suggested Implementation
A new flag should indicate whether all stories should be combined into one output

If you like, I can give a PR a try

**Comment by juristr** [comment]
Hey. Would this work? https://youtu.be/c323HOuFKkA

I'm also soon going to look more closely into the Storybook v6 composition feature. So that might help as well.

**Comment by mehrad-rafigh** [comment]
Hi @juristr. Yes thats what I am looking for, without creating the shared lib ;)

**Comment by juristr** [comment]
Yeah, for now that's the best workaround. More to come soon.

Let's keep this issue open for reference

**Comment by mehrad-rafigh** [comment]
Unstale

**Comment by jogelin** [comment]
I am also interested in grouping multiple storybooks but I feel that having one big storybook is a bit overkill.

Actually, we have multiple levels/scope of shared ui and each app/team will use these shared ui storybooks depending on the context.

[Storybook Composition](https://storybook.js.org/docs/react/workflows/storybook-composition) is a good solution for my use case. It works locally but when it is built, I need to generate the `stories.json` file. Any idea how to include this generation in the storybook builder ?

**Comment by juristr** [comment]
@jogelin hey, storybook composition is on our feature list. Currently, we're focusing to burn down some more issues and then we'll look into adding support for that.

**Comment by juristr** [comment]
Closing this as it is on our feature list. We're going to look into Storybook composition in Nx v13 which is actively being worked on

**Comment by stefan-schweiger** [comment]
@juristr is there a GitHub issue for this that we can watch?

**Comment by juristr** [comment]
@stefan-schweiger not yet. I can post here the PR once it is up. 

I think you could already use Storybook composition now, manually configuring it for a Nx workspace. What we're going to look into when working on the feature will be mostly to improve the DX where we can

**Comment by danr-za** [comment]
@juristr how can we deal in a case where 2 storybooks have different tailwind presets (for example)?

**Comment by juristr** [comment]
@danr-za you mean when composing them together?

Obviously, the approach I described in the video (linked here https://github.com/nrwl/nx/issues/4252#issuecomment-743204262) only works if the configuration of all those storybook setups is exactly the same.

Otherwise, you need the Storybook Composition setup @mandarini is working on in #5561.

**Comment by danr-za** [comment]
@juristr thanks for the comment.
I am actually seeking for a solution for Chromatic deployment, and u unfortunately in this case composition does not solve that.
I cna open a separate ticket for the question though
