### ISSUE TITLE
Wrong output path in workspace.json

### ISSUE THREAD

**Issue by puku0x** [nrwl/nx#4254]
## Current Behavior
`"{options.outputPath}"` is in `outputs`.

![image](https://user-images.githubusercontent.com/2607019/101924400-f953dc80-3c13-11eb-8b1b-b1c873897c64.png)

## Expected Behavior
It has to be `dist/apps/web`, for example.

## Steps to Reproduce
`npx create-nx-workspace@latest workspace` and make a react project.

### Environment

```
% npx nx report

>  NX  Report complete - copy this into the issue template

  Node : 12.16.3
  OS   : darwin x64
  npm  : 6.14.9
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.0.0
  @nrwl/cypress : 11.0.0
  @nrwl/devkit : 11.0.0
  @nrwl/eslint-plugin-nx : 11.0.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.0
  @nrwl/linter : 11.0.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.0.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.0
  @nrwl/web : 11.0.0
  @nrwl/workspace : 11.0.0
  typescript : 4.0.5
```

**Comment by FrozenPandaz** [comment]
Actually, it's a new feature!  :wink: :tada:

`outputs` is a field that is used by the Nx cache to determine what artifacts to cache after running a target.

You can now interpolate data from the options for the task which allows you to only maintain 1 value of the data.

That interpolation becomes `dist/apps/web` for Nx to cache.
