### ISSUE TITLE
nx 11 ignores incorrect input params for lib creation

### ISSUE THREAD

**Issue by gkamperis** [nrwl/nx#4255]
* npx create-nx-workspace

* pick angular + scss + eslint

npx nx g @nrwl/angular:lib ui --style=scss --untiTestRunnera=jasmineasdasd
succeeds!

in fact there is a bigger issue

npx nx g @nrwl/angular:lib ui --style=scss --untiTestRunner=karma

creates a jest setup...

## Current Behavior
succeeds

## Expected Behavior
to fail with explanatory error as it does for 10.4.7

## Steps to Reproduce
npx nx g @nrwl/angular:lib ui --style=scss --untiTestRunnera=jasmineasdasd

### Environment
win 10
latest nx11.0.0

**Comment by FrozenPandaz** [comment]
Hi, I believe your issue is specifically about improper arguments? i.e. typos etc.?

**Comment by gkamperis** [comment]
hi @FrozenPandaz 

two issues I have seen:

* typos are ignored -> invalid values not reported
* input not respected -> ask for karma but get jest

Thanks

**Comment by FrozenPandaz** [comment]
Thank you for the clarification.

I believe fro the "ask for karma but get jest" you also have a typo:

> `--untiTestRunner=karma`

We will look into handling the errors.

**Comment by gkamperis** [comment]
Hi @FrozenPandaz 

nice catch! it took me some time to 👀  spot it even after you pointed it!

but now...

```
npx nx g @nrwl/angular:lib ui --style=scss --unitTestRunner=karma --linter=eslint -d
TypeError: projectConfig.architect.lint.options.tsConfig is not iterable
...stack-trace...
```

which is the same as

https://github.com/nrwl/nx/issues/4256

but for v 11... 


the diff is for v11 I get a stack-trace...

Thanks

**Comment by vsavkin** [comment]
Fixed here: https://github.com/nrwl/nx/pull/4395

Thank you!
