### ISSUE TITLE
nx 10.4.7: cannot create angular:lib with eslint and karma

### ISSUE THREAD

**Issue by gkamperis** [nrwl/nx#4256]
## Current Behavior

```
nx g @nrwl/angular:lib ui --unitTestRunner=karma -d

? Which stylesheet format would you like to use? SASS(.scss)  [ http://sass-lang.com   ]

projectConfig.architect.lint.options.tsConfig is not iterable

```

I suspect this is because of the default test runner in angular.json but it should work....

## Expected Behavior
to create a lib with the desired test runner

## Steps to Reproduce
npx create-nx-workspace@10.4.7

* pick angular + scss + eslint

then create a lib
nx g @nrwl/angular:lib ui --unitTestRunner=karma -d

### Environment
win 10
nx 10.4.7

**Comment by gkamperis** [comment]
actually I was wrong... removing the defaults from angular.json does not help.
nx 10.4.4 has the same issue

`nx g @nrwl/angular:lib ui --linter=eslint --unitTestRunner=karma -d`

but 

`nx g @nrwl/angular:lib ui --linter=eslint --unitTestRunner=jest -d`
 is ok

`nx g @nrwl/angular:lib ui --linter=tslint --unitTestRunner=karma -d`
 is ok

**Comment by FrozenPandaz** [comment]
Good catch, this should be supported.

Should be a low effort fix if someone would like to take a look.

The error is thrown from here which should noop if the linter is not `@angular-devkit/build-angular:tslint`:

https://github.com/nrwl/nx/blob/f57f2b43f432091f9e877c38d136b221185868a0/packages/angular/src/schematics/karma-project/karma-project.ts#L103
