### ISSUE TITLE
Nx migrate banner completely hides information on available updates

### ISSUE THREAD

**Issue by bopm** [nrwl/nx#4260]
## Current Behavior
Running ```ng update``` in nx workspace no longer provides table with outdated packages, but instead display a banner: ```Nx provides a much improved version of "ng update".```.

## Expected Behavior
For me, that one feels like regression, as I am no longer capable of using that for getting informed on outdated parts of my workspace.

## Steps to Reproduce
Just run ```ng update``` in workspace to get that obvious banner.

### Environment

  Node : 12.16.1
  OS   : darwin x64
  yarn : 1.22.4

  nx : Not Found
  @nrwl/angular : 11.0.0
  @nrwl/cli : 11.0.0
  @nrwl/cypress : 11.0.0
  @nrwl/devkit : 11.0.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.0
  @nrwl/linter : 11.0.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.0
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.0
  typescript : 4.0.5

**Comment by vsavkin** [comment]
Thank you for submitting the issue.

I added the following to the end of the message: `If you still want to use "ng update", run "FORCE_NG_UPDATE=true ng update".` So if you pass the env variable, it will run Angular CLI's ng update. 

We still discourage using `ng update` because in our experience it causes a lot of headaches, doesn't work with non-trivial workspaces, doesn't work well with pnpm etc.. But the env variable is there in case you want to use `ng update`.

I'm going to close this issue.

**Comment by bopm** [comment]
Thank you @vsavkin. I agree with the direction on migrations you are taking, it seems right after having a lot of issues with `ng update`, but at the same time workflow should not degrade under those changes. 

I have another quality of life issue, btw, if the developer ignoring text displayed by `nx migrate` and not running `migrations.json`, they get silently rewritten and you practically get your project unmigrated. I think both formatting with `===\n IMPORTANT \n===` and some kind of a check that the user has actually done something with that file needed to avoid a lot of broken repositories in process of switching to a new process.

**Comment by instantgis** [comment]
Angular Evergreen in Visual Studio tells me Angular is outdated. npx create-nx-workspace installed Angular 11.2.0 and 11.2.2 is current. I want to update it so I try ng update and I get...
Nx provides a much improved version of "ng update". It runs the same migrations, but allows you to:
- rerun the same migration multiple times
- reorder migrations, skip migrations
- fix migrations that "almost work"
- change versions of packages to match organizational requirements
And, in general, it is lot more reliable for non-trivial workspaces. Read more at: https://nx.dev/latest/angular/workspace/update
Run "nx migrate latest" to update to the latest version of Nx.
Running "ng update" can still be useful in some dev workflows, so we aren't planning to remove it.
If you need to use it, run "FORCE_NG_UPDATE=true ng update".
PS D:\Projects\nx\youdoit> nx migrate latest
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest
Fetching @nrwl/workspace@11.3.2

>  NX  The migrate command has run successfully.

- package.json has been updated
- there are no migrations to run, so migrations.json has not been created.

>  NX  Next steps:

- Make sure package.json changes make sense and then run 'npm install --legacy-peer-deps'
- To learn more go to https://nx.dev/latest/core-concepts/updating-nx
- 
ok fair enough so I gather there was nothing to update with the nx pieces and package.json did not change but what about Angular. I still want to update Angular.
I copy paste the indicated FORCE_NG_UPDATE=true ng update
and I get 
FORCE_NG_UPDATE=true : The term 'FORCE_NG_UPDATE=true' is not recognized as the name of a cmdlet
So now I am off on a tangent researching what am I doing wrong and what's this passing environment variable passing thing you mention above.
And I try 
npm FORCE_NG_UPDATE=true ng update
and of course that barks at me

Can you please be clear and explicit about how to override nx migrate and update Angular pieces?

Thanks

**Comment by bhanna1693** [comment]
Any update on this? I would really like to be able to use the command line to update Angular packages for their dot releases (i.e. 12.2.0 -> 12.2.7)
