### ISSUE TITLE
Angular 11 upgrade does not work on nx workspaces started on <=9

### ISSUE THREAD

**Issue by kylecannon** [nrwl/nx#4261]
I have been tracking down this issue for a while today and I think I have nailed it down to older workspaces that starts on v9 of nx and below. There is a thread happening in the @nrwl/community slack channel as well: https://nrwlcommunity.slack.com/archives/C016ASCS683/p1607709674218500

What basically ends up happening is the nx update command updates @nrwl/angular to v11, but fails to update any of the angular packages to v11.

Example of a freshly created nx 9 workspace unable to automatically upgrade Angular to v11.

https://gist.github.com/kylecannon/d20d6c83b1f6b532e99c5f9b7749337e

Example of a freshly created nx 10 workspace able to automatically upgrade Angular to v11.

https://gist.github.com/kylecannon/479f33370074a8f7030a9c1c166e68b5

**Comment by FrozenPandaz** [comment]
Hi, could you try to use `npx nx migrate @nrwl/workspace@latest` instead please?

I left commits with the commands that I ran: https://github.com/FrozenPandaz/nx-bugs/tree/9-11-migrate

**Comment by kylecannon** [comment]
Also, is there a way to have it update @ngrx/store and @angular/material?

**Comment by FrozenPandaz** [comment]
> ok, this looks much better and i got further. One repository worked great

Awesome! :tada: 

> /Volumes/Development/project/node_modules/.bin/tao migrate --run-migrations=migrations.json
> Running migration @nrwl/workspace:add-explicit-dep-on-tao
> Cannot find module '@angular-devkit/core/src/experimental/workspace'

Sorry, I would need more info to take a look. Was that repo also on version 9.x?

> Can you explain to me why this worked vs using yarn upgrade in my repositories?

`nx migrate` handles migrations better than `ng update` for non-trivial workspaces which most Nx workspaces are. In Nx 10.x, we made a change where `ng update` is not allowed but previous versions do not have that change so it is not obvious. We will look into how to handle this better.

**Comment by kylecannon** [comment]
> Sorry, I would need more info to take a look. Was that repo also on version 9.x?

No, we were on the latest version of Nx v10 before. However, we have been using nx since the v8 days. If you install a v9 workspace you will see that it will not be able to upgrade to v11 correctly even though it upgrades from 9->10->11

https://gist.github.com/kylecannon/d20d6c83b1f6b532e99c5f9b7749337e has the context.

Please let me know if I can help any further. Thank you for the awesome software!

**Comment by pf1gura** [comment]
Adding `"@angular-devkit/core": "10.2.0"` to `resolutions` in `package.json` fixes this issue (tested with `yarn`, not sure if `npm` supports `resolutions`).

Version `11.X` of `@angular-devkit/core` does not have experimental workspace folder here: https://github.com/angular/angular-cli/tree/master/packages/angular_devkit/core/src/experimental

**Comment by pf1gura** [comment]
Once above issue is gone I was having same issues as #4270 and I had to remove all `@angular/core` migrations. I think they look for `tsconfig.json` file but nx has `tsconfig.base.json`

**Comment by vsavkin** [comment]
Migrating from 9.8 to 11x worked for me. 

Could you try the following as it's more reliable way of migrating.

```
npx @nrwl/tao@latest migrate 10.4.8 (do the whole migration process to 10x)
npx @nrwl/tao@latest migrate latest (do the whole migration process to 11x)
```

We inherently don't know the order in which migrations should run across packages. Let's say you migrate packages A and B. All the versions are independent. There is no way for us to know that 8.12 version of Package A goes before 7.5 version of Package B. We however do a lot of testing in bumping up 1 major at a time.

Could you try the commands above?

**Comment by humblepie** [comment]
> Adding `"@angular-devkit/core": "10.2.0"` to `resolutions` in `package.json` fixes this issue (tested with `yarn`, not sure if `npm` supports `resolutions`).
> 
> Version `11.X` of `@angular-devkit/core` does not have experimental workspace folder here: https://github.com/angular/angular-cli/tree/master/packages/angular_devkit/core/src/experimental

I was getting the following error attempting to upgrade a 10.x repo to 11.x:
nx migrate --run-migrations=migrations.json
yarn run v1.22.10
$ /node_modules/.bin/tao migrate --run-migrations=migrations.json
Running migration @nrwl/workspace:update-script-to-invoke-nx-migrate
**Cannot find module '@angular-devkit/core/src/experimental/workspace'**

@pf1gura Thanks.  The migration ran to completion once I added the **"@angular-devkit/core": "10.2.0"** resolution.

**Comment by mpstv** [comment]
> 
> 
> ok, this looks much better and i got further. One repository worked great, one did have an error:
> 
> ```
> npx nx migrate --run-migrations=migrations.json
> yarn run v1.22.5
> $ /Volumes/Development/project/node_modules/.bin/tao migrate --run-migrations=migrations.json
> Running migration @nrwl/workspace:add-explicit-dep-on-tao
> Cannot find module '@angular-devkit/core/src/experimental/workspace'
> ```
> 
> i then did `yarn list @angular-devkit/core`
> 
> ```
> ├─ @angular-devkit/core@11.0.4
> ├─ @nrwl/cli@10.3.1
> │  └─ @angular-devkit/core@10.1.7
> ✨  Done in 0.79s.
> ```
> 
> turned out that @nrwl/cli was still on 10.3.1. Ran: `yarn upgrade @nrwl/cli --latest` after that and then was able to run it.
> 
> Can you explain to me why this worked vs using `yarn upgrade` in my repositories?

When migrate `@nrwl/angular": "10.3.1"` -> `@nrwl/angular": "11.0.16"` using `nx migrate latest`, i have same error with same `yarn list @angular-devkit/core` output, and `yarn upgrade @nrwl/cli --latest` works well for me.

Thank you @kylecannon !

**Comment by Lonli-Lokli** [comment]
npx nx migrate @nrwl/workspace@latest do not update to the latest Angular 11 version if you are already on Angular 11

**Comment by onedotover** [comment]
The fix for me was to add @nrwl/angular to my setup. It was somehow not included as part of my upgrade.
```
npm install --save @nrwl/angular
```
