### ISSUE TITLE
Nx migrate does not work with Angular Material/CDK

### ISSUE THREAD

**Issue by bopm** [nrwl/nx#4262]
## Current Behavior
Running ```nx migrate @angular/material``` or ```nx migrate @angular/cdk``` in the nx workspace fails with ```Cannot read property 'split' of undefined``` error.

## Expected Behavior
I expect that to work especially if nx at the same time completely blocking my ability to use ```ng update```.

## Steps to Reproduce
Run ```nx migrate @angular/material``` in the project.

### Failure Logs
```
nx migrate @angular/material
yarn run v1.22.4
$ /Users/<...>/angular-monorepo/node_modules/.bin/tao migrate @angular/material
Fetching meta data about packages.
It may take a few minutes.
Fetching @angular/material@latest
Fetching @angular/material@11.0.2

 ERROR  The migrate command failed. Try the following to migrate your workspace:

> npx @nrwl/tao@latest migrate @angular/material@latest
This will use the newest version of the migrate functionality, which might have your issue resolved.
----------------------------------------------------------------------------------------------------
Cannot read property 'split' of undefined
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
/Users/<...>/angular-monorepo/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: yarn tao migrate @angular/material
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.handler (/Users/<...>/angular-monorepo/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:74:21)
    at Object.runCommand (/Users/<...>/angular-monorepo/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/<...>/angular-monorepo/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/Users/<...>/angular-monorepo/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/Users/<...>/angular-monorepo/node_modules/@nrwl/cli/lib/init-local.js:23:13)
    at Object.<anonymous> (/Users/<...>/angular-monorepo/node_modules/@nrwl/cli/bin/nx.js:41:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 48247,
  stdout: null,
  stderr: null
}
```

### Environment
  Node : 12.16.1
  OS   : darwin x64
  yarn : 1.22.4

  nx : Not Found
  @nrwl/angular : 11.0.0
  @nrwl/cli : 11.0.0
  @nrwl/cypress : 11.0.0
  @nrwl/devkit : 11.0.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.0
  @nrwl/linter : 11.0.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.0
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.0
  typescript : 4.0.5

**Comment by kylecannon** [comment]
running into this issue as well.

**Comment by KingDarBoja** [comment]
I got a different error message:

```console
$ ng update @angular/material

>  NX   WARNING  The Angular CLI was invoked instead of the Nx CLI. Use "npx ng [command]" or "nx [command]" instead.

Using package manager: 'yarn'
Collecting installed dependencies...
Found 92 dependencies.
Fetching dependency metadata from registry...
× Migration failed: Cannot read property 'synchronous' of undefined
```
So I removed the `node_modules`, reinstalled again using `yarn` and it worked without issues (besides a small `--force` due to some dependencies).

**Comment by kylecannon** [comment]
Just an FYI @FrozenPandaz, for when I run the migration on the latest change I get the following for every single library:

```
Could not find TypeScript project for project: data-model
......
      ✓  Updated Angular Material to version 11
    
Successfully finished migration-v11

```

I don't know if thats expected?

**Comment by luchsamapparat** [comment]
@kylecannon same problem here

CDK's migration uses the `readJsonWorkspace` function from `@angular-devkit/core` to parse the `angular.json` of your project. It maps the `architects` of the projects (apps and libs) in your `angular.json` to `targets` in some kind of meta-model.

```ts
  for (const { key, value } of projectNode.properties) {
    const name = key.value;
    switch (name) {
      case 'targets':
      case 'architect':
        if (value.kind !== 'object') {
          context.error(`Invalid "${name}" field found; expected an object.`, value);
          break;
        }
        targetsNode = value;
        targets = parseTargetsObject(projectName, value, context);
```
https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/core/src/workspace/json/reader.ts#L186

The CDK migration then passes this model to its own `getTargetTsconfigPath` function, which reads the tsconfig path from either the `"build"` or the `"test"` target.

```ts
    for (const projectName of projectNames) {
      const project = workspace.projects.get(projectName)!;
      const buildTsconfigPath = getTargetTsconfigPath(project, 'build');
      const testTsconfigPath = getTargetTsconfigPath(project, 'test');

      if (!buildTsconfigPath && !testTsconfigPath) {
        logger.warn(`Could not find TypeScript project for project: ${projectName}`);
        continue;
      }
```
https://github.com/angular/components/blob/master/src/cdk/schematics/ng-update/devkit-migration-rule.ts#L83

```
export function getTargetTsconfigPath(project: ProjectDefinition,
                                      targetName: string): WorkspacePath|null {
  const tsconfig = project.targets?.get(targetName)?.options?.tsConfig;
  return tsconfig ? normalize(tsconfig as string) : null;
}
```
https://github.com/angular/components/blob/master/src/cdk/schematics/utils/project-tsconfig-paths.ts#L23

However, in Nx a (non-publishable) library does not have a `build` architect and the Jest `test` architect does not have a `options.tsConfig` property.

I'm not sure whose "fault" this is... CDK probably has the standpoint that it's not a problem in "regular" Angular projects and Nx should not add useless configuration to satisfy some library's migration. 🤔

A hackish fix for this problem would be to provide either a `build` architect with `tsconfig` option or add a `tsconfig` option to your existing `test` architect. (probably, haven't tested it yet)

**Comment by kylecordes** [comment]
It looks like the fix for this issue fixed it by not trying to execute migrations that would fail in this way.

I'm skeptical whether this really fixes things though; presumably these (in this example) CDK migrations exist for a reason, and should be executed to update application code in their intended way, not skipped?

**Comment by hakimio** [comment]
@FrozenPandaz I am still getting `Cannot read property 'split' of undefined` when running `npx @nrwl/tao@latest migrate @angular/material`.
