### ISSUE TITLE
Sourcemaps can't be disabled via flag in NX 11

### ISSUE THREAD

**Issue by sorin-davidoi** [nrwl/nx#4279]
## Current Behavior

Can't disable sourcemaps with the `--sourceMap` flag.

## Expected Behavior

It's a regression, passing `--sourceMap=false` used to work with NX 10.

## Steps to Reproduce

```bash
git clone https://github.com/nrwl/nx-examples.git
cd nx-examples
git checkout 2726397577c12a28e0ed598f28d9763d7320fc48 # https://github.com/nrwl/nx-examples/commit/2726397577c12a28e0ed598f28d9763d7320fc48

npm install
npm run build -- --sourceMap=false
```

### Failure Logs
```
Property 'sourceMap' does not match the schema.
{
  "description": "Output source maps.",
  "default": true,
  "oneOf": [
    {
      "type": "object",
      "properties": {
        "scripts": {
          "type": "boolean",
          "description": "Output source maps for all scripts.",
          "default": true
        },
        "styles": {
          "type": "boolean",
          "description": "Output source maps for all styles.",
          "default": true
        },
        "hidden": {
          "type": "boolean",
          "description": "Output source maps used for error reporting tools.",
          "default": false
        },
        "vendor": {
          "type": "boolean",
          "description": "Resolve vendor packages source maps.",
          "default": false
        }
      },
      "additionalProperties": false
    },
    {
      "type": "boolean"
    }
  ]
}'
```

## Investigation

Adding `sourceMap` to the following array fixes the issue: https://github.com/nrwl/nx/blob/8e53485d2eb41114032a8ec9bb96fad81e224b24/packages/tao/src/commands/run.ts#L39

### Environment

```
Node : 14.15.0
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 11.0.0-rc.0
  @nrwl/cli : 11.0.0-rc.0
  @nrwl/cypress : 11.0.0-rc.0
  @nrwl/devkit : 11.0.0-rc.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.0-rc.0
  @nrwl/linter : 11.0.0-rc.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.0.0-rc.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.0-rc.0
  @nrwl/web : 11.0.0-rc.0
  @nrwl/workspace : 11.0.0-rc.0
  typescript : 4.0.3
```

**Comment by brianmcd** [comment]
I ran into this pre-v11, too.

I'm not sure exactly when `--sourceMap=false` stopped working for us (I'd guess some time in v10), but passing `--no-source-map` works as a workaround, at least for building our React app.

**Comment by jredl-va** [comment]
Note, that I also encountered this. Other commands area also affected by this. For example `--optimization=false` generates a similar error:

```
Property 'optimization' does not match the schema.
{
  "description": "Enables optimization of the build output. Including minification of scripts and styles, tree-shaking, dead-code elimination, tree-shaking and fonts inlining. For more information, see https://angular.io/guide/workspace-config#optimization-and-source-map-configuration.",
  "x-user-analytics": 16,
  "oneOf": [
    {
      "type": "object",
      "properties": {
        "scripts": {
          "type": "boolean",
          "description": "Enables optimization of the scripts output.",
          "default": true
        },
        "styles": {
          "type": "boolean",
          "description": "Enables optimization of the styles output.",
          "default": true
        }
      },
      "additionalProperties": false
    },
    {
      "type": "boolean"
    }
  ],
  "x-deprecated": "Use the \"optimization\" option in the browser builder instead."
}'
```

**Comment by vsavkin** [comment]
Thank you for reporting this! Fixed it in 11.0.4.

**Comment by joaoantunes87** [comment]
Hi Nx team,

First of all, thanks a lot for the great work you have been doing with `nx`! 

I know this was already closed, but I am trying the same in version `13.2.2` with a nextjs project. We do not want to have `source maps` generated in `production`.

I have tried using the following command:
```sh
yarn nx build public-app sourceMap=false
```

However, the `source maps` are being generated, without any error.

I have also tried the following configuration following the documentation [here](https://nx.dev/executors/using-builders#executor-definitions):

```
    "build": {
      "executor": "@nrwl/next:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "root": "apps/public-app",
        "outputPath": "dist/apps/public-app"
      },
      "configurations": {
        "production": {
          "sourceMap": false
        }
      }
    },
```

And the `source maps` keep being generated.

I have even tried to change `productionBrowserSourceMaps ` to `false`  in `next.config.js` file, after reading nextJs documentation [here](https://nextjs.org/docs/advanced-features/source-maps).

We are using version 11 of nextJs. Is anyone aware of someone having this issue, maybe I should do the configurations in a different place, but I am not seeing how? 

I have also tried to update webpack configurations in `next.config.js`, changing `devtool` webpack property.

Thanks!

**Comment by tobertigor** [comment]
just remove sourceMaps from tsconfig.base.json on root folder.
That's help me)

**Comment by joaoantunes87** [comment]
Thanks @tobertigor ,

I will give it a try!

**Comment by joaoantunes87** [comment]
Unfortunately removing sourceMaps from tsconfig.base.json on root folder is not working for us.
