### ISSUE TITLE
Is there a way I can publish npm libs from nx workspace / libs

### ISSUE THREAD

**Issue by a5hik** [nrwl/nx#428]
I created a nx workspace and I added a lib and a demo app that uses the lib, now I need to publish the lib.. Is there a way I can accomplish with nx?

**Comment by noelmace** [comment]
Duplicate of #225. Please close.

**Comment by a5hik** [comment]
closing this considering #225

**Comment by vsavkin** [comment]
Closing this issue. It's duplicate of #225.
