### ISSUE TITLE
constantName is not defined

### ISSUE THREAD

**Issue by ak274** [nrwl/nx#4282]
## Current Behavior

```
Executing Task: ng generate @nrwl/angular:ngrx --name=auth --module=projects/auth/src/lib/auth.module.ts
Is this the root state of the application? No
? Would you like to use a Facade with your NgRx state? Yes
```
This ngrx schematic is broken. And when executing its throwing error --

`constantName is not defined
`

## Expected Behavior

it should successfully execute and generate the feature state for a angular module. 

It seems like regression bug because it seems to be working earlier. 

### Failure Logs

![image](https://user-images.githubusercontent.com/16129430/102090698-c98b1b80-3e43-11eb-92d3-408c1c31ec72.png)

### Environment

"@nrwl/angular": "^10.3.0",
"@nrwl/workspace": "10.3.0",
"@angular/common": "^10.1.0",
    "@angular/compiler": "^10.1.0",
    "@angular/core": "^10.1.0",

**Comment by vsavkin** [comment]
@brandonroberts I believe this has been fixed in 11. Could you port the fix to the Nx 10.4.x branch?

**Comment by brandonroberts** [comment]
Will do

**Comment by brandonroberts** [comment]
@ak274 I was unable to reproduce this with an Nx 10 workspace. Will you reopen this with a reproduction or we can consider it fixed In Nx 11
