### ISSUE TITLE
scss style extension not used when creating new Angular component

### ISSUE THREAD

**Issue by nzacca** [nrwl/nx#4287]
## Current Behavior
When attempting to create a new Angular component, the stylesheet extension remains as `css` instead of `scss` when `scss` is chosen as the default style.

## Expected Behavior
Expect component to have `scss` extension.

Appears that this was fixed in https://github.com/nrwl/nx/issues/2890 so this might be a regression but I have never used Nx prior to v11 to know for sure.

## Steps to Reproduce

1. npx create-nx-workspace
2. Select Angular and scss in the prompts
3. Run `npx ng g m foo` to create a module.
4. Run `npx ng g c foo` to create the component.
5. Note that the file extension created is `css` and not `scss`

### Failure Logs
N/A

### Environment

```bash
npx nx report

>  NX  Report complete - copy this into the issue template

  Node : 12.19.0
  OS   : linux x64
  npm  : 6.14.8

  nx : Not Found
  @nrwl/angular : 11.0.2
  @nrwl/cli : 11.0.2
  @nrwl/cypress : 11.0.2
  @nrwl/devkit : 11.0.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.2
  @nrwl/linter : 11.0.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.2
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.2
  typescript : 4.0.5
```

### Other Notes

I did try a new angular cli 11 app just to see if that was the cause but the file extension was generated successfully there so this appears to be something happening with Nx.

Also note this is happening with a new workspace as noted in the reproduction steps above.

I have also tried setting `"style": "scss"` in `angular.json` but that did not appear to work either:

```json
    "@nrwl/angular": {
      "application": {
        "linter": "eslint"
      },
      "library": {
        "linter": "eslint"
      },
      "storybook-configuration": {
        "linter": "eslint"
      },
      "component": {
        "style": "scss"
      }
    },
```

I have also tried setting the `defaultCollection` to `@schematics/angular` but that also did not work.

**Comment by kylecannon** [comment]
I have the same issue too.

**Comment by mehrad-rafigh** [comment]
@nzacca @kylecannon I took a closer look. It seems that the `preset` and `new` schematics in `@nrwl/workspace` are working fine. They generate the scss files appropriately, but inside `angular.json` there is no field indicating what style extension to use. This defaults to css. I am looking into it right now and will try to create a PR
