### ISSUE TITLE
How to set exception rules for "file doesn't belong to any project" linting errors

### ISSUE THREAD

**Issue by dereklin** [nrwl/nx#429]
We just upgraded from 0.9.0 to 0.11.1.

We have some static css and js files sitting in libs.  When running npm run lint, we are getting these errors:

```
All files in 'apps' and 'libs' must be part of a project.:
The 'libs/xxx.css' file doesn't belong to any project.
```

Is there a way to ignore checking certain files?

**Comment by noelmace** [comment]
This is on purpouse. Nrwl/Nx is strongly opinionated, that's the point.
In my opinion, keeping some css or js files directly in libs/ seems to be a really bad practice. Why do you need this ?

**Comment by dereklin** [comment]
Is it really?  We are using semantic ui, for multiple apps.  Rather than creating the same css and js files for each app, we are putting those files in libs.  Libs is a natural choice for shared code.

If nx makes this a hard rule, then maybe I need to manually create an assets folder or such outside of apps and libs...

**Comment by noelmace** [comment]
I think this should be covered by a specific "core" (or "shared") library. From my perspective, `libs/` isn't about sharing code directly. It's about splitting this code into Angular libraries "the right way".  This permit, with tags, and the associated tslint and tsconfig rules, a better separation of concerns.
@vsavkin, do you confirm ?

**Comment by noelmace** [comment]
FYI : 
* PR introducing this behaviour : https://github.com/nrwl/nx/pull/379
* and the related method : https://github.com/nrwl/nx/blob/ce553b732e8ca004e1ecf53cf54bcadb6ba1f7f3/packages/schematics/src/command-line/workspace-integrity-checks.ts#L51-L71

**Comment by dereklin** [comment]
@noelmace thanks for pointing out the changes.

It turned out I just needed to add an entry into the .angular-cli.json.

I'll close this issue now.

**Comment by willyboy** [comment]
If I have a directory to group libs but the directory isn't itself a lib, I get this error by having a readme in the directory.
Like:
```
libs 
    -  shared (a directory for grouping)
         - layout (a generated lib)
         - tracking (a generated lib)
         README.md
```

**Comment by patrick-entinux** [comment]
> If I have a directory to group libs but the directory isn't itself a lib, I get this error by having a readme in the directory.
> Like:
> 
> ```
> libs 
>     -  shared (a directory for grouping)
>          - layout (a generated lib)
>          - tracking (a generated lib)
>          README.md
> ```

@willyboy Yeah, me too. I put a README.md file in my libs/angular to introduce the different libraries inside this folder. I guess I'll delete it for now.

**Comment by jonathonadams** [comment]
@willyboy  @patrick-entinux  I ran into this issue today as well but I solved it by adding a `.nxignore` file and adding the files there.

The [docs](https://nx.dev/angular/cli/workspace-lint) say:

> To exclude files from this lint rule, you can add them to the ".nxignore" file."

Hope this solves your issues.
