### ISSUE TITLE
RN Plugin build fails with no error with NX 11.0.2

### ISSUE THREAD

**Issue by goofiw** [nrwl/nx#4290]
I did not, but there seem to be a few issues across the board with NX 11, I though it might be helpful to bring visibility to this as well.  Please delete if inappropriate.

## Current Behavior

Details in this issue:
https://github.com/nrwl/nx-react-native/issues/28

## Expected Behavior
RN plugin project generation and builder running is included in nx core tests

**Comment by goofiw** [comment]
Note: I just tried the repro steps in the referenced issue, with the 11.0.3 release and saw the same result

**Comment by jaysoo** [comment]
I've published `@nrwl/react-native@11.0.0` to resolve this issue.
