### ISSUE TITLE
Running tests in GH action is provding an error

### ISSUE THREAD

**Issue by Jefiozie** [nrwl/nx#4293]
## Current Behavior

We recently upgraded to version 11 of NX with the `xLayers` project, the migration flow was smooth but for some reason, we see an error in the Github actions. Locally  it looks okay, but we can't figure out the root cause of this issue.
The complete logging can be found [here](https://github.com/xlayers/xlayers/runs/1555280937?check_suite_focus=true)

```
> nx run xaml-codegen:test 
Cannot find module './defaultConfig'
Require stack:
- D:\a\xlayers\xlayers\node_modules\jest-validate\build\validate.js
- D:\a\xlayers\xlayers\node_modules\jest-validate\build\index.js
- D:\a\xlayers\xlayers\node_modules\jest-config\build\ValidConfig.js
- D:\a\xlayers\xlayers\node_modules\jest-config\build\normalize.js
- D:\a\xlayers\xlayers\node_modules\jest-config\build\index.js
- D:\a\xlayers\xlayers\node_modules\@jest\core\build\cli\index.js
- D:\a\xlayers\xlayers\node_modules\@jest\core\build\jest.js
- D:\a\xlayers\xlayers\node_modules\jest\build\jest.js
- D:\a\xlayers\xlayers\node_modules\@nrwl\jest\src\builders\jest\jest.impl.js
- D:\a\xlayers\xlayers\node_modules\@nrwl\tao\src\shared\workspace.js
- D:\a\xlayers\xlayers\node_modules\@nrwl\tao\src\commands\run.js
- D:\a\xlayers\xlayers\node_modules\@nrwl\tao\index.js
- D:\a\xlayers\xlayers\node_modules\@nrwl\cli\lib\run-cli.js
```
## Expected Behavior

I'm not sure, I would say that there is something missing in our repo.

## Steps to Reproduce

An example repo can be found [here](https://github.com/xlayers/xlayers)

### Environment

The link to the result [nx cloud](https://nx.app/runs/JX3u2sizC9q)

**Comment by Jefiozie** [comment]
Hi @vsavkin, if you need more information or you would like me to test some things just reach out. Im more then happy to help, I just don't know where to start at this point.

**Comment by Jefiozie** [comment]
Just for your information, we just updated to the latest version (`11.0.8`) and we still see this issue.

**Comment by FrozenPandaz** [comment]
Hm so I forked the `xlayers` repo and used a copy of your branch to create a PR on my fork.. and the checks passed... :thinking: 

Is it possible it's a flaky run?

My e2e checks did fail but the checks did run so maybe those are legitimate or also flaky?

**Comment by Jefiozie** [comment]
It looks indeed like a flaky test, see [here](https://github.com/xlayers/xlayers/actions/runs/434250505) closing this as It isn't a NX issue. Thank you for your assistants.
