### ISSUE TITLE
Using decorated @nrwl/nx-cloud prompts again to "Use Nx Cloud?"

### ISSUE THREAD

**Issue by minijus** [nrwl/nx#4295]
## Current Behavior
Using decorated @nrwl/nx-cloud prompts again to "Use Nx Cloud?".

task-runner.ts:
```ts:task-runner.ts
/**
 * Using Nx Private Cloud with self-signed certificate
 * Setting axios defaults to include CA for self-signed certificate
 */
axios.defaults.httpsAgent = new Agent({ ca: caBundle });

export default nxCloudTasksRunner;
```

nx.json:
```ts:nx.json
"tasksRunnerOptions": {
  "default": {
    "runner": "./tools/nx-cloud",
    "options": {
      "accessToken": "accessToken=",
      "cacheableOperations": ["build", "test", "lint", "e2e"],
      "canTrackAnalytics": false,
      "showUsageWarnings": true,
      "url": "https://nxcloud.myorg.net"
    }
  }
}
```

Running any runnable command (i.e. `nx run project:test --scan`) prompts to use Nx Cloud:
![image](https://user-images.githubusercontent.com/3633549/102181952-1a3a5d00-3eb4-11eb-9cd6-8ca35debd97f.png)

## Expected Behavior
It would be great to have possibility to decorate @nrwl/nx-cloud.
Would it be possible to use env variable similarly as NX_CLI_SET is being used?

I had [a suggestion on Slack](https://nrwlcommunity.slack.com/archives/C010ZHLMXNF/p1607956344042700) to add `ca` property to @nrwl/nx-cloud task runner options. It would close the case for self-signed certs.

However, having possibility to decorate the runner itself is more generic solution.

## Steps to Reproduce
See 'Current Behavior' section.

**Comment by vsavkin** [comment]
That's an interesting use case. We haven't considered folks wrapping the runner. Two workarounds:

- You can set scan: true in nx.json, which won't trigger the prompt.
- You can rename scan into `some-other-scan`, and map to the original scan when invoking the wrapped nx-cloud runner.

**Comment by minijus** [comment]
Simple and brilliant solution. Just by looking at prompt code, it seems it should work. Will give it a try and update with the result.

Btw, is there any documentation for `@nrwl/nx-cloud` task runner options? It is a bit inconvenient to reverse what option does exactly what from obfuscated code of `nxCloudTasksRunner`? :)
