### ISSUE TITLE
create nx angular app fails with tslint error

### ISSUE THREAD

**Issue by manoharnikkam** [nrwl/nx#4304]
## Current Behavior
Create workspace successfully
![image](https://user-images.githubusercontent.com/8573069/102268000-4ec40e00-3ee0-11eb-923b-ac0f3665ea49.png)
![image](https://user-images.githubusercontent.com/8573069/102268059-669b9200-3ee0-11eb-8780-d921e143f656.png)

## Expected Behavior
Create a angular app in the workspace

## Steps to Reproduce

- Create a empty workspace
`npx create-nx-workspace nx-angular-workspace --preset=empty --no-nx-cloud`
`cd nx-angular-workspace`

- Create Angular app with routing
`npm install --save-dev @nrwl/angular`
`nx generate @nrwl/angular:application myapp --style=scss`

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs
![image](https://user-images.githubusercontent.com/8573069/102268840-6d76d480-3ee1-11eb-9ba0-d18c0696d8bd.png)
0 verbose cli [
0 verbose cli   '/usr/local/Cellar/node/15.4.0/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   '--quiet'
0 verbose cli ]
1 info using npm@7.0.15
2 info using node@v15.4.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/manohar/Projects/Learning/nx-angular-workspace/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/manohar/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 5ms
19 verbose npm-session 9ab42869b48b8826
20 timing npm:load Completed in 10ms
21 timing arborist:ctor Completed in 1ms
22 timing idealTree:init Completed in 383ms
23 timing idealTree:userRequests Completed in 2ms
24 silly idealTree buildDeps
25 silly fetch manifest @angular/animations@^11.0.0
26 timing arborist:ctor Completed in 0ms
27 http fetch GET 304 https://registry.npmjs.org/@angular%2fanimations 723ms (from cache)
28 silly fetch manifest @angular/core@^11.0.0
29 http fetch GET 304 https://registry.npmjs.org/@angular%2fcore 171ms (from cache)
30 silly fetch manifest rxjs@~6.5.5
31 http fetch GET 304 https://registry.npmjs.org/rxjs 173ms (from cache)
32 silly fetch manifest zone.js@^0.10.2
33 http fetch GET 304 https://registry.npmjs.org/zone.js 181ms (from cache)
34 silly fetch manifest @angular/common@^11.0.0
35 http fetch GET 304 https://registry.npmjs.org/@angular%2fcommon 181ms (from cache)
36 silly fetch manifest @angular/compiler@^11.0.0
37 http fetch GET 304 https://registry.npmjs.org/@angular%2fcompiler 53ms (from cache)
38 silly fetch manifest @angular/forms@^11.0.0
39 http fetch GET 304 https://registry.npmjs.org/@angular%2fforms 61ms (from cache)
40 silly fetch manifest @angular/platform-browser@^11.0.0
41 http fetch GET 304 https://registry.npmjs.org/@angular%2fplatform-browser 68ms (from cache)
42 silly fetch manifest @angular/platform-browser-dynamic@^11.0.0
43 http fetch GET 304 https://registry.npmjs.org/@angular%2fplatform-browser-dynamic 64ms (from cache)
44 silly fetch manifest @angular/router@^11.0.0
45 http fetch GET 304 https://registry.npmjs.org/@angular%2frouter 56ms (from cache)
46 silly fetch manifest @angular-devkit/build-angular@~0.1100.1
47 http fetch GET 304 https://registry.npmjs.org/@angular-devkit%2fbuild-angular 82ms (from cache)
48 silly fetch manifest @angular/compiler-cli@^11.0.0
49 http fetch GET 304 https://registry.npmjs.org/@angular%2fcompiler-cli 118ms (from cache)
50 silly fetch manifest typescript@~4.0.3
51 http fetch GET 304 https://registry.npmjs.org/typescript 86ms (from cache)
52 silly fetch manifest @angular/language-service@^11.0.0
53 http fetch GET 200 https://registry.npmjs.org/@angular%2flanguage-service 3ms (from cache)
54 silly fetch manifest @types/jest@26.0.8
55 http fetch GET 304 https://registry.npmjs.org/@types%2fjest 69ms (from cache)
56 silly fetch manifest codelyzer@^6.0.0
57 http fetch GET 304 https://registry.npmjs.org/codelyzer 53ms (from cache)
58 silly fetch manifest tslint@~6.0.0
59 http fetch GET 304 https://registry.npmjs.org/tslint 51ms (from cache)
60 silly fetch manifest jest@26.2.2
61 http fetch GET 304 https://registry.npmjs.org/jest 54ms (from cache)
62 silly fetch manifest jest-preset-angular@8.3.1
63 http fetch GET 304 https://registry.npmjs.org/jest-preset-angular 45ms (from cache)
64 silly fetch manifest ts-jest@26.4.0
65 http fetch GET 304 https://registry.npmjs.org/ts-jest 43ms (from cache)
66 silly placeDep ROOT @angular-devkit/build-angular@0.1100.4 OK for: nx-angular-workspace@0.0.0 want: ~0.1100.1
67 silly placeDep ROOT @angular/compiler-cli@11.0.4 OK for: @angular-devkit/build-angular@0.1100.4 want: ^11.0.0
68 silly placeDep ROOT @angular/compiler@11.0.4 OK for: @angular/compiler-cli@11.0.4 want: 11.0.4
69 silly placeDep ROOT @angular/animations@11.0.4 OK for: nx-angular-workspace@0.0.0 want: ^11.0.0
70 silly placeDep ROOT @angular/core@11.0.4 OK for: @angular/animations@11.0.4 want: 11.0.4
71 silly placeDep ROOT zone.js@0.10.3 OK for: @angular/core@11.0.4 want: ~0.10.3
72 silly placeDep ROOT @angular/common@11.0.4 OK for: nx-angular-workspace@0.0.0 want: ^11.0.0
73 silly placeDep ROOT @angular/forms@11.0.4 OK for: nx-angular-workspace@0.0.0 want: ^11.0.0
74 silly placeDep ROOT @angular/platform-browser@11.0.4 OK for: @angular/forms@11.0.4 want: 11.0.4
75 silly placeDep ROOT @angular/language-service@11.0.4 OK for: nx-angular-workspace@0.0.0 want: ^11.0.0
76 silly placeDep ROOT @angular/platform-browser-dynamic@11.0.4 OK for: nx-angular-workspace@0.0.0 want: ^11.0.0
77 silly placeDep ROOT @angular/router@11.0.4 OK for: nx-angular-workspace@0.0.0 want: ^11.0.0
78 silly placeDep ROOT @types/jest@26.0.8 OK for: nx-angular-workspace@0.0.0 want: 26.0.8
79 silly placeDep ROOT codelyzer@6.0.1 OK for: nx-angular-workspace@0.0.0 want: ^6.0.0
80 silly placeDep ROOT jest@26.2.2 OK for: nx-angular-workspace@0.0.0 want: 26.2.2
81 silly placeDep ROOT jest-preset-angular@8.3.1 OK for: nx-angular-workspace@0.0.0 want: 8.3.1
82 silly placeDep ROOT rxjs@6.5.5 REPLACE for: nx-angular-workspace@0.0.0 want: ~6.5.5
83 silly placeDep ROOT ts-jest@26.4.0 OK for: nx-angular-workspace@0.0.0 want: 26.4.0
84 silly fetch manifest @angular-devkit/build-optimizer@0.1100.4
85 silly fetch manifest @angular-devkit/build-webpack@0.1100.4
86 silly fetch manifest @babel/core@7.12.3
87 silly fetch manifest @babel/generator@7.12.1
88 silly fetch manifest @babel/plugin-transform-runtime@7.12.1
89 silly fetch manifest @babel/preset-env@7.12.1
90 silly fetch manifest @babel/runtime@7.12.1
91 silly fetch manifest @babel/template@7.10.4
92 silly fetch manifest @jsdevtools/coverage-istanbul-loader@3.0.5
93 silly fetch manifest @ngtools/webpack@11.0.4
94 silly fetch manifest autoprefixer@9.8.6
95 silly fetch manifest babel-loader@8.1.0
96 silly fetch manifest cacache@15.0.5
97 silly fetch manifest circular-dependency-plugin@5.2.0
98 silly fetch manifest copy-webpack-plugin@6.2.1
99 silly fetch manifest core-js@3.6.5
100 silly fetch manifest css-loader@4.3.0
101 silly fetch manifest cssnano@4.1.10
102 silly fetch manifest file-loader@6.1.1
103 silly fetch manifest inquirer@7.3.3
104 silly fetch manifest jest-worker@26.5.0
105 silly fetch manifest karma-source-map-support@1.4.0
106 silly fetch manifest less@3.12.2
107 silly fetch manifest less-loader@7.0.2
108 silly fetch manifest license-webpack-plugin@2.3.1
109 silly fetch manifest loader-utils@2.0.0
110 silly fetch manifest mini-css-extract-plugin@1.2.1
111 silly fetch manifest open@7.3.0
112 silly fetch manifest parse5-html-rewriting-stream@6.0.1
113 silly fetch manifest pnp-webpack-plugin@1.6.4
114 silly fetch manifest postcss@7.0.32
115 silly fetch manifest postcss-import@12.0.1
116 silly fetch manifest postcss-loader@4.0.4
117 silly fetch manifest raw-loader@4.0.2
118 silly fetch manifest resolve-url-loader@3.1.2
119 silly fetch manifest rimraf@3.0.2
120 silly fetch manifest rollup@2.32.1
121 silly fetch manifest rxjs@6.6.3
122 silly fetch manifest sass@1.27.0
123 silly fetch manifest sass-loader@10.0.5
124 silly fetch manifest semver@7.3.2
125 silly fetch manifest source-map-loader@1.1.2
126 silly fetch manifest speed-measure-webpack-plugin@1.3.3
127 silly fetch manifest style-loader@2.0.0
128 silly fetch manifest stylus@0.54.8
129 silly fetch manifest stylus-loader@4.3.1
130 silly fetch manifest terser@5.3.7
131 silly fetch manifest terser-webpack-plugin@4.2.3
132 silly fetch manifest webpack-dev-middleware@3.7.2
133 silly fetch manifest webpack-dev-server@3.11.0
134 silly fetch manifest webpack-merge@5.2.0
135 silly fetch manifest webpack-sources@2.0.1
136 silly fetch manifest webpack-subresource-integrity@1.5.1
137 silly fetch manifest worker-plugin@5.0.0
138 silly fetch manifest tslint@^6.1.0
139 silly fetch manifest reflect-metadata@^0.1.2
140 silly fetch manifest canonical-path@1.0.0
141 silly fetch manifest dependency-graph@^0.7.2
142 silly fetch manifest fs-extra@4.0.2
143 silly fetch manifest source-map@^0.6.1
144 silly fetch manifest yargs@^16.1.1
145 silly fetch manifest jest-diff@^25.2.1
146 silly fetch manifest pretty-format@^25.2.1
147 silly fetch manifest @angular/core@9.0.0
148 silly fetch manifest @angular/compiler@9.0.0
149 silly fetch manifest tslib@^1.10.0
150 silly fetch manifest app-root-path@^3.0.0
151 silly fetch manifest aria-query@^3.0.0
152 silly fetch manifest axobject-query@2.0.2
153 silly fetch manifest css-selector-tokenizer@^0.7.1
154 silly fetch manifest cssauron@^1.4.0
155 silly fetch manifest damerau-levenshtein@^1.0.4
156 silly fetch manifest semver-dsl@^1.0.1
157 silly fetch manifest source-map@^0.5.7
158 silly fetch manifest sprintf-js@^1.1.2
159 silly fetch manifest @jest/core@^26.2.2
160 silly fetch manifest import-local@^3.0.2
161 silly fetch manifest jest-cli@^26.2.2
162 silly fetch manifest pretty-format@26.x
163 silly fetch manifest bs-logger@0.x
164 silly fetch manifest lodash.memoize@4.x
165 silly fetch manifest mkdirp@1.x
166 silly fetch manifest semver@7.x
167 http fetch GET 200 https://registry.npmjs.org/@jsdevtools%2fcoverage-istanbul-loader 217ms (from cache)
168 http fetch GET 200 https://registry.npmjs.org/mini-css-extract-plugin 205ms (from cache)
169 http fetch GET 200 https://registry.npmjs.org/pnp-webpack-plugin 204ms (from cache)
170 http fetch GET 200 https://registry.npmjs.org/speed-measure-webpack-plugin 197ms (from cache)
171 http fetch GET 200 https://registry.npmjs.org/source-map 181ms (from cache)
172 http fetch GET 200 https://registry.npmjs.org/tslib 169ms (from cache)
173 http fetch GET 200 https://registry.npmjs.org/source-map 166ms (from cache)
174 http fetch GET 200 https://registry.npmjs.org/sprintf-js 167ms (from cache)
175 http fetch GET 304 https://registry.npmjs.org/@angular-devkit%2fbuild-optimizer 235ms (from cache)
176 http fetch GET 304 https://registry.npmjs.org/copy-webpack-plugin 269ms (from cache)
177 http fetch GET 304 https://registry.npmjs.org/core-js 304ms (from cache)
178 http fetch GET 304 https://registry.npmjs.org/circular-dependency-plugin 335ms (from cache)
179 http fetch GET 304 https://registry.npmjs.org/@babel%2ftemplate 349ms (from cache)
180 http fetch GET 304 https://registry.npmjs.org/autoprefixer 351ms (from cache)
181 http fetch GET 304 https://registry.npmjs.org/babel-loader 366ms (from cache)
182 http fetch GET 304 https://registry.npmjs.org/@babel%2fgenerator 372ms (from cache)
183 http fetch GET 304 https://registry.npmjs.org/@babel%2fcore 373ms (from cache)
184 http fetch GET 304 https://registry.npmjs.org/@babel%2fpreset-env 378ms (from cache)
185 http fetch GET 304 https://registry.npmjs.org/@babel%2fruntime 379ms (from cache)
186 http fetch GET 304 https://registry.npmjs.org/cacache 378ms (from cache)
187 http fetch GET 304 https://registry.npmjs.org/@babel%2fplugin-transform-runtime 398ms (from cache)
188 http fetch GET 304 https://registry.npmjs.org/@ngtools%2fwebpack 399ms (from cache)
189 http fetch GET 304 https://registry.npmjs.org/cssnano 408ms (from cache)
190 http fetch GET 304 https://registry.npmjs.org/css-loader 411ms (from cache)
191 http fetch GET 304 https://registry.npmjs.org/file-loader 417ms (from cache)
192 http fetch GET 304 https://registry.npmjs.org/jest-worker 422ms (from cache)
193 http fetch GET 304 https://registry.npmjs.org/karma-source-map-support 421ms (from cache)
194 http fetch GET 304 https://registry.npmjs.org/less 428ms (from cache)
195 http fetch GET 304 https://registry.npmjs.org/license-webpack-plugin 433ms (from cache)
196 http fetch GET 304 https://registry.npmjs.org/@angular-devkit%2fbuild-webpack 450ms (from cache)
197 http fetch GET 304 https://registry.npmjs.org/less-loader 444ms (from cache)
198 http fetch GET 304 https://registry.npmjs.org/inquirer 447ms (from cache)
199 http fetch GET 304 https://registry.npmjs.org/loader-utils 453ms (from cache)
200 http fetch GET 304 https://registry.npmjs.org/postcss-import 449ms (from cache)
201 http fetch GET 304 https://registry.npmjs.org/postcss 453ms (from cache)
202 http fetch GET 304 https://registry.npmjs.org/postcss-loader 463ms (from cache)
203 http fetch GET 304 https://registry.npmjs.org/parse5-html-rewriting-stream 470ms (from cache)
204 http fetch GET 304 https://registry.npmjs.org/open 472ms (from cache)
205 http fetch GET 304 https://registry.npmjs.org/raw-loader 483ms (from cache)
206 http fetch GET 304 https://registry.npmjs.org/sass 481ms (from cache)
207 http fetch GET 304 https://registry.npmjs.org/resolve-url-loader 484ms (from cache)
208 http fetch GET 304 https://registry.npmjs.org/rollup 485ms (from cache)
209 http fetch GET 304 https://registry.npmjs.org/sass-loader 501ms (from cache)
210 http fetch GET 304 https://registry.npmjs.org/rimraf 504ms (from cache)
211 http fetch GET 304 https://registry.npmjs.org/rxjs 504ms (from cache)
212 http fetch GET 304 https://registry.npmjs.org/style-loader 502ms (from cache)
213 http fetch GET 304 https://registry.npmjs.org/source-map-loader 508ms (from cache)
214 http fetch GET 304 https://registry.npmjs.org/webpack-dev-middleware 523ms (from cache)
215 http fetch GET 304 https://registry.npmjs.org/webpack-dev-server 524ms (from cache)
216 http fetch GET 304 https://registry.npmjs.org/stylus 532ms (from cache)
217 http fetch GET 304 https://registry.npmjs.org/webpack-merge 532ms (from cache)
218 http fetch GET 304 https://registry.npmjs.org/terser 536ms (from cache)
219 http fetch GET 304 https://registry.npmjs.org/worker-plugin 552ms (from cache)
220 http fetch GET 304 https://registry.npmjs.org/stylus-loader 565ms (from cache)
221 http fetch GET 304 https://registry.npmjs.org/reflect-metadata 559ms (from cache)
222 http fetch GET 304 https://registry.npmjs.org/canonical-path 564ms (from cache)
223 http fetch GET 304 https://registry.npmjs.org/dependency-graph 569ms (from cache)
224 http fetch GET 304 https://registry.npmjs.org/jest-diff 563ms (from cache)
225 http fetch GET 304 https://registry.npmjs.org/fs-extra 575ms (from cache)
226 http fetch GET 304 https://registry.npmjs.org/webpack-subresource-integrity 582ms (from cache)
227 http fetch GET 304 https://registry.npmjs.org/terser-webpack-plugin 586ms (from cache)
228 http fetch GET 304 https://registry.npmjs.org/webpack-sources 588ms (from cache)
229 http fetch GET 304 https://registry.npmjs.org/tslint 587ms (from cache)
230 http fetch GET 304 https://registry.npmjs.org/pretty-format 585ms (from cache)
231 http fetch GET 304 https://registry.npmjs.org/yargs 604ms (from cache)
232 http fetch GET 304 https://registry.npmjs.org/cssauron 598ms (from cache)
233 http fetch GET 304 https://registry.npmjs.org/app-root-path 602ms (from cache)
234 http fetch GET 304 https://registry.npmjs.org/semver 634ms (from cache)
235 http fetch GET 304 https://registry.npmjs.org/@angular%2fcore 606ms (from cache)
236 http fetch GET 304 https://registry.npmjs.org/axobject-query 606ms (from cache)
237 http fetch GET 304 https://registry.npmjs.org/semver-dsl 604ms (from cache)
238 http fetch GET 304 https://registry.npmjs.org/aria-query 608ms (from cache)
239 http fetch GET 304 https://registry.npmjs.org/css-selector-tokenizer 608ms (from cache)
240 http fetch GET 304 https://registry.npmjs.org/damerau-levenshtein 608ms (from cache)
241 http fetch GET 304 https://registry.npmjs.org/@angular%2fcompiler 614ms (from cache)
242 http fetch GET 304 https://registry.npmjs.org/import-local 607ms (from cache)
243 http fetch GET 304 https://registry.npmjs.org/lodash.memoize 607ms (from cache)
244 http fetch GET 304 https://registry.npmjs.org/bs-logger 609ms (from cache)
245 http fetch GET 304 https://registry.npmjs.org/jest-cli 611ms (from cache)
246 http fetch GET 304 https://registry.npmjs.org/pretty-format 617ms (from cache)
247 http fetch GET 304 https://registry.npmjs.org/@jest%2fcore 620ms (from cache)
248 http fetch GET 304 https://registry.npmjs.org/mkdirp 617ms (from cache)
249 http fetch GET 304 https://registry.npmjs.org/semver 616ms (from cache)
250 timing idealTree:#root Completed in 3232ms
251 silly placeDep node_modules/@angular-devkit/architect rxjs@6.6.3 OK for: @angular-devkit/architect@0.1100.4 want: 6.6.3
252 silly fetch manifest tslib@^1.9.0
253 http fetch GET 200 https://registry.npmjs.org/tslib 6ms (from cache)
254 timing idealTree:node_modules/@angular-devkit/architect Completed in 10ms
255 silly fetch manifest webpack@4.44.2
256 http fetch GET 304 https://registry.npmjs.org/webpack 60ms (from cache)
257 silly fetch manifest @angular/compiler@11.0.4
258 http fetch GET 304 https://registry.npmjs.org/@angular%2fcompiler 60ms (from cache)
259 silly fetch manifest typescript@~4.0.0
260 http fetch GET 304 https://registry.npmjs.org/typescript 73ms (from cache)
261 silly placeDep ROOT @angular-devkit/build-optimizer@0.1100.4 OK for: @angular-devkit/build-angular@0.1100.4 want: 0.1100.4
262 silly placeDep ROOT @angular-devkit/build-webpack@0.1100.4 OK for: @angular-devkit/build-angular@0.1100.4 want: 0.1100.4
263 silly placeDep ROOT webpack-dev-server@3.11.0 OK for: @angular-devkit/build-webpack@0.1100.4 want: ^3.1.4
264 silly placeDep node_modules/@angular-devkit/build-angular @babel/core@7.12.3 OK for: @angular-devkit/build-angular@0.1100.4 want: 7.12.3
265 silly placeDep node_modules/@angular-devkit/build-angular @babel/generator@7.12.1 OK for: @angular-devkit/build-angular@0.1100.4 want: 7.12.1
266 silly placeDep ROOT @babel/plugin-transform-runtime@7.12.1 OK for: @angular-devkit/build-angular@0.1100.4 want: 7.12.1
267 silly placeDep node_modules/@angular-devkit/build-angular @babel/preset-env@7.12.1 OK for: @angular-devkit/build-angular@0.1100.4 want: 7.12.1
268 silly placeDep node_modules/@angular-devkit/build-angular @babel/runtime@7.12.1 OK for: @angular-devkit/build-angular@0.1100.4 want: 7.12.1
269 silly placeDep node_modules/@angular-devkit/build-angular @babel/template@7.10.4 OK for: @angular-devkit/build-angular@0.1100.4 want: 7.10.4
270 silly placeDep ROOT @jsdevtools/coverage-istanbul-loader@3.0.5 OK for: @angular-devkit/build-angular@0.1100.4 want: 3.0.5
271 silly placeDep ROOT @ngtools/webpack@11.0.4 OK for: @angular-devkit/build-angular@0.1100.4 want: 11.0.4
272 silly placeDep ROOT autoprefixer@9.8.6 OK for: @angular-devkit/build-angular@0.1100.4 want: 9.8.6
273 silly placeDep node_modules/@angular-devkit/build-angular babel-loader@8.1.0 OK for: @angular-devkit/build-angular@0.1100.4 want: 8.1.0
274 silly placeDep node_modules/@angular-devkit/build-angular cacache@15.0.5 OK for: @angular-devkit/build-angular@0.1100.4 want: 15.0.5
275 silly placeDep ROOT circular-dependency-plugin@5.2.0 OK for: @angular-devkit/build-angular@0.1100.4 want: 5.2.0
276 silly placeDep ROOT copy-webpack-plugin@6.2.1 OK for: @angular-devkit/build-angular@0.1100.4 want: 6.2.1
277 silly placeDep ROOT core-js@3.6.5 OK for: @angular-devkit/build-angular@0.1100.4 want: 3.6.5
278 silly placeDep ROOT css-loader@4.3.0 OK for: @angular-devkit/build-angular@0.1100.4 want: 4.3.0
279 silly placeDep ROOT cssnano@4.1.10 OK for: @angular-devkit/build-angular@0.1100.4 want: 4.1.10
280 silly placeDep ROOT file-loader@6.1.1 OK for: @angular-devkit/build-angular@0.1100.4 want: 6.1.1
281 silly placeDep node_modules/@angular-devkit/build-angular inquirer@7.3.3 OK for: @angular-devkit/build-angular@0.1100.4 want: 7.3.3
282 silly placeDep ROOT jest-worker@26.5.0 OK for: @angular-devkit/build-angular@0.1100.4 want: 26.5.0
283 silly placeDep ROOT karma-source-map-support@1.4.0 OK for: @angular-devkit/build-angular@0.1100.4 want: 1.4.0
284 silly placeDep ROOT less@3.12.2 OK for: @angular-devkit/build-angular@0.1100.4 want: 3.12.2
285 silly placeDep ROOT less-loader@7.0.2 OK for: @angular-devkit/build-angular@0.1100.4 want: 7.0.2
286 silly placeDep ROOT license-webpack-plugin@2.3.1 OK for: @angular-devkit/build-angular@0.1100.4 want: 2.3.1
287 silly placeDep node_modules/@angular-devkit/build-angular loader-utils@2.0.0 OK for: @angular-devkit/build-angular@0.1100.4 want: 2.0.0
288 silly placeDep ROOT mini-css-extract-plugin@1.2.1 OK for: @angular-devkit/build-angular@0.1100.4 want: 1.2.1
289 silly placeDep ROOT open@7.3.0 OK for: @angular-devkit/build-angular@0.1100.4 want: 7.3.0
290 silly placeDep ROOT parse5-html-rewriting-stream@6.0.1 OK for: @angular-devkit/build-angular@0.1100.4 want: 6.0.1
291 silly placeDep ROOT pnp-webpack-plugin@1.6.4 OK for: @angular-devkit/build-angular@0.1100.4 want: 1.6.4
292 silly placeDep ROOT postcss@7.0.32 OK for: @angular-devkit/build-angular@0.1100.4 want: 7.0.32
293 silly placeDep ROOT postcss-import@12.0.1 OK for: @angular-devkit/build-angular@0.1100.4 want: 12.0.1
294 silly placeDep ROOT postcss-loader@4.0.4 OK for: @angular-devkit/build-angular@0.1100.4 want: 4.0.4
295 silly placeDep ROOT raw-loader@4.0.2 OK for: @angular-devkit/build-angular@0.1100.4 want: 4.0.2
296 silly placeDep ROOT resolve-url-loader@3.1.2 OK for: @angular-devkit/build-angular@0.1100.4 want: 3.1.2
297 silly placeDep node_modules/@angular-devkit/build-angular rimraf@3.0.2 OK for: @angular-devkit/build-angular@0.1100.4 want: 3.0.2
298 silly placeDep ROOT rollup@2.32.1 OK for: @angular-devkit/build-angular@0.1100.4 want: 2.32.1
299 silly placeDep node_modules/@angular-devkit/build-angular rxjs@6.6.3 OK for: @angular-devkit/build-angular@0.1100.4 want: 6.6.3
300 silly placeDep ROOT sass@1.27.0 OK for: @angular-devkit/build-angular@0.1100.4 want: 1.27.0
301 silly placeDep ROOT sass-loader@10.0.5 OK for: @angular-devkit/build-angular@0.1100.4 want: 10.0.5
302 silly placeDep node_modules/@angular-devkit/build-angular semver@7.3.2 OK for: @angular-devkit/build-angular@0.1100.4 want: 7.3.2
303 silly placeDep ROOT source-map-loader@1.1.2 OK for: @angular-devkit/build-angular@0.1100.4 want: 1.1.2
304 silly placeDep ROOT speed-measure-webpack-plugin@1.3.3 OK for: @angular-devkit/build-angular@0.1100.4 want: 1.3.3
305 silly placeDep ROOT style-loader@2.0.0 OK for: @angular-devkit/build-angular@0.1100.4 want: 2.0.0
306 silly placeDep ROOT stylus@0.54.8 OK for: @angular-devkit/build-angular@0.1100.4 want: 0.54.8
307 silly placeDep ROOT stylus-loader@4.3.1 OK for: @angular-devkit/build-angular@0.1100.4 want: 4.3.1
308 silly placeDep node_modules/@angular-devkit/build-angular terser@5.3.7 OK for: @angular-devkit/build-angular@0.1100.4 want: 5.3.7
309 silly placeDep node_modules/@angular-devkit/build-angular terser-webpack-plugin@4.2.3 OK for: @angular-devkit/build-angular@0.1100.4 want: 4.2.3
310 timing idealTree Completed in 3955ms
311 timing command:install Completed in 3957ms
312 verbose stack Error: unable to resolve dependency tree
312 verbose stack     at Arborist.[failPeerConflict] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1045:25)
312 verbose stack     at Arborist.[placeDep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1129:30)
312 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:792:46
312 verbose stack     at Array.map (<anonymous>)
312 verbose stack     at Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:792:8)
312 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
312 verbose stack     at async Promise.all (index 1)
312 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:122:5)
312 verbose stack     at async install (/usr/local/lib/node_modules/npm/lib/install.js:39:3)
313 verbose cwd /Users/manohar/Projects/Learning/nx-angular-workspace
314 verbose Darwin 20.2.0
315 verbose argv "/usr/local/Cellar/node/15.4.0/bin/node" "/usr/local/bin/npm" "install" "--quiet"
316 verbose node v15.4.0
317 verbose npm  v7.0.15
318 error code ERESOLVE
319 error ERESOLVE unable to resolve dependency tree
320 error
321 error Found: tslint@6.0.0
321 error node_modules/tslint
321 error   dev tslint@"~6.0.0" from the root project
321 error   peer tslint@"^5.0.0 || ^6.0.0" from codelyzer@6.0.1
321 error   node_modules/codelyzer
321 error     dev codelyzer@"^6.0.0" from the root project
321 error
321 error Could not resolve dependency:
321 error peerOptional tslint@"^6.1.0" from @angular-devkit/build-angular@0.1100.4
321 error node_modules/@angular-devkit/build-angular
321 error   dev @angular-devkit/build-angular@"~0.1100.1" from the root project
321 error
321 error Fix the upstream dependency conflict, or retry
321 error this command with --force, or --legacy-peer-deps
321 error to accept an incorrect (and potentially broken) dependency resolution.
321 error
321 error See /Users/manohar/.npm/eresolve-report.txt for a full report.
322 verbose exit 1

Debug log attached
[2020-12-15T20_15_08_615Z-debug.log](https://github.com/nrwl/nx/files/5698417/2020-12-15T20_15_08_615Z-debug.log)

### Environment

>  NX  Report complete - copy this into the issue template

  Node : 15.4.0
  OS   : darwin x64
  npm  : 7.0.15

  nx : Not Found
  @nrwl/angular : 11.0.4
  @nrwl/cli : 11.0.4
  @nrwl/cypress : 11.0.4
  @nrwl/devkit : 11.0.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.4
  @nrwl/linter : 11.0.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.4
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.4
  typescript : 4.0.5

**Comment by vsavkin** [comment]
I was able to repro with with your version of NPM. Will fix it today. Thank you!

**Comment by vsavkin** [comment]
Fixed it here: https://github.com/nrwl/nx/commit/dfb7363199f6c87a443c69fad5e71387f619546d
I'm going to cut a patch release later today with the fix.

I'm going to close the issue.

**Comment by manoharnikkam** [comment]
It worked. Thank you @vsavkin. Greatly appreciate your help.
