### ISSUE TITLE
Having difficulty installing nx on my mac in global scope

### ISSUE THREAD

**Issue by manoharnikkam** [nrwl/nx#4308]
## Current Behavior
Having difficulty installing nx on my mac in global scope
![image](https://user-images.githubusercontent.com/8573069/102309181-d7b56680-3f2d-11eb-81aa-78c950e802ca.png)

## Expected Behavior
It should have installed nx and allowed me to create workspace with 
```npx create-nx-workspace myworkspace```

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/8573069/102309320-22cf7980-3f2e-11eb-8dc4-042248b67e9c.png)

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

[2020-12-16T05_36_05_536Z-debug.log](https://github.com/nrwl/nx/files/5700550/2020-12-16T05_36_05_536Z-debug.log)

### Environment

Mac BigSur
Darwin manohars-mbpx.lan 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

Followed the Option 1 instruction at https://npm.github.io/installation-setup-docs/installing/a-note-on-permissions.html to setup right permissions.

**Comment by vsavkin** [comment]
Really sorry about this. Fixed it in 11.0.8.

**Comment by manoharnikkam** [comment]
Thank you @vsavkin. It worked.
