### ISSUE TITLE
Failing Angular v11 waitForAsync migration due to missing tsconfig in test target

### ISSUE THREAD

**Issue by EvtK** [nrwl/nx#4309]
## Current Behavior
Migrate to v11 using nx migrate latest and run the migrations. The Angular waitForAsync migration does not have any effect.

This is due to the fact that for test targets there is no tsconfig option set, and the angular schematics determine the files to be used for the schematics based on the tsconfig file configured on the test and build target. 

```
"test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "apps/sample/jest.config.js",
            "passWithNoTests": true
          },
          "outputs": [
            "coverage/apps/sample"
          ]
        }
```

I have already opened up an [issue](https://github.com/angular/angular/issues/40100) on the angular GitHub tracker for this. But I'm not sure who should be in charge for solving this issue :)

## Expected Behavior
Migrate to v11 using nx migrate latest and run the migrations. The Angular waitForAsync should run through all the spec files and update the deprecated async with waitForAsync.

## Steps to Reproduce
npx create-nx-workspace@10.4.7
choose angular

change spec file of app.component.spec.ts to have the deprecated async:

```
import { async, TestBed } from '@angular/core/testing';
import { AppComponent } from './app.component';

describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [AppComponent],
    }).compileComponents();
  }));

  it('should create the app', () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.componentInstance;
    expect(app).toBeTruthy();
  });

  it(`should have as title 'sample'`, () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.componentInstance;
    expect(app.title).toEqual('sample');
  });

  it('should render title', () => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    const compiled = fixture.nativeElement;
    expect(compiled.querySelector('h1').textContent).toContain(
      'Welcome to sample!'
    );
  });
});
```

nx migrate latest
npm install
nx migrate --run-migrations=migrations.json

### Failure Logs
no logging actually, but spec file is not migrated.

### Environment
  Node : 12.18.3
  OS   : darwin x64
  npm  : 6.14.6
  
  nx : Not Found
  @nrwl/angular : 11.0.4
  @nrwl/cli : 11.0.4
  @nrwl/cypress : 11.0.4
  @nrwl/devkit : 11.0.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.4
  @nrwl/linter : 11.0.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.4
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.4
  typescript : 4.0.5

**Comment by vsavkin** [comment]
Fixed it here: https://github.com/nrwl/nx/commit/4278cfd337bbee155ed5efba83c4edc3df58dd30
Going to cut a patch release later today.

Going to close it this issue. If you have any problems migrating to the new release, let me know.

**Comment by EvtK** [comment]
awesome, thanks for the quick fix!

**Comment by EvtK** [comment]
@vsavkin the implemented changes now add a tsconfig entry in my angular.json for the test target, pointing to the tsconfig spec file. Is that how it should behave?
