### ISSUE TITLE
yarn should be used to resolve dependencies

### ISSUE THREAD

**Issue by maiermic** [nrwl/nx#4310]
## Current Behavior
```
yarn create nx-workspace myorg --preset=angular
```
generates a `package-lock.json` instead of `yarn.lock`, i.e. `npm` is used to resolve dependencies.

## Expected Behavior
`yarn` should be used to install/resolve dependencies.

**Comment by bekos** [comment]
@maiermic  You have to specify the package manager to use, otherwise it default to npm.
`yarn create nx-workspace myorg --preset=angular --package-manager=yarn`
