### ISSUE TITLE
Can't build publishable library

### ISSUE THREAD

**Issue by vitorcamachoo** [nrwl/nx#4312]
## Current Behavior

After creating a workspace and add a library with the following command:
```sh
nx g lib backoffice-ui --publishable --style=none
```
And when I run the command to build the library
```sh
NODE_ENV=production nx build backoffice-ui
```

 I get the following error related with the executor `@nrwl/web:package`:

`Error during bundle: Error: You have declared using "bundled" babelHelpers, but transforming ...`

**Comment by vsavkin** [comment]
@vitorcamachoo could you provide a small github repo with repro? Also, what package manager are you using?

**Comment by vitorcamachoo** [comment]
It was a bad config. Thanks

**Comment by fezproof** [comment]
> It was a bad config. Thanks

What was the config problem? Could you post a solution for others?

**Comment by alindsay55661** [comment]
Yes, what is the bad config problem and how did you correct it? I have the same issue.
