### ISSUE TITLE
@nrwl/angular:storybook-configuration schematic adds old version of Storybook to package.json

### ISSUE THREAD

**Issue by PerKjaer** [nrwl/nx#4313]
## Current Behavior

When you use @nrwl/angular:storybook-configuration to add Storybook support to an Angular 11 app or lib, the following lines are added to package.json:

"@storybook/addon-knobs": "^6.0.21",
"@storybook/angular": "^6.0.21",

Version 6.0.21 of Storybook does not work with Angular 11. Storybook only works because npm will install the newest compatible version of Storybook.

## Expected Behavior

A version of Storybook that is compatible with Angular 11 should be added to package.json.

## Steps to Reproduce

- Create a nx workspace containing an Angular app
- Add @nrwl/storybook to packages.json
- Run npm install
- Run the @nrwl/angular:storybook-configuration schematic to add Storybook configuration to the app

### Environment
  Node : 12.20.0
  OS   : win32 x64
  npm  : 6.14.9

  nx : Not Found
  @nrwl/angular : 11.0.8
  @nrwl/cli : 11.0.8
  @nrwl/cypress : 11.0.8
  @nrwl/devkit : 11.0.8
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.8
  @nrwl/linter : 11.0.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.8
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.8
  typescript : 4.0.5

**Comment by mehrad-rafigh** [comment]
@PerKjaer I had to install v6.2.0-alpha.5 to get it working again. Can you please confirm? I would create a PR for this if having an alpha is not an issue @vsavkin

**Comment by PerKjaer** [comment]
I have it working with Storybook v6.1.11.

It is this bug you get when using the old version of Storybook: https://github.com/storybookjs/storybook/issues/13093

**Comment by mehrad-rafigh** [comment]
@PerKjaer Alright then. I will update storybook to v6.1.11
