### ISSUE TITLE
Invalid symlink during remove and create app commands

### ISSUE THREAD

**Issue by rjvim** [nrwl/nx#4315]
## Current Behavior

`npx nx g remove awesome-app      `          
Error: ENOTDIR: not a directory, rmdir '<removed>/fe/apps/awesome-app/node_modules/@babel/runtime'

`npx nx g @nrwl/react-native:app awesome-app`

Failed to create symlinks for apps/awesome-app
(Invalid symlink apps/awesome-app/node_modules/@babel/runtime. Remove apps/awesome-app/node_modules and try again.)

## Expected Behavior
remove and create should work without above problems, basically, delete the folder completely. Apart from that create should work and create required symlinks.

## Steps to Reproduce

1. Follow https://blog.nrwl.io/introducing-react-native-support-for-nx-48d335e90c89
2. Run `npx nx g @nrwl/react-native:app awesome-app`
3. Run `npx nx g remove awesome-app`

### Failure Logs
```
Error: Failed to create symlinks for apps/investor
    at /<removed>/fe/node_modules/@nrwl/react-native/src/utils/symlink-task.js:48:46
    at MergeMapSubscriber.project (<removed>/fe/node_modules/@nrwl/tao/node_modules/@angular-devkit/schematics/src/engine/engine.js:276:24)
    at MergeMapSubscriber._tryNext (/<removed>/fe/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (<removed>/fe/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (<removed>/fe/node_modules/rxjs/internal/Subscriber.js:66:18)
    at <removed>/fe/node_modules/rxjs/internal/util/subscribeToPromise.js:7:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### Environment

  Node : 12.18.3
  OS   : darwin x64
  yarn : 1.22.4
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.0.8
  @nrwl/cypress : 10.4.4
  @nrwl/devkit : 11.0.8
  @nrwl/eslint-plugin-nx : 11.0.8
  @nrwl/express : Not Found
  @nrwl/jest : 10.4.4
  @nrwl/linter : 10.4.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 10.4.4
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.8
  @nrwl/web : 10.4.4
  @nrwl/workspace : 11.0.8
  typescript : 4.0.5

**Comment by rjvim** [comment]
Is this fixed?

**Comment by mattrybin** [comment]
I have the same problem.

**Comment by socialchair-June** [comment]
issue still exists!
