### ISSUE TITLE
[Angular + Nest] ESLint not properly set with preset with --linter=eslint

### ISSUE THREAD

**Issue by johannesschobel** [nrwl/nx#4317]
## Current Behavior

As described in #4272, the present for `--linter=eslint` was not used for the preset `angular` template. This has been fixed by @vsavkin in `nx 11.0.8`. Unfortunately, this has not been fixed for the `angular & nest` preset.

## Steps to Reproduce

- `npx create-nx-workspace@latest`
- select the `angular & nest` preset
- wait 
- check the created angular project

### Environment

Nx 11.0.8 (latest)

**Comment by AmirAlOmari** [comment]
Have been just about to create the same issue, thanks @johannesschobel 🙇 
The same applies to the `angular` preset as well 😢

**Comment by johannesschobel** [comment]
@AmirAlOmari , no, the `angular` preset has been fixed in 11.0.8.. Please see #4272 for more details

**Comment by AmirAlOmari** [comment]
@johannesschobel did you try it? I just tested with both `11.0.8` and `latest` tags. There are some logs

```
❯ npx create-nx-workspace@11.0.8
npx: installed 192 in 9.921s
? Workspace name (e.g., org name)     ipallower
? What to create in the new workspace angular           [a workspace with a single Angular application]
? Application name                    admin
? Default stylesheet format           SASS(.scss)  [ http://sass-lang.com   ]
? Default linter                      ESLint [ Modern linting tool ]
? Use Nx Cloud? (It's free and doesn't require registration.) Yes [Faster builds, run details, Github integra
tion. Learn more at https://nx.app]
Creating a sandbox with Nx...
added 192 packages from 155 contributors and audited 193 packages in 6.188s

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

new ipallower --no-interactive --preset=angular --appName=admin --style=scss --linter=eslint --nxCloud --collection=@nrwl/workspace
```

**Comment by AmirAlOmari** [comment]
What actually works fine: in `angular.json` there are default rules for ng schematics. Those now define eslint as default linter, so `nx g @nrwl/angular:app` generates app with the right linter 🚀

**Comment by vsavkin** [comment]
Fixed it here: https://github.com/nrwl/nx/commit/fba9b15895c644e8ae1cbdbb44f3f31fa1aa6feb

Thank you!
