### ISSUE TITLE
Warnings when creating an empty workspace and adding @nrwl/angular right after.

### ISSUE THREAD

**Issue by fiallega** [nrwl/nx#4321]
## Current Behavior
When creating a new empty workspace and adding the @nrwl/angular afterwards,  it gives the following warnings:
```
npm WARN @nrwl/cypress@11.0.8 requires a peer of cypress@>= 3 < 6 but none is installed. You must install peer dependencies yourself.
npm WARN @cypress/webpack-preprocessor@4.1.5 requires a peer of webpack@^4.18.1 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@8.2.2 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
```
This behavior does not happen if I create from scratch an angular workspace (instead of empty) which automatically adds the cypress and @nrwl/cypress dev dependencies correctly to the package.json and no warning are shown (no reference to webpack but no warnings either).

## Expected Behavior
I expect to be able to create a brand new empty workspace and add @nrwl/angular support, and be able to start my development without any warnings which I have to manually resolve. I am ok with resolving the first warning, but do not feel confident to resolve the second and third warnings. The fact that I get warning in a vanilla setup, looks suspicious and I don't know if it may create problems later in future updates and migrations.

## Steps to Reproduce
```
> npx create-nx-workspace@latest bad-me
   What to create in the new workspace empty 
   Use Nx Cloud? (It's free and doesn't require registration.) No
   new bad-me --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace
> cd bad-me
> npm install --save-dev @nrwl/angular
```

### Failure Logs
```
npm WARN @nrwl/cypress@11.0.8 requires a peer of cypress@>= 3 < 6 but none is installed. You must install peer dependencies yourself.
npm WARN @cypress/webpack-preprocessor@4.1.5 requires a peer of webpack@^4.18.1 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@8.2.2 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
```

### Environment
```
Node : 14.15.1
  OS   : darwin x64
  npm  : 6.14.9
  
  nx : Not Found
  @nrwl/angular : 11.0.8
  @nrwl/cli : 11.0.8
  @nrwl/cypress : 11.0.8
  @nrwl/devkit : 11.0.8
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.8
  @nrwl/linter : 11.0.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.8
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.8
  typescript : 4.0.5

```

**Comment by fiallega** [comment]
After building an angular application 
`nx generate @nrwl/angular:application --name=bad-you-ui --prefix=you --routing --linter=eslint`
all previous warnings go away and I am left with new warnings relate to eslint
```
npm WARN @angular-eslint/eslint-plugin@0.8.0-beta.1 requires a peer of eslint-plugin-import@* but none is installed. You must install peer dependencies yourself.
npm WARN @angular-eslint/eslint-plugin@0.8.0-beta.1 requires a peer of eslint-plugin-jsdoc@* but none is installed. You must install peer dependencies yourself.
npm WARN @angular-eslint/eslint-plugin@0.8.0-beta.1 requires a peer of eslint-plugin-prefer-arrow@* but none is installed. You must install peer dependencies yourself.

```

**Comment by JamesHenry** [comment]
I can address the angular-eslint peerDeps warnings

**Comment by realityfilter** [comment]
The missing peer dependency warning for webpack is already present in an empty workspace. 
The step to install the angular plugin is not necessary. This is present in versions 10.4.10 and 11.1.5.

Is there a workaround I can try?

**Comment by FrozenPandaz** [comment]
It is not expected for `@nrwl/angular` or any plugin to have no peer dependency warnings after installing it.

Generating a new application is expected to add the necessary dependencies for the plugin to work. The angular-eslint warnings have been fixed now so this is true.

I'm going to close this issue as the unintentional behavior has been remedied.
