### ISSUE TITLE
Nx Devkit external generator with default options

### ISSUE THREAD

**Issue by alexpol001** [nrwl/nx#4323]
How do I call an external generator (Nx devkit) in nx-plugin? If I do it directly with a function, then the default parameters from schema.json will not work

This worked in @angular-devkit/schematics via externalSchematics. But it don't work in Nx devkit generator

**Comment by mehrad-rafigh** [comment]
@alexpol001 Did you figure this out?

**Comment by AsmisAlan** [comment]
Hi, Any update ?
