### ISSUE TITLE
Error migrating to nx from cli: Cannot find module 'rxjs/observable/fromPromise'

### ISSUE THREAD

**Issue by wesleygrimes** [nrwl/nx#433]
**When I run the following command I receive the below error when trying to migrate an existing angular cli project to nx:**

` ng generate workspace my-app --collection=@nrwl/schematics`

**Error:**
```
Cannot find module 'rxjs/observable/fromPromise'
Error: Cannot find module 'rxjs/observable/fromPromise'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/wesgrimes/.nvm/versions/node/v8.11.1/lib/node_modules/@nrwl/schematics/src/collection/workspace/index.js:22:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Versions:**
* node: 8.11.1
* npm: 5.8.0
* `@nrwl/schematics`: 1.0.0
* `@angular/cli`: 1.7.4

**`package.json` snippet:**
```
"dependencies": {
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@ionic-native/app-version": "^4.6.0",
    "@ionic-native/camera": "^4.6.0",
    "@ionic-native/core": "^4.6.0",
    "@ionic-native/facebook": "^4.6.0",
    "@ionic-native/file-chooser": "^4.6.0",
    "@ionic-native/google-plus": "^4.6.0",
    "@ionic-native/in-app-browser": "^4.6.0",
    "@ionic-native/keyboard": "^4.6.0",
    "@ionic-native/push": "^4.6.0",
    "@ionic-native/social-sharing": "^4.6.0",
    "@ionic-native/splash-screen": "^4.6.0",
    "@ionic-native/status-bar": "^4.6.0",
    "@ionic/pro": "^1.0.20",
    "@ionic/storage": "2.1.3",
    "@ngrx/effects": "^5.2.0",
    "@ngrx/entity": "^5.2.0",
    "@ngrx/store": "^5.2.0",
    "@ngrx/store-devtools": "^5.2.0",
    "@types/parse": "^2.4.7",
    "branch-cordova-sdk": "^2.6.24",
    "browse": "0.4.0",
    "cordova-android": "6.4.0",
    "cordova-browser": "5.0.3",
    "cordova-ios": "4.5.4",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-appinfo": "^2.1.2",
    "cordova-plugin-camera": "^4.0.2",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-device": "^2.0.1",
    "cordova-plugin-facebook4": "^1.9.1",
    "cordova-plugin-filechooser": "^1.0.1",
    "cordova-plugin-googleplus": "^5.2.2",
    "cordova-plugin-inappbrowser": "^2.0.2",
    "cordova-plugin-ionic": "^4.1.3",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^1.1.16",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.1",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-x-socialsharing": "^5.3.2",
    "es6-promise-plugin": "^4.2.2",
    "intersection-observer": "^0.5.0",
    "ionic-angular": "3.9.2",
    "ionic-img-viewer": "^2.9.0",
    "ionicons": "3.0.0",
    "jquery": "^3.3.1",
    "jsonfile": "^4.0.0",
    "moment": "^2.20.1",
    "ngrx-store-localstorage": "^5.0.0",
    "parse": "^1.11.1",
    "phonegap-plugin-push": "^2.2.2",
    "quill": "^1.3.6",
    "raygun4js": "^2.8.6",
    "read-pkg": "^3.0.0",
    "rxjs": "^5.5.2",
    "sw-toolbox": "3.6.0",
    "trix": "^0.11.2",
    "underscore": "^1.8.3",
    "zone.js": "0.8.18"
  },
```

**Comment by noelmace** [comment]
This look like an issue with rxjs operators. I encountered the same issue, but I choosed to take this oportunity to switch to the current rxjs best practices, like [pipeable operators](https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md) :smiley:

I would highly recommand to do this. Before that, you should verify the version of rxjs you are using (``npm list rxjs``), and make some search (google / stackoverflow) about fromPromise vs from vs toPromise.

If after that you think this is still an issue with Nx, consider creating a project permitting to reproduce it, this could really help

**Comment by wesleygrimes** [comment]
Thanks, I’m using all pipeable operators and all current rxjs best practices. I’ll upload a project reproducing it shortly.

**Comment by noelmace** [comment]
Thx. Sorry for assuming you did not, it's so common these days :wink: Just for my information, did you verify that Nx didn't just upgraded rxjs from an old node_modules in your project by running npm install ?

For me, there is two options for this : 
1. you add a main rxjs-operators file that isn't used anymore after migrating to Nx (the ``import 'rxjs/add/observable/fromPromise';`` is missing)
2. the version of rxjs you are using isn't the same anymore, somehow

But this is just a fast answer.

**Comment by wesleygrimes** [comment]
No problem! It was a valid question. I have tried deleting the entire node_modules folder and re-running npm install. Also uninstalled angular cli, schematics, nrwl schematics and reinstalling globally. Are you at ng-conf by chance? I can show you in person.

**Comment by sdurnov** [comment]
@noelmace make sure you're importing rxjs operators explicitly in each file where you use it.

**Comment by noelmace** [comment]
@sdurnov I'm not the one facing this issue and was aware of this kind of solution, but thanks :wink: about operators import on this issue, this is what I talked about in the (1.) in https://github.com/nrwl/nx/issues/433#issuecomment-382557841. Anyway, this discussion is more about rxjs than Nx, that why @wesleygrimes will either close this issue or create a reproduction project in order to see if their really is a problem with Nx here.

**Comment by wesleygrimes** [comment]
Closing as my project wasn’t a true angular cli project. Rather it was an ionic project. I will work on converting my project over to angular cli and then give this another shot.
