### ISSUE TITLE
Placing of nx.deps should respect the cacheDirectory options

### ISSUE THREAD

**Issue by preda7or** [nrwl/nx#4345]
We are moving the nx cache outside the node_modules so even if the node_modules folder gets deleted, the cache will work. But the nx.deps file interferes with this, as it is always put under node_modules/.cache/nx, not respecting the cacheDirectory options used elsewhere.

https://github.com/nrwl/nx/blob/8e519cd8e41e6db1036675c2d09843079681c851/packages/workspace/src/core/nx-deps/nx-deps-cache.ts#L27

**Comment by vsavkin** [comment]
Fixed here: https://github.com/nrwl/nx/commit/ce877bb8ad2eb77262fee9856fe70752588341ef

Thank you!
