### ISSUE TITLE
Command failed: npx tao migrate --run-migrations=migrations.json

### ISSUE THREAD

**Issue by ravivit9** [nrwl/nx#4356]
Running migration rename-workspace-schematics
ENOENT: no such file or directory, link '/Users/user-name/projects/jopoworkspace/tools/schematics' -> '/Users/user-name/projects/jopoworkspace/tools/generators'

**Comment by vsavkin** [comment]
Do you have the tools/schematics directory or did you remove it prior to the migration process?

**Comment by sskieller** [comment]
I had the same problem and it appeared with and without the tools/schematics folder prior to the migration process..
The only way to avoid it for me, was to remove it from migrations.json

**Comment by vsavkin** [comment]
Could you provide a repro of the before state? A repo I can run the migration in?

The error message says `tools/schematics` is missing. The only thing the migration is doing is performing a move using the file system API, so there is no much we can do to fix it without having a repro.

Can it be that you had a partially completed migration you ran again? And maybe the folder was already moved?

**Comment by sskieller** [comment]
Ah, yes this might be it for when I had a folder with that name. Maybe a check on whether the folder exists, and if it doesnt, just skip migration would be useful here?
I didn't have a folder with that name the first time, so I think it should just skip if the folder doesnt exist?

**Comment by ravivit9** [comment]
I have the folder tools/generators and tools/schematics.  Do I need to remove schematics directory?

**Comment by vsavkin** [comment]
@ravivit9 yup, you can remove the schematics folders.

I thought about skipping it but I feel like it's more of an edge case. Someone has to remove the folder manually. It's not possible for us to account for all different manual changes. We do try to account for things that are common.

This is actually a good example of why we moved to `nx migrate`. Every workspace is different. The `tools/schematics` (now `tools/generators`) folder is used when you create a workspace generator, but for whatever reason you don't have it. You can either remove the migration from `migrations.json` (this capability is important) or you can crate the folder before running the migration. I'd advocate the latter. 

I'm going to close the issue.

**Comment by ravivit9** [comment]
Hi, this time upgrade went well and generators directory got created automatically but still error happened during schematics step.  But looks ok for now.  Hopefully nothing should fail after upgrade. Thanks for the support.
