### ISSUE TITLE
Migrating from 10.4.4 to 10.4.7 only updates @nrwl/workspace

### ISSUE THREAD

**Issue by mehrad-rafigh** [nrwl/nx#4357]
When running `nx migrate 10.4.7` only `@nrwl/workspace` gets updated to 10.4.7. The other packages are not updated. Is this the intended behavior?
 

## Description
nx report output
```
>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : 10.4.4
  @nrwl/cli : 10.4.4
  @nrwl/cypress : 10.4.4
  @nrwl/eslint-plugin-nx : 10.4.4
  @nrwl/express : Not Found
  @nrwl/jest : 10.4.4
  @nrwl/linter : 10.4.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.4.4
  @nrwl/web : Not Found
  @nrwl/workspace : 10.4.7
  typescript : 4.0.5
```

**Comment by vsavkin** [comment]
Unfortunately I'm not able to repro it. Could you try `rm -rf node_modules && npm i` before trying to migrate? If it is still doesn't work, can you provide a github repo with a repro?

**Comment by mehrad-rafigh** [comment]
@vsavkin removing node_modules and reinstalling did the trick. I cannot reproduce this issue anymore. Thank you very much
