### ISSUE TITLE
Unable to Define Bi-directional Relationships using TypeORM (Circular dependency)

### ISSUE THREAD

**Issue by sinnrrr** [nrwl/nx#4358]
This is the remind of the #2975 issue, because it is kept ignored for so long, as it dropped down of the list, but is so fateful, that I can't build apps using Nx workspace.

**Comment by sinnrrr** [comment]
Reproduction repo: https://github.com/sinnrrr/loonify-debug

**Comment by sinnrrr** [comment]
NOTE: tested this on the single nestjs nx app, and there is no circular dependency error!

**Comment by vsavkin** [comment]
Thanks for submitting the issue. I marked the other issue as a bug and assigned it to @Cammisuli. He should be able to take a look early next year. I'm going to to close this one though cause it's a duplicate.
