### ISSUE TITLE
Schema validation issue when running custom nx-plugin after migrating to nx 11

### ISSUE THREAD

**Issue by BLaZeKiLL** [nrwl/nx#4361]
## Current Behaviour
I have a nx-plugin project and after migrating to nx 11 from nx 10, now when I run the builder I get schema validation errors

I have a port property in the schema
```
"port": {
  "type": "integer",
  "description": "Port to listen on",
  "default": 3200
}
```

if I change the type to `number` it works fine

also if I mark a property as required like this
```
"required": ["buildTarget"]
```
and pass it
```
"serve": {
  "builder": "./dist/libs/nx-webcomponent:serve",
  "options": {
    "buildTarget": "samples-wc-angular:build"
  }
},
```
validation fails stating that required property was not passed

## Expected Behaviour
builder should run

## Steps to Reproduce
- create a nx workspace
- create a nx-plugin project
- add an integer property to a builder with a default value
- build the plugin & run the builder

[repo](https://github.com/BLaZeKiLL/microground/tree/fix/nx-update)

### Failure Logs
following error is logged (for the integer issue)
`Property 'port' does not match the schema. '3200' should be a 'integer'.`

following error is logged (for the required property issue)
`schema is invalid: data should have required property 'buildTarget'`

### Environment
```
  Node : 14.15.1
  OS   : win32 x64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : 11.0.15
  @nrwl/cli : 11.0.15
  @nrwl/cypress : 11.0.15
  @nrwl/devkit : 11.0.15
  @nrwl/eslint-plugin-nx : 11.0.15
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.15
  @nrwl/linter : 11.0.15
  @nrwl/nest : 11.0.15
  @nrwl/next : Not Found
  @nrwl/node : 11.0.15
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.15
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.15
  typescript : 4.0.5
```

**Comment by BLaZeKiLL** [comment]
integer validation passes on `11.0.16` thanks to this commit [a10c258](https://github.com/nrwl/nx/commit/a10c258) but again this is kind of a work around. so I added manual validation in the builder

also is there a migration guide from builders to executors ?

**Comment by richtera** [comment]
@arenier I noticed that if I specify the value on the commandline using --maxInstances=10 then it does do the correct casting. Just prompting for the value seems to cast it as a string instead of a number.
