### ISSUE TITLE
lint command not working for express apps with .js extension

### ISSUE THREAD

**Issue by cl3m3c7** [nrwl/nx#4364]
## Current Behavior

cannot lint JavaScript files <_Invalid lint configuration. Nothing to lint._>

## Expected Behavior

lint with no issues!

## Steps to Reproduce

generate new express application with babel-jest and js
generate new library using workspace plugin with babel-jest and js
```
nx generate @nrwl/express:application --name=my-app --babelJest --js
nx generate @nrwl/workspace:library --name=my-lib --babelJest --js
```
the lint key of the project in _workspace.json_ has ___the wrong file extension!___
```
"lint": {
	"executor": "@nrwl/linter:eslint",
	"options": {
		"lintFilePatterns": ["apps/my-app/**/*.ts"]
	}
},
```

**NOTE:**  .eslintrc.json of the express app doesn't include `env: { node: true }` !

### Environment

>  NX  Report complete - copy this into the issue template

  Node : 14.15.3
  OS   : win32 x64
  npm  : 6.14.9
  
  nx : Not Found
  @nrwl/angular : 11.0.15
  @nrwl/cli : 11.0.15
  @nrwl/cypress : 11.0.15
  @nrwl/devkit : 11.0.15
  @nrwl/eslint-plugin-nx : 11.0.15
  @nrwl/express : 11.0.15
  @nrwl/jest : 11.0.15
  @nrwl/linter : 11.0.15
  @nrwl/nest : 11.0.15
  @nrwl/next : 11.0.15
  @nrwl/node : 11.0.15
  @nrwl/react : 11.0.15
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.15
  @nrwl/web : 11.0.15
  @nrwl/workspace : 11.0.15
  typescript : 4.0.5

**Comment by vsavkin** [comment]
@JamesHenry maybe you can take a look?

**Comment by cl3m3c7** [comment]
sure, but the thing is that I am not experienced in contributing and in coding too.

**Comment by JamesHenry** [comment]
@vsavkin Will do! I don't think node/express supported JS the last time I worked on this, so will also check when that was added so I don't make assumptions
