### ISSUE TITLE
How to render template using ejs or hbs

### ISSUE THREAD

**Issue by kedevked** [nrwl/nx#4374]
## Description

I am using nest.js with nx. I would like to render template(hbs or ejs). But the template are not copied into the dist. So it causes the following error:
```
Failed to lookup view "template"
```
Here is a repo to reproduce it: https://github.com/kedevked/angular-nest/tree/render-template (on the branch `render-template` run `nx serve api`)

**Comment by jefftudorbenbria** [comment]
Were you able to solve your issue?

**Comment by kedevked** [comment]
Unfortunately no. I never found a way to do it

**Comment by jefftudorbenbria** [comment]
No problem, I did some digging and was able to resolve the issue by adjusting the build config so that my views were included in the assets. I'm not sure if that is the most correct solution but at the very least my templates are now included in the build and hence the dist folder. Now when my app is served the correct views are reachable.

here are the options I'm using in the build section of my project...

"options": {
            "outputPath": "dist/apps/survey-renderer",
            "main": "apps/survey-renderer/src/main.ts",
            "tsConfig": "apps/survey-renderer/tsconfig.app.json",
            "assets": ["apps/survey-renderer/src/assets", "apps/survey-renderer/src/views"]
          },

**Comment by jefftudorbenbria** [comment]
In the project JSON I configured it such that the views would be part of the dist by adding the views to the assets which probably is not the best way of doing it.

"targets": {
    "build": {
      "executor": "@nrwl/webpack:webpack",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/apps/sample",
        "main": "apps/sample/src/main.ts",
        "tsConfig": "apps/sample/tsconfig.app.json",
        "transformers": ["@nestjs/swagger/plugin"],
        "assets": ["apps/sample/src/assets", "apps/sample/src/views", "apps/sample/src/styles"],
        "target": "node",
        "compiler": "tsc"
      },
...

**Comment by eskres** [comment]
Thanks! Unfortunately I can't get this to work with esbuild for some reason.

**Comment by eskres** [comment]
For anybody with the same problem the assets config below has worked for me.
```

"targets": {
    "build": {
      "executor": "@nrwl/esbuild:esbuild",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/packages/auth",
        "format": ["cjs"],
        "main": "packages/auth/src/main.ts",
        "tsConfig": "packages/auth/tsconfig.app.json",
        "assets": ["packages/auth/src/assets",
                    {"input": "packages/auth/src/app/views", "glob": "**/*", "output": "/views"}
                  ],
        "esbuildOptions": {
          "sourcemap": true,
          "outExtension": {
            ".js": ".js"
          }
        }
      }
```
