### ISSUE TITLE
@nrwl/nest:library dry-run is hanging extra long

### ISSUE THREAD

**Issue by webberwang** [nrwl/nx#4377]
## Current Behavior

Takes about 1 min+ for dry run results to show

## Expected Behavior

Can't recall which version has changed this behavior

## Steps to Reproduce

1. Create nx workspace
2. Install nrwl nest plugin
3. Run inside vscode `@nrwl/nest:library`

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

```
  nx : 10.4.4
  @nrwl/angular : Not Found
  @nrwl/cli : 11.0.16
  @nrwl/cypress : 11.0.16
  @nrwl/devkit : 11.0.16
  @nrwl/eslint-plugin-nx : 11.0.16
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.16
  @nrwl/linter : 11.0.16
  @nrwl/nest : 11.0.16
  @nrwl/next : 11.0.16
  @nrwl/node : 11.0.16
  @nrwl/react : 11.0.16
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.16
  @nrwl/web : 11.0.16
  @nrwl/workspace : 11.0.16
  typescript : 4.1.2
```

**Comment by beeman** [comment]
Seeing the same. It's not only on dry run but also on the real run. 

I think this deleteFile method is the issue. It goes over all the files in the repo, including all files in node_modules, .git, dist and tmp.

And it does it twice as it deletes 2 files.


Ideally this deleteFile method would take .gitignore into account.


https://github.com/nrwl/nx/blob/ddf765bbb7211f2e024af38ba6489ce64c4c2b01/packages/nest/src/schematics/library/library.ts#L53

**Comment by Cammisuli** [comment]
That definitely looks like it's the culprit. We could probably just make a regular function that takes the host as an argument and call ```host.delete(`${options.projectRoot}/src/lib/${options.fileName}.spec.ts`)```.
