### ISSUE TITLE
Incorrect command on Angular Getting Started 

### ISSUE THREAD

**Issue by a45b** [nrwl/nx#4378]
## Current Behavior
On https://nx.dev/latest/angular/getting-started/getting-started the command of creating an angular app is incorrect. It's mention `npx create-nx-workspace --preset=react` 

## Expected Behavior
The Command should be 
`npx create-nx-workspace --preset=angular`

### Environment
![image](https://user-images.githubusercontent.com/1850968/102878170-dcb67080-446d-11eb-8aa4-d3021a04e96d.png)

**Comment by vsavkin** [comment]
Thank you for fixing it! Merged the fix.
