### ISSUE TITLE
withDeps in angular:webpack-browser builder options throws invalid schema errors 

### ISSUE THREAD

**Issue by Stonepaw** [nrwl/nx#4383]
The documentation for setting up [incremental builds](https://nx.dev/latest/angular/guides/ci/setup-incremental-builds-angular) states that the `--with-deps` and `--parallel` options can be added to the builder options in the workspace json:

> Note: you can obviously specify the --with-deps and --parallel flags as part of the options property on the executor in your angular.json or workspace.json.

```json
"todos": {
      "projectType": "application",
      "root": "apps/todos",
      "sourceRoot": "apps/todos/src",
      "prefix": "incremental-nx",
      "architect": {
        "build": {
          "builder": "@nrwl/angular:webpack-browser",
          "options": {
            "withDeps": true,
            "outputPath": "dist/apps/todos",
            "index": "apps/todos/src/index.html",
            "main": "apps/todos/src/main.ts",
            "polyfills": "apps/todos/src/polyfills.ts",
            "tsConfig": "apps/todos/tsconfig.app.json",
            "aot": true,
            "assets": ["apps/todos/src/favicon.ico", "apps/todos/src/assets"],
            "styles": ["apps/todos/src/styles.scss"],
            "scripts": []
          },
```
(other options and configs are removed for brevity)

## Current Behavior
Adding these `withDeps` and `parallel` to `architect.build.options` with a builder of`"builder": "@nrwl/angular:webpack-browser",` and running `nx build <app>` throws the error: 

```
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(withDeps).
```

## Expected Behavior

The build should run with the --with-deps and --parallel flags

## Steps to Reproduce

- Create a new angular application using `npx create-nx-workspace@latest`
- Change the app builder to `"@nrwl/angular:webpack-browser"`
- Add `withDeps: true` to `architect.build.options`
- run `nx build todos`

### Environment

```
  Node : 12.19.0
  OS   : linux x64
  yarn : 1.22.5
  
  nx : Not Found
  @nrwl/angular : 11.0.16
  @nrwl/cli : 11.0.16
  @nrwl/cypress : 11.0.16
  @nrwl/devkit : 11.0.16
  @nrwl/eslint-plugin-nx : 11.0.16
  @nrwl/express : 11.0.16
  @nrwl/jest : 11.0.16
  @nrwl/linter : 11.0.16
  @nrwl/nest : 11.0.16
  @nrwl/next : Not Found
  @nrwl/node : 11.0.16
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.16
  @nrwl/web : 11.0.16
  @nrwl/workspace : 11.0.16
  typescript : 4.0.5

```

**Comment by vsavkin** [comment]
@juristr I think the docs are not right https://nx.dev/latest/angular/guides/ci/setup-incremental-builds-angular. `ng-packagr-lite` doesn't support withDeps or parallel.

**Comment by vsavkin** [comment]
@Stonepaw the docs are incorrect. Every command in Nx can be invoked with --withDeps and --parallel. It affects what part of the graph Nx will try to process and if it will serially or not. 

The only executor/builder that supports it is file-server because it invokes `nx build` under the hood so it can pass the flags to it.

This is what the docs should say:

```
"app0": {
    "projectType": "application",
    ...
    "architect": {
        "build": {
            "builder": "@nrwl/angular:webpack-browser",
            "options": { ... }
            "configurations": { ... }
        },
        "serve": {
            "builder": "@nrwl/web:file-server",
            "options": {
                "buildTarget": "app0:build",
                "withDeps": true,
                "paralell": false
            },
            "configurations": {
                "production": {
                    "buildTarget": "app0:build:production"
                }
            }
        },
        ...
    }
},
```

**Comment by vsavkin** [comment]
Fixed it here: https://github.com/nrwl/nx/commit/f0009c19414a96675a8b846c2bbaf6d986f8343d

Thank you!

**Comment by juristr** [comment]
> @juristr I think the docs are not right https://nx.dev/latest/angular/guides/ci/setup-incremental-builds-angular. `ng-packagr-lite` doesn't support withDeps or parallel.
> 
> 

@vsavkin oops, ofc. thx for the fix!
