### ISSUE TITLE
How to create specific version of angular project?

### ISSUE THREAD

**Issue by shravansofts** [nrwl/nx#4388]
How to create specific version of angular project?
nx g @nrwl/angular:app@10.4.2 myapp --routing --style=scss --unit-test-runner=karma

## Description
nx g @nrwl/angular:app@10.4.2 myapp --routing --style=scss --unit-test-runner=karma
this is not working

**Comment by brandonroberts** [comment]
You can start with a specific version of Nx for your workspace, but all the package versions should be the same as the root package.json

**Comment by shravansofts** [comment]
Didn't understand clearly.
can you provide example commands?

**Comment by shravansofts** [comment]
Any update on this?

**Comment by eduardoperez2151** [comment]
Any Update?

**Comment by wengtad** [comment]
What I did was:

Angular v10 workspace

```bash
npx create-nx-workspace@10.4.15 <your-workspace-name>
```

Angular v11 workspace

```bash
npx create-nx-workspace@11.6.3 <your-workspace-name>
```

You cannot create multiple version of Angular in same workspace because it is refer to root `package.json`.
Hope it help.

**Comment by abf7d** [comment]
Just as a note, I was not able to get this to work with first initializing an empty repository, installing @nrwl/angular, then generating an angular applicaiton. I needed to generate an application with an angular app. Then it installed the right version of angular.
