### ISSUE TITLE
Angular schematics always generated under application's root

### ISSUE THREAD

**Issue by itayod** [nrwl/nx#4402]
## Current Behavior
Following my comment [here](https://github.com/nrwl/nx/issues/4298#issuecomment-749468134), it seems like every schematics command is now generated under the application root path, e.g. `apps/my-app/src/app`.

So for example, if I am trying to create a new component under `apps/my-app/src/app/some/nested/folder` it will be generated `in apps/my-app/src/app`.

## Expected Behavior
Schematics commands should respect the current process path.

## Steps to Reproduce
* create a new workspace `my-app`
* run `$ mkdir apps/internal/src/app/nested && cd $_`
* run any Angular's schematics command (e.g. `$ ng g component hello`).

### Environment
  Node : 14.15.0
  OS   : win32 x64
  npm  : 6.14.8

  @nrwl/angular : 11.0.15
  @nrwl/cli : 11.0.15
  @nrwl/cypress : 11.0.15
  @nrwl/devkit : 11.0.15
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.15
  @nrwl/linter : 11.0.15
  @nrwl/nest : 11.0.15
  @nrwl/next : Not Found
  @nrwl/node : 11.0.15
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.15
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.15
  typescript : 4.0.5

**Comment by SonicReal** [comment]
Still doesn't work

**Comment by Nikami** [comment]
@itayod @vsavkin 
Hello guys,
Do you have a chance to test this issue? Seems it's still reproducible in my case.

### Environment
  Node : 12.18.4
  OS   : win32 x64
  npm  : 6.14.9
  
  nx : Not Found
  @nrwl/angular : 11.1.5
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.5
  typescript : 4.0.5

**Comment by viktor-potapov** [comment]
Waiting solution!

**Comment by itayod** [comment]
> @itayod @vsavkin
> Hello guys,
> Do you have a chance to test this issue? Seems it's still reproducible in my case.
> 
> ### Environment
> Node : 12.18.4
> OS : win32 x64
> npm : 6.14.9
> 
> nx : Not Found
> @nrwl/angular : 11.1.5
> @nrwl/cli : 11.1.5
> @nrwl/cypress : 11.1.5
> @nrwl/devkit : 11.1.5
> @nrwl/eslint-plugin-nx : Not Found
> @nrwl/express : Not Found
> @nrwl/jest : 11.1.5
> @nrwl/linter : 11.1.5
> @nrwl/nest : Not Found
> @nrwl/next : Not Found
> @nrwl/node : Not Found
> @nrwl/react : Not Found
> @nrwl/schematics : Not Found
> @nrwl/tao : 11.1.5
> @nrwl/web : Not Found
> @nrwl/workspace : 11.1.5
> typescript : 4.0.5

correct this is still happening... I will open another issue as it seems I can not reopen this one
