### ISSUE TITLE
express preset invalid

### ISSUE THREAD

**Issue by jbojcic1** [nrwl/nx#4425]
## Current Behavior
`npx create-nx-workspace --preset=express` fails with `Invalid preset` error

## Expected Behavior
It should create workspace with express app according to the [docs](https://nx.dev/latest/node/getting-started/getting-started)

## Steps to Reproduce
Run `npx create-nx-workspace --preset=express` as suggested in the [docs](https://nx.dev/latest/node/getting-started/getting-started)

### Failure Logs
<img width="397" alt="Screen Shot 2021-01-02 at 4 55 49 PM" src="https://user-images.githubusercontent.com/10374826/103461035-72c68280-4d1b-11eb-847a-b7bbd41c6b08.png">

**Comment by vsavkin** [comment]
Thanks for reporting this. Fixed it here: https://github.com/nrwl/nx/commit/8de8273f1ccb15277b79f1987fde410617a41538
