### ISSUE TITLE
Storybook builds incorrectly for a React app.

### ISSUE THREAD

**Issue by iamvinitk** [nrwl/nx#4426]
Value of `someClass.getName()` becomes `undefined` when storybook is used but works as expected with `serve`.

[Link to repo](https://github.com/iamvinitk/nx-storybook-bug)

`App.tsx`
```import React from 'react';

import './app.css';

import SomeClass from './SomeClass';

export const App = () => {
  const someClass = new SomeClass('Demo App')

  return (
    <div className="app">
      <header className="flex">
        <h1>Welcome to {someClass.getName()}.</h1>
      </header>
    </div>
  );
};

export default App;
```

`SomeClass.ts`
```
export default class SomeClass{
  constructor(private name: string) {
  }

  getName(){
    return this.name
  }
}

```
## Report
```
  Node : 14.15.0
  OS   : darwin x64
  npm  : 6.14.10
  
  nx : 11.0.20
  @nrwl/angular : Not Found
  @nrwl/cli : 11.0.20
  @nrwl/cypress : 11.0.20
  @nrwl/devkit : 11.0.20
  @nrwl/eslint-plugin-nx : 11.0.20
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.20
  @nrwl/linter : 11.0.20
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.0.20
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.20
  @nrwl/web : 11.0.20
  @nrwl/workspace : 11.0.20
  typescript : 4.0.5
```

Output of `nx run demoapp:storybook`

<img width="1920" alt="Screenshot 2021-01-02 at 9 08 48 PM" src="https://user-images.githubusercontent.com/17565617/103461013-0cecf180-4d41-11eb-9602-181e63bb88f6.png">

Output of `nx run demoapp:serve`

<img width="1920" alt="Screenshot 2021-01-02 at 9 09 04 PM" src="https://user-images.githubusercontent.com/17565617/103461015-0f4f4b80-4d41-11eb-825d-9f98c7916ada.png">

**Comment by juristr** [comment]
@iamvinitk forgot to keep you updated. The React storybook setup is undergoing some refactoring which solves exactly your issue among other things such as a cleaner Storybook setup in general. There's an open issue on Storybook that prevents our merge to get in atm.

If you're interested, keep an eye on #4799

**Comment by juristr** [comment]
Nx 12.7 has a new React Storybook preset which we export as part of `@nrwl/react`. That should fix the issue. 

Here's a preview doc which will obviously be online on nx.dev once it is released: https://nx-dev-git-refactor-react-storybook-setup-nrwl.vercel.app/preview/react/storybook/migrate-webpack-final

The easier is to upgrade once 12.7 is out, generate a new library with Storybook and inspect the setup.
