### ISSUE TITLE
publish a lib that imports another lib (is not under 'rootDir')

### ISSUE THREAD

**Issue by satanTime** [nrwl/nx#4429]
Hi guys,

my plan is:
1. to have a core lib that implements my solution (core)
2. to have a react lib that prepares the core lib for react apps (redux)
3. to have an angular lib that prepares the core lib for angular apps (ngrx)

- libs
   - core
   - ngrx
   - redux

Therefore, I created 2 publishable (angular:lib and react:lib) libs and 1 buildable (web:lib)

But when I try to build angular or react I get the next error:

```typescript
ERROR: libs/core/src/index.ts:1:15 - error TS6059: File '.../libs/core/src/lib/core.ts' is not under 'rootDir' '.../libs/ngrx/src'. 'rootDir' is expected to contain all source files.
```

My goal is to have 2 libs that contain the whole codebase and don't have any dependencies.

## Question
I've tried to googe, but only found that people struggle with the same issue.

Is there an option to implement something what I described above?

Thank you in advance.

**Comment by satanTime** [comment]
when I changed `workspace.json` to
```json
      "root": "libs",
      "sourceRoot": "libs",
```

it started to work for react lib, but for angular it still shows the same error.

**Comment by satanTime** [comment]
I decided to go for the solution when the code is under angular lib and react lib re-exports it, but the problem is that I can't build the react lib now, it fails do to exported types and interfaces.

If I remove them from exports - the code compiles, but the problem is that I need these types being exported by my lib.

```
Error during bundle: Error: 'HANDLER_ENTITY' is not exported by libs/ngrx/src/lib/types.ts
Bundle failed: redux
```

```
export type HANDLER_ENTITY = ....;
```

```
        "build": {
          "executor": "@nrwl/web:package",
          "outputs": [
            "{options.outputPath}"
          ],
          "options": {
            "outputPath": "dist/libs/redux-entity-relationship",
            "tsConfig": "libs/ngrx/tsconfig.lib.json",
            "project": "libs/redux/package.json",
            "entryFile": "libs/ngrx/src/index.ts",
            "external": [
              "react",
              "react-dom"
            ],
            "babelConfig": "@nrwl/react/plugins/bundle-babel",
            "rollupConfig": "@nrwl/react/plugins/bundle-rollup",
            "assets": [
              {
                "glob": "README.md",
                "input": ".",
                "output": "."
              }
            ]
          }
        },
```

**Comment by satanTime** [comment]
After some investigation, I gave up and decided to use angular build for react, but serving angular stuff under an independent entrypoint: https://github.com/ng-packagr/ng-packagr/blob/master/docs/secondary-entrypoints.md. This let avoid installing angular dependencies for react.

**Comment by dangviettuan** [comment]
#4620 I think this issue can help you
