### ISSUE TITLE
Migration to Nx 11 fails with "Cannot find module '@angular-devkit/core/src/experimental/workspace'"

### ISSUE THREAD

**Issue by luchsamapparat** [nrwl/nx#4432]
## Current Behavior

Migration from Nx 10.3 and Angular 10.1.5 fails with `Cannot find module '@angular-devkit/core/src/experimental/workspace'`.

```
Running migration @nrwl/workspace:add-explicit-dep-on-tao
Cannot find module '@angular-devkit/core/src/experimental/workspace'
Require stack:
- C:\Users\Marvin\Projekte\nx-tao-migration-issue\node_modules\@angular-devkit\schematics\src\exception\exception.js
- C:\Users\Marvin\Projekte\nx-tao-migration-issue\node_modules\@angular-devkit\schematics\src\tree\static.js
- C:\Users\Marvin\Projekte\nx-tao-migration-issue\node_modules\@angular-devkit\schematics\src\index.js
- C:\Users\Marvin\Projekte\nx-tao-migration-issue\node_modules\@nrwl\workspace\src\migrations\update-10-4-0\add-explicit-dep-on-tao.js
- C:\Users\Marvin\Projekte\nx-tao-migration-issue\node_modules\@nrwl\tao\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\Marvin\Projekte\nx-tao-migration-issue\node_modules\@nrwl\tao\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\Marvin\Projekte\nx-tao-migration-issue\node_modules\@nrwl\tao\src\commands\migrate.js
- C:\Users\Marvin\Projekte\nx-tao-migration-issue\node_modules\@nrwl\tao\index.js
C:\Users\Marvin\Projekte\nx-tao-migration-issue\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: npx tao migrate --run-migrations=migrations.json
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.handler (C:\Users\Marvin\Projekte\nx-tao-migration-issue\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:76:21)
    at Object.runCommand (C:\Users\Marvin\Projekte\nx-tao-migration-issue\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\Users\Marvin\Projekte\nx-tao-migration-issue\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (C:\Users\Marvin\Projekte\nx-tao-migration-issue\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (C:\Users\Marvin\Projekte\nx-tao-migration-issue\node_modules\@nrwl\cli\lib\init-local.js:24:13)
    at Object.<anonymous> (C:\Users\Marvin\Projekte\nx-tao-migration-issue\node_modules\@nrwl\cli\bin\nx.js:12:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 7272,
  stdout: null,
  stderr: null
}
```

## Expected Behavior

Migration is successful.

## Steps to Reproduce

```
npx nx migrate latest # or npx nx migrate @nrwl/workspace@latest
npm install
nx migrate --run-migrations=migrations.json
```

in this demo project: https://github.com/luchsamapparat/nx-tao-migration-issue

### Failure Logs

👉🏻 [log.txt](https://github.com/nrwl/nx/files/5764058/log.txt)

### Environment

```

>  NX  Report complete - copy this into the issue template

  Node : 14.15.0
  OS   : win32 x64
  npm  : 6.14.8
  
  nx : Not Found
  @nrwl/angular : 11.0.20
  @nrwl/cli : 10.3.0
  @nrwl/cypress : 11.0.20
  @nrwl/devkit : 11.0.20
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.20
  @nrwl/linter : 11.0.20
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.0
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.20
  typescript : 4.0.3
```

**Comment by luchsamapparat** [comment]
[This comment](https://github.com/nrwl/nx/issues/4261#issuecomment-748629141) recommends to use Yarn resolutions to fix the problem, but I think there should be an "official" resolution to this issue that does not asks me to change my package manager.

**Comment by vsavkin** [comment]
Could you try the following?

```
npx @nrwl/tao@latest migrate latest
```

**Comment by luchsamapparat** [comment]
Thanks for the quick feedback. I did as you suggested and ran

```
npx @nrwl/tao@latest migrate latest
npm install
nx migrate --run-migrations=migrations.json
```

After that, all dependencies were updated from 10 to 11, so that seems to be an easy solution for the issue.

However, I still don't understand what's happening here. Running `npx nx migrate @nrwl/workspace@latest` after that didn't produce any further changes. What then is the difference between migrating `@nrwl/tao` and `@nrwl/workspace`?

Also, as you recommend not using `ng update` anymore, how do I get a list of outdated Angular packages as `ng update` provided? I noticed that the Nx migration didn't update `@angular/cdk`.

```
❯ $env:FORCE_NG_UPDATE="true"
❯ ng update

>  NX   WARNING  The Angular CLI was invoked instead of the Nx CLI. Use "npx ng [command]" or "nx [command]" instead.

Using package manager: 'npm'
Collecting installed dependencies...
Found 54 dependencies.
    We analyzed your package.json, there are some packages to update:

      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cdk                       10.2.4 -> 11.0.3         ng update @angular/cdk
      @angular/core                      11.0.3 -> 11.0.5         ng update @angular/core
      rxjs                               6.5.5 -> 6.6.3           ng update rxjs
```

**Comment by vsavkin** [comment]
`nx migrate` invokes `tao migrate` under the hood. It's just an impl detail.  The command I suggested simply runs the latest version of the migration logic cause it gets it from npm.

You can use `FORCE_NG_UPDATE`  to invoke any `ng update` functionality. I personally think that `ng update` telling you what to update is a misplaced responsibility.  

Here is why:

`npm/yarn/pnpm` will tell you what to update based on deps and peer deps.  If there is a conflict of a dep, you will see a warning or an error (this depends on the version of npm you use) when running `npm install`. `ng update` implements an almost identical mechanism, but now you have two tools that manage the up-to-dateness and the cohesion of your dep graph: `npm` and `ng`. And `npm` is the only one that  really matters. I think ng acting as a package manager is a mistake cause npm6, npm7, yarn1, yarn2, and pnpm all work differently. So you are guaranteed to have disagreements between ng and the package manager you use. Having said that, if you find this functionality useful, you can use `FORCE_NG_UPDATE`.

`@angular/cdk` 10x is compatible with Angular 11, but you can update it manually by running `nx migrate @angular/cdk@latest`.

Hope it clarifies things.

**Comment by luchsamapparat** [comment]
thanks for your detailed answer!

**Comment by Narven** [comment]
> Could you try the following?
> 
> ```
> npx @nrwl/tao@latest migrate latest
> ```
> 
> For some reason you have an old version of `@nrwl/tao`: `10.3.0` where it should be `11.0.20`. One thing you can do as well is to set `@nrwl/tao` to 11.0.20 explicitly in package.json before running `npm install`

This solved the problem for me.
