### ISSUE TITLE
Add `nx add` support in non-angular repos

### ISSUE THREAD

**Issue by yjaaidi** [nrwl/nx#4435]
## Description

I might be missing something but apparently, `nx add` doesn't work on non-angular repos.
`nx add` should install a package and run the `ng-add` schematic event if `@angular/cli` is not available.

This could be useful for nx plugins like `@jscutlery/semver` where currently users have to first install the package then run `nx g @jscutlery/semver:ng-add` manually.

If this makes sense, I'll be happy to help with a PR.

**Comment by edbzn** [comment]
up

**Comment by yjaaidi** [comment]
Oups! Can we reopen this issue to keep it alive? 😊
