### ISSUE TITLE
NextJS app creation ends with error

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#4436]
## Current Behavior
Next app creation command fails when install deps

## Expected Behavior
The process ends without errors

## Steps to Reproduce
1. Create a empty workspace
2. Install @nrwl/next plugin
3. Create the app

### Failure Logs

```
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^10.0.3" from @nrwl/next@11.0.18
npm ERR! node_modules/@nrwl/next
npm ERR!   dev @nrwl/next@"11.0.18" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
```

### Environment
Node : 15.5.0
  OS   : darwin x64
  npm  : 7.3.0
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.0.18
  @nrwl/cypress : 11.0.18
  @nrwl/devkit : 11.0.18
  @nrwl/eslint-plugin-nx : 11.0.18
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.18
  @nrwl/linter : 11.0.18
  @nrwl/nest : 11.0.18
  @nrwl/next : 11.0.18
  @nrwl/node : 11.0.18
  @nrwl/react : 11.0.18
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.18
  @nrwl/web : 11.0.18
  @nrwl/workspace : 11.0.18
  typescript : 4.1.3
  
  > Same error with NX 11.0.20
  
  ### Workaround
  To bypass error use `npm i --legacy-peer-deps`

**Comment by vsavkin** [comment]
Thank you for reporting this! I fixed and I'll cut a version with the fix tomorrow.

For now, you can update package.json to set the version of next to 10.0.3 and run `npm install` after.
