### ISSUE TITLE
Vulnerability in peer dependency (axios)

### ISSUE THREAD

**Issue by wojtek1150** [nrwl/nx#4439]
Currently nx packages are using axios in v 0.19.2 which is affected: https://www.npmjs.com/advisories/1594
Please update to 0.21.1 or latest

Also it would be nice if fix will be applied to the older major versions (v10.x.x, v9.x.x). I think that many users still using them (for Angular v10, NX v10 should be used etc.)

**Comment by tmc101** [comment]
I'm (easily) confused.

npmjs.com is showing a couple of new releases:

![image](https://user-images.githubusercontent.com/11647741/104587743-45ed6600-565f-11eb-8971-36148d989a41.png)

But I can't see these tags or releases in the nx repo.

**Comment by CWSites** [comment]
Which version has this been fixed in?

**Comment by naticaceres** [comment]
seems to be there on v 14.8.4
source: https://github.com/nrwl/nx/releases?page=2#:~:text=)%20(4a30fcd)-,misc%3A%20update%20axios%20to%201.0.0,-(%2312437)%20(
