### ISSUE TITLE
What is viz? Not viz.js, but viz.

### ISSUE THREAD

**Issue by damienwebdev** [nrwl/nx#444]
# What is this?

I just created an NX workspace using the nx commands. It looks like your schematics adds a random empty library.

I see elsewhere in the codebase you're installing `viz.js`, is that intended?

Clearly this doesn't look legit.

https://www.npmjs.com/package/viz

https://github.com/nrwl/nx/blob/08896fd19575aedf0c6d006c69562d4d03b3add4/packages/schematics/src/collection/application/files/__directory__/package.json

**Comment by kylecordes** [comment]
`viz` itself looks like a benign accidental mispublish, not nefarious.

https://unpkg.com/viz@0.0.1/

There is no code in there, just a empty starting package and Readme.

**Comment by damienwebdev** [comment]
@kylecordes Agreed. Should be removed ASAP anyways.

**Comment by FrozenPandaz** [comment]
Good catch! We will resolve this ASAP!

**Comment by damienwebdev** [comment]
@vsavkin resolved this in https://github.com/nrwl/nx/commit/e40503c7e3c879dd8abd65064f7f76a8a26a7729 I'll close as this is now in master.
