### ISSUE TITLE
ESLint issues in karma.conf.js inside angular applications and libraries

### ISSUE THREAD

**Issue by whernebrink** [nrwl/nx#4441]
## Current Behavior
When creating a new workspace (nx 11) using eslint as the linter and karma as the unit test runner, I get linting errors about `require()`, `module.export` and `__dirname` inside the `karma.conf.js` inside the `apps/my-app/karma.conf.js` and `libs/my-lib/karma.conf.js`. 

## Expected Behavior
No linting issues to appear for using require, module.exports and __dirname inside karma.conf.js

## Steps to Reproduce
- Create new nx workspace (preset angular)
- Configure @nrwl/angular:application/library to have karma as unit test runner and linter to be eslint
- Remove initial application, jest configurations, and codelyzer
- Generate a new angular application or library
- Inside apps/your-app/karma.conf.js you will now see the above mentioned linting issues (see screenshots below)

Here is a bare bone repository with the above steps (i.e. nx workspace using eslint, application and library using eslint and karma): https://github.com/whernebrink/nrwl-airlines-karma

### Failure Logs
- Root karma.conf.js has no linting issues
![Root karma.conf.js has no linting issues](https://raw.githubusercontent.com/whernebrink/nrwl-airlines-karma/main/screenshots/no-issue-in-root.png)

- Application and Library karma.conf.js has linting issues
![Application and Library karma.conf.js has linting issues](https://raw.githubusercontent.com/whernebrink/nrwl-airlines-karma/main/screenshots/karma-linting-issue-in-app.png)

**Comment by whernebrink** [comment]
Also noticing these linting issues when generating a .storybook for my UI library:

![Screenshot 2021-01-29 at 15 44 55](https://user-images.githubusercontent.com/73601152/106289496-a37dd700-6249-11eb-835d-b343b6c8bbfd.png)

**Comment by JamesHenry** [comment]
The first of this issues (module, __dirname globals) was resolved by #4804 the second part (no-var-requires) is resolved by #4831

**Comment by JamesHenry** [comment]
Closing now that this has been resolved, thanks all!
