### ISSUE TITLE
webpackConfig for @nrwl/web:dev-server

### ISSUE THREAD

**Issue by paramsinghvc** [nrwl/nx#4446]
## Description

While `@nrwl/web:build` allows you to extend webpack configuration using the `webpackConfig` flag. I'm surprised to understand that it's not allowed in `@nrwl/web:dev-server`. 

## Motivation

I have been using docker configuration in my project that I'm trying to migrate to Nx but since extending the webpackConfig is not allowed in `@nrwl/dev-server`, I can't add custom dev server parameters like 

```
disableHostCheck: true,
historyApiFallback: true,
```

etc. The webpackConfig customisation muist be allowed be allowed in order to support it. Or in general too, it must be allowed to customise things whenever needed.

## Suggested Implementation

There should be webpackConfig option available for @nrwl/web:dev-server just like @nrwl/web:build

```
"serve": {
    "executor": "@nrwl/web:dev-server",
    "options": {
    "webpackConfig": "<path>"
    }
}
```

**Comment by samratshaw** [comment]
@paramsinghvc As a workaround, you can create another configuration for your build & use that for serve.
`"buildTarget": "admin-panel:build:{customConfig}"`

**Comment by fguitton** [comment]
This is still of interest for ongoing projects

**Comment by fguitton** [comment]
This is still of interest 💯 !

**Comment by MatheusBNAguiar** [comment]
@paramsinghvc Here at the company that I work on there is two configs, one for the build and other for serving pointing to the build
![image](https://user-images.githubusercontent.com/3422084/165361465-4a66b957-93a1-4c04-aabd-d6b1b63cdbd1.png)
![image](https://user-images.githubusercontent.com/3422084/165361506-7b77fef9-9e3e-408f-8e52-af5b9cbf0451.png)

**Comment by AgentEnder** [comment]
I'm going to close this out, the dev-server itself isn't responsible for building the project so it wouldn't make sense for it to handle webpack configs. Instead, the build target which is invoked by the dev-server handles them. Using configurations like mentioned above is the proper way to handle this.

**Comment by realappie** [comment]
Thanks @AgentEnder, your last comment helped me come up with the following solution.

```typescript
// https://nx.dev/recipes/other/customize-webpack#customizing-webpack-config
const getWebpackConfig = require('@nrwl/react/plugins/webpack');

module.exports = async (config, context) => {
  // The standard config that nrwl/react/plugins/webpack returns
  const standardConfig = getWebpackConfig(config);

  if ( context.configuration === 'development' ) {
    // Some form of config override, you can use webpack-merge or something else here
    standardConfig.devServer.server = {
      type: 'https',
      options: {
        key: 'test',
        cert: 'test'
      }
    }
  }

  return standardConfig;
};

```

Hope this helps someone!
