### ISSUE TITLE
Allow for multiple artifacts to be created via @nrwl/node:build

### ISSUE THREAD

**Issue by christianallred** [nrwl/nx#4448]
## Description
I have a request where i would like to be able to generate multiple output files into the dist folder when creating a nrwl app. 

## Motivation
My motivation for this is so that i can create threaded tasks using node Thread, which requires a reference to a js file to run. This is also doable with the thread.js npm library. There are other solutions to this problem but most require more overhead as it asks to spin up the entire main file in the new thread. 

## Suggested Implementation
add an `additionalEntires` to the `BuildBuilderOptions` or `BuildNodeBuilderOptions`

Then inside of 'utils/config' make the following changes. 

```
 const OUT_FILENAME_TEMPLATE = '[name].js'
 ......
 entry: {
      main: [options.main],
      ...options.additionalEntries
 },
 .....
 output: {
      path: options.outputPath,
      filename: options.additionalEntries ? OUT_FILENAME_TEMPLATE : OUT_FILENAME,
 },
```

this would allow you to add addtional entry points by simply adding something like below to your workspace folder
```
"additionalEntries": {
  "worker": "/REPO/apps/test/src/worker/worker.ts"
}
```

## Alternate Implementations
I'm not sure how else i would do this. the above is super straight forward

I can create a PR for this if it is a valid request.

**Comment by Cammisuli** [comment]
Awesome! Thanks for your PR! 

I'll take a look as soon as I can.
