### ISSUE TITLE
forcing ng update results in unknown error

### ISSUE THREAD

**Issue by markgoho** [nrwl/nx#4449]
My typical behavior is to use `ng update` wherever possible. Great that Nrwl has upgraded that functionality and I see the benefits, however we're losing some functionality. Specifically, being able to update other project dependencies in the ecosystem that are known to have their own upgrade schematics (ngrx, rxjs, etc.).

## Current Behavior
`npx ng update @ngrx/store` results in long message with instructions on how to use `ng update` if that's what the user wants.

## Expected Behavior
`FORCE_NG_UPDATE=true npx ng update @ngrx/store` should allow me to update the ngrx package. Heck, I'd expect `nx migrate latest` to have done this as well, but this issue isn't about that functionality.

## Steps to Reproduce
Run the recommended command.

### Failure Logs
``` bash
>  NX   ERROR  "ng update" is deprecated in favor of "nx migrate". Read more: https://nx.dev/latest/angular/workspace/update


>  NX   ERROR  "ng update" is deprecated in favor of "nx migrate". Read more: https://nx.dev/latest/angular/workspace/update

Unknown error: Error
```

### Environment
``` bash
 Node : 12.18.3
  OS   : win32 x64
  npm  : 6.14.8

  nx : Not Found
  @nrwl/angular : 11.0.20
  @nrwl/cli : 11.0.20
  @nrwl/cypress : 11.0.20
  @nrwl/devkit : 11.0.20
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.20
  @nrwl/linter : 11.0.20
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.20
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.20
  typescript : 4.0.5
```

**Comment by vsavkin** [comment]
@markgoho I'm not able to repro it. Could you provide a repo I can run the update command in?

**Comment by markgoho** [comment]
Sorry @vsavkin -- I'm now unable to reproduce based on:
`>  NX   ERROR  Decoration of the Angular CLI did not complete successfully`

Here's the repo: https://github.com/ideacrew/active-branch-tracker

**Comment by markgoho** [comment]
Interesting, without Nx decoration in place, I get the following error when running the `npx ng update` command:
``` bash
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
An unhandled exception occurred: npm ERR! code ETARGET
npm ERR! notarget No matching version found for @schematics/angular@11.0.6.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@angular/cli'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mark\AppData\Roaming\npm-cache\_logs\2021-01-06T21_40_10_689Z-debug.log
Package install failed, see above.
See "C:\Users\Mark\AppData\Local\Temp\ng-7gZz31\angular-errors.log" for further details.
```

**Comment by markgoho** [comment]
@vsavkin I'm sorry for the trouble here, I'm unable to reproduce it after removing node modules and starting from scratch. Hopefully this closed issue will benefit someone in the future.
