### ISSUE TITLE
Symlink from the Angular CLI

### ISSUE THREAD

**Issue by ahsanplusplus** [nrwl/nx#4452]
I did update an Angular project from @nrwl/workspace@8.12.11 to @nrwl/workspace@9.7.1 and as part of the update, a decorate-angular-cli.js file was generated.

**Comment by markgoho** [comment]
@ahsanplusplus that file enables your nx workspace to run normal ng commands in an optimized way. If you don't want this increased performance, there are instructions for how to "opt out" in that file:
> To opt out of this patch:
>  - Replace occurrences of nx with ng in your package.json
>  - Remove the script from your postinstall script in your package.json
>  - Delete and reinstall your node_modules

I've found this optimization to be an improvement on the developer experience of using the angular cli, so you might want to see how it goes for a few days and then make a decision.

**Comment by vsavkin** [comment]
Nx wraps the Angular CLI functionality so everything will work the same way except faster (because Nx adds computation caching). As @markgoho pointed out you can opt out but I don't recommend it.

I'm going to close this issue.

**Comment by demisx** [comment]
I am getting this error in `v11.1.5`. Any idea what may be wrong?

```
npm WARN lifecycle ws@0.0.0~postinstall: cannot run in wd ws@0.0.0 node ./decorate-angular-cli.js (wd=/usr/src)
```
