### ISSUE TITLE
Nx Cache Inputs should include NX_* env vars and some others

### ISSUE THREAD

**Issue by mikecann** [nrwl/nx#4455]
I brought this up on slack and it was suggested that I make an issue for it so here goes.

## Description

I just ran into a bit of a gotcha.. It appears that Nx caching does NOT take into account environment variables when building web projects.

So for example say I have `NX_MY_VAR=foo nx build myap`  then it will build and cache, then if I do `NX_MY_VAR=bar nx build 
myap`  it wont re-build and instead will use the cache.. 

this is a bit of a gotcha IMO seeings as the docs say:

> which works against the current state of the codebase and the environment,
https://nx.dev/latest/react/core-concepts/computation-caching

I would expect standard environment variables such as those documented here would automatically be part of the computation cache hash: https://nx.dev/latest/react/guides/environment-variables (edited) 

## Motivation

Because caching is hard and it can lead to some nasty issues that are hard to track down.

## Suggested Implementation

1. Environment variables prefixed with `NX_` should automatically be included as Nx Cache inputs
2. Some other choice environment variables such as `NODE_ENV` and others that NX includes while building (https://nx.dev/latest/react/guides/environment-variables#how-to-use) 
3. Docs should be improved to let users know about this.

**Comment by bekos** [comment]
maybe we can have an array like `cacheableVariables` in nx.json to make it more generic 🤔

**Comment by yharaskrik** [comment]
@bekos I like that idea, @vsavkin what way would Nrwl like to take this? I'd be more than happy to attempt to tackle this, just not sure if Nrwl will want to go with the automatically caching `NX_*` or if something more generoic like @bekos suggested would be better to go with?

**Comment by bekos** [comment]
btw this can be achieved already by using something like `"runtimeCacheInputs": ["echo $NX_MY_VAR" ]`, but the problem in this case, is that the command itself works only for linux vs windows 🤔

**Comment by mikecann** [comment]
Actually the more I think about this the more I think this is the wrong solution. 

I have been reading about Immutable Web Apps (https://immutablewebapps.org/) and they advocate runtime variables being sepparate from the build process.

So IMO environment variables should not be supplied at build time and instead should be supplied AFTER build either injected into index.html or supplied as a sepparate file that can be loaded at runtime. 

The problem is the way the Nx Cloud Caching works, it doesnt allow you to run anything AFTER a build has been run so the env vars cant be injected. I think thats the real problem / solution here.

**Comment by AgentEnder** [comment]
@mikecann something you could think about for the environment variables in index.html could be a custom target called "postbuild" or "inject-environment-variables" or something like that combined with a schematic to update index.html with the current environment variables. Then you could do `nx affected build` followed by `nx affected inject-environment-variables`

**Comment by mikecann** [comment]
@AgentEnder the post-build inject step is pretty much what I have done:

```
 - name: Build Web
        run: |
          yarn nx build web --prod
          yarn nx script web --name=injectEnv
        env:
          ...
```

Which then does:

```
import * as fs from "fs";

async function bootstrap() {
  const cwd = process.cwd();

  const env = {
    NODE_ENV: process.env.NODE_ENV,
  };

  for (let key in process.env) {
    if (!key.startsWith("BT_")) continue;
    env[key] = process.env[key];
  }

  const envPath = `./apps/web/dist/env.json`;

  fs.writeFileSync(envPath, JSON.stringify(env, null, 2));
}

bootstrap()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
```

Which seems to work tho I do wonder if this should be something that NX should support out of the box. 

If not no worries we can close this issue.

**Comment by thor84no** [comment]
> btw this can be achieved already by using something like `"runtimeCacheInputs": ["echo $NX_MY_VAR" ]`. You can even call your own script with node. Can you try it and see if that solves your case?

This is all well and good for normal environment variables, but nx doesn't run `runtimeCacheInputs` doesn't include all environment variables it uses for itself. E.g. `nx-cloud.env`.
