### ISSUE TITLE
ESLint: "Imports of lazy-loaded libraries are forbidden" error when dynamically importing a standalone file from a lib

### ISSUE THREAD

**Issue by ericbiewener** [nrwl/nx#4463]
## Current Behavior

Unexpected eslint error:

> Imports of lazy-loaded libraries are forbidden (eslint@nrwl/nx/enforce-module-boundaries)

## Expected Behavior

I'd expect Nx to know that one path can be imported in the standard way, while the other can be imported via `import()~

## Steps to Reproduce

```
index.ts -> simply re-exports `use-captcha.ts`
lib/
  use-captcha.ts -> does not import `captcha.tsx`
  captcha.tsx
```

In my `tsconfig.json` file, I define a couple different paths:

```json
"~/captcha": ["./libs/captcha/src/index.ts"],
"~/captcha/lazy": ["./libs/captcha/src/lib/captcha.tsx"],
```

One path gets imported via a normal `import` statement, while the other uses `import()`:

```tsx
import dynamic from "next/dynamic";
import { CaptchaService } from "~/captcha";

const Captcha = dynamic(() => import("~/captcha/lazy"), {
  ssr: false,
});
```

This results in an error on the standard `import` line:

> Imports of lazy-loaded libraries are forbidden (eslint@nrwl/nx/enforce-module-boundaries)

### Environment

```
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.4.4
  @nrwl/cypress : 10.4.4
  @nrwl/eslint-plugin-nx : 10.4.4
  @nrwl/express : Not Found
  @nrwl/jest : 10.4.4
  @nrwl/linter : 10.4.4
  @nrwl/nest : Not Found
  @nrwl/next : 10.4.4
  @nrwl/node : 10.4.4
  @nrwl/react : 10.4.4
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.4.4
  @nrwl/web : 10.4.4
  @nrwl/workspace : 10.4.4
  typescript : 4.1.2
```

**Comment by JamesHenry** [comment]
Hi @ericbiewener, in an Nx workspace the primary relationships are between _projects_ (i.e. apps and libs), not files and projects. Projects naturally contain files, and they have their part to play in determining whether or not the project "owns" them is affected by code changes, but the kind of nuanced inter-project behaviour within a workspace you are describing is not the intended usage.

A dependency graph is built and maintained by Nx behind the scenes for your workspace (you can actually check this out on disk in your workspace's node_modules at `node_modules/.cache/nx/nxdeps.json` and this dependency graph is the source of truth for many things, including the lint rule.

Currently the way you have structured your code, you are informing Nx that there is a _dynamic_ (in other words lazy loaded) relationship between your Next.js app (let's call it "foo") and the captcha project/lib.

Therefore for your app "foo", the relationship "nodes" of the dependency graph might look something like this:

```jsonc
"foo": [
      {
        "type": "static",
        "source": "foo",
        "target": "npm:@nrwl/next"
      },
      {
        "type": "static",
        "source": "foo",
        "target": "npm:react"
      },
      {
        "type": "static",
        "source": "foo",
        "target": "npm:next"
      },
      // ------------------------ foo -> captcha has a type of dynamic
      {
        "type": "dynamic",
        "source": "foo",
        "target": "captcha"
      },
      // ------------------------
      {
        "type": "static",
        "source": "foo",
        "target": "npm:@testing-library/react"
      }
    ],
```

Therefore when you _statically_ import from the captcha project, you correctly get the linting error that you are mixing static and dynamic concerns.

I would recommend you refactor to separate your dynamic and static concerns into separate projects/libs. Not only will you not run into the linting issue, but I would argue that your workspace will become easier to reason about over time.

You can of course still group them under a captcha "namespace" using a simple folder structure, e.g.

```
libs/
  captcha/ <-------- just a directory
    lazy/ <------- lib 1
      src/
      index.ts
    static/ <------- lib 2
      src/
      index.ts
```

Hope that helps!

**Comment by ericbiewener** [comment]
Thanks for the thorough explanation @JamesHenry, this makes sense.
