### ISSUE TITLE
Generic Storybook module

### ISSUE THREAD

**Issue by DominikPieper** [nrwl/nx#4466]
## Description
A generic Storybook config for non React/Angular projects would be nice.

## Motivation
For web components or custom Nx plugins which wan't to add storybook support it would be great to be able to add a simple framework config as a starting point

## Suggested Implementation
Shouldn't be hard to add, just a additional parameter to add @storybook/html

**Comment by kishok** [comment]
hi @vsavkin, **@nrwl/storybook:configuration**  not working for the "uiFramework":"@storybook/html" value in v11.1.5. So not able to add storybook to my web component. please add that value to uiFramework schema enum.
