### ISSUE TITLE
Dependency graph doesn't load with CSP that blocks inline scripts

### ISSUE THREAD

**Issue by sorin-davidoi** [nrwl/nx#4468]
## Current Behavior

When generating a static dependency graph with `nx dep-graph --file=output/index.html`, `index.html` contains the project data as inline scripts (see [this](https://github.com/nrwl/nx/blob/fabb6ba65ee1b5ba8407fbe64686acdcf1cfa8c6/apps/dep-graph-client/src/index.html#L55:L61) and [this](https://github.com/nrwl/nx/blob/fabb6ba65ee1b5ba8407fbe64686acdcf1cfa8c6/packages/workspace/src/command-line/dep-graph.ts#L45-L72)). If one wants to deploy this page with a Content Security Policy that prohibits inline scripts, the application fails to load.

## Expected Behavior

The application should work when deployed with a Content Security Policy that blocks inline scripts.

## Steps to Reproduce

```bash
git clone https://github.com/nrwl/nx-examples
cd nx-examples
npm install

npm run dep-graph -- --file=output/index.html

cat << EOF >> serve.json
{
    "public": "output",
    "headers": [{
        "source": "*",
        "headers": [{
            "key": "Content-Security-Policy",
            "value": "script-src 'self'"
        }]
    }]
}

EOF

npx serve@11.3.2
```

### Failure Logs

```
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src").
...
Uncaught TypeError: can't access property "filter", window.affected is undefined
```

### Proposal

Write the project data to a separate script which is loaded from `index.html`.

### Environment

Node : 14.15.4
OS   : darwin x64
yarn : 1.22.10

nx : Not Found
@nrwl/angular : 11.0.1-rc.0
@nrwl/cli : 11.0.1-rc.0
@nrwl/cypress : 11.0.1-rc.0
@nrwl/devkit : 11.0.1-rc.0
@nrwl/eslint-plugin-nx : Not Found
@nrwl/express : Not Found
@nrwl/jest : 11.0.1-rc.0
@nrwl/linter : 11.0.1-rc.0
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/react : 11.0.1-rc.0
@nrwl/schematics : Not Found
@nrwl/tao : 11.0.1-rc.0
@nrwl/web : 11.0.1-rc.0
@nrwl/workspace : 11.0.1-rc.0
typescript : 4.0.3

**Comment by vsavkin** [comment]
Thanks for submitting the issue!

@philipjfulcher not sure if we should treat it as a bug or as a feature.

**Comment by sorin-davidoi** [comment]
Would you accept a patch that moves the data to a separate script?

**Comment by philipjfulcher** [comment]
@sorin-davidoi Sure, assign me when you raise the PR and I'll take a look. :)

**Comment by SamuelWitke** [comment]
Any chance this issue could be opened again?

**Comment by philipjfulcher** [comment]
This issue will be resolved when the merged PR makes it to a release. Look for it soon!
