### ISSUE TITLE
 Failures for test and lint runs in CI with shared cache

### ISSUE THREAD

**Issue by minijus** [nrwl/nx#4470]
## Current Behavior
Using Jenkins as CI engine.
Using shared Nx cache directory (`/home/node/cache/nx`) in CI:
```bash
sed -i 's|./cache/nx|/home/node/cache/nx|' nx.json
```

With this setup running test and lint in distributed setup (very similar to one provided in [Nrwl example](https://github.com/nrwl/nx-jenkins-build)):
```bash
# lint
npx nx run-many --target=lint --projects=redacted-40-projects-here --parallel

# test
npx nx run-many --target=test --projects=redacted-40-projects-here --parallel
```

Getting same errors on seemingly random projects. Failed projects change when re-running same CI jobs, but never fail when running without shared cache and never fail locally (with or without ~~you~~ cache).

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJsonWithComments (/home/jenkins/agent/workspace/redacted/node_modules/@nrwl/workspace/src/utils/fileutils.js:44:17)
    at Object.readJsonFile (/home/jenkins/agent/workspace/redacted/node_modules/@nrwl/workspace/src/utils/fileutils.js:40:12)
    at Object.readCache (/home/jenkins/agent/workspace/redacted/node_modules/@nrwl/workspace/src/core/nx-deps/nx-deps-cache.js:36:67)
    at Object.createProjectGraph (/home/jenkins/agent/workspace/redacted/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:13:232)
    at Object.<anonymous> (/home/jenkins/agent/workspace/redacted/node_modules/@nrwl/workspace/src/command-line/run-many.js:17:46)
    at Generator.next (<anonymous>)
    at fulfilled (/home/jenkins/agent/workspace/redacted/node_modules/tslib/tslib.js:111:62)
```

```
> nx run redacted:lint 

Linting "redacted"...
Error while loading rule '@nrwl/nx/enforce-module-boundaries': Unexpected end of JSON input
Occurred while linting /home/jenkins/agent/workspace/redacted/libs/redacted/src/index.ts
```

## Expected Behavior
It should be possible to set shared cache in CI environment without getting jobs failed.

## Steps to Reproduce
It might be difficult to recreate whole environment so the issue would be reproducible as it is not clear what causes it.
Please share any ideas what could be attempted to narrow down the root cause of this and I will give them a try.

### Failure Logs
See under "Current Behaviour".

### Environment
The report is from local development environment, but it is same Node.js version as on CI:
```
>  NX  Report complete - copy this into the issue template

  Node : 14.15.4
  OS   : darwin x64
  npm  : 6.14.11
  
  nx : Not Found
  @nrwl/angular : 11.1.1
  @nrwl/cli : 11.1.1
  @nrwl/cypress : 11.1.1
  @nrwl/devkit : 11.1.1
  @nrwl/eslint-plugin-nx : 11.1.1
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.1
  @nrwl/linter : 11.1.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.1
  typescript : 4.0.3
```

**Comment by minijus** [comment]
The error message itself is identical to one mentioned in #3735.
However, after verifying `json` files no issues with formatting were noticed - besides prettier format check passes as well. Also, it never fails locally, even when running exactly same `nx run-many" commands.

**Comment by Squixx** [comment]
I'm having this awel.

Can be test / lint / builds that fail, only with run many.

And a rerun often fixes it..

**Comment by minijus** [comment]
@Squixx does this happen on CI (Jenkins) as well? Is it container/pod that you run the `nx` in? Is it mounted volume for cache or a static directory within same file system?

**Comment by minijus** [comment]
The common denominator seems to be mounted volume for cache.
In my case on-prem read-write-many volume might have it's limitation, but @Squixx case I'd expect Azure CI with mounted volume to run flawlessly.

@vsavkin do you have any ideas what could be tried in order to alleviate the issue or at least to get more details on it?

**Comment by Squixx** [comment]
Well tbh, since hosted azure CI doesn't provide a way to mount volumes on multiple agents.  (we split our runs over 12 agents). Our storage account implementation also might have its limitations. _but_ It works most of the time, and on our side a rerun of one job always solves the problem, and the problem also only occurs for the entire task. So run many seems to fully crash on a missing / corrupt / slow file.

I'd say it could be a timeout / rate limit / something other network issue that doesn't fail gracefully or retry. But in the long run we probably cant get around this. I would expect run many to either retry, or just assume there is no cached value and proceed without cache in the case of invalid / unreadable / cache not loading for whatever reason.

**Comment by Squixx** [comment]
Ok so upon further research, with a smaller cache folder, the issue seems to present itself less often. But is still around :(

**Comment by minijus** [comment]
`readJsonFile`could be wrapped to try/catch for `readCache`: https://github.com/nrwl/nx/blob/2c7fa421eba594acf029fa44c0e19b093b9c01cb/packages/workspace/src/core/nx-deps/nx-deps-cache.ts#L58

This should solve issue with test target runs, but lint runs seems to fail in other way.

**Comment by Squixx** [comment]
Would be nice to have a couple of retries on that as well

**Comment by vsavkin** [comment]
This is fixed here: https://github.com/nrwl/nx/commit/d55d6f88e58dfa9599806b8b3efb0a7df6301101.

We are going to cut a release with the fix (both 10x and 11x releases) next week.

Closing this one. 

Thank you!

**Comment by Squixx** [comment]
What @minijus said, this will not fix the issue for linting yet
