### ISSUE TITLE
11.1.1: @nrwl/workspace:run-commands - forwarding args does not seem to work anymore

### ISSUE THREAD

**Issue by NathanWalker** [nrwl/nx#4475]
## Current Behavior

I believe forwarding args is the default when using `command` options as this did used to work in Nx 10. Curious if something changed around this with v11?

Given the following options for the given target:

```
"targets": {
  "ios": {
    "executor": "@nrwl/workspace:run-commands",
    "options": {
      "command": "ns debug ios --no-hmr --env.projectName=nativescript-mobile",
      "cwd": "apps/nativescript-mobile"
    }
  }
```

Running like this: `nx run nativescript-mobile:ios --env.configuration=prod` does *not* forward the extra argument.

This however does work: `nx run nativescript-mobile:ios --args="--env.configuration=prod"` However it is not preferred as is quite verbose and cumbersome to remember.

I have also tried this setup:

```
"targets": {
  "ios": {
    "executor": "@nrwl/workspace:run-commands",
    "options": {
      "commands": [
          {
            "command": "ns debug ios --no-hmr --env.projectName=nativescript-mobile",
            "forwardAllArgs": true
          }
        ],
        "cwd": "apps/nativescript-mobile"
     }
  }
```

Running like this: `nx run nativescript-mobile:ios --env.configuration=prod` also does *not* forward the extra argument.

This however does work: `nx run nativescript-mobile:ios --args="--env.configuration=prod"`

## Expected Behavior

The `--env.configuration=prod` arg to be forwarded.

### Environment

```
Node : 12.13.0
  OS   : darwin x64
  npm  : 6.12.0
  
  nx : Not Found
  @nrwl/angular : 11.1.1
  @nrwl/cli : 11.1.1
  @nrwl/cypress : 11.1.1
  @nrwl/devkit : 11.1.1
  @nrwl/eslint-plugin-nx : 11.1.1
  @nrwl/express : 11.0.2
  @nrwl/jest : 11.1.1
  @nrwl/linter : 11.1.1
  @nrwl/nest : 11.0.2
  @nrwl/next : Not Found
  @nrwl/node : 11.0.2
  @nrwl/react : 11.0.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.1
  @nrwl/web : 11.1.1
  @nrwl/workspace : 11.1.1
  typescript : 4.0.5
```

**Comment by vsavkin** [comment]
Unfortunately, I'm not able to repro it. 

This is what I have:

```
"echo": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "commands": [
              {
                "command": "echo $1 $2",
                "forwardAllArgs": true
              }
            ]
          }
        },
```

If I run `nx run someapp:echo --a=123 --b=242` I see both params forwarded. If I change forwardAllArgs to false, they are no longer forwarded.

Could you provide a repo with a repro?

**Comment by NathanWalker** [comment]
Thank you @vsavkin I'll try to create a simpler repro and experiment some more with variations to see if can pinpoint more details here. Only thing been able to tell so far is what worked as described above on v10 no longer works same in v11.

**Comment by vsavkin** [comment]
@NathanWalker let me know if you need any help with this. I'm happy to jump on a quick call and sort it out.

**Comment by NathanWalker** [comment]
Thanks @vsavkin I'm almost always 100% sure it's something I'm doing non-standard heh. It sort of comes back to the long standing to-do to just create a custom builder here anyway. I'm going to focus on doing that as one is needed in this area related to this so I'll close this and introduce an official Nx plugin (for the case mentioned) along these lines hopefully in coming weeks - a start to it has been created but have few remaining things to polish out before making official.
