### ISSUE TITLE
"nx migrate latest" is not marking cypress for update 

### ISSUE THREAD

**Issue by skopekreep** [nrwl/nx#4480]
## Current Behavior
After reading the release notes for 11.1.1, I noticed that cypress had been bumped to 6.0.1.  My package.json still showed  ```"cypress": "^4.11.0",```, despite just running ```nx migrate latest```.  This behavior may have been happening since nx 9, since all my updates have been done using the ```nx migrate``` command.  Unsure if this is a regression, since I started using nx late in version 9, so the cypress version in my package.json may be from the initial workspace setup.

## Expected Behavior
Running ```nx migrate latest``` should suggest ```cypress``` package updates when appropriate.

## Steps to Reproduce
npx create-nx-workspace@9.0.0 example-workspace
 - choose angular, SCSS options
 - package.json shows ```"cypress": "^3.8.2"```

Run ```nx migrate latest```
- package.json STILL shows ```"cypress": "^3.8.2"```

### Environment (after installing recommended updated)
  Node : 12.14.0
  OS   : darwin x64
  npm  : 6.14.11
  
  nx : Not Found
  @nrwl/angular : 11.1.1
  @nrwl/cli : 11.1.1
  @nrwl/cypress : 11.1.1
  @nrwl/devkit : 11.1.1
  @nrwl/eslint-plugin-nx : 11.1.1
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.1
  @nrwl/linter : 11.1.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.1
  typescript : 4.0.5

**Comment by mehrad-rafigh** [comment]
@skopekreep There are no migrations to update Cypress to v6, because there are a [ton of changes](https://docs.cypress.io/guides/references/migration-guide.html#Migrating-to-Cypress-6-0) which nx cannot migrate. Therefore you should it by yourself.

[This is the PR for v6 update](https://github.com/nrwl/nx/pull/4175)

Still the migration could should a hint, that cypress should be updated by the users themselves. What do you think @vsavkin?

**Comment by skopekreep** [comment]
Makes sense.  Since this will likely happen with other packages as well, your idea to notify users of any updates that have to be done manually would fit well with the current nx trend toward understandable CLI output.  Similar to the peer dependency manual update notifications generated by npm.
