### ISSUE TITLE
Support Blitz.js

### ISSUE THREAD

**Issue by cyrus-za** [nrwl/nx#4482]
## Description

[Blitz.js](https://blitzjs.com) is a framework on top of [next.js](https://nextjs.org) with the latter already officially supported by nx. 

It would be great if blitz itself could also be supported with generators.

## Motivation

There's a huge growing community due to the simplicity of Blitz being full stack without the need of an http api. They call it the ruby on rails of javascript.

## Suggested Implementation

Similar way next.js plugin works.

**Comment by andreasasprou** [comment]
Can anyone provide any insight into the strange things that are happening here?

https://www.loom.com/share/4d22ea7376c042558aa12c71056e6676

**Comment by cyrus-za** [comment]
Thanks for the loom video @andreasasprou and well done on pronouncing my name right :)

Do you think you can open a PR for blitz team to make those changes in node_modules permenant or configurable? I'll ping flybayer to check the issue out.

**Comment by drewhoffer** [comment]
Any news on this?
