### ISSUE TITLE
Add --unitTestRunner=karma option for @nrwl/web:library schematic

### ISSUE THREAD

**Issue by SerkanSipahi** [nrwl/nx#4486]
## Description
Currently, building a library with @nrwl/web does not have support  for `--unitTestRunner=karma` (like @nrwl/angular)

## Motivation
Adding Karma  will run the test suite with the engine of the browser.

## Suggested Implementation
Reuse (or copy) similar task of @nrwl/angular `--unitTestRunner=karma` option.

## Note
Maybe this feature could be implemented with https://github.com/nrwl/nx/issues/3606

**Comment by mehrad-rafigh** [comment]
I can try tackling this. @vsavkin I would suggest creating a new package called @nrwl/karma and move common configuration inside that project. What do you think?

**Comment by SerkanSipahi** [comment]
Please consider in `@nrwl/karma` the publishable option, see also for that #4488

**Comment by florianehmke** [comment]
Can we reopen this issue?
