### ISSUE TITLE
nx-plugin/devkit: when using PNPM, runPackageManagerInstall and installPackagesTask do not work in Nx plugin e2e tests on GitHub CI

### ISSUE THREAD

**Issue by LayZeeDK** [nrwl/nx#4495]
The Nx 12 roadmap (https://github.com/nrwl/nx/issues/4492) mentions additional efforts to *test PNPM-based repos*. This seems to be one of those issues worth looking into. Either that, or I'm doing something wrong.

## Current Behavior

When using PNPM as the workspace package manager, the following occurs in GitHub CI workflows:
1. When calling `runPackageManagerInstall` from `@nrwl/nx-plugin/testing` in an end-to-end test, `spawnSync` fails with `spawnSync /bin/sh ENOENT`.
1. When calling `installPackagesTask` from `@nrwl/devkit` in a generator, end-to-end tests fails with `Command failed: pnpm install`.

End-to-end tests work locally.

## Expected Behavior

When using PNPM as the workspace package manager, the following should occurs in GitHub CI workflows:
1. Calling `runPackageManagerInstall` from `@nrwl/nx-plugin/testing` in an end-to-end test should succeed.
1. Calling `installPackagesTask` from `@nrwl/devkit` in a generator, end-to-end tests should succeed.

## Steps to Reproduce

Minimal reproduction in workspace generated using `create-nx-plugin`: [LayZeeDK/nx-plugin-issue-pnpm-install](https://github.com/LayZeeDK/nx-plugin-issue-pnpm-install).

### Failure Logs

[Sample GitHub CI run](https://github.com/LayZeeDK/nx-plugin-issue-pnpm-install/runs/1678162479?check_suite_focus=true).

`runPackageManagerInstall` error in end-to-end test:
```bash
  console.error
    Error: spawnSync /bin/sh ENOENT
        at Object.spawnSync (internal/child_process.js:1042:20)
        at spawnSync (child_process.js:621:24)
        at Object.execSync (child_process.js:666:15)
        at Object.runPackageManagerInstall (/home/runner/work/nx-plugin-issue-pnpm-install/nx-plugin-issue-pnpm-install/node_modules/.pnpm/@nrwl/nx-plugin@11.1.1_typescript@4.0.5/packages/nx-plugin/src/utils/testing-utils/nx-project.ts:50:19)
        at Object.<anonymous> (/home/runner/work/nx-plugin-issue-pnpm-install/nx-plugin-issue-pnpm-install/e2e/pnpm-install-e2e/tests/pnpm-install.spec.ts:15:27)
        at /home/runner/work/nx-plugin-issue-pnpm-install/nx-plugin-issue-pnpm-install/node_modules/.pnpm/jest-jasmine2@26.6.3_ts-node@9.1.1/node_modules/jest-jasmine2/build/queueRunner.js:45:12
        at new Promise (<anonymous>)
        at mapper (/home/runner/work/nx-plugin-issue-pnpm-install/nx-plugin-issue-pnpm-install/node_modules/.pnpm/jest-jasmine2@26.6.3_ts-node@9.1.1/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
        at /home/runner/work/nx-plugin-issue-pnpm-install/nx-plugin-issue-pnpm-install/node_modules/.pnpm/jest-jasmine2@26.6.3_ts-node@9.1.1/node_modules/jest-jasmine2/build/queueRunner.js:75:41 {
      errno: 'ENOENT',
      code: 'ENOENT',
      syscall: 'spawnSync /bin/sh',
      path: '/bin/sh',
      spawnargs: [ '-c', 'pnpm install' ],
      error: [Circular],
      status: null,
      signal: null,
      output: null,
      pid: 2002,
      stdout: null,
      stderr: null
    }
```

`installPackagesTask` error in end-to-end test:
```bash
  ● pnpm-install e2e › should create pnpm-install

    Command failed: pnpx nx generate @nx-plugin/pnpm-install:pnpm-install pnpm-install4931585
    Command failed: pnpm install
```

### Environment

GitHub CI report:
```bash
>  NX  Report complete - copy this into the issue template

  Node : 12.20.0
  OS   : linux x64
  pnpm : 5.15.0
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.1.1
  @nrwl/cypress : Not Found
  @nrwl/devkit : 11.0.20
  @nrwl/eslint-plugin-nx : 11.1.1
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.1
  @nrwl/linter : 11.1.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.1.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.1
  typescript : 4.0.5
```

Local report:
```bash
>  NX  Report complete - copy this into the issue template

  Node : 12.20.1
  OS   : win32 x64
  pnpm : 5.15.0

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.1.1
  @nrwl/cypress : Not Found
  @nrwl/devkit : 11.0.20
  @nrwl/eslint-plugin-nx : 11.1.1
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.1
  @nrwl/linter : 11.1.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.1.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.1
  typescript : 4.0.5
```

**Comment by LayZeeDK** [comment]
There seems to be an issue with Yarn + GitHub CI as well in that `workspace.json` in the generated `nx-e2e` directory does not have `{ "cli": { "packageManager": "yarn" } }` configured. After configuring it in a `beforeEach` step, Yarn works:
- https://github.com/LayZeeDK/nx-plugin-issue-pnpm-install/blob/7b9be270e70cc5e8aa9acfe819a8da285434586f/e2e/pnpm-install-e2e/tests/pnpm-install.spec.ts#L12-L26
- https://github.com/LayZeeDK/nx-plugin-issue-pnpm-install/runs/1678334715?check_suite_focus=true

When I make the same setup with PNPM, the error caused by `runPackageManagerInstall` is resolved, but the error caused by `installPackagesTask` persists:
- https://github.com/LayZeeDK/nx-plugin-issue-pnpm-install/blob/4b14b6ce623efbe7dad8a6019ef218c8059d7e9d/e2e/pnpm-install-e2e/tests/pnpm-install.spec.ts#L12-L26
- https://github.com/LayZeeDK/nx-plugin-issue-pnpm-install/runs/1678329257?check_suite_focus=true

**Comment by bekos** [comment]
@LayZeeDK I was hit by this myself when trying to make E2E tests run using pnpm. It's really weird and hard to debug since I cannot reproduce locally either 😞 It turns out though that it is an issue of `exec` vs `spawn` but still trying to figure it out 🤔

**Comment by LayZeeDK** [comment]
Are you also using GitHub CI, @bekos?

**Comment by bekos** [comment]
@LayZeeDK we use circleci but I have tested and GH actions. It turns out that the problem is that `pnpm` by default uses `--frozen-lockfile` on CIs and this is causing the failure if `package.json` has changed. I will try to send a PR that will fix it in our side.

**Comment by bekos** [comment]
@ZachJW34 fyi, as a workaround you can add
```
beforeEach(() => {
    ensureNxProject('@nx-plugin/pnpm-install', 'dist/packages/pnpm-install');
    updateFile('.npmrc', 'prefer-frozen-lockfile=false'); // <<<<<<<<<<<<<<<<<< this will prevent the CI 
```

**Comment by LayZeeDK** [comment]
Thank you very much, @bekos!

I will try this in my workspaces.

**Comment by LayZeeDK** [comment]
It worked in this branch of my issue repo:
https://github.com/LayZeeDK/nx-plugin-issue-pnpm-install/blob/8941c3b73b4ce9fa0e7ad1c34d25297a5f122ee6/e2e/pnpm-install-e2e/tests/pnpm-install.spec.ts#L14

**Comment by bekos** [comment]
@LayZeeDK can you try to remove the workspace.json "hack"? I don't believe it's needed 🤔 we determine the desired package manager based on lock files instead of that property.

**Comment by LayZeeDK** [comment]
Thanks, you are right, this doesn't seem to be needed.
