### ISSUE TITLE
`nx generate` wrongly renders a single-select instead of a multi-select x-prompt when running a schematics from a Nx Plugin

### ISSUE THREAD

**Issue by tinesoft** [nrwl/nx#4499]
A multi-select prompt is not rendered correctly when running a Schematics contained in a Nx plugin, with `nx generate`.

Here is an excerpt of the concerned option in the `schema.json` of the schematics:

```
...
    "platforms": {
      "description": "Platforms supported by the project",
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "default": ["android", "ios", "linux", "windows", "macos","web"],
      "x-prompt": {
        "message": "Which platforms would you like to use (--template must have been set to 'app' or 'plugin') ?",
        "type": "list",
        "multiselect": "true",
        "items": [
          {
            "value": "android",
            "label": "Android platform"
          },
          {
            "value": "ios",
            "label": "iOS platform"
          },
          {
            "value": "linux",
            "label": "Linux platform"
          },
          {
            "value": "windows",
            "label": "Windows platform"
          },
          {
            "value": "macos",
            "label": "MacOS platform"
          },
          {
            "value": "web",
            "label": "Web platform"
          }
        ]
      }
    },
...
```

## Current Behavior

Adding "multiselect": true to x-prompt render a "Single Select" instead of a "Multi Select".

![image](https://user-images.githubusercontent.com/4053092/104176984-5526a680-5408-11eb-9ccd-a521e38e7a7f.png)

## Expected Behavior

![image](https://user-images.githubusercontent.com/4053092/104179092-9f5d5700-540b-11eb-8e63-ad9efbbe5dc1.png)

> Note: this is the correct output when running the schematics with the `Angular DevKit's schematics cli` instead (_after having changed the `workspace.json`'s `"version"` from `2` to `1`, otherwise you'll get an `"Error: Invalid format version detected - Expected:[ 1 ] Found: [ 2 ]"`)_ .

`$ npx @angular-devkit/schematics-cli @nxrocks/nx-flutter:app flutter-app`

## Steps to Reproduce

1. create an empty (OSS) nx workspace : `npx create-nx-workspace@latest`
2. install my plugin (@nxrocks/nx-flutter): `npm install @nxrocks/nx-flutter --save-dev`
3. generate the application: `nx g @nxrocks/nx-flutter:app flutter-app`

### Failure Logs

Property 'platforms' does not match the schema. 'ios' should be a 'array'.

### Environment

nx --version: 11.0.20

Link to the concerned Schematics: https://github.com/tinesoft/nxrocks/tree/develop/packages/nx-flutter/src/schematics/application

**Comment by FrozenPandaz** [comment]
This issue has been fixed by https://github.com/nrwl/nx/commit/f075b987c2a5ed03105d3091aa512b90b056da85. :tada:
