### ISSUE TITLE
nx-migrate is not running anything

### ISSUE THREAD

**Issue by jasedwards** [nrwl/nx#450]
I just upgraded from 0.7.2 to 1.0.3.  the post install ran nx-migrate but no migrations were run.  I ran it myself and still nothing ran.  there was no message saying no migrations either.  My @nrwl/schematics and @nrwl/nx packages are up to date.  Here is what my .angular-cli.json looks like:
` "project": {
    "name": "clearsight-apps",
    "npmScope": "clearsight-apps",
    "latestMigration": "20180130-angular-devkit-schematics"
  },`

and here is what my cmd window looks like after running the command.  I can see in node_modules there are scripts it should be running but nothing is happening.
![image](https://user-images.githubusercontent.com/5818023/39445214-f380f2f6-4c7f-11e8-8339-6667a5d9c478.png)

**Comment by jasedwards** [comment]
I just realized all of the npm script names were changed sometime between those versions.  I updated my package.json file.  Is npm run update what should be used going forward?

**Comment by FrozenPandaz** [comment]
`nx-migrate` is now deprecated. Please use `yarn update` or `npm run update` or `ng update @nrwl/schematics`.
