### ISSUE TITLE
workspace:move produces malformed jest.config.js files

### ISSUE THREAD

**Issue by gdrbyKo1** [nrwl/nx#4500]
## Current Behavior

The `@nrwl/workspace:move` schematic breaks `jest.config.js` by swallowing the quotes around string literals:
![image](https://user-images.githubusercontent.com/19717183/104202216-ed358780-542a-11eb-800a-79a00e81c151.png)

## Expected Behavior

The quotes should not be removed.
This bug was introduced in cf7f1c89dae5947392ca88ccf572379b9ca84f5a.
This exact problem is trivial to fix simply by adding the quotes in line 60 of `update-jest-config.ts`, but I chose not to submit a PR like that because it's not hard to see that the general approach won't work at all if `jest.config.js` happens to use double quotes for string literals, etc. So perhaps a more robust solution should be employed instead.

## Steps to Reproduce

```sh
yarn create nx-workspace foo --preset=react --appName=bar --style css --nx-cloud=false
cd foo
yarn nx g mv --project=bar baz
```

### Environment

```
Node : 14.15.4
OS   : win32 x64
npm  : 6.14.10

nx : Not Found
@nrwl/angular : Not Found
@nrwl/cli : 11.1.1
@nrwl/cypress : 11.1.1
@nrwl/devkit : 11.1.1
@nrwl/eslint-plugin-nx : 11.1.1
@nrwl/express : Not Found
@nrwl/jest : 11.1.1
@nrwl/linter : 11.1.1
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/react : 11.1.1
@nrwl/schematics : Not Found
@nrwl/tao : 11.1.1
@nrwl/web : 11.1.1
@nrwl/workspace : 11.1.1
typescript : 4.0.5
```

**Comment by mehrad-rafigh** [comment]
I opened a PR and added `formatFiles` to the move schematic. This should suffice, since formatFiles uses prettier.
