### ISSUE TITLE
yarn create nx-workspace but the created workspace uses npm

### ISSUE THREAD

**Issue by ahnpnl** [nrwl/nx#4513]
## Current Behavior

Use `yarn create nx-workspace` and created workspace uses `npm` instead of `yarn`. I'm using `yarn` via `Homebrew`

## Expected Behavior

The created workspace should use `yarn`

## Steps to Reproduce

- Run `yarn create nx-workspace my-workspace`
- Choose `angular`
- Choose `SCSS`
- Choose `ESLint`
- Choose no `nx cloud`

Screenshots

After running `yarn create nx-workspace`

<img width="1028" alt="Screenshot 2021-01-13 at 01 11 55" src="https://user-images.githubusercontent.com/27772165/104389968-f0209d00-553c-11eb-8714-f6c431aee2fe.png">

The generated workspace only contains `package-lock.json` instead of `yarn.lock`

<img width="852" alt="Screenshot 2021-01-13 at 01 13 29" src="https://user-images.githubusercontent.com/27772165/104389977-f4e55100-553c-11eb-8f80-b6197f95fdba.png">

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

**N.A.**

### Environment

```
  Node : 15.5.1
  OS   : darwin x64
  npm  : 7.3.0
  
  nx : Not Found
  @nrwl/angular : 11.1.4
  @nrwl/cli : 11.1.4
  @nrwl/cypress : 11.1.4
  @nrwl/devkit : 11.1.4
  @nrwl/eslint-plugin-nx : 11.1.4
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.4
  @nrwl/linter : 11.1.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.4
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.4
  typescript : 4.0.5
```

**Comment by Frikki** [comment]
Try to specify the package manager on creation.

```shell
yarn create nx-workspace --package-manager=yarn
```

And then configure the workspace manager.

```shell
npx json -I -f workspace.json -e "this.cli.packageManager = 'yarn';
```

**Comment by ahnpnl** [comment]
Thanks `yarn create nx-workspace --package-manager=yarn` works for me. I couldn't find it in the doc about that `--package-manager` arg

**Comment by Neel166** [comment]
> Try to specify the package manager on creation.
> 
> ```shell
> yarn create nx-workspace --package-manager=yarn
> ```
> 
> And then configure the workspace manager.
> 
> ```shell
> npx json -I -f workspace.json -e "this.cli.packageManager = 'yarn';
> ```

This worked for me

**Comment by athongsavath** [comment]
> Try to specify the package manager on creation.
> 
> ```shell
> yarn create nx-workspace --package-manager=yarn
> ```
> 
> And then configure the workspace manager.
> 
> ```shell
> npx json -I -f workspace.json -e "this.cli.packageManager = 'yarn';
> ```

To configure the workspace manager, it should be:
```
npx json -I -f workspace.json -e "this.cli.packageManager = 'yarn'";
```

**Comment by developer239** [comment]
@Frikki Thank you 🙌 Is it documented anywhere?

**Comment by krstns** [comment]
For anyone trying it now for angular projects (or maybe all?), the line which worked for me is:
```npx json -I -f nx.json -e "this.cli.packageManager = 'yarn'";```

**Comment by onis-csadi** [comment]
1. If you're creating a new workspace use `yarn create nx-workspace --package-manager=yarn`  it will generate the nx.json with yarn.

2. If you're workspace is already created with npm you can just update `nx.json` file in your root folder to use yarn.
```
"cli": {
    "packageManager": "yarn"
  }
```
To update `nx.json`  file through the command line use `npx json -I -f nx.json -e "this.cli.packageManager = 'yarn'";` as mentioned by comments above.

Note: If the workspace was created with npm and switched to yarn using the instructions above then the  `package-lock.json` will no longer be needed since yarn creates it's own `yarn.lock file`  with the next build.

Hope this helps!
