### ISSUE TITLE
Could not format /jest.config.js after removing an app

### ISSUE THREAD

**Issue by tujoworker** [nrwl/nx#4517]
## Current Behavior

By removing an app, I get:

`Could not format /jest.config.js because Unexpected token`

This is because the file gets formatted corrupt:

```
      1 | module.exports = {
    > 2 |   projects: ],
        |             ^
      3 | };
      4 | 
```

## Expected Behavior

By removing an app, the app should get removed from the root jest config `projects` field.
But without leaving a corrupt file.

## Steps to Reproduce

1. Run a plain new NX Workspace

`npx create-nx-workspace --preset=react --style=css --appName=test --no-nxCloud --no-interactive`

2. Remove the app again

`nx g remove test --forceRemove`

3. The failure shows up in the CLI and for sure in the config file `/jest.config.js`.

### Environment

  Node : 14.15.4
  OS   : darwin x64
  yarn : 1.22.4
  
  @nrwl/angular : Not Found
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.1.5
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : 11.1.5
  @nrwl/workspace : 11.1.5
  typescript : 4.0.5

**Comment by mehrad-rafigh** [comment]
I will take a look at this tonight

**Comment by EthanSK** [comment]
any updates on this?

**Comment by mehrad-rafigh** [comment]
Currently I am hustiling with Typescript AST. Try to finish the PR by the end of the week

**Comment by tujoworker** [comment]
@mehrad-rafigh Nice! So it will then be an improvement of [this](https://github.com/nrwl/nx/commit/fd93b84) PR/fix I guess?

**Comment by mehrad-rafigh** [comment]
@tujoworker Yes it is

**Comment by tujoworker** [comment]
@mehrad-rafigh Let me know, if you need any help to get this out 🙏

**Comment by bekos** [comment]
@mehrad-rafigh I think this is fixed via https://github.com/nrwl/nx/commit/d18c0b09146a096d6c96507dd097d880ac7ef323, right?

**Comment by mehrad-rafigh** [comment]
@bekos Yes it looks like it

**Comment by bekos** [comment]
thx @mehrad-rafigh 👍 let's close this then, as this will be part of the next release.
