### ISSUE TITLE
@nrwl/next app not importing global CSS/SCSS files in build from _app.tsx

### ISSUE THREAD

**Issue by ultd** [nrwl/nx#4518]
I know you can only import global CSS/SCSS files to `_app.tsx`, this is not that problem. @nrwl/next app's are not importing CSS/SCSS files when serving for development.

## Current Behavior
`@nrwl/next` app's are not importing CSS/SCSS files from `_app.tsx` (global imports such as `import './styles.scss'`) to the build when running `nx serve $APP_NAME`. If you build using `nx build $APP_NAME` and then `nx serve:production $APP_NAME` it successfully builds (for production) and serves it with the CSS/SCSS files imported. I'm not sure why this is happening, did some debugging and cannot find the culprit.

## Expected Behavior
I expect `nx serve $APP_NAME` to build with CSS/SCSS files imported globally in `_app.tsx` to be served properly.

## Steps to Reproduce
Create any `@nrwl/next` app in an nx workspace and import any CSS/SCSS file globally to the `_app.tsx` file and it will not include it when running `nx serve $APP_NAME`. 

### Environment
package.json NX devDependencies:
```json
{
  "@babel/core": "7.9.6",
  "@babel/preset-env": "7.9.6",
  "@babel/preset-react": "7.9.4",
  "@babel/preset-typescript": "7.9.0",
  "@nrwl/cli": "11.1.1",
  "@nrwl/cypress": "11.1.1",
  "@nrwl/eslint-plugin-nx": "11.1.1",
  "@nrwl/express": "11.1.1",
  "@nrwl/jest": "11.1.1",
  "@nrwl/next": "11.1.1",
  "@nrwl/node": "11.1.1",
  "@nrwl/react": "11.1.1",
  "@nrwl/tao": "11.1.1",
  "@nrwl/web": "11.1.1",
  "@nrwl/workspace": "11.1.1",
}
```
Node @v12.20.0

**Comment by ultd** [comment]
Any progress on this? This is really hurting our development flow.

**Comment by bekos** [comment]
@ultd can you please provide a reproduction repo? I probably don't understand something in the steps to reproduce. fyi I created an Nx workspace, chose `Next.js` preset with Sass, and the generated `_app.tsx` already contains `import "./styles.scss"`, which seems to work correctly during local serve.

**Comment by ultd** [comment]
Upon further review, I believe it's a configuration problem on my end. Apologies & thanks for looking into it.
