### ISSUE TITLE
[emotion] css prop is not working

### ISSUE THREAD

**Issue by RafalFilipek** [nrwl/nx#4520]
## Current Behavior

First problem:

`css` prop is not working in generated next.js application until `.babelrc` is modified into:

```
{
  "presets": ["next/babel", "@emotion/babel-preset-css-prop"],
  "plugins": ["@emotion/babel-plugin"]
}
```

I'm cool with that, while not every app is using emotion.

Second problem:

`css` prop is not working in generated react lib.  Create `.babelrc` looks like:

```
{
  "presets": ["@nrwl/react/babel", "@emotion/babel-preset-css-prop"],
  "plugins": []
}
```

Regardless of what plugins / presets will be added nothing happens. In fact, it looks like `.babelrc` in libs are used only in build task.

## Expected Behavior

`css` prop should work in libs with emotion plugins & presets. 

## Steps to Reproduce

https://github.com/RafalFilipek/nx-css-prop-bug

### Environment

```
 Node : 14.15.3
  OS   : win32 x64
  pnpm : 5.15.0

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.1.4
  @nrwl/cypress : 11.1.4
  @nrwl/devkit : 11.1.4
  @nrwl/eslint-plugin-nx : 11.1.4
  @nrwl/express : 11.1.5
  @nrwl/jest : 11.1.4
  @nrwl/linter : 11.1.5
  @nrwl/nest : Not Found
  @nrwl/next : 11.1.4
  @nrwl/node : 11.1.5
  @nrwl/react : 11.1.4
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.4
  @nrwl/web : 11.1.4
  @nrwl/workspace : 11.1.4
  typescript : 4.0.5
  ```

Thanks,

Rafał

**Comment by aiji42** [comment]
I am experiencing the same bug in my project.

I have a nextjs project under apps, and a shared component under libs.
When I pass styles in css props for a component under libs, I get the following output and the styles are not applied correctly.

````
You have tried to stringify object returned from `css` function. It isn't supposed to be used directly (e.g. as value of the `className` prop), but rather handed to emotion so it can handle it (e.g. as value of `css` prop).
````

By the way, when I use css props under apps, it behaves correctly.

Please support it.

**Comment by aiji42** [comment]
We now work around the problem by adding the following line to the top of the file.

```tsx
/** @jsxImportSource @emotion/react */
import React from 'react'
import { css } from '@emotion/react'
```

**Comment by m-sanders** [comment]
We experienced a similar issue albeit with `styled-components` css prop. We fixed it by renaming `.babelrc` to `babel.config.json`.

See https://github.com/nrwl/nx/issues/3620
