### ISSUE TITLE
Warnings of unmet peer dependencies after installing @nrwl/angular package

### ISSUE THREAD

**Issue by Frikki** [nrwl/nx#4523]
## Current Behavior

Warnings of unmet peer dependencies after installing @nrwl/angular package.

## Expected Behavior

No warnings of unmet peer dependencies after installing @nrwl/angular package.

## Steps to Reproduce

```shell
// Create a minimal Nx workspace.
yarn create nx-workspace nrwl-airlines --npm-scope=nrwl-airlines --preset=empty --no-nx-cloud --package-manager=yarn
// Enter workspace directory.
cd nrwl-airlines
// Install @nrwl/angular package.
yarn add @nrwl/angular
// Install husky@next package.
yarn add husky@next --dev
```

### Failure Logs

```shell
yarn add v1.22.10
warning ../package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@nrwl/angular > @nrwl/cypress@11.1.5" has unmet peer dependency "cypress@>= 3 < 7".
warning "@nrwl/angular > jasmine-marbles@0.6.0" has unmet peer dependency "rxjs@^6.4.0".
warning "@nrwl/angular > @nrwl/cypress > @cypress/webpack-preprocessor@4.1.5" has unmet peer dependency "webpack@^4.18.1".
warning "@nrwl/angular > @nrwl/cypress > @cypress/webpack-preprocessor > babel-loader@8.2.2" has unmet peer dependency "webpack@>=2".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ husky@5.0.6
info All dependencies
└─ husky@5.0.6
✨  Done in 1.89s.
```

### Environment

```shell
  Node : 14.15.4
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 11.1.5
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.5
  typescript : 4.0.5
```

**Comment by vsavkin** [comment]
Hi there! Thank you for submitting the issue.

After installing `@nrwl/angular`, you need to run `npx nx g @nrwl/angular:init`, which will add all the necessary peer dependencies and update necessary configs. The init generator is invoked automatically when you add generate the first angular app.

I'm going to close this as it works as expected. There is no way for us to know what peer deps a particular package can require, so the convention is add whatever is necessary in the init generator. 

The instructions we printed were not very clear, so I updated them here: https://github.com/nrwl/nx/pull/4536

Thank you!

**Comment by Stefaans** [comment]
In my case the warning persisted with @nrwl/angular installed as a global package. (It was global because I am a noop with nrwl.) I was able to correct the issue by removing @nrwl/angular as a global package, re-installing it as a local package in my workspace, and then running `npx nx g @nrwl/angular:init` as @vsavkin suggested.
