### ISSUE TITLE
migration fails, update-10-2-0 missing

### ISSUE THREAD

**Issue by bronkalonka** [nrwl/nx#4526]
Hello all,

I am trying to migrate to the latest version with ```nx migrate latest``` and then running ```npm install```. 

```json
    "@nrwl/angular": "11.1.5",
    "@nrwl/cli": "^10.4.10",
    "@nrwl/cypress": "11.1.5",
    "@nrwl/jest": "11.1.5",
    "@nrwl/tao": "11.1.5",
    "@nrwl/workspace": "11.1.5",
```
When running the migrations with ```nx migrate --run-migrations``` the migrations fail.

In the migration.json is this step:

```json
    {
      "version": "10.2.0-beta.1",
      "description": "Upgrade NgRx libraries to version 10.0.0",
      "factory": "./src/migrations/update-10-2-0/update-10-2-0",
      "package": "@nrwl/angular",
      "name": "update-10-2-0"
    },
```

but the related folder in node_modules/@nrwl/workspace/src/migrations is missing and the migration is failing with ```Unregistered task "RunUpdate" in schematic "update-10-2-0".```

![image](https://user-images.githubusercontent.com/32840221/104562585-d8363f80-5648-11eb-870a-49d886af7dbd.png)

I already tried deleting npm cache, deleting node_modules and running npm install again, but to no avail.
Please have a look why this is missing in the npm package.

If I see it correctly [here](https://github.com/nrwl/nx/pull/3543/files) this migration is just updating NgRx to 10.0.0 so I will try to do that manually for now.

Edit: checking the package.json again, the NgRx packages are already migrated to 10.0.0 without that 10-2-0 migration applied.

```json
    "@ngrx/effects": "10.0.0",
    "@ngrx/entity": "10.0.0",
    "@ngrx/store": "10.0.0",
    "@ngrx/store-devtools": "10.0.0",
```

**Comment by vsavkin** [comment]
Thank you for submitting the issue.

The migration in question is in the `@nrwl/angular` package, not in `@nrwl/workspace`. 

That migration is noop if you use `nx migrate`. It's only there for compatibility with `ng update`. So you can remove it from `migrations.json`. 

Not sure why it fails for you though. If you can create a repro, I'll take a look.

**Comment by mathpaquette** [comment]
same here.

**Comment by vsavkin** [comment]
@mathpaquette could you put together a repo with a repro of the before state?

**Comment by mathpaquette** [comment]
> @mathpaquette could you put together a repo with a repro of the before state?

unfortunately not really. My client is in banking sector. Can't easily replicate the issue. Let me see.

**Comment by cnd5041** [comment]
@mathpaquette  did you ever resolve this issue? I am seeing the same thing.

**Comment by amitrai99** [comment]
Has anyone been able resolve this issue?

**Comment by sean-rowe** [comment]
I just removed that particular migration completely from the migrations file,. Then I made sure that my @nrwl/workspace was at the same version as the other plugins. Then I ran the migration successfully
