### ISSUE TITLE
Angular schematics always generated under application's root

### ISSUE THREAD

**Issue by itayod** [nrwl/nx#4530]
I recently opened https://github.com/nrwl/nx/issues/4402 which seems not to be resolved.

Since I could not reopen it, I suggest we reopen this issue and close this one.

**Comment by vsavkin** [comment]
Hi there!

I'm not able to repro it. If I do something like this:

```
cd apps/myapp/src
mkdir -p a/b/c
cd a/b/c
ng g c mycmp
```

`mycmp` is generated in `apps/myapp/src/a/b/c/`.

Am I testing a wrong use case?

**Comment by SonicReal** [comment]
@vsavkin 
`C:\Projects\vsavkin\apps\vsavkin\src\app\a\b\c>ng g c mycmp
CREATE apps/vsavkin/src/app/mycmp/mycmp.component.html
CREATE apps/vsavkin/src/app/mycmp/mycmp.component.spec.ts
CREATE apps/vsavkin/src/app/mycmp/mycmp.component.ts
CREATE apps/vsavkin/src/app/mycmp/mycmp.component.scss
UPDATE apps/vsavkin/src/app/app.module.ts`

 Node : 14.4.0
  OS   : win32 x64
  npm  : 6.14.5

  nx : Not Found
  @nrwl/angular : 11.1.5
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.5
  typescript : 4.0.5

**Comment by itayod** [comment]
> Hi there!
> 
> I'm not able to repro it. If I do something like this:
> 
> ```
> cd apps/myapp/src
> mkdir -p a/b/c
> cd a/b/c
> ng g c mycmp
> ```
> 
> `mycmp` is generated in `apps/myapp/src/a/b/c/`.
> 
> Am I testing a wrong use case?

Hi @vsavkin I appreciate the quick response, it keeps happening in the latest version just like @SonicReal wrote. This might be an issue that is related to the OS... did you try to reproduce it on windows?
