### ISSUE TITLE
Command failed: npm install @nrwl/workspace@11.1.4

### ISSUE THREAD

**Issue by nnuriozturk** [nrwl/nx#4533]
Hi,

I am getting the error followed during the transition to nrwl 11.1.4. Can you help me with this,  I share the output down.

Microsoft Windows [Version 10.0.18363.1198]
(c) 2019 Microsoft Corporation. All rights reserved.

D:\Work\VITWEB>npm run nx migrate

> vitweb@0.0.0 nx D:\Work\VITWEB
> nx "migrate"

Provide the correct package name and version. E.g., @nrwl/workspace@9.0.0.
D:\Work\VITWEB\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: npx tao migrate 
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.handler (D:\Work\VITWEB\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:74:21)
    at Object.runCommand (D:\Work\VITWEB\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (D:\Work\VITWEB\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (D:\Work\VITWEB\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (D:\Work\VITWEB\node_modules\@nrwl\cli\lib\init-local.js:24:13)
    at Object.<anonymous> (D:\Work\VITWEB\node_modules\@nrwl\cli\bin\nx.js:40:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 42596,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vitweb@0.0.0 nx: `nx "migrate"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vitweb@0.0.0 nx script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Users\VB34856\AppData\Roaming\npm-cache\_logs\2021-01-15T06_37_30_013Z-debug.log

D:\Work\VITWEB>npm run nx migrate 11.1.4

> vitweb@0.0.0 nx D:\Work\VITWEB
> nx "migrate" "11.1.4"

Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@11.1.4
Fetching @types/node@12.12.38
Fetching tslint@~6.1.0
Fetching ts-node@~9.1.1
Fetching prettier@2.2.1
Fetching @nrwl/angular@11.1.4
Fetching @nrwl/cli@11.1.4
Fetching @nrwl/cypress@11.1.4
Fetching @nrwl/jest@11.1.4
Fetching @nrwl/linter@11.1.4
Fetching @nrwl/tao@11.1.4
Fetching @angular/cli@~11.0.0
Could not find '@schematics/angular/migrations/migration-collection.json' in '@angular/cli'. Skipping it
Fetching @angular-devkit/build-angular@~0.1100.1
Fetching codelyzer@^6.0.0
Fetching @angular/core@^11.0.3
Fetching @angular/common@^11.0.3
Fetching @angular/forms@^11.0.3
Fetching @angular/compiler@^11.0.3
Fetching @angular/compiler-cli@^11.0.3
Fetching @angular/platform-browser@^11.0.3
Fetching @angular/platform-browser-dynamic@^11.0.3
Fetching @angular/router@^11.0.3
Fetching @angular/language-service@^11.0.3
Fetching @angular/animations@^11.0.3

 ERROR  The migrate command failed. Try the following to migrate your workspace:

> npx @nrwl/tao@latest migrate @nrwl/workspace@11.1.4
This will use the newest version of the migrate functionality, which might have your issue resolved.
----------------------------------------------------------------------------------------------------
Command failed: npm install @angular/forms@^11.0.3
npm WARN enoent ENOENT: no such file or directory, open 'D:\Users\VB34856\AppData\Local\Temp\tmp-25300ovCbS4mL1OL3\package.json'
npm WARN @angular/forms@11.0.3 requires a peer of @angular/core@11.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@11.0.3 requires a peer of @angular/common@11.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@11.0.3 requires a peer of @angular/platform-browser@11.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@11.0.3 requires a peer of rxjs@^6.5.3 but none is installed. You must install peer dependencies yourself.
npm WARN tmp-25300ovCbS4mL1OL3 No description
npm WARN tmp-25300ovCbS4mL1OL3 No repository field.
npm WARN tmp-25300ovCbS4mL1OL3 No README data
npm WARN tmp-25300ovCbS4mL1OL3 No license field.

npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path D:\Users\VB34856\AppData\Local\Temp\tmp-25300ovCbS4mL1OL3\node_modules\tslib
npm ERR! dest D:\Users\VB34856\AppData\Local\Temp\tmp-25300ovCbS4mL1OL3\node_modules\.tslib.DELETE
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename 'D:\Users\VB34856\AppData\Local\Temp\tmp-25300ovCbS4mL1OL3\node_modules\tslib' -> 'D:\Users\VB34856\AppData\Local\Temp\tmp-25300ovCbS4mL1OL3\node_modules\.tslib.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Users\VB34856\AppData\Roaming\npm-cache\_logs\2021-01-15T07_42_08_190Z-debug.log

D:\Work\VITWEB\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: npx tao migrate 11.1.4
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.handler (D:\Work\VITWEB\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:74:21)
    at Object.runCommand (D:\Work\VITWEB\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (D:\Work\VITWEB\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (D:\Work\VITWEB\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (D:\Work\VITWEB\node_modules\@nrwl\cli\lib\init-local.js:24:13)
    at Object.<anonymous> (D:\Work\VITWEB\node_modules\@nrwl\cli\bin\nx.js:40:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 34936,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vitweb@0.0.0 nx: `nx "migrate" "11.1.4"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vitweb@0.0.0 nx script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Users\VB34856\AppData\Roaming\npm-cache\_logs\2021-01-15T08_07_29_283Z-debug.log

D:\Work\VITWEB>npx @nrwl/tao@latest migrate @nrwl/workspace@11.1.4
npx: installed 76 in 58.351s
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@11.1.4

 ERROR  The migrate command failed.

Command failed: npm install @nrwl/workspace@11.1.4
npm WARN enoent ENOENT: no such file or directory, open 'D:\Users\VB34856\AppData\Local\Temp\tmp-37360M3LI5yW5A5VH\package.json'
npm WARN @nrwl/workspace@11.1.4 requires a peer of prettier@^2.0.4 but none is installed. You must install peer dependencies yourself.
npm WARN tmp-37360M3LI5yW5A5VH No description
npm WARN tmp-37360M3LI5yW5A5VH No repository field.
npm WARN tmp-37360M3LI5yW5A5VH No README data
npm WARN tmp-37360M3LI5yW5A5VH No license field.

npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path D:\Users\VB34856\AppData\Local\Temp\tmp-37360M3LI5yW5A5VH\node_modules\define-properties
npm ERR! dest D:\Users\VB34856\AppData\Local\Temp\tmp-37360M3LI5yW5A5VH\node_modules\.define-properties.DELETE
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename 'D:\Users\VB34856\AppData\Local\Temp\tmp-37360M3LI5yW5A5VH\node_modules\define-properties' -> 'D:\Users\VB34856\AppData\Local\Temp\tmp-37360M3LI5yW5A5VH\node_modules\.define-properties.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Users\VB34856\AppData\Roaming\npm-cache\_logs\2021-01-15T08_24_53_527Z-debug.log

**Comment by vsavkin** [comment]
It looks like an issue with npm on your machine. Could you provide a repro with a repo you are trying to migrate?

**Comment by edmundo096** [comment]
Found this while googling `Command failed: npm install @nrwl/workspace@latest`.

Seems that npm version 7 is not supported, even on Nx 12.
Was on Nx version 12.1.1, and tried to update to 12.3.4.

A similar issue, with what it seem the same cause, is on https://github.com/nrwl/nx/issues/4596.

Downgrading to npm 6 (on Node 14) let the command run successfully.
I assume the same would apply to the issue described here.

**Comment by drdreo** [comment]
`npm i --legacy-peer-deps` does the trick but I dont think this is the way forward
