### ISSUE TITLE
Getting "Port 4200 is already in use" sporadisly when running npx nx run-many

### ISSUE THREAD

**Issue by IssaGithub** [nrwl/nx#4535]
Hi,

im very new to NX. After creating a new NX workspace and inserting two allready excsisting angular applications into the workspace. I am getting once and a while the message 
"Port 4200 is already in use. Use '--port' to specify a different port."

Iam also wondering why i cant find any angular.json file. There is only an workspace.json. I asume its because i firs created a empty workspace and after that i added the two angular apps.
When running the apps iam missing the "Initial Chunk" Files table in the console output. 

[nx-report.txt](https://github.com/nrwl/nx/files/5820043/nx-report.txt)
[package.json.txt](https://github.com/nrwl/nx/files/5820038/package.json.txt)

**Comment by vsavkin** [comment]
Hi there!

If you use run-many to serve multiple multiple applications at the same time, they have to have different ports configured in the their options. By default, 4200 is the port used, so change to say 4201 for the second app's options, and the command will work.

I'm going to close this. Thank you!
