### ISSUE TITLE
@nrwl/angular does not export the generators

### ISSUE THREAD

**Issue by beeman** [nrwl/nx#4539]
## Current Behavior

The generators from `@nrwl/angular` are not public, whereas the other ones (`@nrwl/nest`, etc) are. It seems like [this commit](https://github.com/nrwl/nx/commit/16cdba4dc9bf1c2f73874c591784427bb91ab352#diff-a78dce75d6a03e9378cbc856704a42c4c374cf8e471e9bb83d6cef4388dfa1b9) undid the changes made [here](https://github.com/nrwl/nx/commit/baa8c23d0ff1971d70de6d44c5531f1d080659aa#diff-a78dce75d6a03e9378cbc856704a42c4c374cf8e471e9bb83d6cef4388dfa1b9).

## Expected Behavior

I would expect these to be public.

```

>  NX  Report complete - copy this into the issue template

  Node : 14.13.1
  OS   : darwin x64
  npm  : 6.14.8

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.1.5
  @nrwl/cypress : Not Found
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : 11.1.5
  @nrwl/next : Not Found
  @nrwl/node : 11.1.5
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.5
  typescript : 4.0.5
```

**Comment by FrozenPandaz** [comment]
https://github.com/nrwl/nx/pull/4739 will export the `@nrwl/angular` generators from `@nrwl/angular/generators` :)

```ts
import { applicationGenerator, libraryGenerator, [etc.] } from '@nrwl/angular/generators';
```

**Comment by beeman** [comment]
Thanks @FrozenPandaz 🎉
