### ISSUE TITLE
parallel settings in nx.json aren't respected

### ISSUE THREAD

**Issue by martaver** [nrwl/nx#4542]
## Current Behavior

I'm trying to run tasks in parallel. Specifically, `yarn affected:lint`. When I run `yarn affected:lint --parallel=true --maxParallel=16` then all my tasks run at the same time and it completes much faster, as expected. I want this to be the default behaviour, so I set `taskRunnerOptions` as per configs described at: https://nx.dev/latest/react/getting-started/configuration#nx-json

My (`taskRunnerOptions`) config:
```
"tasksRunnerOptions": {
    "default": {
      "runner": "@nrwl/nx-cloud",
      "options": {
        "parallel": true,
        "maxParallel": "16",
        "accessToken": "XXX",
        "cacheableOperations": ["build", "test", "lint", "e2e"],
        "canTrackAnalytics": false,
        "showUsageWarnings": true
      }
    }
  },
```

## Expected Behavior

Now, when I run `yarn affected:lint` I expect all the tasks to run much faster, as when I manually gave it the arguments.

Instead, it proceeds to lint the projects one by one.

## Steps to Reproduce

The nx repro I'm working with is here: https://github.com/cleric-sh/experiments-nx/tree/repro-parallelism

If you run `yarn affected:lint` you should see one-by-one behaviour, even though `nx.json` is configured for parallelism.

### Failure Logs

None

### Environment

```
  Node : 14.14.0
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : Not Found
  @nrwl/next : 11.1.5
  @nrwl/node : Not Found
  @nrwl/react : 11.1.5
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : 11.1.5
  @nrwl/workspace : 11.1.5
  typescript : 4.1.3
```

I'm looking for something I might have misconfigured, but I'm hard pressed to see what might be out of place. Please feel free to change the issue type if this isn't a bug!

**Comment by martaver** [comment]
Nx is: `nx@11.1.5`

**Comment by tspmelo** [comment]
This is happening again in `nx@12.8.0`.

**Comment by christianacca** [comment]
Looks like it's also a problem in `nx@12.9.0`
