### ISSUE TITLE
@typescript-eslint rules are applied to javscript files

### ISSUE THREAD

**Issue by martaver** [nrwl/nx#4544]
## Current Behavior

This is a contrived example to demonstrate lint problems that emerge when installing a storybook configuration on a react project.

When I create a javascript file in a typescript (react) project, for example:
```
const foo = require('react');
```

Then `eslint` fails with the following rule: 
```
Require statement not part of import statement.(@typescript-eslint/no-var-requires)
```

Since the `@typescript-eslint` plugin is only used in the `@nrwl/nx/typescript` configuration, and in the base `.eslintrc.json` is only applied to files of type `*.ts` and `*.tsx`, I believe this is a bug. More, if typescript rules are needlessly being run on javascript files, then this is an overhead.

## Expected Behavior

`@typescript-eslint` rules to be ignored for `*.js` and `*.jsx` files.

## Steps to Reproduce

`yarn create nx-workspace --preset=react`

Then create a file `blah.js` at `./apps/app/src/app` and add `const foo = require('react')` to it.

Run `yarn lint`. You should see:
```
  1:7   warning  'foo' is assigned a value but never used        @typescript-eslint/no-unused-vars
  1:13  error    Require statement not part of import statement  @typescript-eslint/no-var-requires
```

### Environment

```
  Node : 14.14.0
  OS   : darwin x64
  npm  : 6.14.8
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.1.5
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : 11.1.5
  @nrwl/workspace : 11.1.5
  typescript : 4.0.5
```

**Comment by martaver** [comment]
Nx is: `nx@11.1.5`

**Comment by nkwood** [comment]
Probably related to https://github.com/nrwl/nx/issues/4441

**Comment by martaver** [comment]
For the record, I'm on the react stack, with no angular features installed.
