### ISSUE TITLE
Add a way to ignore dependency when building publishable lib

### ISSUE THREAD

**Issue by Mubramaj** [nrwl/nx#4547]
## Description

Add a way to ignore a dependency when building a publishable library. I know that there is the `.nxignore`. However,
the files added to the `.nxignore` are  also ignored when running the `affected` command which is not what is needed here.

## Motivation

If in a publishable lib there is some spec files that relies on a `utils/util-testing` external lib, this test utility will be built when running the `nx build` command. However this is not needed to publish the library since it's only used in the .spec files.

## Suggested Implementation

Add `.buildignore` for each buildable/publishable lib

## Alternate Implementations

Add an option flag to the command `--ignoreLibs=shared-utils-util-testing,shared-util-foo`

## Other alternate but it will be a `bug fix`

Ignore the dependencies in `*.spec` files when building the library

If needed I can create a simple repo to demonstrate the use case

**Comment by hasparus** [comment]
Hey, is there a solution for this in 2021? I'm having a similar problem (need to ignore tests).

**Comment by vz-tl** [comment]
Here the same. Having several libs but only some of them should be built, which contain specs as well as Storybook stories importing from other libs. Basically this should be ok as those files are more for development purpose and not part of the resulting packages. So actually no reason for the packaging process to complain about these imports. 
As I didn't find any solution so far, is there any hope for an option to exclude those files?

**Comment by nzpopa** [comment]
I have the exact same issue and need the same ignore feature. Found a temporary fix by running "exit 0" as "command" for my "build" task inside the lib's project.json
