### ISSUE TITLE
Unable to import assets from library component into Next app

### ISSUE THREAD

**Issue by therk** [nrwl/nx#4552]
## Current Behavior
Image is not found

## Expected Behavior
Following the instruction on "9. Shared assets library and nx.json - Nx Workspaces Course, by Nrwl" https://www.youtube.com/watch?v=LYjX2V-eQa8 The image should be found. 

## Steps to Reproduce
Created a test project to reproduce the issue https://github.com/therk/nx-test-next-with-assets
In the test project, there is ui lib with the About component and assets folder with about.png file.
In the workspace.json added the following section under build:
```
"assets": [
              {
                "glob": "**/*",
                "input": "libs/ui/src/assets",
                "output": "assets/ui"
              }
            ]
```
 
Int the About component, try to reference the image using:
`<img src="/assets/ui/about.png" alt="About"></img>`

### Environment

>  NX  Report complete - copy this into the issue template

  Node : 15.1.0
  OS   : darwin x64
  yarn : 1.22.4
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : Not Found
  @nrwl/next : 11.1.5
  @nrwl/node : Not Found
  @nrwl/react : 11.1.5
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : 11.1.5
  @nrwl/workspace : 11.1.5
  typescript : 4.0.5

**Comment by DmitryIvanovIAMM** [comment]
Has the same issue

**Comment by Ivanova-A** [comment]
Please, fix it!

**Comment by lunaplush** [comment]
I have the same issue. Need to resolve it.

**Comment by NachoVazquez** [comment]
It works with `img` but not with native NextJS `Image`

**Comment by marqpdx** [comment]
Mine too fails w/ NextJS Image, but works with `img`

**Comment by jls527** [comment]
**This is still an issue. Please can someone have a look?**

Steps to reproduce:

1. Create Nx workspace with Next.js app
2. Generate React library (shared)
3. Add any image file to shared library and reference it in a React component:  
```tsx
import myImage from './assets/my-image.png'

export const MyComp = () => <img src={myImage} />
```

5. Import the React component in your Next.js app. Image will appear broken - probably like this:
```
<img src="[object Object]">
```

**Comment by 7alip** [comment]
Providing absolute url for NextImage worked for me.

```jsx
<NextImage src="http://localhost:4200/assets/image.png" />
// <NextImage src={`${NX_APP_URL}/assets/image.png`} />
```
