### ISSUE TITLE
Nrwl CLI installation prevents the use of the default Angular CLI in other projects

### ISSUE THREAD

**Issue by ArkasDev** [nrwl/nx#4554]
## Current Behavior
I have migrated one organization to NX. For this I have installed the necessary Nrwl modules. I also have other Angular projects on my machine. Unfortunately these are now affected by Nrwl. If I want to use the default Angular CLI in another project e.g. `ng serve`, then the following error occurs.
```
internal/modules/cjs/loader.js:985
throw err; 

Error: Cannot find module '\node_modules\@nrwl\cli\bin\nx.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

## Expected Behavior
I can use the default Angular CLI in other projects without dependencies to Nrwl.

### Environment
Angular 11.0.6
Node 12.16.1

Installed in another project (not global)
Nrwl 11.1.1

**Comment by vsavkin** [comment]
Thank you for submitting the issue.
 
We do not modify any global deps or files. There is nothing global that Nx changes in any way unless you install nx packages globally but even then it will not affect anything outside of those modules. I don't believe we can affect any other project on your machine.

There are a few reasons you could see something like what you see now:
* if you have a project within a project.  Then the inner project is part of the Nx repo.
* Your have node_modules in your home dir or somewhere else in the ancestor tree.
* The `ng` you run is actually located in a different path than you expect.  <-- This is likely the issue, often happens in webstorm

I'd do `which ng` to see where you load ng from. You can also walk up the tree starting from your Angular CLI project to see if you can find any node modules.

I'm going to close this issue cause it's likely to be one of the reasons I outlined. 

Thanks!
