### ISSUE TITLE
Prefix in auto-generated eslintrc does not respect angular.json

### ISSUE THREAD

**Issue by EthanSK** [nrwl/nx#4559]
## Current Behavior
When generating a new lib or something with an eslintrc, the enforced angular prefix for components and directives does not use the one in angular.json.

## Expected Behavior
It should use the one in angular.json. Or at least provide us with another way of setting the default prefix other than changing the npmScope in nx.json

**Comment by johanchouquet** [comment]
So, is there a workaround ?

**Comment by JamesHenry** [comment]
I am little confused by the wording of this one, as prefix definitely is respected for lint config generation.

I will summarize the relevant pieces of this:

- When you generate a new library, you can optionally pass a value for `--prefix`.
- This option definitely _is_ respected when generating either a `tslint.json` or `.eslintrc.json`.
- The value gets written to the linting config files, and it gets written to the angular.json/workspace.json
- There is no "live link" of some kind behind these values, they are separate config files which serve different purposes.

Perhaps the last point is the source of confusion?

If you update the prefix value that is stored in your angular.json/workspace.json that will not have any impact on the prefix value which is stored in your linting configuration and vice-versa, so if you make changes after the point of generation, it will be up to you to keep the two separate files in sync.

If I have misunderstood and you are describing a separate issue, then please feel to reopen the issue with clear reproduction steps for me to follow.

Hope that helps!
