### ISSUE TITLE
[nrwl/storybook] '@storybook/html' uiFramework option not working in storybook configuration V11.1.5

### ISSUE THREAD

**Issue by kishok** [nrwl/nx#4564]
## Current Behavior
Hi @vsavkin, @nrwl/storybook:configuration not working for the "uiFramework":"**@storybook/html**" value in v11.1.5. So not able to add storybook to my web component. please add that value to uiFramework schema enum. Also support **@storybook/web-components** in @nrwl/storybook plugin.

## Expected Behavior
Storybook configuration generator should accept "@storybook/html" value for generic HTML Projects

### Environment
"@nrwl/storybook": "^11.1.5"

### Reference Issue: #4466

**Comment by juristr** [comment]
Hey @kishok. You're right, that's currently not supported. I'll add this to our feature list, thx for reporting.

**Comment by FrancoisDF** [comment]
Any update on this issue? 
It was previously working with `nrwl@10.2.0`.

**Comment by bendunn135** [comment]
Also looking for an update on this

**Comment by psycho063** [comment]
I am having the same issue when trying to create a storybook based on '@storybook/html'.

**Comment by mandarini** [comment]
Hi there! This issue should be solved in the latest versions of Nx and `@nrwl/storybook`, so I will close this issue now. Please let me know if you try it and it still fails, but it should be working normally now.
