### ISSUE TITLE
install nx global is not cli in workspace

### ISSUE THREAD

**Issue by BenzNatthawat** [nrwl/nx#4566]
$ yarn add global @nrwl/workspace
yarn add v1.22.5
warning package-lock.json found. Your project contains lock files generated by t
ools other than Yarn. It is advised not to mix package managers in order to avoi
d resolution inconsistencies caused by unsynchronized lock files. To clear this
warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check.
Excluding it from installation.
info fsevents@2.3.1: The platform "win32" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check.
Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check.
 Excluding it from installation.
[3/4] Linking dependencies...
warning "@nrwl/cypress > @cypress/webpack-preprocessor@4.1.5" has unmet peer dep
endency "webpack@^4.18.1".
warning "@nrwl/cypress > @cypress/webpack-preprocessor > babel-loader@8.2.2" has
 unmet peer dependency "webpack@>=2".
warning "@nrwl/next > copy-webpack-plugin@6.0.3" has unmet peer dependency "webp
ack@^4.37.0 || ^5.0.0".
warning "@nrwl/next > url-loader@3.0.0" has unmet peer dependency "webpack@^4.0.
0 || ^5.0.0".
warning "@nrwl/next > @nrwl/react > eslint-plugin-react-hooks@2.5.1" has incorre
ct peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
[4/4] Building fresh packages...
warning "@nrwl/workspace" is already in "devDependencies". Please remove existin
g entry first before adding it to "dependencies".
success Saved 2 new dependencies.
info Direct dependencies
├─ @nrwl/workspace@11.1.5
└─ global@4.4.0
info All dependencies
├─ @nrwl/workspace@11.1.5
└─ global@4.4.0
Done in 33.57s.

banz_@DESKTOP-JU85RUU MINGW64 ~/Documents/OS/leave (dev)
$ nx

Nx - Extensible Dev Tools for Monorepos.

Create a new project.
 nx new [project-name] [--collection=collection] [options, ...]

Generate code.
 nx generate [collection:][generator] [options, ...]
 nx g [collection:][generator] [options, ...]

Run target.
 nx run [project][:target][:configuration] [options, ...]
 nx r [project][:target][:configuration] [options, ...]

You can also use the infix notation to run a target:
 nx [target] [project] [options, ...]

Migrate packages and create migrations.json.
 nx migrate [package-name]

Run migrations.
 nx migrate --run-migrations=[filename]

banz_@DESKTOP-JU85RUU MINGW64 ~/Documents/OS/leave (dev)
$ npm run start:all

> leave@0.0.0 start:all C:\Users\banz_\Documents\OS\leave
> nx run-many --parallel --target=serve --all --maxParallel=6

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at Module.require (C:\Users\banz_\Documents\OS\leave\node_modules\@nrwl\tao\src\compat\compat.js:7:40)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\banz_\Documents\OS\leave\node_modules\@nrwl\workspace\src\core\project-graph\build-dependencies\typescript-import-locator.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leave@0.0.0 start:all: `nx run-many --parallel --target=serve --all --maxParallel=6`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leave@0.0.0 start:all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     AppData\Roaming\npm-cache\_logs\2021-01-19T11_02_47_934Z-debug.log

**Comment by vsavkin** [comment]
Hi there!

You aren't supposed to install @nrwl/workspace globally.

If this isn't what the issue is about, please reopen it with more details.

Thank you!
