### ISSUE TITLE
Link to slack is broken

### ISSUE THREAD

**Issue by katyapavlenko** [nrwl/nx#4567]
Hi! Link to slack for "have a question?" from this screen is broken 
<img width="1183" alt="Screenshot 2021-01-19 at 14 50 05" src="https://user-images.githubusercontent.com/55044564/105036777-a9afce80-5a65-11eb-9c7c-87ed6dbf2076.png">
<img width="653" alt="Screenshot 2021-01-19 at 14 50 13" src="https://user-images.githubusercontent.com/55044564/105036784-ab799200-5a65-11eb-8932-27d82b40de25.png">

**Comment by bcabanes** [comment]
Hi @katyapavlenko and thank you for opening an issue! 
We've updated the link on the community screen on nx.dev, I'll then issue.

**Comment by alvaromartmart** [comment]
Hi @bcabanes, I think the link is still broken

**Comment by bcabanes** [comment]
Hi @ngmariusz, I'm confused since it does work for me on this screen: https://github.com/nrwl/nx/issues/new/choose (https://go.nrwl.io/join-slack).
I do not have access to the Slack settings, so I'll pass the link your shared to the team. Thanks!
