### ISSUE TITLE
Feature request: format scss with prettier

### ISSUE THREAD

**Issue by adgoncal** [nrwl/nx#457]
It is great that nx uses prettier to format ts. However, prettier also supports formatting other file types, and I think it would be valuable to use prettier to format css/scss (and html also, once that is supported by prettier).

As a reference, I am currently doing this on my project's package.json:

```diff
-    "format:check": "./node_modules/.bin/nx format check",
-    "format:write": "./node_modules/.bin/nx format write",
+    "format-scss:check": "prettier '{apps,libs}/**/*.scss' --debug-check",
+    "format-scss:write": "prettier '{apps,libs}/**/*.scss' --write"`
+    "format-ts:check": "./node_modules/.bin/nx format check",
+    "format-ts:write": "./node_modules/.bin/nx format write",
+    "format:check": "npm run format-ts:check && npm run format-scss:check",
+    "format:write": "npm run format-ts:write && npm run format-scss:write",
```

---

On another topic, can someone please tell me why nx scripts use the relative path `./node_modules/.bin/nx` instead of just using `nx`? If I understand it correctly, running `npm run <script-name>` will look for executables in `node_modules/.bin/`, so why is it necessary to use a relative path?

**Comment by sumigoma** [comment]
@adgoncal I had the same question about `./node_modules/.bin/nx`.
@jeffbcross Is there a reason for this? Is this a `yarn` issue?
