### ISSUE TITLE
@nrwl/workspace:move for buildable library

### ISSUE THREAD

**Issue by junekpavel** [nrwl/nx#4570]
## Current Behavior

When moving buildable library, the destination path in `ng-package.json` and package name in `package.json` are not updated.

## Expected Behavior

The destination path in `ng-package.json` and name in `package.json` should be both updated based on new library location.

## Steps to Reproduce

Run following commands: 

```
nx g @nrwl/angular:lib my-library --buildable
nx g @nrwl/workspace:move --project my-library shared/my-library
```

New library is generated and moved to new destination.

---

The content of `libs/shared/my-library/ng-package.json` is
```
{
  "$schema": "../../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../../dist/libs/my-library",
  "lib": {
    "entryFile": "src/index.ts"
  }
}
```

But it should be (dest path is changed):
```
{
  "$schema": "../../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../../dist/libs/shared/my-library",
  "lib": {
    "entryFile": "src/index.ts"
  }
}

```

---

And same for `libs/shared/my-library/package.json`. Instead of: 
```
{
  "name": "@myworkspace/my-library",
  "version": "0.0.1",
  "peerDependencies": {
    "@angular/common": "^11.0.5",
    "@angular/core": "^11.0.5"
  },
  "dependencies": {
    "tslib": "^2.0.0"
  }
}
```

It should be (name updated):
```
{
  "name": "@myworkspace/shared/my-library",
  "version": "0.0.1",
  "peerDependencies": {
    "@angular/common": "^11.0.5",
    "@angular/core": "^11.0.5"
  },
  "dependencies": {
    "tslib": "^2.0.0"
  }
}

```

### Environment

```
 Node : 12.16.2
  OS   : darwin x64
  yarn : 1.22.0
  
  nx : Not Found
  @nrwl/angular : 11.1.5
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.1.5
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.5
  typescript : 4.0.5
```

**Comment by simondotm** [comment]
Bot is pretty anxious to close bugs!
This issue also exhibits if you use `--importPath` in the move (for a buildable node library for example)

`nx g move my-library new/dir --importPath="@myorg/new-dir-my-library"` should set the name in the `package.json` appropriately but it doesn't. (using Nx `v12.3.4`)
