### ISSUE TITLE
Can't fix require loop using Path

### ISSUE THREAD

**Issue by naishe** [nrwl/nx#4572]
I am using [Objection.js](https://vincit.github.io/objection.js/) as the ORM in my server side application. In model classes of the tables that are joined via an intermediate table, you need to import them in each other. For example, if you have `Book` and `Author` models connected via a many to many relationship, you would have to have `Book` imported in `Author`, and `Author` imported in `Book`.

This creates cyclic dependency.

To fix this, you may use relative paths of the files [as indicated here](https://vincit.github.io/objection.js/guide/relations.html#require-loops). However, since Nx does not preserves directory structure when build, I am not able to do something like this:

```lang-ts
static get relationMappings() {
    return {
      authors: {
        relation: Model.ManyToManyRelation,
        modelClass: path.join(__dirname, '../Book/index'),  // <--- Error: This is not resolving
        join: {
          from: 'authors.id',
          through: {
            from: 'authorsBooks.authorId',
            to: 'authorsBooks.bookId',
          },
          to: 'books.id',
        },
      },
    };
  }
```
### Environment

```bash
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.0.11
  @nrwl/cypress : 10.0.11
  @nrwl/eslint-plugin-nx : 10.0.11
  @nrwl/express : 10.0.11
  @nrwl/jest : 10.0.11
  @nrwl/linter : 10.0.11
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.0.11
  @nrwl/react : 10.0.11
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.11
  @nrwl/web : 10.0.11
  @nrwl/workspace : 10.0.11
  typescript : 3.9.7
```

**Comment by crisboarna** [comment]
Any sort of path usage of `path` to read files from a specific directory results in errors as the entire directory structure is lost. Ideally we should have an option for node apps that specifies for builder to not bundle it all in a single js file but format it as if it was a lerna project, code is present in same directory structure as src and any libs are part of `node_modules`. This is also the same for TypeORM or inversify or any tool where you want to programatically import entire directory. I think this should be a high priority task to be solved. Or at least a feasible workaround solution provided.
