### ISSUE TITLE
Respect packageGroup metadata when running 'nx migrate'

### ISSUE THREAD

**Issue by minijus** [nrwl/nx#4575]
## Description
Angular defines `packageGroup` metadata with published packages and also advise to do same for library developers.
Whenever `ng update package-name` is run this data is being checked and "respected" by `@schematics/update`.

Documentation:
https://github.com/angular/angular-cli/blob/master/docs/specifications/update.md#library-developers

Implementation of `@schematics/update`:
https://github.com/angular/angular-cli/blob/master/packages/schematics/update/update/index.ts

Example of metadata on published package:
https://unpkg.com/@angular/core@11.0.9/package.json
https://unpkg.com/@angular/cli@11.0.7/package.json
https://unpkg.com/@angular/material@11.0.4/package.json
https://unpkg.com/@ngrx/store@10.1.2/package.json

## Motivation
Nrwl strongly pushes to use `nx migrate` instead of `ng update`, but at the same time it does not fully replace it.

Scenario: having a repository with latest version of `@nrwl` libraries and one patch version behind for `@angular`.
`nx migrate @angular/core`:
![image](https://user-images.githubusercontent.com/3633549/105224374-c3d0d600-5b65-11eb-88f8-f70a9a47c161.png)

`FORCE_NG_UPDATE=true ng update @angular/core`:
![image](https://user-images.githubusercontent.com/3633549/105224401-ce8b6b00-5b65-11eb-9580-51d97ed502f5.png)

## Suggested Implementation
`nx` could extract `ng-update` metadata from `package.json` and include packages defined in `packageGroup` within migration.

**Comment by viceice** [comment]
👎

**Comment by Den-dp** [comment]
This one definitely needs some love

**Comment by minijus** [comment]
This just became more relevant after migrating to project based configurations.
`FORCE_NG_UPDATE=true ng update *` now fails because of configuration version missmatch.

At given moment having workspace with v2 of workspace configuration there is no alternative to run updates that respect `packageGroup` metadata.

![image](https://user-images.githubusercontent.com/3633549/143013333-3aa30fd4-3e7a-4337-8915-089a928ccdf9.png)

**Comment by gioragutt** [comment]
Hi people who are involved in this issue, I'd like to start working on it.

I've been doing a lot of prep-work by learning and cleaning up the code of `packages/nx/src/command-line/migrate.ts`.

I'd like to spec the feature correctly. Currently, as I understand, `"ng-update"` sits in the `package.json` of a library.

It contains:
1. `"migrations"` field which points to a migrations json file
2. `"packageGroup"` field which indicates the list of packages that should be fetched and migrated alongside the main package, if they are also being depended upon.

If I compare this to NX's behavior in the [`migrate.ts`](https://github.com/nrwl/nx/blob/master/packages/nx/src/command-line/migrate.ts#L225-L261) to [`packages/workspace/package.json#ng-update.packageGroup`](https://github.com/nrwl/nx/blob/master/packages/workspace/package.json#L34), I find that:
1. The declared packageGroup in the package.json is missing:  `@nrwl/js`, `@nrwl/cli`, `@nrwl/nx-cloud`, `@nrwl/react-native`, `@nrwl/detox` (which do exist in `migrate.ts`).
2. NX overrides the version of `nx-cloud` to `"latest"`.

If I want to be able to turn NX's custom behavior into something that any package can make use of, I'd have to:
1. Allow something like: `"packageGroup": ["@nrwl/js", { "package": "@nrwl/nx-cloud", "version": "latest" }]`
2. Propagate `"packageGroup"` to [`Migrator#collapsePackages`](https://github.com/nrwl/nx/blob/master/packages/nx/src/command-line/migrate.ts#L217) and have it resolve packages in `packageGroup` to the main package version, or to the specified one (like in `"nx-cloud"`).

Does it sound good? I'll upload a PR shortly with the proposed changes. I'll try to separate it into 2 PRs, refactoring and relevant changes.
