### ISSUE TITLE
Add base url option to @nrwl/web:file-server

### ISSUE THREAD

**Issue by ashwinGokhale** [nrwl/nx#4579]
## Description
I would like to have an option in @nrwl/web:file-server to allow serving an app from disk on a sub path, like `http://localhost:4200/my/sub/path`

## Motivation

I have an Angular app that is built with a `baseHref` of `"/portal/v4"` and an `outputPath` of `dist/my-app`. I would like to be able to specify a base url so that I can serve the app from `dist/example-app` on `http://localhost:4200/portal/v4`. It's pretty easy to do in `express`, but it would be nice if this functionality was built into the file-server executor:

```javascript
const express = require('express');
const path = require('path');

const dist = path.resolve('./dist/example-app');

const app = express();
app.use('/portal/v4', express.static(dist));
app.get('*', (req, res) => res.sendFile(path.join(dist, 'index.html')));

app.listen(4200);
```

**Comment by normandjulian** [comment]
I'm facing the same issue
