### ISSUE TITLE
dep-graph : see only the dependencies between libs

### ISSUE THREAD

**Issue by belamrani** [nrwl/nx#458]
It would be great to generate the graph dependencies only for the libs. 
I tried the --files option but it doesn't seems to work.
I tried : 
yarn dep-graph --files="libs/**/*" 
yarn dep-graph --files="libs/" 

Thank you :)

**Comment by FrozenPandaz** [comment]
Sorry for very delayed response.

@belamrani 

What is the motivation for this use case? 

> In _my_ experience, apps are the more important part of the dependency graph as they are the end product and it is most useful to see which end products are affected by the changes. The relationships of the libraries are mostly for transparency to understand _why_ the end product has changed and to assess what the risks of changing a particular library are.
