### ISSUE TITLE
Can't resolve lib-module when run typeorm migration with tsconfig from server

### ISSUE THREAD

**Issue by nglazov** [nrwl/nx#4580]
I have an application with structure
/apps
--/client
--/server
/libs
--/common

In server i have entities like
```typescript
import { Column, Entity } from 'typeorm';
import { SomeEnum } from '@my-system/common';

@Entity('entities')
export class Entitites {
  @PrimaryColumn('enum', { enum: SomeEnum })
  type: SomeEnum;
}
```

Added scripts in `package.json`
```json
{
    "ts-typeorm": "TS_NODE_PROJECT=./apps/server/tsconfig.json node --require ts-node/register ./node_modules/.bin/typeorm",
    "migration:generate": "yarn ts-typeorm migration:generate",
}
```

configured `ormconfig.json` in nrwl project root

and run it `yarn migration:generate -n init `

## Current Behavior
Got error message:` Error: Cannot find module '@my-system/common'`

## Expected Behavior
Migration files was generated

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs
```
Error during migration generation:
Error: Cannot find module '@my-system/common'
Require stack:
- /root/apps/server/src/companies/entites/entities.entity.ts
- /root/node_modules/typeorm/util/DirectoryExportedClassesLoader.js
- /root/node_modules/typeorm/connection/ConnectionMetadataBuilder.js
- /root/node_modules/typeorm/connection/Connection.js
- /root/node_modules/typeorm/connection/ConnectionManager.js
- /root/node_modules/typeorm/index.js
- /root/node_modules/typeorm/commands/SchemaSyncCommand.js
- /root/node_modules/typeorm/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/root/apps/server/src/companies/entites/entities.entity.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module.m._compile (/root/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/root/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:985:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/apps/server/src/companies/entites/entities.entity.ts',
    '/root/node_modules/typeorm/util/DirectoryExportedClassesLoader.js',
    '/root/node_modules/typeorm/connection/ConnectionMetadataBuilder.js',
    '/root/node_modules/typeorm/connection/Connection.js',
    '/root/node_modules/typeorm/connection/ConnectionManager.js',
    '/root/node_modules/typeorm/index.js',
    '/root/node_modules/typeorm/commands/SchemaSyncCommand.js',
    '/root/node_modules/typeorm/cli.js'
  ]
}
```

### Environment

 Node : 12.18.3
  OS   : darwin x64
  yarn : 1.22.5
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.0.18
  @nrwl/cypress : 11.0.18
  @nrwl/devkit : 11.0.18
  @nrwl/eslint-plugin-nx : 11.0.18
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.18
  @nrwl/linter : 11.0.18
  @nrwl/nest : 11.0.18
  @nrwl/next : Not Found
  @nrwl/node : 11.0.18
  @nrwl/react : 11.0.18
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.18
  @nrwl/web : 11.0.18
  @nrwl/workspace : 11.0.18
  typescript : 4.1.3

**Comment by nglazov** [comment]
Got help in [slack](https://nrwlcommunity.slack.com/archives/CMFKWPU6Q/p1611222974004500)

1) `install npm scripty`
2) create `tools/scripts/db/migration/generate.sh`
```bash
cd ./apps/"$1"
ts-node -P ./tsconfig.json -O '{"module": "commonjs", "experimentalDecorators": true}' -r tsconfig-paths/register ../../node_modules/typeorm/cli.js --config ormconfig.cli.js migration:generate -n "$2"
```
3) add in package.json
```json
"scripts": {
  ...
  "db:migration:generate": "scripty",
},
  "scripty": {
    "path": "tools/scripts",
    "windowsPath": "tools/scripts-win"
  },
...
```
4) run `yarn run db:migration:generate api MyMigration`

**Comment by Nightbr** [comment]
@vsavkin Hey, seems a common issue (see several issues about this + several message in the Slack) maybe we could find a way to better integrate TypeORM with Nx or add some "How-to" in the documentation. What do you think?

**Comment by bekos** [comment]
@Nightbr Sorry for the late response 😞  Yeah, you are right, it would be really helpful if we can somehow solve this inside Nx. I have seen on Slack, that you have mainstreamed a solution about it 😃 Do you care of sending a PR or have a discussion about it?

**Comment by Nightbr** [comment]
The solution, I use is a workaround with scripty & shell script but feel free to DM me on Slack to organize a call to discuss about it :ok_hand:

**Comment by johnny68** [comment]
I wish you guys had solved this. But building on @nglazov answer and my already present scripts, I used

```
        "typeorm": "ts-node -r tsconfig-paths/register node_modules/typeorm/cli.js  -f ormconfig",
        "migration:generate": "yarn run typeorm migration:generate -d src/migrations -n",
        "migration:create": "yarn run typeorm migration:create -d src/migrations -n",
        "migration:revert": "yarn run typeorm migration:revert"
```
Basically, `-r tsconfig-paths/register` did the trick.

**Comment by kkb0318** [comment]
I'm glad to find a great answer here.
Based on @johnny68 @nglazov  answer, I solved the problem by adding the following code to package.json

```package.json
    "typeorm": "ts-node -r tsconfig-paths/register -O '{\"module\": \"commonjs\"}' ./node_modules/typeorm/cli.js -f ormconfig",
    "migration:generate": "yarn run typeorm migration:generate  -n"
```

and run 
```
yarn run db:migration:generate MyMigrationName
```
