### ISSUE TITLE
Reexporting types yields in "export 'Type' was not found in './module' warnings

### ISSUE THREAD

**Issue by Katona** [nrwl/nx#4581]
## Current Behavior
Reexporting a type emits a warning:
```
export 'Type' was not found in './module'
```

## Expected Behavior
There shouldn't be a warning.

## Steps to Reproduce
We a have a node library project which export some types in `index.ts`:
```
export 'Type' from './module';
```

`module.ts` looks like this:
```
export interface Type {
  test(): string;
}
```
If I launch the app with `nx serve` then during the bundling the following warning is emitted:
```
export 'Type' was not found in './module'
```

If I build the project with `nx build project` then there is no warning.

I understand that this is because `export Type from './module'` is not removed during transpiling using `nx serve` but `nx build` seems to be able to detect that this is only a type and removes it.

### Environment
  Node : 12.14.1
  OS   : win32 x64
  npm  : 6.13.4

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.0.20
  @nrwl/cypress : 11.0.20
  @nrwl/devkit : 11.0.20
  @nrwl/eslint-plugin-nx : 11.0.20
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.20
  @nrwl/linter : 11.0.20
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.0.20
  @nrwl/react : 11.0.20
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.20
  @nrwl/web : 11.0.20
  @nrwl/workspace : 11.0.20
  typescript : 4.0.5

**Comment by bekos** [comment]
@Katona can you please create a repro repo so we can better understand and debug your case? fwiw I think you should export like this: `export { Type } from './module';` 🤔

**Comment by Katona** [comment]
Hi,

I can not reproduce this issue in a separate repository, unfortunately. My issue is similar to this one https://github.com/nrwl/nx/issues/3915 with regards to the warnings. The problem seems to be that we are exporting a typescript interface and that is left in the transpiled code for some reason and when webpack is bundling it can not resolve that interface (since they exist only in typescript). There is a workaround however:
```
export type { Type } from './module';
```
which I wanted to avoid because now we have to distinguish based on what we are exporting, but it seems have to use. I think we can close this as I can not give you more information.

**Comment by Katona** [comment]
Closing this since I can not reproduce it in a separate repo.

**Comment by ivibe** [comment]
I had same issue for node based apps. Fixed it by adding 
```json
    "module": "commonjs"
```
into compilerOptions of tsconfig.app.json, that was missing for some reason.
