### ISSUE TITLE
Cannot reference the same project-source from different projects in angular.json

### ISSUE THREAD

**Issue by tommueller** [nrwl/nx#4583]
Current Behavior
We are using singleSPA to bundle parts of our Angular application. In order to keep developing simple, I created to projects in my angular.json, like this:

```json
{
  "version": 1,
  "projects": {
    "as": {
      "projectType": "application",
      "root": "apps/as",
      "sourceRoot": "apps/as/src",
      "architect": {
        "build": {
          "options": {
            "main": "apps/as/src/main.ts"
          }
        }
      }
    },
    "as-with-differences": {
      "projectType": "application",
      "root": "apps/as",
      "sourceRoot": "apps/as/src",
      "architect": {
        "build": {
          "options": {
            "main": "apps/as/src/main.spa.ts"
          }
        }
      }
    }
  }
}
```
I then also declare both projects in my `nx.json`.

This works fine, except that when I run `npm run lint` nx throws an error saying: `The angular.json file is out of sync: Cannot find project 'as-with-differences' in 'apps/as'.

## Expected Behavior
Nx should not have any issues with this sort of setup. Neither the name, nor the content of the second entry for a project matters. If you switch them around, you will see, that the first one always works and the second one will throw the error.
## Steps to Reproduce
https://github.com/nrwl/nx-examples/pull/127

### Environment

<code>
<pre>Node : 14.3.0
  OS   : linux x64
  yarn : 1.21.1
  
  nx : Not Found
  @nrwl/angular : 11.1.5
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.1.5
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : 11.1.5
  @nrwl/workspace : 11.1.5
  typescript : 4.0.3</pre></code>

**Comment by tommueller** [comment]
Any more information I can provide to help resolving this issue?

**Comment by tommueller** [comment]
Still an issue.

**Comment by brandonroberts** [comment]
@tommueller I would recommend adding additional targets under `architect` such as `build:spa` rather than additional projects using the same source.

**Comment by tommueller** [comment]
Thanks @brandonroberts that fixed the issue.

I do however still wonder why nx struggles with this, as Angular doesn't mind. If this is expected behavior, it might be helpful to clarify the error message. Like "Multiple projects cannot use the same project source" or something alike.
