### ISSUE TITLE
Some global eslint rules are overridden after upgrade to Nx 11

### ISSUE THREAD

**Issue by tommueller** [nrwl/nx#4585]
## Current Behavior
I defined a couple of global adjustments to our root `.eslintrc.json` file, mostly turning errors into warnings. After upgrading to Nx 11 this warnings are now back to being errors, even though the overrides in the root file still exist.
This is not true for all rules, overriding i.e. `@typescript-eslint/no-explicit-any` from the root file works. Overriding `max-len` however does not work, even though it is probably one of the options which is used consistently throughout all projects in a workspace most.
I understand that this most likely has to do with the new way how the eslint-files are organized and extend each other. 

## Expected Behavior
I would want to have the option to specify ESLint rules on a global level, so that they apply for all projects / libraries in that workspace.
Managing and maintaining the same overrides for some rules can become tedious and extremely annoying to maintain in a big repository with lots of apps and libs.

## Steps to Reproduce
I created a repro [here](https://github.com/tommueller/tslint-rule-repro). You can see that I am overriding the rules for both `@typescript-eslint/no-explicit-any` and `max-len` in the root `eslintrc.json`. Running `npm run lint` you will see, that the change to `no-explicit-any` is kept from the file, whereas the change to `max-len` is not persisted.

### Environment
<pre><code>  Node : 14.3.0
  OS   : linux x64
  npm  : 6.14.11
  
  nx : Not Found
  @nrwl/angular : 11.1.1
  @nrwl/cli : 11.1.2
  @nrwl/cypress : 11.1.1
  @nrwl/devkit : 11.1.1
  @nrwl/eslint-plugin-nx : 11.1.1
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.1
  @nrwl/linter : 11.1.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.1
  typescript : 4.0.5</code></pre>

**Comment by Lonli-Lokli** [comment]
It has been discussed there https://github.com/nrwl/nx/issues/4320#issuecomment-760101732 with some temporary workarounds

**Comment by tommueller** [comment]
Thanks @Lonli-Lokli for the pointer. Will close this one in favor of #4320.
