### ISSUE TITLE
Feature request: css/scss linting

### ISSUE THREAD

**Issue by adgoncal** [nrwl/nx#459]
It would be great to add css/scss linting to the lint script in addition to linting typescript. This can easily be accomplished with [sass-lint](https://github.com/sasstools/sass-lint).

Install `sass-lint`
`npm install sass-lint --save-dev`

Edit the lint script in `package.json`:

```diff
-    "lint": "ng lint --format=stylish",
+    "lint-scss": "sass-lint -v -q",
+    "lint-ts": "ng lint --format=stylish",
+    "lint": "npm run lint-ts && npm run lint-scss",
```

Finally, create a `.sass-lint.yml` file in the root of the project, see sample:
https://github.com/sasstools/sass-lint/blob/6a71e29920a386fd97b986eb54ed0123890c1913/docs/sass-lint.yml

Also, see available rules: 
https://github.com/sasstools/sass-lint/tree/6a71e29920a386fd97b986eb54ed0123890c1913/docs/rules

**Comment by sdurnov** [comment]
@adgoncal well, this isn't the only way to format..
I constantly see formatting TS with clang-format or tsfmt, and scss/css with stylelint.
I guess everyone can define those commands manually.
