### ISSUE TITLE
Cypress builder option "headless": true

### ISSUE THREAD

**Issue by Elif5757** [nrwl/nx#4590]
## Current Behavior

my e2e cypress builder @nrwl/cypress:cypress has the option headless: false. 
when I execute the command the cypress runner opens and i can successfully run my tests.  my tests have no errors.

when I set  headless to true I get the message: 

```
Starting type checking service...
Using 1 worker with 2048MB memory limit


  1) An uncaught error was detected outside of a test

  0 passing (584ms)
  1 failing

  1) An uncaught error was detected outside of a test:
     Error: The following error originated from your test code, not from Cypress.

  > Fetching resource at '/__cypress/tests?p=src\support\index.ts' failed

When Cypress detects uncaught errors originating from your test code it will automatically fail t
he current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
      at XMLHttpRequest.xhr.onerror (http://localhost:4200/__cypress/runner/cypress_runner.js:174
630:14)
```

## Expected Behavior

I would like to give the option headless:true for CI. 

why not here?
## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by vsavkin** [comment]
Thank you for submitting the issue. Could you provide a repo with a repro?

**Comment by Elif5757** [comment]
@vsavkin unfortunately i can't provide my repo..

our application uses nx and angular
i write my cypress tests in cucumber, typescript
I can start the tests without any problems and run them without errors. even if i start it in watch mode i didn't get any errors.

for the CI I have to start my tests in headless mode if I do that with e.g nx e2e md-e2e --headless my tests are failed. don't know why. i get the message:

Starting type checking service...
Using 1 worker with 2048MB memory limit

1) An uncaught error was detected outside of a test

0 passing (565ms)
1 failing

1) An uncaught error was detected outside of a test:
Error: The following error originated from your test code, not from Cypress.

```
Fetching resource at '/__cypress/tests?p=src\support\index.js' failed

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
at XMLHttpRequest.xhr.onerror (https://localhost.applicationname.de:8443/__cypress/runner/cypress_runner.js:17460
2:14)

```
don't understand why the support index.js is not fetching. 
especially if I had implemented it incorrectly, the watch mode would also fail

cypress.json: `{
    "fileServerFolder": ".",

    "fixturesFolder": "./src/fixtures",

    "integrationFolder": "./src/integration",

    "modifyObstructiveCode": false,

    "pluginsFile": "./src/plugins/index",

    "supportFile": "./src/support/index.js",

    "testFiles": "**/*.feature",

    "video": true,

    "videosFolder": "../../dist/cypress/apps/xxx/videos",

    "screenshotsFolder": "../../dist/cypress/apps/xxx/screenshots",

    "chromeWebSecurity": false
}`


src/support/index.js: 
`
import './commands'

import '@cypress/code-coverage/support'
`

my folder structure shows: 
![image](https://user-images.githubusercontent.com/62025022/106124381-51f71e80-615b-11eb-8afa-4eeed68a17fe.png)

**Comment by KamilSocha91** [comment]
@Elif5757 Did you tried running server first (boot-cypres-server){https://docs.cypress.io/guides/guides/continuous-integration.html#Boot-your-server}

**Comment by Elif5757** [comment]
@KamilSocha91 of course

**Comment by Elif5757** [comment]
same issue is here -> https://github.com/cypress-io/cypress/issues/14360

**Comment by Elif5757** [comment]
> Thank you for submitting the issue. Could you provide a repo with a repro?

https://github.com/Elif5757/cypress-test

**Comment by Elif5757** [comment]
https://github.com/Elif5757/cypress-test

**Comment by Elif5757** [comment]
the solution: https://stackoverflow.com/questions/58374064/use-feature-files-in-cypress-with-nrwl-nx
