### ISSUE TITLE
Implicit Dependencies by Tag

### ISSUE THREAD

**Issue by DominikB2014** [nrwl/nx#4598]
## Description
From my understanding, currently implicit dependencies can define a dependency between a file, project, or glob pattern to another project. It would be useful if a these dependencies could be made to a tag.
For example
```
"implicitDependencies": {
    "package.json": ["scope:node"],
    "requirements.txt": ["scope:python"]
}
```
The assumption here is that a project cannot contain the same name as a tag. This could be seen as a breaking change if a workspace already has a tag with the same name as a project.

## Motivation
The main motivation is to improve the technology agnostic status of NX. The example above shows how only node apps depend on the root level package.json, and python apps depend on requirements.txt
However I'm sure there are more use cases I have not thought of.

## Suggested Implementation
Assume `"package.json": ["scope:node"]`
If package.json is modified, find all projects with the tag `scope:node`, treat those apps as affected

If this is agreed to be a useful feature, I would be happy to contribute.

**Comment by jaypea** [comment]
this would actually be an awesome feature, also on a project,json level
