### ISSUE TITLE
Error when trying to create a new workspace

### ISSUE THREAD

**Issue by m0t0r** [nrwl/nx#46]
Hey guys, thanks a lot for the project! 

I am trying to setup a workspace following the official docs but getting an error:

```
➜  WebstormProjects ng new myprojectname --collection=@nrwl/schematics
Cannot find module '@angular-devkit/schematics'
Error: Cannot find module '@angular-devkit/schematics'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/m0t0r/.nvm/versions/node/v8.6.0/lib/node_modules/@nrwl/schematics/src/application/index.js:11:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```
Additional information:
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.5.0-beta.4
node: 8.6.0
os: darwin x64
```

**Comment by vsavkin** [comment]
Have you used this script:

```
curl -fsSL https://raw.githubusercontent.com/nrwl/nx/master/packages/install/install.sh | bash -s myprojectname
```

Or yarn?

**Comment by m0t0r** [comment]
Hi Victor,

The script works perfectly. I used npm to install packages globally and then tried to generate a new workspace and that's when I was getting that error. I guess npm has trouble with peerDependecies.

**Comment by m0t0r** [comment]
Hi Victor,

The script works perfectly. I used npm to install packages globally and then tried to create a new workspace and that's when I was getting that error. I guess npm has some trouble with peerDependecies.

**Comment by vsavkin** [comment]
Exactly! Global npm peer dependencies are problematic (basically broken). 

You can use `yarn` or the script, both of those should work. 

Hans Larsen from the Angular team is working on making it easier, but there is nothing on the nx side we can do. 

Closing this.
