### ISSUE TITLE
Add fire and forget helper for Nx Devkit executors

### ISSUE THREAD

**Issue by ashwinGokhale** [nrwl/nx#4603]
## Description

I would like to have a helper function in @nrwl/devkit that will allow users to create an executor that will start a task in the background, but still proceed to run the next executor.

## Motivation

When running Cypress tests, I want to serve from the dist folder, so I am creating an executor to start a static file server and adding it as a `devServerTarget` to `projects.my-project.targets.e2e.options`. I want to be able to start the file server in the background run the Cypress tests, and then stop both once the tests are completed, but also I want to be able to run the file server executor as a standalone executor. If it is running as a standalone executor, then I would want it to serve until I kill the process, but if I run it from the Cypress `devServerTarget`, then I would want it to start in the background and continue to the cypress executor and only kill the process once the Cypress process is killed.

## Suggested Implementation

In `@angular-devkit/architect`, you have the `scheduleTargetAndForget` function, but I don't know how it would be possible to start a server in the background and continue to the next executor.

**Comment by vsavkin** [comment]
You could wrap `runExecutor` in a setTimeout, like this:

```
  setTimeout(async () => {
    for await (const output of await runExecutor<{
      success: boolean;
    }>(
      { project, target, configuration },
      opts
      context
    )) {
      if (!output.success)
        throw new Error('Could not compile application files');
    }
  }, 0)
```

You could also convert the iterable into an observable if you need status updates from the executor.

Does it solve your problem?

**Comment by ashwinGokhale** [comment]
I guess in my case it doesn't exactly work because I need to fire and forget an express server, not another executor. For my use case, an Observable would be a better fit than an async iterable because I need to emit multiple values over time. The way that I solved it is by using the Angular devkit. I'm not sure how I would be able to replace Angular devkit with Nx devkit in this case. I couldn't find any docs on how to run Nx devkit with an Observable.


tools\executors\file-server\builder.js:
```javascript
const path = require('path');
const http = require('http');
const express = require('express');
const { Observable } = require('rxjs');
const { createBuilder } = require('@angular-devkit/architect');
const { readWorkspaceConfig } = require('@nrwl/workspace');

const builder = createBuilder((options, context) => {
  const workspaceJson = readWorkspaceConfig({ format: 'nx' });
  const targets = workspaceJson.projects[context.target.project].targets;
  const outputPath = options.outputPath || targets.build.options.outputPath;
  if (!outputPath) {
    throw new Error(
      `Could not resolve an output path for project: ${context.target.project}. Please add the --outputPath flag or add and outputPath to the build options.`
    );
  }

  const baseHref = options.baseHref || targets.build.options.baseHref || '/';
  const dist = path.resolve(outputPath);
  const port = options.port || targets.serve.options.port || 4200;

  const app = express();

  app.use(baseHref, express.static(dist));
  app.get('*', (req, res) => res.sendFile(path.join(dist, 'index.html')));
  const server = http.createServer(app);

  return new Observable((obs) => {
    server.on('error', (error) => {
      context.logger.error(`[file-server] error: ${error.message}`);
      obs.error(error);
    });

    server.listen(port, () => {
      context.logger.info(`[file-server] Listening on port: ${port}`);
      obs.next({ success: true });
    });

    const teardown = () => {
      context.logger.info('[file-server] Stopping file server');
      server.close();
      obs.complete();
    };

    process.on('exit', teardown);

    return teardown;
  });
});

module.exports = { default: builder };

```

**Comment by quicksilverr** [comment]
Is there another way to do this using nx devkit?
