### ISSUE TITLE
Using environment variables in `run-commands`

### ISSUE THREAD

**Issue by blitzmann** [nrwl/nx#4606]
## Current Behavior

I'm attempting to run commands that utilize environment variables as arguments in the `run-commands` builder, but the environment variables don't seem to be interpolated correctly. 

Example target:

```
             "echo": {
                    "builder": "@nrwl/workspace:run-commands",
                    "options": {
                        "commands": ["echo \"${TEST}\""],
                        "parallel": false
                    }
                }
```

Console output:
```
Ryan.Holmes@RYANH MINGW64 /c/gitRoot/
$ export TEST=ThisIsATestString

Ryan.Holmes@RYANH MINGW64 /c/gitRoot/
$ echo ${TEST}
ThisIsATestString

Ryan.Holmes@RYANH MINGW64 /c/gitRoot/
$ nx echo testproject

> nx run testproject:echo 
"${TEST}"
```

As you can see, it simply prints out the string and doesn't interpret any variables

As a workaround, I would be able to create a shell script that utilizes this and simply run it via the run-commands builder, but it would be nice to have this functionality built-in

## Expected Behavior

I would expect that the environment variables would be interpreted and be usable within the commands

## Steps to Reproduce
See above

### Environment
```
$ nx report

>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : 10.4.7
  @nrwl/cli : 10.3.1
  @nrwl/cypress : 10.3.1
  @nrwl/eslint-plugin-nx : 10.3.1
  @nrwl/express : 11.0.2
  @nrwl/jest : 10.3.1
  @nrwl/linter : 10.3.1
  @nrwl/nest : 10.4.7
  @nrwl/next : Not Found
  @nrwl/node : 10.3.1
  @nrwl/react : 11.0.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.1
  @nrwl/web : 11.0.2
  @nrwl/workspace : 10.3.1
  typescript : 4.0.3
```

**Comment by david-gettins** [comment]
Perhaps it would be nice if we could use environment variables in the same way we use args that way we don't have to worry about Powershell `$env:SOMETHING` or bash `$SOMETHING` or CMD `%SOMETHING%`?

**For example:**
```json
"echo": {
  "builder": "@nrwl/workspace:run-commands",
  "options": {
    "command": "echo {env.SOMETHING}",
    "parallel": false
  }
}
```

**Comment by david-gettins** [comment]
It would be a shame for this to be closed. I am still of the opinion that it would be nice to be able to use env vars as described in my earlier comment.

**Comment by getlarge** [comment]
I was currently looking at a way to achieve the same, came across that issue and tried the example @blitzmann by replacing the `echo` target by :
```json
    "echo": {
      "builder": "@nrwl/workspace:run-commands",
      "options": {
        "commands": ["echo $TEST"],
        "parallel": false
      }
    },
```
Since it worked this way, i thought i would let people know in case they land here after a google search :)

**Comment by 213edu** [comment]
> I was currently looking at a way to achieve the same, came across that issue and tried the example @blitzmann by replacing the `echo` target by :
> 
> ```json
>     "echo": {
>       "builder": "@nrwl/workspace:run-commands",
>       "options": {
>         "commands": ["echo $TEST"],
>         "parallel": false
>       }
>     },
> ```
> 
> Since it worked this way, i thought i would let people know in case they land here after a google search :)

thank you @getlarge! glad I stumbled upon your comment

**Comment by juventus18** [comment]
> I was currently looking at a way to achieve the same, came across that issue and tried the example @blitzmann by replacing the `echo` target by :
> 
> ```json
>     "echo": {
>       "builder": "@nrwl/workspace:run-commands",
>       "options": {
>         "commands": ["echo $TEST"],
>         "parallel": false
>       }
>     },
> ```
> 
> Since it worked this way, i thought i would let people know in case they land here after a google search :)

works only on *nix host.

Looking for a better solution. My local host is win but my CI build machine is *nix. Running `nx run testproject:echo ` works on one, but not the other. As a workaround I suppose I could make two targets i.e.
```
    "nix-echo": {
      "builder": "@nrwl/workspace:run-commands",
      "options": {
        "commands": ["echo $TEST"],
        "parallel": false
      }
    },
    "win-echo": {
      "builder": "@nrwl/workspace:run-commands",
      "options": {
        "commands": ["echo %TEST%"],
        "parallel": false
      }
    },
    ...
```

Seems really cumbersome, would MUCH prefer a solution as described by @david-gettins

**Comment by yitzchak-ben-ezra-ecoplant** [comment]
Just want to highlight that this can be easily solved..
see for example the `@nx-tools/nx-docker:build` package
they have this simple function:

https://github.com/gperdomor/nx-tools/blob/209cbe48784136bbc1cdc53c05ea4a7cd72169a7/packages/core/src/lib/interpolate.ts

so they just replace the `${X}` or `$X` with the values manually and that's it - it's cross platform and works on my Windows machine

I think it's a good suggestion to adopt this function here.

**Comment by hieutranagi47** [comment]
Hi,
Anyone here has any experience with envFile configuration? It seems that the nx:run-commands will load the environment file from envFile value before execute a command but it does not work for me. :(
I found it [here](https://nx.dev/packages/nx/executors/run-commands#options-playground) and [here](https://nx.dev/packages/workspace/generators/run-commands#envfile)

```
"options": {
  "commands": [
    "echo 'Loading .env.staging ...'",
    "echo Environment Value: $VITE_API_URI"
  ],
  "cwd": ".",
  "envFile": "packages/apps/solidjsexm/.env.staging",
  "parallel": false
}
```

**Comment by juventus18** [comment]
I ended up installing the `env-cmd` package and converting all my commands to look like this: `npx env-cmd --silent -x -f ./.env echo $KEY`. Works great!

**Comment by dijonkitchen** [comment]
I don't `envFile` works: https://github.com/nrwl/nx/issues/13685
