### ISSUE TITLE
NextJS - decorators do not work in libs

### ISSUE THREAD

**Issue by Bielik20** [nrwl/nx#4611]
## Current Behavior
I cannot import files with decorators from libs when using NextJS application.

## Expected Behavior
I should be able to import files using decorators from libs when using NextJS application.

## Steps to Reproduce

1. Create new NX repository

2. Create NextJS app (call it "desktop")

3. Create React lib (call it "utils")

4. Update `apps/desktop/.babelrc`:
```json
{
  "presets": ["next/babel"],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }]
  ]
}
```

5. Install `@wikia/dependency-injection` (or any other decorators based library you feel comfortable using).

6. Create following file inside:
* `apps/desktop/utils/sample-service.ts`
* `libs/utils/src/lib/sample-service.ts` (and export it in `libs/utils/src/index.ts`)
```ts
import { Injectable } from '@wikia/dependency-injection';

@Injectable()
export class SampleService {
  print() {
    console.log('works');
  }
}
```

7. At the begging of `apps/desktop/pages/index.ts` `Index` function paste:
```ts
  useEffect(() => {
    const container = new Container();
    const service = container.get(SampleService);

    service.print();
  }, []);
```

8. Test

If you import `SampleService` from 
```ts
import { SampleService } from '../utils/sample-service';
```
✅  It works with no problems.

If you import `SampleService` from
```ts
import { SampleService } from '@repo-name/utils';
```
or
```ts
import { SampleService } from '../../libs/utils/src/lib/sample-service';
```

❌  You get the error from "Failure Logs".

### Failure Logs
```
Syntax error: Support for the experimental syntax 'decorators-legacy' isn't currently enabled:

  1 | import { Injectable } from '@wikia/dependency-injection';
  2 | 
> 3 | @Injectable()
    | ^
  4 | export class SampleService {
  5 |   print() {
  6 |     console.log('works');
```

### Environment
```
  Node : 12.18.3
  OS   : darwin x64
  npm  : 6.14.6

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : 11.1.5
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : Not Found
  @nrwl/next : 11.1.5
  @nrwl/node : 11.1.5
  @nrwl/react : 11.1.5
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : 11.1.5
  @nrwl/workspace : 11.1.5
  typescript : 4.0.3
```

## My insight

My idea is that NextJS doesn't handle well files outside of **its** root folder, which is in our `apps/**`. They work well with paths so the problem is not there. I am not sure if this issue should land here or in NextJS repository, still it is more nx/monorepo specific than NextJS.

May be related: https://github.com/nrwl/nx/issues/4552

**Comment by Bielik20** [comment]
I took way more hours then I care to admit but it seems like replacing `.babelrc` with `babel.config.js` solves the issue. There are a few more gimmicks I will investigating in following weeks (hopefully). I will update this issue once I know more.

**Comment by nikita-yaroshevich** [comment]
The same issue is reproduced also for "@nrwl/gatsby". Same Steps to reproduce, decorators work fine directly in the app but fail in lib. Thanks a lot @Bielik20 !!! Your solution works perfectly

### Environment
also reproduced with Node 12 and @nrwl 11.2.5

`Node : 14.15.4
  OS   : linux x64
  npm  : 6.14.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.10
  @nrwl/cypress : 11.2.10
  @nrwl/devkit : 11.2.10
  @nrwl/eslint-plugin-nx : 11.2.10
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.10
  @nrwl/linter : 11.2.10
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.2.10
  @nrwl/react : 11.2.10
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.10
  @nrwl/web : 11.2.10
  @nrwl/workspace : 11.2.10
  typescript : 4.0.5`

**Comment by jaysoo** [comment]
There are two issues here:

1. Next.js app is not using babel config for the monorepo and individual libs.
2. The root `babel.config.json` uses a preset that conflicts with `next/babel` preset.

The workaround  is as follow:

1. Open `babel.config.json` at the root and remove `"@nrwl/web/babel"` from the presets .
2. Add `"@nrwl/web/babel"` preset to all React libs in the workspace.
3. Open the `next.config.js` file and change the babel loader to use `rootMode: 'upward'`.
    e.g.
    ```
    const withNx = require('@nrwl/next/plugins/with-nx');

    module.exports = withNx({
      webpack: (config, { defaultLoaders }) => {
        defaultLoaders.babel.options.babelrc = true;
        defaultLoaders.babel.options.rootMode = 'upward';
        return config;
      },
    });
    ```
4. Open  `.babelrc` for the next app and add the decorator plugin:
    e.g.
    ```
    {
      "presets": ["next/babel"],
      "plugins": [
        ["@babel/plugin-proposal-decorators", { "legacy": true }]
      ]
    }
    ```

We'll fix the setup in the next version of Nx.

**Comment by jaysoo** [comment]
Here's an example  https://github.com/jaysoo/acme-next

**Comment by Bielik20** [comment]
Yeah, I think you aimed to solve it in a very elegant way, sadly new problems stem from this solution:
* https://github.com/nrwl/nx/issues/5027
* https://github.com/nrwl/nx/issues/5032

I am posting it here so that people know what is going on.

**Comment by Bielik20** [comment]
In recent updates there was a regression and plugins from base `babel.config.json` do not apply to application `.babelrc`. Example:

* [base](https://github.com/Bielik20/ts-libs/blob/ddfc01ffd88be1e9c025e6cbfcb152262f851353/babel.config.json#L3-L6)
* [app](https://github.com/Bielik20/ts-libs/blob/ddfc01ffd88be1e9c025e6cbfcb152262f851353/apps/react-demo/.babelrc#L3)

Were I to remove plugins from app it would stop working.
