### ISSUE TITLE
Typescript decorators do not function in NX workspace webcomponents

### ISSUE THREAD

**Issue by herrKlein** [nrwl/nx#4614]
## Current Behavior

I created the NX workspace for webcomponents.
Using the polymer3 library I created 2 components with and without using the decorators.
The webcomponents with the decorated properties do not set the property values from the attribute.

## Expected Behavior
Same functionality with or without properties. I tested these webcomponents in a pure typescript build (rollup). The decorated properties do work there.

## Steps to Reproduce
The following repro reproduces this issue.
[https://github.com/herrKlein/polydeco](https://github.com/herrKlein/polydeco)
Its a minimal webcomponents NX repro setup. With 2 imported polymer3 webcomponents.
The one with the decorators does not set the property expectedLength on the webcomponent.

### Environment

 nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : 11.1.5
  @nrwl/workspace : 11.1.5
  typescript : 4.0.5

I tried a few configurations with the new 'options' in the babel.config.json preset, but none of them works. 
```
{
  "presets": [
    ["@nrwl/web/babel", {
      "decorators": { "legacy": true },
      "classProperties": { "loose": true }
    }]
  ],
  "babelrcRoots": ["*"]
}
```
I tried to 'remove' babel from the build, trying to use only typescript build. That failed. 
I also setup a new NX with the opensource template, that one doesn't use babel, but couldn't create an application. 

The project involves a library of polymer3 components which I want to convert to Lit components from within NX. Seems that also the lit components have some difficulty with Babel/Typescript decorators. Besides this problem, NX is a really great solution, we use it for react/angular projects. Hopefully this can be fixed to use with webcomponents.

**Comment by kvernon** [comment]
Is there any resolution over this? Our repos currently require decorators, and I've been working on converting to using this monorepo strategy. I'd hate to go try something else. (We use nestjs & typescript if that helps).

**Comment by cmddavid** [comment]
You can get the Lit decorators to work by updating your tsconfig in the web-components app generated with @nrwl/web:

`
    "target": "es2019",
    "module": "es2015",
    "moduleResolution": "node",
    "lib": ["es2019", "dom"],
    "declaration": true,
    "declarationMap": true,
    "experimentalDecorators": true,
    "useDefineForClassFields": false,
`

I'm not 100% sure you need all these settings, but I copied them over from a freshly generated Lit project and verified it to be working with a @nrwl/web app.
