### ISSUE TITLE
Unable to load *.env in Angular application

### ISSUE THREAD

**Issue by tafax** [nrwl/nx#4618]
## Current Behavior
Serving an Angular app using `nx serve` doesn't load any `*.env` file under `apps/my-angular-app`.

## Expected Behavior
Environment variable like `NX_*` should be replaced in the code. I would expect a behavior similar to the `Webpack DefinePlugin`. So, by defining a global variable you will be able to use it in the code by injecting it at compile time.

## Steps to Reproduce
* `nx generate @nrwl/angular:application myapp`
* create a `.env` under `myapp` with `NX_TEST='loving nx'`
* create a `env.d.ts` near the main with `declare const NX_TEST: string;`
* add `env.d.ts` to `tsconfig.app.json` in the include property
* update the `main.ts` to `console.log` the environment variable above
* `nx serve`

### Failure Logs
```
Unhandled Promise rejection: NX_TEST is not defined ; Zone: <root> ; Task: null ; Value: ReferenceError: NX_TEST is not defined
    at main.ts:31
    at Generator.next (<anonymous>)
    at tslib.es6.js:76
    at new ZoneAwarePromise (zone-evergreen.js:960)
    at Module.__awaiter (tslib.es6.js:72)
    at bootstrap (main.ts:24)
    at Object.aKaQ (main.ts:62)
    at __webpack_require__ (bootstrap:79)
    at Object.0 (main.js:11)
    at __webpack_require__ (bootstrap:79) ReferenceError: NX_TEST is not defined
    at http://localhost:4200/main.js:579:25
    at Generator.next (<anonymous>)
    at http://localhost:4200/vendor.js:72093:71
    at new ZoneAwarePromise (http://localhost:4200/polyfills.js:1055:33)
    at Module.__awaiter (http://localhost:4200/vendor.js:72089:12)
    at bootstrap (http://localhost:4200/main.js:572:33)
    at Object.aKaQ (http://localhost:4200/main.js:601:1)
    at __webpack_require__ (http://localhost:4200/runtime.js:80:30)
    at Object.0 (http://localhost:4200/main.js:11:18)
    at __webpack_require__ (http://localhost:4200/runtime.js:80:30)
```

### Environment
```
  nx : Not Found
  @nrwl/angular : 11.1.5
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : 11.1.5
  @nrwl/next : Not Found
  @nrwl/node : 11.1.5
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.5
  typescript : 4.0.5
```

**Comment by brandonroberts** [comment]
This is not supported in Angular applications themselves, but is available through run-commands, and other areas with the Nx CLI. You should the `environments` if you need environment specific application variables

**Comment by tafax** [comment]
Thanks for the reply, I know Angular doesn't work out of the box with a "filesystem" env. I can accomplish it using the custom webpack builder and the define plugin, but in the doc, I didn't find any reference related to the fact it is not supposed to work in Angular, so I wrongly thought you guys implemented something to support it. My fault.

**Comment by brandonroberts** [comment]
@tafax good point. Would you like to put in a PR to add that clarification?

**Comment by tafax** [comment]
@brandonroberts Sorry for the late response.
To support it, we need to introduce a dependency to a tool like https://github.com/just-jeb/angular-builders by default for Nx. This also leads to the version of Angular that Nx can support and so on. Do you think it is still a good idea?
