### ISSUE TITLE
Css/Scss modules do not generate human readable name

### ISSUE THREAD

**Issue by shlajin** [nrwl/nx#4623]
Human-readable class names helps a lot during development, and I cannot make them work with nx@10 and nx@11.

## Current Behavior
Consider this code sample:

```
import styles from './styles.module.scss'
...
      <div className={styles.myClass}>
        <h1>Hey</h1>
      </div>
...
```

The emitted code is:
```
<div className="PlTsSCcWAII8G85OosB_0"><h1>Hey</h1></div>
```

it's impossible to tell what from which class these styles come from.

## Expected Behavior
It would be so helpful it the class name can be something meaningful. In my past experience I've seen readable generated class names, such as `[filename]__[classname]__[hash]`.
In this example it could be something like
```
<div className="styles-module-scss__myClass__dfj318dja"><h1>Hey</h1></div>
```

### Environment
I'm using a react app.

```
  Node : 14.15.0
  OS   : darwin x64
  npm  : 6.14.8

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.1.5
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : 11.1.5
  @nrwl/workspace : 11.1.5
  typescript : 4.0.5
```

**Comment by quolpr** [comment]
I hope it would be helpful; here how it is done in CRA:

https://github.com/facebook/create-react-app/blob/39689239c18a1d77fb303e285b26beb1a4b650c0/packages/react-scripts/config/webpack.config.js#L526

https://github.com/facebook/create-react-app/blob/39689239c18a1d77fb303e285b26beb1a4b650c0/packages/react-dev-utils/getCSSModuleLocalIdent.js

**Comment by bekos** [comment]
@quolpr I have seen that...I still doubt though if we should keep only the hashes in production or not? cra seems to make no distinction 🤔

**Comment by shlajin** [comment]
I can confirm that CRA emits readable module class names in production bundles.
Hashing names theoretically can reduce bundle size, if class name hashes kept to somewhat tiny. WIth gzip on it'll be neglectable, though, and as almost every server and every browser has gzip features on I don't think the distinction worth the hassle.

**Comment by bekos** [comment]
thx @shlajin. I have already sent a PR for this: https://github.com/nrwl/nx/pull/4629

**Comment by shlajin** [comment]
@bekos Awesome, thank you!

**Comment by bekos** [comment]
6bf245edb75ceef3c7ad5beef6e8b0a28023e22d has landed on master and it will be part of the next release. Hopefully it will solve your issue 😃

**Comment by katyapavlenko** [comment]
@bekos thank you for fixing it! When is next release is planned to be?

**Comment by shlajin** [comment]
@katyapavlenko apparently it has landed https://github.com/nrwl/nx/releases/tag/11.2.8

**Comment by katyapavlenko** [comment]
@shlajin thank you very much!
