### ISSUE TITLE
@nrwl/web:build does not work with webpack 5

### ISSUE THREAD

**Issue by ashwinGokhale** [nrwl/nx#4627]
## Current Behavior

Running `yarn nx build <project_name>` with `webpack@5.18.0` on a React app, gives the following error:
```
Unable to resolve @nrwl/web:build.
Cannot find module 'webpack/lib/dependencies/ImportDependenciesBlock'
```

## Expected Behavior
It should successfully build the React app.

## Steps to Reproduce
1. Create nx workspace with a React app.
2. Add resolutions to package.json:
```json
"resolutions": {
    "webpack": "5.18.0"
}
```
3. Run `yarn`
4. Run `yarn nx build <project_name>`

### Failure Logs

Here is the full error log:
```
Unable to resolve @nrwl/web:build.
Cannot find module 'webpack/lib/dependencies/ImportDependenciesBlock'
Require stack:
- C:\Users\user\source\project\node_modules\@nrwl\web\src\utils\third-party\cli-files\plugins\named-chunks-plugin.js
- C:\Users\user\source\project\node_modules\@nrwl\web\src\utils\third-party\cli-files\models\webpack-configs\common.js
- C:\Users\user\source\project\node_modules\@nrwl\web\src\utils\web.config.js
- C:\Users\user\source\project\node_modules\@nrwl\web\src\builders\build\build.impl.js
- C:\Users\user\source\project\node_modules\@nrwl\tao\src\shared\workspace.js
- C:\Users\user\source\project\node_modules\@nrwl\tao\src\commands\run.js
- C:\Users\user\source\project\node_modules\@nrwl\tao\index.js
- C:\Users\user\source\project\node_modules\@nrwl\cli\lib\run-cli.js
```

### Environment
```
  Node : 12.18.3
  OS   : win32 x64
  yarn : 1.22.5

  nx : Not Found
  @nrwl/angular : 11.1.2
  @nrwl/cli : 11.1.2
  @nrwl/cypress : 11.1.2
  @nrwl/devkit : 11.1.2
  @nrwl/eslint-plugin-nx : 11.1.2
  @nrwl/express : 11.1.2
  @nrwl/jest : 11.1.2
  @nrwl/linter : 11.1.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.1.2
  @nrwl/react : 11.1.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.2
  @nrwl/web : 11.1.2
  @nrwl/workspace : 11.1.2
  typescript : 4.1.3
```

**Comment by sshakil-h2** [comment]
Are there any workarounds?

**Comment by clonardo** [comment]
+1, still looks like an issue. No easy workaround as far as I see, at a quick glance.

**Comment by ChazUK** [comment]
I'm trying to implement the correct format of `@use` in SCSS with the `sass-loader` but that requires the latest version of Webpack :(

**Comment by elenasch** [comment]
This is still very much an issue, and a blocker for us to use Nx. Would love to see it make into the tools soon

**Comment by smasala** [comment]
Any updates on this?

**Comment by smasala** [comment]
One **dreadful** way around this is to download webpack 4 under an alias

```
yarn add -D webpack4@npm:webpack@4.42.0
```

Then add a `postinstall` script to move webpack 4

```
"postinstall": "mv ./node_modules/webpack4 ./node_modules/@nrwl/web/node_modules/webpack"
```

Then you can build the applications

**Comment by Jordan-Hall** [comment]
I was taking a look at this yesterday.  To fix this, NX needs to upgrade the base app to Webpack 5, which will cause some issues then remove https://github.com/nrwl/nx/blob/master/packages/web/src/utils/third-party/cli-files/plugins/named-chunks-plugin.ts this file then inside the common.ts file (https://github.com/nrwl/nx/blob/master/packages/web/src/utils/third-party/cli-files/models/webpack-configs/common.ts) and make a tweak to optimization section

**Comment by smasala** [comment]
@Jordan-Hall correct, they are currently incompatible. The only way round it to patch it or "trick" it by giving`@nrwl/web` it's own local webpack version (i.e 4).

You can either do it as stated [above(https://github.com/nrwl/nx/issues/4627#issuecomment-825797960) or you could prob do it with yarn and `Selective dependency resolutions`. See: [https://classic.yarnpkg.com/en/docs/selective-version-resolutions/](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) and [https://github.com/yarnpkg/rfcs/blob/master/implemented/0000-selective-versions-resolutions.md](https://github.com/yarnpkg/rfcs/blob/master/implemented/0000-selective-versions-resolutions.md)

**Comment by Jordan-Hall** [comment]
Are they a reason we cant upgrade the whole of NX to Webpack 5? I don't mind carrying on working on it due to a requirement for a client.

**Comment by smasala** [comment]
It's on the [roadmap](https://github.com/nrwl/nx/discussions/5475) - there are also quite a few inconsistencies with the storybook plugin too

**Comment by smasala** [comment]
Version `12.3.6` of `@nrwl/web` doesn't need the dodgy hacks for webpack 5 anymore if you use angular 12 in the same repo as the module resolutions can be removed. However, getting this error now when running e2e against a web app:

```
/node_modules/webpack/lib/Dependency.js:311
                throw new Error(
                ^

Error: module property was removed from Dependency (use compilation.moduleGraph.updateModule(dependency, module) instead)
```

**Comment by smasala** [comment]
@FrozenPandaz qq why is there a `react` label on this?

**Comment by smasala** [comment]
FYI: workaround for version `12.3.6` in the meantime and only for use with `yarn`:

```
"resolutions": {
    "**/@nrwl/web/webpack": "4.46.0",
    "**/@nrwl/web/webpack-dev-server": "3.11.2"
  },
  ```

**Comment by Bulletninja** [comment]
If i try to upgrade to webpack 5 i get this:
```
Cannot read property 'tap' of undefined
TypeError: Cannot read property 'tap' of undefined
    at /..../node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/index.js:236:65
```

which is this line: 
```
compilation.hooks.additionalTreeRuntimeRequirements.tap(
```
which is referred to here:

https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/308#issuecomment-783377198

**Comment by Kamshak** [comment]
Any news on this? With webpack5 now being the default for angular apps I just ran into this issue upgrading the workspace

**Comment by gabrielgagne** [comment]
> Version `12.3.6` of `@nrwl/web`:
> 
> ```
> /node_modules/webpack/lib/Dependency.js:311
>                 throw new Error(
>                 ^
> 
> Error: module property was removed from Dependency (use compilation.moduleGraph.updateModule(dependency, module) instead)
> at ProvidedDependency.set (/node_modules/webpack/lib/Dependency.js:311:9)
>     at iterationDependencies (/node_modules/@nrwl/web/node_modules/webpack/lib/Compilation.js:940:21)
> ```

Same problem here, fresh app created with 'nx generate @nrwl/web:app myapp'

nwrl/web 12.5.8

**Comment by camasuri** [comment]
Hi every one, 

I have the same issue, any update that can help us?

**Comment by JustusNBB** [comment]
Somehow managed to break my setup with this too (I am on NX 11), seems NX 12 allows to manually enable Webpack5
`npx nx g @nrwl/web:webpack5`

https://nx.dev/latest/react/guides/webpack-5

**Comment by ainulhassanml** [comment]
@JustusNBB after running `npx nx g @nrwl/web:webpack5` facing following error

```
Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.module.rules[3].oneOf[0].issuer has an unknown property 'test'. These properties are valid:
   object { and?, not?, or? }
   -> Logic operators used in a condition matcher.
```
any workaround to this issue?

**Comment by keshav-kishor** [comment]
after upgrading to NX 13 still getting a similar issue:
_```
Error: Unable to resolve @nrwl/web:build.
Cannot find executor 'build' in \node_modules\@nrwl\web\executors.json.
```_

any workaround for this?

**Comment by Kamshak** [comment]
I think the builder is called @nrwl/web:webpack now @keshav-kishor

**Comment by keshav-kishor** [comment]
> I think the builder is called @nrwl/web:webpack now @keshav-kishor

Thanks, @Kamshak  it worked

**Comment by tejmodi21** [comment]
Hi guys, I am able to get it replaced in project.json and it works to load the project. I am still unable to run the build. 

Error: Unable to resolve @nrwl/web:package.
Cannot find executor 'package' in /Users/DSU/nx-us-monorepo/node_modules/@nrwl/web/executors.json.

Can someone please help?

**Comment by peter-coastpay-com** [comment]
is this issue still open?  I am seeing an error like this

**Comment by stuart-clark-45** [comment]
I have the same issue with a react application :/

**Comment by hveiras** [comment]
Tested in 14.x

Executors have been renamed

"executor": "@nrwl/node:execute" -> "executor": "@nrwl/node:node"
"executor": "@nrwl/node:build" -> "executor": "@nrwl/node:webpack"

also applies for web:build -> web:webpack

see [AliYusuf95](https://github.com/AliYusuf95) reply here: https://github.com/nrwl/nx/issues/9168

**Comment by PapaStef** [comment]
This is still not working for me using `@nrwl/web:dev-server` when mapping env vars:

```ts
new webpack.EnvironmentPlugin(ENV_VAR_ALLOW_LIST)
```

I'm getting the following error:
```
ERROR in Cannot read properties of undefined (reading 'tap')
```

**Comment by jaysoo** [comment]
This has been fixed a while back. If you are still using `@nrwl/web` make sure they are pointing to `@nrwl/webpack`. There is a migration to rename this for you, but if you manually upgraded packages you may have missed it.

We only support Webpack 5 now, not Webpack 4.
