### ISSUE TITLE
nx migrate should update to latest Angular packages

### ISSUE THREAD

**Issue by Tom4U** [nrwl/nx#4632]
## Description
When running `nx migrate latest` it seems the latest updates of Angular aren't recognized as they stay at 11.0.0. Bug or feature?!

**Comment by AppleGamer22** [comment]
I saw a similar behaviour with Nest packages not being updated when running `nx migrate latest`. In my opinion, it would be more functional if the `nx` CLI would update all other relevant packages as well.

**Comment by elvirdolic** [comment]
I tried `nx migrate @nrwl/workspace --to="@angular/core@latest,@angular/cli@latest,@angular/material@latest"` but nothing happens

```
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest
Fetching @nrwl/workspace@11.2.0

>  NX  The migrate command has run successfully.

- there are no migrations to run, so migrations.json has not been created.

>  NX  Next steps:

```

**Comment by viceice** [comment]
currently it's a pain migrating all angular packages one-by-one :-/

before i could do `ng update @angular/core @angular/cli` and it updates and migrates all angular packages.

with `nx migrate` i need to do this for every package seperately. :-(

**Comment by kylecordes** [comment]
Even better... if Nx would know about the sets of Angular packages intended to be consumed with matched version sets, and help keep them aligned. Example: if you're using angular/animation, it should be the same version as core.

**Comment by juristr** [comment]
@viceice you can use `FORCE_NG_UPDATE=true ng update @angular/core`

**Comment by MarKayS** [comment]
@juristr  sadly, that does not work in Windows terminal e.g in Jetbrains IDEs terminal

**Comment by juristr** [comment]
That would mean to incorporate and maintain additional logic within our Nx migrate command...which right now is basically independent from any framework or technology.

But I totally get your points.

I'm going to close this specific issue as there's already one open where we track this. See #4575

**Comment by ajsaraujo** [comment]
In PowerShell, I was only able to set the `FORCE_NG_UPDATE` to `true` by running this command:
```
$env:FORCE_NG_UPDATE = 'true'
```

**Comment by chrisae** [comment]
I'm getting this error:

```
Invalid format version detected - Expected:[ 1 ] Found: [ 2 ]
```

which is likely due to standalone configurations in my angular.json. How to workaround that?
