### ISSUE TITLE
Nx generate package install with pnpm failed

### ISSUE THREAD

**Issue by guysenpai** [nrwl/nx#4638]
## Current Behavior

When I generate a publishable library with Nx Console I get "package install failed" because of `pnpm` which is not found
I have defined `pnpm` as workspace package manager

## Expected Behavior

`pnpm` should be found and package should be installed

## Steps to Reproduce

- Create an empty workspace with pnpm as CLI package manager `npx create-nx-workspace --pm pnpm`
- Add and initialize `@nrwl/angular` plugin `pnpm add @nrwl/angular && nx generate @nrwl/angular:init`
- Go to NX Console in VS Code and generate a publishable library 

### Failure Logs

```
⠋ Installing packages (pnpm).../bin/sh: pnpm: command not found
✖ Package install failed, see above.
UnsuccessfulWorkflowExecution [Error]: Workflow did not execute successfully.
    at ChildProcess.<anonymous> (/Users/guyconcilio.com/Devlab/Starters/afrogeeksland/node_modules/.pnpm/@angular-devkit/schematics@11.0.7/node_modules/@angular-devkit/schematics/tasks/package-manager/executor.js:109:31)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
The generator workflow failed. See above.
```

### Environment

```

  Node : 12.18.3
  OS   : darwin x64
  pnpm : 5.16.0

  nx : Not Found
  @nrwl/angular : 11.2.0
  @nrwl/cli : 11.2.0
  @nrwl/cypress : 11.2.0
  @nrwl/devkit : Not Found
  @nrwl/eslint-plugin-nx : 11.2.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.0
  @nrwl/linter : 11.2.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.0
  @nrwl/web : Not Found
  @nrwl/workspace : 11.2.0
  typescript : 4.0.5
```

**Comment by FrozenPandaz** [comment]
Sorry, I'm having trouble reproducing the issue.

I assume because you're able to run `pnpm add @nrwl/angular` that you have `pnpm` installed.

Can you please push a repo to help me reproduce the issue?

**Comment by samartomar** [comment]
I am facing the same issue.
