### ISSUE TITLE
Help with where to investigate: Long Pause after command is run tests to when the tests actually are running.

### ISSUE THREAD

**Issue by eaustin** [nrwl/nx#4647]
## Current Behavior

![image](https://user-images.githubusercontent.com/6362293/106201549-9c41c500-6186-11eb-9222-a8dde10f02f9.png)

## Expected Behavior

Tests immediately start running
### Environment

 nx : Not Found
  @nrwl/angular : 10.1.0
  @nrwl/cli : 10.1.0
  @nrwl/cypress : 10.1.0
  @nrwl/eslint-plugin-nx : 10.1.0
  @nrwl/express : Not Found
  @nrwl/jest : 10.1.0
  @nrwl/linter : 11.0.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.1.0
  @nrwl/web : Not Found
  @nrwl/workspace : 10.1.0
  typescript : 4.0.2

**Comment by vsavkin** [comment]
Sorry for the late reply.

Are you seeing the same problem when you run it twice in a row?
Are you using Nx Cloud or some home-grown version of it?

**Comment by eaustin** [comment]
We are seeing this issue when we run it twice in a row. We are not using nx cloud; rather we moved the cache for the CI to a sort of mounted drive.

However, we planning on resetting the project since we've been using NX since the beta version :) I'll open another issue if we see after the reset.
