### ISSUE TITLE
[workspace-generator] the generateFiles command only renames files 1 level deep

### ISSUE THREAD

**Issue by beeman** [nrwl/nx#4649]
## Current Behavior

When generating files using the `generateFiles` method from `@nrwl/devkit`, the files are only renamed one level deep.

## Expected Behavior

Files should be renamed at all level.

## Steps to Reproduce

I got a repro [here](https://github.com/beeman/workspace-generator-paths).

After cloning it, and running `yarn` to install the deps, you can execute the generator like so:

In the generator called `crud`, I generate a structure of various directories with some files.

<img width="394" alt="image" src="https://user-images.githubusercontent.com/36491/106349206-1e6ede00-629a-11eb-8cbc-40c0cad1c748.png">

When executing the generator, only the directories get renamed, the files in those directories not.

```
yarn workspace-generator crud product 
```

In the output you can already see the files that are off:

```
...SNIP...
CREATE libs/product/jest.config.js
CREATE libs/product/tsconfig.spec.json
CREATE libs/product/src/lib/product-create/__name__-create.component.ts
CREATE libs/product/src/lib/product-create/__name__-create.module.ts
CREATE libs/product/src/lib/product-edit/__name__-edit.component.ts
CREATE libs/product/src/lib/product-edit/__name__-edit.module.ts
CREATE libs/product/src/lib/product-list/__name__-list.component.ts
CREATE libs/product/src/lib/product-list/__name__-list.module.ts
```

### Failure Logs

No errors.

### Environment

```
>  NX  Report complete - copy this into the issue template

  Node : 14.13.1
  OS   : darwin x64
  yarn : 1.22.5
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.5
  @nrwl/cypress : Not Found
  @nrwl/devkit : 11.2.5
  @nrwl/eslint-plugin-nx : 11.2.5
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.5
  @nrwl/linter : 11.2.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.5
  @nrwl/web : Not Found
  @nrwl/workspace : 11.2.5
  typescript : 4.0.5
```

**Comment by vsavkin** [comment]
@beeman thank you for submitting the issue.

Would you be interested in submitting a PR? 

The fix has to be made in:
packages/devkit/src/generators/generate-files.ts

**Comment by beeman** [comment]
Hey @vsavkin - just sent in a PR, happy to make any adjustments if need. Mainly around the tests happy to improve things.

**Comment by beeman** [comment]
Something I saw when looking at this part of the code, it looks like [this test](https://github.com/nrwl/nx/blob/master/packages/devkit/src/generators/visit-not-ignored-files.spec.ts#L2) imports the method from the package, not from the file that sits next to it.

Is this expected? If not, I'm happy to submit a patch.

**Comment by beeman** [comment]
@FrozenPandaz thanks for merging this fix! 

Any ideas on [this test](https://github.com/nrwl/nx/blob/master/packages/devkit/src/generators/visit-not-ignored-files.spec.ts#L2)? Should this import from the package or from the file sitting next to the test?
