### ISSUE TITLE
React: add PostCSS to Webpack config

### ISSUE THREAD

**Issue by devinshoemaker** [nrwl/nx#4654]
## Description

Configure PostCSS in the Webpack config for React applications.

## Motivation

PostCSS is a powerful tool that could be useful in React applications. Tailwind is growing in popularity and that requires PostCSS to be configured, so currently the user has to override the default Webpack config to get this working. Next also has PostCSS configured, so this would provide better consistency around the React plugins that Nx provides.

## Suggested Implementation

This suggestion works well for CSS files, but does not account for SCSS or LESS files.
https://github.com/nrwl/nx/issues/3480#issuecomment-743692342

**Comment by katyapavlenko** [comment]
Have same problem!
Trying to add config now, but this approach **does not work**:
```
const nrwlConfig = require('@nrwl/react/plugins/webpack.js');

module.exports = (config) => {
  nrwlConfig(config);
  return {
    ...config,
    plugins: [...config.plugins,  require('autoprefixer')],
    module: {
      rules: [
        ...config.module.rules,
        {
          test: /\.scss$/,
          loader: 'postcss-loader'
        },
      ],
    },
  };
};

```

with error
```
Module build failed (from /Users/katyapavlenko/WebstormProjects/lawgeex-realtime-dashboard/node_modules/postcss-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
```

maybe someone has a solution?

**Comment by devinshoemaker** [comment]
@katyapavlenko I wrote a blog post on this, maybe try my version of the Webpack config https://devinshoemaker.com/blog/nx/react-tailwind

**Comment by mattgibb** [comment]
Thanks for the helpful blog post @devinshoemaker ! +1 for postcss/tailwindcss support if it's possible. Thanks for all the great tooling with Nx too!

**Comment by ZackDeRose** [comment]
Hey all, we recently added in official documentation for adding tailwind to a React app in an Nx workspace (this solution works with Next.js and web apps as well):

https://nx.dev/latest/react/guides/using-tailwind-css-in-react#using-tailwind-css-in-react

**Comment by hoangdai95** [comment]
I got `webpack.WebpackError is not a constructor` when running the `nx build app --prod` command (I am using tailwindcss + Nx React)

**Comment by keverw** [comment]
@hoangdai95 Same! Did you solve that issue yet? I'm a bit stuck, I could work on my project while dev with as far as I am now but production builds fail...
