### ISSUE TITLE
React publishable lib styles problem

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#4655]
## Current Behavior
React libraries have some issues with styles and svg files, the exported components are not rendered with styles unless you configure `extractCss=false` in the build config, but even with that change, things like `background-image: url(./logo.svg)` are not working. The components are rendered as expected inside the same workspace, but not when the library is published to npm and installed in other app

## Expected Behavior
The components should rendered as expected, with working styles in both cases (inside and in external npm installations)

## Steps to Reproduce
1. Just create a library and create a custom component
2. Update the component styles and use some svg file, as a background image for example
3. Create a demo app and use that component, run the app
4. Publish the library
5. Create a react app using create-react-app command
5. Install the published library and use the component, run the app

**Comment by pschalk** [comment]
This bug does still exist, any news on this?
