### ISSUE TITLE
Publishable React libraries' dependencies

### ISSUE THREAD

**Issue by Katona** [nrwl/nx#4660]
When executing `nx build` for a publishable library, the generated `package.json` contains all dependencies under the `peerDependencies` section which, I think, is incorrect.

## Current Behavior
Every dependency is placed under `peerDependencies` in the generated `package.json`.
## Expected Behavior
I would expect the dependencies to appear under the `dependencies` section in the `package.json`.

## Steps to Reproduce
Here is a repo: https://github.com/Katona/publishable-react-library
Build the `test-library` and check the results in `dist/libs/test-library`.

### Environment
  Node : 12.14.1
  OS   : win32 x64
  npm  : 6.13.4

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.0
  @nrwl/cypress : 11.2.0
  @nrwl/devkit : 11.2.0
  @nrwl/eslint-plugin-nx : 11.2.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.0
  @nrwl/linter : 11.2.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.2.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.0
  @nrwl/web : 11.2.0
  @nrwl/workspace : 11.2.0
  typescript : 4.0.5

**Comment by dangviettuan** [comment]
I think `--buildableProjectDepsInPackageJsonType=dependencies` can help you

**Comment by Katona** [comment]
Hi @dangviettuan,

That option indeed helps, thank you. Is there a way to control which dependency ends up in which section?

**Comment by dangviettuan** [comment]
Hi @Katona,
I think you have to do it manually. Checkout the NX repository and take a look at `updateBuildableProjectPackageJsonDependencies` method, NX does not have any options to separate dependencies into 2 groups.

**Comment by Katona** [comment]
Hi @dangviettuan,

Yeah, what I did instead is use `--buildableProjectDepsInPackageJsonType=dependencies` as you suggested, this covers 99% percent of the usecases, and when a peer dependency is needed, like React in case of creating a React component library, I add that as `peerDependency` in the project's `package.json`, and Nx seems to be intelligent and separate them when the project is built. Do you see any problem with this approach?

**Comment by dangviettuan** [comment]
I found that I have missing packages in depedencies. Just install published lib and testing. After take a look about rollup, It's my mistake because rollup will bundle all thirdparty.
One more thing, I trying to package my lib and include all my libs in workspace. Because I don't want to publish too many package. Maybe nx only support publish standalone, I'm reading NX source code and still stuck 😭. But what nx has done really great.

**Comment by subhranshudas** [comment]
> I think `--buildableProjectDepsInPackageJsonType=dependencies` can help you

when do you pass this? while creating a publishable package?

**Comment by subhranshudas** [comment]
> > I think `--buildableProjectDepsInPackageJsonType=dependencies` can help you
> 
> when do you pass this? while creating a publishable package?

By doing the following-
 "updateBuildableProjectDepsInPackageJson": true,
  "buildableProjectDepsInPackageJsonType": "dependencies"

**Comment by FutuDimi** [comment]
@subhranshudas it is the config of your target (it is the build target that you are using to prepare your package for publishing) in your project, where you have to add it. E.g. if you are using the rollup executor (@nrwl/web:rollup) you have to add `"buildableProjectDepsInPackageJsonType": "dependencies"` as the other option is by default true according to the docs https://nx.dev/packages/web/executors/rollup

**Comment by subhranshudas** [comment]
> @subhranshudas it is the config of your target (it is the build target that you are using to prepare your package for publishing) in your project, where you have to add it. E.g. if you are using the rollup executor (@nrwl/web:rollup) you have to add `"buildableProjectDepsInPackageJsonType": "dependencies"` as the other option is by default true according to the docs https://nx.dev/packages/web/executors/rollup

I still have a query how do you have a setting where you can make some dependencies `peer` & some `deps`??

**Comment by FutuDimi** [comment]
> I still have a query how do you have a setting where you can make some dependencies `peer` & some `deps`??

If your config is to build with dependencies you have to add the `peerDependencies` in the `package.json` file of your package.

But in general, whatever dependency you add in the `package.json` file of your package will be the one added to your build. There will not be any duplicates and the semantic version that you added will be respected.

**Comment by subhranshudas** [comment]
> > I still have a query how do you have a setting where you can make some dependencies `peer` & some `deps`??
> 
> If your config is to build with dependencies you have to add the `peerDependencies` in the `package.json` file of your package.
> 
> But in general, whatever dependency you add in the `package.json` file of your package will be the one added to your build. There will not be any duplicates and the semantic version that you added will be respected.

I guess, thats a way to do it. So NX will know from the `package.json` &  `project.json` for which one to make `peerDependencies` or not.
