### ISSUE TITLE
NX cache ignores environment variable value changes

### ISSUE THREAD

**Issue by Timppe** [nrwl/nx#4662]
## Current Behavior
When running e.g. `nx run-many --target=build --prod --all` a second time for a react app, after changing the value for an environment variable, the build is taken from the cache and so the new environment variable is never built into the frontend code

## Expected Behavior
I would expect it to build the app again, using the new environment variable and not taking the build from the cache

## Steps to Reproduce
Sample react app, set an env variable and use it in code, build, change value of env variable, build again, see that the build comes from the cache

### Environment
nx : Not Found
@nrwl/angular : Not Found
@nrwl/cli : 10.1.0
@nrwl/cypress : 10.1.0
@nrwl/eslint-plugin-nx : 10.1.0
@nrwl/express : Not Found
@nrwl/jest : 10.1.0
@nrwl/linter : 10.1.0
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/react : 10.1.0
@nrwl/schematics : Not Found
@nrwl/tao : 10.1.0
@nrwl/web : 10.1.0
@nrwl/workspace : 10.1.0
typescript : 4.1.3

**Comment by Timppe** [comment]
I think I found the culprit myself. According to the documentation, some things will need to be manually told to NX when it tries to figure out if it can take result from cache or not. In this specific scenario, it seems to be depending on us not defining the relevant environment variables as runtimeCacheInputs: https://nx.dev/latest/react/core-concepts/computation-caching#runtime-cache-inputs

One would think NX parses through all NX_ prefixed env variables by default, but I guess not. Would that be something to consider as an improvement to NX, or is there some reason this wouldn't be a good idea?

**Comment by Timppe** [comment]
For completeness sake, if you're using .env files (any of them), those would need to be put into the implicitDependencies: https://nx.dev/latest/react/core-concepts/computation-caching#source-code-cache-inputs

**Comment by vsavkin** [comment]
Thank you for submitting the issue. 

I think it's not a bad idea to have some naming convention to include some env variables in the cache.  NX_* is a bit to generic cause we use to configure NX in CI, which should not invalidate the cache.

It's something I need to think about.

**Comment by cyrus-za** [comment]
Ideally we should be able to set that on each project target. e.g. we use prisma and need to sync our db, but if the DATABASE_URL changes it should not cache it.

**Comment by paulvidal** [comment]
Having the same problem and it was a nightmare to debug :( Anyway we can add a way to detect that the cache is stale ? right now I'm just skipping cache which is not ideal

**Comment by harshagarwal-mono** [comment]
HI I am not finding any documentation on how to use env option in run time hash inputs. Can someone give me an example on how to use env files
