### ISSUE TITLE
ng g lib error 

### ISSUE THREAD

**Issue by Yonet** [nrwl/nx#467]
Testing new: "@nrwl/nx": "2.0.0-alpha.2"

Repro: https://github.com/nrwl/nx-tests
```
ng g lib shared-ui
```

Error:
```
ENOENT: no such file or directory, stat '/Users/user/cdk-nx/node_modules/loggly/node_modules/request/node_modules/.bin/har-validator'
```

**Comment by run1t** [comment]
I had the same problem after doing a migration from `nx 1.0.3` to `nx 6.0.2`.
Doing: 
`rm -rf node_modules`
`npm install`

seems to solve the problem.

**Comment by thefliik** [comment]
have you tried `ng g library`?

**Comment by fandorm** [comment]
I have the same problem and am using the same workaround. Unfortunately you need to repeat the process of rm -rf and reinstalling for every new lib you want to create :(

**Comment by bcabanes** [comment]
Hi!

Closing this really old issue.
