### ISSUE TITLE
Regression in latest build with nx run-many command

### ISSUE THREAD

**Issue by damiencal** [nrwl/nx#4670]
## Current Behavior
When running `nx run-many --target=build --prod --all` console returns Cannot find module '@angular-devkit/core' for all my apps.

## Expected Behavior
Before this update the command build the apps properly.

## Steps to Reproduce
I updated  my packages:
 @nrwl/angular    11.2.6  →  11.2.7     
 @nrwl/storybook  11.2.6  →  11.2.7     
 @nrwl/cypress    11.2.6  →  11.2.7     
 @nrwl/jest       11.2.6  →  11.2.7     
 @nrwl/workspace  11.2.6  →  11.2.7 

### Failure Logs
Cannot find module '@angular-devkit/core'

### Environment

 Node : 14.15.4
  OS   : linux x64
  npm  : 6.14.11
  
  nx : Not Found
  @nrwl/angular : 11.2.7
  @nrwl/cli : 11.2.7
  @nrwl/cypress : 11.2.7
  @nrwl/devkit : 11.2.7
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.7
  @nrwl/linter : 11.2.7
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.7
  @nrwl/web : Not Found
  @nrwl/workspace : 11.2.7
  typescript : 4.1.3

**Comment by FrozenPandaz** [comment]
This should not be an issue in `11.2.10`. Can you please retry with the latest version?
