### ISSUE TITLE
Get lint error after upgraded to 11.2.7: The "directory" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by InsaLili** [nrwl/nx#4673]
## Current Behavior
When running nx lint, get the following error:
_The "directory" argument must be of type string. Received undefined_

## Expected Behavior
nx lint should pass

## Steps to Reproduce
Upgrade @nrwl/react from 10.3.1 to 11.2.7

The same error also happens when trying to upgrade 
- @nrwl/web from 11.0.15 to 11.2.7
- @nrwl/eslint-plugin-nx from 11.1.5 to 11.2.7

### Failure Logs

![lint error](https://user-images.githubusercontent.com/6998905/106592246-8e59be80-654f-11eb-8237-41b738367be8.png)

### Environment
```
>  NX  Report complete - copy this into the issue template

  Node : 14.13.0
  OS   : darwin x64
  yarn : 1.22.5
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.2.7
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.2.7
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 10.3.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : 11.2.7
  @nrwl/workspace : 11.1.5
  typescript : 4.1.2
```

**Comment by desmondpnw3dev** [comment]
> ## Current Behavior
> When running nx lint, get the following error:
> _The "directory" argument must be of type string. Received undefined_
> 
> ## Expected Behavior
> nx lint should pass
> 
> ## Steps to Reproduce
> Upgrade @nrwl/react from 10.3.1 to 11.2.7
> 
> The same error also happens when trying to upgrade
> 
> * @nrwl/web from 11.0.15 to 11.2.7
> * @nrwl/eslint-plugin-nx from 11.1.5 to 11.2.7
> 
> ### Failure Logs
> ![lint error](https://user-images.githubusercontent.com/6998905/106592246-8e59be80-654f-11eb-8237-41b738367be8.png)
> 
> ### Environment
> ```
> >  NX  Report complete - copy this into the issue template
> 
>   Node : 14.13.0
>   OS   : darwin x64
>   yarn : 1.22.5
>   
>   nx : Not Found
>   @nrwl/angular : Not Found
>   @nrwl/cli : 11.1.5
>   @nrwl/cypress : 11.1.5
>   @nrwl/devkit : 11.2.7
>   @nrwl/eslint-plugin-nx : 11.1.5
>   @nrwl/express : Not Found
>   @nrwl/jest : 11.1.5
>   @nrwl/linter : 11.2.7
>   @nrwl/nest : Not Found
>   @nrwl/next : Not Found
>   @nrwl/node : Not Found
>   @nrwl/react : 10.3.1
>   @nrwl/schematics : Not Found
>   @nrwl/tao : 11.1.5
>   @nrwl/web : 11.2.7
>   @nrwl/workspace : 11.1.5
>   typescript : 4.1.2
> ```

I had this same issue. I wiped out my node_modules and lockfile and started getting this error for the lint command only after a new npm install:
```
The "directory" argument must be of type string. Received undefined
```

I reverted back to my old lockfile which is using an older version and it works now as a temporary workaround until this is fixed.

**Comment by chrismcleod** [comment]
for me, fixed by making sure all @nrwl/_package name_ packages were at the same latest version

```
"@nrwl/cli": "11.2.12",
    "@nrwl/cypress": "11.2.12",
    "@nrwl/eslint-plugin-nx": "11.2.12",
    "@nrwl/jest": "11.2.12",
    "@nrwl/react": "11.2.12",
    "@nrwl/storybook": "^11.2.12",
    "@nrwl/tao": "11.2.12",
    "@nrwl/web": "11.2.12",
    "@nrwl/workspace": "11.2.12",
    ```

**Comment by InsaLili** [comment]
> for me, fixed by making sure all `@nrwl/_package name_ `packages were at the same latest version
> 
> ```
> "@nrwl/cli": "11.2.12",
>     "@nrwl/cypress": "11.2.12",
>     "@nrwl/eslint-plugin-nx": "11.2.12",
>     "@nrwl/jest": "11.2.12",
>     "@nrwl/react": "11.2.12",
>     "@nrwl/storybook": "^11.2.12",
>     "@nrwl/tao": "11.2.12",
>     "@nrwl/web": "11.2.12",
>     "@nrwl/workspace": "11.2.12",
>     ```
> ```

Yes, this solution works for me. Upgrade all the packages once will fix this issue. Thanks! 
Here are my package versions
```
    "@nrwl/cypress": "11.3.0",
    "@nrwl/eslint-plugin-nx": "11.3.0",
    "@nrwl/jest": "11.3.0",
    "@nrwl/react": "11.3.0",
    "@nrwl/web": "11.3.0",
    "@nrwl/workspace": "11.3.0",
```

Therefore I will close this issue.
