### ISSUE TITLE
Next Serve Prod does not build app

### ISSUE THREAD

**Issue by techgerm** [nrwl/nx#4680]
## Current Behavior

Serving a Next JS app in production mode like so `nx run next-app:serve --prod` does not build the app (see nx-example [PR](https://github.com/nrwl/nx-examples/pull/129)).

Instead I get the following error:
```
Could not start production server. Try building your app with `nx build next-app`.
```

## Expected Behavior

Next apps should build in production mode and then serve the app when running `nx run [app_name]:serve --prod` in the same way that `nx run [app_name]:serve` builds the app in development mode and serves the app.

Otherwise, what's the point of the following **default** serve configuration in `workspace.js` for Next apps which specifies a production `buildTarget`?
```
"next-app": {
  "root": "apps/next-app",
  "sourceRoot": "apps/next-app",
  "projectType": "application",
  "architect": {
	"build": {
	  "builder": "@nrwl/next:build",
	  "outputs": ["{options.outputPath}"],
	  "options": {
		"root": "apps/next-app",
		"outputPath": "dist/apps/next-app"
	  },
	  "configurations": {
		"production": {}
	  }
	},
	"serve": {
	  "builder": "@nrwl/next:server",
	  "options": {
		"buildTarget": "next-app:build",
		"dev": true
	  },
	  "configurations": {
		"production": {
		  "buildTarget": "next-app:build:production",
		  "dev": false
		}
	  }
	},
	"export": {
	  "builder": "@nrwl/next:export",
	  "options": {
		"buildTarget": "next-app:build:production"
	  }
	},
	"lint": {
	  "builder": "@nrwl/linter:eslint",
	  "options": {
		"lintFilePatterns": ["apps/next-app/**/*.{ts,tsx,js,jsx}"]
	  }
	},
	"test": {
	  "builder": "@nrwl/jest:jest",
	  "outputs": ["coverage/apps/next-app"],
	  "options": {
		"jestConfig": "apps/next-app/jest.config.js",
		"passWithNoTests": true
	  }
	}
  }
}
},
```

## Steps to Reproduce

https://github.com/nrwl/nx-examples/pull/129

### Environment

  Node : 12.13.0
  OS   : win32 x64
  npm  : 6.12.0
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : 11.1.5
  @nrwl/next : 11.1.5
  @nrwl/node : 11.1.5
  @nrwl/react : 11.1.5
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : 11.1.5
  @nrwl/workspace : 11.1.5
  typescript : 4.0.5

**Comment by kirjai** [comment]
thanks for opening the issue @germanp173 ! 

behaviour as it is right now just mirrors the behaviour you get from Next. You're right in that we could perhaps be smarter about this and run the build for you, if there isn't one. 

I'm going to mark it as a feature request instead of a bug, since it's working as intended, but could be improved, as you suggest.

**Comment by germanp173** [comment]
@kirjai thanks for getting back to me and that makes sense 👍

**Comment by alexantom** [comment]
@kirjai any update on this ?

Do you also have documentation around nextjs custom server for production deployment using nx

currently, in production deployment (not in vercel) this is what i'm doing
```
nx serve appname
```
appname/project.json
```
"serve": {
      "executor": "@nrwl/next:server",
      "options": {
        "buildTarget": "appname:build",
        "dev": true,
        "customServerPath": "../../server.js",
        "port": 3000
      },
      "configurations": {
        "production": {
          "buildTarget": "appname:build:production",
          "dev": false
        }
      }
    }
```
