### ISSUE TITLE
nx g generic-package:ng-add only supports packages with no special characters

### ISSUE THREAD

**Issue by BensonBen** [nrwl/nx#4688]
## Current Behavior
Any attempt to use the wrapped `ng add` schematic by `nx g my-package:ng-add` results in an error *IF* the package has a `-` character in the package name.

(details of error below).

## Expected Behavior
Should effectively run as `ng add my-package` but does not.
Current example from the NX website is [here](https://nx.dev/latest/angular/getting-started/cli-overview)

## Steps to Reproduce
```
npm i @angular/youtube-player
nx g @angular/youtube-player:ng-add

Alternatively

npm i lodash-es
nx g lodash-es:ng-add
```

### Failure Logs
```
nx g lodash-es:ng-add
Unable to resolve lodash-es:ng-add.
The "path" argument must be of type string. Received undefined
```

### Environment
```
Node Version: 14.15.4
NPM Version: 6.14.11

Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-65-generic
OS Type: 64-bit
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 31.3 GiB of RAM
```

**Comment by FrozenPandaz** [comment]
As far as I can see, neither `@angular/youtube-player` nor `lodash-es` have schematics so you don't need to do `nx g package:ng-add`. I don't believe it has anything to do with the `-`.

I see the error isn't clear though so we can improve that. We should probably throw an error when trying to generate a schematic from a collection that doesn't exist.

e.g.
```sh
nx g @angular/youtube-player:ng-add
ERROR: @angular/youtube-player does not have any generators.
```

**Comment by BensonBen** [comment]
yup, that's kinda what I figured was occurring but the error made it sound like something else was going on.

This fix works for me
