### ISSUE TITLE
"contains invalid WIN32 path characters" when execute the command npx create-nx-workspace

### ISSUE THREAD

**Issue by alvarosinmarca** [nrwl/nx#4690]
## Current Behavior
When try create a new project with Angular + SASS + ESLint + NxCloud/Not NxCloud with `npx create-nx-workspace`

## Expected Behavior
Create a new project sucessfully

## Steps to Reproduce
npm install -g @nrwl/cli@latest
npm i -g @nrwl/workspace@latest
npm install -g @nrwl/angular@latest
npm install -g @angular/cli@latest
npm install -g nx@latest
npx create-nx-workspace@latest
E:>npx create-nx-workspace@latest
? Workspace name (e.g., org name) empresa
? What to create in the new workspace angular [a workspace with a single Angular application]
? Application name tienda
? Default stylesheet format SASS(.scss) [ http://sass-lang.com ]
? Default linter ESLint [ Modern linting tool ]
? Use Nx Cloud? (It's free and doesn't require registration.) No

### Failure Logs
E:\>npx create-nx-workspace@latest
? Workspace name (e.g., org name)     empresa
? What to create in the new workspace angular           [a workspace with a single Angular application]
? Application name                    tienda
? Default stylesheet format           SASS(.scss)  [ http://sass-lang.com   ]
? Default linter                      ESLint [ Modern linting tool ]
? Use Nx Cloud? (It's free and doesn't require registration.) No
Creating a sandbox with Nx...
new empresa --no-interactive --preset=angular --appName=tienda --style=scss --linter=eslint --no-nxCloud --collection=@nrwl/workspace
CREATE empresa/nx.json
CREATE empresa/package.json
CREATE empresa/README.md
CREATE empresa/tools/generators/.gitkeep
CREATE empresa/tools/tsconfig.tools.json
CREATE empresa/tsconfig.base.json
CREATE empresa/.editorconfig
CREATE empresa/.gitignore
CREATE empresa/.prettierignore
CREATE empresa/.vscode/extensions.json
CREATE empresa/angular.json
CREATE empresa/.prettierrc
CREATE empresa/decorate-angular-cli.js
CREATE empresa/apps/.gitkeep
CREATE empresa/libs/.gitkeep
\E:\empresa contains invalid WIN32 path characters.
npm ERR! code 1
npm ERR! path C:\Users\ALVARO~1\AppData\Local\Temp\tmp-123440MhKDe8Wa3am
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c tao new empresa --no-interactive --preset=angular --appName=tienda --style=scss --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=angular --nxWorkspaceRoot=\E:/\

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alvaroheavy\AppData\Local\npm-cache\_logs\2021-02-03T13_01_18_000Z-debug.log
(node:12344) UnhandledPromiseRejectionWarning: Error: Command failed: npx tao new empresa --no-interactive --preset=angular --appName=tienda --style=scss --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=angular --nxWorkspaceRoot=\"E:/\"
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at createApp (C:\Users\alvaroheavy\AppData\Local\npm-cache\_npx\505743838affa773\node_modules\create-nx-workspace\bin\create-nx-workspace.js:380:21)
    at C:\Users\alvaroheavy\AppData\Local\npm-cache\_npx\505743838affa773\node_modules\create-nx-workspace\bin\create-nx-workspace.js:97:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:12344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12344) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Environment

**Global packages npm:**
@angular-devkit/core	11.1.2
@angular/cli	11.1.2
@ionic/cli	6.12.4
@nrwl/angular	11.2.9
@nrwl/cli	11.2.9
@nrwl/workspace	11.2.9
capacitor-resources	2.0.5
cordova-res	0.15.3
cordova	9.0.0
native-run	1.3.0
node-dev	6.2.0
npm-gui	2.1.0
npm-server	0.0.1
npm	7.5.2
nx	11.2.9

Operating System: Windows Enterprise 10 x64
Processors: Intel i7 4770k
Memory: 16 GiB of RAM

### Notes
I tried different drives and different routes.

**Comment by sky0matic** [comment]
Same thing happening here.

Tried with : 
- `empty` preset
- `react + express` preset
- removing the `_` I had in the path

Tried from :
- `Node.js command prompt`
- `Git Bash`

Nothing works.

### Environment
`node -v` : `14.15.3`
`npm -v` : `7.5.2`

Windows 10 Pro x64 20H2 (19042.746)

**Comment by alvarosinmarca** [comment]
I updated all global packages and node and now exist other similar error with the path: **EINVAL: invalid argument, mkdir 'C:\C:\empresa**

### Failure Logs
C:\>npx create-nx-workspace
? Workspace name (e.g., org name)     empresa
? What to create in the new workspace angular           [a workspace with a single Angular application]
? Application name                    tienda
? Default stylesheet format           SASS(.scss)  [ http://sass-lang.com   ]
? Default linter                      ESLint [ Modern linting tool ]
? Use Nx Cloud? (It's free and doesn't require registration.) No
Creating a sandbox with Nx...
new empresa --no-interactive --preset=angular --appName=tienda --style=scss --linter=eslint --no-nxCloud --collection=@nrwl/workspace
CREATE empresa/nx.json
CREATE empresa/package.json
CREATE empresa/README.md
CREATE empresa/tools/generators/.gitkeep
CREATE empresa/tools/tsconfig.tools.json
CREATE empresa/tsconfig.base.json
CREATE empresa/.editorconfig
CREATE empresa/.gitignore
CREATE empresa/.prettierignore
CREATE empresa/.vscode/extensions.json
CREATE empresa/angular.json
CREATE empresa/.prettierrc
CREATE empresa/decorate-angular-cli.js
CREATE empresa/apps/.gitkeep
CREATE empresa/libs/.gitkeep
**EINVAL: invalid argument, mkdir 'C:\C:\empresa'**
npm ERR! code 1
npm ERR! path C:\Users\ALVARO~1\AppData\Local\Temp\tmp-219289jPyM5L1q0v6
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c tao new empresa --no-interactive --preset=angular --appName=tienda --style=scss --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=angular --nxWorkspaceRoot=\C:/\

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alvaroheavy\AppData\Local\npm-cache\_logs\2021-02-05T09_06_05_047Z-debug.log
(node:21928) UnhandledPromiseRejectionWarning: Error: Command failed: npx tao new empresa --no-interactive --preset=angular --appName=tienda --style=scss --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=angular --nxWorkspaceRoot=\"C:/\"
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at createApp (C:\Users\alvaroheavy\AppData\Local\npm-cache\_npx\d2207cf76adb22dc\node_modules\create-nx-workspace\bin\create-nx-workspace.js:380:21)
    at C:\Users\alvaroheavy\AppData\Local\npm-cache\_npx\d2207cf76adb22dc\node_modules\create-nx-workspace\bin\create-nx-workspace.js:97:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Environment
#### Global packages npm:
@angular-devkit/core 11.1.3
@angular/cli 11.1.3
@ionic/cli 6.12.4
@nrwl/angular 11.2.10
@nrwl/cli 11.2.10
@nrwl/workspace 11.2.10
capacitor-resources 2.0.5
cordova-res 0.15.3
cordova 9.0.0
native-run 1.3.0
node-dev 6.2.0
npm-server 0.0.1
npm 7.5.2
nx 11.2.10
typescript 2.9.2

node -v 14.15.4
npm -v 7.5.2

**Comment by Kwandes** [comment]
I have encountered the same issue when running `npx create-nx-workspace@latest clock`

Tried from:
- Command prompt
- Powershell

- following paths:
  - X:\Programming\testing\
  - O:\Programming\testing\

Environment:
- `node`: `v15.7.0`
- `npm`: `7.4.3`
- `Windows`: WIndows 10 Pro x64 20H2 (19042.746)

#### Output:
```sh
❯ npx create-nx-workspace
? Workspace name (e.g., org name)     test
? What to create in the new workspace empty             [an empty workspace with a layout that works best for building apps]
? Use Nx Cloud? (It's free and doesn't require registration.) No
Creating a sandbox with Nx...
new test --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace
CREATE test/nx.json
CREATE test/package.json
CREATE test/README.md
CREATE test/tools/generators/.gitkeep
CREATE test/tools/tsconfig.tools.json
CREATE test/tsconfig.base.json
CREATE test/.editorconfig
CREATE test/.gitignore
CREATE test/.prettierignore
CREATE test/.vscode/extensions.json
CREATE test/workspace.json
CREATE test/.prettierrc
CREATE test/apps/.gitkeep
CREATE test/libs/.gitkeep
\X:\Programming\testing\test contains invalid WIN32 path characters.
npm ERR! code 1
npm ERR! path C:\Users\JanBo\AppData\Local\Temp\tmp-17188UjhzOMdyl51P
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c tao new test --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=nx --nxWorkspaceRoot=\X:/Programming/testing\

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JanBo\AppData\Local\npm-cache\_logs\2021-02-05T09_51_51_657Z-debug.log
node:child_process:682
    err = new Error(msg);
          ^

Error: Command failed: npx tao new test --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=nx --nxWorkspaceRoot=\"X:/Programming/testing\"
    at checkExecSyncError (node:child_process:682:11)
    at Object.execSync (node:child_process:719:15)
    at createApp (C:\Users\JanBo\AppData\Local\npm-cache\_npx\d2207cf76adb22dc\node_modules\create-nx-workspace\bin\create-nx-workspace.js:380:21)
    at C:\Users\JanBo\AppData\Local\npm-cache\_npx\d2207cf76adb22dc\node_modules\create-nx-workspace\bin\create-nx-workspace.js:97:29    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 15520,
  stdout: null,
  stderr: null
}
npm ERR! code 1
npm ERR! path X:\Programming\testing
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c create-nx-workspace

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JanBo\AppData\Local\npm-cache\_logs\2021-02-05T09_51_51_705Z-debug.log
```

**Comment by vltansky** [comment]
got same error running `npx create-nx-workspace --preset=angular` on windows.
Worked fine in WSL (ubuntu).

**Comment by costalvaro** [comment]
Hi, same issue on my side, with exactly the same output as @alvarosinmarca 
For an unknown reason, the folder creation is duplicating the beginning of the path ('C:\C:\workspace' instead of 'C:\workspace')

This happened with a `npx create-nx-workspace@latest --preset=empty` from git-bash.
Updated my node & npm, but didn't change anything.

Environment:

* node: v15.8.0
* npm: 7.5.2
* Windows: Windows 10 Pro x64 20H2 (19042.746)

**Comment by vltansky** [comment]
Maybe npm 7 is related.
As this error didn't happen to me on another pc with npm 6

**Comment by costalvaro** [comment]
Very good call @vltansky , that was indeed the issue!
I downgraded node to v10.16.3 and npm to 6.14.11 then it worked as usual.

While using node v10.16.3 with npm@7, the issue was still present. 
It's only when I went back to npm@6 that it worked.

**Comment by sky0matic** [comment]
Tested dowgrading only `npm` to `6.14.11` and keeping `node` to `14.15.3`, it still doesn't work.

I have some files gettings created, but after that : 

```
spawnSync C:\Windows\system32\cmd.exe ENOENT
(node:14884) UnhandledPromiseRejectionWarning: Error: Command failed: npx tao new maxl_game --no-interactive --preset=react-express --appName=game --style=scss --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=nx --nxWorkspaceRoot=\"D:/_prog\"
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at createApp (C:\Users\maxle\AppData\Roaming\npm-cache\_npx\14884\node_modules\create-nx-workspace\bin\create-nx-workspace.js:380:21)
    at C:\Users\maxle\AppData\Roaming\npm-cache\_npx\14884\node_modules\create-nx-workspace\bin\create-nx-workspace.js:97:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14884) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14884) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
```

**Comment by fxioi** [comment]
Windows 10 20H2 19042.746
Windows Power Shell v1.0
node v14.15.4 
npm 7.5.2

use #4734
then `spawnSync C:\WINDOWS\system32\cmd.exe ENOENT`

    UnhandledPromiseRejectionWarning: Error: Command failed: npx tao new testorg --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=nx --nxWorkspaceRoot="G:/project/nx-proj/demo"

I run this cmd manually.

```
PS G:\project\nx-proj\demo> npx tao new testorg --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=nx --nxWorkspaceRoot="G:/project/nx-proj/demo"
UPDATE testorg/nx.json
UPDATE testorg/package.json
UPDATE testorg/README.md
UPDATE testorg/tools/generators/.gitkeep
UPDATE testorg/tools/tsconfig.tools.json
UPDATE testorg/tsconfig.base.json
UPDATE testorg/.editorconfig
UPDATE testorg/.gitignore
UPDATE testorg/.prettierignore
UPDATE testorg/.vscode/extensions.json
UPDATE testorg/workspace.json
UPDATE testorg/.prettierrc
UPDATE testorg/apps/.gitkeep
UPDATE testorg/libs/.gitkeep

added 254 packages, and audited 255 packages in 24s
Successfully initialized git.
```

**Comment by ruekart** [comment]
node v14.15.4
npm 6.14.9

I don't know if is all npm 7 related. When I tried to create a workspace in my D unit in D:/project I've got this error:

`new workspace --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace
CREATE workspace/nx.json
CREATE workspace/package.json
CREATE workspace/README.md
CREATE workspace/tools/generators/.gitkeep
CREATE workspace/tools/tsconfig.tools.json
CREATE workspace/tsconfig.base.json
CREATE workspace/.editorconfig
CREATE workspace/.gitignore
CREATE workspace/.prettierignore
CREATE workspace/.vscode/extensions.json
CREATE workspace/workspace.json
CREATE workspace/.prettierrc
CREATE workspace/apps/.gitkeep
CREATE workspace/libs/.gitkeep
spawnSync C:\WINDOWS\system32\cmd.exe ENOENT
(node:16396) UnhandledPromiseRejectionWarning: Error: Command failed: npx tao new workspace --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=nx --nxWorkspaceRoot=\"D:/project\"
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at createApp (C:\Users\ruekart\AppData\Roaming\npm-cache\_npx\16396\node_modules\create-nx-workspace\bin\create-nx-workspace.js:380:21)
    at C:\Users\ruekart\AppData\Roaming\npm-cache\_npx\16396\node_modules\create-nx-workspace\bin\create-nx-workspace.js:97:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16396) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

But when I tried in my C unit in C:\project the workspace is created correctly with this output:

`new workspace --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace
CREATE workspace/nx.json
CREATE workspace/package.json
CREATE workspace/README.md
CREATE workspace/tools/generators/.gitkeep
CREATE workspace/tools/tsconfig.tools.json
CREATE workspace/tsconfig.base.json
CREATE workspace/.editorconfig
CREATE workspace/.gitignore
CREATE workspace/.prettierignore
CREATE workspace/.vscode/extensions.json
CREATE workspace/workspace.json
CREATE workspace/.prettierrc
CREATE workspace/apps/.gitkeep
CREATE workspace/libs/.gitkeep
npm notice created a lockfile as package-lock.json. You should commit this file.
added 249 packages from 235 contributors and audited 251 packages in 9.012s

29 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities`


Then I moved my workspace manually to my D unit and the nx cli also worked perfectly.

**Comment by fxioi** [comment]
@ruekart got a new error when i move project folder to `C:`...XD

    EINVAL: invalid argument, mkdir 'C:\C:\project\testorg'

**Comment by alvarosinmarca** [comment]
### With this versions:
@nrwl/angular 11.2.10
@nrwl/cli 11.2.10
@nrwl/workspace 11.2.10
nx 11.2.10

`In the path c:\ WORK!.`

# In others paths, this error: spawnSync C:\WINDOWS\system32\cmd.exe ENOENT:

D:\Programacion\Sinmarca>npx create-nx-workspace
? Workspace name (e.g., org name)     empresa
? What to create in the new workspace angular           [a workspace with a single Angular application]
? Application name                    tienda
? Default stylesheet format           SASS(.scss)  [ http://sass-lang.com   ]
? Default linter                      ESLint [ Modern linting tool ]
? Use Nx Cloud? (It's free and doesn't require registration.) Yes [Faster builds, run details, Github integration. Learn more at https://nx.app]
Creating a sandbox with Nx...
added 240 packages from 232 contributors and audited 241 packages in 10.654s

29 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

new empresa --no-interactive --preset=angular --appName=tienda --style=scss --linter=eslint --nxCloud --collection=@nrwl/workspace
CREATE empresa/nx.json
CREATE empresa/package.json
CREATE empresa/README.md
CREATE empresa/tools/generators/.gitkeep
CREATE empresa/tools/tsconfig.tools.json
CREATE empresa/tsconfig.base.json
CREATE empresa/.editorconfig
CREATE empresa/.gitignore
CREATE empresa/.prettierignore
CREATE empresa/.vscode/extensions.json
CREATE empresa/angular.json
CREATE empresa/.prettierrc
CREATE empresa/decorate-angular-cli.js
CREATE empresa/apps/.gitkeep
CREATE empresa/libs/.gitkeep
**spawnSync C:\WINDOWS\system32\cmd.exe ENOENT**
(node:2992) UnhandledPromiseRejectionWarning: Error: Command failed: npx tao new empresa --no-interactive --preset=angular --appName=tienda --style=scss --linter=eslint --nxCloud --collection=@nrwl/workspace/collection.json --cli=angular --nxWorkspaceRoot=\"D:/Programacion/Sinmarca\"
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at createApp (C:\Users\alvaroheavy\AppData\Local\npm-cache\_npx\d2207cf76adb22dc\node_modules\create-nx-workspace\bin\create-nx-workspace.js:380:21)
    at C:\Users\alvaroheavy\AppData\Local\npm-cache\_npx\d2207cf76adb22dc\node_modules\create-nx-workspace\bin\create-nx-workspace.js:97:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bekos** [comment]
we just released v11.2.12 which should contain the fix for this: 57c6bacfb4c33aba5abe13a742791b5b315da528. Can you please try again and let us know if this works now as expected?

**Comment by ruekart** [comment]
I tried again and now is working correctly in both of my units C and D.

**Comment by alvarosinmarca** [comment]
With v11.2.12 yes, this works in any path. 

Thank you very much to all.

**Comment by fxioi** [comment]
Windows 10 20H2 19042.746
Windows Power Shell v1.0
node v14.15.4
npm 7.5.2

```
PS D:\yananbak> npx create-nx-workspace@11.2.12
? Workspace name (e.g., org name)     sf
? What to create in the new workspace empty             [an empty workspace with a layout that works best for building a
pps]
? Use Nx Cloud? (It's free and doesn't require registration.) No
Creating a sandbox with Nx...
new sf --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace
CREATE sf/nx.json
CREATE sf/package.json
CREATE sf/README.md
CREATE sf/tools/generators/.gitkeep
CREATE sf/tools/tsconfig.tools.json
CREATE sf/tsconfig.base.json
CREATE sf/.editorconfig
CREATE sf/.gitignore
CREATE sf/.prettierignore
CREATE sf/.vscode/extensions.json
CREATE sf/workspace.json
CREATE sf/.prettierrc
CREATE sf/apps/.gitkeep
CREATE sf/libs/.gitkeep
\D:\yananbak\sf contains invalid WIN32 path characters.
npm ERR! code 1
npm ERR! path C:\Users\fuxiao\AppData\Local\Temp\tmp-13320TXTHI2dmfsKg
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c tao new sf --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=nx --nxWorkspaceRoot=\D:/yananbak\

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fuxiao\AppData\Local\npm-cache\_logs\2021-02-11T15_43_27_765Z-debug.log
(node:13320) UnhandledPromiseRejectionWarning: Error: Command failed: npx tao new sf --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=nx --nxWorkspaceRoot=\"D:/yananbak\"
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at createApp (C:\Users\fuxiao\AppData\Local\npm-cache\_npx\7c02767d5c9c4159\node_modules\create-nx-workspace\bin\create-nx-workspace.js:380:21)
    at C:\Users\fuxiao\AppData\Local\npm-cache\_npx\7c02767d5c9c4159\node_modules\create-nx-workspace\bin\create-nx-workspace.js:97:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13320) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PS D:\yananbak>
```

**Comment by howard-huo** [comment]
Seems like the issue was introduced by the change 9abdb78a4ab44c8bee1ca8fb09c763c011dc1db3 at line 422. I removed the 'win32' condition locally and successfully bypass the issue.

**Comment by sky0matic** [comment]
> we just released v11.2.12 which should contain the fix for this: [57c6bac](https://github.com/nrwl/nx/commit/57c6bacfb4c33aba5abe13a742791b5b315da528). Can you please try again and let us know if this works now as expected?

I'm sorry, but this doesn't work ..

`\D:\prog\maxl contains invalid WIN32 path characters.`

**Comment by fxioi** [comment]
npx create-nx-workspace@10.4.13

v10.4.13 WORK!

**Comment by arekbal** [comment]
How is this bug not a Critical? Can't create workspace in `G:/PROJECTS/name/` or `G:/` `C:/` or wherever. Windows it is.

**Comment by alvarosinmarca** [comment]
@arekbal update all packages to v11.2.12, this work for me and for @ruekart  in any paths

@nrwl/angular 11.2.12
@nrwl/cli 11.2.12
@nrwl/workspace 11.2.12
nx 11.2.12

**Comment by falkosch** [comment]
Another option is to use e.g. Ubuntu with the Windows Subsystem for Linux:

1. Enable WSL and install WSL's e.g. Ubuntu (v20 LTS worked for me)
2. Use nvm.sh (node version manager) to install node (v14.16.0 LTS) with npm (6.14.11)
3. Make sure you have set git's identity properties `user.email` and `user.name` (just avoids a later git error during setup of nx workspace)
4. `npm i -g create-nx-workspace@11.4.0`
5. `cd /mnt/c/where/ever/your/workspace/is`
6. `create-nx-workspace foobar`

The created nx workspace can now be found in `C:\where\ever\your\workspace\is\foobar`
