### ISSUE TITLE
Nx projects not working properly with Gitpod: IDE errors

### ISSUE THREAD

**Issue by ceefour** [nrwl/nx#4692]
As described [by Lovia Engineering](https://about.lovia.life/docs/engineering/nx/), Nx projects work well in VSCode but is problematic with Gitpod.

## Current Behavior

IDE behavior in Gitpod:

1. Cannot find module '@myorg/somelib' when `import`ing a lib
2. `Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning.ts(1219)` Even though `experimentalDecorates` is true in app's `tsconfig.app.json`

## Expected Behavior

1. Importing libs work fine in IDE
2. `tsconfig.*.json` files are read properly per app/lib

## Steps to Reproduce

1. Create a new nest monorepo using Nx
2. Generate a new nest lib
3. Import the lib with Nx
4. Open monorepo project in Gitpod
5. Project builds successfully (`yarn nx build`) however IDE shows errors

### Environment

- Gitpod
- NestJS 7.6

**Comment by trumbitta** [comment]
Leaving this here if someone gets here from Google looking for a good way to start working with Nx in Gitpod: https://github.com/trumbitta/gitpod-nx
