### ISSUE TITLE
storybook-migrate-defaults-5-to-6 angular schematic is not installed with v11.2.9

### ISSUE THREAD

**Issue by christianacca** [nrwl/nx#4694]
## Current Behavior
`storybook-migrate-defaults-5-to-6` angular schematic is not installed with v11.2.9

## Expected Behavior
According to the docs `storybook-migrate-defaults-5-to-6` should be an available generator. However, the command `nx generate @nrwl/storybook:migrate-defaults-5-to-6` fails with the following message:

```bash
Unable to resolve @nrwl/storybook:migrate-defaults-5-to-6.
Cannot find generator 'migrate-defaults-5-to-6' in C:\Git\mri-platform-ag-client-admin\node_modules\@nrwl\storybook\collection.json
```

Looking at the file system where the schematic should be installed, I don't see it:

![image](https://user-images.githubusercontent.com/886590/106807008-8b9abe80-6660-11eb-8e30-a247dcb0dca7.png)

## Steps to Reproduce

1. Create a new application (accepting any defaults). eg: `npx create-nx-workspace@latest mri-platform-ag-client-admin --preset=angular --appName=ag-admin --cli=angular --style=scss --npm-scope=mri-platform --interactive=false --nx-cloud=false`
    * **note** for me this command is now actually failing, so my steps to provide a repo is limited
2. Add storybook: `yarn add --dev @nrwl/storybook`
2. Check the content of the directory `./node_modules/@nrwl/angular/src/schematics

### Environment
* OS Name	Microsoft Windows 10 Enterprise N
* Version	10.0.19042 Build 19042
* nodejs: v15.3.0

**Comment by FrozenPandaz** [comment]
Hi, we have not released that functionality quite yet. We will soon though! :wink:

Did you perhaps find this information in the docs in this repo? Or did you find it on https://nx.dev?

The docs in this repo reflect the docs for the latest `master` commit. However, the latest version on `npm` is likely not up to date with `master`. When the feature is released on `npm`, the docsite at https://nx.dev will be updated as well.

**Comment by christianacca** [comment]
https://nx.dev/latest/angular/plugins/storybook/overview#some-info-about-the-generator

:-)

**Comment by FrozenPandaz** [comment]
Ah thanks for pointing to that. I'll look into reintroducing that for an upcoming version of `11.2.x` then :+1:
