### ISSUE TITLE
Publishable Library React Project: Root README.md publishes instead of library README.md  

### ISSUE THREAD

**Issue by lr001dev** [nrwl/nx#4698]
## Current Behavior
So when building/publishing a library, currently the README.md from the root of the project gets published instead of the project README.md

## Expected Behavior
The README.md located at project level should be published with package

## Steps to Reproduce
running nx build <project>

It's pretty simple running nx build doesn't copy readme local to the project.

### Failure Logs
none

### Environment
`Node : 12.13.0
  OS   : win32 x64

  npm  : 6.13.6

  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.2.9
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.9
  @nrwl/web : 11.2.9
  @nrwl/workspace : 11.2.9
  typescript : 4.0.5`

**Comment by dangviettuan** [comment]
Edit your `workspace.json` like below 
`"assets": [
              {
                "glob": "README.md",
                "input": "",
                "output": "."
              }
            ]
`

**Comment by lr001dev** [comment]
Any workarounds to this until this gets addressed?

**Comment by lr001dev** [comment]
So found a work around for anyone who has the same issue:

Inside workspace.json in the library configuration object, you'll see an entry for README.md the assets array ie:
`"assets": [{ 
"glob": "README.md",
"input": ".",
"output": "."
}]`

You can change the input field from `"."` to `libs/<name-of-library-directory>/` and NX will copy the readme when building your library.
