### ISSUE TITLE
Site: broken layout/illustration

### ISSUE THREAD

**Issue by akaRem** [nrwl/nx#4707]
go to https://nx.dev/latest/node/tutorial/01-create-application,

The illustration looks like 

![image](https://user-images.githubusercontent.com/1472728/106938291-13470280-671f-11eb-9968-283a664b1f40.png)

Too many `|` are prefixed with a `file` icon.

**Comment by akaRem** [comment]
... both Chrome and Safari

**Comment by akaRem** [comment]
Same here https://nx.dev/latest/node/plugins/nest/overview

**Comment by bcabanes** [comment]
Hi @akaRem! 
Thank you for reporting this issue, we'll work on a fix.

**Comment by bcabanes** [comment]
Issue has been resolved and nx.dev has been updated.
