### ISSUE TITLE
Allow running 'nx print-affected' from globally installed nx

### ISSUE THREAD

**Issue by minijus** [nrwl/nx#4710]
## Description
`nx print-affected` is commonly used in CI systems to distribute load across multiple agents/pods.
Today running `nx print-affected` requires having node_modules ready locally (`npm ci` or `yarn` finished).

Running `nx print-affected` without local node_modules throws an error:
![image](https://user-images.githubusercontent.com/3633549/107016341-8051ab00-67a6-11eb-9fe3-52e8eaa7b963.png)

## Motivation
This prevents having more efficient CI setup where `npm ci` runs in parallel to `nx print-affected` (on different agents/pods) in turn allowing to prepare CI agents while `npm install` is still running.

## Suggested Implementation
Use globally installed `nx` to run `print-affected` (if locally installed cli does not exists).
As a safety precaution version of local cli could be retrieved from lock files and verified against global version (i.e. if same major version).

**Comment by minijus** [comment]
Created a temp workaround:
https://gist.github.com/minijus/d8ddfc78cc81cc809710044a45dc4ea5

It still would be great to have `nx print-affected` available when local node_modules are not installed.

**Comment by vitorcamachoo** [comment]
This would be very useful to run on CI avoiding to install if theres no affected apps for example.

**Comment by minijus** [comment]
@FrozenPandaz would it be possible to reopen this issue?

Having global affected command is very useful to prevent or delay (run in parallel) dependency installation. This helps to optimize CI setup.

**Comment by martinmicunda** [comment]
I would have same request to be able to run global affected command, mainly for CI.

**Comment by JaydenMaalouf** [comment]
I am also interested in this.
Currently our yarn install takes about 5 minutes - which shouldn't be necessary to determine the affected apps

**Comment by sdjnes** [comment]
Also interested in this. I'm trying to create a GitHub Actions matrix based on affected projects, and want to parse the output of `npx nx print-affected` without needing to do a 1 minute `npm install`.

**Comment by pct-cclausen** [comment]
> Also interested in this. I'm trying to create a GitHub Actions matrix based on affected projects, and want to parse the output of `npx nx print-affected` without needing to do a 1 minute `npm install`.

That is exactly what lead me here

**Comment by martinmicunda** [comment]
@FrozenPandaz @vsavkin is it possible to reopen this issue as it's nice feature specially for CI

**Comment by daem0ndev** [comment]
Another bump, this is a very handy idea for speeding up large pipelines. cc: @vsavkin @FrozenPandaz 

Can we please re-open this?
