### ISSUE TITLE
Env vars passed to the index.html as in CRA

### ISSUE THREAD

**Issue by daruj** [nrwl/nx#4716]
## Description
One of the libraries that we use for tracking user events (heap) requires us to place a script in the index.html and pass a client_id to identify our app. We recently moved from CRA to NX and we could not find a way to pass an env var into the index.html. This is very important for us because we will need to use a different ID depending on each environment so it can't be hardcoded.

**Comment by christian452** [comment]
We are having the same issue with various tracking client ids and configurations.
