### ISSUE TITLE
Convert workspace.json into a directory of config files

### ISSUE THREAD

**Issue by Brian-McBride** [nrwl/nx#4720]
## Description
My team is having a lot of issues dealing with merge conflicts with the `workspace.json` file. As team members are rapidly creating libraries and apps at the start of a project, almost every PR has a merge conflict in the `workspace.json` file. 

## Motivation
Removing blockers from developers. A team will get frustrated dealing with unnecessary conflicts then quickly find "workarounds" like shoving too much stuff in one lib so they don't have to create another. This is a daily issue with my teams since I have made Nx our standard monorepo tooling. 

## Suggested Implementation
Have a `workspace` directory. Inside there can be the main index or config file with items that don't change often.
```
{
  "version": 1,
  "cli": {
    "defaultCollection": "@nrwl/nest"
  },
  "defaultProject": "my-app",
  "schematics": {
    "@nrwl/gatsby": {
      "application": {}
    }
  }
}
```
Inside is a `projects` folder that contains the name of a project. For instance `workspace/projects/common-server.json`
That might look like what we expect
```
    "common-server": {
      "root": "libs/common-server",
      "sourceRoot": "libs/common-server/src",
      "projectType": "library",
      "schematics": {},
      "architect": {
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": ["libs/common-server/**/*.ts"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "libs/common-server/jest.config.js",
            "passWithNoTests": true
          },
          "outputs": ["coverage/libs/common-server"]
        }
      }
    },
```

There are still times that a default project might conflict if two devs change that. But, that is far easier to manage than the noise a large workspace.json file takes up. 

If you can point me in the direction in the codebase where the workspace.json file is parsed, I'd be happy to look at making a PR to change the behavior there.

**Comment by Brian-McBride** [comment]
I should also mention, that I am sure this also happens a bit with `nx.json`, but for some reason, I don't hear the devs complaining about the conflicts there.

**Comment by FrozenPandaz** [comment]
I agree and we actually touched on this on our [Nx 12 Roadmap](https://github.com/nrwl/nx/discussions/4645) :wink:

> For instance, currently the root configuration file can become a bit unruly when you have say 500 projects in your workspace.

We will be looking at this feature soon.

**Comment by cyrus-za** [comment]
+1 this is going to NX 12 as @FrozenPandaz just said.
Also see #4888 and @vsavkin's comment there. 

I can't wait to access this in v12 as we're adding libs on a daily baiss and run into conflicts as we busy moving over our projects from an old monorepo.
