### ISSUE TITLE
Styled Components in a Storybook instance do not HMR/fast-refresh their CSS

### ISSUE THREAD

**Issue by ChristianIvicevic** [nrwl/nx#4723]
## Current Behavior

After creating a UI library and adding the Storybook configuration via `@nrwl/react:storybook-configuration` to that library I noticed that changes to the components are only partially HMRed/fast-refreshed. In particular when changing the JSX of a component it updates as expected, but changing a styled component does not reflect changes to the CSS and requires a hard reload in the browser unlike a classical Storybook installation made without nx.

## Expected Behavior

I expect the CSS to be HMRed/fast-refreshed similar to the DOM.

## Steps to Reproduce

In order to reproduce this I attempted to create an MWE over here: https://github.com/ChristianIvicevic/nx-storybook-styled-components-repro

1. Clone the repository and install all dependencies using `yarn`.
2. Invoke `yarn nx run ui:storybook` to start the Storybook for UI library.
3. Open `http://localhost:4400/` for the Storybook instance with the default Ui/Primary story.
4. In your editor head to `libs/ui/src/lib/ui.tsx` and replace the text `Welcome to ui!` with anything. The changes are compiled and the Storybook instance refreshes the component as expected.
5. Now change the color in the styled component definition from `pink` to anything else.
6. Even though webpack clearly rebuilds the component, Storybook does not refresh and you need to reload the page manually to see the changed CSS.

Surprisingly enough, if you add the component to the available frontend project changes of all kinds are correctly propagated. My vague assumption is that the custom webpack configuration is causing issues with HMRing/fast-refreshing styled components and their CSS.

### Environment

```
  Node : 14.15.4
  OS   : darwin x64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.10
  @nrwl/cypress : 11.2.10
  @nrwl/devkit : 11.2.10
  @nrwl/eslint-plugin-nx : 11.2.10
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.10
  @nrwl/linter : 11.2.10
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.2.10
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.10
  @nrwl/web : 11.2.10
  @nrwl/workspace : 11.2.10
  typescript : 4.0.5
```

**Comment by ChristianIvicevic** [comment]
Apparently it was necessary to change the file `libs/ui/.babelrc`. Setting `pure` and `ssr` explicitly to `false` yields the expected behavior. I assume for the context of the storybook these options do not even have to be changed for production as applications using those components will handle this.

I am wondering whether it's reasonable to set those values to false per default.

**Comment by R4VANG3R** [comment]
I'm experiencing the same issue on `11.3.0` and before migrating on `10.3.1`. However setting `pure` and `ssr` to `false` does not resolve it for me. I did try it on an older "fresh" install of nx where it does work, not sure what is causing it not to work on my main repository.

**Comment by Gieted** [comment]
Changing `ssr` to `false` in `.babelrc` is a working **workaround** for this issue. Doing it, causes generating a new css class names on each rebuild.

**Comment by juristr** [comment]
Nx 12.7 has a new React Storybook preset which we export as part of `@nrwl/react`. That should fix the issue. 

Here's a preview doc which will obviously be online on nx.dev once it is released: https://nx-dev-git-refactor-react-storybook-setup-nrwl.vercel.app/preview/react/storybook/migrate-webpack-final

The easier is to upgrade once 12.7 is out, generate a new library with Storybook and inspect the setup.
