### ISSUE TITLE
cypress e2e exit on status 0 even when there are failing tests

### ISSUE THREAD

**Issue by itayod** [nrwl/nx#4725]
After updating my **NX** version from `11.0.15` to the latest one (cypress's version stayed the same), my e2e tests were starting to pass even when my tests were failing, after downgrading the version from the latest one back to `11.0.15` it got back to work as expected.

## Current Behavior
Cypress exit on status 0 even when there are failing tests.

## Expected Behavior
The e2e should exit with status 1 (or above) when there are failing tests according to the [cypress docs](https://docs.cypress.io/guides/guides/command-line.html#Exit-code)

## Steps to Reproduce
* create a new workspace
* create a failing e2e test
* run `$ npm run e2e -- --headless --exit`
* run `$ echo $?`

The output should be "1", but "0" is received (meaning the tests passed successfully).

### Environment
```
  Node : 14.15.0
  OS   : win32 x64
  npm  : 6.14.8

  nx : Not Found
  @nrwl/angular : 11.0.4
  @nrwl/cli : 11.0.4
  @nrwl/cypress : 11.0.4
  @nrwl/devkit : 11.0.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.4
  @nrwl/linter : 11.0.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.4
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.4
  typescript : 4.0.5
```

**Comment by FrozenPandaz** [comment]
Sorry, I'm not able to reproduce with any of the following Nx versions:

* `11.0.4`
* `11.2.10`
* `11.0.15`

What version of `cypress` is being used?

I tried the following `cypress` versions:

* `^6.0.0`
* `^5.0.0`
* `^4.0.0`

They all return exit 1 for me when a test fails.

Can you provide a repo that would help me reproduce the issue please?

**Comment by itayod** [comment]
> Sorry, I'm not able to reproduce with any of the following Nx versions:
> 
> * `11.0.4`
> * `11.2.10`
> * `11.0.15`
> 
> What version of `cypress` is being used?
> 
> I tried the following `cypress` versions:
> 
> * `^6.0.0`
> * `^5.0.0`
> * `^4.0.0`
> 
> They all return exit 1 for me when a test fails.
> 
> Can you provide a repo that would help me reproduce the issue please?

6.0.0

**Comment by itayod** [comment]
>Can you provide a repo that would help me reproduce the issue please?

There you go:
https://github.com/itayod/nx-cypress-issue

**Comment by itayod** [comment]
@FrozenPandaz did you take a look at my repro? need any more details from my side?

**Comment by SebastianSchmidtInovex** [comment]
I have the same problem and pinned it down to the step from @nrwl/cypress (and @nrwl/workspace) @11.1.5 to @11.2.0.
I am running angular/* @11.2.0 and tried with cypress 6.2.1, 6.4.0 and 6.5.0 on windows (in a git bash MINGW64 shell).

Until 11.1.5 it works correctly, since 11.2.0 and up to 11.3.0-rc3 it is broken.
In a bug report for the @angular/cli project I was send here (https://github.com/angular/angular-cli/issues/20074).

**Comment by srnec** [comment]
Hey guys! 
I reported the same issue
https://github.com/nrwl/nx/issues/4860

My suspicion is this file:
https://github.com/nrwl/nx/blob/11.2.x/packages/devkit/src/utils/convert-nx-executor.ts#L39-L46
It always override the output with `{ success: true }` even when output from the executor contains `{ success: false }`.
