### ISSUE TITLE
npx create-nx-workspace@latest / 11.2.10 / 11.2.9 / 11.2.8 fail on Windows 10

### ISSUE THREAD

**Issue by maartentibau** [nrwl/nx#4727]
## Current Behavior

https://user-images.githubusercontent.com/4103756/107144817-f76d7780-693d-11eb-93af-ed8f285047e0.mp4

## Expected Behavior

https://user-images.githubusercontent.com/4103756/107144826-05bb9380-693e-11eb-8acb-2a0cca5f2cf5.mp4

## Steps to Reproduce

See current behaviour screen recording

### Failure Logs

n/a

### Environment

n/a

**Comment by derHodrig** [comment]
I end up in
_EINVAL: invalid argument, mkdir 'C:\C:\Users\{USERNAME}\source\repos\trashes\{WORKSPACENAME}'_

As you see he tries to make a new directory on C:\C: .... this is totally wrong

**Comment by bekos** [comment]
@maartentibau seems like there was an issue an issue prior to 11.2.10, but was fixed via https://github.com/nrwl/nx/commit/ef42f14. 
![image](https://user-images.githubusercontent.com/551595/107411785-9dc0a500-6b17-11eb-8c7e-09147a47c2b8.png)

Can you please share any more info, like npm/node versions? are you using powershell, git bash etc?

**Comment by maartentibau** [comment]
Node: `v13.11.0`
Git: `2.30.0.windows.1`
npm: `6.13.7`

```
Name             : ConsoleHost
Version          : 7.1.0
InstanceId       : ecadd062-cc21-4ffc-b5bd-e06e7df188ba
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-NL
CurrentUICulture : en-GB
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

**Comment by IT-CASADO** [comment]
I have the same issue.

NX: 11.2.10
Node: v12.17.0
NPM: 6.14.4
OS: Windows 10

I started "npx create-nx-workspace" in VS Code with Integrated Terminal

**Comment by maartentibau** [comment]
Thank!! 🙏
