### ISSUE TITLE
Not able to run react-native project for workspace 11.2.10 using nx run-ios

### ISSUE THREAD

**Issue by akhilvasudev-kiwi** [nrwl/nx#4736]
## Current Behavior
Running React native app using  nx run-ios gives error in terminal

## Expected Behavior
Should run the app on IOS simulator.

## Steps to Reproduce
npx create-nx-workspace workspace --preset=empty 
npm  install --save-dev @nrwl/react-native
npx nx g @nrwl/react-native:app awesome-app
npx nx run-ios awesome-app

### Failure Logs
Cannot find module '@nrwl/workspace/src/utils/fileutils'

### Environment
@nrwl/workspace - 11.2.10
@nrwl/react-native - 11.0.2

**Comment by xavidram** [comment]
Experiencing a similar issue using the same workspace version OP mentioned. I noticed that the @nrwl/workspace lib version 11 doesnt have the fileutils js file. Might need to downgrade? Currently installing previous versions of @nrwl/workspace to find the oldest compatible version.

**Comment by xavidram** [comment]
@akhilvasudev-kiwi 
Figured it out. Install @nrwl/workspace: 11.0.18. That should fix this issue. Newest version of @nrwl/workspace indeed does not have a couple files referenced in the current version of @nrwl/react-native

**Comment by duro** [comment]
@xavidram and @akhilvasudev-kiwi I tried downgrading to v11.0.18 of @nrwl/workspace and now I get the following error:

```
Cannot find module '@nrwl/workspace/src/utilities/perf-logging'
```

**Comment by xavidram** [comment]
I didn't get that error but I did get some others. Looks like the templated react-native app is a bit out of date with it's grade dependencies. I'll see if I can replicate your error @duro

**Comment by alfonsobravi** [comment]
FYI, I only got it working properly when everything was aligned at 11.0.2
I'd be glad to know if someone got it running flawlessly with a different combination of versions.

**Comment by hanselabreu** [comment]
> FYI, I only got it working properly when everything was aligned at 11.0.2
> I'd be glad to know if someone got it running flawlessly with a different combination of versions.

I was having the same issues, changing `@nrwl/workspace` to version `11.0.18` fixed it for me.

Here is my combination of NX versions:

![image](https://user-images.githubusercontent.com/27902567/107400633-f9674000-6acf-11eb-8233-cc6bdff9430a.png)

**Comment by xavidram** [comment]
@hanselabreu Were you able to get it to run on an android device out of the box after fixing your @nrwl versions?

**Comment by hanselabreu** [comment]
@xavidram Yeah, Android ran no problem. However, for iOS I had to delete the `Podfile.lock` and install the dependencies again.

**Comment by akhilvasudev-kiwi** [comment]
Hi @mandarini. I am getting another error now.

./logo.png from workspace/apps/mobile/src/app/App.tsx: ./logo.png could not be found within the project.

![Screenshot 2021-02-11 at 11 17 20 AM](https://user-images.githubusercontent.com/31406608/107605989-b8e7fd80-6c5a-11eb-9dfd-b12377a99f04.png)

**Comment by vincentwuhrlin** [comment]
Hello, same problem (same screen), all require png from application and nodes modules were not found.

I have try to align with 11.0.2 without success :
```
"dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.4"
  },
  "devDependencies": {
    "@nrwl/cli": "11.0.2",
    "@nrwl/eslint-plugin-nx": "11.0.2",
    "@nrwl/jest": "10.4.4",
    "@nrwl/linter": "10.4.4",
    "@nrwl/react": "10.4.4",
    "@nrwl/react-native": "11.0.2",
    "@nrwl/tao": "11.0.2",
    "@nrwl/workspace": "11.0.2",
    "@react-native-community/cli-platform-android": "4.13.0",
    "@react-native-community/cli-platform-ios": "4.13.0",
    "@testing-library/jest-native": "3.4.3",
    "@testing-library/react-native": "7.1.0",
    "@types/jest": "26.0.8",
    "@types/node": "12.12.38",
    "@types/react": "16.9.38",
    "@types/react-native": "0.63.18",
    "@typescript-eslint/eslint-plugin": "4.3.0",
    "@typescript-eslint/parser": "4.3.0",
    "dotenv": "6.2.0",
    "eslint": "7.10.0",
    "eslint-config-prettier": "6.0.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsx-a11y": "6.4.1",
    "eslint-plugin-react": "7.21.5",
    "eslint-plugin-react-hooks": "4.2.0",
    "jest": "26.2.2",
    "jest-react-native": "18.0.0",
    "metro-react-native-babel-preset": "0.63.0",
    "prettier": "2.2.1",
    "react-test-renderer": "17.0.1",
    "ts-jest": "26.4.0",
    "ts-node": "~9.1.1",
    "typescript": "~4.0.3"
  }
```

Any idea ?
NX react-native plugin is so cool but currently we can't using our new app in our monorepo :(

Thank you very much !

**Comment by vincentwuhrlin** [comment]
Hello, I have found a fix.

I don't how it's the correct way, but I have feeling that `metro.config.js` cause the problem.

1. I have tested all versions of React Native Nx plugin with workspace and other dependencies, I have always the resolution error of png image,
2. So, I have updated `@nrwl/workspace` and `@nrwl/cli` and other dependencies to recent version : `11.2.12` (described below),
3. Then, I have compared a personal current React Native app with app created by Nx plugin and I have modified `metro.config.js` by adding a `resolver`. For some unknown reason, when I pass this transformed as arg to method `withNxMetro`, it's not working (official code [here](https://github.com/nrwl/nx-react-native/blob/main/packages/react-native/plugins/with-nx-metro.ts)).

By setting the resolver just before sending final metro config, the demo app is working perfectly !

I am interested in your opinions and feedback.

**`metro.config.js` :**
```
const { withNxMetro } = require('@nrwl/react-native')
const { getDefaultConfig } = require('metro-config')

module.exports = (async () => {
  const { resolver: { sourceExts, assetExts } } = await getDefaultConfig()

  return {
    ...withNxMetro({
      transformer: {
        getTransformOptions: async () => ({
          transform: {
            experimentalImportSupport: false,
            inlineRequires: false,
          },
        }),
      },
    },
    {
      // Change this to true to see debugging info.
      // Useful if you have issues resolving modules
      debug: true,
    }),
    resolver: {
      assetExts: assetExts.filter((ext) => ext !== "svg"),
      sourceExts: [...sourceExts, "ts", "tsx", "json", "svg"],
    }
  }
})()
```

**`package.json` :**
```
 "dependencies": {
    "@apollo/client": "^3.2.5",
    "@nestjs/common": "^7.0.0",
    "@nestjs/core": "^7.0.0",
    "@nestjs/graphql": "^7.8.1",
    "@nestjs/mongoose": "^7.0.2",
    "@nestjs/platform-fastify": "^7.4.4",
    "@nestjs/terminus": "^7.0.1",
    "@p-j/geocodejson-googleapis": "^1.0.0",
    "@p-j/geocodejson-types": "^1.0.0",
    "@types/geojson": "^7946.0.7",
    "apollo-boost": "^0.4.9",
    "apollo-server-fastify": "^3.0.0-alpha.3",
    "barcode": "^0.1.0",
    "base-64": "^1.0.0",
    "base64-stream": "^1.0.0",
    "canvas": "^2.6.1",
    "class-transformer": "^0.3.1",
    "class-validator": "^0.12.2",
    "classnames-prefix": "0.0.4",
    "core-js": "^2.6.12",
    "easy-peasy": "^4.0.1",
    "fastify-helmet": "^5.0.3",
    "fs-extra": "^9.0.1",
    "gatsby": "^2.25.4",
    "gatsby-plugin-manifest": "^2.5.2",
    "gatsby-plugin-postcss": "^3.1.0",
    "gatsby-plugin-react-helmet": "^3.3.14",
    "gatsby-plugin-sass": "^2.6.0",
    "gatsby-plugin-sharp": "^2.7.1",
    "gatsby-plugin-svgr": "^2.0.2",
    "gatsby-transformer-sharp": "^2.5.21",
    "geojson": "^0.5.0",
    "graphql": "14.7.0",
    "graphql-tools": "^7.0.1",
    "i18next": "^19.8.3",
    "i18next-browser-languagedetector": "^6.0.1",
    "i18next-xhr-backend": "^3.2.2",
    "ioredis": "^4.19.4",
    "isomorphic-fetch": "^3.0.0",
    "jsbarcode": "^3.11.3",
    "kafkajs": "^1.15.0",
    "mongoose": "^5.11.13",
    "mongoose-autopopulate": "^0.12.3",
    "node-fetch": "^2.6.1",
    "noflo": "1.4.3",
    "pdfkit": "^0.11.0",
    "postcss": "^8.1.7",
    "postcss-import": "^13.0.0",
    "postcss-preset-env": "^6.7.0",
    "prop-types": "15.7.2",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-flow-renderer": "^8.0.0",
    "react-helmet": "5.2.1",
    "react-i18next": "^11.7.3",
    "react-icons": "^3.11.0",
    "react-native": "0.63.4",
    "reflect-metadata": "^0.1.13",
    "rxjs": "~6.5.5",
    "svg-to-pdfkit": "^0.1.8",
    "tslib": "^2.0.0",
    "xstate": "^4.15.4",
    "yaml-schema-validator": "^1.2.2"
  },
  "devDependencies": {
    "@angular-devkit/schematics": "9.1.7",
    "@babel/plugin-proposal-decorators": "^7.12.1",
    "@emotion/core": "^10.1.1",
    "@emotion/styled": "^10.0.27",
    "@graphql-codegen/cli": "^1.19.1",
    "@graphql-codegen/typescript-operations": "^1.17.9",
    "@graphql-codegen/typescript-react-apollo": "^2.1.1",
    "@nestjs/schematics": "^7.0.0",
    "@nestjs/testing": "^7.0.0",
    "@nrwl/cli": "11.2.12",
    "@nrwl/cypress": "10.3.2",
    "@nrwl/eslint-plugin-nx": "10.3.2",
    "@nrwl/gatsby": "^11.0.0",
    "@nrwl/jest": "10.3.2",
    "@nrwl/linter": "10.4.4",
    "@nrwl/nest": "^10.3.2",
    "@nrwl/node": "10.3.2",
    "@nrwl/react": "9.5.1",
    "@nrwl/react-native": "^11.0.2",
    "@nrwl/workspace": "11.2.12",
    "@react-native-community/cli-platform-android": "4.13.0",
    "@react-native-community/cli-platform-ios": "4.13.0",
    "@testing-library/jest-native": "3.4.3",
    "@testing-library/react": "10.2.1",
    "@testing-library/react-native": "7.1.0",
    "@types/jest": "26.0.8",
    "@types/mongoose": "^5.7.37",
    "@types/node": "^8.10.66",
    "@types/react": "16.9.38",
    "@types/react-native": "0.63.18",
    "@typescript-eslint/eslint-plugin": "4.3.0",
    "@typescript-eslint/parser": "4.3.0",
    "babel-plugin-module-resolver": "4.0.0",
    "babel-preset-gatsby": "0.4.9",
    "cypress": "^4.1.0",
    "dotenv": "6.2.0",
    "eslint": "7.10.0",
    "eslint-config-prettier": "6.0.0",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-import": "2.21.2",
    "eslint-plugin-jsx-a11y": "6.3.1",
    "eslint-plugin-react": "7.20.0",
    "eslint-plugin-react-hooks": "4.0.4",
    "gatsby-cli": "^2.12.117",
    "gatsby-plugin-emotion": "^4.4.0",
    "gatsby-plugin-layout": "^1.4.0",
    "gatsby-plugin-polyfill-io": "^1.1.0",
    "gatsby-plugin-react-svg": "^3.0.0",
    "gatsby-plugin-root-import": "^2.0.5",
    "gatsby-plugin-tsconfig-paths": "^1.0.2",
    "jest": "26.2.2",
    "jest-react-native": "18.0.0",
    "metro-react-native-babel-preset": "0.63.0",
    "node-sass": "4.14.1",
    "npm-force-resolutions": "0.0.3",
    "prettier": "2.0.4",
    "react-test-renderer": "17.0.1",
    "stylelint": "^13.7.2",
    "supertest": "^6.0.1",
    "tailwindcss": "^1.9.6",
    "ts-jest": "26.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.0.0",
    "twin.macro": "^1.12.0",
    "typescript": "~4.0.3"
  }
```

**Comment by mandarini** [comment]
Hello!  I'll take a more extended look on Monday and potentially reopen. In the meantime: 

Did you try to use the latest version of Nx ([11.2.12](https://github.com/nrwl/nx/releases/tag/11.2.12))? That version includes our fix for this issue, so unless you use that version, your issue will persist. 
At some point, the new version of [nrwl/nx-react-native](https://github.com/nrwl/nx-react-native) will be released, which contains another fix, but the latest Nx version should do the trick for now.

Let me know if your issue persists using the latest version!

Thank you all for taking the time!!

**Comment by akhilvasudev-kiwi** [comment]
Hi @mandarini 
Today I used Nx version 11.2.12 ("@nrwl/workspace": "11.2.12"). Now When I am trying to run IOS project I am getting following error

CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal x86_64 /Users/exapmles/acme/apps/awesome-app/ios/Pods/YogaKit/YogaKit/Source/YGLayoutExtensions.swift
(2 failures)

**Comment by anshumanabrol-kiwi** [comment]
Hi @mandarini is this resolved ? Should i give it a try ?

**Comment by mandarini** [comment]
Yes, this should be fixed. Make sure all your nrwl packages versions are aligned!
