### ISSUE TITLE
removeProjectConfiguration in @nrwl/devkit

### ISSUE THREAD

**Issue by adam-marshall** [nrwl/nx#4740]
The docs here https://nx.dev/latest/angular/core-concepts/nx-devkit#devkit-helper-functions

mention `removeProjectConfiguration`
![image](https://user-images.githubusercontent.com/2521384/107259674-316d7500-6a35-11eb-87cf-2322b38ef328.png)

but I can't see it anywhere - is it due in a future release?
![image](https://user-images.githubusercontent.com/2521384/107259731-4518db80-6a35-11eb-9517-c3dff894d6af.png)

**Comment by vsavkin** [comment]
Sorry, it's in the latest beta, but it hasn't been released yet as stable. I authored the guide based on what is in the main branch. I apologize.

I'm going to to close the issue cause the fix will happen on its own later this week :)
