### ISSUE TITLE
Feature Request: @nrwl/web:library generator

### ISSUE THREAD

**Issue by ashwinGokhale** [nrwl/nx#4741]
## Description
It would be nice to have a web library generator.

## Motivation
Currently, if I need to create a library for the web, I have to create a React library and manually remove the React parts.

## Suggested Implementation

Modify the existing @nrwl/react:library generator and remove the React specific parts.

**Comment by luxaritas** [comment]
Can this get re-opened? Still definitely needed, and I'm sad to see that the PR has been silent for a couple months.

**Comment by jaysoo** [comment]
@luxaritas Can you try the workspace lib generator? It's meant to be a generic TS lib that's framework agnostic.

`nx g @nrwl/workspace:lib my-lib`

**Comment by luxaritas** [comment]
Oh yeah I found that recently, and that does indeed do the job!

**Comment by ashwinGokhale** [comment]
@jaysoo that works except for 1 thing. The `build` command uses `@nrwl/workspace:tsc` instead of `@nrwl/web:package`. Is there a way to automatically configure which build command to use?
