### ISSUE TITLE
babel-plugin-macros

### ISSUE THREAD

**Issue by cyrus-za** [nrwl/nx#4744]
## Description

[babel-plugin-macros](https://babeljs.io/blog/2017/09/11/zero-config-with-babel-macros) is a new way to be able to add some babel transpiling without the need to touch one's .babelrc file. Simply install the package and import it. Some packages, like styled-components, comes bundled with their own macros and one can use it by importing from `styled-components/macro`

## Motivation

Frameworks like create-react-app bundle macros as default. This is becoming the norm and there's no additional complexity or bundle size for users who do not want to use it.

## Suggested Implementation

If this can be defaulted in @nrwl/next and @nrwl/react that would be amazing. If selecting `styled-components` as the styled library, please also change the imports from generated components/pages to use `styled-components/macro`. The other nice thing is, you wonnt need to create a .babelrc file and add the styled-components config as the macro defaults to using it. 

## Alternate Implementations

If you do not want to default to it, maybe add a --macro=true option in the initial lib/app creation process or let the user select from a list, like currently done for css solution.

**Comment by cyrus-za** [comment]
@vsavkin please re-open

**Comment by nonameolsson** [comment]
I'm struggling with getting styled-components and twin.macro to work with NX. This seems to be a good solution.

**Comment by rdosSquares** [comment]
babel-plugin-macros has been added see [packages/js/babel.ts](https://github.com/nrwl/nx/blob/master/packages/js/babel.ts)
