### ISSUE TITLE
storybook e2e tests fail to run with Storybook 6.2-alpha

### ISSUE THREAD

**Issue by literalpie** [nrwl/nx#4747]
## Current Behavior
When I run `nx run testlib-e2e:e2e`, the test doesn't run. Instead  "Cannot find module '@storybook/core/dist/server/build-dev' " is printed to the console. See the "Failure Logs" section for the full error.

## Expected Behavior
Tests should run. Tests run properly when using the stable version of storybook (6.1).

I understand this is a prerelease of Storybook and there's no guarantee that nx will work with it, but I assume you want to be aware of these errors (that's what prereleases are for after all!)
I think the fix would be to change [this line](https://github.com/nrwl/nx/blob/master/packages/storybook/src/builders/storybook/storybook.impl.ts#L13) to import from `@storybook/core/server` instead of the longer path. A similar change would also be needed on [line 54 of the same file](https://github.com/nrwl/nx/blob/master/packages/storybook/src/builders/storybook/storybook.impl.ts#L13). (the hardest part will most likely be detecting the correct path to import from)

## Steps to Reproduce

[Use this repo](https://github.com/literalpie/nx-storybook-bug-cannot-find-build-dev-module) and skip to step 7.

1. Create an nx angular project
2. `nx generate library testlib`
3. `nx g c testcomp --project=testlib`
4. `yarn add --dev @nrwl/storybook`
5. `nx g @nrwl/angular:storybook-configuration testlib` - answer yes to all questions
6. `yarn add @storybook/angular@next @storybook/addon-knobs@next`
7. `nx run testlib-e2e:e2e` - This will cause the error

### Failure Logs
```
Cannot find module '@storybook/core/dist/server/build-dev'
Require stack:
- /Users/bkindle/Documents/Development/temp/testco/node_modules/@nrwl/storybook/src/builders/storybook/storybook.impl.js
- /Users/bkindle/Documents/Development/temp/testco/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /Users/bkindle/Documents/Development/temp/testco/node_modules/@angular-devkit/architect/node/index.js
- /Users/bkindle/Documents/Development/temp/testco/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
- /Users/bkindle/Documents/Development/temp/testco/node_modules/@nrwl/tao/src/commands/run.js
- /Users/bkindle/Documents/Development/temp/testco/node_modules/@nrwl/tao/index.js
- /Users/bkindle/Documents/Development/temp/testco/node_modules/@nrwl/cli/lib/run-cli.js
```

### Environment
  Node : 12.14.1
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 11.2.10
  @nrwl/cli : 11.2.10
  @nrwl/cypress : 11.2.10
  @nrwl/devkit : 11.2.10
  @nrwl/eslint-plugin-nx : 11.2.10
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.10
  @nrwl/linter : 11.2.10
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.10
  @nrwl/web : Not Found
  @nrwl/workspace : 11.2.10
  typescript : 4.0.5

**Comment by juristr** [comment]
@literalpie Can you try to see whether you have `@storybook/core` installed? Otherwise, can you try installing that separately and try again. Thx :)

**Comment by literalpie** [comment]
`@storybook/core` was in my node_modules already, but I explicitly added it to be sure. I am still seeing the error.

**Comment by juristr** [comment]
👍 just wanted to be sure as we had a similar issue in the past. Cool thx for reporting. I'm going to give this a look. Thx

**Comment by juristr** [comment]
Looks like the Storybook repo also didn't adjust some of their own paths neither: https://github.com/storybookjs/storybook/blob/next/app/angular/standalone.js#L2

I'm monitoring this to make sure we adjust, once Storybook v6.2 comes near a release

**Comment by JamesHenry** [comment]
For now I am using `patch-package` to workaround this issue. Just follow the instructions in the patch-package README in case you haven't used it before. This is what my final patch looks like:

![image](https://user-images.githubusercontent.com/900523/111441582-e247ed80-8720-11eb-8a1d-6b39be318046.png)
