### ISSUE TITLE
Type-only imports should not trigger circular dependency errors

### ISSUE THREAD

**Issue by rene-leanix** [nrwl/nx#4753]
## Current Behavior

Type-only imports with `import type` seem to be treated exactly the same as regular imports and throw circular-dependency errors.

## Expected Behavior

Type-only imports do not affect the generated code at all, so I would expect them to be ignored when determining circular dependencies. 

## Environment

  nx : Not Found
  @nrwl/angular : 10.4.7
  @nrwl/cli : 10.4.7
  @nrwl/cypress : 10.4.7
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.4.7
  @nrwl/linter : 10.4.7
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.4.7
  @nrwl/web : Not Found
  @nrwl/workspace : 10.4.7
  typescript : 4.0.5

## Related questions

I [posted](https://nrwlcommunity.slack.com/archives/CMFKWPU6Q/p1612345467243800) the following questions about type-only and dynamic imports to your #support Slack-channel a week ago, but didn't receive any responses there. If you prefer to respond there or don't consider this a bug, feel free to close this ticket.

> I’ve got a question about type-only and dynamic imports. Both of them are included in the nx dependency graph and therefore cause the importing code to be affected by code changes and can lead to circular dependency errors.
> I’m wondering whether type-only imports with `import type` should rather be treated as a third category in the dependency tree, so they don’t trigger circular dependency errors at all. I’m unsure about the affectedness of the code, though. The importing code won’t need rebuilding, as the artefact won’t change, but it does require type-checking if the imported type has changed.
> With respect to dynamic imports, it would be great if a particular dynamic import could be excluded from the dependency tree altogether or ignored. To give one example, at a few places in our code we are loading an Angular module dynamically in order to create one of its components and add it to the DOM. I would like this dynamic import to be excluded from the dependency tree, as changes in that module do not require a rebuild (or even type-check) of the importing code and as circular dependencies are not an issue.

**Comment by madebyjeffrey** [comment]
I see no reason why you can't create a circular dependency with types only. For example, you could have type A in A.ts and type B in B.ts where each of them import the other and reference those imports within.

**Comment by rene-leanix** [comment]
@madebyjeffrey, you are right, of course, that you can easily create circular dependencies for types. But these are not a problem for the TS compiler at all. Circular dependencies are only a problem at run-time, when the bundler cannot import the file as it would end up in an infinite loop.

**Comment by twittwer** [comment]
The feature requests is still valid, isn't it?

**Comment by frontendmonster** [comment]
This is also one of my issues. I'd like to contribute to the resolution of this problem.

**Comment by SvenBudak** [comment]
Any News? my whole team was trying for hours today to find the problem... finally we saw that its just a bug...

**Comment by rene-leanix** [comment]
I think I found a work-around for this, based on the fact that `nx` relies on the path aliases defined in the root-level `tsconfig.base.json` or `tsconfig.json`. If the code containing the type imports is compiled with a tsconfig-file extending `tsconfig.base.json` (in our case the nx app's or lib's tsconfig), it may contain additional path aliases that will be unknown to nx during the affected-check and any imports using those path-aliases will just be skipped.

This can be combined with the following ESLint rule

```json
```

**Comment by nayfin** [comment]
I'm having this issue as well. I have a an interface that imports a components type. It was working fine until I started abstracting lib into secondary entry points. Any nrwl advice on this one? Is this an issue with Nx not yet handling all the things that Typescript can or do I need to rethink my hierarchy?

**Comment by MarkusFaatz** [comment]
I would love to see this working, too.
At places where we want to just import a type, we write additional interfaces and make sure to properly implement them in the parent project. But this way we lose 100% of intellisense provided by the authors of the original type, which is a very important channel of communication for us - probably the most important one.
We have specialists providing very complex features in their library. They may add the most beautiful docs to their types - including new features, deprecations etc etc. And those will never reach the audience. Isn’t this in conflict with the idea of using typescript in a monorepo?
