### ISSUE TITLE
Can't run update on CLI v6 app

### ISSUE THREAD

**Issue by shlomiassaf** [nrwl/nx#476]
Hi

With angular cli V6 app and nx 6.0.0-alpha.1 I'm getting this error when running `npm run update:check`

**Error: ENOENT: no such file or directory, open '.angular-cli.json'**

This also happens in other commands (e.g. postinstall)

I thinks it's related to this https://github.com/nrwl/nx/blob/master/packages/schematics/src/utils/fileutils.ts#L55

**Comment by FrozenPandaz** [comment]
Hey, thank you so much for trying out the alpha!

The update functionality is still being prepared. I referenced the PR which I just opened.

Please try again after it has been merged and published!

Your feedback would be greatly appreciated!

**Comment by ThomasBurleson** [comment]
I just checked `npm run update:check` with @nrwl/schematics 6.0.2... works fine.
