### ISSUE TITLE
Support importing woff files when using styled components

### ISSUE THREAD

**Issue by TheKeithStewart** [nrwl/nx#4764]
## Current Behavior
When importing a `.woff` file for use in global styles with styled components we are receiving the following error:

```sh
ERROR in ./app/fonts/Lato-Regular.woff 1:4
Module parse failed: Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

## Expected Behavior
I would expect the application to be able to use these files without any errors.

This does not seem to be a regression. I do not believe this every worked.

## Steps to Reproduce
I have created a very simple example repo to reproduce this issue. You can find the repo at:

https://github.com/TheKeithStewart/woff-import-issue

In this repo `.woff` files are being imported into the application in the `apps/demo/src/app/fonts/fonts.js` file. This file is being imported into the app in the main.tsx file for the app.

### Environment
```
npx nx report

>  NX  Report complete - copy this into the issue template

  Node : 12.12.0
  OS   : darwin x64
  npm  : 3.10.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.12
  @nrwl/cypress : 11.2.12
  @nrwl/devkit : 11.2.12
  @nrwl/eslint-plugin-nx : 11.2.12
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.12
  @nrwl/linter : 11.2.12
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.2.12
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.12
  @nrwl/web : 11.2.12
  @nrwl/workspace : 11.2.12
  typescript : 4.0.6
```

**Comment by riceboyler** [comment]
@vsavkin In the interim, could this be solved locally by extending the webpack config?

**Comment by AndrewOttavianoAbb** [comment]
Hello! I have seen this same issue and have followed the steps @lorenamelor linked and it still isn't working properly. I am running the latest Nx version (13.8 at this time).

We built a component library in Nx and an app to pull in the component library. In the component library, we have a theme component that is pulling in fonts for font icons. I extended the rollup config in the lib like so
```
const url = require('@rollup/plugin-url');
const nrwlConfig = require('@nrwl/react/plugins/bundle-rollup');

module.exports = (config) => {
  nrwlConfig(config);
  return {
    ...config,
    plugins: [...config.plugins, url({
      limit: Infinity,
      include: ['**/*.woff', '**/*.tff', '**/*.svg'],
    })],
  };
};
```
I also added it to the `project.json` config.

That fixed the build issue in the component library but the my app broke, so I extended the webpack config there:
```
const getWebpackConfig = require('@nrwl/react/plugins/webpack');

module.exports = (webpackConfig) => {
  const config = getWebpackConfig(webpackConfig);

  return {
    ...config,
    module: {
      ...config.module,
      rules: [
        ...config.module.rules,
        {
          test: /\.svg$/,
          use: 'url-loader',
        },
        {
          test: /\.(woff|woff2|eot|ttf|otf)$/,
          loader: 'file-loader',
        },
      ],
    },
  };
};
```
Also changed the project.json webpack config in the app to point to the new webpack. All that fixes the build, but my fonts are still not being pulled in
![image](https://user-images.githubusercontent.com/78449844/156232208-24768dbd-57b9-457a-b74a-090a2c1469e2.png)

Any ideas are appreciated!

**Comment by AndrewOttavianoAbb** [comment]
Discovered that I needed to add an export object to the assets array. This did not fix the issue however, we ended up determining to set the fonts at the app level rather than a component in the library.

**Comment by sivathangeswaran** [comment]
@AndrewOttavianoAbb did you find any solution for this issue?

We are using an external component library and facing the same issue in loading font (woff | woff2) files. Do you see any work-around here?

**Comment by nhantran3395** [comment]
@sivathangeswaran @AndrewOttavianoAbb 

I have been trying to import a `.ttf` font file and then used it as custom font in MUI v5 based project. The below worked for me:

1. Install package file-loader to load font

`
npm i file-loader --save-dev
`

2. Add a custom webpack config file in your app folder `apps/<my-app>/webpack.config.js`

```
const nrwlConfig = require('@nrwl/react/plugins/webpack.js');

module.exports = (config, context) => {
  nrwlConfig(config);

  return {
    ...config,
    module: {
      ...config.module,
      rules: [
        ...config.module.rules,
        {
          test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
          use: [
            {
              loader: 'file-loader',
              options: {
                name: '[name].[ext]',
                outputPath: 'fonts/',
              },
            },
          ],
        },
      ],
    },
  };
};

```

3. Change the `webpackConfig` path in your `project.json`. After this step, your app should be able to resolve the font import.

```
"webpackConfig": "apps/<my-app>/webpack.config.js"
```

4. Configure the font so that it can be used with UI library. This is a snippet for MUI v5

```
import PlusJakartaSansTtf from '../assets/fonts/PlusJakartaSans-Regular.ttf';

const theme = createTheme({
  typography: {
    fontFamily: 'PlusJakartaSans',
  },
  components: {
    MuiCssBaseline: {
      styleOverrides: `
        @font-face {
          font-family: 'PlusJakartaSans';
          src: url(${PlusJakartaSansTtf}) format('truetype');
        }
      `,
    },
  },
});
```
