### ISSUE TITLE
Nx website shows Gatsby plugin instead of Nextjs

### ISSUE THREAD

**Issue by tremppu** [nrwl/nx#4765]
This is a documentation bug for the nx.dev website.

When trying to check documentation for Next.js plugin it shows me Gatsby plugin for some reason.
https://nx.dev/latest/react/plugins/next/overview

![image](https://user-images.githubusercontent.com/6898531/107615661-40327280-6c55-11eb-975b-20cd11046d61.png)

**Comment by tremppu** [comment]
Seems to be fixed 💪

**Comment by brandonroberts** [comment]
Thanks @tremppu
