### ISSUE TITLE
nx migrate - unable to use ng update "check"

### ISSUE THREAD

**Issue by psumal** [nrwl/nx#4774]
Is it possible to use ng update (check) or remove nx migrate?
nx migrate does not have the features of ng update.
nrwl only updated nrwl packages (not  @ angular / cli .. core .. nest ... ngrx .. material. etc ...)

**Comment by bopm** [comment]
https://github.com/nrwl/nx/issues/4260#issuecomment-747159497

**Comment by FrozenPandaz** [comment]
> Is it possible to use ng update (check) or remove nx migrate?

Yes it is, see the comment @bopm linked above.

> nrwl only updated nrwl packages (not @ angular / cli .. core .. nest ... ngrx .. material. etc ...)

`nx migrate` can be used to migrate other packages as well. For `@angular/core` and `ngrx`,  we handle those migrations for you so you shouldn't need to worry about those.

You can migrate to the latest version of `@angular/material` using the following:

```sh
nx migrate @angular/material@latest
```

**Comment by FrozenPandaz** [comment]
Going to close this issue as a duplicate of: https://github.com/nrwl/nx/issues/4260#issuecomment-747159497
