### ISSUE TITLE
Schematics: default projectName is undefined

### ISSUE THREAD

**Issue by mtuzinskiy** [nrwl/nx#4782]
## Current Behavior
```
"$default": {
  "$source": "projectName"
}
```
The `projectName` is the current folder's project name with regular Angular schematics, but it's `undefined` with `nx workspace-generator`.
_Note_: I'm not using "cli": "nx", I need to use a regular Angular schematics. According to the docs, they should run as usual:
https://nx.dev/latest/angular/generators/workspace-generators#running-a-workspace-schematic-created-with-angular-devkit

## Expected Behavior
The `projectName` source should behave in the same way as in Angular schematics.
There is no other way to retrieve the current project's name, and it makes the developers to re-enter --project every time.

## Steps to Reproduce
1. Follow this guide: https://nx.dev/latest/node/generators/workspace-generators#running-a-workspace-generator
2. Remove `"cli": "nx"` from `schema.json`
3. Try to use 
```
"properties": {
  "project": {
    "type": "string",
    "description": "The name of the project.",
    "$default": {
      "$source": "projectName"
    }
  }
}
```

### Environment
  Node : 12.13.1
  OS   : linux x64
  npm  : 6.13.7
  
  nx : Not Found
  @nrwl/angular : 11.1.4
  @nrwl/cli : 11.1.4
  @nrwl/cypress : 11.1.4
  @nrwl/devkit : 11.1.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.4
  @nrwl/linter : 11.1.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.4
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.4
  typescript : 4.0.5

**Comment by FrozenPandaz** [comment]
Sorry, I'm not able to reproduce the issue.

The `projectName` default works properly for me.

Can you please retry with the latest version of Nx?

**Comment by mtuzinskiy** [comment]
@FrozenPandaz Indeed, it worked with the latest Nx! That solves my issue, thank you so much!

**Comment by mtuzinskiy** [comment]
Ok I see what I forgot to mention:  I'm not using "cli": "nx", I need to use a regular schematic.
Here is the `schema.json`:
```
{
  "id": "my-generator",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Name",
      "$default": {
        "$source": "argv",
        "index": 0
      }
    },
    "project": {
      "type": "string",
      "description": "Project name",
      "$default": {
        "$source": "projectName"
      }
    }
  },
  "required": ["name"]
}
```
`index.ts`:
```
import { Tree } from '@nrwl/devkit';

export default function (options) {
  return async (host: Tree, context) => {
    console.log(options);
    throw new Error('halt');
  }
}
```
You'll see that the `projectName` is `undefined`...

**Comment by FrozenPandaz** [comment]
Thanks, that helped me reproduce the issue! :wink:
