### ISSUE TITLE
Generated jest.config.js contains deprecated configuration option resulting in console warning.

### ISSUE THREAD

**Issue by nkwood** [nrwl/nx#4792]
## Current Behavior

The current `jest.config.js` generated for projects sets the 'tsConfig' property on the ts-jest configuration object. See: https://github.com/nrwl/nx/blob/400277b170b48ae3d752713fa9328dcfae6b192d/packages/jest/src/generators/jest-project/files/jest.config.js__tmpl__#L7 

ts-jest has deprecated use of 'tsConfig' in favor of 'tsconfig'. See: https://github.com/kulshekhar/ts-jest/pull/2127/files 
As of ts-jest [26.4.2](https://github.com/kulshekhar/ts-jest/blob/master/CHANGELOG.md#2642-2020-10-23) use of 'tsConfig' rather than 'tsconfig' generates a warning:
`ts-jest[config] (WARN) The option 'tsConfig' is deprecated and will be removed in ts-jest 27, use 'tsconfig' instead`

## Expected Behavior

NX should generate a `jest.config.js` for projects with the 'tsconfig' configuration property rather than 'tsConfig'. Additionally NX should include a migration to change the property for `jest.config.js` files in existing projects.

## Steps to Reproduce

Generate a project with jest as the test runner. Run a test with ts-jest greater than 26.4.2. Observe warning regarding deprecation.

### Environment

>  NX  Report complete - copy this into the issue template

  Node : 14.15.4
  OS   : darwin x64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : 11.2.12
  @nrwl/cli : 11.2.12
  @nrwl/cypress : 11.2.12
  @nrwl/devkit : 11.2.12
  @nrwl/eslint-plugin-nx : 11.2.12
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.12
  @nrwl/linter : 11.2.12
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.2.12
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.12
  @nrwl/web : 11.2.12
  @nrwl/workspace : 11.2.12
  typescript : 4.1.5

**Comment by FrozenPandaz** [comment]
Thanks :smile:, we will update the code generation when we update `ts-jest` :+1:

**Comment by AsmisAlan** [comment]
Hello! did u update the code generation ?

**Comment by helumalai** [comment]
I still see this issue when I migrated from Nx workspace 11 to workspace 12.

**Comment by prewk** [comment]
Still there.
