### ISSUE TITLE
Typegoose requiring extra webpack to turn off transpile (build time takes so long)

### ISSUE THREAD

**Issue by underfisk** [nrwl/nx#4793]
## Current Behavior
So using Nestjs with Typegoos here seems to be a problem, well the problem is that i have enums that are in a shared library, since they are not on the same app they will have to be "compiled" in order to be used. If you use anything to the nestjs typegoose decorators outside of the current app it will just throw error. I manage to get it working by disabling transpile while a custom webpack but i don't want to use that because it takes really a lot of time compiling

## Expected Behavior
I expect to have nestjs working with shared library and typegoose, not sure exactly the root of the problem but any decorator that i use (be it swagger or typegoose), if i do import a class, enum or interface from any shared library it requires to turn off transpilation

## Steps to Reproduce
Just create a new application of nestjs and 1 shared library. The share library just need to export an enum and all it requires is in the main application to create a typegoose model and use the enum in the decorator like this https://typegoose.github.io/typegoose/docs/api/decorators/prop/

### Environment
 Node : 14.15.5
  OS   : darwin x64
  pnpm : 5.17.1
  
  nx : 11.2.12
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.12
  @nrwl/cypress : Not Found
  @nrwl/devkit : Not Found
  @nrwl/eslint-plugin-nx : 11.2.12
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.12
  @nrwl/linter : 11.2.12
  @nrwl/nest : 11.2.12
  @nrwl/next : 11.2.12
  @nrwl/node : 11.2.12
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.12
  @nrwl/web : Not Found
  @nrwl/workspace : 11.2.12
  typescript : 4.0.7

**Comment by bekos** [comment]
@underfisk  I am not familiar with Typegoose 😞 Can you please provide a minimal repro repo, as this will drastically decrease the time that I need to understand your setup 😃

**Comment by underfisk** [comment]
@bekos Thanks for reaching me, i saw that Typegoose has a statement for this issue and its probably not related but i think Nx could provide some kind of support that would allow to solve this issue https://typegoose.github.io/typegoose/docs/guides/known-issues#transpile-only

**Comment by bekos** [comment]
@underfisk thx for the info. also if you can provide a [minimal reproduction](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction/) would help me debug this issue and identify if this something that should be solved via Nx.

**Comment by underfisk** [comment]
@bekos Right now i don't have any, it happened when i was migrating from our lerna monorepo into Nx but its simple, you just create a blank nestjs application and a new nodejs library.
In the nodejs library you create an enum and in the nestjs application the Typegoose model that uses the enum from that lib, now at this phase since nx uses transpilation and typegoose does not support, those kinds of things would have to be probably compiled without transpilation which is probably hard to determinate
As i said earlier, i'm not sure that its related to Nx since Typegoose has a statement about transpile option but i would be glad to see if we could find a solution for modules that can't use transpile among with the ones that can

If you really prefer i can build up that reproduction repo, just let me know

**Comment by bekos** [comment]
> If you really prefer i can build up that reproduction repo, just let me know

@underfisk if you can do it, that would be really helpful, thx 👍

**Comment by underfisk** [comment]
@bekos There you have https://github.com/underfisk/typegoose-nx-issue (just run the application backend) where you have a sample CatModel and you'll see the issue of transpile

**Comment by bekos** [comment]
@underfisk Thx a lot for the repo 😃 I see the issue, and seems like your approach with the custom webpack config is the best one.
I don't think it makes more sense to add extra options, or custom checks inside Nx rather than taking advantage of the existing `webpackConfig` in such edge cases. But I think we should add a note on our docs for this case.

Regarding the build time though, I don't see the issue, but probably this has to do with the small size of the repo 🤔 Are you at least removing the `fork-ts-checker` from the plugins now that you enabled the transpilation?

**Comment by underfisk** [comment]
@bekos I haven't touched much in webpack on the large codebase we have in my company, we decided to pass "any" instead of the enum to the decorator, and transpilation is something we need overall but even so, the first time you load webpack its expected it takes some time but reloading it shouldn't take the same time
Do you think removing fork-ts-checker would make any improvement? (We migrated from Lerna, we were using Nestjs CLI to start the app)

**Comment by underfisk** [comment]
@bekos It does make sense, thanks for the heads up on this. I'll add and test it and let you know how it does look like

**Comment by bekos** [comment]
@underfisk Any news on this one? Anyways, I don't know how much we do on Nx side in your case 🤔

**Comment by underfisk** [comment]
@bekos Not yet but i'll test it as soon as i can

**Comment by underfisk** [comment]
@bekos After testing it, it does in fact allow to use the enums but it takes 3x more at building/booting time, its not a thing i would be accepting to work with
