### ISSUE TITLE
@nrwl/nx/enforce-module-boundaries: EACCES: permission denied 

### ISSUE THREAD

**Issue by underfisk** [nrwl/nx#4794]
## Current Behavior
Enforce-module-boundaries eslint rule is always complaining about permission to write in .cache inside node_modules, this is not so normal so happen so i'm not sure if i have to keep constantly giving permissions or not. 

## Expected Behavior
Not sure exactly if this might be a bug or if its due to the fact the module has no permissions to write inside node_modules

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs
```
06:03	Problem with ESLint reformatting:
			webpack.config.js: Error: Error while loading rule '@nrwl/nx/enforce-module-boundaries': EACCES: permission denied, open '/Users/me/Documents/project/node_modules/.cache/nx/nxdeps.json'
			Occurred while linting /Users/me/Documents/project/apps/gateway/webpack.config.js
			Error: Error while loading rule '@nrwl/nx/enforce-module-boundaries': EACCES: permission denied, open '/Users/me/Documents/project/node_modules/.cache/nx/nxdeps.json'
			Occurred while linting /Users/me/Documents/project/apps/gateway/webpack.config.js
			at Object.openSync (fs.js:476:3)
			at Object.writeFileSync (fs.js:1467:35)
			at writeToFile (/Users/me/Documents/project/node_modules/.pnpm/@nrwl/workspace@11.2.12_prettier@2.2.1/node_modules/@nrwl/work... (show balloon)
```

### Environment
 Node : 14.15.5
  OS   : darwin x64
  pnpm : 5.17.1
  
  nx : 11.2.12
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.12
  @nrwl/cypress : Not Found
  @nrwl/devkit : Not Found
  @nrwl/eslint-plugin-nx : 11.2.12
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.12
  @nrwl/linter : 11.2.12
  @nrwl/nest : 11.2.12
  @nrwl/next : 11.2.12
  @nrwl/node : 11.2.12
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.12
  @nrwl/web : Not Found
  @nrwl/workspace : 11.2.12
  typescript : 4.0.7

**Comment by FrozenPandaz** [comment]
Sorry, I'm not sure how to go about reproducing the issue.

Yes, it seems wherever this lint rule is running cannot write to the `node_modules` directory.

Is this happening when you run a command? From the editor?

Can you provide a repo that has the issue to help us reproduce the issue please?

**Comment by underfisk** [comment]
The issue happens on Webstorm, seems that if i don't give sudo permissions to the folder, nx can't write on node_modules but it shouldn't be touching on that, for example Nextjs creates its own cache outside in a .next folder, that's why i'm not sure if i really have to make myself the owner so NX can write on node_modules OR at least make node_modules folder mine
How do you guys manage the permissions issue?
