### ISSUE TITLE
BROKEN CUSTOM BUILDER RUN

### ISSUE THREAD

**Issue by ekselys** [nrwl/nx#4796]
When trying to execute a custom builder with the `nx run` command no builder is started.

## Current Behavior
Custom builders don't start properly.

## Expected Behavior
Cusom builders to work with `nx run` command

## Steps to Reproduce
- Create a simple nx project
- Before run `npm i` duplicate the `postinstall`
- Rename one of 2 scripts as `postinstall-old`
- In the `postinstall` script remove this part `node ./decorate-angular-cli.js &&`
- run `npm i`
- create a custom builder with the `createBuilder` function (from package `@angular-devkit/architect`) and configure it in the default project, just a simple `console.log()` is enough
- execute the custom builder with the command `ng run project:custom-builder` (the builder should execute without errors)
-  restore the original `postinstall` script and execute the `npm i` (or directly execute the `decorate-angular-cli.js` script)
- execute command `nx run project:custom-builder` (an error should be thrown)

A quickstart repo is the official [Angular one](https://github.com/mgechev/cli-builders-demo)

### Failure Logs
> nx run project:custom-builder
implementation is not a function

### Environment
- Angular: 11.2.0
- Nx: 11.2.7

**Comment by FrozenPandaz** [comment]
Hm the Angular example seems a bit outdated. In addition, we have documentation about how to create a custom builder:
https://nx.dev/latest/react/executors/creating-custom-builders#creating-a-builder-with-angular-devkit

I copied the code from the Angular example following the same method described above and pushed an example here:
https://github.com/FrozenPandaz/nx-bugs/tree/custom-builder

I think this method is better for creating custom builders that are specific to your workspace for a number of reasons.
1. No folder outside of the root of your workspace
2. No fake npm dependency on your filesystem
3. Uses the `tools` directory already present in your workspace.
