### ISSUE TITLE
Publishable react library with styled-jsx doesn't transpile styles

### ISSUE THREAD

**Issue by antoniojps** [nrwl/nx#4797]
## Current Behavior
When creating a react publishable library with styled-jsx the bundled version doesn't bundle styled-jsx properly.

This is the current [dist file](https://github.com/antoniojps/nx-lib-styled-jsx-build/blob/master/dist/libs/components/components.esm.js).

## Expected Behavior
Something [like this should be expected](https://github.com/antoniojps/rollup-styled-jsx-test/blob/master/lib/prod.js), notice the use of the [_JSXStyle](https://github.com/vercel/styled-jsx#how-it-works) component.

## Steps to Reproduce
`npx create-nx-workspace --preset=react` pick `styled-jsx`
`nx g @nrwl/react:library components --publishable --importPath=@test/components --style=styled-jsx`
`nx run components:build`

Here's a [**reproduction repository**.](https://github.com/antoniojps/nx-lib-styled-jsx-build)

Here's a [repository](https://github.com/antoniojps/rollup-styled-jsx-test) where I've been testing the expected bundle.

I've tested with other styles: `@emotion/styled`, `styled-components`, `scss` and they are all bundled correctly except `styled-jsx`.

### Environment
```
  Node : 12.18.3
  OS   : darwin x64
  npm  : 6.14.6
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.12
  @nrwl/cypress : 11.2.12
  @nrwl/devkit : 11.2.12
  @nrwl/eslint-plugin-nx : 11.2.12
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.12
  @nrwl/linter : 11.2.12
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.2.12
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.12
  @nrwl/web : 11.2.12
  @nrwl/workspace : 11.2.12
  typescript : 4.0.7
```

**Comment by antoniojps** [comment]
Does it have something to do with this?

https://github.com/nrwl/nx/blob/18c8b2b30d761586f3ee02bd289114ab63b92ee2/packages/react/src/utils/babel-utils.ts#L19

I noticed emotion and styled components are handled but not styled-jsx.

**Comment by antoniojps** [comment]
I've tested this again and it seems to be working now. Closing :)

**Comment by kasperp** [comment]
@antoniojps I'm hitting this issue now. I'm curious, how did you get it to work? Any input would be appreciated.

**Comment by pstepniewskiconfigit** [comment]
@FrozenPandaz @vsavkin yeah this is happening to us in `12.9.0`
