### ISSUE TITLE
CRA React Application - Live Reload Not working for Change in Library

### ISSUE THREAD

**Issue by knoefel** [nrwl/nx#4813]
## Current Behavior
Changing a file in a connected library for an application, the changes are only pushed the first time to the running app. After the second save/change the app in the browser is not refreshed. 

But also after the first save the changes are not visible in the browser. In the example to reproduce the issue an enum (same while trying with an object) is logged to the console. After the first change and save the changed enum is not logged to the console although the `head` and `body` tags are refreshed (short color flash in elements tab).

## Expected Behavior
Changing a file in a connected library results in refreshing the app and pushing all the changes to the running app in the browser.

## Steps to Reproduce
1. Checkout repro [repo](https://github.com/knoefel/nx-reload-bug)
2. Run "yarn"
3. Run "nx serve app"
4. Open browser dev tools (preferable chrome) and select elements tab
5. Change/add/delete a line in file "libs/app/core/src/lib/models/route-keys.ts" for enum `RouteKeys` and save (check while saving that in dev tools the `head` and `body` tags are refreshed)
6. Check that there is no new console statement reflecting the change
7. Make another change in the file (check while saving that in dev tools the `head` and `body` tags are NOT refreshed)

Here is also a small video showing steps 4-7:
https://user-images.githubusercontent.com/2396344/108191774-d3671e80-7113-11eb-913e-d01620f78668.mov

I followed the official instructions for installing a React application for NX. In addition, I followed the [migration guide](https://nx.dev/latest/react/migration/migration-cra) for using a CRA react app with NX.

### Environment

Node : 10.22.0
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.12
  @nrwl/cypress : 11.2.12
  @nrwl/devkit : 11.2.12
  @nrwl/eslint-plugin-nx : 11.2.12
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.12
  @nrwl/linter : 11.2.12
  @nrwl/nest : 11.2.12
  @nrwl/next : Not Found
  @nrwl/node : 11.2.12
  @nrwl/react : 11.2.12
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.12
  @nrwl/web : 11.2.12
  @nrwl/workspace : 11.2.12
  typescript : 4.0.7

**Comment by tiagomnferreira-mzt** [comment]
Having the same problem.  I don't think it is related to being CRA or other tool, because of this issue #4894 .
Waiting for a solution.

**Comment by knoefel** [comment]
This is still an issue!

**Comment by anakinjay** [comment]
I'm having this same issue, just wanted to add my support for this.

**Comment by jaysoo** [comment]
Need to look into this, but I'm guessing the fast refresh plugin doesn't know about the workspace libs, thus you have to manually reload in order to pick up changes.

@ZackDeRose Can you take a look, and perhaps we need to update the migrations instructions.

**Comment by anakinjay** [comment]
On my machine at least I was able to track the problem down to WSL on windows. Inside of WSL it doesn’t refresh automatically. If I run it in a normal windows command prompt it reloads fine.

hope that helps

**Comment by knoefel** [comment]
Unfortunately this is still an issue. I really like NX and how it helps to structure React projects, but not having HMR support slows down development. Are there any updates on this or maybe a timeline when this bug will get reviewed?

One thing i noticed is, that this problem almost always happens, when i edit something TS related like an `interface` or `enum`. Maybe this helps to find the cause of the problem......

Thanks for the awesome work!!!

**Comment by legovadim** [comment]
same issue. When edit exported interfaces/types, it just doesn't react

**Comment by jaysoo** [comment]
This is due to this optimization in CRA.

https://github.com/facebook/create-react-app/blob/50ea5ad6977fcd05eb32aac71f4f56b9b02511f3/packages/react-scripts/config/webpackDevServer.config.js#L77

You could remove or replace the `watchOptions` for dev server.

https://github.com/timarney/react-app-rewired#extended-configuration-options

We'll also release an update to the cra guide to reflect the changes.

**Comment by barak-haviv** [comment]
Hey @jaysoo, can you leave detailed instructions on what can be done meanwhile.

**Comment by patrickgdl** [comment]
Having the same problem. When updating a Typescript `interface` in an isolated library, it does not update the serve.

I have a library called `models` which is making me crazy at the moment, because when updating or creating a new file, I have to stop serving and start again.
