### ISSUE TITLE
Generate angular.json on an empty workspace

### ISSUE THREAD

**Issue by AlbertoBasalo** [nrwl/nx#4814]
## Description
After creating an empty workspace it is possible to add angular capabilities. Then you can generate angular applications and libs.
But there is no angular.json generated.

## Motivation
Start with and empty project and not be always forced to start with a preset.

## Suggested Implementation
Auto configure the workspace adding the angular preset with a command

**Comment by brandonroberts** [comment]
An empty workspace is meant to be framework agnostic, so you have a few options.

- Rename the workspace.json to angular.json, then generate Angular apps/libs.
- Generate a workspace with an Angular preset, and run `ng g @nrwl/workspace:remove app-name` to remove the initial application
