### ISSUE TITLE
NX React Application doesn't work with @react-pdf/renderer (Can't resolve 'stream' and 'zlib' modules)

### ISSUE THREAD

**Issue by knoefel** [nrwl/nx#4817]
## Current Behavior
When using @react-pdf/renderer in nx react application, the dev build fails and the app crashes (see the error message at "Failure Logs"). There is also an closed issue which describes the same problem -> #4233 

## Expected Behavior
@react-pdf/renderer can be used with a nx react application. 

## Steps to Reproduce
1. Pull Repro [Repo](https://github.com/knoefel/nx-pdf-lib-bug)
2. Run "yarn"
3. Run "nx serve app"
4. App crashes with below errors (installing those missing packages doesn't help, app still crashes)

### Failure Logs
![101622149-f9d35400-3a16-11eb-8c5e-4071c9d06983](https://user-images.githubusercontent.com/2396344/108230051-a846f400-7140-11eb-9cba-192bc06961db.png)

### Environment
  Node : 10.22.0
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.12
  @nrwl/cypress : 11.2.12
  @nrwl/devkit : 11.2.12
  @nrwl/eslint-plugin-nx : 11.2.12
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.12
  @nrwl/linter : 11.2.12
  @nrwl/nest : 11.2.12
  @nrwl/next : Not Found
  @nrwl/node : 11.2.12
  @nrwl/react : 11.2.12
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.12
  @nrwl/web : 11.2.12
  @nrwl/workspace : 11.2.12
  typescript : 4.0.3

**Comment by knoefel** [comment]
This is still an issue!

**Comment by knoefel** [comment]
Resolved with new major version [2.0](https://github.com/diegomura/react-pdf/releases/tag/2.0.0) of `@react-pdf/renderer`.

**Comment by Denise-David** [comment]
I have the same error, I have installed the version of react-pdf / renderer 2.0 but nothing, always the same error ...

**Comment by Abdulrahman-Falyoun** [comment]
Same here

**Comment by knoefel** [comment]
Correct, sorry! I checked with v2 while still using a patch. 😳

So, yes this is still an issue (tested with @react-pdf/renderer@2.0.3

**Comment by kyazdani42** [comment]
looks like a polyfill issue, i haven't yet found a way to properly do this with nx.
The issue can be also found [here](https://github.com/diegomura/react-pdf/issues/1079).
for information @diegomura seems like it loads the correct bundle although pdfkit, png-js and font-kit are all using node packages in their browser runtime thus failing build for webpack. Not sure what should be the right move here.

**Comment by kyazdani42** [comment]
just found out nx sets `node: false` in the webpack configuration, setting `node: undefined` fixes this issue as webpack properly loads the required polyfills i believe.

**Comment by ericbolikowski** [comment]
@kyazdani42 thank you - I really struggled with this. I don't understand webpack builds etc. well enough to grasp this solution, but your hint put me on the path to a solution.

**Comment by wontone18** [comment]
well the best answer and solution for this for instance i am using laravel mix and in webback.mix.js simply add this fall back

```
 mix.webpackConfig({ 
          resolve: {
            fallback: {
               // "stream": false,
               // "zlib": false,
               "stream": require.resolve("stream-browserify"),
               "zlib": require.resolve("browserify-zlib"),

            }
          }
        });
```

**Comment by tmclean15** [comment]
To elaborate on the comment by @kyazdani42, in the `workspace.json`, under the build options, you can add the following options to override webpack configs:
`"webpackConfig": "apps/<your-app-name>/webpack.config.js"`

Then in that file:
`module.exports = (config, context) => {
  return {
    ...config,
    node: undefined,
  };
};`

**Comment by TimNuman** [comment]
FYI, in order to get it to work my webpack config ended up looking like this:

`const webpack = require('webpack');
const nrwlConfig = require('@nrwl/react/plugins/webpack');

module.exports = (config, context) => {
  nrwlConfig(config);

  return {
    ...config,
    resolve: {
      ...config.resolve,
      fallback: {
        module: 'empty',
        dgram: 'empty',
        dns: 'mock',
        fs: 'empty',
        http2: 'empty',
        net: 'empty',
        tls: 'empty',
        child_process: 'empty',
        process: require.resolve('process/browser'),
        zlib: require.resolve('browserify-zlib'),
        stream: require.resolve('stream-browserify'),
        util: require.resolve('util'),
        buffer: require.resolve('buffer'),
        asset: require.resolve('assert'),
      },
    },
    plugins: [
      ...config.plugins,
      new webpack.ProvidePlugin({
        Buffer: ['buffer', 'Buffer'],
        process: 'process/browser',
      }),
    ],
    node: undefined,
  };
};
`

And I installed some modules, according to the react-pdf instructions:

`
npm install process browserify-zlib stream-browserify util buffer assert
`

**Comment by ankitt8** [comment]
Webpack 5 says that it doesn't provides polyfills similar to what has been provided in webpack 4
so 
add below code in your webpack config
https://webpack.js.org/configuration/resolve/#resolvefallback

**Comment by nepalibidur14** [comment]
after using `node: undefined` I get following error
`Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve has an unknown property 'fallback'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, cacheWithContext?, concord?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, 
symlinks?, unsafeCache?, useSyncFileSystemCalls? }
   -> Options for the resolver`

here is my webpack configuration code

`const webpack = require('webpack');
const nrwlConfig = require('@nrwl/react/plugins/webpack');

module.exports = (config, context) => {
  nrwlConfig(config);

  return {
    ...config,
    node: undefined,
    resolve: {
      ...config.resolve,
      fallback: {
        module: 'empty',
        dgram: 'empty',
        dns: 'mock',
        fs: 'empty',
        http2: 'empty',
        net: 'empty',
        tls: 'empty',
        child_process: 'empty',
        process: require.resolve('process/browser'),
        zlib: require.resolve('browserify-zlib'),
        stream: require.resolve('stream-browserify'),
        util: require.resolve('util'),
        buffer: require.resolve('buffer'),
        asset: require.resolve('assert'),
      },
    },
    plugins: [
      ...config.plugins,
      new webpack.ProvidePlugin({
        Buffer: ['buffer', 'Buffer'],
        process: 'process/browser',
      }),
    ],
  };
};
`
