### ISSUE TITLE
Angular library using karma includes dependencies from test.ts

### ISSUE THREAD

**Issue by Lightw3ight** [nrwl/nx#4824]
## Current Behavior
When I build a buildable, publishable angular library that uses `karma`, the `package.json` includes `dependencies` from `test.ts`, such as `zone.js` and `@angular/platform-browser-dynamic`

## Expected Behavior
After building an angular library, the `package.json` in the dist folder should only include dependencies for code not related to tests
I have not used nx before this so I don't know if its a regression or not

## Steps to Reproduce
- Create a new workspace
- - `npx create-nx-workspace --preset=angular`
- - ? Workspace name (e.g., org name)     acme
- - ? Application name                    world
- - ? Default stylesheet format           SASS(.scss)  [ http://sass-lang.com   ]
- - ? Default linter                      ESLint [ Modern linting tool ]
- - ? Use Nx Cloud? (It's free and doesn't require registration.) No
- Create a new library
- - `nx g @nrwl/angular:library some-lib --buildable --publishable --importPath=some-lib --unit-test-runner=karma`
- Build the library
- - `nx build some-lib`
- Check `dist\libs\some-lib\package.json`
- - Contains `zone.js` and `@angular/platform-browser-dynamic`

https://github.com/Lightw3ight/nx-angular-karma-wrong-deps

### Environment
Window 10
```
  Node : 14.15.5
  OS   : win32 x64
  npm  : 6.14.11

  nx : Not Found
  @nrwl/angular : 11.2.12
  @nrwl/cli : 11.2.12
  @nrwl/cypress : 11.2.12
  @nrwl/devkit : 11.2.12
  @nrwl/eslint-plugin-nx : 11.2.12
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.12
  @nrwl/linter : 11.2.12
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.12
  @nrwl/web : Not Found
  @nrwl/workspace : 11.2.12
  typescript : 4.0.7
```

**Comment by brandonroberts** [comment]
This is how it behaves by default, but those dependencies should not be included in the distributed `package.json`. As a workaround, you can set the `updateBuildableProjectDepsInPackageJson` to `false` in the `angular.json` under the `build` target for the library.
