### ISSUE TITLE
Support git ancestor commit objects such as `HEAD^1` in affected `--base` and `--head` tags

### ISSUE THREAD

**Issue by david-gettins** [nrwl/nx#4828]
## Description

To be able to specify `--base` and `--head` in the affected command with ancestor commit objects such as `HEAD^1` or `main^1`.

**Example**
```bash
nx affected:apps --base=HEAD^1 --head=HEAD
```
This produces the error:
```text
Error: Command failed: git merge-base HEAD^1 HEAD
fatal: Not a valid object name HEAD1
```

## Motivation

It would save having to implement extra steps to get the commit hash using something like `git rev-parse HEAD^1` in CI pipelines, therefore improving developer experience and simplifying CI pipelines. 

## Suggested Implementation

When an ancestor commit object is found as the value of `--base` or `--head` the tool runs `git rev-parse ...` and replaces the value with the commit hashes. 

## Alternate Implementations

Unsure.

**Comment by AgentEnder** [comment]
@david-gettins This behavior works when if you use a tilde (~), just not currently with the caret. I have found that the tilde solves our use cases, but I am sure that the caret support would be something appreciated.

**Comment by david-gettins** [comment]
I see thank you, I shall try that.

**Comment by AgentEnder** [comment]
https://github.com/nrwl/nx/blob/ad5628557cd40232209b8517a9497f6be6705871/packages/workspace/src/command-line/shared.ts#L45 The change to fix this should be around this area, currently Nx uses `git merge-base` to find a good spot to check the difference. It appears that git merge-base does not support the format HEAD^1 as `git rev-parse` does for whatever reason.

**Comment by AgentEnder** [comment]
Actually strike that, this has been bugging me today. At first I thought this was an issue with yargs, but this is actually a platform specific bug for windows.

https://github.com/AgentEnder/command-line-carets/actions/runs/720531417

The above repository is a minimum reproduction without Nx. ExecSync in node uses cmd.exe on windows, which removes carets from strings that are not double quoted.
