### ISSUE TITLE
'hmr' is not found in schema in node app at run-many command

### ISSUE THREAD

**Issue by wizardnet972** [nrwl/nx#4848]
## Current Behavior

I run serve with `hmr`  flag (for angular). the command pass to both of the projects.
```
nx run-many --target=serve --projects=ng-app,api-app --parallel --hmr
```
I got an error from  `api-app` application. (the app is NOT compiled and NOT runs):
```
'hmr' is not found in schema in node app
```
**I need to run both in parallel** 

## Expected Behavior

I understand that `hmr` is only in angular applications. but nodejs should ignore this flag when it is given. or present a way to pass this `hmr` flag only to angular application.

## Steps to Reproduce

Clone this repo:
[https://github.com/wizardnet972/nx-org-hmr](https://github.com/wizardnet972/nx-org-hmr)

Run `npm install`

Run `nx run-many --target=serve --projects=ng-app,api-app --parallel --hmr` to serve with hmr flag (for angular)

**OR**

```
npx create-nx-workspace
? Workspace name (e.g., org name)     nx-org-hmr
? What to create in the new workspace empty             [an empty workspace with a layout that works best for building apps]
? Use Nx Cloud? (It's free and doesn't require registration.) No

cd nx-org-hmr

npm i @nrwl/angular @nrwl/node

nx g @nrwl/angular:app ng-app

nx g @nrwl/node:app api-app

npm i express
```

I add this content to **apps/api-app/src/main.ts**:
```
import express from 'express';

const app = express()
const port = 3000

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})
```
And run those apps:
```
nx run-many --target=serve --projects=ng-app,api-app --parallel --hmr
```

[https://github.com/wizardnet972/nx-org-hmr](https://github.com/wizardnet972/nx-org-hmr)

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by wizardnet972** [comment]
I found another way to do it by setting `hmr` to `true` in `workspace.json` under angular build section. so I close this issue.

I think this question should be in the `run-many` docs. (HowTo section).

**Comment by rienheuver** [comment]
@wizardnet972 could you please specify where exactly you set `"hmr: true` in the `angular.json`? I'm trying to get this working in our nx-repo but haven't figured it out (yet)
