### ISSUE TITLE
"Maximum call stack size exceeded" when creating a project graph

### ISSUE THREAD

**Issue by Avareto** [nrwl/nx#4849]
Can't use nx any more. 
After more than 10 minutes (!!!) nx aborts with the following error message:

`
(node:11596) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at Object.readWorkspaceFiles (node_modules\@nrwl\workspace\src\core\file-utils.js:209:11)
    at Object.createProjectGraph (node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:13:145)
    at Object.<anonymous> (node_modules\@nrwl\workspace\src\command-line\run-one.js:16:46)
    at Generator.next (<anonymous>)
    at fulfilled (node_modules\tslib\tslib.js:114:62)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11596) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
`
nx needs more than 10 min to complie my project...how can I speed up complie time?

I am using version ^11.2.10 of all packages: 
    "nx": "^11.2.10",
    "@nrwl/workspace": "11.2.10",
    "@nrwl/angular": "11.2.10",

**Comment by Avareto** [comment]
adding .nxignore with '/www' folder entry fixed the problem.

**Comment by vsavkin** [comment]
Could you provide a repro?
