### ISSUE TITLE
adding angular lib does not update jest.config.js and subsequent removal fails

### ISSUE THREAD

**Issue by nhhockeyplayer** [nrwl/nx#4852]
## Current Behavior
adding angular lib does not update jest.config.js and subsequent removal fails

`nx generate @nrwl/angular:lib mm`

jest.config should be updated
and it isnt

## Expected Behavior
jest.config.js
should be update with

`    '<rootDir>/libs/mm',`

## Steps to Reproduce
```
nx generate @nrwl/angular:lib mm
nx g @nrwl/angular:remove  mm
```

and receive error

Could not find mm in projects in /jest.config.js.
Cannot read property 'getStart' of undefined

### Environment
Angular CLI: 11.1.2
Node: 14.15.1
OS: darwin x64

Angular: 11.2.1
... animations, cdk, common, compiler, core, forms, material
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.2
@angular-devkit/build-angular   0.1101.2
@angular-devkit/core            11.1.2
@angular-devkit/schematics      11.1.2
@angular/cli                    11.1.2
@angular/compiler-cli           11.1.1
@angular/flex-layout            11.0.0-beta.33
@angular/http                   7.2.16
@angular/language-service       11.1.1
@schematics/angular             11.0.4
@schematics/update              0.1101.2
rxjs                            6.6.3
typescript                      4.1.3
    
meanstack@me/energy % nx --version
11.2.0

**Comment by brandonroberts** [comment]
I verified that this is working correctly in the latest 11.4.x release of Nx
