### ISSUE TITLE
E2E tests using Storybook do not run, hang after storybook has been started.

### ISSUE THREAD

**Issue by RoyvandenHeuvel** [nrwl/nx#4858]
### Current behavior
Currently you are not able to use Cypress tests which run against an instance of Storybook (using devServerTarget). 
The e2e test will hang indefinitely after starting up Storybook.

### Expected behavior
Running `nx e2e` should start up Storybook and then run the e2e tests against that instance of Storybook (if using Storybook as the devServerTarget).

### Steps to reproduce
See [this repository](https://github.com/RoyvandenHeuvel/nx-cypress-issue) and run the last step or run all steps underneath to reproduce the issue. 

Run `npx create-nx-workspace@latest workspacename --preset angular --cli nx --style css --linter eslint --nx-cloud false`.
Navigate to the new workspace. 
Run `nx generate @nrwl/workspace:remove --projectName=app-name-e2e`.
Run `npm i --save-dev @nrwl/storybook`. 
Run `nx generate @nrwl/storybook:cypress-project --name=app-name`.
Run `nx generate @nrwl/angular:storybook-configuration --name=app-name --configureCypress --generateCypressSpecs --generateStories`. 

Run `nx e2e app-name-e2e`. 

This will start Storybook, but will not run the Cypress tests.
![1](https://user-images.githubusercontent.com/9801523/108708093-43f5ad00-7511-11eb-9295-9d5a86c03c44.PNG)

**Comment by FrozenPandaz** [comment]
This is fixed with https://github.com/nrwl/nx/commit/35049dcdefea0e9946b7ed8d63c202e9437fde0f. :tada:

Please retry with the latest version. :smile:

**Comment by RoyvandenHeuvel** [comment]
It's working now with the latest version. Thank you!
