### ISSUE TITLE
nx@6: library can't be built using ng build command

### ISSUE THREAD

**Issue by ospatil** [nrwl/nx#486]
### Observation 

Library build in a workspace fails with the following error:

```
$ ng build mylib
Target 'build' could not be found in project 'mylib'.
Error: Target 'build' could not be found in project 'mylib'.
```
### Steps to reproduce

1. Create a new workspace `create-nx-workspace nx6 --yarn`.
2. Create a new library in the workspace - `ng g lib mylib`.
3. Build the library - `ng build mylib`.

### Versions
nx - `6.0.0-rc.1`
node - `10.1.0`
npm - `6.0.1`
yarn - `1.6.0`

### Analysis

I compared the `angular.json` configuration in a bare Angular CLI 6 workspace and the nx workspace and found that library build configuration is missing in the nx workspace - 

<details>
<summary>Angular CLI 6 configuration</summary>
  <p>

```javascript
"mylib": {
  "root": "projects/mylib",
  "sourceRoot": "projects/mylib/src",
  "projectType": "library",
  "prefix": "lib",
  "architect": {
    "build": {
      "builder": "@angular-devkit/build-ng-packagr:build",
      "options": {
        "tsConfig": "projects/mylib/tsconfig.lib.json",
        "project": "projects/mylib/ng-package.json"
      },
      "configurations": {
        "production": {
          "project": "projects/mylib/ng-package.prod.json"
        }
      }
    },
    "test": {
      "builder": "@angular-devkit/build-angular:karma",
      "options": {
        "main": "projects/mylib/src/test.ts",
        "tsConfig": "projects/mylib/tsconfig.spec.json",
        "karmaConfig": "projects/mylib/karma.conf.js"
      }
    },
    "lint": {
      "builder": "@angular-devkit/build-angular:tslint",
      "options": {
        "tsConfig": [
          "projects/mylib/tsconfig.lib.json",
          "projects/mylib/tsconfig.spec.json"
        ],
        "exclude": [
          "**/node_modules/**"
        ]
      }
    }
  }
}
```
  </p>
</details>

<details>
<summary>NX 6 workspace configuration</summary>
  <p>

```javascript
"mylib": {
  "root": "libs/mylib",
  "sourceRoot": "libs/mylib/src",
  "projectType": "library",
  "prefix": "lib",
  "architect": {
    "test": {
      "builder": "@angular-devkit/build-angular:karma",
      "options": {
        "main": "libs/mylib/src/test.ts",
        "tsConfig": "libs/mylib/tsconfig.spec.json",
        "karmaConfig": "libs/mylib/karma.conf.js"
      }
    },
    "lint": {
      "builder": "@angular-devkit/build-angular:tslint",
      "options": {
        "tsConfig": [
          "libs/mylib/tsconfig.lib.json",
          "libs/mylib/tsconfig.spec.json"
        ],
        "exclude": [
          "**/node_modules/**"
        ]
      }
    }
  }
}
```
  </p>
</summary>

**Comment by ospatil** [comment]
Found the answer in the code :). Only `publishable` libraries get the build configuration.  Such libraries needs to be generated with `ng g lib mylib --publishable`.

**Comment by dgroh** [comment]
how do I change a library to be publishable? by hand?

**Comment by randallmeeker** [comment]
same question! how do I change it to be publishable?

**Comment by lovesora** [comment]
1. Add `build` configuration in `angular.json`

```json
{
  "projects": {
    "lib": {
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-ng-packagr:build",
          "options": {
            "tsConfig": "libs/lib/tsconfig.lib.json",
            "project": "libs/lib/ng-package.json"
          }
        }
      }
    }
  }
}
```

2. Add `package.json` in the root of `lib` dir.

```
{
  "name": "@petkit/lib",
  "version": "0.0.1",
  "peerDependencies": {
    "@angular/common": "^6.0.0-rc.0 || ^6.0.0",
    "@angular/core": "^6.0.0-rc.0 || ^6.0.0"
  }
}
```

3. Add `ng-package.json` in the root of `lib` dir.
```json
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/libs/lib",
  "lib": {
    "entryFile": "src/index.ts"
  }
}
```



Ref:
- [schema](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_ng_packagr/src/build/schema.json)

**Comment by fallXone** [comment]
> 1. Add `build` configuration in `angular.json`
> 
> ```json
> {
>   "projects": {
>     "lib": {
>       "architect": {
>         "build": {
>           "builder": "@angular-devkit/build-ng-packagr:build",
>           "options": {
>             "tsConfig": "libs/lib/tsconfig.lib.json",
>             "project": "libs/lib/ng-package.json"
>           }
>         }
>       }
>     }
>   }
> }
> ```
> 
> 1. Add `package.json` in the root of `lib` dir.
> 
> ```
> {
>   "name": "@petkit/lib",
>   "version": "0.0.1",
>   "peerDependencies": {
>     "@angular/common": "^6.0.0-rc.0 || ^6.0.0",
>     "@angular/core": "^6.0.0-rc.0 || ^6.0.0"
>   }
> }
> ```
> 1. Add `ng-package.json` in the root of `lib` dir.
> 
> ```json
> {
>   "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
>   "dest": "../../dist/libs/lib",
>   "lib": {
>     "entryFile": "src/index.ts"
>   }
> }
> ```
> 
> Ref:
> 
> * [schema](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_ng_packagr/src/build/schema.json)

are these the same files that would have been generated if the --publishable flag was used? I'm in a similar scenario where I will need to publish my libraries soon, and i didn't generate the libraries with --publishable. I was surprised to see no documentation on how to apply this after the fact.

**Comment by devonc0** [comment]
I had this issue, turns out that when I had generated my library I leaned on the fact that "xxxYyyy" would become "xxx-yyyy", however - in my config files in angular.json, it showed up as "xxxYyyy".

**Changing my references to "xxx-yyyy" with a replace-all && case-sensitive allowed me to build.**

It was by default already "publishable" though, I didn't use this option myself, anywhere
