### ISSUE TITLE
NextJs build --prod not collecting all dependencies in v11

### ISSUE THREAD

**Issue by dionescu-shipserv** [nrwl/nx#4867]
## Current Behavior
When building a nextjs app, not all dependencies are going into the dist package.json file.
My investigation leads me to believe something is not right inside the [buildProjectGraph](https://github.com/nrwl/nx/blob/ff5048e23cc1594461da8e4b75efa08a1db17400/packages/workspace/src/core/project-graph/project-graph.ts#L83) function which is not traversing the tree correctly and is missing out on anything other than direct app/lib dependencies.

## Expected Behavior
I'm expecting all dependencies to be added to package.json as they are required for the app to run correctly.

It is a regression, as I don't experience the same in 10.4.13.

## Steps to Reproduce
Use this repo: https://github.com/dionescu-shipserv/next-demo-missing-deps.git

1. Clone, yarn
2. Run `docker build --rm  -t app:next-demo .`
3. When build is done, run `docker run -it -e PORT=4200 -p 4200:4200 app:next-demo`
4. You will get an error: `Error: Cannot find module '@nrwl/next/plugins/with-nx'`. 

The repo is very minimal, one app - one library demo.  

### Failure Logs
```
$ next start -p 4200
Error: Cannot find module '@nrwl/next/plugins/with-nx'
Require stack:
- /usr/src/app/next.config.js
- /usr/src/app/node_modules/next/dist/next-server/server/config.js
- /usr/src/app/node_modules/next/dist/next-server/server/next-server.js
- /usr/src/app/node_modules/next/dist/server/next.js
- /usr/src/app/node_modules/next/dist/server/lib/start-server.js
- /usr/src/app/node_modules/next/dist/cli/next-start.js
- /usr/src/app/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/src/app/next.config.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/next.config.js',
    '/usr/src/app/node_modules/next/dist/next-server/server/config.js',
    '/usr/src/app/node_modules/next/dist/next-server/server/next-server.js',
    '/usr/src/app/node_modules/next/dist/server/next.js',
    '/usr/src/app/node_modules/next/dist/server/lib/start-server.js',
    '/usr/src/app/node_modules/next/dist/cli/next-start.js',
    '/usr/src/app/node_modules/next/dist/bin/next'
  ]
}
error Command failed with exit code 1.
```

### Environment

Node : 14.10.1
OS   : darwin x64
yarn : 1.22.4
  
nx : Not Found
@nrwl/angular : Not Found
@nrwl/cli : 11.3.1
@nrwl/cypress : 11.3.1
@nrwl/devkit : 11.3.1
@nrwl/eslint-plugin-nx : 11.3.1
@nrwl/express : Not Found
@nrwl/jest : 11.3.1
@nrwl/linter : 11.3.1
@nrwl/nest : Not Found
@nrwl/next : 11.3.1
@nrwl/node : Not Found
@nrwl/react : 11.3.1
@nrwl/schematics : Not Found
@nrwl/tao : 11.3.1
@nrwl/web : 11.3.1
@nrwl/workspace : 11.3.1
typescript : 4.0.7

**Comment by dionescu-shipserv** [comment]
Any help on this one? Any way to quickly get around the issue?

**Comment by kirjai** [comment]
Hey @dionescu-shipserv , thanks for filing the issue!

Is it fair to say that peer dependencies of your application's dependencies aren't being included? in that case, this issue seems related to #4506

**Comment by dionescu-shipserv** [comment]
Yes, it seems like it. Fair to say there's no fix for that yet?

**Comment by kirjai** [comment]
not yet, but it's something we're looking into

**Comment by kirjai** [comment]
should be fixed by #5014

**Comment by Uter1007** [comment]
hmm getting the same error again with newest nrwl/nx version (12.8.0). 

`Error: Cannot find module 'typescript'
Require stack:
- /dist/node_modules/@nrwl/workspace/src/utilities/typescript/compilation.js
- /dist/node_modules/@nrwl/workspace/src/utilities/typescript.js
- /dist/node_modules/@nrwl/workspace/src/core/target-project-locator.js
- /dist/node_modules/@nrwl/workspace/src/core/project-graph/build-dependencies/explicit-project-dependencies.js
- /dist/node_modules/@nrwl/workspace/src/core/project-graph/build-dependencies/index.js
- /dist/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js
- /dist/node_modules/@nrwl/workspace/src/core/file-utils.js
- /dist/node_modules/@nrwl/next/plugins/with-nx.js
- /dist/next.config.js
- /dist/node_modules/next/dist/server/config.js
- /dist/node_modules/next/dist/server/next.js
- /dist/node_modules/next/dist/server/lib/start-server.js
- /dist/node_modules/next/dist/cli/next-start.js
- /dist/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.mod._resolveFilename (/dist/node_modules/next/dist/build/webpack/require-hook.js:96:28)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/dist/node_modules/@nrwl/workspace/src/utilities/typescript/compilation.js:7:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/dist/node_modules/@nrwl/workspace/src/utilities/typescript/compilation.js',
    '/dist/node_modules/@nrwl/workspace/src/utilities/typescript.js',
    '/dist/node_modules/@nrwl/workspace/src/core/target-project-locator.js',
    '/dist/node_modules/@nrwl/workspace/src/core/project-graph/build-dependencies/explicit-project-dependencies.js',
    '/dist/node_modules/@nrwl/workspace/src/core/project-graph/build-dependencies/index.js',
    '/dist/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js',
    '/dist/node_modules/@nrwl/workspace/src/core/file-utils.js',
    '/dist/node_modules/@nrwl/next/plugins/with-nx.js',
    '/dist/next.config.js',
    '/dist/node_modules/next/dist/server/config.js',
    '/dist/node_modules/next/dist/server/next.js',
    '/dist/node_modules/next/dist/server/lib/start-server.js',
    '/dist/node_modules/next/dist/cli/next-start.js',
    '/dist/node_modules/next/dist/bin/next'
  ]
}
`
Already tried to install typescript globally in the docker file itsself.

**Comment by Uter1007** [comment]
hmm maybe it has something to do with my docker layering process (i build a docker base image and all nest / next apps in nx are just using it as a base image to speed up docker builds).

**Comment by amanintech** [comment]
+1 on this
