### ISSUE TITLE
externalSchematic is not executed in nx-plugin

### ISSUE THREAD

**Issue by mehrad-rafigh** [nrwl/nx#4869]
## Current Behavior
I am in the midst of replacing our workspace-generator with nx-plugin generators, due the inability and lacking documentation on how to test workspace generators. 

`externalSchematic` nor `schematic` are generating the files they actually should. 

## Expected Behavior
Running `externalSchematic` should work in a nx-plugin

## Steps to Reproduce
Create a nx-plugin
Use externalSchematic in generator

**Comment by vsavkin** [comment]
We are working on adding more docs right now, but this is what you need to do:

```
import { wrapAngularDevkitSchematic } from '@nrwl/devkit/ngcli-adapter';

const angularComponentGen = wrapAngularDevkitSchematic('@schematics/angular', 'component')
async function myGenerator(fileTree: Tree, opts) {
    await angularComponentGen(fileTree, {...}) // can be invoked as if it is written in Nx devkit
}
```
