### ISSUE TITLE
Support collectCoverageFrom option in JEST builder

### ISSUE THREAD

**Issue by splincode** [nrwl/nx#4880]
## Description

Not found `collectCoverageFrom` in
https://github.com/nrwl/nx/blob/master/packages/jest/src/executors/jest/schema.json

But we have 
https://jestjs.io/docs/en/cli#--collectcoveragefromglob

## Motivation

Add collect coverage from custom directories

## Suggested Implementation

```json
"test": {
      "builder": "@nrwl/jest:jest",
      "options": {
          "jestConfig": "jest.config.js",
          "coverageDirectory": "coverage/libs/core",
          "testPathPattern": ["libs/core/tests"],
          "collectCoverageFrom": ["libs/core/src/**/*.ts"],
          "passWithNoTests": true
      }
  }
```

**Comment by puku0x** [comment]
That is what I missed to display the coverage of all files. Thank you.
I added `collectCoverageFrom` into my `jest.preset.js` for now.

```js
module.exports = {
  ...require('@nrwl/jest/preset'),
  collectCoverageFrom: ['<rootDir>/src/**/*.{js,jsx,ts,tsx}'],
  transform: {
    '^.+\\.(ts|js|html)$': 'babel-jest',
  },
};
```

**Comment by ar-to** [comment]
Can this be reopened because it would be helpful to update @nrwl/jest:jest at https://nx.dev/l/a/jest/jest with `collectCoverageFrom`. I could not get it working manually on the CLI either with 
```
nx test {project name} --collectCoverageFrom="**/*.{js,jsx,tsx,ts}" 
``` 
for example, nor by configuring it as a new nx command. I had to create a new `jest.config.js` to add 
```
  collectCoverageFrom: [
    "**/*.{js,jsx,tsx,ts}",
  ]
```
which then it worked.

**Comment by rntvicente** [comment]
HI,

This issue have solution, Where you add `collectCoverageFrom`
