### ISSUE TITLE
NX_ env vars are not available for the next.js client part

### ISSUE THREAD

**Issue by quolpr** [nrwl/nx#4884]
## Current Behavior
NX_ env vars are not available for the next.js client part.

## Expected Behavior
NX_ env vars are available for the next.js client part.

I modified `next.config.js` to add support:

```
module.exports = withNx({
  webpack: (config, options) => {
    config.plugins.push(
      new webpack.EnvironmentPlugin(
        Object.keys(process.env).filter((k) => k.startsWith('NX_'))
      )
    );

    return config;
  }
});
```

### Environment
```
  Node : 15.2.1
  OS   : darwin x64
  yarn : 1.22.4

  nx : 11.2.12
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.12
  @nrwl/cypress : 11.2.12
  @nrwl/devkit : 11.2.12
  @nrwl/eslint-plugin-nx : 11.2.12
  @nrwl/express : 11.3.0
  @nrwl/jest : 11.2.12
  @nrwl/linter : 11.2.12
  @nrwl/nest : Not Found
  @nrwl/next : 11.2.12
  @nrwl/node : 11.3.0
  @nrwl/react : 11.2.12
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.12
  @nrwl/web : 11.2.12
  @nrwl/workspace : 11.2.12
  typescript : 4.1.5
```

**Comment by vsavkin** [comment]
Thank you for submitting the issue.

Can you talk more about your use case?  NX_  variables  are mainly used by Nx itself. Why would you want them to be available in the client part?

**Comment by quolpr** [comment]
@vsavkin , thank you for asking 🙂 We migrated from CRA, and it was the default way you can inject env variables to your app. So, for dev, we can have http://localhost endpoint, for staging staging.server.com, for prod prod.server.com. I successfully used them with NX React preset but failed with next.js(but they are available only at the server part)

**Comment by lwhiteley** [comment]
did you read the Nextjs environment variable documentation to verify?

>Note: In order to keep server-only secrets safe, Next.js replaces process.env.* with the correct values at build time. This means that process.env is not a standard JavaScript object, so you’re not able to use object destructuring. Environment variables must be referenced as e.g. process.env.NEXT_PUBLIC_PUBLISHABLE_KEY, not const { NEXT_PUBLIC_PUBLISHABLE_KEY } = process.env.

https://nextjs.org/docs/basic-features/environment-variables
