### ISSUE TITLE
getting error "Cannot find module '@nrwl/workspace/src/utilities/fileutils'"

### ISSUE THREAD

**Issue by sivani-pa** [nrwl/nx#4887]
Getting below error when trying to run "nx serve".

"Cannot find module '@nrwl/workspace/src/utilities/fileutils'"

**Comment by mandarini** [comment]
Hi there @sivani-pa ! Are you sure you're using the latest version of Nx? I think we fixed this issue. Can you please try and let me know?

**Comment by sivani-pa** [comment]
I just created a workspace and tried to start the application by running nx serve

After updating to @nrwl/workspace@11.3.1, the original error got resolved but getting the below new error,
Error: Cannot find module '@nrwl/workspace/src/utils/perf-logging'

Getting the same isssue when ran "nx report".

**Comment by grimmersnee** [comment]
yeah, i believe there is a bug when creating an empty workspace and then adding generators and applications as required.

The fix for me, is to create a workspace using a preset other than empty.

There is possibly something missing in the docs?

**Comment by mandarini** [comment]
@sivani-pa  @grimmersnee No, it should work in either case. Can I please see your `nx report`s?

**Comment by mandarini** [comment]
@sivani-pa I see you are saying "After updating to @nrwl/workspace@11.3.1". That means you had an older version and upgraded. Is your `@nrwl/cli` version aligned with the other `@nrwl/*` packages versions? If not, you can update that manually, `yarn add -D @nrwl/cli`.

Please try this out and let me know. This used to be a known issue, but I'm pretty sure we fixed it...

**Comment by mandarini** [comment]
@grimmersnee I just tried generating an empty workspace with `npx create-nx-workspace@latest` and then added apps and generators, and served, and it all worked good, I did not get any errors. I do see that there's the issue that @Nightbr mentioned here, I'll take a look there as well.

**Comment by mandarini** [comment]
@grimmersnee I just tried generating an empty workspace with `npx create-nx-workspace@latest` and then added apps and generators, and served, and it all worked good, I did not get any errors. I do see that there's the issue that @Nightbr mentioned here, I'll take a look there as well.

**Comment by mandarini** [comment]
Any remaining issues concerning `utils/utilities` paths and discrepancies are now solved with Nx [11.4.0](https://github.com/nrwl/nx/releases/tag/11.4.0). So I am closing this issue! 

Thank you all!

**Comment by sivani-pa** [comment]
> @sivani-pa I see you are saying "After updating to @nrwl/workspace@11.3.1". That means you had an older version and upgraded. Is your `@nrwl/cli` version aligned with the other `@nrwl/*` packages versions? If not, you can update that manually, `yarn add -D @nrwl/cli`.
> 
> Please try this out and let me know. This used to be a known issue, but I'm pretty sure we fixed it with [this PR](https://github.com/nrwl/nx/pull/4750)...

thanks @mandarini updating `@nrwl/cli` to latest version resolved the issue.

**Comment by nhhockeyplayer** [comment]
How would one fix nx report ?

```
meanstack02@admin energy % nx report
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '@nrwl/workspace/src/utilities/perf-logging'
Require stack:
- /Users/meanstack02/node_modules/@nrwl/cli/lib/init-local.js
- /Users/meanstack02/node_modules/@nrwl/cli/bin/nx.js
- /Users/meanstack02/.config/yarn/global/node_modules/@nrwl/cli/bin/nx.js
- /Users/meanstack02/.config/yarn/global/node_modules/nx/bin/nx.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/Users/meanstack02/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.initLocal (/Users/meanstack02/node_modules/@nrwl/cli/lib/init-local.js:17:5)
    at Object.<anonymous> (/Users/meanstack02/node_modules/@nrwl/cli/bin/nx.js:43:18)
    at Module._compile (/Users/meanstack02/.config/yarn/global/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/meanstack02/node_modules/@nrwl/cli/lib/init-local.js',
    '/Users/meanstack02/node_modules/@nrwl/cli/bin/nx.js',
    '/Users/meanstack02/.config/yarn/global/node_modules/@nrwl/cli/bin/nx.js',
    '/Users/meanstack02/.config/yarn/global/node_modules/nx/bin/nx.js'
  ]
}
meanstack02@admin energy 
```

**Comment by nhhockeyplayer** [comment]
could this be why Nrwl/Nx is forcing the actual global product to be at latest ?

I manually forced everything back to 11.6.3 in my package.json

so I can roll back to angular@11

cant even check version either same error

meanstack02@admin energy % grep nrwl package.json 
    "@nrwl/workspace": "11.6.3",
    "@nrwl/angular": "11.6.3",
    "@nrwl/cli": "11.6.3",
    "@nrwl/cypress": "^12.5.1",
    "@nrwl/eslint-plugin-nx": "^12.5.1",
    "@nrwl/jest": "^12.3.5",
    "@nrwl/linter": "^12.5.1",
    "@nrwl/nest": "^12.5.1",
    "@nrwl/node": "^12.5.1",
    "@nrwl/nx-cloud": "^12.2.7",
    "@nrwl/schematics": "^8.12.11",
    "@nrwl/tao": "^12.5.1",

**Comment by nhhockeyplayer** [comment]
spo its something within my workspace tripping everything up

I did version in a totally different project with success

```
meanstack02@admin twelve % nx --version
12.3.5
```

my main issue is I am strong-armed to 12.3.5

and I just want to be at 11.6.3
and have had no success rolling nx back to that revision

all yarn and npm is forcing me to be with latest from former migration

does anyone know a quickj workaround to get me to 11.6.3 for nx ?

thank in advance
