### ISSUE TITLE
Nx affected - success but commands exited with non-zero status code

### ISSUE THREAD

**Issue by damianroszyk** [nrwl/nx#4892]
Hi there! 
I have a problem with `nx affected --target` command.

When I run nx affected --target universal --parallel and in angular.json I have ->
```
"universal": {
  "builder": "@nrwl/workspace:run-commands",
  "options": {
    "commands": [
      {
        "command": "npm run build:wizard"
      }
    ]
  }
},
```
(universal is my custom target)

Here is the output (simplified) 
```
npm ERR! A complete log of this run can be found in:
npm ERR!     xxx
Warning: @nrwl/run-commands command "npm run build:wizard" exited with non-zero status code
———————————————————————————————————————————————

 NX   SUCCESS  Running target "universal" succeeded
```

I'd like to have an error there to break pipeline. Anyone has encountered this or know how to fix my problem ?

( I think I land here in code https://github.com/nrwl/nx/blob/master/packages/workspace/src/executors/run-commands/run-commands.impl.ts#L115 so I would expect not to be a SUCCESS )

## Current Behavior
There is a NX SUCCESS and process does not break

## Expected Behavior

I think that in my scenario nx affected should break and display ERROR rather than SUCCESS

**Comment by underfisk** [comment]
I do have the same issue, my Dockerfile builds the Nx affected project but with errors but the result from Nx is a positive status code which does not provoke docker to mark it as failed and still proceeds, i'm looking forward to a solution also on this

**Comment by FrozenPandaz** [comment]
What version of Nx is being used here?

A fix for this was included in `11.3.2` so please retry with the latest version.

**Comment by underfisk** [comment]
@FrozenPandaz I have downloaded the version, i'll test it and give also feedback in here if the issue is solved in my project

**Comment by damianroszyk** [comment]
@FrozenPandaz thanks for your input! I have checked `11.3.2` and it works like a charm ( fails as expected ) 

( I was on 11.0.2 before )
