### ISSUE TITLE
Nestjs app start does not use updated files after files changed

### ISSUE THREAD

**Issue by underfisk** [nrwl/nx#4894]
## Current Behavior
So if i start the Nx project (my nestjs application) and i update something after Nx webpack reloads the app it does not start with the updated files, it comes outdated and this is very frustrating because we spin around thinking it is still bugged but it requires me to stop the nx start command and start it again otherwise it keeps looping with the previous version of the file.
Also another thing that happens often is that the app when booting, it does twice which can introduce issues to me when doing tasks at modules bootstrap

## Expected Behavior
When i change something i want webpack to reload but with the new files

## Steps to Reproduce

Simply create a new Nestjs app using the official nx generator, change something (just create a console log will be sufficient) and see that if you change the message inside just for debugging purposes, it does not reload the app with the updated version, will always be the first that the webpack started off

### Failure Logs

There are no errors associated

### Environment

  Node : 14.15.5
  OS   : darwin x64
  pnpm : 5.17.3
  
  nx : 11.2.12
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.12
  @nrwl/cypress : Not Found
  @nrwl/devkit : Not Found
  @nrwl/eslint-plugin-nx : 11.2.12
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.12
  @nrwl/linter : 11.2.12
  @nrwl/nest : 11.2.12
  @nrwl/next : 11.3.0
  @nrwl/node : 11.2.12
  @nrwl/react : 11.3.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.12
  @nrwl/web : Not Found
  @nrwl/workspace : 11.2.12
  typescript : 4.0.7

**Comment by alejandrocoding** [comment]
Hi @underfisk, thanks for reporting the issue

Can you share what command are you running? (I used: nx serve nest-app)
Also, can you confirm that creating a new project with Nest, it behaves the same way?

I've created a new project with Nest and hot-reloading is working just fine, not sure if I am missing something.

**Comment by underfisk** [comment]
I do use the serve alias in package.json "start". Yes creating a new project happens the same also the double app bootstrapping happens, not sure if it might be affecting when the app is much bigger due to the fact it has to run the type checking but it isn't supposed to run twice

**Comment by alejandrocoding** [comment]
I used the same exact version of Node and Nx to generate a new project and run it by the start script entry in package, but I do see only one bootstrapping process being triggered and hot reloading is working fine. I couldn't manage to reproduce so maybe you can share a repo to discard that maybe this error is produced on your machine for any other external reason? maybe trying in another machine might help. Sorry I couldn't help more.

**Comment by underfisk** [comment]
My project indeed is really giant, sharing it in a repo is hard because i can't create a reproduction of this size.
There are no errors produced, the app starts and in the middle while its boostraping (it takes a bit longer in my nestjs app because its a giant monolith) it will add the version time + typescript version + type errors result in the middle but also i noticed the app when that happens, reloads again and bootstraps from the ground which makes it booting twice every time a change happen or even the first load
Can you try then a bigger project, not sure about any example but in our microservices, this is not happening which is strange but they are really small compared to the giant app, might be related to the size of the app? 
Before the migration to Nx, the nestjs CLI was working really fast, now each time i change something it takes a bit longer, is there also any way i can use nestjs CLI as the runner? It might sound a bit dumb but the CLI was working fine without any issues or is there any way i can tell the default Nx runner to skip type checking (which might be the issue that causes the double boostrap?)

**Comment by tiagomnferreira-mzt** [comment]
Having the same problem, changing some files isn't updating them and the hot reload doesn't work sometimes. I'm currently migrating a project to NX and until now everything was running smoothly.

**Comment by demisx** [comment]
I've also noticed that Nx v12.10.0 with NestJS v8 doesn't reload when a TypeScript interface file changes but it does reload when a class changes. So, errors in the interfaces don't show up in the log. Is this expected because interfaces don't exist at runtime?

**Comment by wSedlacek** [comment]
I have been seeing this too with NestJS 8

**Comment by wSedlacek** [comment]
For me the issue was having `buildLibsFromSource` set to false.

**Comment by Alex44lel** [comment]
> Same behaviour observed in our project. The hot reload seems to be properly triggered, but it uses the old files. For instance, if I add a `console.log` in a controller and save the file, it will reload, but the newly inserted log never gets printed. Stoping and restarting the app results in the log being properly printed.

Hi, did you manage to solve this issue? I am getting the same problem with "npm run start:dev". I have tried to uninstall evything, update node, npm ... but nothing seems to work. It only works if i manually restart the server.

**Comment by cantoute** [comment]
Having exactly same issue...

Out of nowhere I now have to save twice dev server to apply changes.

It's like if dev server rebuilds on previous save.

Anyone manage to solve this ?

**Comment by JudaristFullstackProCoder** [comment]
I couldn't see the changes I made to my source code for two days now, because I had two routes that each took a param

**@Get(":id")**
handler1 ( ) { ... }

@Get(":user")
handler2 ( ) { ... }

and the route @Get(":id") always executed instead of @Get(":user")

to fix the error I changed like this:

@Get(":id")
handler1( ) { ... }

@Get("/user/:user")
handler2() { ... }

If someone has made a mistake like this in the order of their http controller functions it might help!

**Comment by cantoute** [comment]
JudaristFullstackProCoder ... ok cool, what has it got to do here ?

**Comment by cantoute** [comment]
By the way, I've managed to solve the problem I had of changes not showing.

Actually they would show if I saved twice and it has something to do with `enableShutdownHooks()` hooks.

I had copied those hooks from the official documentation.  They are mendatory so I just commented them out.

```ts
  // brakes watch mode start:dev - it reload with previous saved, not current
  // const prismaService = app.get(PrismaService);
  // await prismaService.enableShutdownHooks(app);
```

**Comment by bill-kasa** [comment]
> I've also noticed that Nx v12.10.0 with NestJS v8 doesn't reload when a TypeScript interface file changes but it does reload when a class changes. So, errors in the interfaces don't show up in the log. Is this expected because interfaces don't exist at runtime?

I am having this problem currently. 
I'm using NX v15.2.1, React v18.1 and Node v18.12.1.

If I make a change to a type definition in my code, the NX webpack dev server does not detect the change and does not rebuild. I have to kill the server and restart any time I change a type. This is slowing me down immensely. Does anyone know of a fix for this issue?
