### ISSUE TITLE
Missing typescript dependency 

### ISSUE THREAD

**Issue by lokeshdaiya** [nrwl/nx#4895]
## Current Behavior

Getting error while running below command to generate angular application 

` ng new --collection @nrwl/angular`

![image](https://user-images.githubusercontent.com/7831299/109163072-ef676180-779e-11eb-9de4-935997cb027e.png)

## Expected Behavior

Application should be generated without any error.

## Steps to Reproduce

1. install `@angular/cli` `@nrwl/angular` and `@nrwl/workspace` globally.
2. Run command  ` ng new --collection @nrwl/angular`

### Environment
Angular cli : 11+
nrwl/angular: 11.3.1

**Comment by vsavkin** [comment]
Thank you for submitting the issue.

@nrwl/angular isn't a schematics collection that can be used with ng new. It doesn't have the new schematic.

This is how you create a new angular workspace using Nx: `npx create-nx-workspace --preset=angular`.

See more here: https://nx.dev/angular
