### ISSUE TITLE
Cypress not using the plugins file configuration

### ISSUE THREAD

**Issue by KarmaCop213** [nrwl/nx#4910]
## Current Behavior
I have the following configuration in my plugins file(`plugins/index.js`) inside a folder I have with several e2e tests:
```javascript
  on("file:preprocessor", preprocessTypescript(config, customizeWebpackConfig))

  function customizeWebpackConfig(webPackConfig) {
    webPackConfig.module.rules.push({
      test: /\.graphql$/,
      exclude: /node_modules/,
      loader: 'graphql-tag/loader',
    })

    return webPackConfig;
  }
```

If I run the e2e tests with `nx e2e --watch` the tests run correctly.

If I run the e2e tests with `npx cypress run` the tests run correctly.

If I run the e2e tests with `nx e2e` I get the following errors:
```
Oops...we found an error preparing this test file:

  src/integration/xxx.ts

The error was:

Error: Webpack Compilation Error
my.service.ts
ERROR in my.service.ts(25,34):
TS2307: Cannot find module './graphql/my.query.graphql' or its corresponding type declarations.

my.service.ts(26,47):
TS2307: Cannot find module './graphql/my.mutation.graphql' or its corresponding type declarations.
```

## Expected Behavior
I was expecting to see the e2e tests running using `nx e2e`

## Steps to Reproduce
It seems to be a simple error of not honouring the plugins file. I have the graphql support there, I can run correctly the tests with `nx e2e --watch` and with `npx cypress run --spec "src/integration/send-order.spec.ts"`

### Environment
```
  nx : Not Found
  @nrwl/angular : 10.4.0
  @nrwl/cli : 10.4.0
  @nrwl/cypress : 10.4.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.4.0
  @nrwl/linter : 10.4.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.4.0
  @nrwl/web : Not Found
  @nrwl/workspace : 10.4.0
  typescript : 4.0.7
```

**Comment by KarmaCop213** [comment]
I found the issue while I was creating a simple example to show you the behaviour.

Turns out I was using a configuration on my `tsconfig.app.json` like so:
`  "include": ["src/**/*.ts", "src/**/*.js", "../../@types/__types-for-graphql.d.ts"]`

and `__types-for-graphql.d.ts` was like the following:
```
declare module "*.graphql" {
  import { DocumentNode } from "graphql"
  const Schema: DocumentNode

  export = Schema
}
```

The problem was that I didn't have that last include on my `tsconfig.e2e.json`. Error message didn't help at all! :disappointed:

You can close this. Keep up with the good work!

**Comment by FrozenPandaz** [comment]
I'm glad you found your solution. :smiley:
