### ISSUE TITLE
Error generating a new React library (Cannot find module '@nrwl/workspace/src/utilities/run-tasks-in-serial')

### ISSUE THREAD

**Issue by underfisk** [nrwl/nx#4915]
## Current Behavior
When i attempt to generate a new library i get the following error (Cannot find module '@nrwl/workspace/src/utilities/run-tasks-in-serial')

## Expected Behavior
Generate correctly

## Steps to Reproduce
Install the CLI and just try to create a new react lib

### Environment
  Node : 14.15.5
  OS   : darwin x64
  pnpm : 5.17.3
  
  nx : 11.2.12
  @nrwl/angular : Not Found
  @nrwl/cli : 11.3.2
  @nrwl/cypress : Not Found
  @nrwl/devkit : Not Found
  @nrwl/eslint-plugin-nx : 11.2.12
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.12
  @nrwl/linter : 11.2.12
  @nrwl/nest : 11.2.12
  @nrwl/next : 11.3.0
  @nrwl/node : 11.2.12
  @nrwl/react : 11.3.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.12
  @nrwl/web : Not Found
  @nrwl/workspace : 11.2.12
  typescript : 4.0.7

**Comment by mandarini** [comment]
Hi there @underfisk ! Thanks for filing an issue!
 
Your issue will be resolved if you update your `@nrwl/*` packages versions to match your `@nrwl/cli` version. In general, your `@nrwl/*` packages versions and your `@nrwl/cli` version should be in sync. This is a known issue when the package versions are out of sync. I am closing this issue now. Let me know if it persists when all versions are in sync, and I can reopen.

**Comment by underfisk** [comment]
@mandarini I couldn't find any information about this issue anywhere, i'll try to check that but its very weird indeed

**Comment by underfisk** [comment]
@mandarini I did upgrade and now i can't boostrap my nextjs apps, check the latest issue #4923
