### ISSUE TITLE
frontEndProject flag not working

### ISSUE THREAD

**Issue by SubJunk** [nrwl/nx#4918]
## Current Behavior
Passing `--frontEndProject` does not set `proxyConfig`, and therefore requests from the front-end do not make it to the back-end. I generated the app using `nx g @nrwl/express:app api --frontEndProject=my-site`, following the instructions on nxplaybook.com

I also experienced the same bug when following the tutorials on YouTube directly, so I have reproduced it twice.

## Expected Behavior
I expected it to create the config settings described on this page https://nx.dev/latest/react/tutorial/06-proxy

## Steps to Reproduce
I followed the steps on video 4 on nxplaybook.com https://nxplaybook.com/courses/709074/lectures/12735574

### Environment
  Node : 12.15.0
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.3.2
  @nrwl/cypress : 11.3.2
  @nrwl/devkit : 11.3.2
  @nrwl/eslint-plugin-nx : 11.3.2
  @nrwl/express : 11.4.0
  @nrwl/jest : 11.3.2
  @nrwl/linter : 11.3.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.4.0
  @nrwl/react : 11.3.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.3.2
  @nrwl/web : 11.3.2
  @nrwl/workspace : 11.3.2
  typescript : 4.0.7

**Comment by FrozenPandaz** [comment]
There's a typo in how you passed the flag. The "E" in `frontend` is lowercase:

```diff
+ --frontendProject=my-site
- --frontEndProject=my-site

**Comment by SubJunk** [comment]
@FrozenPandaz I'm not sure why you think that - I pasted the exact command I used above, and I have gone back in my terminal history to verify it:

![image](https://user-images.githubusercontent.com/584228/109548925-212b5000-7b32-11eb-95de-156722116b4b.png)

**Comment by SubJunk** [comment]
That was it, thank you!
