### ISSUE TITLE
Better error/exception stack errors

### ISSUE THREAD

**Issue by underfisk** [nrwl/nx#4924]
## Description
So one thing that tends to happen often is error/exceptions and in order to handle them or be a little bit autonomous, we need to see the error shape. Right now with Nx i feel that that's taken out of hand, when something happens i just see a message but i need sometimes to see its stack to understand where it comes from or even have some guidelines

## Motivation
Having a better error debugging in general for the CLI/commands

## Suggested Implementation
Either we provide a flag to enable debug and the whole stack shows up or something like that (what i'm saying is if you don't want this behaviour to be by default, then some flag to turn it on/off) or it comes by default for everyone but most people will find this really useful because Nx is for developers and developers need real control over some aspects

## Alternate Implementations
I'm not sure if there's something similar on Nx of what i'm suggesting but i'm open to alternatives or suggestions, i just want the error's debug to be better

**Comment by FrozenPandaz** [comment]
I believe the `--verbose` flag does what you want. It prints the stacktrace along with the error.

**Comment by underfisk** [comment]
@FrozenPandaz Oh okay, nice to hear that the flag exists, thanks
