### ISSUE TITLE
Getting nx lint error from putting tslint.json file in libs

### ISSUE THREAD

**Issue by dotDeeka** [nrwl/nx#493]
I want to have a different set of linter rules for my libs than for my apps, so I have a ```libs/tslint.json``` which has the rules for all libs. Running ```nx lint```  returns

```
All files in 'apps' and 'libs' must be part of a project.:
The 'libs/tslint.json' file doesn't belong to any project.
```
It would be useful to allow files like this here. Is this something you guys would consider adding? Or, is there some way to configure it that I'm missing.

**Comment by dotDeeka** [comment]
yeah, while that isn't ideal to have a team of devs need to remember to do that if they create a lib, it will have the desired effect at the moment

**Comment by jschwarty** [comment]
You could also explore creating a [custom workspace schematic](https://nrwl.io/nx/workspace-specific-schematics) that calls the lib schematic and just alters the tsconfig file to make that change.

**Comment by dotDeeka** [comment]
That would also work. Feels like a pretty big hack though when tslint was designed to be hierarchical, and nx breaks that.

**Comment by vsavkin** [comment]
@dotDeeka 

> tslint was designed to be hierarchical

I didn't know tslint implicitly inherits from an ancestor. I though only eslint does it. 

Does creating `libs/tslint.json` change the behavior of your libs' lint checks?

**Comment by dotDeeka** [comment]
@vsavkin it looks like I was a little confused how tslint's inheritance works. It doesn't support configuration cascading the way eslint does, you are correct. They have an issue open for it (https://github.com/palantir/tslint/issues/2302)

tslint does support the extends property though (which I'm using), and files located in the ```libs/**/*``` directories do use the ```libs/tslint.json``` to get there rules.

My set up is
```<root>/tslint.json```

```json
{
  "rulesDirectory": [
    "node_modules/codelyzer",
    "node_modules/@nrwl/schematics/src/tslint"
  ],
  "rules": {
    // ... other rules here
    "directive-selector": [
      true,
      "attribute",
      "pn",
      "camelCase"
    ],
    "component-selector": [
      true,
      "element",
      "pn",
      "kebab-case"
    ],
  }
}
```

Then in my ```<root>/libs/tslint.json``` I override the directive and component selectors in libs to 
have d different prefix

```json
{
  "extends": [
    "../tslint.json"
  ],
  "rules": {
    "directive-selector": [
      true,
      "attribute",
      "intx",
      "camelCase"
    ],
    "component-selector": [
      true,
      "element",
      "intx",
      "kebab-case"
    ],
  }
}

```

This config will lint that all components and directives in ```libs/``` use ```intx``` as their prefix and all components and directives in our apps directories use ```pn``` as their prefix.

I can create an example repo for you guys if that makes it easier for you to check it out?

**Comment by vsavkin** [comment]
Sorry for the late response. 

I believe Nx 6, which is based on CLI 6, does what you are trying to do. Could you confirm it?

**Comment by bcabanes** [comment]
Closing, no answer.

**Comment by Jordan-Hall** [comment]
@vsavkin doesn't appear to be fixed.

```
>  NX   ERROR  The following file(s) do not belong to any projects:

  - libs/grouping-folder/tslint.json
```
