### ISSUE TITLE
The Incremental build and serve require network access

### ISSUE THREAD

**Issue by junekpavel** [nrwl/nx#4936]
## Current Behavior
During the build, network access is required many times.

## Expected Behavior
The network access should not be required and build should not be failing because of it.

## Steps to Reproduce

The issue can be reproduced in nx-incremental-large-repo after updating to version >= 11.2 by running build command.

https://github.com/junekpavel/nx-incremental-large-repo/tree/build-issues

### Failure Logs
```
ERROR: Timed out waiting for sync-rpc server to start (it should respond with "pong" when sent "ping"):


events.js:173

      throw er; // Unhandled 'error' event

      ^

Error: connect ECONNREFUSED 127.0.0.1:37683

    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)

Emitted 'error' event at:

    at emitErrorNT (internal/streams/destroy.js:91:8)

    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)

    at processTicksAndRejections (internal/process/task_queues.js:84:9)

```

### Environment
```
  Node : 12.16.2
  OS   : darwin x64
  yarn : 1.22.0
  
  nx : Not Found
  @nrwl/angular : 11.4.0
  @nrwl/cli : 11.4.0
  @nrwl/cypress : 11.4.0
  @nrwl/devkit : 11.4.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.4.0
  @nrwl/linter : 11.4.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.4.0
  @nrwl/web : 11.4.0
  @nrwl/workspace : 11.4.0
  typescript : 4.0.3
```

**Comment by junekpavel** [comment]
Hi @FrozenPandaz, may I politely ask if there is any plan about resolving this issue? 

Unfortunately, because of this problem, we cannot migrate to new nx versions and we are forced to stay at older ones.

**Comment by cenda** [comment]
Same problem as mentioned by @junekpavel - `nx` upgrade blocked with this issue

**Comment by ondrejsyrovy** [comment]
I'm joining the waiting list for this issue. Thanks.

**Comment by junekpavel** [comment]
I'm still facing this issue.

But in addition to build, the same issue appeared also for dev server (nx serve) after switching to incremental build.

After adding `@nrwl/web:file-server` as builder for dev server, the very same way as @juristr did in example repo (https://github.com/nrwl/nx-incremental-large-repo/commit/8968693e0abab34e82e442ca4ec97306a94c5cf9), and also as described in documentation (https://nx.dev/latest/angular/ci/setup-incremental-builds-angular), I keep getting these (macOS firewall) errors during serve (more than 100 of these popups per rebuild)

![](https://raw.githubusercontent.com/junekpavel/nx-incremental-large-repo/build-issues/node-firewall.png)


Anyone having (or had) same issues? Or at least any suggestions how to get rid of those popups?

**Comment by junekpavel** [comment]
Seems like the source of this issue is that both `@nrwl/angular:ng-packagr-lite` and `@nrwl/angular:webpack-browser` builders are depending on unmaintained `sync-rpc` library (via https://github.com/ForbesLindesay/sync-rpc/pull/12).

Is there any solution for that? Use something another instead of `sync-rpc`?

**Comment by junekpavel** [comment]
Updated to nx 12 and problem is fixed...
