### ISSUE TITLE
generatePackageJson adds @angular/{common/core} to Node project

### ISSUE THREAD

**Issue by the-ult** [nrwl/nx#4939]
## Current Behavior
We've got an Apollo/Express graphql-server and are using `"generatePackageJson": true,` to generate the `package.json` for the production build of the graphql-server.

The generated `package.json` adds `@angular/common` and `@angular/core` as dependencies, while it isn't an Angular project. And `@angular/...` is not used in the project.

## Expected Behavior
The generated `package.json` should not include the `@angular/..` dependencies

## Steps to Reproduce

The generated package.json
```json
{
  "name": "my-graphql-server",
  "version": "0.0.1",
  "main": "main.js",
  "dependencies": {
    "@angular/common": "11.2.3",  // would not expect the package.json to have these
    "@angular/core": "11.2.3",  // would not expect the package.json to have these
    "apollo-datasource-rest": "0.10.0",
    "apollo-server-express": "2.21.0",
    "compression": "1.7.4",
    "express": "4.17.1",
    "graphql-import-node": "0.0.4",
    "graphql-modules": "1.4.1",
    "graphql-scalars": "~1.8.0",
    "graphql-subscriptions": "1.2.0",
    "graphql": "15.5.0",
    "js-yaml": "4.0.0",
    "log4js": "6.3.0",
    "reflect-metadata": "0.1.13",
    "rxjs": "6.6.6"
  }
}
```

`angular.json`
```json
"my-graphql-server": {
      "root": "apps/my-graphql-server",
      "sourceRoot": "apps/my-graphql-server/src",
      "projectType": "application",
      "prefix": "my",
      "architect": {
        "build": {
          "builder": "@nrwl/node:build",
          "outputs": ["{options.outputPath}"],
          "options": {
            "webpackConfig": "apps/my-graphql-server/webpack.config.js",
            "outputPath": "dist/apps/my-graphql-server",
            "main": "apps/my-graphql-server/src/main.ts",
            "tsConfig": "apps/my-graphql-server/tsconfig.app.json",
            "assets": ["apps/my-graphql-server/src/assets"],
            "generatePackageJson": true,
            "buildLibsFromSource": true
          },
          "configurations": {
            "production": {
              "optimization": true,
              "extractLicenses": true,
              "inspect": false,
              "fileReplacements": [
                {
                  "replace": "apps/my-graphql-server/src/environments/environment.ts",
                  "with": "apps/my-graphql-server/src/environments/environment.prod.ts"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@nrwl/node:execute",
          "options": {
            "buildTarget": "my-graphql-server:build"
          }
        },
        ...
       }
    },
```

### Environment
```
❯ nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.15.4
  OS   : darwin x64
  npm  : 6.14.11
  
  nx : Not Found
  @nrwl/angular : 11.4.0
  @nrwl/cli : 11.4.0
  @nrwl/cypress : 11.4.0
  @nrwl/devkit : 11.4.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : 11.4.0
  @nrwl/jest : 11.4.0
  @nrwl/linter : 11.4.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.4.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.4.0
  @nrwl/web : Not Found
  @nrwl/workspace : 11.4.0
  typescript : 4.1.5
```

**Comment by bekos** [comment]
@the-ult it would be really helpful if you can share a repro repo. Can you also check if your issue is solved using `11.6.0-beta.4`?

**Comment by the-ult** [comment]
Hi, sharing the repo would be difficult.
Might be able to reproduce it in stackblitz or something..

But I wil try the `beta.4` 👍

**Comment by the-ult** [comment]
The beta seems to be working 👍 

```
❯ nx build ddb-graphql-server --prod

> nx run ddb-graphql-server:build:production 
```
```
❯ nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.16.0
  OS   : darwin x64
  npm  : 6.14.11
  
  nx : Not Found
  @nrwl/angular : 11.6.0-beta.4
  @nrwl/cli : 11.6.0-beta.4
  @nrwl/cypress : 11.6.0-beta.4
  @nrwl/devkit : 11.6.0-beta.4
  @nrwl/eslint-plugin-nx : 11.6.0-beta.4
  @nrwl/express : 11.6.0-beta.4
  @nrwl/jest : 11.6.0-beta.4
  @nrwl/linter : 11.6.0-beta.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.6.0-beta.4
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.6.0-beta.4
  @nrwl/web : Not Found
  @nrwl/workspace : 11.6.0-beta.4
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

![Screenshot 2021-03-29 at 10 14 04](https://user-images.githubusercontent.com/4863062/112806821-801fae80-9077-11eb-885b-3388fe4e6ad7.png)

**Comment by bekos** [comment]
@the-ult Thanks for trying it out and debugging this 👍 This sounds like an issue with our project graph calculation 🤔 tbh, I am not super familiar with that part of the code but if you can create a a minimal repro I can investigate it.

**Comment by the-ult** [comment]
Thanks.
I will try and create a minimal test repo 👍 
(might take a couple days)

**Comment by the-ult** [comment]
Hi @bekos 
Here is a sample repo: https://github.com/the-ult/nx-node-package-problem

`npm run build express-app -- --prod`
produces:
```
{
  "name": "express-app",
  "version": "0.0.1",
  "dependencies": {
    "@angular/core": "~11.2.7",
    "rxjs": "~6.6.3",
    "zone.js": "^0.10.2",
    "@angular/common": "~11.2.7",
    "@angular/platform-browser-dynamic": "~11.2.7",
    "@angular/compiler": "~11.2.7",
    "@angular/platform-browser": "~11.2.7",
    "@angular/animations": "~11.2.7",
    "express": "4.17.1"
  },
  "main": "main.js"
}

```

<img width="1255" alt="Screenshot 2021-03-31 at 20 37 16" src="https://user-images.githubusercontent.com/4863062/113193993-e4519680-9260-11eb-86dc-5a1375a7c301.png">

**Comment by the-ult** [comment]
@bekos have you had any chance to try the sample repo?

**Comment by bekos** [comment]
@the-ult I took a look, and based on the current implementation, I'm afraid there is no workaround with the current implementation, as Nx calculates dependencies based on the relation of the files and not on the actual import.

An alternative suggestion is to use something like `depcheck` on the build files to calculate the actual dependencies, or populate the `package.json` yourself 😞

**Comment by the-ult** [comment]
Thanks for looking into it

**Comment by bekos** [comment]
Closing as it is not actionable atm, imo the best approach in these cases is to generate (even manually) the appropriate `package.json`.

**Comment by the-ult** [comment]
Ok.. found out what caused the problem.

We were using/importing an `environment.model.ts` from `shared/environment` which had the Interface for the environment.

```ts
import { GraphQLEnvironment } from '@ddb/shared/environment';

export const environment: GraphQLEnvironment = { 
  ...
}
```

However.. The `shared/environment` package also has an `shared-environment.module.ts` and `EnvironmentService` for our Angular projects.
```ts
// shared/environment/src/index.ts
export * from './lib/shared-environment.module';
export * from './lib/environment-versions';
export * from './lib/environment.model';
export { DdbEnvironmentService } from './lib/environment.service';
```

I was in the (_wrong_) assumption that only actually used/imported files would be used. But it seems when you import 1 item from the package.. Alle files/dependencies of the `index.ts` will be used and seen as `peerDependency`.

Will this not be the case if we use (better) secondary-entrypoints / barrel files?
