### ISSUE TITLE
Deployment on Vercel fails. Error: No server pages were built.

### ISSUE THREAD

**Issue by aiji42** [nrwl/nx#4941]
## Current Behavior
Deploy Nextjs monorepo gets an error on Vercel.

## Steps to Reproduce
1. Create nx workspace with Nextjs preset.
2. Go to Vercel account.
3. Import repository.
4. Modify default commands on Vercel (follow the [official documentation](https://nx.dev/latest/react/guides/nextjs#deploying-to-vercel)):
![スクリーンショット 2021-03-04 19 00 18](https://user-images.githubusercontent.com/6711766/109946739-e97ffc00-7d1b-11eb-8e38-3df2859f9e14.png)

### Failure Logs
`Error: No server pages were built. Learn More: https://err.sh/vercel/vercel/now-next-no-serverless-pages-built` 

![スクリーンショット 2021-03-04 19 01 19](https://user-images.githubusercontent.com/6711766/109946836-06b4ca80-7d1c-11eb-9ccb-6823aa9887bd.png)

### Environment
`next.config.js`

![スクリーンショット 2021-03-04 19 05 46](https://user-images.githubusercontent.com/6711766/109947772-09fc8600-7d1d-11eb-9176-361652cb884e.png)

```
 Node : 14.13.1
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.4.0
  @nrwl/cypress : 11.4.0
  @nrwl/devkit : 11.4.0
  @nrwl/eslint-plugin-nx : 11.4.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.4.0
  @nrwl/linter : 11.4.0
  @nrwl/nest : Not Found
  @nrwl/next : 11.4.0
  @nrwl/node : Not Found
  @nrwl/react : 11.4.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.4.0
  @nrwl/web : 11.4.0
  @nrwl/workspace : 11.4.0
  typescript : 4.1.5
```

**Comment by aiji42** [comment]
When I stopped using `withNx` in `next.config.js` and set `serverless` or `experimental-serverless-trace` as target, the above error was resolved.

```js
module.exports = {
  target: 'experimental-serverless-trace', // or 'serverless'
  trailingSlash: true,
  reactStrictMode: true,
  env: ...
}
```

**Comment by aiji42** [comment]
The log reports a message that withNx detected vercel and tried to adapt experimental-serverless-trace. However, I don't think this value is actually applied.

![スクリーンショット 2021-03-05 11 27 09](https://user-images.githubusercontent.com/6711766/110058495-bf731c00-7da5-11eb-9e30-308c869380c6.png)

**Comment by aiji42** [comment]
https://github.com/nrwl/nx/blob/a25e081a84509d83db5c5c4c27d2898dcad79f65/packages/next/plugins/with-nx.ts
It certainly seems that `experimental-serverless-trace` is set in the build stage.  
This is just my prediction, but I think `process.env.NOW_BUILDER` will be false at the time of actual execution.

**Comment by aiji42** [comment]
It seems that my thoughts above were correct. I forced `process.env.NOW_BUILDER` to be true, and the deployment completed correctly.

![スクリーンショット 2021-03-05 13 39 09](https://user-images.githubusercontent.com/6711766/110068157-6e205800-7db8-11eb-9043-81b95b2e9575.png)

**Comment by aiji42** [comment]
I finally worked around this bug by setting it this way.
```js
module.exports = withNx({
  target: 'experimental-serverless-trace', // <-
  trailingSlash: true,
  reactStrictMode: true,
  env: ...
})
```

**Comment by kirjai** [comment]
hey @aiji42 ! thanks for reporting this and for extensive feedback based on your deep investigation!

i'm struggling to recreate this issue myself, to be honest.
`NOW_BUILDER` seems to be set correctly for vercel builds for me.

similarly to how you forced `NOW_BUILDER` to be set to `true`, what about if you instead log out the whole `process.env` object?
```js
// next.config.json
console.log('ENV', process.env);

module.exports = withNx({...});
```

can you post what that returns during your build? obviously, omitting sensitive info

**Comment by aiji42** [comment]
I tried to reproduce the bug earlier, but I couldn't reproduce it. It seems that the problem has already been resolved.
