### ISSUE TITLE
Storybook starts with NODE_ENV='production'

### ISSUE THREAD

**Issue by pitops** [nrwl/nx#4942]
## Current Behavior
I am wondering why storybook starts with a NODE_ENV of `production` instead of development? Also of note that just happened to realise, is that the `nx report` command is not listing the `@nrwl/storybook` package

```
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.3.1
  @nrwl/cypress : 10.4.0
  @nrwl/eslint-plugin-nx : 10.4.0
  @nrwl/express : Not Found
  @nrwl/jest : 10.4.0
  @nrwl/linter : 10.4.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 10.4.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.1
  @nrwl/web : 10.4.0
  @nrwl/workspace : 10.4.0
  typescript : 4.1.2
```

**Comment by juristr** [comment]
@pitops where exactly do you see that?

**Comment by pitops** [comment]
@juristr just console logging `process.env` gives me NODE_ENV production in storybook stories

**Comment by parksj10** [comment]
I can confirm this is the case for me as well... 

```
Node : 15.6.0
  OS   : darwin x64
  npm  : 6.14.11
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.3.0
  @nrwl/cypress : 11.3.0
  @nrwl/devkit : 11.3.0
  @nrwl/eslint-plugin-nx : 11.3.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.3.0
  @nrwl/linter : 11.3.0
  @nrwl/nest : 11.3.0
  @nrwl/next : Not Found
  @nrwl/node : 11.3.0
  @nrwl/react : 11.3.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.3.0
  @nrwl/web : 11.3.0
  @nrwl/workspace : 11.3.0
  typescript : 4.1.5
```

I tried overriding in the `webpack.config.js` with the following:

```
config.mode = 'development';
config.devtool = 'source-map';
config.optimization.minimize = false;
config.optimization.minimizer = [];
```

and none of it works... Seems like the base config doesn't even use the `mode`

```
/**
 * Export a function. Accept the base config as the only param.
 * @param {Object} options
 * @param {Required<import('webpack').Configuration>} options.config
 * @param {'DEVELOPMENT' | 'PRODUCTION'} options.mode - change the build configuration. 'PRODUCTION' is used when building the static version of storybook.
 */
module.exports = async ({ config, mode }) => {
  // Make whatever fine-grained changes you need

  // Return the altered config
  return config;
};
```

Also, not sure if it's the issue, but storybook only accepts `development` or `production`, not the `DEVELOPMENT` or `PRODUCTION` noted in the parameters

Any ideas on how to bypass/force development mode?  I'm currently getting minified react errors that are impossible to debug:

```
Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=null&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

**Comment by pitops** [comment]
@parksj10 as a workaround I did the following in `webpack.config.js`

```
config.plugins.forEach((plugin) => {
    if (plugin.constructor.name === 'DefinePlugin') {
      plugin.definitions['process.env'] = {
        NODE_ENV: JSON.stringify('development'),
        NODE_PATH: JSON.stringify(''),
        PUBLIC_URL: JSON.stringify('.'),
      }
    }
  })
```

**Comment by pitops** [comment]
@parksj10 what do you refer to as `source` ?

**Comment by pitops** [comment]
ah, probably you mean sources maps yes.

That's up to you, if you wish to debug in production then yes you need source maps. 

The error is telling you that probably when you exported a component you imported it using this syntax `import Component from './XYZ'` instead of `import {Component} from './XYZ'`

**Comment by pitops** [comment]
Well the good news is, it is development mode because the production error you got translates to that in development mode. 

However, source mapping is not working properly and probably has to do with your webpack config. However, this github issue is not for that, so I suggest you open another issue if you believe it is related to NX.

**Comment by pitops** [comment]
This is issue shouldn't be closed. Please remove these bots. They do more harm than good.

**Comment by puku0x** [comment]
Same here. In this case, I use Emotion and Storybook reads the wrong runtime.

```js
{
  "presets": [["@nrwl/react/babel", { "importSource": "@emotion/react" }]],
  "plugins": ["@emotion/babel-plugin"]
}
```
```js
if (process.env.NODE_ENV === "production") {
  module.exports = require("./emotion-react.cjs.prod.js");
} else {
  module.exports = require("./emotion-react.cjs.dev.js");
}
```
![image](https://user-images.githubusercontent.com/2607019/114258577-603aa400-9a02-11eb-8491-93da95c28d3d.png)
