### ISSUE TITLE
create-nx-workspace fails on windows with invalid mkdir argument

### ISSUE THREAD

**Issue by ReeceXW** [nrwl/nx#4945]
## Current Behavior
Fails to create monorepo on Windows 10 due to an invalid mkdir argument

## Expected Behavior
Should succeed

## Steps to Reproduce
`npx create-nx-workspace`
Just enter any information, even empty

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

> C:\Users\Reece\Documents\Projects>npx create-nx-workspace

> ? Workspace name (e.g., org name)     test1
> ? What to create in the new workspace empty             [an empty workspace with a layout that works best for building apps]
> ? Use Nx Cloud? (It's free and doesn't require registration.) No
> Creating a sandbox with Nx...
> new test1 --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace
> CREATE test1/nx.json
> CREATE test1/package.json
> CREATE test1/README.md
> CREATE test1/tools/generators/.gitkeep
> CREATE test1/tools/tsconfig.tools.json
> CREATE test1/tsconfig.base.json
> CREATE test1/.editorconfig
> CREATE test1/.gitignore
> CREATE test1/.prettierignore
> CREATE test1/.vscode/extensions.json
> CREATE test1/workspace.json
> CREATE test1/.prettierrc
> CREATE test1/apps/.gitkeep
> CREATE test1/libs/.gitkeep
> EINVAL: invalid argument, mkdir 'C:\C:\Users\Reece\Documents\Projects\test1'
> npm ERR! code 1
> npm ERR! path C:\Users\Reece\AppData\Local\Temp\tmp-15060AYx2mzyQmjKt
> npm ERR! command failed
> npm ERR! command C:\Windows\system32\cmd.exe /d /s /c tao new test1 --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=nx --nxWorkspaceRoot=\C:/Users/Reece/Documents/Projects\
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Reece\AppData\Local\npm-cache\_logs\2021-03-04T18_48_16_769Z-debug.log
> node:child_process:681
>     err = new Error(msg);
>           ^
> 
> Error: Command failed: npx tao new test1 --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=nx --nxWorkspaceRoot=\"C:/Users/Reece/Documents/Projects\"
>     at checkExecSyncError (node:child_process:681:11)
>     at Object.execSync (node:child_process:718:15)
>     at createApp (C:\Users\Reece\AppData\Local\npm-cache\_npx\d2207cf76adb22dc\node_modules\create-nx-workspace\bin\create-nx-workspace.js:385:21)
>     at C:\Users\Reece\AppData\Local\npm-cache\_npx\d2207cf76adb22dc\node_modules\create-nx-workspace\bin\create-nx-workspace.js:98:29
>     at processTicksAndRejections (node:internal/process/task_queues:94:5) {
>   status: 1,
>   signal: null,
>   output: [ null, null, null ],
>   pid: 4676,
>   stdout: null,
>   stderr: null
> }

### Environment
Windows 10 Pro, 19042
Node 15.8.0
NPM 7.5.3

**Comment by bekos** [comment]
@ReeceXW this is an issue with npm@7 in Windows, and it is already fixed via d2bac514ac988e13e71e2c552aa4c6aef1105d92. It will be part of next release.
