### ISSUE TITLE
Cannot read property 'registerOptionsTransform' of undefined

### ISSUE THREAD

**Issue by fstodulski** [nrwl/nx#4947]
## Current Behavior
After running any `ng generate <component|service|module>` I am getting :
<pre><code>Cannot read property 'registerOptionsTransform' of undefined</code></pre>

## Expected Behavior
It should create component, module, component.

## Steps to Reproduce
It happened suddenly. 
I did branch checkout, had to run `npm i`, and after that - it doesn't work.

<pre><code>ng serve</code></pre>

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

<pre><code>➜ ng g m features/main/views/settings/views/all-settings/components/settings-card --project=estimation
Cannot read property 'registerOptionsTransform' of undefined</code></pre>

### Environment

<pre><code>
 Node : 14.15.1
  OS   : darwin x64
  npm  : 6.14.8
  
  nx : Not Found
  @nrwl/angular : 11.4.0
  @nrwl/cli : 11.4.0
  @nrwl/cypress : 11.4.0
  @nrwl/devkit : 11.4.0
  @nrwl/eslint-plugin-nx : 11.4.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.4.0
  @nrwl/linter : 11.4.0
  @nrwl/nest : 11.4.0
  @nrwl/next : Not Found
  @nrwl/node : 11.4.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.4.0
  @nrwl/web : Not Found
  @nrwl/workspace : 11.4.0
  typescript : 4.1.5
</code></pre>

**Comment by fstodulski** [comment]
Removing
```
    "defaultCollection": "@nrwl/angular",
```
from angular.json fixed the issue.

**Comment by fstodulski** [comment]
Removing .node_modules/@angular/cli folder do the job. 
Using Global Angular instead

**Comment by fstodulski** [comment]
I think there is an issue when project's Angular/cli has a different version than global one. 
Looks like I fixed it. 
I suggest to leave this issue for other people with the same problem :)

**Comment by fstodulski** [comment]
After running `npm install` (installing all, also @angular/cli), error comes back. I had to run manually rm -rf node_modules/@angular/cli to make it work again...

**Comment by agroupp** [comment]
I have the same issue :(

**Comment by fstodulski** [comment]
@agroupp check versions of Angular Cli
Check in your project direction with `ng version` if it matches the global one.

**Comment by agroupp** [comment]
@fstodulski I did, 100% match. the only way to make it work is to use `ng` command instead of `nx`, but it's not something we want in Nx

**Comment by agroupp** [comment]
Ok, I found the issue. Problem is that during migrations Nx doesn't update `@angular-devkit/schematics` and at some point the old version breaks the workspace work.

So, what you need to do is to update it manually. Delete `package-lock.json` and issue:

` npm i -D @angular-devkit/schematics@latest`

This will fix the issue. @FrozenPandaz, any comments from Nx side?

**Comment by petterhoel** [comment]
This issue hit me when bumping nx from 11.1.1 to 11.5.2. thanks @agroupp this fixed me :)

**Comment by leosvelperez** [comment]
Thanks everyone for reporting this!

Unfortunately, I haven't been able to reproduce it. I'd need more details to help here. Can someone provide a repo where the issue can be reproduced?

It seems to be associated to migrations according to some of the comments above, I tried to reproduce it by creating a nx workspace with version 11.1.1 and migrated it to 11.5.2 as @petterhoel mentioned and I didn't get the issue.
