### ISSUE TITLE
cannot build node library in production mode 

### ISSUE THREAD

**Issue by vandriesh** [nrwl/nx#4949]
## Current Behavior
I see no effect of prod mode build of node library

## Expected Behavior
I expect to see optimized version of my library (minimized,hashed file name?)

## Steps to Reproduce
```bash
nx run build:my-lib --mode prod
```
## THE Story

All the topics I've encountered are stale/close because of not action (mainly from nx team)

e.g. https://github.com/nrwl/nx/issues/4141
few issues followed same scenario
```
user: we have a problem
nx1: hmm, why would it happen
nx2: not sure
... // after 2 weeks
bot: let's close this issue - 
```

I couldn't find a clear recommendation/documentation how to

generate a ts library and have a something like this

```json.js
{
      ...,
      "configurations": {
          "production": {
              "optimization": true,
              // and/or add custom webpack - which might do what we need to do
              "webpackConfig": "libs/xxx/webpack.config.js"

          }
      }
      ...,
}
```

Guys, you are doing a fantastic job. Whenever project I go I bring onboard nx workspace concept - but it's so hard... to convince whole team because of such small and unpleasant issues. Can we do something about that?

p.s. 

### Environment
 Node : 14.15.1
  OS   : darwin x64
  npm  : 6.14.8
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.0.20
  @nrwl/cypress : Not Found
  @nrwl/devkit : 11.0.20
  @nrwl/eslint-plugin-nx : 11.0.20
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.20
  @nrwl/linter : 11.0.20
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.0.20
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.20
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.20
  typescript : 4.0.5

**Comment by bekos** [comment]
@vandriesh since this is a node app, we don't think it's pretty useful to minimize the output. Nevertheless, if you want to customize it, then using a custom webpack configuration (as you had in your options) and doing something like:
```
module.exports = (config) => {
  config.optimization.minimize = true;
  config.output.filename =  '[hash].js';
  return config;
};
``` 
Will this work for you?

**Comment by vandriesh** [comment]
the biggest problem right now (imho) is that I deliberately pass wrong webpack - and nothing happens - not even an error ,  

e.g.

```json
{
    "version": 2,
    "projects": {
        "xxx": {
            "root": "libs/xxx",
            "sourceRoot": "libs/xxx/src",
            "projectType": "library",
            "targets": {
                "lint": {
                    "executor": "@nrwl/linter:eslint",
                    "options": {
                        "lintFilePatterns": ["libs/xxx/**/*.ts"]
                    }
                },
                "test": {
                    "executor": "@nrwl/jest:jest",
                    "outputs": ["coverage/libs/xxx"],
                    "options": {
                        "jestConfig": "libs/xxx/jest.config.js",
                        "passWithNoTests": true
                    }
                },
                "build": {
                    "executor": "@nrwl/node:package",
                    "outputs": ["{options.outputPath}"],
                    "options": {
                        "outputPath": "dist/libs/xxx",
                        "tsConfig": "libs/xxx/tsconfig.lib.json",
                        "packageJson": "libs/xxx/package.json",
                        "main": "libs/xxx/src/index.ts",
                        "assets": []
                    },
                    "configurations": {
                        "production": {
                            "optimization": true,
                            "webpackConfig": "libs/xxx/webpack.config.js"
                        }
                    }
                }
            }
        }
    },
    "cli": {
        "defaultCollection": "@nrwl/workspace"
    }
}

```

before I've used configuration next to build - same - no error of wrong entry/placement of configurations

**Comment by vandriesh** [comment]
while adding webpack into another (react nx combo) throws an error:

```bash
> nx run test:build:production 
Cannot find module '/Users/vandries/.../ts-workspace/webpack.config.js'
Require stack:
- /Users/vandries/.../ts-workspace/node_modules/@nrwl/web/src/builders/build/build.impl.js
- /Users/vandries/.../ts-workspace/node_modules/@nrwl/tao/src/shared/workspace.js
- /Users/vandries/.../ts-workspace/node_modules/@nrwl/tao/src/commands/run.js
- /Users/vandries/.../ts-workspace/node_modules/@nrwl/tao/index.js
- /Users/vandries/.../ts-workspace/node_modules/@nrwl/cli/lib/run-cli.js

-
```

**Comment by bekos** [comment]
@vandriesh weird, because I get an error 🤔 
![image](https://user-images.githubusercontent.com/551595/111184203-6717f780-85b9-11eb-9108-2f4a01769ef6.png)

Can you provide a reproduction repo plz?

**Comment by vandriesh** [comment]
sure:

https://github.com/vandriesh/nx-node-lib-prod-build

**Comment by bekos** [comment]
@vandriesh oh, I see. For some reason I missed that you were talking about `@nrwl/node:package` and thought `@nrwl/node:build` 😞 The reason that you don't see an error is that this executor doesn't support custom webpack configuration, because under the hood this is using the Typescript compiler, not webpack. See available options here: https://nx.dev/latest/node/node/package

To be honest, I don't know what your actual use case is, but usually we don't care about minification/hashing/etc when distributing Node libraries (fyi this is the same way we use for distributing Nx).

**Comment by vandriesh** [comment]
my use case is quite simple - I want to build a library (like lib1,...libN - which can be used separately.
all I need is minified/hashed output - so my small changes won't be cached  
(it's java+play env which serves web app - that uses require (amd)

no I have some additional tools (workaround (gulp) to do the transformations) but I don't like this "sophisticated" step.

all I wanted is nx run:my-ts-lib:production -> lib1.d2d321.js..lib2.d2d321.js

do I want too much? maybe I use wrong builder? will react lib do this for me?

thanks!

**Comment by bekos** [comment]
@vandriesh If these libraries are going to be used in a browser, and that's why you need minification & hashing, then `@nrwl/node:package` is not the most appropriate. I think `@nrwl/web:package` is better for your case 🤔  Can you confirm that this would work?

This is Rollup under the hood, and in the meantime, I can prepare a PR to support minification/hashing for that builder 😄

**Comment by vandriesh** [comment]
will give it a try - Thanks a lot!

**Comment by bekos** [comment]
@vandriesh what happened? 😃

**Comment by vandriesh** [comment]
hooold :) (c) breave❤️

**Comment by vandriesh** [comment]
> @vandriesh what happened? 😃

yeah, the I like the output. Scares me one thing that web sounds like an app with some html output - but some chores/brooming and app will become a library - would've been nice a simple ts library ts on input ts.hash.js on output...
