### ISSUE TITLE
jest.config.js not updated when moving a library

### ISSUE THREAD

**Issue by hanselabreu** [nrwl/nx#4956]
## Current Behavior

Moving a library using the `move` generator does not update that `jest.config.js` file.

## Expected Behavior

Using the `move` command should replace the old referencer with the new one.

## Steps to Reproduce

1. Create a new library called `feature-library`.
2. Move this library using the `move` generator `nx g mv --project feature-library /shared/feature-library` 
3. Watch as how `jest.config.js` does not replace `<rootDir>/libs/feature-library` with `<rootDir>/libs/shared/feature-library`

### Environment

```
Node : 14.15.4
OS   : darwin x64
yarn : 1.22.10

nx : Not Found
@nrwl/angular : Not Found
@nrwl/cli : 11.4.0
@nrwl/cypress : 11.4.0
@nrwl/devkit : 11.4.0
@nrwl/eslint-plugin-nx : 11.4.0
@nrwl/express : Not Found
@nrwl/jest : 11.4.0
@nrwl/linter : 11.4.0
@nrwl/nest : 11.4.0
@nrwl/next : Not Found
@nrwl/node : 11.4.0
@nrwl/react : 11.4.0
@nrwl/schematics : Not Found
@nrwl/tao : 11.4.0
@nrwl/web : 11.4.0
@nrwl/workspace : 11.4.0
typescript : 4.0.7
```

**Comment by kang-heewon** [comment]
I'm having a similar but slightly different problem. 
If displayName in jest.config.js is different from projectName , it is not updated.

Was this intended?

**Comment by leosvelperez** [comment]
> If displayName in jest.config.js is different from projectName , it is not updated.
> 
> Was this intended?

It is intended, if the developer decided to customize the name and not use the one matching the project name, we don't update it. We can't know if the intention is to have a different name regardless of the project location or not.

**Comment by leosvelperez** [comment]
I'm going to close this issue since it has already been resolved. Please retry with the latest versions and if you still face it, feel free to reopen the issue or report a new one.
