### ISSUE TITLE
Storybook decorators not getting applied

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#4961]
## Current Behavior

When providing a global decorator in /.storybook/preview.js or /libs/<app>/.storybook/preview.js the decorator does not get applied.

## Expected Behavior

The decorator should be applied as per storybook decorator specification.

## Steps to Reproduce

```
export const decorators = [
  (Story) => {
    return (
      <div style={{ backgroundColor: 'red' }}>
        <Story />
      </div>
    );
  },
];
```

### Environment

  Node : 14.15.4
  OS   : win32 x64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : 8.12.11
  @nrwl/cli : 11.4.0
  @nrwl/cypress : 11.4.0
  @nrwl/devkit : 11.4.0
  @nrwl/eslint-plugin-nx : 11.4.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.4.0
  @nrwl/linter : 11.4.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.4.0
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 11.4.0
  @nrwl/web : 11.4.0
  @nrwl/workspace : 11.4.0
  typescript : 4.2.3

**Comment by kpaxton** [comment]
This is still an issue and should not be closed. @vsavkin. I'm finding a lot of these regarding Storybook are closed due to the bot marking things as stale even though they are still issues.
