### ISSUE TITLE
[BUG]: @nrwl/jest:jest doesn't quit when test failed

### ISSUE THREAD

**Issue by splincode** [nrwl/nx#4963]
## Current Behavior

```json5
"test": {
    "builder": "@nrwl/jest:jest",
    "options": {
        "jestConfig": "jest.config.js",
        "coverageDirectory": "coverage/libs/core/iris",
        "testPathPattern": ["libs/core/iris/tests"],
        "passWithNoTests": true
     }
}
```

in terminal

`$ ng test core-iris` and `echo $?`

![image](https://user-images.githubusercontent.com/12021443/110236208-97222380-7f45-11eb-9ea9-31906873b8be.png)

But if running native jest

`$ jest --testPathPattern "libs/core/iris/tests"` and `echo $?`

![image](https://user-images.githubusercontent.com/12021443/110236160-54604b80-7f45-11eb-9e50-24a97a6d160a.png)

We have exit code 1

## Expected Behaviour

The `@nrwl/jest:jest` builder must forward the exit code to the upper level for exit program, when running `ng test`

### Environment

Angular: last
Jest: 26
nrwl: last

**Comment by splincode** [comment]
@vsavkin my workaround, but not production ready, what do you think about `{ success: false }` (which should be correct program exit)?

![image](https://user-images.githubusercontent.com/12021443/110236767-bff7e800-7f48-11eb-9bc3-a1bc97ad1100.png)

**Comment by vsavkin** [comment]
Thank you for submitting the issue. 

Unfortunately I'm not able to repro it. The status code is propagated correctly.

Could you provide a repo with a repro and I'll take a look asap?

**Comment by splincode** [comment]
@vsavkin oh, sorry, i will try

**Comment by splincode** [comment]
I can't reproduce another repo (((
