### ISSUE TITLE
Pass plain command arguments to the plugin executor and/or workspace:run-commands

### ISSUE THREAD

**Issue by dobromyslov** [nrwl/nx#4964]
## Description
I develop a plugin for nestjs-console to be able to run console commands with plain arguments (without --) forwarded from `nx run @dobromyslov/nestjs-console:run console-command-name param1 param2 param3`.

But it's impossible because plugin executor is actually executed by [`workspace/src/command-line/run-one.ts`](https://github.com/nrwl/nx/blob/f160583d5c3f59b4dea592e793f4853a1857f894/packages/workspace/src/command-line/run-one.ts#L9) and it throws away all plain command line arguments (without --). See [`splitArgsIntoNxArgsAndOverrides()`](https://github.com/nrwl/nx/blob/f160583d5c3f59b4dea592e793f4853a1857f894/packages/workspace/src/command-line/utils.ts#L76) how it just does `delete overrides._;`;

## Motivation
I don't want to use a workaround with additional script added to the main `package.json` and then run the nestjs command with plain `yarn`/`npm` instead of `nx`/`ng`. At the moment `package.json` additional script looks like this one: 
```json
"my-project:cli": "env-cmd -f .env.cli ts-node -r tsconfig-paths/register --project apps/my-project/tsconfig.cli.json apps/my-project/src/cli.ts"
```
And is executed with `yarn run my-project:cli console-command-name param1 param2 param3`

## Suggested Implementation
1. `splitArgsIntoNxArgsAndOverrides()` should not strip plain arguments but it should return them to the `runOne()`
2.  Plain arguments should be passed to the plugin executor (workspace:run-commands or my own).

Then it will be possible to add to `angular.json` additional target:
```json
{
  ...
  "projects": {
    ...
    "my-project": {
      ...
      "architect": {
        ...
        "cli": {
          "builder": "@dobromyslov/nestjs-console:run"
        }
      }
    }
  }
```
and run it with  `ng run my-project:cli console-command-name param1 param2 param3`.

**Comment by Esya** [comment]
Having the same issue
