### ISSUE TITLE
Inject the project name into nx run-many

### ISSUE THREAD

**Issue by d3473r** [nrwl/nx#4974]
## Description

Right now I am using default eslint to generate a json report for sonarqube.
`eslint -f json -o reports/eslint-report.json apps/app1 apps/app2 libs/news libs/shared/lib1 ...`
This gives me a combined eslint report in `reports/eslint-report.json`, which i can tell sonarqube to look at (`sonar.eslint.reportPaths=reports/eslint-report.json`).

I would love to generate a combined report or a report per app/lib with nx to make use of the computation caching which I already use for test and build.

When I use `nx run-many --target=lint --all --format json --outputFile reports/eslint-report.json` the report is overwritten by each project and not combined.

## Motivation

One workaround right now ist to define every project lint seperately as npm script:
```
"lint": "npm run lint-app1 && npm run lint-app2 &&"npm run lint-lib1
"lint-app1": "nx lint app1 --format json --outputFile reports/app1/eslint-report.json",
"lint-app2": "nx lint app2 --format json --outputFile reports/app2/eslint-report.json",
"lint-lib1": "nx lint lib1 --format json --outputFile reports/lib1/eslint-report.json",
```
But this gets hard to track and maintain with many apps/libs.

## Suggested Implementation

Allow the injection of the `project` into run-many like so: `nx run-many --target=lint --all --format json --outputFile reports/${project}/eslint-report.json`

## Alternate Implementations

Support a new parameter on run-many like `combinedOutputFile` to combine the reports (I don't know if this is possible).

**Comment by vsavkin** [comment]
I believe you can already do it like this:

```
nx run-many --target=lint --all --format json --outputFile reports/{project.name}/eslint-report.json
```

**Comment by d3473r** [comment]
> I believe you can already do it like this:
> 
> ```
> nx run-many --target=lint --all --format json --outputFile reports/{project.name}/eslint-report.json
> ```

Awesome, thank you! Just tested it 🎉 . I couldn't find it in the docs.
