### ISSUE TITLE
workspace-schematic results in typescript error

### ISSUE THREAD

**Issue by CaioRolla** [nrwl/nx#4975]
## Current Behavior
I updated my repository to v11.4 and my schematics stopped working. When i run the following command:

`nx workspace-schematic create-feature --name feature-name --directory directory-name --routing=true`

This is what i got:

`error TS5042: Option 'project' cannot be mixed with source files on a command line.`

That's it. Only one line. 

I created empty schematics (and deleted that one) but the error still the same.

## Steps to Reproduce

You just need to follow the documentation:

https://nx.dev/latest/angular/generators/workspace-generators#running-a-workspace-generator

`nx generate @nrwl/workspace:workspace-generator my-generator`

`nx workspace-generator my-generator mylib`

Those are some relevant files:

tsconfig.tools.json
`{
  "extends": "../tsconfig.base.json",
  "compilerOptions": {
    "outDir": "../dist/out-tsc/tools",
    "rootDir": ".",
    "module": "commonjs",
    "target": "es5",
    "types": ["node"]
  },
  "include": ["**/*.ts"],
  "exclude": ["**/files"]
}`

collection.json
`{
  "$schema": "../../node_modules/@angular-devkit/schematics/collection-schema.json",
  "name": "create-feature-collection",
  "version": "0.0.1",
  "extends": ["@nrwl/schematics"],
  "schematics": {
    "create-feature": {
      "factory": "../../dist/out-tsc/tools/generators/create-feature",
      "schema": "./create-feature/schema.json",
      "description": "Create feature libs with it's own data access lib"
    }
  }
}`

Dependencies
`  "dependencies": {
    "@agm/core": "1.0.0-beta.5",
    "@angular/animations": "11.2.0",
    "@angular/cdk": "11.2.1",
    "@angular/common": "11.2.0",
    "@angular/compiler": "11.2.0",
    "@angular/core": "11.2.0",
    "@angular/fire": "6.0.0",
    "@angular/flex-layout": "11.0.0-beta.33",
    "@angular/forms": "11.2.0",
    "@angular/localize": "11.2.3",
    "@angular/material": "11.2.1",
    "@angular/material-moment-adapter": "11.2.1",
    "@angular/platform-browser": "11.2.0",
    "@angular/platform-browser-dynamic": "11.2.0",
    "@angular/router": "11.2.0",
    "@fortawesome/angular-fontawesome": "0.5.0",
    "@fortawesome/fontawesome-svg-core": "1.2.22",
    "@fortawesome/pro-regular-svg-icons": "5.10.2",
    "@fortawesome/pro-solid-svg-icons": "5.10.2",
    "@larscom/ngrx-store-storagesync": "6.1.7",
    "@ngmodule/material-carousel": "0.5.0",
    "@ngrx/component-store": "11.0.1",
    "@ngrx/effects": "11.0.1",
    "@ngrx/entity": "11.0.1",
    "@ngrx/router-store": "11.0.1",
    "@ngrx/schematics": "11.0.1",
    "@ngrx/store": "11.0.1",
    "@ngrx/store-devtools": "11.0.1",
    "@ngx-translate/core": "11.0.1",
    "@nrwl/angular": "11.4.0",
    "@nrwl/schematics": "8.12.11",
    "@swimlane/ngx-charts": "11.1.0",
    "@swimlane/ngx-datatable": "15.0.0",
    "@swimlane/ngx-dnd": "7.0.0",
    "@types/hammerjs": "2.0.36",
    "@types/prismjs": "1.16.0",
    "angular-animations": "0.0.9",
    "angular-calendar": "0.27.8",
    "angular-oauth2-oidc": "5.0.2",
    "angular2-carousel": "1.0.17",
    "chart.js": "2.8.0",
    "classlist.js": "1.1.20150312",
    "convert-keys": "1.3.4",
    "core-js": "^2.5.4",
    "d3": "5.16.0",
    "date-fns": "1.30.1",
    "dom-to-image": "2.6.0",
    "emoji-strip": "1.0.1",
    "fast-levenshtein": "3.0.0",
    "firebase": "7.15.0",
    "hammerjs": "2.0.8",
    "jwt-decode": "2.2.0",
    "lodash": "4.17.11",
    "moment": "2.24.0",
    "ng-in-viewport": "6.0.3",
    "ng2-charts": "2.2.4",
    "ngrx-store-freeze": "0.2.4",
    "ngx-clipboard": "12.1.2",
    "ngx-cookie-service": "2.2.0",
    "ngx-custom-validators": "8.0.0",
    "ngx-dy-i18n": "0.0.3",
    "ngx-ellipsis": "2.1.2",
    "ngx-qrcode2": "0.0.9",
    "perfect-scrollbar": "1.4.0",
    "prismjs": "1.16.0",
    "randomcolor": "0.6.2",
    "resize-observer-polyfill": "1.5.1",
    "rxjs": "6.5.5",
    "saturn-datepicker": "7.4.0",
    "squarify": "1.1.0",
    "swipejs": "2.2.14",
    "uuid": "7.0.3",
    "web-animations-js": "github:angular/web-animations-js#release_pr208",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "0.1001.7",
    "@angular-devkit/build-angular": "0.1102.1",
    "@angular/cli": "11.2.3",
    "@angular/compiler-cli": "11.2.0",
    "@angular/language-service": "11.2.0",
    "@angularclass/hmr": "2.1.3",
    "@nrwl/cli": "11.4.0",
    "@nrwl/cypress": "11.4.0",
    "@nrwl/devkit": "11.4.0",
    "@nrwl/jest": "11.4.0",
    "@nrwl/tao": "11.4.0",
    "@nrwl/workspace": "11.4.0",
    "@schematics/angular": "11.2.3",
    "@types/d3": "5.7.2",
    "@types/dom-mediacapture-record": "1.0.7",
    "@types/jest": "26.0.8",
    "@types/lodash": "4.14.132",
    "@types/node": "12.12.38",
    "codelyzer": "6.0.0",
    "cypress": "^3.8.2",
    "firebase-tools": "^6.10.0",
    "fuzzy": "^0.1.3",
    "inquirer": "^6.2.2",
    "inquirer-autocomplete-prompt": "^1.0.1",
    "jest": "26.2.2",
    "jest-preset-angular": "8.3.2",
    "prettier": "2.2.1",
    "protractor": "7.0.0",
    "ts-jest": "26.4.0",
    "ts-node": "9.1.1",
    "tslib": "1.9.3",
    "tslint": "6.1.3",
    "typescript": "4.0.7",
    "webpack-bundle-analyzer": "3.3.2"
  }`

**Comment by ctotzek-md** [comment]
Maybe the problem has to do with `@nrwl/schematics` still being version `8.12.11` while everything else is version 11.x. It causes conflicts with other nrwl-packages, so your node_modules contains different versions, depending on which version you had installed before.

**Comment by juristr** [comment]
@ctotzek-md yeah try to have all of the `@nrwl/*` packages on the same version otherwise you might run into conflicts :)

I'm going to close this, but feel free to re-open if the problem persists

**Comment by ctotzek-md** [comment]
@juristr `@nrwl/schematics` has no version of 11.0 but is not marked as deprecated.
This issue wasn't opened by me.

**Comment by CaioRolla** [comment]
The lastest `@nrwl/schematics` is 8.12.11, the exact one i'm using.

@vsavkin maybe this can help:

`  
  Node : 14.15.1
  OS   : win32 x64
  npm  : 6.14.8

  nx : Not Found
  @nrwl/angular : 11.4.0
  @nrwl/cli : 11.4.0
  @nrwl/cypress : 11.4.0
  @nrwl/devkit : 11.4.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.4.0
  @nrwl/linter : 11.4.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 11.4.0
  @nrwl/web : Not Found
  @nrwl/workspace : 11.4.0
  typescript : 4.0.7
`

**Comment by vsavkin** [comment]
The schematics package has not been deprecated because some folks still use it. But you should only use it if you use Nx 8. In you case you are on Nx 11, so everything from the schematics package was moved to other packages (e.g., @nrwl/workspace, @nrwl/angular) etc.. So you should remove your dependency on @nrwl/schematics. I'm not sure if this is what is causing the issue for you though.

Could you open `node_modules/@nrwl/workspace/src/command-line/workspace-generators.js`, comment out the deletion of the tmp tsconfig in createTmpTsConfig, so you can see why the tsconfig is incorrect.

**Comment by CaioRolla** [comment]
@vsavkin This is the content of the `tsconfig.generated.json`:

```
{
  "extends": "../tsconfig.base.json",
  "compilerOptions": {
    "outDir": "../dist/out-tsc/tools",
    "rootDir": ".",
    "module": "commonjs",
    "target": "es5",
    "types": [
      "node"
    ]
  },
  "include": [
    "C:\\Repos\\MyRepo\\tools\\generators\\**\\*.ts"
  ],
  "exclude": [
    "**/files"
  ]
}
```
What is the difference between a deprecated feature and a feature that doesn't work at all in newer versions?

I removed @nrwl/schematics from my dependencies, deleted node_modules and executed npm install again. Nothing changed.

**Comment by vsavkin** [comment]
The tsconfig looks correct. Could you add quotes around tmpTsConfigPath in compileToolsDir(same file):

`child_process_1.execSync(`${tsc} -p "${tmpTsConfigPath}"``

And print the command as well?
