### ISSUE TITLE
Unable to pass through args with "with-deps" flag

### ISSUE THREAD

**Issue by jase88** [nrwl/nx#4976]
## Current Behavior
I have a dependency between two apps (_my-app_ and _my-app-wrapper_) and I'm not able to pass through the configuration as parameter as well as considering building dependencies as well.

nx.json
```
{
  "npmScope": "my-workspace",
  ....
  "projects": {
    "my-app": { "tags": [] },
    "my-app-wrapper": { "tags": [], "implicitDependencies": ["my-app"] }
  }
}
```

angular.json
```
{
  "version": 1,
  "projects": {
    "my-app": {
      ...
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          ...
          "configurations": {
            "production": {},
            "buildVariantA": {},
            "buildVariantB": {}
          }
        }
      }
    },
    "my-app-wrapper": {
      ...
      "architect": {
        "build": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "commands": ["echo \"received: {args.configuration}\""]
          },
          "configurations": {
            "production": {},
            "buildVariantA": {},
            "buildVariantB": {}
          }
        }
      }
    }
```

a) 
I I call `nx build my-app-wrapper --prod --configuration=buildVariantA`
The result is
```
> nx run my-app-wrapper:build:buildVariantA 
"received: undefined"
```

b)
I I call `nx build my-app-wrapper --prod --args="--configuration=buildVariantA"`
The result is
```
> nx run my-app-wrapper:build:production --args=--configuration=buildVariantA 
"received: buildVariantA"
```
which is fine, but if I call

c)

`nx build my-app-wrapper --prod --args="--configuration=buildVariantA" --with-deps`

```
>  NX  Running target build for project my-app-wrapper and its 2 deps.

———————————————————————————————————————————————

> nx run buildable-lib:build:production --args=--configuration=buildVariantA 
'args' is not found in schema

———————————————————————————————————————————————

>  NX   ERROR  Running target "build" failed
```

d)
`nx build my-app-wrapper --prod --configuration=buildVariantA --with-deps` does work for building dependencies, but print the same undefined value as in a)

## Expected Behavior
I expect to call `nx build my-app-wrapper --prod --configuration=buildVariantA --with-deps` to work for interpolation args as well as building dependencies.

## Steps to Reproduce

https://github.com/kerosin/nx-passing-through-args

run one of the above mentioned commands

### Environment
```
  Node : 14.15.3
  OS   : win32 x64
  npm  : 7.6.1

  nx : Not Found
  @nrwl/angular : 11.4.0
  @nrwl/cli : 11.4.0
  @nrwl/cypress : 11.4.0
  @nrwl/devkit : 11.4.0
  @nrwl/eslint-plugin-nx : 11.4.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.4.0
  @nrwl/linter : 11.4.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.4.0
  @nrwl/web : Not Found
  @nrwl/workspace : 11.4.0
  typescript : 4.0.7
```

**Comment by kerosin** [comment]
Hi @vsavkin,
I would like to open a PR for this, but I'm a bit uncertain about a good implementation.

I have two naive ideas:
a) more generic:
if a given parameter (in this case 'args') is part of at least one underlying project, it should be applied only there and thrown out for others (not resulting in an error there)

b) or creating special cases
- if a configuration is set it should always be added to the args argument (unless explicitly set) OR
- args should be left out if they are not part of a schema

**Comment by JakeGinnivan** [comment]
I've hit this issue, my use case is:

```
pnpx nx run-many --target up --all --env prod --yes --verbose
```

Summary is:
```
>  NX  Running target up for 6 project(s):
  - live-subscriptions-infrastructure
  - client-http-api-infrastructure
  - client-ws-api-infrastructure
  - console-infrastructure
  - shared-infrastructure
  - api-infrastructure
  With flags:
    --env=prod
    --yes=true
```

But then I get:

```
Project 1: > nx run shared-infrastructure:up --env=prod --yes
Project 2: > nx run client-http-api-infrastructure:up
```

I assume this is because I have this in my nx.json

```
"targetDependencies": {
    "up": [
      {
        "target": "up",
        "projects": "dependencies"
      }
    ],
    "build": [
      {
        "target": "build",
        "projects": "dependencies"
      }
    ]
  },
```

The fix for my case is pretty straightforward, I simply ensure that `overrides` gets passed through to `addTasksForProjectDependencyConfig` in node_modules/@nrwl/workspace/src/tasks-runner/run-command.js. But unsure if that will break other scenarios?
