### ISSUE TITLE
Generating new libraries can create conflicting eslint configuration files

### ISSUE THREAD

**Issue by chooban** [nrwl/nx#4986]
## Current Behavior

Our nx workspace has `.eslintrc.js` in the root directory. However, if we generate a new library then the command creates a template `.eslintrc.json` in the same directory and has the configuration file of the library extend that new file.

## Expected Behavior

It would be handy if the generator could determine the format of eslint configuration file used in the workspace and use what it finds rather than generating conflicting config.

## Steps to Reproduce

1. Create a workspace that uses `.eslintrc.js` at its root
2. Generate a new library
3. Note the creation of `.eslintrc.json` and that the new library extends that configuration file, not the existing one.

### Environment

```sh
yarn run v1.22.10
$ nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.15.0
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.12
  @nrwl/cypress : 11.2.12
  @nrwl/devkit : 11.2.12
  @nrwl/eslint-plugin-nx : 11.2.12
  @nrwl/express : 11.2.12
  @nrwl/jest : 11.2.12
  @nrwl/linter : 11.2.12
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.2.12
  @nrwl/react : 11.2.12
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.12
  @nrwl/web : 11.2.12
  @nrwl/workspace : 11.2.12
  typescript : 4.1.5

Done in 0.92s.
```

**Comment by JamesHenry** [comment]
Hi @chooban, I outline all the reasons behind not supporting this here: https://github.com/nrwl/nx/issues/3609#issuecomment-753459123

Many thanks!

**Comment by chooban** [comment]
The upgrade path makes a lot of sense, I hadn't considered that. Thanks!
