### ISSUE TITLE
Cannot import nested CSS files after 11.2

### ISSUE THREAD

**Issue by chooban** [nrwl/nx#4989]
## Current Behavior

If I have a component that imports a CSS file that imports another CSS file, the styles are not applied. The client gets a 404 for the second import, and the terminal shows a PostCSS warning.

## Expected Behavior

With nx@11.2.0, the imports work as expected so I'd like that to continue rather than having to configure PostCSS.

## Steps to Reproduce

I have two repos to show the difference:

- https://github.com/chooban/nx-testkit-11.2 Run yarn start, you'll see a green background
- https://github.com/chooban/nx-testkit Generated with 11.4, upgraded to 11.5.1, and you'll see there's no backround.

### Failure Logs

When running with later versions, the console has this:

```
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
```

The browser console shows a 404 for `variables.css`.

### Environment

```
yarn run v1.22.10
$ nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.15.0
  OS   : darwin x64
  npm  : 6.14.8
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.4.0
  @nrwl/cypress : 11.4.0
  @nrwl/devkit : 11.4.0
  @nrwl/eslint-plugin-nx : 11.4.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.4.0
  @nrwl/linter : 11.4.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.4.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.4.0
  @nrwl/web : 11.4.0
  @nrwl/workspace : 11.4.0
  typescript : 4.0.7

Done in 0.88s.
```

**Comment by fetters5** [comment]
I've run into the same issue myself

**Comment by JoshHubi** [comment]
I am having the same exact issue. If I import the stylesheet as a module postCSS works fine for the component but if I dont, PostCSS fails to do anything.

**Comment by trumbitta** [comment]
I have no CSS imports (I am using styled-components) but I have an annoying wall of those postcss warnings

**Comment by JoshHubi** [comment]
> 
> 
> I have no CSS imports (I am using styled-components) but I have an annoying wall of those postcss warnings

Are the styled components using CSS modules by any chance?

**Comment by trumbitta** [comment]
> > I have no CSS imports (I am using styled-components) but I have an annoying wall of those postcss warnings
> 
> Are the styled components using CSS modules by any chance?

Oh I'm not sure... @mxstbr?

**Comment by mxstbr** [comment]
[styled-components](https://github.com/styled-components/styled-components) is an entirely separate library from CSS modules :blush:
