### ISSUE TITLE
Nx vs Angular-cli@6

### ISSUE THREAD

**Issue by tommyc38** [nrwl/nx#499]
Now that the cli can scaffold out libraries, apps, and workspaces, why use Nx?  Don't get me wrong, I love this library but I always have issues upgrading @nrwl/schematics & @nrwl/nx which frustrates me.  For example, in Nx v0.8 there was an upgrade command.  I tried it and it never worked despite trying a number of things.  Clarification around Nx benefits over the cli and how to upgrade Nx and libraries would be helpful.  Thanks.

**Comment by FrozenPandaz** [comment]
it is great that the CLI has these new features and we are very excited as well about that functionality.

We try our best to automate the upgrade experience so please create specific issues you find in this repo and we will try to help/fix.

As for Nx Benefits over the CLI, there is a Wiki doc about the benefits :)
https://github.com/nrwl/nx/wiki/Nx-and-Angular-CLI
