### ISSUE TITLE
NPM Err No matching version found for @nrwl/nest@11.4.0

### ISSUE THREAD

**Issue by andy-dev** [nrwl/nx#4999]
Hello, I am getting this error trying to create an angular-nest app.

Windows Machine.
Node V 12.19.1
npm 6.14.8

**Comment by vsavkin** [comment]
Thanks for submitting the issue.

Perhaps some issue with npm or with your local proxy (if you have one). I tried both latest and 11.4.0, they both worked.  You can try adding `--ignore-existing` to the command or specify `npx create-nx-workspace@latest`.

I'm going to close this.

**Comment by andy-dev** [comment]
Thank you, it was an issue with the proxy.
