### ISSUE TITLE
Run test with coverage for lib

### ISSUE THREAD

**Issue by merlosy** [nrwl/nx#500]
I have a feature suggestion.
I'd really like to be able to run tests and get coverage of a single app or lib.
The docs suggests using `fdescribe`, but it doesn't feel right..

Suggestion of command (`my-lib` defined in `.angular-cli.json`/`angular.json`:
```
ng test -a=my-lib --cc
```

For now, this gives me an error:
```
An app without 'main' cannot use the test command.
```

**Comment by jschwarty** [comment]
@merlosy I believe you should be able to do this with the current version (v6). Some of the command options changed with Angular CLI v6, one of those being the `--app` flag. That is now `--project` and in some commands the project is the first argument (without a flag).

For more info on testing in Nx have a look at "Rebuilding and Retesting What is Affected" on the [Nx Workspaces page](https://nrwl.io/nx/guide-nx-workspace).

```
ng test myapp # runs unit tests for myapp
ng test mylib # runs unit tests for mylib
```

Also check out the latest [test documentation](https://github.com/angular/angular-cli/wiki/test) for the Angular CLI v6 stuff (some of the options and aliases changed).
