### ISSUE TITLE
nx affected:build --all --watch  stays hanging on the first project

### ISSUE THREAD

**Issue by jlabaj** [nrwl/nx#5003]
I have an Angular 11.2.0, nrwl 11.4.0

The question is how do I run the build on all the projects and watch them.

If I run this:
nx affected:build --all --watch

its stays hanging on the first project in the list and waits for changes

Maybe related to this issue?
https://github.com/nrwl/nx/issues/1222

**Comment by jlabaj** [comment]
I tried it with --parallel --maxParallel=100 but it only watches the first 3 projects

**Comment by jlabaj** [comment]
this also works only for the first 3 projects: nx run-many --all --target=build --watch --parallel --maxParallel=100

**Comment by jlabaj** [comment]
this is also not tracking the changes nx affected:build --uncommitted --watch

**Comment by jlabaj** [comment]
ok as a workaround I used nodemon:
"ngxm:build": "nodemon --exec \"npm run buildaffected || exit 1\""

its working fine and I have the feeling that its faster after every build iteration

**Comment by jlabaj** [comment]
@vsavkin I can't provide a repo, its a large company(angularjs+angular) project. I have many Project dependencies, it builds the whole chain as far as I know.

**Comment by jlabaj** [comment]
@vsavkin even after setting the options in the nx.json the parallel build doesnt work:

"tasksRunnerOptions": {
    "default": {
      "runner": "@nrwl/workspace/tasks-runners/default",
      "options": {
        "parallel": true,
        "maxParallel": "100",
        "cacheableOperations": ["build", "test", "e2e", "lint"]
      }
    }
  },

![image](https://user-images.githubusercontent.com/5179937/111273829-93bd2500-8634-11eb-8ae6-5d34d863fef7.png)

**Comment by jlabaj** [comment]
could it be the node version? 12.16.2 at the moment?

**Comment by vsavkin** [comment]
The version of node shouldn't matter.  You can open "node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:66" and log the maxParallel value used. Unfortunately I'm not able to repro it. I tried all sorts of ways :)

**Comment by walec51** [comment]
scenario when even setting `"parallel": true, "maxParallel": "100"` will not help

lets say we have a workspace with two *buildable* and *publishable* libraries:

- *channels* library
- and *voucher* library which depends on the *channels* library

the following will hang on the *channels* library

```
$ npx nx affected:build --all --watch --parallel --maxParallel=100

>  NX   WARNING  Running affected:* commands with --all can result in very slow builds.

  --all is not meant to be used for any sizable project or to be used in CI.

  Learn more about checking only what is affected: https://nx.dev/latest/angular/cli/affected#affected.


>  NX  Running target build for 3 project(s):

  - back-office-frontend
  - channels
  - voucher

  With flags:
    --watch=true

———————————————————————————————————————————————

> nx run back-office-frontend:build:production --watch 

> nx run channels:build:production --watch 
Building Angular Package

------------------------------------------------------------------------------
Building entry point '@ewejsciowki/channels'
------------------------------------------------------------------------------
√ Compiling with Angular sources in Ivy partial compilation mode.
√ Writing FESM bundles
√ Copying assets
√ Writing package manifest
√ Built @ewejsciowki/channels

------------------------------------------------------------------------------
Built Angular Package
 - from: D:\Projekty\WALCZAK IT\scr\ewejsciowki\ewejsciowki-back-office-frontend\libs\channels
 - to:   D:\Projekty\WALCZAK IT\scr\ewejsciowki\ewejsciowki-back-office-frontend\dist\libs\channels
------------------------------------------------------------------------------

Build at: 2022-02-07T13:28:20.514Z - Time: 4119ms


Compilation complete. Watching for file changes...
√ Browser application bundle generation complete.
√ Index html generation complete.

Initial Chunk Files           | Names         |  Raw Size | Estimated Transfer Size
main.a06eb66471ff6201.js      | main          |  99.77 kB |                28.98 kB
polyfills.246356e93bbd6d60.js | polyfills     |  36.22 kB |                11.50 kB
runtime.fd27f5e1abc07004.js   | runtime       |   1.07 kB |               608 bytes
styles.ef46db3751d8e999.css   | styles        |   0 bytes |                       -

                              | Initial Total | 137.06 kB |                41.07 kB

Build at: 2022-02-07T13:28:22.246Z - Hash: 3afec7663c593ad3 - Time: 3482ms
√ Browser application bundle generation complete.
√ Index html generation complete.

4 unchanged chunks

Build at: 2022-02-07T13:28:22.799Z - Hash: 3afec7663c593ad3 - Time: 389ms

```

At this point *voucher* have not been build and changing any files there will not force a rebuild either. Changing anything in *channels* will rebuild *channels*.

Same thing happend if I try to build just the *voucher* lib

```
$ npx nx build voucher --watch --parallel --maxParallel=100

>  NX  Running target build for project voucher and 1 task(s) that it depends on.


———————————————————————————————————————————————

> nx run channels:build:production --watch 
Building Angular Package

------------------------------------------------------------------------------
Building entry point '@ewejsciowki/channels'
------------------------------------------------------------------------------
√ Compiling with Angular sources in Ivy partial compilation mode.
√ Writing FESM bundles
√ Copying assets
√ Writing package manifest
√ Built @ewejsciowki/channels

------------------------------------------------------------------------------
Built Angular Package
 - from: D:\Projekty\WALCZAK IT\scr\ewejsciowki\ewejsciowki-back-office-frontend\libs\channels
 - to:   D:\Projekty\WALCZAK IT\scr\ewejsciowki\ewejsciowki-back-office-frontend\dist\libs\channels
------------------------------------------------------------------------------

Build at: 2022-02-07T13:29:05.827Z - Time: 2571ms


Compilation complete. Watching for file changes...
```

**Comment by walec51** [comment]
@vsavkin could you please reopen this issue?

**Comment by walec51** [comment]
also tried `nx run-many --all --target=build --watch --parallel --maxParallel=100` same result, `voucher` lib is not getting build

**Comment by walec51** [comment]
hmm, come to think of it this may by related to

https://github.com/nrwl/nx/issues/5570
