### ISSUE TITLE
nx lint doesn’t recognize the files option

### ISSUE THREAD

**Issue by Frikki** [nrwl/nx#5013]
## Current Behavior

`nx lint --files=myfile.js` errors with the message `'files' is not found in schema`.

## Expected Behavior

Nx lint should include the files specified as per [the documentation](https://nx.dev/latest/angular/cli/lint#common-options).

## Steps to Reproduce

Run `nx lint --files=<your-file>`, replacing `<your-file>` with any file in your project.

### Failure Logs

```shell
nx lint --files=myfile.js

> nx run data-explorer-desktop-app:lint --files=myfile.js 
'files' is not found in schema
```

### Environment

```shell
  Node : 14.15.4
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 11.4.0
  @nrwl/cli : 11.4.0
  @nrwl/cypress : 11.4.0
  @nrwl/devkit : 11.4.0
  @nrwl/eslint-plugin-nx : 11.4.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.4.0
  @nrwl/linter : 11.4.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.4.0
  @nrwl/web : Not Found
  @nrwl/workspace : 11.4.0
  typescript : 4.0.5
```

**Comment by vsavkin** [comment]
I think the docs were written for TSLint. I think the option you can use is `lintFilePatterns`.
