### ISSUE TITLE
Schematics - error TS5042: Option 'project' cannot be mixed with source files on a command line

### ISSUE THREAD

**Issue by sivani-pa** [nrwl/nx#5017]
Getting below error when trying to run schematics.
error TS5042: Option 'project' cannot be mixed with source files on a command line.

Below are the commands run to create and run schematic,

nx generate @nrwl/workspace:workspace-schematic new-schematic
nx workspace-schematic new-schematic test

**Comment by FrozenPandaz** [comment]
Can you provide a repo that we can pull down to help reproduce the issue?

If not, please provide the output of `nx report`.

**Comment by sivani-pa** [comment]
the above issue got resolved. But getting another issue now. Below is the error & attached the screenshot of nx report,

getting tsconfig issues while running schematics

C:\Dev\nx-new\nextjs-nx\att\node_modules.bin\tsc -p C:\Dev\nx-new\nextjs-nx\att\tools\tsconfig.generated.json
node_modules/@nrwl/workspace/src/utils/rules/rename-npm-packages.d.ts:3:52 - error TS1005: ',' expected.

3 [packageName: string]: string | [newPackageName: string, version: string];
~

node_modules/@nrwl/workspace/src/utils/rules/rename-npm-packages.d.ts:3:69 - error TS1005: ',' expected.

3 [packageName: string]: string | [newPackageName: string, version: string];
~

node_modules/@types/node/index.d.ts:35:1 - error TS1084: Invalid 'reference' directive syntax.

35 ///
![image](https://user-images.githubusercontent.com/79601703/111566803-d5042080-876b-11eb-8989-7a5dac71bd83.png)

**Comment by sangaiah** [comment]
> the above issue got resolved. But getting another issue now. Below is the error & attached the screenshot of nx report,
> 
> getting tsconfig issues while running schematics
> 
> C:\Dev\nx-new\nextjs-nx\att\node_modules.bin\tsc -p C:\Dev\nx-new\nextjs-nx\att\tools\tsconfig.generated.json
> node_modules/@nrwl/workspace/src/utils/rules/rename-npm-packages.d.ts:3:52 - error TS1005: ',' expected.
> 
> 3 [packageName: string]: string | [newPackageName: string, version: string];
> ~
> 
> node_modules/@nrwl/workspace/src/utils/rules/rename-npm-packages.d.ts:3:69 - error TS1005: ',' expected.
> 
> 3 [packageName: string]: string | [newPackageName: string, version: string];
> ~
> 
> node_modules/@types/node/index.d.ts:35:1 - error TS1084: Invalid 'reference' directive syntax.
> 
> 35 ///
> ![image](https://user-images.githubusercontent.com/79601703/111566803-d5042080-876b-11eb-8989-7a5dac71bd83.png)

Can you please explain ? how did you resolve this issue?
