### ISSUE TITLE
Making installing packages on nx g lib optional

### ISSUE THREAD

**Issue by manfredsteyer** [nrwl/nx#5018]
#4087 makes Nx to install all packages when calling ``nx g lib``. However, this is time-consuming and most of the time not needed. Hence, it's annoying and it breaks my flow. Can we introduce a switch to bypass it?

**Comment by huv1k** [comment]
Yes, we had the same problem we are installing now `@nrwl/web` even that we don't use web components or plan to use it. Can it work the same as for `@nrwl/next`? So when you need it, it gets installed with the required dependencies.

**Comment by FrozenPandaz** [comment]
This is actually bug. No new flag is needed :sweat_smile:

**Comment by Coly010** [comment]
@FrozenPandaz 

I've done some investigation into this.

With the latest version of Nx, it appears that `nx g lib` does not _always_ attempt to reinstall packages.

Rather, it will only reinstall packages for generators that are still using `@angular-devkit`.

It appears that `@angular-devkit` will run an `npm install` of some form when a call to `externalSchematic` is made, which is used in some of our generators still.

**Comment by FrozenPandaz** [comment]
This issue is now fixed :tada: 

Node modules are not re-installed during lib creation if there are no changes to `package.json`
