### ISSUE TITLE
angular compiler doesn't ignore *.d.ts generated by prisma

### ISSUE THREAD

**Issue by SirBr4him** [nrwl/nx#5029]
adding prisma to my angular-nest project angular doesn't compile because it checks prisma auto generate types lib and it breaks. can you help tell the ts compiler to ignore the *.d.ts files in node_modules folder?

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by SirBr4him** [comment]
I resolved this by updating TypeScript from version 4.0.3 to 4.1.5.
Can you update TypeScript to version 4.1.x on the workspace creation?

**Comment by bekos** [comment]
@SirBr4him can you please create a minimal reproduction repo? that would help us a lot to understand and debug the issue 😃

**Comment by SirBr4him** [comment]
The problem was that prisma 2.18.0 isn't compatible with typescript 4.0.3 updating typescript to version 4.1.5 resolved my problem.
when you create a project with nx last version it the typescript in package.json is 4.0.3.
it's not a big deal i resolved so that's ok.
