### ISSUE TITLE
ng lint in v6

### ISSUE THREAD

**Issue by sirajc** [nrwl/nx#503]
With v6, ng lint runs linting for all projects, in case of Nx for all apps and libs. If we look at the https://github.com/nrwl/nx-examples/blob/master/angular.json file, each lib has same two `tsconfig.json` configured, which means that _ng lint_ will run lint on the same set of files?

For a large project, linting has become very slow in v6, hence looking for ways to optimize it. 

Also, what linting is carried out by `nx lint`?

**Comment by vsavkin** [comment]
> each lib has same two tsconfig.json configured

This is the way the way the Angular CLI does it right now. We don't want to deviate unless we have a very good reason to.

> For a large project, linting has become very slow in v6, hence looking for ways to optimize it.

Don't rerun linting on all projects--only relint wha is affected. Also, use `--parallel`.

```
yarn affected:lint -- --base=master --head=HEAD --parallel
```

We have thoughts on how to speed up linting, but it will be different from the default CLI setup, so we evaluating if it is worth it.

**Comment by rokie83** [comment]
I'm not sure if this is related but this was my best find on that topic currently. We have a Nx monorepo with multiple projects and libs in it . We updated to Angular 6 and Nx 6 now. And we noticed if we keep the following tslint.json rule our **ng lint** slows down to 34minutes - without the rule it takes less than 20 seconds.
```
    "nx-enforce-module-boundaries": [
      true,
      {
        "allow": [
          "@bx-client/features/account",
          "@bx-client/features/currency",
          "@bx-client/features/company",
          "@bx-client/features/user",
          "@bx-client/features/tax"
        ],
        "depConstraints": [
          {
            "sourceTag": "*",
            "onlyDependOnLibsWithTags": [
              "*"
            ]
          }
        ]
      }
    ] 
```

**Comment by rokie83** [comment]
The mentioned way (yarn affected:lint) by @vsavkin does work fine. 

Anyhow, at our team we noticed the following behaviour:
Executing a particular ng lint <projectname> on a small project does result in **Done in 165.82s**.

Doing the same excluding the **nx-enforce-module-boundaries** rule (which we really don't want to do) results in **Done in 21.39s**.

Any suggestions maybe?

**Comment by vitalyiegorov** [comment]
@vsavkin Recently our team also noticed that linting takes very long time, removing `nx-enforce-module-boundaries` speeded things up significantly.

**Comment by danielquintero** [comment]
We are having the same issue with a project at large scale. What we could find is that `tsconfig.lib.json` & `tsconfig.spec.json` which are included on the lint architect in `angular.json` extend from the main `tsconfig.json`, which will cause to also lint all of the declared `paths` per project being lint. 

In our case running just affected is not a solution as we are working on tooling and many teams adding libs/features thus writing to `angular.json`, building all projects in CI taking over 40min for linting.


@vsavkin do you really need to extend from the main `tsconfig.json` for the above mentioned files?

**Comment by jimdubbs** [comment]
Im also experiencing extremely long linting times in our project as well. Not sure how to try disabling the nx-enforce-boundries in an effort to speed things up.
