### ISSUE TITLE
Enhancement: Warn user if they clear out their public/ directory and it is not tracked by git

### ISSUE THREAD

**Issue by pitops** [nrwl/nx#5045]
![Screenshot 2021-03-16 at 10 06 31 PM](https://user-images.githubusercontent.com/9624361/111358525-dec25100-86a3-11eb-860f-8c9f55408506.png)

Locally it builds fine. Essentially as I understand the public folder is not included in git but only locally hence vercel is complaining because it's not there if left unused like i left mine. 

Adding a `.gitkeep` fixes the issue

**Comment by JamesHenry** [comment]
Hi @pitops, please follow the instructions on nx.dev for deploying to Vercel: https://nx.dev/latest/react/guides/nextjs#deploying-to-vercel

Those instructions state that you should not be toggling an override for the Vercel Output Directory, as you are here.

**Comment by pitops** [comment]
@JamesHenry that was not the issue. That toggle was an issue for the manifest. I was able to deploy after adding a `.gitkeep` and then toggling that off to remove the `route-manifest.json` error. Please reopen this ticket.

**Comment by JamesHenry** [comment]
@pitops I think adding a feature to detect and warn the user if they clear out their public directory and don't add any files to allow git to track it makes sense.

**Comment by pitops** [comment]
That would be great if you don't consider it a bug, at least warn users would be lovely.

**Comment by JamesHenry** [comment]
@pitops Yes the reasons why I don't currently see it as a bug in Nx:

- Nx generates a working setup out of the box, in order to get to this state the users has to cause it by emptying out their public directory entirely and not adding something, like a .gitkeep, to keep the folder around.
- This is just how git works, it's nothing specific to its use with a directory called public or within an Nx context

**Comment by pitops** [comment]
Yes it makes sense however, having a public folder with these two files inside its almost certain that people will delete those

![Screenshot 2021-03-25 at 12 41 00 PM](https://user-images.githubusercontent.com/9624361/112460250-5ad52c80-8d67-11eb-85bb-13f3e8972d1d.png)

Which means the DX automatically degrades. It would make more sense to have a `.gitkeep` in there to avoid causing headaches to devs who are not aware of that as I was. If they delete the `.gitkeep` file thats on them. That's why I see it as a bug because NX itself is causing the unaware developer this headache.

**Comment by cyrus-za** [comment]
+1 on this issue. I've ran into it a few times when I bootstrap a new app and delete the unused images. Luckily I knew exactly why this happened as I've used nextjs many years before using nx, but other user may not. 

Simply adding a .gitkeep in there as part of the app scaffolding should do the trick.

**Comment by JamesHenry** [comment]
I discussed this with @kirjai and he will work on some protection against user error/clearer warnings in this area in the near future
