### ISSUE TITLE
Stale depedency node-sass

### ISSUE THREAD

**Issue by SanderElias** [nrwl/nx#5049]
## Current Behavior

Node-sass is required by Nx
```bash
npm list node-sass
myProject@1.0.0 /somewhere_on_filesystem
└─┬ @nrwl/builders@7.8.7
  └─┬ @angular-devkit/build-angular@0.13.10
    └── node-sass@4.13.1 
```

## Expected Behavior

The dependency not being there. 
1. It is a deprecated dependency
2. the Angular CLI will raise a warning when present. 
3. Project is not even using sass/scss
4. it takes a stupid amount of time to build in CI/CD

**Comment by FrozenPandaz** [comment]
Hey @SanderElias 

`@nrwl/builders` is an old package. It shouldn't exist in up to date workspaces and can be removed. If it's an older workspace, please update to the latest version.

For instance, `npm ls node-sass` in https://github.com/nrwl/nx-examples does not return any dependencies.
