### ISSUE TITLE
Automatic upgrade to nx 6 fails

### ISSUE THREAD

**Issue by zlepper** [nrwl/nx#505]
Ran commands `npm install @nrwl/schematics@latest --save-dev` and `npm run update`. This fails for some reason. I have linked the run log. 

Log file: https://gist.github.com/zlepper/5d235fa2b5a3cfb396e8e4d15eb362b4

EDIT: Also added the angular-cli.json file, as I have a feeling some expectations about project structure might be failing.

**Comment by merlosy** [comment]
It fails for me as well:
```
Migration 20180515-switch-to-nx6 failed
{ Error: Command failed: ng generate @schematics/update:migrate --package @nrwl/schematics --collection @nrwl/schematics/migrations/migrations.json --from 1.0.3 --to 6.0.0
```

**Comment by FrozenPandaz** [comment]
@zlepper 
Thank you for the logs, helped a ton!
Good news: Looks like most of the migration was successful!

There were 2 issues though:
### Your `mediamanager` library
Looks like you don't have the directory which was specified in your `.angular-cli.json` here https://gist.github.com/zlepper/5d235fa2b5a3cfb396e8e4d15eb362b4#file-angular-cli-json-L143. We tried to move that `src` directory into a `lib` directory for you so I would reference your other libs to see how it should have been done. Below are the steps which did not succeed:

* You might have to update the `/tsconfig.json` in your root directory to have path mappings.
* You should consider creating a `libs/mediamanager/src/index.ts` file to export things from that lib.

### You have a lot of files
This is probably a good thing! The last step of the migration to format all of your files ended up being too long for node to execute.. We'd need to take a look at how we can solve this issue. Your best option here might be to run subsets of that command through your files. I'm not sure what would happen if you just pasted it into the terminal

**Comment by FrozenPandaz** [comment]
@merlosy If possible, could you also post a log or a repo?

**Comment by zlepper** [comment]
Removing the lib/mediamanger does indeed fix one issue, however as you mentioned yourself, the autoformatter still fails. 

How come the autoformatter is an issue now? We have run `npm run format` many times with the previous version of nx without issues?

**Comment by FrozenPandaz** [comment]
The autoformatter collects files that have changed and this migration changes many files because of the large difference between Nx 1.x and Nx 6.0+ . Most likely, for normal dev changes it will not be an issue.

I am not sure if installing the `@angular/cli` along with schematics would help. That is done for you during the migration.

**Comment by merlosy** [comment]
@FrozenPandaz My repo is available here: https://github.com/merlosy/ngx-material-file-input/tree/ng6

I started a branch for the upgrade...
Basically I just used these commands:
```
npm i -D @nrwl/schematics@latest
npm run update
```

and the second one crashes.
Thanks for your help!

**Comment by FrozenPandaz** [comment]
@merlosy Thank you, I was able to replicate the issue.

**Comment by merlosy** [comment]
@FrozenPandaz any update about this one?
It isn't working properly yet...

**Comment by zlepper** [comment]
How is the progress coming along on this? It's really frustrating that something that is supposed to be "for enterprise" can't even handle that many components without exploding...

**Comment by FrozenPandaz** [comment]
Formatting files during migration should now be batched as introduced in https://github.com/nrwl/nx/pull/727
