### ISSUE TITLE
Docs: Error in command for generating new NX workspace

### ISSUE THREAD

**Issue by juristr** [nrwl/nx#506]
I didn't find the docs repo, so I'm filing an issue rather than a PR. In the [docs here](https://nrwl.io/nx/guide-nx-workspace) the command for creating a new NX workspace is written as

```
ng new myworkspacename --@collection=@nrwl/schematics
```

..while it should be 

```
ng new myworkspacename --collection=@nrwl/schematics
```

There's an `@` too much 😄.

Just as a side-note, is `create-nx-workspace` obsolete?

**Comment by jschwarty** [comment]
Thx @juristr for reporting that. Will update the docs and let you know when it is published.

**Comment by jschwarty** [comment]
@juristr This has been published. Thanks again for reporting it!!!
