### ISSUE TITLE
Unable to create an Nx workspace with Stencil library working together with tailwind

### ISSUE THREAD

**Issue by davidrock** [nrwl/nx#5062]
I am having a bad experience trying this tool.
Creating the workspace is fine, but when I try to add a stencil library it returns A LOT of errors.

I tried to follow the official docs and official nx extension (nxext.dev) for both Stencil and Tailwind, but with no success.

## Current Behavior
First I ran: `nx g @nxext/stencil:application design-system`
And I got: `Cannot find module '@angular-devkit/core'`

So I installed it with: `npm i @angular-devkit/core -D `

Ok, I tried again and got another one: `Cannot find module '@angular-devkit/schematics/tools'`

After installing this one (without the "/tools" in the name) I was able to generate the library, but I cannot make it run!

I made the lib buildable and add the Outputtargets for _react and angular_ with the following commands:

```
nx g @nxext/stencil:make-lib-buildable design-system
nx g @nxext/stencil:add-outputtarget design-system
```

After that, I ran `nx build design-system` and got more errors: `Cannot find module '@angular-devkit/architect'`

Again, I installed this package and finally make it build. 
But, I want to use Stencil with Tailwind, so I installed the extension: `npm install @nxext/tailwind --save-dev`
And I ran the command to integrate them available on the nxext.dev docs.

`nx g @nxext/tailwind:stencil design-system`

Now, another error: `Cannot read property 'flags' of null`

And I just can't get away from this error.

## Expected Behavior
The expected behavior should not be this kind of errors when following strictly what the docs say I need to do, since I am not trying to install anything that is not in the docs of **Nx** and **Nxext**.

## Steps to Reproduce
I forked and created a PR and reproduced my problem there.
You can find it here: https://github.com/nrwl/nx-examples/pull/135

### Failure Logs
1st error:
```
Cannot find module '@angular-devkit/schematics/tools'
Require stack:
- /Users/david/dev/rockspace/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
- /Users/david/dev/rockspace/node_modules/@nrwl/tao/src/commands/generate.js
- /Users/david/dev/rockspace/node_modules/@nrwl/tao/index.js
- /Users/david/dev/rockspace/node_modules/@nrwl/cli/lib/init-local.js
- /Users/david/dev/rockspace/node_modules/@nrwl/cli/bin/nx.js
- /Users/david/.nvm/versions/node/v14.16.0/lib/node_modules/nx/node_modules/@nrwl/cli/bin/nx.js
- /Users/david/.nvm/versions/node/v14.16.0/lib/node_modules/nx/bin/nx.js
```
2nd:
```
Cannot find module '@angular-devkit/schematics/tools'
Require stack:
- /Users/david/dev/rockspace/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
- /Users/david/dev/rockspace/node_modules/@nrwl/tao/src/commands/generate.js
- /Users/david/dev/rockspace/node_modules/@nrwl/tao/index.js
- /Users/david/dev/rockspace/node_modules/@nrwl/cli/lib/init-local.js
- /Users/david/dev/rockspace/node_modules/@nrwl/cli/bin/nx.js
- /Users/david/.nvm/versions/node/v14.16.0/lib/node_modules/nx/node_modules/@nrwl/cli/bin/nx.js
- /Users/david/.nvm/versions/node/v14.16.0/lib/node_modules/nx/bin/nx.js
```

3rd:
```
Cannot find module '@angular-devkit/architect'
Require stack:
- /Users/david/dev/rockspace/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
- /Users/david/dev/rockspace/node_modules/@nrwl/tao/src/commands/run.js
- /Users/david/dev/rockspace/node_modules/@nrwl/tao/index.js
- /Users/david/dev/rockspace/node_modules/@nrwl/cli/lib/run-cli.js
```

Last error:
`Cannot read property 'flags' of null`

### Environment
Node : 14.16.0
  OS   : darwin x64
  npm  : 6.14.11
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.5.1
  @nrwl/cypress : 11.5.1
  @nrwl/devkit : 11.5.1
  @nrwl/eslint-plugin-nx : 11.5.1
  @nrwl/express : Not Found
  @nrwl/jest : 11.5.1
  @nrwl/linter : 11.5.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.5.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.5.1
  @nrwl/web : 11.5.1
  @nrwl/workspace : 11.5.1
  @nrwl/storybook : 11.5.1
  @nrwl/gatsby : Not Found
  typescript : 4.0.7

I don't know what else to do, I can't get further after this error. I tried many versions (10, 11, 12, 13, 14) of Nodejs, no progress either.

**Comment by brandonroberts** [comment]
The issue here is that `@nxext/stencil` schematics rely on the Angular Devkit, but those dependencies aren't installed in an `empty` workspace. We've recently introduced the Nx Devkit, but not all plugins have migrated to it yet. To get a running workspace, use the following steps.

```sh
npx create-nx-workspace@latest nx5062 --preset=empty
cd nx5062
npm install @nrwl/angular
nx g @nrwl/angular:init
``

Then add @nxext/stencil and use the schematics

```sh
npm install @nxext/stencil
nx g @nxext/stencil:app my-app
```

If you need further assistance, join the []Nrwl Community Slack Workspace](http://go.nrwl.io/join-slack)
