### ISSUE TITLE
createProjectGraph() doesn't work using runNxCommandAsync()

### ISSUE THREAD

**Issue by Brian-McBride** [nrwl/nx#5065]
## Current Behavior
I am using the plugin generator. 
```
await runNxCommandAsync(`build ${plugin} --skip-nx-cache`);
```

Overall, the generator seems really easy to use. Out of the box, it works. 

Then, I want to follow the conventions set up in `@nrwl/node` as I'm doing a builder very similar. Of course, the e2e tests are way more complicated there. And might know why

If you just try to do this: 
```typescript
export function esbuildExecutor(
  rawOptions: BuildExecutorSchema,
  context: ExecutorContext
) {
  const projGraph = createProjectGraph();
  conole.log(projGraph) // take a peek
  return Promise.resolve({ success: true }) ​
}
```

The `projGraph` value will be set to the outer project, not the generated `./tmp/nx-e2e/proj` where it is expected.

## Expected Behavior
Within e2e tests, `createProjectGraph` should return data about the testing project, not the parent plugin project.

## Steps to Reproduce
I think the sample above shows the code. 
Just use the nx tools to create new plugin library, then, then try to use `createProjectGraph` when running your e2e tests. You'll see that it give you the graph for the root project, not the temp one you created in the temp folder. 

My guess, based not eh completely different test code running in the @nrwlnode tests, is that the CWD is not being set correctly somewhere in that pipeline.

**Comment by Brian-McBride** [comment]
Oh, yeah. I thought, well, heck, I should just copy over the tests that clearly work in the nx repo.

`@nrwl/e2e/utils` isn't something that seemed exported or published anywhere?

The dev tools work is great. I could see a lot more adoption by my teams. I think it would help to have more results in the tools. How do you get the tree for `./tmp/nx-e2e/proj`? 

My end goal is to check dependencies for some stages of my build process. When I saw what was happening in @nrwl/node I was thinking, "oh, making sure you have built the supporting packages... smart"....

**Comment by simondotm** [comment]
Fwiw, the `context.root` directory passed into my executor is correct.

**Comment by simondotm** [comment]
Ok a bit more digging...
`const projGraph = createProjectGraph();` has 3 default parameters:
`readWorkspaceJson(), readNxJson(), readWorkspaceFiles()`

These are not correct. If I log them in my executor, I see right away they are the parent workspace, not the e2e workspace.
```
  console.log("readWorkspaceJson=", JSON.stringify(readWorkspaceJson(), null, 3))
  console.log("readNxJson=", JSON.stringify(readNxJson(), null, 3))
  console.log("readWorkspaceFiles=", JSON.stringify(readWorkspaceFiles(), null, 3))
```

**Comment by simondotm** [comment]
Ok setting environment variable `NX_WORKSPACE_ROOT_PATH` to the e2e workspace root fixes the issue, and my executor now gets the correct project graph.
Now squinting  at: https://github.com/nrwl/nx/blob/d007d37fb4f625fc4854d06d2e083ed778d6a3db/packages/workspace/src/utilities/app-root.ts

**Comment by simondotm** [comment]
ok this is strange: `pathInner()` function in app-root uses `__dirname` as a starting point to unwrap parent directories until it hits a `workspace.json` or `angular.json`
Since `__dirname` is the script being currently run, I console logged this from my executor in the e2e workspace and it revealed the `dist\packages\<plugin>\src\executors\<executor>` script folder, not the `node_modules` folder in the e2e workspace that I expected to see.  So that explains why we get the parent workspace graph, not the e2e plugin graph.

**Comment by simondotm** [comment]
And now of course I realize the e2e workspace `package.json` has my plugin as a local file reference:
`"@myorg/myplugin": "file:<pathto>\\myplugin/dist/packages/myplugin"

**Comment by simondotm** [comment]
Also, linking to a related issue #4157

**Comment by AgentEnder** [comment]
@Brian-McBride Does this still occur w/ latest Nx?

**Comment by Brian-McBride** [comment]
@AgentEnder I haven't had the time to test it. I created an e2e test around the issue and haven't thought about it since. 
I can try to get to that project this week sometime and check it out though.

**Comment by tbinna** [comment]
@AgentEnder this issue still exists for me in Nx 13.9.4. In my case exposed when running e2e tests that invoke a custom build executor (we have been chatting about this over on Slack).

**Comment by simondotm** [comment]
For various reasons I had to regress a workspace to nx 13.10.6 and got hit by this issue _again_, gah.
