### ISSUE TITLE
Seems like there is unreachable code in workspace/src/core/project-graph/operators.ts

### ISSUE THREAD

**Issue by kenptr** [nrwl/nx#5067]
https://github.com/nrwl/nx/blob/4eebad2a6d7764d00aa8ca030ed91ce8235160b6/packages/workspace/src/core/project-graph/operators.ts#L93

Sorry, it might be a confusion. In this function the code below `return builder.build();` is unreachable, right?  Is it expected?

```ts
export function withDeps(
  original: ProjectGraph,
  subsetNodes: ProjectGraphNode[]
): ProjectGraph {
  const builder = new ProjectGraphBuilder();
  const visitedNodes = [];
  const visitedEdges = [];
  Object.values(subsetNodes).forEach(recurNodes);
  Object.values(subsetNodes).forEach(recurEdges);
  return builder.build();

  // ---------------------------------------------------------------------------

  // other code
}
```

@jaysoo - pinging the author

**Comment by vsavkin** [comment]
Hi there!

Those are function definitions used in the withDeps function, so they are reachable because withDeps invokes them. We could have moved those out of withDeps, but it would have made the code clunkier.

Thank you!

**Comment by kenptr** [comment]
Wow! this is magic ) thanks for explaining
