### ISSUE TITLE
lint command does not respect "quiet" option when using `run-many`

### ISSUE THREAD

**Issue by JeuelyFish** [nrwl/nx#5069]
## Current Behavior
Running eslint commands with `--quiet` flag only work on a per project command, but not with `run-many`.

For example, `nx lint my-library --quite` does not display warnings in logs.
However, `nx run-many --target=lint --all --quiet` does.

## Expected Behavior
The nx lint commands should respect the "quiet" configuration option, even when using the `run-many` command

### Environment
Current nx version "11.3.1"

### Related Issues

See https://github.com/nrwl/nx/pull/4330
and ahaskell35[ comment here](https://github.com/nrwl/nx/pull/4330#issuecomment-778401083)

**Comment by vsavkin** [comment]
Some flags can be used by both Nx and the executors Nx invokes (e.g., help, verbose, quiet). You can pass the flag to the executors by splitting the flags using --, as follows:

```
nx run-many --target=lint --all -- --quiet
```

Thank you!

**Comment by bbugh** [comment]
@vsavkin In "nx": "^12.3.4", that doesn't work. With that exact command, the help prints, and this error appears:

```
» yarn nx run-many --target=lint --all -- --quiet

<help text>
Missing required argument: target
```


exit code 1.
