### ISSUE TITLE
Storybook: Incorrect environment when running in dev mode

### ISSUE THREAD

**Issue by esjs** [nrwl/nx#5070]
## Current Behavior
When I run `nx run [package-name]:storybook` I see that `process.env.NODE_ENV` is set to `production`

## Expected Behavior
According to [schematics](https://github.com/nrwl/nx/blob/master/packages/storybook/src/executors/storybook/schema.json#L4) description the mode should be set to `development`

## Steps to Reproduce
Run storybook for any project and `console.log(process.env.NODE_ENV)`, it will output `production`

I've spent some time to find a source of this problem, and looks like I've managed to isolate it.
So, if we look at storybook source code, we can find that they generate special configuration which will be added to webpack build config as plugin
https://github.com/storybookjs/storybook/blob/next/lib/core-common/src/utils/envs.ts#L6-L20
see example webpack config from .storybook/webpack.config.js file
![image](https://user-images.githubusercontent.com/2673700/111808337-9772d500-88dc-11eb-8b3b-041454ebc8e0.png)

The problem here is that we don't pass NODE_ENV and Storybook fallback is `production`.

I've bootstraped create-react-app basic app with  storybook and found the difference in what they do relative to NX config.
The difference is that start-storybook after all initialization calls [buildDev](https://github.com/storybookjs/storybook/blob/next/lib/core-server/src/build-dev.ts#L115) method which in it's turn runs development config where they [set NODE_ENV to `development` if not provided](https://github.com/storybookjs/storybook/blob/next/lib/core-server/src/cli/dev.ts#L7-L11) after all of that they call [buildDevStandalone](https://github.com/storybookjs/storybook/blob/next/lib/core-server/src/build-dev.ts#L119-L127)

but if we look at NX build config, we see that

It calls [buildDevStandalone](https://github.com/nrwl/nx/blob/master/packages/storybook/src/executors/storybook/storybook.impl.ts#L52-L54) directly without specifying NODE_ENV.
I've tested what happens if we would set `NODE_ENV` to `development` before execution this command (see screenshot below), and webpack correctly built React in development mode and `process.env.NODE_ENV` reponts `development` as expected.
![image](https://user-images.githubusercontent.com/2673700/111811868-2df4c580-88e0-11eb-9ff7-e2d189e722ad.png)

I can prepare PR if such change will be accepted by NX team.

### Failure Logs
-

### Environment
  Node : 12.16.3
  OS   : darwin x64
  yarn : 1.22.4
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.4.0
  @nrwl/cypress : 11.4.0
  @nrwl/devkit : 11.4.0
  @nrwl/eslint-plugin-nx : 11.4.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.4.0
  @nrwl/linter : 11.4.0
  @nrwl/nest : Not Found
  @nrwl/next : 11.4.0
  @nrwl/node : 11.4.0
  @nrwl/react : 11.4.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.4.0
  @nrwl/web : 11.4.0
  @nrwl/workspace : 11.4.0
  typescript : 4.0.7

**Comment by puku0x** [comment]
Related to #4942 ?

**Comment by esjs** [comment]
Looks like it is, indeed.
