### ISSUE TITLE
Provide a way to increase max heap size for @nrwl/cypress

### ISSUE THREAD

**Issue by rayriffy** [nrwl/nx#5075]
## Current Behavior

Cypress unit is only limiting to 2GB of maximum memory usage, and there's no any arguments to extend memory limit

## Steps to Reproduce

I cannot put real tests in here because code is internal, sorry.

- Use condition of normal runner (2 CPU-core, 7 GB of memory)
- Running heavy e2e tests on website which include heavy use of memory
- Observe memory usage

### Failure Logs

Because Cypress can use only 2GB of memory, it take some fetch too long to render and causes Cypress to yeet itself

```
AssertionError: Timed out retrying after 60000ms: Expected to find element: `[data-testid=design-leads]`, but never found it.
```

### Environment

```
  Node : 10.19.0
  OS   : linux x64
  yarn : 1.22.5

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.3.2
  @nrwl/cypress : 11.3.2
  @nrwl/devkit : 11.3.2
  @nrwl/eslint-plugin-nx : 11.3.2
  @nrwl/express : Not Found
  @nrwl/jest : 11.3.2
  @nrwl/linter : 11.3.2
  @nrwl/nest : Not Found
  @nrwl/next : 11.3.2
  @nrwl/node : 11.3.2
  @nrwl/react : 11.3.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.3.2
  @nrwl/web : 11.3.2
  @nrwl/workspace : 11.3.2
  typescript : 4.1.3
```

**Comment by vsavkin** [comment]
Thank you for submitting the issue.

@Cammisuli I imagine it might be the node limit, which I believe should be inherit from the process (cause we fork). We need to make sure that's the case. I imagine same issue applies to every other executor, so we should probably document it somewhere.

**Comment by rayriffy** [comment]
Oh thanks for a reply, but I think I tried to overwritten max space to `nx` executor once but that isn't affect to Cypress process at all (but that long time ago, I already forgot).

But to clarify the issue, I brought footage with me as well (in this case I saw `Using 1 worker with 2048 MB memory` came up and taught that TypeScript checker might blocking memory limit so I tried to overwritten plugin to accepts more memory as well but that's doesn't work)  ([to unlisted video](https://youtu.be/kzmsapeH27Y))

**Comment by rayriffy** [comment]
Hello, any updates on this? I attempted to override via `NODE_OPTIONS` environment variable but still no hope

**Comment by Cammisuli** [comment]
Hi @rayriffy, I haven't checked up on this. I'll try to make some time this week and take a deeper look.

 But have you tried running nx directly like this:
`node --max-old-space-size=10000 ./node_modules/.bin/nx`

I had more success using that flag than setting the environment variable.
