### ISSUE TITLE
Cannot disable <base /> tag in web application

### ISSUE THREAD

**Issue by rokkie** [nrwl/nx#5079]
Hi!

I'm not entirely sure if this should be a feature request, but going of what I read in the source I suspect the intended behaviour is different that what it's currently doing.

## Current Behavior
When building/compiling a web application, the `<base />` tag is _always_ added to the `<head />` of the `index.html` file.
In our case this gets in the way and we want to turn it of completely.

## Expected Behavior
Passing `null` or an empty string to the `baseHref` option to disable the `<base />` tag.

## Steps to Reproduce
1. Generate a web app in a workspace
2. Pass `null` or an empty string to the `baseHref` option of the build/serve target of the application in `workspace.json`
3. build/serve the application

When passing `null`, building/compiling fails altogether, when passing an empty string a `<base href="(unknown)" />` is injected.

The `augment-index-html` utility seems to (try to) accomodate for excluding a `<base />` tag going of [this comment](https://github.com/nrwl/nx/blob/ba38da909c4ac96515ddeada282cb84632aafece/packages/web/src/utils/third-party/cli-files/utilities/index-file/augment-index-html.ts#L193). But the condition checks for `typeof params.baseHref == 'string'`, and the schema of the [build](https://github.com/nrwl/nx/blob/ba38da909c4ac96515ddeada282cb84632aafece/packages/web/src/builders/build/schema.json#L36), and [serve](https://github.com/nrwl/nx/blob/ba38da909c4ac96515ddeada282cb84632aafece/packages/web/src/builders/dev-server/schema.json#L68) builder _require_ this to be a string and provides a default value of `/`. Thus, the `<base />` tag is always added.

To fix this, it seems you can either
- allow `null` to be passed by changing the schema of the builder(s), or
- also check if `params.baseHref` is not an empty string.

I'm willing so submit a PR but I don't know if there is a preference for one of the options.

### Environment
NX version `11.5.2`

**Comment by KeKs0r** [comment]
I ran into this exact issue just now. I have not found an example on how to allow `null` as value in schema.json. I tried it with allowing `boolean` and passing in false. This prevents the `<base>` tag from being added, but feels wrong.

**Comment by rokkie** [comment]
From what I understand from the [reference](http://json-schema.org/understanding-json-schema/reference/type.html), this should work: `{ "type": ["string", "null"] }`

**Comment by KeKs0r** [comment]
Ahh thanks for pointing it out.
I somehow think the `null` option then is more explicit and more descriptive. 

Unrelated question: @rokkie How did you modify the rest of the config, all webpack generated files don't work without the `<base>` tag, since the generated script tags are relative:
```
<script src="client/runtime.efb022fb59d95dbe4674.js" type="module"></script>
```

**Comment by rokkie** [comment]
By overriding the webpack config and setting the `publicPath`.

**Comment by KeKs0r** [comment]
I just wanted to put together a PR for this. Unfortunately it does not seem to work with `"null"`


I have tried two variations:
```
Property 'baseHref' does not match the schema.
{
  "type": [
    "string",
    "null"
  ],
  "description": "Base url for the application being built.",
  "default": "/"
}'
```

as well as

```
Property 'baseHref' does not match the schema.
{
  "oneOf": [
    {
      "type": "string"
    },
    {
      "type": "null"
    }
  ],
  "description": "Base url for the application being built.",
  "default": "/"
}'
```

I also did not find any example of allowing "null" within the nx repository. Not sure which library is used to actually validate the schema.
