### ISSUE TITLE
fix(upgrade): errors upgrading for older versions of Node

### ISSUE THREAD

**Issue by ThomasBurleson** [nrwl/nx#508]
It appears that `npm run update` requires latest version of @angular/cli 6 to be installed first.

> We should auto install @angular/cli 6 if it has not been installed.

It also appears to that Nx requires Node >= v8.9. 

>  We should fail gracefully for older versions.

**Comment by vsavkin** [comment]
> It also appears to that Nx requires Node >= v8.9.

Could you expand on it? What requires 8.9?

**Comment by bcabanes** [comment]
Hi!

Closing old issue.
