### ISSUE TITLE
TypeORM migration issue with Nestjs in Nx monorepo

### ISSUE THREAD

**Issue by nhaancs** [nrwl/nx#5084]
## Current Behavior
Serve a Nestjs app (have migrations) cause the error below:
```
"/home/nhaancs/workspace/realworld/migrations/1603352814806-InitUser.ts:1
import { MigrationInterface, QueryRunner, Table } from "typeorm";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /home/nhaancs/workspace/realworld/src/util/DirectoryExportedClassesLoader.ts:41:22
    at Array.map (<anonymous>)
    at Object.importClassesFromDirectories (/home/nhaancs/workspace/realworld/src/util/DirectoryExportedClassesLoader.ts:41:10)
```

ormconfig.js
```
const { getMetadataArgsStorage } = require("typeorm");

module.exports = {
  type: 'mysql',
  host: 'localhost',
  port: 3306,
  username: 'root',
  password: 'qwerty1',
  database: 'realworld_db',
  synchronize: false,
  entities: getMetadataArgsStorage().tables.map(tbl => tbl.target),
  timezone: 'Z',
  bigNumberStrings: false,
  migrations: ["migrations/*.ts"],
  cli: {
    migrationsDir: "migrations"
  },
  extra: {
    // connectionLimit: 5
  }
}
```

## Expected Behavior
Does not cause error above when serve the Nestjs app.

## Steps to Reproduce
Github repo: https://github.com/nhaancs/fullstack-nestjs-angular-nx-monorepo-realworld

You can reproduce the issue by clone this repo, install dependencies, setup mysql like the config, then serve the api app.

### Environment
 Node : 14.15.1
  OS   : linux x64
  npm  : 6.14.8
  
  nx : Not Found
  @nrwl/angular : 11.5.2
  @nrwl/cli : 11.5.2
  @nrwl/cypress : 11.5.2
  @nrwl/devkit : 11.5.2
  @nrwl/eslint-plugin-nx : 11.5.2
  @nrwl/express : Not Found
  @nrwl/jest : 11.5.2
  @nrwl/linter : 11.5.2
  @nrwl/nest : 11.5.2
  @nrwl/next : Not Found
  @nrwl/node : 11.5.2
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.5.2
  @nrwl/web : Not Found
  @nrwl/workspace : 11.5.2
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.0.7

**Comment by nhaancs** [comment]
I fixed this issue by:
- update ormconfig.js to 
```
module.exports = {
  ...
  migrations: ["migrations/*.js"], // was ts
  ...
}
```
- and update the npm script in package.json file:
```
{
    ...
    scripts: {
        ...
        "migration:run": "npx tsc migrations/*.ts --outDir migrations && ./node_modules/.bin/typeorm migration:run",
        ...
    }
    ...
}
```

**Comment by bekos** [comment]
@nhaancs your reproduction link doesn't work 😕

**Comment by developer239** [comment]
@nhaancs Guys running customized or additional migration scripts is not a solution.
