### ISSUE TITLE
fix(schematics): missing dev dependency

### ISSUE THREAD

**Issue by ThomasBurleson** [nrwl/nx#509]
Angular CLI and Nx 6 installs do not install the required **`@angular-devkit/build-angular`**.

**Comment by FrozenPandaz** [comment]
`@angular-devkit/build-angular` should be provided by `@angular/cli` for the most part.
* In existing projects, it would come from `npm run update` which runs `ng update @angular/cli` and should bring it in.
* In new projects, created with Nx, it is in the `ng-new` generated `package.json`.
  * This is the only place we need to specify it right now, and I see it here: https://github.com/nrwl/nx/blob/master/packages/schematics/src/collection/ng-new/files/__directory__/package.json#L52
* In new projects, created with the `@angular/cli` it would be in their generated `package.json`.

I guess the only time this would not be the case is if the user manually runs `ng update @nrwl/schematics` without `ng update @angular/cli` but that should throw an error.

Am I missing something?

**Comment by ThomasBurleson** [comment]
```
npm i @angular/cli@latest --save-dev
npm i @nrwl/schematics@latest --save-dev
npm run update
```

The error manifests when I do:

```
ng run customer-portal:serve
```
