### ISSUE TITLE
React 17 default to `react-jsx` in tsconfig

### ISSUE THREAD

**Issue by cyrus-za** [nrwl/nx#5090]
With react 17 the import of React is not required to use jsx, but this is only possible if we got 
```json
  "compilerOptions": {
    "jsx": "react-jsx",
  }
```
in the tsconfig.json file. 

Can the `@nrwl/react` generator check the version of react in package.json and if its >= 17.0.0 then set that in tsconfig?

**Comment by ptrhck** [comment]
Did you try that? I have added a lib with `nx g @nrwl/react:lib shared-components`, removed the React import and changed all tsconfig options to `"react-jsx"`. Still, I am getting the error "React is not defined". May this be due to the `.babelrc` within the lib?

**Comment by jaysoo** [comment]
We can definitely do that in the next release, and update our babel presets as well.

**Comment by ptrhck** [comment]
@jaysoo Could you provide the corresponding option for the `@nrwl/react/babel` preset for a temporary workaround?

**Comment by jaysoo** [comment]
We'll need to update TS version as well to support `react-jsx`, so this PR addresses that https://github.com/nrwl/nx/pull/5116.

There's a separate PR incoming to update the generators and migrations.

Tartetting for Nx 12 release.

**Comment by cyrus-za** [comment]
Thanks @jaysoo looking forward to the next version

**Comment by puku0x** [comment]
`"importSource": "@emotion/react"` is needed for Emotion users.

```js
// tsconfig.json
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "jsx": "react-jsx",
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true
  },
  "files": [],
  "include": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ]
}
```

Moreover, `@emotion/babel-preset-css-prop"` should be replaced with `@emotion/babel-plugin`.

```js
// .babelrc
{
  "presets": [
    [
      "@babel/preset-react",
      {
        "useBuiltIns": true,
        "runtime": "automatic",
        "importSource": "@emotion/react"
      }
    ]
  ],
  "plugins": ["@emotion/babel-plugin"]
}
```

**Comment by jaysoo** [comment]
> Can we also add a eslint rule to not import the default export from react (seeing as that will eventually go away and be a breaking change)?

Does such a rule exist for React?

**Comment by jaysoo** [comment]
@puku0x Emotion migration has been added packages/react/src/migrations/update-12-0-0/update-emotion-setup.spec.ts

New apps/libs will also generate with `@emotion/babel-plugin` instead of `@emotion/babel-preset-css-prop`.

**Comment by cyrus-za** [comment]
@jaysoo I am not sure if there's a eslint rule for it right now. In fact the react-plugin-react/recommended preset for eslint has [this](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/react-in-jsx-scope.md) turned on which I had to explicitly turn off in my .eslintrc.json
```js
 rules: {
    'react/react-in-jsx-scope': 'off',
    'react/jsx-uses-react': 'off'
  }
```

I did however find this
https://github.com/yannickcr/eslint-plugin-react/issues/2829

Maybe the rule can be written as part of the @nrwl/react package?
```ts
  TSQualifiedName(node) {
    if (node.left.name === 'React') {
      context.report(
        node,
        'Do not use React qualifier, use import deconstruction instead',
      );
    }
  },
```

Further reading:
https://github.com/yannickcr/eslint-plugin-react/issues/2834
https://github.com/yannickcr/eslint-plugin-react/issues/2928

**Comment by jaysoo** [comment]
@cyrus-za Thanks for the pointers. We have turned the two eslint rules off in our `eslint-plugin-nx` rules. See: https://github.com/nrwl/nx/pull/5131/files#diff-8f62961a5b32590af61aaee94cab47b8cf5ca114fbb7bd17a2b1974ebc2c78d3R30

I've opened an issue here to capture your eslint rule request. https://github.com/nrwl/nx/issues/5198

**Comment by cyrus-za** [comment]
Thanks @jaysoo I'm upgrading to nx12 right now :)
