### ISSUE TITLE
`ng generate ngrx`: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by dherges** [nrwl/nx#51]
```bash
$ ng g ngrx
Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at Class.run (~\node_modules\@angular\cli\commands\generate.js:112:63)
    at resolve (~\node_modules\@angular\cli\ember-cli\lib\models\command.js:261:20)
    at Promise (<anonymous>)
    at Class.validateAndRun (~\node_modules\@angular\cli\ember-cli\lib\models\command.js:2
40:12)
    at Promise.resolve.then.then (~\node_modules\@angular\cli\ember-cli\lib\cli\cli.js:140
:24)
    at <anonymous>
```

Expected better error message / help.

**Comment by vsavkin** [comment]
could you provide a repro?

**Comment by dherges** [comment]
Hi Viktor @vsavkin,

here is the repository: https://github.com/dherges/nx-sandbox

It has been set up with the sandbox script (see above) on a Windows 7 64bit machine.

**Comment by maxime1992** [comment]
(I do have the exact same problem on Ubuntu 17.04 64 bit so it doesn't seem to be related to Windows)

**Comment by jschwarty** [comment]
The `ng g ngrx` command requires a `<name>` value and the `--module` option. 

```
ng g ngrx stateModelName --module=pathToModuleToAddItTo
```

I think the Angular CLI used to display error messages reporting when required generator options were not used. Maybe this changed. We need to take a look at that and see if that is a fix needed for the Angular CLI or if it is something we should add to the Nx schematic for ngrx.

**Comment by vsavkin** [comment]
The module param is marked as "required", so must be an issue with AngularCLI. I added a test to verify that: https://github.com/nrwl/nx/commit/d16db1a311512e6a4454bd193228cedc25ed3143

Closing this.
