### ISSUE TITLE
Export an nx library to npm

### ISSUE THREAD

**Issue by run1t** [nrwl/nx#510]
We are currently moving multiple projects to nx and I began to create a library in the nx workspace to unifiy the ui.

Unfortunately, migrating those projects take some times and I was wondering if there is a way to share the library on npm (temporarily) in order to begin to integrate and test the new components from the lib.

If you can just guide me to the good solution it would be very helpful ! 

In the same time I'll make a tool to export library from nx :)

**Comment by merlosy** [comment]
For what it's worth, these helped me:
- https://github.com/dherges/ng-packagr
- Jason Aden - Packaging Angular Libraries https://www.youtube.com/watch?v=QfvwQEJVOig (in the second half of the video)

**Comment by juristr** [comment]
If you're seeking for how to publish an Angular library out of an NX monorepo, I've created a GitHub repo [ngx-tabs-libdemo](https://github.com/juristr/ngx-tabs-libdemo) which I use to experiment with various setups (check out the different branches). These two are using NX:

- https://github.com/juristr/ngx-tabs-libdemo/tree/with-demoproj-setup
- https://github.com/juristr/ngx-tabs-libdemo/tree/multi-lib-monorepo

**Comment by run1t** [comment]
@merlosy @juristr thanks for the very fast response I'll try it out tomorrow !

**Comment by FrozenPandaz** [comment]
@run1t 
If you are using Nx6, `@angular/cli@6` now has the ability to generate and publish libraries. We've kept this functionality but it is hidden under a `--publishable` flag.

In a Nx6, workspace this should be the workflow:
```sh
ng generate lib libname --publishable
ng build libname
cd dist/libname
npm publish
```

**Comment by run1t** [comment]
@FrozenPandaz , @merlosy  and @juristr   Thanks  for your help !
I know have my library on NPM.
 
I was on `nx: 1.0.3`
So migrated to `Nx6`
I did that:
`npm install -g @nrwl/schematics@latest`
`npm install -g @angular/cli@latest`
`npm run update`

I had to remove my node_modules and reinstall all modules.
`rm -rf node_modules`
`npm install`

And then I did an 
`ng generate lib mylib --publishable`
`ng build mylib`
`cd dist/mylib`
`npm publish`

And it was done ! 👏

**Comment by nayfin** [comment]
This was the one thing that made me hesitant to switch to nx. I should have known you guys had it covered. Thanks for all the great tools!!!

**Comment by sameterap** [comment]
@run1t 
Have you tried to use 2 publishable libs that depends on each other ? Let's think that there are libs in the name of parent and child. Parent depends on child. If you run "ng build parent", you get an error. I just couldn't find a way to solve this issue. With some workarounds yes it is ok, but if you imagine that there are lots of dependencies, we should some how automate this. Any ideas ? Thanks in advance.

**Comment by run1t** [comment]
Hi, I never had this use case so I don't really know how it should work.
But If I understand it correctly you are using the published children lib in the parent.
Why not using the children lib directly via relative `from` import ?

**Comment by sameterap** [comment]
"Why not using the children lib directly via relative from import ?" : 
the case is that if a lib is completely deleted(with dependent libs, of course) and moved to an npm server. That's why relative import is not ok. Each lib individually should be built even if it has some dependencies. Thanks though.

**Comment by SSmale** [comment]
> @run1t
> Have you tried to use 2 publishable libs that depends on each other ? Let's think that there are libs in the name of parent and child. Parent depends on child. If you run "ng build parent", you get an error. I just couldn't find a way to solve this issue. With some workarounds yes it is ok, but if you imagine that there are lots of dependencies, we should some how automate this. Any ideas ? Thanks in advance.

This is something I am currently looking for too, did you have any luck solving the issue?
