### ISSUE TITLE
Problem running Storybook on mixed workspaces

### ISSUE THREAD

**Issue by mandarini** [nrwl/nx#5100]
## Current Behavior
On a mixed workspace, when Storybook is added on a different framework it does not run.
eg. 
Workspace with Angular and React libs/apps
Add Storybook in React lib or app
Works/runs
Add Storybook in Angular lib or app
Storybook is generated
Storybook does not run

## Expected Behavior
Storybook works on mixed workspaces.

## Steps to Reproduce
Scenario 1:
1. `create-nx-workspace` with react app
2. Generate react lib as well, and one component in react lib, one component in react app
3. `@nrwl/react:storybook-configuration` schematic for react lib and react app
4. `nx run <app and lib>:storybook`
5. SUCCESS!!

Scenario 2:
1. In same workspace, generate ANGULAR lib
2. generate angular component inside angular lib
3. `@nrwl/angular:storybook-configuration` for angular lib
4. `nx run <angular lib>:storybook`
5. `ERROR: Cannot find module '@storybook/angular/dist/server/options'`

And vice-versa

**Comment by mandarini** [comment]
@juristr I created this issue

**Comment by ringodotnl** [comment]
@mandarini getting the same issue with:
- setup as angular  (`npx create-nx-workspace --preset=angular`)
- add library (`nx generate @nrwl/angular:library sharedlibrary --directory shared --strict --publishable --importPath @myorg/sharedlibrary --buildable --style=scss`)
- add storybook  (`nx generate @nrwl/angular:storybook-configuration shared-sharedlibrary --generateStories --configureCypress --generateCypressSpecs`)
- nx run shared-sharedlibrary:storybook

also gives: ERROR: Cannot find module '@storybook/angular/dist/server/options'

**Comment by nayfin** [comment]
Any update on this? I am presenting a workshop on this in 2 weeks and I just ran `nx migrate` so that I would have the latest `nx workspace`, then this started happening.

**Comment by nayfin** [comment]
I updated `@nrwl/storybook` to "^11.6.0" and `@storybook/angular` to "^6.2.1", and that seems to have fixed it. Maybe migrations can be updated to account for this?
