### ISSUE TITLE
dep-graph depth option

### ISSUE THREAD

**Issue by artaommahe** [nrwl/nx#5101]
## Description
Right now dep-graph show all-depth dependencies that can be unusable for big repos with dozens of apps and hundreds of libs (like screenshot above, red area is where focused lib is)
![image](https://user-images.githubusercontent.com/1944061/112304346-6f092300-8cae-11eb-922f-02f6bcbc5bf4.png)

## Motivation

E.x. i want to view everyone who use some lib directly and everyone who is used by this lib directly (it's 3 and 5 libs for that lib from the screenshot above). Right now i cant do this and have to use grep or IDE search.

## Suggested Implementation

Adding depth option can allow to use dep-graph even for big repos.

## Alternate Implementations

¯\\\_(ツ)_/¯

**Comment by un33k** [comment]
@artaommahe I think we can just follow the `feature | issue` in one place. https://github.com/nrwl/nx/issues/6517?_pjax=%23repo-content-pjax-container#issuecomment-899660457
