### ISSUE TITLE
Fell back to using 'fs' to identify xxx as deleted

### ISSUE THREAD

**Issue by tsinghammer** [nrwl/nx#5104]
## Current Behavior
Since upgrading to 11.5.2 I am getting the error message "Fell back to using 'fs' to identify xxx as deleted" for every path that is not yet committed in Git.
Nx build immediately returns unless the changed files are committed.

## Expected Behavior
No such warning message and build executed if files have changed.

### Environment
Window 10 with Powershell

**Comment by bekos** [comment]
@tsinghammer Can you please share some steps to reproduce? Can you run `git status -s -u` when you see this error and paste it here?

**Comment by tsinghammer** [comment]
Hi @bekos for me it is quite easy to reproduce: Whenever there is an uncommitted file (added a new one or modified an existing one) I get this issue.
I've modified one file to narrow it doen, here is the result of `git status -s -u:`
` M apps/navigator/src/app/dashboard/transformations/edit/EditTransformationForm.tsx`
 So it is really just that file.
 When I run `nx build` I get:
```
Warning: Fell back to using 'fs' to identify web/apps/navigator/src/app/dashboard/transformations/edit/EditTransformationForm.tsx as deleted. Please open an 
issue at https://github.com/nrwl/nx so we can investigate.
```

**Comment by scorsi** [comment]
To reproduce the bug:
```
$> touch some-file
$> git add some-file
$> rm some-file
$> nx build some-app
Warning: Fell back to using 'fs' to identify some-file as deleted. Please open an issue at https://github.com/nrwl/nx so we can investigate.
```
Now you have that boring message :) 
To this that simply `git add some-file`

**Comment by bekos** [comment]
Is your Nx repo at the root of your git?

**Comment by tsinghammer** [comment]
No, it is one subdirectory below the git root. Could this cause the issue?

**Comment by scorsi** [comment]
Nerver mind where, everywhere in your repository / nx project. 
Did you tried the sets of commands above  ?

**Comment by bekos** [comment]
@scorsi I was only able to see it happening only if not from root 🤔 Can you try to create a new workspace and guide me through the steps to follow in a new/empty workspace plz?

**Comment by scorsi** [comment]
@bekos will look at it tomorow with a reproduction repo if I can reproduce it

**Comment by bekos** [comment]
@tsinghammer I know what is causing it in your case. I will try to fix this soon.

**Comment by tsinghammer** [comment]
Cool, thanks!
I must admit I did not expect a reaction that soon.
