### ISSUE TITLE
Enforce module boundaries rule doesn't work on Windows

### ISSUE THREAD

**Issue by trogowski** [nrwl/nx#5115]
On Windows circular dependencies errors are not reported. Looks like the ESLint rule cannot properly match module paths to libraries. 

## Current Behavior
Log from Windows:
```
C:\dev\project>rm -rf node_modules\.cache && nx lint error-handler --skip-nx-cache

> nx run error-handler:lint 

Linting "error-handler"...


All files pass linting.
```

## Expected Behavior
Log from WSL2
```
tim@<redacted>:~/project$ rm -rf node_modules/.cache/ &&  nx lint error-handler --skip-nx-cache

> nx run error-handler:lint 

Linting "error-handler"...

/home/tim/project/libs/error-handler/src/lib/error-handler.module.ts
  2:1  warning  Circular dependency between "error-handler" and "user-identification" detected: error-handler -> user-identification -> core-core -> gui-app -> error-handler  @nrwl/nx/enforce-module-boundaries

/home/tim/project/libs/error-handler/src/lib/handlers/global-error/global-error.handler.ts
  2:1  warning  Circular dependency between "error-handler" and "core-core" detected: error-handler -> core-core -> gui-app -> error-handler                                   @nrwl/nx/enforce-module-boundaries
  9:1  warning  Circular dependency between "error-handler" and "user-identification" detected: error-handler -> user-identification -> core-core -> gui-app -> error-handler  @nrwl/nx/enforce-module-boundaries

/home/tim/project/libs/error-handler/src/lib/models/log-request.model.ts
  1:1  warning  Circular dependency between "error-handler" and "core-core" detected: error-handler -> core-core -> gui-app -> error-handler  @nrwl/nx/enforce-module-boundaries

/home/tim/project/libs/error-handler/src/lib/services/logs-aggregator/logs-aggregator.service.ts
  5:1  warning  Circular dependency between "error-handler" and "core-core" detected: error-handler -> core-core -> gui-app -> error-handler  @nrwl/nx/enforce-module-boundaries

/home/tim/project/libs/error-handler/src/lib/services/remote-logger/remote-logger.service.ts
  6:1  warning  Circular dependency between "error-handler" and "core-core" detected: error-handler -> core-core -> gui-app -> error-handler  @nrwl/nx/enforce-module-boundaries

✖ 6 problems (0 errors, 6 warnings)

Lint warnings found in the listed files.
```

## Steps to Reproduce
I'm observing this in an internal corporate repo that I cannot share. The issue itself looks pretty simple and probably is just a missed case in PRs that addressed similar issues: https://github.com/nrwl/nx/pull/2941, https://github.com/nrwl/nx/pull/3028. See investigation notes and possible fix below. If you think however that a minimal repro repository would still be useful then please let me know.

### Environment
  Node : 14.15.4
  OS   : win32 x64
  npm  : 6.14.10

  nx : Not Found
  @nrwl/angular : 11.5.1
  @nrwl/cli : 11.5.1
  @nrwl/cypress : 11.5.1
  @nrwl/devkit : 11.5.1
  @nrwl/eslint-plugin-nx : 11.5.1
  @nrwl/express : Not Found
  @nrwl/jest : 11.5.1
  @nrwl/linter : 11.5.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.5.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.5.1
  @nrwl/storybook : 11.5.1
  @nrwl/gatsby : Not Found
  typescript : 4.1.3

## Initial investigation

My investigation lead me to target-project-locator: https://github.com/nrwl/nx/blob/master/packages/workspace/src/core/target-project-locator.ts#L125. 
```typescript
  private findProjectOfResolvedModule(resolvedModule: string) {
    const importedProject = this.sortedWorkspaceProjects.find((p) => {
      return resolvedModule.startsWith(p.data.root);
    });

    return importedProject?.name;
  }
```
On Windows passed in resolvedModule parameter for some cases has "\\" as path separators but for others the path separator is already normalized to POSIX "/". The .startsWith check fails for this reason.
In my other setup - Ubuntu Linux (actually ubuntu on WSL2) no path normalization is required as all paths are already POSIX and so circular dependencies errors are properly reported. 

## Possible fix

A possible (but probably a bit naive?) solution would be to replace
```typescript
return resolvedModule.startsWith(p.data.root);
```
with
```typescript
return resolvedModule
  .replace(/\\/g, '/')
  .startsWith(p.data.root);
```

This intentionally narrows down the scope of change just to this one method. As mentioned in linked PRs (https://github.com/nrwl/nx/pull/3028#issuecomment-631571248) making changes higher up in the call stack may or may not lead to unintended consequences. Not sure to what degree this concern is relevant to TargeteProjectLocator and it's callers though.

If the fix described above is sufficient then I am willing to put up a PR for this. If not then we might need to do a little bit more digging to find out from where the unnormalized module paths are coming from and patch this up closer to the root cause. Do let me know how you would like to proceed with this issue, thanks in advance.

**Comment by FrozenPandaz** [comment]
Can you try the latest version please? This may have fixed the issue: https://github.com/nrwl/nx/commit/71d9f867623ec4a71ac5851f47f2b31a0d14111a

**Comment by trogowski** [comment]
Retested on 11.6.1. Works fine now. Thanks 👍
