### ISSUE TITLE
Example and documentation request related to the usage of webworker

### ISSUE THREAD

**Issue by ahnpnl** [nrwl/nx#5123]
## Description

I look on https://nx.dev/ to find documentation about CLI to generate webworker for a Nx workspace which has an Angular app but I couldn't find any information. Besides, I also look at https://github.com/nrwl/nx-examples to find something useful but I couldn't find anything either.

Hereby, I want to request to have update on documentation related to:

- How to generate/configure webworker in an Nx workspace
- How to structure webworker files in an Nx workspace and examples

These requests are not really specific to the case of Angular, but should be in a generic way that other frameworks like React can also use it.

## Motivation

Make it easier for users who want to use webworker in an Nx workspace

## Suggested Implementation

**N.A.**

## Alternate Implementations

**N.A.**

**Comment by localpcguy** [comment]
While our code is not open, we are using a web worker in one of our Angular projects and I am currently in the process of moving the repo over to an Nx workspace. Once I have it working, I could extrapolate what I did and put it in the docs.

Is there a specific spot this documentation should live? Maybe in the Angular examples?

**Comment by Lonli-Lokli** [comment]
@localpcguy did you have a chance to complete it?
My case is with react, but I think concept gonna be the same

**Comment by Coly010** [comment]
There has been no update on this for a while.
Thanks for raising it to our attention and it is something we'll consider when we try to improve our docs and examples. 

I'll close this issue for now.

**Comment by localpcguy** [comment]
My apologies - saw this notification when you closed it, but must of missed the previous ones. I'll comment here if I have a chance to do something, have been dealing with health issues in the family and all side stuff has been paused.

**Comment by Coly010** [comment]
@localpcguy hope all the best for you and your family
