### ISSUE TITLE
Error after running ng add on fresh CLI project

### ISSUE THREAD

**Issue by jeffbcross** [nrwl/nx#513]
* Mac
 * Node 9.11.1
 * Angular CLI version 6.0.3
 * Nx version 6.0.2

1. I created a new Angular CLI project: `ng new marbles`.
1. Then I added Nrwl schematics: `ng add @nrwl/schematics`. But got an error:

```bash
Mac-Pro:marble jeffbcross$ ng add @nrwl/schematics
Installing packages for tooling via npm.
+ @nrwl/schematics@6.0.2
added 51 packages in 9.151s
Installed packages for tooling via npm.
EISDIR: illegal operation on a directory, read
```

**Comment by ffriedl89** [comment]
Got exactly the same error on 
* Windows 10
* Node 8.11.2
* Angular CLI 6.0.3
* Nx version 6.0.2

**Comment by sanyashvets** [comment]
same error
```
Nx: 6.0.2
Angular CLI: 6.0.3
Node: 8.11.1
OS: linux x64 (Ubuntu 17.10)
Angular: 6.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
```

**Comment by xban1x** [comment]
Yup, same here.

Windows 10
Node 9.11.1
Angular CLI 6.0.3
Nx version 6.0.2

**Comment by agusdutra** [comment]
Hi @FrozenPandaz , I've been using Nx on some projects, but now I'm trying to add support for an existing project. 

I've been looking around the related issues but didn't found it was really fixed.
I'm not getting any error, but the workspace isn't created at all.

I watched this [video:](https://angularplaybook.com/courses/264974/lectures/4113784) and as it shows the command `ng add @nrwl/schematics` should update my file structure to handle de apps/app and apps/libs structure, but none of this happens.
 
Only this files are updated/created: 

```
CREATE jest.config.js (275 bytes)
UPDATE angular.json (3586 bytes)
UPDATE package.json (1562 bytes)
```

The steps to reproduce are the same as the original issue by @jeffbcross 
1. Create a new Angular CLI project:` ng new marbles.`
2. Add Nrwl schematics: `ng add @nrwl/schematics. `

**Expected**: an apps and libs structure to be created, the default app and e2e to be inside apps/, an nx.json file and other things.

**Result**: jest.config.ts is created, angular.json and package.json updated.

This happened to me with an existing project with `@angular/cli 7.2.0` and now with a new one with `8.0.1`.

If you execute those 2 commands and get the expected file structure, please let me know, I have no idea what I'm missing, but this command doesn't seem to be working at all.
