### ISSUE TITLE
Jest Test Reports are not creating

### ISSUE THREAD

**Issue by rupeshtiwari** [nrwl/nx#5140]
## Current Behavior
No test results are getting created while using JEST. 

## Expected Behavior
Test Results must create while using JEST

## Steps to Reproduce
Add script: `nx affected:test --ci` 

Here is the jest.config file
```json
module.exports = {
  reporters: [
    'default',
    [
      'jest-junit',
      {
        outputDirectory: 'test_results',
        outputName: 'jest-junit.xml',
        suiteName: 'Angular Inventions Tests',
      },
    ],
  ],
  projects: [
    '<rootDir>/apps/example',
    '<rootDir>/libs/pubsub',
    '<rootDir>/libs/utils',
  ],
};

```
 

### Failure Logs
Test run okay however nothing is created no test reports.

### Environment
Windows. 

However, When I just run `jest --ci` then reports are created. I wanted to use NX to run test with reports. Any help on this? 
Am I missing something ?

**Comment by campions** [comment]
Have you tried to add the `--codeCoverage` flag in the running command?

**Comment by StickNitro** [comment]
I am getting the same issue with @nrwl/jest @13.4.3

relevant section from jest.config.js

  reporters: [
    'default',
    [
      'jest-junit',
      {
        suiteName: 'cdo-connect-pim Jest Tests',
        outputDirectory: '../../coverage/apps/cdo-connect-pim/junit',
        ancestorSeparator: ' > ',
        usePathForSuiteName: true,
        outputName: 'TESTS.xml'
      }
    ],
    'jest-progress-bar-reporter'
  ]
relevant parts from package.json

  "scripts": {
    "test": "nx test"
  },
  "devDependencies": {
    "@nrwl/jest": "13.4.3",
    "jest": "27.2.3",
    "jest-junit": "^13.0.0"
  }
and the relevant section from angular.json

        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": ["coverage/apps/cdo-connect-pim"],
          "options": {
            "jestConfig": "apps/cdo-connect-pim/jest.config.js",
            "passWithNoTests": true
          }
        }
Running npx jest --collectCoverage works and generates the jest-junit output

**Comment by barbados-clemens** [comment]
@StickNitro  or @rupeshtiwari does running with the `--coverage` not create a coverage report as suggested? or are you looking for something else?
