### ISSUE TITLE
Jest - import @testing-library/jest-dom

### ISSUE THREAD

**Issue by integral-llc** [nrwl/nx#5148]
## Current Behavior
Does not properly import types from `jest-dom` library

## Expected Behavior
Should import types and have `.toBeInDocument` available in unit tests

## Steps to Reproduce
Create a react application and try to write in unit tests 
`expect(container.getByText(/Label1/i)).toBeInDocument();`
I did add into my project `jest.config.js` a line to setup `jest-dom` 
```
    setupFilesAfterEnv: [
        "<rootDir>/jest-setup.js"
    ]

```
where `jest-setup.js` is
`require("@testing-library/jest-dom");`

however `toBeInDocument` is still no available, getting this error
```
TypeError: expect(...).toBeInDocument is not a function
```

### Environment
  Node : 15.8.0
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.4.0
  @nrwl/cypress : 11.4.0
  @nrwl/devkit : 11.4.0
  @nrwl/eslint-plugin-nx : 11.4.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.4.0
  @nrwl/linter : 11.4.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.4.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.4.0
  @nrwl/web : 11.4.0
  @nrwl/workspace : 11.4.0
  typescript : 4.0.7

**Comment by puku0x** [comment]
Do you mean `.toBeInTheDocument()` ? It seems work for me.

![image](https://user-images.githubusercontent.com/2607019/112742897-adb01d80-8fcd-11eb-8cb3-ae2d0f362e06.png)
![image](https://user-images.githubusercontent.com/2607019/112742950-08497980-8fce-11eb-8f7d-b8b6dc1d0709.png)

- `apps/client-mobile/src/test-setup.ts`

```js
// jest-dom adds custom jest matchers for asserting on DOM nodes.
// allows you to do things like:
// expect(element).toHaveTextContent(/react/i)
// learn more: https://github.com/testing-library/jest-dom
import '@testing-library/jest-dom';
```

- `apps/client-mobile/jest.config.js`

```js
module.exports = {
  displayName: 'client-mobile',
  preset: '../../jest.preset.js',
  setupFilesAfterEnv: ['<rootDir>/src/test-setup.ts'],
  transform: {
    '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': '@nrwl/react/plugins/jest',
    '^.+\\.[tj]sx?$': 'babel-jest',
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  coverageDirectory: '../../coverage/apps/client-mobile',
};
```

- `apps/client-mobile/tsconfig.spec.json`

```js
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "module": "commonjs",
    "types": ["jest", "node"]
  },
  "include": [
    "src/test-setup.ts",
    "**/*.spec.ts",
    "**/*.spec.tsx",
    "**/*.spec.js",
    "**/*.spec.jsx",
    "**/*.d.ts"
  ],
  "files": [
    "../../node_modules/@nrwl/react/typings/cssmodule.d.ts",
    "../../node_modules/@nrwl/react/typings/image.d.ts"
  ]
}
```

**Comment by integral-llc** [comment]
thx!
went over your changes, and that fixed the jest execution itself, however nor VS Code, nor WebStorm would see the `toBeInTheDocument`
![image](https://user-images.githubusercontent.com/1841073/112756549-5600ba80-8fab-11eb-8f4c-4d4eca1eba36.png)
Ideas?
