### ISSUE TITLE
Remove @types/react-redux

### ISSUE THREAD

**Issue by puku0x** [nrwl/nx#5149]
## Description
`react-redux` installs `@types/react-redux` automatically now.
https://github.com/reduxjs/react-redux/releases/tag/v7.2.3

## Motivation

To simplify dependency management related to `react-redux`.

## Suggested Implementation

Remove `@types/react-redux` from `devDependencies`

**Comment by puku0x** [comment]
Maybe after #5131 ?

**Comment by jaysoo** [comment]
Yeah, let's get that version update merged in, and then we can remove it completely + a migration.
