### ISSUE TITLE
Generator @nrwl/react:stories doesn't see libraries

### ISSUE THREAD

**Issue by yieldinov** [nrwl/nx#5151]
## Current Behavior
Only applications available 
<img width="920" alt="Screenshot 2021-03-28 at 12 21 26" src="https://user-images.githubusercontent.com/929834/112763091-4b045500-8fc0-11eb-8ef9-87ca2d933616.png">

## Expected Behavior
Applications and libraries should be possible to specify (now even thru CLI I can't target library)
<img width="922" alt="Screenshot 2021-03-28 at 12 21 36" src="https://user-images.githubusercontent.com/929834/112763131-640d0600-8fc0-11eb-8748-afe8177f5286.png">

## Steps to Reproduce
start new react workspace
add storybook plugin
try to execute `nx generate @nrwl/react:stories --project=<library here>` or through the GUI

### Failure Logs
`Cannot read property 'sourceRoot' of undefined`

### Environment
macOS

**Comment by puku0x** [comment]
It works on my machine. https://github.com/puku0x/nx-issue-5151

You may need to restart VS Code after generating a library.

![image](https://user-images.githubusercontent.com/2607019/112770124-121bbd00-9060-11eb-9524-7a2cb66084bc.png)
![image](https://user-images.githubusercontent.com/2607019/112770349-5e1b3180-9061-11eb-884c-9e615fc131c1.png)

```
% npx nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.15.4
  OS   : darwin x64
  npm  : 6.14.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.5.2
  @nrwl/cypress : 11.5.2
  @nrwl/devkit : 11.5.2
  @nrwl/eslint-plugin-nx : 11.5.2
  @nrwl/express : Not Found
  @nrwl/jest : 11.5.2
  @nrwl/linter : 11.5.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.5.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.5.2
  @nrwl/web : 11.5.2
  @nrwl/workspace : 11.5.2
  @nrwl/storybook : 11.5.2
  @nrwl/gatsby : Not Found
  typescript : 4.0.7
```

**Comment by yieldinov** [comment]
Restarting VS Code helped. Thanks

Side questions: it's not currently possible to generate stories for all components under some folder, right?

**Comment by puku0x** [comment]
It's possible. `@nrwl/react:stories` does generate stories for all components in a project (in `apps/*` or `libs/*`).

**Comment by lodisy** [comment]
Possible to change the default story directory? 

For example, change the default `lib` to `components`, so when run `nx g @nrwl/react:component ...` to generate components. Changing the `rootMain.stories.push...` in `main.js` seems not working.

**Comment by lodisy** [comment]
Possible to change the default story directory? 

For example, change the default directory `lib` to `components` in `workspace.json`, 

```
    "generators": {
        "@nrwl/react": {
            "application": {
                "babel": true
            },
            "component": {
                "export": true,
                "project": "ui",
                "style": "none",
                "pascalCaseFiles": true,
                "directory": "./components/"
            }
        },
```

so when run `nx g @nrwl/react:component ...`, it generates components. But there is no directory config for stories, changing the `rootMain.stories.push...` in `main.js` seems not working.

**Comment by nathanjisaac** [comment]
> It's possible. `@nrwl/react:stories` does generate stories for all components in a project (in `apps/*` or `libs/*`).

@puku0x Do you know if it works for `lib` components in sub folders? 

```
workspace/libs/example/src/lib
    /component/component.tsx
    /component/component.stories.tsx <-- created
    /directory/other-component/other-component.tsx
    /directory/other-component/other-component.stories.tsx <-- not created
```

It seems to work for non-nested lib components.

**Comment by daton89** [comment]
the stories generator is not able to find components which are not using default exports, would it be possible to make it work for named exports as well?
