### ISSUE TITLE
Warning: Fell back to using 'fs' to identify git-root/workspace/angular.json as deleted. Please open an issue at https://github.com/nrwl/nx so we can investigate.

### ISSUE THREAD

**Issue by SnakeSVx** [nrwl/nx#5155]
## Current Behavior

For every file that gets modified/added in the workspace I'm getting the above warning that it is detecting the files to have been removed using the FS, even though they still exist and only received some changes in them.

## Expected Behavior
No warnings when only modifying or adding files.
Started happening after upgrading from nx 11.2.12 to 11.5.2
(note: adding the modifition to git staging doesn't resolve the issue)

Before this version this warning only occured when removing a file that wasn't removed using git yet, wand got resolved by removing the file from git as well. 

## Steps to Reproduce

Modify any file in the workspace that is used by NX. 
- .eslintrc
- angular component folder (css, html, ts, spec.ts)
- angular.json 

### Environment

- Ubuntu 20.04.2 LTS
- NX 11.5.2
- git version 2.25.1

**Comment by SnakeSVx** [comment]
It also seems like all the command's are using some cached values somewhere.

After fixing linting errors in files and executing the lint command again the out remains the same as before fixing the linting errors, but added to the output are warnings with errors like the title mentions for all the files having linting fixes.

**Comment by bekos** [comment]
@SnakeSVx can you try 11.6.0-rc.0? there was an issue with projects not being at the Git root, but has already been fixed. Is this your case also?
