### ISSUE TITLE
`babelConfig` is removed from @nrwl/web but still exists in generated react libs

### ISSUE THREAD

**Issue by alirezamirian** [nrwl/nx#5156]
## Current Behavior

when a new library is generated with @nrwl/react, `babelConfig` field exists in the builder configuration: https://github.com/nrwl/nx/blob/master/packages/react/src/generators/library/library.ts#L199

## Expected Behavior

It should be in sync with @nrwl/web and should not have that configuration

**Comment by CWSites** [comment]
@alirezamirian I'm not seeing any `babelConfig` fields on the file you linked?

**Comment by alirezamirian** [comment]
Yes, it seems it's already removed here:
https://github.com/nrwl/nx/commit/c84bbb3c93fed7d6fa8853583b3e2c55a3b3c76a#diff-6672620698a23cea33de9297cc99269efb421f6dfeaf8ff7f7176aaccc6c6487
