### ISSUE TITLE
Warning:Fellback to using 'fs' to identify tsconfig.base.json as deleted. Please open an issue ...

### ISSUE THREAD

**Issue by jlabaj** [nrwl/nx#5163]
Angular 11.2.5 nrwl 11.5.2

![image](https://user-images.githubusercontent.com/5179937/112956988-4ca95680-9141-11eb-9dae-5ee302127d63.png)

**Comment by bekos** [comment]
@jlabaj this has already been fixed at 11.6.0. Can you upgrade?

**Comment by jlabaj** [comment]
@bekos yup, fixed, thanks.

**Comment by jlabaj** [comment]
@bekos yup, fixed, thanks.
