### ISSUE TITLE
Missing Dependencies in @nrwl/workspace e.g. webpack-dev-server

### ISSUE THREAD

**Issue by KeKs0r** [nrwl/nx#5169]
This is something I discovered while upgrading to 11.6. I am not sure why its only happening now.

There are dependencies used within `@nrwl/workspace` that are not listed in its dependencies. This sometimes works, if those dependencies are hoisted, but if they are not, the dependency is not found from within `@nrwl/workspace`

## Current Behavior

When running webpack related commands the utility `@nrwl/workspace/src/utilities/run-webpack.js` is used. Which is using the `webpack-dev-server`. This leads to following error

```
> nx run graph-api:build 
Cannot find module 'webpack-dev-server'
Require stack:
- /Users/marc/Workspace/monolaser/node_modules/@nrwl/workspace/src/utilities/run-webpack.js
- /Users/marc/Workspace/monolaser/node_modules/@nrwl/node/src/executors/build/build.impl.js
- /Users/marc/Workspace/monolaser/node_modules/@nrwl/tao/src/shared/workspace.js
- /Users/marc/Workspace/monolaser/node_modules/@nrwl/tao/src/commands/run.js
- /Users/marc/Workspace/monolaser/node_modules/@nrwl/tao/index.js
- /Users/marc/Workspace/monolaser/node_modules/@nrwl/cli/lib/run-cli.js
```

## Expected Behavior
The command should run sucessfully

## Steps to Reproduce
I think most of the time, this issue does not occur because the `webpack-dev-server` is hoisted from the other `@nrwl/node` or `@nrwl/web` dependencies.

### Failure Logs
```
=> Found "webpack-dev-server@3.11.0"
info Reasons this module exists
   - "@nrwl#node" depends on it
   - Hoisted from "@nrwl#node#webpack-dev-server"
   - Hoisted from "@nrwl#web#webpack-dev-server"
 ```

### Environment
```
  Node : 12.16.1
  OS   : darwin x64
  yarn : 1.22.5
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.6.0
  @nrwl/cypress : 11.6.0
  @nrwl/devkit : 11.6.0
  @nrwl/eslint-plugin-nx : 11.6.0
  @nrwl/express : 11.6.0
  @nrwl/jest : 11.6.0
  @nrwl/linter : 11.6.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.6.0
  @nrwl/react : 11.6.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.6.0
  @nrwl/web : 11.6.0
  @nrwl/workspace : 11.6.0
  @nrwl/storybook : 11.6.0
  @nrwl/gatsby : Not Found
  typescript : 4.2.3
```

**Comment by FrozenPandaz** [comment]
Those should be brought in by `@nrwl/web` and `@nrwl/node` respectively, not `@nrwl/workspace`. It doesn't seem like you have any mismatched dependencies either. Is it possible for you to provide a repo exhibiting the issue to help us debug?

**Comment by dcastil** [comment]
I think `@nrwl/workspace` shouldn't rely on `@nrwl/web` or `@nrwl/node` making the dependency available. This can break easily if other packages depend on another version of `webpack-dev-server` and the package manager decides to hoist the other version. This would result in the version `@nrwl/workspace` needs being placed into the node_modules of `@nrwl/web` and `@nrwl/node`, making it unavailable to `@nrwl/workspace`.

**Comment by dcastil** [comment]
I made a simple repro of the dependency tree in my comment above here: https://github.com/dcastil/nrwl-dep-error-test

**Comment by KeKs0r** [comment]
There are apparently also other dependencies that are not included in other packages:
```
15:17:39.922 | Cannot find module '@angular-devkit/architect'
-- | --
15:17:39.922 | Require stack:
15:17:39.922 | - /vercel/workpath1/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
15:17:39.923 | - /vercel/workpath1/node_modules/@nrwl/tao/src/commands/run.js
15:17:39.923 | - /vercel/workpath1/node_modules/@nrwl/tao/index.js
15:17:39.923 | - /vercel/workpath1/node_modules/@nrwl/cli/lib/run-cli.js
```

But when checking which other packages depend on it, I am getting this:
```
yarn why @angular-devkit/architect
yarn why v1.22.5
[1/4] 🤔  Why do we have the module "@angular-devkit/architect"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
error We couldn't find a match!
```
