### ISSUE TITLE
Apps Failing to Build in Docker Containers

### ISSUE THREAD

**Issue by mmcxii** [nrwl/nx#5175]
I have been building my apps into Docker containers for several months without issue, and it worked as recently as yesterday, however today when I attempted to rebuild an image it failed. I have retried each different app and none of them can successfully build any more.

## Current Behavior
Any build commands run within a Dockerfile fail to build.

## Expected Behavior
Apps should be able to be compiled from source code within a Dockerfile.

## Steps to Reproduce
Create a Dockerfile to build the app

```ignore
# .dockerignore
node_modules
dist
```

```dockerfile

# Dockerfile
FROM node:latest

WORKDIR /app

COPY . ./

RUN yarn install

RUN yarn nx:build myapp --prod

EXPOSE 4000

CMD [ "node", "dist/apps/myapp/main.js" ]
```

This will fail at `yarn nx:build myapp --prod` every time (it will also fail without the --prod flag), and no terminal output is present on the Nx Cloud details page.

The app build on my machine (not in the container) every time without fail.

### Failure Logs
No logs are generated from the Docker build output beyond `error Command failed with exit code 1.`.

### Environment
```
  Node : 14.15.4
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.6.0
  @nrwl/cypress : 11.6.0
  @nrwl/devkit : 11.6.0
  @nrwl/eslint-plugin-nx : 11.6.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.6.0
  @nrwl/linter : 11.6.0
  @nrwl/nest : 11.6.0
  @nrwl/next : Not Found
  @nrwl/node : 11.6.0
  @nrwl/react : 11.6.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.6.0
  @nrwl/web : 11.6.0
  @nrwl/workspace : 11.6.0
  @nrwl/storybook : 11.6.0
  @nrwl/gatsby : Not Found
  typescript : 4.2.3
```

**Comment by FrozenPandaz** [comment]
Hm, I am not able to reproduce the issue. 

Can you try adding `--verbose` after the `yarn nx:build` command to see if you get more output please?

**Comment by mmcxii** [comment]
I added the --verbose flag but no additional output was generated.

However, I spun up a fresh Nx repo to try and isolate the problem but the Docker image builds just fine in the new repo. There must be something else I've done wrong.

I'll close this and try to figure it out, if I come up with a solution I'll post it here in case someone else footguns themselves in the future.

**Comment by danr-za** [comment]
@mmcxii I am having the same issue right now with v12.6.5
In my case, only prod build fails for some reason.
Using Webpack 5.

Any idea or a conclusion you got to?
