### ISSUE TITLE
`nx migrate latest` outputs illegible text when using a light color theme

### ISSUE THREAD

**Issue by andreavaccari** [nrwl/nx#5178]
## Current Behavior
The `nx migrate latest` command sets the foreground ansi color of some output lines to a light color without setting the background color. If the terminal is using a light theme, this results in a light color on a light background that is hard to read.

## Expected Behavior
When setting the foreground ansi color, the background should be set to a contrasting color.

## Steps to Reproduce
Run any command in a terminal, and toggle between light and dark theme.

Dark theme:
![d-theme](https://user-images.githubusercontent.com/660980/113086108-ec65f380-91d8-11eb-8d45-d9a2300506e8.png)

Light theme:
![l-theme](https://user-images.githubusercontent.com/660980/113086113-f12aa780-91d8-11eb-8829-090b619141bd.png)

### Environment
I'm using Alacritty and 0.7.2 and tmux 3.1c

**Comment by spiralx** [comment]
Also getting this issue but only when running `nx test` e.g.:

![image](https://user-images.githubusercontent.com/2296633/125267718-fda5bc80-e2fe-11eb-8cce-34db18af25ca.png)

Compared to if I use `nx test --no-colors` instead:

![image](https://user-images.githubusercontent.com/2296633/125269647-cfc17780-e300-11eb-8989-7a3636dbbdc7.png)

Everything else is fine, including `nx test --help`:

![image](https://user-images.githubusercontent.com/2296633/125269866-05fef700-e301-11eb-946c-bf3ef7555c46.png)
