### ISSUE TITLE
eslint does not respect prettier config in libs

### ISSUE THREAD

**Issue by Phhansen** [nrwl/nx#5182]
## Current Behavior
When using a `.prettierrc` like the following:
```json
{
  "singleQuotes": false
}
```
alongside the `.eslintrc.json` with extends:
```json
{
  "root": true,
  "ignorePatterns": ["**/*"],
  "plugins": ["@nrwl/nx"],
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],
      "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/eslint-recommended",
        "plugin:@typescript-eslint/recommended",
        "prettier"
      ],
      "rules": {
        "@nrwl/nx/enforce-module-boundaries": [
          "error",
          {
            "enforceBuildableLibDependency": true,
            "allow": [],
            "depConstraints": [
              { "sourceTag": "*", "onlyDependOnLibsWithTags": ["*"] }
            ]
          }
        ]
      }
    },
    {
      "files": ["*.ts", "*.tsx"],
      "extends": ["plugin:@nrwl/nx/typescript"],
      "rules": {}
    },
    {
      "files": ["*.js", "*.jsx"],
      "extends": ["plugin:@nrwl/nx/javascript"],
      "rules": {}
    }
  ]
}

```
`libs` (angular) added with nx schematics will show eslint error: "Strings must use singlequote"

## Expected Behavior
I would expect eslint configs in created `libs` to inherit the prettier config extends from the root

## Steps to Reproduce
I made an example repo here https://github.com/Phhansen/nxlint.

What I did was:

1. create new workspace
```
npx create-nx-workspace --preset=angular
```

2. choose eslint as the linter
3. set `"singleQuote": false` in the `.prettierrc` root config file
4. create new lib `shared-ui-buttons` 

### Environment
```
Node : 14.9.0
OS   : darwin x64
npm  : 6.14.8

nx : Not Found
@nrwl/angular : 11.6.0
@nrwl/cli : 11.6.0
@nrwl/cypress : 11.6.0
@nrwl/devkit : 11.6.0
@nrwl/eslint-plugin-nx : 11.6.0
@nrwl/express : Not Found
@nrwl/jest : 11.6.0
@nrwl/linter : 11.6.0
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/react : Not Found
@nrwl/schematics : Not Found
@nrwl/tao : 11.6.0
@nrwl/web : Not Found
@nrwl/workspace : 11.6.0
@nrwl/storybook : Not Found
@nrwl/gatsby : Not Found
typescript : 4.0.7
```

**Comment by EpicHigh** [comment]
Sorry, I think it's totally different between your eslint config and prettier config. I think you should align your eslint config with your prettier config.

`.prettierrc`

```json
{
  "singleQuote": true,
  "endOfLine": "auto",
  "semi": false
}

```


`.eslintrc.json`



```json
{
  "root": true,
  "ignorePatterns": ["**/*"],
  "plugins": ["@nrwl/nx"],
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],
      "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/eslint-recommended",
        "plugin:@typescript-eslint/recommended",
        "prettier"
      ],
      "rules": {
        "@nrwl/nx/enforce-module-boundaries": [
          "error",
          {
            "enforceBuildableLibDependency": true,
            "allow": [],
            "depConstraints": [
              { "sourceTag": "*", "onlyDependOnLibsWithTags": ["*"] }
            ]
          }
        ]
      }
    },
    {
      "files": ["*.ts", "*.tsx"],
      "extends": ["plugin:@nrwl/nx/typescript"],
      "rules": {
       "prettier/prettier": [
          "error",
          {
            "singleQuote": true,
            "endOfLine": "auto",
            "semi": false
          }
        ]
      }
    },
    {
      "files": ["*.js", "*.jsx"],
      "extends": ["plugin:@nrwl/nx/javascript"],
      "rules": {}
    }
  ]
}

```

**Comment by Phhansen** [comment]
I hadn't thought of doing anything like that. I was under the impression that the `extends: ["prettier"]` would disable the code style-related rules from eslint.

I'll give it a go later today.  If it isn't actually a bug I'm fine with closing it, there is just no documentation anywhere, and since prettier is also part of nx, I would assume they'd just work out of the box.

**Comment by JamesHenry** [comment]
@Phhansen which version of angular-eslint do you have installed please?

If the answer is v1.0.0 please upgrade to any later version and the issue should go away. I'm afraid I messed up the publishing of 1.0.0 and the recommended config contained some stylistic rules such as `quotes`.

In this case, that wins out over your extends prettier because it is being applied in your project config via `@nrwl/nx/angular`(which is higher specificity than your root config based on cascading configs)

**Comment by JamesHenry** [comment]
Here is that update as a PR: https://github.com/nrwl/nx/pull/5233
