### ISSUE TITLE
Angular schematics always use the default project

### ISSUE THREAD

**Issue by itayod** [nrwl/nx#5183]
## Current Behavior
When generating a component under a project that is not the default project the project setting (e.g. the component's prefix) used to generate the component are taken from the default one.

## Expected Behavior
The schematics should recognize the correct project.

Worth mention it used to work perfectly in version 10.

## Steps to Reproduce

* Create a new workspace with a default app called "test".
* Create another new app "abc" `$ nx generate @nrwl/angular:app abc`.
* Change the prefix in `angular.json` to "abc".
* Generate a component under abc app
* The new component's prefix should be "abc".

### Environment
```
>  NX  Report complete - copy this into the issue template

  Node : 14.15.0
  OS   : win32 x64
  npm  : 6.14.8

  nx : Not Found
  @nrwl/angular : 11.6.0
  @nrwl/cli : 11.6.0
  @nrwl/cypress : 11.6.0
  @nrwl/devkit : 11.6.0
  @nrwl/eslint-plugin-nx : 11.6.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.6.0
  @nrwl/linter : 11.6.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.6.0
  @nrwl/web : Not Found
  @nrwl/workspace : 11.6.0
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.0.5

```

**Comment by FrozenPandaz** [comment]
Sorry, I can't seem to be able to reproduce the issue.

The prefix is picked up properly for me. Can you reproduce on `nx-examples`? Please provide a repo to help reproduce the issue.

<details>
jason@pop-os ~/p/nx-examples (master)> nx g @nrwl/angular:app new-app --prefix new-prefix
? Which stylesheet format would you like to use? CSS
? Would you like to configure routing for this application? No
✔ Packages installed successfully.
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
$ ngcc --properties es2015 browser module main && node decorate-angular-cli.js

>  NX  Angular CLI has been decorated to enable computation caching.

Done in 1.78s.
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
$ ngcc --properties es2015 browser module main && node decorate-angular-cli.js

>  NX  Angular CLI has been decorated to enable computation caching.

Done in 1.77s.
CREATE apps/new-app/tsconfig.editor.json
CREATE apps/new-app/tsconfig.json
CREATE apps/new-app/src/favicon.ico
CREATE apps/new-app/.browserslistrc
CREATE apps/new-app/tsconfig.app.json
CREATE apps/new-app/src/index.html
CREATE apps/new-app/src/main.ts
CREATE apps/new-app/src/polyfills.ts
CREATE apps/new-app/src/styles.css
CREATE apps/new-app/src/assets/.gitkeep
CREATE apps/new-app/src/environments/environment.prod.ts
CREATE apps/new-app/src/environments/environment.ts
CREATE apps/new-app/src/app/app.module.ts
CREATE apps/new-app/src/app/app.component.css
CREATE apps/new-app/src/app/app.component.html
CREATE apps/new-app/src/app/app.component.spec.ts
CREATE apps/new-app/src/app/app.component.ts
CREATE .eslintrc.json
CREATE apps/new-app/.eslintrc.json
CREATE apps/new-app/jest.config.js
CREATE apps/new-app/src/test-setup.ts
CREATE apps/new-app/tsconfig.spec.json
CREATE apps/new-app-e2e/cypress.json
CREATE apps/new-app-e2e/src/fixtures/example.json
CREATE apps/new-app-e2e/src/integration/app.spec.ts
CREATE apps/new-app-e2e/src/plugins/index.js
CREATE apps/new-app-e2e/src/support/app.po.ts
CREATE apps/new-app-e2e/src/support/commands.ts
CREATE apps/new-app-e2e/src/support/index.ts
CREATE apps/new-app-e2e/tsconfig.e2e.json
CREATE apps/new-app-e2e/tsconfig.json
CREATE apps/new-app-e2e/.eslintrc.json
UPDATE angular.json
UPDATE package.json
UPDATE nx.json
UPDATE .vscode/extensions.json
UPDATE jest.config.js
jason@pop-os ~/p/nx-examples (master)> cd apps/new-app/src/app/
jason@pop-os ~/p/n/a/n/s/app (master)> nx g @nrwl/angular:c button
CREATE apps/new-app/src/app/button/button.component.css
CREATE apps/new-app/src/app/button/button.component.html
CREATE apps/new-app/src/app/button/button.component.spec.ts
CREATE apps/new-app/src/app/button/button.component.ts
UPDATE apps/new-app/src/app/app.module.ts
jason@pop-os ~/p/n/a/n/s/app (master)> cat button/button.component.ts | grep selector
  selector: 'new-prefix-button',
jason@pop-os ~/p/n/a/n/s/app (master)> 

</details>

**Comment by itayod** [comment]
@FrozenPandaz 
there you go:
https://github.com/itayod/nx-prefix-issue

**Comment by itayod** [comment]
@FrozenPandaz have you got the time to see my reproduction? did you manage to reproduce it?

Please let me know if you need anything further.

**Comment by itayod** [comment]
@FrozenPandaz any news?

**Comment by itayod** [comment]
@FrozenPandaz ping

**Comment by FrozenPandaz** [comment]
@itayod I pulled down the repo you provided and did the following:

```sh
npm i
nx g @nrwl/angular:app abc
```

Then, I changed the `prefix` property under the `abc` project.

And then I did the following:

```sh
cd apps/abc/src/app
nx g c button
```

`apps/abc/src/app/button/button.component.ts` has the following contents for me:
```ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'abc-button',
  templateUrl: './button.component.html',
  styleUrls: ['./button.component.css']
})
export class ButtonComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

```

Note the selector is properly `abc`.

**Comment by itayod** [comment]
@FrozenPandaz I am not sure how it reproduces on my computer constantly...

Maybe it's related to the os? I am using Windows...

Also, if I downgrade the version of `@nrwl/workspace` and `@nrwl/cli` to `10.4.15` then it works as expected with the prefix and everything...

Did some quick investigating of the problem and it seems that the `option.project` in `@schematics/angular/component` is the wrong one on the new version but the correct one in version `10.4.15`.

**Comment by Coly010** [comment]
Hey @itayod !

Can you check if this is still occurring for you in the latest version of Nx?

**Comment by itayod** [comment]
@Coly010 still is... worth to remention that it works perfectly with version 10, so it must be something that has changed between those versions.

**Comment by Coly010** [comment]
@itayod I can't reproduce this either. I wonder if it's a Windows-specific issue.
