### ISSUE TITLE
convert-tslint-to-eslint on an app

### ISSUE THREAD

**Issue by markgoho** [nrwl/nx#5189]
## Current Behavior
Ran the generator (via the Nx extension) on an app (`dashboard`) but the generator also updated eslint config under `dashboard-e2e`

## Expected Behavior
I executed this generator on a number of libs in the project and each time, the only files that changed were specifically for that lib

## Steps to Reproduce
Open extension, choose the convert-tslint-to-eslint generator, choose an app (not the `-e2e` version, just the base app) and run the generator

### Terminal Output
``` bash
DELETE apps/dashboard/tslint.json
CREATE apps/dashboard/.eslintrc.json
UPDATE angular.json
UPDATE .eslintrc.json
CREATE apps/dashboard-e2e/.eslintrc.json
DELETE apps/dashboard-e2e/tslint.json
```

### Environment

``` bash
Node : 12.18.3
  OS   : win32 x64
  npm  : 6.14.11

  nx : Not Found
  @nrwl/angular : 11.6.0
  @nrwl/cli : 11.6.0
  @nrwl/cypress : 11.6.0
  @nrwl/devkit : 11.6.0
  @nrwl/eslint-plugin-nx : 11.6.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.6.0
  @nrwl/linter : 11.6.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.6.0
  @nrwl/web : Not Found
  @nrwl/workspace : 11.6.0
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.0.5
```

If this behavior is expected, perhaps add a comment in the extension letting folks know that if it's an app instead of a lib, it'll do both base app and e2e app at the same time. I don't think anything bad happened here, it was just unexpected.

**Comment by JamesHenry** [comment]
Thanks @markgoho, it is expected, I'll add a note to the schema description that if we find a corresponding cypress e2e project for an angular app, we automatically attempt to convert that too.
