### ISSUE TITLE
Error for app generation with inline-template option

### ISSUE THREAD

**Issue by JanUnld** [nrwl/nx#519]
Hey,

I recently updated my toolbelt to the latest version of **@nrwl/nx** and I wanted to thank you guys alot for the great work you are putting into this project to make every (ng) developers life much simpler!

Anyway, I came up with a nasty little bug while I was trying to generate an application using the `--inline-template` (`-t`) option. Unfortunately the cli gave me the following output:

```sh
$ ng g app foo-app --inline-template
Path "/apps/foo-app/src/app/app.component.html" does not exist.
```

Guess this isn't a big deal but I wanted to let you guys know so you can investigate into this as soon as you got the time 😉.

**My local environment as is:**

As i mentioned I'm using the latest version of **nx** (`v6.0.2`) with the following **angular cli** layer...

```sh
Angular CLI: 6.0.1
Node: 8.11.1
OS: win32 x64
Angular: 6.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.3
@angular-devkit/build-angular      0.6.3
@angular-devkit/build-ng-packagr   0.6.3
@angular-devkit/build-optimizer    0.6.3
@angular-devkit/core               0.6.3
@angular-devkit/schematics         0.6.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.3
@schematics/angular                0.6.1
@schematics/update                 0.6.1
ng-packagr                         3.0.0-rc.5
rxjs                               6.0.0
typescript                         2.7.2
webpack                            4.8.3
```

**Comment by jschwarty** [comment]
Confirmed this by running (-t for inline template and -d for dry run)
```
ng g app foo-app -t -d
```

Might be [this method](https://github.com/nrwl/nx/blob/master/packages/schematics/src/collection/application/index.ts#L99) that is the culprit.
