### ISSUE TITLE
Publish with Yarn Berry

### ISSUE THREAD

**Issue by Smbkilla** [nrwl/nx#5197]
## Current Behavior
After building libraries with Nx I wanted to publish it with Yarn Berry. 

To do that I've moved into built library eg `cd dist/libs/lib1` and ran `yarn npm publish`. 

Command failed with error: `The nearest package directory (dist/libs/lib1) doesn't seem to be part of the project declared in {project_root_folder}`

## Expected Behavior
Library should be published

## Steps to Reproduce
1. Create Nx monorepo
2. Generate React libs
3. Build with `affected:build`
4. run `yarn npm publish` inside a built library

### Environment
Nx: v 11.2.12

**Comment by AndyClausen** [comment]
This relates to this issue:
https://github.com/yarnpkg/berry/issues/705

Workaround that I'm using:
1) Change workspaces folder in `package.json` from:
```json
  "workspaces": [
    "libs/*"
  ],
```
to:
```json
  "workspaces": [
    "dist/libs/*"
  ],
```
2) Run `yarn`
3) Go to the `dist/libs` folder and run your publish command
4) Revert 1. and run `yarn` again

It ain't pretty, but it gets the job done.

**Comment by AndyClausen** [comment]
This is still a problem, FYI. Could it be reopened?

**Comment by NikkiDelRosso** [comment]
Also running into this issue.
