### ISSUE TITLE
Add eslint rule for checking default import of React

### ISSUE THREAD

**Issue by jaysoo** [nrwl/nx#5198]
## Description
Since React will stop supporting `import React from 'react'` in the future, we should create a rule to find these problems.

## Motivation
So we can future-proof out applications.

## Suggested Implementation
https://github.com/nrwl/nx/issues/5090#issuecomment-811771236

## Alternate Implementations
Wait for React to stop providing default export, then `eslint-plugin-import` will catch it.

**Comment by cyrus-za** [comment]
> So we can future-proof out applications.
our*

Thanks for getting #5090 out and for creating this issue
