### ISSUE TITLE
Nx & Storybook: Cannot read property 'registerOptionsTransform' of undefined

### ISSUE THREAD

**Issue by gelsogrove** [nrwl/nx#5205]
I am trying to install storybook on my workspace installing @nrwl/storybook and follow your [guideline](https://nx.dev/latest/angular/storybook/overview) but it seems there is an internal error  when i run this command

_Command_
**nx g @nrwl/angular:storybook-configuration project-name**

_Error:_
**Cannot read property 'registerOptionsTransform' of undefined**

Version:
last angular version
last nx version
node 14.16
npm 6.14.11

here you can see the [stackoverflow](https://stackoverflow.com/questions/66887156/nx-storybook-cannot-read-property-registeroptionstransform-of-undefined) related to the bug

thanks in advance
Andrea

**Comment by juristr** [comment]
hey @gelsogrove. I just tried to reproduce the issue, but couldn't. 

- Can you run `npx nx report` and include the output?
- Include some more details or stacktrace of the error if present
- try with the latest Nx 12 we just released to see whether the issue is still present?

Thanks a lot for the help

**Comment by gelsogrove** [comment]
even if i use the last version i have the same error


  Node : 14.16.0
  OS   : darwin x64
  npm  : 6.14.11
  
  nx : Not Found
  @nrwl/angular : 11.4.0
  @nrwl/cli : 11.4.0
  @nrwl/cypress : 11.4.0
  @nrwl/devkit : 11.4.0
  @nrwl/eslint-plugin-nx : 11.4.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.4.0
  @nrwl/linter : 11.4.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.4.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.0.0
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 3.5.3

**Comment by gelsogrove** [comment]
![image](https://user-images.githubusercontent.com/15196278/115768740-009daa80-a3ab-11eb-8ae5-712011320145.png)

**Comment by gelsogrove** [comment]
✗ nx g @nrwl/angular:storybook-configuration preliminary
? Configure a cypress e2e app to run against the storybook instance? No
? Automatically generate *.stories.ts files for components declared in this library/application? **Yes**
? Automatically generate *.spec.ts files in the cypress e2e app generated by the cypress-configure generator? **No**
**Cannot read property 'registerOptionsTransform' of undefined**

**Comment by juristr** [comment]
Hey @gelsogrove, I tried again with v11.4.0 as well as with latest v12 and I'm not able to reproduce the issue.

From your `nx report` log I noticed though that you just upgraded the `@nrwl/workspace` to v12. All the Nrwl packages should always be in line in terms of their version.
When updating, use the [nx migrate](https://nx.dev/latest/angular/core-concepts/updating-nx#how-to-migrate) which will also make sure to automatically execute any code transformation that might be needed to adjust the configs in your Nx workspace. 

Also I notice it seems you don't have any `@nrwl/storybook` package installed. That is a prerequisite for having storybook. The error you're getting is weird though, as usually if you don't install the `@nrwl/storybook` you'd get something like

![image](https://user-images.githubusercontent.com/542458/115847549-5f066f80-a423-11eb-8c0c-c60a59c9a8f7.png)

So when I execute the following, it works for me:

```shell
$ npx create-nx-workspace storyngtest --preset=angular
$ cd storyngtest
$ npx nx g lib preliminary
$ npm i @nrwl/storybook
$ npx nx g @nrwl/angular:storybook-configuration preliminary
```

If the problem persists, feel free to reopen the issue. Thanks again

**Comment by gelsogrove** [comment]
Thank you.
just for letting you know when i use this configuration it works fine

"@nrwl/angular": "11.1.5",
"@nrwl/cli": "11.1.5",
"@nrwl/cypress": "11.1.5",
"@nrwl/eslint-plugin-nx": "11.1.5",
"@nrwl/jest": "11.1.5",
"@nrwl/tao": "11.1.5",
"@nrwl/workspace": "11.1.5",


but when i execute the command nx run myapp:storybook, nothing happen (doesn't start and there are
 not errors)
