### ISSUE TITLE
 Error occurred while trying to proxy request /api from localhost:4200

### ISSUE THREAD

**Issue by vandriesh** [nrwl/nx#5209]
## Current Behavior
web doesn't not communicate with api

## Expected Behavior
out of the box I'd expect no issue

## Steps to Reproduce
create nx workspace
serve api, server web (from ide's plugin)

![Screen Shot 2021-04-02 at 15 31 13](https://user-images.githubusercontent.com/7140194/113415721-7d4ef180-93c8-11eb-9989-32ae7ab84291.png)

![Screen Shot 2021-04-02 at 15 33 07](https://user-images.githubusercontent.com/7140194/113415942-ef273b00-93c8-11eb-9b12-afe48f81376a.png)

### Failure Logs
![Screen Shot 2021-04-02 at 15 32 00](https://user-images.githubusercontent.com/7140194/113415779-9c4d8380-93c8-11eb-8d1e-d82579d72da4.png)

### Environment

```

>  NX  Report complete - copy this into the issue template

  Node : 14.15.1
  OS   : darwin x64
  npm  : 6.14.8
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.6.1
  @nrwl/cypress : 11.6.1
  @nrwl/devkit : 11.6.1
  @nrwl/eslint-plugin-nx : 11.6.1
  @nrwl/express : 11.6.1
  @nrwl/jest : 11.6.1
  @nrwl/linter : 11.6.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.6.1
  @nrwl/react : 11.6.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.6.1
  @nrwl/web : 11.6.1
  @nrwl/workspace : 11.6.1
  @nrwl/storybook : 11.6.1
  @nrwl/gatsby : Not Found
  typescript : 4.0.7

```

**Comment by vandriesh** [comment]
the api works:

```
{"message":"Welcome to api!"}
```

**Comment by vandriesh** [comment]
and the cause was some changes related to cloud computing

![Screen Shot 2021-04-02 at 15 48 09](https://user-images.githubusercontent.com/7140194/113416889-e9325980-93ca-11eb-941c-b9f94a558a03.png)

![Screen Shot 2021-04-02 at 15 49 11](https://user-images.githubusercontent.com/7140194/113416969-18e16180-93cb-11eb-8ae6-027e7f641002.png)

**Comment by Cammisuli** [comment]
Does this issue still occur if you try to run the nx command by itself in the terminal? Also, are you using Webstorm or something similar?

**Comment by vandriesh** [comment]
Intellij IDEA

**Comment by vandriesh** [comment]
will open a new one if will happen when I try latest version

**Comment by princemuel** [comment]
also having this issue, but the app works when I startup the api and frontend separately
