### ISSUE TITLE
app.module.ts RouterModule.forRoot initialNavigation default should be 'enabled'

### ISSUE THREAD

**Issue by mattpenner** [nrwl/nx#5216]
## Description
When using ng generate @nrwl/angular:application schematic with the routing switch app.module.ts should contain:
`    RouterModule.forRoot([], { initialNavigation: 'enabledBlocking' }),`
instead of the current:
`    RouterModule.forRoot([], { initialNavigation: 'enabled' }),`

## Motivation
Per the [Angular 11 documentation](https://angular.io/api/router/InitialNavigation) the 'enabled' option has been depreciated and "is - 1:1 replaceable with enabledBlocking."

## Suggested Implementation
Upon executing, if Angular 11 or later is detected (if possible) 'enabledBlocking' should be used. If Angular <11 is detected (again, if possible) 'enabled' should be used.

**Comment by billyjov** [comment]
@vsavkin @FrozenPandaz is there a built in way here to easily check the workspace angular version ? I would like to work on this issue.

**Comment by mattpenner** [comment]
I researched this back when I submitted the issue, planning to add a pull for it but time got away from me. Perhaps you can pick up where I left off or already know the gaps I had in my knowledge.

The first question to ask is, and hopefully you or some Nx veterans can answer,  is this really necessary? If the latest build of Nx targets Angular 11 only then the schematic simply needs to be updated.  However, if it is meant to be backward compatible then detecting the Angular version is required. I couldn't find any evidence in the repo either way.

I would assume many shops using Nx have legacy projects and thus would not want schematics introducing breaking Angular 11 code if they were on a prior version. 

Regarding how to detect the Angular version you would most likely parse package.json.  There are Nx schematics that do just this, such as the [Storybook schematic](https://github.com/nrwl/nx/blob/d51bbe04f9f713a450262e962cc1a09425cfc085/packages/storybook/src/generators/init/init.ts).   

For testing you would want to mock package.json with different versions and ensure it was correctly applying the relevant code. It looks like some of the Nx test suites use [createTreeWithEmptyWorkspace util ](https://github.com/nrwl/nx/blob/d51bbe04f9f713a450262e962cc1a09425cfc085/packages/devkit/src/tests/create-tree-with-empty-workspace.ts#L6)to create the workspace that includes a package.json file.

**Comment by billyjov** [comment]
@mattpenner Yes you are right. let's wait and see if backward compatibility is desired

**Comment by leosvelperez** [comment]
Closed via https://github.com/nrwl/nx/pull/6036.
