### ISSUE TITLE
Unclear documentation: What are new workspace options?

### ISSUE THREAD

**Issue by maiermic** [nrwl/nx#5218]
I asked [this](https://nrwlcommunity.slack.com/archives/CMFKWPU6Q/p1615739386478600) question (3 weeks ago) in the Slack support channel and got no response. Since nobody seems to know, I created this issue with the goal to improve the documentation, which looks like this (in version 11.6.1):

```
Usage: create-nx-workspace <name> [options] [new workspace options]

Create a new Nx workspace

Options:

  name                      Workspace name (e.g., org name)

  preset                    What to create in a new workspace (options: "empty", "oss", "web-components", "angular", "angular-nest", "react", "react-express", "next", "gatsby", "nest", "express")

  appName                   The name of the application created by some presets

  cli                       CLI to power the Nx workspace (options: "nx", "angular")

  style                     Default style option to be used when a non-empty preset is selected
                            options: ("css", "scss", "styl", "less") for React/Next.js also ("styled-components", "@emotion/styled")

  linter                    Default linter. Options: "eslint", "tslint".

  interactive               Enable interactive mode when using presets (boolean)

  packageManager            Package manager to use (npm, yarn, pnpm)

  nx-cloud                  Use Nx Cloud (boolean)

  [new workspace options]   any 'new workspace' options
``` 

I'm refering to the last section

> ```
> [new workspace options]   any 'new workspace' options
> ```

in the following. It is unclear to me, what `new workspace options` are or to what `'new workspace'` refers to in the description. Where can I look up these options?

## Steps to Reproduce
```
yarn create nx-workspace --help
```

**Comment by maiermic** [comment]
Keep it active

**Comment by maiermic** [comment]
@bcabanes Why did you remove the `new workspace options` from the CLI description? Do they not exist? I'm still confused 😕

**Comment by bcabanes** [comment]
This is exactly why we thought it was better to remove the line entirely. This line applied only for one option (`--defaultBase`) so far, which is not recommended to set when creating a new workspace right away. We prefer to remove the line until we have better use of it and better ergonomic.

**Comment by maiermic** [comment]
Thank you for clarifying 👍
