### ISSUE TITLE
Unclear error message when trying to run a custom builder: Invalid format version detected - Expected:[ 1 ] Found: [ 2]

### ISSUE THREAD

**Issue by elenasch** [nrwl/nx#5220]
I am running Nx11 (`nx@11.6.1`) and am trying to write a custom builder in an `empty` workspace.  However when running `nx build` command I get a few errors. 

First it looked like `@angualr-devkit/core` and `@angular-devkit/architect` packages where missing. I installed them with `yarn add @angualr-devkit/core`  and `yarn add @angualr-devkit/architect`. 

Then I started seeing `Invalid format version detected - Expected:[ 1 ] Found: [ 2]` error. With no stack trace or explanation of which package is not .

For starters my builder is the one from one of the examples in the docs. Nothing special to it, just prints a message , but i'm pretty sure the failure is coming from somewhere earlier . 

Here's the builder impl
```
import { ExecutorContext } from '@nrwl/devkit';

interface Schema {
  message: string;
  upperCase: boolean;
}

export default async function printAllCaps(
  options: Schema,
  context: ExecutorContext
): Promise<{ success: true }> {
  if (options.upperCase) {
    console.log(options.message.toUpperCase());
  } else {
    console.log(options.message);
  }
  return { success: true };
}
```

**Comment by vsavkin** [comment]
Thank you for submitting the issue.

Neither @angualr-devkit/core or @angular-devkit/architect are required to author an executor/builder. 

Could you provide a repro with a repo so I can take a look at the issue? I'm not able to reproduce it in the setup I have.

Thank you!
