### ISSUE TITLE
ng generate no longer knows --app?

### ISSUE THREAD

**Issue by jesdynf** [nrwl/nx#523]
Per https://github.com/nrwl/nx-examples/issues/40 , I can't generate bits in libs after installing Nrwl 6. `--help` shows the `--app` argument isn't even on the list. `ng generate service myService --app=lib-service` ignores the `--app` entirely and puts things in the hello-world app.

I tried upgrading my Nrwl5 project but I got a crash and some advice to just 'git checkout .' to bail out, so I wiped out npm and started fresh on a new Nrwl6 project.

**Comment by jesdynf** [comment]
#522 is probably the same thing.

**Comment by FrozenPandaz** [comment]
`ng generate` in Angular CLI 6 now uses `--project`

`ng generate service myService --project=lib-service` is what you want.

Thanks!

**Comment by juristr** [comment]
@jesdynf More infos can be found here: https://nrwl.io/nx/guide-nx-workspace
