### ISSUE TITLE
How do we generate a library with NX 6?

### ISSUE THREAD

**Issue by bryanrideshark** [nrwl/nx#524]
I'm using NX 6.0

Calling `ng g lib library-name` generates a project in the `projects` folder.

I would like it to generate a library in the `libs` folder, like it did before.

I suspect that this is because "lib" runs the Angular CLI schematic now, where I want it to be running the nrwl/schematics schematic.

How do I get it to run the nrwl/schematics:library schematic for me?

**Comment by bryanrideshark** [comment]
After investigation, this comes from `ng add @nrwl/schematics` not working properly.

Your angular.json should contain:

````
"newProjectsRoot": "",
"cli" : {
  "defaultCollection" :"@nrwl/schematics"
}
````

If you are running into the same problem I did, or have had a problem running `ng add @nrwl/schematics`, try manually changing your angular.json. Should fix the problem for you.

**Comment by martzcodes** [comment]
When creating a nx workspace from scratch `ng g lib library-name` seems to work.

**Comment by FrozenPandaz** [comment]
I am not seeing this issue on the latest version of Nx. Can you please retry with version 6.1.0?

Thank you

**Comment by ThomasBurleson** [comment]
Closing as no longer an issue.
