### ISSUE TITLE
Angular monorepo -> Adding Nx - Unhandled exception can't find @nrwl/workspace/src/utils/name-utils

### ISSUE THREAD

**Issue by Vorakor** [nrwl/nx#5241]
## Current Behavior
When trying to generate a library with the nx schematics, it fails complaining about missing a package in the nx/workspace module.

An unhandled exception occurred: Cannot find module '@nrwl/workspace/src/utils/name-utils'
Require stack:
- ~\Development\sample-workspace\node_modules\@nrwl\angular\src\utils\ast-utils.js
- ~\Development\sample-workspace\node_modules\@nrwl\angular\src\schematics\library\library.js
- ~\Development\sample-workspace\node_modules\@angular-devkit\schematics\tools\export-ref.js 
- ~\Development\sample-workspace\node_modules\@angular-devkit\schematics\tools\index.js      
- ~\Development\sample-workspace\node_modules\@angular\cli\utilities\json-schema.js
- ~\Development\sample-workspace\node_modules\@angular\cli\models\command-runner.js
- ~\Development\sample-workspace\node_modules\@angular\cli\lib\cli\index.js
- ~\Development\sample-workspace\node_modules\@angular\cli\lib\init.js
- ~\Development\sample-workspace\node_modules\@angular\cli\bin\ng
See "~\AppData\Local\Temp\ng-ZJnX8c\angular-errors.log" for further details.

## Expected Behavior
Create a new library folder named libs/ and build a new library out in that folder.

## Steps to Reproduce
Using CLI I ran the following steps:
-ng new sample-workspace --create-application=false
-cd sample-workspace
-ng generate library toolbar-components
-ng add @nrwl/schematics (resulted in error: cannot set property 'outDir' of undefined)
-ng generate library design-app
-ng generate library design-app-e2e
-ng add @nrwl/schematics (another error)
-npx add-nx-to-monorepo
-npm install
-npm install @nrwl/cli
-nx migrate latest (didn't do anything)
-nx update --all --force (didn't do anything)
-ng add @nrwl/angular (didn't fix anything)

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs
[error] Error: Cannot find module '@nrwl/workspace/src/utils/name-utils'
Require stack:
- C:\Users\sberube\Development\sample-workspace\node_modules\@nrwl\angular\src\utils\ast-utils.js
- C:\Users\sberube\Development\sample-workspace\node_modules\@nrwl\angular\src\schematics\library\library.js
- C:\Users\sberube\Development\sample-workspace\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\sberube\Development\sample-workspace\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\sberube\Development\sample-workspace\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\sberube\Development\sample-workspace\node_modules\@angular\cli\models\command-runner.js
- C:\Users\sberube\Development\sample-workspace\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\sberube\Development\sample-workspace\node_modules\@angular\cli\lib\init.js
- C:\Users\sberube\Development\sample-workspace\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at Module.require (C:\Users\sberube\Development\sample-workspace\node_modules\@nrwl\tao\src\compat\compat.js:7:40)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\sberube\Development\sample-workspace\node_modules\@nrwl\angular\src\utils\ast-utils.js:7:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)

### Environment
 NX  Report complete - copy this into the issue template

  Node : 12.15.0
  OS   : win32 x64
  npm  : 6.13.4

  nx : Not Found
  @nrwl/angular : 8.12.11
  @nrwl/cli : 11.6.1
  @nrwl/cypress : 8.12.11
  @nrwl/devkit : 11.6.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.12.11
  @nrwl/linter : 11.6.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 11.6.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.6.1
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.5

**Comment by vsavkin** [comment]
Thank you for submitting the issue!

`@nrwl/schematics` is an old version of the package and it should not be used anymore. 

The proper way to add Nx to an Angular CLI repo is by using: `ng add @nrwl/workspace` or by using : `ng add @nrwl/workspace --preserveAngularCLILayout`. See here for more info: https://nx.dev/latest/angular/migration/migration-angular

Thank you!
