### ISSUE TITLE
ESLint plugin:@nrwl/nx/angular should overwrite less rules (e.g. not overwrite member-ordering)

### ISSUE THREAD

**Issue by stefan-schweiger** [nrwl/nx#5259]
Currently `plugin:@nrwl/nx/angular` sets certain rules like `@typescript-eslint/member-ordering`. As far as I can tell this is also already set in `plugin:@nrwl/nx/typescript` in the root `/.eslintrc.json.`

But with `plugin:@nrwl/nx/angular` being extended by default in all angular libs you can't overwrite the member-ordering yourself in the root configuration but would need to set it in each `<lib>/.eslintrc.json`.

I'm certain there are some eslint configurations which make sense to set by default on an angular lib level, but those which are already set by `plugin:@nrwl/nx/typescript` shouldn't be included in them.

Are there any arguments against evaluating and excluding certain eslint rules?

**Comment by JamesHenry** [comment]
Hi @stefan-schweiger, all `@nrwl/nx/angular` currently does it extend from `@angular-eslint/eslint-plugin:recommended`.

In v2+ of `@angular-eslint` there are only @angular-eslint rules in the recommended config, so all you need to do to get the behaviour you want is update your @angular-eslint dependencies in your workspace to the latest.

This was resolved automatically by https://github.com/nrwl/nx/pull/5233 (the automated mgiration will therefore be in the next release of Nx).

**Comment by stefan-schweiger** [comment]
@JamesHenry sorry it's been a few days but I've finally upgraded to Angular 11and `@angular-eslint` v2+.
But as it turns out actually `@angular-eslint/eslint-plugin:recommended` [actually does set rules ](https://github.com/angular-eslint/angular-eslint/blob/master/packages/eslint-plugin/src/configs/recommended.json#L15) which aren't `@angular-eslint` rules...

Do you have any suggestions if there is a way how to overwrite the rules in the root config without having to touch every lib config?

I still stand by my comment that I think `plugin:@nrwl/nx/angular` shouldn't overwrite those settings even if they come from `@angular-eslint`. Any thoughs on that?

**Comment by markonyango** [comment]
Let me add my feedback here as well:

I absolutely agree with this point. It took me quite some time to find out why some rules were not "taking" and others were. The only solution I found so far was to create a separate .eslintrc-base.json file which holds the rules object. That way I can extend it in each apps and libraries .eslintrc.json file (must be the last import because order of extending files matters):
```
"extends": [
        "plugin:@nrwl/nx/angular",
        "plugin:@angular-eslint/template/process-inline-templates",
        "../../.eslintrc-base.json"
      ],
```
The setup as it is being created by the CLI is currently counter-intuitive.

**Comment by JamesHenry** [comment]
Cc @FrozenPandaz 

We are likely going to change this in v13 of Nx. It needs to happen in a major version as it will change linting behaviour and there will likely not be a one size fits all migration.

I’m afraid in the meantime you either need to :

- change your project config each time: either by turning off rules or by adding an extends on an additional shareable config you create within your own workspace which handles it.
- create a workspace generator which wraps the built in one and just tweaks the lib config

**Comment by markonyango** [comment]
@JamesHenry 

So the solution I described is the current intended way of setting up the lint configuration?

**Comment by JamesHenry** [comment]
Ha you managed to write a comment in between me reopening and writing mine! 

Intended might be too strong a word - but yes it’s one of the possible workarounds available to folks who are unhappy with the extra typescript rules which are being applied by default in v12.

**Comment by JamesHenry** [comment]
Sorry for this confusion in general on the cascading configs here...

angular-eslint’s origins are in helping people have a similar experience to the TSLint setup in angular CLI. We have now moved beyond that in that project but the way Nx wires it all up needs to change in a major version

**Comment by markonyango** [comment]
:-D I was not prepared for the swift replies in this thread indeed.

Thank you, I will implement it that way for the time being. 👍

**Comment by yassernascimento** [comment]
Hello everyone, how can I know which rules are defined at `plugin:@nrwl/nx/angular` or `plugin:@nrwl/nx/typescript`?
Is that on any documentation?

**Comment by the-ult** [comment]
> Hello everyone, how can I know which rules are defined at `plugin:@nrwl/nx/angular` or `plugin:@nrwl/nx/typescript`? Is that on any documentation?

This would indeed be nice if this would be somehow documented as part of https://nx.dev/l/a/linter/eslint or something. 👍

**Comment by Coly010** [comment]
@JamesHenry Is this still an issue after the Angular 13 upgrade?

**Comment by davidyoung77** [comment]
This is unfortunately still an issue, is this still going to be fixed?

**Comment by davidyoung77** [comment]
I just manually remove `"plugin:@nrwl/nx/angular"` from the project specific extends, as it causes more harm than it adds benefits, until this can get fixed.

Maybe in the future I will add my own generator to handle this. It seems like this shouldn't be in the nx generator though as it is incomplete and doesn't have a suggested pattern to follow.

**Comment by miluoshi** [comment]
I'm not sure if this is related - config `plugin:@nrwl/eslint-plugin-nx/angular` also extends `plugin:@angular-eslint/recommended--extra`, but according to [overdue TODO comment](https://github.com/nrwl/nx/blob/master/packages/eslint-plugin-nx/src/configs/angular.ts#L29=) it should be removed by Nx v13. Are there plans to remove this?

**Comment by cnschwarz** [comment]
Hi @JamesHenry @FrozenPandaz 

Throug a couple of closed issues and related ones I landed on this issue. 
https://github.com/nrwl/nx/issues/4585 
https://github.com/nrwl/nx/issues/4320

Is this feature still planned to be included soon? 
I am currently on NX 14.4.3 and I face a similar issue. In the global .eslintrc.json I have turned off some TypeScript and Ngrx rules since I have only angular projects in my workspace. Now when I run `nx run-many --all --target=lint` in my workspace the lint job shows me everything is fine and no findings for all projects. But when I run the lint job for a specific app or lib package then the top level eslint configurations are being ignored and I get a lot of warnings that should be turned off. 

Those are the rules I added at the end of the top level rules object:
```
        "@typescript-eslint/consistent-type-assertions": [
          "warn",
          {
            "assertionStyle": "as",
            "objectLiteralTypeAssertions": "never"
          }
        ],
        "@ngrx/on-function-explicit-return-type": "off",
        "@ngrx/prefer-effect-callback-in-block-statement": "off",
        "@ngrx/no-typed-global-store": "off"
```

Plugin versions related to this:
    "@angular-eslint/eslint-plugin": "14.0.2",
    "@angular-eslint/eslint-plugin-template": "14.0.2",
    "@angular-eslint/template-parser": "14.0.2",
    "eslint-plugin-ngrx": "^2.1.2",

Would be great if you could provide an update on this topic :) 

Cheers

**Comment by davidediak** [comment]
I can't specify a global "no-restricted-imports" because of this plugin.
Also plugin's no-restricted-imports rule is actually not working....

**Comment by gabrielmethot** [comment]
Not sure if this is related, but I have the following override in my root `.eslintrc.json`:
```
{
  "files": ["*.ts", "*.tsx"],
  "extends": ["plugin:@nrwl/nx/typescript"],
  "rules": {
    "@typescript-eslint/switch-exhaustiveness-check": "error"
    "@typescript-eslint/member-ordering": "warn",
  }
}
```

For some unknown reason, the `"@typescript-eslint/switch-exhaustiveness-check": "error"` override works perfectly fine, but the override  `"@typescript-eslint/member-ordering": "warn"` is completly ignored.

```
   Node : 16.19.0
   OS   : linux x64
   npm  : 8.19.3
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
```
