### ISSUE TITLE
Generating new components doesn't seem to work

### ISSUE THREAD

**Issue by bryanrideshark** [nrwl/nx#526]
After upgrading to NX 6 in the nx-examples repo, one cannot generate components.

To reproduce, clone the nx-examples repository, make sure you're running nx 6, and then try the following command:

`ng g c test-component --project=login`

You'll either encounter the error "NgModule not found".

This can be alleviated by changing the "root" property for the "login" project in angular.json. Once you do this however, generating the component still puts it in the wrong place - the generated component goes to `libs/login/src/app/test-component`, instead of `libs/login/src/test-component`.

I suppose this requires making a new schematic for Nrwl/nx 6.0?

**Comment by jschwarty** [comment]
@bryanrideshark Is this an issue in the `nx-examples` code base? If so, would it be possible for you to submit this issue [there](https://github.com/nrwl/nx-examples/issues)? Running the component schematic on a new Nx workspace v6 appears to work correctly. Might just be an issue in that example project. Thanks!

**Comment by eliellis** [comment]
This is happening to me as well. Not using `nx-examples` at all. Project was generated using the `create-nx-workspace` on 6.0.2. Trying to run the `ng g c blah -p=main` generates the component files in the incorrect folder. The generated files end up in the default project directory, rather than the one specified in the command. So, in the aforementioned case, if the default project was named `default` the component files are placed in `apps/default/src/blah` rather than the expected `apps/main/src/blah`.

**Comment by vsavkin** [comment]
@bryanrideshark @eliellis could you provide a repo with a repro?

**Comment by CN91** [comment]
I'm also not getting ng g c to work.. freshly installed nrwl and nrgx ,new project. 

If i use 
`ng g c home --project test`
I get the following error:  
`Selector (apps/test-workspace-home) is invalid`


In the directory itself I get the error NgModule not found, and when I use --skip-import, it goes back to selector is invalid.

Any tips?

**Comment by FrankBongers** [comment]
Solved. Maybe.
I had the same problem. Wanted to generate several apps in one workspace, all using same prefix:
ng generate app myapp1 --prefix app
Looked okay. Did that for app1, app2, app3...
Could not generate components in any app:
ng g c comp1 --project app1
Message:
Selector (apps/app-comp1) is invalid
In angular.json I found the following:
"projects": {
    "app1": {
      "root": "apps/app1/",
      "sourceRoot": "apps/app1/src",
      "projectType": "application",
      "prefix": "apps/app",       // <---- !!
     ...
After manually correcting everything worked.
      "prefix": "app",  // -> took out 'apps/' !!
I hope that helps. Maybe Justin can find out what was going on?
All the best,
Frank

**Comment by benjamindamm** [comment]
Is there any solution? This is my very first setup with nx and I got nothing working. Generated a workspace, generated an application. Thats it, I cant even create a simple component. 

And sorry everybody who works for a company, can not share any repos.

I have just a basic setup.

{
  "name": "my-app",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "./node_modules/.bin/nx lint && ng lint",
    "e2e": "ng e2e",
    "affected:apps": "./node_modules/.bin/nx affected:apps",
    "affected:libs": "./node_modules/.bin/nx affected:libs",
    "affected:build": "./node_modules/.bin/nx affected:build",
    "affected:e2e": "./node_modules/.bin/nx affected:e2e",
    "affected:test": "./node_modules/.bin/nx affected:test",
    "affected:lint": "./node_modules/.bin/nx affected:lint",
    "affected:dep-graph": "./node_modules/.bin/nx affected:dep-graph",
    "format": "./node_modules/.bin/nx format:write",
    "format:write": "./node_modules/.bin/nx format:write",
    "format:check": "./node_modules/.bin/nx format:check",
    "update": "ng update @nrwl/schematics",
    "update:check": "ng update",
    "workspace-schematic": "./node_modules/.bin/nx workspace-schematic",
    "dep-graph": "./node_modules/.bin/nx dep-graph",
    "help": "./node_modules/.bin/nx help"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "core-js": "^2.5.4",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26",
    "@nrwl/nx": "6.3.0",
    "@ngrx/effects": "6.0.1",
    "@ngrx/router-store": "6.0.1",
    "@ngrx/store": "6.0.1"
  },
  "devDependencies": {
    "@angular/cli": "6.1.2",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@angular-devkit/build-angular": "~0.7.0",
    "@ngrx/store-devtools": "6.0.1",
    "ngrx-store-freeze": "0.2.4",
    "@nrwl/schematics": "6.3.0",
    "jasmine-marbles": "0.3.1",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2",
    "prettier": "1.13.7"
  }
}

**Comment by benjamindamm** [comment]
Removing "apps/" from prefix in angular.json solves the problem. But this is definitive a bug that should be solved.

**Comment by bcabanes** [comment]
Closing this old issue.

**Comment by Fallenstedt** [comment]
Despite it being an old issue, it's still relevant. 

I encountered a similar problem today, except the problem occured with a library. I could not add any components / modules to an existing library. The problem was similar to what was above. In my angular.json, I had `libs/` in a prefix. 

```
"three": {
      "root": "libs/three",
      "sourceRoot": "libs/three/src",
      "projectType": "library",
      "prefix": "three-experiments", // remove any `libs/` prefix here
      "architect": {
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "libs/three/src/test.ts",
            "tsConfig": "libs/three/tsconfig.spec.json",
            "karmaConfig": "libs/three/karma.conf.js"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "libs/three/tsconfig.lib.json",
              "libs/three/tsconfig.spec.json"
            ],
            "exclude": ["**/node_modules/**"]
          }
        }
      }
    },
```

Basically `"prefix": "three-experiments", // -> took out 'libs/' !!`

Note I was using the angular console to manage all creation of libs, modules and components.

**Comment by ChristopheCuddlup** [comment]
Hi,

Got same issue this morning.
Being in ClientApp/src/app folder and entering 

> ng g c './routes/company/filecontent'

ends with the error 

> Selector (app-filecontent') is invalid.

But using 
> ng generate component routes/company/filecontent
works...

**Comment by skwny** [comment]
I experienced the same issue as well:

```
> Executing task in folder myProject: ng generate @schematics/angular:component --name=new-component --no-interactive --dry-run <

Project 'myProject' could not be found in workspace.
The terminal process terminated with exit code: 1

```
