### ISSUE TITLE
Migration to Nx > 11.0.0 should update ngrx to 11.1.0

### ISSUE THREAD

**Issue by santoshyadavdev** [nrwl/nx#5261]
There is an issue with NgRx 11 https://github.com/ngrx/platform/issues/2919  which is fixed in 11.0.1 as per the comments.

If you can help me where to make changes , I will be more than happy to raise a PR.

## Current Behavior
Migration to Nx does not update ngrx

## Expected Behavior
It should update ngrx version as well.

**Comment by brandonroberts** [comment]
Thanks @santoshyadavdev! There are a few files you have to update for this:

- Update the root `package.json` with the latest versions here https://github.com/nrwl/nx/blob/master/package.json#L56
- Run `yarn` to update the packages
- To update the NgRx packages during migration, you'll need to add updated versions to the `migrations.json` here https://github.com/nrwl/nx/blob/master/packages/angular/migrations.json#L297. For the `version`, use the next version that will be released, such as `12.1.0-beta.0`
- To update the default version installed in a new workspace, update this file https://github.com/nrwl/nx/blob/master/packages/angular/src/utils/versions.ts#L5

That should be what you need for a PR.

**Comment by santoshyadavdev** [comment]
Thanks @brandonroberts , PR coming soon 😀

**Comment by saleemmalikraja** [comment]
Thanks @santoshyadavdev . Faced the same issue and ended up finding this post to fix it :)
