### ISSUE TITLE
Unify behaviour of affected:apps, affected:libs and print-affected

### ISSUE THREAD

**Issue by minijus** [nrwl/nx#5264]
## Description
Today `affected:apps`, `affected:libs` and `print-affected` have different behaviour. Their usage is slightly different and their output formatting differs as well.
https://github.com/nrwl/nx/blob/master/packages/workspace/src/command-line/affected.ts

`nx affected:apps --plain` produce space separated list and `nx print-affected --select=projects` produce comma separated list. 

## Motivation
When building distributed tasks in CI (i.e. Jenkins) it is needed to extract affects apps or libs in convenient format and preferably using same command (to simplify logic). It would be great to have something like:
 * `nx print-affected --select=projects --apps`
 * `nx print-affected --select=projects --libs`

## Suggested Implementation
Make sure printing out of affected projects use same implementation (probably from `print-affected`) and some of commands (`affected:apps`, `affected:libs`) are just shorthands.

**Comment by pauleustice** [comment]
As a related sidenote, the documentation for `nx affected:apps` could be improved. It wasn't clear to me that this would not return e2e applications, and it was only by noticing they were missing while developing a CI integration (early on, luckily) that I was led to this issue (and the existence of `nx print-affected`).
