### ISSUE TITLE
Bug when build publishable package - 'file' is not under 'rootDir' 'libs/...'. 'rootDir' is expected to contain all source files

### ISSUE THREAD

**Issue by wizardnet972** [nrwl/nx#5267]
## Current Behavior

Got an error when I build build publishable package:
```
error TS6059: File 'C:/sandbox/myorg/libs/database/auth/src/lib/database-auth.ts' 
is not under 'rootDir' 'libs/foo/cli'. 'rootDir' is expected to contain all source files.
```

See error details below.

## Expected Behavior
The build process should complete.

## Steps to Reproduce

1. npx create-nx-workspace myorg --preset=empty --nx-cloud=false
2. cd myorg
3. npm i @nrwl/node --save-dev
4. nx generate @nrwl/node:library --name=cli --directory=foo --importPath=@myorg/foo-cli --publishable --no-interactive
5. nx generate @nrwl/node:library --name=auth --directory=database
6. just add the following content to `C:\sandbox\myorg\libs\foo\cli\src\lib\foo-cli.ts`:
```
import { databaseAuth } from '@myorg/database/auth';
```
7. now, run the build: `nx run-many --target=build --all`
 
### Failure Logs

```
yarn run v1.22.5
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ nx run-many --target=build --all

> nx run foo-cli:build
Compiling TypeScript files for library foo-cli...
libs/database/auth/src/index.ts:1:15 - error TS6059: File 'C:/sandbox/myorg/libs/database/auth/src/lib/database-auth.ts' is not under 'rootDir' 'libs/foo/cli'. 'rootDir' is expected to contain all source files.

1 export * from './lib/database-auth';
                ~~~~~~~~~~~~~~~~~~~~~
libs/foo/cli/src/lib/foo-cli.ts:1:30 - error TS6059: File 'C:/sandbox/myorg/libs/database/auth/src/index.ts' is not under 'rootDir' 'libs/foo/cli'. 'rootDir' is expected to contain all source files.

1 import { databaseAuth } from '@myorg/database/auth';
                               ~~~~~~~~~~~~~~~~~~~~~~

libs/database/auth/src/index.ts:1:15 - error TS6059: File 'C:/sandbox/myorg/libs/database/auth/src/lib/database-auth.ts' is not under 'rootDir' 'libs/foo/cli'. 'rootDir' is expected to contain all source files.

1 export * from './lib/database-auth';
                ~~~~~~~~~~~~~~~~~~~~~
libs/foo/cli/src/lib/foo-cli.ts:1:30 - error TS6059: File 'C:/sandbox/myorg/libs/database/auth/src/index.ts' is not under 'rootDir' 'libs/foo/cli'. 'rootDir' is expected to contain all source files.

1 import { databaseAuth } from '@myorg/database/auth';
                               ~~~~~~~~~~~~~~~~~~~~~~
———————————————————————————————————————————————

>  NX   ERROR  Running target "build" failed

````

I think its happens because the `database-auth` is not `publishable`.
And it shouldn't be publishable. 
But the `foo-cli` should be `publishable`. 

Maybe the problem is the [node package](https://github.com/nrwl/nx/blob/master/packages/node/src/executors/build/build.impl.ts) don't read the `paths` from tsconfig at root.

How to fix that problem?

**Comment by iamvinitk** [comment]
@wizardnet972 Did you find a solution for the issue?

**Comment by wizardnet972** [comment]
@iamvinitk  Yes. kind of. this message I get when I run the nx command not at the root folder.
Also when I have publish library that uses non-publish library. the workaround is to create nx lib with `buildable` flag or `publishable` flag. otherwise nx show this error message.

**Comment by mariusvirb** [comment]
hey, there, encountering same issue, publishable libraries that reference non-publishable/buildable library, spews out 'rootDir' error
