### ISSUE TITLE
Specify options to uglify

### ISSUE THREAD

**Issue by Lonli-Lokli** [nrwl/nx#5269]
We would like to specify options to uglify (specifically, keep_fnames)

## Description
possibility to specify flags

## Motivation
 Im relying on class names in my code.

**Comment by vsavkin** [comment]
Could you provide more context? You can provide your own webpack config when building apps? Is it insufficient?

**Comment by Lonli-Lokli** [comment]
Will it work the same as default one? I believe TerserOptions will needs to be replaced completely?
