### ISSUE TITLE
Tests: makeSureNoAppIsSelected is not a function

### ISSUE THREAD

**Issue by Springrbua** [nrwl/nx#529]
When I execute `ng test projectName` in my @nrwl/nx-application I get the following error:
`makeSureNoAppIsSelected is not a function`

this happens, after upgrading to Angular and @nrwl/nx version 6.

The error is probably a wrong `require` in `karma.conf.js`:

`const { makeSureNoAppIsSelected } = require('@nrwl/schematics/src/utils/cli-config-utils');`

The file [schematics/src/utils/cli-config-utils](https://github.com/nrwl/nx/blob/master/packages/schematics/src/utils/cli-config-utils.ts) has no function `makeSureNoAppIsSelected`.  
The function, instead seems to be in [bazel/src/utils/cli-config-utils](https://github.com/nrwl/nx/blob/master/packages/bazel/src/utils/cli-config-utils.ts).

So the generated `karma.conf.js` as well as the one in [@nrwl/nx-example seems to be wrong](https://raw.githubusercontent.com/nrwl/nx-examples/master/karma.conf.js)

**Comment by juristr** [comment]
Is this the global test.js file at the root of ur nx project?

**Comment by exequiel09** [comment]
It should be removed already since each project in the Nrwl Workspace has it's own karma configuration and test bootstrapper.

**Comment by Springrbua** [comment]
@juristr yes, it's the global karma.conf.js file at root-level.
@exequiel09 after the upgrade, the configurations of all projects point to `./karma.conf.js`, which only exists at the root-level.
Also the example application @nrwl/nx-examples seems to use one single karma.conf.js at the root level.

I removed the `require` and the `function` call and executing `ng test projectName` works now, but ofc it tests all projects.

**Comment by exequiel09** [comment]
I didn't used the upgrade/migration provided by Nx, I created a new Nx workspace and replicated those changes to an existing codebase. Try generating a new workspace using v6 and see the configuration. Each has its own karma configuration and test bootstrapper.

**Comment by juristr** [comment]
Exactly, there's now one karma + e2e project configuration per application. That seems to be the new strategy. Although it would be nice to have a way to execute so tests in the workspace without using custom scripts and hacks..

See https://github.com/nrwl/nx/issues/514

**Comment by Springrbua** [comment]
I compared my upgraded application with a newly generated nrwl application and found quite a few differences. 
I updated my project, so that the structure matches the one of the new project and the tests are now executed per app, as they should. 
Thanks for your help :)
