### ISSUE TITLE
How to debug jest tests?  Documentation incorrect?

### ISSUE THREAD

**Issue by jasedwards** [nrwl/nx#5298]
## Current Behavior
The documentation states I should run this to debug tests:
node --inspect-brk ./node_modules/nx/bin/nx test libname

When I do that I get this error:
![image](https://user-images.githubusercontent.com/5818023/114242767-0f1ea780-9951-11eb-8c94-b954e4b91f1f.png)

So I thought I would try the correct path to .bin/nx using node --inspect-brk ./node_modules/.bin/nx test shared-framework-button --runInBand but I get this error:
![image](https://user-images.githubusercontent.com/5818023/114242899-3ecdaf80-9951-11eb-9d7b-bbd3d34858c1.png)

## Expected Behavior
it should work as the docs say it should

## Steps to Reproduce
run the command above

### Failure Logs
see screenshots above

### Environment
 Node : 14.16.0
  OS   : win32 x64
  npm  : 6.14.11

  nx : Not Found
  @nrwl/angular : 11.6.1
  @nrwl/cli : 11.6.1
  @nrwl/cypress : 11.6.1
  @nrwl/devkit : 11.6.1
  @nrwl/eslint-plugin-nx : 11.6.1
  @nrwl/express : Not Found
  @nrwl/jest : 11.6.1
  @nrwl/linter : 11.6.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.6.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.6.1
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.0.7

**Comment by vsavkin** [comment]
Thank you for submitting the issues! Fixed it here: https://github.com/nrwl/nx/pull/5307

You need to change the command to:
```
node --inspect-brk ./node_modules/@nrwl/cli/bin/nx test libname
```
