### ISSUE TITLE
Missing nx.deps.json for ESLint VSCode

### ISSUE THREAD

**Issue by skydever** [nrwl/nx#5299]
## Current Behavior

It seems like that the `nxdeps.json` file will not be created when VSCode is loading the **@nrwl/nx/enforce-module-boundaries** es-lint rule, I geht the following error message at the ESLint output:

`[Info  - 23:28:28] Error while loading rule '@nrwl/nx/enforce-module-boundaries': Cannot read property 'nodes' of null Occurred while linting`

## Expected Behavior

Loading the es-lint rule **@nrwl/nx/enforce-module-boundaries** in VSCode should create the `nxdeps.json` file if it does not exist.

## Steps to Reproduce

Delete the **nx cache** directory and start VSCode with the extension **ESLint** installed. Open a file that contains a linter error. After some loading time the ESLint output of VSCode shows the error message mentioned above, no linter errors are shown at the editor.

Close VSCode and run `nx dep-graph`. The `nxdeps.json` file will be created in the **nx cache** directory. Open VSCode again - now the error is gone and the linter errors are shown.

### Failure Logs

`[Info  - 23:28:28] Error while loading rule '@nrwl/nx/enforce-module-boundaries': Cannot read property 'nodes' of null Occurred while linting`

### Environment

nx: 12.0.0
eslint: 7.22.0
windows 10
node: v12.18.4

**Comment by vsavkin** [comment]
Thank you for submitting the issues! Fixed it here: https://github.com/nrwl/nx/pull/5307
