### ISSUE TITLE
Malformed .babelrc in React projects

### ISSUE THREAD

**Issue by JoelVenable** [nrwl/nx#5303]
## Current Behavior
In a new project, starting from an empty template, running any of the bootstrap utilities may produce errors and always results in a malformed .babelrc in the resulting app/lib.

## Expected Behavior
Successful completion and correct JSON formatting for the resulting .babelrc file.

## Steps to Reproduce

1. Run `yarn create nx-workspace`
2.  Select the following options:  
  - Workspace name: `<any>`
  - What to create: `react`
  - Application name: `<any>`
  - Default stylesheet format: `@emotion/styled`
  - Use Nx Cloud: `no`
3.  Open the .babelrc file in the resulting app directory.

### Failure Logs

.babelrc:

```
{
  "presets": [
    [
      "@nrwl/react/babel", {
        "runtime": "automatic"
        ,"importSource": "@emotion/react" }
      }
    ]
  ],
  "plugins": [
    
    
    ,"@emotion/babel-plugin"
  ]
}
```

### Environment
```
  Node : 14.15.3
  OS   : linux x64
  npm  : 6.14.9
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.0.0
  @nrwl/cypress : 12.0.0
  @nrwl/devkit : 12.0.0
  @nrwl/eslint-plugin-nx : 12.0.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.0
  @nrwl/linter : 12.0.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 12.0.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.0
  @nrwl/web : 12.0.0
  @nrwl/workspace : 12.0.0
  @nrwl/storybook : 12.0.0
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

Also reproduced on `darwin arm64`.

**Comment by JoelVenable** [comment]
Looks like the error is specific to the `@emotion` selection.

**Comment by vsavkin** [comment]
Thank you for submitting the issue! Fixed it here: https://github.com/nrwl/nx/pull/5307

**Comment by JoelVenable** [comment]
In #5307 the common template was fixed, however the lib also has the same issue and was not fixed.
