### ISSUE TITLE
Remove tslint vscode plugin

### ISSUE THREAD

**Issue by cyrus-za** [nrwl/nx#5308]
When generating a new nx workspace a .vscode/extensions.json gets created alongside it with `ms-vscode.vscode-typescript-tslint-plugin` in there.

Nx no longer defaults to tslint but rather uses eslint. Please remove the recommended extension

**Comment by Divlo** [comment]
Hey @cyrus-za!
This is already addressed by this PR: https://github.com/nrwl/nx/pull/5280
