### ISSUE TITLE
NX 12 build failed in React workspace

### ISSUE THREAD

**Issue by dangviettuan** [nrwl/nx#5323]
## Current Behavior
Website with production build crashed.

## Expected Behavior
Production build not be crashed

## Steps to Reproduce
1. Create a new project using NX 12 with preset React.
2. Build Production using VS Code NX Console Extension
3. Use any webserver to serve the built application.
4. Your web crash when init
`Uncaught TypeError: Object(...) is not a function
    at Module.UXeq (main.4ddf020d5744fe66e375.esm.js:2)
    at l (runtime.365178a7a0f8f038a0f1.js:1)
    at Object.0 (main.4ddf020d5744fe66e375.esm.js:2)
    at l (runtime.365178a7a0f8f038a0f1.js:1)
    at t (runtime.365178a7a0f8f038a0f1.js:1)
    at Array.r [as push] (runtime.365178a7a0f8f038a0f1.js:1)
    at main.4ddf020d5744fe66e375.esm.js:2`
5. Inspect the error line and found that **main.tsx** file is imported as a full path in your pc.

### Environment
  Node : 14.16.0
  OS   : linux x64
  npm  : 6.14.11
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.0.1
  @nrwl/cypress : 12.0.1
  @nrwl/devkit : 12.0.1
  @nrwl/eslint-plugin-nx : 12.0.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.1
  @nrwl/linter : 12.0.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 12.0.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.1
  @nrwl/web : 12.0.1
  @nrwl/workspace : 12.0.1
  @nrwl/storybook : 12.0.1
  @nrwl/gatsby : Not Found
  typescript : 4.1.5

**Comment by dangviettuan** [comment]
After investigate I found that 
In file **packages/web/src/utils/config.ts**: When I run build from NX Console Extension the `configuration` param is `undefined`.
The `envName` value is `undefined` too.
Then I hard code `envName` equal 'production' and my build success.
I have tried in the NX older version (11.4.4) the resolve without hardcode is the same but the build is a success.
PS: the command build when run with NX Console is `nx run center-app:build --extractCss --extractLicenses --no-namedChunks --optimization --outputHashing=all --no-sourceMap --no-vendorChunk`
@jaysoo Do you have any idea?

**Comment by aiji42** [comment]
https://github.com/nrwl/nx/issues/5312#issuecomment-819209407

There seems to be a bug in getting NODE_ENV. To avoid this bug, you need to temporarily set `NODE_ENV=production`.
Since the Nx console does not allow command expansion, it is recommended to run the command like this, although it is tedious. `NODE_ENV=production yarn nx run my-app:build:production`.

**Comment by dangviettuan** [comment]
> [#5312 (comment)](https://github.com/nrwl/nx/issues/5312#issuecomment-819209407)
> 
> There seems to be a bug in getting NODE_ENV. To avoid this bug, you need to temporarily set `NODE_ENV=production`.
> Since the Nx console does not allow command expansion, it is recommended to run the command like this, although it is tedious. `NODE_ENV=production yarn nx run my-app:build:production`.

Ya! I knew how to work around this issue, you can also add `--prod` to build command. But I create it because in the past it working but currently not.

**Comment by vaunus** [comment]
@FrozenPandaz are any of the team looking at this currently? We've just branched to upgrade to NX 11 and then 12 came out during that work so we switched to that but are blocked by this now on our pre-prod environments. I'd rather not modify our CI to work around this if a fix is imminent. 
Happy to help look into this as well and open a PR if someone can point me in the right direction.

**Comment by puku0x** [comment]
#5522 is a fix for this issue. @jaysoo could you take a look the PR because it seems many React users are stuck in v11.

**Comment by Nightbr** [comment]
Hey same issue here, impossible to build my React app with Nx 12. Try all workaround, export `NODE_ENV=production` or add` --prod -c beta` but not working.
Could be great if we could have a fix for this? Ready to help tests & debug it if needed!
