### ISSUE TITLE
Error: 'jsxs' is not exported by node_modules/react/jsx-runtime.js on building publishable react:lib 

### ISSUE THREAD

**Issue by nitesr** [nrwl/nx#5328]
## Current Behavior
I have created a sample nx.dev react application with a publishable react library (ui-public). When I try to build the publishable react library it throws below error

Repo where is the build is failing: https://github.com/nitesr/trynxdev

_nx run ui-public:build 
Bundling ui-public...
Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error during bundle: Error: 'jsxs' is not exported by node_modules/react/jsx-runtime.js
Bundle failed: ui-public_

## Expected Behavior
ui-public build should be successful with appropriate bundles in dist/libs/ui-public folder

## Steps to Reproduce

npx create-nx-workspace reactapp --style=scss --linter=eslint --packageManager=yarn --nx-cloud=false --cli=nx
#<choose react as template and create 'sample' application>
yarn nx generate @nrwl/react:library ui-shared
yarn nx generate @nrwl/react:library ui-public --publishable --importPath @reactapp/sample

#have couple of nested divs in the ui-public.tsx so the babel transform leverages jsxs variable to transform the TSX/JSX file. 
yarn build ui-public

 

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs
_yarn build ui-public
yarn run v1.19.1
warning ../package.json: No license field
$ nx build ui-public

> nx run ui-public:build 
Bundling ui-public...
Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error during bundle: Error: 'jsxs' is not exported by node_modules/react/jsx-runtime.js
Bundle failed: ui-public
Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error during bundle: Error: 'jsxs' is not exported by node_modules/react/jsx-runtime.js
Bundle failed: ui-public
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command._

### Environment
_yarn nx report
yarn run v1.19.1
warning ../package.json: No license field
$ nx report

>  NX  Report complete - copy this into the issue template

  Node : 12.13.1
  OS   : darwin x64
  yarn : 1.19.1
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.0.1
  @nrwl/cypress : 12.0.1
  @nrwl/devkit : 12.0.1
  @nrwl/eslint-plugin-nx : 12.0.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.1
  @nrwl/linter : 12.0.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 12.0.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.1
  @nrwl/web : 12.0.1
  @nrwl/workspace : 12.0.1
  @nrwl/storybook : 12.0.1
  @nrwl/gatsby : Not Found
  typescript : 4.1.5

✨  Done in 0.55s._

**Comment by nitesr** [comment]
this issue got fixed when I updated below code to include 'jsxs' as a namedExports
[package.impl.txt](https://github.com/nrwl/nx/files/6301015/package.impl.txt)



file: reactapp/node_modules/@nrwl/web/src/builders/package/package.impl.js
function: createRollupOptions
commonjs({
                namedExports: {
                    // This is needed because `react/jsx-runtime` exports `jsx` on the module export.
                    // Without this mapping the transformed import `import {jsx as _jsx} from 'react/jsx-runtime'` will fail.
                    'react/jsx-runtime': ['jsx', '**jsxs**'],
                },
            }),

**Comment by puku0x** [comment]
Yes, that's why I made #5294

**Comment by Oersnes** [comment]
I got a similar build error and needed to apply mappings for `'react/jsx-dev-runtime'` as well:

```
namedExports: {
    // This is needed because `react/jsx-runtime` exports `jsx` on the module export.
    // Without this mapping the transformed import `import {jsx as _jsx} from 'react/jsx-runtime'` will fail.
    'react/jsx-runtime': ['jsx', 'jsxs'],
    'react/jsx-dev-runtime': ['jsx', 'jsxs', 'jsxDEV'],
},
```

**Comment by puku0x** [comment]
@Oersnes Oh really? Could you try following code and see whether it works or not?

```ts
namedExports: {
    // This is needed because `react/jsx-runtime` exports `jsx` on the module export.
    // Without this mapping the transformed import `import {jsx as _jsx} from 'react/jsx-runtime'` will fail.
    'react/jsx-runtime': ['jsx', 'jsxs', 'Fragment'],
    'react/jsx-dev-runtime': ['jsxDEV', 'Fragment'],
},
```
Because it seems `react/jsx-dev-runtime` only exports `jsxDEV` and `Fragment`.
```js
/** @license React v17.0.1
 * react-jsx-dev-runtime.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
'use strict';
require("object-assign");
require("react");
exports.Fragment=60107;
if("function"===typeof Symbol&&Symbol.for){
    var a=Symbol.for;
    exports.Fragment=a("react.fragment")
}
exports.jsxDEV=void 0;
```

**Comment by puku0x** [comment]
I got the same error when `compilerOptions.jsx` is set to `react-jsxdev`. Thanks for the info.

![image](https://user-images.githubusercontent.com/2607019/114836954-24427d00-9e0e-11eb-92bc-9e7937dbc944.png)

**Comment by Oersnes** [comment]
@puku0x You are absolutely right. I only needed to add:

```
namedExports: {
    // This is needed because `react/jsx-runtime` exports `jsx` on the module export.
    // Without this mapping the transformed import `import {jsx as _jsx} from 'react/jsx-runtime'` will fail.
    'react/jsx-runtime': ['jsx', 'jsxs', 'Fragment'],
    'react/jsx-dev-runtime': ['jsxDEV', 'Fragment'],
},
```

Thank you for the quick response.

**Comment by puku0x** [comment]
Another solution is to add `react/jsx-runtime` to `options.external` in `workspace.json`

```js
// workspace.json
"targets": {
  "build": {
    "executor": "@nrwl/web:package",
    "outputs": ["{options.outputPath}"],
    "options": {
      "external": [
        "react/jsx-runtime",      // 👈 this to be added
        "react/jsx-dev-runtime",  // this may be needed when `"jsx": "react-jsx"`
        "@emotion/styled/base",   // "/base" should be included to reduce bundle size, for emotion users
      ],
      "rollupConfig": "@nrwl/react/plugins/bundle-rollup",
    }
  }
}
```

Note that `@nrwl/web:package` builder adds `import`s based on your `external` in `workspace.json` and `dependencies` in `package.json`. 
https://github.com/nrwl/nx/blob/master/packages/web/src/builders/package/package.impl.ts#L254-L257
```js
// The output in 'dist/libs/**/*.esm.js'
import _styled from '@emotion/styled/base';
import { jsx } from 'react/jsx-runtime';
import { cx } from '@emotion/css';
```
In this case, you don't need to add `@emotion/css` to `external` if it is already in `dependencies` in `package.json`.

**Comment by dustinlacewell** [comment]
Are the workarounds in this issue really resolutions? (Maybe they are, I'm really asking.)

**Comment by YunhoKim21** [comment]
For me upgrading version of mdx-bundler from 8.x.x to 9.0.1 resolved this issue. Make sure you have the appropriate version of modules.
