### ISSUE TITLE
Cannot migrate to Nx 12.0.2

### ISSUE THREAD

**Issue by DominikPieper** [nrwl/nx#5332]
Good Morning,
I have a problem with migrating to the latest version. Seems like there's a wrong version used in the migration.
The migration is searching for version `12.99.0`

## Current Behavior
Error see below

## Expected Behavior
Migration runs and I'm on version 12.0.2

## Steps to Reproduce
Run `yarn update` or `nx migrate latest`

### Failure Logs

> yarn update                                                                                                                                       1 ↵  10463  08:16:33
> yarn run v1.22.10
> $ nx migrate latest
> Fetching meta data about packages.
> It may take a few minutes.
> Fetching @nrwl/workspace@latest
> 
>  ERROR  The migrate command failed.
> 
> Command failed: yarn add @nrwl/workspace@latest
> error Couldn't find any versions for "@nrwl/cli" that matches "12.99.0"
> Error: Couldn't find any versions for "@nrwl/devkit" that matches "12.99.0"
>     at MessageError.ExtendableBuiltin (/Users/dominikpieper/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/lib/cli.js:721:66)
>     at new MessageError (/Users/dominikpieper/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/lib/cli.js:750:123)
>     at Function.<anonymous> (/Users/dominikpieper/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/lib/cli.js:50546:13)
>     at Generator.next (<anonymous>)
>     at step (/Users/dominikpieper/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/lib/cli.js:310:30)
>     at /Users/dominikpieper/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/lib/cli.js:321:13
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> Error: Couldn't find any versions for "@nrwl/jest" that matches "12.99.0"
>     at MessageError.ExtendableBuiltin (/Users/dominikpieper/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/lib/cli.js:721:66)
>     at new MessageError (/Users/dominikpieper/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/lib/cli.js:750:123)
>     at Function.<anonymous> (/Users/dominikpieper/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/lib/cli.js:50546:13)
>     at Generator.next (<anonymous>)
>     at step (/Users/dominikpieper/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/lib/cli.js:310:30)
>     at /Users/dominikpieper/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/lib/cli.js:321:13
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> Error: Couldn't find any versions for "@nrwl/linter" that matches "12.99.0"
>     at MessageError.ExtendableBuiltin (/Users/dominikpieper/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/lib/cli.js:721:66)
>     at new MessageError (/Users/dominikpieper/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/lib/cli.js:750:123)
>     at Function.<anonymous> (/Users/dominikpieper/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/lib/cli.js:50546:13)
>     at Generator.next (<anonymous>)
>     at step (/Users/dominikpieper/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/lib/cli.js:310:30)
>     at /Users/dominikpieper/.nvm/versions/node/v14.15.4/lib/node_modules/yarn/lib/cli.js:321:13
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> 
> /Users/dominikpieper/Projects/angular/nxext/node_modules/yargs/build/lib/yargs.js:1132
>                 throw err;
>                 ^
> 
> Error: Command failed: /var/folders/cy/_5zxcdzx1t1c6krfsrlsfrym0000gn/T/tmp-15873ZS9MTFYJ8XYb/node_modules/.bin/tao migrate latest
>     at checkExecSyncError (child_process.js:616:11)
>     at Object.execSync (child_process.js:652:15)
>     at Object.handler (/Users/dominikpieper/Projects/angular/nxext/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:87:25)
>     at Object.runCommand (/Users/dominikpieper/Projects/angular/nxext/node_modules/yargs/build/lib/command.js:196:48)
>     at Object.parseArgs [as _parseArgs] (/Users/dominikpieper/Projects/angular/nxext/node_modules/yargs/build/lib/yargs.js:1043:55)
>     at Object.get [as argv] (/Users/dominikpieper/Projects/angular/nxext/node_modules/yargs/build/lib/yargs.js:986:25)
>     at Object.initLocal (/Users/dominikpieper/Projects/angular/nxext/node_modules/@nrwl/cli/lib/init-local.js:24:13)
>     at Object.<anonymous> (/Users/dominikpieper/Projects/angular/nxext/node_modules/@nrwl/cli/bin/nx.js:43:18)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
>   status: 1,
>   signal: null,
>   output: [ null, null, null ],
>   pid: 15875,
>   stdout: null,
>   stderr: null
> }
> error Command failed with exit code 1.
> 

### Environment

>   Node : 14.15.4
>   OS   : darwin x64
>   yarn : 1.22.10
> 
>   nx : Not Found
>   @nrwl/angular : 12.0.0
>   @nrwl/cli : 12.0.0
>   @nrwl/cypress : 12.0.0
>   @nrwl/devkit : 12.0.0
>   @nrwl/eslint-plugin-nx : 12.0.0
>   @nrwl/express : Not Found
>   @nrwl/jest : 12.0.0
>   @nrwl/linter : 12.0.0
>   @nrwl/nest : Not Found
>   @nrwl/next : Not Found
>   @nrwl/node : 12.0.0
>   @nrwl/react : 12.0.0
>   @nrwl/schematics : Not Found
>   @nrwl/tao : 12.0.0
>   @nrwl/web : 12.0.0
>   @nrwl/workspace : 12.0.0
>   @nrwl/storybook : 12.0.0
>   @nrwl/gatsby : Not Found
>   typescript : 4.1.4

**Comment by maxfriedmann** [comment]
Duplicate of https://github.com/nrwl/nx/issues/5333, at least for me.

**Comment by DominikPieper** [comment]
Yes, seems like that. That's why I closed it already. #5329 shows the same behavior/problem.
