### ISSUE TITLE
Too aggressive in failing projects when using strictlyOrderedTargets

### ISSUE THREAD

**Issue by arabull** [nrwl/nx#5354]
## Description
When projects are related and a dependency fails, all projects that have yet to run are skipped and marked as failed, even if they don't depend on the failing project.

For example, assume four projects:
* one
* two
* three
* four

Via implicit dependencies, project "four" depends on project "two", and project "three" depends on project "one".

```
-----   -----
| 2 |   | 1 |
-----   -----
  |       |
-----   -----
| 4 |   | 3 |
-----   -----
```

This creates two silos with no dependencies between them.

Also, the "strictlyOrderedTargets" option is set to `true` in `nx.json` for the `@nrwl/workspace/tasks-runners/default` runner.

Now assume we run a target against all of them and that project "two" fails.

We'd fully expect project "four" to fail because a project upon which it depends failed. But there's no reason either "one" or "three" should fail, yet "three" will always fail because it is slotted to run after "two" because it has a dependency, even though that dependency is unrelated to the failure. *Nx short-circuits and fails everything yet to run, which is too aggressive.*

I have a sample repository at https://github.com/arabull/nx-ordered-failures that illustrates this behavior.

I'm filing this as a feature request as opposed to a bug because I can't in good faith argue that anything is broken. It's definitely sub-optimal, though.

## Motivation

I have a workspace with dozens of projects, many of which have pair dependencies like the pattern described above with one/three and two/four. In other words, I have a bunch of silos in my dependency tree with little to no crossover. If I get a failure in one of my dependencies within one of those silos, every single project that depends on another will fail.

Like so:

```
-----   -----   -----   -----   -----
| X |   | ✔️ |   | ✔️ |   | ✔️ |   | ✔️ |
-----   -----   -----   -----   -----
  |       |       |       |       |
-----   -----   -----   -----   -----
| X |   | X |   | X |   | X |   | X |
-----   -----   -----   -----   -----
```

In this example, we'd expect the depending project in the first silo to fail since its dependency failed, but there's no reason the rest of them should fail. But they do, without even running.

## Suggested Implementation

Unless a project's dependency fails, it should run and pass/fail on its own merits.

**Comment by arabull** [comment]
Would still love to see this addressed.

**Comment by FrozenPandaz** [comment]
This now works. :tada:

https://github.com/FrozenPandaz/nx-bugs/tree/ordered-tasks
