### ISSUE TITLE
Provide more control over what gets cached

### ISSUE THREAD

**Issue by bjornharvold** [nrwl/nx#5357]
## Description
The suggestion would be to have better control over how the cache is created.

## Motivation
Our project contains 1000+ libraries. Our CI server spends 3 hours building our project from scratch. We would like to utilize Nx's cache to lower that number to minutes. When a release is created, we bump the version number of every package.json file. That version bump is enough to invalidate the cache even though the code didn't change at all. We also want to use the semver plugin to generate CHANGELOG.md files for every library. That also invalidates caches even though no code was changed.

## Suggested Implementation
The thought here would be to have a global and package-level ignore list of files and directories. Our project just needs to ignore CHANGELOG.md and package.json to be able to deploy in a few minutes by leveraging the Nx cache our CI saved up from last build. 

## Alternate Implementations
Nx Cloud is not an option for us. Large codebase and low tech budget... Not a good combination

Thank you for creating nx.dev. Truly a must-have for enterprice-level SPA development.

**Comment by gustavobini** [comment]
You might run into a pitfall if you remove `package.json` from resetting the cache. For instance, when a library adds a dependency.

Have you considered not bumping versions if nothing has changed?

**Comment by vsavkin** [comment]
You could add all package.json and changelog files into .nxignore (the format is the same .gitignore). Files listed in .nxignore aren't analyzed and aren't included into the hash. In this case, any changes to those files won't result in a hash invalidation.

**Comment by bjornharvold** [comment]
Thank you @vsavkin! .nxignore is EXACTLY what I was looking for :-)
