### ISSUE TITLE
Issues with ng g (generate) after upgrading to 6.

### ISSUE THREAD

**Issue by a5hik** [nrwl/nx#536]
I had upgraded to nx version 6.0.2 (had to do it manually as the auto update crashed)..  was able to build and serve the app. but the generate command is failing and the logs are not useful to find anything.

Generating an app gives the following error

> ng g app myapp
> ENOENT: no such file or directory, stat '../node_modules/.bin/node-pre-gyp'

Generating a Lib gives the following error.

> ng g lib mylib
>Unexpected token / in JSON at position 93

Generating a Comp gives the below.

> ng g c mycomp 
> Could not find an NgModule. Use the skip-import option to skip importing in NgModule.

**Comment by FrozenPandaz** [comment]
Was there an error when doing `ng add @nrwl/schematics`?

There is an existing issue https://github.com/nrwl/nx/issues/513 in the latest released version but there is already a fix for it.

I am quite sure this is a result of that issue but I guess we could keep this issue open until we retry after it is published.

**Comment by a5hik** [comment]
I have been using `nx` from Version `0.x`. I tried deleting node_modules and it doesn't solved issues.
The problem raised when I tried to update `nx` from `1.03` to `6.0.2`
there was an error happened while running the `update` command.. and the logs below..

> warning Error running install script for optional dependency: "/Users/ashik/WebstormProjects/cn-ui-platform/node_modules/@angular-devkit/core/node_modules/fsevents: Command failed.
Exit code: 6
Command: sh
Arguments: -c node install
Directory: /Users/ashik/WebstormProjects/cn-ui-platform/node_modules/@angular-devkit/core/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.0
node-pre-gyp info using node@9.11.1 | darwin | x64
node-pre-gyp info check checked for \"/Users/ashik/WebstormProjects/cn-ui-platform/node_modules/@angular-devkit/core/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v59-darwin-x64.tar.gz
node-pre-gyp ERR! Completion callback never invoked! 
node-pre-gyp ERR! System Darwin 17.3.0
node-pre-gyp ERR! command \"/usr/local/bin/node\" \"/Users/ashik/WebstormProjects/cn-ui-platform/node_modules/@angular-devkit/core/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/ashik/WebstormProjects/cn-ui-platform/node_modules/@angular-devkit/core/node_modules/fsevents
node-pre-gyp ERR! node -v v9.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
success Saved lockfile.
            Updating karma configuration
            Updating configuration
            Removing old config file (.angular-cli.json)
            Writing config file (angular.json)
            Some configuration options have been changed, please make sure to update any npm scripts which you may have modified.
DELETE .angular-cli.json
CREATE angular.json (59387 bytes)
UPDATE karma.conf.js (1736 bytes)
UPDATE package.json (4398 bytes)
UPDATE tslint.json (3281 bytes)
warning " > angular2-jwt@0.2.3" has incorrect peer dependency "@angular/core@^2.0.0||^4.0.0".
warning " > angular2-jwt@0.2.3" has incorrect peer dependency "@angular/http@^2.0.0||^4.0.0".
warning " > apollo-angular@1.0.1" has unmet peer dependency "apollo-link@^1.0.0".
warning " > apollo-angular-link-http@1.0.2" has unmet peer dependency "apollo-link@^1.0.0".
warning "apollo-angular-link-http > apollo-angular-link-http-common@1.0.0" has unmet peer dependency "apollo-link@^1.0.0".
warning "apollo-angular-link-http > apollo-angular-link-http-common@1.0.0" has incorrect peer dependency "graphql@^0.11.3 || ^0.12.3".
warning " > ng2-codemirror@1.1.3" has incorrect peer dependency "@angular/core@^2.1.0 || ^4.0.0".
warning " > ng2-codemirror@1.1.3" has incorrect peer dependency "@angular/forms@^2.1.0 || ^4.0.Cannot read property 'browserTarget' of undefined
The automatic upgrade to Nx 6 has failed with the following error: Error: Command failed: ng generate @schematics/update:migrate --package @nrwl/schematics --collection @nrwl/schematics/migrations/migrations.json --from 1.0.3 --to 6.0.0.

> You

 can upgrade it manually by running:

* yarn install or npm install
* ng update @angular/cli@6.0.1
* ng update @nrwl/schematics@6.0.0

The upgrade process creates a test target for every library. If you have a library
that does not have specs, either set failOnEmptyTestSuite to false in karma.conf.js of the library,
or remove the test target in angular.json.
Migration 20180515-switch-to-nx6 failed
{ Error: Command failed: ng generate @schematics/update:migrate --package @nrwl/schematics --collection @nrwl/schematics/migrations/migrations.json --from 1.0.3 --to 6.0.0
    at checkExecSyncError (child_process.js:575:11)
    at Object.execSync (child_process.js:612:13)
    at Object.run (/Users/ashik/WebstormProjects/cn-ui-platform/node_modules/@nrwl/schematics/migrations/legacy-migrations/20180515-switch-to-nx6.js:34:29)
    at /Users/ashik/WebstormProjects/cn-ui-platform/node_modules/@nrwl/schematics/src/command-line/update.js:87:25
    at Array.forEach (<anonymous>)
    at run (/Users/ashik/WebstormProjects/cn-ui-platform/node_modules/@nrwl/schematics/src/command-line/update.js:83:16)
    at Object.update (/Users/ashik/WebstormProjects/cn-ui-platform/node_modules/@nrwl/schematics/src/command-line/update.js:19:13)
    at Object.handler (/Users/ashik/WebstormProjects/cn-ui-platform/node_modules/@nrwl/schematics/src/command-line/nx.js:32:81)
    at Object.runCommand (/Users/ashik/WebstormProjects/cn-ui-platform/node_modules/@nrwl/schematics/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/ashik/WebstormProjects/cn-ui-platform/node_modules/@nrwl/schematics/node_modules/yargs/yargs.js:1014:30)
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 46318,
  stdout: null,
  stderr: null }
Please run 'git checkout .'
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c ./node_modules/.bin/nx update
Directory: /Users/ashik/WebstormProjects/cn-ui-platform
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/ashik/WebstormProjects/cn-ui-platform/yarn-error.log".

**Comment by a5hik** [comment]
and moreover the update command updated the configs in `angular.json` for all the `libs` as `apps` so i had to manually change them in to `libs`

**Comment by goelinsights** [comment]
I'm getting a similar issue with ng g. In my case, it looks like it's running a post-install script following an initial successful generation of a (in my case library).  That seems to be messing with node_modules and I have to 
`rm -rf node_modules` to get future generator activity to work again

```
libs/product/product-ui/src/test.ts 3ms
npm WARN rm not removing /Users/vijay/ng2_projects/opslytics/node_modules/.bin/uglifyjs as it wasn't installed by /Users/vijay/ng2_projects/opslytics/node_modules/uglify-js
npm WARN rm not removing /Users/vijay/ng2_projects/opslytics/node_modules/.bin/esgenerate as it wasn't installed by /Users/vijay/ng2_projects/opslytics/node_modules/escodegen
npm WARN rm not removing /Users/vijay/ng2_projects/opslytics/node_modules/.bin/escodegen as it wasn't installed by /Users/vijay/ng2_projects/opslytics/node_modules/escodegen
npm WARN rm not removing /Users/vijay/ng2_projects/opslytics/node_modules/.bin/semver as it wasn't installed by /Users/vijay/ng2_projects/opslytics/node_modules/semver
npm WARN rm not removing /Users/vijay/ng2_projects/opslytics/node_modules/.bin/nopt as it wasn't installed by /Users/vijay/ng2_projects/opslytics/node_modules/nopt
npm WARN rm not removing /Users/vijay/ng2_projects/opslytics/node_modules/fsevents/node_modules/.bin/node-pre-gyp as it wasn't installed by /Users/vijay/ng2_projects/opslytics/node_modules/fsevents/node_modules/node-pre-gyp
npm WARN rm not removing /Users/vijay/ng2_projects/opslytics/node_modules/.bin/esvalidate as it wasn't installed by /Users/vijay/ng2_projects/opslytics/node_modules/esprima
npm WARN rm not removing /Users/vijay/ng2_projects/opslytics/node_modules/.bin/esparse as it wasn't installed by /Users/vijay/ng2_projects/opslytics/node_modules/esprima

> fsevents@1.2.4 install /Users/vijay/ng2_projects/opslytics/node_modules/fsevents
> node install

[fsevents] Success: "/Users/vijay/ng2_projects/opslytics/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote

> uws@9.14.0 install /Users/vijay/ng2_projects/opslytics/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> node-sass@4.9.0 install /Users/vijay/ng2_projects/opslytics/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/vijay/.npm/node-sass/4.9.0/darwin-x64-59_binding.node

> node-sass@4.9.0 postinstall /Users/vijay/ng2_projects/opslytics/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/vijay/ng2_projects/opslytics/node_modules/node-sass/vendor/darwin-x64-59/binding.node
Testing binary
Binary is fine

> @angular/cli@6.0.1 postinstall /Users/vijay/ng2_projects/opslytics/node_modules/@angular/cli
> node ./bin/ng-update-message.js

added 470 packages from 127 contributors, removed 208 packages and updated 1199 packages in 57.064s
[!] 27 vulnerabilities found [29945 packages audited]
    Severity: 1 Low | 26 Moderate
    Run `npm audit` for more detail

Vijays-MacBook-Pro:opslytics vijay$ ng g lib product-form --directory=product
ENOENT: no such file or directory, stat '/Users/vijay/ng2_projects/opslytics/node_modules/loggly/node_modules/request/node_modules/.bin/har-validator'
```

**Comment by vsavkin** [comment]
> and moreover the update command updated the configs in angular.json for all the libs as apps so i had to manually change them in to

This tells me that the upgrade process completely failed. Could you try upgrading again with `@nrwl/schematics@6.1.0-beta.1`? We improved the upgrade process, so it might solve your problem.

**Comment by a5hik** [comment]
I keep getting `No migrations to run` when trying to upgrade from `6.0.2` to latest versions.
I did tried global install of `@nrwl\schematics` as well.

**Comment by a5hik** [comment]
an update to the original issue reported.. (still i'm in version 6.0.2)

Now I'm able to generate new apps.. re installing node_modules seems to be the issue.. but however it is not a straight forward one.. as one of the symlink in .bin of node_modules is pointing to a wrong location.. so I had deleted the .bin dir first and then did the install.. there seems to be some issue in ordering of the install.

Also, not generating the components issue is also resolved after updating my workspace with proper nx expected configs.. 

But I still having the same issue as reported with generating a `lib`

**Comment by FrozenPandaz** [comment]
@a5hik 
Thank you for the thorough debugging. Are all of your issues resolved? I see there are 3 that have been resolved by the recent improvements to update. 

I'm also able to generate a new component in an updated nx workspace. Is there any other issues?

**Comment by a5hik** [comment]
I think this can be closed.
