### ISSUE TITLE
Typescript Barrel files may break Angular Universal (SSR) due to Ivy bundling - enhance documentation

### ISSUE THREAD

**Issue by robertgartman** [nrwl/nx#5365]
# Short version
The NX way of libs with barrel files may result in that your Universal app won't start - and it's hard to figure out why. When you do an import from a lib via the the barrel file (e.g. import { HarmlessModule } from "@whatever/shared/data-access-user"; ) everything exported by the lib's barrel is bundled in your app. That is, if you are compiling with Ivy - more on that topic [here](https://github.com/angular/angular-cli/issues/16799#issuecomment-580912090).
If another (not imported) module in the same lib pulls in a 3d party package, and that package cannot run server side then... fail!
**Suggested improvement: enhance the docs** under "Workspace structure", for example [here](https://nx.dev/latest/angular/structure/creating-libraries), and make it clear that what goes into the lib will drive bundle size and may in some corner cases (such as SSR) cause runtime errors.

# A very verbose version
This is a write-up of our specific case and how we tracked it down - as it may save a day or two if you will find yourself in this situation.

### Background
An enterprise app + website that has evolved from the early AngularJS days and is now running on Angular 11 + Ivy. The website code is served with [Angular Universal](https://angular.io/guide/universal). A while back we decided to adopt NX. And with that comes the work of figuring out how to slice and dice the code into libs and expose this code with barrel files (i.e. index.ts). Our own pre-NX code had no barrel files. Migration of code is done in an iterative way, moving piece by piece of functionality into libs and verifying that it flies.

### Issue
Migrating our website code, running Universal, an import of a very basic module broke the server side code. When starting the application with `ng run website:serve-ssr --configuration=production` it compiled fine and died directly on start with a 6MB (!) log entry. To share the taste of it, here is the start and end of it:

```
Compiled successfully.
/<cut>/angular/dist/website/server/main.js:1
!function(e,a){for(var i in a)e[i]=a[i]}(exports,function(modules){var installedModules={},installedChunks={3:0};function __webpack_require__(moduleId){if(installedModules[moduleId])return installedModules[moduleId].exports;var module=installedModules[moduleId]={i:moduleId,l:!1,exports:{}};return modules[moduleId].call(module.exports,module,module.exports,__webpack_require__),module.l=!0,module.exports}return __webpack_require__.e=function requireEnsure(chunkId){if(0!==installedChunks[chunkId]){var chunk=require("./"+({0:"avt-website-feature-misc",1:"ext",2:"i18n-extra-locales",4:"vendors~avt-website-feature-misc",5:"vendors~i18n-base-locales"}[chunkId]||chunkId)+".js"),moreModules=chunk.modules,chunkIds=chunk.ids;for(var moduleId in moreModules)modules[moduleId]=moreModules[moduleId];for(var i=0;i<chunkIds.length;i++)installedChunks[chunkIds[i]]=0}return Promise.all([])},__webpack_require__.m=modules,__webpack_require__.c=installedModules,__webpack_require__.d=function(exports,name,getter){__webpack_require__.o(exports,name)||Object.defineProperty(exports,name,{enumerable:!0,get:getter})},__webpack_require__.r=function(exports){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(exports,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(exports,"__esModule",{value:!0})},__webpack_require__.t=function(value,mode){if(1&mode&&(value=__webpack_require__(value)),8&mode)return value;if(4&mode&&"object"==typeof value&&value&&value.__esModule)return value;var

<cut>

rid:"layout-grid",layoutGridChar:"layout-grid-char",layoutGridLine:"layout-grid-line",layoutGridMode:"layout-grid-mode",layoutGridType:"layout-grid-type",left:"left",letterSpacing:"letter-spacing",lightingColor:"lighting-color",lineBreak:"line-break",lineHeight:"line-height",listStyle:"list-style",listStyleImage:"list-style-image",listStylePosition:"list-style-position",listStyleType:"list-style-type",margin:"margin",marginBottom:"margi
```

We found this log entry flawed in 3 ways:

1. Length
2. Formatting
3. Lack of information of cause (the log really ends in the middle of a word as above with no more information)

Completely lost...
We tried piping the output to a file hoping some formatting got lost in the VS Code console.
`ng run website:serve-ssr --configuration=production &> /tmp/log.txt`
This payed off in an unexpected way. The error was hidden in the stderr. Note the '&>' and the [impact](https://stackoverflow.com/a/4749356). Why stderr is not part of the VS Code console output is another topic.

So we now had a clue of the issue:
```
ReferenceError: self is not defined
    at Object.SsJP (/<cut>/dist/website/server/main.js:1:3338254)
    at __webpack_require__ (/<cut>/dist/website/server/main.js:1:317)
    at Object.4BGq (/<cut>/dist/website/server/main.js:1:1244897)
    at __webpack_require__ (/<cut>/dist/website/server/main.js:1:317)
    at Object.drFX (/<cut>/dist/website/server/main.js:1:5060028)
    at __webpack_require__ (/<cut>/dist/website/server/main.js:1:317)
    at Module.07Rf (/<cut>/dist/website/server/main.js:1:75944)
    at __webpack_require__ (/<cut>/dist/website/server/main.js:1:317)
    at Object.0 (/<cut>/dist/website/server/main.js:1:72261)
    at __webpack_require__ (/<cut>/dist/website/server/main.js:1:317)

A server error has occurred.
node exited with 1 code.
```
The ´self is not defined' indicates that one of our 3rd party packages was in play. Some of them will not run server side as they reference browser-only objects. Using [Domino](https://github.com/fgnass/domino) might suppress issues like this - we did not try that path. Maybe there is a clue hidden around `main.js:1:3338254`? Arghh, VS Code does not support navigation by character. Plugins exist, though we resorted to bash:
`tail -c +3337000 /<cut>/dist/website/server/main.js | head -c 2000`
And there we found strong evidence of the culprit. A 3rd party package that we can refer to as 'Culprit'.

However - still lost on the root cause. The code modification we did that turned working code into broken code had no imports of the Culprit package. Double check. Tripple Check.

Code analyzers to the rescue. Build the code with `--stats-json`
`ng build website --stats-json`

You'll find the stats.json file under your apps folder (/apps/website/browser/stats.json in our case). There are several candidate analyzer tools. We found https://statoscope.tech/ to be a perfect fit for understanding what/why invited Culprit to the party. Searching in statoscope for the Culrit package and then showing how it was imported revealed this:

```
apps/website/src/main.ts
apps/website/src/app/app.module.ts
apps/website/src/app/app.routes.ts
libs/website/util-core/src/index.ts
libs/website/util-core/src/lib/router-locale.resolver.ts   <-- the change here broke the server side runtime execution
libs/shared/data-access-user/src/index.ts
libs/shared/data-access-user/src/lib/user-catalogue/user-catalogue.service.ts
libs/shared/data-access-culprit/src/index.ts
libs/shared/data-access-culprit/src/lib/culprit.service.ts
```

In here, the lessons learned hides. Our router-locale.resolver.ts imported a harmless and without-side-effects module within our data-access-user library. It was the first time reference of that lib during website-to-NX-migration. The user-catalogue.service.ts wasn't referenced at all in the website code, but seeing that it was imported it explained the dependency on Culprit. Soo... what is happening?

Turns out that by adding something like
`import { HarmlessModule } from "@whatever/shared/data-access-user"; `
then everything exported by the barrel file under data-access-user lib jumps onboard (minus Ivy's tree shaking)

Apparently [by design](https://github.com/angular/angular-cli/issues/16799#issuecomment-580912090)

Coming from Angular pre-Ivy, pre barrel files, this was completely unknown to us.

### Conclusion
The decision of how to organize the libs WILL drive bundle size and MAY even break your code in unforeseen ways.

## Suggestion
Improve documentation - make users aware of the impact

Somewhat related issue: #3426

**Comment by Sam-Lin-MillersLab** [comment]
not stale. still kicking

**Comment by Coly010** [comment]
Thank you very much for pointing this out. 

We are making a new pass of our docs to ensure their quality and improve the information that is available on them.

This does seem to be an issue coming from Angular, so I've made note that we should add a warning in our docs about this and I'll close this issue for now.

Thank you again.
