### ISSUE TITLE
how to invoke custom schematic?

### ISSUE THREAD

**Issue by jasedwards** [nrwl/nx#537]
I followed the directions on your blog on how to create a custom schematic.  The section for invoking the custom schematic however cuts off the command you actually run.  I created a schematic called new-app that I use so teams do not have to remember all the options we enforce for each app.  I then run ng g new-app myapp but an error is thrown stating 'Schematic "new-app" not found in collection @nrwl/schematics'

**Comment by argygkou** [comment]
Try  `npm/yarn  run workspace-schematic new-app {app-name}` and it will run your custom schematics.

**Comment by jasedwards** [comment]
that got it.  thanks @argygkou

**Comment by Nxt3** [comment]
@jasedwards Could I get a link to that article?

**Comment by jasedwards** [comment]
@Nxt3  It is near the bottom 

https://blog.nrwl.io/announcing-nrwl-nx-6-0-29b963d87d8e
