### ISSUE TITLE
[ESLint/VSCode] HTML files not linted in VSCode

### ISSUE THREAD

**Issue by skydever** [nrwl/nx#5371]
## Current Behavior

The **VSCode ESLint** extension does not lint my `html` files, but executing `nx lint my-app` shows errors/warnings for `html` files.

## Expected Behavior

The **VSCode ESLint** extension should show errors/warnings for `html` files.

## Steps to Reproduce

I created a new nx workspace using `npx create-nx-workspace@latest` [here](https://github.com/skydever/nx-lint-html). Clone the repo and open it using **VSCode** having the **ESLint** extension installed.

Open the file `apps\my-app\src\app\app.component.ts` - a lint error will be shown at line 13 (empty lifecycle method)
Open the file `apps\my-app\src\app\app.component.html` - no error, but there should be an error at line 7 (async pipes should not be negated)

***UPDATE***
After some digging I was able to get the error by setting `"eslint.validate": ["html"]` in the `settings.json` of **VSCode**, but as stated [here](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) this should not be necessary:

```
As soon as TypeScript is correctly configured inside ESLint, you no longer need additional configuration through VS Code's eslint.validate setting. The same is true for HTML and Vue.js files.
```

Typescript files are still *found* by **ESLint** after adding `eslint.validate` with `html` only.

Is the TypeScipt ESLint configuration of the nx workspace missing anything?

### Environment

nx: 12.0.6
eslint: 7.24.0
windows 10
node: v12.18.4

**Comment by JamesHenry** [comment]
@skydever If you take a look at the repo that powers the extension you can see that the heuristic for automatically HTML detection is based on usage of the `eslint-plugin-html` plugin:

https://github.com/microsoft/vscode-eslint/blob/e4b2738e713b7523824e0c72166f5cdd44f47052/server/src/eslintServer.ts#L753

That plugin is not really relevant to the angular use-case, the relevant plugin is `@angular-eslint/eslint-plugin-template`. Maybe you could submit a PR to the extension repo adding that to the mapping?
