### ISSUE TITLE
Empty Workspace + Angular app not work

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#5372]
## Current Behavior
Creating an empty workspace and then add an angular app, is not working (same behavior with --cli=nx and --cli=angular)

## Expected Behavior
The angular app should be serve, build, etc

## Steps to Reproduce
- Create a empty workspace
- Run `npm i -D @nrwl/angular`
- Create a angular app
- Run `nx serve your-app`

### Failure Logs
```
Cannot find module 'webpack'
Require stack:
- /Users/.../example-workspace/node_modules/@angular-devkit/build-webpack/src/webpack/index.js
- /Users/.../example-workspace/node_modules/@angular-devkit/build-webpack/src/index.js
- /Users/.../example-workspace/node_modules/@angular-devkit/build-angular/src/browser/index.js
- /Users/.../example-workspace/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /Users/.../example-workspace/node_modules/@angular-devkit/architect/node/index.js
- /Users/.../example-workspace/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
- /Users/.../example-workspace/node_modules/@nrwl/tao/src/commands/run.js
- /Users/.../example-workspace/node_modules/@nrwl/tao/index.js
- /Users/.../example-workspace/node_modules/@nrwl/cli/lib/run-cli.js
```

### Environment
```
 NX  Report complete - copy this into the issue template

  Node : 15.14.0
  OS   : darwin x64
  npm  : 7.9.0
  
  nx : Not Found
  @nrwl/angular : 12.0.6
  @nrwl/cli : 12.0.6
  @nrwl/cypress : 12.0.6
  @nrwl/devkit : 12.0.6
  @nrwl/eslint-plugin-nx : 12.0.6
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.6
  @nrwl/linter : 12.0.6
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.6
  @nrwl/web : Not Found
  @nrwl/workspace : 12.0.6
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

**Comment by FrozenPandaz** [comment]
Hi, I wasn't able to reproduce it with yarn, npm, or pnpm.

Please provide a repo that we can pull down to help reproduce the issue.

**Comment by gperdomor** [comment]
@FrozenPandaz here https://github.com/gperdomor/workspace

**Comment by gperdomor** [comment]
@FrozenPandaz tested with node 14 and npm 6 and works... Node 14 + npm 7 not works, so the problem seems to be with npm7

**Comment by gperdomor** [comment]
@FrozenPandaz was able to check the repo?

**Comment by pgg** [comment]
package-lock.json was the issue for me. tested with both node 14, npm 6 and node 15, npm7

**Comment by Coly010** [comment]
@gperdomor

I cloned your repo and ran `npm install` with NPM 7.

Running `nx serve` afterwards did produce the webpack not found error.

However, as per https://github.com/nrwl/nx/issues/5372#issuecomment-823316271
Deleting package-lock and running `npm install` with NPM 7 again, everything works as expected!

Closing this issue as a resolution has been found
