### ISSUE TITLE
Support Cypress 7.x

### ISSUE THREAD

**Issue by cyrus-za** [nrwl/nx#5382]
The name is pretty clear so not going to say much. Please support cypress 7. It might already natively be supported, but I see that nx repo is still on 6.0.1 so I'd rather not update until this is officially closed by someone in the core team

**Comment by mehrad-rafigh** [comment]
I will take a look at this tonight. Might look like the previous updates, where nx cannot migrate and the developers have to do this by themselves.

**Comment by alexan** [comment]
I have cypress@7.1.0 running with @nrwl/cypress@12.0.8 the only problem I am seeing is @nrwl/cypress is reporting it is not compatible through its [peerDependencies](https://github.com/nrwl/nx/blob/master/packages/cypress/package.json#L35)

**Comment by cyrus-za** [comment]
What's the latest?

**Comment by mehrad-rafigh** [comment]
Sry guys, I will not do the update, since our company and my team are migrating to angular workspaces

**Comment by cyrus-za** [comment]
@mehrad-rafigh why? What does ng workspaces have that nx does not? I am just curious, I am not using angular (for a few years now) so not up to date with that side
