### ISSUE TITLE
SSR with nextjs + nx libs

### ISSUE THREAD

**Issue by cyrus-za** [nrwl/nx#5383]
This probably belongs more in a gh discussion than a bug report, but I wanted to make sure I get this in front of the nx core team.

When using nextjs, all code used inside getStaticProps or getServersideProps get removed from the bundle going to the frontend, which allows one to not run into issues of importing a lib that contains code that will fail in the browser.

The problem is, let's say one has a library called `@org/auth` and is located in `libs/auth`. Let's say there are 2 ts files in `libs/auth/src/lib`. The one is a react hook + context provider for authentication and is meant to be used inside the react app in the browser. The other is a function that is meant to be used server side get get the user from the `req` object by decoding a `JWT` from the headers. Let's say under the hood that this decoding library requires some node modules that are not meant for the browser, e.g. `fs` or `nodemailer` or whatever else. 

Both of these files are exported from `libs/auth/index.ts` and imported from `@org/auth` which `tsconfig.base.json` links to that index.ts file.

When a normal react component imports the `useAuth` hook from `@org/auth` it will throw an error
<img width="946" alt="image" src="https://user-images.githubusercontent.com/1845861/115112307-3e529b80-9f85-11eb-8146-296dbc1d91ef.png">

The way that libraties like [`next-auth`](next-auth.js.org) address this issue is by exporting `next-auth` module and `next-auth/client` module. 

How do we do this in a best-practice way inside `nx`?

Do we create 2 libs and call the one `auth` and the other `auth-client` and then configure their import path in tsconfig to `@org/auth` and `@org/auth/client` to go to the respective lib or is there a better approach? Can we keep it in 1 lib but manually add 2 entries in `tsconfig.base.json` or will this break some of the other nx features like knowing which libs got affected based on imports? Is there a way to make nx play ball with next by configuring the `next.config.js` file to remove certain modules from the browser bundle?

**Comment by kirjai** [comment]
hey @cyrus-za , this is an interesting question.

So there's definitely multiple ways to achieve this. both approaches the you mentioned - creating two libs, and having a single lib, but two entries in `tsconfig.base.json` should both work.

*But* with the latter approach (single lib) you're right in that the affected command will not give you enough granularity. For example, if your apps and libs depend on each other in the following way:

<img width="593" alt="Screenshot 2021-04-30 at 12 37 13" src="https://user-images.githubusercontent.com/9858620/116690100-90ea7980-a9c1-11eb-9855-f5c822688f53.png">

- `react-lib` is a lib that contains both react ui code, as well as server-only code under a different entry point (`/server`)
- assuming that `node-lib` only imports the server entry point of `react-lib`

in that case, making changes to the react UI side of the `react-lib` will still mark `node-lib` as affected.

so it's kind of up to you which of the two approaches fits best.

---

>  Is there a way to make nx play ball with next by configuring the next.config.js file to remove certain modules from the browser bundle?

not sure what do you mean by that? do you mean the nextjs functionality that doesn't bundle dynamic imports?

**Comment by cyrus-za** [comment]
> not sure what do you mean by that? do you mean the nextjs functionality that doesn't bundle dynamic imports?

I mean if there's a lib that uses `fs` from node (or whatever other server-only lib) it would be nice if that code gets stripped by the webpack config. 

If we got a lib that exports multiple modules from its index.ts file and the next-app requires one of those modules, it will automatically import all of them despite only needing one of them and then it will fail at compile time

**Comment by kirjai** [comment]
considering that this behaviour works with Next.js out of the box, this is something we need to look into, so this seems like a bug on our end, you're right

**Comment by cyrus-za** [comment]
yep, it's related to the single index.ts exporting multiple modules, wheras a typical nextjs app would import the file directly and not the entire lib

**Comment by kirjai** [comment]
looks like my previous comment wasn't quite right. after spending some more time with it, i realized that Nx currently behaves the same as Next.js without Nx. Specifically, importing a function from a *file* that has server-side imports and attempting to use it on the client side will error out either way. so i'm back to thinking that this isn't a bug.

In the interest of updating someone who can stumble upon this issue in the future:
I know you've been speaking with some other maintainers of Nx regarding this issue, and correct me if i'm wrong, the following is what's been suggested.

for these cases, you could generate two nested libs.
```
npx nx g @nrwl/workspace:lib browser --directory auth
npx nx g @nrwl/workspace:lib server --directory auth
```

---

if there's something else that i've missed, please mention it here.
