### ISSUE TITLE
sourcemaps not being generated

### ISSUE THREAD

**Issue by cyrus-za** [nrwl/nx#5384]
I am using `@nrwl/next` and for some reason I cannot find a way to generate source maps.

Running `nx serve my-app --sourceMap` does not generate it, neither does `nx build my-app`. In fact, `nx build my-app` only has `package.json`, `public/.gitkeep` and `next.config.json` in the `dist/my-app` directory.

Where are all the nextjs chunks? Do they go in some node_module/next directory or something?

**Comment by kirjai** [comment]
hey @cyrus-za ,

so, after the build `nx build my-app` you should have a `.next` directory in your `dist/apps/my-app` folder. that's where all the next application files are. is it possible that your IDE is hiding it, if you're not seeing it? 

---

i believe nextjs is using inline source maps for development, so you wouldn't really see any `.map` files among the build artefacts, but as far as i can see, they work correctly locally. In the screenshots below, it shows that a `console.log` is coming from the correct `.tsx` file, and has a correct line number:

<img width="490" alt="Screenshot 2021-04-30 at 12 55 38" src="https://user-images.githubusercontent.com/9858620/116691891-2981f900-a9c4-11eb-89e5-918c27a4aa08.png">

<img width="405" alt="Screenshot 2021-04-30 at 12 56 38" src="https://user-images.githubusercontent.com/9858620/116691998-56cea700-a9c4-11eb-99be-90cee2cd6db8.png">

---

if you wanted to generate source map for production, the approach that next.js support works with Nx as well. [Next.js production source maps documentation](https://nextjs.org/docs/advanced-features/source-maps). TLDR, just add `productionBrowserSourceMaps: true` to your application's `next.config.js` and you should be good to go

**Comment by cyrus-za** [comment]
its not just in my IDE. runnign `ls -a` also does not show it.

**Comment by h-jennings** [comment]
I'm running into this issue as well. Specifically, source maps are _not_ being generated in **development mode**. The suggestions posted are referring to source maps in production mode, which is a different scenario.

Steps to reproduce:
1.  `npx create-nx-workspace happynrwl` (select nextjs app)
2. `cd happynrwl`
3. `npm start` (runs the default app in development mode)
4. Place a debugger anywhere in the app and you'll notice in the browser that source maps aren't generated

**Comment by h-jennings** [comment]
@cyrus-za Were you ever able to resolve this issue?

**Comment by kirjai** [comment]
Looks like source maps during dev is already being tracked in #6788

**Comment by nemonemi** [comment]
I'm experiencing source map issues with nx react. https://github.com/nrwl/nx/issues/7125

**Comment by nzpopa** [comment]
Wow why is this closed ? Is no one using NX + Next in production with Sentry? How are we able to debug issues without source maps ? 

```
const nxNextConfig = {
  nx: {
    svgr: false,
  },
  swcMinify: true,
  images: {
    domains: ['t.me'],
  },
  generateBuildId: async () => {
    return `${buildNumber}`
  },
  productionBrowserSourceMaps: true,
}

return withSentryConfig(
    withPWA({
      ...withNx(nextConfig),
      pwa: {
        dest: 'public',
        runtimeCaching,
      },
    }),
    {
      release: `${buildNumber}`,
    },
  )
```

This is my config and no source maps are being generated at build. Would highly appreciate a fix for this

**Comment by Furizaa** [comment]
After a day of digging I figured out that source maps only work properly if the projects setup is in the default `apps/` and `libs/` schema.

We've migrated a large lerna project to NX and kept every package in `packages/` for the time beeing which works well with small config adjustments - except for source maps.

I tried to dig into the code to figure out why that happens but couldn't find any obvious reason like a hard-coded value.

**Comment by vppics** [comment]
Any update on this? Production source maps are not being generated.

**Comment by tlehwalder** [comment]
> Wow why is this closed ? Is no one using NX + Next in production with Sentry? How are we able to debug issues without source maps ?
> 
> ```
> const nxNextConfig = {
>   nx: {
>     svgr: false,
>   },
>   swcMinify: true,
>   generateBuildId: async () => {
>     return `${buildNumber}`
>   },
>   productionBrowserSourceMaps: true,
> }
> 
> return withSentryConfig(
>     withPWA({
>       ...withNx(nextConfig),
>       pwa: {
>         dest: 'public',
>         runtimeCaching,
>       },
>     }),
>     {
>       release: `${buildNumber}`,
>     },
>   )
> ```
> 
> This is my config and no source maps are being generated at build. Would highly appreciate a fix for this

Have you found a solution?

Any updates on this?

**Comment by maninacan** [comment]
I am using NX 15.8.9 + @nrwl/react and my dev source maps are not being generated.  Could use some help.

**Comment by gpodliegaiev** [comment]
> I am using NX 15.8.9 + @nrwl/react and my dev source maps are not being generated. Could use some help.

add `"sourceMap": true` to tsconfig.json, it is not extended from the root
