### ISSUE TITLE
Show full error details when "nx run" or "nx run-many" fails

### ISSUE THREAD

**Issue by kenptr** [nrwl/nx#5388]
## Description

Consider showing full error details when "nx run <cmd>" fails. Currently we run `nx affected --target=build` in our CI, sometimes it fails and shows this message:

![https://i.ibb.co/wrKhTX6/Screen-Shot-2021-04-18-at-7-33-48-PM.png](https://i.ibb.co/wrKhTX6/Screen-Shot-2021-04-18-at-7-33-48-PM.png)

(In this particular case, retrying fixed the issue. But I don't like that `nx run` is flaky)

## Motivation

Just showing which component failed is good for local debugging, because it's easy to run again and test. But in CI environment, it's not that easy.

## Suggested Implementation

If there is an error, print all the error logs instead of silencing them. Capture all the logs from subprocesses/threads, then, if there is an error, just print them.

## Alternate Implementations

Add more documentation details to `--verbose` and use this to print error details

**Comment by kenptr** [comment]
Running with `--verbose` didn't show error details:

```
> nx run admin:build:production
Nx could not find process's output. Run the command without --parallel.

>  NX   ERROR  Running target "build" failed

  Failed projects:

  - admin

  You can isolate the above projects by passing: --only-failed


real	7m13.992s
user	9m49.527s
sys	0m17.864s
```

**Comment by kenptr** [comment]
I did small experiment. Looks like 2 extra terser plugins reduce final bundle size from 2.0M to 1.9M, but add extra 188s (5x times slow).

**Packages:** react, antd, firebase, apollo, and some more

**Command:** `time nx run admin:build:production --verbose --skip-nx-cache`

**Custom webpack configuration, optimization=true, 2 terser plugins are removed**

Time: 45.76s

```
❯ ls -lah dist/apps/admin
total 22960
drwxr-xr-x   5 ken  staff   160B Apr 18 22:25 assets
-rw-r--r--   1 ken  staff   593B Apr 18 22:25 index.html
-rw-r--r--   1 ken  staff   2.0M Apr 18 22:25 main.1db5a5f5072b44caec84.esm.js
-rw-r--r--   1 ken  staff   7.8M Apr 18 22:25 main.1db5a5f5072b44caec84.esm.js.map
-rw-r--r--   1 ken  staff    79K Apr 18 22:25 polyfills.4c7aec88bcb295b780aa.esm.js
-rw-r--r--   1 ken  staff   389K Apr 18 22:25 polyfills.4c7aec88bcb295b780aa.esm.js.map
-rw-r--r--   1 ken  staff   1.5K Apr 18 22:25 runtime.7b550c4ecb2a593f9f1c.js
-rw-r--r--   1 ken  staff   8.1K Apr 18 22:25 runtime.7b550c4ecb2a593f9f1c.js.map
-rw-r--r--   1 ken  staff   489K Apr 18 22:25 styles.11dfca914847fa168d29.css
-rw-r--r--   1 ken  staff   177K Apr 18 22:25 styles.11dfca914847fa168d29.css.map
```

**Default webpack configuration, optimization=true, @nrwl/react/plugins/webpack**

Time: 233.86s

```
❯ ls -lah dist/apps/admin
total 22784
drwxr-xr-x   5 ken  staff   160B Apr 18 22:30 assets
-rw-r--r--   1 ken  staff   593B Apr 18 22:30 index.html
-rw-r--r--   1 ken  staff   1.9M Apr 18 22:30 main.7138825ca38755728d13.esm.js
-rw-r--r--   1 ken  staff   7.7M Apr 18 22:30 main.7138825ca38755728d13.esm.js.map
-rw-r--r--   1 ken  staff    79K Apr 18 22:30 polyfills.af4b9a1dcbf09abb404f.esm.js
-rw-r--r--   1 ken  staff   388K Apr 18 22:30 polyfills.af4b9a1dcbf09abb404f.esm.js.map
-rw-r--r--   1 ken  staff   1.5K Apr 18 22:30 runtime.365178a7a0f8f038a0f1.js
-rw-r--r--   1 ken  staff   8.0K Apr 18 22:30 runtime.365178a7a0f8f038a0f1.js.map
-rw-r--r--   1 ken  staff   489K Apr 18 22:30 styles.11dfca914847fa168d29.css
-rw-r--r--   1 ken  staff   177K Apr 18 22:30 styles.11dfca914847fa168d29.css.map
```

**Comment by vsavkin** [comment]
This is most likely because webpack runs out of memory and the process gets terminated. This is an issue with webpack and the typescript type checking. If you run without --parallel you might be able to see some messages printed out before the process crashes, but it depends on many things. 

You can try running the command with --maxWorkers=1, this should drastically reduce the number of workers used for type checking.

**Comment by kenptr** [comment]
I removed parallel, and using solution in #5370 to improve build time. Will update if it still fails. Thanks!

**Comment by npwork** [comment]
facing the same issue on 13.10.1 

<img width="1169" alt="Screen Shot 2022-04-19 at 5 51 58 PM" src="https://user-images.githubusercontent.com/1792720/164032643-93d4751b-0885-47f8-a19c-135ff5a427b3.png">
