### ISSUE TITLE
Support folders (or even globs) in `implicitDependencies` map

### ISSUE THREAD

**Issue by laSinteZ** [nrwl/nx#5389]
## Description
Right now, `implicitDependencies` only supports files (like `workspace.json` and so on). __Maybe__ it is worth adding support to passing a folder there
## Motivation
It could be useful if we want to trigger a rebuild of all apps if, for example, any of `.github/workflows/` files had changed.

## Suggested Implementation
Not sure, to be hones. I guess it might slow down the implementation since it will need to check all the files in folder.

## Alternate Implementations
At least it might be worthy to mention in doc that `implicitDependencies` supports files only. I didn't find a mention of it there (I could help with docs if needed).

**Comment by glafxdev** [comment]
@laSinteZ globs are already supported. Check the docs here: https://nx.dev/latest/angular/core-concepts/configuration#implicit-dependencies
```
{
  "implicitDependencies": {
    "angular.json": "*",
    ....
    "styles/**/*.css": ["myapp"]
  }
}
```

**Comment by bekos** [comment]
@laSinteZ globs are already supported. Check the docs here: https://nx.dev/latest/angular/core-concepts/configuration#implicit-dependencies
```
{
  "implicitDependencies": {
    "angular.json": "*",
    ....
    "styles/**/*.css": ["myapp"]
  }
}
```

**Comment by laSinteZ** [comment]
@bekos thank you, I guess I am blind :D closing this issue.
