### ISSUE TITLE
ES5 Build  is created despite correct browserlist configuration preventing it

### ISSUE THREAD

**Issue by KeKs0r** [nrwl/nx#5392]
## Current Behavior
We have a browserlistsrc with the following configuration:
```
supports es6-module
```
When building our React Frontend, the ES5 build is still generated, although the browserlist configuration should prevent it.

## Expected Behavior
When building only for targets that support es6 modules, the es5 build should be skipped

## Potential Culprit
I tried to debug this and it seems that its from the fact that the `caniuse-lite` package is not up to date. Browserlist does a query to get all browsers that DO support `es6-module`. But when checking for wether we need to build for es5, x uses the `caniuse-lite` package to determine if a package supports `es6-module`. The problem  now arises if there are new browser versions that browserlist knows about but `caniuse-lite` does not YET know about it. 

In my current case the featureStatus for the following browsers is not found
```
[
  'and_chr 89',        'and_ff 86',
  'android 89',        'chrome 93',
  'chrome 92',         'chrome 91',
  'chrome 90',         'edge 90',
  'edge 89',           'edge 88',
  'edge 87',           'firefox 89',
  'firefox 88',        'firefox 87',
  'firefox 86',        'firefox 85',
  'ios_saf 14.0-14.5', 'opera 73',
  'samsung 13.0'
]
```

I think a temporary fix would be to update `caniuse-lite` but its not really a sustainable solution, since the same issue would arise again in a few weeks.

## Steps to Reproduce

Use browserlistrc with the following content:
```
supports es6-module
```

### Environment

```
  Node : 12.16.1
  OS   : darwin x64
  yarn : 1.22.5
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.0.20
  @nrwl/cypress : 11.0.20
  @nrwl/devkit : 11.0.20
  @nrwl/eslint-plugin-nx : 11.0.20
  @nrwl/express : 11.0.20
  @nrwl/jest : 11.1.1
  @nrwl/linter : 11.0.20
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.0.20
  @nrwl/react : 11.0.20
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.20
  @nrwl/web : 11.0.20
  @nrwl/workspace : 11.0.20
  typescript : 4.2.3
```

**Comment by KeKs0r** [comment]
It turns out, there is a command to update caniuse lite, that needs to be run in userland:
```
npx browserslist@latest --update-db
```

The issue is, most users would not be aware of the issue (an additional build creeping up on them). I am not sure whether there is a good way to detect the issue in NX and to nudge the user towards running the command.

**Comment by ShayDavidson** [comment]
Even after running `npx browserslist@latest --update-db` it still happens to us as well.

Can we provide a way to devs to bypass this check https://github.com/nrwl/nx/blob/d007d37fb4f625fc4854d06d2e083ed778d6a3db/packages/web/src/utils/third-party/utils/build-browser-features.ts#L45 so we don't rely on `browserlistrc`?

**Comment by WolfspiritM** [comment]
We had this issue aswell. "npx browserslist" also showed the wrong versions when run in the app directory.
I have the feeling NX is generating wrong files there.

Make sure that you have a ".browserslistrc" not a ".browserlistrc" (note the additional "s" after browser). After renaming it the correct browsers were listed with "npx browserslist"

The docs here are using the wrong filename https://nx.dev/latest/react/guides/browser-support

**Comment by hakimio** [comment]
This is not only issue with React. `.browserslistrc` is not respected in Angular project as well. Tried all the proposed solutions. Nothing seems to work. Spelling of the filename is correct and it contains correct list of [ES6] browsers. `Nx` disregards the browser list and still always builds ES5 bundle.
@brandonroberts  Can you fix this bug?

**Comment by hakimio** [comment]
Ok, finally found out that my issue was unrelated to Nrwl Nx. It was an issue with `caniuse-lite` package.
Thank you @Adam-Michalski for providing solution.
[More info](https://github.com/angular/angular-cli/issues/19060#issuecomment-709826944)
