### ISSUE TITLE
Jest builder fails if the config file is written in TypeScript

### ISSUE THREAD

**Issue by tmercswims** [nrwl/nx#5394]
## Current Behavior
As of [this pull request](https://github.com/facebook/jest/pull/10564), released in [Jest 26.6.0](https://github.com/facebook/jest/releases/tag/v26.6.0), Jest supports writing config files in TypeScript (e.g. `jest.config.ts`). However, when I attempt to do this in an Nx project, it does not work.

Pointing the `@nrwl/jest:jest` builder at a TypeScript Jest config results in an error which I think originates from TypeScript itself, complaining about how the config file is not inside a module:
```sh
$ nx run exchange-api:test
Cannot use import statement outside a module
```
Interestingly, if I bypass Nx altogether and invoke Jest directly, pointing to that same config file with zero other changes, it works as expected:
```sh
$ jest --config ./apps/exchange/api/jest.config.ts
# works...
```
So that, of course, leads me to believe that Nx is doing something incorrectly when it comes to passing the config on to Jest.

## Expected Behavior
I expect that pointing Nx to my `jest.config.ts` should work.

## Steps to Reproduce
The general idea is pretty straightforward: Point the `@nrwl/jest:jest` builder at a Jest config which is written in TypeScript. My particular setup looks something like this:

`jest.config.ts`:
```ts
import { Config } from '@jest/types';

const config: Config.InitialOptions = {
  displayName: 'exchange-api',
  preset: '@nrwl/jest/preset',
  globals: {
    'ts-jest': {
      tsConfig: '<rootDir>/tsconfig.spec.json',
    },
  },
  coverageDirectory: '<rootDir>/coverage/',
  coverageThreshold: {
    global: {
      functions: 99,
      branches: 97,
      lines: 99,
      statements: 0,
    },
  },
};

export = config;
```

`tsconfig.spec.json`:
```json
{
  "extends": "./tsconfig.json",
  "include": [
    "./test/**/*.ts"
  ]
}
```

builder definition:
```json
"test": {
  "builder": "@nrwl/jest:jest",
  "options": {
    "jestConfig": "apps/exchange/api/jest.config.ts",
    "passWithNoTests": true
  }
}
```

### Failure Logs
```
$ nx run exchange-api:test
Cannot use import statement outside a module

>  NX   CLOUD  See run details at ...
```
### Environment
```
>  NX  Report complete - copy this into the issue template

  Node : 14.16.0
  OS   : win32 x64
  yarn : 1.22.5

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.4.0
  @nrwl/cypress : 11.4.0
  @nrwl/devkit : 11.4.0
  @nrwl/eslint-plugin-nx : 11.4.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.4.0
  @nrwl/linter : 11.4.0
  @nrwl/nest : 11.4.0
  @nrwl/next : Not Found
  @nrwl/node : 11.4.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.4.0
  @nrwl/web : Not Found
  @nrwl/workspace : 11.4.0
  typescript : 4.1.5
```

**Comment by mheob** [comment]
I ran into the same problem today. Is there an implementation planned to use a typed configuration of Jest?

**Comment by FrozenPandaz** [comment]
Typescript config files will soon be supported by `@nrwl/jest:jest` :tada: 

However, I would recommend holding off on changing them just yet because our automated migrations will not work.

**Comment by demisx** [comment]
Is there any update when the workspace root `jest.config.ts` and `jest.config.ts` will be generated and supported by Nx? `v13.x`?
