### ISSUE TITLE
The cli getting-started page does not provide instructions on how to install the cli

### ISSUE THREAD

**Issue by whitneyit** [nrwl/nx#5395]
## Current Behavior

No instructions can be found on the [getting-started](https://nx.dev/latest/node/getting-started/nx-cli) page.

## Expected Behavior

I expect instructions on how to install the cli to be listed.

I do not know if this is a regression. I also do not know if there are, or, ever were instructions elsewhere on the documentation pages.

## Steps to Reproduce

Go to the [getting-started](https://nx.dev/latest/node/getting-started/nx-cli) page and look for instructions to install the cli.

**Comment by bcabanes** [comment]
Hi @whitneyit and thank you for the issue! We revamps our documentation and have now a dedicated section to [how to setup Nx and create new workspace](https://nx.dev/getting-started/nx-setup#install-nx-cli).

I'll be closing this issue, feel free to create a new one if you feel it can be improved!
