### ISSUE TITLE
Missing nx.deps.json for TSLint

### ISSUE THREAD

**Issue by mserwicki** [nrwl/nx#5399]
## Current Behavior

The tslint script fails when I'm trying to lint files in my custom directory inside the nx workspace.
It appears the nxdeps.json file is missing in the node_modules/.cache directory.
The problem is disappearing when I do run nx dep-graph or nx lint,

Almost The same issue was reported and described in #5299 for eslint and was fixed in https://github.com/nrwl/nx/pull/5307/files

But for TSLint, it is coming from file https://github.com/nrwl/nx/blob/master/packages/workspace/src/tslint/nxEnforceModuleBoundariesRule.ts
I do believe that the same logic can be applied to this file to fix it

## Expected Behavior

The tslint should still work when the  file `nxdeps.json`  does not exist.

## Steps to Reproduce

https://github.com/nrwl/nx-examples/pull/141

```
rm -rf node_modules/.cache
npx tslint -p tsconfig.base.json
```

### Failure Logs

```
TypeError: Cannot read property 'nodes' of null
    at new Rule (.....\node_modules\@nrwl\workspace\src\tslint\nxEnforceModuleBoundariesRule.js:30:115)
```

### Environment

```
  Node : 14.16.0
  OS   : win32 x64
  npm  : 6.14.11

  nx : Not Found
  @nrwl/angular : 12.0.7
  @nrwl/cli : 12.0.7
  @nrwl/cypress : 12.0.7
  @nrwl/devkit : 12.0.7
  @nrwl/eslint-plugin-nx : 12.0.7
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.7
  @nrwl/linter : 12.0.7
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.7
  @nrwl/web : Not Found
  @nrwl/workspace : 12.0.7
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.0.7
```

**Comment by cakeinpanic** [comment]
experiencing same problem

**Comment by vsavkin** [comment]
Thank you for reporting the issue. Fixed it here: https://github.com/nrwl/nx/commit/c41968648a7874c0a03e5523048fa19bf3066011
