### ISSUE TITLE
Allow using html-webpack-plugin in webpack build

### ISSUE THREAD

**Issue by ericyd** [nrwl/nx#5407]
## Description

Nx writes an `index.html` file to the outputPath when running `nx build` on a React app. (Probably other frameworks too, but have no personally confirmed). The index.html file [is written here](https://github.com/nrwl/nx/blob/5ad1a61a7ab5c9a99905d9f5e18e3ea22921eb96/packages/web/src/builders/build/build.impl.ts#L189-L202) - and although it is inside a conditional, that conditional is always truthy due to [the webpack normalization](https://github.com/nrwl/nx/blob/5ad1a61a7ab5c9a99905d9f5e18e3ea22921eb96/packages/web/src/utils/normalize.ts#L148-L154).

It would be really nice if Nx could expose an option to the `build` executor to which allows consumers to skip writing the Nx `index.html`.

## Motivation

The `index.html` generated by Nx is sufficient for most cases, but some requirements call for using the [`html-webpack-plugin`](https://github.com/jantimon/html-webpack-plugin/), or any plugins that depend on that plugin (e.g. [`csp-html-webpack-plugin`](https://github.com/slackhq/csp-html-webpack-plugin)).

Unfortunately, there is no way to avoid overwriting the output from html-webpack-plugin with the output from Nx. The only way I was able to achieve this goal is to add a bogus path to the `options.outputPath` in `workspace.json`, and then manually set the path to my desired output path in my `webpack.config.js`. This is hardly ideal.

## Suggested Implementation

Add an option to the build schema which can skip writing the index.html file. The default should be "false" so that by default, existing behavior is kept intact and the `index.html` file is generated.

## Alternate Implementations

N/A

**Comment by jaysoo** [comment]
merged in https://github.com/nrwl/nx/pull/5843
