### ISSUE TITLE
@nrwl/nextjs issue

### ISSUE THREAD

**Issue by vasuneet** [nrwl/nx#5408]
## Current Behavior

I wanted to use customServer in nextjs app. So to do that i am providing 
customerServerPath = path to server.js in my app

Server.js is as below :

import next from 'next';
import express from 'express';

const port = parseInt(process.env.PORT, 10) || 3000;
const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
const handle = app.getRequestHandler();

app.prepare().then(() => {
  const server = express()
  //server.use('/','../../dist/apps/app-shell-ssr/.next/server')
  server.get('/a', (req, res) => {
    return app.render(req, res, '/a', req.query)
  })

  server.get('/b', (req, res) => {
    return app.render(req, res, '/b', req.query)
  })

  server.all('*', (req, res) => {
    return handle(req, res)
  })

  server.listen(port, (err) => {
    if (err) throw err
    console.log(`> Ready on http://localhost:${port}`)
  })
})

Giviing Error:

Cannot use import statement outside a module

If I use require instead of import 

Giving Error:

require(...) is not a function.

Can you help here

## Expected Behavior
No error should be reported in console and custom server should work fine.
nx build <myapp> is working fine.

but when i try to run ng serve with custom server it gives error.

## Steps to Reproduce
generate nextjs app using generator and use the mentioned server file.

### Failure Logs
already provided details above

### Environment

>  NX  Report complete - copy this into the issue template

  Node : 14.16.1
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.0.7
  @nrwl/cypress : 12.0.7
  @nrwl/devkit : 12.0.7
  @nrwl/eslint-plugin-nx : 12.0.7
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.7
  @nrwl/linter : 12.0.7
  @nrwl/nest : Not Found
  @nrwl/next : 12.0.8
  @nrwl/node : Not Found
  @nrwl/react : 12.0.7
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.7
  @nrwl/web : 12.0.7
  @nrwl/workspace : 12.0.7
  @nrwl/storybook : 12.0.7
  @nrwl/gatsby : Not Found
  typescript : 4.1.5

package.json

{
  "name": "app-shell-workspace",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "nx": "nx",
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test",
    "lint": "nx workspace-lint && nx lint",
    "e2e": "nx e2e",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint": "nx affected:lint",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected": "nx affected",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "update": "nx migrate latest",
    "workspace-generator": "nx workspace-generator",
    "dep-graph": "nx dep-graph",
    "help": "nx help"
  },
  "private": true,
  "dependencies": {
    "@types/express": "^4.17.11",
    "core-js": "^3.6.5",
    "document-register-element": "1.13.1",
    "express": "^4.17.1",
    "next": "10.1.3",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "regenerator-runtime": "0.13.7",
    "styled-jsx": "3.4.4",
    "tslib": "^2.0.0"
  },
  "devDependencies": {
    "@babel/core": "7.12.13",
    "@babel/preset-env": "7.12.13",
    "@babel/preset-react": "7.12.13",
    "@babel/preset-typescript": "7.12.13",
    "@nrwl/cli": "12.0.7",
    "@nrwl/cypress": "12.0.7",
    "@nrwl/eslint-plugin-nx": "12.0.7",
    "@nrwl/jest": "12.0.7",
    "@nrwl/linter": "12.0.7",
    "@nrwl/next": "^12.0.8",
    "@nrwl/react": "12.0.7",
    "@nrwl/tao": "12.0.7",
    "@nrwl/web": "12.0.7",
    "@nrwl/workspace": "12.0.7",
    "@testing-library/react": "11.2.6",
    "@types/jest": "26.0.8",
    "@types/node": "14.14.33",
    "@types/react": "17.0.3",
    "@types/react-dom": "17.0.3",
    "@types/styled-jsx": "2.2.8",
    "@typescript-eslint/eslint-plugin": "4.19.0",
    "@typescript-eslint/parser": "4.19.0",
    "babel-jest": "26.2.2",
    "cypress": "^6.0.1",
    "dotenv": "8.2.0",
    "eslint": "7.22.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsx-a11y": "6.4.1",
    "eslint-plugin-react": "7.23.1",
    "eslint-plugin-react-hooks": "4.2.0",
    "jest": "26.2.2",
    "prettier": "2.2.1",
    "ts-jest": "26.4.0",
    "ts-node": "~9.1.1",
    "typescript": "~4.1.4"
  }
}

**Comment by kirjai** [comment]
hey @vasuneet , thanks for filing the issue!

so, how custom servers work with Nx is a bit different to how they work in plain Next.js. we do some of the work for you. the main difference is that you need to export a function from your custom server file:

```
module.exports = (nextApp, nextServerOptions, proxyConfiguration) => {}
```

as a result, you don't need to import and call `next` yourself. you should use the next app that is provided as a first argument (`nextApp` in the code snippet above)

and secondly, you should use the `require` syntax in your server.

---

we are actually reviewing how custom servers work with Next.js and Nx, and are looking to potentially align ourselves closer to how Next.js does it. but until that's changed - the advice above stands. hope it helps!

**Comment by vasuneet** [comment]
Its not working. I replaced my server.js with the following code :


#################
module.exports = (next, nextServerOptions, proxyConfiguration) => {


const express = require('express');

const port = parseInt(process.env.PORT, 10) || 3000;
const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
const handle = app.getRequestHandler();

app.prepare().then(() => {  
  const server = express();
  
  //server.use('/','../../dist/apps/app-shell-ssr/.next/server')
  server.get('/a', (req, res) => {
    return app.render(req, res, '/a', req.query)
  })

  server.get('/b', (req, res) => {
    return app.render(req, res, '/b', req.query)
  })

  server.all('*', (req, res) => {
    console.log(__dirname);
    return handle(req, res)
  })

  server.listen(port, (err) => {
    if (err) throw err
      console.log(`> Ready on http://localhost:${port}`)
    })
  })


}

**Comment by vasuneet** [comment]
Still giving the following issue :   


Cannot use import statement outside a module

**Comment by vasuneet** [comment]
I got it working. you mean app should be replaced by nextApp and I should not initiate it.

**Comment by vasuneet** [comment]
How I am gonna make it work for nx build. It is working for nx serve with customServerPath

**Comment by kirjai** [comment]
regarding using it with `nx build` - there's an open issue for that already - https://github.com/nrwl/nx/issues/3199 so it's on our radar

**Comment by vasuneet** [comment]
the mentioned issue is resolved targetted to this issue. issue is still there.
