### ISSUE TITLE
ng add @nrwl/schematic do not create the nx script entries to existent project

### ISSUE THREAD

**Issue by cvgaviao** [nrwl/nx#541]
When we create a nx workspace using the `create-nx-workspace myworkspacename` many script entries are created in the `package.json`.

But if we use the `ng add @nrwl/schematic` command to add nx support to an existent project created previously by angular-cli those script entries are not being created.

===

Also, it is not being added this:

> "cli": {
    "warnings": {
      "typescriptMismatch": false,
      "versionMismatch": false
    },
    "defaultCollection": "@nrwl/schematics"
  }

**Comment by FrozenPandaz** [comment]
Was there an error when doing `ng add @nrwl/schematics`?

There is an existing issue https://github.com/nrwl/nx/issues/513 in the latest released version but there is already a fix for it.

**Comment by cvgaviao** [comment]
@FrozenPandaz, I was not able to view any error message.
It was as a normal procedure and the files was created ok.

**Comment by FrozenPandaz** [comment]
@cvgaviao 

This issue is relatively old and seems to be working now. Please try with the latest version and we can reopen this issue if it is still an issue.

**Comment by huy-iwa** [comment]
When I tried to `ng add @nrwl/schematic` into existing project using angular 5.2.1 and lastest angular cli as below:

```
Angular CLI: 7.3.1
Node: 11.9.0
OS: darwin x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.6
@angular-devkit/build-angular      0.10.6
@angular-devkit/build-optimizer    0.10.6
@angular-devkit/build-webpack      0.10.6
@angular-devkit/core               7.0.6
@angular-devkit/schematics         7.3.1
@angular/cdk                       6.0.0-beta.2
@angular/cli                       7.3.1
@angular/flex-layout               2.0.0-beta.12
@angular/material                  6.0.0-beta.2
@angular/material-moment-adapter   5.1.0
@ngtools/webpack                   7.0.6
@schematics/angular                7.3.1
@schematics/update                 0.13.1
rxjs                               5.5.6
typescript                         2.5.3
webpack                            4.19.1
```

I got the same issue like above @cvgaviao 
And another thing I notice: 

````
+ @nrwl/schematics@7.5.2
added 50 packages from 35 contributors and audited 47132 packages in 8.45s
found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
Installed packages for tooling via npm.
Two or more projects are using identical roots. Unable to determine project using current working directory. Using default workspace project instead.
? What is the npm scope you would like to use for your Nx Workspace?
    Path: src/karma.conf.js does not exist
    Renamed src/tsconfig.app.json -> apps/fuse2/tsconfig.app.json
    Renamed src/tsconfig.spec.json -> apps/fuse2/tsconfig.spec.json
    Path: src/tslint.json does not exist
    Renamed src -> apps/fuse2/src
    Path:  does not exist
Path:  does not exist

````

What does `Path` mean ?
