### ISSUE TITLE
Ability to pass Cypress tag flag for CI runs

### ISSUE THREAD

**Issue by bloodmadridista** [nrwl/nx#5413]
Currently, there is no ability to pass the tag flag to Cypress so CI runs get tagged on the Cypress Dashboard

https://docs.cypress.io/guides/guides/command-line#cypress-run-tag-lt-tag-gt

**Comment by antonyfuentes** [comment]
Any news around this? in my team, we rely heavily on tags to organize most of our test runs. The lack of this feature in NX is causing us headaches.

**Comment by KeylinHidalgoBarrios** [comment]
Following up on this, my team is also waiting for this to be fixed ASAP please.

**Comment by bloodmadridista** [comment]
Closing since [this commit](https://github.com/nrwl/nx/commit/240da9a43cf48d46c5bba017c2afa3646709825e#diff-ce79d55185c3d4fbd2ad5caeeebb5248a037789d439740c4d6373a9d1e5257fd) should address this issue.

**Comment by cakeinpanic** [comment]
@bloodmadridista I'm stuck with angular 11 and can't update nx because of it
is there any workaround to add tags to my runs?
