### ISSUE TITLE
Next.js build doesn't work with material-ui

### ISSUE THREAD

**Issue by stefanbinder** [nrwl/nx#5445]
## Current Behavior
The `nx r next-project:build` creates the build with wrong hydration css classnames.  

Serving the App with `next start` runs the app, but css-class names aren't hydrated correct.  
Therefore the initial load is incorrect.  

Doing the build WITHOUT nx is working fine:  
cd into/next-project and executing next via the node_modules bin folder:

`.../node_modules/.bin/next build`  
(eg. output path to nx's /dist/apps/next-project folder)

executing there:  
`.../node_modules/.bin/next start`  

Runs the next-server correctly and without any problems.

## Expected Behavior

Running `nx r next-project:build` does the same as `next build`

Question:  
**What are the differences? How can I debug build options?**

## Steps to Reproduce

I've prepared a repo: https://github.com/stefanbinder/nx-next-material
Checkout and follow instructions in readme

<details><summary>But here all steps to reproduce, or what I've done:</summary>

```
npx create-nx-workspace nx-next-material
empty and all default values

cd nx-next-material
yarn add -D @nrwl/next

# choosing: emotion
nx generate @nrwl/next:application the-next-app

cp apps/the-next-app/tsconfig.json ./tsconfig.json_backup

curl https://codeload.github.com/mui-org/material-ui/tar.gz/master | tar -xz --strip=2  material-ui-master/examples/nextjs-with-typescript
cp -R nextjs-with-typescript/* apps/the-next-app/

cp tsconfig.json_backup apps/the-next-app/tsconfig.json

yarn add @material-ui/core

# nice it runs without problems on localhost:4200
nx r the-next-app:serve

# lets build it
nx r the-next-app:build
cd dist/apps/the-next-app/

# nice it runs on localhost:3000, but with styling differences
../../../node_modules/.bin/next start
```
</details>

### Environment

<details><summary>NX-REPORT:</summary>

 NX  Report complete - copy this into the issue template

  Node : 12.16.1
  OS   : darwin x64
  yarn : 1.22.0
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.5.2
  @nrwl/cypress : 11.5.2
  @nrwl/devkit : 11.5.2
  @nrwl/eslint-plugin-nx : 11.5.2
  @nrwl/express : 11.5.2
  @nrwl/jest : 11.5.2
  @nrwl/linter : 11.5.2
  @nrwl/nest : Not Found
  @nrwl/next : 11.5.2
  @nrwl/node : 11.5.2
  @nrwl/react : 11.5.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.5.2
  @nrwl/web : 11.5.2
  @nrwl/workspace : 11.5.2
  @nrwl/storybook : 11.5.2
  @nrwl/gatsby : Not Found
  typescript : 4.0.5
</details>

**Comment by michael-proulx** [comment]
Same behavior for next-i18next.

Doesn't work with nx serve app, but jumping into to app and doing `../../node_modules/.bin/next` works perfectly as expected.

**Comment by kirjai** [comment]
hey @stefanbinder , thanks for filing the issue and providing the repro, it's very helpful!

just so i understand this correctly, in your repro, i can see that serving the next app with nx applies the border styling:
<img width="400" alt="Screenshot 2021-04-30 at 13 15 44" src="https://user-images.githubusercontent.com/9858620/116693690-f2f9ad80-a9c6-11eb-9e45-f6a5a0c09e9e.png">

but serving using `next start` doesn't apply those styles at all:
<img width="404" alt="Screenshot 2021-04-30 at 13 16 42" src="https://user-images.githubusercontent.com/9858620/116693822-191f4d80-a9c7-11eb-9c44-83bfa1be9aff.png">

and you're saying that that behaviour is incorrect?

**Comment by kirjai** [comment]
so after looking into it it might be related to a known issue with an empty `NODE_ENV` during the build.

building the app with `NODE_ENV=production` explicitly - solves the issue in the repro repo. please give that a try as a workaround for now, until we fix the underlying `NODE_ENV` issue. let us know if that workaround works for you!

@michael-proulx, could you give that a try in your repo that has the same issue with `next-i18next` and see if this workaround works for you too?

**Comment by stefanbinder** [comment]
Thx @kirjai - you want to keep the issue open for fixing the issue itself?  
Otherwise let's close it.

For everybody who finds the same problem, my workaround:

1. Changing the "build" command to "nx-build"
2. Adding own "build" command with run-commands and export the `NODE_ENV` before.

```
"build": {
  "builder": "@nrwl/workspace:run-commands",
  "options": {
    "commands": [
      "export NODE_ENV=production",
      "nx r the-next-app:nx-build"
    ]
  }
},
"nx-build": {
  "executor": "@nrwl/next:build",
  "outputs": ["{options.outputPath}"],
  "options": {
    "root": "apps/the-next-app",
    "outputPath": "dist/apps/the-next-app"
  },
  "configurations": {
    "production": {}
  }
},
```
