### ISSUE TITLE
💥 eslint fails with Angular webworker schematic

### ISSUE THREAD

**Issue by rustygreen** [nrwl/nx#5446]
## Current Behavior
After adding an [Angualr webworker](https://angular.io/guide/web-worker) to a project, the lint command will no longer work (using eslint configuration). The reason is because the NX (or NG) CLI is adding in a "tsConfig" property to the "lint" section in angualr.json:
```javascript
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": [
              "apps/omni/src/**/*.ts",
              "apps/omni/src/**/*.html"
            ],
            "tsConfig": ["apps/omni/tsconfig.app.json"] // <--- shouldn't be here
          }
        },
```

## Expected Behavior
The lint command should run successfully. The `lint` section in angular.json should not include the 'tsConfig' entry.

## Steps to Reproduce
```bash
# Create workspace
npx create-nx-workspace --preset=angular --name=my-workspace --appName=my-app --interactive=false --nx-cloud=false --style=scss --linter=eslint

# Go to workspace
cd my-workspace

# NOTE: linting will work fine at this point (npm run lint -- my-app)

# Add new Angular webworker
npm run ng -- generate web-worker my-test-worker

# Lint project
npm run lint -- my-app

# 💥💥💥 Will get error: 'tsConfig' is not found in schema
```

### Failure Logs
![image](https://user-images.githubusercontent.com/1774477/115894811-b0186280-a427-11eb-81d8-2877bb3b2b19.png)

### Solution
Adding the webworker appears to be adding in a "tsConfig" section to the "lint" configuration. If this `tsConfig` property is removed, then linting works again.
```javascript
        "lint": {
             .....
            // REMOVE:
            "tsConfig": ["apps/omni/tsconfig.app.json"]
          }
        },
```

### Environment
Windows 10
Node 14.16.1

**Comment by FrozenPandaz** [comment]
I think this is an issue with the `web-worker` schematic.

They've fixed the issue here:
https://github.com/angular/angular-cli/commit/226a8d274d27d191651926bc7970af11cfee2597#diff-7d49d9a39efee9024b4e070bf8350a37ca5c7bbd9bd2bb011a26581b3190179e

Though we'll have to wait for v12 for it.

I don't think there's anything actionable for us here.

**Comment by meeroslav** [comment]
I can confirm that this is fixed in v12.
