### ISSUE TITLE
Nested library is not getting bundled.

### ISSUE THREAD

**Issue by iamvinitk** [nrwl/nx#5458]
## Current Behavior
Whenever `react-publishable-lib` is built, `lib2` gets bundled but `lib1` doesn't get bundled.

## Expected Behavior
I expect both `lib1` and `lib2` to be bundled in the output file.

<img width="1680" alt="Screenshot 2021-04-25 at 3 48 51 PM" src="https://user-images.githubusercontent.com/17565617/115989820-d7b12b80-a5dd-11eb-9217-68cfcfd282bd.png">

`react-publishable-lib.esm.js`

<img width="1254" alt="Screenshot 2021-04-25 at 3 53 09 PM" src="https://user-images.githubusercontent.com/17565617/115989916-573efa80-a5de-11eb-96fa-354c42e14909.png">

## Steps to Reproduce
[Link to repo](https://github.com/iamvinitk/nx-import-bug)

### Environment
```
  Node : 14.15.5
  OS   : darwin x64
  npm  : 7.6.0
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.0.8
  @nrwl/cypress : 12.0.8
  @nrwl/devkit : 12.0.8
  @nrwl/eslint-plugin-nx : 12.0.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.8
  @nrwl/linter : 12.0.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.0.8
  @nrwl/react : 12.0.8
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.8
  @nrwl/web : 12.0.8
  @nrwl/workspace : 12.0.8
  @nrwl/storybook : 12.0.8
  @nrwl/gatsby : Not Found
  typescript : 4.0.7
```

**Comment by iamvinitk** [comment]
Keeping it active.

**Comment by qjnz** [comment]
Keeping it active.

**Comment by iamvinitk** [comment]
Keeping it active.
