### ISSUE TITLE
Dep graph visualization options

### ISSUE THREAD

**Issue by Driesigner** [nrwl/nx#5459]
## Description

Introduce options for visualisation of the depgraph, much like dependency-cruiser allows. See here for [examples](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/real-world-samples.md)

## Motivation

When projects get larger, the current way of visualising the graph has it's limits. One style to rule them all is probably not possible, but having more options could help to improve the overall clarity of the graph. Configuring colours per domain or per app, arrows that curve around other tiles (the straight arrows tend to sometimes pass under tiles, creating some confusion) Configuring font-sizes, paddings or even the ability to reposition tiles could be interesting.

## Suggested Implementation

A `depgraph.config.json` file could be a good place to configure options.

## Alternate Implementations

Add a configuration panel in the dep-graph sidebar, to adjust the layout for the opened graph.

**Comment by jase88** [comment]
Different colors for different tags /scopes would already be great

**Comment by tmtron** [comment]
+1
