### ISSUE TITLE
ng add @nrwl/workspace fails when path mapping exist

### ISSUE THREAD

**Issue by danzrou** [nrwl/nx#5463]
## Current Behavior
Using `ng add @nrwl/workspace` in a Angular CLI project fails on this  line:
`await formatFiles(tree);`
My assumption that it's happening due to paths mapped in `tsconfig` file.
If I comment this line, the migration finishes but the paths are not updated to new ones.

## Expected Behavior
Migration finishes succesfully

## Steps to Reproduce
* Create an Angular project
* Add path mapping in `tsconfig`
* run `ng add @nrwl/workspace`

### Failure Logs
```
Path: src/karma.conf.js does not exist
No e2e project was migrated because there was none declared in angular.json
ERROR! apps/WebClientTN/src/app/app-injector.ts does not exist..
ERROR! apps/WebClientTN/src/app/app-routing.module.ts does not exist..
ERROR! apps/WebClientTN/src/app/app.component.html does not exist..
ERROR! apps/WebClientTN/src/app/app.component.ts does not exist..
ERROR! apps/WebClientTN/src/app/app.component.scss does not exist..
ERROR! apps/WebClientTN/src/app/app.module.ts does not exist..
```

the same for each file in the project.

### Environment
```
>  NX  Report complete - copy this into the issue template

  Node : 12.16.2
  OS   : win32 x64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.0.8
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.0.8
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.8
  @nrwl/linter : 12.0.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.8
  @nrwl/web : Not Found
  @nrwl/workspace : 12.0.8
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

**Comment by leosvelperez** [comment]
@danzrou thanks for reporting this!

Unfortunately, I'm not able to reproduce it following the described steps. I can see in the shared error log that is not coming from a freshly generated Angular CLI workspace, so maybe some of the differences could be causing the issue. Could you please share a repro repo to help me reproduce it?
