### ISSUE TITLE
Testing with Jest results in type error when importing a file with a dependency on Express

### ISSUE THREAD

**Issue by donnyroufs** [nrwl/nx#5465]
## Current Behavior

When running nx test {{ lib/app }} and the spec file imports a file that does not use a default import it throws a type error
similiar to this: **TypeError: express_1.default is not a function** which makes it untestable. Only way to solve it is to import it like so: `import * as express from 'express'`

## Expected Behavior

As long as the tsconfig has the options:

-  "esModuleInterop": false,
-  "allowSyntheticDefaultImports": true,

then it should run the test without type errors.

## Steps to Reproduce

[Repository](https://github.com/donnyroufs/nx-issue-repo)

1. npx create-nx-workspace --preset=empty
2. npx nx generate @nrwl/workspace:library woef  
3. npm install express
4. npm install -D @types/express
5. create a file that exports an instance of express
6. inside woef.spec.ts import the express instance from step 5 and assert if it's defined
7. npx nx test woef

### Failure Logs
```
Test suite failed to run
    TypeError: express_1.default is not a function

      1 | import express from 'express';
      2 |
    > 3 | export const app = express();
```

### Environment

```
  Node : 14.16.0
  OS   : linux x64
  npm  : 7.10.0
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.0.8
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.0.8
  @nrwl/eslint-plugin-nx : 12.0.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.8
  @nrwl/linter : 12.0.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.8
  @nrwl/web : Not Found
  @nrwl/workspace : 12.0.8
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

**Comment by FrozenPandaz** [comment]
It seems `ts-jest` deprecated using that flag in favor of using `esModuleInterop`.

https://github.com/kulshekhar/ts-jest/issues/632

Do you not want `esModuleInterop` to be `true`?

**Comment by donnyroufs** [comment]
As far as I'm aware `esModuleInterop` has to be false for older packages like Express. I've managed to "fix" it by importing it like so:
`import express = require('express')`
Not sure why this works, but it seems to fix the issue for me.

**Comment by FrozenPandaz** [comment]
Glad you found a workaround :smile:. 

This doesn't seem actionable from Nx so I'm going to close this issue.
