### ISSUE TITLE
Error during bundle: Error: '__spreadArray' is not exported by tslib.js

### ISSUE THREAD

**Issue by EladBezalel** [nrwl/nx#5467]
I have this code 
```ts
export const MEDIA_QUERIES = {
  upToDesktop: (first: CSSObject | TemplateStringsArray, ...args: SimpleInterpolation[]) => css`
    @media (max-width: ${MAX_SCREEN_SIZES.desktop}px) {
      ${css(first, ...args)};
    }
  `
}
```
and when building this project i get
```
Error during bundle: Error: '__spreadArray' is not exported by tslib.js
```

it seems like the solution will be to upgrade `rollup-plugin-typescript2` to `0.30.0`
https://github.com/nrwl/nx/blob/2089d37cf989b50d1b7f4108a6c0f886548c0df2/package.json#L202

**Comment by tgelu** [comment]
Any plans to release this soon? seems rather critical since one cannot build code using the spread operator (unless I'm missing something).
