### ISSUE TITLE
npx run storybook Error: Cannot find module

### ISSUE THREAD

**Issue by gelsogrove** [nrwl/nx#5468]
i am trying to install storybook using @nrwl 11.1.5 (it's the only version that works) 
but i have an error on running this command:

**npx run frontend-core:storybook**

## Steps to Reproduce
rm -rf node_modules 
 npm install
nx migrate 11.1.5 
npm i @nrwl/storybook -D
 npx nx g @nrwl/angular:storybook-configuration frontend-core

manually update this version on package.json
 "@nrwl/angular": "11.1.5",
 "@nrwl/cli": "11.1.5",
 "@nrwl/eslint-plugin-nx": "11.1.5",
 "@nrwl/jest": "11.1.5",
 "@nrwl/linter": "11.1.5",
 "@nrwl/storybook": "12.0.8",
 "@nrwl/tao": "11.1.5",
 "@nrwl/workspace": "11.1.5",

npx nx g @nrwl/angular:storybook-configuration frontend-core

SUCCESS INSTALLATION

### Failure Logs
command: **npx run frontend-core:storybook**

npx: installed 5 in 1.729s
Watching /Users/gelso/workspace2/recall2-frontend and all sub-directories not excluded by your .gitignore. Will not monitor dotfiles.
Found & ignored ./.env ; is listed in .gitignore
Found & ignored ./.git ; is listed in .gitignore
Found & ignored ./.github ; is listed in .gitignore
Found & ignored ./.husky ; is listed in .gitignore
Found & ignored ./.storybook ; is listed in .gitignore
Found & ignored ./.vscode ; is listed in .gitignore
Found & ignored ./apps ; is listed in .gitignore
Found & ignored ./coverage ; is listed in .gitignore
Found & ignored ./libs ; is listed in .gitignore
Found & ignored ./node_modules ; is listed in .gitignore
Found & ignored ./reports ; is listed in .gitignore
Found & ignored ./shared-i18n ; is listed in .gitignore
Found & ignored ./showcases ; is listed in .gitignore
Found & ignored ./stories ; is listed in .gitignore
Found & ignored ./tools ; is listed in .gitignore
Found & ignored ./ts-types ; is listed in .gitignore
Found & ignored ./unsupported-browser ; is listed in .gitignore
Found & ignored ./webpack ; is listed in .gitignore
Found & ignored ./README.md ; is listed in .gitignore
Found & ignored ./TODO.md ; is listed in .gitignore
Found & ignored ./angular.json ; is listed in .gitignore
Found & ignored ./jest.config.js ; is listed in .gitignore
Found & ignored ./jest.preset.js ; is listed in .gitignore
Found & ignored ./nx.json ; is listed in .gitignore
Found & ignored ./package-lock.json ; is listed in .gitignore
Found & ignored ./package.json ; is listed in .gitignore
Found & ignored ./tsconfig.base.json ; is listed in .gitignore
Found & ignored ./tsconfig.base.strict.json ; is listed in .gitignore
Found & ignored ./tsconfig.lint.json ; is listed in .gitignore

Starting: frontend-core:storybook
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/Users/gelso/workspace2/recall2-frontend/frontend-core:storybook'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: '**MODULE_NOT_FOUND'**,
  requireStack: []

thanks in advance

**Comment by FrozenPandaz** [comment]
> npx run frontend-core:storybook

Did you mean to do `npx nx run frontend-core:storybook`?

**Comment by gelsogrove** [comment]
if i execute your command i have no result..:-( as you can see on the picture

(please not that i can install storybook only with the nx version 11.1.5)

![image](https://user-images.githubusercontent.com/15196278/116209899-a736d200-a742-11eb-90b6-305e2bb0282d.png)

**Comment by gelsogrove** [comment]
![image](https://user-images.githubusercontent.com/15196278/116210484-347a2680-a743-11eb-913d-5920335b380b.png)
this is the output of your command

please note that i can install storybook only with the version 11.1.5 the latest doesnt' work

**Comment by gelsogrove** [comment]
nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.16.0
  OS   : darwin x64
  npm  : 6.14.11
  
  nx : Not Found
  @nrwl/angular : 11.1.5
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.5
  typescript : 3.5.3

**Comment by gelsogrove** [comment]
the command for run storybook is ng run frontend-core:storybook
(but it fails)
