### ISSUE TITLE
`nx <custom command> --all` not supported with Angular CLI powered workspace

### ISSUE THREAD

**Issue by bbaia** [nrwl/nx#5471]
## Current Behavior

I could not use `nx <custom command> --all` with an Angular CLI powered workspace.
I add to switch to `nx run-many --target=restore --all`
See https://github.com/bbaia/nx-dotnet-core/blob/master/packages/nx-dotnet-core/src/generators/new/generator.ts#L188

## Expected Behavior
`nx <custom command> --all` should work everywhere.

## Steps to Reproduce

Can be reproduced with the `restore` custom command using this plugin: https://github.com/bbaia/nx-dotnet-core 

### Failure Logs

> The specified command ("restore") is invalid. For a list of available options,
> run "ng help".
> 
> Did you mean "test"?

**Comment by vsavkin** [comment]
Could you provide a repro? I believe the issue is that the decorate-angular-cli script does run in your workspace.

**Comment by bbaia** [comment]
You can reproduce it on the repo https://github.com/bbaia/nx-dotnet-core
It is not based on Angular CLI, so no decorate-angular-cli script.
