### ISSUE TITLE
Nx Nextjs build produce broken dist app MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by overbit** [nrwl/nx#5473]
## Current Behavior
Building a nextjs application for production creates a deployable application that cannot start due to the following error:
`Error: Cannot find module '@nrwl/next/plugins/with-nx'`

When deploying the application as SSR app in a docker image, it would not make sense to add all the devDependencies.

## Expected Behavior
Either of the following two:
- the produced nextjs application next.config.js does not have any dependency on  Nx plugin (`@nrwl/next/plugins/with-nx`)
- the dependent plugin `@nrwl/next/plugins/with-nx` is added as dependency for production (not as a devDependency)

## Steps to Reproduce

Based on the nx official docs:

```shell
npx create-nx-workspace@latest test-workspace
cd test-workspace
yarn
yarn add -D @nrwl/next
nx generate @nrwl/next:application test-app
# styled-components
yarn nx build test-app --prod

# remove node_modules since it won't be present in prod 
# yarn install will be run in the built application
rm -rf node_modules

# Prepare app for prod deployment
cd  dist/apps/test-app
yarn install --production=true
NODE_ENV=production yarn start
```

### Failure Logs
```shell
NODE_ENV=production yarn start
yarn run v1.22.10
warning package.json: No license field
$ next start
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Error: Cannot find module '@nrwl/next/plugins/with-nx'
Require stack:
- /home/workspaces/tmp/test-workspace/dist/apps/test-app/next.config.js
- /home/workspaces/tmp/test-workspace/dist/apps/test-app/node_modules/next/dist/next-server/server/config.js
- /home/workspaces/tmp/test-workspace/dist/apps/test-app/node_modules/next/dist/next-server/server/next-server.js
- /home/workspaces/tmp/test-workspace/dist/apps/test-app/node_modules/next/dist/server/next.js
- /home/workspaces/tmp/test-workspace/dist/apps/test-app/node_modules/next/dist/server/lib/start-server.js
- /home/workspaces/tmp/test-workspace/dist/apps/test-app/node_modules/next/dist/cli/next-start.js
- /home/workspaces/tmp/test-workspace/dist/apps/test-app/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.mod._resolveFilename (/home/workspaces/tmp/test-workspace/dist/apps/test-app/node_modules/next/dist/build/webpack/require-hook.js:4:1784)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/workspaces/tmp/test-workspace/dist/apps/test-app/next.config.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/workspaces/tmp/test-workspace/dist/apps/test-app/next.config.js',
    '/home/workspaces/tmp/test-workspace/dist/apps/test-app/node_modules/next/dist/next-server/server/config.js',
    '/home/workspaces/tmp/test-workspace/dist/apps/test-app/node_modules/next/dist/next-server/server/next-server.js',
    '/home/workspaces/tmp/test-workspace/dist/apps/test-app/node_modules/next/dist/server/next.js',
    '/home/workspaces/tmp/test-workspace/dist/apps/test-app/node_modules/next/dist/server/lib/start-server.js',
    '/home/workspaces/tmp/test-workspace/dist/apps/test-app/node_modules/next/dist/cli/next-start.js',
    '/home/workspaces/tmp/test-workspace/dist/apps/test-app/node_modules/next/dist/bin/next'
  ]
}
error Command failed with exit code 1.
```

### Environment

nx won't be installed in the docker image nor in the dist folder and this is actually the problem.

All the commands have been run with the latest nx version:
```shell
  Node : 12.21.0
  OS   : linux x64
  npm  : 7.10.0
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.0.8
  @nrwl/cypress : 12.0.8
  @nrwl/devkit : 12.0.8
  @nrwl/eslint-plugin-nx : 12.0.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.8
  @nrwl/linter : 12.0.8
  @nrwl/nest : Not Found
  @nrwl/next : 12.0.8
  @nrwl/node : Not Found
  @nrwl/react : 12.0.8
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.8
  @nrwl/web : 12.0.8
  @nrwl/workspace : 12.0.8
  @nrwl/storybook : 12.0.8
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by jole78** [comment]
We have sort of the same issue but we're hosting the nextjs app in a docker container and had to temporarily add this after the RUN yarn install instruction:

`RUN yarn add @nrwl/next@11.3.1`

older version yes I know but it now works anyway

**Comment by AlexandrePhilibert** [comment]
I am having the same issue with nx 12.2.0, I also managed to do a temporary fix in my Dockerfile using :

`RUN npm install @nrwl/next`

**Comment by kirjai** [comment]
thanks for reporting the issue!

how Nx determines where to put a dependency - (`devDependencies` or `dependencies`) is dependent on the root `package.json`

so if you put `@nrwl/next` into `dependencies` in your root `package.json` - it will appear in `dependencies` in the built `package.json`

---

@jole78 and @AlexandrePhilibert give that a try, should be easier than running `yarn add` / `npm install` in docker

**Comment by kirjai** [comment]
so what we've done with #5662 is that new workspaces that use the `next.js` preset will be generated with the `@nrwl/next` dependency in the `dependencies`, rather than `devDependencies`.

but as mentioned above:
*how Nx determines where to put a dependency - is dependent on where it is in the root `package.json`*.

i will also make sure we update the docs to *not* suggest adding `@nrwl/next` as a dev dependency, which is what we currently do

**Comment by wguerram** [comment]
I'm having the issue that withNx is requiring typescript pacakge, in order to deploy I had to add typescript as de production dependency. Is anybody else having that issue?

**Comment by alvinalexander** [comment]
@wguerram I am having the same issue

**Comment by kirjai** [comment]
@wguerram @alvinalexander 

issue with TS not being installed was tracked in #6985 and #6886, and recently closed by #7130

**Comment by SebasG22** [comment]
+1 This is happening to me.

**Comment by benediktms** [comment]
I'm getting the same issue. I can confirm that moving `@nrwl/next` from `devDependencies` into `dependencies` fixes this issue, however this does not seem correct. Nx should not have any dependencies in the production build of an application. Doing a compare of before/after adding the dependency also increases the image size by roughly 400mb. Could you shed some light into what `@nrwl/next` is doing in the next.config file? Can it safely be stripped out?

**Comment by Maus3rSR** [comment]
> so what we've done with #5662 is that new workspaces that use the `next.js` preset will be generated with the `@nrwl/next` dependency in the `dependencies`, rather than `devDependencies`.
> 
> but as mentioned above: _how Nx determines where to put a dependency - is dependent on where it is in the root `package.json`_.
> 
> i will also make sure we update the docs to _not_ suggest adding `@nrwl/next` as a dev dependency, which is what we currently do

Hello,

Involving with this issue currently, still suggesting to add `@nrwl/next` as a dev dependency
