### ISSUE TITLE
When signing git commits create-nx-workspace behaves weirdly

### ISSUE THREAD

**Issue by giggio** [nrwl/nx#5476]
## Current Behavior
If you have set `commit.gpgsign = true` for your git config when you run `create-nx-workspace` it'll stop in the end of the process to ask for the password and the terminal UI gets really broken.
My guess is the spinner keeps updating the terminal screen and that breaks the password UI from git.

## Expected Behavior
The password UI appears cleanly, as it does when not using `create-nx-workspace`.

## Steps to Reproduce
1. Set `commit.gpgsign = true` for your git config with a password for our gpg key;
2. Run `create-nx-workspace` to the end.

### Failure Logs
None.

### Environment
Ubuntu 20.04 on WSL2, git 2.25.1, Node.js 15.14.0, Npm 7.7.6.

**Comment by benjamincharity** [comment]
fwiw I also hit this on MacOS Big Sur `11.5.2`, `nx@12.9.0`, `node@16.9.1`

**Comment by giggio** [comment]
not stale

**Comment by giggio** [comment]
not stale

**Comment by giggio** [comment]
not stale
