### ISSUE TITLE
Unable to set process env variables using executors in workspace.json

### ISSUE THREAD

**Issue by sivani-pa** [nrwl/nx#5480]
Hi,

I have added the below executor in my workspace.json but the command is not adding the value to the env variable.

{
  "version": 2,
  "cli": {
    "defaultCollection": "@nrwl/react"
  },
"app1": {
      "root": "apps/app1",
      "sourceRoot": "apps/app1/src",
      "projectType": "application",
      "prefix": "app1",
      "targets": {
        "setConfigPath": {
          "executor": "@nrwl/workspace:run-commands",
          "options": {
            "commands": ["cross-env APP_PATH=apps/app1/config"]
          }
        }
  }
}

I can use .env file for adding the variable on process.env but the value is not static.
## Current Behavior
When I console the process.env.APP_PATH, it's giving undefined.

## Expected Behavior
When I console the process.env.APP_PATH in my application should give the value "apps/app1/config".

**Comment by AgentEnder** [comment]
Cross-env and other packages that update environment variables only update the environment variables for the currently running process + child processes spawned by it. Unfortunately setting system level environment variables is non-trivial and something that these packages do not support.

For more explanation see ebohlman's comment here: https://stackoverflow.com/questions/10829433/how-can-i-set-an-environmental-variable-in-node-js#comment-14115865

**Comment by FrozenPandaz** [comment]
Can you be more specific about why the variable is not static and what you are trying to accomplish?

**Comment by montogeek** [comment]
@FrozenPandaz How would you deal with situations where you need to use git hash as a version for example?
