### ISSUE TITLE
Why don't you parse `.env.local`?

### ISSUE THREAD

**Issue by awakia** [nrwl/nx#5481]
## Description

In react, local only version of `.env` is `.env.local` instead of `.local.env`, which currently nx parses.
So why don't you parse `.env.local` additionally?

## Motivation

It becomes more integration friendly for react users when nx parses `.env.local`

## Suggested Implementation

in [packages/workspace/src/tasks-runner/task-orchestrator.ts](https://github.com/nrwl/nx/blob/b388c1ed81c4ee7baa61df2fac31a68d117b6711/packages/workspace/src/tasks-runner/task-orchestrator.ts#L339-L344)

```diff
    const envsFromFiles = {
      ...parseEnv('.env'),
      ...parseEnv('.local.env'),
+     ...parseEnv('.env.local'),
      ...parseEnv(`${task.projectRoot}/.env`),
      ...parseEnv(`${task.projectRoot}/.local.env`),
+     ...parseEnv(`${task.projectRoot}/.env.local`),
    };
```

## Alternate Implementations

```diff
    const envsFromFiles = {
      ...parseEnv('.env'),
+     ...parseEnv('.env.local'),
      ...parseEnv('.local.env'),
      ...parseEnv(`${task.projectRoot}/.env`),
+     ...parseEnv(`${task.projectRoot}/.env.local`),
      ...parseEnv(`${task.projectRoot}/.local.env`),
    };
```

This can override `.env.local` by `.local.env` if you needed. This implementation may be slightly better than upper one.

**Comment by FrozenPandaz** [comment]
That's a good idea. Would you like to contribute your suggested implementation?

**Comment by awakia** [comment]
@FrozenPandaz Thanks. I've just created Pull Request, but I couldn't understand document logic nx uses.
Please review #5491 and teach me how to change docs part.
