### ISSUE TITLE
Nextjs 10.2v support

### ISSUE THREAD

**Issue by underfisk** [nrwl/nx#5492]
## Description
Support to the latest nextjs version 10.2 in order to also benefit from webpack5

## Motivation
It has significant performance boosts

**Comment by erkobridee** [comment]
I tried to update my project to use the next.js v10.2 but I got the following error

```
error - /${local path}/nx-nextjs/libs/shared/components/src/lib/shared-components/index.tsx
SyntaxError: /${local path}/nx-nextjs/libs/shared/components/src/lib/shared-components/index.tsx: Duplicate __self prop found. You are most likely using the deprecated transform-react-jsx-self Babel plugin. Both __source and __self are automatically set when using the automatic runtime. Please remove transform-react-jsx-source and transform-react-jsx-self from your Babel config.
   9 |   return (
  10 |     <div className="rounded shadow-md p-3">
> 11 |       <h1 className="font-open-sans text-blue-500">
     |       ^
  12 |         Welcome to shared-components!
  13 |       </h1>
  14 |     </div>

```

I tested on my pet project where I test the version before apply to the real projects [erkobridee/nx-nextjs](https://github.com/erkobridee/nx-nextjs)

**Comment by hcharley** [comment]
@erkobridee I encountered that too in my project

**Comment by underfisk** [comment]
@FrozenPandaz Any status when we'll have a release with this, even if its a next release because its a bit important, currently it is breaking our builds

**Comment by cyrus-za** [comment]
also running into this now (still on next 10.1.3)

**Comment by FrozenPandaz** [comment]
@kirjai has been taking a look here https://github.com/nrwl/nx/pull/5503

**Comment by underfisk** [comment]
@FrozenPandaz It seems a small change, any ETA on this issue because at my side its a bit urgent having support for 10.2

**Comment by kirjai** [comment]
there are still some things that we need to dig deeper into in #5503 , but it's getting there..

also, it's worth noting that if you're eager to get the webpack 5 benefits with 10.2 - you will have to wait longer for that, as we still don't support webpack 5 in Nx. we're throwing an error currently on Nx 10.1 if you try to enable webpack 5.

**rest assured that supporting webpack 5 is very high on our priority list**. but as it stands now, webpack 5 support is unlikely to land before or at the same time as support for Next 10.2

**Comment by erkobridee** [comment]
I updated the nx to v12.1.1 and next to v10.2.0 (the next is running on top of webpack v4), but I still got the same issue

```
error - /${local path}/nx-nextjs/libs/shared/components/src/lib/shared-components/index.tsx
SyntaxError: /${local path}/nx-nextjs/libs/shared/components/src/lib/shared-components/index.tsx: Duplicate __self prop found. You are most likely using the deprecated transform-react-jsx-self Babel plugin. Both __source and __self are automatically set when using the automatic runtime. Please remove transform-react-jsx-source and transform-react-jsx-self from your Babel config.
   9 |   return (
  10 |     <div className="rounded shadow-md p-3">
> 11 |       <h1 className="font-open-sans text-blue-500">
     |       ^
  12 |         Welcome to shared-components!
  13 |       </h1>
  14 |     </div>

```

follow the branch with that behavior: [[GitHub] erkobridee/nx-nextjs - update/nextjs](https://github.com/erkobridee/nx-nextjs/tree/update/nextjs)

![Screen Shot 2021-05-06 at 12 04 15](https://user-images.githubusercontent.com/342471/117281009-7bfb6380-ae63-11eb-80eb-f10f7c8ec530.png)

@kirjai do you have any tip of why I got that complaining on the babeljs? thanks

**Comment by kirjai** [comment]
I don't believe this change was released as part of `12.1.1`, that version was released before the PR got merged. we'll try and release a new version, with the fix soon. 

ultimately, the issue is that the `.babelrc` files inside a next app directory, and inside a react lib directory are merged by babel. this results in a `preset-react` babel plugin being included twice - resulting in that error. 

as a very temporary workaround, until we release a new version with our fix - you can try commenting out the `@nrwl/react/babel` instance from your react lib's `.babelrc`. that would of course be problematic if you're using that lib elsewhere - not in a next.js app. so this workaround might not be suitable for you, if that's the case. but worth pointing that out and trying if you're severely blocked by this issue

**Comment by erkobridee** [comment]
@kirjai I give it a try, for the next.js application inside of my mono repo it works, but the other application based on plain react, that didn't ran without the `@nrwl/react/babel` preset on the library 😢

**Comment by vitorcamachoo** [comment]
> I don't believe this change was released as part of `12.1.1`, that version was released before the PR got merged. we'll try and release a new version, with the fix soon.
> 
> ultimately, the issue is that the `.babelrc` files inside a next app directory, and inside a react lib directory are merged by babel. this results in a `preset-react` babel plugin being included twice - resulting in that error.
> 
> as a very temporary workaround, until we release a new version with our fix - you can try commenting out the `@nrwl/react/babel` instance from your react lib's `.babelrc`. that would of course be problematic if you're using that lib elsewhere - not in a next.js app. so this workaround might not be suitable for you, if that's the case. but worth pointing that out and trying if you're severely blocked by this issue

With that approach, it will break the unit tests I have on the library  🥲

**Comment by FrozenPandaz** [comment]
We will be releasing this as part of `12.2.0` early next week!

Have a good weekend and stay tuned! :smile: 

If you would really like to confirm this works.. you can try version `12.2.0-beta.0` which has the fix but we will be promoting it to stable when it is not Friday :wink:

**Comment by erkobridee** [comment]
thank you @FrozenPandaz and @kirjai now the project is 100% working 🍾 

[[GitHub] erkobridee/nx-nextjs](https://github.com/erkobridee/nx-nextjs)
