### ISSUE TITLE
parserOptions parameter at .eslintrc.json is not updated when moving a library

### ISSUE THREAD

**Issue by aantciferov-codepoint** [nrwl/nx#5493]
## Current Behavior
After moving the library (generated with React plugin) with `nx g move`, the library path at .eslintrc.json > overrides > parserOptions > project isn't updated.

## Expected Behavior
The path to the library should be updated.

## Steps to Reproduce
- Create a library:
`nx g @nrwl/react:lib library-name --directory some-directory`
- Check .eslintrc.json at some-directory/library-name/ -- the `project` parameter contains the library path.

- Move the library:
`nx g move --project some-directory-library-name some-directory/new-name`
- Check .eslintrc.json again, it should contain the updated path.

### Environment
  Node : 15.8.0
  OS   : linux x64
  yarn : 1.22.5

  nx : 11.4.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.0.8
  @nrwl/cypress : 12.0.8
  @nrwl/devkit : 12.0.8
  @nrwl/eslint-plugin-nx : 12.0.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.8
  @nrwl/linter : 12.0.8
  @nrwl/nest : Not Found
  @nrwl/next : 12.0.8
  @nrwl/node : Not Found
  @nrwl/react : 12.0.8
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.8
  @nrwl/web : 12.0.8
  @nrwl/workspace : 12.0.8
  @nrwl/storybook : 12.0.8
  @nrwl/gatsby : Not Found
  typescript : 4.1.4

Thank you!

**Comment by FrozenPandaz** [comment]
Would someone like to try implementing this feature?

**Comment by meeroslav** [comment]
@FrozenPandaz I will look into it.
