### ISSUE TITLE
Cannot get NX Workspace folders only Angular CLI app folder structure

### ISSUE THREAD

**Issue by thaoula** [nrwl/nx#55]
Hi Guys,

Thanks very much for making this framework available. Have been looking to implement this structure for a while but never had the time to create the tooling. 

So I followed the instructions on the getting started -

1. I copy pasted the command to create the workspace using the sandbox method. After a short time and without error I ended up with a Angular cli looking folder structure. No apps and no libs folders

2. I tried running the command to upgrade existing cli app to workspace and I received error stating workspace was unknown schematic. 

3. Tried globally uninstalling angular cli and installed beta 1.5b4. Ran the commands for sandbox and I still got Angular cli folder structures. 

4. Tried global installation of nx it complained about missing dependcies such as schematics etc. tried installing them. Ran command to generate app and I got once again an Angular cli folder structure. 

Has anyone encountered this issue? 

Have a feeling I am missing something obvious and probably perfectly documented. 

I am using a Mac for development. 

Regards,
Tarek

**Comment by vsavkin** [comment]
>> I copy pasted the command to create the workspace using the sandbox method. After a short time and without error I ended up with a Angular cli looking folder structure. No apps and no libs folders

Could you do `ls -la` in the folder? Also, could you provide the contents of `angular-cli.json`?

**Comment by thaoula** [comment]
Hi @vsavkin,

Many thanks for getting back to me. Please find the info attached

[folder.txt](https://github.com/nrwl/nx/files/1388200/folder.txt)
[angular-cli.txt](https://github.com/nrwl/nx/files/1388206/angular-cli.txt)

Regards,
Tarek

**Comment by thaoula** [comment]
Hi Victor,

Did that information help? Can I do anything else?

Regards,
Tarek

**Comment by thaoula** [comment]
Hi Victor,

I uninstalled node deleted all node_module.

Installed node using Brew and ran the installer and now everything is working fine.

Regards,
Tarek
