### ISSUE TITLE
Short version of ng generate app fails

### ISSUE THREAD

**Issue by KyleW** [nrwl/nx#550]
I'm using nx 6.0.2. Trying to create a new app with:
```
ng generate app reporting
```
returns the following error
```
Schematic "app" not found in collection "@schematics/angular".
Error: Schematic "app" not found in collection "@schematics/angular".
```
The longer version of this command `ng generate application reporting` works just fine

**Comment by FrozenPandaz** [comment]
It seems that you are still using the `@schematics/angular` collection.

Did you add `@nrwl/schematics` to this project?

Was there an error when doing `ng add @nrwl/schematics`?

There is an existing issue https://github.com/nrwl/nx/issues/513 in the latest released version but there is already a fix for it.

**Comment by KyleW** [comment]
I got past this error locally, but unfortunatley, I didn't keep track of what I did and it's been a couple weeks now. I think it's safe to close this and I'll reopen if I manage to reproduce it.

Independently of this, I am seeing an error running  `ng add @nrwl/schematics?`.  I'll gather the details and document in a separate issue.
