### ISSUE TITLE
Support --args in nx run-many

### ISSUE THREAD

**Issue by EthanSK** [nrwl/nx#5502]
## Description

I would like to run nx run-many with --args so I can pass the configuration to a step that uses run-commands that itself triggers node builder. I want to forward the commands to node builder from run-commands but cannot with nx run-many

**Comment by FrozenPandaz** [comment]
This is already possible!

`nx run-many --target build -- --args="args1"` forwards everything after the `--` to the underlying commands.

Is this what you are looking for?

I guess this isn't documented well. Would you like to add an example under `run-many` [here](https://github.com/nrwl/nx/blob/master/packages/workspace/docs/run-commands-examples.md)?

**Comment by jase88** [comment]
This probably won't work if any of those targets doesn't have the args in it's schematic. For example a angular build and a run command build

**Comment by FrozenPandaz** [comment]
Sorry, it's probably confusing that the above example uses `args` :sweat_smile:.

Everything after the `--` is forwarded much like `npm run build -- --watch`. Another example would be that the two commands below are equivalent:

```sh
nx run-many --target build --projects my-app -- --watch
nx build my-app --watch
```

**Comment by EthanSK** [comment]
@jase88 is right. I get the error "'args' is not found in schema']"

**Comment by jase88** [comment]
I had similiar issues: https://github.com/nrwl/nx/issues/4976

I also had a first look at the repo for a PR, but didn't had a clue how to restructure the command processing.

**Comment by theres** [comment]
@FrozenPandaz It is working only if you are using globally installed nx - I tend to not do it. If you'll try to run it via `yarn nx` / `npm run nx` it is not working:

```sh
yarn nx run-many --all --target build -- --args="args1"
```

Do you have any idea how to overcome it without introduction of `--args` parameter to `run-many`?

**Comment by seriouscoderone** [comment]
I see a "With flags:" section near the bottom when `run-many` starts executing. 

does not that mean it is passing args?

It appears that the flags are not passed in all the projects. Some get the args and other dont.

**Comment by theres** [comment]
no stale
