### ISSUE TITLE
nrwl/react: nx build --configuration=staging uses react-jsxdev

### ISSUE THREAD

**Issue by puku0x** [nrwl/nx#5512]
## Current Behavior

Nx uses `react-jsxdev` even if script optimization is enabled when `--configuration` is not `production`.

## Expected Behavior

Nx should use `react-jsx` when `optimization === true` or `optimization.scripts === true`

## Steps to Reproduce

1. `npx create-nx-workspace workspace --preset=react` ~with Emotion~
2. Replace `production` with `staging`, for example, in `targets.build.configurations`
3. `npx nx build <project-name> --configuration=staging`
4. See the output has `jsxDEV` in `main.[hash].js` which should not be in the optimized bundle.

### Failure Logs

![image](https://user-images.githubusercontent.com/2607019/116726360-1f8ce400-aa1e-11eb-839f-5047fb661d24.png)

### Environment

```
% npx nx report                                              

>  NX  Report complete - copy this into the issue template

  Node : 14.15.4
  OS   : darwin x64
  npm  : 6.14.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.0.8
  @nrwl/cypress : 12.0.8
  @nrwl/devkit : 12.0.8
  @nrwl/eslint-plugin-nx : 12.0.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.8
  @nrwl/linter : 12.0.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 12.0.8
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.8
  @nrwl/web : 12.0.8
  @nrwl/workspace : 12.0.8
  @nrwl/storybook : 12.0.8
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

**Comment by puku0x** [comment]
`envName` should be `production` when `isScriptOptimizeOn===true`
https://github.com/nrwl/nx/blob/master/packages/web/src/utils/config.ts#L60

**Comment by puku0x** [comment]
or should I set `env` in `.babelrc`? https://github.com/nrwl/nx/pull/3385

**Comment by Nightbr** [comment]
Hey same behavior in my react app for `-c beta` (to map branches). And it has jsxDEV in esm modules. 
Could be great to have this fix for React Apps! thanks
