### ISSUE TITLE
@nrwl/jest - include more (or all) jest argv options

### ISSUE THREAD

**Issue by cdaringe** [nrwl/nx#5517]
## Description

`@nrwl/jest/src/builders/jest/jest.impl.js` currently uses only a subset of jest CLI options. I would like to have more, if not all CLI options available.

## Motivation

I seek to use _other_ CLI args, such as `testTimeout`. This is current infeasible due to a hard-coded set of options.

## Suggested Implementation

- have the builder accept an `argv` or similar array or KV object, used to map into the jest CLI call.

## Alternate Implementations

- keep adding additional KV pairs to the jest argv set 1 by 1

**Comment by FrozenPandaz** [comment]
We can keep adding jest arguments 1 by 1. Would you like to send a PR to add `testTimeout`?

**Comment by cdaringe** [comment]
done.
