### ISSUE TITLE
Clarify Globally Installing Nx in the docs

### ISSUE THREAD

**Issue by 1tree** [nrwl/nx#5525]
## Description
In all of your documentation, you have ignored the elephant in the room. I have spent 10 minutes trying what the package name is to install/upgrade. This makes it difficult for me to get started.

## Motivation
Documenting how to install Nx will make getting started easier.

## Suggested Implementation
Add the package name to install and how to install it.

## Alternate Implementations
None

**Comment by jase88** [comment]
Read the docs before complainig: https://nx.dev/latest/angular/getting-started/nx-setup

**Comment by 1tree** [comment]
Read you own docs before responding. The first two commands assume that you have a global installation. The third indicates it will transform your project into a workspace with no reference as to it installing all needed tools. And if this can be made to install globally as the first two command assume, then it doesn't tell you such.

**Comment by jase88** [comment]
You just need NodeJS installed, no other global installation required. 

`npx` is part of node, see https://docs.npmjs.com/cli/v7/commands/npx

**Comment by arekbal** [comment]
`nx` cli command is not part of the npx workspace install.

I spend more than 30 hours with `nx` and it's docs. Let me openly say it - it is ~~trash~~ quite bad. Not worst of the worst, but still a lot of it requires improvement.

My example of how bad it is, would be that "Workspace Structure" section, in none of it's topics tells you about "workspace structure".
Another example of my problem with docs was when searching for structure of custom executor and finding it only in blog article, with subpar explanation.
I want to work with `nx`. I need it badly to say the least and I truly love the premise and some of the accomplishments the project already achieved. But the amount of annoyance - documentation quality being nr.1 - reaches, a bit too close to the point of me calling it *problematic*.

**Comment by jase88** [comment]
> `nx` cli command is not part of the npx workspace install.
> 
It is installed locally. No need to install it globally. 

I understand your frustration about the docs, but the author is complaining about the installation, which is imho described totally fine.

Ranting about a open source project won't change anything. Make good improvement suggestions or even contributions - everything else is a waste of time.

**Comment by arekbal** [comment]
`nx` throughout docs is treated as installed globally.
I would add a note explaining a difference (a need for prefixing with `yarn` or `npm run`), would also write a sentence about npm/yarn as packageManager distinction, recall that you can pass it into `create-nx-workspace` and provide a link to proper `create-nx-workspace` reference.

**Comment by FrozenPandaz** [comment]
Hi everyone.

I acknowledge the documentation can always be improved! :sweat_smile:.

Rest assured, we are working actively on the docs and welcome any feedback!

That said...

**Please be civil when discussing issues.** I've moderated the conversation here to be more constructive.

**Comment by FrozenPandaz** [comment]
@1tree I agree. The docs do expect `nx` to be installed globally but it is not well explained in the getting started section.
@arekbal I like that idea. Let's cover the following points:

* The docs expect `nx` to be globally.
* How to install `nx` globally (with `npm`, `yarn`, `pnpm`)
* How to run nx commands without `nx` being installed globally (`npm run nx`, `npx nx`, `yarn nx`, `pnpm run nx`)

 Please make a PR if you have the time!
