### ISSUE TITLE
ERROR: Bad builder config for @nrwl/run-commands - "readyWhen" can only be used when parallel=true

### ISSUE THREAD

**Issue by arekbal** [nrwl/nx#5526]
I have defined command that runs successfully with `nx serve <project-name>`. It is calling rust's `cargo run`.
When I added the `"readyWhen": "READY"` part, it started to fail with message as in title.

Actually it started throwing with `s.startsWith` over `undefined` because
in  `tao/source/shared/params.js` in `handleErrors()`
it does `logger_1.logger.error(err.message);`
when I fixed this into more generic `err.message || err` then I got the:
`ERROR: Bad builder config for @nrwl/run-commands - "readyWhen" can only be used when parallel=true`
Maybe that should be reported as separate bug.

Setting `"parallel": true,` doesn't help at all. Even so, it shouldn't be required as docs state that parallel=true is the default value.

I also tried `nx serve <project-name> --parallel` or `nx serve <project-name> --parallel=true` with same results.

## Current Behavior
```json
"serve": {
          "executor": "@nrwl/workspace:run-commands",
          "options": {
            "command": "cargo run",
            "cwd": "<project-path>",
          }
        }
```
Works

```json
"serve": {
          "executor": "@nrwl/workspace:run-commands",
          "options": {
            "command": "cargo run",
            "cwd": "<project-path>",
            "readyWhen": "READY"
          }
        }
```
Works not.

```json
"serve": {
          "executor": "@nrwl/workspace:run-commands",
          "options": {
            "command": "cargo run",
            "cwd": "<project-path>",
            "parallel": true,
            "readyWhen": "READY"
          }
        }
```
Works not.

## Expected Behavior
```json
"serve": {
          "executor": "@nrwl/workspace:run-commands",
          "options": {
            "command": "cargo run",
            "cwd": "<project-path>",
            "readyWhen": "READY"
          }
        }
```
Should work.

## Steps to Reproduce
```
 "serve": {
          "executor": "@nrwl/workspace:run-commands",
          "options": {
            "command": "cargo run",
            "cwd": "<project-path>",
            "parallel": true,
            "readyWhen": "READY"
          }
        }
```
~Might update it with PR to nx-examples in a minute.~
PR: https://github.com/nrwl/nx-examples/pull/143

### Failure Logs
```sh
> nx run <project-name>:serve 
ERROR: Bad builder config for @nrwl/run-commands - "readyWhen" can only be used when parallel=true
```

```sh
> nx run user-api:serve 
/home/me/Projects/invex/node_modules/@nrwl/tao/src/shared/logger.js:10
        if (s.startsWith('NX ')) {
              ^

TypeError: Cannot read property 'startsWith' of undefined
    at Object.error (/home/me/Projects/invex/node_modules/@nrwl/tao/src/shared/logger.js:10:15)
    at Object.<anonymous> (/home/me/Projects/invex/node_modules/@nrwl/tao/src/shared/params.js:17:33)
    at Generator.throw (<anonymous>)
    at rejected (/home/me/Projects/invex/node_modules/tslib/tslib.js:115:69)
```

### Environment
Debian, Intel i7, `"packageManager": "yarn"`

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Regarding the `readyWhen` and `parallel` error, as the message says, `readyWhen` is intended to be used when running parallel commands. In the example you're sharing, a single command is being run, so even though the default for `parallel` is `true`, it's a no-op because there are no multiple commands to run. We can do better with the messaging though. I'll create a PR to improve the docs about this and to warn instead of error if `readyWhen` is specified for a single command.

Regarding the logger issue, I wonder which version of Nx you are using. Since [v11.2.0](https://github.com/nrwl/nx/pull/4524/files#diff-e5a8075184d1a56a409d1118a3f58805cf0e71a675db4e5a31259edfc039512eR48) this shouldn't be an issue.
