### ISSUE TITLE
Static Images Not Loading in Storybook (React)

### ISSUE THREAD

**Issue by AndrewTBurks** [nrwl/nx#5528]
## Current Behavior
Static images (specifically `/\.(png|jpe?g|gif|webp)$/`) are not properly bundled and loaded when imported from TS files.

The bundled image hash does not match the hash of the static asset from within the component.

## Expected Behavior

Import statements should properly load the images:

```ts
import logo from './MyLogo.png';

const MyComponent = () => <img src={logo} />; // the image is not found
```

## Steps to Reproduce

Run `yarn nx g @nrwl/react:storybook-configuration <your-project>` and the webpack.config.js file generated in the project files will be broken when loading image files.

## **Steps Found to Fix**

The base template for generating the project-files webpack config seems to be incorrectly applying the `url-loader` alongside the default `file-loader` for static assets.

[The default config test regex for the `file-loader` can be found here](https://github.com/nrwl/nx/blob/master/packages/storybook/src/generators/configuration/project-files/.storybook/webpack.config.js__tmpl__#L28)

[The default config test regex for the added `url-loader` can be found here](https://github.com/nrwl/nx/blob/master/packages/storybook/src/generators/configuration/project-files/.storybook/webpack.config.js__tmpl__#L32)

The problem was mitigated by removing the image types found in the `url-loader` from the `file-loader` regex as follows:

```ts
// Original version
config.module.rules[svgRuleIndex].test = /\.(ico|jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|cur|ani|pdf)(\?.*)?$/;

// Corrected version
config.module.rules[svgRuleIndex].test = /\.(ico|eot|otf|ttf|woff|woff2|cur|ani|pdf)(\?.*)?$/;
```

### Failure Logs
No logs, just an image not found when loading the static asset url.

### Environment
Node : 12.21.0
  OS   : linux x64
  yarn : 1.22.5
  
  nx : 11.5.1
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.10
  @nrwl/cypress : 11.2.10
  @nrwl/devkit : 11.2.10
  @nrwl/eslint-plugin-nx : 11.2.10
  @nrwl/express : 11.2.10
  @nrwl/jest : 11.2.10
  @nrwl/linter : 11.2.10
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.2.10
  @nrwl/react : 11.2.10
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.10
  @nrwl/web : 11.2.10
  @nrwl/workspace : 11.2.10
  typescript : 4.1.5

**Comment by FrozenPandaz** [comment]
@juristr is this something that #4799 would fix?

**Comment by juristr** [comment]
@FrozenPandaz yeah could be. I'll verify tomorrow.

**Comment by juristr** [comment]
So yeah, basically the problem is the Storybook configs need to be fixed. I'll fix that in the PR mentioned above. 

Meanwhile ppl can apply the workaround mentioned by @AndrewTBurks if they run into it. Thx for reporting this @AndrewTBurks!

**Comment by juristr** [comment]
Nx 12.7 has a new React Storybook preset which we export as part of `@nrwl/react`. That should fix the issue. 

Here's a preview doc which will obviously be online on nx.dev once it is released: https://nx-dev-git-refactor-react-storybook-setup-nrwl.vercel.app/preview/react/storybook/migrate-webpack-final

The easier is to upgrade once 12.7 is out, generate a new library with Storybook and inspect the setup.

**Comment by AndrewTBurks** [comment]
Great, thank you @juristr for the fix + the follow-up comment!

**Comment by evanjmg** [comment]
@juristr is there any more instructions on this? Upgrading workspace individually doesn't work. I assume we need to update specific libs with the nx migrate command? Which ones?

**Comment by juristr** [comment]
@evanjmg This doc should have the details how the Storybook setup should look like with the React Storybook Preset we provide: https://nx.dev/l/r/storybook/migrate-webpack-final

Best might also be to just generate a new lib + storybook setup and copy it from there. Would be the easiest. But that should work. Otherwise, can you try to setup a new Nx workspace compare the install libs with the one you mentioned where it doesn't work? It might be something specific to your workspace setup then.
