### ISSUE TITLE
[Question] versioning libs and apps.

### ISSUE THREAD

**Issue by brunano21** [nrwl/nx#553]
Hi all.

I think this can be related to https://github.com/nrwl/nx/issues/309, even though an answer has not been provided yet.

For an enterprise project, I'm thinking to explore and adopt Nrwl. After going through docs and issues, I'm wondering if there could be a way (trick or strategy) of using a particular version of a library (under `libs/`). Specifically let's assume the following scenario: I have one application only - `app1` - and multiple libraries (Angular features) - most likely they will be lazy loading features/modules. Each team can/should work on one feature only and will be in somehow responsible only for that one.

 With these premises, is there a way to make the main application depending on a specific version of a library? 

Per my understanding, and as also stated in Nrwl Code Organization docs, we usually don't need to publish a library, because its client is an application that lives in the same workspace. However in this way, we cannot deploy our application which depends on `libs/libA@0.1.0` and `libs/libB@2.4.0`. We cannot beacuse there is only one package.json at root-level.

**Comment by helgetan** [comment]
Just bumping up this Question ;)

**Comment by vsavkin** [comment]
We authored a free book on using Nx (https://go.nrwl.io/angular-enterprise-monorepo-patterns-new-book?utm_campaign=Book%3A%20Monorepo%20Patterns%2C%20Jan%202019&utm_source=Github&utm_medium=Banner%20Ad). It goes into some detail on using trunk-based development, which is related to what you are asking.

**Comment by nhhockeyplayer** [comment]
that book is not searchable

couldnt find anythign on vewrsioned api either
