### ISSUE TITLE
Generate gzipped files for apps by default

### ISSUE THREAD

**Issue by AlexAegis** [nrwl/nx#5537]
I used this webpack plugin: https://github.com/webpack-contrib/compression-webpack-plugin for a good while, but in an NX workspace I can't seem to add it. That's a topic on it's own, but I think it would be a good idea to just gzip everything built if it's an app by default.

**Comment by FrozenPandaz** [comment]
Are you working on a React project of some sort?

You can use the `webpackConfig` option to customize the webpack configuration.

You can see something similar being done here:
https://github.com/nrwl/nx/issues/3175#issuecomment-644296842

**Comment by AlexAegis** [comment]
@FrozenPandaz nope, it's an Angular project and the `@angular-devkit/build-angular:browser` builder doesn't accept a custom webpackConfig.

```sh
> nx run core-demo:build:production 
'webpackConfig' is not found in schema
```

I can though use a different builder:

```sh
npm i -D @angular-builders/custom-webpack compression-webpack-plugin
```

```json
	"architect": {
				"build": {
					"builder": "@angular-builders/custom-webpack:browser",
					"options": {
						"customWebpackConfig": {
							"path": "./webpack.config.js",
							"mergeStrategies": {
								"externals": "replace"
							}
						},
```

webpack.config.js

```js
const CompressionPlugin = require('compression-webpack-plugin');

module.exports = {
	plugins: [new CompressionPlugin()],
};
```

Anyway, what do you think about gzipping built apps by default? I think it's a common enough thing to do, or at least it should be.
