### ISSUE TITLE
x-prompt boolean doesn't work after upgrading @nrwl/* from 11.6 to 12.X 

### ISSUE THREAD

**Issue by pablocdev** [nrwl/nx#5547]
## Current Behavior
We have created a project generator with nx-plugin. When we have updated the version of @nrwl from 11.6 to 12.1, the boolean fields with x-prompt have stopped working

## Expected Behavior
Boolean fields with x-promt should work in version 12.X, same as in version 11.6

## Steps to Reproduce

- First of all, create an empty workspace `npx create-nx-workspace`, type a name, select an empty template and select "No" when propt for Nx-Cloud
- Link our custom generator to this project with `npm link @myorg/mypackage`

### 11.6 - Before upgrade 
- Check workspace nx version with `nx --version`
![image](https://user-images.githubusercontent.com/23481169/116980783-f347c080-acc6-11eb-8156-4f6c094c102c.png)
- Execute generator with `nx g @myorg/mypackage:mygenerator` and follow base steps
![image](https://user-images.githubusercontent.com/23481169/116981028-491c6880-acc7-11eb-855a-7f11123c4286.png)
- All works fine

### 12.1 - After upgrade
- Now upgrade all packages with `ncu -u` and `npm i` in my workspace monorepo
![image](https://user-images.githubusercontent.com/23481169/116981406-bb8d4880-acc7-11eb-99cd-406d635b0969.png)
- Check workspace nx version with `nx --version`
![image](https://user-images.githubusercontent.com/23481169/116981485-d65fbd00-acc7-11eb-9589-baf4a6354c48.png)
- Execute generator with `nx g @myorg/mypackage:mygenerator` and follow base steps with same options
![image](https://user-images.githubusercontent.com/23481169/116981652-1e7edf80-acc8-11eb-8dd8-6476052aff88.png)
- Now, all boolean fields with x-prompt throw an error

### Our generator schema.json file
![image](https://user-images.githubusercontent.com/23481169/116981999-90572900-acc8-11eb-9914-3c65951a3203.png)

### Our generator repository, where `packages/nx/src/generators/nextjs` is the generator used to test this issue
***Our Readme is not up to date, so please ignore it***
https://github.com/Desarrollo-Util/nx-learnthis/tree/master/packages/nx

**Comment by leosvelperez** [comment]
Thanks for reporting this!

In v12 we replaced the usage of `inquirer` with `enquirer` for prompts. Both offer similar functionalities, but the latter provides better performance, so we were able to improve the Nx cli startup performance. There seems to be an issue with using what we call `list` (`select` in `enquirer`) for boolean values. I think it was never intended to be used like that (or it could very well by a bug 🤷🏻 ) and the right type of prompt for boolean values would be `confirm`.

Could you please try changing your `boolean` properties that are using an `x-prompt` of type `list` to instead use an `x-prompt` if type `boolean`?

In the example you show, it would be something like:

```json
"useToast": {
  "type": "boolean",
  "default": true,
  "x-prompt": {
    "message": "Use toast (react-toastify)?",
	"type": "confirm"
  }
}
```

**Comment by leosvelperez** [comment]
I'm closing this since a workaround is provided. Please feel free to reopen it if you think there's still an issue.
