### ISSUE TITLE
Add testing capabilities to workspace generators

### ISSUE THREAD

**Issue by mehrad-rafigh** [nrwl/nx#5548]
## Description
Currently there is no easy way to test workspace generators and there is no documentation on how to do this.

## Motivation
Generators like everything else should be testable. Users of nx should not be forced to migrate their workspace generators to nx-plugins

## Suggested Implementation
The same way that nx-plugins are tested

**Comment by mehrad-rafigh** [comment]
Hey @vsavkin Any update on this? Our team really depends on this and we do not want to migrate to a plugin in order to be able to test our schematics

**Comment by junekpavel** [comment]
Hi! Really missing this feature as well. Although I figured a way how to do this - create custom jest configuration for tools:

1. Update the `tools/tsconfig.tools.json` file to exclude spec files:
```
"exclude": ["**/*.spec.ts"],
```

2. Create the `tools/tsconfig.spec.json` file with following content (mostly copied from some library):
```
{
  "extends": "./tsconfig.tools.json",
  "compilerOptions": {
    "outDir": "../dist/out-tsc/tools",
    "module": "commonjs",
    "types": ["jest", "node"]
  },
  "include": ["**/*.spec.ts"]
}
```

3. Create the `tools/jest.config.js` file with following content (mostly copied from some library): 
```
module.exports = {
  displayName: 'tools',
  preset: '../jest.preset.js',
  globals: {
    'ts-jest': {
      tsconfig: '<rootDir>/tsconfig.spec.json',
    },
  },
  testEnvironment: 'node',
  transform: {
    '^.+\\.[tj]sx?$': 'ts-jest',
  },
  testTimeout: 10000,
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  coverageDirectory: '../coverage/tools',
};
```

4. Now you can run ` jest --config tools/jest.config.js` (or create shortcut in package.json scripts).

**Comment by pongells** [comment]
For anyone stumbling here: workspace generators are deprecated in favour of local generators. Tests will work there.
