### ISSUE TITLE
waitUnitTargets for @nrwl/node:build executor

### ISSUE THREAD

**Issue by linbudu599** [nrwl/nx#5551]
## Description

Just like `@nrwl/node:execute` schema includes `waitUntilTargets` option to ensure some targets to be invoked before starting(executing) application, sometimes build executor will also need to wait some extra works to be done. As nx doesnot expose this 'hook' for build executor, we'll need to fork the entire build execuotr source code and add own 
 custom codes, when we have a lots of things to do, the code would be ...

Also, as there might be some works which need to be processed after the execute/build/package, maybe a `executeAfterTargets` is considerable ?

## Motivation

Help developers to customize targets execution progress better, plugin developers especially. In fact, I got this idea just when I'm creating nx plugin integration with Prisma, which requires extra works after application build.

**Comment by heathprovost** [comment]
Just +1'ing this. Could really use it.

**Comment by heathprovost** [comment]
Posting a specific use case...

We currently use [@graphql-codegen](https://www.npmjs.com/package/@graphql-codegen/cli)  and are doing something like this in our workspace.json to ensure it runs whenever the schema file gets changed:

`"targets": {
        "build": {
          "executor": "@nrwl/node:build",
          "outputs": ["{options.outputPath}"],
          ...
        },
        "codegen": {
          "executor": "@nrwl/workspace:run-commands",
          "options": {
            "commands": [
              "graphql-codegen"
            ],
            "cwd": "apps/graphql-notifications",
            "parallel": false
          }
        },
        "codegen-watch": {
          "executor": "@nrwl/workspace:run-commands",
          "options": {
            "commands": [
              "graphql-codegen --watch src/assets/schema.graphql"
            ],
            "cwd": "apps/graphql-notifications",
            "readyWhen": "Watching for changes...",
            "parallel": true
          }
        },
        "serve": {
          "executor": "@nrwl/node:execute",
          "options": {
            "inspect": false,
            "waitUntilTargets": [ "graphql-notifications:codegen-watch" ],
            "buildTarget": "graphql-notifications:build"
          }
        },`

So the idea is we are using WaitUntilTargets to execute codegen in watch mode when serve target is run. This works, but serve _already_ has a watcher that is watching the same file(s) that triggers build on changes, so we **could** do this (I think) if node:build supported WaitUntilTargets:

`"targets": {
        "build": {
          "executor": "@nrwl/node:build",
          "outputs": ["{options.outputPath}"],
          "options": {
            "waitUntilTargets": [ "graphql-notifications:codegen" ]
          },
          ...
        },
        "codegen": {
          "executor": "@nrwl/workspace:run-commands",
          "options": {
            "commands": [
              "graphql-codegen"
            ],
            "cwd": "apps/graphql-notifications",
            "parallel": false
          }
        },
        "serve": {
          "executor": "@nrwl/node:execute",
          "options": {
            "inspect": false,
            "buildTarget": "graphql-notifications:build"
          }
        },`

Much simpler. Now whenever a build is triggered by a file change, the codegen runs first. Thanks for consider.
