### ISSUE TITLE
[feature request] Storybook Composition Support

### ISSUE THREAD

**Issue by ChazUK** [nrwl/nx#5561]
## Description
Storybook 6.2 comes with many new improvements, especially with composing stories for Angular.

**Comment by puku0x** [comment]
I'm looking forward to Nx v13 because the feature is on its roadmap! https://github.com/nrwl/nx/discussions/5475

**Comment by Jordan-Hall** [comment]
I've notice Storybook comes with enums. Don't we validate against the enum values? If so, I think it needs removing so 3rd party plugins can easily add storybook support

**Comment by FrozenPandaz** [comment]
I changed the title to be specific to composing storybooks as we already support Storybook 6.2.

Are there any other Storybook features that you think Nx should provide better support for?

**Comment by Jordan-Hall** [comment]
@FrozenPandaz  I was thinking maybe just to support them all in term of generation storybook configuration such as Vue and svelte and then let the 3rd party extension write the story generation.

**Comment by mandarini** [comment]
@Jordan-Hall @puku0x @ChazUK 

Is this issue referring to [Storybook Composition support](https://www.chromatic.com/blog/storybook-composition/)?

**Comment by ChazUK** [comment]
It was more around the different way's stories can be written now https://storybook.js.org/docs/angular/writing-stories/introduction

**Comment by mlebarron** [comment]
I definitely understood this and the roadmap item as this as what @mandarini said, composition support.

**Comment by ChazUK** [comment]
@mlebarron sorry that is true. I just checked my old team slack and that is what we were trying to achieve. Composing Storybooks not Stories

**Comment by mandarini** [comment]
Ok, so, to avoid any confusion:

We now support Storybook 6.2 and the new syntax of writing stories. So, that's one part of this issue that's solved. You can use the latest version of Nx and you will get all the new fun stuff of Storybook 6.x.

Eventually, we are planning to support Storybook Composition, in Nx 13. I am supposed to be working on it. I will link [this issue](https://github.com/nrwl/nx/issues/4252) here, too.

So, I will keep you updated, and once I have a PR ready, I will post it here.

**Comment by mandarini** [comment]
PR ready, for anyone who wants to give it a try

**Comment by SunStupic** [comment]
@mandarini How to try your generator?

**Comment by mandarini** [comment]
It's not published yet!!!! :) @SunStupic only the PR is in progress, and some things are to be added. You would be able to try it if you publish a local version of Nx!

**Comment by mandarini** [comment]
linking this here https://github.com/nrwl/nx/issues/8287

**Comment by sigginjals** [comment]
What is the status here? Do we have an ETA?

**Comment by mandarini** [comment]
No ETA yet, @sigginjals . :( We're focusing on bugs at the moment. I'll try to add this in my schedule, soon, though. I'll produce a guide sooner or later.

**Comment by mandarini** [comment]
We've [published some docs](https://nx.dev/storybook/storybook-composition-setup) that explain how to set this up in your Nx workspace, until we have some generators and executors to do it automatically!

**Comment by puku0x** [comment]
Thank you so much!

Currently, I use compositions only on local because Chromatic does not support monorepo😂

```js
refs: (_, { configType }) => {
  return configType === 'DEVELOPMENT'
    ? {
        'components': {
          title: '@workspace/components',
          url: 'https://localhost:4401',
        },
      }
    : undefined;
},
```

**Comment by sir-captainmorgan21** [comment]
Looks like addons dont work when composing storybooks :(

**Comment by sir-captainmorgan21** [comment]
@beaussan that is actually the suggestion in a youtube video I saw. You basically create an empty lib, Add storybook configuration to it, and then update the find paths to look in the entire `packages` directory.

**Comment by mlebarron** [comment]
@beaussan yeah I have a dedicated "docs" app that just pulls stories in from all over the repo. I'm still not clear on the value of having actual storybook running all over the place

**Comment by mandarini** [comment]
Hello all! Do you think it's ok to close this? There is support for Storybook composition (out of the box), [here's how to set it up](https://nx.dev/storybook/storybook-composition-setup). At some point we may issue some generators to set it up in a more automatic way, but that would just be an extra. If you want to use Storybook composition, Nx is already fully capable of supporting! :) 

Let me know and I can open this up again if anyone is really having trouble! :)
