### ISSUE TITLE
prefer local installed package in nx run-commands

### ISSUE THREAD

**Issue by linbudu599** [nrwl/nx#5572]
## Description

Support local installed packages to be used by nx run-commands, just like npm scripts do.
Since run-commands is now handled by origin nodejs child_process, [npm-run-path](https://www.npmjs.com/package/npm-run-path) can easily help to make local installed packages avaliable in run-commands.

## Motivation

This will greatly decrease the plugin developing, for example, when creating plugins with some packages which didn't expose proper interface for programmatic usage, enable invoking package cli directly will be useful.

## Suggested Implementation

Add `preferLocal` option to preserved schema option, when this option is enabled, use npm-run-path to process env just like :
```javascript
if (preferLocal) {
  return npmRunPath.env({env, cwd: localDir, execPath});
}
```

Add processed env to `createProcess` [here](https://github.com/nrwl/nx/blob/master/packages/workspace/src/executors/run-commands/run-commands.impl.ts#L177).

**Comment by FrozenPandaz** [comment]
That's a good idea!

Would you like to try contributing this feature?

**Comment by rubiagatra** [comment]
I would like to take a look into this

**Comment by linbudu599** [comment]
> This issue should be closed right @FrozenPandaz ?

Yep, you can close it now.
