### ISSUE TITLE
Running affected:libs rebuilds everything when new publishable lib is added

### ISSUE THREAD

**Issue by electrofLy** [nrwl/nx#5573]
## Current Behavior
Running `affected:libs` rebuilds everything when adding a new publishable library. 

After some investigation we found out that it is because the `tsconfig.base.json` is edited to add a publishable library (new library added to `paths`).

## Expected Behavior
Running `affected:libs` builds only the newly added library.

## Steps to Reproduce

1. Create an Angular NX workspace.
2. Add a **publishable** library.
3. Push it to master.
4. Add another **publishable** library.
5. Run `affected:libs`

### Failure Logs
Not relevant.

### Environment
```
  Node : 16.0.0
  OS   : win32 x64
  npm  : 7.10.0

  nx : Not Found
  @nrwl/angular : 11.5.2
  @nrwl/cli : 11.5.2
  @nrwl/cypress : 11.5.2
  @nrwl/devkit : 11.5.2
  @nrwl/eslint-plugin-nx : 11.5.2
  @nrwl/express : Not Found
  @nrwl/jest : 11.5.2
  @nrwl/linter : 11.5.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.5.2
  @nrwl/web : Not Found
  @nrwl/workspace : 11.5.2
  @nrwl/storybook : 11.5.2
  @nrwl/gatsby : Not Found
  typescript : 4.0.7

```

**Comment by owehmer** [comment]
@electrofLy  I'm guessing you are using something like this in your `nx.json`?
![image](https://user-images.githubusercontent.com/45573843/117709583-65da0400-b1d1-11eb-9796-f51d25908299.png)

That means that every time one of these files gets changed you are telling NX to rebuild everything.

If you don't like this behavior you need to delete the `tsconfig.base.json` from this list.

**Comment by FrozenPandaz** [comment]
@owehmer is right! and in fact, this is now the default behavior in `v12` when you create a new workspace. Could you please retry with the latest version?
