### ISSUE TITLE
NextJS build doesn't handle buildLibsFromSource

### ISSUE THREAD

**Issue by Bielik20** [nrwl/nx#5577]
## Current Behavior

Running `nx run react-demo:serve` results in

```
Please build these libraries first:
- ...

Try: `nx build react-demo --with-deps`
```

Running `nx run my-nextjs-app:serve --with-deps` results in the same message.

Running `nx run my-nextjs-app:serve --buildLibsFromSource` results in the same message.

Running `nx run my-nextjs-app:serve --withDeps` works.

## Expected Behavior

**Running `nx run my-nextjs-app:serve --buildLibsFromSource` should work without a need to build libs.**

Running `nx run my-nextjs-app:serve --with-deps` should also work just like `withDeps`, or at least the error message should be changed.

## Steps to Reproduce

* Create NextJS application.
* Create buildable lib.
* Try serving NextJS application.

Current example: https://github.com/Bielik20/ts-libs/pull/3/checks?check_run_id=2501403561

### Failure Logs
```
Some of the project react-demo's dependencies have not been built yet.

Please build these libraries first:
- react-di
- ts-utils
- http-client

Try: nx build react-demo --with-deps
```

### Environment
```
  Node : 12.18.3
  OS   : darwin x64
  npm  : 6.14.12
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.1.1
  @nrwl/cypress : 12.1.1
  @nrwl/devkit : 12.1.1
  @nrwl/eslint-plugin-nx : 12.1.1
  @nrwl/express : 12.1.1
  @nrwl/jest : 12.1.1
  @nrwl/linter : 12.1.1
  @nrwl/nest : Not Found
  @nrwl/next : 12.1.1
  @nrwl/node : 12.1.1
  @nrwl/react : 12.1.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.1.1
  @nrwl/web : 12.1.1
  @nrwl/workspace : 12.1.1
  @nrwl/storybook : 12.1.1
  @nrwl/gatsby : Not Found
  typescript : 4.1.4
```

### Additional Info

In this commit: https://github.com/nrwl/nx/commit/d767261 web dev server handles that.
But this PR for NextJS https://github.com/nrwl/nx/pull/5360 doesn't support it.

**Comment by Bielik20** [comment]
This is update blocker for us. Could we get an estimate when and if this will be addressed?

**Comment by FrozenPandaz** [comment]
@kirjai could you please add a flag similar to https://github.com/nrwl/nx/blob/1c714de84487fd4a40f0ba065ac2f3b8e4425946/packages/web/src/builders/build/build.impl.ts#L130

**Comment by BasileNouvellet** [comment]
It seems that this flag is also needed in the `@nrwl/web:package` executor. Currently, it is not possible to pass the `buildLibsFromSource` option for a buildable library relying on other buildable libraries.
