### ISSUE TITLE
Unable to "take snapshot" of Memory when running tests in debug mode

### ISSUE THREAD

**Issue by tar-aldev** [nrwl/nx#5581]
## Current Behavior

I am following your example of running tests in debug mode which is
```
node --inspect-brk ./node_modules/@nrwl/cli/bin/nx test backend
```

I am able to connect to this debugger via dedicated node devtools .
I am able to take snapshot in Memory -> Take snapshot.
However as soon as I am starting the tests (by going to Sources -> Resume script execution)
The following happens:
1. It gives error saying 
 nx run backend:test 
Starting inspector on 127.0.0.1:9229 failed: address already in use
(which I cannot understand at all)
2. I am unable to make any snapshots anymore - it will hang forever saying 
Snapshot 1
<some number of percentage>
Looks like debugger just stops listening at this point but tests continue to run
3. And the most awful and annoying - I am not able to stop the tests with ctrl + c anymore

## Expected Behavior

Ability to make snapshot of memory or at least add some more information to documentation as now it is not clear at all what should happen after
```
node --inspect-brk ./node_modules/@nrwl/cli/bin/nx test backend
```

## Steps to Reproduce

1. Run tests in debug mode with the above script
2. connect debugger
3. in sources resume execution
4. Go to Memory tab
5. try to take a snapshot

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

nx : 12.0.8
  @nrwl/angular : Not Found
  @nrwl/cli : 12.0.8
  @nrwl/cypress : 12.0.8
  @nrwl/devkit : 12.0.8
  @nrwl/eslint-plugin-nx : 12.0.8
  @nrwl/express : 12.0.8
  @nrwl/jest : 12.0.8
  @nrwl/linter : 12.0.8
  @nrwl/nest : Not Found
  @nrwl/next : 12.0.8
  @nrwl/node : 12.1.0
  @nrwl/react : 12.1.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.8
  @nrwl/web : 12.0.8
  @nrwl/workspace : 12.0.8
  @nrwl/storybook : 12.1.0
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by FrozenPandaz** [comment]
Can you take a snapshot if you run `node --inspect-brk ./node_modules/@nrwl/cli/bin/nx test products` in the [nx-examples repo](https://github.com/nrwl/nx-examples)?

I was able to take a snapshot.

![image](https://user-images.githubusercontent.com/8104246/118339104-dd67a600-b4e5-11eb-8df7-b1eb7da24f49.png)
