### ISSUE TITLE
Cannot use component from library in Next.js app

### ISSUE THREAD

**Issue by luchsamapparat** [nrwl/nx#5584]
## Current Behavior
Using a component from a library in an Next.js fails in production.

![image](https://user-images.githubusercontent.com/875017/117330017-8d5d6380-ae95-11eb-87d2-2e253a2e852c.png)

EDIT: I just noticed that in the [reproduction repo](https://github.com/luchsamapparat/nextjs-lib-reproduction) mentioned below `nx serve` also fails, but with another error:
EDIT2: After completely removing the project and cloning it again, `nx serve` works without issues. So maybe this is an unrelated issue 🤨

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

In my actual project, this problem does not occur.

## Expected Behavior
It should work.

## Steps to Reproduce

```
npx create-nx-workspace nextjs-lib-reproduction

√ What to create in the new workspace · next
√ Application name                    · nextjsapp
√ Default stylesheet format           · scss
√ Use Nx Cloud? (It's free and doesn't require registration.) · No

cd nextjs-lib-reproduction
nx g lib foo

√ Which stylesheet format would you like to use? · scss
```

Import the generated `Foo` component from the library:

```tsx
// apps/nextjsapp/pages/index.tsx
import { Foo } from '@nextjs-lib-reproduction/foo';
import React from 'react';


export function Index() {
  return (
    <Foo />
  );
}

export default Index;
```

Then build and start the app:

```
npm run build
cd dist/apps/nextjsapp
npm install
npm start
```

The page should now look like this:

![image](https://user-images.githubusercontent.com/875017/117330603-27251080-ae96-11eb-85aa-3b186859a43d.png)

You can reproduce the error with the project in this repository:
https://github.com/luchsamapparat/nextjs-lib-reproduction

### Failure Logs
No errors during build. Only at runtime as in the screenshot above.

### Environment
```

>  NX  Report complete - copy this into the issue template

  Node : 14.16.1
  OS   : win32 x64
  npm  : 6.14.12
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.1.1
  @nrwl/cypress : 12.1.1
  @nrwl/devkit : 12.1.1
  @nrwl/eslint-plugin-nx : 12.1.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.1.1
  @nrwl/linter : 12.1.1
  @nrwl/nest : Not Found
  @nrwl/next : 12.1.1
  @nrwl/node : Not Found
  @nrwl/react : 12.1.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.1.1
  @nrwl/web : 12.1.1
  @nrwl/workspace : 12.1.1
  @nrwl/storybook : 12.1.1
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

**Comment by luchsamapparat** [comment]
This seems to be a regression. When I set up the workspace with `npx create-nx-workspace@11 nextjs-lib-reproduction`, it works.

**Comment by bradbarrow** [comment]
https://github.com/nrwl/nx/issues/5312
