### ISSUE TITLE
When creating an Production Build, process.env.NODE_ENV is set to "development" in react

### ISSUE THREAD

**Issue by Fibs7000** [nrwl/nx#5592]
When creating an Production Build, process.env.NODE_ENV is set to "development" in react

## Current Behavior
When creating an Production Build, process.env.NODE_ENV is set to "development" in react

## Expected Behavior
When creating an Production Build, process.env.NODE_ENV should be set to "production" in react

## Steps to Reproduce

React Version: @nrwl/react@11.5.1

run nx build [projectname]

### Environment

```
  Node : 10.24.0
  OS   : linux x64
  yarn : 1.22.10
  
  nx : 11.4.0
  @nrwl/angular : Not Found
  @nrwl/cli : 11.5.1
  @nrwl/cypress : 11.5.1
  @nrwl/devkit : 11.5.1
  @nrwl/eslint-plugin-nx : 11.5.1
  @nrwl/express : Not Found
  @nrwl/jest : 11.5.1
  @nrwl/linter : 11.5.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.5.1
  @nrwl/react : 11.5.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.5.1
  @nrwl/web : 11.5.1
  @nrwl/workspace : 12.1.1
  @nrwl/storybook : 11.5.1
  @nrwl/gatsby : Not Found
  typescript : 4.2.2
```

**Comment by puku0x** [comment]
You should build your app with `--prod` option.
https://nx.dev/latest/react/cli/build#build

```
npx nx build projectname --prod
npx nx build projectname --configuration=production
```

If you prefer `npm run`, you will need additional hyphens.
```
npm run nx build projectname -- --prod
npm run nx build projectname -- --configuration=production
```

**Comment by puku0x** [comment]
Good news. #5630 has been merged and you will be able to build your application in production mode by default by setting `defaultConfiguration` to `production`.

**Comment by Fibs7000** [comment]
What exactly determines the Production build? Is it the optimize flag?

Cause without the optimize flag but the prod config env is "development"...

**Comment by puku0x** [comment]
@Fibs7000 Yes, the `optimization` flag in `workspace.json` is.
https://nx.dev/latest/react/core-concepts/configuration

You should specify the `configuration` which has `optimization: true` when you when production build.
```
# --prod is shorthand for --configuration=production
npx nx build projectname --prod
```
