### ISSUE TITLE
Common Environment Variables

### ISSUE THREAD

**Issue by wbhob** [nrwl/nx#56]
Nx IS AWESOME! I love it soo much. I have just a couple feature requests:
1. Shared assets folder. This is particularly useful if you have CSS libraries shared between apps.
2. Shared environments. This is useful when sharing apiUrls and the like.

Otherwise, keep rocking!

**Comment by jschwarty** [comment]
Thanks @wbhob, glad you like it! In terms of your feature requests, you can actually set up your Nx Workspace to accomplish these things right now.

1. You can make a new lib (`ng g lib assets`) in your workspace, put your shared asset files in the `src` dir of that, and in the `.angular-cli.json` file in the `apps` array and add a [glob entry](https://github.com/angular/angular-cli/wiki/stories-asset-configuration) for your shared assets to be used by each app:

```
{
  "input": "../../../libs/assets/src/",
  "output": "assets/",
  "glob": "**/*"
}
```

2. You can do a similar thing with environments, creating a new lib (`ng g lib environments`) and then importing constants from those into your app environment files and merging them into your app environment constants. Add something like a `sharedEnvironments` const to the lib that has properties for `development` and `production` and use them in your app environments:

**/apps/<yourapp>/src/environments/environment.ts**
```typescript
import {sharedEnvironment} from '@nxenv/environments';

export const environment = {
  production: false,
  apiUrl: sharedEnvironment.development.apiUrl
};
```

**/apps/<yourapp>/src/environments/environment.prod.ts**
```typescript
import {sharedEnvironment} from '@nxenv/environments';

export const environment = {
  production: true,
  apiUrl: sharedEnvironment.production.apiUrl
};
```

**Comment by wbhob** [comment]
That's awesome! Thank you!

**Comment by FallenRiteMonk** [comment]
@jschwarty Could you please give me a hint on how you would then point an api in a lib to different urls?
Meaning I have a local deployed api endpoint during development (https://localhost/...) and a deployed one for production (https:example.com/...)

I cant seem to get my head wrapped around it. Using your approach from point 2 I would have to import the libs variables in every app and use a HttpsInterceptor to inject the url or something like that, but that would interfere with any other api endpoint that I would like to contact.

The other solution I can think of is importing environment into the api lib, but that would then make it useless to have it in a lib.

**Comment by jared-christensen** [comment]
@jschwarty I'm having a hard time figuring out exactly where that glob entry goes in the angular-cli.json. Is this correct?
```
"apps": [
  {
    "name": "assets",
    "root": "libs/assets/src",
    "test": "../../../test.js",
    "appRoot": "",
    "assets": [
      {
        "input": "../../../libs/assets/src",
        "output": "assets/",
        "glob": "**/*"
      }
    ]
  }
]
```

**Comment by srb11** [comment]
I am reviving this thread 9 months later.  
I would like to have a common "assets" lib for images and css, to be imported by many applications and a few existing component libs. However, in the time since this thread was active, angular-cli.json has been changed to angular.json, and I am not seeing an "apps[]" in it. 

In the meantime, a couple of weeks ago, I have begun implementing an nx workspace, and being newer, I may have missed something obvious.

Correct me if I am wrong - I am thinking that perhaps the structure of nx workspace `angular.json` has also changed in the last few months as well, and used to have `apps[]`, but now that is `projects {}`? 

Alternatively, if there is another nx best practice recommended for making global assets available to many apps, any guidance/examples/direction would be fantastic.

**Comment by joelcipriano** [comment]
Nice!

But has anyone tried or has a working example?

**Comment by SWGeekPD** [comment]
@FallenRiteMonk  did you found any solution.

**Comment by FallenRiteMonk** [comment]
@SWGeekPD I use injection.

In a helper lib I define a InjectionToken:
```export const ENVIRONMENT = new InjectionToken<{}>('Environment');```
Which I then inject wherever it's needed:
```constructor(@Inject(ENVIRONMENT) private environment: {}) {}```
