### ISSUE TITLE
extra lib folder added to lib schematics for nx6.0

### ISSUE THREAD

**Issue by goelinsights** [nrwl/nx#560]
Is there a reason why the lib schematic added a subfolder for libs under the lib name? Seems to add a breaking change from the existing folder structure and an extra subfolder...don't understand a benefit (didn't see this referenced in other issues).  Having some trouble generating ngrx in the right folder following the change (not sure if it's related or documentation is just behind) but it seems unnecessarily confusing unless there is an underlying reason for adding a subfolder named lib two levels below the libs folder
```
expect(
-          tree.exists('libs/my-dir/my-lib/src/my-lib.module.ts')
+          tree.exists('libs/my-dir/my-lib/src/lib/my-dir-my-lib.module.ts')
```
https://github.com/nrwl/nx/commit/907ec275282fde223a33048abe3276ef7151b334#diff-cfffc0c5b67e13d32cfd4ddeb76d3b68
...schematics/src/collection/lib/lib.spec.ts

**Comment by goelinsights** [comment]
Also noticed that the index.ts file is in /src.  This makes the import look something like:
`import { MyModule } from '@workspace/my-directory/my-module/src';` instead of the my-module directory

**Comment by goelinsights** [comment]
re: APIs and imports this does lead to a best practice question of how to set up API access to action statements within a lib.  should they be exported via index files if they need to be used elsewhere in the app (or in my case I'm separating out UI from state libs for each feature, as this is how I can re-use state for things like AMP that need a different UI...since it looks like deep imports are moving toward being excluded in the future, what's the right pattern here?)

**Comment by StefanKoenen** [comment]
Any update on this question please?

**Comment by vsavkin** [comment]
The reason to change the directory structure is to match the default structure generated by the Angular CLI. I'm not the biggest fan of it either. But imo it's better to be close to what the CLI does.

The `import { MyModule } from '@workspace/my-directory/my-module';` import should still work. tsconfig.json contains a path mapping of this sort:

```
''@workspace/my-directory/my-module': ['libs/my-directory/my-module/src/index.ts']
```

If you don't have the path mapping in place, something might have gone wrong during the upgrade process. You can add the needed path mapping manually.

**Comment by goelinsights** [comment]
That was it.  The tsconfig.json was off post-upgrade for some reason, in case anyone else encounters this.  I fixed it all with a fresh install.
