### ISSUE TITLE
Can't run redux slice generator for next.js

### ISSUE THREAD

**Issue by Himadu2000** [nrwl/nx#5605]
This is a follow up to discussion.

## Current Behavior
Redux slice generator currently only support CRA apps, currently running will produce following error,
`> Executing task: nx generate @nrwl/react:redux --name=next--project=app --no-interactive --dry-run <
Could not find apps\app\main.tsx during store configuration`

## Expected Behavior
> Executing task: nx generate @nrwl/react:redux --name=next --project=app --no-interactive --dry-run <

```
CREATE apps/app/src/app/next.slice.spec.ts
CREATE apps/app/src/app/next.slice.ts
UPDATE apps/app/src/main.tsx
```

Is this a regression? No.

## Steps to Reproduce
Create a basic project with `yarn create nx-workspace`,
and choosing next.js as application,
then running following command,
`nx generate @nrwl/react:redux --name=slice --project=app --no-interactive --dry-run`

### Failure Logs
`Could not find apps\app\main.tsx during store configuration`

### Environment
  Node : 14.16.0
  OS   : win32 x64
  npm  : 6.14.11

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.1.1
  @nrwl/cypress : 12.1.1
  @nrwl/devkit : 12.1.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 12.1.1
  @nrwl/linter : 12.1.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 12.1.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.1.1
  @nrwl/web : 12.1.1
  @nrwl/workspace : 12.1.1
  @nrwl/storybook : 12.1.1
  @nrwl/gatsby : Not Found
  typescript : 4.1.5

**Comment by asheroto** [comment]
Having this issue as well

**Comment by Mohendran** [comment]
Having this issue as well... This should be a higher priority.

**Comment by yuchant** [comment]
Making a blank main.tsx helped.

**Comment by yuchant** [comment]
Nevermind, no longer works even with blank main.tsx on 13.1.4

**Comment by Mohendran** [comment]
This issue is still isn't fixed.

**Comment by asheroto** [comment]
The blank file works for me...
```
yarn create nx-workspace
```
name the workspace something such as `blah` and the project something such as `blah`, then open `blah\apps\blah` and create an empty `main.tsx` file. Run this command under `blah\` (make sure to set the project name in the command)...
```
nx generate @nrwl/react:redux --name=slice --project=blah --no-interactive --dry-run
```

**Comment by Mush-A** [comment]
This is still an issue!
