### ISSUE TITLE
ng g ngrx seems broken in 6.0

### ISSUE THREAD

**Issue by goelinsights** [nrwl/nx#561]
After generating auth in libs:
```
ng g ngrx auth --module=libs/auth/src/lib/auth.module.ts
```

> Path "/libs/auth/src/lib/+state/auth.effects.spec.ts" does not exist.

**Comment by agalazis** [comment]
Same Here

**Comment by FrozenPandaz** [comment]
There are many nuances with moving to `@ngrx/*@6.0.0+`. @ThomasBurleson might have more specific details.

It's more recommended to stay on `@ngrx/*@5.x.x`.

**Comment by goelinsights** [comment]
@FrozenPandaz from my initial experience I agree... I had thought it was a bit more ready to go given Victor's announcement that v6 was here https://blog.nrwl.io/announcing-nrwl-nx-6-0-29b963d87d8e

Perhaps he should update that to make it feel a bit more like it's still in RC or other framing to let people know the switch isn't as straightforward at the moment as he made it sound?

**Comment by agalazis** [comment]
sticking to 5.x wouldn't be ideal for new projects

**Comment by fballkmbs** [comment]
This is happening with @ngrx/*@5.2.0 as well. I created a workspace with create-nx-workspace then did:
```
ng g app school
ng g ngrx User --module apps/school/src/app/app.module.ts
```
and get:

Path "/apps/school/src/app/+state/User.effects.spec.ts" does not exist.

This is with @angular-cli@6.0.7 and @nrwl/schematics@6.0.4 installed globally.

**Comment by Maden-maxi** [comment]
I have the same issue in case with @ngrx/schematics@5.2.0, @nrwl/shematics@6.1.0, @angular/cli@6.0.1
That project had been generated by create-nx-workspace.
And in other case when I was generate a project by @angular/angular-cli@6.0.8. Then I had installed to this project @nrwl/schematics by command `yarn add @nrwl/schematics`.Then I was execute `ng update` and @ngrx packages had been updated to latest version.
On my machine I have @angular/cli@6.0.8 and @nrwl/schematics@6.1.0.
The latest case with @angular/cli@6.0.8 I had published to my repo https://github.com/Maden-maxi/founderinvest

**Comment by jeffbcross** [comment]
I ran into this issue when passing a camelcase name, `logsRoot`. It wasn't being dasherized, so was failing at the step where our schematic tries to move the result of calling the NgRx schematic. 

I.e. at this point `featureName` was expected to be `logs-root` but was actually `logsRoot`: https://github.com/nrwl/nx/blob/80b243eaca471bdebf365829b50d7de578343e7a/packages/schematics/src/collection/ngrx/index.ts#L187

**Comment by jasedwards** [comment]
I got it trying to set ngrx up at root.  no App.effect.spec.ts

**Comment by ankemp** [comment]
Any update on a fix or workaround for this?

**Comment by goelinsights** [comment]
@ankemp workaround is pretty simple...just don't use schematics and copy/paste the files

**Comment by jasedwards** [comment]
I am on ngrx 6 already and have this issue.  so upgrading does not fix it for me.

**Comment by agalazis** [comment]
could it be that I did `ng g ngrx app --module apps/school/src/app/app.module.ts` at some point ? 
Anw I ended up not using the schematics lates since I wanted to use feature modules and that wasn't the layout given

**Comment by frgul006** [comment]
I'm in the same boat as @jasedwards. Even trying with a simple name such as "demo" isn't working. I'm using nx 6.0.4 with ngrx 6.0.1.

**Comment by m-abs** [comment]
I get this error when with a new project.

**Comment by agalazis** [comment]
another thing is that have installed ngrx v6 schametics globally+ upgraded to v6
and
ng g ngrx app --module apps/school/src/app/app.module.ts (the app part there I think did the trick)
But before you waste more time to sort this put think twice dont's you want to layout you projrct in feature modules or use enittes? ofcourse you can plcae the output to any directory you want but what's generated is a bit off

**Comment by ankemp** [comment]
@m-abs what version(s) of ngrx are you using?

**Comment by m-abs** [comment]
@ankemp
 @ngrx/*@6.0.1  except for  `@ngrx/schematics`

**Comment by mlota** [comment]
Hi, I seem to still be having this issue using the latest release. Running `ng g ngrx foo --module/foo/src/lib/foo.module.ts` doesn't create any of the NGRX files in the lib folder. Also doesn't show any errors, just seems to fail silently. I have @nrwl/schematics 6.3.1 installed globally and the project is using ngrx 6.0.1. Any ideas?

**Comment by pascalwinter** [comment]
> Hi, I seem to still be having this issue using the latest release. Running `ng g ngrx foo --module=libs/foo/src/lib/foo.module.ts` doesn't create any of the NGRX files in the lib folder. Also doesn't show any errors, just seems to fail silently. I have @nrwl/schematics 6.3.1 installed globally and the project is using ngrx 6.0.1. Any ideas?
> 
> EDIT: Ok, so a bit more info here - the above command **does** work when I specify the --onlyAddFiles parameter

I am also experiencing this behavior in Nx 7.1.1.

**Comment by kamekazemaster** [comment]
> > Hi, I seem to still be having this issue using the latest release. Running `ng g ngrx foo --module=libs/foo/src/lib/foo.module.ts` doesn't create any of the NGRX files in the lib folder. Also doesn't show any errors, just seems to fail silently. I have @nrwl/schematics 6.3.1 installed globally and the project is using ngrx 6.0.1. Any ideas?
> > EDIT: Ok, so a bit more info here - the above command **does** work when I specify the --onlyAddFiles parameter
> 
> I am also experiencing this behavior in Nx 7.1.1.

I am experiencing the same behavior @nrwl/schematics 7.6.2 installed locally.

**Comment by luke-gav** [comment]
> > > Hi, I seem to still be having this issue using the latest release. Running `ng g ngrx foo --module=libs/foo/src/lib/foo.module.ts` doesn't create any of the NGRX files in the lib folder. Also doesn't show any errors, just seems to fail silently. I have @nrwl/schematics 6.3.1 installed globally and the project is using ngrx 6.0.1. Any ideas?
> > > EDIT: Ok, so a bit more info here - the above command **does** work when I specify the --onlyAddFiles parameter
> > 
> > 
> > I am also experiencing this behavior in Nx 7.1.1.
> 
> I am experiencing the same behavior @nrwl/schematics 7.6.2 installed locally.

Also experiencing this with @nrwl/schematics 7.7.2. Adding --onlyAddFiles lets command run.

**Comment by lifaon74** [comment]
Hi this issue should be re-opened as it's still broken . For example running:

```
ng g @nrwl/angular:ngrx products --module=C:/workspace/projects/app/apps/my-app/src/app/app.module.ts --facade -d
````

results in : `Path does not exist: C:/workspace/projects/app/apps/connect-four/src/app/app.module.ts`
