### ISSUE TITLE
Cannot use wrapped schematic within generator if it uses tree.getDir() internally

### ISSUE THREAD

**Issue by JamesHenry** [nrwl/nx#5616]
## Current Behavior

`tree.getDir` in a wrapped angular schematic does not properly visit files created within the Nx generator where it is used.

## Expected Behavior

The wrapped angular schematic can use `tree.getDir` to properly visit files created within the Nx generator where it is used.

## Steps to Reproduce

https://github.com/JamesHenry/nx-workspace-generator-get-dir-repro

**Comment by AgentEnder** [comment]
If I run `nx migrate latest` to migrate the reproduction repo to Nx 13, this passes now. Do you care to recheck it and see if its been fixed in your use cases?
