### ISSUE TITLE
Migration failing for 'rule is not a function'

### ISSUE THREAD

**Issue by jaqua** [nrwl/nx#5618]
I tried to migrate to 12.1.1, but the migration fails with this error:

```
>  NX  Running migrations from 'migrations.json'

Running migration update-jest-preset-angular-8-4-0
rule is not a function
/Users/project/node_modules/.pnpm/yargs@15.4.1/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /var/folders/wd/5kx_tycx49ldnvrn3_b6fylc0000gn/T/tmp-59448-HCUj9bW9akaS/node_modules/.bin/tao migrate --run-migrations
```

**Comment by leosvelperez** [comment]
@jaqua thanks for reporting this!

We need some more details so we can properly troubleshoot this issue. Could you please tell me from which version were you trying to migrate to 12.1.1? Also, could you please run `nx report` and share the results here?

**Comment by timdeschryver** [comment]
I also bumped against this issue (from Angular 11 and NX 12 to Angular 12 and NX 12.3).
It seems like we should use the [nx migrate](https://nx.dev/latest/react/core-concepts/updating-nx#how-to-migrate) command instead of `ng update`?

**Comment by jaqua** [comment]
I don't have any angular project in my workspace.

This is my nx report:

```
  Node : 14.16.1
  OS   : darwin x64
  pnpm : 6.2.5
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.2.0
  @nrwl/cypress : 12.2.0
  @nrwl/devkit : Not Found
  @nrwl/eslint-plugin-nx : 12.2.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.2.0
  @nrwl/linter : 12.2.0
  @nrwl/nest : 12.2.0
  @nrwl/next : 12.2.0
  @nrwl/node : 12.2.0
  @nrwl/react : 12.2.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.2.0
  @nrwl/web : 12.2.0
  @nrwl/workspace : 12.2.0
  @nrwl/storybook : 12.2.0
  @nrwl/gatsby : Not Found
  typescript : 4.1.4
```

**Comment by jaqua** [comment]
Even installing `@nrwl/angular`, the error persists.

The same error occurs also for this migration:

```
{
      "version": "12.1.0-beta.1",
      "description": "Replace tsConfig with tsconfig for ts-jest in jest.config.js",
      "factory": "./src/migrations/update-12-1-0/update-ts-jest",
      "package": "@nrwl/jest",
      "name": "update-ts-jest-6-5-5"
    }
```

**Comment by leosvelperez** [comment]
> I also bumped against this issue (from Angular 11 and NX 12 to Angular 12 and NX 12.3).
> It seems like we should use the [nx migrate](https://nx.dev/latest/react/core-concepts/updating-nx#how-to-migrate) command instead of `ng update`?

Yep, we definitely recommend using `nx migrate`.

**Comment by leosvelperez** [comment]
> @leosvelperez This is my nx report:
> 
> ```
>   Node : 14.16.1
>   OS   : darwin x64
>   pnpm : 6.2.5
>   
>   nx : Not Found
>   @nrwl/angular : Not Found
>   @nrwl/cli : 12.2.0
>   @nrwl/cypress : 12.2.0
>   @nrwl/devkit : Not Found
>   @nrwl/eslint-plugin-nx : 12.2.0
>   @nrwl/express : Not Found
>   @nrwl/jest : 12.2.0
>   @nrwl/linter : 12.2.0
>   @nrwl/nest : 12.2.0
>   @nrwl/next : 12.2.0
>   @nrwl/node : 12.2.0
>   @nrwl/react : 12.2.0
>   @nrwl/schematics : Not Found
>   @nrwl/tao : 12.2.0
>   @nrwl/web : 12.2.0
>   @nrwl/workspace : 12.2.0
>   @nrwl/storybook : 12.2.0
>   @nrwl/gatsby : Not Found
>   typescript : 4.1.4
> ```

That report shows a workspace using 12.2.0 which is a greater version than the 12.1.1 you refer to be migrating to. Could you please double check and share the results of the report when is run in the workspace prior migrating to 12.1.1?
