### ISSUE TITLE
Missleading Error message

### ISSUE THREAD

**Issue by wiesnery** [nrwl/nx#5625]
I just ran into this issue of importing my own lib via an external reference. (`@project/lib` vs. local path './file.ts`)
This could be better expresses when altering the error message.
https://github.com/nrwl/nx/blob/4b73b7c1f73159355b7f5ca5c78dd473e7570fa0/packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts#L85
Currently: "Only relative imports are allowed within the project. Absolute import found: XYZ"
My suggestion: "Only local relative imports are allowed for files which reside within the same project. Hint: use ./path/to/file instead of @project/library"

**Comment by FrozenPandaz** [comment]
Would you like to contribute a fix?

What about this for the message?

```
Projects should use relative imports to import other files within itself instead of absolute imports. i.e. Do not import from {{ imp }} within {{ root }}.
```
