### ISSUE TITLE
Tailwind's JIT mode wrong behavior due to the undefined NODE_ENV variable

### ISSUE THREAD

**Issue by BorisZubchenko** [nrwl/nx#5627]
## Current Behavior

Within the NX Workspace + Next.js Application, [Tailwind's JIT](https://tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode) mode:
* runs a one-off build while building

The thing is that [it's behavior](https://tailwindcss.com/docs/just-in-time-mode#watch-mode-and-one-off-builds) depends on the `NODE_ENV` variable which was fixed [recently](https://github.com/nrwl/nx/pull/5574). For now, this PR:
* sets the `NODE_ENV` variable only if we run a `build` command;
* [sets](https://github.com/nrwl/nx/pull/5574/files#diff-fcd96d0c9996c7987e1c72da9391cb2d845b36ab056886d02511dea284371c5dR26) the `NODE_ENV` variable only to `production` if it's `undefined`.

## Expected Behavior

* `NODE_ENV` must be set within both `build` and `serve` commands;
* `NODE_ENV` must be set `development` as well.

## Steps to Reproduce

Here's [a reproduction repo](https://github.com/BorisZubchenko/nx-tailwind-jit-issue). All steps are aligned to [the commits](https://github.com/BorisZubchenko/nx-tailwind-jit-issue/commits/main), but in short:
* Serve the application (dev).
* Go to the website. You will see a blue background.
* Open `_app.tsx`.
* Replace `bg-[#00f]` with any other Tailwind class.
* You will see no background anymore.

### Environment

```
 Node : 14.16.1
  OS   : linux x64
  npm  : 7.10.0
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.2.0
  @nrwl/cypress : 12.2.0
  @nrwl/devkit : 12.2.0
  @nrwl/eslint-plugin-nx : 12.2.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.2.0
  @nrwl/linter : 12.2.0
  @nrwl/nest : Not Found
  @nrwl/next : 12.2.0
  @nrwl/node : Not Found
  @nrwl/react : 12.2.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.2.0
  @nrwl/web : 12.2.0
  @nrwl/workspace : 12.2.0
  @nrwl/storybook : 12.2.0
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

**Comment by FrozenPandaz** [comment]
Seems like we can use a similar fix in the `serve.impl.ts` file: https://github.com/nrwl/nx/blob/1c714de84487fd4a40f0ba065ac2f3b8e4425946/packages/next/src/executors/server/server.impl.ts#L37

Would you like to contribute a fix?

**Comment by BorisZubchenko** [comment]
Yes, I will do a PR soon.

**Comment by patdx** [comment]
This issue affects me too, I was using a workaround of `NODE_ENV=development nx serve ...`, however it's hard to explain/remember. So, while waiting for the PR to get merged and new release, I am using the following workaround:

1. create a new .env file:

```
# scripts/node-env-development.env
# Temporary fix for Tailwind JIT mode
NODE_ENV=development
```

2. In workspace.json, rename the Next.js project's "serve" command to "serve-base":

```diff
-        "serve-base": {
+        "serve-base": {
          "builder": "@nrwl/next:server",
          "options": {
            "buildTarget": "helpdesk:build",
            "dev": true,
            "port": 4200
          },
```

3. In workspace.json, create a new "serve" command:

```
        "serve": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "command": "nx run {{NEXT_JS_PROJECT_NAME}}:serve-base",
            "envFile": "scripts/node-env-development.env"
          }
        },
```

Make sure to replace `{{NEXT_JS_PROJECT_NAME}}` with the name of your project.

**Comment by BorisZubchenko** [comment]
FYI, I remember about this issue and will fix it as soon as I have free time.
