### ISSUE TITLE
 Cannot find module '@nrwl/workspace/src/utils/name-utils'

### ISSUE THREAD

**Issue by naveennagar88** [nrwl/nx#5633]
Hi Team

I have created an application in angular 10. When I try to create a library using "ng generate library". I am getting the following error:
An unhandled exception occurred: Cannot find module '@nrwl/workspace/src/utils/name-utils'
Require stack:
- D:\Users\naveen.nagar\git\Angular10\getting-started\node_modules\@nrwl\angular\src\utils\ast-utils.js
- D:\Users\naveen.nagar\git\Angular10\getting-started\node_modules\@nrwl\angular\src\schematics\library\lib\add-children.js
- D:\Users\naveen.nagar\git\Angular10\getting-started\node_modules\@nrwl\angular\src\schematics\library\lib\add-module.js
- D:\Users\naveen.nagar\git\Angular10\getting-started\node_modules\@nrwl\angular\src\schematics\library\library.js
- D:\Users\naveen.nagar\git\Angular10\getting-started\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
- D:\Users\naveen.nagar\git\Angular10\getting-started\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
- D:\Users\naveen.nagar\git\Angular10\getting-started\node_modules\@angular\cli\utilities\json-schema.js
- D:\Users\naveen.nagar\git\Angular10\getting-started\node_modules\@angular\cli\models\command-runner.js
- D:\Users\naveen.nagar\git\Angular10\getting-started\node_modules\@angular\cli\lib\cli\index.js
- D:\Users\naveen.nagar\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- D:\Users\naveen.nagar\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
See "D:\Users\naveen.nagar\AppData\Local\Temp\1\ng-IQxtlW\angular-errors.log" for further details.

**Comment by leosvelperez** [comment]
@naveennagar88 thanks for reporting this!

Unfortunately, I can't reproduce the issue. I tried to reproduce it using Nx 10.4.15, though there's no clear indication on the issue regarding the specific version being used.

To help us address this issue, could you please provide the steps to reproduce it and share the results of the execution of `nx report`? Or better yet, could you share a repro repo?
