### ISSUE TITLE
eslint tries to resolve conf from project node_modules using yarn workspaces

### ISSUE THREAD

**Issue by edbzn** [nrwl/nx#5671]
## Current Behavior

I'm using yarn workspaces to manage projects dependencies, so I have a root node_modules, and per project node_modules because it's multiple package that are deployed to npm. After upgrading to v12, eslint tries to resolve configurations inside projects node_modules, not the root one. It makes the linting task hanging for a long moment and finaly leads to an error:

```
Linting "cypress-mount"...
Failed to load config "./node_modules/kcd-scripts/eslint.js" to extend from.
Referenced from: ****/jscutlery/test-utils/packages/cypress-mount/node_modules/downshift/package.json
```

To fix this I had to update eslint configuration from the concerned project, and ignore the node_modules.

```json
{
  "extends": "../../.eslintrc.json",
  "ignorePatterns": ["!**/*", "node_modules"],
  "rules": {}
}
```

## Expected Behavior

By default project node_modules should be ignored by eslint.

**Comment by FrozenPandaz** [comment]
Thank you for reporting the issue.

Can you please provide a repo that exhibits the issue to help us reproduce the issue?

**Comment by edbzn** [comment]
Hi, the repo is open-source, the problem was introduced by the migration commit [here](https://github.com/jscutlery/test-utils/commit/6d591c929ac6387017e18cc5aa5a84c0b242c523), the [logs](https://github.com/jscutlery/test-utils/runs/2585575256) from the job that failed, the [commit](https://github.com/jscutlery/test-utils/commit/6096573477eee48b5873d15970764a99c65204b4) that resolved the issue, then I updated all configs because the linting was continuing to hang without failing, so I ignored all submodules in another [commit](https://github.com/jscutlery/test-utils/commit/2497404367ed251439986e9857cef98a95e31327). Let me know if I can help you more.

**Comment by meeroslav** [comment]
Thank you, @edbzn, for the details. We will look into it.

**Comment by meeroslav** [comment]
Interestingly enough, downgrading `@storybook/angular` to `^6.1.17` and then back to `^6.2.9` resolves the issue. The yarn.lock file gets changed of course. I will investigate further which package exactly is causing the problem.

**Comment by edbzn** [comment]
@meeroslav But, in any case, eslint should ignore the node_modules folder, am I wrong?

**Comment by meeroslav** [comment]
Yes, eslint should ignore local `node_modules`. From the NX side nothing has changed - we set up eslint with same options and pass the same file `pattern`.

**Comment by edbzn** [comment]
Well, I also checked some other repositories like angular-eslint and nothing seems related to this issue, feel free to close since it's not a problem when explicitly ignore node_modules.

**Comment by meeroslav** [comment]
I wouldn't explicitly ignore node_modules just yet. If you remove `node_modules` and `yarn.lock` and reinstall everything it should be fine. It should not happen, though, so we will keep issue open until we find out where this is coming from.

**Comment by meeroslav** [comment]
Closing this in favor of #5716
