### ISSUE TITLE
Custom Port Not Working

### ISSUE THREAD

**Issue by Max-Lev** [nrwl/nx#568]
Dependencies:
@nrwl/nx: "6.0.4"
Node: v8.9.4
Angular CLI: 6.0.1
Node: 8.9.4
OS: darwin x64
Angular: 6.0.1
Package                            Version
------------------------------------------------------------
angular-devkit/architect          0.6.7
angular-devkit/build-angular      0.6.7
angular-devkit/build-ng-packagr   0.6.7
angular-devkit/build-optimizer    0.6.7
angular-devkit/core               0.6.7
angular-devkit/schematics         0.6.1
ngtools/json-schema               1.1.0
ngtools/webpack                   6.0.7
schematics/angular                0.6.1
schematics/update                 0.6.1
ng-packagr                         3.0.0
rxjs                               6.0.0
typescript                         2.7.2
webpack                            4.8.3
------------------------------------------------------------
Issue:
1.Running command to serve project with **custom port not working from npm scripts**:
"serve:employees": "npm run ng serve --project employees port 4201".

2.Running command from terminal console results in an expected behaviour: 
ng serve --project=employees --port 4201

**Comment by FrozenPandaz** [comment]
npm scripts require a `--`

You actually want this script
```json
"serve:employees": "npm run ng -- serve --project employees --port 4201"
```

**Comment by Max-Lev** [comment]
Thank you!
