### ISSUE TITLE
[Feature Request] Allow Tree to write file with permissions

### ISSUE THREAD

**Issue by tinesoft** [nrwl/nx#5680]
## Description

Similar to the feature request here https://github.com/angular/angular-cli/issues/11781, it would be nice if the Nrwl DevKit's `Tree.write()|overwrite()` could allow setting the permissions on the file being written.

## Motivation

Sometimes, you need to create a file with  specific permissions, like for example, being *executable*. This is currently not possible with the Tree API.

## Suggested Implementation

1 - The `Tree.write()|overwrite()` could be overwritten to accept an optional `"mode?: string | number"` parameter (see  [fs.chmodSync()](https://nodejs.org/api/fs.html#fs_fs_chmodsync_path_mode) API), that would allow setting the required permissions on the file.

2 - Then the [FileChange](https://github.com/nrwl/nx/blob/ff691343737d4b470aef89723c597769e7299799/packages/tao/src/shared/tree.ts#L66) could be enhanced to store that `mode` parameter, 

3 - and finally after line:
https://github.com/nrwl/nx/blob/ff691343737d4b470aef89723c597769e7299799/packages/tao/src/shared/tree.ts#L289
and line:
https://github.com/nrwl/nx/blob/ff691343737d4b470aef89723c597769e7299799/packages/tao/src/shared/tree.ts#L291
we could add a call to `fs.chmodSync(fPath, f.mode)` if `f.mode` is defined.

## Alternate Implementations

If this feature request gets accepted, I can start working on it and provide a PR.

**Comment by FrozenPandaz** [comment]
@vsavkin should we match the node API and accept an options object instead of separate parameters?
