### ISSUE TITLE
Unbundled React libraries

### ISSUE THREAD

**Issue by Katona** [nrwl/nx#5689]
## Description
We are creating a React component library and I would like to publish it unbundled.

## Motivation
Unbundled libraries are better targets of treeshaking. While NX currently generates ES6 bundles which are treeshakeable, my experience shows that the 3rd party dependencies are included in the final bundle even if they are not used.

## Suggested Implementation
It is not actually a suggested implementation, but the Rollup configuration is already customizable, and I made a test with `preserveModules: true` (https://rollupjs.org/guide/en/#outputpreservemodules), and modified the `package.json` so it points the proper file as the module entry point. The module created this way yielded better treeshaking results (though it's css was still bundled as one big file).

**Comment by puku0x** [comment]
What if setting `external` modules in `workspace.json` ?

```js
// Example for Nx v12 + React v17 + Emotion v11
options: {
  external: ['react/jsx-runtime', '@emotion/styled/base']
}
```

**Comment by Katona** [comment]
I am talking about arbitrary 3rd party dependencies, not just React. My investigate shows that if anything is used from the library bundle, then all of the 3rd party dependencies will be part of the final bundle, not just the ones which are actually used.

**Comment by Katona** [comment]
I am actually considering writing a custom builder which would create an 'exploded' package, is there any concern regarding that? I don't know, something like 'it conflicts with the philosophy of Nx', or anything ...
