### ISSUE TITLE
nx 12.0.1 generate looking for tsconfig.base.json

### ISSUE THREAD

**Issue by BrandonClapp** [nrwl/nx#5691]
## Current Behavior

I am currently on `@nrwl/angular` v12.0.1. Upon running

```
ng generate @nrwl/angular:library --name=user-management --no-interactive --dry-run
```

I receive the following error.

```
Cannot read property 'paths' of undefined
```

Upon further research, [someone else suggested duplicating](https://github.com/nrwl/nx/issues/3874#issuecomment-721481424) `tsconfig.json` and renaming the duplicate to `tsconfig.base.json`. 

![image](https://user-images.githubusercontent.com/2096746/118545480-47699080-b71c-11eb-9c60-325a0ffb80f7.png)

While that seems to allow the `nx generate` command to work, it also wants to delete my `tsconfig.json` file. I can't delete this root `tsconfig.json` because every component in my application extends it.

It's my understanding that the `tsconfig.base.json` was _only_ an angular v10 nuance and has recently been removed back in favor of `tsconfig.json`.

I guess my question is why would the `nx generate` command be _looking_ for the `tsconfig.base.json` and why does it want to delete my root `tsconfig.json`?

## Expected Behavior

`nx generate` commands look for `tsconfig.json` instead of `tsconfig.base.json` and create the library without deleting the root `tsconfig.json`

## Steps to Reproduce
- Have `@nrwl/angular` v12.0.1 (and `@nrwl/workspace` v12.0.1 if it matters) installed
- Don't have a `tsconfig.base.json` in your workspace root
- run `ng generate @nrwl/angular:library --name=user-management --no-interactive --dry-run`
- Observe `Cannot read property 'paths' of undefined`
- Duplicate the `tsconfig.json` and rename it to `tsconfig.base.json`
- Rerun the `ng generate` command above
- See if you see the same dry run results shown in the screenshot above.

### Environment

![image](https://user-images.githubusercontent.com/2096746/118547071-7a148880-b71e-11eb-8ead-3e7319509db5.png)

Some possibly relevant dependency versions:

dependencies
```
    "@nrwl/angular": "12.0.1",
    "@angular/common": "11.2.14",
    "@angular/compiler": "11.2.14",
    "@angular/core": "11.2.14",
```

devDependencies
```
    "@angular/cli": "11.2.13",
    "@angular/compiler-cli": "11.2.14",
    "@angular/language-service": "11.2.14",
    "@nrwl/jest": "12.0.1",
    "@nrwl/workspace": "12.0.1",
```

## Possibly related

#3725, #3251, #3874

**Comment by BrandonClapp** [comment]
These comments suggest that `tsconfig.base.json` is correct and that I should keep this name and update other tsconfig files to extend from this one.

https://github.com/nrwl/nx/issues/3251#issuecomment-674294370

https://github.com/nrwl/nx/issues/3251#issuecomment-692700616

**Comment by BrandonClapp** [comment]
If anyone else has this issue in the future, I was able to find/replace instances of the string tsconfig.json with tsconfig.base.json to fix all of my child tsconfigs that extended it with this

![image](https://user-images.githubusercontent.com/2096746/118558556-6a9c3c00-b72c-11eb-816d-1f0e589b5218.png)

**Comment by vsavkin** [comment]
Thank you for submitting the issue. 

The reason why using tsconfig.json is no good is that it's picked up by the language service (by vscode and webstorm) which it complicates a lot of things and results in bugs. The purpose of the root tsconfig is to dedup compiler options not to inform the editor. We have a migration that renames the file when you move to Nx 10, but perhaps something went wrong and it didn't run for you. Sorry about this.

I'm going to close this as it's the desired behavior.
