### ISSUE TITLE
Tailwindcss build production not work

### ISSUE THREAD

**Issue by unnhao** [nrwl/nx#5696]
## Current Behavior
I use tailwind 2.1.2, During develop time there is no problem, but when i build production for deployment, the tailwind style not effect on the element, so... the layout is destroyed.

## Expected Behavior
I expected to the same as the development period after the build production.

## Steps to Reproduce
`nx run client:serve:development` it's okay,
`nx run client:build:production` it's failed!

### Environment
```
  Node : 14.16.1
  OS   : win32 x64
  npm  : 6.14.12
  
  nx : Not Found
  @nrwl/angular : 12.3.1
  @nrwl/cli : 12.3.1
  @nrwl/cypress : 12.3.1
  @nrwl/devkit : 12.3.1
  @nrwl/eslint-plugin-nx : 12.3.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.1
  @nrwl/linter : 12.3.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.1
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.1
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

```
 "dependencies": {
    "@angular/animations": "12.0.0",
    "@angular/cdk": "^12.0.0",
    "@angular/common": "12.0.0",
    "@angular/compiler": "12.0.0",
    "@angular/core": "12.0.0",
    "@angular/forms": "12.0.0",
    "@angular/material": "^12.0.0",
    "@angular/platform-browser": "12.0.0",
    "@angular/platform-browser-dynamic": "12.0.0",
    "@angular/router": "12.0.0",
    "@nrwl/angular": "12.3.1",
    "@tailwindcss/forms": "^0.3.2",
    "rxjs": "~6.6.0",
    "tailwindcss": "^2.1.2",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "12.0.0",
    "@angular-eslint/eslint-plugin": "~12.0.0",
    "@angular-eslint/eslint-plugin-template": "~12.0.0",
    "@angular-eslint/template-parser": "~12.0.0",
    "@angular/cli": "12.0.0",
    "@angular/compiler-cli": "12.0.0",
    "@angular/language-service": "12.0.0",
    "@nrwl/cli": "12.3.1",
    "@nrwl/cypress": "12.3.1",
    "@nrwl/eslint-plugin-nx": "12.3.1",
    "@nrwl/jest": "12.3.1",
    "@nrwl/linter": "12.3.1",
    "@nrwl/tao": "12.3.1",
    "@nrwl/workspace": "12.3.1",
    "@types/jest": "26.0.8",
    "@types/node": "14.14.33",
    "@typescript-eslint/eslint-plugin": "4.19.0",
    "@typescript-eslint/parser": "4.19.0",
    "cypress": "^6.0.1",
    "dotenv": "8.2.0",
    "eslint": "7.22.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "jest": "26.2.2",
    "jest-preset-angular": "8.4.0",
    "postcss": "^8.2.15",
    "prettier": "2.2.1",
    "ts-jest": "26.5.5",
    "ts-node": "~9.1.1",
    "typescript": "~4.2.4"
  }
```

**Comment by unnhao** [comment]
> ## Current Behavior
> I use tailwind 2.1.2, During develop time there is no problem, but when i build production for deployment, the tailwind style not effect on the element, so... the layout is destroyed.
> 
> ## Expected Behavior
> I expected to the same as the development period after the build production.
> 
> ## Steps to Reproduce
> `nx run client:serve:development` it's okay,
> `nx run client:build:production` it's failed!
> 
> ### Environment
> ```
>   Node : 14.16.1
>   OS   : win32 x64
>   npm  : 6.14.12
>   
>   nx : Not Found
>   @nrwl/angular : 12.3.1
>   @nrwl/cli : 12.3.1
>   @nrwl/cypress : 12.3.1
>   @nrwl/devkit : 12.3.1
>   @nrwl/eslint-plugin-nx : 12.3.1
>   @nrwl/express : Not Found
>   @nrwl/jest : 12.3.1
>   @nrwl/linter : 12.3.1
>   @nrwl/nest : Not Found
>   @nrwl/next : Not Found
>   @nrwl/node : Not Found
>   @nrwl/react : Not Found
>   @nrwl/schematics : Not Found
>   @nrwl/tao : 12.3.1
>   @nrwl/web : Not Found
>   @nrwl/workspace : 12.3.1
>   @nrwl/storybook : Not Found
>   @nrwl/gatsby : Not Found
>   typescript : 4.2.4
> ```

**Comment by Coly010** [comment]
Hi!

Could you provide us with a minimum repo that can recreate this issue to allow us to investigate further?

Thanks!!

**Comment by cwqt** [comment]
Have a feeling this is more to do with Tailwind/webpack purging classes because the env is production, than anything to do with Nx

**Comment by unnhao** [comment]
> Have a feeling this is more to do with Tailwind/webpack purging classes because the env is production, than anything to do with Nx

Yes, maybe. And I remove node_module, package-lock.json re-install, it worked.
I very confused, but it worked!

Thanks guys help me. maybe still this time I don't know what's going on.
