### ISSUE TITLE
Execute Cypress tests over BrowserStack

### ISSUE THREAD

**Issue by brunano21** [nrwl/nx#5701]
## Description
I'd like to have support for running Cypress tests over BrowserStack.

## Motivation
In my company, our Jenkins agents don't meet the basic requirements to run cypress tests. Hence I'm looking to run cypress tests over BrowserStack, for which we have a license.

I found out that Browserstack comes with Cypress support as shown [here](https://www.browserstack.com/docs/automate/cypress). However, this cannot be used when within a nx workspace. The reason is that the preferred and recommended way for running Cypress tests is `nx e2e my-awesome-app-e2e`. 
I have tried to customize browserstack.json adding all required dependencies, but I believe this is not the only required action to make this work with nx. My understanding is that the `@nrwl/cypress/plugins/preprocessor` plugin might need some tweak in order to work with `browserstack-cypress-cli`.

Error log on Browserstack Dashboard:
```
The function exported by the plugins file threw an error.

We invoked the function exported by `.\src\plugins\index.js`, but it threw an error.

 Error: Please provide an absolute path to a tsconfig.json as cypressConfig.env.tsConfig
    at preprocessTypescript (.\node_modules\@nrwl\cypress\src\plugins\preprocessor.js:18:15)
    at module.exports (.\src\plugins\index.js:22:27)
    at \cypress_package\4.12.1\app\packages\server\lib\plugins\child\run_plugins.js:78:12
    at tryCatcher (\cypress_package\4.12.1\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (\cypress_package\4.12.1\node_modules\bluebird\js\release\method.js:39:29)
    at load (\cypress_package\4.12.1\app\packages\server\lib\plugins\child\run_plugins.js:75:7)
    at EventEmitter.<anonymous> (\cypress_package\4.12.1\app\packages\server\lib\plugins\child\run_plugins.js:231:5)
    at EventEmitter.emit (events.js:210:5)
    at process.<anonymous> (\cypress_package\4.12.1\app\packages\server\lib\plugins\util.js:19:22)
    at process.emit (events.js:210:5)
    at process.emit (\cypress_package\4.12.1\node_modules\source-map-support\source-map-support.js:495:21)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

cypress run process exited with code 1
cypress run failed, exiting with code: 1
```

## Suggested Implementation
_None_ :-(
## Alternate Implementations
_None_ :-(

**Comment by brunano21** [comment]
Somehow this relates to this other issue I reported a while back, about running Nx-enabled Cypress tests over Docker. https://github.com/nrwl/nx/issues/4079
Tagging @shlomiassaf that at that time has helped a bit :-)

**Comment by brunano21** [comment]
Hi - is there any update on this? It's currently a blocker for us and we would like to use Cypress over Browserstack.

**Comment by brunano21** [comment]
UP

**Comment by mehrad-rafigh** [comment]
@FrozenPandaz any ideas on how we can tackle this? This is a real show stopper for us. Anyway the community can help tackle this issue?

**Comment by mehrad-rafigh** [comment]
Should that live in the documentation of nx so people don't have to go through github issues @nrwl/nx?

**Comment by barbados-clemens** [comment]
thanks for finding a workable solution @brunano21
You might be able to reattempt this after upgraded > v7 of cypress as the preprocess isn't needed anymore.

**Comment by rao123dk** [comment]
I am still unable to run cypress over BrowserStack. anyone have idea? 
I am using `"@nrwl/cypress": "^13.2.3"`

**Comment by GrayedFox** [comment]
@barbados-clemens @brunano21 do either of you have more detailed instructions for how we can get this working?

At the moment it's looking like I am going to have to remove all of our Cypress tests from our nx mono repo due to not being able to get it to play nicely with Browserstack. 

I've tried setting up a custom NX command using the run executor but no matter which way I try it, when trying to install certain dependencies, I get the following error:

```
npm ERR!
 code EEXIST
npm ERR! path .\node_modules\.bin\ts-node-cwd

npm ERR! Refusing to delete .\node_modules\.bin\ts-node-cwd: is outside .\node_modules\ts-node and not a link
npm ERR!
 File exists: .\node_modules\.bin\ts-node-cwd
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
```

I will post a solution/workaround here if I find one, also opened a support ticket with BrowserStack.

**Comment by swatinigam** [comment]
> @barbados-clemens @brunano21 do either of you have more detailed instructions for how we can get this working?
> 
> At the moment it's looking like I am going to have to remove all of our Cypress tests from our nx mono repo due to not being able to get it to play nicely with Browserstack.
> 
> I've tried setting up a custom NX command using the run executor but no matter which way I try it, when trying to install certain dependencies, I get the following error:
> 
> ```
> npm ERR!
>  code EEXIST
> npm ERR! path .\node_modules\.bin\ts-node-cwd
> 
> npm ERR! Refusing to delete .\node_modules\.bin\ts-node-cwd: is outside .\node_modules\ts-node and not a link
> npm ERR!
>  File exists: .\node_modules\.bin\ts-node-cwd
> npm ERR! Remove the existing file and try again, or run npm
> npm ERR! with --force to overwrite files recklessly.
> ```
> 
> Problematically, removing the dependencies that throw the above EEXIST errors makes the tests fail for obvious reasons - removing typescript as a dependency results in `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for .\cypress.config.ts` being thrown as there is no TS transpiler to interpret the TS extension.
> 
> I will post a solution/workaround here if I find one, also opened a support ticket with BrowserStack.

Hi there! 

Fwiw I am also seeing the same error about .ts not being a valid extension. 🤦 Curious to know if you found a solution or if Browserstack provided a workaround? Let us know please 🙏  Thank you.

**Comment by GrayedFox** [comment]
For those running into issues with running Cypress tests from within an NX repo on BrowserStack, adding this line to our **browserstack.json** file helped with installing dependencies:

```json
"run_settings": {
        "cache_dependencies": false,
}
```

We still ended up switching to PlayWright given that it supports real Android device testing and iOS device emulation out of the box and has built in support for fixtures. I do think Cypress is outclassed in several ways by PW, would be good to see NX add support for PW alongside Cypress (or potentially phase our Cypress completely) - but that's another thread! ☮️
