### ISSUE TITLE
After upgrade to angular 12.0.0.0 - NX commands failing

### ISSUE THREAD

**Issue by samartomar** [nrwl/nx#5709]
## Current Behavior
After Angular upgrade and nx 12.3.3 we started getting following error
"SchematicsNxApp" schema is using the keyword "id" which its support is deprecated. Use "$id"

## Expected Behavior

NX 12.3.3 to have updated scheam 

## Steps to Reproduce
Initiaize nx@latest update angular to 12.0.0 and create app or try to setup tailwind anything that touches scheama

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by FrozenPandaz** [comment]
Please post the results of `nx report`. That schema has been updated already https://github.com/nrwl/nx/blob/master/packages/angular/src/schematics/application/schema.json#L3
