### ISSUE TITLE
Directory option not accepting directory path

### ISSUE THREAD

**Issue by vimalraj-a** [nrwl/nx#572]
I like to put my libraries in below structure 
```
client
        chart
                feature-chart-viewer
                feature-chart-designer
                data-access-chart-viewer
                data-access-chart-designer
        weberport
                 feature-webreport-viewer
                 feature-webreport-viewer
```
But, above structure is not able to be created with `--directory`

**Comment by Yonet** [comment]
I am not sure what the feature-chart-viewer is, component/library? You can create this structure by 
`
ng g lib chart/feature-chart-viewer --directory=client
`

**Comment by vimalraj-a** [comment]
Its a library. 

After I looked into source code found that we should use / as path separator.

I was trying with \ and it fails.
