### ISSUE TITLE
Type 'Tree' is missing the following properties from type 'Tree': write, isFile, children, listChangests(2345)

### ISSUE THREAD

**Issue by hadrien-toma** [nrwl/nx#5722]
## Current Behavior

I try to mix Angular and Nx tools made for the development of new schematics but the `Tree` from `@angular-devkit/schematics` and from `@nrwl/devkit` seems to be incompatible. If it is expected, may we imagine a method to create a parser from one to the other (the main important direction for me is from `@angular-devkit/schematics` to `@nrwl/devkit`).

## Expected Behavior

I would like to be able to use `getWorkspaceLayout` from `@nrwl/devkit`. This function requires a tree from `@nrwl/devkit` but the `Tree` I already have (and use quite intensively) in my schematic is from `@angular-devkit/schematics` so I get the error below.

## Steps to Reproduce

Here is a minimal code triggering the error:

```
import { chain, Rule, SchematicContext, Tree } from '@angular-devkit/schematics';
import { getWorkspaceLayout } from '@nrwl/devkit';

export interface Schema {}

export default function ({}: Schema): Rule {
	return (tree: Tree, schematicContext: SchematicContext) => {
		const workspaceLayout = getWorkspaceLayout(tree);
		const ruleList = [];
		const rule = chain(ruleList)(tree, schematicContext);
		return rule;
	};
}
```

### Failure Logs

```
Argument of type 'import("/home/hadrien_toma/gitlab.com/bashroom-devs/yoptoruta/node_modules/@angular-devkit/schematics/src/tree/interface").Tree' is not assignable to parameter of type 'import("/home/hadrien_toma/gitlab.com/bashroom-devs/yoptoruta/node_modules/@nrwl/tao/src/shared/tree").Tree'.
  Type 'Tree' is missing the following properties from type 'Tree': write, isFile, children, listChangests(2345)
```

### Environment

```
  Node : 15.14.0
  OS   : linux x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 11.6.1
  @nrwl/cli : 11.6.1
  @nrwl/cypress : 11.6.1
  @nrwl/devkit : 11.6.1
  @nrwl/eslint-plugin-nx : 11.6.1
  @nrwl/express : Not Found
  @nrwl/jest : 11.6.1
  @nrwl/linter : 11.6.1
  @nrwl/nest : 11.6.1
  @nrwl/next : Not Found
  @nrwl/node : 11.6.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.6.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.6.1
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.0.7
```

**Comment by DominikPieper** [comment]
Hi, yes they're incompatible. The @nrwl/devtools package is using the Tree from the devtools and works for the new generator API. There are functions with the same features like e.g. getWorkspaceLayout in Nx. 

For getWorkspaceLayout e.g.:
import { getNpmScope } from '@nrwl/workspace';
import { libsDir, appsDir } from '@nrwl/workspace/src/utils/ast-utils';

These functions use the angular-devkit Tree

**Comment by hadrien-toma** [comment]
That's perfect, thank you very much @DominikPieper ;
