### ISSUE TITLE
npx nx g @nrwl/express:application api --frontendProject=todos

### ISSUE THREAD

**Issue by rullymartanto** [nrwl/nx#5723]
Hi,

I try follow the tutorial,
and after follow this step 
npx nx g @nrwl/express:application api --frontendProject=todos

it's give me 
Expected argument `jsonString` to be a `string`, got `object`

Thanks

**Comment by Peter-NZ** [comment]
Might be the same issue identified [here](https://github.com/nrwl/nx/issues/5719#issuecomment-844741208)

**Comment by FrozenPandaz** [comment]
Closing as a duplicate of https://github.com/nrwl/nx/issues/5719#issuecomment-844741208. Please follow that issue.
