### ISSUE TITLE
Module name is not customizable

### ISSUE THREAD

**Issue by vimalraj-a** [nrwl/nx#573]
`ng g lib feature-chart-viewer --directory=chart`

Creates the module name as `ChartFeatureChartViewer` (not a better name for module). Provide option to customize the module name at least provide option for workspace specific schematic.

**Comment by kennyfowler** [comment]
I was wondering myself if there is a reason for prefixing the module, because I thought the --directory parameter would be "the feature" for putting your (non-reuseable) app-modules in libs subdir, or putting several shared modules in a "shared" subdir.

**Comment by boicetomlin** [comment]
This issue has currently stopped my workflow completely on nx.  I have no control of my module names when using the directory option.  Is there a reason for this functionality?

**Comment by listepo-alterpost** [comment]
@vsavkin I think we can add option --skipModulePrefix for --directory or something like that.
