### ISSUE TITLE
Error creating stories for libraries without e2e

### ISSUE THREAD

**Issue by hgschwibbe** [nrwl/nx#5743]
## Steps to Reproduce
1. Create a storybook configuration without e2e:
`$ ng g @nrwl/angular:storybook-configuration libraryXyz`
✔ Configure a cypress e2e app to run against the storybook instance? (Y/n) · false
✔ Automatically generate *.stories.ts files for components declared in this project? (Y/n) · false
✔ Automatically generate *.spec.ts files in the cypress e2e app generated by the cypress-configure generator? (Y/n) · false

2. generate stories:
`$ ng g @nrwl/angular:stories --name=libraryXyz`

## Current Behavior
Error: Cannot find project 'libraryXyz-e2e'

## Expected Behavior
Stories will be created

### Environment
  Node : 14.17.0
  OS   : linux x64 (Ubuntu 20.04)
  npm  : 6.14.13
  
  @nrwl/angular : 12.1.1
  @nrwl/cli : 12.1.1
  @nrwl/cypress : 12.1.1
  @nrwl/devkit : 12.1.1
  @nrwl/eslint-plugin-nx : 12.1.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.1.1
  @nrwl/linter : 12.1.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.1.1
  @nrwl/web : Not Found
  @nrwl/workspace : 12.1.1
  @nrwl/storybook : 12.3.4
  @nrwl/gatsby : Not Found
  typescript : 4.1.5

**Comment by juristr** [comment]
@hgschwibbe You can add `--generateCypressSpecs=false` to the command and it should work. I'll have a look as we should be able to automatically detect this
