### ISSUE TITLE
Command to build Next.js for Vercel errors out

### ISSUE THREAD

**Issue by Xenfo** [nrwl/nx#5748]
## Current Behavior

Command fails

## Expected Behavior

I expected it to build my project successfully

## Steps to Reproduce

Repo: https://github.com/Xenfo/atomic
Try to deploy it to Vercel following the guide in the NX Next.js docs.

### Failure Logs

```
❯ nx build frontend --prod --outputPath=.

> nx run frontend:build:production --outputPath=. 
info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types  
info  - Using external babel configuration from /home/xenfo/Desktop/Projects/atomic/apps/frontend/.babelrc
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
info  - Generating static pages (3/3)
info  - Finalizing page optimization  

Page                                                           Size     First Load JS
┌ ○ /                                                          1.22 kB        68.4 kB
├   └ css/f06ddab96869c260cfa8.css                             20 B
├   /_app                                                      0 B            67.2 kB
└ ○ /404                                                       3.73 kB        70.9 kB
+ First Load JS shared by all                                  67.2 kB
  ├ chunks/f6078781a05fe1bcb0902d23dbbb2662c8d200b3.9f24d5.js  13.6 kB
  ├ chunks/framework.0c3b20.js                                 41.8 kB
  ├ chunks/main.bab312.js                                      6.95 kB
  ├ chunks/pages/_app.4b9835.js                                4.15 kB
  ├ chunks/webpack.50bee0.js                                   751 B
  └ css/48cbfac088811e35fdc5.css                               667 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)


———————————————————————————————————————————————

>  NX   ERROR  Running target "frontend:build" failed

  Failed tasks:
  
  - frontend:build:production


>  NX   CLOUD  See run details at ...
```

### Environment

```
Node : 14.15.5
OS   : linux x64
yarn : 1.22.5
  
nx : Not Found
@nrwl/angular : Not Found
@nrwl/cli : 12.3.4
@nrwl/cypress : 12.3.4
@nrwl/devkit : 12.3.4
@nrwl/eslint-plugin-nx : 12.3.4
@nrwl/express : 12.3.4
@nrwl/jest : 12.3.4
@nrwl/linter : 12.3.4
@nrwl/nest : Not Found
@nrwl/next : 12.3.4
@nrwl/node : 12.3.4
@nrwl/react : 12.3.4
@nrwl/schematics : Not Found
@nrwl/tao : 12.3.4
@nrwl/web : 12.3.4
@nrwl/workspace : 12.3.4
@nrwl/storybook : 12.3.4
@nrwl/gatsby : Not Found
typescript : 4.2.4
```

### Workaround from Vercel
Set custom build command to: `npx nx build my-app --prod`
Set output directory to: `dist/apps/my-app/.next`

_Note for this to work you must have NX Cloud off as far as I can tell_

**Comment by hcharley** [comment]
I can confirm I'm seeing the same problem with my own freshly created repo.

This fails:

```
yarn nx build my-app --prod --outputPath=.
```

This works:

```
yarn nx build my-app --prod
```

**Comment by Xenfo** [comment]
Yup that worked

**Comment by FrozenPandaz** [comment]
Seems like we should update the documentation. I'm not sure why that option is there in the docs.

@kirjai Please take a look.

**Comment by Xenfo** [comment]
It still doesn't build properly in Vercel

**Comment by hcharley** [comment]
Yes, I should have clarified, that I could not succeed in building for Vercel.

The documentation reccomends `--outputPath=.` as a hack of sorts to get things to work properly specifically for Vercel, so as far as I can tell, its required. The reason for this is that I think the build files need to be colocated to the `node_modules` directory.

It's possible that maybe we can figure out a workaround by removing `--outputPath=.` and then doing a `mv` to move these files out of `dist/apps/my-app/*` and next to `node_modules`:

- `.next`
- `public`
- `next.config.js`
- `package.json`

**Comment by hcharley** [comment]
I am trying out this workaround command:

```
npx nx build beach-chronicle --prod && mv -v dist/apps/beach-chronicle/* .
```

**Comment by hcharley** [comment]
I am trying out this workaround command:

```
npx nx build my-app --prod && mv -v dist/apps/my-app/* .
```

**Comment by hcharley** [comment]
That didn't work for some reason, so I tried this way, and *it worked*:

```
npx nx build my-app --prod && rm package.json && mv -v dist/apps/my-app/.next .next && mv -v dist/apps/my-app/package.json package.json && mv -v dist/apps/my-app/next.config.js next.config.js
```

@Xenfo try this out for size in your Vercel build step:

```
npx nx build frontend --prod && rm package.json && mv -v dist/apps/frontend/.next .next && mv -v dist/apps/frontend/package.json package.json && mv -v dist/apps/frontend/next.config.js next.config.js
```

**Comment by DuyBui1993** [comment]
I got vercel build working by using this [workaround](https://github.com/nrwl/nx/issues/5660#issuecomment-841639368)

**Comment by Xenfo** [comment]
hcharley's method worked for me I'll be trying DuyBui1993's method later.

**Comment by kirjai** [comment]
unfortunately, there is a known issue at the moment with builds on Vercel, which is being tracked here: https://github.com/nrwl/nx/issues/5660

still, why using `--outputPath=.` fails the build is worth investigating on our end

**Comment by Xenfo** [comment]
@hcharley Just want to note that when Vercel tries to build with build cache it fails.

**Comment by hcharley** [comment]
@Xenfo I can confirm that using the cache fails with my method.

Without the cache, my method still works. 

It's still a workaround, so yes @kirjai understanding why `--outputPath=.` is not working, would be helpful.

**Comment by Xenfo** [comment]
Just to double check, NX would normally download from the cache right?

**Comment by hcharley** [comment]
@Xenfo I have never use Vercel’s cache. I would not know. Maybe someone else who has experience can speak to that.

**Comment by Xenfo** [comment]
Sorry, I think I've confused you. Does NX usually pull from NX cloud's cache. I think Vercel's cache is fine.

**Comment by Bodom78** [comment]
Got hit by this issue as well, this [solution](https://github.com/nrwl/nx/issues/5660#issuecomment-841639368) at least allowed me to get the build working on Vercel.

**Comment by hcharley** [comment]
I've switched to using the solution mentioned last by @Bodom78 which felt cleaner:

https://github.com/nrwl/nx/issues/5660#issuecomment-841639368

**Comment by kirjai** [comment]
We have merged an update to the documentation. we no longer advise to use `--outputPath=.`. please use a custom build output path instead. Refer to the [updated documentation for more details](https://nx.dev/latest/react/guides/nextjs#existing-vercel-project).

If you experience any issues with the updated approach, please open a new issue
