### ISSUE TITLE
TSLint's support is discontinued and we're deprecating its support in Angular CLI.

### ISSUE THREAD

**Issue by dean-g** [nrwl/nx#5749]
I am getting a deprecation warning towards tslint, 

Can you please check this below and advise ?
TSLint's support is discontinued and we're deprecating its support in Angular CLI.
To opt-in using the community driven ESLint builder, see: https://github.com/angular-eslint/angular-eslint#migrating-an-angular-cli-project-from-codelyzer-and-tslint.

**Comment by AnkitaSood** [comment]
> New projects are created with TSLint by default.

Did you mean new projects are created with ESLint by default?

**Comment by leosvelperez** [comment]
> Did you mean new projects are created with ESLint by default?

Yeah, that was a typo. New projects will use ESLint by default now.

**Comment by chelsumz007** [comment]
Anyway I can avoid this warning?

![image](https://user-images.githubusercontent.com/52992133/126467974-b77cf58b-aa4b-4386-8b2d-d3c6ec5ae0fc.png)
