### ISSUE TITLE
can we make ngrx optional? 

### ISSUE THREAD

**Issue by xmlking** [nrwl/nx#575]
Some users may use` ngxs` for state management. wonder if we can make  `ngrx` optional via `create-nx-workspace ` command. 

```bash
create-nx-workspace srika --prefix=ngx --style=scss --routing  --service-worker
cd srika
ng update @angular/core
```
We also see version out of sync errors 
 
```
Package "@ngrx/store" has an incompatible peer dependency to "rxjs" (requires "^5.5.0", would install "6.2.0").
Incompatible peer dependencies found. See above.
```

**Comment by arjunyel** [comment]
If possible it would be awesome to have NGXS as a support state management library 😄

**Comment by vsavkin** [comment]
We are considering it. 

This is a workaround for now:

1. Remove the  `NxModule.forRoot` call from app.module.ts.
2. Remove ngrx from package.json
3. Obviously do not call `ng g ngrx` :)

**Comment by intellix** [comment]
Everytime I update it brings itself back and installs ngrx again. Can't seem to kill the beast

**Comment by dtomaszewski** [comment]
> We are considering it.
> 
> This is a workaround for now:
> 
> 1. Remove the  `NxModule.forRoot` call from app.module.ts.
> 2. Remove ngrx from package.json
> 3. Obviously do not call `ng g ngrx` :)

@vsavkin are there any news about supporting ngxs  ? :)

**Comment by vsavkin** [comment]
Sorry for the late reply.

Ngrx is optional now. We add the dependencies only when you invoke the ngrx schematic.

@dtomaszewski we aren't planning to add ngxs schematic at the moment, but you can create your own schematic (can be a package, can be a workspace schematic).

**Comment by cjkumaresh** [comment]
@vsavkin from which version it is available ?
