### ISSUE TITLE
nx migrate latest does not update angular

### ISSUE THREAD

**Issue by heddendorp** [nrwl/nx#5750]
## Current Behavior

running `nx migrate latest` only update @nrwl packages

## Expected Behavior

The command should help me update all packages in my app.

## Steps to Reproduce

Run the command in https://github.com/heddendorp/tumi-app/tree/nx-workspace

### Environment

```
>  NX  Report complete - copy this into the issue template

  Node : 14.16.1
  OS   : win32 x64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.3.4
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.3.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.4
  @nrwl/linter : 12.3.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.4
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.4
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

**Comment by FrozenPandaz** [comment]
This issue occurs because `@nrwl/angular` is not installed.

This seems to be an Angular CLI workspace that was migrated to Nx so we should add `@nrwl/angular` as part of that process.

**Comment by heddendorp** [comment]
Okay, thank you @FrozenPandaz so for me the quick fix is to just install the angular plugin?

**Comment by leosvelperez** [comment]
@heddendorp as @FrozenPandaz mentioned, this seems to be a workspace that was not correctly migrated to Nx. I can see you created this other issue where the migration did fail https://github.com/nrwl/nx/issues/5751 and that's unfortunate, I'll have a look at that one, but it can take some time until it gets resolved.

You can follow the steps on this guide https://nx.dev/latest/angular/migration/migration-angular#transitioning-manually to manually migrate your application to an Nx workspace.

**Comment by leosvelperez** [comment]
I'm closing this one as it doesn't seem to be an issue of the `nx migrate` command, but [a faulty migration to an Nx workspace from an Angular CLI workspace](https://github.com/nrwl/nx/issues/5751).

Please, feel free to reopen this if you still think this is an issue after [the workspace migration issue](https://github.com/nrwl/nx/issues/5751) is resolved.
