### ISSUE TITLE
Be able to run `nx affected` with npx

### ISSUE THREAD

**Issue by yharaskrik** [nrwl/nx#5752]
## Description

In some CI steps we do not need to have our node modules cache installed/restored but do need to run custom affected commands for building docker images. So save CI time/resources it would be sweet to be able to just run `npx nx@12.1.0 affected --target=<custom> --base=$BASE`

## Motivation

Mentioned above

## Suggested Implementation

It seems to sort of be implemented as Nx does "work" with `npx` but I do get this error:

```
npx nx@12.1.0 affected --target=<custom> --config=<config> --parallel
npx: installed 62 in 5.42s

>  NX   ERROR  Could not find Nx modules in this workspace.

  Have you run npm/yarn install?
```

So not sure if this is a bug report or if its a feature request, I feel like it's not implemented with Nx and npx just tries anyway so I would classify as a feature request.

**Comment by FrozenPandaz** [comment]
This is the intentional behavior.

Nx expects for the `node_modules` directory to contain things like Executors, Generators, .etc so apart from `create-nx-workspace`, this all should be done within a workspace with installed `node_modules`.
