### ISSUE TITLE
Broken Storybook (probably due minor dependencies update)

### ISSUE THREAD

**Issue by rfprod** [nrwl/nx#5755]
## Current Behavior
Storybook e2e no longer works reporting the following error:
> Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
> - configuration.module.rules[9] has an unknown property 'mimetype'. These properties are valid:
   object { compiler?, enforce?, exclude?, include?, issuer?, loader?, loaders?, oneOf?, options?, parser?, query?, realResource?, resolve?, resource?, resourceQuery?, rules?, sideEffects?, test?, type?, use? }
   -> A rule

## Expected Behavior
Storybook e2e tests work as previously.

According to the pipelines the following revision works https://github.com/rfprod/nx-ng-starter/tree/e1b9df65bde8424e8d497b90c64b61b80c204a16

Master pipeline run result https://github.com/rfprod/nx-ng-starter/runs/2412491544
Expand the `Build documentation` step results and search for the `last` entry of `client-components-e2e`

![working-client-components-e2e](https://user-images.githubusercontent.com/1507770/119251988-1e308080-bbb2-11eb-8a51-cd9d576011bd.png)

## Steps to Reproduce
Clone this repo: https://github.com/rfprod/nx-ng-starter
Execute from the project root: `ng e2e client-components-e2e --headless`

### Failure Logs
Local reproduction

```bash
$ ng e2e client-components-e2e --headless

> nx run client-components-e2e:e2e --headless 
info => Loading presets
info => Loading 1 config file in "/media/suser/DATA/git/rfprod/nx-ng-starter/libs/client-components/.storybook"
info => Loading 1 other file in "/media/suser/DATA/git/rfprod/nx-ng-starter/libs/client-components/.storybook"
info => Loading custom manager config
info => Found custom tsconfig.json
info => Using implicit CSS loaders
info => Loading custom manager config
info => Using angular project 'client' for configuring Storybook.
info => Loading angular-cli config.
info => Get angular-cli webpack config.
info => Loading custom Webpack config (full-control mode).
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[9] has an unknown property 'mimetype'. These properties are valid:
   object { compiler?, enforce?, exclude?, include?, issuer?, loader?, loaders?, oneOf?, options?, parser?, query?, realResource?, resolve?, resource?, resourceQuery?, rules?, sideEffects?, test?, type?, use? }
   -> A rule

———————————————————————————————————————————————

>  NX   ERROR  Running target "client-components-e2e:e2e" failed

  Failed tasks:
  
  - client-components-e2e:e2e
```

Here is how it fails in the pipeline https://github.com/rfprod/nx-ng-starter/runs/2643227085
Expand the `Build documentation` step results and search for the `last` entry of `client-components-e2e`

![failed-client-components-e2e](https://user-images.githubusercontent.com/1507770/119252047-9008ca00-bbb2-11eb-99ab-bdbdfa87eb0c.png)

### Environment
```bash
$ sudo npm list -g --depth=0
/usr/lib
├── @angular/cli@12.0.1
├── @compodoc/compodoc@1.1.11
├── @nestjs/cli@7.6.0
├── @ngxs/cli@2.0.0
├── @nrwl/cli@12.3.4
├── asar@3.0.3
├── clang-format@1.5.0
├── commitizen@4.2.4
├── cz-conventional-changelog@3.3.0
├── firebase-tools@9.11.0
├── grpcc@1.1.3
├── madge@4.0.2
├── npm-check-updates@11.5.13
├── npm@7.14.0
├── svgo@2.3.0
├── typescript@4.2.4
└── yarn@1.22.10
```

```bash
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.1
Node: 14.17.0
Package Manager: yarn 1.22.10
OS: linux x64

Angular: 12.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@angular/flex-layout            12.0.0-beta.34
@schematics/angular             12.0.1
rxjs                            7.0.1
typescript                      4.2.4
```

```bash
$ nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.17.0
  OS   : linux x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 12.3.4
  @nrwl/cli : 12.3.4
  @nrwl/cypress : 12.3.4
  @nrwl/devkit : 12.3.4
  @nrwl/eslint-plugin-nx : 12.3.4
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.4
  @nrwl/linter : 12.3.4
  @nrwl/nest : 12.3.4
  @nrwl/next : Not Found
  @nrwl/node : 12.3.4
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.4
  @nrwl/web : 12.3.4
  @nrwl/workspace : 12.3.4
  @nrwl/storybook : 12.3.4
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

Thank you!

**Comment by rfprod** [comment]
[This PR](https://github.com/rfprod/nx-ng-starter/pull/260) in the repository that I linked to previously fixes the issue most probably. At least I was able to build storybook locally

**Comment by mandarini** [comment]
So, should I close this issue, does it seem like it was resolved?

**Comment by rfprod** [comment]
@mandarini yes, I think it can be closed.

for anyone facing similar issues, [this repository](https://github.com/rfprod/nx-ng-starter) has a working storybook with almost all the latest dependencies
