### ISSUE TITLE
NX Move Renames Translation files contain existing name

### ISSUE THREAD

**Issue by jordanpowell88** [nrwl/nx#5766]
## Current Behavior
I recently used the nx move schematic to move a lib to another place in our monorepo. However, during a PR review, I noticed that the schematic actually changed the name of a translation file containing a copy with the name of the library

## Expected Behavior
I'm assuming that the schematic is searching for .json files and doing a find and replace. I would have expected that JSON files located inside of the i18n folders not have been used.

## Steps to Reproduce
I ran the script `nx g mv --project register domains/account/register  ` to move `libs/register` to `libs/domains/account/`. 

The schematic found some copy in a translation file with the same name `registration` and renamed it to the new lib name. You can see from the screenshot below the PR diff.
<img width="430" alt="Screen Shot 2021-05-24 at 2 04 20 PM" src="https://user-images.githubusercontent.com/3605268/119390035-6cb94a00-bc9a-11eb-8eb3-72cf9e0a4136.png">

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment
@nrwl/angular : 9.2.3
  @nrwl/cli : 9.2.3
  @nrwl/cypress : 9.2.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.2.3
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.3
  @nrwl/web : Not Found
  @nrwl/workspace : 9.2.3
  typescript : 3.8.3

**Comment by jase88** [comment]
I have also seen this behaviour.

Nx is probably aggressively scanning for string occurences. Also saw that total unrelated files like xml, md or even iOS project files were changed after moving libraries.

**Comment by AgentEnder** [comment]
Hey @jordanpowell88!

A fix for this issue was released as part of v11.1.0. Updating to this version should fix the problem. If you are still experiencing this issue, please reopen this issue.

Thanks!
Craigory.
