### ISSUE TITLE
Be able to use external schematics from a workspace generator

### ISSUE THREAD

**Issue by hadrien-toma** [nrwl/nx#5783]
## Description

> "As an intensive Nx user, I would like to be able to create generators linked to the advanced architecture Nx helped me to put in place, using `@nrwl/*` packages in order to increase my productivity."

For the moment, those Nx workspace generators are not able to use all the great features offered by Nx schematics.

## Motivation

- Increase the level of crafting provided by Nx and enhance developer experience
- Synergy between two awesome Nx tools: workspace generators and schematics 

## Suggested Implementation

I have no idea on the implementation side unfortunately... What I can tell is that it would be very nice to be able to call for instance `externalSchematic('@nrwl/angular', 'library', options);` within a workspace generator (other schematic I would like to run: `@nrwl/nx-plugin`, which seems to have no `libraryGenerator` at the time of writing).

## Related issues

- https://github.com/nrwl/nx/issues/4737#issuecomment-801293159

**Comment by hadrien-toma** [comment]
Thanks to @DominikPieper I discovered the `libGenerator` from `@nrwl/angular/generators` that have all the options I wanted. Can we consider each schematic of the `@nrwl` collection will have a generator in the feature? If yes, I propose to close this issue.

**Comment by DominikPieper** [comment]
The code I know most of the schematics which aren’t migrated already have a generated generator (nearly sure all have one already)

**Comment by hadrien-toma** [comment]
OMG you are so awesome ! :rocket: :heart: So let's go re-designing all my schematics as generators! :heart_eyes:

**Comment by hadrien-toma** [comment]
@DominikPieper I am now searching for the `libraryGenerator` of the plugin schematic (https://github.com/nrwl/nx/blob/master/packages/nx-plugin/src/schematics/plugin/plugin.ts) but I can't find it, maybe you know where is it? :persevere: In any case thanks for your support.

**Comment by DominikPieper** [comment]
@hadrien-toma  You’re right, seems there’s no generator for that yet

**Comment by hadrien-toma** [comment]
Arf, shame... all the schematics I plan to migrate will require this one to create their lib... I re-open the issue

**Comment by DominikPieper** [comment]
@hadrien-toma I added a PR #5790 for that

**Comment by hadrien-toma** [comment]
Waw, I didn't know you few days ago and now will never forget haha.

Thank you VERY MUCH :pray: .

As soon as it is migrating I will try it and will give a feedback (nevertheless I have nearly 50 schematics to migrate so it will take time).
