### ISSUE TITLE
Cypress common commands library 

### ISSUE THREAD

**Issue by kpeether** [nrwl/nx#5784]
## Description
Hi,

In our project we have a monorepo with many applications and we are using Cypress for testing. Currently each application has its own **commands.ts** file for the reusable commands. 
It is working fine but we have many commands that are not related to any application and can be used by anybody. For these common commands we would like to create a common library to be used by each application.

We tried many ways but it seems like it is not possible to make a common commands library like that.

How we are doing it:
- Created a common library called "util-cypress".
- This library contains a commands.ts file with the reusable commands.
- This commands file is exported in index.ts file like:
`export * from './libs/commands';`
- In each application we import the library in the index.ts file like:
`import '@shared/util-cypress';`

After this we get an error during the build like:
"ERROR in .. util-cypress/src/index.ts(1,15)
File .. shared/util-cypress/src/lib/commands.ts is not a module."

We tried to export the code inside commands.ts file but it was not successful. Is it possible to export commands from commands.ts file?

Has anyone made something like that before? Or do you have any ideas how we could make this?

## Motivation
Common Cypress commands library to increase code reusability and avoid code duplication.

## Suggested Implementation
Somehow export commands.ts code as a module?

**Comment by twittwer** [comment]
Is this helping?
https://youtu.be/VpZCn33WuF8
