### ISSUE TITLE
Skipping migration as the workspace uses third-party builders which may require "emitDecoratorMetadata" TypeScript compiler option.

### ISSUE THREAD

**Issue by dean-g** [nrwl/nx#5785]
why am I getting following waring while executing the migration command? 

![image](https://user-images.githubusercontent.com/12157452/119545001-e9f6c480-bd57-11eb-8dcd-dd44f7be901b.png)

**Comment by vsavkin** [comment]
Thank you for submitting the issue. 

Those are the migrations authored by the Angular folks, we are running.
