### ISSUE TITLE
question: nx workspace vs angular-cli 6 workspace

### ISSUE THREAD

**Issue by ternyk** [nrwl/nx#579]
I realy like concept of workspace in nx and plan to use it in quite large project (three aplications, shared libraries, monorepo) but after introducing a "workspace" in angular-cli 6 it seems that it has a similiar concept (already angular-cli and no need for additional dependency of nx in the project). The other thing that workspace's in angular-cli is not yet mature what I had seen so far.
Is there some danger that nx workspace would not be compatible in newer angular-cli?

**Comment by vsavkin** [comment]
It's a good question. This blog post answer this question: https://blog.nrwl.io/announcing-nrwl-nx-6-0-29b963d87d8e

TLDR: Nx is an extension for the CLI that enables monorepo-style development, improves dev experience, and provides useful conventions. It's an extension, so there is NO danger that they would be incompatible.
