### ISSUE TITLE
Service created in the first app instead of in the specified lib

### ISSUE THREAD

**Issue by mehulgupta29** [nrwl/nx#580]
I am following the tutorial - https://angularplaybook.com/courses/264974/lectures/4113840
and when i run the command "ng g service ticket **-a=backend**" it creates the ticket service in "customer-portal" app instead of "backend" lib.
![image](https://user-images.githubusercontent.com/16285656/41194428-ffde61a4-6be8-11e8-8775-c6ac68d33eea.png)

**Comment by mehulgupta29** [comment]
Removed package.json from the issue

**Comment by vsavkin** [comment]
The playbook course uses the older version of the CLI. The new version takes `--project` instead of `-a`, so you can generate the service by running `ng g service ticket --project=backed`.

You can also run  `ng g service --help` to see the list of options you can pass.
