### ISSUE TITLE
Improve documentation on how to write generators/executors

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#5801]
I found this video which describes the process of writing a simple generator.
https://www.youtube.com/watch?v=ki2eOXvh2Sw

I'd like to create a Vite builder, to try to replace and improve upon `@nrwl/web:dev-server`.

The [documentation on the website ](https://nx.dev/latest/react/executors/creating-custom-builders#creating-nx-executors-or-angular-devkit-builders-in-your-nx-workspace)is not very useful...

Please provide a guide on how to write this... executor?

**Comment by bilalshaikh42** [comment]
This might be relevant as I believe the generators are the same or at least quite similar to angular.

https://angular.io/guide/cli-builder
