### ISSUE TITLE
Document and simplify usage of cypress component tests

### ISSUE THREAD

**Issue by madelk** [nrwl/nx#5814]
## Description
I would like to see either good document on how to run component testing with Cypress or have it added to the generator when creating libraries

## Motivation
Testing with Jest is limited and cypress offers more features, however E2E requires the entire app be tested every time with every test. For large apps with hundreds of components this isn't maintainable. Component tests should now be supported https://github.com/nrwl/nx/issues/5622 however the implementation isn't easy to follow

I have tried to wire up component tests in a public test repo but I've been unable to succeed: https://github.com/madelk/nx-component-testing/pull/1

**Comment by barbados-clemens** [comment]
Better cypress component test support in nx is planned for the release of cypress v10. Closing for now 👍
