### ISSUE TITLE
Image typings break when adding storybooks to a react lib component

### ISSUE THREAD

**Issue by LiamMyles** [nrwl/nx#5817]
## Current Behavior

After adding storybooks to a generated react library, types from `@nrwl/react/typings/image.d.ts` seem to get lost, resulting in type checking failing to properly handle image files.

Currently, I'm using VScode to confirm types are correct. Below is a screenshot of the type error.

![type error on logo.svg](https://user-images.githubusercontent.com/10930659/119909998-14aa6e00-bf4e-11eb-995a-57e524b9fa74.png)

You can also [check out this example repo](https://github.com/LiamMyles/nx-tinkering/tree/storybook-type-issue/storybooks-issue/storybooks-tinkering) which contains the erroring code  located at `storybooks-tinkering/libs/react-component/`

Code from the screenshot:
```jsx
import styled from 'styled-components';
import logo from './logo.svg';

/* eslint-disable-next-line */
export interface ReactComponentProps {}

const StyledReactComponent = styled.div`
  color: pink;
`;

export function ReactComponent(props: ReactComponentProps) {
  return (
    <StyledReactComponent>
      <h1>Welcome to react-component!</h1>
      <img src={logo} alt="nice little logo" />
    </StyledReactComponent>
  );
}

export default ReactComponent;
```

### Possible Fix

I have fixed the error in my repo at work by changing the `.storybooks/tsconfig.json` `include` from `../src/**/*` to `../src/**/*.stories.*`. I'm not sure if this is the best fix, but another possible fix was to change `react-component/tsconfig.json` by reordering the `references` array and putting the `.storybooks/tsconfig.json` reference first.

## Expected Behavior

When you add storybooks to a react component, no image imports are affected by type errors.

### Git Repo
Checkout [this nx-tinkering repo](https://github.com/LiamMyles/nx-tinkering) and navigate to `/storybooks-issue/storybooks-tinkering/libs/react-component/src/lib/react-component.tsx /` in VSCode, or another IDE that can check types.

### Recreate via nx commands

- Create a react workspace: `npx create-nx-workspace --preset=react`
- Generate a react lib component: `nx generate @nrwl/react:library --name=react-component --no-interactive`
- Add storybooks to the react lib component: `nx generate @nrwl/react:storybook-configuration --name=react-component --no-configureCypress --no-generateCypressSpecs --no-interactive`
- Move an image into `libs/react-component/src/lib` - The default app will have a logo.svg you can copy -
- Import the image into `react-component.tsx`

You should now see the following error message when you mouse over the image import:
> Cannot find module './logo.svg' or its corresponding type declarations.

### Failure Logs

Nothing extra to add.

### Environment

```bash
  NX  Report complete - copy this into the issue template

  Node : 15.1.0
  OS   : linux x64
  npm  : 7.0.8
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.3.5
  @nrwl/cypress : 12.3.5
  @nrwl/devkit : 12.3.5
  @nrwl/eslint-plugin-nx : 12.3.5
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.5
  @nrwl/linter : 12.3.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 12.3.5
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.5
  @nrwl/web : 12.3.5
  @nrwl/workspace : 12.3.5
  @nrwl/storybook : 12.3.5
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by Polm1** [comment]
Will follow with much interest because I am currently facing with this, for now I've solved adding:

`"files": ["../../../node_modules/@nrwl/react/typings/image.d.ts"],`

to `tsconfig.json` of `.storybook` folder
