### ISSUE TITLE
Transitive dependencies aren't included in generated package.json

### ISSUE THREAD

**Issue by moredhel** [nrwl/nx#5820]
I have generated an app & a lib. In the library. The library just needs to be included in the `node_modules` & needn't actually be used in the application itself. (for performing admin tasks pre-boot in the container).

## Current Behavior
I have set the following:
`"my-service": { "tags": [], "implicitDependencies": ["config"] },` in `nx.json`.

And in the config library _index.ts_: `require('dotenv').config()`.

When I build the service though with nx, I don't see `dotenv` in the generated `package.json` located at:
`dist/apps/my-service/package.json`.

If I grep the generated `main.js`, I also don't see any reference to the included library.

## Expected Behavior

From my understanding of these docs:
https://nx.dev/latest/node/structure/dependency-graph

I would expect adding the `config` library to `implicitDependencies` would automatically include the dependant library (and all transitive dependencies).

This doesn't seem to be the case , & I haven't found any way to manually inject a(n already tracked library) so it is picked up when automatically generating the `package.json`.

I'm not sure this is a regression.

## Steps to Reproduce

A sample repo: https://github.com/moredhel/nx-demo

### Expectation
```
rm -rf node_modules/
cd dist/my-service
npm i
node -r dotenv/config main.js
```

### Actual
```
cd dist/my-service
npm i
node -r dotenv/config main.js
## fail...
```

### Environment

```
>  NX  Report complete - copy this into the issue template

  Node : 14.17.0
  OS   : darwin arm64
  npm  : 6.14.13

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.3.5
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.3.5
  @nrwl/eslint-plugin-nx : 12.3.5
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.5
  @nrwl/linter : 12.3.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.3.5
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.5
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.5
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by j** [comment]
I just came across this as well.

My generated `package.json` doesn't seem to be including dependencies from libraries I'm using.

**Comment by valerius21** [comment]
I had the same error. Since I am containerizing my apps, I accidentally started the development version via `nx serve ...`. After changing the working directory to the corresponding `dist` directory, everything worked.

**Comment by Ion-manden** [comment]
```
        "externalDependencies": "none",
        "generatePackageJson": true
```
adding `"externalDependencies": "none"` seems to have worked for me

not pretty but it is a workaround for now

**Comment by 31i0t** [comment]
You can find the source for `generatePackageJson` [here](https://github.com/nrwl/nx/blob/master/packages/workspace/src/utilities/create-package-json.ts).

You might be surprised to find it's just an `executor` so you can write your own if this is something you really care about. For me, I wrote something that recursively imported packages from `libs/*` along with dependencies/peerDependencies because I wanted to deploy projects installing as little deps as possible from the root package.json, but you can adapt it for your use-case. Here's the code (mind you it's not battle-tested but works for me):

```ts
import chalk from "chalk";
import { execSync } from 'child_process';
import { readJsonFile, readCachedProjectGraph, readJson } from "@nrwl/devkit";
import rJSON from "relaxed-json";
import { flow, forEach, map, filter, replace, flatMap, uniq, isNil, keys, join, toPairs, find } from "lodash/fp";

import type { ExecutorContext, ProjectGraphDependency } from "@nrwl/devkit"

interface Schema {
	preInstallPackages: string[]
}
interface FetchedPeerDependencies {
	[key: string]: string;
}

const initialPackageMatchers: (RegExp | string)[] = [
	/^@nrwl.*/,
	"nx",
	"chalk",
	"relaxed-json",
	"lodash"
]

const getLibDependencies = (
	projectName: string,
	dependencies: Record<string, ProjectGraphDependency[]>,
	libDependencies = []
) => {
	const projectDeps = dependencies[projectName];
	const libDependenciesOfProject = filter(({ target }) => !target.startsWith("npm"), projectDeps);

	forEach(({ target }) => {
		getLibDependencies(target, dependencies, libDependencies);
	}, libDependenciesOfProject)

	libDependencies.push(filter(({ target }) => target.startsWith("npm"), projectDeps))
	return flow(
		flatMap((deps: ProjectGraphDependency[]) => map(({ target }) => target, deps)),
		uniq,
	)(libDependencies)
}

const fetchPeerDependencies = (targetPackage: string): FetchedPeerDependencies => {
	const peerDependencies = execSync(`npm info ${targetPackage} peerDependencies`, { encoding: 'utf-8' });
	
	return peerDependencies === ""
		? {}
		: rJSON.parse(peerDependencies)
}

const getPeerDependencies = (packageName: string, peerDependencies = []) => {
	if (find(packageName, keys(peerDependencies))) {
		return;
	}

	const fetchedPeerDependencies = fetchPeerDependencies(packageName);
	forEach((peerDep) => {
		getPeerDependencies(peerDep);
	}, keys(fetchedPeerDependencies))

	peerDependencies.push(fetchedPeerDependencies);
	return flow(
		map((peerDeps) => keys(peerDeps)),
		flatMap((deps) => deps),
		uniq
	)(peerDependencies)
}

const installPackages = async (
	{ preInstallPackages = [] }: Schema,
	{ projectName, root }: ExecutorContext
) => {
	const {
		dependencies: rootDependencies,
		devDependencies: rootDevDependencies
	} = readJsonFile(`${root}/package.json`);
	
	const initialPackages = flow(
		keys,
		(matchers) => [...matchers, ...preInstallPackages],
		filter((dep) => Boolean(
			find((matcher) => typeof matcher === "string"
					? matcher === dep
					: matcher.test(dep)
			, initialPackageMatchers
		)))	
	)({ ...rootDevDependencies, ...rootDependencies });

	console.log(chalk.bold.green(`Identified the following initial packages:\n`))
	forEach((dep) => {
		console.log(`  ${chalk.bold(dep)}\n`)
	}, initialPackages)
	execSync(`npm install ${join(' ', initialPackages)} --no-save`);

	const { dependencies } = readCachedProjectGraph();
	const withLibDeps = getLibDependencies(projectName, dependencies)
	const withoutDevDependencies = flow(
		map((dep: string) => replace('npm:', '', dep)),
		filter((dep) => dep in rootDependencies)
	)(withLibDeps);
	const withPeerDependencies = flow(
		map((dep: string) => getPeerDependencies(dep)),
		flatMap((deps) => deps),
		(deps) => [...deps, ...withoutDevDependencies],
		uniq,
		filter((dep) => !isNil(dep)),
		filter((dep) => dep in rootDependencies)
	)(withoutDevDependencies);

	console.log(chalk.bold.green(`Identified the following dependencies:\n`))
	forEach((dep) => {
		console.log(`  ${chalk.bold(dep)}\n`)
	}, withPeerDependencies)


	
	execSync(`npm install ${join(" ", withPeerDependencies)} --no-save`)

	return { success: true }
}

export default installPackages;
```

**Comment by nartc** [comment]
Please retry with latest. As mentioned in https://github.com/nrwl/nx/issues/6840#issuecomment-1166183147, transitive dependencies seem to be included in the generated `package.json` now. If you still have problem, please provide a new reproduce procedure.

**Comment by jensbodal** [comment]
Does this or the other issue cover issues with not including transitive dependencies from imports from other packages (whether you own them or not)?

Is there something I should be doing in my other package to allow it to be picked up?

Essentially the same type of issue, just instead of importing from a local `lib` package, I’m importing a function from another package which uses dotenv

**Comment by jensbodal** [comment]
Yes referring to external packages to the monorepo which are also in a monorepo which we also own. 

And rethinking my question I’m not sure why I asked, what you described is just expected npm behavior for external packages so that makes sense.

Thanks!

**Comment by francisaguilar21** [comment]
Just in case someone is still experiencing this old issue and the solutions above doesn't cut it. The one in issue [2625](https://github.com/nrwl/nx/issues/2625#issuecomment-881830299) can be a workaround and it worked perfectly for our solution.
