### ISSUE TITLE
Ormconfig.json not found when nx serve api

### ISSUE THREAD

**Issue by Pablodotnet** [nrwl/nx#5830]
## Current Behavior
I integrated typeorm and managed to do the migrations which is an error I've seen a lot of people have too, but after solving this issue, I found another when trying to run my api again, at the moment I do `nx serve api` it throws me an error where it says `ormconfig.json` is not found on the root folder which it is, there's the file

## Expected Behavior
Serve my api without errors

## Steps to Reproduce
Integrate typeorm and try to serve your api.

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs
`Luiss-MacBook-Pro:pablodotjs luispablo$ nx serve api
> nx run api:serve 
Starting type checking service...
Using 14 workers with 2048MB memory limit
Type checking in progress...
Hash: 42f1f70da8e68440cfc2
Built at: 05/28/2021 8:51:07 PM
Entrypoint main [big] = main.js main.js.map
chunk {main} main.js, main.js.map (main) 2.94 MiB [entry] [rendered]
WARNING in ./node_modules/TypeORM/connection/ConnectionOptionsReader.js 118:45-64
Critical dependency: the request of a dependency is an expression
WARNING in ./node_modules/TypeORM/connection/ConnectionOptionsReader.js 130:44-63
Critical dependency: the request of a dependency is an expression
WARNING in ./node_modules/TypeORM/platform/PlatformTools.js 110:19-81
Critical dependency: the request of a dependency is an expression
WARNING in ./node_modules/TypeORM/util/DirectoryExportedClassesLoader.js 42:38-94
Critical dependency: the request of a dependency is an expression
WARNING in ./node_modules/TypeORM/util/DirectoryExportedClassesLoader.js 56:38-94
Critical dependency: the request of a dependency is an expression
WARNING in ./node_modules/TypeORM/platform/PlatformTools.js
Module not found: Error: Can't resolve '@sap/hana-client' in '/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/TypeORM/platform'
WARNING in ./node_modules/TypeORM/platform/PlatformTools.js
Module not found: Error: Can't resolve 'better-sqlite3' in '/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/TypeORM/platform'
WARNING in ./node_modules/TypeORM/platform/PlatformTools.js
Module not found: Error: Can't resolve 'hdb-pool' in '/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/TypeORM/platform'
WARNING in ./node_modules/TypeORM/platform/PlatformTools.js
Module not found: Error: Can't resolve 'ioredis' in '/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/TypeORM/platform'
WARNING in ./node_modules/TypeORM/platform/PlatformTools.js
Module not found: Error: Can't resolve 'mongodb' in '/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/TypeORM/platform'
WARNING in ./node_modules/TypeORM/platform/PlatformTools.js
Module not found: Error: Can't resolve 'mssql' in '/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/TypeORM/platform'
WARNING in ./node_modules/TypeORM/platform/PlatformTools.js
Module not found: Error: Can't resolve 'mysql' in '/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/TypeORM/platform'
WARNING in ./node_modules/TypeORM/platform/PlatformTools.js
Module not found: Error: Can't resolve 'mysql2' in '/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/TypeORM/platform'
WARNING in ./node_modules/TypeORM/platform/PlatformTools.js
Module not found: Error: Can't resolve 'oracledb' in '/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/TypeORM/platform'
WARNING in ./node_modules/TypeORM/platform/PlatformTools.js
Module not found: Error: Can't resolve 'pg-native' in '/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/TypeORM/platform'
WARNING in ./node_modules/TypeORM/platform/PlatformTools.js
Module not found: Error: Can't resolve 'pg-query-stream' in '/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/TypeORM/platform'
WARNING in ./node_modules/TypeORM/driver/react-native/ReactNativeDriver.js
Module not found: Error: Can't resolve 'react-native-sqlite-storage' in '/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/TypeORM/driver/react-native'
WARNING in ./node_modules/TypeORM/platform/PlatformTools.js
Module not found: Error: Can't resolve 'react-native-sqlite-storage' in '/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/TypeORM/platform'
WARNING in ./node_modules/TypeORM/platform/PlatformTools.js
Module not found: Error: Can't resolve 'redis' in '/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/TypeORM/platform'
WARNING in ./node_modules/TypeORM/platform/PlatformTools.js
Module not found: Error: Can't resolve 'sql.js' in '/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/TypeORM/platform'
WARNING in ./node_modules/TypeORM/platform/PlatformTools.js
Module not found: Error: Can't resolve 'sqlite3' in '/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/TypeORM/platform'
WARNING in ./node_modules/TypeORM/platform/PlatformTools.js
Module not found: Error: Can't resolve 'typeorm-aurora-data-api-driver' in '/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/TypeORM/platform'
Debugger listening on ws://localhost:54345/38b52364-9873-4900-82b3-e68c13357700
Debugger listening on ws://localhost:54346/38b52364-9873-4900-82b3-e68c13357700
For help, see: https://nodejs.org/en/docs/inspector
(node:57172) UnhandledPromiseRejectionWarning: Error: Cannot find module '/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/ormconfig.json'
    at webpackEmptyContext (/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/dist/apps/api/webpack:/node_modules/TypeORM/connection sync:2:1)
    at ConnectionOptionsReader.<anonymous> (/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/dist/apps/api/webpack:/node_modules/TypeORM/connection/ConnectionOptionsReader.js:130:45)
    at step (/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/tslib/tslib.js:124:57)
    at /Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/tslib/tslib.js:113:16)
    at ConnectionOptionsReader../node_modules/TypeORM/connection/ConnectionOptionsReader.js.ConnectionOptionsReader.load (/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/dist/apps/api/webpack:/node_modules/TypeORM/connection/ConnectionOptionsReader.js:90:1)
    at ConnectionOptionsReader.<anonymous> (/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/dist/apps/api/webpack:/node_modules/TypeORM/connection/ConnectionOptionsReader.js:32:1)
    at step (/Users/luispablo/Documents/MyGit/pablodotjs/pablodotjs/node_modules/tslib/tslib.js:143:27)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:57172) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:57172) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
No type errors found
Version: typescript 4.2.4
Time: 7362ms`

**FOLDER STRUCTURE**

<img width="447" alt="Screen Shot 2021-05-28 at 21 08 23" src="https://user-images.githubusercontent.com/10190000/120054977-df0e8f00-bff8-11eb-94e8-2a968247d418.png">

**Environment**
<img width="504" alt="Screen Shot 2021-05-28 at 21 09 49" src="https://user-images.githubusercontent.com/10190000/120055005-0ebd9700-bff9-11eb-869e-cca23855cdd7.png">

**Comment by johannesschobel** [comment]
i believe, the `ormconfig.js` file should be moved to the `apps/api` folder. Because, in your project you may have multiple apis and databases (i.e., microservice architecture). This will - certainly - not work when having the `ormconfig.js` file on the top-level of the workspace

**Comment by AgentEnder** [comment]
@Pablodotnet Can you confirm if moving the ormconfig.js fixes your issue?

**Comment by Pablodotnet** [comment]
Not working yet, Im getting now `UnhandledPromiseRejectionWarning: Error: No connection options were found in any orm configuration files.`

**Comment by AgentEnder** [comment]
@Pablodotnet I'm trying to focus on this issue now, and can confirm that when using nest it unfortunately looks in the root directory of your workspace (vs your app). A work around for this, is to add `process.env.APP_ROOT_PATH = __dirname` somewhere above the import of app.module.ts inside main.ts.

Your initial issue seems to not be caused by the ormconfig.json file not being found though, as it was at the workspace root. Can you share the non-sensitive portions of the file?
