### ISSUE TITLE
Long rebuild/build time

### ISSUE THREAD

**Issue by gtokarz** [nrwl/nx#5837]
## Current Behavior
I have noticed one of my small repos have quite long build times, upon further investigation before each webpack starting there is long running git command which is responsible for 70% of build time. After renaming .git directory it seems it is not starting the git process resulting in really fast builds/rebuilds. 

## Expected Behavior
Looking for a way to disable this git behaviour

## Steps to Reproduce

1. Start nx build
2. It spawns git process depending on repo size it might be fast or take ages

### Environment
Windows 10, nx 11

**Comment by PavelValentov** [comment]
I have 10 apps, more than 40 libs and 2.9GB repo.
1 month ago I've got the issue.
"nx run-many" command lasts 45 minutes instead of 5-7 minutes.

Nx 11, Debian

**Comment by MarcinCebula** [comment]
Solution: delete project and git clone it again.

Ran in to the same exact issue. I'm not sure what caused it but deleting the project and cloning it again fixes the issue.

Replicated on Mac Mini M1 with BigSurf 
Just to confirm the behavior. After running any kind of nx command if you look at your process list, git appear to be taking up 99% to 100%. of the CPU on 1 to 2 threads. It runs on 2 Threads and Idle Wake Ups are going up as time progresses. It eventually finishes but it takes a very long time.

Renaming the .git directory does solve the issue but that is not a solution obviously.

**Comment by vsavkin** [comment]
Really sorry for the late reply.

Do you have issue running this? 

```
git ls-tree HEAD -r -z 
```

How long does it take?

**Comment by MarcinCebula** [comment]
@vsavkin I can’t test the solution cause the issue hasn’t come back, but if it does I’ll let you know. 
As goes for the second question, the task would run anywhere between 10 and 20min. The task being any nx command (nx run project:serve)

**Comment by vsavkin** [comment]
> As goes for the second question, the task would run anywhere between 10 and 20min. The task being any nx command (nx run project:serve)

Sorry I'm not sure what question you are referring to. The serve command doesn't terminate, so i'm not sure if it is the best example to use for measuring timings.
