### ISSUE TITLE
Support Prettier Eslint

### ISSUE THREAD

**Issue by Xenfo** [nrwl/nx#5838]
## Description

Support Eslint Prettier integration where Eslint will detect Prettier problems and be able to fix them.

## Motivation

I like to know when I'm breaking styling rules and it also allows you to fix styling rules in CI using the linter.

## Suggested Implementation

Extend `plugin:prettier/recommended` via the package `eslint-plugin-prettier` in the current configs or add a new set of configs that can be access via
```json
{
  "extend": ["@nrwl/nx/prettier"]
}
and/or
{
    "files": ["*.ts", "*.tsx"],
    "extends": ["plugin:@nrwl/nx/prettier/typescript"],
    "rules": {}
}
```

**Comment by meeroslav** [comment]
Thank you for the feature request @Xenfo.

Unfortunately, implementation of this feature would most likely be distracting and/or annoying to users. Additionally, linter should be focusing on the code analysis to find issues. Coding style, is not code issue per se. These two should have clear separation of concerns.

As `prettier` is included in NX it's easy to run formatting on pre-commit or pre-push hook. It also allows people to opt out of prettier if they don't like it.

You can run `nx format --all` which would find styling issues and fix them.

Hope that helps
