### ISSUE TITLE
nx run my-lib:lint : registry.useXDeprecatedProvider is not a function

### ISSUE THREAD

**Issue by dean-g** [nrwl/nx#5862]
I just pulled the latest version of the nrwl and running into the following error while running affected lint, 
 "@nrwl/angular": "12.3.5",

yarn affected:lint

> nx run my-lib:lint 
registry.useXDeprecatedProvider is not a function

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This is a duplicate of https://github.com/nrwl/nx/issues/5829, even though the command is different, the issue is the same. Please check that issue for a solution to this problem.

Closing.
