### ISSUE TITLE
maintaining multiple conf files with version 6.

### ISSUE THREAD

**Issue by a5hik** [nrwl/nx#590]
After the version 6 upgrade my app is having multiple protractor.conf files for the apps.. and there are multiple conf files for karma.. 

Actually, I wanted to add some additional configs to these files for my CI setup.. looks like I had to touch every file and do this changes. It will soon be cluttered when the libs count grows beyond ~50. and I feel maintaining that would be difficult.

Is there a way I can override the karma.conf code gen, so that I can customize according to my need.
Or, whether I can have a common conf, and extend it.
any other cleaner approach to do it?

**Comment by FrozenPandaz** [comment]
I'm planning to work on having the project karma/protractor.confs extend one in the root directory.

This would allow you to have most of the configuration in the root applied to all projects and then the projects can override certain options as they please.

Does this solve your issue?

**Comment by listepo-alterpost** [comment]
@FrozenPandaz  any news for protractor.confs ?
