### ISSUE TITLE
npx nx build frontend-next --prod --outputPath=. stopped working after upgrading from 12.1.1

### ISSUE THREAD

**Issue by therk** [nrwl/nx#5904]
Per https://nx.dev/latest/react/guides/nextjs the build command should specify --outputPath=. to work with Vercel.

## Current Behavior
λ  (Lambda)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

———————————————————————————————————————————————

>  NX   ERROR  Running target "frontend-next:build" failed

## Expected Behavior
λ  (Lambda)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

———————————————————————————————————————————————

>  NX   SUCCESS  Running target "build" succeeded

## Steps to Reproduce
Create NextJS app called frontend-next and run the following command:
npx nx build frontend-next --prod --outputPath=. 

### Environment

>  NX  Report complete - copy this into the issue template

  Node : 14.15.5
  OS   : darwin x64
  npm  : 6.14.11
  
  nx : 12.3.6
  @nrwl/angular : Not Found
  @nrwl/cli : 12.3.6
  @nrwl/cypress : 12.3.6
  @nrwl/devkit : 12.3.6
  @nrwl/eslint-plugin-nx : 12.3.6
  @nrwl/express : 12.3.6
  @nrwl/jest : 12.3.6
  @nrwl/linter : 12.3.6
  @nrwl/nest : Not Found
  @nrwl/next : 12.3.6
  @nrwl/node : 12.3.6
  @nrwl/react : 12.3.6
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.6
  @nrwl/web : 12.3.6
  @nrwl/workspace : 12.3.6
  @nrwl/storybook : 12.3.6
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by Divlo** [comment]
Same issue.
Running `npx nx build website --prod --outputPath=.` on Vercel, shows this error :
```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
 ```

**Comment by puku0x** [comment]
There is a workaround https://github.com/nrwl/nx/issues/5660#issuecomment-841639368

**Comment by Divlo** [comment]
> There is a workaround https://github.com/nrwl/nx/issues/5660#issuecomment-841639368

Right, thanks! @puku0x 
Is this issue a duplicate ?
We should probably close this one, if the #5660 issue is the same one.

**Comment by therk** [comment]
The workaround from https://github.com/nrwl/nx/issues/5660#issuecomment-841639368 worked
