### ISSUE TITLE
Unable to see any change in Package.JSON after attempting angular 11.0.8 update to angular 12

### ISSUE THREAD

**Issue by kevin192291** [nrwl/nx#5909]
## Current Behavior

NX does not update angular to the latest version when running: nx migrate latest
This command yields NO a migrations.json to angular 12 and results in this message:

```
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest
Fetching @nrwl/workspace@12.3.6

>  NX  The migrate command has run successfully.

- package.json has been updated
- there are no migrations to run, so migrations.json has not been created.

>  NX  Next steps:

- Make sure package.json changes make sense and then run 'npm install'
- To learn more go to https://nx.dev/latest/core-concepts/updating-nx
```
running npm install does nothing.

## Expected Behavior

I believe that this process should take me from:
my Packages.json:
```
"dependencies": {
    "@angular/animations": "~11.0.8",
    "@angular/common": "~11.0.8",
    "@angular/compiler": "~11.0.8",
    "@angular/core": "~11.0.8",
    "@angular/forms": "~11.0.8",
    "@angular/localize": "^11.0.8",
```
TO:
```
"dependencies": {
    "@angular/animations": "~12.x.x",
    "@angular/common": "~12.x.x",
    "@angular/compiler": "~12.x.x",
    "@angular/core": "~12.x.x",
    "@angular/forms": "~12.x.x",
    "@angular/localize": "^12.x.x",
```

## Steps to Reproduce

running the commands:
nx migrate latest
npm install

### Environment

  Node : 15.10.0
  OS   : linux x64
  npm  : 7.16.0
  
  nx : Not Found
  @nrwl/angular : 12.3.6
  @nrwl/cli : 12.3.6
  @nrwl/cypress : 12.3.6
  @nrwl/devkit : 12.3.6
  @nrwl/eslint-plugin-nx : 12.3.6
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.6
  @nrwl/linter : 12.3.6
  @nrwl/nest : 12.3.6
  @nrwl/next : Not Found
  @nrwl/node : 12.3.6
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.6
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.6
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.0.5

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Unfortunately, I was unable to reproduce the issue, I tried upgrading an Nx workspace from v12.2.0 (pre Angular 12) to v12.4.0 and it generated the right migrations.

In order to help us troubleshoot this issue, could you please share a reproduction repo?
