### ISSUE TITLE
should remove path in tsconfig.base when running remove

### ISSUE THREAD

**Issue by maxisam** [nrwl/nx#5910]
When I run 

ng generate @nrwl/workspace:remove --projectName

## Current Behavior

it removes everything but path in tsconfig.base

## Expected Behavior

should remove the path

## Steps to Reproduce
Generate an angular lib with importPath

remove it 

### Environment
nx v12.3.5

**Comment by puku0x** [comment]
It seems it removes the path only when the library is in `libs/` (five letters).
https://github.com/nrwl/nx/blob/b4d27fcfd7a1412be70baeb9c0495f9d3c160cc6/packages/workspace/src/generators/remove/lib/update-tsconfig.ts#L23-L26

**Comment by maxisam** [comment]
Ah. that is why. Why don't we use the importPath?
