### ISSUE TITLE
Bump prettier version

### ISSUE THREAD

**Issue by GalDayan** [nrwl/nx#5911]
## Description
NX Support latest prettier version

## Motivation
NX Should support caret prettier

## Suggested Implementation
in package.json		`"prettier": "^2.2.1",`

**Comment by puku0x** [comment]
Wow, `prettier@2.3.1` supports TypeScript 4.3! 
https://github.com/prettier/prettier/blob/main/CHANGELOG.md#231

**Comment by Phillip9587** [comment]
See #5623. @puku0x I will update the PR to prettier 2.3.1 tomorrow.

**Comment by GalDayan** [comment]
> See #5623. @puku0x I will update the PR to prettier 2.3.1 tomorrow.

Great thanks for your fast response

**Comment by Phillip9587** [comment]
Closed by #5623
