### ISSUE TITLE
"Prerender" run is cached but not rewritten

### ISSUE THREAD

**Issue by GrandSchtroumpf** [nrwl/nx#5915]
## Current Behavior
When I run `nx run marketplace:prerender:dev` for the first time the result is cached.
If I delete the content of the `dist` folder, and run  `nx run marketplace:prerender:dev` again, the console uses the cache but do not write the result of prerender.
The `build` command on the other hand works well.

## Expected Behavior
The folder should be generated from the cache.
Is it a regression: Yes, this was working before v12.

## Steps to Reproduce
```
npx create-nx-workspace marketplace --preset=angular
cd marketplace
nx add @nguniversal/express-engine
```
add "prerender" in nx.config.json > tasksRunnerOptions.default.runner.cacheableOperations
```
nx run marketplace:prerender
rm -rf dist
nx run marketplace:prerender
cd dist/apps/marketplace
cd: dist/apps/marketplace: No such file or directory
```
marketplace folder is not generated

### Environment
```
  Node : 14.15.4
  OS   : win32 x64
  npm  : 6.14.10

  nx : Not Found
  @nrwl/angular : 12.3.6
  @nrwl/cli : 12.3.6
  @nrwl/cypress : 12.3.6
  @nrwl/devkit : 12.3.6
  @nrwl/eslint-plugin-nx : 12.3.6
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.6
  @nrwl/linter : 12.3.6
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.3.6
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.6
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.6
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by FrozenPandaz** [comment]
You need to add `outputs` to the target configuration:

```
"prerender": {
  "builder": "@nguniversal/express-engine:prerender",
  "output": ["dist/my-app/browser"],
  "options": {...}
}
```

Then the files will be restored properly.

I should warn you however, If your application calls external APIs (outside of the repo) to prerender the content. If the app is cached, this would mean you may have stale results. If the APIs are part of the same repo though, that's actually super cool! :tada:

**Comment by GrandSchtroumpf** [comment]
I updated the `angular.json` file with the output and I still see the issue.
Here is my config:
```
"prerender": {
  "builder": "@nguniversal/builders:prerender",
  "output": ["dist/apps/marketplace/browser"],
  "options": {
    "browserTarget": "marketplace:build",
    "serverTarget": "marketplace:server",
    "guessRoutes": true,
  }
},
```
I also tried with `"output": ["dist/apps/marketplace"],`, but none of them is working.
Here is my local taskRunnerOptions: 
```
"local": {
  "runner": "@nrwl/workspace/tasks-runners/default",
  "options": {
    "cacheableOperations": ["build", "lint", "test", "e2e", "server", "prerender"]
  }
}
```
