### ISSUE TITLE
Jest + SVGR

### ISSUE THREAD

**Issue by cyrus-za** [nrwl/nx#5922]
I am not sure why https://github.com/nrwl/nx/issues/4850 was closed but I am not able to test any react components that import a svg file, no matter what jest config I try from the solutions out there. Something in the nx preset must be breaking it

**Comment by Lonli-Lokli** [comment]
It's not stale

**Comment by Lonli-Lokli** [comment]
Copy from closed thread

For those who interested in workaround:

edit root jest.preset.js
```module.exports = {
    ...nxPreset,
    moduleNameMapper: {
     '\\.svg': '<rootDir>/../../testing/svgrMock.js'
    }
};
```
Please note two /.. after root dir. Due to #8029 all libs folders are using their src as rootDir

add /testing/svgr.Mock.js
`module.exports = { ReactComponent: 'IconMock' }`

**Comment by StephenStrickland** [comment]
@Lonli-Lokli I've tried your approach and still cannot get around the error:
```ts
 // error TS2307: Cannot find module './brand-icon.svg' or its corresponding type declarations.
 import { ReactComponent as BrandIcon} from './brand-icon.svg';
```

**Comment by Lonli-Lokli** [comment]
@StephenStrickland 
Are you sure you have physically this file?

Here is my repo with failing and fixed test, in 3 commits https://github.com/Lonli-Lokli/nx-reacticon
1) Initial commit with Nx
2) Commit with failing test ( npx nx run header:test)
3) Commit with fixed test.

The only diff with my approach is content fo svgrMock - test was passing but with console error.

**Comment by StephenStrickland** [comment]
@Lonli-Lokli I think I figured out the issue, we're using `ts-jest` instead of `babel-jest`, your solution works with `babel-jest` and `ts-jest` seems to ignore all solutions for loading svgs. Still digging into why `ts-jest` is giving me issues.

**Comment by Lonli-Lokli** [comment]
@StephenStrickland have you tried this? 
https://medium.com/@real-biel/jest-typescript-and-svgs-44b4333a1164
