### ISSUE TITLE
Typescript not working correctly with attributes that are possibly undefined

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#5924]
I've noticed that the Typescript is not working correctly when a potentially undefined attribute doesn't report that accessing properties on that attribute directly should be avoided.

This incorrect behavior of Typescript makes it very difficult to have any confidence in the code that is written.

## Current Behavior

**Intellij Idea**
![image](https://user-images.githubusercontent.com/77624664/121197064-489c6200-c871-11eb-9261-7148d150fa5c.png)
This should not be passing. 

**VS Code**
![image](https://user-images.githubusercontent.com/77624664/121196290-a41a2000-c870-11eb-91ce-4486d0ba9b55.png)
Same problem.

If I would add a third type to the union so that there are `string | number | undefined` the Typescript would understand the first two, but not the `undefined`:
![image](https://user-images.githubusercontent.com/77624664/121200864-5acbcf80-c874-11eb-92f0-b636680a4be3.png)

## Expected Behavior

When I've tested another Typescript project, outside of the NX, it behaved correctly:
![image](https://user-images.githubusercontent.com/77624664/121200502-16d8ca80-c874-11eb-8937-8abd2a2aa2a2.png)
This is how Typescript should behave.

## Steps to Reproduce

It doesn't matter where, in the monorepo, I've tried this, it always behaved the same.

<details>
<summary>tsconfig.base.json</summary>

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2017", "dom", "ESNext.String"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "allowJs": false,
    "noImplicitAny": true,
    "allowSyntheticDefaultImports": true,
    "paths": {
       ...
    },
    "plugins": [
      {
        "name": "typescript-styled-plugin"
      }
    ]
  },
  "exclude": ["node_modules", "tmp", "dist"]
}
```
</details>

### Environment

 Node : 14.16.0
  OS   : win32 x64
  yarn : 2.4.2

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.1.1
  @nrwl/cypress : 12.1.1
  @nrwl/devkit : 12.1.1
  @nrwl/eslint-plugin-nx : 12.1.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.1.1
  @nrwl/linter : 12.1.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 12.1.1
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 12.1.1
  @nrwl/web : 12.1.1
  @nrwl/workspace : 12.1.1
  @nrwl/storybook : 12.1.1
  @nrwl/gatsby : Not Found
  typescript : 4.2.4 and 4.3.2

**Comment by puku0x** [comment]
It is intended if you don't use TypeScript's *Strict mode*.
As of v12.3, Nx generates applications and libraries with strict mode enabled by default.

You can enable it by adding `strict: true` to your `tsconfig.json`.
```js
// apps/**/tsconfig.json
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "jsx": "react-jsx",
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    // --
    // following options are added by `nx g @nrwl/react:application --strict`
    "forceConsistentCasingInFileNames": true,
    "strict": true,  // 👈 this
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true
    // --
  },
  "files": [],
  "include": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ]
}
```

**Comment by puku0x** [comment]
Another solution is to add `strict: true` to `tsconfig.base.json` which enables strict mode your entire workspace😉

**Comment by nemonemi** [comment]
Must be that I've missed it in the release notes.

Thanks a bunch, @puku0x !
