### ISSUE TITLE
Wrong path to tsconfig.base.json in all nrwl packages

### ISSUE THREAD

**Issue by mlc-mlapis** [nrwl/nx#5929]
## Current Behavior

Installing a default workspace with a single Angular application using `npx create-nx-workspace@latest` leads to the situation where the path for `"extends": "../../tsconfig.base.json"` in all `tsconfig.json` files contains a wrong value of `"../../tsconfig.base.json"` and it should be `"../../../tsconfig.base.json"` to get the root `tsconfig.base.json` file.

```
// tsconfig.json
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "types": ["node", "jest"]
  },
  "include": [],
  "files": [],
  "references": [
    {
      "path": "./tsconfig.lib.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/5693835/121241978-51eef400-c89c-11eb-9a9c-1e6c3dac9bcd.png)

## Expected Behavior
The correct path to the root `tsconfig.base.json` file.

**Comment by FrozenPandaz** [comment]
You are looking at the `tsconfig.json` files in `node_modules/@nrwl/workspace` :sweat_smile:.

1. Those aren't really supposed to be there.. we should remove them.
2. I don't think it really matters if they don't point to the right place. Is there a particular reason that you need these files? :thinking:

**Comment by mlc-mlapis** [comment]
@FrozenPandaz No, I don't need them. But VC Code is crying, that there are wrong paths, now. And it's also misleading anyway.

PS: It's the same in all @nrwl packages:
![image](https://user-images.githubusercontent.com/5693835/121655242-bed1dc00-ca9e-11eb-8253-049484d42d66.png)
