### ISSUE TITLE
Migration from 10.4.5 to 11.0.1 fails

### ISSUE THREAD

**Issue by ahilangopal** [nrwl/nx#5932]
I am trying to migrate from 10.4.5 to 11.0.1 and it failed. I am getting the below error.

`Running migration add-template-support-and-presets-to-eslint
Schematic "add-template-support-and-presets-to-eslint" not found in collection "@nrwl/angular".
C:\User\Git_Projects\WebApp\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: npx tao migrate --run-migrations=migrations.json
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
`

`{
  "migrations": [
    {
      "version": "11.0.0-beta.3",
      "description": "Update the decoration script when using Angular CLI",
      "factory": "./src/migrations/update-11-0-0/update-decorate-angular-cli",
      "package": "@nrwl/workspace",
      "name": "update-decorate-angular-cli"
    },
    {
      "version": "11.0.0-beta.3",
      "description": "Update the @types/node package",
      "factory": "./src/migrations/update-11-0-0/update-node-types",
      "package": "@nrwl/workspace",
      "name": "update-node-types"
    },
    {
      "version": "11.0.0-beta.3",
      "description": "Rename tools/schematics into tools/generators",
      "factory": "./src/migrations/update-11-0-0/rename-workspace-schematics",
      "package": "@nrwl/workspace",
      "name": "rename-workspace-schematics"
    },
    {
      "version": "11.0.0-beta.15",
      "description": "Adds `outputs` based on builders",
      "factory": "./src/migrations/update-11-0-0/add-outputs-in-workspace",
      "package": "@nrwl/workspace",
      "name": "add-outputs-in-workspace"
    },
    {
      "version": "10.5.0-beta.0",
      "description": "Update eslint config and builder to extend from new Nx Angular presets and lint templates",
      "factory": "./src/migrations/update-10-5-0/add-template-support-and-presets-to-eslint",
      "package": "@nrwl/angular",
      "name": "add-template-support-and-presets-to-eslint"
    },
    {
      "version": "11.0.0-beta.13",
      "description": "Update builder configurations and dependencies",
      "factory": "./src/migrations/update-11-0-0/update-builders-config",
      "package": "@nrwl/angular",
      "name": "update-11-0-0"
    },
    {
      "version": "11.0.0-beta",
      "description": "NavigationExtras omissions migration. In version 11, some unsupported properties were omitted from the `extras` parameter of the `Router.navigateByUrl` and `Router.createUrlTree` methods.",
      "factory": "./migrations/navigation-extras-omissions/index",
      "package": "@angular/core",
      "name": "migration-v11-navigation-extras-omissions"
    },
    {
      "version": "11.0.0-beta",
      "description": "The default value for `relativeLinkResolution` is changing from 'legacy' to 'corrected'.\nThis migration updates `RouterModule` configurations that use the default value to \nnow specifically use 'legacy' to prevent breakages when updating.",
      "factory": "./migrations/relative-link-resolution/index",
      "package": "@angular/core",
      "name": "migration-v11-router-relative-link-resolution-default"
    },
    {
      "version": "11.0.0-beta",
      "description": "In Angular version 11, the type of `AbstractControl.parent` can be `null` to reflect the runtime value more accurately. This migration automatically adds non-null assertions to existing accesses of the `parent` property on types like `FormControl`, `FormArray` and `FormGroup`.",
      "factory": "./migrations/abstract-control-parent/index",
      "package": "@angular/core",
      "name": "migration-v11-abstract-control-parent"
    },
    {
      "version": "11.0.0-beta",
      "description": "ViewEncapsulation.Native has been removed as of Angular version 11. This migration replaces any usages with ViewEncapsulation.ShadowDom.",
      "factory": "./migrations/native-view-encapsulation/index",
      "package": "@angular/core",
      "name": "migration-v11-native-view-encapsulation"
    },
    {
      "version": "11.0.0-beta",
      "description": "`async` to `waitForAsync` migration. The `async` testing function has been renamed to `waitForAsync` to avoid confusion with the native `async` keyword.",
      "factory": "./migrations/wait-for-async/index",
      "package": "@angular/core",
      "name": "migration-v11-wait-for-async"
    },
    {
      "version": "11.0.0-beta",
      "description": "NavigationExtras.preserveQueryParams has been removed as of Angular version 11.  This migration replaces any usages with the appropriate assignment of the queryParamsHandling key.",
      "factory": "./migrations/router-preserve-query-params/index",
      "package": "@angular/core",
      "name": "migration-v11-router-preserve-query-params"
    },
    {
      "version": "11.0.0-beta",
      "description": "Updates the `initialNavigation` property for `RouterModule.forRoot`.",
      "factory": "./migrations/initial-navigation/index",
      "package": "@angular/core",
      "name": "migration-v11-router-initial-navigation-options"
    }
  ]
}`

 NX  Report complete - copy this into the issue template

  Node : 14.16.1
  OS   : win32 x64
  npm  : 6.14.6

  nx : Not Found
  @nrwl/angular : 10.4.5
  @nrwl/cli : 11.0.1
  @nrwl/cypress : 11.0.1
  @nrwl/devkit : 11.0.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.1
  @nrwl/linter : 11.0.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.1
  @nrwl/web : 9.8.0
  @nrwl/workspace : 11.0.1
  typescript : 4.0.5

**Comment by FrozenPandaz** [comment]
It seems like you might have run `nx migrate --run-migrations=migrations.json` without first doing a `npm install`.

Also, could you update to the latest 10.x version first before updating to the latest 11.x version?

Here's an issue with other tips concerning migrations.
