### ISSUE TITLE
Updating node-sass to sass

### ISSUE THREAD

**Issue by njncalub** [nrwl/nx#5933]
## Current Behavior

I generated a new NextJS project using `@nrwl/next` and it added the `node-sass` in the `devDependencies`. But as of 2020-10-26, [libsass has already been deprecated](https://sass-lang.com/blog/libsass-is-deprecated).

After [searching through the codebase](https://github.com/nrwl/nx/search?q=%22node-sass%22), the Gatsby generator might also be affected.

There's #5049, but I think that's only related to `@nrwl/builders`.

## Expected Behavior

The [migration instructions](https://sass-lang.com/blog/libsass-is-deprecated#how-do-i-migrate) says to use the [sass](https://www.npmjs.com/package/sass) package.

So instead of `"node-sass": "5.0.0"`, it should be changed to `"sass": "1.34.1"`.

## Steps to Reproduce

```bash
$ yarn add @nrwl/next
$ yarn nx g @nrwl/next:application example
$ yarn why node-sass                     
yarn why v1.22.10
[1/4] Why do we have the module "node-sass"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "node-sass@5.0.0"
info Has been hoisted to "node-sass"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "6.26MB"
info Disk size with unique dependencies: "15.5MB"
info Disk size with transitive dependencies: "27.21MB"
info Number of shared dependencies: 122
Done in 1.00s.
```

### Environment

```bash
# yarn nx report
yarn run v1.22.10
$ nx report

>  NX  Report complete - copy this into the issue template

  Node : 15.0.1
  OS   : linux x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.3.6
  @nrwl/cypress : 12.3.6
  @nrwl/devkit : 12.3.6
  @nrwl/eslint-plugin-nx : 12.3.6
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.6
  @nrwl/linter : 12.3.6
  @nrwl/nest : Not Found
  @nrwl/next : 12.3.6
  @nrwl/node : Not Found
  @nrwl/react : 12.3.6
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.6
  @nrwl/web : 12.3.6
  @nrwl/workspace : 12.3.6
  @nrwl/storybook : 12.3.6
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

Done in 0.34s.
```

**Comment by xiongemi** [comment]
this is fixed in pr https://github.com/nrwl/nx/pull/7105
