### ISSUE TITLE
Cypress --env.grepTags="@legacy @test" isn't correctly parsed 

### ISSUE THREAD

**Issue by jogelin** [nrwl/nx#5934]
## Current Behavior
I would like to use the [cypress grep library](https://github.com/bahmutov/cypress-grep) to be able to select tests by tags.
```
npx nx run app-e2e:e2e:ci --env.grepTags="@legacy @smoke"
```

This command should run tests tagged with `@legacy` or `@smoke`

However, this does not work because the value received in Cypress is containing the quotes inside the string `""@legacy @smoke""`

And when this string is parsed by cypress grep, it returns something like:
```
[
  [ { tag: '"@legacy', invert: false } ],
  [ { tag: '@smoke"', invert: false } ]
]
```

When I log the list of options in nrwl, I also see a wrong value:
```
  cypressConfig: 'apps/app-e2e/cypress.json',
  tsConfig: 'apps/app-e2e/tsconfig.e2e.json',
  devServerTarget: 'app:serve:production',
  skipServe: true,
  watch: false,
  headless: true,
  env: { grepTags: '"@legacy @smoke"' },
  exit: true,
  record: false,
  parallel: false
```

This is working with only one tag:
```
npx nx run app-e2e:e2e:ci --env.grepTags="@legacy"
```

## Expected Behavior
The quotes used in the command should be removed from the value

### Environment
```
  Node : 14.15.1
  OS   : darwin x64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : 12.0.8
  @nrwl/cli : 12.0.8
  @nrwl/cypress : 12.0.8
  @nrwl/devkit : 12.0.8
  @nrwl/eslint-plugin-nx : 12.0.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.8
  @nrwl/linter : 12.0.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.0.8
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.8
  @nrwl/web : 12.0.8
  @nrwl/workspace : 12.0.8
  @nrwl/storybook : 12.0.8
  @nrwl/gatsby : Not Found
  typescript : 4.1.4
```

**Comment by AgentEnder** [comment]
Hey! Can you retry this with nx >= 12.3.4? I believe this has been fixed recently.

**Comment by jogelin** [comment]
@AgentEnder it works with nx 12.4.0 Thank You !
