### ISSUE TITLE
Use custom app name in plugin generated files (react/next generator)

### ISSUE THREAD

**Issue by writam-roy** [nrwl/nx#5936]
I have a situation where I am creating a custom Nx plugin which is similar to react/next app generator to an extent, but with little tweaks and changes in the generated files, I have a situation in one of the generated files where I would want to use user entered app name during "yarn nx generate" for certain customizations, I haven't found a reference of doing such a thing in any of the NX plugins, like suppose I want to add "writam-app" in the index.html generated,if I give the app name to be "writam app" during nx generate ,any help or suggestions of how to do such a thing would be greatly appreciated.
Note: I have found in file **create-application-files.ts** ,the value "options.appProjectRoot" indicates the user entered app name, not sure how to use that within my generators

**Comment by FrozenPandaz** [comment]
The generated files call a method from `@nrwl/devkit`.

You can learn more about writing generators here: https://nx.dev/latest/angular/generators/workspace-generators#creating-files-with-a-generator

The files use [EJS](https://ejs.co/) which is how you can use the template variables within the files.

I added more docs in the above PR.
