### ISSUE TITLE
`src\lib` folder structure is hard coded while creating lib/comp

### ISSUE THREAD

**Issue by a5hik** [nrwl/nx#594]
Creating a comp in lib always creates it under `src\lib` dir. 

I have migrated from v1 to 6, However I kept my lib code in `src` and added the required conf files.,
as I had felt ..just to have the `lib` in my src path as `src\lib` I need to refactor/move many files.

But when I issue `ng g c mycomp --project=mylib` I see the mycomp is generating a new `lib` dir in `src`. 

Issue 1: I should be able to have any folder structure for my lib
Issue 2: If we just maintain the `src` folder structure the files that we have to migrate is lesser compared to `src\lib`.

**Comment by FrozenPandaz** [comment]
That is a valid point. This might be more of an issue in the Angular CLI.

Please make an issue in https://github.com/angular/angular-cli/issues.

I believe you could use the path option (and set a default in your `angular.json` and that would help solve the issue.

Closing this as it's not an Nx issue. We don't modify the component schematics.
