### ISSUE TITLE
Adding a @nrwl/web app and serving it in a workpace with an angular 12 app fails

### ISSUE THREAD

**Issue by kirjai** [nrwl/nx#5943]
## Current Behavior

If a workspace already has an angular 12 app - then adding a new `@nrwl/web` app and serving it throws an error.

Interestingly, the order that the apps are added in seems to matter. creating a `@nrwl/web` app first, and then adding `@nrwl/angular` app later - doesn't have this problem. 

**Downgrading to `12.3.5` seems to solve the issue**

## Expected Behavior

Serving a web app in the mentioned context would not error.

## Steps to Reproduce

- [repro repo](https://github.com/kirjai/solid-meme).
- run `npx nx serve web-app`

### Failure Logs

```
% npx nx serve web-app

> nx run web-app:serve 
Starting type checking service...
Using 10 workers with 2048MB memory limit

>  NX  Web Development Server is listening at http://localhost:4200/
/myorg-wp-c/node_modules/webpack/lib/Dependency.js:311
                throw new Error(
                ^

Error: module property was removed from Dependency (use compilation.moduleGraph.updateModule(dependency, module) instead)
    at ProvidedDependency.set (/myorg-wp-c/node_modules/webpack/lib/Dependency.js:311:9)
    at iterationDependencies (/myorg-wp-c/node_modules/@nrwl/web/node_modules/webpack/lib/Compilation.js:940:21)
    at /myorg-wp-c/node_modules/@nrwl/web/node_modules/webpack/lib/Compilation.js:950:8
    at /myorg-wp-c/node_modules/@nrwl/web/node_modules/webpack/lib/NormalModuleFactory.js:409:6
    at /myorg-wp-c/node_modules/@nrwl/web/node_modules/webpack/lib/NormalModuleFactory.js:155:13
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/myorg-wp-c/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at /myorg-wp-c/node_modules/@nrwl/web/node_modules/webpack/lib/NormalModuleFactory.js:138:29
    at /myorg-wp-c/node_modules/@nrwl/web/node_modules/webpack/lib/NormalModuleFactory.js:346:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

———————————————————————————————————————————————
```

### Environment

```

  Node : 14.16.0
  OS   : darwin x64
  npm  : 6.14.11
  
  nx : Not Found
  @nrwl/angular : 12.3.6
  @nrwl/cli : 12.3.6
  @nrwl/cypress : 12.3.6
  @nrwl/devkit : 12.3.6
  @nrwl/eslint-plugin-nx : 12.3.6
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.6
  @nrwl/linter : 12.3.6
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.6
  @nrwl/web : 12.3.6
  @nrwl/workspace : 12.3.6
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by Jimmysh** [comment]
+1，  I think it's a webpack version issue, @angular-devkit/build-angular need webpack 5， @nrwl/web need 4. 

If set webpack to 4 in package.json,  `@nrwl/web` app can work

```js
  "resolutions": {
    "webpack": "^4.0.0"
  }
```

**Comment by Frikki** [comment]
I still get the error despite adding the webpack resolutions entry to _package.json_.

**Comment by looeee** [comment]
Add the `resolutions` field to my package.json and then running `yarn` to update the packages worked for me.

**Comment by jogelin** [comment]
I had the same issue and I just ran [the migration to webpack 5](https://nx.dev/latest/angular/web/migrate-to-webpack-5) by using:
```
nx g @nrwl/web:migrate-to-webpack-5
```

This is adding webpack 5 libraries into the `package.json`. However, I don't understand why these two libraries are added:
- `@pmmmwh/react-refresh-webpack-plugin`
- `react-refresh`

Any details?

**Comment by looeee** [comment]
> @pmmmwh/react-refresh-webpack-plugin
> react-refresh

These are used for hot module reloading in React. You made need to add `devServer.hot` = true in your config for it to work.
