### ISSUE TITLE
nx migrate causes Windows login to slow down 

### ISSUE THREAD

**Issue by luchsamapparat** [nrwl/nx#5947]
## Current Behavior

A few days ago Windows on my brand new machine suddenly needed minutes instead of seconds to login. Right after entering my credentials, the login process seemed to be stuck at the "Welcome" screen. I have noticed the same behavior several times before on my previous machine and at some point the problem always disappeared. But this time, it spoiled the fun of having a new laptop, so I started to investigate 🕵️‍♂️

Enabling [verbose status messages](https://tweaks.com/windows/39215/enable-detailed-logon-logoff-and-shutdown-status-messages/) revealed that it was actually the User Profile service that slowed down the login process: "Please wait for the User Profile Service."

Next, I did some [performance profiling using XPerf](https://superuser.com/a/1012442) to see what was going on during login. First, this confirmed that it was indeed the User Profile Service that was running amok:

![image](https://user-images.githubusercontent.com/875017/121420436-5e8f4d00-c96d-11eb-92e7-62bd55b5d22a.png)

Some more digging revealed that in addition to the high CPU usage, there was also a lot of file I/O activity caused by that same process (`svchost.exe (2184)`, the host process of the `profsvc.dll`):

![image](https://user-images.githubusercontent.com/875017/121421550-91861080-c96e-11eb-9401-e80e744925d8.png)

Most of that activity happened in directories named `tmp-{something}` in my user profile's temp directory.

There were 153 of these folders, containing 547,852 files amounting to 2.81 GB in total. All created between 13:00 and 14:00 on Saturday. Looking at the contents of those folders revealed that they somehow seemed to be related to npm packages and my development stuff:

![image](https://user-images.githubusercontent.com/875017/121421876-eaee3f80-c96e-11eb-97e5-823a8aaa3c2d.png)

![image](https://user-images.githubusercontent.com/875017/121421989-09543b00-c96f-11eb-8c62-4c2ba8c6b5b6.png)

So I deleted all these directories and sure enough, the login time was back to seconds. I solved the problem, now I wanted to know what caused the creation of all these files in the first place.

Thanks to [WakaTime](https://wakatime.com/) I could reconstruct that I was indeed working on a project around the time all those directories had been created:

![image](https://user-images.githubusercontent.com/875017/121422074-212bbf00-c96f-11eb-9a6c-8b280eedd86b.png)

Among the things I did on Saturday was an Angular update (10 to 11, then to 12) using `nx migrate`.

So I reverted to the Angular 10 commit of the project, ran `./node_modules/.bin/nx migrate latest` again and sure enough: new `tmp-{something}` directories were showing up while Nx was fetching various packages:

![image](https://user-images.githubusercontent.com/875017/121422963-0dcd2380-c970-11eb-8f58-c1f37f551451.png)

## Expected Behavior

First of all, the expected behavior of the Windows User Profile service is that it should not be slowed down by temp directory full of garbage. But I guess that's something for [microsoft/Windows-Dev-Performance](https://github.com/microsoft/Windows-Dev-Performance/issues) ;-)

In the meantime, it would be great if `nx migrate` could clean up after itself.

## Steps to Reproduce
1. buy an expensive, high-end Windows notebook
2. have an outdated Nx Workspace (e.g. `@nrwl/workspace@10`)
3. run `./node_modules/.bin/nx migrate latest`

### Environment

```

>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : 10.1.0
  @nrwl/cli : 10.4.4
  @nrwl/cypress : 10.1.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.1.0
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.4.4
  @nrwl/web : Not Found
  @nrwl/workspace : 10.4.4
  typescript : 3.9.7
```

**Comment by FrozenPandaz** [comment]
Wow, fascinating discovery! We expected the OS to responsibly clean those directories up but we can clean them up more rigorously.

**Comment by luchsamapparat** [comment]
Let me know if I can help by testing the fix
