### ISSUE TITLE
'Cannot read property 'toString' of null' after clean ng/cli and nrwl install generating workspace

### ISSUE THREAD

**Issue by lorenjerickson** [nrwl/nx#596]
Looking to set up a new workspace with nrwl schematics.  Following the introduction verbatim, even uninstalled ng/cli globally before starting.  I get the cli and schematics installed and get this error when generating a workspace.  

```
$ ng new myworkspacename --collection=@nrwl/schematics
Error: Cannot read property 'toString' of null
Cannot read property 'toString' of null

```

Seems pretty straightforward.  What am I missing?

Angular CLI: 1.7.4
Node: 8.9.4
OS: darwin x64

**Comment by FrozenPandaz** [comment]
Can you please try with the latest version of the Angular CLI?

Also providing a reproduction would help us help you.

**Comment by lorenjerickson** [comment]
Unfortunately, upgrading to the latest CLI (v6) is not an option for me at this time, due to all the breaking changes (those in ng 6 anyway).  I found that the script to create a workspace worked just fine, and that got me past this issue, but it's a little disconcerting that it doesn't work out of the box.  The reproduction is: install the CLI version noted, install the associated version of the nx schematics, and run the command given.  There's nothing special going on here.

**Comment by spidermon** [comment]
In our project this issue was reproducible with latest angular cli and nx. Cause of issue was @angular/pwa package or some of 14 derived dependencies. I didn't dig deep enough but workaround is to delete @angular/pwa. Angular CLI with nx working after that as expected.

**Comment by intuvision** [comment]
> In our project this issue was reproducible with latest angular cli and nx. Cause of issue was @angular/pwa package or some of 14 derived dependencies. I didn't dig deep enough but workaround is to delete @angular/pwa. Angular CLI with nx working after that as expected.

https://github.com/nrwl/nx/issues/1367#issuecomment-515069767
