### ISSUE TITLE
Read config.json file

### ISSUE THREAD

**Issue by MartynenkoA** [nrwl/nx#5975]
I`m trying to read file

this.http.get(jsonFile).toPromise().then((response : Config) => {
        this.config= response;
      }).catch((response: any) => {
        reject(`Could not load file '${jsonFile}': ${JSON.stringify(response)}`);
      });

 but got an error

**You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.**

On another project without nx everything works fine

**Comment by FrozenPandaz** [comment]
Sorry, I dont' think there's enough information here.

Where is the above code being used? Is it in an `Effects` file? Could you provide a repo to help us reproduce the issue please?
