### ISSUE TITLE
lib move deletes contents of eslint, index.ts

### ISSUE THREAD

**Issue by ed4becky** [nrwl/nx#5978]
## Current Behavior
I wanted to move a libraries from libs/mylib to libs/shared/mylib
I used nx g @nrwl/workspace:move --project mylib shared/mylib

1. the new .eslint file is now empty
2. the new tsconfig.spec.json is empty
3. the new index.ts is empty
4. test-setup.ts is empty
5. tsconfig.base.json was updated to change @myworkspace/mylib to @myworkspace/shared/mylib
6. users of @myworkspace/mylib were not updated to use @myworkspace/shared/mylib

## Expected Behavior

1. the new .eslint file reflects the original
2. the new tsconfig.spec.json reflects the original
3. the new index.ts reflects the original
4. test-setup.ts reflects the original
5. tsconfig.base.json was updated to change @myworkspace/mylib to @myworkspace/shared/mylib
6. users of @myworkspace/mylib are updated to use @myworkspace/shared/mylib

I only just started using @nrwl/workspace:move with angular 11

## Steps to Reproduce

create a library "mylib" under libs with "mysvc"
create an app "myapp" under apps
reference mysvc from myapp
compile successfully

nx g @nrwl/workspace:move --project mylib shared/mylib

### Environment

  Node : 14.17.0
  OS   : win32 x64
  npm  : 6.14.13

  nx : Not Found
  @nrwl/angular : 11.6.3
  @nrwl/cli : 11.6.3
  @nrwl/cypress : 11.6.3
  @nrwl/devkit : 11.6.3
  @nrwl/eslint-plugin-nx : 11.6.3
  @nrwl/express : Not Found
  @nrwl/jest : 11.6.3
  @nrwl/linter : 11.6.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.6.3
  @nrwl/web : Not Found
  @nrwl/workspace : 11.6.3
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.5

**Comment by meeroslav** [comment]
Hi @ed4becky, I tried to reproduce this first with latest version `v12.4.0` (I suggest you always use latest version whenever possible) and then with version you've specified `v11.6.3` but could not reproduce it.

Here is the link to my test repo: https://github.com/meeroslav/investigate-move-lib-5978
You can see the initial setup and result after running:
```bash
npm run nx generate @nrwl/workspace:move -- --project mylib shared/mylib
```

Next steps:
- Please update the project to see if this is still reproducible on the latest version
- When yes, then please send us the minimal repo where this happens so we can investigate further
