### ISSUE TITLE
ng update not working

### ISSUE THREAD

**Issue by Nxt3** [nrwl/nx#598]
Just upgraded `nrwl` from `6.0.4` to `6.1.0`. Went to run `ng update @nrwl/schematics` but it doesn't do anything. Was looking to add in the `affected` scripts. Am I doing something wrong?

**Comment by Yonet** [comment]
Please follow these steps:

- Install the new schematics and nx 
```
npm i @nrwl/schematics @nrwl/nx
npm run update
```

**Comment by Nxt3** [comment]
That yields the same result. Also, `npm run update` has been deprecated. You're supposed to use `ng update @nrwl/schematics` now.

**Comment by Nxt3** [comment]
@FrozenPandaz that was the issue. I didn't realize I couldn't upgrade manually via yarn. Thanks!
