### ISSUE TITLE
Is it possible to work with a project with its own node_modules folder inside it while solving problems of incompatibility with monorepo of a package?

### ISSUE THREAD

**Issue by Radecom** [nrwl/nx#5980]
Hello, first of all, congratulations on your outstanding work, thanks to it many of us have been interested in moving our projects to Monorepositories.

It is normal to find some difficulties during the conversion process; for example, some dependencies of your project are not developed to work in a multi-project workspace; for example, I was transforming a multi-repo project that I have, and I ran into this error:

`Error: Module not found: Error: Can't resolve '../../../../../capacitor.config.json'`

For that reason, I had to stop my migration temporarily, but the project must continue, hence my question.

**Is it possible to temporarily work with that project with its own node_modules folder inside, which fixes that problem?**

More than a yes or no answer, **is there a methodology to follow in such a situation?**

**Comment by vsavkin** [comment]
Yup, it's possible to have nested node modules. Nothing in Nx prevents you from having them. No particular methodology is required.

In the long run, we do recommend folks to adopt single-version policy cause of the benefits it provides. But nothing in Nx requires it.

I'm going to close this issue. The community slack is a better place to discuss different ways of adding Nx to existing projects.

Thank you!
