### ISSUE TITLE
Different version of webpack  with error message - Cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by sprabhus** [nrwl/nx#5984]
Followed the steps provided in the tutorial - https://nx.dev/latest/angular/examples/react-and-angular for creating the workspace containing angular and react.
## Current Behavior
Getting the runtime error - "Cannot read property 'tap' of undefined" while serving the react app

## Expected Behavior
I am able to serve angular app but not the react app due to given run time error.
Should able to serve both angular and react app

Issue is due to different version of the webpack needed by angular-devkit  and react
angular-devkit - webpack@5.38.1
React - 4.42.0

![image](https://user-images.githubusercontent.com/13001718/121746856-5fce9000-cabb-11eb-9b7f-44ac69b99a02.png)

## Steps to Reproduce
npx --ignore-existing create-nx-workspace happynrwl --preset=empty
yarn add @nrwl/angular
nx g @nrwl/angular:app angularapp
yarn add @nrwl/react
nx g @nrwl/react:app reactapp
nx serve reactapp

**Comment by andrewgrewell** [comment]
This is a pretty big issue that is affecting running storybook as well. Any update or workarounds?

**Comment by Bulletninja** [comment]
I also have this issue, and i think is the same as https://github.com/nrwl/nx/issues/5907
