### ISSUE TITLE
Update Storybook templates to 6.x pattern

### ISSUE THREAD

**Issue by Brian-McBride** [nrwl/nx#5992]
## Description
The current generated templates for Storybook match the 5x syntax but are not proper for Storybook 6. They work because of backward compatibility, but the Controls and other items don't work as expected. 

## Motivation
I'm making the request because I'm constantly writing my own stories and skipping the generator. Not horrible, but it sure would be nice to have the template auto-generated. I have not built a migration otherwise I'd try and get a PR open soon, however it will be a couple of weeks at best before I have time to dig into that. Speaking of, there is a distant lack of good tutorials on building migrations for Nx. 

### New packages
```
@storybook/addon-essentials
@storybook/addon-controls
```

### Remove packages
```
@storybook/addon-knobs
```

### <root>/storybook/main.js
The top-level `main.js` needs to be changed to the following:
```javascript
module.exports = {
  stories: [],
  addons: [
    {
      name: '@storybook/addon-essentials',
      addons: ['@storybook/addon-controls''],
      options: {
        backgrounds: true,
      },
    },
  ],
  // Added to fix the bug:  https://github.com/styleguidist/react-docgen-typescript/issues/356
  typescript: {
    reactDocgen: 'react-docgen',
  },
};
```

### Individual story format
```typescript
import React from 'react';
import { Story, Meta } from '@storybook/react/types-6-0';
import { MyComponent, MyComponentProps } from './MyComponent';

export default {
  component: MyComponent,
  title: 'MyComponent',
} as Meta;

const Template: Story<MyComponentProps> = (args) => (
  <MyComponent {...args} />
);

export const Primary = Template.bind({});
```

## Final thoughts
Maybe there just needs to be 5x and a 6x generator option in the story template?

**Comment by JSMike** [comment]
FYI, Storybook 6.3.0 completely removes support for knobs, so this will become a bigger issue as soon as 6.3.0 gets fully released (currently in RC)

**Comment by manuelmeister** [comment]
As now [Storybook v6.3](https://github.com/storybookjs/storybook/releases/tag/v6.3.0) is released, I think this would be an important step. How can I help with this?

**Comment by Brian-McBride** [comment]
It looks like 2.5.0 is properly generating stories now.
