### ISSUE TITLE
Can libs reference scripts?

### ISSUE THREAD

**Issue by Nxt3** [nrwl/nx#600]

**Comment by thelgevold** [comment]
Hi. Can you please include more details about what you are trying to do?

**Comment by thelgevold** [comment]
Closing as this is a duplicate of https://github.com/nrwl/nx/issues/601

**Comment by Nxt3** [comment]
In Angular 5, you could do this in `.angular-cli.json`:

```
    {
      "name": "logger-lib",
      "root": "libs/logger-lib/src",
      "test": "../../../test.ts",
      "scripts": ["../../../node_modules/js-logger/src/logger.min.js"],
      "tsconfig": "tsconfig.app.json",
      "tags": []
    }
```

but there doesn't seem to be an equivalent now--unless I'm missing something.
