### ISSUE TITLE
Ng CLI adaptation for migrations breaks the function externalSchematic

### ISSUE THREAD

**Issue by mmuenker** [nrwl/nx#6004]
The ng cli adaptation for the class `NodeModulesEngineHost` should not change the behavior of `_resolveCollectionPath` if called from a migration schematic.

## Current Behavior

If a migration schematic calls the function `externalSchematic('ngx-my-lib', 'config')`. The method [`_resolveCollectionPath`](https://github.com/nrwl/nx/blob/master/packages/tao/src/commands/ngcli-adapter.ts#L556-L603) tries to load the `migration.json` for the package `ngx-my-lib`

## Expected Behavior

If the function `externalSchematic` is called the method [`_resolveCollectionPath`](https://github.com/nrwl/nx/blob/master/packages/tao/src/commands/ngcli-adapter.ts#L556-L603) should load the `collection.json` for the package `ngx-my-lib`.

## Steps to Reproduce

1. create a migration schematic for a package
2. call the `externalSchematic` function to execute an external schematic for packages that does not have a `mirgation.json`
3. execute the created migration schematic with `nx migrate --run-migrations`

### Failure Logs

```
Could not find migrations in package: "ngx-my-lib"
```

### Environment

```
Node : 14.16.1
OS   : linux x64
yarn : 1.22.10

nx : Not Found
@nrwl/angular : 12.3.6
@nrwl/cli : 12.3.6
@nrwl/cypress : 12.3.6
@nrwl/devkit : 12.3.6
@nrwl/eslint-plugin-nx : 12.3.6
@nrwl/express : Not Found
@nrwl/jest : 12.3.6
@nrwl/linter : 12.3.6
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : 12.3.6
@nrwl/react : Not Found
@nrwl/schematics : Not Found
@nrwl/tao : 12.3.6
@nrwl/web : Not Found
@nrwl/workspace : 12.3.6
@nrwl/storybook : 12.3.6
@nrwl/gatsby : Not Found
typescript : 4.2.4
```

**Comment by mmuenker** [comment]
A possible solution would be to check the optional parameter `requester` for the `_resolveCollectionPath` method.

If the parameter `requester` is defined. Check if the request package has a `collection.json` or throw an error.

I am not familiar enough with how nx migration works to know if this is a good solution or would break something. 

```typescript
const packageJson = require(packageJsonPath);
let pkgJsonSchematics;
if (requester) {
  pkgJsonSchematics = packageJson[ 'schematics' ];
  if (!pkgJsonSchematics) {
    throw new Error(`Could not find collection in package: "${name}"`);
  }
} else {
  pkgJsonSchematics = packageJson[ 'nx-migrations' ];
  if (!pkgJsonSchematics) {
    pkgJsonSchematics = packageJson[ 'ng-update' ];
    if (!pkgJsonSchematics) {
      throw new Error(`Could not find migrations in package: "${name}"`);
    }
  }
  if (typeof pkgJsonSchematics != 'string') {
    pkgJsonSchematics = pkgJsonSchematics.migrations;
  }
}
collectionPath = resolve(dirname(packageJsonPath), pkgJsonSchematics);
```

**Comment by FrozenPandaz** [comment]
Thank you for the debugging! Sorry but I'm not sure that I fully understand the issue. Could you provide a repo  that reproduces the issue please?

**Comment by mmuenker** [comment]
I have created a demo repo: https://github.com/mmuenker/nrwl-bug-6004

---

1. Run the setup script: `yarn setup`
2. Check if the schematic `@nrwl-bug-6004/without-migration-json:demo` is working: `yarn test:demo-schematic`
3. Run nx migrations with `nx migrate --run-migrations`

**Comment by mmuenker** [comment]
@FrozenPandaz is it possible to reproduces this issue?
