### ISSUE TITLE
installations of npm packages is run everytime I try nx g library with directory multi folders deep

### ISSUE THREAD

**Issue by webmandman** [nrwl/nx#6033]
## Current Behavior

When I run this command:

`nx g library mystock --directory=data/stock`

It takes 1 minute for NPM packages to install, and everytime I run this command it always goes through installing packages. It does indeed successfully create the project and in the intended data/stock/mystock folder. 

## Expected Behavior

I expect NPM packages to be installed once and cached. This generator command should be blazing fast not 1 minute slow. 

IF I run the same command but the directory is only 1 folder deep, then it does not go through installing NPM packages. 

## Environment
Windows 10
nx --version 12.0.8
npm -v 6.14.8
Using both nx.json and angular.json (defaultCollection: @nrwl/angular)

**Comment by AgentEnder** [comment]
Which generator collection are you using? (if just using `nx g lib`, check defaultCollection in workspace/angular.json)

**Comment by webmandman** [comment]
Here is what I have in my workspace/angular.json cli.defaultCollection: "@nrwl/angular"

**Comment by FrozenPandaz** [comment]
Good news :tada: 

This is actually for Angular _libraries_ fixed with version `12.4.0`! Please try with the latest version.

Angular applications will be fixed soon as well.

**Comment by webmandman** [comment]
I'm unsure if it is ok to only update the @nrwl packages from 12.0.8 to 12.4.0 or if I really need to go through `nx migrate`. This would be my first time doing any update on this workspace.

**Comment by FrozenPandaz** [comment]
No worries.

I tried it on https://github.com/nrwl/nx-examples

`nx g @nrwl/angular:library mylib` does re-install node_modules anymore :tada: 

Closing this issue as I can confirm it has been fixed.

**Comment by webmandman** [comment]
do I just updated @nrwl packages from 12.0.8 to 12.4.0? or do nx migrate?

**Comment by AgentEnder** [comment]
I would recommend using `nx migrate latest` to get up to 12.4, it should go pretty smoothly.
