### ISSUE TITLE
Update gatsby to version 3

### ISSUE THREAD

**Issue by Himadu2000** [nrwl/nx#6040]
## Description
Please update to gatsby v3.

## Motivation
Bug prone and for new features.

## Suggested Implementation
I imagine this will install gatsby latest version and not v2.
Should change the gatsby package.json version, run tests and fix bugs.
As with the new version their should be breaking changes.

## Alternate Implementations
I have no other imaginations.

**Comment by FrozenPandaz** [comment]
Hi, which version of Nx are you using?

Gatsby was updated to v3 in version `12.0.0`.

The latest version of Nx at this time uses gatsby `3.5.0`. There is an [open PR](https://github.com/nrwl/nx/pull/5948) to update the version of gatsby to `3.7.0`.

**Comment by Himadu2000** [comment]
@FrozenPandaz Thanks for info, we'll close issue once it merged then.

**Comment by Himadu2000** [comment]
@FrozenPandaz so, is the pr merged?

**Comment by Himadu2000** [comment]
Still no update?
