### ISSUE TITLE
affected:build with broken publishable library doesn't finish process with failed exit code

### ISSUE THREAD

**Issue by Poccomaxazt** [nrwl/nx#6067]
## Current Behavior
We are using Angular with multiple applications (let's say fe microservices). Some time ago migrated build process to your incremental builds.
When I launch current command
**nx affected:build --prod --with-deps --buildOptimizer=false --optimization=false --base=origin/qa --head=HEAD**
build starts to work with correct graph ordering (libraries first)
_Running target build for 42 project(s):_

In situation when some library has an error (example)
_Building entry point '@name/interfaces'
ERROR: libs/interfaces/src/address-model.ts:1:14 - error TS2322: Type 'number' is not assignable to type 'string'._

Build continue to work with other libraries in the parallel, then stops and doesn't exit with exit code. So CI can't see that build is failed.

## Expected Behavior
When some library from the publishable libs has an Error **affected:build** command should finish process with **exit code 1** (so CI build can be marked as Failed)

### Environment
I was receiving such behavior with different libraries combinations (also different OS). Previous versions as well. Now updated everything to latest versions and still situation is the same.

Library uses **"builder": "@nrwl/angular:ng-packagr-lite",**

 Node : 14.15.5
  OS   : win32 x64
  yarn : 1.22.5

  nx : Not Found
  @nrwl/angular : 12.4.0
  @nrwl/cli : 12.4.0
  @nrwl/cypress : 12.4.0
  @nrwl/devkit : 12.4.0
  @nrwl/eslint-plugin-nx : 12.4.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.4.0
  @nrwl/linter : 12.4.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.4.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.4.0
  @nrwl/storybook : 12.4.0
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by SnakeSVx** [comment]
We have a simular issue. When buildable libs won't build, for example because of a circular dependency or a compile error the build just stops without any error code. 

This seems to happen with both the "affected" command as with the "run-many" command. 

Doing a regular nx build command works as it should.

**Comment by SnakeSVx** [comment]
Seems fixed in version 12.5.0.

But next to this version upgrade I had to fix some npm issues as well. Npm had installed an older version of nx with the previous upgrade to 12.4.0. (seems like this was an issue with the --legacy-peer-deps command from npm).

**Comment by Poccomaxazt** [comment]
Looks like 12.5.0 fixes this issue - I can see message about NX Error build, but now I'm receiving another problem. It doesn't build apps / libs in a proper order. nx affected --with-deps starts to build apps without previous processes for libraries. As a result - of course - we can see that dependencies are missing.

**Comment by imdadul** [comment]
> It doesn't build apps / libs in a proper order

I am also having similar problem.
When specifying in nx  files the the dependencies are being built in order

```
targetDependencies": {
    "build": [
      {
        "target": "build",
        "projects": "dependencies"
      }
    ]
  },
```

But whenever I am building with `--with-deps `the order is wrong & it tries to build libs first without building its deps, therefore build failure.

**Comment by FrozenPandaz** [comment]
It's unintended that the order that projects run with `--with-deps` is incorrect.
 
Could somebody please provide an example that exhibits this issue to make it easier to replicate?

Using `targetDependencies` is the better way to ensure that tasks happen in order though.

**Comment by Poccomaxazt** [comment]
In my case angular.json file **doesn't** contain
```
          "dependsOn": [{
            "target": "build",
            "projects": "dependencies"
          }]
```
for my projects.

So when I use **--with-deps** flag from the console - it just starts to build apps (without first build for libraries), and that's my issue.
To fix it locally I added section to angular.json - I can build apps - it starts to build libs and then apps.
