### ISSUE TITLE
Angular.json no longer grouped by project type?

### ISSUE THREAD

**Issue by Nxt3** [nrwl/nx#607]
Prior to `@nrwl 6.0`, when generating an app or library--the `.angular.cli.json` file would have the project types grouped together by type then alphabetically.

Now it just puts the most recently generated project at the bottom of the file. Is this intended? I'd prefer keeping stuff grouped/sorted to it's easier to find stuff.

**Comment by markcdev** [comment]
I don't seem to be able to add a lib with the same name as an app anymore...not sure if it's related to this

**Comment by mehrad-rafigh** [comment]
@markcdev Nope thats not related to the problem described above. You should not be able to create an app and a lib with the same name!

**Comment by vsavkin** [comment]
Folks. I'm going to close this issue because it is stale. Please reopen it the problem is still present.
