### ISSUE TITLE
"@angular-eslint/template/eqeqeq":"off" in app .eslint.rc not applied

### ISSUE THREAD

**Issue by gubo** [nrwl/nx#6074]
## Current Behavior
cannot turn rule off:
"@angular-eslint/template/eqeqeq":"off" 
does not get applied when set this rule in the app .eslintrc.json

## Expected Behavior
should override angular lint rule

## Steps to Reproduce
PR:
https://github.com/nrwl/nx-examples/pull/153

nx run eqeqeq:lint

## Failure Logs

Linting "eqeqeq"...

/uscsf/_misc/nx-examples/apps/eqeqeq/src/app/app.component.html
  1:13  error  Expected `===` but received `==`  @angular-eslint/template/eqeqeq

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

Lint errors found in the listed files.

### Environment

  Node : 14.8.0
  OS   : darwin x64
  yarn : 1.22.5
  
  nx : Not Found
  @nrwl/angular : 12.4.0-beta.2
  @nrwl/cli : 12.4.0-beta.2
  @nrwl/cypress : 12.4.0-beta.2
  @nrwl/devkit : 12.4.0-beta.2
  @nrwl/eslint-plugin-nx : 12.4.0-beta.2
  @nrwl/express : Not Found
  @nrwl/jest : 12.4.0-beta.2
  @nrwl/linter : 12.4.0-beta.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 12.4.0-beta.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.4.0-beta.2
  @nrwl/web : 12.4.0-beta.2
  @nrwl/workspace : 12.4.0-beta.2
  @nrwl/storybook : 12.4.0-beta.2
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by puku0x** [comment]
@gubo Please refer https://github.com/nrwl/nx-examples/pull/153#discussion_r654857790 and you can close this issue.

**Comment by FrozenPandaz** [comment]
Looks like this is resolved now.

Thank you all!
