### ISSUE TITLE
apps created with broken nx logo

### ISSUE THREAD

**Issue by guiseek** [nrwl/nx#6076]
the URL of the NX logo in the header of the generated apps is broken, probably something related to switching to nextjs

![Nx logo](https://nx.dev/assets/images/nx-logo-white.svg)

## Current Behavior
I used the app generator using @nrwl/web and saw the broken logo, consulted the URL and it directs to the site

## Expected Behavior
it doesn't make much difference to whoever generates the project, as the overwhelming majority will not remain. but I thought I'd better let them know

## Steps to Reproduce

`nx g @nrwl/web:app webapp`

**Comment by FrozenPandaz** [comment]
@bcabanes I think we missed the `web` apps when we inlined SVGs into the template.

**Comment by bcabanes** [comment]
Thanks for the ping, I'll take a look!
