### ISSUE TITLE
Nx cache hash calculation ignores the implicitDependencies configuration in nx.json

### ISSUE THREAD

**Issue by peterreisz** [nrwl/nx#6078]
## Current Behavior

In `nx.json` there is a part where you can define only the `dependencies` matters from the `package.json` the rest of the file doesn't:

```json
  "implicitDependencies": {
    "package.json": {
      "dependencies": "*",
      "devDependencies": "*"
    },
  }
```

nx ignores this, rendering the cache useless in case of I want create a release via bumping the version in the `package.json`.
The whole `package.json` file is calculated in the hash, resulting an unnecessarily full build of the project.

## Expected Behavior

nx should respect the `implicitDependencies` and bumping the version should not affect caching.

## Steps to Reproduce

Create an empty project with at least a buildable lib:

```
npx create-nx-workspace foo --preset=empty --interactive=false --nx-cloud=false
cd foo
npx nx generate @nrwl/workspace:library --name=bar --buildable --no-interactive
npx nx run bar:build
```

Try the build again, it will come from the cache, but when you change the version in `package.json` it will do a rebuild.

This bug effects the latest 12.4.0 version too.

## Ugly quick fix via patch-package

Just to give you an idea. This patch only works for the top level of every defined `implicitDependencies`.

```patch
diff --git a/node_modules/@nrwl/workspace/src/core/hasher/hasher.js b/node_modules/@nrwl/workspace/src/core/hasher/hasher.js
index 61fa2cf..1af2f32 100644
--- a/node_modules/@nrwl/workspace/src/core/hasher/hasher.js
+++ b/node_modules/@nrwl/workspace/src/core/hasher/hasher.js
@@ -146,9 +146,20 @@ class Hasher {
                     '.gitignore',
                     '.nxignore',
                 ];
+                for (const [name, filter] of Object.entries(this.nxJson.implicitDependencies || {})) {
+                    if ('*' !== filter) {
+                        delete this.fileHasher.fileHashes[name];
+                    }
+                }
+                const transformFile = (file, text) => {
+                    const filter = this.nxJson.implicitDependencies[file];
+                    const keysToKeep = Object.keys(filter);
+                    const filteredObj = Object.entries(JSON.parse(text)).filter(([k,v]) => keysToKeep.includes(k));
+                    return JSON.stringify(Object.fromEntries(filteredObj), undefined, 2);
+                }
                 const fileHashes = [
                     ...fileNames.map((file) => {
-                        const hash = this.fileHasher.hashFile(file);
+                        const hash = this.fileHasher.hashFile(file, text => transformFile(file, text));
                         return { file, hash };
                     }),
                     ...this.hashGlobalConfig(),

```

**Comment by statop** [comment]
The hasher ignores implicitDependencies array values too. Any key in implicitDependencies basically applies to all projects. For example, I would expect this to cause changes to anything in some/dir to only affect some-project -
```
    "some/dir/**": [
      "some-project"
    ],
```

but it makes it so changes in some/dir cause _all_ projects to rebuild.

**Comment by ydmitry** [comment]
The same issue...
Btw, had to add **/*.html as implicitDependencies for Angular app because it was ignored by cache hashing

**Comment by ydmitry** [comment]
Any updates for this bug?

**Comment by cyrixmorten** [comment]
I am seeing that with: 

```
  "implicitDependencies": {
    "libs/lib-a/project.json": {
      "tags": "*"
    },
    "libs/**/project.json": {
      "tags": "*"
    }
```

Updating a tag in `lib-a` will cause affected to build everything as expected, however updating a tag in any other lib (captured by the glob pattern), will only trigger build for affected. 

Would expect updating the tag in any `project.json` to cause a rebuild of everything - especially as that is the behaviour when writing out the path without globs.

**Comment by konstantinschuette** [comment]
Maybe someone can take a look at this. NX Cloud saves us a ton of computation time, but its not useable for us, without this problem solved.
