### ISSUE TITLE
Can't generate simple TS library

### ISSUE THREAD

**Issue by its-galitch** [nrwl/nx#608]
In previous versions were implemented CLI command `ng generate lib <lib-name> --nomodule`. And in the new version ("@nrwl/schematics": "6.1.0") according to `ng g lib --help`  **`--publishable `**  should _Generate a simple TS library when set to true_. But when I implement this command I got the same structure as by creating regular angular lib with ng-module inside.

If it is the right behaveour, how can I generate simple ts library. And if it is not, how it could be fixed?

**Comment by FrozenPandaz** [comment]
There should be an option to exclude generation of the module.

**Comment by ThomasBurleson** [comment]
@FrozenPandaz - 

Using `ng g @schematics/angular:lib -h` we see

```console
usage: ng generate @schematics/angular:lib <name> [options]
options:
  --dry-run (-d)
    Run through without making any changes.
  --entry-file 
    The path to create the library's public API file.
  --force (-f)
    Forces overwriting of files.
  --prefix (-p)
    The prefix to apply to generated selectors.
  --skip-package-json 
    Do not add dependencies to package.json.
  --skip-ts-config 
    Do not update tsconfig.json for development experience.
```
So the option to not generate the ngModule is no longer available in the latest schematic.
I think the `@nrwl/schematic` **lib** schematic should be fixed to support this and delete the ngModule.

@see  [schematics/src/collection/library/index.ts](https://github.com/nrwl/nx/blob/master/packages/schematics/src/collection/library/index.ts#L418-L430)

**Comment by FrozenPandaz** [comment]
Added with https://github.com/nrwl/nx/pull/799 😄

`ng g lib simple-lib --no-module` generates a lib with no module 👍
