### ISSUE TITLE
@nrwl/web:file-server does not work without own certificate

### ISSUE THREAD

**Issue by RobinVdBroeck** [nrwl/nx#6081]
## Current Behavior
When you use `nx serve --ssl=true`, so without a cert and key, with a target that has @nrwl/web:file-server as his builder, you get a `Error: Could not find certificate cert.pem`. However, `@angular-devkit/build-angular:dev-server`, does support that. (It generates one for you I think)

## Expected Behavior
Should not error and serve an https app.

## Steps to Reproduce
See:   https://github.com/nrwl/nx-examples/pull/154
Run `nx serve2 products --ssl` (vs `nx serve products --ssl`)

### Failure Logs
Error: Could not find certificate cert.pem

### Environment

```
  Node : 16.3.0
  OS   : linux x64
  npm  : 6.14.13

  nx : Not Found
  @nrwl/angular : 12.0.8
  @nrwl/cli : 12.0.8
  @nrwl/cypress : 12.0.8
  @nrwl/devkit : 12.0.8
  @nrwl/eslint-plugin-nx : 12.0.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.8
  @nrwl/linter : 12.0.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.8
  @nrwl/web : 12.0.8
  @nrwl/workspace : 12.0.8
  @nrwl/storybook : 12.0.8
  @nrwl/gatsby : Not Found
  typescript : 4.1.4
```

**Comment by s-bauer** [comment]
This is still an issue which should be solved!
