### ISSUE TITLE
NX Console generates React vs Next componets in different places (under libs)

### ISSUE THREAD

**Issue by iangregsondev** [nrwl/nx#6084]
## Current Behavior
Using NX Console (vscode) to create a React Component vs a Next component puts them in different directories, why ?

Which is considered correct ?

And what is the difference between a react component and a nextjs component as I am not seeing any real difference.

Here is what I am talking about

![image](https://user-images.githubusercontent.com/2370364/122776093-11837300-d2ab-11eb-9bea-3339296f2c64.png)

Can you confirm why these are different, I classed it under a bug as I don't think its consistent.

In fact, it was confusing me :-)

**Comment by sairaj2119** [comment]
Yup I too noticed this today

**Comment by iangregsondev** [comment]
> Yup I too noticed this today

Yep - its very confusing. I think I will just go with the location of the react component under "libs" and not "components". 

The generator doesn't really make a difference in the boilerplate it creates. I mean a Nextjs component creates a react component.

I am unsure why it was even created considering nextjs depends on react.

Maybe I am missing something ?

Would be nice to get some input from NRWL about the direction they had for it.
