### ISSUE TITLE
Libraries overwrites configuration in the workspace

### ISSUE THREAD

**Issue by rrdlpl** [nrwl/nx#6085]
## Current Behavior
Creating a library with the same name as a project overwrites the configuration of the application in the `workspace.json`

## Expected Behavior
Names of the application and library can be the same. No duplicates within libraries or applications are fine.

## Steps to Reproduce
Create a new application.
`yarn nx g @nrwl/nest:application test`
Create a new library
`yarn nx g @nrwl/nest:lib test`

The configuration for the application in the `worskpace.json` file is overwritten by the library.

### Environment
```
 "@nrwl/cli": "10.4.15",
    "@nrwl/cypress": "11.6.3",
    "@nrwl/eslint-plugin-nx": "11.6.3",
    "@nrwl/linter": "11.6.3",
    "@nrwl/workspace": "11.6.3",
```
macBig OS Sur 11.2.3
node v12.0.0

**Comment by FrozenPandaz** [comment]
It is not possible to have an application with the same name as a library because it would then become ambiguous what to run when running `nx test not-unique-name` but it should throw an error when generating a project with the same name.

**Comment by rrdlpl** [comment]
@FrozenPandaz Well, It didn't throw any error for me
