### ISSUE TITLE
Creating a new workspace does not create in subdirectory

### ISSUE THREAD

**Issue by amiller29au** [nrwl/nx#609]
When running command:

`ng new myworkspacename --collection=@nrwl/schematics`

It creates the workspace in the current directory not the subdirectory which is behaviour when using both angular cli "ng new myworkspacename" or "create-nx-workspace myworkspacename"

**Comment by juristr** [comment]
Experienced the same issue.

**Comment by FrozenPandaz** [comment]
This is a duplicate of #549. There is a fix for it in CLI 6.1.0-rc.0 https://github.com/nrwl/nx/issues/549#issuecomment-397754337
