### ISSUE TITLE
Start serving applications while lazy loaded libraries are still building

### ISSUE THREAD

**Issue by RobinVdBroeck** [nrwl/nx#6091]
## Description
Nx could start serving some routes while the application is still being build. 
(This only makes sense with incremental builds using buildable libraries)

## Motivation
Faster startup times. No need to wait for libraries to be build that are lazy loaded, if we actually never need them.

## Suggested Implementation
If the browsers request a library that is still being build, the browser should wait until the library is done building.

## Alternate Implementations
We could also build JIT (when you request the actual javascript files, like Vite does)

**Comment by FrozenPandaz** [comment]
Thank you! :smile: 

This is interesting and we can look into implementing this.
