### ISSUE TITLE
Misconfiguration in workspace package: collection.json

### ISSUE THREAD

**Issue by piet-v** [nrwl/nx#6094]
The workspace collection.json has a misconfiguration.

The remove command references the move factory instead of the remove factory.

This bug seems to break calling the generator through code.

(calling the generator through CLI works)

https://github.com/nrwl/nx/blob/122f7eca72e5a1a29f74db38ef1bdedbfb8016c4/packages/workspace/collection.json#L34

**Comment by AgentEnder** [comment]
@piet-v The workspace collection should not cause this to break when calling the generator through code as the collection.json is not read since you can just import the generator. Can I see how you are trying to call the generator?

**Comment by piet-v** [comment]
@AgentEnder 

Here's a generator which will trigger the error

```
import { externalSchematic } from '@angular-devkit/schematics';

export default function () {
  return externalSchematic('@nrwl/workspace', 'remove', {
    projectName: 'foo',
  });
}
```

`Error: Schematic "remove" cannot resolve the factory. at NodeModulesEngineHost.createSchematicDescription`

**Comment by AgentEnder** [comment]
Ah! Yeah, calling it that way _should_ be valid, but would have been broken with this misconfiguration. For future reference though, for any nx style generator you do not have to use externalSchematic to call them. Changing this one over to the nx-devkit style as an example would look like this:

```typescript
import { removeGenerator } from '@nrwl/workspace';

export default function (host: Tree) {
  return removeGenerator(host, {
    projectName: 'foo',
  });
}
```
