### ISSUE TITLE
Unable to create a new work space

### ISSUE THREAD

**Issue by pr447e** [nrwl/nx#6100]
## Current Behavior

npx create-nx-workspace
(node:44349) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
npx: installed 48 in 10.44s
✔ Workspace name (e.g., org name)     · ATTT
✔ What to create in the new workspace · next
✔ Application name                    · MYSSR
✔ Default stylesheet format           · styled-jsx
✔ Use Nx Cloud? (It's free and doesn't require registration.) · No

>  NX  Nx is creating your workspace.

  To make sure the command works reliably in all environments, and that the preset is applied correctly,
  Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✖ Creating your workspace

>  NX   ERROR  Nx failed to create a workspace.

  Exit code: 1
  Log file: /var/folders/hx/1jg3l7j12v343mdq0b0gkvrm0000gp/T/tmp-44347-aKGzvFIAmefk/error.log

## Expected Behavior

A new workspace needs to be created. I have checked the log file and I am facing the below issue.

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs
cypress@7.5.0 postinstall /Users/pr447e/attt/node_modules/cypress
> node index.js --exec install

Installing Cypress (version: 7.5.0)

[STARTED] Task without title.
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/7.5.0?platform=darwin&arch=x64
Error: read ETIMEDOUT

----------

**Comment by yharaskrik** [comment]
Same here except my error is (I chose angular-nest):

```
InvalidInputOptions [Error]: Schematic input does not validate against the Schema: {"name":"client","inlineStyle":false,"inlineTemplate":false,"prefix":"12-4-0-jest-test","skipTests":false,"style":"scss","routing":false,"skipInstall":true,"skipPackageJson":false}
Errors:

  Data path "/prefix" must match format "html-selector".
    at MapSubscriber.project (/12-4-0-jest-test/node_modules/@angular-devkit/schematics/tools/schema-option-transform.js:30:27)
    at MapSubscriber._next (/12-4-0-jest-test/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next /12-4-0-jest-test/node_modules/rxjs/internal/Subscriber.js:66:18)
    at ThrowIfEmptySubscriber._next (/12-4-0-jest-test/node_modules/rxjs/internal/operators/throwIfEmpty.js:44:26)
    at ThrowIfEmptySubscriber.Subscriber.next (/12-4-0-jest-test/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeSubscriber._next (/12-4-0-jest-test/node_modules/rxjs/internal/operators/take.js:54:30)
    at TakeSubscriber.Subscriber.next (/12-4-0-jest-test/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/12-4-0-jest-test/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
    at SimpleInnerSubscriber._next (/12-4-0-jest-test/node_modules/rxjs/internal/innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (/12-4-0-jest-test/node_modules/rxjs/internal/Subscriber.js:66:18) {
  errors: [
    {
      instancePath: '/prefix',
      schemaPath: '#/properties/prefix/format',
      keyword: 'format',
      params: [Object],
      message: 'must match format "html-selector"'
    }
  ]
}

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.



gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/jaybell/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/jaybell/.nvm/versions/node/v12.20.1/bin/node" "/Users/jaybell/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /12-4-0-jest-test/node_modules/watchpack-chokidar2/node_modules/fsevents
gyp ERR! node -v v12.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @nrwl/cypress@12.4.0 requires a peer of cypress@>= 3 < 8 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.

Schematic input does not validate against the Schema: {"name":"client","inlineStyle":false,"inlineTemplate":false,"prefix":"12-4-0-jest-test","skipTests":false,"style":"scss","routing":false,"skipInstall":true,"skipPackageJson":false}
Errors:

  Data path "/prefix" must match format "html-selector".
Workspace creation failed, see above.
```

**Comment by FrozenPandaz** [comment]
@pr447e

I think creating an `Empty` workspace will work for you because it does not install cypress. Though when you create a new application, the same error will occur.

How do you usually install Cypress? From the error, you might need to pass additional env variables. There's a full guide here: https://docs.cypress.io/guides/getting-started/installing-cypress

**Comment by FrozenPandaz** [comment]
@yharaskrik
Can you please create a separate issue with the command that you ran?

**Comment by SvenBudak** [comment]
The error is still there but topic closed?
