### ISSUE TITLE
Jest tests failing after upgrade to 12.4.0 (ts-jest/jest 27, jest-preset-angular 9)

### ISSUE THREAD

**Issue by yharaskrik** [nrwl/nx#6110]
## Current Behavior

Erroring when running Angular tests (node tests run fine)

```
Component 'FundraiserPageEditorPublishDialogComponent' is not resolved:
     - templateUrl: ./fundraiser-page-editor-publish-dialog.component.html
     - styleUrls: ["./fundraiser-page-editor-publish-dialog.component.scss"]
    Did you run and wait for 'resolveComponentResources()'?
```

## Expected Behavior

Tests run as they do before

## Steps to Reproduce

Upgraded and having all the libraries migrate broke Angular tests, Node tests run fine. I drilled into the Nx code and found that `testEnvironment` is being set to `jsdom` in the root `jest.preset.js` now, which is right, but doesn't seem to work right. I found this issue in the `jest-preset-angular` repo that is discussing the same thing, but the fix is what Nx provided in a migration so not sure what went wrong.

https://github.com/thymikee/jest-preset-angular/issues/951

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

```
Node : 12.20.1
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 12.4.0
  @nrwl/cli : 12.4.0
  @nrwl/cypress : 12.4.0
  @nrwl/devkit : 12.4.0
  @nrwl/eslint-plugin-nx : 12.4.0
  @nrwl/express : 12.4.0
  @nrwl/jest : 12.4.0
  @nrwl/linter : 12.4.0
  @nrwl/nest : 12.4.0
  @nrwl/next : Not Found
  @nrwl/node : 12.4.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.4.0
  @nrwl/web : 12.4.0
  @nrwl/workspace : 12.4.0
  @nrwl/storybook : 12.4.0
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
jest-preset-angular: 9.0.3
jest: 27.0.3
ts-jest: 27.0.3
```

**Comment by yharaskrik** [comment]
I upgraded the nx-incremental-large-repo to 12.4.0 and the same errors are showing up.

**Comment by AgentEnder** [comment]
@yharaskrik I am unable to reproduce this behavior, do you have a reproduction I can test this against?

**Comment by yharaskrik** [comment]
@AgentEnder 

1. clone `nx-incremental-large-repo`
2. `nx migrate @nrwl/workspace@latest`
3. `yarn`
4. `nx migrate --run-migrations`
5. try and run one of the test suites (or all of them).

These steps recreated the problem for me earlier.

**Comment by AgentEnder** [comment]
I was able to fix this in the reproduction repo for 1 lib with the following changeset: https://github.com/yharaskrik/nx-incremental-large-repo/pull/1.

The jest migration failed to identify that the libraries were angular related and did not update the transforms + globals to reflect. I'm looking into the migration script now to see if there is a better way to tidying this one up.

**Comment by yharaskrik** [comment]
Nice! Glad you were able to find the issue. I have always thought that having some key somewhere (maybe nx.json) that tells Nx what framework the library is would be awesome. It would help with a lot of random scripts.

**Comment by AgentEnder** [comment]
Is there anyway you can share your jest.config.js file before the migration? 

We don't want to switch to checking the test-setup.ts file, since the relevant section of the migration is changing how the transforms are handled. We want to detect the old way and change it to the new. If the old way was not there, than the tests should not have succeeded in the past. If you check nx test on the nx-large-incremental repo they actually do not run in its starting state, probably something that was overlooked at the time.

If your project was missed by the migration, its possible its jest.config was missing something regarding its transforms.

**Comment by yharaskrik** [comment]
Ok I was able to recreate this in a public repo

Here is the branch: https://github.com/trellisorg/platform/tree/jaybell/upgrade-repo-12-4-0

The current commit on that branch is failing with

```
nx run angularfire-ngrx-demo:test 
 FAIL  apps/angularfire-ngrx-demo/src/app/app.component.spec.ts
  AppComponent
    ✕ should create (19 ms)

  ● AppComponent › should create

    Component 'AppComponent' is not resolved:
     - templateUrl: ./app.component.html
     - styleUrls: ["./app.component.scss"]
    Did you run and wait for 'resolveComponentResources()'?
```

 when running `yarn nx test angularfire-ngrx-demo`

If you go back one commit to `7203d568c4a988709c93479d5f599fda3592e94b` this was right before upgrading the same tests pass.

**Comment by dean-g** [comment]
Having a similar issue during migration: [Unable to run Jest](https://github.com/nrwl/nx/issues/6090). Any one can help me on this?
