### ISSUE TITLE
Environment variable support exposes potentially sensitive data in web builds

### ISSUE THREAD

**Issue by dariusj18** [nrwl/nx#6117]
## Current Behavior

Currently NX automatically adds a Webpack.Plugin to include environment variables prefixed with NX_.  The problem is that NX  automatically includes variables that NX defines during the build, including `NX_TERMINAL_OUTPUT_PATH` which exposes potentially sensitive paths from the computer running the build.

## Expected Behavior

This was added via https://github.com/nrwl/nx/pull/2502 and I would prefer to use the babel `transform-inline-environment-variables` plugin.  Which works in code from my repository, but code form `styled-components` still ends up using the webpack plugin.

Possible solutions include:  
- Add an allow-list/block-list of environment variables to include in the `workspace.json`'s build options.
- Add an option to specify your own prefix.  This might also be a good idea to allow for easier migration of CRAs.
- Add flag for the behavior.

## Steps to Reproduce

Running a production build of a react app with styled-components will inject the environment as an object when https://github.com/styled-components/styled-components/blob/902e72945712288b05dce3ee6d35e0af70005f1e/packages/styled-components/src/constants.ts is a part of the package.

### Environment

>   Node : 14.16.0
>   OS   : win32 x64
>   npm  : 7.16.0
> 
>   nx : Not Found
>   @nrwl/angular : Not Found
>   @nrwl/cli : 12.3.6
>   @nrwl/cypress : 12.3.6
>   @nrwl/devkit : 12.3.6
>   @nrwl/eslint-plugin-nx : 12.3.6
>   @nrwl/express : Not Found
>   @nrwl/jest : 12.3.6
>   @nrwl/linter : 12.3.6
>   @nrwl/nest : 12.3.6
>   @nrwl/next : Not Found
>   @nrwl/node : 12.3.6
>   @nrwl/react : 12.3.6
>   @nrwl/schematics : Not Found
>   @nrwl/tao : 12.3.6
>   @nrwl/web : 12.3.6
>   @nrwl/workspace : 12.3.6
>   @nrwl/storybook : 12.3.6
>   @nrwl/gatsby : Not Found
>   typescript : 4.2.4

**Comment by NAndreasson** [comment]
I also perceive this as an issue. Whitelisting env variables seems like a prudent default for the production bundle.
