### ISSUE TITLE
12.4.0 NX Format continuously updating some json files

### ISSUE THREAD

**Issue by CH9587** [nrwl/nx#6118]
## Current Behavior

After running `npx create-nx-workspace@latest` with `react` and `scss`, any time I run `npm run format`, the following three `.json` files are modified:

- nx.json
- tsconfig.base.json
- workspace.json

![image](https://user-images.githubusercontent.com/69921547/123281919-10835900-d4d8-11eb-99dd-c94d8c5540a8.png)

Running it the first time causes changes:
![image](https://user-images.githubusercontent.com/69921547/123281385-a79be100-d4d7-11eb-8cfb-fbf19047d4e5.png)
and subsequent runs cause the modifications to revert back to the original state. This happens continuously, and causes many issues when hooked into husky. None of the command line args seem to affect these three files being formatted. e.g. `--libs-and-apps` still modifies these three files.

Only the recommended extensions from `.vscode` are enabled. latest @nrwl/cli (nx v12.4.0) is installed globally via npm

## Expected Behavior

`nx format` should not continuously update these three files unless there is an actual formatting discrepancy.

## Steps to Reproduce

- Clone latest https://github.com/nrwl/nx-examples
- Install dependencies via `npm i --legacy-peer-deps`
- run `npm run format` or `nx format:write`

You can also try the following default react project:
- Clone https://github.com/CH9587/prettier-check
- `npm i --legacy-peer-deps`
- `npm run format`

You can even replicate the issue on this repo:
- clone https://github.com/nrwl/nx.git
- `yarn install`
- run `nx format` or `npm run format` and see that the files do not update
- update all `@nrwl/...: 12.3.0` references with `12.4.0`
- delete `yarn.lock` and `node_modules` and run `yarn install` to update versions
- run `nx format` or `npm run format` and the files update

**Note** this issue doesn't seem to occur on the [previous commit of v12](https://github.com/nrwl/nx-examples/commit/7d74659e4d60dc65c6a006ce5c0495320c70b777) in the `nx-examples` repo

Possibly related: https://github.com/nrwl/nx/pull/5890 ?

### Environment

  Node : 14.17.0
  OS   : darwin x64
  npm  : 7.14.0
  
  nx : Not Found
  @nrwl/angular : 12.4.0-beta.2
  @nrwl/cli : 12.4.0-beta.2
  @nrwl/cypress : 12.4.0-beta.2
  @nrwl/devkit : 12.4.0-beta.2
  @nrwl/eslint-plugin-nx : 12.4.0-beta.2
  @nrwl/express : Not Found
  @nrwl/jest : 12.4.0-beta.2
  @nrwl/linter : 12.4.0-beta.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 12.4.0-beta.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.4.0-beta.2
  @nrwl/web : 12.4.0-beta.2
  @nrwl/workspace : 12.4.0-beta.2
  @nrwl/storybook : 12.4.0-beta.2
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by puku0x** [comment]
> Possibly related: #5890 ?

You're right. And #6044 fixed this.
