### ISSUE TITLE
workspace-schematic ignores argv in schema.json

### ISSUE THREAD

**Issue by jasedwards** [nrwl/nx#612]
I have a custom schematic where I would like to have to properties with default values from argv.  Here is the relevant part of the schema.json.  At first I set name to be index 0 and prefix to be index 1.  prefix kept coming through as undefined even though my command was "npm run workspace-schematic new-lib MyLib ml".  I would expect prefix to be ml now.  So I was checking if maybe everything but the first argv was getting stripped out somewhere.  I switched to name as index 1 and prefix to index 0 and ran "npm run workspace-schematic new-lib ml MyLib.  In this case it was still using argv index 0 for the name and setting it to "ml".  Here is the schema.json with reversed indices.  Does it ignore this type of default?

``` json
"name": {
      "type": "string",
      "description": "Library name",
      "$default": {
        "$source": "argv",
        "index": 1
      }
    },
    "prefix": {
      "type": "string",
      "format": "html-selector",
      "description": "The prefix to apply to generated selectors.",
      "$default":{
        "$source": "argv",
        "index": 0
      }
    }
```

**Comment by FrozenPandaz** [comment]
Fixed with https://github.com/nrwl/nx/pull/831
