### ISSUE TITLE
NX Migration 11.6 to 12.4 error on app start and build: "TS17004: Cannot use JSX unless the '--jsx' flag is provided." and "Module '****' was resolved to '***', but '--jsx' is not set."

### ISSUE THREAD

**Issue by joaoantunesTD** [nrwl/nx#6126]
Recently, I have started using NX professionally in a new React project (Thanks for your work!!) around April. At the time I have created a new workspace from scratch using 11.6 version.

Now, I am trying to migrate it to 12.4 following the steps defined in the documentation [here](https://nx.dev/latest/react/core-concepts/updating-nx).

Following it, the main changes are upgrades of lib versions. I let here an image:

![image](https://user-images.githubusercontent.com/80686896/123411273-2bbd9980-d5a8-11eb-9a33-bf439cdbaed5.png)

After everything is migrated I started having some errors, related to typescript and jsx, when using the command:
```nx build --prod```
or
```nx serve```

Those are the errors:
- **"TS17004: Cannot use JSX unless the '--jsx' flag is provided."** 
- **"Module '****' was resolved to '***', but '--jsx' is not set."**

The commands referred are executing for one react application I have in the workspace. After digging a bit I noticed if I changed:
"jsx": "react-jsx",
to
"jsx": "react",

In the ```tsconfig.json``` of this application the errors would disappear.

This happens for apps or libs which contain react components using JSX. On libs with no components, only hooks, for example, there is no errors.

Should I do anything further, that I am missing?

Thanks!

**Comment by mboettcher** [comment]
I had the same issue. Upgrading Typescript solved it. My Typescript version was `4.0.5` and is now `4.3.5`

**Comment by joaoantunesTD** [comment]
Thanks! It makes sense. I will try that.

**Comment by joaoantunesTD** [comment]
Hi there,

I confirm, after upgrading to ```4.3.5``` version of typescript the error disappeared.

Thanks!
