### ISSUE TITLE
Empty line after imports

### ISSUE THREAD

**Issue by ph55** [nrwl/nx#614]
[V] Enhancement

Please add empty line after imports in new generated libs' modules. (`ng g lib`)
Currently its added without.

 
![image](https://user-images.githubusercontent.com/1386622/42214073-292f7a7e-7ec3-11e8-8990-0c197c520674.png)

**Comment by ThomasBurleson** [comment]
Why is an empty line needed?

**Comment by ph55** [comment]
Well it's sort of convention.

Also for consistency. 
All projects/components/services/modules created by `ng g application`, `ng g c`, `ng g m` and `ng g s` have empty line after imports.

**Comment by JamesHenry** [comment]
I agree that it looks cluttered and deviates from the other generated code. It is very low priority, as it has no semantic significance, but I think we should accept a PR on this.

Do you want to create one @ph55?

**Comment by FrozenPandaz** [comment]
@cristianmartinez Of course! 👍Thank you for taking a look!

**Comment by cristianmartinez** [comment]
Done :)
