### ISSUE TITLE
web:package - incorrect output

### ISSUE THREAD

**Issue by Bielik20** [nrwl/nx#6143]
I have stumbled on many problems with `web:package` where it does not produce what would be expected. I have decided to create this one issue to address them. `web:package` really does need some love. Some of these are small improvement suggestions, some are serious bugs. I have marked them with 🟢 , 🟡 , 🔴 . I have decided to make this issue a bug report because in my opinion most of those problems are actually bugs (especially yellow and red ones).

## Steps to reproduce

Create yourself a react publishable lib:

* `nx g @nrwl/react:lib my-react-lib --publishable --importPath some-import-path`

Add some code with classes, and other modern ES features.

### 🟢  Missing `.browserslistrc`

When creating a publishable lib one would expect default configuration to address most common configuration. Adding `.browserslistrc` to the repository root (if not present) would be helpful for those users that did not have experience with that. You could use one of your presets like: https://github.com/nrwl/nx/blob/06f84b3326ad80103b0edff8bdfbc2436bf388f0/packages/web/src/generators/application/files/app/browserslist#L1-L13

### 🟡  `core-js` does not appear in created `package.json`

When compiling `core-js` imports will appear in bundle:

```
import 'core-js/modules/web.dom-collections.iterator.js';
```

But they will not appear in created `package.json`. This will create problems should someone who does not have `core-js` installed and installs this library.

### 🔴  `tslib` gets bundled into the package

Instead of `tslib` being imported as configured in `tsconfig.base.json`:
```
    "importHelpers": true,
```

they appear in dist bundle.

#### Current Behaviour

```js
function __awaiter(thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
}
```

#### Expected Behaviour

```js
import { __awaiter } from 'tslib';
```

#### Workaround

Manually add `tslib` as external:

```
            "external": ["react/jsx-runtime", "tslib"],
```

### 🟡  With above workaround `tslib` does not appear in created `package.json`

The same issue as with `core-js` but with `tslib`

### 🔴  `@babel/runtime` gets bundled into the package

The same as with `tslib` but `@babel/runtime`. In here I do not have a workaround, adding to `external` doesn't fix that. Example: 

```js
function _classCallCheck(instance, Constructor) {
  if (!(instance instanceof Constructor)) {
    throw new TypeError("Cannot call a class as a function");
  }
}
```

### 🟡  99% `@babel/runtime` won't appear in created `package.json`

Same issue again, it should appear as a dependency if we fix above issue.

### 🔴  submodules get bundled into the package

This I have raised here https://github.com/nrwl/nx/issues/3809

### 🟢  There is no generator for publishable web lib

This is not a big issue we could use a generator for creating publishable lib that is not react nor angular, but for web in general. I am actually doing it myself by using `@nrwl/web:lib` with `buildable` flag and replace build command like [that](https://github.com/Bielik20/ts-libs/blob/a766dd21bb62460478f465ca56951680b918c898/tools/generators/web-lib/index.ts#L34-L58).

## Environment
```
  Node : 14.16.1
  OS   : darwin x64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.3.6
  @nrwl/cypress : 12.3.6
  @nrwl/devkit : 12.3.6
  @nrwl/eslint-plugin-nx : 12.3.6
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.6
  @nrwl/linter : 12.3.6
  @nrwl/nest : Not Found
  @nrwl/next : 12.3.6
  @nrwl/node : Not Found
  @nrwl/react : 12.3.6
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.6
  @nrwl/web : 12.3.6
  @nrwl/workspace : 12.3.6
  @nrwl/storybook : 12.3.6
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by Bielik20** [comment]
It is still a valid issue.

**Comment by Bielik20** [comment]
Some still remain valid...

**Comment by jaysoo** [comment]
We reworked our webpack setup and no longer add babel runtime and regenerator.
