### ISSUE TITLE
Angular preset app component template unable to load nx logo image

### ISSUE THREAD

**Issue by mythopoeian** [nrwl/nx#6148]
## Current Behavior
After freshly creating a new nx workspace with a single app using the Angular preset, the `app.component.html` template defines a logo to display that is not available to be retrieved: https://nx.dev/assets/images/nx-logo-white.svg

![image](https://user-images.githubusercontent.com/57697880/123556599-fc638400-d783-11eb-8569-f7937aff85e9.png)

## Expected Behavior
I would expect the asset to be available when serving the Angular app. I would also expect that asset to be available via a browser. Neither are possible.

## Steps to Reproduce
- `npx create-nx-workspace --preset=angular`
- `npm install`
- `npm run start`

### Failure Logs
![image](https://user-images.githubusercontent.com/57697880/123556709-a8a56a80-d784-11eb-9c76-d4a82f2093ca.png)

### Environment
```
  Node : 14.17.1
  OS   : linux x64
  npm  : 6.14.13
  
  nx : Not Found
  @nrwl/angular : 12.4.0
  @nrwl/cli : 12.4.0
  @nrwl/cypress : 12.4.0
  @nrwl/devkit : 12.4.0
  @nrwl/eslint-plugin-nx : 12.4.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.4.0
  @nrwl/linter : 12.4.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.4.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.4.0
  @nrwl/storybook : 12.4.0
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by FrozenPandaz** [comment]
Thanks for reporting the issue. This is fixed since `12.5.0` in https://github.com/nrwl/nx/pull/6114
