### ISSUE TITLE
[Schematics] - Wront path added to the module by the @nrwl/nest:provider schematics

### ISSUE THREAD

**Issue by gauravsoni119** [nrwl/nx#6149]
## Current Behavior
After running `@nrwl/nest:provider` schematics, the provider added to the module has the wrong path. For example, running the below schematics,

`ng g @nrwl/nest:provider --name=connection --project=api --directory=core` will add the following provider to the core.module.ts:-

`import { Connection } from './connection/connection.provider';`

but the generated provider has a path

`import { Connection } from './connection/connection';`

## Expected Behavior
After running the schematics, the correct path should be added to the module i.e

`import { Connection } from './connection/connection';`

## Steps to Reproduce

1. Run the `@nrwl/nest:provider` schematics with the directory having a module(for example **core.module.ts**).
2. Look at the import path of the added provider. 

[Attached Screenshot](https://user-images.githubusercontent.com/8476712/123559267-4441d580-d79b-11eb-82dd-d14cbb0181ae.png)

**Note:-** The workspace two applications. One is with `nestjs` and another one is with `angular`.

### Environment
  Node : 10.13.0
  OS   : linux x64
  npm  : 6.14.8
  
  nx : Not Found
  @nrwl/angular : 12.3.3
  @nrwl/cli : 12.3.3
  @nrwl/cypress : 12.3.3
  @nrwl/devkit : 12.3.3
  @nrwl/eslint-plugin-nx : 12.3.3
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.3
  @nrwl/linter : 12.3.3
  @nrwl/nest : 12.3.3
  @nrwl/next : Not Found
  @nrwl/node : 12.3.3
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.3
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.3
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by nartc** [comment]
Hi @gauravsoni119, this issue has been fixed in Nx 12.6 where we wrap and use NestJS Schematics directly. Please consider upgrading to 12.6.
