### ISSUE TITLE
workspace: @nrwl/workspace uses `@angular-devkit/schematics` but doesn't provide it within dependencies

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#6153]
## Current Behavior
if we use nx with react ecosystem and one would like to import any API from `@nrwl/workspace` it will FAIL.

## Expected Behavior

- no errors when importing stuff from `@nrwl/workspace`  ([easy quick fix by providing devkit as direct dependency](https://github.com/nrwl/nx/blob/master/packages/workspace/package.json#L57-L80))
- getting rid of `@angular-devkit/schematics`  from workspace package (its still used quite heavily https://github.com/nrwl/nx/blob/master/packages/workspace/src/utils/ast-utils.ts#L8-L19)

## Steps to Reproduce

for example in workspace custom generators:

```ts
import {serializeJson} from '@nrwl/workspace'

// code ....
serializeJson(objectValue)
```

- running  tests or generator will fail with error:

![2021-06-28 at 11 41](https://user-images.githubusercontent.com/1223799/123615616-c4048a00-d805-11eb-99b5-dfba50147060.png)

### Environment

```
 Node : 12.20.1
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.4.0
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.4.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 12.4.0
  @nrwl/linter : 12.4.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.4.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.4.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.4.0
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

**Comment by FrozenPandaz** [comment]
This is intentional. We don't want `@angular-devkit/schematics` to be a `dependency` but we also wanted to keep the older utils where they are in case people are using them. If your plugin is written with the Nx Devkit, please import utilities from `@nrwl/devkit`. If anything is missing from there, let us know.

**Comment by Hotell** [comment]
> This is intentional. We don't want @angular-devkit/schematics to be a dependency but we also wanted to keep the older utils where they are in case people are using them.

I understand the reasoning, but with this setup we are shipping invalid nx package  (as described in the issue) :) 

I'd suggest to create new `compat` package with deprecated apis for users that still use old schematics and re-export it from workspace
- correct package dep resolution
- clean workspace 
- expicit deprecation contract for consumers

> If your plugin is written with the Nx Devkit

this has nothing to do with authoring plugins etc, any user that will import anything from `@nrwl/workspace` will get runtime error.

**Comment by trumbitta** [comment]
> If anything is missing from there, let us know.

Hey @FrozenPandaz I was able to remove almost entirely `@nrwl/workspace` from the imports of my plugin: the only one I didn't figure out how to replace is:

`import { runTasksInSerial } from '@nrwl/workspace/src/utilities/run-tasks-in-serial';`
