### ISSUE TITLE
[Discussion] where to put shared helpers/models/interfaces.

### ISSUE THREAD

**Issue by ph55** [nrwl/nx#616]
Need advice guys.

Is everything should be module inside libs folder?
Or there is a place for helpers/assets barrels as well?

Lets say I have few models/interfaces that used across multiple modules.
If I put it inside one of modules - it could lead to circular dependency.

Will `dep-graph` be able to process it ?

**Comment by ternyk** [comment]
I'm creating the library for models but without any NgModule in it. Then I can assign tags for such a library to help dependency checks and visualisation.

**Comment by ph55** [comment]
Thanks, also thought about this option.
But since `--nomodule` flag is gone, it's a bit weird to have all these module related config and test files.

Found this comment of Justin https://github.com/nrwl/nx/issues/479#issuecomment-392863191
Seems that preferable option now is custom schematics, huh.
