### ISSUE TITLE
`nx migrate latest` only bumps @nrwl/workspace

### ISSUE THREAD

**Issue by AgentEnder** [nrwl/nx#6160]
## Current Behavior
Running `nx migrate latest` only bumps the `@nrwl/workspace` package.

## Expected Behavior
Running `nx migrate latest` bump all of the nrwl packages.

## Steps to Reproduce
Attempt to migrate any repo on 12.3 or below.

**Comment by MichaelDeBoey** [comment]
I just migrated from `12.3` to latest and it worked perfectly.

**Comment by AgentEnder** [comment]
Were you on windows / mac / linux? I just ran into this issue on a few repos.

**Comment by AgentEnder** [comment]
I'm closing this for now, as I am unable to reproduce on other repositories. Must have been some misconfiguration.

**Comment by MichaelDeBoey** [comment]
macOS here
