### ISSUE TITLE
Broken Img Link In Initial Application

### ISSUE THREAD

**Issue by linbudu599** [nrwl/nx#6163]
## Current Behavior

Generated application contains Nx logo by link: `https://nx.dev/assets/images/nx-logo-white.svg`, and import it like:

```html
<img
    alt="Nx logo"
    width="75"
    src="https://nx.dev/assets/images/nx-logo-white.svg"
  />
```

And I found this link got broke and will redirect to Nx documentation site intead of displaying the img:

![image](https://user-images.githubusercontent.com/48507806/123755156-36509980-d8ee-11eb-9d59-01db4e9800a1.png)

I checked the documentation site and found all the logos are replaced as svg, so I think generated application template should keep the same with it?

It you're too busy to handle it, I'm glad to submit a PR to fix this bug in all templates.

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by mandarini** [comment]
Hi there @linbudu599 ! Would you like to try to submit a PR for this?

**Comment by linbudu599** [comment]
> Hi there @linbudu599 ! Would you like to try to submit a PR for this?

Sure, this weekend probably.

**Comment by linbudu599** [comment]
This bug was already fixed in latest version, [code](https://github.com/nrwl/nx/blob/master/packages/angular/src/generators/application/lib/nrwl-home-tpl.ts), so I'm closing this issue now.
