### ISSUE TITLE
upgrade to 6.0.0 fails

### ISSUE THREAD

**Issue by JochenDiekenbrock** [nrwl/nx#617]
I want to migrate from Angular 5.2.10, nx 1.0.3 to the newest version. The direct upgrade to the newest version failed, so I tried it step by step. First I did `yarn add @nrwl/schematics@6.0.0 --dev` followed by `yarn update`

This failed after some time with the error "Cannot read property 'prefix' of undefined". After some digging around, I found that in `@nrwl/schematics/migrations/update-6-0-0/update-6-0-0.js`
the line 267 fails:
var prefix = json.schematics['@nrwl/schematics:component'].prefix;

The automatically migrated angular.json does not contain an entry for @nrwl/schematics:component.

Can I add something to .angular-cli.json before the migration to circumvent this bug?

**Comment by JochenDiekenbrock** [comment]
I found the cause. I somehow had
`"$schema": "./node_modules/@angular/cli/lib/config/schema.json",`
in .angular-cli.json. By comparing with another nx project, I found that it should be
`"$schema": "./node_modules/@nrwl/schematics/src/schema.json",`

After changing the $schemo, yarn update worked fine.

**Comment by JamesHenry** [comment]
Seems like this issue can be closed then 😃
