### ISSUE TITLE
Jasmine is not defined when using @nrwl/angular/testing

### ISSUE THREAD

**Issue by Lalem001** [nrwl/nx#6171]
## Current Behavior
```
ReferenceError: jasmine is not defined

   8 |
>  9 | import { hot } from '@nrwl/angular/testing';
     | ^
```

Jasmine being referenced in `jasmine-marbles` which is a dependency of mentioned `@nrwl/angular/testing`.

Based on some other tickets, it looks like jest dropped global `jasmine`?

## Expected Behavior
Importing `@nrwl/angular/testing` should just work.

## Steps to Reproduce
Simply import `@nrwl/angular/testing` in a spec file.

### Failure Logs
```
● Test suite failed to run

  ReferenceError: jasmine is not defined

     8 |
  >  9 | import { hot } from '@nrwl/angular/testing';
       | ^
    10 |

    at setupEnvironment (../../../../node_modules/jasmine-marbles/bundles/jasmine-marbles.umd.js:386:5)
    at ../../../../node_modules/jasmine-marbles/bundles/jasmine-marbles.umd.js:393:1
    at ../../../../node_modules/jasmine-marbles/bundles/jasmine-marbles.umd.js:2:65
    at Object.<anonymous> (../../../../node_modules/jasmine-marbles/bundles/jasmine-marbles.umd.js:5:2)
    at ../../../../node_modules/@nrwl/angular/bundles/nrwl-angular-testing.umd.js:2:85
    at Object.<anonymous> (../../../../node_modules/@nrwl/angular/bundles/nrwl-angular-testing.umd.js:5:2)
```

### Environment

```

>  NX  Report complete - copy this into the issue template

  Node : 14.17.0
  OS   : darwin x64
  npm  : 6.14.13
  
  nx : Not Found
  @nrwl/angular : 12.5.0
  @nrwl/cli : 12.5.0
  @nrwl/cypress : 12.5.0
  @nrwl/devkit : 12.5.0
  @nrwl/eslint-plugin-nx : 12.5.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.0
  @nrwl/linter : 12.5.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.0
  @nrwl/storybook : 12.5.0
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

**Comment by Lalem001** [comment]
Additional context:

This is occurring after migrating from `12.0.4` to `12.5.0`.

**Comment by AgentEnder** [comment]
Hey, yeah Jest 27 swapped test runners to jest-circus. If using @nrwl/angular/testing I would recommend swapping the testrunner to jest-jasmine2 in your jest.preset.js or jest.config.js file.

**Comment by andrewgremlich** [comment]
I'm assuming this issue might be related...

As soon as `jest-jasmine2` is added to a default nx angular project, this follow error disappears, but if I add `jest-jasmine2` to any `jest.config.js` file the error persists.

![jasmine-error](https://user-images.githubusercontent.com/10425476/125142836-f0f25000-e0d5-11eb-8c4b-75a11f85641e.png)
