### ISSUE TITLE
Support AWS Amplify with Next.js plugin

### ISSUE THREAD

**Issue by aaronmcadam** [nrwl/nx#6172]
## Description
I've tried and failed to get a Next.js app working with AWS Amplify.
I think there might be a problem with the package.json file. Amplify uses that to decide whether to generate SSR or SSG sites. Here are the docs: https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app.

I've tried copying a package.json file into the Amplify build process, but that didn't work.

From what I can gather, Amplify's monorepo support assumes that each app directory can stand alone, with all of its dependencies and node modules in one directory, *not in the root directory like how Nx works*.

## Motivation

Others have posted about having this problem on the Amplify Console repo: https://github.com/aws-amplify/amplify-console/issues/1866.

## Suggested Implementation
We could output a package.json with scripts that Amplify expects to see.

**Comment by Rafcin** [comment]
Has there been any update to this?

**Comment by aaronmcadam** [comment]
I don't know @Rafcin, I dropped Next.js from my project for other reasons, so I've not followed up on this issue.

**Comment by Rafcin** [comment]
That's a shame, I was really hoping to find some answers. I've been trying to get it to work for the last week and I can't get it to build properly with amplify, I finally figured out you don't actually need to go into the individual app roots and build it, if you just use NX and build it it builds correctly but it doesn't deploy correctly because of an SSR resource that Json issue

**Comment by reeslabree** [comment]
@Rafcin were you running into issues finding the nx configuration? Thats where I'm currently stuck.

**Comment by Rafcin** [comment]
> @Rafcin were you running into issues finding the nx configuration? Thats where I'm currently stuck.
> 
> I've been building from the root directory and pointing the output to `dist/apps/myApp/.next`, and pointing the cache to `node_modules/**/*`

I don't think I had any issues, with my Amplify config the build always started in the monorepo app, so I would step out to the root, run install etc. The major pain point was the nm folder, pointing it correctly just became a pain and even if I managed to get everything to build, there was some issue with the SSR build and it just didn't work.

For the time I used NX I thoroughly enjoyed it, however if you're doing some monorepo work take a peek at Turborepo. It's solid I promise. It will work if you use something like AWS Amplify to deploy and it's just less of a pain in the ass to work with.

**Comment by reeslabree** [comment]
> > @Rafcin were you running into issues finding the nx configuration? Thats where I'm currently stuck.
> > I've been building from the root directory and pointing the output to `dist/apps/myApp/.next`, and pointing the cache to `node_modules/**/*`
> 
> I don't think I had any issues, with my Amplify config the build always started in the monorepo app, so I would step out to the root, run install etc. The major pain point was the nm folder, pointing it correctly just became a pain and even if I managed to get everything to build, there was some issue with the SSR build and it just didn't work.
> 
> For the time I used NX I thoroughly enjoyed it, however if you're doing some monorepo work take a peek at Turborepo. It's solid I promise. It will work if you use something like AWS Amplify to deploy and it's just less of a pain in the ass to work with.

I'll check it out today - initially was opposed since it seemed like an equivalent headache to get my Amplify hosting up and running but at this point I'll try anything. Do you know of any guides for converting an Nx monorepo to a turborepo monorepo?

**Comment by mad-gav** [comment]
Are we saying you can't deploy to AWS using nx? I'm looking at nx vs turborepo for a new project and we need to use AWS amplify

**Comment by reeslabree** [comment]
Unfortunately Nx  isn't supported at the moment - I switched to Turborepo and it all worked out of the box. I submitted a support ticket to AWS and it sounds like they have it in their backlog, but probably not particularly prioritized. Hopefully the support comes some day and I can switch back, but for now I'm rocking Turborepo.
