### ISSUE TITLE
ng g ngrx doesn't create all files

### ISSUE THREAD

**Issue by ternyk** [nrwl/nx#618]
Hi
There is something not clear regarding which files should be generated for ngrx.
Currently when I use that functionality, only actions, effects, reducer files are created but documentation says that also interfaces.ts and init.ts files should be. See: https://github.com/nrwl/nx/blob/68e34d494fdca1c57a757c889ea8105e8a0a7a6e/packages/schematics/src/collection/ngrx/ngrx.md

There is also merged PR: https://github.com/nrwl/nx/pull/386 which states:

> ...
> generate init and interface files
> ...
> 

but in the commit I can see that generation of these files was removed.

**Comment by ThomasBurleson** [comment]
@ternyk - see our upcoming [NgRx.md Schematics doc](https://github.com/ThomasBurleson/nx/blob/2b77c140083f284848f44dbad6e0433f16d18578/packages/schematics/src/collection/ngrx/ngrx.md)
