### ISSUE TITLE
git actions fails when nx affected:e2e runs

### ISSUE THREAD

**Issue by vetik32** [nrwl/nx#6181]
## Current Behavior
consider this PR - [PR#3](https://github.com/Bizaline/technical-challenge/pull/3)

## Expected Behavior
to be green - [PR#1](https://github.com/Bizaline/technical-challenge/pull/1) e.g.
## Steps to Reproduce

https://github.com/Bizaline/technical-challenge/runs/2946099625?check_suite_focus=true

check failed `Run e2e test` 

```
Run npx nx affected:e2e
  npx nx affected:e2e
  shell: /usr/bin/bash -e {0}

>  NX   NOTE  Affected criteria defaulted to --base=main --head=HEAD

fatal: Not a valid object name main
fatal: No such ref: 'main'
nx affected:e2e

Run e2e tests for the applications affected by changes
```

**Comment by FrozenPandaz** [comment]
This is because in your CI pipeline, `main` is not checked out. You can set add `--base origin/main` to your `nx affected:e2e` command to make it refer to `origin/main` which I believe should be checked out in github actions.

**Comment by vetik32** [comment]
Thanks, 

Run npx nx affected:e2e --base origin/main
fatal: Not a valid object name origin/main
fatal: No such ref: 'origin/main'
nx affected:e2e


![Screen Shot 2021-07-08 at 17 56 51](https://user-images.githubusercontent.com/2412005/124944325-e5d7eb00-e015-11eb-9185-48df2827007f.png)


any clue ?

p.s. thank for your support.

**Comment by vetik32** [comment]
@FrozenPandaz - sorry - too late noticed your reply - did expect that soon - do you get notification after closing issue?
