### ISSUE TITLE
Application generation fails if e2eTestRunner is set to "protractor".

### ISSUE THREAD

**Issue by ennovum** [nrwl/nx#6185]
## Current Behavior
In newly created Nx workspace, generating a new application fails if `e2eTestRunner` options is set to `protractor`.

## Expected Behavior
The application should be generated properly with the proper e2e setup.

## Steps to Reproduce
I'm using the latest Angular & Nx. I created a new workspace using `create-nx-workspace`. I'm trying to generate new app using the following command.

```
npm run nx -- g @nrwl/angular:application --name="my-app" --style="scss" --routing=false --unitTestRunner="jest" --e2eTestRunner="protractor"
```

The application generation fails with the following error.

```
Cannot read property 'replace' of null
```

### Failure Logs
```
Cannot read property 'replace' of null
npm ERR! code 1
npm ERR! path C:\Users\...\Dev\my-app
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c nx g @nrwl/angular:application --name=my-app --style=scss --routing=false --unitTestRunner=jest --e2eTestRunner=protractor

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Local\npm-cache\_logs\2021-06-29T22_06_30_854Z-debug.log
```

I dug into this a little bit and I found a slight mismatch between options logged here:
https://github.com/nrwl/nx/blob/01934415783984ff40f55ca14cac1f08fbda6b44/packages/angular/src/generators/application/application.ts#L38

and `e2eProjectRoot` logged here:
https://github.com/nrwl/nx/blob/01934415783984ff40f55ca14cac1f08fbda6b44/packages/angular/src/generators/application/application.ts#L47

Specifically it's `apps/my-app-e2e` vs. `apps/my-app/e2e`.

[UPDATE1]

I believe the problem is around how the `e2eProjectRoot` is not passed to `updateE2eProject` call here:
https://github.com/nrwl/nx/blob/01934415783984ff40f55ca14cac1f08fbda6b44/packages/angular/src/generators/application/lib/add-e2e.ts#L45

So inside that function the value from `options` is used, which is different than the one in `e2eProjectRoot`.

### Environment
```
$ npm run nx -- report

> platform-portal-ui3@0.0.0 nx
> nx "report"


>  NX  Report complete - copy this into the issue template

  Node : 12.22.1
  OS   : win32 x64
  npm  : 7.6.3

  nx : Not Found
  @nrwl/angular : 12.5.0
  @nrwl/cli : 12.5.0
  @nrwl/cypress : 12.5.0
  @nrwl/devkit : 12.5.0
  @nrwl/eslint-plugin-nx : 12.5.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.0
  @nrwl/linter : 12.5.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.0
  @nrwl/storybook : 12.5.0
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by leosvelperez** [comment]
This was resolved in https://github.com/nrwl/nx/pull/6422. Closing.
