### ISSUE TITLE
DataPersistence should use proper types

### ISSUE THREAD

**Issue by Manduro** [nrwl/nx#62]
An effect built with the DataPersistence service is always typed as `Observable<any>`, while a regular effect can infer types like (for example) `Observable<user.CreateUserSuccess | user.CreateUserFailure>`. (1)

The arguments of `run`, `onError`, and others should also infer types. (2, 3)

#### Current situation
```ts
@Injectable()
class TodoEffects {
  @Effect()
  loadTodo = this.s.pessimisticUpdate('UPDATE_TODO', {
    run: (a, state) => ({
      type: 'TODO_UPDATED',
      payload: { user: state.user, newTitle: a.payload.newTitle }
    }),
    onError: (a, e: any) => null
  });

  constructor(private s: DataPersistence<TodosState>) {}
}
```
1. `(property) TodoEffects.loadTodo: Observable<any>`
2. `(parameter) a: Action`
3. `(parameter) state: any`

#### Optimal situation
```ts
@Injectable()
class TodoEffects {
  @Effect()
  loadTodo = this.s.pessimisticUpdate<UpdateTodo>('UPDATE_TODO', {
    run: (a, state) => ({
      type: 'TODO_UPDATED',
      payload: { user: state.user, newTitle: a.payload.newTitle }
    }),
    onError: (a, e: any) => null
  });

  constructor(private s: DataPersistence<TodosState>) {}
}
```
1. `(property) TodoEffects.loadTodo: Observable<{ type: 'TODO_UPDATED', payload: {...} }>`
2. `(parameter) a: UpdateTodo`
3. `(parameter) state: TodosState`

PR #63 attempts to fix issues 2 and 3

**Comment by vsavkin** [comment]
Thank you for the PR.

I'm not sure if 1 is actually possible. Do you think it is?

**Comment by Manduro** [comment]
@vsavkin I think it is. Upon first inspection it seemed that the typing was mostly broken because of rxjs operators used like `operator.call()`.

**Comment by vsavkin** [comment]
Will it be fixed if we switch to the new version of RxJs and use lettable operators instead?

**Comment by jobvanstiphout** [comment]
@vsavkin That would make it much easier. I'll give it a try.

**Comment by Manduro** [comment]
@vsavkin That would make it much easier. I'll give it a try.
