### ISSUE TITLE
Failing to use @ngrx/schematics commands with nx --version 6.1.0

### ISSUE THREAD

**Issue by joelmuskwe** [nrwl/nx#620]
When I use: 

`ng g store products --module libs/products/src/lib/products.module.ts`

```console
Schematic input does not validate against the Schema: {"module":"libs/products/src/lib/products.module.ts","path":"app","sourceDir":"src","flat":true,"spec":true,"statePath":"reducers","root":false}
Errors:

  Data path "" should have required property 'name'.
```

**Comment by vsavkin** [comment]
Could you provide a repro?

**Comment by joelmuskwe** [comment]
[https://github.com/joelmuskwe/nx-demo](url)

**Steps Done:**
create-nx-workspace MyShopSuite

- cd MyShopSuite
- ng g app website --style scss
- ng generate ngrx app --module=apps/website/src/app/app.module.ts  --onlyEmptyRoot
- ng g lib product
- ng g store libs/product/src/lib/Product -m product.module.ts

**Comment by bcabanes** [comment]
This issue is related to the Ngrx schematics, not specifically Nx.
