### ISSUE TITLE
Extract CSS does not work

### ISSUE THREAD

**Issue by montogeek** [nrwl/nx#6205]
## Current Behavior
Extract CSS does not work.

## Expected Behavior
CSS is extracted into an external CSS file.

## Steps to Reproduce

1. Run `npx create-nx-workspace`
```
npx: installed 48 in 3.688s
✔ Workspace name (e.g., org name)     · test
✔ What to create in the new workspace · react
✔ Application name                    · testapp
✔ Default stylesheet format           · css
✔ Use Nx Cloud? (It's free and doesn't require registration.) · No
```
2. Run `nx build testapp --prod`
3. Open `dist/apps/testapp/styles.[hash].css`.
4. File is empty, it should have the CSS.

### Environment

```
❯ nx report                                                                                                                                                                                               ─╯

>  NX  Report complete - copy this into the issue template

  Node : 14.17.0
  OS   : darwin arm64
  npm  : 6.14.13

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.5.1
  @nrwl/cypress : 12.5.1
  @nrwl/devkit : 12.5.1
  @nrwl/eslint-plugin-nx : 12.5.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.1
  @nrwl/linter : 12.5.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 12.5.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.1
  @nrwl/web : 12.5.1
  @nrwl/workspace : 12.5.1
  @nrwl/storybook : 12.5.1
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by FrozenPandaz** [comment]
Hi, are you referring to the styles in `apps/testapp/src/app.module.css`?

The CSS option is to use `css-modules` for component styles meaning the styles in `apps/testapp/src/app.module.css` are actually a part of the `main.js` and would not be extracted into a `.css` file.

The `css` that is extracted are the global ones in `apps/testapp/src/styles.css` which are properly extracted into `dist/apps/testapp/styles.css`
