### ISSUE TITLE
nx lint --quiet with run-many is not suppressing eslint warnings

### ISSUE THREAD

**Issue by bbugh** [nrwl/nx#6207]
## Current Behavior

When running `nx lint <project> --quiet`, eslint warnings are suppressed.
When running `nx run-many --target=lint --quiet <projects>`, eslint warnings appear in the output.

As far as I can tell from going through a bunch of issues and PRs, this should have been fixed by https://github.com/nrwl/nx/pull/4330 We are on nx 12.3.4, which appears to have the changes based on the threads.

## Expected Behavior

`--quiet` should work to suppress eslint warnings. 

According to #5069, we should be able to pass it through via `-- --quiet`, but that does not work either, [see my comment](https://github.com/nrwl/nx/issues/5069#issuecomment-871741213). 

## Steps to Reproduce

Run `nx run-many --target=lint --quiet` on a project with eslint warnings.

An easy way to do this is add a `map` that doesn't return anything.

```typescript
const _nothing = [1, 2, 3].map((i) => {
  if (i > 0) {
    return 1;
  }
});
```

### Environment

<details>
<summary> nx report</summary>

```
yarn run v1.22.10
$ nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.17.0
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : 12.3.4
  @nrwl/angular : Not Found
  @nrwl/cli : 12.0.8
  @nrwl/cypress : 12.0.8
  @nrwl/devkit : 12.0.8
  @nrwl/eslint-plugin-nx : 12.0.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.8
  @nrwl/linter : 12.0.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.0.8
  @nrwl/react : 12.0.8
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.8
  @nrwl/web : 12.0.8
  @nrwl/workspace : 12.0.8
  @nrwl/storybook : 12.0.8
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

Done in 0.55s.
```

</details>

### Related

- https://github.com/nrwl/nx/issues/5069
- https://github.com/nrwl/nx/issues/5498
- https://github.com/nrwl/nx/issues/3946
- https://github.com/nrwl/nx/pull/4330

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Unfortunately, I can't reproduce this issue. I created a workspace with 12.3.4, added the code to trigger a warning and ran `nx run-many --target=lint --projects=app1,app1-e2e --quiet` and I got the following output:
```bash
>  NX  Running target lint for 2 project(s):

  - app1-e2e
  - app1

  With flags:
    --quiet=true

———————————————————————————————————————————————

> nx run app1:lint --quiet

Linting "app1"...
Quiet mode enabled - filtering out warnings


All files pass linting.


> nx run app1-e2e:lint --quiet

Linting "app1-e2e"...
Quiet mode enabled - filtering out warnings


All files pass linting.


———————————————————————————————————————————————

>  NX   SUCCESS  Running target "lint" succeeded


✨  Done in 6.94s.
```

Could you please provide a repro?

**Comment by bbugh** [comment]
It appears that you're running `nx` as a global command. If you use `yarn nx` instead, it will exhibit the issue.

**Comment by meeroslav** [comment]
@bbugh I tried running it on the local version (I don't have global `nx` specifically to avoid such issues) and I also could not reproduce it. Do you have a minimal repo where this is reproducible?

**Comment by bbugh** [comment]
Did you specifically use `yarn nx` to run it?

**Comment by meeroslav** [comment]
Yes

**Comment by bbugh** [comment]
Roger that. I'll try to put together a minimalist repo!

**Comment by meeroslav** [comment]
Here is the minimal repo: https://github.com/meeroslav/nx-issue-6207
As you can see in the `app.tsx`, there is code that produces lint warning: https://github.com/meeroslav/nx-issue-6207/blob/main/apps/testlint/src/app/app.tsx

Running both `yarn nx lint testlint --quiet` and `yarn nx run-many --target=lint --quiet --projects=testlint` gives equal result - no warning being reported.

If you can still encounter this issue, it's most likely related to something else. Please compare your package versions with those in the https://github.com/meeroslav/nx-issue-6207/blob/main/package.json. There might be some package clash in your local repo.

Also the `run-many` command you stated is invalid, but I assume that was only typo.

If you have a repo where this can be reproduced let us know and we can reopen the issue.
