### ISSUE TITLE
ReferenceError: jasmine is not defined in generated effects test

### ISSUE THREAD

**Issue by juri-sinitson** [nrwl/nx#6227]
## Current Behavior
The generated Effect test throws `ReferenceError: jasmine is not defined`.

## Expected Behavior
The generated Effect test passes without errors, so there is no need to edit the generated tests manually to get them work (e.g. by using RxJs Marbles directly).

Is it possible/reasonable to drop Jasmine-Marbles and generate Marble-Tests with RxJs Marbles?

## Steps to Reproduce
`$ npx nx g ngrx --module=apps/my-app1/src/app/app.module.ts --minimal=false --root --directory=stores/common/entity-alt`
`$ yarn run test -test-file=entity-alt/entity.effects.spec`

### Failure Logs
`$ yarn run test --test-file=entity-alt/entity.effects.spec`

> nx run app1:test --testFile=entity-alt/entity.effects.spec 
 FAIL   app1 apps/app1/src/app/stores/common/entity-alt/entity.effects.spec.ts
  ● Test suite failed to run

    ReferenceError: jasmine is not defined

      4 | import { provideMockStore } from '@ngrx/store/testing';
      5 | import { NxModule } from '@nrwl/angular';
    > 6 | import { hot } from '@nrwl/angular/testing';
        | ^
      7 | import { Observable } from 'rxjs';
      8 |
      9 | import * as EntityActions from './entity.actions';

      at setupEnvironment (../../node_modules/jasmine-marbles/bundles/jasmine-marbles.umd.js:386:5)
      at ../../node_modules/jasmine-marbles/bundles/jasmine-marbles.umd.js:393:1
      at ../../node_modules/jasmine-marbles/bundles/jasmine-marbles.umd.js:2:65
      at Object.<anonymous> (../../node_modules/jasmine-marbles/bundles/jasmine-marbles.umd.js:5:2)
      at ../../node_modules/@nrwl/angular/bundles/nrwl-angular-testing.umd.js:2:85
      at Object.<anonymous> (../../node_modules/@nrwl/angular/bundles/nrwl-angular-testing.umd.js:5:2)
      at Object.<anonymous> (src/app/stores/common/entity-alt/entity.effects.spec.ts:6:1)
      at TestScheduler.scheduleTests (../../node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (../../node_modules/@jest/core/build/runJest.js:387:19)
      at _run10000 (../../node_modules/@jest/core/build/cli/index.js:408:7)
      at Object.runCLI (../../node_modules/@jest/core/build/cli/index.js:261:3)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        12.084 s
Ran all test suites matching /entity-alt\\entity.effects.spec/i.

### Environment

  Node : 16.4.0
  OS   : win32 x64
  yarn : 2.4.1
  
  nx : Not Found
  @nrwl/angular : 12.5.1
  @nrwl/cli : 12.5.1
  @nrwl/cypress : 12.5.1
  @nrwl/devkit : 12.5.1
  @nrwl/eslint-plugin-nx : 12.5.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.1
  @nrwl/linter : 12.5.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.1
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.1
  @nrwl/storybook : 12.5.1
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by ubergeoff** [comment]
Hi there 

I assume you are running Jest 27..?

It seems there are "new" defaults in Jest 27 (testRunner) compared to Jest 26. (As noted here: https://jestjs.io/blog/2021/05/25/jest-27)

I got the same error when migrating my project to Jest 27.

The easiest way to fix this problem is to switch back to:

```
testRunner: 'jest-jasmine2'
```
This change can be made in the `jest.preset.js` file...

**Comment by juri-sinitson** [comment]
Thanks. As you recommended, I fixed `jest.preset.js` and undid the manual changes to the generated test above. And it worked. 

Dropping Jasmine marbles is a proposition. 
The goal of this issue for me was, that generated tests work out of the box with @nrwl abstraction layer again. This goal is reached.

I will close the issue. If this issue should still be opened, let me know.
