### ISSUE TITLE
Ability to add-jest via a schematic

### ISSUE THREAD

**Issue by Nxt3** [nrwl/nx#623]
As per request in #497 

Here is how to accomplish this if you don't want to wait for nrwl to implement the feature.

https://medium.com/@nategantt/how-to-integrate-jest-with-a-nrwl-workspace-b7130041fb75

**Comment by JamesHenry** [comment]
This is actively being worked on, stay tuned! 😃

**Comment by juristr** [comment]
Any updates or timeline?

**Comment by FrozenPandaz** [comment]
The beginning of the work is in https://github.com/nrwl/nx/pull/690 ;)

**Comment by jogelin** [comment]
@FrozenPandaz Please have a look on https://github.com/meltedspark/angular-builders

**Comment by ernie58** [comment]
@FrozenPandaz I saw the PR for the JEST schematic was merged yesterday. 
Do you know when a new NPM release will happen?

**Comment by FrozenPandaz** [comment]
This is done! :fireworks:

You can now do
* `ng g jest` to configure the workspace to run Jest
* `ng g jest-project --project projectName` to add jest to a project
  * NOTE: The project must have no test configuration.
  * If you are converting existing projects, you should probably also remove karma configuration.

**Comment by arturhungrig** [comment]
@FrozenPandaz Just a quick question, regarding this sentence in your nrwl blog post:

> Jest is only available for libraries at first but will be made available for applications soon as well. 

What is an approximate timeframe one can expect jest available for apps in nx workspaces?

**Comment by FrozenPandaz** [comment]
@arturhun 
Just published a new beta which has the ability 🎉 

Give it a try and let us know if there are any issues.

Maybe expect a stable release in the coming weeks :)

**Comment by jvpepino** [comment]
Is it possible to run test for a single component? I run into issues that it cannot access import from the shared library in the repo.
