### ISSUE TITLE
When only a test is changed, builds are marked as affected

### ISSUE THREAD

**Issue by jvandemo** [nrwl/nx#6237]
## Description
When only a test is changed, builds are marked as affected.

## Suggested Implementation
When only a test is changed, builds should not be marked as affected.

## Motivation

Given 4 applications:

- app-1
- app-2
- app-3
- app-4

that all depend on the same library:

- lib-1

when making a change to one of the spec files in lib-1 (e.g. `some-file.spec.ts`), all build targets of app-1, app-2, app-3, and app-4 are marked as affected.

This causes unnecessary tasks to run (typically on CI pipelines).

Thanks in advance! 🙏

**Comment by wrslatz** [comment]
I can link some related requests

**Comment by rluvaton** [comment]
comment to keep this issue open:

this is a highly valuable feature, I can try to implement it but would need some guidance

I thought it could be implemented as part of the target inputs (this is how I first thought the inputs are for)
