### ISSUE TITLE
[Feature Request] Allow globs for file paths in implicitDependencies

### ISSUE THREAD

**Issue by SebastianSchenk** [nrwl/nx#625]
Currently, implicitDependencies only accepts fix paths to files (e.g. `"styles/scss/main.scss": "*"`).

In addition, it would be useful to accept globs as file paths in order to define multiple files at once.

**My use case:**
I have a styles folder on root level, which is used in all projects. In the current version I have to define every single file of the styles folder in `implicitDependencies`.
It would be more convenient to have something like this: `"styles/**/*.scss": "*"`

**Comment by FrozenPandaz** [comment]
A feature was added to allow projects to specify another project as an implicit dependency.

This would allow you to create a `styles` lib which is implicitly depended upon by `apps` which use it. All files in the lib would affect the apps when changed.

Now there should be less files outside of projects which would require the need for a glob.

What do you think?

**Comment by sroettering** [comment]
I would love the proposed feature as well and also for single projects/apps.
In my use case I have a monorepo with an angular frontend and java backend.
Now I would like to run my e2e tests when something changed in the backend part of the app. This is currently not possible with the `affected:e2e` command.

So glob support or even folder support would be greatly appreciated.

**Comment by sroettering** [comment]
This issue was opened quite a while ago. Any decisions on this?

**Comment by conor-mac-aoidh** [comment]
This would be a very useful feature.

**Comment by SebastianSchenk** [comment]
I think this is still a valid feature request which could be quite useful

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.
This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.
