### ISSUE TITLE
generate @nrwl/angular:application -> Expected apps/apps/myapp/tsconfig.json to exist. Please create one.

### ISSUE THREAD

**Issue by marekwalach** [nrwl/nx#6251]
## Current Behavior
When I run command:
`nx generate @nrwl/angular:application --name=myapp --style=scss --e2eTestRunner=none --linter=eslint --prefix=myapp --routing --strict --unitTestRunner=jest`
i got this error:
`Expected apps/apps/myapp/tsconfig.json to exist. Please create one.`

This project was created with nx 7 and upgraded every new release and now when I upgraded to 12.5 I noticed this behavior. I haven't used this command for a while now so it could broke earlier. When I create totally new project with nx I do not have such problems so it could be something inside my project files but I can't find the reason.

## Expected Behavior
To have angular application created.

### Failure Logs
`Expected apps/apps/myapp/tsconfig.json to exist. Please create one.`

### Environment
` Node : 14.17.2
  OS   : darwin x64
  npm  : 6.14.13
  
  nx : Not Found
  @nrwl/angular : 12.5.1
  @nrwl/cli : 12.5.1
  @nrwl/cypress : 12.5.1
  @nrwl/devkit : 12.5.1
  @nrwl/eslint-plugin-nx : 12.5.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.1
  @nrwl/linter : 12.5.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.1
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.1
  @nrwl/storybook : 12.5.1
  @nrwl/gatsby : Not Found
  typescript : 4.2.4`

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Could you please provide a reproduction?

**Comment by marekwalach** [comment]
This is a problem. When I create new project with the same dependencies it works just find. Only on my work project I have this issue. It would be nice if you could show me where should I look to find problem so I can try.

**Comment by st-little** [comment]
is there any news on this?

**Comment by AhsanAyaz** [comment]
@dandouglas that helped. Thanks 👍🏼 
Would be nice to have this fixed by the team.
