### ISSUE TITLE
Replace "enableIvy": false with "compilationMode": "partial"

### ISSUE THREAD

**Issue by bjornharvold** [nrwl/nx#6259]
Hi Team Nx!

## Description
We are working with a large Angular 12 monorepo POWERED BY NX. When I create new Angular libraries I use a command like this:
`nx g @nrwl/angular:lib util-abstract-control-promoter-pipe --buildable --directory shared`

This command creates a tsconfig.lib.prod.json that has Ivy disabled by default. I want to request that with Angular 12, it enables Ivy by default; just like Angular does it.

## Motivation
It's easier to tell a bunch of developers to use the default settings instead of telling them to modify every tsconfig.lib.prod.json for every new library they create.

## Suggested Implementation
If project is an Angular 12 project, enable Ivy by default.

```
Node : 12.22.2
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 12.5.1
  @nrwl/cli : 12.5.1
  @nrwl/cypress : 12.5.1
  @nrwl/devkit : 12.5.1
  @nrwl/eslint-plugin-nx : 12.5.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.1
  @nrwl/linter : 12.5.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.1
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.1
  @nrwl/storybook : 12.5.1
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by gerardcastell** [comment]
This feature is quite necessary!

**Comment by Coly010** [comment]
@bjornharvold Can you try this again with latest Nx?

**Comment by bjornharvold** [comment]
Works since a while back. 🍻

**Comment by Coly010** [comment]
Awesome! In that case I'll close this issue :)
