### ISSUE TITLE
Lint checks silently fail when npmScope is not defined.

### ISSUE THREAD

**Issue by ThomasBurleson** [nrwl/nx#626]
If the `npmScope` is not set or not correct:

```json
     "nx-enforce-module-boundaries": [    true ]
```

then the `npm run lint` will not detect  deep imports into libs.                                                       

should be:

```
    "nx-enforce-module-boundaries": [
      true,
      {
        "npmScope": "sd-portal",
        "lazyLoad": [],
        "allow": []
      }
    ]
```

**Comment by JamesHenry** [comment]
We should probably throw if required info is missing in the rule config

**Comment by FrozenPandaz** [comment]
This information should actually be in the `nx.json`, some warning would be useful in the rule config which says to define it in `nx.json`.

**Comment by bcabanes** [comment]
Most likely here https://github.com/nrwl/nx/blob/master/packages/schematics/src/tslint/nxEnforceModuleBoundariesRule.ts

**Comment by FrozenPandaz** [comment]
This is a really old issue so I'm not sure when this was fixed.. but there's an error now 🎉

```bash
Jasons-MacBook-Pro:nx-examples jason$ yarn lint
yarn run v1.19.0
$ nx workspace-lint && ng lint
/Users/jason/projects/nx-examples/node_modules/@nrwl/workspace/node_modules/yargs/yargs.js:1133
      else throw err
           ^

Error: nx.json must define the npmScope property.
    at Object.readNxJson (/Users/jason/projects/nx-examples/node_modules/@nrwl/workspace/src/command-line/shared.js:272:15)
```
