### ISSUE TITLE
NX Extensions Fail When Workspace is not at root of repository

### ISSUE THREAD

**Issue by Murtha97** [nrwl/nx#627]
We have an workspace located under a subfolder in our git repository. When running affected:* scripts no apps or changes would be located due to the following problem.

git diff --name-only returned a different file root than the angular.json, which causes the following method to fail.
```
function directlyTouchedProjects(projects, touchedFiles) {
    return projects
        .filter(function (project) {
        return touchedFiles.some(function (file) {
            //file comes from git diff command, the project path comes from angular json,
            // only works if your repo is at the same level as the workspace.
            return file.startsWith(project.root);  
        });
    })
        .map(function (project) { return project.name; });
}
```

**Comment by JamesHenry** [comment]
Thanks @Murtha97 and @domkrel! I am going to close this as it is a duplicate
