### ISSUE TITLE
configFilePath ending up in project.json files on disk

### ISSUE THREAD

**Issue by JamesHenry** [nrwl/nx#6272]
## Steps to Reproduce

- In order to reproduce you first need to follow the reproduction for this bug: https://github.com/nrwl/nx/issues/6271

- _...Once you have reached the final step outlined on that issue resume here..._

At this point you will see that `"configFilePath"` exists in the project config within the `workspace.json`/`angular.json`. Now if you clean up the `project.json` files (which was a logical action given the above linked bug had moved all the config back into workspace.json) and rerun the conversion, `configFilePath` will end up in your new `project.json` files.

i.e. simply run the following on top of the commands outlined in the above linked issue:

- `rm -rf **/project.json`
- `npx ng g @nrwl/workspace:convert-to-nx-project --all`

**Comment by JamesHenry** [comment]
@AgentEnder Hope you don't mind, I saw you grabbed the other one already so assigned this one to you too!

**Comment by AgentEnder** [comment]
Yeah, these are likely one in the same.

**Comment by AgentEnder** [comment]
Closed by #6276
