### ISSUE TITLE
@nrwl/workspace:run-commands argument without value converted to `arg=true`

### ISSUE THREAD

**Issue by unlight** [nrwl/nx#6278]
## Current Behavior
Unexpected convert of forwarded argument `--arg` to `--arg=true`

## Expected Behavior
Arguments should be forwarded as is

## Steps to Reproduce
1. Generate workspace `npx create-nx-workspace@latest`
2. Add to `workspace.json` to default project section
```
        "echo1": {
          "executor": "@nrwl/workspace:run-commands",
          "options": {
            "parallel": false,
            "commands": ["echo 1"]
          }
        }
```

3. Run `nx run project:echo1 --watch`
Result: `1 --watch=true`
Expected: `1 --watch`

4. Run `nx run project:echo1 --watch --no-watch`
Result: `1 --watch=true,false`
Expected: `1 --watch --no-watch`

### Environment
```
  Node : 14.15.4
  OS   : win32 x64
  npm  : 7.6.1

  nx : 12.5.7
  @nrwl/angular : Not Found
  @nrwl/cli : 12.5.2
  @nrwl/cypress : 12.5.2
  @nrwl/devkit : 12.5.2
  @nrwl/eslint-plugin-nx : 12.5.2
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.2
  @nrwl/linter : 12.5.2
  @nrwl/nest : 12.5.2
  @nrwl/next : Not Found
  @nrwl/node : 12.5.2
  @nrwl/react : 12.5.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.2
  @nrwl/web : 12.5.2
  @nrwl/workspace : 12.5.2
  @nrwl/storybook : 12.5.2
  @nrwl/gatsby : Not Found
  typescript : 4.3.4
```

**Comment by gtwebsite** [comment]
hope this gets resolved soon. :(

**Comment by edgehero** [comment]
how to solve this bug? is there a workaround?
