### ISSUE TITLE
Adding NX to existing CLI project -> 'options' of undefined

### ISSUE THREAD

**Issue by thorgod** [nrwl/nx#628]
Running the command `ng add @nrwl/schematics` to a existing CLI created project throwing a error.
I was able to create a new `nx workspace` just fine, but adding to existing `Angular CLI` project I am getting the error bellow.

```
>ng add @nrwl/schematics
Installing packages for tooling via yarn.
yarn add v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible wiinfo "fsevents@1.2.4" is an optional dependency and failed c[3/4] Linking dependencies...
warning " > @nrwl/nx@6.1.0" has unmet peer dependency "jasmiwarning " > ng2-daterangepicker@2.0.12" has unmet peer depen[4/4] Building fresh packages...
success Saved lockfile.
success Saved 2 new dependencies.
├─ @nrwl/nx@6.1.0
└─ @nrwl/schematics@6.1.0
Done in 151.80s.
Installed packages for tooling via yarn.
Cannot read property 'options' of undefined 

```

Node: 8.11.3
Angular-CLI: ^6.0.8
@nrwl/nx: "^6.1.0"
@nrwl/schematic": "^6.1.0"

**Comment by JamesHenry** [comment]
What OS are you running? Looks like windows?

**Comment by thorgod** [comment]
Windows 7.
It could of been because I had malformed package.json  
```
    "ts-node": "^7.0.0",
    "tslint": "^5.11.0",  //<< Extra comma at the end
  }
```
However, I will close this issue. I will be using the new Angular CLI that can control multiple projects instead.

**Comment by dodongphure** [comment]
I tried to add workspace to existing project, but got the error:
```
angular.json already exists
package.json already exists
etc
...
```
Seem can not add workspace to existing angular cli project right?

**Comment by dodongphure** [comment]
In my case when using `ng add @nrwl/schematics`, at the step `What is the npm scope you would like to use for your Nx Workspace?`, I typed some name but got the error:
> Path must be a string. Received undefined

Any idea for this. Thanks?
