### ISSUE TITLE
nx dep-graph not generating graph

### ISSUE THREAD

**Issue by djbreen7** [nrwl/nx#6280]
## Current Behavior

The graph is served to http://127.0.0.1:4211, but no graph is visible.

## Expected Behavior

`nx dep-graph` should generate or use the files it needs in order to display the dependency graph

## Steps to Reproduce

1. `npx nx create-nx-workspace deps-repro`
2. Answer prompts:
    ```
    √ What to create in the new workspace · angular
    √ Application name                    · admin
    √ Default stylesheet format           · scss
    √ Use Nx Cloud? (It's free and doesn't require registration.) · No
    ```
3. `cd deps-repro`
4. ` ng generate @nrwl/angular:library --name=test-lib`
5. Add `import { TestLibModule } from '@deps-repro/test-lib'` to `app.module.ts`
6. `nx dep-graph`

**Repo that reproduces error:**
https://github.com/djbreen7/deps-repro

### Failure Logs

**Browser Console Errors:**
```
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught (in promise) SyntaxError: Unexpected token F in JSON at position 0
```

**Browser Network Errors:**
```
File C:\code\deps-repro\node_modules\@nrwl\workspace\src\core\dep-graph\projectGraph.json not found!
```

### Environment

```
  Node : 14.16.1
  OS   : win32 x64
  npm  : 6.14.12

  nx : Not Found
  @nrwl/angular : 12.5.7
  @nrwl/cli : 12.5.7
  @nrwl/cypress : 12.5.7
  @nrwl/devkit : 12.5.7
  @nrwl/eslint-plugin-nx : 12.5.7
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.7
  @nrwl/linter : 12.5.7
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.7
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.7
  @nrwl/storybook : 12.5.7
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
  ```

**Comment by Poccomaxazt** [comment]
I guess I was facing the same issue with 12.5. It's related to Win OS and path to files:

node_modules/@nrwl/workspace/src/command-line/dep-graph.js
**if (sanitizePath === '/projectGraph.json') {**

But our result is **'\projectGraph.json'**.

**Comment by djbreen7** [comment]
@Poccomaxazt good find! Sounds like you understand a little about what's going on under the hood. Is this just looking for the json, or creating it?

If its creating it, then that would explain while the file truly isn't there.

![image](https://user-images.githubusercontent.com/13296622/124793854-a3c28280-df0b-11eb-9715-a2931fb292e4.png)

**Comment by Poccomaxazt** [comment]
NX doesn't create real file. It generates graph JSON on the fly when local server requests file with concrete path
```
  if (sanitizePath === '/projectGraph.json') {
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify(currentDepGraphClientResponse));
      return;
  }
```
The main problem that it compares path with symbol **/**, but on the Win OS it equal **\**.

**Comment by djbreen7** [comment]
@Poccomaxazt sounds like a job for `path`. I'll take a closer look.

**Comment by djbreen7** [comment]
Opened that PR ☝️ with `path.basename()` instead of regex. Not sure what vercel's deal is, but hopefully someone will let me know if there's an issue. Otherwise, all the tests are passing.
