### ISSUE TITLE
Call multiple generators inside a generator

### ISSUE THREAD

**Issue by hadrien-toma** [nrwl/nx#6285]
## Description

Based on the following example (source [here](https://github.com/nrwl/nx/issues/4737#issuecomment-775269877)), it seems not possible to call multiple generators inside a generator.

```ts
import { Tree, readProjectConfiguration } from '@nrwl/devkit';
import { join } from 'path';
import { libraryGenerator } from '@nrwl/angular/generators'; // This will be available in 11.3.0.

interface Options { ... }
export default function(tree: Tree, options: Options) {
  // Generate a lib
  const installTask = await libraryGenerator(tree, {
    ...options,
  });
  // Get the library configuration
  const lib = readProjectConfiguration(tree, options.name);
  const root = lib.root;
  updateJson(tree, join(root, '.eslintrc.json'), value => {
    /* Update ESLint file */
    return value;
  });
  return installTask;
}
```

## Motivation

My application generator will always create a lazy loaded route so in my application generator I need to use

- applicationGenerator to create the application
- libraryGenerator to create the above-mentioned lazy loaded route

## Suggested Implementation

I would be happy to be able to use something like:

```ts
import { Tree, readProjectConfiguration } from '@nrwl/devkit';
import { join } from 'path';
import { applicationGenerator, libraryGenerator } from '@nrwl/angular/generators'; // This will be available in 11.3.0.

interface Options { ... }
export default function(tree: Tree, options: Options) {
  // Generate a lib
  const applicationInstallTask = await applicationGenerator(tree, {
    ...options,
  });
  const libraryInstallTask = await libraryGenerator(tree, {
    ...options,
  });
  // Get the library configuration
  const lib = readProjectConfiguration(tree, options.name);
  const root = lib.root;
  updateJson(tree, join(root, '.eslintrc.json'), value => {
    /* Update ESLint file */
    return value;
  });
  return [applicationInstallTask, libraryInstallTask];
}
```

**Comment by AgentEnder** [comment]
The only part of this not currently possible is returning the array of tasks. In this case, both tasks in the array actually do the same thing (invoking `npm i`, `yarn` etc). The actual package.json modifications are handled within the generators, not the returned tasks.

As such, you should only need to return one of them. That being said, if you needed both of them to be called in a different case, your return could look something like this:

```typescript
import { Tree, formatFiles, installPackagesTask } from '@nrwl/devkit';
import {applicationGenerator, libraryGenerator} from '@nrwl/angular/generators';

export default async function(tree: Tree, options: any) {
  // Generate a lib
  const applicationInstallTask = await applicationGenerator(tree, {
    ...options,
  });
  const libraryInstallTask = await libraryGenerator(tree, {
    ...options,
    name: options.name + '-lib',
  });
  
  return () => Promise.all([applicationInstallTask, libraryInstallTask]);
}
```

Does this address the feature request, or is there a situation that is not covered by this?

**Comment by hadrien-toma** [comment]
Thank you very much for the explanation @AgentEnder :pray:. This perfectly addresses the feature request :heart_eyes: !
