### ISSUE TITLE
feat(ngrx): support ngrx-data and ngrx-entity

### ISSUE THREAD

**Issue by ThomasBurleson** [nrwl/nx#630]
Both are relatively new features within the NgRx platform. These libraries provide elegant support for collections of data with minimal boilerplate scaffolding needed.

**Comment by bkooistra** [comment]
Hi Thomas, this feature would be great to have. When could we expect this? And what is the best way to add right now / for the time being? Can I just create a new library, add ngrx data and import export via ngModule or am I missing some best practices this way?

**Comment by ccpony** [comment]
+1

**Comment by brandonroberts** [comment]
Out of the box support for `@ngrx/entity` was added with `Nx 8.3`, and `@ngrx/data` can be added manually if needed using the ngrx docs https://ngrx.io/guide/data/install.
