### ISSUE TITLE
on recompile/reload my base route is duplicated

### ISSUE THREAD

**Issue by webmandman** [nrwl/nx#6307]
## Current Behavior
When I make changes to my angular ts files the browser to reloads my app adding my base route after the existing base route. 
URI: /profile ----> code change/save ----> recompile ----> browser reloads app, and URI is now: /profile/profile

## Expected Behavior
When I make changes to my angular ts files I expect the browser to reload once its done recompiling without the URI to change. 

## Steps to Reproduce
I can't reproduce the issue in a new NX workspace angular app, or in the Nx Examples. Believe me I tried. I want to provide a reproduceable issue with a repo you can try but I can't for the life of me figure it out. I have compared and reviewed all my code to see what would cause such a thing and I don't see anything. 

My routes configuration in my base app.module.ts is:
`const routes: Routes = [
  { path: 'profile',
    loadChildren: () =>
      import(`./profile/profile.module`).then(m => m.ProfileModule)
  },
  { path: '**', redirectTo: 'profile', pathMatch: 'full' }
];
`

My profile (lazy loaded)module routes is:
`const profileRoutes: Routes = [
  { path: '', component: ProfileComponent },
  { path: 'address', component: AddressComponent },
  { path: 'phone', component: PhoneComponent },
  { path: 'photo', component: PhotoComponent },
  { path: 'password', component: PasswordComponent }
];
`

### Environment
Node : 14.11.0
  OS   : win32 x64
  npm  : 6.14.8

  nx : Not Found
  @nrwl/angular : 12.0.8
  @nrwl/cli : 12.0.8
  @nrwl/cypress : 12.0.8
  @nrwl/devkit : 12.0.8
  @nrwl/eslint-plugin-nx : 12.0.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.8
  @nrwl/linter : 12.0.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.8
  @nrwl/web : Not Found
  @nrwl/workspace : 12.0.8
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.4

**Comment by webmandman** [comment]
this angular app when it was not in an nx workspace was not doing this. so thats why I'm here for help.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Looking at the routes config you shared, they seem fine to me. Unfortunately, we don't have enough information, we are going to need a reproduction so we can help to troubleshoot it.

**Comment by webmandman** [comment]
I guess you can close this. I can't reproduce it. So I'm going to go the route of starting a new nx workpsace from scratch then add my one app and several libs. I'm hoping this issue is just non existing in the new workspace.
