### ISSUE TITLE
Workspace Move generator modifies library .eslintrc.json

### ISSUE THREAD

**Issue by piet-v** [nrwl/nx#6314]
## Current Behavior
Using the workspace:move generator to move a react library modifes the library's .eslintrc.json which results in the line
`"extends": ["plugin:@nrwl/nx/react", "../../../../.eslintrc.json"],`
turning into
`"extends": "../../../../.eslintrc.json",`
which results into eslint errors

## Expected Behavior
The .eslintrc.json should not be modified

## Steps to Reproduce
* use react workspace generator to create a library
* use workspace:move generator to move the library

### Environment
Node : 12.14.1
OS : darwin x64
npm : 6.14.11

nx : Not Found
@nrwl/angular : Not Found
@nrwl/cli : 12.5.7
@nrwl/cypress : 12.5.7
@nrwl/devkit : 12.5.7
@nrwl/eslint-plugin-nx : 12.5.7
@nrwl/express : Not Found
@nrwl/jest : 12.5.7
@nrwl/linter : 12.5.7
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/react : 12.5.7
@nrwl/schematics : Not Found
@nrwl/tao : 12.5.7
@nrwl/web : 12.5.7
@nrwl/workspace : 12.5.7
@nrwl/storybook : 12.5.7
@nrwl/gatsby : Not Found
typescript : 4.1.4

**Comment by meeroslav** [comment]
Thank you @piet-v! The fix is on the way
