### ISSUE TITLE
Can't build library that uses private fields

### ISSUE THREAD

**Issue by pstepniewskiconfigit** [nrwl/nx#6317]
## Current Behavior
UMD package isn't build. Only ESM one is available,.
![image](https://user-images.githubusercontent.com/75308464/125097158-c5814e00-e060-11eb-9f8e-87fed5912f78.png)

## Expected Behavior

Build ESM and UMD package for library. Also to be able to set target to ES2015 or ES2018 or respect target from `tsconfig.json`

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.
Create and export some class using private fields inside library.

### Failure Logs

![image](https://user-images.githubusercontent.com/75308464/125097158-c5814e00-e060-11eb-9f8e-87fed5912f78.png)

### Environment

```
  Node : 16.1.0
  OS   : win32 x64
  npm  : 7.19.0

  @nrwl/nx : 12.5.1
  @nrwl/cli : 12.5.1
  @nrwl/cypress : 12.5.1
  @nrwl/devkit : 12.5.1
  @nrwl/eslint-plugin-nx : 12.5.1
  @nrwl/jest : 12.5.1
  @nrwl/linter : 12.5.1
  @nrwl/react : 12.5.1
  @nrwl/tao : 12.5.1
  @nrwl/web : 12.5.1
  @nrwl/workspace : 12.5.1
  @nrwl/storybook : 12.5.1
  typescript : 4.3.5
```

**Comment by FrozenPandaz** [comment]
Are you using [Typescript private properties](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#ecmascript-private-fields) or [Javascript private fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields)?

Please provide a repo that will make it easier to reproduce the issue.

**Comment by pstepniewskiconfigit** [comment]
Link to repo: https://github.com/pstepniewskiconfigit/nx-lib-private-fields
@FrozenPandaz also worth to mention is that output generated by build is bloated compared to what TypeScript Compiler will output.

**Comment by pstepniewskiconfigit** [comment]
No it's still active.

**Comment by pstepniewskiconfigit** [comment]
@vsavkin @FrozenPandaz any update on that one?
