### ISSUE TITLE
doc(ngrx): update "setting up ngrx" guidelines

### ISSUE THREAD

**Issue by ThomasBurleson** [nrwl/nx#632]
The online [Guide to setting up NgRx](docs at https://nrwl.io/nx/guide-setting-up-ngrx) should be updated to match the latest code fixes in PR #631 and PR #474.

**Comment by bcabanes** [comment]
Hi!

Updates on the [nrwl.io/nx/guide-setting-up-ngrx](https://nrwl.io/nx/guide-setting-up-ngrx) has been done.

Closing.
