### ISSUE TITLE
ReferenceError: jasmine is not defined

### ISSUE THREAD

**Issue by awaissaeed530** [nrwl/nx#6327]
## Current Behavior
I generated ngrx feature state with @nrwl/angular:ngrx. I have made no changes to any of the generated files with but running generated tests produces this error.
`ReferenceError: jasmine is not defined`

Here is complete error log

     FAIL   inventory-feature-product  libs/inventory/feature-product/src/lib/+state/products.effects.spec.ts
    ● Test suite failed to run

    ReferenceError: jasmine is not defined

      4 | import { provideMockStore } from '@ngrx/store/testing';
      5 | import { NxModule } from '@nrwl/angular';
    > 6 | import { hot } from '@nrwl/angular/testing';
        | ^
      7 | import { Observable } from 'rxjs';
      8 |
      9 | import * as ProductsActions from './products.actions';

      at setupEnvironment (../../../node_modules/jasmine-marbles/bundles/jasmine-marbles.umd.js:386:5)
      at ../../../node_modules/jasmine-marbles/bundles/jasmine-marbles.umd.js:393:1
      at ../../../node_modules/jasmine-marbles/bundles/jasmine-marbles.umd.js:2:65
      at Object.<anonymous> (../../../node_modules/jasmine-marbles/bundles/jasmine-marbles.umd.js:5:2)
      at ../../../node_modules/@nrwl/angular/bundles/nrwl-angular-testing.umd.js:2:85
      at Object.<anonymous> (../../../node_modules/@nrwl/angular/bundles/nrwl-angular-testing.umd.js:5:2)
      at Object.<anonymous> (src/lib/+state/products.effects.spec.ts:6:1)

     FAIL   inventory-feature-product  libs/inventory/feature-product/src/lib/+state/products.facade.spec.ts
    ● Test suite failed to run

    ReferenceError: jasmine is not defined

      4 | import { Store, StoreModule } from '@ngrx/store';
      5 | import { NxModule } from '@nrwl/angular';
    > 6 | import { readFirst } from '@nrwl/angular/testing';
        | ^
      7 | import * as ProductsActions from './products.actions';
      8 | import { ProductsEffects } from './products.effects';
      9 | import { ProductsFacade } from './products.facade';

      at setupEnvironment (../../../node_modules/jasmine-marbles/bundles/jasmine-marbles.umd.js:386:5)
      at ../../../node_modules/jasmine-marbles/bundles/jasmine-marbles.umd.js:393:1
      at ../../../node_modules/jasmine-marbles/bundles/jasmine-marbles.umd.js:2:65
      at Object.<anonymous> (../../../node_modules/jasmine-marbles/bundles/jasmine-marbles.umd.js:5:2)
      at ../../../node_modules/@nrwl/angular/bundles/nrwl-angular-testing.umd.js:2:85
      at Object.<anonymous> (../../../node_modules/@nrwl/angular/bundles/nrwl-angular-testing.umd.js:5:2)
      at Object.<anonymous> (src/lib/+state/products.facade.spec.ts:6:1)`

## Steps to Reproduce
Generate a new nx workspace with an Angular project. Genrate a feature state with @nrwl/angular:ngrx schematic and then run test.

### Environment
  nx : Not Found
  @nrwl/angular : 12.5.7
  @nrwl/cli : 12.5.7
  @nrwl/cypress : 12.5.7
  @nrwl/devkit : 12.5.7
  @nrwl/eslint-plugin-nx : 12.5.7
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.7
  @nrwl/linter : 12.5.7
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.7
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.7
  @nrwl/storybook : 12.5.7
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by ubergeoff** [comment]
Hi there

Have you tried the solution here:

https://github.com/nrwl/nx/issues/6227
