### ISSUE TITLE
nx generate cypress-project fails

### ISSUE THREAD

**Issue by rogerfar** [nrwl/nx#6328]
I'm trying to run `nx generate cypress-project` according to this doc: https://nx.dev/latest/react/storybook/cypress-project

I want to add a 2nd e2e project to test a library specifically (because it relies on the browser SDK).

But when I run the command it gives the error: 
```
Unable to resolve @nrwl/react:cypress-project.
Cannot find generator 'cypress-project' in client\node_modules\@nrwl\react\collection.json.
```

Was this functionality removed? I can't find any docs about how to create an e2e cypress library.

**Comment by FrozenPandaz** [comment]
Please try running `nx g @nrwl/storybook:cypress-project` as suggested by the docs.
