### ISSUE TITLE
"nx affected:lint --base develop --quiet" ignores the --quiet option

### ISSUE THREAD

**Issue by ed4becky** [nrwl/nx#6331]
## Current Behavior
When I run nx affected:lint with the --quit option, the option is ignored and warnings are displayed in the output

## Expected Behavior
I expect running affected respects any flags passed to it.

## Steps to Reproduce
In a workspace with multiple projects, execute "nx affected:lint --base develop --quiet"

### Failure Logs
 >nx affected:lint --base develop --quiet
...
>  NX  Running target lint for projects:
...
> nx run page-posture-checks:lint [retrieved from cache]

Linting "page-posture-checks"...

D:\Users\ed\IdeaProjects\WebstormProjects\netfoundry-ui\libs\page\posture-checks\src\lib\posture-checks.component.ts
  290:18  warning  'data' is defined but never used   @typescript-eslint/no-unused-vars
  295:18  warning  'error' is defined but never used  @typescript-eslint/no-unused-vars
  428:14  warning  'error' is defined but never used  @typescript-eslint/no-unused-vars
  556:22  warning  'event' is defined but never used  @typescript-eslint/no-unused-vars

✖ 4 problems (0 errors, 4 warnings)

### Environment

  Node : 14.17.0
  OS   : win32 x64
  npm  : 7.17.0

  nx : Not Found
  @nrwl/angular : 11.6.3
  @nrwl/cli : 11.6.3
  @nrwl/cypress : 11.6.3
  @nrwl/devkit : 11.6.3
  @nrwl/eslint-plugin-nx : 11.6.3
  @nrwl/express : Not Found
  @nrwl/jest : 11.6.3
  @nrwl/linter : 11.6.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.6.3
  @nrwl/web : Not Found
  @nrwl/workspace : 11.6.3
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.5

**Comment by FrozenPandaz** [comment]
This has been fixed in Nx 12.2.0 with https://github.com/nrwl/nx/commit/8d24bb01a009cd8f84da33659a320c059e67ed8e. Can you upgrade?

Next time we cut a patch version, we can look into backporting this but this is fixed in the latest version of Nx.

**Comment by ed4becky** [comment]
Thank you
