### ISSUE TITLE
Ability to call ng add and app-shell schematics in a generator

### ISSUE THREAD

**Issue by Jad31** [nrwl/nx#6338]
## Description
I want to be able to create generators that can create an app-shell, configure the pwa and configure angular material.
I want to call those external schematics: `yarn run nx generate @angular/pwa:ng-add`, `yarn run nx generate app-shell` and ` yarn run nx generate @angular/material:ng-add`

## Motivation

- Increase the level of crafting provided by Nx and enhance developer experience
- Being able to generate an application directly configuring Angular material, being a pwa and having an app shell

## Suggested Implementation
Maybe have a function like the `applicationGenerator` from `'@nrwl/angular/generators'` but it would be `appShellGenerator` for the app-shell configuration, `pwaGenerator` for the pwa configuration and `materialGenerator` for Angular material.

## Related Issues

- #5783 
- #3779

**Comment by hadrien-toma** [comment]
I am also very interested in this feature, thank you @Jad31 for submitting it!

Maybe @DominikPieper has any idea about how we can achieve it ? In any case, Dominik thank you again for the help you provided last time, I really appreciated it :pray: :heart:

**Comment by DominikPieper** [comment]
@hadrien-toma Thank you, you're welcome :-)

For the problem @Jad31:
I don't think there will be official generators, cause it would be hard to do that for every angular schematic.
For your workspace-schematics it should be possible to use the "wrapAngularDevkitSchematic" function. That function will return a generator from the given schematic. 

```ts
import { Tree, formatFiles } from '@nrwl/devkit';
import { runTasksInSerial } from '@nrwl/workspace/src/utilities/run-tasks-in-serial';
import { wrapAngularDevkitSchematic } from '@nrwl/devkit/ngcli-adapter';

export default async function (host: Tree, schema: any) {
  const pwaGenerator = wrapAngularDevkitSchematic(
    '@angular/pwa',
    'ng-add'
  )
  const pwalTask = await pwaGenerator(host, { project: schema.project });
  
  await formatFiles(host);
  return runTasksInSerial(pwalTask); // runTasksInSerial if you need multiple tasks
}

```

In a small test, this works with the PWA schematic but not for the material one. I'm not sure why but I just tested it really quick

**Comment by FrozenPandaz** [comment]
Thanks for the help @DominikPieper! Yes, that is the way to call an Angular Schematic from a generator.

It is also documented here: https://nx.dev/latest/angular/generators/composing-generators#using-angular-devkit-schematics

Closing this issue as the feature already exists.
