### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by anilsbidve** [nrwl/nx#634]
Hi Team,

On this page https://nrwl.io/nx/guide-nx-workspace.

After this line 
This will create a new lib, will place it in the libs directory, and will configure the angular.json and nx.json files to support the new lib.

Line - Run ng generate app --help to see the list of available options:
Should replace with - Run ng generate **lib** --help to see the list of available options:

Thanks.

Regards,
Anil Bidve

**Comment by anilsbidve** [comment]
One more thing on the same page for below line
npm run affected:dep-graph -- --base=[SHA1] --base=[SHA2]
extra -- should be remove which is after :dep-graph

**Comment by anilsbidve** [comment]
Just search npm run affected:dep-graph -- --
You will find more places.

**Comment by anilsbidve** [comment]
npm run affected:build -- --
The above one as well.

**Comment by anilsbidve** [comment]
npm run affected:test -- --
npm run affected:e2e -- --

Fix in above two as well.

**Comment by anilsbidve** [comment]
npm run format:write -- --
Fix this above one as well.

On below line 
Check out the [Workspace-Specific Schematics](/nx/workspace-specific schematics) guide to learn more.
Link is not correctly added,

**Comment by marcorinck** [comment]
Can I add something here? 

On this page after adding a data-access-schematic, the guide contains this line: 

````
Finally, invoke it to generate a new data-access lib.
```` 

I'm completely new to schematics and nx and didn't knew what I should do, the corresponding image didn't contain the command how to invoke it either. I only found it in one of the pull requests:

````
npm run workspace-schematic data-access-lib data-access-users 
````  

This should be added to the guide.

**Comment by ThomasBurleson** [comment]
@here - Here is a Gist [Guide to Custom Nx Workspace Schematics](https://gist.github.com/ThomasBurleson/30e45a6bc61f0d53fe07045d69b548e6). We will use this to:

* update the online docs
* update the workspace schematics template to support `--directory` options

**Comment by bcabanes** [comment]
Closing since the documentation is now part of the repository and has been rewritten. The documentation is also accessible via https://nx.dev.
