### ISSUE TITLE
Having issue with react-native-paper in react-native-web platform

### ISSUE THREAD

**Issue by somitBond** [nrwl/nx#6340]
I have followed react native paper documentation for User on the Web.
When I try to serve it gave me an error
![err-1](https://user-images.githubusercontent.com/3232739/125388029-8172ae00-e3be-11eb-84c7-5936d21a0413.PNG)
![err-5](https://user-images.githubusercontent.com/3232739/125388036-82a3db00-e3be-11eb-8ce3-f954f8733452.PNG)

**Comment by FrozenPandaz** [comment]
Please provide a repo to make it easier to reproduce the issue.

**Comment by somitBond** [comment]
Thank you for reply @FrozenPandaz 
Here is the repo: https://github.com/somitBond/rnwnp

https://callstack.github.io/react-native-paper/using-on-the-web.html

**Comment by arjdesign** [comment]
I also had same issue!!
