### ISSUE TITLE
React-App production build only injects script tags with type="module" (after Upgrade @nrwl/* > 12.3.6)

### ISSUE THREAD

**Issue by sbeugen** [nrwl/nx#6341]
As written in the title, our production build of a React-App with the default nx webpack build produces a `index.html` with the resulting JS-Files in script tags, but with the attribute `type="module"`. With this attribute our App is not working in IE11 any more.

![image](https://user-images.githubusercontent.com/14964195/125409711-76b71980-e3bc-11eb-831b-7cba816cd349.png)

I was able to identify the commit, which introduced the adding of the attribute. In that commit we upgraded all `@nrwl` packages from `12.1.1` to `12.3.6`. Higher versions still have the same issue. Before the upgrade the script tags only had the attribute `defer`.
![image](https://user-images.githubusercontent.com/14964195/125410109-dca3a100-e3bc-11eb-9c6a-ee8fabdf71a1.png)

The used build-command is: `NODE_ENV=production nx run-many --target=build --all --baseHref="./"`
The development build still injects the script tags without the type attirbute.

Except the version upgrade, nothing else has changed in that commit. 
Our `.browserslistrc` looks like this:
```
last 1 Chrome version
last 1 Firefox version
last 2 Edge major versions
last 2 Safari major version
last 2 iOS major versions
Firefox ESR
IE 11
```

**Comment by Anenth** [comment]
@jaysoo  I am also having the same issue, were you able to fix a fix?
