### ISSUE TITLE
workspace generators + project generation + wrapAngularDevkitSchematic = incompatible

### ISSUE THREAD

**Issue by JamesHenry** [nrwl/nx#6342]
## Current Behavior

It is not possible to create workspace generators which create projects and update them within the same run, if that update is coming via a wrapped schematic and the workspace is leveraging distributed configuration (`project.json`).

## Expected Behavior

Leveraging `project.json` instead of centralized `workspace.json` should not have any impact on workspace generators.

## Steps to Reproduce

Create a workspace generator which attempts to create a new component library _and_ a component within it:

```ts
import { strings } from "@angular-devkit/core";
import { libraryGenerator } from "@nrwl/angular/generators";
import { UnitTestRunner } from "@nrwl/angular/src/utils/test-runners";
import { normalizePath, Tree } from "@nrwl/devkit";
import { Linter } from "@nrwl/linter";
import { wrapAngularDevkitSchematic } from "@nrwl/tao/src/commands/ngcli-adapter";
import { join } from "path";

interface Schema {
  name: string;
}

export default async function (tree: Tree, options: Schema) {
  const { name } = options;
  const sharedComponentsDir = "shared/components";

  await libraryGenerator(tree, {
    name,
    directory: sharedComponentsDir,
    strict: true,
    linter: Linter.EsLint,
    unitTestRunner: UnitTestRunner.Jest,
    standaloneConfig: true, // <------------------------- key config for repro, use project.json
  });

  const createdProjectName = normalizePath(
    join(sharedComponentsDir, strings.dasherize(name))
  ).replace(/\//g, "-");

  const schematicsAngularComponentGenerator = wrapAngularDevkitSchematic(
    "@schematics/angular",
    "component"
  );
  await schematicsAngularComponentGenerator(tree, {
    name,
    module: `${createdProjectName}.module.ts`,
    project: createdProjectName,
    style: "scss",
    changeDetection: "OnPush",
    displayBlock: true,
    export: true,
  });
}
```

Run it and you will get an exception that the new project's `project.json` does not exist:

```sh
ENOENT: no such file or directory, open 'PATH/TO/project.json'
```

**Comment by thutinavaneethreddy** [comment]
Is this issue fixed for all use cases? I get similar error while running unit tests for a workspace generator which sequentially calls multiple @nrwl/angular generators.

**Comment by AgentEnder** [comment]
Hey, I believe this should be resolved in most cases. In any case, can you put together a small reproduction of your issue? 

What Nx version are you on?

**Comment by thutinavaneethreddy** [comment]
Hey @AgentEnder , I have created a minimal repo to reproduce this issue and explained the steps in readme - https://github.com/thutinavaneethreddy/minimal-generators-unit-testing/

To summarize, this is what I am trying to do :

In a workspace-generator : 
`import {
  applicationGenerator,
  libraryGenerator,
} from '@nrwl/angular/generators';

export default async function (
  tree: Tree,
  schema: { appName: string; libName: string }
) {
  await applicationGenerator(tree, {
    name: schema.appName,
    standaloneConfig: true,
  });

  await libraryGenerator(tree, {
    name: schema.libName,
    standaloneConfig: true,
  });

  await formatFiles(tree);
}`


Above generator works fine when executed normally in the workspace and also creates projects with standalone configs.
But when I tried to write unit test for the same, it gives error saying path to project.json can't be found.

`it('should` create angular app and library', async () => {
    await firstGenerator(tree, {
      appName: 'app3',
      libName: 'lib3'
    });
  });`

This happens only when we keep two or more generators from @nrwl/angular inside workspace-generator. It also doesn't happen if standaloneConfig is set to false. 

Below is the error log : 

 `FAIL   tools  tools/generators/first-generator/index.spec.ts (30.144 s)
  ● first-generator › should create angular app and library

    Cannot find ../NX/minimal-generators-unit-testing/apps/app3/project.json

      at Object.readJson (../packages/devkit/src/utils/json.ts:21:11)
      at ../packages/devkit/src/generators/project-configuration.ts:424:41
          at Array.forEach (<anonymous>)
      at inlineProjectConfigurationsWithTree (../packages/devkit/src/generators/project-configuration.ts:421:48)
      at readWorkspace (../packages/devkit/src/generators/project-configuration.ts:402:25)
      at Object.readProjectConfiguration (../packages/devkit/src/generators/project-configuration.ts:230:21)
      at fixProjectWorkspaceConfig (../packages/angular/src/generators/library/lib/update-project.ts:121:19)
      at Object.<anonymous> (../packages/angular/src/generators/library/lib/update-project.ts:19:3)
      at ../node_modules/tslib/tslib.js:117:75`
