### ISSUE TITLE
Multiple unnecessary rebuilds

### ISSUE THREAD

**Issue by seravifer** [nrwl/nx#6343]
## Current Behavior
I want to build all the monorepo libraries. For this I am executing all the commands of each library sequentially.
The problem is that when it comes to a library that has a dependency on another, it builds it too.

## Expected Behavior
Before upgrading to NX and Angular to v12 it worked as expected. I'm not sure if it's a regression, a feature, or a bug.
Is there a new command to build all libs only once? Or a flag to avoid build deps?

## Steps to Reproduce
We run this command: `nx build styles && nx build icons && nx build components && ...` 

And then de CLI say this:
![Captura de pantalla 2021-07-13 a las 12 03 03 p  m](https://user-images.githubusercontent.com/5394989/125433248-c2e49e57-f0ef-49a3-aac2-256d58f595e0.png)

### Environment
```
  Node : 14.17.0
  OS   : darwin x64
  npm  : 6.14.13
  
  nx : Not Found
  @nrwl/angular : 12.5.7
  @nrwl/cli : 12.5.7
  @nrwl/cypress : 12.5.7
  @nrwl/devkit : 12.5.7
  @nrwl/eslint-plugin-nx : 12.5.7
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.7
  @nrwl/linter : 12.5.7
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.5.7
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.7
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.7
  @nrwl/storybook : 12.5.7
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by seravifer** [comment]
Ok, it seems that it is produced by a behavior change when having this in the nx.json file:
```
"targetDependencies": {
    "build": [
      {
        "target": "build",
        "projects": "dependencies"
      }
    ]
  }
```

**Comment by AgentEnder** [comment]
Hey, this behavior is due to the targetDependencies. In subsequent steps though, the build for libraries that are already built should simply pull from the local cache. Are you seeing additional time due to this, or just the console output?

**Comment by seravifer** [comment]
Yes, the problem we see is that the time was multiplied by 3. Since it did not always use the cache. Anyway, we already know how to use the expected behavior.
