### ISSUE TITLE
Introduce path variables to project.json files

### ISSUE THREAD

**Issue by diegovilar** [nrwl/nx#6344]
## Description
Introduce 2 variables to be used in `projects.json` files:
- One with the absolute path to the monorepo directory;
- Another one with the absolute path to the project directory.

## Motivation
The introduction of `project.json` files in v12 (and the ability to extract project configurations from `workspace.json` to them) was a great improvement. Keeping configuration close to the project it concerns is great. But I feel that those files (`project.json`) should be unaware of both the monorepo path and the project path. It's a lot of repetition and error prone if you're scoping using subpaths and/or need to use the paths for custom targets.

Using variables allow for cleaner values and more portability.

## Suggested Implementation
Suppose there are 2 variables available: `NX_ROOT` and `NX_PROJECT`. A `project.json` file would only need to use those variables to reference the monrepo root and the project path:

```json
{
  "root": "$NX_PROJECT",
  "sourceRoot": "$NX_PROJECT/src",
  "projectType": "application",
  "targets": {
    "package": {
      "executor": "@nrwl/workspace:run-commands",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "$NX_ROOT/dist/serverless/payment.package",
        "commands": [
          "rm -rf $NX_ROOT/dist/serverless/payment.package",
          "pnpx nx run serverless-payment-app:build --with-deps",
          "cd $NX_PROJECT && $NX_ROOT/node_modules/.bin/serverless package --config serverless.ts --package $NX_ROOT/dist/serverless/payment.package"
        ],
        "parallel": false
    }
  }
}
```

Those variables would automatically be expanded by NX. Also, those variables would be made available as environment variables to any command/shell executed by a target.

**Comment by FrozenPandaz** [comment]
We'll have to think through how we want to handle this.

**Comment by MaximSagan** [comment]
This feature along with the ability to extend a base project (similar to tsconfig) like
```json
{
    "extends": "../../project.base.json",
}
```
would cut out so much repetition

**Comment by MaximSagan** [comment]
(continuing my above thought)

We just had to upgrade a large number of app `project.json` files with the manual `ng serve` fix that @brandonroberts kindly provided [here](https://dev.to/brandontroberts/speeding-up-the-development-serve-after-upgrading-to-angular-v12-5db5). It would be great to be able to fix this in one configuration file that all or most apps extend (something like `project.app-base.json`).

**Comment by popovicsandras** [comment]
Hello.

We have some similar needs, especially because we have some apps in our monorepo, which need to be mirrored into a public repo (community distributions), with their own angular.json. At the moment, we needed to duplicate the content of angular.json files related to those particular apps, but with the current approach (version 2), we would still need to have duplications since the paths are hardcoded into the project.json.

I really like the suggestion from @diegovilar, however I reckon, using a different notation might be better, to avoid those template strings (`$NX_ROOT `, `$NX_PROJECT `) to be mistaken with shell environment variables.
What about following something similar which I saw in the jest config for example?
- `<nx_root>`/...
- `<nx_project>`/...

**Comment by kylecordes** [comment]
We have a repo with 100+ projects/libraries, and we generate the workspace and nx.json files using a homegrown very-purpose-specific piece of JavaScript. Looking at it, the need for it is driven mostly by the lack of variables like this. We do things like automatically compensate for how many ../../../../ it takes to get back to the root, to make the name of a project or library a strict function of its directory name (instead of independently varying), etc.

This feature would be a great step toward reducing the need for this sort of complexity.

(Ideally none of the files inside a specific project or library should ever contain the name of that project or library, nor anything that would have to very based on how deep it is in the file hierarchy.)

**Comment by chrisui** [comment]
Seems like an ideal place to ask where the `"{}"` syntax in `targets[].outputs[]` comes from and why the syntax for variable expansion would not be consistent?

Eg.

```
{
  "root": "lib/a",
  "sourceRoot": "lib/a/src",
  "projectType": "library",
  "targets": {
    "lint": {
      "executor": "@nrwl/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["lib/a/**/*.{ts,tsx,js,jsx}"]
      }
    }
  },
  "tags": [],
  "implicitDependencies": []
}

```

**Comment by MrChrisRodriguez** [comment]
Not sure if this is documented anywhere, but by printing out env vars I found that Nx sets the `$NX_WORKSPACE_ROOT` env variable which I've been using a lot in my project.json targets. I didn't check for application-specific abs or rel paths, but there might be one (try a command-type target and printenv to see the environment within the Nx runner's context)

**Comment by diegovilar** [comment]
> Not sure if this is documented anywhere, but by printing out env vars I found that Nx sets the `$NX_WORKSPACE_ROOT` env variable which is half of what you're looking for.
> 
> I didn't check for application-specific abs or rel paths, but there might be one, too. Try having a run-command executor do a `printenv` to see what env vars are available within the executor's context.
> 
> Or, if you wanted to be fancy, you could use `jq` to get it out of the workspace.json:
> 
> ```
> cat $NX_WORKSPACE_ROOT/workspace.json | jq '.projects.<project-name>' --> rel path to project
> ``` 

NX does indeed set some envs when executing targets, but while they may be used by shell scripts ran by said targets (or any other program that can read envs), they cannot be used to populate properties of the project.json itself.

Since targets are being executed by NX, NX knows the project location and could just make it (alongside the monorepo root path and other useful paths) available to be expanded inside project.json. That would lower repetition and allow for a lot of flexibility inside those files.

**Comment by Zamiell** [comment]
> Not sure if this is documented anywhere, but by printing out env vars I found that Nx sets the $NX_WORKSPACE_ROOT env variable which is half of what you're looking for.

Adding on to this, it seems that `NX_TASK_TARGET_PROJECT` is also set with the name of the project.

Thus, you can change something like:

```json
{
  "targets": {
    "build": {
      "executor": "nx:run-commands",
      "dependsOn": [
        {
          "target": "build",
          "projects": "dependencies"
        }
      ],
      "options": {
        "command": "bash packages/my-package-name/build.sh"
      }
    },
  }
}
```

To:

```sh
{
  "targets": {
    "build": {
      "executor": "nx:run-commands",
      "dependsOn": [
        {
          "target": "build",
          "projects": "dependencies"
        }
      ],
      "options": {
        "command": "bash packages/$NX_TASK_TARGET_PROJECT/build.sh"
      }
    },
  }
}
```

This is helpful to remove a ton of repetition, but we still desperately need the extends feature:

```
{
    "extends": "../../project.base.json",
}
```

**Comment by binaryartifex** [comment]
damn....surprised this is still an issue. this has become one of my biggest pain points with NX....

**Comment by MaximSagan** [comment]
> damn....surprised this is still an issue. this has become one of my biggest pain points with NX....

Absolutely. Having to repeat massive configuration for every "small" lib I make is main thing that prevents me from readily recommending NX to others.

@vsavkin, @FrozenPandaz, is this something the NX team is aware of?

**Comment by Zamiell** [comment]
> But it's unclear how to use environment variables inside of a command, as doing "command": "echo $NX_TASK_TARGET_PROJECT" will just echo the literal string.

The solution I landed at for now is to do something like this:

```json
    "build": {
      "executor": "nx:run-commands",
      "dependsOn": [
        {
          "target": "build",
          "projects": "dependencies"
        }
      ],
      "options": {
        "command": "bash build-package.sh"
      }
    },
```

```
#!/bin/bash

set -e # Exit on any errors

# Get the directory of this script:
# https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ -z "$NX_TASK_TARGET_PROJECT" ]; then
  echo "The \"NX_TASK_TARGET_PROJECT\" environment variable is blank. Are you running this script manually? This script is only meant to be invoked by NX."
  exit 1
fi

bash "$DIR/packages/$NX_TASK_TARGET_PROJECT/build.sh"
```

You can obviously edit the `build.sh` script to your liking, but that's the general idea.

**Comment by jbadeau** [comment]
Why is there no response on this?

- extends
- env var expanding

would really make managing larger repos easy.

**Comment by skoblenick** [comment]
A use case I find myself wanting env var expansion in the `project.json` is for `sslCert` and `sslKey`. I'd like to avoid adding to team member's cognitive load by forcing them to remember which options and paths to pass around. Sane defaults should just be set in the project configuration files. While I could wrap the command in scripts it breaks a strict nx cli workflow forcing the devs to bounce between multiple cli tools. Another reason I don't really want to add scripts is to keep it simple; adding scripts increases the complexity of maintaining the monorepo and could introduce cross-platform issues.

for example:

```json
"serve: {
    "options": {
        "port": 4200,
        "ssl": true,
        "sslCert": "$HOME/certs/localhost/cert.pem",
        "sslKey": "$HOME/certs/localhost/key.pem"
     }
}
```

**Comment by kornect** [comment]
@skoblenick I find myself in the same predicament. I'm building an Excel add-in using angular which must be hosted using SSL so it can be loaded on Excel. My team uses different machines (Mac/Windows) resulting in different home directory paths for the certs used. This would be really useful if it was possible.

**Comment by huantaoliu** [comment]
watching this

**Comment by rek** [comment]
same ^^. would love a feature like this. my use-case is publishing to different locations for different pipelines, without having to duplicate a large target.

**Comment by chrisui** [comment]
Half the bugs we encounter in our task pipelines are due to subtly wrong paths in json config files. Would love to see some improvements to the story of making configuration much more relative and transportable (bonus: re-usable/composable/extendable).

**Comment by AgentEnder** [comment]
This is already implemented in the form of extended targetDefaults. See: https://nx.dev/reference/nx-json#target-defaults

We don't want to support these tokens inside of the actual project configuration, as it makes generators and migrations much harder to write in a reliable fashion.

The extended target defaults syntax lets you pull any options which are consistent across projects into nx.json and make use of `{projectRoot}, {workspaceRoot}, and {projectName` tokens.
