### ISSUE TITLE
[devkit] `updateProjectConfiguration` does not update standalone projects

### ISSUE THREAD

**Issue by edbzn** [nrwl/nx#6345]
## Current Behavior

I have a workspace with an extracted configuration (standalone) for some projects, I want to create a generator that will update these configurations using the [`updateProjectConfiguration`](https://github.com/nrwl/nx/blob/dd51c18d12abd1dd059956e4b64f331b7891c79a/packages/devkit/src/generators/project-configuration.ts#L58) function from the devkit, but it does not work if the project configuration was extracted. 

For example the following code works if `'my-project'` configuration is defined in `workspace.json` but not if it's a extracted in `libs/my-project/project.json` : 

```ts
updateProjectConfiguration(tree, 'my-project', {
  targets: {
    version: {
      executor: '@jscutlery/semver:version'
    },
  },
});
```

## Expected Behavior

Transparently handle standalone project configuration.

**Comment by AgentEnder** [comment]
@edbzn What is the output of `nx report` for you? I was unable to reproduce, as the below generator successfully updated project.json file.

```typescript
import { Tree, installPackagesTask, updateProjectConfiguration, readProjectConfiguration } from '@nrwl/devkit';

export default async function (host: Tree, schema: {name: string}) {
  const configuration = readProjectConfiguration(host, schema.name);
  updateProjectConfiguration(host, schema.name, {
    ...configuration,
    targets: {
      ...configuration.targets,
      version: {
        executor: '@jscutlery/semver:version'
      },
    },
  });
  return () => {
    installPackagesTask(host);
  };
}

```

**Comment by edbzn** [comment]
My bad, the editor was displaying an outdated version of the file, I confirm it works. :facepalm: Sorry for that!
