### ISSUE TITLE
project.json split not remembered by NestJS generator

### ISSUE THREAD

**Issue by Ionaru** [nrwl/nx#6354]
## Current Behavior

`--standaloneConfig` must be passed to the NestJS generator each time you generate an app, even if all projects are currently utilizing it.

## Expected Behavior

The NestJS generator behaves like the other generators and creates a standalone config if this is the standard in a workspace.
Other generators (like `@nrwl/node`) do this correctly since #6180 was merged and released.

## Steps to Reproduce
1. `create-nx-workspace --name test-project --preset empty --nx-cloud false`
2. `cd test-project`
3. `npm i -D @nrwl/nest`
4. `nx g @nrwl/nest:application api --standaloneConfig`
5. `nx g @nrwl/nest:application api2`

A separate `project.json` is not generated for api2 and the configuration is instead added to `workspace.json`.

### Failure Logs

None.

### Environment

```
  Node : 14.16.0
  OS   : win32 x64
  npm  : 6.14.13

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.5.8
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.5.8
  @nrwl/eslint-plugin-nx : 12.5.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.8
  @nrwl/linter : 12.5.8
  @nrwl/nest : 12.5.8
  @nrwl/next : Not Found
  @nrwl/node : 12.5.8
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.8
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.8
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by FrozenPandaz** [comment]
@AgentEnder Can you take a look please?

**Comment by AgentEnder** [comment]
@Ionaru This is fixed in latest master, and should be fixed in the next release. If you are still experiencing this issue afterwards, please reopen this issue.
