### ISSUE TITLE
nx serve/build --with-deps should output list of libraries built or used from cache to terminal

### ISSUE THREAD

**Issue by webmandman** [nrwl/nx#6355]
## Description

`ng serve --with-deps` should output to the terminal a list of buildable libraries and state whether the library was rebuilt or used from cache. This list should go after Initial Chunk Files and Lazy Chunk Files lists. 

Thank you!

**Comment by FrozenPandaz** [comment]
This is actually the intended behavior when running a single project.

This makes it easier to see the results of the project you are running without the noise of logs from the dependencies. There could be many projects. 

If any libraries are not cached, you should see the output. Only the cached output is hidden when running a single project.

Does that make sense?

**Comment by webmandman** [comment]
yup makes sense.
