### ISSUE TITLE
v12.6.0-beta.6 Next minimum typescript warning

### ISSUE THREAD

**Issue by dan2kx** [nrwl/nx#6356]
## Current Behavior
I have just used nx migrate next to migrate to the pre-release version which upgrades next to 11.0.1 and it gives a warning 

```
Minimum recommended TypeScript version is v4.3.2, older versions can potentially be incompatible with Next.js. Detected: 4.2.4
```

## Expected Behavior
I would expect nx to have updated typescript to at least 4.3.2 to negate this warning.

I also tried to update typescript to the latest version in the package.json file manually and got an error during a nx lint check, i expect that would need to be bumped to support too.

```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.3.0

YOUR TYPESCRIPT VERSION: 4.3.5

Please only submit bug reports when using the officially supported version.

=============
```

## Steps to Reproduce
in a next enabled workspace run 
1. nx migrate next 
2. serve the application

### Environment
  Node : 14.15.0
  OS   : darwin x64
  npm  : 7.16.0
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.6.0-beta.6
  @nrwl/cypress : 12.6.0-beta.6
  @nrwl/devkit : 12.6.0-beta.6
  @nrwl/eslint-plugin-nx : 12.6.0-beta.6
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.0-beta.6
  @nrwl/linter : 12.6.0-beta.6
  @nrwl/nest : Not Found
  @nrwl/next : 12.6.0-beta.6
  @nrwl/node : 12.6.0-beta.6
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.6.0-beta.6
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.0-beta.6
  @nrwl/web : 12.6.0-beta.6
  @nrwl/workspace : 12.6.0-beta.6
  @nrwl/storybook : 12.6.0-beta.6
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by FrozenPandaz** [comment]
Thank you for the information! We will look into upgrading typescript soon.
