### ISSUE TITLE
make it easier to maintain package.json

### ISSUE THREAD

**Issue by mhamri** [nrwl/nx#6357]
## Description

atm there is no way to check if a package is used in the mono repo or not. the node_module and its install get longer and longer and no way to confirm if a package is used in one of the hundred lib and app other than checking them manually. 

`depcheck` lib doesn't support nx, so there should be a contribution from nx to that repo or nx independant lib. 

## Motivation

to clean the package.json and decrease install time 

## Suggested Implementation

contribute to depcheck lib or come up with a built in solution

## Alternate Implementations

there is none that I am aware of

**Comment by FrozenPandaz** [comment]
Hm... I'm not sure we know enough at the moment for this to be 100% accurate and I think having a lot of false positives would be annoying. We have some information about which `node_modules` the projects depend on but I don't think it's accurate enough to recommend removing ones that we don't see.

This isn't currently planned to be worked on but is someone interested in experimenting with using the Nx project graph to recommend removing dependencies?

**Comment by mhamri** [comment]
there are package that is doing that like 'depcheck' but the problem is
they can't figure out the nx folder structure. so no need to guess or
reinvent the wheel, just look at their code. moreover it won't need to be
100% accurate. the user can confirm its correctness.

**Comment by mhamri** [comment]
still it's a valid requirement for publishable lib. we have to manually
maintain the contain of package and it's list
