### ISSUE TITLE
NX 11 -> 12 Migration issue:  zone-testing.js is needed for the fakeAsync()

### ISSUE THREAD

**Issue by sameera** [nrwl/nx#6361]
## Current Behavior
After migrating a NX 11 (exclusively Angular) repo to 12, I'm getting the following error when running the Jest unit tests:
```
    zone-testing.js is needed for the fakeAsync() test helper but could not be found.
            Please make sure that your environment includes zone.js/testing
```
I noticed that polyfills.ts was updated during migration, changing the zone.js import statement. So, I changed back that line and tried as well. But the same error persisted. I also tried adding `import "zone.js/tsting"` without any luck.

## Expected Behavior
Unit tests to execute without an error.

## Steps to Reproduce
Migrate a NX 11 repo with `nx migrate latest`.

### Failure Logs
```

    zone-testing.js is needed for the fakeAsync() test helper but could not be found.
            Please make sure that your environment includes zone.js/testing

      at resetFakeAsyncZone (../../../packages/core/testing/src/fake_async.ts:25:9)
      at Object.<anonymous> (../../../packages/core/testing/src/test_hooks.ts:39:7)
```

### Environment
>  NX  Report complete - copy this into the issue template

  Node : 12.14.1
  OS   : darwin x64
  npm  : 7.19.1
  
  nx : 11.1.5
  @nrwl/angular : 12.5.8
  @nrwl/cli : 12.5.8
  @nrwl/cypress : 12.5.8
  @nrwl/devkit : 12.5.8
  @nrwl/eslint-plugin-nx : 12.5.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.8
  @nrwl/linter : 12.5.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : 12.2.7
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.8
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.8
  @nrwl/storybook : 12.5.8
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by FrozenPandaz** [comment]
What is the resulting `jest.config.js`? Does it have the following?

```ts
setupFilesAfterEnv: ['<rootDir>/src/test-setup.ts'],
```

Which has `import 'jest-preset-angular/setup-jest';` in the file?

is it possible to provide a repo that has the project before and after migrating that is failing?

**Comment by sameera** [comment]
@FrozenPandaz 
Yes on the content of `jest.config.js`
No on the `import 'jest-preset-angular/setup-jest'` in `test-steup.ts`.
Instead it still has only the import 'jest-preset-angular' from previous versions.
Adding this line manually, fixes the issue.

I ran `nx migrate --run-migrations` multiple times but, never got the migration to update `test-setup.ts` files.
Here's my `migrations.json` file if it helps: 
[migrations.json.txt](https://github.com/nrwl/nx/files/6820441/migrations.json.txt)


I see the relevant (seemingly) migrations ran successfully
```
Running migration update-jest-preset-angular-8-4-0
Successfully finished update-jest-preset-angular-8-4-0
---------------------------------------------------------
Running migration update-ts-jest-6-5-5
Successfully finished update-ts-jest-6-5-5
---------------------------------------------------------
Running migration support-jest-27
Successfully finished support-jest-27
---------------------------------------------------------
Running migration update-ts-jest-and-jest-preset-angular
Successfully finished update-ts-jest-and-jest-preset-angular
```

**Comment by mehrad-rafigh** [comment]
How can this be closed? I have the same issue migrating to nx 12.7

**Comment by zoechi** [comment]
Migration added this to my `test-setup.ts` before and after my original content

```ts
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting,
} from '@angular/platform-browser-dynamic/testing';

// original content
import 'jest-extended';
import 'jest-preset-angular/setup-jest';
// original content

getTestBed().resetTestEnvironment();
getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting(), {
  teardown: { destroyAfterEach: false },
});
```
removing that fixed my tests

**Comment by bridzius** [comment]
For people who actually need the environment teardown override:
`import 'jest-preset-angular/setup-jest';` has to be imported *before* the other `@angular` imports for the setup to happen correctly. So:
```ts
import 'jest-preset-angular/setup-jest';
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting,
} from '@angular/platform-browser-dynamic/testing';

getTestBed().resetTestEnvironment();
getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting(), {
  teardown: { destroyAfterEach: false },
});
```

**Comment by jansgescheit** [comment]
> For people who actually need the environment teardown override - `import 'jest-preset-angular/setup-jest';` has to be imported **before** the other `@angular` imports for the setup to happen correctly. So:
> 
> ```ts
> import 'jest-preset-angular/setup-jest';
> import { getTestBed } from '@angular/core/testing';
> import {
>   BrowserDynamicTestingModule,
>   platformBrowserDynamicTesting,
> } from '@angular/platform-browser-dynamic/testing';
> 
> getTestBed().resetTestEnvironment();
> getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting(), {
>   teardown: { destroyAfterEach: false },
> });
> ```

Any tipps how this workaround works with organize imports feature of vscode?

**Comment by Hypenate** [comment]
We ran into the same issue and we've created a custom linting rule for this:

The rule:
```
/**
 * This file sets you up with structure needed for an ESLint rule.
 *
 * It leverages utilities from @typescript-eslint to allow TypeScript to
 * provide autocompletion etc. for the configuration.
 *
 * Your rule's custom logic will live within the create() method below.
 * You can learn more about writing ESLint rules on the official guide:
 *
 * https://eslint.org/docs/developer-guide/working-with-rules
 *
 * You can also view many examples of existing rules here:
 *
 * https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin/src/rules
 */

import { ESLintUtils, TSESTree } from '@typescript-eslint/utils';

// NOTE: The rule will be available in ESLint configs as "@nrwl/nx/workspace/test-setup-import-order"
export const RULE_NAME = 'test-setup-import-order';

export const rule = ESLintUtils.RuleCreator(() => __filename)({
  name: RULE_NAME,
  meta: {
    type: 'problem',
    fixable: 'code',
    hasSuggestions: true,
    docs: {
      description: `'import 'jest-preset-angular/setup-jest';' must always be on top`,
      recommended: 'error',
    },
    schema: [],
    messages: {
      orderImport: `Place "import 'jest-preset-angular/setup-jest';" on top of the import list`,
    },
  },
  defaultOptions: [],
  create(context) {
    return {
      ImportDeclaration(node: TSESTree.ImportDeclaration) {
        if (node.loc.start.line !== 1 && node.source.value == 'jest-preset-angular/setup-jest') {
          context.report({
            node,
            messageId: 'orderImport',
            fix: (fixer) => {
              return [fixer.remove(node), fixer.insertTextBeforeRange([0, 1], `import 'jest-preset-angular/setup-jest';\n`)];
            },
          });
        }
      },
    };
  },
});
```

The test (optional):
```
import { convertAnnotatedSourceToFailureCase } from '@angular-eslint/utils';
import { TSESLint } from '@typescript-eslint/utils';
import { rule, RULE_NAME } from './test-setup-import-order';

const ruleTester = new TSESLint.RuleTester({
  parser: require.resolve('@typescript-eslint/parser'),
});

ruleTester.run(RULE_NAME, rule, {
  valid: [`import 'jest-preset-angular/setup-jest';`],
  invalid: [
    convertAnnotatedSourceToFailureCase({
      description: 'should fail when the "jest-preset-angular/setup-jest" import is not first',
      annotatedSource: `import { getTestBed } from '@angular/core/testing';
import 'jest-preset-angular/setup-jest';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`,
      messageId: 'orderImport',
      annotatedOutput: `import 'jest-preset-angular/setup-jest';
import { getTestBed } from '@angular/core/testing';

`,
    }),
  ],
});

```

The change in .eslintrc file:
```
    {
      files: ['test-setup.ts'],
      rules: {
        '@nrwl/nx/workspace/test-setup-import-order': 'error',
      },
    },
```
