### ISSUE TITLE
Trigger cleanup of old cache entries via command line

### ISSUE THREAD

**Issue by gselltho** [nrwl/nx#6362]
https://github.com/nrwl/nx/blob/8ab463e38693064063c2296e3ea8a4fc1f75e2da/packages/workspace/src/tasks-runner/cache.ts#L38-L43

At the moment it seems, that cleaning up the outdated cache entries is only executed when a random number between 0 and 50 equals 1.
It would be nice to have a more granular control when the cleanup will be executed. For example with a dedicated cli command. Like `nx prune-cache`

**Comment by FrozenPandaz** [comment]
Hm that sounds like a reasonable implementation of cleaning up the cache.

I think we'd prefer to keep it automatic.. is the cache getting too large for you? It is intended to be kept small automatically and maybe we could make the automatic clean up better than the random occurrence :wink:

**Comment by gselltho** [comment]
@FrozenPandaz 
Yes it's getting too large for us. We use it in our build pipeline and need to keep the the build workspace small for some reasons.
We have a quite big repo and the cache has already more then 1 gb after compressing. After pruning the cache only 200mb left.

We do not really need a manual way to prune the cache but a one we can rely upon. The random thingy does not work for us, because it got not executed since weeks.

**Comment by lavigneer** [comment]
We're seeing an issue in our build pipeline where the nx cache is getting massive (it's at 21GB right now) and contains entries from several months ago. There could be something weird going on with our environment setup as I only see this on the build VM and not my laptop. We use docker with a docker volume mounted for the cache in both environments. 

I need to dig into why this is happening but having some way to adjust the behavior of cache cleanup.making it more consistent, or forcing it through a command as suggested above would be really useful as we can run that command after/before each build run to prevent the size from getting out of hand.

I tried initializing a new Cache instance and running `removeOldCacheRecords` on it 10k times and it never cleaned up the cache directory. Running `node node_modules/@nrwl/workspace/src/tasks-runner/remove-old-cache-records.js /path/to/cache` manually did result in the old entries getting cleaned up, so it seems there's something weird going on with `removeOldCacheRecords` logic
