### ISSUE TITLE
createGlobPatternsForDependencies function from @nrwl/react/tailwind does not work on Windows

### ISSUE THREAD

**Issue by ashwinGokhale** [nrwl/nx#6369]
## Current Behavior
Following step #2 of [Tailwind instructions](https://nx.dev/latest/react/guides/using-tailwind-css-in-react#using-tailwind-css-in-react) throws an error when calling `createGlobPatternsForDependencies(__dirname)` on Windows. I suspect it is because Windows paths use the `\` character instead of the `/` character

## Expected Behavior
I expect the Tailwind guide to work.

## Steps to Reproduce
1. Use an existing Nx React Clone or clone the [Nx example](https://github.com/nrwl/nx-examples)
2. Follow the [Tailwind guide](https://nx.dev/latest/react/guides/using-tailwind-css-in-react#using-tailwind-css-in-react)

### Failure Logs
```
ERROR in ./styles.scss (C:/Users/USERNAME/source/REPO/node_modules/@nrwl/web/src/utils/third-party/cli-files/plugins/raw-css-loader.js!C:/Users/USERNAME/source/REPO/node_modules/@nrwl/web/node_modules/postcss-loader/dist/cjs.js??ref--5-oneOf-9-2!C:/Users/USERNAME/source/REPO/node_modules/@nrwl/web/node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-9-3!./styles.scss)
Module Error (from C:/Users/USERNAME/source/REPO/node_modules/@nrwl/web/node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "tailwindcss" plugin failed: createGlobPatternsForDependencies: Error when trying to determine main project.
The "from" argument must be of type string. Received undefined

(@C:\Users\USERNAME\source\REPO\apps\automation\src\styles.scss)
ENOENT: no such file or directory, open 'dist\apps\automation\index.html'
```

### Environment

```
Node : 14.16.1
  OS   : win32 x64
  yarn : 1.22.5

  nx : Not Found
  @nrwl/angular : 12.5.5
  @nrwl/cli : 12.5.5
  @nrwl/cypress : 12.5.5
  @nrwl/devkit : 12.5.5
  @nrwl/eslint-plugin-nx : 12.5.5
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.5
  @nrwl/linter : 12.5.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 12.5.5
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.5
  @nrwl/web : 12.5.5
  @nrwl/workspace : 12.5.5
  @nrwl/storybook : 12.5.5
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by juristr** [comment]
@ashwinGokhale can you have a look at the guide here: https://blog.nrwl.io/setup-next-js-to-use-tailwind-with-nx-849b7e21d8d0

The configuration should look like

```
// available since Nx v 12.5
const { createGlobPatternsForDependencies } = require('@nrwl/next/tailwind');

module.exports = {
  purge: [
    './apps/site/pages/**/*.{js,ts,jsx,tsx}',
    ...createGlobPatternsForDependencies(__dirname),
  ],
  ...
};
```

So the `createGlobPatternsForDependencies` generates globs just for dependencies of the app where the `tailwind.config.js` is living. For the app itself you have to configure it manually.

I'll adjust the guide to make that more clear. In case that doesn't help, can you point me to some repo that reproduces the problem? That'll make it easier for me to look into it. Thank you :)

**Comment by juristr** [comment]
@ashwinGokhale can you post the content of your `styles.scss`?

**Comment by ashwinGokhale** [comment]
@juristr here is [what I changed](https://github.com/ashwinGokhale/nx-tailwind-bug/commit/e03ba4c9c379feaf646c0eb4ad78fc7dfb5b9101)

**Comment by juristr** [comment]
@ashwinGokhale thanks. I'll look into it next week 👍

**Comment by webmandman** [comment]
i'm on Nx 12.5.8 and I'm trying to utilize @nrwl/angular/tailwind and I'm getting the same error. 

createGlobPatternsForDependencies: Error when trying to determine main project.
The "from" argument must be of type string. Received undefined
Error: createGlobPatternsForDependencies: Error when trying to determine main project.
The "from" argument must be of type string. Received undefined
    at Object.createGlobPatternsForDependencies (C:\Development\sites\intra\angularworkspace\node_modules\@nrwl\workspace\src\utilities\generate-globs.js:23:15)
    at createGlobPatternsForDependencies (C:\Development\sites\intra\angularworkspace\node_modules\@nrwl\angular\tailwind.js:13:29)
    at Object.<anonymous> (C:\Development\sites\intra\angularworkspace\apps\employeeportal\tailwind.config.js:10:10)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (C:\Development\sites\intra\angularworkspace\node_modules\@nrwl\tao\src\compat\compat.js:7:40)
    at require (node:internal/modules/cjs/helpers:94:18)
    at C:\Development\sites\intra\angularworkspace\node_modules\tailwindcss\lib\index.js:83:107
    at tailwindcss (C:\Development\sites\intra\angularworkspace\node_modules\tailwindcss\lib\index.js:96:36)
    at Object.getStylesConfig (C:\Development\sites\intra\angularworkspace\node_modules\@angular-devkit\build-angular\src\webpack\configs\styles.js:142:66)
    at webpack_browser_config_1.generateI18nBrowserWebpackConfigFromContext.differentialLoadingNeeded.differentialLoadingNeeded (C:\Development\sites\intra\angularworkspace\node_modules\@angular-devkit\build-angular\src\browser\index.js:67:19)
    at generateWebpackConfig (C:\Development\sites\intra\angularworkspace\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:59:49)
    at async generateBrowserWebpackConfigFromContext (C:\Development\sites\intra\angularworkspace\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:116:20)

**Comment by webmandman** [comment]
In the version of Nx that I'm in (12.5.8) I found the issue here: https://github.com/nrwl/nx/blob/6eb1819e99f81c1f97457f253545ce611cb7f3ff/packages/workspace/src/utilities/project-graph-utils.ts#L48

 `const relativePath = relative(node.data.root, projRelativeDirPath);`
 
the function getProjectNameFromDirPath is looping through all the graph nodes and attempting to build a relative path of each node. But the nodes array contains npm packages which do not have a "root" property.

an example node without "root":
{
  type: 'npm',
  name: 'npm:typescript',
  data: { version: '~4.2.4', packageName: 'typescript', files: [] }
}

So when relative() gets called its being passed an undefined. 

Anyways, this project-graph-util.{ts|js} has been changed several times already since 12.5.8. I think I will update to latest and try it again. 

But I'm wondering if this utility is meant to work with angular projects. 12.5.8 includes @nrwl/angular/tailwind, but I haven't found any tutorials for angular, only for next.

**Comment by webmandman** [comment]
I upgraded to 5.7.2 and its working. Thank you.

**Comment by ashwinGokhale** [comment]
I can confirm it works for Nx v12.8 for React apps. Thanks a lot @juristr! There was 1 issue though. 

We have a common assets library like this:
```treeview
libs/
└───common/
│   └───assets/
│       │   index.html
│       │   favicon.ico
│       └───styles/
│           │   ...
│       └───i18n/
│           │   ...
```

The section in our angular.json looks like this:
```json
"common-assets": {
      "root": "libs/common/assets",
      "sourceRoot": "libs/common/assets",
      "projectType": "library",
      "schematics": {},
      "architect": {}
    },
```

I noticed that the glob that is produced by the createGlobPatternsForDependencies function looks in the src folder for each library, but we don't have a src folder because its just static files. 

I have 2 questions:
1. Can this function should look at the sourceRoot folder in the angular.json/workspace.json to determine the src folder?
2. Is there any guide on sharing styles/translations/etc in an Nx library?

**Comment by ashwinGokhale** [comment]
> I can confirm it works for Nx v12.8 for React apps. Thanks a lot @juristr! There was 1 issue though.
> 
> We have a common assets library like this:
> 
> ```
> libs/
> └───common/
> │   └───assets/
> │       │   index.html
> │       │   favicon.ico
> │       └───styles/
> │           │   ...
> │       └───i18n/
> │           │   ...
> ```
> 
> The section in our angular.json looks like this:
> 
> ```json
> "common-assets": {
>       "root": "libs/common/assets",
>       "sourceRoot": "libs/common/assets",
>       "projectType": "library",
>       "schematics": {},
>       "architect": {}
>     },
> ```
> 
> I noticed that the glob that is produced by the createGlobPatternsForDependencies function looks in the src folder for each library, but we don't have a src folder because its just static files.
> 
> I have 2 questions:
> 
> 1. Can this function should look at the sourceRoot folder in the angular.json/workspace.json to determine the src folder?
> 2. Is there any guide on sharing styles/translations/etc in an Nx library?

Never mind. I cleared my Nx cache and it uses the correct src folder.

**Comment by nawlbergs** [comment]
Tailwind is suddenly not pulling in styles defined in my ui library... same repo works on my mac.  Did this break again?
Im on 15.3.3

**Comment by nawlbergs** [comment]
I've had to manually add the path to the lib in my `tailwind.config.js`
```
  content: [
    join(__dirname, 'src/**/!(*.stories|*.spec).{ts,html}'),
    ...createGlobPatternsForDependencies(__dirname),
    // seems like createGlobPatternsForDependencies stopped working on windows... so we need to add this manually
    join(__dirname, '../../libs/af-angular/src/**/!(*.stories|*.spec).{ts,html}'),
  ],
```
again... i have my macbook next to me and it was working great there...

```
"dependencies": {
    "@angular/animations": "~15.0.0",
    "@angular/cdk": "15.0.3",
    "@angular/common": "~15.0.0",
    "@angular/compiler": "~15.0.0",
    "@angular/core": "~15.0.0",
    "@angular/forms": "~15.0.0",
    "@angular/material": "~15.0.0",
    "@angular/platform-browser": "~15.0.0",
    "@angular/platform-browser-dynamic": "~15.0.0",
    "@angular/router": "~15.0.0",
    "@kripod/uuidv7": "^0.3.4",
    "@ngrx/component-store": "^15.0.0-beta.1",
    "@ngrx/effects": "^15.0.0-beta.1",
    "@ngrx/entity": "^15.0.0-beta.1",
    "@ngrx/router-store": "^15.0.0-beta.1",
    "@ngrx/store": "^15.0.0-beta.1",
    "@ngrx/store-devtools": "^15.0.0-beta.1",
    "@nrwl/angular": "15.3.3",
    "@sentry/browser": "^7.26.0",
    "@sentry/node": "^7.26.0",
    "@sentry/tracing": "^7.26.0",
    "@sequelize/core": "^7.0.0-alpha.20",
    "async": "^3.2.4",
    "aws-sdk": "^2.1276.0",
    "body-parser": "^1.20.1",
    "chart.js": "^3.9.1",
    "compression": "^1.7.4",
    "cookie-parser": "^1.4.6",
    "dayjs": "^1.11.7",
    "express": "^4.18.1",
    "jsonwebtoken": "^8.5.1",
    "pg": "^8.8.0",
    "pg-hstore": "^2.3.4",
    "pino": "^7.10.0",
    "pino-pretty": "^7.6.1",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~15.0.0",
    "@angular-eslint/eslint-plugin": "~15.0.0",
    "@angular-eslint/eslint-plugin-template": "~15.0.0",
    "@angular-eslint/template-parser": "~15.0.0",
    "@angular/cli": "~15.0.0",
    "@angular/compiler-cli": "~15.0.0",
    "@angular/language-service": "~15.0.0",
    "@nrwl/cli": "15.3.3",
    "@nrwl/cypress": "15.3.3",
    "@nrwl/eslint-plugin-nx": "15.3.3",
    "@nrwl/express": "15.3.3",
    "@nrwl/jest": "15.3.3",
    "@nrwl/linter": "15.3.3",
    "@nrwl/node": "15.3.3",
    "@nrwl/workspace": "15.3.3",
    "@types/async": "^3.2.15",
    "@types/chart.js": "^2.9.37",
    "@types/express": "4.17.13",
    "@types/jest": "28.1.1",
    "@types/jsonwebtoken": "^8.5.9",
    "@types/lodash": "^4.14.191",
    "@types/node": "18.7.1",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.36.1",
    "@typescript-eslint/parser": "^5.36.1",
    "autoprefixer": "^10.4.0",
    "cross-env": "^7.0.3",
    "cypress": "^11.0.0",
    "eslint": "~8.15.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "gulp": "^4.0.2",
    "gulp-sass": "^5.1.0",
    "jest": "28.1.1",
    "jest-environment-jsdom": "28.1.1",
    "jest-preset-angular": "~12.2.3",
    "lodash": "^4.17.21",
    "module-alias": "^2.2.2",
    "nx": "15.3.3",
    "postcss": "^8.4.5",
    "prettier": "^2.6.2",
    "sass": "^1.51.0",
    "supertest": "^6.2.4",
    "tailwindcss": "^3.2.4",
    "ts-jest": "28.0.5",
    "ts-node": "10.9.1",
    "typescript": "~4.8.2"
  }
  ```
