### ISSUE TITLE
CircleCI error "Not a valid commit name asdf..."

### ISSUE THREAD

**Issue by rpd10** [nrwl/nx#6374]
## Current Behavior

We randomly receive this error when building pull requests in CircleCI:
```
npx nx affected --target=build --base=${UPSTREAM_MAIN_SHA1} --head=${CIRCLE_SHA1}
fatal: Not a valid commit name e84b10...788e
```

We are trying to track down whether this is a bug in Nx, or something misconfigured or a possible race condition in how we're calculating the base commit used by the affected command.  Most builds of PRs work, but we will see this error sometimes. Re-running the CircleCI job usually clears it up right away.

## Expected Behavior

nx affected finds the relevant commits and works successfully.

## Steps to Reproduce
We are using a fork and pull model, where we have an upstream repository that contributors fork, and submit PRs to upstream in order to contribute.  We have configured CircleCI to build pull requests against the upstream.

Here's our relevant configuration in CircleCI:
```
export UPSTREAM_MAIN_SHA1=`git ls-remote git@www-our-git-repo.com/our-project.git main | cut -c1-40`
npx nx affected --target=build --base=${UPSTREAM_MAIN_SHA1} --head=${CIRCLE_SHA1}
```

### Failure Logs

```
fatal: Not a valid commit name e84b10...788e
```

### Environment

```
>  NX  Report complete - copy this into the issue template

  Node : 14.17.0
  OS   : darwin x64
  npm  : 6.14.13
  
  nx : Not Found
  @nrwl/angular : 11.3.0
  @nrwl/cli : 11.3.0
  @nrwl/cypress : 11.3.0
  @nrwl/devkit : 11.3.0
  @nrwl/eslint-plugin-nx : 11.3.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.3.0
  @nrwl/linter : 11.3.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.3.0
  @nrwl/web : Not Found
  @nrwl/workspace : 11.3.0
  typescript : 4.1.5
```

**Comment by FrozenPandaz** [comment]
Is there any additional information such as a command that failed? It's hard to tell what the issue is with just that log.

Is the commit name in the error one of the ones passed in as `--base` or `--head`?

**Comment by rpd10** [comment]
Sorry for the delay, been on family vacation :).  

Yes, I believe the commit name listed in the error is passed as the --base argument to nx:affected.  Thinking about it more, I don't see how this could be a Nx bug, I'm guessing it has to be something to do with how we're calculating the upstream commit name.  The `CIRCLE_SHA1` is the commit name that Circle is currently building, so I don't see how that could be invalid.  This is how we're currently calculating the upstream commit name for base:

```
export UPSTREAM_MAIN_SHA1=`git ls-remote git@www-our-git-repo.com/our-project.git main | cut -c1-40`
npx nx affected --target=build --base=${UPSTREAM_MAIN_SHA1} --head=${CIRCLE_SHA1}
```

Does that look to be a reasonable approach?  I will compare that against how Nx itself is building (before moving to Orbs, our CircleCI is too old to support them right now).
