### ISSUE TITLE
Should Effects Services Be Listed In NgModule's `providers` Array?

### ISSUE THREAD

**Issue by swseverance** [nrwl/nx#638]
These two commands:
```bash
ng g ngrx foo --module=apps/sample/src/app/app.module.ts --root
ng g ngrx bar --module=apps/sample/src/app/app.module.ts
```
Update app.module to the following, where `providers: [FooEffects, BarEffects]`
```typescript
@NgModule({
declarations: [AppComponent],
  imports: [
    BrowserModule,
    NxModule.forRoot(),
    StoreModule.forRoot(
      { foo: fooReducer },
      {
        initialState: { foo: fooInitialState },
        metaReducers: !environment.production ? [storeFreeze] : []
      }
    ),
    EffectsModule.forRoot([FooEffects]),
    !environment.production ? StoreDevtoolsModule.instrument() : [],
    StoreModule.forFeature('bar', barReducer, {
      initialState: barInitialState
    }),
    EffectsModule.forFeature([BarEffects])
  ],
  providers: [FooEffects, BarEffects],
  bootstrap: [AppComponent]
})
export class AppModule {}
```
My understanding is that `EffectsModule.forRoot(..)` and `EffectsModule.forFeature(...)` both return a `ModuleWithProviders`. Given that, is the ngrx schematic saying `FooEffects` is a provider to both `AppModule` and `EffectsModule` (same with `BarEffects`)? Is it necessary for the schematic to generate `providers: [FooEffects, BarEffects]`?

Version: @nrwl/schematics@6.1.1

**Comment by ThomasBurleson** [comment]
@swseverance  - Agreed. Registering the Effects 2x (as providers) was an oversight; The EffectModule will handle that functionality for us.
