### ISSUE TITLE
Make some aspects optional (such as Data Persistence)

### ISSUE THREAD

**Issue by adaojunior** [nrwl/nx#64]
I've been exploring nrwl/nx and I really like it since it solves the exact problems we found when building an application on my company.
While I really enjoy the Workspaces, aliases, libs, the only aspect I decided to leave out is `Ngrx 
 Data Persistence`.
I wonder if it would be a good idea to make it optional, or at least make it easy to remove it ?

**Comment by vsavkin** [comment]
I was thinking about it too. The issue is that other schematics (e.g., NgRx) require the data persistence stuff. Making all of them optional is too cumbersome. 

Are you using NgRx in your project?

**Comment by adaojunior** [comment]
Yes, I'm using `NgRx` but it is nothing too complex, just to keep in sync the authentication and a few other dependencies.

**Comment by jschwarty** [comment]
@adaojunior Nx now has support for [custom workspace schematics](https://nrwl.io/nx/workspace-specific-schematics). This might be an option for leveraging the ngrx schematic but altering it to not use the DataPersistence stuff.
