### ISSUE TITLE
missing test environment for node libs

### ISSUE THREAD

**Issue by wizardnet972** [nrwl/nx#6405]
## Current Behavior

I got an error when I run the jest test command `nx test my-lib` (node lib):
```
  ReferenceError: setImmediate is not defined.
```
`setImmediate` is a native function exists in the node runtime.

The problem is jest need to have `testEnvironment: 'node'` in order to run the test in node mode which not supply when creating the lib.

With this flag, jest will be resolve native functions such `setImmediate` and will not throw an error.

## Expected Behavior

To be able to test node library with native functions.

## Steps to Reproduce

1. create a node lib: `nx g @nrwl/node:lib my-lib`.
2. `winston` logger uses `setImmediate`, so import and use `winston` in your function or run some third party that using `winston`. [or check the code here](https://github.com/winstonjs/winston/blob/master/lib/winston/transports/console.js#L45).
3. or run in the code `setImmediate`
4. You get an error: ` ReferenceError: setImmediate is not defined.`

### Failure Logs
```  
ReferenceError: setImmediate is not defined.
```

* When I add the flag it solves my problem and alow me to do tests as expected.
* I can send a PR if you like.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Unfortunately, I can reproduce the issue. Following the steps you mention above, the `testEnvironment: 'node'` is correctly set and the tests run successfully.

Could you please share a minimal reproduction repo so we can troubleshoot the issue?

**Comment by alumni** [comment]
Actually, I can confirm this with v12.5.8. The jest preset that nx-jest provides sets `testEnvironment: 'jsdom'`. In my case, this is causing CORS issues, because jsdom emulates CORS. So I had to reset that config option back to the jest default, which is `'node'`, like @wizardnet972 mentioned.

**Comment by nartc** [comment]
@alumni it is true that `jest-preset` sets `testEnvironment: 'jsdom'` but the `nrwl/node:lib` jest config overrides `testEnvironment` and sets it to `node`. Can you provide a reproduce?

**Comment by alumni** [comment]
@nartc I'm using the jest preset from `@nrwl/jest/preset` directly in my repo because it was the only one that can be used by extenal apps, so it's probably a different thing then. I would have expected that this preset doesn't change the jest defaults unless somehow required by the features introduced by nx.
