### ISSUE TITLE
feat(nx→g→move): extract module file independently to new package

### ISSUE THREAD

**Issue by zgover** [nrwl/nx#6408]
## Description

First simply inquiring clarification for the recent release (`v12.6.0-beta.6`) of Nx. My attention was pulled towards the new incorporation of automated package version management. However, is this feature for all libs and applications in the Nx monorepo (e.g. react, node and angular), from what I am assuming this release only provided this feature for angular. Please confirm in your response, if the latter is true; provide an expected eta for its release for all subpackages.

Secondly, I have some specific requests from the Nx team. These requests will add additional feature commands pertaining the move generator for the workspace CLI. Listing in order of the most desired, arising controversy within my dev teams desiring alternative monorepo frameworks are as follows☟☟

## Motivation

1. **[nx→g→move(lib-module-file)]** presently, Nx is lacking a solution for a tedious and exhausting operation while performing large refactoring tasks or rather more commonly, as a _said_ library scales—surpassing our designed max allocation for lib size and shared consumption.
2. **[nx→g→move(lib-pkg-dep)]** part two request for the monorepo wide automation for symversion mgmt., Nx consumers will revel in the efficient optimization of management to identify specific dependencies for each lib away from the global workspace in their own package.json.

## Suggested Implementation

1. **[nx→g→move(lib-module-file)]** independent extraction of file module into their own package, simply by adding a new feature to the workspace cli move generator. This would involve the removal module re-export in the package barrel additionally the migration of all imports consuming the module to another import declaration with the new lib.
2. **[nx→g→move(lib-pkg-dep)]** possibly moving/duplicating solely, the specific dependencies for each individual lib into their own respective local `package.json`? Otherwise another solution may be, add a new property in `nx.json` under each project entry with tags to specify the constraints to pkg imports?

**Comment by FrozenPandaz** [comment]
> My attention was pulled towards the new incorporation of automated package version management.

Sorry, I'm not sure which feature you're referring to. Is there a particular changelog entry that you can point to?

> [nx→g→move(lib-module-file)]

I'm not sure about VS Code, but in Webstorm, the following works pretty well:
1. Create a new lib
2. Using `Refactor this` to move something to the `src/index.ts` of the new lib. This will also update all imports of the symbol.
3. Then move the definition into a different file and re-export it from the `index.ts`.

Does that solve your issue? Sorry I don't have a solution for VS Code.. Maybe someone else does?

> specific dependencies for each lib away from the global workspace in their own package.json

This causes some issues and we don't recommend it. We don't plan on adding that to our generators as we advise against it.

It is not strictly forbidden though. You can feel free to add `package.json` files to libraries and run the installs. Tools like `webpack`, `jest`, .etc should all import from the right place.
