### ISSUE TITLE
More intelligent linting and testing when dependencies change

### ISSUE THREAD

**Issue by Ezard** [nrwl/nx#6410]
## Description
I would like for linting to only be triggered by changes to code, changes to lint config and/or changes to lint-related dependencies.
I would like for testing to only be triggered by changes to code, changes to a lib that is a dependency, and/or changes to an npm dependency that is used by an app/lib (or by one of its dependencies).

### Preface
We use [Renovate](https://github.com/renovatebot/renovate) for keeping our dependencies up-to-date, which works by updating dependencies one at a time (so that any failing tests are easily traced to a certain dependency upgrade). We have multiple Nx repos (1 per client), and therefore get a lot of dependency upgrade PRs, with linting/testing occurring in CI before anything gets merged. As we increase the number of repos using Nx, keeping the amount of time spent in CI to a minimum is becoming more important. Nx migrations are not usually used for upgrading dependencies, but we do periodically check to see if any need to be applied (and we also run them in the case of a failing dependency upgrade in case that resolves the issue).

### Linting
Currently, whenever any dependency in `package.json` changes, `nx affected:lint` causes every app and lib to be linted. However, the vast majority of dependencies aren't lint-related, so this is unnecessary work - if the code hasn't changed, the lint rules haven't changed, and lint-related dependencies haven't changed, then there's no point in linting everything. For example, a change to the `rxjs` dependency shouldn't trigger workspace-wide linting.

### Testing
Currently, whenever any dependency in `package.json` changes, `nx affected:lint` causes every app and lib to be tested. However, in cases where a dependency isn't related to an app/lib, this is unnecessary work. For example, if the `rxjs` dependency is changed, but `lib A` (and none of the other libs in its dependency chain) depend on `rxjs`, then in most cases there's no need to test that lib.

### Linting
Within `nx.json`, users should be able to specify which targets for which projects are affected by certain dependency changes. This could be handled by expanding the `implicitDependencies` config, so that something like the following is allowed:
```json
{
  "implicitDependencies": {
    "package.json": {
      "devDependencies": {
        "eslint": "*:lint"
      }
    },
  },
}
```
For scenarios where this should only apply to certain apps/libs, it should be possible to specify both the project and the target (e.g. `"eslint": ["lib1:lint", "lib2": "lint"]`), as well as a wildcard for all projects as in the above example.

### Testing
Nx should automatically determine which apps/libs are affected by each dependency for the purpose of testing, in the same way that it determines this when building an app with the `generatePackageJson` flag enabled. For cases where Nx isn't able to determine this (e.g. `class-transformer` when using NestJS - it's only normally used internally by `ValidationPipe`, and therefore Nx wouldn't see any imports), users should continue to be able to specify this in the `implicitDependencies` config.

## Notes
I'm unsure how this would work with `nx affected:apps` and `nx affected:libs`, since whether or not an app/lib is affected would be based on the target that's being invoked (i.e. a lib could be affected for linting purposes but not testing purposes).  A potential solution to this would be to retain the current behaviour, but allow the target to optionally be specified e.g. `nx affected:libs:lint`.

**Comment by wrslatz** [comment]
Similar feature that I think aligns with this request:
I'd love to set all `apps` and `libs` using `jest` as `implicitDependencies` of `jest.preset.js` instead of `*`, as I want to skip running `lint` and `e2e` tasks when only `jest` config has changed.

**Comment by wrslatz** [comment]
I'd also like to add `e2e` and `build` to the list of smarter task types that would be really helpful for us

**Comment by konstantintieber** [comment]
Hi @Ezard, we ran into the same issue at LeanIX and we combined the `nx dep-graph` and `nx affected` commands to solve the issue for us.

You can read about our [reusable GitHub Action](https://github.com/leanix/nx-affected-dependencies-action) here: https://engineering.leanix.net/blog/smarter-nx-affected-checks/

I think it would be great if this could be solved within the nx CLI without extra configuration, as the dep-graph already has all the information. Something like `nx run my-react-app:test --with-affected-deps`

**Comment by DaSchTour** [comment]
I was just thinking about exactly this. Changes to root eslint config or stylelint config could only affected specific targets. Or changing jest config or presets should only affected test target and not everything else.

**Comment by maxime1992** [comment]
Up.

**Comment by bryanjtc** [comment]
Any update on this?
