### ISSUE TITLE
Newly generated projects point to project.json location with \\ on windows instead of /

### ISSUE THREAD

**Issue by SvenBudak** [nrwl/nx#6411]
I collect cli commands for my team so they can quickly create basic structures. Here is an example:
```console
# Create Auth Lib
nx generate @nrwl/angular:library --name=auth --directory=features --lazy --prefix=auth --routing --simpleModuleName --standaloneConfig
# Create Auth Components
nx generate @schematics/angular:component --name=sign-in --project=features-auth --style=scss --changeDetection=OnPush --displayBlock --export --path=libs/features/auth/src/lib/components --skipTests
nx generate @schematics/angular:component --name=sign-out --project=features-auth --style=scss --changeDetection=OnPush --displayBlock --export --path=libs/features/auth/src/lib/components --skipTests
nx generate @schematics/angular:component --name=sign-up --project=features-auth --style=scss --changeDetection=OnPush --displayBlock --export --path=libs/features/auth/src/lib/components --skipTests
# Create Auth Layout
nx generate @schematics/angular:component --name=layout --project=features-auth --style=scss --changeDetection=OnPush --displayBlock --export --path=libs/features/auth/src/lib/layouts --skipTests
# Create Auth Views
nx generate @schematics/angular:component --name=view-sign-in --project=features-auth --style=scss --changeDetection=OnPush --displayBlock --export --path=libs/features/auth/src/lib/views --skipTests
nx generate @schematics/angular:component --name=view-sign-out --project=features-auth --style=scss --changeDetection=OnPush --displayBlock --export --path=libs/features/auth/src/lib/views --skipTests
nx generate @schematics/angular:component --name=view-sign-up --project=features-auth --style=scss --changeDetection=OnPush --displayBlock --export --path=libs/features/auth/src/lib/views --skipTests
```
Because I don't want my colleagues to have to enter every cli command by hand, I decided to try it with the generator: https://nx.dev/latest/angular/generators/composing-generators#composing-generators

However, I noticed that many options can not be passed:
```js
import { Tree } from '@nrwl/devkit';
import { Schema } from '@nrwl/workspace/src/generators/library/schema';
import { libraryGenerator } from '@nrwl/workspace/generators';

function createLibrary(tree: Tree, schema: Schema) {
  return libraryGenerator(tree, {
    name: schema.name ?? 'auth',
    directory: 'features',
    lazy: true, <<< Not accepted
    prefix: 'auth2', <<< Not accepted
    routing: true, <<< Not accepted
    simpleModuleName: true,
    standaloneConfig: true
  });
}
```

IDE Error Report:
![image](https://user-images.githubusercontent.com/4930169/126092004-8627187d-f6ee-46ef-8dce-7462be10298b.png)

CLI Error Report:
![image](https://user-images.githubusercontent.com/4930169/126092057-b6230c7f-e040-47a7-8c7e-63bbfaac18e4.png)

**Comment by SvenBudak** [comment]
Ich entschuldige mich vielmals. nach langer suche, habe ich herausgefunden, dass ich libraryGenerator von `@nrwl/angular/generators` importieren muss:

```
import { libraryGenerator } from '@nrwl/workspace/generators'; <<< WRONG
import { libraryGenerator } from '@nrwl/angular/generators'; <<< CORRECT
```

But i still think that there is a bug. when i check my `workspace.json`:

```json
{
  "version": 2,
  "projects": {
    "features-auth": "libs/features/auth", <<< CLI generated
    "features-auth2": "libs\\features\\auth2", <<< Generator generated
    "website": "apps/website",
    "website-e2e": "apps/website-e2e"
  },
  "cli": {
    "defaultCollection": "@nrwl/angular"
  },
  ...
}
```

Instead of `/` the generator adds `\\`. i am not sure this is a problem or not. but in fact that its different to the cli generated code... let me think that its maybe a bug.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

> I found out that I need to import `libraryGenerator` from `@nrwl/angular/generators`

Yes, that's the right import for the Angular library generator.

> And how can i generate components in current NX Version?

To generate a component you can do:

```typescript
import { wrapAngularDevkitSchematic } from '@nrwl/devkit/ngcli-adapter';

...

const componentSchematic = wrapAngularDevkitSchematic('@schematics/angular', 'component');
await componentSchematic(tree, {
  // options here
});

...
```

**Comment by leosvelperez** [comment]
@Coly010 could you take a look at the path separators that are generated in the workspace config?

**Comment by SvenBudak** [comment]
Thanks @leosvelperez! Maybe the problem in this issue: #6425 is because the path separators.

**Comment by Coly010** [comment]
@SvenBudak out of curiosity, are you using Windows?

**Comment by SvenBudak** [comment]
@Coly010 yes i am using windows 10

**Comment by AgentEnder** [comment]
@SvenBudak What is the output of `nx report`? This should be fixed in latest.

**Comment by SvenBudak** [comment]
@AgentEnder I submit my report in the other issue: https://github.com/nrwl/nx/issues/6425#issuecomment-885693038

**Comment by SvenBudak** [comment]
@AgentEnder Sry correct me if i am wrong, but it looks to me that it is fixed in 8e194f524184f4288179d51c80f776c0dcd11355 ?

**Comment by SvenBudak** [comment]
Hmm i upated all packages in my `package.json` and still have same issue. i was not able to figure out how to check what version of the cli i have installed globally. i didnt find any in the docs and `nx -v` or `nx -version` dosnt exist. But if it have nothing to do with the CLI, then the bug isnt fixed.

**Comment by AgentEnder** [comment]
Yeah, I was worried about that. It definitely still needs investigation. For reference, `nx report` is how to check nrwl package versions easily.

**Comment by SvenBudak** [comment]
ah thanks. then so i have nx not globally installed ;)
