### ISSUE TITLE
npx create-nx-workspace show wrong tutorial link on the screen

### ISSUE THREAD

**Issue by doggy8088** [nrwl/nx#6412]
## Current Behavior

![image](https://user-images.githubusercontent.com/88981/126104786-fe302605-fecb-4cc2-a659-98c26d65293a.png)

## Expected Behavior

The link should change to https://nx.dev/latest/node/tutorial/01-create-application

## Steps to Reproduce

1. Create app

    ```sh
    npx create-nx-workspace --preset=nest --name=example --appName=my-tool --cli=nx
    ```

### Failure Logs

N/A

### Environment

```log

>  NX  Report complete - copy this into the issue template

  Node : 14.17.1
  OS   : win32 x64
  npm  : 6.14.13
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.5.8
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.5.8
  @nrwl/eslint-plugin-nx : 12.5.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.8
  @nrwl/linter : 12.5.8
  @nrwl/nest : 12.5.8
  @nrwl/next : Not Found
  @nrwl/node : 12.5.8
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.8
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.8
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by doggy8088** [comment]
Many links in that page are also broken. I think this might need overall review.

![image](https://user-images.githubusercontent.com/88981/126105773-ce93fcbf-80bc-4f48-a2bd-69742e37c477.png)

**Comment by meeroslav** [comment]
Thank you @doggy8088. Fix is on the way

**Comment by meeroslav** [comment]
@bcabanes Can we also make sure that redirect from `nx.dev/node/...`, `nx.dev/angular/...` and `nx.dev/react/...`to appropriate `latest` version is set?
