### ISSUE TITLE
Coverage mismatch in combined code coverage output

### ISSUE THREAD

**Issue by dominikspiertz** [nrwl/nx#6413]
## Current Behavior
Since we updated our project to the latest version of nx (12.5.8) our tests fail inside our CI and locally due to an exceed of the coverage threshold. If the affected lib is tested, the coverage output is very different than the one that is outputted if every project / lib has been tested in the end.

## Expected Behavior
The accumulated coverage of all libs / apps should be the same as running each lib / app individually

## Steps to Reproduce
Start the tests with those parameters: `yarn affected:test --code-coverage`

### Failure Logs
![single output](https://user-images.githubusercontent.com/13203787/126152070-4f6a3083-f3df-4d75-b2d6-1026fbc87913.png)
![combined output](https://user-images.githubusercontent.com/13203787/126152074-c586f775-a132-4f05-ae08-f3f4b68909db.png)

### Environment
  Node : 15.12.0
  OS   : darwin x64
  yarn : 1.22.5
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.5.8
  @nrwl/cypress : 12.5.8
  @nrwl/devkit : 12.5.8
  @nrwl/eslint-plugin-nx : 12.5.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.8
  @nrwl/linter : 12.5.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.5.8
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.5.8
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.8
  @nrwl/web : 12.5.8
  @nrwl/workspace : 12.5.8
  @nrwl/storybook : 12.5.8
  @nrwl/gatsby : Not Found
  typescript : 4.0.8

**Comment by dominikspiertz** [comment]
This issue still persists in our code base. We now have multiple libraries that refer to each other (react). If I run libraryA that uses components from libraryB, the coverage output of libraryA contains entries of untested components from libraryB. libraryB components do not belong in the coverage report of libraryA, since they will not get tested at all. Therefore all referenced components from libraryB have 0% coverage and push the "real" coverage of libraryA to a false level. This way we cannot enforce coverage thresholds.

**Comment by barbados-clemens** [comment]
hi @dominikspiertz can you provide me a reproducible repo so I can take a closer look at this?
