### ISSUE TITLE
Preset React: use test() instead of it() for jest

### ISSUE THREAD

**Issue by Lonli-Lokli** [nrwl/nx#6415]
it()  method belongs to Karma, Jest spcific case is test()

## Description
Use correct method for testing with Jest

## Motivation
It's just correct now

## Suggested Implementation
Currently:

```
import { render } from '@testing-library/react';

import ReportTabsView from './report-tabs-view';

describe('ReportTabsView', () => {
  it('should render successfully', () => {
    const { baseElement } = render(<ReportTabsView />);
    expect(baseElement).toBeTruthy();
  });
});
```

Expected:

```
import { render } from '@testing-library/react';

import ReportTabsView from './report-tabs-view';

describe('ReportTabsView', () => {
  test('should render successfully', () => {
    const { baseElement } = render(<ReportTabsView />);
    expect(baseElement).toBeTruthy();
  });
});
```

**Comment by Ezard** [comment]
@Lonli-Lokli Jest supports both - `it` is an alias of `test` (see: https://jestjs.io/docs/api#testname-fn-timeout)

**Comment by Lonli-Lokli** [comment]
@Ezard Yep, I know it's just an alias. But the reason for this alias is that Jest appears later than Mocha or Jasmine, and they just give an option for those who decided to migrate from older frameworks.

Jets's own function is test and as for me it's much more intuitive for developers.

**Comment by Ezard** [comment]
@Lonli-Lokli sure, makes sense

However, some developers (including myself) find `it` to be more intuitive, so I guess the best solution would be to allow for a global setting somewhere which determines which variant Nx uses when generating code
