### ISSUE TITLE
Custom ordered projects in Workspace

### ISSUE THREAD

**Issue by alienfacepalm** [nrwl/nx#6419]
## Description
We have a lot of projects in our workspace file and we like to order them in Nx Console by type, so we put the apps on top, then the libs on bottom based on which projects are used more than others. However, everytime we use the generators it reorders them alphabetically, so we've given up on that. We'd like to be able to set a custom order. 

If we had known maybe we would have used alphabetical names, but it's too late for that now. 

## Motivation
It helps us onboard new devs easier and keeps Nx Console cleaner. It's a much better Nx Console DX, makes more logical sense. Even if it was just sorted by project TYPE it'd make more sense. 

## Suggested Implementation
An array of project keys in nx.json in custom order.

**Comment by oreporan** [comment]
+1
