### ISSUE TITLE
Custom workspace schematic does not support 'directory' option

### ISSUE THREAD

**Issue by ThomasBurleson** [nrwl/nx#642]
The custom workspace schematic generates a schematic for a custom 'lib':

```ts
import { chain, externalSchematic, Rule } from '@angular-devkit/schematics';

export default function(schema: any): Rule {
  return chain([
    externalSchematic('@nrwl/schematics', 'lib', { name: schema.name  })
  ]);
}
```

> This schematic does not support the `--directory=<parent folder>` option.

Here is what **should be** generated:

```ts
import {
  chain,
  externalSchematic,
  Rule
} from '@angular-devkit/schematics';

export default function(schema: any): Rule {
  return chain([
    externalSchematic('@nrwl/schematics', 'lib', {
      name: schema.name,
      directory : schema.directory
    })
  ]);
}
```

**Comment by FrozenPandaz** [comment]
Closing thing because I believe this was discussed internally and the conclusion was that `workspace-schematic` schematic only generates a template for users to update and not a fully featured `workspace-schematic`.
