### ISSUE TITLE
@nrwl/nx/enforce-module-boundaries erroring when importing type

### ISSUE THREAD

**Issue by joemckie** [nrwl/nx#6421]
## Current Behavior
I am receiving an error from `@nrwl/nx/enforce-module-boundaries` reporting that I have a circular dependency. This is true, but one side only imports a type from the other.

This is the dependency structure:

```ts
// stacks/RootStack.tsx

import { HomeScreen } from '@.../home-page';

export type RootStackParamList = {};
```

```ts
// home-page/HomeScreen.tsx

import type { RootStackParamList } from '@.../stacks';

export const HomeScreen = () => <div />;
```

## Expected Behavior
This should perform similar to TypeScript, and should not error when using the `type` keyword.

## Steps to Reproduce
Checkout https://github.com/joemckie/nx-deps-test

Interestingly enough, I can't get this error to appear on https://github.com/nrwl/nx-examples. Not sure if that is a config issue?

**Comment by meeroslav** [comment]
The workspace should not care whether you are importing a `type` or a `function`. It's properly signaling you that there is a circular dependency. Nx goes beyond simple transpilability (what compiles and what doesn't) and shows also fundamental issues with the design/architecture.

If you have a type that's used in multiple applications, the correct thing to do would be to extract it into shared `lib` e.g. `root-stack-models`.

**Comment by joemckie** [comment]
@meeroslav thanks for responding! I figured that might be the reason.

To explain my use case a bit more thoroughly, I'm using React Navigation to build up a stack of screens for an app.  `RootStackParamList` contains keys of the navigable pages in the stack, and it also exports a React component that renders the stack (which is where the screens are imported). Each of the screens takes in `RootStackParamList` to add type safety when navigating.

Currently I have a structure like this:

```
apps/
├─ customer-app/
libs/
├─ customer-app/
│  ├─ shared/
│  │  ├─ stacks/
├─ home-page/
│  ├─ ui-home-page/

```

Are you suggesting a structure like this?

```
apps/
├─ customer-app/
libs/
├─ customer-app/
│  ├─ shared/
│  │  ├─ stacks/
│  │  │  ├─ ui/
│  │  │  ├─ types/
├─ home-page/
│  ├─ ui-home-page/
```

**Comment by joemckie** [comment]
I'm also unsure as to how low level to make libs (fairly new to NX here). Is it common practice to bundle related code into a single lib like this:

```
libs/
├─ ui-button/
│  ├─ PrimaryButton.tsx
│  ├─ SecondaryButton.tsx
```

Or is it better to split each component out into their own libs like this?

```
libs/
├─ ui-primary-button/
│  ├─ PrimaryButton.tsx
├─ ui-secondary-button/
│  ├─ SecondaryButton.tsx
```

**Comment by meeroslav** [comment]
> @meeroslav thanks for responding! I figured that might be the reason.
> 
> To explain my use case a bit more thoroughly, I'm using React Navigation to build up a stack of screens for an app. `RootStackParamList` contains keys of the navigable pages in the stack, and it also exports a React component that renders the stack (which is where the screens are imported). Each of the screens takes in `RootStackParamList` to add type safety when navigating.
> 
> Currently I have a structure like this:
> 
> ```
> apps/
> ├─ customer-app/
> libs/
> ├─ customer-app/
> │  ├─ shared/
> │  │  ├─ stacks/
> ├─ home-page/
> │  ├─ ui-home-page/
> ```
> 
> Are you suggesting a structure like this?
> 
> ```
> apps/
> ├─ customer-app/
> libs/
> ├─ customer-app/
> │  ├─ shared/
> │  │  ├─ stacks/
> │  │  │  ├─ ui/
> │  │  │  ├─ types/
> ├─ home-page/
> │  ├─ ui-home-page/
> ```

What I would suggest is something along with this (if you have multiple apps):
```bash
apps/
├─ customer-app/
├─ home-page-app/
libs/
├─ customer-app/
│  ├─ ui-shared/ #includes stacks or have a separate `stacks` project
├─ home-page/ 
│  ├─ ui-home-page/ # this feature belongs to a different app
├─ shared/
│  ├─ stacks-models/ # these are shared between apps and/or libs
```

The `libs\customer-app` contains libs that represent features, ui components, or helper libs used only by `customer-app` application. If `home-page` belongs to the customer app, it should be also under the `libs\customer-app` folder.
The same goes for shared `stacks-models`.

So in the case of a single app it would probably be:
```bash
apps/
├─ customer-app/
libs/
├─ customer-app/
│  ├─ ui-shared/ # ui elements share between app and/or multiple feature libs
│  ├─ ui-home-page/ # single feature lib
│  ├─ stacks-models/ # interfaces
```

**Comment by meeroslav** [comment]
> I'm also unsure as to how low level to make libs (fairly new to NX here). Is it common practice to bundle related code into a single lib like this:
> 
> ```
> libs/
> ├─ ui-button/
> │  ├─ PrimaryButton.tsx
> │  ├─ SecondaryButton.tsx
> ```
> 
> Or is it better to split each component out into their own libs like this?
> 
> ```
> libs/
> ├─ ui-primary-button/
> │  ├─ PrimaryButton.tsx
> ├─ ui-secondary-button/
> │  ├─ SecondaryButton.tsx
> ```

My suggestion would be to keep them together in `ui-button` as most likely you'll often import both of them to target projects. You could even have something like `ui-components` that could have buttons, links, cards, etc. if that makes sense.

Think of it as an npm package. Would you rather install single `material-ui` or install separate `material-ui-button`, `material-ui-cards` etc.

There are cases when you'd like to extract specific component(s) into a separate project. But there's no right or wrong. Whatever feels most ergonomic to you while respecting the logical dependency boundaries is the best for you.

**Comment by joemckie** [comment]
That makes sense 😄  thanks for the in-depth answers!

**Comment by meeroslav** [comment]
I'm glad if I can help. Is it ok if I close this issue?

**Comment by joemckie** [comment]
No problem 😄
