### ISSUE TITLE
Enable blockchain development support (Truffle, HardHat)

### ISSUE THREAD

**Issue by un33k** [nrwl/nx#6431]
## Description
Truffle and Hardhat are the two leading javascript frameworks enabling Ethereum development in nodeJs.  Setting up `truffle` and/or `hardhat` is not hard, but very repetitive and challenging on the first try.  It would be great to have `@nrwl/truffle` and `@nrwl/hardhat` support.

## Motivation
Smart contracts development is a huge market and it would be great to spread NX's greatness over on to the block-chain development as well. 

## Suggested Implementation
`@nrwl/truffle` and `@nrwl/hardhat` to be added, based on their configuration and setup published on their websites.

## Alternate Implementations
Use the `scripts` commands and nail-down the commands to directly run `truffle` &| `hardhat` within an NX framework, without making NX aware of the above frameworks. 

## Related Info
- https://www.trufflesuite.com/
- https://hardhat.org/

**Comment by leosvelperez** [comment]
Thanks for suggesting this!

We don't have a plan to add them as part of the core Nx plugins, but they can definitely be implemented as community plugins.
