### ISSUE TITLE
Failed to format 'angular.json' when creating new Nest application with standalone config in React workspace

### ISSUE THREAD

**Issue by trumbitta** [nrwl/nx#6452]
## Current Behavior
When trying to create a new Nest application in a workspace v2 with no Angular whatsoever, Nx console dry run fails with an odd message

## Expected Behavior
The dry run succeedes

## Steps to Reproduce

- Create empty 12.5.8 workspace, no Nx Cloud
- add `@nrwl/react` and `@nrwl/nest`
- start creating Nest application via Nx console, with standalone config

### Failure Logs

```
> Executing task: nx generate @nrwl/nest:application --name=backend-simulator --frontendProject=frontend --standaloneConfig --no-interactive <

Failed to format: /angular.json
Error: 'project.json' files are incompatible with version 1 workspace schemas.
    at /Users/w.ghelfi/dev/Iungo/frontend-demo/giant-robots/node_modules/@nrwl/tao/src/shared/workspace.js:208:19
    at Array.forEach (<anonymous>)
    at toOldFormatOrNull (/Users/w.ghelfi/dev/Iungo/frontend-demo/giant-robots/node_modules/@nrwl/tao/src/shared/workspace.js:206:37)
    at Object.reformattedWorkspaceJsonOrNull (/Users/w.ghelfi/dev/Iungo/frontend-demo/giant-robots/node_modules/@nrwl/tao/src/shared/workspace.js:167:53)
    at updateWorkspaceJsonToMatchFormatVersion (/Users/w.ghelfi/dev/Iungo/frontend-demo/giant-robots/node_modules/@nrwl/devkit/src/generators/format-files.js:59:41)
    at Object.<anonymous> (/Users/w.ghelfi/dev/Iungo/frontend-demo/giant-robots/node_modules/@nrwl/devkit/src/generators/format-files.js:21:9)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/w.ghelfi/dev/Iungo/frontend-demo/giant-robots/node_modules/tslib/tslib.js:114:62)
```

### Environment

```
>  NX  Report complete - copy this into the issue template

  Node : 12.16.1
  OS   : darwin x64
  npm  : 7.6.2
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.5.8
  @nrwl/cypress : 12.5.8
  @nrwl/devkit : 12.5.8
  @nrwl/eslint-plugin-nx : 12.5.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.8
  @nrwl/linter : 12.5.8
  @nrwl/nest : 12.5.8
  @nrwl/next : Not Found
  @nrwl/node : 12.5.8
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.5.8
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.8
  @nrwl/web : 12.5.8
  @nrwl/workspace : 12.5.8
  @nrwl/storybook : 12.5.8
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This particular issue with NestJS app schematic should be resolved in the next version, when this https://github.com/nrwl/nx/pull/6157 gets released and the NestJS plugin is fully migrated to Nx DevKit.

That said, @AgentEnder it seems there's an issue with the Angular CLI compatibility layer and the configuration per project, I was able to reproduce this issue, though the project was created successfully for me. Could you please take a look?

**Comment by AgentEnder** [comment]
@leosvelperez I'll take a look soon, its possible this is something that is fixed in master already.

**Comment by trumbitta** [comment]
> Thanks for reporting this!
> 
> 
> 
> This particular issue with NestJS app schematic should be resolved in the next version, when this https://github.com/nrwl/nx/pull/6157 gets released and the NestJS plugin is fully migrated to Nx DevKit.
> 
> 
> 
> That said, @AgentEnder it seems there's an issue with the Angular CLI compatibility layer and the configuration per project, I was able to reproduce this issue, though the project was created successfully for me. Could you please take a look?

Thanks 🙏 I should add that I since went back to check and, despite the error I reported, the project was created successfully for me too.

**Comment by AgentEnder** [comment]
This persists in 12.5.9, going to look into what wrapper is hitting the error.
