### ISSUE TITLE
Hasher ignores implicitDependencies values in nx.json

### ISSUE THREAD

**Issue by statop** [nrwl/nx#6461]
## Current Behavior
For hashing, any key in nx.json implicitDependencies applies to _all_ projects. 

## Expected Behavior
The behavior described in https://nx.dev/latest/react/core-concepts/configuration#implicit-dependencies for globalFile.

## Steps to Reproduce

add an implicitDependencies entry like -
```
    "some/dir/**": [
      "some-project"
    ],
```

build all your projects, then change something in some/dir/ , and try to build again, it will build everything again instead of using cache.

The code related to this is here - https://github.com/nrwl/nx/blob/master/packages/workspace/src/core/hasher/hasher.ts#L193

it does not look like it has ever worked as intended.

### Failure Logs
none

### Environment
>  NX  Report complete - copy this into the issue template

  Node : 12.22.1
  OS   : darwin x64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : 12.5.8
  @nrwl/cli : 12.5.8
  @nrwl/cypress : 12.5.8
  @nrwl/devkit : 12.5.8
  @nrwl/eslint-plugin-nx : 12.5.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.8
  @nrwl/linter : 12.5.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.5.8
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.8
  @nrwl/web : 12.5.8
  @nrwl/workspace : 12.5.8
  @nrwl/storybook : 12.5.8
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by ydmitry** [comment]
Have the same issue

**Comment by ydmitry** [comment]
Any updates on this bug?
