### ISSUE TITLE
CI configuration of storybook runs watcher

### ISSUE THREAD

**Issue by bgutschke** [nrwl/nx#6463]
## Current Behavior
When creating the Storybook configuration file watchers are activated for CI runs.

## Expected Behavior
File watchers should be deactivated for CI runs.

## Steps to Reproduce
Create new Storybook configuration using the storybook generator. 

The workspace.json will contain something along the lines of:

 ```json
"storybook": {
  "executor": "@nrwl/storybook:storybook",
  "options": {
    "uiFramework": "@storybook/angular",
    "port": 4400,
    "config": {
      "configFolder": "libs/shared/ui/.storybook"
    }
  },
  "configurations": {
    "ci": {
      "quiet": true,
    }
  }
},
```

`configurations.ci` contains the option `quiet: true`, but is missing `watch: false,`, 

### Environment
```
Node : 14.17.0
OS   : darwin x64
yarn : 1.22.10

nx : Not Found
@nrwl/angular : Not Found
@nrwl/cli : 12.6.0-beta.10
@nrwl/cypress : 12.6.0-beta.10
@nrwl/devkit : 12.6.0-beta.10
@nrwl/eslint-plugin-nx : 12.6.0-beta.10
@nrwl/express : Not Found
@nrwl/jest : 12.6.0-beta.10
@nrwl/linter : 12.6.0-beta.10
@nrwl/nest : Not Found
@nrwl/next : 12.6.0-beta.10
@nrwl/node : 12.6.0-beta.10
@nrwl/nx-cloud : 12.2.7
@nrwl/react : 12.6.0-beta.10
@nrwl/schematics : Not Found
@nrwl/tao : 12.6.0-beta.10
@nrwl/web : 12.6.0-beta.10
@nrwl/workspace : 12.6.0-beta.10
@nrwl/storybook : 12.6.0-beta.10
@nrwl/gatsby : Not Found
typescript : 4.3.5
```

**Comment by juristr** [comment]
@bgutschke sorry for the late reply, please see my message here: https://github.com/nrwl/nx/pull/6464#issuecomment-1032548214

I'm going to close this for now as we're working on a better integration with Storybook under the hood which should solve this issue as well.
