### ISSUE TITLE
Sorting of paths in tsconfig.base.json can break things

### ISSUE THREAD

**Issue by statop** [nrwl/nx#6472]
## Current Behavior
Sorting of paths in tsconfig.base.json can break things. The order of the paths matters. 

This broke in this pr - https://github.com/nrwl/nx/pull/5945

## Expected Behavior
Paths in tsconfig.base.json are not sorted.

## Steps to Reproduce

Sometimes it is useful to redirect something specific with paths and have everything else handled with a wildcard, for example -
```
      "foo/bar/cat": ["libs/some/other/whatever/cat"],
      "foo/bar/*": ["libs/foo/bar/*"],
```
This breaks if the paths are sorted, sorting would result in -
```
      "foo/bar/*": ["libs/foo/bar/*"],
      "foo/bar/cat": ["libs/some/other/whatever/cat"],
```
which basically causes the second statement to be ignored by typescript.

### Failure Logs
none

### Environment

>  NX  Report complete - copy this into the issue template

  Node : 12.22.1
  OS   : darwin x64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : 12.5.8
  @nrwl/cli : 12.5.8
  @nrwl/cypress : 12.5.8
  @nrwl/devkit : 12.5.8
  @nrwl/eslint-plugin-nx : 12.5.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.8
  @nrwl/linter : 12.5.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.5.8
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.8
  @nrwl/web : 12.5.8
  @nrwl/workspace : 12.5.8
  @nrwl/storybook : 12.5.8
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by nzacca** [comment]
Is there a way to opt-out of this new sorting behavior? The original discussion [mentions being able to opt-out](https://github.com/nrwl/nx/issues/2607#issuecomment-596058476) but I'm not seeing a config to do this.

We have also tried to use the `--files` argument to only format specified files but the new sorting does not appear to respect that argument.
