### ISSUE TITLE
docs support multi languages

### ISSUE THREAD

**Issue by Muromi-Rikka** [nrwl/nx#6486]
### Discussed in https://github.com/nrwl/nx/discussions/6466

<div type='discussions-op-text'>

<sup>Originally posted by **Muromi-Rikka** July 22, 2021</sup>
I plan to translate the document to Chinese, how do I do it?</div>

**Comment by bcabanes** [comment]
Hi!

Thank you for taking the time to open an issue for it, though, we do not have plan currently to support translation of the documentation.
