### ISSUE TITLE
node_modules/@nrwl/schematics/src/tslint missing

### ISSUE THREAD

**Issue by xmlking** [nrwl/nx#651]
my generated project `tslint.json` has `node_modules/@nrwl/schematics/src/tslint` but con't find this file in `node_modules/@nrwl/schematics/src` directory !
 
```json
{
  "rulesDirectory": [
    "node_modules/codelyzer",
    "node_modules/@nrwl/schematics/src/tslint"
  ]
}
```

**Comment by vsavkin** [comment]
The rules directory property points to an array of directories, not to files. You should have the "node_modules/@nrwl/schematics/src/tslint" directory present. If you don't, please reinstall your node modules.

If the directory is misconfigured, you should see an error that will look like this:

```
Failed to load /private/tmp/nx/proj/apps/myapp/tslint.json: Could not find custom rule directory: node_modules/@nrwl/schematics/src/tslint
```

**Comment by un33k** [comment]
@vsavkin freshly reinstalled node_modules. There is no such a directory. 

![nrwl-missing-lint-rules](https://user-images.githubusercontent.com/407537/62481282-063f0100-b780-11e9-907a-92fcbf38c638.PNG)

**Comment by un33k** [comment]
It seems `create-nx-workspace foobar` has this problem, but if you do `npm init nx-workspace foobar`, then you won't run into this problem.

**Comment by adover** [comment]
@un33k how would you fix this in an existing NX workspace?

**Comment by tcoz** [comment]
Interested in how to fix this in an existing workspace as well. I installed @nrwl/schematics and it does not install the tslint file in the indicated path. I'm going to look into explicitly installing @nrwl/angular schematics or some such.
