### ISSUE TITLE
dep-graph falls over with 400+ libs

### ISSUE THREAD

**Issue by bryanrideshark** [nrwl/nx#6517]
## Current Behavior

We have a very large project which causes dep-graph to fall over, when trying to focus on a particular part in the graph.

## Expected Behavior

It shouldn't lock up trying to render 500+ libraries.

## Steps to Reproduce

Create an nx monorepo with 500+ libs, all with varying degrees of interconnectivity.
Run `nx dep-graph`
Try to focus on one module in the dep-graph.

### Failure Logs

No failure logs - Processor / browser just locks up.

### Environment

Chrome, on a relatively powerful computer (i7, 24GB ram)

**Comment by un33k** [comment]
@bryanrideshark `I agree` - the current graph engine has passed its initial usefulness except for minimal affected libs.  In an  enterprise projects, with 100s of libs, the map is very messy and not visible, navigable or seamlessly useful. 

<img width="auto" src="https://raw.githubusercontent.com/neekware/fullerstack/main/libs/agx-assets/src/lib/images/tech/dep-graph-front.png">

**Comment by un33k** [comment]
`Something like this would be great` - There must be a library that does this already.  Keeping vertical levels is tremendously useful, in layering dependancies and enforcing via eslint. 

![privilege-hierarchy-graph](https://user-images.githubusercontent.com/407537/129600564-dd252cde-14a2-41b3-80c9-78047f119ff8.png)
