### ISSUE TITLE
Cannot combine mfe with incremental build

### ISSUE THREAD

**Issue by beatlang** [nrwl/nx#6526]
## Current Behavior
I think the approaches of mfe and incremental build are great and would like to start with both in our new project. But if I add a Module Federation configuration to the workspace with nx g @nrwl/angular:setup-mfe and then reference a buildable library in this app, the incremental build fails for the app with no additional information.
![image](https://user-images.githubusercontent.com/63296777/127270873-780b347f-9657-4ccc-a895-bd307969e577.png)

## Expected Behavior
The build works.

## Steps to Reproduce
I add a Module Federation configuration to the workspace with nx g @nrwl/angular:setup-mfe and then reference a buildable library in this app, the incremental build fails for the app.

**Comment by Coly010** [comment]
Hi, I've tried this really quickly locally with Nx 12.7.1 and cannot reproduce it. Are you able to try again with the latest Nx?
And if you're still having problems could you provide a minimal reproduction so I could investigate further?

**Comment by daBishMan** [comment]
`⠋ Generating browser application bundles (phase: setup)...Cannot find module 'webpack/lib/container/ModuleFederationPlugin'
Require stack:
- /Users/jaybishtawi/code/xperiments/front-end/apps/shell/webpack.config.js
- /Users/jaybishtawi/code/xperiments/front-end/apps/shell/webpack.prod.config.js
- /Users/jaybishtawi/code/xperiments/front-end/node_modules/@nrwl/angular/src/builders/webpack-server/webpack-server.impl.js
- /Users/jaybishtawi/code/xperiments/front-end/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /Users/jaybishtawi/code/xperiments/front-end/node_modules/@angular-devkit/architect/node/index.js
- /Users/jaybishtawi/code/xperiments/front-end/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
- /Users/jaybishtawi/code/xperiments/front-end/node_modules/@nrwl/tao/src/commands/run.js
- /Users/jaybishtawi/code/xperiments/front-end/node_modules/@nrwl/tao/index.js
- /Users/jaybishtawi/code/xperiments/front-end/node_modules/@nrwl/cli/lib/run-cli.js`

I am experiencing something similar when I build.  

I crated a new nx workspace with angular `"@nrwl/cli": "12.7.2",`  ` "@nrwl/angular": "12.7.2",` using these versions.

I ran the following command
nx generate @nrwl/angular:setup-mfe --appName=shell --mfeType=host  --port=5500     

when trying to serve I get the above error
