### ISSUE TITLE
@nrwl/angular:webpack-server fails when `defaultConfiguration` is blank

### ISSUE THREAD

**Issue by chrisfitz** [nrwl/nx#6533]
## Current Behavior
When running `nx serve [app]` without a configuration specified, the command will fail if the `defaultConfiguration` key in the task is left blank.

It appears this is caused by the builder assuming that the `defaultConfiguration` key is not empty and provides no fallback to use the task's default options when it is. The problematic part of the build can be seen on these lines: https://github.com/nrwl/nx/blob/ec414e5840a7076554fbe1a541d2e9ff26daeef9/packages/angular/src/builders/webpack-server/webpack-server.impl.ts#L27-L29

Changing it to the following will fix this issue and serve the application as expected:
```
const selectedConfiguration = parsedBrowserTarget.configuration
    ? buildTarget.configurations[parsedBrowserTarget.configuration]
    : buildTarget.configurations[buildTarget.defaultConfiguration] || buildTarget.options;
```

**Note:** The `defaultConfiguration` field was added to my "angular.json" file with no value during a migration.

## Expected Behavior
When running the task the builder correctly falls back to using the task's default options rather than throwing an error.

## Steps to Reproduce
This can be reproduced with the https://github.com/nrwl/nx-examples project by changing the following line https://github.com/nrwl/nx-examples/blob/master/apps/products/project.json#L73

From:
```
"executor": "@angular-devkit/build-angular:dev-server",
```
To:
```
"executor": "@nrwl/angular:webpack-server",
```
**Note:** The `defaultConfiguration` field is not present for any task for this example project, but the result is the same as if it was present with a blank value.

### Failure Logs
```
$ yarn nx serve products
yarn run v1.22.10
$ nx serve products

> nx run products:serve
Required property 'browserTarget' is missing

———————————————————————————————————————————————

>  NX   ERROR  Running target "products:serve" failed

  Failed tasks:

  - products:serve

  Hint: run the command with --verbose for more details.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment
```
Node : 12.19.0
OS   : darwin x64
yarn : 1.22.10

nx : Not Found
@nrwl/angular : 12.6.2
@nrwl/cli : 12.6.2
@nrwl/cypress : 12.6.2
@nrwl/devkit : 12.6.2
@nrwl/eslint-plugin-nx : 12.6.2
@nrwl/express : Not Found
@nrwl/jest : 12.6.2
@nrwl/linter : 12.6.2
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : 12.6.2
@nrwl/nx-cloud : Not Found
@nrwl/react : Not Found
@nrwl/schematics : Not Found
@nrwl/tao : 12.6.2
@nrwl/web : 12.6.2
@nrwl/workspace : 12.6.2
@nrwl/storybook : 12.6.2
@nrwl/gatsby : Not Found
typescript : 4.3.5
```

**Comment by Camo30** [comment]
Same issue here. It should also work with empty `defaultConfiguration` value.
