### ISSUE TITLE
Found an outdated version of webpack-node-externals. Falling back to webpack 4

### ISSUE THREAD

**Issue by DmitryEfimenko** [nrwl/nx#6538]
## Current Behavior

After upgrading my workspace to the latest nx (12.6.2), my node project outputs the following warning when compiling it:
>  \> NX  Using webpack 5. Reason: detected version 5 in node_modules/webpack/package.json       
    Found an outdated version of webpack-node-externals
    If you want to use webpack 5, try installing compatible versions of the plugins.
    See: https://nx.dev/guides/webpack-5
    \> NX  Falling back to webpack 4 due to incompatible plugin versions

When running `npm ls webpack-node-externals` I see the following output:
```sh
+-- @nrwl/cypress@12.6.2
| `-- webpack-node-externals@1.7.2         
`-- @nrwl/node@12.6.2
  `-- webpack-node-externals@1.7.2
```

It seems that the `@nrwl/cypress` and `@nrwl/node` need to update their deps.

## Expected Behavior
I suppose it's not as critical for a node app, but I expect Webpack 5 to be used

## Steps to Reproduce
* Create a workspace with a node application
* Run the command to start the node server
* Observe the output

### Environment
Node : 14.15.0
  OS   : win32 x64
  npm  : 6.14.8

  nx : Not Found
  @nrwl/angular : 12.6.2
  @nrwl/cli : 12.6.2
  @nrwl/cypress : 12.6.2
  @nrwl/devkit : 12.6.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.2
  @nrwl/linter : 12.6.2
  @nrwl/nest : 12.6.2
  @nrwl/next : Not Found
  @nrwl/node : 12.6.2
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.2
  @nrwl/web : Not Found
  @nrwl/workspace : 12.6.2
  @nrwl/storybook : 12.6.2
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by jaysoo** [comment]
Hi @DmitryEfimenko the log can be safely ignored for now. We are migrating all out plugins to webpack 5 for Nx 13, so for now Nx will try to use webpack 5 if it is installed in the workspace. The message you are seeing is because the `webpack-node-externals` plugin isn't compatible, but this shouldn't matter.

We will patch this so the warning logs don't appear for Cypress tests since it doesn't matter.

Sorry for the confusion!

**Comment by jaysoo** [comment]
The latest packages will be upgraded for Nx 13.

**Comment by DmitryEfimenko** [comment]
Thank you for the clarification. Feel free to close the issue or to leave it open for your own tracking purposes. Looking forward to v13!
