### ISSUE TITLE
npm run affected:build fails

### ISSUE THREAD

**Issue by dgroh** [nrwl/nx#654]
When I run `npm run affected:build` I get the following error:

> lotes-maps@0.0.0 affected:build D:\Projekte\Git\lotes-maps
> nx affected:build
> Invalid options provided
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! lotes-maps@0.0.0 affected:build: `nx affected:build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the lotes-maps@0.0.0 affected:build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\dgroh\AppData\Roaming\npm-cache\_logs\2018-07-30T16_35_45_489Z-debug.log

That is my configuration:

```
Angular CLI: 6.0.1
Node: 8.11.3
OS: win32 x64
Angular: 6.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.0.0
typescript                        2.7.2
webpack                           4.8.3

```

**Comment by electrichead** [comment]
You need to provide criteria to diff against (specify `files` or `--uncommitted` or two SHAs to compare against).

e.g. `npm run affected:build -- --uncommitted`

**Comment by dgroh** [comment]
how do I automate this in my CI or in a git hook via Husky?What if I want to run this by every `pre-push`?
