### ISSUE TITLE
prod build for next app not generating correct dependency structure in package.json

### ISSUE THREAD

**Issue by writam-roy** [nrwl/nx#6542]
I have made a plugin which generates a next app kind of a structure with some customizations as needed,the app creation using the plugin is fine in all respect,except the fact that once I do prod build for the app it is unable to gather all necessary dependency in the dist folder package.json,hence it causes issues in deployment stage.

I tried modifying the file : libs\my-plugin\src\executors\build\build\lib\create-package-json.ts,without success as the generated dist folder package.json still doesnt have all dependencies needed
to include all dependencies of my choice,I tried like this, can you guide if its the correct way of doing it?(check : packageJson.dependencies)

----------------------------------------------------------------------------------------------------------
```ts
import { ExecutorContext } from '@nrwl/devkit';

import { createProjectGraphAsync } from '@nrwl/workspace/src/core/project-graph';
import { writeJsonFile } from '@nrwl/workspace/src/utilities/fileutils';
import { createPackageJson as generatePackageJson } from '@nrwl/workspace/src/utilities/create-package-json';

import { NextBuildBuilderOptions } from '../../../../utils/types';

export async function createPackageJson(
  options: NextBuildBuilderOptions,
  context: ExecutorContext
) {
  const depGraph = createProjectGraphAsync();
  const packageJson = generatePackageJson(context.projectName, await depGraph, {
    root: context.root,
    projectRoot: context.workspace.projects[context.projectName].sourceRoot,
  });
  if (!packageJson.scripts) {
    packageJson.scripts = {};
  }
  packageJson.scripts.start = 'next start';
  if (!packageJson.devDependencies) {
    packageJson.devDependencies = {};
  }
  const nrwlWorkspaceNode = (await depGraph).nodes['npm:@nrwl/workspace'];

  packageJson.dependencies={
     "next-compose-plugins": "2.2.1",
    "@zeit/next-css": "^1.0.1",
    "next-optimized-images": "^2.6.2",
    "next-transpile-modules": "^5.0.0",
    "@zeit/next-sass": "^1.0.1",
    "lodash-webpack-plugin": "^0.11.6",
    "@next/bundle-analyzer": "^10.0.3",
    "core-js": "^3.14.0",
    "react": "17.0.2",
    "next": "^10.2.3",
    "react-dom": "17.0.2",
    "sass": "^1.35.1",
    "swagger-ui-express": "^4.1.6",
    "swagger-jsdoc": "^6.1.0",
    "isomorphic-fetch": "^3.0.0",
    "tslib": "^2.2.0",
    "smoothscroll-polyfill": "^0.4.4"
  };
  if (nrwlWorkspaceNode) {
    packageJson.devDependencies['@nrwl/workspace'] =
      nrwlWorkspaceNode.data.version;
  }
  writeJsonFile(`${options.outputPath}/package.json`, packageJson);
}
```
------------------------------------------------------------------------------------------------------------------
Any help on this would be greatly appreciated

**Comment by FrozenPandaz** [comment]
Sorry, I don't quite understand what the expected behavior is.

Could you provide a repo and the dependency that is missing from the `package.json` please?

**Comment by writam-roy** [comment]
Hi @FrozenPandaz ,my query to sum up is mostly in regards to the fact that whether I can  add a few dependencies of my own using the 
"create-package-json.ts" which I guess is used during the build process of a next app in either dev or general dependencies like this - 
packageJson.dependencies={
     "next-compose-plugins": "2.2.1",
    "@zeit/next-css": "^1.0.1",
    "next-optimized-images": "^2.6.2",
    "next-transpile-modules": "^5.0.0",
    "@zeit/next-sass": "^1.0.1",
    "lodash-webpack-plugin": "^0.11.6",
    "@next/bundle-analyzer": "^10.0.3",
    "core-js": "^3.14.0",
    "react": "17.0.2",
    "next": "^10.2.3",
    "react-dom": "17.0.2",
    "sass": "^1.35.1",
    "swagger-ui-express": "^4.1.6",
    "swagger-jsdoc": "^6.1.0",
    "isomorphic-fetch": "^3.0.0",
    "tslib": "^2.2.0",
    "smoothscroll-polyfill": "^0.4.4"
  };
