### ISSUE TITLE
Faster Type Checking for Git Hooks

### ISSUE THREAD

**Issue by david-morris** [nrwl/nx#6547]
## Description

I would like to be able to type-check quickly.  Specifically, I'd like an option to tell nx to return nonzero from an `affected` or `run-many`/`all` command, especially a type-check, as soon as one module failed, and I would like an option to pass `--incremental` (rather than `--incremental=true`, which causes an error) to `tsc` in my type check.
## Motivation

I use nx to manage a monorepo in a professional setting, and we would like to run quick type-checks automatically in git pre-push hooks to minimize cases where people are pulled away from tasks to review code which isn't ready to be merged.  We use graphical frontends for git which don't show the git output, leaving some of us simply confused as to why a push is taking so long.

## Suggested Implementation

I would like to see a `--fail-fast` option which applies to `all`, `run-many`, and `affected`, and I would like to see flags passed inwards, especially to tsc, to not have an `=true` added to them.

## Alternate Implementations

I imagine that there's a historical or technical reason why flags passed inwards are modified, so a config setting controlling this behavior and/or `--raw-subprocess-flags="--flag --otherflag"` parameter might be more appropriate.

**Comment by david-morris** [comment]
For others out there, I added `--incremental` to my `workspace.json` under specific targets, and found that I got a better speedup only adding `--incremental` to modules that took a long time to build.  However, I still want to be able to turn this flag off for staging and prod, since we compose a container during deployment.

**Comment by KeKs0r** [comment]
@david-morris I would be curious about how you setup your type check command. I have created libs over time with different versions with NX and not yet have found a proper setup to run a type check just for a lib or an app. 

Would you be able to share your setup?

**Comment by david-morris** [comment]
@KeKs0r we set up our type check command pretty ad-hoc.  In our monorepo's workspace.json, under the top-level projects key:
```
        "type-check": {
          "executor": "@nrwl/workspace:run-commands",
          "options": {
            "command": "yarn run tsc -b ./some-path-from-monorepo-root/tsconfig.json --incremental"
          }
        }
```
for each module that got speed boosts from incremental compilation, otherwise omitting `--incremental`.  I think we have a lot to learn about how to really leverage nx.

**Comment by KeKs0r** [comment]
@david-morris could you please  also provide the `tsconfig` that control how that tsc is run?
I had trouble setting it up in a way that worked. So curious which approach you went. Are you using project references?

**Comment by david-morris** [comment]
@KeKs0r here's a typical module tsconfig:
```
{
  "extends": "../../../tsconfig.base.json",
  "compilerOptions": {
    "jsx": "react-jsx",
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true
  },
  "files": [],
  "include": [],
  "references": [
    {
      "path": "./tsconfig.lib.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ]
}
```

And here is our tsconfig.base.json:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": ["es2017", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@ourcompany/design-system": ["libs/design-system/src/index.ts"],
        (more redacted lines)
    }
  },
  "include": ["@types"],
  "exclude": ["node_modules", "tmp"]
}
```

**Comment by david-morris** [comment]
Good bot. The suggested feature has been added, as documented [here](https://nx.dev/cli/run-many#nx-bail).  If there's something wrong with the nx-bail of run-many, that should be filed as a separate ticket.
