### ISSUE TITLE
Styles.scss entry point not injected into index.html if larger than 50KB for NX 12.6.3 using Webpack 5

### ISSUE THREAD

**Issue by fetters5** [nrwl/nx#6558]
## Current Behavior
Using SCSS, If the styles.scss stylesheet is 50kb+ it will get renamed from styles.[hash].css to 467.[hash].css and will not be injected into index.html.  The highlighted line below is the compiles version of styles.scss 

![image](https://user-images.githubusercontent.com/3276557/127700536-9347d85d-a4a8-40bf-8940-18b1accb35b8.png)

## Expected Behavior
styles will be injected into index.html

## Steps to Reproduce
Run a new project and then add enough styles to styles.scss to the point where the file size on disk is over 50kb.  At this point the file name changes and is no longer injected into index.html and no styles show

### Failure Logs
No errors 

### Environment

 Using Webpack 5 
  
  Node : 14.15.4
  OS   : win32 x64
  npm  : 6.14.13

  nx : Not Found
  @nrwl/angular : 12.6.3
  @nrwl/cli : 12.6.3
  @nrwl/cypress : 12.6.3
  @nrwl/devkit : 12.6.3
  @nrwl/eslint-plugin-nx : 12.6.3
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.3
  @nrwl/linter : 12.6.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.6.3
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.3
  @nrwl/web : 12.6.3
  @nrwl/workspace : 12.6.3
  @nrwl/storybook : 12.6.3
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by fetters5** [comment]
Just to add  that when running `npm start -- --prod`  the 467.[hash].css file is injected  but when running `npm run build -- --prod ` the 467.[hash].css file  is not injected into index.html

**Comment by jaysoo** [comment]
This is certainly a misconfiguration of `splitChunks`. Will be patched in 12.8.1.

**Comment by fetters5** [comment]
Thank you
