### ISSUE TITLE
Cannot find module '@angular-devkit/core'

### ISSUE THREAD

**Issue by bahizi** [nrwl/nx#6564]
Upgraded my dependencies tonight and started seeing that angular 12 builds (which I typically run via `nx run web:build:prod` started failing with the below error:
```
> nx run web:build:prod 
Cannot find module '@angular-devkit/core'
Require stack:
- /Users/andrei/Projects/my-app/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
- /Users/andrei/Projects/my-app/node_modules/@nrwl/tao/src/commands/run.js
- /Users/andrei/Projects/my-app/node_modules/@nrwl/tao/index.js
- /Users/andrei/Projects/my-app/node_modules/@nrwl/cli/lib/run-cli.js
```
I looked at tao's package.json and seems it doesn't list `angular-devkit/core` as a dependency. To fix the issue for myself,  I simply ran `npm i -D @angular-devkit/core`, which got me `12.1.4` and the build worked, but it got me wondering: should we add the dependency to tao's package.json since the src code there is explicitly importing from it?

**Comment by Coly010** [comment]
hi!

I've tried to reproduce this with Nx 12.7.1 but I'm not running into the same problem.

Could you try two things for me:
 - retry with the latest version of Nx
 - provide a minimal reproduction of this issue that I can use to investigate this

thank you!!
