### ISSUE TITLE
Css extraction with linaria and storybook

### ISSUE THREAD

**Issue by macieklad** [nrwl/nx#6573]
## Current Behavior
After configuring ui library with storybook using linaria as css solution with the provided [loader](https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md#webpack), webpack is correctly extracting the css modules to the configured directory, but the generated styles are not embedded into the html. 

I suspect that it is somehow related to the way nx is set up (I do not have sufficient experience with the tool as of now, so pinpointing the problem is hard for me), because I have tried:

1. Different ordering of the linaria webpack loader (before and after css loaders)
2. Using older linaria versions (v3 and v2)
3. Attaching generated directory to the tsconfig includes
4. Trying the same setup in lerna based workspace (in older project) with pure `npx sb init --type react`, it works there with the guide from the linaria docs.
 
## Expected Behavior
Generated css (from .linaria-cache) folder should be embedded as inline style tags, and be fully hot-reloadable.

## Steps to Reproduce
1. Clone the repo and checkout to the linaria-issue branch
https://github.com/macieklad/universe/tree/linaria-issue
2. Run the `nx run ui:storybook` command
3. The first and only storybook story will have no css applied, although the classes and files are generated.

### Failure Logs
Everything builds correctly, so there were none. There were also no errors in the web console.

### Environment
```
  Node : 16.0.0
  OS   : linux x64
  npm  : 7.10.0
  
  nx : 12.6.3
  @nrwl/angular : Not Found
  @nrwl/cli : 12.6.3
  @nrwl/cypress : 12.6.3
  @nrwl/devkit : 12.6.3
  @nrwl/eslint-plugin-nx : 12.6.3
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.3
  @nrwl/linter : 12.6.3
  @nrwl/nest : Not Found
  @nrwl/next : 12.6.3
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.6.3
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.3
  @nrwl/web : 12.6.3
  @nrwl/workspace : 12.6.3
  @nrwl/storybook : 12.6.3
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by mandarini** [comment]
Hi there @macieklad ! Thanks for filing an issue! Do you think that this is a bug, or rather a feature request, that we support `linaria`, in a way?

**Comment by macieklad** [comment]
Hello!

As of now, I would classify it as a bug, going with the thought that if the "pure" storybook configuration handles the tool well, it should technically work here out of the box too. Also, for me linaria is an improvement in dx over the css modules and gives roughly the same benefits, while keeping the runtime costs untouched, so it would be great for nx to support it natively, however each type of project (web, cra, next etc.) has to set it up in a slightly different way (but quite simple and mostly solved by the community), so it may not be the best candidate for a feature. 

After some more tinkering and inspecting the final webpack loaders configuration in the two workspaces (nx generated and the manually setup one) I couldn't find any differences in the style processing (style-loader + css-loader) and that's what bugs me.

**Comment by mandarini** [comment]
Hi @macieklad ! Is this still an issue? If yes, can you please send me the reproduction repo again (above link does not work) to test this out more thoroughly?

**Comment by mandarini** [comment]
Hi @macieklad! I will be closing this issue now, since it's been inactive for 2 weeks. Let me know if the issue persists, and if you can provide a reproduction repository, and I will re-open! Thank you!

**Comment by macieklad** [comment]
Hi, sorry for no response, I will clarify if anyone wanders here, the issue was caused by incompatibilities between storybook and webpack 5 at the time. There was really nothing that could be done o the nx side. Thank you for your time and taking a look at this issue. It can be left closed :)
