### ISSUE TITLE
App generator plugin not installing all its required dependencies in a workspace

### ISSUE THREAD

**Issue by writam-roy** [nrwl/nx#6578]
I have a customized app generator plugin which is pretty similar to a react app plugin that is provided by @nrwl ,as its in a private repo im unable to attach link to that.
The problem I'm facing is ,in my plugin code, inside package.json of the plugin,I have a section like this where I have mentioned,what are the dependencies my plugin needs (attaching snapshot below),but when I use the plugin in a newly created Nx workspace,to create a react app I see only a few among the ones that I mentioned in the plugin package.json are installed not all,why this behaviour? 

****Original package.json dependency set within my plugin code -**** 
"dependencies": {
    "@next/bundle-analyzer": "^10.0.3",
    "@nrwl/node": "^12.5.7",
    "@zeit/next-bundle-analyzer": "^0.1.2",
    "@zeit/next-css": "^1.0.1",
    "@zeit/next-sass": "^1.0.1",
    "@zeit/next-typescript": "^1.1.1",
    "core-js": "^3.14.0",
    "document-register-element": "1.13.1",
    "enzyme-adapter-react-16": "^1.15.6",
    "global": "^4.4.0",
    "hazelcast-client": "3.12.2",
    "isomorphic-fetch": "^3.0.0",
    "jest-sonar-reporter": "^2.0.0",
    "lodash-webpack-plugin": "^0.11.6",
    "next": "^10.2.3",
    "next-compose-plugins": "2.2.1",
    "next-optimized-images": "^2.6.2",
    "next-transpile-modules": "^5.0.0",
    "ora": "^5.4.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "regenerator-runtime": "0.13.7",
    "resolve": "^1.20.0",
    "sass": "^1.35.1",
    "sass-loader": "10.1.1",
    "smoothscroll-polyfill": "^0.4.4",
    "styled-jsx": "3.4.4",
    "swagger-jsdoc": "^6.1.0",
    "swagger-ui-express": "^4.1.6",
    "tslib": "^2.2.0",
    "@babel/core": "7.12.13",
    "@babel/preset-env": "7.12.13",
    "@babel/preset-react": "^7.14.5",
    "@babel/preset-typescript": "^7.14.5",
    "@babel/runtime": "^7.14.6",
    "@nrwl/cli": "12.6.2",
    "@nrwl/cypress": "12.6.2",
    "@nrwl/eslint-plugin-nx": "12.6.2",
    "@nrwl/jest": "12.6.2",
    "@nrwl/linter": "12.6.2",
    "@nrwl/next": "12.6.2",
    "@nrwl/react": "12.6.2",
    "@nrwl/tao": "12.6.2",
    "@nrwl/web": "12.6.2",
    "@nrwl/workspace": "12.6.2",
    "@testing-library/react": "11.2.6",
    "@types/jest": "26.0.8",
    "@types/node": "14.14.33",
    "@types/react": "17.0.3",
    "@types/react-dom": "17.0.3",
    "@types/styled-jsx": "2.2.8",
    "@typescript-eslint/eslint-plugin": "4.19.0",
    "@typescript-eslint/parser": "4.19.0",
    "babel-jest": "26.2.2",
    "chalk": "^4.1.1",
    "cypress": "^7.3.0",
    "dotenv": "8.2.0",
    "eslint": "7.22.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsx-a11y": "6.4.1",
    "eslint-plugin-react": "7.23.1",
    "eslint-plugin-react-hooks": "4.2.0",
    "jest": "27.0.3",
    "prettier": "2.2.1",
    "sonarqube-scanner": "^2.8.0",
    "ts-jest": "27.0.3",
    "ts-node": "~9.1.1",
    "typescript": "~4.2.4"
  }

**the one that gets installed in a different nx workspace,where I use the plugin -**

 "dependencies": {
    "core-js": "^3.6.5",
    "document-register-element": "1.13.1",
    "next": "10.1.3",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "regenerator-runtime": "0.13.7",
    "styled-jsx": "3.4.4",
    "tslib": "^2.0.0"
  },
  "devDependencies": {
    "@babel/core": "7.12.13",
    "@babel/preset-env": "7.12.13",
    "@babel/preset-react": "7.12.13",
    "@babel/preset-typescript": "7.12.13",
    "@nrwl/cli": "12.6.3",
    "@nrwl/cypress": "12.6.3",
    "@nrwl/eslint-plugin-nx": "12.6.3",
    "@nrwl/jest": "12.6.3",
    "@nrwl/linter": "12.6.3",
    "@nrwl/next": "*12.6.3",
    "@nrwl/react": "12.6.3",
    "@nrwl/tao": "12.6.3",
    "@nrwl/web": "12.6.3",
    "@nrwl/workspace": "12.6.3",
    "@testing-library/react": "11.2.6",
    "@types/jest": "26.0.8",
    "@types/node": "14.14.33",
    "@types/react": "17.0.3",
    "@types/react-dom": "17.0.3",
    "@types/styled-jsx": "2.2.8",
    "@typescript-eslint/eslint-plugin": "4.19.0",
    "@typescript-eslint/parser": "4.19.0",
    "babel-jest": "26.2.2",
    "cypress": "^7.3.0",
    "dotenv": "8.2.0",
    "eslint": "7.22.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsx-a11y": "6.4.1",
    "eslint-plugin-react": "7.23.1",
    "eslint-plugin-react-hooks": "4.2.0",
    "jest": "27.0.3",
    "prettier": "^2.3.1",
    "ts-jest": "27.0.3",
    "ts-node": "~9.1.1",
    "typescript": "~4.2.4"
  }

As you can see there is somehow some filter in some code within the plugin which works in the background to remove certain dependencies, which I am not able to figure out, any help regarding this would be greatly appreciated

**Comment by AgentEnder** [comment]
What preset are you using when you generate a new workspace? Looking at above, I wonder if the packages that are installed are installed regardless of your plugin. The package.json in your plugin works the same way as any other npm package's package.json, it labels your deps, not what should be added to the workspace's package.json. (those would be peerDependencies, and normally the init generator for your plugin would register them)

Here you can see how we set this up for @nrwl/react. https://github.com/nrwl/nx/blob/master/packages/react/src/generators/init/init.ts#L53
