### ISSUE TITLE
Not able to create workspace (Angular) - Cypress App could not be unzipped & permission error

### ISSUE THREAD

**Issue by sharathsg27** [nrwl/nx#6584]
## Current Behavior
I'm trying to create a new workspace for angular. But it's failing due to Cypress unzipping & permission issue. I do not know the reason for it

## Steps to Reproduce
Run the below commands:
`npx create-nx-workspace@latest`
`npm install --save-dev @nrwl/angular` (fails here)

### Failure Logs
<img width="781" alt="Screenshot 2021-08-03 at 9 18 15 AM" src="https://user-images.githubusercontent.com/29069848/127955121-7a602dc0-f7e3-4e94-9d9f-940539f403e5.png">

I'm following the steps from the docs here: https://nx.dev/latest/angular/migration/overview

### Environment
Node version: 14.17.3
NPM version: 7.19.1
Angular CLI: 12.1.1
@angular-devkit/architect: 0.1201.1 (cli-only)
@angular-devkit/core: 12.1.1 (cli-only)
@angular-devkit/schematics: 12.1.1 (cli-only)
@schematics/angular: 12.1.1 (cli-only)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This looks like a system permission issue where Cypress can't unzip its artifact into the cache. I'm afraid there's nothing we can do on our side. I'd recommend you to check the permissions of the folder where Cypress is trying to unzip its files and if you think there's an issue there, the best place to raise it would be the Cypress repo.
