### ISSUE TITLE
[angular] Schema validation failed with the following errors: Data path "" must NOT have additional properties(maxWorkers).

### ISSUE THREAD

**Issue by hnxb** [nrwl/nx#6585]
Add `"maxWorkers": 1` and `"memoryLimit": 1024` option under `my-angular.architect.build.options` in angular.json file

## Current Behavior

Failed to run `nx serve web` (angular).

## Steps to Reproduce

1. Add `maxWorkers` and  `memoryLimit` as below
```json
"web": {
  "projectType": "application",
    "root": "apps/web",
    "sourceRoot": "apps/web/src",
    "architect": {
      "build": {
        "options": {
          "maxWorkers": 1,
          "memoryLimit": 1024,
        }
      }
   }
}
```
2. Run `nx serve web`

### Failure Logs

```
> nx run web:serve:development 
Schema validation failed with the following errors:
  Data path "" must NOT have additional properties(maxWorkers).

———————————————————————————————————————————————

>  NX   ERROR  Running target "web:serve" failed

```

### Environment

Node : 14.16.0
  OS   : linux x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 12.5.8
  @nrwl/cli : 12.5.8
  @nrwl/cypress : 12.5.8
  @nrwl/devkit : 12.5.8
  @nrwl/eslint-plugin-nx : 12.5.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.8
  @nrwl/linter : 12.5.8
  @nrwl/nest : 12.5.8
  @nrwl/next : Not Found
  @nrwl/node : 12.5.8
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.8
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.8
  @nrwl/storybook : 12.5.8
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Which executor are you using in that target?

If it's using one of the `@nrwl/angular:webpack-browser` or `@angular-devkit@build-angular:browser` executors, as the message says, the `maxWorker` option is not allowed (`memoryLimit` is not allowed either).

**Comment by hnxb** [comment]
Thanks for your reply,

It was `@angular-devkit/build-angular:browser`, so is this a known issue? Do I know need to switch to another executor inoder to have `maxWorkers` and `memoryLimit` option?

**Comment by leosvelperez** [comment]
It's not an issue, it's an option the executor doesn't accept. The executor here is working as expected and rejecting an unknown/unsupported option.

If you think you have a use case for those options to be supported, please note that's an executor provided by the Angular CLI, so you could request the support for it in the Angular CLI repo.

I'm closing this issue since the behavior is what's expected.
