### ISSUE TITLE
Build failure when NX_CACHE_PROJECT_GRAPH = false

### ISSUE THREAD

**Issue by knguyen0125** [nrwl/nx#6586]
## Current Behavior

With NX_CACHE_PROJECT_GRAPH = false, readCachedProjectGraph no longer works and fails build

## Expected Behavior

With NX_CACHE_PROJECT_GRAPH = false, either recompute project graph to calculate generatePackageJson, or do not throw an error.

Previously with NX_CACHE_PROJECT_GRAPH=false, I was able to build projects

## Steps to Reproduce

Remove node_modules/.cache folder.
Run `NX_CACHE_PROJECT_GRAPH=false nx affected:build`

### Failure Logs

```
[AWS CodeBuild Plugin]       [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.
[AWS CodeBuild Plugin]       
[AWS CodeBuild Plugin]       If you are leveraging `readCachedProjectGraph()` directly then you will need to refactor your usage to first ensure that
[AWS CodeBuild Plugin]       the ProjectGraph is created by calling `await createProjectGraphAsync()` somewhere before attempting to read the data.
[AWS CodeBuild Plugin] 
[AWS CodeBuild Plugin]       If you encounter this error as part of running standard `nx` commands then please open an issue on https://github.com/nrwl/nx
```

### Environment

```
yarn nx report
yarn run v1.22.10
$ nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.17.0
  OS   : linux x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.6.3
  @nrwl/cypress : 12.6.3
  @nrwl/devkit : 12.6.3
  @nrwl/eslint-plugin-nx : 12.6.3
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.3
  @nrwl/linter : 12.6.3
  @nrwl/nest : 12.6.3
  @nrwl/next : Not Found
  @nrwl/node : 12.6.3
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.6.3
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.3
  @nrwl/web : 12.6.3
  @nrwl/workspace : 12.6.3
  @nrwl/storybook : 12.6.3
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

I couldn't reproduce the issue with the provided information. Could you please share a minimal repo where this issue can be reproduced?

**Comment by SerdarN92** [comment]
Locally my build runs without errors.

As soon i do the same on google cloud build, i get the same error:

![image](https://user-images.githubusercontent.com/7069847/129041926-d226d592-65e7-4223-b11f-121798d85760.png)

**Comment by pmoehler** [comment]
@SerdarN92 what I can see on our side is, that everything was fine to 12.6.2, afterwards same error - will dig into it this evening

**Comment by SerdarN92** [comment]
@pmoehler thanks for the hint. I will try to downgrade to 12.6.2. I already tried 12.6.5, but i got the same error.

**Comment by SerdarN92** [comment]
@pmoehler it worked now with 12.6.2. THANK YOU !!!

**Comment by pmoehler** [comment]
I can't find the time today but will give an update when I get a chance.

**Comment by pmoehler** [comment]
@SerdarN92 just found out, that we had the issue only inside docker where no npm post-install steps are running by default. So `decorate-angular-cli.js` was not invoked by which `ng` is not symlinked to `nx`, which was the root cause of our issue. It worked before so to speak accidentally.

**Comment by SerdarN92** [comment]
@pmoehler yes the issue came only up in the pipeline inside docker. So the solution is to put the decorate-angular-cli.js into the dockerfile?

**Comment by pmoehler** [comment]
@SerdarN92 We transitioned to `nx` with an existing angular code-base (see https://nx.dev/latest/angular/migration/migration-angular) and wanted to preserve our existing `ng` structure. Since there is no need for this now I just use `nx` directly inside `package.json` scripts  (`nx build`, `nx test`, ..) and this works fine. If you want to preserve `ng` structure make sure that `decorate-angular-cli.js` is executed within the `postinstall` script inside your container that symlinks `node_modules/.bin/ng` to `node_modules/.bin/nx`. Additionally, we only run `ngcc` within postinstall since we need it (https://nx.dev/latest/angular/ci/setup-incremental-builds-angular) 🙂 Note: if your container `npm install` step is running as root at this point, the `postinstall` script is not executed automatically.

**Comment by SerdarN92** [comment]
After updating to latest version the error comes up again .. @pmoehler did you find any solution? i also did what you wrote like changing all the ng things to nx .. still the error comes up

**Comment by pmoehler** [comment]
@SerdarN92 our related project run`s with the following versions:

```bash
$ nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.18.2
  OS   : linux x64
  npm  : 6.14.15
  
  nx : Not Found
  @nrwl/angular : 12.10.1
  @nrwl/cli : 12.10.1
  @nrwl/cypress : 12.10.1
  @nrwl/devkit : 12.10.1
  @nrwl/eslint-plugin-nx : 12.10.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.10.1
  @nrwl/linter : 12.10.1
  @nrwl/nest : 12.10.1
  @nrwl/next : Not Found
  @nrwl/node : 12.10.1
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.1
  @nrwl/web : Not Found
  @nrwl/workspace : 12.10.1
  @nrwl/storybook : 12.10.1
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

Everything is fine with this so far, haven`t upgraded to 13.4.3 until now but I will come back if there are issues.

Happy new year! :)

**Comment by SerdarN92** [comment]
@pmoehler Happy new year to you too! I opened a new issue and will try the possible solution one guy wrote under it. You can find it here: https://github.com/nrwl/nx/issues/8288

**Comment by SerdarN92** [comment]
The solution at https://github.com/nrwl/nx/issues/8288 worked! @pmoehler
