### ISSUE TITLE
Build is cached even when app code is affected by the changes

### ISSUE THREAD

**Issue by DzmVasileusky** [nrwl/nx#6587]
## Current Behavior

We have the following nx workspace structure:
apps
-- app1
-- app2
libs

I changed the file in libs which is imported and used in both apps.
But my changes wasn't deployed:
`nx run app1:build:dev [retrieved from cache]`.

## Expected Behavior

If the file from libs imported by an app is changed - build shouldn't be cached.

## Steps to Reproduce

Our app is pretty big, but I'll try to come with some repo if there are no other ways to research this.

### Environment

  Node : 12.16.1
  OS   : darwin x64
  npm  : 7.6.3
  
  nx : Not Found
  @nrwl/angular : 11.5.1
  @nrwl/cli : 11.5.1
  @nrwl/cypress : 11.5.1
  @nrwl/devkit : 11.5.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.5.1
  @nrwl/linter : 11.5.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.5.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.5.1
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.0.3

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Unfortunately, I can't reproduce this issue. Could you provide a minimal repo where this issue can be reproduced?

**Comment by hmica** [comment]
Hi, I had the same issue yesterday just changing a string with same length in a file into the libs folder.
The lib is not referenced has a project, only configured as a paths in the tsconfig.base.json maybe this is the cause.
Did'nt have time to make a minirepo to reproduce it know sorry.
