### ISSUE TITLE
buildLibsFromSource not working

### ISSUE THREAD

**Issue by dangviettuan** [nrwl/nx#6589]
## Current Behavior
buildLibsFromSource is not working after the upgrade from 12.0.8 to 12.6.3.
## Expected Behavior
buildLibsFromSource work correctly

## Steps to Reproduce
1. Execute a production build with `buildLibsFromSource` checked in Nx Console.
![image](https://user-images.githubusercontent.com/11323132/128006817-497791a3-06d4-4305-87ea-d43ab0dd7b5b.png)

2. Build process is not working correctly. Libs were built separately.
![image](https://user-images.githubusercontent.com/11323132/128006964-5d411aab-c17b-45d4-9e50-7c1c020ccd1c.png)

### Environment
  Node : 14.16.0
  OS   : linux x64
  yarn : 1.22.5
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.6.3
  @nrwl/cypress : 12.6.3
  @nrwl/devkit : 12.6.3
  @nrwl/eslint-plugin-nx : 12.6.3
  @nrwl/express : 12.6.3
  @nrwl/jest : 12.6.3
  @nrwl/linter : 12.6.3
  @nrwl/nest : Not Found
  @nrwl/next : 12.6.3
  @nrwl/node : 12.6.3
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.6.3
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.3
  @nrwl/web : 12.6.3
  @nrwl/workspace : 12.6.3
  @nrwl/storybook : 12.6.3
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by nartc** [comment]
I can't seem to reproduce this issue. This seems like a workspace with NextJS. Can you please provide a sample reproduce?

**Comment by dangviettuan** [comment]
> I can't seem to reproduce this issue. This seems like a workspace with NextJS. Can you please provide a sample reproduce?

**Comment by dangviettuan** [comment]
@nartc You can reproduce as below.
- Create a new workspace with react preset.
- Create a new react library with buildable and publishable.
- Create a new app and Import the library to your app.
- Build the new app and the issue happen.

Here is the build result when I checked buildLibsFromSource
![image](https://user-images.githubusercontent.com/11323132/128222294-d82e99fd-c8b6-4249-9de4-98c36259734f.png)

**Comment by dangviettuan** [comment]
@leosvelperez It's saved my day. Just remove `targetDependencies`. I đi not noticed this new update.

The default value is
`"targetDependencies": {
    "build": [
      {
        "target": "build",
        "projects": "dependencies"
      }
    ]
  }`

And in a newly created workspace, it's the same.

**Comment by nartc** [comment]
@dangviettuan just fyi that if you've run Nx Migrate recently, this is one of the migration step to add `targetDependencies`. Glad that you're able to resolve it. Thank you @leosvelperez
