### ISSUE TITLE
`TreeWriteOptions` doesn't give permissions while creating file in Generator

### ISSUE THREAD

**Issue by Jad31** [nrwl/nx#6590]
## Current Behavior

Tree doesn't write file with permission

```typescript
const writeOptions: TreeWriteOptions = { mode: '755' };


tree.write(`scripts/serve/index.bash`, 'echo "bash file"', writeOptions);
```

## Expected Behavior
I want to create a file with the corrects permissions gived by `TreeWriteOptions`.

## Steps to Reproduce
Clone this repository: https://github.com/Jad31/nx-write-options-issue

`cd write-issue`

`yarn`

`yarn run nx workspace-generator my-generator`

It should create an `index.bash` file in `scripts/serve` folder.

### Failure Logs
```bash
> ./scripts/serve/index.bash

bash: permission denied: ./scripts/serve/index.bash
```

### Environment
```bash
> yarn run nx report

yarn run v1.22.11
$ nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.17.4
  OS   : linux x64
  yarn : 1.22.11
  
  nx : Not Found
  @nrwl/angular : 12.6.3
  @nrwl/cli : 12.6.3
  @nrwl/cypress : 12.6.3
  @nrwl/devkit : 12.6.3
  @nrwl/eslint-plugin-nx : 12.6.3
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.3
  @nrwl/linter : 12.6.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.3
  @nrwl/web : Not Found
  @nrwl/workspace : 12.6.3
  @nrwl/storybook : 12.6.3
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

```

## Related issues

- #5680

**Comment by Jad31** [comment]
Is it also possible to have a method that allows us to change permissions of a file without changing or update the content ?
In my case, i want to use the `generateFiles` method that creates file from templates and then change permissions.
I can open a new issue dedicated to this feature if you want.

**Comment by leosvelperez** [comment]
@Jad31 yes please, this issue will be closed with the linked PR which solves the wrong behavior reported here. Adding a method to change file permissions would be a new feature.
