### ISSUE TITLE
webpack.WebpackError on nx build --prod

### ISSUE THREAD

**Issue by TassiloSinghammerVolue** [nrwl/nx#6600]
## Current Behavior
After migrating to 12.6.4 I'm getting the following error when trying to run a production build:
**nx run [appname]:build:production 
webpack.WebpackError is not a constructor**

## Expected Behavior
Build and produce output to the dist folder.

## Steps to Reproduce
It is hard to say what exactly causes the issue. However I can state that it seems to be related to @nrwl/web
Reverting this package to 12.5.9 makes the production build work again

### Environment
Windows 10, Powershell, Node v14.17.1

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Please note this is a duplicate of #6485. I'm closing this in favor of that one. You can follow that issue for updates.
