### ISSUE TITLE
nx test fails after migrating to 12.6.4

### ISSUE THREAD

**Issue by TassiloSinghammerVolue** [nrwl/nx#6602]
## Current Behavior
**NX   ERROR  Running target "[application]:test" failed**

## Expected Behavior
Run all tests of the application

## Steps to Reproduce
`nx test`

The application currently has two projects: a React web project, and a library
It seems that it is looking for the package dependency in below the web application's folder.
Provided path to resolve: C:\[path-to-root]\apps\[application]\libs\[dependent-package]
Instead libs is located at workspace root level, the same level as the apps folder.

### Failure Logs
Can't find a root directory while resolving a config file path.
Provided path to resolve: C:\[path-to-root]\apps\[application]\libs\[dependent-package]
cwd: [path-to-root]

———————————————————————————————————————————————

>  NX   ERROR  Running target "[application]:test" failed

### Environment
Windows 10, Powershell, Node v14.17.1

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Unfortunately, I couldn't reproduce this with the provided information. Could you please provide a minimal repo where the issue can be reproduced?

**Comment by Bugget** [comment]
I am experiencing exactly the same behavior after running nx migrate from 12.3.6 to 12.6.6.  It appears that something is trying to find the libs directory under the apps directory.  Is something perhaps not using the root directory but rather concatenating the apps directory when looking for tsconfig.spec.json?

**Comment by TassiloSinghammerVolue** [comment]
Still experiencing this with 12.7.1
I will try to provide a small repo, but the question is how small it will be, as it seems not to be reproducible with just setting up a new repo with one React app and one lib.
What I can say is that it is still working with 12.5.9.
It may be just a jest configuration that is not compatible with the latest Nx verions?
This is the content of my jest.config.js:
`module.exports = {
  testMatch: ['**/+(*.)+(spec|test).+(ts|js)?(x)'],
  transform: {
    '^.+\\.(ts|js|html)$': 'ts-jest',
  },
  resolver: '@nrwl/jest/plugins/resolver',
  moduleFileExtensions: ['ts', 'js', 'html'],
  coverageReporters: ['html'],
  testEnvironment: 'jsdom',
};
`

**Comment by TassiloSinghammerVolue** [comment]
In Addition I'm getting these warnings on nx build after the migration. Maybe this is related?

`The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.`

**Comment by TassiloSinghammerVolue** [comment]
Btw. unfortunately I'm not able to reproduce it with a new repo. So I'm not really sure what to do. It must be a setting somewhere in the existing repository but I would end up moving all code and configs of the old repo to the new one. Maybe that's what I have to to.

**Comment by TassiloSinghammerVolue** [comment]
I did a bit of debugging.
The `jestConfigurationSet getJestProjects()` returns looks like:
`jestConfigurationSet Set(2) {
  '<rootDir>\\libs\\authentication',
  '<rootDir>\\apps\\navigator'
}`

AS the error says `Can't find a root directory while resolving a config file path.` it looks to me as it caanot resolve <rootDir>

**Comment by TassiloSinghammerVolue** [comment]
I think we had this issue before. It occured if the Nx workspace root did not match the Git repo root.

**Comment by TassiloSinghammerVolue** [comment]
It starts running the tests if I change the jest.config.js to hardcoded projects like
`// projects: getJestProjects(),
  projects:['libs/authentication', 'apps/navigator'],`
  
 However it brings up  a lot of Cannot find module errors while running the tests.
 I think I will give up on this and try to migrate our projects to a clean workspace setup when I find some time.

**Comment by karol-majewski** [comment]
I have a similar problem. One of my libraries, Logger, is used globally in my apps.

Ideally I would do:

`jest.config.js`

```js
const { Logger } = require('@namespace/logger');
```

But since path aliases don't work in Jest out of the box, I did:

```js
const { Logger } = require('../../libs/logger/src/index');
```

Visual Studio Code resolves that path correctly — I can jump right to my logger if I click the path. However, Jest throws with:

```
Error: Cannot find module '../../libs/logger/src/index'
```

Using Nx 12.7.2.

**Comment by danielwanja** [comment]
I can confirm this is still an issue I just encountered  migrating a customer workspace to Nx 12.9.0

In the root jest.config.js
``` 
const { getJestProjects } = require('@nrwl/jest');

module.exports = {
  testMatch: ['**/+(*.)+(spec|test).+(ts|js)?(x)'],
  transform: {
    '^.+\\.(ts|js|html)$': 'ts-jest',
  },
  resolver: '@nrwl/jest/plugins/resolver',
  moduleFileExtensions: ['ts', 'js', 'html'],
  coverageReporters: ['html'],
  // projects: getJestProjects(), <-- 🔥 returns wrong list of projects
};
```

I.e. when running `nx test ui-app1 --watch false --code-coverage` the call to getJestProjects returns 

```
myworkspace/libs/ui/app1/apps/app1 
myworkspace/libs/ui/app1/apps/app2   <-- 🔥 wrong should mabye be myworkspace/apps/app2
myworkspace/libs/ui/app1/libs/components/md-forms <-- 🔥 wrong should maybe be myworkspace/libs/components/md-forms
myworkspace/libs/ui/app1/libs/components/forms
myworkspace/libs/ui/app1/libs/pn-jsonapi
myworkspace/libs/ui/app1/libs/pn-library
myworkspace/libs/ui/app1/libs/third-party/angular-google-maps
```

Just disabling `getJestProjects` is not the solution but highlights the issue. Still debugging this, will report further info once I dive deeper.

Thanks for Nx and all your hard work.
