### ISSUE TITLE
Regression: --verbose being passed to executors can break commands

### ISSUE THREAD

**Issue by Ezard** [nrwl/nx#6606]
## Current Behavior
Due to this PR (https://github.com/nrwl/nx/pull/6593), Nx now passes the verbose flag to executors.
In the case of the `@nrwl/workspace:run-commands` executor, this causes `--verbose=false` to be appended to commands, even when not manually specified.
However, if the command that's being run does not support that flag, and does not silently ignore unknown flags, then that command will fail. In my case I am running `npx prisma generate` via this executor, which means the command ended up being `npx prisma generate --verbose=false`; the Prisma CLI does not support this flag or unknown flags, and so fails.

## Expected Behavior
`--verbose` should only be passed to executors if manually specified (as `--verbose`, `--verbose=false`, etc)

## Steps to Reproduce
Add the following target to any project in an Nx 12.6.4 workspace, and then try to execute it (via `nx run <target>:generate`):
```
"generate": {
  "builder": "@nrwl/workspace:run-commands",
  "options": {
    "commands": [
      "npx prisma generate"
    ]
  }
}
```

### Environment
```
  Node : 16.4.2
  OS   : win32 x64
  npm  : 7.18.1

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.6.4
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.6.3
  @nrwl/eslint-plugin-nx : 12.6.4
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.4
  @nrwl/linter : 12.6.3
  @nrwl/nest : 12.6.4
  @nrwl/next : Not Found
  @nrwl/node : 12.6.4
  @nrwl/nx-cloud : 12.3.5
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.4
  @nrwl/web : Not Found
  @nrwl/workspace : 12.6.4
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by nartc** [comment]
@Ezard Thanks for reporting. The `verbose` flag is passed in because `run-commands` executor has `additionalProperties: true` (https://github.com/nrwl/nx/blob/master/packages/workspace/src/executors/run-commands/schema.json#L83)
Not sure if it's more logical to change that in the executor schema or change the logic to append `verbose`. I'll be discussing with the team internally.

**Comment by hwasurr** [comment]
```json
"generate": {
  "builder": "@nrwl/workspace:run-commands",
  "options": {
    "commands": [
      {
        "command": "npx prisma generate",
        "forwardAllArgs": false
      }
    ]
  }
}
```

This works for me

**Comment by diegovilar** [comment]
This started happening here after upgrading from 12.6.3 to 12.6.4 too:

In 12.6.3:
![image](https://user-images.githubusercontent.com/759416/128287704-613311c1-a82a-4d60-81b9-d0c884fced64.png)

In 12.6.4:
![image](https://user-images.githubusercontent.com/759416/128287580-b988047b-1ba8-48d0-9d04-8ae036f273b4.png)

**Comment by yharaskrik** [comment]
This also happens when using something like: https://www.npmjs.com/package/start-server-and-test

Verbose is passed and it changes the # of CLI args (which the package checks)

**Comment by asherccohen** [comment]
I confirm the issue is still happening on 12.6.5.
I fixed it with 

```
"generate": {
  "builder": "@nrwl/workspace:run-commands",
  "options": {
    "commands": [
      {
        "command": "npx prisma generate",
        "forwardAllArgs": false
      }
    ]
  }
}
```

**Comment by nartc** [comment]
12.6.5 does not contain this fix yet. It should be in the next patch.

**Comment by nartc** [comment]
@maxisam are you sure you're on 12.6.6?

**Comment by maxisam** [comment]
@nartc Yes, I was on 12.6.5 and I started having this issue. And I upgraded it and still have the same issue

**Comment by nartc** [comment]
Can you provide a repro? I can't seem to reproduce this on 12.6.6

**Comment by maxisam** [comment]
did you test it with @nrwl/angular:package? It seems like only happen to that one

**Comment by maxisam** [comment]
Do you see --verbose=false in the end of the nx run xxx:build:config

**Comment by nartc** [comment]
No. 

The target
![image](https://user-images.githubusercontent.com/25516557/129070641-da03b8a9-742f-46ac-945c-e3d49214fd7b.png)

Invoking commands
![image](https://user-images.githubusercontent.com/25516557/129070649-131205c0-6293-4c37-a73d-dc0334347f36.png)

**Comment by maxisam** [comment]
ummm, mine is a bit different, I didn't call it directly. the package build is triggered by the main one

**Comment by nartc** [comment]
![image](https://user-images.githubusercontent.com/25516557/129071458-149c12a0-ed7c-484a-b767-98b5294d1232.png)
I have a target that calls multiple build target as well and this one runs fine with 12.6.6.
