### ISSUE TITLE
Generated component incompatible with ESLint rules

### ISSUE THREAD

**Issue by ph55** [nrwl/nx#6621]
When component generated it has ESLint errors:

1. `ESLint: Unexpected empty constructor.(@typescript-eslint/no-empty-function)`

![image](https://user-images.githubusercontent.com/1386622/128391302-ac88443d-8edd-4ef5-b1c6-ef34ad6ecf42.png)

2. `ESLint: Lifecycle methods should not be empty(@angular-eslint/no-empty-lifecycle-method)`

![image](https://user-images.githubusercontent.com/1386622/128392142-7eb2d172-e517-42f1-8685-2832dbb5aba0.png)

Component should be either generated without `constructor` and `ngOnInit` or ESLint rules should be adjusted to generated component.

**Comment by nartc** [comment]
@ph55 thank you for reporting. However, this issue might not be actionable. There are two reasons:

1. Component Generator is from `@schematics/angular` which Nx does not control.
2. The ESLint rule cannot be adjusted just for component generation. The rules are there to guide the developers. What if we disable the rule/adjust the rule to pass component generation, but later on as the component grows, the developers are not aware of they're violating the rules that were meant to be there?

That said, this is really on the developers' responsibility to remove the `constructor` and `ngOnInit` if they don't need them.
