### ISSUE TITLE
[Angular] Migration to Nx v.12.6 is not finding the libs dependencies anymore

### ISSUE THREAD

**Issue by gerardcastell** [nrwl/nx#6648]
I have taken a glance at your update on [https://github.com/nrwl/nx/issues/6443](https://github.com/nrwl/nx/issues/6443), but, unfortunately it is NOT working neither if I run the migration to the latest version (Nx. 12.6). The error keeps the same.
Steps to reproduce:
Environemnt:

Node : 12.22.1
OS : darwin x64
npm : 6.14.12

nx : Not Found
@nrwl/angular : 12.5.8
@nrwl/cli : 12.5.8
@nrwl/cypress : 12.5.8
@nrwl/devkit : 12.5.8
@nrwl/eslint-plugin-nx : 12.5.8
@nrwl/express : Not Found
@nrwl/jest : 12.5.8
@nrwl/linter : 12.5.8
@nrwl/nest : 12.5.8
@nrwl/next : Not Found
@nrwl/node : 12.5.8
@nrwl/nx-cloud : 12.2.7
@nrwl/react : Not Found
@nrwl/schematics : Not Found
@nrwl/tao : 12.5.8
@nrwl/web : Not Found
@nrwl/workspace : 12.5.8
@nrwl/storybook : 12.5.8
@nrwl/gatsby : Not Found
typescript : 4.2.4
  
  
1. Git clone the repository [https://github.com/gerardcastell/nx-monorepo-libs-deps](https://github.com/gerardcastell/nx-monorepo-libs-deps)
2. Run "nx migrate latest"
3. Run "npm i"
4. Run "nx migrate --run-migrations"
5. Finally, run "nx build"

The error displayed on the console is the same one:
![Screenshot 2021-07-27 at 11 53 57](https://user-images.githubusercontent.com/25346175/127134863-2d480035-5530-4ba6-87c6-f1e1d224945c.png)

The resulting environment properties now are:
Node : 12.22.1
  OS   : darwin x64
  npm  : 6.14.12

  nx : Not Found
  @nrwl/angular : 12.6.2
  @nrwl/cli : 12.6.2
  @nrwl/cypress : 12.6.2
  @nrwl/devkit : 12.6.2
  @nrwl/eslint-plugin-nx : 12.6.2
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.2
  @nrwl/linter : 12.6.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.2
  @nrwl/web : Not Found
  @nrwl/workspace : 12.6.2
  @nrwl/storybook : 12.6.2
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

What I realised is that if I create a new repository with the command "npx create-nx-workspace@latest" and then perform the steps explained at [https://github.com/nrwl/nx/issues/6443](https://github.com/nrwl/nx/issues/6443) the error is fixed and the dependencies are well defined, so I think that the error here is solved for new projects but not for already existing ones that needs the migration step to get the Nx 12.6.0.

Could you please check my case and consider reopen this issue? 
Thank you in advance!

**Comment by Coly010** [comment]
Thanks for raising this! I'll add a migration that will recalculate invalid importPaths

**Comment by gerardcastell** [comment]
Any news about this issue? This is blocking my company app from update. Thanks!

**Comment by Coly010** [comment]
Hi @gerardcastell 
We have the work needed to fix this in a migration planned and should be released soon.

However, in the meantime, you can manually fix it by changing the `package.json` of the buildable libraries that are affected.

The `name` property in the `package.json` needs to match the key of the property `path` in the `tsconfig.base.json`

**Comment by gerardcastell** [comment]
Thank you so much! We really appreciate your efforts! We will stay tuned

**Comment by Coly010** [comment]
@gerardcastell 12.9.0 is released and this migration should be included. Can you try it out and let me know if it works for you

**Comment by gerardcastell** [comment]
Hi! thanks for the job! It seems like it has solved the problem but now some other libraries have different issues, for instance, when building an Ui lib that was created before a year ago with the proper nx version, it displays the following error:
![Screenshot 2021-09-08 at 19 14 54](https://user-images.githubusercontent.com/25346175/132554526-d827db56-c6fc-4716-800c-87309e2547e7.png)
The new UI libs created with Nx.12 are not raising up this problem so it seems like something is missing in the migration. Any idea? Btw, thank you so much for your efforts we really appreciate it!
