### ISSUE TITLE
@nrwl/angular and @nrwl/cypress preinstallation removes cypress package on app generation

### ISSUE THREAD

**Issue by meeroslav** [nrwl/nx#6650]
## Current Behavior
* If both @nrwl/angular and @nrwl/cypress are manually installed, after the application is generated the installed `cypress` package is removed

## Expected Behavior
* Generating application when @nrwl/cypress is already installed should not cleanup the `cypress` the from the installed packages

## Steps to Reproduce
* Create empty workspace (e.g. `yarn create nx-workspace test --preset=empty --no-interactive`)
* Install `@nrwl/angular` and `@nrwl/cypress` (e.g. `yarn add -D @nrwl/angular @nrwl/cypress`)
* Generate angular application (e.g. `yarn nx g @nrwl/angular:app testapp`)
* Run e2e tests - `yarn nx e2e testapp-e2e`
* Test run fails because there is no `cypress` in the `node_modules`

### Failure Logs
![Screenshot 2021-08-09 at 10 25 23](https://user-images.githubusercontent.com/881612/128678147-1a7c5a6b-1ef6-46e0-bec6-e4870464627f.png)

### Environment
* Happens on CI and locally
* CI runs ubuntu and node 14 (all package managers)
* Local M1 chip running node 14 (latest nx, but has been happening for a while)

**Comment by dinesh-88** [comment]
+
