### ISSUE TITLE
command to open cypress

### ISSUE THREAD

**Issue by mhamri** [nrwl/nx#6663]
## Description

in the previous nx when cypress was using js we could type `npx cypress open`, in new version cypress using typescript and running this command produce error: 

```
cd .\apps\revaedge-desktop-e2e\
npx cypress open 
```

![image](https://user-images.githubusercontent.com/8991783/128791343-3dbfaa85-7ec2-49a1-b83e-b05147622411.png)

it's because the `index.js` require `preprocessTypescript` so it needs a `tsconfig.json` 

while we can't open the cypress normally anymore, looking at nx cypress documentation there is no way we could achieve same result as `npx cypress open` that will list down all the test and we could test just one file or a portion of the tests

![image](https://user-images.githubusercontent.com/8991783/128791557-0f77bd7e-1beb-4037-a912-fb1b526407b4.png)

## Motivation

what I expect to be something similar that achieve same thing and shows the list of the test in that app, so I can test only one file or a portion of the app

moreover, clicking on the test doesn't do anything so even setting `exit:false` is useless in this situation
![image](https://user-images.githubusercontent.com/8991783/128791971-4b7f460e-134b-4d2d-b7ad-c37b96693ff5.png)

## Suggested Implementation

adding a flag that open the cypress normally something like `npm run e2e project-name-e2e --open`

## Alternate Implementations

not anything i'm aware of

**Comment by Nick-Lucas** [comment]
These are the commands we use for development:

```
    "e2e:admin": "nx e2e admin-e2e --watch",
    "e2e:admin:running": "nx e2e admin-e2e --watch --baseUrl=https://localhost:44317 --devServerTarget=''",
```

If you set `baseUrl` and unset `devServerTarget` via the CLI, or in workspaces.json, then Cypress will open and run against an existing frontend rather than attempt the frontend build

**Comment by FrozenPandaz** [comment]
Good news! This is actually going to be remedied in an upcoming version with this change: https://github.com/nrwl/nx/pull/6706

You can expect try it out on Nx `12.8.0-beta.0` or when `12.8.0` is released.

If you run `npx cypress open` from the `apps/my-app-e2e` directory, cypress will open! :tada:
