### ISSUE TITLE
@nrwl/web 12.6.5 break dependency for webpack 5

### ISSUE THREAD

**Issue by smasala** [nrwl/nx#6665]
## Current Behavior

After upgrading from 12.3.6 to 12.6.5 `@nrwl/web` causes webpack 4 to be the root version (`./node_modules/webpack`).

Leads to this error: https://github.com/webpack/webpack/issues/11647

## Expected Behavior

That webpack 5 is the root version (like before)

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

```
  Node : 14.16.0
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 12.6.5
  @nrwl/cli : 12.6.5
  @nrwl/cypress : 12.6.5
  @nrwl/devkit : 12.6.5
  @nrwl/eslint-plugin-nx : 12.6.5
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.5
  @nrwl/linter : 12.6.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.6.5
  @nrwl/nx-cloud : 12.3.6
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.5
  @nrwl/web : 12.6.5               <------- removing this fixes it
  @nrwl/workspace : 12.6.5
  @nrwl/storybook : 12.6.5
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by montogeek** [comment]
I have a similar error, the problem is that even after installing Webpack 5 using `nx g @nrwl/web:migrate-to-webpack-5`, `@nrwl/web` will still use its own Webpack 4 version, and of course Hooks architecture are incompatible.

**Comment by brianmcd** [comment]
> I have a similar error, the problem is that even after installing Webpack 5 using `nx g @nrwl/web:migrate-to-webpack-5`, `@nrwl/web` will still use its own Webpack 4 version, and of course Hooks architecture are incompatible.

This sounds like it might be due to what I'm seeing in #6662, assuming you've ended up with webpack installed in `node_modules/@nrwl/web/node_modules`.

**Comment by montogeek** [comment]
>  assuming you've ended up with webpack installed in node_modules/@nrwl/web/node_modules.

Yep, the error is coming from ProgressPlugin.js  at `/Users/fernando/Code/project/node_modules/@nrwl/web/node_modules/webpack/lib/ProgressPlugin.js:242:30`

And that Webpack version is 4.x, not 5.x.
