### ISSUE TITLE
Wrong implicit dependencies detected

### ISSUE THREAD

**Issue by seravifer** [nrwl/nx#6668]
## Current Behavior
We have a library that contains all the _Angular schematics_. When we are going to build it, Nx erroneously detects that it depends on the rest of the libraries in the existing monorepo.

## Expected Behavior
Be built without dependencies.

## Steps to Reproduce
If you have a file (`ng-add.ts`) that contains create imports like:
```
import { addModuleImportToRootModule } from '@angular/cdk/schematics';
addModuleImportToRootModule(tree, module, '@nx-playground/core/auth', project);
```

Then i have a test file (`ng-add.spec.ts`) that check that:

```
      expect(
        nodesInterface.find(
          (a) =>
            a.getText() ===
            `import { MTranslateConfig } from '@nx-playground/core/translate';`
        )
      ).toBeDefined();
```
It detects that it depends on that library `@nx-playground/core` when it really is not. If i remove this file, works perfect.

### Environment
```
 Node : 14.17.0
  OS   : darwin x64
  npm  : 6.14.13
  
  nx : Not Found
  @nrwl/angular : 12.6.5
  @nrwl/cli : 12.6.5
  @nrwl/cypress : 12.6.5
  @nrwl/devkit : 12.6.5
  @nrwl/eslint-plugin-nx : 12.6.5
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.5
  @nrwl/linter : 12.6.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.6.5
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.5
  @nrwl/web : Not Found
  @nrwl/workspace : 12.6.5
  @nrwl/storybook : 12.6.5
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by statop** [comment]
I'm fairly certain the root cause of this is described here - https://github.com/nrwl/nx/issues/6672

**Comment by seravifer** [comment]
Not quite. My package is not a dependency, so I don't have it defined in in the `tsconfig.json`. I've done more research and the problem is that it detects the full "import". I updated the issue.
