### ISSUE TITLE
When using DTE feature build fails: JavaScript heap out of memory

### ISSUE THREAD

**Issue by elvirdolic** [nrwl/nx#6673]
## Current Behavior

Build fails when using DTE NX Cloud feature

## Expected Behavior

Build should not fail. It doesn't fail if no DTE is used.

## Steps to Reproduce
Simple DTE setup. Some apps and projects build without issues, some not

<--- Last few GCs --->

[1966:0x5035c40]   393729 ms: Mark-sweep (reduce) 2020.4 (2055.2) -> 2020.2 (2055.9) MB, 1843.7 / 0.0 ms  (average mu = 0.074, current mu = 0.002) allocation failure scavenge might not succeed
[1966:0x5035c40]   396109 ms: Mark-sweep (reduce) 2021.2 (2052.9) -> 2021.0 (2054.9) MB, 2376.3 / 0.0 ms  (average mu = 0.035, current mu = 0.002) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 0xa25510 node::Abort() [/usr/local/bin/node]
 2: 0x9664d3 node::FatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0xb9a8ee v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0xb9ac67 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0xd56cd5  [/usr/local/bin/node]
 6: 0xd8766e v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [/usr/local/bin/node]
 7: 0xd936a6 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [/usr/local/bin/node]
 8: 0xd7f83f v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [/usr/local/bin/node]
 9: 0xd7fab8 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [/usr/local/bin/node]
10: 0xd72399 v8::internal::ItemParallelJob::Run() [/usr/local/bin/node]
11: 0xd95600 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [/usr/local/bin/node]
12: 0xd95e9c v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [/usr/local/bin/node]
13: 0xd96065 v8::internal::MarkCompactCollector::Evacuate() [/usr/local/bin/node]
14: 0xda8061 v8::internal::MarkCompactCollector::CollectGarbage() [/usr/local/bin/node]
15: 0xd64328 v8::internal::Heap::MarkCompact() [/usr/local/bin/node]
16: 0xd65e18 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
17: 0xd6925c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]

Build is running on Linux Hosted Build Agent from Azure Devops

> nx run fm-new:build 
Nx could not find process's output. Run the command without --parallel.

**Comment by linkstrifer** [comment]
Any updates on this? I'm having the same issue

**Comment by vaunus** [comment]
Same issue here all of a sudden on our CI. Can't track this back to anything we've changed with regards to packages or NX config.

I am not seeing a `JavaScript heap out of memory` exception, only `Nx could not find process's output. Run the command without --parallel.`

Removing `--parallel` has solved it for us for now.
