### ISSUE TITLE
Nest controller created inside src folder instead of lib.

### ISSUE THREAD

**Issue by ph55** [nrwl/nx#6695]
Nest controller created inside `src` folder instead of `lib`. 
Created controller also not imported inside  project's module.

```
❯ nx g @nrwl/nest:controller --project chat-api-message
✔ What name would you like to use? · yolo
"SchematicsNestController" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
CREATE libs/chat-api/message/src/yolo/yolo.controller.spec.ts
CREATE libs/chat-api/message/src/yolo/yolo.controller.ts
```

![image](https://user-images.githubusercontent.com/1386622/129190788-49803f6a-17fa-4dd5-98fa-63342975dfd1.png)

**Comment by Herdu** [comment]
@ph55 to overcome the problem with invalid directory you can pass additional 'directory' arg (which describes the path relative to the selected project root dir).

The following command would put your service inside 'lib' dir.
`nx g @nrwl/nest:controller --project chat-api-message --directory lib`

Using that the controller has also been automatically added to 'controllers' array in module metadata. Check it out :)
