### ISSUE TITLE
Tests in NX dont work like "vanilla" react

### ISSUE THREAD

**Issue by SirRegion** [nrwl/nx#6696]
## Current Behavior
If you copy and paste the example test code from the react tutorial site [here](https://reactjs.org/docs/testing-recipes.html#data-fetching), it fails to execute in a project setup with nx, but not one setup with `create-react-app`.

## Expected Behavior
The test behaviour of projects created with `create-react-app` and `npx create-nx-workspace@latest` should be the same.

## Steps to Reproduce

Create to new projects: one using `create-react-app` and one with `npx create-nx-workspace` (choose react when prompted).

Copy both files from [https://reactjs.org/docs/testing-recipes.html#data-fetching](https://reactjs.org/docs/testing-recipes.html#data-fetching) into each projects `src` folder.
 
Try to execute the tests with either `react-scripts test` or `nx test` . 

The nx tests fail, but the react-scripts tests pass.

I know this issue is somewhere deeper in nx or the used dependencies, but I do not know enough about nx to find the exact reason.

### Failure Logs
```
FAIL   nx-setup-test  apps/nx-setup-test/src/app/user.test.js
  ● renders user data

    Cannot spy the fetch property because it is not a function; undefined given instead

      20 |
      21 | it("renders user data", async () => {
    > 22 |   const fakeUser = {    name: "Joni Baez",    age: "32",    address: "123, Charming Avenue"  };  jest.spyOn(global, "fetch").mockImplementation(() =>    Promise.resolve({
   json: () => Promise.resolve(fakeUser)    })  );
         |                                                                                                       ^
      23 |   // Use the asynchronous version of act to apply resolved promises
      24 |   await act(async () => {
      25 |     render(<User id="123" />, container);

      at ModuleMocker.spyOn (../../node_modules/jest-mock/build/index.js:795:15)
      at Object.<anonymous> (src/app/user.test.js:22:103)

```

### Environment
 ```
Node : 16.1.0
  OS   : win32 x64
  npm  : 7.20.1

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.7.0
  @nrwl/cypress : 12.7.0
  @nrwl/devkit : 12.7.0
  @nrwl/eslint-plugin-nx : 12.7.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.7.0
  @nrwl/linter : 12.7.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.7.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.7.0
  @nrwl/web : 12.7.0
  @nrwl/workspace : 12.7.0
  @nrwl/storybook : 12.7.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5


```

**Comment by wSedlacek** [comment]
I think what is missing is this pollyfill

https://github.com/facebook/create-react-app/blob/b45ae3c9caf10174d53ced1cad01a272d164f8de/packages/react-app-polyfill/jsdom.js#L9-L14
```js
// Make sure we're in a Browser-like environment before importing polyfills
// This prevents `fetch()` from being imported in a Node test environment
if (typeof window !== 'undefined') {
  // fetch() polyfill for making API calls.
  require('whatwg-fetch');
}
```
