### ISSUE TITLE
Property '_differentiate_from_OpaqueToken_structurally' is missing in type '(state: Test, action: TestAction) => Test'.

### ISSUE THREAD

**Issue by wolfhoundjesse** [nrwl/nx#67]
I have been receiving this area when trying to wire up ngrx. I cloned the ngrx_exemplary app, and it builds just fine. I tried to reproduce this as minimally as possible, and I'm still receiving the following error:

```
ERROR in ~/Repos/AngularSandbox/apps/test/src/app/app.module.ts (17,60): Argument of type '(state: Test, action: TestAction) => Test' is not assignable to parameter of type 'ActionReducerMap<{ readonly count: number; }, Action> | InjectionToken<ActionReducerMap<{ readonl...'.
  Type '(state: Test, action: TestAction) => Test' is not assignable to type 'InjectionToken<ActionReducerMap<{ readonly count: number; }, Action>>'.
    Property '_differentiate_from_OpaqueToken_structurally' is missing in type '(state: Test, action: TestAction) => Test'.
```
I only updated the interfaces and init files:

```
export interface Test {
  // define state here
  readonly count: number;
}

export interface TestState { readonly test: Test; }
```

```
import {Test} from './test.interfaces';

export const testInitialState: Test = {
  // fill it initial state here
  count: 4
};
```

**Comment by jvandemo** [comment]
We are seeing the same here. As soon as we add a property to the state, the following error appears:

```
Error:(20, 25) TS2345:Argument of type '(state: Mystate, action: MystateAction) => Mystate' is not assignable to parameter of type 'ActionReducerMap<{ version: number; }, Action> | InjectionToken<ActionReducerMap<{ version: numbe...'.
  Type '(state: Mystate, action: MystateAction) => Mystate' is not assignable to type 'InjectionToken<ActionReducerMap<{ version: number; }, Action>>'.
    Property '_differentiate_from_OpaqueToken_structurally' is missing in type '(state: Mystate, action: MystateAction) => Mystate'.
```

**Comment by ejmvar** [comment]
Same here.
I started a new project (curl from master), added ngrx, and served whthout issues.
But compilation failed once first element added to global (root) state.
How should I solve this?
Could be this issue still persists?

Thenks for so useful project.

**Comment by jvandemo** [comment]
@ejmvar &mdash; Do you have the latest version of the schematics installed?

```
yarn global add @nrwl/schematics
```

The error has disappeared here with the latest version.

**Comment by jvandemo** [comment]
@ejmvar &mdash; Also make sure that you have the latest version of nx installed (0.1.0-beta.0).

**Comment by ejmvar** [comment]
Started by re-installing @nrwl/schematics and @nrwl/nx.
Still the same.
Built another clean environment (using nvm).
No way. Same issue.
It's absolutely minimal install.
Sorry I'm not able to track this issue deeper enough.
Cannot determine where my environments are failing.
Thanks for your answer, @jvandemo.

**Comment by jvandemo** [comment]
@ejmvar &mdash; Do you have version 0.1.0-beta.0 installed? You can check in `node_module/@nrwl/nx/package.json`. If not, you can try to manually install it. 

Version 0.1.0-beta.0 solved the issue here. Thanks!
