### ISSUE TITLE
Export @nrwl/angular:init

### ISSUE THREAD

**Issue by srleecode** [nrwl/nx#6713]
## Description
Export generators from the @nrwl/angular index

## Motivation
I would like to use the @nrwl/angular initGenerator in my own generator. I can do the below for other generator packages, but not @nrwl/angular.
import { reactInitGenerator } from '@nrwl/react';
import { cypressInitGenerator } from '@nrwl/cypress';

## Suggested Implementation
Export the generators like the other packages do, e.g. https://github.com/nrwl/nx/blob/master/packages/react/index.ts

**Comment by FrozenPandaz** [comment]
The Angular Generators are exported from [here](https://github.com/nrwl/nx/blob/master/packages/angular/generators.ts).

However, `init` is not exported but we can add an export for it. Would you like to contribute adding the export?
