### ISSUE TITLE
nx 6.2 can't generate libs

### ISSUE THREAD

**Issue by isaacplmann** [nrwl/nx#672]
`ng g lib mylib` fails with the error:

```
Cannot read property 'entries' of undefined
```

With `@nrwl/nx@6.2.0`, `@angular/core@6.1.1`, `@nrwl/schematics@6.2.0`, `@angular-devkit/schematics@0.6.8` and `@schematics/angular@0.6.8`.

If I update to `@angular-devkit/schematics@0.7.2` and `@schematics/angular@0.7.2`, I get this error:

```
Tree type is not supported.
```

`@nrwl/schematics` definitely depends on those two packages, but has no peer dependency on them as far as I can tell.  What versions should I be using?

This is a pretty clean workspace - just tried setting up a new nx workspace today.  I'm working on a minimal reproduction repo.

**Comment by mxth** [comment]
I'm having the same issue with an existing project. Though, fresh project can generate lib.

**Comment by isaacplmann** [comment]
The problem may be with the [cli](https://github.com/angular/angular-cli/issues/11683)

**Comment by isaacplmann** [comment]
Yep, fixed by running:
```
npm uninstall -g @angular/cli
npm uninstall @angular/cli
npm i -g @angular/cli
npm i @angular/cli
```

**Comment by isaacplmann** [comment]
It would still be nice to know what the peerDependencies of `@nrwl/schematics` are.

**Comment by FrozenPandaz** [comment]
Glad you found your fix.

`@nrwl/schematics@6.2.0` is compatible with `@angular/cli@~6.1.0`.

In general, you should not have those packages installed directly. They should come from the `@angular/cli`.

**Comment by isaacplmann** [comment]
@FrozenPandaz thanks for the info.  It would be nice to have `@angular/cli` listed as a peerDependency to `@nrwl/schematics` then.

**Comment by kambbado** [comment]
@isaacplmann solution worked, why, I do not know,  I had tried everything else suggested above.
