### ISSUE TITLE
Nx Version 999.9.9?!?

### ISSUE THREAD

**Issue by spicemix** [nrwl/nx#6738]
npm is giving me Nx version 999.9.9...even all the libs are 999.9.9...I imagine you guys messed up a release numbering?

https://www.npmjs.com/package/nx

42 minutes ago as 999.9.9

**Comment by m4s7** [comment]
All nrwl packages seems to have same wrong version.
<img width="729" alt="Screenshot 2021-08-16 at 20 57 39" src="https://user-images.githubusercontent.com/59734315/129619590-a08b85bd-c391-4dc8-b71a-eb3fe0418948.png">

**Comment by teovillanueva** [comment]
how did this happen?

**Comment by andzno1** [comment]
I just migrated from Nx version 12.4.0 to latest and got the same problem:

![image](https://user-images.githubusercontent.com/4320938/129626004-413e3bb5-6391-48cb-8266-fa0f9f7f91a2.png)

![image](https://user-images.githubusercontent.com/4320938/129626028-f0c676ee-5b14-4659-9b41-03fbc8101a86.png)

`nx --version` yields:
```
$ nx --version
999.9.9
Done in 0.21s.
```

Also, it seems that `@angular/cdk` is not getting updated (stays at version 11.2.13). I don't know if this is intended, but there seem to be missing mixins:
```
Error: Module build failed (from ../node_modules/sass-loader/dist/cjs.js):
SassError: Undefined mixin.
   ╷
14 │   @include a11y.a11y-visually-hidden();
   │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  ../node_modules/@angular/material/core/_core.scss 14:3       core()
```

**Comment by brandonroberts** [comment]
The latest release version issue is being worked. Should be resolved here shortly.

**Comment by brandonroberts** [comment]
The packages are reporting correctly as `12.7.1` now
