### ISSUE TITLE
Error generating Lib In 6.2 -- > Path "/libs/auth/src/lib/+state/auth.effects.spec.ts" does not exist

### ISSUE THREAD

**Issue by rmacteague** [nrwl/nx#674]
Did this issue get reintroduced?  On both nrwl/nx 6.2 and schematics 6.2, angular 6.1.1, cli 6.1.2

**Comment by ilmstudios** [comment]
![image](https://user-images.githubusercontent.com/29419183/43846633-6ef1ae36-9af4-11e8-8baa-ff55d4674ac4.png)

I get a similar error for generating libs saying 'x.module.ts does not exist'.

**Comment by mottych** [comment]
![image](https://user-images.githubusercontent.com/2342955/46115968-9a872180-c1c7-11e8-897b-948bd8f32bb3.png)
Similar error here

**Comment by bcabanes** [comment]
Hi @mottych, you're error is related to this issue #755.

**Comment by bcabanes** [comment]
Hi @rmacteague,
Could you provide a link where we can see a reproduction of the bug please?
_Make sure to use the latest version of Nx for the reproduction._

Thank you.
