### ISSUE TITLE
Issue with Fastify Adapter in Nest - Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by adnanebrahimi** [nrwl/nx#6742]
## Current Behavior

By changing the Adapter to Fastify, routes will no longer work
```
 const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter()
  );
```
request GET: http://localhost:3000/api
```
// http://localhost:3000/api

{
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "Right-hand side of 'instanceof' is not an object"
}
```

## Expected Behavior

```
// 20210817131211
// http://localhost:3333/api

{
  "message": "Welcome to api!"
}

```
## Steps to Reproduce

[The repo with reproduced issue](https://github.com/adnanebrahimi/nx-nest-fastify)

1.` npx create-nx-workspace`
2. choose nest and name it api
3. run `npm i --save @nestjs/platform-fastify`
4. Add Fastify Adapter in main.ts by following [this instructions](https://docs.nestjs.com/techniques/performance)
5. Run project: `nx serve api`

### Failure Logs

-
### Environment

```
 NX  Report complete - copy this into the issue template

  Node : 14.17.5
  OS   : win32 x64
  npm  : 6.14.14

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.1.1
  @nrwl/cypress : Not Found
  @nrwl/devkit : 11.1.1
  @nrwl/eslint-plugin-nx : 11.1.1
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.1
  @nrwl/linter : 11.1.1
  @nrwl/nest : 11.1.1
  @nrwl/next : Not Found
  @nrwl/node : 11.1.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.1
  typescript : 4.0.8
```

**Comment by tamirazrab** [comment]
Can confirm this, I just switched adapter to fastify from express, prior my all routes were working fine, after switch facing the same error.

**Comment by laureanray** [comment]
I also can confirm this.

```
   "@nestjs/common": "^7.6.15",
    "@nestjs/core": "^7.6.15",
    "@nestjs/jwt": "^8.0.0",
    "@nestjs/passport": "^8.0.1",
    "@nestjs/platform-express": "^7.6.15",
    "@nestjs/platform-fastify": "^8.0.6",
```

**Comment by avantika3667** [comment]
> I also can confirm this. I use the ff version
> 
> ```
>    "@nestjs/common": "^7.6.15",
>     "@nestjs/core": "^7.6.15",
>     "@nestjs/jwt": "^8.0.0",
>     "@nestjs/passport": "^8.0.1",
>     "@nestjs/platform-express": "^7.6.15",
>     "@nestjs/platform-fastify": "^8.0.6",
> ```

With @nestjs => version 7 use same version of "@nestjs/platform-fastify": "^7.6.18"
It will work fine.

**Comment by nartc** [comment]
@adnanebrahimi Sorry for the late response. As @avantika3667 pointed out, if NestJS version is 7, please use the respective version of PlatformFastify. In your repo, you have NestJS 7 but PlatformFastify is 8
