### ISSUE TITLE
Add `--include` flag to `nx affected`

### ISSUE THREAD

**Issue by jordems** [nrwl/nx#6758]
## Description
Currently the `nx affected` only contains a `--exclude` flag to not allowing you to explicitly include apps in the command. 

## Motivation
The reason I think this is useful is because I'm running into this case currently. 

Our company has a fairly large mono-repo with a bunch of apps. But we are only deploying some apps to certain environments. And currently only the `exclude` flag exists.

So if there is 12 apps in our repo, and only 3 of them are being built and deployed to a specific environment. I'll use the `exclude` flag to stop all but the three apps from being built and deployed. But, now if another nx app is created in the repo, I need to remember to exclude it from the script. Gets very tedious. Adding the include flag would alleviate this by allowing us to select the specific list of apps to check for affected changes, then run the appropriate target. 

## Suggested Implementation
`yarn nx affected --include='app1,app2,app3' --target=build`
This would take into consideration only these three apps: app1,app2, and app3. And if any of them are affected then they will be built. Any other apps in the project will be ignored.

**Comment by sumitparakh** [comment]
Hey nx team, I would like to take this up.

**Comment by sumitparakh** [comment]
The issue talks about deploying to a specific env. In this case, you could have different targets, so you could do:

nx affected --target=deploy-to-qa // only consider 3 apps out of 12
nx affected --target=deploy-to-staging // only consider 9 apps out of 12

I think this is a cleaner solution that doesn't require you to manage lists of projects.

**Comment by jordems** [comment]
> As per [#6914 (comment)](https://github.com/nrwl/nx/pull/6914#issuecomment-920076226)
> 
> The issue talks about deploying to a specific env. In this case, you could have different targets, so you could do:
> 
> nx affected --target=deploy-to-qa // only consider 3 apps out of 12
> nx affected --target=deploy-to-staging // only consider 9 apps out of 12
> 
> I think this is a cleaner solution that doesn't require you to manage lists of projects.

Agreed, Thanks a lot for jumping on this!!
