### ISSUE TITLE
'ReactComponent' is not exported by lib

### ISSUE THREAD

**Issue by shubhamdeodia** [nrwl/nx#6761]
## Current Behavior
I am trying to bundle a svg publishable React ibrary, but when I try run build it fails with below error

`Error during bundle: Error: 'ReactComponent' is not exported by <path/to/svg>`

## Expected Behavior
Build should be sucessful

## Steps to Reproduce
Update project's worspace.json with 

`"webpackConfig": "@nrwl/react/plugins/webpack",`

Add typing to base tsconfig.base.json

` "files": ["./node_modules/@nrwl/react/typings/image.d.ts"],`

run 

`nx affected:build --base=remotes/origin/main --with-deps`

### Failure Logs
```
'elementType' is not exported by 'node_modules\prop-types\index.js'
'forwardRef' is not exported by 'node_modules\react\index.js'
'createElement' is not exported by 'node_modules\react\index.js'
'createElement' is not exported by 'node_modules\react\index.js'
Error during bundle: Error: 'ReactComponent' is not exported by <path to svg>
Bundle failed: iep-logos
```

### Environment
node: 16.3

Appreciate it if someone could provide a fix this. We have tring to publish internal React library based on SVGs and this is turning out to be major blocker.

**Comment by danr-za** [comment]
As a React library is built with rollup, you'll need to add svgr to rollup as well as url (if you are using it as source and not as a component)

https://react-svgr.com/docs/rollup/

**Comment by shubhamdeodia** [comment]
@danr-za : I changed the bundler to webpack and `@nrwl/react/plugins/webpack` already has svgr loader for svg files.

**Comment by marckassay** [comment]
@FrozenPandaz I'm also seeing this issue. [Here](https://github.com/marckassay/nunx) is a repo replicating this issue. I'm using yarn v1, and when I execute `yarn build`, I see the same as what @shubhamdeodia mentioned:

```
Error during bundle: Error: 'ReactComponent' is not exported by libs\feature\src\lib\logo.svg, imported by libs\feature\src\lib\feature.tsx
Bundle failed: feature
```

**Comment by marckassay** [comment]
I suppose a workaround is not to import Svgs as a ReactComponent. Such as done [here](https://github.com/marckassay/nunx/blob/feature/add-postcss-config/libs/feature/src/lib/feature.tsx).

**Comment by Shaglock** [comment]
Having the same issue. @FrozenPandaz  please take a look, this is not stale and repro is already done by @marckassay.

**Comment by doublemarked** [comment]
Moved past this today by patching the rollup config to include svgr,


```JSON
// workspace.json
   "rollupConfig": [
      "@nrwl/react/plugins/bundle-rollup",
      "packages/ui/bundle-rollup.cjs"
   ],
```


```Javascript
// packages/ui/bundle-rollup.cjs
const url = require('@rollup/plugin-url');
const svgr = require('@svgr/rollup').default;

module.exports = options => ({
    ...options,
    plugins: [ ...options.plugins, url(), svgr()],
});

```

**Comment by shubhamdeodia** [comment]
@danr-za and @doublemarked : your solution is correct and working. We cannot possibly change to webpack bundler for React Library, it always default to rollup. So additional changes are reuired in custom rollupt config.

**Comment by smithad15** [comment]
Can confirm that this is still an issue in the default setup for NX
