### ISSUE TITLE
No suggestion/auto-import for monorepo projects

### ISSUE THREAD

**Issue by diegovilar** [nrwl/nx#6780]
## Current Behavior

Editing a project file, VSCode cannot suggest/auto-import from other projects in the same NX monorepo.

I'm not sure this is a TSServer or VSCode thing, or if it's related to how NX structure tsconfigs from projects. SOMETIMES it works as expected, for instance, in nx-eamples. But then I add a new lib in nx-examples and it does not work for it. I can't put my finger on it...

## Expected Behavior

Given a repository with the following projects

- api `app`
- utils `lib`
- domain `lib`

Where both libs were generated with import paths, store in `tsconfig.base.json`

```json
{
    "baseUrl": ".",
    "paths": {
      "@my/domain": ["libs/domain/src/index.ts"],
      "@my/utils": ["libs/utils/src/index.ts"]
    }
}
````

I'd expect VSCode to suggest importing exported symbols from said libs when I use them in source files from all projects, instead of requiring me to manually import them for the editor know that they exist.

The interesting thing is that, sometimes, for some projects, it just works...

## Steps to Reproduce

1. Create a NX workspace;
2. Run `npm install` in it;
3. User NX generators to add 1 node app and 2 node libs, making sure to set import paths for both libs;
4. Open any source file from any of the projects and start typing exported symbols from any of the libs and notice that the editor doesn't suggest them, let alone auto-import them;
5. Try to manually import the same symbols and see that that paths are recognized.

Example repo: https://github.com/diegovilar/testing-imports

### Environment
```
  Node : 14.17.3
  OS   : linux x64
  npm  : 7.20.1
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.7.2
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.7.2
  @nrwl/eslint-plugin-nx : 12.7.2
  @nrwl/express : Not Found
  @nrwl/jest : 12.7.2
  @nrwl/linter : 12.7.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.7.2
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.7.2
  @nrwl/web : Not Found
  @nrwl/workspace : 12.7.2
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by ehaynes99** [comment]
Did you close this because you figured it out? If so... what was the solution?

**Comment by rauldeheer** [comment]
It doesn't work in Visual Studio Code, but it works fine in IntelliJ IDEA Ultimate. So it might be the settings?
