### ISSUE TITLE
Generate library module creates a 

### ISSUE THREAD

**Issue by Yonet** [nrwl/nx#68]
ng generate lib mymodule --ngmodule

generates:
```
libs/mymodule/apps/<apps[0]>src/mymodule.module.spec.ts
libs/mymodule/apps/<apps[0]>src/mymodule.module.ts
libs/mymodule/apps/<apps[0]>index.ts
```
instead of expected: 
```
libs/mymodule/src/mymodule.module.spec.ts
libs/mymodule/src/mymodule.module.ts
libs/mymodule/index.ts
```

"@angular/cli": "github:nrwl/fix-cli-build",
"@nrwl/nx": "nrwl/nx-build"

**Comment by vsavkin** [comment]
You are using a wrong version of the CLI in your package.json. You must use a patched version there.

Could you provide a repro?

**Comment by mgol** [comment]
I've hit it as well, it doesn't matter whether you're generating a new lib or app. Repro steps:

```sh
echo '{"packageManager": "yarn"}' >~/.angular-cli.json # this may not be necessary
yarn global add @angular/cli@next # installs CLI 1.5.0-rc.3
ng new foo-bar
cd foo-bar
yarn add @nrwl/schematics --dev
ng generate workspace app1 --collection=@nrwl/schematics
ng generate app app2
```

This creates the following directory structure:
```
apps
├── app1
│   ├── e2e
│   │   ├── app.e2e-spec.ts
│   │   └── app.po.ts
│   └── src
│       ├── app
│       │   ├── app.component.css
│       │   ├── app.component.html
│       │   ├── app.component.spec.ts
│       │   ├── app.component.ts
│       │   └── app.module.ts
│       ├── assets
│       ├── environments
│       │   ├── environment.prod.ts
│       │   └── environment.ts
│       ├── favicon.ico
│       ├── index.html
│       ├── main.ts
│       ├── polyfills.ts
│       ├── styles.css
│       └── typings.d.ts
└── app2
    ├── apps
    │   └── app1
    │       └── src
    │           ├── app
    │           │   ├── app.component.css
    │           │   ├── app.component.html
    │           │   ├── app.component.spec.ts
    │           │   ├── app.component.ts
    │           │   └── app.module.ts
    │           ├── assets
    │           │   └── nx-logo.png
    │           ├── environments
    │           │   ├── environment.prod.ts
    │           │   └── environment.ts
    │           ├── favicon.ico
    │           ├── index.html
    │           ├── main.ts
    │           ├── polyfills.ts
    │           └── styles.css
    └── e2e
        ├── app.e2e-spec.ts
        └── app.po.ts
```

**Comment by sasxa** [comment]
I had this issue also. I noticed in `.angular-cli.json` one of my libraries included path to app1:

      "root": "libs\\lib1\\apps\\app1\\src",

After deleting this (I'm not sure when or how it was added)

      "root": "libs\\lib1\\src",

generate works normally. 

    ng g s xxx -a lib1 -d
      create libs/lib1/src/xxx.service.spec.ts (356 bytes)
      create libs/lib1/src/xxx.service.ts (109 bytes)

**Comment by theivanaguilar** [comment]
Con confirm this happens with Angular 5.0.0

**Comment by rmacteague** [comment]
I have this issue as well, only happens on existing cli projects that were upgraded to a workspace.  Originally created workspaces work fine.

**Comment by vsavkin** [comment]
The issue is because you are using an unpatched version of the CLI. We point to the patched version of the CLI for this very reason. See here for more info: https://github.com/nrwl/nx/wiki/FAQ

**Comment by CharlieGreenman** [comment]
For those reading this and trying to figure out, simply modify your @angular/cli to look like this: 
`"@angular/cli": "file:.angular_cli.tgz",` 

The .angular_cli.tgz is generate by upgrading angular cli app to a workspace.
