### ISSUE TITLE
affected:lint doesn't pass format correctly

### ISSUE THREAD

**Issue by llehn** [nrwl/nx#680]
using nx 6.2 I try to run this:
````nx affected:lint --files=package.json --parallel --format=msbuild````

I get a bunch of error messages, because nx tries to execute this for each project:
````ng "lint" "--format=msbuild" "--format:write=msbuild" "--project=kui-base-components"````

the error message reads
````Unknown option: '--format:write'````

Somehow nx rewrites the format parameter and messes it up.

running ````ng lint --format=msbuild --project=kui-base-components```` works as expected

**Comment by FrozenPandaz** [comment]
Fixed with https://github.com/nrwl/nx/pull/876 + https://github.com/nrwl/nx/pull/903

You will need to run:
```sh
nx affected:lint --files=package.json --parallel -- --format msbuild
