### ISSUE TITLE
Collection "@schematics/angular" cannot be resolved.

### ISSUE THREAD

**Issue by solshark** [nrwl/nx#6820]
## Current Behavior

Cannot generate angular app/library.

## Steps to Reproduce

1. Created new workspace with `npx create-nx-workspace@latest --packageManager pnpm`
2. Trying to generate new library with `generate @nrwl/angular:library --name=shared-ui --linter=eslint --strict --unitTestRunner=jest`
3. Getting `Collection "@schematics/angular" cannot be resolved.`

### Environment

```
❯ pnx report

> birk@0.0.0 nx /Users/solshark/Development/wmt/birk
> nx "report"


>  NX  Report complete - copy this into the issue template

  Node : 14.17.5
  OS   : darwin x64
  pnpm : 6.14.2

  nx : Not Found
  @nrwl/angular : 12.7.2
  @nrwl/cli : 12.7.2
  @nrwl/cypress : 12.7.2
  @nrwl/devkit : 12.7.2
  @nrwl/eslint-plugin-nx : 12.7.2
  @nrwl/express : Not Found
  @nrwl/jest : 12.7.2
  @nrwl/linter : 12.7.2
  @nrwl/nest : 12.7.2
  @nrwl/next : Not Found
  @nrwl/node : 12.7.2
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.7.2
  @nrwl/web : Not Found
  @nrwl/workspace : 12.7.2
  @nrwl/storybook : 12.7.2
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by solshark** [comment]
I've created new project using following command:
`pnpx create-nx-workspace --package-manager=pnpm`

<img width="1278" alt="Screenshot 2021-09-15 at 13 39 26" src="https://user-images.githubusercontent.com/107233/133427218-6631b63d-0ab4-4319-9a10-65294284027f.png">

Next, trying to generate new library using plugin for WebStorm:
<img width="1605" alt="Screenshot 2021-09-15 at 13 47 06" src="https://user-images.githubusercontent.com/107233/133427732-1a786b5e-34f1-459a-ab43-b0449702810b.png">

git@github.com:solshark/i6820.git

**Comment by Coly010** [comment]
Hi @solshark , can you try generate the library manually using the command line? I'd just like to rule out the issue being related to the WebStorm Plugin as that isn't officially supported by us.

**Comment by solshark** [comment]
You right, it's related to plugin. I'll address to plugin maintainer. Sorry for confusion.

**Comment by nhhockeyplayer** [comment]
can you offer solution in more descriptive manner?
like actual command so we can cut paste that?
thanks

**Comment by nhhockeyplayer** [comment]
>[solshark](https://github.com/solshark) commented [on Sep 29, 2021](https://github.com/nrwl/nx/issues/6820#issuecomment-930071480)

why dont you close this issue when its fixed?

**Comment by nhhockeyplayer** [comment]
```
node node_modules/@nrwl/cli/bin/nx.js generate @nrwl/angular:library --name=auth --directory=shared/root/security/auth --tags=type:ui --unitTestRunner=jest --importPath=@nhhockeyplayer/auth --strict --linter=eslint --compilationMode=full --viewEncapsulation=Emulated --changeDetection=Default --style=scss --no-interactive --dry-run

>  NX  Generating @nrwl/angular:library


 >  NX   Collection "@schematics/angular" cannot be resolved.

   Pass --verbose to see the stacktrace.

```
