### ISSUE TITLE
Reuse or cache serve target across Cypress e2e projects with same devServerTarget

### ISSUE THREAD

**Issue by wrslatz** [nrwl/nx#6835]
## Description
Say I have two Cypress e2e projects, `myapp-feature-A-e2e` and `myapp-feature-B-e2e`, which test two parts of a single app, `myapp`. `myapp-feature-A-e2e` and `myapp-feature-B-e2e` both have the same `devServerTarget` of `myapp:serve:e2e`. These projects are split for a performance improvement with `affected`, and we have implicit dependencies from `myapp-feature-A-e2e` to `feature-A-lib` and from `myapp-feature-B-e2e` to `feature-B-lib`.

When both `myapp-feature-A-e2e` and `myapp-feature-B-e2e` target the same `devServerTarget`, they both do a full run of `myapp:serve:e2e`, which adds a performance overhead (in our case it's ~30 seconds). As the number of e2e prjects grows, so does the overhead for re-serving the `myapp:serve:e2e`.

It would be really helpful if e2e projects targeting the same `devServerTarget` could reuse that `serve` target without a full rebuild occurring.

## Motivation

For improved local development experience (and for teams that can't distribute e2e across multiple runners in CI), the performance improvements of reusing the same `serve` target would be a big boost to e2e testing speed, especially as the application grows.

## Suggested Implementation

Implementation options might include
1) Caching the `serve` target (not sure if this is currently possible) so subsequent `serve` actions are much faster
2) Running the `serve` target before running each `affected` e2e suite with the same `devServerTarget` targeting that same `serve` target (would need to handle stopping the serve after all of these e2e projects are done)

## Alternate Implementations

I'm not sure if incremental builds are a suitable solution here (slightly larger startup time for first e2e serve but much faster after that)

Somewhat related requests I've found before:
https://github.com/nrwl/nx/issues/1604
https://github.com/nrwl/nx/issues/3748

Our current workaround is following this suggestion (https://github.com/nrwl/nx/issues/3748#issuecomment-791278929) and using `start-server-and-test` package to run the app before executing all e2e. The reasons this implementation is less than ideal are
1) the dependency between serve and e2e run is no longer explicit
2) more cumbersome handling e2e with different targets (before it's as easy as a configuration with `"skipServe": true`, now it's a separate command for running e2e against a local target using `start-server-and-test`)
3) `start-server-and-test` doesn't support chaining arguments to the test command (https://github.com/bahmutov/start-server-and-test/issues/267), so we've had to add custom scripts to allow chaining arguments and it's hard to maintain

**Comment by wrslatz** [comment]
Cross-posting related request https://github.com/nrwl/nx/issues/5570

**Comment by wrslatz** [comment]
Updated https://github.com/nrwl/nx/discussions/7668#discussioncomment-3973376 with my latest attempt. Looks like neither `devServerTarget` or `dependsOn` work to solve this use case currently. `start-server-and-test` or using `devServerTarget` and eating the overhead of uncached `serve` target being called for each suite seem to be the two options.

**Comment by barbados-clemens** [comment]
so serve will never be able to be a cacheable target since it technically never ends. instead you should serve the build files like with @nrwl/web:file-server for static FE apps. then the build should be cacheable and make it quicker to startup/less resource intensive.

**Comment by wrslatz** [comment]
Looks like `@nrwl/web:file-server` can't use `proxy.conf.json` that the Angular serve uses, so we would have to setup a separate proxy config and keep it in sync with the Angular serve proxy config? This also doesn't seem ideal, but it may be worth investigating further as a workaround.

**Comment by barbados-clemens** [comment]
you could try setting the proxyOptions on it. or just running nginx with a run-commands if you need ultimate flexibility.

**Comment by barbados-clemens** [comment]
Just as a headsup, we are looking to auto generate a 'serve-static' target to apps in the coming months with should help people for things out of the box, though any custom stuff like a proxy config probably won't work on this initial round. but i'll keep this issue open to track the static file serving story.
