### ISSUE TITLE
nx v6.2.0 is not able to generate lazy routing module when using typescript 2.9.2

### ISSUE THREAD

**Issue by xmlking** [nrwl/nx#684]
### How to reproduce:
1. create new workspace and `webapp` 
3. update `typescript` version to `2.9.2` in `package.json`
2. try generating following modules 
```bash
ng g lib dashboard      --routing --lazy --prefix=ngx --parent-module=apps/webapp/src/app/app.module.ts       --tags=layout,entry-module
# this will fail silently 
ng g lib grid           --routing --lazy --prefix=ngx --parent-module=libs/dashboard/src/lib/dashboard.module.ts   --tags=child-module
```

### Success path:
if you change `typescript` version back to `2.7.2` , above generate commands works

**Comment by isaacplmann** [comment]
@xmlking Thanks for tracking down the workaround.  I had noticed this too, but I choose to just manually enter the code instead of finding a solution.

**Comment by edcarroll** [comment]
I've found this also stops you from being able to generate applications. Am manually downgrading to TS 2.7 if I need to generate one for now.

**Comment by FrozenPandaz** [comment]
Sorry, I know everyone want's the latest and greatest but please do not use `typescript@2.9.2` and stick to `typescript@~2.7.2`. We need to wait for `@angular/cli@~6.2.0` is released. We can keep this issue to track `typescript@~2.9.2` support.
