### ISSUE TITLE
Cannot serve web apps for webpack 4 on Nx 12.8

### ISSUE THREAD

**Issue by ashwinGokhale** [nrwl/nx#6853]
## Current Behavior

Trying to serve a brand new Nx React app fails for Nx v12.8.

## Expected Behavior

I expect serving an Nx React app to work. This is a regression.

## Steps to Reproduce

1. Clone [Nx examples repo](https://github.com/nrwl/nx-examples)
2. Run `yarn`
3. Upgrade to Nx 12.8: `yarn nx migrate latest && yarn && yarn nx migrate --run-migrations`
4. Serve the cart app: `yarn nx serve cart` 

### Failure Logs
```
$ nx serve cart

> nx run cart:serve 

>  NX  Web Development Server is listening at http://localhost:4200/

C:\Users\agokhale\source\nx-examples\node_modules\@nrwl\web\node_modules\webpack-dev-server\node_modules\webpack\lib\Dependency.js:311
                throw new Error(
                ^

Error: module property was removed from Dependency (use compilation.moduleGraph.updateModule(dependency, module) instead)
    at ProvidedDependency.set (C:\Users\agokhale\source\nx-examples\node_modules\@nrwl\web\node_modules\webpack-dev-server\node_modules\webpack\lib\Dependency.js:311:9)
    at iterationDependencies (C:\Users\agokhale\source\nx-examples\node_modules\@nrwl\web\node_modules\webpack\lib\Compilation.js:940:21)
    at C:\Users\agokhale\source\nx-examples\node_modules\@nrwl\web\node_modules\webpack\lib\Compilation.js:950:8
    at C:\Users\agokhale\source\nx-examples\node_modules\@nrwl\web\node_modules\webpack\lib\NormalModuleFactory.js:409:6
    at C:\Users\agokhale\source\nx-examples\node_modules\@nrwl\web\node_modules\webpack\lib\NormalModuleFactory.js:155:13
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (C:\Users\agokhale\source\nx-examples\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at C:\Users\agokhale\source\nx-examples\node_modules\@nrwl\web\node_modules\webpack\lib\NormalModuleFactory.js:138:29
    at C:\Users\agokhale\source\nx-examples\node_modules\@nrwl\web\node_modules\webpack\lib\NormalModuleFactory.js:346:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

———————————————————————————————————————————————

>  NX   ERROR  Running target "cart:serve" failed

  Failed tasks:

  - cart:serve

  Hint: run the command with --verbose for more details.


>  NX   CLOUD  See run details at https://nx.app/runs/OgZScQIG8w2

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment

```
  Node : 14.16.1
  OS   : win32 x64
  yarn : 1.22.5

  nx : Not Found
  @nrwl/angular : 12.8.0
  @nrwl/cli : 12.8.0
  @nrwl/cypress : 12.8.0
  @nrwl/devkit : 12.8.0
  @nrwl/eslint-plugin-nx : 12.8.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.8.0
  @nrwl/linter : 12.8.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : 12.3.10
  @nrwl/react : 12.8.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.8.0
  @nrwl/web : 12.8.0
  @nrwl/workspace : 12.8.0
  @nrwl/storybook : 12.8.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by ashwinGokhale** [comment]
@FrozenPandaz looks like your branch has been deleted. I deleted my node_modules in the nx-examples repo and it started working but I was still seeing the error ^ in my own repo. The way to reproduce in the nx-examples repo is to remove the [version of webpack-dev-server](https://github.com/nrwl/nx-examples/blob/master/package.json#L108) and run yarn. Once I added the webpack-dev-server line in my own package.json it hoisted webpack-dev-server v3.11.2 to the top level in the local node_modules folder and started working. Looks like for some reason you have to explicitly specify the version in the package.json. This might be a bug.

**Comment by brianmcd** [comment]
> @FrozenPandaz looks like your branch has been deleted. I deleted my node_modules in the nx-examples repo and it started working but I was still seeing the error ^ in my own repo. The way to reproduce in the nx-examples repo is to remove the [version of webpack-dev-server](https://github.com/nrwl/nx-examples/blob/master/package.json#L108) and run yarn. Once I added the webpack-dev-server line in my own package.json it hoisted webpack-dev-server v3.11.2 to the top level in the local node_modules folder and started working. Looks like for some reason you have to explicitly specify the version in the package.json. This might be a bug.

Sounds like maybe another instance of https://github.com/nrwl/nx/issues/6662?

**Comment by ashwinGokhale** [comment]
@brianmcd it is possible it is another instance of #6662 but I have no idea how to confirm whether or not it is.

**Comment by jaysoo** [comment]
This is an issue if webpack 4 and 5 are both installed to the same repo (because React uses 4, and Angular uses 5). There are interface mismatches between the plugins the different webpack versions.

In this case I'd recommend running `nx g @nrwl/web:webpack-5` for Nx 12 to upgrade  React to webpack 5.

Or wait until Nx 13 where we will only support Nx 13 so this will not be an issue .
