### ISSUE TITLE
running affected:test --all reports wrong failures

### ISSUE THREAD

**Issue by llehn** [nrwl/nx#687]
using nx 6.2 
when I run nx affected:test --all it runs all the tests, but then at then end prints:
````Failed projects: docker-management,utils,testids,domain-states,e2e-objects````

Those projects have no "test" target defined in angular.json, so they are not tested by ng and thus should not be reported as failed IMHO.

**Comment by kpaxton** [comment]
you need to set in your karma.conf.js ```failOnEmptyTestSuite: false```. that is a karma thing.

**Comment by llehn** [comment]
the projects in question have no karma.conf.js. ng test is not being run for those projects

**Comment by FrozenPandaz** [comment]
Something is wrong with how `--only-failed` is reading the cache. Those failed projects are stored in there because they are removed from the task instead of being fixed (and thus, the file is never removed)

**Comment by pglazkov** [comment]
Is there an update about this issue or a workaround?

**Comment by pglazkov** [comment]
Never mind, deleting `dist/.nx-results` fixed the issue for me.

**Comment by cwmrowe** [comment]
I had this issue while running tests for my libs with Jest and running with Jest flag  `--passWithNoTests` seems to have resolved it.
````
npm run affected:test -- --base=master --passWithNoTests

**Comment by bcabanes** [comment]
Issue resolved, closing.

**Comment by weblancaster** [comment]
I created a lib and later decided to delete which caused `NX   ERROR  Running target "test" for affected projects failed`, turns out the issue was in the `dist/.nx-results` as @pglazkov mentioned.

Thank you.
