### ISSUE TITLE
make `stringUtils` part of devkit instead workspace package to mitigate requirement on implicit angular-devkit install

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#6876]
## Description
`stringUtils` are part of `workspace` package. This means users have to install angular devkit if they wanna use string utils in they generators.

## Suggested Implementation

- move https://github.com/nrwl/nx/blob/301e70aa7a8759ee428ef59070f09e0d755f8d33/packages/workspace/src/utils/strings.ts to devkit package

## Related issues
https://github.com/nrwl/nx/issues/6153

**Comment by merlosy** [comment]
Hi! 
```ts
import { names } from '@nrwl/devkit';
``` 
seems to do the trick for me, with some changes in the code to adapt.
