### ISSUE TITLE
One workspace for each project or one workspace for everything.

### ISSUE THREAD

**Issue by boicetomlin** [nrwl/nx#688]
We are interested in using NX for all of our client projects - many clients each with as many as four apps each.  Because we have so many clients and apps we wanted to use the --directory option to keep everything organized a bit.  But as we started creating libs we noticed it pre-pended the directory name we chose - #573.  This made me think we might be using this tool incorrectly.  It would be nice to have all apps for all clients under one big repo because then we could reuse several shared libraries we have written.  Some clarity on development like this is needed in the documentation and examples.  All the examples we've looked at seem to be creating apps for a single domain or project even though one of the major advantages seems to be code reuse.  The examples however would lead one to believe that if you want to create more apps for a separate project you need to create more workspaces.  Then of course the code reuse idea is gone. For instance we are going to have a LayoutModule for 50+ clients and at least 2 projects each.  That's 100+ modules called LayoutModule all put in different subdirectories by client.  Prefixing each of those modules with the client name and app type is just not reasonable.  This is what caused us to pause and think maybe the intention was for us to create separate workspaces and thus avoid these naming issues.

**Comment by FrozenPandaz** [comment]
Hi, I do not think this is the best forum to discuss this.

Please ask your question on the [Gitter](https://gitter.im/nrwl-nx/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge))
