### ISSUE TITLE
Typescript is required by @nrwl/next but not added as dependency in built nextjs app in dist

### ISSUE THREAD

**Issue by searchableguy** [nrwl/nx#6886]
## Current Behavior

Generated package.json from nx build doesn't have typescript listed as a dependency. It is required to run the built nextjs app by `@nrwl/next` package. It will work locally because typescript is installed at root but won't in a dockerized environment or if you move the built folder outside the root.

## Expected Behavior

To run normally. I don't know if it worked before. I'm using nx for the first time.

## Steps to Reproduce

https://github.com/searchableguy/nx-next-typescript-error

### Failure Logs
Included in the error.log in the reproduction repo.

### Environment
```
>  NX  Report complete - copy this into the issue template

  Node : 16.8.0
  OS   : linux x64
  pnpm : 6.14.3
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.8.0
  @nrwl/cypress : 12.8.0
  @nrwl/devkit : 12.8.0
  @nrwl/eslint-plugin-nx : 12.8.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.8.0
  @nrwl/linter : 12.8.0
  @nrwl/nest : Not Found
  @nrwl/next : 12.8.0
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.8.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.8.0
  @nrwl/web : 12.8.0
  @nrwl/workspace : 12.8.0
  @nrwl/storybook : 12.8.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by nsmith7989** [comment]
I can reproduce this issue. From my project it seems to have appeared between 12.6.2 and 12.8.0.

I can also confirm manually adding typescript to the built app's package.json corrects the issue.

**Comment by amanintech** [comment]
I have the same issue 
Migrations from 12.4 => 12.9 and docker fails

**Comment by amanintech** [comment]
Tried with typescript install
With Docker file ~

```
FROM node:lts-alpine
WORKDIR /app
COPY /dist/apps/partnersite .
ENV NODE_ENV production
ENV PORT=3000

EXPOSE ${PORT}

RUN npm install --production typescript@4.3.5 -g

CMD ["npm", "start"]
```

Docker run output
![image](https://user-images.githubusercontent.com/28403318/132977062-41aabdc0-ae62-4acd-abbc-6341865c55b5.png)

NX report
```
>  NX  Report complete - copy this into the issue template

  Node : 16.9.1
  OS   : darwin arm64
  npm  : 7.21.1
  
  nx : 12.9.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : 12.9.0
  @nrwl/node : Not Found
  @nrwl/nx-cloud : 12.3.10
  @nrwl/react : 12.9.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```
