### ISSUE TITLE
Use of build --with-deps produces Error: ENOENT: no such file or directory, open 'libs/scope/some-lib/package.json'

### ISSUE THREAD

**Issue by cdaringe** [nrwl/nx#6896]
## Current Behavior

`nx build --with-deps`

yields:

`Error: ENOENT: no such file or directory, open '/opt/app/libs/scope/some-lib/package.json'`

This occurs because the recursive logic [scans for buildable libs, and attempts to extract information from `package.json`](https://github.com/nrwl/nx/blob/0a6434dbf62dc9402a263abe072c92421c3d0b08/packages/workspace/src/utilities/buildable-libs-utils.ts#L41-L47).

My lib is buildable, but has no package.json. It was my understanding that only publishable libraries need package.json, but in the link above, one can observe no such check.

Library entry in workspace.json:

```json
"scope-some-lib": {
  "root": "libs/scope/some-lib",
  "sourceRoot": "libs/scope/some-lib/src",
  "projectType": "library",
  "targets": {
    "build": {
      "executor": "@nrwl/node:build",
      "options": {
        "buildLibsFromSource": true,
        "outputPath": "dist/libs/scope/some-lib",
        "tsConfig": "libs/scope/some-lib/tsconfig.mocks.json",
        "main": "libs/scope/some-lib/src/lib/mocks.ts"
      },
      "outputs": ["{options.outputPath}"],
      "configurations": {
        "production": {
          "optimization": true
        }
      }
    }
  }
}
```

## Expected Behavior

No attempt to read a package.json, or a toleration of no package.json.

## Steps to Reproduce

TBD

### Failure Logs

Stack

```
Error: ENOENT: no such file or directory, open '/opt/app/libs/scope/some-lib/package.json'
    at Object.readJsonFile (/@nrwl+workspace@11.4.0_prettier@2.2.1/packages/workspace/src/utilities/fileutils.ts:38:38)
    at /@nrwl+workspace@11.4.0_prettier@2.2.1/packages/workspace/src/utilities/buildable-libs-utils.ts:51:32
    at Array.map (<anonymous>)
    at Object.calculateProjectDependencies (/@nrwl+workspace@11.4.0_prettier@2.2.1/packages/workspace/src/utilities/buildable-libs-utils.ts:45:6)
    at getProjectDeps (/@nrwl+next@11.4.0_0f5c2d6afb5eccfe7050ff326ee45ecc/packages/next/src/executors/build/lib/create-package-json.ts:14:34)
    at Object.createPackageJson (/@nrwl+next@11.4.0_0f5c2d6afb5eccfe7050ff326ee45ecc/packages/next/src/executors/build/lib/create-package-json.ts:50:45)
    at Object.<anonymous> (/@nrwl+next@11.4.0_0f5c2d6afb5eccfe7050ff326ee45ecc/packages/next/src/executors/build/build.impl.ts:25:3)
```

Annotated (reverse stack):

- https://github.com/nrwl/nx/blob/91002d43b6b72136848a40b9650d8e685a4d1534/packages/next/src/executors/build/build.impl.ts#L25
- https://github.com/nrwl/nx/blob/91002d43b6b72136848a40b9650d8e685a4d1534/packages/next/src/executors/build/lib/create-package-json.ts#L50
- https://github.com/nrwl/nx/blob/91002d43b6b72136848a40b9650d8e685a4d1534/packages/next/src/executors/build/lib/create-package-json.ts#L14
- https://github.com/nrwl/nx/blob/91002d43b6b72136848a40b9650d8e685a4d1534/packages/workspace/src/utilities/buildable-libs-utils.ts#L47-L53
 
### Environment

Occurs in multiple envs!

```

>  NX  Report complete - copy this into the issue template

  Node : 16.6.2
  OS   : darwin x64
  pnpm : 6.14.3
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.0.0
  @nrwl/cypress : 12.0.0
  @nrwl/devkit : 12.0.0
  @nrwl/eslint-plugin-nx : 12.0.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.4.0
  @nrwl/linter : 12.0.0
  @nrwl/nest : Not Found
  @nrwl/next : 11.4.0
  @nrwl/node : 11.4.0
  @nrwl/react : 12.0.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.0
  @nrwl/web : 12.0.0
  @nrwl/workspace : 12.0.0
  @nrwl/storybook : 12.0.0
  @nrwl/gatsby : 12.0.0
  typescript : 4.1.4

```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This is the intended behavior, the `package.json` is needed by our solution for buildable libs. If you generate a library with the flag `--buildable`, you'll see it gets generated for you.
