### ISSUE TITLE
Component test : Template parse errors

### ISSUE THREAD

**Issue by raphael-volt** [nrwl/nx#69]
I have create my Nx Workspace with an app and a lib. I have added a simple component to the lib and added it to app component template.
No problem when I serve the app, but when I run the tests, this error is thrown in app.component.spec.ts: 
```txt
Failed: Template parse errors:
'app-my-button' is not a known element:
1. If 'app-my-button' is an Angular component, then verify that it is part of this module.
2. If 'app-my-button' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<app-my-button></app-my-button>
```

**Comment by wolfhoundjesse** [comment]
Did you import it into and declare it in your appmodule?

**Comment by raphael-volt** [comment]
I am almost certain that it's not a problem with imports and declarations, because `ng build` compiles without errors, and the component is correctly rendered using `ng serve`.

Here is my repo : [raphael-volt/nx-experiments](https://github.com/raphael-volt/nx-experiments)

I have added the imports and declarations in the appmodule on the fix/imports branch but I still get the error.

**Comment by vsavkin** [comment]
Your test needs to import the right module as well, currently it doesn't, see here:

```
  beforeEach(
    async(() => {
      TestBed.configureTestingModule({
        declarations: [AppComponent]
      }).compileComponents();
    })
  );
```

You probably want something like this:

```
  beforeEach(
    async(() => {
      TestBed.configureTestingModule({
        declarations: [AppComponent],
        imports: [SampleLibModule]
      }).compileComponents();
    })
  );
```

**Comment by vsavkin** [comment]
Closing this issue.
