### ISSUE TITLE
styled-components.browser.esm.js.map not found when running the dev-server

### ISSUE THREAD

**Issue by dominikspiertz** [nrwl/nx#6908]
## Current Behavior
When starting a react dev server, we always get an error in the network tab of the browser, that the source map for styled-components cannot be found (404). 

## Expected Behavior
The react dev server should serve the source map for styled-components

## Steps to Reproduce
1. Create a react project in the workspace and choose styled-components as css option
2. Start dev server and open up the browser
3. Open up the developer console to see the error

### Failure Logs
`Failed to load resource: the server responded with a status of 404 (Not Found): http://localhost:4200/styled-components.browser.esm.js.map`

### Environment
Node : 15.12.0
OS   : darwin x64
yarn : 1.22.5
  
nx : Not Found
@nrwl/angular : Not Found
@nrwl/cli : 12.8.0
@nrwl/cypress : 12.8.0
@nrwl/devkit : 12.8.0
@nrwl/eslint-plugin-nx : 12.8.0
@nrwl/express : Not Found
@nrwl/jest : 12.8.0
@nrwl/linter : 12.8.0
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/nx-cloud : Not Found
@nrwl/react : 12.8.0
@nrwl/schematics : Not Found
@nrwl/tao : 12.8.0
@nrwl/web : 12.8.0
@nrwl/workspace : 12.8.0
@nrwl/storybook : 12.8.0
@nrwl/gatsby : Not Found
typescript : 4.3.5

**Comment by nemonemi** [comment]
I'm experiencing the same issue. Tested both in Chrome and Firefox.
From Firefox:
```
Source map error: Error: request failed with status 404
Resource URL: http://localhost:4203/vendor.js
Source Map URL: styled-components.browser.esm.js.map
```
but also:
```
Source map error: Error: request failed with status 404
Resource URL: http://localhost:4203/vendors-node_modules_gqless_logger_dist_gqless-logger_esm_js.js
Source Map URL: gqless-logger.esm.js.map
```

In my case, when I do a console.log to test it, it starts logging correctly, but then reverts to the `react_devtols_backend.js:****:**`
