### ISSUE TITLE
Module federation using webpack 5 & React or Next JS 11

### ISSUE THREAD

**Issue by writam-roy** [nrwl/nx#6909]
I was curious to know if at this stage Nx supports webpack 5 module federations with React app or NextJs 11?,I do see a few links around how to do it for Angular apps, but I don't find one for React, It would be really helpful If any knowledge, can be shared around this topic(Links,Examples)

**Comment by leosvelperez** [comment]
@writam-roy you can find information about this in the following docs https://nx.dev/latest/react/guides/webpack-5#webpack-5-migration. There are sections for React and Next.js.

**Comment by sushruth** [comment]
@leosvelperez There is no information about setting up module federation in there.
