### ISSUE TITLE
Issue with adding fastify in Nest plugin

### ISSUE THREAD

**Issue by mo0om** [nrwl/nx#6915]
## Current Behavior
I have a Nest.js app inside my NX repo.
I'm trying to bundle main.js for production and i'm getting this error
`fastify not found, proceeding anyway`

I'm not getting this error when I'm serving the app in dev mode.

```typescript
// main.ts
// inside bootstrap()
...
 const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter())
...
  await app.listen(port, '0.0.0.0', () => {
    Logger.info({
      message: 'Listening at http://localhost:' + port + '/' + globalPrefix
    })
  })

```

```typescript
// angular.json
"production": {
              "optimization": true,
              "outputHashing": "all",
              "extractLicenses": true,
              "inspect": false,
              "namedChunks": true,
              "aot": true,
              "vendorChunk": true,
              "buildOptimizer": true,
              "externalDependencies": [
                "@nestjs/microservices",
                "@nestjs/microservices/microservices-module",
                "@nestjs/websockets/socket-module",
                "cache-manager",
                "class-transformer",
                "class-validator",
                "class-transformer/storage"
              ]

```

```javascript
// webpack.config.ts
const webpack = require('webpack')

const SwaggerPluginOptions = {
  dtoFileNameSuffix: ['.dto.ts', '.entity.ts', '.view.ts'],
  classValidatorShim: true,
  introspectComments: true
}

module.exports = (config, _context) => {
  config.module.rules
    .filter((rule) => rule.loader.includes('ts-loader'))
    .forEach((tsRule) => {
      tsRule.options = { ...tsRule.options }
      tsRule.options.transpileOnly = false
      tsRule.options.getCustomTransformers = addSwaggerPluginTransformer(tsRule.options.getCustomTransformers)
    })

  config.plugins = [
    ...(config.plugins || []),
    new webpack.ProvidePlugin({
      openapi: '@nestjs/swagger'
    })
  ]
  return config
}

function addSwaggerPluginTransformer(prevGetCustomTransformers) {
  return (program) => {
    const customTransformers = { ...(prevGetCustomTransformers ? prevGetCustomTransformers(program) : undefined) }
    customTransformers.before = [
      require('@nestjs/swagger/plugin').before(SwaggerPluginOptions, program),
      ...(customTransformers.before || [])
    ]
    return customTransformers
  }
}
```

## Expected Behavior
Expect fastify to be bundled inside main.js

### Failure Logs
`fastify not found, proceeding anyway`

### Environment

>nx report 
  nx : Not Found 
  @nrwl/angular : 10.0.12
  @nrwl/cli : 10.0.12
  @nrwl/cypress : 10.0.12
  @nrwl/eslint-plugin-nx : 12.8.0
  @nrwl/express : Not Found
  @nrwl/jest : 10.0.12
  @nrwl/linter : 11.6.0
  @nrwl/nest : 12.8.0
  @nrwl/next : Not Found
  @nrwl/node : 12.8.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.8.0
  @nrwl/web : Not Found
  @nrwl/workspace : 10.0.12
  typescript : 3.9.7

> "@nestjs/common": "^7.0.0",
    "@nestjs/core": "^7.0.0",
    "@nestjs/platform-express": "^7.0.0",
    "@nestjs/platform-fastify": "^7.0.0",
    "@nestjs/swagger": "4.8.0",
    "@nestjs/schematics": "^7.0.0",
    "@nestjs/testing": "^7.0.0",
    "fastify-swagger": "^4.8.4",

**Comment by nartc** [comment]
@mo0om sorry for the late response. Can you provide a reproduce sample?

**Comment by nartc** [comment]
It has been 3 months. If you can create a simple reproduce, please create a new issue.
