### ISSUE TITLE
Nx not updated for Angular 12.2.x

### ISSUE THREAD

**Issue by sskieller** [nrwl/nx#6916]
Angular has been updated to 12.2.x with the new forms validations here: https://github.com/angular/angular/blob/master/CHANGELOG.md#1220-2021-08-04 

Nx is lacking behind on the 12.2.x version - when do we get 12.2.x for nx?

**Comment by leosvelperez** [comment]
This was already merged in https://github.com/nrwl/nx/pull/6836 and it will be released on version 12.9.0 early next week. Please keep an eye on the releases.
