### ISSUE TITLE
Can't create new workspace

### ISSUE THREAD

**Issue by iamyuu** [nrwl/nx#6934]
## Current Behavior

Attempt create a new workspace

<img width="756" alt="Screen Shot 2021-09-04 at 06 48 01" src="https://user-images.githubusercontent.com/45778229/132074960-78d4fe2d-d0b0-4419-82a0-25019ef850cd.png">

## Expected Behavior

this should successfully create a new workspace

## Steps to Reproduce

create a new workspace using `npx create-nx-workspace`

### Failure Logs

<img width="988" alt="Screen Shot 2021-09-04 at 06 44 34" src="https://user-images.githubusercontent.com/45778229/132074772-24236333-ea3d-4103-8604-078bb833b5eb.png">

### Environment

```sh
  System:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 172.88 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.volta/tools/image/node/14.17.0/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 7.20.0 - ~/.volta/tools/image/npm/7.20.0/bin/npm
    Watchman: 2021.08.02.00 - /usr/local/bin/watchman
```

**Comment by khalid283** [comment]
`oss` preset has been renamed to `npm`, you should update `create-nx-workspace` and try again.

**Comment by iamyuu** [comment]
Previously I've tried choosing another preset but the result is the same so I created a new issue, but the problem is in the version of `create-nx-workspace` that I'm using, I'm using `npx` and I'm not sure how to update it
