### ISSUE TITLE
Common Vendor Bundle Across Apps

### ISSUE THREAD

**Issue by imranweb** [nrwl/nx#6945]
I was going through the older issue here https://github.com/nrwl/nx/issues/1847
Looks like its closed as unresolved.

I am looking for having a common vendor bundle across apps which includes some common packages used across apps (React, React DOM, NextJS, Redux, etc).

e.g. I have two apps (app1 and app2).
There should be common bundle generated (vendor.xxxx.js). It should be loaded across app.

**Comment by imranweb** [comment]
@FrozenPandaz any suggestion here?

**Comment by jsanta** [comment]
I'm bringing a zombie back to life but just in case someone looks for this and doesn't find any answers.
This is somewhat what's achievable with micro-frontends.
I once made some naive attempts of implementing a "shared vendor" my own way. Read much about Webpack's DLLs, and failed implementing it (bit it seems to be the way). Ended up generating the required libraries UMD bundles and making some strange module definitions.
It's Angular related but it may give some ideas:
https://github.com/manfredsteyer/ngx-build-plus/issues/314
