### ISSUE TITLE
why remove typescript preprocessor in 12.8.0? 

### ISSUE THREAD

**Issue by mhamri** [nrwl/nx#6946]
today I ran `nx migrate latest` and the migration generated was 

```
{
  "migrations": [
    {
      "cli": "nx",
      "version": "12.8.0-beta.0",
      "description": "Remove Typescript Preprocessor Plugin",
      "factory": "./src/migrations/update-12-8-0/remove-typescript-plugin",
      "package": "@nrwl/cypress",
      "name": "remove-typescript-plugin"
    }
  ]
}
```

this cause the cypress to lose its ts preprocessors.

```diff
const { preprocessTypescript } = require('@nrwl/cypress/plugins/preprocessor');

/**
 * @type {Cypress.PluginConfig}
 */
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  // Preprocess Typescript file using Nx helper
- on('file:preprocessor', preprocessTypescript(config));
};
``` 
I came and visited the release, and saw if the project doesn't have any target, then it removes the preprocessor. 

though still cypress can run, but there is no typechecking anymore and I can pass wrong set of arguments to a function now!

1- this is a fresh nx project that is generated with `nx 12.1.0` version. if there should be a target, the migration should be adding it. with this migration the whole typechecking is being removed from my e2e projects. 
2- where the target should be added? where is the related documentation?
3- [this release](https://github.com/nrwl/nx/pull/6803#ref-commit-dc93a6a) doesn't have any explanation, no task is linked, what was the problem, what we should do? 
4- if the `preprocessor` isn't meant to be there, the import also should be removed not only the usage.

**Comment by edbzn** [comment]
Hi @mhamri, looks like the explanation is here https://github.com/nrwl/nx/pull/6706, also I know that Cypress removed the preprocessor event in 7.0.0 in favor of a `dev-server:start`.

**Comment by mhamri** [comment]
Thanks @edbzn for the link to the commit, look like I looked into the wrong one. you are right, cypress can process the ts but they have a bug that doesn't show the ts error

**Comment by edbzn** [comment]
Something weird is that the migration keeps the import: 

```ts
const { preprocessTypescript } = require('@nrwl/cypress/plugins/preprocessor');

module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  // Preprocess Typescript file using Nx helper
};
```

Is it the desired behavior?
