### ISSUE TITLE
Next.js | Multi process child spawned when run "nx serve core" command with repetitive string logged

### ISSUE THREAD

**Issue by ild0tt0re** [nrwl/nx#6952]
## Current Behavior
When i run `nx serve core` command, multiple child process are spawned with repetitive string logged to console: 

> Using external babel configuration from /Users/angeloca/Projects/fe.monorepo/apps/core/.babelrc

## Expected Behavior
The string above is shown only one time with faster app startup 

## Steps to Reproduce
Install nextjs app and start it with `nx serve core` command

### Failure Logs

**Nx/Next logs**
![nx-serve-next](https://user-images.githubusercontent.com/1527913/132465424-003a3021-d2ff-4bdf-9edb-565433ec19c8.png)

**Multi process spawned**
<img width="418" alt="process-child" src="https://user-images.githubusercontent.com/1527913/132466226-be254db7-8a84-44a6-a99f-60eccd9f95b9.png">

### Environment

```
  Node : 14.17.0
  OS   : darwin x64
  yarn : 1.22.10

  nx : 12.7.2
  @nrwl/angular : Not Found
  @nrwl/cli : 12.7.2
  @nrwl/cypress : 12.7.2
  @nrwl/devkit : 12.7.2
  @nrwl/eslint-plugin-nx : 12.7.2
  @nrwl/express : Not Found
  @nrwl/jest : 12.7.2
  @nrwl/linter : 12.7.2
  @nrwl/nest : Not Found
  @nrwl/next : 12.7.2
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.7.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.7.2
  @nrwl/web : 12.7.2
  @nrwl/workspace : 12.7.2
  @nrwl/storybook : 12.7.2
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by kirjai** [comment]
hi @ild0tt0re, thanks for reporting this issue!

there's been a lot of changes to the terminal output recently, could you please try with the latest version and report back, if this is still an issue for you?
