### ISSUE TITLE
Failure to write cache hash makes task to exit with non 0 exit code (to fail)

### ISSUE THREAD

**Issue by minijus** [nrwl/nx#6957]
## Current Behavior
In not very stable fs environments (mounted cache directory with NFS based volume) there are sometimes failures on atomic fs operations. Ideally these should be handled (when possible) and the actual task run should not exit with failure.

![image](https://user-images.githubusercontent.com/3633549/132483702-79862880-b1a2-4c58-8596-139b8cd949d5.png)

## Expected Behavior
Failure to write latest cache hash should be reported but it should not make the task run exit with failure.

Would it be enough to wrap [writeToFile](https://github.com/nrwl/nx/blob/master/packages/workspace/src/tasks-runner/cache.ts#L154) into `try/catch`? Could it potentially break something on workspace? Or is it just that latest cache hash entry will be missing?

## Steps to Reproduce

- Have unstable fs, or
- Mock fs import to fail.

### Environment
```
>  NX  Report complete - copy this into the issue template

  Node : 14.17.5
  OS   : darwin x64
  npm  : 6.14.14
  
  nx : Not Found
  @nrwl/angular : 12.9.0
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : 12.9.0
  @nrwl/next : Not Found
  @nrwl/node : 12.9.0
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

```

**Comment by minijus** [comment]
Had to revert `@nrwl/*` back to `12.8` for now. The issue is not present with `12.8`.

**Comment by FrozenPandaz** [comment]
Fixed with https://github.com/nrwl/nx/pull/6959
