### ISSUE TITLE
Generate new eslint rule should install the deps

### ISSUE THREAD

**Issue by ArielGueta** [nrwl/nx#6967]
I'm using the new eslint generator:

`nx g @nrwl/linter:workspace-rule my-custom-rule`

but it doesn't install the `@typescript-eslint/experimental-utils` package. I need to do it manually.

**Comment by meeroslav** [comment]
@ArielGueta can you tell me which version of Nx you are using (assuming 12.9.0), what package manager and what type of projects do you have (with which linter)?

I tried reproducing the issue, but as soon as there is a lintable project the `@typescript-eslint/experimental-utils` should be installed. It could be that `node_modules` is corrupted, in which case removing it and re-running `npm i` (or `yarn`) should solve it.

**Comment by ArielGueta** [comment]
Maybe an npm issue. Thanks.
