### ISSUE TITLE
Angular build production failure after updating to Nx 12.9 

### ISSUE THREAD

**Issue by olsonjj** [nrwl/nx#6976]
After updating our mono repo from Nx 12.8 to Nx 12.9, production builds are failing with the following error:  

## Current Behavior

Running nx build {APP_NAME} -c production fails on routing module with an error about dynamic imports not currently enabled. 

## Expected Behavior

Builds were working prior to the update. 

## Steps to Reproduce
nx migrate latest
npm install 
nx migrate --run-migrations

This updated nx dependencies with 12.9 from 12.8. It also updated our Angular and Angular Material to 12.2.5

### Failure Logs

`
./apps/live-eda/src/app/app.routing.module.ts - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
SyntaxError: /Users/jolson/Documents/Code/ipro-mono-repo/apps/live-eda/src/app/app.routing.module.ts: Support for the experimental syntax 'dynamicImport' isn't currently enabled (9:29):

   7 |     {
   8 |         path: '',
>  9 |         loadChildren: () => import('./views/eda-list/eda-list.module').then((m) => m.EdaListModule),
     |                             ^
  10 |         canActivate: [LiveEDAAuthGuard],
  11 |     },
  12 |     {`

### Environment

"dependencies": {
    "@angular/animations": "12.2.5",
    "@angular/cdk": "^12.2.5",
    "@angular/common": "12.2.5",
    "@angular/compiler": "12.2.5",
    "@angular/core": "12.2.5",
    "@angular/forms": "12.2.5",
    "@angular/material": "12.2.5",
    "@angular/platform-browser": "12.2.5",
    "@angular/platform-browser-dynamic": "12.2.5",
    "@angular/router": "12.2.5", ...

"devDependencies": {
    "@angular-devkit/build-angular": "12.2.5",
    "@angular-eslint/eslint-plugin": "12.3.1",
    "@angular-eslint/eslint-plugin-template": "12.3.1",
    "@angular-eslint/template-parser": "12.3.1",
    "@angular/cli": "12.2.5",
    "@angular/compiler-cli": "12.2.5",
    "@angular/language-service": "12.2.5",
    "@nrwl/cli": "12.9.0",
    "@nrwl/cypress": "12.9.0",
    "@nrwl/eslint-plugin-nx": "12.9.0",
    "@nrwl/jest": "12.9.0",
    "@nrwl/nest": "12.9.0",
    "@nrwl/node": "12.9.0",
    "@nrwl/tao": "12.9.0",
    "@nrwl/workspace": "12.9.0", ...

**Comment by leosvelperez** [comment]
Thanks for reporting this!

I wasn't able to reproduce it. Could you put together a minimal repo where this issue can be reproduced?

**Comment by olsonjj** [comment]
I've been unable to replicate this in a test repo, and re-did the migration in another branch without issues.  This branch had been Nx 12.6 originally, then when to 12.8, and then migrated to 12.9.   Chalk it up to user error.
