### ISSUE TITLE
migrating a project to nx doesn't migrate the e2e tsconfig correctly

### ISSUE THREAD

**Issue by gkamperis** [nrwl/nx#698]
Using Nx v6.2.0 (but pretty sure it happened with 6.1.0 as well)

ng new myapp
npm run lint
(this works fine)

ng add @nrwl/schematics
npm run lint
(now breaks)

the extends path in myapp\apps\myapp-e2e\tsconfig.e2e.json
is wrong, it was not moved with the migration (the main app's tsconfig was)
{
  "extends": "../tsconfig.json",
...
  }
}

workaround:
"extends": "../../tsconfig.json",

**Comment by FrozenPandaz** [comment]
This was fixed by https://github.com/nrwl/nx/pull/758
