### ISSUE TITLE
Small mistake in the docs : Creating Custom Executors

### ISSUE THREAD

**Issue by khalilou88** [nrwl/nx#6987]
Hello

There is a small mistake in the doc in this page :
https://nx.dev/latest/angular/executors/creating-custom-builders 

>  const success = !!stderr;
>   return { success };

To calculate success we need only one exclamation mark.

The executor in this case failed even it should be returning true.

I created a PR to fix this docs here :
https://github.com/nrwl/nx/pull/6990

**Comment by vsavkin** [comment]
Fixed! Thank you
