### ISSUE TITLE
Include custom folder/files as part of nx cache

### ISSUE THREAD

**Issue by ntziolis** [nrwl/nx#6997]
In certain situations it should be possible to include arbitrary files as part of cached command output. 
One example would be when executing tests in a CI environment when Test results should be published.
Currently the test result / report files are not part of the cache output.

## Motivation
- extend use cases of nx cache

## Suggested Implementation. 
- Ability to specify additional glob pattern / patterns of files that are included in the cache output

Related issues (last comment):
https://github.com/nrwl/nx/issues/837

**Comment by vsavkin** [comment]
Hi there.

You can already any files into the cached output. The only thing you need to do is to to add them to the outputs property of the executor. See the outputs section here: https://nx.dev/latest/react/core-concepts/configuration

Hope it helps! Going to close this issue. If you have any other questions, reach out.

**Comment by miluoshi** [comment]
I would just add that event outputs section indeed is mentioned in the docs, does poor(no) job explaining its' purpose.
> The outputs property lists the folders the executor creates files in. The property is optional. If not provided, Nx assumes it is dist/libs/mylib.

It does not say anything about Nx cache.
