### ISSUE TITLE
Creating component for library doesn't work

### ISSUE THREAD

**Issue by wolfhoundjesse** [nrwl/nx#70]
I don't have this issue: #68 
Even though my output is as expected, when I then do as it says in the video:
`ng g component myComponent -a=myLib --export`
I receive the errors:
`Error: Cannot read property 'length' of null
Cannot read property 'length' of null
`

**Comment by vsavkin** [comment]
Could you provide a repro?

**Comment by Yonet** [comment]
ng generate lib nx-d3 --ngmodule
ng generate component bar —app=nx-d3

With the latest version of nx, there is not error produced but the component is created inside the first app instead of library.

**Comment by vsavkin** [comment]
@Yonet your issue is due to this: https://github.com/nrwl/nx/wiki/FAQ

@wolfhoundjesse if you have the same problem with Nx 0.2.0, please reopen the issue.

Closing this issue.
