### ISSUE TITLE
Images not showing on documentation guide

### ISSUE THREAD

**Issue by amanintech** [nrwl/nx#7005]
## Current Behavior

Documentation pages are not loading images which is making it hard to read them

## Expected Behavior

images should show
## Steps to Reproduce

visit any documentation URL
example - https://nx.dev/latest/react/guides/deploy-nextjs-to-vercel#deploying-nextjs-applications-to-vercel

**Comment by vsavkin** [comment]
Fixed it here: https://github.com/nrwl/nx/commit/402969a948471eae29eef6a23cf96e2efa37f2b4 Thank you!
