### ISSUE TITLE
Dep graph does not work correctly if application has root as "" in angular.json

### ISSUE THREAD

**Issue by gmfun** [nrwl/nx#7008]
## Current Behavior

nx dep-graph is wrong in default angular project structure

## Steps to Reproduce

- create angular cli app starting with letter z, where app has `root: ""` in angular.json
- migrate it to nx preserving the layout
- generate a library starting with letter a, the projects in angular.json will get sorted alphabetically and app will move down

## Cause of the issue
Issue is in https://github.com/nrwl/nx/blob/ac218c6f46a03591b4088dc092a93d0535d685cc/packages/workspace/src/core/file-graph/project-file-map.ts#L26

If `p.root` is `""`, it will always pass, and all the files will pass this logic

## Solution
```
if (f.file.startsWith(p.root || p.sourceRoot)) {
    fileMap[projectName].push(f);
    seen.add(f.file);
}
```

**Comment by gmfun** [comment]
If the team does not have bandwidth and the solution seems fine, I can put up an MR for this

**Comment by vsavkin** [comment]
@gmfun thank you for submitting the issue. The proposed solution is good. if you send a PR, I'll merge it :) 

Thank you again!
