### ISSUE TITLE
Inconsistent path in tsconfig.base.json after moving a library

### ISSUE THREAD

**Issue by david-bulte** [nrwl/nx#7009]
## Current Behavior
When moving a library, e.g. _shared/tech/whaterver_ to _shared/deprecated/whatever_, the newly generated path is _@org/shared-deprecated-whatever_ in the tsconfig.base.json.

## Expected Behavior
This is not consistent with the normal path format a library has after creation. We would expect it to be _@org/shared/deprecated/whatever_

## Steps to Reproduce

Just move a library with the NX move command:
```
nx g move --project shared-tech-whatever shared/deprecated/whatever
```
### Environment

  Node : 14.15.3
  OS   : win32 x64
  npm  : 6.14.5

  nx : 12.9.0
  @nrwl/angular : 12.9.0
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by mandarini** [comment]
Closing this, since it seems to be on purpose!

**Comment by ajwootto** [comment]
@mandarini I know this was a while ago but if you remember, can you explain why it's "on purpose"?
