### ISSUE TITLE
Try to run custom schematics on nx projects, got Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by chgc** [nrwl/nx#703]
I am trying to run custom schematics on nx projects, but I get an error message "Cannot read property 'toString' of null'. The schematics can work fine on regular angular cli project. 
It seems it didn't trigger schematics action.

![image](https://user-images.githubusercontent.com/4550568/44001684-f65af888-9e68-11e8-8039-8517c94a770f.png)

**environment information**
![image](https://user-images.githubusercontent.com/4550568/44001676-cf450bc6-9e68-11e8-826d-3628324a6853.png)

 "@nrwl/nx": "6.2.0",

**Comment by FrozenPandaz** [comment]
Is this what you are trying to use? https://www.npmjs.com/package/ngcli-wallaby

The correct command seems to be `ng add ngcli-wallaby`.

**Comment by chgc** [comment]
after I digged around, I found this error was causing by schematics itself. This issue should close for now. I will update ngcli-wallaby schematics version to the newest and try again.
