### ISSUE TITLE
Angular - Nest.js

### ISSUE THREAD

**Issue by WCN-llc** [nrwl/nx#7035]
## Current Behavior
1. I launch - nx serve
2. I get the error: "styles.css - Error: (0 , _identifier.getUndoPath) is not a function"

## Expected Behavior
There is no mistake

## Steps to Reproduce
1. npx create-nx-workspace@latest
2.  Setting project parameters:
√ What to create in the new workspace · angular-nest
√ Application name                    · vl
√ Default stylesheet format           · scss
√ Use Nx Cloud? (It's free and doesn't require registration.) · No

### Environment
  Node : 14.17.0
  OS   : win32 x64
  npm  : 6.14.13

  nx : 12.9.0
  @nrwl/angular : 12.9.0
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : 12.9.0
  @nrwl/next : Not Found
  @nrwl/node : 12.9.0
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by linbudu599** [comment]
Duplicate of #6612

**Comment by nartc** [comment]
Can you please provide a reproduce sample?
