### ISSUE TITLE
The automatic nx format fails with "The command line is too long" as Workspace is growing

### ISSUE THREAD

**Issue by renepape** [nrwl/nx#704]
When generating new items in a nx workspace, automatic formatting takes place.
When I reached 10 projects with state etc. in the solution, the formatting part fails with:
```
nx@0.0.0 format C:\Udvikling\Plass.Id\nx
> nx format:write "--untracked" "--quiet"

The command line is too long.
```
And the underlying call to node prettier is indeed huge.

Maybe, the formatting should be divided into a prettier call for each project instead of consolidating all files across the workspace.

**Comment by johnRambo2k14** [comment]
I'm getting the same issue, is this a known issue amongst the team?

**Comment by FrozenPandaz** [comment]
This should have been fixed with https://github.com/nrwl/nx/pull/727. Can you please retry with the latest version and close if it is resolved?

**Comment by renepape** [comment]
Thanks FrozenPandaz, I updated to 6.3, added a test-lib, and it formatted 300+ files without any problems. Thanks everyone for the great work.
