### ISSUE TITLE
Facing issues while using nativebase io framework in NX workspace :

### ISSUE THREAD

**Issue by avanti-cs** [nrwl/nx#7056]
## Current Behavior
Facing issues while using nativebase io framework in NX workspace :

Issue- Module parse failed: Unexpected token
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See
https://webpack.js.org/concepts#loaders

I have also tried installing nativebase framework on workspace level as well as project level however facing the same issue. 

## Steps to Reproduce

Adding just one single nativebase component in nx workspace react project throwing an Error

        <NativeBaseProvider>
      <Box>Hello world</Box>
        </NativeBaseProvider>
### Environment
Version stack -

    "babel-preset-es2015": "^6.24.1",
    "core-js": "^3.6.5",
    "expo": "39.0.2",
    "expo-status-bar": "1.0.2",
    "native-base": "^3.1.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",

**Comment by mitch-keenan** [comment]
@avanti-cs Did you ever figure this out? Seeing the same issue and trying to debug.

**Comment by AgentEnder** [comment]
@mitch-keenan @avanti-cs 

Can either of you run `nx report` and paste the output here? If this can be reproduced in a small repo it could help us understand whats causing the breakage too.

**Comment by marienvo** [comment]
@AgentEnder I'm having a similar issue, `nx report`:

```
  Node : 16.13.0
  OS   : linux x64
  npm  : 8.1.0

  nx : 13.1.2
  @nrwl/angular : Not Found
  @nrwl/cli : 13.1.2
  @nrwl/cypress : 13.1.2
  @nrwl/devkit : 13.1.2
  @nrwl/eslint-plugin-nx : 13.1.2
  @nrwl/express : 13.1.2
  @nrwl/jest : 13.1.2
  @nrwl/linter : 13.1.2
  @nrwl/nest : Not Found
  @nrwl/next : 13.1.2
  @nrwl/node : 13.1.2
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 13.1.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.2
  @nrwl/web : 13.1.2
  @nrwl/workspace : 13.1.2
  @nrwl/storybook : 13.1.2
  @nrwl/gatsby : Not Found
  typescript : 4.4.3
```
