### ISSUE TITLE
NX ERROR Nx failed to install dependencies - no logs

### ISSUE THREAD

**Issue by ChazUK** [nrwl/nx#7057]
Hi, I'm trying to create a new blank workspace but having issues with the create-nx-workspace script, also I must add that I'm using a private repository which currently has create-nx-workspace@12.9.0.

```
$ npx create-nx-workspace@latest
npx: installed 48 in 6.582s
✔ Workspace name (e.g., org name)     · Test
✔ What to create in the new workspace · empty
✔ Use Nx Cloud? (It's free and doesn't require registration.) · No

>  NX  Nx is creating your workspace.

  To make sure the command works reliably in all environments, and that the preset is applied correctly,
  Nx will run "npm install" several times. Please wait.

✖ Installing dependencies with npm

>  NX   ERROR  Nx failed to install dependencies

  Exit code: 1
  Log file: /var/folders/_h/_2cbzjc533ddnkrvc4rzhls1_189jg/T/tmp-28544-FJvoErpxB3PZ/error.log
  ```
  
  Looking into the error.log file shows a completely blank file. Is there a way to get a verbose view or find out what packages nx is trying to install?

**Comment by ChazUK** [comment]
I've noticed that there is a `--silent` flag on the [package manager install line](https://github.com/nrwl/nx/blob/70ff791b62963e7b0eb25bb8ee1dee243d369033/packages/create-nx-workspace/bin/create-nx-workspace.ts#L455) 

Is it possible to remove this if the user running the script adds `--verbose`?

**Comment by dimsky** [comment]
the same error.

**Comment by aflores** [comment]
On a Mac, this worked for me:

npm uninstall @nrwl/schematics; npm install -g @nrwl/schematics npm cache clean --force;npx create-nx-workspace@latest
