### ISSUE TITLE
Cannot generate Angular App on Windows. npx ng g @nrwl/angular:app fails.

### ISSUE THREAD

**Issue by shahggeek** [nrwl/nx#7070]
##Current Behavior
When running this command from a Windows machine:
npx ng g @nrwl/angular:app tutorials --prefix="tuts" --routing --style="scss"
an error of **"Cannot read property 'replace' of null"** is seen. 

##Expected Behavior
Able to properly generate a new app on a Windows machine. 12.9.0 version was expected to fix  this issue for Windows devices.

##Steps to Reproduce
Run this on a Windows machine -
npx ng g @nrwl/angular:app tutorials --prefix="tuts" --routing --style="scss"

##Similar Issue Raised earlier:
https://github.com/nrwl/nx/issues/6795 

### Environment
$ npx nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.16.1
  OS   : win32 x64
  npm  : 6.14.15

  nx : 12.9.0
  @nrwl/angular : 12.9.0
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : 12.9.0
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : 12.9.0
  @nrwl/next : Not Found
  @nrwl/node : 12.9.0
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by rajibsaha06** [comment]
Same issue after upgrading NX to 12.6.2

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Could please share a repo with a workspace where I can run the generation and see it fail? I haven't been able to reproduce the issue.
