### ISSUE TITLE
@nrwl/nx/react-typescript eslint plugin fails to use rules requiring TypeScript compiler to be available

### ISSUE THREAD

**Issue by jbmusso** [nrwl/nx#7077]
## Current Behavior
The `yarn lint` command fails for a Next/TypeScript application after migrating a workspace from 12.3.5 to 12.9.0 using the `nx migrate` command and following the official documentation. ESLint rules requiring TypeScript no longer works, and eslint command early exits with an error:

```
Error: You have attempted to use a lint rule which requires the full TypeScript type-checker to be available, but you do not have `parserOptions.project` configured to point at your project tsconfig.json files in the relevant TypeScript file "overrides" block of your project ESLint config `apps/sample/.eslintrc.json`
```

The following changes were made to `apps/sample/eslintrc.json` by the `nx migrate` command

```diff
-  "extends": ["plugin:@nrwl/nx/react", "../../.eslintrc.json"],
+  "extends": [
+    "plugin:@nrwl/nx/react-typescript",
+    "../../.eslintrc.json",
+    "next",
+    "next/core-web-vitals"
+  ],
```

## Expected Behavior

I would expect `yarn lint` command to not complain about using eslint rules which requires the TypeScript compiler.

## Steps to Reproduce

Migrate to 12.9.0 and run `yarn lint` on a Next/TypeScript application:

```
yarn run v1.22.5
$ nx workspace-lint && nx lint

> nx run sample:lint 

Linting "sample"...

Error: You have attempted to use a lint rule which requires the full TypeScript type-checker to be available, but you do not have `parserOptions.project` configured to point at your project tsconfig.json files in the relevant TypeScript file "overrides" block of your project ESLint config `apps/sample/.eslintrc.json`

Please see https://nx.dev/guides/eslint for full guidance on how to resolve this issue.
```

Switching back to `"plugin:@nrwl/nx/react"` and discarding the `"next"` and `"next/core-web-vitals"` makes eslint able to use rules requiring TypeScript again, though `next@11` now warns about missing eslint plugins.

Could it be that `import { appRootPath } from '@nrwl/tao/src/utils/app-root';` fails to properly resolve the application root path?
See: https://github.com/nrwl/nx/blob/8ab463e38693064063c2296e3ea8a4fc1f75e2da/packages/eslint-plugin-nx/src/configs/typescript.ts#L20
`console.log(appRootPath)` shows the root of the workspace rather than the root of the `sample` application - I was expected to see `apps/sample`, but maybe I'm misunderstanding.

Also, I tried  using `eslintrc.js` with `tsconfigRootDir: __dirname,` without success. See: https://github.com/typescript-eslint/typescript-eslint/issues/251

### Environment

```
yarn run v1.22.5
$ nx report

>  NX  Report complete - copy this into the issue template

  Node : 16.4.2
  OS   : darwin x64
  yarn : 1.22.5
  
  nx : 12.9.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : 12.9.0
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.9.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

✨  Done in 0.82s.
```

Thanks for your time, I apologize if I'm missing the obvious.

**Comment by meeroslav** [comment]
Hi @jbmusso, just a gentle ping. Have managed to resolve the issue with the help of our guide?
