### ISSUE TITLE
Expose task information to runtime cache inputs

### ISSUE THREAD

**Issue by raymondhoagland** [nrwl/nx#7081]
## Description

Scripts executed as runtime cache inputs should be provided information about the project/target that is being evaluated, e..g through environment variables.  

## Motivation

Some inputs may only be relevant to specific targets, e.g. the execution environment impacts the result of the build and should bust the cache but should not require linting again.

Similarly there may be specific projects that depend on the execution environment and configuration but are otherwise not impacted.

## Suggested Implementation

Set environment variables for relevant information (e.g. project/target/configuration) [before executing the runtime inputs](https://github.com/nrwl/nx/blob/677e481729ac054c2908acaef1082c7930d4feff/packages/workspace/src/core/hasher/hasher.ts#L79), at least project/target/configuration.

**Comment by vsavkin** [comment]
Hi there,

The project name is already set (NX_TASK_TARGET_PROJECT is the env variable), but we don't set the target.
