### ISSUE TITLE
@nrwl/react new app with React Router has source map warning

### ISSUE THREAD

**Issue by jamesmcglinn** [nrwl/nx#7082]
## Current Behavior

A new @nrwl/react app with routing shows a source map warning in the browser console.

## Expected Behavior

No warnings shown with the dev server when a new react app's created.

## Steps to Reproduce

```
npm install --save-dev @nrwl/react
nx g @nrwl/react:app my-app # Would you like to add React Router to this application – Yes
nx run my-app:serve
```

### Failure Logs

Opening the app in the browser the console warns:
```
DevTools failed to load source map: Could not load content for http://localhost:4200/react-router.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

### Environment

  Node : 16.4.1
  OS   : darwin x64
  npm  : 7.21.0

  nx : 12.9.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : 12.3.11
  @nrwl/react : 12.9.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by learningnewthings** [comment]
@vsavkin 
@jamesmcglinn 

Same issue, please fix. Many thanks.

Meanwhile here's an work around - in workspace.json set "webpackConfig": "/pathTo/webpack.config.js"

webpack.config.js
```
const nrwlConfig = require('@nrwl/react/plugins/webpack.js');
module.exports = (config) => {
  nrwlConfig(config);
  return {
    ...config,
    devtool: 'source-map',
  };
};
```


or 
webpack.config.js
```
const nrwlConfig = require('@nrwl/react/plugins/webpack.js');
module.exports = (config) => {
  nrwlConfig(config);
  return {
    ...config,
     module: {
       rules: [
         ...config.module.rules,
         {
           test: /\.js$/,
           enforce: 'pre',
           use: ['source-map-loader'],
         },
       ],
     },
  };
};

```

**Comment by xiejay97** [comment]
> @vsavkin @jamesmcglinn
> 
> Same issue, please fix. Many thanks.
> 
> Meanwhile here's an work around - in workspace.json set "webpackConfig": "/pathTo/webpack.config.js"
> 
> webpack.config.js
> 
> ```
> const nrwlConfig = require('@nrwl/react/plugins/webpack.js');
> module.exports = (config) => {
>   nrwlConfig(config);
>   return {
>     ...config,
>     devtool: 'source-map',
>   };
> };
> ```
> 
> or webpack.config.js
> 
> ```
> const nrwlConfig = require('@nrwl/react/plugins/webpack.js');
> module.exports = (config) => {
>   nrwlConfig(config);
>   return {
>     ...config,
>      module: {
>        rules: [
>          ...config.module.rules,
>          {
>            test: /\.js$/,
>            enforce: 'pre',
>            use: ['source-map-loader'],
>          },
>        ],
>      },
>   };
> };
> ```

good!
