### ISSUE TITLE
React + CSS Modules + tailwind - scss does not include tailwind styles

### ISSUE THREAD

**Issue by danr-za** [nrwl/nx#7095]
## Current Behavior
When using css modules which include tailwind code in a `scss` file, tailwind styles are not processed.
e.g.
```
Button.module.scss
Button.tsx

// Button.module.scss
.button {
  @apply bg-blue-600 text-white;
}
```

* The same works when using `css` instead of `scss`.
* The same works when renaming `Button.module.scss` to `Button.scss` (not using CSS Modules)

## Expected Behavior
CSS Modules should have tailwind processing with SASS as well.

## Steps to Reproduce
1. Create a repo with React app
2. Create a React lib
3. Add PostCSS + Tailwind configuration
4. Add a component with css modules (e.g. Button.module.scss + Button.tsx)
5. Use tailwind styles in `Button.module.scss` , e.g. `@apply bg-blue-100`
6. Run storybook / use it in your app / build the lib and see the result

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment
```sh
  Node : 14.16.1
  OS   : darwin x64
  yarn : 2.4.2
  
  nx : 12.9.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.9.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

```

**Comment by puku0x** [comment]
It seems `*.module.css` (not `.module.scss`) files can handle `@apply` because `postcss-loader` is used for them.
https://github.com/nrwl/nx/blob/fec1c39be0177133face9b641c9f36b1da5f0b6e/packages/web/src/utils/web.config.ts#L192-L237

Here is a repositry to reproduce the problem
https://github.com/puku0x/workspace-7095

**Comment by danr-za** [comment]
Created a PR for it
