### ISSUE TITLE
"apps/" being added to tags when tagging with app name

### ISSUE THREAD

**Issue by asherbig** [nrwl/nx#7097]
## Current Behavior
when I'm using the app generator, I pass in tags like `--tags=test` but what happens is I get a tag array that looks like `[apps/test]` in my nx.json. This only happens if I use my app name as a tag. Why is this happening, and is there a way to stop it?
It is finding any substring, so `--tags=blahtestblah`  is turning into `[blahapps/testblah]` in my nx.json

## Expected Behavior
The tags I pass into the `--tags` field should not be modified in any way. Tags should appear in the nx.json.

## Steps to Reproduce
`ng generate @nrwl/angular:application --name=test --tags=test`

### Environment
>  NX  Report complete - copy this into the issue template

  Node : 14.17.6
  OS   : darwin x64
  yarn : 1.22.4
  
  nx : Not Found
  @nrwl/angular : 12.7.2
  @nrwl/cli : 12.7.2
  @nrwl/cypress : 12.7.2
  @nrwl/devkit : 12.7.2
  @nrwl/eslint-plugin-nx : 12.7.2
  @nrwl/express : Not Found
  @nrwl/jest : 12.7.2
  @nrwl/linter : 12.7.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.7.2
  @nrwl/nx-cloud : 12.3.10
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.7.2
  @nrwl/web : Not Found
  @nrwl/workspace : 12.7.2
  @nrwl/storybook : 12.7.2
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by linbudu599** [comment]
This is indeed a bug and seems appear only in `@nrwl/angular` generator and really confuse me, in [angular.generator.application.update-config-file](https://github.com/nrwl/nx/blob/master/packages/angular/src/generators/application/lib/update-config-files.ts#L23), the `updateJson` method received correct tag value like `test`, but the generated result is `APP_DIR/test`, this happens not only in the situation that using same tag name with app name, but also in which tag name starts with app name, like tag `test123` and app `test`.
What's even stranger is that only this only appears in `@nrwl/angular`, `@nrwl/react` or `@nrwl/web` with similar logics works correctly.
