### ISSUE TITLE
Build fails with custom webpack.config.ts on @nrwl/node: execute. 

### ISSUE THREAD

**Issue by babette-landmesser** [nrwl/nx#7108]
Hi,

I'm having issues with building a node app with a custom webpack.config.js. In this case, I decided for a custom webpack configuration because I need multiple possible entry points to this package. What am I doing wrong? Is this just not possible so far or am I missing some other package / command / configuration / ... ?

## Current Behavior
When running `nx run <app-name>:build` with a custom webpack.config.js referred to in workspace.json, the build fails with the error below: `require(...) is not a function`. When removing the webpack reference in workspace.json it works perfectly fine. 
 
## Expected Behavior
I expect the node environment of nx to be working with custom webpack configurations.

## Steps to Reproduce
1. setup @nrwl/node monorepository and add an app
2. add a custom webpack.config.js to the app and link it in `workspace.json`
3. add some code to the app 
4. let nx build the app. 

### Failure Logs
```
$ nx run <appname>:build --verbose                                                                         

> nx run <appname>:build --verbose

>  NX  Using webpack 5. Reason: detected version 5 in node_modules/webpack/package.json

require(...) is not a function
TypeError: require(...) is not a function
    at [...]project-folder/node_modules/@nrwl/node/src/executors/build/build.impl.js:39:35
    at Array.reduce (<anonymous>)
    at buildExecutor_1 ([...]project-folder/node_modules/@nrwl/node/src/executors/build/build.impl.js:38:46)
    at buildExecutor_1.next (<anonymous>)
    at resume ([...]project-folder/node_modules/tslib/tslib.js:225:48)
    at [...]project-folder/node_modules/tslib/tslib.js:224:125
    at new Promise (<anonymous>)
    at Object.i.<computed> [as next] ([...]project-folder/node_modules/tslib/tslib.js:224:67)
    at [...]project-folder/node_modules/@nrwl/tao/src/commands/run.js:92:35
    at Generator.next (<anonymous>)

———————————————————————————————————————————————

>  NX   ERROR  Running target "asset-creation:build" failed
```

**Comment by linbudu599** [comment]
Can we take a look at reproduce repo please? I need more information to offer assistance, like how you configure workspace.json, the content of your custom webpack config file...

**Comment by davidpodhola** [comment]
Hi,

this was happening to me too, the correct 'webpack.config.js' structure is to export a function e.g.

```
module.exports = (x) => {
  const result =
    {
      ...x,
      entry: {
        main: './packages/catalog-api/src/main.ts',
        azure: './packages/catalog-api/main/index.ts',
      },
    };
  result.output.filename = '[name].js';

  return result;
}
```

Hope that helps-
