### ISSUE TITLE
Jest tests failing while using svg's as ReactComponent

### ISSUE THREAD

**Issue by ruslan-byondxr** [nrwl/nx#7109]
Tests are failing while testing simple react component that  includes svg file as ReactComponent

## Current Behavior

Im getting the following error:
```src/app/header.tsx:9:45 - error TS2307: Cannot find module '../logo.svg' or its corresponding type declarations.```

## Expected Behavior

Should work as expected

## Steps to Reproduce

header.tsx
```
import React from 'react';
import { ReactComponent as Logo } from './logo.svg';

const Header = () => <Logo title="Logo" />;

export default Header;
```

header.spec.tsx
```
import { render, screen } from '@testing-library/react'
import Header from './header'

describe('My first plugin', () => { 
  it('should render successfully', async () => {
    const { baseElement } = render(<Header />)  
        expect(baseElement).toBeTruthy()
    }
}
```

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

```
src/app/header.tsx:9:45 - error TS2307: Cannot find module './logo.svg' or its corresponding type declarations.
```

### Environment

 Node : 14.17.4
  OS   : darwin x64
  yarn : 1.22.11
  
  nx : 12.9.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : 12.9.0
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.9.0
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.9.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by puku0x** [comment]
Oh really? I could not reproduce the problem.
https://github.com/puku0x/workspace-7109
![image](https://user-images.githubusercontent.com/2607019/134536515-0c0d37f7-19fa-4b7c-b392-f585df2dd836.png)

There might be something you missed.

**Comment by casiimir** [comment]
Could be useful put inside the `jest.config.js`:

`transform: {
  '^.+\\.jsx?$': 'babel-jest',
  '^.+\\.svg$': 'jest-svg-transformer',
},`
