### ISSUE TITLE
Trace imports between two targets

### ISSUE THREAD

**Issue by artaommahe** [nrwl/nx#7124]
## Description

nrwl/nx provides a `dep-graph` tool to view all relations between apps/libs and also there is a eslint rule `enforce-module-boudaries` that can display circular imports paths.
Would be cool to have a command that prints all imports paths between two targets (e.x. app and lib, lib and other lib) like `enforce-module-boudaries` does.

## Motivation

Changing some lib code can affect apps that should not be dependant on this lib. Currently we have to add degugger/console.warn statement to index file of such lib and trace imports path manually in runtime to understand why this lib is imported by this app. It's hard to use `dep-graph` when you have hundreds of libs with a lot of connections to understand all imports paths between two targets.

## Suggested Implementation

CLI command like `ng trace-imports some-app some-lib`

## Alternate Implementations

Tool for `dep-graph`  to display only imports paths between some (mb multiple) targets (but don't just highlight cause dep-graph's output for all repo is too slow and messy)

**Comment by artaommahe** [comment]
Nope

**Comment by artaommahe** [comment]
🙏

**Comment by philipjfulcher** [comment]
I don't have time to implement this as part of the command line right now, but this information is available in the graph visualization. You can trace between two projects and then use the tooltip on the edges between nodes to see the files that are a part of the dependency. 

If you (or anyone else watching this thread) is willing to implement the command line implementation, I can help get you started.
