### ISSUE TITLE
Command line arguments not passed to dependent tasks

### ISSUE THREAD

**Issue by JakeGinnivan** [nrwl/nx#7136]
## Description

When using targetDependencies to get run-many tasks to take order into account by running dependencies first any additional arguments are left off.

For example

```
    "targetDependencies": {
        ...,
        "up": [
            {
                "target": "up",
                "projects": "dependencies"
            }
        ]
    },
```

`pnpx nx run-many --all --target=up --env=stg --yes`

When this runs, some executors get `--env=stg --yes` passed to them, others do not.

## Motivation

Run infrastructure as code deployments for affected projects

## Suggested Implementation

https://github.com/nrwl/nx/pull/7055

## Alternate Implementations

I think the main variation is if we limit it to the same target type or not

**Comment by JakeGinnivan** [comment]
@FrozenPandaz any chance you could take a look at this? Otherwise can re-open the PR I closed to discuss there?

**Comment by Bielik20** [comment]
I do experience the same problem, not only with `run-many` command. I have described here a similar example: https://github.com/nrwl/nx/issues/7514#issuecomment-968647412
