### ISSUE TITLE
Pass in `--e2e-tags` when generating application

### ISSUE THREAD

**Issue by asherbig** [nrwl/nx#7140]
## Description
When I generate an application, I want to be able to specify the tags that the e2e app gets.

## Motivation
I would like all of my projects to be properly tagged after the generator runs. I don't want people to have to manually change anything. We can override this ourselves, but if it's possible to fix it at the source, then that would be best.

## Suggested Implementation
Add a schema option for `--e2e-tags` on all of the application generators. Those tags get applied to the e2e project that gets created with the application.

## Alternate Implementations
Only add it on select generators.

**Comment by linbudu599** [comment]
`tags` should be used to prevent unexpected import statements between apps/libs, see [monorepo-tags](https://nx.dev/l/a/structure/monorepo-tags#tags) for more details, so supporting this feature for the e2e application does not seem very necessary.

**Comment by asherbig** [comment]
That makes sense. I was going off of their example project here https://github.com/nrwl/nx-workshop/blob/master/docs/lab12/LAB.md where they go over tagging, and end up tagging the e2e project https://github.com/nrwl/nx-workshop/blob/master/docs/lab12/SOLUTION.md.

Should the example project be changed so the e2e project doesn't get tagged?
