### ISSUE TITLE
Storybook run fail on workspace basing on workspace.json instead of angular.json due to lack of some config entries

### ISSUE THREAD

**Issue by orkisz** [nrwl/nx#7159]
## Current Behavior
Workspace has only workspace.json file (no angular.json)
```
> nx run swo-ng-checkbox-wrapper:storybook
info => Loading presets
info => Loading 1 config file in "/Users/krzysztoforkiszswo/dev/orkisz/ng-react-mix-nx/libs/swo-ng/checkbox-wrapper/.storybook"
info => Loading 8 other files in "/Users/krzysztoforkiszswo/dev/orkisz/ng-react-mix-nx/libs/swo-ng/checkbox-wrapper/.storybook"
info => Adding stories defined in "/Users/krzysztoforkiszswo/dev/orkisz/ng-react-mix-nx/libs/swo-ng/checkbox-wrapper/.storybook/main.js"
info => Found custom tsconfig.json
info => Using implicit CSS loaders
info => Loading angular-cli config
info => Using angular project "swo-ng-progress-bar:build" for configuring Storybook
ERR! => Could not get angular cli webpack config
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined


          Broken build, fix the error above.
          You may need to refresh the browser.


———————————————————————————————————————————————

>  NX   ERROR  Running target "swo-ng-checkbox-wrapper:storybook" failed

  Failed tasks:

  - swo-ng-checkbox-wrapper:storybook

  Hint: run the command with --verbose for more details.
```
Take a look that it also tries to invoke default project build, not those I'm interested in

## Expected Behavior
Storybook runs normally

## Steps to Reproduce
In this commit I added some necessary props to workspace.json:
https://github.com/orkisz/ng-react-mix-nx/tree/b5d28bcde242041267debdede95c9698034d5c91
just checking out previous commit will show the error.
I assume Storybook integration needs info that exists in angular.json (tsConfig and angularBrowserTarget) but because of some convention is not necessary for NX

### Environment

  Node : 14.17.6
  OS   : darwin x64
  yarn : 1.22.11

  nx : 12.9.0
  @nrwl/angular : 12.9.0
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.9.0
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.9.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by maxisam** [comment]
I just ran into this one right now. It happens when I use projectBuildConfig setting.

**Comment by maxisam** [comment]
https://github.com/nrwl/nx/issues/5657#issuecomment-897625521

This one might help.

**Comment by orkisz** [comment]
I know that (nice debugging session...) but that's not all, `angularBrowserTarget` is also needed or it will use default project as a config for all projects (which sometimes is ok and sometimes not). IMHO those sections should be there added by schematics.

**Comment by mandarini** [comment]
Hi there @maxisam and @orkisz . Can you please give this another go with the latest version of Nx (Nx 13), and let me know if the issue persists?

**Comment by junekpavel** [comment]
Hey @juristr and others, I'm having exactly same issue.

After some investigations, I found out, the issue isn't probably related to `workspace.json` file name, but rather to the buildable libraries.

I prepared the repo with minimal reproduction https://github.com/junekpavel/nx-sb-demo, including all commands I run to generate it. Notice the `--buildable` flags when generating libraries - if you run generate libraries without them, the storybook is working.

**Comment by juristr** [comment]
@junekpavel thanks, will have a look 👍

**Comment by juristr** [comment]
@admin-happ yeah that's how the Storybook integration (not the Nx specific one) works. Storybook picks the Angular app configuration to get information about the build setup.
We added a `projectBuildConfig` property to the Storybook configuration which you can use to point to a different project than the "default" one: https://nx.dev/l/a/storybook/build#projectbuildconfig

**Comment by asilvadesigns** [comment]
I'm currently having this issue, anyone have a fix?

**Comment by junekpavel** [comment]
Still having the issue. Although the workaround that worked for me - update both project targets, build and storybook. 

1. Add the `tsConfig` to the `build` target default options (seems like the defaultConfiguration is not loaded):
```jsonc
"build": {
  "options": {
    "tsConfig": "packages/second-lib/tsconfig.lib.prod.json",
    // ...
  }
}
```

2. Add the `projectBuildConfig` into the `storybook` and `build-storybook` targets:
```jsonc
"storybook": {
  "options": {
    "projectBuildConfig": "second-library",
    // ...
  }
}
```

**Comment by mandarini** [comment]
Could be potentially solved by https://github.com/nrwl/nx/pull/8494
