### ISSUE TITLE
Cache doesn't re-create .jest-test-results.json when running tests

### ISSUE THREAD

**Issue by trumbitta** [nrwl/nx#7167]
## Current Behavior

When using cloud cache (not sure about local), if the output from `nx test` (be it `affected` or per-project) comes from the cache the `.jest-test-results.json` file doesn't get written even though the output logs a message saying it's been written as usual.

This breaks Storybook when it's configured to import the file and show stats about it in component stories.

## Expected Behavior

The `.jest-test-results.json` file gets written when requested, even if the output comes from the cache.

## Steps to Reproduce

- Have a repo with cloud cache
- Have `"json": true` among the options for the `test` target of a project
- Run tests for the first time: the `.jest-test-results.json` file gets created
- Run tests for the second time, hitting the cache: the `.jest-test-results.json` gets deleted and never re-created

### Environment

```
>  NX  Report complete - copy this into the issue template

  Node : 12.18.3
  OS   : darwin x64
  npm  : 6.14.6
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.8.0
  @nrwl/cypress : 12.8.0
  @nrwl/devkit : 12.8.0
  @nrwl/eslint-plugin-nx : 12.8.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.8.0
  @nrwl/linter : 12.8.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.8.0
  @nrwl/nx-cloud : 12.3.10
  @nrwl/react : 12.8.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.8.0
  @nrwl/web : 12.8.0
  @nrwl/workspace : 12.8.0
  @nrwl/storybook : 12.8.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by trumbitta** [comment]
Up

**Comment by barbados-clemens** [comment]
is this still an issue on the latest versions of nx?

**Comment by azerafati** [comment]
I am having this issue as well, text coverage is created even if you hit cache but test reports are not. In my case I'm using [jest-junit](https://github.com/jest-community/jest-junit)

**Comment by barbados-clemens** [comment]
have you tried adding the coverage report to the outputs of the test target?
