### ISSUE TITLE
ESM support for jest

### ISSUE THREAD

**Issue by mattlewis92** [nrwl/nx#7170]
## Description
Angular package format v13 seems like it [won't be shipping libraries as commonjs](https://github.com/ng-packagr/ng-packagr/commit/cc5914659973a3c9e6dc04e2c038457923afae82) anymore and will only include esm bundles. Right now if you try and use an esm node_module inside of a jest unit test it doesn't work. If there is already discussion about this elsewhere, or there is already a plan for how to deal with this, feel free to close this issue 😄 

## Motivation

It won't be possible to run unit tests with angular 13 otherwise.

## Suggested Implementation

Use the esm support provided by [jest](https://jestjs.io/docs/ecmascript-modules) and [jest-preset-angular](https://thymikee.github.io/jest-preset-angular/docs/guides/esm-support).

## Alternate Implementations

Use a custom jest transformer to downlevel the esm in node_modules into commonjs. Having to always run `nx test` with `NODE_OPTIONS=--experimental-vm-modules` isn't an ideal solution. Or maybe it's possible to persuade the angular team to continue shipping a commonjs bundle to npm until the esm story inside of jest is no longer experimental.

**Comment by mattlewis92** [comment]
I messed about with transpiling node_modules esm -> commonjs today and I think this may work as a decent solution and can easily be auto migrated via nx:

1. `npm i -D jest-esm-transformer`
2. For each libraries `jest.config.js` (maybe angular libs only? But more and more packages are starting to ship ESM only so maybe it makes sense for all libs) set these options:
```
  transform: {
    'node_modules\\/.+\\.js$': 'jest-esm-transformer',
    '^.+\\.(ts|js|html)$': 'jest-preset-angular', // probably tweak this regexp to exclude anything in node_modules
  },
  transformIgnorePatterns: [] // by default jest ignores anything in node_modules: https://jestjs.io/docs/configuration#transformignorepatterns-arraystring
```
3. update the [nx resolver](https://github.com/nrwl/nx/blob/master/packages/jest/plugins/resolver.ts) to support the `module` field according to the guide [here](https://jestjs.io/docs/configuration#resolver-string) (it looks like APF v13 will only provide the `module` and `exports` fields, neither of which are supported out the box by jest)

The only downside of this approach is that there will be a slight perf hit to transpiling node_modules, but I think jest's built in caching should mitigate _most_ of that, my initial tests on our app there didn't seem to be much of an observable perf change with this change.

**Comment by FacePalmDev** [comment]
> 'node_modules\\/.+\\.js$': 'jest-esm-transformer'

Sorry but instruction step 3 is not well defined. Could someone please add some examples here?

**Comment by Nightbr** [comment]
We have the same issue here with React18 and some libs that now support only ESM module (such as [ReactDnD](https://github.com/react-dnd/react-dnd)). 

I tried to transform `'node_modules\\/.+\\.js$': 'jest-esm-transformer',` But seems not sufficient.

Could be great to have a working solution the time Jest support ESM modules. I will dig this up and update  this post if I found a solution.

**Comment by barbados-clemens** [comment]
@FacePalmDev that change is already in the [nx resolver today](https://github.com/nrwl/nx/blob/master/packages/jest/plugins/resolver.ts?rgh-link-date=2021-10-01T12:17:11Z#L62)


@Nightbr you more than likely just need to set up your [transformIgnorePatterns to handle the react-dnd package](https://github.com/barbados-clemens/testing-validation-bench/blob/main/apps/react-app-one/jest.config.ts#L10).
