### ISSUE TITLE
Prod build of react lib uses the wrong runtime

### ISSUE THREAD

**Issue by ZNackasha** [nrwl/nx#7174]
## Current Behavior
currently when i build a react lib with the --prod it still uses `react/jsx-dev-runtime`. this causes alot of issues when it comes time to publish. 

## Expected Behavior
the build should use the `react/jsx-runtime` for production builds

## Steps to Reproduce
1. create a @nrwl/react:lib
2. build it with --prod flag
3. look at the *.esm.js file generated in the dist dir
4. notice that it still import from  `react/jsx-dev-runtime`

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by puku0x** [comment]
`nx g @nrwl/react:lib` does not generate a library with `production` configuration. How did you make your library?

Here is my procedure.

```
npx create-nx-workspace workspace-7174 --preset=react --app-name=web --style=styled-components --no-nx-cloud
cd workspace-7174
npx nx g @nrwl/react:lib --name=components --buildable --publishable --importPath=@workspace/components
npx nx run-many --target=build --all --prod
```

- `dist/libs/components/components.esm.js`
```tsx
import { jsx } from 'react/jsx-runtime';
import styled from 'styled-components';

function _taggedTemplateLiteralLoose(strings, raw) {
  if (!raw) {
    raw = strings.slice(0);
  }

  strings.raw = raw;
  return strings;
}

var _templateObject;
var StyledComponents = styled.div(_templateObject || (_templateObject = _taggedTemplateLiteralLoose(["\n  color: pink;\n"])));
function Components(props) {
  return jsx(StyledComponents, {
    children: jsx("h1", {
      children: "Welcome to Components!"
    }, void 0)
  }, void 0);
}

export { Components };

```

It seems it works well on my machine. Of course, you can provide a reproduction.
