### ISSUE TITLE
Updating past Nx 12.5.2 causes depGraph bug and silently fails building of an Angular app

### ISSUE THREAD

**Issue by benpsnyder** [nrwl/nx#7176]
## Current Behavior

We use gulp scripts to automate our build toolchain, where nx CLI commands are invoked. We've been using Nx for a while on many projects, since about v6/v7. This one particular code repo we have for a large client is on Nx 12.5.2 and we can't upgrade further because of a bug.

To test this, we use an isolated command:
`
nx run portals-connect:build --configuration=staging --skip-nx-cache --verbose
`
The results:
![image](https://user-images.githubusercontent.com/707567/135362449-0b2473c9-5ffc-4f23-9052-59ab114fbc92.png)

You will see that it does not begin by compiling **portals-connect**

However if I adjust nx.json by removing this...
![image](https://user-images.githubusercontent.com/707567/135362528-9f313515-5cab-46a9-b973-0637c950496f.png)

The same command begins building **portals-connect**
![image](https://user-images.githubusercontent.com/707567/135362605-9204916e-cee6-413b-bf9b-8d4a243ad7fc.png)

I suspect this is related to https://github.com/nrwl/nx/pull/6245

### Environment

 ```
 Node : 16.9.1
  OS   : darwin x64
  yarn : 1.22.11

  nx : 12.5.2
  @nrwl/angular : 12.9.0
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : 12.9.0
  @nrwl/next : Not Found
  @nrwl/node : 12.9.0
  @nrwl/nx-cloud : 12.3.13
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by vsavkin** [comment]
Hi @benpsnyder 

Thank you for submitting the issue!

This isn't a bug. Often when a buildable project depends on another buildable project (A->B), the B project has to be built cause the A project will use the results of compiling B. If B has already been built before, it will be restored from the cache. 

If this isn't the behavior you want in your workspace, removing the targetDependencies section in nx.json is totally fine. 

I'm going to close this issue because the workaround is clear, and the targetDependencies is intended to be there.

Thank you!

**Comment by benpsnyder** [comment]
Dear @vsavkin - big fan of your work. I attended Nx Conf and have a team of 40+ doing Nx on many projects. You guys rock and we are looking forward to committing company resources to help out the Nx ecosystem.

The issue is that, even when **portals-connect** or its dependent libraries have changes, the app still gets skipped and doesn't compile. I have to delete node_modules/.cache/nx if I revert from 12.9.0 to 12.5.2 after testing things.

For now I will remove **targetDependencies** but I think it is best we keep it. Perhaps I have a one-off, workspace specific bug.

Any recommendation on what debugging information I can post for you? If not ... I don't want to burn cycles of your time. thx
