### ISSUE TITLE
How to create a styles.scss in libs?

### ISSUE THREAD

**Issue by dgroh** [nrwl/nx#718]
When I add a **lib** I don't get a `styles.scss`. Where can I include a `styles.scss` in my lib so I can write global styles in it as I'm used to do in apps? For instance I have global sass variables which I want to import there. I don't find anything about it in the docs.

**Comment by jdk339** [comment]
I don't think there is any good way of doing this. Also, this is arguably against good design as you should not have design code in your library. Each app should have its own custom styling.

**Comment by dgroh** [comment]
If I create a library which is an `accordion` and this `accordion` is made of 2 components (`accordion-group` and `accordion-item`) and both components share of same sass variables or have common styles, you mean I should duplicate the styles / sass variables?

**Comment by xmlking** [comment]
xplat generate nx project that has convention to keep scss module at libs level. 
https://nstudio.io/xplat/

**Comment by dgroh** [comment]
this is interesting, but not really planing on refactoring my entire `ngrx` based project to use `xplat`. this would be over engineering just to add a `styles.scss`

**Comment by dgroh** [comment]
Closing as this is being discussed here: https://github.com/nrwl/nx/issues/54
