### ISSUE TITLE
Certain storybook addon doesn't work

### ISSUE THREAD

**Issue by maxisam** [nrwl/nx#7186]
## Update

It seems like only certain addons don't work. I tested with `Accessibility` addon and it works fine.

## Current Behavior
If I have the following config

```js
module.exports = {
   stories: [],
   addons: ['@storybook/addon-console', '@storybook/addon-essentials']
   // uncomment the property below if you want to apply some webpack config globally
   // webpackFinal: async (config, { configType }) => {
   //   // Make whatever fine-grained changes you need that should apply to all storybook configs

   //   // Return the altered config
   //   return config;
   // },
};

```
It throws error like 

'Accessing non-existent addons channel
## Expected Behavior
it should work

### Environment

  Node : 14.17.1
  OS   : win32 x64
  yarn : 1.22.5

  nx : 12.9.0
  @nrwl/angular : 12.9.0
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : 12.3.12
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by juristr** [comment]
Hey @maxisam. This looks like an issue with the actual `@storybook/addon-console` itself. Please refer to their issue tracker: https://github.com/storybookjs/storybook-addon-console/issues/41
