### ISSUE TITLE
implicitDependencies field triggers additional builds

### ISSUE THREAD

**Issue by anton-gorbikov** [nrwl/nx#7191]
## Current Behavior
After migration from nx 11 to nx 12 we've noticed that `nx build project-with-implicit-deps` triggers the build for all implicit dependencies. It was not the case in nx 11.

## Expected Behavior
According to the documentation, this behavior should only apply to `dependsOn` configuration property. `implicitDependencies` field is only used to calculate the dependency graph and affected graph.

## Steps to Reproduce
1. Checkout `nx-examples` repo
2. `yarn nx generate app implicit-deps`
3. Open `project.json` for newly generated project and add:
 ```
   "implicitDependencies": [
     "cart",
     "products"
   ],
 ```
4. Run `yarn nx build  implicit-deps`

### Environment
```
>  NX  Report complete - copy this into the issue template

  Node : 14.16.0
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : 12.9.0-beta.3
  @nrwl/angular : 12.9.0-beta.3
  @nrwl/cli : 12.9.0-beta.3
  @nrwl/cypress : 12.9.0-beta.3
  @nrwl/devkit : 12.9.0-beta.3
  @nrwl/eslint-plugin-nx : 12.9.0-beta.3
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0-beta.3
  @nrwl/linter : 12.9.0-beta.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : 12.3.10
  @nrwl/react : 12.9.0-beta.3
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0-beta.3
  @nrwl/web : 12.9.0-beta.3
  @nrwl/workspace : 12.9.0-beta.3
  @nrwl/storybook : 12.9.0-beta.3
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by FrozenPandaz** [comment]
Sorry for the issues, There was a migration that added this to the `nx.json`:

https://github.com/nrwl/nx-examples/blob/master/nx.json#L24

If you don't want this behavior, you can remove that bit.
