### ISSUE TITLE
support --stats-json for nextjs apps

### ISSUE THREAD

**Issue by stopyransky** [nrwl/nx#7208]
I am using nx + next app and i try to get stats.json to analyze the bundle (installed webpack-bundle analyzer and npm-run-all).
I have followed this guide : https://www.xtivia.com/blog/webpack-bundle-analyzer-with-nx-and-react/

i use following scripts in package.json (simplified)

```
    "test-app:build:prod": "nx build test-app --prod --memoryLimit=8192",
    "test-app:build:prod:stats": "nx build test-app --prod --skip-nx-cache  --stats-json",
    "test-app:build:dev:stats": "nx build test-app --skip-nx-cache  --stats-json",
    "analyze:prod:stats": "run-s \"test-app:build:prod:stats\" \"webpack-bundle-analyzer\"",
    "analyze:dev:stats": "run-s \"test-app:build:dev:stats\" \"webpack-bundle-analyzer\"",
    "webpack-bundle-analyzer": "webpack-bundle-analyzer dist/apps/test-app/stats.json"
```

For simplicity I also tried only running 
`nx build test-app --prod --stats-json` and
`nx build test-app --prod --skip-nx-cache --stats-json`

 but it also fails to generate stats.json in both cases

## Current Behavior
the build succeeds, files are generated in /dist/apps/test-app/ but the stats.json file is not generated 

## Expected Behavior
the build succeeds, files are generated and stats.json is present

## Steps to Reproduce
run  "npm run analyze:prod:stats" scripts as listed above

### Failure Logs
```
> test-nx@0.0.0 webpack-bundle-analyzer /Users/.../test-nx
> webpack-bundle-analyzer dist/apps/test-app/stats.json

Couldn't read webpack bundle stats from "/Users/.../test-nx/dist/apps/test-app/stats.json":
Error: ENOENT: no such file or directory, open '/Users/.../test-nx/dist/apps/test-app/stats.json'
```
### Environment

using globally installed nx@12.9.0 with nrwl/cli@12.9.0 

  Node : 14.17.6
  OS   : darwin x64
  npm  : 6.14.15
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : 12.9.0
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.9.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by kirjai** [comment]
hey @stopyransky , thanks for opening the issue!

at the moment, `@nrwl/next` plugin doesn't have the `--stats-json` option that is referenced in that article, since the article is written based on the `@nrwl/react` plugin.

we might add it in the future, i think it's a good idea. but in the meantime, you should be able to use the [`@next/bundle-analyzer` package](https://www.npmjs.com/package/@next/bundle-analyzer) package

**Comment by AgentEnder** [comment]
I'm going to close this feature out, as we have recently discussed the behavior in https://github.com/nrwl/nx/pull/10081 and decided against adding it. From a dev standpoint, `@next/bundle-analyzer` can be added and used by consumers of Nx.
