### ISSUE TITLE
@nrwl/nest:library options not working

### ISSUE THREAD

**Issue by svalup** [nrwl/nx#7214]
## Current Behavior
The options for the library generator command for nest seem to be failing, even though the same command works fine for the @nrwl/react collection.
The command I use is:
```nx g @nrwl/nest:library test --setParserOptionsProject```
And the output:
```'setParserOptionsProject' is not found in schema```
The same thing happens for the 'standaloneConfig' option as well.

## Expected Behavior
The library should be generated with the parserOptions project set up in the eslintrc.json file in the library directory.

## Steps to Reproduce
```nx g @nrwl/nest:library test --setParserOptionsProject```
Run the command in a nx workspace.

### Failure Logs
'setParserOptionsProject' is not found in schema
Unfortunately there is no other more verbose output

### Environment

>   Node : 14.8.0
>   OS   : darwin x64
>   npm  : 6.14.7
>   
>   nx : Not Found
>   @nrwl/angular : Not Found
>   @nrwl/cli : 12.7.1
>   @nrwl/cypress : 12.7.1
>   @nrwl/devkit : 12.7.1
>   @nrwl/eslint-plugin-nx : 12.7.1
>   @nrwl/express : Not Found
>   @nrwl/jest : 12.7.1
>   @nrwl/linter : 12.7.1
>   @nrwl/nest : 12.7.1
>   @nrwl/next : Not Found
>   @nrwl/node : 12.7.1
>   @nrwl/nx-cloud : Not Found
>   @nrwl/react : 12.7.1
>   @nrwl/schematics : Not Found
>   @nrwl/tao : 12.7.1
>   @nrwl/web : 12.7.1
>   @nrwl/workspace : 12.7.1
>   @nrwl/storybook : 12.7.1
>   @nrwl/gatsby : Not Found
>   typescript : 4.3.5

**Comment by nartc** [comment]
This has been fixed with https://github.com/nrwl/nx/pull/7103 and released in `12.10.0`
