### ISSUE TITLE
Error "Cannot find tsconfig.base.json" when running migration `update-invalid-import-paths` (v12.9.0)

### ISSUE THREAD

**Issue by wshager** [nrwl/nx#7223]
## Current Behavior
When running `nx migrate  --run-migrations=migrations.json` there is an error while running migration `update-invalid-import-paths`: `Cannot find tsconfig.base.json`.

This occurred after upgrading from 12.8.0 to 12.9.0. Note that there's a `tsconfig.json` in the root that was migrated from `tsconfig.base.json` by Nx previously AFAICT.

## Expected Behavior
Upgrade to 12.9.0.

## Steps to Reproduce
```
npx nx migrate latest
npm install
npx nx migrate --run-migrations=migrations.json
```

### Failure Logs

>  NX  Running migrations from 'migrations.json'

Running migration update-invalid-import-paths
Cannot find tsconfig.base.json
Command failed: /var/folders/6b/jjddfddn7rddfcq5mw04qz8c0000gn/T/tmp-13499-ux2vOCnkzWHO/node_modules/.bin/tao migrate --run-migrations=migrations.json

### Environment
  Node : 12.21.0
  OS   : darwin x64
  npm  : 6.14.11
  
  nx : Not Found
  @nrwl/angular : 12.9.0
  @nrwl/cli : 12.8.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.7.2
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : 12.9.0
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.9.0
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.7.2
  @nrwl/web : Not Found
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by FrozenPandaz** [comment]
> Note that there's a tsconfig.json in the root that was migrated from tsconfig.base.json by Nx previously AFAICT.

This might have been done by an Angular CLI migration but Nx does prefer the `tsconfig.base.json`. However, having a `tsconfig.json` instead of a `tsconfig.base.json` should also be valid. This is indeed an issue with the migration.

**Comment by Coly010** [comment]
This has been fixed, however, it has not yet been released. When we release a new version of Nx containing this fix, I'll update here :)

**Comment by ringodotnl** [comment]
@Coly010  any eta, is there some PR for it ? Cheers.

**Comment by ringodotnl** [comment]
@Coly010 thank you for your quick answer.

We are just migrating to 12 what would be the best solution copy tsconfig.json to tsconfig.base.json or remove this migration  step ?

(I also noticed that nx format:write all  gave a error at the end that tsconfig.base.json it not found. When making a new project tsconfig.json seems to be the default, I assume tsconfig.base.json is migrated out ?)


Cheers,
Ringo.

**Comment by moniuch** [comment]
> > Note that there's a tsconfig.json in the root that was migrated from tsconfig.base.json by Nx previously AFAICT.
> 
> This might have been done by an Angular CLI migration but Nx does prefer the `tsconfig.base.json`. However, having a `tsconfig.json` instead of a `tsconfig.base.json` should also be valid. This is indeed an issue with the migration.

I renamed `tsconfig.base.json` to `tsconfig.json` - which immediately fixed custom paths issue, and all was fine until I ran `nx g lib my-lib` - then schematics complained about missing `tsconfig.base.json`
