### ISSUE TITLE
Failing migration: update-jest-preset-angular-8-4-0

### ISSUE THREAD

**Issue by LukasMachetanz** [nrwl/nx#7241]
Hi everyone!

Running the generated migrations (`nx migrate latest`) like `nx migrate --run-migrations` I get an error for the `update-jest-preset-angular-8-4-0` migration as it cannot find `jest.config.js`. This makes sense as our *nx-workspace* has some libraries which are using `karma` and some which are using `jest`. I guess the libraries using `karma` cause the error. I am wondering how this problem could be solved. I guess it is not possible to run a migration for a specific library, right? In the best case libraries using `karma` should just be ignored. Any help appreciated. Thanks.

**Comment by FrozenPandaz** [comment]
The projects using `karma` are ignored by that migration.

I can't really debug what is going on without more information.

I suspect one of the projects configured to use `@nrwl/jest:jest` as the executor has a `jestConfig` property pointing to a file which does not exist.

Is it possible for you to post your `workspace.json`?

**Comment by ldco2016** [comment]
@FrozenPandaz @LukasMachetanz 

I am getting this issue as well.

I ran `nx migrate @nrwl/workspace@14.6.0` which is a downgrade because I have been having so much problems getting Nx 14.6.4 to work with Angular 14.

Then when I ran `nx migrate --run-migrations` and I got the following errors:

```bash
>  NX   Failed to run update-jest-preset-angular-8-4-0 from @nrwl/jest. This workspace is NOT up to date!


 >  NX   Cannot find module '/Users/ldco2016/Projects/cyclone/apps/corny-server/jest.config.js'
```

The file does exist:

```javascript
/* eslint-disable */
export default {
  displayName: 'boreas-ui',
  preset: '../../jest.preset.js',
  setupFilesAfterEnv: ['<rootDir>/src/test-setup.ts'],
  globals: {
    'ts-jest': {
      stringifyContentPathRegex: '\\.(html|svg)$',

      tsconfig: '<rootDir>/tsconfig.spec.json'
    }
  },
  coverageDirectory: '../../coverage/apps/boreas-ui',
  snapshotSerializers: ['jest-preset-angular/build/serializers/no-ng-attributes', 'jest-preset-angular/build/serializers/ng-snapshot', 'jest-preset-angular/build/serializers/html-comment'],
  transform: { '^.+\\.(ts|js|html)$': 'jest-preset-angular' }
};
```
