### ISSUE TITLE
fileReplacements isn't working for nodejs apps when app is served

### ISSUE THREAD

**Issue by Yohandah** [nrwl/nx#7246]
## Current Behavior
Configuring `fileReplacements` for a NestJS app works when I do `nx build myApp --configuration=myConf`, but when I do `nx serve myApp --configuration=myApp` it doesn't work and throws

> Watchpack Error (initial scan): Error: ENOTDIR: not a directory, scandir 'C:\Users\x\Documents\dev\x\x\apps\x\src\environments\environment.ts'

## Expected Behavior
I would expect it to work as well and replace the files ?

## Steps to Reproduce

* Create a NestJS app
* Configure a new configuration like this
```
"myApp": {
  ...
  "architect": {
    "build": {
      "configurations": {
        "myConf": {
          "fileReplacements": [ { "replace": "apps/myApp/src/environments/environment.ts", "with": "apps/myApp/src/environments/environment.myConf.ts" ]
      }
    },
    "serve": {
      "configurations": {
        "myConf": {
          "buildTarget": "myApp:build:myConf"
        }
      }
    }
  }
}
```
* `nx build myApp --configuration=myConf` works !
* `nx serve myApp --configuration=myConf` doesn't work !

### Environment

```
  Node : 14.17.0
  OS   : win32 ia32
  npm  : 6.14.13

  nx : 12.9.0
  @nrwl/angular : 12.9.0
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : 12.9.0
  @nrwl/next : Not Found
  @nrwl/node : 12.9.0
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

```

**Comment by nartc** [comment]
Can you please provide a sample repo that reproduces this issue? I have tried on 12.9.0 and fileReplacements works correctly

**Comment by nartc** [comment]
@Yohandah I see. I never had to do it like that. Have you tried splitting up into different target instead, like:

```
"multi": {},
"multi-x": {},
"multi-y": {}
```

It seems weird that you'd need to run both environments at the same time.

**Comment by Yohandah** [comment]
Yeah it's quite complex it's an app that will run on multiple servers and one server can access the data of all the instances. So when we dev in local we need to launch several instances; I wanted to make one target to launch the full environment but it's fine I'll figure something out. Thanks for trying.
