### ISSUE TITLE
Bug: Build adds peerDependecies from test files to package output.

### ISSUE THREAD

**Issue by shaharkazaz** [nrwl/nx#7257]
## Current Behavior
I have an Angular lib that I added a peer dependency of `@angular/core` and `rxjs`, when I build the package I see that 2 peerDependecies were added by nx during build time.
The issue is that these dependencies are not part of the lib and are used in the `test-steup`

Pre-build `package.json`:
```
  "peerDependencies": {
    "@angular/core": ">=12.0.0",
    "rxjs": ">=6.0.0"
  },
```

Post-build `package.json`:
```
  "peerDependencies": {
    "@angular/core": ">=12.0.0",
    "rxjs": ">=6.0.0",
    "zone.js": "0.11.4",
    "@angular/platform-browser-dynamic": "12.2.5"
  },
```

`test-steup.ts` is the only place importing `zone.js` and `@angular/platform-browser-dynamic`.

## Expected Behavior
Dependencies from test-related files shouldn't be part of the peer dependencies.
Also, is there a way to disable adding peer dependencies during build time?

## Steps to Reproduce
You can see this behavior in [Transloco repo](https://github.com/ngneat/transloco), just run `nx run transloco:build` and see the `package.json` file in the dist folder.

### Environment
  Node : 12.20.0
  OS   : darwin x64
  npm  : 7.24.1
  
  nx : 12.9.0
  @nrwl/angular : 12.9.0
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Please note this automatic generation can be disabled using the [updateBuildableProjectDepsInPackageJson](https://nx.dev/l/a/angular/package#updatebuildableprojectdepsinpackagejson) option of the `@nrwl/angular:package` executor. You can set `updateBuildableProjectDepsInPackageJson": false` to be in control of the generated `package.json` dependencies.

**Comment by leosvelperez** [comment]
I'm closing this.

The default generation of dependencies in `package.json` files works most of the time. For the scenarios where it doesn't work correctly, the current recommendation is to disable it by setting `updateBuildableProjectDepsInPackageJson": false` in the options for the `@nrwl/angular:package` executor and manually set the dependencies for your `package.json`.

**Comment by shaharkazaz** [comment]
@leosvelperez seems kind of odd to me that the fix is to disable the feature and manually resolve the dependencies instead of fixing the bug in this feature 🤷

**Comment by wallace41290** [comment]
Would be nice if we could tell it to ignore dependencies found in test files, mock files, storybook files etc...

**Comment by daiscog** [comment]
@leosvelperez please can you consider reopening this issue?

Having to disable this option and manually manage peer dependencies for a subset of libs in a monorepo is really not a good solution at all.

We've now got to remember which libs we need to manually manage the peer deps for, which is very easy to forget.  This is really not a scalable solution.
