### ISSUE TITLE
Support to test the workspace schematic generators

### ISSUE THREAD

**Issue by sonikasharma1403** [nrwl/nx#7271]
## Current Behavior

Setting up Unit Tests for workspace generators is difficult

## Expected Behavior

Workspace generators are setup with unit tests.

**Comment by sonikasharma1403** [comment]
Any update on this?

**Comment by cjones26** [comment]
I am also curious as to whether there is any update on this.  It seems like there isn't any documentation on how to test custom schematics.

**Comment by AgentEnder** [comment]
Support for testing local generators will be included in #9116, by generating a full plugin with jest + e2e setup included.

**Comment by cjones26** [comment]
@AgentEnder, that's great to hear.  Thanks for the update!
