### ISSUE TITLE
[Angular] postinstall ngcc does not work

### ISSUE THREAD

**Issue by muuvmuuv** [nrwl/nx#7317]
## Current Behavior

Running the `postinstall` script from the default project created with `npx create-nx-workspace` does nothing. I tested this in a `ng new` project and there it works. I am using pnpm as my package manager.

## Expected Behavior

Running ngcc like in a basic Angular project create with `ng new`

## Steps to Reproduce

```
npx create-nx-workspace
```

### Failure Logs

No failures

**Comment by muuvmuuv** [comment]
Ok, it seems this is an issue with ngcc itself: https://github.com/angular/angular/issues/38023

**Comment by AgentEnder** [comment]
The next feature release of Nx (13.2) should include angular 13 support, which eliminates the need for ngcc. I'm going to close this since we are tracking angular 13 support with PR #7161
