### ISSUE TITLE
Adding new component "affects" all libraries

### ISSUE THREAD

**Issue by ed4becky** [nrwl/nx#7320]
## Current Behavior
touching angular.json or nx.json results in nx affected:libs returning ALL libraries
This has the unfortunate side effect: adding a new library "affects" all other libraries, even if it is empty or never used.

## Expected Behavior
adding a new library does not affect other libraries until a component in that library is used.

## Steps to Reproduce
in a workspace where nx affected:libs returns an empty list, add a library and rerun nx affected:libs

  Node : 14.17.5
  OS   : win32 x64
  npm  : 6.14.14

  nx : Not Found
  @nrwl/angular : 11.6.3
  @nrwl/cli : 11.6.3
  @nrwl/cypress : 11.6.3
  @nrwl/devkit : 11.6.3
  @nrwl/eslint-plugin-nx : 11.6.3
  @nrwl/express : Not Found
  @nrwl/jest : 11.6.3
  @nrwl/linter : 11.6.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.6.3
  @nrwl/web : Not Found
  @nrwl/workspace : 11.6.3
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.1.5

**Comment by thutinavaneethreddy** [comment]
What do you have under implcitDependencies in nx.json file?

**Comment by ianldgs** [comment]
I have the same behaviour and in my nx.json:

```json
  "implicitDependencies": {
    "package.json": {
      "dependencies": "*",
      "devDependencies": "*"
    },
    ".eslintrc.json": "*"
  },
```
