### ISSUE TITLE
Display message after Generator `printChanges` output in terminal screen

### ISSUE THREAD

**Issue by ChazUK** [nrwl/nx#7332]
## Description
As discussed in https://github.com/nrwl/nx/discussions/7287 I've been looking for a way to output additional information after a custom generator function has ran.

Currently if I try to console.log at the end of my generator function the log will be placed before the [`printChanges`](https://github.com/nrwl/nx/blob/2f675f7577d8e919704dbbc39e99097c935c9be4/packages/tao/src/commands/generate.ts#L233) output

```
Test log from Generator

UPDATE angular.json
UPDATE nx.json
CREATE apps/test-app/README.md
UPDATE package.json
```

The main issue with this is that some generators can produced and update a lot of files which makes the changes log very long. Anything printed before this has a chance that it won't be seen by the user, thus losing the ability to alert them of additional steps they may need to take.

Creators can then have the power to log any useful information that will definitely be seen by the user.

```
UPDATE angular.json
UPDATE nx.json
CREATE apps/test-app/README.md
UPDATE package.json

Next steps:
* Register domain
* Create SSL Certificate
* Deploy ECS Server
```

## Suggested Implementation
Maybe the generator function could return a function that can be called after the `printChanges` method and before the check for `--dryRun`

**Comment by beeme1mr** [comment]
@ChazUK, this seems to be possible already if you return a callback and perform the logging in there.

```typescript
export default async function (tree: Tree, schema: unknown) {
  // Generate files

  return () => {
    logger.info('🎉 Success 🎉');
  };
}
```

**Comment by AgentEnder** [comment]
I'm going to close this out. The `GeneratorCallback` that is mentioned  by @beeme1mr is meant for things that need to run after the generator completes. Logging that happens after printChanges falls under that category
