### ISSUE TITLE
Workspace file utils throws: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by lukasholzer** [nrwl/nx#7366]
## Current Behavior

When running `nx run mytarget:build --verbose` it fails with 

```
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Object.filesChanged (/.../node_modules/@nrwl/node/node_modules/@nrwl/workspace/src/core/file-utils.js:255:24)
    at Object.createProjectGraph (/.../node_modules/@nrwl/node/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:21:32)
    at buildExecutor (/.../node_modules/@nrwl/node/src/executors/build/build.impl.js:28:39)
    at /.../node_modules/@nrwl/tao/src/commands/run.js:134:23
    at Generator.next (<anonymous>)
    at /.../node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
```

## Expected Behavior
It builds the target

## Steps to Reproduce
Hard to tell issue is located inside 

`node_modules/@nrwl/node/node_modules/@nrwl/workspace/src/core/file-utils.js`

```diff
function filesChanged(a, b) {
+  console.log(a,b)
+   if (a.length !== b?.length)
-   if (a.length !== b.length)
        return true;
```

The optional chaining on `b` does the trick and the `console.log` prints the following output:

```
[
  {
    file: 'package.json',
    hash: '1d085cde9f328c6fbe905dff7068ca8b70efdba0',
    ext: '.json'
  },
  {
    file: 'workspace.json',
    hash: '62266cc6a1d39f52da09833b25d8c6d545e46b19',
    ext: '.json'
  },
  {
    file: 'nx.json',
    hash: 'dcad049f2fa8f67840dc27514732a8992aae73aa',
    ext: '.json'
  },
  {
    file: 'tsconfig.base.json',
    hash: '11253ac5c2b7bc7ccc8003036c9379134582575c',
    ext: '.json'
  }
] undefined
```

### Failure Logs

```
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Object.filesChanged (/.../node_modules/@nrwl/node/node_modules/@nrwl/workspace/src/core/file-utils.js:255:24)
    at Object.createProjectGraph (/.../node_modules/@nrwl/node/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:21:32)
    at buildExecutor (/.../node_modules/@nrwl/node/src/executors/build/build.impl.js:28:39)
    at /.../node_modules/@nrwl/tao/src/commands/run.js:134:23
    at Generator.next (<anonymous>)
    at /.../node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
```

### Environment

```
 nx report

>  NX  Report complete - copy this into the issue template

  Node : 16.7.0
  OS   : darwin x64
  npm  : 7.20.3

  nx : 12.10.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.10.0
  @nrwl/cypress : 12.10.0
  @nrwl/devkit : 12.10.0
  @nrwl/eslint-plugin-nx : 12.10.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.10.0
  @nrwl/linter : 12.10.0
  @nrwl/nest : 12.5.9
  @nrwl/next : Not Found
  @nrwl/node : 12.5.9
  @nrwl/nx-cloud : 12.3.13
  @nrwl/react : 12.10.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.0
  @nrwl/web : 12.10.0
  @nrwl/workspace : 12.10.0
  @nrwl/storybook : 12.10.0
  @nrwl/gatsby : Not Found
  typescript : 4.4.4
```

**Comment by lukasholzer** [comment]
By updating the dependencies this issue was not reproducible anymore! Thx a lot for the quick reply and help 👍

**Comment by edbzn** [comment]
Also ran into this issue, here is report: 

```
Node : 14.16.0
  OS   : linux x64
  yarn : 1.22.5
  
  nx : Not Found
  @nrwl/angular : 11.4.0
  @nrwl/cli : 11.4.0
  @nrwl/cypress : 11.4.0
  @nrwl/devkit : 11.4.0
  @nrwl/eslint-plugin-nx : 11.4.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.4.0
  @nrwl/linter : 11.4.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.4.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.4.0
  @nrwl/web : Not Found
  @nrwl/workspace : 11.4.0
  typescript : 4.1.5
```

**Comment by VesterDe** [comment]
Hope I'm right in bumping this thread. We're getting the same error, it came out of nowhere randomly appearing on a branch that doesn't even touch our frontend, failing our CircleCI builds.

We're running `nx run-many --target=build --all --parallel --maxParallel=4 -c production --output-hashing none --source-map false`.

```
>  NX  Report complete - copy this into the issue template

  Node : 14.18.0
  OS   : linux x64
  npm  : 6.14.15
  
  nx : Not Found
  @nrwl/angular : 11.3.1
  @nrwl/cli : 11.3.1
  @nrwl/cypress : 11.3.1
  @nrwl/devkit : 11.3.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.3.1
  @nrwl/linter : 11.3.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.3.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.3.1
  typescript : 4.0.7
```

The same builds have a test job running that also fails, but that one for a completely different reason (seemingly): 

![image](https://user-images.githubusercontent.com/722505/141513778-db2cbf0c-54aa-4318-abc7-d2af5c397d5d.png)

I'm just mentioning that other failure because it coincides with the above problem 100%.

**Comment by nadavsinai** [comment]
HI, I've debugged this issue which started appearing in our CI in parallel to me starting to work on the platform update which updates NX (still in a private branch) to latest. @vsavkin it appears that NX 13.x corrupts the cache for NX 11.x.
in your cache you have nxdeps.json which should have .rootFIles property as an array (at least by how NX 11.x assumes)
the code in @nrwl/workspace/src/core/project-graph/project-graph.js line 18
states :
`   if (cache && !file_utils_1.filesChanged(rootFiles, cache.rootFiles ) {
...`
and then delegates into filesChanged function (file-utils.js:247) with undefined creating the above stacktrace
my fix would be to change the above line into:
`` if (cache && !file_utils_1.filesChanged(rootFiles, cache.rootFiles || [] ) {
..
I would happily create a PR if you want

**Comment by nadavsinai** [comment]
anyone?

**Comment by hardy925** [comment]
This seems to happen when NodeJS versions change. For me I confirmed the NodeJS version I wanted and ran `npm ci` for some reason, if you still have issues, you can try removing the local git project (commit and push up unsaved work first if needed) and re-clone it and `npm ci`. 

It was a hassle but it worked for me.

**Comment by jsonRUHLS** [comment]
I'm getting `Cannot read property length of undefined` when I run `npx nx run service-api:serve` which runs the `@nrwl/web:dev-server` executor.

I'm able to run build successfully.

`
>  NX  Report complete - copy this into the issue template

  Node : 14.18.1
  OS   : darwin x64
  npm  : 6.14.15
  
  nx : undefined
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.4
  @nrwl/cypress : 13.4.4
  @nrwl/devkit : 13.4.4
  @nrwl/eslint-plugin-nx : 13.4.4
  @nrwl/express : undefined
  @nrwl/jest : 13.4.4
  @nrwl/linter : 13.4.4
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.4.4
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.4
  @nrwl/web : 13.4.4
  @nrwl/workspace : 13.4.4
  @nrwl/storybook : undefined
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
         @nrwl/js: 13.4.4
`

Here are my relevant targets:

`   
 "build": {
      "executor": "@nrwl/node:build",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/apps/service-api",
        "main": "apps/service-api/src/index.ts",
        "tsConfig": "apps/service-api/tsconfig.app.json",
        "buildLibsFromSource": true
      }
    },
    "serve": {
      "executor": "@nrwl/web:dev-server",
      "options": {
        "buildTarget": "service-api:build"      
      }
    }
`

Any suggestions would be appreciated!

**Comment by hardy925** [comment]
@jsonRUHLS Did you move you switch nodeJS versions? or did you move your cache?
