### ISSUE TITLE
(node:8003) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by bjornharvold** [nrwl/nx#7394]
## Current Behavior
My app fails to start

## Expected Behavior
My app should start

## Steps to Reproduce
This is an interesting one. I tried using a new beta of Cloudinary Angular
```
"@cloudinary/angular": "1.0.0-beta.11",
"@cloudinary/url-gen": "^1.1.0",
```

I import CloudinaryModule into one of my libraries. This fails with the error below. However, it works fine if I use the older version of the beta:
```
"@cloudinary/angular": "1.0.0-beta.8",
"@cloudinary/base": "1.0.0-beta.4",
```

I've never gotten Nx to crash just because I upgraded a library.

### Failure Logs
```
(node:8003) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at ProjectHasher.<anonymous> (/Users/crash/git/iko-travel-spa/node_modules/@nrwl/workspace/src/core/hasher/hasher.js:248:41)
    at Generator.next (<anonymous>)
    at /Users/crash/git/iko-travel-spa/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/crash/git/iko-travel-spa/node_modules/tslib/tslib.js:113:16)
    at /Users/crash/git/iko-travel-spa/node_modules/@nrwl/workspace/src/core/hasher/hasher.js:241:79
    at new Promise (<anonymous>)
    at ProjectHasher.<anonymous> (/Users/crash/git/iko-travel-spa/node_modules/@nrwl/workspace/src/core/hasher/hasher.js:241:50)
    at Generator.next (<anonymous>)
    at /Users/crash/git/iko-travel-spa/node_modules/tslib/tslib.js:117:75
(node:8003) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8003) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Environment
```
Node : 12.22.6
  OS   : darwin x64
  yarn : 1.22.15
  
  nx : 12.10.0
  @nrwl/angular : 12.10.0
  @nrwl/cli : 12.10.0
  @nrwl/cypress : 12.10.0
  @nrwl/devkit : 12.10.0
  @nrwl/eslint-plugin-nx : 12.10.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.10.0
  @nrwl/linter : 12.10.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.10.0
  @nrwl/storybook : 12.10.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by bjornharvold** [comment]
Nevermind. This is a non-issue. Just had to rename all the old references to @cloudinary/base -> @cloudinary/url-gen in the codebase. Interesting that Nx would give this strange error and not something like "Library path X doesn't exist".

**Comment by chrisui** [comment]
Just a quick +1 that I have encountered this as well but it's non-trivial in larger refactors to trace exactly where the bad project reference is. Would be great if we had a better error message when a project's data is not loaded (which knows _which_ project name it's looking at). Maybe re-open this issue as a proposal for that?

**Comment by bjornharvold** [comment]
Agreed. It is due to nx daemon. Disable the daemon and you will get the actual error.

**Comment by driver-by** [comment]
I've got here with the same error after removing one npm package.
The `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined` doesn't really help to understand what is the issue :see_no_evil: 

I've figured out that it's some nx cache and tried to find how to remove it.
Advice from [StackOverflow](https://stackoverflow.com/a/66892555/1707258) helped me with that:
```rm -rf ./node_modules/.cache/nx```

**Comment by hcharley** [comment]
Trashing my node_modules on a hunch fixed this issue for me just now. 

Thanks @driver-by for showing me that I could have deleted just that one directory/file.

**Comment by morriq** [comment]
I have this error in CI
I'm not sure `rm -rf ./node_modules/.cache/nx` is the best option here? That way it would not use features of nx to speed up commands?

**Comment by vsavkin** [comment]
Thank you for submitting the issue!

Could someone provide a repro using the latest version of Nx?

Nx Daemon is experimental, so we have merged a lot of fixes into it in the last month. Without a repro, it's hard to know if the issue has been already addressed.

**Comment by derek-pavao** [comment]
I don't have a repo, but I can at least confirm that I encountered this issue on Nx v13.4.6
