### ISSUE TITLE
Unable to install nx

### ISSUE THREAD

**Issue by phsims** [nrwl/nx#74]
yarn gives me the following warnings

```
warning "@nrwl/schematics@0.0.7" has unmet peer dependency "rxjs@>5.4.2".
warning "@nrwl/schematics@0.0.7" has unmet peer dependency "@angular-devkit/schematics@>0.0.18".
warning "@nrwl/schematics@0.0.7" has unmet peer dependency "@schematics/angular@>0.0.30".
[4/4] Building fresh packages...
warning "@nrwl/schematics@0.0.7" has no binaries
```

My workplace has banned connection to git and a few other places so i cant use the install script

**Comment by dreamerNcoder** [comment]
Same is happening for me. Please some one act on it.

**Comment by phsims** [comment]
I have also tried updating an existing app and get this error
`Unable to find app with name or index. Verify the configuration in `.angular-cli.json``

NX sounds like a great idea but so far I have been unable to make it work

**Comment by vsavkin** [comment]
- the warnings should not prevent you from using nx. They should be gone once the CLI 1.5 final is released.
- Unfortunately, you have to be able to access github at the moment. We pull certain dependencies from github instead of npm. If you cannot access github, you won't be able to use it.

**Comment by phsims** [comment]
Will NPM be usable in the future?

**Comment by vsavkin** [comment]
Yup, hopefully very soon. We are waiting on a fix in the CLI to be merged and released. Right now we have to apply the fix ourselves and use a patched version of the CLI, which we pull from github.

**Comment by phsims** [comment]
That's great news, thanks :)
