### ISSUE TITLE
feat(lint): template errors, import statements

### ISSUE THREAD

**Issue by skydever** [nrwl/nx#741]
I was thinking about some useful lint rules, maybe some of them are already there but I missed them somehow:

* **Angular Language Service** related errors within a template should be thrown as lint errors too, to avoid mistakes that pass unit testing and the way how `ng serve` integrated the changes - but will then fail at a real build process. There is a gap that is not covered with linting and serving, maybe just edge cases? Some kind of pre-push check I do (lint + test) passes, but build fails. *Example:* have a default unit test that just checks the creation of the component, all required modules are imported and services are provided for the test - the test passes even if there is an error that the *Angular Language Service* would throw (e.g. *tempateVariable not defined/found* or similar, maybe just the tempate erros). I can catch this kind of mistakes before I build the app if the linter (or test) would catch this.

* **import - relative vs. path mapping** importing from inside of a lib or app should be done using relative paths, if not specified otherwise (related to #738 somehow, check what is configured in `tsconfig.*.js` files), imports out of the lib/app should be done using the paths mechanism. Somehow this also *comes through* without any error, but I want it that to error prior build. Should this already be covered, but I missed that?

**Comment by bcabanes** [comment]
Thank you for the feedback, we have created a new issue #2019 which capture the import linting.
