### ISSUE TITLE
React: Tailwind classes are not purged unless explicit NODE_ENV=production setting.

### ISSUE THREAD

**Issue by sjbuysse** [nrwl/nx#7410]
## Current Behavior
* running `yarn nx run minimal-example:build:production` does not purge the css classes, even though the `process.env.NODE_ENV` evaluates to `production`!
* running `NODE_ENV= production yarn nx run minimal-example:build:production` *does* purge the css classes!
* I have also noticed that when I make a nextjs app (in stead of a react app), the setup below does work, and the behaviour is as expected. 
 
## Expected Behavior
* running `yarn nx run minimal-example:build:production` purges the classes

## Steps to Reproduce
* create a new workspace with `npx create-nx-workspace nx-tailwind-purging`, a react app (I named it `minimal-example`), and choose css for the style. 
* modify `apps/minimal-example/src/app/app.tsx` so that the `App` component looks like this.
```
export function App() {
  return (
    <div className="bg-green-500">hello, I should be green {process.env.NODE_ENV}</div>
  );
}
``` 
* follow the [nx tailwind guide](https://nx.dev/l/r/guides/using-tailwind-css-in-react), with the one exception, that classes in our `minimal-example` app will also not be purged. So my `tailwind.config.js` looks like this:
```
const { createGlobPatternsForDependencies } = require('@nrwl/react/tailwind');

module.exports = {
      purge: [    './apps/minimal-example/src/**/*.{js,jsx,ts,tsx}',
          ...createGlobPatternsForDependencies(__dirname)
],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
```

## Result
* running `yarn nx run minimal-example:build:production` does not purge the css classes, even though the `process.env.NODE_ENV` evaluates to `production`!
* running `NODE_ENV= production yarn nx run minimal-example:build:production` *does* purge the css classes!
* I have also noticed that when I make a nextjs app (in stead of a react app), the setup does work. 

### Environment
macOS Big Sur

Here is a github repo where I have executed above steps: 
https://github.com/sjbuysse/nx-tailwind-purging

**Comment by AdaskoTheBeAsT** [comment]
it can be issue with tailwindcss - inprecise documentation
try add following into tailwind.config.js
`
module.exports = {
...
mode:'jit',
purge: {
    enabled: true,
    content: [
       './src/**/*.html',
       ...
    ],
  },
`

based on 
https://tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode
https://v1.tailwindcss.com/docs/controlling-file-size#enabling-manually
