### ISSUE TITLE
polyfills.ts in generated tsconfig.spec.json with jest flags

### ISSUE THREAD

**Issue by xmlking** [nrwl/nx#744]
I generated new lib module with `--unit-test-runner=jest` flags. 

`ng g lib test123  --publishable=true  --unit-test-runner=jest`

noticed the generated `tsconfig.spec.json` file have `src/polyfills.ts` but i don't see file `polyfills.ts` present in `src`

is this added for future use?
 
```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc/libs/app-confirm",
    "module": "commonjs",
    "types": ["jest", "node"]
  },
  "files": ["src/test-setup.ts", "src/polyfills.ts"],
  "include": ["**/*.spec.ts", "**/*.d.ts"]
}
```

**Comment by FrozenPandaz** [comment]
It should be removed. It's a low effort fix for someone looking to contribute ;)

**Comment by FrozenPandaz** [comment]
This was fixed with https://github.com/nrwl/nx/pull/767
