### ISSUE TITLE
Document how to run next.js in production with NX and customServerPath

### ISSUE THREAD

**Issue by phal0r** [nrwl/nx#7448]
## Description
Currently the `customServerPath` of @nrwl/next server executor is not very well documented. There is one blog post describing its usage. 

This works very well in development mode. Now we want to build the next app and put all necessary files into a Docker image to deploy it to our servers. What is the optimal way to do this? @nrwl/next server executor has a preconfigured production configuration, so `nx run app:serve:production works, but @nrwl dependencies are `devDependencies`, so this won't work with `npm install --production`. How do we best run it in a production environment?

## Motivation
Understanding the best way to run nextjs with nx monorepo in a production docker environment. This is not very clear based on the information, that is publicly accessible.

## Suggested Implementation
Provide a minimalistic way to run nextjs in production mode with a custom server.

**Comment by TheGooner93** [comment]
Is there any movement on this issue ? I have a slightly similar one where even though I am copying all of package.json, yarn.lock, nx.json, tsconfig.base.json, babel.config.json, workspace.json  into the root of the Docker container I get the following error(nextapp is the name of the app to be built)

```
 > [build 2/4] RUN   yarn nx run nextapp:build:production:
#10 1.093 yarn run v1.22.15
#10 1.257 $ /node_modules/.bin/nx run nextapp:build:production
#10 1.706 Could not find @nrwl/tao/index.js module in this workspace. Error: The cwd isn't part of an Nx workspace
#10 1.706     at findWorkspaceRoot (/node_modules/@nrwl/tao/index.js:52:15)
#10 1.706     at Object.<anonymous> (/node_modules/@nrwl/tao/index.js:67:35)
#10 1.706     at Module._compile (/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
#10 1.706     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
#10 1.706     at Module.load (node:internal/modules/cjs/loader:975:32)
#10 1.706     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
#10 1.706     at Module.require (node:internal/modules/cjs/loader:999:19)
#10 1.706     at require (/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
#10 1.706     at loadCli (/node_modules/@nrwl/cli/lib/init-local.js:87:9)
#10 1.706     at Object.initLocal (/node_modules/@nrwl/cli/lib/init-local.js:39:13)
#10 1.743 error Command failed with exit code 1.
#10 1.743 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jcze91** [comment]
Any progress on this subject ?

**Comment by phal0r** [comment]
I guess there never will be an answer to this. We created our own small entrypoint, which uses the custom server to power the docker container.

**Comment by dgbau** [comment]
> I guess there never will be an answer to this. We created our own small entrypoint, which uses the custom server to power the docker container.

how were you able to run the server of the built app in the docker container? I am stuck on this as well..

**Comment by phal0r** [comment]
I added this little bootstrap file

```
import next from 'next'
import customServer from './server'

/**
 * this file uses the nx customServer format and starts the next server without all the boilerplate
 */

// init next in default production mode
const nextApp = next({ dev: false })

// pass the next instance to our custom server
customServer(nextApp)
```

and this target for my next app:
```
"build-docker-entrypoint": {
          "executor": "@nrwl/node:webpack",
          "outputs": ["{options.outputPath}"],
          "options": {
            "outputPath": "dist/apps/docker-entrypoint",
            "main": "apps/next-app/bootstrap.ts",
            "tsConfig": "apps/next-app/tsconfig.docker.json",
            "assets": []
          }
        }
```

run normal build target and this one:
```
- npx nx build next-app
- npx nx run next-app:build-docker-entrypoint
```

Copy all the js into the docker file (including the result of the transpiled entrypoint) and just use node executable to start with the transpiled entrypoint file.

**Comment by damianesteban** [comment]
I can't believe that there is no response on this. In another similar issue the answer was "use Vercel". I'm a fan of Vercel, but this application needs to be deployed on a Kubernetes cluster. And there is no official documentation on how to properly make a docket image even.

**Comment by sebastiandg7** [comment]
Hey there. I just published a blog post series about building NextJS apps with Nx and Docker (with or without using a custom server implementation). Hope it is helpful: https://dev.to/sebastiandg7/nx-nextjs-docker-the-nx-way-creating-the-nextjs-application-1efl
