### ISSUE TITLE
add ability to set global settings  to default to `jest`  

### ISSUE THREAD

**Issue by xmlking** [nrwl/nx#745]
add ability to set global settings  to default to `jest` instead of  `karma` when generating new lib modules.
This way we don't need to add  `--unit-test-runner=jest ` every time we create new module.

**Comment by xmlking** [comment]
is this right ? I just have to add "unitTestRunner": "jest" to angular.json ?

```json
  "schematics": {
    "@nrwl/schematics:component": {
      "prefix": "ngx",
      "styleext": "scss"
    },
    "@nrwl/angular:directive": {
      "prefix": "ngx"
    },
    "@nrwl/schematics:library": {
      "unitTestRunner": "jest"
    }
  }
```

**Comment by FrozenPandaz** [comment]
This is correct :). Thanks for the tip.

**Comment by skorunka** [comment]
@xmlking That actually doesn't work in Angular CLI Console. 
I have got this in `angular.json`:

```
"schematics": {
		"@nrwl/schematics:application": {
			"styleext": "scss",
			"unitTestRunner": "jest"
		},
		"@nrwl/schematics:component": {
			"styleext": "scss",
			"unitTestRunner": "jest"
		},
		"@nrwl/schematics:library": {
			"unitTestRunner": "jest"
		}
	}
```

But Angular Console still defaults to KARMA:

![image](https://user-images.githubusercontent.com/218913/47256368-05e6ab00-d477-11e8-97f8-162d48f02597.png)
