### ISSUE TITLE
Add verbose logging for @nrwl/angular:ng-packagr-lite

### ISSUE THREAD

**Issue by Serg-Mois** [nrwl/nx#7451]
## Description
Add verbose logging for @nrwl/angular:ng-packagr-lite . 

## Motivation
There is no verbose build log, I can't determine why my libs build fails.
I'm trying to configure incremental builds for existing large enterprise following this guide: 
https://nx.dev/l/a/ci/setup-incremental-builds-angular

When calling serve the app - the build is started, I see some 'first dependencies' are built successfully in dest/libs , but then it just showed:

> nx run myLib:build 
[33mStarting up http-server, serving [39m[36mdist/apps/myApp[39m[33m[39m
[33mAvailable on:[39m
  http://localhost:[32m4200[39m
Hit CTRL-C to stop the server

But it just builds 10-20 libs out of 600+.

When I try to build only lib on which everything stuck I see: 

> nx run myLib:build --verbose 

———————————————————————————————————————————————

>  NX   ERROR  Running target "myLib:build" failed

  Failed tasks:
  
  - myLib:build
  
  Hint: run the command with --verbose for more details.

**Comment by Coly010** [comment]
Hi, thank you for the suggestion! 

I've noted down this issue as a possible improvement to our executor. For now, we'll be focusing on other impact areas of the Angular Plugin, however, if we revisit this I'll reopen the issue.

Thanks again for bringing this to our attention!

**Comment by ChazUK** [comment]
:(

**Comment by RoySchiffmannGrip** [comment]
Hey, @Coly010, any chance there are updates in this regard? :(
