### ISSUE TITLE
Should support --testPathIgnorePatterns jest CLI option

### ISSUE THREAD

**Issue by MattGson** [nrwl/nx#7462]
## Description
Should support all jest command line options

eg. `--testPathIgnorePatterns` currently does not work

## Motivation

Jest has these functions for a reason, working without them can be very difficult.

**Comment by FrozenPandaz** [comment]
Yes, we can add the `--testPathIgnorePatterns` option. 

Would you like to open a PR? You can follow https://github.com/nrwl/nx/pull/6729 as a guide.
