### ISSUE TITLE
nx has hard dependency on * version of @nrwl/cli

### ISSUE THREAD

**Issue by astrotim** [nrwl/nx#7464]
## Current Behavior

CI builds are failing with error 

> ERROR  As of Nx 13, project configuration should be moved from nx.json to workspace.json/project.json. Please run "nx format" to fix this.

## Expected Behavior

We have `nx` pinned to exact version `12.7.2`, so we should not see a failure referencing a newer version.

## Steps to Reproduce

The [nx package.json](https://github.com/nrwl/nx/blob/master/packages/nx/package.json#L31) contains

```json
  "dependencies": {
    "@nrwl/cli": "*"
  }
```

which would explain the version mismatch.

### Failure Logs

```
21-Oct-2021 09:47:28 	> nx affected --target=lint --parallel --maxParallel=4
21-Oct-2021 09:47:29 	>  NX   NOTE  Affected criteria defaulted to --base=develop --head=HEAD
21-Oct-2021 09:47:29 	ERROR  As of Nx 13, project configuration should be moved from nx.json to workspace.json/project.json. Please run "nx format" to fix this.
```

### Environment

>  NX  Report complete - copy this into the issue template

  Node : 14.17.4
  OS   : darwin x64
  npm  : 7.20.5

  nx : 12.7.2
  @nrwl/angular : Not Found
  @nrwl/cli : 13.0.1
  @nrwl/cypress : Not Found
  @nrwl/devkit : 13.0.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 13.0.1
  @nrwl/linter : 13.0.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.0.1
  @nrwl/web : Not Found
  @nrwl/workspace : 13.0.1
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.4.2

**Comment by jankaszel** [comment]
i'm facing a similar issue: i intend to run `nx@12`, but since there is a wildcard dependency on `@nrwl/cli`, npm will install the most recent version as sub-dependency of nx when running e.g. `npm i -g nx@12.9`. it took me quite a while to figure this out!

**Comment by AgentEnder** [comment]
@jankaszel All of the CLI commands are ran from the locally installed version of NX within a projects node_modules folder. If you want to run with a specific version, your project should also be that version.

**Comment by ihazar** [comment]
In my case nx displays the following command:

> ERROR  As of Nx 13, project configuration should be moved from nx.json to workspace.json/project.json. Please run "nx format" to fix this.

and suggests running `nx format`. But, after running `nx format` - you cyclically get the same error "As of Nx 13, project configuration should be moved from nx.json to workspace.json/project.json. Please run "nx format" to fix this".

You can solve this by opening `nx.json` file from the workspace root, and removing the `projects` object:

`  "defaultProject": "web-client",
  "projects": { /* remove this object */
    "nativescript-mobile": {
      "tags": []
    }
  }`

then, run `nx format`, and then run your nx command. This solved this issue for me (I was running command `npx nx run nativescript-mobile:ios`). Worked in my case. Hope this helps.

**Comment by ThomasBurleson** [comment]
As @ihazar states: manually removing the `projects` object in `nx.json` and then running `nx format` works.

### Migrate Bug
This appears to be a bug in the `nx migrate latest` process?

**Comment by mruffieux** [comment]
FYI, for angular projects, it won't create a `project/workspace.json`. It moves to `angular.json` Remove `defaultProject` & `projects` properties from `nx.json` and run `nx format`. They will show up there.

**Comment by mtiahrt** [comment]
removing the projects object did the trick for me

**Comment by vjosey** [comment]
Is there a way of running `nx format` without reformatting all of my files? I just want to fix the `project/workspace.json` error.

**Comment by mandarini** [comment]
Should we close this issue, since it has been addressed?
