### ISSUE TITLE
v13 - PostCSS resolving changes broke tailwind used by a lib

### ISSUE THREAD

**Issue by danr-za** [nrwl/nx#7468]
## Current Behavior
* I have an app and a UI lib in my project.
* The UI lib has its own postcss config together with a tailwind one.
* The app consumes this UI library
* Until now, when building the app, the library's postcss config was used and everything worked as expected
* in v13, I am required to update my app's postcss config to include the settings I have in the UI lib

It is expected that a library will hold all its configurations and assets and they will be built with them when consumed by different apps.

**Worked as expected in v12.10**

## Steps to Reproduce
* Create a workspace with v13 with a React app
* Add a lib with Tailwind setup (tailwind+postcss)
* Add `tailwindcss/nesting` to the library's PostCSS config
* Add a component to the library with a CSS file that has nesting, e.g.: 
```css
.button {
  &.status-danger {
     @apply text-red-500;
  }
}
 ``` 
* Consume the component in your app - color is not applied

**Comment by danr-za** [comment]
@jaysoo are there any plans for implementing this? If not I can create a PR

**Comment by danr-za** [comment]
Any news about this?

**Comment by bdebon** [comment]
Oh, I think this is the explanation of my infinite loop of failure today...
@danr-za, I was following your tuto about tailwind nx and next (I was adapting it for my nx react project), but nothing was working correctly... It was like postcss and tailwind in my ui libs were never read.
I think we should let the lib have its own config and eventually fallback to the app's one if the lib does not have it.

I find it strange to be able to include an UI lib that highly relies on tailwind, without letting the lib properly setting up its own tailwind's settings. It means that your UI lib design will depend of the config of tailwind in the app you call it. Which sounds strange to me...

**Comment by bdebon** [comment]
For now for example in my nx react project, with this recent change that does not check the postcss.config and the tailwind.config of my lib, I can not use storybook and tailwind to test the component of my lib. In fact, the classNames of my UI lib are not parsed so tailwind is completely empty and I ends up with a storybook with no styles...

**Comment by RileySeaburg** [comment]
Accoring to this quote from @jaysoo 

> Will be part of Nx 13 in a couple  of weeks.
> 
> _Originally posted by @jaysoo in https://github.com/nrwl/nx/issues/7040#issuecomment-939051273_

This issue should be solved already but it's currently not solved, at least not for NextJS.
I have to say this is the only thin holding us back from being able to use NX in production.
It would be really nice to see a clean implementation of this with a tutorial as well. 😉😊

Has anybody actually got this working properly even with a config file in your lib?

**Comment by bdebon** [comment]
I found a way to make it work with nx 12.5 and tailwind 3.8 and you have to
use the watch mode of tailwind... I spent 2 days experimenting everything
possible to find this specific config.
I can tell you more specifically later if you need. I'm on my phone rn

Le jeu. 13 janv. 2022 à 12:55, Riley Seaburg ***@***.***> a
écrit :

**Comment by DOZBORNE** [comment]
I definitely need this implementation as well. I can't seem to get my libs to identify tailwind. I've tried following the @danr-za s tutorial and it was somewhat helpful, but I haven't been able to crack the code to make it work. So I'm kind of stuck for now :/. https://blog.nrwl.io/setup-next-js-to-use-tailwind-with-nx-849b7e21d8d0

I'm also tried making my own custom webpack config, but wasn't sure how to do that since the way I had tried didn't work. https://github.com/nrwl/nx/issues/3175..

Anyway, hoping this is fixed soon! Also, if anyone knows how to make path aliases for paths within an app inside of an nx workspace, do let me know! I'm talking about for just regular folders in the same directory. I hate the whole relative path chasing, but I couldn't get TS to accept my alias suggestion: /.

**Comment by mohammadTaghiElmi** [comment]
Hi there,

Please provide a temporary solution to this issue if possible, Thank you @jaysoo.

**Comment by DOZBORNE** [comment]
@mohammadTaghiElmi, there are some relative solutions over here: `https://github.com/nrwl/nx/issues/8218#issuecomment-1014898174`! Hope this helps!

**Comment by mohammadTaghiElmi** [comment]
@DOZBORNE,
No, Unfortunately! Thanks for the suggestion.

**Comment by mohammadTaghiElmi** [comment]
@jaysoo Is there no solution?

**Comment by jaysoo** [comment]
I think we need to introduce a `postcssConfig` option, similar to `webpackConfig` where you can either set it to:

* `true` - enables  auto-loading of postcss config files, so each lib can have their own.
* `string` - a path to a single postcss config file that applies to the app + all libs.

And for sharing config, we should follow the same setup as jest, eslint, etc. and created a root `tailwind.preset.js` that can be included into each tailwind config.

**Comment by mohammadTaghiElmi** [comment]
@jaysoo 

Thank you for your response, It will be great.
