### ISSUE TITLE
Get name of all libraries or apps

### ISSUE THREAD

**Issue by splincode** [nrwl/nx#7472]
## Description

Now we have the opportunity:

```bash
$ nx affected:libs --plain
core taiga-schematics addon-tablebars addon-commerce addon-charts addon-mobile addon-doc addon-editor addon-table kit cdk i18n icons testing
```

And we can do this:

```bash
$ nx affected --exclude=$(nx affected:apps --plain) # run only libraries
```

But I don't see `--exclude` for `run-many` command.

Please, add API for get list `apps` or `libs`

```
$ nx info:apps 
demo

$ nx info:libs
core taiga-schematics addon-tablebars addon-commerce addon-charts addon-mobile addon-doc addon-editor addon-table kit cdk i18n icons testing
```

## Motivation

we had to write code that will exclude applications

![image](https://user-images.githubusercontent.com/12021443/138287562-70a56f2d-ff53-45bf-9963-d8ec54c21814.png)

![image](https://user-images.githubusercontent.com/12021443/138287577-a93a6751-51d5-421e-af19-cf223e18e782.png)

**Comment by AgentEnder** [comment]
`run-many` does support exclude as you expected, see the docs here: https://nx.dev/l/n/cli/run-many#exclude

**Comment by f22hd** [comment]
> ```
> So then you can do: nx run-many --target package --all and because apps won't have the package target, they won't be run.
> ```
> 
> But I want use build command instead package))
> 
> work in branch/any
> 
> ```
> npx nx affected --target=build --exclude=$(nx affected:apps --plain)
> ```
> 
> didn't work in branch/master
> 
> ```
> npx nx run-many --target=build --all  --exclude=$(nx affected:apps --plain)
> ```
> 
> We want
> 
> ```
> $ nx workspace:apps --plain # show all names for library type
> $ nx workspace:libs --plain # show all names for apps type
> ```
> 
> And then we can in master:
> 
> ```
> npx nx run-many --target=build --all  --exclude=$(nx workspace:apps --plain)
> ```

it would be great to add this command, any update?

**Comment by padraigfl** [comment]
obvious hack, but `nx affected:apps --plain --target=build --base=${INITIAL_OR_VERY_OLD_GIT_COMMIT_HASH}` might suffice for some use cases?

**Comment by distante** [comment]
It is not possible to list all projects? Why is this issue closed?
