### ISSUE TITLE
Run-many projects option not working properly

### ISSUE THREAD

**Issue by khalilou88** [nrwl/nx#7482]
## Current Behavior

`nx run-many --target=lint --projects=web-app,api` result :

```
Error: Invalid projects: web-app api
    at checkForInvalidProjects (C:\Users\khali\devs\run-many-projects\node_modules\@nrwl\workspace\src\command-line\run-many.js:54:15)
    at projectsToRun (C:\Users\khali\devs\run-many-projects\node_modules\@nrwl\workspace\src\command-line\run-many.js:35:9)
    at Object.<anonymous> (C:\Users\khali\devs\run-many-projects\node_modules\@nrwl\workspace\src\command-line\run-many.js:21:26)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\khali\devs\run-many-projects\node_modules\tslib\tslib.js:114:62)
```

## Expected Behavior

`nx run-many --target=lint --projects=web-app,api` should lint project1 and project2
Same for other executors like test and so.

## Steps to Reproduce
I produce it here https://github.com/khalilou88/run-many-projects

### Environment
`PS C:\Users\khali\devs\run-many-projects> nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.15.1
  OS   : win32 x64
  npm  : 6.14.8

  nx : 13.0.2
  @nrwl/angular : 13.0.2
  @nrwl/cli : 13.0.2
  @nrwl/cypress : 13.0.2
  @nrwl/devkit : 13.0.2
  @nrwl/eslint-plugin-nx : 13.0.2
  @nrwl/express : Not Found
  @nrwl/jest : 13.0.2
  @nrwl/linter : 13.0.2
  @nrwl/nest : 13.0.2
  @nrwl/next : Not Found
  @nrwl/node : 13.0.2
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.0.2
  @nrwl/web : Not Found
  @nrwl/workspace : 13.0.2
  @nrwl/storybook : 13.0.2
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

PS C:\Users\khali\devs\run-many-projects> `

**Comment by mateuszkocz** [comment]
Seems like the issue got swept under the rug. If you navigated here, the work around it to remove the Nx cache in `node_modules/.cache/nx`.

**Comment by Stusaw** [comment]
Still have an issue with this. Solution for me is to declare --projects in quotes ( " or ' ), E.g. --projects="project1,project2"

**Comment by michaeljmonte** [comment]
> Still have an issue with this. Solution for me is to declare --projects in quotes ( " or ' ), E.g. --projects="project1,project2"

Same issue, this solution worked for me.

**Comment by ajihyf** [comment]
Same issue on Windows. Add quotes helps but can not do it in vscode externsion.
