### ISSUE TITLE
Npx nx serve does not work:  [webpack-dev-middleware] wait until bundle finished

### ISSUE THREAD

**Issue by Lonli-Lokli** [nrwl/nx#7495]
## Current Behavior
npx nx serve does not work - page is just showing browser progress

## Expected Behavior
npx nx serve should work

## Steps to Reproduce

So I've migrated from Nx12 to Nx13 
npm run update
npm install
npx nx migrate --run-migrations
npx nx g @nrwl/workspace:convert-to-nx-project --all

I have 3 apps (2 react, one express) and about 20 libs

### Failure Logs
 npx nx serve

> nx run recon:serve 
<i> [webpack-dev-server] [HPM] Proxy created: /doAction  -> http://localhost:3333
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:4200/, http://127.0.0.1:4200/
<i> [webpack-dev-server] 404s will fallback to '/index.html'

>  NX  Web Development Server is listening at http://localhost:4200/

<i> [webpack-dev-middleware] wait until bundle finished: /

### Environment
  Node : 14.17.4
  OS   : win32 x64
  npm  : 6.14.11

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 13.0.2
  @nrwl/cypress : 13.0.2
  @nrwl/devkit : 13.0.2
  @nrwl/eslint-plugin-nx : 13.0.2
  @nrwl/express : 13.0.2
  @nrwl/jest : 13.0.2
  @nrwl/linter : 13.0.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 13.0.2
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 13.0.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.0.2
  @nrwl/web : 13.0.2
  @nrwl/workspace : 13.0.2
  @nrwl/storybook : 13.0.2
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by jaysoo** [comment]
@phal0r @Lonli-Lokli Would you be able to provide a repro or more info? Like if you have any additional webpack plugins , etc.?

**Comment by W3Max** [comment]
Same problem here.
Simple setup : Next Web App (almost empty), 1 lib with 1 simple react component.

**Comment by Lonli-Lokli** [comment]
@jaysoo I updated acorn dependency, removed resolve for it (it was required before to handle some new TS fearures) and now I am able to serve with latest webpack & Nx. Just to note, serve time increased comparing to previous version

**Comment by phal0r** [comment]
My problem persists. I tried to upgrade to nx 13.1.x, but still the same problem, high cpu load until browser crashes. I will try to create a repro and provide it.

**Comment by nemonemi** [comment]
@phal0r have you managed to resolve your problem, and if so, how?

**Comment by phal0r** [comment]
@nemonemi I abandonded my branch and we made another try updating Nx, which worked without the issues. So I guess, I did something wrong or had a local problem.
