### ISSUE TITLE
Help:  Tests are not updating snapshot, sorry if this is not the right forum

### ISSUE THREAD

**Issue by daBishMan** [nrwl/nx#750]
Hello I created a new project using nx 6.3 with CLI 6.15 to try to get Jest to work and understand how it works.   

Repo for this work [Public Repo](https://github.com/daBishMan/nx-jest)

I created a new workspace, added jest, created a single library, I am able to create the first snapshot.  I updated the HTML on both components under tests, yet I failed to get the snapshots to update, I am not sure if it is an nx problem, a user problem (definitely a possibility) or jest problem. 

I can not figure out how to get the jest runner to re-generate the snapshot.

Can you help.

**Comment by FrozenPandaz** [comment]
`yarn test libname --updateSnapshot` and read the [Jest Docs on Snapshot Testing](https://jestjs.io/docs/en/snapshot-testing).

Short Explanation of **Snapshot Testing**
* The first time a snapshot is tested, it is generated by default (no options).
  * The snapshot's value is set to the input of the test.
  * These snapshots should be committed to your repository.
* After the snapshot is generated for the first time, it is matched against the test input.
* If it does not match, the expectation fails.
* If this change is _unintentional_, this is a real mistake and should be fixed.
* If this change is _intentional_, the snapshot needs to be updated. To do this, pass `--updateSnapshot` (or `-u`).
  * These changes should be committed to your repository.
* In CI, if the snapshot is not generated, the test should fail.
  * Use the `--ci` option when running in CI to cause tests without snapshots to fail.

I hope this answers your question. Feel free to reopen the issue if it is not answered.

**Comment by daBishMan** [comment]
Thank you so much for your reply.  I have another quick question, specifically around have ng-version the snapshot.  

The only way I was able to get the snapshot to generate html template was using the following:

`
expect(fixture.nativeElement).toMatchSnapshot();
`
The snapshot looks like:

`exports["TestTwoComponent should test fixture snapshot 1"] =`
`<div  id="root1"  ng-version="6.1.6">`
  `<h1>    Header For Test-Two  </h1>`
  `<p>     test-two works!  </p>`
  `<p>     From Unit Test   </p>`
`</div>`

I have couple of questions:
- Is this the right way to test the component template? 
- if that is the right way, the snapshot has the ng-version in it, which means when I update my Angular version I would have to update all my snapshots?

**Comment by FrozenPandaz** [comment]
@daBishMan You are correct, that is snapshotting the component. One recommendation I would make the mitigate part 2 is to point to a node you're responsible for to test.
```diff
- expect(fixture.nativeElement).toMatchSnapshot();
+ expect(fixture.nativeElement.querySelector('h1')).toMatchSnapshot();
```

Reasoning:
* Your code is not responsible for generating the root and the ng-version, Angular is doing that and as you said, the snapshot will change when you update which does not necessarily mean your code is wrong.
* You're going to get more granular test results which will better tell the issue without even going into the logs.
  * `headline does not match snapshot` vs `app does not match snapshot`

**Comment by intellix** [comment]
one thing that makes development really painful is the inability to update snapshots easily from the many apps/libs that changed in a PR.

16 different libs have incorrect snapshots due to me touching a base component aand the only way to fix them is to either:

Takes ages due to many libs
```
ng test -u
```

or copy/paste the `git status` modified file list, cut off `libs` and `src` and prefix each line with ng test -u.

Wish there was something like `nx affected:snapshots -u`
