### ISSUE TITLE
Circular dependency between "applib1-" and "app1" detected: applib1 -> app1 -> applib1 @nrwl/nx/enforce-module-boundaries

### ISSUE THREAD

**Issue by GrumpyMeow** [nrwl/nx#7507]
## Current Behavior
The ESLint rule "@nrwl/nx/enforce-module-boundaries" concludes that a circular dependency, which is not the case.

## Expected Behavior
I expect that the ESLint-rule to only look at the entries in the "compilerOptions.paths" of the apps/libs to look for circular-dependencies. I think that the current implementation of the ESLint-rule will always add entries for all apps to it's model, while the path is not exposed thru the "compilerOptions.paths".

Normally the ESLint-rule probably doesn't give any issue, but because our (current) naming convention the ESLint rule falsely sees a circular-dependency.

## Steps to Reproduce

Our app/lib folder structure:
```
apps/products-app/...
apps/customers-app/...
libs/products-app/productslib/...
libs/products-app/specificationslib/...
libs/customers-app/customerslib/...
```
In the root tsconfig.json file:
```
"paths": {
      "@our-nx/products-app/productslib/product": ["libs/products-app/productslib/index.ts"],
      "@our-nx/products-app/specificationslib/something": ["libs/products-app/specificationslib/index.ts"],
}
```
When we do in the "libs/products-app/productslib/index.ts":
```
import { Something } from '@our-nx/products-app/specificationslib/something';
```
As we didn't register our actual app in the paths-entries we wouldn't expect the circular reference. But it seems that "@our-nx/products-app" is implicitly registered for the app (apps/products-app/....) in the ESLint-rule-logic.

### Environment

@nrwl/angular : 9.8.0
  @nrwl/cli : 9.8.0
  @nrwl/cypress : 12.5.8
  @nrwl/eslint-plugin-nx : 12.3.4
  @nrwl/express : 12.3.6
  @nrwl/jest : 9.8.0
  @nrwl/linter : 12.3.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.3.6
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.8.0
  @nrwl/web : 12.6.2
  @nrwl/workspace : 9.8.0
  typescript : 3.8.3

**Comment by meeroslav** [comment]
Thank you @GrumpyMeow for reporting. We were able to reproduce it on latest version, so no need to check anything on your side.

**Comment by meeroslav** [comment]
@GrumpyMeow can you tell me which IDE you use and whether this was error in IDE or also in the terminal?

VS Code has an issue with updating to latest changes, so when adding new project might report wrongfully this error.  Restarting ESLint Server should fix it. Can you please verify this? Also running `nx lint productslib` should run without an error.

In the meantime I will check why this issue gets reported in IDE at all.

**Comment by meeroslav** [comment]
Hi @GrumpyMeow,

I could not reproduce your issue with latest 12.x and 13.x versions.
Can you please confirm that you still have the error after updating all packages to the same version?
If not, I kindly ask you to close this issue.

**Comment by GrumpyMeow** [comment]
I’m unable to retry. Good to hear that the issue is resolved
