### ISSUE TITLE
@nrwl/web:build: extractCss no longer honored

### ISSUE THREAD

**Issue by doublemarked** [nrwl/nx#7512]
I'm in the process of upgrading a project from nx 12 to nx 13 and encountered some discrepancies in build outputs. 

## Current Behavior

As of https://github.com/nrwl/nx/pull/7411 the `extractCss` option for `@nrwl/web:build` is no longer honored. When `extractCss: false`, the `MiniCssExtractPlugin` is still injected into the webpack config, and CSS files are extracted. 

## Expected Behavior

I expect the `extractCss` flag to behave as it did in nx12 when `extractCss: false`.

The documentation and schema still reference `extractCss`, but it appears to have been thoroughly purged from the code in PR https://github.com/nrwl/nx/pull/7411. It's not clear if this is a regression or not, and it's not clear whether there's an intended alternative.

**Comment by qbawalat** [comment]
Hi @jaysoo, what is the status on this one? Can we expect a fix anytime soon?

**Comment by MkMan** [comment]
This is causing my project's styling to break when I try to migrate to Nx 13. When the css is extracted the classes I set in the repo are being overridden by the ones shipped from the Material UI library.

**Comment by vadistic** [comment]
Just noticed this:

https://github.com/nrwl/nx/blob/45bf0e5a251d8d0261204514ac2e31eec8f83c29/packages/web/src/utils/web.config.ts#L75
