### ISSUE TITLE
Support for generating secondary entry points in libraries

### ISSUE THREAD

**Issue by leosvelperez** [nrwl/nx#7517]
This was split from the https://github.com/nrwl/nx/issues/4733, created by @albyrock87.

## Description

Would like to create secondary entry points for publishable libraries, similar to what packages like `@angular/material` does. For example:

```
- @angular/cdk <-- package
  - @angular/cdk/tree <-- secondary entry point
  - ...
- @angular/material <-- package
  - @angular/material/button <-- secondary entry point
  - @angular/material/icon <-- secondary entry point
  - ...
```

## Motivation

Having secondary entry points is useful to split symbols we don't want to group together with the main entry point (e.g. `@nrwl/angular` and `@nrwl/angular/testing`).

## Suggested Implementation

Have a generator that allows creating secondary entry points for a library. The entry points should be a nested folder inside an existing library with a `package.json` file inside. A path mapping needs to be added to the `tsconfig.base.json` in order to correctly resolve imports from the entry point.

Also, the `@nrwl/web:package` executor would need to support this. It would need to collect the secondary entry points to build them and expose them in the output package by either:

- Have a `package.json` in the output of each secondary entry point defining its entry file.
- Have only one top-level `package.json` for the package with the `exports` field containing the main entry point and the secondary entry points.

**Comment by sumitparakh** [comment]
Would love to have this feature in Nx
