### ISSUE TITLE
Documenation: Unit tests for Workspace Schematic

### ISSUE THREAD

**Issue by CharlieGreenman** [nrwl/nx#753]
I was wondering if some documentation could perhaps be added around unit testing for the workspace  schematics. In particular how to use the SchematicTestRunner, when there is no collection.json produced. Thank you.

**Comment by minijus** [comment]
Generating new workspace schematics results only in implementation file. And it is great, as it simplifies usage and development of schematics a lot.

However, there is no test setup for these schematics. It would be great to have:
* dummy test file generated for initial tests
* test runner for schematics inside workspace
* adding ./tools/schematics to affected modules pool (if anything changed for schematics - run lint and tests for ./tools/schematics).

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.
