### ISSUE TITLE
[feature] Ability to pass through options to jest via ng test

### ISSUE THREAD

**Issue by johnRambo2k14** [nrwl/nx#754]
I'm currently experiencing issues where my CI memory limit is being maxed since jest sets a worker for each existing CPU.

It would be great if I can pass in Jest CLI options through including `--runInBand`

A full list of CLI commands can be found here:

https://jestjs.io/docs/en/cli.html

**Comment by skydever** [comment]
hi @johnRambo2k14,

do you also set a `--maxParallel` parameter when you run `affected:test`, if that is the way how you start the tests via CI? but yes, setting all the cli params in `angular.json` to pass through to jest would be great 👍

**Comment by johnRambo2k14** [comment]
Ah that totally escaped me! I haven't tested it out with jest just yet, I will let you know my findings.

**Comment by FrozenPandaz** [comment]
I will add `runInBand` and `maxWorkers` as per this [troubleshooting docs from jest docs](https://jestjs.io/docs/en/troubleshooting#tests-are-extremely-slow-on-docker-and-or-continuous-integration-ci-server).

I am holding off on passing every option into `jest` as there may be some which are not applicable. Adding options is relatively easy to do, so we will keep maintaining it this way for the time being.

**Comment by matheo** [comment]
@FrozenPandaz the `runInBand` and `maxWorkers` (2) are there by default now?
I'm having memory problems with CircleCI and I'm wondering how to address this with Nx

**Comment by demisx** [comment]
Just to clarify, the `runInBand` option needs to be set in `angular.json`:

```json
     "e2e": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "apps/api-e2e/jest.config.js",
            "tsConfig": "apps/api-e2e/tsconfig.spec.json",
            "runInBand": true
          }
      }
```
