### ISSUE TITLE
Schematic "13-0-0-config-locations" is missing a factory

### ISSUE THREAD

**Issue by simhnna** [nrwl/nx#7554]
`An unhandled exception occurred: Schematic "13-0-0-config-locations" is missing a factory.`

Looks like this [line](https://github.com/nrwl/nx/blob/master/packages/workspace/migrations.json#L189) should use `factory` instead of `implementation`

**Comment by simhnna** [comment]
I was getting that in two projects uring nrwl 8 or 11. The issue was that I upgraded using the angular cli instead of using nx. Using nx and updating one major release at a time I got through. The repositories are private repositories that I can't share.
If you want you can close the issue I guess.

**Comment by AgentEnder** [comment]
I'm going to go ahead and close this out, since using `nx migrate` went well. Thanks for the follow up info @simhnna, `nx migrate` is the preferred way to update Nx, as you can definitely hit some odd behavior otherwise.
