### ISSUE TITLE
`runExecutor()` should trigger target dependencies

### ISSUE THREAD

**Issue by yjaaidi** [nrwl/nx#7560]
## Description

The logic of triggering target dependencies described in `nx.json` _(cf. https://nx.dev/l/a/core-concepts/configuration#target-dependencies)_ is embedded in [`runCommand()`](https://github.com/nrwl/nx/blob/b23f2d8b8027795184b74e0bcdf0567a87e9a4b4/packages/workspace/src/tasks-runner/run-command.ts#L28) but this function is not exposed by the `@nrwl/devkit`

The most similar function exposed by `@nrwl/devkit` is [`runExecutor()`](https://github.com/nrwl/nx/blob/79cf69b4e4adc687043cd064a37367086267d67f/packages/tao/src/commands/run.ts#L290) which doesn't trigger target dependencies.

It would be nice to expose a function in `@nrwl/devkit` that triggers target dependencies.

## Motivation

[@jscutlery/sermver's postTargets option](https://github.com/jscutlery/semver#post-targets) is using `runExecutor()` under the hood but [here is an issue with this approach as this doesn't trigger the target dependencies (https://github.com/jscutlery/semver/issues/367).
e.g. adding `my-project:build` to `postTargets` doesn't trigger `my-project's` dependencies build.

## Suggested Implementation

Here are different possibilities:

1. Move the target dependencies logic to [`runExecutor()`](https://github.com/nrwl/nx/blob/79cf69b4e4adc687043cd064a37367086267d67f/packages/tao/src/commands/run.ts#L290)
2. Move the target dependencies logic to [`runExecutor()`](https://github.com/nrwl/nx/blob/79cf69b4e4adc687043cd064a37367086267d67f/packages/tao/src/commands/run.ts#L290) and hide it behind an option like `runTargetDependencies: true`
3. Add a function similar to [`runCommand()`](https://github.com/nrwl/nx/blob/b23f2d8b8027795184b74e0bcdf0567a87e9a4b4/packages/workspace/src/tasks-runner/run-command.ts#L28)  to `@nrwl/devkit`

**Comment by tonivj5** [comment]
Up

**Comment by LonguCodes** [comment]
I'm facing this issue as well, can progress on this?

**Comment by k1llabee** [comment]
+

**Comment by samuelfernandez** [comment]
@AgentEnder @vsavkin would you welcome a contrib on this issue? Anything to take into consideration? As stated above, I assume that `runExecutor` should trigger dependencies by default.

**Comment by AgentEnder** [comment]
Hey @samuelfernandez ! Thanks for the offer, but we are currently evaluating exactly what the API will look like for this. It won't be a fix for the run executor function, as that's meant to be a low level function. 

It'll likely be a new API

**Comment by samuelfernandez** [comment]
@AgentEnder any news or related follow up issues? Thanks for the great job you do! 😄

**Comment by AgentEnder** [comment]
An API for this isn't currently planned. If you need to run a target, complete with caching, dependencies etc, you should use `execSync` or similar to start a new instance of Nx. I understand this isn't ideal.

For the time being, I'm going to close this out as there isn't further work in the area planned. Know that it is a known limitation, and may eventually be changed.
