### ISSUE TITLE
Bundle size is different in command output than files on the hard disk.

### ISSUE THREAD

**Issue by f22hd** [nrwl/nx#7574]
## Current Behavior
I just noticed a big difference between the output files size that displayed after the build is finished in the command line and the app folder on the hard disk. 

I've experimented with many different project sizes, I just increase budget files sizes in `workspace.json` file as a workaround to resolve this issue. 
The following screenshot with the initial workspace with one react application.

![Screenshot 2021-10-30 at 13 32 49](https://user-images.githubusercontent.com/5451346/139530476-80dd2ef3-bc3d-4530-a7f7-c6fb67ac18d4.jpg)

![Screenshot 2021-10-30 at 13 53 40](https://user-images.githubusercontent.com/5451346/139530513-c8389e9f-7996-4ff9-a3ba-8715e2a762d9.jpg)

other project:
![Screenshot 2021-10-30 at 14 09 55](https://user-images.githubusercontent.com/5451346/139530587-46d1b59f-8522-4279-9e13-7c2d6785166b.jpg)

![Screenshot 2021-10-30 at 14 10 02](https://user-images.githubusercontent.com/5451346/139530590-d72e6419-9e6a-45b7-9024-ffab3dccb9dc.jpg)

### Environment

  Node : 12.16.3
  OS   : darwin x64
  npm  : 7.20.6
  
  nx : 13.1.2
  @nrwl/angular : Not Found
  @nrwl/cli : 13.1.2
  @nrwl/cypress : 13.1.2
  @nrwl/devkit : 13.1.2
  @nrwl/eslint-plugin-nx : 13.1.2
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.2
  @nrwl/linter : 13.1.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 13.1.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.2
  @nrwl/web : 13.1.2
  @nrwl/workspace : 13.1.2
  @nrwl/storybook : 13.1.2
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Any explanation?**

**Comment by ruslan-byondxr** [comment]
stat, parsed or gzip:

On filesystem you see the stat file size

**Comment by AgentEnder** [comment]
@ruslan-byondxr is correct as to why they show up differently, this is more accurate to how browsers + transfer is affected by file size.
