### ISSUE TITLE
After migrating to NX 13: "Nx Console encountered an error parsing your node modules"

### ISSUE THREAD

**Issue by rujorgensen** [nrwl/nx#7586]
I recently migrated to NX 13 and I am now unable to use Nx Console via the extension in VS Code. The issue seems to be that some folders in node_modules does not contain a package.json-file (if I manually add empty ones the tool seems to work again).

The reason we have folders without package.json-files in node_modules is that we use the Prisma ORM to generate types, and our current setup is configured to put them in node_modules.

The issue haven't been there before migrating to NX 13, as far as I know.

![image](https://user-images.githubusercontent.com/6797319/139802205-b3cf8e53-11a3-417a-b9ac-d700965a15d9.png)
![image](https://user-images.githubusercontent.com/6797319/139802492-e61adbf5-aba0-481e-a9c3-164039fbb1fe.png)

## Current Behavior
Nx Console fails to run.

## Expected Behavior
Being able to use the Nx Console (eg. for generating a new Angular app in my current workspace)

## Steps to Reproduce
Have folders in node_modules which does not contain a package.json file

### Environment
 Node : 14.18.1
  OS   : win32 x64
  npm  : 7.5.3
  
  nx : 13.1.2
  @nrwl/angular : 13.1.2
  @nrwl/cli : 13.1.2
  @nrwl/cypress : 13.1.2
  @nrwl/devkit : 13.1.2
  @nrwl/eslint-plugin-nx : 13.1.2
  @nrwl/express : 13.1.2
  @nrwl/jest : 13.1.2
  @nrwl/linter : 13.1.2
  @nrwl/nest : 13.1.2
  @nrwl/next : Not Found
  @nrwl/node : 13.1.2
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.2
  @nrwl/web : Not Found
  @nrwl/workspace : 13.1.2
  @nrwl/storybook : 13.1.2
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

Thanks!

**Comment by rujorgensen** [comment]
The issue seems to have solved itsself. It might have been a glitch on my system although I updated to v. 13.1.3 this morning, perhaps that had something to do with it 🤷‍♂️.

All good, closing 😊.

**Comment by ammad172** [comment]
I am still not able to resolve it please help
