### ISSUE TITLE
React-hooks/exhaustive-deps not "working"

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#7588]
## Current Behavior

The application is configured to use the plugin, however, it is not being applied in the component.

## Expected Behavior

The dependency array of e.g. `useEffect` should be marked whenever there is a dependency inside which is not denoted in the dependency array.

## Steps to Reproduce

Add to an application's `extends` property in the `.eslintrc.json` the `"plugin:react-hooks/recommended"` plugin.
In a component of said application add 
```ts
useEffect(() => {
    errors?.forEach((error) => {
      if (!isFetching) {
        history.push('/error-screen', { errorCode: '500', goBackPath: '/' });
      }
    });
  }, [history]);
```

Notice how, e.g. `isFetching` is not in the dependency array, but the said array is not reporting any problems with it.

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

 Node : 14.15.4
  OS   : win32 x64
  yarn : 3.0.2

  nx : 12.9.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.9.0
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by Joroze** [comment]
I've also came across this issue.

**Comment by Joroze** [comment]
I think this is caused from the upgrade of ESLint v7.x to v8.x

**Comment by nemonemi** [comment]
My project is at Eslint 7.22.0

**Comment by violabg** [comment]
I confirm this as a bug with ESLint 8 and vscode.
I'm using "@nrwl/react": "13.4.6",
and with "eslint": "8.2.0",

I receive a warning in vscode output console
`Rules with suggestions must set the `meta.hasSuggestions` property to `true`. Occurred while linting /Users/paolo/Sites/mc-intranet/apps/web/src/pages/login/index.tsx:114 Rule: "react-hooks/exhaustive-deps"`

but not quick fix option in the ide.

if I downgrade to eslint 7 it works.

**Comment by nemonemi** [comment]
I will close this ticket.

Feel free to re-open it, should the need arise.
