### ISSUE TITLE
Add a feature similar to "affected" but is focused on "related" 

### ISSUE THREAD

**Issue by jyono** [nrwl/nx#7589]
## Description

I have found the "affected" feature incredible useful for speeding up our CI pipeline and building. A problem that still arises is for the worst case for affected builds is essentially a restart. For example, if one has a library that is used in 20 apps in the mono repo, every app needs to be rebuilt when that libary changes. 

Similar to `affected`, I'm pitching a tag for `related` that can be used the same way, but targets all things that an app/lib depends on. 

This behavior isn't really useful for `build` commands because they can rely on their imports to build all of their dependencies. This would be really useful for commands like `test/lint`. For example, if you do `npm run nx build myapp`, it will build all the required libs. If you do `npm run nx test myapp`, it will only run the app's test, but not any of the "related" libs tests. 

## Motivation

I'm an engineer at StockX and one of my goals was to speed up our CI builds. We leveraged affected builds but found that we still have the worst case problem and that affected builds alone weren't sufficient. I knew that `nx dep-graph` simulates this behavior when it builds the dep-graph. I dug into the NX source code and found that the you can specify an output file and json is a supported type. None of this is described in the NX docs, but maybe including it would be helpful. The command `NX_APP=my_app dep-graph nx dep-graph --focus=$NX_APP **--file=/output.json` actually outputs the dependencies needed for that specific app. 

In order to get the test/lint dependencies, I wrote some custom scripts to build the dep-graph, output it locally, read it, parse it, and run the "related" test/builds. This is far from ideal and I think others might benefit from this behavior. 

## Suggested Implementation
If this is something that Nx is interested in and goes with existing design philosophy I'm happy to do the leg work for an implementation. 
TBD

## Alternate Implementations
with-deps is deprecated. however, i found the replacement quite nice

    "targetDependencies": {
        "build": [
            {
                "target": "build",
                "projects": "dependencies"
            }
        ],
        "test": [
            {
                "target": "test",
                "projects": "dependencies"
            }
        ],
        "lint": [
            {
                "target": "lint",
                "projects": "dependencies"
            }
        ]
    }

**Comment by konstantintieber** [comment]
Hi @jyono, I published a GitHub Action using the same approach to get the affected projects scoped to one application and its dependencies: https://github.com/leanix/nx-affected-dependencies-action

I also published a blog post about it: https://engineering.leanix.net/blog/smarter-nx-affected-checks/

With some feedback by the nx team on how to incorporate such a command into the nx cli I would be happy to prepare a PR for this.

Maybe it could be something like this: `nx run my-react-app:test --with-affected-deps`

**Comment by JoshuaCWebDeveloper** [comment]
Wouldn't this feature be the same as running `nx run-many --target=test --projects=myapp --with-deps`, or am I not understanding it?

**Comment by alfaproject** [comment]
FYI:
> DEPRECATION WARNING: --with-deps is deprecated and it will be removed in v14.
> Configure target dependencies instead: https://nx.dev/latest/angular/core-concepts/configuration#target-dependencies.

**Comment by konstantintieber** [comment]
> Wouldn't this feature be the same as running nx run-many --target=test --projects=myapp --with-deps, or am I not understanding it?

That command does not filter out the dependencies that come from the `with-deps` list that are not affected. It will just test project `myapp` and all its dependencies.

**Comment by JoshuaCWebDeveloper** [comment]
> While I did not check if the nx cli actually supports `run-many` or even just `run` with a `with-deps` flag, let's assume it does.
> 
> Then that command does not filter out the dependencies that come from the `with-deps` list that are not affected. It will just test project `myapp` and all its dependencies, where the non-affected ones are of course tested without necessity.

That is the command I use to target a dependency tree, so it does work, but as @alfaproject pointed out, it is now deprecated, and you are correct it doesn't have the `affected` behavior.

**Comment by jyono** [comment]
> > Wouldn't this feature be the same as running nx run-many --target=test --projects=myapp --with-deps, or am I not understanding it?
> 
> While I did not check if the nx cli actually supports `run-many` or even just `run` with a `with-deps` flag, let's assume it does.
> 
> Then that command does not filter out the dependencies that come from the `with-deps` list that are not affected. It will just test project `myapp` and all its dependencies, where the non-affected ones are of course tested without necessity.

with-deps is deprecated. however, i found the replacement quite nice 

```
    "targetDependencies": {
        "build": [
            {
                "target": "build",
                "projects": "dependencies"
            }
        ],
        "test": [
            {
                "target": "test",
                "projects": "dependencies"
            }
        ],
        "lint": [
            {
                "target": "lint",
                "projects": "dependencies"
            }
        ]
    }
```

**Comment by jyono** [comment]
I haven't tested it yet, but i believe 

```
    "targetDependencies": {
        "build": [
            {
                "target": "build",
                "projects": "dependencies"
            }
        ],
        "test": [
            {
                "target": "test",
                "projects": "dependencies"
            }
        ],
        "lint": [
            {
                "target": "lint",
                "projects": "dependencies"
            }
        ]
    }
```

 + using an affected command should give the desired output @konstantintieber

**Comment by chromey** [comment]
@jyono The problem though is that this hardwires the behaviour to include dependent projects to the target, but I would really like to have an opt-in feature like `with-deps` provided:

I have a setup where I have a Jenkins "dispatch" job that uses `nx affected:apps` to find out what to build, then delegates to individual jobs that only test, lint and build one application (with their dependencies, so I am using `with-deps`). But locally I want to continue to be able to execute tests only for the app I am currently working on.

Of course the computation cache would prevent unchanged libs from being tested all over again, but it would still be nice to (continue to) have that option explicitly.

**Comment by jyono** [comment]
@chromey well, in this case i did overwrite the default build/test, but you can just write wrappers around this so you can have the isolated normal test/lint and the test-with-deps/lint-with-deps

**Comment by konstantintieber** [comment]
To prevent this ticket being closed: Nx still does not support a way to run the affected command to only get the list of affected projects that are the dependency of a given app/library.

**Comment by jyono** [comment]
is this still on the table?
