### ISSUE TITLE
jest test is not satisfied.

### ISSUE THREAD

**Issue by kang-heewon** [nrwl/nx#7591]
## Current Behavior

test failed with this message.
Directory /root in the rootDir option was not found.

## Expected Behavior

The master branch wants to satisfy the tests

## Steps to Reproduce

Go to the master branch and run nx test jest.

### Failure Logs

  ● Jest Executor › when the jest config file is untouched › should send appropriate options to jestCLI

    ● Validation Error:

      
        Directory /root in the rootDir option was not found.
      
        Configuration Documentation:
        https://jestjs.io/docs/configuration
      

### Environment

i'm on 588793bd9d0bac72fd8648a7b80eaa82b4dacfac commit

**Comment by AgentEnder** [comment]
This should be fixed by #7556
