### ISSUE TITLE
Storybook - yarn audit  

### ISSUE THREAD

**Issue by arumuganainar73** [nrwl/nx#7595]
## Description

We Developed Nx monorepo application and added storybook. 

While running yarn audit command  below packages are creating high vulanarbilty.

### Command

I tried 'yarn audit --level high' 

### Failure Logs

@storybook/builder-webpack5 
@angular-devkit/build-angular
@storybook/angular    
@storybook/addon-essentials

**Comment by mandarini** [comment]
Hi there @arumuganainar73 ! Thank you for your concern regarding these packages. These are really part of the Nx workspace dependencies, and given that these packages are not owned by us, there really isn't something we could do about it. However, I would suggest that you could update these packages and see if they're still under "high vulnerability", and soon Storybook v6.4 will be out, and once it's stable it may not be in that list either! :)
