### ISSUE TITLE
Cannot read property 'e2e' of undefined

### ISSUE THREAD

**Issue by macjohnny** [nrwl/nx#760]
When performing the following steps:

```
ng new test6
cd test6
ng add @nrwl/schematics
```
I get the following error:
```
+ @nrwl/schematics@6.3.0
added 47 packages in 11.85s
Installed packages for tooling via npm.
    Cannot read property 'e2e' of undefined
    Your workspace could not be converted into an Nx Workspace because of the above error.
```
Versions:
```
Angular CLI: 6.2.1
Node: 8.9.1
OS: win32 x64
Angular: 6.1.7
```

**Comment by FrozenPandaz** [comment]
Fix: Please use `@angular/cli@6.1.5` for now.

Related Issue: https://github.com/angular/angular-cli/issues/12230

**Comment by macjohnny** [comment]
seems to work as expected with `@angular/cli@6.2.2`

**Comment by macjohnny** [comment]
@vance which angular cli version are you using?

**Comment by vance** [comment]
I am using `"@angular/cli": "6.2.4"`

**Comment by vance** [comment]
hm, doing a manual ng update on cli and core first seems to have fixed it.

**Comment by wilgert** [comment]
I'm running into the same issue when trying to add Nx to an Angular project that was created in 2017. Too bad the error message gives so little info.
