### ISSUE TITLE
Create NX Workspace command crashes with NextJS and Styled Components

### ISSUE THREAD

**Issue by Durisvk** [nrwl/nx#7609]
## Current Behavior
Running `npx create-nx-workspace` and choosing Next.JS with styled-components fails at `Creating your workspace` step with `Nx failed to create a workspace.`.

It works when I select `express` preset

## Expected Behavior
Workspace should be bootstrapped

## Steps to Reproduce

1. run `npx create-nx-workspace`
2. enter any organization name
3. select Next.JS
4. select styled-components
5. select that you don't want to use Nx cloud (doesn't matter what you select)
6. see error in **Failure Logs** section

### Failure Logs
**var/folders/d3/.../T/tmp-.../error.log**:
```
CREATE org/README.md
CREATE org/.editorconfig
CREATE org/.gitignore
CREATE org/.prettierignore
CREATE org/.vscode/extensions.json
CREATE org/workspace.json
CREATE org/nx.json
CREATE org/package.json
CREATE org/tools/generators/.gitkeep
CREATE org/tools/tsconfig.tools.json
CREATE org/tsconfig.base.json
CREATE org/.prettierrc
CREATE org/apps/.gitkeep
CREATE org/libs/.gitkeep

npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated ecstatic@3.3.2: This package is unmaintained and deprecated. See the GH Issue 259.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     '/Users/jurajcarnogursky/org/org/org/node_modules/@nrwl',
npm WARN cleanup     [Error: EINVAL: invalid argument, rmdir '/Users/jurajcarnogursky/org/org/org/node_modules/@nrwl/workspace/src/generators/library/files'] {
npm WARN cleanup       errno: -22,
npm WARN cleanup       code: 'EINVAL',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: '/Users/jurajcarnogursky/org/org/org/node_modules/@nrwl/workspace/src/generators/library/files'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path /Users/jurajcarnogursky/org/org/org/node_modules/coa
npm ERR! command failed
npm ERR! command sh -c start /B node compile.js & node compile.js
npm ERR! sh: start: command not found
npm ERR! internal/modules/cjs/loader.js:905
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module '/Users/jurajcarnogursky/org/org/org/node_modules/coa/compile.js'
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
npm ERR!     at internal/main/run_main_module.js:17:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jurajcarnogursky/.npm/_logs/2021-11-04T13_27_45_813Z-debug.log
Command failed: npm install
```

---
**/Users/jurajcarnogursky/.npm/_logs/2021-11-04T13_27_45_813Z-debug.log**

```
6231 error code 1
6232 error path /Users/jurajcarnogursky/org/org/org/node_modules/coa
6233 error command failed
6234 error command sh -c start /B node compile.js & node compile.js
6235 error sh: start: command not found
6235 error internal/modules/cjs/loader.js:905
6235 error   throw err;
6235 error   ^
6235 error
6235 error Error: Cannot find module '/Users/jurajcarnogursky/ooo/org/org/node_modules/coa/compile.js'
6235 error     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
6235 error     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
6235 error     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
6235 error     at internal/main/run_main_module.js:17:47 {
6235 error   code: 'MODULE_NOT_FOUND',
6235 error   requireStack: []
6235 error }
6236 verbose exit 1
```

### Environment
**macOS** Big Sur v11.5.2
**NodeJS** v14.18.0
**npm** v7.24.0

**Comment by Durisvk** [comment]
Actually, just found out that even running `npm install -D @nrwl/next` crashes with following logs:

```
npm ERR! code 1
npm ERR! path /Users/jurajcarnogursky/ooo/vette/monorepo/node_modules/svgo/node_modules/coa
npm ERR! command failed
npm ERR! command sh -c start /B node compile.js & node compile.js
npm ERR! sh: start: command not found
npm ERR! internal/modules/cjs/loader.js:905
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module '/Users/jurajcarnogursky/org/org/org/node_modules/svgo/node_modules/coa/compile.js'
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
npm ERR!     at internal/main/run_main_module.js:17:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jurajcarnogursky/.npm/_logs/2021-11-04T13_52_16_613Z-debug.log
```

**Comment by Chris-LuYi** [comment]
I have similar issue 

`CREATE nx-app/nx.json
CREATE nx-app/package.json
CREATE nx-app/README.md
CREATE nx-app/tools/generators/.gitkeep
CREATE nx-app/tools/tsconfig.tools.json
CREATE nx-app/tsconfig.base.json
CREATE nx-app/.editorconfig
CREATE nx-app/.gitignore
CREATE nx-app/.prettierignore
CREATE nx-app/.vscode/extensions.json
CREATE nx-app/workspace.json
CREATE nx-app/.prettierrc
CREATE nx-app/apps/.gitkeep
CREATE nx-app/libs/.gitkeep

> coa@2.1.3 preinstall D:\SourceCode\Playground\nx-app\node_modules\coa
> start /B node compile.js & node compile.js


npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated ecstatic@3.3.2: This package is unmaintained and deprecated. See the GH Issue 259.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'D:\SourceCode\Playground\nx-app\node_modules\coa\compile.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'D:\SourceCode\Playground\nx-app\node_modules\coa\compile.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.3.2 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! coa@2.1.3 preinstall: `start /B node compile.js & node compile.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the coa@2.1.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chris\AppData\Roaming\npm-cache\_logs\2021-11-04T13_55_01_981Z-debug.log
Command failed: npm install
`

**Comment by Durisvk** [comment]
I tried it like a week ago and it used to work. Something had to break recently.

Two possible things that might have gone wrong are either this update 7 days ago:
https://github.com/nrwl/nx/commit/89fc04da72ea612a21af6de75863005265fdc371 
@gperdomor @vsavkin 

or this update followed by a release:
https://github.com/svg/svgo/commit/cb7e9be623b6e2fbbfcb9b67c4c85131e1477925
https://github.com/svg/svgo/commit/b37d90e12a87312bba87a6c52780884e6e595e23

cause the error starts with:
```
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
```

**Comment by Joroze** [comment]
This is apparently now fixed. https://github.com/veged/coa/issues/99#issuecomment-961058779

**Comment by kirjai** [comment]
thanks for bringing this up, everyone!
I have given creating a new nextjs app with styled-components a try, and given that https://github.com/veged/coa/issues/99 is resolved now, looks like this can be closed now.

please let me know if that's not the case for anyone, and i'll reopen
