### ISSUE TITLE
"angularCompiler.getNextProgram is not a function" when updating from nx 12 to nx 12.10 (or 13)

### ISSUE THREAD

**Issue by FunnyGhost** [nrwl/nx#7618]
## Current Behavior

If I try to update using the `nx migrate latest`  command, it all succeeds, but when I do `npm start`, it fails with `TypeError: angularCompiler.getNextProgram is not a function`

### Failure Logs

`⠋ Generating browser application bundles...(node:30448) UnhandledPromiseRejectionWarning: TypeError: angularCompiler.getNextProgram is not a function
    at /Users.../node_modules/@ngtools/webpack/src/ivy/plugin.js:390:61
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:30448) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30448) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠙ Generating browser application bundles (phase: building)...(node:30448) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)`

### Environment

So, everything Angular is going from `11.2.0` to `12.2.13`
However, `@angular-builders/custom-webpack` is not changing version(stays at `11.1.1` and `@angular-devkit/build-angular` changes from `~0.1102.0` to `12.2.13`

`
  Node : 14.17.0
  OS   : darwin x64
  npm  : 6.14.13

  nx : Not Found
  @nrwl/angular : 13.1.3
  @nrwl/cli : 13.1.3
  @nrwl/cypress : 13.1.3
  @nrwl/devkit : 13.1.3
  @nrwl/eslint-plugin-nx : 13.1.3
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.3
  @nrwl/linter : 13.1.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 13.1.3
  @nrwl/nx-cloud : 12.5.2
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.3
  @nrwl/web : Not Found
  @nrwl/workspace : 13.1.3
  @nrwl/storybook : 13.1.3
  @nrwl/gatsby : Not Found
  typescript : 4.3.5`

**Comment by AgentEnder** [comment]
Hey, does bumping the @angular-builders/custom-webpack fix this? It could be caused by a mismatch

**Comment by FunnyGhost** [comment]
> Hey, does bumping the @angular-builders/custom-webpack fix this? It could be caused by a mismatch

Updating to `12.1.3` gives this error: 
```
Cannot find module 'webpack'
Require stack:
- /Users/.../node_modules/webpack-dev-server/lib/Server.js
- /Users/.../node_modules/@angular-devkit/build-angular/node_modules/@angular-devkit/build-webpack/src/webpack-dev-server/index.js
- /Users/.../node_modules/@angular-devkit/build-angular/node_modules/@angular-devkit/build-webpack/src/index.js
- /Users/.../node_modules/@angular-devkit/build-angular/src/browser/index.js
- /Users/.../node_modules/@angular-devkit/build-angular/src/index.js
- /Users/.../node_modules/@angular-builders/custom-webpack/dist/dev-server/index.js
- /Users/.../node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /Users/.../node_modules/@angular-devkit/architect/node/index.js
- /Users/.../node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
- /Users/.../node_modules/@nrwl/tao/src/commands/run.js
- /Users/.../node_modules/@nrwl/tao/index.js
- /Users/.../node_modules/@nrwl/cli/lib/run-cli.js
