### ISSUE TITLE
Nrwl React Storybook Preset: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by amosbastian** [nrwl/nx#7640]
## Current Behavior
Currently when following [this](https://nx.dev/l/r/storybook/migrate-webpack-final) to upgrade my Storybook configuration I get the following error after adding the new `@nrwl/react/plugins/storybook` preset to the addons:

```
It looks like you use Webpack 5 but your Storybook setup is not configured to leverage that
and thus falls back to Webpack 4.
Make sure you upgrade your Storybook config to use Webpack 5.

  - https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324#upgrade


info => Loading presets
info => Loading Nrwl React Storybook preset from "@nrwl/react/plugins/storybook"
TypeError: Cannot read property 'includes' of undefined


          Broken build, fix the error above.
          You may need to refresh the browser.
```

It is also strange I am getting the warning about Webpack 4, since I have set the builder to Webpack 5 in each `main.js` file.

## Expected Behavior

It should load the preset properly and Storybook should run fine.

## Steps to Reproduce

https://github.com/amosbastian/boilerplate/tree/chore/nrwl-13

```
nx serve shared-storybook:storybook
```

### Environment

```
  Node : 14.16.1
  OS   : darwin x64
  npm  : 7.20.5

  nx : 13.1.3
  @nrwl/angular : Not Found
  @nrwl/cli : 13.1.3
  @nrwl/cypress : 13.1.3
  @nrwl/devkit : 13.1.3
  @nrwl/eslint-plugin-nx : 13.1.3
  @nrwl/express : 13.1.3
  @nrwl/jest : 13.1.3
  @nrwl/linter : 13.1.3
  @nrwl/nest : Not Found
  @nrwl/next : 13.1.3
  @nrwl/node : 13.1.3
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 13.1.3
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.3
  @nrwl/web : 13.1.3
  @nrwl/workspace : 13.1.3
  @nrwl/storybook : 13.1.3
  @nrwl/gatsby : Not Found
  typescript : 4.4.4
  ```

**Comment by mandarini** [comment]
Hi there @amosbastian ! Does your issue still persist?

**Comment by mandarini** [comment]
Hi there @amosbastian , thanks for filing this issue! I just finished looking into it more, I just wondered if your issue persisted since I saw you had updated your workspace, but I verified that it still persists! I just pushed a PR that should be able to capture the fact that you're using `webpack5` and also not throw `includes of undefined`.  Thanks, both of these were a good catch! :)

**Comment by amosbastian** [comment]
Thanks a lot for the quick fix @mandarini!
