### ISSUE TITLE
101 Tutorial failed

### ISSUE THREAD

**Issue by pixycz** [nrwl/nx#7641]
## Current Behavior

https://nx.dev/l/n/tutorial/01-create-application – I run `npx create-nx-workspace` and I don't get any prompt like "What to create in the new workspace" as in the video. The workspace is created, there are empty `./app` and `./lib` folders, but **I have no idea how to create my first application.**

## Expected Behavior

I expect the tutorial and the real life usage will match. I also expect tutorial are for newbies not familar with the subject. I know nothing about NX but I want to try it and learn it. But then I fail completely on the very first basic tutorial.

## Steps to Reproduce

Repeat steps exactly as in the tutorial.

### Environment

```
pixy$ nx report

>  NX  Report complete - copy this into the issue template

  Node : 12.18.3
  OS   : darwin x64
  npm  : 6.14.6
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 13.1.3
  @nrwl/cypress : Not Found
  @nrwl/devkit : 13.1.3
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.3
  @nrwl/linter : 13.1.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.3
  @nrwl/web : Not Found
  @nrwl/workspace : 13.1.3
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by mandarini** [comment]
Hi there @pixycz ! Thanks for filing an issue, that bug you run into must be frustrating. Can you please do me a favor? Can you please run 
```
npx create-nx-workspace
```

And let me know if your experience is NOT the following:
1. You get asked to provide a workspace name, and you provide one (see screenshot below)
```
Workspace name (e.g., org name)
```
2. Right after that, you get asked
```
What to create in the new workspace
```
(like the screenshot)

![Screenshot 2021-11-10 at 11 36 56 AM](https://user-images.githubusercontent.com/6603745/141088254-48a64767-3304-45af-a9b1-a08db3b333e1.png)

Your experience was NOT the above? Maybe you accidentally hit ENTER twice when providing the workspace name, and you unwillingly chose the first option which was "`empty`"? This would explain why you have empty `apps` and `libs` directories in your new workspace.

Let me know if you experienced something different, and thank you for choosing Nx!

**Comment by pixycz** [comment]
Hello!

Yes, this works exactly as you say:

<img width="933" alt="Screenshot 2021-11-11 at 1 19 20" src="https://user-images.githubusercontent.com/3990823/141214607-7b670183-99f9-4716-9102-203858d28583.png">
<img width="932" alt="Screenshot 2021-11-11 at 1 19 45" src="https://user-images.githubusercontent.com/3990823/141214626-5cd1a67c-4a84-48c3-b7eb-985c84e7f3b0.png">
<img width="933" alt="Screenshot 2021-11-11 at 1 21 21" src="https://user-images.githubusercontent.com/3990823/141214632-eb752261-4ba3-4e36-8b84-b9e4716a6e96.png">

But that wasn't the point. The point is, a question "What to create in the new workspace" should follow to create a new app. It didn't. The workspace has been created but I have no idea how to create a new app. 

According to your tutorial I should have seen this:

<img width="1268" alt="Screenshot 2021-11-11 at 1 29 52" src="https://user-images.githubusercontent.com/3990823/141215290-6460a527-f63f-45d2-91f0-fac8782d1209.png">

I believe I followed your tutorial correctly (except the NX cloud option) but I've got different results. And I couldn't find another option to create a new app than this.

**Comment by linbudu599** [comment]
@pixycz After creating empty workspace, you can install target framework integration with nx, like `@nrwl/react` `@nrwl/express`, then you can run `nx g @nrwl/react:app your-react-app` to create a react application.

**Comment by pixycz** [comment]
I don't get it. I don't want any React or another framework. I need just to setup my new vanilla/ES6 project.

**Comment by mandarini** [comment]
Hi there @pixycz ! Thanks for following up, and apologies for taking too long to answer, I was OOO. 
From your screenshot, I see that for the question
```
What to create in the new workspace
```
which means "what kind of application to create in the new workspace", you chose `empty`.
<img width="437" alt="Screenshot 2021-11-17 at 10 07 03 AM" src="https://user-images.githubusercontent.com/6603745/142160256-e331528f-2edb-4d55-9fec-4e0cea3964a0.png">

This means that it will not create an application, so it will not ask you about the application name, since there will be no application.

In the tutorial you are following, and the tutorial screenshot that you provided here:
<img width="586" alt="Screenshot 2021-11-17 at 10 07 52 AM" src="https://user-images.githubusercontent.com/6603745/142160377-4cd16f67-ec53-4ade-8c28-821782a177d0.png">

the `nest` option is chosen, meaning that Nx will create a nest application, and ask you for a name.

So, can you please try once more, following the steps of the tutorial, and please let me know if the issue persists!

Thank you so much!

**Comment by pixycz** [comment]
OK, I understand I missed the selection in the tutorial. It's so quick it seems the "empty" option was selected.

Anyway, I still have no idea how to create a new app within my new workspace. That tutorial is the only information about the topic "how to create a new application" in the documentation. Can you advice me: If I've created the empty workspace, how can I create a new app (like those "todos" in your tutorial). I couldn't find any clue in the documenation.

**Comment by mandarini** [comment]
Hi there @pixycz !

Here's a link from our documentation explaining [how to generate a new application in your empty workspace](https://nx.dev/l/a/examples/react-and-angular).

In general, in an empty workspace, you will need to add one of our framework packages (eg. `yarn add -D @nrwl/angular`) and then you can generate an application using the[ application generator](https://nx.dev/l/a/angular/application) (`nx g @nrwl/angular:app my-app-name`).

Let me know if this helps!

**Comment by pixycz** [comment]
I'm affraid it didn't help at all. I'm not using React or Angular. I'm building a pure, frameworkless vanilla-JS application. However, it seems using [the similar step for Node](https://nx.dev/l/a/node/application) could be the right solution for me, I guess. 

In fact, the missing essential piece of information I was looking for was this: `nx generate application`. You've navigated me to it to the deep of the documentation and I guess this is it. Anyway, it's missing in the 101 tutorial, that's the problem. If someone wants to use a plain JS without any framework, they will fail with the tutorial, like me – esp. if someone is a newbie like me, knowing zero about NX. I believe it would be useful to add this hint to the tutorial.
