### ISSUE TITLE
Nx 13 commands failing on CI (Gitlab) without errors

### ISSUE THREAD

**Issue by edriang** [nrwl/nx#7648]
## Current Behavior

After migrating to nx v13, some graph-related nx commands no longer work.

The following is a list of different commands I tried. What is weird, is that none of them throws any error nor logs any message (this 5-lines output is taken directly from the GitlabCI output terminal):

```
$ nx affected:libs --base=HEAD~20 --head=HEAD --verbose --skip-nx-cache
$ nx affected:apps --base=HEAD~20 --head=HEAD --verbose --skip-nx-cache
$ nx run pedixapp:build:develop --verbose --skip-nx-cache
$ NX_VERBOSE_LOGGING=true nx affected --target=build --configuration=development --base=HEAD~25 --head=HEAD --verbose --skip-nx-cache
$ NX_VERBOSE_LOGGING=true nx run-many --all --target=build --configuration=development --verbose --skip-nx-cache
```

## Expected Behavior

Before migrating to v13, I was using v12.9.0. The following command worked properly on the CI (building the affected apps and libs for a given pushed commit):

`nx affected --target=build --configuration=development --base=HEAD~1 --head=HEAD`

## Steps to Reproduce

Nx 13 is working properly on my local machine. I tried many different stuff and commands but the result is empty output when running on Gitlab CI.

I've tried both with old and new project structure.

I don't know if this is CI-related only, but at least NX should be throwing/logging something, which it doesn't (even if I'm including the `--verbose` flag).

Is there any other place I could check to look for errors?

### Failure Logs

None

### Environment

Gitlab CI job is running on a custom Docker image, but there is nothing special about it:

```
FROM google/cloud-sdk:alpine

RUN apk add --no-cache --update \
  nodejs \
  npm \
  shadow \                                                                   
  gcc \                                                                                         
  musl-dev \                                                                                    
  autoconf \                                                                                    
  automake \                                                                                    
  make \                                                                                        
  libtool \                                                                                     
  nasm \                                                                                        
  tiff \                                                                                        
  jpeg \                                                                                        
  zlib \                                                                                        
  zlib-dev \                                                                                    
  file \                                                                                        
  pkgconf

COPY package.json package-lock.json ./

RUN export NODE_OPTIONS='--max-old-space-size=4096' && \
  npm set unsafe-perm true && \
  npm ci --cache /usr/local/.npm --prefer-offline
```

```
Node : 14.18.1
  OS   : linux x64
  npm  : 6.14.15
  
  nx : 13.1.3
  @nrwl/angular : 13.1.3
  @nrwl/cli : 13.1.3
  @nrwl/cypress : 13.1.3
  @nrwl/devkit : 13.1.3
  @nrwl/eslint-plugin-nx : 13.1.3
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.3
  @nrwl/linter : 13.1.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 13.1.3
  @nrwl/nx-cloud : 12.5.2
  @nrwl/react : 13.1.3
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.3
  @nrwl/web : 13.1.3
  @nrwl/workspace : 13.1.3
  @nrwl/storybook : 13.1.3
  @nrwl/gatsby : 13.1.3
  typescript : 4.3.5
```

**Comment by anneau** [comment]
same as https://github.com/nrwl/nx/issues/7536 ?

maybe i have same issue.  

nx build works on local, but on gitlab ci not works

**Comment by AgentEnder** [comment]
Its very possible this is the same issue @anneau mentioned, I'm going to mark this as blocked to retry after the next release since the fix for #7536 has already been merged.

**Comment by edriang** [comment]
Thanks @anneau and @AgentEnder for the very quick reply!

@AgentEnder , is there any ETA for the new version to be released?

**Comment by rrjohnson85** [comment]
@AgentEnder do you have a sense if the changes will be included in a patch release for 13.1 or only available in 13.2?

**Comment by AgentEnder** [comment]
@rrjohnson85 This should be in 13.1.4, which should be releasing soon 😅

**Comment by AgentEnder** [comment]
With 13.1.4 released, this should be fixed now. Im going to close the issue, leave a comment and we can reopen if needed.
