### ISSUE TITLE
Importmap rather than tsconfig paths

### ISSUE THREAD

**Issue by nordfjord** [nrwl/nx#7650]
## Description
[Import-maps](https://github.com/WICG/import-maps) is an emerging standards based way to control javascript import behavior.

I would like to propose that nx move towards using a single `importmap.json` file in the root of the workspace to specify paths resolution rather than using `tsconfig.base.json`'s `paths` property.

## Motivation
Import-maps are becoming more widely used. Deno for example has [built-in support](https://deno.land/manual/linking_to_external_code/import_maps) for them.

They also align with design decisions made by nx such as "everything must only import the index file of a module".

## Suggested Implementation
1. Create an import map.json migration from `/tsconfig.base.json` paths
2. Use a webpack resolver that handles import maps

**Comment by DaSchTour** [comment]
How well does the TypeScript compiler and IDEs support this new format?
