### ISSUE TITLE
Error adding nrwl/workspace (prettier)

### ISSUE THREAD

**Issue by Leio99** [nrwl/nx#7651]
## Current Behavior

I'm trying to transform my angular project using nx. I ran this command `npx make-angular-cli-faster` with success.
When running the second command `ng add @nrwl/workspace`, but it fails, showing the following error:
`generateFiles: No files found in "/myproject/angular/node_modules/@nrwl/workspace/src/generators/init/files/prettier". Are you sure you specified the correct path?`

## Expected Behavior

Converting my project with nx.

## Steps to Reproduce

Run `ng add @nrwl/workspace` in already existing angular project.

### Failure Logs

`No e2e project was migrated because there was none declared in angular.json
generateFiles: No files found in "myproject/angular/node_modules/@nrwl/workspace/src/generators/init/files/prettier". Are you sure you specified the correct path?`

### Environment

Angular 12.2.1
Nrwl cli 13.1.3

**Comment by sean-rowe** [comment]
I see this is closed, but I'm seeing this same issue with the latest angular. What is the fix?

**Comment by whimzyLive** [comment]
I am seeing this issue as well. 😢️

**Comment by jkonst** [comment]
I can confirm this issue also.

**Comment by palmtreefrb** [comment]
Same issue here.

**Comment by wkaskie** [comment]
Can this be reopened? I'm new to Nx and step one has failed.

**Comment by michaelbuller** [comment]
Seeing same issue
The package @nrwl/workspace@13.4.3 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.
No e2e project was migrated because there was none declared in angular.json
generateFiles: No files found in "/node_modules/@nrwl/workspace/src/generators/init/files/prettier". Are you sure you specified the correct path?

**Comment by ax2k** [comment]
I fixed it on my side by adding the file .prettierignore to the root of my project. Hope it can help !

**Comment by pacoita** [comment]
> I fixed it on my side by adding the file .prettierignore to the root of my project. Hope it can help !

I can confirm that adding an empty `.prettierignore` file at root level (as suggested by @ax2k ) made the schamatic command complete successfully in my existing angular project. 

Now apps/ and libs/ folders are correctly created and all files scaffolded as expected.

angular v 13.0.3
nrwl/workspace 13.4.3

**Comment by yusijs** [comment]
I tried adding a .prettierignore and, well...

> ➜ ng add @nrwl/workspace
> Skipping installation: Package already installed
> Cannot read properties of undefined (reading 'options')

**Comment by mburger81** [comment]
empty .prettierignore works also for me
