### ISSUE TITLE
Problem if build for master

### ISSUE THREAD

**Issue by tamtakoe** [nrwl/nx#7653]
I use this command for build after each commit
```
nx affected:build --base=remotes/origin/master --configuration=production
```
It works for any branch except `master` on build server. If I commit to `master` I see
```
NX No projects with "build" that are configured for "production" were run
```
But I don't see any errors and build looks like OK. Of course application doesn't work because of `/dist` folder doesn't exist

**Comment by AgentEnder** [comment]
Hey @tamtakoe. When you are running `nx affected:build --base=master` on master, no projects have changed, so no projects are built. 

Generally, teams take 1 of 2 approaches depending on their workflow
```
nx affected:build --base=remotes/origin/master~1 --configuration=production
```
or 
```
nx affected:build --base=$LAST_SUCCESSFUL_BUILD --configuration=production
```

If using the second option, you have to figure out how to get that last successful variable set since its not something Nx itself handles. We have a few things that can help with that part.
- https://github.com/nrwl/nx-tag-successful-ci-run
- https://github.com/nrwl/nx-orb

**Comment by tamtakoe** [comment]
Way with placeholder is not universal and not suitable for many cases.
`--base=remotes/origin/master~1` or `master~2` doesn't work also in my CI system.

How can I see which BASE and HEAD commit hash were actually used by NX? Maybe it has some debug flag?

**Comment by AgentEnder** [comment]
BASE / HEAD are all handled from git, not within Nx. If you don't give Nx a base, it will default to whatever is specified in nx.json, or `main` if nothing is specified. The arguments you pass are direct references to a commit via git, to see more info on the commit you are specifying you could use something like this.

```shell
git log HEAD~1 -1 --pretty=oneline
```

Nx doesn't do anything special though, we use `git merge-base ${base} ${head}` to determine where the branch was created, and whats been changed on it.

**Comment by tamtakoe** [comment]
Im still investigating this issue for my CI. So I created the feature request to simplify this way https://github.com/nrwl/nx/issues/7696

**Comment by mklueh** [comment]
I'm having the same issue on master, however I'm using 

```
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        id: setSHAs
        with:
          last-successful-event: 'pull-request'
          main-branch-name: 'master'
```

and it produces

```
Run nrwl/nx-set-shas@v3
Run node $GITHUB_ACTION_PATH/dist/index.js *** master false pull-request . 
Run echo "Base SHA"
Base SHA
[8](https://github.com/.../actions/runs/.../jobs/...#step:5:9)b623f1c79ab63f373a6[20](https://github.com/.../actions/runs/.../jobs/...#step:5:23)927bacabc5a997b4cf

Head SHA
8b6[23](https://github.com/.../runs/.../jobs/...#step:5:26)f1c79ab63f373a620927bacabc5a997b4cf

Run echo "NX_BASE=8b623f1c79ab63f373a620927bacabc5a997b4cf" >> $GITHUB_ENV
NX_BASE and NX_HEAD environment variables have been set for the current Job
```

While `8b623f1c79ab63f373a620927bacabc5a997b4cf` pointing to the pull request commit containing changes of one app.

I even verified that adding another step to my workflow

```
      - name: Show head changes
        run: git show HEAD
```

showing the exact same commit `8b623f1c79ab63f373a620927bacabc5a997b4cf` with the expected changes

The nx affected command looks like this


```
      - name: Running some task
        run: |
          nx affected \
          --nx-bail \
          --parallel=3 \
          --target=some-task \
          --base=${{ steps.setSHAs.outputs.base }} \
          --head=${{ steps.setSHAs.outputs.head }}
```


and I'm only running on closed and successful pull requests


```
on:
  pull_request:
    branches:
      - "master"
      - "main"
    types: [ closed ]
```

**base and head are obviously the same SHA, is this wrong? Has base to be one commit behind?**
