### ISSUE TITLE
React native application generator using local file path to entry file

### ISSUE THREAD

**Issue by raymondpebble** [nrwl/nx#7678]
## Current Behavior
In Xcode -> Build Phases -> Bundle React Native code and images:
```
../node_modules/react-native/scripts/react-native-xcode.sh /Users/.../nx-prototype/apps/rn-app/src/main.tsx
```

This is a local path to the entry file which would not work if someone else checked out this code.

## Expected Behavior
The path to the entry file should be relative to the repo.

The migration [guide](https://blog.nrwl.io/introducing-react-native-support-for-nx-48d335e90c89#:~:text=We're%20very%20excited%20to,capabilities%2C%20including%20shared%20workspace%20libraries.) suggests doing:
```
export ENTRY_FILE=./apps/my-native-app/index.js
``` 

However this requires `xcodebuild` commands to be run from the root directory, not sure if there's a way to allow running from subfolders out of the box? E.g. if someone wants to use fastlane, it's common to run the fastlane commands from a ` fastlane` subfolder.

## Steps to Reproduce

Generate a fresh nx react native application.

### Environment
```
  Node : 16.13.0
  OS   : darwin arm64
  npm  : 8.1.0

  nx : 13.1.3
  @nrwl/angular : Not Found
  @nrwl/cli : 13.1.3
  @nrwl/cypress : 13.1.3
  @nrwl/devkit : 13.1.3
  @nrwl/eslint-plugin-nx : 13.1.3
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.3
  @nrwl/linter : 13.1.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 13.1.3
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.3
  @nrwl/web : 13.1.3
  @nrwl/workspace : 13.1.3
  @nrwl/storybook : 13.1.3
  @nrwl/gatsby : Not Found
  typescript : 3.9.10
```

**Comment by xiongemi** [comment]
maybe try to set ENTRY_FILE as `${PROJECT_DIR}/../index.js`
export ENTRY_FILE=${PROJECT_DIR}/../index.js

PROJECT_DIR should be the ios folder
