### ISSUE TITLE
(node:21000) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'rootpath/tsconfig.json'

### ISSUE THREAD

**Issue by benmed00** [nrwl/nx#7685]
## Current Behavior
when nx serve/build app 

nx serve <app>

It demande the existing of a "tsconfig.json" on the monorepo scope, normaly it shoudn't becose there is the "tsconfig.base.json"

_(node:27516) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'D:\WorkSpace\arcelor-monorepo\tsconfig.json'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.readJsonFile (D:\WorkSpace\arcelor-monorepo\node_modules\@nrwl\tao\src\utils\fileutils.js:16:26)
    at readRootTsConfig (D:\WorkSpace\arcelor-monorepo\node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:155:25)      
    at createProjectGraph (D:\WorkSpace\arcelor-monorepo\node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:59:26)     
    at Object.<anonymous> (D:\WorkSpace\arcelor-monorepo\node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:40:16)     
    at Generator.next (<anonymous>)
    at D:\WorkSpace\arcelor-monorepo\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (D:\WorkSpace\arcelor-monorepo\node_modules\tslib\tslib.js:113:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled 
promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). 
(rejection id: 2)
(node:27516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code._

## Expected Behavior
build smoothly

## Steps to Reproduce
I just created a component with nx and it want build 

### Failure Logs
![image](https://user-images.githubusercontent.com/17787436/141103364-8bf697e9-b753-49ac-ac5f-351525930f26.png)

### Environment
Windows 10
![image](https://user-images.githubusercontent.com/17787436/141103270-5d82b93c-fc31-41f0-8dc9-b2cd76a70a75.png)
![image](https://user-images.githubusercontent.com/17787436/141103295-4ffa3b23-cf62-436c-bcbb-0fc1c196cd06.png)

the result of `nx report` 
![image](https://user-images.githubusercontent.com/17787436/141146379-c44208bf-d646-4127-b23b-77d9b886e486.png)

**Comment by juristr** [comment]
Can you try to upgrade to at least v12.10 of Nx?

**Comment by christianallred** [comment]
Can you post the tsconfig.json of the project you're trying to build?

**Comment by AgentEnder** [comment]
Hey @benmed00 it looks like `nx report` failed due to a small typo. The full command should be `nx report`, not `nx repport {project}`. Do you care to try running it one more time?

**Comment by benmed00** [comment]
> 
> 
> Can you try to upgrade to at least v12.10 of Nx?

**Comment by benmed00** [comment]
> 
> 
> Can you try to upgrade to at least v12.10 of Nx?

It is already in version nx : 12

**Comment by benmed00** [comment]
> 
> 
> Can you post the tsconfig.json of the project you're trying to build?

tsconfig.json

{
    "projectType": "library",
    "root": "libs/features/webcares/material-creation",
    "sourceRoot": "libs/features/webcares/material-creation/src",
    "prefix": "wbc",
    "targets": {
        "test": {
            "executor": "@nrwl/jest:jest",
            "outputs": ["coverage/libs/features/webcares/material-creation"],
            "options": {
                "jestConfig": "libs/features/webcares/material-creation/jest.config.js",
                "passWithNoTests": true
            }
        },
        "lint": {
            "executor": "@nrwl/linter:eslint",
            "options": {
                "lintFilePatterns": [
                    "libs/features/webcares/material-creation/src/**/*.ts",
                    "libs/features/webcares/material-creation/src/**/*.html"
                ]
            }
        }
    },
    "tags": ["scope:shared", "application:webcares"]
}

**Comment by benmed00** [comment]
> 
> 
> Hey @benmed00 it looks like `nx report` failed due to a small typo. The full command should be `nx report`, not `nx repport {project}`. Do you care to try running it one more time?

Done

**Comment by AgentEnder** [comment]
Great, thanks. Like @juristr mentioned, can you retry with 12.10 or latest? This is something that may be fixed 😄

**Comment by w-hafner** [comment]
I have the same error, but it occurs when I try to move an existing component from my angular project to a library.
