### ISSUE TITLE
"@nrwl/cypress": "13.2.0-beta.2", "@nrwl/jest": "13.2.0-beta.3" don't work with angular 13

### ISSUE THREAD

**Issue by SvetlanaMuravlova** [nrwl/nx#7700]
**Current Behavior**
After updating our lib up to angular 13 with nx 13.2.0-beta.2 we are unavailable to run unit test (with jest) and e2e tests (with cypress).

**Steps to Reproduce**
I've tried to create a small repository with local reproducing such problems
https://github.com/SvetlanaMuravlova/angula-13/tree/nx-lib

branch nx-lib

we get such error from jest builder (only for libs testing) you are able to reproduce it with commands
`npm run test:lib` or `nx run first-lib:test`
![image](https://user-images.githubusercontent.com/83700465/141314339-b668b69e-80f8-44c6-8bd6-a50c3c046910.png)

the same error we get in our lib after library updating

Regarding e2e tests (with cypress), it can't compile any lib in nx workspace. Also can be tested in the same rep. Tests are default after command
`nx g @nrwl/cypress:cypress-project your-app-name-e2e --project=your-app-name`
Can be reproduce with commands
`npm run test:e2e` or `nx run test-project-e2e:e2e`

May be i do something wrong that is why i get such errors
I will be glad for any help)

**Environment**
"dependencies": {
    "@angular/animations": "~13.0.0",
    "@angular/common": "~13.0.0",
    "@angular/compiler": "~13.0.0",
    "@angular/core": "~13.0.0",
    "@angular/forms": "~13.0.0",
    "@angular/platform-browser": "~13.0.0",
    "@angular/platform-browser-dynamic": "~13.0.0",
    "@angular/router": "~13.0.0",
    "rxjs": "~7.4.0",
    "ts-jest": "^27.0.7",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.0.1",
    "@angular/cli": "~13.0.1",
    "@angular/compiler-cli": "~13.0.0",
    "@nrwl/angular": "13.2.0-beta.2",
    "@nrwl/cli": "13.2.0-beta.2",
    "@nrwl/cypress": "13.2.0-beta.2",
    "@nrwl/eslint-plugin-nx": "13.2.0-beta.2",
    "@nrwl/linter": "13.2.0-beta.2",
    "@nrwl/jest": "13.2.0-beta.3",
    "@types/jest": "^27.0.2",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "~4.33.0",
    "@typescript-eslint/parser": "~4.33.0",
    "cypress": "9.0.0",
    "eslint": "7.32.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "jest": "^27.3.1",
    "jest-createspyobj": "2.0.0",
    "jest-preset-angular": "^11.0.0-rc.3",
    "ng-packagr": "next",
    "ts-jest": "27.0.7",
    "typescript": "~4.4.3"
  }

**Comment by AgentEnder** [comment]
@SvetlanaMuravlova Did you use `nx migrate next` to update to the beta, or just bump package versions?

**Comment by SvetlanaMuravlova** [comment]
@AgentEnder, thank you for your reply, you know i did it for migration up to version 13.1 but not for beta versions.
On default project i can see cypress and jest tests are workable after migration, so i will close this issue
thank you for your help)
