### ISSUE TITLE
Migration from NX workspace 11.x to 13.x does not create `project.json` configuration files 

### ISSUE THREAD

**Issue by ThomasBurleson** [nrwl/nx#7715]
Using the latest npx command to create an Nx workspace with Next.JS 

```shell
npx create-nx-workspace next12-nx-workspace \
--preset=next \
--style=css \
--appName=demo12-w-nx
```

creates a workspace with @nrwl libs v11.x with a traditional `workspace.json` configuration.

I then upgrade to React 17, Next.js 12, and Nx 13.x using

```shell
nx migrate latest
npm i
nx migrate --run-migrations
```

Everything looks good and runs. Then I notice that my app and e2e-app do NOT have a `project.json` file. This improved approach has not been migrated. 

![image](https://user-images.githubusercontent.com/210413/141499909-1b5cda05-e484-4e3f-ab93-1be688d4b50b.png)

I would consider this a migration bug and it certainly will introduce future confusion.

**Comment by ThomasBurleson** [comment]
Also notice I used `npx create-nx-workspace ...`. So I expected the latest Nrwl libs, latest workspace structures and latest Next. Yet I had to run `nx migrate latest` to upgrade.  

Is this also a bug ?

**Comment by AgentEnder** [comment]
Hey @ThomasBurleson. `project.json` files are opt-in during migration, so to convert you can use the generator `nx g @nrwl/workspace:convert-to-nx-project --all`.

When using `npx create-nx-workspace ...` if you don't specify latest (`npx create-nx-workspace@latest ...`) npx will grab a cached version 😞. This can easily end up w/ the behavior you seen where you get an older workspace.
