### ISSUE TITLE
"affected:test" (and probably others) fail if the project doesn't have an "architect" assigned

### ISSUE THREAD

**Issue by juristr** [nrwl/nx#773]
I'm using Ionic 4 in my NX workspace. The current setup I'm using, has the project configured in `angular.json`, but didn't have the `architect` property defined.

As a result, executing the `affected:test` NX script (and maybe others as well) fails with "cannot read property 'build' of undefined" here in the `filter` function.

https://github.com/nrwl/nx/blob/d779d2bcc1b8a8c4153695bca56de59b0dfa5921/packages/schematics/src/command-line/shared.ts#L373-L376

Adding an empty `architect` property obviously works.

```
"ionic-project": {
    "root": "apps/ionic-project/",
    "sourceRoot": "apps/ionic-project/src",
    "projectType": "application",
    "prefix": "smartfed",
    "architect": {},
    "schematics": {
        "@schematics/angular:component": {
            "styleext": "scss"
        }
    }
}
```

The question is whether it is legit to have a project configured in the `angular.json` without a `architect` property specified. If so, I'd suggest to guard the NX script against that (I can provide a PR if desired)

**Comment by FrozenPandaz** [comment]
I suppose it is legitimate to have a project with no `architect` as per https://github.com/angular/angular-cli/blob/master/packages/angular/cli/lib/config/schema.json#L355. It would be best to throw a NullException error atm without an `architect` configuration. 

However, also in this space, the AngularCLI will switch to the `targets` configuration (same thing just a rename) _eventually_. (I am not quite sure when). At which time, reading configurations might be easier to be done via util method(s). @.@ We would want a util method for reading from `fs` as well as a `Tree`.
