### ISSUE TITLE
Misleading Workspace Library Documentation

### ISSUE THREAD

**Issue by Vlad1m1ru5** [nrwl/nx#7730]
# Steps to Reproduce

Follow the [example](https://nx.dev/l/r/workspace/library#examples) (<https://nx.dev/l/r/workspace/library#examples>) and run `nx g lib mylib --directory=myapp` inside existing nx workspace.

# Expected Behavior

Lib `mylib` created under `libs/myapp` folder.

# Current Behavior

As you can see from the following snippet lib `mylib` is **not** created under `libs/myapp` folder.

```sh
$ npx nx g lib mylib --directory=myapp
CREATE packages/myapp/mylib/project.json
UPDATE workspace.json
CREATE packages/myapp/mylib/.eslintrc.json
CREATE packages/myapp/mylib/.babelrc
CREATE packages/myapp/mylib/README.md
CREATE packages/myapp/mylib/src/index.ts
CREATE packages/myapp/mylib/tsconfig.json
CREATE packages/myapp/mylib/tsconfig.lib.json
UPDATE tsconfig.base.json
CREATE packages/myapp/mylib/jest.config.js
CREATE packages/myapp/mylib/tsconfig.spec.json
CREATE packages/myapp/mylib/src/lib/myapp-mylib.spec.tsx
CREATE packages/myapp/mylib/src/lib/myapp-mylib.tsx
```

## Report

```sh
  Node : 14.17.6
  OS   : linux x64
  npm  : 6.14.15
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 13.1.4
  @nrwl/cypress : 13.1.4
  @nrwl/devkit : 13.1.4
  @nrwl/eslint-plugin-nx : 13.1.4
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.4
  @nrwl/linter : 13.1.4
  @nrwl/nest : 13.1.4
  @nrwl/next : Not Found
  @nrwl/node : 13.1.4
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 13.1.4
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.4
  @nrwl/web : 13.1.4
  @nrwl/workspace : 13.1.4
  @nrwl/storybook : 13.1.4
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by AgentEnder** [comment]
It looks like you have 'packages' set as your libs folder in `nx.json`, which changes that base directory. Can you check this?

**Comment by Vlad1m1ru5** [comment]
@AgentEnder thanks for your reply!

It seams to me so that my `nx.json` does not explicitly sets `packages` as libs folder, but it extends `@nrwl/workspace/presets/npm.json` which does the same thing under the hood.

I was mislead with[React App](https://nx.dev/l/r/react/library) generator example and the [NX Core](https://nx.dev/l/r/getting-started/nx-core#creating-a-new-workspace) empty workspace generator example. The first one states that `libs` is expected to be in the workspace root folder, but the last one overrides this behavior with `packages`.

After the research it sims to me that `--preset=empty` is the solution for my problem here.

**Comment by AgentEnder** [comment]
Yeah, so the different presets can modify workspace layout, and using `--preset=npm` (previously `--preset=oss`) sets those to `packages`. I'm going to go ahead and close this issue, this is working as expected.

Let me know if there is anything further that I can answer 😄
