### ISSUE TITLE
migrations are not running sucessfully 13.2.0-rc.0

### ISSUE THREAD

**Issue by MRisto** [nrwl/nx#7731]
Hope im doing it right. First time reporting something here.
## Current Behavior

Migration "schematic-options-13" and others are not running

## Expected Behavior

Migration should run without a problem

## Steps to Reproduce

* Upgraded with nx migrate next
* npm i
* nx migrate --run-migrations=migrations.json

### Failure Logs

`Running migration schematic-options-13
Cannot find module '@angular-devkit/core'
Require stack:
- C:\Users\MRisto\AppData\Local\Temp\tmp-22100-kdLQajavTs0C\node_modules\@nrwl\tao\src\commands\ngcli-adapter.js
- C:\Users\MRisto\AppData\Local\Temp\tmp-22100-kdLQajavTs0C\node_modules\@nrwl\tao\src\commands\migrate.js
- C:\Users\MRisto\AppData\Local\Temp\tmp-22100-kdLQajavTs0C\node_modules\@nrwl\tao\index.js
D:\projects\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: C:\Users\MRisto\AppData\Local\Temp\tmp-22100-kdLQajavTs0C\node_modules\.bin\tao migrate --run-migrations=migrations.json
    at checkExecSyncError (child_process.js:640:11)
    at execSync (child_process.js:676:15)
    at Object.handler (D:\projects\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:124:42)
    at Object.runCommand (D:\projects\7.Galenos_Solutions\dytab\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (D:\projects\7.Galenos_Solutions\dytab\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (D:\projects\7.Galenos_Solutions\dytab\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:986:25)
    at initLocal (D:\projects\node_modules\@nrwl\cli\lib\init-local.js:28:79)
    at Object.<anonymous> (D:\projects\bin\nx.js:43:32)
    at Module._compile (C:\Users\MRisto\AppData\Roaming\npm\node_modules\@nrwl\cli\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 24140,
  stdout: null,
  stderr: null
}`

### Environment

`  Node : 14.17.0
  OS   : win32 x64
  npm  : 7.24.2

  nx : 13.2.0-rc.0
  @nrwl/angular : 13.2.0-rc.0
  @nrwl/cli : 13.2.0-rc.0
  @nrwl/cypress : 13.2.0-rc.0
  @nrwl/devkit : 13.2.0-rc.0
  @nrwl/eslint-plugin-nx : 13.2.0-rc.0
  @nrwl/express : undefined
  @nrwl/jest : 13.2.0-rc.0
  @nrwl/linter : 13.2.0-rc.0
  @nrwl/nest : 13.2.0-rc.0
  @nrwl/next : undefined
  @nrwl/node : 13.2.0-rc.0
  @nrwl/nx-cloud : 12.5.2
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.0-rc.0
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.0-rc.0
  @nrwl/storybook : 13.2.0-rc.0
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.0
         @angular/cdk: 13.0.0
         @angular/common: 13.0.0
         @angular/compiler: 13.0.0
         @angular/core: 13.0.0
         @angular/forms: 13.0.0
         @angular/material: 13.0.0
         @angular/platform-browser: 13.0.0
         @angular/platform-browser-dynamic: 13.0.0
         @angular/router: 13.0.0
         @datorama/akita: 6.2.4
         @ngneat/helipopper: 4.1.1
         @ngneat/transloco: 2.22.0
         @angular-devkit/build-angular: 13.0.2
         @angular/cli: 13.0.2
         @angular/compiler-cli: 13.0.0
         @angular/language-service: 13.0.0
         @ngneat/spectator: 8.3.1
         @storybook/angular: 6.4.0-rc.1`

**Comment by tFaster** [comment]
I am having the same issue!
Seems that the node_modules in the generated temp folder (C:\Users\MRisto\AppData\Local\Temp\tmp-22100-kdLQajavTs0C) does not contain @angular-devkit/core (its not listen in its package.json, nor package-lock.json).
Shouldn't tao define it as dependency?

**Comment by juristr** [comment]
Can you try to set the `NX_MIGRATE_USE_LOCAL=true` environment variable and try again?

**Comment by tFaster** [comment]
Yes, @juristr this solves it at least for me! Thanks!

**Comment by juristr** [comment]
@tFaster thanks for trying. Yeah we're looking into why this happens 👍

**Comment by juristr** [comment]
We pushed a fix here: https://github.com/nrwl/nx/commit/3d54a7961aaa138ac6c48f05697a58b9ae19184d

**Comment by kentytik** [comment]
> Can you try to set the `NX_MIGRATE_USE_LOCAL=true` environment variable and try again?

This solved it. Thanks
