### ISSUE TITLE
Storybook on @nrwl/next:app

### ISSUE THREAD

**Issue by caenguidanos** [nrwl/nx#7735]
## Description
As far as i know, if we try to add storybook configuration, via @nrwl/react, to @nrwl/next:app in Nx 13.1.4, we receive an error at build time on storybook target because it seems that Storybook needs babel config like @nrwl/react:lib to build successfully but @nrwl/react:lib babel config is incompatible with @nrwl/next:app babel config.

## Motivation
Integration of Storybook workflow on @nrwl/next:app, for example, to run isolated pages.

## Suggested Implementation
Same process that runs @nrwl/react:storybook-configuration in @nrwl/next.

**Comment by puku0x** [comment]
I'm trying to integrate `@nrwl/next` and Storybook too. Here is a repo.
https://github.com/puku0x/nx-nextjs-storybook-sample

It seems it works for me but the best solution is to make `@nrwl/next` support Storybook, indeed.
