### ISSUE TITLE
DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead

### ISSUE THREAD

**Issue by viceice** [nrwl/nx#7739]
## Description

There is a new Node v16 warning, which can be easily fixed.

```
DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
```

https://github.com/nrwl/nx/blob/387af0cf3f92bb9dd20f39eccb349d766bd613bb/packages/react-native/src/utils/ensure-node-modules-symlink.spec.ts#L14
https://github.com/nrwl/nx/blob/387af0cf3f92bb9dd20f39eccb349d766bd613bb/packages/react-native/src/utils/ensure-node-modules-symlink.spec.ts#L41
https://github.com/nrwl/nx/blob/8d6ac4f694aa6050c0c57b9fd6e2fedf515988de/packages/angular/src/executors/ng-packagr-lite/ng-packagr-adjustments/write-package.ts#L204
https://github.com/nrwl/nx/blob/387af0cf3f92bb9dd20f39eccb349d766bd613bb/packages/react-native/src/utils/ensure-node-modules-symlink.ts#L42

## Motivation

Remove the deprecation noise 😉 

## Suggested Implementation

Simply replace token `rmdir` with `rm`.  

## Alternate Implementations

none

**Comment by DaiDai267** [comment]
Ummmm... Im still stuck, can anyone help me? What do I need to do?

**Comment by DaiDai267** [comment]
Hi, would anyone be able to assist me with the solution to this problem? I've been trying to solve it for a week now and finally decided to get some help. I'm a newbie to coding and the GitHub community so I'd greatly appreciate any help from y'all. 
Thank you :)

**Comment by geromegrignon** [comment]
Hi @DaiDai267, the current issue is about a warning which should not need to be solved on its own. There is nothing to fix on your side.

**Comment by DaiDai267** [comment]
Oh, I see. But my code isn't working (generating images), so what's the problem? Cheers

**Comment by IXC28** [comment]
lograste solucionar este error ?

**Comment by Angelje47** [comment]
need to solve it
