### ISSUE TITLE
Include devDependencies when building node with generatePackageJson and "production mode"

### ISSUE THREAD

**Issue by 7mllm7** [nrwl/nx#7740]
## Description
It might be useful to include devDependencies when building a node app / lib with `generatePackageJson` = `true` and when run without `--prod` or equivalent, or based on another flag.

## Motivation
In our case, we have an AWS Lambda project, and we want to be able to run a Lambda function locally (for example via [`sam local invoke`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-local-invoke.html) or [`sam local start-api`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-local-start-api.html)). For that to work, we need a proper build of our node app / lib. However, currently when using the `@nrwl/node:build` executor, and setting `generatePackageJson` to `true`, the generated package.json does not include used devDependencies - but we need it, as we're running stuff locally.

## Suggested Implementation
In [this line](https://github.com/nrwl/nx/blob/bea4ba22b189f4e89a92beeda32b44d35580df16/packages/node/src/utils/generate-package-json.ts#L14) we do `delete packageJson.devDependencies;`, and that's where it happens.

We should consider removing them only when `--prod` flag is up, or possibly based on some other flag that will come in `options: BuildNodeBuilderOptions`.

## Alternate Implementations
I'd suggest to extend the `generatePackageJson` configuration field to be a string (and not boolean), with values such as: `all`, `no-dev`, and even `none` (for cases where you just need the package's info, without deps 🤷🏽‍♂️.
However, this would be such a painful breaking change, so I'm not really suggesting it :).

**Comment by zyf0330** [comment]
I want this function. We need generated package.json to install typescript to build ts source files in the cloud docker build environment, so we need it includes devDependencies.

**Comment by zyf0330** [comment]
After comment `delete packageJson.devDependencies;`, generated package.json gives wrong `devDependencies` result which  doesn't include `typescript`.

**Comment by zyf0330** [comment]
I don't use `generatePackageJson` feature now, because I found that generated package.json doesn't include all prod dependencies.
