### ISSUE TITLE
"FORCE_NG_UPDATE=true ng update" not working

### ISSUE THREAD

**Issue by JosepAlacid** [nrwl/nx#7745]
## Current Behavior
Following instructions on nx command line help the command "FORCE_NG_UPDATE=true ng update" fails as 
```
'FORCE_NG_UPDATE' is not recognized as an internal or external command
```

## Expected Behavior

We expect to override the block on ng update command imposed by nx decoration. 
The error information and the advice should be clearly documented. 

## Steps to Reproduce

Not to much about how to reproduce this issue. Just use a PowerShell or Command Line to start a `ng update` command.

### Failure Logs

No logs recorded on Windows command line or powershell terminals. 

### Environment

```
  Node : 14.18.1
  OS   : win32 x64
  npm  : 8.0.0
 ...
```

**Comment by stefanmo** [comment]
I used the command on my project and it works. If you are using power shell I guess this is how you send the environment variable: https://stackoverflow.com/a/714918/6730157

**Comment by JosepAlacid** [comment]
Maybe it would be a good idea to improve the advise on the error message. Something like 
```
Set your console environement variable 'FORCE_NG_UPDATE' to true to allow the use of 'ng update'
```

**Comment by JelleBruisten** [comment]
I encountered this before if you want to FORCE_NG_UPDATE from powershell you have todo so like this:

`$Env:FORCE_NG_UPDATE = "true";`

**Comment by JosepAlacid** [comment]
I would like to change the TAG from `bug` to `improvement`, `feature request` or `documentation` but I'm not been able to.
