### ISSUE TITLE
Support Next.js 12.0.4

### ISSUE THREAD

**Issue by anneau** [nrwl/nx#7746]
## Description

Next.js 12.0.4 is released

https://github.com/vercel/next.js/releases/tag/v12.0.4

## Motivation

Next.js 12.0.4 supports some features and fix bugs.
so, I want to use Next.js 12.0.4

**Comment by sanders-vag** [comment]
Please, we would really appreciate it :), as we couldn't complete the upgrade due to a bug that's fixed in 12.0.4. Thanks!!!

**Comment by MitkoTschimev** [comment]
In my opinion, it is not even a feature because static site generation is broken till 12.0.4
This means If I do the upgrade to nx 13 with nextjs 12.0.0
 I have a broken application

**Comment by MitkoTschimev** [comment]
Thanks a lot for the quick reaction and solving the problem! Can't wait for the next release ❤️
