### ISSUE TITLE
jest is not well configured by npx create-nx-workspace --preset=angular 

### ISSUE THREAD

**Issue by adnanebrahimi** [nrwl/nx#7750]
Every time I create a new workspace with `npx create-nx-workspace --preset=angular` the jest is not working

The jest import in the test-setup.ts file is different
jest.config.ts is different
and the` npm run test` or `nx test` is not working 

You can see my repo for more information
https://github.com/adnanebrahimi/nx-example-windows

##Environment:

Windows 10

node 16

npm 8

global angular cli 13

**Comment by puku0x** [comment]
It is well configured as far as I can see. What if you run `npx create-nx-workspace@latest --preset=angular` ?

![image](https://user-images.githubusercontent.com/2607019/142084816-967e9c4f-a375-4a1b-8829-2cd9906f0371.png)

```
% npx nx report

>  NX  Report complete - copy this into the issue template

  Node : 16.13.0
  OS   : darwin x64
  npm  : 8.1.0
  
  nx : 13.1.4
  @nrwl/angular : 13.1.4
  @nrwl/cli : 13.1.4
  @nrwl/cypress : 13.1.4
  @nrwl/devkit : 13.1.4
  @nrwl/eslint-plugin-nx : 13.1.4
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.4
  @nrwl/linter : 13.1.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.4
  @nrwl/web : Not Found
  @nrwl/workspace : 13.1.4
  @nrwl/storybook : 13.1.4
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by AgentEnder** [comment]
Hey @adnanebrahimi, looking at your repo it looks like your running Nx 11.1, this likely has been fixed and I cannot reproduce in latest Nx. Can you try with `npx create-nx-workspace@latest --preset angular`?

**Comment by adnanebrahimi** [comment]
Sure. I will retry with latest flag.

I normally use `npx create-nx-workspace --preset=angular`

You can see my CMD Screen shot in readme.md file as well

**Comment by adnanebrahimi** [comment]
Testing by `npx create-nx-workspace@latest --preset angular` works.

before generating the create-nx-workspace updated first:
![image](https://user-images.githubusercontent.com/5724920/142378812-af1d144a-6f35-4645-bd8b-52f35b89ac61.png)

Thanks everyone for helping me
