### ISSUE TITLE
Issue with parameters being passed into run-commands

### ISSUE THREAD

**Issue by craigbroadman** [nrwl/nx#7752]
## Current Behavior

When passing a parameter to a custom run-command the parameter is being passed through to every line in the array.

If one of the lines is a command that validates arguments the process fails with an **"unrecognized option"** error

## Expected Behavior

To be able to ignore the parameter.

## Steps to Reproduce

Setup a custom run command such as:

```
"my-custom-command": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "commands": [
          "echo {args.myParam}",
          "cd dist"
        ],
        "cwd": "microservices/apply/apply-api-iac",
        "parallel": false
      }
    }
```

Run the command with a parameter. For example:
`npx nx affected --target=my-custom-command  --base=origin/main --myParam=hello`

This fails on the "ls" command with an error **"unrecognized option --myParam=hello"** because the "myParam" parameter is passed to every line, effectively running `ls myOutputs --myParam=hello`

**Note:** The same error occurs if I run other commands such as chmod  or cat

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by craigbroadman** [comment]
I've also tried to move the commands to a single .sh script

However this errored with a permission error... I then tried adding a line to the beginning of the commands to set the permissions:

`chmod +x ./myscript.sh`

But this again failed with the **"unrecognized option --myParam=hello"** error

**Comment by craigbroadman** [comment]
I've managed to sort out the permissions out by following this article...

https://medium.com/@akash1233/change-file-permissions-when-working-with-git-repos-on-windows-ea22e34d5cee

However the bash script sees the parameter value as the whole "--myParam=hello" string rather than just the value of "hello"

**Comment by puku0x** [comment]
Does `"forwardAllArgs": false` help you?
https://nx.dev/l/r/workspace/run-commands-executor#arguments-forwarding

**Comment by craigbroadman** [comment]
> `false`

That works 👍 thank you

**Comment by chrisui** [comment]
I'd really like to re-open this and discuss alternatives (including workspace wide configuration) for this. The default behaviour of forwarding all args to every command that is run (even dependencies) is highly undesirable and the needs to swap between "commands" and "command" with a verbose syntax just to escape the default behaviour isn't great. I'd argue there's even security concerns with this default behaviour but I'm not an expert.

If I want to run target "A" and know args to pass I want only target "A" to receive those args. Right now every dependent target receives the same args.

Concrete example: `"nx run service:deploy --stack production --awsProfile service-deployer" --preview` etc. Deploy targets are dependent upon `"package" -> "build" -> "prepare"` and if I'm using run-commands for any of those they are receiving the args I was using for the `"deploy"` target and failing.

The ONLY way to make sure this doesn't happen is to add "forwardAllArgs" to *every* command by default and explicitly opt-in to that behaviour instead. I think this is a much much safer default. Right now my dependencies are at least failing with "unknown args" but one day someone is going to have a stray option which does not have the semantic intention they issues the nx command with.

**Comment by klemenoslaj** [comment]
> I'd really like to re-open this and discuss alternatives (including workspace wide configuration) for this. The default behaviour of forwarding all args to every command that is run (even dependencies) is highly undesirable and the needs to swap between "commands" and "command" with a verbose syntax just to escape the default behaviour isn't great. I'd argue there's even security concerns with this default behaviour but I'm not an expert.
> 
> If I want to run target "A" and know args to pass I want only target "A" to receive those args. Right now every dependent target receives the same args.
> 
> Concrete example: `"nx run service:deploy --stack production --awsProfile service-deployer" --preview` etc. Deploy targets are dependent upon `"package" -> "build" -> "prepare"` and if I'm using run-commands for any of those they are receiving the args I was using for the `"deploy"` target and failing.
> 
> The ONLY way to make sure this doesn't happen is to add "forwardAllArgs" to _every_ command by default and explicitly opt-in to that behaviour instead. I think this is a much much safer default. Right now my dependencies are at least failing with "unknown args" but one day someone is going to have a stray option which does not have the semantic intention they issues the nx command with.

I couldn't agree more. This really can be a security hazard.

Was there any progress on that?

To avoid breaking change I would at first I would recommend a global `forwardAllArgs` setting, to set the default value.

**Comment by chrisui** [comment]
@klemenoslaj opened new issue here https://github.com/nrwl/nx/issues/11384
