### ISSUE TITLE
creating a single @nrwl/linter:workspace-rule slows down eslint / linting significantly

### ISSUE THREAD

**Issue by riltsken** [nrwl/nx#7758]
## Current Behavior
Creating a `@nrwl/linter:workspace-rule` slows down linting significantly

## Expected Behavior
When creating a `@nrwl/linter:workspace-rule` it shouldn't multiply the lint time by a significant amount

## Steps to Reproduce
I created a repo here that reproduces the issue https://github.com/riltsken/nx-eslint-slow-test. In our case we have a much larger application and when generating a single custom rule it slows down lint times from 1m30s -> 4m. I suspect something is being compiled/ran several times over when using a custom workspace-rule but looking for some guidance here. The issue is mostly exacerbated by having a larger amount of libs/apps that live in a workspace

### Environment

Happy to share more here but I think the example repo should be enough?

**Comment by meeroslav** [comment]
Thank you @riltsken for reporting this,

I have updated your solution to the latest Nx version and reduced the project differences to workspace-lint only (you can find the fork here https://github.com/meeroslav/nx-eslint-slow-test).

The way `workspace-lint` rules work is by dynamically requiring the project at `tools/eslint-rules` and appending rules defined in `index.ts` as lint rules. Unfortunately, we use node's `require` which is very slow, and for your repository takes ~800ms per lint run (running lint for 10 projects means over 8sec in total). Even having the empty `eslint-rules` without rules would take a similar amount of time.

In comparison, `enforce-module-boundaries` takes ~200ms and that's just a single file in the already transpiled project.

Not sure if the re-loading of the `eslint-rules` can be avoided.

cc @vsavkin @JamesHenry

**Comment by JamesHenry** [comment]
Hmm yeah we can probably be a bit smarter about this.

My first thought is can we replace ts-node with one of the modern esbuild powered alternatives?

IIRC correctly exploring that at the time was not an option because they did not support custom path mappings from the tsconfig, which we need to be able to support.

Additionally, we can potentially look into leveraging the Nx project graph/caching in a smart way, because ultimately `tools/eslint-rules` is a project on the graph and we should be able to figure when its sources have changed (and thus only re-require it in those cases).

**Comment by meeroslav** [comment]
Yes, using something like `@swc-node/register` brings it back to normal values. This is the result running on the above-mentioned repo with 10 projects.

* No **`tools/eslint-rules`**:
```5.81s user 0.93s system 102% cpu 6.581 total```
* Using **`@swc-node/register`**:
```6.89s user 1.06s system 105% cpu 7.493 total```
* Using **`esbuild-runner`**:
```6.58s user 1.12s system 101% cpu 7.571 total```
* Using **`ts-node`**:
```23.69s user 1.67s system 156% cpu 16.218 total```

The second point can help with incremental runs, but would not help on cold start.

**Comment by riltsken** [comment]
amazing thank you so much! :partying_face:
