### ISSUE TITLE
The eslint rule `no-unreachable` should be available by default

### ISSUE THREAD

**Issue by xiejay97** [nrwl/nx#7759]
I found that `no-unreachable` is disabled in `plugin:@nrwl/nx/typescript`, maybe one of extends turn off it.

This means that when using the default config without explicitly turning off the `allowUnreachableCode` flag, no ESLint or TS errors will alert the developer of the presence of unreachable code.

**Comment by meeroslav** [comment]
It is switched off in the [@typescript-eslint/eslint-recommended](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/eslint-recommended.ts#L25). The reason for this is that the Typescript already covers this case during the transpilation (see TS 7027).

Did you find an issue with typescript not catching your unreachable code? In this case, please create an issue on https://github.com/typescript-eslint/typescript-eslint project and link this issue.
