### ISSUE TITLE
"lib" tsconfig.json and "base" tsconfig.json have different default "lib" configuration: ["dom", "es2018"] vs ["es2017", "dom"],

### ISSUE THREAD

**Issue by david-bulte** [nrwl/nx#7764]
## Current Behavior
Not sure whether this is a bug. When generating a lib, its tsconfig.json has a different "lib" configuration than the one in tsconfig.base.json.

tsconfig.base.json: "lib": ["es2017", "dom"],

tsconfig.json: "lib": ["dom", "es2018"]

## Expected Behavior

I would suggest that a lib-specific tsjson does not have an entry for "lib" (and "target") and that by default it just inherits these from the tsconfig.base.json?

But if it does have to have a lib entry of its own, it should (by default) be the same as the base one? Because certainly with buildable libs, this could result in slighly different behavior between ng serve and ng build?

### Environment
  Node : 14.15.3
  OS   : win32 x64
  npm  : 6.14.5

  nx : 13.1.4
  @nrwl/angular : 13.1.4
  @nrwl/cli : 13.1.4
  @nrwl/cypress : 13.1.4
  @nrwl/devkit : 13.1.4
  @nrwl/eslint-plugin-nx : 13.1.4
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.4
  @nrwl/linter : 13.1.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.4
  @nrwl/web : 13.1.4
  @nrwl/workspace : 13.1.4
  @nrwl/storybook : 13.1.4
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by Coly010** [comment]
The lib tsconfig's configuration will override the base config. This is fine. 
In a mixed repo, this makes a lot of sense because some apps/libs/frameworks may need to target different versions themselves without impacting other projects in the repo.

I hope this helps explain it a little! :)
