### ISSUE TITLE
createGlobPatternsForDependencies does not update with hot reload (for tailwind in JIT mode)

### ISSUE THREAD

**Issue by sjbuysse** [nrwl/nx#7768]
## Current Behavior
I use the `createGlobPatternsForDependencies` function in the tailwind config file, so that tailwind knows in which dependencies to look for its classes. When I serve my app, and import a new library afterwards (so the development build is already being served), it will not update the dependency array properly. The reason why I think it's an nx-issue rather than a tailwind issue, is that when I log out the result of `createGlobPatternsForDependencies`, it will not update properly. Only after stopping and re-serving the application, the new dependency is added to the array.
 
## Expected Behavior
* using `createGlobPatternsForDependencies` in your tailwind config file will get the new dependencies on a hot reload. 

## Steps to Reproduce
I've created a very minimal example based on the [nx tailwind guide](https://nx.dev/l/r/guides/using-tailwind-css-in-react).
You can find this minimal example here: https://github.com/sjbuysse/nx-tailwind-purging

My `tailwind.config.js` looks like this:
```
const { createGlobPatternsForDependencies } = require('@nrwl/react/tailwind');

module.exports = {
  purge: [
    './apps/minimal-example/src/**/*.{js,jsx,ts,tsx}',
    ...createGlobPatternsForDependencies(__dirname),
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  mode: 'jit',
  variants: {
    extend: {},
  },
  plugins: [],
};
```

## Result
* Run`yarn nx serve minimal-example`, you will have an empty app. Now go to `App.tsx` and import the `HelloWorld` component from the `hello-world` library (comment it out). 
* The green background in the `HelloWorld` component will not be shown after hot reload.

### Environment
macOS Big Sur

Here is a github repo again, if you missed it: 
https://github.com/sjbuysse/nx-tailwind-purging

**Comment by IgorKurkov** [comment]
this issue still exist, deps are not updated after hot reload in nx. Any ideas?
