### ISSUE TITLE
Error "Cannot read property 'toString' of null" when setting newProjectRoot

### ISSUE THREAD

**Issue by babeal** [nrwl/nx#777]
Versions
@nrwl/nx                                     6.3.1
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.2
@angular/cli                      6.1.2
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.2
@schematics/update                0.7.2

After generating a new project with the following command

```
ng new nx-cli-test --collection=@nrwl/schematics
```

and changing the "newProjectRoot" to anything other than empty string I get an error "Cannot read property 'toString' of null".

I would like nx to support custom directory structure since I want all src organized under the src folder.

**Comment by vsavkin** [comment]
Nx is an opinionated setup on top of the CLI. As with any opinionated approach, it may be limiting at times, but it simplifies a lot things for Nx devs and for Nx users. 

Custom project root is something that imo few will really benefit from, so at the moment we aren't planning to support it.

Thanks!

**Comment by spidermon** [comment]
In our project this issue was reproducible with latest angular cli and nx. Cause of issue was @angular/pwa package or some of 14 derived dependencies. I didn't dig deep enough but workaround is to delete @angular/pwa. Angular CLI with nx working after that as expected.

**Comment by intuvision** [comment]
> In our project this issue was reproducible with latest angular cli and nx. Cause of issue was @angular/pwa package or some of 14 derived dependencies. I didn't dig deep enough but workaround is to delete @angular/pwa. Angular CLI with nx working after that as expected.

I have found the same, in that @angular/pwa was the culprit for the issue:

https://github.com/nrwl/nx/issues/1367#issuecomment-515069767
