### ISSUE TITLE
Default NX13 React app production bundle does not work in IE11

### ISSUE THREAD

**Issue by jannisg** [nrwl/nx#7777]
## Current Behavior
When adding `IE 11` as a line item in the `.browserslistrc` file (as per the [docs](https://nx.dev/l/r/guides/browser-support#adding-support-for-ie-11)) and running a production build via `nx build`, I can see the `dist` folder output containing the expected `*.esm.js` and `*.es5.js` files. 
However the ES5 files _still contain arrow functions_ thus breaking IE11 compatibility which is throwing syntax errors when loading the ES5 files.

## Expected Behavior

I expect (as is asserted by the [docs](https://nx.dev/l/r/guides/browser-support#adding-support-for-ie-11)) that adding the IE11 browserslist item, the build output correctly transpiles the source code into an ES5 compatible output that runs in IE11 without syntax errors.

I have not personally used NX prior to version 13 so not entirely sure if it's a regression. I have seen some (closed) Github issues around this topic dating back to NX 10 but have no hands on experience with this.

## Steps to Reproduce

1. `npm install -g nx`
2. `npx create-nx-workspace --preset=react`
3. Edit `apps/{yourApp}/.browserslistrc` file to include `IE 11` as per https://nx.dev/l/r/guides/browser-support#adding-support-for-ie-11
4. `nx build`
5. Try to run dist output in IE11 or inspect es5 files in dist folder which also shows the arrow functions still being in the transpiled output.

Full **reproduction available** at: https://github.com/jannisg/nx-ie11-repro

Just run:
1. `npm ci`
2. `nx build`
3. inspect the es5 files or run dist output and load in IE11 browser

### Failure Logs
There are no explicit errors during the build, the output is generated but contains invalid syntax.

### Example of issue

**Arrow function contained in production build ES5 asset**
![image](https://user-images.githubusercontent.com/109211/142296853-20e06676-aa85-4ca9-b1fe-3feee41f8dbf.png)

Looking at the above ES5 output without optimisations enabled (ESM output) it appears that the arrow function is part of the webpack generated code:
![image](https://user-images.githubusercontent.com/109211/142297235-544145b6-22e3-4be3-851f-13e231a4b95b.png)

**IE11 Syntax error (expected given the arrow functions in the output)**
![image](https://user-images.githubusercontent.com/109211/142296922-6570673a-7f6b-40b8-b99b-d8d58b923d7c.png)

### Environment

```
>  NX  Report complete - copy this into the issue template

  Node : 14.16.0
  OS   : darwin x64
  npm  : 6.14.11
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 13.1.4
  @nrwl/cypress : 13.1.4
  @nrwl/devkit : 13.1.4
  @nrwl/eslint-plugin-nx : 13.1.4
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.4
  @nrwl/linter : 13.1.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 13.1.4
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.4
  @nrwl/web : 13.1.4
  @nrwl/workspace : 13.1.4
  @nrwl/storybook : 13.1.4
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by bansalrachita** [comment]
I faced a similar issue when upgrading from `Nx 12 + Webpack 4` to `Nx 13`, was able to fix it with specifying targets explicitly to `['web', 'es5']` in the `webpack.config.js`.

Reference: [https://webpack.js.org/migrate/5/#need-to-support-an-older-browser-like-ie-11](https://webpack.js.org/migrate/5/#need-to-support-an-older-browser-like-ie-11)

**Comment by jannisg** [comment]
Can confirm that setting the webpack `target` to include `'es5'` explicitly (`'web'`) appears to be the standard config from `@nrwl/react/plugins/webpack` will ensure the compiled output works as expected in IE11.

```js
const nrwlWebpackConfigFn = require("@nrwl/react/plugins/webpack")

module.exports = function(config) {
  // applying @nrwl/react webpack config (mutates config)
  nrwlWebpackConfigFn(config);

  // Explicitly setting target to produce IE11 compatible ES5 code:
  config.target = [
    'web',
    'es5',
  ];

  return config;
};
```

![image](https://user-images.githubusercontent.com/109211/144767886-d9e7a0ed-f4e5-432a-bd77-09e0742639a2.png)

**Comment by jannisg** [comment]
It's worth mentioning that setting `config.target` to either explicitly `'browserslist'` or deleting the target property entirely (`delete config.target`) in a custom webpack wrapper (as above) which is mentioned in the [migration docs](https://webpack.js.org/migrate/5/#need-to-support-an-older-browser-like-ie-11) @bansalrachita mentions above, ensures the browserlist config is correctly applied.

With the `config.target = "browserlist"` set, and the `.browserlistrc` file containing `IE 11`, it will produce valid `.es5.js` files. Without the `IE 11` line in `.browserlistrc` it will only generate `.esm.js` files.

It appears to me like the baseline configuration for NX's webpack config should be changed to `config.target: "browserlist"`.

**Comment by DrewBradley** [comment]
@jannisg Where are you creating that webpack wrapper in the NX workspace?

**Comment by DrewBradley** [comment]
@jannisg I tried making a webpack wrapper like you suggested above, but I am getting an error:
```Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.target should be one of these:
   "web" | "webworker" | "node" | "async-node" | "node-webkit" | "electron-main" | "electron-renderer" | "electron-preload" | function
   -> Environment to build for
   Details:
    * configuration.target should be one of these:
      "web" | "webworker" | "node" | "async-node" | "node-webkit" | "electron-main" | "electron-renderer" | "electron-preload"
    * configuration.target should be an instance of function```

**Comment by jannisg** [comment]
@DrewBradley Are you sure you have created the webpack config correctly and wired it up to the project in NX?

For reference, my `webpack.config.js` file is located in my `apps/myApp/src/` folder and then within the same folder, I have amended my `project.json` to point to this file instead of the `@nrwl/react/plugins/webpack` package:
```
"webpackConfig": "apps/myApp/webpack.config.js"
```

Beyond that I am not sure how I can help in this context.

**Comment by ymor** [comment]
@LeoLeal I don't suppose you can share your config? I've just hit both of the issues you mentioned. Thanks in advance.

**Comment by LeoLeal** [comment]
@ymor I have moved on from the project, so I dont have access to the codebase anymore to paste an example based on It, but essentially what I did was while extending webpack configuration, I placed a conditional on the ES5 one (it's available in the node-js runtime during build), and forcefully set the browserlists target to es5-only, and added a new mjs rule that copies the normal js rule from nx's webpack oob configuration. That made mjs files from apolllo client to transpile to es5.

**Comment by jaysoo** [comment]
We no longer support IE11, and most major frameworks do not either. There are ways to handle it with polyfills, but we dont' have the resources to maintain proper support.

If you want something out of the box, I encourage you to check out Vite + [@vitejs/plugin-legacy](https://www.npmjs.com/package/@vitejs/plugin-legacy). We have support for Vite so this could be a viable alternative to Webpack.
