### ISSUE TITLE
Move Generator does not auto update module file name & module name

### ISSUE THREAD

**Issue by RonanCodes** [nrwl/nx#7778]
If there is a reason for this behaviour, then perhaps add a checkbox to allow the auto update of the module name.
Many people use the default derived module name from folder dir nesting, so it needs to be updated when you move the lib.

## Current Behavior

Move Generator does not auto update module file name & module name

## Expected Behavior

Move Generator does auto update module file name & module name

## Steps to Reproduce

Use the Move generator.

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by FrozenPandaz** [comment]
Did you use `nx g @nrwl/angular:move`?

This one renames the module for Angular projects.

`nx g @nrwl/workspace:move` does not rename the angular modules.

Sorry if that is confusing.

**Comment by RonanCodes** [comment]
I just tried again using the angular generator, and that works.
Sorry, I thought I had run the angular move generator.
Thanks for verifying!

I wonder can any console output be given or when trying to use a workspace generator against an angular lib?

I have quite a big team, and this issue is going to pop up again and again.
