### ISSUE TITLE
Question: directory structure modifications

### ISSUE THREAD

**Issue by babeal** [nrwl/nx#778]
For some reason I am having a hard time finding the root source folders Apps and Libs in the sea of other top level folders.  I want to move apps and libs into a root folder src and then remove the src folders in each of the app folders and lib folders.  The only thing in the root of the app folder is the tsconfig.app.json and the tsconfig.spec.json so that shouldn't be a problem.  

I would like to know what I would be sacrificing by doing this.  If newProjectRoot would work properly I know that the schematics would generate libs and apps into the proper root src folder.  It seems that the inner "src" folder is hard coded and would need a custom schematic.  Is there anything else that i need to be aware of?  Is there anything coming down the pipe like upgrade tools that could make this a problem?  I could complete live with duplicated src folders src/apps/project/src if that makes it easier to stay compliant.

**Comment by vsavkin** [comment]
See the response here: https://github.com/nrwl/nx/issues/777

Thanks
