### ISSUE TITLE
generatePackageJson is not generating package.json in generated apps

### ISSUE THREAD

**Issue by AnubhutiRoX** [nrwl/nx#7784]
## Current Behavior
I am having three apps but one single package.json file at root.

## Expected Behavior
I want to deploy these three apps in three different pods so need to create three dockerfiles but at the same time i need individual package.json files

I am using nx 12 react>=17 
executor is build:web

**Comment by Itrulia** [comment]
I guess a duplicate of https://github.com/nrwl/nx/issues/6901 ?

**Comment by FrozenPandaz** [comment]
This option is not available for web builds and should not be necessary.

The built scripts have the `node_modules` bundled within the `js` files so you don't need to install anything for those scripts to run.

I would recommend you build on the host machine and move the resulting built files into the docker image.

Does that solve your issue?

**Comment by Mistic92** [comment]
I'm having the same issue on full backend app with nest.js. Every package.json in dist have empty dependencies

**Comment by gdubs** [comment]
> I'm having the same issue on full backend app with nest.js. Every package.json in dist have empty dependencies

did you ever find a way to generate your package.json using this property on a node/nestjs app?

**Comment by benja-lizarrraga** [comment]
I'm currently experiencing the same issue with nest js apps
