### ISSUE TITLE
NgRx Schematic: Use Enum for Action Names

### ISSUE THREAD

**Issue by vsavkin** [nrwl/nx#78]

**Comment by jaufgang** [comment]
Better yet,  consider adopting https://github.com/cartant/ts-action and https://github.com/cartant/ts-action-operators.  

Uses "action creators" which allow you to declare actions using a much less verbose syntax.  Also adds the `type` as a static property to the action, which allows you to filter  action types in your reducer using `Action.type`.  This gets rid of the need to export action names from your action file altogether, you only need to export the actions themselves.

**Comment by vsavkin** [comment]
We switched to using the default NgRx schematics fo generating actions. Our goal is to be as close to the default schematics as possible. Currently they use classes, but it may change in NgRx 6.  

Closing this issue.
