### ISSUE TITLE
Cypress: Angular v12: Fails compiling e2e tests with libs using 3rd party package

### ISSUE THREAD

**Issue by wimme** [nrwl/nx#7805]
## Current Behavior
In our e2e test, we're using types that are declared in one of our libraries. Some of these libraries use a module of a 3rd party npm package.
Running the test, it returns the error:

> An uncaught error was detected outside of a test:
>     Error: The following error originated from your test code, not from Cypress.
>
>  > The directive 'ResizedDirective' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.
>
> The directive is part of a library that has been partially compiled.
> However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.
> 
> Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
> Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
> or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
> 
> When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
> 
> Cypress could not associate this error to any specific test.
> 
> We dynamically generated a new test to display this failure.

Building the libs/apps works without issues in both production and development configurations. Only the compile of the e2e project seems to fail.
We're having the issue with several 3rd party packages, like 'angular-resize-event' and 'angular-gridster2'.

This used to work in previous versions (we encoutered this now as we are now trying to upgrade to v12).

## Expected Behavior
The e2e tests to compile and run in Cypress.

## Steps to Reproduce

1. Create a Nx workspace with Angular v12
2. Create an Angular lib with some custom types
3. Install a 3rd party Angular lib package, and import it in the Angular lib
4. Create an e2e test that uses a custom type from our Angular lib

Repro repo: https://github.com/wimme/nx-workspace-angular-v12
Run e2e of the 'dashboards-e2e' project

### Environment
>  Node : 16.13.0
>  OS   : win32 x64
>  npm  : 8.1.3
>
>  nx : 12.10.0
>  @nrwl/angular : 12.10.0
>  @nrwl/cli : 12.10.0
>  @nrwl/cypress : 12.10.0
>  @nrwl/devkit : 12.10.0
>  @nrwl/eslint-plugin-nx : 12.10.0
>  @nrwl/express : Not Found
>  @nrwl/jest : 12.10.0
>  @nrwl/linter : 12.10.0
>  @nrwl/nest : Not Found
>  @nrwl/next : Not Found
>  @nrwl/node : Not Found
>  @nrwl/nx-cloud : Not Found
>  @nrwl/react : Not Found
>  @nrwl/schematics : Not Found
>  @nrwl/tao : 12.10.0
>  @nrwl/web : Not Found
>  @nrwl/workspace : 12.10.0
>  @nrwl/storybook : 12.10.0
>  @nrwl/gatsby : Not Found
>  typescript : 4.3.5
>  Cypress : 8.7.0 with Electron 93

**Comment by FrozenPandaz** [comment]
The issue is this line here:

https://github.com/wimme/nx-workspace-angular-v12/blob/main/apps/dashboards/dashboards-e2e/src/integration/app.spec.ts#L2

You shouldn't be importing runtime code into your e2e tests in general. In some cases it might be alright, but Cypress is unable to process those Angular libraries so it's an issue.

I'd suggest if you need something specifically for runtime + e2e tests, that it is exposed in an import without any other runtime code.

**Comment by vincentpalita** [comment]
Hello! We are experiencing the same issue here. After looking around it seems that to be able to use such runtime code we would need to use the Angular Linked in the cypress webpack-preprocessor config.
Would it seems reasonable?

**Comment by vincentpalita** [comment]
Ok finally got it working, as mentioned in Angular documentation you can configure webpack to use they Angular Linker babel-loader when you need to run code that would for example import 3rd parties libraries that would be pre compiled such as @angular/core for example.

With the following conf in the plugins/index file our project is finally working again smoothly:

```
// ***********************************************************
// This example plugins/index.js can be used to load plugins
//
// You can change the location of this file or turn off loading
// the plugins file with the 'pluginsFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/plugins-guide
// ***********************************************************

const webpackPreprocessor = require('@cypress/webpack-preprocessor')
const { getWebpackConfig } = require('@nrwl/cypress/plugins/preprocessor')

function preprocess(config) {
  const webpackConfig = getWebpackConfig(config)

  webpackConfig.module.rules.push(
    {
      test: /\.mjs$/,
      loader: 'babel-loader',
      options: {
        configFile: false,
        plugins: ['@angular/compiler-cli/linker/babel'],
      },
    }
  )

  return async (...args) =>
    webpackPreprocessor({
      webpackOptions: webpackConfig,
    })(...args)
}

module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  on('file:preprocessor', preprocess(config))
}

```
