### ISSUE TITLE
Give the option to swap out the "Shared" folder name in the derived module name to use the given prefix instead

### ISSUE THREAD

**Issue by RonanCodes** [nrwl/nx#7809]
This issue is in relation to the auto derived module name creation when following the enterprise folder structure:
https://nx.dev/l/a/guides/monorepo-nx-enterprise

When you publish a lib in a shared folder the module has the word shared in it, which may not make sense outside of the Monorepo.
Ideally we could use some kind of prefix instead, or just remove the Shared keyword altogether.

## Description

Give the option to swap out the "Shared" folder name in the derived module name to use the given prefix instead

## Motivation

If you have a workspace called `spotify` with a shared folder for all your shared libs, and at this root level you use the prefix `spot`.
All of your derived modules will have "Shared" in the name, which doesn't really make sense outside of the Monorepo.
Much better would be if the Shared was swapped out for the Prefix used for the lib.

Example:
spotify/libs/shared/ui/album
Current auto derived module name: SharedUiAlbum
If we use the prefix instead of Shared it would become: SpotUiAlbum
Which is much better for consumers.

Going a level deeper, if you use the enterprise structure you may have a folder per app inside your libs folder (using prefix for the app folders), we would ideally like to remove the `Shared` prefix entirely, since we can assume it's shared since it has the `admn` prefix: 
spotify/libs/admn/shared/ui/album (prefix: admn)- > prefix: admn -> SharedAdmnUiAlbum
spotify/libs/desk/shared/ui/album (prefix: desk) -> SharedDeskUiAlbum

In this scenario we would have more folder per app section within each app grouping folder:
spotify/libs/admn/login/feature
spotify/libs/admn/payments/feature
Where each app section would have it's own custom prefix.

## Suggested Implementation

If we could have some kind of inputs on the lib generator to either remove the `Shared` keyword, or to swap the `Shared` keyword for the `prefix`.

**Comment by Coly010** [comment]
We have a flag `--simpleModuleName` which should aid you in removing the `shared-` prefix.
We also have a flag `--importPath` that should be used with publishable libraries to define a valid npm package name, allowing you to remove shared from the package name.
Finally, we have a `--prefix` flag that lets you define the prefix for the selectors for Components, Pipes, Directives etc of the library.

Thanks for raising the issue. I hope this clears up some confusion.
