### ISSUE TITLE
Prettier will try to fix files that it doesn't support with --target=lint --fix (yml file)

### ISSUE THREAD

**Issue by istvandesign** [nrwl/nx#7820]
## Current Behavior
When running `npx nx run-many --all --target=lint --fix ` prettier will try to fix even yaml files like .gitlab-ci.yml, which it can't and will fail with 

`Error: Command failed: node "../nxproject/node_modules/prettier/bin-prettier.js" --write "**/*{.js,._js,.bones,.cjs,.es,.es6,.frag,.gs,.jake,.jsb,.jscad,.jsfl,.jsm,.jss,.mjs,.njs,.pac,.sjs,.ssjs,.xsjs,.xsjslib,.wxs,.js.flow,.jsx,.ts,.tsx,.json,.avsc,.geojson,.gltf,.har,.ice,.JSON-tmLanguage,.mcmeta,.tfstate,.tfstate.backup,.topojson,.webapp,.webmanifest,.yy,.yyp,.jsonc,.sublime-build,.sublime-commands,.sublime-completions,.sublime-keymap,.sublime-macro,.sublime-menu,.sublime-mousemap,.sublime-project,.sublime-settings,.sublime-theme,.sublime-workspace,.sublime_metrics,.sublime_session,.json5,.css,.wxss,.pcss,.postcss,.less,.scss,.handlebars,.hbs,.graphql,.gql,.graphqls,.md,.markdown,.mdown,.mdwn,.mkd,.mkdn,.mkdown,.ronn,.scd,.workbook,.mdx,.component.html,.html,.htm,.html.hl,.inc,.xht,.xhtml,.mjml,.vue,.yml,.mir,.reek,.rviz,.sublime-syntax,.syntax,.yaml,.yaml-tmlanguage,.yaml.sed,.yml.mysql}"   at checkExecSyncError (node:child_process:826:11) at Object.execSync (node:child_process:900:15)`

## Expected Behavior
When running  npx nx run-many --all --target=lint --fix prettier should lint and fix all the files it can fix, but not fail with an error when running over a yaml file with broken formatting.

If this is not possible the --fix parameter should take a matcher to exclude extensions.

## Steps to Reproduce
1. Create a .gitlab-ci.yml file in any nx project and make sure the formatting is broken (indentation should be enough)
2. Run `npx nx run-many --all --target=lint --fix `

### Environment
```
  Node : 16.11.0
  OS   : linux x64
  npm  : 8.0.0
  
  nx : 12.9.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.9.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by meeroslav** [comment]
Thank you for reporting this error. Can create a basic repository that reproduces this error?

I just tried with the default scaffolded Nx workspace in v12.9.0 and added a malformed yaml file:
```
version: 2.1

# -------------------------
#        DEFAULTS
-------------------------
machine:
  pre:
mkdir ~/.cache/yarn
- mkdir ~/Library/Caches/Homebrew
- mkdir /usr/local/Homebrew

playing_song_artist: Playing song, {{ song_name }} by {{ artist }}
```

But running `nx lint --fix` did not pick up the yaml file, as I would expect since we have no rules for yaml files.
The problem might be in your `.eslintrc.json`
