### ISSUE TITLE
React native app does not support custom babel config in project folder

### ISSUE THREAD

**Issue by raymondpebble** [nrwl/nx#7826]
## Current Behavior
Adding a `.babelrc` or `.babel.config.js` in the react native project folder is not picked up when trying do a production ios build (that creates a js bundle).

It seems like metro always looks for the babel config file [relative to the `projectRoot`](https://github.com/facebook/metro/blob/main/packages/metro-react-native-babel-transformer/src/index.js
) which nx sets to the [workspace root](https://github.com/nrwl/nx-react-native/blob/main/packages/react-native/plugins/with-nx-metro.ts#L14):

## Expected Behavior
The babel config file should be used by metro.

## Steps to Reproduce

Add a custom babel config file under the project folder

Option A: Try to run `npx nx run-ios <project>`, setting:

```
          "options": {
            "configuration": "Release"
          },
```

Option B: Try to build the Release configuration in Xcode

### Environment

```
  Node : 16.13.0
  OS   : darwin arm64
  npm  : 8.1.0

  nx : 13.1.4
  @nrwl/angular : Not Found
  @nrwl/cli : 12.3.6
  @nrwl/cypress : 12.3.6
  @nrwl/devkit : 12.3.6
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.6
  @nrwl/linter : 12.3.6
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 12.3.6
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.6
  @nrwl/web : 12.3.6
  @nrwl/workspace : 12.3.6
  @nrwl/storybook : 12.3.6
  @nrwl/gatsby : Not Found
  typescript : 3.9.9

```

**Comment by xiongemi** [comment]
this should be fixed in nx 14 with pr https://github.com/nrwl/nx/pull/9872/files#diff-cb2ad48025f452c6f5f8a489ec49cdd605525f5d9c0dde806d3cb5d7367a0cc7.
Now, it allows users to set projectRoot to metro config.

**Comment by raymondpebble** [comment]
Thank you!
