### ISSUE TITLE
compdoc command is not generating json file for project

### ISSUE THREAD

**Issue by dimitriliberman** [nrwl/nx#7831]
Hello,
compdoc and storybook was working fine with nx 12
Upgraded to nx 13 using migration path, after upgrade when running compdoc:json command (npx nx run shared-ui-overlay-window:compodoc:json) to generate json documentation getting error:

node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:948
        throw new Error(message);
        ^

Error: error TS5083: Cannot read file 'C:\cgi-work\tps-client\libs\shared\ui-overlay-window\C:\cgi-work\tps-client\libs\shared\ui-overlay-window\tsconfig.lib.json'.

    at readConfig (C:\cgi-work\tps-client\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:948:15)
    at CliApplication.start (C:\cgi-work\tps-client\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:13250:40)
    at Object.<anonymous> (C:\cgi-work\tps-client\node_modules\@compodoc\compodoc\bin\index-cli.js:6:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

here is my package.json dependencies:

  "dependencies": {
    "@angular-builders/custom-webpack": "^13.0.0",
    "@angular/animations": "13.0.0",
    "@angular/cdk": "13.0.0",
    "@angular/common": "13.0.0",
    "@angular/compiler": "13.0.0",
    "@angular/core": "13.0.0",
    "@angular/forms": "13.0.0",
    "@angular/material": "13.0.0",
    "@angular/platform-browser": "13.0.0",
    "@angular/platform-browser-dynamic": "13.0.0",
    "@angular/router": "13.0.0",
    "@angular/upgrade": "13.0.0",
    "@ngrx/effects": "13.0.1",
    "@ngrx/store": "13.0.1",
    "@ngrx/store-devtools": "13.0.1",
    "@nrwl/angular": "13.2.1",
    "@popperjs/core": "^2.9.2",
    "@tinymce/tinymce-angular": "4.2.4",
    "ag-grid-angular": "^25.3.0",
    "ag-grid-community": "^25.3.0",
    "angular": "npm:@xlts.dev/angular@1.8.7",
    "angular-animate": "npm:@xlts.dev/angular-animate@1.8.7",
    "angular-aria": "npm:@xlts.dev/angular-aria@1.8.7",
    "angular-cache": "^4.6.0",
    "angular-clipboard": "^1.7.0",
    "angular-file-saver": "1.1.3",
    "angular-hotkey": "0.2.1",
    "angular-pdfjs-viewer": "2.0.1",
    "angular-resizable-element": "^3.4.0",
    "angular-resource": "npm:@xlts.dev/angular-resource@1.8.7",
    "angular-route": "npm:@xlts.dev/angular-route@1.8.7",
    "angular-sanitize": "npm:@xlts.dev/angular-sanitize@1.8.7",
    "angular-toarrayfilter": "1.0.3",
    "angular-ui-bootstrap": "2.5.6",
    "bootstrap": "3.4.1",
    "bootstrap-new": "npm:bootstrap@^5.0.1",
    "crypto-js": "4.0.0",
    "d3": "^6.7.0",
    "error-stack-parser": "^2.0.6",
    "jquery": "^3.5.1",
    "jquery-ui": "^1.12.1",
    "jquery-ui-bundle": "*",
    "luxon": "^1.27.0",
    "material-icons": "^1.6.0",
    "ng-device-detector": "5.1.4",
    "ng-file-upload": "12.2.13",
    "rxjs": "~6.6.0",
    "tinymce": "5.9.2",
    "tslib": "^2.0.0",
    "zone.js": "0.11.4"
  },
  "devDependencies": {
    "@angular-architects/ddd": "^1.5.1",
    "@angular-devkit/build-angular": "13.0.1",
    "@angular-eslint/eslint-plugin": "13.0.1",
    "@angular-eslint/eslint-plugin-template": "13.0.1",
    "@angular-eslint/template-parser": "13.0.1",
    "@angular/cli": "13.0.3",
    "@angular/compiler-cli": "13.0.0",
    "@angular/language-service": "13.0.0",
    "@compodoc/compodoc": "^1.1.15",
    "@nrwl/cli": "13.2.1",
    "@nrwl/cypress": "13.2.1",
    "@nrwl/eslint-plugin-nx": "13.2.1",
    "@nrwl/jest": "13.2.1",
    "@nrwl/linter": "13.2.1",
    "@nrwl/storybook": "13.2.1",
    "@nrwl/tao": "13.2.1",
    "@nrwl/web": "13.2.1",
    "@nrwl/workspace": "13.2.1",
    "@storybook/addon-a11y": "^6.3.11",
    "@storybook/addon-essentials": "6.4.0-rc.3",
    "@storybook/angular": "6.4.0-rc.3",
    "@storybook/builder-webpack5": "6.4.0-rc.3",
    "@storybook/manager-webpack5": "6.4.0-rc.3",
    "@twittwer/compodoc": "^1.6.5",
    "@types/d3": "^6.7.0",
    "@types/jest": "27.0.2",
    "@types/node": "14.14.33",
    "@typescript-eslint/eslint-plugin": "4.33.0",
    "@typescript-eslint/parser": "4.33.0",
    "angular-template-cache": "^1.3.3",
    "autoprefixer": "9.8.6",
    "babel-plugin-angularjs-annotate": "^0.10.0",
    "copy-webpack-plugin": "^6.3.2",
    "cypress": "^8.3.0",
    "dotenv": "8.2.0",
    "eslint": "7.32.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "express": "4.17.1",
    "file-loader": "^6.2.0",
    "gifsicle": "5.1.0",
    "jasmine-core": "^3.6.0",
    "jest": "27.2.3",
    "jest-preset-angular": "11.0.0",
    "ng-packagr": "13.0.6",
    "prettier": "^2.3.1",
    "ts-jest": "27.0.5",
    "ts-node": "~9.1.1",
    "typescript": "4.4.4",
    "url-loader": "^4.1.1",
    "webpack-cli": "^4.7.2"
  }

Please help!

Thank you

**Comment by AgentEnder** [comment]
This looks like its likely an issue with the `@twittwer/compodoc` plugin. Can you open an issue on [the plugin repo](https://github.com/twittwer/nx-tools), for them to investigate? Thanks
