### ISSUE TITLE
Link to old documentation

### ISSUE THREAD

**Issue by vespertilian** [nrwl/nx#7832]
## Description

I want to move an angular 6 project to NX but it's hard to find docs. Are they hidden in the repo somewhere?

## Motivation

We need to move slowly. I can't just jump to the latest version. 

## Suggested Implementation

Link to old docs if they exist or republish them.

**Comment by bcabanes** [comment]
Hi @vespertilian!

We have that planned but maybe in few months, we are currently focusing on having better documentation for the current Nx version and have other things in the works.

Be assured though, this is on our todo list.

In the meantime, you can check and consult the documentation for each Nx version by looking at the releases ([Nx releases](https://github.com/nrwl/nx/releases)). Indeed, each Nx release ships with the current state of the documentation as well as the website (nx.dev). That's a less convenient, but would unblock you for sure 👍 

I want to thank you for your time.
