### ISSUE TITLE
How to access libs while generating app with Tree api

### ISSUE THREAD

**Issue by ruslan-byondxr** [nrwl/nx#7833]
We created a generator, which generates an app with Tree API.
While generating an app, the generator has to read and write some piece of code into libs/ports-config.

As far as I checked, I cannot access libs with a Tree object. 
Tree object have its own virtual context.

**Comment by AgentEnder** [comment]
Hey @ruslan-byondxr! Generator's trees can access any and all files underneath the workspace root. For example, a simple generator to create an app-shell and routing lib in angular may be something like

```typescript
import {applicationGenerator, libraryGenerator} from '@nrwl/angular/generators'

export default async function (host: Tree, options) {
    const libName = options.name + '-routing'
    await applicationGenerator(host, options)
    await libraryGenerator(host, {...options, name: libName})    
}
```
