### ISSUE TITLE
@nrwl/angular ivy incompatible

### ISSUE THREAD

**Issue by pgg** [nrwl/nx#7834]
## Current Behavior
Error: node_modules/@nrwl/angular/src/runtime/nx/nx.module.d.ts:7:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (@nrwl/angular) which declares NxModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy

### Environment
```
  Node : 16.13.0
  OS   : darwin x64
  npm  : 8.1.0
  
  nx : 13.2.1
  @nrwl/angular : 13.2.1
  @nrwl/cli : 13.2.1
  @nrwl/cypress : 13.2.1
  @nrwl/devkit : 13.2.1
  @nrwl/eslint-plugin-nx : 13.2.1
  @nrwl/express : undefined
  @nrwl/jest : 13.2.1
  @nrwl/linter : 13.2.1
  @nrwl/nest : 13.2.1
  @nrwl/next : undefined
  @nrwl/node : 13.2.1
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.1
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.1
  @nrwl/storybook : 13.2.1
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.2
         @angular/cdk: 13.0.2
         @angular/common: 13.0.2
         @angular/compiler: 13.0.2
         @angular/core: 13.0.2
         @angular/forms: 13.0.2
         @angular/material: 13.0.2
         @angular/platform-browser: 13.0.2
         @angular/platform-browser-dynamic: 13.0.2
         @angular/router: 13.0.2
         @ngrx/effects: 13.0.1
         @ngrx/entity: 13.0.1
         @ngrx/router-store: 13.0.1
         @ngrx/store: 13.0.1
         @ngrx/store-devtools: 13.0.1
         @angular-devkit/build-angular: 13.0.3
         @angular/compiler-cli: 13.0.2
         @angular/language-service: 13.0.2
```

**Comment by pgg** [comment]
works with: ```"@nrwl/angular": "13.1.4"```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Unfortunately, I was not able to reproduce it with the provided information. Could please provide a minimal repo where the issue can be reproduced?

**Comment by Camo30** [comment]
Same issue here. Downgrading the package like @pgg suggested does not work for me. Instead removing `NxModule.forRoot()` from imports in `app.module.ts` seems to resolve the issue. Is this intended?

**Comment by pgg** [comment]
Also just figured out that removing NxModule resolves the issue . . .

**Comment by kochax** [comment]
Same issue here, downgrading to 13.1.4 fixed the problem.

**Comment by ueqt** [comment]
Same issue, and downgrading to 13.1.4,it worked, but show following warning
```
[1] Processing legacy "View Engine" libraries:
[1] - @nrwl/angular [es2015/esm2015] (https://github.com/nrwl/nx.git)
[1] Encourage the library authors to publish an Ivy distribution.
```

**Comment by mccool** [comment]
> 

minimal repo here: https://github.com/mccool/nx13-demo

Running `nx serve` gives me this error

```
Error: node_modules/@nrwl/angular/src/runtime/nx/nx.module.d.ts:7:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (@nrwl/angular) which declares NxModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

7 export declare class NxModule {
```

Also, I'm seeing this error in my editor 
<img width="339" alt="Screen Shot 2021-12-03 at 4 25 19 PM" src="https://user-images.githubusercontent.com/648237/144685577-c5ab126c-31fa-42ec-a9d6-d391f87ff584.png">

Thanks!

**Comment by leosvelperez** [comment]
@mccool thanks for providing a repro! The key piece is that this only happens with `nx serve`, `nx build` works fine and that's why I couldn't reproduce it before. There was no mention of the command used and I wrongly assumed the issue was happening when building.

I'll look into fixing this.

That said, as mentioned in [this comment](https://github.com/nrwl/nx/issues/7834#issuecomment-977720732), you could remove the usage of `NxModule` altogether and use the operators instead. Using the operators is actually the recommended approach, you can have a look at the docs for further reference https://nx.dev/l/a/guides/misc-data-persistence#using-datapersistence.

**Comment by mccool** [comment]
@leosvelperez Thanks for pointing that out! The docs have grown and I haven't seen this change. I've been using nx for a while so some of the docs I haven't seen in a while. I am looking forward to migrating from 12.10 to 13 and will make sure to update all my effects files to use these methods directly from @nrwl/angular. Thanks again and have a great week!
