### ISSUE TITLE
nx migrate from version 11 to 12 does not update Angular

### ISSUE THREAD

**Issue by cichy380** [nrwl/nx#7839]
I have Angular project generated by Nx CLI. Version 11.6.3. I want to update Angular to version 12 (not latest 13 version, I need version 12). 

## Current Behavior
I used command `nx migrate 12`.

## Expected Behavior
I expected the command to update @nrwl packages and Angular framework packages.

## Steps to Reproduce
Command `nx migrate 12` just featching Nx packages:
```
Fetching @nrwl/workspace@12.0.0
Fetching @nrwl/angular@12.0.0
Fetching @nrwl/cli@12.0.0
Fetching @nrwl/cypress@12.0.0
Fetching @nrwl/eslint-plugin-nx@12.0.0
Fetching @nrwl/jest@12.0.0
Fetching @nrwl/linter@12.0.0
```

**Comment by AgentEnder** [comment]
Hey @cichy380. Nx 12.0.0 didn't support angular 12, support was added in 12.3.0

Try `nx migrate 12.3.0`, or `nx migrate 12.10.1` to get the most benefit out of v12. If the reasoning for not going up to 13 is that you need Angular v12, you can migrate up to 13.1.x, which is the latest feature version with angular 12 support.

**Comment by gregoiremotot** [comment]
`nx migrate 12.1` worked for me
