### ISSUE TITLE
Webpack Live Server not detecting specific lib changes after migration to 13.2.1

### ISSUE THREAD

**Issue by iamchrisdev** [nrwl/nx#7849]
## Current Behavior

Currently changes Ive made to some files which are placed in "@myworkspace/interfaces" are not detected by the webpack. Application is not auto refreshed and also still not working after manual refresh of the page. I want to **BOLD**  on that this only happens with that specific lib which only contains typescript interfaces. In our workspace we have 5 other libs that are working perfectly fine. Also everything **was** alright before migration.

## Expected Behavior

I expect webpack live server to detect changes in all applications and libs.

## Steps to Reproduce

Not sure how to reproduce that, it only happen in that particular project. Im using nx workspace in couple of other projects for the last 3-4 years and Ive never had an issue like that. 

What Ive actually done this time is the following:

1. We've been using nx workspace (react) with version 12.5.7
2. Ive migrate it to version 12.10.0 (everything was working as expected)
3. Then Ive migrate nx to 13.2.1
4. Sh*t happens

 - Also Ive turned on HRM and I thought the problem is coming somehow from there => Ive turned it off, but result was the same..
 - Ive checked if there is some difference of config files (babel, tsconfig and so on), but this specific lib files are no different than the other. 
 - Also checked the workspace.json.. same no difference than the other libs.
 - Ive tried to make new lib and just copy the files from the problematic lib (again this are all only simple .ts files which are exporting interfaces), updated index.ts file of the newly created lib. Again newly created lib stopped working (meaning stop being detected by the webpack)

### Environment

NODE: 16.13.0
NX: 13.2.1
REACT: 17.0.2

**Comment by akryvasheyeu** [comment]
got the same problem after migration 12.7.2 -> 13.2.2
