### ISSUE TITLE
fatal: path 'workspace.json' exists on disk, but not in '335079884104542a6009523fddc7cf380da4c4eb'

### ISSUE THREAD

**Issue by leon** [nrwl/nx#7855]
## Current Behavior
When I'm trying to run our repo in github actions using distributed agents and cloud run, I'm getting
fatal: path 'workspace.json' exists on disk, but not in '335079884104542a6009523fddc7cf380da4c4eb'

I renamed angular.json to workspace.json which is causing nx cloud to freak out.

**is there any way I can force delete the nx cloud cache?**

## Expected Behavior
want the CI to run

## Steps to Reproduce
use nx cloud
do a ci run with angular.json

then rename it to workspace.json
then do another ci run.
it will fail

### Failure Logs
```
fatal: path 'workspace.json' exists on disk, but not in '335079884104542a6009523fddc7cf380da4c4eb'
```

### Environment

```
Node : 16.13.0
  OS   : darwin x64
  yarn : 3.1.0
  
  nx : 13.2.2
  @nrwl/angular : 13.2.2
  @nrwl/cli : 13.2.2
  @nrwl/cypress : 13.2.2
  @nrwl/devkit : 13.2.2
  @nrwl/eslint-plugin-nx : 13.2.2
  @nrwl/express : undefined
  @nrwl/jest : 13.2.2
  @nrwl/linter : 13.2.2
  @nrwl/nest : 13.2.2
  @nrwl/next : undefined
  @nrwl/node : 13.2.2
  @nrwl/nx-cloud : 12.5.4
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.2
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.2
  @nrwl/storybook : 13.2.2
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
```

**Comment by StalkAltan** [comment]
Hi @leon!

Apologies for extremely delayed response here. You are looking for the `--skip-nx-cache` flag. 

We will look into making this error more helpful moving forward.

Thanks, and apologies again for the delay here. I think it's likely you have already moved on from this issue.

**Comment by mteterel** [comment]
This problem is still occuring as of today. I just set up a fresh Nx workspace with a Nest application and pre-configured CI pipeline for Github Actions.

I have the message "fatal: path '.eslintrc.json' exists on disk, but not in '5e15d9b1'", the lint command still succeed locally but when running in CI, it somehows returns 1 as error code and fail entirely.

**Comment by mkurczewski** [comment]
I started having similar issue and I'm using `--skip-nx-cache` flag always as this is the only way to not use the cache feature that is bugged as hell. Why this issue was closed? What's the real solution for that?

**Comment by algoflows** [comment]
I just ran into this today, no response or resolution on this?!
