### ISSUE TITLE
Cypress is added when generating new next.js apps, when not using cypress

### ISSUE THREAD

**Issue by bogdansoare** [nrwl/nx#7856]
## Description
Right now if you remove all the packages related to cypress, after you generate a next.js app they will be reinstalled.

## Motivation
Not everybody wants to use cypress

## Suggested Implementation
Give an option to completely remove cypress

**Comment by jackoliver** [comment]
I ran into this issue previously using the VSCode plugin. I found manually toggling the cypress flag on and off again allowed me to generate an application without e2e by default.
