### ISSUE TITLE
Cypress component tests require deprecated 'headless' option

### ISSUE THREAD

**Issue by piemasters** [nrwl/nx#7864]
## Current Behavior

Since upgrading to `13.2.0` our Cypress component tests started to fail in Github Actions. We use the  `@nrwl/cypress:cypress` executor with `"testingType": "component"`.  

Initially I believed this was down to the `"parallel": 1` added to `nx.json` so I set all component tests not to run in parallel but it still threw various `Xvfb` errors. This lead me to believe that under the hood Nx is always using `cypress open-ct` rather than `cypress  run-ct`. Adding the deprecated `"headless": true` option fixes the problem, so I believe confirms this.

## Expected Behavior

The `@nrwl/cypress:cypress` executor should use `cypress run-ct` by default rather than `cypress open-ct`, or the `headless` option shouldn't be deprecated.

## Steps to Reproduced

This can be reproduced by running a simple Cypress component test within a GitHub action. I'm not sure if the any of the projects in the example repo are setup to use Cypress component tests? If required I can try to find some time to create a PR to add one somewhere, but I'm not sure if i'll be able to create and run a GitHub action?

### Failure Logs
When running the following script in GitHub:

```
    "test-component": {
      "executor": "@nrwl/cypress:cypress",
      "options": {
        "cypressConfig": "libs/shared/component-library/cypress.json",
        "parallel": false,
        "testingType": "component"
      }
    }
```

```

[STARTED] Task without title.
[FAILED] Xvfb exited with a non zero exit code.
[FAILED] 
[FAILED] There was a problem spawning Xvfb.
[FAILED] 
[FAILED] This is likely a problem with your system, permissions, or installation of Xvfb.
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Error: (EE) 
[FAILED] Fatal server error:
[FAILED] (EE) Server is already active for display 99
[FAILED] If this server is no longer running, remove /tmp/.X99-lock
[FAILED] and start again.
[FAILED] (EE)
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Platform: linux-x64 (Ubuntu - 20.04)
[FAILED] Cypress Version: 9.1.0
Xvfb exited with a non zero exit code.

There was a problem spawning Xvfb.

This is likely a problem with your system, permissions, or installation of Xvfb.

----------

Error: (EE) 
Fatal server error:
(EE) Server is already active for display 99
If this server is no longer running, remove /tmp/.X99-lock
and start again.
(EE)

----------

Platform: linux-x64 (Ubuntu - 20.04)
Cypress Version: 9.1.0
```

### Environment
```

  Node : 14.18.1
  OS   : darwin x64
  yarn : 1.22.15
  
  nx : 13.2.2
  @nrwl/angular : undefined
  @nrwl/cli : 13.2.2
  @nrwl/cypress : 13.2.2
  @nrwl/devkit : 13.2.2
  @nrwl/eslint-plugin-nx : 13.2.2
  @nrwl/express : undefined
  @nrwl/jest : 13.2.2
  @nrwl/linter : 13.2.2
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.2.2
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.2
  @nrwl/web : 13.2.2
  @nrwl/workspace : 13.2.2
  @nrwl/storybook : 13.2.2
  @nrwl/gatsby : undefined
  typescript : 4.5.2
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:

```

**Comment by barbados-clemens** [comment]
@piemasters can you make a minimum reproduction repo with this?

Component tests are [considered alpha according to cypress currently](https://docs.cypress.io/guides/component-testing/introduction) as a btw.

Right now cypress executor calls open or run with the [arguments passed in after normalizing them](https://github.com/nrwl/nx/blob/master/packages/cypress/src/executors/cypress/cypress.impl.ts#L168-L223) so I don't see what with nx would be causing the issue initially.

We do use [headless if that argument is passed in, but also use the headed argument](https://github.com/nrwl/nx/blob/master/packages/cypress/src/executors/cypress/cypress.impl.ts#L191-L195). so if you pass it in it will be set.
