### ISSUE TITLE
Allow --port to be passed through to the E2E tests

### ISSUE THREAD

**Issue by RonanCodes** [nrwl/nx#7871]
## Description

Allow the -- --port=1234 to be passed through to the Cypress, so that we can serve the app on a non 4200 port.
Currently if port 4200 is in used I get prompted yes or no to pick a random port.
So the random free ports do work, I just need NX to allow me to pass through the port flag so I can set it to 0 for my pipeline build.

## Motivation

I want to be able to set the port to 0 so that a random free port will be used instead of port 4200.
I currently have a build agent that can run 5 builds at once, but the agent only has one port 4200.

## Suggested Implementation

Pass the port flag through to Cypress.

**Comment by RonanCodes** [comment]
Linked to this closed issue: https://github.com/nrwl/nx/issues/1177

**Comment by RonanCodes** [comment]
Found a workaround for now:
`echo 'yes' | nx affected:e2e`

When the port is taken for your app, you are prompted with a yes/no question to choose a free port.
Yes will be auto input for every single app e2e run.
I tested it with 3 apps.

I tried adding it as an NPM script but it doesn't like the pipe, so instead I'm just calling it directly like this.

**Comment by barbados-clemens** [comment]
can you use the`--baseUrl` with the port set as a workaround?

**Comment by fs-innonova** [comment]
@R0-NaN that looked promising.. unfortunately did not work.. I have several apps running e2e in port 4200 and I dont think that the "script" is being "questioned" to use another port

 ✖  nx run marketing-app-e2e:e2e
       info  - automatically enabled Fast Refresh for 1 custom loader
       event - compiled client and server successfully in 473 ms (617 modules)
       [ ready ] on http://localhost:4200
       error - uncaughtException: Error: listen EADDRINUSE: address already in use :::4200

**Comment by crates** [comment]
I'm in the same boat. The project I'm managing often runs into port conflicts if someone forgets to close the Cypress watch task before running the `nx affected:e2e` command. The options provided by @RonanCodes and @barbados-clemens didn't work for me. I can't get the `--port` flag to work, either.

**Comment by barbados-clemens** [comment]
We will be working on creating port collision logic within cypress in the comming months to help solve this issue
