### ISSUE TITLE
@nrwl/node:package --watch exits unexpectedly

### ISSUE THREAD

**Issue by DibyodyutiMondal** [nrwl/nx#7877]
## Current Behavior
I have  2 node libraries... `models` and `cloud-services`, and one application `app-engine`. Both libraries are buildable.
`cloud-services` depends on `models`
`app-engine` depends on `cloud-services`.

To get rid of webpack and use plain esm output, the `app-engine` build target uses `@nrwl/node:package` as an executor instead of `@nrwl/node:build`, and the serve target uses nodemon.

To make this work, so that changes in the libraries would reload the app, I used to set the typescript paths to the respective `dist` folder output. 
Then, I'd build the libraries in watch mode, starting with `models`, then `cloud-services`,
Thus, changes to the libraries would change the output folder of the libraries,
This would make the app recompile, because typescript would pick up the change.
And then the app recompilation would trigger nodemon to restart the `app-engine` application.

This used to work perfectly, but after migrating from 13.1 to 13.2, this no longer works. Any time I make changes to any of the libraries, the projects which are further down the dependency tree exit their build watch command, with a cryptic 'Debug error' message. For example, changes to `models` would cause both `cloud-services` and `app-engine` to exit build; while changes to `cloud-services` would cause only `app-engine` to exit build.

After a lot of debugging, I found the flow of the error:

### 1. node_modules\@nrwl\workspace\src\utilities\typescript\compilation.js
After I tell nrwl to execute the build target, this piece of code runs. The important thing here is the host variable.
```javascript
function compileTypeScriptWatcher(options, callback) {
    // ... other statements
    const host = ts.createWatchCompilerHost(tsConfig.fileNames, tsConfig.options, ts.sys);
    // ... other statements
    ts.createWatchProgram(host);
    return new Promise(() => { });
}
```

### 2. node_modules\typescript\lib\typescript.js
Before the typecript compilation runs, the `host` variable from the above nrwl code is being used to populate a variable `configFileName` inside of typescript,
This variable remains `undefined` after the code executes because the `host` variable has no such key.
```javascript
function createWatchProgram(host) {
  // many var declarations...
  var configFileName = host.configFileName, 
  // function continues
}
```

### 3. node_modules\typescript\lib\typescript.js
This function runs every time typescript detects code changes.
Notice the statement `parseConfigFile()`. Long story short, inside of that function call it tries to read a file using the variable, `configFileName`. As stated above, this variable is `undefined`, and that causes the read operation to throw an error, and the compiler exits.
```javascript
function reloadConfigFile() {
  writeLog("Reloading config file: " + configFileName);
  reloadLevel = ts.ConfigFileProgramReloadLevel.None;
  if (cachedDirectoryStructureHost) {
    cachedDirectoryStructureHost.clearCache();
  }
  parseConfigFile();
  hasChangedCompilerOptions = true;
  synchronizeProgram();
  // Update the wild card directory watch
  watchConfigFileWildCardDirectories();
  // Update extended config file watch
  updateExtendedConfigFilesWatches(toPath(configFileName), compilerOptions, watchOptions, ts.WatchType.ExtendedConfigFile);
}
```

## Workaround  
As of now, I am just adding a null-check before that line in point no. 4
```javascript
if (!!configFileName)
  parseConfigFile();
```

So far, this is working great, but I am of course afraid of any unnoticeable side-effects. 
Plus, I'll probably have to come back here after every npm update/install.
Also, I don't know if this is a bug with typescript for not checking the variable before using it, or a bug with nrwl for not populating the `host.configFileName` in point no. 1. (or both?)
Hence, I am putting it here

### Environment
  nx : 13.2.2
  @nrwl/angular : 13.2.2
  @nrwl/cli : 13.2.2
  @nrwl/cypress : 13.2.2
  @nrwl/devkit : 13.2.2
  @nrwl/eslint-plugin-nx : 13.2.2
  @nrwl/express : undefined
  @nrwl/jest : 13.2.2
  @nrwl/linter : 13.2.2
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.2.2
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.2
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.2
  @nrwl/storybook : 13.2.2
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.2
         @angular/cdk: 13.0.2
         @angular/common: 13.0.2
         @angular/compiler: 13.0.2
         @angular/core: 13.0.2
         @angular/fire: 7.2.0
         @angular/forms: 13.0.2
         @angular/material: 13.0.2
         @angular/platform-browser: 13.0.2
         @angular/platform-browser-dynamic: 13.0.2
         @angular/pwa: 13.0.3
         @angular/router: 13.0.2
         @angular/service-worker: 13.0.2
         @capacitor/angular: 2.0.0
         @angular-devkit/build-angular: 13.0.3
         @angular/compiler-cli: 13.0.2
         @angular/language-service: 13.0.2

**Comment by DibyodyutiMondal** [comment]
I just migrated all nrwl packages to version 13.4.0 and watch mode for nrwl/node:package no longer works, irrespective of whether I patch  `typescript.js` as mentioned above. Normal builds work fine,

However, changing the executor to the new `@nrwl/js:tsc` allows watch mode to work. Although that still does require the patching of `typescript.js`

**Comment by iangregsondev** [comment]
Yep, I confirm. I get the same. Its a real pain :-) I am going to just not use watch mode until its fixed. I wish I found your post sooner :-)

**Comment by vuexpert** [comment]
Same here, i then have stick to "@nrwl/node": "13.3.12"

**Comment by jensbodal** [comment]
For now this work around seems to work

```
    "watch": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "command": "nodemon -e ts,tsx,js,jsx,json,css,scss -w packages/my-package -x 'nx build my-package'"
      }
    },
```

I assume it's less efficient than tsc watch itself but it's good enough for now

**Comment by DibyodyutiMondal** [comment]
Tbh, I have not used @nrwl/node for a while now. The new @nrwl/js package is extremely straightforward, especially for libraries, and the latest version 13.8.4 allows me to develop using `incremental build` + `watch` pretty easily.

I'll update the same for node apps as soon as I have used it more extensively and have some confidence in it.

**Comment by AgentEnder** [comment]
The solution for this one is definitely to migrate over to the nrwl/js package, as nrwl/node:package will become deprecated in the near future in favor of the executors inside nrwl/js.

**Comment by DibyodyutiMondal** [comment]
Should I close this issue, then?
