### ISSUE TITLE
[question] Recommened structure for reusable container components

### ISSUE THREAD

**Issue by ternyk** [nrwl/nx#788]
Hi,
After reading your suggestions about how to structure application by using libs. I see that you propose:
* component libraries type which should contain dumb components without state/services dependency,
* data/access/state/services libraries

In which type of libraries should be "containers" components to be reusable in different applications?
I know that I can define my own library and tag this as lib:containers and put a rule that a container library depend on lib:component and lib:data-access.
Some example:
there are:
libs:
common-components: AboutComponent
common-data-access: AboutAPIService
commmon-containers: AboutContainerComponent

apps:
app-first and app-second can: just import CommmonContainersModule and use AboutContainerComponent and forget how to fetch the data.

Is this OK? Do you have a better idea?

**Comment by FrozenPandaz** [comment]
We've written a book on this topic:

https://connect.nrwl.io/app/books/enterprise-angular-monorepo-patterns
