### ISSUE TITLE
Coverage reports are broken on blank project

### ISSUE THREAD

**Issue by MarcScheib** [nrwl/nx#789]
**What is happening:**
I am running coverage reports on my projects, but each app/lib has broken reports. I reproduced this issue with a blank project created from command line only.
If I am using a blank Angular project everything is working fine. I also compared files and could not face any issues. On istanbul repo, I could found a statement saying generated source maps could be broken.

Is anybody facing the same issue or has solution for it? Is this a bug somewhere in nx? 

**What I did:**
```bash
npm i -g @angular/cli@latest @nrwl/schematics
create-nx-workspace test
cd test
ng generate app myapp
npm run test -- myapp --code-coverage
```

**Result:**

![image](https://user-images.githubusercontent.com/5886709/46199373-2f486700-c30f-11e8-93a1-a9de993a647e.png)

**Environment:**
Windows 10
Node 8.11.1
NPM 6.4.0
NG CLI global 6.2.1
NG CLI project 6.1.2
@nrwl/schematics 6.3.1

**Comment by bcabanes** [comment]
Hi @MarcScheib!

Thank you for reporting this issue, however I don't think this comes from Ns specifically, but more from the AngularCLI. Internally, Nx is using the AngularCLI's configuration on source maps to generate code coverage.

See this issue on the [AngularCLI repository here](https://github.com/angular/angular-cli/issues/12343), concerning _enabling source-maps by default when using karma_.
You can see this feature will be available for [the next version of AngularCLI (v7+)](https://github.com/angular/angular-cli/releases).

In the meantime, you can use the `--source-map` option to force the cli to create the source maps when build the application for testing.

```shell
npm run test -- myapp --code-coverage --source-map
```

This will work with Nx and AngularCLI.
