### ISSUE TITLE
unable to upgrade eslint version to 8

### ISSUE THREAD

**Issue by Areen3** [nrwl/nx#7890]
Yours pacagage @nwrl/nx provide rules for project dependency 
this is project @nwrl/eslint-plugin-nx
that use npm @typescript-eslint/experimental-utils in wersion "~4.33.0",

that package is used by  @typescript-eslint/eslint-plugin
but in new wersion of @typescript-eslint/experimental-utils in wersion some
I use @eslint-config-airbnb-typescript npm, that use new wersion of 
@typescript-eslint/experimental-utils
and there is some braking changes  between 4.33 and 5.0
https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/experimental-utils/CHANGELOG.md
Can You upgrade to new wersion of this utils?

## Current Behavior

error whern i run  npm install eslint@8.0.0 @eslint-config-airbnb-typescript 
when I tray lint any project

## Expected Behavior

after install to eslint version 8 airbnb and @nwrl/nx plugin work together

## Steps to Reproduce

install new wersion of nx, eslint, airbnb and lint any project

If you want this sample, please tell me, i do it

### Environment

lastes nx@13.0.2

Thanks...

**Comment by Areen3** [comment]
this is error when You run nx lint in  these configuration
Failed to load plugin '@nrwl/nx' declared in 'libs\af\shared\typescript\.eslintrc.json » ../../../../.eslintrc.json': Class extends value undefined is not a constructor
 or null

**Comment by puku0x** [comment]
It seems ESLint v8 will be available on next minor version (maybe v13.3.0?) https://github.com/nrwl/nx/pull/7800

**Comment by Areen3** [comment]
ok, I'm sorry for the duplicate, I checked but it is not accurate,
Thank you for your answer...
