### ISSUE TITLE
findProjectOfResolvedModule in target-project-locator doesn't handle project with wildcard correctly

### ISSUE THREAD

**Issue by timmisset** [nrwl/nx#7892]
We have a workspace where we have:
libs/activity-domain/activity/activity-feature
libs/activity-domain/activity/activity-feature-ui
libs/activity-domain/activity/activity-util

with a wildcard in our tsconfig.base.json:
@activity/*: [ libs/activity-domain/* ]

when the activity-feature module imports the activity-feature-ui module via @activity/activity/activity-feature-ui the findPaths resolves to [ libs/activity-domain/* ]. The findProjectOfResolvedModule then resolves this to <projectroot>/libs/activiteit-domain/ ==> fullpath
It then checks it against the project roots by: fullpath.startsWith(project.root)

None of the projects match that condition because their root is not the same as the root of the @activity, but a subfolder.
When I modify the findPaths() method a bit so that it doesn't return [ libs/activity-domain/* ] but [ libs/activity-domain/activity/activity-feature-ui ] everything works correctly.

## Current Behavior
The wildcard asterix is only trimmed from the paths

## Expected Behavior
I would expect the remainder of the import statement to be appended and the asterix trimmed so that the import resolves correctly to the full folder stated by the import.
This worked fine in version 11.6

## Steps to Reproduce
See description above

code used to fix it for our situation
```javascript
findPaths(normalizedImportExpr) {
        if (!this.paths) {
            return undefined;
        }
        if (this.paths[normalizedImportExpr]) {
            return this.paths[normalizedImportExpr];
        }
        const wildcardPath = Object.keys(this.paths).find((path) => path.endsWith('/*') &&
            normalizedImportExpr.startsWith(path.replace(/\/\*$/, '')));
        if (wildcardPath) {
            let path = this.paths[wildcardPath] && this.paths[wildcardPath][0];
            if(!path) { return undefined; }
            path = path.substring(0, path.length - 1) + normalizedImportExpr.substring(wildcardPath.length - 1);
            return [path];
        }
        return undefined;
    }
```

**Comment by yasinkocak** [comment]
any updates of this issue?
