### ISSUE TITLE
Update `@typescript-eslint/experimental-utils` on `@nwrl/eslint-plugin-nx`

### ISSUE THREAD

**Issue by antonioandrade** [nrwl/nx#7893]
I'm looking to update `@typescript-eslint/eslint-plugin` to `5.4.0` on our monorepo so that it plays ball with TS 4.5.2 but it seems that `@nwrl/eslint-plugin-nx` at `13.2.2` is still locking `@typescript-eslint/experimental-utils` at `4.33.0` instead of the `5.4.0` I was hoping to get.

Right now, linting within our NX workspace yields the warning:
```
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.5.2

```
## Description
Update the `@typescript-eslint/experimental-utils` dependency to `5.4.0` on `@nwrl/eslint-plugin-nx`.

## Motivation
For ESlint to support TypeScript 4.5.2.

**Comment by DmitryKandratsenka** [comment]
I have the same problem. For some reason it still requests this legacy version
![image](https://user-images.githubusercontent.com/74970709/143506860-02706593-5188-48e2-8033-5e8cdb9c482f.png)

**Comment by puku0x** [comment]
I guess current Nx supports TS 4.4 which is the same version that Angular v13 supports.
Fortunately, ESLint v8 and typescript-eslint v5 will be available soon by https://github.com/nrwl/nx/pull/7800 .

**Comment by AgentEnder** [comment]
Hey, Thanks for reporting this!

I'm going to close this since it has been fixed in latest master branch. If you are experiencing any other issues, feel free to open another issue.
