### ISSUE TITLE
After migration from 11 to 13.2, build is not creating any output

### ISSUE THREAD

**Issue by romankh** [nrwl/nx#7923]
## Current Behavior

- Building the app does not produce any output in the dist folder, but instead terminates immediately without any hint 
- Only output is **_NX  Running target build for project XXX and 1 task(s) that it depends on._**
- nx serve XXX however seems to work fine

I also removed node_modules and package-lock.json and re-installed to ensure webpack 5 is installes as suggested in some other issue, but without any effect

## Expected Behavior

Have no idea how to debug this. Even building with --verbose option does not produce more output.

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

  Node : 14.18.1
  OS   : linux x64
  npm  : 8.1.4
  
  nx : 13.2.3
  @nrwl/angular : 13.2.3
  @nrwl/cli : 13.2.3
  @nrwl/cypress : 13.2.3
  @nrwl/devkit : 13.2.3
  @nrwl/eslint-plugin-nx : 13.2.3
  @nrwl/express : undefined
  @nrwl/jest : 13.2.3
  @nrwl/linter : 13.2.3
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.3
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.3
  @nrwl/storybook : 13.2.3
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.2
         @angular/cdk: 13.0.2
         @angular/common: 13.0.2
         @angular/compiler: 13.0.2
         @angular/core: 13.0.2
         @angular/forms: 13.0.2
         @angular/material: 13.0.2
         @angular/material-moment-adapter: 13.0.2
         @angular/platform-browser: 13.0.2
         @angular/platform-browser-dynamic: 13.0.2
         @angular/platform-server: 13.0.2
         @angular/router: 13.0.2
         @ngrx/effects: 13.0.1
         @ngrx/router-store: 13.0.1
         @ngrx/store: 13.0.1
         @ngrx/store-devtools: 13.0.1
         @nguniversal/express-engine: 13.0.1
         ngx-build-plus: 13.0.1
         @angular-devkit/build-angular: 13.0.0
         @angular/cli: 13.0.2
         @angular/compiler-cli: 13.0.2
         @angular/language-service: 13.0.2
         @nguniversal/builders: 13.0.1

**Comment by romankh** [comment]
Some updates:

- I suspected the libs to be involved in this, so I removed the libraries from the projects in angular.json
- Build with only the app in angular.json works
- Then I just put the library entries back in place in angular.json
- Build still works
- I clear the cache in node_modules/nx
- Build breaks again, no output to dist folder


Can anyone give me a hint what might be going on here?

**Comment by AgentEnder** [comment]
Hey @romankh. Have you figured this out since reporting?

If not, can you paste the target configurations for the app + lib combination that is causing the breakage here?

**Comment by romankh** [comment]
Hi @AgentEnder, 
thanks for your response.
No, have not figured out yet.
What do mean exactly with target configuration, the whole angular.json? Or something more specific?

**Comment by AgentEnder** [comment]
The config for the apps + libs that cause it to break would be fine, don't need the whole file. 

Also, if you could migrate to 13.3 that released to confirm that its not already fixed, that would help

**Comment by romankh** [comment]
I did the migration to 13.3, but problem is not fixed.

I believe that the following lib causes the problem, removing it for the first build seems to solve the issue for the following builds. The lib contains a Angular module, and it provides 2 Angular components, one for uploading images using ngx-dropzone, and a dialog for cropping.

```
    "ui-image-upload": {
      "projectType": "library",
      "root": "libs/ui/image-upload",
      "sourceRoot": "libs/ui/image-upload/src",
      "prefix": "wedress",
      "architect": {
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": [
              "libs/ui/image-upload/src/**/*.ts",
              "libs/ui/image-upload/src/**/*.html"
            ]
          },
          "outputs": [
            "{options.outputFile}"
          ]
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": [
            "coverage/libs/ui/image-upload"
          ],
          "options": {
            "jestConfig": "libs/ui/image-upload/jest.config.js",
            "passWithNoTests": true
          }
        }
      },
      "tags": []
    },
```

The config just looks like other 22 libs, so I guess something in this specific lib is different.
After the initial build it can be put into angular.json again, and everything seems to work fine. The functionality of the lib is fully available in app.

**Comment by romankh** [comment]
Finally had some more time for that issue.
Cause was that the problematic lib was mistakenly importing a class from the app, which created a cyclic dependency between the library and the app. Most likely that's why the second build worked

I am closing this issue, however I suggest providing some kind of output for this kind of issues so that debugging is a bit easier.
