### ISSUE TITLE
Peer dependency warning - jasmine-marbles

### ISSUE THREAD

**Issue by bostondevin** [nrwl/nx#793]
Getting this with latest Angular 6

@nrwl/nx@6.3.1 requires a peer of jasmine-marbles@0.3.1 but none is installed. You must install peer dependencies yourself.

**Comment by bcabanes** [comment]
Hi @bostondevin,

Could you add more information about the steps where you have this issue, I can't seem to reproduce this issue with the latest version of Nx.

Do you still have this issue?

**Comment by sprov03** [comment]
I am having the same issue when trying to update angular.  Here is my setup and the commands i ran to repoduce the issue and my current package.json file


$ ng update

> 
>     We analyzed your package.json, there are some packages to update:
> 
>       Name                               Version                  Command to update
>      --------------------------------------------------------------------------------
>       @angular/cli                       6.1.2 -> 6.2.4           ng update @angular/cli
>       @ngrx/store                        6.0.1 -> 6.1.0           ng update @ngrx/store
>       @nrwl/nx                           6.2.1 -> 6.4.0           ng update @nrwl/nx
> 
> 
>     There might be additional packages that are outdated.
>     Or run ng update --all to try to update all at the same time.
> 
> 

$ ng update --all

>                   Package "@nrwl/nx" has an incompatible peer dependency to "jasmine-marbles" (requires "0.3.1", would install "0.4.0").
>                   Package "@nrwl/nx" has an incompatible peer dependency to "jasmine-marbles" (requires "0.3.1", would install "0.4.0")
>                   Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=2.7.2 <2.10", would install "3.1.1").
> Incompatible peer dependencies found. See above.
> 

package.json
```

{
  "name": "sprov-workspace",
  "version": "0.0.0",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/fire": "^5.0.2",
    "@angular/forms": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "@ngrx/effects": "6.0.1",
    "@ngrx/router-store": "6.0.1",
    "@ngrx/store": "6.0.1",
    "@nrwl/nx": "6.2.1",
    "core-js": "^2.5.4",
    "firebase": "^5.5.3",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26",
    "@ngrx/entity": "6.0.1"
  },
  "devDependencies": {
    "@angular/cli": "6.1.2",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@angular-devkit/build-angular": "~0.7.0",
    "@ngrx/store-devtools": "6.0.1",
    "ngrx-store-freeze": "0.2.4",
    "@nrwl/schematics": "6.2.1",
    "jasmine-marbles": "0.3.1",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2",
    "prettier": "1.13.7"
  }
}
```
