### ISSUE TITLE
nx affected --target=my-custom-command

### ISSUE THREAD

**Issue by craigbroadman** [nrwl/nx#7931]
## Current Behavior

I have the following structure in my repo

- my-api
- my-api-iac (infrastructure as code)
  - has an implicit dependency on "my-api"
- my-api-integration-tests
  - has an implicit dependency on "my-api-iac"

my-api-iac has a custom command setup similar to the below that will deploy to AWS using the AWS CDK:

```json
"temp-stack-deploy": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "commands": [
          "cdk deploy  xyz"
        ],
      }
    },
```
If I make a change to an integration test, I need the IAC "temp-stack-deploy" process to be kicked off when `npx nx affected --target=temp-stack-deploy` is executed but it is not. 

With `npx nx affected --target=build` correctly picking up the dependency chain (e.g. when "my-api-iac" changes, it builds "my-api") I thought I could resolve the issue by adding a target of "temp-stack-deploy" to "my-api-integration-tests" as below as maybe the target needed to be found in order to make the link.  However this didn't help either.

```json
"temp-stack-deploy": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "commands": [
          "echo this ensures the microservice is deployed during build when integration tests change"
        ]
      }
    },
```

## Expected Behavior

I need nx:affected to recognise a change to "my-api-integration-tests" as requiring "my-api-iac" to run "temp-stack-deploy".

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by AgentEnder** [comment]
Does the targetDependencies/ dependsOn option work for this? 

You should be able to setup as something like

```
    targetDependencies: {
        test: [{
            target: some-deploy-target,
            project: dependencies
        }]
    }
```

**Comment by craigbroadman** [comment]
Thanks @AgentEnder, I will give this a try but could you confirm I am understanding this correctly.

Currently I have this set up in nx.json:

```json
"targetDependencies": {
    "build": [
      {
        "target": "build",
        "projects": "dependencies"
      }
    ]
  },
```

and I think I should be updating it to be...

```json
"targetDependencies": {
    "build": [
      {
        "target": "build",
        "projects": "dependencies"
      }
    ],
    "temp-stack-deploy": [
      {
        "target": "temp-stack-deploy",
        "projects": "dependencies"
      }
    ]
  },
```

**Comment by AgentEnder** [comment]
Yeah, that looks correct.

**Comment by craigbroadman** [comment]
It worked - thank you @AgentEnder
