### ISSUE TITLE
Make NestJS generator less opiniated about HTTP framework

### ISSUE THREAD

**Issue by getlarge** [nrwl/nx#7938]
## Current Behavior
In the context of a project using NestJS with Fastify, i noticed that the Nx NestJS generator makes the assumption that Express is always used. So each time we generate a new application with `npx nx generate @nrwl/nest:application myapp` it will add `@nestjs/platform-express@7.0.0` in package.json.

1. for a Fastify app this package is not needed 
2. it creates versions conflicts if we are currently using NestJS 8.x.x

## Expected Behavior
Nx should be more neutral regarding the underlying HTTP framework or should allow to select which framework is used with an extra option (?)

## Steps to Reproduce

1. Create a new workspace
```sh
npx create-nx-workspace
```

2. Generate a NestJS app:
```sh
npx nx generate @nrwl/nest:application myapp
```

### Environment
```
  nx : 13.1.2
  @nrwl/angular : Not Found
  @nrwl/cli : 13.1.2
  @nrwl/cypress : 13.1.4
  @nrwl/devkit : 13.1.2
  @nrwl/eslint-plugin-nx : 13.1.2
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.2
  @nrwl/linter : 13.1.2
  @nrwl/nest : 13.1.3
  @nrwl/next : 13.1.4
  @nrwl/node : 13.1.2
  @nrwl/nx-cloud : 12.5.2
  @nrwl/react : 13.1.4
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.2
  @nrwl/web : 13.1.4
  @nrwl/workspace : 13.1.2
  @nrwl/storybook : 13.1.4
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by getlarge** [comment]
Maybe it's more of a feature request ?

**Comment by nartc** [comment]
@getlarge sorry for such a delayed response. Number 2 on the original issue is no longer an issue I believe as we support Nest 8 now. For `fastify`, I think it makes sense to allow an option to be passed in to customize. Also, there are #8297 and #8192 but the suggestion was to make it a community plugin instead.

That said, can you make a new issue (feature request) to outline the option to add Fastify to `nrwl/nest`? Closing this one.
