### ISSUE TITLE
Allow next.js assets outside of the public folder

### ISSUE THREAD

**Issue by flippidippi** [nrwl/nx#7941]
## Description

Currently, assets are only allowed to be put into the public folder using the `assets` build option. The current implementation of only allowing moving things into the public folder is not only inconsistent with other executors but is also less flexible. I don't see the issue with making users put the `public` prefix in the assets options if they need it to go into that folder.

We have a use case that we need to copy our `.npmrc` into the parent build directory of the next.js project so `npm i` works. But the assets build option does not allow us to do so. 

Another use case is if we have environment-specific files that we want to load and we need to copy them into the build.

## Motivation

Consistency and more flexibility. 

## Suggested Implementation

Remove the automatic public prefix for the Next.js builder here https://github.com/nrwl/nx/blob/67ff4acea20300de7ae316a957d310cd4fb40e5e/packages/next/src/utils/config.ts#L137. Create a migration to prefix all current asset outputs for next.js project with the public prefix.

**Comment by danielr18** [comment]
Here's my temporary solution until this gets implemented:

```js
const withNx = require('@nrwl/next/plugins/with-nx');
const path = require('path');
const { createCopyPlugin } = require('@nrwl/web/src/utils/config');
const { normalizeAssets } = require('@nrwl/web/src/utils/normalize');

const nextConfig = {
  webpack: (config, { isServer }) => {
    const workspaceRoot = process.env.NX_WORKSPACE_ROOT;
    if (workspaceRoot) {
      const assets = ['apps/web/.env'];
      if (isServer && Array.isArray(assets) && assets.length > 0) {
        const projectRoot = path.join(
          workspaceRoot,
          'apps',
          process.env.NX_TASK_TARGET_PROJECT
        );
        config.plugins.push(
          createCopyPlugin(
            normalizeAssets(assets, workspaceRoot, projectRoot).map(
              (asset) => ({
                ...asset,
                output: path.join('../', asset.output),
              })
            )
          )
        );
      }
    }
    return config;
  },
};

module.exports = withNx(nextConfig);

```

**Comment by marko-hologram** [comment]
@flippidippi would something like this work for you?

```json
"build": {
  "executor": "@nrwl/next:build",
  "outputs": ["{options.outputPath}"],
  "defaultConfiguration": "production",
  "options": {
    "root": "apps/my-app",
    "outputPath": "dist/apps/my-app",
    "assets": [
      {
        "input": "apps/my-app",
        "glob": ".npmrc",
        "output": "./.."
      }
    ]
  },
  "configurations": {
    "production": {}
  }
},
```

I tested this and I managed to copy a file outside of public folder by using `./..` as output for asset definition.

**Comment by flippidippi** [comment]
@marko-hologram I swear I had tried that, but nx fussed at me for trying to put something outside of the public folder 🤷 

It seems to work.

**Comment by marko-hologram** [comment]
> @marko-hologram I swear I had tried that, but nx fussed at me for trying to put something outside of the public folder 🤷
> 
> It seems to work. Thanks!

`./` is important. I couldn't get it to work by using just `..`, had to make sure that `./` is at the beginning.
