### ISSUE TITLE
Cannot serve/build application after converting angular repo to nx repo.

### ISSUE THREAD

**Issue by Exslims** [nrwl/nx#7942]
## Current Behavior
Hello! I got TypeError: Cannot read property 'default' of undefined in project-graph.js 
`const useDaemonProcessOption = (_b = (_a = nxJson.tasksRunnerOptions['default']) === null || _a === void 0 ? void 0 : _a.options) === null || _b === void 0 ? void 0 : _b.useDaemonProcess;` 
after running any commands like npx nx serve <app-name> or smth else.
Guess it is because in nx.json file there are no populated tasksRunnerOptions and default properties. I am not sure but maybe you need to add additional **if** like nxJson.tasksRunnerOptions && nxJson.tasksRunnerOptions['default'].
When I manually fix this line of code to avoid this error everything is ok.
## Expected Behavior
Command like npx nx serve <app-name> is working.

## Steps to Reproduce

1. Install the latest angular@cli globally (>13)
2. Do **ng new** project
3. Convert angular repo to nx repo by doing **ng add @nrwl/workspace** command
4. Run npx nx serve <your-app-name>

### Failure Logs

> (node:14778) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'default' of undefined
    at /Users/konstantinkupcov/Work/sherpu-frontend/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:47:77
    at Generator.next (<anonymous>)
    at /Users/konstantinkupcov/Work/sherpu-frontend/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/Users/konstantinkupcov/Work/sherpu-frontend/node_modules/tslib/tslib.js:113:16)
    at createProjectGraphAsync (/Users/konstantinkupcov/Work/sherpu-frontend/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:45:34)
    at Object.<anonymous> (/Users/konstantinkupcov/Work/sherpu-frontend/node_modules/@nrwl/workspace/src/command-line/run-one.js:18:80)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/konstantinkupcov/Work/sherpu-frontend/node_modules/tslib/tslib.js:114:62)

### Environment

>  Node : 12.22.7
  OS   : darwin x64
  npm  : 6.14.15
  
  nx : undefined
  @nrwl/angular : 13.2.3
  @nrwl/cli : 13.2.3
  @nrwl/cypress : 13.2.3
  @nrwl/devkit : 13.2.3
  @nrwl/eslint-plugin-nx : undefined
  @nrwl/express : undefined
  @nrwl/jest : 13.2.3
  @nrwl/linter : 13.2.3
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.3
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.3
  @nrwl/storybook : 13.2.3
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.2
         @angular/common: 13.0.2
         @angular/compiler: 13.0.2
         @angular/core: 13.0.2
         @angular/forms: 13.0.2
         @angular/platform-browser: 13.0.2
         @angular/platform-browser-dynamic: 13.0.2
         @angular/router: 13.0.2
         @taiga-ui/core: 2.24.0
         @angular-devkit/build-angular: 13.0.3
         @angular/cli: 13.0.3
         @angular/compiler-cli: 13.0.2

**Comment by iKrishnaSahu** [comment]
I am also facing the same issue while running nx commands like affected.

@Exslims is there any workaround?

**Comment by AgentEnder** [comment]
Hey, I just looked into this and it was fixed in #7814, and will be part of 13.3's release. Thanks for reporting this!

I'm going to close out this issue, since the fix has been merged. Feel free to open a new issue if something else comes up, or let me know if you feel the issue needs to be reopened.

**Comment by Exslims** [comment]
Thank you!
