### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'type')

### ISSUE THREAD

**Issue by davidfmatheson** [nrwl/nx#7951]
## Current Behavior
```
$ nx --version
/Users/davidmatheson/.nvm/versions/node/v16.13.0/lib/node_modules/@nrwl/cli/bin/nx.js:6
if (workspace.type === 'nx') {
              ^

TypeError: Cannot read properties of null (reading 'type')
    at Object.<anonymous> (/Users/davidmatheson/.nvm/versions/node/v16.13.0/lib/node_modules/@nrwl/cli/bin/nx.js:6:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

## Expected Behavior
```
$ nx --version
>  NX  The current directory isn't part of an Nx workspace.

  To create a workspace run:
  npx create-nx-workspace@latest <workspace name>


>  NX   NOTE  For more information please visit https://nx.dev/
```

## Steps to Reproduce
```
$ cd ~
$ npm install -g @nrwl/cli@13.2.2
$ nx --version
$ npm install -g @nrwl/cli@13.2.3
$ nx --version
```

### Failure Logs
I believe that [this commit](https://github.com/nrwl/nx/commit/e666d3fdf0655adbd6488d073c3ef530e8f40113) was the breaking change.

### Environment
Mac OS 12.0.1
Node 16.13.0
NPM 8.1.4

**Comment by andyjessop** [comment]
I'm getting the same error. I assume that all commands have to be run from within a workspace.

**Comment by davidfmatheson** [comment]
@andyjessop it will work if you are within a workspace, it's just it used to work regardless of where you were. I am realizing now that it never did report the version, though, which was the reason I would run that command. Anyway, the behavior changed between 13.2.2 and 13.2.3, so they can prioritize it however they want :)

**Comment by AgentEnder** [comment]
@leosvelperez I'm sending this your way since you touched the logic recently. Do you care to move the ` if (!workspace ` logic up? 

If --version actually worked it'd be ideal, but it's fine to just log the appropriate error message too.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

I'll close the issue since it has already been fixed in https://github.com/nrwl/nx/commit/a4e97c735628b444a9b0358b21223a943c72b5b4. The fix should be released soon so please keep an eye on the releases.
