### ISSUE TITLE
[nrwl/workspace:move] Does not change 'dest' property in ng-package.json

### ISSUE THREAD

**Issue by bjesuiter** [nrwl/nx#7969]
I used the nrwl/workspace:move command and the my build broke. 
Reason: 
The move generator did not adjust the output path in ng-package.json. 

This MAY be my fault, I have to look up whether the angular generator has a move function. 

But anyway, the `workspace:move` generator should output a warning in this case, that this move should be done via the angular generator, or better yet, 
do the move with the angular generator transparently under the hood! :)

Original commenter, which had the same problem: 

> In my case, the @nrwl/angular:move command forgot to change the path set in libs/YOUR LIBRARY/ng-package.json. In any case someone (or my future me) stumbles over this issue again: Check the dist folder output!
> 
_Originally posted by @maxfriedmann in https://github.com/nrwl/nx/issues/2463#issuecomment-831727290_

**Comment by AgentEnder** [comment]
The @nrwl/angular:move generator wraps @nrwl/workspace:move, adding some additional functionality. Adding checks inside @nrwl/workspace:move or warnings would warn when being ran from the angular move generator, and may not be needed if the project doesn't use angular.

So long as @nrwl/angular:move is doing the changes needed, this is working as it should.
