### ISSUE TITLE
wrong build order after upgrading to nx 13

### ISSUE THREAD

**Issue by platon-rov** [nrwl/nx#7974]
## Current Behavior

I have the following structure of the libraries in monorepo

```
- core
  - core-libA
  - core-libB
  ...
- platform // depends on core
  - platform-libA // depends on core-libA
  - platform-libB // depends core-libB
  ...
```

When I try to run `nx build platform` building some of its sub-packages failed with errors like

```
Some of the project platform-lib* dependencies have not been built yet. Please build these libraries before:
- ***
```

```
error TS2307: Cannot find module ...
```

If I try to run `nx build core && nx build platform` it builds. So, if I have a cache for `core` then `platform` builds. 

If I try to run `nx build platform-lib*` (which throws an error when I try to build the whole `platform`) it builds, even without the cache. 

If I add `core` as `implicitDepencesies` for the failing `platform-lib*` packages then the whole `platform` builds. So the root of the issue is the determining order of packages to build.

## Expected Behavior

The order of building packages is proper and no errors are thrown.

## Steps to Reproduce

```
git clone --branch feat/migrate-nx-ng13 git@github.com:SAP/fundamental-ngx.git && 
cd fundamental-ngx && 
git reset --hard 0db4cf7dd44a1cf0d6b35501508932f2d9eba227 && 
npm i && 
nx build platform
```

```
// Works
rm -rf dist && nx clear-cache && nx build core && nx build platform

// works but previously failed when tried to build the whole platform
rm -rf dist && nx clear-cache && nx build platform-table
```

### Failure Logs

See above, in the description

### Environment

```
➜  ~ npx nx report
Cannot read property 'type' of null
```

Mac M1, arm64
MacOS 12.0.1
NodeJS 14.18.2 x64, NodeJS 16.13.1 arm64

The issue also persists on x64 machines.

**Comment by KamalAman** [comment]
Yes, this is very annoying. 

Adding [implicit-dependencies](https://nx.dev/l/n/core-concepts/configuration#implicit-dependencies) resolved the issue for me

**Comment by Lightw3ight** [comment]
I have the same issue, when I try to build a library, it says
`Some of the project xxx dependencies have not been built yet. Please build these libraries before:`

It also tells me to
`Try: nx run aspect-ui:build --with-deps`

Which I would normally use, however running that has the same effect except it gives a deprecation warning

`DEPRECATION WARNING: --with-deps is deprecated and it will be removed in v14.
Configure target dependencies instead: https://nx.dev/configuration/projectjson`

**Comment by Lightw3ight** [comment]
> Yes, this is very annoying.
> 
> Adding [implicit-dependencies](https://nx.dev/l/n/core-concepts/configuration#implicit-dependencies) resolved the issue for me for now.

I tried this but it made no difference for me unfortunately

**Comment by Lightw3ight** [comment]
Ive worked out what I think the issue was for me

My build config for my app in my `angular.json` looked like this

```json
"build": {
    "builder": "@nrwl/angular:package",
    "options": {
        "tsConfig": "libs/aspect/ui/tsconfig.lib.json",
        "project": "libs/aspect/ui/ng-package.json"
    },
    "configurations": {
        "production": {
            "tsConfig": "libs/aspect/ui/tsconfig.lib.prod.json"
        }
    },
    "dependsOn": [
        {
            "target": "pre-build",
            "projects": "self"
        }
    ]
}
```

I also hav `targetDependencies` set up in my `nx.json` as per default
```json
"targetDependencies": {
    "build": [
        {
            "target": "build",
            "projects": "dependencies"
        }
    ]
},
```

I presumed that my `dependsOn` in my build config would be inheriting from `targetDependencies` in my `nx.json`.
However it appears that `dependsOn` **overwrites** `targetDependencies` because if I remove `dependsOn` from my build config **or** I copy the `targetDependencies` to my `dependsOn`, the build runs fine.

So now my libraries build config looks like this and the build works fine
```json
"build": {
    "builder": "@nrwl/angular:package",
    "options": {
        "tsConfig": "libs/aspect/ui/tsconfig.lib.json",
        "project": "libs/aspect/ui/ng-package.json"
    },
    "configurations": {
        "production": {
            "tsConfig": "libs/aspect/ui/tsconfig.lib.prod.json"
        }
    },
    "dependsOn": [
        {
            "target": "build",
            "projects": "dependencies"
        },
        {
            "target": "pre-build",
            "projects": "self"
        }
    ]
}
```

Im not sure if this is a bug or not but I think it would be more intuitive if a libraries build config `dependsOn` were to inherit from the `targetDependencies` defined in your `nx.json`
