### ISSUE TITLE
nx cloud not updated during migration, gets an error

### ISSUE THREAD

**Issue by MatznRisto** [nrwl/nx#7983]
Hi, hope this is not somewhere as an issue. Did not find it though.

Thank you for your good work.
## Current Behavior
When i migrate to nx next (current 13.3.0-beta.4) also the case before in beta.3, then i can't start any nx command. I get an error. When i update nx cloud to newest beta it works

## Expected Behavior
nx migrate next should also update nx-cloud to newest beta.

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs
(node:21476) UnhandledPromiseRejectionWarning: Error: If you are using Nx Cloud, update the version of @nrwl/nx-cloud to >=13.0.0
    at tasksRunnerV2 (D:\repositories\dytab\node_modules\@nrwl\workspace\src\tasks-runner\tasks-runner-v2.js:14:15)
    at cloudEnabledTasksRunner (D:\repositories\dytab\node_modules\@nrwl\nx-cloud\lib\core\runners\cloud-enabled\cloud-enabled.runner.js:1:5333)
    at nxCloudTasksRunner (D:\repositories\dytab\node_modules\@nrwl\nx-cloud\lib\nx-cloud-tasks-runner.js:51:63)
    at D:\repositories\dytab\node_modules\@nrwl\workspace\src\tasks-runner\run-command.js:52:37
    at Generator.next (<anonymous>)
    at D:\repositories\dytab\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (D:\repositories\dytab\node_modules\tslib\tslib.js:113:16)
    at runCommand (D:\repositories\dytab\node_modules\@nrwl\workspace\src\tasks-runner\run-command.js:30:34)
    at Object.<anonymous> (D:\repositories\dytab\node_modules\@nrwl\workspace\src\command-line\run-many.js:23:38)`

### Environment

  Node : 14.17.5
  OS   : win32 x64
  npm  : 7.5.6

  nx : 13.3.0-beta.4
  @nrwl/angular : 13.3.0-beta.4
  @nrwl/cli : 13.3.0-beta.4
  @nrwl/cypress : 13.3.0-beta.4
  @nrwl/devkit : 13.3.0-beta.4
  @nrwl/eslint-plugin-nx : 13.3.0-beta.4
  @nrwl/express : undefined
  @nrwl/jest : 13.3.0-beta.4
  @nrwl/linter : 13.3.0-beta.4
  @nrwl/nest : 13.3.0-beta.4
  @nrwl/next : undefined
  @nrwl/node : 13.3.0-beta.4
  @nrwl/nx-cloud : 12.5.4
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.0-beta.4
  @nrwl/web : undefined
  @nrwl/workspace : 13.3.0-beta.4
  @nrwl/storybook : 13.3.0-beta.4
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.0
         @angular/cdk: 13.0.0
         @angular/common: 13.0.0
         @angular/compiler: 13.0.0
         @angular/core: 13.0.0
         @angular/forms: 13.0.0
         @angular/material: 13.0.0
         @angular/platform-browser: 13.0.0
         @angular/platform-browser-dynamic: 13.0.0
         @angular/router: 13.0.0
         @datorama/akita: 6.2.4
         @ngneat/helipopper: 4.3.0
         @ngneat/transloco: 3.1.1
         @angular-devkit/architect: 0.1300.3
         @angular-devkit/build-angular: 13.0.3
         @angular/cli: 13.0.3
         @angular/compiler-cli: 13.0.0
         @angular/language-service: 13.0.0
         @ngneat/spectator: 8.0.4
         @storybook/angular: 6.4.0-rc.3

**Comment by mrodrigues95** [comment]
Getting the same thing on my end on `13.3.0-beta.18`. Upgrading `@nrwl/nx-cloud` to `>=13.0.0` as the error suggests does not fix it either.

**Comment by trungpq163** [comment]
I've got the same bug when running build on Vercel. 
I changed nx-cloud package by suggests ("@nrwl/nx-cloud": "lastest" => "@nrwl/nx-cloud": "^13.0.0") and It worked.

**Comment by StalkAltan** [comment]
Hi all in this thread!

We generally try and keep @nrwl/nx-cloud compatible with the two most recent versions of Nx (at time of writing, this would be Nx 13 and 14), so it's often best to keep the version committed as "latest" in your package.json.

Nx 13 had a lot of internal restructuring that broke the compatibility sometimes, but this is a rare occurrence and should be resolved moving forward. For that reason, I'm closing this issue.

Thanks!

**Comment by mikestecker** [comment]
@StalkAltan I just attempted updating to the latest as of today (going from 14.1.4 -> 14.2.1) and ran into the same issue with @nrwl/nx-cloud

**Comment by StalkAltan** [comment]
Hi @mikestecker, apologies for the delay.

Can you send the output of `nx report` and the contents of your `nx.json` file, excluding your Nx Cloud access token and anything else that might need to stay private?

**Comment by mikestecker** [comment]
> Hi @mikestecker, apologies for the delay.
> 
> Can you send the output of `nx report` and the contents of your `nx.json` file, excluding your Nx Cloud access token and anything else that might need to stay private?

The latest update (as of today) for 14.3.6 seems to no longer have this issue.
