### ISSUE TITLE
Generator migrate-defaults-5-to-6 fails for Nx13

### ISSUE THREAD

**Issue by Wimpert** [nrwl/nx#7989]
## Current Behavior

When using `nx g @nrwl/angular:storybook-migrate-defaults-5-to-6` in Nx13, I get the following error:

`Cannot find configuration for 'undefined' in /angular.json.`

## Expected Behavior
The generator should run without throwing an error.

## Steps to Reproduce

Try running Nx g @nrwl/angular:storybook-migrate-defaults-5-to-6 in any Nx13 workspace using storybook.
 

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

Cannot find configuration for 'undefined' in /angular.json.

### Environment

```
 Node : 16.6.0
  OS   : darwin x64
  npm  : 7.19.1
  
  nx : 13.2.3
  @nrwl/angular : 13.2.3
  @nrwl/cli : 13.2.3
  @nrwl/cypress : 13.2.3
  @nrwl/devkit : 13.2.3
  @nrwl/eslint-plugin-nx : 13.2.3
  @nrwl/express : undefined
  @nrwl/jest : 13.2.3
  @nrwl/linter : 13.2.3
  @nrwl/nest : 13.2.3
  @nrwl/next : undefined
  @nrwl/node : 13.2.3
  @nrwl/nx-cloud : 12.5.4
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.3
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.3
  @nrwl/storybook : 13.2.3
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.3
         @angular/cdk: 13.0.3
         @angular/common: 13.0.3
         @angular/compiler: 13.0.3
         @angular/core: 13.0.3
         @angular/forms: 13.0.3
         @angular/google-maps: 13.0.3
         @angular/localize: 13.0.3
         @angular/material: 13.0.3
         @angular/platform-browser: 13.0.3
         @angular/platform-browser-dynamic: 13.0.3
         @angular/platform-server: 13.0.3
         @angular/router: 13.0.3
         @ngrx/component-store: 13.0.1
         @nguniversal/express-engine: 13.0.1
         @nx-aws-plugin/nx-aws-cache: 0.0.5
         @scullyio/init: 1.1.4
         @angular-devkit/build-angular: 13.0.4
         @angular/cli: 13.0.4
         @angular/compiler-cli: 13.0.3
         @angular/language-service: 13.0.3
         @nguniversal/builders: 13.0.1
         @storybook/angular: 6.4.4
```

**Comment by mandarini** [comment]
Hi @leosvelperez here's the issue. I managed to reproduce in a new Nx 13 workspace using Storybook. Even if I do have the latest Storybook configuration, the migrator should not fail, it should exit gracefully. I assume this is related to the new `project.json` and `workspace.json` layouts. Let's look into it. 

Thank you @Wimpert for finding this bug!

**Comment by mandarini** [comment]
So, this issue can be skipped if we use the `nx g @nrwl/storybook:migrate-defaults-5-to-6` directly, and not the `@nrwl/angular:storybook-migrate-defaults-5-to-6` generator. Will look into this eventually, but for now one should be good to use the workaround!

**Comment by Wimpert** [comment]
@mandarini Thx a lot for the great support on this!

**Comment by mandarini** [comment]
@Wimpert [here's the MR](https://github.com/nrwl/nx/pull/7990) that solves the issue properly!

**Comment by Wimpert** [comment]
@mandarini awesome, thx!
