### ISSUE TITLE
Unable to include styles in Storybook for Angular 13

### ISSUE THREAD

**Issue by literalpie** [nrwl/nx#7992]
## Current Behavior
In Angular <=12, the @nrwl/storybook builder can be used to build storybook. Styles can be included by adding styles to a `"storybook:build"` architect in the angular.json. This was kind of "magic" (in a bad way), but it worked.

In Angular >=13, storybook made [this change](https://github.com/storybookjs/storybook/pull/16644#issuecomment-965645077) which no longer lets you set styles using the magic behavior of the 'storybook:build' architect. If someone wants to set styles of a storybook build, they can use the '@storybook/angular:start-storybook' builder instead of the nrwl builder.

## Expected Behavior
There should be a way to use the @nrwl/storybook builder and get styles. One way to do this would be to add a 'browserTarget' option to the builder, which is how the '@storybook/angular:start-storybook' builder works. Or maybe it should just be recommended that everyone uses the storybook builder going forward.

## Steps to Reproduce
I can create a minimal reproduction if needed, but I think the above should be enough information.

### Failure Logs
N/A

### Environment
This applies to Angular >= 13 and storybook>=6.4

**Comment by mandarini** [comment]
Hi there @literalpie ! Maybe we could mark this as "feature request"?

**Comment by literalpie** [comment]
I'm okay with that. I was on the fence in which it should be. I went with bug because something isn't possible that should be/used to be possible.

**Comment by mandarini** [comment]
Hi there!

I think this is no longer an issue, and it got fixed in the latest versions! :) So, closing this!

You can add styles now as normal!
