### ISSUE TITLE
Cypress - `--parallel` flag is omitted

### ISSUE THREAD

**Issue by danr-za** [nrwl/nx#8014]
## Current Behavior
When running `nx run app:e2e --parallel`, the parallel flag is omitted

```shell
➜  app git:(main) nx e2e app-e2e --parallel --ciBuildId=test --group=group --key=key                    

> nx run app-e2e:e2e --ciBuildId=test --group=group --key=key 

```

## Expected Behavior
The parallel flag should be passed

## Steps to Reproduce
* Create a repo with an app together with e2e
* Run `nx run app:e2e --parallel`

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment
```shell
Node : 16.13.0
  OS   : darwin x64
  yarn : 3.1.0
  
  nx : 13.2.3
  @nrwl/angular : undefined
  @nrwl/cli : 13.2.3
  @nrwl/cypress : 13.2.3
  @nrwl/devkit : 13.2.3
  @nrwl/eslint-plugin-nx : 13.2.3
  @nrwl/express : undefined
  @nrwl/jest : 13.2.3
  @nrwl/linter : 13.2.3
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.2.3
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.2.3
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.3
  @nrwl/web : 13.2.3
  @nrwl/workspace : 13.2.3
  @nrwl/storybook : 13.2.3
  @nrwl/gatsby : undefined
  typescript : 4.5.2
  rxjs : 6.6.7

```

**Comment by kpl1** [comment]
Hey there! 
Same issue for me. 

The only workaround I found is to add "-" 
Instead of having " --parallel ", I have "-- -- --parallel".

**Comment by danr-za** [comment]
Closing as it works with @kpl1 's comment
