### ISSUE TITLE
Add affected:xi18n support

### ISSUE THREAD

**Issue by vitalyiegorov** [nrwl/nx#802]
Hi @vsavkin our project is multilingual and we would love to have `affected:*` support for this command, also we are using `@ngx-translate/i18n-polyfill/extractor/ngx-extractor` for inside code translations,

So a generic approach to run any command according to projects building logic by `affected` would be very cool. 

Any plans towards this direction?

**Comment by minijus** [comment]
Having a translation management strategy/solution would be interesting to me as well. In company I work we are migrating AngularJS applications where deployable apps are composed of 50+ smaller apps. These smaller apps holds their own translations and webpack merges these translations during build.

We find it very useful and practical having translations isolated on "lib" modules. Thus, it would be nice to have similar solution using nx workspace.
