### ISSUE TITLE
jest 'setupFilesAfterEnv' with <rootDir> breaks libs tests

### ISSUE THREAD

**Issue by Tirke** [nrwl/nx#8029]
Kind of same issue as #2344.
I have a monorepo with some nest apps and some libs.
 
## Current Behavior
root `jest.preset.js` is 
```
/** @type {import('@jest/types').Config.InitialOptions} */

const nxPreset = require('@nrwl/jest/preset')

module.exports = {
  ...nxPreset,
  logHeapUsage: true,
  setupFilesAfterEnv: ['<rootDir>/jest.setup.after.env.js'],
  transform: {
    '^.+\\.ts$': 'babel-jest',
  },
}
```
package `jest.config.js` is 
```
/** @type {import('@jest/types').Config.InitialOptions} */

module.exports = {
  displayName: 'aws',
  preset: '../../jest.preset.js',
  testEnvironment: 'node',
  moduleFileExtensions: ['ts', 'js', 'html', 'json'],
  coverageDirectory: '../../coverage/libs/aws',
}
```

Running the test outputs an error
```
❯ nx run aws:test --skip-nx-cache

> nx run aws:test
● Validation Error:

  Module <rootDir>/jest.setup.after.env.js in the setupFilesAfterEnv option was not found.
         <rootDir> is: /Users/tirke/code/nx-nest-prisma/libs/aws

  Configuration Documentation:
  https://jestjs.io/docs/configuration


———————————————————————————————————————————————

>  NX   ERROR  Running target "aws:test" failed

  Failed tasks:

  - aws:test

  Hint: run the command with --verbose for more details.
```

I believe that when a libs has a package.json, jest switches the `<rootDir>` to the directory where the package.json lives. Removing the package.json solves the issue, but I want to publish the lib so I need the package.json.

## Expected Behavior
Properly resolve `<rootDir>` when setupFiles are being used for jest config.

## Steps to Reproduce
Here is the PR with repro 
https://github.com/nrwl/nx-examples/pull/178
Added a demo lib with the setup I'm explaining here.

### Environment

```
❯ nx report

>  NX  Report complete - copy this into the issue template

  Node : 16.13.1
  OS   : darwin arm64
  yarn : 1.22.17

  nx : 13.2.3
  @nrwl/angular : undefined
  @nrwl/cli : 13.2.3
  @nrwl/cypress : 13.2.3
  @nrwl/devkit : 13.2.3
  @nrwl/eslint-plugin-nx : 13.2.3
  @nrwl/express : undefined
  @nrwl/jest : 13.2.3
  @nrwl/linter : 13.2.3
  @nrwl/nest : 13.2.3
  @nrwl/next : undefined
  @nrwl/node : 13.2.3
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.3
  @nrwl/web : 13.2.3
  @nrwl/workspace : 13.2.3
  @nrwl/storybook : undefined
  @nrwl/gatsby : undefined
  typescript : 4.3.5
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:

(node:91798) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/tirke/code/nx-nest-prisma/node_modules/@elastic/elasticsearch/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:91798) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/tirke/code/nx-nest-prisma/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
```

**Comment by joshfarrant** [comment]
Did you get anywhere with this? I'm seeing the same thing and struggling to figure out a tidy solution.

**Comment by barbados-clemens** [comment]
this looks like it's the same behavior as the jest cli so unsure if this is something we can "fix". I'll spend some more time to see if there's something we can do internally to nx but we try to make sure what works via nx jest plugin also works via the jest cli to prevent breaking editor plugins for instance. 

in this case you can just not use the `<rootDir>` in the path to the file and use relative pathing since this file is at the root of the directory. 

i.e. 
```diff
- setupFilesAfterEnv: ['<rootDir>/jest.setup.after.env.js'],
+ setupFilesAfterEnv: ['./jest.setup.after.env.js']
```

you could optionally copy the jest.setup.after.env.js into every library that needs it if so desired (though not ideal)

hopefully that'll help some @joshfarrant and @Tirke

**Comment by joshfarrant** [comment]
Thanks @barbados-clemens - weirdly changing it to use `<rootDir>/jest.setup.js` still doesn't work. It still tries to look in my lib's directory for it. It doesn't look like `<rootDir>` points to the right place

```
> nx run shared-theme:test

● Validation Error:

  Module ./jest.setup.after.env.js in the setupFilesAfterEnv option was not found.
         <rootDir> is: /Users/joshfarrant/code/nx/libs/shared/theme

  Configuration Documentation:
  https://jestjs.io/docs/configuration
```

I'd expect `<rootDir>` to point to `/Users/joshfarrant/code/nx`

**Comment by barbados-clemens** [comment]
@joshfarrant you'd want to remove the usage of `<rootDir>` and just relative path to the file as I showed. I'm not 100% sure if changing the root makes sense to the root of nx workspace because that would mean the pathing for all the projects would be off and you'd end up testing the entire repo test files when invoking a project tests target. 
you can try via the `--roots` flag and provide the root of the repo as another root to search into. 
https://jestjs.io/docs/cli#--roots

**Comment by joshfarrant** [comment]
Sorry, that's what comes of replying to issues first thing in the morning! No joy without the `<rootDir>` either unfortunately. Makes sense why that wouldn't work now in hindsight.

I've tried what feels like all possible options for `setupFilesAfterEnv`, I'll probably just leave it now and have separate setups for each lib.

**Comment by joshfarrant** [comment]
I can try to put a minimal reproduction together to see what happens then share that if the issue persists.

**Comment by barbados-clemens** [comment]
@Lonli-Lokli you just use relative pathing from the jest config to the path you want.

**Comment by Lonli-Lokli** [comment]
@barbados-clemens It's manual work, espcially with different project structures, eg whn you have secondary entry points...

RootDir by it's name should point to the root, not lib

**Comment by barbados-clemens** [comment]
@Lonli-Lokli [this is the documented behavior of jest.](https://jestjs.io/docs/configuration#rootdir-string) 
you are more the welcome to set it to whatever you want in your jest config. 

> Default: The root of the directory containing your Jest [config file](https://jestjs.io/docs/configuration#) or the package.json or the [pwd](http://en.wikipedia.org/wiki/Pwd) if no package.json is found
