### ISSUE TITLE
Storybook fails on clean install

### ISSUE THREAD

**Issue by Cuboctaedro** [nrwl/nx#8032]
## Current Behavior
Storybook fails on a clean Next app inside a new workspace. I am getting this error:
ModuleNotFoundError: Module not found: Error: Can't resolve '../src/app' in 'C:\0_nelios\e-consierge\econcierge-nx\apps\hotel\.storybook'
and also an erro in the tsconfig of the Next app:
Referenced project '......./econcierge-nx/apps/hotel/.storybook/tsconfig.json' must have setting "composite": true.ts

## Steps to Reproduce
I have the problem on a workspace I am working but I have reproduced it on a clean project here: 
https://github.com/Cuboctaedro/nx-test
All the steps I have taken were:
- npx create-nx-workspace@latest (empty workspace)
- npm install -D @nrwl/nest
- nx g @nrwl/nest:application api
- npm install -D @nrwl/next
- nx g @nrwl/next:application hotel
- npm install -D @nrwl/storybook
- nx g @nrwl/react:storybook-configuration hotel
- nx run hotel:storybook

### Environment
  Node : 16.13.0
  OS   : win32 x64
  npm  : 8.1.0
  
  nx : 13.2.3
  @nrwl/angular : undefined
  @nrwl/cli : 13.2.3
  @nrwl/cypress : 13.2.3
  @nrwl/devkit : 13.2.3
  @nrwl/eslint-plugin-nx : 13.2.3
  @nrwl/express : undefined
  @nrwl/jest : 13.2.3
  @nrwl/linter : 13.2.3
  @nrwl/nest : 13.2.3
  @nrwl/next : 13.2.3
  @nrwl/node : 13.2.3
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.2.3
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.3
  @nrwl/web : 13.2.3
  @nrwl/workspace : 13.2.3
  @nrwl/storybook : 13.2.3
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:

**Comment by puku0x** [comment]
@Cuboctaedro I guess your console told you a useful message like following.

```
/nx-test-main/apps/hotel/src/app doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve '../src/app' in '/nx-test-main/apps/hotel/.storybook'
```

Resolving `../src/app` is the common use case of `@nrwl/react` but you need some modifications for `@nrwl/next`.

The first step is to fix the paths for stories.

```js
// apps/hotel/.storybook/main.js
const rootMain = require('../../../.storybook/main');

module.exports = {
  ...rootMain,

  core: { ...rootMain.core, builder: 'webpack5' },

  stories: [
    ...rootMain.stories,
    '../**/*.stories.mdx',  // 👈 change here
    '../**/*.stories.@(js|jsx|ts|tsx)',  // 👈 and here for your Next.js app  
  ],
```

You may need to modify `apps/**/.storybook/preview.js` (optional).

```js
import * as NextImage from 'next/image';

import '../pages/styles.css';  // 👈 this is needed for your global styles, others are optional

export const parameters = {
  controls: {
    expanded: true,
  },
};

// https://storybook.js.org/blog/get-started-with-storybook-and-next-js/
const OriginalNextImage = NextImage.default;

// eslint-disable-next-line no-import-assign
Object.defineProperty(NextImage, 'default', {
  configurable: true,
  value: (props) => <OriginalNextImage {...props} unoptimized />,
});
```

And add `.babelrc`. This means you cannot use SWC for Storybook.

```js
{
  "presets": ["@nrwl/next/babel"],
  "plugins": []
}
```

Finally, you should fix `tsconfig.json` which was messed by `nx g @nrwl/react:storybook-configuration`.

```js
// apps/**/tsconfig.json
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "jsx": "preserve",
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "types": ["node", "jest"],
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "resolveJsonModule": true,
    "isolatedModules": true
  },
  "files": [],
  "include": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.spec.json"
    },
    {
      "path": "./.storybook/tsconfig.json"
    }
  ]
}
```
```js
// apps/**/tsconfig.app.json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "types": ["node"]
  },
  "files": [
    "../../node_modules/@nrwl/react/typings/cssmodule.d.ts",
    "../../node_modules/@nrwl/react/typings/image.d.ts",
    "../../node_modules/@nrwl/next/typings/image.d.ts"
  ],
  "exclude": [
    "**/*.spec.js",
    "**/*.spec.jsx",
    "**/*.spec.ts",
    "**/*.spec.tsx",
    "**/*.stories.js",
    "**/*.stories.jsx",
    "**/*.stories.ts",
    "**/*.stories.tsx"
  ],
  "include": ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx", "next-env.d.ts"]
}
```
```js
// apps/**/tsconfig.spec.json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "module": "commonjs",
    "types": ["jest", "node", "@testing-library/jest-dom"]
  },
  "files": [
    "../../node_modules/@nrwl/react/typings/cssmodule.d.ts",
    "../../node_modules/@nrwl/react/typings/image.d.ts",
    "../../node_modules/@nrwl/next/typings/image.d.ts"
  ],
  "include": [
    "**/*.spec.js",
    "**/*.spec.jsx",
    "**/*.spec.ts",
    "**/*.spec.tsx",
    "**/*.stories.js",
    "**/*.stories.jsx",
    "**/*.stories.ts",
    "**/*.stories.tsx",
    "**/*.d.ts"
  ]
}
```

I see this procedure looks complicated a little, but it is the only way to handle Storybook for Next.js project until `@nrwl/next` supports it.

Here is a working sample. I hope it helps you.
https://github.com/puku0x/nx-nextjs-storybook-sample

**Comment by Cuboctaedro** [comment]
I have managed to make it work without errors folowing the working sample. In the file apps/**/tsconfig.app.json I had to move the .stories files to include to stop getting an error in all of them. The sample is realy helpfull, maybe it should be mentioned in the docs.

**Comment by mandarini** [comment]
Linking [this issue](https://github.com/nrwl/nx/issues/9010) here.

**Comment by Qwal** [comment]
It started to work after I included this addon: https://github.com/Karibash/storybook-addon-swc in `<root>/.storybook/main.js`

**Comment by jaysoo** [comment]
Found one issue with the `stories` generator, once that's fixed we can close this issue.
