### ISSUE TITLE
Add `.env` (etc.) to `.gitignore`

### ISSUE THREAD

**Issue by somebody1234** [nrwl/nx#8040]
## Description

`.env` (and variants) should probably always be in `.gitignore`.

## Motivation

Anyone using `.env` will have to manually add it anyway - I don't think it would hurt?  
And since this would ideally only happen at generation time, this shouldn't affect existing users.

**Comment by adamwdennis** [comment]
`.env` should not be in .gitignore, only the `*local*` variants (e.g. `.env.local` or `.local.env`)

**Comment by saby22** [comment]
I am curious as to why these files aren't ignored during the scaffolding process
