### ISSUE TITLE
Add processing environment variables via {env.variable} to @nrwl/workspace:run-commands beside {argv.variable}

### ISSUE THREAD

**Issue by solarfrantz** [nrwl/nx#8044]
## Description
Right now it's already possible to process arguments in `@nrwl/workspace:run-commands` but I think it would be useful to allow processing also of environment variables.

## Motivation
Possibility to pass variables via the environment. Right now I have a use case where I wanted to pass some variables processed from an executor to a docker command and the only way I see to share those vars is via environment.

## Suggested Implementation
It would suffice to enhance the code for from `transformCommand` https://github.com/nrwl/nx/blob/master/packages/workspace/src/executors/run-commands/run-commands.impl.ts#L247 by handling also `process.env`.

**Comment by jbadeau** [comment]
Is there a solution for this?

**Comment by jbadeau** [comment]
Can we reopen this or is there another solution?

**Comment by jbadeau** [comment]
Hello?
