### ISSUE TITLE
No name was provided for external module '@ngrx/store' in output.globals – guessing 'store'

### ISSUE THREAD

**Issue by LloydTDavies** [nrwl/nx#806]
Getting issues when trying to build a publishable lib from my workspace.
Here's the build output.

I have the below packages as peer dependencies.

Building Angular Package
Building entry point '@website/website-overview'
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
No name was provided for external module '@ngrx/store' in output.globals – guessing 'store'
No name was provided for external module '@ngrx/effects' in output.globals – guessing 'effects'
No name was provided for external module '@ngx-translate/core' in output.globals – guessing 'core'
Minifying UMD bundle
Copying declaration files
Writing package metadata
Removing scripts section in package.json as it's considered a potential security vulnerability.
Built @website/website-overview

Also noticed after it built the paths of some of the imports are using a local path.
export declare const getAllWebsites: import("../../../../../../../../../../Development/Source Code/Porject/Workspace/node_modules/@ngrx/store/src/selector").MemoizedSelector<object, import("libs/website-overview/src/lib/interfaces/website/website").Website[]>;

Not sure how to get around this.

**Comment by LloydTDavies** [comment]
Sorry this seemed to be a ng packag issue.
Importing  MemoizedSelector and Website seemed to fix my issue as well.

**Comment by itachiRedhair** [comment]
Importing works. But any idea on why this is happening?

**Comment by samtsai** [comment]
As for the warnings, see: https://github.com/ng-packagr/ng-packagr/blob/master/docs/dependencies.md#resolving-umd-module-identifiers

**Comment by shahidql1** [comment]
> As for the warnings, see: https://github.com/ng-packagr/ng-packagr/blob/master/docs/dependencies.md#resolving-umd-module-identifiers

Solved using above link.

**Comment by iamandrewluca** [comment]
Hello. I also have this issue after some nx updates.
My problem is. How I tell rollupjs to not use any externals? I want all to be bundled together.

🤔

**Comment by iamandrewluca** [comment]
Found solution.

In my custom rollupjs config I just emptied the external and globals

```js
/* eslint-disable @typescript-eslint/no-var-requires */
const getRollupOptions = require('@nrwl/react/plugins/bundle-rollup');
const { terser } = require('rollup-plugin-terser');
const replace = require('rollup-plugin-replace');

module.exports = function (options) {
    const newOptions = getRollupOptions(options);
    newOptions.plugins = [
        ...newOptions.plugins,
        replace({
            'process.env.NODE_ENV': JSON.stringify('production'),
        }),
        terser(),
    ];

    // https://rollupjs.org/guide/en/#outputglobals
    // https://github.com/nrwl/nx/blob/703725491170af51afd8f4b8868a38a88af46b7f/packages/react/plugins/bundle-rollup.ts#L4-L10
    newOptions.output.globals = {};

    // https://rollupjs.org/guide/en/#external
    // https://github.com/nrwl/nx/blob/703725491170af51afd8f4b8868a38a88af46b7f/packages/web/src/builders/package/package.impl.ts#L254https://github.com/nrwl/nx/blob/703725491170af51afd8f4b8868a38a88af46b7f/packages/web/src/builders/package/package.impl.ts#L254
    newOptions.external = [];

    return newOptions;
};
```

**Comment by l3ender** [comment]
When configuring `umdModuleIds` in ng-package.json, how do you know what to use for the value of something like `@ngrx/store`? Does one simply use the same value as what is provided in warning output (`store`)?
