### ISSUE TITLE
Purging Tailwind in a Nx monorepo for multiple Angular apps has unclear documentation and may need attention

### ISSUE THREAD

**Issue by adam-marshall** [nrwl/nx#8072]
### Discussed in https://github.com/nrwl/nx/discussions/7936

<div type='discussions-op-text'>

<sup>Originally posted by **adam-marshall** November 29, 2021</sup>
Hi, 

I wasn't sure what to do for help so I created a SO issue https://stackoverflow.com/q/70153513/1061602

**tl;dr:** using `createGlobPatternsForDependencies` with `tailwind.config.js` at workspace level with `__dirname` doesn't seem to work. 

I don't think this is a bug, it might need some comments updates, it might need documentation changes/enhancements (particularly as Tailwind is only in the React section of the Nx docs). Alternatively I might just be getting confused and its a support request.

Can anyone shed any light on this?</div>

so the following works, but only for one app at a time.

```
purge: {
    enabled: true,
    content: createGlobPatternsForDependencies(join(__dirname, 'apps/my-app-name')),
  },
```

the configuration in the docs https://nx.dev/l/r/guides/using-tailwind-css-in-react#introducing-nx-utility-for-better-tailwind-purging, does not work, i.e.

```
purge: {
    content: createGlobPatternsForDependencies(__dirname),
  },
```

**Comment by adam-marshall** [comment]
related to https://github.com/nrwl/nx/issues/3610 in that we would also want a nice way of turning on purging for production builds, but not otherwise, and it doesn't work currently with

`enabled: process.env.NODE_ENV === 'production'`

**Comment by leon** [comment]
Tailwind 3 was released the other day,
in it they have changed so `mode: 'jit'` is the standard way.

To get it to work with nx this is what I needed to do.

https://gist.github.com/leon/86f4502faa1953d35cc6547da849f703

**Comment by adam-marshall** [comment]
@leon thanks, I found some time to upgrade Tailwind.

this still doesn't work for me,  `__dirname` is my top level workspace name, and then `createGlobPatternsForDependencies` always fails with `[createGlobPatternsForDependencies] WARNING: There was no ProjectGraph available to read from, returning an empty array of glob patterns`...

If I pass in `dirPath` of an individual app it does return an array of glob patterns.

**Comment by Miikis** [comment]
Hi. After some trial & error, I've realized the new `createGlobPatternsForDependencies(dirPath, fileGlobPattern)` has it's parameters improperly labeled. The first param should be called something like `projectName`. 

Also, the second param used to have a default glob pattern and it'd be nice if that was put back. 

Below is what worked for me.

tailwind.config file located at `apps/myapp/tailwind.config.js`:

```
const { createGlobPatternsForDependencies } = require('@nrwl/next/tailwind');

const purgeGlob = '/**/!(*.stories|*.spec).{ts,tsx}';

const tailwindConfig = {
// ... tailwind stuff

  purge: [
    __dirname + purgeGlob,
    ...createGlobPatternsForDependencies('apps/myapp', purgeGlob),
  ],

// ... more tailwind stuff
};

module.exports = tailwindConfig;
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

That's a fair request, I'll be adding a guide for using Tailwind CSS in Angular in the coming days.

Please note the `createGlobPatternsForDependencies` utility is meant to be used at a project level. It's a utility that creates glob patterns for the dependencies of a project. It shouldn't be used in a tailwind config located at the root of the workspace.

If you have a `tailwind.config.js` file at the root of your workspace, don't use the mentioned utility and instead have:

```
// tailwind v2
module.exports = {
  mode: 'jit',
  purge: [
    join(__dirname, 'apps/**/!(*.stories|*.spec).{ts,html}'),
    join(__dirname, 'libs/**/!(*.stories|*.spec).{ts,html}'),
  ],
  ...
};
```

```
// tailwind v3
module.exports = {
  content: [
    join(__dirname, 'apps/**/!(*.stories|*.spec).{ts,html}'),
    join(__dirname, 'libs/**/!(*.stories|*.spec).{ts,html}'),
  ],
  ...
};
```

Also note that if your workspace contains more than one app is not advisable to have a tailwind configuration at the root of the workspace. The above configuration at the root of the workspace will cause all your apps to generate the CSS with all the different utility classes found in all apps and libs in your workspace. This is not desirable since you might end up with your style bundles being bigger than they should be because they might contain CSS not used by a specific app.

If you do have more than one application in your workspace, please use a `tailwind.config.js` file per application.

**Comment by adam-marshall** [comment]
> Also note that if your workspace contains more than one app is not advisable to have a tailwind configuration at the root of the workspace. 

ah from looking at the argument names, I wondered if it was supposed to work out what the dependencies were dynamically to the extent that it would know 'I'm building app-x so I need all the utility classes referenced in app-x' - now you mention it that does sound luxurious 😄 

looking forward to the guide.

**Comment by adam-marshall** [comment]
> join(__dirname, 'apps/**/!(*.stories|*.spec).{ts,html}'),

however, won't this fail? if it is per app, then why is it looking in the /apps/ folder?

**Comment by adam-marshall** [comment]
do you need the `createGlobPatternsForDependencies` still to ensure that it won't just harvest utility classes from ALL libs?

my current solution has two apps with similar CSS amounts so it isn't urgent for me to swap from a single tailwind config file immediately... and it is (for v3)

```javascript
  content: [
    join(__dirname, 'apps/**/*.{html,ts}'),
    ...createGlobPatternsForDependencies(join(__dirname, 'apps/my-first-app')),
    ...createGlobPatternsForDependencies(join(__dirname, 'apps/my-second-app')),
  ],
```

so my understanding is

1. the first line will look for utility classes in any HTML/TS files which are in the actual apps themselves (both **my-first-app** and **my-second-app**).
2. the second line will look for utility classes in _dependent libs_ of **my-first-app**.
3. the third line will look for utility classes in _dependent libs_ of **my-second-app**.

is this understanding correct? everything seems to be working, although it is too much perhaps.


so for per-project (per-app) config I'd go for something like the below?

```javascript
  content: [
    join(__dirname, '/**/*.{html,ts}'),
    ...createGlobPatternsForDependencies(__dirname),
  ],
```

feel free to tell me to wait for the guide by the way! 😄  just posting what I have incase it helps anyone else

**Comment by leosvelperez** [comment]
> > join(__dirname, 'apps/**/!(_.stories|_.spec).{ts,html}'),
> 
> however, won't this fail? if it is per app, then why is it looking in the /apps/ folder?

Not sure what you mean. The above snippet was for a root `tailwind.config.js` which is not a per-app configuration.

> do you need the `createGlobPatternsForDependencies` still to ensure that it won't just harvest utility classes from ALL libs?
> 
> my current solution has two apps with similar CSS amounts so it isn't urgent for me to swap from a single tailwind config file immediately... and it is (for v3)
> 
> ```js
>   content: [
>     join(__dirname, 'apps/**/*.{html,ts}'),
>     ...createGlobPatternsForDependencies(join(__dirname, 'apps/my-first-app')),
>     ...createGlobPatternsForDependencies(join(__dirname, 'apps/my-second-app')),
>   ],
> ```

If you have independent libraries in your workspace not related to your apps, that will help reduce the number of files to scan. Please note the above could result in duplicated globs if the apps have common dependencies. You could use a `Set` to guarantee unique globs.

Also, as I mentioned before, for multiple applications the recommendation is to use a `tailwilnd.config.js` file per project instead.

I'll definitely make sure to cover all the different scenarios in a workspace in the guide.

**Comment by adam-marshall** [comment]
sorry I missed that your snippet wasn't for a per-app configuration! 😄  thanks for clarifying.

I will definitely look to use a separate `tailwind.config.js` file per project.

**Comment by NsdHSO** [comment]
@leosvelperez I have some issues with tailwind when I want to use in multiple apps with nx. When I am in default app(shell, localhost:4200) tailwind not working, but if I open on every independently app ( localhost:4201) it works. I need your wisdom, can you help me? Your experiences it will be of real help to me.
