### ISSUE TITLE
What does ./node_modules/.bin/nx lint do?

### ISSUE THREAD

**Issue by dereklin** [nrwl/nx#808]
It seems ./node_modules/.bin/nx lint is not doing anything.  What is it supposed to do?

**Comment by xmlking** [comment]
i experienced same thing. it is doing nothing for me with latest nx. 
i use `npm run affected:lint  -- --uncommitted --fix --parallel` to automatically lint when users commit code.

**Comment by bcabanes** [comment]
Hi @dereklin,

The command `./node_modules/.bin/nx lint` verifies that your Nx Workspace is not inconsistent nor has some file out of sync. This command will show you the problem if you start deviating from the Nx guidelines when creating a library or an application not in the right place.

The command `lint` from Nx does Workspace integrity checks of your `/apps` and `/libs` like so:
- check the consistency of your dependencies;
- check if you have declared project in your `angular.json` that target nowhere;
- chick if you have apps or libs that are not declared in your `angular.json`;

This is more like a Nx validation of your project's configuration than simply checking _language errors_. The latest is done with the `ng lint` command which is the code linting from the Angular CLI.

**Comment by dereklin** [comment]
Hi @bcabanes,

When you say 
```
The latest is done with the ng lint command which is the code linting from the Angular CLI.
```
Does it mean ./node_modules/.bin/nx lint is no longer needed if we use ng lint?

**Comment by bcabanes** [comment]
No sorry i'meant to say _the latter_, they do different things.

You want to have `nx lint` for checking the integrity of you whole workspace to the Nx guidelines, and `ng lint` for checking code errors.

**Comment by skorunka** [comment]
@dereklin: Your workspace `lint` command should actually run `./node_modules/.bin/nx lint && ng lint`.

**Comment by dereklin** [comment]
Thanks @bcabanes and @skorunka

**Comment by tmtron** [comment]
@bcabanes : has this changed in recent releases?

I see this in my build output:
```
> nx lint && ng lint
>  NX   NOTE  Nx didn't recognize the command, forwarding on to the Angular CLI.
```

**Comment by bcabanes** [comment]
@tmtron This is caused by our new shiny CLI, this Note will be fixed in the next release ;)
