### ISSUE TITLE
Couldn't find component at path to add SCAM setup.

### ISSUE THREAD

**Issue by wizardnet972** [nrwl/nx#8083]
## Current Behavior

When I try to create a new scam component I got an error:
```
Couldn't find component at path libs/ng-lib/src/lib/foo/foo.component.ts to add SCAM setup.
error Command failed with exit code 1.
```

Also, I get the capital letter "C" in the schematics field:  
in type Adds a developer-defined type to the filename, in the format "name.type.ts".

## Expected Behavior
I would expect to generate a new component.

## Steps to Reproduce

```
npx create-nx-workspace (empty)
yarn add -D @nrwl/angular @nrwl/node
yarn nx g @nrwl/node,angular:app ...
yarn nx g @nrwl/angular:lib ng-lib ...

yarn nx generate @nrwl/angular:scam --name=foo --project=ng-lib --path=apps/nx-ui/src/app --type=component 
```

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

```
>  NX  Report complete - copy this into the issue template

  Node : 16.13.0
  OS   : darwin arm64
  yarn : 1.22.11

  nx : 13.3.0
  @nrwl/angular : 13.3.0
  @nrwl/cli : 13.3.0
  @nrwl/cypress : 13.3.0
  @nrwl/devkit : 13.3.0
  @nrwl/eslint-plugin-nx : 13.3.0
  @nrwl/express : undefined
  @nrwl/jest : 13.3.0
  @nrwl/linter : 13.3.0
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.3.0
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.0
  @nrwl/web : undefined
  @nrwl/workspace : 13.3.0
  @nrwl/storybook : 13.3.0
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
  	 @angular/animations: 13.1.0
  	 @angular/common: 13.1.0
  	 @angular/compiler: 13.1.0
  	 @angular/core: 13.1.0
  	 @angular/forms: 13.1.0
  	 @angular/platform-browser: 13.1.0
  	 @angular/platform-browser-dynamic: 13.1.0
  	 @angular/router: 13.1.0
  	 @angular-devkit/build-angular: 13.0.4
  	 @angular/cli: 13.0.4
  	 @angular/compiler-cli: 13.1.0
  	 @angular/language-service: 13.1.0
  	 @nrwl/js: 13.3.0

```

**Comment by Coly010** [comment]
Hey @wizardnet972 ! 
Your usage of the command seems a little incorrect, however, it did highlight an issue in the generator. Thank you!
There's a fix in PR now: #8100 

The usage in your command that I mention is wrong:
```
yarn nx generate @nrwl/angular:scam --name=foo --project=ng-lib --path=apps/nx-ui/src/app --type=component
```

1. You're specifying your library project, but providing a path under your app, not your library. 
2. You're passing a component type. You don't need to do that. it's always a component and that property just changes the filename from `foo.component.ts` to whatever you specify. e.g. `--type=random` would result in `foo.random.ts`

**Comment by wizardnet972** [comment]
@Coly010 thank you!!
The command line you mention I copied from the console of the nx console, perhaps I clicked on the app folder and open the nx-console and choose the `ng-lib` in the `project` property.
But by default, nx filled those fields include `type.

**Comment by Coly010** [comment]
Interesting, that's something we'll need to look into too. Thanks for that info!

**Comment by wizardnet972** [comment]
Happy to help! :)
