### ISSUE TITLE
Generated package.json for publishable libs includes wrong peerDependencies

### ISSUE THREAD

**Issue by the-ult** [nrwl/nx#8096]
## Current Behavior
When generating the `package.json` for a publishable lib it sometimes includes dependencies as _peerDependency_, which shouldn't.

## Expected Behavior
Only include the dependencies in the generated `package.json`, that are actually needed/used in production.

## Steps to Reproduce
For example, in the `angular-testing-library`, we encountered the [problem](https://github.com/testing-library/angular-testing-library/issues/270) that `@angular/forms` and `@testing-library/user-event` were somehow included in the generated `package.json`

`@angular/forms` and `@testing-library/user-event` are _NOT_  used in the library files, but _ARE_ used in in the tests/spec files.

```json
/// libs/testing-library/package.json

"peerDependencies": {
    "@angular/common": ">= 13.0.0",
    "@angular/platform-browser": ">= 13.0.0",
    "@angular/router": ">= 13.0.0",
    "@angular/core": ">= 13.0.0"
  },
```

```json
/// GENERATED
/// dist/@testing-library/angular/package.json

"peerDependencies": {
    "@angular/common": ">= 13.0.0",
    "@angular/platform-browser": ">= 13.0.0",
    "@angular/router": ">= 13.0.0",
    "@angular/core": ">= 13.0.0",
    "@angular/forms": "13.0.2",  // should not be included as peerDependency
    "rxjs": "^7.4.0",
    "@testing-library/user-event": "^13.5.0" // should not be included as peerDependency
  },
```

(moving those 2 dependencies to our `devDependencies` solves the problem. But is that the correct solution?)

See: https://github.com/testing-library/angular-testing-library/pull/272#issuecomment-990251660 for more information

**N.B.**
The strange thing is that the problem did not occur while using `angular.json`, but does occur with `workspace.json`

### Possible Solutions
- Maybe the solution could be to excluded dependencies only used in tests?
- Or adding a `nx` section to the library package.json with an exlcude?
```json

{
 ...
  "nx": {
    "excludeDependencies": ["@angular/forms", ....]
  },
  "peerDependencies":{
    ...
  }
}

```

### Environment
```
>  NX  Report complete - copy this into the issue template

  Node : 16.13.1
  OS   : darwin x64
  npm  : 7.24.2
  
  nx : 13.2.2
  @nrwl/angular : 13.2.2
  @nrwl/cli : 13.2.2
  @nrwl/cypress : 13.2.2
  @nrwl/devkit : 13.2.2
  @nrwl/eslint-plugin-nx : 13.2.2
  @nrwl/express : undefined
  @nrwl/jest : 13.2.2
  @nrwl/linter : 13.2.2
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.2.2
  @nrwl/nx-cloud : 12.5.4
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.2
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.2
  @nrwl/storybook : 13.2.2
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @angular/common: 13.0.2
         @angular/compiler: 13.0.2
         @angular/core: 13.0.2
         @angular/platform-browser: 13.0.2
         @angular/platform-browser-dynamic: 13.0.2
         @angular/router: 13.0.2
         @ngrx/store: 13.0.1
         @angular/animations: 13.0.2
         @angular/cdk: 13.0.2
         @angular/material: 13.0.2
         @angular/forms: 13.0.2
         @angular-devkit/build-angular: 13.0.3
         @angular/cli: 13.0.3
         @angular/compiler-cli: 13.0.2
         @angular/language-service: 13.0.2
         @nrwl/nx-plugin: 13.2.2
```

### Related
Might be related to:
- https://github.com/nrwl/nx/issues/4939 
- https://github.com/nrwl/nx/issues/1777

**Comment by the-ult** [comment]
Same still happens with a node project (#4939 )

Generated `package.json`
```json
{
  "name": "ddb-graphql-server",
  "version": "1.0.0",
  "dependencies": {
    "apollo-server-core": "3.3.0",
    "graphql": "15.6.0",
    "apollo-datasource-rest": "3.2.0",
    "graphql-modules": "~1.4.4",
    "@taiga-ui/cdk": "~2.29.0",  <== Should not be included
    "@angular/animations": "13.1.2", <== Should not be included
    "@angular/core": "13.1.2", <== Should not be included
    "rxjs": "7.5.2",
    "zone.js": "0.11.4",
    "@angular/common": "13.1.2", <== Should not be included
    "@angular/forms": "13.1.2", <== Should not be included
    "@angular/platform-browser": "13.1.2", <== Should not be included
    "date-fns": "2.28.0",
    "graphql-subscriptions": "~1.2.1",
    "apollo-server-express": "3.3.0",
    "express": "4.17.1",
    "graphql-scalars": "1.11.1",
    "js-yaml": "4.1.0",
    "@angular/compiler": "13.1.2", <== Should not be included
    "@angular/platform-browser-dynamic": "13.1.2", <== Should not be included
    "@log4js-node/gelf": "1.0.2",
    "log4js": "6.3.0",
    "reflect-metadata": "0.1.13",
    "compression": "1.7.4",
    "subscriptions-transport-ws": "0.9.19",
    "graphql-import-node": "0.0.4"
  },
  "main": "main.js"
}

```

**Comment by MysticEarth** [comment]
We are encountering a similar issue with wrong `peerDependencies`, but in our case it has to do with secondary entrypoints.

Our publishable UI library has a couple of "main" peerDependencies, like `@angular/core` and `@angular/common`.
Only one of the components has a peerDependency to `@angular/material`, so we have created a `package.json` for that specific entrypoint with the following peerDependency:

`"@angular/material": "^13.0.0 || ^14.0.0 || ^15.0.0",`

But, when building the lib with NX this results in a main package.json with:

```
"peerDependencies": {
    "@angular/core": "^13.0.0 || ^14.0.0 || ^15.0.0",
    "@angular/common": "^13.0.0 || ^14.0.0 || ^15.0.0",
    "@angular/router": "^13.0.0 || ^14.0.0 || ^15.0.0",
    "@angular/material": "13.3.3" ❌
  },
```

**Comment by tinesoft** [comment]
Hi,
 
I have a similar problems on my [nxrocks project](https://github.com/tinesoft/nxrocks/) project, event after having upgraded to Nx `v15.0.4`, which includes in particular that fix : https://github.com/nrwl/nx/pull/12851. 

In my case, I have a **publishable library** named `@nxrocks/common` with a **secondary entrypoint ** `@nxrocks/common/testing` used only in the tests files (*.spec.ts, *.test.ts) of projects that depend on that publishable library.

Here is an excerpt of the root  tsconfig file:

**tsconfig.base.json**
```
    "paths": {
      "@nxrocks/common": ["packages/common/src/index.ts"],
      "@nxrocks/common/testing": ["packages/common/testing/index.ts"], <-- secondary entry point, used in tests only
      "@nxrocks/nx-flutter": ["packages/nx-flutter/src/index.ts"],
      "@nxrocks/nx-micronaut": ["packages/nx-micronaut/src/index.ts"],
      "@nxrocks/nx-quarkus": ["packages/nx-quarkus/src/index.ts"],
      "nxrocks/nx-spring-boot": ["packages/nx-spring-boot/src/index.ts"]
    }
  }
}

``` 

When packaging (`nx build common`), the external libraries used in `@nxrocks/common/testing` (like `@jest/globals`)  are still included, even if that package is only imported in test files...

A workaround, is to declare them explicitly as **devDependencies" in the package.json of the publishable library

@nxrocks/common's **package.json**
```
  "devDependencies": {
    "@jest/globals": "*"
  },
```

Is that the appropriate thing to do?

**Comment by dpeger** [comment]
We're encountering the same issue. The generated `package.json` for the publishable artifact includes dependencies that are only used in spec-files. Even if we clear the `peerDependencies` in the lib's `package.json`, nx will add the testing libraries as `peerDependencies` to the generated `package.json`.

I think the spec-files should be ignored by nx's dependency discovery mechanism. There should be no need to include dev dependency information in a publishable artifact.

Adding an option to exclude libs from being included in the generated artifact would be another solution although this manual configuration should not be necessary IMHO.

Relates to/Is duplicated by https://github.com/nrwl/nx/issues/4547

**Comment by wjehring** [comment]
Replying to keep this topic active,

**Comment by wjehring** [comment]
Replying to keep this topic active.

**Comment by FrozenPandaz** [comment]
We have resolved this by changing the way to keep dependencies in sync via an EsLint rule which should allow for you to have dependencies in either `dependencies` or `peerDependencies`. Please give that a try. https://nx.dev/nx-api/eslint-plugin/documents/dependency-checks#dependency-checks-rule
