### ISSUE TITLE
`nx dep-graph --json`

### ISSUE THREAD

**Issue by jackall3n** [nrwl/nx#8099]
## Description

Adding the ability to print the dependency graph to the console as `JSON`. 

## Motivation

One example would be that within a CI environment it would be useful to be able to create matrix jobs based off of the output of the `dep-graph` command.

## Suggested Implementation

```typescript
// packages/workspace/src/command-line/dep-graph.ts#281
/* else */ if (args.json) {
    const json = {
        graph,
        affectedProjects,
        criticalPath: affectedProjects,
    }

    console.log(JSON.stringify(json, null, 2));
}
```

## Alternate Implementations

The alternative is to use the `--file=output.json` argument. While this option would work, it feels redundant to need to store the file only to read it.
```sh
$ nx dep-graph --file=output.json && cat output.json
```

**Comment by philipjfulcher** [comment]
Thanks for filing this issue! There's an alternative command that might already fulfill your needs: `nx print-affected` will print to the console a data model very close to what you have proposed here. It admittedly doesn't have the same level of data that the `nx dep-graph --file graph.json` would give you, but I'm curious if you need the extra data to accomplish what you want.

**Comment by philipjfulcher** [comment]
@jackall3n Have you had a chance to take a look at the output from `nx print-affected` to see if it gives you what you need?

**Comment by jackall3n** [comment]
Hey @philipjfulcher, thanks for getting back. Actually yes, this is just what I wanted!

The command I can use to get all projects (regardless of whether they've been affected is:

```shell
nx print-affected | jq .projectGraph.nodes
```

**Comment by philipjfulcher** [comment]
@jackall3n - Great! I'm glad you've got the data you need there. The semantics there could use some work. Why do we have to use the affected commands to get all projects? 🤔 I'll bring this up with the team to see what we can do to make it clear/more discoverable.

And I'll add that there's a `--select` option for `print-affected` that I think will give you the same result as using `jq`:
```nx print-affected --select projectGraph.nodes```

I'll close this and discuss the semantics with the rest of the team. Thanks for your question!
