### ISSUE TITLE
Lazy loading module from library not working in AOT

### ISSUE THREAD

**Issue by diginikkari** [nrwl/nx#81]
I receive "Module not found " -error if I build AOT version of my app when there is lazy loaded modules.

this doesn't work when building with `ng build --aot`:
`{ path: 'login', loadChildren: '@bootherp-fs/login#LoginModule' },`

I'm able to get it working using relative path, but that doesn't feel right way to do it.

this works:
`{ path: 'login', loadChildren: '../../../../libs/login/src/login.module#LoginModule' },`

Perhaps I'm doing it wrong, but at least it would be good to have documentation how it should be done.

I am very much enjoying how NX is helping me to structure my code much better way than I have done earlier.

**Comment by phsims** [comment]
I'm having problems with lazy loading also..
The below code is from my lazy loaded module whose path is 'login'

```
const routes: Routes = [
  { path: '', component: LoginComponent,},  
  { path: 'not-found',   component: PageNotFoundComponent } 
];
```
In my regular cli build the path for PageNotFoundComponent would be '/not-found'.  Using NX the path is '/login/not-found'

**Comment by diginikkari** [comment]
@phsims If you would like to have PageNotFoundComponent to be in /not-found, you should move it to your app's route. It should be parallel to your lazy loaded login path.

This will route all unknown paths to PageNotFoundComponent:

```    
RouterModule.forRoot([
      { path: 'login', loadChildren: '../../../../libs/login/src/login.module#LoginModule' },
      { path: '', loadChildren: '../../../../libs/erp/src/other.module#OtherModule' },
      { path: '**', component: PageNotFoundComponent }
    ])
```

**Comment by jeffbcross** [comment]
@diginikkari thanks for opening the issue, we've seen this same error with prod builds because there's no ngfactory module being generated for the index.ts which re-exports the NgModule to be lazy loaded. We're looking into it.

In the meantime, rather than using relative paths as you're doing, you could still start at the lib entry point and resolve the module from there: `@bootherp-fs/login/src/login.module#LoginModule`

**Comment by diginikkari** [comment]
Thanks @jeffbcross, I'll do that in meantime. That is much more elegant.

**Comment by phsims** [comment]
@diginikkari I know :).  My point is that CLI and NX paths in lazy loaded modules appear to be working differently, I am not why or which is correct
