### ISSUE TITLE
nx test --with-deps --codeCoverage isn't running code coverage for dependencies

### ISSUE THREAD

**Issue by craigbroadman** [nrwl/nx#8111]
## Current Behavior

if I run the following command, I expected the dependencies to be tested with code coverage, but it does not. Is there a way around this>

`npx nx my-app --with-deps --codeCoverage`

## Expected Behavior

I expected the dependencies to be tested with code coverage

**Comment by craigbroadman** [comment]
@AgentEnder - would you agree this to be a bug and are you aware of any work arounds? 

I noticed in the output that --with-deps is actually going to be deprecated in v14 

`DEPRECATION WARNING: --with-deps is deprecated and it will be removed in v14.
Configure target dependencies instead: https://nx.dev/latest/angular/core-concepts/configuration#target-dependencies.`

If I was to change things over now, would that help?

**Comment by craigbroadman** [comment]
Is there any update on this?

**Comment by wrightomated** [comment]
I recently changed things over to target dependencies and had the same result.

The solution was to have "codeCoverage": true in the test target options.

**Comment by craigbroadman** [comment]
> I recently changed things over to target dependencies and had the same result.
> 
> The solution was to have "codeCoverage": true in the test target options of the dependencies.

Thanks @wrightomated, I will take a look at this option
