### ISSUE TITLE
@nrwl/tao fails to validate schema in case of multiple types

### ISSUE THREAD

**Issue by fr-esco** [nrwl/nx#8112]
I'm using "@nrwl/angular": "^12.9.0" and "@angular/fire": "~7.2.0".

`@angular/fire:deploy` accepts the following parameter in [its schema](https://github.com/angular/angularfire/blob/master/src/schematics/deploy/schema.json):

```json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "FirebaseDeploySchema",
  "title": "Firebase Deploy",
  "description": "Ng Deploy target options for Firebase.",
  "properties": {
    // ...
    "ssr": {
      "type": ["boolean", "string"],
      "description": "Should we attempt to deploy the function to Cloud Functions (true or 'cloud-functions') / Cloud Run ('cloud-run') or just Hosting (false)"
    }
  }
}
```

In my `angular.json` I have:

```json
"deploy": {
	"builder": "@angular/fire:deploy",
	"options": {
		"prerender": false,
		"ssr": false,
		"browserTarget": "my-app:build:production",
		"firebaseProject": "my-project-id",
	}
}
```

## Current Behavior

If I run: `nx run my-app:deploy`, it fails:
```bash
Property 'ssr' does not match the schema. 'false' should be a 'boolean,string'.
```

## Expected Behavior

It runs successfully. I don't know if it's ever worked.

## Considerations
I'm pretty sure it depends on [validation logic](https://github.com/nrwl/nx/blob/12.9.0/packages/tao/src/shared/params.ts#L216), that does not take into account the possibility of (valid) mutliple types in the schema.

**Comment by FrozenPandaz** [comment]
I think what you want is the `oneOf` type:

```json
"oneOf": [
  { "type": "boolean" },
  { "type": "string" }
]
```

Example:
https://github.com/nrwl/nx/blob/421d4f2f022b6ffaf6699f315c5d1a48f68efdd0/packages/node/src/executors/build/schema.json#L111

Does this help? https://json-schema.org/understanding-json-schema/reference/combining.html

**Comment by fr-esco** [comment]
Actually, I'm referring to multiple types, as per the last example of this page: https://json-schema.org/understanding-json-schema/reference/type.html

```json
{ "type": ["number", "string"] }
```

**Comment by fr-esco** [comment]
Do I need to give you more info?

**Comment by fr-esco** [comment]
Has this issue been validated?

**Comment by fr-esco** [comment]
Is there anything I could add?

**Comment by vi-verrone** [comment]
Hi all, I'm having the same issue during the validationStep since it seems to not accept the `type` in array form although it's defined in the JSON Schema specifications. When will a fix be planned for this issue?
