### ISSUE TITLE
Issues with MFE project and app generators

### ISSUE THREAD

**Issue by coltpini** [nrwl/nx#8120]
## Current Behavior

We are migrating our current app from lerna to Nx (woot) and I am running through the MFE quick start (https://nx.dev/l/a/guides/setup-mfe-with-angular)
I have found the issues with the module federation and angular 13 and have mitigated them. But keep running into issues. It seems really odd to me that after running
```
npx create-nx-workspace ng-mfe
# choosing empty
npm install --save-dev @nrwl/angular
npx nx g @nrwl/angular:app shell --mfe --mfeType=host --routing=true
npx nx g @nrwl/angular:app builder --mfe --mfeType=remote --port=4201 --host=builder --routing=true
```
Then applying the fixes for the aforementioned bugs I am getting errors in running it using
`nx run shell:build-mfe`

When I load the remote from the host I get this error:

<img width="442" alt="Screen Shot 2021-12-10 at 15 11 45" src="https://user-images.githubusercontent.com/792704/145647965-37a854e3-026a-4901-bafb-25a372051878.png">

I know there has been some churning in the last couple of days with the angular 13 / module federation I am wondering if this might be part of the issues from that.

## Expected Behavior

I would expect the CLI tools to create a working app out of the gate.

## Steps to Reproduce

As stated above:
```
npx create-nx-workspace ng-mfe
# choosing empty
npm install --save-dev @nrwl/angular
npx nx g @nrwl/angular:app shell --mfe --mfeType=host --routing=true
npx nx g @nrwl/angular:app builder --mfe --mfeType=remote --port=4201 --host=builder --routing=true
```
Then applying the fixes for the aforementioned bugs I am getting errors in running it using the suggestion here: https://github.com/angular-architects/module-federation-plugin/issues/96#issuecomment-981896034 by Manfred at angular-architects
then run this
`nx run shell:build-mfe`
if you navigate directly to the sub app (or create a link to the sub module on the html of the app component in shell) you get this error. It is like it is finding the `remoteEntry.js` file, but not the module itself or something along those lines. Not sure what is happening, trying to work through it currently.

Minimal Repo"
https://github.com/coltpini/taco

### Environment

```
Node : 14.15.5
  OS   : darwin x64
  npm  : 6.14.11
  
  nx : undefined
  @nrwl/angular : 13.3.1
  @nrwl/cli : 13.3.1
  @nrwl/cypress : 13.3.1
  @nrwl/devkit : 13.3.1
  @nrwl/eslint-plugin-nx : 13.3.1
  @nrwl/express : undefined
  @nrwl/jest : 13.3.1
  @nrwl/linter : 13.3.1
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.1
  @nrwl/web : undefined
  @nrwl/workspace : 13.3.1
  @nrwl/storybook : 13.3.1
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @angular-architects/module-federation: 13.0.1
         @angular/animations: 13.1.0
         @angular/common: 13.1.0
         @angular/compiler: 13.1.0
         @angular/core: 13.1.0
         @angular/forms: 13.1.0
         @angular/platform-browser: 13.1.0
         @angular/platform-browser-dynamic: 13.1.0
         @angular/router: 13.1.0
         @angular-devkit/build-angular: 13.0.4
         @angular/cli: 13.0.4
         @angular/compiler-cli: 13.1.0
         @angular/language-service: 13.1.0
```

**Comment by mikezks** [comment]
In general, yes, we will release an further version soon, that will fix the current bugs.

Meanwhile, you are using `scriptType: 'text/javascript'`, which is the opt-out of ESM to the previous (ng 12) bundling, and `library: { type: "module" }`, which tells webpack to use ESM - both together does not work, see https://github.com/angular-architects/module-federation-plugin/issues/96.

**Comment by Coly010** [comment]
You should be able to use module syntax now. Can you try this all again with the latest version of Nx?

**Comment by coltpini** [comment]
I just regenerated and it is failing still. I am going to poke around at the generated code and see if I can get it working.
Previous to this I tried lots of variations of module and `scriptType: 'text/javascript'` and had no luck.

**Comment by coltpini** [comment]
I guess it would be good to share what I am running into as I try and work through the generated code.
I generated the app with this:
```
npx create-nx-workspace ng-mfe
# choosing empty
npm install --save-dev @nrwl/angular
npx nx g @nrwl/angular:app shell --mfe --mfeType=host --routing=true
npx nx g @nrwl/angular:app builder --mfe --mfeType=remote --port=4201 --host=builder --routing=true
```
Then when I run `nx run builder:serve` I get this error:
```
> nx run builder:serve:development 
Cannot find module 'webpack'
Require stack:
- /Users/coltpini/proj/taco/node_modules/@angular-devkit/build-webpack/src/webpack/index.js
- /Users/coltpini/proj/taco/node_modules/@angular-devkit/build-webpack/src/index.js
- /Users/coltpini/proj/taco/node_modules/@angular-devkit/build-angular/src/builders/dev-server/index.js
- /Users/coltpini/proj/taco/node_modules/@nrwl/angular/src/builders/webpack-server/webpack-server.impl.js
- /Users/coltpini/proj/taco/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /Users/coltpini/proj/taco/node_modules/@angular-devkit/architect/node/index.js
- /Users/coltpini/proj/taco/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
- /Users/coltpini/proj/taco/node_modules/@nrwl/tao/src/commands/run.js
- /Users/coltpini/proj/taco/node_modules/@nrwl/tao/index.js
- /Users/coltpini/proj/taco/node_modules/@nrwl/cli/lib/run-cli.js

———————————————————————————————————————————————

>  NX   ERROR  Running target "builder:serve" failed

  Failed tasks:
  
  - builder:serve:development
  
  Hint: run the command with --verbose for more details.
```

and when I run `nx run shell:build-mfe` I get:
```
>  NX   ERROR  Cannot find target 'build-mfe' for project 'shell'
```

**Comment by coltpini** [comment]
manually installing webpack fixed the above issue:
- `npm i --save-dev webpack`
- `npm i --save-dev webpack-dev-server`

**Comment by coltpini** [comment]
but didn't solve the second issue with starting `build-mfe`

**Comment by coltpini** [comment]
Yes, success, with the installation of the above, it is working fully now!!!

**Comment by coltpini** [comment]
It looks like those fixes were built into the generator, so I suppose I will need to do some manual updating once I have updated the angular architects updates to their modules, and upgrade to the latest version of angular.

**Comment by coltpini** [comment]
Thank you a ton for your help.
