### ISSUE TITLE
Enable more strict options

### ISSUE THREAD

**Issue by puku0x** [nrwl/nx#8121]
## Description

Angular recently added two strict options for new projects. https://github.com/angular/angular-cli/pull/21538
- [noImplicitOverride](https://www.typescriptlang.org/tsconfig#noImplicitOverride)
- [noPropertyAccessFromIndexSignature](https://www.typescriptlang.org/tsconfig#noPropertyAccessFromIndexSignature)

## Motivation

Those options are enabled by default in the latest Angular.
They look great in terms of the type safety. Why not apply them to all other frameworks that Nx supports?

## Suggested Implementation

1. Fix existing generators
2. Add `--strict` option to other generators

The current status of supporting the two strict options.

- [ ] `@nrwl/angular:application` #8126
- [ ] `@nrwl/angular:library` #8126
- [ ] `@nrwl/express:application` ⚠️ `--strict` is not supported
- ~`@nrwl/express:library`~ 🚫 not implemented
- [ ] `@nrwl/gatsby:application` ⚠️ `--strict` is not supported
- ~`@nrwl/gatsby:library`~ 🚫 not implemented
- [ ] `@nrwl/js:application`
- [ ] `@nrwl/js:library`
- [ ] `@nrwl/nest:application` ⚠️ `--strict` is not supported
- [ ] `@nrwl/nest:library`
- [ ] `@nrwl/next:application` ⚠️ `--strict` is not supported
- [ ] `@nrwl/next:library` https://github.com/nrwl/nx/pull/8127
- [ ] `@nrwl/node:application` ⚠️ `--strict` is not supported
- [ ] `@nrwl/node:library`
- [ ] `@nrwl/react:application` https://github.com/nrwl/nx/pull/8127
- [ ] `@nrwl/react:library` https://github.com/nrwl/nx/pull/8127
- [ ] `@nrwl/react-native:application` ⚠️ `--strict` is not supported
- [ ] `@nrwl/react-native:library`
- [ ] `@nrwl/web:application` ⚠️ `--strict` is not supported
- ~`@nrwl/web:library`~  🚫 not implemented
- ~`@nrwl/workspace:application`~ 🚫 not implemented
- [ ] `@nrwl/workspace:library`

## Alternate Implementations

Hard coding to the templates? Sounds nice. 
https://github.com/angular/angular-cli/blob/4bf3cd76f11840ab0fa808a95cde0f5c8681087f/packages/schematics/angular/workspace/files/tsconfig.json.template#L6-L12

**Comment by jaysoo** [comment]
Merged, thanks!

**Comment by puku0x** [comment]
@jaysoo Thank you for taking a look at this issue. I will create other PRs to ensure strict mode later.
