### ISSUE TITLE
Issues with upgrading from 13.2.4 to 13.3.1

### ISSUE THREAD

**Issue by ivicac** [nrwl/nx#8124]
## Current Behavior
I am trying to upgrade my project from 13.2.4 to 13.3.1, but migration fails complaining about mfe configuration update, but I don't have mfe set.

## Expected Behavior
I expect the migration to work smoothly.

## Steps to Reproduce
Migrate a project with nx 13.2.4 installed to 13.3.1.

### Failure Logs
`>  NX  Running migrations from migrations.json

Running migration 13-3-0-tsc-location
Successfully finished 13-3-0-tsc-location
---------------------------------------------------------
Running migration update-mfe-config-to-module-syntax
Cannot read property 'implementation' of undefined
/Volumes/data/saas/lomvo/lomvo/client/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;

Error: Command failed: /var/folders/d7/38c7n7nj0cg00ngyfhrhjcnm0000gn/T/tmp-11316-9bs79651qDJ1/node_modules/.bin/tao migrate --run-migrations
    at checkExecSyncError (child_process.js:643:11)
    at execSync (child_process.js:679:15)
    at Object.handler (/Volumes/data/saas/lomvo/lomvo/client/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:125:42)
    at Object.runCommand (/Volumes/data/saas/lomvo/lomvo/client/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Volumes/data/saas/lomvo/lomvo/client/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/Volumes/data/saas/lomvo/lomvo/client/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
    at initLocal (/Volumes/data/saas/lomvo/lomvo/client/node_modules/@nrwl/cli/lib/init-local.js:28:79)
    at Object.<anonymous> (/Volumes/data/saas/lomvo/lomvo/client/node_modules/@nrwl/cli/bin/nx.js:45:32)
    at Module._compile (/Volumes/data/Users/ivicac/.nvm/versions/node/v14.17.1/lib/node_modules/nx/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 11340,
  stdout: null,
  stderr: null
}
`

### Environment
`Node : 14.17.1
  OS   : darwin x64
  npm  : 6.14.13
  
  nx : undefined
  @nrwl/angular : 13.2.4
  @nrwl/cli : 13.2.4
  @nrwl/cypress : 13.2.4
  @nrwl/devkit : 13.2.4
  @nrwl/eslint-plugin-nx : 13.2.4
  @nrwl/express : undefined
  @nrwl/jest : 13.2.4
  @nrwl/linter : 13.2.4
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.4
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.4
  @nrwl/storybook : 13.2.4
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.3
         @angular/cdk: 13.1.0
         @angular/common: 13.0.3
         @angular/compiler: 13.0.3
         @angular/core: 13.0.3
         @angular/forms: 13.0.3
         @angular/google-maps: 13.1.0
         @angular/localize: 13.0.3
         @angular/platform-browser: 13.0.3
         @angular/platform-browser-dynamic: 13.0.3
         @angular/router: 13.0.3
         @datorama/akita: 7.0.1
         @ng-bootstrap/ng-bootstrap: 10.0.0
         @ngneat/transloco: 3.1.1
         @pebula/ngrid: 4.0.0-alpha.3
         @angular-devkit/build-angular: 13.0.4
         @angular/cli: 13.0.4
         @angular/compiler-cli: 13.0.3
         @angular/language-service: 13.0.3
         @ngneat/spectator: 9.0.0`

migrations.json

`{
  "migrations": [
    {
      "version": "13.3.0-beta.0",
      "description": "@nrwl/workspace:tsc is now @nrwl/js:tsc",
      "cli": "nx",
      "implementation": "./src/migrations/update-13-3-0/update-tsc-executor-location",
      "package": "@nrwl/workspace",
      "name": "13-3-0-tsc-location"
    },
    {
      "cli": "nx",
      "version": "13.3.0-beta.0",
      "description": "In Angular version 13, the ESM became a first class citizen. This means the webpack config generated must be modified to support modules.",
      "factory": "./src/migrations/update-13-3-0/update-mfe-webpack-config",
      "package": "@nrwl/angular",
      "name": "update-mfe-config-to-module-syntax"
    },
    {
      "cli": "nx",
      "version": "13.3.0-beta.0",
      "description": "Update eslint-rules jest.config.js in order to support ESLint v8 exports mapping, remove category field",
      "factory": "./src/migrations/update-13-3-0/eslint-8-updates",
      "package": "@nrwl/linter",
      "name": "eslint-8-updates"
    }
  ]
}`

**Comment by heavybeard** [comment]
I'm from `13.2.2` version and I received a similar issue

```
Running migration 13-3-0-tsc-location
Successfully finished 13-3-0-tsc-location
---------------------------------------------------------
Running migration update-mfe-config-to-module-syntax
The "path" argument must be of type string. Received undefined
/Users/andrea/workspace/nibol-manager-new/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /var/folders/cv/gd18xb4s09d3b5z5h24b6y8h0000gn/T/tmp-28236-ONjDnhu7qu57/node_modules/.bin/tao migrate --run-migrations
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at Object.handler (/Users/andrea/workspace/nibol-manager-new/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:125:42)
    at Object.runCommand (/Users/andrea/workspace/nibol-manager-new/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/andrea/workspace/nibol-manager-new/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/Users/andrea/workspace/nibol-manager-new/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
    at initLocal (/Users/andrea/workspace/nibol-manager-new/node_modules/@nrwl/cli/lib/init-local.js:27:79)
    at Object.<anonymous> (/Users/andrea/workspace/nibol-manager-new/node_modules/@nrwl/cli/bin/nx.js:45:32)
    at Module._compile (/usr/local/lib/node_modules/nx/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 28244,
  stdout: null,
  stderr: null
}
```

**Comment by patrickmichalina** [comment]
Same here. Anything after `13.2.4` and I get ..

```bash
Error: Unable to resolve @nrwl/workspace:tsc.
Cannot find executor 'tsc' in .../node_modules/@nrwl/workspace/executors.json
```

**Comment by nicholasconfer** [comment]
> I'm from `13.2.2` version and I received a similar issue
> 
> ```
> Running migration 13-3-0-tsc-location
> Successfully finished 13-3-0-tsc-location
> ---------------------------------------------------------
> Running migration update-mfe-config-to-module-syntax
> The "path" argument must be of type string. Received undefined
> /Users/andrea/workspace/nibol-manager-new/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
>                 throw err;
>                 ^
> 
> Error: Command failed: /var/folders/cv/gd18xb4s09d3b5z5h24b6y8h0000gn/T/tmp-28236-ONjDnhu7qu57/node_modules/.bin/tao migrate --run-migrations
>     at checkExecSyncError (node:child_process:826:11)
>     at execSync (node:child_process:900:15)
>     at Object.handler (/Users/andrea/workspace/nibol-manager-new/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:125:42)
>     at Object.runCommand (/Users/andrea/workspace/nibol-manager-new/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
>     at Object.parseArgs [as _parseArgs] (/Users/andrea/workspace/nibol-manager-new/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
>     at Object.get [as argv] (/Users/andrea/workspace/nibol-manager-new/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
>     at initLocal (/Users/andrea/workspace/nibol-manager-new/node_modules/@nrwl/cli/lib/init-local.js:27:79)
>     at Object.<anonymous> (/Users/andrea/workspace/nibol-manager-new/node_modules/@nrwl/cli/bin/nx.js:45:32)
>     at Module._compile (/usr/local/lib/node_modules/nx/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
>   status: 1,
>   signal: null,
>   output: [ null, null, null ],
>   pid: 28244,
>   stdout: null,
>   stderr: null
> }
> ```

Can confirm for those upgrading to v13 from previous version, that we ran into this issue.  You can avoid it in meantime by running nx migrate 13.2.4 instead of latest version while awaiting fix.

**Comment by maxisam** [comment]
It seems to me it is from this part

https://github.com/nrwl/nx/blob/69c5251c89cc439ba4f512c676ce532475506d24/packages/angular/src/migrations/update-13-3-0/update-mfe-webpack-config.ts#L22-L23

```
const webpackPath = opts[CUSTOM_WEBPACK_OPTION]?.path;
```
webpackPath is undefined here. 

I feel like `tree.exists(webpackPath)` is expecting a string type.

**Comment by Coly010** [comment]
Hey! Thanks everyone for bringing this to our attention. 

Is anyone able to share the `workspace.json` or `project.json` for the corresponding project that this is failing for?
I'm trying to replicate it but I can't seem to create a valid failing scenario. 

Any help in this would be awesome!

**Comment by ubergeoff** [comment]
This does indeed seem to fix the issue:

```
if (!webpackPath || !tree.exists(webpackPath)) {
```

**Comment by Coly010** [comment]
@ubergeoff Are you able to share the workspace.json or project.json for the corresponding project that this was failing for?

**Comment by ubergeoff** [comment]
No - sorry - cannot share private repo ;(

But I do have a couple of app's

One has a `customWebpackConfig` for non-MFE app
And another also has a `customWebpackConfig` for a MFE app

**Comment by pmenze** [comment]
I have the same issue. I cannot post my angular.json file here in public. But I could send the file to you (and others if required) through another private channel

**Comment by Coly010** [comment]
@pmenze For sure, reach out to me on Twitter @FerryColum! that would be brilliant!
