### ISSUE TITLE
React Project: 13.2.4 serves ok but 13.3.1 give error: Unable to resolve @nrwl/web:build.

### ISSUE THREAD

**Issue by rexebin** [nrwl/nx#8125]
## Current Behavior

It was ok with 13.2.4, after upgrading to 13.3.1, running `yarn serve` fails with error: 
```
Unable to resolve @nrwl/web:build.
Cannot find executor 'build' in C:\projects\...\node_modules\@nrwl\web\executors.json.
```

## Expected Behavior

No error

No error if I reverse @nrwl/web back to 13.2.4

## Steps to Reproduce

New React project with 13.3.1 and serve.

**Comment by puku0x** [comment]
@rexebin Replacing `@nrwl/web:build` with `@nrwl/web:webpack` in your `project.json` solves the problem.

**Comment by rexebin** [comment]
Thank you!

**Comment by Graveheart** [comment]
I see you've also added the migration, thanks a lot!
