### ISSUE TITLE
jest `snapshotSerializers` not loaded from jest-preset-angular (can't use `<rootDir>`)

### ISSUE THREAD

**Issue by llwt** [nrwl/nx#813]
It looks like there are issues using `<rooDir>` in paths inside the `jest.config.js`.

I had to do the following in the root `jest.config.js` to get it working:
 * remove `rootDir` references from our `transformIgnorePatterns` (see #812)
 * update our local `transform` references to use `path.resolve` and re-add `snapshotSerializers`
   - __before:__  `'sass-to-ts.scss': '<rootDir>/tools/sass-extract-preprocessor.js',`
   - __after:__     `'sass-to-ts.scss': path.resolve(__dirname, 'tools/sass-extract-preprocessor.js'),`
* re-add `snapshotSerializers` from `jest-preset-angular` without `rootDir`:
```js
  snapshotSerializers: [
    'jest-preset-angular/AngularSnapshotSerializer.js',
    'jest-preset-angular/HTMLCommentSerializer.js',
  ],
```

@FrozenPandaz Is there a better way to handle this?

**Comment by FrozenPandaz** [comment]
I like adding this. Do you have a particular issue with it?
```
snapshotSerializers: [
    'jest-preset-angular/AngularSnapshotSerializer.js',
    'jest-preset-angular/HTMLCommentSerializer.js',
  ],
```

If something is a node_module, I would personally always use the above approach. If it is your own transformer or jest plugin, I think adding them to `tools` is a good solution (and that's really cool).

**Comment by llwt** [comment]
👍 That sounds good to me. 

It doesn't currently cause issues, [but this basically just duplicates the `snapshotSerializers` defined in  `jest-preset-angular`](https://github.com/thymikee/jest-preset-angular/blob/master/jest-preset.json#L30), imported by the generated in `<lib>/src/test-setup.ts`, sans `<root-dir>`. It seems to silently fail when defining a serializer who's path doesn't exist. Just something to be aware of in case that functionality changes within jest.

**Comment by FrozenPandaz** [comment]
This issue seems resolved now. Please let us know if you continue having issues.
