### ISSUE TITLE
React Typescript linting rule is ignored (@nrwl/next)

### ISSUE THREAD

**Issue by zaunermax** [nrwl/nx#8134]
## Current Behavior
The lint rules of `plugin:@nrwl/nx/react-typescript` do not work in a newly generated next.js project.

The generated next lint file looks like [this](https://github.com/zaunermax/nx-lint-repro/blob/main/apps/test/.eslintrc.json).

```
{
  "extends": [
    "plugin:@nrwl/nx/react-typescript",
    "../../.eslintrc.json",
    "next",
    "next/core-web-vitals"
  ],
  "ignorePatterns": ["!**/*"],
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],
      "rules": {
        "@next/next/no-html-link-for-pages": ["error", "apps/test/pages"]
      }
    },
    {
      "files": ["*.ts", "*.tsx"],
      "rules": {}
    },
    {
      "files": ["*.js", "*.jsx"],
      "rules": {}
    }
  ],
  "env": {
    "jest": true
  }
}
```

The extending of the config from `plugin:@nrwl/nx/react-typescript` just does not seem to work at all, as pasting in the config manually to the override section works just fine.

## Expected Behavior
The linting rules should be extended correctly.

## Steps to Reproduce
[This repo](https://github.com/zaunermax/nx-lint-repro) contains a newly generated next.js app with 2 deliberately added linting errors. They're annotaded with a `//FIXME: ...` comment in [this file](https://github.com/zaunermax/nx-lint-repro/blob/main/apps/test/pages/_app.tsx).

When running any linting operation on the test (next.js) app, the linter won't complain about anything, though it should.

### Environment
```
Node : 16.13.1
OS   : linux x64
npm  : 8.1.2

nx : 13.3.1
@nrwl/angular : undefined
@nrwl/cli : 13.3.1
@nrwl/cypress : 13.3.1
@nrwl/devkit : 13.3.1
@nrwl/eslint-plugin-nx : 13.3.1
@nrwl/express : undefined
@nrwl/jest : 13.3.1
@nrwl/linter : 13.3.1
@nrwl/nest : undefined
@nrwl/next : 13.3.1
@nrwl/node : undefined
@nrwl/nx-cloud : undefined
@nrwl/react : 13.3.1
@nrwl/react-native : undefined
@nrwl/schematics : undefined
@nrwl/tao : 13.3.1
@nrwl/web : 13.3.1
@nrwl/workspace : 13.3.1
@nrwl/storybook : 13.3.1
@nrwl/gatsby : undefined
typescript : 4.4.4
rxjs : 6.6.7
---------------------------------------
Community plugins:

```

**Comment by puku0x** [comment]
That's weird... It works for `*.js` and `*.jsx` files, though.

**Comment by puku0x** [comment]
You need to enable the rule manually because `plugin:@nrwl/nx/typescript` in your root `.eslintrc.json` ignores it.

```js
{
  "root": true,
  "ignorePatterns": ["**/*"],
  "plugins": ["@nrwl/nx"],
  "overrides": [
    :
    {
      "files": ["*.ts", "*.tsx"],
      "extends": ["plugin:@nrwl/nx/typescript"],  // 👈 @typescript-eslint/no-unused-vars is 'off' by default
      "rules": {}
    },
    :
 }
```

https://github.com/nrwl/nx/blob/4343f56da6039649ec2c04553fb361ed725ad255/packages/eslint-plugin-nx/src/configs/typescript.ts#L35-L42

BTW, it works for `*.js` and `*.jsx` files.

**Comment by zaunermax** [comment]
Yes, I know that manually adding works, I wanted to point out, that upon generating a new next app this happens. It should work out of the box when generating a new app right? That's why I wanted to open an issue :raised_hands:
