### ISSUE TITLE
Remove nested "lib" and "app" folders

### ISSUE THREAD

**Issue by gxxcastillo** [nrwl/nx#8156]
## Description
I want to be able to place all of my code directly in the `/src` folder of my applications and libraries.  However, I have not been able to find a way to do this and given the conversation in #3414 it seems this is not currently supported.

## Motivation
I just started getting into NX and one of the things I like about it is how I can actually make the setup pretty flexible by leveraging the app and project configurations.  However, it's not clear to me why this one configuration option is not provided.

In my experience I've never found a need to deeply nest my projects within an extra folder under the `src` folder and this may be my first time seeing this practice. It's unfortunate to have to add this unnecessary extra layer simply as a side-affect of using NX.

## Suggested Implementation
I wonder if we could create a new `projectDir` prop at the top level of project.json.  Optionally, it could be set to an empty string resulting in all code going directly into `/src`.

All of these type of calls:
```  
  return joinPathFragments(
    sourceRoot,
    (projectType === 'application' ? 'app' : 'lib')
  );
```

Would need to be updated to be something like this:
```
  return joinPathFragments(
    sourceRoot,
    projectDir ?? (projectType === 'application' ? 'app' : 'lib')
  );
```

**Comment by FrozenPandaz** [comment]
The layout is supported by Nx but it isn't generated by Nx as it is not what we would recommend. You can feel free to take the code out of `lib` and put it directly under `src`. As mentioned in https://github.com/nrwl/nx/issues/3414#issuecomment-670690016, there are other ways to add this behvior via [Workspace Generators](https://nx.dev/l/r/generators/workspace-generators)
