### ISSUE TITLE
`Missing required argument: target` when using pnpm

### ISSUE THREAD

**Issue by binary64** [nrwl/nx#8158]
## Current Behavior

Running `pnpm nx affected --target=lint --uncommitted=true` shows the nx affected help and "Missing required argument: target".

However running the same with `yarn` works as expected.

### Environment

```
> nx "report"


>  NX  Report complete - copy this into the issue template

  Node : 16.13.0
  OS   : win32 x64
  pnpm : 6.23.6

  nx : 13.3.2
  @nrwl/angular : undefined
  @nrwl/cli : 13.3.2
  @nrwl/cypress : 13.3.2
  @nrwl/devkit : 13.3.2
  @nrwl/eslint-plugin-nx : 13.3.2
  @nrwl/express : undefined
  @nrwl/jest : 13.3.2
  @nrwl/linter : 13.3.2
  @nrwl/nest : undefined
  @nrwl/next : 13.3.2
  @nrwl/node : 13.3.2
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.3.2
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.2
  @nrwl/web : 13.3.2
  @nrwl/workspace : 13.3.2
  @nrwl/storybook : 13.3.2
  @nrwl/gatsby : undefined
  typescript : 4.5.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
```

**Comment by guifeliper** [comment]
Same thing here. 
The following command return  `Missing required argument: target`

`npm run nx affected --target=ANYTARGET`

**Comment by FrozenPandaz** [comment]
This is an error message from `pnpm`, not nx.

`yarn` parses args in a different way than `npm` and `pnpm`. `pnpm` needs a delimiting `--` to separate out flags that are passed to `pnpm` vs flags that are part of the command. The command you are looking for is:

```
pnpm nx -- affected --target=lint --uncommitted=true
```
