### ISSUE TITLE
Custom Command - Unable to update $PATH

### ISSUE THREAD

**Issue by fkolar** [nrwl/nx#8163]
## Current Behavior
When I try to add custom command into my app project.json

```
"targets": {
    "serve": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "commands": [
          "export PATH=$PATH:/My/Custom/PATH/bin",
          "echo $PATH"
        ],
        "cwd": "apps/webapp/examples/AtIssue",
        "parallel": false
      }
    }
  },
```

the  `nx run webapp:serve` prints some default path set by this custom runner and ignoring what I set. 

## Expected Behavior

It needs to include my settings. 

## Steps to Reproduce
1. Add custom command similar to one above
2. run `nx run YOUR_APP:serve`

It will ignore your SET PATH. 

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

```
i304804@C02Y20ECJGH8 next-gen-ui % nx report

>  NX  Report complete - copy this into the issue template

  Node : 12.14.1
  OS   : darwin x64
  npm  : 6.13.4
  
  nx : undefined
  @nrwl/angular : undefined
  @nrwl/cli : 13.3.2
  @nrwl/cypress : undefined
  @nrwl/devkit : 13.3.2
  @nrwl/eslint-plugin-nx : 13.3.2
  @nrwl/express : undefined
  @nrwl/jest : 13.3.2
  @nrwl/linter : 13.3.2
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.3.2
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.2
  @nrwl/web : undefined
  @nrwl/workspace : 13.3.2
  @nrwl/storybook : undefined
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:


```

**Comment by vsavkin** [comment]
Thank you for submitting the issue.

Every command will run in a child process, sort of like this:

```
const cp = require('child_process')
cp.execSync('export BLAH=13') # process1
cp.execSync('echo $BLAH') # process2                                    
```

The export will only affect process1 and its children. It won't affect process2.

You will have to set PATH in front of every command like this:

```
PATH=$PATH:/My/Custom/PATH/bin echo $PATH
```

We could introduce new APIs to set up some context, create a parent process etc, but I'm not sure how widely useful this would be.

Given this I'll close the issue.

Thank you!
