### ISSUE TITLE
Custom Logger Module

### ISSUE THREAD

**Issue by chrisui** [nrwl/nx#8167]
## Description

I would like to be able to provide a custom logging implementation so I can have more control over the output of nx task executions.

## Motivation

Right now when using Nx programatically or in a non trivial way (incl. composing executors together using `runExecutor`) there is no apparent way to control how stdout is streamed.

For various build services and tools I would like to do the following:
1. Stream outputs to individual log files
2. Stream to stdout using a json structured logging format
3. Prettify output with namespacing for interleaved processes (ie. when two runExecutors are run in parallel in the same parent process)

## Suggested Implementation

Provide a "logger" `nx.json` configuration property which is a path/reference to a module exposing an implementation of the typical {info,warn,error,trace,debug} interface.

## Alternate Implementations

Provide a "logger" configuration option to `runExecutor` api.

**Comment by FrozenPandaz** [comment]
We made the decision to not add a logger into the API of `runExecutor` or executors in general.

Instead, you can..

1. Listen to the events that the iterable returned by the executor returns while somehow specifying that the executor should be silent.
2. The executor itself would have an option to specify the format in which it logs output similar to how `eslint` has `--quiet` or `jest` has different reporters.

We would be open to having a silent/reporter option of sorts for our executors but it's a different ask for each different executors.

**Comment by chrisui** [comment]
Thanks for the info. I agree with the decision not to add a logger to individual executors but would expect, given Nx's role as a task runner, greater control at the user level of a whole "run".

There seems a significant semantic difference between output of an executor (a) and the output of nx (b)

a) which is controlled by the implemented process and is critical to that process (so should control independently how it's output is configured and interpreted
b) of which the output it provides when I, as a user, execute it, is not _critical_ but should be useful for user consumption.

That is to say it makes sense not to be able to vary how output is propagated to the user individually per executor but is for the user of nx.

The practicality of this right now is there is no good way of consuming, in any structured way, interleaved logs and propagating to the user nicely.

Things people would like to do within a monorepo setting:

1. Run multiple tasks in parallel
    1. understand what project is emitting what output
    2. be able to filter output (perhaps I only want to propagate to the foreground a particular project and only others if they crash/error)
2. Parse the output of a run so I can better audit with downstream tooling our ci

Note if exposing a logging api is undesireable earlier on in a project lifecycle, my own use case and others would just be solved by having a first-class `--json` cli option which makes wraps the stdout stream in structured logging (with timing meta data, project namespace, tags, target) etc.
