### ISSUE TITLE
(6.4.0) Not able to create new workspace on windows

### ISSUE THREAD

**Issue by mbaljeetsingh** [nrwl/nx#817]
When I run `create-nx-workspace nxt`, I'm not getting any error and no workspace is created also
![image](https://user-images.githubusercontent.com/872762/46937361-b66f3c00-d07e-11e8-9eaf-b36791d15f4f.png)

and when is create the workspace using `@nrwl/schematics` collection with the command
ng new nxt --collection="@nrwl/schematics". I'm getting the following error,
![image](https://user-images.githubusercontent.com/872762/46937512-1b2a9680-d07f-11e8-8bfd-d0ffbb2598b1.png)

I recently updated the `@nrwl/schematics` global package. I was working before.

Angular CLI info
![image](https://user-images.githubusercontent.com/872762/46937575-46ad8100-d07f-11e8-88e4-2fc62e2e09ee.png)

**Comment by bcabanes** [comment]
Hi @mbaljeetsingh!

Would it be possible for you to test these commands? (I'm presuming that you are using `npm`)

```bash
npm uninstall -g @angular/cli
npm uninstall -g @nrwl/schematics
npm cache clean
npm install -g @angular/cli@latest @nrwl/schematics@latest
```

And then try again to create a new workspace.

**Comment by mbaljeetsingh** [comment]
Hi @bcabanes,
Did that, still getting the same error.

![image](https://user-images.githubusercontent.com/872762/47066475-dda34600-d203-11e8-8b33-d6698e253a8f.png)

![image](https://user-images.githubusercontent.com/872762/47066489-ec89f880-d203-11e8-9499-883bd7c785a6.png)

**Comment by mathpaquette** [comment]
same here! #838

**Comment by luchsamapparat** [comment]
Same problem here. After downgrading to 6.3.1 it worked again.

```
+-- @angular/cli@7.0.2
+-- @nrwl/schematics@6.3.1
+-- npm@6.4.0
+-- typescript@3.0.1
```

**Comment by mh453Uol** [comment]
@mbaljeetsingh try create-nx-workspace myWorkspaceName to create a workspace.
Also I had the same issue as you however install angular cli 6.0.0 then it work fine.

**Comment by guibulator** [comment]
create-nx-workspace doesn`t seem to be working on windows anymore.
My setup:
- node  10.14.1
- npm  6.4.1
- ng 7.1.2
- nx 7.1.1

I tried downgrading @nrwl/schematics to 6.3.1 but no luck.
I tried installing the latest node and npm on both my mac and PC.
I succeeded running create-nx-workspace on my mac.
On my PC, I get this error

> Creating a sandbox with the CLI and Nx Schematics...
child_process.js:651
    throw err;
    ^
Error: Command failed: npm install --silent
    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:648:13)
    at Object.<anonymous> (C:\Users\GUIBULATOR\AppData\Local\Yarn\Data\global\no
de_modules\@nrwl\schematics\bin\create-nx-workspace.js:77:21)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)

**Comment by guibulator** [comment]
It fails only when using npm. If I use --yarn, it will work, Any ideas why? I thought it might have been related to admin rights needed to execute the process, but it works with --yarn.

**Comment by mh453Uol** [comment]
@guibulator I had the same issue I followed @bcabanes advice and upgraded the angular cli. I think the issue happens when you dont supply all the argument to create-nx-workspace

**Comment by vsavkin** [comment]
Closing this. If the problem persists with Nx 7.8, could you reopen it?
