### ISSUE TITLE
Nx failed to create a workspace

### ISSUE THREAD

**Issue by duxard** [nrwl/nx#8187]
Hi team,

I'm new to NX framework and I've been trying to create a simple Angular project using instructions listed here:
https://nx.dev/l/a/tutorial/01-create-application

However, I'm getting  "Nx failed to create a workspace" error while creating a new app. I see the following error in logs:

`
npm WARN lifecycle The node binary used for scripts is C:\Program Files\nodejs\node.exe but npm is using C:\Users\ven_astarchenko\AppData\Roaming\npm\node_modules\node\bin\node.exe itself. Use the --scripts-prepend-node-path option to include the path for the node binary npm was executed with.

internal/modules/cjs/loader.js:1174
 throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: c:\Users\ven_astarchenko\IdeaProjects\nxdev\mlp\node_modules\@angular\compiler-cli\bundles\ngcc\main-ngcc.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mlp@0.0.0 postinstall: node ./decorate-angular-cli.js && ngcc --properties es2015 browser module main
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mlp@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ven_astarchenko\AppData\Roaming\npm-cache\_logs\2021-12-15T14_38_41_788Z-debug.log

Command failed: npm install
Workspace creation failed, see above.
` 

Everything goes by well when I'm creating React app using the very same steps. Could you pls advice me on what can be wrong? 

Thanks,
Aleksandr

**Comment by mandarini** [comment]
Hi there @duxard ! Thanks for filing an issue! Can you please check these links?

* https://github.com/nodenv/nodenv/issues/108
* https://stackoverflow.com/questions/51293566/how-to-include-the-path-for-the-node-binary-npm-was-executed-with

There seems to be a mismatch in your node binaries, and maybe the above links could help you resolve this! Let me know if this helps! :)

**Comment by duxard** [comment]
Hi  FrozenPandaz,
thank a lot for the information provided! I was able to resolve this problem by updating NodeJS to 16ver (I had 12 before).

Thanks a lot!
