### ISSUE TITLE
support --minimal and --skip-tests flags for nx generate @nrwl/angular:app

### ISSUE THREAD

**Issue by jeffschulzusc** [nrwl/nx#8217]
## Description
<pre>
$ nx generate @nrwl/angular:app bff-test-client --minimal --skip-tests  --directory test --dryRun
✔ Which stylesheet format would you like to use? · scss
✔ Would you like to configure routing for this application? (y/N) · true

CREATE apps/test/bff-test-client/tsconfig.editor.json
CREATE apps/test/bff-test-client/tsconfig.json
CREATE apps/test/bff-test-client/src/favicon.ico
CREATE apps/test/bff-test-client/.browserslistrc
CREATE apps/test/bff-test-client/tsconfig.app.json
CREATE apps/test/bff-test-client/src/index.html
CREATE apps/test/bff-test-client/src/main.ts
CREATE apps/test/bff-test-client/src/polyfills.ts
CREATE apps/test/bff-test-client/src/styles.scss
CREATE apps/test/bff-test-client/src/assets/.gitkeep
CREATE apps/test/bff-test-client/src/environments/environment.prod.ts
CREATE apps/test/bff-test-client/src/environments/environment.ts
CREATE apps/test/bff-test-client/src/app/app.module.ts
CREATE apps/test/bff-test-client/src/app/app.component.scss
CREATE apps/test/bff-test-client/src/app/app.component.html
CREATE apps/test/bff-test-client/src/app/app.component.ts
CREATE apps/test/bff-test-client/.eslintrc.json
CREATE apps/test/bff-test-client/jest.config.js
CREATE apps/test/bff-test-client/src/test-setup.ts
CREATE apps/test/bff-test-client/tsconfig.spec.json
CREATE apps/test/bff-test-client-e2e/cypress.json
CREATE apps/test/bff-test-client-e2e/src/fixtures/example.json
CREATE apps/test/bff-test-client-e2e/src/integration/app.spec.ts
CREATE apps/test/bff-test-client-e2e/src/plugins/index.js
CREATE apps/test/bff-test-client-e2e/src/support/app.po.ts
CREATE apps/test/bff-test-client-e2e/src/support/commands.ts
CREATE apps/test/bff-test-client-e2e/src/support/index.ts
CREATE apps/test/bff-test-client-e2e/tsconfig.e2e.json
CREATE apps/test/bff-test-client-e2e/tsconfig.json
CREATE apps/test/bff-test-client-e2e/.eslintrc.json
UPDATE angular.json
UPDATE nx.json
UPDATE package.json
UPDATE jest.config.js

NOTE: The "dryRun" flag means no changes were made.
</pre>
## Motivation
dont always want the e2e tests

## Suggested Implementation
same as ng

## Alternate Implementations
now have to go back and remove e2e

**Comment by FrozenPandaz** [comment]
I'm not sure exactly what the expected behavior for `--minimal` is but you can remove the test, e2e, and lint runners by passing:

`--linter none --unitTestRunner none --e2eTestRunner none` produce the following:

![image](https://user-images.githubusercontent.com/8104246/146868670-6960af21-a353-4e7f-ab51-6e0f99604c74.png)

Is this the behavior you are expecting?

**Comment by jeffschulzusc** [comment]
thanks for the reply ...

--minimal as per
https://angular.io/cli/generate

yes, the above dryRun is what i am after ... 
but i don't see these options anywhere 
can add documentation ?
https://nx.dev/l/r/cli/generate

**Comment by Coly010** [comment]
@jeffschulzusc It looks like you linked the doc for the `generate` command.

I guess there might be some confusion between the flags accepted by `generate` command itself and the flags accepted by each possible generator we support via our plugins. 

If you look at the menu on the docs site, there are links to the docs for each generator itself which should list the supported flags for each specific generator.

I hope this helps!! 😄 

As we already support the desired outcome, I'm going to close this issue.
