### ISSUE TITLE
React: Tailwind CSS 3 doesn't work

### ISSUE THREAD

**Issue by smacintyre** [nrwl/nx#8218]
## Current Behavior

If you try to add TailwindCSS to a React project, the tailwind styles are never generated when serving or buildings.

## Expected Behavior

- Tailwind styles are applied

## Steps to Reproduce

- Create a new workspace
- Add the react plugin
- Create a new react application
- Follow the instructions at: https://nx.dev/l/r/guides/using-tailwind-css-in-react
  - Note, using the new `content` key instead of `purge`
- Serve the app

### Failure Logs

- No failure logs

### Environment

```
  Node : 14.18.1
  OS   : darwin x64
  yarn : 1.22.17
  
  nx : 13.3.6
  @nrwl/angular : undefined
  @nrwl/cli : 13.3.6
  @nrwl/cypress : 13.3.9
  @nrwl/devkit : 13.3.9
  @nrwl/eslint-plugin-nx : 13.3.9
  @nrwl/express : undefined
  @nrwl/jest : 13.3.9
  @nrwl/linter : 13.3.9
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.3.9
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.6
  @nrwl/web : 13.3.9
  @nrwl/workspace : 13.3.6
  @nrwl/storybook : 13.3.9
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
```

**Comment by puku0x** [comment]
It works for me. I guess you forgot adding a glob pattern for your app.

```js
// apps/<app-name>/postcss.config.js
module.exports = {
  plugins: {
    tailwindcss: {
      config: 'apps/<app-name>/tailwind.config.js',
    },
    autoprefixer: {},
  },
};
```
```js
// apps/<app-name>/tailwind.config.js
const { createGlobPatternsForDependencies } = require('@nrwl/react/tailwind');

module.exports = {
  content: [
    'apps/<app-name>/src/**/*.{js,jsx,ts,tsx}',
    ...createGlobPatternsForDependencies(__dirname),
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
```
```scss
// apps/<app-name>/src/styles.css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Comment by smacintyre** [comment]
@puku0x Thank you for replying. However, TailwindCSS v3 still doesn't work. I had done all you suggested.

Here is a sample repo: https://github.com/smacintyre/tailwindfail
You can run it from gitpod: https://gitpod.io/#https://github.com/smacintyre/tailwindfail

Exact steps:

1.  `nvm use --lts=fermium`
2. `npx create-nx-workspace tailwindfail --preset=empty --packageManager=yarn --nx-cloud=false`
3. `cd tailwindfail/`
4. `git init && git add . && git commit -m 'Initial commit'`
5. `yarn add -D @nrwl/react`
6. `yarn nx generate @nrwl/react:application fail --style=css --routing --pascalCaseFiles`
7.  `git add . && git commit -m 'Adding react app'`
8. `yarn add -D tailwindcss@latest postcss@latest autoprefixer@latest`
9. `cd apps/fail/`
10. `npx tailwindcss init -p`
11. Update `apps/fail/postcss.config.js`: https://github.com/smacintyre/tailwindfail/blob/main/apps/fail/postcss.config.js
12. Update `apps/fail/tailwind.config.js`: https://github.com/smacintyre/tailwindfail/blob/main/apps/fail/tailwind.config.js
13. Update `apps/fail/src/styles.css`: https://github.com/smacintyre/tailwindfail/blob/main/apps/fail/src/styles.css
14. Update `apps/fail/src/app/App.tsx` to use Tailwind CSS: https://github.com/smacintyre/tailwindfail/blob/main/apps/fail/src/app/App.tsx
15. Remove irrelevant files: `git rm src/app/nx-welcome.tsx src/app/App.module.css`
15. `yarn nx serve`

Output:
```
yarn run v1.22.17
warning ../../package.json: No license field
$ /Users/smacintyre/tmp/tailwindfail/node_modules/.bin/nx serve

> nx run fail:serve
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:4200/, http://127.0.0.1:4200/
<i> [webpack-dev-server] 404s will fallback to '/index.html'

>  NX  Web Development Server is listening at http://localhost:4200/

Entrypoint main [big] 1.58 MiB (1.87 MiB) = runtime.js 50.4 KiB vendor.js 1.53 MiB main.js 5.08 KiB 3 auxiliary assets
Entrypoint polyfills [big] 779 KiB (945 KiB) = runtime.js 50.4 KiB polyfills.js 728 KiB 2 auxiliary assets
Entrypoint styles [big] 486 KiB (579 KiB) = runtime.js 50.4 KiB styles.css 18.9 KiB styles.js 417 KiB 2 auxiliary assets
chunk (runtime: runtime) main.js (main) 3.12 KiB [initial] [rendered]
chunk (runtime: runtime) polyfills.js (polyfills) 683 KiB [initial] [rendered]
chunk (runtime: runtime) runtime.js (runtime) 33.9 KiB [entry] [rendered]
chunk (runtime: runtime) styles.css, styles.js (styles) 400 KiB (javascript) 18.9 KiB (css/mini-extract) [initial] [rendered]
chunk (runtime: runtime) vendor.js (vendor) (id hint: vendor) 1.5 MiB [initial] [rendered] split chunk (cache group: vendor) (name: vendor)
webpack compiled successfully (0b016b64a9ddb9c9)
No issues found.
Entrypoint main [big] 1.58 MiB (1.87 MiB) = runtime.js 50.4 KiB runtime.0b016b64a9ddb9c9.hot-update.js 343 bytes vendor.js 1.53 MiB main.js 5.08 KiB 4 auxiliary assets
Entrypoint polyfills [big] 779 KiB (945 KiB) = runtime.js 50.4 KiB runtime.0b016b64a9ddb9c9.hot-update.js 343 bytes polyfills.js 728 KiB 3 auxiliary assets
Entrypoint styles [big] 487 KiB (579 KiB) = runtime.js 50.4 KiB runtime.0b016b64a9ddb9c9.hot-update.js 343 bytes styles.css 18.9 KiB styles.js 417 KiB styles.0b016b64a9ddb9c9.hot-update.js 514 bytes 4 auxiliary assets
chunk (runtime: runtime) main.js (main) 3.12 KiB [initial]
chunk (runtime: runtime) polyfills.js (polyfills) 683 KiB [initial]
chunk (runtime: runtime) runtime.js, runtime.0b016b64a9ddb9c9.hot-update.js (runtime) 33.9 KiB [entry] [rendered]
chunk (runtime: runtime) styles.css, styles.js, styles.0b016b64a9ddb9c9.hot-update.js (styles) 400 KiB (javascript) 18.9 KiB (css/mini-extract) [initial] [rendered]
chunk (runtime: runtime) vendor.js (vendor) (id hint: vendor) 1.5 MiB [initial] split chunk (cache group: vendor) (name: vendor)
webpack compiled successfully (bf5e2e39b341d465)
No issues found.
```

**Comment by puku0x** [comment]
@smacintyre `<app-name>` should be replaced with `fail`
```js
content: [
  'apps/fail/src/**/*.{js,jsx,ts,tsx}',
  ...createGlobPatternsForDependencies(__dirname),
],
```

**Comment by smacintyre** [comment]
@puku0x Thank you very much! It works, not sure how I missed that. I had done that on the project project I was upgrading. I will try to see why it's not working.

Note for the docs for #8221
- The text still talks about the deprecated `purge` key
- The dark mode configuration should be removed: https://tailwindcss.com/docs/upgrade-guide#remove-dark-mode-configuration
- The variant config should be removed: https://tailwindcss.com/docs/upgrade-guide#remove-dark-mode-configuration

**Comment by puku0x** [comment]
Thank you, I will update the PR later.

**Comment by DOZBORNE** [comment]
I somehow just managed to get this to work. I'm not even sure if it will keep working, but i'm happy it is 😅.

I'm on `"@nrwl/react": "^13.4.5"`, `"tailwindcss": "^3.0.15"`, and all latest versions of other plugins like Postcss and tailwind/forms. 

I have a UI lib, so I want that to share the css, obviously, so I have placed a config file inside the root of my workspace `tailwind-workspace-preset.js` and added my tailwind extended styles there, as well as my plugin config (forms). You can see how to build that file here: https://tailwindcss.com/docs/presets.

I have a `tailwind.config.js` file inside of my app folder pointing to the two directories, and referencing the root preset file as well.

`const { createGlobPatternsForDependencies } = require('@nrwl/react/tailwind');

module.exports = {
  presets: [require('../../tailwind-workspace-preset.js')],
  content: [
    'src/**/*.{js,jsx,ts,tsx}',
    'libs/ui/src/**/*.{js,jsx,ts,tsx}',
    ...createGlobPatternsForDependencies(__dirname),
  ],
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
}`

My postcss file inside of my app folder simply has this configuration: `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};`

I haven't testing it in build yet, but it's working in dev. 

@bdebon, hope this helps!

**Comment by rogerfar** [comment]
Could the docs be updated to reflect tailwind 3? Right now it's installing the latest version but the instructions, and generated config files, are wrong.

**Comment by CodeAndWeb** [comment]
'../../libs/**/*.{js,jsx,ts,tsx}',

should not be required - that is what `...createGlobPatternsForDependencies(__dirname)` is meant do, or am I wrong?

---

This works so far. The only issue I am experiencing is that the auto-refresh in Chrome reflects the changes in the files but does not seem too reload the style sheets.

    <div className="bg-red-100>Test</div>

correctly shows up in red when launching the app. Changing it to:

    <div className="bg-indigo-100>Test</div>

Now shows Test with a transparent background because bg-indigo-100 is not contained in the css file.
Only a manual refresh in Chrome picks up that change.

**Comment by filarrro** [comment]
@CodeAndWeb I have the same problem that auto-refresh is not working and I need to refresh the page manually to see the changes. No matter if JIT mode for tailwind is ON or OFF.
Have you managed to resolve this issue? Or anyone?

I have project generated based on "@nrwl/cli": "14.3.6", "tailwindcss": "^3.1.4" and "react": "18.2.0".

**Comment by wanghy0113** [comment]
> ```
> '../../libs/**/*.{js,jsx,ts,tsx}',
> ```
> 
> should not be required - that is what `...createGlobPatternsForDependencies(__dirname)` is meant do, or am I wrong?
> 
> This works so far. The only issue I am experiencing is that the auto-refresh in Chrome reflects the changes in the files but does not seem too reload the style sheets.
> 
> ```
> <div className="bg-red-100>Test</div>
> ```
> 
> correctly shows up in red when launching the app. Changing it to:
> 
> ```
> <div className="bg-indigo-100>Test</div>
> ```
> 
> Now shows Test with a transparent background because bg-indigo-100 is not contained in the css file. Only a manual refresh in Chrome picks up that change.

Having the same issue. Anyone has a workaround??
