### ISSUE TITLE
Workspace generator `generateFiles()` will generate `.js` and `.js.map` files when using `.ts` template

### ISSUE THREAD

**Issue by junzhengca** [nrwl/nx#8220]
## Current Behavior

I have a workspace generator setup to scaffold some TypeScript code, here is the directory structue and my generator configuration.
![Screenshot 2021-12-18 4 28 38 AM](https://user-images.githubusercontent.com/7855724/146636371-c230d4d2-12eb-46bf-8750-f1b0d4946ee5.png)

```ts
import {
  Tree,
  formatFiles,
  generateFiles,
  installPackagesTask,
  joinPathFragments,
} from '@nrwl/devkit';

export default async function (tree: Tree, schema: any) {
  generateFiles(
    tree, // the virtual file system
    joinPathFragments(__dirname, './files'), // path to the file templates
    schema.path, // destination path of the files
    schema // config object to replace variable in file templates
  );
  await formatFiles(tree);
  return () => {
    installPackagesTask(tree);
  };
}
```

`schema.json` simply includes two parameters: `name` and `path`.

When I try to run the generator, it will generate `.js` and `.map.js` files alongside my `.ts` file.

```bash
$ nx workspace-generator core-data-schema --path=packages/data/src/lib --name=myValidator
CREATE packages/data/src/lib/README.md
CREATE packages/data/src/lib/myValidator.js
CREATE packages/data/src/lib/myValidator.js.map
CREATE packages/data/src/lib/myValidator.ts
```

## Expected Behavior

`.js` and `.map.js` files should not be generated.

...or at least should have a way to specify if I want to generate them.

## Steps to Reproduce

Simply setup a new generator with above mentioned configurations.

### Environment

```
>  NX  Report complete - copy this into the issue template

  Node : 14.17.6
  OS   : linux x64
  npm  : 6.14.15
  
  nx : 13.3.1
  @nrwl/angular : undefined
  @nrwl/cli : 13.3.1
  @nrwl/cypress : undefined
  @nrwl/devkit : 13.3.1
  @nrwl/eslint-plugin-nx : 13.3.1
  @nrwl/express : undefined
  @nrwl/jest : 13.3.1
  @nrwl/linter : 13.3.1
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.3.1
  @nrwl/nx-cloud : 13.0.0
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.1
  @nrwl/web : undefined
  @nrwl/workspace : 13.3.1
  @nrwl/storybook : undefined
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.5.5
  ---------------------------------------
  Community plugins:
```

**Comment by puku0x** [comment]
You can use `*.ts.template` for generator templates but if you prefer to use `*.ts`, you should exclude `**/files/*`. 

```js
// tools/tsconfig.tools.json
{
  "extends": "../tsconfig.base.json",
  "compilerOptions": {
    "outDir": "../dist/out-tsc/tools",
    "rootDir": ".",
    "module": "commonjs",
    "target": "es5",
    "types": ["node"],
    "importHelpers": false
  },
  "include": ["**/*.ts"],
  "exclude": ["**/files/*"]  // 👈 exclude them to not to be compiled to .js/.js.map
}
```

**Comment by junzhengca** [comment]
> You can use `*.ts.template` for generator templates but if you prefer to use `*.ts`, you should exclude `**/files/*`.
> 
> ```js
> // tools/tsconfig.tools.json
> {
>   "extends": "../tsconfig.base.json",
>   "compilerOptions": {
>     "outDir": "../dist/out-tsc/tools",
>     "rootDir": ".",
>     "module": "commonjs",
>     "target": "es5",
>     "types": ["node"],
>     "importHelpers": false
>   },
>   "include": ["**/*.ts"],
>   "exclude": ["**/files/*"]  // 👈 exclude them to not to be compiled to .js/.js.map
> }
> ```

This works like a charm! Will close this issue, maybe we should add some documentation for this? This is the link I used:
https://nx.dev/l/r/generators/creating-files#creating-files-with-a-generator
