### ISSUE TITLE
https://github.com/nrwl/nx/releases not in sync with npm releases any more

### ISSUE THREAD

**Issue by leon** [nrwl/nx#8241]
## Current Behavior

https://github.com/nrwl/nx/releases
was before kept up to date with the current npm releases.
but they are lagging behind now.

- github 13.3.6
- npm 13.3.11

## Expected Behavior
that npm and github should be in sync

**Comment by FrozenPandaz** [comment]
@vsavkin must have forgot to add release notes for those. We will add release notes for upcoming versions.

Do not worry, they are legitimate versions published by us.

**Comment by FrozenPandaz** [comment]
Just published `13.3.12` with a changelog. 👍
