### ISSUE TITLE
Error "'style' is not found in schema" when generating an Angular library module

### ISSUE THREAD

**Issue by zoechi** [nrwl/nx#8252]
## Current Behavior

`npx nx g @nrwl/angular:library --name product-search --directory app/feature --tags platform:typescript,platform:angular,scope:app-feature --prefix pdp --routing false --importPath @pdp/product-search`

Results in this error:

```
'style' is not found in schema
```

I had to remove the `style` entry in `nx.json` from 
```json
"@nrwl/angular:library": {
      "style": "scss",
      "linter": "eslint",
      "unitTestRunner": "jest"
    },
```

I'm pretty sure I didn't add this entry manually. Was this removed in a recent update? I couldn't find anything in the https://github.com/nrwl/nx/releases

### Environment

```
  Node : 16.13.1
  OS   : win32 x64
  npm  : 8.3.0

  nx : 13.3.11
  @nrwl/angular : 13.3.11
  @nrwl/cli : 13.3.11
  @nrwl/cypress : 13.3.11
  @nrwl/devkit : 13.3.11
  @nrwl/eslint-plugin-nx : 13.3.11
  @nrwl/express : undefined
  @nrwl/jest : 13.3.11
  @nrwl/linter : 13.3.11
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.11
  @nrwl/web : undefined
  @nrwl/workspace : 13.3.11
  @nrwl/storybook : 13.3.11
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.0
         @angular/cdk: 13.0.0
         @angular/common: 13.0.0
         @angular/compiler: 13.0.0
         @angular/core: 13.0.0
         @angular/forms: 13.0.0
         @angular/material: 13.0.0
         @angular/material-moment-adapter: 13.1.0
         @angular/platform-browser: 13.0.0
         @angular/platform-browser-dynamic: 13.0.0
         @angular/router: 13.0.0
         @ngrx/component: 13.0.2
         @ngrx/component-store: 13.0.2
         @ngrx/effects: 13.0.2
         @ngrx/entity: 13.0.2
         @ngrx/router-store: 13.0.2
         @ngrx/store: 13.0.2
         @angular-devkit/build-angular: 13.0.4
         @angular/cli: 13.0.4
         @angular/compiler-cli: 13.0.0
         @angular/language-service: 13.0.0
         @ngrx/schematics: 13.0.2
         @ngrx/store-devtools: 13.0.2
         @storybook/angular: 6.4.9
         eslint-plugin-ngrx: 2.0.2

(node:27712) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\zoechbau\source\plansee\data-platform\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by erasmussenBHTP** [comment]
I have a similar issue when using the @nrwl/angular:component generator I get an error saying that 'linter' is not found in schema. I'm on 13.3.6 after recently doing small incremental upgrades (i.e. v11 latest, v12, v12 latest, v13, v 13 latest) from v11. All migrations were applied without issues. If I remove the @nrwl/angular:component node from my nx.json generators, I'm able to add components via the angular CLI without issues.

**Comment by nvedrines** [comment]
I have a similar issue when using @nrwl 13.3.9.

Executing task: npx nx generate @nrwl/angular:library --name=ngs --directory=ngs/security --no-interactive --dry-run <
'style' is not found in schema

**Comment by Areen3** [comment]
it turns out that the style section has dropped out of the library creation area, how do you create the application it is
probably because as the library schema from nx.json is loaded and there is a style entry, it is a bug
but that's my guess

**Comment by BenLune** [comment]
I have a similar issue while creating a new library. Thanks a lot for the workaround, it worked for me.

**Comment by jbistis** [comment]
I have the same issue creating a new library. Thank you for the workaround, it worked for me too.

**Comment by MarkusCodes** [comment]
Had the same issue, removing style:scss worked, thanks. Would be nice to know what the long-term solution is.

**Comment by palmtreefrb** [comment]
Same issue here. Removed style:scss and it worked for me as well.

**Comment by brianpooe** [comment]
Still getting this issue in v13.4.4

**Comment by FrozenPandaz** [comment]
Yes, the option was removed from the `@nrwl/angular:library` generator.

@leosvelperez we should write a migration to remove defaults.
