### ISSUE TITLE
Serve with custom port doesn't work for Nest projects

### ISSUE THREAD

**Issue by tamtakoe** [nrwl/nx#8259]
If I set port in the `project.json` of Nest-project I see no changes. Server is still on 3333 port.
```
...
 "serve": {
      "executor": "@nrwl/node:execute",
      "options": {
        "buildTarget": "api:build",
        "port": 3001
      }
    },
...
```
But the same works for web (e.g. React) projects

**Comment by funber** [comment]
I have the same issue. Can not change the default port value. I have tried to do that in project.json or in "nx serve .... --port 3001". Nothing happens.
