### ISSUE TITLE
help me! I get an error when I refresh the webrower. error occurred while building production

### ISSUE THREAD

**Issue by quyphan97** [nrwl/nx#8267]
![image](https://user-images.githubusercontent.com/59947963/147030584-e1c8862a-2474-4014-b211-fabf2280add3.png)

version:
"@next/bundle-analyzer": "^12.0.7",
 "@next/mdx": "^12.0.7",
 "@nrwl/next": "13.3.12",
  "next": "12.0.7",
  "next-seo": "^4.28.1",
  "next-translate": "^1.2.0",
   "react": "17.0.2",

**Comment by FrozenPandaz** [comment]
Sorry, there's not enough information here for us to help. Do you have a repo that we can use to reproduce the issue?
