### ISSUE TITLE
Documentation: Add some documentation how to create an angular component library with storybook + tailwind

### ISSUE THREAD

**Issue by CodeCakePie** [nrwl/nx#8276]
## Description
I would be interested in creating an angular component library with tailwind + storybook, but I have no idea how to connect the created tailwind.config.js with storybook

## Motivation
I think many developers would benefit from it 😄 

## Suggested Implementation
Create a blog post

**Comment by svallory** [comment]
I'd like to add that documentation on the difference between the many library generators would be a huge help to newcomers. I'm just starting with Nx and it's very hard to decide between options like `@nrwl/angular:library` and `@schematics/angular:library`. Plus, there's also `@nrwl/angular:library-secondary-entry-point` and no docs on the trade-off between that and a separate lib.

Right now I'm generating each of them and comparing the generated code which is a lot of work :/

**Comment by mandarini** [comment]
Hi there @CodeCakePie @svallory ! Thanks for creating a feature request! :)

Would [this guide here by @juristr](https://juristr.com/blog/2021/08/nextjs-storybook-tailwind-nx/) help, or are you looking for something else?

**Comment by CodeCakePie** [comment]
Hi @mandarini

Thx for your suggestion, I already tried all tutorials i found by googleing "nx angular component library with tailwind and storybook", but none of them used the new `ng generate @nrwl/angular:setup-tailwind` generator but i would really prefer to use that one, as it is integrated in the cli now...

And I didn´t found many tutorials for using angular with tailwind in general.

I think that the  `ng generate @nrwl/angular:setup-tailwind` would need more documentation

**Comment by vladimirdrayling** [comment]
I'm trying to integrate tailwind within a lib with `project.json`. And it works only in `*.scss` files like this:
```scss
:host {
  @apply flex flex-col border-r-neutral-500;
}
```

If I add classes in `*.html` files:
```html
<a class="hover:bg-amber-400 p-2 dark:text-neutral-200">...</a>
```
the styles are not applied.

### `libs/shared/project.json`
```json
{
  "targets": {
    "build": {
      "executor": "@nrwl/angular:ng-packagr-lite",
      "options": {
        "project": "libs/shared/ng-package.json",
        "tailwindConfig": "libs/shared/tailwind.config.js",
        // ...
      },
      // ...
  },
  // ...
}
```

### `libs/shared/tailwind.config.json`
```js
module.exports = {
  theme: {
    extend: {},
  },
  plugins: [],
};
```

Same goes to the lib with a `secondary entry`.

Hope someone has a solution

**Comment by Flusinerd** [comment]
Hello, I am having the same issues and cant get it working.
I tried multiple approaches but neither of them works. Did someone got this working?

**Comment by mandarini** [comment]
Hi there! Thank you for your interest! I'll try to find a repo that's setup with Angular+Tailwind+Storybook and post it here at some point!

**Comment by mandarini** [comment]
Would [this article](https://blog.nrwl.io/set-up-tailwind-css-with-angular-in-an-nx-workspace-6f039a0f4479) be helpful? I understand it's not using Storybook, but maybe if you combine the React+Tailwind+Storybook one with that one, something makes more sense? I am really sorry, I do not have time to look into it more at the moment, and create a repo.. :/

**Comment by CodeCakePie** [comment]
Thank you for all your responses!

@tomstolarczuk had the solution to the problem :)

**Comment by mandarini** [comment]
@CodeCakePie @tomstolarczuk  here's a sample Tailwind+Storybook repo--> https://github.com/leosvelperez/nx-storybook-tailwind

**Comment by marckassay** [comment]
I just created this [post](https://marckassay.github.io/workspace/node/2022/03/07/angular-tailwind-nx-storybook.html) derived from ['Set up Tailwind CSS with Angular in an Nx workspace'](https://blog.nrwl.io/set-up-tailwind-css-with-angular-in-an-nx-workspace-6f039a0f4479).

**Comment by mandarini** [comment]
@marckassay thanks, I tweeted it! :)
