### ISSUE TITLE
[swc] - building a publishable react library does not generate type definitions (d.ts)

### ISSUE THREAD

**Issue by rodrigofariow** [nrwl/nx#8279]
Nx **13.3.12**

## Current Behavior

First, I created a nx workspace `npx create-nx-workspace --preset=react` using version 13.3.12.

Then, I tried to create a publishable react library using `swc` as the compiler:
`yarn nx g @nrwl/react:library --compiler=swc --publishable --importPath=@my-lib --name=my-lib --style=none`

and then build it:
`yarn nx run my-lib:build`

I get:
![image](https://user-images.githubusercontent.com/22502084/147116728-598e3541-f18e-42d5-8d84-89572923b1a7.png)

## Expected Behavior

I expected the output to **generate type definitions**:

Here is the output when building with `babel` as the compiler instead:
![image](https://user-images.githubusercontent.com/22502084/147116935-87081890-ef79-4649-885a-76d4dc34be44.png)

Is this something related to `swc` only or can Nx do something about it?

Thanks for your time and appreciate the effort on getting `swc` available so fast for us! 🙏 😉

**Comment by gperdomor** [comment]
Same here with 14.1.7

**Comment by gperdomor** [comment]
Also from version 14.1.8 or greater, the build output change to only one index.js and projects that use the publishable lib stop working. 
<img width="188" alt="Screen Shot 2022-06-14 at 5 56 10 PM" src="https://user-images.githubusercontent.com/371939/173696073-17be13c3-90e7-4637-aace-0e7e50b842ce.png">

**Comment by gperdomor** [comment]
@FrozenPandaz @AgentEnder any know reason for this? :( how can i help?

**Comment by tienne** [comment]
any update? same with 15.6.2

**Comment by rodrigofariow** [comment]
UPDATE:
I found a workaround that uses `tsc` directly to generate the declaration files after the build step is done.

First, you will need to create another tsconfig.json for your lib that extends `tsconfig.lib.json`:

`tsconfig.declaration.json`
```json
{
  "extends": "./tsconfig.lib.json",
  "compilerOptions": {
    "emitDeclarationOnly": true,
    "declaration": true,
    // declarationDir should point to the root dist folder on your workspace
    // Yours might be "../../dist" (depending on where your lib is located)
    "declarationDir": "../../../dist"
  }
}
```

Then, in `project.json` (or `workspace.json` depending on your nx version) you can encapsulate the `build` command to:
1. Run the actual build using an nx executor (specified as `build-internal`)
2. Generate `d.ts` files using `tsc`

Here is my lib `project.json` file:
```json
    "build-internal": {
      "executor": "@nrwl/rollup:rollup",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/libs/karoo-ui/core",
        "tsConfig": "libs/karoo-ui/core/tsconfig.lib.json",
        "project": "libs/karoo-ui/core/package.json",
        "entryFile": "libs/karoo-ui/core/src/index.ts",
        "compiler": "swc"
        ...
      },
      ...
    },
    "build": {
      "executor": "nx:run-commands",
      "options": {
        "command": "pnpm nx run karoo-ui-core:build-internal && pnpm tsc -p ./libs/karoo-ui/core/tsconfig.declaration.json"
      }
    },
```

This should place the declaration files at the same folder as the `outputPath`. Here is how it looks like for my lib:
<img width="410" alt="image" src="https://user-images.githubusercontent.com/22502084/215338667-70224635-8dcf-40ba-a00b-c0cfc8304439.png">

Hope this helps someone!

Cheers
