### ISSUE TITLE
Bug: jasmine-marbles with jest

### ISSUE THREAD

**Issue by Bielik20** [nrwl/nx#828]
# Description

nrwl: `6.4.0`
test-runner: `jest`

```ts
const value = of('foo');
const expected = of('foo');
expect(value).toBeObservable(expected);
```

## Current Behavior

`jasmine-marbles` does not work with `jest`. When running tests I get `TypeError: expect(...).toBeObservable is not a function`.

## Expected Behavior

`jasmine-marbles` should work with `jest`.

## Rationale

When following the [jest-preset-angular guide](https://github.com/thymikee/jest-preset-angular) and adding `jest` to a standard angular-cli project `jasmine-marbles` work as expected. But when using `nx` built-in support for `jest` `jasmine-marbles` do not work.

I think it is worth noting that VSCode detects that test methods (`expect`, `describe` etc.) are from `jest` in an `nx` project. However, in an angular-cli project it points to `@types/jasmine`.

## Alternatives

`jest-marbles` work but lack some of `jasmine-marbles` functionalities.

**Comment by FrozenPandaz** [comment]
Fixed by:

https://github.com/synapse-wireless-labs/jasmine-marbles/commit/2bc640e73042d0417a6ca967081b9d78a799ebbc

You can now use `jasmine-marbles` with `jest` 🎉 

> Re: I think it is worth noting that VSCode detects that test methods (expect, describe etc.) are from jest in an nx project. However, in an angular-cli project it points to @types/jasmine.

Refer to #816
