### ISSUE TITLE
NestJS Build fails in Docker - No cached ProjectGraph is available

### ISSUE THREAD

**Issue by SerdarN92** [nrwl/nx#8288]
## Current Behavior
Locally i have no problems to build my NestJS Application. In Docker with node:14-slim as baseimage, it is failing with the error:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/7069847/147240147-dcc8f189-49a9-47f0-b6e5-1ad0343567cc.png">

I also set 

ENV NX_CACHE_PROJECT_GRAPH=false

in the Dockerfile, but it did not help.

## Expected Behavior
I expect that it should work with no problems.

### Environment
 Node : 16.11.1
  OS   : win32 x64
  npm  : 8.0.0

  nx : 13.3.9
  @nrwl/angular : 13.3.9
  @nrwl/cli : 13.3.9
  @nrwl/cypress : 13.3.9
  @nrwl/devkit : 13.3.9
  @nrwl/eslint-plugin-nx : 13.3.9
  @nrwl/express : undefined
  @nrwl/jest : 13.3.9
  @nrwl/linter : 13.3.9
  @nrwl/nest : 13.3.9
  @nrwl/next : undefined
  @nrwl/node : 13.3.9
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.9
  @nrwl/web : undefined
  @nrwl/workspace : 13.3.9
  @nrwl/storybook : 13.3.9
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.1.1
         @angular/cdk: 13.1.1
         @angular/common: 13.1.1
         @angular/compiler: 13.1.1
         @angular/core: 13.1.1
         @angular/forms: 13.1.1
         @angular/google-maps: 13.1.1
         @angular/material: 13.1.1
         @angular/material-moment-adapter: 13.1.1
         @angular/platform-browser: 13.1.1
         @angular/platform-browser-dynamic: 13.1.1
         @angular/platform-server: 13.1.1
         @angular/router: 13.1.1
         @fortawesome/angular-fontawesome: 0.10.1
         @nguniversal/express-engine: 13.0.1
         @angular-devkit/build-angular: 13.1.2
         @angular/cli: 13.1.2
         @angular/compiler-cli: 13.1.1
         @angular/language-service: 13.0.3
         @nguniversal/builders: 13.0.1

**Comment by PhilippCl** [comment]
Hi @SerdarN92, I think I found a solution to this problem. I encountered the Error as well while dockerizing our Build Process.
As the Error Message Indicates, you need to call the "decorate-angular-cli.js" File before running the Build Command.
You can do this by changing it to

> RUN node ./decorate-angular-cli.js && \
    npm run build

Note: You need to remove `ENV NX_CACHE_PROJECT_GRAPH=false` otherwise it won't work

**Comment by SerdarN92** [comment]
Hi @PhilippCl , thank you so much for your answer. I will try it and tell you, if it worked.

**Comment by SerdarN92** [comment]
@PhilippCl you are my hero. I tried before the command, but did not remove the ENV NX_CACHE_PROJECT_GRAPH=false. 

Thank you so much! Whenever you want you can get a beer from me :)

**Comment by stefanbinder** [comment]
I receive the same error, but using nextJS and react.  
I don't have the command `decorate-angular-cli.js` available. 
I did try the ENV NX_CACHE_PROJECT_GRAPH=true/false as well, but nothing.

**Comment by SerdarN92** [comment]
@stefanbinder does the Error only come up in your Dockerfile?

**Comment by stefanbinder** [comment]
@SerdarN92 yes it's just coming up in the Dockerfile 
(I guess because of cached project graph on local system)

I'm trying again to find a solution but still the same problem.

**Comment by stefanbinder** [comment]
I found a little trick to jump over that problem!
What is did is executing `nx dep-graph` before the build, but important with an --file export, so that the server isn't starting:

```
RUN nx dep-graph --file dep-graph.json
RUN nx r web-app:build
```
