### ISSUE TITLE
Make Fastify a 1st class citizen similar to Express/Nest by adding an official plugin.

### ISSUE THREAD

**Issue by omardoma** [nrwl/nx#8297]
## Description

An official [Fastify](https://github.com/fastify/fastify) Nx plugin similar to the one for Express/Nest.

## Motivation

[Fastify](https://github.com/fastify/fastify) is a wonderful framework for Node.js and has a very large community that could benefit from Nx, it is also very closely associated to/maintained by Node.js Core contributors, so an official plugin would really help drive the adoption of Nx and introduce it to more projects/use cases, as well as, help both communities.

## Suggested Implementation

[Fastify](https://github.com/fastify/fastify) has a great [cli](https://github.com/fastify/fastify-cli) that already makes it very easy to generate a project with different presets, run a Fastify server with configurable port, debugging mode, watch mode, log level and many more options. So it can be wrapped as an Nx generator/executor. The use of fastify-cli is essential imo, because it handles a lot of things for the app out of the box such as: Graceful shutdown, Safe promises usage and protection against memory leaks, listening on 0.0.0.0 when containerized and etc..

## Alternate Implementations

Currently in order to work with Fastify (or any non supported framework such as AWS SAM, Serverless etc...) in an Nx workspace, you can generate a nrwl/node:application then override the `project.json` targets to compile TS as well as run a custom command to serve/package:

```json
    "build": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "commands": [
          "tsc -p tsconfig.app.json"
        ],
        "cwd": "apps/fastify-app",
        "parallel": false
      }
    },
    "serve": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "commands": [
          "tsc -p tsconfig.app.json -w",
          "fastify start ../../dist/out-tsc/apps/fastify-app/app.js -w",
        ],
        "cwd": "apps/fastify-app",
        "parallel": true
      }
    }
```

However there is a heavy downside that the `paths` defined in the `tsconfig` are not resolved correctly because `tsc` is used directly and no Webpack path aliasing/similar functionality is available, so its a bit hard/inconvenient to import libs into the app codebase without their aliased paths. It also makes using Fastify with Nx feel unnatural. You can workaround it by using a tool like `tsc-alias` as follows:

```json
    "build": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "commands": [
          "tsc -p tsconfig.app.json",
          "tsc-alias -p tsconfig.app.json"
        ],
        "cwd": "apps/fastify-app",
        "parallel": false
      }
    },
    "serve": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "commands": [
          "tsc -p tsconfig.app.json -w",
          "tsc-alias -p tsconfig.app.json -w",
          "fastify start ../../dist/out-tsc/apps/fastify-app/app.js -w"
        ],
        "cwd": "apps/fastify-app",
        "parallel": true
      }
    }
```

**Comment by rubiagatra** [comment]
Fastify User here, what can I help to work this one out?.

I am using https://www.npmjs.com/package/@plugified/nx-fastify and is breaking on `"13.4.6"`

```
➜ nx-flutter-fastify-terraform (main) ✗ yarn nx g @plugified/nx-fastify:application api

yarn run v1.22.17
$ /github/nx-flutter-fastify-terraform/node_modules/.bin/nx g @plugified/nx-fastify:application api
TypeError: workspace_1.toFileName is not a function
```

@omardoma @vsavkin

**Comment by Javadebi** [comment]
> Fastify User here, what can I help to work this one out?.
> 
> I am using https://www.npmjs.com/package/@plugified/nx-fastify and is breaking on `"13.4.6"`
> 
> ```
> ➜ nx-flutter-fastify-terraform (main) ✗ yarn nx g @plugified/nx-fastify:application api
> 
> yarn run v1.22.17
> $ /github/nx-flutter-fastify-terraform/node_modules/.bin/nx g @plugified/nx-fastify:application api
> TypeError: workspace_1.toFileName is not a function
> ```
> 
> @omardoma @vsavkin

Did you manage to fix the issue?

**Comment by kokoskiwi** [comment]
hi are there any new news

@rubiagatra @omardoma did you try out what @Javadebi said? no problems anymore?

@Javadebi so you mean I just create with `nx g @nrwl/node:application my-new-app` a node app, and just use Fastify as a library? and there won't be any issues? because I am a noob with nx, overall i am a junior dev, and my biggest fear is, that if I go off the road and use off-the-road stuff like Fastify (since it is not officially compatible), that I will run into bugs. Because I can not deal with them. I will get into depression, watch anime for the rest of the day, and delete at the next day everything and go again with an on-the-road solution like Express

**Comment by Javadebi** [comment]
> hi are there any new news
> 
> @rubiagatra @omardoma did you try out what @Javadebi said? no problems anymore?
> 
> @Javadebi so you mean I just create with `nx g @nrwl/node:application my-new-app` a node app, and just use Fastify as a library? and there won't be any issues? because I am a noob with nx, overall i am a junior dev, and my biggest fear is, that if I go off the road and use off-the-road stuff like Fastify (since it is not officially compatible), that I will run into bugs. Because I can not deal with them. I will get into depression, watch anime for the rest of the day, and delete at the next day everything and go again with an on-the-road solution like Express

sorry for delay, yea you wont have problem with fastify if you go this way but as you said if you run into a problem, you have to figure it out by yourself because nobody is here to help you with fastify, fastify has weak community and thats the biggest weakness in fastify. I recommend if you haven't started your project with fastify, just go with express.

**Comment by laneme** [comment]
For those still being skeptical, you likely wont have any problems with the methods provided above. 

If you look into what nx generates for you when you run the nrwl/express generator, you'll notice it is identical to a `@nrwl:node` application. So all you have to do install fastify and place it on `main.ts`.

**Comment by rubiagatra** [comment]
yes we using fastify by `@nrwl/node`
