### ISSUE TITLE
Cannot use the SWC compiler - @nrwl/js:swc

### ISSUE THREAD

**Issue by florinrelea** [nrwl/nx#8305]
## Current Behavior

![Bug Image](https://i.imgur.com/3RSp9YD.png)

Excepting the path bugs, I receive this error only when compiling with SWC. No error when using tsc
`Return type of exported function has or is using private name X`

## Expected Behavior

![Correct behavior](https://i.imgur.com/8eewcX8.png)

## Steps to Reproduce

```
npx create-nx-workspace

# In the project directory
npm i -D @nrwl/js

nx g @nrwl/js:library --name=testlib --buildable --compiler=swc --importPath=testlib

nx build testlib
```

[Github Repo](https://github.com/florinrelea/nx-swc-bug)

### Environment

```
 Node : 15.14.0
  OS   : win32 x64
  npm  : 7.7.6
  
  nx : 13.4.1
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.1
  @nrwl/cypress : undefined
  @nrwl/devkit : 13.4.1
  @nrwl/eslint-plugin-nx : 13.4.1
  @nrwl/express : undefined
  @nrwl/jest : 13.4.1
  @nrwl/linter : 13.4.1
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.1
  @nrwl/web : undefined
  @nrwl/workspace : 13.4.1
  @nrwl/storybook : undefined
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
         @nrwl/js: 13.4.1
```

**Comment by vadistic** [comment]
Ok, so I think the way this issue is described by OP is a bit confusing but I think there is really something there.

I'm on linux (or WSL) and I was ussing using yarn:
- `npx create-nx-workspace`
- `nx g @nrwl/js:library --name=my-swc-lib --buildable --compiler=swc`
- `nx build my-swc-lib`

```
> nx run my-swc-lib:build

Compiling with SWC for my-swc-lib...
npx: installed 26 in 7.462s
command not found: swc
Command failed: npx swc ../my-swc-lib -d ../../dist/packages/my-swc-lib/src --source-maps --no-swcrc --config-file=/.../tmp/packages/my-swc-lib/.swcrc.generated
npx: installed 26 in 7.462s
command not found: swc


 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "my-swc-lib:build" failed

   Failed tasks:
   
   - my-swc-lib:build
   
   Hint: run the command with --verbose for more details.
```

I have swccli bin in `node_modules/.bin/swc` & `npx swc` or `yarn swc` works jsut fine. 

I'm on @nrwl `13.7.0`, I am usually to run all kinds of projects in my company so I do not think it's my misconfigured env.

Random guess - something is quite wrong with child_process cwd/shell

**Comment by vadistic** [comment]
Does it work with `npx nx build testlib`?

I just had really similar issue yesterday with `@nrwl/js` swc compiler - different error but it may be different platform (WSL) `command not found: swc`.

Calling explicitly with local nx binary fixed it (`yarn nx build xxx` in my case).

It seems to me there is something wrong with paths or module resolution when using global nx cli here. It does not have local binaries on $PATH.
