### ISSUE TITLE
ESLint throwing circular dependency issues (what feels) at random

### ISSUE THREAD

**Issue by robbievandam** [nrwl/nx#8313]
## Current Behavior
So I've been trying out nx the past few days and so far it looks very promising!

Now I've been playing around with different structures and the issue seems to be returning, so not sure whether it's a bug or just me doing something wrong. It seems to be at random that ESLint is throwing circular dependencies:
```
Circular dependency between "api-core-feature" and "api" detected: api-core-feature -> api -> api-core-feature

Circular file chain:
- libs/api/core/feature/src/lib/api-core-feature.module.ts
- apps/api/src/app/app.module.ts (eslint@nrwl/nx/enforce-module-boundaries)
```

Often it also throws: `imports of apps are forbidden (nx-enforce-module-boundaries)`, but these seem to go away automatically.

Everything works fine, running the linter also shows no issues, and neither does creating a build. I've no boundaries setup in ESLint and there are no tags added to the libs.

![eslint-err](https://i.imgur.com/YXg9sZF.png)

![dep-graph](https://i.imgur.com/InlaaEH.png)

## Expected Behavior
To only throw actual circular deps.

## Steps to Reproduce
Keeps happening at random, but it's mainly happening to the stuff I import in the `ApiCoreFeatureModule`. Although, It's also happened in other spots.

### Environment
MacOS on both VSCode and WebStorm.

node 16.13.1
npm 8.1.2

```
"@nrwl/angular": "13.4.1",
"@nrwl/cli": "13.4.1",
"@nrwl/cypress": "13.4.1",
"@nrwl/eslint-plugin-nx": "13.4.1",
"@nrwl/jest": "13.4.1",
"@nrwl/linter": "13.4.1",
"@nrwl/nest": "^13.4.1",
"@nrwl/node": "13.4.1",
"@nrwl/tao": "13.4.1",
"@nrwl/workspace": "13.4.1"
```

**Comment by demisx** [comment]
When I get circular deps issues reported in VS Code, the first thing I do is check with `npx nx affected:lint`. If the latter doesn't report any errors, it's usually a cache issue in VS Code and it goes away after restarting it. This happens quite often when I move libs around.

**Comment by robbievandam** [comment]
I've found that sometimes the errors don't disappear after restarting the IDE _(like I said, it happens in both VSCode and WebStorm)_ and the only solution which seems to remove them is completely removing my `node_modules` and re-installing them :/ 

Haven't tried removing the `node_modules/.cache` folder though.

**Comment by twittwer** [comment]
Sounds similar to #8319

**Comment by robbievandam** [comment]
Definitely sounds like the same issue as my lib folder name equals the app name. 

Removing the cache folder does nothing. So it either disappears at random or I’ll have to reinstall the packages completely.

**Comment by ivibe** [comment]
I have the same issue. My IDE is VS Code. Apparently it's a cache issue as mentioned by @demisx . My workaround is to force linting across entire monorepo
```
nx run-many --target=lint --all --parallel --force
```
and then just to restart IDE.

**Comment by FrozenPandaz** [comment]
Thanks for trying Nx.

From the picture of the dependency graph, it doesn't seem like you should be having this error especially after clearing the cache and restarting.

Could you please provide a repo that we can use to reproduce the issue?

**Comment by robbievandam** [comment]
I'd have to set up a new project for that and hope the error pops-up again. But then again I doubt others would then experience it as the error would disappear for me when re-installing the node packages, which would be the same for others installing it for the first time.

I'll see if I can find some time somewhere to try this out, but I've honestly just started to ignore it, as now I know it's not an actual error, and they sometimes disappear and sometimes don't. Seeing as it only happens right after I add a new lib, I'm aware of it, and it doesn't bother me that much.

I also haven't tried out the suggestion by @ivibe, but this might save some time compared to my solution, I'll come back on that one!

**Comment by qortex** [comment]
I can confirm the same happens to me when adding a new library. I got used to it and now lint/restart when this happens, and I confirm it makes the issue disappear. (cf this early bug report I didn't make sense of : #8319 )

It happened a lot to me when setting up Nx module boundaries, because that's when you add lots of libs & play with tags. I guess it is less of an annoyance when the codebase is more stable.

**Comment by BOBRIWE** [comment]
We have similar issue, but in our case `nx lint` finds an error in CI but locally lint passes (and circular dependency really exist. Webstorm not showing this error either). It started happening after migration from 13.1.4 to 13.4.6.

**Comment by meeroslav** [comment]
@BOBRIWE by locally you mean running it in the terminal? This should be the same as the CI.

The source of this error is that in IDE or while running eslint directly from the terminal (without nx) repo can have an outdated project graph cached resulting in unexpected circular dependencies. I will look into this more carefully in the upcoming days.

If your `nx ... lint` command gives different results on CI and locally then this is a different error.

**Comment by BOBRIWE** [comment]
@meeroslav locally on my PC in terminal, yes.
I've issue with dep-graph as well (https://github.com/nrwl/nx/issues/8601). I just tested it and my graph not working, it can't find any relations
