### ISSUE TITLE
Global install of nx does not find yarn plug'n'play packages

### ISSUE THREAD

**Issue by Person-93** [nrwl/nx#8315]
## Possible duplicate of https://github.com/nrwl/nx/issues/2386
I'm not sure if this falls under that issue's scope since this is only about the global package.

## Current Behavior
Running `nx` in a workspace that uses plug'n'play results in an error prompting me to run `yarn install`.

## Expected Behavior
It should find the installed plugins.

## Steps to Reproduce
 - create a new workspace
 - run `yarn set version berry`
 - delete node_modules if present
 - in .yarnrc.yml, set nodeLinker to pnp
 - run any nx command using the globally installed package

### Failure Logs
```console
$ nx

>  NX   ERROR  Could not find Nx modules in this workspace.

  Have you run npm/yarn install?
```

### Environment
```
  Node : 16.13.1
  OS   : linux x64
  yarn : 3.1.1
  
  nx : undefined
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.1
  @nrwl/cypress : undefined
  @nrwl/devkit : undefined
  @nrwl/eslint-plugin-nx : undefined
  @nrwl/express : undefined
  @nrwl/jest : undefined
  @nrwl/linter : undefined
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.1
  @nrwl/web : undefined
  @nrwl/workspace : 13.4.1
  @nrwl/storybook : undefined
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : undefined
  ---------------------------------------
  Community plugins:
  	@nrwl/nx-plugin: 13.4.1
```

**Comment by Person-93** [comment]
Maybe it should use the [PnP API](https://yarnpkg.com/advanced/pnpapi) instead of require.

https://github.com/nrwl/nx/blob/7fd7849729da3e407d0dc9247bb28e46ddf08f80/packages/cli/bin/nx.ts#L32-L36

**Comment by FrozenPandaz** [comment]
Let's track this as part of https://github.com/nrwl/nx/issues/2386

Could you please add your information there as well?
