### ISSUE TITLE
Tslint fails when I include "node_modules/@nrwl/schematics/src/tslint" rules directory

### ISSUE THREAD

**Issue by kevinbeal** [nrwl/nx#832]
I updated my @nrwl/schematics package from 6.1.1 to 6.4.0 and now I get an ugly error in my editor:

> SyntaxError: Unexpected token / in JSON at position 874
>     at JSON.parse (<anonymous>)
>     at Object.readJsonFile (MY_PROJECT/node_modules/@nrwl/schematics/src/utils/fileutils.js:57:17)
>     at Object.readAngularJson (MY_PROJECT/node_modules/@nrwl/schematics/src/command-line/shared.js:235:24)
>     at new Rule (MY_PROJECT/node_modules/@nrwl/schematics/src/tslint/nxEnforceModuleBoundariesRule.js:37:44)
>     at Object.loadRules (MY_PROJECT/node_modules/tslint/lib/ruleLoader.js:46:24)
>     at Linter.getEnabledRules (MY_PROJECT/node_modules/tslint/lib/linter.js:215:29)
>     at Linter.lint (MY_PROJECT/node_modules/tslint/lib/linter.js:98:33)
>     at TSLintPlugin.processLinting (/Applications/WebStorm.app/Contents/plugins/tslint/js/languageService/tslint-plugin.js:77:20)
>     at TSLintPlugin.getErrors (/Applications/WebStorm.app/Contents/plugins/tslint/js/languageService/tslint-plugin.js:55:21)
>     at TSLintPlugin.process (/Applications/WebStorm.app/Contents/plugins/tslint/js/languageService/tslint-plugin.js:23:29)

```
"tslint": "~5.11.0",
"typescript": "~3.1.3",
"@angular/core": "^7.0.0",
"codelyzer": "^4.5.0",
```

In my `tslint.json` file, I have to comment a line out to get tslint to work at all:

```
{
	"rulesDirectory": [
		"node_modules/codelyzer",
		"node_modules/@nrwl/schematics/src/tslint", // <-getting rid of this fixes tslint
		"node_modules/tslint-microsoft-contrib",
		"node_modules/rxjs-tslint-rules"
	],
...
```

Does the new version require me to use a different rules directory or something? What am I missing?

**Comment by kevinbeal** [comment]
Yeah, that was exactly it. I didn't think to check that file. It was just coincidental that I upgraded the package.

Thank you! 😅

**Comment by tcoz** [comment]
Note that I had the same problem, and had to remove the entry from my tslint.json file (the root one in an nrwl/angular workspace). The indicated directory simply is not where it is supposed to be. There is a schematics directory, but no tslint file in it. I've installed the latest and greatest (as of today) nrwl/workspace and nrwl/angular packages.
