### ISSUE TITLE
generate @nrwl/react:stories is destructive

### ISSUE THREAD

**Issue by Brian-McBride** [nrwl/nx#8335]
# @nrwl/react:stories is destructive

## Problem
```
nx generate @nrwl/react:stories --project=components
```

Will be destructive to existing stories via UPDATE

### example: 

```
CREATE libs/components/src/lib/Footer/Footer.stories.tsx
CREATE libs/components/src/lib/Header/Header.stories.tsx
UPDATE libs/components/src/lib/LoginForm/LoginForm.stories.tsx
CREATE libs/components/src/lib/Logos/MicrosoftLogo.stories.tsx
UPDATE libs/components/src/lib/RegisterForm/RegisterForm.stories.tsx
CREATE libs/client/components/src/lib/ScanRequest/ScanRequest.stories.tsx
```

## Proposed Feature

Add a flag to update, default to not updating existing stories.

## Why?

Because developers customize stories with various states or custom wrappers.

**Comment by mandarini** [comment]
Thanks for filing this feature request @Brian-McBride ! It's in the plans, we'll get to it, I promise! :)
