### ISSUE TITLE
RFC: Dangerously opt-out of edge in dependency graph

### ISSUE THREAD

**Issue by cdaringe** [nrwl/nx#8343]
## Description

I want to remove a module from the dependency graph, removing it intentionally from being consider in `affected` behavior.

## Motivation

I have a module that will be used _everywhere_, frequently. It is also changed often. Changing this module will re-test the world on a daily basis, and it will be wasteful. Common tasks like `build` or `test` will implicitly test and protect any breakages from this module.

Because I am confident that this configuration module is safe to change and captured by guaranteed-to-run _other targets_, I want to isolate it from the affected graph.

My module, for example, is just

```ts
// contants mapping
export const KEY1 = "str1"
export const KEY2 = "str2"
// ...
export const KEY_BANANAS = "something with bananas"
```

## Suggested Implementation

🤷 

## Alternate Implementations

Currently, I'm considering using babel/swc transformers. My module will be in JSON, not in typescript, and the transformer will swap values. In this regard, my project complexity increases and my many targets needing transpilation grow more complex and slow down slightly. This is all just to eject from the dependency graph.

**Comment by FrozenPandaz** [comment]
Does adding the file to `.nxignore` solve the issue? Changes to the file will be ignored after that.

**Comment by cdaringe** [comment]
Surely I considered this at the time, but I cannot recall why I found it unsatisfactory. Until I can answer this question, I will close and assume nxignore as adequate
