### ISSUE TITLE
Generate a angular lib without module

### ISSUE THREAD

**Issue by mackelito** [nrwl/nx#8358]
## Description

If a library only contains a service then there is no real point of having a module at all
## Motivation

Less code will be generated

## Suggested Implementation

Add an option to skip the generation of module file

**Comment by FrozenPandaz** [comment]
This is already implemented via https://nx.dev/angular/library#skipmodule. :smile:

**Comment by mackelito** [comment]
Oh.. I see, so it is just not implemented in the vs code console plugin..
