### ISSUE TITLE
Display test results and code coverage on TFS/DevOps(VSTS)

### ISSUE THREAD

**Issue by skorunka** [nrwl/nx#837]
I have setup my workspace to generate test results using `jest-junit` but every app or lib overrides the previously generated `junit.xml` file, so it actually ends up with the lastly executed tests.

Is there any way how to merge the `junit.xml` results and not to override?

Anyway, my question is actually more related to if anyone has successfully integrated JEST test results/codecoverage into TFS/DevOps(VSTS) CI pipeline?

**Comment by mohyeid** [comment]
I am having the same problem. I got to batch jest-junit index.js and override it with the following 
```
processor = (report, reporterOptions = {}) => {
  // If jest-junit is used as a reporter allow for reporter options
  // to be used. Env and package.json will override.
  const options = getOptions.options(reporterOptions);

  const jsonResults = buildJsonResults(report, fs.realpathSync(process.cwd()), options);

  // Ensure output path exists
  mkdirp.sync(path.dirname(options.output));

  if (fs.existsSync(options.output.replace('xml', 'json'))) {
    var contents = JSON.parse(fs.readFileSync(options.output.replace('xml', 'json'), 'utf8'));
    const currentAttr = jsonResults.testsuites[0]._attr;
    contents.testsuites[0]._attr.tests += currentAttr.tests;
    contents.testsuites[0]._attr.failures += currentAttr.failures;
    contents.testsuites[0]._attr.time += currentAttr.time;
    jsonResults.testsuites.shift();
    jsonResults.testsuites = contents.testsuites.concat(jsonResults.testsuites);
  }
  // Write data to file
  fs.writeFileSync(options.output, xml(jsonResults, {
    indent: '  '
  }));
  fs.writeFileSync(options.output.replace('xml', 'json'), JSON.stringify(jsonResults));

  // Jest 18 compatibility
  return report;
};
```

But now I am facing a new issue for collecting coverage for sonar. It expects one lcov.info file per repo, but NX is creating one per app/lib. Now I am wondering if a jest.config per app/lib was a good design or not?

**Comment by skorunka** [comment]
@mohyeid Yep, I did the same with this https://github.com/Leonidas-from-XIV/node-xml2js
So, I have a build task which actually merge all the cobertura files into one. It's more like a hack then a solution. I just wonder what is the recommendation from NRWL team. I don't believe they didn't face this issue as CC results is pretty common task.

**Comment by flugger** [comment]
We also encountered the issue of the junit.xml file getting replaced for each test suite. We found out Azure DevOps can handle multiple xml-files, so our solution was to change the root `jest.config.js` to include the following reporters:

```js
reporters: ['default', ['jest-junit', { outputDirectory: './junit', outputName: new Date().getTime() + '.xml' }]]
```

This way it will create a new xml file inside a `junit` folder for every test suite with the name of the current timestamp the suite ran. Then you can add the `junit` folder to Azure DevOps.

Our solution of only running JUnit in CI environment was to add an environment variable to our command:

`JUNIT=true ng test --ci --code-coverage`

And then add a conditional to our Jest config:

```js
reporters: process.env.JUNIT
    ? ['default', ['jest-junit', { outputDirectory: './junit', outputName: new Date().getTime() + '.xml' }]]
    : ['default'],
```

Hope this helps someone and hoping for a better solution out of the box from the Nx team in the future.

**Comment by TimGeerts** [comment]
Any news on this?  
@flugger 's option is a viable one to have devops merge all the files, but it seems a bit strange that we'd have to _hack_ it together rather than having something out of the box?

**Comment by vsavkin** [comment]
@jaysoo could you comment on this?

**Comment by Pace17881** [comment]
@flugger 
Our solution is to add the following line into each jest config per project.
`reporters: ["default", ["jest-junit", {outputDirectory: './coverage/apps/app1'}]]`

@vsavkin @FrozenPandaz @bcabanes 
Maybe this is a possible solution for nx?

**Comment by EvtK** [comment]
@vsavkin is this feature request on the backlog somewhere?

**Comment by adinath** [comment]
@flugger @EvtK  - We resolved it by adding jest-config  dependency and following piece of code in jest-config.json

```
reporters: [["jest-unit", {
    "outputDirectory": '<rootDir>',
    "outputName": "test-report.xml"
}]]
```

this will generate test-report.xml in respective directories which you can converge in azure devops task.

**Comment by jaysoo** [comment]
It looks like there isn't any work needed from Nx's to support multiple junit reports.

@adinath 's solution should work for everyone since `<rootDir>` will be the root of each app/lib, which means the reports will no override each other.

**Comment by EvtK** [comment]
@adinath thanks for sharing your solution.

In the end the solution is the same: you need to distinguish in generating the reports and then later merge them yourself. It would be nice if this was an out of the box functionality within NX. But.. the current solutions are sufficient.

**Comment by FortinFred** [comment]
I was able to get unique files per libs/apps using this jest config.

```
reporters: [
    'default',
    [
      'jest-junit',
      {
        suiteName: 'jest tests',
        outputDirectory: 'build/test-results',
        uniqueOutputName: 'true',
        classNameTemplate: '{classname}-{title}',
        titleTemplate: '{classname}-{title}',
        ancestorSeparator: ' › ',
        usePathForSuiteName: 'true',
      },
    ],
  ],
```

Getting files with uuid numbers:
junit-d44f8e60-ff33-11ea-a312-85dbd838ca1a.xml

**Comment by ntziolis** [comment]
In current nx versions its not necessary anymore to configure this for each app / lib. Instead its possible to extend the `jest.preset.js` and have the setting applied to all apps / libs. 

```js
const nxPreset = require('@nrwl/jest/preset');

// this ensures test results are only be generated in Azure DevOps CI pipeline
if (process.env.TF_BUILD) {
  nxPreset.reporters = [
    [
      'jest-junit',
      {
        outputDirectory: '<rootDir>',
        outputName: 'test-report.xml',
      },
    ],
  ];
}

module.exports = {
  ...nxPreset,
};
```

In you pipeline simply add the following after running the tests:
```yml
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-report.xml'
    testRunTitle: 'Jest Unit Tests'
    mergeTestResults: true
    failTaskOnFailedTests: true
```

**Comment by nelsond6** [comment]
@ntziolis thanks for mentioning the jest.preset.js file.  Modifying this file was the only way we could get this working. Thanks again!

**Comment by EvtK** [comment]
@ntziolis nice solution you have there, thanks for sharing!

Right now I'm facing the issue that when test results are retrieved from the cache, I am missing the junit reports. These are not included in the nx cache. Has anyone yet come accross this issue? @jaysoo maybe?

**Comment by GreedyA1** [comment]
I did add reporters as mentioned above. like: 

`  nxPreset.reporters = [
    [
      'jest-junit',
      {
        outputDirectory: '<rootDir>',
        outputName: 'test-report.xml',
        suiteName: 'Jest tests',
        classNameTemplate: '{classname} / {title}',
        titleTemplate: '{classname} / {title}',
        ancestorSeparator: ' / ',
        usePathForSuiteName: 'true',
      },
    ],
  ];
`
 The issue is that now the tests aren't shown in terminal or logs.
 
![image](https://user-images.githubusercontent.com/18186211/140288958-4cf91afb-1c00-4d0b-bbf5-329d7c15029a.png)

Is there a way to have both?

**Comment by GreedyA1** [comment]
nvm. fixed it. was missing defaults in reporters: 

```
nxPreset.reporters = [
        'default',
        [
            'jest-junit',
            {
                outputDirectory: '<rootDir>',
                outputName: 'test-report.xml',
                suiteName: 'Jest tests',
                classNameTemplate: '{classname} / {title}',
                titleTemplate: '{classname} / {title}',
                ancestorSeparator: ' / ',
                usePathForSuiteName: 'true',
                includeConsoleOutput: 'true',
            },
        ],
    ];
```

**Comment by amitrai99** [comment]
> In current nx versions its not necessary anymore to configure this for each app / lib. Instead its possible to extend the `jest.preset.js` and have the setting applied to all apps / libs.
> 
> Here are the complete steps:
> 
> First install the reporter package in your workspace as dev dependency `npm install --save-dev jest-junit`
> 
> The extend the `jest.preset.js`:
> 
> ```js
> const nxPreset = require('@nrwl/jest/preset');
> 
> // this ensures test results are only be generated in Azure DevOps CI pipeline
> if (process.env.TF_BUILD) {
>   nxPreset.reporters = [
>     [
>       'jest-junit',
>       {
>         outputDirectory: '<rootDir>',
>         outputName: 'test-report.xml',
>         suiteName: 'Jest tests',
>         classNameTemplate: '{classname} / {title}',
>         titleTemplate: '{classname} / {title}',
>         ancestorSeparator: ' / ',
>         usePathForSuiteName: 'true',
>       },
>     ],
>   ];
> }
> 
> module.exports = {
>   ...nxPreset,
> };
> ```
> 
> And last extend your pipeline by adding the following after running the tests (same as previously pointed out):
> 
> ```yaml
> - task: PublishTestResults@2
>   inputs:
>     testResultsFormat: 'JUnit'
>     testResultsFiles: '**/test-report.xml'
>     testRunTitle: 'Jest Unit Tests'
>     mergeTestResults: true
>     failTaskOnFailedTests: true
> ```

What version of `nx` is this method supported from? I'm on nx 6.
