### ISSUE TITLE
The @nrwl/workspace 13.4.3 on npm does not contain the code available on github

### ISSUE THREAD

**Issue by mauriziovitale** [nrwl/nx#8370]
## Current Behavior
If importing **libraryGenerator** from `import { libraryGenerator } from '@nrwl/workspace/generators';` the code is an outdated version. i.e. there is no karma support
<img width="505" alt="Screenshot 2022-01-04 at 14 05 32" src="https://user-images.githubusercontent.com/14923305/148063510-d55dfcc6-5610-46b0-8a92-d577105dafe8.png">
It looks like the code is [this one outaded](https://github.com/nrwl/nx/blob/f1911a71f3ccecd26ecde0c1c1c765e89df04e17/packages/workspace/src/generators/library/library.ts)
## Expected Behavior
The libraryGenerator should provide support for karma as available [here](https://github.com/nrwl/nx/blob/13.4.3/packages/angular/src/generators/library/library.ts#L120)

## Steps to Reproduce
 **1**. Generate a new workspace with latest nx 13.4.3
npx create-nx-plugin my-org --pluginName my-plug
**2**. Generate a new generator
nx generate @nrwl/workspace:workspace-generator example
**3** Import the libraryGenerarot
`import { libraryGenerator } from '@nrwl/workspace/generators'

**Comment by mauriziovitale** [comment]
I think I was using the wrong libraryGenerator import

**Comment by FrozenPandaz** [comment]
Thank you for double-checking.
