### ISSUE TITLE
Use Nx for publishable widgets

### ISSUE THREAD

**Issue by ArielGueta** [nrwl/nx#8371]
Hi,

We need to create a publishable React widget with Nx. How do we build a buildable and publishable library and bundle the external modules from npm inside it so that the consumers don't have to install anything? For example, the React source code should be bundled inside. 

Thanks.

**Comment by FrozenPandaz** [comment]
There's nothing stopping you from using Nx for publishable widgets but we don't have any easy way to get started doing so. You'll likely need to change how you do your build.

I don't think a github issue is going to be the best way to help you here. If you join the [community slack](https://go.nrwl.io/join-slack), you would get more help.
