### ISSUE TITLE
When generating Standalone angular library there is no way to skipFormat files

### ISSUE THREAD

**Issue by mauriziovitale** [nrwl/nx#8386]
##Precondition: 
Have an angular.json file not formatted

## Current Behavior
When generating a Standalone angular library there is no way to skipFormat files

## Expected Behavior
When generating Standalone angular library if the --skipFormat option is passed no files should be formatted

## Steps to Reproduce
nx @nrwl/angular:library --name=feature --skipFormat --standaloneConfig

The issue is [here](https://github.com/nrwl/nx/blob/1b6c0ee7fab95c352002228c7be73fee25f7a71d/packages/workspace/src/generators/convert-to-nx-project/convert-to-nx-project.ts#L85)

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by mauriziovitale** [comment]
Fixed on a forked repo 
https://github.com/nrwl/nx/pull/8387

**Comment by Coly010** [comment]
Hey @mauriziovitale! Thanks for raising an issue!
What is the actual ill behaviour you're experiencing by not being able to `skipFormat`?

**Comment by mauriziovitale** [comment]
> Hey @mauriziovitale! Thanks for raising an issue! What is the actual ill behaviour you're experiencing by not being able to `skipFormat`?

Hey @Coly010 same behavior as [angular generator](https://github.com/nrwl/nx/blob/master/packages/angular/src/generators/library/library.ts#L102)
I hope it makes sense
