### ISSUE TITLE
When committing the prompt does not offer workspace as available scope

### ISSUE THREAD

**Issue by mauriziovitale** [nrwl/nx#8404]
## Description
When committing the prompt does not offer **workspace** as the available feat scope

## Suggested Implementation
The scope array should contain workspace as well

**Comment by FrozenPandaz** [comment]
Sorry, it might be a bit confusing because the `@nrwl/workspace` package contains a few different scopes within itself.

Please use the `core` or `misc` scope instead of `workspace`. We are actively working on separating some of that logic out into separate packages.
