### ISSUE TITLE
What does `batchJest` supposed to do?

### ISSUE THREAD

**Issue by YonatanKra** [nrwl/nx#8413]
While investigating the Nx code I stumbled upon this function:
https://github.com/nrwl/nx/blob/54a5eb989df46d9768d4bf1cd060cd7160bfd0c8/packages/jest/src/executors/jest/jest.impl.ts#L125
A quick search found no usage of this function nor does it seem to be tested.
What is it used for?

**Comment by FrozenPandaz** [comment]
It's supposed to be a way to run jest for nx project's using a single `jest` sub process while keeping the cacheability for each project. We're still working on this functionality though so it's not exposed yet.
