### ISSUE TITLE
Command `nx run` works, `nx r` doesn't

### ISSUE THREAD

**Issue by poeck** [nrwl/nx#8426]
## Current Behavior

When I run `nx run web:serve`, everything works perfectly - but when I run `nx r web:serve` I get this:

```bash
paul@pop-os:~/projects/remark$ nx r web:serve
info  - Loaded env from apps/web/.env.local
Segmentation fault (core dumped)
```

## Expected Behavior

`nx r` to work the same as `nx run`.

### Failure Logs

Failing Command:
```bash
paul@pop-os:~/projects/remark$ nx r web:serve
info  - Loaded env from apps/web/.env.local
Segmentation fault (core dumped)
```

Working Command:
```bash
paul@pop-os:~/projects/remark$ nx run web:serve

> nx run web:serve
info  - Loaded env from apps/web/.env.local
info  - automatically enabled Fast Refresh for 1 custom loader
event - compiled client and server successfully in 2s (703 modules)
[ ready ] on http://localhost:3000
```

### Environment

```
  Node : 16.9.1
  OS   : linux x64
  yarn : 1.22.15

  nx : 13.4.2
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.2
  @nrwl/cypress : 13.4.3
  @nrwl/devkit : 13.4.2
  @nrwl/eslint-plugin-nx : 13.4.2
  @nrwl/express : 13.4.2
  @nrwl/jest : 13.4.2
  @nrwl/linter : 13.4.2
  @nrwl/nest : undefined
  @nrwl/next : 13.4.3
  @nrwl/node : 13.4.2
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.4.3
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.2
  @nrwl/web : 13.4.3
  @nrwl/workspace : 13.4.2
  @nrwl/storybook : 13.4.3
  @nrwl/gatsby : undefined
  typescript : 4.5.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:

(node:19430) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /home/paul/projects/remark/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by poeck** [comment]
I tried creating a fresh next app inside my workspace, and again `nx run next:serve` worked perfectly but  `nx r next:serve` failed with `Segmentation fault (core dumped)`.

**Comment by jaysoo** [comment]
Can confirm that this is a problem running with nextjs only.

In Node 14 you get an error message saying:

```
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Invalid host defined options
```

In Node 16 you get an `SIGSEGV` error.

**Comment by jaysoo** [comment]
Really odd that `run` vs `r` matters since the latter is just an alias. We'll investigate but in the meantime use `run` or the short form `nx serve next`.

**Comment by poeck** [comment]
That is exactly what I thought. It's fine, just really confused me.

**Comment by poeck** [comment]
@jaysoo any updates?

**Comment by jaysoo** [comment]
Not yet, it's on my list.

**Comment by poeck** [comment]
After updating everything to latest, I'm facing the same Issue with a small custom executor. `nx run browser:serve` works perfectly again, `nx r browser:serve` ends in a SIGSEGV. So I don't think this problem is related with @nrwl/next only.

**Comment by kanika7** [comment]
No, I don't think its related to @nrwl/next only. I upgraded NX and storybook as well and I'm starting to get `Segmentation fault      node "$basedir/node_modules/nx/bin/nx.js" "$@" ` when I try to build storybook
