### ISSUE TITLE
[Question] How to fetch nested state in Effects

### ISSUE THREAD

**Issue by KuldeepDesai** [nrwl/nx#843]
How do I inject nested state in datapersistence via constructor. By default it selects root state.

e.g.
`ApplicationState{
     moduleState: ActionReducerMap{
           childComponent:ChildState
    }
}`
When I generate effects using ng g ngrx... command.
It shows in constructor as `DataPersistence<ChildState>`, however the actual value in the effect is ApplicationState

**Comment by antiformatiker** [comment]
I stumbled upon the same issue. I've got a library with multiple nested states and inside the run method the state is defined as a nested child state but actually consists the application state.

**Comment by antiformatiker** [comment]
I just realized, that the schematics create an extra interface called `[Feature]PartialState` which represents a "partial" app state. So you can use this interface inside your effect class and you're good to go.

**Comment by brandonroberts** [comment]
Closing as resolved.
