### ISSUE TITLE
Linter issue - ES modules is not supported 

### ISSUE THREAD

**Issue by erez-walkme** [nrwl/nx#8444]
## Current Behavior
linter fails to run in react project

## Expected Behavior
linter run through the command npx nx run <project>:lint 

## Steps to Reproduce
run command nox nx run <project>:lint for a new react type project 

### Failure Logs
> nx run nx-test-linter:lint --verbose
Must use import to load ES Module: /Users/erez.asulin/walkme/test-nx/node_modules/@eslint/eslintrc/universal.js
require() of ES modules is not supported.
require() of /Users/erez.asulin/walkme/test-nx/node_modules/@eslint/eslintrc/universal.js from /Users/erez.asulin/walkme/test-nx/node_modules/eslint/lib/linter/linter.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename universal.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/erez.asulin/walkme/test-nx/node_modules/@eslint/eslintrc/package.json.

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/erez.asulin/walkme/test-nx/node_modules/@eslint/eslintrc/universal.js
require() of ES modules is not supported.
require() of /Users/erez.asulin/walkme/test-nx/node_modules/@eslint/eslintrc/universal.js from /Users/erez.asulin/walkme/test-nx/node_modules/eslint/lib/linter/linter.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename universal.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/erez.asulin/walkme/test-nx/node_modules/@eslint/eslintrc/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1149:13)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/erez.asulin/walkme/test-nx/node_modules/eslint/lib/linter/linter.js:27:9)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
### Environment

  Node : 12.16.3
  OS   : darwin x64
  npm  : 6.14.4

  nx : undefined
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.3
  @nrwl/cypress : 13.4.3
  @nrwl/devkit : 13.4.3
  @nrwl/eslint-plugin-nx : 13.4.3
  @nrwl/express : undefined
  @nrwl/jest : 13.4.3
  @nrwl/linter : 13.4.3
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.4.3
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.3
  @nrwl/web : 13.4.3
  @nrwl/workspace : 13.4.3
  @nrwl/storybook : 13.4.3
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:

➜  test-nx git:(main)

**Comment by meeroslav** [comment]
Thank you @erez-walkme for reporting an issue. Can you please provide a minimal reproduction for this issue?

Based on the error reported it seems that you have been trying to use `require` over `import` for ES module.
