### ISSUE TITLE
Storybook Integration still not supports @storybook/web-components as uiFramework option in config generator

### ISSUE THREAD

**Issue by kishok** [nrwl/nx#8496]
## Current Behavior

 currently storybook config generator only supports two values only **@storybook/angular** , **@storybook/react**
## Expected Behavior

it should support more options (ex. @storybook/web-components).  And also update relevant docs and add examples.

### Environment

Nx 13.4.4

**Comment by mandarini** [comment]
Hi there @kishok ! Thank you for this feature request!

Actually, you can use any of the following values:
```
        "@storybook/angular",
        "@storybook/react",
        "@storybook/html",
        "@storybook/web-components",
        "@storybook/vue",
        "@storybook/vue3",
        "@storybook/svelte"
```

however, the `storybook-configuration` generator will only generate actual stories for `@storybook/angular` and `@storybook/react`. For all the rest of the options, it will generate the `.storybook` folders and the configuration files. Everything except for stories, and anything else framework-specific.

If I understand correctly, you are asking that we create generators for stories etc for web-components, as well, right? This is not in our plans at the moment, however, you can go ahead and generate Storybook configuration for web-components using Nx, as you would normally do, and then write your own stories!

Also, you can of course help in the creation for full web-components support! :)

**Comment by kishok** [comment]
thanks @mandarini. i will check the config generator and also happy to support in Nx plugin to generate / Build libraries for web components.

**Comment by alvinalexander** [comment]
@mandarini @kishok  What is exact command to use ? I have tried `nx g @nrwl/storybook:configuration <my-lib> --uiFramework @storybook/web-components --dry-run` and it gives me following error 

```bash
Property 'uiFramework' does not match the schema. '@storybook/web-components' should be one of @storybook/angular,@storybook/react.
```

**Comment by mandarini** [comment]
Hi there!

Nx Storybook does not support web components. The `@nrwl/storybook:configuration` generator will only generate actual stories for `@storybook/angular` and `@storybook/react`.

You can change the executor to use `web-components`, if you want, but you cannot configure Storybook using `@storybook/web-components`. The UI frameworks listed above are for the executor. If you want to use `@storybook/web-components`, you can configure Storybook manually, and then invoke the executor using `@storybook/web-components`.

There are no plans at the moment to support generators for `@storybook/web-components`.

**Comment by alvinalexander** [comment]
Got it! Thanks for clarifying. Do you happen to know of any reference configs for storybook+web components inside a nx monorepo?

**Comment by mandarini** [comment]
Hm, I do not, to be honest... I will let you know if I find something, or I make a reproduction. Sounds good?

**Comment by alvinalexander** [comment]
Sounds good:) Thanks

**Comment by HackPoint** [comment]
> . Do you happen to know of any reference configs for storybook+web components inside a nx monorepo?

Is it possible to run both uiFrameworks in one storybook? react/angular
Like so: "uiFramework": [@storybook/react, @storybook/angular], I need to show a catalog of both react and angular

**Comment by mandarini** [comment]
Hi there @HackPoint ! I am not sure I understand what you mean. That is not possible, because Storybook will only work for one framework at a time. This is not a Nx shortcoming, it's how Storybook works. You can have individual projects for Angular and React, and then you can use Storybook composition to see both in your browser. Please check out this guide on how to [set up Storybook Composition with Nx](https://nx.dev/storybook/storybook-composition-setup).

**Comment by Stusaw** [comment]
Any ideas about this?
`Property 'uiFramework' does not match the schema. '@storybook/angular' should be one of @storybook/react,@storybook/html,@storybook/web-components,@storybook/vue,@storybook/vue3,@storybook/svelte.`

It appears @storybook/angular has been removed from the enum?

**Comment by Kleberto** [comment]
I have the same problem as @Stusaw .

"@nrwl/storybook": "14.1.5", is a working version for me.

**Comment by Stusaw** [comment]
> I have the same problem as @Stusaw .
> 
> "@nrwl/storybook": "14.1.5", is a working version for me.

Just reading this @Kleberto 
https://github.com/nrwl/nx/commit/51b66d139498f8cc15b7166b29e2c11ee08e6705

**Comment by mandarini** [comment]
Yep, that's on me, I'm sorry, I'll get it fixed. what's the issue that you're facing?

**Comment by Stusaw** [comment]
> Yep, that's on me, I'm sorry, I'll get it fixed. what's the issue that you're facing?

In project.json "uiFramework" option won't accept '@storybook/angular' as a valid option, so won't build. Not sure if it was intentional to remove from enum? Or is there a new way we now need to configure? Thanks

**Comment by mandarini** [comment]
Oh yes, it was intentional. If you're on Nx v. 14.1.8 and up (on an Angular project using Storybook) then we changed the syntax. If you use `nx migrate` it should have migrated everything automatically. Did you upgrade without using `nx migrate`? @Stusaw [Here](https://nx.dev/storybook/extra-topics-for-angular-projects)'s the documentation, and please do let me know which version you are on and if you used `nx migrate`, and from which version to which.

**Comment by mandarini** [comment]
@Stusaw @Kleberto This is 100% intentional. Starting Nx v.14.1.8 we are moving away from the Nx executor, and we're using the native Storybook executor. If you're using `nx mgirate` to update to the latest version, it should have already made the changes to your `project.json` files. If you did not use `nx migrate`, you can use the [`change-storybook-targets`](https://nx.dev/packages/storybook/generators/change-storybook-targets) generator, and that will change all your `project.json` files of Angular projects using Storybook to use the new schema. Please read the [new documentation](https://nx.dev/storybook/extra-topics-for-angular-projects), and let me know if you have any issues.

**Comment by Stusaw** [comment]
Thanks @mandarini . The generator was successful in updating the project.json file, however, I had assets configured like so, that are now being rejected. "Property assets is not allowed"
```
       "assets": [
          {
            "input": "libs/shared/ui/src/lib/translation/src/assets/i18n",
            "glob": "**/*",
            "output": "assets/i18n"
          },
          {
            "input": "libs/lynx-sale-configurator-mfe/feature-salecard/src/assets/i18n/feature-salecard",
            "glob": "*.json",
            "output": "assets/i18n/feature-salecard"
          }
```
How do these now get confgured? Thanks

**Comment by mandarini** [comment]
So, Storybook now can be configured as you would configure it in any app without Nx. So, you can just use the pure Storybook documentation!

Here is a link I found regarding assets:

https://storybook.js.org/docs/angular/configure/images-and-assets

**Comment by DzmVasileusky** [comment]
@mandarini that's kinda strange but `nx migrate 14.1.9` haven't updated project.json for me
it just output the following
```
nx migrate 14.1.9
Fetching meta data about packages.
It may take a few minutes.
Fetching nx@14.1.9

>  NX  The migrate command has run successfully.

- package.json has been updated
- there are no migrations to run, so migrations.json has not been created.

>  NX  Next steps:

- Make sure package.json changes make sense and then run 'npm install'
- To learn more go to https://nx.dev/using-nx/updating-nx
```

My project json is looking the same
```
        "storybook": {
            "executor": "@nrwl/storybook:storybook",
            "options": {
                "uiFramework": "@storybook/angular",
                "port": 4400,
                "config": {
                    "configFolder": "libs/ui-kit/.storybook"
                },
                "projectBuildConfig": "ui-kit:build-storybook"
            },
            "configurations": {
                "ci": {
                    "quiet": true
                }
            }
        },
        "build-storybook": {
            "executor": "@nrwl/storybook:build",
            "outputs": ["{options.outputPath}"],
            "options": {
                "uiFramework": "@storybook/angular",
                "outputPath": "dist/storybook/ui-kit",
                "config": {
                    "configFolder": "libs/ui-kit/.storybook"
                },
                "projectBuildConfig": "ui-kit:build-storybook",
                "stylePreprocessorOptions": {
                    "includePaths": ["libs/ui-kit/src/styles"]
                },
                "styles": [
                    "libs/shared/content/fonts/proxima-nova.css",
                    "libs/ui-kit/src/styles/global.scss",
                    "libs/ui-kit/.storybook/docs-typography.scss"
                ]
            },
            "configurations": {
                "ci": {
                    "quiet": true
                }
            }
        }
```

I've updated executor but it have started to complain about more and more scheme differences.

**Comment by DzmVasileusky** [comment]
I had to switch to the branch without storybook and init it again with nx then copy the initial config.
May be helpful to someone

Old
```
        "storybook": {
            "executor": "@nrwl/storybook:storybook",
            "options": {
                "uiFramework": "@storybook/angular",
                "port": 4400,
                "config": {
                    "configFolder": "libs/ui-kit/.storybook"
                },
                "projectBuildConfig": "ui-kit:build-storybook"
            },
            "configurations": {
                "ci": {
                    "quiet": true
                }
            }
        },
        "build-storybook": {
            "executor": "@nrwl/storybook:build",
            "outputs": ["{options.outputPath}"],
            "options": {
                "uiFramework": "@storybook/angular",
                "outputPath": "dist/storybook/ui-kit",
                "config": {
                    "configFolder": "libs/ui-kit/.storybook"
                },
                "projectBuildConfig": "ui-kit:build-storybook",
                "stylePreprocessorOptions": {
                    "includePaths": ["libs/ui-kit/src/styles"]
                },
                "styles": [
                    "libs/shared/content/fonts/proxima-nova.css",
                    "libs/ui-kit/src/styles/global.scss",
                    "libs/ui-kit/.storybook/docs-typography.scss"
                ]
            },
            "configurations": {
                "ci": {
                    "quiet": true
                }
            }
        }
```

New
```
        "storybook": {
            "executor": "@storybook/angular:start-storybook",
            "options": {
                "port": 4400,
                "configDir": "libs/ui-kit/.storybook",
                "browserTarget": "ui-kit:build-storybook",
                "compodoc": false
            },
            "configurations": {
                "ci": {
                    "quiet": true
                }
            }
        },
        "build-storybook": {
            "executor": "@storybook/angular:build-storybook",
            "outputs": ["{options.outputPath}"],
            "options": {
                "outputDir": "dist/storybook/ui-kit",
                "configDir": "libs/ui-kit/.storybook",
                "browserTarget": "ui-kit:build-storybook",
                "compodoc": false
            },
            "configurations": {
                "ci": {
                    "quiet": true
                }
            }
        }
```

**Comment by mandarini** [comment]
Hi @DzmVasileusky ! Thanks for letting me know. I will look into this. Can you give me a reproduction repository? I mean, can you create a minimum reproduction, so that I can test this locally? It will help me debug!

**Comment by mandarini** [comment]
PR for this is on the way, people!!! :D :D
