### ISSUE TITLE
FOUC with next + styled-jsx setup after creating a lib

### ISSUE THREAD

**Issue by austinjlaverty** [nrwl/nx#8497]
## Current Behavior

I have a `nx` generated `next` app with which I'm using `styled-jsx` to provide css.  After adding an empty library with which to provide some shared UI components, when building and running a `nx + next + styled-jsx` setup in production  mode a visible flash of unstyled content will occur, as well as completely missing styles when javascript is disabled. CSS provided with `styled-jsx` works with a freshly generated `nx + next + styled-jsx` app, but the feature support breaks as soon as you begin to add to `libs`

## Expected Behavior

`next + styled-jsx` support ssr by generating styles for the first paint, therefore one would expect the same when building and serving from an generated nx environment. The correct results should be visible styles when javascript is disabled, and no flash of unstyled content when javascript is enabled, specifically after adding a new UI library to the project.

### 1. Generate a new next app
Let's get started by generating a new `next` application with `nx`:

```bash
> npx create-nx-workspace example

✔ What to create in the new workspace · next
✔ Application name                    · test
✔ Default stylesheet format           · styled-jsx
✔ Use Nx Cloud? (It's free and doesn't require registration.) · No
```

### 2. Configure styling to use `styled-jsx` only
We want to style our app using `styled-jsx` exclusively, so lets cleanup the generated output by removing the `styles.css` file and it's associated `import`

Remove the file:
```
rm apps/test/pages/styles.css
```
Remove the import from `apps/test/pages/_app.tsx`

```typescript
import { AppProps } from 'next/app';
import Head from 'next/head';
// import './styles.css'; <--- Remove this line
```
### 3. Add some `styled-jsx` to the index
`nx` generated a index file with a `<style jsx>` tag for us to use. Open  `apps/test/pages/index.tsx` and add some css to the`<style jsx>` tag:

```ts
// apps/test/pages/index.tsx

return (
  <div>
    <style jsx>
        .wrapper { // << add this little bit of css to the generated .wrapper
          background: red;
        }
     </style>

     <div className="wrapper">
         // ... the rest of the nx generated index html
     </div>
  </div>
);
```

### 4. Test (spoiler: it works! ...until the next step)

Go ahead and test by building and serving `test` in production mode:

```bash
nx build test && nx serve test --prod
```

At this point, you'll notice that all `styled-jsx` css is working correctly and as expected, regardless of whether javascript is enabled or disabled.

Left is with javascript enabled, while right has javascript disabled.

![nx__next+styled-jsx--working](https://user-images.githubusercontent.com/1315661/149207240-ff7ed767-c88c-40fa-b364-80f59788df3c.png)

However, once we attempt to scale our app the tiniest bit, this working functionality will become lost...

### 5. Generate an empty lib

Now generate an empty UI library:

```bash
nx g lib shared/ui
✔ Which stylesheet format would you like to use? · styled-jsx
CREATE libs/shared/ui/project.json
UPDATE workspace.json
CREATE libs/shared/ui/.eslintrc.json
CREATE libs/shared/ui/.babelrc
CREATE libs/shared/ui/README.md
CREATE libs/shared/ui/src/index.ts
CREATE libs/shared/ui/tsconfig.json
CREATE libs/shared/ui/tsconfig.lib.json
UPDATE tsconfig.base.json
CREATE libs/shared/ui/jest.config.js
CREATE libs/shared/ui/tsconfig.spec.json
CREATE libs/shared/ui/src/lib/shared-ui.spec.tsx
CREATE libs/shared/ui/src/lib/shared-ui.tsx
```

### 6. Test (spoiler: its broken)

Then build and serve the application in production mode:

```bash
nx build test && nx serve test --prod
```
![nx__next+styled-jsx--broken](https://user-images.githubusercontent.com/1315661/149207289-aed1d723-c378-4cbe-8a35-6c1521997ae2.png)
As you can see in the screenshot, the red background is visible when javascript is enabled, but styles are missing when javascript is disabled.

In the javascript enabled scenario, we can clearly see the flash of unstyled content when measuring performance:

![nx__next+styled-jsx--fouc](https://user-images.githubusercontent.com/1315661/149207338-1f494fa2-ea63-49b5-a229-724c48de6d79.png)

### Failure Logs

This issue involves silently failing functionality. No errors or logs are recorded/generated.

### Environment

```bash
  Node : 16.13.0
  OS   : linux x64
  npm  : 8.1.0

  nx : 13.4.4
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.4
  @nrwl/cypress : 13.4.4
  @nrwl/devkit : 13.4.4
  @nrwl/eslint-plugin-nx : 13.4.4
  @nrwl/express : undefined
  @nrwl/jest : 13.4.4
  @nrwl/linter : 13.4.4
  @nrwl/nest : undefined
  @nrwl/next : 13.4.4
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.4.4
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.4
  @nrwl/web : 13.4.4
  @nrwl/workspace : 13.4.4
  @nrwl/storybook : 13.4.4
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
```

**Comment by jaysoo** [comment]
It looks like a version mismatch between what Next.js expects and what Nx installs.

You can try removing it from  the workspace, and use whatever comes with Next.js.

https://github.com/vercel/styled-jsx/issues/792#issuecomment-1097754759

Or install the latest Next.js-supported version (5.0.1). We'll need to keep our version in sync with Next.js's moving forward.
