### ISSUE TITLE
@nrwl/js libraryGenerator function fails (but cli generator doesn't)

### ISSUE THREAD

**Issue by yharaskrik** [nrwl/nx#8500]
## Current Behavior

When calling the `@nrwl/js:lib` generator from a workspace executor like so:

```
await libraryGenerator(tree, {
        name: options.name,
        buildable: true,
        testEnvironment: 'node',
        tags: ['platform:any', `type:${options.type}`, `scope:${options.scope}`].join(','),
        linter: Linter.EsLint,
        unitTestRunner: options.unitTestRunner,
        strict: true,
        compiler: 'swc',
    });
```

We get 

```
Cannot set property 'lint' of undefined
```

If I set `linter` to `none` and then rerun instead we get 
```
Cannot read property 'test' of undefined
```

This workspace executor was previously calling the exact same thing just with `@nrwl/node:lib` instead and it has been working.

## Expected Behavior

Should be able to call the `libraryGenerator` function from within a workspace executor

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

```
>  NX  Report complete - copy this into the issue template

  Node : 12.22.7
  OS   : darwin x64
  yarn : 1.22.17
  
  nx : 13.4.4
  @nrwl/angular : 13.4.4
  @nrwl/cli : 13.4.4
  @nrwl/cypress : 13.4.4
  @nrwl/devkit : 13.4.4
  @nrwl/eslint-plugin-nx : 13.4.4
  @nrwl/express : 13.4.4
  @nrwl/jest : 13.4.4
  @nrwl/linter : 13.4.4
  @nrwl/nest : 13.4.4
  @nrwl/next : undefined
  @nrwl/node : 13.4.4
  @nrwl/nx-cloud : 13.0.2
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.4
  @nrwl/web : 13.4.4
  @nrwl/workspace : 13.4.4
  @nrwl/storybook : 13.4.4
  @nrwl/gatsby : undefined
  typescript : 4.5.4
  rxjs : 7.4.0
```

**Comment by Stonepaw** [comment]
Found the issue and a work around. If the `config` option in the generator is not `project` or `workspace` then the projectConfiguration targets are not saved into the project.json so the following addLint and addJest tasks fail. (See packages/js/src/utils/project-generator.ts addProject)

We will change our generator to have set `config: 'project'` when the library generator is called.
