### ISSUE TITLE
Unable to ignore files, causing NX to take 2 minutes to run every command

### ISSUE THREAD

**Issue by gioragutt** [nrwl/nx#8503]
## Current Behavior

My teammate had a problem running anything with NX. Every command would take about 2 minutes before executing.
After a couple of minutes of `console.log` debugging the nx cli in `node_modules`, we found out the thing that took the most time was building the dependency graph.

After some troubleshooting, it ended up taking a lot of time due to him having some huge (<= 2.4GB) json/csv files inside a lib.
We tried using `.nxignore` but to no avail. We ended up moving the files away from inside the repository.

## Expected Behavior

I'd expect to have the ability to `.nxignore` files which I don't want NX to take into consideration.
Moreover, I'd expect to have the ability to have nested `.nxignore` files, much like `.gitignore` files.

I'm not sure how this would work with `nx affected` commands, but that can be discussed in an RFC or something.

## Steps to Reproduce

```bash
npx create-nx-workspace my-workspace --preset=empty
cd my-workspace
yarn add -D @nrwl/node
yarn nx generate @nrwl/node:library repro-lib --buildable
cd libs/repro-lib
mkdir tools
cd tools
mkfile -n 3g big-file-1.json
mkfile -n 3g big-file-2.json
mkfile -n 3g big-file-3.json
mkfile -n 3g big-file-4.csv
yarn nx build repro-lib
```

### Environment

```
 Node : 17.3.0
  OS   : darwin x64
  yarn : 1.22.17
  nx : 13.3.1
  @nrwl/angular : undefined
  @nrwl/cli : 13.3.1
  @nrwl/cypress : undefined
  @nrwl/devkit : 13.3.1
  @nrwl/eslint-plugin-nx : 13.3.1
  @nrwl/express : undefined
  @nrwl/jest : 13.3.1
  @nrwl/linter : 13.3.1
  @nrwl/nest : 13.3.1
  @nrwl/next : undefined
  @nrwl/node : 13.3.1
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.1
  @nrwl/web : undefined
  @nrwl/workspace : 13.3.1
  @nrwl/storybook : undefined
  @nrwl/gatsby : undefined
  typescript : 4.3.5
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @nrwl/js: 13.3.1
         @nrwl/nx-plugin: 13.3.1
         @trumbitta/nx-plugin-openapi: 1.10.0
```

**Comment by FrozenPandaz** [comment]
Could you provide a repo that we could pull to reproduce and debug the issue please?
