### ISSUE TITLE
Cache restoration does not work in 13.4.4

### ISSUE THREAD

**Issue by skrtheboss** [nrwl/nx#8504]
## Current Behavior
Nx omits library name in the cache storing process. I have added a log message in the [Cache's put](https://github.com/nrwl/nx/blob/master/packages/workspace/src/tasks-runner/cache.ts#L113)  function to log the `src` and `directory` variables, this is what i got:

NX 13.4.3
`C:\some-package\dist\libs\package" C:\some-package\node_modules\.cache\nx\2e8c0a3faa9be7f2167abe97bc5974e0f98a0b1191270abe471b856348f76441\outputs\di
st\libs\package"`

NX 13.4.4:
` "C:\some-package\dist\libs\package" "C:\some-package\node_modules\.cache\nx\b695927ba87de71339259c5092702366bf19ed0eb6f999859d9c66476d026ed1\outputs\dist\libs"`

As a reulst i always get the message `[existing outputs match the cache, left as is]` even if i delete my whole dist folder.

I think this bug has been introduced with [this](https://github.com/nrwl/nx/commit/16e9f58f765f81e09239df15755b887a43b1f505#diff-916c87b54c219ec49ee2383ad896459b8264a73f7d907b82f4bd7357cd18f0e4R106-R110) change.

## Expected Behavior
Should store cache in the correct format.

## Steps to Reproduce
See above.

**Comment by FrozenPandaz** [comment]
Could you provide a repo that we could pull to reproduce and debug the issue please?

**Comment by Allistairec** [comment]
+1 for this fix, confirmed on my side that cache restoration is indeed broken from 13.4.4 onwards
