### ISSUE TITLE
run-many: Allow use of wildcards

### ISSUE THREAD

**Issue by jbjhjm** [nrwl/nx#8508]
## Description

Allow use of * wildcard in run-many command, like `nx run-many --target="lint" --projects="core-*"`

Old issue from 2020 was auto-closed without any solution.
I think todays it still is a useful and relatively easy to implement addition.
https://github.com/nrwl/nx/issues/3736 

## Motivation

For all larger monorepos it becomes an increasingly tedious task to run testing/linting processes on multiple packages.
Providing packages follow a wellthought naming convention, run-many could save us lots of writing by accepting a wildcard operator.

Examples:
`nx run-many --target=lint --projects="myapp-frontend-*"`
`nx run-many --target=lint --projects="libs-ui-*"`
`nx run-many --target=lint --projects="*database*"`

## Suggested Implementation

When trying to find the package IDs matching the input data, a check for * operator must happen, if found, package names in workspace/angular.json must be matched against the input wildcard. After matching process, the run-many command can continue working as usual.

## Alternate Implementations

Thinking further, the matching process could also/additionally work by matching nx tags assigned to the packages.

**Comment by linbudu599** [comment]
I will take a look at this

**Comment by jbjhjm** [comment]
Damn, you are a hero @linbudu599 ! 🎉

**Comment by sauldeleon** [comment]
this is awesome! cant wait for this! Thanks!

**Comment by alex-vladut** [comment]
That is a great feature, I would like to have this option. Thanks for adding it. I noticed there is a PR open for some time, does anyone know if there is any progress being made to get this feature integrated? Thanks!

**Comment by linbudu599** [comment]
> That is a great feature, I would like to have this option. Thanks for adding it. I noticed there is a PR open for some time, does anyone know if there is any progress being made to get this feature integrated? Thanks!

I'm the original initiator of the PR, sorry for putting it on hold after I ran into some problems with the testing after the feature was implemented, I'll start refining the PR this week and ask for help from official members and get it in the official version as soon as possible.

**Comment by belgattitude** [comment]
Would be great. Not sure I would re-use the `--project` though.

In the wild:

```
# yarn 3+ https://yarnpkg.com/cli/workspaces/foreach#options
# Works with --include / --exclude
yarn workspaces foreach -tv --include '@belgattitude/*' --since=origin/main --recursive run lint

# turbo: https://turborepo.org/docs/core-concepts/filtering
# Works with --filter and negations
turbo run lint --filter=./apps/* --filter=!admin

# pnpm https://pnpm.io/filtering
# works with --filter
pnpm --filter "@babel/*" lint

# lerna 5
# works with --scope / --exclude
lerna run --scope package-1 --scope *-2 lint

```

I find the --filter with negation quite easy to read

**Comment by albertilagan** [comment]
@FrozenPandaz
