### ISSUE TITLE
'Unable to write a reference...' error when using run-commands builder

### ISSUE THREAD

**Issue by parky128** [nrwl/nx#8534]
### Discussed in https://github.com/nrwl/nx/discussions/8533

<div type='discussions-op-text'>

<sup>Originally posted by **parky128** January 14, 2022</sup>
I am getting a peculiar error with building a lib that has a dependency on another lib in an Nx workspace. I am using run-commands as there are some other tasks that need to be invoked after the initial library build.

I am seeing 'Unable to write a reference...' type error message, e.g.

    Unable to write a reference to SomethingCoolComponent in /Users/robert.parker/Documents/Github/nx-playground/libs/common-components/src/lib/components/something-cool/something-cool.component.ts from /Users/robert.parker/Documents/Github/nx-playground/libs/common-components/src/lib/common-components.module.ts
    ERROR: Something went wrong in @nrwl/run-commands - Command failed: nx base-build shiny-components

I have a replicable repo where I can showcase here https://github.com/parky128/nx-playground

After installing deps, just run `ng run shiny-components:build` and see the error.

If I don't use the `run-commands` builder, and just run the `base-build` task on the same lib it builds fine, so I am blaming run-commands, does anyone have any idea what could be the actual problem here?</div>

**Comment by alexzuza** [comment]
https://stackoverflow.com/questions/70078697/nx-unable-to-write-a-reference-error-when-using-run-commands-builder/70732735#answer-70732735

**Comment by parky128** [comment]
Thanks @alexzuza for your input, I have looked over your suggestions, which has help me resolve the problem in my real world project.
