### ISSUE TITLE
MiniCssExtractPlugin is not a constructor

### ISSUE THREAD

**Issue by xelaos** [nrwl/nx#8540]
## Current Behavior
`nx run frontend:serve`
leads to 

```
MiniCssExtractPlugin is not a constructor

———————————————————————————————————————————————

>  NX   ERROR  Running target "frontend:serve" failed

  Failed tasks:
  
  - frontend:serve

```

## Expected Behavior
serving react application

## Steps to Reproduce
`npx create-nx-workspace test`
select react template
select less as a stylesheet format
`npm run start`

tested this on multiple devices

**Comment by FrozenPandaz** [comment]
I've resolved the issue with `v13.4.5`. :tada:
