### ISSUE TITLE
`package.json` in build result of buildable library using `@nrwl/workspace:library` contains `main` property refrencing module ES files.

### ISSUE THREAD

**Issue by AbdUlHamedMaree** [nrwl/nx#8558]
I'm using NX to organize and publish a set of libraries, I've created a buildable library by the following command `nx generate @nrwl/workspace:library --buildable` 

## Current Behavior

The library contains module ES files, after building the library, the `package.json` in the build result of the library contains `main` property referencing on the module ES files, so when I try to publish it or use its build it will break.

## Expected Behavior

`package.json` in the build result should have `module` property instead of `main` property.

## Steps to Reproduce

- generate the lib using the following command `nx generate @nrwl/workspace:library --name=my-lib --buildable`.
- build the lib using the following command `nx build my-lib`.
- look inside `dist/libs/my-lib/package.json` it will have `main` property referencing on file have `export` keyword.

### Failure Logs

when using this build or publishing it to `npm` and use it it won't work because any bundler will recognize it as `comonjs` file but it's actually a `module` file.

### Environment
```
Node : 16.13.2
OS   : win32 x64
yarn : 1.22.5

nx : 13.2.2
@nrwl/angular : undefined
@nrwl/cli : 13.2.2
@nrwl/cypress : 13.2.2
@nrwl/devkit : 13.2.2
@nrwl/eslint-plugin-nx : 13.2.2
@nrwl/express : undefined
@nrwl/jest : 13.2.2
@nrwl/linter : 13.2.2
@nrwl/nest : undefined
@nrwl/next : undefined
@nrwl/node : undefined
@nrwl/nx-cloud : 12.5.4
@nrwl/react : 13.2.2
@nrwl/react-native : undefined
@nrwl/schematics : undefined
@nrwl/tao : 13.2.2
@nrwl/web : 13.2.2
@nrwl/workspace : 13.2.2
@nrwl/storybook : 13.2.2
@nrwl/gatsby : undefined
typescript : 4.4.4
rxjs : 6.6.7
---------------------------------------
Community plugins:  
```

**Comment by vsavkin** [comment]
This applies to nrwl/js as well.
