### ISSUE TITLE
Document new external generators feature of create-nx-workspace

### ISSUE THREAD

**Issue by luxaritas** [nrwl/nx#8559]
In #8084, new functionality was introduced allowing for create-nx-workspace to be passed an npm package containing a generator named preset which can be used to create the workspace. This capability is currently not shown in either the CLI itself (ie, with the `--help` flag) or in the documentation proper (either from a preset user's side or a preset creator's side). If I hadn't checked the release notes and the linked PR, I would've completely missed this. :)

**Comment by linbudu599** [comment]
I am glad to provide documentation enhancement and preset examples 😄
