### ISSUE TITLE
Migration to 13.4.4 fails if using a custom jest.preset.ts that removes transforms from jest.config.js

### ISSUE THREAD

**Issue by kpaxton** [nrwl/nx#8566]
## Current Behavior
When I try to update to 13.4.5 from 13.4.3 it tries to run a single migration to convert transforms to use `babel-jest`.
I get this error: 
```
>  NX  Running migrations from './migrations.json'

Running migration add-missing-root-babel-config
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at /home/kcpaxto/Projects/uee-ui/node_modules/@nrwl/jest/src/migrations/update-13-4-4/add-missing-root-babel-config.js:21:42
    at forEachExecutorOptions (/home/kcpaxto/Projects/uee-ui/node_modules/@nrwl/workspace/src/utilities/executor-options-utils.js:23:17)
    at checkIfProjectNeedsUpdate (/home/kcpaxto/Projects/uee-ui/node_modules/@nrwl/jest/src/migrations/update-13-4-4/add-missing-root-babel-config.js:14:57)
    at /home/kcpaxto/Projects/uee-ui/node_modules/@nrwl/jest/src/migrations/update-13-4-4/add-missing-root-babel-config.js:32:37
    at Generator.next (<anonymous>)
    at /home/kcpaxto/Projects/uee-ui/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/home/kcpaxto/Projects/uee-ui/node_modules/tslib/tslib.js:113:16)
    at update (/home/kcpaxto/Projects/uee-ui/node_modules/@nrwl/jest/src/migrations/update-13-4-4/add-missing-root-babel-config.js:31:34)
/home/kcpaxto/Projects/uee-ui/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /tmp/tmp-1746-AONKBi8NYiqM/node_modules/.bin/tao migrate --run-migrations=./migrations.json -v
    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at Object.handler (/home/kcpaxto/Projects/uee-ui/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:125:42)
    at Object.runCommand (/home/kcpaxto/Projects/uee-ui/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/home/kcpaxto/Projects/uee-ui/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/home/kcpaxto/Projects/uee-ui/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
    at initLocal (/home/kcpaxto/Projects/uee-ui/node_modules/@nrwl/cli/lib/init-local.js:27:79)
    at Object.<anonymous> (/home/kcpaxto/Projects/uee-ui/node_modules/@nrwl/cli/bin/nx.js:45:32)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1795,
  stdout: null,
  stderr: null
}
```

It seems that the migration script is not handling the case where `transforms` does not exist in the `jest.config.js` due to a custom preset extracting it. 

## Expected Behavior
Expect the migration to complete successfully even if the particular property it's looking for is not present. Or should check to see if a custom preset is used instead of the default and skip the migration.

## Steps to Reproduce

sample of one of my jest.config.js:
```
module.exports = {
  displayName: 'shared-ui-date-picker',
  preset: '../../../../tools/jest/angular-jest.preset.js',
  setupFilesAfterEnv: ['<rootDir>/src/test-setup.ts'],
  globals: {
    'ts-jest': {
      tsconfig: '<rootDir>/tsconfig.spec.json',
      stringifyContentPathRegex: '\\.(html|svg)$'
    }
  },
  coverageDirectory: '../../../../coverage/libs/shared/ui/date-picker',
  snapshotSerializers: [
    'jest-preset-angular/build/serializers/no-ng-attributes',
    'jest-preset-angular/build/serializers/ng-snapshot',
    'jest-preset-angular/build/serializers/html-comment'
  ]
};
```

my preset: 
```
const esModules = ['.*.mjs$', 'lodash-es'].join('|');
const rootPreset = require('../../jest.preset.js');

module.exports = {
  ...rootPreset,
  transform: {
    '^.+.(ts|mjs|js|html)$': 'jest-preset-angular',
    '^.+\\.js$': 'babel-jest'
  },
  transformIgnorePatterns: [`/node_modules/(?!${esModules})`],
  verbose: true
};
```

I believe the issue is here: https://github.com/nrwl/nx/blob/master/packages/jest/src/migrations/update-13-4-4/add-missing-root-babel-config.ts
line 36. It does not seem to check for the existence of the property on the config before trying to access it.

### Environment
Node : 14.18.2
  OS   : linux x64
  npm  : 7.24.2
  
  nx : 13.4.5
  @nrwl/angular : 13.4.5
  @nrwl/cli : 13.4.5
  @nrwl/cypress : 13.4.5
  @nrwl/devkit : 13.1.3
  @nrwl/eslint-plugin-nx : 13.4.5
  @nrwl/express : undefined
  @nrwl/jest : 13.4.5
  @nrwl/linter : 13.4.5
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.4.5
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.5
  @nrwl/web : undefined
  @nrwl/workspace : 13.4.5
  @nrwl/storybook : 13.4.5
  @nrwl/gatsby : undefined
  typescript : 4.5.4
  rxjs : 7.5.1
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.1.1
         @angular/cdk: 13.1.1
         @angular/common: 13.1.1
         @angular/compiler: 13.1.1
         @angular/core: 13.1.1
         @angular/forms: 13.1.1
         @angular/material: 13.1.1
         @angular/platform-browser: 13.1.1
         @angular/platform-browser-dynamic: 13.1.1
         @angular/router: 13.1.1
         @fortawesome/angular-fontawesome: 0.10.1
         @ngrx/component-store: 13.0.2
         @ngrx/effects: 13.0.2
         @ngrx/entity: 13.0.2
         @ngrx/router-store: 13.0.2
         @ngrx/store: 13.0.2
         @angular-builders/jest: 13.0.2
         @angular-devkit/build-angular: 13.1.2
         @angular-eslint/builder: 13.0.1
         @angular-eslint/schematics: 13.0.1
         @angular/cli: 13.1.2
         @angular/compiler-cli: 13.1.1
         @angular/language-service: 13.1.1
         @ngrx/schematics: 13.0.2
         @ngrx/store-devtools: 13.0.2
         @storybook/angular: 6.4.9
         @testing-library/angular: 11.0.2

**Comment by Serg-Mois** [comment]
I faced exactly the same issue.

**Comment by guesskingf** [comment]
same issue +1

**Comment by kpaxton** [comment]
simple workaround is to add an if statement around the `for` that loops the transforms in the `node_modules/@nrwl/jest/src/migrations/update-13-4-4/add-missing-root-babel-config.js` temporarily.
```
if(config.transform){
    for (const transformer of Object.values(config.transform)) {
            if ((typeof transformer === 'string' && transformer === 'babel-jest') ||
                (Array.isArray(transformer) && transformer[0] === 'babel-jest')) {
                shouldUpdate = true;
            }
        }
}
```
I'll submit a PR shortly for it so that it's there for the future.
