### ISSUE TITLE
Add TestCafe E2E project scaffolding 

### ISSUE THREAD

**Issue by xmlking** [nrwl/nx#857]
TestCafe is open source E2E testing frameworks that can run partially on node. 
would be nice if we have  `TestCafe e2e test runner` option. 

https://medium.com/yld-engineering-blog/evaluating-cypress-and-testcafe-for-end-to-end-testing-fcd0303d2103

**Comment by sforner405** [comment]
Any news on this one?
Will the change be integrated in a upcoming release?
Thanks a lot.

**Comment by alex-kachura** [comment]
+1 for TestCafe option for e2e testing

**Comment by mehrad-rafigh** [comment]
Seems like @thillmann is not actively working on his PR. I will take a look in the coming week and work on an integration of TestCafe.

**Comment by vsavkin** [comment]
Folks. We are unlikely to add support for TestCafe in the near future. If you want to put together an external package of builders and schematics for it, we are happy to help, and happy to help promote it.

**Comment by mzaicevs** [comment]
I believe this should be here: [A custom Angular builder for TestCafe](https://github.com/politie/angular-testcafe)

**Comment by alambertt** [comment]
Please any tutorial to integrate Testcafe with Nx?? Thks
