### ISSUE TITLE
Rollup plugin enhancement

### ISSUE THREAD

**Issue by linbudu599** [nrwl/nx#8575]
## Description

There is now room for a number of enhancements to the rollup plugin, including but not limited to：

- Support ESM in `rollupConfig`(#8459 )
- Further and more detailed documentation, such as schema-related descriptions, and in particular the function entry descriptions for the `rollupConfig` configuration export (`currentConfig` and `options`).
- Support `.ts` for `rollupConfig`, with corresponding typing support(`type RollupConfigFactory = (...) => ValidateRollupConfig`), for `.js` file we can also use JSDoc to provide typing tips from IDE(just as how snowpack does), like `/** @type {import("@nrwl/web").RollupConfigFactory } */`.
- Generator support, for example, use `nx g @nrwl/web:rollup exist-web-app --rollupConfig=rollup.config.ts` to add a section of target configuration using `@nrwl/web:rollup` as build executor.
- Incorrect build output (#8475 >>> #8526 )
- ... more to be discovered

**Comment by vadistic** [comment]
I'm using fully specified ESM import paths. `@nrwl/web` can handle those with babel, but not with swc.

It seem to be supported by swc/spack - but not configured for rollups' commonjs & node-resolve plugins. Idk.

https://github.com/swc-project/swc/issues/3043

```json
    "build": {
      "executor": "@nrwl/web:rollup",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/libs/my-lib",
        "tsConfig": "libs/my-lib/tsconfig.lib.json",
        "project": "libs/my-lib/package.json",
        "entryFile": "libs/my-lib/src/index.ts",
        "external": ["react/jsx-runtime"],
        "rollupConfig": "@nrwl/react/plugins/bundle-rollup",
        "compiler": "swc"
      }
    },
```

```ts
// index.ts
import { abort } from './abort.js';

// two.ts
export function two() {};
```

```txt
[!] Error: unfinished hook action(s) on exit:
(commonjs) resolveId "./two.js" "/home/vadistic/work/my-project/libs/my-lib/src/index.ts"
(node-resolve) resolveId "./two.js" "/home/vadistic/work/my-project/libs/my-lib/src/index.ts"
```

**Comment by perjerz** [comment]
There is issue when you try import other libray files to app that use @nrwl/web:rollup as executor. Ex. src/main.ts
```
// src/main.ts
import '../../../libs/shared-assets-backend/generator/main';
```

The error will be shown as 
```
Error during bundle: /Users/xxx/reactor-room/apps/bundler-js/src/main.ts(2,8): semantic error TS6059: File '/Users/xxx/reactor-room/libs/shared-assets-backend/generator/main.ts' is not under 'rootDir' '/Users/xxx/reactor-room/apps/bundler-js/src'. 'rootDir' is expected to contain all source files.

```

The rootDir is set by entryFile folder.

```

 "projectType": "application",
  "root": "apps/bundler-js",
  "sourceRoot": "apps/bundler-js/src",
  "tags": [],
  "targets": {
    "build": {
      "executor": "@nrwl/web:rollup",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "project": "apps/bundler-js/package.json",
        "entryFile": "apps/bundler-js/src/main.ts", // <-------------- entry Folder = apps/bundler-js/src
        "tsConfig": "apps/bundler-js/tsconfig.gulp.json",
        "outputPath": "dist/apps/bundler-js",
        "format": ["esm", "cjs"],
        "deleteOutputPath": true,
```

You can see the source code below.

https://github.com/nrwl/nx/blob/a622ee5f0851e652ee4b6284e4e4b001275a158d/packages/web/src/executors/rollup/lib/normalize.ts#L20

To fix this problem, the entryRoot has to be root folder by default.

The workaround is to move main.ts to root project. and configure project.json and fix entryFile as below.

```
"options": {
        "project": "apps/bundler-js/package.json",
        "entryFile": "main.ts",
```
