### ISSUE TITLE
nx run test - fails for unsupported jest args when running karma projects

### ISSUE THREAD

**Issue by gkamperis** [nrwl/nx#8587]
## Current Behavior
`nx affected:test --runInBand`

fails for repos with mixed karma and jest projects.

The karma projects fail with
`'runInBand' is not found in schema`

If I specify a Karma option like 
`nx affected:test --browsers=Chrome`

jest tests run ok ignoring the unsupported arg

## Expected Behavior
I would expect runners to report/ignore unsupported args and not fail the run

## Steps to Reproduce
* create a mixed repo with jest + karma
* nx affected:test --runInBand

### Environment
win 10
Nx 13.4.3

**Comment by vsavkin** [comment]
Thank you for submitting the issue!

We cannot know what flags each executor supports (some of them are defined in the schema, but not all of them), so unfortunately this cannot be fixed. If we maintained the Karma executor, we could have added runInBand there, but we dont'. The Angular team does.

You can either:
*  define a configuration called "runInBand" that would do nothing for Karma projects (nx affected --target=test --configuration=runInBand)
* name karma targets "karma-test" and run two command nx affected --target=test and nx affected --target=karma-test
* wrap the karma executor to ignore runInBand

Sorry again, but this cannot be fixed on our side, so I'll close the issue.

**Comment by gkamperis** [comment]
@vsavkin thanks for the reply but `--browsers` is not supported by jest either and it does not result in error. 

how is this ignored for the jest schema/runner?

is jest more lenient with invalid cli args?
