### ISSUE TITLE
Storybook - using forwardRef without React namespace introduces all element props

### ISSUE THREAD

**Issue by danr-za** [nrwl/nx#8591]
## Current Behavior
Using `forwardRef` without `React` import introduces all available element props.

With React import:

```ts
import React from 'react'

interface ButtonProps { 
  primary: boolean
}

export const Button = React.forwardRef<HTMLButtonElement,ButtonProps>((props,ref) => {
  const {children, primary} = props;
  return <button ref={ref} className={primary ? 'primary' : 'secondary'}>{children}</button>
})
```

Controls in Button story: **2**

Without React import:

```ts
import { forwardRef } from 'react'

interface ButtonProps { 
  primary: boolean
}

export const Button = forwardRef<HTMLButtonElement,ButtonProps>((props,ref) => {
  const {children, primary} = props;
  return <button ref={ref} className={primary ? 'primary' : 'secondary'}>{children}</button>
})
```

Controls in Button story: **256**

Story **.mdx file**:
```ts
import { Button } from './Button'

<Meta
  title="Button"
  component={Button} />

<Canvas>
  <Story>
      {(args) => <Button {...args} />}
  </Story>
</Canvas>
```

## Expected Behavior

Should not affect controls and props in any way.

## Steps to Reproduce
* Create a repo with React app
* Add Storybook configuration
* Add a component like the Button above
* First create it with `React.forwardRef` - inspect the number of controls
* Then remove React import, import `forwardRef`  instead - inspect the number of controls

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by mandarini** [comment]
Hello @danr-za ! Thanks for filing this issue. Can you please post here a reproduction repository? It would very helpful for me, so that I can debug your issue more easily!

**Comment by danr-za** [comment]
Sure thing, will do.

**Comment by danr-za** [comment]
@mandarini good news - cannot reproduce it in latest versions.
Closing this. Thanks for checking in!
