### ISSUE TITLE
Storybook - does not support swc compiler

### ISSUE THREAD

**Issue by danr-za** [nrwl/nx#8592]
## Current Behavior
The latest Nx versions introduced the swc compiler as an option.
Currently, adding the `"compiler": "swc"` to the `project.json` file under `storybook` configuration fails because `babel` remains in webpack loaders.

## Expected Behavior
Storybook should support swc compiler

## Steps to Reproduce
* Create a React app
* Add Storybook configuration
* Add `"compiler": "swc"` under the project's `storybook` configuration -> `options`
* Run storybook

**Comment by gperdomor** [comment]
Any update about this issue? :(

**Comment by fllprbt** [comment]
Hmm, I just tried it and I might be facing a diferent issue but I am not sure:

`Error: Cannot find module 'swc-loader'`

```
    "@nrwl/cli": "13.7.3",
    "@nrwl/react": "13.7.3",
    "@nrwl/storybook": "13.8.0",
```

**Comment by kirill-konshin** [comment]
Storybook does not support SWC, as far as I know. It supports ESBuild via [Vite Builder](https://storybook.js.org/blog/storybook-for-vite) or [Turbo Build Addon](https://storybook.js.org/addons/storybook-addon-turbo-build). I can confirm that TurboBuild works... 

But for SWC I haven't seen anything for the manager itself (outside the stories iframe), only for stories (inside the iframe).

**Comment by david-morris** [comment]
@kirill-konshin the manager builds in just a few seconds to me.  Could you link more about getting the stories built with SWC?

**Comment by danr-za** [comment]
Ye, its mainly for stories.
It will work btw if you provide `"compiler": "swc"` in your options but it will still preserve the babel one, resulting in build errors.

That's the issue.

**Comment by just-mitch** [comment]
I seem to have gotten this working by
1. removing the "compiler": "swc" from the project.json
2. `yarn add swc-loader`
3. Adding the following to (the project specific) .storybook/main.js as suggested [here](https://github.com/swc-project/swc-loader#usage) 
```
// add your own webpack tweaks if needed

    return {
      ...config,
      module: {
        rules: [
          {
            test: /\.[tj]sx?$/,
            exclude: /(node_modules|bower_components)/,
            use: {
              // Use `.swcrc` to configure swc
              loader: 'swc-loader',
            },
          },
        ],
      },
    }
```

**Comment by fllprbt** [comment]
> I seem to have gotten this working by
> 
> 1. removing the "compiler": "swc" from the project.json
> 2. `yarn add swc-loader`
> 3. Adding the following to (the project specific) .storybook/main.js as suggested [here](https://github.com/swc-project/swc-loader#usage)
> 
> ```js
> // add your own webpack tweaks if needed
>     return {
>       ...config,
>       module: {
>         ...config.module,
>         rules: [
>           ...config.module.rules,
>           {
>             test: /\.(tsx?)$/,
>             use: {
>               // Use `.swcrc` to configure swc
>               loader: 'swc-loader',
>               options: {
>                 parseMap: true,
>               },
>             },
>           },
>         ],
>       },
>     }
> ```
> 
> 4. Using the following for my `.swcrc` within the library
> 
> ```json
> {
>   "jsc": {
>     "target": "es2016",
>     "parser": {
>       "syntax": "typescript",
>       "decorators": true,
>       "dynamicImport": true,
>       "tsx": true
>     },
>     "transform": {
>       "decoratorMetadata": true,
>       "legacyDecorator": true
>     },
>     "keepClassNames": true,
>     "externalHelpers": true,
>     "loose": true
>   },
>   "module": {
>     "type": "es6",
>     "strict": false,
>     "strictMode": true,
>     "lazy": false,
>     "noInterop": false
>   }
> }
> ```

Removed my top-level babel config and pushed mine last and it would still pick babel. Putting it as first rule makes it work nice!

**Comment by ild0tt0re** [comment]
Finally the storybook addon to swap babel loader with swc.
https://storybook.js.org/addons/storybook-addon-swc

@vsavkin please add it as default when bootstrap a project with the swc compiler option selected

**Comment by danr-za** [comment]
@mandarini I assume that this addon can be directly used after your PR of using the native executor? (according to the project's configuration of course)

**Comment by mandarini** [comment]
Hi all!! @danr-za I expect that yes, when that PR is ready to be merged, for Angular, it should allow for this to happen.

@ild0tt0re we are still prioritising bugs, at the moment. If you want to give this a shot, please do. Otherwise, please be patient, and we'll get to this eventually! Thank you for understanding!

**Comment by mandarini** [comment]
Do you think we can close this issue now?

**Comment by david-morris** [comment]
I'd like to try out that addon @mandarini posted next week, I'll try to report back if I get to it.

**Comment by danr-za** [comment]
@mandarini should the storybook support `"compiler": "swc"` configuration like apps/libs? If so, that still doesn't seem to work

**Comment by david-morris** [comment]
I installed `storybook-addon-swc` and storybook is still making gzips in the babel subfolder of the cache directory.

**Comment by mandarini** [comment]
I'm adding all these things into a generator. But it should work as is.

If you follow [these steps here](https://storybook.js.org/addons/storybook-addon-swc), it works.

We could add the `"compiler": "swc"` in the Storybook target configuration for non-angular projects, if you think it will be valuable. I was thinking of just reading it from the `build` target if it exists. Wdyt @danr-za ?

**Comment by danr-za** [comment]
Hey @mandarini 
I was assuming that an additional plugin library won't be necessary because nx supports swc OOTB in build targets of non-angular apps.
So maybe its worth preserving the behavior all for Storybook configuration, as IIRC there's a shared webpack config.
Wdyt?

**Comment by mandarini** [comment]
Actually, that last part I said about adding it to the `storybook` target, the `compiler` option, it does not really make sense. I was not thinking clearly when I wrote it 😅.

What we *can* do, is add a `compiler` option to the `storybook-configuration` generator. But I think this will come at a later point, as an enhancement. 

After my PR is merged, all glitches will be out, in regards to the generators and Next.js 12. `swc` is supported, in the sense that you can set it up [like this](https://storybook.js.org/addons/storybook-addon-swc) retrospectively (in already existing projects), or opt in manually in new projects that don't use `next.js` OR `swc` as a compiler in their `build` target. 

You can read the notes on [my PR](https://github.com/nrwl/nx/pull/10828) and see when a project will be generated with the `swc` settings.
