### ISSUE TITLE
A library should use its own tsconfig to compile instead of the tsconfig of the app using it ?

### ISSUE THREAD

**Issue by Yohandah** [nrwl/nx#8596]
I am not sure this is a bug but I'm struggling making this work and it could be.

## Current Behavior

I have in an Nx repo :
* An Angular app 
* An Angular library (with --buildable option)

The tsconfig of the Angular app got this option `strict: true` and the tsconfig of the library `strict: false`.

My IDE detects this configuration and everything compiles in my IDE. But when I run npm run start (nx serve myApp), it fails trying to compile because the lib doesn't comply with strict: true, this gives errors like ` Argument of type 'undefined' is not assignable to parameter of type 'Theme'.`

## Expected Behavior
I should be able to use different compiling options between libs and projects

## Steps to Reproduce
* Create an Angular app with the ts compilerOption `strict: true`
* Create a --buildable Angular library with `strict: false`
* In the lib try to add  this line of code somewhere `test: string = undefined`
* run `npm run start` => it fails
* run `nx build myLib` => it works 

### Environment

```
 Node : 16.13.2
  OS   : win32 x64
  npm  : 8.1.2

  nx : 13.4.4
  @nrwl/angular : 13.4.4
  @nrwl/cli : 13.4.4
  @nrwl/cypress : 13.4.4
  @nrwl/devkit : 13.4.4
  @nrwl/eslint-plugin-nx : 13.4.4
  @nrwl/express : undefined
  @nrwl/jest : 13.4.4
  @nrwl/linter : 13.4.4
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.4
  @nrwl/web : undefined
  @nrwl/workspace : 13.4.4
  @nrwl/storybook : 13.4.4
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.1.2
         @angular/common: 13.1.2
         @angular/material: 13.1.2
         @angular/cdk: 13.1.2
         @angular/compiler: 13.1.2
         @angular/core: 13.1.2
         @angular/forms: 13.1.2
         @angular/platform-browser: 13.1.2
         @angular/platform-browser-dynamic: 13.1.2
         @angular/router: 13.1.2
         @ngrx/effects: 13.0.1
         @ngrx/entity: 13.0.1
         @ngrx/store: 13.0.1
         @angular-devkit/build-angular: 13.1.3
         @angular/cli: 13.1.3
         @angular/compiler-cli: 13.1.2
         @angular/language-service: 13.1.2
         @ngrx/store-devtools: 13.0.1
         eslint-plugin-ngrx: 2.0.3

```

**Comment by vsavkin** [comment]
Thank you for submitting the issue.

Unless you are building the libraries before running the serve (i.e., if the serve target compiles the library), everything will be compiled using the tsconfig of the app. The reason for that is that there is a single Angular Compiler instance being created.

If you build libraries first, and then serve your app against the built libraries, then each library will use its own tsconfig.

I'm going to close this. I know this is confusing, but this is how the Angular Compiler works.
