### ISSUE TITLE
Issue with migration of `jest.config.js

### ISSUE THREAD

**Issue by stefannikolei** [nrwl/nx#8604]
Another minor issue I run into was that in `jest.config.js
```json
transformIgnorePatterns: ['node_modules/(?!.*.mjs$)'],
```
was added multiple times (looks like once pro `--run-migrations`

This also caused further issues where I already had a custom `transformIgnorePatterns` entry.

_Originally posted by @zoechi in https://github.com/nrwl/nx/issues/7613#issuecomment-990977553_

**Comment by vsavkin** [comment]
> was added multiple times (looks like once pro --run-migrations

Do you run migrate multiple times? If that's the case, every migration in the migration.json file will execute again. You can remove the migrations you already ran.

**Comment by zoechi** [comment]
This seems to be fixed now.
