### ISSUE TITLE
The workspace.json file is out of sync

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [nrwl/nx#8609]
## Current Behavior
After upgrading from 13.4.4 to 13.4.6 after running yarn lint I receive 
The workspace.json file is out of sync

## Expected Behavior
It should work without problems

## Steps to Reproduce
Create nx with react in version 13.4.4  - react app named "ui"
then upgrade by using nx migrate latest
then execute yarn lint

### Failure Logs
yarn run v1.22.10
$ nx workspace-lint && nx lint

>  NX   ERROR  The workspace.json file is out of sync

  - Cannot find project 'ui-e2e' in 'apps/ui-e2e'
  - Cannot find project 'ui' in 'apps/ui'

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Environment
Windows 10  node 16.13.2

**Comment by FrozenPandaz** [comment]
Sorry @AdaskoTheBeAsT, I can't reproduce this issue. The `nx workspace-lint` command succeeds for me. Could you please provide a repo showing the issue after the migration?

**Comment by AdaskoTheBeAsT** [comment]
@FrozenPandaz 
I will try to regenerate our project from scratch using newest version and check differences

**Comment by AdaskoTheBeAsT** [comment]
@FrozenPandaz found it :)
please take a look at my repository https://github.com/AdaskoTheBeAsT/NetCoreTypewriterRecipes
and folder with frontend react app located at https://github.com/AdaskoTheBeAsT/NetCoreTypewriterRecipes/tree/master/src/ReactWebApiSample/ClientApp

before upgrade commit https://github.com/AdaskoTheBeAsT/NetCoreTypewriterRecipes/commit/af4f6c96a876976dab8b37587383cf1b8937eb0d

upgrade from 13.4.1 to 13.4.6 https://github.com/AdaskoTheBeAsT/NetCoreTypewriterRecipes/commit/31fb67ae552e6dc97a5db1f841c45f2b838d4c1e

and output

C:\github\NCTR\src\ReactWebApiSample\ClientApp>yarn lint
yarn run v1.22.17
$ nx workspace-lint && nx lint

>  NX   ERROR  The workspace.json file is out of sync

  - Cannot find project 'client-app-e2e' in 'apps/client-app-e2e'
  - Cannot find project 'client-app' in 'apps/client-app'

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by fetters5** [comment]
Same issue here  going from 13.4.1 to 13.4.6

**Comment by akryvasheyeu** [comment]
got the same after migration 13.4.4 -> 13.5.3

**Comment by AdaskoTheBeAsT** [comment]
hmm after migrating to 13.6.0 problem disappeared

**Comment by nehalvpatel** [comment]
Please keep this open!

**Comment by yardenxr** [comment]
same problem on version 13.7.1 while running "nx workspace-lint"

**Comment by nehalvpatel** [comment]
Please keep this open!

**Comment by jkolyer** [comment]
still happening.  individual project lint no problem but `nx workspace-lint` produces "cannot find project ..."

**Comment by IgorPropisnov** [comment]
I get this error after put some apps into the .nxignore.

**Comment by ascdi** [comment]
This is still happening in 2023.
Using nx 15.6.3 and angular.
Newly created libraries can not be linted:

```
 >  NX   The workspace.json file is out of sync 
 - Cannot find project example-test in libs/example/test 
```
