### ISSUE TITLE
Nx incorrectly removes file from output directory on subsequent runs despite `[existing outputs match the cache, left as is]`

### ISSUE THREAD

**Issue by chrisui** [nrwl/nx#8612]
## Current Behavior

I have a really odd issue where a particular file (notably, nested within an outputs[] directory and notably a significant binary file) is nuked when running the nx task that copied the file into the outputs directory in the first place. All other files remain. (File in question `libquery_engine-linux-arm64-openssl-1.0.x.so.node`). Most interestingly the nx output for the task that originally copies the file is `[existing outputs match the cache, left as is]`

Looking at [the docs](https://nx.dev/using-nx/caching) I see the following:

> Minimizes the IO by remembering what files are replayed where.

I'm not sure exactly how it is intending it does this but perhaps has an edge case in this logic?

Extra Info:

1. Also worth noting that my process which copies this binary also copies a few other sibling files (ie. `schema.prisma` and `index.js`) from the same source directory to the same output directory where these are both untouched by the cached nx run fine.
2. There are also some .zip's in the output directory (which contain the binary)
3. As we are packaging lambda functions, the output also contains several `package.json` (for each function) and `node_modules` (where we copy the binary within actually node_modules/.prisma/client)

## Expected Behavior

All files copied/created in my outputs[] directory/directories should be restored appropriately, including the binary in question.

## Steps to Reproduce

1. Create a project with a target that copies a [prisma binary](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#binarytargets-options) into a folder nested within outputs[]
2. Run the target, see the binary in outputs
3. Run the target again, see `[existing outputs match the cache, left as is]` but note the file is missing.

Ie. something along these lines

```
{
  "root": "lib",
  "sourceRoot": "lib/src",
  "projectType": "library",
  "targets": {
    "package": {
      "executor": "@nrwl/workspace:run-commands",
      "outputs": ["lib/dist/pkg"],
      "options": {
        "command": "cp /path/to/my/binary lib/dist/pkg/some/nested/binary"
      }
    }
  }
}
```

### Environment

```
% nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.18.1
  OS   : darwin arm64
  npm  : 8.1.3
  
  nx : 13.4.4
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.4
  @nrwl/cypress : undefined
  @nrwl/devkit : 13.4.4
  @nrwl/eslint-plugin-nx : undefined
  @nrwl/express : undefined
  @nrwl/jest : 13.4.4
  @nrwl/linter : 13.4.4
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : 13.0.2
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.4
  @nrwl/web : undefined
  @nrwl/workspace : 13.4.4
  @nrwl/storybook : undefined
  @nrwl/gatsby : undefined
  typescript : 4.5.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
```

**Comment by vsavkin** [comment]
Thank you for submitting the issue.

Could you provide a repo with a repro?
