### ISSUE TITLE
[Question] Is there a way to skip prompt and have nx work like before?

### ISSUE THREAD

**Issue by dereklin** [nrwl/nx#864]
I just upgraded to 7

I do:
```
ng g lib mytest -d
```
It prompts me for the location.

Is there a way to skip the prompt?

**Comment by skydever** [comment]
hi @dereklin 

like described [here](https://angular.io/cli/generate), are you looking for `--interactive=false` and/or `--defaults=true`?

**Comment by dereklin** [comment]
@skydever 
Thanks for the doc link.  The --interactive flag works.  The --defaults flag doesn't work -- I am guessing this is because ng g lib is not native to angular cli
