### ISSUE TITLE
@nrwl/web|@nrwl/workspace: Package gets all dependencies of its children

### ISSUE THREAD

**Issue by layershifter** [nrwl/nx#8640]
## Current Behavior

I have a workspace that has following structure:

```
               | --------- |
               | suite-pkg |
               | --------- |
               /           \
              /             \
             /               \
            /                 \
           /                   \
  | --------- |             | --------- |
  | core-pkg1 |             | core-pkg2 |
  | --------- |             | --------- |
```

- `core-pkg1` & `core-pkg2` have NPM dependencies (i.e. third party)
- `suite-pkg` only re-exports things from `core-pkg1` & `core-pkg2`

After build `suite-pkg` contains dependencies of its children in `package.json`:

![image](https://user-images.githubusercontent.com/14183168/150524111-9a757ec7-4f69-4aac-9a0a-f94c932f2d9c.png)

> note: changing `buildableProjectDepsInPackageJsonType` to `dependencies` does not change the behavior

This happens because `@nrwl/web` and its Rollup executor use `recursivelyCollectDependencies()` that actually does recursive collection of dependencies:

https://github.com/nrwl/nx/blob/1139c616e1b7e27c519e385a3982ac8b486dbb0f/packages/workspace/src/utilities/buildable-libs-utils.ts#L84-L96

## Expected Behavior

- `core-pkg1` & `core-pkg2` dependencies used in its sources
- `suite-pkg` has only `core-pkg1` & `core-pkg2` in dependencies (again, dependencies used in its sources)

## Proposal

I see following options:
- do not collect dependencies recursively for generation of `package.json` files
- make this behavior optional/configurable

## Steps to Reproduce

-  https://stackblitz.com/edit/github-j67jat or clone https://github.com/layershifter/nx-issue-recusrive-dependencies
- `npm install`
- `nx run suite-pkg:build`
-  check `dist/libs/suite-pkg/package.json`

### Environment

```
  Node : 16.13.1
  OS   : darwin arm64
  npm  : 8.1.2
  
  nx : 13.4.6
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.6
  @nrwl/cypress : 13.4.6
  @nrwl/devkit : 13.4.6
  @nrwl/eslint-plugin-nx : 13.4.6
  @nrwl/express : undefined
  @nrwl/jest : 13.4.6
  @nrwl/linter : 13.4.6
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.4.6
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.6
  @nrwl/web : 13.4.6
  @nrwl/workspace : 13.4.6
  @nrwl/storybook : 13.4.6
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
```

**Comment by jaysoo** [comment]
We'll address this. It never should  have been recursive since npm dependencies are only one level deep.

**Comment by egorderg** [comment]
I think it should ignore recursive when the dependency has the 'publishable' flag. Sometimes you need recursive dependencies when you are not publishing some of the libraries or want to collect everything in one library.

**Comment by jaysoo** [comment]
> I think it should ignore recursive when the dependency has the 'publishable' flag. Sometimes you need recursive dependencies when you are not publishing some of the libraries or want to collect everything in one library.

But consumers of that parent library won't be able to use it without also adding the child libraries, or am I missing something here?

For example, I have `@acme/parent-lib` that consumes `@acme/child-lib`, I don't want npm deps from `child-lib` to be in the final `package.json of `parent-lib`. Even if you aren't publishing `parent-lib`, there is no way to consume it without also adding `child-lib`.

The only valid use-case for including deps of deps is if we are bundling `child-lib` into `parent-lib`. This bundling isn't currently supported so isn't a concern. If this behavior is needed we should track is as a separate enhancement.
