### ISSUE TITLE
core: build/package executors should include only implementation files for `package.json#dependencies` generation from project-graph

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#8641]
## Current Behavior

This occurs in every executor related to packaging/building. For simplicity I'd describe behaviour for `@nrwl/node:package` executor.

**1. We have following dep-graph (contrived for simplicity)**

![2022-01-21 at 15 03](https://user-images.githubusercontent.com/1223799/150540250-28cd1d3e-c3c0-4574-a08e-df294b135690.png)

now when running `nx run @griffel/jest-serializer:build`

following package.json will be generated:

```json
"dependencies":  {
    // repo pacakges
    "@griffel/react": "1.0.0",
    "@griffel/core": "1.0.7",
    "@griffel/hello": "0.0.1"

     // npm packages - those are used in core and react
    "stylis": "^4.0.13",
    "@emotion/hash": "^0.8.0",
    "rtl-css-js": "^1.15.0",
    "csstype": "^2.6.19"
}
```

> 💡 **Note:** npm packages and `@griffel/react` shouldn't be here as well - see https://github.com/nrwl/nx/issues/8640

based on following dependency graph creation (`nx print-affected --target=build`):

```json
"dependencies": {
      "@griffel/jest-serializer": [
        {
          "source": "@griffel/jest-serializer",
          "target": "npm:@testing-library/jest-dom",
          "type": "static"
        },
        {
          "source": "@griffel/jest-serializer",
          "target": "npm:react",
          "type": "static"
        },
        {
          "source": "@griffel/jest-serializer",
          "target": "npm:@testing-library/react",
          "type": "static"
        },
        {
          "source": "@griffel/jest-serializer",
          "target": "@griffel/hello",
          "type": "static"
        },
        {
          "source": "@griffel/jest-serializer",
          "target": "@griffel/core",
          "type": "static"
        }
      ],
}
```

**2. If we remove import statements for `@griffel/core` from implementation files of `@griffel/jest-serializer` package**

![2022-01-21 at 15 08](https://user-images.githubusercontent.com/1223799/150540894-eb6fcbed-5fce-4198-be2c-768506e3f7a3.png)

following package.json will be generated:

```
"dependencies":  {
  "@griffel/hello": "0.0.1"
}
```

based on following dependency graph creation (`nx print-affected --target=build`):

```json
"dependencies": {
"@griffel/jest-serializer": [
        {
          "source": "@griffel/jest-serializer",
          "target": "npm:@testing-library/jest-dom",
          "type": "static"
        },
        {
          "source": "@griffel/jest-serializer",
          "target": "npm:react",
          "type": "static"
        },
        {
          "source": "@griffel/jest-serializer",
          "target": "npm:@testing-library/react",
          "type": "static"
        },
        {
          "source": "@griffel/jest-serializer",
          "target": "@griffel/hello",
          "type": "static"
        }
      ],
}
```

**3. Now only if we remove `@griffel/hello` from our **test file** we'll get no dependencies **as expected****

![2022-01-21 at 15 11](https://user-images.githubusercontent.com/1223799/150541387-ab01d81d-e0da-40d2-a769-f566ff606f5d.png)

following package.json will be generated:

```
"dependencies": {}
```

based on following dependency graph creation (`nx print-affected --target=build`):

```json
"dependencies": {
"@griffel/jest-serializer": [
        {
          "source": "@griffel/jest-serializer",
          "target": "npm:@testing-library/jest-dom",
          "type": "static"
        },
        {
          "source": "@griffel/jest-serializer",
          "target": "npm:react",
          "type": "static"
        },
        {
          "source": "@griffel/jest-serializer",
          "target": "npm:@testing-library/react",
          "type": "static"
        }
      ],
}
```

## Expected Behavior

- During `package.json` generation executed while running package/build executors, dependency graph should be filtered/processed to include only implementation files for package.json generation.

Based on our original dependency graph:
![2022-01-21 at 15 03](https://user-images.githubusercontent.com/1223799/150540250-28cd1d3e-c3c0-4574-a08e-df294b135690.png)

Following package.json should be generated:

```json
"dependencies":  {
    // repo packages
    "@griffel/core": "1.0.7",
}
```

- `.nxignore` should be included in filtering as currently it is omitted as well.

### Environment

```
Node : 14.18.1
  OS   : darwin x64
  yarn : 3.1.1
  
  nx : 13.4.6
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.6
  @nrwl/cypress : 13.4.6
  @nrwl/devkit : 13.4.6
  @nrwl/eslint-plugin-nx : 13.4.6
  @nrwl/express : undefined
  @nrwl/jest : 13.4.6
  @nrwl/linter : 13.4.6
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.4.6
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.4.6
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.6
  @nrwl/web : 13.4.6
  @nrwl/workspace : 13.4.6
  @nrwl/storybook : 13.4.6
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
         @nrwl/js: 13.4.6
```

**Comment by egorderg** [comment]
I think it's the same problem like in #8640.
Will the solution also be integrated into @nrwl/js:tsc? I have currently some npm packages where i create them with js:tsc and don't want the recursive dependencies.

**Comment by tinesoft** [comment]
@egorderg the solution was integrated to `@nrwl/js:tsc` in https://github.com/nrwl/nx/pull/10600, before [being reverted](https://github.com/nrwl/nx/pull/10600#issuecomment-1149068899) because it caused other issues...
No other update so far...
