### ISSUE TITLE
docker build failing after upgrade to @nrwl/workspace 13.4.6

### ISSUE THREAD

**Issue by bahizi** [nrwl/nx#8654]
## Current Behavior
After the upgrade to version 13.4.6 of `@nrwl/workspace`, docker builds are failing as the build commands
are assuming that git is available, which won't be the case in most docker builds that use slim base images.

## Expected Behavior
As in versions <13.4.6, I'd expect the build commands to not attempt executing git since git won't always be available, for various reasons.

## Steps to Reproduce

To reproduce the issue, take a look at https://github.com/bahizi/nx-docker-build. Clone the repo and try running a simple `docker build .` in the root directory.

The `fix/docker-build` branch will work as expected, since there we're using `@nrwl/workspace@13.4.5`

### Failure Logs

```
> nx-docker-build@0.0.0 ng /home/airline
> nx "run" "api:build"

events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn git',
  path: 'git',
  spawnargs: [ 'ls-files', '-s', '-z', '--exclude-standard', '.' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nx-docker-build@0.0.0 ng: `nx "run" "api:build"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nx-docker-build@0.0.0 ng script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


```

### Environment
Docker. The `node:14.18.2-alpine3.14` image

**Comment by sjjk001** [comment]
I have has the same issue but I have managed to fix it. I had to install git in the container as nx makes use of git history. Try `apt-get update - apt-get install git `or `apk update && apk add git`.

**Comment by bahizi** [comment]
yep, installing git in the container would work, but may not be allowed in some organizations for runtime containers.

**Comment by sjjk001** [comment]
I'm sorry I did not read the issue description fully. I understand your point now. Either way this post has helped me solve my issue thank you.

**Comment by balibou** [comment]
> I have had the same issue but I have managed to fix it. I had to install git in the container as nx makes use of git history. Try `apt-get update && apt-get install git` or `apk update && apk add git`.

also:
```yml
before_script:
  - apk add --update git
```

**Comment by bahizi** [comment]
After looking at this more, figured out a simple and elegant way to solve the issue: add `.git` to the `.dockerignore` file. Closing the issue.

**Comment by DriLLFreAK100** [comment]
@bahizi I have just migrated an app to Nx Workspace v13.5.3, adding .git to .dockerignore doesn't work unfortunately :(

**Comment by bahizi** [comment]
@DriLLFreAK100 tested this in https://github.com/bahizi/nx-docker-build/tree/feature/migrate-to-nx-13.5.3 and you're right, seems 13.5.3 are now failing even when the `.git` folder is excluded/missing. Unfortunately without having taken a close look at the commits since 13.4.5 or 13.4.6 yet, I am out of ideas at the moment.

@vsavkin hate to tag you directly but can we pick your brain here? Looks like since 13.4.6 nx workspace builds are getting tightly coupled with git (so much that they'll fail when git isn't installed). Is this a side effect of some other feature or is it here to stay and if so, thoughts on how to get around it? Ideally we'd like to not have to install git in prod runtime images.

**Comment by simonstone97** [comment]
I have a similar problem regarding the `.git` folder, but this is not related to a Docker environment. Compiling my libraries, which have a dependency on each other, fail. This has been happening since the update to nx 13.4.6, I was able to figure out that it only fails if there is no `.git` folder in the project. However, since I have a mono repo and the NX project is only a part of the repo, the `.git` folder is one level up.

Here is my issue: https://github.com/nrwl/nx/issues/8716

**Comment by FrozenPandaz** [comment]
Sorry all, the builds should not fail without `git`. We will address the issue.
