### ISSUE TITLE
Nx 13 dep-graph does not show affected projects in HTML output

### ISSUE THREAD

**Issue by fallion** [nrwl/nx#8657]
## Current Behavior
Running `nx affected:dep-graph --base=main --head=HEAD --file=dist/dep-graph/index.html` yields an HTML page with no affected projects visible.

## Expected Behavior
In Nx 12 the same command would yield a dep graph HTML output that could be deployed as part of the PR to help developers visualize the apps/libs that had been affected. 

In Nx 13 the new dep-graph, while being much nicer, does not include the affected libraries in the final build output for HTML output. This means that the developer can only view all apps/libs and cannot dive into what had been affected by the PR.

## Steps to Reproduce

**Example repo**: https://github.com/fallion/nx-dep-graph-example/tree/example
In repo:
- clone
- checkout example branch
- cd into nx-12
- run `yarn`
- run `yarn example`
- check localhost:3000
- repeat for folder nx-latest and compare outputs

From scratch
- Set up project using: npx create-nx-workspace@latest
- Push to main
- Create a branch
- Create a library and commit it to the new branch
- Run  `nx affected:dep-graph --base=main --head=HEAD --file=dist/dep-graph/index.html`
- Serve the HTML files using any static page serving tool

### Failure Logs

The command succeeds.

### Environment
 Node : 16.13.0
  OS   : linux x64
  yarn : 1.22.17
  
  nx : 13.4.6
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.6
  @nrwl/cypress : undefined
  @nrwl/devkit : 13.4.6
  @nrwl/eslint-plugin-nx : 13.4.6
  @nrwl/express : undefined
  @nrwl/jest : 13.4.6
  @nrwl/linter : 13.4.6
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.4.6
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.6
  @nrwl/web : undefined
  @nrwl/workspace : 13.4.6
  @nrwl/storybook : undefined
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:

**Comment by Hotell** [comment]
it would be also good idea to add testing coverage for affected and other related CLI `dep-graph` functionality https://github.com/nrwl/nx/tree/master/dep-graph/client-e2e/src to catch these kinds of regression in the future.
