### ISSUE TITLE
workspace: make `affected` function public API/callable

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#8664]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

If one needs to get list of all affected projects for any kind of programatic processing there is only `CLI` way how to achieve this is by running:

1. `nx print-affected --select=projects`
2. `nx affected:libs && nx affected:apps`

The command needs to be executed from node program/script which is forced  to post processed the terminal output.

```js
const {execSync} = require('child_process')

const output =  execSync('nx print-affected --select=projects')
const affectedProjects = output.trim().split(',').map(value=>value.trim())


if(affectedProjects.length > 0)(

 // DO STUFF
)
```

## Suggested Implementation

- as a start adding `--json` flag to `affected` family of commands
  -  `nx print-affected --select=projects --json` emits `{"version":2", "projects": [...]}`
- refactoring `affected` function to be able to return data structure
```js
import {affected} from '@nrwl/workspace'

const affectedGraph = affected()

const affectedProjects =  affectedGraph.projects

if(affectedProjects.length > 0){
   // DO STUFF
}
```  

## Related issues

https://github.com/nrwl/nx/issues/8099

**Comment by FrozenPandaz** [comment]
I agree, this would be awesome.

But I would say let's hold off on doing this for now. The core packages are being reorganized soon so it'll be more clear where this should end up. If we do it now, there's a good chance it will be moved to somewhere else.

**Comment by Nodonisko** [comment]
Any news on this?
