### ISSUE TITLE
Malformed library/app package.json files prevents the NX CLI from discovering targets in workspace.json

### ISSUE THREAD

**Issue by KronsyC** [nrwl/nx#8682]
## Current Behavior
Whenever You attempt to build a library with a malformed `package.json`, cli says cannot find target `build`

## Expected Behavior
Should probably give a more specific error, i.e `malformed package.json`

## Steps to Reproduce

1. Create a new library
2. Add a trailing comma to the package.json or something else
3. Attempt build
4. profit?

### Failure Logs

```bash
>  NX Cannot find target 'build' for project 'web'
```
### Environment
   Node : 16.13.1
   OS   : win32 x64
   yarn : 1.22.11

   nx : 13.5.1
   @nrwl/angular : undefined
   @nrwl/cli : 13.5.1
   @nrwl/cypress : undefined
   @nrwl/detox : undefined
   @nrwl/devkit : 13.5.1
   @nrwl/eslint-plugin-nx : 13.5.1
   @nrwl/express : undefined
   @nrwl/jest : 13.5.1
   @nrwl/js : 13.5.1
   @nrwl/linter : 13.5.1
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : undefined
   @nrwl/tao : 13.5.1
   @nrwl/web : undefined
   @nrwl/workspace : 13.5.1
   typescript : 4.4.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

**Comment by hcharley** [comment]
I had this happen to me with a trailing comma in the `apps/xyz/package.json` of my project:

```json5
{
  "name": "@org/xyz",
  "version": "1.399.0",
  "bin": {
    "xyz": "./assets/cli.js"
  },
  "publishConfig": {
    "registry": "https://npm.pkg.github.com"
  },
  "repository": "https://github.com/xyz/xyz",
  "dependencies": {
    "@trivago/prettier-plugin-sort-imports": "^3.2.0", // <------- Trailing comma made this happen
  }
}
```

**Comment by hcharley** [comment]
I think this issue should probably be renamed to "Malformed library/app package.json files prevents the NX CLI from discovering targets in workspace.json"
