### ISSUE TITLE
Environment Variables from .env not working in Angular projects

### ISSUE THREAD

**Issue by k3nsei** [nrwl/nx#8697]
## Current Behavior

When I want to use variables from .env file in angular project I'm getting this error.

![image](https://user-images.githubusercontent.com/190422/151040277-8a8abc4e-ac28-4332-bf20-74f2491b401b.png)

## Expected Behavior

I want to have value from .env file in envirements object. Like it is working with react project.
**I don't want to hardcode secrets in my repo, so this feature is crucial.**

![image](https://user-images.githubusercontent.com/190422/151040461-c860cabc-07a5-4cf5-9024-85e8529e9df5.png)

## Steps to Reproduce

Based on this guide: https://nx.dev/guides/environment-variables
Here is a repo with example code https://github.com/k3nsei/nx-env-var

Please look into files:
```
.env

apps/angular/src/environments/environment.ts
apps/react/src/environments/environment.ts

apps/angular/src/main.ts
apps/react/src/main.tsx
```

### Failure Logs

Screen was provided in `current behavior`

### Environment

```
   Node : 16.13.2
   OS   : win32 x64
   npm  : 8.3.1
   
   nx : 13.5.2
   @nrwl/angular : 13.5.2
   @nrwl/cli : 13.5.2
   @nrwl/cypress : 13.5.2
   @nrwl/detox : undefined
   @nrwl/devkit : 13.5.2
   @nrwl/eslint-plugin-nx : 13.5.2
   @nrwl/express : undefined
   @nrwl/jest : 13.5.2
   @nrwl/js : 13.5.2
   @nrwl/linter : 13.5.2
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : 13.5.2
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.5.2
   @nrwl/tao : 13.5.2
   @nrwl/web : 13.5.2
   @nrwl/workspace : 13.5.2
   typescript : 4.4.4
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
   	 @angular/animations: 13.1.3
   	 @angular/common: 13.1.3
   	 @angular/compiler: 13.1.3
   	 @angular/core: 13.1.3
   	 @angular/forms: 13.1.3
   	 @angular/platform-browser: 13.1.3
   	 @angular/platform-browser-dynamic: 13.1.3
   	 @angular/router: 13.1.3
   	 @angular-devkit/build-angular: 13.1.4
   	 @angular/cli: 13.1.4
   	 @angular/compiler-cli: 13.1.3
   	 @angular/language-service: 13.1.3
```

**Comment by Coly010** [comment]
Hey! So it seems like you may be a little confused here on mixing different contexts.

`.env` files work by substituting the values at build time into the `process.env`. For React and Web projects, we use an Nx Executor that has been built to iterate over the values in `process.env` looking for any that begins with NX. Then we replace any instance we see of these env vars. 

This all happens during the build process which is key here. During build, we're running within a NodeJS context which has access to NodeJS specific globals, i.e. `process`.

Angular projects do not share this ability. They are built using the Angular CLI builder, so we have less control over what is possible during build time. It should also be noted that the `environment.ts` file is read by Angular projects at runtime, in a browser context. We are no longer in NodeJS, we are using the Browser's JS Context. At this point, we do not have NodeJS specific globals such as `process`. 

You might find this article to be of some help: https://javascript.plainenglish.io/setup-dotenv-to-access-environment-variables-in-angular-9-f06c6ffb86c0


As this isn't an issue with Nx directly, I'm going to close this issue. However, feel free to reach out and ask for more help if required.

**Comment by k3nsei** [comment]
@Coly010 you don't understand I wan't to read variables from .env file specific for my local environment and I don't want to push that information to git repository as it could be personal tokens. Webpack have [EnvironmentPlugin](https://webpack.js.org/plugins/environment-plugin/) that allow to replace those during build process, so in runtime there would be value from that variable.

**Comment by Coly010** [comment]
We do have an executor that allows you to use a custom webpack config. `@nrwl/angular:webpack-browser`. You can then use Webpack Env plugin if you want.

We actually do state in the documentation what we support. This is taken from the link you provided in your original issue:
`Nx supports interpolating environment variables into your index.html file for React and Web applications.`

**Comment by k3nsei** [comment]
So maybe it should be market in more readable form like tag/pills on top of
the page below header.

Anyways I solved that by using proxy and bypass function.

pon., 31 sty 2022, 12:11 użytkownik Colum Ferry ***@***.***>
napisał:
