### ISSUE TITLE
nx build issues

### ISSUE THREAD

**Issue by raoitjewelers** [nrwl/nx#8699]
## Current Behavior
Trying to build with nx build app-name --prod does not generate any build. 
It simply shows the message -
_NX  Running target build for project <project-name> and 1 task(s) that it depends on._

![image](https://user-images.githubusercontent.com/64246856/151065431-f006becc-beec-4401-9a94-6a13745ee32d.png)

But it does not generate any dist folder output of the build. 

## Expected Behavior

dist folder should get generated with the build output

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

NX  Running target build for project vms and 1 task(s) that it depends on.

**Comment by FrozenPandaz** [comment]
Could you please provide a repo that we can use to reproduce and debug the issue?

**Comment by gitaumoses4** [comment]
@raoitjewelers did you get a fix for this?

**Comment by bublinec** [comment]
Same issue here. No idea what's wrong

**Comment by bublinec** [comment]
For me the problem was importing a function from another project within the monorepo:

This fixed the issue:
<img width="996" alt="Screenshot 2022-06-27 at 09 15 24" src="https://user-images.githubusercontent.com/44405894/175881376-1c245905-fd2f-497b-bdf5-4a9ad3c654fc.png">
