### ISSUE TITLE
No error when using non-existent configuration

### ISSUE THREAD

**Issue by raymondpebble** [nrwl/nx#8700]
## Current Behavior
`nx target:nonexistent-configuration project` silently runs the target with its default configuration.

## Expected Behavior
The command should fail with an error that `nonexistent-configuration` does not exist.

This would help catch A) typos when the user types in the command and B) errors in the workspace.json/project.json setup.
 
E.g. with a Nx react project, `serve:production` runs the `build:production` target. Case A) If a user types `nx serve:prod` by accident, Nx does not show any errors. Case B) If a user adds `serve:staging` and refers to `build:staging` but forgets to add the `build:staging` configuration, Nx does not show any errors and incorrectly builds with the default configuration.

## Steps to Reproduce
Scaffold any Nx project. Try to run a target using a nonexistent configuration.

### Environment
```
>  NX  Report complete - copy this into the issue template

  Node : 16.13.0
  OS   : darwin arm64
  npm  : 8.1.0

  nx : 13.1.4
  @nrwl/angular : Not Found
  @nrwl/cli : 12.3.6
  @nrwl/cypress : 12.3.6
  @nrwl/devkit : 12.3.6
  @nrwl/eslint-plugin-nx : 12.3.6
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.6
  @nrwl/linter : 12.3.6
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 12.3.6
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.6
  @nrwl/web : 12.3.6
  @nrwl/workspace : 12.3.6
  @nrwl/storybook : 12.3.6
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by FrozenPandaz** [comment]
Sorry, that isn't a correct way to pass a `configuration`. We should throw an error in that case.

But you should use `nx target proj --configuration some-config` instead. It will throw an error if `some-config` does not exist on `proj:target`.

**Comment by raymondpebble** [comment]
Oh I didn't realize, thanks! Was `target:configuration` some internal API that happened to work?
