### ISSUE TITLE
Nest.js + GraphQL + Optimization -> Duplicated class names.

### ISSUE THREAD

**Issue by j** [nrwl/nx#8701]
## Current Behavior

Production optimization has duplicate class names which breaks libraries that require reflection (Nest.js).  With an optimized production build, it's duplicating classes with a suffix and those are being handed over to GraphQL.  THis is causing GraphQL schema to use the class names with the suffix as well as, for some reason, in Nest.js, loading modules twice.

## Expected Behavior

I expect my GraphQL schema to use the exact name I defined as the `@ObjectType`'s class name.
I also expect Nest.js to load modules ones.

## Steps to Reproduce

```typescript
// foo.ts
@ObjectType()
class Foo { /** ... */ }

// auth.module.ts
@Module({})
export class AuthModule { /** ... */ }
```

In regards to the ObjectType, some ObjectTypes will be named `Foo_1` in the schema.

In regards to the `AuthModule`, when importing that module, Nest.js for some reason is loading it twice:

```
[Nest] 1  - 01/25/2022, 11:31:09 PM     LOG [InstanceLoader] AuthModule dependencies initialized +1ms
...
[Nest] 1  - 01/25/2022, 11:31:09 PM     LOG [InstanceLoader] AuthModule_1 dependencies initialized +1ms
```

Run a nest.js app with optimization = true (--prod by default).  I can confirm that removing optimization, things work as intended, though the bundled file will still have the suffixed name, however it's not double loading modules and naming GraphQL types incorrectly.

The bundled, "unoptimized" code looks like:

```typescript
let Adjustment = Adjustment_1 = class Adjustment {
```

But somehow everything works when not optimized.

### Environment

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : darwin x64
   npm  : 8.1.2
   
   nx : 13.5.3
   @nrwl/angular : undefined
   @nrwl/cli : 13.5.3
   @nrwl/cypress : undefined
   @nrwl/detox : undefined
   @nrwl/devkit : 13.5.3
   @nrwl/eslint-plugin-nx : 13.5.3
   @nrwl/express : undefined
   @nrwl/jest : 13.5.3
   @nrwl/js : undefined
   @nrwl/linter : 13.5.3
   @nrwl/nest : 13.5.3
   @nrwl/next : undefined
   @nrwl/node : 13.5.3
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : undefined
   @nrwl/tao : 13.5.3
   @nrwl/web : undefined
   @nrwl/workspace : 13.5.3
   typescript : 4.3.5
   rxjs : 7.3.0
   ---------------------------------------
   Community plugins:

I think this issue was the "fix" but it didn't fix in my case:  https://github.com/nrwl/nx/issues/8537

**Comment by benediktms** [comment]
I have the exact same issue. Turning optimizations off is the only way to get this to work.

**Comment by j** [comment]
@benediktms Yeah, we stopped using NODE_ENV for anything other than the build process.  We started using APP_ENV for app related environments.  I believe it was because we wanted a "production" build but to have have staging.  So in that case, NODE_ENV would be production but APP_ENV would be staging and can load configuration based on that.

**Comment by augustolima** [comment]
We've been experiencing the same issue. We didn't have the NODE_ENV set, since NX ignores it. Turning optimization off get the stuff to work.
