### ISSUE TITLE
set sensible defaults for  'directory' , 'modules' prompts for schematics

### ISSUE THREAD

**Issue by xmlking** [nrwl/nx#871]
Most of the times we want to create app and lib modules in `/apps` and  `/libs` directories respectively. 
if we want to generate module in silent mode, we have to explicitly specify `--modules`  `--directory` options which force us type long commands.

Having sensible defaults for `--modules=true`  `--directory=` options  make those commands short.

```
ng g lib NotFound     --routing  --module --directory --lazy --prefix=ngx --parent-module=apps/dapp/src/app/app.module.ts --unit-test-runner=jest --tags=entry-module
```

**Comment by xmlking** [comment]
I am seeing prompts like  `"In which directory should the library be generated?"` when I try to create an `app` or `lib` in nx monorepo using CLI.  I would live to suppress them without passing any extra command-line arguments.  
I am thinking if you set  "default": "" in 
https://github.com/nrwl/nx/blob/master/packages/schematics/src/collection/library/schema.json#L16
the prompts will be silenced.

**Comment by xmlking** [comment]
please also make `module` optional and default to `false`

**Comment by FrozenPandaz** [comment]
Even options which have a default will have a prompt. There is no way currently to exclude certain ones. The following are 2 options:
  * You can disable the interactive prompts by passing `--no-interactive`.
  * You can also pass `--defaults` to disable them only for options which have a default.

**Comment by vsavkin** [comment]
I'm going to close this issue. If it's still present, could you reopen it? Thank you!
