### ISSUE TITLE
Unable to generate Stories for non-wrapped tags or components

### ISSUE THREAD

**Issue by robotsrng** [nrwl/nx#8715]
## Current Behavior

When generating stories with pure React components, nothing is generated. This is specific to components that have no open and close tags. For example 
`return (<img ... ... .. />)` will not generate a story or end to end tests. but `return (<img ... ... ... > </img>)` will generate stories and tests.

Wrapping the tag in react fragments doesn't work either unfortunately, ie. `return (<><img ... ... ... /></>` doesn't work.

These components all include default exports, and if you just add a div around tag, it will generate the stories.

## Expected Behavior

I would expect that regardless of the size of the component, or whether it was a wrapper, it would still generate stories / tests automatically using `npx nx generate @nrwl/react:stories --project=ui` 

## Steps to Reproduce

Create a new React workspace, with a library. Generate a component, but change it to something simple (like <input type="text" />)
attempt to generate a story and end to end tests for it.

I traced this into the stories generator, and ast_utils, but got lost in there. It seems to be finding the identifier and defaultExport, but failing at line 347 ish in the ast-utils.js file.

Pr with basic reproduction - https://github.com/nrwl/nx-examples/pull/184

### Failure Logs
No failure logs

### Environment
Local environment

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : linux x64
   yarn : 1.22.17
   
   nx : 13.5.2
   @nrwl/angular : 13.5.2
   @nrwl/cli : 13.5.2
   @nrwl/cypress : 13.5.2
   @nrwl/detox : undefined
   @nrwl/devkit : 13.5.2
   @nrwl/eslint-plugin-nx : 13.5.2
   @nrwl/express : undefined
   @nrwl/jest : 13.5.2
   @nrwl/js : 13.5.2
   @nrwl/linter : 13.5.2
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : 13.1.2
   @nrwl/react : 13.5.2
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.5.2
   @nrwl/tao : 13.5.2
   @nrwl/web : 13.5.2
   @nrwl/workspace : 13.5.2
   typescript : 4.5.4
   rxjs : 6.5.5
   ---------------------------------------
   Community plugins:
   	 @angular/animations: 13.1.1
   	 @angular/common: 13.1.1
   	 @angular/compiler: 13.1.1
   	 @angular/core: 13.1.1
   	 @angular/forms: 13.1.1
   	 @angular/platform-browser: 13.1.1
   	 @angular/platform-browser-dynamic: 13.1.1
   	 @angular/router: 13.1.1
   	 @ngrx/component-store: 13.0.1
   	 @ngrx/effects: 13.0.1
   	 @ngrx/entity: 13.0.1
   	 @ngrx/router-store: 13.0.1
   	 @ngrx/store: 13.0.1
   	 @angular-devkit/build-angular: 13.1.2
   	 @angular/cli: 13.1.2
   	 @angular/compiler-cli: 13.1.1
   	 @angular/language-service: 13.1.1
   	 @ngrx/store-devtools: 13.0.1

(node:152062) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /home/shattered/code/nx-examples/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by mandarini** [comment]
Thanks for filing this issue @robotsrng ! And thank you for pointing me to the source of the problem, in that file, too! :) It was very helpful, it sped up my debugging process! It turns out we were only checking for `ts.SyntaxKind.JsxElement` and not for `ts.SyntaxKind.JsxSelfClosingElement` :)
