### ISSUE TITLE
New Daemon enabled by default breaks docker compilation

### ISSUE THREAD

**Issue by vincent-benbria** [nrwl/nx#8750]
## Current Behavior
Normal Nx project upgraded to v13.6.x fails to build in docker with `UnhandledPromiseRejectionWarning: Error: Failed to start the Nx Daemon process. `

## Expected Behavior
That breaking changes that affect most build processes and a lot of development environment be better documented than a one-liner "feature". This is also in spite of adding the `ENV NX_DAEMON=false` (or the weird typo ENV NX_DEAMON=false from documentation).

## Steps to Reproduce
Try to build any project in docker

### Failure Logs
```
 => => # (node:17) UnhandledPromiseRejectionWarning: Error: Failed to start the Nx Daemon process.                                                                                                        
 => => # Messages from the log:                                                                                                                                                                           
 => => # Error: listen EACCES: permission denied /app/node_modules/@nrwl/workspace/src/core/project-graph/daemon/client/.cache/nx/d/d.sock                                                                
 => => #     at Server.setupListenHandle [as _listen2] (net.js:1299:21)                                                                                                                                   
 => => #     at listenInCluster (net.js:1                                                                                                                                                                 
 => => # [output clipped, log limit 100KiB/s reached]
```

### Environment
docker.

**Comment by vsavkin** [comment]
@vincent-benbria could you provide your command and the full log?

**Comment by sheikalthaf** [comment]
@vsavkin I'm facing the same issue in our pipeline

![image](https://user-images.githubusercontent.com/22526247/151686794-0b9f62cf-f3c3-4da4-b6db-72750ed2248e.png)

**Comment by sheikalthaf** [comment]
It is working fine in latest nx version. This issue is only available in **nx13.6**
