### ISSUE TITLE
NestJs Swagger DTO not showing

### ISSUE THREAD

**Issue by techandmedia** [nrwl/nx#8766]
## Current Behavior

Empty DTO in Swagger API
![Capture](https://user-images.githubusercontent.com/15700861/151652983-5f3f2a60-1d12-4f58-a3ca-d71ce70898d7.JPG)

## Expected Behavior

Using this sample repo without Nx Monorepo shows DTO Swagger works fine
![Capture](https://user-images.githubusercontent.com/15700861/151653011-36f757a1-9f5f-4adf-b968-e0c06c642a8d.JPG)

## Steps to Reproduce

NestJs with Swagger: works
https://github.com/techandmedia/nx-reporting/tree/error/missing-swagger-dto

Nx Monorepo with NestJs and Swagger: not work
https://github.com/techandmedia/nx-reporting/tree/error/missing-swagger-dto

### Failure Logs

No Error

### Environment

```bash
>  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : win32 x64
   yarn : 1.22.10                                                                              k out https

   nx : 13.7.1                                                                                 r-dto ✖ ✱ ◼
   @nrwl/angular : undefined
   @nrwl/cli : 13.7.1
   @nrwl/cypress : 13.7.1
   @nrwl/detox : undefined
   @nrwl/devkit : 13.7.1                                                                       r-dto ✖ ✱ ◼
   @nrwl/eslint-plugin-nx : 13.7.1                                                             r-dto ✖ ✱ ◼
   @nrwl/express : undefined
   @nrwl/jest : 13.7.1
   @nrwl/js : 13.7.1
   @nrwl/linter : 13.7.1
   @nrwl/nest : 13.7.1
   @nrwl/next : undefined
   @nrwl/node : 13.7.1
   @nrwl/nx-cloud : undefined
   @nrwl/react : 13.7.1
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.7.1
   @nrwl/tao : 13.7.1
   @nrwl/web : 13.7.1
   @nrwl/workspace : 13.7.1
   typescript : 4.5.5
   rxjs : 7.5.2
   ---------------------------------------
   Community plugins:

(node:12528) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at D:\Projects\Test\nx-error\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by kendallroth** [comment]
I have noticed this as well recently, but oddly enough found that some random manipulations in the affected DTO or controller files could sometimes automagically make the plugin start working and detect those specific DTOs! I have absolutely no idea why this might be, but have validated it on another environment. Unfortunately this makes the plugin almost unusable as it does not provide much benefit since the body is not getting set automatically, nor are comments being introspected.

**Comment by kendallroth** [comment]
Enabling the plugin seems to automatically perform most of the described tasks, but _not_ the last several

> The Swagger plugin will automatically:
> - annotate all DTO properties with `@ApiProperty` unless `@ApiHideProperty` is used
> - set the required property depending on the question mark (e.g. `name?: string` will set `required: false`)
> - set the type or enum property depending on the type (supports arrays as well)
> - set the default property based on the assigned default value
> - set several validation rules based on class-validator decorators (if `classValidatorShim` set to true)
> - ~add a response decorator to every endpoint with a proper status and type (response model)~
> - ~generate descriptions for properties and endpoints based on comments (if `introspectComments` set to true)~
> - ~generate example values for properties based on comments (if `introspectComments` set to true)~

**Comment by kendallroth** [comment]
Just to confirm how sporadic this is, I modified a single DTO (at random) to add an `@example` comment, and suddenly everything was working again... 🤦
