### ISSUE TITLE
Defer loading Effects until APP_INITIALIZER promise is resolved

### ISSUE THREAD

**Issue by KuldeepDesai** [nrwl/nx#877]
In my app, we are loading runtime configuration via a rest call thru APP_INITIALIZER provider in main app. There are no effects defined at app level, all effects are defined at lib level and libs are loaded via lazy-loading. 
The effects and in-turn the services are initialized before APP_INITIALIZER is complete. How, do I halt initialization of Effects until the promise is complete?

**Comment by brandonroberts** [comment]
This issue has already been raised in the [NgRx repo](https://github.com/ngrx/platform) and is not applicable to Nx.
