### ISSUE TITLE
Could not find TypeScript configuration file "tsconfig.build.json". Please, ensure that you are running this command in the appropriate directory (inside Nest workspace).

### ISSUE THREAD

**Issue by Arkady-Skvortsov** [nrwl/nx#8777]
`npx nest start ./apps/api`:   Could not find TypeScript configuration file "tsconfig.build.json". Please, ensure that you are running this command in the appropriate directory (inside Nest workspace). When I want to start Nest application;

I have an Angular/Nest Monorepo

## Current Behavior
Throw an exception, which I had written upper; I dunno why, cause I have tsconfig.build.json file in /api directory with project

## Expected Behavior
Just start an application

### Failure Logs
Could not find TypeScript configuration file "tsconfig.build.json". Please, ensure that you are running this command in the appropriate directory (inside Nest workspace).

### Environment
Nest, Angular
nx report: DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\Arkasha\Documents\interesting-project\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".

**Comment by Arkady-Skvortsov** [comment]
Anyone now why? I have a `tsconfig.build.json` file, but he thinks that no;

**Comment by salmomascarenhas** [comment]
> Anyone now why? I have a `tsconfig.build.json` file, but he thinks that no;

managed to solve ? I have the same problem.

**Comment by yemoche** [comment]
In my own case...I added a tsconfig.build.json file to the root directory, then use this code
{
  "extends": "./tsconfig.json",
  "exclude": ["node_modules", "test", "dist", "**/*spec.ts"]
}

**Comment by mandarini** [comment]
I will close this issue, since there seems to be a fix for it. If you think that this issue should be kept open, and we, as the Nx team, should do something to address it, please ping me and I can re-open it! :)
