### ISSUE TITLE
ENOENT: no such file or directory, open 'C:\Users\Arkasha\Documents\my-project\my-project\project.json'

### ISSUE THREAD

**Issue by Arkady-Skvortsov** [nrwl/nx#8778]
## Current Behavior
I want to start some operation with @nrwl/nx CLI command, like: `` - generate angular component, and catch that: ; But I don't know why he thinks that I have a some recursion, I mean: my-project folder and (inside my-project folder again!?) and than project.json file;

## Expected Behavior
Create an Angular component or some other operation through Nx commands

### Environment
Angular, Nest;
`nx report`: [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\Аркадий\Documents\secret\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".

**Comment by FrozenPandaz** [comment]
Hi can you please provide a repo we can pull down to reproduce the issue please?

**Comment by Arkady-Skvortsov** [comment]
> Hi can you please provide a repo we can pull down to reproduce the issue please?

**Comment by Arkady-Skvortsov** [comment]
> Hi can you please provide a repo we can pull down to reproduce the issue please?

https://github.com/Arkady-Skvortsov/Adventure-Time-Card-Wars/

**Comment by timofeysie** [comment]
I have the same issue with "nx": "14.0.2".
Steps to reproduce:

```shell
>npx create-nx-workspace@latest
√ Workspace name (e.g., org name)     · demo-app
√ What to create in the new workspace · core
...
>cd demo-app
>npm install @nrwl/angular
>nx generate @nrwl/angular:app customer-portal --routing
ENOENT: no such file or directory, open 'C:\Users\timof\repos\demo-app\packages\customer-portal\project.json'
```

Note I don't want to create an Angular specific repo as I will have React apps as well in it.

It looks to me like this issue has been fixed [here[(https://github.com/nrwl/nx/issues/8707), and [here](https://github.com/nrwl/nx/pull/9466).  But the creating a core workspace and Angular app first still fails with the above error.

Note that creating a workspace with a default React app, and then adding an Angular app after that works fine.
