### ISSUE TITLE
ng g lib indentation off

### ISSUE THREAD

**Issue by markgoho** [nrwl/nx#878]
`ng g lib file-upload`

the `file-upload.module.spec.ts` file:
![image](https://user-images.githubusercontent.com/9759954/48012373-d8913280-e0ef-11e8-8902-5b8eafc1db92.png)

`file-upload.module.ts`
![image](https://user-images.githubusercontent.com/9759954/48012403-e941a880-e0ef-11e8-9291-a4ffac360985.png)

`index.ts`
![image](https://user-images.githubusercontent.com/9759954/48012433-f6f72e00-e0ef-11e8-8e8f-e56a96f3fef6.png)

Other files appear to be indented properly

**Comment by FrozenPandaz** [comment]
Files should be formatted by prettier after code generation. Can you provide a repo where we can reproduce the issue you are seeing? If not, can you please provide the command-line output?

**Comment by jaysoo** [comment]
Closing this issue as there hasn't been any activity.
