### ISSUE TITLE
bug: cannot specify new/custom @nrwl/angular:package build target name

### ISSUE THREAD

**Issue by dereekb** [nrwl/nx#8780]
## Current Behavior
When adding a new target in a project with the @nrwl/angular:package executor, the build fails, even if it has the exact same configuration as the working "build" target.

```
"build": {
          "executor": "@nrwl/angular:package",
          "outputs": ["dist/packages/dbx-web"],
          "options": {
            "project": "packages/dbx-web/ng-package.json"
          },
          "configurations": {
            "production": {
              "tsConfig": "packages/dbx-web/tsconfig.lib.prod.json"
            },
            "development": {
              "tsConfig": "packages/dbx-web/tsconfig.lib.json"
            }
          },
          "defaultConfiguration": "production"
        },

        "buildnew": {
          "executor": "@nrwl/angular:package",
          "outputs": ["dist/packages/dbx-web"],
          "options": {
            "project": "packages/dbx-web/ng-package.json"
          },
          "configurations": {
            "production": {
              "tsConfig": "packages/dbx-web/tsconfig.lib.prod.json"
            },
            "development": {
              "tsConfig": "packages/dbx-web/tsconfig.lib.json"
            }
          },
          "defaultConfiguration": "production"
        }
```

See logs below for the output.

My goal is to create the following configuration:

```
        "build-lib": {
          "executor": "@nrwl/angular:package",
          "outputs": ["dist/packages/dbx-web"],
          "options": {
            "project": "packages/dbx-web/ng-package.json"
          },
          "configurations": {
            "production": {
              "tsConfig": "packages/dbx-web/tsconfig.lib.prod.json"
            },
            "development": {
              "tsConfig": "packages/dbx-web/tsconfig.lib.json"
            }
          },
          "defaultConfiguration": "production"
        },
        "build": {
          "executor": "@nrwl/workspace:run-commands",
          "options": {
            "commands": [{
              "command": "npx nx build-lib dbx-web"
            }, {
              "command": "echo do command to do things on assets"
            }],
            "parallel": false
          }
        },
```

This way I can execute commands after running build.

## Expected Behavior
The new "build-lib" target should execute properly.

## Steps to Reproduce
It didn't seem like nx-examples had a similar enough setup, but my own non-trivial project is available here on this branch:

https://github.com/dereekb/dbcomponents/tree/nx-build-bug-report

I made a commit so you should be able to run `npx nx run dbx-web:build build-lib` after doing npm install.

My guess is that I am misunderstanding something with how nx might treat build in a special manner. It seems like when I call the `build-lib` target that it does not have any of the similar output as nx does. There's magic happening that I'm not sure how to configure around or modify.

Ultimately I don't know if this is a bug or not.

### Failure Logs

```
> nx run dbx-web:buildb:production 
Building Angular Package

------------------------------------------------------------------------------
Building entry point '@dereekb/dbx-web'
------------------------------------------------------------------------------
✖ Compiling with Angular sources in Ivy partial compilation mode.
[object Object]

———————————————————————————————————————————————

>  NX   ERROR  Running target "dbx-web:buildb" failed

  Failed tasks:
  
  - dbx-web:buildb:production
  
  Hint: run the command with --verbose for more details.

  See Nx Cloud run details at https://nx.app/runs/0CpWCTsKR1a
```

### Environment
```
Node : 16.13.2
  OS   : darwin arm64
  npm  : 8.3.2
  
  nx : undefined
  @nrwl/angular : 13.4.3
  @nrwl/cli : 13.4.3
  @nrwl/cypress : 13.4.3
  @nrwl/devkit : 13.4.3
  @nrwl/eslint-plugin-nx : 13.4.3
  @nrwl/express : undefined
  @nrwl/jest : 13.4.3
  @nrwl/linter : 13.4.3
  @nrwl/nest : 13.4.6
  @nrwl/next : undefined
  @nrwl/node : 13.4.3
  @nrwl/nx-cloud : 13.1.2
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.3
  @nrwl/web : undefined
  @nrwl/workspace : 13.4.3
  @nrwl/storybook : 13.4.3
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.5.2
  ---------------------------------------
  Community plugins:
  	 @angular/animations: 13.2.0
  	 @angular/cdk: 13.2.0
  	 @angular/common: 13.2.0
  	 @angular/compiler: 13.2.0
  	 @angular/core: 13.2.0
  	 @angular/fire: 7.2.0
  	 @angular/forms: 13.2.0
  	 @angular/material: 13.2.0
  	 @angular/platform-browser: 13.2.0
  	 @angular/platform-browser-dynamic: 13.2.0
  	 @angular/router: 13.2.0
  	 @ngrx/component-store: 13.0.2
  	 @ngrx/data: 13.0.2
  	 @ngrx/effects: 13.0.2
  	 @ngrx/entity: 13.0.2
  	 @ngrx/store: 13.0.2
  	 @ngx-formly/schematics: 6.0.0-next.6
  	 @angular-devkit/build-angular: 13.2.0
  	 @angular/cli: 13.2.0
  	 @angular/compiler-cli: 13.2.0
  	 @angular/language-service: 13.2.0
  	 @jscutlery/semver: 2.17.5
  	 @ngrx/store-devtools: 13.0.2
  	 @nrwl/js: 13.4.3
```

**Comment by FrozenPandaz** [comment]
I agree. Ideally it should work if you switch the target name.

This is a weird implementation detail where the `@nrwl/angular:package` executor looks into targets of the same name in projects it depends on. When you change the name of the target of the `dbx-web` project, it no longer uses the information from the `build` of its dependencies. The fix for this isn't simple though so in the meantime, I would keep the target names the same. For example, we use `build-base` as our target name in the nx repo instead of `build`.

**Comment by dereekb** [comment]
Gotcha. Up until now I had only added a second target, build-for-npm, and have the CI run that as well. I hadn't considered changing all of the projects to use 'build-base', and then configure a build target.

So I just went ahead and did that and everything works how I intended it to. For those who run into this, I did 3 things:

1. Change all build targets to 'build-base'
2. Add a new target called build that uses run-commands:

```
        "build": {
          "executor": "@nrwl/workspace:run-commands",
          "options": {
            "command": "npx nx run dbx-web:build-base",
            "color": true
          }
        }
```

3. Add dependsOn to the new `build-base` targets to make sure the dependencies each run their build commands as well:

```
        "build-base": {
          "executor": "@nrwl/js:tsc",
          "outputs": ["{options.outputPath}"],
          "dependsOn": [{
            "target": "build",
            "projects": "dependencies"
          }],
         ...
        }
```

You can see these changes here for reference:

https://github.com/dereekb/dbcomponents/commit/9215d57d5dfead7130b8377a9598d2cc718970f7

Getting back to the bug ticket, I think what I would suggest is adding documentation somewhere instructing how to set up more complex building, or specifically if you want to target the build command and use multiple steps. The changes I made above do make sense now, I just wasn't sure how to get there at first.
