### ISSUE TITLE
Angular version 2 is not working on Mac

### ISSUE THREAD

**Issue by JvinMahmoud** [nrwl/nx#8781]
The issue is happening only for mac / tried on windows and it works well

## Current Behavior

When trying to run ng s, i'm getting this error `angular.json': Invalid format version detected - Expected:[ 1 ] Found: [ 2 ]`
ng build works with no error

## Expected Behavior

started after update to angular new version

### Environment
MacBook / M1 - tried also with another mac (getting same issue)
MacOs / Big Sur / version 11.2.3
Node: 16.10.0
npm: 8.3.0 (tried also with 7.8.x)
angular/cli: 13.2.0,
@nrwl/cli: 13.7.1 (tried with 13.4.6 also)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This is happening because `s` is not a command supported by the Nx CLI, you should use `serve` instead and it will work as expected.

**Comment by JvinMahmoud** [comment]
Thank u @leosvelperez  for your quick response.. that was really smooth..
It works with ng serve. I still wondering, why was it working with ng s for me before?
Thanks againg 😃

**Comment by GeorgeKnap** [comment]
@leosvelperez at least some better error messages for unknown commands 🙏
