### ISSUE TITLE
Storybook global styles not used for library component  

### ISSUE THREAD

**Issue by DimitriLib** [nrwl/nx#8790]
I am trying to access application/global styles from storybook library. My setup new repository with latest packages that nx installs as of 01/26/2022

Setup sample repository at https://github.com/DimitriLib/storybook-test if somebody want to try test it.

I have 1 application apps/storybooktest that is used as projectBuildConfig for libs/lib-test
storybooktest has global styles: styles.scss that i want to be able to access in my storybook library component.

I tried the following combinations without success, global styles are not available in lib project:

Executing command: nx storybook lib-test --projectBuildConfig=storybooktest:build-storybook
Updating preview.js with: import '!style-loader!css-loader!postcss-loader!sass-loader!../../../apps/storybooktest/src/styles.scss';
import '../../../apps/storybooktest/src/styles.scss';
This is a simple setup, but on real project my application has dependency from material design theme, ag-grid and other global styles that i want to use when writing/testing library story.

Not sure where is the problem, am i doing something wrong, is it nx setup, storybook setup?
## Current Behavior

Current behavior global style is not applied to story that was created for library component.
![image](https://user-images.githubusercontent.com/66094347/151853877-94c0f048-ee12-40db-a9e1-1a88c37082ec.png)

## Expected Behavior

![image](https://user-images.githubusercontent.com/66094347/151853934-110d8d10-81f3-4d0a-b510-1654ee193b8b.png)

## Steps to Reproduce

Clone repository from https://github.com/DimitriLib/storybook-test
Install dependency: npm install
Execute command: nx storybook lib-test --projectBuildConfig=storybooktest:build-storybook
Styles from apps/storybooktest that define on the application are not used in lib-test storybook even command specifies to use projectBuildConfig

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by mandarini** [comment]
Hi @DimitriLib ! Did you try `nx storybook lib-test --projectBuildConfig=storybooktest`?

**Comment by DimitriLib** [comment]
Hi @mandarini,
Thank you for looking into this. I tried what you suggested, command:

nx storybook lib-test --projectBuildConfig=storybooktest

Gives an error: 
ModuleBuildError: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: C:\Users\dimitri.liberman\story-test\storybook\apps\storybooktest\src\polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at C:\Users\dimitri.liberman\story-test\storybook\node_modules\@ngtools\webpack\src\ivy\loader.js:60:26
    at processResult (C:\Users\dimitri.liberman\story-test\storybook\node_modules\webpack\lib\NormalModule.js:751:19)
    at C:\Users\dimitri.liberman\story-test\storybook\node_modules\webpack\lib\NormalModule.js:853:5
    at C:\Users\dimitri.liberman\story-test\storybook\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\Users\dimitri.liberman\story-test\storybook\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\Users\dimitri.liberman\story-test\storybook\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at C:\Users\dimitri.liberman\story-test\storybook\node_modules\@ngtools\webpack\src\ivy\loader.js:60:17


          Broken build, fix the error above.
          You may need to refresh the browser.
        

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "lib-test:storybook" failed

But this command works and global styles are availabel on the lib:
nx storybook lib-test --projectBuildConfig=storybooktest:build-storybook

Thank you again!

**Comment by mandarini** [comment]
Yep, that's the error I mentioned in my previous comment! :)

**Comment by mandarini** [comment]
[New docs](https://github.com/nrwl/nx/pull/9057) for `styles` and `stylePreprocessorOptions`
