### ISSUE TITLE
`@nrwl/detox` doesn't use `metro.config.js` / `nx g @nrwl/react-native:app` e2e is broken

### ISSUE THREAD

**Issue by Peeja** [nrwl/nx#8792]
## Current Behavior

On a newly generated `@nrwl/react-native:app`,
* `test-ios` fails.
* A `console.log()` placed in `metro.config.js` never appears.

## Expected Behavior

On a newly generated `@nrwl/react-native:app`,
* `test-ios` should pass.
* A `console.log()` placed in `metro.config.js` should appear somewhere.

## Steps to Reproduce

1. `nx g @nrwl/react-native:app applesauce`
2. Add `console.log('IN METRO CONFIG');` to the top of `metro.config.js`.
3. `nx run-ios applesauce`
  * This ensures `pod install` runs, and demonstrates the app working.
  * Note the `IN METRO CONFIG` in the Metro output from this command.
4. Ctrl-C to kill the `run-ios` process.
3. `nx test-ios applesauce-e2e`
  * `@nrwl/detox:build` runs `xcodebuild` which launches Terminal.app to run Metro. The Metro output does not contain `IN METRO CONFIG`, implying the `metro.config.js` is not loaded.
  * The Metro output and the simulator show an error: `Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: number.`
    * Commenting out the SVG references in the generated app causes the errors to go away. The error appears to be caused by Metro importing `.svg` files incorrectly without the `metro.config.js` (since [`withNxMetro()` changes the way they're handled](https://github.com/nrwl/nx/blob/c319367dfe8236b898a5e3f1d3c4265419157681/packages/react-native/src/generators/application/files/app/metro.config.js.template#L17-L21)).

Note that if you leave `nx run-ios applesauce` in a separate terminal and then run `nx test-ios applesauce-e2e`, the step `xcodebuild` runs will detect the running Metro process and use it instead of launching its own. Doing that causes the test to execute properly and pass. 

Repro PR: https://github.com/nrwl/nx-examples/pull/185

### Failure Logs

<details>
<summary>Metro Log</summary>

```
 ERROR  Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: number.

Check the render method of `App`.

This error is located at:
    in RCTView (at View.js:32)
    in View (at App.tsx:52)
    in RCTView (at View.js:32)
    in View (at App.tsx:51)
    in RCTView (at View.js:32)
    in View (at App.tsx:50)
    in RCTScrollContentView (at ScrollView.js:1674)
    in RCTScrollView (at ScrollView.js:1792)
    in ScrollView (at ScrollView.js:1818)
    in ScrollView (at App.tsx:37)
    in RCTSafeAreaView (at SafeAreaView.js:51)
    in SafeAreaView (at App.tsx:36)
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in main(RootComponent) (at renderApplication.js:60)
```
</details>

### Environment

<details>
<summary><code>nx report</code></summary>

```
 >  NX   Report complete - copy this into the issue template

   Node : 16.13.0
   OS   : darwin x64
   yarn : 1.22.15
   
   nx : 13.5.2
   @nrwl/angular : 13.5.2
   @nrwl/cli : 13.5.2
   @nrwl/cypress : 13.5.2
   @nrwl/detox : 13.5.3
   @nrwl/devkit : 13.5.2
   @nrwl/eslint-plugin-nx : 13.5.2
   @nrwl/express : undefined
   @nrwl/jest : 13.5.2
   @nrwl/js : 13.5.2
   @nrwl/linter : 13.5.2
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : 13.1.2
   @nrwl/react : 13.5.2
   @nrwl/react-native : 13.5.3
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.5.2
   @nrwl/tao : 13.5.2
   @nrwl/web : 13.5.2
   @nrwl/workspace : 13.5.2
   typescript : 4.5.4
   rxjs : 6.5.5
   ---------------------------------------
   Community plugins:
   	 @angular/animations: 13.1.1
   	 @angular/common: 13.1.1
   	 @angular/compiler: 13.1.1
   	 @angular/core: 13.1.1
   	 @angular/forms: 13.1.1
   	 @angular/platform-browser: 13.1.1
   	 @angular/platform-browser-dynamic: 13.1.1
   	 @angular/router: 13.1.1
   	 @ngrx/component-store: 13.0.1
   	 @ngrx/effects: 13.0.1
   	 @ngrx/entity: 13.0.1
   	 @ngrx/router-store: 13.0.1
   	 @ngrx/store: 13.0.1
   	 @angular-devkit/build-angular: 13.1.2
   	 @angular/cli: 13.1.2
   	 @angular/compiler-cli: 13.1.1
   	 @angular/language-service: 13.1.1
   	 @ngrx/store-devtools: 13.0.1

```
</details>

**Comment by xiongemi** [comment]
i got it working with above solution by running `nx start ...` in a new terminal
