### ISSUE TITLE
angular.json and nx.json are out of sync.

### ISSUE THREAD

**Issue by mousavidev** [nrwl/nx#881]
`npm run dep-graph`  returns "angular.json and nx.json are out of sync.", Is there any way to sync the nx.json by angular.json?

**Comment by stianmorsund** [comment]
Check the entries of "project" in both files and verify that you dont have any projects in only one of those files

**Comment by FrozenPandaz** [comment]
> Is there any way to sync the nx.json by angular.json

There should be an error message telling which projects are out of sync. However, could you expand on _how_ you would like to be able to sync the two files?

**Comment by wimzyLive** [comment]
@FrozenPandaz Getting same issue here, after upgrading to @nrwl/schematics: 8.4.13

**Comment by vsavkin** [comment]
@wimzyLive could you provide a github repo with a repro?

**Comment by wimzyLive** [comment]
@vsavkin It's my work repo and so unable to share it here, but what I noticed is that when I updated schematics via cli it puts `@nrwl/schematic` back to `v7.2`, and also adds new package with name `@nrwl/workspace` v8.0. I was receiving this error when I had `@nrwl/schematics` and `@nrwl/workspace`, once I removed `@nrwl/schematics` package, this error goes away.

**Comment by vsavkin** [comment]
@wimzyLive  Starting with 8.4.13, `@nrwl/schematics` is replaced with `@nrwl/workspace`. So your situation is interesting. Can you try running the update twice as described here: https://nx.dev/angular/guides/nx7-to-nx8#upgrading-from-nx-7-to-nx-8?

**Comment by vsavkin** [comment]
Folks. I'm going to close this issue. We patched up the upgrade process, and updated our guides to cover common gotchas. If you are still having problems upgrading from nx 7 to nx 8, please reopen the issue.

Thank you!
