### ISSUE TITLE
Circle CI `main` branch instructions wrong

### ISSUE THREAD

**Issue by joshribakoff-sm** [nrwl/nx#8810]
### Documentation issue
- [ ] Reporting a typo
- [x ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[https://nx.dev/ci/monorepo-ci-circle-ci](https://nx.dev/ci/monorepo-ci-circle-ci)

### Additional context or description

On the other docs pages, you conditionally set the `base` to `HEAD~1` for `main` branch builds, but here it incorrectly instructs the user to set it to `NX_BASE`, for builds on the `main` branch this causes `affected` to detect no changes if the user set it up with this mistake.

**Comment by bcabanes** [comment]
Hi! the CircleCi example is using `NX_BASE` because it is using `nrwl/nx` CircleCi Orb that calculates automatically the base for the affected command. Here is the repository https://github.com/nrwl/nx-orb.

Make sure to import the Orb (line 3) before using the `NX_BASE` syntax or like you mentioned, do the base calculation manually.

**Comment by joshribakoff-sm** [comment]
Thanks, we are already using that orb, and calling `set-shas`, and got the problem I described. I found some additional context in the logs thanks to your hints:

```
#!/bin/bash
echo "$PARAM_SCRIPT" >> "index.js"
RESPONSE=$(node index.js $CIRCLE_BUILD_URL $CIRCLE_BRANCH $PARAM_MAIN_BRANCH $PARAM_ERROR_ON_NO_SUCCESSFUL_WORKFLOW)
echo "$RESPONSE"
BASE_SHA=$(echo "$RESPONSE" | grep 'Commit:' | sed 's/.*Commit: //')
HEAD_SHA=$(git rev-parse HEAD)
echo "Base SHA"
echo $BASE_SHA
echo ""
echo "Head SHA"
echo $HEAD_SHA
echo ""
echo "export NX_BASE=\"$BASE_SHA\";" >> $BASH_ENV
echo "export NX_HEAD=\"$HEAD_SHA\";" >> $BASH_ENV
echo ""
echo "NX_BASE and NX_HEAD environment variables have been set for the current Job"

undefined:1
{:message "Project not found"}
 ^

SyntaxError: Unexpected token : in JSON at position 1
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/circleci/repo/index.js:119:22)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Base SHA


Head SHA
8d71c23c57fa837d6965473d56327b8d581ce41c


NX_BASE and NX_HEAD environment variables have been set for the current Job
CircleCI received exit code 0
```

Are we doing something wrong here? As far as we can tell we're doing everything in the docs :) We're loading the orb like this, and our main branch is simply `main` which seems to match the default in the orb:

```
orbs:
  nx: nrwl/nx@1.1.3
  aws-ecr: circleci/aws-ecr@7.3.0

```

Thanks!

**Comment by joshribakoff-sm** [comment]
@bcabanes

**Comment by joshribakoff-sm** [comment]
For anyone reading this, see:

> The commits therefore can't just be HEAD and HEAD~1. If a few deployments fail one after another, that means that we're accumulating a list of affected projects that are not getting deployed.

and

> To use this orb with a private repository on your main branch, you need to grant the orb access to your CircleCI API. You can do this by creating an environment variable called CIRCLE_API_TOKEN in the context or the project.

Note: It should be a user token, not project token.

from the orb's readme here https://github.com/nrwl/nx-orb#private-repositories

It looks like this issue report was valid, the docs on the Nx website omit this information.
