### ISSUE TITLE
Using Tailwind with publishable Libs

### ISSUE THREAD

**Issue by ohabash** [nrwl/nx#8830]
I want to build my puclishable libs with tailwind included. I can see activity around this topic but the literature is going over my head and i can narrow down a simple set of instructions to get this done. Here is what i have 

1. My lib is libs/mylib
2. config location is `libs/mylib/tailwind.config.js` it has content: [ './**/*.{html,ts,css,scss,sass,less,styl}', ],
3. the angular root components (the one host apps will use to start the view) is libs/mylib/src/lib/mylib.component.scss 
4. that is where I included the imports like @import 'tailwindcss/components';
5. nx build mylib it is not including the JIT styles as expected (tailwind classes in HTML are ignored)

Ideally the solution i am looking for is a workspace wide installation of tailwind with one config. then when publishable libs build they will all include JIT css in there assets. But I will settle for getting it to work with just one lib. 

Does any one have a high-level list of steps to take so that `nx build myPublishableLib` will include JIT and other tailwind styles?

```
"tailwindcss": "^3.0.18"
"@nrwl/angular": "13.4.4",
"@nrwl/node": "^13.4.4",
"@nrwl/cli": "13.4.4",
"@nrwl/cypress": "13.4.4",
"@nrwl/eslint-plugin-nx": "13.4.4",
"@nrwl/jest": "13.4.4",
"@nrwl/js": "13.4.4",
"@nrwl/linter": "13.4.4",
"@nrwl/nx-cloud": "13.0.2",
"@nrwl/tao": "13.4.4",
"@nrwl/workspace": "13.4.4",
```

```
Angular CLI: 13.1.3
Node: 14.16.0
Package Manager: npm 6.14.11
OS: darwin x64

Angular: 13.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.3
@angular-devkit/build-angular   13.1.3
@angular-devkit/core            13.1.3
@angular-devkit/schematics      13.1.3
@angular/cli                    13.1.3
@angular/fire                   7.2.0
@schematics/angular             13.1.3
ng-packagr                      13.1.3
rxjs                            6.6.7
typescript                      4.5.4
```

**Comment by Coly010** [comment]
Hey! :) We have a guide here on how to use Tailwind with Nx and Publishable libraries

https://nx.dev/guides/using-tailwind-css-with-angular-projects

**Comment by ohabash** [comment]
There is soo much info here. I have a specific need. I cant decide if im supposed to install it in the app level using a generator with what flags; then if it is installed at the root what needs to be done within the lib. 

Reading this lets me know it can be done but not what I need to do. However i will figure it out and post the steps unless someone already knows ?

**Comment by ohabash** [comment]
I setup tailwind with `npx nx generate @nrwl/angular:setup-tailwind mylib`

- Am i supposed to import the css utilities to a component scss? ie `@import 'tailwindcss/base';`
- when its done should I expect that `ng build` will generate the postcss where i imported that css? 
- am i supposed to generate the css with a command other than build?

**Comment by agomesd** [comment]
@Coly010 Does this work for react projects? Is there an example of this for a react library?
