### ISSUE TITLE
Unable to Compute Project Graph - ENAMETOOLONG

### ISSUE THREAD

**Issue by slewis30328** [nrwl/nx#8834]
I have a new nx workspace with 1 library and 2 apps (angular and express).

The express app has a directory of .sql (text files) that I use inside app.  Some of the file names are long.

When I try to run the lint process on the app, it fails and says:
NX   Nx Daemon was not able to compute the project graph.
NX   spawn ENAMETOOLONG

If I remove the directory that contains the .sql files, the lint process completes without issue.

**Environment:**

Windows 10
Node: 17.4

{
  "name": "smart",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test",
    "postinstall": "ngcc --properties es2015 browser module main"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.2.0",
    "@angular/common": "~13.2.0",
    "@angular/compiler": "~13.2.0",
    "@angular/core": "~13.2.0",
    "@angular/forms": "~13.2.0",
    "@angular/platform-browser": "~13.2.0",
    "@angular/platform-browser-dynamic": "~13.2.0",
    "@angular/router": "~13.2.0",
    "canvas": "^2.9.0",
    "express": "4.17.2",
    "express-fileupload": "^1.3.1",
    "morgan": "^1.10.0",
    "jsbarcode": "^3.11.5",
    "rxjs": "~7.4.0",
    "tslib": "^2.0.0",
    "xss": "^1.0.10",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.2.0",
    "@angular-eslint/eslint-plugin": "~13.0.1",
    "@angular-eslint/eslint-plugin-template": "~13.0.1",
    "@angular-eslint/template-parser": "~13.0.1",
    "@angular/cli": "~13.2.0",
    "@angular/compiler-cli": "~13.2.0",
    "@angular/language-service": "~13.2.0",
    "@nrwl/angular": "^13.7.2",
    "@nrwl/cli": "13.7.1",
    "@nrwl/cypress": "13.7.2",
    "@nrwl/eslint-plugin-nx": "13.7.1",
    "@nrwl/express": "^13.7.2",
    "@nrwl/jest": "13.7.1",
    "@nrwl/js": "^13.7.1",
    "@nrwl/linter": "13.7.1",
    "@nrwl/node": "^13.7.2",
    "@nrwl/tao": "13.7.1",
    "@nrwl/workspace": "13.7.1",
    "@types/express": "4.17.13",
    "@types/jest": "27.0.2",
    "@types/node": "16.11.7",
    "@typescript-eslint/eslint-plugin": "~5.10.0",
    "@typescript-eslint/parser": "~5.10.0",
    "cypress": "^9.1.0",
    "eslint": "~8.7.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "jest": "27.2.3",
    "jest-preset-angular": "11.0.0",
    "prettier": "^2.5.1",
    "ts-jest": "27.0.5",
    "supertest": "^6.1.6",
    "typescript": "~4.5.2"
  }
}

**Comment by slewis30328** [comment]
After more research into this issue, pretty sure it's related to the number of files nx is trying to consume.  I added another library to the workspace and removed the directory of files that contain the long names and now ENAMETOOLOONG occurs for all commands except list.  Trying to convert an existing project from an older nx workspace and dead in the water at this point.   Would appreciate any assistance or work-around(s).

**Comment by devBarbar** [comment]
I unfortunatly have the same Issue

**Comment by FrozenPandaz** [comment]
Sorry, could someone please provide a repo that we can use to reproduce the issue?

**Comment by slewis30328** [comment]
Can I send you repo directly?  Do no want available for public viewing.  If not, I will have to make some mods to take stuff out.  Thanks.

**Comment by slewis30328** [comment]
There are too many issues involved with me trying to post the actual repo that is causing this error.

Here is some more info that might help:

**Test 1:**
656 Files in apps and libs directories
3,315,306 Total Byte Size all Files
run command: nx workspace-lint
result: success, works fine

**Test 2:**
Add 1 file to apps or libs directory, anywhere, with 0 byte size
657 Files in apps and libs directories
3,315,306 Total Byte Size all Files
run command: nx workspace-lint
error: **>  NX   spawn ENAMETOOLONG**

When I cross that file count threshold the error is generated. I have created a variety of test workspaces with apps and libs that include stub files > 656 files and can't generate the error.  Frustrating issue to say the least.  It looks like there is a byte size threshold somewhere in one of the libraries/frameworks that is called when the project graph is computed or the lint process runs.  Is there anyway to enable a debugging stream that can pickup/dump where the exception actually occurs?

Would really appreciate any help on this.

Thanks

**Comment by boy51** [comment]
I have the same issue.

Are you by any chance trying to use npm workspaces? I have a feeling nx is consuming multiple node_modules folders.

```
Failed to start the Nx Daemon process.
Messages from the log:
[NX Daemon Server] - 2022-02-16T16:30:56.377Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2022-02-16T16:30:58.196Z - Time taken for 'build project graph' 1810.269ms
[NX Daemon Server] - 2022-02-16T16:30:58.197Z - Time taken for 'write cache' 1.1605ms
[NX Daemon Server] - 2022-02-16T16:30:58.197Z - Time taken for 'total execution time for createProjectGraph()' 1814.7882ms
[NX Daemon Server] - 2022-02-16T16:30:58.199Z - Time taken for 'serialize graph' 1.1626ms
[NX Daemon Server] - 2022-02-16T16:30:59.615Z - [WATCHER]: 2 file(s) created or restored, 1 file(s) modified, 0 file(s) deleted
[NX Daemon Server] - 2022-02-16T16:31:06.053Z - Time taken for 'hash changed files from watcher' 35.8717ms
[NX Daemon Server] - 2022-02-16T16:31:06.054Z - Time taken for 'incremental hashing' 0.0146ms
[NX Daemon Server] - 2022-02-16T16:31:06.055Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2022-02-16T16:31:06.058Z - Time taken for 'build project graph' 0.8722ms
[NX Daemon Server] - 2022-02-16T16:31:06.059Z - Time taken for 'write cache' 0.8733ms
[NX Daemon Server] - 2022-02-16T16:31:06.059Z - Time taken for 'total execution time for createProjectGraph()' 3.4694ms
[NX Daemon Server] - 2022-02-16T16:31:06.060Z - Time taken for 'serialize graph' 0.8839ms
[NX Daemon Server] - 2022-02-16T16:31:09.085Z - [WATCHER]: .prettierrc was modified
[NX Daemon Server] - 2022-02-16T16:31:10.504Z - [WATCHER]: Unsubscribed from changes within: <path>\1645023000\repo
[NX Daemon Server] - 2022-02-16T16:31:10.504Z - Server stopped because: "Lock file changed"

 >  NX   spawn ENAMETOOLONG```

**Comment by boy51** [comment]
Yeah after doing random stuff now it suddenly works again for me.

- For me, no nx command was working, including `nx g rm some-lib`, `nx serve`, `nx lint` 
- After a while I realized that actually `nx build` is working, and it gave me an error saying that I have a `.browserslistrc` and browsers in my `package.json` (not sure if at this point I already did something else to fix it)
- I removed browserslist from my package.json and now I'm not seeing the error anymore.

**Comment by slewis30328** [comment]
As far as I know, I'm using nx workspaces.  I've used older versions of nx workspaces for years, on this same source, and never had issues. Just since I upgraded in the last few weeks, issues surfaced. I uploaded my package.json, nx.json, workspace.json and tsconfig.

Thanks for taking a look...
[projectconfig.zip](https://github.com/nrwl/nx/files/8082325/projectconfig.zip)

**Comment by slewis30328** [comment]
This issue was related to Uncommitted Changes.  Picked up tip through #9037.
