### ISSUE TITLE
Hi, would anyone be able to assist me with the solution to this problem? I've been trying to solve it for a week now and finally decided to get some help. I'm a newbie to coding and the GitHub community so I'd greatly appreciate any help from y'all.

### ISSUE THREAD

**Issue by DaiDai267** [nrwl/nx#8861]
Hi, would anyone be able to assist me with the solution to this problem? I've been trying to solve it for a week now and finally decided to get some help. I'm a newbie to coding and the GitHub community so I'd greatly appreciate any help from y'all. 
Thank you :)

_Originally posted by @DaiDai267 in https://github.com/nrwl/nx/issues/7739#issuecomment-1030600047_

**Comment by geromegrignon** [comment]
Hi, please avoid creating both an issue and a comment about the same problem.
You'll find an answer in the original issue.

**Comment by FrozenPandaz** [comment]
Glad you found your answer! :+1:
