### ISSUE TITLE
Module build failed (from ../../node_modules/@nrwl/web/src/utils/web-babel-loader.js)

### ISSUE THREAD

**Issue by andyjessop** [nrwl/nx#8870]
## Current Behavior
Babel is not compiling TS. I get the following error when trying to run `npx nx serve app`:

```
ERROR in ../event-emitter/src/lib/event-emitter.ts
Module build failed (from ../../node_modules/@nrwl/web/src/utils/web-babel-loader.js):
SyntaxError: /Users/andy/dev/nx-test/packages/event-emitter/src/lib/event-emitter.ts: Unexpected token, expected "(" (6:34)

  4 |  * Create an event emitter.
  5 |  */
> 6 | export function createEventEmitter<
    |                                   ^
  7 |   T extends Record<string, unknown>
  8 | >(): EventEmitter<T> {
```

## Expected Behavior
TS syntax should be recognised correctly.

## Steps to Reproduce
Here is a minimal repository: https://github.com/andyjessop/nx-test

**Comment by andyjessop** [comment]
It seems that if you put a `.babelrc` in the dependency then this works.

I guess every TS library generator should include this file?

**Comment by maxmousse** [comment]
Hi,

It seems I'm running into the same problem: I just generated a react app with @nrwl/react:application and I have syntax errors when running the serve target.

@andyjessop could you please add more details about how you solved this problem ?

**Comment by andyjessop** [comment]
I just added a `.babelrc` into each of my package root directories with these contents:

```json
{
  "presets": ["@nrwl/web/babel"]
}

```

**Comment by andyjessop** [comment]
This is still an issue as I'm running into it on the latest version too.
