### ISSUE TITLE
Setting `workspace.json` causes nx to look at `project.json`

### ISSUE THREAD

**Issue by lughino** [nrwl/nx#8874]
## Current Behavior

I installed a new nx monorepo, using the configurations in `package.json` as explained [here](https://nx.dev/configuration/packagejson).
My packages contain a property `nx` inside the `package.json`.
As explained [here](https://nx.dev/configuration/packagejson#workspace-json), the creation of `workspace.json` is optional but possible with the `package.json` approach instead of the `project.json` one.
However, when I add a `workspace.json` inside the root, every command that I try to run fails with the error:
```sh
ENOENT: no such file or directory, open '/Users/lughino/project/packages/package-a/project.json'
```
When I remove the `workspace.json` file, everything comes back to work normally.
I guess when the workspace file is found, nx just looks for the `project.json` inside each package.

## Expected Behavior

Either be able to set `workspace.json` and use the configuration through `package.json` or remove from [this documentation](https://nx.dev/configuration/packagejson#workspace-json) the section related to setting `workspace.json`.

## Steps to Reproduce

- In any nx monorepo add the `workspace.json` in the root
- ensure to not have `project.json` file inside the packages
- run any command, like `nx build package-a`

### Failure Logs

```sh
ENOENT: no such file or directory, open '/Users/lughino/project/packages/package-a/project.json'
```

### Environment

```sh
 >  NX   Report complete - copy this into the issue template

   Node : 16.13.0
   OS   : darwin x64
   yarn : 1.22.17
   
   nx : 13.7.3
   @nrwl/angular : undefined
   @nrwl/cli : 13.7.3
   @nrwl/cypress : undefined
   @nrwl/detox : undefined
   @nrwl/devkit : 13.7.3
   @nrwl/eslint-plugin-nx : 13.7.3
   @nrwl/express : undefined
   @nrwl/jest : 13.7.3
   @nrwl/js : undefined
   @nrwl/linter : 13.7.3
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : undefined
   @nrwl/tao : 13.7.3
   @nrwl/web : undefined
   @nrwl/workspace : 13.7.3
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by FrozenPandaz** [comment]
I think I understand what you mean by this but could you provide a repo to make reproducing this setup easier please?

**Comment by kitsune7** [comment]
@FrozenPandaz I'm experiencing the same issue in one of my projects. I reproduced the issue using the nx-examples repository [here](https://github.com/nrwl/nx-examples/pull/189).

**Comment by AgentEnder** [comment]
@FrozenPandaz this is working as intended based on when the project inference capabilities were added, if you think it should be expanded to work from package.json as well it would not be terribly hard to add the capability.

LMK what you think, I can implement.

**Comment by airtonix** [comment]
the issue is that the documentation is not clear enough on the nuanced and magical side effects caused by the presence of these files.


Usually documentation challenges like these means that surprising behaviour is hidden in densely wrapped paragraphs of information.

**Comment by mklueh** [comment]
@airtonix I'm facing this as well. It once worked without project.json file and now it complains. All I want to do is run my npm build script inside the package.json, nothing fancy.

**Comment by VincentThomas06** [comment]
if you have a package.json it should not necessary to add another project.json file. But nx almost forces us to have all deps in the root package.json. If you do that, you don't need an package.json (for non-external libs and apps) and you only use the project.json for scripts or nx-specific executors.

**Comment by konsalex** [comment]
Facing the same issue, with a simple `@nrwl/gatsby` example app and a custom added Strapi package, when I try to execute a script as `nx run cms:develop` I get:

`ENOENT: no such file or directory, open '/nous/packages/cms/project.json'`

**Comment by AgentEnder** [comment]
This is expected behavior, and we don't generate workspace.json by default anymore. As such, I'm going to remove this issue.
