### ISSUE TITLE
Don't replace undescore

### ISSUE THREAD

**Issue by moniuch** [nrwl/nx#8875]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Could we allow the underscore character and not convert it to hyphen, please?

```
npx nx generate @nrwl/angular:ngrx --name=user --module=libs/user/src/lib/user.module.ts --directory=_store
```

Output:

```sh
...
CREATE libs/user/src/lib/-store/user.actions.ts
...
```

## Motivation

Underscore is a character usually used for sorting purposes and is absolutely legit. There is no reason to replace it. :)
Further renaming of generated directory (and sometimes imports) is just an unnecessary step in the workflow that could be avoided.

**Comment by moniuch** [comment]
Update: no renaming is involved from what I can see, it is just `dry-run` that wrongly reports the path about to be created. Sorry about that - looks like this could be ngrx domain actually. Please close if so.

**Comment by FrozenPandaz** [comment]
I think that's fair. I think delimiting `_` would still be converted to `-` though.

Would someone like to make a PR? The code is here: https://github.com/nrwl/nx/blob/master/packages/devkit/src/utils/names.ts#L57

**Comment by AloisH** [comment]
Hello I made a PR (my first contribution) following your advice @FrozenPandaz.
Here is the link: [#9870](https://github.com/nrwl/nx/pull/9870)
