### ISSUE TITLE
angular buildable lib can't use "simple library" code

### ISSUE THREAD

**Issue by kkoo95** [nrwl/nx#8879]
## Current Behavior
Using latest nx 13.7, having 2 libraries, one buildable, one plain simple (not buildable); the buildable one fail to compile when importing something from the latter, with the following error: `File xxx/libs/plain/src/lib/plain.module.ts is not under 'rootDir'`.
It happens whether the plain is generated inside the buildable one or not.

## Expected Behavior
From [the doc](https://nx.dev/structure/buildable-and-publishable-libraries), it seems like this setup is not really supported anymore ? Sorry it is unclear to me. Maybe tsconfig should be automatically adjusted to allow such setup ? Maybe prevent/warn about this setup ?

## Steps to Reproduce
1/ create an angular workspace
2/ `$ nx g lib foo --buildable`
3/ `$ nx g lib bar`
4/ import `BarModule` in `FooModule`
5/ `$ ng build --target foo -c production`

**Comment by FrozenPandaz** [comment]
True this is not supported as noted in the doc:

> Note: In order for a buildable library to be pre-compiled, it can only depend on other buildable libraries. This allows you to take full advantage of incremental builds.

The warning is in our `nx-enforce-module-boundaries` lint rule: https://github.com/nrwl/nx-examples/blob/master/.eslintrc.json#L60
