### ISSUE TITLE
Parallel builds consistently wait for unrelated projects

### ISSUE THREAD

**Issue by joneshf** [nrwl/nx#8888]
## Current Behavior

Running in parallel with `nx run-many --target=build --all --parallel=100` consistently waits for unrelated projects to build. For example, if there is one library, four applications, and each application only depends on the one library, it will:
1. Build the library first (this seems correct).
2. Build one of the applications next (this seems incorrect).
3. Build the rest of the applications in parallel (this seems correct given that there are no other dependencies).

The second step seems to be the problem. The rest of the applications are waiting on this first application to finish building, which seems incorrect because they don't depend on that application.

<img width="1792" alt="Screen Shot 2022-02-07 at 08 12 30" src="https://user-images.githubusercontent.com/1356417/152826944-8e09c1d4-9f08-4124-913e-76ef638bfd5f.png">

## Expected Behavior

I naïvely assume that the applications would all be build in parallel. That is:
1. Build the library first.
3. Build the rest of the applications in parallel.

I've only just started experimenting with `nx`, so I don't know if this is a regression in behavior.

## Steps to Reproduce

There's a reproduction available here: https://github.com/joneshf/nx-issue-8888. The `profile.json` is [also available](https://github.com/joneshf/nx-issue-8888/blob/164a6625fff3ffcb55d121082693c39e16acb35e/profile.json) if you'd like to just see the issue without running anything.

I setup that repo by doing the following:

1. Setup the repo:
    ```Console
    $ npm init nx-workspace -- parallel-issue --no-nx-cloud --preset=ts
    $ npx nx generate @nrwl/js:library --name=library-1 --no-interactive
    $ npx nx generate @nrwl/js:application --name=application-1 --no-interactive
    $ npx nx generate @nrwl/js:application --name=application-2 --no-interactive
    $ npx nx generate @nrwl/js:application --name=application-3 --no-interactive
    $ npx nx generate @nrwl/js:application --name=application-4 --no-interactive
    ```
1. Add the library as a dependency in each `packages/application-*/package.json`.
1. Profile the parallel build:
    ```Console
    $ NX_PROFILE=profile.json npx nx run-many --target=build --all --parallel=100 --skip-nx-cache
    ```
1. Load up the profile as shown on https://nx.dev/guides/performance-profiling#how-to-profile-the-performance-of-running-tasks, and you should see that it builds the library, one application, then the rest of the applications in parallel.

### Failure Logs

There don't seem to be any failures, as far as I can tell.

### Environment

```Console
$ npx nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : darwin x64
   npm  : 8.1.2
   
   nx : 13.7.3
   @nrwl/angular : undefined
   @nrwl/cli : 13.7.3
   @nrwl/cypress : undefined
   @nrwl/detox : undefined
   @nrwl/devkit : 13.7.3
   @nrwl/eslint-plugin-nx : 13.7.3
   @nrwl/express : undefined
   @nrwl/jest : 13.7.3
   @nrwl/js : 13.7.3
   @nrwl/linter : 13.7.3
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : undefined
   @nrwl/tao : 13.7.3
   @nrwl/web : undefined
   @nrwl/workspace : 13.7.3
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

(node:57207) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/joneshf/programming/joneshf/nx-issue-8888/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by skrtheboss** [comment]
I tried applying the fix in the https://github.com/nrwl/nx/pull/8840 and it fixes this issue, got this profile:

![image](https://user-images.githubusercontent.com/10209728/152975323-920885b9-1568-45e7-9d54-69357323c6eb.png)

**Comment by joneshf** [comment]
Sweet! I'm glad to hear that that works to fix this issue. Can't wait for it to be merged! Thanks for checking into it.
