### ISSUE TITLE
NX serve and build does not handle multi-configurations as designed in Angular CLI

### ISSUE THREAD

**Issue by raphael22** [nrwl/nx#8904]
Hi !

## Current Behavior
`nx serve` and `nx build` doesn't allow multi-configurations but Angular Cli does.
I get the point that it was in discussion in #4296 and #2839 but it's been a year and nothing show up.

Running command twice as recommended by @vsavkin will not solve my issue.

## Expected Behavior

NX must not broke native cli features !
Configuration need to extendable.
Copy/paste huge chunk of configuration is not a pleasant adventure.

## Steps to Reproduce
- Define a base and dev configuration
- Try to consume both as allowed by NG
- `"dev": {
          "browserTarget": "shell:build:base,dev"
        },`

### Environment
Windows 10 - WSL Ubuntu
NX 13.7.3
Node 16

**Comment by FrozenPandaz** [comment]
Someone will take a look at https://github.com/nrwl/nx/issues/2839. I'll close this issue as a duplicate.
