### ISSUE TITLE
Jest NX monorepo single setupFiles ignored

### ISSUE THREAD

**Issue by GalDayan** [nrwl/nx#8905]
### Documentation issue

- [x] Documentation improvement

Hey there, I'm trying to use Jest in our monorepo and setupFile in one config. I expect this to be reflected in my existing and new (generated) test configs. I saw that there is an option to use [Jest projects](https://jestjs.io/docs/configuration#projects-arraystring--projectconfig) but seems it does nothing. 

I need your help with how to configure better our dev environment for this specific case.

### ROOT jest.config.js
```
const { getJestProjects } = require('@nrwl/jest');

module.exports = {
	projects: getJestProjects(),
	testEnvironment: 'node',
	setupFiles: ['<rootDir>/setupJest.js'],
};
```

### one of our libs jest.config.js
```
module.exports = {
	displayName: 'utils-email',
	preset: '../../../jest.preset.js',
	globals: {
		'ts-jest': {
			tsconfig: '<rootDir>/tsconfig.spec.json',
		},
	},
	transform: {
		'^.+\\.[tj]sx?$': 'ts-jest',
	},
	moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
	coverageDirectory: '../../../coverage/libs/utils/email',
};

```

**Comment by FrozenPandaz** [comment]
Hi sorry for the confusion.

You need to put the config:
```js
	testEnvironment: 'node',
	setupFiles: ['<rootDir>/setupJest.js'],
```

inside `/jest.preset.js` which is the configuration that is extended by all of the projects.

**Comment by wguerram** [comment]
Hi, I think an issue I'm having might be related.

I've this config in my project

setupJest.js
`
import '@testing-library/jest-dom';
import '@testing-library/jest-dom/extend-expect';
`

I added to jest.preset.js
`
const nxPreset = require('@nrwl/jest/preset').default;

module.exports = {
  ...nxPreset,
  setupFiles: ['<rootDir>/setupJest.js'],
  setupFilesAfterEnv: ['<rootDir>/setupJest.js'],
};
`

When running tests I get the error

ReferenceError: expect is not defined

If I import the files 
`
import '@testing-library/jest-dom';
import '@testing-library/jest-dom/extend-expect';
`
in my spec files I don't get the error. I don't want to individually import those files but use them globally.

I'm trying to use the method toBeInTheDocument

Could you please help me.
