### ISSUE TITLE
Buildable libraries dependent upon shared libraries

### ISSUE THREAD

**Issue by ThomasBurleson** [nrwl/nx#8912]
In Nx  (v13.8.x), how can I have a buildable library that is dependent upon another shared library?

## Scenario: 

I have two libraries:

 1) React App 'a1'
 2) React lib 'r1': buildable, publishable
 3) JS lib 'ts1'; typescript only, not buildable, not publishable

#### Dependency:

* a1 -> r1 -> ts1  (when building app)
* r1 -> ts1   (when build r1)

When I build the application `a1`, then the compile and bundling all work!
When I attempt to build `r1` directly, I get a 'rootDir' error:

## Error 

Error during bundle: Error: 

```console
libs/r1/src/lib/libs-r1.tsx(2,23): semantic error TS6059: File 
'libs/ts1/src/index.ts' is not under 'rootDir' 'libs/r1/src'. 

'rootDir' is expected to contain all source files.
```

**Comment by ThomasBurleson** [comment]
Note: when I make `ts1` buildable, I still get the same error when trying to compile `r1`.

**Comment by ThomasBurleson** [comment]
Does the build output for `r1` include the **code** from `ts1`?

**Comment by FrozenPandaz** [comment]
Hey Thomas, :wave: 

> Question: Does the build output for r1 include the code from ts1?
> Answer: If ts1 is a buildable library, then from r1 deployed package, It appears that ts1 will be considered a peer dependency.

> I would like to allow developers to install EITHER r1 (for React developers) or t1 for TypeScript developers. This means the published r1 or t1 is the only library needed to be installed.

No, the code of `ts1` is not within the output of `r1`.

However, that doesn't necessarily mean they _need_ to be peer dependencies. If `ts1` is some underlying behavior of `r1` that the `r1` user shouldn't be able to swap out for different versions, it should be an actual `dependency`. This means that specifying `r1` in `package.json` will also bring in `ts1` without the developer having to specify `ts1` as a dependency. Yes, both libraries would be installed but the developer only has to specify and maintain their version of `r1`. I think this would be the easiest way to achieve your goal.

**Comment by ThomasBurleson** [comment]
@FrozenPandaz - thank you for responding. After some consideration, I agree this is the most consistent approach:

1) standard use of npm packages
2) `ts1` VERSIONing is consistent with dev expectations.

I do have two questions I will add shortly.

**Comment by vladimirdrayling** [comment]
I have, probably, a similar error:

The `web-client` is not built. Getting following error:

```js
D:\dev\web\bugs\nx-bugs>nx build web-client

   ×    1/2 dependent project tasks failed (see below)
   √    1/2 dependent project tasks succeeded [0 read from cache]

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


> nx run user-feature:build:production

Building Angular Package

------------------------------------------------------------------------------
Building entry point '@nx-bugs/user-feature'
------------------------------------------------------------------------------
libs/user/domain/src/lib/user.service.ts:1:1 - error TS6059: File 'D:/dev/web/bugs/nx-bugs/libs/user/domain/src/lib/user.service.ngtypecheck.ts' is not under 'rootDir' 'D:\dev\web\bugs\nx-bugs\libs\user\feature\src'. 'rootDir' is expected to contain all source files.

1 import { Injectable } from '@angular/core';
  
libs/user/domain/src/lib/user-domain.module.ts:1:1 - error TS6059: File 'D:/dev/web/bugs/nx-bugs/libs/user/domain/src/lib/user-domain.module.ngtypecheck.ts' is not under 'rootDir' 'D:\dev\web\bugs\nx-bugs\libs\user\feature\src'. 'rootDir' is expected to contain all source files.

1 import { NgModule } from '@angular/core';
  
libs/user/domain/src/lib/user-domain.module.ts:2:29 - error TS6059: File 'D:/dev/web/bugs/nx-bugs/libs/user/domain/src/lib/user.service.ts' is not under 'rootDir' 'D:\dev\web\bugs\nx-bugs\libs\user\feature\src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Imported via './user.service' from file 'D:/dev/web/bugs/nx-bugs/libs/user/domain/src/lib/user-domain.module.ts'
    Imported via './lib/user.service' from file 'D:/dev/web/bugs/nx-bugs/libs/user/domain/src/index.ts'

2 import { UserService } from './user.service';
                              ~~~~~~~~~~~~~~~~

  libs/user/domain/src/index.ts:2:15
    2 export * from './lib/user.service';
                    ~~~~~~~~~~~~~~~~~~~~
    File is included via import here.
libs/user/domain/src/index.ts:1:1 - error TS6059: File 'D:/dev/web/bugs/nx-bugs/libs/user/domain/src/index.ngtypecheck.ts' is not under 'rootDir' 'D:\dev\web\bugs\nx-bugs\libs\user\feature\src'. 'rootDir' is expected to contain all source files.

1 export * from './lib/user-domain.module';
 
libs/user/domain/src/index.ts:1:15 - error TS6059: File 'D:/dev/web/bugs/nx-bugs/libs/user/domain/src/lib/user-domain.module.ts' is not under 'rootDir' 'D:\dev\web\bugs\nx-bugs\libs\user\feature\src'. 'rootDir' is expected to contain all source files.

1 export * from './lib/user-domain.module';
                ~~~~~~~~~~~~~~~~~~~~~~~~~~
libs/user/feature/src/lib/user-feature.module.ts:4:34 - error TS6059: File 'D:/dev/web/bugs/nx-bugs/libs/user/domain/src/index.ts' is not under 'rootDir' 'D:\dev\web\bugs\nx-bugs\libs\user\feature\src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Imported via '@nx-bugs/user/domain' from file 'D:/dev/web/bugs/nx-bugs/libs/user/feature/src/lib/user-feature.module.ts'
    Imported via '@nx-bugs/user/domain' from file 'D:/dev/web/bugs/nx-bugs/libs/user/feature/src/lib/user-list.component.ts'

4 import { UserDomainModule } from '@nx-bugs/user/domain';
                                   ~~~~~~~~~~~~~~~~~~~~~~

  libs/user/feature/src/lib/user-list.component.ts:2:29
    2 import { UserService } from '@nx-bugs/user/domain';
                                  ~~~~~~~~~~~~~~~~~~~~~~
    File is included via import here.


 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Ran target build for project web-client and 2 task(s) it depends on (9s)

    ×    1/2 failed
    √    1/2 succeeded [0 read from cache]
```

Hope someone can help me. Thank you in advance! 🙏

**Comment by smasala** [comment]
For the record: it's also important that path names do not have more than one `/`. For example: `@org/api/user` will fail, although the `package.json` they may be named correctly as `@org/api-user`.

**Comment by B1Z1** [comment]
Hi @cre8, this solution doesn't help. Every time when I delete cache, other libraries blow up in the same way. The workaround is to build every broken library separately and turn on the watch once again. Does someone know another way to fix this bug? We have 200+ libraries and it's terrifying that we cannot build them normally

**Comment by nhhockeyplayer** [comment]
This one is really shutting me down...

got large repo if committers are interested ask to be collaborator

but I have slew of 

- shared-feature libraries
- shared-root-data-access library (ngrx stores for all features)

I cannot do anything at the IOC level (dependency injection) because the build system cannot handle the imports

So I re-iterate on this ticket... 

- how can I have a buildable library that is dependent upon another shared library?

or in my case

- how can I have a shared library that is dependent upon another shared library?

still researching this one out and dire for a solution I had to fake installation of my lib packages using the `file://` protocol to this point

field is desperate for resolve
