### ISSUE TITLE
Allow overriding generator template files

### ISSUE THREAD

**Issue by jacob-israel-turner** [nrwl/nx#8914]
- [x] I'd _potentially_ be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Users should have the ability to replace the template files for generators. In some cases, the output files need small modifications in order to adhere to style guide requirements.  The ability to copy the template file and make those slight modifications, while still utilizing the generator pipeline, would make this process trivial.

## Motivation
I was excited to use the `@nx/react:component` and `@nx/react:component-story` generators to quickly scaffold new components in my project. I even created a small workspace generator to compose the two, so developers only have to call `yarn generate:component` and both the component and component-story generators run in one command.

However, I was frustrated that my team members would need to immediately modify the output files and bring them up-to-par with linting rules. To fix this, I ended up copying the NX implementation of those two generators, and made very slight modifications to the template files. It worked, but took much longer than it needed to.

## Suggested Implementation
I apologize, I don't know the internals well enough to know exactly how this would work. But I have an idea of how a consumer could use this.

Extend the generator framework. Every generator takes a `templateOverrideDirectory` argument. Any consumer can provide an override directory filled with templates they want to use.  The exact same variables will be injected. Every generator also takes a `skipTemplate` argument - an array of template file names that the consumer would like to skip, if they exist in the target generator.

The `generateFiles` function will still take the files directory as an argument.  However, if a file with the name exists within the override directory provided by the consumer, it is used instead of the template within the directory provided by the source generator. If there is no duplicated file, but the file name matches an entry in the `skipTemplate` list, it is skipped.  This allows the consumer to effectively rename or even completely reorganize the file structure. If there is no override file and no match in the `skipTemplate` list, then the file is generated as usual.

It would be really nice to expand generator documentation as a part of this. I would like for consumers to know which files are created from the generator (including the ability to copy the template, so they can easily copy and modify), and which variables are available for injection into templates.  I'm not sure if these could be grabbed dynamically.

## Alternate Implementations
This could be implemented on a per-generator basis. This seems like a lot more work. It could take longer to release and/or result in fewer generators providing this functionality. But if there are technical limitations with my proposal, then this could work.

**Comment by FrozenPandaz** [comment]
The best way to do this for your workspace is to create a [`workspace-generator`](https://nx.dev/generators/workspace-generators). With this, you can compose our behavior and modify the files before they are generated.

```ts
import { Tree } from '@nrwl/devkit';
import { componentGenerator } from '@nrwl/react';

export default function(tree: Tree, options: any) {
  // This will do the same thing as `nx g @nrwl/react:component ...`
  await componentGenerator(options);
  
  // Write new content before it is generated to disk
  tree.write('path_to_update', newContent);
}

```

**Comment by jacob-israel-turner** [comment]
Hi @FrozenPandaz! Thanks for responding.

Unfortunately, it doesn't seem there's an easy way to _replace_ the template for a pre-built generator. For example, with `componentGenerator`, I'd like to simply replace the template files that it uses, but continue to use the logic driven by the generator itself. Modifying a set of files _after_ they've already been generated seems like a lot more work and would likely be much more brittle to maintain.

It would be a much better developer experience to have the capability to completely override the template for `componentGenerator`.

**Comment by jacob-israel-turner** [comment]
Here is my workspace generator file:
```
import {
  Tree,
  formatFiles,
  names,
} from '@nrwl/devkit';
import { componentStoryGenerator } from '../_generate-component-story/component-story';
import { componentGenerator } from '../_generate-component/component';

interface Schema {
  name: string;
}

export default async function GenerateComponent(tree: Tree, schema: Schema) {
  const { fileName } = names(schema.name);
  await componentGenerator(tree, {
    name: schema.name,
    project: 'components',
    export: true,
    style: 'css',
  });
  await componentStoryGenerator(tree, {
    project: 'components',
    componentPath: `lib/${fileName}/${fileName}.tsx`,
  });
  await formatFiles(tree);
}
```

`_generate-component-story` and `_generate-component` are completely forked versions of the component and component-story generators provided by NX. I had to completely replace them, because I wanted the underlying templates it uses to be different. The folder structure is different and the files themselves are different (due mostly to a difference in linting rules).

Instead of having to go through the effort of _forking_ a generator, I want to be able to use the same generator and provide different templating files.

Hopefully this clarifies what I'm aiming to do.

**Comment by jacob-israel-turner** [comment]
@FrozenPandaz can this ticket be re-opened please? I don't feel the request has been understood or addressed.

**Comment by aaronmcadam** [comment]
I'm trying to do the same as @jacob-israel-turner. I don't want to have to reimplement the generator just to make some small changes to the template.

**Comment by aaronmcadam** [comment]
@jacob-israel-turner Here's my custom generator based on the built in one. My needs are very simple, I don't need all the extra options. But this might help you get started:

```ts
import {
  formatFiles,
  generateFiles,
  getProjects,
  joinPathFragments,
  names,
  Tree,
} from '@nrwl/devkit';

interface Schema {
  name: string;
  project: string;
}

export default async function (tree: Tree, schema: Schema) {
  const project = getProjects(tree).get(schema.project);
  const { className, fileName } = names(schema.name);
  const destinationDir = getDirectory(tree, schema, fileName);
  const templateDir = joinPathFragments(__dirname, './files');
  const outputDir = joinPathFragments(project.sourceRoot, destinationDir);

  generateFiles(tree, templateDir, outputDir, {
    name: schema.name,
    fileName,
    className,
    // We use `__tmpl__` at the end of the template file extension to avoid TypeScript type checking them.
    // So we need to set it to an empty string to remove it from the output filename.
    tmpl: '',
  });

  await formatFiles(tree);
}

function getDirectory(host: Tree, schema: Schema, fileName: string) {
  const workspace = getProjects(host);
  const baseDir =
    workspace.get(schema.project).projectType === 'application' ? 'app' : 'lib';

  return joinPathFragments(baseDir, fileName);
}
```

**Comment by mkurczewski** [comment]
Having the same issue. I even proposed a simpler solution for that https://github.com/nrwl/nx/issues/9579 and also nothing.  I'm using Nx a while and every new day leads me to believe that this team is a bunch of noobs or has very incompetent boss. Sad that such a great project is so underdeveloped.

I will definitely not use it anymore and do not recommend to other's as well. I'd spare much more time configuring the project by myself once instead of constantly fighting with some Nx's stuff.
