### ISSUE TITLE
Don't perform preset-specific actions in workspace:workspace and workspace:new generators

### ISSUE THREAD

**Issue by luxaritas** [nrwl/nx#8917]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Currently, `@nrwl/workspace:workspace` and `@nrwl/workspace:new` perform a number of actions based on the preset, such as modifying the nx.json, creating the apps/libs/packages directories, adding npm scripts, etc. Instead, these actions should be done in `@nrwl/workspace:preset`

## Motivation
When creating a custom preset via the functionality provided in #8084, this would allow for a preset like core to be extended, while retaining all of its behavior. As currently implemented, `create-nx-workspace` calls `workspace:new`, which in turn calls `workspace:workspace`, then some custom behavior, then gets the preset and runs that. This means if I ran the preset generator in core mode from my preset, it would for example use apps and libs instead of packages.

## Suggested Implementation
Moving the preset-specific code from the workspace and new generators to the preset generator

## Alternate Implementations
- Consolidating these three generators further, so that `create-nx-workspace` _just_ figures out which preset generator to call (or perhaps creating a workspace with the bare minimum necessary to install the necessary generator), and then the preset generator handles everything else, delegating to composed generators.
- As an end-user, not using the preset flag in create-nx-workspace with a custom preset, running it with the intended "base" preset, and then installing the custom plugin and running its preset code (likely what I'll do for now)

**Comment by FrozenPandaz** [comment]
Agreed. Would you like to open a PR moving the functionality?

**Comment by luxaritas** [comment]
I can work on that soon - do you agree that my approach (moving just the preset-specific functionality, rather than further consolidation) is the way to go?

**Comment by luxaritas** [comment]
I believe this is still relevant

**Comment by luxaritas** [comment]
Not stale

**Comment by luxaritas** [comment]
AFAIK still relevant

**Comment by FrozenPandaz** [comment]
> do you agree that my approach (moving just the preset-specific functionality, rather than further consolidation) is the way to go?

Yes, moving the preset-specific functionality will be the easiest way.
