### ISSUE TITLE
Argument stringification causes CLI issues in `run-scripts` with `--verbose`

### ISSUE THREAD

**Issue by j3tan** [nrwl/nx#8918]
## Current Behavior
When using `@nrwl/workspace:run-script` or `@nrwl/workspace:run-commands`, arguments/options get stringified.

Example: `--verbose` becomes `--verbose=true`

This can cause issues for downstream CLIs that are the target of these commands and will often cause failures.

Example with `tsc`:
```
error TS5023: Unknown compiler option '--verbose=true'.
```

## Expected Behavior
Argumentless options should not be automatically stringified or there should be an option to avoid stringification of certain options.

## Steps to Reproduce

Built a minimal test repo for this issue:
https://github.com/j3tan/test-run-scripts

Set up a `project.json` such as:
```json
{
  "root": "packages/foo",
  "sourceRoot": "packages/foo/src",
  "projectType": "library",
  "targets": {
    "build-script": {
      "executor": "@nrwl/workspace:run-script",
      "options": {
        "script": "test-script"
      }
    }
  }
}
```

and a `package.json` with something like:
```json
{
  "name": "foo",
  "version": "1.0.0",
  "scripts": {
    "test-script": "cp ./src/start.js ./src/end.js"
  }
}
```

Then running this command:

```bash
yarn nx run foo:build-script --verbose
```

Also `run-many` passes `--verbose` through causing the same issue,
```bash
yarn nx run-many --target=build-script --all --verbose
```

## Related Code
- [run-scripts stringification](https://github.com/nrwl/nx/blob/91ca67ad6b7b711d003980193fb8b3973cdf60f7/packages/workspace/src/executors/run-script/run-script.impl.ts#L19-L21)
- [run-commands stringification](https://github.com/nrwl/nx/blob/91ca67ad6b7b711d003980193fb8b3973cdf60f7/packages/workspace/src/executors/run-commands/run-commands.impl.ts#L242-L262)

### Failure Logs
Downstream CLI error examples:
```bash
> nx run foo:typecheck --verbose

error TS5023: Unknown compiler option '--verbose=true'.
```

```bash
cp: option '--verbose' doesn't allow an argument
```

### Environment
Node 16.13
NX 13 (generated with `create-nx-workspace`)

**Comment by amized** [comment]
I'm trying to run nx build on a next js app (the app was already built prior to using nx).

When I run
```
yarn nx run consumer-app:build --verbose
```

I get
```
$ next build --verbose=true
Unknown or unexpected option: --verbose
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 —————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "consumer-app:build" failed

   Failed tasks:

   - consumer-app:build

   Hint: run the command with --verbose for more details.
```

Can anyone help?
