### ISSUE TITLE
Nx extension does not work with latest pnpm and zsh

### ISSUE THREAD

**Issue by nilanjansiromani** [nrwl/nx#8925]
## Current Behavior
nx console extension does not work 
when used with
- pnpm 
- nx 13.8.0

## Expected Behavior
Should work ❤️

## Steps to Reproduce
- Install zsh
- install nvm 
- install pnpm globally
- install the nxconsole extension 
- try running any task
- pnpm is added into the path variables, in my case, 
```
❯ which pnpm
/Users/n0s00jx/.nvm/versions/node/v16.6.2/bin/pnpm

```
![image](https://user-images.githubusercontent.com/49792104/153466304-d7292b91-e233-4518-ae29-b7e7e618d5f2.png)

**Comment by Cammisuli** [comment]
If you run tasks through vscode's task mechanism does it find pnpm there? 

https://code.visualstudio.com/Docs/editor/tasks

Nx Console uses the same internals as that. 

I've seen hard closes and reopens fix this particular issue with vs code as well.

**Comment by nilanjansiromani** [comment]
I dont think the issue is there 
![image](https://user-images.githubusercontent.com/49792104/157889023-636f67e7-b648-4ed4-bebf-040e8ec34329.png)

When I click this job from the workspace.json
The job launched is 
```
/usr/local/bin/zsh '-c', 'pnpm exec nx run pci-functional-wallet:functional --configuration=production'
```

**Comment by nilanjansiromani** [comment]
I presume the problem is zsh shell does not read ~/.zshrc file in a non interactive shell
and since i am using nvm (or volta) the path is defined inside ~/.zshrc

**Comment by nilanjansiromani** [comment]
![image](https://user-images.githubusercontent.com/49792104/157890243-4df06e2d-84fd-4987-9d47-961c7ba10620.png)
the `i` flag needs to be passed which will force the ~/.zshrc file to be read and thereby all is well

**Comment by Cammisuli** [comment]
Try changing the settings for the terminal like mentioned here:
https://github.com/nrwl/nx-console/issues/1207#issuecomment-1025007577

**Comment by nilanjansiromani** [comment]
this works !
Thanks a lot 
```
"terminal.integrated.profiles.osx": {
    "zsh": {
      "path": "zsh",
      "args": ["-i"]
    }
  }
```
