### ISSUE TITLE
nx migrate doesn't respect configured indent_size

### ISSUE THREAD

**Issue by jasongerbes** [nrwl/nx#8928]
## Current Behavior

The `nx migrate` command doesn't respect the configured `indent_size` in `.editorconfig` or `tabWidth` in `.prettierrc`.

When running the `nx migrate` command, the tab spacing `package.json` is set to `2`, regardless of configured tab spacing.

## Expected Behavior

The `nx migrate` command should respect the configured tab spacing.

## Steps to Reproduce

1. Create an empty workspace with an older version of Nx.
2. Set the `indent_size` in `.editorconfig` to `4`.
3. Run `nx format:write` to update the tab spacing of the workspace.
4. Run `nx migrate latest`.
5. Check `package.json`, notice that `nx migrate` has reverted the tab spacing to `2`.

### Failure Logs

N/A

### Environment

```
Node : 16.13.2
OS   : darwin x64
npm  : 8.1.2

nx : 13.8.0
@nrwl/angular : undefined
@nrwl/cli : 13.8.0
@nrwl/cypress : undefined
@nrwl/detox : undefined
@nrwl/devkit : 13.8.1
@nrwl/eslint-plugin-nx : 13.8.0
@nrwl/express : undefined
@nrwl/jest : 13.8.0
@nrwl/js : 13.8.1
@nrwl/linter : 13.8.0
@nrwl/nest : undefined
@nrwl/next : undefined
@nrwl/node : undefined
@nrwl/nx-cloud : undefined
@nrwl/react : undefined
@nrwl/react-native : undefined
@nrwl/schematics : undefined
@nrwl/storybook : undefined
@nrwl/tao : 13.8.0
@nrwl/web : undefined
@nrwl/workspace : 13.8.0
typescript : 4.5.5
rxjs : 6.6.7
---------------------------------------
Community plugins:
```

**Comment by FrozenPandaz** [comment]
We should have `prettier` format the contents of the file before writing it to disk in `nx migrate`.

**Comment by jasongerbes** [comment]
This is also an issue with the `@nrwl/js:convert-to-swc` command

**Comment by jasongerbes** [comment]
@FrozenPandaz any chance this issue could be addressed? We are frequently migrating to the latest Nx version

**Comment by jasongerbes** [comment]
> We should have `prettier` format the contents of the file before writing it to disk in `nx migrate`.

Happy to create a PR for this if you could provide more context

**Comment by jasongerbes** [comment]
This issue still exists in 16.7.4

**Comment by jasongerbes-vista** [comment]
This is still an issue.
