### ISSUE TITLE
Alternative tasks runner cacheDirectory definition in nx.json is ignored

### ISSUE THREAD

**Issue by MaGnaL** [nrwl/nx#8929]
## Current Behavior
`cacheDirectory` property for alternative task runner is ignored.

`yarn nx build library --runner other`

In a workspace with a task runner in nx.json called "other" with a different `cacheDirectory` than the default runner, the cacheDirectory is not used, but the one defined in the default runner (or "node_modules/.cache/nx" if no default is defined).

## Expected Behavior
`cacheDirectory` is not ignored but used for the given targets. All caches and nxdeps.json should be located here. No other directories are touched to handle the nx cache when an alternative task runner definition is used.

## Steps to Reproduce
Reproduction: https://github.com/MaGnaL/reproduction-nx-cache/

`yarn nx build shared-api --runner other`
The above call is using the default cache directory "node_modules/.cache/nx" although an alternative one is defined for runner "other" in nx.json.

### Failure Logs
No failure logs occur.

### Environment

```
   nx : 13.8.1
   @nrwl/angular : 13.8.1
   @nrwl/cli : 13.8.1
   @nrwl/cypress : 13.8.1
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.1
   @nrwl/eslint-plugin-nx : 13.8.1
   @nrwl/express : undefined
   @nrwl/jest : 13.8.1
   @nrwl/js : undefined
   @nrwl/linter : 13.8.1
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.1
   @nrwl/tao : 13.8.1
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.1
   typescript : 4.5.5
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
         @angular/animations: 13.2.2
         @angular/common: 13.2.2
         @angular/compiler: 13.2.2
         @angular/core: 13.2.2
         @angular/forms: 13.2.2
         @angular/platform-browser: 13.2.2
         @angular/platform-browser-dynamic: 13.2.2
         @angular/router: 13.2.2
         @angular-devkit/build-angular: 13.2.3
         @angular/cli: 13.2.3
         @angular/compiler-cli: 13.2.2
         @angular/language-service: 13.2.2

Done in 0.60s.
```

**Comment by MaGnaL** [comment]
Probably introduced in https://github.com/nrwl/nx/commit/75cc52fd480e6097a41097698c29a154d589954d

Works with 13.4.5.

**Comment by styriandev** [comment]
It still does not work correctly as far as I see it. I tested that with the mentioned test repository. 

The code that should read the cache directory property:
```
function readCacheDirectoryProperty(root: string): string | undefined {
  try {
    const nxJson = readJsonFile<NxJsonConfiguration>(join(root, 'nx.json'));
    return nxJson.tasksRunnerOptions.default.options.cacheDirectory;
  } catch {
    return undefined;
  }
}
```

So it takes the default options always. 
However, there is a workaround: You have to define the system enviroment (NX_CACHE_DIRECTORY) and if you do that nx takes that variable to get the cache directory. Important: You have to set the enviroment variable relative, so no full path. 
Tested with **13.9.3**.
As all other options of the tasksRunnerOptions work there should also be a fix for the mentioned point.

**Comment by utsavkapoor** [comment]
I am also suffering from the issue. NX Always read the cacheDirectory defined in default runner. 
I was able to make it work with the workaround but that does not seem like an ideal situation

Would love if we can get this bug resolved. 

Also in the workaround absolute paths worked

**Comment by utsavkapoor** [comment]
@Todberg - You can use `NX_CACHE_DIRECTORY=<cache-directory> nx <target> <package-name>`

**Comment by utsavkapoor** [comment]
up
