### ISSUE TITLE
Tailwind doesn't work with for more than one app

### ISSUE THREAD

**Issue by borgesis95** [nrwl/nx#8930]
## Current Behavior

Good Afternoon, i want to use Tailwind on my applications . To do that I've followed this step: [Using tailwind CSS in React](https://nx.dev/guides/using-tailwind-css-in-react) .

This is my tailwind.config.js

```
const { createGlobPatternsForDependencies } = require('@nrwl/react/tailwind');
const { join } = require('path');

module.exports = {
  purge: {
    enabled: true,
    content: [
      join(__dirname, 'src/**/*.{js,ts,jsx,tsx}'),
      ...createGlobPatternsForDependencies(__dirname),
    ],
  },
  theme: { ... },
  
  variants: {
    extend: {},
  },
  plugins: [],
  corePlugins: {
    preflight: false,
  },
  mode: 'jit',
};

```

Also this is postcss.config.js

```
module.exports = {
  plugins: {
    tailwindcss: { config: './apps/gestione-dpi/tailwind.config.js' },
    autoprefixer: {},
  },
};
```

With just one application it work properly, however when I generate new application , it stop to work with this warning : 

`[createGlobPatternsForDependencies] WARNING: There was no ProjectGraph available to read from, returning an empty array of glob patterns
`

Thanks in advance! :+1: 

### Environment

  ```
    "postcss": "^8.3.11",
    "tailwindcss": "^2.2.17",
    "autoprefixer": "^10.3.7",

```

**Comment by MarcelMalik** [comment]
@borgesis95 It looks like you have the postcss.config.js in the root directory of your nx workspace project and not in the app folder.
In Step 2 you should change to the app directory and create the tailwind.config.js and postcss.config.js inside the app folder. The path in your postcss.config.js should be "tailwindcss: { config: '.i/tailwind.config.js' },"

**Comment by dukakent** [comment]
Sorry If I'm breaking the rules but I have a related question. I use tailwind in angular monorepo and I have tailwind.config.js in each app folder and I see the mentioned warning message. I've debugged the try/catch statement inside `createGlobPatternsForDependencies` function and I see it catches the error "maximum call stack size exceeded". Linter and dep-graph don't say anything about circular dependencies. What's the reliable way to check circular dependencies? Or maybe there is another problem causing the stack size error?
