### ISSUE TITLE
nx serve doesn't respect "buildLibsFromSource"

### ISSUE THREAD

**Issue by ziacik** [nrwl/nx#8942]
## Current Behavior
I have an app with strict:true setting, which uses a lib which is non-strict. To be able to build the app, I've set `"buildLibsFromSource": false` in the app config. That allows me to run `nx build app` without an error. But `nx serve app` still shows errors as if the lib was built during the serve - in strict mode.

## Expected Behavior
`nx serve app` should use the independently built lib sources and finish without error, just like `nx build app` does.

## Steps to Reproduce
1. create a workspace with a @nrwl/web:application and a buildable non-strict @nrwl/node:library.
2. make the app strict in its tsconfig.
3. add a code to the library that does something that wouldn't build in strict mode.
4. use the library in the app
5. set the "buildLibsFromSource" to false in app's project.json
6. run nx serve app

Repro repo:
https://github.com/ziacik/nx-bug-2

### Environment
```
>  NX   Report complete - copy this into the issue template

   Node : 14.17.6
   OS   : linux x64
   npm  : 6.14.15
   
   nx : undefined
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.1
   @nrwl/cypress : 13.8.1
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.1
   @nrwl/eslint-plugin-nx : 13.8.1
   @nrwl/express : undefined
   @nrwl/jest : 13.8.1
   @nrwl/js : 13.8.1
   @nrwl/linter : 13.8.1
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : 13.8.1
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : undefined
   @nrwl/tao : 13.8.1
   @nrwl/web : 13.8.1
   @nrwl/workspace : 13.8.1
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by FrozenPandaz** [comment]
The `@nrwl/web:file-server` executor does that you want. That one invokes the actual `build` and starts a static web server based on the outputs. 

The documentation is here: https://nx.dev/ci/setup-incremental-builds-angular#running-and-serving-incremental-builds

We will work on making the guide generic and not labeled specifically for Angular.

**Comment by ziacik** [comment]
@FrozenPandaz 
Sorry to revisit this, but after some research I still think this is a bug.

Looking at the code here
https://github.com/nrwl/nx/blob/b1e52b67f279c3e772eaf6e553f7f444a19ad34b/packages/web/src/executors/dev-server/dev-server.impl.ts#L82

it looks like the dev-server actually tries to handle this situation by generating a temporary tsconfig with paths remapped.
But the generated tsconfig doesn't seem to be actually used later on and that - I think - is why the serve fails.


P.S.
I tried to use @nrwl/web:file-server, but ran into some other problems. Because of defaultConfiguration=production, the serve target builds production configuration, though I need a development one during serve. I can overcome that by introducing explicit development configuration, but then also NODE_ENV is set to production by webpack plugin, so I have to explicitly set it before calling nx serve. Not quite developer-friendly.
