### ISSUE TITLE
NPM Audit reports vulnerabilities after installing storybook in nx workspace

### ISSUE THREAD

**Issue by mbeckenbach** [nrwl/nx#8947]
I created issue at storybook regarding npm audit. 
When creating a nx workspace with empty preset, adding @nrwl/angular the NPM audit is nice and clean. Until you add @nrwl/storybook. 

https://github.com/storybookjs/storybook/issues/17494

Not sure if it is more connected to nrwl/storybook or the other side. :-)

**Comment by FrozenPandaz** [comment]
This is an indeed an issue for the Storybook repo.

The vulnerable dependencies are brought in by `storybook` dependencies.

I will close this issue since it is not actionable by us.
