### ISSUE TITLE
Daemon error

### ISSUE THREAD

**Issue by qamar2** [nrwl/nx#8950]
## Current Behavior

When running this command:

  nx serve erp  --configuration development --host 0.0.0.0  --disable-host-check

I got this error:

   Log file with the error: ./node_modules/.cache/nx/d/daemon-error.log
   Please file an issue at https://github.com/nrwl/nx
   Nx Daemon is going to be disabled until you run "nx reset".

### Environment

[daemon-error.log](https://github.com/nrwl/nx/files/8055158/daemon-error.log)

**Comment by tcoz** [comment]
I am seeing this as well. 

I run npx create-nx-workspace my-project --profile=react

It seems to complete the creation of the workspace, installs everything etc, but at the very end of the operation it throws this error:

 >  NX   Nx Daemon was not able to compute the project graph.

   > Log file with the error: C:\...etc\daemon-error.log
   > Please file an issue at https://github.com/nrwl/nx
   > Nx Daemon is going to be disabled until you run "nx reset".
   
   So I install the nx cli and run nx reset. That seems to work (I have not tested the workspace fully, but at least the error message says it completed successfully):
   
   C:\Users\...etc>nx reset

 >  NX   Resetting the Nx workspace cache and stopping the Nx Daemon.

   This might take a few minutes.


 >  NX   Daemon Server - Stopped


 >  NX   Successfully reset the Nx workspace.
   
   Note this is on Windows. I've never seen this on my Macs. 

Thanks :)

**Comment by tcoz** [comment]
Update: the issue isn't resolved by running nx reset. 

When I start my-project, the error repeats. 

C:\...etc>nx run my-project:serve

 >  NX   Nx Daemon was not able to compute the project graph.

   Log file with the error: C:\...\my-project\node_modules\.cache\nx\d\daemon-error.log
   Please file an issue at https://github.com/nrwl/nx
   Nx Daemon is going to be disabled until you run "nx reset".
   
   The project does serve, but this error persists whenever your run a command.

**Comment by tcoz** [comment]
For what it's worth, this also appears in the console when I serve the project:

WARNING in DefinePlugin
Conflicting values for 'process.env.NODE_ENV'

I am running node 14.18.1

**Comment by julianess** [comment]
I found out that this has something to do with your workspace setup. If you are using git as version control the project graph internally uses git-base-file-hasher which works fine for both symstems: Windows and MacOS. If you are not using git (e.g. TFVC) the project-graph falls back to a node-based-file-hasher which delivers on Windows paths like "dir\\subdir\\file.ts" instead git-based and node-based hasher on MacOS deliver paths like "dir/subdir/file.ts". With a wrong file path the file is not considered as part of any project and therefore the cache does not have any files inside the projects. @FrozenPandaz this should be fixable quite easily on short term with my description, isn't it?

**Comment by qamar2** [comment]
No, I'm not on Windows, I am on Linux.

**Comment by jeffascript** [comment]
I am also experiencing the same issue especially while starting up a react app, even after running the `nx rest`. I'm using a mac btw

**Comment by moisescer** [comment]
I'm having the same issue when I running the command to create a docker image @nx-tools/nx-docker:build
OS: MacOS

**Comment by SuneRadich** [comment]
> For what it's worth, this also appears in the console when I serve the project:
> 
> WARNING in DefinePlugin Conflicting values for 'process.env.NODE_ENV'
> 
> I am running node 14.18.1

Is this confirmed as being related? I see the DefinePlugin error after migrating to nx 14.1.9, but I am not currently seeing any issues with the daemon.
