### ISSUE TITLE
(next) --statsJson flag

### ISSUE THREAD

**Issue by acentfrio** [nrwl/nx#8962]
## Description

When working on a next js in a NX environment I noticed that a --jsonStats flag was absent which prevents the generation of stats.json file used by webpack bundle analyzer. Is this that will be implemented in the future?
What are the current alternatives to analyze bundle size?

## Motivation

Allows us to generate stats.json used in bundle Inspection

**Comment by rishabh2712** [comment]
The issue still persists

**Comment by Vanguard90** [comment]
Yes, I am having some pain due to this as well.
