### ISSUE TITLE
Can't build publishable lib which depends on other libs

### ISSUE THREAD

**Issue by deeeed** [nrwl/nx#8972]
Similar to [#3518 ](https://github.com/nrwl/nx/issues/3518)

I have been trying to export a CLI app that depends on other internal libs but I am not sure how to replace the dependencies in the created package.json.

libs/cli:
- depends on: libs/sdk 

`libs/sdk` is publishable.

`libs/cli/package.json`:
```
{
  "name": "cli",
  "version": "0.0.1",
  "bin": "src/index.js",
  "main": "src/index.js"
}
```
- I compile `libs/cli` with:
```
nx build cli --with-deps
```

In my `dist/libs/cli` it generates the dependencies for package.json with:
```
{
  "name": "cli",
  "version": "0.0.1",
  "bin": "src/index.js",
  "main": "src/index.js",
  "typings": "./src/index.d.ts",
  "dependencies": {
    "yargs": "^17.3.1",
     ...
    "@fm/sdk": "0.0.1",
  },
  "peerDependencies": {}
}
```
The issue is that my `@fm/sdk` isn't published to npm and needs to be accessed in `@fm/cli`.
I tried to configure my package.json with _moduleAliases:
```
 "_moduleAliases": {
    "@fm/sdk"      : "../sdk"
  }
```
It still doesn't work. and I get:
```
Error: Cannot find module '@fm/sdk'
Require stack:...
 code: 'MODULE_NOT_FOUND',
  requireStack: [...
```

Any help would be much appreciated :)

**Comment by JasonPingAesop** [comment]
Hi @deeeed,

You mentioned `libs/sdk` is publishable but did you publish it to npm? Or are you saying you don't want `libs/sdk` to be published but still can be access from `@fm/cli`

**Comment by FrozenPandaz** [comment]
Hi @deeeed, If `@fm/cli` is publishable and depends on `@fm/sdk`, then `@fm/sdk` should be publishable as well. We don't currently have an easy way to rollup multiple projects into a single package.
