### ISSUE TITLE
After adding @nwrl/workspace to angular 13 project, ng serve gives NX spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by kimwykoff** [nrwl/nx#8974]
## Current Behavior

 > ng serve

 >  NX   Nx Daemon was not able to compute the project graph.

   Log file with the error: C:\dev\myproject\node_modules\.cache\nx\d\daemon-error.log
   Please file an issue at https://github.com/nrwl/nx
   Nx Daemon is going to be disabled until you run "nx reset".

 >  NX   spawn ENAMETOOLONG

## Expected Behavior

I expect to be able to run my angular project as I did before

## Steps to Reproduce

I have an angular project. It was using angular 12.2.9, but I wasn't able to get nx 12 to move the directories into the new structure. nx 13 was able to do it, but I was having this problem with the ENAMETOOLONG, so I decided that to improve my chances, I would upgrade angular to 13 before trying the workspace. This didn't help and I still get the ENAMETOOLONG. Looking into the daemon-error.log file doesn't make it any clearer. It just give the same error message.

I don't think I can give a reproducible example. But I really need to know where to start looking for the problem.

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

I don't know why it says nx is undefined. I have it installed globally: nx@13.8.1
```
 >  NX   Report complete - copy this into the issue template

   Node : 14.15.1
   OS   : win32 x64
   npm  : 6.14.8

   nx : undefined
   @nrwl/angular : 13.8.1
   @nrwl/cli : 13.8.1
   @nrwl/cypress : 13.8.1
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.1
   @nrwl/eslint-plugin-nx : undefined
   @nrwl/express : undefined
   @nrwl/jest : 13.8.1
   @nrwl/js : undefined
   @nrwl/linter : 13.8.1
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.1
   @nrwl/tao : 13.8.1
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.1
   typescript : 4.5.5
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
         @angular/animations: 13.2.2
         @angular/cdk: 12.2.9
         @angular/common: 13.2.2
         @angular/compiler: 13.2.2
         @angular/core: 13.2.2
         @angular/forms: 13.2.2
         @angular/platform-browser: 13.2.2
         @angular/platform-browser-dynamic: 13.2.2
         @angular/router: 13.2.2
         @fortawesome/angular-fontawesome: 0.9.0
         @micro-focus/ux-aspects: 4.7.0
         @ngrx/effects: 12.4.0
         @ngrx/router-store: 12.4.0
         @ngrx/store: 12.4.0
         @ngrx/store-devtools: 12.4.0
         ngx-bootstrap: 6.2.0
         @angular-devkit/build-angular: 13.2.3
         @angular/cli: 13.2.3
         @angular/compiler-cli: 13.2.2
```

**Comment by slewis30328** [comment]
Have same issue.  Posted 12 days ago.  They want a repo.  Waiting to hear from them on ways I can make repo available.  Have some issues with source if I have to make available for public viewing.

https://github.com/nrwl/nx/issues/8834

**Comment by charl-kruger** [comment]
also just created a fresh workspace, added a few angular apps and getting the error trying to run nx cmds like serve or format

**Comment by kimwykoff** [comment]
I ran ng serve again and it's working. I don't know why.
