### ISSUE TITLE
Alternate eslint config file for linting during dev

### ISSUE THREAD

**Issue by Drecula** [nrwl/nx#8982]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.
https://nx.dev/guides/eslint 

### Additional context or description
I would like to use a different eslint config for linting while developing, so my `debugger` and `console.log` statements are not stripped out when I lint my code. 

I could not find anything in the Nx documentation that tells me exactly how to 'point' Nx to a different lint config file

**Comment by FrozenPandaz** [comment]
If you would like point Nx at a different eslint config, you can use this flag: https://nx.dev/linter/eslint#eslintconfig

So you can have a `.eslintrc` for local and point Nx to `.eslintrc-ci` or something like that for CI

I would also recommend instead using `warn` level failures instead of `error` for the rules that you want to be more laxed instead of having separate `.eslintrc` files.

**Comment by timtos** [comment]
I am also having trouble setting up different eslint configurations. In my case, I have a commit hook that executes eslint and as some rules are very expensive, I don't want to check for these. If I understand it correctly, to really speed things up, I need to get rid of 

```
"parserOptions": {
	"project": ["libs/common/tsconfig.*?.json"]
}
```

in this library eslint configuration:

```
{
	"extends": "../../../.eslintrc.json",
	"ignorePatterns": ["!**/*"],
	"overrides": [
		{
			"files": ["*.ts"],
			"extends": ["../../../.eslintrc.angular.json"],
			"parserOptions": {
				"project": ["libs/common/tsconfig.*?.json"]
			}
		},
		{
			"files": ["*.html"],
			"extends": ["../../../.eslintrc.angular-template.json"]
		}
	]
}
```
This is also stated [here](https://nx.dev/guides/eslint#using-eslint-in-nx-workspaces).

Has someone a little hint how something like this could be realized?
