### ISSUE TITLE
Support for Allure reporting tools with Jest

### ISSUE THREAD

**Issue by ng-plex** [nrwl/nx#8992]
## Description
It is possible to run Jest tests using Allure Reporting tools for Angular Libs and Applications?. I tried to add jest-allure or jest-circus-allure-environment packages without success.

## Motivation
Allow to report based on Jira and or some test management tool tickets

## Suggested Implementation
Extend the Jest implementation with support for Allure reporting tools

**Comment by FrozenPandaz** [comment]
I don't think we're interested in adding allure functionality to the `@nrwl/jest` executor but there could certainly be a separate runner by the community for Allure :smile:

**Comment by barbados-clemens** [comment]
as mentioned we aren't looking to add this into `@nrwl/jest` but an opportunity for a community plugin 👍
