### ISSUE TITLE
AppRoutingModule imports RouterModule.forChild instead of forRoot

### ISSUE THREAD

**Issue by beeman** [nrwl/nx#90]
# Issue

The AppRoutingModule that gets generating when creating the a new app with the `--routing` flag imports `RouterModule.forChild()` instead of `RouterModule.forRoot()`.

This causes the following error message:

```
StaticInjectorError[ChildrenOutletContexts]: 
  StaticInjectorError[ChildrenOutletContexts]: 
    NullInjectorError: No provider for ChildrenOutletContexts!
    at _NullInjector.get (core.js:923)
    at resolveToken (core.js:1211)
    at tryResolveToken (core.js:1153)
    at StaticInjector.get (core.js:1024)
    at resolveToken (core.js:1211)
    at tryResolveToken (core.js:1153)
    at StaticInjector.get (core.js:1024)
    at resolveNgModuleDep (core.js:10584)
    at NgModuleRef_.get (core.js:11805)
    at resolveDep (core.js:12301)
```

# Expected behaviour

When generating the app the `RouterModule.forRoot()` should be imported.

# Steps to reproduce

```
> curl -fsSL https://raw.githubusercontent.com/nrwl/nx/master/packages/install/install-next.sh | bash -s angular-next
> cd angular-next
> ng generate app web --routing
> grep for apps/web/src/app/app-routing.module.ts
imports: [RouterModule.forChild(routes)],
```

I've tried to send in a PR but it's not clear yet how to get my local nx repo working when generating apps. Happy on any input so I can start working on it :)

**Comment by jschwarty** [comment]
Thx @beeman for catching this! It has been [fixed](https://github.com/nrwl/nx/commit/409bfff878ca879d9cd6cb06005cf651c09b808b#diff-90b7ded0c89175762081cbca37b5de0e) in version 0.2.0.
