### ISSUE TITLE
`--prefix=prefix` becomes "prefix":"apps/prefix" in angular.json

### ISSUE THREAD

**Issue by logicaroma** [nrwl/nx#900]
`ng generate @nrwl/schematics:app dy --prefix=dy`

When `--prefix` is provided the actual value that is written in angular.json contains `apps/` in the prefix name.
` "prefix": "apps/dy",`

The expected behavior would be:
` "prefix": "dy",`

**Comment by bcabanes** [comment]
Note: Most likely due to https://github.com/nrwl/nx/blob/master/packages/schematics/src/utils/cli-config-utils.ts#L47
