### ISSUE TITLE
Wrong circle CI docs

### ISSUE THREAD

**Issue by joshribakoff-sm** [nrwl/nx#9001]
Apologies for the duplicate issue but the[ previous issue ](https://github.com/nrwl/nx/issues/8810)was closed. My team has followed all the instructions [here](https://nx.dev/ci/monorepo-ci-circle-ci) and [here](https://circleci.com/developer/orbs/orb/nrwl/nx#commands-set-shas) exactly. It's still not working. As mentioned in the previous issue the output of calling `set-shas` is:

```
undefined:1
{:message "Project not found"}
 ^

SyntaxError: Unexpected token : in JSON at position 1
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/circleci/repo/index.js:119:22)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

This is not a very helpful error message. It would be my position the docs are still incomplete or missing (and that this error message could be improved substantially). This also appears to be related to https://github.com/nrwl/nx-orb/issues/2 and we'll try setting the (undocumented) environment variable, but this environment variable is not mentioned anywhere in the docs for the orb or the circleCI docs on the Nx website, and the error message is not super helpful, therefore it would be my position the docs are in fact wrong. It would be my position this is a valid issue, and I'd be happy to even backfill the docs once we establish it is a valid bug. Could I respectfully request my issue not be closed under an assumption we didn't follow the steps? Thanks!

**Comment by joshribakoff-sm** [comment]
From the orb's readme:

> To use this orb with a private repository on your main branch, you need to grant the orb access to your CircleCI API. You can do this by creating an environment variable called CIRCLE_API_TOKEN in the context or the project.
> Note: It should be a user token, not project token.

This information is not present on the Orb's docs, or on the Nx docs.

**Comment by crenus** [comment]
To second off of this, why is a user token required and not a project token? What is needed in this sense other than read access to that projects builds?

**Comment by FrozenPandaz** [comment]
@meeroslav could you take a look at this issue please?

**Comment by meeroslav** [comment]
Thank you @joshribakoff-sm, updating the docs for orb has been on the list for this week. Thank you for pointing out the missing information on the nx docs as well.

**Comment by meeroslav** [comment]
> To second off of this, why is a user token required and not a project token? What is needed in this sense other than read access to that projects builds?

Since the repo is private, it is guarded by user privileges. That's why the user token is needed to grant read rights for CircleCI API calls on the project's pipeline. It might seem a bit counterintuitive to not use project tokens, but that's just the way the CircleCI works.

**Comment by meeroslav** [comment]
Added also information to the Nx orb - https://github.com/nrwl/nx-orb/commit/89660a1c9387f96bee147d231fec025effa00945

Thank you!

**Comment by joshribakoff-sm** [comment]
Thank you so much, on behalf of everyone who will benefit from the improved docs. We did end up getting it working and figured out that context on our own. The orb has been working great, and the design is quite clever.

The only small suggestion I would maybe add is to make it optional, since it's mainly used to handle an edge case (when multiple failed builds happen in succession, the "affected" apps & libs should accumulate over time and be applied to the next build that succeeds). Perhaps this could even be an opt-in feature to ease the setup even more :)

**Comment by meeroslav** [comment]
Do you mean marking it as optional in the docs? 
The docs already refer to orb's details stating why we need this functionality.
Having it opt-in is difficult since you never know when one of your builds might break. If you swallow the error it's already too late.

**Comment by joshribakoff-sm** [comment]
Yes, all the other Nx docs for other CI setups don't have this affordance. It's nice to have, but not strictly "needed". Maybe there could be a way to opt out if people are absolutely sure they don't want it, or at the very least a more friendly error message in addition to the docs :)

My use case was that we were early prototyping, and not deploying at all was worse than sometimes not deploying :)

**Comment by meeroslav** [comment]
Perhaps the docs are misleading. You **don't**  have to use this orb. You can use the same logic that is mentioned e.g. in the Azure CI.

I will check if we can improve that error message.

Thank you for the feedback

**Comment by meeroslav** [comment]
Here is the improved error message: https://github.com/nrwl/nx-orb/pull/15

**Comment by smallstepstoday** [comment]
It would be helpful to know specifically which scopes are needed in the user token in order to make this work. Are you able to provide a list of those scopes that are needed?
