### ISSUE TITLE
Build does not fail after migrating from CRA to nx when a library has a compilation error

### ISSUE THREAD

**Issue by llucarbolus** [nrwl/nx#9003]
## Current Behavior
After migrating a CRA to a nx workspace, I've added a library to it. On the library, I've added a typescript compilation error. When I build or serve the app, there are no errors and everything goes well. However, eslint actually marks the error on VS Code.

## Expected Behavior
If there's a compilation error on a library, the app does not build.

## Steps to Reproduce
1. Create a CRA app (`npx create-react-app my-app --template typescript`)
2. Migrate that app to nx (`cd my-app && npx cra-to-nx`)
3. Add a library to the workspace (`npx nx g @nrwl/workspace:lib data`)
4. Add a typescript compilation error to the library, e.g.:
```typescript
export function data(): string {
  return 5;
}
```
5. Use the `data` function on the app
6. `npx nx build` -> No compilation error / `npx nx start` -> Runs with no problem

### Environment
 ```
 >  NX   Report complete - copy this into the issue template

   Node : 16.13.1
   OS   : linux x64
   npm  : 8.3.0
   
   nx : 13.8.1
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.1
   @nrwl/cypress : 13.8.1
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.1
   @nrwl/eslint-plugin-nx : 13.8.1
   @nrwl/express : undefined
   @nrwl/jest : 13.8.1
   @nrwl/js : 13.8.1
   @nrwl/linter : 13.8.1
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : 13.1.4
   @nrwl/react : 13.8.1
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.1
   @nrwl/tao : 13.8.1
   @nrwl/web : 13.8.1
   @nrwl/workspace : 13.8.1
   typescript : 4.5.5
   rxjs : 6.5.5
   ---------------------------------------
   Community plugins:

```

**Comment by JosepSalvat** [comment]
Same thing happens to me, any workaround?

**Comment by FrozenPandaz** [comment]
I get an error for `build` and for `serve` (in the browser)

```
jason@pop-os ~/p/t/my-app (master) [SIGINT]> nx build
No project name specified. Using default project : my-app

> my-app@0.1.0 build
> BUILD_PATH=../../dist/apps/my-app craco build

Creating an optimized production build...
Failed to compile.

SyntaxError: /home/jason/projects/triage/my-app/libs/data/src/lib/data.ts: Unterminated string constant. (2:10)
  1 | export function data(): string {
> 2 |   return 5';
    |           ^
  3 | }
  4 |


jason@pop-os ~/p/t/my-app (master) [1]> 
```
