### ISSUE TITLE
Please add LICENSE file to @nrwl/nx-cloud package

### ISSUE THREAD

**Issue by Seledrex** [nrwl/nx#9007]
## Current Behavior
The license is currently not included with the package. Additionally, as far as I can see, I cannot find the source code repository for this plugin online either.

## Expected Behavior
The license should be included in the package.

Here is a [link to the license](https://creativecommons.org/licenses/by-nd/3.0/legalcode) that the package.json says the package should be licensed as. Having a plain text version of this added to the package would solve this licensing problem.

## Steps to Reproduce
N/A

### Failure Logs
N/A

### Environment
N/A

**Comment by FrozenPandaz** [comment]
`@nrwl/nx-cloud` is closed source but we should indeed have the `LICENSE` file published. Thank you for reporting this issue.
