### ISSUE TITLE
Ho to debug node-app in VSCode

### ISSUE THREAD

**Issue by mickz18** [nrwl/nx#901]
After launching ng serve my-server and attach debugger I not able to stop on breakpoint in VSCode.
I suppose I must set sourceMapPathOverrides in my launch.json but I didn't succeeded.
Thanks !

**Comment by samtsai** [comment]
What is your folder structure?  And where does your `.vscode` directory live within it?

I had to adjust my `webRoot` property in the `launch.json` to something like this:
`"webRoot": "${workspaceFolder}/apps/app-email"`

Note: `nx` creates applications in a new directory `apps`

**Comment by mickz18** [comment]
I'm trying to debug a server app part so my launch.json look like this for now
        {
            "type": "node",
            "request": "attach",
            "name": "Attach",
            "port": 9229,
            "sourceMaps": true,
        },

webRoot is not allowed for node

**Comment by samtsai** [comment]
This will be fixed with #894
