### ISSUE TITLE
Next.js 12 Output File Tracing Fails to Build

### ISSUE THREAD

**Issue by Miikis** [nrwl/nx#9017]
## Current Behavior
- create a new nx workspace w/ a next.js app
- turn on [next.js output file tracing](https://nextjs.org/docs/advanced-features/output-file-tracing)
- run `nx build --prod`
- build fails w/ the error message saying `dist/apps/haha/.next/standalone/apps/haha/server.js` doesn't exist (it doesn't)

## Expected Behavior

The `standalone` folder should contain a `server.js` file.

## Steps to Reproduce

I've created a repro repo [here](https://github.com/Miikis/nx_next_standalone_repro). Clone & run `yarn nx build --prod` to see error message.

### Failure Logs

```
ENOENT: no such file or directory, open '/nx_next_standalone_repro/dist/apps/haha/.next/standalone/apps/haha/server.js'
```

### Environment
**Output of `next info`**
```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2
```

**Output of `nx report`**
```
   Node : 16.13.1
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 13.8.2
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.2
   @nrwl/cypress : 13.8.2
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.2
   @nrwl/eslint-plugin-nx : 13.8.2
   @nrwl/express : undefined
   @nrwl/jest : 13.8.2
   @nrwl/js : 13.8.2
   @nrwl/linter : 13.8.2
   @nrwl/nest : undefined
   @nrwl/next : 13.8.2
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : 13.8.2
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.2
   @nrwl/tao : 13.8.2
   @nrwl/web : 13.8.2
   @nrwl/workspace : 13.8.2
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by Miikis** [comment]
This actually does seem to be a dependency mismatch issue. The last next.js version that `output-file-tracing` works for is `12.0.7` (which has a known security vulnerability according to snyk). 

Does Nx document supported next.js versions anywhere? Just saw [an issue](https://github.com/nrwl/nx/issues/9018) asking for support for `next.js@12.1.0`, so I'm assuming its not officially supported?

**Comment by palmithor** [comment]
I reproduced a similar issue, including next config for standalone as well, using NX. It'd be very nice if you could see figure out what is wrong (setup or bug?). Thanks in advance.

Next Config:
```
const nextConfig = {
  nx: {
    // Set this to true if you would like to to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: false,
  },
  experimental: {
    outputStandalone: true,
    outputFileTracingRoot: path.join(__dirname, '../../'),
  },
};
```

Readme shows how to reproduce the bug.
https://github.com/palmithor/nextjs-nx-standalone-bug

Error:
```
ENOENT: no such file or directory, open '****/nextjs-nx-standalone-bug/dist/apps/nextjs-nx-standalone-bug/.next/standalone/apps/nextjs-nx-standalone-bug/server.js'
```

**Comment by plusplushq** [comment]
The Caveats section here documents monorepo 

https://nextjs.org/docs/advanced-features/output-file-tracing#caveats
It seems that on monorepo setups `outputStandalone: true,` isn't needed. only  `outputFileTracingRoot: path.join(__dirname, '../../')`

![Screenshot 2022-03-09 at 14 06 23](https://user-images.githubusercontent.com/34548660/157447590-920d8e79-cba9-4c3e-a762-3cd060bbc5b4.png)

**Comment by Miikis** [comment]
@plusplushq  I read that caveat as being a subsequent step to enabling `outputStandalone`. When I tried it without `outputStandalone`, there is no standalone directory generated. Have you tried this and seen it work?

**Comment by always-maap** [comment]
I tried it today and it's working.
```
experimental: {
    outputStandalone: true,
    outputFileTracingRoot: path.join(__dirname, '../../')
  },
```
 
`node apps/web-app/server.js`

**Comment by Miikis** [comment]
@always-maap what's working exactly? Did you try it w/ the repro example above? Did you update any dependencies? That command that you're running at the end `node apps/web-app/server.js` — is `server.js` a custom server you've set up? If so, what does that have to do w/ output-tracing? The `server.js` that's missing above is a file that would normally be generated, on build, in nx's build-output directory.

**Comment by always-maap** [comment]
> @always-maap what's working exactly? Did you try it w/ the repro example above? Did you update any dependencies? That command that you're running at the end `node apps/web-app/server.js` — is `server.js` a custom server you've set up? If so, what does that have to do w/ output-tracing? The `server.js` that's missing above is a file that would normally be generated, on build, in nx's build-output directory.

No, I tested against our org nx project. no, it is not a custom server.
```
nrwl/next: 13.1.3
```

**Comment by Miikis** [comment]
What version of next.js are you using? As far as I can tell, `12.0.7` is the last time output file-tracing worked w/ any version of nx. If that's not the case, do you mind posting a minimal reproduction where it's working?

**Comment by always-maap** [comment]
> What version of next.js are you using? As far as I can tell, `12.0.7` is the last time output file-tracing worked w/ any version of nx. If that's not the case, do you mind posting a minimal reproduction where it's working?

We are using `12.1.0`

**Comment by Miikis** [comment]
just tried dowgrading the repro nx repo above to use `13.1.3` (next.js is already at 12.1.0. same error: it can't find `.next/standalone/apps/<app-name>/server.js`

**Comment by palmithor** [comment]
For those running next.js in docker this is a groundbreaking feature so I would be very happy to have this issue resolved. The docker image will reduce in size by a lot.

In our case it will also reduce the build time very much as we are doing what we can to have the docker image as small as possible, and in order to achieve that we have to do npm install twice, first for the build, and then again for the generated package.json file for this app.

**Comment by Miikis** [comment]
I looked into this a bit more last weekend. It looks like the root-cause might be a race-condition of some sort. The step that writes the tiny server to the `server.js` file located [here](https://github.com/vercel/next.js/blob/canary/packages/next/build/utils.ts#L1222-L1270) is throwing an error because it thinks that file hasn't been created yet. 

On next.js' side, output-file-tracing is working fine (if you `create-next-app` and enable `outputFileTracing`, everything works as expected). So I'm thinking somewhere around [this step](https://github.com/nrwl/nx/blob/master/packages/next/src/executors/build/build.impl.ts#L57), something in nx is maybe removing that `server.js` file.

Hope that helps.

**Comment by Miikis** [comment]
One thing that's interesting: at one point I hard-coded the `distDir` value as an absolute-path inside the next.js codebase (for that build process), and the correct standalone output was generated. Albeit, in the wrong directory lol it put the build output in `apps/<my-app>/<absolute-path-from-home-dir>/<dist-folder-with-correct-standalone>`.

**Comment by palmithor** [comment]
Seems like this isn't gaining any focus? 😔

**Comment by cocamm** [comment]
Changing the outputPath on production configuration works for me:

`"configurations": {
        "production": {
          "outputPath": "apps/<my-app>/dist"
        }
      }`

**Comment by Miikis** [comment]
@cocamm how are you getting that to work for you? doesn't that output the build in your app's directory, where the standalone bundle is several layers deep? are you wrapping the next/build executor in a run-command executor and shuffling that bundle around till everything's in its place?

**Comment by cocamm** [comment]
> @cocamm how are you getting that to work for you? doesn't that output the build in your app's directory, where the standalone bundle is several layers deep? are you wrapping the next/build executor in a run-command executor and shuffling that bundle around till everything's in its place?

Yes, you are right.
But, I will run this command just in the CI step of my workflow and I've made some changes in my Dockerfile to get just the files from this folder. 

I know it is not the best solution, but it was the only way that I could get this working.

**Comment by pstoica** [comment]
Hi all, I was wondering if there was an official fix for this. I'm currently leaving the build inside the Next.js directory (I just added Nx), but I was able to get it working with this Dockerfile (app is named `dashboard`):

```
# Automatically leverage output traces to reduce image size 
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --chown=nextjs:nodejs /packages/dashboard/.next/standalone ./
COPY --chown=nextjs:nodejs /packages/dashboard/.next/static ./packages/dashboard/.next/static
COPY /packages/dashboard/public ./packages/dashboard/public
# These are partially installed for some reason. Remove or it won't work.
RUN rm -rf ./packages/dashboard/node_modules/react
RUN rm -rf ./packages/dashboard/node_modules/next

...

CMD ["node", "./packages/dashboard/server.js"]
```

Pretty weird combination of folders, but I hope it helps someone in the meantime, or reveals the source of the issue.

**Comment by always-maap** [comment]
I post mine maybe it helps

```Dockerfile
FROM docker-repo.url.com/node:v-alpine

COPY dist/apps/zoomit-editorial/.next/standalone app/
# TODO: serve with CDN
COPY dist/apps/zoomit-editorial/public/ app/apps/zoomit-editorial/public/
COPY dist/apps/zoomit-editorial/.next/static app/dist/apps/zoomit-editorial/.next/static/

WORKDIR /app

ENV NODE_ENV production
ENV PORT 4200

CMD ["node", "apps/Editorial/server.js"]
```

**Comment by danr-za** [comment]
Error still exists in 13.9.5

**Comment by palmithor** [comment]
And in `13.9.7`, reproduce the issue by cloning the following [repository](https://github.com/palmithor/nextjs-nx-standalone-bug) and run
```
npm install
npm run build
```

Errror message:
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/1733717/162202024-0073791d-e57b-48ed-9201-36c7b0ce39ed.png">

**Comment by MarcieMarc425** [comment]
<img width="830" alt="Screen Shot 2022-04-09 at 6 05 54 AM" src="https://user-images.githubusercontent.com/32941251/162538174-34036056-7d3e-4615-ab42-5a3d74884ad5.png">

Encountering same issue on Vercel with `@nrwl/next 13.10.1` and `next 12.1.4`. Not sure if I should still continue Next development with nx considering this is pretty much breaking for me on UAT and PROD envs.

**Comment by amized** [comment]
Somewhat related but I'm stuck with an issue running a build command for next js. Config in package json is:
```
"nx": {
    "type": "application",
    "targets": {
      "build": {
        "options": {},
        "configurations": {
          "production": {
            "outputPath": "apps/consumer-app/dist"
          }
        }
      }
    }
  },
```

When I run 
```
yarn nx run consumer-app:build --configuration=production
```

I get the following error:
```
> nx run consumer-app:build:production

$ next build --outputPath=apps/consumer-app/dist
Unknown or unexpected option: --outputPath
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

For some reason nx is passing the `outputPath` cli option into the next build command. Can anyone suggest how I can modify the output path for next js builds?

**Comment by LudovicPelleDMS** [comment]
First of all thank you for your work, so I also came across the same problem, I was able to find a Hack similar to the comments, it is indeed a problem of Path between Nx (root, outputPath) and the standalone of next, 

```
"targets": {
  "build": {
      "executor": "@nrwl/next:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
          "root": "apps/terminal",
          "outputPath": "apps/terminal"
      },
```

and 
 
```
    experimental: {
        outputStandalone: true,
        outputFileTracingRoot: path.join(__dirname, "../../")
    }
```

finish with 
![Capture d’écran 2022-04-15 à 05 54 48](https://user-images.githubusercontent.com/85235286/163515774-15a0fc92-a709-4e90-b372-8f3a1027837b.png)

this standalone functionality is a real "plus value" for the production of minimal image (docker, k8s, ...) I hope you will be able to look into it quickly, thank you

**Comment by fllprbt** [comment]
@always-maap works. awesome!
```
"next": "12.0.7",
"@nrwl/next": "13.7.3"
```

**Comment by ctrlx-altf4** [comment]
changing the output path did the trick. Thanks @LudovicPelleDMS

**Comment by westmark** [comment]
Thanks @LudovicPelleDMS - getting build output now. However, I also get an error message 

`Source and destination must not be the same.`

and the build exits with error code 1. Are you also getting this? Not ideal for CI. Fix can't arrive soon enough

**Comment by LudovicPelleDMS** [comment]
> Thanks @LudovicPelleDMS - getting build output now. However, I also get an error message
> 
> `Source and destination must not be the same.`
> 
> and the build exits with error code 1. Are you also getting this? Not ideal for CI. Fix can't arrive soon enough

Yeah, i got this message too, as i said it's a "hack" , and an experimental feature , deploy on production may be risky (for now it's seems ok for my project , cypress cover my back ^^) 

 Thanks to @pstoica  solution's, you can have the good return code then  moving the "weird" folder structure  (move static and public ) cf @pstoica Dockerfile

**Comment by bboyz269** [comment]
It seems this issue won't be resolved for quite some time. I created a sample repo [nx-next-i18next-standalone](https://github.com/bboyz269/nx-next-i18next-standalone) building a minimal docker image that works with multiple apps nx workspace. Thanks to all comments from this thread!  
There's also next-i18next integration if you're interested.

**Comment by dukemai** [comment]
I have the same problem on Mac with "@nrwl/next": "14.1.7" and "next": "12.1.5". 
In my case I can generate if I update next.config.js as following: outputFileTracingRoot: join(__dirname, './dist/apps/web-app'),
the server.js is generated directly under /dist which is I dont really want

**Comment by Yizhachok** [comment]
Just don't ask how I investigated this and how much time I spend to find out how to fix this.
⚠️ WARNING ⚠️  Next text for people who believe in magic, skeptics, please stop read this text right now.
I warned you.

Steps to get working repo for standalone Next.js server with build using NX CLI.

### Init example workspace (or use your own)
1. Run `npx create-nx-workspace@latest --preset=next` (tested on v14.1.9 workspace)
2. Answers to questions:
✔ Workspace name (e.g., org name): next-test
✔ Application name: site
✔ Default stylesheet format: scss
3. Go to `next.config.js` file and add to config:
```js
experimental: {
    outputStandalone: true,
    outputFileTracingRoot: path.join(__dirname, "../../")
}
```

### Preparation finished, now let's make real magic
Go to `pages/index.tsx` (or any page file) and add this lines (don't ask why, this is MAGIC):
```js
import path from 'path';
path.resolve('./next.config.js');
```
Really can be any js file that can be resolved from current location (even empty). 
This code enough to insert only once.

### Show magic to the world
Run `npm run build`. That's it! No errors!

### Bonus
This is a VERY SIMPLE Docker config that show how to work with this build.
```docker
FROM node:16-alpine AS builder
RUN apk add --no-cache libc6-compat python3 make g++
WORKDIR /build
COPY . .
RUN npm i && npm run build


FROM node:16-alpine AS runner
ARG APP=site
WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs /build/dist/apps/${APP}/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /build/dist/apps/${APP}/.next/static ./dist/apps/${APP}/.next/static
COPY --from=builder --chown=nextjs:nodejs /build/dist/apps/${APP}/public ./apps/${APP}/public

USER nextjs

EXPOSE 3000

ENV NODE_ENV=production
ENV PORT 3000

CMD node apps/${APP}/server.js
```

Thanks to @bboyz269 for working example, from his repository I found the issue why build didn't work on clean project. His repo works because of `next-i18next` lib code.

**Comment by westmark** [comment]
@Yizhachok I tried your magic and it actually worked! Then I wondered, what was the original error message? Because I had forgotten. So I removed the import and resolve in `index.tsx` and... the build worked again! The only other change I made was to change `outputPath` to `dist/apps/myapp`. Just to be sure, I removed the dist folder and the NX cache folder, and the build still worked. 

I'm so confused right now.

**Comment by Yizhachok** [comment]
@westmark I have tested this on a new project, going through steps that described in first message and using `rm -rf ./node_modules/.cache/nx && npm run build` command (and then on my project). Actually, `npm run build` must execute `nx build`. Main hint as I found out is in running `path.resolve` with existing file name. I think this is related somehow to babel process and what it adds when see some dependencies (because if you will try to call `path.join` this will not work).

**Comment by westmark** [comment]
@Yizhachok Yes, I also tried it on a fresh project, and it absolutely works. An interesting tidbit is that resolving `./next.config.js` makes the build succeed, but resolving `../next.config.js`, i.e the _correct_ path relative to `pages/index.tsx`, fails the build.

As for my own project I'm guessing I accidentally "solved" this problem in a similar fashion along the way without realizing it, since I was still using the outputPath-hack so the original error was obscured.

**Comment by Yizhachok** [comment]
@westmark you can even try to resolve `./1.js` file and create empty one near next.config.js and this still will be work. Very interesting behavior and if somebody can use this information to find the root of the problem this will be great. For now for me this solution is enough.

**Comment by ShadiBlitz** [comment]
@Yizhachok solution worked for me. However I had to add some additional option because I got this error `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory` during build time.
These were the following changes : 

in pages/index.tsx
```
const { resolve } = require('path')
resolve('./next.config.js')
```
<br>

in next.config.js
```
const { join } = require('path')

experimental: {
    outputStandalone: true,
    outputFileTracingRoot: join(__dirname, '../../'),
    esmExternals: false,
  },
```

<br>

and update next in package.json to canary
```
"next": "canary",
```
<br>
And the docker build worked great.
However, an official solution has to be done on NX side.. @ndcunningham

**Comment by dwfee** [comment]
Hooray! I almost works! Did what ShadiBlitz stated, but since there was a new version out  I picked "next": "^12.2.0", to comfirm thing work I copied the files to my standalone server and tried with docker. Result it would work if all static files could be read.
Is there a solution?
![image](https://user-images.githubusercontent.com/1276411/176613142-19130c2a-62ff-4a9b-9e55-171172452aff.png)

**Comment by krissetto** [comment]
Has anyone else noticed issues when it comes to the automatic environment variable expansion in the `.env` files when using the `outputStandalone` and `outputFileTracingRoot` options? 

Example from the docs for clarity:
``` .env
# .env
HOSTNAME=localhost
PORT=8080
HOST=http://$HOSTNAME:$PORT
```

Everything else seems ok, but my pages are dying because of incorrect configuration values (my env vars seem to be passed along as simple strings like `$HOSTNAME` instead of actually being substituted)

**Comment by enchorb** [comment]
The steps by @moatorres work great except I had to change:

```
const nextConfig = {
  nx: {
    svgr: false,
  },
  // add the lines below ↓
  experimental: {
    outputStandalone: true,
    outputFileTracingRoot: path.join(__dirname, '../../'),
  }
}
```

to:

```
const nextConfig = {
  nx: {
    svgr: false,
  },
  // add the lines below ↓
  output: 'standalone',
  experimental: {
    outputFileTracingRoot: path.join(__dirname, '../../'),
  }
}
```

**Comment by AlexandreCassagne** [comment]
> ### Preparation finished, now let's make real magic
> Go to `pages/index.tsx` (or any page file) and add this lines (don't ask why, this is MAGIC):
> 
> ```js
> import path from 'path';
> path.resolve('./next.config.js');
> ```

Can confirm this fixed everything for me 😂

**Comment by raymondKelly** [comment]
Unfortunately the above workaround did not work for me while using `nx: 14.5.15 ` and `next:12.2.3`. I'm just going to go without the new functionality for now until their is support for such with nx.

**Comment by bojanbass** [comment]
Unfortunately, none of workarounds work with `nx 14.8.1` and `next 12.3.1`. I've also tried to debug Next CLI and change the output folder, but it looks like .nft files are not generated correctly. For sure the bug is present in NX and should be fixed, as Next standalone works fine.

**Comment by eglove** [comment]
I fixed this problem a few days ago by disabling NX build cache.

`npx nx build my-app --prod  --skip-nx-cache`

I haven't had the issue since I started doing this.

**Comment by bojanbass** [comment]
> 

Skipping NX cache shouldn't make any difference. Are you sure you're building standalone version of Next, have some other configuration in place or use an older version of Next?

**Comment by eglove** [comment]
Shouldn't but does. This issue is not specific to a standalone version.

**Comment by traianrusu1** [comment]
Thanks to the comments above here's what worked for me on "nx": "14.8.3" and "next": "12.3.1".

As Yizhachok said I had to add the following, although I had to add 'output' outside of experimental. Also needed to add `const path = require('path');` to the top of the file.

```
  output: 'standalone',
  experimental: {
    // this includes files from the monorepo base two directories up
    outputFileTracingRoot: path.join(__dirname, '../../'),
  },
```

then in pages/index I added 

```
import path from 'path';
path.resolve('./next.config.js');
```

This wasn't working for me initially so the final thing I had to do was delete my dist folder that I had generated previously and then run the build command with the --skip-nx-cache argument so: `nx build shop-next --skip-nx-cache`. This finally worked and I was able to run the server file in dist/apps/my-app/.next/standalone/apps/my-app/server.js

I think a more proper solution by NX is really necessary as without these workarounds the docker image is 1.5 GB for me.

**Comment by juliolugo96** [comment]
> Thanks to the comments above here's what worked for me on "nx": "14.8.3" and "next": "12.3.1".
> 
> As Yizhachok said I had to add the following, although I had to add 'output' outside of experimental. Also needed to add `const path = require('path');` to the top of the file.
> 
> ```
>   output: 'standalone',
>   experimental: {
>     // this includes files from the monorepo base two directories up
>     outputFileTracingRoot: path.join(__dirname, '../../'),
>   },
> ```
> 
> then in pages/index I added
> 
> ```
> import path from 'path';
> path.resolve('./next.config.js');
> ```
> 
> This wasn't working for me initially so the final thing I had to do was delete my dist folder that I had generated previously and then run the build command with the --skip-nx-cache argument so: `nx build shop-next --skip-nx-cache`. This finally worked and I was able to run the server file in dist/apps/my-app/.next/standalone/apps/my-app/server.js
> 
> I think a more proper solution by NX is really necessary as without these workarounds the docker image is 1.5 GB for me.

This worked perfectly for me! Thank you very much, man!

**Comment by virus2016** [comment]
Hey all,

My standalone build outputs this server.js file 

```Javascript
const NextServer = require('next/dist/server/next-server').default
const http = require('http')
const path = require('path')
process.env.NODE_ENV = 'production'
process.chdir(__dirname)
...
```

However it only outputs this next-server.js file in the node_modules folder

```Javascript

"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.default = void 0;
require("./initialize-require-hook");
require("./node-polyfill-fetch");
require("./node-polyfill-web-streams");
....
```

![image](https://user-images.githubusercontent.com/11227384/202263179-56afb870-055c-4fea-8f25-724400f62449.png)

The server fails to start because required("./initialize-require-hook"); doesn't exist in the node_modules.

Here is my next config file 

```Javascript
//@ts-check

// eslint-disable-next-line @typescript-eslint/no-var-requires
const { withNx } = require('@nrwl/next/plugins/with-nx');
const path = require('path');

/**
 * @type {import('@nrwl/next/plugins/with-nx').WithNxOptions}
 **/
const nextConfig = {

  // outputStandalone: true,
  output: 'standalone',
  experimental: {
    // this includes files from the monorepo base two directories up
    // outputFileTracingRoot: path.join(__dirname, '../../'),
  },


  nx: {

    // Set this to true if you would like to to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: false,
  },
};

module.exports = withNx(nextConfig);
```

Am I missing something?

**Comment by electriccode** [comment]
Looks like the server folder is not copied properly.

After running `nx build myapp --skip-nx-cache`, the `apps/myapp/.next/standalone/node_modules/next/dist/server` folder has significantly less number of files as compared to the a non nx nextjs build created via `npx
 create-next-app --example with-docker nextjs-docker `.

Here are the contents for `apps/myapp/.next/standalone/node_modules/next/dist/server`
```
get-page-files.js next-server.js
htmlescape.js     utils.js
```

Contents for with-docker for `.next/standalone/node_modules/next/dist/server`
```
accept-header.js
api-utils
app-render.js
base-http
base-server.js
body-streams.js
config-shared.js
config-utils.js
config.js
crypto-utils.js
font-utils.js
get-page-files.js
google-font-metrics.json
htmlescape.js
image-optimizer.js
initialize-require-hook.js
internal-utils.js
lib
load-components.js
next-server.js
node-polyfill-fetch.js
node-polyfill-web-streams.js
node-web-streams-helper.js
optimize-amp.js
post-process.js
render-result.js
render.js
request-meta.js
require.js
response-cache
router.js
send-payload
serve-static.js
server-route-utils.js
utils.js
web
```

**Comment by electriccode** [comment]
Upgrading to latest nx fixed the issue

`nx migrate latest`
`npm install`
`npx nx migrate --run-migrations`

**Comment by bntzio** [comment]
> Upgrading to latest nx fixed the issue
> 
> `nx migrate latest` `npm install` `npx nx migrate --run-migrations`

Still not working for me with `"nx": "15.2.4"`

**Comment by damianesteban** [comment]
> Just don't ask how I investigated this and how much time I spend to find out how to fix this. ⚠️ WARNING ⚠️ Next text for people who believe in magic, skeptics, please stop read this text right now. I warned you.
> 
> Steps to get working repo for standalone Next.js server with build using NX CLI.
> 
> ### Init example workspace (or use your own)
> 1. Run `npx create-nx-workspace@latest --preset=next` (tested on v14.1.9 workspace)
> 2. Answers to questions:
>    ✔ Workspace name (e.g., org name): next-test
>    ✔ Application name: site
>    ✔ Default stylesheet format: scss
> 3. Go to `next.config.js` file and add to config:
> 
> ```js
> experimental: {
>     outputStandalone: true,
>     outputFileTracingRoot: path.join(__dirname, "../../")
> }
> ```
> 
> ### Preparation finished, now let's make real magic
> Go to `pages/index.tsx` (or any page file) and add this lines (don't ask why, this is MAGIC):
> 
> ```js
> import path from 'path';
> path.resolve('./next.config.js');
> ```
> 
> Really can be any js file that can be resolved from current location (even empty). This code enough to insert only once.
> 
> ### Show magic to the world
> Run `npm run build`. That's it! No errors!
> 
> ### Bonus
> This is a VERY SIMPLE Docker config that show how to work with this build.
> 
> ```
> FROM node:16-alpine AS builder
> RUN apk add --no-cache libc6-compat python3 make g++
> WORKDIR /build
> COPY . .
> RUN npm i && npm run build
> 
> 
> FROM node:16-alpine AS runner
> ARG APP=site
> WORKDIR /app
> 
> RUN addgroup --system --gid 1001 nodejs
> RUN adduser --system --uid 1001 nextjs
> 
> COPY --from=builder --chown=nextjs:nodejs /build/dist/apps/${APP}/.next/standalone ./
> COPY --from=builder --chown=nextjs:nodejs /build/dist/apps/${APP}/.next/static ./dist/apps/${APP}/.next/static
> COPY --from=builder --chown=nextjs:nodejs /build/dist/apps/${APP}/public ./apps/${APP}/public
> 
> USER nextjs
> 
> EXPOSE 3000
> 
> ENV NODE_ENV=production
> ENV APP_PATH=apps/${APP}/server.js
> ENV PORT 3000
> 
> CMD node $APP_PATH
> ```
> 
> Thanks to @bboyz269 for working example, from his repository I found the issue why build didn't work on clean project. His repo works because of `next-i18next` lib code.

I was unable to get standalone builds working until I followed this. There is no reason why it should be this difficult.

**Comment by moatorres** [comment]
Just a heads up to let you know that the workarounds shared above (and therefore the bug) are also needed in Next 13, except that we should add the below into `app/page.tsx` or whichever root `page.tsx` you have in your project. In my case it sits on `app/(landing)/page.tsx`.

```ts 
import path from 'path'
path.resolve('./next.config.js')
```

Works like a charm.

**Comment by moatorres** [comment]
Just a heads up to let you know that the workaround shared here (and therefore the bug) are also needed in Next 13, except that we should add the below into `app/page.tsx` (or whatever is the root `page.tsx` of your project). In my case it sits on `app/(landing)/page.tsx`.

```ts 
import path from 'path'
path.resolve('./next.config.js')
```

Works like a charm.

**Comment by meightythree** [comment]
> > Just don't ask how I investigated this and how much time I spend to find out how to fix this. ⚠️ WARNING ⚠️ Next text for people who believe in magic, skeptics, please stop read this text right now. I warned you.
> > Steps to get working repo for standalone Next.js server with build using NX CLI.
> > ### Init example workspace (or use your own)
> > 
> > 1. Run `npx create-nx-workspace@latest --preset=next` (tested on v14.1.9 workspace)
> > 2. Answers to questions:
> >    ✔ Workspace name (e.g., org name): next-test
> >    ✔ Application name: site
> >    ✔ Default stylesheet format: scss
> > 3. Go to `next.config.js` file and add to config:
> > 
> > ```js
> > experimental: {
> >     outputStandalone: true,
> >     outputFileTracingRoot: path.join(__dirname, "../../")
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Preparation finished, now let's make real magic
> > Go to `pages/index.tsx` (or any page file) and add this lines (don't ask why, this is MAGIC):
> > ```js
> > import path from 'path';
> > path.resolve('./next.config.js');
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Really can be any js file that can be resolved from current location (even empty). This code enough to insert only once.
> > ### Show magic to the world
> > Run `npm run build`. That's it! No errors!
> > ### Bonus
> > This is a VERY SIMPLE Docker config that show how to work with this build.
> > ```
> > FROM node:16-alpine AS builder
> > RUN apk add --no-cache libc6-compat python3 make g++
> > WORKDIR /build
> > COPY . .
> > RUN npm i && npm run build
> > 
> > 
> > FROM node:16-alpine AS runner
> > ARG APP=site
> > WORKDIR /app
> > 
> > RUN addgroup --system --gid 1001 nodejs
> > RUN adduser --system --uid 1001 nextjs
> > 
> > COPY --from=builder --chown=nextjs:nodejs /build/dist/apps/${APP}/.next/standalone ./
> > COPY --from=builder --chown=nextjs:nodejs /build/dist/apps/${APP}/.next/static ./dist/apps/${APP}/.next/static
> > COPY --from=builder --chown=nextjs:nodejs /build/dist/apps/${APP}/public ./apps/${APP}/public
> > 
> > USER nextjs
> > 
> > EXPOSE 3000
> > 
> > ENV NODE_ENV=production
> > ENV APP_PATH=apps/${APP}/server.js
> > ENV PORT 3000
> > 
> > CMD node $APP_PATH
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks to @bboyz269 for working example, from his repository I found the issue why build didn't work on clean project. His repo works because of `next-i18next` lib code.
> 
> I was unable to get standalone builds working until I followed this. There is no reason why it should be this difficult.

Thanks @damianesteban your solution worked for me!

```
        "next": "13.1.1",
        "nx": "15.8.5",
        "react": "18.2.0",
```

**Comment by salihsagdilek** [comment]
same here.

```
    "next": "13.2.4",
    "@nrwl/next": "15.8.9",
    "nx": "15.8.9",
```


```
[ERROR]: !!! CustomerError: The standalone directory /codebuild/output/src945274832/src/XXX/dist/apps/XXX/.next/standalone is missing a server.js file. This file shoud have been created automatically by NextJS. Make sure you enable output standalone on your next.config.js file or set NEXT_PRIVATE_STANDALONE=true. https://nextjs.org/docs/advanced-features/output-file-tracing#automatically-copying-traced-files
```


```
const nextConfig = {
  output: "standalone",
  typescript: {
    ignoreBuildErrors: true,
  },
  experimental: {
    outputFileTracingRoot: path.join(__dirname, '../../'),
  },
  nx: {
    svgr: true,
  },
};
```

**Comment by moatorres** [comment]
@nowlena Have you tried the workarounds suggested on this thread?

**Comment by nowlena** [comment]
> @nowlena Have you tried the workarounds suggested on this thread?

Yes, I'm not being lazy here, I'm unable to find a working solution.

**Comment by moatorres** [comment]
> > @nowlena Have you tried the workarounds suggested on this thread?
> 
> Yes, I'm not being lazy here, I'm unable to find a working solution.

I'm not implying that either, but since I did share workarounds above for both Next 12 and 13, I find it fairly difficult to help you without any inputs other than "I've been trying to resolve this all day without luck. Is there any way to get eyes on this?" 😕

What have you tried? What is the structure of your workspace? Are you using the default 'dist' path? What error messages are you catching? Are you using Next 12 or 13? Have you added the suggested "import path from 'path'"? On which file? I understand your frustration. Hence why I'm here replying to you.

**Comment by dnyn92** [comment]
I have the same issue as @salihsagdilek 
    "next": "13.3.0",
    "@nrwl/next": "15.9.1",
    "nx": "15.9.1",
```

**Comment by breningham** [comment]
Just want to add my penny's-worth, using the above workarounds does create the server.js, but it does not work, manually updating the server.js to replace the `NextServer`'s configuration `conf.distDir` value from "./../../../dist/apps/[app-path]/.next" just ".next" allows it to work

i'm just wondering if this is possible what's blocking it from working initially without the workarounds

**Comment by yusijs** [comment]
I'm seeing the same as @breningham, but I need to change `conf.distDir` from `./../../dist/apps/frontend/.next` to `"./../../.."`

This is kind of making the nx plugin a pain to use, instead of doing what it's meant to do (simplify development for mono-repos). We have multiple applications being built, and previously (using angular) we've been able to create minimal docker-images by building everything outside and only copying what is required. The only feasible "solution" I'm seeing here is doing a full build within the dockerfile for the client, which both slows down the build and bloats the dockerfile. :/

**Comment by ild0tt0re** [comment]
Probably Nx v16.3.0 will fix this issue thanks to the direct use of nextjs cli and API instead of nx wrappers
