### ISSUE TITLE
secondary entry points for workspace/node library

### ISSUE THREAD

**Issue by wizardnet972** [nrwl/nx#9035]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
 
I would like to create a lib that contains angular and nodejs code like so:

```
products <-- workspace/nodejs package
  api  <--- node package (server)
  data-access <-- angular package (angular services only)
  feature-dashboard <-- angular package
  ui-dashboard <-- angular package 
  src
    lib <-- common things that shared between nodejs and angular (server and client) models, utils...
      entity-model.ts
       ...
   package.json

Imports:

import { entityModel } from '@org/products'; <--- I can import only the src folder.
import { ... } from '@org/products/api';  <--- I can import only the api folder.
import { ... } from '@org/products/feature-dashboard';
```

## Motivation

I have been trying to get on board using wrap those libraries with a directory - which is a good solution. 
But I think it's better implementation and better code structure in order to wrap the angular and nodejs code together.
And this way I can import things from the correct folders.

## Suggested Implementation

just add secondary entry points to nodejs/workspace schematics - they should act just like angular secondary entry points that create the lib inside another lib, and add paths to tsconfig.

**Comment by FrozenPandaz** [comment]
You are free to add more path mappings into `tsconfig.base.json`. Nx will parse those dependencies as well. All of the imports of those secondary entry points will create dependencies to the same project as those are all secondary entry points of the same project.

Is there anything else that you need?
