### ISSUE TITLE
Can not start application due to  >  NX   spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by jizang58** [nrwl/nx#9037]
I have a nrwl/nx angular application when I am trying to start I am getting the errors explaing below, this is my package.json:

```
{
  "name": "moniesta-admin",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "postinstall": "node ./decorate-angular-cli.js && ngcc --properties es2015 browser module main",
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.2.0",
    "@angular/cdk": "^13.0.0",
    "@angular/common": "~13.2.0",
    "@angular/compiler": "~13.2.0",
    "@angular/core": "~13.2.0",
    "@angular/forms": "~13.2.0",
    "@angular/localize": "~13.2.0",
    "@angular/material": "^13.2.2",
    "@angular/platform-browser": "~13.2.0",
    "@angular/platform-browser-dynamic": "~13.2.0",
    "@angular/router": "~13.2.0",
    "@nebular/auth": "^9.0.1",
    "@nebular/eva-icons": "^9.0.1",
    "@nebular/theme": "^9.0.1",
    "@ng-bootstrap/ng-bootstrap": "^11.0.0",
    "@nrwl/angular": "13.8.3",
    "bootstrap": "^5.1.3",
    "eva-icons": "^1.1.3",
    "rxjs": "~7.4.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.2.0",
    "@angular-eslint/eslint-plugin": "~13.0.1",
    "@angular-eslint/eslint-plugin-template": "~13.0.1",
    "@angular-eslint/template-parser": "~13.0.1",
    "@angular/cli": "~13.2.0",
    "@angular/compiler-cli": "~13.2.0",
    "@angular/language-service": "~13.2.0",
    "@nrwl/cli": "13.8.3",
    "@nrwl/cypress": "13.8.3",
    "@nrwl/eslint-plugin-nx": "13.8.3",
    "@nrwl/jest": "13.8.3",
    "@nrwl/linter": "13.8.3",
    "@nrwl/tao": "13.8.3",
    "@nrwl/workspace": "13.8.3",
    "@schematics/angular": "~13.2.0",
    "@types/jest": "27.0.2",
    "@types/node": "16.11.7",
    "@typescript-eslint/eslint-plugin": "~5.10.0",
    "@typescript-eslint/parser": "~5.10.0",
    "cypress": "^9.1.0",
    "eslint": "~8.7.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "jest": "27.2.3",
    "jest-preset-angular": "11.1.1",
    "prettier": "^2.5.1",
    "ts-jest": "27.0.5",
    "typescript": "~4.5.2"
  }
}
```

## Current Behavior
When trying to run npm run start I am getting the following error:
 >  NX   spawn ENAMETOOLONG

## Expected Behavior
My application starts when I enter the npm run start command.

## Steps to Reproduce
Generate an nrwl/nx Angular application and try to execute the npm run start command
### Failure Logs
 >  NX   spawn ENAMETOOLONG

### Environment
I am using vs code and hav npm lts version and nrwl the latest version. My application worked a week ago, when I had generated it.

**Comment by jizang58** [comment]
does no one have an answer for this?

**Comment by slewis30328** [comment]
Logged this issue 17 days ago. They wanted a repo, but I have security issues posting mine. If you have a repo to post, that would be great. This issue has caused me major problems with upgrade. Would really like to move forward, but I'm out of options at this point. I've tried creating stub repos to trigger error and I can't. It has something to do with allocation/threshold/high-water mark type logic. I can trigger error in my repo by going increasing file count in apps and libs directory. Just a reminder, pretty sure you have to run nx reset after error is triggered. If you don't, it will continue regardless of changes you make.

**Comment by michael-golden** [comment]
I believe this is an issue related to uncommitted changes.  I get this error when I have changes that have not been checked in. (not sure how the error originates).  However, after committing the changes, the error resolves.

**Comment by AgentEnder** [comment]
This should be resolved by #8965, just need to test it against a sample repo. I'm going to close this since its a duplicate of #8684

**Comment by slewis30328** [comment]
Michael,
Thanks for the info!  That was issue.  Really appreciate your help.
Steve

    On Tuesday, February 22, 2022, 10:26:23 AM CST, Michael ***@***.***> wrote:  
 
 


I believe this is an issue related to uncommitted changes. I get this error when I have changes that have not been checked in. (not sure how the error originates). However, after committing the changes, the error resolves.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KamranTaghaddos** [comment]
I had the same issue and solve it like this:

**First:** Updating Nx to version 13.8.5. Do as below:

1. Run command: _nx migrate @nrwl/workspace@13.8.5_
2. Run command: _npm install_
3. Run command: _nx migrate --run-migrations_
4. Remove "migrations.json" file in nx workspace root directory

**Second:** Re-install npm globally based on nx version 13.8.5. Do as below:

1. Run command: _npm i -g nx@13.8.5_

**Comment by Abdullah-Shahen** [comment]
> I had the same issue. I noticed I had 4k changes in my working copy. They were appearing because the `.angular` folder was not git-ignored. I added `.angular/` to my _.gitignore_ and it solved the issue.

You saved the day. Thanks.

**Comment by backup01** [comment]
> I believe this is an issue related to uncommitted changes. I get this error when I have changes that have not been checked in. (not sure how the error originates). However, after committing the changes, the error resolves.

In my case the reason was as @michael-golden described, but the root cause of the problem was not so obvious. I defined a local directory for a project and initialized local repo, then downloaded the project from remote repo into the directory and connected local repo with remote repo. As a result, i had nothing to commit, since i changed nothing, but `git status` showed that all of the files are not staged for furhter commit. And `nx serve..` returned `spawn ENAMETOOLONG`.

For me the solution was deletion whole project directory, downloading some client for version control system (for example, TortoiseGit) and clone the project from remote repo using the client and providing a link of the remote repo to it. In this case nx serve works perfectly.

**Comment by Thomaskfang** [comment]
> I have a nrwl/nx angular application when I am trying to start I am getting the errors explaing below, this is my package.json:
> 
> ```
> {
>   "name": "moniesta-admin",
>   "version": "0.0.0",
>   "license": "MIT",
>   "scripts": {
>     "ng": "ng",
>     "postinstall": "node ./decorate-angular-cli.js && ngcc --properties es2015 browser module main",
>     "start": "nx serve",
>     "build": "nx build",
>     "test": "nx test"
>   },
>   "private": true,
>   "dependencies": {
>     "@angular/animations": "~13.2.0",
>     "@angular/cdk": "^13.0.0",
>     "@angular/common": "~13.2.0",
>     "@angular/compiler": "~13.2.0",
>     "@angular/core": "~13.2.0",
>     "@angular/forms": "~13.2.0",
>     "@angular/localize": "~13.2.0",
>     "@angular/material": "^13.2.2",
>     "@angular/platform-browser": "~13.2.0",
>     "@angular/platform-browser-dynamic": "~13.2.0",
>     "@angular/router": "~13.2.0",
>     "@nebular/auth": "^9.0.1",
>     "@nebular/eva-icons": "^9.0.1",
>     "@nebular/theme": "^9.0.1",
>     "@ng-bootstrap/ng-bootstrap": "^11.0.0",
>     "@nrwl/angular": "13.8.3",
>     "bootstrap": "^5.1.3",
>     "eva-icons": "^1.1.3",
>     "rxjs": "~7.4.0",
>     "tslib": "^2.0.0",
>     "zone.js": "~0.11.4"
>   },
>   "devDependencies": {
>     "@angular-devkit/build-angular": "~13.2.0",
>     "@angular-eslint/eslint-plugin": "~13.0.1",
>     "@angular-eslint/eslint-plugin-template": "~13.0.1",
>     "@angular-eslint/template-parser": "~13.0.1",
>     "@angular/cli": "~13.2.0",
>     "@angular/compiler-cli": "~13.2.0",
>     "@angular/language-service": "~13.2.0",
>     "@nrwl/cli": "13.8.3",
>     "@nrwl/cypress": "13.8.3",
>     "@nrwl/eslint-plugin-nx": "13.8.3",
>     "@nrwl/jest": "13.8.3",
>     "@nrwl/linter": "13.8.3",
>     "@nrwl/tao": "13.8.3",
>     "@nrwl/workspace": "13.8.3",
>     "@schematics/angular": "~13.2.0",
>     "@types/jest": "27.0.2",
>     "@types/node": "16.11.7",
>     "@typescript-eslint/eslint-plugin": "~5.10.0",
>     "@typescript-eslint/parser": "~5.10.0",
>     "cypress": "^9.1.0",
>     "eslint": "~8.7.0",
>     "eslint-config-prettier": "8.1.0",
>     "eslint-plugin-cypress": "^2.10.3",
>     "jest": "27.2.3",
>     "jest-preset-angular": "11.1.1",
>     "prettier": "^2.5.1",
>     "ts-jest": "27.0.5",
>     "typescript": "~4.5.2"
>   }
> }
> ```
> 
> ## Current Behavior
> When trying to run npm run start I am getting the following error:
> 
> > NX   spawn ENAMETOOLONG
> 
> ## Expected Behavior
> My application starts when I enter the npm run start command.
> 
> ## Steps to Reproduce
> Generate an nrwl/nx Angular application and try to execute the npm run start command
> 
> ### Failure Logs
> > NX   spawn ENAMETOOLONG
> 
> ### Environment
> I am using vs code and hav npm lts version and nrwl the latest version. My application worked a week ago, when I had generated it.

I've figure it out by add the generated file & folder to gitignore configuration file .gitignore
