### ISSUE TITLE
Cli wont work, daemon keeps stopping

### ISSUE THREAD

**Issue by VincentThomas06** [nrwl/nx#9043]
## Current Behavior
When i try to do anything in the nx cli it gives me this error
```
 NX   Nx Daemon was not able to compute the project graph.

   Log file with the error: C:\Users\vincent\coding\projects-new\node_modules\.cache\nx\d\daemon-error.log
   Please file an issue at https://github.com/nrwl/nx
   Nx Daemon is going to be disabled until you run "nx reset".


 NX   spawn ENAMETOOLONG
```

C:\Users\vincent\coding\projects-new\node_modules\.cache\nx\d\daemon-error.log: 
```
Failed to start the Nx Daemon process.
Messages from the log:

NX   spawn ENAMETOOLONG
```

More information: C:\Users\vincent\coding\projects-new\node_modules\.cache\nx\d\daemon.log
```
 NX   spawn ENAMETOOLONG
```

## Expected Behavior
I would like the cli to work like normal

### Is this a regression?
No

## Steps to Reproduce
https://github.com/VincentThomas06/Projects

### Failure Logs
```
 NX   Nx Daemon was not able to compute the project graph.

   Log file with the error: C:\Users\vincent\coding\projects-new\node_modules\.cache\nx\d\daemon-error.log
   Please file an issue at https://github.com/nrwl/nx
   Nx Daemon is going to be disabled until you run "nx reset".


 >  NX   spawn ENAMETOOLONG
```

C:\Users\vincent\coding\projects-new\node_modules\.cache\nx\d\daemon-error.log:
```
Failed to start the Nx Daemon process.
Messages from the log:

 >  NX   spawn ENAMETOOLONG
```

More information: C:\Users\vincent\coding\projects-new\node_modules\.cache\nx\d\daemon.log
```
 >  NX   spawn ENAMETOOLONG
```

### Environment
``` 
Node : 16.13.1
   OS   : win32 x64
   yarn : 1.22.17

   nx : 13.8.3
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.3
   @nrwl/cypress : 13.8.1
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.3
   @nrwl/eslint-plugin-nx : 13.8.1
   @nrwl/express : undefined
   @nrwl/jest : 13.8.1
   @nrwl/js : 13.8.1
   @nrwl/linter : 13.8.1
   @nrwl/nest : 13.8.3
   @nrwl/next : undefined
   @nrwl/node : 13.8.1
   @nrwl/nx-cloud : 13.1.4
   @nrwl/react : 13.8.3
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.3
   @nrwl/tao : 13.8.3
   @nrwl/web : 13.8.1
   @nrwl/workspace : 13.8.3
   typescript : 4.2.4
   rxjs : 7.5.4
   ---------------------------------------
   Community plugins:
```

**Comment by slewis30328** [comment]
Logged this issue 17 days ago.  They wanted a repo, but I have security issues posting mine.  If you have a repo to post, that would be great.  This issue has caused me major problems with upgrade.  Would really like to move forward, but I'm out of options at this point.  I've tried creating stub repos to trigger error and I can't.  It has something to do with  allocation/threshold/high-water mark type logic.  I can trigger error in my repo by going increasing file count in apps and libs directory.  Just a reminder, pretty sure you have to run nx reset after error is triggered. If you don't, it will continue regardless of changes you make.  

https://github.com/nrwl/nx/issues/8834

**Comment by VincentThomas06** [comment]
> Logged this issue 17 days ago.  They wanted a repo, but I have security issues posting mine.  If you have a repo to post, that would be great.  This issue has caused me major problems with upgrade.  Would really like to move forward, but I'm out of options at this point.  I've tried creating stub repos to trigger error and I can't.  It has something to do with  allocation/threshold/high-water mark type logic.  I can trigger error in my repo by going increasing file count in apps and libs directory.  Just a reminder, pretty sure you have to run nx reset after error is triggered. If you don't, it will continue regardless of changes you make.  
> 
> https://github.com/nrwl/nx/issues/8834
> 
> 

Yes i know but sometimes it doesnt matter if i run nx reset, its still does this

**Comment by slewis30328** [comment]
Oh…I know! 🤕 I just meant if you were making a change and wanted to see if the change made an impact - it’s good to run that to start fresh.

**Comment by karelinda** [comment]
So...there is a solution???!!!!.... Somebody!!!!

**Comment by slewis30328** [comment]
I was able to resolve the issue by committing my unsaved changes. Sounds crazy, but that fixed it. I was doing my upgrade in a fresh repo. Have a very large code base and I copied the files over into the new nix workspace after I created the shell for my apps. The files had not been committed and I was trying to run lints, builds, etc. only way to get nx cli to keep going was to commit the files. Not sure if that is considered a “fix”, but it’s definitely a work around that enabled me to keep working.

**Comment by karelinda** [comment]
> I was able to resolve the issue by committing my unsaved changes. Sounds crazy, but that fixed it. I was doing my upgrade in a fresh repo. Have a very large code base and I copied the files over into the new nix workspace after I created the shell for my apps. The files had not been committed and I was trying to run lints, builds, etc. only way to get nx cli to keep going was to commit the files. Not sure if that is considered a “fix”, but it’s definitely a work around that enabled me to keep working.
> […](#)
> Sent from my iPhone
> On Feb 24, 2022, at 3:57 PM, karelinda ***@***.***> wrote: ﻿ So...there is a solution???!!!!.... Somebody!!!! — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.

Thanks.....it works for me

**Comment by AgentEnder** [comment]
Hey, I'm going to close this out since its a duplicate of #8646. The PR fixing this should be merged soon.

**Comment by jwilbur-godaddy** [comment]
> I was able to resolve the issue by committing my unsaved changes. Sounds crazy, but that fixed it. I was doing my upgrade in a fresh repo. Have a very large code base and I copied the files over into the new nix workspace after I created the shell for my apps. The files had not been committed and I was trying to run lints, builds, etc. only way to get nx cli to keep going was to commit the files. Not sure if that is considered a “fix”, but it’s definitely a work around that enabled me to keep working.
> […](#)
> Sent from my iPhone
> On Feb 24, 2022, at 3:57 PM, karelinda ***@***.***> wrote: ﻿ So...there is a solution???!!!!.... Somebody!!!! — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.

I second this. This made this work for me too. Weird.
