### ISSUE TITLE
Tailwind setup on existing angular is incomplete

### ISSUE THREAD

**Issue by DaSchTour** [nrwl/nx#9044]
## Current Behavior
Running `npx nx g @nrwl/angular:setup-tailwind my-project` doesn't produce fully working setup. The build executor is left at `@angular-devkit/build-angular:browser` and is not changed to `@nrwl/angular:webpack-browser`

## Expected Behavior
The build executor is changed to make tailwind work.

## Steps to Reproduce
Setup a new workspace with an angular application
Run `npx nx g @nrwl/angular:setup-tailwind my-project` on that project

### Environment

   Node : 16.13.0
   OS   : darwin x64
   npm  : 8.3.0
   
   nx : 13.8.3
   @nrwl/angular : 13.8.3
   @nrwl/cli : 13.8.3
   @nrwl/cypress : 13.8.3
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.3
   @nrwl/eslint-plugin-nx : 13.8.3
   @nrwl/express : undefined
   @nrwl/jest : 13.8.3
   @nrwl/js : undefined
   @nrwl/linter : 13.8.3
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : 13.1.4
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.3
   @nrwl/tao : 13.8.3
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.3
   typescript : 4.5.5
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
   	 @angular/animations: 13.2.3
   	 @angular/cdk: 13.2.3
   	 @angular/common: 13.2.3
   	 @angular/compiler: 13.2.3
   	 @angular/core: 13.2.3
   	 @angular/forms: 13.2.3
   	 @angular/material: 13.2.3
   	 @angular/platform-browser: 13.2.3
   	 @angular/platform-browser-dynamic: 13.2.3
   	 @angular/router: 13.2.3
   	 @auth0/auth0-angular: 1.9.0
   	 @angular-devkit/build-angular: 13.2.4
   	 @angular/cli: 13.2.4
   	 @angular/compiler-cli: 13.2.3
   	 @angular/language-service: 13.2.3

**Comment by DaSchTour** [comment]
Well, only after I switched the executor I get rid of @tailwind in my final css and got actually tailwind classes inside my final CSS.

**Comment by leosvelperez** [comment]
Could you share a minimal repo where the issue can be reproduced?

**Comment by DaSchTour** [comment]
@leosvelperez I have it also working on another project but there the tailwind.config.js is in the root folder and not in the project folder

**Comment by leosvelperez** [comment]
Alright, but that's not what the `@nrwl/angular:setup-tailwind` generates, that's a custom setup and as such, it's not an issue of the generator. If you run the generator, it will set up the Tailwind CSS config per project and it would work as expected.

That said, AFAIK, the `@angular-devkit/build-angular:browser` should pick the workspace root config, if it's not doing that, it might be an issue of that executor which comes from the Angular CLI.

**Comment by DaSchTour** [comment]
Well, but in the end the point is, you run `@nrwl/angular:setup-tailwind` and potentially end up with a not working setup 😞

**Comment by leosvelperez** [comment]
I disagree based on what we've been discussing, if you run `@nrwl/angular:setup-tailwind`, you'll get a config in the project you're running it for and it does work as expected. You mentioned a different scenario where the config is not in the project, but in the root, which is not what the generator would have generated.

Like I mentioned above, if you have something different where using the generator ends up in a state that Tailwind CSS doesn't work, please provide a minimal repo with the issue.

**Comment by leosvelperez** [comment]
By following the reproduction steps you provided in the OP, I get a working application with the Tailwind CSS directives processed as expected.

**Comment by DaSchTour** [comment]
Well. I checked the configuration and it's very strange.


Works:
```
"executor": "@angular-devkit/build-angular:browser",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/apps/halbcamp",
        "index": "apps/halbcamp/src/index.html",
        "main": "apps/halbcamp/src/main.ts",
        "polyfills": "apps/halbcamp/src/polyfills.ts",
        "tsConfig": "apps/halbcamp/tsconfig.app.json",
        "inlineStyleLanguage": "scss",
        "assets": ["apps/halbcamp/src/favicon.ico", "apps/halbcamp/src/assets"],
        "styles": [
          "apps/halbcamp/src/styles.scss",
          "./node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css"
        ],
        "scripts": []
      },
```

Doesn't work:
```
"executor": "@angular-devkit/build-angular:browser",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/apps/halbcamp",
        "index": "apps/halbcamp/src/index.html",
        "main": "apps/halbcamp/src/main.ts",
        "polyfills": "apps/halbcamp/src/polyfills.ts",
        "tsConfig": "apps/halbcamp/tsconfig.app.json",
        "inlineStyleLanguage": "scss",
        "assets": ["apps/halbcamp/src/favicon.ico", "apps/halbcamp/src/assets"],
        "styles": [
          "./node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css",
          "apps/halbcamp/src/styles.scss"
        ],
        "scripts": []
```

But this works:
```
"executor": "@angular-devkit/build-angular:browser",
      "outputs": [
        "{options.outputPath}"
      ],
      "options": {
        "outputPath": "dist/apps/tailwind-test",
        "index": "apps/tailwind-test/src/index.html",
        "main": "apps/tailwind-test/src/main.ts",
        "polyfills": "apps/tailwind-test/src/polyfills.ts",
        "tsConfig": "apps/tailwind-test/tsconfig.app.json",
        "inlineStyleLanguage": "scss",
        "assets": [
          "apps/tailwind-test/src/favicon.ico",
          "apps/tailwind-test/src/assets"
        ],
        "styles": [
          "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css",
          "apps/tailwind-test/src/styles.scss"
        ],
        "scripts": []
      },
```

**Comment by leosvelperez** [comment]
I can't spot anything that could cause the issue either. The only difference in the first two snippets is that the styles are in a different order, but then the last snippet has it in the same order as the one failing. That shouldn't really be an issue unless there's a weird bug in the `@angular-devkit/build-angular:browser` executor.

I wonder if there's an Angular cache issue. Could you make sure to delete the `.angular` directory and then run the build again?
