### ISSUE TITLE
Generator JSON schema app/lib: tags not of type array

### ISSUE THREAD

**Issue by TomONeill** [nrwl/nx#9055]
Hello, I am trying to add a JSON schema to my VSCode settings ([`json.schemas`](https://code.visualstudio.com/docs/languages/json#_mapping-in-the-user-settings)) so that the `project.json` files will be typed and Intellisense works.

Referencing `https://raw.githubusercontent.com/nrwl/nx/master/packages/next/src/generators/application/schema.json` works, except the `tags` array gives me a warning: `Incorrect type. Expected "string"`.

I think that's because of the following:
https://github.com/nrwl/nx/blob/33c9ca98ae6940befb8e1132cb2263adb99ce5bc/packages/next/src/generators/application/schema.json#L98-L102
https://github.com/nrwl/nx/blob/33c9ca98ae6940befb8e1132cb2263adb99ce5bc/packages/next/src/generators/library/schema.json#L86-L90

Is it possible to change that into an array? Or is there another way to make the schema work?

Edit:
And while I'm at it, is there a schema.json available for `nx.json` that I can use?

**Comment by TomONeill** [comment]
Related: #2299

**Comment by FrozenPandaz** [comment]
`https://raw.githubusercontent.com/nrwl/nx/master/packages/next/src/generators/application/schema.json` should not be the schema of `project.json`.

The schema of `project.json` is not easily expressed as a single `schema.json` file. But we do have a VS Code extension that provides this schema with autocompletion and everything :)

https://marketplace.visualstudio.com/items?itemName=nrwl.angular-console

Does that work for you?
