### ISSUE TITLE
implicitDependencies in package.json files are ignored

### ISSUE THREAD

**Issue by isaacplmann** [nrwl/nx#9065]
## Current Behavior
Setting `implicitDependencies` in the `nx` property of a `package.json` file is ignored.

## Expected Behavior
https://nx.dev/configuration/packagejson#implicitdependencies

## Steps to Reproduce
1. `npx create-nx-workspace --preset=core something`
2. Set up yarn workspaces
3. Make `packages/lib1` with a `package.json` and the `name` property set to `lib1`
4. Make `packages/lib2` with a `package.json` and the `name` property set to `lib2`
5. Add `nx: { implicitDependencies: ["lib1"] }` to the `lib2` `package.json` file.
6. Run `nx dep-graph`

Expected results:
`lib2` should depend on `lib1` in the dependency graph.

Actual results:
The projects are not connected.

**Comment by agdimech** [comment]
I am also having this issue. The only time I can get the dependencies to actually show is by adding a dep on lib1 directly in the package.json deps or devDeps

**Comment by agdimech** [comment]
Just did some debugging and it appears the workspace is not taking into account the nx property in the package.json.

https://github.com/nrwl/nx/blob/master/packages/tao/src/shared/workspace.ts#L761

If you modify this function as follows, it fixes the issue (tested locally).

```js
function buildProjectConfigurationFromPackageJson(path, packageJson, nxJson) {
    var _a;
    const directory = (0, path_1.dirname)(path).split('\\').join('/');
    const npmPrefix = `@${nxJson.npmScope}/`;
    let name = (_a = packageJson.name) !== null && _a !== void 0 ? _a : toProjectName(directory, nxJson);
    if (name.startsWith(npmPrefix)) {
        name = name.replace(npmPrefix, '');
    }
    return {
        root: directory,
        sourceRoot: directory,
        name,
        implicitDependencies: packageJson.nx && packageJson.nx.implicitDependencies || []
    };
}
```

**Comment by avimehenwal** [comment]
Hi, I am using nx version `14.0.2` and I can confirm the same that `implicitDependencies` is NOT working with `package.json` .
However to my surprise, I was implicity able to add a edge when I moved the `implicitDependencies` block over to `project.json` file. Hope it help in someway
