### ISSUE TITLE
Request - Be more flexible with required versions

### ISSUE THREAD

**Issue by gkamperis** [nrwl/nx#907]
Hi

We are using @nrwl/schematics but are in an Artifactory environment.

Not all versions in your lib-versions are available.

For example for v6.4 you required @angular/cli v6.2.4
v6.2.3 and v6.2.5 were available but not v6.2.4.
The result was that create-nx-workspace was failing silently.

This "hard-coding" of versions becomes very problematic and makes usage and adoption difficult.
Especially for upgrading Nx.
I would need to make available all your required versions before using Nx.

Ideally you should allow a range of versions for all used "lib-versions".

Or at least provide a better way of finding out what is missing/required in order to not have to go and search for what is missing.

Thanks

**Comment by gkamperis** [comment]
@FrozenPandaz well most of the time the current versions are different to the ones you have in lib-versions.

A workspace might be scaffolded with the ones you specify. 
But through time they change.

Creating libs/apps *usually* works ok with newer lib-versions.
What breaks mostly is creating a workspace or migrating and app.

Security is one reason but also there is no need to have in Artifactory every single version of every package.

The packages that become available have to be on-boarded and somebody has to ask for them.

That means that if I want to use the latest Nx version I have to look at the libs you require and first make sure they are available and then get Nx.

This has become already a pain - started using v6 of Nx.

As mentioned if specific versions are absolutely required then making them dependencies would force them to also be installed with Nx.

That is far from ideal for a lot of reasons but with the current approach, essentially, you are treating specific versions as required dependencies.

**Comment by emilio-martinez** [comment]
@FrozenPandaz Perhaps it is worth setting range peer dependencies on Nx for the required packages? It wouldn't exactly solve the flexibility challenge, but at least there would be more transparency around valid ranges.

**Comment by emilio-martinez** [comment]
Example: CLI 7.1 release is out and I'm personally unclear whether Nx is compatible. As mentioned above, historically some versions have caused issues but there is no clear indication whether this release is in the clear. Only via trial and error.

**Comment by gkamperis** [comment]
@emilio-martinez The issue I raised is not about future-proofing.
How can Nx know if an upcoming version will introduce a breaking change?
I don't think it can.

What I'd (ideally) want is tolerance for patch or minor versions.
I can understand that Nx needs to be sure it works and that it requires specific versions.

If there is no way to allow a range then I would say that the errors thrown because of missing versions is explicit and explains that the reason for the failure is a missing version.

Currently it fails silently and I have to figure out which of the libs is missing.

**Comment by vsavkin** [comment]
Sorry for the late reply.

We tried to use version ranges in the past, but it resulted in issues where a patch release of the angular cli would break us. We are running our e2e tests against a specific version of the CLI, so we only guarantee it works with that version. 

Having said that, we are trying to make it such that Nx 7x works with any version of Angular CLI 7x. So you can upgrade the version of the cli independently (or any other package). Most likely everything will work without any problems. 

In this case, you can run the update command (or generate command) without running `npm install`, relax the versions and then run `npm install` yourself. 

`create-nx-workspace` is a special case. It hardcodes a particular version of the CLI. In this case, a better option might be running `ng new --collection=@nrwl/schematics` or using `ng add`.

**Comment by nhhockeyplayer** [comment]
I cannot NOT comment on this
no matter what I try yarn or npm... clean cache reinstall
I cannot get nx@11.6.3 to install
it seems hardwired to install latest 12.5.1

the ecosystem for npm has gone south worse than its been since the early days of typedefs and when packages werent even governed flanked by half a dozen webpack, jest, @angular/cli@12 changes and I have not been in my 200k lines of code business logic in two weeks wrestling with build hell 

it would be nice if something were done to mitigate this, the angular 12 upgrade is not ripe enough for my code and the worst hit I have ever seen in six years and im sitting at node.js 12 now after trying every major version to the latest without resolve

if I log a bug it may get sent to stackoverflow like the others I dont see anything becoming stable for while until ALL parties flanking the ecosystem get their A game on the table

I dont know who is responsible for this (open source developers but several packages made their 0.02cents contribution to the instability) and Victors masterpiece has been desecrated and its not good
version 11 angular flies and 12 is slow as molasses there are dependencies with the cli's

Im trying to back down Nrwl/Nx to 11.6.3 and @angular.11 and I cant with Nrwl/Nx its hardwired all NPM YARN installation to 12.5.1

Can someone help make something possible

The core developers may know what Im talking about... and I would predict they would agree nothing is stable at this time

any feedback is appreciated

```
meanstack02@admin energy % yarn global add nx@11.6.3
yarn global v1.22.10
warning ../../package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @nrwl/nx@7.8.7" has unmet peer dependency "jasmine-marbles@0.4.0".
warning " > @nrwl/workspace@12.5.1" has unmet peer dependency "prettier@^2.3.0".
warning abbrev@1.1.0: Invalid bin field for "abbrev".
warning ansicolors@0.3.2: Invalid bin field for "ansicolors".
warning ansistyles@0.1.3: Invalid bin field for "ansistyles".
warning archy@1.0.0: Invalid bin field for "archy".
warning call-limit@1.1.0: Invalid bin field for "call-limit".
warning bluebird@3.5.0: Invalid bin field for "bluebird".
warning chownr@1.0.1: Invalid bin field for "chownr".
warning cmd-shim@2.0.2: Invalid bin field for "cmd-shim".
warning columnify@1.5.4: Invalid bin field for "columnify".
warning config-chain@1.1.11: Invalid bin field for "config-chain".
warning debuglog@1.0.1: Invalid bin field for "debuglog".
warning detect-indent@5.0.0: Invalid bin field for "detect-indent".
warning dezalgo@1.0.3: Invalid bin field for "dezalgo".
warning editor@1.0.0: Invalid bin field for "editor".
warning fs-vacuum@1.2.10: Invalid bin field for "fs-vacuum".
warning fs-write-stream-atomic@1.0.10: Invalid bin field for "fs-write-stream-atomic".
warning fstream@1.0.11: Invalid bin field for "fstream".
warning graceful-fs@4.1.11: Invalid bin field for "graceful-fs".
warning has-unicode@2.0.1: Invalid bin field for "has-unicode".
warning iferr@0.1.5: Invalid bin field for "iferr".
warning imurmurhash@0.1.4: Invalid bin field for "imurmurhash".
warning inflight@1.0.6: Invalid bin field for "inflight".
warning inherits@2.0.3: Invalid bin field for "inherits".
warning ini@1.3.4: Invalid bin field for "ini".
warning init-package-json@1.10.1: Invalid bin field for "init-package-json".
warning lazy-property@1.0.0: Invalid bin field for "lazy-property".
warning lockfile@1.0.3: Invalid bin field for "lockfile".
warning lodash._baseindexof@3.1.0: Invalid bin field for "lodash._baseindexof".
warning lodash._baseuniq@4.6.0: Invalid bin field for "lodash._baseuniq".
warning lodash._bindcallback@3.0.1: Invalid bin field for "lodash._bindcallback".
warning lodash._cacheindexof@3.0.2: Invalid bin field for "lodash._cacheindexof".
warning lodash._createcache@3.1.2: Invalid bin field for "lodash._createcache".
warning lodash._getnative@3.9.1: Invalid bin field for "lodash._getnative".
warning lodash.clonedeep@4.5.0: Invalid bin field for "lodash.clonedeep".
warning lodash.restparam@3.6.1: Invalid bin field for "lodash.restparam".
warning lodash.union@4.6.0: Invalid bin field for "lodash.union".
warning lodash.uniq@4.5.0: Invalid bin field for "lodash.uniq".
warning lodash.without@4.4.0: Invalid bin field for "lodash.without".
warning mississippi@1.3.0: Invalid bin field for "mississippi".
warning move-concurrently@1.0.1: Invalid bin field for "move-concurrently".
warning npm-cache-filename@1.0.2: Invalid bin field for "npm-cache-filename".
warning npm-install-checks@3.0.0: Invalid bin field for "npm-install-checks".
warning once@1.4.0: Invalid bin field for "once".
warning osenv@0.1.4: Invalid bin field for "osenv".
warning path-is-inside@1.0.2: Invalid bin field for "path-is-inside".
warning promise-inflight@1.0.1: Invalid bin field for "promise-inflight".
warning read@1.0.7: Invalid bin field for "read".
warning read-cmd-shim@1.0.1: Invalid bin field for "read-cmd-shim".
warning read-installed@4.0.3: Invalid bin field for "read-installed".
warning readdir-scoped-modules@1.0.2: Invalid bin field for "readdir-scoped-modules".
warning retry@0.10.1: Invalid bin field for "retry".
warning sha@2.0.1: Invalid bin field for "sha".
warning slide@1.1.6: Invalid bin field for "slide".
warning sorted-object@2.0.1: Invalid bin field for "sorted-object".
warning sorted-union-stream@2.1.3: Invalid bin field for "sorted-union-stream".
warning tar@2.2.1: Invalid bin field for "tar".
warning text-table@0.2.0: Invalid bin field for "text-table".
warning uid-number@0.0.6: Invalid bin field for "uid-number".
warning umask@1.1.0: Invalid bin field for "umask".
warning unique-filename@1.1.0: Invalid bin field for "unique-filename".
warning unpipe@1.0.0: Invalid bin field for "unpipe".
warning validate-npm-package-license@3.0.1: Invalid bin field for "validate-npm-package-license".
warning validate-npm-package-name@3.0.0: Invalid bin field for "validate-npm-package-name".
warning wrappy@1.0.2: Invalid bin field for "wrappy".
[4/4] 🔨  Building fresh packages...
success Installed "nx@11.6.3" with binaries:
      - nx
✨  Done in 6.61s.
meanstack02@admin energy % nx --version
12.5.1
meanstack02@admin energy % which nx
/usr/local/bin/nx
meanstack02@admin energy %

```


```
meanstack02@admin energy % npm install -g nx@11.6.3
/usr/local/bin/nx -> /usr/local/lib/node_modules/nx/bin/nx.js
+ nx@11.6.3
added 62 packages from 31 contributors in 5.077s
meanstack02@admin energy % which nx
/usr/local/bin/nx
meanstack02@admin energy % nx --version
12.5.1
```

**Comment by nhhockeyplayer** [comment]
it would be nice to slip back to nx@11.6.3
so I can resume my business logic at @angular/cli@11
and ditch the forced use of webpack thats being imposed to get around build hell

I have a codebase that doesnt even rely on webpack for anything

and im finding I need to create webpack.config.js and builders to fix the damned 'fs' issues and the cb.apply() issues ands the engine issues and so many others making build impossible now for a large scale normal codebase

**Comment by nhhockeyplayer** [comment]
and how does one explain the above output

says it installed 11.6.3

and I check version and its something else?

**Comment by nhhockeyplayer** [comment]
here is another of whats happening under the hood

```
meanstack02@admin energy % nx build admin

> nx run admin:build 

An error occurred during the build:
Error: The Angular Compiler requires TypeScript >=4.0.0 and <4.2.0 but 4.3.5 was found instead.


meanstack02@admin energy % tsc --version
Version 4.1.3
meanstack02@admin energy % grep typescript package.json 
    "@typescript-eslint/eslint-plugin": "^4.28.1",
    "@typescript-eslint/parser": "^4.28.1",
    "typescript": "^4.1.3",
meanstack02@admin energy % 
```

where is typescript 4.3.5 coming from ?

I purged cache
reinstalled everything

its a mystery

**Comment by itsmelion** [comment]
I understand @vsavkin but can at least the Linter stuff be relaxed?
now it asks for `eslint-plugin-react-hooks@4.3.0`, and my linter asks for `@^4.5.0` so then is duping the react-hooks package so linter don't work.

I have to use `resolutions` from yarn to ensure only one is resolved ://
