### ISSUE TITLE
Build from within project directory fails

### ISSUE THREAD

**Issue by jeffreyschultz** [nrwl/nx#9070]
## Current Behavior

When I run `nx build` within an application or library project directory the build doesn't seem to understand where it is executing, and fails with pathing errors.

## Expected Behavior

The actual issue with this ticket is that the build fails due to output pathing issues.

The expected behavior would be for the `nx` build system to understand the command is being executed under the context of the current project, and build the project with all output preferablly colocated within the project folder. It would be preferable if the `dist` folder is created within the project folder due to colocation of Dockerfiles and other build systems such as Gradle, that might be expecting ouputs from `nx build`, and it would be cleaner than having a `Dockerfile` within `webapps/browser` that needs to reach all the way back to `../../dist/webapps/browser`, and instead only had to grab source from `webapps/browser/dist` or rather `./dist`.

## Steps to Reproduce

1. Create nx workspace.
2. Create a react application.
3. Change directory to react application folder.
4. Run `nx build`

### Failure Logs

![image](https://user-images.githubusercontent.com/479560/155754923-a01e137f-8b0c-4a8f-9690-9b28d4b5661d.png)

I thought I had found a workaround using outputPath located within project.json, but there seems to be a bug related to child folders under dist not being created properly when the build is executed from the project folder.

![image](https://user-images.githubusercontent.com/479560/155755263-f1536ef8-14dc-4018-a416-e8d733b97211.png)

This only works when the build is executed from the workspace root directory, but fails within the individual project directories.

If I manually create the dist/browser folder it still fails to properly build the project from the project directory. It only generates the index.html file, so there seem to be several issues at play here.

```
dist
└── browser
    └── index.html

1 directory, 1 file
```

### Environment

MacOSX Monterey 12.2.1
Nx 13.7.3

**Comment by jeffreyschultz** [comment]
I thought I had found a workaround using `outputPath` located within `project.json`, but there seems to be a bug related to child folders under `dist` not being created properly when the build is executed from the project folder.

<img width="568" alt="image" src="https://user-images.githubusercontent.com/479560/155056581-e832dfe3-0a12-4a1f-9129-5627f869fb95.png">

```
npx nx build

> nx run browser:build:production

Entrypoint main 177 KiB = runtime.c1411f2a2fb6c6b8.esm.js 1.03 KiB main.b400dc8c7e6f1ad8.esm.js 176 KiB
Entrypoint polyfills 88.7 KiB = runtime.c1411f2a2fb6c6b8.esm.js 1.03 KiB polyfills.161a3442567b3cb1.esm.js 87.7 KiB
Entrypoint styles 1.03 KiB = runtime.c1411f2a2fb6c6b8.esm.js 1.03 KiB styles.ef46db3751d8e999.css 0 bytes
chunk (runtime: runtime) main.b400dc8c7e6f1ad8.esm.js (main) 288 KiB [initial] [rendered]
chunk (runtime: runtime) polyfills.161a3442567b3cb1.esm.js (polyfills) 286 KiB [initial] [rendered]
chunk (runtime: runtime) styles.ef46db3751d8e999.css (styles) 50 bytes (javascript) 0 bytes (css/mini-extract) [initial] [rendered]
chunk (runtime: runtime) runtime.c1411f2a2fb6c6b8.esm.js (runtime) 3.01 KiB [entry] [rendered]
webpack compiled successfully (3f3eec0442c9a8a4)
ENOENT: no such file or directory, open 'dist/browser/index.html'

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "browser:build" failed

   Failed tasks:

   - browser:build:production

   Hint: run the command with --verbose for more details.
   ```

**Comment by jeffreyschultz** [comment]
If I manually create the `dist/browser` folder it still fails to properly build the project from the project directory. It only generates the index.html file.

<img width="331" alt="image" src="https://user-images.githubusercontent.com/479560/155057129-a2a29c34-da3f-49b8-afab-b1d54652aeef.png">

**Comment by FrozenPandaz** [comment]
Yes, this is an issue with the `@nrwl/web:webpack` executor. We will take a look

With regards to `dist` location. You are free to define your own output directories to be within the project root.

**Comment by jeffreyschultz** [comment]
Thanks @FrozenPandaz!

Yes, I have done that in my project.

**Comment by mattfysh** [comment]
Many plugins seem to have this same issue (e.g. format, lint, nx-pulumi). I wonder if there's something to be added to devkit for reading files relative to project dir?
