### ISSUE TITLE
Passing prettier configuration file to nx format:write or nx format:check don't work

### ISSUE THREAD

**Issue by mikaelboff** [nrwl/nx#9071]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/cli/format-check
https://nx.dev/cli/format-write

### Additional context or description

Apparently the `--configuration` flag passed by argument to `nx format:write` or `nx format:check` commands is not interpreted.
If I run `prettier --config .prettierrc -c` my configuration file is used, but with `nx format:check --configuration=.prettierrc` it don't use it.

**Comment by FrozenPandaz** [comment]
Sorry, I don't think the `--configuration` flag should be on that command but it is a different type of `configuration`. We could add something for `--prettierConfiguration`. But before we do so, what is your use case for a different prettier config?

**Comment by johngrimsey** [comment]
I believe this issue remains as described.
