### ISSUE TITLE
upgrade to 13.8.3 doesn't make nextjs upgrade to 12.1.0

### ISSUE THREAD

**Issue by lisagherschon** [nrwl/nx#9077]
## Current Behavior
Upgrading nx from `13.3.6` to `13.8.3` 

## Expected Behavior
upgrading nx to get nextjs 12.1.0 from 13.8.3

## Steps to Reproduce

From a project that is using nx 13.3.6
`nx migrate latest `
verify package.json -> next version is `12.0.7` instead of `12.1.0`

### Environment
 Node : 16.14.0
  OS   : darwin x64
  yarn : 1.22.17
  
  nx : 13.3.6
  @nrwl/angular : undefined
  @nrwl/cli : 13.3.6
  @nrwl/cypress : 13.3.6
  @nrwl/devkit : 13.3.6
  @nrwl/eslint-plugin-nx : 13.3.6
  @nrwl/express : undefined
  @nrwl/jest : 13.3.6
  @nrwl/linter : 13.3.6
  @nrwl/nest : 13.3.6
  @nrwl/next : 13.3.6
  @nrwl/node : 13.3.6
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.3.6
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.6
  @nrwl/web : 13.3.6
  @nrwl/workspace : 13.3.6
  @nrwl/storybook : 13.3.6
  @nrwl/gatsby : undefined
  typescript : 4.3.5
  rxjs : 7.4.0

**Comment by FrozenPandaz** [comment]
The migration will run when upgrading to Nx `13.9.0` which will come soon.
