### ISSUE TITLE
App Depending On Buildable Library Fails (13.8.2 & Above)

### ISSUE THREAD

**Issue by enchorb** [nrwl/nx#9079]
## Current Behavior
On Nrwl versions 13.8.2 and up, building an app that depends on a buildable library fails. In my case this is happening with a firebase cloud functions app that depends on a buildable libeary and produces the following error:
```
nx run functions:build

Copying asset files...
Done copying asset files.
- Processing dependencies for firebase functions app 'functions':
 -  Added 'npm' dependency '@biesbjerg/ngx-translate-extract-marker'
 -  Added 'npm' dependency 'firebase-admin'
 -  Added 'npm' dependency 'firebase-functions'
 -  Added 'npm' dependency 'rxjs'
Cannot read property 'type' of undefined
```

## Expected Behavior

This seems to be a regression as it works fine for version 13.8.1 and under

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by enchorb** [comment]
After further testing this seems to be caused when upgrading `@nrwl/workspace` to over 13.8.1

My build works correctly with this configuration for the time being, not sure what changed in post 13.8.1 to cause the above error.

```
   "@nrwl/angular": "13.8.3",
    "@nrwl/cli": "13.8.3",
    "@nrwl/cypress": "13.8.3",
    "@nrwl/detox": "13.8.3",
    "@nrwl/devkit": "13.8.3",
    "@nrwl/eslint-plugin-nx": "13.8.3",
    "@nrwl/express":"13.8.3",
    "@nrwl/jest": "13.8.3",
    "@nrwl/js": "13.8.3",
    "@nrwl/linter": "13.8.3",
    "@nrwl/node": "13.8.3",
    "@nrwl/nx-cloud": "latest",
    "@nrwl/react": "13.8.3",
    "@nrwl/react-native": "13.8.3",
    "@nrwl/tao": "13.8.3",
    "@nrwl/web":"13.8.3",
    "@nrwl/workspace": "13.8.1"
```

**Comment by FrozenPandaz** [comment]
Sorry, could you please provide a repro that we can use to reproduce the issue?
