### ISSUE TITLE
Angular Library Build fails with NON-descriptive error [object Object]

### ISSUE THREAD

**Issue by tomastrajan** [nrwl/nx#9080]
## Current Behavior

Setup:
* **EDIT** it turned out the error can be triggered by generating a lib and changing its `name` in the inline `package.json` from `@org/a/b/c` to `@org/a-b-c` without adjusting the paths in `tsconfig.base.json`
* 3 libs with no implementation `ui -> feature -> shell` 
* all libs created created using `--buildable` flag 
* shell consumed by an example application
* build triggered using `nx build`

The build fails for the `feature` lib with a very NON-descriptive error `[object Object]`

## Expected Behavior

Build works or at least fails with a descriptive error

## Workaround
Adding `console.error()` to the following place, based on my understanding the NX catches all the re-thrown errors on some higher level and tries to stringify them which leads to `[object Object]`
 so maybe there can be some more robust logic to detect if error is an object of different sorts and come up with more destriptive error in that case? 
![image](https://user-images.githubusercontent.com/3764868/155160095-da1fecc8-3ffb-4ef3-8183-726916ab0042.png)

### Failure Logs

```
------------------------------------------------------------------------------
Building entry point '@org/some-lib'
------------------------------------------------------------------------------
[object Object] <--- this is really not helpful
```

#### With workaround

```
FatalDiagnosticError {
  code: 3004,
  node: <ref *1> SourceFileObject {
    pos: 0,
    end: 0,
    flags: 0,
    modifierFlagsCache: 0,
    transformFlags: 0,
    parent: undefined,
    kind: 303,
    statements: [ pos: 0, end: 0, hasTrailingComma: false, transformFlags: 0 ],
    endOfFileToken: TokenObject {
      pos: 0,
      end: 0,
      flags: 0,
      modifierFlagsCache: 0,
      transformFlags: 0,
      parent: [Circular *1],
      kind: 1
    },
    fileName: '/home/tomastrajan/projects/mobi/rwc-b2e-workspace/libs/b2e/public/ui/button/src/lib/button/button.component.ngtypecheck.ts',
    text: '',
    languageVersion: 99,
    languageVariant: 0,
    scriptKind: 3,
    isDeclarationFile: false,
    hasNoDefaultLib: false,
    externalModuleIndicator: undefined,
    bindDiagnostics: [],
    bindSuggestionDiagnostics: undefined,
    pragmas: Map(0) {},
    checkJsDirective: undefined,
    referencedFiles: [],
    typeReferenceDirectives: [],
    libReferenceDirectives: [],
    amdDependencies: [],
    commentDirectives: undefined,
    nodeCount: 2,
    identifierCount: 0,
    identifiers: Map(0) {},
    parseDiagnostics: []
  },
  message: {
    category: 3,
    code: 0,
    messageText: 'Unable to import symbol ButtonComponent.',
    next: [ [Object] ]
  },
  relatedInformation: [
    {
      category: 3,
      code: 0,
      file: [SourceFileObject],
      start: 44,
      length: 162,
      messageText: 'The symbol is declared here.'
    }
  ],
  _isFatalDiagnosticError: true
}
[object Object]
```

### Environment

```
>  NX   Report complete - copy this into the issue template

   Node : 14.16.0
   OS   : linux x64
   npm  : 6.14.11

   nx : 13.8.3
   @nrwl/angular : 13.8.3
   @nrwl/cli : 13.8.3
   @nrwl/cypress : 13.8.3
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.3
   @nrwl/eslint-plugin-nx : 13.8.3
   @nrwl/express : undefined
   @nrwl/jest : 13.8.3
   @nrwl/js : 13.8.3
   @nrwl/linter : 13.8.3
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.3
   @nrwl/tao : 13.8.3
   @nrwl/web : 13.8.3
   @nrwl/workspace : 13.8.3
   typescript : 4.5.5
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
         @angular/animations: 13.2.2
         @angular/common: 13.2.2
         @angular/compiler: 13.2.2
         @angular/core: 13.2.2
         @angular/forms: 13.2.2
         @angular/platform-browser: 13.2.2
         @angular/platform-browser-dynamic: 13.2.2
         @angular/router: 13.2.2
         @angular-devkit/build-angular: 13.2.3
         @angular/cli: 13.2.3
         @angular/compiler-cli: 13.2.2
         @angular/language-service: 13.2.2
```

**Comment by davidmarquis** [comment]
I had the same error and your workaround helped me diagnose the issue, thanks for that!

I would add that as far as my workspace was concerned, running `nx reset` (clearing Nx caches) fixed the issue and allowed me to build the library.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

I tried to reproduce it by following the provided steps and renaming the project name in the `package.json` of the buildable libraries, but when I build the app or the libs I do get a descriptive error as shown in the following screenshot:

![image](https://user-images.githubusercontent.com/12051310/155976752-e91a1151-eb6f-4652-b895-be4f97e629c5.png)

In case I missed something, I ended up with this project graph where all libs are buildable:

![graph](https://user-images.githubusercontent.com/12051310/155977194-94f14357-3ffd-4a88-945b-183096f2472d.png)

@tomastrajan would you be able to provide a minimal repo with a reproduction of the issue so I can troubleshoot it?

**Comment by tomastrajan** [comment]
@leosvelperez for some reason I have hard time reproducing in an new empty workspace, must have been some special constellation of things in original repo.

That being said, based on previous comment (and StackOverflow issues) I was definitely not the only one experiencing this + the exact source of the error is not as important in our specific case.

The error source in my particular case was https://github.com/nrwl/nx/blob/master/packages/angular/src/executors/ng-packagr-lite/ng-packagr-adjustments/ng-package/entry-point/compile-ngc.transform.ts#L66

and in that case it was a complex object which then resulted in logging of the `[object Object]` in the console.

This brings me to idea that there is most likely some central error handler for the NX process, right? (haven't really explored the source that much yet) and such case could be handled by increasing of the robustness of that final handler  that it can handle objects more gracefully.

I am aware that it was more of an edge case error but in such cases, seeing at least something was essential. (as shown in the original description with the workaround of adding of `console.error on that line`)

**Comment by leosvelperez** [comment]
@tomastrajan it does make sense. I had a look again at the error object you shared above and I can see why `[object Object]` is being printed. We print the `error.message` as is because that property is expected to be a `string` and not a complex object. In the error above is a complex object which is wrong and it turns out that the `FatalDiagnosticError` shouldn't be thrown and instead be converted to a `ts.Diagnostics`, this is an issue in the `@angular/compiler-cli` that's being reported [here](https://github.com/angular/angular/issues/44999).

**Comment by tomastrajan** [comment]
@leosvelperez thx for the elaborate answer!
