### ISSUE TITLE
Nx is waiting on 1 dependent project tasks before running tasks from "project_name"

### ISSUE THREAD

**Issue by usarskyy** [nrwl/nx#9085]
My angular project stopped compiling and shows a weird message

_Nx is waiting on 1 dependent project tasks before running tasks from "project_name"_

## Current Behavior
After I execute a command "npx nx build project_name --prod" the following message is shown:

_Nx is waiting on 1 dependent project tasks before running tasks from "project_name"_

After this execution is stopped with no further information.

## Expected Behavior
1) Either I should see a message with the details that explain what project tasks are hanging, so I can fix this problem
2) Or the compiler has to wait until all tasks are completed and finally try to compile my project

## Steps to Reproduce
Unfortunately I can't tell exactly what exactly is causing this issue. If there is any log files generated during the execution, I will be happy to provide them.

### Environment
1) Windows 10 with NodeJs v16.13.0
2) Angular project
3) Package versions:
    "@nrwl/angular": "13.8.3",
    "@nrwl/cli": "13.8.3",
    "@nrwl/cypress": "13.8.3",
    "@nrwl/eslint-plugin-nx": "13.8.3",
    "@nrwl/jest": "13.8.3",
    "@nrwl/linter": "13.8.3",
    "@nrwl/tao": "13.8.3",
    "@nrwl/workspace": "13.8.3",

**Comment by usarskyy** [comment]
What's funny, the following command works fine:
`npx nx serve project_name --prod`

But building the project fails:
`npx nx build project_name --prod`

**Comment by JonesHong** [comment]
Hey! I have same issue this days.
![截圖 2022-03-12 下午10 54 10](https://user-images.githubusercontent.com/22835128/158022896-fcd761ef-d3d3-4b61-8404-cbb3e6c743ee.png)

I am just build successfully by adding 
`"dependsOn": []`
to project.json > targets >build
![截圖 2022-03-12 下午10 58 53](https://user-images.githubusercontent.com/22835128/158023097-12d9d06b-7c6e-409c-97d1-5e7de0cb673b.png)

![截圖 2022-03-12 下午10 59 15](https://user-images.githubusercontent.com/22835128/158023108-97de6298-fea4-4cbe-a16e-12e8c8b5d6a9.png)

I still don't know why.
But it work for me!

**Comment by JonesHong** [comment]
I am working with Angular and Nestjs by using Nx. I wrote some share code in /libs/*.After I try to combine codes at main.ts both Angular and Nestjs. This happened to me.

**Comment by snowmandev** [comment]
Facing the same issue. I am able to proceed with a work around by running:

`npx @nrwl/tao run _projectName_:build`

If I get the time later on today, I'll try to dig deeper into the issue.

**Comment by usarskyy** [comment]
Hi @JamesHenry 

Sorry for the delay with an answer.

`--verbose` doesn't give much info. The problem was in the file references. After copy-pasting a block of code my IDE automatically imported missing references, one of them was an import from "environment.ts" that belongs to another app. After I changed the path to local "environment.ts", my project started compiling again.
I will try to create a small project that reproduces this problem.

**Comment by JonesHong** [comment]
Same issue at [#2570 ](https://github.com/nrwl/nx/issues/2570)
