### ISSUE TITLE
Lazily loaded module is showing Typescript compilation error.

### ISSUE THREAD

**Issue by jafsparrow** [nrwl/nx#909]
Everything has been working for me till this morning. I am not sure what did I do wrong to get this error.

I have a lazily loaded module which now shows an error that typescipt compilation does not find the particular module.

`       { path: 'events',
        loadChildren:
          '@football/events#EventsModule'
      },`

football is my app name. This did work for me earlier. Now when I 'ng serve' or run the app, I get this error.

ERROR in F:/Projects/football/libs/events/src/lib/events.module.ts
Module build failed: Error: F:\Projects\football\libs\events\src\lib\events.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (F:\Projects\football\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:749:23)
    at plugin.done.then (F:\Projects\football\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

From the other issues of the same type, they all got the issue solved by adding "include' in the tsconfig.app.json or tsconfig.json file. 

I tried adding it in the tsconfig files, not no use.

I have other modules (library) imported (not lazily loaded) the same way but it works fine for me. Problem is only with lazily loaded module.

this particular module (EventsModule) has index.ts file in the src directory which is exporting the event.module.ts. 

`export * from './lib/events.module';`

plz help

**Comment by jafsparrow** [comment]
I am not sure if it has anything to do with Nx. anybody's been facing this issue???

**Comment by FrozenPandaz** [comment]
Hi you are missing that index file from the `includes` in the `tsconfig.app.json`

Example:
```json
  "include": ["**/*.ts", "../../libs/events/src/index.ts"]
```

**Comment by jafsparrow** [comment]
Thanks a lot @FrozenPandaz : It worked when I added to "files" section. Now tried as "include". It worked.. thanks... But I am still wondering why did this come up out of nowhere as it was working before..
