### ISSUE TITLE
Cant uninstall library

### ISSUE THREAD

**Issue by AlePisanu** [nrwl/nx#9097]
I cant uninstall npx make-angular-cli-faster.
How i can do it? If i do npm uninstall make-angular-cli-faster
Nx continue to stay

**Comment by FrozenPandaz** [comment]
Sorry, I'm not sure I understand. What "stays"? The changes to the workspace?

1. `npx make-angular-cli-faster` doesn't keep `make-angular-cli-faster` in your global `npm` packages. It installs a copy of it to invoke.
2. `npm uninstall make-angular-cli-faster` will also not undo the changes to your code.
  a. You can use `git revert` or `git reset` for that.
