### ISSUE TITLE
ng generate lib does not support --routing

### ISSUE THREAD

**Issue by beeman** [nrwl/nx#91]
# Issue

In order to use the libs for building out feature modules for an app it would be very useful to have it generate a routing file. Passing in the `--routing` option when doing `ng generate lib [name]` results in a warning.

# Expected behaviour

Generate `libs/<name>/src/<name>-routing.module.ts` with an empty Routing module.

# Steps to reproduce
```
> ng generate lib pages --ngmodule --routing
The option '--routing' is not registered with the generate command. Run `ng generate --help` for a list of supported options.
```

**Comment by jschwarty** [comment]
Thx @beeman for another good suggestion! With version 0.2.0 we now have support for `routing`, `lazy` and `parentModule` options when creating a new lib. Check out the [docs](https://nrwl.io/nx/guide-nx-workspace#create-an-angular-module-lib) for a description on these new options.

**Comment by tfiwm** [comment]
I tried it but get following error:

ng generate lib portal-comm --routing --lazy --parentModule=apps/main/src/app/main.module.ts
ng generate lib portal-comm --routing --lazy --parentModule=apps/main/src/app/app/main.module.ts

Error: Cannot read property 'toString' of null
Cannot read property 'toString' of null

after debugging i figured out that the **host.read(schema.parentModule)** returns null and this ends up to this error message.

Are the apps not listed to the **host** FileSystemTree?

```javascript
FileSystemTree {
  _actions: 
   ActionList {
     _actions: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] },
  _cacheMap: 
   Map {
     '/libs/portal-comm/src/portal-comm.module.spec.ts' => SimpleFileEntry {
     _path: '/libs/portal-comm/src/portal-comm.module.spec.ts',
     _content: <Buffer 69 6d 70 6f 72 74 20 7b 20 50 6f 72 74 61 6c 43 6f 6d 6d 4d 6f 64 75 6c 65 20 7d 20 66 72 6f 6d 20 27 2e 2f 70 6f 72 74 61 6c 2d 63 6f 6d 6d 2e 6d 6f ... > },
     '/libs/portal-comm/src/portal-comm.module.ts' => SimpleFileEntry {
     _path: '/libs/portal-comm/src/portal-comm.module.ts',
     _content: <Buffer 69 6d 70 6f 72 74 20 7b 20 4e 67 4d 6f 64 75 6c 65 20 7d 20 66 72 6f 6d 20 27 40 61 6e 67 75 6c 61 72 2f 63 6f 72 65 27 3b 0a 69 6d 70 6f 72 74 20 7b ... > },
     '/libs/portal-comm/index.ts' => SimpleFileEntry {
     _path: '/libs/portal-comm/index.ts',
     _content: <Buffer 65 78 70 6f 72 74 20 7b 20 50 6f 72 74 61 6c 43 6f 6d 6d 4d 6f 64 75 6c 65 20 2c 20 70 6f 72 74 61 6c 43 6f 6d 6d 52 6f 75 74 65 73 20 7d 20 66 72 6f ... > },
     '/.angular-cli.json' => SimpleFileEntry {
     _path: '/.angular-cli.json',
     _content: <Buffer 7b 0a 20 20 22 24 73 63 68 65 6d 61 22 3a 20 22 2e 2f 6e 6f 64 65 5f 6d 6f 64 75 6c 65 73 2f 40 61 6e 67 75 6c 61 72 2f 63 6c 69 2f 6c 69 62 2f 63 6f ... > } }
...
...
```
