### ISSUE TITLE
Custom environment variables for executors (at least @nrwl/next:build)

### ISSUE THREAD

**Issue by nzpopa** [nrwl/nx#9108]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I would like to be able to inject custom environment variables inside the configuration block of a build target, eg:

```
  "targets": {
    "build": {
      "executor": "@nrwl/next:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production-local",
      "options": {
        "root": "apps/next-app",
        "outputPath": "dist/apps/next-app"
      },
      "configurations": {
        "production-local": {
            "customEnvVars": [
                "NODE_ENV": "production",
                "NX_ENV": "local"
            ]
        }
      }
    },
```

## Motivation

There are cases when this ability is very useful.

Eg (but not limited to): I'd like to indicate a production build, but also that it's a local build. Why? For example, if `NX_ENV=local`, I don't want to push source maps to Sentry. Only if `NX_ENV=vercel` I'd upload them (or whatever).

I have `lint-staged` configured to run `nx affected:build --base=main`. When I commit, my next app is being build with respect to `"defaultConfiguration":"production"` and I have no way to inject other environment variables to indicate that's a local production build.

## Suggested Implementation

Don't know yet. If someone knows how to do it, I'd gladly implement this feature if I could get some guidance.

What do you think?

**Comment by Bielik20** [comment]
I think you could achieve that with flags, like `nx run next-app:build --stage local` and then rewrite that to env variables in custom next plugin (it is pretty simple to map `process.argv` to env in NextJs). This is what I am doing at work where I need static stages like test and prod, as well as dynamic ones like a branch name. The only problem is that Nx is not very generous in the way it passes those overwrites from project to project. This is actually something I am trying to address here: https://github.com/nrwl/nx/issues/9034
I would appreciate input there as well.

As far as this translation is concerned, it is something like that:
```ts
import yargs from 'yargs';

function withStage(nextConfig = {} as any) {
  const argv = yargs(process.argv.slice(2))
    .options({ stage: { type: 'string' } })
    .parseSync();

  return {
    ...nextConfig,
    env: {
      ...nextConfig.env,
      STAGE: argv.stage,
    },
  };
}

module.exports = withStage;
```
Then just use it in `next.config.js`
