### ISSUE TITLE
enhancement - change the default test target to be headless/watch=false

### ISSUE THREAD

**Issue by gkamperis** [nrwl/nx#911]
Given that Nx and (Angular) uses the workspace and that the idea is to have multiple apps/libs, it no longer makes sense to have the default "test" target to be Chrome and/or watch.

If I have multiple apps/libs then running test launches chrome for each app/lib.
The default target setup launches chrome but then will disappear for the next target.

It makes more sense to have the default test target to be ChromeHeadless and watch=false.

And what would be even better is to create extra "test-watch" targets with Chrome/watch=true and the accompanying scripts in package.json.

**Comment by FrozenPandaz** [comment]
The default for a new workspace now should already be `watch = false`. Allowing `ng test` to go through all the tests without manually exiting it.

> Angular CLI changed the default to have watch in v6 which we adopted for a while but it should have been fixed in `Nx 6.2` (so a while ago).

If you are still seeing the browser stick around after the tests complete, check the `singleRun` property in your `karma.conf.js`.

As for the browser, the choice should be with the developer (the team). The browser chosen has more to do with the environment which the tests are testing against, as opposed to how many projects are being tested. We are going to stay with what AngularCLI defaults to (Chrome) but you can change the browser for all of your projects by changing the config in the root `karma.conf.js` which is extended by all other projects.

Feel free to create your own `test-watch` scripts in `package.json`.

If you are still having trouble with `ng test` we also have `yarn affected:test --all` which will in practice, do the same thing as `ng test` but `watch` will be forced to `false`. We suggest using `yarn affected:test` over `ng test` to intelligently decide which projects need testing.
