### ISSUE TITLE
Doc - NgRx Feature Workflow

### ISSUE THREAD

**Issue by digoburigo** [nrwl/nx#9114]
### Documentation issue

- [x] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/guides/misc-ngrx

### Additional context or description

There is a typo in all the code snippets of the page. After the letter `g` don't have a space.
Example:
`nx g@nrwl/angular:ngrx <featurename> --module=<path-to-module> --defaults [options]`
Correct?
`nx g @nrwl/angular:ngrx <featurename> --module=<path-to-module> --defaults [options]`

**Comment by AgentEnder** [comment]
Hey @digoburigo, I just looked into this and it looks correct to me. I'm going to close this, but let me know if it still seems broken to you.
