### ISSUE TITLE
@nrwl/web:rollup: support for sourceMap option

### ISSUE THREAD

**Issue by layershifter** [nrwl/nx#9119]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

`@nrwl/web:rollup` does generate source maps for output files:

![image](https://user-images.githubusercontent.com/14183168/155697579-df37d5bb-fda0-48cf-b9b4-a8bebb0317a7.png)

This can be verified in [`rollup.impl.ts`](https://github.com/nrwl/nx/blob/e677a1d82d68a47ff1392b1f77cc1276b4da3366/packages/web/src/executors/rollup/rollup.impl.ts): there is nothing that enables sourcemap generation in Rollup. Source maps can be enabled in Rollup with [`output.sourcemap`](https://rollupjs.org/guide/en/#outputsourcemap).

## Motivation

_It's not a blocker as Rollup config could be tweaked via [`rollupConfig`](https://nx.dev/web/package#rollupconfig) and it's what we [are already doing](https://github.com/microsoft/griffel/blob/ff6078d3d9dac9a1d5310a027d41e7d6a75ce959/tools/getRollupOptions.js#L10)._

However, `sourceMap` option is supported in [@nrwl/web:webpack](https://nx.dev/web/build#sourcemap):
https://github.com/nrwl/nx/blob/85da21bf29b4e467e82df467716ba1adff5dea14/packages/web/src/utils/config.ts#L49-L54

For `@nrwl/node:package` it could be configured via TypeScript config.

## Suggested Implementation

- add `sourcemap` option to `@nrwl/web:rollup`

**Comment by AgentEnder** [comment]
Yeah, that makes sense. If you want to implement it, feel free to get a PR in and we can make sure it gets reviewed.

**Comment by layershifter** [comment]
Bump, it's still a thing.

**Comment by goldsam** [comment]
@AgentEnder This issue is not limited to react. Not sure that label is appropriate.

**Comment by AgentEnder** [comment]
react label was previously used for webpack + rollup issues

**Comment by minuz** [comment]
+1 for this. Not having source maps have been a bit of an pain to debug the libs on legacy apps that are not part of the monorepo

**Comment by layershifter** [comment]
bot, keep it open

**Comment by jaysoo** [comment]
Merged PR that adds `sourceMap` option for `@nx/rollup:rollup`: https://github.com/nrwl/nx/pull/27539

It will be in 19.7 (which is end of August).
