### ISSUE TITLE
Update @ngrx/store failed - require to update dependencies

### ISSUE THREAD

**Issue by adnanebrahimi** [nrwl/nx#912]
If I want to update the ngrx store after the initial setup, this error shows up:

Rebuild issue:

**C:\ ng update**

 Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cli                       7.0.1 -> 7.0.6           ng update @angular/cli
      @ngrx/store                        6.1.0 -> 6.1.2           ng update @ngrx/store

**C:\ ng update @angular/cli**
    Updating package.json with dependency @angular/cli @ "7.0.6" (was "7.0.1")...

**C:\ ng update @ngrx/store**
                  Package "@ngrx/store" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0", would install "7.0.4")
                  Package "@ngrx/effects" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0", would install "7.0.4")
                  Package "@ngrx/router-store" has an incompatible peer dependency to "@angular/common" (requires "^6.0.0", would install "7.0.4")

**Comment by FrozenPandaz** [comment]
What _you_ can do id `ng update @angular/core` which will update the angular framework dependencies. I'm not sure why that does not show up in `ng update`... The peer dependencies is the nature of `ng update`. It will not let you update your dependencies to a bad state (by definition of peer dependency restrictions).

As for `@ngrx/store`, the team is working on a `7.0.0` release which is currently in beta. Once it is stable, we will update the dependencies in the Nx workspace.

Closing this issue as it pertains to the Angular CLI.
