### ISSUE TITLE
Angular component with svg template doesn't work with Storybook

### ISSUE THREAD

**Issue by Jad31** [nrwl/nx#9123]
## Current Behavior
I have an Angular component which have a svg as template.
To make it work with Storybook, I have to add webpack configs with the `svg-inline-loader` loader.

## Expected Behavior
i want Storybook to work with Angular components which have svg templates.

## Steps to Reproduce
I provided a minimal repo: https://github.com/Jad31/storybook-inline-svg-angular-issue.git

- `yarn` to install the dependencies
- `yarn run nx run svg-layout:storybook`

### Failure Logs
```bash
ModuleParseError: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <svg [attr.viewBox]="viewbox.minx + ' ' + viewbox.miny + ' ' + viewbox.width + ' ' + viewbox.height">
|     <svg:g
|         workspace-svg-part
```
### Environment
```ts
> yarn run nx report
yarn run v1.22.11

 >  NX   Report complete - copy this into the issue template

   Node : 14.19.0
   OS   : linux x64
   yarn : 1.22.11
   
   nx : 13.8.3
   @nrwl/angular : 13.8.3
   @nrwl/cli : 13.8.3
   @nrwl/cypress : 13.8.3
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.3
   @nrwl/eslint-plugin-nx : 13.8.3
   @nrwl/express : undefined
   @nrwl/jest : 13.8.3
   @nrwl/js : undefined
   @nrwl/linter : 13.8.3
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.3
   @nrwl/tao : 13.8.3
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.3
   typescript : 4.5.5
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
         @angular/animations: 13.2.4
         @angular/common: 13.2.4
         @angular/compiler: 13.2.4
         @angular/core: 13.2.4
         @angular/forms: 13.2.4
         @angular/platform-browser: 13.2.4
         @angular/platform-browser-dynamic: 13.2.4
         @angular/router: 13.2.4
         @angular-devkit/build-angular: 13.2.5
         @angular/cli: 13.2.5
         @angular/compiler-cli: 13.2.4
         @angular/language-service: 13.2.4
         @storybook/angular: 6.4.19

Done in 0.59s.
```

**Comment by mandarini** [comment]
Hi there @Jad31 ! Thanks for filing an issue. I will take a look at the repository you provided, and thank you for that. In the meantime, can you help me understand the following: if you add, as you said. webpack configs with the `svg-inline-loader` loader, is the issue resolved?

**Comment by Jad31** [comment]
> Hi there @Jad31 ! Thanks for filing an issue. I will take a look at the repository you provided, and thank you for that. In the meantime, can you help me understand the following: if you add, as you said. webpack configs with the `svg-inline-loader` loader, is the issue resolved?

Sorry for the bad explanation, i added webpack configs with the `svg-inline-loader` but it doesn't resolve the issue, here is the problem.

**Comment by Coly010** [comment]
Hey @Jad31 !
It looks like the repo you listed either doesn't exist or it is set to private. Could you let me know how to access it so I can take a look at this issue for you?

Thanks!!

**Comment by Jad31** [comment]
Hey @Coly010, the repo was set to private, sorry for that. It is now public.

**Comment by Coly010** [comment]
I opened a PR on your repo containing the following:

```
Issue was coming from your custom `webpack.config.js`.

If you remove that, Storybook builds and serves correctly.

I added a `<text>` tag to your `svg-layout.component.html` so that you can see that storybook is correctly rendering the SVG.
```

That said. Storybook is not correctly handling the `.svg` file as a templateUrl, which is supported by Angular.

There's an open issue on the Storybook Repo about this:
https://github.com/storybookjs/storybook/issues/16438 

It would be worthwhile commenting on that issue to help them see the issue and the impact. 

This is outside our control right now, so I'll set this as blocked by third party.

**Comment by mandarini** [comment]
Hi all! I am going to close this issue, since it has a workaround, and it's a third-party issue, not controlled by us. If you think it makes sense, we can re-open this in the future!
