### ISSUE TITLE
Unable to use Next js 12 middleware feature with Next js apps generated in Nx without a custom server

### ISSUE THREAD

**Issue by writam-roy** [nrwl/nx#9126]
## Current Behavior
Operating System:
Platform: win32
Arch: x64
Version: Windows 10 Enterprise
Binaries:
Node: 14.16.0
npm: 6.14.11
Yarn: 1.21.1
pnpm: N/A
Relevant packages:
next: 12.1.0
react: 17.0.2
react-dom: 17.0.2

I see an issue with Next js apps generated within Nx monorepo,where it is not being able to use middleware functionalities and there is an error saying " cannot use middleware without adding port and hostname to next js server".

Please suggest what should be the content of the custom server in this scenario to proceed,as with this code attached in the example - https://nextjs.org/docs/advanced-features/custom-server

I get futher issues from Nx saying "customServer is not a function".(Note:- I have made necessary changes to add server.js as a custom path to the Nx project)

## Expected Behavior

Next js apps created with Nx next plugins should support the feature out of the box without the need for a custom server.

## Steps to Reproduce

On starting off the app using  "nx serve appname" this is the error - 
![image](https://user-images.githubusercontent.com/84510770/155762939-5833600c-6479-4210-988b-4d2d5de918b5.png)

![image](https://user-images.githubusercontent.com/84510770/155762887-bd3137c9-e871-4671-92ba-348b741d8e88.png)

Unable to share the PR or repo link as it is a private repo

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

  NX   Report complete - copy this into the issue template

   Node : 14.16.0
   OS   : win32 x64
   yarn : 1.21.1

   nx : 13.8.3
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.3
   @nrwl/cypress : 13.5.3
   @nrwl/detox : undefined
   @nrwl/devkit : 13.5.3
   @nrwl/eslint-plugin-nx : 13.5.3
   @nrwl/express : undefined
   @nrwl/jest : 13.5.3
   @nrwl/js : 13.5.3
   @nrwl/linter : 13.5.3
   @nrwl/nest : undefined
   @nrwl/next : 13.5.3
   @nrwl/node : 13.5.3
   @nrwl/nx-cloud : undefined
   @nrwl/react : 13.5.3
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.5.3
   @nrwl/tao : 13.8.3
   @nrwl/web : 13.5.3
   @nrwl/workspace : 13.5.3
   typescript : 4.3.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

**Comment by adamwdennis** [comment]
Try adding the hostname and port to your app-specific `project.json`, under your "serve" target options...

e.g.
```json
"serve": {
      "executor": "@nrwl/next:server",
      "options": {
        "buildTarget": "website:build",
        "dev": true,
        "port": 4200,
        "hostname": "localhost"
      },
...
}
```

**Comment by writam-roy** [comment]
Thanks @adamwdennis that works!...:)

**Comment by mononoke-choi** [comment]
i have same issue and then added port and hostname in 'project.json' file.
unfortunately after that i couldn't access localhost using android by ip address.
how can i accomplish both of them?

> i've used latest nx with next@12.1.0
