### ISSUE TITLE
Angular-specific Prettier HTML formatting

### ISSUE THREAD

**Issue by emilio-martinez** [nrwl/nx#913]
Prettier with HTML formatting was added in via #884/#889. However, Prettier has a specific parser that formats additional Angular syntax in addition to the default HTML syntax—[see "angular" option in Prettier parser docs](https://prettier.io/docs/en/options.html#parser).

Perhaps the [Prettier config defaults](https://github.com/nrwl/nx/blob/master/packages/schematics/src/utils/common.ts#L35-L38) should be augmented to add [overrides](https://prettier.io/docs/en/configuration.html#configuration-overrides) to specify the parser for html within the `apps` and `libs` directories?

```json
{
  "singleQuote": true,
  "overrides": [
    {
      "files": "{apps,libs}/**/*.html",
      "options": {
        "parser": "angular"
      }
    }
  ]
}
```

**Comment by emilio-martinez** [comment]
Ah, thank you! I missed that part of the docs.

**Comment by Githamza** [comment]
I have prettier 1.18.1 version but it does not format my html files as expected, how can I activate angular html formatting ?

**Comment by ExploreHW** [comment]
@Githamza Try below
```prettier --write \"src/app/**/*.component.html\" --parser angular```
