### ISSUE TITLE
tslib installed in package.json deps regardless of existence

### ISSUE THREAD

**Issue by dustinsgoodman** [nrwl/nx#9138]
## Current Behavior

https://github.com/nrwl/nx/pull/6763 introduced a behavior when running `nx workspace-generator` tslib is automatically installed into the project's `dependencies`. This change does not attempt to detect `tslib` in the `devDependencies` (arguably where it belongs). This introduces an unexpected side effect when working with workspace generators and causes issues when tslib is already installed via `devDependencies`.

## Expected Behavior

Instead of the behavior introduced in #6763, I believe this should do the following:

1. Initializing an nx workspace should already include `tslib` as a `devDependencies`
2. If `tslib` is only essential for workspace generators and should not be part of an nx workspace initialization, then it should be installed as a `devDependencies` and not a regular `dependencies`
3. If `tslib` is already installed as either a `dependencies` or `devDependencies`, it should not be installed regardless.

Point 3 above is the most important IMO but I'd like to see 1 and/or 2 addressed.

## Steps to Reproduce

I can push up a repo if you need it but the reproduction can be seen easily by running the following commands in your terminal:

```
npx create-nx-workspace
# choose any of the presets - it doesn't matter
nx generate @nrwl/workspace:workspace-generator my-generator
nx workspace-generator my-generator test
```

See tslib added to `dependencies` in package.json

Alternatively to see 3 in action, do the following instead:

```
npx create-nx-workspace
# choose any of the presets - it doesn't matter
nx generate @nrwl/workspace:workspace-generator my-generator
yarn add -D tslib
nx workspace-generator my-generator test
```

See tslib added to `dependencies` in package.json ignoring the `devDependencies` version.

### Environment
<img width="1287" alt="Screen Shot 2022-02-27 at 2 55 08 PM" src="https://user-images.githubusercontent.com/1815379/155899537-437a8ba8-a9e6-47e7-99b2-f7687f9bb88a.png">

```
Node : 16.13.0
   OS   : darwin arm64
   npm  : 8.1.0

   nx : 13.8.3
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.3
   @nrwl/cypress : undefined
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.3
   @nrwl/eslint-plugin-nx : 13.8.3
   @nrwl/express : undefined
   @nrwl/jest : 13.8.3
   @nrwl/js : undefined
   @nrwl/linter : 13.8.3
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : undefined
   @nrwl/tao : 13.8.3
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.3
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
```

**Comment by SolarLiner** [comment]
`tslib` is not a compile-time dependency but a runtime one - you'll need it to execute compiled TypeScript code. It contains all helper functions (ie. for `esModuleInterop`) that are used when needed in the resulting JavaScript code. https://www.npmjs.com/package/tslib

**Comment by dustinsgoodman** [comment]
Right, `tslib` is very helpful and serves a purpose. However, the way it's used in this context should be a dev dependency concern and not a production dependency. It is only used for a local dev script runtime and not a production build. It has no place in the dependencies section. Regardless of either of these points though, it needs to respect existing entries in a package.json and should be documented as a required dependency of workspace generators rather than installed at runtime.

**Comment by dustinsgoodman** [comment]
Bump to prevent close

**Comment by dustinsgoodman** [comment]
Bump for the bot

**Comment by AgentEnder** [comment]
Hey @dustinsgoodman 👋, sorry for taking a while to get to this one. I believe it should have been fixed with the changes to workspace generators over the past 6 months 🤦.

Can you check it out and verify?

**Comment by FaisalAfroz** [comment]
I am also facing same issue by default tslib is added to a new lib. while lint the app error  `The "tslib" package is not used by "lib-name" project ` . Although tslib is very useful, I think by default there should be no dependency on it in new library.
