### ISSUE TITLE
[jest-dom] TypeError: expect(...).toBeInTheDocument is not a function

### ISSUE THREAD

**Issue by jonybekov** [nrwl/nx#9140]
## Current Behavior

I have configured jest.config.js globally and added setupFilesAfterEnv as explained in https://github.com/testing-library/jest-dom

But setupFilesAfterEnv is not injecting jest.setup.ts file to tests.
Thus, compiler cannot find matcher functions of jest-dom.

Note: If I configure it on app/lib level, it's working. But global configuration is not working

## Expected Behavior

`import "testing-library/jest-dom"` should be injected to every test file.

## Steps to Reproduce

1. Create jest.setup.ts file in nx workspace root and import '@testing-library/jest-dom'.
2. Add `setupFilesAfterEnv: ['<rootDir>/jest.setup.ts']` to global jest.config.js
3. Use any jest-dom matcher in your test (Example: toBeInTheDocument).
4. Run that test.

### Failure Logs

![image](https://user-images.githubusercontent.com/39439363/155929854-b3969df5-530d-4c1c-b8a4-be9a31c9dadb.png)

**Comment by sdjnes** [comment]
Try adding it to the global `jest.preset.js`. I have this working inside Jest perfectly, unfortunately TS doesn't seem to like it, even after including the setup file as part of the `include` files in the TS config. I receive the following error for all custom matchers:


```
Property 'toBeEnabled' does not exist on type 'JestMatchers<HTMLElement>'.ts(2339)
```

**Comment by jonybekov** [comment]
> Try adding it to the global `jest.preset.js`. I have this working inside Jest perfectly, unfortunately TS doesn't seem to like it, even after including the setup file as part of the `include` files in the TS config. I receive the following error for all custom matchers:
> 
> ```
> Property 'toBeEnabled' does not exist on type 'JestMatchers<HTMLElement>'.ts(2339)
> ```

I've tried to do that But this method requires to have jest.setup.ts file (which imports @testing-library/jest-dom) in every nx project (apps, libs and etc.)

**Comment by the-ult** [comment]
Any new/tips/tricks how we can use `@testing-library/jest-dom` globally?

**Comment by Ronaldo-Maciel** [comment]
I have the some problem!

**Comment by the-ult** [comment]
Strange. Cause it worked without the extra `@types`.
But thanks at least I don't get any more errors.

Next step.. Setting `testing-library/jest-dom`globally (once)

**Comment by umyomyomyon** [comment]
I had same error and resolved by write `import '@testing-library/jest-dom';` in `.test.tsx`file.

**Comment by silogos** [comment]
install `@types/testing-library__jest-dom` and add configuration at `jest.config.js`
```
{
  setupFilesAfterEnv: [
    "@testing-library/jest-dom/extend-expect"
  ]
}
```

**Comment by PodStuart** [comment]
@silogos - thank you that worked for me

i did not have to explicitly import @types/testing-library__jest-dom but the setupFilesAfterEnv sorted it for me

**Comment by srbagg** [comment]
@barbados-clemens any updates on this?

**Comment by rizaldirnm** [comment]
Install:
-

> 1. @testing-library/jest-dom
> 2. @types/testing-library__jest-dom

Setting up
-

1. Create `setupTests.ts` in root your project and add the following code
```
import '@testing-library/jest-dom'
```

2. Edit `**/apps/your-app-here/jest.config.ts` with following the code

```
export default {
    ....
    setupFilesAfterEnv: ['../../setupTests.ts'],
}
```

From here you can run the Test smoothly.. BUT you still have kind issue with typescript, to fix this follow next step

3. Edit `**/apps/your-app-here/tsconfig.json`

```
{
   ...

   "include": [
      ....
       "../../setupTests.ts",
    ]

   ...
}
```

You should ready to Go.

**Comment by sgibson-magnite** [comment]
You should just need to add a setupTests.js file in your src directory that imports @testing-library/jest-dom

`import '@testing-library/jest-dom';`

**Comment by barbados-clemens** [comment]
@rizaldirnm you should probably put this in the tsconfig.spec.json, not the tsconfig.json.

**Comment by barbados-clemens** [comment]
@srbagg can you try what was posted above?

**Comment by barbados-clemens** [comment]
@jonybekov placing it into the jest.preset.js works oddly enough, only issue you have is the `<rootDir>` is going to be where the project is. so you just have to resolve it like so

```js
const nxPreset = require('@nrwl/jest/preset').default;
const path = require('path');
module.exports = {
  ...nxPreset,
  setupFilesAfterEnv: [path.resolve(__dirname, '<path from root of your workspace to your setup script>')],
};
```

[See this commit for all that I changed to get it working](https://github.com/barbados-clemens/testing-validation-bench/commit/4292b3265af43e46d07a33214968140fe9443996)

though I'll note I wouldn't recommend setting this up globally as it will apply to everything in your monorepo, I'd rather suggest setting up a shared jest preset that you import and spread in your projects you wish to use it in. (that is unless your entire monorepo is going to use this library and won't have conflicts with it)

**Comment by AndresdoSantos** [comment]
@rizaldirnm thanks bro!

**Comment by komalharmale** [comment]
TypeError: expect(...).toBeOnTheScreen is not a function

      37 |     const toClick = await screen.findByText('Go To Login Screen');
      38 |     const header = screen.getByText('List of numbers from 1 to 20');
    > 39 |     expect(header).toBeOnTheScreen();
         |                    ^
      40 |     // expect(tree).toBeCalledWith('Dashboard')    
      41 | })

**Comment by xousik** [comment]
For me it was enough to add:
import '@testing-library/jest-dom'
to my setupTest.ts file
