### ISSUE TITLE
An application gets run multiple times in development

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#9148]
## Current Behavior
When run in development, an application's `main.tsx` gets called 3 times.
`nx serve ...`

## Expected Behavior
The `main.tsx` should be called only once both in production and during development.
This started happening some time ago (a month or two ago).

### Environment

```
  Node : 14.16.0
  OS   : win32 x64
  yarn : 3.0.2

  nx : 12.9.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.9.0
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by r4hulp** [comment]
I am observing the same. Did you manage to figure it out @nemonemi?

**Comment by nemonemi** [comment]
Hello, @r4hulp.
Not yet. I am currently debugging it. So far, I have noticed that it doesn't occur in an empty workspace.

**Comment by nemonemi** [comment]
@r4hulp,
I've had an iframe loaded locally that was causing the reload. In my case, it had nothing to do with NX.
I will be closing this ticket, but if you are still having an issue, do let me know and we can re-open it.
