### ISSUE TITLE
`--experimental-ivy`  not generating enableIvy code

### ISSUE THREAD

**Issue by xmlking** [nrwl/nx#915]
`ng g app webapp --unit-test-runner=jest --experimental-ivy`

## Expected Behavior
Should generate code with `enableIvy` support. 
 

## Current Behavior
`enableIvy` enabled code is not generated

Should generate:

tsconfig.app.json
```json
  "angularCompilerOptions": {
    "enableIvy": "ngtsc"
  }
```

main.js
```ts
import { AppComponent } from './app/app.component';
import { ɵrenderComponent as renderComponent } from '@angular/core';

renderComponent(AppComponent);
```

```ts
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```
## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

`ng g app webapp --unit-test-runner=jest --experimental-ivy`

### Context

Please provide any relevant information about your setup:

```
@angular-devkit/architect         0.11.0-rc.0
@angular-devkit/build-angular     0.11.0-rc.0
@angular-devkit/build-optimizer   0.11.0-rc.0
@angular-devkit/build-webpack     0.11.0-rc.0
@angular-devkit/core              7.1.0-rc.0
@angular-devkit/schematics        7.1.0-rc.0
@ngtools/webpack                  7.1.0-rc.0
@schematics/angular               7.1.0-rc.0
@schematics/update                0.11.0-rc.0
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
```

nx 7.1.0

**Comment by xmlking** [comment]
Agree @FrozenPandaz tried manual integration, but not much success

**Comment by leon** [comment]
The problem isn't with nx, it's with angular cli, because I just got the same problem there.

I was able to get it working by adding the missing
```
"angularCompilerOptions": {
  "enableIvy": "ngtsc"
}
```

to tsconfig.app.json

**Comment by bcabanes** [comment]
Closing this old issue, we have now a preset for Nx with Ivy.
