### ISSUE TITLE
SCSS React library with swc fails to build

### ISSUE THREAD

**Issue by jcguarinpenaranda** [nrwl/nx#9150]
## Current Behavior
I created a React UI library, which works ok in dev mode but fails to build.

![imagen](https://user-images.githubusercontent.com/7200821/156176099-5525ff7b-24e1-410f-acb8-2b67ae0d5334.png)

It seems to be the scss modules are being treated as JS at some point, which should not be as they should be processed before by SASS.

## Expected Behavior
I would expect the library to build without problems.
Related content on: https://github.com/nrwl/nx/pull/2719 

## Steps to Reproduce
The setup I have is very minimal, two components in the lib: `full-page-wrapper` and `box`
The styles for the first component are:

![imagen](https://user-images.githubusercontent.com/7200821/156176488-7a8abb99-8052-446c-b4ee-4e818a29d835.png)

And the react component looks like this
![imagen](https://user-images.githubusercontent.com/7200821/156176553-4e07e758-a921-4fb5-9ede-4cdac2a5b12c.png)

I don't include the second component for the sake of simplicity, but it's also a very simple one. As you see I'm using a `.modules.scss` file that is imported at the top of the component and then use the key `full-page-wrapper` coming from the object it returns, that matches what I have in the `scss` module.

I have tried using the `styles` and `stylePreprocessorOptions` options without luck. My project file looks like this:
![imagen](https://user-images.githubusercontent.com/7200821/156176714-02570d62-620c-4a1d-8ebd-baf511f892a2.png)

Also added the assets to be compiled
![imagen](https://user-images.githubusercontent.com/7200821/156176738-be8dde7d-6d76-4113-b866-7ae89fadd926.png)

When I'm working on another app that is connected to this React library in development mode, I have no issue whatsoever and it's very fast. When I build I see the error shown at the top of this issue.

### Failure Logs
[](https://nx.app/runs/btcaeVyltfH)

### Environment
Windows 11

![imagen](https://user-images.githubusercontent.com/7200821/156177044-dd3d652b-50e3-421c-87f2-9b0fba9d2a7e.png)

**Comment by jcguarinpenaranda** [comment]
Nx Cloud Run: https://nx.app/runs/btcaeVyltfH

**Comment by jcguarinpenaranda** [comment]
I found another way of reproducing.

1. Generate a new react library, using --name=test2 --buildable --importPath=@org/scss-test --publishable
2. Try to build the generated library. Works OK
3. Add any class to the `css` file generated
4. Try to build again. Error thrown is the same as my original error found. Example: https://nx.app/runs/8zVEWJInpvk

**Comment by aruke** [comment]
I'm having the exact same issue. And I spent hours configuring `rollup.config.js` for CSS Modules. 
For folks who are here because of CSS Modules, a tentative fix would be to change the compiler to `babel`.

**Comment by MarcieMarc425** [comment]
Is this issue still being investigated? I am having the exact same issue - not being able to use SWC to bundle react libraries with the unexpected token error for css/sass modules.

**Comment by MarcieMarc425** [comment]
seems like this is no longer an issue when I bump NX version to `14.8.1`. (I have not extensively tested which version gets rid of this issue, but I previously was experiencing this issue in NX version `14.3.x`)

**Comment by mandarini** [comment]
I believe that this is no longer an issue in the latest version of Nx. I will be closing this issue. Feel free to ping me to reopen if the issue comes up again!
