### ISSUE TITLE
angular application generator error

### ISSUE THREAD

**Issue by simcoder** [nrwl/nx#9161]
when you run angular application generator it errors 
## Current Behavior
it errors if you try to use angular application generator
## Expected Behavior

it should create/scaffold app
## Steps to Reproduce
run generate application

.. I know what the issue is. 
style: 'none', line 91 application.ts file
it need to be 
style: options.style

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by AgentEnder** [comment]
Can you post the output of `nx report` as well as the error message you are receiving?
