### ISSUE TITLE
Add deleteOutputPath option to @nrwl/node:webpack executor

### ISSUE THREAD

**Issue by jaytavares** [nrwl/nx#9167]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Addition of a `deleteOutputPath` option to the @nrwl/node:webpack executor

## Motivation
I am running into some issues with stale build output. For example, a static asset file generated only via one build configuration remains when an alternate build configuration is used. That file ends up in the Nx cache and pollutes the subsequent cached output of the second build.

## Suggested Implementation
As implemented in the @nrwl/web:webpack executor

## Alternate Implementations
none necessary

**Comment by AgentEnder** [comment]
Hey! I see you checked the box saying you'd be willing to implement. This sounds sane to me, so feel free to work on the PR and ask any questions that come up.
