### ISSUE TITLE
Stories Generator to support MDX

### ISSUE THREAD

**Issue by ChazUK** [nrwl/nx#9172]
## Description
Update the Stories Generator to support MDX format. 

## Motivation
Using storybook with MDX story files allows for more comprehensive documentation with inline component demos.
https://storybook.js.org/docs/react/writing-docs/mdx

## Suggested Implementation
`@nrwl/angular:stories project --format mdx`
`@nrwl/angular:stories project --format csf`

**Comment by mandarini** [comment]
Hi @ChazUK ! Thanks for the feature suggestion! How would you like to take this up?

**Comment by mandarini** [comment]
Hi @ChazUK ! 

So, answer to (1):

The `generateFiles` method takes a `srcFolder` string, which is actually the directory of the template files that are going to be used. In our case it's the [packages/angular/src/generators/component-story/files](https://github.com/nrwl/nx/tree/master/packages/angular/src/generators/component-story/files) directory. You would need to create two folders, one for csf and one for mdx, and add logic in the generator to chose either one or the other as the templates path. Does this make sense? Are you familiar with the template syntax?

For (2), we'll see this eventually, hehe.

**Comment by mandarini** [comment]
(assigning myself, so that I watch this issue and help if needed)

**Comment by ChazUK** [comment]
@mandarini, yep I've made a few generators before so I'll be able to handle that. I'll look at the migration stuff which I haven't done before.

**Comment by mandarini** [comment]
Keeping this unstale just in case anyone's interested in contributing!

**Comment by mandarini** [comment]
I will be closing this feature request now. It is not in our immediate plans! If anyone is interested, you can take it up and I can review/help!

Thank you!
