### ISSUE TITLE
Next js apps with custom server throws "customServer is not a function"

### ISSUE THREAD

**Issue by writam-roy** [nrwl/nx#9179]
## Current Behavior

I have next js app in Nx monorepo and whenever I add a server.js file within the app and try to serve the app,I get this error saying "customServer is not a function"
## Expected Behavior

Ideally apps should work with a custom server wrapper
## Steps to Reproduce

Add server.js file in the root directory and then within serve command of project.json with customServerPath add the path to the file and then there is this issue.
Attaching screenshot of the server file and serve config -
![image](https://user-images.githubusercontent.com/84510770/156621955-3a18a3f2-821d-4d85-9334-784a7ece179b.png)
Server file code - 
// server.js(located within src folder)
const { createServer } = require('http')
const { parse } = require('url')
const next = require('next')

const dev = process.env.NODE_ENV !== 'production'
const hostname = 'localhost'
const port = 3000
// when using middleware `hostname` and `port` must be provided below
const app = next({ dev, hostname, port })
const handle = app.getRequestHandler()

app.prepare().then(() => {
  createServer(async (req, res) => {
    try {
      // Be sure to pass `true` as the second argument to `url.parse`.
      // This tells it to parse the query portion of the URL.
      const parsedUrl = parse(req.url, true)
      const { pathname, query } = parsedUrl

      if (pathname === '/welcome') {
        await app.render(req, res, '/welcome', query)
      } else if (pathname === '/c;osed') {
        await app.render(req, res, '/closed', query)
      } else {
        await handle(req, res, parsedUrl)
      }
    } catch (err) {
      console.error('Error occurred handling', req.url, err)
      res.statusCode = 500
      res.end('internal server error')
    }
  }).listen(port, (err) => {
    if (err) throw err
    console.log(`> Ready on http://${hostname}:${port}`)
  })
})

![image](https://user-images.githubusercontent.com/84510770/156622134-ad234757-cac1-46fe-8393-eabd56f60cd2.png)

Cannot share PR/code as its a private repo

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

![image](https://user-images.githubusercontent.com/84510770/156622251-2ce7c5bb-f74d-4c8e-9a14-b31455c0e1ce.png)

### Environment

  Node : 14.16.0
   OS   : win32 x64
   yarn : 1.21.1
   
   nx : 13.8.3
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.3
   @nrwl/cypress : 13.5.3
   @nrwl/detox : undefined
   @nrwl/devkit : 13.5.3
   @nrwl/eslint-plugin-nx : 13.5.3
   @nrwl/express : undefined
   @nrwl/jest : 13.5.3
   @nrwl/js : 13.5.3
   @nrwl/linter : 13.5.3
   @nrwl/nest : undefined
   @nrwl/next : 13.5.3
   @nrwl/node : 13.5.3
   @nrwl/nx-cloud : undefined
   @nrwl/react : 13.5.3
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.5.3
   @nrwl/tao : 13.8.3
   @nrwl/web : 13.5.3
   @nrwl/workspace : 13.5.3
   typescript : 4.3.5
   rxjs : 6.6.7

**Comment by kirjai** [comment]
hi @writam-roy , thanks for opening the issue!

Defining a custom server for next.js apps in Nx has a slightly different syntax to vanilla next.js. you need to export the custom server function from your `server.js` file:

```js
module.exports = (app) => {
  app.prepare().then(/*etc.*/)
}
```

---

Another thing to point out, is that you *don't need to* require / import the `"next"` module and instantiate a server yourself, like so:
```js
// no need to do this
const next = require('next');
const app = next({/*...*/});
```
the function that you export from your `server.js` file will be given a next.js server instantiated within Nx in the function arguments:
```js
//                 \/ - here it is
module.exports = (app) => {
  app.prepare().then(/* etc. */)
}
```

---

we'll be adding the docs for this in the future, so apologies that you had to stumble upon this, and that it hasn't been documented yet.

give this a try and please don't hesitate letting us know if it still doesn't work for you! i'll re-open the issue, if that's the case
