### ISSUE TITLE
Remove publishConfig.directory when copying to dist folder

### ISSUE THREAD

**Issue by JakeGinnivan** [nrwl/nx#9185]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

I use https://github.com/changesets/changesets with PNPM to publish my NPM packages, NX builds it's packages into a dist/ folder. This means the location of the packages Changesets needs to publish is different.

This can be resolved by adding the following config to your package.json

```
"publishConfig": {
    "directory": "../../dist/libs/nx-terraform"
},
```

The problem is that this config gets copied to the dist/libs/nx-terraform folder, and then during publish it will look at that dir, see the directory config again and then go looking in dist/dist/libs/nx-terraform which does not exist.

When copying the package.json to the dist folder, NX should delete the publishConfig.directory key if it exists to prevent this issue.

## Motivation

Better interop with other mono repo tooling.

## Suggested Implementation

After the package.json is copied into the dist folder, delete the publishConfig.directory key if it exists

## Alternate Implementations

I can't think of another good implementation.

**Comment by wobo-nate** [comment]
Thanks for the tip about `publishConfig.directory`. I'm currently working around this issue by using a `prepublish` npm script which simply reads the `dist/lib/my-lib/package.json` file, deletes `publishConfig.directory`, and writes the file. Would be fantastic if this behavior could be supported by nx, even if it's not a default.

**Comment by andersonba** [comment]
Ping

**Comment by andersonba** [comment]
Ping
