### ISSUE TITLE
Updating dependencies & peer dependencies

### ISSUE THREAD

**Issue by dominikspiertz** [nrwl/nx#9193]
## Current Behavior
We have been using nx for two years now and have stumbled upon a problem that conflicts our workflow and decreases our productivity. We are updating nx and our third party dependencies inside the package.json every other week to make sure we stay up-to-date with nx and packages we build our features with. Now nx has some fixed packages inside the package.json that are touched by the migrations (e.g. eslint) and we have other packages that do not interfer with nx (e.g. eslint-config-airbnb). 

When updating our packages we make sure to only update the ones in the package.json to the newest version, that are added without a fixed version. But nowadays every update we try to do is not possible without peer dependencies to be up-to-date as well or are not updated at all.

Our current workflow is to delete the .lock file (yarn.lock for us), update non-fixed packages, execute nx update and check the peer dependencies. Since we have been working for two years with nx we had a lot of packages that we found where not updated at all. So what we also do, we create a new empty workspace with nx and compare the package.json from the new project with ours.

An example for updating all peer dependencies would be taking all the linting packages in consideration. Currently I would expect essential linting packages with a fixed version (E.g. eslint-plugin-react, eslint-plugin-import, eslint-plugin-jsx-a11y) to be updated whenever the eslint package is updated.

## Expected Behavior
Dependency updates for fixed versions should be more reliable in terms of peer dependencies

## Steps to Reproduce
Use the latest version (13.8.4) Create a new workspace with a react project and see the issue of eslint-plugin-jsx-a11y to be incompatible with eslint version 8

### Failure Logs
warning " > eslint-config-airbnb@19.0.4" has incorrect peer dependency "eslint-plugin-import@^2.25.3".
warning " > eslint-config-airbnb@19.0.4" has incorrect peer dependency "eslint-plugin-jsx-a11y@^6.5.1".
warning " > eslint-config-airbnb@19.0.4" has incorrect peer dependency "eslint-plugin-react@^7.28.0".
warning " > eslint-plugin-jsx-a11y@6.4.1" has incorrect peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7".

### Environment
   Node : 16.14.0
   OS   : darwin x64
   yarn : 1.22.17
   
   nx : 13.8.4
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.4
   @nrwl/cypress : 13.8.4
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.4
   @nrwl/eslint-plugin-nx : 13.8.4
   @nrwl/express : undefined
   @nrwl/jest : 13.8.4
   @nrwl/js : 13.8.4
   @nrwl/linter : 13.8.4
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : 13.8.4
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.4
   @nrwl/tao : 13.8.4
   @nrwl/web : 13.8.4
   @nrwl/workspace : 13.8.4
   typescript : 4.4.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         nx-stylelint: 12.3.1

**Comment by realityfilter** [comment]
nrwl/eslint-plugin-nx has indeed very old peerDependencies of `@typescript-eslint/eslint-plugin: 5.10.2`
This should be updated frequently.

**Comment by michaelmarcus-ml** [comment]
nrwl/express plugin has its Express peer dependency [pinned to 4.17.2](https://github.com/nrwl/nx/blob/master/packages/express/package.json#L37). While this is a fairly recent version, it is preventing us from upgrading to 4.18.0 or even 4.17.3. The [peer dependency version should be more lenient](https://nodejs.org/es/blog/npm/peer-dependencies/#using-peer-dependencies) to allow for such upgrades.
