### ISSUE TITLE
Permission denied when deploy to vercel after adding ignore-vercel-build.sh

### ISSUE THREAD

**Issue by norassystemes** [nrwl/nx#9200]
<html>
<body>

Cloning completed: 840.035ms
--
04:46:10.679 | Running "./tools/ignore-vercel-build.sh"
04:46:10.684 | /bin/sh: ./tools/ignore-vercel-build.sh: Permission denied
04:46:10.688 | Error: Command failed with exit code 126: ./tools/ignore-vercel-build.sh
04:46:10.688 | at a1t (/var/task/sandbox.js:182:57)
04:46:10.688 | at /var/task/sandbox.js:182:9995
04:46:10.688 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
04:46:10.688 | at async kLt (/var/task/sandbox.js:214:390)
04:46:10.688 | at async YUe (/var/task/sandbox.js:212:398)
04:46:10.688 | at async MLt (/var/task/sandbox.js:216:4840)
04:46:10.688 | at async LLt (/var/task/sandbox.js:216:4540) {
04:46:10.688 | shortMessage: 'Command failed with exit code 126: ./tools/ignore-vercel-build.sh',
04:46:10.688 | command: './tools/ignore-vercel-build.sh',
04:46:10.688 | exitCode: 126,
04:46:10.689 | signal: undefined,
04:46:10.689 | signalDescription: undefined,
04:46:10.689 | stdout: undefined,
04:46:10.689 | stderr: undefined,
04:46:10.689 | failed: true,
04:46:10.689 | timedOut: false,
04:46:10.689 | isCanceled: false,
04:46:10.689 | killed: false
04:46:10.690 | }

</body>
</html>

**Comment by AgentEnder** [comment]
Hey @norassystemes, can you make sure the shell script is marked as executable? You'll need to run something like `chmod +x tools/scripts/ignore-vercel-build.sh` and commit the results.

**Comment by Jesperson** [comment]
I'm having the same issue, my file is marked as executable.

**Comment by Jacqueline-Kelly** [comment]
Where do we run this chmod +x tools/scripts/ignore-vercel-build.sh command?
