### ISSUE TITLE
Add external `$ref` resolution to allow modular schemas for generators/executors

### ISSUE THREAD

**Issue by adam-coster** [nrwl/nx#9206]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

*(I'll likely implement my own, repo-specific approach by including schema-building in my custom builders. I'm not familiar enough with the nx codebase to be confident I could find the correct central endpoints for schema loading.)*

## Description

I would like the generator/executor JSON Schemas to allow for resolution of *external* references. In particular references to other JSON Schemas within the project, though being able to use remote URLs would also be great.

nx uses JSON Schema for executors and generators, which are used as documentation, sources for auto-generation of UI elements and CLI arguments, and validation of inputs.

## Motivation

Generator/executor options are frequently re-used, but nx provides no tooling to break them into actual re-usable components. This creates a DRY problem that is particularly trick since JSON Schemas are already hard to read and write, and people are not very familiar with schema tools (on average).

Allowing Schema modularity would make the maintainability of the nx repo itself easier (check any two official nx schemas and you'll see what I mean), and will provide the same benefit to plugin authors.

## Suggested Implementation

There are many well-established, well-tested, and heavily-used JSON Schema libraries and tools out there. One of these existing tools is [json-schema-ref-parser](https://www.npmjs.com/package/json-schema-ref-parser), which does exactly what the label describes.

For this specific feature that package is a perfect fit:

- It specifically and *only* performs `$ref` resolution, so no extra features are being added
- It can be added to nx wherever the centralized Schema-loading functionality is, as an initial step. Since this library does nothing else, *no other changes* would need to be made to the nx code. It's basically the addition of one dependency and one line of code, to enable a much better developer experience 
- It will handle external references from the filesystem *and* remote URLs, out of the box
- It allows schemas to be written in YAML, which is a much friendlier authoring format for what is otherwise a fairly complex JSON structure

(I found a lot of schema-related code in the nx source, but couldn't find a function/class whose job it was to be the schema-reader. In the above points I'm assuming that schema-loading makes use of some common entrypoint.)

## Alternate Implementations

If the nx team does not want to add another dependency, custom implementation of basic external `$ref` resolution wouldn't be too big of a deal.

Nx already lists `node-fetch` [as a dependency](https://github.com/nrwl/nx/blob/efedd2eff78700a72bcc30bdf7450656860a4ffb/package.json#L194), so no additional deps would be added.

As far as I can tell, all of nx's current `$ref` resolution is handled here:

https://github.com/nrwl/nx/blob/e54e36e2ab35e60cdf025aca3569c5a9e1095a9c/packages/tao/src/shared/params.ts#L486-L495

Without any bells and whistles (error & input handling, etc), it could be changed to something like this:

```ts
async function resolveDefinition(ref: string, schema: Schema, schemaPath: string) {
  // Could continue to enforce the `#/definitions` requirement,
  // but also allow a URI to prefix it. For example, the following
  // would be valid:
  // - ../local-folder/my-dope-local-schema.json/#/definitions/reusable-subschema
  // - https://example.com/my-dope-schema.json/#/definitions/reusable-subschema
  // - #/definitions/less-reusable-internal-subschema
  //
  // The JSON Schema spec doesn't require that `$ref` pointers specifically
  // point at the root "definitions" field. Perhaps more importantly, the "definitions"
  // field name is from older drafts of JSON Schema (current drafts use "$defs").
  // The requirement could thus be dropped.
  //
  // For simplicity, the following:
  // - Removes the requirement to point at a "definitions" field
  // - Assumes that a hash exists in the ref, though that isn't strictly required by spec
  // - Minimal error handling

  const [, schemaUri, jsonPointer] = ref.match(/^([^#]*)(#.+)$/) || [];
  assert(jsonPointer, `Invalid JSON pointer: ${ref}`);

  // If there is a URI, it's we need a different schema
  if(schemaUri){
    if(/^https?:\/\//.test(ref)){
      schema = await fetch(ref).then(res => res.json());
    }
    else{
      const pathToSchema = path.resolve(path.dirname(schemaPath), ref);
      schema = JSON.parse(await fs.readFile(pathToSchema, 'utf8'));
    }
  }

  // Assuming a function that can resolve a JSON Pointer
  const dereferenced = resolveJsonPointer(jsonPointer, schema);
  assert(dereferenced, `Could not resolve JSON Pointer: ${jsonPointer}`);
  return dereferenced;
}
```

IMO it would be better to use an existing spec-compliant resolver, since there are lots of little nuances in the spec.

**Comment by Phault** [comment]
Bumping to keep alive, since there's been no official answer yet. Sorry if this is frowned upon..

**Comment by danielsharvey** [comment]
Both #9206 (this) and #9208 remain good ideas. Is there any interest in re-opening or other consideration of this idea?
