### ISSUE TITLE
ng serve webpack dependency

### ISSUE THREAD

**Issue by JosepAlacid** [nrwl/nx#9216]
## Current Behavior
Cannot find module 'webpack'
Require stack:
- C:\projects\ingeniusds\idsmain\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
- C:\projects\ingeniusds\idsmain\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\projects\ingeniusds\idsmain\node_modules\@angular-devkit\build-angular\src\builders\dev-server\index.js
- C:\projects\ingeniusds\idsmain\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js 
- C:\projects\ingeniusds\idsmain\node_modules\@angular-devkit\architect\node\index.js
- C:\projects\ingeniusds\idsmain\node_modules\@nrwl\tao\src\commands\ngcli-adapter.js
- C:\projects\ingeniusds\idsmain\node_modules\@nrwl\tao\src\commands\run.js
- C:\projects\ingeniusds\idsmain\node_modules\@nrwl\tao\index.js
- C:\projects\ingeniusds\idsmain\node_modules\@nrwl\cli\lib\run-cli.js
Error: Cannot find module 'webpack'
Require stack:
- C:\projects\ingeniusds\idsmain\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
- C:\projects\ingeniusds\idsmain\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\projects\ingeniusds\idsmain\node_modules\@angular-devkit\build-angular\src\builders\dev-server\index.js
- C:\projects\ingeniusds\idsmain\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\projects\ingeniusds\idsmain\node_modules\@angular-devkit\architect\node\index.js
- C:\projects\ingeniusds\idsmain\node_modules\@nrwl\tao\src\commands\ngcli-adapter.js
- C:\projects\ingeniusds\idsmain\node_modules\@nrwl\tao\src\commands\run.js
- C:\projects\ingeniusds\idsmain\node_modules\@nrwl\tao\index.js
- C:\projects\ingeniusds\idsmain\node_modules\@nrwl\cli\lib\run-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (C:\projects\ingeniusds\idsmain\node_modules\@nrwl\tao\src\compat\compat.js:14:40)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (C:\projects\ingeniusds\idsmain\node_modules\@angular-devkit\build-webpack\src\webpack\index.js:18:35)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)

### Environment
Node : 14.18.1
   OS   : win32 x64
   npm  : 8.1.4

   nx : 13.8.4
   @nrwl/angular : 13.8.4
   @nrwl/cli : 13.8.4
   @nrwl/cypress : 13.8.4
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.4
   @nrwl/eslint-plugin-nx : 13.8.4
   @nrwl/express : undefined
   @nrwl/jest : 13.8.4
   @nrwl/js : undefined
   @nrwl/linter : 13.8.4
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : 8.12.11
   @nrwl/storybook : 13.8.4
   @nrwl/tao : 13.8.4
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.4
   typescript : 4.5.5
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
         @angular-devkit/build-webpack: 0.1302.5
         @angular/animations: 13.2.5
         @angular/cdk: 13.2.5
         @angular/common: 13.2.5
         @angular/compiler: 13.2.5
         @angular/core: 13.2.5
         @angular/forms: 13.2.5
         @angular/google-maps: 13.0.2
         @angular/localize: 13.2.5
         @angular/material: 13.2.5
         @angular/material-moment-adapter: 13.0.2
         @angular/platform-browser: 13.2.5
         @angular/platform-browser-dynamic: 13.2.5
         @angular/pwa: 13.0.3
         @angular/router: 13.2.5
         @angular/service-worker: 13.2.5
         @ngx-pwa/local-storage: 13.0.2
         @ngxs/schematics: 0.0.1-alpha.5
         @angular-devkit/build-angular: 13.2.5
         @angular/cli: 13.2.5
         @angular/compiler-cli: 13.2.5
         @angular/language-service: 13.2.5

**Comment by AgentEnder** [comment]
Hey @JosepAlacid, can you provide your serve target's configuration?

**Comment by JosepAlacid** [comment]
I'm now unable to reproduce it too. I'll be aware if it happens again to catch up all the info. I'm closing it right now.
