### ISSUE TITLE
nx upgrade: failed to run unit test case (transformIgnorePatterns is not working for d3 packages )

### ISSUE THREAD

**Issue by dean-g** [nrwl/nx#9226]
I am trying to upgrade the packages and getting the following error while running my jest unit test case, 

`TypeError: import_index.Selection is not a constructor`

It looks like, the following global jest.preset.js configuration is not working with the latest version on nx, 

```
const d3Modules = ['d3', 'd3-array', 'd3-selection'].join('|');
transformIgnorePatterns: [`node_modules/(?!${d3Modules}|.*.mjs$)`],
```

Can you please advise if anything needs to be changed on that to get my d3 packages ignored?

The same worked well with the following version 13.7.2

**Comment by dean-g** [comment]
the jest-preset-angular package upgrade is an issue!. if I downgrade this, everything works well

**Comment by barbados-clemens** [comment]
@zoechi can you provide a reproducible repo I can take a look at?

**Comment by zoechi** [comment]
@barbados-clemens sorry, it's a closed source project. I'll update though if I find any clues.

**Comment by bmordue** [comment]
I'm struggling with a similar issue, except I'm starting from scratch, no upgrade.
I think this example repo shows the problem: https://github.com/bmordue/nx-bmordue
GH action log with OP's error message: https://github.com/bmordue/nx-bmordue/runs/6469344545?check_suite_focus=true#step:4:13
Thanks for looking!

**Comment by joewIST** [comment]
This is also an issue for our project, and I can confirm that downgrading jest-present-angular to 11.0.1 has no impact. we are seeing many instances of the following error: "TypeError: import_index.Selection is not a constructor"
