### ISSUE TITLE
create-nx-workspace command support for unitTestRunner selection

### ISSUE THREAD

**Issue by MasterSaberD1996** [nrwl/nx#9230]
## Description

I would love to see a flag/prompt introduced into the create-nx-workspace command that allows a user to select the default unitTestRunner whether it be Karma or Jest. It should also generate all of the necessary files for the specified test runner.

## Motivation

A lot of companies and solo developers prefer to use karma over jest. Allowing them to decide what unit test runner is set to be the default at the creation of the workspace would save developers time and frustration in getting the configuration just right.

## Suggested Implementation

Two basic implementations come to mind:

1.  An optional flag is provided (i.e. --unitTestRunner) that allows a user to type in the name of the unit test runner that they want
2. A prompt is provided that asks the user to select a unit test runner (as jest seems to be the preferred by the main development body for the group creating nx it could default to jest)

**Comment by AgentEnder** [comment]
Hey @MasterSaberD1996! for options not exposed during create-nx-workspace, you can choose the `apps` preset and then install `@nrwl/angular` and generate the first app yourself, with access to all of the subcommands.

I'm going to close this, as the intent of `create-nx-workspace` isn't to expose all arguments. Let me know if you have any more questions.
