### ISSUE TITLE
Command `nx run project:command` does not work if `command` contains a colon (`:`)

### ISSUE THREAD

**Issue by lughino** [nrwl/nx#9232]
## Current Behavior
When I try to run the command `yarn nx run project:command` where the command has colon char in it, `nx` returns an error as it is not be able to recognise it.
E.g.
I have a command in each package that is `sub:cmd`.
I try to run that command for one package with `yarn nx run package-a:"sub:cmd"` and it returns the error ` NX   Cannot find target 'sub' for project 'package-a'`.
I tried with double quotes, with single quotes, and without, but I always receive the same error.

If I use the command format `yarn nx sub:cmd package-a` it works.

## Expected Behavior
Being able to execute a command in a package with colon in the command

## Steps to Reproduce
You can use [this link](https://codesandbox.io/s/nx-subcommands-bug-h1l71q) to reproduce the error. Head to the terminal and try to run `yarn nx run package-a:"sub:cmd"`

### Environment

```bash
   Node : 14.18.1
   OS   : linux x64
   yarn : 1.22.17

   nx : 13.8.5
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.5
   @nrwl/cypress : undefined
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.5
   @nrwl/eslint-plugin-nx : undefined
   @nrwl/express : undefined
   @nrwl/jest : 13.8.5
   @nrwl/js : 13.8.5
   @nrwl/linter : 13.8.5
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : undefined
   @nrwl/tao : 13.8.5
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.5
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by AgentEnder** [comment]
Nx generally uses a colon to delimit `nx run {project}:{target}:{configuration}`, so it interprets the command as a target and configuration.

A simple workaround for this would be to change the target name, but that won't work in only `package.json`. You can create a minimal `project.json` for that app with contents like:
```json
{
  "root": "path/to/my-app"
  "targets": {
    "sub-cmd": {
      "executor": "@nrwl/workspace:run-script"
      "options": {
        "script": "sub:cmd"
        }
    }
  }
}
```

**Comment by reenan** [comment]
I'm also facing this issue while migrating a big mono-repo with lots of legacy commands that are rooted to other stuff and have `:` in their name.

Any possibility to maybe support it as `nx run project:"command:with:colons"` (quotes wrapping)?

**Comment by lughino** [comment]
+1 on supporting with quotes...
I guess it's already doing that somewhere as if you use the command `yarn nx sub:cmd package-a` it works and print in the console `executing nx run package-a:"sub:cmd"`

**Comment by gioragutt** [comment]
* https://github.com/nrwl/nx/blob/master/packages/nx/src/utils/split-target.ts

That's the method that `nx run` uses to parse the string (which [`parse-target-string.ts`](https://github.com/nrwl/nx/blob/6f038e7a4a4fe27dd218138fd21b46541761aec9/packages/devkit/src/executors/parse-target-string.ts) should be using but doesn't).

It should be a fairly easy PR. It would however impose more complexity on `splitTarget`, as it introduces some edge cases (`package-a:"sum:cmd` or `package-a:sum:cmd"`) which needs to be handled.

Also docs 😅

**Comment by elado** [comment]
I can confirm that wrapping with quotes works. In the terminal I had to escape the quotes with `\"`.
