### ISSUE TITLE
@nx/web:app "strict" option

### ISSUE THREAD

**Issue by ziacik** [nrwl/nx#9238]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
_@nrwl/js:lib_, _@nrwl/react:app_ and many others have a `"strict"` option, `@nrwl/web:app` should have one too.

## Motivation
To have consistency between generators, and to be able to generate strict apps, by default.

**Comment by ziacik** [comment]
Don't close, please.

**Comment by ziacik** [comment]
Not stale. Still no strict option in @nx/web:application generator, still generated with non-strict tsconfigs. In 16.5.5.

**Comment by FrozenPandaz** [comment]
Would someone in the community like to open a PR?

**Comment by ziacik** [comment]
I might try to make this one.
