### ISSUE TITLE
nx build produce only types, not executable .js code

### ISSUE THREAD

**Issue by whalemare** [nrwl/nx#9246]
I want to use `nx` as a place, that contain publishable react-native libraries, which I can easily develop and distribute.

For achieve this, I do all steps describes in [tutorial page](https://nx.dev/react-native/overview)

## Steps to Reproduce

1. Create workspace without nx cloud
```
npx create-nx-workspace your-workspace-name \
--preset=react-native \
--appName=your-app-name
```

2. `cd your-workspace-name`

3. Generate publishable react-native library
```
npx nx g @nrwl/react-native:lib your-lib-name --publishable --importPath @whalemare/your-lib-name
```

4. Add some stub files with logic (interface Logger, and implementation ConsoleLogger)

5. Prepare lib for publishing, by calling 
`npx nx build your-lib-name`

6. Try to execute bundled code with `node index.umd.js`

## Current Behavior
NX build with success only entry point of library without any implementation details

I was try to dig deeper, and found that build is done with `rollup`. But I don't know why it emit only typings, without implementation details.

```
Bundling your-lib-name...
  index.esm.js 57 Bytes
  index.umd.js 195 Bytes
⚡ Done in 1.18s
```

<img width="400" alt="Снимок экрана 2022-03-09 в 18 09 45" src="https://user-images.githubusercontent.com/9128731/157430133-99c0f8b4-0680-407f-ae3b-bbafbb4be8fc.png">

When I execute bundled code with `node index.umd.js` I receive 'MODULE_NOT_FOUND' error

```
node index.umd.js 
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './logger'
Require stack:
- /Users/whalemare/dev/temp/your-workspace-name/dist/libs/your-lib-name/index.umd.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/whalemare/dev/temp/your-workspace-name/dist/libs/your-lib-name/index.umd.js:6:186
    at /Users/whalemare/dev/temp/your-workspace-name/dist/libs/your-lib-name/index.umd.js:3:2
    at Object.<anonymous> (/Users/whalemare/dev/temp/your-workspace-name/dist/libs/your-lib-name/index.umd.js:4:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/whalemare/dev/temp/your-workspace-name/dist/libs/your-lib-name/index.umd.js'
  ]
}
```

## Expected Behavior
NX build entry points and implementations files, how it do `tsc` compiler.
`dist/libs/your-lib-name` folder contains as index.js file and `ConsoleLogger.js`

<img width="400" alt="Снимок экрана 2022-03-09 в 18 32 13" src="https://user-images.githubusercontent.com/9128731/157433733-25ca00bd-fa34-4583-a2a1-7bf8f9fc003c.png">

Repository with reproducible example: https://github.com/whalemare/nx-reproduce-not-found-module.git

### Environment

```
>  NX   Report complete - copy this into the issue template

   Node : 16.13.1
   OS   : darwin arm64
   npm  : 8.1.2
   
   nx : 13.8.5
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.5
   @nrwl/cypress : 13.8.5
   @nrwl/detox : 13.8.5
   @nrwl/devkit : 13.8.5
   @nrwl/eslint-plugin-nx : 13.8.5
   @nrwl/express : undefined
   @nrwl/jest : 13.8.5
   @nrwl/js : 13.8.5
   @nrwl/linter : 13.8.5
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : 13.8.5
   @nrwl/react-native : 13.8.5
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.5
   @nrwl/tao : 13.8.5
   @nrwl/web : 13.8.5
   @nrwl/workspace : 13.8.5
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by xiongemi** [comment]
to build the react native library, there are a few steps:

1. inside your library's .babelrc, change it to:
```
{
  "presets": [
    [
      "@nrwl/react/babel",
      {
        "runtime": "automatic",
        "useBuiltIns": "usage"
      }
    ]
  ]
}
```

2 in your lib's tsconfig.lib.json, add below to compilerOptions:
```
"jsx": "react-native"
```

3. in your lib's project.json, for targets -> build -> external, make sure react-native is in the array:
```
"external": ["react/jsx-runtime", "react-native"],
```

**Comment by subhranshudas** [comment]
@xiongemi i am also facing the same issue in my dummy `react-native-library`!!
i have copied your solution & it works!! Thank you for the magic!

One query though - i am using NX-14.1.7 and don't intend to migrate to latest NX version for some time, will it be good with the fix in place? or i might face issues when i migrate?

Thanks!!

**Comment by nicost71** [comment]
hi @xiongemi 
Many thanks for providing a fix.
Unfortunately on my project, it still only generates definition files...

I created a fresh workspace + project like this:

1) npx create-nx-workspace@latest test-nx
2) npx nx g lib react-native-components --publishable
    (as a generator I use @nrwl/react-native:library)
3) Generate a dummy hook "dummy.tsx" on the libs/react-native-components/src directory
4) Run "nx build react-native-components"
5) In the dist/libs/react-native-components, I only have a "dummy.d.ts" file with the type definition, but no actual implementation. The index.js/index.d.ts is also empty (as also the index.ts in the lib itself is empty)


Do you have any idea what the problem might be? Is there a need for something in particular to put in the index.ts?

Many thanks for your help - really appreciated!!

**Comment by xiongemi** [comment]
in the dist index.js file, you should see your dummy component code. you should be able to import from your built library.

**Comment by nicost71** [comment]
I managed to get the (compiled) source-code in the dist/index.js by exporting the js-files in the original index.js using "export * from ./mycomponent" etc.

it's right though, that the components itself are only visible as type-definition (e.g. mycomponent.d.ts) and it's (compiled) code is all in the index.js, right?
