### ISSUE TITLE
import path by project name instead of projectDirectory (due to my project inside multi folder level)

### ISSUE THREAD

**Issue by anhdiepmmk** [nrwl/nx#9259]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@nrwl/node@13.8.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@nrwl/node/src/generators/library/library.js b/node_modules/@nrwl/node/src/generators/library/library.js
index b7d4c07..2b7f1b8 100644
--- a/node_modules/@nrwl/node/src/generators/library/library.js
+++ b/node_modules/@nrwl/node/src/generators/library/library.js
@@ -42,7 +42,7 @@ function normalizeOptions(tree, options) {
     const parsedTags = options.tags
         ? options.tags.split(',').map((s) => s.trim())
         : [];
-    const importPath = options.importPath || `@${defaultPrefix}/${projectDirectory}`;
+    const importPath = options.importPath || `@${defaultPrefix}/${projectName}`;
     return Object.assign(Object.assign({}, options), { prefix: defaultPrefix, // we could also allow customizing this
         fileName, name: projectName, projectRoot,
         projectDirectory,
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by AgentEnder** [comment]
Hey @anhdiepmmk, this is an intentional decision in the generator. We use the expanded path for the imports to minimize collisions, as people may run commands like `nx g lib models --directory a` and `nx g lib models --directory b`.

I'm going to close this one, let me know if you feel it should be looked at closer.
