### ISSUE TITLE
How to run yarn test on windows and see log from bash shell

### ISSUE THREAD

**Issue by vairamsvsjdo** [nrwl/nx#927]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

* [x ] I am running the latest version
* [ x] I checked the documentation and found no answer
* [ x] I checked to make sure that this issue has not already been filed
* [ x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior
I would like to visualize the test result log files and use a test explorer to see the output.

## Current Behavior
I am seeing some errors generated when running yarn test and yarn e2e on windows machine. However, I am unable to see the console (test) output post build. Where are the test results stored and how to see it in a text file.

## Failure Information (for bugs)

None

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Follow steps described in contribution guide to "yarn test" or "yarn e2e"

### Context
Master branch in this project with nodejs 10.x
Angular CLI: 7.0.1
Node: 10.13.0
OS: win32 x64
Angular: 7.0.0
... common, compiler, compiler-cli, core, platform-browser
... platform-browser-dynamic, router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.1
@angular-devkit/build-angular     0.10.1
@angular-devkit/build-optimizer   0.10.1
@angular-devkit/build-webpack     0.10.1
@angular-devkit/core              7.0.1
@angular-devkit/schematics        7.0.1
@angular/cli                      7.0.1
@ngtools/json-schema              1.1.0
@ngtools/webpack                  7.0.1
@schematics/angular               7.0.1
@schematics/update                0.10.1
ng-packagr                        4.3.1
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1

**A minimal reproduce scenario using allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**
see stesps to reproduce

### Failure Logs
None

## Other

Any other relevant information that will help us help you.

**Comment by vairamsvsjdo** [comment]
when running the ng test script second part from "bash" shell directly I get the following warning messages:

 MINGW64 ~/source/repos/nx (master)
$ ./scripts/test_nx.sh
(node:19648) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

webpack: Compiled with warnings.
webpack: Compiling...

webpack: Compiled with warnings.
24 11 2018 15:50:42.733:INFO [karma]: Karma v2.0.5 server started at http://0.0.0.0:9876/
24 11 2018 15:50:42.768:INFO [launcher]: Launching browser Chrome with unlimited concurrency
24 11 2018 15:50:42.791:INFO [launcher]: Starting browser Chrome
24 11 2018 15:50:48.701:INFO [Chrome 70.0.3538 (Windows 10 0.0.0)]: Connected on socket jFk_LQY0ySEC38VmAAAA with id 40191947
WARN: 'Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?'
.
WARN: 'Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?'
WARN: 'Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?'
.
WARN: 'Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?'
WARN: 'Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?'

**Comment by vsavkin** [comment]
Closing this. If the problem persists, could you reopen it against Nx 7.8?
