### ISSUE TITLE
Some dependencies of 'libb-api' have not been built. This probably due to the build target being misconfigured 

### ISSUE THREAD

**Issue by wizardnet972** [nrwl/nx#9278]
## Current Behavior

When I run:

```
yarn nx run-many --target build --all
```
or:
```
yarn nx run-many --target build --all --skip-nx-cache
```
I got error:
```
  Some of the project libb-api's dependencies have not been built yet. Please build these libraries before:
       - libc-api

       Try: nx run libb-api:build --with-deps
       Some dependencies of 'libb-api' have not been built. This probably due to the build target being misconfigured.
```
in nx 13.8.7.

## Expected Behavior

nx run-many should build all projects

## Steps to Reproduce
My project is simple:
create app preset: nx-app (node app)
then create three libs: `liba-api`, `libb-api`, `libc-api` (node lib buildable)

**Or clone:**
```
git clone https://github.com/wizardnet972/nx-cache.git
yarn
yarn nx run-many --target build --all
```

### Failure Logs

```
$ /Users/wizardnet972/sandbox/nx-cache/node_modules/.bin/nx run-many --target build --all

    ✔  nx run libc-api:build (691ms)

    ✖  nx run libb-api:build
       Some of the project libb-api's dependencies have not been built yet. Please build these libraries before:
       - libc-api

       Try: nx run libb-api:build --with-deps
       Some dependencies of 'libb-api' have not been built. This probably due to the build target being misconfigured.

    ✔  nx run workspace:build (4s)

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for 5 projects (4s)

    ✖    1/3 failed
    ✔    2/3 succeeded [0 read from cache]
```
### Environment

```

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.0
   OS   : darwin arm64
   yarn : 1.22.11

   nx : 13.8.7
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.7
   @nrwl/cypress : undefined
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.7
   @nrwl/eslint-plugin-nx : 13.8.7
   @nrwl/express : undefined
   @nrwl/jest : 13.8.7
   @nrwl/js : 13.8.7
   @nrwl/linter : 13.8.7
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : 13.8.7
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : undefined
   @nrwl/tao : 13.8.7
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.7
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

(node:74635) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/wizardnet972/sandbox/nx-cache/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
```

**Comment by tonimora74** [comment]
I have the same problem.


 >  NX   Report complete - copy this into the issue template

   Node : 16.15.0
   OS   : macOS Monterey Version 12.3.1
   npm : 18.5.5

   "@nrwl/angular": "14.1.7",
    "@nrwl/cli": "14.1.7",
    "@nrwl/eslint-plugin-nx": "14.1.7",
    "@nrwl/js": "14.1.7",
    "@nrwl/linter": "14.1.7",
    "@nrwl/node": "14.1.7",
    "@nrwl/workspace": "14.1.7",
   "typescript": "4.6.3"
   "rxjs": "6.6.3"
    "@angular/animations": "13.3.9",
    "@angular/cdk": "13.3.7",
    "@angular/common": "13.3.9",
    "@angular/compiler": "13.3.9",
    "@angular/core": "13.3.9",
    "@angular/forms": "13.3.9",
    "@angular/platform-browser": "13.3.9",
    "@angular/platform-browser-dynamic": "13.3.9",
    "@angular/router": "13.3.9",
    "@angular-devkit/build-angular": "13.3.6",
    "@angular-devkit/core": "13.3.6",
    "@angular-devkit/schematics": "13.3.6",
    "@angular-devkit/schematics-cli": "^12.2.17",
    "@angular-eslint/builder": "12.6.1",
    "@angular-eslint/eslint-plugin": "13.0.1",
    "@angular-eslint/eslint-plugin-template": "13.0.1",
    "@angular-eslint/template-parser": "13.0.1",
    "@angular-extensions/svg-icons-builder": "3.0.0",
    "@angular/cli": "13.3.6",
    "@angular/compiler-cli": "13.3.9"

**Comment by voznik** [comment]
Facing the same issue in the latest v13
Also, this includes self. Also, ignore pattern doesn't work

```
>  NX   Report complete - copy this into the issue template

   Node : 14.17.4
   OS   : linux x64
   npm  : 6.14.16
   
   nx : 13.10.6
   @nrwl/angular : 13.10.5
   @nrwl/cypress : 13.10.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.5
   @nrwl/eslint-plugin-nx : 13.10.5
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.5
   @nrwl/js : 13.10.5
   @nrwl/linter : 13.10.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 13.10.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.5
   @nrwl/web : 13.10.5
   @nrwl/workspace : 13.10.5
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
```

```
{
    "projectType": "library",
    "root": "libs/shared/ui",
    "sourceRoot": "libs/shared/ui/src",
    "tags": [
        "scope:shared"
    ],
    "implicitDependencies": [
        "shared-utils",
        "!shared-i18n",
    ],
   ...
```

```
nx run shared-ui:build --skip-nx-cache

> nx run shared-ui:build

Some of the project shared-ui's dependencies have not been built yet. Please build these libraries before:
- shared-ui
- shared-i18n

Try: nx run shared-ui:build --with-deps
```

Can someone help to understand why is it happening?

**Comment by kenatwex** [comment]
This one is biting hard... we have a formidable project and now its quitting.

```
    ✖  nx run shared-root-logging:build:production
       It looks like all of shared-root-logging's dependencies have not been built yet:
       - shared-root-core-configuration
       
       You might be missing a "targetDefaults" configuration in your root nx.json (https://nx.dev/configuration/projectjson#target-defaults),
       or "dependsOn" configured in shared-root-logging's project.json (https://nx.dev/configuration/projectjson#dependson)
      
```

Is a workaround available?

Thanks for an elite product

**Comment by dereekb** [comment]
Did you just update to Nx 14? I ran into the same issue with my repo that I had modified the build setup a little so the migration didn’t cut it.

If you have go see if my notes can’t help you out or seem familiar. My issue ended up being I hadn’t defined the build order properly given the changes.

https://github.com/nrwl/nx/issues/11556

**Comment by kenatwex** [comment]
> Did you just update to Nx 14? I ran into the same issue with my repo that I had modified the build setup a little so the migration didn’t cut it.
> 
> If you have go see if my notes can’t help you out or seem familiar. My issue ended up being I hadn’t defined the build order properly given the changes.
> 
> #11556

yes I have been keeping current by the day

**Comment by kenatwex** [comment]
Okay this is getting weirder.... I do not use `red` except for scss

while attempting to move things back

nx is inserting red into the error message

>  NX   unable to find "@my-folder/red/root/core/actions" in tsconfig.base.json compilerOptions.paths

**Comment by kenatwex** [comment]
so this is looking like an internal cache issue with tsconfig.paths

I have all cache shut off with all my projects inside project.json

no `.angular/cache exists`

so the typescript angular compiler is giving out here

**Comment by FrozenPandaz** [comment]
This issue should now be resolved. Please open a new issue if you can reproduce the issue on the latest versions of Nx.
