### ISSUE TITLE
@nrwl/nx-plugin:plugin generator includes .ts files in dist

### ISSUE THREAD

**Issue by michaelcamper** [nrwl/nx#9283]
## Current Behavior
`@nrwl/nx-plugin:plugin` generator defines build executor (`@nrwl/js:tsc`) which still includes .ts files in build dist.

## Expected Behavior
".ts" should not be included in build output

## Steps to Reproduce
- initialise new workspace: `yarn create nx-workspace my-org --preset=core --no-nx-cloud`
- install "@nrwl/nx-plugin": `yarn add -W -D @nrwl/nx-plugin`
- generate a new plugin: `nx g @nrwl/nx-plugin:plugin my-plugin`
- build plugin: `nx build my-plugin`
- check dist files

This issue seems to be related to the replacement of `@nrwl/node:package` to `@nrwl/js:tsc` executor.

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment
 Node : 16.13.0
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 13.8.7
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.7
   @nrwl/cypress : 13.8.7
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.7
   @nrwl/eslint-plugin-nx : 13.8.7
   @nrwl/express : undefined
   @nrwl/jest : 13.8.7
   @nrwl/js : 13.8.7
   @nrwl/linter : 13.8.7
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : 13.8.7
   @nrwl/nx-cloud : undefined
   @nrwl/react : 13.8.7
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.7
   @nrwl/tao : 13.8.7
   @nrwl/web : 13.8.7
   @nrwl/workspace : 13.8.7
   typescript : 4.4.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         @nrwl/nx-plugin: 13.8.7

**Comment by AgentEnder** [comment]
Hey, I can't seem to reproduce this. To test I followed:
1. `npx create-nx-plugin test --pluginName my-plugin`
2. `cd test`
3. `nx build my-plugin`

This resulted in the below dist contents for dist/packages/my-plugin:
<img width="356" alt="image" src="https://user-images.githubusercontent.com/6933928/157906759-831c7044-0b6a-4329-ad3c-6a31a42087bc.png">


There are some .d.ts files, but no raw .ts files. Is this different from your observations?

**Comment by michaelcamper** [comment]
The issues seems to be caused by `targets.build.options.assets[1]` in the respective `project.json`:
```
...,
{
  "input": "./packages/my-plugin/src",
  "glob": "**/!(*.ts)",
  "output": "./src"
},
...
```

 Adding `"ignore": "**/*.ts"` works as an ugly workaround

**Comment by AgentEnder** [comment]
Double checking in my repo, my workspace is on 13.8.7. Are you on windows by chance?

**Comment by AgentEnder** [comment]
Here is the project.json for the `my-plugin` project:
```json
{
  "root": "packages/my-plugin",
  "sourceRoot": "packages/my-plugin/src",
  "targets": {
    "build": {
      "executor": "@nrwl/js:tsc",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/packages/my-plugin",
        "main": "packages/my-plugin/src/index.ts",
        "tsConfig": "packages/my-plugin/tsconfig.lib.json",
        "assets": [
          "packages/my-plugin/*.md",
          {
            "input": "./packages/my-plugin/src",
            "glob": "**/!(*.ts)",
            "output": "./src"
          },
          {
            "input": "./packages/my-plugin/src",
            "glob": "**/*.d.ts",
            "output": "./src"
          },
          {
            "input": "./packages/my-plugin",
            "glob": "generators.json",
            "output": "."
          },
          {
            "input": "./packages/my-plugin",
            "glob": "executors.json",
            "output": "."
          }
        ]
      }
    },
    "lint": {
      "executor": "@nrwl/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["packages/my-plugin/**/*.ts"]
      }
    },
    "test": {
      "executor": "@nrwl/jest:jest",
      "outputs": ["coverage/packages/my-plugin"],
      "options": {
        "jestConfig": "packages/my-plugin/jest.config.js",
        "passWithNoTests": true
      }
    }
  },
  "tags": []
}
```

**Comment by michaelcamper** [comment]
This is odd. No, I am on MacOS

This is my report after running the steps you provided:

```
 Node : 16.13.0
  OS   : darwin arm64
  yarn : 1.22.17
  
  nx : 13.2.3
  @nrwl/angular : undefined
  @nrwl/cli : 13.2.3
  @nrwl/cypress : undefined
  @nrwl/devkit : 13.2.3
  @nrwl/eslint-plugin-nx : 13.2.3
  @nrwl/express : undefined
  @nrwl/jest : 13.2.3
  @nrwl/linter : 13.2.3
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.2.3
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.3
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.3
  @nrwl/storybook : undefined
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
         @nrwl/nx-plugin: 13.2.3

```

**Comment by boeto** [comment]
@AgentEnder please using the `yarn create nx-workspace my-org --preset=core --no-nx-cloud` should be able to reproduce the issues instead of 'npx create-nx-plugin@latest'.

**Comment by boeto** [comment]
```json
// project.json

{
  "targets": {
    "build": {
      "executor": "@nrwl/js:tsc",
      "options": {
        "assets": [
          {
            "input": "./libs/p1/src",
            "glob": "**/!(*.ts)",
            "output": "./src"
          },
        ]
      }
    }
  }
}
```
Maybe the issues is caused by this parameter, or '@nrwl/js:tsc' doesn't need this parameter

**Comment by boeto** [comment]
> The issues seems to be caused by `targets.build.options.assets[1]` in the respective `project.json`:
> 
> ```
> ...,
> {
>   "input": "./packages/my-plugin/src",
>   "glob": "**/!(*.ts)",
>   "output": "./src"
> },
> ...
> ```
> 
> Adding `"ignore": "**/*.ts"` works as an ugly workaround


This parameter `!(*.ts)` should not be parsed, so it should be

```json
{
  "input": "./libs/p1/src",
  "glob": "*",
  "ignore": ["**/*.ts"],
  "output": "./src"
},
```

**Comment by AgentEnder** [comment]
I just retried this with 13.8.8, with the below environment. I still can't reproduce this, as the only ts files in the build were `.d.ts` files, as expected. Can you provide a reproduction in the form of a repo I can clone and test?
```
 >  NX   Report complete - copy this into the issue template

   Node : 14.17.0
   OS   : darwin x64
   npm  : 6.14.13
   
   nx : undefined
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.8
   @nrwl/cypress : undefined
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.8
   @nrwl/eslint-plugin-nx : 13.8.8
   @nrwl/express : undefined
   @nrwl/jest : 13.8.8
   @nrwl/js : 13.8.8
   @nrwl/linter : 13.8.8
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : undefined
   @nrwl/tao : 13.8.8
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.8
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         @nrwl/nx-plugin: 13.8.8
```

**Comment by boeto** [comment]
@AgentEnder I created the [reproduction](https://github.com/boeto/test-nx-plugin-build-yarn.git), please check it~

```sh
#!/bin/sh

# To test followed:
npx create-nx-plugin test-nx-plugin-build-yarn --pluginName my-plugin --package-manager=yarn
cd test-nx-plugin-build-yarn
yarn nx build my-plugin
ls dist/packages/my-plugin/src/generators/my-plugin
# files             generator.js      generator.spec.ts schema.d.ts
# generator.d.ts    generator.js.map  generator.ts      schema.json

#############################################################################

#Set yarn workspace followed:
yarn set version 3.2.0

cat <<EOF | tee .yarnrc.yml 
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.2.0.cjs
EOF

#Add .gitignore
cat <<EOF | tee -a .gitignore

# yarn v3
.pnp.*
.yarn/*
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/sdks
!.yarn/versions 
EOF
```

**Comment by gioragutt** [comment]
@michaelcamper @boeto after some research the problem seems to be a regression of `fast-glob`, @AgentEnder found that 👍🏻

A workaround in the meanwhile, if you're using `yarn`, is to add the following to your package.json:

```json
{
  "resolutions": {
    "fast-glob": "3.2.7"
  }
}
```

**Comment by AgentEnder** [comment]
Thanks again @gioragutt! We found it together. We'll work on pinning the version for `fast-glob` in nx, until that goes through the npm overrides or yarn resolutions mechanisms should unblock yall. See here for the npm solution https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides
