### ISSUE TITLE
"@nrwl/storybook:storybook" uses proxy package for "@storybook/core-server"

### ISSUE THREAD

**Issue by michaelcamper** [nrwl/nx#9286]
## Current Behavior
The `storybook` executor [imports from `@storybook/core`](https://github.com/nrwl/nx/blob/a32d46c5a36246b2349d72f7b50f7f0e532744bb/packages/storybook/src/executors/storybook/storybook.impl.ts#L2) to spin up a dev server. As this package is used as a proxy for backwards compatibility, I don't think it is good practice. `@storybook/core` is only installed when using `@storybook/addon-essentials` (`@storybook/addon-docs` to me more specific) and therefor breaks if storybook is used without the docs addon.

## Expected Behavior
`storybook` executor should use `@storybook/core-server` instead of relying on a proxy package.

## Steps to Reproduce
- Uninstall `@storybook/addon-essentials` from a workspace with a set up storybook project
- run `nx storybook [project]`

### Failure Logs
`Cannot find module '@storybook/core/server`

### Environment
   Node : 16.13.0
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 13.8.7
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.7
   @nrwl/cypress : 13.8.7
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.7
   @nrwl/eslint-plugin-nx : 13.8.7
   @nrwl/express : undefined
   @nrwl/jest : 13.8.7
   @nrwl/js : 13.8.7
   @nrwl/linter : 13.8.7
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : 13.8.7
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.7
   @nrwl/tao : 13.8.7
   @nrwl/web : 13.8.7
   @nrwl/workspace : 13.8.7
   typescript : 4.5.5
   rxjs : 6.6.7

**Comment by mandarini** [comment]
Hi there @michaelcamper ! Ha, you got me, is all I'll say :P 

That's a known issue, and I'm supposed to be working on it. Will try to have this fixed some time soon. 

Potentially related issues:
https://github.com/nrwl/nx/issues/8403
https://github.com/nrwl/nx/issues/7544

**Comment by michaelcamper** [comment]
Wow, you guys are quick to reply! 👏🏼

Cool happy to hear that!

Just out of curiosity, wouldn't be sufficient to just adjust the import statement?

**Comment by mandarini** [comment]
Hm, maybe yes maybe no. There's some logic behind this, and right now I'm not 100% sure how we should treat this. I will post updates here, don't worry!

**Comment by shilman** [comment]
@mandarini I think it's save to use `@storybook/core-server` directly if that helps. the rationale on the storybook side: when we did the refactor that split `@storybook/core` into `core-client` and `core-server` in SB6.2, we we kept `@storybook/core` around to try to avoid breaking changes.

**Comment by mandarini** [comment]
Hi there @michaelcamper ! I am just trying out your issue now! So, your issue exists, indeed if I remove `@storybook/addon-essentials` I get the `Cannot find module '@storybook/core/server'` error.

However, if I change the import to `@storybook/core-server`, I still get the not found error, for `core-server` this time. Do you want to try it out on your own, too, and let me know if it works for you in a different way? I can help you out make the change to the Nx codebase and run it locally to test if you want.

**Comment by mandarini** [comment]
Also, I think it sort of makes sense to assume that `@storybook/core` is available. But I see where you're coming from. In any case, the server implementations will soon change, hopefully. But yes, let's see if you can get it working with the `core-server`.

Or did you mean to add `core-server` as a dependency in `package.json`?

**Comment by mandarini** [comment]
Actually, [here's the PR](https://github.com/nrwl/nx/pull/9368). You can test it locally, too. It does not seem to be working for me.

**Comment by michaelcamper** [comment]
Hi @mandarini! I've just tested it in my project by replacing the import directly in `node_modules/@nrwl/storybook/src/executors/storybook/storybook.impl.js`, which seems to work!

The changes in your PR look good to me! Some tests seem to fail, but I cannot see a relation to the change in storybook. Do you?

**Comment by mandarini** [comment]
@michaelcamper I first tried changing the import directly in node_modules as well, and it does not work for me. Can you send me a sample reproduction repository, so that I can test it on my side? I will just change the import after I `yarn` install the deps.

**Comment by mandarini** [comment]
So, I am going to change this to an enhancement, since a simple change in the import does not fix it, and also I really think that expecting `storybook/core` to be present is reasonable. I'll tell you what, though. It's in the works to change the way we use the server, so this is going to change in any case! Does this sound good?
