### ISSUE TITLE
Error during ng build in nx mono repo after using the module federation

### ISSUE THREAD

**Issue by karthikLC** [nrwl/nx#9294]
## Current Behavior
ng build --project <projectname> is throwing the compile time error in nx mono repo after using module federation

## Expected Behavior

ng build --project <projectname> should work without any error.

### Failure Logs
An unhandled exception occurred: [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.
f you are leveraging \`readCachedProjectGraph()\` directly then you will need to refactor your usage to first ensure that
the ProjectGraph is created by calling \`await createProjectGraphAsync()\` somewhere before attempting to read the data.

If you encounter this error as part of running standard \`nx\` commands then please open an issue on https://github.com/nrwl/nx

Make sure invoke 'node ./decorate-angular-cli.js' in your postinstall script.
The decorated CLI will compute the project graph.
'ng --help' should say 'Smart, Fast and Extensible Build System'.
See "/private/var/folders/gc/r2lbllp507xfmf5md5wwqy_80000gp/T/ng-nImfNG/angular-errors.log" for further details.

**Comment by Coly010** [comment]
Hey! Sorry that you have encountered this issue. 

Could you share a minimal reproduction of this issue? It'll be difficult to investigate without any indication of what is causing the problem.
