### ISSUE TITLE
 NX   spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by deepkuma** [nrwl/nx#9295]
## Current Behavior
Unable to serve / build / test project using nx cmd.

## Expected Behavior
It was working 1 day before but nx cmd stopped working without updating anything.

### Failure Logs
PS C:\Developer\git\fb> nx build

 >  NX   spawn ENAMETOOLONG

PS C:\Developer\git\fb> nx test

 >  NX   spawn ENAMETOOLONG

### Environment
   Node : 17.3.1
   OS   : win32 x64
   npm  : 8.3.0
   
   nx : 13.8.7
   @nrwl/angular : 13.8.3
   @nrwl/cli : 13.8.7
   @nrwl/cypress : 13.8.7
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.3
   @nrwl/eslint-plugin-nx : 13.8.7
   @nrwl/express : undefined
   @nrwl/jest : 13.8.7
   @nrwl/js : undefined
   @nrwl/linter : 13.8.7
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.3
   @nrwl/tao : 13.8.7
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.3
   typescript : 4.5.5
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
         @angular/animations: 13.2.6
         @angular/cdk: 13.2.6
         @angular/common: 13.2.6
         @angular/compiler: 13.2.6
         @angular/core: 13.2.6
         @angular/forms: 13.2.6
         @angular/material: 13.2.6
         @angular/platform-browser: 13.2.6
         @angular/platform-browser-dynamic: 13.2.6
         @angular/router: 13.2.6
         @angular-devkit/build-angular: 13.2.6
         @angular/cli: 13.2.6
         @angular/compiler-cli: 13.2.6
         @angular/language-service: 13.2.6

**Comment by deepkuma** [comment]
@AgentEnder.  It is fixed now seems like updating @nrwl/workspace to latest version helped. Not sure on one thing. why NX cmd stopped working if it was working previously (I did not updated and dependency version).

**Comment by AgentEnder** [comment]
This error looks similar to something we fixed in 13.8.X that was caused by a large number of git changes that were not yet committed.
