### ISSUE TITLE
Generated paths in tsconfig.json prevent building of publishable libraries with dependencies to other libraries

### ISSUE THREAD

**Issue by strobocopter** [nrwl/nx#930]
## Expected Behavior

I would expect to be able to create multiple, publishable libraries inside my mono-repo, that can depend upon each other and all be builded separately.
Therefor the contents generated inside the tsconfig.json should cause any problems. 

## Current Behavior

Currently the generated "paths" in the tsconfig.json will cause errors, when trying to build a library that depends upon another library.
This can be fixed when the "paths" are adjusted to look the way they are generated by angular-cli itself --> let them point into the dist-folder.

Now each library can be build. But doing this reveals a further problem:
The generated symbolic names inside the tsconfig.json for libraries inside folders do not match the names of the npm-packages that are generated for those libraries. 
(Example:  generated in tsconfig.json is "@abc/something/else" : ["libs/something/else/src/index.ts"] but package-name generated is "@abc/something-else")
When those symbolic names (like "@abc/something/else") are used for imports inside the ts-code of other libs, they will still be present in the output code of those libraries (e.g. in "dist/libs/something/else/fesm2015/..js").
When now an app should be built that references such a library corrupted imports the app will get a build-error, that denotes that an import could not be resolved - which is correct as no npm-package with the name of the import exists.

## Failure Information (for bugs)

Please have a look at this github-repo:
https://github.com/strobocopter/nx-build-lib-fails

The master-branch demonstrates the problem when trying to build a library that depends upon another library with the default generated tsconfig.json

### Steps to Reproduce

Simply get both branches of the linked repo and follow the steps in the corresponding readme.md

### Context

* version of Nx used 7.1.0
* version of Angular CLI used 7.0.1
* `angular.json` configuration -> see linked repo
* version of Angular DevKit used 7.0.6

**Comment by pos1tron** [comment]
>This can be fixed when the "paths" are adjusted to look the way they are generated by angular-cli itself --> let them point into the dist-folder.

@strobocopter Can you share an example of a fixed tsconfig.json that would make the build work?

**Comment by ViceIce** [comment]
@strobocopter Your paths mapping should match the package name

if your tsconfig.json has `@abc/something/else` than the package.json name should be `@abc/something/else`

**Comment by strobocopter** [comment]
> 
> 
> @strobocopter Your paths mapping should match the package name
> 
> if your tsconfig.json has `@abc/something/else` than the package.json name should be `@abc/something/else`

Unfortunately a package-name may not contain any "/"-characters besides the one that separates it from the scope-name.
See: [https://docs.npmjs.com/files/package.json#name](url)
Nevertheless if the name could be in the format proposed by you, then the generated package.json should use the right name.

**Comment by ViceIce** [comment]
@strobocopter If you use more than one slash, you need secondary entrypoints in you package

See [Secondary Entry Points](https://github.com/ng-packagr/ng-packagr/blob/HEAD/docs/secondary-entrypoints.md#secondary-entry-points)

**Comment by strobocopter** [comment]
> 
> 
> @strobocopter If you use more than one slash, you need secondary entrypoints in you package
> 
> See [Secondary Entry Points](https://github.com/ng-packagr/ng-packagr/blob/HEAD/docs/secondary-entrypoints.md#secondary-entry-points)

That's clear to me, but thats totally not the point of this issue. 

We do not have one library with multiple entry-points. We have two separate libraries generated with two separate package.json files. Both are generated into a sub-folder of the libs-folder.
The names generated in their package.json files are correctly derived from their location. Every "/" is tranlated into an "-" for the package-name.
But the names generated in the tsconfig.json do not match the generated names the corresponding package.json files.
This causes problems when the first library depends on the second library.

**Comment by strobocopter** [comment]
> 
> 
> > This can be fixed when the "paths" are adjusted to look the way they are generated by angular-cli itself --> let them point into the dist-folder.
> 
> @strobocopter Can you share an example of a fixed tsconfig.json that would make the build work?

The fixed paths-section of the global tsconfig.json would look like this:
`"paths": {
      "@stroboware/framework-utils": [
        "dist/libs/framework/utils"
      ],
      "@stroboware/framework-tracing": [
        "dist/libs/framework/tracing"
      ]
}`
This way the paths-configuration matches the names used in the package.json files of the libraries.

Unfortunately with this configuration ng serve that not recognise changes inside the library-code. We faced this issue now by providing two different tsconfig-files in our workspace. One is used by ng serve and references the source-folder of the libraries. The second file is used for building our application and references the dist-folder.

**Comment by ViceIce** [comment]
Ok, now i know what you mean. I have the same problem even without using nx. This is a known angular bug

https://github.com/angular/angular-cli/issues/13588

**Comment by kristofdegrave** [comment]
Maybe another idea is to add the npm name of publishable packages and add this to the paths variable.
```
{
  ...
  "paths": {
    "@myLib/core-test": ["libs/core/test/src/index.ts"]
  }
}
```
I would like to have this, to make refactoring the publishable packages into a seperate repo easier. In that case I can just leave `import {} from '@myLib/core-test'` in my code. In the current scenario I have to replace  `import {} from '@myLib/core/test'` with  `import {} from '@myLib/core-test'` if I do the refactoring.

So my concrete question was, if you create a library with the `--publishable` option, can the path mapping in the tsconfig.json be:
```
{
  ...
  "paths": {
    "@myLib/core-test": ["libs/core/test/src/index.ts"]
  }
}
```

**Comment by FrozenPandaz** [comment]
This should be fixed now with the new `@nrwl/angular:package` builder.

Can you please confirm? @juristr

**Comment by juristr** [comment]
@FrozenPandaz Yes, with the latest Nx version and publishable libraries this should be fixed. More [on our blog](https://blog.nrwl.io/nx-8-12-distributed-caching-improved-dependency-detection-better-support-for-buildable-libraries-6f7cec17b83f). It was introduced in `v8.12` & optimized in `v9`.

@kristofdegrave that should already be the case if you generate a new buildable library (aka publishable library) with the latest Nx version.

Closing the issue as this should be resolved.

**Comment by tobico** [comment]
@juristr this does not appear to be fixed with the `@nrwl/workspace` or `@nrwl/react` plugins.

You can see the problem code here, where `projectDirectory` is used in the import path instead of `projectName`: https://github.com/nrwl/nx/blob/master/packages/workspace/src/generators/library/library.ts#L238

I can submit a PR to fix these if it's welcome.
