### ISSUE TITLE
Expose all arguments to executor through context

### ISSUE THREAD

**Issue by Telokis** [nrwl/nx#9302]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
I would like to be able to do `nx run app:exec arg1 arg2 arg3` (note the positional arguments).  
The executor responsible for `exec` would then call the `app` like so: `node <path to app.js> arg1 arg2 arg3` (positional arguments are preserved).  
This is currently not possible because all positional arguments are discarded in `commands/run.ts`.  
Just to clarify: this is different from using the `run-command` executor because this executor requires the arguments to be hard-specified inside the `project.json` which is not my goal.

## Motivation
This would help handling CLI applications when using NX. Currently, I need to first build the app and then run `node` myself.  
I would like to use the same entrypoint for all my apps.

## Suggested Implementation
The most clean and non-breaking way would be to provide the whole original `process.args.slice(2)` array as a `context` property when calling executors.

## Alternate Implementations
We could add a special `forwardPositional` config in the executor schema. This would add a `"_"` array to options, with unparsed arguments.  

Another thing I expected to work was using `"cli": "node"` inside the `schema.json` of my executor. I thought this would simple call `node` but it only made my executor crash. (Expected something related to angular, from what I saw. Specifying anything other than `"nx"` means "use raw angular cli").

**Comment by Telokis** [comment]
Still an issue..

**Comment by Telokis** [comment]
Was this implemented?

**Comment by NexusNull** [comment]
This is still an issue.

**Comment by FrozenPandaz** [comment]
This was implemented. Any arguments which are not Nx specific are forwarded now.
