### ISSUE TITLE
Adding new libs in VS Code seems to corrupt workspace.json file by removing "cli" entry

### ISSUE THREAD

**Issue by bdphil86** [nrwl/nx#9303]
## Current Behavior
When I run `yarn` or `npm install`, I get an error message:

`
Output:
>  NX   Nx Daemon was not able to compute the project graph.

   Log file with the error: H:...\node_modules\.cache\nx\d\daemon-error.log
   Please file an issue at https://github.com/nrwl/nx
   Nx Daemon is going to be disabled until you run "nx reset".
`

For some reason, it keeps removing the following lines of code from workspace.json:

`
},
    "cli": {
      "defaultCollection": "@nrwl/workspace"
    }
`

I added new libs using the built-in generator in VS Code. It seems to remove this for some reason.

## Expected Behavior
I don't expect to get any error messages.

## Steps to Reproduce
1. Clone a repo created with nx CLI.
2. Use `yarn` or `npm install` go generate packages.

### Failure Logs

`
Output:
>  NX   Nx Daemon was not able to compute the project graph.

   Log file with the error: H:...\node_modules\.cache\nx\d\daemon-error.log
   Please file an issue at https://github.com/nrwl/nx
   Nx Daemon is going to be disabled until you run "nx reset".
`

### Environment

  Node : 16.3.0
  OS   : win32 x64
  yarn : 1.22.17

  nx : 12.10.1
  @nrwl/angular : Not Found
  @nrwl/cli : 12.10.1
  @nrwl/cypress : 13.8.7
  @nrwl/devkit : 13.8.7
  @nrwl/eslint-plugin-nx : 12.10.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.10.1
  @nrwl/linter : 12.10.1
  @nrwl/nest : Not Found
  @nrwl/next : 13.8.7
  @nrwl/node : Not Found
  @nrwl/nx-cloud : 13.1.6
  @nrwl/react : 13.8.7
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.1
  @nrwl/web : 13.8.7
  @nrwl/workspace : 12.10.1
  @nrwl/storybook : 13.8.7
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by AgentEnder** [comment]
@bdphil86 It looks like your package versions are mismatched. All @nrwl/* packages except nx-cloud should be the same version, I think thats whats causing the issue. Can you try with latest?

Thanks!
