### ISSUE TITLE
@nrwl/js: add an option to symlink the output of a library to `node_modules` of the workspace folder

### ISSUE THREAD

**Issue by DibyodyutiMondal** [nrwl/nx#9304]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Add an option that when specified, symlinks the output of a library to the workspace-level `node_modules`.
This proposal is only for libraries, but in truth it could be done for apps as well. However, I have not come across such a requirement yet.

## Motivation

Currently, the `@nrwl/js` package works fine and great. However, in certain cases, running the code becomes really troublesome.
The requirements for my project are as follows:
  a. The output must be ESM. No webpack etc. Just the tsc output for each library/application. No extra compilation/build steps.
  b. The code must be able to run anywhere. For example, in my particular case, both firebase functions and google app engine, (and the firebase emulator)
  c. incremental builds with watch mode during dev

The `@nrwl/js` does not have an executor for running an application, but the `@nrwl/node:node` executor exists. However, 
  a. It tries to use commonjs require to load my app, which obviously fails. And I have not been able to find a way to tell @nrwl/node to use esm loading. I believe I saw in another issue that the `@nrwl/node` package is to be deprecated anyway.
  b. Using nodemon because I can't use `@nrwl/node:node` doesn't work, because it can't resolve the project dependencies
  c. Inside of the firebase emulator, we can't use nrwl tooling. so it also can't resolve the project dependencies

So currently, for this particular type of project configuration which is going for a minimal, incremental esm development approach, there is no way to use nrwl for resolving dependencies at runtime during development.

Symlinking the output folder with the workspace level `node_modules` immediately enables 2 things:
a. The code simply works in development. Whether I use nodemon or the firebase emulator - it just simply work.
b. We no longer have to rely on setting the typescript path config for the libraries.

However, my concern with this is: I am not entirely sure if symlinking outputs into `node_modules` is a good practice. If it isnt' I would like to suggest a compromise: symlink it into `dist/node_modules` instead of workspace-level `node_modules`. That works perfectly, although we then have to continue to use tsconfig path configuration, and deal with the incorrect import suggestions (that happen even now), but that's not really a big issue - just mildly irritating, I suppose.

## Suggested Implementation

Following is a custom executor I use that just does this at the beginning of every build, and delegates it back to the `@nrwl/js:tsc` builder

```typescript

import { ExecutorContext } from '@nrwl/devkit';
import { tscExecutor as nrwl_tsc_exec } from '@nrwl/js/src/executors/tsc/tsc.impl';
import { ExecutorOptions } from '@nrwl/js/src/utils/schema';
import * as fs from 'fs/promises';
import * as path from 'path';


export async function* custom_tscExecutor(
    options: ExecutorOptions,
    context: ExecutorContext
) {
    const dist_path = path.resolve(context.cwd, options.outputPath);

    // do this at the beginning of the command 
    // (but not on every build, for ex. in watch mode)
    if (context.workspace.projects[context.projectName!].projectType === 'library') {
        const node_path = path.resolve(context.cwd, `node_modules/@${context.workspace.npmScope}/${context.projectName}`);
        await fs.rm(node_path, { recursive: true, force: true });
        await fs.mkdir(path.resolve(node_path, '..'), { recursive: true });
        await fs.symlink(dist_path, node_path, 'dir');
    }

    return yield* nrwl_tsc_exec(options, context);
}

export default custom_tscExecutor;
```

**Comment by DibyodyutiMondal** [comment]
The typescript path config will still be necessary otherwise watch mode stops working after making edits

(PS: Sorry for the wrong button click)

**Comment by DibyodyutiMondal** [comment]
Hi, any thoughts on this?

**Comment by quincarter** [comment]
I'll +1 to this. I'd like to drop lerna and just use Nx altogether for my component library but this is kind of preventing me from doing that.

**Comment by PetarKirov** [comment]
We're using [Yarn (v3) workspace](https://yarnpkg.com/features/workspaces) for this:
1. Add `apps` and `libs` folders to the `workspaces` field in the root `package.json`
2. Generate the library as usual with `nx g ...`
3. Run `yarn install`. At this point yarn will add the newly generated library to `yarn.lock` and symlink it in `node_modules`

But in general I agree that it sucks that Nx insists on using `tsconfig.base.json` paths for this, as it breaks compatibility with various tools that otherwise work fine by using `require.resolve`.
