### ISSUE TITLE
It is not possible to run the example of generator definitions in the documentation.

### ISSUE THREAD

**Issue by lejinseop** [nrwl/nx#9309]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[generator-options#definitions](https://nx.dev/generators/generator-options#definitions)

### Additional context or description

I'm making a generator while looking at the documentation.
So, I'm learning by running all the examples.

the test sequence is as follows.
1. npx create-nx-workspace@latest --preset=core
2. nx generate @nrwl/workspace:workspace-generator my-generator
3. copy and paste [definitions example](https://nx.dev/generators/generator-options#definitions) to schema.json
4. nx workspace-generator my-generator

example shcema.json
```json
{
  "$id": "https://example.com/schemas/customer",
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "type": "object",
  "properties": {
    "first_name": { "type": "string" },
    "last_name": { "type": "string" },
    "shipping_address": { "$ref": "/schemas/address" },
    "billing_address": { "$ref": "/schemas/address" }
  },
  "required": [
    "first_name",
    "last_name",
    "shipping_address",
    "billing_address"
  ],

  "$defs": {
    "address": {
      "$id": "/schemas/address",
      "$schema": "http://json-schema.org/draft-07/schema#",

      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city": { "type": "string" },
        "state": { "$ref": "#/definitions/state" }
      },
      "required": ["street_address", "city", "state"],

      "definitions": {
        "state": { "enum": ["CA", "NY", "... etc ..."] }
      }
    }
  }
}
```

Meanwhile, I was testing the definitions part. However, the example could not be executed and the following error occured.

<img width="345" alt="image" src="https://user-images.githubusercontent.com/79432498/158050326-747f5815-5858-4914-b9c6-ff3bab00b09b.png">

I looked at the definition resolver and [found a condition](https://github.com/nrwl/nx/blob/5a74c02a49076a145cdba8d475b03193f317c889/packages/tao/src/shared/params.ts#L487). 

<img width="496" alt="image" src="https://user-images.githubusercontent.com/79432498/158050556-4fdc71b1-054f-4a43-912d-e83fe99ca8f6.png">

Is there something I've missed in the documentation?

**Comment by AgentEnder** [comment]
Hey @lejinseop, it looks like this should be updated in the docs. Does it work if you use `definitions` instead of `defs`?
