### ISSUE TITLE
Enums/constants undefined in the runtime when self-imported in library

### ISSUE THREAD

**Issue by thefill** [nrwl/nx#9319]
## Current Behavior
While importing enum or const in the same library using @project/lib-name emitted code throws error:
```
TypeError: Cannot read property 'XYZ' of undefined
```
If code is imported using relative path all is fine:
```
// throws error when using this enum/const
import {SomeEnum} from '@project/lib-name';

// no error
import {SomeEnum} from '../lib-name'; // or './lib-name' or any relative path
```

## Expected Behaviour
No error expected - self-imports should be supported.

## Steps to Reproduce
1. Create node app 'test'
2. App content: 
```
import { test } from '@github-issue/test-lib';
test();
```
3. Create node lib 'test-lib'
4. Create 2 files in the lib test-1.ts and test-2.ts
5. in the lib index export from both
```
export * from './lib/test-2';
export * from './lib/test-1';
```
6. file test-1.ts
```
export enum TestEnum {
  DOO = 'DOO',
}
```
7. test-2.ts
```
import { TestEnum } from '@github-issue/test-lib';

const testConst = {
  [TestEnum.DOO]: 'aa',
};

export function test(): string {
  return 'test';
}
```
8. Serve app
9. Error
```
~/.../libs/test-lib/src/lib/test-2.ts:4
  [TestEnum.DOO]: 'aa',
          ^
TypeError: Cannot read property 'DOO' of undefined
```
10. Change test-2.ts to
```
import { TestEnum } from './test-1';

const testConst = {
  [TestEnum.DOO]: 'aa',
};

export function test(): string {
  return 'test';
}
```

### Environment
   Node : 14.17.6
   OS   : darwin x64
   yarn : 1.22.17

   nx : 13.8.8
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.8
   @nrwl/cypress : undefined
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.8
   @nrwl/eslint-plugin-nx : 13.8.8
   @nrwl/express : undefined
   @nrwl/jest : 13.8.8
   @nrwl/js : 13.8.8
   @nrwl/linter : 13.8.8
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : 13.8.8
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : undefined
   @nrwl/tao : 13.8.8
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.8
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

**Comment by sebastiancotta** [comment]
could try putting const when create enum
