### ISSUE TITLE
Running test takes too much time.

### ISSUE THREAD

**Issue by Tomek678** [nrwl/nx#933]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

* [yes] I am running the latest version
* [yes] I checked the documentation and found no answer
* [yes] I checked to make sure that this issue has not already been filed
* [yes] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior
Running npm run affected:test -all take too much time. We should reduce this time.

## Current Behavior
For now you can run npm run affected:test -- --all to run all test

If you run this command above nx will grab all libs and apps tests and run ng test for each libs/apps independent. This means that for each lib/apps will be open browser and compile modules. And this takes time that is redundant.

## Failure Information (for bugs)
If you run npm run test affected:test -- --all 
In this branch: https://github.com/nrwl/nx-examples/pull/60
**Tests will execute 4 minutes (sic!) and there is only 29 tests.** 
> real	4m2.462s
> user	4m18.752s
> sys	0m28.848s

## How we can speed up test execution time ?
We can create karma.conf.js, test.ts and tsconfig.spec.json
In test.ts grab all the test from libs/apps
Execute in ONE browser and compile modules only ones:
Than the same test will take:
> real	0m26.657s
> user	0m26.316s
> sys	0m2.156s

## What is the best solution ?
We can run nx affected, grab all the tests from affected libs/app and run them in ONE browser.

I really don't see and values from reopening browser for each libs/app.

**Comment by FrozenPandaz** [comment]
Yes, running absolutely _all_ the tests will take longer, but you would want to do this as rarely as possible so it's not a use case we are optimizing for. I understand taking 4 minutes is ridiculous for a small amount of tests. However, for large repositories, there may be thousands or 10s of thousands of tests (There really is no limit).

Running tests for projects independently allows them to be intelligently selected for execution. `affected` analyzes the dependencies of your workspace and only runs the projects which have been touched or affected by the projects which have been touched. (Run `yarn affected:dep-graph` to visualize this).

**Comment by Tomek6789** [comment]
Ok, I understand the power of affected and i really admire this functionality. 

But affected:test should have some option flag to run all test for affected projects in ONE browser.
To do this we can split this task to two part:
1. Provide karma.conf and tsconfig.spec.json for browser
2. Grab all test from affected projects and include them to browser.

I think it will be nice to have this optional functionallity. 

P.S If developer change something in package.json affected:test will run all test.

**Comment by jasedwards** [comment]
as an FYI, we have to run them all at once on our build server to generate a comprehensive coverage report.  We have run into an issue recently where it timesout after an hour.  it usually runs about 1500 tests.  Not sure if this would solve that or not.  Locally a dev never does that as they just test their app or lib.

**Comment by Tomek6789** [comment]
You need to run all the test when you change something from implicitDependencies. For example: package.json

**Comment by vsavkin** [comment]
@Tomek6789  You are right that launching an instance of chrome is slow. There are two ways to make it faster:
- Use chrome headless
- Use Jest (the startup time for Jest is a tiny fraction of the startup time for Karma)
- You should also use: yarn affected:test --parallel

We cannot reuse the same karma instance to run tests for several projects for the following reason: the execution of a project's tests should not depend on another project's tests. Sharing a karma instance will break this. That's why we run every project's tests in a separate process.
