### ISSUE TITLE
Support for logHeapUsage and detectLeaks when using jest

### ISSUE THREAD

**Issue by jepetko** [nrwl/nx#9338]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Support for Jest's memory leaks detection options, namely:
* `logHeapUsage` (see https://jestjs.io/docs/cli#--logheapusage)
* `detectLeaks` (although experimental, this feature was added years ago so it does not seem to be experimental any longer: https://github.com/facebook/jest/blame/54eab578597125bf666b4d9ccfe58273c2934dc6/packages/jest-cli/src/cli/args.ts#L234)

## Motivation

These options help immensely when fixing memory leaks. Therefore they need to be passed on Jest CLI.

## Suggested Implementation

Adapt the schema and add options to jest.impl.ts. 

## Alternate Implementations

none

**Comment by barbados-clemens** [comment]
`@nrwl/jest:jest` should support passing any args through to the jest cli as of #9904 even if it's not in the schema so you can give that a try.

**Comment by barbados-clemens** [comment]
Didn't see the PR you made. Closing
