### ISSUE TITLE
Include tslib as a dependency in buildable packages when importHelpers is true

### ISSUE THREAD

**Issue by ajwootto** [nrwl/nx#9343]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
When creating a publishable npm package using the `@nrwl/js` package, and having the package.json autogenerated by Nx with the set of detected dependencies, the resulting output won't work when `importHelpers: true` is set in the tsconfig.

The resulting package output has a dependency on `tslib` due to the importHelpers setting, but that dependency is not listed in the package.json output. Therefore, if you publish the package it will not be functional when installed via npm. 

If this option is set in the tsconfig, Nx could infer that the tslib package is a required dependency of any package that is built.

## Motivation
WIthout automatic detection of this dependency, the output of `nx build` will not be a usable package. The only workaround would be to manually add the dependency to the package.json of each buildable package in the project.

## Suggested Implementation
Nx could inspect the tsconfig settings to determine whether the "importHelpers" option is in use, and adjust the package.json output if it is.

## Alternate Implementations
There could also be a setting like "additionalDependencies" in the nx.json that would let you add additional required packages in one place. This wouldn't be quite as nice since it's a pretty easy trap to walk into if you're using this setting and don't really understand what it actually does (like I was). 

Nx sets this to true by default when you generate a new repo, so basically any newly generated repo wouldn't be able to create publishable NPM packages without manual intervention

**Comment by gioragutt** [comment]
I'd like to try to solve this one. I'll do some code research and see if I can find how to do that 👍🏻

**Comment by gioragutt** [comment]
My pleasure @ajwootto 🙂

**Comment by jkossis** [comment]
@gioragutt this solution looks awesome! Wanted to get your thoughts on this, since you did the initial implementation for `@nrwl/js` ... any reason this shouldn't also live in `@nrwl/node`?  I'm running into the exact same issue when building a node-based project, gotta manually include tslib for things to run probably (due to the `importHelpers` flag).

Tagging OP as well: @ajwootto
