### ISSUE TITLE
Serving default @nrwl/next:server makes a dist/ folder outside repository

### ISSUE THREAD

**Issue by frasermcc9** [nrwl/nx#9347]
Hey team,

## Current Behavior
When running `nx serve` in a default next js project, a `dist` directory appears to be created two levels outside the repository, i.e. at `../../dist` if cwd is the repo root. 

This is especially problematic in devcontainers, where trying to making a directory at `../../dist` causes a permission error.

## Expected Behavior
Either this directory is not created, or its created inside the repository.

## Steps to Reproduce
1. Create a new next workspace `npx create-nx-workspace --preset=next`
2. Run `npm start` to serve the next project
3. A directory has been made at `../../dist`

## Investigation
It seems to be a problem caused inside the default nextjs server, `server/dev/hot-reloader.js`:
```js
await _fs.promises.mkdir(this.config.distDir, {
  recursive: true
});
```
The value for `this.config.distDir` is `'../../dist/apps/site/.next'` by default. When this line is executed, the problematic directory is created. Changing `next.config.js` to the following (adding distDir) seems to stop the random `dist/` directory being made incorrectly, but then causes the actual output directory to be incorrect.

```js
const nextConfig = {
  distDir: 'dist/apps/site/.next',
  nx: {
    // Set this to true if you would like to to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: false,
  },
};
```

### Environment
```
 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : win32 x64
   npm  : 8.1.2
   
   nx : 13.9.0
   @nrwl/angular : undefined
   @nrwl/cypress : 13.9.0
   @nrwl/detox : undefined
   @nrwl/devkit : 13.9.0
   @nrwl/eslint-plugin-nx : 13.9.0
   @nrwl/express : undefined
   @nrwl/jest : 13.9.0
   @nrwl/js : 13.9.0
   @nrwl/linter : 13.9.0
   @nrwl/nest : undefined
   @nrwl/next : 13.9.0
   @nrwl/node : undefined
   @nrwl/nx-cloud : 13.1.6
   @nrwl/nx-plugin : undefined
   @nrwl/react : 13.9.0
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.9.0
   @nrwl/web : 13.9.0
   @nrwl/workspace : 13.9.0
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by NatoNathan** [comment]
This is an issue, we are having with nx, nextjs and gitpod.

**Comment by ndcunningham** [comment]
Is this still happening with the latest version of Nx @frasermcc9 ?

**Comment by frasermcc9** [comment]
Yes the issue doesn't happen on the newest version. Thanks guys 😄
