### ISSUE TITLE
Support more jest cli params

### ISSUE THREAD

**Issue by sforner405** [nrwl/nx#935]
## Expected Behavior

We use a Plugin for VSCode and jest debugging, where you can debug a specification directly from vscode. 
You should be able to use the plugin from vscode with nx.

## Current Behavior

It used to work, but stoped after upgrading to NX 7.1.1.

## Failure Information (for bugs)

There are unknown params provided to the angular cli, which causes the test not to run.
Parameters are the file to test (test.spec.ts) and the testNamePattern.
Eaxample: 
ng test lib-name test.spec.ts --testNamePattern "should run"

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. ng test lib-name test.spec.ts --testNamePattern "should run"

### Context

* version of Nx used 7.1.1
* version of Angular CLI used 7.1.0

**A minimal reproduce scenario using allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

Unknown option: 'test.spec.ts'
Unknown option: '--testNamePattern'
Unknown option: 'should run'

**Comment by FrozenPandaz** [comment]
Closed with #940
