### ISSUE TITLE
All Nx cli commands fail on 13.9

### ISSUE THREAD

**Issue by manan-jadhav** [nrwl/nx#9359]
## Current Behavior
All NX cli commands fail for me with no output, even `--help`.

## Expected Behavior
Nx cli commands should work - at least `--help` should. 

This started to happen since yesterday, giving me the hint that this might be a regression in `13.9`

## Steps to Reproduce
I already had a monorepo - so I ran this command according to docs: 
`npx add-nx-to-monorepo`

I've done this multiple times, after switching to a clean branch and clearing `node_modules`, and running `npm install`. 

When I pin the `@nrwl/*` versions to `13.8`, it works fine.

### Failure Logs
Nx commands return nothing except a non-zero return code. Stdout / stderr is completely empty, even for `npx nx`

### Environment
Node : 14.17.5
OS   : darwin x64
npm  : 6.14.14

The following version gives me this error:
```
"@nrwl/cli": "latest",
"@nrwl/tao": "latest",
"@nrwl/workspace": "latest",
```

**Comment by LuckeeDev** [comment]
I'm having the same issue migrating from `13.8.8` to `13.9.0`. The command `nx migrate latest` takes forever and doesn't output anything.

**Comment by andynunes** [comment]
Although the actual issue you're reporting might not be fixed in `13.9.1`, as I'm now getting:
```
Unexpected error:
Error: Cannot find module 'nx/src/cli/run-cli.js'
```

**Comment by jahumes** [comment]
I am wondering if this is related to https://github.com/nrwl/nx/issues/9346

**Comment by LuckeeDev** [comment]
@andynunes it worked, thanks a lot!

**Comment by manan-jadhav** [comment]
Update: After updating to `13.9.2`, I now see the warning ("Please update your global Nx").

**Comment by manan-jadhav** [comment]
Update: I think I understand what happened:

- I added Nx to my monorepo when the version was `13.8.8`
- Next day, I ran `npm install` after merging in another dev's work that lead to `package-lock.json` getting updated, and my version getting updated to `13.9.x` (I'm not sure if `13.9.0` or `13.9.1`)
- At this point, `require('nx/bin/nx')` in my `node_modules/.bin/nx` started to fail silently because of `@nrwl/cli` being removed in `13.9.1`. I don't know why it didn't throw a `Module not found`.
- I started seeing the warning message a few hours ago when `13.9.2` was released.

**Comment by manan-jadhav** [comment]
@FrozenPandaz Steps to reproduce:

1. Use `npx add-nx-to-monorepo` to add Nx to a monorepo
2. Nx cli commands won't work after this. 

`npx add-nx-to-monorepo` does not add `"nx": "latest"` to my package.json, which is the root of the problem.

There is no point in sharing a repro repo because this is an issue with `npx add-nx-to-monorepo` and `13.9.0` together. 

When `13.8.x` was latest, `add-nx-to-workspace` worked fine.

I'm going to make an issue report on that project too.

**Comment by junzhengca** [comment]
Not sure if this helps. I recently ran the migration utility to migrate from nx 13.4.1 to latest, but for some reason, nx did not automatically update the version of `@nrwl/cli`.

Simply changing the `@nrwl/cli` version to match others fixed the issue.

**Comment by viceice** [comment]
Seeing the same when upgrading from 13.8.x.

repro
```sh
> npx create-nx-workspace@latest --preset angular --cli angular nx-v13
√ Application name                    · test-app
√ Default stylesheet format           · scss
√ Use Nx Cloud? (It's free and doesn't require registration.) · No
> cd .\nx-v13\
> npm run update
> npm install --legacy-peer-deps
> npx nx migrate --run-migrations
```
Checkout `package.json` before and after `npx nx migrate --run-migrations` and you see the issue.

**Comment by viceice** [comment]
Should `@nrwl/cli` removed from `package.json` or updated?

**Comment by manan-jadhav** [comment]
removing `@nrwl/cli` and replacing with `nx` worked for me

**Comment by shayll-herolo** [comment]
can confirm on 13.9.4, uninstalling `@nrwl/cli` and installing `nx` worked for me.
`npm uninstall -D @nrwl/cli`
`npm install -D nx`
I can run all `nx` commands now

**Comment by viceice** [comment]
the `nx` package was there after migration and `@nrwl/tao` was also removed. It seeems the migration code missed the `@nrwl/cli`

**Comment by JoA-MoS** [comment]
I can confirm that `@nrwl/cli` was not updated in the migration step and uninstalling `@nrwl/cli` and install `nx` solved the issue. 

This is also the case for the global package. Could we update the error messging to indicate that you need to uninstall `@nrwl/cli`

```
Please update your global install of Nx
- npm install -g nx
> If you had previously installed the nx cli using the @nrwl/cli package uninstall this and install using the nx package
- npm uninstall -g @nrwl/cli
- npm install -g nx
```

**Comment by vltansky** [comment]
manual updated `@nrwl/cli` to version `13.9.4` solved it for me.
`npm i @nrwl/cli@13.9.4 -D`

**Comment by ThomasBurleson** [comment]
Definitely the migration scripts should account for this.

**Comment by BensonBen** [comment]
recently bumped into this issue. I used @shayll-herolo 's solution which allowed me use cli commands locally.
I reverted to a previous version of my project using `git reset --hard someCommitHash` then using `nx migrate latest` tried to bypass bad versions. Whatever migrations wasn't working before still isn't working
