### ISSUE TITLE
Error building when using mfe 

### ISSUE THREAD

**Issue by a616101** [nrwl/nx#9375]
## Current Behavior
As Title, my mfe setting:
host: main
remote: feat1

When I build the main project I get the following error.

**Generating browser application bundles (phase: setup)...SharedMappings.register: tsConfigPath needs to be an absolute path!**

I think it may be caused by the following.
const tsConfigPath = process.env.NX_TSCONFIG_PATH ?? path.join(__dirname, "../../tsconfig.base.json");
process.env.NX_TSCONFIG_PATH value is "apps/main/tsconfig.app.json"
This path not a absolute path.

## Expected Behavior
When building the main project, it should be able to be successfully built.

_I tried to set tsConfigPath as an absolute path and the result was able to build successfully_

### Environment
 NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : darwin x64
   npm  : 8.3.1
   
   nx : 13.9.0
   @nrwl/angular : 13.9.0
   @nrwl/cypress : 13.9.0
   @nrwl/detox : undefined
   @nrwl/devkit : 13.9.0
   @nrwl/eslint-plugin-nx : 13.9.0
   @nrwl/express : undefined
   @nrwl/jest : 13.9.0
   @nrwl/js : 13.9.0
   @nrwl/linter : 13.9.0
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/nx-plugin : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.9.0
   @nrwl/web : 13.9.0
   @nrwl/workspace : 13.9.0
   typescript : 4.5.5
   rxjs : 7.5.5

**Comment by zwjohn** [comment]
Getting the same issue after upgrade to the latest NX 
- Generating browser application bundles (phase: setup)...SharedMappings.register: tsConfigPath needs to be an absolute path!

**Comment by Coly010** [comment]
Thanks for reporting the issue! 🙂 

I've a fix in PR 🙂

**Comment by zwjohn** [comment]
@Coly010 Thanks!. 

For people having this issue before receiving the patch, you can use node path to get the absolute path as shown below

const tsConfigPath = process.env.NX_TSCONFIG_PATH ? path.join(__dirname, '../../'+process.env.NX_TSCONFIG_PATH) : path.join(__dirname, '../../tsconfig.base.json');

**Comment by lhenriquegomescamilo** [comment]
> @Coly010 Thanks!.
> 
> For people having this issue before receiving the patch, you can use node path to get the absolute path as shown below
> 
> const tsConfigPath = process.env.NX_TSCONFIG_PATH ? path.join(__dirname, '../../'+process.env.NX_TSCONFIG_PATH) : path.join(__dirname, '../../tsconfig.base.json');

@zwjohn thanks for the answer, it's works for me!
