### ISSUE TITLE
"Please update your global install of Nx " - 13.9.2@nrwl/workspace:run-commands

### ISSUE THREAD

**Issue by raphael22** [nrwl/nx#9388]
## Current Behavior

Even though I update nx globally and @nrwl/cli from my projects to 13.9.2 I got this warning output from every nx commands wrap in executor:run-commands.
```
Please update your global install of Nx
- npm install -g nx
```
Related to #9359

## Expected Behavior
Last @nrwl/workspace:run-commands should not output warning about updating :)

## Steps to Reproduce
- Create a workspace with angular preset
`npx create-nx-workspace@latest`

- Wrap default build command with an executor
```
    "build-app": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "commands": ["nx run test-ng:build"],
        "parallel": false
      }
    },
```
- nx build
```
no warning
```
- nx build-app
 ```
 > nx run test-ng:build-app

Please update your global install of Nx
- npm install -g nx

> nx run test-ng:build:production
```

### Environment

Windows 10 - WSL2 Ubuntu
Node 16 - npm 8
Angular 13.3 - Nx 13.9.2

**Comment by michael-golden** [comment]
I believe the issue comes from linee 65 of decorate-angular-cli.js:

changed from  `require('nx/cli/lib/decorate-cli').decorateCli()` to  `require('nx/src/cli/decorate-cli').decorateCli();`

**Comment by alexandrequillacq** [comment]
You can try to uninstall @nrwl/cli and install nx instead:
```
npm uninstall -D @nrwl/cli
npm install -D nx
```
Nx commands are now working for me

**Comment by Greenek** [comment]
I confirm, `nx migrate @nrwl/workspace@13.9.5` fixed the problem, but it must be run with the last working version of Nx installed.

**Comment by meeroslav** [comment]
The cleanest fix currently is to clean the packages during the migration. Follow these steps:
- nx migrate latest
- remove node_modules and lock file (e.g. `rm -rf node_modules package-lock.json`
- install packages (npm install, yarn or pnpm install)
- nx migrate --run-migrations

**Comment by hervehobbes** [comment]
Other solution, use nx in node modules, for examples :
```
.\node_modules\.bin\nx.ps1 dep-graph
.\node_modules\.bin\nx.ps1 build backoffice
```
