### ISSUE TITLE
Installing @nrwl/cli 13.9.3 results in `command not found: nx`

### ISSUE THREAD

**Issue by ComradeCow** [nrwl/nx#9399]
## Current Behavior
Running `npm install -g @nrwl/cli@13.9.3` installs the nx cli packages, but running any `nx` command results in "command not found: nx"

## Expected Behavior
The `nx` command should resolve to the binaries in the `@nrwl/cli` package.

## Steps to Reproduce
```
npm install -g @nrwl/cli@13.9.3

nx --help # this comes back with command not found

npm install -g @nrwl/cli@13.9.2

nx --help # this will show the normal help file.
```

Note - the command still works if you run `npx nx ....`, but not if you use `nx` directly.

### Environment
```
  Node : 16.13.0
  OS   : linux x64
  npm  : 8.3.2

  nx : 13.1.3
  @nrwl/angular : 13.1.3
  @nrwl/cli : 13.1.3
  @nrwl/cypress : 13.1.3
  @nrwl/devkit : 13.1.3
  @nrwl/eslint-plugin-nx : 13.1.3
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.3
  @nrwl/linter : 13.1.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.3
  @nrwl/web : Not Found
  @nrwl/workspace : 13.1.3
  @nrwl/storybook : 13.1.3
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

That's from my local machine. We first saw this in the Azure DevOps `ubuntu-latest` VMs.

**Comment by brianagriffith** [comment]
Began receiving this error in Azure Devops this afternoon as well. Was able to unblock by prefixing the nx commands with npx per the documentation here: https://nx.dev/ci/monorepo-ci-azure

**Comment by FrozenPandaz** [comment]
Can you please install `nx` instead?
```
npm install -g nx@latest
```

**Comment by vire** [comment]
> Sorry we purposely got rid of it because it was conflicting within workspaces.
> 
> Can you please install `nx` instead?
> 
> ```
> npm install -g nx@latest
> ```

Globally installed `nx@latest` does not working in a yarn2+ pnp monorepo, it results into

```
 NX   ERROR  Could not find Nx modules in this workspace.
```

I think the `bin` removal from `@nrwl/cli` was a bit breaking change 😁

**Comment by vire** [comment]
@FrozenPandaz the issue with missing `nrwl/cli` bin can be resolved

```
yarn add -D nx
```

**Comment by hcharley** [comment]
This caught me off guard as well.

**Comment by cdmistman** [comment]
Hi, if the move to the `nx` package can please be referenced in the docs I think it would be greatly appreciated - just spent far too long trying to figure out why `nx: command not found` wasn't working but the only mention of running `npm install -g nx@latest` is this issue!
