### ISSUE TITLE
How to start development mode correctly

### ISSUE THREAD

**Issue by G233** [nrwl/nx#9406]
## Current Behavior

When I want to start package A's development mode, Nx will first start package A's dependency package B's development mode, and then the whole process will be blocked by B's development mode, because B's development mode is a task that will not end (watch).
## Expected Behavior

Start the development mode of package A normally, and compile the product of A and its dependencies, and listen to the file changes of A and its dependencies (watch mode)

**Comment by FrozenPandaz** [comment]
The truth is there is no single way to start a development mode. 

I think the one that you are looking for is using [`@nrwl/web:file-server`](https://nx.dev/packages/web/executors/file-server#nrwlwebfile-server) which runs the build and runs a web-server serving the files from file system.

Does that point you in the right direction?

**Comment by G233** [comment]
but webpack watch model not surport（HMR） ?   Do I need to re-run build every time I change a file?
