### ISSUE TITLE
nx generate @nrwl/js:app [appname] command not available for framework agnostic typescript based application

### ISSUE THREAD

**Issue by dreamerkumar** [nrwl/nx#9411]
## Current Behavior
Get the following error when trying to create a new app in workspace with preset=ts:
npx nx generate @nrwl/js:app app1
Unable to resolve @nrwl/js:app.
Cannot find generator 'app' in [workspace-name]/node_modules/@nrwl/js/generators.json.

 I was able to create a library though.

## Expected Behavior

Expected a typescript application to be created as per the documentation at https://nx.dev/getting-started/nx-and-typescript#create-a-typescript-based-application

Not sure as I tried this for the first time today.

## Steps to Reproduce
Create a new workspace with ts preset
npx create-nx-workspace ast --preset=ts
Try to create a new application. It fails with the above error.
npx nx generate @nrwl/js:app app1

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by AgentEnder** [comment]
Hey @dreamerkumar. We removed the @nrwl/js:app generator since @nrwl/js is only runtime agnostic, and could be used for node or web projects. In turn, we recommend using either @nrwl/node or @nrwl/web when generating your apps.

**Comment by AgentEnder** [comment]
I'm going to leave this open until the above PR is merged, to refer to.

**Comment by leohxj** [comment]
the tutorial video also use @nrwl/js:app, it should be updated, thanks.

**Comment by juristr** [comment]
Done, fixed the video. Thanks @leohxj for pointing it out :)

**Comment by mrmikardo** [comment]
I believe that the docs here are also out of date: https://nx.dev/getting-started/node-tutorial

**Comment by AgentEnder** [comment]
I don't see any references to @nrwl/js:app on that page.

**Comment by MaximSagan** [comment]
> we recommend using either @nrwl/node or @nrwl/web when generating your apps.

@nrwl/web sounds great until you look at the generated code and realize that "web" is short for "web components". Would be good to have an option to build a more basic framework-less web app.
