### ISSUE TITLE
`.gitignore` generated from create-nx-workspace allows nested `node_modules` to be committed

### ISSUE THREAD

**Issue by melanieseltzer** [nrwl/nx#9412]
It's maybe not a bug, per se, but more like a question of whether it's intentional / could be improved?

## Current Behavior
The `.gitignore` that is generated from `create-nx-workspace` has an entry for node_modules like `/node_modules` (note the leading slash). This means that the pattern is scoped to the directory level of the `.gitignore` (only ignores `node_modules` at the same level of the `.gitignore`).

I'm using Nx along with Yarn workspaces, and some nested `node_modules` ended up being committed, i.e. https://github.com/melanieseltzer/toolkit/commit/042d4cea9dbdc4f4c6514538c4f47bd4cbffebdc

Was wondering if the leading slash is intentional, or maybe it would be better not to include it in the generated `.gitignore` to prevent this behavior on accident?

## Expected Behavior
`.gitignore` ignores all `node_modules` regardless of nesting level.

**Comment by FrozenPandaz** [comment]
I agree. There's no reason not to ignore all `node_modules` directories. Would you like to contribute the change?

**Comment by melanieseltzer** [comment]
Great! Yes, I'd be happy to make the change :)
