### ISSUE TITLE
Generate new TS App Error

### ISSUE THREAD

**Issue by Beatr1xK1ddo** [nrwl/nx#9419]
What's up guys!! When I am using nx 13.9.3 and run 
`nx generate @nrwl/js:app demoapp`
i have error with msg:
<img width="851" alt="Screenshot 2022-03-20 at 21 08 19" src="https://user-images.githubusercontent.com/55491741/159192221-6b783457-ba7f-495c-b869-41b87baee8ca.png">
This happened twice on my Mac and Windows PC's. When i run nx 13.8.3 everything works correct and offcourse i ran 
`npx create-nx-workspace happynrwl --preset=ts`
first....

**Comment by AgentEnder** [comment]
Hey, some things changed recently and we removed the @nrwl/js:app generator. You should use either @nrwl/web:app or @nrwl/node:app depending on your use case. For more info see this issue (which will be used to track the docs changes): #9411

**Comment by kkarimi** [comment]
Hi @AgentEnder thanks for the response, although seems documentation hasn't updated. 

Using @nrwl/node:app results in:

```
$ npx nx generate @nrwl/node:app backend
Unable to resolve @nrwl/node:app.
Cannot find module '@nrwl/node/package.json'
Require stack:
- /Volumes/dev/heni/nft_secondary_marketplace/node_modules/nx/src/shared/workspace.js
- /Volumes/dev/heni/nft_secondary_marketplace/node_modules/nx/src/cli/init-local.js
- /Volumes/dev/heni/nft_secondary_marketplace/node_modules/nx/bin/nx.js
```

Is there another command to run to update list of generators?

**Comment by AgentEnder** [comment]
Hey, sorry yeah you'll need to install @nrwl/node.
