### ISSUE TITLE
ng commands not working after migrating from nrwl nx version 12 to 13 for my angular project

### ISSUE THREAD

**Issue by anuLdepot** [nrwl/nx#9428]
ng serve is resulting in the following error

"Cannot determine project or target for command."

My package.json
![image](https://user-images.githubusercontent.com/102036504/159264673-54c8ecda-c501-4453-9dca-9784376c77b5.png)

The "defaultProject" property is missing in angular.json.
The "ng s" command works upon adding "defaultProject" manually to angular.json.
But each time I create a new library using nx console, the angular.json gets over-written and the "defaultProject" gets removed.

**Comment by anuLdepot** [comment]
Hi,

The output for nx report
![image](https://user-images.githubusercontent.com/102036504/159294723-70dfb4d7-c180-40a2-8ea7-141eda14351f.png)

![image](https://user-images.githubusercontent.com/102036504/159294848-c191a430-182f-468d-9d86-0cd2ec05eec2.png)

**Comment by Coly010** [comment]
Hey @anuLdepot  ! Is there a `decorate-cli` file at the root of your workspace? And is there a `postinstall` command in your package.json to execute that file with node?

**Comment by AgentEnder** [comment]
In addition to @Coly010's question, can you try bumping the other packages in your workspace to v13.9.3? Aside from @nrwl/nx-cloud, all @nrwl/* packages and the `nx` package itself should be at the same version. 13.9 changed some internal mechanisms, which could cause issues with mismatched versions.

**Comment by Arghh** [comment]
I have the same problem also with 13.9.3 Version. I have "ng" : "nx" added in package.json but still get the same exception.

**Comment by anuLdepot** [comment]
> In addition to @Coly010's question, can you try bumping the other packages in your workspace to v13.9.3? Aside from @nrwl/nx-cloud, all @nrwl/* packages and the `nx` package itself should be at the same version. 13.9 changed some internal mechanisms, which could cause issues with

**Comment by anuLdepot** [comment]
> Hey @anuLdepot ! Is there a `decorate-cli` file at the root of your workspace? And is there a `postinstall` command in your package.json to execute that file with node?
@Coly010,

There is no decorate-cli file in my workspace. But we have the 'postinstall' command as follows:
 **"postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points",**

**Comment by Coly010** [comment]
@Arghh and @anuLdepot 

As @AgentEnder has mentioned, it looks like you're using a higher version of Nx than your Workspace. Can you run `npx nx mgirate latest` then `npx nx migrate --run-migrations` and see if you still have issues?

**Comment by anuLdepot** [comment]
> @Arghh and @anuLdepot
> 
> As @AgentEnder has mentioned, it looks like you're using a higher version of Nx than your Workspace. Can you run `npx nx mgirate latest` then `npx nx migrate --run-migrations` and see if you still have issues?

@Coly010 , I had migrated to the latest version of nx (13.9.4). Then renamed angular.json as workspace.json. Then the ng serve command worked. But it has the error
"(node:11600) UnhandledPromiseRejectionWarning: Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID"

**Comment by AgentEnder** [comment]
@anuLdepot it sounds like one of the plugins you are using (@ldsm/environment, ngx-build-plus etc) is using an older json schema version that is unsupported. What executor are you using for serve?
