### ISSUE TITLE
Removal of the bin setting breaks nx usage in pnpm

### ISSUE THREAD

**Issue by roderik** [nrwl/nx#9436]
## Current Behavior

13.9.3

<img width="637" alt="CleanShot 2022-03-21 at 17 26 53@2x" src="https://user-images.githubusercontent.com/16780/159305924-742e9627-6c7b-428f-9b85-4d2493de65b2.png">

## Expected Behavior

13.9.2

<img width="1060" alt="CleanShot 2022-03-21 at 17 27 47@2x" src="https://user-images.githubusercontent.com/16780/159306033-7aac4fad-5588-4b15-bc37-178ec34f8cc4.png">

## Steps to Reproduce

Start a new nx project with pnpx, try to create a lib -> fail
downgrade to 13.9.2 -> success

**Comment by roderik** [comment]
no i do not, i did a clean repo + the add nx to monorepo thingy. That installs latest but maybe it is missing there?

**Comment by FrozenPandaz** [comment]
We've added `@nrwl/cli` during the `add-nx-to-monorepo`. Also, please update your global install of `nx` :smile:.

This shouldn't be an issue anymore.
