### ISSUE TITLE
npm ci via nx target does not install peerDependencies

### ISSUE THREAD

**Issue by dsheng3** [nrwl/nx#9439]
## Current Behavior

peerDependencies are not installed into local node_modules. The folder only contains a .package-lock.json

    {
      "name": "@example/simple",
      "version": "0.0.0",
      "lockfileVersion": 2,
      "requires": true,
      "packages": {}
    }

## Expected Behavior

peer dependency is installed. `nx build simple --skip-nx-cache` executes `npm ci` the same way as if it where ran locally on the command line

If this is not a bug, an explanation is much appreciated, as my assumption is, that nx does not change how npm scripts work
"**Nx Core doesn't replace your tools and doesn't change how they work.**" from https://nx.dev/getting-started/nx-core

## Steps to Reproduce

Following the tutorial https://nx.dev/getting-started/nx-core
- `npx create-nx-workspace@latest --preset=core` (no cloud)
- `nx g npm-package simple`
- modify package.json of simple
  - add peer dependency, e.g. react@17.0.2 to package.json in simple
  - add `"build": "npm ci",` to scripts
- npm install in simple package to create package-lock.json
- `nx build simple` or `nx build simple --skip-nx-cache`

nx-examples seems to not us local package.jsons, so here is a patch of the above: [nx_peerDependencies.txt](https://github.com/nrwl/nx/files/8319512/nx_peerDependencies.txt)

### Failure Logs

    nx build simple --skip-nx-cache
    
    > nx run simple:build
    
    > @example/simple@0.0.0 build
    > npm ci
    
    
    up to date, audited 1 package in 490ms
    
    found 0 vulnerabilities
    
        
    >  NX   Successfully ran target build for project simple (3s)

### Environment
   >  NX   Report complete - copy this into the issue template
  
     Node : 16.13.0
     OS   : win32 x64
     npm  : 8.3.1
  
     nx : 13.9.3
     @nrwl/angular : undefined
     @nrwl/cypress : undefined
     @nrwl/detox : undefined
     @nrwl/devkit : 13.9.3
     @nrwl/eslint-plugin-nx : undefined
     @nrwl/express : undefined
     @nrwl/jest : 13.9.3
     @nrwl/js : undefined
     @nrwl/linter : 13.9.3
     @nrwl/nest : undefined
     @nrwl/next : undefined
     @nrwl/node : undefined
     @nrwl/nx-cloud : undefined
     @nrwl/nx-plugin : undefined
     @nrwl/react : undefined
     @nrwl/react-native : undefined
     @nrwl/schematics : undefined
     @nrwl/storybook : undefined
     @nrwl/web : undefined
     @nrwl/workspace : 13.9.3
     typescript : 4.5.5
     rxjs : 6.6.7

     ---------------------------------------
     Community plugins:

**Comment by FrozenPandaz** [comment]
Yup, it's a legitimate bug. We'll look into it. Thank you for reporting the issue.

**Comment by gioragutt** [comment]
@FrozenPandaz perhaps this is related to cwd being set to the project's root?

https://github.com/nrwl/nx/blob/master/packages/workspace/src/executors/run-script/run-script.impl.ts#L26
