### ISSUE TITLE
node-app enable mjs imports

### ISSUE THREAD

**Issue by muradm** [nrwl/nx#944]
## Expected Behavior

When using nrwl for node-app, imported modules can be ES6 modules. Should be able to import either by default out-of-the box (`extensions: ['.ts', '.js', '.mjs']`), or ability to specify extra `extensions` and `loaders` from build options to `node-app` project.

## Current Behavior

Importing ES6 modules fails to build in production mode. For instance this [issue](https://github.com/graphql/graphql-js/issues/1272) happens with `graphql` package. Which obviously can be fixed with [this solution](https://github.com/graphql/graphql-js/issues/1272#issuecomment-393903706).

### Steps to Reproduce

1. create new nrwl workspace
2. add `node-app`
3. import `graphql`
4. attempt to build production version of `node-app`

### Failure Logs

Sample logs in mentioned issue above.

## Other

Similar issue happens with raw `@angular/cli` and not resolved at the moment, which might or might not be reasonable for browser side. For server side there are no restrictions that are applicable for reasoning on browser side.

**Comment by muradm** [comment]
Btw, angular finally [added `mjs`](https://github.com/angular/angular-cli/blob/914f99d75e6c44bd611fac817418132104b8e846/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts#L270) I think.

**Comment by FrozenPandaz** [comment]
Closed with #949
