### ISSUE TITLE
Security issues in dev packages

### ISSUE THREAD

**Issue by 72gm** [nrwl/nx#9455]
## Current Behavior
NPM audit is throwing around 15 high severity vulnerabilities for package minimist

## Expected Behavior
NPM audit throws no high severity vulnerabilities for this nrwl package

I appreciate that these are dev dependencies and doesn't affect Production but there is a v1.26 of minimist, https://github.com/substack/minimist , that should resolve this pretty easily. 

Will also keep my security team happier 

## Steps to Reproduce
Create a NX repo react app then run npm audit. Occurs in 13.9.4

![image](https://user-images.githubusercontent.com/12847881/159479308-2907217a-7547-4e6e-a93b-bc4de9a33788.png)

**Comment by jaysoo** [comment]
This has been resolved  and `npm audit` no longer shows any issues.
