### ISSUE TITLE
VSCode auto-import doesn't use library importPath

### ISSUE THREAD

**Issue by ehaynes99** [nrwl/nx#9465]
## Current Behavior
In a workspace with both apps and libraries, the auto-import in VSCode doesn't attempt to import from libraries by name, but rather the full relative path.

E.g.
```
Auto import from '../../../libs/test-lib-js/src' function testLibJs(): string
```
## Expected Behavior

```
Auto import from '@nx-test/test-lib' function testLib(): string
```

## Steps to Reproduce
* `npx create-nx-workspace@latest nx-test --preset=apps --nx-cloud=false`
* `cd nx-test`
* `npm i -D @nrwl/node`
* `npx nx generate @nrwl/js:library --name=test-lib --testEnvironment=node --no-interactive`
* `npx nx generate @nrwl/node:application --name=test-app --no-interactive`
* Open the project in VSCode
* Open the `apps/test-app/src/main.ts` file in the editor
* Type `testLib`

### Failure Logs
None

### Environment
VSCode Version: 1.59.0
Nx Console v17.14.1

```
$ nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : darwin x64
   npm  : 8.5.0
   
   nx : 13.9.4
   @nrwl/angular : undefined
   @nrwl/cypress : undefined
   @nrwl/detox : undefined
   @nrwl/devkit : 13.9.4
   @nrwl/eslint-plugin-nx : 13.9.4
   @nrwl/express : undefined
   @nrwl/jest : 13.9.4
   @nrwl/js : 13.9.4
   @nrwl/linter : 13.9.4
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : 13.9.4
   @nrwl/nx-cloud : undefined
   @nrwl/nx-plugin : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : undefined
   @nrwl/web : undefined
   @nrwl/workspace : 13.9.4
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

(node:69330) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/ehaynes/workspace/tmp/nx-test/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by FrozenPandaz** [comment]
@Cammisuli Don't we have something in Nx Console that helps with this?

**Comment by Cammisuli** [comment]
Yea Nx Console should update the tsserver process to include all available paths listed in tsconfig.base.ts.

**Comment by Cammisuli** [comment]
It appears to still be working ( I tried it on a GitHub code space )
https://user-images.githubusercontent.com/4332460/160243315-b34bc197-04d6-4dfe-98e3-4f1847aaab26.mov

**Comment by ehaynes99** [comment]
I can't seem to get it working in any project, including the `nx` repo itself. To make sure I've isolated everything, I:
* cloned this repository: https://github.com/ehaynes99/nx-console-import-test.git
* `cd nx-console-import-test`
* `npm install`
* code .
* command pallete -> `Extensions: Disable All Installed Extensions for this Workspace`
* extensions view -> NX Console -> `Enable (Workspace)`
* open `main.ts`
* type `testLib`

I repeated this entire process on both my personal machine running Manjaro, as well as my work Macbook, and the behavior is the same.

![Screen Shot 2022-03-26 at 11 05 02 PM](https://user-images.githubusercontent.com/2187664/160264935-bc2b49dd-6f37-4cbd-89f0-1fc748573cc4.png)

**Comment by Cammisuli** [comment]
if you press enter to accept the suggestion what is actually imported? I’ve seen that particular case happen (where the suggestion shows `../../etc` but actually accepting the suggestion, it corrects the import to the workspace one.

**Comment by ehaynes99** [comment]
It imports the path shown in the dialog. One thing that might be relevant is that the eslint extension does complain about the path, and the quick fix does update it to the import path name. Is it possible you have something that would automatically be applying `eslint --fix` upon import?

If it is supposed to show the import path in the dialog as well, I've tried the additional debugging below, but I'm not familiar enough with the vscode extension api to be sure of what's happening. I.e. it's not really clear to me at what point the actual project name gets mapped. If there is anything additional I can check, I'm happy to do so.

`typescript-plugin#getExternalFiles` returns the following:
```
[
  {
    mainFile: "/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib/src/index.ts",
    directory: "/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib",
  }
]
```
The relevant tsserver log output from `@monodon/typescript-nx-imports-plugin` was:
```
Info 28   [14:51:39.117] NX Imports Plugin: create
Info 29   [14:51:39.117] NX Imports Plugin: setting configuration {"externalFiles":[{"mainFile":"/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib/src/index.ts","directory":"/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib"}],"name":"@monodon/typescript-nx-imports-plugin"}
Info 30   [14:51:39.117] NX Imports Plugin: addProject /Users/ehaynes/workspace/tmp/nx-console-import-test/apps/test-app/tsconfig.json
Info 31   [14:51:39.117] NX Imports Plugin: updating project: /Users/ehaynes/workspace/tmp/nx-console-import-test/apps/test-app/tsconfig.json
Info 32   [14:51:39.117] NX Imports Plugin: get root files: {"externalFiles":[{"mainFile":"/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib/src/index.ts","directory":"/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib"}],"name":"@monodon/typescript-nx-imports-plugin"}
Info 33   [14:51:39.117] NX Imports Plugin: project directory: /Users/ehaynes/workspace/tmp/nx-console-import-test/apps/test-app
Info 34   [14:51:39.117] NX Imports Plugin: root files: ["/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib/src/index.ts"]
Info 35   [14:51:39.117] NX Imports Plugin: decorate
Info 64   [14:51:39.199] NX Imports Plugin: create
Info 65   [14:51:39.199] NX Imports Plugin: setting configuration {"externalFiles":[{"mainFile":"/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib/src/index.ts","directory":"/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib"}],"name":"@monodon/typescript-nx-imports-plugin"}
Info 66   [14:51:39.199] NX Imports Plugin: addProject /Users/ehaynes/workspace/tmp/nx-console-import-test/apps/test-app/tsconfig.app.json
Info 67   [14:51:39.199] NX Imports Plugin: updating project: /Users/ehaynes/workspace/tmp/nx-console-import-test/apps/test-app/tsconfig.app.json
Info 68   [14:51:39.199] NX Imports Plugin: get root files: {"externalFiles":[{"mainFile":"/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib/src/index.ts","directory":"/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib"}],"name":"@monodon/typescript-nx-imports-plugin"}
Info 69   [14:51:39.199] NX Imports Plugin: project directory: /Users/ehaynes/workspace/tmp/nx-console-import-test/apps/test-app
Info 70   [14:51:39.199] NX Imports Plugin: root files: ["/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib/src/index.ts"]
Info 71   [14:51:39.199] NX Imports Plugin: decorate
Info 107  [14:51:40.417] NX Imports Plugin: onConfigurationChanged called, {"externalFiles":[{"mainFile":"/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib/src/index.ts","directory":"/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib"}]}
Info 108  [14:51:40.417] NX Imports Plugin: setting configuration {"externalFiles":[{"mainFile":"/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib/src/index.ts","directory":"/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib"}]}
Info 109  [14:51:40.417] NX Imports Plugin: updating project: /Users/ehaynes/workspace/tmp/nx-console-import-test/apps/test-app/tsconfig.json
Info 110  [14:51:40.417] NX Imports Plugin: get root files: {"externalFiles":[{"mainFile":"/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib/src/index.ts","directory":"/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib"}]}
Info 111  [14:51:40.417] NX Imports Plugin: project directory: /Users/ehaynes/workspace/tmp/nx-console-import-test/apps/test-app
Info 112  [14:51:40.417] NX Imports Plugin: root files: ["/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib/src/index.ts"]
Info 113  [14:51:40.417] NX Imports Plugin: onConfigurationChanged called, {"externalFiles":[{"mainFile":"/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib/src/index.ts","directory":"/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib"}]}
Info 114  [14:51:40.417] NX Imports Plugin: setting configuration {"externalFiles":[{"mainFile":"/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib/src/index.ts","directory":"/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib"}]}
Info 115  [14:51:40.417] NX Imports Plugin: updating project: /Users/ehaynes/workspace/tmp/nx-console-import-test/apps/test-app/tsconfig.app.json
Info 116  [14:51:40.417] NX Imports Plugin: get root files: {"externalFiles":[{"mainFile":"/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib/src/index.ts","directory":"/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib"}]}
Info 117  [14:51:40.417] NX Imports Plugin: project directory: /Users/ehaynes/workspace/tmp/nx-console-import-test/apps/test-app
Info 118  [14:51:40.417] NX Imports Plugin: root files: ["/Users/ehaynes/workspace/tmp/nx-console-import-test/libs/test-lib/src/index.ts"]
```

I ran the nx-console extension in debug mode where I first updated the `@monodon/typescript-nx-imports-plugin` dependency to a local version, which I could verify was working by adding additional logging output. I tried adding logging within the `getCompletionsAtPosition` function in `nx-imports-plugin.ts`, but it never fired:
```diff
       options: ts_module.GetCompletionsAtPositionOptions | undefined
     ) => {
       this.logger?.log(`getCompletionsAtPosition ${fileName}:${position}`);
-      return this.getCompletionsAtPosition(
+      const result = this.getCompletionsAtPosition(
         oldGetCompletionsAtPosition,
         fileName,
         position,
         options
       );
+      this.logger?.log(`completions result: ${result}`);
+      return result;
     };
```

![Screen Shot 2022-03-26 at 11 18 25 PM](https://user-images.githubusercontent.com/2187664/160289008-8019d216-73e5-4dcf-8a08-99757830e97d.png)
![Screen Shot 2022-03-27 at 3 26 31 PM](https://user-images.githubusercontent.com/2187664/160297447-3229773d-3c3b-43ad-8baf-1b200599b5d7.png)

**Comment by Cammisuli** [comment]
We're not doing anything with the completions list for the plugin. The plugin essentially tells the tsserver about additional files outside of the current open ts project, (the ts server will create a new project for each nx project, because of the tsconfigs in each directory). Because we tell the tsserver, hey, include this file, it'll find all the relative imports. This saves us having to manipulate the imports list, and hands all that heavy lifting to the tsserver. 

But I cloned your repository and things are imported properly still 🤔 
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/4332460/160304940-2bcd3ce4-b404-458a-be19-3c9e4001b717.png">

The only thing I can see different between our env's is that I'm using the latest VSCode (1.65.2 at this time), and your OP says 1.59.0. 
<img width="267" alt="image" src="https://user-images.githubusercontent.com/4332460/160305026-af1a9542-0636-40e7-a2ca-672d3ba19b23.png">

Could you try with the latest version of VSCode? I know for a fact that the typescript plugin gets updated with each version of vscode too

**Comment by ehaynes99** [comment]
Ok, finally figured it out. Sorry if you wasted too much time on this...

It's due to the `typescript.preferences.importModuleSpecifier` setting in VSCode. Looks like a bit of a goldilocks solution, as there are 4 options, and 3 of them break this in one way or another:
* `shortest` - :x: coin toss, as it's based on the character count in the `from 'characters';` statement. Surprised this is actually an option, TBH
* `relative` - :x: what I had. It works within the library, but causes the behavior I was seeing in consuming projects
* `non-relative` - :x: inverse of the prior, this works in the consuming project(s), but then not within the same project. A peer file in the library would become e.g. `import { testLib } from 'libs/test-lib/src/lib/test-lib';`. This fails the linter with `Projects cannot be imported by a relative or absolute path, and must begin with a npm scope eslint(@nrwl/nx/enforce-module-boundaries)`. I didn't see any of its [options](@nrwl/nx/enforce-module-boundaries) that looked like it would allow this, but maybe there is one. I like the idea in general, as there aren't confusing levels of `../../../../` everywhere, but is completely dependent on the `baseUrl` setting in tsconfig to work, so I gave up on it years ago.
* `project-relative` - :heavy_check_mark: And we have a winner! It'll use relative imports within the same project, and package imports in the consuming project(s)

**Comment by Cammisuli** [comment]
Ahh! That's right! The project relative setting was added in TypeScript 4.4 or so, and I had that on for the longest time. I had completely forgotten about it. 

Thank you for replying back, now I'll remember to check that setting with others if they come across the same problem 🙂

**Comment by ehaynes99** [comment]
It's actually a VSCode setting, not a tsconfig option. Not sure if you want to get into the business of modifying `.vscode/settings.json` in generated workspaces, but it might be a case where nx should be opinionated by default.

* `@nrwl/jest` and `@nrwl/linter` already create/modify `.vscode/extensions.json` (without asking about IDE of choice, though it's a reasonable assumption with only the one official editor extension)
* The default of `shortest` will probably work out _most_ of the time as package names are usually shorter than relative paths, but it will seem like random breakage when it doesn't.
* The default lint scripts including `--fix` will change it anyway

Note: there is a corresponding `javascript.preferences.importModuleSpecifier` setting for js, which functions in the same way.

**Comment by Shaglock** [comment]
Hello @ehaynes99 thank you for the suggestion, I had similar problem, I needed suggestions to give me 
```ts 
import { something } from '../../../../constants';
```  
and vscode suggestion was always absolute path like 
```ts
import { something } from 'libs/libname/src/lib/constants';
```
which of course brought NX lint error
`Libraries cannot be imported by a relative or absolute path, and must begin with a npm scopeeslint[@nrwl/nx/enforce-module-boundaries]`.

Changing `typescript.preferences.importModuleSpecifier` setting in VSCode to `project-relative` helped me, thank you!

**Comment by jaytavares** [comment]
@ehaynes99 👏 👏 👏 👏 Thank you for finally solving this issue for us. This was so annoying!

**Comment by ehaynes99** [comment]
Now that you bring this issue back to memory, I should amend something I said above:
> It's actually a VSCode setting, not a tsconfig option

_Actually_ it's a [typescript-language-server](https://github.com/typescript-language-server/typescript-language-server) option. VSCode is so tightly integrated with this that it's hard to find the line. Many other editors are taking up the LSP route, though, so E.g. in nvim with lsp-config, you could use:

```lua
init_options = {
  preferences = {
    importModuleSpecifierPreference = 'project-relative',
```
