### ISSUE TITLE
Invalid format version detected when running ng s

### ISSUE THREAD

**Issue by truesensei** [nrwl/nx#9474]
## Current Behavior
When I try to run an ng s inside an app forlder I get the following message: "Unable to read workspace file '...\angular.json': Invalid format version detected - Expected:[ 1 ] Found: [ 2 ]"

## Expected Behavior
The application should be sherved

### Failure Logs
 >  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : win32 x64
   npm  : 8.3.1

   nx : 13.8.2
   @nrwl/angular : 13.9.4
   @nrwl/cypress : 13.9.4
   @nrwl/detox : undefined
   @nrwl/devkit : 13.9.4
   @nrwl/eslint-plugin-nx : 13.9.4
   @nrwl/express : undefined
   @nrwl/jest : 13.9.4
   @nrwl/js : undefined
   @nrwl/linter : 13.9.4
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/nx-plugin : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.9.4
   @nrwl/web : undefined
   @nrwl/workspace : 13.9.4
   typescript : 4.5.5
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
         @ngrx/effects: 12.4.0
         @ngrx/store: 12.4.0
         @ngrx/store-devtools: 12.4.0
         ngx-build-plus: 13.0.1

(node:6000) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at D:\Desarrollo\KUTXABANK\ktf
v2-mf\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by AgentEnder** [comment]
Hey @truesensei! When you run `ng s` using that shorthand instead of `ng serve`, nx doesn't recognize the command and falls back to regular angular CLI ops. Since Angular CLI doesn't know about nor support our workspace schema, this causes the error. Try with `ng serve` or `nx serve`.

Additionally, it looks like your `nx` package is behind the others in terms of version numbers. You may want to update that to be equal.

**Comment by truesensei** [comment]
I have tried both `ng serve` and `nx serve`. With `ng serve` I get the same result :
![image](https://user-images.githubusercontent.com/6338392/159724557-18343b44-5d89-4e27-82ec-b0fe883ce6ae.png)

If I execute `nx serve` i get the following:

![image](https://user-images.githubusercontent.com/6338392/159724836-e8902afb-c2cd-46d6-8175-5e28864d9a98.png)

The thing it is a module federations app, and yesterday it was working like a charm. I could serve each app with the command `ng s` and it worked perfectly. Yesterday installed UUID library from NPM and included in the project and started getting that error.

**Comment by daveksb** [comment]
I also found this error when trying to use 'ng ....' command inside nx project.
Using 'nx ....' command instead fixed the issue for me.
