### ISSUE TITLE
Schema definitions for nx.json and workspace.json

### ISSUE THREAD

**Issue by julianess** [nrwl/nx#9475]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Currently it is not possible for the user to discover the possibilities of settings in nx.json and workspace.json directly inside the own project file neither it is validated while coding.

## Motivation
Today there is no real documentation on what to be set in workspace.json and nx.json and what is optionally possible to be set. A schema (like it is present for angular.json inside pure angular projects) would help the developers to easily figure out which options can be set and how they should look like.

## Suggested Implementation
A file which defines the schema in the same way it is defined for other types of .json config files (like angular did for angular.json) and adding them to the respective file via the "$schema" property inside.

**Comment by AgentEnder** [comment]
Hey @julianess, I'm going to close this issue out in favor of #2299 and #8574. Let me know if you feel there are any pieces which are not covered in those issues.
