### ISSUE TITLE
Wrong generated fileNames with "@nrwl/web:rollup

### ISSUE THREAD

**Issue by Sam10F** [nrwl/nx#9498]
This behaviour happens after install **nrwl/web@19.3.0**, where the release notes specify that web:package have been rename to web:rollup 

## Current Behavior
The generated files are called **index.esm.js** and **index.umd.js** instead of having the name stablished in the package.json of the project.

## Expected Behavior
The generated files before the release **nrwl/web@19.3.0** were named with the name of the project stablished in the package.json (E.g: **projectName.esm.js** and **projectName.umd.js**). This is the expected behaviour. 

## Steps to Reproduce
Install a smaller version of **nrwl/web@19.3.0**, (E.g: nrwl/web@19.2.4) and run a build with next code or similar in the project.json:
```
...
...
"build": {
      "executor": "@nrwl/web:package",
      "outputs": ["{options.outputPath}"],
      "options": {
        "globals": [
          {"global": "_", "moduleId": "lodash"},
          {"global": "axios", "moduleId": "axios"},
        ],
        "outputPath": "dist/libs/projectName",
        "tsConfig": "libs/projectName/tsconfig.json",
        "project": "libs/projectName/package.json",
        "entryFile": "libs/projectName/src/index.ts",
      }
    },
...
...
```
The generated files will be named with the name of the project. (E.g: **projectName.esm.js** and **projectName.umd.js(Expected behaviour)**)

Later, install **nrwl/web@19.3.0** or bigger release a run a build with the next code or similar in the project.json:
```
...
...
"build": {
      "executor": "@nrwl/web:rollup",
      "outputs": ["{options.outputPath}"],
      "options": {
        "globals": [
          {"global": "_", "moduleId": "lodash"},
          {"global": "axios", "moduleId": "axios"},
        ],
        "outputPath": "dist/libs/projectName",
        "tsConfig": "libs/projectName/tsconfig.json",
        "project": "libs/projectName/package.json",
        "entryFile": "libs/projectName/src/index.ts",
      }
    },
...
...
```

The generated files will be named **index.esm.js** and **index.umd.js**.

I've been researching and I don't find any option in [the docs of web:rollup](https://nx.dev/web/package) to set the fileName. I Added the option umdName but does not seems to work... Also, I've tried to extend a rollup config but i didn't manage to change the name of my generated files.

Any help will be appreciated!
Thanks in advance!

**Comment by aLosada7** [comment]
Hi Samuel.

After reproducing the steps mentioned above, I faced the same problem than you.

Fortunately, there is a configuration we can add to our rollup file which solves this problem.

```
const nrwlConfig = require('@nrwl/react/plugins/bundle-rollup');

module.exports = (config) => {
  const nxConfig = nrwlConfig(config);

  return {
    ...nxConfig,
    output: {
      ...nxConfig.output,
      // Modify generated bundle name (lib name instead of entry file)
      entryFileNames: `${nxConfig.output.dir.split('/').pop()}.${
        nxConfig.output.format
      }.js`,
      chunkFileNames: `${nxConfig.output.dir.split('/').pop()}.${
        nxConfig.output.format
      }.js`,
    },
  };
};
```

In this code, we are obtaining the lib name from the output direction and at the same time we have to pass the correct output format. Overriding _entryFileNames_ & _chunkFileNames_ we archieve the desired behaviour.

After doing this, remember to add the configuration to your project.json file.

```
...
...
"build": {
      "executor": "@nrwl/web:package",
      "outputs": ["{options.outputPath}"],
      "options": {
        "globals": [
          {"global": "_", "moduleId": "lodash"},
          {"global": "axios", "moduleId": "axios"},
        ],
        "outputPath": "dist/libs/projectName",
        "tsConfig": "libs/projectName/tsconfig.json",
        "project": "libs/projectName/package.json",
        "entryFile": "libs/projectName/src/index.ts",
         ### "rollupConfig": ["libs/tailor-core/rollup.config.js"]
      }
    },
...
...
```
And that's it.
