### ISSUE TITLE
Full path libs in name 

### ISSUE THREAD

**Issue by bkooistra** [nrwl/nx#950]
[Question]

Hi, I am new to nx workspace but I like it a lot. I am running into something I don't get. When I look at the example repository on github the names of apps and libraries are neat and short. When I create a library in my project and give it a directory, the full path of the library is used as a name. For example, I have the following applications in the following paths: 

- apps/web/love2u-web

- apps/mobile/love2u-mobile

I would like to add a library with shared components, so I decided to add a library with the following command: `ng g lib shared-components --directory=components --prefix=love2u --publishable --tags=components,shared`

The project names which are generated in my angular.json are as follows:
`"projects": {
    "web-love2u-web": {
    },
    "web-love2u-web-e2e": {
    },
    "mobile-love2u-mobile": {
    },
    "mobile-love2u-mobile-e2e": {
    },
    "components-shared-components": {
    },
    "data-access-state-user-state": {
    }
  },`

I am using the latest version of the angular/cli and nrwl/schematics.

**Comment by FrozenPandaz** [comment]
I think the command which might suit you better is the following:

```
ng g lib components --directory=shared --prefix=love2u --publishable --tags=components,shared
```

This would create the following:
```
libs/shared/components
```

**Comment by bkooistra** [comment]
Hey, thanks for your answer. Then I would get a library called shared-components. But I also have a library holding ngrx code for user state management, which sits in deeper nested folder, data-access/state, which would make sense I think. However this translates to a project name called data-access-state-user-state. Importing * from @love2u/data-access-state-user-state seems off. I'd rather see something like @love2u/user-state, ignoring the path.

I don't know what best practices there are or what the common standard is for what I do. I might of course adjust the names by hand, but maybe I am missing something.

**Comment by bkooistra** [comment]
Hey, I just saw #573, #688 and #861. Would --simpleModuleName also ommit the path in the project name?

**Comment by bkooistra** [comment]
Hey, I just had some time to try this out. The module name is nice and short, but the project name still consists of the full directory path. As answer to #686 it is stated that it's a duplicate of #573. However, #686 seems more like the naming of the project instead of the module. The flag --simpleModuleName only effects the module name. Is there also an option for the project name? If not, is it a good idea to reopen issue #686 and add support for this?

**Comment by vsavkin** [comment]
@bkooistra the project name has to contain the directory name. Otherwise, two similarly named projects in two separate directories won't be able to exist in the same workspace. We want to guarantee that project names are unique by consturction.

You can of course rename the project yourself (in angular.json and nx.json), but I don't recommend it.

**Comment by roip890** [comment]
@vsavkin 
I am having the same issue.
I think what he meant is that if he want to organize his library in some sturcture inside his project, like:
a/b/c/d/lib-name
And not have the lib name to be a-b-c-d-lib-name.

There is any option to do this?
