### ISSUE TITLE
The "path" argument must be of type string. Received an instance of Array

### ISSUE THREAD

**Issue by jigsawmegs** [nrwl/nx#9509]
## Current Behavior
Trying to build Android release.
Run works without error
npx nx run <project>:android:prod
Build fails
npx nx build <project> --platform android --key-store-path <path to key> --key-store-password <pwd> --key-store-alias <alias> --key-store-alias-password <alias pwd>
Build results in error
The "path" argument must be of type string. Received an instance of Array
I do notice that the parameters passed into the npx nx build command are repeated twice in the generated nx

iOS works fine

## Expected Behavior
Android build creates apk file

## Steps to Reproduce
Execute npx nx build for Android 

### Failure Logs
![image](https://user-images.githubusercontent.com/1054932/160029135-391439c8-4ce0-4f85-a83b-d0d5eb4039da.png)

### Environment
Node : 16.14.2
   OS   : darwin x64
   npm  : 8.5.0
   
   nx : 13.9.4
   @nrwl/angular : 13.9.4
   @nrwl/cypress : 13.9.4
   @nrwl/detox : undefined
   @nrwl/devkit : 13.9.4
   @nrwl/eslint-plugin-nx : 13.9.4
   @nrwl/express : undefined
   @nrwl/jest : 13.9.4
   @nrwl/js : undefined
   @nrwl/linter : 13.9.4
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/nx-plugin : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.9.4
   @nrwl/web : undefined
   @nrwl/workspace : 13.9.4
   typescript : 4.6.2
   rxjs : 7.5.2
   ---------------------------------------
   Community plugins:
         @alyle/ui: 11.1.1
         @ngx-formly/schematics: 6.0.0-next.7
         ngx-daterangepicker-material: 5.0.1
         @nativescript/nx: 3.0.13

**Comment by FrozenPandaz** [comment]
Could you please provide a repo that exhibits this issue? You might also want to look for issues/ create a new issue here: https://github.com/nativescript/nx which is the repo for the Nativescript Nx Plugin

**Comment by jigsawmegs** [comment]
Yes I will. just happen to be in hospital at the moment. Likely end of next week

Sent from my iPhone




Steve Mcgrath

Office:          (02) 9672 4222
Fax:     (02) 9672 4211
[Jigsaw Technology]<http://www.jigsaw.com.au>


On 26 Mar 2022, at 9:59 am, Jason Jean ***@***.***> wrote:

﻿

Could you please provide a repo that exhibits this issue? You might also want to look for issues/ create a new issue here: https://github.com/nativescript/nx which is the repo for the Nativescript Nx Plugin
