### ISSUE TITLE
Coverage from Test via Jest in CI overlaps

### ISSUE THREAD

**Issue by a88zach** [nrwl/nx#951]
# Prerequisites
* [X] I am running the latest version
* [X] I checked the documentation and found no answer
* [X] I checked to make sure that this issue has not already been filed
* [X] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior
Coverage reports should include coverage for tested app/lib only

## Current Behavior
This only happens when we run the tests in our CI environment (Jenkins).  The coverage tool is picking up files that are not part of the current lib/app.  We have code coverage requirements that must be met in order to pass our status checks and so we need to run all of the test during each build.  I have a feeling it's b/c the way jest starts/stops when running multiple app/lib test when running `ng test` with no specific project

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1l Create a nx workspace with multiple projects containing multiple test in each project.
2. Add a code coverage reporter to the jest.config.js files in each project.
3. Run `ng test` on a build server like Jenkins

**Comment by FrozenPandaz** [comment]
Can you provide a repo showing the issue? I believe the issue is in how you defined the `coverageDirectory`.

Here is the default:
```

  coverageDirectory: '../../coverage/apps/app2/'
```

**Comment by a88zach** [comment]
I'll have to work on getting a repo together that I can share.  The coverageDirectory is set on a per app/lib basis but it mimics the default.  

The interesting part here is that it works correctly about 70% of the time locally, but fails 100% of the time on the build server.  I think jest doesn't exit cleanly between app/lib runs since each test run uses a new jest test runner.

I'll add more information to this ticket as I can, and I'll try to get a repo together showing the issue.

Another interesting note here is that the test seem to run much slower when you have budgets set in the angular.json.  The terminal output will flash messages like in this screenshot below

![screen shot 2018-12-12 at 4 16 50 pm](https://user-images.githubusercontent.com/1724822/49951942-1d677080-fec9-11e8-8f43-7ad86882fcd4.png)

What might be more interesting about this message is that my budgets are set at 2mb and 5mb
```
"budgets": [
              {
                "type": "any",
                "maximumWarning": "2mb",
                "maximumError": "5mb"
              }
            ]
```

**Comment by a88zach** [comment]
Closing this issue as I can only reproduce this issue on a private repo that I'm unable to share.  I'll reopen this if I find the root cause
