### ISSUE TITLE
Buildable library dependencies with single version policy

### ISSUE THREAD

**Issue by jasongerbes** [nrwl/nx#9510]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Improve support for a **single version policy** by adding the option to use a single version number when building a library with the [updateBuildableProjectDepsInPackageJson] option.

## Motivation

Currently, a [buildable library] that uses  the [updateBuildableProjectDepsInPackageJson] option will populate its `peerDependencies` with the version number from their individual `package.json` files. For example:

[updateBuildableProjectDepsInPackageJson]: https://nx.dev/packages/angular/executors/package#updatebuildableprojectdepsinpackagejson
[buildable library]: https://nx.dev/structure/buildable-and-publishable-libraries

### Root

```jsonc
// '/package.json'
{
    "name": "my-app",
    "version": "1.2.3"
}
```

### Lib 1

```jsonc
// '/libs/lib-1/package.json'
{
    "name": "@my-app/lib-1",
    "version": "0.0.1"
}
```

```ts
// '/libs/lib-1/src/index.ts'

export const helloWorld = 'Hello world';
```

### Lib 2

```jsonc
// '/libs/lib-2/package.json'
{
    "name": "@my-app/lib-2",
    "version": "0.0.1"
}
```

```ts
// '/libs/lib-2/src/index.ts'

import { helloWorld } from '@my-app/lib-1';
console.log(helloWorld);
```

### Dist/build output

```jsonc
// '/dist/libs/lib-1/package.json'
{
    "name": "@my-app/lib-1",
    "version": "0.0.1"
}
```

```jsonc
// '/dist/libs/lib-2/package.json'
{
    "name": "@my-app/lib-2",
    "version": "0.0.1",
    "peerDependencies": {
        "@my-app/lib-1": "0.0.1"
    }
}
```

This approach makes it difficult to enforce a **single version policy** as you'll need to manually do one of the following:

- Maintain the `version` across all `package.json` files.
- Modify the `version` and dependency versions in build output before publishing.

## Suggested Implementation

To retain backwards-compatibility, an option to enable this behaviour should be added to the relevant build executors.

Something like:

### buildableProjectDepsVersionStrategy

Type: `string`
Default: `individualVersions`
Accepted values: `individualVersions`, `singleVersion`

I have a couple of ideas about how this could be implemented:

### Use the `version` from the root `package.json` file

You could ignore the `version` in the individual project `package.json` files (e.g. `/libs/lib-1/package.json`), and instead use the `version` from the root `/package.json` file when populating `peerDependencies` using this option.

### Use a template string in the library `package.json` files

As the `version` property of the individual library `package.json` files will be invalid and unused, you could potentially use a template string that is replaced during build time.

For example, when building lib 2 this:

```jsonc
// '/libs/lib-2/package.json'
{
    "name": "@my-app/lib-2",
    "version": "<NX_VERSION>"
}
```

Would become this:

```jsonc
// '/dist/libs/lib-2/package.json'
{
    "name": "@my-app/lib-2",
    "version": "1.2.3",
    "peerDependencies": {
        "@my-app/lib-1": "1.2.3"
    }
}
```

## Alternative Implementation

Instead of using `version` from the root `package.json` file, you could add a property along the lines of `workspaceVersion` to the `nx.json` configuration file.

Rather than using a template string for the version, the `updateBuildableProjectDepsInPackageJson` could automatically use the global version number when adding an internal dependency to a package's package.json file.

**Comment by jasongerbes** [comment]
@FrozenPandaz do you have any thoughts about how this should be implemented?

**Comment by husni1992** [comment]
@jasongerbes  this is much needed. We should have an option to manage versions and node_modules separately for each app.

**Comment by jasongerbes** [comment]
@husni1992 what you’ve described is essentially the opposite of what I’m proposing.

It sounds like what you want is [Lerna](https://lerna.js.org) with [independent versioning](https://lerna.js.org/docs/features/version-and-publish).

**Comment by tan-yaka** [comment]
Has any progress been made on this or has an alternate solution been implemented? I'm looking for the same functionality that has been proposed but can't find it anywhere
