### ISSUE TITLE
affected:lint not finding affected apps and libs to lint

### ISSUE THREAD

**Issue by dereklin** [nrwl/nx#952]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

* [x] I am running the latest version
* [x] I checked the documentation and found no answer
* [x] I checked to make sure that this issue has not already been filed
* [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

affected:lint should identify the affected apps/libs consistently

Please describe the behavior you are expecting

I am trying to run affected:lint to reduce pr build time.  However, sometimes it will identify the affected things correctly, but other times won't.  So essentially it can't be used.

## Current Behavior

sometimes it will identify the affected things correctly, but other times won't.  So essentially it can't be used.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

On a separate note, I was wondering if there could be an affected:libs script so that I can combine that with affected:apps and do my custom ng lint [aProject]

**Comment by FrozenPandaz** [comment]
If you can provide a repo, that would help greatly.

If not, you can look at the following to investigate why these dependencies are not being created.

Running `yarn dep-graph` will produce a visual graph of the dependencies.

Dependencies are created via the following ways:
1. `import {} from '@npmScope/libName/root';`
2. `loadChildren: '@npmScope/libName/root#Module';`
3. implicitDependencies (specified in `nx.json`

**Comment by dereklin** [comment]
@FrozenPandaz 
Thanks for responding.

This is a private repo.

The problem happens in the pr build with jenkins.  The trouble is sometimes it detects the affected apps or libs correctly, but other times doesn't.  And when it doesn't detect the affected apps or libs, the linting passes and the code is merged into master, even when there are violations.

I suspect it's related how the code checkout works in jenkins in the pr build:

```
    scm {
		git {
			remote {
				name('origin')
				url('ssh://git@git.mycom.com/team/project.git')
			}
			branches('origin/pr/master', '*/release/**', '*/bugfix/**')
			extensions {
				wipeOutWorkspace()
				localBranch('$GIT_BRANCH')
				mergeOptions {
					remote('origin')
					branch('master')
					strategy('default')
					fastForwardMode(FastForwardMergeMode.FF)
				}
			}
		}
    }
```

We run this in the pr build:
```
npm run affected:lint -- --base=origin/master --head=HEAD --parallel
```

**Comment by dereklin** [comment]
Tried with affected:apps and affected:libs.  It's the same problem.  I think the problem is with the merge options, it's not able to detect the difference between the current branch and the master branch.

I wonder anyone has used affected:lint in their pr build successfully.  If so, how do you work around the merge options problem.

**Comment by dereklin** [comment]
Since affected:lint is not reliable in my pr build, I am using this script as a workaround.
There is some overhead sometimes, but I am hoping it will save some time in most cases:
```
#!/bin/bash

APPS=$(./node_modules/.bin/nx affected:apps $(git merge-base origin/master HEAD) HEAD)
APPS="${APPS/playground/''}"
LIBS=$(./node_modules/.bin/nx affected:libs $(git merge-base origin/master HEAD) HEAD)
PROJECTS="${APPS} ${LIBS}"

# https://stackoverflow.com/questions/369758/how-to-trim-whitespace-from-a-bash-variable
PROJECTS="$(echo -e "${PROJECTS}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"

if [ -z "$PROJECTS" ]
then
  ./node_modules/.bin/nx lint && npm run affected:lint -- --all --parallel --silent
else
  echo "Linting specific projects: ${PROJECTS}"
  for project in $PROJECTS
  do
    echo "[lint.sh] linting project: ${project}" &
    ng lint ${project} &
  done

  wait
fi
```

**Comment by dereklin** [comment]
Using refs/remotes/origin/master instead of origin/master gives me better results...

As in 
```
apps=$(./node_modules/.bin/nx affected:apps "$(git merge-base refs/remotes/origin/master HEAD)" HEAD)
```

**Comment by vsavkin** [comment]
Sorry for the late reply. Could you provide a repository reproducing the issue?

**Comment by dereklin** [comment]
The repo is private.  I think the problem is because of our internal usage of jenkins and bitbucket.  I'll close the issue.
