### ISSUE TITLE
remove-typescript-plugin migration leaves dead code

### ISSUE THREAD

**Issue by amayer42** [nrwl/nx#9542]
## Current Behavior

When running `nx migrate --run-migrations` with 

```json
{
    "migrations": [
        {
            "cli": "nx",
            "version": "12.8.0-beta.0",
            "description": "Remove Typescript Preprocessor Plugin",
            "factory": "./src/migrations/update-12-8-0/remove-typescript-plugin",
            "package": "@nrwl/cypress",
            "name": "remove-typescript-plugin"
        }
    ]
}
```

as the `migrations.json` file, the migration updates the contents of all cypress `pluginsFile`s to remove the typescript preprocessor

```javascript
const { preprocessTypescript } = require('@nrwl/cypress/plugins/preprocessor');

module.exports = (on, config) => {
    // `on` is used to hook into various events Cypress emits
    // `config` is the resolved Cypress config

    // Preprocess Typescript file using Nx helper
    on('file:preprocessor', preprocessTypescript(config));
};
```

becomes

```javascript
const { preprocessTypescript } = require('@nrwl/cypress/plugins/preprocessor');

module.exports = (on, config) => {
    // `on` is used to hook into various events Cypress emits
    // `config` is the resolved Cypress config
    // Preprocess Typescript file using Nx helper
};
```

## Expected Behavior

The migration does not remove the import of the `preprocessTypescript` function and it does not remove the comment that was previously associated with preprocessing typescript files.

I would expect this to be the resulting output of the migration:

```javascript
module.exports = (on, config) => {
    // `on` is used to hook into various events Cypress emits
    // `config` is the resolved Cypress config
};
```

## Steps to Reproduce

`nx migrate --run-migrations` with the `migrations.json` file specified above.

### Failure Logs

No failures, just unexpected behavior.

### Environment

```
  Node : 14.19.0
  OS   : win32 x64
  npm  : 6.14.16

  nx : Not Found
  @nrwl/angular : 12.10.1
  @nrwl/cli : 12.10.1
  @nrwl/cypress : 12.10.1
  @nrwl/devkit : 12.10.1
  @nrwl/eslint-plugin-nx : 12.10.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.10.1
  @nrwl/linter : 12.10.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.1
  @nrwl/web : Not Found
  @nrwl/workspace : 12.10.1
  @nrwl/storybook : 12.10.1
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by amayer42** [comment]
Expecting the comment to be removed as well feels a bit nit-picky, But I'd argue that since it was previously generated that way, it should be considered removable.

This isn't a major issue, I've manually removed the import and the comment while migrating. I just thought that the migration could be a bit slicker if it removed those for you.

**Comment by FrozenPandaz** [comment]
I agree that this is ideally what would happen.

But it is tough to analyze that. The function isn't empty.. We don't know what other comments are there.

This is a bug that I don't think is worth the effort fixing. You are free to manually update it though. (Or you can search and replace).

Hope you understand.

**Comment by amayer42** [comment]
@FrozenPandaz , I at least understand regarding the comment, but I would think that the migration should at least be removing the dead import. Would updating the migration to do that not be worthwhile?
