### ISSUE TITLE
`@nrwl/next` plugin keeps on installing itself as a dependency

### ISSUE THREAD

**Issue by hubertkuoch** [nrwl/nx#9548]
## Current Behavior

Whenever I run a command involving the `@nrwl/next` plugin, the latter keeps on re-installing itself as a dependency (don't know if it has an impact but I am using `pnpm`).
## Expected Behavior

`@nrwl/next` should stay a dev dependency after being invoked.
## Steps to Reproduce

Simply generate anything (app or lib) with the plugin.

## Misc
Also, two more questions regarding `@nrwl/next` vis-à-vis `@nrwl/react` since those two can generate libraries and also components inside libraries: 
- Should we use one plugin over the other depending on how the parent library was generated or we can safely mix the two commands no matter which plugin was used first to generate the parent library? For example first generate a library with `@nrwl/next:library --name=foo` and then generate a component inside it with `@nrwl/react:component --name=bar  --project=foo`(or the other way around).
-  Also asking because generated libraries have different default config depending on the plugin used (e.g. for `jest` and `babel`) so not sure if using those plugins interchangeably could create any conflict down the road. Should we then keep library framework specific to stay on the safe side? (at least for libs consumed by Next.js app).

Thanks

**Comment by Aleksandern** [comment]
The same for `yarn`

**Comment by hubertkuoch** [comment]
Hi - Any update on why `@nrwl/next` is re-installed as dependency when invoked?
