### ISSUE TITLE
Receiving warning of incorrect peer dependency using angular 7 and nx 7

### ISSUE THREAD

**Issue by vairamsvsjdo** [nrwl/nx#955]
Receiving warning of incorrect peer dependency using angular 7 and nx 7

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

* [ x] I am running the latest version
* [ x] I checked the documentation and found no answer
* [ x] I checked to make sure that this issue has not already been filed
* [ x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior
No warnings and use correct angular version.

## Current Behavior
Received following warning, which seems there is no angular 7 equivalent of nx workspace.

## Failure Information (for bugs)
``` batch
warning karma > log4js > circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
warning " > @ngrx/effects@6.1.0" has incorrect peer dependency "@angular/core@^6.0.0".
warning " > @ngrx/router-store@6.1.0" has incorrect peer dependency "@angular/common@^6.0.0".
warning " > @ngrx/router-store@6.1.0" has incorrect peer dependency "@angular/core@^6.0.0".
warning " > @ngrx/router-store@6.1.0" has incorrect peer dependency "@angular/router@^6.0.0".
warning " > @ngrx/store@6.1.0" has incorrect peer dependency "@angular/core@^6.0.0".
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. npm install -g @angular/cli (received + @angular/cli@7.1.3)
2. npm install -g @nrwl/schematics (received + @nrwl/schematics@7.1.1)
3. create-nx-workspace ngrx06
4.package.json contains incorrect packages for    
``` javascript
 "@ngrx/effects": "6.1.0",
    "@ngrx/router-store": "6.1.0",
    "@ngrx/store": "6.1.0"
```

### Context

Please provide any relevant information about your setup:

* version of Nx used 7.1.1
* version of Angular CLI used 7.1.3
* `angular.json` configuration
``` javascript
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "",
  "projects": {},
  "cli": {
    "warnings": {
      "typescriptMismatch": false,
      "versionMismatch": false
    },
    "defaultCollection": "@nrwl/schematics",
    "packageManager": "npm"
  }
}
````
* version of Angular DevKit used
* 3rd-party libraries and their versions none
* and most importantly - a use-case that fails

1. npm install -g @angular/cli (received + @angular/cli@7.1.3)
2. npm install -g @nrwl/schematics (received + @nrwl/schematics@7.1.1)
3. create-nx-workspace ngrx06

### Failure Logs

``` batch
warning karma > log4js > circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
warning " > @ngrx/effects@6.1.0" has incorrect peer dependency "@angular/core@^6.0.0".
warning " > @ngrx/router-store@6.1.0" has incorrect peer dependency "@angular/common@^6.0.0".
warning " > @ngrx/router-store@6.1.0" has incorrect peer dependency "@angular/core@^6.0.0".
warning " > @ngrx/router-store@6.1.0" has incorrect peer dependency "@angular/router@^6.0.0".
warning " > @ngrx/store@6.1.0" has incorrect peer dependency "@angular/core@^6.0.0".
```

**Comment by markgoho** [comment]
These warnings are related to the ngrx library. They are working on a v7 that will eventually eliminate these warnings, but for now they should be safe to ignore.

**Comment by vairamsvsjdo** [comment]
Does ngrx does not support angular V7.x?
