### ISSUE TITLE
NX custom executor doesn't work well with tsConfig

### ISSUE THREAD

**Issue by MarufSharifi** [nrwl/nx#9550]
## Current Behavior

I created new custom executor to run my cucumber tests, but when I run my test it shows me this error

error TS2307: Cannot find module '@my/lib' or its corresponding type declarations.

**@my/lib** is my local lib and i have it's path in my tsconfig file

it works fine with all my apps and all other files, but when run Cucumber test from inside of my executor it doesn't work, 

## Expected Behavior

I need to use from my local lib data inside of my test file, how can i do that?

**Comment by AgentEnder** [comment]
We have a new way to write custom executors as part of #9116, but it's not released yet. This will be resolved once it's released, since custom executors can just be created as an executor under a workspace plugin.

**Comment by AgentEnder** [comment]
@MarufSharifi I'm going to close this one out now, the advice given on https://github.com/cucumber/cucumber-js/issues/1139 and the community slack should have answered this, but at the end of the day the behavior noted is an issue with how cucumber works, not Nx.
