### ISSUE TITLE
Add another example to setup required variables for Azure Devops

### ISSUE THREAD

**Issue by McGiogen** [nrwl/nx#9556]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[Configuring CI Using Azure Pipelines and Nx](https://nx.dev/ci/monorepo-ci-azure)

### Additional context or description

Current example configuration does not works on Windows Server 2019 Datacenter with Azure Devops 18.181, at least without an ubuntu vm.

Variables' scripts are not evaluated as expected (using for example: `value: $(git rev-parse HEAD~1)`), instead they are threated as a string. From this command `yarn run nx affected:build --parallel=3 --base=$(BASE_SHA)` the result is something like `yarn run nx affected:build --parallel=3 "--base=git" rev-parse "HEAD~1"`.

We solved adding this powershell task:

```yaml
  - task: PowerShell@2
    displayName: 'Generate variables'
    inputs:
      targetType: 'inline'
      script: |
        if ('$(Build.Reason)' -eq 'PullRequest') {
          Write-Host "##vso[task.setvariable variable=NX_BRANCH;]$(System.PullRequest.PullRequestNumber)"
          Write-Host "##vso[task.setvariable variable=TARGET_BRANCH;]$[replace(variables['System.PullRequest.TargetBranch'],'refs/heads/','origin/')]"
          Write-Host "##vso[task.setvariable variable=BASE_SHA;]$(git merge-base $(TARGET_BRANCH) HEAD)"
        } else {
          Write-Host "##vso[task.setvariable variable=NX_BRANCH;]$(Build.SourceBranchName)"
          Write-Host "##vso[task.setvariable variable=BASE_SHA;]$(git rev-parse HEAD~1)"
        }
```

**Comment by heikofritz** [comment]
@McGiogen 

Thanks for that snipped. 
One question: I get this not to work. I Have still the problem as you mentioned with $(TARGET_BRANCH) . And I found out that nested variables did not work on azure devops pipeline, so how did you get it to work?
Can you probably have a look on the hole yml File, maybe there is something special.... 
Thanks !

**Comment by isaacplmann** [comment]
Thanks for providing this information.  If you would like to create a recipe page to add to the docs, I can help you get that merged.  Otherwise, we can leave this in the issues for people to search for.
