### ISSUE TITLE
ng add @angular/pwa fails to register ngsw-worker.js

### ISSUE THREAD

**Issue by stefan-karlsson** [nrwl/nx#956]
## Expected Behavior
Expects the service worker to be registered in my browser.

## Current Behavior

Files is generated as expected by the schema.
![image](https://user-images.githubusercontent.com/25538602/50187150-7d24a800-031d-11e9-99e0-09aa1a705c79.png) 

when running `ng build --prod` service worker files is generated as expected.
![image](https://user-images.githubusercontent.com/25538602/50187399-4bf8a780-031e-11e9-8e22-2bc51e8cf06a.png)

AppModule trys to register the service worker script (tried `/ngsw-worker.js`) `ServiceWorkerModule.register('ngsw-worker.js', { enabled: environment.production })`

Everything seems fine but when i run the `http-server` command:
` http-server -p 8080 -c-1 dist/apps/ecom-web-client` and navigates to the application, no service-worker is registered.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create-nx-workspace myworkspace
2. cd myworkspace
3. ng g app myapp
4. ng add @angular/pwa --project myapp
5. ng build --prod
6. http-server -p 8080 -c-1 dist/apps/myapp

### Context
* @nrwl/schematics": "7.1.1",
* @angular/cli 7.0.1
* @angular-devkit/build-angular": "~0.10.0",
* NodeJs v10.9.0

## Other
If running the `ng add` schematic with a vanilla angular-cli application, the service worker gets registered.

**Comment by mehrad-rafigh** [comment]
Hi @stefan-karlsson 
Could you provide a repo please? I am using nrwl with universal and pwa support for a little side project of mine. I could take a look at it, if you could provide a repo where I could reproduce your problem :)

Cheers

**Comment by stefan-karlsson** [comment]
Ofc, I will try to find some time tomorrow to create a repo.

**Comment by stefan-karlsson** [comment]
The service worker now works, updated angular-cli and nrwl to latest versions.

repo: https://github.com/stefan-karlsson/nrwl-pwa-test

Closing since solved
