### ISSUE TITLE
Error: Cannot find module '../../../.storybook/main'

### ISSUE THREAD

**Issue by Drecula** [nrwl/nx#9571]
## Current Behavior

I am using react/storybook, fresh pull/install of repo, now storybook
does not run and I get a path error.

I logged `process.cwd()` and got `/home/develop/gitRepos/thingi`

If I change to `const rootMain = require('../../../libs/components/.storybook/main.js')`,
it finds main.js, but then I get error `rootMain.stories is not iterable`

Please help me.

Thanks!

## Expected Behavior
I expect this to run. It worked on initial repo setup pull and there have been no code changes to this lib.

## Steps to Reproduce
I cannot reproduce due to the proprietary nature of the code.

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

`> nx run components:storybook --verbose 
Error: Cannot find module '../../../.storybook/main'
Require stack:
- /home/develop/gitRepos/thingi/libs/components/.storybook/main.js
- /home/develop/gitRepos/thingi/node_modules/@storybook/core-common/dist/cjs/utils/interpret-require.js
- /home/develop/gitRepos/thingi/node_modules/@storybook/core-common/dist/cjs/utils/load-custom-presets.js
- /home/develop/gitRepos/thingi/node_modules/@storybook/core-common/dist/cjs/presets.js
- /home/develop/gitRepos/thingi/node_modules/@storybook/core-common/dist/cjs/index.js
- /home/develop/gitRepos/thingi/node_modules/@storybook/core-server/dist/cjs/index.js
- /home/develop/gitRepos/thingi/node_modules/@storybook/core/dist/cjs/server.js
- /home/develop/gitRepos/thingi/node_modules/@storybook/core/server.js
- /home/develop/gitRepos/thingi/node_modules/@nrwl/storybook/src/executors/storybook/storybook.impl.js
- /home/develop/gitRepos/thingi/node_modules/@nrwl/tao/src/shared/workspace.js
- /home/develop/gitRepos/thingi/node_modules/@nrwl/tao/src/commands/run.js
- /home/develop/gitRepos/thingi/node_modules/@nrwl/tao/index.js
- /home/develop/gitRepos/thingi/node_modules/@nrwl/cli/lib/run-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/develop/gitRepos/thingi/libs/components/.storybook/main.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at interopRequireDefault (/home/develop/gitRepos/thingi/node_modules/@storybook/core-common/dist/cjs/utils/interpret-require.js:64:16)
    at serverRequire (/home/develop/gitRepos/thingi/node_modules/@storybook/core-common/dist/cjs/utils/interpret-require.js:101:10)
    at getPreviewBuilder (/home/develop/gitRepos/thingi/node_modules/@storybook/core-server/dist/cjs/utils/get-preview-builder.js:25:55)
    at buildDevStandalone (/home/develop/gitRepos/thingi/node_modules/@storybook/core-server/dist/cjs/build-dev.js:102:71)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
`

### Environment

Node : 14.19.1
  OS   : linux x64
  yarn : 1.22.17
  
  nx : 13.9.5
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.4
  @nrwl/cypress : 13.4.4
  @nrwl/devkit : 13.4.4
  @nrwl/eslint-plugin-nx : 13.4.4
  @nrwl/express : undefined
  @nrwl/jest : 13.4.4
  @nrwl/linter : 13.4.4
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.4.4
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.4
  @nrwl/web : 13.4.4
  @nrwl/workspace : 13.4.4
  @nrwl/storybook : 13.9.5
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:

**Comment by AgentEnder** [comment]
It looks like several NRWL packages are at 13.4.4, while some key ones are at 13.9.X, can you bump the others to match with `nx migrate latest` and retry? Ideally only @nrwl/nx-cloud should be at a different version.

**Comment by guifeliper** [comment]
@AgentEnder I still have the error after migrating to the latest. 

 ```
>  NX   Cannot find module '../../../.storybook/main'

   Require stack:
   - /Users/guilhermereis/www/Work/connect/libs/ui/.storybook/main.js
   - /Users/guilhermereis/www/Work/connect/node_modules/@storybook/core-common/dist/cjs/utils/interpret-require.js
   - /Users/guilhermereis/www/Work/connect/node_modules/@storybook/core-common/dist/cjs/utils/load-custom-presets.js
   - /Users/guilhermereis/www/Work/connect/node_modules/@storybook/core-common/dist/cjs/presets.js
   - /Users/guilhermereis/www/Work/connect/node_modules/@storybook/core-common/dist/cjs/index.js
   - /Users/guilhermereis/www/Work/connect/node_modules/@storybook/core-server/dist/cjs/index.js
   - /Users/guilhermereis/www/Work/connect/node_modules/@nrwl/storybook/src/executors/storybook/storybook.impl.js
   - /Users/guilhermereis/www/Work/connect/node_modules/nx/src/config/workspaces.js
   - /Users/guilhermereis/www/Work/connect/node_modules/nx/src/command-line/run.js
   - /Users/guilhermereis/www/Work/connect/node_modules/nx/bin/run-executor.js
   Pass --verbose to see the stacktrace.

```
```
nx migrate latest
Fetching meta data about packages.
It may take a few minutes.
Fetching nx@14.6.4
Fetching @nrwl/storybook@14.6.4
Fetching @nrwl/next@14.6.4
Fetching @nrwl/react@14.6.4
Fetching @nrwl/linter@14.6.4
Fetching @nrwl/jest@14.6.4
Fetching @nrwl/web@14.6.4
Fetching @nrwl/workspace@14.6.4
Fetching @nrwl/cypress@14.6.4
```

**Comment by obiyoda** [comment]
@guifeliper I just had this problem playing around with nx. I set up a new project and for some reason or another I ended up missing this file  project-root/.storybook/main.js I spun up another nx workspace and it had it in there.

**Comment by tfohlmeister** [comment]
Just had the same problem and wanted to give a hint about why this might happen: If you already have `.storybook` folders (either in the app/lib folder or root) nx is not writing config files to them but ignores them instead.

Those empty folders might be left over from previous installs. For example, I was reverting some test installs with `git revert` which leaves empty folders behind -> Next time I try to setup storybook using `nx generate` no config files are being generated. Simply delete the folders and re-run.
