### ISSUE TITLE
Nx formatFiles does not call prettier getFileInfo with FileInfoOptions

### ISSUE THREAD

**Issue by danjor** [nrwl/nx#9576]
When using Nx generators with a call to formatFiles(tree), this function calls 

prettier.getFileInfo(systemPath)

instead of calling with the second parameter of type FileInfoOptions

prettier.getFileInfo(systemPath, options.fileInfoOptions)

interface FileInfoOptions {
    withNodeModules?: boolean;
    ignorePath?: string;
}

Then, FileInfoOptions in undefined in all nested functions under prettier.getFileInfo.
This cause support.ignored to be always false.

So, we need to have the second parameters called and retrieved from prettierrc, in which option can be defined like this :
"fileInfoOptions": {
    "withNodeModules": false,
    "ignorePath": "./.prettierignore"
  },

https://github.com/nrwl/nx/blob/70492f3939cfab6eae48fcb62f98eecfc9eed117/packages/devkit/src/generators/format-files.ts#L50

**Comment by danjor** [comment]
I just found that there are several format-files.ts.

![image](https://user-images.githubusercontent.com/3473673/160555689-b1fd0ab7-653e-4a4f-afd1-d6188edf92d5.png)

The second parameter is missing in the format-files.ts used by generators
[nx/packages/devkit/src/generators/format-files.ts](https://github.com/nrwl/nx/blob/70492f3939cfab6eae48fcb62f98eecfc9eed117/packages/devkit/src/generators/format-files.ts#L50)

But not in this one which looks ok 
https://github.com/nrwl/nx/blob/70492f3939cfab6eae48fcb62f98eecfc9eed117/packages/workspace/src/utils/rules/format-files.ts#L64

Should we update the first one look like the second one, and have the raw fileInfoOptions in prettierrc 
"withNodeModules": false,
"ignorePath": "./.prettierignore"

Should we update both to have fileInfoOptions attributes nested under fileInfoOptions in prettierrc
"fileInfoOptions": {
   "withNodeModules": false,
   "ignorePath": "./.prettierignore"
},

Should we delete "nx/packages/devkit/src/generators/format-files.ts" and make usage of "nx/packages/workspace/src/utils/rules/format-files.ts" instead ?

**Comment by AgentEnder** [comment]
Hey @danjor, the @nrwl/workspace/src/utils/rules/format-files file is for use in angular style schematics (and isn't super relevant anymore). It's kept around for legacy consumers. Thanks for the PR, it looks mostly good so we should be able to get it merged quickly.
