### ISSUE TITLE
Nx Daemon was not able to compute the project graph.

### ISSUE THREAD

**Issue by projaguar** [nrwl/nx#9581]
>  NX   Nx Daemon was not able to compute the project graph.

   Log file with the error: /Users/projaguar/Projects/project-forme/node_modules/.cache/nx/d/daemon-error.log
   Please file an issue at https://github.com/nrwl/nx
   Nx Daemon is going to be disabled until you run "nx reset".

daemon-error.log
-----------------
Failed to start the Nx Daemon process.
Messages from the log:

More information: /Users/projaguar/Projects/project-forme/node_modules/.cache/nx/d/daemon.log

daemon.log
------------
[NX Daemon Server] - 2022-03-29T10:49:29.776Z - Started listening on: /Users/projaguar/Projects/project-forme/node_modules/.cache/nx/d/d.sock
[NX Daemon Server] - 2022-03-29T10:49:29.787Z - [WATCHER]: Subscribed to changes within: /Users/projaguar/Projects/project-forme

versions
---------
"@nrwl/cli": "13.9.5",
"@nrwl/eslint-plugin-nx": "13.9.5",
"@nrwl/jest": "13.9.5",
"@nrwl/js": "13.9.5",
"@nrwl/linter": "13.9.5",
"@nrwl/react-native": "^13.9.5",
"@nrwl/web": "13.9.5",
"@nrwl/workspace": "13.9.5",

**Comment by julianess** [comment]
I think this is related to #8950 I've pasted my suggestion about the possible issues there.
