### ISSUE TITLE
Nx computational cache not getting generated(custom cache location)

### ISSUE THREAD

**Issue by writam-roy** [nrwl/nx#9589]
## Current Behavior

When I add a custom path for Nx custom cache generatio,I see no nx cache getting generated,though the same was working in a Nx workspace previously and the behaviour was tested.
## Expected Behavior

Nx cache should get generated in a custom location
## Steps to Reproduce

Add this in project.json 
"default": {
      "options": {
        "cacheableOperations": ["build", "test", "lint", "e2e"],
        "cacheDirectory": "/nx-cache/nx"
      }
    }
to make nx cache get generated in a custom folder outside of node modules

Cannot send PR link ,as it is for a private repo,the above steps can be used to reproduce the issue

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

 Node : 14.16.0
   OS   : win32 x64
   yarn : 1.21.1

   nx : 13.5.3
   @nrwl/angular : undefined
   @nrwl/cli : 13.5.3
   @nrwl/cypress : 13.5.3
   @nrwl/detox : undefined
   @nrwl/devkit : 13.5.3
   @nrwl/eslint-plugin-nx : 13.5.3
   @nrwl/express : 12.10.1
   @nrwl/jest : 13.5.3
   @nrwl/js : 13.5.3
   @nrwl/linter : 13.5.3
   @nrwl/nest : 12.10.1
   @nrwl/next : 13.5.3
   @nrwl/node : 13.5.3
   @nrwl/nx-cloud : undefined
   @nrwl/react : 13.5.3
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.5.3
   @nrwl/tao : 13.5.3
   @nrwl/web : 13.5.3
   @nrwl/workspace : 13.5.3
   typescript : 4.3.5
   rxjs : 6.6.7

**Comment by AgentEnder** [comment]
It's possibly unrelated, but can you try the same with all your packages synced up to the latest? Running `nx migrate latest` should suffice. If there are problems getting to the latest, I'd at least recommend running `nx migrate @nrwl/workspace@13.5.3` to get all packages onto the correct version. Currently, node + express are a major version behind, so things may be broken.

**Comment by writam-roy** [comment]
As per your suggestions,I have tried migrating to latest,yet I do not see cache getting generated in the custom location --
Please find the current config @AgentEnder 
  Node : 16.14.2
   OS   : win32 x64
   yarn : 1.21.1

   nx : 13.9.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.9.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.9.5
   @nrwl/eslint-plugin-nx : 13.9.5
   @nrwl/express : 13.9.5
   @nrwl/jest : 13.9.5
   @nrwl/js : 13.9.5
   @nrwl/linter : 13.9.5
   @nrwl/nest : 13.9.5
   @nrwl/next : 13.9.5
   @nrwl/node : 13.9.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.9.5
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.5.3
   @nrwl/web : 13.9.5
   @nrwl/workspace : 13.9.5
   typescript : 4.3.5
   rxjs : 6.6.7
