### ISSUE TITLE
@nrwl/node:node won't resolve tsconfig paths

### ISSUE THREAD

**Issue by aggarwaldev** [nrwl/nx#9596]
## Current Behavior
When trying to import library files like this:

```
import { Module } from '@scope/package/dir/ModuleFile';
```

and start application using `nx serve <app>`

nx throws following error:

`TS2307: Cannot find module '@scope/package/dir/ModuleFile' or its corresponding type declarations.`

Note: I can confirm I have proper paths in tsconfig.base.json

## Expected Behavior
According to Issue#[1223](https://github.com/nrwl/nx/issues/1223) and PR#[1233](https://github.com/nrwl/nx/pull/1233), it should work without any errors as both of the issue and PR is closed and merged.

## Steps to Reproduce

Minimal GH Repo: https://github.com/aggarwaldev/nx_demo

Run the following commands in your terminal.
1. `git clone git@github.com:aggarwaldev/nx_demo.git`
2. `cd nx_demo`
3. `yarn`
4. `nx serve easy`

Optional: Check [tsconfig.base.json](https://github.com/aggarwaldev/nx_demo/blob/6f2fa07f0ec6fb12d255583d8f0f31eb6ce58561/tsconfig.base.json#L20)

### Environment
```
  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : linux x64
   yarn : 3.2.0
   
   nx : 13.9.5
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.9.5
   @nrwl/eslint-plugin-nx : 13.9.5
   @nrwl/express : Not Found
   @nrwl/jest : 13.9.5
   @nrwl/js : 13.9.5
   @nrwl/linter : 13.9.5
   @nrwl/nest : 13.9.5
   @nrwl/next : Not Found
   @nrwl/node : 13.9.5
   @nrwl/nx-cloud : 13.1.6
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 13.9.5
   typescript : 4.6.3
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:
```

**Comment by AgentEnder** [comment]
Hey @aggarwaldev, thanks for the issue report. The issue and PR you linked are quite old, and several things have changed since then. This definitely should still work, so we will be looking into this. Thanks!

**Comment by nartc** [comment]
This is working as expected. You have a typo in `AppModule`
<img width="565" alt="image" src="https://user-images.githubusercontent.com/25516557/168105763-bdede96d-2559-4055-9171-d719c904aa82.png">

**Comment by udnes99** [comment]
Has this been resolved? I am experiencing the same issue.
VSCode seems satisfied and is resolving imports correctly. When building, on the other hand, I get a ts2307 for imports referencing folders within the package (not for the imports that are in the index.ts of the package)

Currently, using these paths in tsconfig.base.json:
```
 "paths": {
      "@backend/kernel/*": ["libs/kernel/src/*"],
      "@backend/kernel": ["libs/kernel/src/index.ts"]
    }
```
