### ISSUE TITLE
export 'ɵɵresetView' (imported as 'i0') was not found in '@angular/core'

### ISSUE THREAD

**Issue by GaneshVersionx** [nrwl/nx#9615]
export 'ɵɵresetView' (imported as 'i0') was not found in '@angular/core'   this error happened  after ng update 12.x to 13.x

**Comment by AgentEnder** [comment]
Hey! Can you run `nx report` and list the output here? You mentioned that you used `ng update`, what was the exact command you ran? In Nx you would generally use `nx migrate`

**Comment by raphibolliger** [comment]
Try to delete the `.angular` folder. After I deleted the folder the build passed normal.
![image](https://user-images.githubusercontent.com/6289764/162577580-89d7b74d-7451-40d0-9e9f-b2eb15f84cf9.png)

**Comment by Vitruvius21** [comment]
> Try to delete the `.angular` folder. After I deleted the folder the build passed normal. ![image](https://user-images.githubusercontent.com/6289764/162577580-89d7b74d-7451-40d0-9e9f-b2eb15f84cf9.png)

This was the only solution, thanks.

**Comment by vukmilanovic** [comment]
> Try to delete the `.angular` folder. After I deleted the folder the build passed normal. ![image](https://user-images.githubusercontent.com/6289764/162577580-89d7b74d-7451-40d0-9e9f-b2eb15f84cf9.png)

I just did it, and problem is not solved yet. If someone has some other solution, please let me know.
Thank you.
