### ISSUE TITLE
npm run affected:build fails with "Unknown option"

### ISSUE THREAD

**Issue by garethrpratt** [nrwl/nx#962]
## Expected Behaviour

I'd appreciate help with this issue, where I'm trying to build apps affected between two git commits.  For an angular 7 app using npm, I would expect the following command:

```npm run affected:build -- master HEAD --configuration=production --prod```

To build affected projects.

## Current Behaviour

nx appears to pass through "HEAD" and "master" as options to the build, causing it to fail with the following output:

```nx affected:build "master" "HEAD" "--configuration=production" "--prod"

Running build for projects:
  project1
With flags: master HEAD --configuration=production --prod=true
Running build for project1
Unknown option: 'master'
Unknown option: 'HEAD'
Running build for affected projects failed.
Failed projects: project1,project2,project3
```

## Failure Information (for bugs)

Note that the following command correctly identifies the affected project, and runs without error:

```npm run affected:apps -- master HEAD --configuration=production --prod```

It's the build itself that fails.

### Steps to Reproduce

Generate Workspace with two apps, create a branch with changes, execute the command:

```
cd c:\temp
create-nx-workspace workspacename --npm-scope=ascope --packageManager=npm
cd workspacename
ng g app project1 --interactive=false
ng g app project2 --interactive=false
git add .
git commit -m 'test'
git checkout -b ANewBranch
echo {} >> c:\temp\workspacename\apps\project1\src\main.ts
git add .
git commit -m 'test2'
npm run affected:build -- master HEAD --configuration=production --prod
```

### Context

Please provide any relevant information about your setup:

* version of Nx used: 7.1.1
* version of Angular CLI used: 7
* version of Angular DevKit used: 0.11.0

### Failure Logs

See current behaviour.

**Comment by BuckyMaler** [comment]
@garethrpratt the build is failing because `master` and `HEAD` aren't valid options to `ng build`. Try `npm run affected:build -- --base=master --head=HEAD --configuration=production --prod`. Your command is simply missing the options `--base` and `--head`, which Nx will use to identify affected apps, and not be passed to `ng build`. For more info you can run `npm run affected:build -- --help`.

**Comment by garethrpratt** [comment]
Thank you @BuckyMaler , yes that worked - my apologies, I'd missed the need for those options.

**Comment by BuckyMaler** [comment]
@garethrpratt no apologies necessary. I'm glad I could help. 😄
