### ISSUE TITLE
Cannot have dashes or underscores in workspace or application names

### ISSUE THREAD

**Issue by justinnoor** [nrwl/nx#9623]
When using underscores or dashes in workspace or application names with the angular-nest plugin the workspace creation fails:

`npx create-nx-workspace --preset=angular-nest`

`CREATE tester-0/nx.json
CREATE tester-0/package.json
CREATE tester-0/README.md
CREATE tester-0/tools/generators/.gitkeep
CREATE tester-0/tools/tsconfig.tools.json
CREATE tester-0/tsconfig.base.json
CREATE tester-0/.editorconfig
CREATE tester-0/.gitignore
CREATE tester-0/.prettierignore
CREATE tester-0/.vscode/extensions.json
CREATE tester-0/angular.json
CREATE tester-0/.prettierrc
CREATE tester-0/decorate-angular-cli.js
CREATE tester-0/apps/.gitkeep
CREATE tester-0/libs/.gitkeep

> tester-0@0.0.0 postinstall
> node ./decorate-angular-cli.js

 >  NX   Angular CLI has been decorated to enable computation caching.

added 662 packages, and audited 663 packages in 17s

56 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
SchematicsException [Error]: Selector (tester-0-root) is invalid.
    at validateHtmlSelector (D:\nx\tester-0\node_modules\@schematics\angular\utility\validation.js:18:15)
    at D:\nx\tester-0\node_modules\@schematics\angular\component\index.js:111:47

Selector (tester-0-root) is invalid.
Workspace creation failed, see above.`

OS version: Windows 10
Vscode version: 1.66.0
Nodejs version: 17.8.0
Nestjs version: 8.2.4
Angular version:
@angular-devkit/architect    0.1201.4 (cli-only)
@angular-devkit/core         12.1.4 (cli-only)
@angular-devkit/schematics   12.1.4 (cli-only)
@schematics/angular          12.1.4 (cli-only)

**Comment by Coly010** [comment]
Hi, thanks for reporting this! 😄 

You cannot create a workspace with a name that contains a number after a dash or underscore, i.e. `-0`, it would need to be something like `-a0` etc. 

As this is a correct error, I'll close this issue. If you need any more help, let me know!!
