### ISSUE TITLE
IDE cannot use root TS config

### ISSUE THREAD

**Issue by Viperwow** [nrwl/nx#9624]
**Problem**:
We all know the main workspace TS config named `tsconfig.base.json`, all the NX generators use this as the main one to derive from, but, unfortunately, **IDE won't** use it and therefore I cannot see where TS type is gonna blow if I'm developing, for example, my own NX plugin.

**Workaround**:
Add `tsconfig.json` that just extends the base one

**Suggestion**:
Rename `tsconfig.base.json` to the `tsconfig.json`

**Comment by VincentThomas06** [comment]
you could do like this:
```jsonc
// tsconfig.json
{
  "extends": "./tsconfig.base.json"
  ...
}
```
