### ISSUE TITLE
NX Update Latest : Getting error  The Init-local performance mark has not been set

### ISSUE THREAD

**Issue by kanwarkakkar** [nrwl/nx#9629]
## Current Behavior
NX 11.x is working fine but when upgrading to 12.x or Latest NX 13.9.5, I am not able to build or test the project. **Getting DOMException [SyntaxError]**

## Expected Behavior
Should be able to build or test the project

## Steps to Reproduce
Updated the project from 11.6.3 to 12.x or latest NX ( Both cases )

### Failure Logs
<img width="702" alt="Capture" src="https://user-images.githubusercontent.com/18175033/161040546-d5835398-38b1-41fa-b014-69c436a3e4e4.PNG">

### Environment
Node : v16.13
NX : 13.9.5

**Comment by AgentEnder** [comment]
Hey @kanwarkakkar, can you post the versions of all @nrwl packages as well as the `nx` package itself?

**Comment by AgentEnder** [comment]
That @nrwl/cli version is really, really out of date at v10.4.15, it should be updated to match the others at 13.9.5.

After that, if its still not working we can try to dig in further.

**Comment by kanwarkakkar** [comment]
Yes, @nrwl/cli was out of date, Thanks for the info.
