### ISSUE TITLE
please support bazel after angular 7.2.0 release

### ISSUE THREAD

**Issue by Jimmysh** [nrwl/nx#963]
https://github.com/angular/angular/pull/27784

My projects getting bigger and slower to build

**Comment by markgoho** [comment]
@Jimmysh from what I can ascertain there are still a lot of issues with bazel that need to be worked out, not least among them, it doesn't work on Windows.

**Comment by dereklin** [comment]
How much time is slow in your case?

I have been dealing with slow builds.  My current strategy is to run everything in parallel when possible.  For example, test, lint, and build can be run in parallel in pr builds.  Use affected to lint, test, and build only the affected projects.

If you are not doing that already, that will improve your build speed.

However, if you are looking for sub-minute build speed, then maybe only bazel can help.

**Comment by Jimmysh** [comment]
@markgoho Angular projects run on bazel, so it's not hard to fix.

@dereklin  run ng serve  time: 87282ms  bazel need easier to install and use.I'm trying use it now.

**Comment by vsavkin** [comment]
We are working with Alex E from the Angular team. The moment the Bazel story is good enough, we are going to incorporate it into Nx.
