### ISSUE TITLE
`nx run-many --target=lint --all` doesnt check linting rules for a fresh nx workspace

### ISSUE THREAD

**Issue by mondo192** [nrwl/nx#9638]
## Current Behavior

Running the command `yarn nx run-many --target=lint --projects=spa --skip-nx-cache` doesn't catch lint errors/warnings. Instead running the command `yarn nx run spa:lint --skip-nx-cache` properly catches the lint issues.  

## Expected Behavior

Running the command `yarn nx run-many --target=lint --all` should lint all projects in the repo.

## Steps to Reproduce

https://github.com/mondo192/nx-workspace

1. Clone the repo above
2. yarn install etc.
3. run the two linter commands above
4. They dont behave the same 

### Environment

```

   Node : 16.14.2
   OS   : linux x64
   yarn : 3.2.0
   
   nx : 13.9.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.9.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.9.5
   @nrwl/eslint-plugin-nx : 13.9.5
   @nrwl/express : Not Found
   @nrwl/jest : 13.9.5
   @nrwl/js : 13.9.5
   @nrwl/linter : 13.9.5
   @nrwl/nest : 13.9.5
   @nrwl/next : Not Found
   @nrwl/node : 13.9.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.9.5
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.9.5
   @nrwl/web : 13.9.5
   @nrwl/workspace : 13.9.5
   typescript : 4.5.5
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:
```

**Comment by mondo192** [comment]
bump

**Comment by mondo192** [comment]
Any updates on this?

**Comment by meeroslav** [comment]
Sorry for waiting, I will get to this as soon as possible.

**Comment by meeroslav** [comment]
Actually, this is a feature, not a bug.

Nx commands that (potentially) run target on multiple projects (such as `affected` or `run-many`) now by default run in the compact view. For `linter`, this means that warnings are hidden. If you would run the same command with `--verbose` you would achieve the same result:

```bash
yarn nx run-many --target=lint --projects=spa --skip-nx-cache --verbose
```

> Please note that this refers only to warnings. In case of error, your report would exit the compact view and show the full error message.

**Comment by ashhadsheikh** [comment]
> Actually, this is a feature, not a bug.
> 
> Nx commands that (potentially) run target on multiple projects (such as `affected` or `run-many`) now by default run in the compact view. For `linter`, this means that warnings are hidden. If you would run the same command with `--verbose` you would achieve the same result:
> 
> ```shell
> yarn nx run-many --target=lint --projects=spa --skip-nx-cache --verbose
> ```
> 
> > Please note that this refers only to warnings. In case of error, your report would exit the compact view and show the full error message.
> 
> ![Screenshot 2022-05-05 at 15 41 53](https://user-images.githubusercontent.com/881612/166936049-e95f3c51-b8c4-4d01-a3a8-76394878de5b.png)

+1, it worked!

**Comment by meeroslav** [comment]
@ElvenSpellmaker this is not a workaround nor it influences the caching.

Caching is done per command, so when you add `--verbose` you are changing the command. If you would run it again you would see that the result is cached (if run was successful). The only speed difference you might see is the amount of time it takes to print our all the logs vs compact one.
