### ISSUE TITLE
@nrwl/nx-cloud@13.2.1 has a hard dependency on rxjs@6.5.5

### ISSUE THREAD

**Issue by samvloeberghs** [nrwl/nx#9644]
```
$ node -v && npm -v 
v16.14.2
8.5.0
```

I upgraded to `"rxjs": "^7.5.5",` and doing `npm i` fails because of this.

## Current Behavior

`npm i` fails

## Expected Behavior

I would expect `npm i` to work.
This would mean nx-cloud would accept both rxjs 6 and 7 as peer dependency?

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

```
$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: xxx@0.0.0
npm ERR! Found: rxjs@7.5.5
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"^7.5.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"6.5.5" from @nrwl/nx-cloud@13.2.1
npm ERR! node_modules/@nrwl/nx-cloud
npm ERR!   @nrwl/nx-cloud@"13.2.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/xxx/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/samvloeberghs/.npm/_logs/2022-04-01T07_14_53_761Z-debug-0.log
```

### Environment

```
$ npx nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : darwin arm64
   npm  : 6.14.16
   
   nx : 13.9.5
   @nrwl/angular : 13.9.5
   @nrwl/cypress : 13.9.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.9.5
   @nrwl/eslint-plugin-nx : 13.9.5
   @nrwl/express : Not Found
   @nrwl/jest : 13.9.5
   @nrwl/js : 13.9.5
   @nrwl/linter : 13.9.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 13.9.5
   @nrwl/nx-cloud : 13.2.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.9.5
   @nrwl/web : Not Found
   @nrwl/workspace : 13.9.5
   typescript : 4.5.5
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:
   	 ngx-bootstrap: 8.0.0
   	 @storybook/angular: 6.4.20

(node:22255) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/samvloeberghs/Projects/Kwerri/kor-financial/kor-frontend/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by JamesHenry** [comment]
Thanks @samvloeberghs, Victor just released `13.2.2` which should hopefully resolve the issue

**Comment by innoveltec** [comment]
Having the same issue. Changed the @nrwl/nx-cloud to v13.0.0 to make the npm install succeeding.

  NX   Report complete - copy this into the issue template

   Node : 16.13.1
   OS   : win32 x64
   npm  : 8.1.2

   nx : 13.9.5
   @nrwl/angular : 13.9.5
   @nrwl/cypress : 13.9.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.9.5
   @nrwl/eslint-plugin-nx : 13.9.5
   @nrwl/express : Not Found
   @nrwl/jest : 13.9.5
   @nrwl/js : Not Found
   @nrwl/linter : 13.9.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 13.0.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.9.5
   @nrwl/web : Not Found
   @nrwl/workspace : 13.9.5
   typescript : 4.5.5
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:
         ngx-bootstrap: 8.0.0
         @storybook/angular: 6.4.20

**Comment by innoveltec** [comment]
changing the @nrwl/nx-cloud to v13.2.2 also fixes the failing npm install for me
