### ISSUE TITLE
Website is incredibly slow on Firefox

### ISSUE THREAD

**Issue by davidrhoderick** [nrwl/nx#9646]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

[The homepage renders very slowly on Firefox.](https://nx.dev)  I've suggested NX to my team as a possible solution but I feel like if they see the website's performance, they'll think that the product is not worthy.  Lerna's site loads in a second and Bit's doesn't have the same issues.

### Additional context or description

Operating system is Pop!_OS 21.10, Firefox version 98.0.2.  My computer has an AMD 4750G processor and 64GB RAM.

**Comment by bcabanes** [comment]
Thank you for your issue @davidrhoderick! 
A fix is on its way and will be released to production soon 👍
