### ISSUE TITLE
ng add @nrwl/workspace -> Cannot find undefined

### ISSUE THREAD

**Issue by EnricoVogt** [nrwl/nx#9647]
# Transforming an angular workspace to nx:

## Current Behavior
`ng add @nrwl/workspace` stops with meaningless error:

Console output
❯ ng add @nrwl/workspace --verbose
ℹ Using package manager: npm
⠋ Searching for compatible package version...Locating potential npmrc files:
✔ Found compatible package version: @nrwl/workspace@13.9.5.
✔ Package information loaded.

The package @nrwl/workspace@13.9.5 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.
**Cannot find undefined**

## Expected Behavior
Should setup workspace correctly

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Could you provide a minimal repo where this issue can be reproduced? Unfortunately, the error thrown doesn't give much for us to troubleshoot this issue.

**Comment by EnricoVogt** [comment]
This happens in a organisation project, i can't share. I will try to provide a reproduceable example with a sample application.
