### ISSUE TITLE
Nx extremely slow in a large monorepo (>500k files) due to globbing of `**/project.json`

### ISSUE THREAD

**Issue by elado** [nrwl/nx#9660]
## Current Behavior

I'm trying to integrate nx in an existing large monorepo (>500k files), but it only has ~25 workspaces.
When nx initializes, it tries to get the list of workspaces by globbing both `**/project.json` and all the `workspaces` items from `package.json`:

https://github.com/nrwl/nx/blob/428106f6be641757bba42376cdd689425b6461d9/packages/nx/src/config/workspaces.ts#L497-L500

This `**/project.json` forces the glob to crawl every file, and that takes 20-40s in my case, just the init phase of every command.

Dropping `**/project.json` from the glob makes the glob operation instantaneous.
A fix would be to have something similar to `getGlobPatternsFromPackageManagerWorkspaces` that only reads package path entries from package.json workspaces instead, and appends `project.json`.

https://github.com/nrwl/nx/blob/428106f6be641757bba42376cdd689425b6461d9/packages/nx/src/config/workspaces.ts#L471-L484

## Expected Behavior

To have a faster nx boot time.

## Steps to Reproduce

Any repo with hundreds of thousands of files should show the slowness.

### Environment

```
 >  NX   Report complete - copy this into the issue template

   Node : 17.7.2
   OS   : darwin arm64
   yarn : 3.1.1
   
   nx : 13.9.6
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.9.6
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 13.9.6
   @nrwl/js : Not Found
   @nrwl/linter : 13.9.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 13.9.6
   typescript : 4.2.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by B1Z1** [comment]
I hope it will be solved because I'm migrating a project with a huge count of modules into Nx and I don't want to have problems with it :c

**Comment by elado** [comment]
Reopen

**Comment by elado** [comment]
Reopened at https://github.com/nrwl/nx/issues/13637
