### ISSUE TITLE
broken cache: nx cli appears to exit early and doesn't wait for any task to actually run

### ISSUE THREAD

**Issue by NullVoxPopuli** [nrwl/nx#9661]
## Current Behavior
```
$ yarn nx run <my-app>:_start

 >  NX   Running target _start for project <my-app> and 15 task(s) it depends on

 —————————————————
:sparkles:  Done in 7.29s.
```

It _appears as if_ something is not getting `await`ed, and the cli command is finishing before any of the tasks even start.

## Expected Behavior
the 15 tasks run, and then `_start` runs on `<my-app>`

## Steps to Reproduce
I have no idea how to reproduce this, as it is inconsistent based on machine? (sorta?)
- for some folks, doing `git clean -Xfd` first resolved the issue
- for some folks deleting node_modules and re-running yarn (`@v1`) resolves the issue
- for some folks, the nx command (shown above) only works in a new worktree (or fresh clone)
    - this leads me to believe there is _something_ about the repo that `git clean -Xfd`
      isn't finding -- like state is kept outside the monorepo and cached based on path-on-disk to the monorepo (which is maybe why a worktree or separate git clone works)
      
What's weirder, we (debugging with a co-worker) can delete _all but one_ dependency from `<my-app>` and then delete _all_ dependencies in that one package. So, I would _expect_ there to be 1 task to run, something like:
```
 >  NX   Running target _start for project <my-app> and 1 task(s) it depends on
 ```
 _however_, this is not the case. The message is the same. nx still thinks there are 15 task(s).
 
 So then we delete the `<repo root>/node_modules/.cache` directory, and re-run the nx command.
 We _still_ see that nx thinks there are 15 task(s) to run (we expect only one, because we deleted a bunch of stuff).
 

---------------------------------

After some debugging, we found that the project graph doesn't care about package.json, and instead analyzes all source files.

--------------------

 <details><summary>
 
`nx.json`

 </summary>
 
 ```
 {
  "extends": "@nrwl/workspace/presets/npm.json",
  "npmScope": "<my-monorepo>",
  "tasksRunnerOptions": {
    "default": {
      "runner": "@nrwl/workspace/tasks-runners/default",
      "options": {
        "parallel": true,
        "cacheableOperations": [
          "_build"
        ]
      }
    }
  },
  "targetDependencies": {
    "_build": [
      {
        "target": "_build",
        "projects": "dependencies"
      }
    ],
    "_start": [
      {
        "target": "_build",
        "projects": "dependencies"
      }
    ],
    "_test": [
      {
        "target": "_build",
        "projects": "dependencies"
      }
    ]
  }
}
 ```
 
 </details>
 
### Failure Logs
There are no failure logs that I'm aware of. No errors, just :sparkles: Done.

### Environment
```
 >  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : darwin x64
   npm  : 8.5.0
   
   nx : 13.9.6
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.9.6
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 13.9.6
   @nrwl/js : Not Found
   @nrwl/linter : 13.9.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 13.9.6
   typescript : 4.5.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

Done in 1.82s.
```

**Comment by msabramo** [comment]
Sounds like the same issue as #2219 (closed; never solved)?

**Comment by msabramo** [comment]
I am running into this same issue. My builds work fine on my Mac laptop, but when I try to run them on a Ubuntu 20.04.02 Linux VM for CI, the build command does nothing and exits with a 0 and no output:

```
$ npx nx build backdrop
$ echo $?
0
```

I've added some `console.log` statements to `node_modules/@nrwl/workspace/src/command-line/run-one.js` and it seems to not get past this line in the `runOne` function:

```js
const projectGraph = yield project_graph_1.createProjectGraphAsync();
```

In more detail, here's the modified code I have:

```js
        yield connect_to_nx_cloud_1.connectToNxCloudUsingScan(nxArgs.scan);
            console.log('*** About to call project_graph_1.createProjectGraphAsync()');
        const projectGraph = yield project_graph_1.createProjectGraphAsync();
            console.log('*** project_graph_1.createProjectGraphAsync() returned projectGraph = ', projectGraph);
        const { projects, projectsMap } = getProjects(projectGraph, opts.project);
```

and the output with this code:

```
$ npx nx build backdrop
*** About to call project_graph_1.createProjectGraphAsync()
```

Digging in further, if I update `node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js` as follows:

```js
function createProjectGraphAsync(projectGraphVersion = '5.0') {
    return tslib_1.__awaiter(this, void 0, void 0, function* () {
        /**
         * Using the daemon is currently an undocumented, opt-in feature while we build out its capabilities.
         * If the environment variable is not set to true, fallback to using the existing in-process logic.
         */
console.log('*** I am in createProjectGraphAsync - 1');
        if (process.env.NX_DAEMON !== 'true') {
console.log('*** I am in createProjectGraphAsync - 2');
            return projectGraphAdapter('5.0', projectGraphVersion, yield build_project_graph_1.buildProjectGraph());
        }
console.log('*** I am in createProjectGraphAsync - 3');
        const daemonClient = require('./daemon/client/client');
console.log('*** I am in createProjectGraphAsync - 4');
        if (!(yield daemonClient.isServerAvailable())) {
console.log('*** I am in createProjectGraphAsync - 5');
            yield daemonClient.startInBackground();
        }
console.log('*** I am in createProjectGraphAsync - 6');
        return projectGraphAdapter('5.0', projectGraphVersion, daemonClient.getProjectGraphFromServer());
    });
}
```

then I get this output:

```
jenkins@or1010051147177:/apps/slave/workspace/lied-ml_sail-ui_ethos-k8s-deploy$ npx nx build backdrop
*** About to call project_graph_1.createProjectGraphAsync()
*** I am in createProjectGraphAsync - 1
*** I am in createProjectGraphAsync - 2
```

so that suggests that the problem occurs while executing this line:

```
return projectGraphAdapter('5.0', projectGraphVersion, yield build_project_graph_1.buildProjectGraph());
```

Even more specifically, I can break the code down a bit to figure out whether the problem is in `buildProjectGraph` or `projectGraphAdapter`:

```js
        if (process.env.NX_DAEMON !== 'true') {
console.log('*** I am in createProjectGraphAsync - 2');
                const projectGraphForDebugging = yield build_project_graph_1.buildProjectGraph();
console.log('*** I am in createProjectGraphAsync - 2.5 - projectGraphForDebugging = ', projectGraphForDebugging);
            return projectGraphAdapter('5.0', projectGraphVersion, yield build_project_graph_1.buildProjectGraph());
        }
```

and the result is:

```
$ npx nx build backdrop
*** About to call project_graph_1.createProjectGraphAsync()
*** I am in createProjectGraphAsync - 1
*** I am in createProjectGraphAsync - 2
```

so I think the problem is when calling `build_project_graph_1.buildProjectGraph()`.

**Comment by msabramo** [comment]
I think I found the problem, at least in my case and will send a PR with a fix shortly.

If I modify `buildExplicitDependenciesUsingWorkers` in `node_modules/@nrwl/workspace/src/core/project-graph/build-project-graph.js` to add `console.log`s as follows:

```js
function buildExplicitDependenciesUsingWorkers(ctx, totalNumOfFilesToProcess, builder) {
    const numberOfWorkers = os.cpus().length - 1;
console.log('*** I am in buildExplicitDependenciesUsingWorkers - os.cpus().length = ', os.cpus().length);
console.log('*** I am in buildExplicitDependenciesUsingWorkers - numberOfWorkers = ', numberOfWorkers);
    const bins = splitFilesIntoBins(ctx, totalNumOfFilesToProcess, numberOfWorkers);
// console.log('*** I am in buildExplicitDependenciesUsingWorkers - bins.length = ', bins.length);
    const workers = createWorkerPool(numberOfWorkers);
console.log('*** I am in buildExplicitDependenciesUsingWorkers - workers.length = ', workers.length);
    let numberOfExpectedResponses = bins.length;
```

Here is the output:

```
$ npx nx build backdrop --skip-nx-cache
*** I am in buildExplicitDependenciesUsingWorkers - os.cpus().length =  1
*** I am in buildExplicitDependenciesUsingWorkers - numberOfWorkers =  0
*** I am in buildExplicitDependenciesUsingWorkers - bins.length =  1
*** I am in buildExplicitDependenciesUsingWorkers - workers.length =  0
```

Note that I have 1 CPU (this is confirmed with the `nproc` Linux command) and that this causes `numberOfWorkers` to be **zero**.

**Comment by msabramo** [comment]
Oh darn - it looks like I don't have the latest version of Nx -- I have 13.0.2. It looks like this might've already been fixed somewhere along the way.
