### ISSUE TITLE
Non hermetic builds

### ISSUE THREAD

**Issue by joshribakoff-sm** [nrwl/nx#9662]
## Scenario A

This works as expected

Targets:
```json
"build": {
      "executor": "@nrwl/node:build",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/apps/api",
        "main": "apps/api/src/main.ts",
        "tsConfig": "apps/api/tsconfig.app.json",
        "assets": [
          "apps/api/src/assets"
        ]
      },
      "configurations": {
        "production": {
          "optimization": true,
          "extractLicenses": true,
          "inspect": false,
          "fileReplacements": [
            {
              "replace": "apps/api/src/environments/environment.ts",
              "with": "apps/api/src/environments/environment.prod.ts"
            }
          ]
        }
      }
    },
```

Command I ran
```
rm -fr node_modules/.cache/nx
rm -fr dist
npx nx build api
cat dist/apps/api/main.js # not minified
npx nx build api --prod
cat dist/apps/api/main.js # minified
npx nx build api
cat dist/apps/api/main.js # not minified
```

## Scenario B

Now I rename `build`  to `base-build`, and create a new `build` that calls it

Targets:
```json
"build": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "commands": ["npx nx codegen api", "nx base-build api --prod"],
        "parallel": false
      }
    },
"base-build": {
      "executor": "@nrwl/node:build",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/apps/api",
        "main": "apps/api/src/main.ts",
        "tsConfig": "apps/api/tsconfig.app.json",
        "assets": [
          "apps/api/src/assets"
        ]
      },
      "configurations": {
        "production": {
          "optimization": true,
          "extractLicenses": true,
          "inspect": false,
          "fileReplacements": [
            {
              "replace": "apps/api/src/environments/environment.ts",
              "with": "apps/api/src/environments/environment.prod.ts"
            }
          ]
        }
      }
    },
```

In targets, I edited:
```
"commands": ["npx nx codegen api", "nx base-build api --prod"],
```
to:
```
"commands": ["npx nx codegen api", "nx base-build api"],
```

After editing it back and forth a few times and recompiling after each step, the build is no longer hermetic like in "Scenario A". It takes a few times before the bug is replicated. First I do a prod build, then a non prod build, then a prod build.

Nx outputs:

```
 Nx read the output from the cache instead of running the command for 1 out of 1 tasks.
```

However my `dist/app/api/main.js` now contains development code, and I'm running the command with `--prod`.

### Environment
```
 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : darwin x64
   npm  : 8.1.2
   
   nx : 13.7.1
   @nrwl/angular : undefined
   @nrwl/cli : 13.7.1
   @nrwl/cypress : 13.7.1
   @nrwl/detox : undefined
   @nrwl/devkit : 13.7.1
   @nrwl/eslint-plugin-nx : 13.7.1
   @nrwl/express : 13.8.3
   @nrwl/jest : 13.7.1
   @nrwl/js : 13.7.1
   @nrwl/linter : 13.7.1
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : 13.7.1
   @nrwl/nx-cloud : undefined
   @nrwl/react : 13.7.1
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.3
   @nrwl/tao : 13.7.1
   @nrwl/web : 13.7.1
   @nrwl/workspace : 13.7.1
   typescript : 4.4.4
   rxjs : 7.5.4
   ---------------------------------------
   Community plugins:
         @nx-tools/nx-docker: 2.3.0
```

**Comment by AgentEnder** [comment]
Hey @joshribakoff-sm , it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

**Comment by joshribakoff-sm** [comment]
I ran that command, all it did was add a blank line 😆 

```
npx nx migrate 13.7.1
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@13.7.1

>  NX  The migrate command has run successfully.

- package.json has been updated
- there are no migrations to run, so migrations.json has not been created.

>  NX  Next steps:

- Make sure package.json changes make sense and then run 'npm install'
- To learn more go to https://nx.dev/using-nx/updating-nx
- You may run "nx connect-to-nx-cloud" to get faster builds, GitHub integration, and more. Check out https://nx.app
```

![Screen Shot 2022-04-06 at 12 04 24 PM](https://user-images.githubusercontent.com/97546767/162049646-0925f240-8d2f-4dab-9c59-1d40002234c0.png)

**Comment by AgentEnder** [comment]
Ah, that's probably since 13.7.1 is the lower of the 2 versions. Either try again with 13.8.3 or `latest` (which would be 13.9.X as of now), or just bump them down. I'd personally recommend latest, since nothing should've broke in that interval and you may get some extra bug fixes.

**Comment by joshribakoff-sm** [comment]
I got it all upgraded, and the issue still occurs

**Comment by AgentEnder** [comment]
Hey @joshribakoff-sm! Getting back to this now, it looks like it may need to have `outputs` specified on the build target. What is likely happening is the following:
- Nx builds --prod (cache miss, stores cache of console logs only w/o having file artifacts since no outputs is specified)
- Nx builds (cache miss, no prod, stores output of console logs only)
- Nx builds --prod (cache hit, nx replays terminal output, but doesn't touch FS artifacts since none are specified)

**Comment by joshribakoff-sm** [comment]
It's in there. Maybe the issue is related to me renaming `build` to `base-build`? This was necessary to run some codegen command(s) for when the app is build/serve

![Screen Shot 2022-05-04 at 3 11 08 PM](https://user-images.githubusercontent.com/97546767/166833908-ae3ab8ad-80e5-4a78-8dbc-bb3ed11b15e8.png)

**Comment by joshribakoff-sm** [comment]
Oh I see you can also add it here https://nx.dev/packages/workspace/executors/run-commands#outputpath 

Right now those docs say it just affects Nx cloud. I guess it also affects whether your build will be hermetic when running it locally, is what you're suggesting?

It would be good to have an "official" pattern for hooking in a codegen command for serve/build, it seems like a fairly common use case.

**Comment by AgentEnder** [comment]
So the reason for the behavior is that the cache hit you are seeing is for the **_build_** target, not the **_build-base_** target. Since the **_build_** target doesn't have any outputs, Nx just replays the terminal.

For this pattern, a more idiomatic way to express the behavior would be to have a target dependency between build and codegen, such that the codegen task was ran.

**Comment by joshribakoff-sm** [comment]
Makes sense, thanks. 

I tried the `targetDependency` but I need the codegen to run in "watch mode" when I serve the app, which means it will never exit and the serve command will never start up, if I recall correctly

**Comment by joshribakoff-sm** [comment]
@AgentEnder 

> For this pattern, a more idiomatic way to express the behavior would be to have a target dependency between build and codegen, such that the codegen task was ran.

I think the blocker there is that I could not get the codegen to run in watch mode, since a target dependency has to exit before the next command. Any way ya'll can post an example with a codegen working the recommended way (including watch mode in development)?
