### ISSUE TITLE
Migrating from 13.8.1 to 13.9.6 throws `Please update your global install of Nx`

### ISSUE THREAD

**Issue by jaqua** [nrwl/nx#9672]
Updating from 13.8.1 to 13.9.6 didn't throw any errors

```
Running migration 13-9-0-update-decorate-cli
Successfully finished 13-9-0-update-decorate-cli
---------------------------------------------------------
Running migration 13-9-0-replace-tao-with-nx
Successfully finished 13-9-0-replace-tao-with-nx
---------------------------------------------------------
Running migration rename-build-to-webpack
Successfully finished rename-build-to-webpack
---------------------------------------------------------
Running migration rename-execute-to-node
Successfully finished rename-execute-to-node
---------------------------------------------------------
Running migration update-package-to-tsc
Successfully finished update-package-to-tsc
---------------------------------------------------------
```

 but as I want to run any nx command I always get the errors

    Please update your global install of Nx
    - npm install -g nx

The global install of nx is of course correct.

I had to run `npm install -D nx`. Then all `nx serve` commands are working again. But still I do get always the output

    Please update your global install of Nx
    - npm install -g nx

### Environment

   Node : 16.14.0
   OS   : darwin arm64
   npm  : 8.3.1
   
   nx : 13.9.6
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.9.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.9.6
   @nrwl/eslint-plugin-nx : 13.9.6
   @nrwl/express : Not Found
   @nrwl/jest : 13.9.6
   @nrwl/js : 13.9.6
   @nrwl/linter : 13.9.6
   @nrwl/nest : 13.9.6
   @nrwl/next : 13.9.6
   @nrwl/node : 13.9.6
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.9.6
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.9.6
   @nrwl/web : 13.9.6
   @nrwl/workspace : 13.9.6
   typescript : 4.5.4
   rxjs : 7.4.0

**Comment by phaniteja1** [comment]
I am facing the same issue as well. Can someone please post a fix for this. Thanks!

**Comment by AgentEnder** [comment]
Hey, it is correct that the `nx` package should be installed locally now. @FrozenPandaz is investigating why the error message is still showing up in some cases.

**Comment by smasala** [comment]
@AgentEnder thanks! It's a shame that `nx migrate latest` didn't do this and instead bumped the version of `@nrwl/cli` to `13.9.6`

**Comment by AgentEnder** [comment]
One of the migrations was definitely meant to add the dep, not 100% sure why it wouldn't have.

**Comment by smasala** [comment]
The jump was prob to big I guess 🤷‍♂️ The migration scripts run after the migrate latest right?

**Comment by AgentEnder** [comment]
It needs to be listed in `package.json`
