### ISSUE TITLE
open Storybook automatically in the browser

### ISSUE THREAD

**Issue by ofirrifo** [nrwl/nx#9681]
## Current Behavior
I'm using NX with react project and storybook.
When I'm running this command ```nx run project-name:storybook``` I would expected to open the browser automatically
or alternatively use any like given by the storybook options https://storybook.js.org/docs/react/api/cli-options

## Expected Behavior
open Storybook automatically in the browser

## Steps to Reproduce
- Create a new NX react Lib 
- Add storybook to the lib
- Run Storybook

### Environment

 Node : 16.10.0
   OS   : darwin x64
   npm  : 7.10.0
   
   nx : 13.9.4
   @nrwl/angular : undefined
   @nrwl/cypress : 13.9.4
   @nrwl/detox : undefined
   @nrwl/devkit : 13.9.4
   @nrwl/eslint-plugin-nx : 13.9.4
   @nrwl/express : undefined
   @nrwl/jest : 13.9.4
   @nrwl/js : 13.9.4
   @nrwl/linter : 13.9.4
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/nx-plugin : undefined
   @nrwl/react : 13.9.4
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.9.4
   @nrwl/web : 13.9.4
   @nrwl/workspace : 13.9.4
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

**Comment by mandarini** [comment]
Linking this here: https://github.com/nrwl/nx/issues/7531

**Comment by mandarini** [comment]
So, @ofirrifo ! The issue goes a bit deeper than what it seems. To make it work automatically, like Storybook does, it will take some time from us to change some things in the builder, and it's planned to happen sooner than later. 

In the meantime, I will push a fix that will work if you pass `--open=true` or just `--open` when you're running Storybook. Alternatively, in your `project.json`, in your `storybook` target, in the options, you can add `open: true`.

The reason why right now, even if passing `open:true` does not work is that we are force-passing `ci: true`.

**Comment by mandarini** [comment]
Also, @ofirrifo , let me know if using `--open` to make it work should suffice for now and we can close this, until we have the other things lined up.

**Comment by ofirrifo** [comment]
@mandarini
Thanks for the help?
I need to update the nx project to latest for test it ?

**Comment by mandarini** [comment]
@ofirrifo yes!

**Comment by ofirrifo** [comment]
@mandarini Thanks it work perfect :)
