### ISSUE TITLE
[feature reuqest]: @nrwl/builders:node-build stdout formatting

### ISSUE THREAD

**Issue by Toxicable** [nrwl/nx#969]
## Expected Behavior
The stdout should be formatted more prettily

## Current Behavior
The output is not pretty

## Failure Information (for bugs)
n/a

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.
use @nrwl/builders:node-build on any project

here is an example:
The top two are `@angular-devkit/build-angular:browser` followed by `@angular-devkit/build-angular:server`

![image](https://user-images.githubusercontent.com/13490925/50567024-3024e500-0da5-11e9-9317-8a9ecbc83e29.png)

**Comment by FrozenPandaz** [comment]
Closing this issue as this is now properly formatted :tada: :

![image](https://user-images.githubusercontent.com/8104246/78192889-1f02d200-7447-11ea-95b6-5ea8453075b0.png)
