### ISSUE TITLE
Please provide a working examples of how to break up code into libs.

### ISSUE THREAD

**Issue by deanmiller** [nrwl/nx#97]
The idea of Nx sounds very interesting but as someone who cannot spend all day in code, some real-world in-depth, opinionated, best practices examples would be a huge help. I'd even argue that the developer who is able/willing to sift thru GitHub issues to figure out how to use Nx libs to create reusable code sections is in the minority.

Thanks

**Comment by matthewharwood** [comment]
I would argue that nrwl/nx is for everyone interested, the target audience is for large enterprises teams.  Enterprise teams that are indeed, spending all day coding.

Aside, I believe nrwl is always accepting pull requests and therefore, documentation PRs are possible.  Maybe you can describe what you're interested in achieving and I can help a bit?

**Comment by deanmiller** [comment]
I would argue that Nx is for anyone who is interested in code reuse and automated builds across several sites/projects.

To start with I'd settle for and documentation on how to structure the code inside a lib & a link to that documentation on https://nrwl.io/nx/guide-setting-up-ngrx

**Comment by deanmiller** [comment]
I think what I'm trying to say is. Beginners should be within the scope of your official documentation.  Even large corporations have beginners.

Good documentation drives adoption.

**Comment by jschwarty** [comment]
@deanmiller @matthewharwood Thank you for the suggestions and input on the value of Nx for different target audiences. :) We have some additional content in the works, from some more guides to blog posts and podcasts. The community is also starting to create some content about Nx. We would also like to have a demo repo that could showcase Nx in action with multiple apps/libs and examples of using the schematics and leveraging the Nx library code.

Currently we don't have a pipeline for receiving PRs to update the docs.

**Comment by jschwarty** [comment]
We should have a blog post up next week on the [Nrwl blog](https://blog.nrwl.io) about using libs to modularize code. Keep an eye out for that. We also announce Nx stuff on there as well as on Twitter @nrwl_io

**Comment by deanmiller** [comment]
Thanks
