### ISSUE TITLE
[fetture request] @nrwl/builders:node-execute add watch mode flag

### ISSUE THREAD

**Issue by Toxicable** [nrwl/nx#970]
## Expected Behavior
A watch flag that is passed through to `@nrwl/builders:node-build` so can optionally only run once or in watch mode

## Current Behavior
`@nrwl/builders:node-execute` can only run in watch mode

**Comment by hoang-innomizetech** [comment]
I am looking for this feature as well. Basically, we just wanted to run the command one time and exist, watch mode keep the process running forever even we use process.exit(1)

**Comment by jdherder** [comment]
This is also something I'm interested in as well.

**Comment by Cammisuli** [comment]
Resolved in #1534
