### ISSUE TITLE
Problems with generated angular project.json

### ISSUE THREAD

**Issue by alexkimru** [nrwl/nx#9706]
Short app names can produce problems in generated `project.json` file. As I understand, some script just auto replace all matches of app name with path to application directory. For example, if you have application with name `mb`, you get `"maximumError": "1apps/mb"` in project.json, instead of `"maximumError": "1mb"`.

## Current Behavior
`project.json` file is generated with mistakes

## Expected Behavior
`project.json` file should be generated without mistakes

## Steps to Reproduce

- While creating new project, just use short app name, which can be replaced in `project.json`. For example `dev`.
![image](https://user-images.githubusercontent.com/36776954/161959644-86afa7f8-1e22-4df1-b527-9b9db5369dca.png)

- Or in existing project run command:
`nx g app dev`

- Try to start application:
`nx serve dev`
![image](https://user-images.githubusercontent.com/36776954/161960752-b8f4feba-efb7-4a35-afde-cbab2129fe6a.png)

**Comment by Coly010** [comment]
Hey :) Let me look into this. Thanks for all the info provided :)
