### ISSUE TITLE
@nestjs/schematics support 

### ISSUE THREAD

**Issue by xmlking** [nrwl/nx#972]
today we can generate `nestjs` artifacts after `npm i -D @nestjs/schematics` in nx workspace

```bash
ng g @nestjs/schematics:module game --path app --source-root apps/api/src -d
ng g @nestjs/schematics:controller match --path app/game  --source-root apps/api/src -d
ng g @nestjs/schematics:service match --path app/game --source-root apps/api/src -d
ng g @nestjs/schematics:class match/match.entity --path app/game --source-root apps/api/src --spec -d
```

would be nice if we can wrap `nrwl` schematics so that we can shorten those commands (`without passing --source-root,  --path`)  and provide consistent developer experiences 
e.g., 
```
ng g nestjs-module game —project api
ng g nestjs-controller match —project api
ng g nestjs-service match —project api
```

**Comment by FrozenPandaz** [comment]
@kamilmysliwiec

Do you have any ideas how we can make this integration better?

**Comment by kamilmysliwiec** [comment]
I think that both `path` and `source-root` options bring some redundancy and useless complexity here. I'll think about potential solutions to make it cleaner and will post them soon.

**Comment by AliYusuf95** [comment]
I think at least instead of `source-root` we can just point to the project name

**Comment by vsavkin** [comment]
@AliYusuf95 could you expand?

**Comment by rarmatei** [comment]
Related issue: #2959 - it already has some PRs in progress so let's discuss there, closing this one
