### ISSUE TITLE
does not generate stories when components come from an array in routing module

### ISSUE THREAD

**Issue by joaorodr84** [nrwl/nx#9721]
## Current Behavior

nx g @nrwl/angular:stories project-name
...
--> creates only stories file for SimpleComponent

## Expected Behavior
Stories should be created for HasRouteComponent and AlsoHasRouteComponent as well.

## Steps to Reproduce
File: abc-routing.module.ts

```
const routes: Routes = [
  // defines routes for the componts from variable "routedComponents"
]

@NgModule({
  imports: [RouterModule.forChild(routes), NbDialogModule.forChild()],
  exports: [RouterModule],
})
export class AbcRoutingModule {}

export const routedComponents = [
  HasRouteComponent,
  AlsoHasRouteComponent,
];
```

File: abc.module.ts

```
@NgModule({
  declarations: [...routedComponents, SimpleComponent],
})
export class AbcModule {}
```

### Environment

```
Node : 14.17.3
OS   : Win10
npm  : 8.3.0

nx : 13.1.4
"@nrwl/angular": "^13.1.4",
"@nrwl/cli": "13.1.4",
"@nrwl/cypress": "13.1.4",
"@nrwl/eslint-plugin-nx": "13.1.4",
"@nrwl/jest": "13.1.4",
"@nrwl/linter": "13.1.4",
"@nrwl/storybook": "^13.5.3",
"@nrwl/tao": "13.1.4",
"@nrwl/workspace": "13.1.4",
"typescript": "~4.3.5"
```

**Comment by Coly010** [comment]
Thanks for reporting this!

I can reproduce this on latest, I'll investigate 🙂

**Comment by mandarini** [comment]
Linking [this](https://github.com/nrwl/nx/issues/10369) here, just because they seem related (have not looked into any of the two)

**Comment by Coly010** [comment]
Hey @joaorodr84 

Can you try this again with the latest version of Nx? 

`nx migrate latest` or `npx create-nx-workspace@latest` 

I think this could be fixed 🙂
