### ISSUE TITLE
Typing error in Nx: shared/params.d.ts

### ISSUE THREAD

**Issue by kristianmandrup** [nrwl/nx#9722]
## Current Behavior

It fails when trying to build

## Expected Behavior

It does not fail a build

## Steps to Reproduce

```json
  "devDependencies": {
    "@types/jest": "^27.4.1",
    "jest": "^27.5.1",
    "prettier": "^2.6.2",
    "ts-jest": "^27.1.4",
    "tslint": "^6.1.3",
    "tslint-config-prettier": "^1.18.0",
    "typescript": "^4.6.3"
  },
  "dependencies": {
    "@nrwl/devkit": "^13.8.1",
    "@nrwl/workspace": "^13.8.1",
    "@phenomnomnominal/tsquery": "^4.2.0"
  }
```

### Failure Logs

```bash
> nx-code-mods@1.0.0 build
> tsc

node_modules/nx/src/shared/params.d.ts:60:5 - error TS2411: Property ''--'' of type 'Unmatched[] | undefined' is not assignable to 'string' index type 'string | number | boolean | string[] | Unmatched[]'.

60     '--'?: Unmatched[];
       ~~~~


Found 1 error in node_modules/nx/src/shared/params.d.ts:60

npm ERR! code 2
npm ERR! path /Users/kristian/repos/personal/nx-code-ops
npm ERR! command failed
npm ERR! command sh -c npm run build

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kristian/.npm/_logs/2022-04-07T03_16_13_351Z-debug-0.log
```

If I click on the error and go to the file and line `node_modules/nx/src/shared/params.d.ts:60` with the error in question I see the following:

```
export declare type Options = {
    '--'?: Unmatched[];
    [k: string]: string | number | boolean | string[] | Unmatched[];
};
```

<img width="608" alt="image" src="https://user-images.githubusercontent.com/125005/162114113-6db50583-c90b-48f5-b2fa-b08c786d1569.png">

Looks like a typing error in the latest version of Nx (13.9.7)

<img width="269" alt="image" src="https://user-images.githubusercontent.com/125005/162114436-52be567f-4137-4cf0-ac5d-a8a945e5eb71.png">

**Comment by kristianmandrup** [comment]
I move to eslint as I noticed tslint is deprecated (followed "old" guide on setting up npm module with typescript)

```json
  "devDependencies": {
    "@types/jest": "^27.4.1",
    "eslint": "^8.12.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.5.1",
    "prettier": "^2.6.2",
    "ts-jest": "^27.1.4",
    "typescript": "^4.6.3"
  },
  "dependencies": {
    "@nrwl/devkit": "13.9.5",
    "@nrwl/workspace": "13.9.5",
    "@phenomnomnominal/tsquery": "^4.2.0"
  }
```

Project can be found here: https://github.com/kristianmandrup/nx-code-mods

**Comment by kristianmandrup** [comment]
I ended up fixing the issue by ignoring `node_modules` in my eslint config

```json
{
    "extends": ["prettier"],
    "plugins": ["prettier"],
    "rules": {
      "prettier/prettier": ["error"]
    },
    "ignorePatterns": ["node_modules/**/*"]
  }
```

**Comment by FrozenPandaz** [comment]
Thanks for letting us know, we can fix that.

However, I would recommend adding `"skipLibCheck": true` to your `tsconfig.json`. It doesn't really make sense for your build to fail because of invalid typings in a dependency that you can't control. :shrug:
