### ISSUE TITLE
Cannot find module Angular loadChildren() with short library path

### ISSUE THREAD

**Issue by GeofoxCoding** [nrwl/nx#9724]
## Current Behavior

I've created a new fresh workspace @latest which is meant for a demo presentation. I've added a minimalistic Nest.js API and a first Angular client. That worked!

Now I wanted to create an Angular library to move my first routes and components out of the app and into that package.
But if I now try to load my lazy loaded feature module in app-routing.module.ts:

`const routes: Routes = [
    {
        path: 'todo',
        loadChildren: () => import('@wibas/todo-ui-angular/ui-angular.module').then(m => m.UiAngularModule)
    },
`

I receive an error.

## Expected Behavior

The workspace should be able to find the module with @wibas/todo-ui-angular. Other module @wibas/todo-data-access is found correctly.

## Steps to Reproduce

Please find my Repo here:
[Example Repo](https://github.com/GeofoxCoding/nx-module-not-found)

### Failure Logs

Cannot find module '@wibas/todo-ui-angular/ui-angular.module' or its corresponding type declarations.

### Environment
...\NxDemo\wibas>nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : win32 x64
   npm  : 8.5.0

   nx : 13.9.7
   @nrwl/angular : 13.9.7
   @nrwl/cypress : 13.9.7
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.9.7
   @nrwl/eslint-plugin-nx : 13.9.7
   @nrwl/express : Not Found
   @nrwl/jest : 13.9.7
   @nrwl/js : 13.9.7
   @nrwl/linter : 13.9.7
   @nrwl/nest : 13.9.7
   @nrwl/next : Not Found
   @nrwl/node : 13.9.7
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.9.7
   @nrwl/web : Not Found
   @nrwl/workspace : 13.9.7
   typescript : 4.5.5
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:

(node:5276) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at ...\NxDemo\wibas\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by AgentEnder** [comment]
Hey @GeofoxCoding! Based on the import statement it looks like you are trying to perform a deep import to pick up the library? If you've not specifically set them up in tsconfig.base.json, those don't typically work. The recommendation in Nx is to use your libraries index.ts file as a sort of "public api" for your libs, so you'd need to list the module there and import it as 
```typescript
const routes: Routes = [ { path: 'todo', loadChildren: () => import('@wibas/todo-ui-angular').then(m => m.UiAngularModule) }]0
```
