### ISSUE TITLE
Add support for APF 13 exports in @nrwl/angular:ng-packagr-lite

### ISSUE THREAD

**Issue by AndyClausen** [nrwl/nx#9727]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Currently, if you run the `ng-packagr-lite` executor, it doesn't generate entries for the `exports` field in `package.json`. This does not conform to the new APF 13 format, which `ng-packagr` is following.
Interestingly, I found this in the executor code:
![image](https://user-images.githubusercontent.com/16802212/162186044-53978b00-5310-49fe-a501-498fe83c6319.png)
https://github.com/nrwl/nx/blob/b6617105f32ba61e1e40f6ff9f96fc0ba333c7fb/packages/angular/src/executors/ng-packagr-lite/ng-packagr-adjustments/ng-package/entry-point/write-package.transform.ts#L6
So it seems like you're explicitly removing the generated exports, although I didn't find any code for this statement.

## Motivation

I need to export some styles, and am getting errors because of missing exports. But it would also just be best to follow the [APF specs](https://angular.io/guide/angular-package-format).

## Suggested Implementation

However `ng-packagr` does it originally.

## Alternate Implementations

N/A.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

As you've discovered, this is intentional. The `@nrwl/angular:ng-packagr-lite` executor is not meant to be used to publish libraries, it's meant to build buildable libraries. For that reason, it doesn't need to follow the APF and some functionalities of the APF have been stripped out to reduce overhead and speed it up.

Just to confirm, are buildable libraries what you want to use or should they be publishable libraries?

You can always add any exports manually if for any reason is needed. What are you trying to do that requires the `exports` field to be automatically generated on the `package.json`?

**Comment by AndyClausen** [comment]
Hey, thanks for the quick response :)

I am indeed using it for a publishable library. I'll just have to work around it. It seems to have worked with adding the exports manually.

I still do find it odd that it is not aligned with the newest APF, seeing how it's aligned with the older ones. But if that's how it is, then that's how it is.

**Comment by leosvelperez** [comment]
If you're using it for a publishable library, that's the wrong executor to use. You should use the `@nrwl/angular:package` executor instead. That one does follow the APF and is the one meant to be used for publishable libraries. If you generate your libraries as in `nx generate @rnwl/angular:lib lib1 --publishable --importPath=@my-org/lib1` the right executor would be generated in the build target.

As mentioned previously, the `@nrwl/angular:ng-packagr-lite` is not intended to produce publishable outputs. It's for the buildable libraries use case and as such, it's optimized for build speed and not for producing outputs to be distributed. It's not exactly aligned with the older versions of the APF, for example, it doesn't produce the extra bundles the APF defined. It just happens to use `ng-packagr` as a base implementation, but not with the goal of producing APF output.

**Comment by leosvelperez** [comment]
I'm closing this since the doubt is now covered. For future reference the `@nrwl/angular:ng-packagr-lite` executors is for buildable libraries and the `@nrwl/angular:package` executor is for publishable libraries.
