### ISSUE TITLE
Unable to pass node enviroment variables to node-app

### ISSUE THREAD

**Issue by gvsouza** [nrwl/nx#973]
* [x] I am running the latest version
* [x] I checked the documentation and found no answer
* [x] I checked to make sure that this issue has not already been filed
* [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

I want to have an Express App inside the workspace created by Nx. So I created a node-app using the CLI, and was able to get it working so far. The problem is that I am using dotenv to load some variables into process.env. I don't want to use environment.ts files because those files are in version control.

The issue I am facing is that on development using ng serve, I did not figured a way to load enviroment variables into the child process (I see on source that it uses fork).

On production I would just use pm2 or something to load the vars into the node process, or load it from the .env file.

Also, I cannot have it as an asset that is copied over to dist, because on rebuild the dist .env file cannot be overwritten, only if it could have assets setup that is only copied on `ng serve` and not copied on `ng build`

## Current Behavior

Unable to pass process.env variables from ng serve.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create workspace with node-app
2. Use `process.env['SOME_VAR']` inside node-app
3. Try to pass this var to `ng serve your-app`

**Comment by gvsouza** [comment]
I am currently using pm2 to workaround.

**Comment by Toxicable** [comment]
Your environment variables should be read from a .env file.
The .env file you use in dev shouldn't be deployed to production.

Where else would you want these variables to come from?

**Comment by gvsouza** [comment]
I was able to find a correct solution, closing...

**Comment by YonatanKra** [comment]
What is the solution? It doesn't work for me. In my env file I have this:
```
export const environment = {
  production: false
};
```
In my code I try: `console.log(process.env.production)` which return `undefined`.
How did you use environment variables?

**Comment by gvsouza** [comment]
> What is the solution? It doesn't work for me. In my env file I have this:
> 
> ```
> export const environment = {
>   production: false
> };
> ```
> In my code I try: `console.log(process.env.production)` which return `undefined`.
> How did you use environment variables?

I'm not using environment.ts files because my vars are not in version control. I am using dotenv.

**Comment by jmcdo29** [comment]
@gvsouza How did you get dotenv working for you? I tried using it, but my variables aren't being set correctly. I've checked that dotenv is calling the .env file for the current directory, did you have to have some additional step? Thanks

**Comment by myflowpl** [comment]
@jmcdo29 `dotenv` works for me, and the setup is like this:

In my `main.ts` server file I placed this as the first line.
````ts
require('dotenv').config()
````

Optionally, if any problems, for debugging you can put this code:
```ts
const result = require('dotenv').config()
if (result.error) {
  throw result.error
}
console.log(result.parsed)
```

And in your root directory just create `.env` file, the root is the curent working directory I suppose 
```
ORIENTDB_ROOT_PASSWORD="root"
ORIENTDB_HOST="localhost"
ORIENTDB_POR=2424
```

**Comment by gvsouza** [comment]
@Offtree 
> This solution doesn't really seem to work too well with a per application .env file though.
> 
> Anyone come up with anything elegant to deal with that?

What do you mean with "per application"?

**Comment by Offtree** [comment]
If you have multiple services that need their own unique version of the same environment variable is an example of the single root .env file not working.

**Comment by twittwer** [comment]
@Offtree You can also define multiple `.env` files.

https://www.npmjs.com/package/dotenv#path
```ts
require('dotenv').config({ path: '...your .env path...' })
```

Does that help?

**Comment by bunnyvishal6** [comment]
For anyone who is still having the problem, try defining dotenv import in a separate file and import  that file in main.ts as the first line. ES6 imports are hoisted and ran in order of declaration. 

Example
```
// config.ts
import * as dotenv from 'dotenv';
dotenv.config({path: 'path to your env file'});

// main.ts
import './config.ts';
// reset of your code
```

**Comment by chiragj97** [comment]
You must install the dotenv package and require it in your server.js file
1. npm install dotenv
2. require('dotenv').config();
Now you should be able to access the variable mentioned in the '.env' file. Hope this will help

**Comment by omirobarcelo** [comment]
In my case I was trying to set `NODE_ENV` to `test` to use the appropriate env file (I have one for development and another for testing). I found the solution here: https://stackoverflow.com/a/59805161/8526764
