### ISSUE TITLE
nx migrate from 13.9.6 to 13.10.0 missed @nrwl/tao

### ISSUE THREAD

**Issue by fbartho** [nrwl/nx#9732]
## Current Behavior

I used `nx migrate` on my repo for the first time, it appeared to update a bunch of `@nrwl/*` packages plus a few other ones.

## Expected Behavior
I expected there to be no references to `@nrwl/*` packages that pointed at 13.9.6, but there were still references in my yarn.lock

I looked at the package.json settings and realized that @nrwl/tao wasn't updated

## Steps to Reproduce

1. Start with a repo containing at least the following dependencies
```json
{
  "dependencies": {
		"@nrwl/cli": "13.9.6",
		"@nrwl/eslint-plugin-nx": "13.9.6",
		"@nrwl/express": "13.9.6",
		"@nrwl/jest": "13.9.6",
		"@nrwl/linter": "13.9.6",
		"@nrwl/node": "13.9.6",
		"@nrwl/nx-cloud": "13.2.2",
		"@nrwl/tao": "13.9.6",
		"@nrwl/workspace": "13.9.6",
  }
}
```
1. Install them via `yarn install`
1. run `yarn nx migrate` -- notice many packages are updated
1. look at package.json -- notice that all the relevant packages are on 13.10.0 **except** `@nrwl/tao` and `@nrwl/nx-cloud`

### Failure Logs

N/A.

### Environment

NX Report before `nx migrate`:
```
   Node : 16.13.2
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 13.9.6
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.9.6
   @nrwl/eslint-plugin-nx : 13.9.6
   @nrwl/express : 13.9.6
   @nrwl/jest : 13.9.6
   @nrwl/js : 13.9.6
   @nrwl/linter : 13.9.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 13.9.6
   @nrwl/nx-cloud : 13.2.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 13.9.6
   typescript : 4.6.3
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

✨  Done in 0.45s.
```
NX Report post manual fixups:
```
   Node : 16.13.2
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 13.10.0
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.0
   @nrwl/eslint-plugin-nx : 13.10.0
   @nrwl/express : 13.10.0
   @nrwl/jest : 13.10.0
   @nrwl/js : 13.10.0
   @nrwl/linter : 13.10.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 13.10.0
   @nrwl/nx-cloud : 13.2.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 13.10.0
   typescript : 4.6.3
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

✨  Done in 0.75s
```

**Comment by FrozenPandaz** [comment]
Hm, a migration in `13.9.0` removed `@nrwl/tao` in favor of `nx`. If you haven't been running migrations, you might want to fetch earlier migrations and run them as well:

```
nx migrate @nrwl/workspace@latest --from=@nrwl/workspace@13.0.0
```

**Comment by fbartho** [comment]
This was definitely a miss on our part. We didn't know we needed to run migrations when we integrated NX, we thought that was an optional convenience, and this was the first time we really realized it might be necessary.

**Comment by fbartho** [comment]
Do you have an example GitHub Actions workflow that runs on a weekly basis to upgrade NX automatically? I'm worried about Dependabot fighting to upgrade individual packages and us missing that migrations were needed.
