### ISSUE TITLE
Chunks cacheGroups links not included in index.html

### ISSUE THREAD

**Issue by vcardins** [nrwl/nx#9737]
I'm using a custom webpack config where I split the chunks by vendor's group. Everything works fine when I serve the app, however, when I build for production it just doesn't add all the dependencies to the `index.html`.

![2022-04-07 16 22 09](https://user-images.githubusercontent.com/2383329/162337133-106c230d-6c16-4c90-a446-cec5f73a26dc.gif)
```html
...
<body>
	<div id="root"></div>
	<script src="polyfills.a2e606ba856eef9d.esm.js" type="module"></script>
	<script src="main.97287e69e078d055.esm.js" type="module"></script>
</body>
...
```

```
Node : 16.13.2
   OS   : darwin arm64
   yarn : 1.22.18
   
   nx : 13.9.6
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.9.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.9.6
   @nrwl/eslint-plugin-nx : 13.9.6
   @nrwl/express : Not Found
   @nrwl/jest : 13.9.6
   @nrwl/js : 13.9.6
   @nrwl/linter : 13.9.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 13.2.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.9.6
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.9.6
   @nrwl/web : 13.9.6
   @nrwl/workspace : 13.9.6
   typescript : 4.6.3
   rxjs : 6.6.7
```

**Comment by Sh1d0w** [comment]
Have you found any resolution to the issue? Running into the same problem with latest nx

**Comment by KarlPurk** [comment]
I'm also looking for a solution to this problem.

**Comment by Kyzyl-ool** [comment]
Is anybody solved the problem?

**Comment by jaysoo** [comment]
If you set `vendorChunk: true` if your `project.json` for `production` configuration then it will be built as well. The reason it is enabled for dev by default is to avoid rebuilding/linking that chunk unnecessarily during development.
