### ISSUE TITLE
Migration to NX 13: Error [ERR_REQUIRE_ESM]: require() of ES Module Errors in NestJS Server

### ISSUE THREAD

**Issue by ShooterMcgavin** [nrwl/nx#9738]
Hi everyone, 

First of all, just wanted to thank @vsavkin and the NX team for all of your hard work!  NX is an awesome platform.

## Background
We recently migrated two NX monorepos to v13, and both repos essentially the same structure.  One is used to build libraries for building components and publishing libraries to NPM, and the second is the primary client-facing application.  Both repos have an Angular client running on top of a NestJS server.  Until the migration, we were able to create multiple libraries for components, interfaces, enums, etc, publish them to npm, and utilize them in the client-facing application (using the components in the Angular app, and the non-angular elements in Angular and Nest...  it worked really well.)

## Current Behavior
We successfully migrated to v13 in both repos, but I started noticing some strange things...  

If you attempted to reference a class from another library through a barrel file, it would throw the following error: 
**/Users/alphaware/Desktop/Projects/corp/node_modules/@nrwl/node/src/executors/node/node-with-require-overrides.js:16**
**return originalLoader.apply(this, arguments);** 

**Error [ERR_REQUIRE_ESM]: require() of ES Module** **/Users/alphaware/Desktop/Projects/corp/node_modules/@angular/core/fesm2015/core.mjs not supported.  Instead change the require of /Users/alphaware/Desktop/Projects/corp/node_modules/@angular/core/fesm2015/core.mjs to a dynamic import() which is available in all CommonJS modules.**

We’re still able to build and publish the libraries, but when those libraries get pulled into the other application, we get the same sort of error, which crashes the node server in the same way.  I noticed that the file format is now .mjs in the exported library files, and I have a feeling that this has something to do with ESModules being exported from Angular 13, but I'm a bit out of my depth and I'm not sure how to resolve it.

## Expected Behavior
The files generated in the libs should be consumable by the Nest server, or there should be a way to export them in a format that the node server understands (Note: There may be a way to do this, I'm just not familiar with it.). Really I just want to understand what causes this error (and if it's something we can fix, or if it's an incompatibility between the new versions of Angular / Nest that were installed with NX 13.  Is it due to the target/module of the library or the app?  Is it caused by files being referenced in the wrong kind of library?  Etc.)

## Steps to Reproduce
- Spin up a new workspace with the latest version of NX
- Create an Angular client and a Nest Server.
- Create a publishable library that contains some sort of class (like a data model or something that you can create with the "new" command.)
- Attempt to reference that object and create a new instance of it in one of the nest services (note that if you reference it directly, it works, but if you reference it through an index.ts file, it will throw the error above.)
- Publish the library to npm (if you try to pull into another NX 13 node application, it will throw errors as well.)

### Environment
Both repos have the same libraries installed and both have been updated to NX13:
"@angular/animations": "~13.2.0",
"@angular/common": "~13.2.0",
"@angular/compiler": "~13.2.0",
"@angular/core": "~13.2.0",
"@angular/forms": "~13.2.0",
"@angular/platform-browser": "~13.2.0",
"@angular/platform-browser-dynamic": "~13.2.0",
"@angular/router": "~13.2.0",
"@nestjs/common": "^8.0.0",
"@nestjs/core": "^8.0.0",
"@nestjs/platform-express": "^8.0.0",
"@nrwl/angular": "13.9.6",
"@angular-devkit/build-angular": "~13.2.0",
"@angular-eslint/eslint-plugin": "~13.0.1",
"@angular-eslint/eslint-plugin-template": "~13.0.1",
"@angular-eslint/template-parser": "~13.0.1",
"@angular/cli": "~13.2.0",
"@angular/compiler-cli": "~13.2.0",
"@angular/language-service": "~13.2.0",
"nx": "13.9.6",

Thanks in advance for your help!

**Comment by ShooterMcgavin** [comment]
Hope this helps someone...  But I think this is happening because indirectly, the barrel files is referencing something that eventually references a service or a class that contains a reference to @angular/core (which is why the error occurs in node when you use the barrel, but not when you reference a file directly.)

Long story short, if you run into this error with a similar environment, try to isolate the item that causes it and check your related imports to see if the barrel or file has any references to Angular packages.  If it does, you'll have to restructure your libraries so that those files aren't referenced in the same barrel.

**Comment by ShooterMcgavin** [comment]
Still curious if there's a way to export/publish libraries from NX13 in a format that both the new Angular (v13) and Node can consume.  It looks like published packages cause the same error in node (Is this because they are .mjs files?)

**Comment by nartc** [comment]
@ShooterMcgavin Hey there, can I ask what are the content of the "publish libraries"? Are those Angular components? utilities functions? models? etc...

**Comment by nartc** [comment]
@ShooterMcgavin You got it right. Barrel files are fine and should be constrained to use as Public API of a Nx library (aka the only `index.ts` file you should have is the one that gets generated with the library). 

Another thing you could do is to be as granular as possible. Break up `client` library into many different smaller libraries to 100% sure that things related to Angular should/should not be bundled by `ng-packagr`. `ng-packagr` is the library that bundles your Angular libraries and we do not control how it bundles. In Angular 13, they switch to ESM completely, that's why you'd see `.mjs` files. Changing `tsconfig` doesn't do anything as `ng-packagr` does not look at `tsconfig` at all.

Last but not least, you can (and should) leverage Nx Boundary Lint rules to really tie down the relationships between all these components (like Angular libraries, `client`, should only be imported in the Angular apps/libs).

**Comment by ShooterMcgavin** [comment]
Thanks @nartc , I really appreciate your time and this was really helpful!  Is it possible to tag libraries so that they can also be enforced by the NX Boundary Lint rules?  As an example, I'm wondering if we can tag the "client" library so that it can only be used within the client app/libs of the consuming application (or are boundaries limited to the libs within a given repo.)  Thanks again!

**Comment by nartc** [comment]
@ShooterMcgavin Yes, that's the idea. We encourage you to tag your libraries as much and as meaningful as you can. Use multiple dimensions: `scope`, `tag`, `platform`, etc... (these are just names, you can use whatever makes sense for your company/team).

`scope` says “what’s the domain” of this library (`app-one`, `app-two`, `domain-one`, `domain-two` etc...)
`type` says “what type of code is this library” (ui, feature, state, data-access, etc...)
`platform` says “where should this code run” (web, angular, node, java, etc...)

AFAIK, tagging can only be used for libraries that the monorepo is managing. For other linting rules, you can utilize Workspace Lint. I'd highly recommend giving this talk about Workspace Lint a watch https://www.youtube.com/watch?v=tEVNYmJ05Ew

**Comment by ShooterMcgavin** [comment]
Thanks @nartc , I'll definitely take a look!  Have a great weekend.
