### ISSUE TITLE
Broken link / page url has changed?

### ISSUE THREAD

**Issue by neilsoult** [nrwl/nx#9739]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[The page with the broken link](https://nx.dev/micro-frontends/dynamic-module-federation-with-angular)
[Link should be](https://nx.dev/micro-frontends/setup-mfe-with-angular)

### Additional context or description
In the Prerequisites section, where it says:

> This guide follows the previous Angular Micro Frontend guide. It will use the same workspace that was created in that guide. If you have not completed it, you can find that guide [here](https://nx.dev/guides/setup-mfe-with-angular).

the link is https://nx.dev/guides/setup-mfe-with-angular, which redirects to the intro page. The link should be https://nx.dev/micro-frontends/setup-mfe-with-angular.

**Comment by bcabanes** [comment]
Thanks you @neilsoult! 
Fix is on its way 👍
