### ISSUE TITLE
Moving from 13.9.5 to 13.10.0 breaks angular-cli decoration

### ISSUE THREAD

**Issue by julianess** [nrwl/nx#9742]
## Current Behavior
Decorating "ng" from angular-cli works perfectly after "npm i" is done with nx 13.9.5.
Moving to 13.10.0 (doesn't matter with or without nx migrate as there are no tasks for migration) breaks this decoration as the path to the script changed from `require('nx/src/cli/decorate-cli').decorateCli();` to `require('nx/src/adapter/decorate-cli').decorateCli();`.
I've found the new path in a fresh new workspace generated by nx@13.10.0.

## Expected Behavior
When migrating to 13.10.0 this path should be adapted, otherwise the decoration is broken (at least for angular projects).

## Steps to Reproduce
Create a workspace with 13.9.5 (decoration is fine) and move to 13.10.0 (either via nx migrate 13.10.0 or manually). Decoration is now broken when `npm i` is executed.

### Failure Logs
 `NX   Decoration of the Angular CLI did not complete successfully`

### Environment
Windows 10
all nrwl (+nx) packages at 13.10.0

**Comment by Coly010** [comment]
I cannot reproduce this.

I created a workspace at `13.9.5` and can see the decorate angular script points to:
`require('nx/src/cli/decorate-cli').decorateCli();`

Then I do the following:

1. `nx migrate latest`
2. `nx migrate --run-migrations`

And then I can see that the file has been updated to point to:

`require('nx/src/adapter/decorate-cli').decorateCli();`

Are you sure you ran `nx migrate --run-migrations` after running `nx migrate latest`?

Also, we HIGHLY discourage manually updating `@nrwl/` packages. Always use `nx migrate` as we have migrations that run that will fix any breaking changes etc.

**Comment by julianess** [comment]
I did run `nx migrate 13.10.0` which is described in my issue. With "latest" you get 13.10.1 or even newer (which wasn't published at the time of this issue description).
I also could not run `nx migrate --run-migrations` as there were no migrations generated from 13.9.5 to 13.10.0 by using `nx migrate 13.10.0` so no file was generated.
Maybe this was fixed with 13.10.1 but wasn't with initial 13.10.1

**Comment by Coly010** [comment]
Can you try again, running `nx migrate latest`?

**Comment by julianess** [comment]
Using `nx migrate latest` (currently it's using 13.0.1) generates a valid migrations.json which performs the necessary change in angular-cli-decoration. This wasn't the case when migrating to 13.10.0 but seems to be fixed with all other versions. I close this bug.
