### ISSUE TITLE
Target name is required to be `build` to take advantage of nx automation for internal dependency handling

### ISSUE THREAD

**Issue by MaGnaL** [nrwl/nx#9748]
This refers to a comment @FrozenPandaz wrote in #9054:

> The target name should not be required to be `build` or any particular name. Could you please open an issue with the case that you saw?

## Setup
In our project live two publishable angular libraries which depend on each other (`lib1` depends on `lib2`). For some reason we need to run additional actions after the build of `lib1`. That's why we end up having two targets to build `lib1`:

- `build-lib`: uses "@nrwl/angular:package" to actually build the library
- `build`: uses "@nrwl/workspace:run-commands" to run "nx run lib1:build-lib" and some more actions sequentially

`build` is the main target since this ensures that dependencies are build automatically.

This setup doesn't work and `build` fails. It prevents nx from applying some automation during `build-lib` because the actual build target (using "@nrwl/angular:package") is not named `build`.

btw: Changing the setup to have `build-lib` as "dependsOn" of `build` has the same problem.
btw2: I tried using "@nrwl/angular:delegate-build" since it sounds like it would bring a solution for the problem, but couldn't get it to work.

## Current Behavior

Without workarounds in `lib1`s tsconfig and package.json running "nx build lib1" fails.

(Reproduction repo branch: master)

```
nx run lib1:build            

 >  NX   Running target build for project lib1 and 1 task(s) it depends on

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

> nx run lib1:build-lib:production

Building Angular Package

------------------------------------------------------------------------------
Building entry point 'lib1'                                                   
------------------------------------------------------------------------------
× Compiling with Angular sources in Ivy partial compilation mode.
libs/lib2/src/lib/lib2.module.ts:1:1 - error TS6059: File '.../magnal/reproduction-nx-build-target/libs/lib2/src/lib/lib2.module.ngtypecheck.ts' is not under 'rootDir' '...\magnal\reproduction-nx-build-target\libs\lib1\src'. 'rootDir' is expected to contain all source files.

1 import { NgModule } from '@angular/core';
 
libs/lib2/src/index.ts:1:1 - error TS6059: File '.../magnal/reproduction-nx-build-target/libs/lib2/src/index.ngtypecheck.ts' is not under 'rootDir' '...\magnal\rep
roduction-nx-build-target\libs\lib1\src'. 'rootDir' is expected to contain all source files.

1 export * from './lib/lib2.module';
 
libs/lib2/src/index.ts:1:15 - error TS6059: File '.../magnal/reproduction-nx-build-target/libs/lib2/src/lib/lib2.module.ts' is not under 'rootDir' '...\magnal\repr
oduction-nx-build-target\libs\lib1\src'. 'rootDir' is expected to contain all source files.

1 export * from './lib/lib2.module';
                ~~~~~~~~~~~~~~~~~~~
libs/lib1/src/lib/lib1.module.ts:3:26 - error TS6059: File '.../magnal/reproduction-nx-build-target/libs/lib2/src/index.ts' is not under 'rootDir' '...\magnal\repr
oduction-nx-build-target\libs\lib1\src'. 'rootDir' is expected to contain all source files.

3 import {Lib2Module} from 'lib2';
                           ~~~~~~


 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Running target "lib1:build" failed

   Failed tasks:

   - lib1:build-lib:production

   Hint: run the command with --verbose for more details.
```

We can work around that by adding an additional path config to tsconfig.lib.json of `lib1`.

```
    "baseUrl": ".",
    "paths": {
      "lib2": ["../../dist/libs/lib2"]
    }
```

It calms down the build, but has several disadvantages, mostly for devs because tsconfig is not pointing to the sources but to the dist folder and therefore is not able to provide all information to imported code (critical for code refactoring).

Another disadvantage is, that the generated "package.json" in `lib1`s dist folder is missing the dependency to `lib2`. Again, because the target name of the build wasn't `build` but `build-lib`.

(Reproduction repo branch: path-hack)

```
  "name": "lib1",
  "version": "0.0.1",
  "peerDependencies": {
    "@angular/common": "^13.3.0",
    "@angular/core": "^13.3.0"
  },
  "dependencies": {
    "tslib": "^2.3.0"
  },
```

We can work around that as well by adding the dependency manually in the original package.json file of `lib1` but it's not the idea of how nx should work and support here.

(Reproduction repo branch: package-json-hack)

## Expected Behavior
I would expect, that nx' automation regarding local dependencies is not bound to the actual name of a target, but it's executor.

However, if the behavior is indeed intentional, I would expect documentation on how to handle such cases.

## Steps to Reproduce

https://github.com/MaGnaL/reproduction-nx-build-target

See the mentioned branches above.

### Failure Logs

none

### Environment

```
   Node : 12.22.10
   OS   : win32 x64
   yarn : 1.22.17

   nx : 13.10.0
   @nrwl/angular : 13.10.0
   @nrwl/cypress : 13.10.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.0
   @nrwl/eslint-plugin-nx : 13.10.0
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.0
   @nrwl/js : Not Found
   @nrwl/linter : 13.10.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.0
   @nrwl/web : Not Found
   @nrwl/workspace : 13.10.0
   typescript : 4.6.3
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
```

**Comment by P4** [comment]
We encountered the same issue recently in a private repo when I was trying to do a similar thing to one of our libraries. Debugging it using `NX_VERBOSE_LOGGING_PATH_MAPPINGS=true` was showing that a dependency was getting remapped to `dist/` only for the `build` target and not `build-lib`. Eventually I reached a dead end at the following:
https://github.com/nrwl/nx/blob/adb02d2610177c9f8bc6fde2b3b2c808f44392bc/packages/workspace/src/utilities/buildable-libs-utils.ts#L51-L52

https://github.com/nrwl/nx/blob/adb02d2610177c9f8bc6fde2b3b2c808f44392bc/packages/workspace/src/utilities/buildable-libs-utils.ts#L16-L22

Instead of `build` name being hardcoded, it checks if a target with the same name as the current target is present in a dependency. In the above example, running `lib1:build-lib` will check for `lib2:build-lib` and since it's not present, it will get marked as non-buildable and will not be mapped to the compiled version.

I assume this is a bug, since it's not affected by the `dependsOn` configuration but looks like it should, with something like:
```
"build-lib": {
  "dependsOn": [{ projects: "dependencies", target: "build"}]
}
```
forcing Nx to look at `lib2:build` instead of `lib2:build-lib`.

I guess a workaround for now would be to have all the libraries in a repo have a separate `build-lib` target, but since for most of them there would be no additional steps it would result in a lot of unwanted boilerplate.

**Comment by floross** [comment]
I can confirm that this bug is still present. When I try to name the target `prebuild` with the `@nrwl/angular:pacakge` executor the executor does not work anymore and when I revert back the target name as `build`, everything is working fine.
