### ISSUE TITLE
build angular-app and node-app

### ISSUE THREAD

**Issue by GregorBiswanger** [nrwl/nx#975]
I have one question to the deployment with a Angular App in combination with a Node.js App... Should I execute "`ng build --prod --out-dir /server/public && ng build server --prod`" or have nx a another solution?

The debugging of both applications at the same time would also be noble... :)

**Comment by Toxicable** [comment]
Is the goal to have your Nodejs app serve up the Angular app?

If so i'd suggest avoiding that approach; I've found a few issues around tooling combining them for prod and dev.
Instead i'd suggest building the apps separately and on separate hosts, this makes tooling easy with a little bit more config - the frontend needs to know what host the backend sits on

**Comment by GregorBiswanger** [comment]
I have a lot of projects with Nodejs apps that serves Angular apps... what problems did you have with it? Or only with Nx in combination?

**Comment by Toxicable** [comment]
Oh no there's no issues with it serving your frontend that way.

I just prefer the separate approach since it
- Allows you to scale your FE separate from your API if needed
- Tooling is easier since it's 2 distinct build processes (no having to combine the ouput of 2)

**Comment by muradm** [comment]
> The debugging of both applications at the same time would also be noble... :)

This does not make sense. Your angular app is running in browser and node app running on server, meaning that they are two separate processes. When you open DevTools for Chrome for instance, you are attaching to client browser process, when you debug node process (with `--inspect` for instance) you are attaching to server node process.

The only case where it would make sense, if you are using SSR which is rendering your angular application in node process. Then attaching to node process (with `--inspect`) will make both debug any way.
